### PR TITLE
Fix feature switch IL when feature attributes are removed

### LINKED ISSUE #104945: "Optimizing assemblies for size failed" - Core 9 Preview 6 Maui Mac Catalyst Build
### Description

I am trying to build for mac catalyst - this seemed to work in Preview 4 with the same command line, but what I did for that was to clear old preview SDK's out and that fixed it - where as here, all I have is core 8 final and 9 preview 6.

 ILLink : error IL1011: Failed to write 'obj/Release/net9.0-maccatalyst/maccatalyst-x64/linked/System.Private.CoreLib.dll'.
    /Users/mitch/.nuget/packages/microsoft.net.illink.tasks/9.0.0-preview.6.24327.7/build/Microsoft.NET.ILLink.targets(95,5): error NETSDK1144: Optimizing assemblies for size failed.
  AbMobileMaui net9.0-maccatalyst failed with 16 warning(s) (3.8s)

### Steps to Reproduce

I am using this command line:
dotnet publish -f net9.0-maccatalyst -c Release \
    -p:ArchiveOnBuild=true \
    -p:CreatePackage=true \
    -p:EnableCodeSigning=true \
    -p:CodesignKey="Apple Distribution: AlzBetter LLC (8DVSMQ7G8N)" \
    -p:CodesignProvision="MacOS Distribution" \
    -p:CodesignEntitlements="Platforms/MacCatalyst/Entitlements.plist" \
    -p:UseHardenedRuntime=true
    
    
    And here's my CSProj - I could be way off base on how I have things configured, so please feel free to tell me what I might have set up wrong here.
Edit: Attaching CSProj as a file due to formatting.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-preview.4.10690

### Affected platforms

macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by sbomer**
When removing `FeatureSwitchDefinition` and `FeatureGuard` attributes, we need to ensure that the body rewriting logic still respects these attributes even though the rewriting happens after attribute removal. Caching the substituted constant value fixes this.

More detail:

When feature switches or feature guards are substituted with a constant, the IL rewriting of the feature property happens after SweepStep, during CodeRewriterStep. At this point, any attributes marked for removal by RemoveAttributeInstancesAttribute have already been swept. When removing `FeatureSwitchDefinitionAttribute` and `FeatureGuardAttribute`, as we do with AggressiveAttributeTrimming, this means that CodeRewriterStep fails to substitute a constant for attributed feature check or feature guard properties.

Normally, the attributed feature properties would be removed entirely when substituted, so CodeRewriterStep wouldn't even visit the property. However, it's possible that the caller of the property was a `copy` assembly where the callsite can't be rewritten to return a constant.

When this happens, we can end up with a property that's not stubbed out during CodeRewriterStep, even though we didn't mark a callee of the property (because MarkStep did treat the property as a constant and didn't mark its instructions). When trying to write out the property's IL this results in a failure because we see a reference to a method that was removed.

Fixes https://github.com/dotnet/runtime/issues/104945

### CODE REVIEW

File: src/tools/illink/src/linker/Linker/MemberActionStore.cs [hunk 1]
```diff
@@ -68,6 +70,9 @@ public bool TryGetMethodStubValue (MethodDefinition method, out object? value)
 
 		internal bool TryGetFeatureCheckValue (MethodDefinition method, out bool value)
```
Comment (vitek-karas) [inline src/tools/illink/src/linker/Linker/MemberActionStore.cs:71]: How do we guarantee this will be called at least once on a given method before the `CodeRewriterStep`?
If I understand the repro for this problem, the callsites in trimmed assemblies are all removed due to branch removal, so we won't mark them and thus won't call this either. This leaves `copy` assemblies and their references. I don't remember exactly what type of processing we do there - if we end up calling `MarkMethod` then this should be fine.

I guess the reason why this works is:
If the `CoreRewriterStep` gets to process a method, that method had to be marked (otherwise it would have been removed) and thus `MarkMethod` ended up calling this `TryGetFeatureCheckValue` and thus populate the cache within.

I must admit this makes me a bit nervous - it feels pretty fragile. Maybe we should make the link from MarkMethod to this a bit more obvious - currently it goes through GetMethodAction which doesn't "seem" like being related to this that much.

**Review by vitek-karas — APPROVED** [review]
Thanks!
