### PR TITLE
[browser][MT] Handling blocking wait

### LINKED ISSUE #44622: [browser][MT] System.Threading.Tasks.Task.SpinThenBlockingWait(...) uses non supported API
Browser compat: System.Threading.Tasks.Task.SpinThenBlockingWait(...) references `ManualResetEventSlim.Wait(..)` not supported on browser

_we need browser-specific implementation. Please create an issue and link if from here. I'm curious how this works today, I guess we are lucky and hit SpinWait all the time_

@lewing

_Originally posted by @marek-safar in https://github.com/dotnet/runtime/pull/43363#discussion_r522485542_

### LINKED ISSUE #97914: [browser][MT] WebWorkerTest.WaitAssertsOnJSInteropThreads
### Error Blob

```json
{
  "ErrorMessage": "[FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.WaitAssertsOnJSInteropThreads",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=550368
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97845-merge-1d5bab7ff8dd450fac/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.f8349007.log?helixlogtype=result)
```
[02:57:19] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.WaitAssertsOnJSInteropThreads(executor: JSWebWorker)
[02:57:19] info: [0x0452ffe8-jsww 02:57:19.193] MONO_WASM: forceDisposeProxies done: 0 imports, 0 exports, 0 GCHandles, 0 JSHandles.
[02:57:19] fail: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.WaitAssertsOnJSInteropThreads(executor: JSWebWorker)
[02:57:19] info: Assert.NotNull() Failure: Value is null
[02:57:19] info:    at System.Runtime.InteropServices.JavaScript.Tests.Executor.AssertBlockingWait(Exception exception)
[02:57:19] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.<>c__DisplayClass16_0.<WaitAssertsOnJSInteropThreads>b__0()
[02:57:19] info:    at System.Runtime.InteropServices.JavaScript.Tests.Executor.<>c__DisplayClass7_0.<Execute>g__wrapExecute|0()
[02:57:19] info:    at System.Runtime.InteropServices.JavaScript.JSWebWorker.<>c__DisplayClass5_0.<<RunAsync>b__0>d.MoveNext()
[02:57:19] info: --- End of stack trace from previous location ---
[02:57:19] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.WaitAssertsOnJSInteropThreads(Executor executor)
[02:57:19] info: --- End of stack trace from previous location ---
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=550368
**Error message validated:** `[FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.WaitAssertsOnJSInteropThreads`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/3/2024 8:07:36 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[601538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=601538)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=601538&view=ms.vss-test-web.build-test-results-tab&runId=14601066&resultId=187693)|dotnet/runtime#99671|
|[599402](https://dev.azure.com/dnceng-public/public/_build/results?buildId=599402)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=599402&view=ms.vss-test-web.build-test-results-tab&runId=14529824&resultId=100746)|dotnet/runtime#99595|
|[597331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=597331)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=597331&view=ms.vss-test-web.build-test-results-tab&runId=14473206&resultId=187271)|dotnet/runtime#98802|
|[594953](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594953)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594953&view=ms.vss-test-web.build-test-results-tab&runId=14401684&resultId=187929)|dotnet/runtime#98492|
|[593365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593365)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=593365&view=ms.vss-test-web.build-test-results-tab&runId=14347914&resultId=187301)|dotnet/runtime#98559|
|[592874](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592874)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592874&view=ms.vss-test-web.build-test-results-tab&runId=14330026&resultId=186892)|dotnet/runtime#99400|
|[592800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592800)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592800&view=ms.vss-test-web.build-test-results-tab&runId=14328246&resultId=181897)|dotnet/runtime#98802|
|[591885](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591885)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.BackgroundExec.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591885&view=ms.vss-test-web.build-test-results-tab&runId=14298744&resultId=187154)|dotnet/runtime#99343|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|8|

### LINKED ISSUE #98804: [browser][MT] PlatformNotSupportedException Blocking wait is not supported on the JS interop threads
### Error Blob

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "System\.PlatformNotSupportedException ?: Blocking wait is not supported on the JS interop threads",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98118-merge-d3bb697342374ee0a2/WasmTestOnBrowser-System.Net.Http.Functional.Tests/1/console.7d02ff39.log?helixlogtype=result)
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=574940
```
[22:24:46] info: [FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.ReadAsStreamAsync_EmptyResponseBody_HandlerProducesWellBehavedResponseStream
[22:24:46] info: System.PlatformNotSupportedException : Blocking wait is not supported on the JS interop threads.
[22:24:46] info:    at System.Threading.Thread.AssureBlockingPossible()
[22:24:46] info:    at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[22:24:46] info:    at System.Threading.SemaphoreSlim.Wait()
[22:24:46] info:    at System.IO.Stream.BeginReadInternal(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state, Boolean serializeAsynchronously, Boolean apm)
[22:24:46] info:    at System.IO.Stream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
[22:24:46] info:    at System.Threading.Tasks.TaskFactory`1[[System.Int32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].FromAsyncImpl[Byte[],Int32,Int32](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, Byte[] arg1, Int32 arg2, Int32 arg3, Object state, TaskCreationOptions creationOptions)
[22:24:46] info:    at System.Threading.Tasks.TaskFactory.FromAsync[Byte[],Int32,Int32,Int32](Func`6 beginMethod, Func`2 endMethod, Byte[] arg1, Int32 arg2, Int32 arg3, Object state)
[22:24:46] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<ReadAsStreamAsync_EmptyResponseBody_HandlerProducesWellBehavedResponseStream>b__29_0(Uri uri)
[22:24:46] info:    at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
[22:24:46] info: --- End of stack trace from previous location ---
[22:24:46] info:    at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
[22:24:46] info:    at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass6_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
[22:24:46] info: --- End of stack trace from previous location ---
[22:24:46] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[22:24:46] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.ReadAsStreamAsync_EmptyResponseBody_HandlerProducesWellBehavedResponseStream()
[22:24:46] info: --- End of stack trace from previous location ---
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Provided build not found. Provide a valid build in the "**Build:** :mag_right:" line.
**Validation performed at:** 4/15/2024 7:27:53 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[643881](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643881)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643881&view=ms.vss-test-web.build-test-results-tab&runId=15890716&resultId=186742)|dotnet/runtime#101056|
|[644056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644056)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644056&view=ms.vss-test-web.build-test-results-tab&runId=15888292&resultId=100604)|dotnet/runtime#101038|
|[643951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643951)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643951&view=ms.vss-test-web.build-test-results-tab&runId=15886098&resultId=186742)|dotnet/runtime#100765|
|[643885](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643885)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643885&view=ms.vss-test-web.build-test-results-tab&runId=15883368&resultId=100167)|dotnet/runtime#100898|
|[643867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643867)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643867&view=ms.vss-test-web.build-test-results-tab&runId=15883472&resultId=186785)|dotnet/runtime#100266|
|[643892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643892)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643892&view=ms.vss-test-web.build-test-results-tab&runId=15883710&resultId=100604)|dotnet/runtime#100949|
|[643833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643833)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643833&view=ms.vss-test-web.build-test-results-tab&runId=15881900&resultId=100604)|dotnet/runtime#100947|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|7|7|

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### PR DESCRIPTION
**Pull request by pavelsavara**
- simplify configuration of MT handling of blocking `.Wait`
     - removed `MainThreadingMode` and `JSThreadInteropMode` configuration
 - new `Thread.WarnOnBlockingWaitOnJSInteropThread`
 - MT unit tests now use `ThrowWhenBlockingWait` mode

### `JSThreadBlockingMode` now could have following values

`PreventSynchronousJSExport` - default
* Prevents synchronous `JSExport` from being called from JavaScript code in UI thread.
* On `JSWebWorker` synchronous `JSExport` always works.
* On `JSWebWorker` blocking .Wait always warns.
* This is the default mode.

`ThrowWhenBlockingWait`
* Allows synchronous `JSExport` to be called from JavaScript code also in UI thread.
* Inside of that call blocking `.Wait` throws PNSE.
* Inside of that call nested call back to synchronous `JSImport` throws PNSE (because it would deadlock otherwise in 100% cases).
* On `JSWebWorker` synchronous `JSExport` always works.
* On `JSWebWorker` blocking `.Wait` always throws PNSE.

`WarnWhenBlockingWait`
* Allows synchronous `JSExport` to be called from JavaScript code also in UI thread.
* Inside of that call blocking `.Wait` warns.
* Inside of that call nested call back to synchronous `JSImport` throws PNSE (because it would deadlock otherwise in 100% cases).
* On `JSWebWorker` synchronous `JSExport` always works.
* On `JSWebWorker` blocking `.Wait` always warns.

`DangerousAllowBlockingWait`
* Allows synchronous `JSExport` to be called from JavaScript code, and allows managed code to use blocking `.Wait`
* `.Wait` on `Promise`/`Task` chains could lead to deadlock because JS event loop is not processed and it can't resolve JS promises.
* This mode is dangerous and not supported.
* Allows synchronous `JSExport` to be called from JavaScript code also in main thread.
* Inside of that call nested call back to synchronous `JSImport` throws PNSE (because it would deadlock otherwise in 100% cases).

Contributes to https://github.com/dotnet/runtime/issues/76958
Contributes to https://github.com/dotnet/runtime/issues/98652
Contributes to https://github.com/dotnet/runtime/issues/99951

Fixes https://github.com/dotnet/runtime/issues/98804
Fixes https://github.com/dotnet/runtime/issues/97914
Fixes https://github.com/dotnet/runtime/issues/44622

More scenarios: https://github.com/dotnet/runtime/issues/93603#issuecomment-1766601298

### CODE REVIEW

File: src/mono/browser/runtime/types/internal.ts [hunk 1]
```diff
@@ -569,36 +567,37 @@ export interface MonoThreadMessage {
...
-    // allow non-re-entrant synchronous blocking calls to and from JS on JSWebWorker on threads with JS interop, like JSWebWorker and Main thread.
-    // calling synchronous JSImport on thread pool or new threads is allowed.
-    SimpleSynchronousJSInterop = 1,
+    /**
+     * Prevents synchronous JSExport from being called from JavaScript code in UI thread.
+     * On JSWebWorker synchronous JSExport always works.
+     * On JSWebWorker blocking .Wait always warns.
+     * This is the default mode.
+     */
+    PreventSynchronousJSExport = 0,
```
Comment (maraf) [inline src/mono/browser/runtime/types/internal.ts:578]: We should use string values instead of numbers in public API, same as for `GlobalizationMode`

File: src/libraries/System.Runtime.InteropServices.JavaScript/src/System/Runtime/InteropServices/JavaScript/JSSynchronizationContext.cs [hunk 2]
```diff
@@ -50,9 +50,18 @@ public static unsafe JSSynchronizationContext InstallWebWorkerInterop(bool isMai
             ctx.previousSynchronizationContext = SynchronizationContext.Current;
             SynchronizationContext.SetSynchronizationContext(ctx);
 
-            if (JSProxyContext.ThreadBlockingMode == JSHostImplementation.JSThreadBlockingMode.NoBlockingWait)
+            if (!isMainThread)
             {
-                Thread.ThrowOnBlockingWaitOnJSInteropThread = true;
+                if (JSProxyContext.ThreadBlockingMode == JSHostImplementation.JSThreadBlockingMode.ThrowWhenBlockingWait)
```
Comment (maraf) [inline src/libraries/System.Runtime.InteropServices.JavaScript/src/System/Runtime/InteropServices/JavaScript/JSSynchronizationContext.cs:55]: Why don't we unset `ThrowOnBlockingWaitOnJSInteropThread` and `WarnOnBlockingWaitOnJSInteropThread` the same as for main thread? Why do we need to unset them for main thread?

File: src/mono/browser/runtime/types/internal.ts (hunk 1 above)
Comment (pavelsavara) [reply src/mono/browser/runtime/types/internal.ts:578]: We need it as number during early start and on managed side. For config, I agree, good point.

File: src/libraries/System.Runtime.InteropServices.JavaScript/src/System/Runtime/InteropServices/JavaScript/JSSynchronizationContext.cs (hunk 2 above)
Comment (maraf) [reply src/libraries/System.Runtime.InteropServices.JavaScript/src/System/Runtime/InteropServices/JavaScript/JSSynchronizationContext.cs:55]: Thanks!

**Review by maraf — APPROVED** [review]

**Comment by pavelsavara** [comment]
All the CI failures are https://github.com/dotnet/runtime/issues/99888
