### PR TITLE
Fix a deadlock in NonGC + Profiler API

### LINKED ISSUE #90830: ProfilingAPI: `ICorProfilerInfo14::GetNonGCHeapBounds` deadlock on .NET 8.0-preview7
Hi there,
We started to use `ICorProfilerInfo14::GetNonGCHeapBounds` and got permanent red tests on:
- Windows ARM64 for some kinds of x64 and x86 processes
- macOS ARM64 for some kinds of x64 processes

I think the deadlock appears because we call `ICorProfilerInfo14::GetNonGCHeapBounds` during the initialization of the execution engine.

Stack trace:
```
0:000:ARM64EC> ~* k

.  0  Id: 44b8.57b8 Suspend: 1 Teb: 000000e3`ff155000 Unfrozen
 #   Arch   Child-SP          RetAddr               Call Site
00  ARM64EC 000000e3`fefde6f0 00007ffd`12e65334     ntdll!#NtWaitForSingleObject+0x14
01  ARM64EC 000000e3`fefde700 00007ffd`12f93444     KERNELBASE!WaitForSingleObjectEx+0x84
02  ARM64EC 000000e3`fefde790 00007ffc`97779e4d     KERNELBASE!$ientry_thunk$cdecl$i8$i8+0x24
03    AMD64 (Inline Function) --------`--------     coreclr!GCEvent::Impl::Wait+0xc [D:\a\_work\1\s\src\coreclr\gc\windows\gcenv.windows.cpp @ 1372] 
04    AMD64 (Inline Function) --------`--------     coreclr!GCEvent::Wait+0x13 [D:\a\_work\1\s\src\coreclr\gc\windows\gcenv.windows.cpp @ 1422] 
05    AMD64 000000e3`fefde840 00007ffc`979078ea     coreclr!WKS::gc_heap::wait_for_gc_done+0x29 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 14543] 
06    AMD64 (Inline Function) --------`--------     coreclr!WKS::WaitLonger+0x44 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 1635] 
07    AMD64 (Inline Function) --------`--------     coreclr!WKS::enter_spin_lock+0xa6e85 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 1690] 
08    AMD64 000000e3`fefde870 00007ffc`97860a17     coreclr!WKS::gc_heap::insert_ro_segment+0xa6eba [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 9868] 
09    AMD64 000000e3`fefde8c0 00007ffc`97864178     coreclr!WKS::GCHeap::RegisterFrozenSegment+0x87 [D:\a\_work\1\s\src\coreclr\gc\gcee.cpp @ 466] 
0a    AMD64 000000e3`fefde8f0 00007ffc`9778c21f     coreclr!FrozenObjectSegment::FrozenObjectSegment+0xb0 [D:\a\_work\1\s\src\coreclr\vm\frozenobjectheap.cpp @ 149] 
0b    AMD64 000000e3`fefde950 00007ffc`9778bc46     coreclr!FrozenObjectHeapManager::TryAllocateObject+0x15f [D:\a\_work\1\s\src\coreclr\vm\frozenobjectheap.cpp @ 66] 
0c    AMD64 (Inline Function) --------`--------     coreclr!AllocateString+0x4d [D:\a\_work\1\s\src\coreclr\vm\gchelpers.cpp @ 971] 
0d    AMD64 (Inline Function) --------`--------     coreclr!AllocateStringObject+0x54 [D:\a\_work\1\s\src\coreclr\vm\stringliteralmap.cpp @ 472] 
0e    AMD64 000000e3`fefde9d0 00007ffc`9778ba9d     coreclr!GlobalStringLiteralMap::AddStringLiteral+0x76 [D:\a\_work\1\s\src\coreclr\vm\stringliteralmap.cpp @ 503] 
0f    AMD64 (Inline Function) --------`--------     coreclr!GlobalStringLiteralMap::GetStringLiteral+0x5a [D:\a\_work\1\s\src\coreclr\vm\stringliteralmap.cpp @ 396] 
10    AMD64 000000e3`fefdeae0 00007ffc`977cbb22     coreclr!StringLiteralMap::GetStringLiteral+0xdd [D:\a\_work\1\s\src\coreclr\vm\stringliteralmap.cpp @ 170] 
11    AMD64 000000e3`fefdeb40 00007ffc`977cbaa8     coreclr!LoaderAllocator::GetStringObjRefPtrFromUnicodeString+0x4e [D:\a\_work\1\s\src\coreclr\vm\loaderallocator.cpp @ 1751] 
12    AMD64 000000e3`fefdeb80 00007ffc`977cba5d     coreclr!StringObject::InitEmptyStringRefPtr+0x48 [D:\a\_work\1\s\src\coreclr\vm\object.cpp @ 859] 
13    AMD64 000000e3`fefdebd0 00007ffc`977cb9f5     coreclr!StringObject::GetEmptyString+0x1d [D:\a\_work\1\s\src\coreclr\vm\object.h @ 989] 
14    AMD64 000000e3`fefdec00 00007ffc`97812877     coreclr!AppDomain::SetupSharedStatics+0x51 [D:\a\_work\1\s\src\coreclr\vm\appdomain.cpp @ 3059] 
15    AMD64 000000e3`fefdec40 00007ffc`9783c5a3     coreclr!EEStartupHelper+0x697 [D:\a\_work\1\s\src\coreclr\vm\ceemain.cpp @ 933] 
16    AMD64 000000e3`fefdee60 00007ffc`9783c54a     coreclr!EEStartup+0x27 [D:\a\_work\1\s\src\coreclr\vm\ceemain.cpp @ 1051] 
17    AMD64 000000e3`fefdeeb0 00007ffc`9783c488     coreclr!EnsureEEStarted+0x92 [D:\a\_work\1\s\src\coreclr\vm\ceemain.cpp @ 300] 
18    AMD64 000000e3`fefdef00 00007ffc`9784d040     coreclr!CorHost2::Start+0x58 [D:\a\_work\1\s\src\coreclr\vm\corhost.cpp @ 101] 
19    AMD64 000000e3`fefdef40 00007ffc`c47335b0     coreclr!coreclr_initialize+0x180 [D:\a\_work\1\s\src\coreclr\dlls\mscoree\exports.cpp @ 320] 
1a    AMD64 000000e3`fefdf010 00007ffc`c4752068     hostpolicy!coreclr_t::create+0x2b0 [D:\a\_work\1\s\src\native\corehost\hostpolicy\coreclr.cpp @ 73] 
1b    AMD64 000000e3`fefdf190 00007ffc`c4753c37     hostpolicy!`anonymous namespace'::create_coreclr+0x158 [D:\a\_work\1\s\src\native\corehost\hostpolicy\hostpolicy.cpp @ 82] 
1c    AMD64 000000e3`fefdf1f0 00007ffc`c5a2b5ac     hostpolicy!corehost_main+0x187 [D:\a\_work\1\s\src\native\corehost\hostpolicy\hostpolicy.cpp @ 427] 
1d    AMD64 000000e3`fefdf2f0 00007ffc`c5a2e166     hostfxr!execute_app+0x2ac [D:\a\_work\1\s\src\native\corehost\fxr\fx_muxer.cpp @ 145] 
1e    AMD64 000000e3`fefdf3f0 00007ffc`c5a30316     hostfxr!`anonymous namespace'::read_config_and_execute+0xa6 [D:\a\_work\1\s\src\native\corehost\fxr\fx_muxer.cpp @ 532] 
1f    AMD64 000000e3`fefdf4e0 00007ffc`c5a2e744     hostfxr!fx_muxer_t::handle_exec_host_command+0x166 [D:\a\_work\1\s\src\native\corehost\fxr\fx_muxer.cpp @ 1007] 
20    AMD64 000000e3`fefdf590 00007ffc`c5a28533     hostfxr!fx_muxer_t::execute+0x494 [D:\a\_work\1\s\src\native\corehost\fxr\fx_muxer.cpp @ 578] 
21    AMD64 000000e3`fefdf6d0 00007ff6`51ec3399     hostfxr!hostfxr_main_startupinfo+0xb3 [D:\a\_work\1\s\src\native\corehost\fxr\hostfxr.cpp @ 61] 
22    AMD64 000000e3`fefdf7d0 00007ff6`51ec3706     DetectMemoryLeak!exe_start+0x859 [D:\a\_work\1\s\src\native\corehost\corehost.cpp @ 242] 
23    AMD64 000000e3`fefdf9a0 00007ff6`51ec4c58     DetectMemoryLeak!wmain+0xa6 [D:\a\_work\1\s\src\native\corehost\corehost.cpp @ 313] 
24    AMD64 (Inline Function) --------`--------     DetectMemoryLeak!invoke_main+0x22 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 90] 
25    AMD64 000000e3`fefdf9d0 00007ffd`1535f0cc     DetectMemoryLeak!__scrt_common_main_seh+0x10c [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
26  ARM64EC 000000e3`fefdfa10 00007ffd`152f6020     KERNEL32!$iexit_thunk$cdecl$i8$i8+0x1c
27  ARM64EC 000000e3`fefdfa40 00007ffd`17188308     KERNEL32!#BaseThreadInitThunk+0x30
28  ARM64EC 000000e3`fefdfa50 00000000`00000000     ntdll!#RtlUserThreadStart+0x48

  15  Id: 44b8.5344 Suspend: 1 Teb: 000000e3`ff173000 Unfrozen
 #   Arch   Child-SP          RetAddr               Call Site
00  ARM64EC 000000e3`822fe530 00007ffd`171cd188     ntdll!#NtWaitForAlertByThreadId+0x14
01  ARM64EC 000000e3`822fe540 00007ffd`171cc5e8     ntdll!#RtlpWaitOnCriticalSection+0x390
02  ARM64EC 000000e3`822fe650 00007ffd`171ca580     ntdll!#RtlpEnterCriticalSectionContended+0x308
03  ARM64EC 000000e3`822fe6d0 00007ffd`1727e654     ntdll!#RtlEnterCriticalSection+0x70
04  ARM64EC 000000e3`822fe6f0 00007ffc`9776b55a     ntdll!$ientry_thunk$cdecl$i8$i8+0x24
05    AMD64 000000e3`822fe7a0 00007ffc`979b04e4     coreclr!CrstBase::Enter+0x5a [D:\a\_work\1\s\src\coreclr\vm\crst.cpp @ 328] 
06    AMD64 (Inline Function) --------`--------     coreclr!CrstBase::AcquireLock+0x8 [D:\a\_work\1\s\src\coreclr\vm\crst.h @ 187] 
07    AMD64 (Inline Function) --------`--------     coreclr!CrstBase::CrstHolder::{ctor}+0xd [D:\a\_work\1\s\src\coreclr\vm\crst.h @ 378] 
08    AMD64 000000e3`822fe7d0 00007ffc`83bf8a97     coreclr!ProfToEEInterfaceImpl::GetNonGCHeapBounds+0x44 [D:\a\_work\1\s\src\coreclr\vm\proftoeeinterfaceimpl.cpp @ 7676] 
09    AMD64 000000e3`822fe810 00007ffc`83bf56f6     JetBrains_Profiler_Core!jbprof::GraphGatherer::get_non_gc_heaps+0xb7 [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\profilers\memory\GraphGatherer.cpp @ 174] 
0a    AMD64 000000e3`822feb70 00007ffc`83c90510     JetBrains_Profiler_Core!jbprof::GraphGatherer::WriteGarbageCollectionStarted+0x206 [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\profilers\memory\GraphGatherer.cpp @ 256] 
0b    AMD64 000000e3`822fee20 00007ffc`83c94f46     JetBrains_Profiler_Core!`jbprof::memory_profiler::GarbageCollectionStarted'::`10'::<lambda_2>::operator()+0x5b0 [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\profilers\memory\memory_profiler.gc.cpp @ 341] 
0c    AMD64 000000e3`822ff010 00007ffc`83c8d786     JetBrains_Profiler_Core!jbprof::do_noexcept_log<`jbprof::memory_profiler::GarbageCollectionStarted'::`10'::<lambda_2>,`jbprof::memory_profiler::GarbageCollectionStarted'::`10'::<lambda_3> >+0x26 [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\utility\do_noexcept_log.hpp @ 21] 
0d    AMD64 000000e3`822ff040 00007ffc`9796f587     JetBrains_Profiler_Core!jbprof::memory_profiler::GarbageCollectionStarted+0x2d6 [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\profilers\memory\memory_profiler.gc.cpp @ 342] 
0e    AMD64 000000e3`822ff170 00007ffc`979a694b     coreclr!EEToProfInterfaceImpl::GarbageCollectionStarted+0x7f [D:\a\_work\1\s\src\coreclr\vm\eetoprofinterfaceimpl.cpp @ 5866] 
0f    AMD64 000000e3`822ff1c0 00007ffc`978c5207     coreclr!ProfControlBlock::DoProfilerCallbackHelper<int (__cdecl*)(ProfilerInfo *),long (__cdecl*)(EEToProfInterfaceImpl *,int,int * const,enum __MIDL___MIDL_itf_corprof_0000_0001_0006),int,int *,enum __MIDL___MIDL_itf_corprof_0000_0001_0006>+0x3f [D:\a\_work\1\s\src\coreclr\inc\profilepriv.h @ 284] 
10    AMD64 (Inline Function) --------`--------     coreclr!ProfControlBlock::DoOneProfilerIteration+0x5e [D:\a\_work\1\s\src\coreclr\inc\profilepriv.h @ 199] 
11    AMD64 (Inline Function) --------`--------     coreclr!ProfControlBlock::IterateProfilers+0x5e [D:\a\_work\1\s\src\coreclr\inc\profilepriv.h @ 207] 
12    AMD64 (Inline Function) --------`--------     coreclr!ProfControlBlock::DoProfilerCallback+0x6c [D:\a\_work\1\s\src\coreclr\inc\profilepriv.h @ 295] 
13    AMD64 (Inline Function) --------`--------     coreclr!ProfControlBlock::GarbageCollectionStarted+0x6c [D:\a\_work\1\s\src\coreclr\inc\profilepriv.inl @ 1656] 
14    AMD64 000000e3`822ff200 00007ffc`9779fc49     coreclr!GarbageCollectionStartedCallback+0x12555f [D:\a\_work\1\s\src\coreclr\vm\proftoeeinterfaceimpl.cpp @ 680] 
15    AMD64 000000e3`822ff2a0 00007ffc`9779f4d0     coreclr!GCToEEInterface::DiagGCStart+0x1d [D:\a\_work\1\s\src\coreclr\vm\gcenv.ee.cpp @ 771] 
16    AMD64 000000e3`822ff300 00007ffc`977a1cf9     coreclr!WKS::gc_heap::garbage_collect+0x16c [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 23758] 
17    AMD64 000000e3`822ff350 00007ffc`97a237b9     coreclr!WKS::GCHeap::GarbageCollectGeneration+0x141 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 50081] 
18    AMD64 000000e3`822ff3a0 00007ffc`979d476e     coreclr!WKS::GCHeap::GarbageCollect+0xc9 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 49252] 
19    AMD64 000000e3`822ff3e0 00007ffc`979ab82f     coreclr!ETW::GCLog::ForceGCForDiagnostics+0xc6 [D:\a\_work\1\s\src\coreclr\vm\eventtrace_gcheap.cpp @ 492] 
1a    AMD64 000000e3`822ff4b0 00007ffc`83c6c9a4     coreclr!ProfToEEInterfaceImpl::ForceGC+0x7f [D:\a\_work\1\s\src\coreclr\vm\proftoeeinterfaceimpl.cpp @ 4686] 
1b    AMD64 000000e3`822ff4e0 00007ffc`83c6d8eb     JetBrains_Profiler_Core!jbprof::gc_command_queue::thread_data::force_gc_thread+0x264 [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\profilers\memory\gc_command_queue.cpp @ 367] 
1c    AMD64 000000e3`822ff730 00007ffc`83c71996     JetBrains_Profiler_Core!`jbprof::gc_command_queue::raw_force_gc_thread'::`2'::<lambda_1>::operator()+0xab [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\profilers\memory\gc_command_queue.cpp @ 303] 
1d    AMD64 000000e3`822ff7c0 00007ffc`83c7195b     JetBrains_Profiler_Core!jbprof::do_noexcept_log<`jbprof::gc_command_queue::raw_force_gc_thread'::`2'::<lambda_1>,`jbprof::do_noexcept_log<`jbprof::gc_command_queue::raw_force_gc_thread'::`2'::<lambda_1> >'::`2'::<lambda_1> >+0x26 [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\utility\do_noexcept_log.hpp @ 21] 
1e    AMD64 000000e3`822ff7f0 00007ffc`83c6c4ed     JetBrains_Profiler_Core!jbprof::do_noexcept_log<`jbprof::gc_command_queue::raw_force_gc_thread'::`2'::<lambda_1> >+0x2b [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\utility\do_noexcept_log.hpp @ 34] 
1f    AMD64 000000e3`822ff830 00007ffd`1535f0cc     JetBrains_Profiler_Core!jbprof::gc_command_queue::raw_force_gc_thread+0x5d [C:\Work\dotnet-products\Profiler\Native\Solution\core\src\profilers\memory\gc_command_queue.cpp @ 305] 
20  ARM64EC 000000e3`822ff890 00007ffd`152f6020     KERNEL32!$iexit_thunk$cdecl$i8$i8+0x1c
21  ARM64EC 000000e3`822ff8c0 00007ffd`17188308     KERNEL32!#BaseThreadInitThunk+0x30
22  ARM64EC 000000e3`822ff8d0 00000000`00000000     ntdll!#RtlUserThreadStart+0x48
```

Could you please fix before release?

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/90830

Quick explanation how's the dead-lock happening:
**Thread1:**
Someone (typically, JIT) tries to allocate an object on NonGC heap. `FrozenObjectHeapManager` (FOHM) acquires its lock and calls GC's API `RegisterNewSegment`. That API internally **can** hit a case when a GC is happening so it has to wait for GC to complete.

**Thread2 (GC's):**
GC is executing a callback (e.g. `GarbageCollectionFinished` or `*Started`) and Profiler uses that callback to enumerate objects on NonGC heap via `ICorProfilerInfo14::GetNonGCHeapBounds` thus, it also tries to acquire FOHM's lock (to be able to safely enumerate the objects). Thus, GC's thread (Thread2) is wating for FOHM's lock to release (it's taken by Thread1) while Thread1 is waiting for GC to finish.

The fix is https://github.com/dotnet/runtime/issues/90830#issuecomment-1684841908

### CODE REVIEW

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 1]
```diff
@@ -10,11 +10,54 @@
...
+    // Release the active lock since segment's initialization logic (RegisterFrozenSegment to be exact) might
+    // hit a gc lock while e.g. profiler is trying to enumerate NonGC objects in GC's callback and waiting for this lock.
+    activeLock->Release();
+
+    bool justInitialized = false;
+    {
+        // We don't want to initialize it twice so a new quick lock is taken.
+        CrstHolder initSegmentLock(&m_InitSegmentCrst);
+
+        // Double-checked locking if some thread already initialized it here.
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:43]: The new segment is not visible to other threads at this point. This won't ever happen in this implementation.

Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp:43]: Ah, I take the registration lock earlier than I release the main one - I pushed a slightly wrong version

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 2]
```diff
@@ -10,11 +10,54 @@
...
+            segment->Initialize();
+        }
+    }
+
+    // Reacquire the active lock
+    activeLock->Acquire();
+    if (justInitialized)
+    {
+        // Update m_CurrentSegment and m_FrozenSegments only for the thread that won the race.
+        m_CurrentSegment = segment;
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:56]: This can override a `m_CurrentSegment` that was just allocated by other thread and that has a plenty of space available.

(The implementation that I have sketched in https://github.com/dotnet/runtime/issues/90830#issuecomment-1684841908 tried to avoid this problem by creating the new segment under the main lock, and only taking the other lock for registering the new segment with the GC.)

Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp]: Thanks! I actually didn't realize I can let it allocate objects in a non-registered segment (and register it later before use)

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 3]
```diff
@@ -201,8 +225,17 @@ Object* FrozenObjectSegment::TryAllocateObject(PTR_MethodTable type, size_t obje
 
     m_pCurrent += objectSize;
 
-    // Notify GC that we bumped the pointer and, probably, committed more memory in the reserved part
-    GCHeapUtilities::GetGCHeap()->UpdateFrozenSegment(m_SegmentHandle, m_pCurrent, m_pStart + m_SizeCommitted);
+    if (IsRegistered())
+    {
+        // Notify GC that we bumped the pointer and, probably, committed more memory in the reserved part
+        // NOTE: UpdateFrozenSegment is not expected to take any lock inside
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:231]: This sounds a bit suspicious. What guarantees that some other GC thread is not reading the limits as they are being updated?

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 4]
```diff
@@ -135,34 +152,41 @@ FrozenObjectSegment::FrozenObjectSegment(size_t sizeHint) :
...
+    si.ibAllocated = (size_t)m_pCurrent; // there can be multiple objects already allocated
+    si.ibCommit = m_SizeCommitted;
     si.ibReserved = m_Size;
 
+    // NOTE: RegisterFrozenSegment may take a GC lock inside.
     m_SegmentHandle = GCHeapUtilities::GetGCHeap()->RegisterFrozenSegment(&si);
     if (m_SegmentHandle == nullptr)
     {
-        ClrVirtualFree(alloc, 0, MEM_RELEASE);
+        ClrVirtualFree(m_pStart, 0, MEM_RELEASE);
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:181]: We do not want to free the memory here. We should leave it reserved and assume that some other thread tries to register the segment, it is going to succeed.

(We will leak the frozen object allocation in this situation. I think it is ok.)

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 5]
```diff
@@ -33,6 +36,7 @@ Object* FrozenObjectHeapManager::TryAllocateObject(PTR_MethodTable type, size_t
 #else // FEATURE_BASICFREEZE
 
     Object* obj = nullptr;
+    FrozenObjectSegment* currentSegment = nullptr;
     {
         CrstHolder ch(&m_Crst);
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:41]:
```suggestion
        GCX_PREEMP();

        CrstHolder ch(&m_Crst);
```
Would it be possible to switch to preemptive mode around this lock? This is potentially expensive operation due to VirtualAlloc calls. It is better to be in preemptive mode for that; and to take unmanaged locks in general - preemptive mode makes sure that the lock won't cause GC starvation or deadlock with GC.

File: src/coreclr/vm/appdomain.hpp [hunk 6]
```diff
@@ -2449,14 +2449,21 @@ class SystemDomain : public BaseDomain
         _ASSERTE(m_pGlobalStringLiteralMap);
         return m_pGlobalStringLiteralMap;
     }
-    static FrozenObjectHeapManager* GetFrozenObjectHeapManager()
+    static FrozenObjectHeapManager* GetFrozenObjectHeapManager(bool initialize = true)
```
Comment (jkotas) [inline src/coreclr/vm/appdomain.hpp:2452]: I would look better to have two different methods instead of `initialize` bool arg. It is what we do in other places, e.g.: https://github.com/dotnet/runtime/blob/ac02b66e41041e1cefd355eacaddb45bcb4f1741/src/coreclr/vm/interoplibinterface_comwrappers.cpp#L211-L224

It allows proper contracts. `LIMITED_METHOD_CONTRACT` for the non-throwing version, and `THROWS; MODE_COOPERATIVE (?)` for the throwing version.

Comment (jkotas) [reply src/coreclr/vm/appdomain.hpp:2452]: (Could you please indentation on this contract while you are on it - https://github.com/dotnet/runtime/blob/ac02b66e41041e1cefd355eacaddb45bcb4f1741/src/coreclr/vm/methodtable.cpp#L4225-L4226)

File: src/coreclr/vm/profilingenumerators.cpp [hunk 7]
```diff
@@ -103,7 +103,13 @@ BOOL ProfilerObjectEnum::Init()
...
     CONTRACTL_END;
 
-    FrozenObjectHeapManager* foh = SystemDomain::GetFrozenObjectHeapManager();
+    // initialize = false to avoid breaking the NOTHROW contract
+    FrozenObjectHeapManager* foh = SystemDomain::GetFrozenObjectHeapManager(/*initialize*/ false);
+    if (foh == nullptr)
+    {
+        return TRUE;
+    }
+
```
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/vm/profilingenumerators.cpp:111]: Good catch! Done

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp:231]: Do you mean it should take the lock in GC and FrozenManager should take the registration lock for every allocation?

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp:181]: Do you mean we shouldn't also ThrowOOM here? And we'll just return an object from FrozenObjectManager and pretend everything is ok (let's say there are no other thread, it's just our thread failed to reserve it)

Comment (jkotas) [reply src/coreclr/vm/frozenobjectheap.cpp:183]: We should ThrowOOM here. I do not think we can proceed without the segment being registered with the GC.

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 3 above)
Comment (jkotas) [reply src/coreclr/vm/frozenobjectheap.cpp:233]: I do not know how and where the limits are used by the GC. It just looks suspicious that we do not need any synchronization when updating them.

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp]: My guess that generally GC just ignores ro segments except:
1) scanning in-range ro-segements in segments-based GC (e.g. 32bit)
2) reporting them to debugger via EnumMemory

so probably it does need a lock

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp:232]: My guess that generally GC just ignores ro segments except:
1) scanning in-range ro-segements in segments-based GC (e.g. 32bit)
2) reporting them to debugger via EnumMemory

so probably it does need a lock (but am not sure). maybe @Maoni0 @cshung can advise? 
Question is:
Does 
https://github.com/dotnet/runtime/blob/899461780a9e309142e8d85f25e15d4416157fa7/src/coreclr/gc/gcee.cpp#L510-L517

need to take `gc_heap::gc_lock` lock?

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp]: Ok, remove ClrVirtualFree

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp]: Added locking via https://github.com/dotnet/runtime/pull/90847/commits/9c944ecfbcf012575cd1df110b9a66ded4a51fa8 but still would be nice to hear an opinion from GC team

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 8]
```diff
@@ -135,34 +150,48 @@ FrozenObjectSegment::FrozenObjectSegment(size_t sizeHint) :
...
 
-    segment_info si;
-    si.pvMem = committedAlloc;
-    si.ibFirstObject = sizeof(ObjHeader);
-    si.ibAllocated = si.ibFirstObject;
-    si.ibCommit = FOH_COMMIT_SIZE;
-    si.ibReserved = m_Size;
+void FrozenObjectSegment::RegisterOrUpdate()
+{
+    m_SizeCommittedRegistered = m_SizeCommitted;
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:165]: `m_SizeCommitted` and `m_pCurrent` can be updated by the other thread while they are being read here. Can it lead to race conditions?

Comment (jkotas) [reply src/coreclr/vm/frozenobjectheap.cpp:165]: I think you may want to pass how far the current thread got as an argument to `RegisterOrUpdate`. `RegisterOrUpdate` can then decide whether some other thread beat it to register/update the space, or whether the space still needs to registering/updating.

Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp]: Thanks! Indeed could be a race condition, fixed

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp]: Looks like it's definitely needed, otherwise Profiler will have a race condition

Comment (mangod9) [reply src/coreclr/vm/frozenobjectheap.cpp]: @cshung, can you please take a look at this?

Comment (cshung) [reply src/coreclr/vm/frozenobjectheap.cpp]: I am on it.

File: src/coreclr/vm/profilingenumerators.cpp [hunk 9]
```diff
@@ -113,6 +118,10 @@ BOOL ProfilerObjectEnum::Init()
         for (unsigned segmentIdx = 0; segmentIdx < segmentsCount; segmentIdx++)
         {
             const FrozenObjectSegment* segment = segments[segmentIdx];
+            if (!segment->IsRegistered())
```
Comment (cshung) [inline src/coreclr/vm/profilingenumerators.cpp:121]: It feels like there is a possibility for a race condition here:

1. Allocating thread left the `m_crst`, took the `m_SegmentRegistrationCrst`, called `RegisterFrozenSegment`, but having performed the volatile store yet.
2. A thread is running here, it is able to reach here because the allocating thread already left the `m_crst`

In this case, you would think the segment is not registered here but it is already registered on the allocation side.

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 10]
```diff
@@ -135,34 +155,63 @@ FrozenObjectSegment::FrozenObjectSegment(size_t sizeHint) :
...
-    si.ibFirstObject = sizeof(ObjHeader);
-    si.ibAllocated = si.ibFirstObject;
-    si.ibCommit = FOH_COMMIT_SIZE;
-    si.ibReserved = m_Size;
-
-    m_SegmentHandle = GCHeapUtilities::GetGCHeap()->RegisterFrozenSegment(&si);
-    if (m_SegmentHandle == nullptr)
+void FrozenObjectSegment::RegisterOrUpdate(uint8_t* current, size_t sizeCommited)
+{
+    if (!IsRegistered())
```
Comment (cshung) [inline src/coreclr/vm/frozenobjectheap.cpp:169]: Can you please assert this method is called under preemptive mode, and that the `m_SegmentRegistrationCrst` is already taken by the current thread?

File: src/coreclr/gc/gcee.cpp [hunk 11]
```diff
@@ -510,9 +510,12 @@ bool GCHeap::IsInFrozenSegment(Object *object)
 void GCHeap::UpdateFrozenSegment(segment_handle seg, uint8_t* allocated, uint8_t* committed)
 {
 #ifdef FEATURE_BASICFREEZE
```
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/gc/gcee.cpp:512]: I am going to backport this to 8.0 so do you mind if I make refactorings in a separate PR for 9.0 only? We can also discuss getting rid of word "Frozen" everywhere and replace with "NonGC"

File: src/coreclr/vm/profilingenumerators.cpp (hunk 9 above)
Comment (EgorBo) [reply src/coreclr/vm/profilingenumerators.cpp:121]: hm.. I don't see a good solution for this case other then using GC's lock for the whole registration part cc @jkotas 
Since profiler is expected to be executed on GC's thread.

**Comment by jkotas** [comment]
> Use preemptive for the whole method

Was this fixing a real problem or was it just a nice to have cleanup?

File: src/coreclr/vm/profilingenumerators.cpp (hunk 9 above)
Comment (jkotas) [reply src/coreclr/vm/profilingenumerators.cpp:121]: The earlier change run the registration part in cooperative mode. The GC cannot run when there are threads running in cooperative mode. Running the registration in cooperative mode would prevent updates while the GC is running.

When is the profiler allowed to call `GetNonGCHeapBounds`? Is it allowed to call the API only during the GC or even outside the GC?

Comment (EgorBo) [reply src/coreclr/vm/profilingenumerators.cpp:121]: > When is the profiler allowed to call GetNonGCHeapBounds? Is it allowed to call the API only during the GC or even outside the GC?

A similar API the `GetNonGCHeapBounds` is based on, namely - `GetGenerationBounds` has a comment:
https://github.com/dotnet/runtime/blob/819e288da8689a5aefe9f201865b0f44f00537d4/src/coreclr/inc/corprof.idl#L2040-L2042

so I assume we're allowed to provide the same guarantee only for those callbacks too.

> The GC cannot run when there are threads running in cooperative mode. 

It seems that underlying Update/Register frozen segment can switch to preemptive, can't they? If gclock spinning takes too long it switches to preemptive and yeilds so perhaps a GC can happens once it wakes up?

**Comment by EgorBo** [comment]
> > Use preemptive for the whole method
> 
> Was this fixing a real problem or was it just a nice to have cleanup?

Hm.. it fixed an assert I've seen:
```
Assert failure(PID 5520 [0x00001590], Thread: 1412 [0x0584]): !GCForbidden()


CORECLR! Thread::EnablePreemptiveGC + 0xF6 (0x00007ffb75d9d4f6) CORECLR! GCToEEInterface::EnablePreemptiveGC + 0x3B (0x00007ffb76186e0b)
CORECLR! WKS::WaitLongerNoInstru + 0x11 (0x00007ffb764e7371) CORECLR! WKS::gc_heap::update_ro_segment + 0x173 (0x00007ffb76519013)
CORECLR! FrozenObjectHeapManager::TryAllocateObject + 0x500 (0x00007ffb76183a30) CORECLR! AllocateString + 0x13A (0x00007ffb7618e8fa)
CORECLR! AllocateStringObject + 0x101 (0x00007ffb763214c1) CORECLR! GlobalStringLiteralMap::AddStringLiteral + 0x352 (0x00007ffb76320d02)
CORECLR! GlobalStringLiteralMap::GetStringLiteral + 0x717 (0x00007ffb76323317) CORECLR! StringLiteralMap::GetStringLiteral + 0x463 (0x00007ffb763237e3)
File: D:_work1ssrccoreclrm	hreads.h Line: 1795
Image: C:hwACF509B8pcorerun.exe
```

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 12]
```diff
@@ -10,7 +10,8 @@
 #define FOH_COMMIT_SIZE (64 * 1024)
 
 FrozenObjectHeapManager::FrozenObjectHeapManager():
-    m_Crst(CrstFrozenObjectHeap, CRST_UNSAFE_COOPGC),
+    m_Crst(CrstFrozenObjectHeap, CRST_UNSAFE_ANYMODE),
+    m_SegmentRegistrationCrst(CrstFrozenObjectHeap, CRST_UNSAFE_ANYMODE),
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:14]:
```suggestion
    m_SegmentRegistrationCrst(CrstFrozenObjectHeap),
```
This can be regular "safe" lock. It is always entered in preemptive mode.

File: src/coreclr/vm/profilingenumerators.cpp (hunk 9 above)
Comment (jkotas) [reply src/coreclr/vm/profilingenumerators.cpp:121]: Ok, I think that we should report all frozen segments that were created by VM here, irrespective of whether they have been registered with the GC or not.

(If we do not like that behavior for some reason and we would like to only report what the GC knows about, we need to shift the responsibility to report it to the GC or get the GC to cooperate with the reporting. Otherwise, the locking schemes around this get way too complicated.)

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 13]
```diff
@@ -194,22 +244,17 @@ Object* FrozenObjectSegment::TryAllocateObject(PTR_MethodTable type, size_t obje
...
-    // Notify GC that we bumped the pointer and, probably, committed more memory in the reserved part
-    GCHeapUtilities::GetGCHeap()->UpdateFrozenSegment(m_SegmentHandle, m_pCurrent, m_pStart + m_SizeCommitted);
-
     return object;
 }
 
 Object* FrozenObjectSegment::GetFirstObject() const
 {
-    if (m_pStart + sizeof(ObjHeader) == m_pCurrent)
+    if (m_pStart + sizeof(ObjHeader) == m_pCurrentRegistered)
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:257]: Why do we need to switch to `m_pCurrentRegistered` here? 

We are under `m_Crst` lock when enumerating the objects.

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 14]
```diff
@@ -221,11 +266,11 @@ Object* FrozenObjectSegment::GetNextObject(Object* obj) const
 {
     // Input must not be null and should be within the segment
     _ASSERT(obj != nullptr);
-    _ASSERT((uint8_t*)obj >= m_pStart + sizeof(ObjHeader) && (uint8_t*)obj < m_pCurrent);
+    _ASSERT((uint8_t*)obj >= m_pStart + sizeof(ObjHeader) && (uint8_t*)obj < m_pCurrentRegistered);
 
     // FOH doesn't support objects with non-DATA_ALIGNMENT alignment yet.
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:271]: Do we need to set `m_NumComponents` for arrays as part of `TryAllocateObject`?

We are setting it too late and we can end up enumerating arrays without `m_NumComponents` that is not going to end wel..

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 15]
```diff
@@ -135,34 +157,65 @@ FrozenObjectSegment::FrozenObjectSegment(size_t sizeHint) :
...
+    }
+    CONTRACTL_END
 
-    m_SegmentHandle = GCHeapUtilities::GetGCHeap()->RegisterFrozenSegment(&si);
-    if (m_SegmentHandle == nullptr)
+    if (!IsRegistered())
     {
-        ClrVirtualFree(alloc, 0, MEM_RELEASE);
-        ThrowOutOfMemory();
+        // Other threads won't touch these fields until we set m_IsRegistered to true
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:180]: This works, but it is not straightforward to see that it is correct when `RegisterFrozenSegment` fails.

It would be easier to see that this is correct if you set these fields after `RegisterFrozenSegment` succeeds. You would not actually even need `m_IsRegistered` bool flag if you do it that way - non-null `m_pCurrentRegistered can act as `m_IsRegistered` flag.

**Review by jkotas — APPROVED** [review]
Looks good to me otherwise. Thank you!

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 16]
```diff
@@ -135,34 +157,65 @@ FrozenObjectSegment::FrozenObjectSegment(size_t sizeHint) :
...
+        VolatileStore(&m_SizeCommittedRegistered, sizeCommited);
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:181]: Nothing reads `m_SizeCommittedRegistered` in the latest revision.  It can be deleted too.

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 14 above)
Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp]: Good point! It also allowed to simplify the PublishObject logic a bit. The final API might be simplified a bit with C++ template to allow use of capturing lambdas for simplicity but that needed a bit more changes

File: src/coreclr/vm/profilingenumerators.cpp (hunk 9 above)
Comment (EgorBo) [reply src/coreclr/vm/profilingenumerators.cpp]: I prototyped a change to expose gc lock: https://github.com/EgorBo/runtime-1/commit/e5d9dacc26d7eddae8af81a5d266f29daed39e7b but overall yeah, it feels like it making NonGC heap to be rather GC heap 🙂

**Comment by EgorBo** [comment]
> Looks good to me otherwise. Thank you!

Thanks for the help! I wish I could easily spot all possible race conditions/corner cases just like you 🙂

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 17]
```diff
@@ -135,34 +157,59 @@ FrozenObjectSegment::FrozenObjectSegment(size_t sizeHint) :
...
+        if (current > VolatileLoad(&m_pCurrentRegistered))
+        {
+            GCHeapUtilities::GetGCHeap()->UpdateFrozenSegment(
+                m_SegmentHandle, current, m_pStart + sizeCommited);
+            VolatileStore(&m_pCurrentRegistered, current);
+        }
+        else
+        {
+            // Some other thread already advanced it.
+        }
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:206]:
```suggestion
    if (m_pCurrentRegistered == nullptr)
    {
        segment_info si;
        si.pvMem = m_pStart;
        si.ibFirstObject = sizeof(ObjHeader);
        si.ibAllocated = (size_t)current;
        si.ibCommit = sizeCommited;
        si.ibReserved = m_Size;

        // NOTE: RegisterFrozenSegment may take a GC lock inside.
        m_SegmentHandle = GCHeapUtilities::GetGCHeap()->RegisterFrozenSegment(&si);
        if (m_SegmentHandle == nullptr)
        {
            ThrowOutOfMemory();
        }
        m_pCurrentRegistered = current;
    }
    else
    {
        if (current > m_pCurrentRegistered)
        {
            GCHeapUtilities::GetGCHeap()->UpdateFrozenSegment(
                m_SegmentHandle, current, m_pStart + sizeCommited);
            m_pCurrentRegistered = current;
        }
        else
        {
            // Some other thread already advanced it.
        }
```
The registration used `m_pCurrentRegistered` that would always be null.
Also, `m_pCurrentRegistered` is always read under the `m_SegmentRegistrationCrst` lock. It does not need to volatile.
