### PR TITLE
Don't set GCState to 1 in PInvoke Epilog

### LINKED ISSUE #38192: UnmanagedCallersOnly does not work when called from a P/Invoke in Release mode
As per the title, the following program succeeds if run under `Debug` but fails under `Release`

```csharp
using System;
using System.Runtime.InteropServices;

unsafe class Program
{
    public const int CS_VREDRAW = 0x0001;
    public const int CS_HREDRAW = 0x0002;

    public const int CW_USEDEFAULT = unchecked((int)0x80000000);

    public const int SW_SHOWDEFAULT = 10;

    public const uint WS_OVERLAPPED = 0x00000000;
    public const uint WS_CAPTION = 0x00C00000;
    public const uint WS_SYSMENU = 0x00080000;
    public const uint WS_THICKFRAME = 0x00040000;
    public const uint WS_MINIMIZEBOX = 0x00020000;
    public const uint WS_MAXIMIZEBOX = 0x00010000;

    public const uint WS_OVERLAPPEDWINDOW = WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX;

    public unsafe partial struct WNDCLASSEXW
    {
        public uint cbSize;
        public uint style;
        public delegate* stdcall<IntPtr, uint, nuint, nint, nint> lpfnWndProc;
        public int cbClsExtra;
        public int cbWndExtra;
        public IntPtr hInstance;
        public IntPtr hIcon;
        public IntPtr hCursor;
        public IntPtr hbrBackground;
        public ushort* lpszMenuName;
        public ushort* lpszClassName;
        public IntPtr hIconSm;
    }

    [DllImport("user32", EntryPoint = "CreateWindowExW", ExactSpelling = true)]
    public static extern IntPtr CreateWindowExW(uint dwExStyle, ushort* lpClassName, ushort* lpWindowName, uint dwStyle, int X, int Y, int nWidth, int nHeight, IntPtr hWndParent, IntPtr hMenu, IntPtr hInstance, void* lpParam);

    [DllImport("user32", EntryPoint = "DefWindowProcW", ExactSpelling = true)]
    public static extern nint DefWindowProcW(IntPtr hWnd, uint Msg, nuint wParam, nint lParam);

    [DllImport("user32", EntryPoint = "RegisterClassExW", ExactSpelling = true)]
    public static extern ushort RegisterClassExW(WNDCLASSEXW* param0);

    [UnmanagedCallersOnly]
    private static nint WindowProc(IntPtr hWnd, uint Msg, nuint wParam, nint lParam)
    {
        return DefWindowProcW(hWnd, Msg, wParam, lParam);
    }

    static void Main(string[] args)
    {
        fixed (char* lpszClassName = "SampleClass")
        fixed (char* lpWindowName = "SampleTitle")
        {
            var hInstance = Marshal.GetHINSTANCE(typeof(Program).Module);

            // Requires an explicit cast until C# handles UnmanagedCallersOnly
            var wndProc = (delegate* stdcall<IntPtr, uint, nuint, nint, nint>)(delegate* managed<IntPtr, uint, nuint, nint, nint>)&WindowProc;

            // Initialize the window class.
            var windowClass = new WNDCLASSEXW
            {
                cbSize = (uint)sizeof(WNDCLASSEXW),
                style = CS_HREDRAW | CS_VREDRAW,
                lpfnWndProc = wndProc,
                hInstance = hInstance,
                lpszClassName = (ushort*)lpszClassName
            };
            _ = RegisterClassExW(&windowClass);

            var hwnd = CreateWindowExW(
                0,
                windowClass.lpszClassName,
                (ushort*)lpWindowName,
                WS_OVERLAPPEDWINDOW,
                X: CW_USEDEFAULT,
                Y: CW_USEDEFAULT,
                nWidth: CW_USEDEFAULT,
                nHeight: CW_USEDEFAULT,
                hWndParent: IntPtr.Zero,
                hMenu: IntPtr.Zero,
                hInstance,
                lpParam: null
            );
        }
    }
}
```

The csproj should resemble the following so function pointers can be used:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <RestoreSources>
      https://api.nuget.org/v3/index.json;
      https://dotnet.myget.org/F/roslyn/api/v3/index.json;
    </RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="3.8.0-1.20320.1" />
  </ItemGroup>

</Project>
```

A more complete program will successfully display the window, handle the callbacks etc in `Debug`. Additionally it will all work as expected under `Release` if using `Marshal.GetFunctionPointerForDelegate` instead.

However, under `Release` when using `UnmanagedCallersOnly`, it fails with the following:
```
Fatal error. Invalid Program: attempted to call a UnmanagedCallersOnly method from managed code.
Repeat 2 times:
--------------------------------
   at Program.CreateWindowExW(UInt32, UInt16*, UInt16*, UInt32, Int32, Int32, Int32, Int32, IntPtr, IntPtr, IntPtr, Void*)
--------------------------------
   at Program.Main(System.String[])
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Remove the incorrect setting of `GCState` and fix the liveness computation for `compLvFrameListRoot` for tailcalls.

Fix #38192

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/dnceng - the `CoreCLR Pri0 Runtime Tests Run Windows_NT x86 checked` leg doesn't seem to complete. AFAICT there aren't any errors [here](https://helix.dot.net/api/2019-06-17/jobs/d761b210-1a1d-4689-961b-f1fe79484357/workitems/PayloadGroup0/console).

**Comment by MattGal** [comment]
> @dotnet/dnceng - the `CoreCLR Pri0 Runtime Tests Run Windows_NT x86 checked` leg doesn't seem to complete. AFAICT there aren't any errors [here](https://helix.dot.net/api/2019-06-17/jobs/d761b210-1a1d-4689-961b-f1fe79484357/workitems/PayloadGroup0/console).

I shall investigate.

**Comment by MattGal** [comment]
@CarolEidt it's a timeout.  It'd be nice if this were more obvious for sure but it'd be unfortunately a breaking API change so will have to wait.

To see this:

1) remove the /console to get the other logs: https://helix.dot.net/api/2019-06-17/jobs/d761b210-1a1d-4689-961b-f1fe79484357/workitems/PayloadGroup0

2) The  -3  exit code is a giveaway for timeouts but can also check the run_client log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-38303-merge-d761b2101a1d468996/PayloadGroup0/9e2629ef-b8b2-4720-9a04-88c386f6c7bb.log

```
2020-06-24T21:33:03.483Z	INFO   	job(51)	kill	Begin killing timed-out process(es)
2020-06-24T21:33:03.483Z	ERROR  	job(60)	kill	Job running for too long. Killing...
2020-06-24T21:33:03.483Z	INFO   	job(66)	kill	Finished killing timed-out process(es)
2020-06-24T21:33:03.483Z	INFO   	job(37)	wait	Work item's process exited normally.
2020-06-24T21:33:03.483Z	ERROR  	executor(652)	_execute_command	Executor timed out after 1800 seconds and was killed.
2020-06-24T21:33:03.483Z	INFO   	event(42)	send	Sending event type WorkItemTimeout
2020-06-24T21:33:03.624Z	INFO   	saferequests(87)	request_with_retry	Response complete with status code '201'
2020-06-24T21:33:03.624Z	INFO   	executor(618)	_dump_file_upload	No dump files to upload
2020-06-24T21:33:03.624Z	INFO   	executor(674)	_execute_command	Finished _execute_command, exit code: -3
```

**Comment by CarolEidt** [comment]
Thanks @MattGal - is the timeout common? I've already retried once, and have retried again. I just ran the tests on my system and they completed in what seems like about the normal amount of time.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

File: src/coreclr/src/jit/liveness.cpp [hunk 1]
```diff
@@ -513,13 +514,22 @@ void Compiler::fgPerBlockLocalVarLiveness()
             {
                 noway_assert(info.compLvFrameListRoot < lvaCount);
 
-                LclVarDsc* varDsc = &lvaTable[info.compLvFrameListRoot];
+// 32-bit targets always pop the frame in the epilog.
+// For 64-bit targets, we only do this in the epilog for IL stubs;
+// for non-IL stubs the frame is popped after every PInvoke call.
```
Comment (AndyAyersMS) [inline src/coreclr/src/jit/liveness.cpp:519]: Use the `CLANG_FORMAT_COMMENT_ANCHOR` here?

File: src/coreclr/src/jit/liveness.cpp [hunk 2]
```diff
@@ -342,16 +342,16 @@ void Compiler::fgPerNodeLocalVarLiveness(GenTree* tree)
...
+            // If this is a p/invoke unmanaged call or if this is a tail-call via helper,
             // and we have an unmanaged p/invoke call in the method,
             // then we're going to run the p/invoke epilog.
             // So we mark the FrameRoot as used by this instruction.
             // This ensures that the block->bbVarUse will contain
             // the FrameRoot local var if is it a tracked variable.
 
-            if ((tree->AsCall()->IsUnmanaged() || tree->AsCall()->IsTailCall()) && compMethodRequiresPInvokeFrame())
+            if ((tree->AsCall()->IsUnmanaged() || tree->AsCall()->IsTailCallViaJitHelper()) &&
+                compMethodRequiresPInvokeFrame())
```
Comment (AndyAyersMS) [inline src/coreclr/src/jit/liveness.cpp:354]: Just below this is another comment mentioning "the TCB". Since you redid other comments, maybe redo this one too?

**Review by AndyAyersMS — APPROVED** [review]
LGTM, just a few comments on comments.

**Comment by MattGal** [comment]
> Thanks @MattGal - is the timeout common? I've already retried once, and have retried again. I just ran the tests on my system and they completed in what seems like about the normal amount of time.

Quick check of Kusto shows a work item with that naming timing out on Windows.10.Amd64.Open having happened 257 of 9366 total run times in the past 30 days.   Do note that while things may work on your box, there are variances; these machines have 2 cores, they run server OS skus, and it's also unlikely you ran the test locally 9300 times.
