### PR TITLE
Fix virtual static dispatch for variant interfaces when using default implementations

### LINKED ISSUE #78621: Variant static interface dispatch crashes the runtime
```csharp
using System;

Console.WriteLine(GetTheFooString<FooBar, Base>());
Console.WriteLine(GetTheFooString<FooBar, Mid>());
Console.WriteLine(GetTheFooString<FooBar, Derived>());

Console.WriteLine(GetTheBarString<FooBar, Base>());
Console.WriteLine(GetTheBarString<FooBar, Mid>());
Console.WriteLine(GetTheBarString<FooBar, Derived>());

Console.WriteLine(GetTheFooString<FooBarBaz, Base>());
Console.WriteLine(GetTheFooString<FooBarBaz, Mid>());
Console.WriteLine(GetTheFooString<FooBarBaz, Derived>());

Console.WriteLine(GetTheBarString<FooBarBaz, Base>());
Console.WriteLine(GetTheBarString<FooBarBaz, Mid>());
Console.WriteLine(GetTheBarString<FooBarBaz, Derived>());


static string GetTheFooString<T, U>() where T : IFoo<U> => T.GetString();
static string GetTheBarString<T, U>() where T : IBar<U> => T.GetString();

interface IFoo<in T> { static virtual string GetString() => $"IFoo<{typeof(T).Name}>"; };
interface IBar<out T> { static virtual string GetString() => $"IBar<{typeof(T).Name}>"; };
class FooBar : IFoo<Base>, IBar<Derived> { }

interface IBaz : IFoo<Mid>, IBar<Mid>
{
    static string IFoo<Mid>.GetString() => "IBaz";
    static string IBar<Mid>.GetString() => "IBaz";
}
class FooBarBaz : FooBar, IBaz { }

class Base { }
class Mid : Base { }
class Derived : Mid { }
```

## Expected

Doesn't crash

## Actual

```
IFoo<Base>
IFoo<Base>
IFoo<Base>
IBar<Derived>
IBar<Derived>
IBar<Derived>
IFoo<Base>
Fatal error. Internal CLR error. (0x80131506)
   at Program.<<Main>$>g__GetTheFooString|0_0[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]()
   at Program.<Main>$(System.String[])
```

### PR DESCRIPTION
**Pull request by davidwrighton**
- Move the handling for variance so that it is in the same place as it is for instance methods
- Validate the behavior of such dispatch is equivalent to the dispatch behavior involving instance variant default dispatch
- Rework the fix for #80350 to avoid violating an invariant of the type system (which is that all MethodDef's of a TypeDef are loaded as MethodDescs when loading the open type).

Fixes #78621

### CODE REVIEW

File: src/coreclr/vm/methodtable.cpp [hunk 1]
```diff
@@ -8911,7 +8912,7 @@ MethodTable::ResolveVirtualStaticMethod(
             // Search for match on a per-level in the type hierarchy
             for (MethodTable* pMT = this; pMT != nullptr; pMT = pMT->GetParentMethodTable())
```
Comment (trylek) [inline src/coreclr/vm/methodtable.cpp:8913]: Shouldn't this parent type descent also be in a 2-pass loop over <code>allowVariance = FALSE, TRUE</code> when <code>allowVariantMatches</code> is set i.o.w. shouldn't it also be in the below loop used for default interface resolution?

Comment (trylek) [reply src/coreclr/vm/methodtable.cpp:8913]: Hmm, after getting my head around the tests I take it back, the variant lookup should take place before descending into parent.

File: src/coreclr/vm/methodtable.cpp [hunk 2]
```diff
@@ -8955,7 +8956,7 @@ MethodTable::ResolveVirtualStaticMethod(
                         {
                             // Variant or equivalent matching interface found
                             // Attempt to resolve on variance matched interface
-                            pMD = pMT->TryResolveVirtualStaticMethodOnThisType(pItfInMap, pInterfaceMD, verifyImplemented, level);
+                            pMD = pMT->TryResolveVirtualStaticMethodOnThisType(pItfInMap, pInterfaceMD, verifyImplemented, /*allowVariance*/ FALSE, level);
```
Comment (trylek) [inline src/coreclr/vm/methodtable.cpp:8959]: Shouldn't we be setting <code>allowVariance</code> to <code>TRUE</code> (or perhaps to <code>allowVariantMatches</code>) here? Otherwise I don't see where we are supposed to be performing the variant resolution in this method; can you please explain to me what am I missing?

Comment (trylek) [reply src/coreclr/vm/methodtable.cpp:8959]: Alternatively, if it's the case that in practice all variant resolution is only limited to the default interface implementation case (which is probably correct), why do we need this additional pass over the interface map in this place?

**Review by trylek — APPROVED** [review]
LGTM, thanks David! I had a bit of trouble getting my head around the exact code flow in SVM resolution but I now think it is actually correct.
