### PR TITLE
fix TLS resume with HttpClientHandler on Linux

### LINKED ISSUE #75434: HttpClientHandler always set LocalCertificateSelectionCallback delegate in SslOptions
Besides extra work this prevents TLS resume on Linux so HttpClient won't be able to benefit from #64369

https://github.com/dotnet/runtime/blob/855c475fd9c0b3a303e3de15785b63456108f7e3/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L298-L310

Since the delegate _could_ return different certificate, we would somehow need to track what was actually selected and resume accordingly (if possible)

It seems like the best option wold be not set the delegate unless there is actual need e.g. client certificate is in use.

### PR DESCRIPTION
**Pull request by wfurt**
fixes #75434
contributes to #75545  

The existing code prevents TLS resume on Linux when `HttpClientHandler` is used (works fine if `SocketsHttpHandler` is used directly)

I updated test loopback server with `CertificateContext`. I was debating if we should add while ssl options but decided not to as there is currently no other use for it.

### CODE REVIEW

File: src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs [hunk 1]
```diff
@@ -471,14 +477,25 @@ public static async Task<Connection> CreateAsync(SocketWrapper socket, Stream st
...
-                        await sslStream.AuthenticateAsServerAsync(
-                            cert,
-                            clientCertificateRequired: true, // allowed but not required
-                            enabledSslProtocols: httpOptions.SslProtocols,
-                            checkCertificateRevocation: false).ConfigureAwait(false);
+                         await sslStream.AuthenticateAsServerAsync(
+                             cert,
+                             clientCertificateRequired: true, // allowed but not required
+                             enabledSslProtocols: httpOptions.SslProtocols,
+                             checkCertificateRevocation: false).ConfigureAwait(false);
```
Comment (rzikm) [inline src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:496]: nit: the indentation seemed to be correct before this change

**Review by rzikm — APPROVED** [review]
LGTM!

**Comment by wfurt** [comment]
all the failures are known according to `build analyses.
