### PR TITLE
Fix TailCallStress mode.

### LINKED ISSUE #8017: [RyuJIT] TailcallStress needs to check more conditions
When `COMPlus_TailcallStress=1` is set, the JIT converts as many call/ret pairs as possible into tail call, which it treats as `tail.` prefixed "explicit" tail calls. It does not in this case run the legality checks that are run when checking to determine if implicit tailcall optimization can be done, specifically the code under `FEATURE_TAILCALL_OPT` in fgMorphCall() that rejects a potential tail call if any variable in the function has had its address taken, if there are pinned locals, or if there are struct promoted struct arguments.

This causes code such as this to fail:
```
    unsafe class Program
    {
        static void foo(IntPtr x)
        {
            Console.WriteLine(*(int*)x);
        }
        static void Main(string[] args)
        {
            int x = 42;
            foo((IntPtr)(&x));
        }
    }
```

category:correctness
theme:tail-call
skill-level:intermediate
cost:small

### LINKED ISSUE #37117: Test failure: profiler\\unittest\\getappdomainstaticaddress\\getappdomainstaticaddress.cmd
failed in job: [runtime-coreclr jitstress 20200526.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=660842&view=ms.vss-test-web.build-test-results-tab&runId=20497446&resultId=100008&paneView=debug)

Error message
~~~
Unhandled exception. System.ArgumentException: Path "??\h\w\A833091C\w\B2390971\e\profiler\unittest\getappdomainstaticaddress\unloadlibrary.dll" is not an absolute path. (Parameter 'assemblyPath')
 at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
 at Profiler.Tests.Program.LoadCollectibleAssembly() in F:\workspace\_work\1\s\src\coreclr\tests\src\profiler\unittest\getappdomainstaticaddress.cs:line 44
 at Profiler.Tests.Program.RunTest() in F:\workspace\_work\1\s\src\coreclr\tests\src\profiler\unittest\getappdomainstaticaddress.cs:line 33
 at Profiler.Tests.Program.Main(String[] args) in F:\workspace\_work\1\s\src\coreclr\tests\src\profiler\unittest\getappdomainstaticaddress.cs:line 21
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
 at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in F:\workspace\_work\1\s\src\coreclr\tests\src\profiler\common\ProfilerTestRunner.cs:line 137
 at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in F:\workspace\_work\1\s\src\coreclr\tests\src\profiler\common\ProfilerTestRunner.cs:line 91
 at Profiler.Tests.Program.Main(String[] args) in F:\workspace\_work\1\s\src\coreclr\tests\src\profiler\unittest\getappdomainstaticaddress.cs:line 26

Return code: 1
Raw output file: C:\h\w\A833091C\w\B2390971\e\profiler\unittest\Reports\profiler.unittest\getappdomainstaticaddress\getappdomainstaticaddress.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A833091C\p\corerun.exe" getappdomainstaticaddress.dll 
Profiler path: C:\h\w\A833091C\w\B2390971\e\profiler\unittest\getappdomainstaticaddress\Profiler.dll
Profiler path: C:\h\w\A833091C\w\B2390971\e\profiler\unittest\getappdomainstaticaddress\Profiler.dll
Profiler.dll!DllGetClassObject

Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A833091C\p
> C:\h\w\A833091C\w\B2390971\e\profiler\unittest\getappdomainstaticaddress\getappdomainstaticaddress.cmd
Expected: True
Actual: False


Stack trace
   at profiler_unittest._getappdomainstaticaddress_getappdomainstaticaddress_._getappdomainstaticaddress_getappdomainstaticaddress_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\profiler.unittest\profiler.unittest.XUnitWrapper.cs:line 140
~~~

category:correctness
theme:tail-call
skill-level:expert
cost:medium

### LINKED ISSUE #38887: Test failure: System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.DisableAiaOptionWorks
With:
```
COMPlus_TieredCompilation=0
COMPlus_TailcallStress=1
```

Fails for Windows x86, x64, and arm64

e.g., (Windows x64, Release libraries, Checked coreclr)

```
C:\gh\runtime\artifacts\bin\System.Security.Cryptography.X509Certificates.Tests\net5.0-Windows_NT-Release>call .\RunTests.cmd -r C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64
----- start Tue 07/07/2020 11:58:50.12 ===============  To repro directly: =====================================================
pushd C:\gh\runtime\artifacts\bin\System.Security.Cryptography.X509Certificates.Tests\net5.0-Windows_NT-Release\
"C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\dotnet.exe" exec --runtimeconfig System.Security.Cryptography.X509Certificates.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.X509Certificates.Tests.deps.json xunit.console.dll System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

C:\gh\runtime\artifacts\bin\System.Security.Cryptography.X509Certificates.Tests\net5.0-Windows_NT-Release>"C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\dotnet.exe" exec --runtimeconfig System.Security.Cryptography.X509Certificates.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.X509Certificates.Tests.deps.json xunit.console.dll System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
  Discovering: System.Security.Cryptography.X509Certificates.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.X509Certificates.Tests (found 571 of 612 test cases)
  Starting:    System.Security.Cryptography.X509Certificates.Tests (parallel test collections = on, max threads = 8)
    System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.DisableAiaOptionWorks [FAIL]
      Chain build with intermediate, AIA disabled
      Expected: True
      Actual:   False
      Stack Trace:
        C:\gh\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\AiaTests.cs(112,0): at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.DisableAiaOptionWorks()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.X509Certificates.Tests  Total: 1044, Errors: 0, Failed: 1, Skipped: 0, Time: 10.181s
----- end Tue 07/07/2020 11:59:07.11 ----- exit code 1 ----------------------------------------------------------
```

category:correctness
theme:tail-call
skill-level:expert
cost:medium

### LINKED ISSUE #38889: Test failure: System.Drawing.Common.Tests
Windows x86 and arm64 with:
```
COMPlus_TailcallStress=1
COMPlus_TieredCompilation=0
```

Doesn't fail on Windows x64.

x86:
```
C:\h\w\ADD60980\w\AB530912\e>set COMPlus 
COMPlus_TailcallStress=1
COMPlus_TieredCompilation=0

C:\h\w\ADD60980\w\AB530912\e>call RunTests.cmd --runtime-path C:\h\w\ADD60980\p 
----- start Tue 07/07/2020  9:13:41.98 ===============  To repro directly: ===================================================== 
pushd C:\h\w\ADD60980\w\AB530912\e\
"C:\h\w\ADD60980\p\dotnet.exe" exec --runtimeconfig System.Drawing.Common.Tests.runtimeconfig.json --depsfile System.Drawing.Common.Tests.deps.json xunit.console.dll System.Drawing.Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\ADD60980\w\AB530912\e>"C:\h\w\ADD60980\p\dotnet.exe" exec --runtimeconfig System.Drawing.Common.Tests.runtimeconfig.json --depsfile System.Drawing.Common.Tests.deps.json xunit.console.dll System.Drawing.Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Drawing.Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Drawing.Common.Tests (found 1934 of 1969 test cases)
  Starting:    System.Drawing.Common.Tests (parallel test collections = on, max threads = 2)
    System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6 [SKIP]
      Condition(s) not met: "IsOSX"
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SystemDefault) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAlias) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAliasGridFit) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixel) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixelGridFit) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: ClearTypeGridFit) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Bold | Italic | Strikeout, gdiCharSet: 255, gdiVerticalFont: True, expectedNamePrefix: "@", expectedWeight: 700) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(795,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 0, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(795,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 10, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(795,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Imaging.Tests.EncoderParameterTests.Ctor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues: -1) [SKIP]
      backwards compatibility on 32 bit platforms may not throw
    System.Drawing.Imaging.Tests.EncoderParameterTests.Ctor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues: -2147483648) [SKIP]
      backwards compatibility on 32 bit platforms may not throw
  Finished:    System.Drawing.Common.Tests
=== TEST EXECUTION SUMMARY ===
   System.Drawing.Common.Tests  Total: 4675, Errors: 0, Failed: 9, Skipped: 3, Time: 72.518s
----- end Tue 07/07/2020  9:15:21.31 ----- exit code 1 ----------------------------------------------------------
```

https://dev.azure.com/dnceng/public/_build/results?buildId=718587&view=ms.vss-test-web.build-test-results-tab&runId=22273786&resultId=178432&paneView=debug

category:correctness
theme:tail-call
skill-level:expert
cost:medium

### LINKED ISSUE #38892: [Linux/arm32] Hundreds of TailcallStress failures in libraries tests
The Linux/arm32 checked coreclr + release libraries test run with:
```
export COMPlus_TieredCompilation=0
export COMPlus_TailcallStress=1
```

has 579 failures (non-TailcallStress modes only have a few failures, with other issues opened to track them).

https://dev.azure.com/dnceng/public/_build/results?buildId=718587&view=ms.vss-test-web.build-test-results-tab&runId=22267618&paneView=debug

category:correctness
theme:tail-call
skill-level:expert
cost:medium

### LINKED ISSUE #39309: Test failure: System.Net.Tests.HttpListenerResponseHeadersTests.KeepAlive_SetDisposed_ThrowsObjectDisposedException
With:
```
COMPlus_TailcallStress=1
COMPlus_TieredCompilation=0
```

This test hangs. Fails on Windows x86, x64 and arm64 (at least).

https://dev.azure.com/dnceng/public/_build/results?buildId=728248&view=ms.vss-test-web.build-test-results-tab&runId=22547532&resultId=178566&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

This is release libraries, checked coreclr.

category:correctness
theme:testing
skill-level:expert
cost:medium

### LINKED ISSUE #39398: Test failure: System.Collections.Concurrent.Tests.ConcurrentStackTests.Add_TakeFromAnotherThread_ExpectedItemsTaken
The failure is not a consistent repro, but I see it fail about 50% of the time. It will fail without GCStress as well, if you are "lucky". The failure mode also changes, but always looks like one of the set of common GCStress asserts.

```
set COMPlus_TieredCompilation=0
set COMPlus_TailcallStress=1
set COMPlus_GCStress=C
```

```
C:\bugs\System.Collections.Concurrent.Tests\net5.0-Release>"C:\bugs\testhost\net5.0-Windows_NT-Release-arm64\dotnet.exe" exec --runtimeconfig System.Collections.Concurrent.Tests.runtimeconfig.json --depsfile System.Collections.Concurrent.Tests.deps.json xunit.console.dll System.Collections.Concurrent.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -verbose -parallel none -method "System.Collections.Concurrent.Tests.ConcurrentStackTests.Add_TakeFromAnotherThread_ExpectedItemsTaken"
  Discovering: System.Collections.Concurrent.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Concurrent.Tests (found 1 of 876 test case)
  Starting:    System.Collections.Concurrent.Tests (parallel test collections = off, max threads = 8)
    System.Collections.Concurrent.Tests.ConcurrentStackTests.Add_TakeFromAnotherThread_ExpectedItemsTaken [STARTING]

Assert failure(PID 11808 [0x00002e20], Thread: 11172 [0x2ba4]): RawGetMethodTable()

CORECLR! GetCLRRuntimeHost + 0x2B72F8 (0x00007ffa`ace95d78)
CORECLR! GetCLRRuntimeHost + 0x2B79E4 (0x00007ffa`ace96464)
CORECLR! GetCLRRuntimeHost + 0x29C748 (0x00007ffa`ace7b1c8)
CORECLR! GetCLRRuntimeHost + 0x2607C4 (0x00007ffa`ace3f244)
CORECLR! GetCLRRuntimeHost + 0x25F040 (0x00007ffa`ace3dac0)
CORECLR! GetCLRRuntimeHost + 0x25E9F0 (0x00007ffa`ace3d470)
CORECLR! GetCLRRuntimeHost + 0x25F108 (0x00007ffa`ace3db88)
CORECLR! GetCLRRuntimeHost + 0x25F340 (0x00007ffa`ace3ddc0)
CORECLR! GetCLRRuntimeHost + 0x25C830 (0x00007ffa`ace3b2b0)
CORECLR! GetCLRRuntimeHost + 0x2619E0 (0x00007ffa`ace40460)
    File: C:\gh\runtime\src\coreclr\src\gc\gc.cpp Line: 3677
    Image: C:\bugs\testhost\net5.0-Windows_NT-Release-arm64\dotnet.exe
```

In a separate run under a debugger, I see:
```
coreclr!WKS::my_get_size(void)+0x10
coreclr!WKS::gc_heap::find_first_object(unsigned char * start = 0x000001be`4ec4f460 "", unsigned char * first_object = 0x000001be`4ea01000 "???")+0x180
coreclr!WKS::gc_heap::find_object(unsigned char * interior = 0x000001be`4ec4f460 "")+0x190
coreclr!WKS::GCHeap::Promote(class Object ** ppObject = 0x000001be`4cba6098, struct ScanContext * sc = <Value unavailable error>, unsigned int flags = 1)+0x58
coreclr!PromoteCarefully(<function> * fn = 0x00007ffa`ab72b0b0, class Object ** ppObj = 0x000001be`4cba6098, struct ScanContext * sc = 0x000000a4`565bb7e0, unsigned int flags = 1)+0xb8
coreclr!GcEnumObject(void * pData = <Value unavailable error>, class OBJECTREF * pObj = 0x000001be`4cba6098, unsigned int flags = 1)+0x64
coreclr!GcInfoDecoder::ReportRegisterToGC(int regNum = 0n0, unsigned int gcFlags = 1, struct REGDISPLAY * pRD = <Value unavailable error>, unsigned int flags = 1, <function> * pCallBack = 0x00007ffa`ab5c8b70, void * hCallBack = 0x000000a4`565bb6e0)+0x288
coreclr!GcInfoDecoder::ReportSlotToGC(class GcSlotDecoder * slotDecoder = <Value unavailable error>, unsigned int slotIndex = 0, struct REGDISPLAY * pRD = 0x000000a4`565bad30, bool reportScratchSlots = true, unsigned int inputFlags = 1, <function> * pCallBack = 0x00007ffa`ab5c8b70, void * hCallBack = 0x000000a4`565bb6e0)+0xe4
coreclr!GcInfoDecoder::EnumerateLiveSlots(struct REGDISPLAY * pRD = 0x000000a4`565bad30, bool reportScratchSlots = true, unsigned int inputFlags = 1, <function> * pCallBack = 0x00007ffa`ab5c8b70, void * hCallBack = 0x000000a4`565bb6e0)+0xd3c
coreclr!EECodeManager::EnumGcRefs(struct REGDISPLAY * pRD = 0x000000a4`565bad30, class EECodeInfo * pCodeInfo = 0x000000a4`565ba800, unsigned int flags = 1, <function> * pCallBack = 0x00007ffa`ab5c8b70, void * hCallBack = 0x000000a4`565bb6e0, unsigned long relOffsetOverride = <Value unavailable error>)+0x2cc
coreclr!GcStackCrawlCallBack(class CrawlFrame * pCF = 0x000000a4`565ba5d0, void * pData = 0x000000a4`565bb6e0)+0x274
coreclr!Thread::MakeStackwalkerCallback(class CrawlFrame * pCF = 0x000000a4`565ba5d0, <function> * pCallback = 0x00007ffa`ab5c8ce0, void * pData = 0x000000a4`565bb6e0, unsigned int uFramesProcessed = <Value unavailable error>)+0x70
coreclr!Thread::StackWalkFramesEx(struct REGDISPLAY * pRD = 0x000000a4`565bad30, <function> * pCallback = 0x00007ffa`ab5c8ce0, void * pData = 0x000000a4`565bb6e0, unsigned int flags = <Value unavailable error>, class Frame * pStartFrame = 0x00000000`00000000)+0x174
coreclr!Thread::StackWalkFrames(<function> * pCallback = 0x00007ffa`ab5c8ce0, void * pData = 0x000000a4`565bb6e0, unsigned int flags = 0x8500, class Frame * pStartFrame = 0x00000000`00000000)+0x130
coreclr!ScanStackRoots(class Thread * pThread = 0x000001be`4ca38270, <function> * fn = 0x00007ffa`ab72b0b0, struct ScanContext * sc = 0x000000a4`565bb7e0)+0x1b4
coreclr!GCToEEInterface::GcScanRoots(<function> * fn = 0x00007ffa`ab72b0b0, int condemned = 0n2, int max_gen = 0n2, struct ScanContext * sc = 0x000000a4`565bb7e0)+0x19c
coreclr!WKS::gc_heap::mark_phase(int condemned_gen_number = 0n2, int mark_only_p = 0n0)+0x238
coreclr!WKS::gc_heap::gc1(void)+0x238
coreclr!WKS::gc_heap::garbage_collect(int n = <Value unavailable error>)+0x4cc
coreclr!WKS::GCHeap::GarbageCollectGeneration(unsigned int gen = 2, gc_reason reason = reason_gcstress (0n8))+0x3b4
coreclr!WKS::GCHeap::GarbageCollect(int generation = <Value unavailable error>, bool low_memory_p = <Value unavailable error>, int mode = 0n-2147483648)+0x12c
coreclr!WKS::GCHeap::StressHeap(struct gc_alloc_context * context = <Value unavailable error>)+0x5d4
coreclr!DoGcStress(struct _CONTEXT * regs = 0x000001be`4cba6090, class NativeCodeVersion * nativeCodeVersion = <Value unavailable error>)+0x2f0
coreclr!Thread::RedirectedHandledJITCase(Thread::RedirectReason reason = RedirectReason_GCStress (0n3))+0x17c
coreclr!RedirectedHandledJITCaseForGCStress_Stub(void)+0x28
System_Private_CoreLib!System.Collections.Generic.HashSet`1[[System.__Canon, System.Private.CoreLib]].AddIfNotPresent(<Win32 error 0n318>)+0xffffffff`a26db0c8
System_Collections_Concurrent_Tests!System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.Add_TakeFromAnotherThread_ExpectedItemsTaken(<Win32 error 0n318>)+0x164
coreclr!CallDescrWorkerInternal(void)+0x84
coreclr!CallDescrWorkerWithHandler(struct CallDescrData * pCallDescrData = 0x000000a4`565bc540, int fCriticalCall = 0n0)+0xd0
coreclr!CallDescrWorkerReflectionWrapper::__l6::__Body::Run(void)+0x8
```

and the function being examined:
```
0:000> !u -gcinfo 7ffa4d67f058
Normal JIT generated code
System.Collections.Generic.HashSet`1[[System.Int32, System.Private.CoreLib]].AddIfNotPresent(Int32, Int32 ByRef)
ilAddr is 00007FFAAA92B2C8 pImport is 000001E307EFE780
Begin 00007FFA4D67E958, size 760
Prolog size: 0
Security object: <none>
GS cookie: <none>
PSPSym: <none>
Generics inst context: <none>
PSP slot: <none>
GenericInst slot: <none>
Varargs: 0
Frame pointer: Fp
Has tailcalls: 0
Size of parameter area: 0
Return Kind: Scalar
Code size: 760
00007ffa`4d67e958 a9b57bfd stp         fp,lr,[sp,#-0xB0]!
00007ffa`4d67e95c a90653f3 stp         x19,x20,[sp,#0x60]
00007ffa`4d67e960 a9075bf5 stp         x21,x22,[sp,#0x70]
00007ffa`4d67e964 a90863f7 stp         x23,x24,[sp,#0x80]
00007ffa`4d67e968 a9096bf9 stp         x25,x26,[sp,#0x90]
00007ffa`4d67e96c a90a73fb stp         x27,x28,[sp,#0xA0]
00007ffa`4d67e970 910003fd mov         fp,sp
00007ffa`4d67e974 aa0003f3 mov         x19,x0
00007ffa`4d67e978 2a0103f4 mov         w20,w1
00007ffa`4d67e97c aa0203f5 mov         x21,x2
00000028 interruptible
00000028 +X19 +X21(interior)
00007ffa`4d67e980 f9400660 ldr         x0,[x19,#8]
0000002c +X0
00007ffa`4d67e984 b5000080 cbnz        x0,00007FFA4D67E994
00000030 -X0
00007ffa`4d67e988 aa1303e0 mov         x0,x19
00000034 +X0
00007ffa`4d67e98c 52800001 mov         w1,#0
00007ffa`4d67e990 97ffe08a bl          00007FFA4D676BB8
0000003c -X0
00007ffa`4d67e994 f9400660 ldr         x0,[x19,#8]
00000040 +X0
00007ffa`4d67e998 f100001f cmp         x0,#0
00007ffa`4d67e99c 9a9f07e0 csetne      x0
00000048 -X0
00007ffa`4d67e9a0 d2860c01 mov         x1,#0x3060
00007ffa`4d67e9a4 f2abd401 movk        x1,#0x5EA0,lsl #0x10
00007ffa`4d67e9a8 f2c037c1 movk        x1,#0x1BE,lsl #0x20
00007ffa`4d67e9ac f9400036 ldr         x22,[x1]
00000058 +X22
00007ffa`4d67e9b0 aa1603f7 mov         x23,x22
0000005c +X23
00007ffa`4d67e9b4 35000200 cbnz        w0,00007FFA4D67E9F4
00007ffa`4d67e9b8 d2800500 mov         x0,#0x28 (gcstress)
00007ffa`4d67e9bc f2a97700 movk        x0,#0x4BB8,lsl #0x10 (gcstress)
00007ffa`4d67e9c0 f2cfff40 movk        x0,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67e9c4 5280dde1 mov         w1,#0x6EF (gcstress)
00007ffa`4d67e9c8 97957fa6 bl          00007FFA4BCE2C74 (gcstress)
00007ffa`4d67e9cc d284d200 mov         x0,#0x2690 (gcstress)
00007ffa`4d67e9d0 f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67e9d4 f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67e9d8 c8dffc00 ldar        x0,[x0] (gcstress)
00000084 +X0
00007ffa`4d67e9dc aa1703e1 mov         x1,x23 (gcstress)
00000088 +X1
00007ffa`4d67e9e0 aa1603e2 mov         x2,x22 (gcstress)
0000008c +X2
00007ffa`4d67e9e4 f9400003 ldr         x3,[x0] (gcstress)
00007ffa`4d67e9e8 f9402463 ldr         x3,[x3,#0x48] (gcstress)
00007ffa`4d67e9ec f9401063 ldr         x3,[x3,#0x20] (gcstress)
00007ffa`4d67e9f0 d63f0060 blr         x3 (gcstress)
0000009c -X23 -X22 -X2 -X1 -X0
00007ffa`4d67e9f4 f9400a76 ldr         x22,[x19,#0x10]
000000a0 +X22
00007ffa`4d67e9f8 d2860c00 mov         x0,#0x3060
00007ffa`4d67e9fc f2abd400 movk        x0,#0x5EA0,lsl #0x10
00007ffa`4d67ea00 f2c037c0 movk        x0,#0x1BE,lsl #0x20
00007ffa`4d67ea04 f9400017 ldr         x23,[x0]
000000b0 +X23
00007ffa`4d67ea08 b5000276 cbnz        x22,00007FFA4D67EA54
00007ffa`4d67ea0c d2800500 mov         x0,#0x28 (gcstress)
00007ffa`4d67ea10 f2a97700 movk        x0,#0x4BB8,lsl #0x10 (gcstress)
00007ffa`4d67ea14 f2cfff40 movk        x0,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67ea18 5280dde1 mov         w1,#0x6EF (gcstress)
00007ffa`4d67ea1c 97957f91 bl          00007FFA4BCE2C74 (gcstress)
00007ffa`4d67ea20 d284d200 mov         x0,#0x2690 (gcstress)
00007ffa`4d67ea24 f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ea28 f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ea2c c8dffc00 ldar        x0,[x0] (gcstress)
000000d8 +X0
00007ffa`4d67ea30 d2860e01 mov         x1,#0x3070 (gcstress)
00007ffa`4d67ea34 f2abd401 movk        x1,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ea38 f2c037c1 movk        x1,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ea3c f9400021 ldr         x1,[x1] (gcstress)
000000e8 +X1
00007ffa`4d67ea40 aa1703e2 mov         x2,x23 (gcstress)
000000ec +X2
00007ffa`4d67ea44 f9400003 ldr         x3,[x0] (gcstress)
00007ffa`4d67ea48 f9402463 ldr         x3,[x3,#0x48] (gcstress)
00007ffa`4d67ea4c f9401063 ldr         x3,[x3,#0x20] (gcstress)
00007ffa`4d67ea50 d63f0060 blr         x3 (gcstress)
000000fc -X23 -X2 -X1 -X0
00007ffa`4d67ea54 f9400e77 ldr         x23,[x19,#0x18]
00000100 +X23
00007ffa`4d67ea58 52800018 mov         w24,#0
00007ffa`4d67ea5c b5000db7 cbnz        x23,00007FFA4D67EC10
00000108 -X23
00007ffa`4d67ea60 2a1403f9 mov         w25,w20
00007ffa`4d67ea64 f9400677 ldr         x23,[x19,#8]
00000110 +X23
00007ffa`4d67ea68 b9400afa ldr         w26,[x23,#8]
00007ffa`4d67ea6c 2a1a03fb mov         w27,w26
00007ffa`4d67ea70 f940167c ldr         x28,[x19,#0x28]
00007ffa`4d67ea74 d2860c00 mov         x0,#0x3060
00007ffa`4d67ea78 f2abd400 movk        x0,#0x5EA0,lsl #0x10
00007ffa`4d67ea7c f2c037c0 movk        x0,#0x1BE,lsl #0x20
00007ffa`4d67ea80 f9400002 ldr         x2,[x0]
0000012c +X2
00007ffa`4d67ea84 f90023a2 str         x2,[fp,#0x40]
00000130 +Fp+40
00007ffa`4d67ea88 f9001fa2 str         x2,[fp,#0x38]
00000134 +Fp+38
00007ffa`4d67ea8c 12b00000 mov         w0,#-0x80000001
00007ffa`4d67ea90 6b00037f cmp         w27,w0
00007ffa`4d67ea94 54000209 bls         00007FFA4D67EAD4
00000140 -X2
00007ffa`4d67ea98 d2800500 mov         x0,#0x28 (gcstress)
00007ffa`4d67ea9c f2a97700 movk        x0,#0x4BB8,lsl #0x10 (gcstress)
00007ffa`4d67eaa0 f2cfff40 movk        x0,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67eaa4 5280dde1 mov         w1,#0x6EF (gcstress)
00007ffa`4d67eaa8 97957f6e bl          00007FFA4BCE2C74 (gcstress)
00007ffa`4d67eaac d284d200 mov         x0,#0x2690 (gcstress)
00007ffa`4d67eab0 f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67eab4 f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67eab8 c8dffc00 ldar        x0,[x0] (gcstress)
00000164 +X0
00007ffa`4d67eabc f94023a1 ldr         x1,[fp,#0x40] (gcstress)
00000168 +X1
00007ffa`4d67eac0 f9401fa2 ldr         x2,[fp,#0x38] (gcstress)
0000016c +X2
00007ffa`4d67eac4 f9400003 ldr         x3,[x0] (gcstress)
00007ffa`4d67eac8 f9402463 ldr         x3,[x3,#0x48] (gcstress)
00007ffa`4d67eacc f9401063 ldr         x3,[x3,#0x20] (gcstress)
00000178 -Fp+40 -Fp+38
00007ffa`4d67ead0 d63f0060 blr         x3 (gcstress)
0000017c -X2 -X1 -X0
00007ffa`4d67ead4 2a1403e0 mov         w0,w20
00007ffa`4d67ead8 9b007f80 mul         x0,x28,x0
00007ffa`4d67eadc d360fc00 lsr         x0,x0,#0x20
00007ffa`4d67eae0 91000400 add         x0,x0,#1
00007ffa`4d67eae4 2a1b03e1 mov         w1,w27
00007ffa`4d67eae8 9b017c00 mul         x0,x0,x1
00007ffa`4d67eaec d360fc00 lsr         x0,x0,#0x20
00007ffa`4d67eaf0 2a0003fc mov         w28,w0
00007ffa`4d67eaf4 7100037f cmp         w27,#0
00007ffa`4d67eaf8 54002d60 beq         00007FFA4D67F0A4
00007ffa`4d67eafc 1adb0a80 udiv        w0,w20,w27
00007ffa`4d67eb00 1b1b7c00 mul         w0,w0,w27
00007ffa`4d67eb04 4b000280 sub         w0,w20,w0
00007ffa`4d67eb08 6b1c001f cmp         w0,w28
00007ffa`4d67eb0c 9a9f17e0 cseteq      x0
00007ffa`4d67eb10 d2860c01 mov         x1,#0x3060
00007ffa`4d67eb14 f2abd401 movk        x1,#0x5EA0,lsl #0x10
00007ffa`4d67eb18 f2c037c1 movk        x1,#0x1BE,lsl #0x20
00007ffa`4d67eb1c f940003b ldr         x27,[x1]
000001c8 +X27
00007ffa`4d67eb20 f9001bbb str         x27,[fp,#0x30]
000001cc +Fp+30
00007ffa`4d67eb24 35000200 cbnz        w0,00007FFA4D67EB64
00007ffa`4d67eb28 d2800500 mov         x0,#0x28 (gcstress)
00007ffa`4d67eb2c f2a97700 movk        x0,#0x4BB8,lsl #0x10 (gcstress)
00007ffa`4d67eb30 f2cfff40 movk        x0,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67eb34 5280dde1 mov         w1,#0x6EF (gcstress)
00007ffa`4d67eb38 97957f4a bl          00007FFA4BCE2C74 (gcstress)
00007ffa`4d67eb3c d284d200 mov         x0,#0x2690 (gcstress)
00007ffa`4d67eb40 f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67eb44 f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67eb48 c8dffc00 ldar        x0,[x0] (gcstress)
000001f4 +X0
00007ffa`4d67eb4c f9401ba1 ldr         x1,[fp,#0x30] (gcstress)
000001f8 +X1
00007ffa`4d67eb50 aa1b03e2 mov         x2,x27 (gcstress)
000001fc +X2
00007ffa`4d67eb54 f9400003 ldr         x3,[x0] (gcstress)
00007ffa`4d67eb58 f9402463 ldr         x3,[x3,#0x48] (gcstress)
00007ffa`4d67eb5c f9401063 ldr         x3,[x3,#0x20] (gcstress)
00000208 -Fp+30
00007ffa`4d67eb60 d63f0060 blr         x3 (gcstress)
0000020c -X27 -X2 -X1 -X0
00007ffa`4d67eb64 6b1a039f cmp         w28,w26
00007ffa`4d67eb68 54002a42 bhs         00007FFA4D67F0B0
00007ffa`4d67eb6c 93407f80 sxtw        x0,w28
00007ffa`4d67eb70 d37ef400 lsl         x0,x0,#2
00007ffa`4d67eb74 91004000 add         x0,x0,#0x10
00007ffa`4d67eb78 8b0002fa add         x26,x23,x0
00000224 +X26(interior)
00007ffa`4d67eb7c b9400340 ldr         w0,[x26]
00007ffa`4d67eb80 5100041b sub         w27,w0,#1
00007ffa`4d67eb84 7100037f cmp         w27,#0
00007ffa`4d67eb88 540012cb blt         00007FFA4D67EDE0
00007ffa`4d67eb8c b9400ac0 ldr         w0,[x22,#8] (gcstress)
00007ffa`4d67eb90 2a0003f7 mov         w23,w0 (gcstress)
0000023c -X23
00007ffa`4d67eb94 6b17037f cmp         w27,w23 (gcstress)
00007ffa`4d67eb98 540028c2 bhs         00007FFA4D7834C4 (gcstress)
00007ffa`4d67eb9c 93407f60 sxtw        x0,w27 (gcstress)
00007ffa`4d67eba0 d2800061 mov         x1,#3 (gcstress)
00007ffa`4d67eba4 9b017c00 mul         x0,x0,x1 (gcstress)
00007ffa`4d67eba8 d37ef400 lsl         x0,x0,#2 (gcstress)
00007ffa`4d67ebac 91004000 add         x0,x0,#0x10 (gcstress)
00007ffa`4d67ebb0 8b0002c0 add         x0,x22,x0 (gcstress)
0000025c +X0(interior)
00007ffa`4d67ebb4 b9400001 ldr         w1,[x0] (gcstress)
00007ffa`4d67ebb8 6b14003f cmp         w1,w20 (gcstress)
00007ffa`4d67ebbc 540000a1 bne         00007FFA4D782FE4 (gcstress)
00007ffa`4d67ebc0 b9400801 ldr         w1,[x0,#8] (gcstress)
00007ffa`4d67ebc4 6b19003f cmp         w1,w25 (gcstress)
00007ffa`4d67ebc8 9a9f17e1 cseteq      x1 (gcstress)
00007ffa`4d67ebcc 35000101 cbnz        w1,00007FFA4D783000 (gcstress)
00007ffa`4d67ebd0 b940041b ldr         w27,[x0,#4] (gcstress)
00007ffa`4d67ebd4 11000718 add         w24,w24,#1 (gcstress)
00007ffa`4d67ebd8 6b1802ff cmp         w23,w24 (gcstress)
00007ffa`4d67ebdc 54002663 blo         00007FFA4D7834BC (gcstress)
00000288 -X0(interior)
00007ffa`4d67ebe0 7100037f cmp         w27,#0 (gcstress)
00007ffa`4d67ebe4 54fffd8a bge         00007FFA4D782FA8 (gcstress)
00007ffa`4d67ebe8 1400007e b           00007FFA4D7831F4 (gcstress)
00000294 -X22 -X19 -X26(interior)
00007ffa`4d67ebec b90002bb str         w27,[x21] (gcstress)
00007ffa`4d67ebf0 52800000 mov         w0,#0 (gcstress)
0000029c not interruptible
0000029c -X21(interior)
00007ffa`4d67ebf4 a94a73fb ldp         x27,x28,[sp,#0xA0]
00007ffa`4d67ebf8 a9496bf9 ldp         x25,x26,[sp,#0x90]
00007ffa`4d67ebfc a94863f7 ldp         x23,x24,[sp,#0x80]
00007ffa`4d67ec00 a9475bf5 ldp         x21,x22,[sp,#0x70]
00007ffa`4d67ec04 a94653f3 ldp         x19,x20,[sp,#0x60]
00007ffa`4d67ec08 a8cb7bfd ldp         fp,lr,[sp],#0xB0
00007ffa`4d67ec0c d65f03c0 ret
000002b8 interruptible
000002b8 +X23 +X22 +X19 +X21(interior)
00007ffa`4d67ec10 aa1703e0 mov         x0,x23 (gcstress)
000002bc +X0
00007ffa`4d67ec14 2a1403e1 mov         w1,w20 (gcstress)
00007ffa`4d67ec18 d2872a0b mov         x11,#0x3950 (gcstress)
00007ffa`4d67ec1c f2a974ab movk        x11,#0x4BA5,lsl #0x10 (gcstress)
00007ffa`4d67ec20 f2cfff4b movk        x11,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67ec24 f9400162 ldr         x2,[x11] (gcstress)
00007ffa`4d67ec28 d63f0040 blr         x2 (gcstress)
000002d4 -X0
00007ffa`4d67ec2c 2a0003f9 mov         w25,w0 (gcstress)
00007ffa`4d67ec30 f940067a ldr         x26,[x19,#8] (gcstress)
000002dc +X26
00007ffa`4d67ec34 b9400b5b ldr         w27,[x26,#8] (gcstress)
00007ffa`4d67ec38 2a1b03fc mov         w28,w27 (gcstress)
00007ffa`4d67ec3c f9401662 ldr         x2,[x19,#0x28] (gcstress)
00007ffa`4d67ec40 f9002fa2 str         x2,[fp,#0x58] (gcstress)
00007ffa`4d67ec44 d2860c00 mov         x0,#0x3060 (gcstress)
00007ffa`4d67ec48 f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ec4c f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ec50 f9400003 ldr         x3,[x0] (gcstress)
000002fc +X3
00007ffa`4d67ec54 f90017a3 str         x3,[fp,#0x28] (gcstress)
00000300 +Fp+28
00007ffa`4d67ec58 f90013a3 str         x3,[fp,#0x20] (gcstress)
00000304 +Fp+20
00007ffa`4d67ec5c 12b00000 mov         w0,#-0x80000001 (gcstress)
00007ffa`4d67ec60 6b00039f cmp         w28,w0 (gcstress)
00007ffa`4d67ec64 54000209 bls         00007FFA4D7830B8 (gcstress)
00000310 -X3
00007ffa`4d67ec68 d2800500 mov         x0,#0x28 (gcstress)
00007ffa`4d67ec6c f2a97700 movk        x0,#0x4BB8,lsl #0x10 (gcstress)
00007ffa`4d67ec70 f2cfff40 movk        x0,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67ec74 5280dde1 mov         w1,#0x6EF (gcstress)
00007ffa`4d67ec78 97957efa bl          00007FFA4BCE2C74 (gcstress)
00007ffa`4d67ec7c d284d200 mov         x0,#0x2690 (gcstress)
00007ffa`4d67ec80 f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ec84 f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ec88 c8dffc00 ldar        x0,[x0] (gcstress)
00000334 +X0
00007ffa`4d67ec8c f94017a1 ldr         x1,[fp,#0x28] (gcstress)
00000338 +X1
00007ffa`4d67ec90 f94013a2 ldr         x2,[fp,#0x20] (gcstress)
0000033c +X2
00007ffa`4d67ec94 f9400003 ldr         x3,[x0] (gcstress)
00007ffa`4d67ec98 f9402463 ldr         x3,[x3,#0x48] (gcstress)
00007ffa`4d67ec9c f9401063 ldr         x3,[x3,#0x20] (gcstress)
00000348 -Fp+28 -Fp+20
00007ffa`4d67eca0 d63f0060 blr         x3 (gcstress)
0000034c -X2 -X1 -X0
00007ffa`4d67eca4 2a1903e0 mov         w0,w25 (gcstress)
00007ffa`4d67eca8 f9402fa2 ldr         x2,[fp,#0x58] (gcstress)
00007ffa`4d67ecac 9b007c40 mul         x0,x2,x0 (gcstress)
00007ffa`4d67ecb0 d360fc00 lsr         x0,x0,#0x20 (gcstress)
00007ffa`4d67ecb4 91000400 add         x0,x0,#1 (gcstress)
00007ffa`4d67ecb8 2a1c03e1 mov         w1,w28 (gcstress)
00007ffa`4d67ecbc 9b017c00 mul         x0,x0,x1 (gcstress)
00007ffa`4d67ecc0 d360fc00 lsr         x0,x0,#0x20 (gcstress)
00007ffa`4d67ecc4 2a0003e2 mov         w2,w0 (gcstress)
00007ffa`4d67ecc8 7100039f cmp         w28,#0 (gcstress)
00007ffa`4d67eccc 54001ec0 beq         00007FFA4D7834B8 (gcstress)
00007ffa`4d67ecd0 1adc0b20 udiv        w0,w25,w28 (gcstress)
00007ffa`4d67ecd4 1b1c7c00 mul         w0,w0,w28 (gcstress)
00007ffa`4d67ecd8 4b000320 sub         w0,w25,w0 (gcstress)
00007ffa`4d67ecdc b90057a2 str         w2,[fp,#0x54] (gcstress)
00007ffa`4d67ece0 6b02001f cmp         w0,w2 (gcstress)
00007ffa`4d67ece4 9a9f17e0 cseteq      x0 (gcstress)
00007ffa`4d67ece8 d2860c01 mov         x1,#0x3060 (gcstress)
00007ffa`4d67ecec f2abd401 movk        x1,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ecf0 f2c037c1 movk        x1,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ecf4 f940003c ldr         x28,[x1] (gcstress)
000003a0 +X28
00007ffa`4d67ecf8 f9000fbc str         x28,[fp,#0x18] (gcstress)
000003a4 +Fp+18
00007ffa`4d67ecfc 35000200 cbnz        w0,00007FFA4D783150 (gcstress)
00007ffa`4d67ed00 d2800500 mov         x0,#0x28 (gcstress)
00007ffa`4d67ed04 f2a97700 movk        x0,#0x4BB8,lsl #0x10 (gcstress)
00007ffa`4d67ed08 f2cfff40 movk        x0,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67ed0c 5280dde1 mov         w1,#0x6EF (gcstress)
00007ffa`4d67ed10 97957ed4 bl          00007FFA4BCE2C74 (gcstress)
00007ffa`4d67ed14 d284d200 mov         x0,#0x2690 (gcstress)
00007ffa`4d67ed18 f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ed1c f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ed20 c8dffc00 ldar        x0,[x0] (gcstress)
000003cc +X0
00007ffa`4d67ed24 f9400fa1 ldr         x1,[fp,#0x18] (gcstress)
000003d0 +X1
00007ffa`4d67ed28 aa1c03e2 mov         x2,x28 (gcstress)
000003d4 +X2
00007ffa`4d67ed2c f9400003 ldr         x3,[x0] (gcstress)
00007ffa`4d67ed30 f9402463 ldr         x3,[x3,#0x48] (gcstress)
00007ffa`4d67ed34 f9401063 ldr         x3,[x3,#0x20] (gcstress)
000003e0 -Fp+18
00007ffa`4d67ed38 d63f0060 blr         x3 (gcstress)
000003e4 -X28 -X2 -X1 -X0
00007ffa`4d67ed3c b94057a2 ldr         w2,[fp,#0x54] (gcstress)
00007ffa`4d67ed40 6b1b005f cmp         w2,w27 (gcstress)
00007ffa`4d67ed44 54001b62 bhs         00007FFA4D7834C4 (gcstress)
00007ffa`4d67ed48 93407c40 sxtw        x0,w2 (gcstress)
00007ffa`4d67ed4c d37ef400 lsl         x0,x0,#2 (gcstress)
00007ffa`4d67ed50 91004000 add         x0,x0,#0x10 (gcstress)
00007ffa`4d67ed54 8b00035a add         x26,x26,x0 (gcstress)
00000400 -X26 +X26(interior)
00007ffa`4d67ed58 b9400340 ldr         w0,[x26] (gcstress)
00007ffa`4d67ed5c 5100041c sub         w28,w0,#1 (gcstress)
00007ffa`4d67ed60 7100039f cmp         w28,#0 (gcstress)
00007ffa`4d67ed64 540003eb blt         00007FFA4D7831F4 (gcstress)
00007ffa`4d67ed68 b9400ac1 ldr         w1,[x22,#8] (gcstress)
00007ffa`4d67ed6c 2a0103fb mov         w27,w1 (gcstress)
00007ffa`4d67ed70 6b1b039f cmp         w28,w27 (gcstress)
00007ffa`4d67ed74 540019e2 bhs         00007FFA4D7834C4 (gcstress)
00007ffa`4d67ed78 93407f81 sxtw        x1,w28 (gcstress)
00007ffa`4d67ed7c d2800060 mov         x0,#3 (gcstress)
00007ffa`4d67ed80 9b007c21 mul         x1,x1,x0 (gcstress)
00007ffa`4d67ed84 d37ef421 lsl         x1,x1,#2 (gcstress)
00007ffa`4d67ed88 91004021 add         x1,x1,#0x10 (gcstress)
00007ffa`4d67ed8c 8b0102c3 add         x3,x22,x1 (gcstress)
00000438 +X3(interior)
00007ffa`4d67ed90 b9400061 ldr         w1,[x3] (gcstress)
00007ffa`4d67ed94 6b19003f cmp         w1,w25 (gcstress)
00007ffa`4d67ed98 54000181 bne         00007FFA4D7831DC (gcstress)
00007ffa`4d67ed9c f90027a3 str         x3,[fp,#0x48] (gcstress)
00000448 +Fp+48(interior)
00007ffa`4d67eda0 b9400861 ldr         w1,[x3,#8] (gcstress)
00007ffa`4d67eda4 aa1703e0 mov         x0,x23 (gcstress)
00000450 +X0
00007ffa`4d67eda8 2a1403e2 mov         w2,w20 (gcstress)
00007ffa`4d67edac d2872b0b mov         x11,#0x3958 (gcstress)
00007ffa`4d67edb0 f2a974ab movk        x11,#0x4BA5,lsl #0x10 (gcstress)
00007ffa`4d67edb4 f2cfff4b movk        x11,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67edb8 f9400164 ldr         x4,[x11] (gcstress)
00007ffa`4d67edbc d63f0080 blr         x4 (gcstress)
00000468 -X0 -X3(interior)
00007ffa`4d67edc0 f94027a3 ldr         x3,[fp,#0x48] (gcstress)
0000046c +X3(interior)
00007ffa`4d67edc4 35000820 cbnz        w0,00007FFA4D7832DC (gcstress)
00000470 -Fp+48(interior)
00007ffa`4d67edc8 b940047c ldr         w28,[x3,#4] (gcstress)
00007ffa`4d67edcc 11000718 add         w24,w24,#1 (gcstress)
00007ffa`4d67edd0 6b18037f cmp         w27,w24 (gcstress)
00007ffa`4d67edd4 540016a3 blo         00007FFA4D7834BC (gcstress)
00000480 -X3(interior)
00007ffa`4d67edd8 7100039f cmp         w28,#0 (gcstress)
00007ffa`4d67eddc 54fffcaa bge         00007FFA4D783184 (gcstress)
00000488 -X23
00007ffa`4d67ede0 b9403a60 ldr         w0,[x19,#0x38]
00007ffa`4d67ede4 7100001f cmp         w0,#0
00007ffa`4d67ede8 5400082d ble         00007FFA4D67EEEC
00007ffa`4d67edec b9403661 ldr         w1,[x19,#0x34] (gcstress)
00007ffa`4d67edf0 2a0103f8 mov         w24,w1 (gcstress)
00007ffa`4d67edf4 51000400 sub         w0,w0,#1 (gcstress)
00007ffa`4d67edf8 b9003a60 str         w0,[x19,#0x38] (gcstress)
00007ffa`4d67edfc b9400adb ldr         w27,[x22,#8] (gcstress)
00007ffa`4d67ee00 6b1b003f cmp         w1,w27 (gcstress)
00007ffa`4d67ee04 54001562 bhs         00007FFA4D7834C4 (gcstress)
00007ffa`4d67ee08 93407c20 sxtw        x0,w1 (gcstress)
00007ffa`4d67ee0c d2800061 mov         x1,#3 (gcstress)
00007ffa`4d67ee10 9b017c00 mul         x0,x0,x1 (gcstress)
00007ffa`4d67ee14 d37ef400 lsl         x0,x0,#2 (gcstress)
00007ffa`4d67ee18 91004000 add         x0,x0,#0x10 (gcstress)
00007ffa`4d67ee1c 8b0002c0 add         x0,x22,x0 (gcstress)
000004c8 +X0(interior)
00007ffa`4d67ee20 b9400400 ldr         w0,[x0,#4] (gcstress)
000004cc -X0(interior)
00007ffa`4d67ee24 4b0003e0 neg         w0,w0 (gcstress)
00007ffa`4d67ee28 51000c00 sub         w0,w0,#3 (gcstress)
00007ffa`4d67ee2c 3100041f cmn         w0,#1 (gcstress)
00007ffa`4d67ee30 9a9fb7e0 csetge      x0 (gcstress)
00007ffa`4d67ee34 d2860c01 mov         x1,#0x3060 (gcstress)
00007ffa`4d67ee38 f2abd401 movk        x1,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ee3c f2c037c1 movk        x1,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ee40 f9400037 ldr         x23,[x1] (gcstress)
000004ec +X23
00007ffa`4d67ee44 35000260 cbnz        w0,00007FFA4D7832A4 (gcstress)
00007ffa`4d67ee48 d2800500 mov         x0,#0x28 (gcstress)
00007ffa`4d67ee4c f2a97700 movk        x0,#0x4BB8,lsl #0x10 (gcstress)
00007ffa`4d67ee50 f2cfff40 movk        x0,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67ee54 5280dde1 mov         w1,#0x6EF (gcstress)
00007ffa`4d67ee58 97957e82 bl          00007FFA4BCE2C74 (gcstress)
00007ffa`4d67ee5c d284d200 mov         x0,#0x2690 (gcstress)
00007ffa`4d67ee60 f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ee64 f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ee68 c8dffc00 ldar        x0,[x0] (gcstress)
00000514 +X0
00007ffa`4d67ee6c d2860f01 mov         x1,#0x3078 (gcstress)
00007ffa`4d67ee70 f2abd401 movk        x1,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ee74 f2c037c1 movk        x1,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ee78 f9400021 ldr         x1,[x1] (gcstress)
00000524 +X1
00007ffa`4d67ee7c aa1703e2 mov         x2,x23 (gcstress)
00000528 +X2
00007ffa`4d67ee80 f9400003 ldr         x3,[x0] (gcstress)
00007ffa`4d67ee84 f9402463 ldr         x3,[x3,#0x48] (gcstress)
00007ffa`4d67ee88 f9401063 ldr         x3,[x3,#0x20] (gcstress)
00007ffa`4d67ee8c d63f0060 blr         x3 (gcstress)
00000538 -X23 -X2 -X1 -X0
00007ffa`4d67ee90 b9403660 ldr         w0,[x19,#0x34] (gcstress)
00007ffa`4d67ee94 6b1b001f cmp         w0,w27 (gcstress)
00007ffa`4d67ee98 540010c2 bhs         00007FFA4D7834C4 (gcstress)
00007ffa`4d67ee9c 93407c00 sxtw        x0,w0 (gcstress)
00007ffa`4d67eea0 d2800061 mov         x1,#3 (gcstress)
00007ffa`4d67eea4 9b017c00 mul         x0,x0,x1 (gcstress)
00007ffa`4d67eea8 d37ef400 lsl         x0,x0,#2 (gcstress)
00007ffa`4d67eeac 91004000 add         x0,x0,#0x10 (gcstress)
00007ffa`4d67eeb0 8b0002c0 add         x0,x22,x0 (gcstress)
0000055c +X0(interior)
00007ffa`4d67eeb4 b9400400 ldr         w0,[x0,#4] (gcstress)
00000560 -X0(interior)
00007ffa`4d67eeb8 4b0003e0 neg         w0,w0 (gcstress)
00007ffa`4d67eebc 51000c00 sub         w0,w0,#3 (gcstress)
00007ffa`4d67eec0 b9003660 str         w0,[x19,#0x34] (gcstress)
00007ffa`4d67eec4 1400005c b           00007FFA4D783448 (gcstress)
00000570 -X22 -X19 -X26(interior)
00007ffa`4d67eec8 b90002bc str         w28,[x21] (gcstress)
00007ffa`4d67eecc 52800000 mov         w0,#0 (gcstress)
00000578 not interruptible
00000578 -X21(interior)
00007ffa`4d67eed0 a94a73fb ldp         x27,x28,[sp,#0xA0]
00007ffa`4d67eed4 a9496bf9 ldp         x25,x26,[sp,#0x90]
00007ffa`4d67eed8 a94863f7 ldp         x23,x24,[sp,#0x80]
00007ffa`4d67eedc a9475bf5 ldp         x21,x22,[sp,#0x70]
00007ffa`4d67eee0 a94653f3 ldp         x19,x20,[sp,#0x60]
00007ffa`4d67eee4 a8cb7bfd ldp         fp,lr,[sp],#0xB0
00007ffa`4d67eee8 d65f03c0 ret
00000594 interruptible
00000594 +X22 +X19 +X26(interior) +X21(interior)
00007ffa`4d67eeec b9403260 ldr         w0,[x19,#0x30]
00007ffa`4d67eef0 2a0003f8 mov         w24,w0
00007ffa`4d67eef4 b9400adb ldr         w27,[x22,#8]
00007ffa`4d67eef8 6b18037f cmp         w27,w24
00007ffa`4d67eefc 54000961 bne         00007FFA4D67F028
00007ffa`4d67ef00 9795b3b2 bl          00007FFA4BCF01DC (gcstress)
000005ac -X22 -X26(interior)
00007ffa`4d67ef04 2a0003e1 mov         w1,w0 (gcstress)
00007ffa`4d67ef08 aa1303e0 mov         x0,x19 (gcstress)
000005b4 +X0
00007ffa`4d67ef0c 52800002 mov         w2,#0 (gcstress)
00007ffa`4d67ef10 97ffdf18 bl          00007FFA4D77AF84 (gcstress)
000005bc -X0
00007ffa`4d67ef14 f940067a ldr         x26,[x19,#8] (gcstress)
000005c0 +X26
00007ffa`4d67ef18 b9400b56 ldr         w22,[x26,#8] (gcstress)
00007ffa`4d67ef1c 2a1603fb mov         w27,w22 (gcstress)
00007ffa`4d67ef20 f940167c ldr         x28,[x19,#0x28] (gcstress)
00007ffa`4d67ef24 d2860c00 mov         x0,#0x3060 (gcstress)
00007ffa`4d67ef28 f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ef2c f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ef30 f9400017 ldr         x23,[x0] (gcstress)
000005dc +X23
00007ffa`4d67ef34 f9000bb7 str         x23,[fp,#0x10] (gcstress)
000005e0 +Fp+10
00007ffa`4d67ef38 12b00000 mov         w0,#-0x80000001 (gcstress)
00007ffa`4d67ef3c 6b00037f cmp         w27,w0 (gcstress)
00007ffa`4d67ef40 54000209 bls         00007FFA4D783394 (gcstress)
00007ffa`4d67ef44 d2800500 mov         x0,#0x28 (gcstress)
00007ffa`4d67ef48 f2a97700 movk        x0,#0x4BB8,lsl #0x10 (gcstress)
00007ffa`4d67ef4c f2cfff40 movk        x0,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67ef50 5280dde1 mov         w1,#0x6EF (gcstress)
00007ffa`4d67ef54 97957e43 bl          00007FFA4BCE2C74 (gcstress)
00007ffa`4d67ef58 d284d200 mov         x0,#0x2690 (gcstress)
00007ffa`4d67ef5c f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67ef60 f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67ef64 c8dffc00 ldar        x0,[x0] (gcstress)
00000610 +X0
00007ffa`4d67ef68 f9400ba1 ldr         x1,[fp,#0x10] (gcstress)
00000614 +X1
00007ffa`4d67ef6c aa1703e2 mov         x2,x23 (gcstress)
00000618 +X2
00007ffa`4d67ef70 f9400003 ldr         x3,[x0] (gcstress)
00007ffa`4d67ef74 f9402463 ldr         x3,[x3,#0x48] (gcstress)
00007ffa`4d67ef78 f9401063 ldr         x3,[x3,#0x20] (gcstress)
00000624 -Fp+10
00007ffa`4d67ef7c d63f0060 blr         x3 (gcstress)
00000628 -X23 -X2 -X1 -X0
00007ffa`4d67ef80 2a1903e0 mov         w0,w25 (gcstress)
00007ffa`4d67ef84 9b007f80 mul         x0,x28,x0 (gcstress)
00007ffa`4d67ef88 d360fc00 lsr         x0,x0,#0x20 (gcstress)
00007ffa`4d67ef8c 91000400 add         x0,x0,#1 (gcstress)
00007ffa`4d67ef90 2a1b03e1 mov         w1,w27 (gcstress)
00007ffa`4d67ef94 9b017c00 mul         x0,x0,x1 (gcstress)
00007ffa`4d67ef98 d360fc00 lsr         x0,x0,#0x20 (gcstress)
00007ffa`4d67ef9c 2a0003f7 mov         w23,w0 (gcstress)
00007ffa`4d67efa0 7100037f cmp         w27,#0 (gcstress)
00007ffa`4d67efa4 54000800 beq         00007FFA4D7834B8 (gcstress)
00007ffa`4d67efa8 1adb0b20 udiv        w0,w25,w27 (gcstress)
00007ffa`4d67efac 1b1b7c00 mul         w0,w0,w27 (gcstress)
00007ffa`4d67efb0 4b000320 sub         w0,w25,w0 (gcstress)
00007ffa`4d67efb4 6b17001f cmp         w0,w23 (gcstress)
00007ffa`4d67efb8 9a9f17e0 cseteq      x0 (gcstress)
00007ffa`4d67efbc d2860c01 mov         x1,#0x3060 (gcstress)
00007ffa`4d67efc0 f2abd401 movk        x1,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67efc4 f2c037c1 movk        x1,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67efc8 f940003b ldr         x27,[x1] (gcstress)
00000674 +X27
00007ffa`4d67efcc aa1b03fc mov         x28,x27 (gcstress)
00000678 +X28
00007ffa`4d67efd0 35000200 cbnz        w0,00007FFA4D783424 (gcstress)
00007ffa`4d67efd4 d2800500 mov         x0,#0x28 (gcstress)
00007ffa`4d67efd8 f2a97700 movk        x0,#0x4BB8,lsl #0x10 (gcstress)
00007ffa`4d67efdc f2cfff40 movk        x0,#0x7FFA,lsl #0x20 (gcstress)
00007ffa`4d67efe0 5280dde1 mov         w1,#0x6EF (gcstress)
00007ffa`4d67efe4 97957e1f bl          00007FFA4BCE2C74 (gcstress)
00007ffa`4d67efe8 d284d200 mov         x0,#0x2690 (gcstress)
00007ffa`4d67efec f2abd400 movk        x0,#0x5EA0,lsl #0x10 (gcstress)
00007ffa`4d67eff0 f2c037c0 movk        x0,#0x1BE,lsl #0x20 (gcstress)
00007ffa`4d67eff4 c8dffc00 ldar        x0,[x0] (gcstress)
000006a0 +X0
00007ffa`4d67eff8 aa1c03e1 mov         x1,x28 (gcstress)
000006a4 +X1
00007ffa`4d67effc aa1b03e2 mov         x2,x27 (gcstress)
000006a8 +X2
00007ffa`4d67f000 f9400003 ldr         x3,[x0] (gcstress)
00007ffa`4d67f004 f9402463 ldr         x3,[x3,#0x48] (gcstress)
00007ffa`4d67f008 f9401063 ldr         x3,[x3,#0x20] (gcstress)
00007ffa`4d67f00c d63f0060 blr         x3 (gcstress)
000006b8 -X28 -X27 -X2 -X1 -X0
00007ffa`4d67f010 6b1602ff cmp         w23,w22 (gcstress)
00007ffa`4d67f014 540004e2 bhs         00007FFA4D7834C4 (gcstress)
00007ffa`4d67f018 93407ee0 sxtw        x0,w23 (gcstress)
00007ffa`4d67f01c d37ef400 lsl         x0,x0,#2 (gcstress)
00007ffa`4d67f020 91004000 add         x0,x0,#0x10 (gcstress)
00007ffa`4d67f024 8b00035a add         x26,x26,x0 (gcstress)
000006d0 -X26 +X26(interior)
00007ffa`4d67f028 11000700 add         w0,w24,#1
00007ffa`4d67f02c b9003260 str         w0,[x19,#0x30]
00007ffa`4d67f030 f9400a76 ldr         x22,[x19,#0x10]
000006dc +X22
00007ffa`4d67f034 b9400ac0 ldr         w0,[x22,#8]
00007ffa`4d67f038 6b00031f cmp         w24,w0
00007ffa`4d67f03c 540003a2 bhs         00007FFA4D67F0B0
00007ffa`4d67f040 93407f00 sxtw        x0,w24
00007ffa`4d67f044 d2800061 mov         x1,#3
00007ffa`4d67f048 9b017c00 mul         x0,x0,x1
00007ffa`4d67f04c d37ef400 lsl         x0,x0,#2
00007ffa`4d67f050 91004000 add         x0,x0,#0x10
00007ffa`4d67f054 8b0002c0 add         x0,x22,x0
00000700 +X0(interior)
>>> 00007ffa`4d67f058 b9000019 str         w25,[x0]
00007ffa`4d67f05c b9400341 ldr         w1,[x26] (gcstress)
00007ffa`4d67f060 51000421 sub         w1,w1,#1 (gcstress)
00007ffa`4d67f064 b9000401 str         w1,[x0,#4] (gcstress)
00007ffa`4d67f068 b9000814 str         w20,[x0,#8] (gcstress)
00007ffa`4d67f06c 11000700 add         w0,w24,#1 (gcstress)
00000718 -X0(interior)
00007ffa`4d67f070 b9000340 str         w0,[x26] (gcstress)
00007ffa`4d67f074 b9403e60 ldr         w0,[x19,#0x3C] (gcstress)
00007ffa`4d67f078 11000400 add         w0,w0,#1 (gcstress)
00007ffa`4d67f07c b9003e60 str         w0,[x19,#0x3C] (gcstress)
00007ffa`4d67f080 b90002b8 str         w24,[x21] (gcstress)
00007ffa`4d67f084 52800020 mov         w0,#1 (gcstress)
00000730 not interruptible
00000730 -X22 -X19 -X26(interior) -X21(interior)
00007ffa`4d67f088 a94a73fb ldp         x27,x28,[sp,#0xA0]
00007ffa`4d67f08c a9496bf9 ldp         x25,x26,[sp,#0x90]
00007ffa`4d67f090 a94863f7 ldp         x23,x24,[sp,#0x80]
00007ffa`4d67f094 a9475bf5 ldp         x21,x22,[sp,#0x70]
00007ffa`4d67f098 a94653f3 ldp         x19,x20,[sp,#0x60]
00007ffa`4d67f09c a8cb7bfd ldp         fp,lr,[sp],#0xB0
00007ffa`4d67f0a0 d65f03c0 ret
0000074c interruptible
00007ffa`4d67f0a4 97957df7 bl          00007FFA4BCE2C94 (gcstress)
00007ffa`4d67f0a8 9796bec8 bl          00007FFA4BD32FDC (gcstress)
00007ffa`4d67f0ac d43e0000 brk         #0xF000 (gcstress)
00007ffa`4d67f0b0 97957de8 bl          00007FFA4BCE2C64 (gcstress)
00007ffa`4d67f0b4 d43e0000 brk         #0xF000 (gcstress)
00000760 not interruptible
```

category:correctness
theme:testing
skill-level:expert
cost:medium

### PR DESCRIPTION
**Pull request by erozenfeld**
Improve validation of tail calls that are not tail-prefixed in the IL
but are marked as such because of TailCallStress. We now do the same
correctness validation in morph for such tail calls as we do for
implicit tail calls. That blocks tail calls when we have address-taken
locals, struct promoted params, and pinned vars.

Fixes #39398.
Fixes #39309.
Fixes #38892.
Fixes #38889.
Fixes #38887.
Fixes #37117.
Fixes #8017.

### CODE REVIEW

**Comment by erozenfeld** [comment]
jitstress run: https://dev.azure.com/dnceng/public/_build/results?buildId=766638&view=results
libraries-jitstress run: https://dev.azure.com/dnceng/public/_build/results?buildId=766642&view=results

**Comment by erozenfeld** [comment]
Pushed a fix and re-started stress jobs.
jitstress: https://dev.azure.com/dnceng/public/_build/results?buildId=768042&view=results
libraries-jitstress: https://dev.azure.com/dnceng/public/_build/results?buildId=768054&view=results

**Comment by erozenfeld** [comment]
@AndyAyersMS These changes include switching to always dispatching tail calls via helpers with tailcallstress. Because of that I'm hitting #35687 : JIT\opt\OSR\tailrecursetry\tailrecursetry.cmd fails. #35687 was pushed to future. What do you recommend I should do with this failure? One option is to disable this test under stress.

**Comment by AndyAyersMS** [comment]
Yes, you should disable under stress.

**Comment by erozenfeld** [comment]
Disabled tailrecursetry under stress and rebased. 
Started another libraries-jitstress run: https://dev.azure.com/dnceng/public/_build/results?buildId=769705&view=results

**Comment by erozenfeld** [comment]
I think this is ready for review.

@AndyAyersMS @dotnet/jit-contrib PTAL

**Review by AndyAyersMS — APPROVED** [review]
Thanks, this seems like a much better approach.

There is likely some code in the importer we can clean up as a result (see `passedStressModeValidation`), but no need to do this now.

File: src/coreclr/src/jit/morph.cpp [hunk 1]
```diff
@@ -8810,23 +8816,14 @@ GenTree* Compiler::fgMorphCall(GenTreeCall* call)
...
-                GenTree*  dst        = gtNewLclvNode(tmpNum, structType);
-                assg                 = gtNewAssignNode(dst, call);
-            }
-            else
-            {
-                assg = gtNewTempAssign(tmpNum, call);
-            }
-
-            assg = fgMorphTree(assg);
+            CORINFO_CLASS_HANDLE structHandle = call->gtRetClsHnd;
```
Comment (echesakovMSFT) [inline src/coreclr/src/jit/morph.cpp:8819]: @erozenfeld Can you please expain what this part does?

Comment (sandreenko) [reply src/coreclr/src/jit/morph.cpp:8819]: It was marking `long` on x86 as `lvIsMultiRegRet ` that was not expected by `decomposeLong` (firing an assert).
Right now decomposeLong has its own mechanism to deal with such lclVars.

A long term solution could be to mark long lclVar as `lvIsMultiRegRet` on x86 because and delete the logic from decomposeLong but for now it is not necessary.

**Comment by echesakovMSFT** [comment]
@erozenfeld FYI, related issue https://github.com/dotnet/runtime/issues/8017

File: src/coreclr/src/jit/importer.cpp [hunk 2]
```diff
@@ -7526,11 +7526,13 @@ enum
...
-    PREFIX_UNALIGNED   = 0x00001000,
-    PREFIX_CONSTRAINED = 0x00010000,
-    PREFIX_READONLY    = 0x00100000
+    PREFIX_TAILCALL_STRESS =
+        0x00000100, // call doesn't "tail" IL prefix but is treated as explicit because of tail call stress
+    PREFIX_TAILCALL    = (PREFIX_TAILCALL_EXPLICIT | PREFIX_TAILCALL_IMPLICIT | PREFIX_TAILCALL_STRESS),
+    PREFIX_VOLATILE    = 0x00001000,
+    PREFIX_UNALIGNED   = 0x00010000,
+    PREFIX_CONSTRAINED = 0x00100000,
+    PREFIX_READONLY    = 0x01000000
```
Comment (briansull) [inline src/coreclr/src/jit/importer.cpp:7535]: Why do these flags only use every forth bit?
i.e. 0x1000, 0x2000, 0x4000, 0x8000

**Review by briansull — APPROVED** [review]

File: src/coreclr/src/jit/importer.cpp (hunk 2 above)
Comment (erozenfeld) [reply src/coreclr/src/jit/importer.cpp:7535]: I don't see any reason. I was just following the existing pattern.

**Comment by erozenfeld** [comment]
> @erozenfeld FYI, related issue #8017

@echesakovMSFT Thank you for pointing that out. I pushed a change to enable `GitHub_11408` that is mentioned in #8017.

**Comment by erozenfeld** [comment]
This failure in libraries-jitstress : 
https://helix.dot.net/api/2019-06-17/jobs/ac0b6120-1e47-4e4c-8cab-0080a2f765f7/workitems/System.Threading.Thread.Tests/files/console.1b1c3541.log

```
C:\h\w\AE050963\w\AB2209B8\e>"C:\h\w\AE050963\p\dotnet.exe" exec --runtimeconfig System.Threading.Thread.Tests.runtimeconfig.json --depsfile System.Threading.Thread.Tests.deps.json xunit.console.dll System.Threading.Thread.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Threading.Thread.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Thread.Tests (found 45 of 49 test cases)
  Starting:    System.Threading.Thread.Tests (parallel test collections = on, max threads = 2)
    System.Threading.Threads.Tests.ThreadTests.ApartmentState_NoAttributePresent_DefaultState_Nano [SKIP]
      Condition(s) not met: "IsWindowsNanoServerAndRemoteExecutorSupported"
    System.Threading.Threads.Tests.ThreadTests.ApartmentStateTest_ChangeBeforeThreadStarted_Windows_Nano_Server [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
Stack overflow.
   at System.Threading.Threads.Tests.ThreadTests+<>c__DisplayClass2_0.<ConstructorTest>b__4()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
----- end Thu 08/13/2020 21:56:29.82 ----- exit code -1073741571 ----------------------------------------------------------
```

seems to be unrelated. I was able to repro it locally without my changes and without tailcallstress set. It succeeded once but failed with the same "Stack overflow" on subsequent runs.

The stack trace in the debugger is

```
(5f54.32e0): CLR exception - code e0434352 (first chance)
(5f54.14cc): Stack overflow - code c00000fd (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
coreclr!__chkstk+0x38:
00007ffa`c72ee8d8 41c60300        mov     byte ptr [r11],0 ds:00000039`f2bc6000=00
0:023> !DumpStack
OS Thread Id: 0x14cc (23)
Current frame: coreclr!__chkstk + 0x38 [d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\misc\amd64\chkstk.asm:109]
Child-SP         RetAddr          Caller, Callee
00000039F2BCDDD0 00007ffac6fa0c23 coreclr!ETW::MethodLog::SendMethodDetailsEvent + 0x1b [F:\runtime1\src\coreclr\src\vm\eventtrace.cpp:6341], calling coreclr!__chkstk [d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\misc\amd64\chkstk.asm:67]
00000039F2BCDDE0 00007ffac6fa2059 coreclr!ETW::MethodLog::SendMethodJitStartEvent + 0x109 [F:\runtime1\src\coreclr\src\vm\eventtrace.cpp:6437], calling coreclr!ETW::MethodLog::SendMethodDetailsEvent [F:\runtime1\src\coreclr\src\vm\eventtrace.cpp:6341]
00000039F2BCDE30 00007ffac72fb0c8 coreclr!try_get_function + 0x38 [d:\A01\_work\6\s\src\vctools\crt\vcruntime\src\internal\winapi_downlevel.cpp:198], calling coreclr!invalid_function_sentinel [d:\A01\_work\6\s\src\vctools\crt\vcruntime\src\internal\winapi_downlevel.cpp:79]
00000039F2BCDF10 00007ffac6d864ee coreclr!EEContract::DoChecks + 0xc6 [F:\runtime1\src\coreclr\src\vm\eecontract.cpp:42], calling coreclr!BaseContract::DoChecks [F:\runtime1\src\coreclr\src\inc\contract.inl:25]
00000039F2BCDFB0 00007ffac6f9b1c2 coreclr!ETW::MethodLog::MethodJitting + 0x2ba [F:\runtime1\src\coreclr\src\vm\eventtrace.cpp:5439], calling coreclr!ETW::MethodLog::SendMethodJitStartEvent [F:\runtime1\src\coreclr\src\vm\eventtrace.cpp:6413]
00000039F2BCE160 00007ffac6c8936d coreclr!MethodDesc::JitCompileCodeLockedEventWrapper + 0x2f9 [F:\runtime1\src\coreclr\src\vm\prestub.cpp:876], calling coreclr!ETW::MethodLog::MethodJitting [F:\runtime1\src\coreclr\src\vm\eventtrace.cpp:5425]
00000039F2BCE1D0 00007ffac6ccf03c coreclr!DeadlockAwareLock::EndEnterLock + 0x214 [F:\runtime1\src\coreclr\src\vm\threads.cpp:8263], calling coreclr!DebugOnlyCodeHolder::Leave [F:\runtime1\src\coreclr\src\inc\contract.h:794]
00000039F2BCE1F0 00007ffac6d864ee coreclr!EEContract::DoChecks + 0xc6 [F:\runtime1\src\coreclr\src\vm\eecontract.cpp:42], calling coreclr!BaseContract::DoChecks [F:\runtime1\src\coreclr\src\inc\contract.inl:25]
00000039F2BCE290 00007ffac6c8778c coreclr!MethodDesc::GetMulticoreJitCode + 0xb0 [F:\runtime1\src\coreclr\src\vm\prestub.cpp:603], calling coreclr!EEContract::DoChecks [F:\runtime1\src\coreclr\src\vm\eecontract.cpp:26]
00000039F2BCE350 00007ffac6c88a08 coreclr!MethodDesc::JitCompileCode + 0x4f4 [F:\runtime1\src\coreclr\src\vm\prestub.cpp:795], calling coreclr!MethodDesc::JitCompileCodeLockedEventWrapper [F:\runtime1\src\coreclr\src\vm\prestub.cpp:802]
00000039F2BCE4B0 00007ffac6c8ab29 coreclr!MethodDesc::PrepareILBasedCode + 0x24d [F:\runtime1\src\coreclr\src\vm\prestub.cpp:404], calling coreclr!MethodDesc::JitCompileCode [F:\runtime1\src\coreclr\src\vm\prestub.cpp:693]
00000039F2BCE500 00007ffac6d864ee coreclr!EEContract::DoChecks + 0xc6 [F:\runtime1\src\coreclr\src\vm\eecontract.cpp:42], calling coreclr!BaseContract::DoChecks [F:\runtime1\src\coreclr\src\inc\contract.inl:25]
00000039F2BCE5A0 00007ffac6c8a88d coreclr!MethodDesc::PrepareCode + 0xe9 [F:\runtime1\src\coreclr\src\vm\prestub.cpp:332], calling coreclr!MethodDesc::PrepareILBasedCode [F:\runtime1\src\coreclr\src\vm\prestub.cpp:356]
00000039F2BCE660 00007ffac6b10865 coreclr!CodeVersionManager::PublishVersionableCodeIfNecessary + 0x359 [F:\runtime1\src\coreclr\src\vm\codeversion.cpp:1701], calling coreclr!MethodDesc::PrepareCode [F:\runtime1\src\coreclr\src\vm\prestub.cpp:326]
00000039F2BCE690 00007ffac6a303ed coreclr!CAutoTryCleanup<CLRException::HandlerState>::~CAutoTryCleanup<CLRException::HandlerState> + 0x11 [F:\runtime1\src\coreclr\src\inc\ex.h:608], calling coreclr!CLRException::HandlerState::CleanupTry [F:\runtime1\src\coreclr\src\vm\clrex.cpp:864]
00000039F2BCE6F0 00007ffac6c691cb coreclr!Object::ValidateInner + 0x55b [F:\runtime1\src\coreclr\src\vm\object.cpp:616], calling coreclr!CAutoTryCleanup<CLRException::HandlerState>::~CAutoTryCleanup<CLRException::HandlerState> [F:\runtime1\src\coreclr\src\inc\ex.h:599]
00000039F2BCE800 00007ffac6c29719 coreclr!MethodDesc::ContainsGenericVariables + 0x1c9 [F:\runtime1\src\coreclr\src\vm\method.cpp:900], calling coreclr!MethodDesc::GetNumGenericMethodArgs [F:\runtime1\src\coreclr\src\vm\method.cpp:731]
00000039F2BCE930 00007ffac6c84906 coreclr!MethodDesc::DoPrestub + 0x932 [F:\runtime1\src\coreclr\src\vm\prestub.cpp:2125], calling coreclr!CodeVersionManager::PublishVersionableCodeIfNecessary [F:\runtime1\src\coreclr\src\vm\codeversion.cpp:1641]
00000039F2BCE9F0 00007ffac6aaaac8 coreclr!Module::CheckActivated + 0x1d0 [F:\runtime1\src\coreclr\src\vm\ceeload.cpp:13332], calling coreclr!DomainFile::CheckActivated [F:\runtime1\src\coreclr\src\vm\domainfile.cpp:302]
00000039F2BCEA20 00007ffac6cd8585 coreclr!Thread::SetFrame + 0x3e9 [F:\runtime1\src\coreclr\src\vm\threads.cpp:266], calling ntdll!LdrpDispatchUserCallTarget
00000039F2BCEB30 00007ffac6a3d22e coreclr!AppDomain::CheckCanExecuteManagedCode + 0x1aa [F:\runtime1\src\coreclr\src\vm\appdomain.cpp:2866], calling coreclr!Module::CheckActivated [F:\runtime1\src\coreclr\src\vm\ceeload.cpp:13319]
00000039F2BCEB90 00007ffac6a43d33 coreclr!Thread::EnablePreemptiveGC + 0xdb [F:\runtime1\src\coreclr\src\vm\threads.h:2013], calling coreclr!Thread::TriggersGC [F:\runtime1\src\coreclr\src\vm\threads.h:4079]
00000039F2BCEBC0 00007ffac6a8bc33 coreclr!GCHolderBase::EnterInternalPreemp<1> + 0x1cf [F:\runtime1\src\coreclr\src\vm\threads.h:5504], calling coreclr!Thread::EnablePreemptiveGC [F:\runtime1\src\coreclr\src\vm\threads.h:1986]
00000039F2BCEC20 00007ffac6a8c248 coreclr!GCPreempThreadExists::GCPreempThreadExists + 0x30 [F:\runtime1\src\coreclr\src\vm\threads.h:5731], calling coreclr!GCHolderBase::EnterInternalPreemp<1> [F:\runtime1\src\coreclr\src\vm\threads.h:5485]
00000039F2BCEC70 00007ffac6c8d6f2 coreclr!PreStubWorker + 0x532 [F:\runtime1\src\coreclr\src\vm\prestub.cpp:1952], calling coreclr!MethodDesc::DoPrestub [F:\runtime1\src\coreclr\src\vm\prestub.cpp:2021]
00000039F2BCEE50 00007ffac6dd67f7 coreclr!ForbidGC::~ForbidGC + 0x5b [F:\runtime1\src\coreclr\src\vm\fcall.cpp:189], calling coreclr!Thread::EndNoTriggerGC [F:\runtime1\src\coreclr\src\vm\threads.h:2063]
00000039F2BCEE80 00007ffac715e5e5 coreclr!ThePreStub + 0x55 [F:\runtime1\src\coreclr\src\vm\amd64\ThePreStubAMD64.asm:21], calling coreclr!PreStubWorker [F:\runtime1\src\coreclr\src\vm\prestub.cpp:1869]
00000039F2BCEF30 00007ffac65a2c4a (MethodDesc 00007ffa68821198 + 0xca System.Threading.ThreadHelper.ThreadStart_Context(System.Object))
00000039F2BCEF80 00007ffa68d95a0c (MethodDesc 00007ffa67fbe3e0 + 0x8c System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object))
00000039F2BCEFF0 00007ffac65a2ddd (MethodDesc 00007ffa68821258 + 0x6d System.Threading.ThreadHelper.ThreadStart()), calling (MethodDesc 00007ffa67fbe3e0 + 0 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object))
00000039F2BCF030 00007ffac715d463 coreclr!CallDescrWorkerInternal + 0x83 [F:\runtime1\src\coreclr\src\vm\amd64\CallDescrWorkerAMD64.asm:100]
00000039F2BCF070 00007ffac6d39a3c coreclr!MethodDescCallSite::CallTargetWorker + 0x884 [F:\runtime1\src\coreclr\src\vm\callhelpers.cpp:552], calling coreclr!CallDescrWorkerWithHandler [F:\runtime1\src\coreclr\src\vm\callhelpers.cpp:54]
00000039F2BCF0E0 00007ffac6d39890 coreclr!MethodDescCallSite::CallTargetWorker + 0x6d8 [F:\runtime1\src\coreclr\src\vm\callhelpers.cpp:386], calling coreclr!__chkstk [d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\misc\amd64\chkstk.asm:67]
00000039F2BCF130 00007ffac6ca4362 coreclr!MetaSig::GetReturnTypeNormalized + 0x32 [F:\runtime1\src\coreclr\src\vm\siginfo.cpp:5194], calling coreclr!SigPointer::PeekElemTypeNormalized [F:\runtime1\src\coreclr\src\vm\siginfo.cpp:2349]
00000039F2BCF270 00007ffac6a468d7 coreclr!ArgIteratorTemplate<ArgIteratorBase>::ForceSigWalk + 0x1b3 [F:\runtime1\src\coreclr\src\vm\callingconvention.h:1733], calling coreclr!MetaSig::Reset [F:\runtime1\src\coreclr\src\vm\siginfo.cpp:880]
00000039F2BCF530 00007ffac6d54ee8 coreclr!ThreadNative::KickOffThread_Worker + 0x788 [F:\runtime1\src\coreclr\src\vm\comsynchronizable.cpp:247], calling coreclr!MethodDescCallSite::CallTargetWorker [F:\runtime1\src\coreclr\src\vm\callhelpers.cpp:264]
00000039F2BCF820 00007ffac6a57caa coreclr!ClrDebugState::LockReleased + 0x8e [F:\runtime1\src\coreclr\src\inc\contract.inl:289], calling coreclr!DbgStateLockData::LockReleased [F:\runtime1\src\coreclr\src\inc\contract.inl:369]
00000039F2BCF860 00007ffac6cd4415 coreclr!ManagedThreadBase_DispatchInner + 0xb9 [F:\runtime1\src\coreclr\src\vm\threads.cpp:7337], calling ntdll!LdrpDispatchUserCallTarget
00000039F2BCF920 00007ffac6cd44d6 coreclr!ManagedThreadBase_DispatchMiddle + 0x76 [F:\runtime1\src\coreclr\src\vm\threads.cpp:7381], calling coreclr!ManagedThreadBase_DispatchInner [F:\runtime1\src\coreclr\src\vm\threads.cpp:7327]
00000039F2BCF9E0 00007ffac6bb2ce1 coreclr!Frame::Push + 0x1a1 [F:\runtime1\src\coreclr\src\vm\frames.cpp:418], calling coreclr!Thread::SetFrame [F:\runtime1\src\coreclr\src\vm\threads.cpp:217]
00000039F2BCFAB0 00007ffac6cd6a3f coreclr!``ManagedThreadBase_DispatchOuter'::`11'::__Body::Run'::`5'::__Body::Run + 0x77 [F:\runtime1\src\coreclr\src\vm\threads.cpp:7540], calling coreclr!ManagedThreadBase_DispatchMiddle [F:\runtime1\src\coreclr\src\vm\threads.cpp:7341]
00000039F2BCFB00 00007ffac6cd6cff coreclr!`ManagedThreadBase_DispatchOuter'::`11'::__Body::Run + 0x7f [F:\runtime1\src\coreclr\src\vm\threads.cpp:7542], calling coreclr!``ManagedThreadBase_DispatchOuter'::`11'::__Body::Run'::`5'::__Body::Run [F:\runtime1\src\coreclr\src\vm\threads.cpp:7538]
00000039F2BCFB70 00007ffac6cd45c3 coreclr!ManagedThreadBase_DispatchOuter + 0xc7 [F:\runtime1\src\coreclr\src\vm\threads.cpp:7564], calling coreclr!`ManagedThreadBase_DispatchOuter'::`11'::__Body::Run [F:\runtime1\src\coreclr\src\vm\threads.cpp:7536]
00000039F2BCFBF0 00007ffac6cd46b2 coreclr!ManagedThreadBase_FullTransition + 0xca [F:\runtime1\src\coreclr\src\vm\threads.cpp:7588], calling coreclr!ManagedThreadBase_DispatchOuter [F:\runtime1\src\coreclr\src\vm\threads.cpp:7493]
00000039F2BCFC40 00007ffac6d864ee coreclr!EEContract::DoChecks + 0xc6 [F:\runtime1\src\coreclr\src\vm\eecontract.cpp:42], calling coreclr!BaseContract::DoChecks [F:\runtime1\src\coreclr\src\inc\contract.inl:25]
00000039F2BCFCE0 00007ffac6d546a4 coreclr!ThreadNative::KickOffThread + 0x1c4 [F:\runtime1\src\coreclr\src\vm\comsynchronizable.cpp:327], calling coreclr!ManagedThreadBase::KickOff [F:\runtime1\src\coreclr\src\vm\threads.cpp:7621]
00000039F2BCFE70 00007ffb39b07bd4 KERNEL32!BaseThreadInitThunk + 0x14, calling ntdll!LdrpDispatchUserCallTarget
00000039F2BCFEA0 00007ffb3b0ace51 ntdll!RtlUserThreadStart + 0x21, calling ntdll!LdrpDispatchUserCallTarget

```

**Comment by AndyAyersMS** [comment]
@erozenfeld anything else you're planning on doing before merging?

**Comment by erozenfeld** [comment]
@AndyAyersMS Yes, there are 3 failures in libraries-jitstress (Linux x64 and Linux arm64) that I need to investigate. I suspect these may be product bugs exposed by my change to always dispatch tail calls via helpers under tailcallstress. If that's the case I'll remove that change from this PR and address those bugs separately.

**Comment by AndyAyersMS** [comment]
Need any help?

**Comment by erozenfeld** [comment]
No, at the moment I'm not blocked on anything.

**Comment by erozenfeld** [comment]
If you want, take a look at the issue I described in https://github.com/dotnet/runtime/pull/40698#issuecomment-673922319 . I was able to repro it on a clean clone without my changes but I only saw it in CI with my changes. It appears to be non-deterministic but fails almost 100% for me.

**Comment by erozenfeld** [comment]
It may be something similar to https://github.com/dotnet/runtime/issues/10015

**Comment by erozenfeld** [comment]
I confirmed that the libraries-jitstress failures were exposed by switching to always dispatching tail calls via helpers under tailcallstress. I removed that change from this PR and will address those failures separately.

Re-started stress jobs.

jitstress: https://dev.azure.com/dnceng/public/_build/results?buildId=771604&view=results
libraries-jitstress: https://dev.azure.com/dnceng/public/_build/results?buildId=771599&view=results

@AndyAyersMS PTAL at the current changes

**Review by AndyAyersMS — COMMENTED** [review]
So, just to sum up, the impact is that under tail call stress, we will now
* validate correctness of "stress" tail calls like we do implicit tail calls
* dispatch stress tail calls as tail calls via a helper (or as fast tail calls)
* dispatch implicit tail calls as fast tail calls (reject if requires a helper)

One would hope the parenthetical sets above are empty, and the behavior change from tail call stress mode is to now allow slow implicit tail calls in addition to the tail calls the jit would normally perform. Is that right?

**Comment by erozenfeld** [comment]
>> validate correctness of "stress" tail calls like we do implicit tail calls

It's almost the case. This change ensures that the validation we do in morph for implicit tail calls also implies to stress calls.
The remaining difference is in the importer: we do `verCheckTailCallConstraint` validation for stress calls but don't do it for implicit calls. It shouldn't matter since the checks in `impImportCall` and in morph should cover `verCheckTailCallConstraint` checks. As you mentioned in https://github.com/dotnet/runtime/issues/12833#issuecomment-500945768 and https://github.com/dotnet/runtime/pull/40698#pullrequestreview-467116124 this is something that needs to be cleaned up.

>> dispatch stress tail calls as tail calls via a helper (or as fast tail calls)

In the current state that is correct. My initial attempt was to always dispatch stress tail calls via a helper. That uncovered some issues in the new tail calls via helpers mechanism that I'm investigating. Once they are fixed we should switch to dispatching all stress tail calls via a helper.

>> dispatch implicit tail calls as fast tail calls (reject if requires a helper)

Correct, that part is not changed.

**Comment by erozenfeld** [comment]
We gain two things from tailcallstress:
1. Slow implicit tail calls. That's especially important for platforms that don't support fast tail calls: x86 and arm32.
2. Inlining wins against implicit tail calls but stress tail calls win against inlining.

**Review by AndyAyersMS — APPROVED** [review]
Thanks again. This is a big improvement in tail call stress reliability.

**Comment by erozenfeld** [comment]
libraries-jitstress failures are #40607 and #37291.

**Comment by erozenfeld** [comment]
jitstress failures are #40751.
