### PR TITLE
Delete dead code from and fix `getSIMDStructFromField`

### LINKED ISSUE #71219: `getSIMDStructFromField` is not resilient against struct reinterpretation
Reproduction:
```cs
static int Problem(Vector4 a)
{
    a += a;
    return Unsafe.As<Vector4, StructWithIndex>(ref a).Value;
}

struct StructWithIndex
{
    public int Index;
    public int Value;
}
```
Compile `Problem` with a checked Jit targeting x64.

Expected result: things work fine.

Actual result:
```
Assert failure(PID 25932 [0x0000654c], Thread: 26732 [0x686c]): Assertion failed 'fieldType == TYP_FLOAT' in 'RyuJitReproduction.Program:Problem(System.Numerics.Vector4):float' during 'Morph - Global' (IL size 23; hash 0xc38e8508; FullOpts)

    File: C:\Users\Accretion\source\dotnet\runtime\src\coreclr\jit\morph.cpp Line: 9862
    Image: C:\Users\Accretion\source\dotnet\runtime\artifacts\bin\coreclr\windows.x64.Checked\CoreRun.exe
```
Cause: `getSIMDStructFromField` doesn't account the possibility of struct reinterpretation.

### PR DESCRIPTION
**Pull request by SingleAccretion**
Fixes #71219.

[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1842164&view=ms.vss-build-web.run-extensions-tab) (modulo small TP wins), as expected.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -9820,95 +9820,50 @@ GenTree* Compiler::fgMorphForRegisterFP(GenTree* tree)
...
         {
-            GenTree* obj = nullptr;
-            if (objRef->gtOper == GT_ADDR)
-            {
-                obj = objRef->AsOp()->gtOp1;
-            }
-            else if (ignoreUsedInSIMDIntrinsic)
-            {
-                obj = objRef;
-            }
```
Comment (tannergooding) [inline src/coreclr/jit/morph.cpp:9848]: We don't need this anymore because now that GT_CALL gets the handle directly from the arg info, we should never encounter a `OBJ(SIMD)` or `OBJ(HWINTRINSIC)`, right?

File: src/coreclr/jit/morph.cpp [hunk 2]
```diff
@@ -9820,95 +9820,50 @@ GenTree* Compiler::fgMorphForRegisterFP(GenTree* tree)
...
             if (isSIMDTypeLocal(obj))
             {
                 LclVarDsc* varDsc = lvaGetDesc(obj->AsLclVarCommon());
                 if (varDsc->lvIsUsedInSIMDIntrinsic() || ignoreUsedInSIMDIntrinsic)
                 {
-                    *simdSizeOut        = varDsc->lvExactSize;
-                    *simdBaseJitTypeOut = getBaseJitTypeOfSIMDLocal(obj);
-                    ret                 = obj;
+                    CorInfoType simdBaseJitType = varDsc->GetSimdBaseJitType();
+                    var_types   simdBaseType    = JITtype2varType(simdBaseJitType);
```
Comment (tannergooding) [inline src/coreclr/jit/morph.cpp:9846]: This one is going to do:
```
BYTE -> BYTE
UBYTE -> UBYTE
SHORT -> SHORT
USHORT -> USHORT
FLOAT -> FLOAT
DOUBLE -> DOUBLE
```

but also:
```
INT, UINT -> INT
LONG, ULONG -> LONG
NATIVEINT, NATIVEUINT -> I_IMPL
```

Is that going to be too conservative for `BYTE/UBYTE` and `SHORT/USHORT`?

Comment (tannergooding) [reply src/coreclr/jit/morph.cpp:9846]: Maybe more concretely, given that this is converted to an "extract", does the type here even matter?

We really just care that the field access is 1/2/4/8 bytes in size and that its at an offset of the same and so we really just care about the type of the field access so that the `Extract` node has a valid `CorInfoType` and `simdSize`

File: src/coreclr/jit/morph.cpp (hunk 1 above)
Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:9848]: This condition specifically used to account for the eager morphing of implicit byrefs, that is, we used to get here with an already morphed implicit byref: `FIELD(LCL_VAR byref)`. After #70243, we no longer do, the tree is always `FIELD(ADDR(LCL_VAR struct))`.

For the below code which looks at `ADDR(HWI/SIMD)`, yep, it's the result of us no longer generating such IR.

File: src/coreclr/jit/morph.cpp (hunk 2 above)
Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:9846]: Correct, this logic quite conservative, the "base type" of the underlying local doesn't actually matter (there is a comment below noting that). The reason it is written this way is because there is currently no scenario where we need something more advanced which would support mismatched base/tree types (we only really need to handle `TYP_FLOAT`).

Basically it is working around the fact that there is no `varType2jitType`-style function to turn the `FIELD`'s type into `CorInfoType`.

**Review by tannergooding — APPROVED** [review]

**Comment by JulieLeeMSFT** [comment]
@AndyAyersMS, please review this community PR.

**Review by AndyAyersMS — APPROVED** [review]
