### PR TITLE
Disable TC for UnmanagedCallersOnly methods.

### LINKED ISSUE #46512: Assert failure(PID 5984 [0x00001760], Thread: 1888 [0x0760]): CONTRACT VIOLATION by CallCountingManager::OnCallCountThresholdReached within calls to KERNELBASE! EnumCalendarInfoExEx
Globalization related tests are periodically failing with output like this
```
Assert failure(PID 5984 [0x00001760], Thread: 1888 [0x0760]): CONTRACT VIOLATION by CallCountingManager::OnCallCountThresholdReached at "F:\workspace\_work\1\s\src\coreclr\vm\callcounting.cpp" @ 725

MODE_COOPERATIVE encountered while thread is in preemptive state.

                        CONTRACT in CallCountingManager::OnCallCountThresholdReached at "F:\workspace\_work\1\s\src\coreclr\vm\callcounting.cpp" @ 725
                        CONTRACT in DispatchCallSimple at "F:\workspace\_work\1\s\src\coreclr\vm\callhelpers.cpp" @ 185
                        CONTRACT in ThreadNative::KickOffThread_Worker at "F:\workspace\_work\1\s\src\coreclr\vm\comsynchronizable.cpp" @ 148
                        CONTRACT in ManagedThreadBase_DispatchInner at "F:\workspace\_work\1\s\src\coreclr\vm\threads.cpp" @ 7293
                        CONTRACT in ManagedThreadBase_FullTransition at "F:\workspace\_work\1\s\src\coreclr\vm\threads.cpp" @ 7542
                        CONTRACT in ThreadNative::KickOffThread at "F:\workspace\_work\1\s\src\coreclr\vm\comsynchronizable.cpp" @ 196

We can't find the violated contract. Look for an old-style non-holder-based contract.


CORECLR! <no symbol> + 0x0 (0x00007ff8`11a93c82)
CORECLR! GetCLRRuntimeHost + 0x259212 (0x00007ff8`11de2f32)
CORECLR! <no symbol> + 0x0 (0x00007ff8`11af7229)
CORECLR! GetCLRRuntimeHost + 0x5CD7D5 (0x00007ff8`121574f5)
KERNELBASE! RegLoadMUIStringA + 0x17B37 (0x00007ff8`3c5b6437)
KERNELBASE! EnumCalendarInfoExEx + 0x5A (0x00007ff8`3c57fcda)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ff8`114ea4dc)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ff8`115e2528)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ff8`115e22ca)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ff8`115e1e85)
    File: F:\workspace\_work\1\s\src\coreclr\vm\callcounting.cpp Line: 725
    Image: C:\h\w\A2F3094A\p\dotnet.exe

----- end Thu 12/31/2020  8:15:58.95 ----- exit code -1073740286 ----------------------------------------------------------
```

It is happening ~2x a day over the last 10 days and only on windows.10.amd64.open.rt `### OS: Distro=WindowsProductType=8 WindowsInstallationType=Server Description=Microsoft Windows 10.0.14393 Version=Microsoft Windows NT 10.0.14393.0 Arch=X64 Rid=win10-x64`

It occurs in these test jobs
```
System.Globalization.Tests
System.Globalization.Nls.Tests
System.Runtime.Tests
```
the stack always contains
```
KERNELBASE! Internal_EnumCalendarInfo + 0x225 (0x00007ff8`b074ff15)
KERNELBASE! EnumCalendarInfoExEx + 0x5A (0x00007ff8`b074fcda)
```
or
```
KERNELBASE! RegLoadMUIStringA + 0x17B37 (0x00007ff8`3c5b6437)
KERNELBASE! EnumCalendarInfoExEx + 0x5A (0x00007ff8`3c57fcda)
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Tiered compilation uses call counting and the call counting mechanism today is incompatible with UnmanagedCallersOnly. Disabled tiered compilation for UnmanagedCallersOnly methods.

Fixes #46512

### CODE REVIEW

File: src/coreclr/vm/method.cpp [hunk 1]
```diff
@@ -4866,7 +4866,11 @@ bool MethodDesc::DetermineAndSetIsEligibleForTieredCompilation()
         !IsJitOptimizationDisabled() &&
 
         // Policy - Tiered compilation is not disabled by the profiler
-        !CORProfilerDisableTieredCompilation())
+        !CORProfilerDisableTieredCompilation() &&
+
+        // Functional requirement - UnmanagedCallersOnly methods exit in Preemptive GC, which is incompatible with
+        // the lifetime management used for tiered compilation call counting today.
+        !HasUnmanagedCallersOnlyAttribute())
```
Comment (jkotas) [inline src/coreclr/vm/method.cpp:4873]: Can we do this lazily - only once the method is about to be JITed?

Comment (jkoritzinsky) [reply src/coreclr/vm/method.cpp:4873]: I'll try to find a place that both makes sure we don't patch the prestub with call counting and set the right optimization tier for the JIT. My guess is we will end up checking in two places (one for each of these cases).

Comment (kouvel) [reply src/coreclr/vm/method.cpp:4873]: The attribute lookup may also be too expensive to do for every method that is called. The check done for precompiled code in `MethodDesc::GetPrecompiledCode` currently uses the caller's GC mode to condition the attribute lookup, that might reduce the cost for jitted cases too, the only caller is `MethodDesc::PrepareILBasedCode` currently, that may be a good place to do the check for both cases.

Comment (jkoritzinsky) [reply src/coreclr/vm/method.cpp:4873]: I was afraid of that. I'll try another approach.

**Comment by jkoritzinsky** [comment]
After trying to repro locally, this is looking very odd. There's already some code in jithelpers.cpp to force jitted UnmanagedCallersOnly methods to switch to optimized code which works locally in what I thought would be a minimal repro, but for some reason the failing case (the dump from the tests) has the method QuickJitted. I'll make this a draft until I can actually get a local repro.

**Comment by jkoritzinsky** [comment]
I've found the issue. It's a bad interaction between JitStress and the way UnmanagedCallersOnly opts out of TieredCompilation. Working on a fix now.

File: src/coreclr/vm/jitinterface.cpp [hunk 2]
```diff
@@ -6817,7 +6817,13 @@ void CEEInfo::setMethodAttribs (
             if (attribs & CORINFO_FLG_SWITCHED_TO_MIN_OPT)
             {
                 _ASSERTE(!ftn->IsJitOptimizationDisabled());
-                config->SetJitSwitchedToMinOpt();
+                // UnmanagedCallersOnly methods that are switched to optimized must be optimized.
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/jitinterface.cpp:6820]: I don't get this code path. From this point it appears the method in question has been marked as `CORINFO_FLG_SWITCHED_TO_MIN_OPT`, but the check in here validates it wasn't "switched to optimized". This begs the question why would the config be "switched to optimized" with the "switched to min opt" flag being passed in? This seems like a fundamental logical flaw. The next question would be below when the flag `CORINFO_FLG_SWITCHED_TO_OPTIMIZED` is passed in - is it okay for that? Even though this method state should be return `false` with `IsEligibleForTieredCompilation`? It may not be but the point here is that methods marked with `UnmanagedCallersOnlyAttribute` aren't supported. Which means now we have a case where `IsEligibleForTieredCompilation` isn't always correct.

Comment (kouvel) [reply src/coreclr/vm/jitinterface.cpp:6820]: This path would be taken when the JIT decides to optimize or not, differently from the JIT flags that were requested. It may switch to minopt (for a JIT invocation requesting optimizations) if the method is too complex to optimize, or it may switch to optimized (for a JIT invocation requesting tier 0 JIT) if the method contains a loop since we currently don't tier methods that contain a loop when the method does not have prejitted code. The change here in the `PrepareCodeConfig` is only meant to convey the change up to the invoker of the JIT so that the method would be treated appropriately, for instance to disable tiering for the method if a tier 0 JIT invocation generated optimized code. In that case the method is technically eligible for tiering according to `IsEligibleForTieredCompilation` (which is determined much earlier with less info) but tiering is disabled shortly after jitting it for the first time by disabling call counting. For a method that contains a loop, if it has prejitted code, the method would be tiered, we would just not JIT it without optimizations when it doesn't have prejitted code.

> There's already some code in jithelpers.cpp to force jitted UnmanagedCallersOnly methods to switch to optimized code which works locally in what I thought would be a minimal repro

Come to think of it, that may be what is happening here. Does the method contain a loop?

Since we want to disable tiering for `UnmanagedCallersOnly` methods whether prejitted or not, `MethodDesc::PrepareILBasedCode` may be a good place to disable call counting, using a check similar to that currently done in `MethodDesc::GetPrecompiledCode`. If the method has prejitted code, the prejitted code would get used and call counting would be disabled (same as currently). If the method has to be jitted, the JIT would be invoked with flags requesting optimizations because call counting has already been disabled.

Comment (jkoritzinsky) [reply src/coreclr/vm/jitinterface.cpp:6820]: No. We explicitly force any method marked with the `CORJIT_REVERSE_PINVOKE` jit flag (which is only applied to UnmanagedCallersOnly-style methods and IL stubs to switch to optimized code in an attempt to opt-out of TC.

**Comment by jkoritzinsky** [comment]
I tried out another new approach. This time we'll override the "should we do call counting" after we finish getting the R2R or jitted code if the method is UnmanagedCallersOnly. I left in the previous checks in since we still want to force the optimization level for the jitted code.

File: src/coreclr/vm/prestub.cpp [hunk 3]
```diff
@@ -412,6 +412,17 @@ PCODE MethodDesc::PrepareILBasedCode(PrepareCodeConfig* pConfig)
         DACNotifyCompilationFinished(this, pCode);
     }
 
+#if defined(FEATURE_TIERED_COMPILATION) && !defined(TARGET_X86)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/prestub.cpp:415]: Can you elaborate on the x86 aspect of this?

File: src/coreclr/vm/jitinterface.cpp (hunk 2 above)
Comment (kouvel) [reply src/coreclr/vm/jitinterface.cpp]: Oh I see, I guess it was setting the tier1 flag but the JIT then decides to switch to minopt for some reason, in which case tiering would is not disabled

File: src/coreclr/vm/prestub.cpp (hunk 3 above)
Comment (jkoritzinsky) [reply src/coreclr/vm/prestub.cpp:415]: My PR that moves x86 to the full UnmanagedCallersOnly plan still hasn't been merged yet. That's basically it.

File: src/coreclr/vm/method.hpp [hunk 4]
```diff
@@ -2137,12 +2137,10 @@ class PrepareCodeConfig
...
     }
 
-    void SetShouldCountCalls()
+    void SetShouldCountCalls(bool value = true)
     {
         WRAPPER_NO_CONTRACT;
-        _ASSERTE(!m_shouldCountCalls);
-
-        m_shouldCountCalls = true;
+        m_shouldCountCalls = value;
```
Comment (kouvel) [inline src/coreclr/vm/method.hpp:2143]: This change shouldn't be necessary after my other suggestion

**Review by kouvel — COMMENTED** [review]
I think this can be refactored a bit to simplify/improve the logic in various places and to reflect the state of the method more correctly:
- Move all of the following to the beginning of `MethodDesc::PrepareILBasedCode`
https://github.com/dotnet/runtime/blob/0622fa017488afe5c8262a012caad1404afbd75e/src/coreclr/vm/prestub.cpp#L444-L466
- Pass `shouldTier` into `MethodDesc::GetPrecompiledCode`
- Delete all of
https://github.com/dotnet/runtime/blob/0622fa017488afe5c8262a012caad1404afbd75e/src/coreclr/vm/jitinterface.cpp#L13027-L13042

With call counting properly disabled, the JIT flags sent would request optimization, and the tier that shows up in profiles would be correct.

File: src/coreclr/vm/method.hpp [hunk 5]
```diff
@@ -2023,16 +2023,23 @@ class MethodDesc
 
 private:
     PCODE PrepareILBasedCode(PrepareCodeConfig* pConfig);
+#ifdef FEATURE_TIERED_COMPILATION
+    PCODE GetPrecompiledCode(PrepareCodeConfig* pConfig, bool shouldCountCalls);
+    PCODE JitCompileCode(PrepareCodeConfig* pConfig, bool shouldCountCalls);
+    PCODE JitCompileCodeLockedEventWrapper(PrepareCodeConfig* pConfig, JitListLockEntry* pEntry, bool shouldCountCalls);
+    PCODE JitCompileCodeLocked(PrepareCodeConfig* pConfig, JitListLockEntry* pLockEntry, bool shouldCountCalls, ULONG* pSizeOfCode, CORJIT_FLAGS* pFlags);
```
Comment (kouvel) [inline src/coreclr/vm/method.hpp:2030]: The `JitCompileCode*` methods don't need `shouldCountCalls` passed in, they would only call `PrepareCodeConfig::ShouldCountCalls()` if doing a tier 0 JIT, which it won't be doing for `UnmanagedCallersOnly` because tiering / call counting has already been disabled.

File: src/coreclr/vm/prestub.cpp [hunk 6]
```diff
@@ -361,6 +361,19 @@ PCODE MethodDesc::PrepareILBasedCode(PrepareCodeConfig* pConfig)
...
 
+#if defined(FEATURE_TIERED_COMPILATION)
+    bool shouldCountCalls = pConfig->GetMethodDesc()->IsEligibleForTieredCompilation();
+#if !defined(TARGET_X86)
+    if (shouldCountCalls
+        && (pConfig->GetCallerGCMode() == CallerGCMode::Preemptive
+            || (pConfig->GetCallerGCMode() == CallerGCMode::Unknown
+                && HasUnmanagedCallersOnlyAttribute())))
+    {
+        shouldCountCalls = false;
```
Comment (kouvel) [inline src/coreclr/vm/prestub.cpp:372]: It would be a bit better to disable call counting and update the optimization tier here like in `GetPrecompiledCode` before, instead of relying on the `JitSwitchedToOptimized` system that was meant to be used only for changes made by the JIT.
```suggestion
        NativeCodeVersion codeVersion = pConfig->GetCodeVersion();	
        if (codeVersion.IsDefaultVersion())	
        {	
            pConfig->GetMethodDesc()->GetLoaderAllocator()->GetCallCountingManager()->DisableCallCounting(codeVersion);	
        }	
        codeVersion.SetOptimizationTier(NativeCodeVersion::OptimizationTierOptimized);
        shouldCountCalls = false;
```

File: src/coreclr/vm/prestub.cpp [hunk 7]
```diff
@@ -1007,6 +1034,23 @@ PCODE MethodDesc::JitCompileCodeLocked(PrepareCodeConfig* pConfig, JitListLockEn
...
+        pFlags->Clear(CORJIT_FLAGS::CORJIT_FLAG_TIER0);
+        pFlags->Clear(CORJIT_FLAGS::CORJIT_FLAG_TIER1);
+
+        if (pConfig->GetMethodDesc()->IsEligibleForTieredCompilation())
+        {
+            pConfig->SetJitSwitchedToOptimized();
+        }
+    }
+#endif
+
```
Comment (kouvel) [inline src/coreclr/vm/prestub.cpp:1053]: This can be deleted, shouldn't be necessary after the other suggestion

File: src/coreclr/vm/method.hpp (hunk 5 above)
Comment (kouvel) [reply src/coreclr/vm/method.hpp:2030]: After the other suggestion below

**Comment by kouvel** [comment]
Ah I think there is a bug currently in the optimization flags when call counting is disabled, so it wouldn't work the way I expected it to with the above changes I suggested. Please ignore my suggestions above, I'll fix the bug separately and update along with that.

**Review by kouvel — APPROVED** [review]

**Comment by kouvel** [comment]
Also if you have a small test case can you please share it with me so that I can make sure it is working as intended? Or is it checked in somewhere?

**Comment by jkoritzinsky** [comment]
My test case is kind of hacky, but here it is:

```csharp
using System;
using System.Runtime.InteropServices;

var calendarDataType = Type.GetType("System.Globalization.CalendarData");
var method = calendarDataType.GetMethod("EnumCalendarInfoCallback", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static, null, System.Reflection.CallingConventions.Standard, new[] { typeof(char*), typeof(uint), typeof(IntPtr), typeof(void*)}, null);
var fnptr = method.MethodHandle.GetFunctionPointer();

unsafe
{
    byte b = ((delegate* unmanaged<char*, uint, IntPtr, void*, byte>)fnptr)(null, 0, IntPtr.Zero, null);
}
```

I validated that when running with no COMPlus flags, the JIT builds the code as untiered (optimized) and `!dumpmd` reports the CodeVersion as optimized. I also validated that when `COMPlus_JitStress=2` (the failing case) the JIT uses MinOpts as expected and the CodeVersion agrees with the JIT.

**Comment by jkoritzinsky** [comment]
The System.Private.Uri.Functional.Tests dump looks like a GC hole which I believe is unrelated to this PR. I'll open a separate issue for it and merge this in.
