### PR TITLE
Do not copy XState other than AVX when redirecting for GC stress

### LINKED ISSUE #65776: CopyContext in Thread::RedirectCurrentThreadAtHandledJITCase sometimes fails
I have noticed that on my machine the `CopyContext` call in the `Thread::RedirectCurrentThreadAtHandledJITCase` sometimes fails with the `ERROR_INSUFFICIENT_BUFFER`. I have debugged it and found the culprit. The issue is that the target context that we've just allocated in `AllocateOSContextHelper` doesn't have enough space in the XState due to the fact that we set too small XState compaction mask in the `InitializeContext2` call. We set just `XSTATE_MASK_LEGACY | XSTATE_MASK_AVX`, but the source context that we get from the vectored exception handler was created with `XSTATE_MASK_LEGACY | XSTATE_MASK_AVX | XSTATE_MASK_AVX512 | XSTATE_MASK_MPX` (in other words, the masks returned by the `GetEnabledXStateFeatures()`. While the `CopyContext` can copy only parts of the legacy context based on the context flags, it obviously cannot copy only part of the xstate from the source context.

I am not sure what makes OS to call the vectored exception handler with this full AVX state only in some cases, because I hit this problem only with one of the coreclr tests and only when tiered compilation is disabled.

It seems that we need to pass the result of the `GetEnabledXStateFeatures()` as `xStateCompactionMask` to the `InitializeContext2`.

### PR DESCRIPTION
**Pull request by VSadov**
GC stress mechanism relies on exceptions thrown from random locations in managed code. 

The context that OS passes for the exception location may contain whatever XState that happens to be dirty. However only AVX matters in managed code. 
Besides, the redirection context that stores the state may not have space to save other XState features.

To avoid dealing with the state that we do not expect, we will indicate via the feature mask that only AVX state is valid in the provided context.

Fixes: https://github.com/dotnet/runtime/issues/65776

### CODE REVIEW

**Comment by VSadov** [comment]
@janvorli - could you check that the fix actually resolves the issue? I could not reproduce it. I think the issue requires your other changes.

**Comment by janvorli** [comment]
It doesn't work, the CopyContext still fails with this change.

**Comment by janvorli** [comment]
It seems that the SetXStateFeatureMask is an "or" operation. I've called GetXStateFeatureMask after the SetXStateFeatureMask you've added and the mask was the same as before the set (0xA3 in my case).

**Comment by VSadov** [comment]
Ah, yes, since it is picking whatever is dirty, it is possible that there is XState, but without AVX. I need to apply the mask unconditionally.

**Comment by janvorli** [comment]
But what would it copy then when the source context doesn't contain AVX? And it would drop the AVX512 state possibly resulting in floating point state corruption, wouldn't it? It still seems to me that allocating the context with everything is a better way.

**Comment by VSadov** [comment]
Since this is happening in managed code only AVX could have live data. If that is not present, we will only copy the legacy part.

The AVX2 vs. AVX512 is confusing. I keep mixing them up. I believe managed code may use AVX2 (i.e. AVX256), but that is included in AVX feature in XState, but not AVX512.

When AVX512 is supported we will have to make the context larger and start saving/restoring AVX512 feature as well.

File: src/coreclr/vm/threadsuspend.cpp [hunk 1]
```diff
@@ -1997,15 +1997,6 @@ CONTEXT* AllocateOSContextHelper(BYTE** contextBuffer)
             pfnInitializeContext2(buffer, context, &pOSContext, &contextSize, xStateCompactionMask):
             InitializeContext(buffer, context, &pOSContext, &contextSize);
 
-        // if AVX is supported set the appropriate features mask in the context
```
Comment (janvorli) [inline src/coreclr/vm/threadsuspend.cpp:2000]: With this removed, the code above that sets the supportAVX based on the FeatureMask can be removed too.

Comment (VSadov) [reply src/coreclr/vm/threadsuspend.cpp:2000]: Right, even before `supportAVX` was redundant, since `SetXStateFeaturesMask` performs the same check - to filter out what is not supported.

**Comment by janvorli** [comment]
I can confirm that the current state of the change works.

File: src/coreclr/vm/threadsuspend.cpp [hunk 2]
```diff
@@ -2912,9 +2901,23 @@ BOOL Thread::RedirectThreadAtHandledJITCase(PFN_REDIRECTTARGET pTgt)
...
+#if defined(TARGET_X86) || defined(TARGET_AMD64)
+    // Scenarios like GC stress may indirectly disable XState features in the pCtx
+    // depending on the state at the time of GC stress interrupt.
+    // 
+    // Make sure that AVX feature mask is set, if supported.
+    // 
+    // This should not normally fail.
+    // The system silently ignores any feature specified in the FeatureMask
+    // which is not enabled on the processor.
+    bRes &= SetXStateFeaturesMask(pCtx, XSTATE_MASK_AVX);
```
Comment (janvorli) [inline src/coreclr/vm/threadsuspend.cpp:2917]: I only have one nit - I would prefer failures / asserts on each of the failure instead of combining the results together.

**Review by janvorli — APPROVED** [review]

File: src/coreclr/vm/threadsuspend.cpp (hunk 2 above)
Comment (VSadov) [reply src/coreclr/vm/threadsuspend.cpp:2917]: `GetXStateFeaturesMask` and `SetXStateFeaturesMask` basically cannot fail. They are very tolerant to the input. 
To get failures you'd need something like pass flags for a wrong architecture (like arm64). As-is that would not compile.

Realistically only `CopyContext` is something that could fail here due to some mistake.
I think in this particular case individual asserts/returns would not add a lot of value.

Comment (janvorli) [reply src/coreclr/vm/threadsuspend.cpp:2917]: I've just found those would fail also when passed context without any XSTATE present. It seems like something that could possibly happen for the usage in `Thread::RedirectCurrentThreadAtHandledJITCase` where we pass it a general context that we get from the vectored exception handler. So it seems that it would be nice to actually make that work in that case.

Comment (VSadov) [reply src/coreclr/vm/threadsuspend.cpp:2917]: Hmm, my read on that was that Set(Get) would be a noop, but I think you are right, if no XState is set it may fail. Arguably a bug in the validation of Set not accepting 0.

Yes, we should make this case work.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

File: src/coreclr/vm/threadsuspend.cpp [hunk 3]
```diff
@@ -3029,8 +3032,35 @@ BOOL Thread::RedirectCurrentThreadAtHandledJITCase(PFN_REDIRECTTARGET pTgt, CONT
...
+    // but only AVX feature may contain live data. (that could change with new features in JIT)
+    // Besides pCtx may not have space to store other features.
+    // So we will mask out everything but AVX.
+    DWORD64 srcFeatures = 0;
+    success = GetXStateFeaturesMask(pCurrentThreadCtx, &srcFeatures);
     _ASSERTE(success);
+    if (!success)
+        return FALSE;
+
+    // Get may return 0 if no XState is set, which Set would not accept.
```
Comment (VSadov) [inline src/coreclr/vm/threadsuspend.cpp:3049]: Get may return 0 if no XState is set, which Set would not accept.

**Comment by VSadov** [comment]
linux DAC build failures happen in other PRs as well.
