### PR TITLE
Fix issue with hoisting and copy prop interaction

### LINKED ISSUE #84619: JIT: Assertion failed '((tree->gtFlags & GTF_VAR_DEF) == 0) && (tree->GetLclNum() == lclNum) && tree->gtVNPair.BothDefined()' during 'VN based copy prop
```csharp
// Generated by Fuzzlyn v1.5 on 2023-04-09 16:37:03
// Run on X64 Windows
// Seed: 6230188300048624105
// Reduced from 155.1 KiB to 0.2 KiB in 00:01:48
// Hits JIT assert in Release:
// Assertion failed '((tree->gtFlags & GTF_VAR_DEF) == 0) && (tree->GetLclNum() == lclNum) && tree->gtVNPair.BothDefined()' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'VN based copy prop' (IL size 25; hash 0xade6b36b; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\copyprop.cpp Line: 161
// 
public class Program
{
    public static sbyte s_27;
    public static void Main()
    {
        long vr1 = 0;
        for (int vr3 = 0; vr3 < -1; vr3++)
        {
            s_27 = (sbyte)(vr1 | vr1);
        }
    }
}
```

Looks introduced/exposed by #83956, cc @BruceForstall

### PR DESCRIPTION
**Pull request by BruceForstall**
After hoisting creates a tree copy, it morphs it. That morph might lose the value numbers on LCL_VAR uses, but leave the SSA numbers. Copy prop was assuming that such a use had a VN. Instead, check this dynamically instead of asserting.

Fixes #84619

### CODE REVIEW

**Comment by BruceForstall** [comment]
[No asm diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255257&view=ms.vss-build-web.run-extensions-tab)

Slight TP cost

**Comment by BruceForstall** [comment]
@AndyAyersMS PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
> After hoisting creates a tree copy, it morphs it. That morph might lose the value numbers on LCL_VAR uses, but leave the SSA numbers. Copy prop was assuming that such a use had a VN. Instead, check this dynamically instead of asserting.
> 
> Fixes #84619

I hate to open a can of worms here, but *why* does hoisting call morph? Seems like maybe it shouldn't.

**Comment by BruceForstall** [comment]
> I hate to open a can of worms here, but _why_ does hoisting call morph?

Disabling morphing only causes one family of diffs.

Another question, though: why does morphing lose VNs on LCL_VARs?

**Comment by SingleAccretion** [comment]
The case from #84619 is `optNarrowTree`'s work, and it cannot (easily) preserve VNs on trees that it transforms (although it has some logic that tries). What we've been doing with such transformation is putting them under `if (fgGlobalMorph)`. This may be expensive CQ-wise in this case.

**Comment by AndyAyersMS** [comment]
> > I hate to open a can of worms here, but _why_ does hoisting call morph?
> 
> Disabling morphing only causes one family of diffs.

I was wondering if you'd actually see improvements, since hoisting relies on CSE and perhaps morphing the hoisted copy would break CSE (either by changing tree shape so it no longer matches the in-loop tree or perhaps by losing the `GTF_MAKE_CSE` flag) and hence messes up hoisting.

Oddly we don't check for `GTF_MAKE_CSE` in CSE proper, we just use it to keep morph and other things from deleting the thing we just hoisted.

> Another question, though: why does morphing lose VNs on LCL_VARs?

Could be there's a missing surgical VN update that could be fixed, you'd have to dig in.

**Comment by AndyAyersMS** [comment]
@BruceForstall you're not waiting on me here, are you?

**Comment by BruceForstall** [comment]
> @BruceForstall you're not waiting on me here, are you?

No. But the questions asked require investigations, which I've prioritized very low compared to other work (even though it would be nice to get Fuzzlyn cleaner, but it has good baselining anyway)

**Comment by BruceForstall** [comment]
@AndyAyersMS I updated this. I found the case that was creating a CAST that wasn't getting fully morphed/optimized, in `fgOptimizeCastOnStore`, and added a call to `fgOptimizeCast`. With this, the hoisted code that gets morphed doesn't actually optimize anything, and so the assert is avoided. (It turns out it doesn't create a CSE in this test case, either, but I didn't look into why.) I propose to leave the dynamic check in `optBlockCopyProp` for safety. Finally, if I remove morphing from hoisting there are no diffs now (at least on win-x64). Perhaps removing that can be done as a follow-up.

I also added a unit test.

There are a few [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274714&view=ms.vss-build-web.run-extensions-tab), with the additional call to `fgOptimizeCast` causing a few more cases of narrowing to kick in.

There is a bit of TP hit.

File: src/coreclr/jit/copyprop.cpp [hunk 1]
```diff
@@ -389,7 +391,8 @@ bool Compiler::optBlockCopyProp(BasicBlock* block, LclNumToLiveDefsMap* curSsaNa
             {
                 optCopyPropPushDef(tree, lclDefNode, curSsaName);
             }
-            else if (tree->OperIs(GT_LCL_VAR, GT_LCL_FLD) && tree->AsLclVarCommon()->HasSsaName())
+            else if (tree->OperIs(GT_LCL_VAR, GT_LCL_FLD) && tree->AsLclVarCommon()->HasSsaName() &&
+                     tree->gtVNPair.BothDefined())
```
Comment (SingleAccretion) [inline src/coreclr/jit/copyprop.cpp:395]: I would recommend removing this check. `optCopyProp` doesn't actually depends on the VNs being present for trees it examines, so this is effectively the same as removing the assert.

Comment (BruceForstall) [reply src/coreclr/jit/copyprop.cpp:395]: `optCopyProp` does `assert(tree->gtVNPair.BothDefined())` which is why I added this.

But it's true that `optCopyProp` does not actually use the `tree->gtVNPair` : it looks up the VN in the `lvPerSsaData` for the SSA def of the local. Presumably this assert is a partial expression of the expectation that if a local has an SSA number, then its SSA def should have the same VN as the SSA use (I believe that should be true?). It would therefore seem odd to ignore the fact that a lclvar use has no VN but its SSA does, and just use the def. That seems to indicate something is odd/wrong, perhaps due to morph, like what happened here.

Of course, I could remove the assert from `optCopyProp`, too.

Comment (SingleAccretion) [reply src/coreclr/jit/copyprop.cpp:395]: > Presumably this assert is a partial expression of the expectation that if a local has an SSA number, then its SSA def should have the same VN as the SSA use (I believe that should be true?).

Here is how this situation came to be: `optCopyProp` used to use the tree VN, but was changed to use the definition VN in #65250, with the main motivation being `LCL_FLD` handling. I left the tree VN assert as it seemed valuable on its own (indeed, as you say, to catch missing VNs - we are generally sorely lacking in validating this aspect of morph).

Comment (BruceForstall) [reply src/coreclr/jit/copyprop.cpp:395]: So it seems like I could either:
1. Remove both the `tree->gtVNPair.BothDefined()` check here and `assert(tree->gtVNPair.BothDefined())` in `optCopyProp` (so `optCopyProp` will no longer check for "missing" VNs), or
2. Leave it as I've written it -- with more testing/checking than maybe should be required, or
3. Something else? (e.g., asserting for and fixing "missing VNs" -- but that seems out of scope for this fix)

Do you have a preference?

Comment (SingleAccretion) [reply src/coreclr/jit/copyprop.cpp:395]: My preference would be to check for missing VNs and fix them (leave the assert without the check, or even migrate it to the general loop in `optBlockCopyProp`), but barring that removing the assert (`1`) seems better.

Comment (AndyAyersMS) [reply src/coreclr/jit/copyprop.cpp:395]: I think the SSA checker should also be able to spot missing VNs, though not perhaps in as timely a manner.

Comment (BruceForstall) [reply src/coreclr/jit/copyprop.cpp:395]: > I think the SSA checker should also be able to spot missing VNs, though not perhaps in as timely a manner.

Well, `fgDebugCheckSsa()` already has this comment: `* Verify VNs on uses match the VN on the def` :-)

**Comment by BruceForstall** [comment]
Ok, I've removed the assert in `optCopyProp`.

**Review by SingleAccretion — APPROVED** [review]

**Comment by BruceForstall** [comment]
ping

**Review by AndyAyersMS — APPROVED** [review]
