### PR TITLE
Fix ldapur instruction

### LINKED ISSUE #91647: Test failure: JIT/Directed/coverage/oldtests/stfldstatic2_r/stfldstatic2_r.dll
pipeline: runtime-coreclr outerloop
coreclr osx arm64 Checked no_tiered_compilation @ OSX.1200.ARM64.Open
Directed_1 Work Item

https://dev.azure.com/dnceng-public/public/_build/results?buildId=392066&view=ms.vss-test-web.build-test-results-tab&runId=8427280&paneView=debug&resultId=120604

(failure started with runtime-coreclr outerloop 20230831.3)

```
12:57:21.890 Running test: JIT/Directed/coverage/oldtests/stfldstatic2_r/stfldstatic2_r.dll
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at stfldstatic2.Main()
   at Program.<<Main>$>g__TestExecutor171|0_172(System.IO.StreamWriter, System.IO.StreamWriter, <>c__DisplayClass0_0 ByRef)
   at Program.<Main>$(System.String[])
[createdump] Invalid process id: task_for_pid(58591) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Target process is alive
[createdump] Failure took 0ms
waitpid() returned successfully (wstatus 0000ff00) WEXITSTATUS ff WTERMSIG 0
App Exit Code: 22
Expected: 100
Actual: 22
END EXECUTION - FAILED
```

Maybe related to https://github.com/dotnet/runtime/pull/89681 @EgorBo ?

### LINKED ISSUE #91648: Test failure: JIT/Directed/PREFIX/volatile/1/Box_Unbox_volatile/Box_Unbox_volatile.dll
pipeline: runtime-coreclr outerloop
coreclr osx arm64 Checked no_tiered_compilation @ OSX.1200.ARM64.Open
Directed_2 Work Item

https://dev.azure.com/dnceng-public/public/_build/results?buildId=392066&view=ms.vss-test-web.build-test-results-tab&runId=8427280&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=120605

```
12:57:36.545 Running test: JIT/Directed/PREFIX/volatile/1/Box_Unbox_volatile/Box_Unbox_volatile.dll
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Box_Unbox.main()
   at Program.<<Main>$>g__TestExecutor31|0_32(System.IO.StreamWriter, System.IO.StreamWriter, <>c__DisplayClass0_0 ByRef)
   at Program.<Main>$(System.String[])
[createdump] Invalid process id: task_for_pid(80065) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Target process is alive
[createdump] Failure took 1ms
waitpid() returned successfully (wstatus 0000ff00) WEXITSTATUS ff WTERMSIG 0
App Exit Code: 22
Expected: 100
Actual: 22
END EXECUTION - FAILED
```

Same failure in `coreclr osx arm64 Checked @ OSX.1200.ARM64.Open.`

Related? https://github.com/dotnet/runtime/issues/91647 @EgorBo

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/91648
Fixes https://github.com/dotnet/runtime/issues/91647

The issue is that LDAPUR doesn't support fp regs, I made a small clean up and now it should ignore those (just like for existing ldar)

PTAL @BruceForstall @TIHan @dotnet/jit-contrib

### CODE REVIEW

File: src/coreclr/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -1767,42 +1767,31 @@ void CodeGen::genCodeForIndir(GenTreeIndir* tree)
...
+        bool canUseLdapur = compiler->compOpportunisticallyDependsOn(InstructionSet_Rcpc2) && !addrIsInReg && tree->Addr()->OperIs(GT_LEA) && !tree->HasIndex() && (tree->Scale() == 1) &&
+            emitter::emitIns_valid_imm_for_unscaled_ldst_offset(tree->Offset());
 
         if ((ins == INS_ldrb) && addrIsInReg)
         {
-            ins = hasRcpc ? INS_ldaprb : INS_ldarb;
+            // RCPC2 is supported -> ldapurb (ldaprb with IMM offset)
+            // RCPC1 is supported -> ldaprb
+            // Fallback:          -> ldarb
+            ins = canUseLdapur ? INS_ldapurb : hasRcpc ? INS_ldaprb : INS_ldarb;
```
Comment (BruceForstall) [inline src/coreclr/jit/codegenarmarch.cpp:1778]: `canUseLdapur` is only true if `!addrIsInReg` is true, but this code only runs if `addrIsInReg` is true (so `!addrIsInReg` is false). So does the `canUseLdapur` case ever get hit?

Comment (EgorBo) [reply src/coreclr/jit/codegenarmarch.cpp:1778]: ah, my follow-up clean up is not correct (or rather - it disables ldapur), let me revert it

Comment (EgorBo) [reply src/coreclr/jit/codegenarmarch.cpp]: reverted, thanks for noticing!

**Review by BruceForstall — APPROVED** [review]
Seems like all the cases could check `genIsValidIntReg(targetReg)` but I guess since there aren't float versions of the 'h' and 'b' versions you don't need to, but it's somewhat confusing to have to remember that's why the check is only in one place.
