### PR TITLE
Make `coreclr_initialize` run cleanly for `corewasmrun`

### LINKED ISSUE #119001: [wasm coreclr] pinvoke / Qcalls
## PInvoke

We need to handle PInvokes before we have wasm codegen. In the [proof of concept](https://github.com/dotnet/runtime/compare/main...radekdoulik:runtime:clr-interp-qcall-and-helper-call-poc) code I use simple
replacement for `InvokeCompiledMethod`. It is now just handling simple Qcalls with `i32` parameters and void return types. This allowed us to get further in the runtime initialization and needs to be improved.

### Current next step

It needs to map MetaSig to wasm signatures to get the right forwarding function and C function type. Alternatively it might be easier to map the known entrypoints to the forwarding functions and types.

For example, it should map System.RuntimeTypeHandle.GetRuntimeTypeFromHandleSlow signature to `[CallWasmFuncVoidI32I32, void (*fn)(int, int)]` which can then be used to call the native RuntimeTypeHandle_GetRuntimeTypeFromHandleSlow function.
Or alternatively map StackTrace_GetStackFramesInternal to `[CallWasmFuncVoidI32I32, void (*fn)(int, int)]`.

Currently we are reaching these entrypoints (native functions)

    InvokeCompiledMethod: System.RuntimeTypeHandle.GetRuntimeTypeFromHandleSlow --> RuntimeTypeHandle_GetRuntimeTypeFromHandleSlow [entrypoint]
    InvokeCompiledMethod: System.Runtime.CompilerServices.InitHelpers.InitClassHelper --> InitClassHelper [entrypoint]
    InvokeCompiledMethod: System.Diagnostics.StackTrace.<GetStackFramesInternal>g____PInvoke|0_0 --> StackTrace_GetStackFramesInternal [entrypoint]

Note: you can use `wa-info` to check the wasm signatures, like this:

    > wa-info -d -f StackTrace_GetStackFramesInternal ../../artifacts/obj/coreclr/browser.wasm.Debug/hosts/corewasmrun/corewasmrun.wasm|head -1

which outputs

    (func StackTrace_GetStackFramesInternal(param $0 i32, $1 i32, $2 i32))

### Future

We can continue using hand written forwarding functions like

    void CallWasmFuncVoidI32I32(void (*fn)(int, int), int8_t* pArgs)
    {
        (*fn)(((int*)pArgs)[0], ((int*)pArgs)[2]);
    }

and we can later generate them, when we hit a call with unavailable forwarding function. We can generate them at buildtime as C source or at runtime with JS (JavaScript).

Once we have codegen, they can be replaced by real stubs.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
- Separate call invokers between JIT compatible interpreter and interpreter with Portable EntryPoints.
- Native asserts now emit a managed stackwalk with IR offsets of interpreter frames

Current output of `corewasmrun` running on Chrome.

```
coreclr_initialize succeeded - retval: 0x00000000
onExit, code: 0
```

Fixes https://github.com/dotnet/runtime/issues/119001

### CODE REVIEW

File: src/coreclr/vm/interpexec.cpp [hunk 1]
```diff
@@ -2067,18 +1980,15 @@ void InterpExecMethod(InterpreterFrame *pInterpreterFrame, InterpMethodContextFr
                             // small subset of frames high.
                             pInterpreterFrame->SetTopInterpMethodContextFrame(pFrame);
                             GCX_PREEMP();
-                            // Attempt to setup the interpreter code for the target method.
-                            if ((targetMethod->IsIL() || targetMethod->IsNoMetadata()) && !targetMethod->IsUnboxingStub())
-                            {
-                                PrepareInitialCode(targetMethod);
-                            }
+                            CallPreStub(targetMethod);
```
Comment (jkotas) [inline src/coreclr/vm/interpexec.cpp:2194]: As an optimization to avoid the CallPreStub setup in steady state, we can add `if (pMD->IsPointingToPrestub())` around this. It is the same as the early out in `ReflectionInvocation_CompileMethod`.

File: src/coreclr/vm/callstubgenerator.cpp [hunk 2]
```diff
@@ -1902,4 +1902,123 @@ CallStubGenerator::ReturnType CallStubGenerator::GetReturnType(ArgIterator *pArg
...
+{
+    InvokeManagedMethod(targetMethod, stack + callArgsOffset, stack + returnOffset, callTarget);
+}
+
+void InvokeDelegateInvokeMethod(MethodDesc *pMDDelegateInvoke, int8_t *pArgs, int8_t *pRet, PCODE target)
+{
+    CONTRACTL
+    {
+        THROWS;
+        MODE_ANY;
```
Comment (jkotas) [inline src/coreclr/vm/callstubgenerator.cpp]:
```suggestion
        MODE_COOPERATIVE;
```

File: src/coreclr/vm/wasm/calldescrworkerwasm.cpp [hunk 3]
```diff
@@ -13,7 +13,7 @@ extern "C" void STDCALL CallDescrWorkerInternal(CallDescrData * pCallDescrData)
     if (targetIp == NULL)
     {
         GCX_PREEMP();
-        pMethod->PrepareInitialCode(CallerGCMode::Coop);
+        (void)pMethod->DoPrestub(NULL /* MethodTable */, CallerGCMode::Preemptive);
```
Comment (jkotas) [inline src/coreclr/vm/wasm/calldescrworkerwasm.cpp]:
```suggestion
        (void)pMethod->DoPrestub(NULL /* MethodTable */, CallerGCMode::Coop);
```
I think this should be `CallerGCMode::Coop` (or the default `CallerGCMode::Unknown` that takes a slower path).

This argument represents GC mode that the method is expected to be called in. It does not represent the current GC mode. `CallDescrWorkerInternal` is only ever used to invoke managed methods that are expected to be called in cooperative mode.

File: src/coreclr/vm/wasm/helpers.cpp [hunk 4]
```diff
@@ -478,17 +479,66 @@ extern "C" int32_t mono_wasm_browser_entropy(uint8_t* buffer, int32_t bufferLeng
...
+LPVOID GetCookieForCalliSig(MetaSig* pMetaSig)
+{
+    STANDARD_VM_CONTRACT;
+    _ASSERTE(CheckPointer(pMetaSig));
+    _ASSERTE(pMetaSig->IsReturnTypeVoid());
+
+    int32_t numArgs = pMetaSig->NumFixedArgs();
+    switch (numArgs)
+    {
+        case 1: return (LPVOID)&CallFuncVoidI32;
```
Comment (jkotas) [inline src/coreclr/vm/wasm/helpers.cpp]: Check the (normalized) argument types as well to make sure that they match?

File: src/coreclr/vm/prestub.cpp [hunk 5]
```diff
@@ -2297,7 +2297,17 @@ PCODE MethodDesc::DoPrestub(MethodTable *pDispatchingMT, CallerGCMode callerGCMo
...
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+        // Store the IL Stub interpreter data on the actual
+        // P/Invoke MethodDesc.
+        void* ilStubInterpData = PortableEntryPoint::GetInterpreterData(pCode);
+        _ASSERTE(ilStubInterpData != NULL);
+        SetInterpreterCode((InterpByteCodeStart*)ilStubInterpData);
+#else // !FEATURE_PORTABLE_ENTRYPOINTS
+        // Only vararg P/Invoke use shared stubs, they need a precode to push the hidden argument.
+        if (IsVarArg())
+            GetOrCreatePrecode();
```
Comment (jkotas) [inline src/coreclr/vm/prestub.cpp]:
```suggestion
```
It may make more sense to add `pNMD->GetOrCreatePrecode()` call at   https://github.com/dotnet/runtime/blob/f2b00689e5ab854bdb133014fd13f937fe1a1f76/src/coreclr/vm/dllimport.cpp#L5653-L5656. It will save IsVarArg check that is not cheap, and keep the varargs special handling in fewer places.

(I expect that we are not going to support varargs with `FEATURE_PORTABLE_ENTRYPOINTS`.)

File: src/coreclr/vm/wasm/helpers.cpp [hunk 6]
```diff
@@ -478,17 +479,66 @@ extern "C" int32_t mono_wasm_browser_entropy(uint8_t* buffer, int32_t bufferLeng
...
+        void (*fn)(int32_t, int32_t, int32_t) = (void (*)(int32_t, int32_t, int32_t))ftn;
+        (*fn)(((int32_t*)pArgs)[0], ((int32_t*)pArgs)[2], ((int32_t*)pArgs)[4]);
+    }
+}
+
+LPVOID GetCookieForCalliSig(MetaSig* pMetaSig)
+{
+    STANDARD_VM_CONTRACT;
+    _ASSERTE(CheckPointer(pMetaSig));
+    _ASSERTE(pMetaSig->IsReturnTypeVoid());
```
Comment (jkotas) [inline src/coreclr/vm/wasm/helpers.cpp]: We will also need to check whether this is managed or unmanaged signature since managed vs. unmanaged calling conventions are different for `FEATURE_PORTABLE_ENTRYPOINTS` (managed one has the extra hidden argument).

File: src/coreclr/vm/precode_portable.hpp [hunk 7]
```diff
@@ -31,6 +32,17 @@ class PortableEntryPoint final
 
 public:
     void Init(MethodDesc* pMD);
+
+    // Query methods for entry point state.
+    bool IsInitialized() const { return _pMD != nullptr; }
+    bool IsByteCodeCompiled() const { return IsInitialized() && _pInterpreterData != nullptr; }
```
Comment (jkotas) [inline src/coreclr/vm/precode_portable.hpp]:
```suggestion
    bool IsByteCodeCompiled() const
    {
        _ASSERTE(IsInitialized());
        return _pInterpreterData != nullptr;
    }
```
We should never see uninitialized entrypoints in circulation. These should be asserts. (We can also assert that the canary is good in IsIniitalized. Maybe a better name for the method would be `IsValid`.

File: src/coreclr/vm/precode_portable.cpp [hunk 8]
```diff
@@ -29,6 +29,16 @@ void* PortableEntryPoint::GetActualCode(TADDR addr)
     return portableEntryPoint->_pActualCode;
 }
 
+void PortableEntryPoint::SetActualCode(TADDR addr, void* actualCode)
+{
+    STANDARD_VM_CONTRACT;
+    _ASSERTE(actualCode != NULL);
+
+    PortableEntryPoint* portableEntryPoint = ToPortableEntryPoint(addr);
+    _ASSERTE(portableEntryPoint->_pActualCode == NULL);
```
Comment (jkotas) [inline src/coreclr/vm/precode_portable.cpp]: I do not expect this assert to hold. This is likely going to be updated in lock-free manner.

File: src/coreclr/vm/jitinterface.cpp [hunk 9]
```diff
@@ -10871,12 +10867,22 @@ void CEECodeGenInfo::getHelperFtn(CorInfoHelpFunc    ftnNum,               /* IN
 
             if (IndirectionAllowedForJitHelper(ftnNum))
             {
+                InfoAccessType accessType;
+                LPVOID targetAddr;
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+                accessType = IAT_VALUE;
+                targetAddr = (LPVOID)helperMD->GetPortableEntryPoint();
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]: We also need to change how the `pNativeEntrypoint` gets returned below. Otherwise, there would be an ambiguity about whether `IAT_VALUE` means portable entrypoint or native entrypoint (aka "actual code").

File: src/coreclr/vm/wasm/calldescrworkerwasm.cpp (hunk 3 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/wasm/calldescrworkerwasm.cpp]: Okay. I recall adding this and the name is very misleading then. I must have misunderstood something when I added it. An enum called `CallerGCMode` seems rather clear that it is the current state of the caller.

File: src/coreclr/vm/prestub.cpp (hunk 5 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/prestub.cpp]: Good idea.

File: src/coreclr/vm/wasm/calldescrworkerwasm.cpp (hunk 3 above)
Comment (jkotas) [reply src/coreclr/vm/wasm/calldescrworkerwasm.cpp]: It is the state that the original caller is in before any transitions. `DoPrestub` has preemptive mode contract, so it would not make sense to pass in mode of the immediate `DoPrestub` caller.

File: src/coreclr/vm/wasm/helpers.cpp (hunk 4 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/wasm/helpers.cpp]: This was a bit of a slap dash solution. I can start on a more robust validation scheme if you like. I suppose asserting certain invariants is warranted though.

File: src/coreclr/vm/jitinterface.cpp (hunk 9 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp]: Is this one of those cases where we flip a low order bit?

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp]: Done.

File: src/coreclr/vm/threads.cpp [hunk 10]
```diff
@@ -1062,10 +1062,12 @@ void InitThreadManager()
     }
     CONTRACTL_END;
 
+#ifndef TARGET_WASM
     // All patched helpers should fit into one page.
```
Comment (jkotas) [inline src/coreclr/vm/threads.cpp:1066]: Can we delete `JIT_PatchedCodeLast` and `JIT_PatchedCodeStart` from wasm helpers.cpp now?

File: src/coreclr/vm/precode_portable.hpp [hunk 11]
```diff
@@ -31,6 +34,32 @@ class PortableEntryPoint final
...
+    }
+
+    bool HasNativeCode() const
+    {
+        LIMITED_METHOD_CONTRACT;
+        _ASSERTE(IsValid());
+        return _pActualCode != nullptr;
+    }
+
+    bool IsReadyForR2R() const
```
Comment (janvorli) [inline src/coreclr/vm/precode_portable.hpp]: A nit - would it make sense naming this `IsReadyForAOT` or `IsReadyForAOTCall` instead?

File: src/coreclr/vm/callstubgenerator.cpp [hunk 12]
```diff
@@ -1902,4 +1902,122 @@ CallStubGenerator::ReturnType CallStubGenerator::GetReturnType(ArgIterator *pArg
     return ReturnTypeVoid;
 }
 
+static CallStubHeader *UpdateCallStubForMethod(MethodDesc *pMD)
```
Comment (janvorli) [inline src/coreclr/vm/callstubgenerator.cpp]: What was the reason for moving these methods to the callstubgenerator? I would prefer keeping only the implementation oof the CallStubGenerator class in this file.

File: src/coreclr/vm/jitinterface.cpp (hunk 9 above)
Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp]: I do not think we want to do any bit flipping for entrypoints on wasm. As you have discovered, low order fit bit flipping would not work on wasm anyway since the native function pointers on wasm are ordinals starting with 1. I do not think that anything in wasm spec says that the high order bit of function pointer ordinal is unused.

I think we want to create and return pointer to PortableEntryPoint even for the native helpers here.

I am a bit surprised that we are able to go through whole `coreclr_initialize` with this issue. Are we lucky that we only ever call the managed JIT helpers during `coreclr_initialize`?

File: src/coreclr/vm/precode_portable.hpp (hunk 11 above)
Comment (jkotas) [reply src/coreclr/vm/precode_portable.hpp]: I would call this "IsPreparedForNativeCall`.

We have a prior art of using "Prepare" in similar solutions. For example, look for `PrepareForUseAsAFunctionPointer` or `PrepareForUseAsADependencyOfANativeImage`.

File: src/coreclr/vm/precode_portable.hpp [hunk 13]
```diff
@@ -31,6 +34,32 @@ class PortableEntryPoint final
 
 public:
     void Init(MethodDesc* pMD);
+
+    // Query methods for entry point state.
+    bool IsValid() const;
+
+    bool IsByteCodeCompiled() const
```
Comment (jkotas) [inline src/coreclr/vm/precode_portable.hpp]: This name makes is sound like that the byte code was compiled into something that's not right. The byte code is the product of the compilation.

I would call this `HasInterpreterCode`. I think we use "Interpreter Code" in this context in majority of the codebase (e.g. `MethodDesc::GetInterpreterCode`).

File: src/coreclr/vm/jitinterface.cpp [hunk 14]
```diff
@@ -10871,12 +10867,22 @@ void CEECodeGenInfo::getHelperFtn(CorInfoHelpFunc    ftnNum,               /* IN
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]: The current scheme where `hlpFuncTable` entry that is less than `DYNAMIC_CORINFO_HELP_COUNT` implies dynamic helper won't work reliably for wasm. Wasm function pointers are ordinals that start with like `1`, so this trick won't work.

For wasm, I think we need to change `hlpFuncTable` that has just native code pointers, and separate table that has the information about dynamic entry points (or change `hlpFuncTable` to be array of structs).

File: src/coreclr/vm/callstubgenerator.cpp (hunk 12 above)
Comment (jkotas) [reply src/coreclr/vm/callstubgenerator.cpp]: Reduce ifdefs. We are going to have two implementations of the calling convention converters: 
- The low-level one (CallStubGenerator) that generates them at runtime and that is used on platforms where the low-level tricks work (Apple) 
- The portable one that generates them at build time and that is used on platforms where the low-level tricks do not work (wasm)

Would you prefer to have this in interpexec.cpp with ifdefs instead?

Comment (janvorli) [reply src/coreclr/vm/callstubgenerator.cpp]: In that case, I'd prefer a new separate .cpp file, one for the wasm one and one for the other one. Maybe place the wasm one under the existing wasm subdirectory.

File: src/coreclr/vm/jitinterface.cpp (hunk 9 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp]: > I do not think that anything in wasm spec says that the high order bit of function pointer ordinal is unused.

I changed this to be the high order bit and it does work without issue. I researched this is a bit and found there is nothing explicit about the full 32-bits being used, but practically all implementations have a limit on the function table. I've found limits of 1,000,000 to 10,000,000. We can explore other options, but for now this seems to be the accepted practical limit.

File: src/coreclr/vm/precode_portable.hpp (hunk 11 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/precode_portable.hpp]: `IsPreparedForNativeCall` seems closet to intent here.

File: src/coreclr/vm/threads.cpp (hunk 10 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/threads.cpp:1066]: No, there are a bunch of uses of it. None of them make a lot of sense, but I'm not sure what to replace them with on WASM. All involve write barrier logic.

File: src/coreclr/vm/callstubgenerator.cpp (hunk 12 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/callstubgenerator.cpp]: > Maybe place the wasm one under the existing wasm subdirectory.

The wasm one is in a cpp under the wasm directory. The code here is specifically the versions that use `CallStubGenerator`. I can place these functions in a new cpp, but that seems odd since these functions require `CallStubGenerator`. We're down to moving them back into `interpexec.cpp` under a non WASM ifdef _or_ placing them in a new cpp. What would be the name of the new cpp to contain the functions that require `CallStubGenerator`?

File: src/coreclr/vm/jitinterface.cpp (hunk 9 above)
Comment (radekdoulik) [reply src/coreclr/vm/jitinterface.cpp]: > I am a bit surprised that we are able to go through whole coreclr_initialize with this issue. Are we lucky that we only ever call the managed JIT helpers during coreclr_initialize?

Possibly, I checked the helper opcodes, not sure whether the JIT helpers are also called through different path.

During `coreclr_initialize` we call just a few. I checked the log output and currently the managed code involved in initialization could possibly call these
```
inc/jithelpers.h:    DYNAMICJITHELPER(CORINFO_HELP_CHKCASTANY,               NULL,   METHOD__CASTHELPERS__CHKCASTANY)
inc/jithelpers.h:    DYNAMICJITHELPER(CORINFO_HELP_CHKCASTCLASS,             NULL,   METHOD__CASTHELPERS__CHKCASTCLASS)
inc/jithelpers.h:    DYNAMICJITHELPER(CORINFO_HELP_CHKCASTCLASS_SPECIAL,     NULL,   METHOD__CASTHELPERS__CHKCASTCLASSSPECIAL)
inc/jithelpers.h:    DYNAMICJITHELPER(CORINFO_HELP_GET_GCSTATIC_BASE,                JIT_GetGCStaticBase, METHOD__STATICSHELPERS__GET_GC_STATIC)
inc/jithelpers.h:    DYNAMICJITHELPER(CORINFO_HELP_INITCLASS,           NULL, METHOD__INITHELPERS__INITCLASS)
inc/jithelpers.h:    DYNAMICJITHELPER(CORINFO_HELP_ISINSTANCEOFCLASS,        NULL,   METHOD__CASTHELPERS__ISINSTANCEOFCLASS)
inc/jithelpers.h:    DYNAMICJITHELPER(CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPEHANDLE,  NULL,   METHOD__RT_TYPE_HANDLE__GETRUNTIMETYPEFROMHANDLE)
inc/jithelpers.h:    DYNAMICJITHELPER(CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPEHANDLE_MAYBENULL,    NULL,   METHOD__RT_TYPE_HANDLE__GETRUNTIMETYPEFROMHANDLEMAYBENULL)
```
which look like all managed except one.

`JIT_GetGCStaticBase` is possibly native, the `JIT_GetGCStaticBase` is defined as NULL though, so I think we use the managed version of it. And indeed, I see
```
Compiled method: .System.Runtime.CompilerServices.StaticsHelpers:GetGCStaticBase(ptr)
```
in the log.

The helper opcodes should be fine though as they use `GetPossiblyIndirectHelper`, which calls `PortableEntryPoint::GetActualCode` and that removes the mask (bit). Again, maybe we call the JIT helpers elsewehere too?

I agree that not using the mask would be cleaner, maybe add TODO-WASM comment for now?

BTW, the function indices start from 0.
```
> wa-info -vv ../../artifacts/obj/coreclr/browser.wasm.Debug/hosts/corewasmrun/corewasmrun.wasm
...
Reading section:    Custom size:      3023182 name: name
  module name: corewasmrun.wasm
      function names count: 33536
        function idx: 0 name: __assert_fail
        function idx: 1 name: abort
        function idx: 2 name: exit
...
```

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp]: This is broken in multiple ways - see my other feedback in https://github.com/dotnet/runtime/pull/119217#discussion_r2314120083 . I think we should do this properly so that we do not have to keep coming back to this.

File: src/coreclr/vm/callstubgenerator.cpp (hunk 12 above)
Comment (janvorli) [reply src/coreclr/vm/callstubgenerator.cpp]: Maybe `nativecodeinvocation.cpp`, similar to `reflectioninvocation.cpp` naming.

Comment (jkotas) [reply src/coreclr/vm/callstubgenerator.cpp]: This not a general-purpose native code invocation scheme. It is very specific to interpreter executor.

I think my personal preference would be ifdefs in interpexec.cpp. We are going to have number of ifdefs for portable entrypoints there, so a few more or less won't make a huge difference.

File: src/coreclr/vm/callhelpers.cpp [hunk 15]
```diff
@@ -224,9 +224,13 @@ void* DispatchCallSimple(
     callDescrData.fpReturnSize = 0;
     callDescrData.pTarget = pTargetAddress;
 
-#ifdef TARGET_WASM
-    PORTABILITY_ASSERT("wasm need to fill call description data");
-#endif
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+    callDescrData.pMD = PortableEntryPoint::GetMethodDesc(pTargetAddress);
```
Comment (jkotas) [inline src/coreclr/vm/callhelpers.cpp]: Can we delete `pMD` from WASM `callDescrData` and move `PortableEntryPoint::GetMethodDesc` call into `CallDescrWorkerInternal`?

File: src/coreclr/vm/callstubgenerator.cpp (hunk 12 above)
Comment (janvorli) [reply src/coreclr/vm/callstubgenerator.cpp]: Sounds good to me too.

File: src/coreclr/vm/jitinterface.cpp (hunk 9 above)
Comment (radekdoulik) [reply src/coreclr/vm/jitinterface.cpp]: Just to add more details, the function indices also include imports, so the lower indices are for imports and actual functions with code in `.wasm` are on top of that. So in the previous output, the first 3 function indices are of imported functions (these come from JS in this case).
```
...
Reading section:    Import size:         1265 count: 48
  (import "env" "__assert_fail" (TypeIdx  typeidx: 8))
  (import "env" "abort" (TypeIdx  typeidx: 9))
  (import "env" "exit" (TypeIdx  typeidx: 2))
...
```

File: src/coreclr/vm/callhelpers.cpp [hunk 16]
```diff
@@ -224,9 +224,13 @@ void* DispatchCallSimple(
...
+    callDescrData.nArgsSize = numStackSlotsToCopy * sizeof(ARGHOLDER_TYPE);
+
+    TransitionBlock block{};
+    callDescrData.pTransitionBlock = &block;
```
Comment (jkotas) [inline src/coreclr/vm/callhelpers.cpp]: This does not look right either. `TransitionBlock` is open sized structure that is expected to contain the arguments. I think the right solution is to delete `pTransitionBlock` from `CallDescrData` and adjust the rest as needed.

File: src/coreclr/vm/callhelpers.cpp (hunk 15 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/callhelpers.cpp]: Yep, done.

File: src/coreclr/vm/callhelpers.cpp (hunk 16 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/callhelpers.cpp]: Is this needed for WASM? The `TransitionBlock` on WASM has little if any content at present. Is this a temporary state?

Comment (jkotas) [reply src/coreclr/vm/callhelpers.cpp]: I am not sure why it was needed on wasm. It should not be needed on wasm here to make wasm look more like other architectures.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/callhelpers.cpp]: > I am not sure why it was needed on wasm. I

Perfect. Thank you.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/callhelpers.cpp]: Passing `NULL` along to `ExecuteInterpretedMethodWithArgs` will evetually get to `InterpreterFrame`, which forwards it on to `FramedMethodFrame` and that shares it via `TransitionFrame::GetTransitionBlock()`. I can let the `NULL` flow and we can fix it up as it flows _or_ in WASM's `CallDescrWorkerInternal`, I can create a dummy that does basically nothing. Do you have a preference?

Comment (jkotas) [reply src/coreclr/vm/callhelpers.cpp]: I would create a dummy in `CallDescrWorkerInternal` or in `ExecuteInterpretedMethodWithArgs` for now.

File: src/coreclr/vm/interpexec.cpp [hunk 17]
```diff
@@ -500,20 +433,25 @@ LONG IgnoreCppExceptionFilter(PEXCEPTION_POINTERS pExceptionInfo, PVOID pv)
         : EXCEPTION_EXECUTE_HANDLER;
 }
 
-// Wrapper around MethodDesc::PrepareInitialCode to handle possible managed exceptions thrown by it.
-void PrepareInitialCode(MethodDesc *pMD)
+// Wrapper around MethodDesc::DoPrestub to handle possible managed exceptions thrown by it.
+static void CallPreStub(MethodDesc *pMD, CallerGCMode callerGCMode = CallerGCMode::Preemptive)
```
Comment (jkotas) [inline src/coreclr/vm/interpexec.cpp]:
```suggestion
static void CallPreStub(MethodDesc *pMD)
```

File: src/coreclr/vm/interpexec.cpp [hunk 18]
```diff
@@ -500,20 +433,25 @@ LONG IgnoreCppExceptionFilter(PEXCEPTION_POINTERS pExceptionInfo, PVOID pv)
...
     STATIC_STANDARD_VM_CONTRACT;
+    _ASSERTE(pMD != NULL);
+
+    if (!pMD->IsPointingToPrestub())
+        return;
 
     struct Param
     {
         MethodDesc *pMethodDesc;
+        CallerGCMode callerGCMode;
```
Comment (jkotas) [inline src/coreclr/vm/interpexec.cpp]:
```suggestion
```

File: src/coreclr/vm/interpexec.cpp [hunk 19]
```diff
@@ -500,20 +433,25 @@ LONG IgnoreCppExceptionFilter(PEXCEPTION_POINTERS pExceptionInfo, PVOID pv)
...
     }
-    param = { pMD };
+    param = { pMD, callerGCMode };
 
     PAL_TRY(Param *, pParam, &param)
     {
-        pParam->pMethodDesc->PrepareInitialCode(CallerGCMode::Coop);
+        (void)pParam->pMethodDesc->DoPrestub(NULL /* MethodTable */, pParam->callerGCMode);
```
Comment (jkotas) [inline src/coreclr/vm/interpexec.cpp]:
```suggestion
        (void)pParam->pMethodDesc->DoPrestub(NULL /* MethodTable */, CallerGCMode::Coop);
```

**Review by jkotas — COMMENTED** [review]
CallerGCMode should be Coop.

File: src/coreclr/vm/interpexec.cpp (hunk 17 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp]: Yep.

File: src/coreclr/vm/callhelpers.cpp [hunk 20]
```diff
@@ -224,9 +224,9 @@ void* DispatchCallSimple(
     callDescrData.fpReturnSize = 0;
     callDescrData.pTarget = pTargetAddress;
 
-#ifdef TARGET_WASM
-    PORTABILITY_ASSERT("wasm need to fill call description data");
-#endif
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+    callDescrData.nArgsSize = numStackSlotsToCopy * sizeof(ARGHOLDER_TYPE);
+#endif // FEATURE_PORTABLE_ENTRYPOINTS
```
Comment (jkotas) [inline src/coreclr/vm/callhelpers.cpp]:
```suggestion
#ifdef TARGET_WASM
    callDescrData.nArgsSize = numStackSlotsToCopy * sizeof(ARGHOLDER_TYPE);
#endif // TARGET_WASM
```
Given that nArgsSize is under Wasm ifdef everywhere else

File: src/coreclr/vm/precode_portable.hpp [hunk 21]
```diff
@@ -22,7 +25,7 @@ class PortableEntryPoint final
     static PortableEntryPoint* ToPortableEntryPoint(TADDR addr);
 
 private:
-    void* _pActualCode;
+    VolatilePtr<BYTE> _pActualCode;
```
Comment (jkotas) [inline src/coreclr/vm/precode_portable.hpp]:
```suggestion
    Volatile<void*> _pActualCode;
```
Would `Volatile<void*>` work better?

File: src/coreclr/vm/jitinterface.cpp (hunk 9 above)
Comment (SingleAccretion) [reply src/coreclr/vm/jitinterface.cpp]: > practically all implementations have a limit on the function table

I will note that bit tagging using the upper bit will not be able to distinguish entrypoints-as-data allocated above a 2GB boundary and "tagged" native entrypoints. It can be made to work with a bit more complex bit twiddling logic that takes advantage of data alignment though (assuming the entrypoints-as-data are indeed aligned, shift the value left to pack, unshift to unpack).

File: src/coreclr/vm/precode_portable.hpp (hunk 21 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/precode_portable.hpp]: Yep, that works too.

File: src/coreclr/vm/precode_portable.cpp [hunk 22]
```diff
@@ -7,28 +7,53 @@
...
 
+    if (IsNativeEntryPoint(addr))
+    {
+        const TADDR mask = ~NATIVE_ENTRYPOINT_HELPER_BIT;
+        return (void*)(addr & mask);
+    }
+
     PortableEntryPoint* portableEntryPoint = ToPortableEntryPoint(addr);
-    _ASSERTE(portableEntryPoint->_pActualCode != NULL);
+    _ASSERTE(portableEntryPoint->_pActualCode != (void*)NULL);
```
Comment (jkotas) [inline src/coreclr/vm/precode_portable.cpp]:
```suggestion
    _ASSERTE(portableEntryPoint->_pActualCode != nullptr);
```
A few other places use nullptr without any casts. Does it work here?

File: src/coreclr/vm/precode_portable.cpp [hunk 23]
```diff
@@ -7,28 +7,53 @@
...
     return portableEntryPoint->_pActualCode;
 }
 
+void PortableEntryPoint::SetActualCode(TADDR addr, void* actualCode)
+{
+    STANDARD_VM_CONTRACT;
+    _ASSERTE(actualCode != NULL);
+
+    PortableEntryPoint* portableEntryPoint = ToPortableEntryPoint(addr);
+    _ASSERTE(portableEntryPoint->_pActualCode == (void*)NULL || portableEntryPoint->_pActualCode == actualCode);
```
Comment (jkotas) [inline src/coreclr/vm/precode_portable.cpp]:
```suggestion
    _ASSERTE(portableEntryPoint->_pActualCode == nullptr || portableEntryPoint->_pActualCode == actualCode);
```

File: src/coreclr/vm/precode_portable.cpp [hunk 24]
```diff
@@ -7,28 +7,53 @@
 #include "common.h"
 #include "precode_portable.hpp"
 
+// WASM uses function indices so we should avoid using
+// low order bits for masking.
 #ifdef HOST_64BIT
-    #define CANARY_VALUE 0x1234567812345678
+#define CANARY_VALUE 0x1234567812345678
+#define NATIVE_ENTRYPOINT_HELPER_BIT 0x8000000000000000
```
Comment (jkotas) [inline src/coreclr/vm/precode_portable.cpp]: This bit twiddling is the only part that's questionable in this PR. Are you working on cleaning up the JIT helpers handling so that it is not needed?

If you revert the bit twiddling from this PR, I am happy to sign-off on the rest.

File: src/coreclr/vm/wasm/helpers.cpp [hunk 25]
```diff
@@ -478,17 +481,192 @@ extern "C" int32_t mono_wasm_browser_entropy(uint8_t* buffer, int32_t bufferLeng
...
+
+    void CallFunc_I32_I32_I32_RetI32(PCODE pcode, int8_t *pArgs, int8_t *pRet)
+    {
+        int32_t (*fptr)(int32_t, int32_t, int32_t) = (int32_t (*)(int32_t, int32_t, int32_t))pcode;
+        *(int32_t*)pRet = (*fptr)(ARG(0), ARG(1), ARG(2));
+    }
+
+#undef ARG
+
+    void* RetVoidThunks[] =
```
Comment (jkotas) [inline src/coreclr/vm/wasm/helpers.cpp]: These can be `const` arrays. It does not matter a whole lot since this is temporary code.

File: src/coreclr/vm/precode_portable.cpp (hunk 22 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/precode_portable.cpp]: Yes, it will. I'm trying to be consistent with using `NULL` or `nullptr`. Perhaps our default should be `NULL`, unless we need a cast and then `nullptr` if possible?

File: src/coreclr/vm/wasm/helpers.cpp (hunk 25 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/wasm/helpers.cpp]: Yep. I can mark them as such.

File: src/coreclr/vm/precode_portable.cpp (hunk 24 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/precode_portable.cpp]: > Are you working on cleaning up the JIT helpers handling so that it is not needed?

I'm considering options here. I'm okay to just allocate a `PortableEntryPoint` too, which will be attempt (1).

File: src/coreclr/vm/callingconvention.h [hunk 26]
```diff
@@ -1874,11 +1874,14 @@ int ArgIteratorTemplate<ARGITERATOR_BASE>::GetNextOffset()
 
     return argOfs;
 #elif defined(TARGET_WASM)
-    int cbArg = ALIGN_UP(StackElemSize(argSize), TARGET_POINTER_SIZE);
+    // See duplicate definition in interpreter code.
+#define INTERP_STACK_SLOT_SIZE 8
```
Comment (kg) [inline src/coreclr/vm/callingconvention.h]: I'd like to see a comment in interpretershared mentioning that callingconvention.h needs to be updated if the define is changed

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/callingconvention.h]: I've never found those comments very helpful. Instead I've used the exact same define name and indicated it is a duplicate. The first steps for these things are typically, "where is this used?", which should bring people here.

File: src/coreclr/vm/interpexec.cpp [hunk 27]
```diff
@@ -11,14 +11,36 @@
...
+    inlinedCallFrame.m_pCallerReturnAddress = (TADDR)pFrame->ip;
+    inlinedCallFrame.m_pCallSiteSP = pFrame;
+    inlinedCallFrame.m_pCalleeSavedFP = (TADDR)stack;
+    inlinedCallFrame.m_pThread = GetThread();
+    inlinedCallFrame.m_Datum = NULL;
+    inlinedCallFrame.Push();
+
+    {
+        GCX_PREEMP();
+        InvokeManagedMethod(targetMethod, stack + callArgsOffset, stack + returnOffset, callTarget);
```
Comment (kg) [inline src/coreclr/vm/interpexec.cpp:35]: Why is this function called InvokeUnmanagedMethodWithTransition if it's calling InvokeManagedMethod?

File: src/coreclr/vm/interpexec.cpp [hunk 28]
```diff
@@ -101,19 +128,20 @@ void InvokeDelegateInvokeMethod(MethodDesc *pMDDelegateInvoke, int8_t *pArgs, in
     pHeader->Invoke(pHeader->Routines, pArgs, pRet, pHeader->TotalStackSize);
 }
 
-void InvokeCalliStub(PCODE ftn, CallStubHeader *stubHeaderTemplate, int8_t *pArgs, int8_t *pRet)
+void InvokeCalliStub(PCODE ftn, void *cookie, int8_t *pArgs, int8_t *pRet)
```
Comment (kg) [inline src/coreclr/vm/interpexec.cpp:132]: Why are we stripping the type information from this argument and then casting it back to CallStubHeader?

File: src/coreclr/vm/interpexec.cpp [hunk 29]
```diff
@@ -155,35 +191,50 @@ CallStubHeader *CreateNativeToInterpreterCallStub(InterpMethod* pInterpMethod)
...
-    inlinedCallFrame.m_pCalleeSavedFP = (TADDR)stack;
-    inlinedCallFrame.m_pThread = GetThread();
-    inlinedCallFrame.m_Datum = NULL;
-    inlinedCallFrame.Push();
+    Thread* pThread = GetThread();
+
+    int32_t frameCount = 0;
 
+    // Get the "capital F" frame and start walking.
+    for (Frame* pFrame = pThread->GetFrame(); pFrame != FRAME_TOP; pFrame = pFrame->PtrNextFrame())
```
Comment (kg) [inline src/coreclr/vm/interpexec.cpp:207]: Is it possible we enter DBG_PrintInterpreterStack with no frame(s) on the thread? I don't know the answer to this, just wondering since you put a call to this in the assert handler iirc

Comment (kg) [reply src/coreclr/vm/interpexec.cpp:207]: Also is it possible we have no pThread yet if we assert on a native thread that hasn't had a managed thread object set up yet, and then ->GetFrame crashes?

File: src/coreclr/vm/interpexec.cpp (hunk 28 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp:132]: Beacuse this API is used in an agnostic manner. For the `CallStubGenerator` scenario it is a `CallStubHeader`, when `PortableEntryPoint`s are used it is currently a staticly defined thunk. See the other implementation in this PR's `src/coreclr/vm/wasm/helpers.cpp`.

File: src/coreclr/vm/interpexec.cpp (hunk 29 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp:207]: That is possible. I will guard against that.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp:207]: Right, the guard for no Thread is the issue. No capital F frames is already handled by `pFrame != FRAME_TOP`.

File: src/coreclr/vm/interpexec.cpp [hunk 30]
```diff
@@ -1835,9 +1890,25 @@ void InterpExecMethod(InterpreterFrame *pInterpreterFrame, InterpMethodContextFr
...
+                        int stackOffset = pMethod->allocaSize;
+                        callArgsOffset = stackOffset;
+
+                        // Pass argument to the target method
+                        LOCAL_VAR(stackOffset, void*) = helperArg;
+
+                        targetMethod = pILTargetMethod;
+                        ip += 4;
+                        goto CALL_INTERP_METHOD;
+                    }
```
Comment (kg) [inline src/coreclr/vm/interpexec.cpp:1912]: It would be nice if we could encapsulate this repeated logic somehow since it's fairly nuanced but I don't see an easy way to do it since we're populating locals and doing a goto...

File: src/coreclr/vm/interpexec.cpp [hunk 31]
```diff
@@ -1855,9 +1926,26 @@ void InterpExecMethod(InterpreterFrame *pInterpreterFrame, InterpMethodContextFr
...
+                    HELPER_FTN_P_PP helperFtn = GetPossiblyIndirectHelper<HELPER_FTN_P_PP>(pMethod, ip[3], &pILTargetMethod);
+                    if (pILTargetMethod != NULL)
+                    {
+                        returnOffset = ip[1];
+                        int stackOffset = pMethod->allocaSize;
+                        callArgsOffset = stackOffset;
+
+                        // Pass arguments to the target method
+                        LOCAL_VAR(stackOffset, void*) = helperArg;
+                        LOCAL_VAR(stackOffset + INTERP_STACK_SLOT_SIZE, void*) = LOCAL_VAR(ip[2], void*);
```
Comment (kg) [inline src/coreclr/vm/interpexec.cpp]: could `ip[2] == stackOffset` and have been overwritten by the previous assignment?

File: src/coreclr/vm/interpexec.cpp (hunk 27 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp:35]: Because the current `InvokeManagedMethod`, previously `InvokeCompiledMethod`, does double duty in the interpreter path. @jkotas made this suggestion offline.

File: src/coreclr/vm/interpexec.cpp [hunk 32]
```diff
@@ -1890,8 +1992,24 @@ void InterpExecMethod(InterpreterFrame *pInterpreterFrame, InterpMethodContextFr
...
+                    HELPER_FTN_P_PP helperFtn = GetPossiblyIndirectHelper<HELPER_FTN_P_PP>(pMethod, ip[4], &pILTargetMethod);
+                    if (pILTargetMethod != NULL)
+                    {
+                        returnOffset = ip[1];
+                        int stackOffset = pMethod->allocaSize;
+                        callArgsOffset = stackOffset;
 
+                        // Pass arguments to the target method
+                        LOCAL_VAR(stackOffset, void*) = helperArg;
+                        LOCAL_VAR(stackOffset + INTERP_STACK_SLOT_SIZE, void*) = LOCAL_VAR(ip[3], void*);
```
Comment (kg) [inline src/coreclr/vm/interpexec.cpp]: Could `ip[3] == stackOffset`?

File: src/coreclr/vm/interpexec.cpp (hunk 31 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp]: Great question. I don't think it hurts to be defensive in this case. Will do the same below.

File: src/coreclr/vm/interpexec.cpp (hunk 30 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp:1912]: > It would be nice if we could encapsulate this repeated logic somehow since it's fairly nuanced 

There is so much duplicated code in the interpreter, I'm not sure it is changing much. I do agree though that it isn't obvious how to make this simpler and I loathe to introduce a macro of any sort for this. It is already troublesome to read.

File: src/coreclr/vm/precode_portable.cpp [hunk 33]
```diff
@@ -7,28 +7,53 @@
 #include "common.h"
 #include "precode_portable.hpp"
 
+// WASM uses function indices so we should avoid using
+// low order bits for masking.
```
Comment (kg) [inline src/coreclr/vm/precode_portable.cpp]: This comment being above HOST_64BIT is confusing because it makes it seem like the HOST_64BIT guard is sensing WASM

File: src/coreclr/vm/precode_portable.cpp [hunk 34]
```diff
@@ -75,6 +102,13 @@ void PortableEntryPoint::Init(MethodDesc* pMD)
     INDEBUG(_canary = CANARY_VALUE);
 }
 
+bool PortableEntryPoint::IsValid() const
+{
+    LIMITED_METHOD_CONTRACT;
+    _ASSERTE(_canary == CANARY_VALUE);
```
Comment (kg) [inline src/coreclr/vm/precode_portable.cpp]: This feels like it's mixing modes. If it's intended to be safe to call this on an invalid PEP to determine whether it's valid, we shouldn't assert.

If it's not intended to be safe, it should be `void PortableEntryPoint::AssertValid() const` and trigger a runtime failure when given an invalid address.

Comment (kg) [reply src/coreclr/vm/precode_portable.cpp]: I'd also say we should make _canary not INDEBUG if we rely on IsValid/AssertValid to do its job, so it's more likely to work somewhat reliably. I did this to InterpMethod, where for now it has a canary 'self' pointer in the header that points to itself - this made it easier to debug cases where we were treating random addresses as interpreter bytecode or InterpMethod pointers.

I don't know how many portable entry point instances we're going to have though and whether the cost of always having _canary is prohibitive. If we're really determined to have canary be indebug I wonder whether IsValid should be entirely debug-only.

File: src/coreclr/vm/wasm/cgencpu.h [hunk 35]
```diff
@@ -22,8 +22,8 @@
 
 inline unsigned StackElemSize(unsigned parmSize, bool isValueType = false /* unused */, bool isFloatHfa = false /* unused */)
 {
-    _ASSERTE("The function is not implemented on wasm");
-    return 0;
+    const unsigned stackSlotSize = sizeof(void*);
```
Comment (kg) [inline src/coreclr/vm/wasm/cgencpu.h]: Should this be the interpreter stack slot size? I'm not clear on what contract StackElemSize needs to fulfill.
According to GCC's docs, alloca does alignment:
> The __builtin_alloca function must be called at block scope. The function allocates an object size bytes large on the stack of the calling function. The object is aligned on the default stack alignment boundary for the target determined by the __BIGGEST_ALIGNMENT__ macro

And it looks like emscripten also uses clang's `__builtin_alloca`, which probably conforms to the same contract (I couldn't find LLVM's docs for it in a quick search)
So maybe we want to use `__BIGGEST_ALIGNMENT__` here because that's the alignment alloca tries to maintain for its stack?

Pointer size feels fine though, just wanted to sense whether this is 'correct' vs a temporary hack. My only concern is that if parts of the wasm/emscripten stack are aligning to a hard-coded 4 bytes, this would break on wasm64 in a mysterious way.

File: src/coreclr/vm/precode_portable.cpp (hunk 33 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/precode_portable.cpp]: Yep, I'm removing a bunch of thing based on other feedback.

File: src/coreclr/vm/wasm/cgencpu.h (hunk 35 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/wasm/cgencpu.h]: > Should this be the interpreter stack slot size?

Quite possibly. I selected `void*` since I was trying to use what would make sense for wasm64 and ideally it would "naturally" work. It was also before I discovered `INTERP_STACK_SLOT_SIZE`, so I'm fine using that here if that is more appropriate, which it seems like it would be. I defer to you on the clearest value here.

**Comment by kg** [comment]
LGTM! I'll leave giving it a green check to jkotas since he left a lot of feedback.

File: src/coreclr/vm/wasm/cgencpu.h (hunk 35 above)
Comment (kg) [reply src/coreclr/vm/wasm/cgencpu.h]: According to https://reviews.llvm.org/D151820#4385568 `__BIGGEST_ALIGNMENT__` on wasm is a fixed 8 bytes (not 16 like it is on some targets - presumably because vector128 is optional? uncertain) so I think we should use either the interp stack slot size here or `__BIGGEST_ALIGNMENT__` (assuming clang implements that).

File: src/coreclr/vm/callingconvention.h (hunk 26 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/callingconvention.h]: I was able to refactor this and avoid redeclaring the define.

File: src/coreclr/vm/precode_portable.cpp (hunk 34 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/precode_portable.cpp]: > I wonder whether IsValid should be entirely debug-only.

I'll go down this route. We tend not to have magic numbers in release builds.

File: src/coreclr/vm/interpexec.cpp (hunk 27 above)
Comment (jkotas) [reply src/coreclr/vm/interpexec.cpp:35]: The current code makes assumption that the managed calling convention is same as the unmanaged calling convention. That's not a valid assumption. 

I expect that this will need to be redone to handle unmanaged calling conventions properly that you have touched upon on the teams chat. Once it is redone InvokeUnmanagedMwethod won't be calling InvokeManagedMethod anymore.

It may be a good idea to add `WASM-TODO: Handle unmanaged calling conventions` next to this to avoid confusion in the meantime.

File: src/coreclr/vm/interpexec.cpp (hunk 30 above)
Comment (radekdoulik) [reply src/coreclr/vm/interpexec.cpp:1912]: We discussed that with JanV before and he didn't like the macros either, because they are difficult to debug.

File: src/coreclr/vm/jitinterface.cpp [hunk 36]
```diff
@@ -10905,15 +10919,15 @@ PCODE CEECodeGenInfo::getHelperFtnStatic(CorInfoHelpFunc ftnNum)
...
+    // In this case we need to find the actual pfnHelper
+    // using an extra indirection.
+    size_t dynamicFtnNum;
+    if (helperDef.IsDynamicHelper(dynamicFtnNum))
     {
-        pfnHelper = LoadDynamicJitHelper((DynamicCorInfoHelpFunc)((size_t)pfnHelper - 1)).pfnHelper;
+        pfnHelper = LoadDynamicJitHelper((DynamicCorInfoHelpFunc)dynamicFtnNum);
     }
 
     _ASSERTE(pfnHelper != NULL);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/jitinterface.cpp]: @jkotas Should I apply the same `PortableEntryPoint` wrapping here as well?

File: src/coreclr/vm/mlinfo.cpp [hunk 37]
```diff
@@ -2544,7 +2544,13 @@ void MarshalInfo::SetupArgumentSizes()
     const unsigned targetPointerSize = TARGET_POINTER_SIZE;
     const bool pointerIsValueType = false;
     const bool pointerIsFloatHfa = false;
+#ifdef TARGET_WASM
+    // Wasm uses the interpreter which uses a pointer agnostic stack slot size.
+    // Therefore, we only need assert it is sufficiently large.
+    _ASSERTE(targetPointerSize <= StackElemSize(TARGET_POINTER_SIZE, pointerIsValueType, pointerIsFloatHfa));
+#else
     _ASSERTE(targetPointerSize == StackElemSize(TARGET_POINTER_SIZE, pointerIsValueType, pointerIsFloatHfa));
```
Comment (jkotas) [inline src/coreclr/vm/mlinfo.cpp]: I am not sure why this assert is useful. How is it relevant to the code that follows?

I think it would be better to delete it instead of ifdefing it out for wasm.

File: src/coreclr/vm/wasm/cgencpu.h [hunk 38]
```diff
@@ -22,8 +23,8 @@
 
 inline unsigned StackElemSize(unsigned parmSize, bool isValueType = false /* unused */, bool isFloatHfa = false /* unused */)
 {
-    _ASSERTE("The function is not implemented on wasm");
-    return 0;
+    const unsigned stackSlotSize = INTERP_STACK_SLOT_SIZE;
+    return ALIGN_UP(parmSize, stackSlotSize);
```
Comment (jkotas) [inline src/coreclr/vm/wasm/cgencpu.h]: StackElemSize is used to compute the amount of memory used to pass argument in native ABI. It does not make sense to me to tie it together with interpreter. I think it would be better to keep it as is with assert and add just do a local fix in callingconvention.h that's with the interpreter calling convention currently.

File: src/coreclr/vm/callingconvention.h [hunk 39]
```diff
@@ -1874,11 +1874,11 @@ int ArgIteratorTemplate<ARGITERATOR_BASE>::GetNextOffset()
 
     return argOfs;
 #elif defined(TARGET_WASM)
-    int cbArg = ALIGN_UP(StackElemSize(argSize), TARGET_POINTER_SIZE);
+    int cbArg = ALIGN_UP(StackElemSize(argSize), INTERP_STACK_SLOT_SIZE);
```
Comment (jkotas) [inline src/coreclr/vm/callingconvention.h]:
```suggestion
    int cbArg = ALIGN_UP(argSize, INTERP_STACK_SLOT_SIZE);
```

File: src/coreclr/vm/wasm/cgencpu.h [hunk 40]
```diff
@@ -7,6 +7,7 @@
 
 #include "stublink.h"
 #include "utilcode.h"
+#include "../../interpreter/interpretershared.h"
```
Comment (jkotas) [inline src/coreclr/vm/wasm/cgencpu.h]:
```suggestion
```

File: src/coreclr/vm/jithelpers.cpp [hunk 41]
```diff
@@ -2515,24 +2515,31 @@ enum __CorInfoHelpFunc {
...
-#define JITHELPER(code, pfnHelper, binderId) HELPERDEF(code, pfnHelper, binderId)
-#define DYNAMICJITHELPER(code, pfnHelper, binderId) HELPERDEF(code, 1 + DYNAMIC_##code, binderId)
+#define JITHELPER(code, pfnHelper, binderId) HELPERDEF(code, pfnHelper, false)
+#define DYNAMICJITHELPER(code, pfnHelper, binderId) HELPERDEF(code, 1 + DYNAMIC_##code, true)
 #include "jithelpers.h"
 };
 
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+// Collection of entry points for JIT helpers
+TADDR hlpFuncEntryPoints[CORINFO_HELP_COUNT] = {};
```
Comment (jkotas) [inline src/coreclr/vm/jithelpers.cpp]:
```suggestion
PCODE hlpFuncEntryPoints[CORINFO_HELP_COUNT] = {};
```
PCODE is more self-describing

File: src/coreclr/vm/jithelpers.cpp [hunk 42]
```diff
@@ -2561,18 +2592,18 @@ void _SetJitHelperFunction(DynamicCorInfoHelpFunc ftnNum, void * pFunc)
     LOG((LF_JIT, LL_INFO1000000, "Setting JIT dynamic helper %3d (%s) to %p\n",
         ftnNum, hlpDynamicFuncTable[ftnNum].name, pFunc));
 
-    hlpDynamicFuncTable[ftnNum].pfnHelper = (void*)pFunc;
+    hlpDynamicFuncTable[ftnNum].pfnHelper = (TADDR)pFunc;
 }
 
-VMHELPDEF LoadDynamicJitHelper(DynamicCorInfoHelpFunc ftnNum, MethodDesc** methodDesc)
+TADDR LoadDynamicJitHelper(DynamicCorInfoHelpFunc ftnNum, MethodDesc** methodDesc)
```
Comment (jkotas) [inline src/coreclr/vm/jithelpers.cpp]:
```suggestion
PCODE LoadDynamicJitHelper(DynamicCorInfoHelpFunc ftnNum, MethodDesc** methodDesc)
```

File: src/coreclr/vm/jithelpers.cpp [hunk 43]
```diff
@@ -2544,6 +2551,30 @@ static const BinderMethodID hlpDynamicToBinderMap[DYNAMIC_CORINFO_HELP_COUNT] =
 #include "jithelpers.h"
 };
 
+bool VMHELPDEF::IsDynamicHelper(size_t& dynamicFtnNum) const
```
Comment (jkotas) [inline src/coreclr/vm/jithelpers.cpp]:
```suggestion
bool VMHELPDEF::IsDynamicHelper(DynamicCorInfoHelpFunc& dynamicFtnNum) const
```
Also, should this be `DynamicCorInfoHelpFunc*` to make it clear that this is out arg? It is unusual to return out args via `&` in this codebase.

File: src/coreclr/vm/jitinterface.cpp [hunk 44]
```diff
@@ -10755,25 +10751,28 @@ void CEECodeGenInfo::getHelperFtn(CorInfoHelpFunc    ftnNum,               /* IN
...
 
-    size_t dynamicFtnNum = ((size_t)pfnHelper - 1);
-    if (dynamicFtnNum < DYNAMIC_CORINFO_HELP_COUNT)
+    MethodDesc* helperMD = NULL;
+    VMHELPDEF const& helperDef = hlpFuncTable[ftnNum];
+    TADDR pfnHelper = helperDef.pfnHelper;
+
+    size_t dynamicFtnNum;
+    bool isDynamicMethod = helperDef.IsDynamicHelper(dynamicFtnNum);
+    if (isDynamicMethod)
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]:
```suggestion
    bool isDynamicHelper = helperDef.IsDynamicHelper(dynamicFtnNum);
    if (isDynamicHelper)
```
DynamicMethod is a thing that has nothing to do with this.

File: src/coreclr/vm/precode_portable.cpp [hunk 45]
```diff
@@ -8,24 +8,24 @@
...
 
 #ifdef HOST_64BIT
-    #define CANARY_VALUE 0x1234567812345678
+#define CANARY_VALUE 0x1234567812345678
 #else // HOST_64BIT
-    #define CANARY_VALUE 0x12345678
+#define CANARY_VALUE 0x12345678
 #endif // HOST_64BIT
 
 bool PortableEntryPoint::IsNativeEntryPoint(TADDR addr)
```
Comment (jkotas) [inline src/coreclr/vm/precode_portable.cpp]:
```suggestion
bool PortableEntryPoint::HasNativeEntryPoint(TADDR addr)
```
This can return true for interpreted methods with native call stub, so `Has` makes more sense.

File: src/coreclr/vm/jitinterface.cpp [hunk 46]
```diff
@@ -10905,18 +10919,18 @@ PCODE CEECodeGenInfo::getHelperFtnStatic(CorInfoHelpFunc ftnNum)
...
+    if (helperDef.IsDynamicHelper(dynamicFtnNum))
     {
-        pfnHelper = LoadDynamicJitHelper((DynamicCorInfoHelpFunc)((size_t)pfnHelper - 1)).pfnHelper;
+        pfnHelper = LoadDynamicJitHelper((DynamicCorInfoHelpFunc)dynamicFtnNum);
     }
 
-    _ASSERTE(pfnHelper != NULL);
+    _ASSERTE(pfnHelper != (TADDR)NULL);
 
     return GetEEFuncEntryPoint(pfnHelper);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]:
```suggestion
    return pfnHelper;
```

File: src/coreclr/vm/jitinterface.cpp [hunk 47]
```diff
@@ -10859,41 +10846,68 @@ void CEECodeGenInfo::getHelperFtn(CorInfoHelpFunc    ftnNum,               /* IN
...
+    targetAddr = (LPVOID)hlpFuncEntryPoints[ftnNum];
+    if (targetAddr == NULL)
+#endif // FEATURE_PORTABLE_ENTRYPOINTS
     {
-        pNativeEntrypoint->accessType = IAT_VALUE;
-        pNativeEntrypoint->addr = (LPVOID)GetEEFuncEntryPoint(pfnHelper);
+        TADDR entryPoint = GetEEFuncEntryPoint(pfnHelper);
+
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+        NewHolder<PortableEntryPoint> portableEntryPoint = new PortableEntryPoint();
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]:
```suggestion
        PortableEntryPoint* portableEntryPoint = (void*)(SystemDomain::GetGlobalLoaderAllocator()->GetHighFrequencyHeap()->AllocMem(sizeof(PortableEntryPoint));
```
Loader allocator may make more sense for this.

File: src/coreclr/vm/jitinterface.cpp [hunk 48]
```diff
@@ -10859,41 +10846,68 @@ void CEECodeGenInfo::getHelperFtn(CorInfoHelpFunc    ftnNum,               /* IN
...
+    accessType = IAT_VALUE;
+
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+    targetAddr = (LPVOID)hlpFuncEntryPoints[ftnNum];
+    if (targetAddr == NULL)
+#endif // FEATURE_PORTABLE_ENTRYPOINTS
     {
-        pNativeEntrypoint->accessType = IAT_VALUE;
-        pNativeEntrypoint->addr = (LPVOID)GetEEFuncEntryPoint(pfnHelper);
+        TADDR entryPoint = GetEEFuncEntryPoint(pfnHelper);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]:
```suggestion
        TADDR entryPoint = pfnHelper;
```
`GetEEFuncEntryPoint` macro does make sense here. It used to extract actual code on platforms where function pointers did not point to actual code (we do not have any platform like that currently , and it is also used to DACize pointers to runtime functions (this file is not DAcized so it does not apply here).

File: src/coreclr/vm/jitinterface.cpp [hunk 49]
```diff
@@ -10859,41 +10846,68 @@ void CEECodeGenInfo::getHelperFtn(CorInfoHelpFunc    ftnNum,               /* IN
...
-                }
+                accessType = IAT_PVALUE;
+                targetAddr = ((FixupPrecode*)pPrecode)->GetTargetSlot();
+#endif // FEATURE_PORTABLE_ENTRYPOINTS
                 goto exit;
             }
         }
 
-        pfnHelper = LoadDynamicJitHelper((DynamicCorInfoHelpFunc)dynamicFtnNum).pfnHelper;
+        pfnHelper = LoadDynamicJitHelper((DynamicCorInfoHelpFunc)dynamicFtnNum);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]: With portable entrypoints, this returns `PortableEntryPoint*` but then we will go and wrap it in PortableEntryPoint a few lines later again since ` if (targetAddr == NULL)` condition is going to be true. I do not see how this can work.

File: src/coreclr/vm/jitinterface.cpp (hunk 44 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp]: Oops. I thought I replaced all those.

File: src/coreclr/vm/jitinterface.cpp (hunk 36 above)
Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp]: This is only used for R2R fixups. Once we get to then, I think we will require all JIT helpers to be precompiled so that we can call them directly without the PortableEnrypoint indirection. I do not think we will need the wrapping here. Chances are this method is going to be unreachable for wasm. 

I would leave this as is for now.

File: src/coreclr/vm/jitinterface.cpp (hunk 47 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp]: Backout for that is harder. That is why I went with `new`, where the backout logic is far simpler.

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp]: You can use `AllocMemHolder` that is about as hard to backout as NewHolder.

File: src/coreclr/vm/precode_portable.cpp (hunk 45 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/precode_portable.cpp]: Good point.

File: src/coreclr/vm/jitinterface.cpp [hunk 50]
```diff
@@ -10859,41 +10845,70 @@ void CEECodeGenInfo::getHelperFtn(CorInfoHelpFunc    ftnNum,               /* IN
...
-                }
+                accessType = IAT_PVALUE;
+                targetAddr = ((FixupPrecode*)pPrecode)->GetTargetSlot();
+#endif // FEATURE_PORTABLE_ENTRYPOINTS
                 goto exit;
             }
         }
 
-        pfnHelper = LoadDynamicJitHelper((DynamicCorInfoHelpFunc)dynamicFtnNum).pfnHelper;
+        pfnHelper = LoadDynamicJitHelper(dynamicFtnNum);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:10897]: This still does not look right. LoadDynamicJitHelper can return IL-based helper or dynamically assigned native helper. The dynamically assigned helper still needs wrapping by a portable entrypoint. The helpers backed by managed methods are the only ones where we can skip the wrapping.

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp:10897]: I think that the maze of the different paths is impossible to deal with well using interleaved ifdefs. I have pushed a commit into your PR with what I think it should look like. (I have not tested - please beat it into shape.)

I do not really like that `LoadDynamicJitHelper` can return either portable entrypoint or actual code. Refactoring that contract can be done separately.

**Review by jkotas — APPROVED** [review]
LGTM (modulo fixes for breaks that I have introduced by the last commit :)

File: src/coreclr/vm/jitinterface.cpp (hunk 50 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp:10897]: > I do not really like that LoadDynamicJitHelper can return either portable entrypoint or actual code. Refactoring that contract can be done separately.

There are some additional refactorings in this area I'd like to do as well.
