### PR TITLE
Avoid deadlock with ConfigurationManager

### LINKED ISSUE #61747: Possible deadlock in ConfigurationManager in .NET 6
### Description

We have a production HTTP application that we updated recently to .NET 6.0.0 from .NET 6.0.0-rc.2 and have observed a number of issues where the application appeared to be become suddenly unresponsive to HTTP requests. This would cause application health checks to fail, and the instances to be taken out of service.

Having dug into this over the last day or so (https://github.com/dotnet/runtime/issues/60654#issuecomment-970302827), I think I've tracked this down to a deadlock that occurs in `ConfigurationManager` if the application's configuration is manually reloaded at runtime.

Overall the issue appears to be that if an options class is bound to configuration via a type such as `IOptionsMonitor<T>` and there is a change callback bound to `IConfigurationRoot.Reload()`, then the application will deadlock trying to get configuration values to bind to the options class as the lock around getting an option's value:

https://github.com/dotnet/runtime/blob/13024af94f951851d9cee9a7d79911749a25fa3b/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs#L46

will be waiting for the lock acquired during the reload:

https://github.com/dotnet/runtime/blob/13024af94f951851d9cee9a7d79911749a25fa3b/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs#L109

I've captured a memory dump from the application after triggering the issue in our staging environment, and a screenshot of the Parallel Stacks window from Visual Studio taken from inspecting the memory dump is below.

deadlock

Thread 852 has called `IConfigurationRoot.Reload()`, which is blocked on thread 3516 waiting on an options monitor callback for an options class.

Thread 3516 is deadlocked on a call to `IConfiguration[string]` to create an options class.

`IConfiguration` and `IConfigurationRoot` are both the same instance of `ConfigurationManager`.

I haven't ruled out this being a latent bug in our application that .NET 6 has brought to the surface, but we've only had the issue with .NET 6.0.0. We've reverted the application to .NET 6.0.0-rc2 for the time being, and the problem has gone away.

I figured I would log the issue now in case someone looks at it and can quickly find the root cause while I'm continuing to repro this independently or determine it's an actual bug in our app.

### Reproduction Steps

_Will update with a minimal repro project once I can write one up either later today or tomorrow_

A conceptual repro is to do the following two actions concurrently in an app using `WebApplicationBuilder` so `ConfigurationManager` is the app's `IConfigurationRoot`:

1. Reload the `IConfigurationRoot` from an HTTP request in a loop;
2. Issue an HTTP request that resolves `IOptionsMonitor<T>` or `IOptionsSnapshot<T>` from the service provider which is bound to configuration in a loop.

After a period of time (in testing I found this happened within 10 minutes), the application will deadlock.

### Expected behavior

Configuration reloads successfully and does not deadlock requests in flight.

### Actual behavior

The application deadlocks the thread reloading the configuration and other threads accessing the configuration to bind options.

### Regression?

Compared to using `IConfigurationRoot` directly with `Program`/`Startup` (i.e. a non-Minimal API), yes.

### Known Workarounds

I'm not aware of any workarounds at this point, other than not using Minimal APIs when doing configuration reloading at runtime.

### Configuration

* .NET `6.0.0-rtm.21522.10`
* Microsoft Windows 10.0.17763
* Runtime version `6.0.0-rtm.21522.10+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6`
* ASP.NET Core version `6.0.0+ae1a6cbe225b99c0bf38b7e31bf60cb653b73a52`

### Other information

_No response_

### PR DESCRIPTION
**Pull request by halter73**
ConfigurationManager does not attempt to support unrestricted concurrent usage. For example, concurrently adding IConfigurationSources is not thread safe. However, we did attempt to make it possible to safely read configuration while sources are being modified. To support this, I originally added a _providerLock in order to prevent modifications to the configuration sources from interfering with the IConfigurationProvider list while it was being used for concurrent reads.

Unfortunately, locking while blocking on IConfigurationProvider methods is dangerous because these methods can have arbitrary implementations. #61747 shows how this locking can cause a deadlock even without any custom IConfigurationProviders due to the way Load() can trigger ConfigurationReloadToken callbacks inline and the way this interacts with OptionsMonitor/Cache's `Lazy<T>` usage.

To fix this, I decided to make the IConfigurationProvider list copy-on-write. This is enough to stop the list itself from being corrupted during a read operation. However, this makes it more difficult to wait to dispose any removed IConfigurationProvider's until after all readers are done with them. Before, the lock would ensure there were no concurrent readers when an IConfigurationProvider was removed. Now, there could be concurrent readers, but we do not want to block waiting on them to complete.

For this reason, I added reference counting to the copy-on-write IConfigurationProvider list and only dispose the removed IConfigurationProviders after the last reference is removed. There's still a lock to assist with the reference counting, but it's no longer taken when waiting on IConfigurationProvider methods to complete. I am worried that this is unnecessarily complicated though.

### Alternatives considered

Alternatively, considering both IConfigurationProvider.Load() and IConfigurationProvider.TryGet() are "readers" that don't modify the list of IConfigurationProviders, we could consider a ReaderWriterLockSlim. Writers (only things that change the IConfigurationSources) should be very infrequent which might make this a good choice, but [we've been burned by the poor performance of ReaderWriterLockSlim](https://github.com/aspnet/Caching/issues/242) in the past even when there are no writers.

We could also consider disposing the IConfigurationProviders immediately even if there are concurrent readers. In practice, this might be better than it sounds since disposing IConfigurationProviders often doesn't render them completely unusable but instead just unregisters from file change notifications or similar. However, relying on this seems like a very bad idea. It would be reasonable for IConfigurationProviders to start throwing ODEs immediately upon disposal and some already might.

Removing the guarantee that you can safely read from the ConfigurationManager concurrently with IConfigurationSource modification is a last resort, but I think this makes the ConfigurationManager far less useful and harder to use in general. The ability to react to config changes to load new configuration sources is one of the nice features ConfigurationManager provides, and removing this guarantee would be a breaking change. Manually synchronizing source changes shouldn't be too difficult for most apps, but synchronizing everything that reads configuration could be very difficult.

Fixes #61747

Once we agree on an approach, I think we'll need to backport this PR for .NET 6 servicing.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 1]
```diff
@@ -259,6 +234,77 @@ IEnumerator IEnumerable.GetEnumerator()
             }
         }
 
+        private class ProviderManager : IDisposable
```
Comment (kasperk81) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:237]: sealed?

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 2]
```diff
@@ -259,7 +234,78 @@ IEnumerator IEnumerable.GetEnumerator()
...
+            public ProvidersReference(List<IConfigurationProvider> providers)
+            {
+                Providers = providers;
+            }
+
+            public List<IConfigurationProvider> Providers { get; set; }
+
+            public void AddRef()
+            {
+                Interlocked.Increment(ref _refCount);
```
Comment (stephentoub) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:293]: What happens if _refCount was already 0 so this was already disposed?  Is that just something we don't care about? Or it's not possible by construction of consumers?

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 3]
```diff
@@ -259,7 +234,78 @@ IEnumerator IEnumerable.GetEnumerator()
             }
         }
 
-        private class ConfigurationBuilderProperties : IDictionary<string, object>
+        private sealed class ProviderManager : IDisposable
+        {
+            private readonly object _replaceProvidersLock = new object();
+            private ProvidersReference _refCountedProviders = new(new List<IConfigurationProvider>());
+
+            public IEnumerable<IConfigurationProvider> Providers => _refCountedProviders.Providers;
```
Comment (stephentoub) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:242]: You could be accessing disposed providers here.  That's ok?

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 4]
```diff
@@ -259,7 +234,78 @@ IEnumerator IEnumerable.GetEnumerator()
...
+                    _refCountedProviders = new ProvidersReference(providers);
+                }
+
+                oldRefCountedProviders.Dispose();
+            }
+
+            public void AddProvider(IConfigurationProvider provider)
+            {
+                // Maintain existing references, but replace list with copy containing new item.
+                _refCountedProviders.Providers = new List<IConfigurationProvider>(_refCountedProviders.Providers)
```
Comment (stephentoub) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:271]: Technically this should be done with a volatile write, in order to ensure all of the writes that initialize the list are published before the write that updates Providers.  In practice, the runtime needs a barrier anyway, so it won't matter.  I personally prefer to make it clear in the code.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 5]
```diff
@@ -259,7 +234,78 @@ IEnumerator IEnumerable.GetEnumerator()
             }
         }
 
-        private class ConfigurationBuilderProperties : IDictionary<string, object>
+        private sealed class ProviderManager : IDisposable
```
Comment (stephentoub) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:237]: Comments would be helpful, in particular outlining what thread-safety guarantees are being made and what usage is explicitly unprotected / undefined.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs (hunk 2 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:293]: `AddRef()` is only called by `ProviderManager.GetReference()` with the `_replaceProvidersLock` lock to ensure that this doesn't happen.

```
                // Lock to ensure oldRefCountedProviders.Dispose() in ReplaceProviders() doesn't decrement ref count to zero
                // before calling _refCountedProviders.AddRef().
```

I'll add a comment here too.

It should not be possible for the `_refCount` to go to zero until `ReplaceProviders` calls `oldRefCountedProviders.Dispose()` or the entire `ConfigurationManager` is disposed.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs (hunk 3 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:242]: > You could be accessing disposed providers here. That's ok?

It's not completely ok. This was also a problem before this change because we couldn't keep the lock for as long as an app had a reference to the exposed `IEnumerable<IConfigurationProvider>`. I have this comment in the one place we reference this.

```
        // We cannot track the duration of the reference to the providers if this property is used.
        // If a configuration source is removed after this is accessed but before it's completely enumerated,
        // this may allow access to a disposed provider.
        IEnumerable<IConfigurationProvider> IConfigurationRoot.Providers => _providerManager.Providers;
```

I can add a comment here too to explain this is specifically to support `IConfigurationRoot.Providers`.

> Or is the idea that you should only ever be accessing this property when you're holding the reference returned from GetReference? In that case, consider asserting here that its ref count > 0.

That's the idea for the more-commonly-used `ProvidersReference.Providers`. I can add an assert there.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 6]
```diff
@@ -43,17 +43,13 @@ public ConfigurationManager()
         {
             get
             {
-                lock (_providerLock)
-                {
-                    return ConfigurationRoot.GetConfiguration(_providers, key);
-                }
+                using var reference = _providerManager.GetReference();
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:46]: (nit) `var` shouldn't be used here since the type isn't obvious from the left hand side.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 7]
```diff
@@ -63,35 +59,24 @@ public ConfigurationManager()
...
-            {
-                lock (_providerLock)
-                {
-                    return new List<IConfigurationProvider>(_providers);
-                }
-            }
-        }
+        // We cannot track the duration of the reference to the providers if this property is used.
+        // If a configuration source is removed after this is accessed but before it's completely enumerated,
+        // this may allow access to a disposed provider.
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:72]: How concerned should we be able this scenario?

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 8]
```diff
@@ -21,8 +21,8 @@ public sealed class ConfigurationManager : IConfigurationBuilder, IConfiguration
         private readonly ConfigurationSources _sources;
         private readonly ConfigurationBuilderProperties _properties;
 
-        private readonly object _providerLock = new();
-        private readonly List<IConfigurationProvider> _providers = new();
+        // _providerManager provides copy-on-write references. It waits until all readers unreference before disposing any providers.
+        private readonly ProviderManager _providerManager = new();
         private readonly List<IDisposable> _changeTokenRegistrations = new();
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:26]: I see `_changeTokenRegistrations` is now being mutated without the lock. Is that going to be a problem?

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs (hunk 4 above)
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:271]: Would it make sense to initialize this list with `_refCountedProviders.Providers.Count + 1` capacity? That way when you add the new provider, if we are at a bound (like going from 4 to 5), we don't immediately grow the backing array.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs (hunk 8 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:26]: As @stephentoub says, I need to provide better comments about the thread safety guarantees. I'm working on that now.

But to answer the question, the `_changeTokenRegistrations` list is similar to `_sources` in that it's only referenced when config sources are modified and when the ConfigurationManager is disposed. Concurrently modifying sources or disposing while modifying sources was never thread safe. It should still be safe to read config while `_changeTokenRegistrations` is concurrently modified.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs (hunk 7 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:72]: I definitely don't like it, but I'm not very concerned because this comment is describing the existing behavior and I haven't heard complaints yet. Even when we had the `_providerLock`, we released it before returning the copied list.

I can think of two main reasons this hasn't been a bigger issue:
1. It's not super common to access `IConfigurationRoot.Providers` vs other `IConfiguration` methods and accessors.
2. Disposing IConfigurationProviders often doesn't render them completely unusable but instead just unregisters from file change notifications or similar.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs (hunk 4 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:271]: That's a pretty cool idea. I'm not sure it's worth the effort though. There's a lot of other work involved in adding a configuration source.

**Comment by halter73** [comment]
I think the first round of feedback has been addressed.

File: src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs [hunk 9]
```diff
@@ -20,11 +20,16 @@ internal static class InternalConfigurationRootExtensions
         /// <returns>Immediate children sub-sections of section specified by key.</returns>
         internal static IEnumerable<IConfigurationSection> GetChildrenImplementation(this IConfigurationRoot root, string? path)
         {
-            return root.Providers
+            using ReferenceCountedProviders? reference = (root as ConfigurationManager)?.GetProvidersReference();
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs:23]: I wonder if this code makes sense here. What if the "special" logic here was moved into `ConfigurationManager` - calling `GetProvidersReference()` and `ToList()`? We could still share the inner logic here, we just wouldn't be paying the cost nor complexity in code paths outside of ConfigurationManager.

This would also remove the need for the `internal GetProvidersReference()` method on ConfigurationManager.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 10]
```diff
@@ -106,9 +92,9 @@ IConfigurationBuilder IConfigurationBuilder.Add(IConfigurationSource source)
 
         void IConfigurationRoot.Reload()
         {
-            lock (_providerLock)
+            using (var reference = _providerManager.GetReference())
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:95]: Bad `var` usage. Repeated elsewhere in this code.

File: src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+        private readonly object _replaceProvidersLock = new object();
+        private ReferenceCountedProviders _refCountedProviders = new(new List<IConfigurationProvider>());
+
+        // This is only used to support IConfigurationRoot.Providers because we cannot track the lifetime of that reference.
+        public IEnumerable<IConfigurationProvider> NonReferenceCountedProviders => _refCountedProviders.NonReferenceCountedProviders;
+
+        public ReferenceCountedProviders GetReference()
+        {
+            // Lock to ensure oldRefCountedProviders.Dispose() in ReplaceProviders() doesn't decrement ref count to zero
+            // before calling _refCountedProviders.AddRef().
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs:23]:
```suggestion
            // before calling _refCountedProviders.AddReference().
```

File: src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs [hunk 12]
```diff
@@ -0,0 +1,55 @@
...
+        public void AddProvider(IConfigurationProvider provider)
+        {
+            // Maintain existing references, but replace list with copy containing new item.
+            _refCountedProviders.Providers = new List<IConfigurationProvider>(_refCountedProviders.Providers)
+            {
+                provider
+            };
+        }
+
+        public void Dispose() => _refCountedProviders.Dispose();
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs:53]: Should we assert that `_refCountedProviders` refcount is `0` after disposing it?

**Review by eerhardt — APPROVED** [review]
I think this approach looks good. I just had some minor comments.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs (hunk 10 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:95]: My find/replace failed here because it's `using (var ...`  instead of `using var ...`. Did I miss this somewhere else?

File: src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs (hunk 9 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs:23]: I initially went that route, but the problem is that `ConfigurationSection` also calls into this internal method and should use `ReferenceCountedProviders` when paired with `ConfigurationManager`.

I considered making a custom `IConfigurationSection` implementation for `ConfigurationManager` but was concerned that changing the runtime type from one public type to something else could be breaking to applications that might cast the `IConfigurationSection` to `ConfigurationSection`. Maybe that's too paranoid, but I would like to get this serviced.

I also considered doing this logic just in `ConfigurationManager.GetChildren()` and `ConfigurationSection.GetChildren()`, but at that point `ConfigurationRoot.GetChildren()` would be the only thing without this logic.

I could skip the `.ToList()` when this isn't being used with a `ConfigurationManager` though.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 13]
```diff
@@ -106,9 +92,9 @@ IConfigurationBuilder IConfigurationBuilder.Add(IConfigurationSource source)
...
             {
-                foreach (var provider in _providers)
+                foreach (var provider in reference.Providers)
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:97]: Bad var usage.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 14]
```diff
@@ -126,59 +114,49 @@ private void RaiseChanged()
         // Don't rebuild and reload all providers in the common case when a source is simply added to the IList.
         private void AddSource(IConfigurationSource source)
         {
-            lock (_providerLock)
-            {
-                var provider = source.Build(this);
-                _providers.Add(provider);
+            var provider = source.Build(this);
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:117]: Bad var usage.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 15]
```diff
@@ -126,59 +114,49 @@ private void RaiseChanged()
...
-                    _providers.Add(source.Build(this));
-                }
+            var newProvidersList = new List<IConfigurationProvider>();
 
-                foreach (var p in _providers)
-                {
-                    p.Load();
-                    _changeTokenRegistrations.Add(ChangeToken.OnChange(() => p.GetReloadToken(), () => RaiseChanged()));
-                }
+            foreach (var source in _sources)
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:135]: Bad var usage.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 16]
```diff
@@ -126,59 +114,49 @@ private void RaiseChanged()
...
+            {
+                newProvidersList.Add(source.Build(this));
+            }
+
+            foreach (var p in newProvidersList)
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:140]: Bad var usage.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs [hunk 17]
```diff
@@ -126,59 +114,49 @@ private void RaiseChanged()
...
 
+            _providerManager.ReplaceProviders(newProvidersList);
             RaiseChanged();
         }
 
-        private void DisposeRegistrationsAndProvidersUnsynchronized()
+        private void DisposeRegistrations()
         {
             // dispose change token registrations
             foreach (var registration in _changeTokenRegistrations)
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:153]: Bad var usage.

File: src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs [hunk 18]
```diff
@@ -20,11 +20,16 @@ internal static class InternalConfigurationRootExtensions
...
+            var providers = reference?.Providers ?? root.Providers;
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs:24]: Bad var usage.

File: src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProviders.cs [hunk 19]
```diff
@@ -0,0 +1,59 @@
...
+            // AddReference() is always called with a lock to ensure _refCount hasn't already decremented to zero.
+            Debug.Assert(_refCount > 0);
+            Interlocked.Increment(ref _refCount);
+        }
+
+        public void Dispose()
+        {
+            if (Interlocked.Decrement(ref _refCount) == 0)
+            {
+                foreach (var provider in _providers)
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProviders.cs:52]: Bad var usage.

**Review by eerhardt — COMMENTED** [review]
I marked all the bad `var` usages.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs (hunk 10 above)
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs:95]: I added a new review with each one marked.

File: src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs (hunk 9 above)
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs:23]: > that ConfigurationSection also calls into this internal method and should use ReferenceCountedProviders when paired with ConfigurationManager.

Ah, I missed this. Good point. Thanks for clarifying.

File: src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs (hunk 12 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs]: I did this, but this made me consider how this assert (like all the others) isn't truly invariant if the ConfigurationManager is used after it's disposed. This indicates a bug in the code using the ConfigurationManager, but it would be fairly benign in most cases today. How do we feel about `Debug.Assert`s that are only valid of the API is used correctly? To me it feels like it's not invariant enough.

We could prevent this by preemptively throwing an ODE from `ReferenceCountedProviderManager.GetReference()` after it's disposed, but this might break existing apps that are today able to continue to read configuration after disposing a ConfigurationManager (or a ConfigurationRoot for that matter). I think disposing providers multiple times is the lesser evil.

We could also just start using a `ReferenceCountedProviders` instance that no longer reference counts after the ConfigurationManager is disposed. This way the `Debug.Assert`s are truly invariant and we only need to throw ODEs if something tries to change configuration sources after disposing the ConfigurationManager. I experimented with this [here](https://github.com/dotnet/runtime/compare/halter73/61747...halter73/61747-invariant?expand=1). I'm not sure if it's worth the complexity or not.

**Comment by halter73** [comment]
@eerhardt I requested another review because of https://github.com/dotnet/runtime/pull/62209#discussion_r767069415. All of the interesting changes are in the [latest commit](https://github.com/dotnet/runtime/pull/62209/commits/30b1c3602c38b427235e071d2b42133c69bfdc9e).

File: src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs (hunk 12 above)
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs]: > How do we feel about Debug.Asserts that are only valid of the API is used correctly? To me it feels like it's not invariant enough.

My thinking is that if a `Debug.Assert` can be made to fail using public APIs, then it really shouldn't be a `Debug.Assert`. @stephentoub might have a different opinion though...

For this case, if this was the first time we were shipping this type, I'd vote for throwing `ODE` if you used the object after you disposed of it. It seems like the "right" behavior to me. But I understand if we are concerned with breaking working applications.

If we choose to not throw ODE, then I think your latest commit makes the most sense from a behavior perspective at the cost of a bit of added complexity.

Comment (stephentoub) [reply src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs]: > My thinking is that if a Debug.Assert can be made to fail using public APIs, then it really shouldn't be a Debug.Assert.

That is my stance as well.  Debug.Assert/Fail should only be used for things that should _never_ be able to happen; if you can trigger one, it's either a bug in the implementation or a faulty assert.

**Comment by eerhardt** [comment]
@halter73 - is this ready for final review? If so I can take a look.

**Comment by halter73** [comment]
Thanks! I just added a test to the PR to verify the ODE changes. This is ready for final review. You should have seen everything before [`c785706` (#62209)](https://github.com/dotnet/runtime/pull/62209/commits/c785706aacb4a6ed3fcc219222518bd0e946cb4e) already.

File: src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs [hunk 20]
```diff
@@ -0,0 +1,86 @@
...
+            ReferenceCountedProviders oldRefCountedProviders = _refCountedProviders;
+
+            lock (_replaceProvidersLock)
+            {
+                _disposed = true;
+
+                // Create a non-reference-counting ReferenceCountedProviders instance now that the ConfigurationManager is disposed.
+                // We could preemptively throw an ODE from ReferenceCountedProviderManager.GetReference() instead, but this might
+                // break existing apps that were previously able to continue to read configuration after disposing an ConfigurationManager.
+                _refCountedProviders = ReferenceCountedProviders.CreateDisposed(oldRefCountedProviders.Providers);
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs:80]: Is it reasonable to delay this allocation? That way in a "normal" app that doesn't access a disposed ConfigurationManager, we don't need to allocate this one extra object.

If it is too much complexity, I'd be OK with leaving it as-is. Just needed to ask the question.

**Review by eerhardt — APPROVED** [review]
Looks good to me. I just had one question.

File: src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs (hunk 20 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.Configuration/src/ReferenceCountedProvidersManager.cs]: I updated it to return a new instance every time a disposed ConfigurationManager is accessed. We could cache it, but I don't think it's worth even a little extra complexity to optimize the scenario.

**Review by eerhardt — APPROVED** [review]
