### PR TITLE
Fix for bug #53520, Entry point not found

### LINKED ISSUE #53520: net6.0 preview 4 "Entry point was not found." exception when PublishReadyToRun with old Newtonsoft.Json 9.0.1
### Description

Using an older version of `Newtonsoft.Json` `9.0.1` results in an "Entry point was not found." exception after a `PublishReadyToRun` publish.
With the latest version `13.0.1` of `Newtonsoft.Json` it works correctly or when `PublishReadyToRun` is `false`.

### Configuration

* Which version of .NET is the code running on? `6.0.100-preview.4.21255.9` (I also tried out the daily `6.0.100-preview.6.21301.1` build which resulted in the same exception)
* What OS and version, and what distro if applicable? `win`
* What is the architecture (x64, x86, ARM, ARM64)?  `x64`
* Do you know whether it is specific to that configuration? no

### Regression?

Yes, with net6.0 preview 3 this worked.

### Other information

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Platform>x64</Platform>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows10.0.19041</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <SelfContained>true</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
  </ItemGroup>

</Project>
````

Program.cs
```c#
using System;

namespace EntryPointNotFound
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Newtonsoft.Json.Linq.JToken token = Newtonsoft.Json.Linq.JToken.Parse("{}");
                var result = token.ToObject<object>();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message + Environment.NewLine + ex.StackTrace);
            }
            Console.Read();
        }
    }
}
```

Publish with: `dotnet publish -c Release`

Console output when running the published exe:
```
Entry point was not found.
   at System.Collections.Generic.IEnumerable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) in System.Private.CoreLib.dll:token 0x60065c5+0x5c
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetFields(Type targetType, BindingFlags bindingAttr) in Newtonsoft.Json.dll:token 0x6000431+0x0
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetFieldsAndProperties(Type type, BindingFlags bindingAttr) in Newtonsoft.Json.dll:token 0x6000428+0x0
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetSerializableMembers(Type objectType) in Newtonsoft.Json.dll:token 0x60004b0+0xa
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization) in Newtonsoft.Json.dll:token 0x60004cc+0x0
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType) in Newtonsoft.Json.dll:token 0x60004b2+0xe
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType) in Newtonsoft.Json.dll:token 0x60004c7+0xc9
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type) in Newtonsoft.Json.dll:token 0x60004af+0x38
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in Newtonsoft.Json.dll:token 0x60005df+0xe
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in Newtonsoft.Json.dll:token 0x6000152+0x45
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer) in Newtonsoft.Json.dll:token 0x600093e+0x11
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType) in Newtonsoft.Json.dll:token 0x600093c+0x2c8
   at Newtonsoft.Json.Linq.JToken.ToObject[T]() in Newtonsoft.Json.dll:token 0x600093b+0x0
   at EntryPointNotFound.Program.Main(String[] args) in C:\Users\xxx\source\repos\EntryPointNotFound\EntryPointNotFound\Program.cs:line 11
```

Reference https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/1284

### PR DESCRIPTION
**Pull request by trylek**
Manish investigated this issue and he found out that the problem
is caused by the fact that in the method

Newtonsoft.Json.Utilities.ReflectionUtils.GetFields

Crossgen2 produces a NewObject fixup for the incorrect type

System.Collections.Generic.List`1<System.Type>

instead of the right type

System.Collections.Generic.List`1<System.Reflection.MemberInfo>

This was caused by a bug in the token harvesting logic; at some
point resolveToken was asked to resolve the token 0x0A02BA,

string [System.Runtime/*23000001*/]System.Type/*01000019*/::get_Name() /* 0A0002BA */

As part of the token harvesting logic we looked at the
MethodReference.Parent (01000019) and stored it in the harvesting
table along with the OwningType of the method. The problem is
that the translation of the MemberReference to MethodDesc
resolves the method on a base class,

string [System.Reflection/*23000009*/]System.Reflection.MemberInfo/*01000076*/::get_Name() /* 0A0002B5 */

As a result we were storing the incorrect [token - type] pair
[01000019 - System.Reflection.MemberInfo] into the type token
translation table and that confused the signature encoder because
01000019 is System.Type.

The trivial solution is to separately translate the memberref
parent entity handle to the owning type entity instead than
extracting it from the MethodDesc. I have verified using R2RDump
that I now see the correct NewObject fixup getting generated
in the method.

Thanks

Tomas

Fixes: #53520 
/cc @dotnet/crossgen-contrib

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]

**Comment by mangod9** [comment]
Do we know why this isnt hit for later versions of newtonsoft? The affected method doesnt seem to have changed.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs [hunk 1]
```diff
@@ -139,7 +139,11 @@ public void AddModuleTokenForMethod(MethodDesc method, ModuleToken token)
             {
                 MemberReference memberRef = token.MetadataReader.GetMemberReference((MemberReferenceHandle)token.Handle);
                 EntityHandle owningTypeHandle = memberRef.Parent;
-                AddModuleTokenForType(method.OwningType, new ModuleToken(token.Module, owningTypeHandle));
+                object owningType = token.Module.GetObject(owningTypeHandle, NotFoundBehavior.ReturnNull);
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs:142]: Is `NotFoundBehavior.ReturnNull` correct here? 

When we run into missing depedencies during compilation, we should leave holes in the image. We should not generate broken code. I suspect that `NotFoundBehavior.ReturnNull` will generate broken code.

Notice that there are not existing uses of `NotFoundBehavior.ReturnNull` in this file.

Comment (trylek) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Good point, thanks, fixed in 2nd commit.

**Comment by trylek** [comment]
@mangod9 - I think it can easily be an ordering issue - if we first harvest MemberInfo with the right typeref token (01000076), everything is fine. This can be easily affected by subtle changes in the IL code, it could even be non-deterministic in parallel mode.

**Comment by trylek** [comment]
Sigh, a new CG2 failure has appeared, it's hitting the test

https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Regression/JitBlue/GitHub_13822/GitHub_13822.il

I swear my outerloop run for the 46239 fix was green and so were several runs after mine, this is the last successful run:

https://dev.azure.com/dnceng/public/_build/results?buildId=1172801&view=results

This is the first run that hits the regression:

https://dev.azure.com/dnceng/public/_build/results?buildId=1172844&view=ms.vss-test-web.build-test-results-tab

I'm going to call it a day shortly; I'll take a look tomorrow what exactly is failing in the test unless someone beats me to it.

**Comment by mangod9** [comment]
Yeah I am trying to look what might have caused the issue. My CI run for the stack overflow fix was green, and I also see it in this batched run before my merge: https://dev.azure.com/dnceng/public/_build/results?buildId=1172774&view=results

**Comment by mangod9** [comment]
Also doesnt look like this is cg2 related since it fails on non-r2r runs too.

**Comment by trylek** [comment]
According to my initial local testing on Windows-x64 the regression test indeed fails when compiled with both Crossgen1 and Crossgen2 but for some reason it passes when not AOT-compiled.

**Comment by mangod9** [comment]
I cant repro without R2R as well, but wonder how is it failing in the non-r2r CI runs though? Adding @kunalspathak since it started failing as part of Batched CI run here: https://dev.azure.com/dnceng/public/_build/results?buildId=1172774&view=results. The run after this was possibly green since it just missed picking up the change?

**Comment by mangod9** [comment]
Yeah looks to be related to that change. I have created an issue for that: https://github.com/dotnet/runtime/issues/53781. So you can merge if other tests are looking good.

**Comment by trylek** [comment]
Thanks Manish for root-causing the issue. Indeed all the outerloop failures in my run are hitting just this one test so I'm merging this in.
