### PR TITLE
[wasm][coreclr] Improve method portable entrypoints lifecycle

### LINKED ISSUE #123712: [browser][coreCLR] GC/Finalizer is corrupting memory
```
  info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.JSImportTest.JSImportDateTime(value: 2026-01-28T11:33:18.5980000Z)
  info: ASSERT FAILED
  info:         Expression: portableEntryPoint->HasNativeCode()
  info:         Location:   D:/runtime/src/coreclr/vm/precode_portable.cpp:35
  info:         Function:   GetActualCode
  info:         Process:    42
  info: Frame (InterpreterFrame): 0x4fff2c
  info:    0) InvokeFunc_ObjSpanArgs::IL_STUB_DelegateShuffleThunk, IR_0018
  info:    1) System.Reflection.MethodBaseInvoker::InvokeWithOneArg, IR_00ff
  info:    2) System.Reflection.RuntimeMethodInfo::Invoke, IR_00cb
  info:    3) System.Reflection.MethodBase::Invoke, IR_0018
  info:    4) Xunit.Sdk.TestInvoker`1[__Canon]::CallTestMethod, IR_0019
```

```
(char*)pParam->pMD->m_pszDebugMethodName
'InvokeStub_JavaScriptTestHelper.__Wrapper_AwaitTaskOfObject_1736242449'
```

```
(char*)pParam->pMD->m_pszDebugMethodName
'InvokeStub_EventSourceAttribute.set_Name'
```

### PR DESCRIPTION
**Pull request by radekdoulik**
- Reset the portable entrypoint in places where we clear the interpreter code pointer. To avoid having stale portable entrypoint set to a method without interpreter code pointer.

- Re-enable running of finalizers

This was happening when dynamic method was finalized and added back to free list. Later when `Reset()` was called on that method, the portable entrypoint had still data from previous cycle, with dangling pointer to the interpreter code.

I also added call to reset portable entry point in other places, where we clear the interpreter code pointer to avoid similar issues.

Fixes https://github.com/dotnet/runtime/issues/123712

### CODE REVIEW

File: src/coreclr/vm/method.cpp [hunk 1]
```diff
@@ -2490,7 +2502,9 @@ void MethodDesc::Reset()
     // Reset any flags relevant to the old code
     ClearFlagsOnUpdate();
 
-#ifndef FEATURE_PORTABLE_ENTRYPOINTS
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+    ResetPortableEntryPoint();
+#else // !FEATURE_PORTABLE_ENTRYPOINTS
     _ASSERTE(HasPrecode());
     GetPrecode()->Reset();
 #endif // !FEATURE_PORTABLE_ENTRYPOINTS
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/method.cpp]:
```suggestion
#endif // FEATURE_PORTABLE_ENTRYPOINTS
```

File: src/coreclr/vm/method.cpp [hunk 2]
```diff
@@ -2474,6 +2474,18 @@ BOOL MethodDesc::ShouldCallPrestub()
 #endif // FEATURE_PORTABLE_ENTRYPOINTS
 }
 
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+void MethodDesc::ResetPortableEntryPoint()
+{
+    PCODE tempEntry = GetTemporaryEntryPointIfExists();
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/method.cpp]: If this is needed, please create a `GetPortableEntryPointIfExists()`. All these methods should be in the same block/area. Ideally this would be define after the `GetPortableEntryPoint()` in how it was defined in the header. Keeping the functions in the same order is a big benefit for searching for things in general.

File: src/coreclr/vm/method.cpp [hunk 3]
```diff
@@ -2879,6 +2881,27 @@ PCODE MethodDesc::GetPortableEntryPoint()
...
+PCODE MethodDesc::GetPortableEntryPointIfExists()
+{
+    WRAPPER_NO_CONTRACT;
+
+    // The portable entry point is currently the same as the
+    // temporary entry point.
+    return GetTemporaryEntryPointIfExists();
+}
+
+// WASM-TODO: If the portable entry point diverges from the temporary
```
Comment (jkotas) [inline src/coreclr/vm/method.cpp]: Why would it diverge?

Comment (radekdoulik) [reply src/coreclr/vm/method.cpp]: The comments in the non-temporary methods sound like this might change in future, so I wanted to make sure we don't forget to update the reset.

```
    // The portable entry point is currently the same as the
    // temporary entry point.
```

Comment (jkotas) [reply src/coreclr/vm/method.cpp]: Unless we have concrete plans to change this. this should not be WASM-TODO

File: src/coreclr/vm/method.cpp [hunk 4]
```diff
@@ -2879,6 +2881,27 @@ PCODE MethodDesc::GetPortableEntryPoint()
...
+{
+    WRAPPER_NO_CONTRACT;
+
+    // The portable entry point is currently the same as the
+    // temporary entry point.
+    return GetTemporaryEntryPointIfExists();
+}
+
+// If the portable entry point diverges from the temporary
+// entry point, we may need to reset both of them.
```
Comment (jkotas) [inline src/coreclr/vm/method.cpp]:
```suggestion
```
I do not think this comment is useful. It does not explain what the code does currently.

This comment talks about what the code may need to do in theory in case fundamental invariants change. Information like that is rarely captured in comments. If it is captured, the comment needs to state that it is describing hypothetical alternative.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/method.cpp (hunk 4 above)
Comment (radekdoulik) [reply src/coreclr/vm/method.cpp]: I am curious about the methods themselves, why do we keep 2 sets of them, one set forwarding to the other. Is that to resemble the precode behavior/style?

File: src/coreclr/vm/finalizerthread.cpp [hunk 5]
```diff
@@ -58,8 +58,7 @@ extern "C" void SystemJS_ExecuteFinalizationCallback()
     INSTALL_UNHANDLED_MANAGED_EXCEPTION_TRAP;
     {
         GCX_COOP();
-        // TODO-WASM https://github.com/dotnet/runtime/issues/123712
-        // ManagedThreadBase::KickOff(FinalizerThread::FinalizerThreadWorkerIteration, NULL);
+        ManagedThreadBase::KickOff(FinalizerThread::FinalizerThreadWorkerIteration, NULL);
     }
```
[the remark this answers is not in the document]
Comment (radekdoulik) [reply src/coreclr/vm/finalizerthread.cpp:62]: I will look at that in followup PR

File: src/coreclr/vm/method.cpp (hunk 4 above)
Comment (jkotas) [reply src/coreclr/vm/method.cpp]: Consistent naming style. I do not think it is strictly required to make things work.
