### PR TITLE
Move FLS init before EventPipeAdapter::FinishInitialize and the first SetupThread()

### LINKED ISSUE #114506: Assertion failure g_flsIndex != FLS_OUT_OF_INDEXES
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1012520
Build error leg or test failing: tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.cmd
Pull request: https://github.com/dotnet/runtime/pull/114464

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "g_flsIndex != FLS_OUT_OF_INDEXES",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #114506

In the previous fix we tried to call `FinalizerThread::WaitForFinalizerThreadStart();` as late as possible in `EEStartupHelper()` - to make sure finalizer has enough time to do its part in initializing COM and FLS slot.  

But if calls that happen before `FinalizerThread::WaitForFinalizerThreadStart();` can result in `Thread` objects created and registered for OS destruction, then those threads will see `g_flsIndex != FLS_OUT_OF_INDEXES`, that includes the call to `SetupThread()`, which `EEStartupHelper()` itself does.

The change moves `FinalizerThread::WaitForFinalizerThreadStart();` earlier, before any `Threads` could be created and registered for OS destruction. 
We still have GC heap initialization happening before that, which will typically result in finalizer thread completing its part before the EE init thread needs to check for the completion.

### CODE REVIEW

**Comment by VSadov** [comment]
If I deliberately delay finalizer thread by adding `ClrSleepEx(1000, false);` at the beginning of `FinalizerThreadStart`, I can see the original failure quite often.

If I run `\tracing\tracing\tracing.cmd` in a loop 3 times, I see 16 stack traces in the output with `g_flsIndex != FLS_OUT_OF_INDEXES`. I am not sure if they may be double-reported in the output, that is still a fairly consistent repro.

**Comment by VSadov** [comment]
I think this is ready to be reviewed.

File: src/coreclr/vm/ceemain.cpp [hunk 1]
```diff
@@ -898,6 +867,43 @@ void EEStartupHelper()
...
+#ifdef TARGET_WINDOWS
+        // g_pGCHeap->Initialize() above could take nontrivial time, so by now the finalizer thread
+        // should have initialized FLS slot for thread cleanup notifications.
+        // And ensured that COM is initialized (must happen before allocating FLS slot).
+        // Make sure that this was done.
+        FinalizerThread::WaitForFinalizerThreadStart();
+#endif
+
+        // throws on error
+        SetupThread();
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:897]:
```suggestion
        _ASSERTE(GetThreadNULLOk() == NULL);
        SetupThread();
```

File: src/coreclr/vm/ceemain.cpp [hunk 2]
```diff
@@ -898,6 +867,44 @@ void EEStartupHelper()
...
+        //
+        // Install our global exception filter
+        //
+        if (!InstallUnhandledExceptionFilter())
+        {
+            IfFailGo(E_FAIL);
+        }
+
+#ifdef TARGET_WINDOWS
+        // g_pGCHeap->Initialize() above could take nontrivial time, so by now the finalizer thread
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:889]: Can we end up creating the finalizer thread too soon on non-Windows?

For example, can the finalizer `Thread` be registered in thread store before `ProfilingAPIUtility::InitializeProfiling` and miss profiler notifications that are done as part of the registration?

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:889]: If `InitializeProfiling` does not need `Thread` object for the current thread, it can be moved earlier. 

The comments inside `InitializeProfiling` say that there are asserts somewhere that finalizer thread has started. So I wonder - are there tests for profiler attach?

Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp:890]: > The comments inside InitializeProfiling say that there are asserts somewhere that finalizer thread has started.

These comments refer to the old profiler attach implementation. I am deleting them in https://github.com/dotnet/runtime/pull/115680

> So I wonder - are there tests for profiler attach?

Yes, look for "Attach" under https://github.com/dotnet/runtime/tree/main/src/tests/profiler. (The tests won't hit every subtle race condition though.)

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:890]: I've moved the profiler initializtion earlier. If it needs to attach a Thread, then it would hit an assert in `OsAttachThread`. There is an assert there to fail deterministically.

I was mostly wondering if we test scenarios beyond "profiler is not involved at all".

File: src/coreclr/vm/ceemain.cpp [hunk 3]
```diff
@@ -839,33 +839,13 @@ void EEStartupHelper()
 
 #ifdef PROFILING_SUPPORTED
         // Initialize the profiling services.
+        // THis must happen before the finalizer thread is stopped on its first wait.
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:842]: I do think this describes the required invariant accurately.

My concern is about making sure that the profilers receive [these ThreadCreated notification](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/threads.cpp#L749-L764) for the finalize or any other thread reliably. I think it means that `ProfilingAPIUtility::InitializeProfiling` is called before `SetupThread` is on any thread.

File: src/coreclr/vm/ceemain.cpp (hunk 2 above)
Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:890]: With default test set there are no failures, so based on that we could say profiler initializtion does not create/attach Thread objects.

If the profiler tests you've pointed too run in default test set, it may be good enough. If we need to run some other leg - like outer loop, perhaps makes sense to do that. Maybe makes sense to do that regardless.

File: src/coreclr/vm/ceemain.cpp (hunk 3 above)
Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp:842]: I am wondering whether it would make sense to start the profiler thread in a different place on Windows vs. non-Windows to make both cases about as optimal as possible.

Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp:842]: Start it earlier on Windows since we know we will need to wait for it and it won't run away to do other things.

Start it later on Windows once there is no problem with the finalizer thread running away to do other things.

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:842]: My main concern is that `InitializeProfiling` would not try to set up a thread, directly or indirectly. It looks like it does not.

Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:842]:
```suggestion
        // This must happen before SetupThread is called on the finalizer thread.
```

Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp:842]: InitializeProfiling looks fine with the current version of the change (except for the comment that I left feedback for). 

My suggestion is:
- Call `FinalizerThread::FinalizerThreadCreate` as one of the things in `EEStartupHelper` on Windows. It will maximize the chances that the finalizer thread is going to finish initializing COM by the time we need to wait for it.
- Call `FinalizerThread::FinalizerThreadCreate` as late as necessary on non-Windows to avoid stepping on the subtle landmines like debugger or profiler.

Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp:842]: I have realized that we would have to wait on the finalizer thread before calling HasStarted for this suggestion to work. You can ignore the suggestion. I assume that we will want to push this change to servicing so this should be a minimal fix.

The problem with debugger initialization that I have mentioned in the other comment may be real.

Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp:842]: Actually, we may need to introduce a wait like that on the finalizer thread to fix the debugger initialization problem.

File: src/coreclr/vm/ceemain.cpp [hunk 4]
```diff
@@ -839,33 +839,13 @@ void EEStartupHelper()
...
-        }
-
-        // throws on error
-        SetupThread();
-
-#ifdef DEBUGGING_SUPPORTED
-        // Notify debugger once the first thread is created to finish initialization.
-        if (g_pDebugInterface != NULL)
-        {
-            g_pDebugInterface->StartupPhase2(GetThread());
```
[the remark this answers is not in the document]
Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:865]: `SetupThread` also calls `ThreadCreated` and the EE initializing thread calls `ThreadCreated` before `StartupPhase2` is called.  

Both `SetupThread` and `HasStarted` will check for `if (CORDebuggerAttached())` before sending the notification though.

The functional part of `ThreadCreated` (apart from notifications) is to check if debugger wants threads to stop, which cannot happen if debugger is not yet officially attached.

[the remark this answers is not in the document]
Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:865]: I think there could be a race where finalizer thread checks if debugger is attached (sees that it is not) and then debugger asks threads to stop. 

There is no such race for the thread that initializes the EE.

File: src/coreclr/vm/ceemain.cpp (hunk 3 above)
Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:842]: I think next to what GC does (reserves tons of VM, creates a few threads,..), it may be ok. 
But maybe one day GC will do all that in pay-for-play fashion. Fundamentally, it does not have to do it upfront.

The alternative is to start finalizer thread later on non-windows - as you've suggested. After the debugger is fully initialized.

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp]: > Actually, we may need to introduce a wait like that on the finalizer thread to fix the debugger initialization problem.

Yes, to be sure that finalizer thread on Windows waits for debugger init we need to make it wait for EE thread to tell it what it can to proceed to `HasStarted()`

I've added that in the last change. Also in non-Windows case simply moved `FinalizerThreadCreate()` to a place after `g_pDebugInterface->StartupPhase2`

File: src/coreclr/vm/ceemain.cpp [hunk 5]
```diff
@@ -898,6 +879,48 @@ void EEStartupHelper()
...
+            g_pDebugInterface->StartupPhase2(GetThread());
+        }
+#endif
+
+#ifndef TARGET_WINDOWS
+        // This isn't done as part of InitializeGarbageCollector() above because
+        // debugger must be initialized before creating EE thread objects
+        FinalizerThread::FinalizerThreadCreate();
+#else
+        // On windows the finalizer thread is already partially created created and is waiting
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:919]:
```suggestion
        // On windows the finalizer thread is already partially created and is waiting
```

**Review by jkotas — APPROVED** [review]
LGTM. Thanks!

**Comment by VSadov** [comment]
@jkotas   Re: backporting. I think we have not seen evidence that the bug is harmful in release builds. 

Possibly it just leads to leaks of Thread objects for the event pipe thread or for the thread that initializes EE (if it quits before the rest of the app). There is a possibility of effects that are worse, but not yet seen or attributed to this issue.

It feels like there is no urgency in backporting and there is some risk that the fix may not be complete or brings up some other issue. I would suggest to at least wait couple weeks before considering backporting.

**Comment by jkotas** [comment]
Ok, sounds good.

**Comment by VSadov** [comment]
Thanks!
