### PR TITLE
Force concurrent LdapConnection in new process

### LINKED ISSUE #39009: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed. running DirectoryServices tests on Linux coreclr
Not much to go on -- 

Libraries Test Run release coreclr Linux x64 Debug
(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-helix-20200512010621-4f8cef7.

https://dev.azure.com/dnceng/public/_build/results?buildId=718537&view=logs&jobId=71afe768-e493-597c-228c-037834193aeb&j=71afe768-e493-597c-228c-037834193aeb&t=3e74a8b7-5e62-58f8-6a85-9e36ef39d1c1
```
    System.DirectoryServices.Protocols.Tests.DirectoryServicesProtocolsTests.TestAddUser [SKIP]
      Condition(s) not met: "IsLdapConfigurationExist"
dotnet: ../nptl/pthread_mutex_lock.c:79: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
./RunTests.sh: line 161:  2035 Aborted                 "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.DirectoryServices.Protocols.Tests.runtimeconfig.json --depsfile System.DirectoryServices.Protocols.Tests.deps.json xunit.console.dll System.DirectoryServices.Protocols.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
~/work/B45D097D/w/B56E0989/e
----- end Tue Jul 7 05:00:01 UTC 2020 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
Looking around for any Linux dump...
... found no dump in /home/helixbot/work/B45D097D/w/B56E0989/e
```

@davidfowl where are we at with collecting dump files? 😃

### PR DESCRIPTION
**Pull request by ericstj**
Fix #39009 
Ensure an initial non-concurrent call to OpenLDAP

OpenLDAP requires a single call for initialization before any other concurrent call.

This fixes asserts and segfaults we were seeing when calling OpenLDAP concurrently.

### CODE REVIEW

File: src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs [hunk 1]
```diff
@@ -291,6 +293,18 @@ public void Dispose_MultipleTimes_Nop()
             connection.Dispose();
         }
 
+        [ConditionalFact(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported))]
+        public void CanCreateConcurrentConnections()
+        {
+            RemoteExecutor.Invoke(() =>
```
Comment (joperezr) [inline src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs:299]: Just so I understand you only use RemoteExecutor since you don’t want other tests to run first and instantiate it for you right?

Also even if we do this I wonder if we can get a repro fairly easily si ce it is obviously still possible for some thread to execute a bit sooner than others causing the issue not to repro

Comment (ericstj) [reply src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs:299]: > Just so I understand you only use RemoteExecutor since you don’t want other tests to run first and instantiate it for you right?

yep.

> Also even if we do this I wonder if we can get a repro fairly easily si ce it is obviously still possible for some thread to execute a bit sooner than others causing the issue not to repro

True, I'm doing this first to make sure it's good enough to repro occasionally in CI.  It's not full proof, race conditions never are.  If I can't get a repro I'll make it more agressive (running RE multiple times, for example, or spinning up multiple threads having them wait on event, then signalling).  My thinking is that if we regress here this will start crashing flakily and we'll notice it.  It should be a pretty good indicator, and better than our current crash which has taken us quite a while to track down (though we still did despite its flakiness).

Comment (joperezr) [reply src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs:299]: Seems like it didn’t repro, so we probably do need a more aggressive concurrency approach

Comment (ericstj) [reply src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs:299]: Potentially.  I've been trying locally and haven't had any success, as least in WSL.  It's possible that even the crash is more nuanced than we can reliably reproduce.  I'll try tossing up my test case into Helix and see if its any luckier than I have been in WSL.

Comment (ericstj) [reply src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs]: Frustrating, I still can't repro the crash.  The dumps we have are clear enough that show two threads in ldap_init at the same time, but I can't seem to force it.  😠

Comment (jkotas) [reply src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs]: You may need to make sure that:
- The other tests finished running so that all processors are ready to go. `Thread.Sleep(60000)` as the first thing in the test may do it.
- Use spinloop on `static volatile bool` variable to kick off all threads. It is the most precise way to get all threads going at the exact same time.

Comment (ericstj) [reply src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs]: I'll let this run finish then toss up another attempt to see if spin wait is any better.

Comment (jkotas) [reply src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs]: Hmm, I do not think that the spin wait is going to help. The threads will get blocked on JIT lock multiple times before they reach the pinvoke. Waiting a bit for the machine to be idle and/or retrying for fixed amount of time instead of fixed number of iterations may work better.

Comment (ericstj) [reply src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs]: Ok. I’ll give that a try

**Comment by ericstj** [comment]
> All checks have passed

I think I'm going to need to give up on getting this to repro in CI.  It's very rare.  I was able to get a repro in WSL locally.  Rather than calling through S.DS.P I just put the ldap_init PInvoke directly in a test program and used the same method as this test and had it run for 10,000 iterations.  I was able to hit one version of this crash:
```
dotnet: ../nptl/pthread_mutex_lock.c:79: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
./test.sh: line 1: 18048 Aborted                 (core dumped) ( dotnet /mnt/c/scratch/ds.p.linux/bin/Debug/netcoreapp3.1/ds.p.linux.dll )
```

I'm trying a few times without a fix to make sure I can repro then will try with the fix to make sure it goes away.

**Comment by joperezr** [comment]
Yeah I was going to suggest doing PInvoke directly to at least confirm this is the cause, but having that regression test would have been nice. We do a bit if work on that constructor and run several operations before that call so I do believe it will be really har ld to get consistent repro going directly from S.DS.P unfortunately.

**Comment by ericstj** [comment]
So without the fix I hit this about 1 / 3000 times when directly invoking the PInvoke.  After the fix I don't hit it at all in 10000 iterations.  I'm running more to confirm I no longer repro.

**Comment by danmosemsft** [comment]
Probably want to minimize the diff for porting purposes

**Comment by ericstj** [comment]
> Probably want to minimize the diff for porting purposes

I did specifically consider this.  The reason for the larger diff was that this library did not create a class specific to libldap.  Rather than put a static constructor on the Interop class (which could conflict with other usage) I moved all the libLdapPinvokes to their own class.  This change was done in a way that "if it compiles, it is correct" at least from the rename perspective.

I could make a smaller change in release that adds the static constructor to the "Interop"  class. at the moment this library *only* uses libldap, if you think a smaller diff is worth having the potential maintenance issue in the future.

**Comment by danmosemsft** [comment]
Ah - I see. Makes sense.

File: src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs [hunk 2]
```diff
@@ -3,8 +3,12 @@
 
 using System.Collections.Generic;
 using System.ComponentModel;
+using System.Diagnostics;
```
Comment (jkotas) [inline src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs:6]: Undo changes in this file?

File: src/libraries/System.DirectoryServices.Protocols/tests/System.DirectoryServices.Protocols.Tests.csproj [hunk 3]
```diff
@@ -1,6 +1,7 @@
 <Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
     <TargetFrameworks>$(NetCoreAppCurrent)-Windows_NT;$(NetCoreAppCurrent)-Linux;$(NetCoreAppCurrent)-OSX;net48</TargetFrameworks>
+    <IncludeRemoteExecutor>true</IncludeRemoteExecutor>
```
Comment (jkotas) [inline src/libraries/System.DirectoryServices.Protocols/tests/System.DirectoryServices.Protocols.Tests.csproj:4]: Undo?

**Review by jkotas — APPROVED** [review]

**Comment by joperezr** [comment]
While I'm fine with the change proposed here, another option if we want to minimize the changes and still not add a static constructor to Interop class would be to move the static constructor one level up to LdapConnection class right? This is the primary one that interacts with libldap anyway.

File: src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs [hunk 4]
```diff
@@ -61,141 +61,158 @@ internal enum SaslChallengeType
...
+    {
+        static Ldap()
+        {
+            // OpenLdap must be initialized on a single thread, once this is done it allows concurrent calls
+            // By doing so in the static constructor we guarantee this is run before any other methods are called.
+
+            // we call ldap_get_option_int to get an option and trigger the initialization as reccomended by
+            // https://www.openldap.org/software//man.cgi?query=ldap_init
+            int unused = 0;
+            ldap_get_option_int(IntPtr.Zero, LdapOption.LDAP_OPT_DEBUG_LEVEL, ref unused);
```
Comment (joperezr) [inline src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs:74]: Just one note here, at least in Linux native library will fail the call when the option isn't recognized, so we could either add a try catch here in case it isn't, or alternatively either confirm debug level is present on all implementations or use another option we know will like protocol version

File: src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs [hunk 5]
```diff
@@ -61,141 +61,158 @@ internal enum SaslChallengeType
...
 
-    [DllImport(Libraries.OpenLdap, EntryPoint = "ldap_get_option", CharSet = CharSet.Ansi)]
-    public static extern int ldap_get_option_sechandle([In] ConnectionHandle ldapHandle, [In] LdapOption option, ref SecurityHandle outValue);
+        [DllImport(Libraries.OpenLdap, EntryPoint = "ldap_get_option", CharSet = CharSet.Ansi)]
+        public static extern int ldap_get_option_sechandle([In] ConnectionHandle ldapHandle, [In] LdapOption option, ref SecurityHandle outValue);
 
-    [DllImport(Libraries.OpenLdap, EntryPoint = "ldap_get_option", CharSet = CharSet.Ansi)]
-    public static extern int ldap_get_option_int([In] ConnectionHandle ldapHandle, [In] LdapOption option, ref int outValue);
+        [DllImport(Libraries.OpenLdap, EntryPoint = "ldap_get_option", CharSet = CharSet.Ansi)]
+        private static extern int ldap_get_option_int([In] IntPtr ldapHandle, [In] LdapOption option, ref int outValue);
```
Comment (joperezr) [inline src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs:96]: We already have a public ldap_get_option_int, why not just use that one?

**Review by joperezr — APPROVED** [review]
Left a few comments but looks good! Thanks so much for fixing!

File: src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs (hunk 5 above)
Comment (joperezr) [reply src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs:96]: Oh I see, you do that cause you pass in IntPtr.Zero instead of a ConnectionHandle

Comment (ericstj) [reply src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs:96]: Because it doesn't take Null for handle.  It takes ConnectionHandle which itself cannot have a IntPtr.Zero handle.

File: src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs (hunk 4 above)
Comment (ericstj) [reply src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs:74]: I chose an option that did not require a handle nor any allocation.  It appears to me that this option is present everywhere: https://github.com/openldap/openldap/blob/b06f5b0493937fc28f2cc86df1d7f464aa4504d8/libraries/libldap/options.c#L366

**Comment by ericstj** [comment]
So 150K iterations after fix and no-repro after seeing about once every 3K before locally.  I think this fixed it.   Will merge in master and open RC2 port.  Will test more in RC2.
