### PR TITLE
X86 Debug Stack offsets are encoded divided by 4

### LINKED ISSUE #57951: Debugger incorrectly resolves argument in MethodImplOptions.NoOptimization frame in Windows x86
### Description

The VS Debugger attempts to scraps the 'tasks' array from the [System.Private.CoreLib.dll!System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[] tasks)](https://github.com/dotnet/runtime/blob/8ddb6335236416562dca5e00eddc812d1d0f3340/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L4591) frame of the call stack in order to understand wait relationships. This method is marked with `MethodImplOptions.NoOptimization` in order to make this possible. But something changed in either preview 5 or preview 6 so that this no longer works in x86 Windows.

### Configuration

* Which version of .NET is the code running on? 6.0 preview 7
* What OS and version, and what distro if applicable? Windows 10
* What is the architecture (x64, x86, ARM, ARM64)? x86
* Do you know whether it is specific to that configuration? Yes

### Regression?

Yes

### Other information

This issue reproduces both with live debugging and a dump. I have a dump available if any Microsoft employee would like it.

From the dump, here is the stack memory for the WaitAll frame:

| VFrame relative address | Address | Value | Notes |
| -------------------------- | --------- | ------ | ------ |
| $vframe-16 | 0x02FBEF78 | 7b5ce584 | Where ICorDebug tells us `args` is |
| $vframe-12  | 0x02FBEF7C | 00000000 | |
| $vframe-8 | 0x02FBEF80 | 00000000 | |
| $vframe-4 | 0x02FBEF84 | 05550778 | Where `args` actually is |
| $vframe | 0x02FBEF88 | 02fbefa8 | Saved EBP |
| $vframe+4 | 0x02FBEF8C | 08992e81 | Return address |

Disassembly:
```
        public static void WaitAll(params Task[] tasks)
        {
            WaitAllCore(tasks, Timeout.Infinite, default);
7B5CE560  push        ebp  
7B5CE561  mov         ebp,esp  
7B5CE563  sub         esp,8  
7B5CE566  xor         eax,eax  
7B5CE568  mov         dword ptr [ebp-8],eax  
7B5CE56B  mov         dword ptr [ebp-4],ecx  <- Storing args in [$vframe - 4]
7B5CE56E  xor         ecx,ecx  
7B5CE570  mov         dword ptr [ebp-8],ecx  
7B5CE573  push        dword ptr [ebp-8]  
7B5CE576  mov         ecx,dword ptr [ebp-4]  
7B5CE579  mov         edx,0FFFFFFFFh  
7B5CE57E  call        dword ptr [Pointer to: CLRStub[MethodCallThunk]@92b7b12c7b7a3d20 (7BC53DDCh)]  
7B5CE584  mov         esp,ebp  
7B5CE586  pop         ebp  
7B5CE587  ret  
```

### Repro steps

1. Create a new .NET 6 console project.
2. Open the project file and add `<RuntimeIdentifier>win7-x86</RuntimeIdentifier>`
3. Add the following source code
4. Launch the project under the debugger
5. After the program is running Debug->Break
6. Switch to the Task.WaitAll frame
7. Switch to the locals window and attempt to evaluate `tasks`

Result:
| Name | Value | Type |
| -- | -- | -- |
| tasks | Unable to read memory | System.Threading.Tasks.Task[] |

```C#
class Program
{
    static private async Task<int> SlowNumber()
    {
        // Wait for 20 seconds.
        await Task.Delay(20000);
        return 12;
    }

    public static void Main(string[] args)
    {
        Task t1 = SlowNumber();
        Task t2 = SlowNumber();
        Task.WaitAll(t1, t2);
    }
}
```

### PR DESCRIPTION
**Pull request by davidwrighton**
- Fix the encoding

Fixes #57951

### CODE REVIEW

**Review by AndyAyersMS — APPROVED** [review]
Seems like that should do the trick.

Can you verify the new R2R debug info for x86 `Task.WaitAll` looks right?

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugInfoTableNode.cs [hunk 1]
```diff
@@ -206,6 +209,19 @@ public static byte[] CreateVarBlobForMethod(NativeVarInfo[] varInfos)
                     default:
                         throw new BadImageFormatException("Unexpected var loc type");
                 }
+
+                static void WriteEncodedStackOffset(NibbleWriter _writer, int offset, bool assume4ByteAligned)
```
Comment (trylek) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugInfoTableNode.cs:213]: Nit - if at some point we considered expanding this behavior to other architectures, the name of the argument (<code>assume4ByteAligned</code>) would probably need to change to e.g. something like <code>encodeUsingPointerSizeUnits</code> or some such. If we believe this to be limited to X86 forever, it's probably OK.

**Review by trylek — APPROVED** [review]
LGTM, thanks David for fixing this so quickly!

**Comment by davidwrighton** [comment]
@AndyAyersMS  Yep. Verified the WaitAll behavior, and it looks good.

```
void System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[])
Handle: 0x060032D8
Rid: 13016
EntryPointRuntimeFunctionId: 10598
Number of RuntimeFunctions: 1
Number of fixups: 1
    TableIndex 4, Offset 0380: System.Threading.CancellationToken (TYPE_HANDLE)

void System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[])
Id: 10598
StartAddress: 0x002743C0
Size: 40 bytes
UnwindRVA: 0x000425B0

Debug Info
    Bounds:
    Native Offset: 0x0, Prolog, Source Types: StackEmpty
    Native Offset: 0xE, IL Offset: 0x0000, Source Types: StackEmpty
    Native Offset: 0x24, IL Offset: 0x0011, Source Types: StackEmpty
    Native Offset: 0x24, Epilog, Source Types: StackEmpty

    Variable Locations:
    Variable Number: 0
    Start Offset: 0x0
    End Offset: 0xE
    Loc Type: VLT_REG
    Register: ECX

    Variable Number: 0
    Start Offset: 0xE
    End Offset: 0x24
    Loc Type: VLT_STK
    Base Register: EBP
    Stack Offset: -4

    Variable Number: 1
    Start Offset: 0xE
    End Offset: 0x24
    Loc Type: VLT_STK
    Base Register: EBP
    Stack Offset: -8
```

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugInfoTableNode.cs (hunk 1 above)
Comment (davidwrighton) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugInfoTableNode.cs:213]: I just checked to see how valuable this really is, and we could save something like 0.08% of System.Private.CoreLib.dll size if we applied a similar size optimization on X64. I don't see that as worthwhile given the complexity it would impose on the reader in the runtime.
