### PR TITLE
Report invalid global.json state in `dotnet --info` and `hostfxr_resolve_sdk2`

### LINKED ISSUE #94496: dotnet --version completes with exit code 0 when global.json is malformed
### Describe the bug
`dotnet --version` completes fine even when `global.json` is malformed JSON.

### To Reproduce
Make `global.json` malformed and execute `dotnet --version`.

### Exceptions (if any)
Should exit with non-zero exit code. Instead:

```
$ dotnet --version
A JSON parsing exception occurred in [/Users/matt/code/nuke/external/functions/global.json], offset 36 (line 3, column 24): Invalid encoding in string.
6.0.100

$ echo $?
0
```

### Further technical details
MacOS

### PR DESCRIPTION
**Pull request by elinor-fung**
We currently ignore invalid global.json, which can lead to unexpected/undesired behaviour. While we're not going to change that behaviour right now, this change adds some indication about this situation in `dotnet --info` and updates a `hostfxr` API to indicate if an invalid global.json was found.

- Make `sdk_resolver` track/store information about global.json even when it is deemed invalid
- Update `dotnet --info` to list invalid global.json file path and error message
- Add `hostfxr_resolve_sdk2_result_key_t::global_json_state` for `hostfxr_resolve_sdk2` API
  - string values of: `not_found`, `valid`, `invalid_json`, `invalid_data`
  - This can be used in the SDK to add telemetry for when we have invalid global.json

Example part of `dotnet --info`:
```
global.json file:
  Invalid [C:\repos\helloworld\global.json]
    Version '9.0' is not valid for the 'sdk/version' value
    Invalid global.json is ignored for SDK resolution.
```
Before:
```
global.json file:
  Not found
```

cc @dotnet/appmodel @AaronRobinsonMSFT @richlander 

Resolves https://github.com/dotnet/runtime/issues/94496

Related:
- https://github.com/dotnet/sdk/issues/50058
- https://github.com/dotnet/runtime/issues/96299
- https://github.com/dotnet/sdk/issues/49816

### CODE REVIEW

File: src/native/corehost/fxr/sdk_resolver.cpp [hunk 1]
```diff
@@ -353,18 +362,14 @@ bool sdk_resolver::parse_global_file(pal::string_t global_file_path)
     {
         if (!version_value->value.IsString())
         {
-            trace::warning(_X("Expected a string for the 'sdk/version' value in [%s]"), global_file_path.c_str());
-            return false;
+            ret.error_message = _X("Expected a string for the 'sdk/version' value");
+            return ret;
         }
 
         if (!fx_ver_t::parse(version_value->value.GetString(), &requested_version, false))
```
[the remark this answers is not in the document]
Comment (elinor-fung) [reply src/native/corehost/fxr/sdk_resolver.cpp:377]: This is not true. It is a member variable.

File: src/native/corehost/fxr/sdk_resolver.cpp [hunk 2]
```diff
@@ -237,14 +225,27 @@ sdk_resolver sdk_resolver::from_nearest_global_file(const pal::string_t& cwd, bo
...
-        trace::warning(
-            _X("Ignoring SDK settings in global.json: the latest installed .NET SDK (%s prereleases) will be used"),
-            resolver.allow_prerelease ? _X("including") : _X("excluding"));
+            trace::verbose(_X("Invalid global.json [%s]:\n  %s"), global_file.path.c_str(), global_file.error_message.c_str());
+            trace::warning(
+                _X("Ignoring SDK settings in global.json: the latest installed .NET SDK (%s prereleases) will be used"),
+                resolver.allow_prerelease ? _X("including") : _X("excluding"));
+        }
+
+        resolver.global_json = std::move(global_file);
```
Comment (AaronRobinsonMSFT) [inline src/native/corehost/fxr/sdk_resolver.cpp:256]: This is unintuitive to me. We replace `resolver` above, but still set the `global_file` on the replaced version? Can I assume the `global_json` file is checked for validity in future locations?

Comment (elinor-fung) [reply src/native/corehost/fxr/sdk_resolver.cpp:256]: > We replace `resolver` above, but still set the `global_file` on the replaced version?

Yes. We are now tracking even invalid global.json, so the `global_file` encompasses the path, state, and any error message.

> Can I assume the `global_json` file is checked for validity in future locations?

We check the `state` when determining whether to invoke the callback in `hostfxr_resolve_sdk2` and when determining what to print in `dotnet --info`. Other than than, we don't use the global.json after the `sdk_resolver` is created.

File: src/installer/tests/HostActivation.Tests/HostCommands.cs [hunk 3]
```diff
@@ -168,6 +169,42 @@ public void Info_ListEnvironment_LegacyPrefixDetection()
...
+                    .And.HaveStdOutContaining($"Invalid [{globalJsonPath}]")
+                    .And.HaveStdOutContaining("JSON parsing exception:")
+                    .And.NotHaveStdErr();
+            }
+        }
+
+        [Theory]
+        [InlineData("9.0")]
+        [InlineData("invalid")]
+        public void Info_GlobalJson_InvalidData(string version)
```
Comment (Frulfump) [inline src/installer/tests/HostActivation.Tests/HostCommands.cs:194]: Can we augment with `9.0.x` and `9.0.0` as explicit invalid values to make sure those cases are covered as well?
Ref `9.0.x`: https://github.com/dotnet/sdk/issues/49816
Ref `9.0.0` https://github.com/microsoft/azure-pipelines-tasks/issues/19292#issuecomment-3088581817 & https://github.com/dotnet/sdk/issues/49816#issuecomment-3088594741
(maybe `9` should be added to really cover any permutation in the same vein?)

File: src/native/corehost/fxr/sdk_resolver.cpp [hunk 4]
```diff
@@ -380,33 +385,37 @@ bool sdk_resolver::parse_global_file(pal::string_t global_file_path)
...
-            );
-            return false;
+            ret.error_message = utils::format_string(_X("The roll-forward policy '%s' requires a 'sdk/version' value"), roll_forward_value->value.GetString());
+            return ret;
         }
     }
 
+    // SDK feature bands start at 1, so setting version with a feature band < 1 and not rolling forward on feature band will always
+    // fail when trying to resolve the SDK. We want to provide an error message, but we should not fall back to the default resolver.
+    if (!requested_version.is_empty() && requested_version.get_patch() < 100
```
Comment (AaronRobinsonMSFT) [inline src/native/corehost/fxr/sdk_resolver.cpp]: This `100` could use a comment. I see the "start at 1", but assume that isn't a typo and is instead talking about something else.

Comment (elinor-fung) [reply src/native/corehost/fxr/sdk_resolver.cpp]: Pulled out into a `get_feature_band` helper.

File: src/installer/tests/HostActivation.Tests/HostCommands.cs (hunk 3 above)
Comment (elinor-fung) [reply src/installer/tests/HostActivation.Tests/HostCommands.cs:194]: Added `9` and `9.0.x` here. Added a slight separate case for `9.0.0` - unlike the other invalid cases, we don't (and shouldn't) ignore it, but it will never work at run time without roll-forward, so we should still report an error message in `--info` (unlike the valid cases).

File: src/native/corehost/hostmisc/utils.h [hunk 5]
```diff
@@ -69,6 +69,15 @@ namespace utils
...
         return starts_with(value, prefix, L - 1, match_case);
     }
+
+    template <typename... Args>
+    pal::string_t format_string(const pal::char_t* format, Args&&... args)
+    {
+        int len = pal::strlen_printf(format, std::forward<Args>(args)...) + 1;
+        std::vector<pal::char_t> buffer(len);
+        pal::str_printf(&buffer[0], len, format, std::forward<Args>(args)...);
+        return pal::string_t(buffer.data(), len - 1);
```
Comment (AaronRobinsonMSFT) [inline src/native/corehost/hostmisc/utils.h]: Nit: normally I would expect this to be `buffer.data(), buffer.size() - 1`.

Comment (elinor-fung) [reply src/native/corehost/hostmisc/utils.h]:
```suggestion
        return pal::string_t(buffer.data(), buffer.size() - 1);
```

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/installer/tests/HostActivation.Tests/HostCommands.cs (hunk 3 above)
Comment (Frulfump) [reply src/installer/tests/HostActivation.Tests/HostCommands.cs:194]: But 9.0.0 itself isn't a valid `version` string.

>Doesn't have wildcard support; that is, you must specify the full version number.

It's essentially a wild card in this case and that's not supported https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#version

And doesn't constitute a full version number since an SDK version will never have the `0` in the feature band part.
 https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#versioning feature bands start at 1 and always increases. I think it would be good to teach users to use a valid .NET SDK version string in the version field as it will lead to confusion otherwise irrespective of `rollForward` or not.

Comment (elinor-fung) [reply src/installer/tests/HostActivation.Tests/HostCommands.cs:194]: That is a good read of how that doc statement applies to something like 9.0.0. We still don't (and shouldn't) ignore it, but I updated to make `--info` indicate any feature band < 1 as invalid.
