### PR TITLE
Fix 48403 - Assertion failed 'call->gtControlExpr == nullptr' 

### LINKED ISSUE #48403: Assertion failed 'call->gtControlExpr == nullptr' in 'System.Text.Json.JsonParameterInfo`1[Nullable`1]
Seeing below failures in libraries-jitstressregs on Linux arm64/Windows arm64/Linux x64. It got introduced in https://github.com/dotnet/runtime/pull/47808

```
Assert failure(PID 135 [0x00000087], Thread: 147 [0x0093]): Assertion failed 'call->gtControlExpr == nullptr' in 'System.Text.Json.JsonParameterInfo`1[Nullable`1][System.Nullable`1[System.UInt64]]:Initialize(System.Type,System.Reflection.ParameterInfo,System.Text.Json.JsonPropertyInfo,System.Text.Json.JsonSerializerOptions):this' during 'Morph - Global' (IL size 101)

    File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 9192
    Image: /root/helix/work/correlation/dotnet
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47307-head-5275d70d52b544f981/System.Text.Json.Tests/console.ebed8485.log?sv=2019-07-07&se=2021-03-09T08%3A58%3A31Z&sr=c&sp=rl&sig=fuZORDqaA2Hwbji7AAwR%2B%2FwqptUnkEdVbpom5xH94xs%3D

### PR DESCRIPTION
**Pull request by briansull**
In method `fgMorphCopyBlock` don't call `gtCloneExpr` on the `addrSpill`
We also don't call `fgMorphTree` on the `addrSpill` tree as well

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -8128,9 +8129,21 @@ GenTreeCall* Compiler::gtCloneExprCallHelper(GenTreeCall* tree, unsigned addFlag
...
-    copy->gtReturnType  = tree->gtReturnType;
-    copy->gtControlExpr = gtCloneExpr(tree->gtControlExpr, addFlags, deepVarNum, deepVarVal);
+    copy->gtCallType   = tree->gtCallType;
+    copy->gtReturnType = tree->gtReturnType;
+
+    // Are we in fgGlobalMorph and did we just expand this virtual method call target early?
+    //
+    if (fgGlobalMorph && tree->IsExpandedEarly() && tree->IsVirtualVtable())
+    {
+        // The 'copy' node will create its own expanded sequence when we morph this cloned node
```
Comment (AndyAyersMS) [inline src/coreclr/jit/gentree.cpp:8139]: Presumably `gtControlExpr` is `nullptr` here? Could we check for that instead?

**Review by AndyAyersMS — COMMENTED** [review]
The morph changes seem unrelated to fixing the assert. Should they be PR'd separately?

File: src/coreclr/jit/gentree.cpp (hunk 1 above)
Comment (briansull) [reply src/coreclr/jit/gentree.cpp:8139]: This method gets called from  fgMorphCopyBlock (and several other places)

And when called from fgMorphCopyBlock the gtControlExpr has already been expanded as we start from the bottom of the tree and morph upwards.  It also could be nullptr if we are planning on expanding this callsite late.

**Comment by briansull** [comment]
This is ready for checkin now.
@AndyAyersMS @sandreenko PTAL

File: src/coreclr/jit/gentree.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/gentree.cpp:8139]: I guess I don't understand why this needs to be dependent on `fgGlobalMorph` and can't simply be
```
    if (tree->gtControlExpr == nullptr)
```

Comment (briansull) [reply src/coreclr/jit/gentree.cpp:8139]: Because for some calls we want to expand Virtual Calls late in Lower and for the others we will expand them earlier during Morph. We could revisit this decision, but originally it was pretty simple to implement this way, and I wanted to be able to turn off this change and revert back to the old way to allow us to investigate any bugs that might come up due to this change.
 
By checking `(tree->gtControlExpr == nullptr)` this would match all the cases where we want to expand the call late in Lower, so instaed we always need to check `tree->IsExpandedEarly() && tree->IsVirtualVtable()`. 

Here I also have to check `fgGlobalMorph`, since morph is called multiple times when we optimize (in CSE, etc..), only during the first "global morph" phase do we want to expand the gtControlExpr.  

On these last couple of issues that I am fixing, the problem is that for some unusual code paths, we weren't calling  gtMorphTree at all while in the "global morph" phase.
Thus the `gtControlExpr` was not expanded and the call flags were set to tell Lower that it should not expand `gtControlExpr` as it should have been expanded early.

Comment (briansull) [reply src/coreclr/jit/gentree.cpp:8139]: Oh Joy,
Now when I add the call to fgMorpgTree of the cloned tree for `STRESS_CLONE_EXPR `it now fails for asmall number of methods with a  `'!"Missing flags on tree"'` assertion cause by `optAssertionProp_Ind` setting the GTF_ORDER_SIDEEFF flag and not propagating it up the tree.

This only happens for a couple of methods when JIitStress is on.

Comment (AndyAyersMS) [reply src/coreclr/jit/gentree.cpp:8139]: Sorry harp on this, but are you saying if we get here and we're in global morph and are cloning an expand early call and `gtControlExpr` is non-null, we don't clone the existing tree because we know we'll create a proper new tree shortly..?

Won't that just create a tree that's more or less identical to the one we'd get it we did clone the existing tree?

Comment (briansull) [reply src/coreclr/jit/gentree.cpp:8139]: I will investigate doing it that way.

Comment (briansull) [reply src/coreclr/jit/gentree.cpp:8139]: That is what we had previously and it causes the assert in the Issue #48403
In he field by field copy path we call fgMorphTree on a cloned tree.

I will try a different fix.

**Comment by briansull** [comment]
I have reworked this fix.
It is now a minimal fix that fixes the issue.

- In method `fgMorphCopyBlock` don't call `gtCloneExpr` on the `addrSpill`
- We also don't call `fgMorphTree` on the `addrSpill` tree as well

This is ready for checkin now.
@AndyAyersMS @sandreenko PTAL

**Review by AndyAyersMS — APPROVED** [review]
LGTM.

Thanks for reconsidering how to fix this.

**Comment by briansull** [comment]
The only failures that I see in the JitStress runs are due to
`eventpipe\eventsvalidation\ThreadPool\ThreadPool.cmd`

Which is a currently known issue:  #48727
