### PR TITLE
Fix fgRemoveUnreachableBlocks to detect all changes

### LINKED ISSUE #57061: ARM32: runtime crash inside JIT
```csharp
// Generated by Fuzzlyn v1.2 on 2021-08-07 03:24:16
// Run on .NET 6.0.0-dev on Arm Linux
// Seed: 12756399625466979010
// Reduced from 798.7 KiB to 1.5 KiB in 03:42:20
// Crashes the runtime
struct S0
{
    public bool F0;
    public bool F1;
    public uint F2;
    public short F3;
    public ulong F4;
    public S0(bool f0, bool f1, uint f2, short f3, ulong f4): this()
    {
        F0 = f0;
        F1 = f1;
        F2 = f2;
        F3 = f3;
        F4 = f4;
    }
}

class C0
{
    public C0(S0 f7, S0 f8)
    {
    }
}

class C1
{
    public S0 F1;
    public ulong F5;
}

struct S2
{
    public S2(C0 f4): this()
    {
    }
}

struct S3
{
    public uint F0;
}

class C2
{
    public C1 F3;
}

public class Program
{
    static C2 s_23;
    static C1 s_37;
    static sbyte s_56;
    static S3 s_60;
    public static void Main()
    {
        uint vr2 = default(uint);
        uint vr3;
        bool vr4 = true;
        if (!vr4)
        {
            try
            {
                System.Console.WriteLine(s_60.F0);
            }
            finally
            {
                var vr5 = new C0(new S0(false, true, 0, 0, 0), new S0(false, false, 0, 0, 0));
            }

            s_37.F5 = s_23.F3.F1.F4++;
        }

        vr4 = vr4;
        for (int vr6 = 0; vr6 < 0; vr6++)
        {
            sbyte vr8 = s_56;
            try
            {
                var vr7 = new S2(new C0(new S0(true, false, 0, 0, 0), new S0(true, true, 0, 0, 0)));
            }
            finally
            {
                vr3 = vr2;
            }

            vr3 = vr3;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
When 'removing' a BBF_DONT_REMOVE block we change it to BBJ_THROW. After
this it is possible that other blocks become unreachable, so we should
keep looking for such blocks.

In #57061 that manifested in a case where the unreachable block did not
have SSA built for it, but downstream the compiler was relying on SSA
being built.

Fix #57061

cc @dotnet/jit-ctontrib

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
No instruction diffs in x64/x86/ARM32 SPMI, but there are a few GC info diffs because we mark some functions as partially interruptible instead of fully interruptible now.

File: src/coreclr/jit/fgopt.cpp [hunk 1]
```diff
@@ -419,6 +420,9 @@ bool Compiler::fgRemoveUnreachableBlocks()
             /* Unmark the block as removed, */
             /* clear BBF_INTERNAL as well and set BBJ_IMPORTED */
 
+            // The successors may be unreachable after this change.
+            changed |= block->NumSucc() > 0;
```
Comment (EgorBo) [inline src/coreclr/jit/fgopt.cpp:424]: can it be just `hasUnreachableBlocks |= block->NumSucc() > 0;` without that additional argument? 
the `if (hasUnreachableBlocks)` block won't do anything for `BBF_DONT_REMOVE` blocks anyway

Comment (AndyAyersMS) [reply src/coreclr/jit/fgopt.cpp:424]: Seems clearer to me to keep the two separate.

**Review by AndyAyersMS — APPROVED** [review]
We should also consider ways to harden downstream code so that it does not depend on unreachable blocks being removed.

File: src/coreclr/jit/fgopt.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/fgopt.cpp:424]: I went back and forth on this, but decided to go with the extra variable since the loop below doesn't need to run unless there are actually unreachable blocks.

**Comment by jakobbotsch** [comment]
I'll merge this now and submit a separate change to harden VN/loop opts for trees that might not have had SSA built for it.
