### PR TITLE
Block inlines with different exception wrapping behavior

### LINKED ISSUE #113815: Test failure: JIT/Directed/throwbox/filter/filter.dll
**Failed in:** [runtime-coreclr jitstress-random 20250323.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=990490&view=ms.vss-test-web.build-test-results-tab&runId=26439486&resultId=122013&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress_random_2 @ osx.13.arm64.open
    - JIT/Directed/throwbox/filter/filter.dll
```

**Error message:**
```
 An object that does not derive from System.Exception has been wrapped in a RuntimeWrappedException.
```

**Stack trace:**
```
   at Program.<<Main>$>g__TestExecutor28|0_29(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Fixes #113815

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jkotas PTAL
cc @dotnet/jit-contrib

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -7890,6 +7890,25 @@ CorInfoInline CEEInfo::canInline (CORINFO_METHOD_HANDLE hCaller,
...
+    // wrapped exception behavior, and the callee has EH, we cannot inline.
+    _ASSERTE(!pCallee->IsDynamicMethod());
+    {
+        COR_ILMETHOD_DECODER header(pCallee->GetILHeader(), pCallee->GetMDImport(), NULL);
+        if (header.EHCount() > 0)
+        {
+            Module* pCalleeModule = pCallee->GetModule();
+            Module* pRootModule = pOrigCaller->GetModule();
+
+            if (pRootModule->IsRuntimeWrapExceptions() != pCalleeModule->IsRuntimeWrapExceptions())
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:7903]: These checks are catched cheap bit tests. We should do them first, and run the more expensive IL header decoder only when the modes do not match.

**Comment by jkotas** [comment]
I think we need the same check in crossgen2

**Comment by AndyAyersMS** [comment]
> I think we need the same check in crossgen2 for R2R

Would the check go into `CrossModuleInlineableUncached`?

File: src/coreclr/vm/jitinterface.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/vm/jitinterface.cpp:7903]: Also looks like there are still issues with (lack of) an IL header.

Comment (AndyAyersMS) [reply src/coreclr/vm/jitinterface.cpp:7903]: Likely I need to handle transient methods here too.

Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:7903]: I think this needs to compare method being compiled and the inlinee to deal with cases like this one correctly:

methodFromModuleA -> methodFromModuleB -> methodFromModuleBWithEH

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp:7903]: Ah, it does that already. pOrigCaller is m_pMethodBeingCompiled.

**Comment by jkotas** [comment]
> Would the check go into CrossModuleInlineableUncached?

I do not see caller and callee in CrossModuleInlineableUncached. I think it needs to be earlier.

**Comment by AndyAyersMS** [comment]
> > Would the check go into CrossModuleInlineableUncached?
> 
> I do not see caller and callee in CrossModuleInlineableUncached. I think it needs to be earlier.

@jkotas I started in on crossgen2 support, but I can't see where custom attributes on modules are  recorded, so could use some help finishing it off.

Also I think it would be better to either always return INLINE_FAIL from `canInline` or else distinguish between `INLINE_FAIL` and `INLINE_NEVER` and use the latter to short-circuit some work... at least to remember context-free decisions within the current process.

**Comment by AndyAyersMS** [comment]
@davidwrighton maybe you can give me some pointers? How do we find module attributes in crossgen2? I see support for assembly attributes but nothing for modules.

**Comment by MichalStrehovsky** [comment]
> @davidwrighton maybe you can give me some pointers? How do we find module attributes in crossgen2? I see support for assembly attributes but nothing for modules.

We don't have higher level facilities for this in crossgen2, this will have to use System.Reflection.Metadata APIs, something along the lines of:

```
var reader = rootMod.MetadataReader;
var c = reader.StringComparer;
foreach (var attr in reader.GetModuleDefinition().GetCustomAttributes())
{
    if (reader.GetAttributeNamespaceAndName(attr, out var ns, out var n))
    {
        if (c.Equals(ns, "System.Runtime.CompilerServices") && c.Equals(n, "RuntimeCompatibilityAttribute"))
        {
            var dec = reader.GetCustomAttribute(attr).DecodeValue(new CustomAttributeTypeProvider(mod));
            // Go over dec.NamedArguments and find WrapNonExceptionThrows
        }
    }
}
```

We'll probably want to cache this on EcmaModule.

**Comment by AndyAyersMS** [comment]
> > @davidwrighton maybe you can give me some pointers? How do we find module attributes in crossgen2? I see support for assembly attributes but nothing for modules.
> 
> We don't have higher level facilities for this in crossgen2, this will have to use System.Reflection.Metadata APIs, something along the lines of:
> 
> ```
> var reader = rootMod.MetadataReader;
> var c = reader.StringComparer;
> foreach (var attr in reader.GetModuleDefinition().GetCustomAttributes())
> {
>     if (reader.GetAttributeNamespaceAndName(attr, out var ns, out var n))
>     {
>         if (c.Equals(ns, "System.Runtime.CompilerServices") && c.Equals(n, "RuntimeCompatibilityAttribute"))
>         {
>             var dec = reader.GetCustomAttribute(attr).DecodeValue(new CustomAttributeTypeProvider(mod));
>             // Go over dec.NamedArguments and find WrapNonExceptionThrows
>         }
>     }
> }
> ```
> 
> We'll probably want to cache this on EcmaModule.

Thanks. By "this" do you mean "WrapNonExceptionThrows" or something more general?

**Comment by davidwrighton** [comment]
@AndyAyersMS just WrapNonExceptionThrows. We don't need this concept much, so let's not build a generalized mechanism unless we need to.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs [hunk 2]
```diff
@@ -107,9 +107,26 @@ public bool CanInline(MethodDesc caller, MethodDesc callee)
                 }
             }
 
+            EcmaModule rootModule = (root.OwningType as MetadataType)?.Module as EcmaModule;
+            EcmaModule calleeModule = (callee.OwningType as MetadataType)?.Module as EcmaModule;
+
+            // If this inline crosses module boundaries, ensure the modules agree on exception wrapping behavior.
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:113]: I think this should be directly in CorInfoImpl.cs. It is not a policy decision whether the inlining is allowed for this case. It is required for correctness, so it should not be abstracted by the policy.

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs [hunk 3]
```diff
@@ -16,6 +16,8 @@ public partial class EcmaModule : ModuleDesc
     {
         private readonly PEReader _peReader;
         protected readonly MetadataReader _metadataReader;
+        private bool _isWrapNonExceptionThrowsKnown;
+        private bool _isWrapNonExceptionThrows;
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:20]: These may need to be `volatile`.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs (hunk 2 above)
Comment (AndyAyersMS) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:113]: Ok. I can then undo some of the other changes, since the policy will no longer need to know the root method.

**Comment by AndyAyersMS** [comment]
@jkotas PTAL.

I haven't added a test case and am not sure this gets properly tested anywhere.

**Comment by AndyAyersMS** [comment]
I finally got around to testing this in crossgen, and the inline is still happening.

It looks like the attribute is actually on the assembly, not on the module?

In my C# calling assembly:
```
.assembly x
{
  .custom instance void [System.Runtime]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
  .custom instance void [System.Runtime]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                                   63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.
```

And the runtime seems to look it up on the assembly, even though it gets associated with the module...?

https://github.com/dotnet/runtime/blob/a27c3cd8ba4166eb5ff54d8283f29a5a6ac54c08/src/coreclr/vm/ceeload.cpp#L1071-L1099

**Comment by jkotas** [comment]
`Yes, it looks like it. The attribute sources say the attribute target is an assembly:

https://github.com/dotnet/runtime/blob/f7bffcb6945ee8fb28fba7d09078be3b6cc1d4b3/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeCompatibilityAttribute.cs#L9

> And the runtime seems to look it up on the assembly, even though it gets associated with the module...?

My guess is that it is a left-over from fragile NGen. Fragile NGen allowed precomputing information associated with Module structure. So in order for the attribute value to be computed at NGen time, caches like this were moved from Assembly to Module structure.

**Comment by AndyAyersMS** [comment]
If I modify my EcmaModule code to look at assembly attributes then the inline is blocked as expected. I can push that change, or would you suggest revising the whole concept to be assembly-based throughout?

**Comment by jkotas** [comment]
I think it is fine to keep it on Module. Assembly and Module are 1:1 in .NET Core.

**Comment by jkotas** [comment]
Are you going to add a test as well?

**Comment by AndyAyersMS** [comment]
> Are you going to add a test as well?

I think the existing outerloop R2R pri1 composite tests should cover this. But we may need to mark the IL method that throws in the normal runtime tests with aggressive inlining.

Let me try that in a separate PR and see if I can get it to fail.

File: src/coreclr/vm/jitinterface.cpp [hunk 4]
```diff
@@ -7890,6 +7890,68 @@ CorInfoInline CEEInfo::canInline (CORINFO_METHOD_HANDLE hCaller,
...
+                    goto exit;
+                }
+            }
+            else if (pCallee->IsIL() && pCallee->GetRVA() == 0)
+            {
+                MethodInfoHelperContext cxt{ pCallee };
+                // We will either find or create transient method details.
+                _ASSERTE(!cxt.HasTransientMethodDetails());
+
+                // IL methods with no RVA indicate there is no implementation defined in metadata.
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:7918]: This is copy&paste from `CEEInfo::getMethodInfo`. Can this be factored into a method to avoid duplicate code?

**Comment by AndyAyersMS** [comment]
> Let me try that in a separate PR and see if I can get it to fail.

I haven't been able to get the expected failure yet in CI. Not sure why yet....

**Comment by AndyAyersMS** [comment]
> > Let me try that in a separate PR and see if I can get it to fail.
> 
> I haven't been able to get the expected failure yet in CI. Not sure why yet....

Aha, the composite mode tests in R2R outerloop do not enable jit optimizations. If I enable optimization, then the composite R2R tests for Directed_3 will fail.

Seems like running these tests with optimizations enabled is desirable, since very few people will build unoptimized R2R images.

**Comment by AndyAyersMS** [comment]
Now that #114464 is merged, and I've added aggressive inlining to the IL test case, crossgen2 tests should fail on that test, if the fix doesn't work.

**Comment by AndyAyersMS** [comment]
@jkotas PTAL...

**Review by jkotas — APPROVED** [review]
Thanks!
