### PR TITLE
Do not store result of cast in IDynIntfCastable scenarios

### LINKED ISSUE #125577: .NET AOT caching IDynamicInterfaceCastable.IsInterfaceImplemented results based on type rather than instance
### Description

From what I recall, `IDynamicInterfaceCastable.IsInterfaceImplemented` is meant to be a per instance decision rather than a per type thing.  `GetInterfaceImplementation` was the one that was a per type decision.  But it seems the results of `IsInterfaceImplemented` are being cached based on type.  In the below repro, which is similar to our `IInspectable` in CsWinRT, we are seeing that if an `is` check passes for one instance of a type, it also passes for other instances even if the IDIC implementation is returning false.

This issue seems to only happen on AOT for generic interfaces.  On JIT, the expected results are observed.

### Reproduction Steps

```
   internal class Program
    {
        static void Main(string[] args)
        {
            var shapeshifter = new Shapeshifter(true);
            bool isEnumerableInt = shapeshifter is IEnumerable<int>;
            Console.WriteLine("shapeshifter is IEnumerable<int>: " + isEnumerableInt);

            var shapeshifter2 = new Shapeshifter(false);
            bool isEnumerableInt2 = shapeshifter2 is IEnumerable<int>;
            Console.WriteLine("shapeshifter2 is IEnumerable<int>: " + isEnumerableInt2);
        }
    }

    class Shapeshifter : IDynamicInterfaceCastable
    {
        private bool _result;

        public Shapeshifter(bool result)
        {
            _result = result;
        }

        public RuntimeTypeHandle GetInterfaceImplementation(RuntimeTypeHandle interfaceType) => throw new NotImplementedException();
        public bool IsInterfaceImplemented(RuntimeTypeHandle interfaceType, bool throwIfNotImplemented) => _result;
    }
```

### Expected behavior

Same as .NET 8 AOT and same as .NET 10 JIT

net8.0\publish\win-x64\ConsoleApp35.exe
shapeshifter is IEnumerable<int>: True
shapeshifter2 is IEnumerable<int>: False

### Actual behavior

net10.0\publish\win-x64\ConsoleApp35.exe
shapeshifter is IEnumerable<int>: True
shapeshifter2 is IEnumerable<int>: True

### Regression?

.NET 8, seems related to https://github.com/dotnet/runtime/pull/108328

### Known Workarounds

_No response_

### Configuration

.NET 10

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #125577

Incorrectly copied a piece of logic and comment from CoreCLR but different considerations apply here (we do have an object instance).

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks

File: src/tests/nativeaot/SmokeTests/UnitTests/Interfaces.cs [hunk 1]
```diff
@@ -2046,4 +2047,30 @@ static string Frob<T, U, V>() where T : class, IFoo<U> where U : class where V :
             return T.Frob<V>();
         }
     }
+
+    class TestRuntime125577Regression
```
Comment (jkotas) [inline src/tests/nativeaot/SmokeTests/UnitTests/Interfaces.cs:2051]: Should this be a general regression test? There is nothing NAOT specific about it (except that the bug happened to be in nativeaot).

Comment (MichalStrehovsky) [reply src/tests/nativeaot/SmokeTests/UnitTests/Interfaces.cs:2051]: The caching works differently between CoreCLR and native AOT and I don't want anything (someone doing tweaks to this, running it multithreaded with other code, etc.) to stop exercising this specific scenario. See e.g. https://github.com/dotnet/runtime/issues/107999#issuecomment-3072051079.

**Comment by Sergio0694** [comment]
@MichalStrehovsky could we backport this to .NET 10 since it's breaking CsWinRT in a bunch of scenarios? 😅

Also, thank you for the quick fix!! 😄
