### PR TITLE
Fix detection of static readonly field re-initialization via reflection

### LINKED ISSUE #37796: Reflection is able to set initonly static fields in some situation
### Description
It appears that you can set initonly static fields by using reflection when the type load is invoked by the reflection itself. This requires that the value assigned to it is non zero or is being set by a method.

This also has interesting side effect that it allows the JIT to inline the value! Normally this only happens on values set to zero which is a shame. This seems to be bug as per comment on https://github.com/dotnet/runtime/issues/4287#issuecomment-108635719 explains that JIT is already capable on performing suck inline. It seems like changes to JIT has made it unable to inline static fields but abusing reflection magically restores it.

The following code prints out 0x123456789. However when InlineMagicNumber is set to zero FieldAccessException is thrown as expected.
```csharp
internal class Program
{
    private static void Main(string[] args)
    {
        typeof(InlineReadOnly).GetField(nameof(InlineReadOnly.InlineMagicNumber)).SetValue(null, 0x123456789);

        InlineReadOnly.Test();
    }
}

public static class InlineReadOnly
{
    public static readonly long InlineMagicNumber = InlineReadOnly.GetInlineMagicNumber();

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void Test() => Console.WriteLine(InlineReadOnly.InlineMagicNumber);

    public static long GetInlineMagicNumber() => 0;
}
```

### Configuration
Tested on 5.0.0-preview.6.20305.6 using Window 10 1909 x64

### Regression?
This bug seems to go as far as .NET Core 1. However there are some behavior differences. On .NET Core 1 you can freely set static readonly fields whenever you want. So I'm assuming there was no guard against it.

On .NET Core 2 the behavior has changed and the reflection fails silently on values set to zero and you are unable to change the value.

On .NET Core 3 the method starts to throw FieldAccessException.

### Other information
When abusing reflection to set the value the JIT is able to produce inlined code. Magic!
```asm
IN0001: 00000A mov      rcx, 0x123456789
IN0002: 000014 call     Console:WriteLine(long)
IN0003: 000019 nop   
```

When the value is left to zero the JIT is able to inline it too!
```asm
IN0001: 00000A xor      rcx, rcx
IN0002: 00000C call     Console:WriteLine(long)
IN0003: 000011 nop      
```

However when assigning the value to any other value the JIT is unable to inline it. Boo :(
```asm
IN0001: 00000A mov      rcx, 0x7FF7AEBBE8C0
IN0002: 000014 mov      edx, 2
IN0003: 000019 call     CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE
IN0004: 00001E mov      rcx, qword ptr [reloc classVar[0xaebe97f8]]
IN0005: 000025 call     Console:WriteLine(long)
IN0006: 00002A nop      
```

### PR DESCRIPTION
**Pull request by jkotas**
Move the check for static readonly field re-initialization after the static constructor is triggered.

Fixes #37796

### CODE REVIEW

File: src/coreclr/src/vm/invokeutil.cpp [hunk 1]
```diff
@@ -1162,27 +1170,29 @@ OBJECTREF InvokeUtil::GetFieldValue(FieldDesc* pField, TypeHandle fieldType, OBJ
     {
         pDeclMT = declaringType.GetMethodTable();
 
+        // We don't allow getting the field just so we don't have more specical
+        // cases than we need to.  The we need at least the throw check to insure
+        // we don't allow data corruption, but
```
Comment (am11) [inline src/coreclr/src/vm/invokeutil.cpp:1175]:
```suggestion
        // We don't allow getting the field just so we don't have more specical
        // cases than we need to.  Then we need at least the throw check to insure
        // we don't allow data corruption.
```

File: src/coreclr/src/vm/invokeutil.cpp [hunk 2]
```diff
@@ -954,27 +949,28 @@ void InvokeUtil::SetValidField(CorElementType fldType,
     {
         pDeclMT = declaringType.GetMethodTable();
 
+        // We don't allow setting the field of nullable<T> (hasValue and value)
+        // Because you can't independantly set them for this type.
```
Comment (janvorli) [inline src/coreclr/src/vm/invokeutil.cpp:953]: A nit - independantly -> independently
```suggestion
        // Because you can't independently set them for this type.
```

File: src/coreclr/src/vm/invokeutil.cpp [hunk 3]
```diff
@@ -1162,27 +1170,29 @@ OBJECTREF InvokeUtil::GetFieldValue(FieldDesc* pField, TypeHandle fieldType, OBJ
     {
         pDeclMT = declaringType.GetMethodTable();
 
+        // We don't allow getting the field just so we don't have more specical
+        // cases than we need to.  Then we need at least the throw check to insure
```
Comment (janvorli) [inline src/coreclr/src/vm/invokeutil.cpp:1174]: A nit:
```suggestion
        // cases than we need to.  Then we need at least the throw check to ensure
```

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by lambdageek** [comment]
> /cc @vargaz @lambdageek this will need similar fix on Mono side

I created an issue https://github.com/dotnet/runtime/issues/37903  Looks like mono doesn't have a check in `SetValue` for static field reinit at all
