### PR TITLE
[GC] Avoid OOM in large-allocation-only workloads

### LINKED ISSUE #94175: Unexpected OOM with GCHeapLimit
### Description

I run a code that allocates a 100MB array, iterates over it, then discard it (initially meant as a benchmark). When running with `DOTNET_GCHeapHardLimit=7D000000`, the code crashes at the 20th iteration with an OutOfMemoryException.

There are a number of things that make me think it's a bug:

 - It only happens with regions
 - It doesn't happen if I force a GC after each iteration
 - It doesn't happen if I increase the size of the array to be 150MB or bigger
 - When running with a debug CLR, it randomly triggers an assertion:

```
Assert failure(PID 30596 [0x00007784], Thread: 12248 [0x2fd8]): planned_regions_per_gen[0]
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31714
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 18508 [0x484c]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 16148 [0x3f14]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 16720 [0x4150]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 17976 [0x4638]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 37468 [0x925c]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 35856 [0x8c10]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 28252 [0x6e5c]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 37336 [0x91d8]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 33332 [0x8234]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe


Assert failure(PID 30596 [0x00007784], Thread: 44380 [0xad5c]): saved_planned_regions_per_gen[0] >= to_be_empty_regions
    File: E:\git\runtime\src\coreclr\gc\gc.cpp Line: 31721
    Image: E:\git\runtime\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe
```

Note: the assertion doesn't happen every time, so it could be unrelated.

### Reproduction Steps

Run the following code:

```
  public static long Allocate()
  {
      var array = new byte[100 * 1024 * 1024];

      long sum = 0;

      for (int i = 0; i < array.Length; i++)
      {
          sum += array[i];
      }

      return sum;
  }

static void Main()
{
    for (int i = 0; i < 10_000; i++)
    {
        Allocate();
    }
}

```
With:
```
DOTNET_GCHeapHardLimit=7D000000
DOTNET_gcServer=1
```
My machine has 12 cores and it seems to affect the problem, so you might have to adjust the number of heaps accordingly.

### Expected behavior

The code runs without crashing.

### Actual behavior

An OOM is thrown after 19 iterations.

### Regression?

The problem seems related to regions. It happens in .NET 7 and 8, but I can't reproduce it in .NET 6 or when using clrgc.dll.

### Known Workarounds

Use clrgc.dll or increase the heap limit.

### Configuration

.NET 8 RC2
Windows x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by markples**
A few problems can occur with workloads that only allocate huge objects:
- Regions can be pushed to the global decommit list faster than we can process them.  This can lead to OOM (more easily reproducible using a hard heap limit).
- BGCs don't currently call `distribute_free_regions`, so if only those occur, then the freelist processing never occurs at all.

This change addresses those by doing the following:
- Call `distribute_free_regions` during `background_mark_phase` (while we initially have the VM suspended to avoid complications).
- Currently, `distribute_free_regions` can't hit the `move_highest_free_regions` code path when `background_running_p()`.  Change that check to also require `settings.condemned_generation != max_generation`.
- Slow the movement of huge regions from the freelist to the global decommit list.
  - Add aging to regions in `global_free_huge_regions`.
  - Require an age of MIN_AGE_TO_DECOMMIT_HUGE (2) before including them in a surplus balance.
  - Factor aging code into `age_free_regions`.

Fixes #94175

### CODE REVIEW

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -13587,6 +13617,40 @@ void gc_heap::distribute_free_regions()
...
+    {
+        gc_heap* hp = gc_heap::g_heaps[i];
+#else //MULTIPLE_HEAPS
+    {
+        gc_heap* hp = pGenGCHeap;
+        const int i = 0;
+#endif //MULTIPLE_HEAPS
+
+        hp->descr_generations (label);
+#ifdef USE_REGIONS
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:13633]: we'd want to leave this in gc1 because this doesn't only apply to regions

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -13587,6 +13617,40 @@ void gc_heap::distribute_free_regions()
...
+        if (settings.condemned_generation == max_generation)
+        {
+            // age and print all kinds of free regions
+            if (i == 0)
+            {
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:13638]: nit - could hoist this out.

**Comment by Maoni0** [comment]
actually there is an optimization we should do here to avoid calling `distribute_free_regions` at the beginning of a BGC if we just did an ephemeral GC (there's no need to call it again as that ephemeral GC would've called it).

File: src/coreclr/gc/gc.cpp (hunk 1 above)
Comment (markples) [reply src/coreclr/gc/gc.cpp:13633]: Interestingly, I had preserved the non-regions behavior by having the `#ifdef USE_REGIONS` scoped carefully here, but it was confusing because of the name `age_free_regions` (which is already a good reason to pull this line out).  But then, after pulling this line out, since the entire method is now only for regions, I don't need an extra `ifdef` to hoist out the code for your next comment.

**Comment by markples** [comment]
> actually there is an optimization we should do here to avoid calling `distribute_free_regions` at the beginning of a BGC if we just did an ephemeral GC (there's no need to call it again as that ephemeral GC would've called it).

I did this for `distribute_free_regions` and `age_free_regions`.  The latter prevents the basic regions from being aged twice but requires the ephemeral GC to age the large and huge regions.

**Review by Maoni0 — APPROVED** [review]
LGTM!

**Comment by markples** [comment]
verified that original test case in #94175 is fixed by this PR
