### PR TITLE
[mono][tests] Update instantiate_info to use mono_class_interface_offset_with_variance for interface offset

### LINKED ISSUE #71910: [mono] Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319 crashes with runtime assertion failure
Runtime: **mono**
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1867131&view=ms.vss-test-web.build-test-results-tab&runId=48975646&resultId=102178&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab
Test: <code>Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319</code>

Diagnostic info:
<pre>
  Starting:    Loader.classloader.XUnitWrapper (parallel test collections = on, max threads = 2)
    Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319/GitHub_71319.sh [FAIL]
      
      =================================================================
      External Debugger Dump:
      =================================================================
      [New LWP 9728]
      [New LWP 9730]
      [New LWP 9731]
      [Thread debugging using libthread_db enabled]
      Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
      warning: the debug information found in "/datadisks/disk1/work/B2220938/p/libcoreclr.so.dbg" does not match "/datadisks/disk1/work/B2220938/p/libcoreclr.so" (CRC mismatch).
      
      0x00007f3a54d8c32a in __waitpid (pid=9732, stat_loc=0x7ffe561cdf40, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
      30../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
        Id   Target Id         Frame 
      * 1    Thread 0x7f3a553b3740 (LWP 9725) "corerun" 0x00007f3a54d8c32a in __waitpid (pid=9732, stat_loc=0x7ffe561cdf40, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
        2    Thread 0x7f3a513ff700 (LWP 9728) "SGen worker" 0x00007f3a54d87ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3a54013608) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
        3    Thread 0x7f3a4e677700 (LWP 9730) "corerun" 0x00007f3a5415ebb9 in __GI___poll (fds=0x7f3a48002d50, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        4    Thread 0x7f3a4e476700 (LWP 9731) "Finalizer" 0x00007f3a54d8a7c6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7f3a54004510) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
      
      Thread 4 (Thread 0x7f3a4e476700 (LWP 9731)):
      #0  0x00007f3a54d8a7c6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7f3a54004510) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
      #1  do_futex_wait (sem=sem@entry=0x7f3a54004510, abstime=0x0) at sem_waitcommon.c:111
      #2  0x00007f3a54d8a8b8 in __new_sem_wait_slow (sem=0x7f3a54004510, abstime=0x0) at sem_waitcommon.c:181
      #3  0x00007f3a52839186 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #4  0x00007f3a52811dfa in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #5  0x00007f3a52811c89 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #6  0x00007f3a54d816db in start_thread (arg=0x7f3a4e476700) at pthread_create.c:463
      #7  0x00007f3a5416b61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
      
      Thread 3 (Thread 0x7f3a4e677700 (LWP 9730)):
      #0  0x00007f3a5415ebb9 in __GI___poll (fds=0x7f3a48002d50, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
      #1  0x00007f3a52a9991a in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #2  0x00007f3a52a96e25 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #3  0x00007f3a52a95539 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #4  0x00007f3a52a98d31 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #5  0x00007f3a54d816db in start_thread (arg=0x7f3a4e677700) at pthread_create.c:463
      #6  0x00007f3a5416b61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
      
      Thread 2 (Thread 0x7f3a513ff700 (LWP 9728)):
      #0  0x00007f3a54d87ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3a54013608) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
      #1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f3a540135b8, cond=0x7f3a540135e0) at pthread_cond_wait.c:502
      #2  __pthread_cond_wait (cond=0x7f3a540135e0, mutex=0x7f3a540135b8) at pthread_cond_wait.c:655
      #3  0x00007f3a528b7653 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #4  0x00007f3a54d816db in start_thread (arg=0x7f3a513ff700) at pthread_create.c:463
      #5  0x00007f3a5416b61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
      
      Thread 1 (Thread 0x7f3a553b3740 (LWP 9725)):
      #0  0x00007f3a54d8c32a in __waitpid (pid=9732, stat_loc=0x7ffe561cdf40, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
      #1  0x00007f3a529d0db7 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #2  0x00007f3a52972a6e in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #3  0x00007f3a529d0548 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #4  <signal handler called>
      #5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
      #6  0x00007f3a5408a7f1 in __GI_abort () at abort.c:79
      #7  0x00007f3a52a4b075 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #8  0x00007f3a52860c33 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #9  0x00007f3a52a4b4dd in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #10 0x00007f3a52a4b645 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #11 0x00007f3a52a4b687 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #12 0x00007f3a5297d55c in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #13 0x00007f3a5297c3c1 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #14 0x00007f3a5291de15 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
      #15 0x00007f3a4defdcdc in Program_CallStatic_T_REF_U_REF () from /datadisks/disk1/work/B2220938/w/90800829/e/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319/GitHub_71319.dll.so
      #16 0x0000556a7bfb2ec0 in ?? ()
      #17 0x00007f3a4defdd9f in Program_Main () at /__w/1/s/src/tests/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319.cs:28
      #18 0x0000000000000000 in ?? ()
      /datadisks/disk1/work/B2220938/w/90800829/e/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319/GitHub_71319.sh: line 382:  9725 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/B2220938/w/90800829/uploads/Reports/Loader.classloader/StaticVirtualMethods/RegressionTests/GitHub_71319/GitHub_71319.output.txt
      Raw output:
      BEGIN EXECUTION
      /datadisks/disk1/work/B2220938/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false GitHub_71319.dll ''
      * Assertion at /__w/1/s/src/mono/mono/mini/mini-generic-sharing.c:2267, condition `ioffset != -1' not met
      
      
      =================================================================
      Native Crash Reporting
      =================================================================
      Got a SIGABRT while executing native code. This usually indicates
      a fatal error in the mono runtime or one of the native libraries 
      used by your application.
      =================================================================
      
      =================================================================
      Native stacktrace:
      =================================================================
      0x7f3a529d0c72 - Unknown
      0x7f3a52972a6e - Unknown
      0x7f3a529d0548 - Unknown
      0x7f3a54d8c980 - Unknown
      0x7f3a54088e87 - Unknown
      0x7f3a5408a7f1 - Unknown
      0x7f3a52a4b075 - Unknown
      0x7f3a52860c33 - Unknown
      0x7f3a52a4b4dd - Unknown
      0x7f3a52a4b645 - Unknown
      0x7f3a52a4b687 - Unknown
      0x7f3a5297d55c - Unknown
      0x7f3a5297c3c1 - Unknown
      0x7f3a5291de15 - Unknown
      0x7f3a4defdcdc - Unknown
      
      =================================================================
      Basic Fault Address Reporting
      =================================================================
      Memory around native instruction pointer (0x7f3a54088e87):0x7f3a54088e77  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
      0x7f3a54088e87  48 8b 8c 24 08 01 00 00 64 48 33 0c 25 28 00 00  H..$....dH3.%(..
      0x7f3a54088e97  00 44 89 c0 75 1f 48 81 c4 18 01 00 00 c3 0f 1f  .D..u.H.........
      0x7f3a54088ea7  00 48 8b 15 b9 bf 3a 00 f7 d8 41 b8 ff ff ff ff  .H....:...A.....
      
      =================================================================
      Managed Stacktrace:
      =================================================================
      =================================================================
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/B2220938/p
      > /datadisks/disk1/work/B2220938/w/90800829/e/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319/GitHub_71319.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at Loader_classloader._StaticVirtualMethods_RegressionTests_GitHub_71319_GitHub_71319_._StaticVirtualMethods_RegressionTests_GitHub_71319_GitHub_71319_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        =================================================================
        External Debugger Dump:
        =================================================================
        [New LWP 9728]
        [New LWP 9730]
        [New LWP 9731]
        [Thread debugging using libthread_db enabled]
        Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
        warning: the debug information found in "/datadisks/disk1/work/B2220938/p/libcoreclr.so.dbg" does not match "/datadisks/disk1/work/B2220938/p/libcoreclr.so" (CRC mismatch).
        
        0x00007f3a54d8c32a in __waitpid (pid=9732, stat_loc=0x7ffe561cdf40, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
        30../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
          Id   Target Id         Frame 
        * 1    Thread 0x7f3a553b3740 (LWP 9725) "corerun" 0x00007f3a54d8c32a in __waitpid (pid=9732, stat_loc=0x7ffe561cdf40, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
          2    Thread 0x7f3a513ff700 (LWP 9728) "SGen worker" 0x00007f3a54d87ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3a54013608) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
          3    Thread 0x7f3a4e677700 (LWP 9730) "corerun" 0x00007f3a5415ebb9 in __GI___poll (fds=0x7f3a48002d50, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
          4    Thread 0x7f3a4e476700 (LWP 9731) "Finalizer" 0x00007f3a54d8a7c6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7f3a54004510) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
        
        Thread 4 (Thread 0x7f3a4e476700 (LWP 9731)):
        #0  0x00007f3a54d8a7c6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7f3a54004510) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
        #1  do_futex_wait (sem=sem@entry=0x7f3a54004510, abstime=0x0) at sem_waitcommon.c:111
        #2  0x00007f3a54d8a8b8 in __new_sem_wait_slow (sem=0x7f3a54004510, abstime=0x0) at sem_waitcommon.c:181
        #3  0x00007f3a52839186 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #4  0x00007f3a52811dfa in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #5  0x00007f3a52811c89 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #6  0x00007f3a54d816db in start_thread (arg=0x7f3a4e476700) at pthread_create.c:463
        #7  0x00007f3a5416b61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
        
        Thread 3 (Thread 0x7f3a4e677700 (LWP 9730)):
        #0  0x00007f3a5415ebb9 in __GI___poll (fds=0x7f3a48002d50, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        #1  0x00007f3a52a9991a in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #2  0x00007f3a52a96e25 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #3  0x00007f3a52a95539 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #4  0x00007f3a52a98d31 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #5  0x00007f3a54d816db in start_thread (arg=0x7f3a4e677700) at pthread_create.c:463
        #6  0x00007f3a5416b61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
        
        Thread 2 (Thread 0x7f3a513ff700 (LWP 9728)):
        #0  0x00007f3a54d87ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3a54013608) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
        #1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f3a540135b8, cond=0x7f3a540135e0) at pthread_cond_wait.c:502
        #2  __pthread_cond_wait (cond=0x7f3a540135e0, mutex=0x7f3a540135b8) at pthread_cond_wait.c:655
        #3  0x00007f3a528b7653 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #4  0x00007f3a54d816db in start_thread (arg=0x7f3a513ff700) at pthread_create.c:463
        #5  0x00007f3a5416b61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
        
        Thread 1 (Thread 0x7f3a553b3740 (LWP 9725)):
        #0  0x00007f3a54d8c32a in __waitpid (pid=9732, stat_loc=0x7ffe561cdf40, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
        #1  0x00007f3a529d0db7 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #2  0x00007f3a52972a6e in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #3  0x00007f3a529d0548 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #4  <signal handler called>
        #5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        #6  0x00007f3a5408a7f1 in __GI_abort () at abort.c:79
        #7  0x00007f3a52a4b075 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #8  0x00007f3a52860c33 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #9  0x00007f3a52a4b4dd in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #10 0x00007f3a52a4b645 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #11 0x00007f3a52a4b687 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #12 0x00007f3a5297d55c in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #13 0x00007f3a5297c3c1 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #14 0x00007f3a5291de15 in ?? () from /datadisks/disk1/work/B2220938/p/libcoreclr.so
        #15 0x00007f3a4defdcdc in Program_CallStatic_T_REF_U_REF () from /datadisks/disk1/work/B2220938/w/90800829/e/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319/GitHub_71319.dll.so
        #16 0x0000556a7bfb2ec0 in ?? ()
        #17 0x00007f3a4defdd9f in Program_Main () at /__w/1/s/src/tests/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319.cs:28
        #18 0x0000000000000000 in ?? ()
        /datadisks/disk1/work/B2220938/w/90800829/e/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319/GitHub_71319.sh: line 382:  9725 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/B2220938/w/90800829/uploads/Reports/Loader.classloader/StaticVirtualMethods/RegressionTests/GitHub_71319/GitHub_71319.output.txt
        Raw output:
        BEGIN EXECUTION
        /datadisks/disk1/work/B2220938/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false GitHub_71319.dll ''
        * Assertion at /__w/1/s/src/mono/mono/mini/mini-generic-sharing.c:2267, condition `ioffset != -1' not met
        
        
        =================================================================
        Native Crash Reporting
        =================================================================
        Got a SIGABRT while executing native code. This usually indicates
        a fatal error in the mono runtime or one of the native libraries 
        used by your application.
        =================================================================
        
        =================================================================
        Native stacktrace:
        =================================================================
        0x7f3a529d0c72 - Unknown
        0x7f3a52972a6e - Unknown
        0x7f3a529d0548 - Unknown
        0x7f3a54d8c980 - Unknown
        0x7f3a54088e87 - Unknown
        0x7f3a5408a7f1 - Unknown
        0x7f3a52a4b075 - Unknown
        0x7f3a52860c33 - Unknown
        0x7f3a52a4b4dd - Unknown
        0x7f3a52a4b645 - Unknown
        0x7f3a52a4b687 - Unknown
        0x7f3a5297d55c - Unknown
        0x7f3a5297c3c1 - Unknown
        0x7f3a5291de15 - Unknown
        0x7f3a4defdcdc - Unknown
        
        =================================================================
        Basic Fault Address Reporting
        =================================================================
        Memory around native instruction pointer (0x7f3a54088e87):0x7f3a54088e77  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
        0x7f3a54088e87  48 8b 8c 24 08 01 00 00 64 48 33 0c 25 28 00 00  H..$....dH3.%(..
        0x7f3a54088e97  00 44 89 c0 75 1f 48 81 c4 18 01 00 00 c3 0f 1f  .D..u.H.........
        0x7f3a54088ea7  00 48 8b 15 b9 bf 3a 00 f7 d8 41 b8 ff ff ff ff  .H....:...A.....
        
        =================================================================
        Managed Stacktrace:
        =================================================================
        =================================================================
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/B2220938/p
        > /datadisks/disk1/work/B2220938/w/90800829/e/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_71319/GitHub_71319.sh
  Finished:    Loader.classloader.XUnitWrapper
</pre>

In the PR

https://github.com/dotnet/runtime/pull/71461

I'm adding the new regression test <code>GitHub_71319</code>; the test however currently fails on Mono, I'm creating this issue so that I can merge in the appropriate <code>issues.targets</code> exclusion as part of the test.

Thanks

Tomas

### PR DESCRIPTION
**Pull request by kotlarmilos**
Fix disabled runtime generic methods test. Update `instantiate_info` to use `mono_class_interface_offset_with_variance` for interface offset in `MONO_RGCTX_INFO_VIRT_METHOD_CODE`.

Related issues:

- https://github.com/dotnet/runtime/issues/71910

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

File: src/mono/mono/mini/mini-generic-sharing.c [hunk 1]
```diff
@@ -2273,7 +2273,8 @@ instantiate_info (MonoMemoryManager *mem_manager, MonoRuntimeGenericContextInfoT
 		mono_class_setup_vtable (info->klass);
 		// FIXME: Check type load
 		if (mono_class_is_interface (iface_class)) {
-			ioffset = mono_class_interface_offset (info->klass, iface_class);
+			gboolean variance_used;
+			ioffset = mono_class_interface_offset_with_variance (info->klass, iface_class, &variance_used);
```
Comment (vargaz) [inline src/mono/mono/mini/mini-generic-sharing.c:2277]: Shouldn't we do something with variance_used ?

Comment (kotlarmilos) [reply src/mono/mono/mini/mini-generic-sharing.c:2277]: For interface with generic variant arguments, it tries to find the compatible one and sets `variance_used = TRUE`. Result of the function is used for vtable method positioning as `method = m_class_get_vtable (info->klass) [ioffset + slot];`. I don't see that it should be changed according to `variance_used` variable. Other references of the method don't use `variance_used` as well.

Do you see a case where it should be used?
