### PR TITLE
Fixing several of the Sse/Sse2.Compare* intrinsics to account for NaN inputs

### LINKED ISSUE #34094: CompareGreaterThan, CompareGreaterThanOrEqual, CompareNotGreaterThan, and CompareNotGreaterThanOrEqual have incorrect implementations
As per the title, the following methods have incorrect implementations and won't handle NaN inputs correctly:
* NI_SSE_CompareGreaterThan
* NI_SSE_CompareScalarGreaterThan
* NI_SSE_CompareGreaterThanOrEqual
* NI_SSE_CompareScalarGreaterThanOrEqual
* NI_SSE_CompareNotGreaterThan
* NI_SSE_CompareScalarNotGreaterThan
* NI_SSE_CompareNotGreaterThanOrEqual
* NI_SSE_CompareScalarNotGreaterThanOrEqual
* NI_SSE2_CompareGreaterThan
* NI_SSE2_CompareScalarGreaterThan
* NI_SSE2_CompareGreaterThanOrEqual
* NI_SSE2_CompareScalarGreaterThanOrEqual
* NI_SSE2_CompareNotGreaterThan
* NI_SSE2_CompareScalarNotGreaterThan
* NI_SSE2_CompareNotGreaterThanOrEqual
* NI_SSE2_CompareScalarNotGreaterThanOrEqual

For pre-AVX hardware, there isn't a hardware comparison mode that performs the given operations and so they are currently being implemented using the inverse operation.
However, using the inverse operation (such as converting `GreaterThan` to `NotLessThanOrEqual`) does not correctly handle the unordered relation (when one or both inputs is `NaN`).

These should instead be using a different inverse relation and swapping the operands. For example, `CompareGreaterThan(a, b)` should be emitted as `CompareLessThan(b, a)` as native does and as recommended by the x86 instruction manual: https://godbolt.org/z/ghwY5N

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #34094 by updating several of the Sse/Sse2.Compare* intrinsics to account for NaN inputs when their isn't a direct comparison mode supported by the underlying hardware.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @CarolEidt, @echesakovMSFT 

As called out in #34094 this is a breaking change if one of the inputs was NaN, but it was also a bug and caused a difference in behavior if you were using `FloatComparisonMode` directly on AVX enabled hardware.

File: src/coreclr/src/jit/hwintrinsicxarch.cpp [hunk 1]
```diff
@@ -1172,19 +1172,191 @@ GenTree* Compiler::impBaseIntrinsic(NamedIntrinsic        intrinsic,
...
+        {
+            assert(sig->numArgs == 2);
+            op2      = impSIMDPopStack(TYP_SIMD16);
+            op1      = impSIMDPopStack(TYP_SIMD16);
+            baseType = getBaseTypeOfSIMDType(sig->retTypeSigClass);
+            assert(baseType == TYP_FLOAT);
+
+            if (compSupports(InstructionSet_AVX))
+            {
+                retNode = gtNewSimdHWIntrinsicNode(TYP_SIMD16, op1, op2, gtNewIconNode(14), NI_AVX_Compare, baseType, simdSize);
```
Comment (tannergooding) [inline src/coreclr/src/jit/hwintrinsicxarch.cpp]: On AVX hardware, we can just use the hardware supported comparison mode. On non-AVX enabled hardware, we have to fallback to doing a different operation with the operands swapped.

File: src/coreclr/src/jit/hwintrinsicxarch.cpp [hunk 2]
```diff
@@ -1172,19 +1172,191 @@ GenTree* Compiler::impBaseIntrinsic(NamedIntrinsic        intrinsic,
...
+                retNode = gtNewSimdHWIntrinsicNode(TYP_SIMD16, op1, op2, gtNewIconNode(14), NI_AVX_CompareScalar, baseType, simdSize);
+            }
+            else
+            {
+                GenTree* clonedOp1 = nullptr;
+                op1                = impCloneExpr(op1, &clonedOp1, NO_CLASS_HANDLE, (unsigned)CHECK_SPILL_ALL,
+                                        nullptr DEBUGARG("Clone op1 for Sse.CompareScalarGreaterThan"));
+
+                retNode = gtNewSimdHWIntrinsicNode(TYP_SIMD16, op2, op1, NI_SSE_CompareScalarLessThan, baseType, simdSize);
+                retNode = gtNewSimdHWIntrinsicNode(TYP_SIMD16, clonedOp1, retNode,  NI_SSE_MoveScalar, baseType, simdSize);
```
Comment (tannergooding) [inline src/coreclr/src/jit/hwintrinsicxarch.cpp]: For the scalar versions, the non-AVX path needs to ensure that `CopiesUpperBits` is still respected, so we have to do an additional `MoveScalar` operation.

**Comment by tannergooding** [comment]
@BruceForstall, @jeffhandley, @terrajobst; What is the current process for getting sign-off on breaking changes like this?

**Comment by tannergooding** [comment]
Just a note, this is the kind of change that could have been easily handled in managed land (rather than in importation) if we weren't blocked due to the more complex trees that it produces (https://github.com/dotnet/runtime/issues/956).

**Comment by terrajobst** [comment]
> @BruceForstall, @jeffhandley, @terrajobst; What is the current process for getting sign-off on breaking changes like this?

I don't believe we have centralized sign-off process for this anymore. @ericstj @PriyaPurkayastha what are your thoughts?

**Comment by PriyaPurkayastha** [comment]
Correct, there is no compat council that reviews/approves breaking changes. Review happens during Tactics. General guidelines that are given to teams is to determine what are the driving factors for making the breaking change (is this a customer reported issue etc.). What is the cost to make the change in a compatible way - can opt-in/opt-out switches be provided? Should additional data be gathered to understand impact of change? (e.g. contact .NET Technical Insights team). Other action items are to add/update functional tests for code paths changed and documenting the breaking change by using the https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md issue template. 
@marklio do you have additional comments/feedback for this proposed breaking change?

**Comment by marklio** [comment]
Things I would be interested in:

  *   It sounds like whether this is breaking depends slightly on what kind of hardware you’re on a) is that correct, and b) do we have data or an intuition about what the split is on the hardware distribution?
  *   Are there APIs we can look for in the ecosystem to get an idea of the impact of a change?
  *   How would customers encounter this as a break? Different output from floating point comparisons? Exceptions? How do these behaviors compare to the documentation? (are we standardizing on documented behavior? Or do the docs not cover this)
  *   How does the behavior compare to .NET Framework? (if relevant)

It definitely sounds like the new behavior is “more correct” and that we definitely want it to be the behavior going forward. So, the discussion is likely going to be about how we help customers absorb the change (rather than whether we would “approve” the change).

Mark

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tannergooding** [comment]
@marklio, see below

>  *   It sounds like whether this is breaking depends slightly on what kind of hardware you’re on a) is that correct, and b) do we have data or an intuition about what the split is on the hardware distribution?

Not quite. Basically there exists two instruction sets for the purposes of this discussion. SSE2 (which has been around since 2000 and is a baseline requirement for .NET Core) and AVX (which has been around since 2011 and which, to my knowldege, is available in all Intel/AMD based VMs on Azure).

Today, if using the 8x `Sse2.Compare*` APIs that do `GreaterThan`, `GreaterThanOrEqual`, `NotGreaterThan` or `NotGreaterThanOrEqual` comparisons you get a behavior that doesn't correctly handle `NaN` (not-a-number) inputs. These APIs are available on any x86 (Intel/AMD) machine running .NET Core 3.0 or later. This is because the correct implementation of these functions must be "emulated" as there doesn't exist direct hardware support and the overloads were provided for completeness and parity with the equivalent feature in C/C++, Rust, and other langugages. `floating-point` behaves a bit differently form normal math, especially around `NaN` inputs, and so the normal inversion rules don't quite apply (that is `NotGreaterThan` can't be implemented as `LessThanOrEqual`). This was missed in review, hence the bug.

If using the related `Avx.Compare*` APIs, you get a different behavior that does correctly handle `NaN` because there is direct hardware support. This is only available on machines from 2011 and later, but is still fairly prominent being nearly 10 years old and with it being available on machines in Azure, AWS, etc.

>  *   Are there APIs we can look for in the ecosystem to get an idea of the impact of a change?

These are new APIs only introduced in .NET Core 3.0 (Sep 2019, already end of support) and available in .NET Core 3.1 (Dec 2019, supported until Dec 2022).

They are also extremely low level/advanced APIs that are designed to be (and were documented as being) essentially a 1-to-1 mapping with certain instructions exposed by the underlying hardware. You can only use certain APIs if your hardware supports it and they are meant to be used in high-performance/unsafe scenarios.

The usages, as such, would likely be limited (new and advanced use-case API) and hard to find. We aren't using them in the framework ourselves.

>  *   How would customers encounter this as a break? Different output from floating point comparisons? Exceptions? How do these behaviors compare to the documentation? (are we standardizing on documented behavior? Or do the docs not cover this)

You would get a different result as part of the comparison if either input contained a `NaN` floating-point value. As for documented behavior, we document ourselves to be compatible with the native equivalents of the intrinsics and with the underlying hardware instructions.

>  *   How does the behavior compare to .NET Framework? (if relevant)

This is not supported on .NET Framework, it is only available on .NET Core 3.0 and later.

**Comment by marklio** [comment]
Cool. So what scenarios would lead folks to calling the problematic overloads on Sse2 over the AVX ones? For the sake of argument, are those scenarios worth fixing? Should they just be deprecated? Should we handle this with an analyzer/fixer that calls the "working" API?

I assume that fixing the bug in 3.x wouldn't meet the servicing bar?

To be clear, you're under no obligation to convince me of anything. I'm just trying to help build a case for taking the fix and deciding how help customers through any pain. It seems like anyone who knows what they're doing will expect appropriate behavior from these APIs, and we haven't gotten feedback probably because very few people are using these APIs, and those who are probably aren't pushing NaN's through them. In which case, documenting the breaking change and making it probably makes the most sense.

**Comment by tannergooding** [comment]
> Cool. So what scenarios would lead folks to calling the problematic overloads on Sse2 over the AVX ones? For the sake of argument, are those scenarios worth fixing? Should they just be deprecated? Should we handle this with an analyzer/fixer that calls the "working" API?

The primary reason would be wanting to support downlevel hardware while also accelerating further (such as by operating on 256-bits per iteration, rather than 128-bits) on newer hardware.
We could fix it with an analyzer/obsoleting the existing API, but seems like a poor alternative to just fixing it, given how new the API is and that the alternatives aren't as straightforward to use.

That is, the `Avx` overloads are primarily for 256-bit operations (vs the 128-bit operations that `Sse2` provides) and the `Avx` overload that does operate on `128-bits` takes a much more complex enum where the operation mapping isn't as straightforward (`CompareGreaterThan(left, right)` would be `Compare(left, right, FloatComparisonMode.OrderedGreaterThanSignaling);`). Likewise, on hardware without `Avx` support, you have to know that `CompareGreaterThan(left, right)` needs to be implemented as `CompareLessThan(right, left)` and that you need an additional `MoveScalar(result, left)` to ensure bit propagation remains for the `Scalar` variants of the APIs.

> I assume that fixing the bug in 3.x wouldn't meet the servicing bar?

I'm unsure whether or not this would meet the bar and would defer to @jeffhandley and/or @BruceForstall.

**Comment by marklio** [comment]
I definitely wouldn't want to break folks in servicing for this. It was more of a rhetorical question about whether it had been considered. I definitely could have phrased that more clearly.

**Comment by jeffhandley** [comment]
> I definitely wouldn't want to break folks in servicing for this.

So is fixing it only in .NET 5.0+ the best approach here, @marklio?  @tannergooding, do you know of any reason to lobby for it to be fixed in 3.x, or would 5.0 be OK with you?

**Comment by marklio** [comment]
> So is fixing it only in .NET 5.0+ the best approach here, @marklio?

Yes, that would be the position I'd take to tactics. Take the fix in 5.0 and document through the breaking change process.

We wouldn't bring this for 3.x because:
* It is a breaking change.
* We don't have any customers hitting this. (likely few folks using it, and they may not be passing NaN
* We think people using these features are advanced folks who will likely be moving to bleeding edge to get more of these features, and won't mind moving to 5 to get this fix (this is conjecture on my part, so we have any data to back this up? I'll look for some tomorrow).

We want the fix in 5.0 because:
* It is "correct" behavior WRT specification, and moreover represents a consolidation of similar behaviors being added to the product.
* We have time to get feedback, and a feature audience that is likely adopting new versions quickly (again, conjecture)

I'd also watch for signal in previews of anyone playing with 5.0 that encounters this as a break in their code. That might lead us to other mitigations.

**Comment by BruceForstall** [comment]
A minor point is that if we do NOT fix it in servicing, and people start using this relatively new API in their code, we could end up with MORE user code that needs to be updated in the long run.

I wonder (and this is a general query, not just for this case) if there is a way we can (or should) annotate the 3.1 documentation now indicating a post-3.1 breaking change has been made to a particular API, to try and encourage people not to take a dependency on the subsequently-broken behavior.

**Comment by saucecontrol** [comment]
In this case, there's a clean and forward-compatible workaround, so it's not a big deal if it isn't fixed in 3.1.  But if it weren't as simple, the argument that the breakage footprint will never be smaller than now is really important.

**Comment by jeffhandley** [comment]
We solidified the decision today, @tannergooding:

1. Make the fix in .NET 5.0
1. Do not apply the fix to 3.x
1. Update documentation to call out the bug and the upcoming breaking change, illustrating a forward-compatible workaround

**Comment by tannergooding** [comment]
I've rebased ontop of current master and this should be ready for review. I'll get a change up for the docs-repo that calls out the breaking change before merging.

**Comment by PriyaPurkayastha** [comment]
Here's the breaking change issue template to be used https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md

**Comment by tannergooding** [comment]
Had to update to use the new `compExactlyDependsOn` method.

File: src/coreclr/src/jit/hwintrinsicxarch.cpp [hunk 3]
```diff
@@ -1173,19 +1173,209 @@ GenTree* Compiler::impBaseIntrinsic(NamedIntrinsic        intrinsic,
...
     {
+        case NI_SSE_CompareGreaterThan:
+        {
+            assert(sig->numArgs == 2);
+            op2      = impSIMDPopStack(TYP_SIMD16);
+            op1      = impSIMDPopStack(TYP_SIMD16);
+            baseType = getBaseTypeOfSIMDType(sig->retTypeSigClass);
+            assert(baseType == TYP_FLOAT);
+
+            if (compExactlyDependsOn(InstructionSet_AVX))
```
Comment (tannergooding) [inline src/coreclr/src/jit/hwintrinsicxarch.cpp:1196]: @davidwrighton, should I be using `Exactly` or `Opportunistically` here?

Based on https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/vectors-and-intrinsics.md#mechanisms-in-the-jit-to-generate-correct-code-to-handle-varied-instruction-set-support, it sounds like I want `Opportunistically` since the two paths are semantically equivalent and the AVX path is just an optimization for better codegen. Is that correct?

Comment (davidwrighton) [reply src/coreclr/src/jit/hwintrinsicxarch.cpp:1196]: Yes. My analysis matches yours. These can (and should) be compared using `Opportunistically`.

Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsicxarch.cpp:1196]: Thanks! I just asked a related question on https://github.com/dotnet/runtime/pull/33924#issuecomment-613015698, since I think it falls into the same category.

Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsicxarch.cpp]: Switched to using `compOpportunisticallyDependsOn` as both paths are TYP_SIMD16 and are semantically equivalent.

**Comment by tannergooding** [comment]
Test failures are unrelated and tracked by https://github.com/dotnet/runtime/issues/34905

**Comment by tannergooding** [comment]
Logged https://github.com/dotnet/docs/issues/17838 to track the breaking change

File: src/coreclr/src/jit/hwintrinsicxarch.cpp [hunk 4]
```diff
@@ -1173,19 +1173,209 @@ GenTree* Compiler::impBaseIntrinsic(NamedIntrinsic        intrinsic,
...
+        {
+            assert(sig->numArgs == 2);
+            op2      = impSIMDPopStack(TYP_SIMD16);
+            op1      = impSIMDPopStack(TYP_SIMD16);
+            baseType = getBaseTypeOfSIMDType(sig->retTypeSigClass);
+            assert(baseType == TYP_FLOAT);
+
+            if (compOpportunisticallyDependsOn(InstructionSet_AVX))
+            {
+                retNode = gtNewSimdHWIntrinsicNode(TYP_SIMD16, op1, op2, gtNewIconNode(14), NI_AVX_Compare, baseType,
```
Comment (echesakovMSFT) [inline src/coreclr/src/jit/hwintrinsicxarch.cpp:1198]: Can we have an enum for this constants or at least #define-s  instead of hardcoding them?

File: src/coreclr/src/jit/hwintrinsicxarch.cpp [hunk 5]
```diff
@@ -1173,19 +1173,209 @@ GenTree* Compiler::impBaseIntrinsic(NamedIntrinsic        intrinsic,
...
+                                                   simdSize);
+            }
+            else
+            {
+                retNode = gtNewSimdHWIntrinsicNode(TYP_SIMD16, op2, op1, NI_SSE_CompareLessThan, baseType, simdSize);
```
Comment (echesakovMSFT) [inline src/coreclr/src/jit/hwintrinsicxarch.cpp:1203]: So idea here is to use AVX `vcmpps` if supported, otherwise, flip the arguments and use SSE `cmpps`? This is done because the AVX instruction guaranteed to be more performant even for the same vector size?

File: src/coreclr/tests/src/Regressions/coreclr/GitHub_34094/test34094.cs [hunk 6]
```diff
@@ -0,0 +1,557 @@
+// Licensed to the .NET Foundation under one or more agreements.
```
Comment (echesakovMSFT) [inline src/coreclr/tests/src/Regressions/coreclr/GitHub_34094/test34094.cs:1]: Are these auto-generated with T4? If so, can you attach the *.tt file?

File: src/coreclr/src/jit/hwintrinsicxarch.cpp (hunk 4 above)
Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsicxarch.cpp:1198]: As long as you're fine with the existing C++ names:
```
#define _CMP_EQ_OQ     0x00  /* Equal (ordered, nonsignaling)               */
#define _CMP_LT_OS     0x01  /* Less-than (ordered, signaling)              */
#define _CMP_LE_OS     0x02  /* Less-than-or-equal (ordered, signaling)     */
#define _CMP_UNORD_Q   0x03  /* Unordered (nonsignaling)                    */
#define _CMP_NEQ_UQ    0x04  /* Not-equal (unordered, nonsignaling)         */
#define _CMP_NLT_US    0x05  /* Not-less-than (unordered, signaling)        */
#define _CMP_NLE_US    0x06  /* Not-less-than-or-equal (unordered,
                                                        signaling)          */
#define _CMP_ORD_Q     0x07  /* Ordered (nonsignaling)                      */
#define _CMP_EQ_UQ     0x08  /* Equal (unordered, non-signaling)            */
#define _CMP_NGE_US    0x09  /* Not-greater-than-or-equal (unordered,
                                                           signaling)       */
#define _CMP_NGT_US    0x0A  /* Not-greater-than (unordered, signaling)     */
#define _CMP_FALSE_OQ  0x0B  /* False (ordered, nonsignaling)               */
#define _CMP_NEQ_OQ    0x0C  /* Not-equal (ordered, non-signaling)          */
#define _CMP_GE_OS     0x0D  /* Greater-than-or-equal (ordered, signaling)  */
#define _CMP_GT_OS     0x0E  /* Greater-than (ordered, signaling)           */
#define _CMP_TRUE_UQ   0x0F  /* True (unordered, non-signaling)             */
#define _CMP_EQ_OS     0x10  /* Equal (ordered, signaling)                  */
#define _CMP_LT_OQ     0x11  /* Less-than (ordered, nonsignaling)           */
#define _CMP_LE_OQ     0x12  /* Less-than-or-equal (ordered, nonsignaling)  */
#define _CMP_UNORD_S   0x13  /* Unordered (signaling)                       */
#define _CMP_NEQ_US    0x14  /* Not-equal (unordered, signaling)            */
#define _CMP_NLT_UQ    0x15  /* Not-less-than (unordered, nonsignaling)     */
#define _CMP_NLE_UQ    0x16  /* Not-less-than-or-equal (unordered,
                                                        nonsignaling)       */
#define _CMP_ORD_S     0x17  /* Ordered (signaling)                         */
#define _CMP_EQ_US     0x18  /* Equal (unordered, signaling)                */
#define _CMP_NGE_UQ    0x19  /* Not-greater-than-or-equal (unordered,
                                                           nonsignaling)    */
#define _CMP_NGT_UQ    0x1A  /* Not-greater-than (unordered, nonsignaling)  */
#define _CMP_FALSE_OS  0x1B  /* False (ordered, signaling)                  */
#define _CMP_NEQ_OS    0x1C  /* Not-equal (ordered, signaling)              */
#define _CMP_GE_OQ     0x1D  /* Greater-than-or-equal (ordered,
                                                       nonsignaling)        */
#define _CMP_GT_OQ     0x1E  /* Greater-than (ordered, nonsignaling)        */
#define _CMP_TRUE_US   0x1F  /* True (unordered, signaling)                 */
```

File: src/coreclr/src/jit/hwintrinsicxarch.cpp (hunk 5 above)
Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsicxarch.cpp:1203]: Yes. `Avx` has direct support for the comparison while `Sse` has to emulate it by doing a different comparison with flipped arguments (and possibly accounting for "copy upper bits")

File: src/coreclr/tests/src/Regressions/coreclr/GitHub_34094/test34094.cs (hunk 6 above)
Comment (tannergooding) [reply src/coreclr/tests/src/Regressions/coreclr/GitHub_34094/test34094.cs:1]: This was just hand written since its a regression test, there is no template.

File: src/coreclr/src/jit/hwintrinsicxarch.cpp [hunk 7]
```diff
@@ -1173,19 +1173,209 @@ GenTree* Compiler::impBaseIntrinsic(NamedIntrinsic        intrinsic,
...
+    int       simdSize = HWIntrinsicInfo::lookupSimdSize(this, intrinsic, sig);
+    var_types baseType = TYP_UNKNOWN;
 
     // The Prefetch and StoreFence intrinsics don't take any SIMD operands
     // and have a simdSize of 0
     assert((simdSize == 16) || (simdSize == 0));
 
     switch (intrinsic)
     {
+        case NI_SSE_CompareGreaterThan:
```
Comment (CarolEidt) [inline src/coreclr/src/jit/hwintrinsicxarch.cpp:1188]: Since these cases are all basically the same, with different constants, it would seem that you could add a function to determine the constant to use for the AVX intrinsic, based on the constant associated with the SSE intrinsic. Does that make sense or am I missing something?

**Review by CarolEidt — APPROVED** [review]
LGTM - I just had a question about whether it could be simplified.

File: src/coreclr/src/jit/hwintrinsicxarch.cpp (hunk 7 above)
Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsicxarch.cpp:1188]: Yes, we probably could define a `getInverseFloatingComparison` method or something similar. A similar function could also be useful in lowering as it would allow either operand to be contained.

Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsicxarch.cpp:1271]: I added a new function `HWIntrinsicInfo::lookupFloatingComparisonForSwappedArgs` and cleaned up the importation logic.

**Comment by tannergooding** [comment]
The formatting patch was suggesting some odd changes, so I've attempted to manually fix it. It was suggesting:
```diff
-#define _CMP_NLE_US    0x06  /* Not-less-than-or-equal (unordered,
-                                                        signaling)          */
+#define _CMP_NLE_US                                                                                                    \
+    0x06 /* Not-less-than-or-equal (unordered,                                                          \ \ \ \ \ \ \  \
+            \                                                                                                          \
+                                    signaling)          */
```

And then on the subsequent run it suggested:
```diff
 #define _CMP_NLE_US                                                                                                    \
     0x06 /* Not-less-than-or-equal (unordered,                                                          \ \ \ \ \ \ \  \
             \                                                                                                          \
+            \ \                                                                                                                     \
+            \ \ \                                                                                                                     \
+            \ \ \ \                                                                                                                     \
+            \ \ \ \ \                                                                                                                     \
+            \ \ \ \ \ \                                                                                                                     \
+            \ \ \ \ \ \ \                                                                                                                     \
+            \ \ \ \ \ \ \ \                                                                                                                     \
+            \ \ \ \ \ \ \ \ \                                                                                                                     \
+            \ \ \ \ \ \ \ \ \ \                                                                                                                     \
                                     signaling)          */
```

**Comment by BruceForstall** [comment]
You can disable the formatter around this section if that makes the most sense.

File: src/coreclr/src/jit/hwintrinsic.h [hunk 8]
```diff
@@ -315,6 +316,41 @@ struct HWIntrinsicInfo
     }
 };
 
+#if defined(TARGET_XARCH)
+#define _CMP_EQ_OQ 0x00    /* Equal (ordered, nonsignaling) */
```
Comment (BruceForstall) [inline src/coreclr/src/jit/hwintrinsic.h:320]: This seems like strange naming. Did you copy/paste from some other location? Should there be a comment about which location?

Would it be better to give them a better name prefix than `_CMP`? Or put them all in an `enum` instead of using `#define`?

Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsic.h:320]: This is the naming of the comparison values used by the C++ Hardware Intrinsics where they are already defines.
For Windows, they are already included/available, but on Unix they aren't available without including `immintrin.h` and enable AVX support in the compilation (which we can't do).

We use different names, with a proper enum, on the C# side, but document them mapping to the C++ names: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/X86/Enums.cs

Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsic.h:320]: I think using the existing C++ names makes the most sense, but we can't easily use those names in anything other than a `#define` due to other code potentially already defining them with the same values.

Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsic.h:325]: I added the following comment for now:
```
// These use the same names as defined by the C++ HWIntrinsics. They are
// already defined/available on Windows but aren't available on Unix
// without including immintrin.h and enabling AVX in the compilation, so
// we will just redefine them here with the same values.
```

Comment (echesakovMSFT) [reply src/coreclr/src/jit/hwintrinsic.h:325]: > I think using the existing C++ names makes the most sense, but we can't easily use those names in anything other than a #define due to other code potentially already defining them with the same values.

Can we "port" the `enum` from the C# file you pointed out and document the values in the way?
```suggestion
enum class FloatComparisonMode : int
{
  OrderedEqualNonSignaling = 0, // _CMP_EQ_OQ 
  OrderedLessThanSignaling = 1, // _CMP_LT_OS
...
}
#define _CMP_EQ_OQ 0x00    /* Equal (ordered, nonsignaling) */
```

Comment (tannergooding) [reply src/coreclr/src/jit/hwintrinsic.h]: Changed to mirroring the FloatComparisonMode enum.

Comment (echesakovMSFT) [reply src/coreclr/src/jit/hwintrinsic.h]: Thanks - looks much more readable now!

Nit: we don't use xml comments in c++
```c++
    /// <summary> 
    /// _CMP_EQ_OQ 
    /// </summary>
```

**Review by echesakov — APPROVED** [review]
LGTM (minus comment about C++ comments :) )
