### PR TITLE
JIT: ensure AVX512 ternary operands aren't used twice

### LINKED ISSUE #91796: Assertion failed '!"Duplicate gtTreeID was found"' during 'Importation'
Repro file:

[TestClass22-test-assertion.g.cs.txt](https://github.com/dotnet/runtime/files/12560459/TestClass22-test-assertion.g.cs.txt)

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Don't spill unused zeros early; we might decide to use them later.

Fixes #91796.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@tannergooding PTAL
cc @dotnet/jit-contrib

File: src/coreclr/jit/hwintrinsicxarch.cpp [hunk 1]
```diff
@@ -3602,17 +3602,19 @@ GenTree* Compiler::impSpecialIntrinsic(NamedIntrinsic        intrinsic,
                     op2 = impSIMDPopStack();
                     op1 = impSIMDPopStack();
 
-                    if (unusedVal1)
+                    // Consume operands we won't use, in case they have side effects.
+                    //
```
Comment (teo-tsirpanis) [inline src/coreclr/jit/hwintrinsicxarch.cpp:3606]:
```suggestion
```

**Comment by AndyAyersMS** [comment]
SPMI failure is #91838.

**Review by tannergooding — APPROVED** [review]
