### PR TITLE
ARM64: Fix the alignment for Vector64 to 8 bytes

### LINKED ISSUE #37429: ARM64: Investigate why more stack space is allocated than needed and why they are not aligned
This was brought to the attention by @TamarChristinaArm in https://github.com/dotnet/runtime/pull/37139#issuecomment-635892020. For a method that takes 2 `Vector64<>` parameters, there are couple of problems:
1. We allocate stack space of 48 bytes although we just want to store 16 bytes. 
2. The 16 bytes that is stored are not aligned properly. If they are aligned properly, we can convert it tp `stp` instead. 

Here is the sample code:
```
G_M35607_IG01:
        A9BD7BFD          stp     fp, lr, [sp,#-48]!
        910003FD          mov     fp, sp
        FD0017A0          str     d0, [fp,#40]
        FD000FA1          str     d1, [fp,#24]
						;; bbWeight=1    PerfScore 3.50
G_M35607_IG02:
        FD4017B0          ldr     d16, [fp,#40]
        FD400FB1          ldr     d17, [fp,#24]
        0EB01E10          mov     v16.8b, v16.8b
```

Here is the assembly code for reference: [Create_after.txt](https://github.com/dotnet/runtime/files/4698903/Create_after.txt)

### PR DESCRIPTION
**Pull request by kunalspathak**
Fix the alignment for `Vector64` on ARM64 to be 8-bytes instead of 16-bytes.

```csharp
private static Vector128<int> int_Create(Vector64<int> lower, Vector64<int> upper)
{
    return Vector128.Create(lower, upper);
}
```

Before, we were creating the following:
```asm
G_M60438_IG01:
        A9BD7BFD          stp     fp, lr, [sp,#-48]!
        910003FD          mov     fp, sp
        FD0017A0          str     d0, [fp,#40]
        FD000FA1          str     d1, [fp,#24]
                                                ;; bbWeight=1    PerfScore 3.50
G_M60438_IG02:
        FD4017B0          ldr     d16, [fp,#40]
        FD400FB1          ldr     d17, [fp,#24]
        4E083E20          umov    x0, v17.d[0]
        4E181C10          ins     v16.d[1], x0
        4EB01E00          mov     v0.16b, v16.16b
                                                ;; bbWeight=1    PerfScore 6.50
G_M60438_IG03:
        A8C37BFD          ldp     fp, lr, [sp],#48
        D65F03C0          ret     lr
```

Now, we don't allocate lot of stack space:
```asm
G_M60438_IG01:
        A9BE7BFD          stp     fp, lr, [sp,#-32]!
        910003FD          mov     fp, sp
        FD000FA0          str     d0, [fp,#24]
        FD000BA1          str     d1, [fp,#16]
                                                ;; bbWeight=1    PerfScore 3.50
G_M60438_IG02:
        FD400FB0          ldr     d16, [fp,#24]
        FD400BB1          ldr     d17, [fp,#16]
        4E083E20          umov    x0, v17.d[0]
        4E181C10          ins     v16.d[1], x0
        4EB01E00          mov     v0.16b, v16.16b
                                                ;; bbWeight=1    PerfScore 6.50
G_M60438_IG03:
        A8C27BFD          ldp     fp, lr, [sp],#32
        D65F03C0          ret     lr
                                                ;; bbWeight=1    PerfScore 2.00
```

Fixes: https://github.com/dotnet/runtime/issues/37429

### CODE REVIEW

File: src/coreclr/src/jit/simd.cpp [hunk 1]
```diff
@@ -97,7 +98,9 @@ int Compiler::getSIMDTypeAlignment(var_types simdType)
         return 32;
     }
 #elif defined(TARGET_ARM64)
-    return 16;
+    // preferred alignment for 64-bit vectors is 8-bytes.
+    // For everything else, 16-bytes.
+    return (size == 8) ? 8 : 16;
```
Comment (tannergooding) [inline src/coreclr/src/jit/simd.cpp:103]: For reference, the actual alignment of the ABI types is here: <https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/methodtablebuilder.cpp#L9541-L9580>
We can't necessarily get this info from the VM because `Vector2`/`Vector3`/`Vector4`, and `Vector<T>` aren't classified as the ABI types, but we still align them as such if they are on the stack.

**Comment by kunalspathak** [comment]
@CarolEidt , @dotnet/jit-contrib

**Review by tannergooding — APPROVED** [review]
Looks correct to me and matches what I read from the ABI specs.

**Review by CarolEidt — APPROVED** [review]
LGTM - thanks!
