### PR TITLE
Console.ReadKey should print a char, not an integer

### LINKED ISSUE #66596: [WebToolsE2E] Running console app 7.0 with the code "Console.ReadKey();" in Program.cs, an extra "13" appears in the command prompt.
REGRESSION INFO: Doesn't repro in .NET 6.0
REPRO CONFIGURATION: Win10 x64 ENU 20H1 + Dev17.2 Preview 1 VSP + .NET 7.0 + Private feed

.NET Core SDK (CLI) Version: 7.0.100-preview.1.22101.1
Latest .NET Core runtime Version: 7.0.0-preview.1.22076.8

TESTCASES AFFECTED
[[7.0] SimpleConsoleAppOnCoreWithClassLib](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VS/AspNetCore30/30_SimpleConsoleAppOnCoreWithClassLib.md)

INSTALL STEP
1. Clean machine: Win10 x64 ENU 20H1
2. Install Dev17.2 Preview 1 [[d17.2-32209.124](https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build/results?buildId=5731965&view=results)] VSP
Select Web workload + .NET Desktop workload
Under 'Optional', check all the checkboxes
Check .NET Core 5.0/3.1/2.1 runtime under IC tab
3. Install .NET 7.0 from: [Pipelines - Run 20220201.1-7.0.100-preview.1.22101.1-125159 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=1584931&view=artifacts&pathAsName=false&type=publishedArtifacts)
4. Apply Feed: [https://pkgs.dev.azure.com/dnceng/public/_packaging/7.0.100-preview.1.22101.1-shipping/nuget/v3/index.json](https://pkgs.dev.azure.com/dnceng/public/_packaging/7.0.100-preview.1.22101.1-shipping/nuget/v3/index.json)

REPRO STEPS
1. File > New project > C# > Console App > .NET 7.0 (Preview) > Create
2. Open Program.cs, add Console.ReadKey(); in row 3.
3. F5

ACTUAL

image

EXPECTED

image

### PR DESCRIPTION
**Pull request by adamsitnik**
fixes #66596 which got introduced in #52740

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs [hunk 1]
```diff
@@ -16,7 +16,7 @@ internal struct KeyEventRecord
         internal short repeatCount;
         internal short virtualKeyCode;
         internal short virtualScanCode;
-        internal ushort uChar; // Union between WCHAR and ASCII char
+        internal char uChar; // Union between WCHAR and ASCII char
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs:19]: I think it would look better to keep it as `ushort` and cast it as necessary. It avoids any ambiguity for interop marshaling. @elinor-fung @jkoritzinsky What do you think?

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs [hunk 2]
```diff
@@ -16,7 +16,7 @@ internal struct KeyEventRecord
         internal short repeatCount;
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs:16]: Unrelated nit: The name of this struct should be `KEY_EVENT_RECORD` to follow the coding conventions.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs [hunk 3]
```diff
@@ -16,7 +16,7 @@ internal struct KeyEventRecord
...
         internal short virtualKeyCode;
```
[the remark this answers is not in the document]
Comment (jkotas) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs:17]: (similar for the other fields)

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs (hunk 1 above)
Comment (elinor-fung) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs:19]: Agreed - would prefer to keep it as `ushort` for interop and cast as needed.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs [hunk 4]
```diff
@@ -8,24 +8,26 @@ internal static partial class Interop
...
-        internal short repeatCount;
-        internal short virtualKeyCode;
-        internal short virtualScanCode;
-        internal ushort uChar; // Union between WCHAR and ASCII char
-        internal int controlKeyState;
+        internal BOOL bKeyDown;
+        internal short wRepeatCount;
+        internal short wVirtualKeyCode;
+        internal short wVirtualScanCode;
+        private short _uChar; // Union between WCHAR and ASCII char
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs:18]:
```suggestion
        internal ushort wRepeatCount;
        internal ushort wVirtualKeyCode;
        internal ushort wVirtualScanCode;
        private ushort _uChar; // Union between WCHAR and ASCII char
```
to match https://docs.microsoft.com/en-us/windows/console/key-event-record-str

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs [hunk 5]
```diff
@@ -8,24 +8,26 @@ internal static partial class Interop
...
+        internal int dwControlKeyState;
+
+        // _uChar is stored as short to avoid any ambiguity for interop marshaling
+        internal char uChar => (char)_uChar;
     }
 
     // Really, this is a union of KeyEventRecords and other types.
     [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
     internal struct InputRecord
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs:27]:
```suggestion
    internal struct INPUT_RECORD
```

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs [hunk 6]
```diff
@@ -8,24 +8,26 @@ internal static partial class Interop
...
     {
         internal short eventType;
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs:29]:
```suggestion
        internal ushort EventType;
```

**Review by jkotas — APPROVED** [review]

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs [hunk 7]
```diff
@@ -8,24 +8,26 @@ internal static partial class Interop
...
-        internal short virtualKeyCode;
-        internal short virtualScanCode;
-        internal ushort uChar; // Union between WCHAR and ASCII char
-        internal int controlKeyState;
+        internal BOOL bKeyDown;
+        internal ushort wRepeatCount;
+        internal ushort wVirtualKeyCode;
+        internal ushort wVirtualScanCode;
+        private ushort _uChar; // Union between WCHAR and ASCII char
+        internal int dwControlKeyState;
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadConsoleInput.cs:19]:
```suggestion
        internal uint dwControlKeyState;
```
missed this one

File: src/libraries/System.Console/src/System/ConsolePal.Windows.cs [hunk 8]
```diff
@@ -306,20 +306,20 @@ public static bool KeyAvailable
...
             {
-                if (_cachedInputRecord.eventType == Interop.KEY_EVENT)
+                if (_cachedInputRecord.EventType == Interop.KEY_EVENT)
                 {
                     // We had a previous keystroke with repeated characters.
                     ir = _cachedInputRecord;
-                    if (_cachedInputRecord.keyEvent.repeatCount == 0)
-                        _cachedInputRecord.eventType = -1;
+                    if (_cachedInputRecord.keyEvent.wRepeatCount == 0)
+                        _cachedInputRecord.EventType = 0;
```
Comment (adamsitnik) [inline src/libraries/System.Console/src/System/ConsolePal.Windows.cs:319]: I've changed the value to `0` from `-1` but it should be OK as all usages of this field are:

```cs
if (_cachedInputRecord.EventType == Interop.KEY_EVENT) // 1
{
}
else // 0, -1 and all other values
{
}
```

**Review by stephentoub — APPROVED** [review]
Any way to add a test?  We have a manual tests project for Console as a worst case; would this be caught there?

**Comment by adamsitnik** [comment]
> We have a manual tests project for Console as a worst case; would this be caught there?

In theory yes, because after running each test the user is asked to press `y/n` and when pressing `y` the app was printing `121` instead of `y`:

image

But to be 100% sure I've added a new test:

image

> Any way to add a test? 

I currently don't have a better idea than extending the manual tests. I hope that when I get more familiar with `System.Console` I am going to be able to automate it.
