### PR TITLE
Fix dummy OBJ/BLK/IND nodes.

### LINKED ISSUE #39737: assert failed `!IsDummyUse()` for an `OBJ` under `HWINTRINSIC`.
Try to compile and run the following test (Windows x64, SSE41 supported, tiering disabled, checked Runtime):
```
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System;

class Runtime_39403
{
   
    public static int Main()
    {
        if (Sse41.IsSupported)
        {
            Vector128<int> left = Vector128.Create(1);
            Vector128<int> right = Vector128.Create(2);
            ref var rightRef = ref right;
            Vector128<int> mask = Vector128.Create(3);
            Sse41.BlendVariable(left, rightRef, mask);
        }
        return 100;
    }
}

```

it will fail with:

```
Assert failure(PID 97424 [0x00017c90], Thread: 121580 [0x1daec]): Assertion failed '!IsDummyUse()' in 'Runtime_39403:Main():int' during 'Rationalize IR' (IL size 48)

    File: D:\Sergey\git\runtime\src\coreclr\src\jit\lir.cpp Line: 109
```

That happens because when we delete the dead `Sse41.BlendVariable` we extract side effects from arguments and one of them is:
```
top level assign
Extracted side effects list...
N003 (  9,  6) [000024] ---XG-------              *  OBJ       simd16<System.Runtime.Intrinsics.Vector128`1[Int32]>
N002 (  3,  2) [000023] ------------              \--*  LCL_VAR   byref  V02 loc2
```
that we don't expect to see later.

There are a few things that could be fixed here:
1. the local var in this example should be marked as `lvStackByref`, so `OBJ` can't throw and there is no side effect (however, we can change the test so it is necessary to keep the obj node);
2. replace `OBJ` with null check when extract as a to side effect.

category:correctness
theme:intrinsics
skill-level:intermediate
cost:small

### PR DESCRIPTION
**Pull request by sandreenko**
If an unconsumed `OBJ` or `BLK` node reaches `rationalize` or later phases it fires an assert because we don't know how to produce them.

Such nodes could appear from their parent removal if the parent is a dead store or an unused HWIntrinsic intrinsic.

This PR fixes  #39737, there are other issues that were discovered but they are CQ and don't meet RC1 bar.

Changes:
https://github.com/dotnet/runtime/pull/39824/commits/a1697dedbf7c5c545e97abc1684075c7738ac29d: Add a repro.

https://github.com/dotnet/runtime/pull/39824/commits/0158523f7b20c4166a1e2c0b37cd6aae1b035e9e: Add a helper function `fgTryRemoveNonLocal`.

https://github.com/dotnet/runtime/pull/39824/commits/4ee3da9ab6521dd4dc17046f997fc294cdb70dc2: Fix the issue.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @erozenfeld @dotnet/jit-contrib

File: src/coreclr/src/jit/liveness.cpp [hunk 1]
```diff
@@ -2109,40 +2109,80 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
...
+bool Compiler::fgTryRemoveNonLocal(GenTree* node, LIR::Range* blockRange)
+{
+    assert(!node->OperIsLocal());
+    if (!node->IsValue() || node->IsUnusedValue())
+    {
+        // We are only interested in avoiding the removal of nodes with direct side-effects
+        // (as opposed to side effects of their children).
+        // This default case should never include calls or assignments.
+        assert(!node->OperRequiresAsgFlag() && !node->OperIs(GT_CALL));
+        if (!node->gtSetFlags() && !node->OperMayThrow(this))
```
Comment (sandreenko) [inline src/coreclr/src/jit/liveness.cpp:2169]: That condition was pre-existing but it is not always correct,  lower replaces many `HWIntrinsic` and other nodes as `IND` (for example Vector64.Create) without setting `GTF_IND_NONFAULTING` on these `IND` nodes. If you call `fgDebugCheckFlags` on such `IND` that is not marked as `X` and not marked `GTF_IND_NONFAULTING` it would fail.

A better condition would be `if (!node->gtSetFlags() && (!node->OperMayThrow(this)) || ((node->gtFlags & GTF_EXCEPT) == 0)` but such fix doesn't produce many positive diffs, so I would wait for 
https://github.com/dotnet/runtime/issues/10249 to show all such places and then fix the root cause, not the side-effects.

File: src/coreclr/src/jit/liveness.cpp [hunk 2]
```diff
@@ -2109,40 +2109,80 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
...
+//   side effects.
+//
+// Arguments
+//    node       - the non-local node to try;
+//    blockRange - the block range that contains the node.
+//
+// Return value:
+//    None
+//
+// Notes: local nodes are processed independently and not-expected in this funtion.
```
Comment (erozenfeld) [inline src/coreclr/src/jit/liveness.cpp:2158]:
```suggestion
// Notes: local nodes are processed independently and are not expected in this function.

File: src/coreclr/src/jit/liveness.cpp [hunk 3]
```diff
@@ -2109,40 +2109,80 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
...
+//
+bool Compiler::fgTryRemoveNonLocal(GenTree* node, LIR::Range* blockRange)
+{
+    assert(!node->OperIsLocal());
+    if (!node->IsValue() || node->IsUnusedValue())
+    {
+        // We are only interested in avoiding the removal of nodes with direct side-effects
```
Comment (erozenfeld) [inline src/coreclr/src/jit/liveness.cpp:2165]:
```suggestion
        // We are only interested in avoiding the removal of nodes with direct side effects

File: src/coreclr/src/jit/liveness.cpp (hunk 1 above)
Comment (erozenfeld) [reply src/coreclr/src/jit/liveness.cpp:2169]: I believe in LIR `GTF_EXCEPT` is not supposed to capture children side effects. What happens if you use `if (!node->gtSetFlags()  && ((node->gtFlags & GTF_EXCEPT) == 0)` here?

File: src/coreclr/src/jit/liveness.cpp [hunk 4]
```diff
@@ -2109,40 +2109,80 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
...
-                        DISPNODE(node);
-
-                        node->VisitOperands([](GenTree* operand) -> GenTree::VisitResult {
-                            operand->SetUnusedValue();
-                            return GenTree::VisitResult::Continue;
-                        });
-
-                        blockRange.Remove(node);
-                    }
+                    // IR doesn't expect dummy uses of `GT_OBJ/BLK/DYN_BLK`.
```
Comment (erozenfeld) [inline src/coreclr/src/jit/liveness.cpp:2130]: Is it ok to have a dummy use of `GT_IND`?

**Comment by erozenfeld** [comment]
Any diffs from this change?

**Comment by sandreenko** [comment]
> Any diffs from this change?

No, there were a few functions with JitDump changes, but there were about `OBJ SIMD`->`NULLCHECK SIMD` and did not lead to a different asm.

File: src/coreclr/src/jit/liveness.cpp (hunk 1 above)
Comment (sandreenko) [reply src/coreclr/src/jit/liveness.cpp:2169]: > I believe in LIR GTF_EXCEPT is not supposed to capture children side effects

Yes, but we don't check it and right now many parent nodes are having `GTF_EXCEPT` from children, so with `if (!node->gtSetFlags() && ((node->gtFlags & GTF_EXCEPT) == 0)` we are keeping many null checks that we can delete.

File: src/coreclr/src/jit/liveness.cpp (hunk 4 above)
Comment (sandreenko) [reply src/coreclr/src/jit/liveness.cpp:2130]: Yes, lower and rationalize tolerate that even for struct `IND`:
```
void Lowering::LowerIndir(GenTreeIndir* ind)
{
    assert(ind->OperIs(GT_IND, GT_NULLCHECK));
    // Process struct typed indirs separately unless they are unused;
    // they only appear as the source of a block copy operation or a return node.
    if (!ind->TypeIs(TYP_STRUCT) || ind->IsUnusedValue())
```

File: src/coreclr/src/jit/liveness.cpp [hunk 5]
```diff
@@ -2109,40 +2109,80 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
...
+                    node->ChangeType(TYP_BYTE);
+                    node->ChangeOper(GT_NULLCHECK);
+                    block->bbFlags |= BBF_HAS_NULLCHECK;
+                    optMethodFlags |= OMF_HAS_NULLCHECK;
```
Comment (erozenfeld) [inline src/coreclr/src/jit/liveness.cpp:2134]: We should probably factor this to a helper, e.g., `ChangeOperToNullCheck` but it can be done in a separate PR.

**Review by erozenfeld — APPROVED** [review]
LGTM

File: src/coreclr/src/jit/liveness.cpp (hunk 5 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/liveness.cpp:2134]: I don't think this matters, but `Lowering` may change these to `GT_IND` because that produces better code for some cases.

File: src/coreclr/src/jit/liveness.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/liveness.cpp:2169]: When you say "it is not always correct" you mean that it is overly conservative, correct?
It seems to me that the better approach would be to fix the setting of `GTF_IND_NONFAULTING`.

**Review by CarolEidt — APPROVED** [review]
LGTM

File: src/coreclr/src/jit/liveness.cpp (hunk 5 above)
Comment (sandreenko) [reply src/coreclr/src/jit/liveness.cpp]: Yes, I saw that code, unconsumed `IND` are fine, we had asserts only about `OBJ/BKJ/DYN_BLK`.

Comment (CarolEidt) [reply src/coreclr/src/jit/liveness.cpp]: Right - my point was that it might be nice to avoid having to transform multiple times, but neither do we want to duplicate the determination of which form to use.

File: src/coreclr/src/jit/liveness.cpp (hunk 1 above)
Comment (sandreenko) [reply src/coreclr/src/jit/liveness.cpp:2166]: > When you say "it is not always correct" you mean that it is overly conservative, correct?

Yes.

> It seems to me that the better approach would be to fix the setting of GTF_IND_NONFAULTING.

Agree, I should have said "a better temporary hack", I think we should set `GTF_IND_NONFAULTING` for 6.0 after  #10249

File: src/coreclr/src/jit/compiler.cpp [hunk 6]
```diff
@@ -9285,3 +9285,19 @@ bool Compiler::lvaIsOSRLocal(unsigned varNum)
 
     return false;
 }
+
+//------------------------------------------------------------------------------
+// gtChangeOperToNullCheck: helper to change tree oper with a NULLCHECK.
```
Comment (erozenfeld) [inline src/coreclr/src/jit/compiler.cpp:9290]:
```suggestion
// gtChangeOperToNullCheck: helper to change tree oper to a NULLCHECK.

File: src/coreclr/src/jit/compiler.cpp [hunk 7]
```diff
@@ -9285,3 +9285,19 @@ bool Compiler::lvaIsOSRLocal(unsigned varNum)
...
+//
+// Arguments:
+//    tree       - the node to change;
```
Comment (erozenfeld) [inline src/coreclr/src/jit/compiler.cpp:9293]:
```suggestion
//    tree       - The node to change;

**Review by erozenfeld — APPROVED** [review]
LGTM with a couple of comment nits. Thank you for the refactoring.
