### PR TITLE
Methods on primitives 65707

### LINKED ISSUE #65670: [wasm][debugger] Support optional parameters in external methods
Sample external function with optional parameter:
public string[] Split (char separator, int count, StringSplitOptions options = System.StringSplitOptions.None);

Reproduction:
```
var strToSplit = "ab-cd";
```

How to test in debugger watch:
`strToSplit.Split('-', 1);`
`strToSplit.Split('-', 1,  System.StringSplitOptions.None);`
Test in OnCallFrameTests:
`EvaluateMethodWithLinq`

How to fix:
`GetMethodInfo` should return not-null value for external methods. Either fix loading symbols https://github.com/dotnet/runtime/blob/4fd5132c1fb8292e2d94ad4a1b2fe62357205402/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L1081 or fix saving and extracting method: https://github.com/dotnet/runtime/blob/4fd5132c1fb8292e2d94ad4a1b2fe62357205402/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L781.

Make sure that Linq functions work both in headless mode in tests and manually in browser.

### LINKED ISSUE #65707: [wasm][debugger] Fix OnFrameCall for methods on variable values
Reproduction code:
```
	private void IncrementCount()
	{
		string str= "ab-cd";
                int num = 12;
	}
```
Evaluate in watch:
str -> "ab-cd" [OK]
str.ToString() -> [FAIL]
num -> 12 [OK]
num.ToString() -> <not available> [FAIL]

Source of the problem:
Exception is thrown here: https://github.com/dotnet/runtime/blob/976428fa4778faa3257b9cd7d6d3ea76a43410a0/src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs#L390
because we are not setting any ID for variable values here:
https://github.com/dotnet/runtime/blob/976428fa4778faa3257b9cd7d6d3ea76a43410a0/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L1888
so the rootObject looks e.g. like this:
```
{{
  "type": "string",
  "value": "ab-cd",
  "description": "ab-cd"
}}
```
We need the variable ID to get the type of evaluated variable and see what methods it has to choose right method ID.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/65707 and
fixes https://github.com/dotnet/runtime/issues/65670.
If a result is an array, it enables to get its properties.

Before: evaluation of methods on a primitive value in debugger window did not work, threw "cannot evaluate".
Now: we are getting a proper reply for most of cases with exceptions listed below. To achieve it, we are replacing variables in evaluated script, which means we are appending at the beginning a list of used variables in a form: 
```
type valueName = value;
...
user'sScriptWhereValueNamesAreUsed()
```
and running to script to get the result that we want to return to the user.

Does not fix:
ToList in: someString.Split(".", 2, StringSplitOptions.None)**.ToList()**
int_arr**.Length** (https://github.com/dotnet/runtime/issues/66823)
myList + "Asd https://github.com/dotnet/runtime/issues/65707#issuecomment-1048461662

Changes:
- Minor refactoring of naming convention `EvaluateExpression` -> `ExpressionEvaluator` and `FindVariableNMethodCall` -> `ExpressionSyntaxReplacer`, `FindVariableNMethodCall.methodCall` -> `ExpressionSyntaxReplacer.methodCalls`.
- Differentiation of schemes in "object" when replacing variables in script. Before we were using the same way for replacing all variables of "object" type in evaluated script, which resulted in errors for valueTypes.
- Refactoring: merging `ResolveMemberAccessExpressions` and `ResolveIdentifiers` into `Resolve` that iterates through a collection and resolves accessExpression or identifier by a function accepting a single element. It's neater.
- If a method call on a primitive type is detected in `ResolveMethodCalls` we are no longer using the regular procedure of asking the runtime to evaluate it because it would throw an exception - runtime has no means of evaluating objects that have no `objectId`. Instead in `ReplaceMethodCall`, we replace the values used in the script and append them at the beginning to evaluate the expression on the debugger side.
- Supporting `boolean` return type. Before we were treating boolean as a complex object after evaluating an expression . We granted it "object" type in `ConvertCSharpToJSType`. Thus, we had to use TObject in tests when checking the value from a function that returned bool. It was confusing so bool scenario was added in `ConvertCSharpToJSType` and tests were adjusted accordingly.
- Adjusted negative tests because some error messages got changed slightly as the flow changed.
- Differentiation between Enum and Non-Enum in `ValueTypeClass.ToJObject()`. Enum has its value in the first field, even though it does not have fields in the same sense typical ValueType, e.g. structure has. To get the value of Non-Enum we need to additionally ask runtime for this info, so we keep this value null till we need it. We have to save Enum's value there because we will need it during the script's variables replacement procedure.
- Saving the full className in `FindStaticMemberInType` (full = with namespace) because we need it for Enums in `ConvertJSToCSharpLocalVariableAssignment` to construct `valueRet` correctly. If we cut the namespace the script will throw during compilation because script will not be able to cast integer to Enum - it will not recognise the Enum's name as correct.

### CODE REVIEW

**Review by radical — CHANGES_REQUESTED** [review]
In the current state, this is very hard to read, mainly due to the `EvaluationExpression.cs` being split. I suggest either moving the split into a separate PR, or redo the commits, so the first one is just the split, with no other changes. And then the other commits on top of that. That would allow seeing what exactly is being changed.

File: src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs [hunk 1]
```diff
@@ -359,39 +399,40 @@ internal static async Task<JObject> CompileAndRunTheExpression(string expression
...
 
-                findVarNMethodCall.VisitInternal(expressionTree);
-
-                IList<JObject> methodValues = await ResolveMethodCalls(findVarNMethodCall.methodCall, findVarNMethodCall.memberAccessValues, resolver, token);
+                replacer.VisitInternal(expressionTree);
 
-                syntaxTree = findVarNMethodCall.ReplaceVars(syntaxTree, null, null, methodValues, null);
+                IList<JObject> methodValues = await ResolveMethodCalls(replacer, resolver, token);
+                memberAccessValues = await ResolveMemberAccessExpressions(replacer.memberAccesses, resolver, token);
+                identifierValues = await ResolveIdentifiers(replacer.identifiers, resolver, token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:422]: This will repeat the work for all previous memberAccesses, and identifiers. And it might not even be needed, like if there was no method call on a primitive.

Instead, you can return `(IList<JObject> methodValues, IList<JObject> newMemberAccessValues, IList<JObject> new IdentifierValues)` from `ResolveMethodCalls`. And then use the `memberAccessValues+newMemberAccessValues`, and identifiers, in the call to`ReplaceVars`.

And that would mean that you can remove `UpdateForMethod*`.

File: src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs [hunk 2]
```diff
@@ -436,9 +476,28 @@ private static object ConvertCSharpToJSType(object v, Type type)
...
+                            value = new JArray(arr.Cast<object>().Select((val, idx) => JObject.FromObject(
+                                new
+                                {
+                                    value = ConvertCSharpToJSType(resolver, val, val.GetType()),
+                                    name = $"{idx}"
+                                }))),
+                            description = v.ToString(),
+                            className = type.ToString()
+                        }));
+            }
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:496]: I would suggest moving the bits to support methods returning "objects"/arrays to a follow up PR, so we can get rest of the changes right.

**Review by radical — CHANGES_REQUESTED** [review]

File: src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs [hunk 3]
```diff
@@ -247,14 +249,30 @@ private string ConvertJSToCSharpLocalVariableAssignment(string idName, JToken va
...
-                        typeRet = "object";
+                        DotnetObjectId.TryParse(variable["objectId"], out DotnetObjectId objectId);
+                        switch (objectId?.Scheme)
+                        {
+                            case "valuetype":
+                                {
+                                    typeRet = variable["className"].Value<string>();
+                                    var valueWithouCast = value[0]["value"]["value"].Value<double>();
+                                    valueRet = $"({typeRet}) {valueWithouCast}";
+                                    break;
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:260]: Casting number that decodes enum to its type but now I checked and the cast is really redundant. I'll leave it as e.g.: `valTypeName varName = 0`.

File: src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs [hunk 4]
```diff
@@ -247,14 +249,30 @@ private string ConvertJSToCSharpLocalVariableAssignment(string idName, JToken va
...
                     case "object":
-                        valueRet = "Newtonsoft.Json.Linq.JObject.FromObject(new {"
-                            + $"type = \"{type}\""
-                            + $", description = \"{variable["description"].Value<string>()}\""
-                            + $", className = \"{variable["className"].Value<string>()}\""
-                            + (subType != null ? $", subtype = \"{subType}\"" : "")
-                            + (objectId != null ? $", objectId = \"{objectId}\"" : "")
-                            + "})";
-                        typeRet = "object";
+                        DotnetObjectId.TryParse(variable["objectId"], out DotnetObjectId objectId);
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:252]: I did not want to change the original behavior and there if objectId is null then we just skip it in object. We are not using it anywhere else. So I did the same: if it's null then switch case goes to default where we just skip it. Additional check, e.g. before switch-case seems redundant in this situation.

[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:252]: What scenario would you suggest for `TryParse==false`?

[the remark this answers is not in the document]
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:252]: The same reasons due to which `TryParse` would return false, like badly formatted object id.

File: src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs (hunk 2 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs]: The new PR: https://github.com/dotnet/runtime/pull/67095.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 5]
```diff
@@ -1892,7 +1892,7 @@ public async Task<JObject> CreateJObjectForValueType(MonoBinaryReader retDebugge
             else if (isBoxed && numFields == 1) {
                 return fieldValueType;
             }
-            return CreateJObject<string>(null, "object", description, false, className, $"dotnet:valuetype:{valueTypeId}", null, null, true, true, isEnum == 1);
+            return CreateJObject(valueTypes[valueTypeId].valueTypeJson, "object", description, false, className, $"dotnet:valuetype:{valueTypeId}", null, null, true, true, isEnum == 1);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1895]: `valueTypeJson` here is:
```json
 [
  {
    "value": {
      "type": "number",
      "value": 1,
      "description": "1"
    },
    "writable": true,
    "isOwn": true,
    "name": "value__"
  }
]
```

The whole thing isn't needed, just extract the actual value, and use that, like `valueTypeJson[0]["value"]`.

This is kinda [misusing](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-RemoteObject) the `value` field in the object that we create though. In a follow up PR, we should return a better result object for enums.

File: src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs [hunk 6]
```diff
@@ -272,50 +290,69 @@ private string ConvertJSToCSharpLocalVariableAssignment(string idName, JToken va
...
                 if (value == null)
                     throw new ReturnAsErrorException($"Failed to resolve member access for {methodCall}", "ReferenceError");
+                methodCallValues.Add(value);
+            }
+            return (methodCallValues, maesValues, identifierValues);
 
-                values.Add(value);
+            async Task ReplaceMethodCall(InvocationExpressionSyntax method)
+            {
+                replacer.methodCall.Remove(method);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:339]: Add a comment like:
```csharp
                /*
                    Instead of invoking the method on the primitive type ourselves,
                    we emit a local for the primitive, and emit the the method
                    itself in the script. For example:

                    double test_propUlong_2c64c = 12;
                    return (test_propUlong_2c64c.ToString());
                */
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 7]
```diff
@@ -1330,7 +1330,7 @@ public async Task<List<FieldTypeClass>> GetTypeFields(int typeId, CancellationTo
                 //.Replace("System.Decimal", "decimal")
                 .ToString();
 
-        internal async Task<MonoBinaryReader> GetCAttrsFromType(int objectId, int typeId, string attrName, CancellationToken token)
+        internal async Task<MonoBinaryReader> GetCAttrsFromType(int typeId, string attrName, CancellationToken token)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1333]: Why the change? Needs tests that would fail with `objectId`, and now pass with `typeId`.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 8]
```diff
@@ -1225,15 +1225,15 @@ public async Task<bool> ClearSingleStep(int req_id, CancellationToken token)
...
+        public async Task<JObject> GetFieldValue(int typeId, int fieldId, string fieldName, CancellationToken token)
         {
             using var commandParamsWriter = new MonoBinaryWriter();
             commandParamsWriter.Write(typeId);
             commandParamsWriter.Write(1);
             commandParamsWriter.Write(fieldId);
 
             using var retDebuggerCmdReader = await SendDebuggerAgentCommand(CmdType.GetValues, commandParamsWriter, token);
-            return await CreateJObjectForVariableValue(retDebuggerCmdReader, "", false, -1, false, token);
+            return await CreateJObjectForVariableValue(retDebuggerCmdReader, fieldName, false, -1, false, token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1236]: Needs tests to match, that would fail without `fieldName` being passed.

File: src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs [hunk 9]
```diff
@@ -166,6 +167,8 @@ public SyntaxTree ReplaceVars(SyntaxTree syntaxTree, IEnumerable<JObject> ma_val
                         memberAccessValues[id_name] = value;
                         AddLocalVariableWithValue(id_name, value);
                     }
+                    // do not replace memberAccesses that were already replaced
+                    memberAccesses = new List<MemberAccessExpressionSyntax>();
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:171]: Why exactly is this needed?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 10]
```diff
@@ -366,122 +366,129 @@ public async Task<JObject> Resolve(ElementAccessExpressionSyntax elementAccess,
...
+                return (rootObject, methodName);
+            }
+            catch (Exception ex) when (ex is not ReturnAsErrorException)
+            {
+                throw new Exception($"Unable to evaluate method '{methodName}'", ex);
+            }
+        }
 
-                if (rootObject != null)
+        public async Task<JObject> Resolve(DotnetObjectId objectId, string methodName, InvocationExpressionSyntax method, Dictionary<string, JObject> memberAccessValues, CancellationToken token)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:394]: Keep the signature of the method the same. And call `ResolveInvokationInfo` from here too. This would allow `MemberReferenceResolver` to not lose the ability to resolve a `InvocationExpressionSyntax`.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 11]
```diff
@@ -140,9 +138,11 @@ async Task<JObject> FindStaticMemberInType(string name, int typeId)
...
                         isInitialized = await context.SdbAgent.TypeInitialize(typeId, token);
                     }
-                    var valueRet = await context.SdbAgent.GetFieldValue(typeId, field.Id, token);
-
-                    return await GetValueFromObject(valueRet, token);
+                    var staticFieldValue = await context.SdbAgent.GetFieldValue(typeId, field.Id, name, token);
+                    var valueRet = await GetValueFromObject(staticFieldValue, token);
+                    // we need the full name here
+                    valueRet["className"] = classNameToFind;
+                    return valueRet;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:145]: Why the change? Needs corresponding tests.

**Review by radical — CHANGES_REQUESTED** [review]

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 7 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1333]: Argument `objectId` was never used but passes nevertheless. It was confusing so I removed it. `TypeId` was there all the time

File: src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs (hunk 9 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:171]: Let's assume we not emptying the list and resolving: `test.propString.Split('*', 3, System.StringSplitOptions.RemoveEmptyEntries)`.
Then here: https://github.com/dotnet/runtime/blob/8e6ab78d84c0053da776f0cb04c7b9f029297301/src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs#L398 we are resolving System.StringSplitOptions.RemoveEmptyEntries. Then, as it's a method call we are entering the `ReplaceVars` method again, now only with `newMemberAccessValues` that has one element: `test.propString` but replacer.memberAccesses have already 2 elements (0: enum, 1: string), so zip will pair them wrong, enum will get the string value and string will be skipped as it does not have a matching value in `ma_values`. That's why we have to clear `memberAccesses` after the first call. 
It should work with `replacer.identifiers` the same way but I could not find a test case to break the current version of code, so I did not add the clean-up there.

Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/ExpressionEvaluator.cs:171]: The best way would be to replace the Lists of SyntaxElement in Replacer with <Key, Value> collections. It would simplify the logic much more and make the code more legible (e.g. no nulls passed into ReplaceVars, just Replacer instance) but it is a target for some separate PR.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 11 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:145]: Without this change this test is failing:
```
DebuggerTests.EvaluateOnCallFrameTests.EvaluateMethodsOnPrimitiveTypesReturningPrimitives [FAIL]
```
for `test.propString.Split('*', 3, System.StringSplitOptions.RemoveEmptyEntries)`
That's why: we are using `className` in `ConvertJSToCSharpLocalVariableAssignment` when casting number to Enum. If we allow className to be "stringSplitOptions", which is the original value returned by Runtime we won't get a valid cast. We needed to somehow get the full name and in this place it's available. This way we are getting "System.StringSplitOptions" in `className`.

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 12]
```diff
@@ -359,55 +411,53 @@ internal static async Task<JObject> CompileAndRunTheExpression(string expression
...
 
             expressionTree = syntaxTree.GetCompilationUnitRoot(token);
             if (expressionTree == null)
                 throw new Exception($"BUG: Unable to evaluate {expression}, could not get expression from the syntax tree");
 
+            var newScript = script.ContinueWith(
+                string.Join("\n", replacer.variableDefinitions) + "\nreturn " + syntaxTree.ToString());
             try
             {
-                var newScript = script.ContinueWith(
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:403]: Actually yes, it cannot throw as long as we are not passing null as both args: code and options. The only option to fail is not to meet asserts in `Script` constructor. Now only `options` arg is null so it's populated with default options by `ContinueWith()`. 

The original reason behind it was to use `newScript.Code` in `CompilationErrorException` message and we cannot reference it when `newScript is null`. But good point - this change is not that necessary. I will just initialize `newScript` with original value and move ContinueWith into try.

**Comment by radical** [comment]
Please expand the PR description to explain what is being done in this PR, and why.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 13]
```diff
@@ -375,125 +377,126 @@ public async Task<JObject> Resolve(ElementAccessExpressionSyntax elementAccess,
...
+                    commandParamsObjWriter.WriteObj(objectId, context.SdbAgent);
+                }
 
-                    List<int> typeIds;
-                    if (objectId.IsValueType)
+                int passedArgsCnt = method.ArgumentList.Arguments.Count;
+                int methodParamsCnt = passedArgsCnt;
+                ParameterInfo[] methodParamsInfo = null;
+                var methodInfo = await context.SdbAgent.GetMethodInfo(methodId, token);
+                if (methodInfo != null) //FIXME: #65670
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:449]: `65670` is about optional params. It doesn't seem related here.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 14]
```diff
@@ -506,19 +506,25 @@ async Task EvaluateOnCallFrameFail(string call_frame_id, params (string expressi
                var id = pause_location["callFrames"][0]["callFrameId"].Value<string>();
 
                var (_, res) = await EvaluateOnCallFrame(id, "this.objToTest.MyMethodWrong()", expect_ok: false );
-               Assert.Contains($"Method 'MyMethodWrong' not found", res.Error["message"]?.Value<string>());
+               Assert.Equal(
+                    $"Method 'MyMethodWrong' not found in type 'DebuggerTests.EvaluateMethodTestsClass.ParmToTest'", 
+                    res.Error["exceptionDetails"]["exception"]["description"]?.Value<string>());
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:511]:
```suggestion
                    res.Error["result"]?["description"]?.Value<string>());
```

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 15]
```diff
@@ -506,19 +506,25 @@ async Task EvaluateOnCallFrameFail(string call_frame_id, params (string expressi
...
 
                (_, res) = await EvaluateOnCallFrame(id, "this.objToTest.MyMethod(1)", expect_ok: false);
-               Assert.Contains("Cannot invoke method 'this.objToTest.MyMethod(1)' - too many arguments passed", res.Error["message"]?.Value<string>());
+                Assert.Equal(
+                    "Unable to evaluate method 'MyMethod'. Too many arguments passed.", 
+                    res.Error["exceptionDetails"]["exception"]["description"]?.Value<string>());
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:516]:
```suggestion
                    res.Error["result"]?["description"]?.Value<string>());
```

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 16]
```diff
@@ -506,19 +506,25 @@ async Task EvaluateOnCallFrameFail(string call_frame_id, params (string expressi
...
 
                (_, res) = await EvaluateOnCallFrame(id, "this.ParmToTestObjNull.MyMethod()", expect_ok: false );
-               Assert.Contains("Expression 'this.ParmToTestObjNull.MyMethod' evaluated to null", res.Error["message"]?.Value<string>());
+               Assert.Equal("Expression 'this.ParmToTestObjNull.MyMethod' evaluated to null", res.Error["message"]?.Value<string>());
 
                (_, res) = await EvaluateOnCallFrame(id, "this.ParmToTestObjException.MyMethod()", expect_ok: false );
-               Assert.Contains("Cannot invoke method 'MyMethod'", res.Error["message"]?.Value<string>());
+               Assert.Contains(
+                    "Cannot evaluate '(this.ParmToTestObjException.MyMethod()\n)'", 
+                    res.Error["exceptionDetails"]["exception"]["description"]?.Value<string>());
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:527]:
```suggestion
                    res.Error["result"]?["description"]?.Value<string>());
```

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 17]
```diff
@@ -506,19 +506,25 @@ async Task EvaluateOnCallFrameFail(string call_frame_id, params (string expressi
...
                Assert.Contains("Unable to evaluate method 'this.CallMethodWithParm(\"1\")'", res.Error["message"]?.Value<string>());
 
                (_, res) = await EvaluateOnCallFrame(id, "this.ParmToTestObjNull.MyMethod()", expect_ok: false );
-               Assert.Contains("Expression 'this.ParmToTestObjNull.MyMethod' evaluated to null", res.Error["message"]?.Value<string>());
+               Assert.Equal("Expression 'this.ParmToTestObjNull.MyMethod' evaluated to null", res.Error["message"]?.Value<string>());
 
                (_, res) = await EvaluateOnCallFrame(id, "this.ParmToTestObjException.MyMethod()", expect_ok: false );
-               Assert.Contains("Cannot invoke method 'MyMethod'", res.Error["message"]?.Value<string>());
+               Assert.Contains(
+                    "Cannot evaluate '(this.ParmToTestObjException.MyMethod()\n)'",
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:526]:
```suggestion
                    "Cannot evaluate '(this.ParmToTestObjException.MyMethod()\n)'",
```

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 18]
```diff
@@ -359,55 +410,54 @@ internal static async Task<JObject> CompileAndRunTheExpression(string expression
...
                 throw new Exception($"BUG: Unable to evaluate {expression}, could not get expression from the syntax tree");
 
+            Script<object> newScript = script;
             try
             {
-                var newScript = script.ContinueWith(
-                    string.Join("\n", findVarNMethodCall.variableDefinitions) + "\nreturn " + syntaxTree.ToString());
-
+                newScript = script.ContinueWith(
+                string.Join("\n", replacer.variableDefinitions) + "\nreturn " + syntaxTree.ToString());
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:454]: indent

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 19]
```diff
@@ -247,75 +249,123 @@ private static string ConvertJSToCSharpLocalVariableAssignment(string idName, JT
...
 
-        private static async Task<IList<JObject>> ResolveMethodCalls(IEnumerable<InvocationExpressionSyntax> methodCalls, Dictionary<string, JObject> memberAccessValues, MemberReferenceResolver resolver, CancellationToken token)
+        private static async Task<(IList<JObject>, IList<JObject>, IList<JObject>)> ResolveMethodCalls(ExpressionSyntaxReplacer replacer, MemberReferenceResolver resolver, CancellationToken token)
         {
-            var values = new List<JObject>();
-            foreach (InvocationExpressionSyntax methodCall in methodCalls)
+            var methodCallValues = new List<JObject>();
+            // used for replacing method call on primitive:
+            var maesValues = new List<JObject>();
+            var identifierValues = new List<JObject>();
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:329]: The maximum number of objects that these can have is == `replacer.methodCalls.Count`, so we can use `new List<JObject>(capacity: numCalls);`. This will make sure that the lists don't need to resize their internal arrays.

**Review by radical — APPROVED** [review]
Other than a few small suggestions, this looks good to me!

**Comment by radical** [comment]
Some cases to fix in *future* PRs:

- `localEnum.toString()`, and  `test.propEnum.ToString()`
- `this.ParmToTestObjException.MyMethod()` - this one fails with:
```
 Script used to compile it:

string this_ParmToTestObjException_fee35 = "System.Exception: error2"; return (this_ParmToTestObjException_fee35.MyMethod() );

(2,43): error CS1061: 'string' does not contain a definition for 'MyMethod' and no accessible extension method 'MyMethod' accepting a first argument of type 'string' could be found (are you missing a u    sing directive or an assembly reference?)
```

 .. but it should fail because `ParmToTestObjException` threw an exception.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 13 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:449]: It's already fixed, I should have removed this comment. The Issue number is correct, we needed optional params support for external functions to run tests on primitive for: str.Split(char, partsCnt, optional_enum: splitType). That's why this is here. This PR turned out to solve this case, so I'm removing this comment.
