### PR TITLE
Ensure Vector256.Dot produces a V256 result

### LINKED ISSUE #88704: VectorDot test failes in codegen
```
19:49:28.347 Running test: JIT/SIMD/VectorDot_ro/VectorDot_ro.dll

Assert failure(PID 5812 [0x000016b4], Thread: 5272 [0x1498]): Assertion failed 'varTypeUsesIntReg(targetType) || (emitTypeSize(targetType) == emitTypeSize(op1Type))' in 'VectorTest:TestEntryPoint():int' during 'Generate code' (IL size 503; hash 0x9bbcab36; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\codegenxarch.cpp Line: 5107
    Image: C:\h\w\A7B3093D\p\corerun.exe
```

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #88704

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib, this resolves #88704 and the last of the outerloop HWIntrinsic related failures. Remaining jitstress failures are in other areas.

File: src/coreclr/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -4462,29 +4462,30 @@ GenTree* Lowering::LowerHWIntrinsicDot(GenTreeHWIntrinsic* node)
                 assert(comp->compIsaSupportedDebugOnly(InstructionSet_AVX));
 
                 // We will be constructing the following parts:
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:4464]: The issue was simply that we were returning a `V128` still when we should've been returning a full `V256`

The old code was basically doing:
```asm
vdpps    ymm0, ymm1, ymm2, -15
vextractf128 xmm1, ymm0, 1
vaddps xmm0, xmm0, xmm1
```

The new code instead does:
```asm
vdpps    ymm0, ymm1, ymm2, -1
vperm2f128 ymm1, ymm0, ymm0, 1
vaddps ymm0, ymm0, ymm1
```

So we have the same general size of code and are simply swapping lower/upper rather than extracting upper, we then do a 256-bit add rather than a 128-bit add.

In a couple edge cases, we do end up with slightly better code due to how the register allocator handles the uses of the clones and so we see a very small -51 bytes disasm improvement.

File: src/coreclr/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -5026,20 +5028,21 @@ GenTree* Lowering::LowerHWIntrinsicDot(GenTreeHWIntrinsic* node)
...
 
-        tmp1 = comp->gtNewSimdGetLowerNode(TYP_SIMD16, tmp1, simdBaseJitType, simdSize);
-        BlockRange().InsertAfter(tmp3, tmp1);
-        LowerNode(tmp1);
+        idx = comp->gtNewIconNode(0x01, TYP_INT);
+        BlockRange().InsertAfter(tmp3, idx);
 
-        tmp2 = comp->gtNewSimdBinOpNode(GT_ADD, TYP_SIMD16, tmp3, tmp1, simdBaseJitType, 16);
-        BlockRange().InsertAfter(tmp1, tmp2);
+        NamedIntrinsic permute2x128 = (simdBaseType == TYP_DOUBLE) ? NI_AVX_Permute2x128 : NI_AVX2_Permute2x128;
```
Comment (EgorBo) [inline src/coreclr/jit/lowerxarch.cpp:5037]: the debug assert only checks AVX: `assert(comp->compIsaSupportedDebugOnly(InstructionSet_AVX));` in this case, should it be updated to avx2?

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/lowerxarch.cpp (hunk 2 above)
Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp:5037]: We have an assert a bit higher up already. We could replicate it here if you really want it to be.
