### PR TITLE
[EventTrace] AddEventPipe filter data parsing

### LINKED ISSUE #102572: It is not possible to pass the ID of the garbage collection when the .NET provider is enabled with the GCHeapCollect(0x800000) keyword
### Description

It is possible to trigger a garbage collection by enabling the .NET runtime provider with the GCHeapCollect(0x800000) keyword and an Informal verbosity. In the payload, an id can provided and it is supposed to be passed to ETW::GCLog::ForceGC(LONGLONG l64ClientSequenceNumber) as a custom collection id; unrelated to the normal incremented one. 
However, this id is not well parsed in the CLR
Discussed with @noahfalk and @brianrob 

### Reproduction Steps

- the payload contains a string such as "id=42" (see [an example](https://github.com/dotnet/diagnostics/blob/main/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeProvider.cs#L63) from the diagnostics client)
- in [provider_invoke_callback](https://github.com/dotnet/runtime/blob/main/src/native/eventpipe/ep-provider.c#L381), this string is stored into a buffer to get rrid of = and ; characters. So, "Id=42" becomes "Id\042\0"
- next, ep_event_filter_desc_init() used that buffer to fill up the 3 fields of the EventFilterDescriptor that is used later (see next step)
```
uint64_t ptr = address of the buffer
uint32_t size = size of the buffer (=6 for id\042\0)
uint32_t type = 0
```
- finally, EtwCallbackCommon receives the filterdata and tries the following to get the collection id:
```
PEVENT_FILTER_DESCRIPTOR FilterData = (PEVENT_FILTER_DESCRIPTOR)pFilterData;
if ((FilterData != NULL) &&
   (FilterData->Type == 1) &&
   (FilterData->Size == sizeof(l64ClientSequenceNumber)))
{
    l64ClientSequenceNumber = *(LONGLONG *) (FilterData->Ptr);
}
```
it will fail because:
-	the received type value is 0
-	the received size is not the size of a 64 bit number
-	the ptr field does not point to the value as 64 bit number (but as a string)

### Expected behavior

I don't know if things are different for ETW but I'm expecting the buffer pointed to by Ptr to be parsed to:
-  extract the key and compare it with a well known string such as "ClientSequenceNumber"
-  extract the value and convert it as a 64 bit number

### Actual behavior

The client sequence number cannot be set

### Regression?

I don't know if it works for .NET Framework

### Known Workarounds

No workaround

### Configuration

I'm reproducing with .NET 8

### Other information

The following code should fix the problem in EtwCallbackCommon():
```
if ((FilterData != NULL) && (FilterData->Type == 0))
{
    // look for the value without checking the provided id
    char* clientSequenceNumberAsString = (char*)FilterData->Ptr;
    clientSequenceNumberAsString += strlen(clientSequenceNumberAsString) + 1;

    // extract the client sequence number from the string
    int result = sscanf_s(clientSequenceNumberAsString, "%u", &l64ClientSequenceNumber, FilterData->Size - (strlen((char*)FilterData->Ptr) + 1));
    if (result == 1)
    {
        //  use the client sequence number
    }
}
```

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes https://github.com/dotnet/runtime/issues/102572

This PR follows-up on https://github.com/dotnet/runtime/pull/102612#discussion_r1649499591 and https://github.com/dotnet/runtime/pull/102612#discussion_r1651605026 by extending the FilterData parsing to cover EventPipe scenarios.

## Testing

Checked the value of  [l64ClientSequenceNumber](https://github.com/dotnet/runtime/blob/6d23ef4d68bbcdb38fdc22218d1073c5083ac6a1/src/coreclr/vm/eventtrace.cpp#L2423) after enabling an EventPipe session with ` dotnet trace collect -n sampleapp --providers "Microsoft-Windows-DotNETRuntime:800000:5:mihw=whim;GCSeqNumber=2024"` and saw `0x7e8`.

### CODE REVIEW

File: src/coreclr/vm/eventtrace.cpp [hunk 1]
```diff
@@ -2328,6 +2328,72 @@ enum CallbackProviderIndex
     DotNETRuntimePrivate = 3
 };
 
+// EventFilterType identifies the filter type used by the PEVENT_FILTER_DESCRIPTOR
+enum EventFilterType
```
Comment (noahfalk) [inline src/coreclr/vm/eventtrace.cpp:2332]: Rather than including the ETW enum I'd focus on values we will accept and what we expect those enumerants to mean. For example:
```suggestion
enum EventFilterType
{
    // data should be pairs of UTF8 null terminated strings all concatenated together.
    // The first element of the pair is the key and the 2nd is the value. We expect one of the
    // keys to be the string "GCSeqNumber" and the value to be a number encoded as text.
    // This is the standard way EventPipe encodes filter values
    StringKeyValueEncoding = 0
    // data should be an 8 byte binary LONGLONG value
    // this is the historic encoding defined by .NET Framework for use with ETW
    LongBinaryClientSequenceNumber = 1
}
```

File: src/coreclr/vm/eventtrace.cpp [hunk 2]
```diff
@@ -2328,6 +2328,72 @@ enum CallbackProviderIndex
...
+        {
+            const char* key = buffer;
+            buffer += strlen(key) + 1;
+
+            if (buffer >= buffer_end)
+                break;
+
+            const char* value = buffer;
+            buffer += strlen(value) + 1;
+
```
Comment (noahfalk) [inline src/coreclr/vm/eventtrace.cpp:2381]: To be safe against a mal-formed buffer we should do a bounds check on the value portion too:
```suggestion
if(buffer > buffer_end)
    break;
```

File: src/coreclr/nativeaot/Runtime/eventtrace.cpp [hunk 3]
```diff
@@ -94,6 +94,42 @@ enum CallbackProviderIndex
...
+    EVENT_FILTER_DESCRIPTOR * FilterData,
+    LONGLONG * pClientSequenceNumber)
+{
+    if (FilterData == NULL)
+        return;
+
+    if (FilterData->Type == ClientSequenceNumber && FilterData->Size == sizeof(LONGLONG))
+    {
+        *pClientSequenceNumber = *(LONGLONG *) (FilterData->Ptr);
+    }
```
Comment (noahfalk) [inline src/coreclr/nativeaot/Runtime/eventtrace.cpp:129]: NativeAOT supports EventPipe too so unless there is particular reason not to I'd support the same parsing options that we have on CoreCLR.

**Review by noahfalk — APPROVED** [review]
Some suggestions inline, but the approach seems good.

File: src/coreclr/nativeaot/Runtime/eventtrace.cpp (hunk 3 above)
Comment (mdh1418) [reply src/coreclr/nativeaot/Runtime/eventtrace.cpp:129]: I left it out since there was a comment that `// NativeAOT currently only supports forcing a GC with ManagedHeapCollectKeyword via ETW`, so this path won't get hit until forcing a GC via EventPipe is supported on NativeAOT. I figured the parsing could be added once/if the EventPipe scenario is supported.

I don't mind adding the parsing, if that is preferred. @LakshanF @elinor-fung do y'all happen to know if NativeAOT will ever support forcing a GC with the keyword via EventPipe?

Comment (noahfalk) [reply src/coreclr/nativeaot/Runtime/eventtrace.cpp:129]: I'm not sure why that limitation is there and I'd be pretty surprised if its fundamental. My guess was that it was omitted just for lack of time to implement/test something.

Comment (brianrob) [reply src/coreclr/nativeaot/Runtime/eventtrace.cpp:129]: Agreed with @noahfalk here.  I suspect this was an exercise in scoping more than anything else.

File: src/coreclr/vm/eventtrace.cpp (hunk 1 above)
Comment (mdh1418) [reply src/coreclr/vm/eventtrace.cpp:2332]: Changed! Thanks

File: src/coreclr/nativeaot/Runtime/eventtrace.cpp (hunk 3 above)
Comment (mdh1418) [reply src/coreclr/nativeaot/Runtime/eventtrace.cpp:121]: Thanks! Added the EventPipe parsing to the nativeaot counterpart.

File: src/native/eventpipe/ep-provider.c [hunk 4]
```diff
@@ -421,7 +421,7 @@ provider_invoke_callback (EventPipeProviderCallbackData *provider_callback_data)
 		if (j < filter_data_len)
 			buffer_size = j + 1;
 
-		ep_event_filter_desc_init (&event_filter_desc, (uint64_t)buffer, buffer_size, 0);
+		ep_event_filter_desc_init (&event_filter_desc, (uint64_t)buffer, buffer_size, /* EventFilterType.EventPipePayload */ 2);
```
[the remark this answers is not in the document]
Comment (mdh1418) [reply src/native/eventpipe/ep-provider.c]: Done, thanks!

File: src/coreclr/nativeaot/Runtime/eventtrace.cpp [hunk 5]
```diff
@@ -94,6 +94,67 @@ enum CallbackProviderIndex
...
+            buffer += key_len + 1;
+
+            if (buffer >= buffer_end)
+                break;
+
+            const char* value = buffer;
+            size_t value_len = strnlen(value, buffer_end - buffer);
+            buffer += value_len + 1;
+
+            if (buffer >= buffer_end)
```
Comment (noahfalk) [inline src/coreclr/nativeaot/Runtime/eventtrace.cpp:140]: I think this should be '>' no? Maybe I have the wrong mental model but this is what I was expecting:
FilterData->Ptr = 0x1000000, pointing to the UTF8 string "GCSeqNumber\025\0"
FilterData->Size = 15
key = 0x1000000
key_len = 11
value = 0x100000c (+12)
value_len = 2
buffer = 0x100000f (+15)
buffer_end = 0x100000f (+15)

**Review by noahfalk — APPROVED** [review]
I think you may have an off-by-one error, but looks good otherwise 👍

File: src/coreclr/nativeaot/Runtime/eventtrace.cpp (hunk 5 above)
Comment (mdh1418) [reply src/coreclr/nativeaot/Runtime/eventtrace.cpp:140]: Ah, you're right, I tricked myself thinking that the break conditions would be the same.
