### PR TITLE
Fix DiagnosticSource to work with NativeAOT

### LINKED ISSUE #75945: [NativeAOT] IndexOutOfRangeException when running under perfview
Stacktrace:
```
---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
System.Diagnostic.Tracing.EventSource.WriteEventWithRelatedActivityIdCore
System.Diagnostic.Tracing.EventSource.WriteEvent
System.Diagnostic.DiagnosticSourceEventSource.FilterAndTransform
System.Diagnostic.DiagnostisListener.AllListenerObservable.OnNewDiagnosticListener
System.Diagnostic.Listener..ctor
System.Net.DiagnosticHandler..ctor
System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun
```

Repro: https://github.com/kshyju/Net7IsolatedHttpApp

### PR DESCRIPTION
**Pull request by eerhardt**
There were 2 problems:

1. The use of MakeGenericType doesn't work when a property is a ValueType. An app will crash when a listener is enabled and DiagnosticSourceEventSource tries writing values.
2. The properties on KeyValuePair were not being preserved correctly, so the Arguments of the DiagnosticSourceEventSource methods were not being serialized correctly.

Add test (and infrastructure) to ensure DiagnosticSource works in a NativeAOT app

Fix #75945

Remaining Tasks:

- [x] Hook the new NativeAotTests up to a CI leg. @MichalStrehovsky @joperezr - thoughts on which leg to hook them up to?

### CODE REVIEW

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs [hunk 1]
```diff
@@ -1407,6 +1434,74 @@ public ValueTypedFetchProperty(Type type, PropertyInfo property) : base(type)
...
+                                // If there's only 1 item, simply return the ToString of that
+                                if (!en.MoveNext())
+                                {
+                                    // Only one value available
+                                    return firstString ?? string.Empty;
+                                }
+
+                                var result = new ValueStringBuilder(stackalloc char[256]);
+
+                                result.Append(firstString);
```
Comment (tarekgh) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs:1485]: firstString.Length can be greater than 256?

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/NativeAotTests/DiagnosticSourceEventSourceTests.cs [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+using System.Diagnostics.CodeAnalysis;
+using System.Diagnostics.Tracing;
+
+/// <summary>
+/// Tests that using writing to a DiagnosticSource writes the correct payloads
+/// to the DiagnosticSourceEventSource.
+/// </summary>
+internal class Program
+{
+    private class TestEventListener : EventListener
```
Comment (tarekgh) [inline src/libraries/System.Diagnostics.DiagnosticSource/tests/NativeAotTests/DiagnosticSourceEventSourceTests.cs:17]: >TestEventListener [](http://example.com/codeflow?start=18&length=17)

Can we add a test cause ValueStringBuilder inside EnumeratePropertyFetch store more than 256 characters?

**Review by tarekgh — APPROVED** [review]
Added a question and test suggestion. LGTM!

**Comment by MichalStrehovsky** [comment]
Cc @LakshanF

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky @joperezr - thoughts on which leg to hook them up to?

Maybe we could hook it up here:

https://github.com/dotnet/runtime/blob/main/eng/pipelines/coreclr/nativeaot-post-build-steps.yml

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs [hunk 3]
```diff
@@ -1355,20 +1352,50 @@ public static PropertyFetch FetcherForProperty(Type? type, string propertyName)
...
                         }
                     }
 
+                    [UnconditionalSuppressMessage("AOT", "IL3050:RequiresDynamicCode",
+                        Justification = "MakeGenericType is only called when IsDynamicCodeSupported is true or only with ref types.")]
+                    private static PropertyFetch CreateEnumeratePropertyFetch(Type type, Type enumerableOfTType)
+                    {
+                        Type elemType = enumerableOfTType.GetGenericArguments()[0];
+#if NETCOREAPP
+                        if (!RuntimeFeature.IsDynamicCodeSupported && elemType.IsValueType)
```
Comment (marek-safar) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs:1366]: Would be better to have only `RuntimeFeature.IsDynamicCodeSupported` check and assert on `elemType.IsValueType` ?

Comment (eerhardt) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs:1366]: I don't believe there is a valid assert we could put on `elemType.IsValueType`. It is valid for it to be either `true` or `false`. (Note my test that I added is `IEnumerable<int>`.)

The reason I'm checking for `IsValueType` is so the behavior/implementation remains the same for `IEnumerable<RefType>` - since it is possible to still call `MakeGenericType` if the Type being passed is a ref type.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs (hunk 1 above)
Comment (eerhardt) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs:1485]: ValueStringBuilder handles growing and allocating as necessary.

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/NativeAotTests/DiagnosticSourceEventSourceTests.cs (hunk 2 above)
Comment (eerhardt) [reply src/libraries/System.Diagnostics.DiagnosticSource/tests/NativeAotTests/DiagnosticSourceEventSourceTests.cs:17]: ValueStringBuilder is used all over the codebase. I don't think this test would be valuable, as ValueStringBuilder is tested in many places.

File: eng/testing/linker/SupportFiles/Directory.Build.props [hunk 4]
```diff
@@ -13,5 +12,8 @@
     <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
     <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
     <NoWarn>$(NoWarn);IL2121</NoWarn>
+
+    <!-- EventSourceSupport is disabled by default with PublishAot=true, so need to enable it here. -->
+    <EventSourceSupport>true</EventSourceSupport>
```
Comment (eerhardt) [inline eng/testing/linker/SupportFiles/Directory.Build.props:17]: @MichalStrehovsky @jkotas - with this change we now have tests ensuring EventSource works (at least in proc) with PublishAot. Do you think in .NET 8 we should re-enable `EventSourceSupport=true` by default? Or do you think we should keep it disabled by default going forward (for size savings?)

Comment (jkotas) [reply eng/testing/linker/SupportFiles/Directory.Build.props:17]: would wait for feedback on the current .NET 7 default before doing more changes.

I think it makes sense to leave it off by default and turn it on only for server app-models in their SDKs.

Comment (MichalStrehovsky) [reply eng/testing/linker/SupportFiles/Directory.Build.props:17]: Agree with Jan. I kind of like the size savings. I would like to see feedback. Re-enabling it is an instant 30% size regression from 7.0 for hello world.

Comment (eerhardt) [reply eng/testing/linker/SupportFiles/Directory.Build.props:17]: FYI - @noahfalk @tommcdon

Comment (noahfalk) [reply eng/testing/linker/SupportFiles/Directory.Build.props:17]: Just curious, how big (in bytes) is 30%? I wouldn't have guessed the savings were such a high percentage but I don't know if that is because I overestimated the size of HelloWorld or underestimated the size of EventSource.

Comment (MichalStrehovsky) [reply eng/testing/linker/SupportFiles/Directory.Build.props:17]: I was off a little bit. It's 2.85 MB to 3.48 MB, so 22%.

**Review by noahfalk — APPROVED** [review]
LGTM, thanks @eerhardt!

File: eng/testing/linker/SupportFiles/Directory.Build.props (hunk 4 above)
Comment (noahfalk) [reply eng/testing/linker/SupportFiles/Directory.Build.props:17]: Interesting, so 650KB is eliminated just by removing EventSource, certainly more than I expected. I'm not planning to look into now, but I am guessing in the future there is some tooling or log that would help us break down the contribution by type or method to better understand the size? Thanks @MichalStrehovsky!

Comment (MichalStrehovsky) [reply eng/testing/linker/SupportFiles/Directory.Build.props:17]: Yes, we have a log and I'm hoping to do some offcycle work to visualize/diff them.

**Comment by eerhardt** [comment]
@MichalStrehovsky @jkotas - are the test failures an existing issue? I tried searching and I can't find any open issues for them.

`runtime (Build Linux arm64 Release NativeAOT)` failures are all System.IO.FileSystem.Tests, which just got enabled in #76146 2 days ago.

```
System.PlatformNotSupportedException : Operation is not supported on this platform.
   at System.IO.Tests.FileSystemTest.mkfifo(String path, Int32 mode) + 0x28
   at System.IO.Tests.File_ExistsAsDirectory.FalseForNonRegularFile() + 0x40
   at System.IO.FileSystem!<BaseAddress>+0x11c8aa4
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0xd4
```

`runtime (Build windows arm64 Release NativeAOT)` failures seem transient: `The process cannot access the file 'D:\a\_work\1\s\artifacts\helix\tests\windows.AnyCPU.Release\System.Runtime.Tests.zip' because it is being used by another process.`

**Comment by jkotas** [comment]
I have not seen failures like this.

"The process cannot access the file 'D:\a\_work\1\s\artifacts\helix\tests\windows.AnyCPU.Release\System.Runtime.Tests.zip' because it is being used by another process." suggests that there is a build race condition.

Also, one of the test failures is:
`System.DllNotFoundException : Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace.`. It looks like a build race condition that mixes of Windows and Linux bits.`

Any chance that the changes in the test infrastructure you have made introduced this build race condition?

**Comment by eerhardt** [comment]
Ah, I see it now. The MSBuild property I added "`TestNativeAot`" conflicts with an existing MSBuild property with the same name, but to mean different things. I'll rename my new one.

> Also, one of the test failures is:
System.DllNotFoundException : Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace..

Where did you see that error? I hadn't seen that one.

**Review by vitek-karas — APPROVED** [review]

File: eng/testing/linker/SupportFiles/Directory.Build.props (hunk 4 above)
Comment (MichalStrehovsky) [inline eng/testing/linker/SupportFiles/Directory.Build.props:17]: Does this enable EventSource for everything always? I've been adding it to only those tests that need it, like so:

https://github.com/dotnet/runtime/blob/d54a47d5fdd2b2c57a88f3e816a3c6d62fdf0fcd/src/libraries/Microsoft.Extensions.Logging.EventSource/tests/Microsoft.Extensions.Logging.EventSource.Tests.csproj#L6

Motivation:
1. Better to test what our customers will be running.
2. Less code to compile == faster CI

**Review by MichalStrehovsky — APPROVED** [review]
Looks great otherwise, thanks!

**Comment by eerhardt** [comment]
@noahfalk @tommcdon @MichalStrehovsky @jkotas - any thoughts on backporting this to net7? We can leave EventSourceSupport off by default. But if someone turns it on, any app that sends an Http request would be broken when a trace was running.

**Comment by MichalStrehovsky** [comment]
The failure mode is pretty bad, but it's mitigated by the fact that it's off by default. Someone needs to opt in and presumably would run into it immediately after opting in. The current theory is that opting into it wouldn't be a mainstream scenario for the appmodels we currently support with Native AOT.

Since it's not a mainstream scenario, I don't know if that meets the bar. It will more likely meet the bar if we have a customer report and then we can service it.

File: eng/testing/linker/SupportFiles/Directory.Build.props (hunk 4 above)
Comment (brianrob) [reply eng/testing/linker/SupportFiles/Directory.Build.props]: I've love to see the results of this.  Agreed with @noahfalk that this is more than I would have expected.  It feels important to describe the diagnostic expectations for native AOT in .NET 8 so that we can determine how this decision fits in.

Comment (MichalStrehovsky) [reply eng/testing/linker/SupportFiles/Directory.Build.props]: There's a similar difference for `PublishTrimmed` as well - the size of managed code goes from 2,718,848 bytes to 3,003,008. So the cost is about 300 kB in IL terms. (The repro steps for both is basically just run `dotnet publish -r win-x64 -c Release` with `-p:PublishTrimmed=true` for trimming or `-p:PublishAot=true` for NativeAOT. Use `-p:EventSourceSupport=false` to enable/disable EventSource.)

For the NativeAOT case a quick breakdown is following.

# Size of code per namespace with EventSource enabled

Namespace | Size of code in bytes
-- | --
System | 414,414
System.Collections.Generic | 246,832
System.Globalization | 128,834
Internal.Runtime.TypeLoader | 128,583
System.Diagnostics.Tracing | 116,975
System.Text | 92,958
Internal.TypeSystem | 85,341
System.Reflection | 40,905
System.Reflection.Runtime.TypeInfos | 36,802
System.Collections.Concurrent | 34,363
System.Reflection.Runtime.General | 31,092
System.Numerics | 30,384
System.Threading | 27,273
Internal.Reflection.Execution | 27,180
System.IO | 26,659
System.Resources | 25,769
System.Reflection.Runtime.MethodInfos | 22,513
System.Runtime | 21,400
System.Runtime.CompilerServices | 20,287
System.Buffers | 20,055

# Size of code per namespace with EventSource disabled

Namespace | Size of code in bytes
-- | --
System | 306,356
System.Collections.Generic | 156,429
Internal.Runtime.TypeLoader | 127,630
System.Globalization | 107,047
System.Text | 86,065
Internal.TypeSystem | 85,341
System.Reflection | 36,931
System.Reflection.Runtime.TypeInfos | 35,576
System.Collections.Concurrent | 34,363
System.Numerics | 30,384
System.Reflection.Runtime.General | 27,776
System.IO | 26,299
Internal.Reflection.Execution | 25,920
System.Resources | 25,445
System.Runtime | 21,336


(This is just namespaces with more than 20 kB of code)

Most of the cost is in transitive dependencies. EventSource has a big transitive closure and depends on a lot of framework code.

I can file an issue if there's interest in reducing the transtive closure.

Comment (eerhardt) [reply eng/testing/linker/SupportFiles/Directory.Build.props]: > Most of the cost is in transitive dependencies. EventSource has a big transitive closure and depends on a lot of framework code.

This tells me that this is the upper bound of the size savings for having EventSource disabled. In a real world app that uses these transitive dependencies, they won't be able to be trimmed. So the size savings of disabling EventSource will be less. For example, 90 kB of size savings is coming from `System.Collections.Generic` which many apps will use. When the app uses those collections, they won't be able to be trimmed anymore, even with EventSource disabled.

Comment (MichalStrehovsky) [reply eng/testing/linker/SupportFiles/Directory.Build.props]: > So the size savings of disabling EventSource will be less. For example, 90 kB of size savings is coming from System.Collections.Generic which many apps will use. When the app uses those collections, they won't be able to be trimmed anymore, even with EventSource disabled

That depends - when thinking about native code, one needs to think about instantiated generic code. For example the costs associated with `System.Collections.Generic.Dictionary`2<System.Type,System.Diagnostics.Tracing.TraceLoggingTypeInfo>` are exclusive to EventSource not matter what the app does.

It's easy to test out theories - just pick a bigger app and see the impact of EventSource. For apps the size of current ASP.NET, an extra 600 kB overhead is negligible either way,

**Comment by akoeplinger** [comment]
@MichalStrehovsky can you try the backport again?
