### PR TITLE
Correct nullable annotation on ICustomTypeDescriptor.GetConverter

### LINKED ISSUE #69229: System.ComponentModel.ICustomTypeDescriptor.GetConverter have incorrect nullable annotation
Interface `System.ComponentModel.ICustomTypeDescriptor` have nullable annotations, but method `GetConverter` is wrongly annotated to return non-null value, while [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.icustomtypedescriptor.getconverter) says it could return `null`:

```
Returns
A TypeConverter that is the converter for this object, or null if there is no TypeConverter for this object
```

I propose to mark return value as nullable. It will be breaking change, but people would get `NullReferenceException` anyway if they wont check for `null`

### PR DESCRIPTION
**Pull request by eerhardt**
The documentation, and even some of our own code, return null for this method. Correcting the nullable annotation to indicate that null can be returned.

Fix #69229

(Note it is probably best to review with whitespace changes ignored, since I moved one type out a level.)

### CODE REVIEW

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs [hunk 1]
```diff
@@ -862,13 +865,13 @@ public static TypeConverter GetConverter([DynamicallyAccessedMembers(Dynamically
...
-        internal static ICustomTypeDescriptor? GetDescriptor(
+        private static DefaultTypeDescriptor GetDescriptor(
             [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type,
             string typeName)
         {
-            ArgumentNullException.ThrowIfNull(type);
+            ArgumentNullException.ThrowIfNull(type, typeName);
 
-            return NodeFor(type).GetTypeDescriptor(type);
+            return NodeFor(type).GetDefaultTypeDescriptor(type);
```
Comment (stephentoub) [inline src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:874]: The code in this new GetDefaultTypeDescriptor is what you would have gotten from the GetTypeDescriptor override that was there before?

**Review by stephentoub — APPROVED** [review]

**Review by tarekgh — APPROVED** [review]

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs (hunk 1 above)
Comment (eerhardt) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:874]: Correct. 

`NodeFor(type)` always returns a private class `TypeDescriptionNode`.

https://github.com/dotnet/runtime/blob/62eb291312749c52507309d50051dd61538cc62d/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L1425

`GetTypeDescriptor(type)` is a non-virtual method on the base `TypeDescriptionProvider` class that forwards to the `GetTypeDescriptor(type, instance)` virtual method:

https://github.com/dotnet/runtime/blob/62eb291312749c52507309d50051dd61538cc62d/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptionProvider.cs#L217-L220

Which is overriden by `TypeDescriptionNode` to always return a `DefaultTypeDescriptor`:

https://github.com/dotnet/runtime/blob/62eb291312749c52507309d50051dd61538cc62d/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L3107-L3117

I wanted to do this for the `GetConverter` method that takes an object instance as well, but couldn't because there it can return either a `DefaultTypeDescriptor` or a `MergedTypeDescriptor`, so I had to continue letting the helper method return `ICustomTypeDescriptor` and added the assert that whomever we called returned non-null from `GetConverter()`.

**Comment by DrewScoggins** [comment]
Improvements: https://github.com/dotnet/perf-autofiling-issues/issues/6852

**Comment by eerhardt** [comment]
> Improvements: https://github.com/dotnet/perf-autofiling-issues/issues/6852

I had suspected that this change would help perf, but I didn't want to jinx it. 😄

**Comment by DrewScoggins** [comment]
Also seeing wins on Arm64: https://github.com/dotnet/perf-autofiling-issues/issues/6861
