### PR TITLE
[tests][mobile] Enable diagnostic_tracing for mobile runtime tests

### LINKED ISSUE #52763: [Mono Android][Test] tracing/eventactivityidcontrol/eventactivityidcontrol fails on Android
tracing/eventactivityidcontrol/eventactivityidcontrol fails on Android for both x64 and arm64

Here is the failure log:

```
3241  3267 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.322  3241  3267 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.322  3241  3267 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.322  3241  3267 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.326  3241  3282 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.326  3241  3282 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.326  3241  3282 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.326  3241  3282 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.327  3241  3284 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.327  3241  3284 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.327  3241  3284 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.327  3241  3284 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.327  3241  3283 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.327  3241  3283 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.327  3241  3283 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.327  3241  3283 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.330  3241  3285 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.330  3241  3285 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.330  3241  3285 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.330  3241  3285 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.333  3241  3286 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.333  3241  3286 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.333  3241  3286 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.333  3241  3286 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.334  3241  3287 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.334  3241  3287 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.334  3241  3287 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.334  3241  3287 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.334  3241  3288 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.334  3241  3288 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.334  3241  3288 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.334  3241  3288 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.335  3241  3289 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.335  3241  3289 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.335  3241  3289 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.335  3241  3289 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.335  3241  3290 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.335  3241  3290 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.335  3241  3290 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.335  3241  3290 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.336  3241  3291 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.336  3241  3291 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.336  3241  3291 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.336  3241  3291 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.343  1585  1662 I RoleManagerService: Granting default roles...
05-13 15:21:00.374  3241  3299 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.374  3241  3299 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.374  3241  3299 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.374  3241  3299 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.374  3241  3300 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.374  3241  3300 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.374  3241  3300 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3300 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3298 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3298 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3298 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3298 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3295 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3295 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3295 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3295 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3292 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3292 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3292 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3292 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3296 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3296 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3296 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3296 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3294 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3294 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3294 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3294 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.376  3241  3297 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.376  3241  3297 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.376  3241  3297 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.376  3241  3297 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3292 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3292 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3292 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3292 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3296 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3296 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3296 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3296 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3294 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3294 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3294 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3294 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3298 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3298 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3298 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3298 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3294 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3294 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3294 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3294 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3297 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3297 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3297 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3297 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3292 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3292 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3292 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3292 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3298 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3298 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3298 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3298 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.386  3241  3299 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.386  3241  3299 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.386  3241  3299 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.386  3241  3299 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.386  3241  3295 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.386  3241  3295 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.386  3241  3295 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.386  3241  3295 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.386  3241  3294 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.386  3241  3294 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.386  3241  3294 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.386  3241  3294 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.386  3241  3296 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.386  3241  3296 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.386  3241  3296 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.386  3241  3296 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.390  3241  3267 D DOTNET  : Exit code: 0.
```

### PR DESCRIPTION
**Pull request by mdh1418**
Before merging this, dotnet/diagnostics needs to be updated to accept a string parameter to the DiagnosticsClient constructor and allow for TCPIP connection. After which, `MicrosoftDiagnosticsNETCoreClientVersion` can be bumped. The tests work locally because a modified manual build of dotnet/diagnostics was used.

This PR looks to stand-up diagnostics tests for mobile, specifically targeting Android. Diagnostics runtime components have been made compatible for mobile platforms, and here, they will be tested and integrated.

The following are changes made:
Includes `diagnostics_tracing` runtime components in `BuildAndroidApp`
Sets the `DiagnosticsPorts` to default to `127.0.0.1:9000,nosuspend,listen`
Fix IpcUtils `GetStandardTransport` to set up TCP/IP connection on Android, connecting to default DiagnosticsPorts
Fixes #52763
Disables `JitOptimizationSensitive` on Android for eventpipe tests

----
With a goal of emulating the diagnostics tracing tests on mono desktop, the following tests now pass locally.

## eventlistener
eventlistener

## eventcounter
eventcounter
pollingcounter
regression-46938
regression-25709
incrementingpollingcounter
runtimecounters
incrementingeventcounter
gh53564

## eventactivityidcontrol
eventactivityidcontrol

----
Of the eventpipe tests, 5 of them will be enabled in a separate PR, and the rest require a significant modification to allow Android to run multiple apps at a time, specifically to allow for RunSubprocess in IpcUtils to work.

name_config_with_pid, reverse, reverseouter, pauseonstart, diagnosticport, processenvironment

### CODE REVIEW

**Comment by fanyang-mono** [comment]
With Steve's latest change to reduce the amount of runtime tests running per PR, I believe that all runtime tests running on mobile targets have been moved to rolling build. You would need to modify the runtime.yml and/or runtime-stage.yml files to validate your change here.

File: src/tests/tracing/eventpipe/common/IpcUtils.cs [hunk 1]
```diff
@@ -446,6 +446,12 @@ public static Stream GetStandardTransport(int processId)
                 namedPipe.Connect(3);
                 return namedPipe;
             }
+            else if (OperatingSystem.IsAndroid())
+            {
+                Int32 port = 9000;
+                TcpClient client = new TcpClient("127.0.0.1", port);
```
Comment (lateralusX) [inline src/tests/tracing/eventpipe/common/IpcUtils.cs:452]: Android emulator doesn't use 127.0.0.1 as its IP (unless you have setup port forwarding using adb). Is that the case? If not, then emulator uses 10.0.2.2 as its loopback interface IP address.

**Review by lateralusX — COMMENTED** [review]
Once this builds and pass, could we also validate that the tests are actually executed on CI as expected?

File: src/tests/tracing/eventpipe/common/IpcUtils.cs (hunk 1 above)
Comment (mdh1418) [reply src/tests/tracing/eventpipe/common/IpcUtils.cs:452]: I has tried using 10.0.2.2 here, but `System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused 10.0.2.2:9000` is hit. I was guessing that this needs to be the same value as `DiagnosticsPort` set in `build.proj`, and my initial attempts to use `10.0.2.2` didn't work there either.
Should `processinfo.cs` fail here when using `GetStandardTransport`?

File: src/tests/tracing/eventpipe/common/IpcUtils.cs [hunk 2]
```diff
@@ -446,6 +446,12 @@ public static Stream GetStandardTransport(int processId)
                 namedPipe.Connect(3);
                 return namedPipe;
             }
+            else if (OperatingSystem.IsAndroid())
+            {
+                Int32 port = 9000;
```
[the remark this answers is not in the document]
Comment (steveisok) [reply src/tests/tracing/eventpipe/common/IpcUtils.cs:451]: @akoeplinger double checking with you.  I *think* we're good.

**Comment by mdh1418** [comment]
Can I get another look over this PR @lateralusX, all the tests in the updated PR description are passing on CI.

File: src/tests/tracing/eventpipe/common/IpcUtils.cs (hunk 1 above)
Comment (lateralusX) [reply src/tests/tracing/eventpipe/common/IpcUtils.cs:452]: We run the client directly on the device for this scenario, so it will be good.

File: src/tests/tracing/eventcounter/eventcounter.csproj [hunk 3]
```diff
@@ -4,7 +4,7 @@
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
     <GCStressIncompatible>true</GCStressIncompatible>
     <!-- This test is timing sensitive and JIT timing affects the results of the test -->
-    <JitOptimizationSensitive>true</JitOptimizationSensitive>
+    <JitOptimizationSensitive Condition="'$(TargetOS)' != 'Android'">true</JitOptimizationSensitive>
```
Comment (lateralusX) [inline src/tests/tracing/eventcounter/eventcounter.csproj:7]: Is this just to get the test running on the Android CoreCLR runtime test configuration? Believe this should be set when we run the runtime tests used the same configuration as we do on OSX, it should set the COM_TieredCompilation=0 as part of running no_tiered_compilation, that in turn should be part of the innerloop configuration, https://github.com/dotnet/runtime/blob/4c662b16e3e6fe688f9bbff2a9423fdee799ecfe/eng/pipelines/runtime.yml#L1062. Similar to what we did in this PR, https://github.com/dotnet/runtime/pull/58106

Having that said it might be equal important to be less dependent on all these configs and since this is not an issue on MonoVM (not running tiered JIT), we could just make sure we run the tests independently.

**Comment by lateralusX** [comment]
@mdh1418 How did you verify that the enabled tests now runs on Android on CI? Are we running the tests on all Android platforms currently tested on CI?

I believe this looks overall good, great to get the test running on mobile platforms.

**Comment by mdh1418** [comment]
> @mdh1418 How did you verify that the enabled tests now runs on Android on CI? Are we running the tests on all Android platforms currently tested on CI?
> 
> I believe this looks overall good, great to get the test running on mobile platforms.

I looked through the Android runtime tests lane on this PR's CI checks `runtime-extra-platforms` and in `PayloadGroup0`, I was able to find all of the tests in https://helix.dot.net/api/jobs/ed8baac3-e67c-47aa-95d8-0376b284f7a3/workitems/PayloadGroup0?api-version=2019-06-17 and looked through the adb log for a successful output of 100.
```
eventlistener
eventcounter
pollingcounter
regression-46938
regression-25709
incrementingpollingcounter
runtimecounters
incrementingeventcounter
gh53564
eventactivityidcontrol
```

However, I only checked that one lane so far `Build Android x64 Release AllSubsets_Mono_RuntimeTests`

File: src/tests/tracing/eventcounter/eventcounter.csproj (hunk 3 above)
Comment (mdh1418) [reply src/tests/tracing/eventcounter/eventcounter.csproj:7]: Good catch. Now that I'm inspecting this, I do believe I had been running the test on Android CoreCLR runtime test configuration. I thought it had been necessary to exclude `JitOptimizationSensitive` to run the test, but I guess its a CoreCLR specific property.

I thought I was running on mono runtime with 
`<reporoot>/build.sh -s mono+libs -os Android -arch x64 -c Debug`
`<reporoot>/src/tests/build.sh /p:LibrariesConfiguration=Debug -excludemonofailures -rebuild mono -os Android debug -test:tracing/eventcounter/eventcounter.csproj`
`<reporoot>/dotnet.sh artifacts/tests/coreclr/Android.x64.Debug/Tests/Core_Root/xunit.console.dll artifacts/tests/coreclr/Android.x64.Debug/tracing/eventcounter/tracing.eventcounter.XUnitWrapper.dll`
But this is hitting `SKIPPING EXECUTION BECAUSE COMPlus_TieredCompilation has not been disabled and this test is marked JitOptimizationSensitive
Test Harness Exitcode is : 0` so it must still be CoreCLR?

I did see `RuntimeFlavor=mono` in some of the console text when building the test, what am I missing to run it as mono? (I'm assuming its not mono if i'm still seeing the output above'
```
Building managed test group 1: "/Users/mdhwang/runtime_droid/dotnet.sh" msbuild /Users/mdhwang/runtime_droid/src/tests/build.proj /t:Build "/p:TargetArchitecture=x64" "/p:Configuration=Debug" "/p:LibrariesConfiguration=Debug" "/p:TargetOS=Android" "/p:RuntimeOS=" "/p:RuntimeFlavor=mono" "/p:RuntimeVariant=" "/p:CLRTestBuildAllTargets=" "/p:__TestGroupToBuild=1" "/p:__SkipRestorePackages=1" /nodeReuse:false /maxcpucount /bl:/Users/mdhwang/runtime_droid/artifacts//log/Debug/InnerManagedTestBuild.1.binlog
  Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
  Copyright (C) Microsoft Corporation. All rights reserved.

  /Users/mdhwang/runtime_droid/.dotnet/sdk/6.0.100/MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/Users/mdhwang/runtime_droid/.dotnet/sdk/6.0.100/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/Users/mdhwang/runtime_droid/.dotnet/sdk/6.0.100/dotnet.dll -maxcpucount /maxcpucount -verbosity:m /bl:/Users/mdhwang/runtime_droid/artifacts//log/Debug/InnerManagedTestBuild.1.binlog /nodeReuse:false /p:TargetArchitecture=x64 /p:Configuration=Debug /p:LibrariesConfiguration=Debug /p:TargetOS=Android /p:RuntimeOS= /p:RuntimeFlavor=mono /p:RuntimeVariant= /p:CLRTestBuildAllTargets= /p:__TestGroupToBuild=1 /p:__SkipRestorePackages=1 /t:Build /Users/mdhwang/runtime_droid/src/tests/build.proj
  Building managed test group 2: "/Users/mdhwang/runtime_droid/dotnet.sh" msbuild /Users/mdhwang/runtime_droid/src/tests/build.proj /t:Build "/p:TargetArchitecture=x64" "/p:Configuration=Debug" "/p:LibrariesConfiguration=Debug" "/p:TargetOS=Android" "/p:RuntimeOS=" "/p:RuntimeFlavor=mono" "/p:RuntimeVariant=" "/p:CLRTestBuildAllTargets=" "/p:__TestGroupToBuild=2" "/p:__SkipRestorePackages=1" /nodeReuse:false /maxcpucount /bl:/Users/mdhwang/runtime_droid/artifacts//log/Debug/InnerManagedTestBuild.2.binlog
  Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
  Copyright (C) Microsoft Corporation. All rights reserved.

  /Users/mdhwang/runtime_droid/.dotnet/sdk/6.0.100/MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/Users/mdhwang/runtime_droid/.dotnet/sdk/6.0.100/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/Users/mdhwang/runtime_droid/.dotnet/sdk/6.0.100/dotnet.dll -maxcpucount /maxcpucount -verbosity:m /bl:/Users/mdhwang/runtime_droid/artifacts//log/Debug/InnerManagedTestBuild.2.binlog /nodeReuse:false /p:TargetArchitecture=x64 /p:Configuration=Debug /p:LibrariesConfiguration=Debug /p:TargetOS=Android /p:RuntimeOS= /p:RuntimeFlavor=mono /p:RuntimeVariant= /p:CLRTestBuildAllTargets= /p:__TestGroupToBuild=2 /p:__SkipRestorePackages=1 /t:Build /Users/mdhwang/runtime_droid/src/tests/build.proj
  Building managed test group 3: "/Users/mdhwang/runtime_droid/dotnet.sh" msbuild /Users/mdhwang/runtime_droid/src/tests/build.proj /t:Build "/p:TargetArchitecture=x64" "/p:Configuration=Debug" "/p:LibrariesConfiguration=Debug" "/p:TargetOS=Android" "/p:RuntimeOS=" "/p:RuntimeFlavor=mono" "/p:RuntimeVariant=" "/p:CLRTestBuildAllTargets=" "/p:__TestGroupToBuild=3" "/p:__SkipRestorePackages=1" /nodeReuse:false /maxcpucount /bl:/Users/mdhwang/runtime_droid/artifacts//log/Debug/InnerManagedTestBuild.3.binlog
  Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
  Copyright (C) Microsoft Corporation. All rights reserved.

  /Users/mdhwang/runtime_droid/.dotnet/sdk/6.0.100/MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/Users/mdhwang/runtime_droid/.dotnet/sdk/6.0.100/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/Users/mdhwang/runtime_droid/.dotnet/sdk/6.0.100/dotnet.dll -maxcpucount /maxcpucount -verbosity:m /bl:/Users/mdhwang/runtime_droid/artifacts//log/Debug/InnerManagedTestBuild.3.binlog /nodeReuse:false /p:TargetArchitecture=x64 /p:Configuration=Debug /p:LibrariesConfiguration=Debug /p:TargetOS=Android /p:RuntimeOS= /p:RuntimeFlavor=mono /p:RuntimeVariant= /p:CLRTestBuildAllTargets= /p:__TestGroupToBuild=3 /p:__SkipRestorePackages=1 /t:Build /Users/mdhwang/runtime_droid/src/tests/build.proj
  ```

Comment (mdh1418) [reply src/tests/tracing/eventcounter/eventcounter.csproj:7]: I'll remove all the associated `JitOptimizationSensitive` exclusions and check CI results again.

> Having that said it might be equal important to be less dependent on all these configs and since this is not an issue on MonoVM (not running tiered JIT), we could just make sure we run the tests independently, would it make sense to look at a more generic property, like runtime flavor when setting this property, that way we don't need to update these with a lot of different conditions when we start to run these tests on all Mono runtime platforms supporting them?

Ah, so instead conditioning `JitOptimizationSensitive` based on `RuntimeFlavor` in each csproj? 

> we could just make sure we run the tests independently

What would this look like?

Comment (mdh1418) [reply src/tests/tracing/eventcounter/eventcounter.csproj]: > I'll remove all the associated `JitOptimizationSensitive` exclusions and check CI results again.

Lane `Build Android x64 Release AllSubsets_Mono_RuntimeTests` results https://helix.dot.net/api/jobs/50218d6c-c030-4a62-947e-7cfb705d399b/workitems/PayloadGroup0?api-version=2019-06-17, I see `SKIPPING EXECUTION BECAUSE COMPlus_TieredCompilation has not been disabled and this test is marked JitOptimizationSensitive
Test Harness Exitcode is : 0`

Comment (lateralusX) [reply src/tests/tracing/eventcounter/eventcounter.csproj]: > Ah, so instead conditioning `JitOptimizationSensitive` based on `RuntimeFlavor` in each csproj?

Yes, I believe not condition them to only Android but to MonoVM would make sense, alternative is to add the condition directly into the target that emits the script:

https://github.com/dotnet/runtime/blob/87777b624b0b8ea295b0fe9cd8505ce262ed75c0/src/tests/Common/CLRTest.Execute.Batch.targets#L96

https://github.com/dotnet/runtime/blob/87777b624b0b8ea295b0fe9cd8505ce262ed75c0/src/tests/Common/CLRTest.Execute.Bash.targets#L99

So adding something like `Condition="'$(RuntimeFlavor)' != 'mono'"` would make sure we run these tests on MonoVM independent on what CI configuration we use and what env variables that ends up setting.

**Comment by lateralusX** [comment]
@mdh1418 Can you verify that the last config in this PR now runs the test on Android? If so I believe this is good to go!

**Comment by mdh1418** [comment]
@lateralusX Just checked the lane `Build Android x64 Release AllSubsets_Mono_RuntimeTests` again, all the respective tests have a successful exit code of 100.

**Review by lateralusX — APPROVED** [review]
