### PR TITLE
Only allocate StringBuilder for complex type names

### LINKED ISSUE #79317: Logger name allocations from ILoggerFactory.CreateLogger<MyClass>()
### Description

As noticed in https://github.com/dotnet/aspnetcore/pull/45480, `CreateLogger<MyClass>()` allocates a StringBuilder + string for the logger name, even for simple cases. For example, `MyClass` is just getting `typeof(MyClass).FullName`.

https://github.com/dotnet/runtime/blob/c6d6b19da5427ae78eab241d2af596a3320a5e5b/src/libraries/Common/src/Extensions/TypeNameHelper/TypeNameHelper.cs#L81

Creating the logger name should avoid using a `StringBuilder` unless necessary. Usually `CreateLogger<T>` is used with a basic type (not nested, not generic, not array, etc). Most of the time `Type.FullName` can be used directly.

### Configuration

.NET 8 alpha

### Regression?

No

### Data

Allocations identified in https://github.com/dotnet/aspnetcore/pull/45480

### PR DESCRIPTION
**Pull request by benaadams**
Resolves https://github.com/dotnet/runtime/issues/79317

### CODE REVIEW

File: src/libraries/Common/src/Extensions/TypeNameHelper/TypeNameHelper.cs [hunk 1]
```diff
@@ -49,9 +49,43 @@ internal static class TypeNameHelper
         /// <returns>The pretty printed type name.</returns>
         public static string GetTypeDisplayName(Type type, bool fullName = true, bool includeGenericParameterNames = false, bool includeGenericParameters = true, char nestedTypeDelimiter = DefaultNestedTypeDelimiter)
         {
-            var builder = new StringBuilder();
-            ProcessType(builder, type, new DisplayNameOptions(fullName, includeGenericParameterNames, includeGenericParameters, nestedTypeDelimiter));
-            return builder.ToString();
+            if (type.IsGenericType)
```
Comment (stephentoub) [inline src/libraries/Common/src/Extensions/TypeNameHelper/TypeNameHelper.cs:52]: Instead of duplicating all of this logic, could:
```C#
private static void ProcessType(StringBuilder builder, Type type, in DisplayNameOptions options)
```
be changed to instead be something like:
```C#
private static string? ProcessType(ref StringBuilder? builder, Type type, in DisplayNameOptions options)
```
where it would append to the builder if it's not null, lazily initialize the builder if it needs to append more than one thing, but if the builder is null and it only has one string then just return it?

Comment (benaadams) [reply src/libraries/Common/src/Extensions/TypeNameHelper/TypeNameHelper.cs]: Updated

File: src/libraries/Common/src/Extensions/TypeNameHelper/TypeNameHelper.cs [hunk 2]
```diff
@@ -49,43 +49,62 @@ internal static class TypeNameHelper
...
 
-        private static void ProcessType(StringBuilder builder, Type type, in DisplayNameOptions options)
+        private static string? ProcessType(ref StringBuilder? builder, Type type, in DisplayNameOptions options)
         {
             if (type.IsGenericType)
             {
                 Type[] genericArguments = type.GetGenericArguments();
+                builder ??= new StringBuilder();
                 ProcessGenericType(builder, type, genericArguments, genericArguments.Length, options);
+
```
Comment (stephentoub) [inline src/libraries/Common/src/Extensions/TypeNameHelper/TypeNameHelper.cs:64]:
```suggestion
```

**Review by stephentoub — APPROVED** [review]
Thanks.  And nice to see you again :)
