### PR TITLE
Fix WASM exception propagation through native runtime

### LINKED ISSUE #122462: [borwser][coreCLR] exception in static constructor
`node .\corerun.js /throwcctor.dll`

```cs
try
{
    Console.WriteLine("Hello, World!");
    Console.WriteLine("BOOM " + XXX.Something);
}
catch (Exception ex)
{
    Console.WriteLine("Caught!");
    Console.WriteLine("Caught : " + ex);
}


class XXX
{
    static XXX()
    {
        Console.WriteLine("Static constructor called.");
        throw new Exception("Exception in static constructor.");
    }

    private static string SomethingField = "Hi";

    public static string Something
    {
        get
        {
            return SomethingField;
        }
    }
}
```

# expected
```
Hello, World!
Static constructor called.
Caught!
Caught : System.TypeInitializationException: The type initializer for 'XXX' threw an exception.
 ---> System.Exception: Exception in static constructor.
   at XXX..cctor() in D:\samples\throwcctor\Program.cs:line 17
   --- End of inner exception stack trace ---
   at XXX.get_Something() in D:\samples\throwcctor\Program.cs:line 25
   at Program.<Main>$(String[] args) in D:\samples\throwcctor\Program.cs:line 4
```

# actual
```
Hello, World!
Static constructor called.
Caught!
Caught : System.Exception: Exception in static constructor.
   at XXX..cctor()
   at XXX.get_Something()
   at Program.<Main>$(String[] args)

Assert failure(PID 42 [0x0000002a], Thread: 1 [0x0001]): The 'LastThrownObject' should not be, but is, NULL.
The runtime may have lost track of the type of an exception in flight.
Please get a good stack trace, find the caller of Validate, and file a bug against the owner.

To suppress this assert 'set DOTNET_SuppressLostExceptionTypeAssert=1'
    File: D:/runtime/src/coreclr/vm/clrex.cpp:2125
    Image: /managed

Aborted(native code called abort())
```

### PR DESCRIPTION
**Pull request by janvorli**
This change fixes propagating managed exceptions into native frames on WASM. It ensures that the exception is ignored in the `UNINSTALL_MANAGED_EXCEPTION_DISPATCHER_EX` until it reaches the target frame. This is necessary because we cannot unwind the stack up to the target frame on WASM unlike other platforms.

I have also removed some obsolete bits from the `PAL_SEHException` class.

Close #122462

### CODE REVIEW

File: src/coreclr/vm/exceptmacros.h [hunk 1]
```diff
@@ -223,11 +223,11 @@ VOID DECLSPEC_NORETURN DispatchManagedException(PAL_SEHException& ex, bool isHar
 #define UNINSTALL_MANAGED_EXCEPTION_DISPATCHER_EX(nativeRethrow) \
         }                                           \
         catch (PAL_SEHException& ex)                \
-        {                                           \
-            if (nativeRethrow)                      \
-            {                                       \
-                throw;                              \
-            }                                       \
+        {                        \
+            if (nativeRethrow || (ex.HasTargetFrame() && ex.TargetFrameSp > (SIZE_T)&exCopy))               \
```
Comment (pavelsavara) [inline src/coreclr/vm/exceptmacros.h:227]: is the new code here necessary on non-WASM platforms ?

Comment (janvorli) [reply src/coreclr/vm/exceptmacros.h:227]: It is not, but since it is deep in the macro, it was easier to keep it like this. The HasTargetFrame() will always return false on other platforms and performance is not a problem here.

**Review by pavelsavara — APPROVED** [review]
