### PR TITLE
fix pal test

### LINKED ISSUE #66630: Test failure file_io.GetSystemTime.test1
Run: [runtime-coreclr r2r-extra 20220313.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=1661469&view=ms.vss-test-web.build-test-results-tab&runId=45726098&resultId=106360&paneView=debug)

Failed test:
```
R2R Linux x64 Checked jitstress1_tiered @ Ubuntu.1804.Amd64.Open

- file_io.GetSystemTime.test1

```
**Error message:**
```
ERROR: 2 calls for GetSystemTime interrupted by a 1000 ms sleep failed Value[0.000000]


Stack trace
```

### PR DESCRIPTION
**Pull request by danmoseley**
Fix #66630

It's checking that the abs seconds-number across a 1 second sleep differs. Because it is possible for the thread to be switched out for 60 seconds, it does this 5 times. However (a) it was using a short not a float and (b) it was checking that it was exactly 1 anyway. So it was making it 5 times more likely to have this problem.

It still seems a bit implausible, but it's at least possible this is why it failed.

Change to float and check that at least one iteration has a different value of seconds.

### CODE REVIEW

**Comment by am11** [comment]
> a) it was using a short not a float and (b) it was checking that it was exactly 1 anyway.

I don't see it in the existing code? It is using short to store sum of absolute values and checking that value be < 1.

**Comment by danmoseley** [comment]
> It is using short to store sum of absolute values and checking that value be < 1.

It's checking that the value is not less than 1, right? Yes, the short doesn't make any difference, but I think there was some edit at some point because why write `1.0`. Maybe they were aiming to do something like checking it was not less than 0.5. As it is the looping just makes it more likely you hit the 60-second problem.

File: src/coreclr/pal/tests/palsuite/file_io/GetSystemTime/test1/test.cpp [hunk 1]
```diff
@@ -100,24 +95,24 @@ PALTEST(file_io_GetSystemTime_test1_paltest_getsystemtime_test1, "file_io/GetSys
...
-        GetSystemTime(&secondTime);    
-        avgDeltaFileTime +=  abs(firstTime.wSecond - secondTime.wSecond );
-
-    }     
+        GetSystemTime(&secondTime);
+        avgDeltaFileTime += abs(firstTime.wSecond - secondTime.wSecond);
+    }
 
-    if( (avgDeltaFileTime/5) < 1.0)
+    if( (avgDeltaFileTime / 5) == 0)
```
Comment (am11) [inline src/coreclr/pal/tests/palsuite/file_io/GetSystemTime/test1/test.cpp:110]: Would it be better to change this condition to `<= 0`? (since this test is known to be passing on several platforms for a long time)

**Comment by am11** [comment]
Nvm, I missed that it was the error condition. :)

**Comment by danmoseley** [comment]
test failure is https://github.com/dotnet/runtime/issues/66668

**Review by BruceForstall — APPROVED** [review]
Seems fine to me.

Seems likely that the failure is because 1 of the 5 runs sleeps less than a second, so we get 4 /5 = 0 (for WORD division).

Maybe a better test would add the difference in wMilliseconds and compare `avgDeltaFileTime / 5 < 750` (say)?

@janvorli owns the PAL

**Comment by danmoseley** [comment]
> seems likely that the failure is because 1 of the 5 runs sleeps less than a second, so we get 4 /5 = 0 (for WORD division).

I have always assumed that a sleep is guaranteed to never return early. But I see the PAL's implementation of sleep is by no means straightforward! Well, this change would avoid that case.

I'm inclined to commit this as-is rather than spend more time on this test. Is that reasonable?

**Comment by BruceForstall** [comment]
> I'm inclined to commit this as-is as it's a rather dusty corner, rather than spend more time on this test. Is that reasonable?

agreed.
