### PR TITLE
Fix for COM Weakreference test failure under JIT stress.

### LINKED ISSUE #78945: Test failure: Interop\\COM\\ComWrappers\\WeakReference\\WeakReferenceTest\\WeakReferenceTest.cmd
Failed in win-x86 with random JitStress twice:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=94457&view=ms.vss-test-web.build-test-results-tab&runId=1991330&paneView=debug&resultId=105021

Related? https://github.com/dotnet/runtime/pull/78589

with:
```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2f6
```

as well as with:
```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=3be
```

error:
```
    Interop\COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\B3570998\w\97580854\uploads\Reports\Interop.COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\B3570998\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  WeakReferenceTest.dll 
      Running ValidateNonComWrappers...
      Running ValidateGlobalInstanceMarshalling...
        -- Validate weak reference creation
          -- Validate RCW recreation
          -- Validate release
        -- Validate target reset
          -- Validate RCW recreation
          -- Validate release
      Running ValidateGlobalInstanceTrackerSupport...
        -- Validate weak reference creation
          -- Validate RCW recreation
          -- Validate release
        -- Validate target reset
          -- Validate RCW recreation
          -- Validate release
      Validate weak reference with aggregation.
      Test Failure: Xunit.Sdk.NullException: Assert.Null() Failure
      Expected: (null)
      Actual:   DerivedObject { }
         at ComWrappersTests.Program.ValidateAggregatedWeakReference()
         at ComWrappersTests.Program.Main()
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
```

@VSadov @AaronRobinsonMSFT

### PR DESCRIPTION
**Pull request by VSadov**
JIT stress changes inlining heuristics and may cause methods to inline when they otherwise would not. That can extend life times of locals and temps in those methods.
 If a testcase depends on the local/temps life times to be within some method, it needs to ensure that the method is not inlined, so that the testcase behavior is the same regardless of JIT settings.

Fixes: #78945

### CODE REVIEW

**Comment by VSadov** [comment]
cc: @BruceForstall @AaronRobinsonMSFT

File: src/tests/Interop/COM/ComWrappers/WeakReference/WeakReferenceTest.cs [hunk 1]
```diff
@@ -132,6 +134,7 @@ private static void ValidateWeakReferenceState(WeakReference<WeakReferenceableWr
                 Assert.Equal(sourceWrappers.Registration, target.Registration);
         }
 
+        [MethodImpl(MethodImplOptions.NoInlining)]
```
Comment (AaronRobinsonMSFT) [inline src/tests/Interop/COM/ComWrappers/WeakReference/WeakReferenceTest.cs:137]: This makes sense, but I'm going to ask you to make a slightly more complicate fix. Can you please convert both of this APIs into `static` local functions into the `ValidateNativeWeakReference` test? Setting the `[MethodImpl(MethodImplOptions.NoInlining)]` is also appropriate. We should also update the other `GetWeakReference` local functions that are in this file to be `static` with the same impl attribute.

Comment (VSadov) [reply src/tests/Interop/COM/ComWrappers/WeakReference/WeakReferenceTest.cs:137]: > Can you please convert both of this APIs into static local functions into the ValidateNativeWeakReference test?

I was actually wondering why we do not do the opposite. 

Local functions reduce readability. That is the reason why I missed other local functions in this file - because it is hard to see that there are helper functions when they are hidden inside other functions and look like method blocks. 

I think for a testcase it is more important that the code is simple and readable.

Comment (VSadov) [reply src/tests/Interop/COM/ComWrappers/WeakReference/WeakReferenceTest.cs:137]: Actually, once there are attributes, it may be easier to spot them.

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/COM/ComWrappers/WeakReference/WeakReferenceTest.cs:137]: > Local functions reduce readability.

A rather subjective opinion that I empathize with. The most important consideration for me is being consistent so if you want to convert them to `static` methods on the class that is also okay with me.

Comment (VSadov) [reply src/tests/Interop/COM/ComWrappers/WeakReference/WeakReferenceTest.cs:137]: I will also move them to the top of containing methods - so that they are not mixed up with sequential code.

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/tests/Interop/COM/ComWrappers/WeakReference/WeakReferenceTest.cs (hunk 1 above)
Comment (VSadov) [reply src/tests/Interop/COM/ComWrappers/WeakReference/WeakReferenceTest.cs]: Local functions have benefits. The primary one is encapsulation and not polluting the outer name space. I just wish the syntax would make them stand out more, or perhaps visualize them in VisualStudio somehow - highlight the background a little, or something.

Anyways. I've updated other cases of the same pattern.

**Comment by VSadov** [comment]
Thanks!!!
