### PR TITLE
Fix assert in Thread::VirtualUnwindCallFrame on ARM64

### LINKED ISSUE #102337: win-arm64 tests failing with `Assert failure: (uImageBase == uImageBaseFromOS) && (memcmp(pFunctionEntry, pFunctionEntryFromOS, sizeof(RUNTIME_FUNCTION)) == 0)`
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=678076&view=ms.vss-test-web.build-test-results-tab
Build error leg or test failing: 

Example console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-102261-merge-14575ba9d22e4201a6/Common.Tests/1/console.59225bcf.log?helixlogtype=result

```
C:\h\w\A215090B\w\AA7609C4\e>"C:\h\w\A215090B\p\dotnet.exe" exec --runtimeconfig Common.Tests.runtimeconfig.json --depsfile Common.Tests.deps.json xunit.console.dll Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Common.Tests (found 247 of 257 test cases)
  Starting:    Common.Tests (parallel test collections = on [2 threads], stop on fail = off)

Assert failure(PID 7932 [0x00001efc], Thread: 8332 [0x208c]): (uImageBase == uImageBaseFromOS) && (memcmp(pFunctionEntry, pFunctionEntryFromOS, sizeof(RUNTIME_FUNCTION)) == 0)

CORECLR! Thread::VirtualUnwindCallFrame + 0xDC (0x00007ff8`8e589f7c)
CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x70 (0x00007ff8`8e4c8f38)
CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x34 (0x00007ff8`8e585dac)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x12C (0x00007ff8`8e58928c)
CORECLR! StackFrameIterator::NextRaw + 0x5C4 (0x00007ff8`8e588b1c)
CORECLR! Thread::StackWalkFramesEx + 0x28C (0x00007ff8`8e589d7c)
CORECLR! Thread::StackWalkFrames + 0x130 (0x00007ff8`8e589a48)
CORECLR! ScanStackRoots + 0x290 (0x00007ff8`8e6297f0)
CORECLR! GCToEEInterface::GcScanRoots + 0x1A4 (0x00007ff8`8e628564)
CORECLR! WKS::gc_heap::background_mark_phase + 0xFC (0x00007ff8`8e7d6b54)
    File: D:\a\_work\1\s\src\coreclr\vm\stackwalk.cpp:596
    Image: C:\h\w\A215090B\p\dotnet.exe
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "(uImageBase == uImageBaseFromOS) && (memcmp(pFunctionEntry, pFunctionEntryFromOS, sizeof(RUNTIME_FUNCTION)) == 0)",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Observed in libraries-jitstress, but I think it's unlikely to be related to jitstress.

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=678076
**Error message validated:** `[(uImageBase == uImageBaseFromOS) && (memcmp(pFunctionEntry, pFunctionEntryFromOS, sizeof(RUNTIME_FUNCTION)) == 0)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/16/2024 8:32:28 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[678333](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678333)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678333&view=ms.vss-test-web.build-test-results-tab&runId=16814588&resultId=100206)|dotnet/runtime#102261|
|[678076](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678076)|dotnet/runtime|[System.Globalization.Nls.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678076&view=ms.vss-test-web.build-test-results-tab&runId=16807746&resultId=100588)|dotnet/runtime#102261|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|2|2|

### PR DESCRIPTION
**Pull request by janvorli**
My recent change to fix windows arm64 unwinding for native code has started to trigger an assert in jitstress tests. The problem is that the codeinfo that is passed to the Thread::VirtualUnwindCallFrame in case of managed frames was created from an unadjusted PC, while the check that we use to verify the codeinfo validity in debug builds gets the function entry from the OS using the adjusted address.
The fix is to perform the adjustment only when codeinfo is not passed in.

Close #102337

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas I was originally considering instantiating the CodeInfo from PC adjusted in the same manner, but there are too many places where that happens.

**Review by mangod9 — APPROVED** [review]

File: src/coreclr/vm/stackwalk.cpp [hunk 1]
```diff
@@ -554,7 +554,11 @@ PCODE Thread::VirtualUnwindCallFrame(T_CONTEXT* pContext,
     PT_RUNTIME_FUNCTION pFunctionEntry;
 
 #if !defined(TARGET_UNIX) && defined(TARGET_ARM64)
-    if ((pContext->ContextFlags & CONTEXT_UNWOUND_TO_CALL) != 0)
+    // We don't adjust the control PC when we have a code info, as the code info is always created from an unadjusted one
```
Comment (jkotas) [inline src/coreclr/vm/stackwalk.cpp:557]: Is the unadjusted code info going to work well for the unwind? In other words, can we hit the bug that you have fixed when the code info is passed in?

Comment (janvorli) [reply src/coreclr/vm/stackwalk.cpp:557]: The code info is passed in only for managed frames. If it was not the case, the code info would not be valid and the assert I am fixing would be firing. 
Return address in managed code is never out of the bounds of the method containing the call, otherwise unwinding managed code would be crashing / hanging on arm64 Windows both with and without the new EH.

**Review by jkotas — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Any idea what causes jitstress in particular to hit this issue?

**Comment by janvorli** [comment]
@jakobbotsch the way how the managed method gets covered by multiple RUNTIME_FUNCTIONS seems to be jitstress specific.

**Comment by jakobbotsch** [comment]
Ah, this is likely our unwind stress mode then. In that mode we split the function into multiple fragments even when the function doesn't exceed the max fragment size.
