### PR TITLE
Fix TypeMap test to match trimming spec

### LINKED ISSUE #121912: Validate_ProxyTypeMapping test failing with trimming enabled
In #121697 I'm enabling trimming on the src/tests tree so that we're testing a configuration that is closer to the AOT default that we recommend externally (full trimming with TrimMode=full instead of TrimMode=partial).

I'm seeing the Validate_ProxyTypeMapping test failing.

```
Validate_ProxyTypeMapping
System.Collections.Generic.KeyNotFoundException: The given key 'C1' was not present in the dictionary.
   at System.Runtime.InteropServices.TypeMapLazyDictionary.AssociatedTypeMapDictionary.get_Item(Type) + 0x30
   at TypeMap.Validate_ProxyTypeMapping() + 0x34
   at __GeneratedMainWrapper.Main() + 0x12
```

https://github.com/dotnet/runtime/blob/6a06e6629ab7e97216ebff3bba840e0d209d93f5/src/tests/Interop/TypeMap/TypeMapApp.cs#L141-L178

From my read of the TypeMap trimming behavior spec, this looks like a test bug, not a product bug.

https://github.com/dotnet/runtime/blob/6a06e6629ab7e97216ebff3bba840e0d209d93f5/docs/design/features/typemap.md?plain=1#L205-L222

The type is only referenced with a `typeof` (therefore maps to the `ldtoken` rule), but there's no annotation to force constructor reflectability (so the rest of the rule is not satisfied). The compiler therefore determines that the type cannot be seen as allocated and generates only limited metadata for it (and that includes not making it present in the TypeMap).

If we determine this is indeed a test bug, I can make a PR that switches the `typeof` to a `new X().GetType()` (which should satisfy the heuristic rules).

Otherwise we have a native AOT product bug.

Cc @Sergio0694 @AaronRobinsonMSFT @jkoritzinsky @dotnet/illink

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #121912

### CODE REVIEW

File: src/tests/Interop/TypeMap/TypeMapApp.cs [hunk 1]
```diff
@@ -145,17 +145,17 @@ public static void Validate_ProxyTypeMapping()
 
         IReadOnlyDictionary<Type, Type> map = TypeMapping.GetOrCreateProxyTypeMapping<TypicalUseCase>();
 
-        Assert.Equal(typeof(C1), map[typeof(C1)]);
-        Assert.Equal(typeof(S1), map[typeof(S1)]);
-        Assert.Equal(typeof(C1), map[typeof(Guid)]);
-        Assert.Equal(typeof(S1), map[typeof(string)]);
-        Assert.Equal(typeof(C1), map[typeof(List<int>)]);
+        Assert.Equal(typeof(C1), map[new C1().GetType()]);
```
Comment (AaronRobinsonMSFT) [inline src/tests/Interop/TypeMap/TypeMapApp.cs:149]: Nit: Let's add a link to the rules/design doc here. Walking up to this it isn't obvious why some are `typeof` whereas others use instance creation.

**Review by AaronRobinsonMSFT — APPROVED** [review]
Minor request for a doc link. Other than that, looks great!

File: src/tests/Interop/TypeMap/TypeMapApp.cs (hunk 1 above)
Comment (MichalStrehovsky) [inline src/tests/Interop/TypeMap/TypeMapApp.cs:149]:
```suggestion
        // Need to use `new`, not just `typeof` due to trimming rules: https://github.com/dotnet/runtime/blob/550c960396d3bba1a83198d0a3ac24109124e82d/docs/design/features/typemap.md#type-map-entry-trimming-rules
        Assert.Equal(typeof(C1), map[new C1().GetType()]);
```

**Review by AaronRobinsonMSFT — APPROVED** [review]
Thanks.
