### PR TITLE
[wasm][debugger] Fixed debugger attachment to a project with special characters in the path.

### LINKED ISSUE #62856: Debugging Blazor WASM project running from a directory with special characters fails to
### Describe the bug
When running a Blazor WASM project from a directory containing special characters, breakpoints will not be hit correctly and will produce:
`Unable to retrieve source content (Unable to retrieve source content)`

Tested with Chrome, Edge, Firefox, Vivaldi. All result in a similar response

### To Reproduce
Reproducible using project templates from a fresh install of Visual Studio 2022.

Create a new Blazor WebAssembly App with a project directory containing a hash (eg: `%UserProfile%/Projects/C#`), select .NET 6.0 (Long-term support) for framework, and leave the remaining options default.

### Exceptions (if any)
No exceptions will be raised.

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2022 Version 17.0.2
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.209 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

### Related Issues
Raised dotnet/aspnetcore#14501, then dotnet/aspnetcore#22036, and should be resolved by dotnet/aspnetcore#14827 (according to comments) but the issue remains as of today when debugging a Blazor WASM app from a directory with a special char (a hash (#) in this case).

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes #62856.

Source of problem: 
`Uri` constructor does not support special characters coding if they are not of a typical path format, so appending string `"file://"` to url for rooted path resulted in `SourceUri` e.g.:  
`file:///C:/Users/itomkowicz/source/repos/C#\SpecialPath\SpecialPath\Shared\WeatherForecast.cs`

Fix: 
We could just use `Uri` constructor as it appends the prefix `file://` if the assembly is loaded and the path is a recognized as system path. This way we are getting a SourceUri of: 
`file:///C:/Users/itomkowicz/source/repos/C%23/SpecialPath/SpecialPath/Shared/WeatherForecast.cs`
where C# is coded correctly.
However, this results in related but not loaded assembly tests failures:
```
DebuggerTests.EvaluateOnCallFrameTests.EvaluateLocalObjectFromAssemblyNotRelatedButLoaded [FAIL]
DebuggerTests.EvaluateOnCallFrameTests.EvaluateStaticAttributeInAssemblyNotRelatedButLoaded [FAIL]
DebuggerTests.MiscTests.GetSourceUsingSourceLink [FAIL]
```
In order to avoid it, we have to keep appending the prefix manually, just code the url before passing to the `Uri` constructor using @lewing's function from [commit](https://github.com/lewing/mono/commit/17519ba6235af36d15b65142798b375680172241).

### CODE REVIEW

File: src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs [hunk 1]
```diff
@@ -928,5 +928,15 @@ public async Task InspectLocalsUsingClassFromLibraryUsingDebugTypeFull()
...
         //TODO add tests covering basic stepping behavior as step in/out/over
+
+        [Fact]
+        public async Task SetBreakpointInProjectWithSpecialCharactersInPath()
+        {
+            var bp = await SetBreakpointInMethod("debugger-test-special-char-in-path.dll", "DebuggerTests.CheckSpecialCharactersInPath", "Evaluate", 1);
+            Assert.True(
+                bp.Value["breakpointId"].Value<string>().EndsWith("debugger-test-special-char-in-path-%23%40/test.cs"), 
+                "Failed to set a breakpoint in project with special characters in path."
+                );
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:939]: This should try hitting that breakpoint too.

File: src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs [hunk 2]
```diff
@@ -928,5 +928,15 @@ public async Task InspectLocalsUsingClassFromLibraryUsingDebugTypeFull()
             );
         }
         //TODO add tests covering basic stepping behavior as step in/out/over
+
+        [Fact]
+        public async Task SetBreakpointInProjectWithSpecialCharactersInPath()
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:933]: It would be useful to check a path having non-ascii chars too.
And checking a source file name with such characters.

**Comment by radical** [comment]
```
  Failed DebuggerTests.MiscTests.SetBreakpointInProjectWithSpecialCharactersInPath [98 ms]
  Error Message:
   Failed to set a breakpoint in project with special characters in path.
Expected: True
Actual:   False
  Stack Trace:
     at DebuggerTests.MiscTests.SetBreakpointInProjectWithSpecialCharactersInPath() in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 956
```

File: src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs (hunk 1 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:948]: The error was originally visible already while setting but good point, added.

File: src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs (hunk 2 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs]: I added both and still working.

**Comment by ilonatommy** [comment]
> ```
>   Failed DebuggerTests.MiscTests.SetBreakpointInProjectWithSpecialCharactersInPath [98 ms]
>   Error Message:
>    Failed to set a breakpoint in project with special characters in path.
> Expected: True
> Actual:   False
>   Stack Trace:
>      at DebuggerTests.MiscTests.SetBreakpointInProjectWithSpecialCharactersInPath() in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 956
> ```

Did you get this error after rebuilding? It never fails for me and I cannot reproduce.

**Comment by radical** [comment]
The error is from the CI - https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64527-merge-2c4181738eaa4102b2/DebuggerTests.MiscTests/1/console.4cb5a616.log?sv=2019-07-07&se=2022-02-20T18%3A25%3A54Z&sr=c&sp=rl&sig=PneAlwlqpctMt7Z59FkxZWhDPy9CPLuLRA8AZ%2BbMlFg%3D after my `dummy commit`. Test failures in `runtime-staging` don't fail the job, so you need to check the details tab.

File: src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs [hunk 3]
```diff
@@ -932,20 +932,14 @@ public async Task InspectLocalsUsingClassFromLibraryUsingDebugTypeFull()
...
             "DebuggerTests.CheckSNonAsciiCharactersInPath", 
-            "debugger-test-special-char-in-path-%23%40/non-ascii-test-ął.cs", 
             "dotnet://debugger-test-special-char-in-path.dll/non-ascii-test-ął.cs")]
         public async Task SetBreakpointInProjectWithSpecialCharactersInPath(
-            string classWithNamespace, string expectedLocationSufix, string expectedFileLocation)
+            string classWithNamespace, string expectedFileLocation)
         {
             var bp = await SetBreakpointInMethod("debugger-test-special-char-in-path.dll", classWithNamespace, "Evaluate", 1);
-            Assert.True(
-                bp.Value["breakpointId"].Value<string>().EndsWith(expectedLocationSufix),
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs]: What was the actual value that didn't match?

Comment (ilonatommy) [reply src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs]: Locally @# was coded into hex so %23%40 and on CI it was just @#.

**Comment by thaystg** [comment]
Looks like that passed on CI :)

**Review by thaystg — APPROVED** [review]
LGTM
