### PR TITLE
Do not set predecessor for throw block

### LINKED ISSUE #49625: Test failure baseservices/exceptions/unittests/EHPatternTests/EHPatternTests.sh
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20210314.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1038574&view=ms.vss-test-web.build-test-results-tab&runId=32191738&resultId=109665&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0x3 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
 -baseservices/exceptions/unittests/EHPatternTests/EHPatternTests.sh
```

**Error message:**
```
/root/helix/work/workitem/baseservices/exceptions/unittests/EHPatternTests/EHPatternTests.sh: line 376: 5136 Segmentation fault (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /root/helix/work/workitem/baseservices/exceptions/Reports/baseservices.exceptions/unittests/EHPatternTests/EHPatternTests.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun EHPatternTests.dll ''
-----------------------------
BaseClassTest
-----------------------------
System.IO.FileNotFoundException: 1
 at BaseClassTest.f2()
 at BaseClassTest.f1()
System.IO.FileNotFoundException: 1
 at BaseClassTest.f1()
 at BaseClassTest.Run()
0121: PASS
-----------------------------
TryCatchInFinallyTest
-----------------------------
System.InvalidProgramException: Common Language Runtime detected an invalid program.
 at TryCatchInFinallyTest.Run()
0123456: PASS
-----------------------------
RecurseTest
-----------------------------
System.Exception: 7
 at RecurseTest.DoTest(Int32 level)
System.Exception: 5
 at RecurseTest.DoTest(Int32 level)
System.Exception: 3
 at RecurseTest.DoTest(Int32 level)
System.Exception: 1
 at RecurseTest.DoTest(Int32 level)
876543210: PASS
-----------------------------
ThrowInFinallyNestedInTryTest
-----------------------------
System.ArgumentException: Value does not fall within the expected range.
 at ThrowInFinallyNestedInTryTest.MiddleMethod()
 at ThrowInFinallyNestedInTryTest.Run()
0123456789a: PASS
-----------------------------
GoryManagedPresentTest
-----------------------------
System.DivideByZeroException: Attempted to divide by zero.
 at GoryManagedPresentTest.foo(Int32 dummy)
 at GoryManagedPresentTest.Run()
0123456: PASS
-----------------------------
InnerFinallyAndCatchTest
-----------------------------
abcdefghijklm13: PASS
-----------------------------
InnerFinallyTest
-----------------------------
 try 1
 try 1.1
 finally 1.1
 try 1.1.1
 Throwing an exception here!
 finally 1.1.1
 catch 1
 finally 1
: PASS
-----------------------------
ThrowInFinallyTest
-----------------------------
System.Exception: C
 at ThrowInFinallyTest.Dumb()
 at ThrowInFinallyTest.Run()
0123456789Ca: PASS
-----------------------------
RecursiveRethrow
-----------------------------
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.Run()
210C0C1C2: PASS
-----------------------------
RecursiveThrowNew
-----------------------------
System.Exception: eX
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e0
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e1
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e2
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
 at RecursiveThrowNew.Run()
210C0(eX)C1(e0)C2(e1)CM(e2): PASS
-----------------------------
PendingTest
-----------------------------
System.Exception: Exception of type 'System.Exception' was thrown.
 at PendingTest.f3()
 at PendingTest.f2()
System.Exception: Exception of type 'System.Exception' was thrown.
 at PendingTest.f3()
 at PendingTest.f2()
 at PendingTest.f1()
System.Exception: Exception of type 'System.Exception' was thrown.
 at PendingTest.f1()
 at PendingTest.Run()
System.Exception: Exception of type 'System.Exception' was thrown.
 at PendingTest.f3()
 at PendingTest.f2()
System.Exception: Exception of type 'System.Exceptio

Stack trace
   at baseservices_exceptions._unittests_EHPatternTests_EHPatternTests_._unittests_EHPatternTests_EHPatternTests_sh()

```

### PR DESCRIPTION
**Pull request by kunalspathak**
When the LSRA block sequence is set up, if there is no predecessor to a block, we set the predecessor `predBBNum` to be the previous block that was present in the lexical order. However, doing that  doesn't work well if the current block is a throw block. No block's `bbJumpDest` point to the shared throw block. For such blocks, we never have predecessor and assigning the `predBBNum` to the lexically ordered previous block is problematic in register liveness. By doing that, we tell the register allocator that in whatever registers the values of live-out variables of previous block resides, they continue to stay live in those registers for the live-in variables to the throw block. This might not be true always.  The successor of a throw block are always finally or a handler and has EH boundary-in i.e. the successor blocks always expect and load the variables from the stack and not from the registers. Hence, ideally, the shared throw block helpers shouldn't have any variables live in registers, and all of them should be on stack. That way, if a GC occurs inside such a throw block, it will not consider the value in register as valid objects.

To fix this, I added a new `BBF_SHARED_THROW` kind that is set on such blocks. During LSRA block sequencing, if we see such blocks, we would return `nullptr` instead of previous block so the values are left on the stack.

E.g. In #49623, we assigned `rdi` to variable `V01` at all places except in one block A where it gets `rbx`. However, since block A was lexically before the throw block, the throw block assumed that the variable `V01` is live in `rbx`, but in fact, the block that jumps to the throw block has that variable in `rdi` instead. When the GC happens, it wrongly think that value in `rbx` is a valid object. We started seeing failure when GC happened in `IG67` and it wanted to collect object inside `rbx` except that the value in `rbx` was not a valid object.

Asmdiffs before and after this changes are [here](https://www.diffchecker.com/MyB11MNK).

There are minor diffs with superpmi asmdiff:

```
Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 43144
Total bytes of diff: 43135
Total bytes of delta: -9 (-0.02% of base)
    diff is an improvement.


Top file improvements (bytes):
          -4 : 193548.dasm (-0.70% of base)
          -1 : 193493.dasm (-0.28% of base)
          -1 : 193632.dasm (-0.26% of base)
          -1 : 193518.dasm (-0.18% of base)
          -1 : 193611.dasm (-0.26% of base)
          -1 : 193509.dasm (-0.19% of base)

6 total files with Code Size differences (6 improved, 0 regressed), 32 unchanged.

Top method improvements (bytes):
          -4 (-0.70% of base) : 193548.dasm - <SkipWhileIterator>d__198`1[__Canon][System.__Canon]:MoveNext():bool:this
          -1 (-0.28% of base) : 193493.dasm - <SelectIterator>d__180`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:MoveNext():bool:this
          -1 (-0.26% of base) : 193632.dasm - <WhereIterator>d__246`1[__Canon][System.__Canon]:MoveNext():bool:this
          -1 (-0.18% of base) : 193518.dasm - <SelectManyIterator>d__183`2[Byte,Nullable`1][System.Byte,System.Nullable`1[System.Int32]]:MoveNext():bool:this
          -1 (-0.26% of base) : 193611.dasm - <TakeWhileIterator>d__226`1[__Canon][System.__Canon]:MoveNext():bool:this
          -1 (-0.19% of base) : 193509.dasm - <SelectManyIterator>d__183`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:MoveNext():bool:this

Top method improvements (percentages):
          -4 (-0.70% of base) : 193548.dasm - <SkipWhileIterator>d__198`1[__Canon][System.__Canon]:MoveNext():bool:this
          -1 (-0.28% of base) : 193493.dasm - <SelectIterator>d__180`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:MoveNext():bool:this
          -1 (-0.26% of base) : 193611.dasm - <TakeWhileIterator>d__226`1[__Canon][System.__Canon]:MoveNext():bool:this
          -1 (-0.26% of base) : 193632.dasm - <WhereIterator>d__246`1[__Canon][System.__Canon]:MoveNext():bool:this
          -1 (-0.19% of base) : 193509.dasm - <SelectManyIterator>d__183`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:MoveNext():bool:this
          -1 (-0.18% of base) : 193518.dasm - <SelectManyIterator>d__183`2[Byte,Nullable`1][System.Byte,System.Nullable`1[System.Int32]]:MoveNext():bool:this

6 total methods with Code Size differences (6 improved, 0 regressed), 32 unchanged.
```

Fixes: #49625, #49624, #49623

### CODE REVIEW

**Comment by kunalspathak** [comment]
libraries-jitstressregs failures are related to https://github.com/dotnet/runtime/issues/49700

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
Thank you @BruceForstall for your time and helping me think through the problem.

File: src/coreclr/jit/lsra.cpp [hunk 1]
```diff
@@ -2309,12 +2308,43 @@ BasicBlock* LinearScan::findPredBlockForLiveIn(BasicBlock* block,
...
+        //      JMP IG08
+        // IG07:
+        //      ...         ; LSRA thinks V01 is in 'rbx' if IG06 is set as previous block of IG07.
+        //      ....
+        //      CALL CORINFO_HELP_RNGCHKFAIL
+        //      ...
+        // IG08:
+        //      ...
+        //      ...
+        if (block->bbJumpKind == BBJ_THROW && ((block->bbFlags & BBF_SHARED_THROW) != 0))
```
Comment (kunalspathak) [inline src/coreclr/jit/lsra.cpp:2337]: I was thinking if I should add a new flag `BBF_SHARED_THROW` but I was not certain if `BBF_DONT_REMOVE` for a `throw` block would capture the case that I wanted to check.

Comment (BruceForstall) [reply src/coreclr/jit/lsra.cpp:2337]: BBF_DONT_REMOVE is used on many blocks; checking that as well as BBJ_THROW would work, but might possibly pick up additional cases. You could check diffs to see, perhaps. Adding the flag seems reasonable.

File: src/coreclr/jit/flowgraph.cpp [hunk 2]
```diff
@@ -4088,6 +4088,7 @@ BasicBlock* Compiler::fgAddCodeRef(BasicBlock* srcBlk, unsigned refData, Special
 
     newBlk->bbFlags |= BBF_IMPORTED;
     newBlk->bbFlags |= BBF_DONT_REMOVE;
+    newBlk->bbFlags |= BBF_SHARED_THROW;
```
Comment (BruceForstall) [inline src/coreclr/jit/flowgraph.cpp:4091]: Add the flag to `BasicBlock::dspFlags()`

**Review by BruceForstall — CHANGES_REQUESTED** [review]

File: src/coreclr/jit/lsra.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lsra.cpp:2337]: The shared throw helpers are special in that they don't have any live-in vars of their own (that is part of how we get away with not giving them actual preds). So you could perhaps instead check that the block's use set is empty and that it is also BBJ_THROW and avoid special up front analysis and block tagging.

It seems odd to me that LSRA doesn't get rid of unreachable blocks and instead tolerates them.

File: src/coreclr/jit/lsra.cpp [hunk 3]
```diff
@@ -2309,12 +2308,43 @@ BasicBlock* LinearScan::findPredBlockForLiveIn(BasicBlock* block,
...
+        {
+            assert((block->bbFlags & BBF_DONT_REMOVE) != 0);
+            JITDUMP(" - Shared throw block; ");
+            return nullptr;
+        }
+
         // We may have unreachable blocks, due to optimization.
         // We don't want to set the predecessor as null in this case, since that will result in
         // unnecessary DummyDefs, and possibly result in inconsistencies requiring resolution
         // (since these unreachable blocks can have reachable successors).
```
Comment (BruceForstall) [inline src/coreclr/jit/lsra.cpp:2347]: Did you try just always returning null and look at diffs, to understand this comment? Maybe it wouldn't apply to any throw block since I believe there would never be a register resolution between a throw block and any successor? That is, maybe you can return null for any throw block with no predecessor, and not worry about it being a special throw helper block.

Comment (kunalspathak) [reply src/coreclr/jit/lsra.cpp:2347]: I see slight regression if just return `nullptr` if there is no previous block.

```
Total PerfScoreUnits of base: 65337.50000000002
Total PerfScoreUnits of diff: 65373.940000000024
Total PerfScoreUnits of delta: 36.44 (0.06% of base)
    diff is a regression.

```
<details>
<summary>Details perfscore diff</summary>

```
Top file regressions (PerfScoreUnits):
       32.40 : 191062.dasm (0.63% of base)
        0.90 : 74188.dasm (0.27% of base)
        0.85 : 231849.dasm (0.20% of base)
        0.85 : 230436.dasm (0.20% of base)
        0.85 : 230451.dasm (0.19% of base)
        0.85 : 231864.dasm (0.19% of base)
        0.85 : 231040.dasm (0.20% of base)
        0.85 : 231055.dasm (0.19% of base)
        0.55 : 74042.dasm (0.04% of base)
        0.50 : 231835.dasm (0.12% of base)
        0.50 : 230422.dasm (0.12% of base)
        0.50 : 231026.dasm (0.12% of base)

Top file improvements (PerfScoreUnits):
       -0.90 : 193548.dasm (-0.40% of base)
       -0.75 : 106063.dasm (-0.20% of base)
       -0.48 : 193493.dasm (-0.59% of base)
       -0.47 : 193611.dasm (-0.54% of base)
       -0.47 : 193509.dasm (-0.20% of base)
       -0.47 : 193518.dasm (-0.21% of base)
       -0.47 : 193632.dasm (-0.32% of base)

19 total files with Perf Score differences (7 improved, 12 regressed), 34 unchanged.

Top method regressions (PerfScoreUnits):
       32.40 ( 0.63% of base) : 191062.dasm - System.Linq.Parallel.OrderPreservingPipeliningSpoolingTask`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:SpoolingWork():this
        0.90 ( 0.27% of base) : 74188.dasm - Microsoft.CodeAnalysis.AssemblyPortabilityPolicy:LoadFromXml(System.IO.Stream):Microsoft.CodeAnalysis.AssemblyPortabilityPolicy
        0.85 ( 0.20% of base) : 231849.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int32][System.Int32]:Equals(int,int):bool:this
        0.85 ( 0.20% of base) : 230436.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int32][System.Int32]:Equals(int,int):bool:this
        0.85 ( 0.19% of base) : 230451.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int64][System.Int64]:Equals(long,long):bool:this
        0.85 ( 0.19% of base) : 231864.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int64][System.Int64]:Equals(long,long):bool:this
        0.85 ( 0.20% of base) : 231040.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int32][System.Int32]:Equals(int,int):bool:this
        0.85 ( 0.19% of base) : 231055.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int64][System.Int64]:Equals(long,long):bool:this
        0.55 ( 0.04% of base) : 74042.dasm - Microsoft.CodeAnalysis.CommonCompiler:RunCore(System.IO.TextWriter,Microsoft.CodeAnalysis.ErrorLogger,System.Threading.CancellationToken):int:this
        0.50 ( 0.12% of base) : 231835.dasm - Xunit.Sdk.AssertEqualityComparer`1[Byte][System.Byte]:Equals(ubyte,ubyte):bool:this
        0.50 ( 0.12% of base) : 230422.dasm - Xunit.Sdk.AssertEqualityComparer`1[Byte][System.Byte]:Equals(ubyte,ubyte):bool:this
        0.50 ( 0.12% of base) : 231026.dasm - Xunit.Sdk.AssertEqualityComparer`1[Byte][System.Byte]:Equals(ubyte,ubyte):bool:this

Top method improvements (PerfScoreUnits):
       -0.90 (-0.40% of base) : 193548.dasm - <SkipWhileIterator>d__198`1[__Canon][System.__Canon]:MoveNext():bool:this
       -0.75 (-0.20% of base) : 106063.dasm - System.Data.DataColumn:set_DataType(System.Type):this
       -0.48 (-0.59% of base) : 193493.dasm - <SelectIterator>d__180`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:MoveNext():bool:this
       -0.47 (-0.54% of base) : 193611.dasm - <TakeWhileIterator>d__226`1[__Canon][System.__Canon]:MoveNext():bool:this
       -0.47 (-0.20% of base) : 193509.dasm - <SelectManyIterator>d__183`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:MoveNext():bool:this
       -0.47 (-0.21% of base) : 193518.dasm - <SelectManyIterator>d__183`2[Byte,Nullable`1][System.Byte,System.Nullable`1[System.Int32]]:MoveNext():bool:this
       -0.47 (-0.32% of base) : 193632.dasm - <WhereIterator>d__246`1[__Canon][System.__Canon]:MoveNext():bool:this

Top method regressions (percentages):
       32.40 ( 0.63% of base) : 191062.dasm - System.Linq.Parallel.OrderPreservingPipeliningSpoolingTask`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:SpoolingWork():this
        0.90 ( 0.27% of base) : 74188.dasm - Microsoft.CodeAnalysis.AssemblyPortabilityPolicy:LoadFromXml(System.IO.Stream):Microsoft.CodeAnalysis.AssemblyPortabilityPolicy
        0.85 ( 0.20% of base) : 231849.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int32][System.Int32]:Equals(int,int):bool:this
        0.85 ( 0.20% of base) : 230436.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int32][System.Int32]:Equals(int,int):bool:this
        0.85 ( 0.20% of base) : 231040.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int32][System.Int32]:Equals(int,int):bool:this
        0.85 ( 0.19% of base) : 230451.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int64][System.Int64]:Equals(long,long):bool:this
        0.85 ( 0.19% of base) : 231864.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int64][System.Int64]:Equals(long,long):bool:this
        0.85 ( 0.19% of base) : 231055.dasm - Xunit.Sdk.AssertEqualityComparer`1[Int64][System.Int64]:Equals(long,long):bool:this
        0.50 ( 0.12% of base) : 231835.dasm - Xunit.Sdk.AssertEqualityComparer`1[Byte][System.Byte]:Equals(ubyte,ubyte):bool:this
        0.50 ( 0.12% of base) : 230422.dasm - Xunit.Sdk.AssertEqualityComparer`1[Byte][System.Byte]:Equals(ubyte,ubyte):bool:this
        0.50 ( 0.12% of base) : 231026.dasm - Xunit.Sdk.AssertEqualityComparer`1[Byte][System.Byte]:Equals(ubyte,ubyte):bool:this
        0.55 ( 0.04% of base) : 74042.dasm - Microsoft.CodeAnalysis.CommonCompiler:RunCore(System.IO.TextWriter,Microsoft.CodeAnalysis.ErrorLogger,System.Threading.CancellationToken):int:this

Top method improvements (percentages):
       -0.48 (-0.59% of base) : 193493.dasm - <SelectIterator>d__180`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:MoveNext():bool:this
       -0.47 (-0.54% of base) : 193611.dasm - <TakeWhileIterator>d__226`1[__Canon][System.__Canon]:MoveNext():bool:this
       -0.90 (-0.40% of base) : 193548.dasm - <SkipWhileIterator>d__198`1[__Canon][System.__Canon]:MoveNext():bool:this
       -0.47 (-0.32% of base) : 193632.dasm - <WhereIterator>d__246`1[__Canon][System.__Canon]:MoveNext():bool:this
       -0.47 (-0.21% of base) : 193518.dasm - <SelectManyIterator>d__183`2[Byte,Nullable`1][System.Byte,System.Nullable`1[System.Int32]]:MoveNext():bool:this
       -0.75 (-0.20% of base) : 106063.dasm - System.Data.DataColumn:set_DataType(System.Type):this
       -0.47 (-0.20% of base) : 193509.dasm - <SelectManyIterator>d__183`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:MoveNext():bool:this

19 total methods with Perf Score differences (7 improved, 12 regressed), 34 unchanged.

```
</details>

However, I don't see any diffs in libraries if I remove the check for `BBF_SPECIAL_THROW` flag. So I will return `nullptr` for throw block that do not have predecessor.

**Comment by EgorBo** [comment]
Unrelated, those floating THROW blocks sometimes can be found in the final codegen and be still unreachable, e.g. https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgy5UQAtsUPgBlsweszYdFS5cQDMlAEzkuygN7LyL8s9fuXAbQBSrDADiMEwi0gAUGACefDAQAGZhwBAQggCUaORRMfGJkRgwqakAup6UVqws5ACyMPjQkVVauJqCAPpceBitAKII2PzCADwAKlRow9YAfGGppU5KrovkFRiZVOQAvOQAqky42HGcoqwAXjAA8nEjVNOppkuuK5m2W7v7hzTHZ5cjUzP3DzcC0BrDi5Ai6w2Www1lmwIe80BSwA9MjMupWLhyHxsBh1MssRhsABrYKlJHEADs5FIAIeAF9ya4YIJcDAmS5EUjXKj0ZjyMBBBAwMTyM0IAxBAATAUwciwOoSGBSjkotHABirLjnOgASQAcgAxc6tAAS3R0AAVWsNTXRzgB1VrnABq3Tohp0joJYrYgkE6JE7Ph3Kp5DA6hgIuVEPIAGpnndVYyQyn6UA

**Comment by AndyAyersMS** [comment]
I was chatting with Bruce about why we could not add edges for those blocks -- his argument was that because these special exception checks happen mid-block it would be misleading to add the edges, and that it would be (or was thought to be) too expensive to split the blocks once we introduce the tests. For instance there might be hundreds of bounds checks in a block.

Some compilers I know of tolerate mid-block flow (aka "superblocks") and factor these repeated mid-block edges into a single super-edge so that the overall flow graph topology is still properly modelled, and make suitable updates to data flow to compensate for these super-edges. So we might consider adopting something like that. May not be worth the trouble, if we're just using it for this sort of thing.

**Comment by kunalspathak** [comment]
> Unrelated: those floating THROW blocks sometimes can be found in the final codegen and be still unreachable

Yes, probably because they are marked as `BBF_DONT_REMOVE` when they are created.

**Comment by kunalspathak** [comment]
> I was chatting with Bruce about why we could not add edges for those blocks

Will it be possible to had some kind of field like `throwBlockPredList` containing list of blocks that reach the `throw` block and use that information only at few places like dead block removal or LSRA? We can continue to ignore `throwBlockPredList` for edge connection, etc.

File: src/coreclr/jit/flowgraph.cpp (hunk 2 above)
Comment (kunalspathak) [reply src/coreclr/jit/flowgraph.cpp:4091]: Not needed anymore.

File: src/coreclr/jit/lsra.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/lsra.cpp:2337]: Just checking if the block is `BBJ_THROW` without any predecessor works, so I don't need `BBF_SHARED_THROW` anymore.

**Comment by BruceForstall** [comment]
> Unrelated: those floating THROW blocks sometimes can be found in the final codegen and be still unreachable

If we dead code remove a caller, we don't know it was the only caller, since the throw blocks are shared, we don't have predecessor edges on them, and even if we did, we'd need to have a count of uses per predecessor (or something like that) and do "ref counting" on them.

**Review by BruceForstall — APPROVED** [review]

**Comment by nelsondani** [comment]
[](https://www.dropbox.com/t/https://www.dropbox.com/t/1vORK1nh9gvc1dX3**_[](https://www.dropbox.com/t/1vORK1nh9gvc1dX3)_**
