### PR TITLE
[Android] Expand smoke tests for CoreCLR Android

### LINKED ISSUE #51399: System.Diagnostics.StackTrace.Tests Fails on iOS, tvOS
System.Diagnostics.StackTrace.Tests
System.Diagnostics.SymbolStore.Tests.StackTraceSymbolsTests.StackTraceSymbolsDoNotLockFile

```
System.Diagnostics.StackTrace.Tests.dll   Failed: 1

Test collection for System.Diagnostics.SymbolStore.Tests.StackTraceSymbolsTests
System.Diagnostics.SymbolStore.Tests.StackTraceSymbolsTests.StackTraceSymbolsDoNotLockFile
    Assert.True() Failure\nExpected: True\nActual:   False

### PR DESCRIPTION
**Pull request by kotlarmilos**
## Description

This PR updates the test library to skip tests that are not supported on the CoreCLR Android platform. Additionally, it expands the smoke tests to include a group of tests with Android-specific behavior.

## Changes
 - Replace ActiveIssue with ConditionalFact for tests that fail due to single-file host limitations
 - Expand smoke tests to cover scenarios with Android-specific behavior

Fixes https://github.com/dotnet/runtime/issues/51399
Contributes to https://github.com/dotnet/runtime/issues/114951

### CODE REVIEW

File: src/libraries/System.Diagnostics.StackTrace/tests/StackTraceSymbolsTests.cs [hunk 1]
```diff
@@ -11,7 +11,6 @@ public class StackTraceSymbolsTests
     {
         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.HasAssemblyFiles))]
         [ActiveIssue("https://github.com/dotnet/runtime/issues/51399", TestPlatforms.iOS | TestPlatforms.tvOS | TestPlatforms.MacCatalyst)]
-        [ActiveIssue("https://github.com/dotnet/runtime/issues/114951", TestPlatforms.Android)]
         public void StackTraceSymbolsDoNotLockFile()
```
Comment (vitek-karas) [inline src/libraries/System.Diagnostics.StackTrace/tests/StackTraceSymbolsTests.cs:14]: Does this mean the test passes on mono as well?

File: src/libraries/System.Runtime/tests/System.Reflection.Tests/AssemblyTests.cs [hunk 2]
```diff
@@ -845,7 +845,6 @@ public void AssemblyLoadFromBytesNeg()
 
         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsAssemblyLoadingSupported), nameof(PlatformDetection.HasAssemblyFiles))]
         [SkipOnPlatform(TestPlatforms.iOS | TestPlatforms.tvOS | TestPlatforms.MacCatalyst, "Symbols are in a different location on iOS/tvOS/MacCatalyst")]
-        [ActiveIssue("https://github.com/dotnet/runtime/issues/114951", TestPlatforms.Android)]
         public void AssemblyLoadFromBytesWithSymbols()
```
Comment (vitek-karas) [inline src/libraries/System.Runtime/tests/System.Reflection.Tests/AssemblyTests.cs:848]: Same - does it work on mono?

**Review by vitek-karas — APPROVED** [review]

File: src/libraries/System.Diagnostics.StackTrace/tests/StackTraceSymbolsTests.cs (hunk 1 above)
Comment (kotlarmilos) [reply src/libraries/System.Diagnostics.StackTrace/tests/StackTraceSymbolsTests.cs:14]: Good catch — the tests are failing on Mono because the pdb path isn't located next to the assemblies. I've set SkipOnPlatform and will close https://github.com/dotnet/runtime/issues/51399.

**Review by vitek-karas — APPROVED** [review]
