### PR TITLE
[mono] Fix the long opcode decompose pass when using llvm.

### LINKED ISSUE #53546: [wasm][aot] Windows: `mono-aot-cross` crashes with 0xC0000374 compiling `MessagePack.dll`
Based off #53314 .

Steps to reproduce:

- install dotnet preview 4 (dotnet.microsoft.com/download/dotnet/6.0), into a system location
- install the workload packs with: dotnet workload install microsoft-net-sdk-blazorwebassembly-aot. You would need to run that as root
- create a new blazor project with dotnet new blazorwasm
- Add `<RunAOTCompilation>true</RunAOTcompilation>`, and `<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="6.0.0-preview.4.21253.5" />` to the project
- build with `dotnet publish -c:release -p:RunAOTCompilation=true -bl`

Fails while running `mono-aot-cross` for `MessagePack.dll`:

```
Running: C:\Program Files\dotnet\packs\microsoft.netcore.app.runtime.aot.win-x64.cross.browser-wasm\6.0.0-preview.4.21222.10\Sdk\..\tools\mono-aot-cross.exe --debug
--llvm "--aot=no-opt,static,direct-icalls,deterministic,nodebug,llvm-path=C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.12.Sdk.win-x64\6.0.0-preview.4.21220.1\tools\bin\,llvmonly,interp,asmonly,llvm-outfile=C:\dev\bl0\obj\release\net6.0\wasm\MessagePack.dll.bc" MessagePack.dll (TaskId:134)
       Using working directory: C:\dev\bl0\obj\release\net6.0\linked (TaskId:134)
       Setting environment variables for execution: (TaskId:134)
           MONO_PATH = C:\dev\bl0\obj\release\net6.0\linked;C:\Users\Ankit Jain\.nuget\packages\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.4.21253.7\runtimes\browser-wasm\native\;C:\Users\Ankit Jain\.nuget\packages\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.4.21253.7\runtimes\browser-wasm\\lib\net6.0 (TaskId:134)
           MONO_ENV_OPTIONS =  (TaskId:134)

Exit code: -1073740940 (TaskId:134)

System.Exception: Error:

  at Utils.RunProcess(String path, String args, IDictionary`2 envVars, String workingDir, Boolean ignoreErrors, Boolean silent, MessageImportance outputMessageImportance, MessageImportance debugMessageImportance) in MonoAOTCompiler.dll:token 0x600002f+0x1fd
  at MonoAOTCompiler.PrecompileLibrary(ITaskItem assemblyItem, String monoPaths) in MonoAOTCompiler.dll:token 0x600002b+0x436 (TaskId:134)
```

exit code `-1073740940`(0xC0000374, heap corruption?)

cc @vargaz @lewing @radekdoulik @steveisok

### PR DESCRIPTION
**Pull request by vargaz**
It was replacing 64 bit opcodes with 32 bit ones while keeping the input/output 64 bit
vregs, leading to memory overwrites in later passes. Instead simply keep the 64
bit opcodes, llvm can handle them.

Fixes https://github.com/dotnet/runtime/issues/53546.

### CODE REVIEW

**Comment by BrzVlad** [comment]
@vargaz what about non-llvm 32 bit targets ?

**Comment by vargaz** [comment]
Those don't have this problem because LREG=IREG on 64 bit.

**Comment by BrzVlad** [comment]
I'm asking about arm/x86 where we don't implement opcodes like `OP_LCONV_TO_I4` and we need to decompose them ?

**Comment by vargaz** [comment]
decompose_long_opcode () is called like:
#if SIZEOF_REGISTER == 8
		if (decompose_long_opcode (cfg, ins, &repl))
			emulate = FALSE;
#else
		if (COMPILE_LLVM (cfg) && decompose_long_opcode (cfg, ins, &repl))
			emulate = FALSE;
#endif
So its only called on 64 bit, and llvm+32 bit.

**Review by naricc — APPROVED** [review]
I approved this, but maybe some one who actually understands the compiler better should also take a look :)

**Review by radekdoulik — COMMENTED** [review]
I have checked that it fixes the problem causing https://github.com/dotnet/runtime/issues/56526. The problematic performance microbenchmark runs fine with this change.

File: src/mono/mono/mini/decompose.c [hunk 1]
```diff
@@ -36,7 +36,10 @@ decompose_long_opcode (MonoCompile *cfg, MonoInst *ins, MonoInst **repl_ins)
 
 	switch (ins->opcode) {
 	case OP_LCONV_TO_I4:
-		ins->opcode = OP_SEXT_I4;
+		if (TARGET_SIZEOF_VOID_P == 4)
+			;
+		else
+			ins->opcode = OP_SEXT_I4;
```
Comment (imhameed) [inline src/mono/mono/mini/decompose.c:42]: Wouldn't we only want this for non-LLVM 64-bit? `process_bb` already has a case for `OP_LCONV_TO_I4` that does what you'd expect.

**Comment by BrzVlad** [comment]
Ok. I got confused between `mono_decompose_long_opts` and `decompose_long_opcode`. I see now that `mono_decompose_long_opts` already does what I was trying to do in my commit.

**Review by BrzVlad — APPROVED** [review]

File: src/mono/mono/mini/decompose.c (hunk 1 above)
Comment (vargaz) [reply src/mono/mono/mini/decompose.c:42]: Not sure, didn't want to make larger changes close to the release.
