### PR TITLE
JIT: Fix asserts from #112728

### LINKED ISSUE #113829: JIT: Assertion failed `genTypeSize(op1) == genTypeSize(simdBaseType)` during 'Lowering nodeinfo'
```csharp
// Generated by Fuzzlyn v2.5 on 2025-03-23 15:10:25
// Run on X64 Windows
// Seed: 14181260275910254012-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86avx512fx64,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 68.9 KiB to 0.3 KiB in 00:01:38
// Hits JIT assert in Debug:
// Assertion failed 'genTypeSize(op1) == genTypeSize(simdBaseType)' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Lowering nodeinfo' (IL size 20; hash 0xade6b36b; MinOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\lowerxarch.cpp Line: 4086
// 
using System.Runtime.Intrinsics;

public class C0
{
    public sbyte F4;
}

public class Program
{
    public static void Main()
    {
        var vr4 = new C0();
        Vector128.CreateScalar((short)vr4.F4);
    }
}
```

Bisected to #112728, cc @saucecontrol 

cc @dotnet/jit-contrib

### LINKED ISSUE #113832: JIT: Assertion failed `(consume == 0) || (ComputeAvailableSrcCount(tree) == consume)` during 'Linear scan register alloc'
```csharp
// Generated by Fuzzlyn v2.5 on 2025-03-23 15:25:27
// Run on X86 Windows
// Seed: 916448399438567841-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86bmi1,x86bmi2,x86fma,x86lzcnt,x86pclmulqdq,x86popcnt,x86sse,x86sse2,x86sse3,x86sse41,x86sse42,x86ssse3,x86x86base
// Reduced from 63.4 KiB to 0.7 KiB in 00:02:21
// Hits JIT assert in Release:
// Assertion failed '(consume == 0) || (ComputeAvailableSrcCount(tree) == consume)' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Linear scan register alloc' (IL size 68; hash 0xade6b36b; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\lsrabuild.cpp Line: 1776
// 
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static byte s_4;
    public static void Main()
    {
        var vr9 = Vector128.Create<ulong>(0);
        var vr10 = (ulong)s_4;
        var vr11 = Vector128.CreateScalar(vr10);
        var vr12 = Avx2.BroadcastScalarToVector128(vr11);
        var vr13 = (byte)0;
        var vr14 = Vector256.CreateScalar(vr13);
        var vr15 = (ulong)Avx2.MoveMask(vr14);
        var vr16 = Vector128.Create<ulong>(vr15);
        var vr17 = Avx512F.VL.TernaryLogic(vr9, vr12, vr16, 1);
        System.Console.WriteLine(vr17);
    }
}
```

Note that when I try this locally with AltJit (since I don't have an AVX512 CPU) I get a different assert:
```
Assert failure(PID 34784 [0x000087e0], Thread: 20004 [0x4e24]): Assertion failed 'unreached' in 'Program:Main()' during 'Generate code' (IL size 61; hash 0xcb019401; FullOpts)

    File: C:\dev\dotnet\runtime4\src\coreclr\jit\instr.cpp:1049
    Image: D:\dev\core_roots\16236fdcd417dcfc700e55dd7ae76365ceb7ff87\corerun.exe
```
I've bisected this to #112728, so I assume the original assert seen by Fuzzlyn is also related to that PR. cc @saucecontrol 

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by saucecontrol**
Fixes #113829
Fixes #113832

Both asserts from #113829 were testing assumptions that should have been checked in the condition instead.  Since casts from small types both have TYP_INT actual type, either byte or short args match the IR type for either overload of `Vector###.Create`, so an extra cast is needed when the sizes don't match.

#113832 is a case where `BroadcastScalarToVector` was allowed to contain `CreateScalar([GT_LONG])`. There was already a check that prevented containment of `CreateScalarUnsafe` of a decomposed long, and `CreateScalar` should have followed the same path.

### CODE REVIEW

File: src/coreclr/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -9665,6 +9664,12 @@ void Lowering::ContainCheckHWIntrinsic(GenTreeHWIntrinsic* node)
                         {
                             GenTreeHWIntrinsic* childNode = op1->AsHWIntrinsic();
 
+                            if (childNode->Op(1)->OperIsLong())
```
Comment (jakobbotsch) [inline src/coreclr/jit/lowerxarch.cpp:9667]: What guarantees the child node is an intrinsic that has any operands?

**Comment by jakobbotsch** [comment]
> @jakobbotsch do any/all of these need regression tests? In hindsight, they were kind of obvious misses, but they don't have any test coverage outside Fuzzlyn.

It would be nice.

File: src/coreclr/jit/lowerxarch.cpp (hunk 1 above)
Comment (saucecontrol) [reply src/coreclr/jit/lowerxarch.cpp]: Moved this bailout back to where it was. The handling for CreateScalar should be the same as for CreateScalarUnsafe.

File: src/tests/JIT/Regression/JitBlue/Runtime_113829/Runtime_113829.cs [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+{
+    [Fact]
+    public static void Problem()
+    {
+        var vr4 = new C0();
+        Vector128.CreateScalar((short)vr4.F4);
+    }
+
+    [Fact]
+    public static Vector256<short> Problem2()
```
Comment (jakobbotsch) [inline src/tests/JIT/Regression/JitBlue/Runtime_113829/Runtime_113829.cs:33]: Not sure if the test infrastructure will be happy with this type of return value, but let's see.

**Review by jakobbotsch — APPROVED** [review]
LGTM

File: src/tests/JIT/Regression/JitBlue/Runtime_113829/Runtime_113829.cs (hunk 2 above)
Comment (saucecontrol) [reply src/tests/JIT/Regression/JitBlue/Runtime_113829/Runtime_113829.cs]: Dangit. I had to modify that one to get it to repro in Disasmo and forgot to change it back.  Fixed.

**Comment by jakobbotsch** [comment]
/ba-g Failures are azurelinux timeouts and #113877

**Comment by jakobbotsch** [comment]
Thanks for the quick fixes.
