### PR TITLE
JIT: Import string.Empty as ""

### LINKED ISSUE #42694: RyuJIT: String.Empty vs ""
It looks like some of the jit optimizations aren't `String.Empty` friendly and prefer `""` instead, e.g.:
### Inliner
```csharp
class Tests
{
    static int GetLengthWithLimit(string str) => str.Length > 10 ? str.Length : 0;

    // I expect both Case1 and Case2 to have the same codegen:
    int Case1() => GetLengthWithLimit("");
    int Case2() => GetLengthWithLimit(string.Empty);
}
```
Current codegen for `Case1` and `Case2`:
```asm
; Method Case1():int:this
       33C0                 xor      eax, eax    ;; <--- inlined & folded into `return 0;`
       C3                   ret      
; Total bytes of code: 3


; Method Case2():int:this
       48B9603000E9D7010000 mov      rcx, 0x1D7E9003060
       488B09               mov      rcx, gword ptr [rcx]
       E95E81FFFF           jmp      Tests:GetLengthWithLimit(System.String):int    ;; <--- not even inlined!
; Total bytes of code: 18
```
JIT [imports](https://github.com/dotnet/runtime/blob/fa8fb1ddfddb754dee3161e335d6a021ac6055d4/src/coreclr/src/jit/importer.cpp#L14613-L14616) `string.Empty` as a  `GT_IND + <address>` node whether `""` is emitted as `GT_CNS_STR` (which is then transformed into `GT_IND + <address>` later but the optimizations expect `GT_CNS_STR`). Since `GT_CNS_STR` node is know to be a const (has `GTK_CONST` flag), the inliner for the second case (Case2) has:
```
Inline candidate has **const arg** that feeds a conditional.  Multiplier increased to 5.
```
and doesn't have it for `Case1`.

### String.get_Length optimization
This optimization also supports only GT_CNS_STR nodes, e.g:
```csharp
int Case1() => "".Length;
int Case2() => string.Empty.Length;
```
Codgen:
```asm
; Method Case1():int:this
       33C0                 xor      eax, eax
       C3                   ret      


; Method Case2():int:this
       488B00               mov      rax, gword ptr [rax]
       8B4008               mov      eax, dword ptr [rax+8]
       C3                   ret   
```

I wonder if we can easily fix it by importing `String.Empty` as a fake (or real) `GT_CNS_STR` node like this: https://github.com/EgorBo/runtime-1/commit/09f81b1a9b49f89d51a68f2229b9820beb7c694c (this prototype fixes both issues above ^)

Jit-diff: https://gist.github.com/EgorBo/c6c12e79b7b90ff7aaee58f3fb5a49fb (diff is a "regression" because the fix allows to inline more stuff)
/cc @dotnet/jit-contrib 

category:cq
theme:basic-cq
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by EgorBo**
A better version of https://github.com/dotnet/runtime/pull/44847, it now saves mdToken of actual "" in VM and JIT just asks VM for it.
Extends effect of https://github.com/dotnet/runtime/pull/63734 for `string.Empty`

Example:
```csharp
int Test1() => string.Empty.Length; // e.g. after inlining

bool Test2(string s) => s == string.Empty; // is string empty?
```
Current codegen:
```asm
; Method Tests:Test1():int:this
G_M28758_IG01:
G_M28758_IG02:
       mov      rax, 0xD1FFAB1E      ; ""
       mov      rax, gword ptr [rax]
       mov      eax, dword ptr [rax+8]
G_M28758_IG03:
       ret      
; Total bytes of code: 17


; Method Tests:Test2(System.String):bool:this
G_M31606_IG01:
       push     rax
G_M31606_IG02:
       mov      r8, 0xD1FFAB1E      ; ""
       mov      r8, gword ptr [r8]
       cmp      rdx, r8
       jne      SHORT G_M31606_IG04
G_M31606_IG03:
       mov      eax, 1
       jmp      SHORT G_M31606_IG08
G_M31606_IG04:
       test     rdx, rdx
       je       SHORT G_M31606_IG05
       mov      ecx, dword ptr [rdx+8]
       cmp      ecx, dword ptr [r8+8]
       je       SHORT G_M31606_IG06
G_M31606_IG05:
       xor      eax, eax
       jmp      SHORT G_M31606_IG08
G_M31606_IG06:
       mov      eax, dword ptr [r8+8]
       add      rdx, 12
       add      r8, 12
       mov      bword ptr [rsp], r8
       add      ecx, ecx
       mov      r8d, ecx
       mov      rcx, rdx
       mov      rdx, bword ptr [rsp]
G_M31606_IG07:
       add      rsp, 8
       jmp      System.SpanHelpers:SequenceEqual(byref,byref,long):bool
G_M31606_IG08:
       add      rsp, 8
       ret      
; Total bytes of code: 86
```
New codegen:
```asm
; Method Tests:Test1():int:this
G_M28758_IG01:
G_M28758_IG02:
       xor      eax, eax
G_M28758_IG03:
       ret      
; Total bytes of code: 3


; Method Tests:Test2(System.String):bool:this
G_M31606_IG01:
G_M31606_IG02:
       test     rdx, rdx
       je       SHORT G_M31606_IG04
G_M31606_IG03:
       cmp      dword ptr [rdx+8], 0
       sete     al
       movzx    rax, al
       jmp      SHORT G_M31606_IG05
G_M31606_IG04:
       xor      eax, eax
G_M31606_IG05:
       ret      
; Total bytes of code: 20
```

Closes https://github.com/dotnet/runtime/issues/42694

### CODE REVIEW

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -15115,9 +15115,20 @@ void Compiler::impImportBlockCode(BasicBlock* block)
                     {
                         assert(aflags & CORINFO_ACCESS_GET);
 
-                        LPVOID         pValue;
-                        InfoAccessType iat = info.compCompHnd->emptyStringLiteral(&pValue);
-                        op1                = gtNewStringLiteralNode(iat, pValue);
+                        // Try to import String.Empty as "" (GT_CNS_STR) if VM has a mdToken for ""
+                        uint32_t emptyStrTok = info.compCompHnd->getEmptyStringMdToken();
```
Comment (jkotas) [inline src/coreclr/jit/importer.cpp:15119]: This is not pretty. Why is the metadata token needed to make the JIT happy? Can the JIT assume that e.g. token with value of `0` means empty string instead?

**Comment by am11** [comment]
> ```assembly
> ; Method Tests:Test2(System.String):bool:this
> ```

Would be cooler if we could  eliminate extra move and jump like naive compilers do: https://godbolt.org/z/7r7fbr9Y6, but this is great work as-is!, thanks :+1:

File: src/coreclr/jit/importer.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/importer.cpp:15119]: @jkotas what you suggest was my initial implementation: https://github.com/dotnet/runtime/pull/44847/commits/4f9d795f02606ddbb2f2d061c7e6585735f8aa4d

in this PR I'm addressing https://github.com/dotnet/runtime/pull/44847#pullrequestreview-556647573 cc @AndyAyersMS

Comment (jkotas) [reply src/coreclr/jit/importer.cpp:15119]: > what you suggest was my initial implementation: 4f9d795

I think that was better.

In general, methods on JIT/EE interface that return tokens are anti-pattern. The JIT/EE interface should always go from token to runtime entity like handle, pointer or offset.

Comment (jkotas) [reply src/coreclr/jit/importer.cpp]: The main problem in the original implementation was the static cache. I think you can replace the static cache by picking up a number that cannot be a valid string token, like `0` or `-1`.

Comment (EgorBo) [reply src/coreclr/jit/importer.cpp]: Switched to JIT-only change (SconCPX == 0), previous impl is here https://github.com/EgorBo/runtime-1/commit/15a47c2660fe5b9e2149b20361a6f6645575d66e

**Comment by jkotas** [comment]
> Set module to corelib, just in case

What's the point of this change? I think it can only mask real problems.

**Comment by EgorBo** [comment]
> > Set module to corelib, just in case
> 
> What's the point of this change? I think it can only mask real problems.

You're right, if anyone introduce a new EE-JIT api to work with strings or use any of the existing ones in a new place - it should crash if `if (IsStringEmptyField())` won't be used

**Comment by EgorBo** [comment]
PTAL @dotnet/jit-contrib 

Diffs: https://dev.azure.com/dnceng/public/_build/results?buildId=1582186&view=ms.vss-build-web.run-extensions-tab

A lot of size regressions due to inlining (along with improvements). Now, when the inliner sees a GT_CNS_STR it considers it as a constant argument so all operations on this argument in callees are considered foldable including branches leading to bigger "benefit multipliers". Example: https://www.diffchecker.com/mLb1tijN (see https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.Xml/src/System/Xml/Serialization/SoapAttributeOverrides.cs#L41)

Unfortunately, there is a faulty (too optimistic) heuristic "if I see an unknown call and we have a const argument on stack - the call most likely returns another const" - I am going to remove it, it's responsible for huge diffs in general.

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -5793,6 +5793,12 @@ GenTree* Compiler::gtNewStringLiteralNode(InfoAccessType iat, void* pValue)
 //
 GenTreeIntCon* Compiler::gtNewStringLiteralLength(GenTreeStrCon* node)
 {
+    if (node->IsStringEmptyField())
+    {
+        JITDUMP("Folded String.Empty.Length to 0");
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.cpp:5798]:
```suggestion
        JITDUMP("Folded String.Empty.Length to 0\n");
```

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 3]
```diff
@@ -3278,7 +3278,9 @@ private bool canGetVarArgsHandle(CORINFO_SIG_INFO* pSig)
 
         private InfoAccessType emptyStringLiteral(ref void* ppValue)
         {
-            return constructStringLiteral(_methodScope, (mdToken)CorTokenType.mdtString, ref ppValue);
+            ISymbolNode stringObject = _compilation.NodeFactory.SerializedStringObject("");
```
Comment (am11) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:3281]: Unlike `src/coreclr/tools/aot/ILCompiler.Compiler/ILCompiler.Compiler.csproj`,
`src/coreclr/tools/aot/ILCompiler.ReadyToRun/ILCompiler.ReadyToRun.csproj` and `src/coreclr/tools/aot/ILCompiler.RyuJit/ILCompiler.RyuJit.csproj`, both files are missing the partial that has `SerializedStringObject()` definition:

```xml
    <Compile Include="Compiler\DependencyAnalysis\NodeFactory.cs" />
    <!-- may also need -->
    <Compile Include="Compiler\DependencyAnalysis\NodeFactory.GenericLookups.cs" />
    <Compile Include="Compiler\DependencyAnalysis\NodeFactory.NativeLayout.cs" />
```

Comment (EgorBo) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs]: Yeah thanks, turns out there was an issue in NativeAOT - `constructStringLiteral` when called by `emptyStringLiteral` could silently crash with `IndexOutOfBoundsException` and that was not reported, some how my PR made it more visible, but if you take Main and try to build `Reflection_ReflectedOnly.ilc.rsp` with first chance exceptions enabled you will see it.

`methodIL` is `ILStubMethodIL` and the method it fails on is `[S.P.CompilerGenerated]Internal.CompilerGenerated.<Module>.Format(string)`

Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs]: Yeah, NativeAOT sometimes asks RyuJIT to compile IL that doesn't come from a file on disk, but was synthesized by the compiler. RyuJIT making up a token and asking questions about it doesn't work well with that, even though it's a ECMA-spec-defined token. We could potentially fix this in `GetObject` too since the token value is defined by the spec, but this will do.
