### PR TITLE
Fix JIT TARGET usage

### LINKED ISSUE #31372: Distributed Context in ASP.NET and Open Telemetry
This issue is tracking the work that needs to be done for supporting the distributed context scenarios for ASP.NET and [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-specification).

Here are the scenarios we need to support: 

## Distributed Context scenarios
These scenarios talking about ILogger and OpenTelemetry scenarios. OpenTelemetry has a goal to implement all these scenarios if you replace “ILogger” with “OpenTelemetry Logging API”. The goal of this document is to come up with scenarios that will not require OpenTelemetry to introduce new concepts and libraries. And out-of-the-box ASP.NET apps be more distributed apps friendly.

### Out of the box ASP.NET application
- Distributed trace identifiers are automatically propagated through the app. This enables the correlation of telemetry across multiple components even when only a subset of these components has monitoring enabled.
Note: This is already implemented via DiagnosticsSource.Activity. 

- Log messages and exceptions are automatically associated with the distributed trace identifiers. This allows pinpointing the root cause of the problem faster by associating logs and exceptions with the downstream components that might have caused the problem or upstream - components providing incorrect data.
Note: This is partially implemented - trace-id and span-id of a topmost request are added to the ILogger scope.

- Users may output distributed trace identifiers as part of an error page for the app user reference. This allows improving application supportability by providing a fast lookup reference that will simplify customer communication with support personnel.

### Scoping of distributed logs
- The developer may add a name/value pairs to the scope of execution. This name/value pair will be associated with all logs captured in this scope
	Note: this is an existing ILogger feature

- The developer may configure some of the name/value pairs in scope to be distributed. These scope values will be transmitted over the wire and associated with the logs reported by downstream services. This feature enables scenarios like clients sending client app versions as a context property and all logs across many layers of a distributed trace will be attributed to it.

### ASP.NET app with OpenTelemetry enabled
- When OpenTelemetry is enabled - all logs reported by ILogger must bye be attributed with the OpenTelemetry span identity. So telemetry reported by OpenTelemetry and ILogger can be cross-referenced.

- Spans reported by OpenTelemetry can use the scope’s name/value pairs configured by the customer for ILogger as dimensions for telemetry. This will ensure that OpenTelemetry benefits from app attribution made by the developer for better diagnostics experience. This includes both - local and distributed contexts.

### Metrics and scopes
- Metrics aggregation in OpenTelemetry may use the scope’s name/value pairs as a dimension for aggregation based on configuration. This includes both - local and distributed contexts.

- EventCounters may use the scope’s name/value pairs as a dimension for aggregation. This includes both - local and distributed contexts.

### Distributed “HTTP context”
- The developer must be able to set up business-critical properties that can be used across the entire distributed trace.

## Tracked work items:

- [x] [Make Activity and Span the same.](https://github.com/dotnet/runtime/issues/31373) @tarekgh
- [x] [Add Ids and Context to all logs.](https://github.com/dotnet/runtime/issues/34305) @tarekgh
- [ ] [Distributed Context API (distributed http context)](https://github.com/dotnet/runtime/issues/31393). Should be in a separate library. @tarekgh
    * string/string
    * Scope-able
    * Not attached to Activity

Ref: 
[OpenTelemetry .NET  implementation](https://github.com/open-telemetry/opentelemetry-dotnet)
[Improvements in .NET Core 3.0 for troubleshooting and monitoring distributed apps blog](https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/)

CC @SergeyKanzhelev @pakrym

### LINKED ISSUE #31732: Clean up target defines in JIT
There are a number of inconsistencies in the use of the target defines in the JIT. Some are remnants from #2256 which didn't rename the use of the macros in comments, and some are pre-existing (and of more concern).

These look like actual mistakes/bugs:
 - optcse.cpp: `#elif _TARGET_ARM32`
 - gentree.cpp: `#if defined(_TARGET_XARCH4_) && defined(FEATURE_HW_INTRINSICS)` (this just protects a bunch of asserts)

Occurrences of these in comments should be cleaned up :
- Rename `_TARGET_xxx_` or `_TARGET_xxx` to `TARGET_xxx` (note that there are a few `_TARGET_xxx` without the trailing `_` in comments)

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes `_TARGET*` & `TARGET*_` comments

Fixes TARGET_XARCH4 reference to TARGET_XARCH

Fixes #31732

### CODE REVIEW

File: src/coreclr/src/jit/compiler.h [hunk 1]
```diff
@@ -1608,7 +1608,7 @@ struct fgArgTabEntry
 
     bool isPassedInFloatRegisters()
     {
-#ifdef _TARGET_X86
+#ifdef TARGET_X86
```
Comment (sdmaclea) [inline src/coreclr/src/jit/compiler.h]: Note: Functional change.

File: src/coreclr/src/jit/gentree.cpp [hunk 2]
```diff
@@ -16759,7 +16759,7 @@ GenTree* Compiler::gtGetSIMDZero(var_types simdType, var_types baseType, CORINFO
                 }
                 break;
 
-#if defined(_TARGET_XARCH4_) && defined(FEATURE_HW_INTRINSICS)
+#if defined(TARGET_XARCH) && defined(FEATURE_HW_INTRINSICS)
```
Comment (sdmaclea) [inline src/coreclr/src/jit/gentree.cpp]: Note: Functional change.

File: src/coreclr/src/jit/optcse.cpp [hunk 3]
```diff
@@ -1664,7 +1664,7 @@ class CSE_Heuristic
                 largeFrame = true;
                 break; // early out,  we don't need to keep increasing frameSize
             }
-#elif _TARGET_ARM32
+#elif TARGET_ARM
```
Comment (sdmaclea) [inline src/coreclr/src/jit/optcse.cpp]: Note: Functional change.

File: src/coreclr/src/jit/gentree.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/gentree.cpp]: Functional only for checked or debug builds, as the code in this `#if` only includes asserts.

File: src/coreclr/src/jit/importer.cpp [hunk 4]
```diff
@@ -14120,9 +14120,9 @@ void Compiler::impImportBlockCode(BasicBlock* block)
 
                 lclTyp = JITtype2varType(ciType);
 
-#ifdef _TARGET_AMD64
+#ifdef TARGET_AMD64
                 noway_assert(varTypeIsIntegralOrI(lclTyp) || varTypeIsFloating(lclTyp) || lclTyp == TYP_STRUCT);
```
Comment (CarolEidt) [inline src/coreclr/src/jit/importer.cpp]: @dotnet/jit-contrib @BruceForstall - this is a `noway_assert` that has apparently been inactive for at least some time. Should it simply be eliminated?

File: src/coreclr/src/jit/optcse.cpp (hunk 3 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/optcse.cpp]: @briansull - could you comment on this one?

**Review by CarolEidt — COMMENTED** [review]
This LGTM - thanks @sdmaclea! -  but I'd like to get @briansull to give an opinion on the optcse.cpp change.

File: src/coreclr/src/jit/optcse.cpp (hunk 3 above)
Comment (BruceForstall) [inline src/coreclr/src/jit/optcse.cpp]: This should be `#elif defined(TARGET_ARM)` (similar change below for ARM64) -- not related to this change

File: src/coreclr/src/jit/target.h [hunk 5]
```diff
@@ -3,8 +3,8 @@
 // See the LICENSE file in the project root for more information.
 
 /*****************************************************************************/
-#ifndef _TARGET_H_
```
Comment (BruceForstall) [inline src/coreclr/src/jit/target.h]: You should leave this file alone

File: src/coreclr/src/jit/importer.cpp (hunk 4 above)
Comment (BruceForstall) [reply src/coreclr/src/jit/importer.cpp]: Seems reasonable to just delete, but someone more familiar with the importer than I should make the call.

**Review by BruceForstall — APPROVED** [review]
Thanks for the change!

I'd recommend triggering an outerloop job due to the functional changes that could trigger new asserts.

File: src/coreclr/src/jit/importer.cpp (hunk 4 above)
Comment (AndyAyersMS) [reply src/coreclr/src/jit/importer.cpp]: You might be the best one to make a call on this; it apparently came in with dotnet/coreclr#2545...
```
git blame -L 14047 -- importer.cpp
05b0c2cfdf0b (Carol Eidt                                           2015-12-08 18:15:15 -0800 14047) #ifdef _TARGET_AMD64
```

Comment (CarolEidt) [reply src/coreclr/src/jit/importer.cpp]: I don't think it's useful, since `JITtype2varType` will always return one of these for a field. I would vote to delete it.

Comment (AndyAyersMS) [reply src/coreclr/src/jit/importer.cpp]: Fine by me.

**Review by AndyAyersMS — APPROVED** [review]

**Review by briansull — APPROVED** [review]

File: src/coreclr/src/jit/target.h (hunk 5 above)
Comment (sdmaclea) [reply src/coreclr/src/jit/target.h]: @lpereira Pointed out that the use of identifiers with a leading underscore followed by a capital letter is reserved for the compiler host implementation in C/C++.  I fixed this now, because it showed up in my search.

**Comment by sdmaclea** [comment]
> I'd recommend triggering an outerloop job

@BruceForstall I'll let you trigger outerloop and merge when you think it is ready.  The no way assert was removed. The new assert are probably minimal now.

@AndyAyersMS mentioned running a jit-diff to see if the optcse change affected anything.

**Comment by CarolEidt** [comment]
Thanks @sdmaclea !
