### PR TITLE
[mono] Prevent memory corruption when decoding UCO entry point

### LINKED ISSUE #86264: [mono] FullAOT compilation of Microsoft.iOS.dll crashes with managed static registrar
## Problem

Managed static registrar - (MSR further in the text),  is a new Xamarin feature being introduced via: https://github.com/xamarin/xamarin-macios/pull/18268

The feature is been tested in the PR and works correctly with `.NET7`. However, when using the current - `.NET8 preview 5` version of the MonoAOT compiler and `MSR`, AOT compilation of `Microsoft.iOS.dll` crashes with the following error message:
```
mono-aot-cross(68995,0x1df9cdb40) malloc: Incorrect checksum for freed object 0x12674acd8: probably modified after being freed.
Corrupt value: 0x1311c010120041c
``` 

## Repro

1. Merge: https://github.com/rolfbjarne/xamarin-macios/tree/msr into https://github.com/xamarin/xamarin-macios/tree/main
2. Merge: https://github.com/xamarin/xamarin-macios/tree/main into https://github.com/xamarin/xamarin-macios/tree/net8.0
3. Build the repo:
```
make world
```
4. Navigate to `MySingleView` sample:
```
cd tests/dotnet/MySingleView
```
5. Build the sample:
```
../../../builds/downloads/dotnet-sdk-8.0.100-preview.5.23258.8/dotnet build -c Debug /bl /t:Run -r ios-arm64 -p:MtouchExtraArgs=--registrar:managed-static
```
6. The build should fail with:
```
Tool /Users/ivan/repos/xamarin/xamarin-macios/builds/downloads/dotnet-sdk-8.0.100-preview.5.23258.8/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/8.0.0-preview.5.23252.13/Sdk/../tools/mono-aot-cross execution finished (exit code = 134).
          
/Users/ivan/repos/xamarin/xamarin-macios/builds/downloads/dotnet-sdk-8.0.100-preview.5.23258.8/packs/Microsoft.iOS.Sdk/16.4.8451-ci.net8-0-msr/targets/Xamarin.Shared.Sdk.targets(1082,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 134 [/Users/ivan/repos/xamarin/xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj]
  Tool /Users/ivan/repos/xamarin/xamarin-macios/builds/downloads/dotnet-sdk-8.0.100-preview.5.23258.8/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/8.0.0-preview.5.23252.13/Sdk/../tools/mono-aot-cross execution finished (exit code = 139).
          
/Users/ivan/repos/xamarin/xamarin-macios/builds/downloads/dotnet-sdk-8.0.100-preview.5.23258.8/packs/Microsoft.iOS.Sdk/16.4.8451-ci.net8-0-msr/targets/Xamarin.Shared.Sdk.targets(1082,3): error : Failed to AOT compile Microsoft.iOS.dll, the AOT compiler exited with code 139 [/Users/ivan/repos/xamarin/xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj]

Build FAILED.
```
7. Set `MONO_PATH`
```
export MONO_PATH=/Users/ivan/repos/xamarin/xamarin-macios/tests/dotnet/MySingleView/obj/Debug/net8.0-ios/ios-arm64/linked
```
8. AOT Compile `Microsoft.iOS.dll` with:
```
/Users/ivan/repos/xamarin/xamarin-macios/builds/downloads/dotnet-sdk-8.0.100-preview.5.23258.8/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/8.0.0-preview.5.23252.13/Sdk/../tools/mono-aot-cross --aot=mtriple=arm64-ios,data-outfile=obj/Debug/net8.0-ios/ios-arm64/nativelibraries/aot-output/arm64/Microsoft.iOS.aotdata,static,asmonly,dedup-skip,direct-icalls,full,readonly-value=ObjCRuntime.Runtime.Arch=i4/0,dwarfdebug,no-direct-calls,outfile=obj/Debug/net8.0-ios/ios-arm64/nativelibraries/aot-output/arm64/Microsoft.iOS.dll.s --debug -O=gsharedvt /Users/ivan/repos/xamarin/xamarin-macios/tests/dotnet/MySingleView/obj/Debug/net8.0-ios/ios-arm64/linked/Microsoft.iOS.dll
```
9. AOT compiler throws with:
```
Mono Ahead of Time compiler - compiling assembly /Users/ivan/repos/xamarin/xamarin-macios/tests/dotnet/MySingleView/obj/Debug/net8.0-ios/ios-arm64/linked/Microsoft.iOS.dll
AOTID 5D36E7A7-60A5-F99E-9CCD-F2A9D006C9A5
mono-aot-cross(2918,0x203a1f280) malloc: Incorrect checksum for freed object 0x7fa39b047bd0: probably modified after being freed.
Corrupt value: 0x9000000000071112
mono-aot-cross(2918,0x203a1f280) malloc: *** set a breakpoint in malloc_error_break to debug
```
---

/cc: @rolfbjarne @filipnavara @kotlarmilos

### PR DESCRIPTION
**Pull request by ivanpovazan**
### Description

This PR fixes an issue with memory corruption when MonoAOT compiler decodes the name of the exported symbols specified via `EntryPoint` of a `UnmanagedCallersOnly` method.

The offending lines were assuming that the entry point string in the metadata blob is null terminated, which caused `sprintf` to corrupt the memory around `export_name`.

I haven't been able to reproduce the issue with a smaller example other than how it is described in the tracking issue. If I manage to find a simple repro, I will add a unit test.

PS Not sure how this was not noticed before. One possibility is that the UCOs causing the problem have different encoding in the metadata blob, as they are generated by Cecil library not Roslyn.

--- 

Fixes #86264

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

File: src/mono/mono/mini/aot-compiler.c [hunk 1]
```diff
@@ -5352,10 +5352,16 @@ MONO_RESTORE_WARNING
 				for (j = 0; j < decoded_args->named_args_num; ++j) {
 					if (decoded_args->named_args_info [j].field && !strcmp (decoded_args->named_args_info [j].field->name, "EntryPoint")) {
 						named = (const char *)decoded_args->named_args[j]->value.primitive;
-						slen = mono_metadata_decode_value (named, &named) + (int)strlen(acfg->user_symbol_prefix);
-						export_name = (char *)g_malloc (slen + 1);
-						sprintf (export_name, "%s%s", acfg->user_symbol_prefix, named);
```
Comment (filipnavara) [inline src/mono/mono/mini/aot-compiler.c:5357]: FWIW this could have been modified to
```
namedlen = mono_metadata_decode_value (named, &named);
slen = namedlen + (int)strlen(acfg->user_symbol_prefix);
export_name = (char *)g_malloc (slen + 1);
sprintf (export_name, "%s%.*s", acfg->user_symbol_prefix, namedlen, named);
```

**Review by lambdageek — APPROVED** [review]

File: src/mono/mono/mini/aot-compiler.c (hunk 1 above)
Comment (ivanpovazan) [reply src/mono/mono/mini/aot-compiler.c:5357]: Thank you for your suggestion. 
However, even though it achieves the same thing, I prefer not to use `sprintf` as originally it hid the underlying problem that was difficult to track down. So for that reason, I will keep it as is (simple and easily debuggable).

**Comment by ivanpovazan** [comment]
Failures are known and unrelated.
