### PR TITLE
Disable W^X on macOS under Rosetta emulation

### LINKED ISSUE #70758: .Net application aborts at startup with "Failed to create CoreCLR, HRESULT: 0x80004005" - .Net 7 preview 5
### Description

I have a project here: https://github.com/Webreaper/Damselfly which I upgraded to .Net 7 preview 5 this evening, and also updated EF Core and a bunch of other dependencies (https://github.com/Webreaper/Damselfly/compare/master...develop). 

The app compiles and runs fine on my M1 Macbook (I'm using VS for Mac 2022). However, when built and deployed to a docker container, and launched on Linux (I'm using a Synology NAS) it fails with:

`Failed to create CoreCLR, HRESULT: 0x80004005`

The same app launched fine built and ran (on both OSX and Linux) against .Net 7 preview 4. 

I'll do some additional tests tomorrow to see if I can narrow down to the specific update that cause this to break (i.e., is it .Net 7 preview 5 itself, or some other dep, or a combination of the two). The app is a Blazor Server app running as a self-contained single-file executable, but since it never gets as far as initialising the CLR I don't think that Blazor or ASP.Net is relevant. I've also tried disabling trimming, but it didn't resolve the issue.

I guess my first question is - how do I go about getting additional debugging information to figure out what's causing this problem?

### Reproduction Steps

Take my app, build and run it against .Net 7 preview 4. It works. Upgrade to preview 5, it fails to start. 

### Expected behavior

App runs successfully on both OSX and Linux.

### Actual behavior

App runs successfully on OSX, but on Linux the app fails to start with `Failed to create CoreCLR, HRESULT: 0x80004005`

### Regression?

Yes, this app worked with .Net 7 preview 4.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### LINKED ISSUE #70910: W^X double mapping doesn't work correctly on macOS under Rosetta emulation
Apple has reported that the memory double mapping we use for x64 macOS doesn't work under Rosetta correctly due to limitations of the emulation. The problem occurs when an existing code generated to a double mapped area is modified.

We need to disable W^X under Rosetta.

### PR DESCRIPTION
**Pull request by janvorli**
Apple has informed us that double mapping doesn't work properly
on Rosetta emulation. This change disables W^X if Rosetta is detected.

Close #70910

It also fixes a problem with W^X not being able to work on WSL1 and some Linux distro with kernel older than 3.17
Close #70758

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

File: src/coreclr/minipal/Unix/doublemapping.cpp [hunk 1]
```diff
@@ -23,6 +23,18 @@
...
+
+bool IsProcessTranslated()
+{
+   int ret = 0;
+   size_t size = sizeof(ret);
+   if (sysctlbyname("sysctl.proc_translated", &ret, &size, NULL, 0) == -1)
+   {
+      return false;
+   }
+   return ret != 0;
```
Comment (am11) [inline src/coreclr/minipal/Unix/doublemapping.cpp:36]: nit: in other places, we have used `== 1`:

https://github.com/dotnet/runtime/blob/051b4828c7d3a0cad3289830ef9fd2120f45bb2b/src/native/libs/System.Native/pal_runtimeinformation.c#L112
https://github.com/dotnet/runtime/blob/051b4828c7d3a0cad3289830ef9fd2120f45bb2b/src/native/corehost/hostmisc/pal.unix.cpp#L1090

Comment (janvorli) [reply src/coreclr/minipal/Unix/doublemapping.cpp:36]: Thank you @am11 for the info, I didn't know we already check for this somewhere.
