### PR TITLE
[release/5.0] Fix GCDesc::GetNumPointers for collectible types

### LINKED ISSUE #49684: Crash in GC
### Description
.NET Runtime crash in GC with stack:
```
[0x0]   coreclr!CGCDesc::GetNumPointers + 0x24   
[0x1]   coreclr!WKS::gc_heap::background_mark_simple1 + 0x10262a   
[0x2]   coreclr!WKS::gc_heap::background_mark_simple + 0x74   
[0x3]   coreclr!WKS::gc_heap::background_promote + 0x52   
[0x4]   coreclr!ScanConsecutiveHandlesWithoutUserData + 0x45   
[0x5]   coreclr!BlockScanBlocksWithoutUserData + 0x44   
[0x6]   coreclr!ProcessScanQNode + 0x44   
[0x7]   coreclr!ProcessScanQueue + 0x3f   
[0x8]   coreclr!xxxTableScanQueuedBlocksAsync + 0x5d   
[0x9]   coreclr!xxxAsyncSegmentIterator + 0x55   
[0xa]   coreclr!TableScanHandles + 0x7c   
[0xb]   coreclr!xxxTableScanHandlesAsync + 0x97   
[0xc]   coreclr!HndScanHandlesForGC + 0x10c   
[0xd]   coreclr!Ref_TracePinningRoots + 0x96   
[0xe]   coreclr!GCScan::GcScanHandles + 0xd4   
[0xf]   coreclr!WKS::gc_heap::background_mark_phase + 0x1244   
[0x10]   coreclr!WKS::gc_heap::gc1 + 0x1b5   
[0x11]   coreclr!WKS::gc_heap::bgc_thread_function + 0x90   
[0x12]   coreclr!<lambda_c5a49c859c7ba70587da980d74c056e1>::operator() + 0xa0   
[0x13]   kernel32!BaseThreadInitThunk + 0x14   
[0x14]   ntdll!RtlUserThreadStart + 0x21   
```
I tried to switch into Server GC but it crashed too:
```
[0x0]   coreclr!CGCDesc::GetNumPointers + 0x25   
[0x1]   coreclr!SVR::gc_heap::background_mark_simple1 + 0xf4   
[0x2]   coreclr!SVR::gc_heap::background_mark_simple + 0x96   
[0x3]   coreclr!SVR::gc_heap::background_promote + 0x11d   
[0x4]   coreclr!ScanConsecutiveHandlesWithoutUserData + 0x45   
[0x5]   coreclr!BlockScanBlocksWithoutUserData + 0x44   
[0x6]   coreclr!ProcessScanQNode + 0x44   
[0x7]   coreclr!ProcessScanQueue + 0x3f   
[0x8]   coreclr!xxxTableScanQueuedBlocksAsync + 0x5d   
[0x9]   coreclr!xxxAsyncSegmentIterator + 0x55   
[0xa]   coreclr!TableScanHandles + 0x7c   
[0xb]   coreclr!xxxTableScanHandlesAsync + 0x97   
[0xc]   coreclr!HndScanHandlesForGC + 0x10c   
[0xd]   coreclr!Ref_TraceNormalRoots + 0xb8   
[0xe]   coreclr!GCScan::GcScanHandles + 0x218   
[0xf]   coreclr!SVR::gc_heap::background_mark_phase + 0x13ba   
[0x10]   coreclr!SVR::gc_heap::gc1 + 0x136   
[0x11]   coreclr!SVR::gc_heap::bgc_thread_function + 0xe0   
[0x12]   coreclr!<lambda_c5a49c859c7ba70587da980d74c056e1>::operator() + 0xa0   
[0x13]   kernel32!BaseThreadInitThunk + 0x14   
[0x14]   ntdll!RtlUserThreadStart + 0x21   
```
It happened in our internal build system. When I run build with /m:16 and worked if I run build without /m.
### Configuration
Windows: 19042.867
.NET Core SDK: dotnet-sdk-5.0.103-win-x64
x64

### Other information
I create two full dumps in Server and Workstation GC mode.
https://drive.google.com/file/d/1RvDtBOVmexXFYRdJuaEIpZUXmWLsRTg7/view?usp=sharing
https://drive.google.com/file/d/1yzqwsb2WXwmYaxBQE7kp702L1YR9qodb/view?usp=sharing

### PR DESCRIPTION
**Pull request by jkotas**
## Customer Impact
Intermittent crash during GC in complex scenarios that use collectible types

## Description
It looks like a bug that has been there since forever. The bug just results into occasional small GC inefficiency most of the time. The crash only happens when all of the following is true:

- The workload uses collectible types
- The GC hits mark stack overflow (ie the object graph is very deep and complex)
- The overflowing objects have collectible types
- The MethodTable of the overflowing objects is allocated at the start of the page and the preceding page is unmapped. (The crash is caused by accesing this unmapped page.)

## Regression?
No.

## Risk (see taxonomy)
Low. Fix validated by the customer.

Fixes #49684

### CODE REVIEW

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  Please get a cr and we will take for consideration in 5.0.x

File: src/coreclr/src/gc/gcdesc.h [hunk 1]
```diff
@@ -199,28 +199,38 @@ class CGCDesc
...
-        if (cnt > 0)
+        if (pMT->ContainsPointers())
         {
-            CGCDescSeries* last = map->GetLowestSeries();
-            while (cur >= last)
+            CGCDesc* map = GetCGCDescFromMT(pMT);
+            CGCDescSeries* cur = map->GetHighestSeries();
+            ptrdiff_t cnt = (ptrdiff_t)map->GetNumSeries();
+
+            if (cnt >= 0)
```
Comment (davidwrighton) [inline src/coreclr/src/gc/gcdesc.h:209]: My analysis indicates the change here to change from > to >= is a small performance optimization. From my analysis cnt == 0 can't actually happen so this is ok, but I want to verify that was the rationale.

**Review by davidwrighton — APPROVED** [review]
Assuming you agree with my comment, this is approved.

File: src/coreclr/src/gc/gcdesc.h (hunk 1 above)
Comment (jkotas) [reply src/coreclr/src/gc/gcdesc.h:209]: My primary motivation for this was to make the conditions and flow to be more similar to the `go_through_object` macros, so that easier to validate that the logic in this method matches it.

You are right that the side-effect is minor perf optimization.

File: src/coreclr/src/gc/gcdesc.h [hunk 2]
```diff
@@ -199,28 +199,38 @@ class CGCDesc
...
+                }
+
+                NumOfPointers *= NumComponents;
             }
+        }
 
-            NumOfPointers *= NumComponents;
+        if (pMT->Collectible())
+        {
+            NumOfPointers += 1;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/gc/gcdesc.h:233]: I think it might be helpful here to comment why when this is collectable the the pointer count is +1.

File: src/coreclr/src/gc/gcdesc.h [hunk 3]
```diff
@@ -199,28 +199,38 @@ class CGCDesc
...
+            ptrdiff_t cnt = (ptrdiff_t)map->GetNumSeries();
+
+            if (cnt >= 0)
             {
-                NumOfPointers += (cur->GetSeriesSize() + ObjectSize) / sizeof(JSlot);
-                cur--;
+                CGCDescSeries* last = map->GetLowestSeries();
+                do
+                {
+                    NumOfPointers += (cur->GetSeriesSize() + ObjectSize) / sizeof(JSlot);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/gc/gcdesc.h:214]: Will `cur` never be `null`? The previous code would have handled that without issue if `last` used some sentinel value, but now we dereference `cur` all the time.

File: src/coreclr/src/gc/gcdesc.h (hunk 2 above)
Comment (jkotas) [reply src/coreclr/src/gc/gcdesc.h:233]: https://github.com/dotnet/runtime/pull/49951

This PR is minimum change for servicing. I have already checked in a more complete fix for this bug to main.

File: src/coreclr/src/gc/gcdesc.h (hunk 3 above)
Comment (jkotas) [reply src/coreclr/src/gc/gcdesc.h:214]: It cannot be ever null.
