### PR TITLE
[jit] Fix gsharedvt constrained calls to Object.GetType () under netcore.

### LINKED ISSUE #35674: [mono] iOS FullAOT crashes with condition `method->is_inflated' not met
`((null) error) * Assertion at class.c:1851, condition 'method->is_inflated' not met`

(it happens in `mono_class_inflate_generic_method_full_checked` for Object.GetType)

Simple repro:
```csharp
using System;
using System.Collections.Generic;

public class Program
{
    public static void Main() {
        Test(1, 2, GetComparer<int>());
    }

    static IComparer<T> GetComparer<T>() where T : IComparable {
        return new AssertComparer<T>();
    }

    static int Test<T>(T low, T high, IComparer<T> comparer) {
        return comparer.Compare(low, high);
    }
}

class AssertComparer<T> : IComparer<T> where T : IComparable
{
    public int Compare(T x, T y) {
        return x.GetType() != y.GetType() ? 1 : 0;
    }
}
```

Steps to reproduce:
```bash
cd src/mono/netcore/sample/iOS/Makefile

# next command should build the whole repo for arm64 and iOS
make runtimepack

# Open 'src/mono/netcore/sample/iOS/Program.cs' and use the repro ^

# generate an XCode project
make bundle USE_LLVM=False

# open Xcode project, deploy to a real device, observe the crash
```
Many tests crash because of it (some gsharedvt-related issue?)

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/35674.

### CODE REVIEW

File: src/mono/mono/mini/jit-icalls.c [hunk 1]
```diff
@@ -1420,6 +1420,21 @@ mono_gsharedvt_constrained_call (gpointer mp, MonoMethod *cmethod, MonoClass *kl
 	gpointer this_arg;
 	gpointer new_args [16];
 
+#ifdef ENABLE_NETCORE
+	if (!mono_class_is_ginst (cmethod->klass) && !cmethod->is_inflated) {
+		MonoVTable *vt;
+
+		/* Object.GetType () is an intrinsic under netcore */
+		g_assert (!strcmp (cmethod->name, "GetType"));
```
Comment (lambdageek) [inline src/mono/mono/mini/jit-icalls.c:1428]:
```suggestion
		g_assertf (!strcmp (cmethod->name, "GetType"), "%s.%s", m_class_get_name (cmethod->klass), cmethod->name);
```

**Review by lambdageek — APPROVED** [review]
