### PR TITLE
Skip cleanup of eventpipe for mono to prevent crashes on shutdown

### LINKED ISSUE #99609: mono_os_mutex_destroy: pthread_mutex_destroy failed with "Device or resource busy"
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=599402
Build error leg or test failing: System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest
Pull request: https://github.com/dotnet/runtime/pull/99595

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "mono_os_mutex_destroy: pthread_mutex_destroy failed",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=599402
**Error message validated:** `[mono_os_mutex_destroy: pthread_mutex_destroy failed`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/12/2024 3:23:03 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[641780](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641780)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641780&view=ms.vss-test-web.build-test-results-tab&runId=15827364&resultId=167476)|dotnet/runtime#100386|
|[641646](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641646)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=641646&view=ms.vss-test-web.build-test-results-tab&runId=15824850&resultId=160304)|dotnet/runtime#100993|
|[640958](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640958)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640958&view=ms.vss-test-web.build-test-results-tab&runId=15803136&resultId=146293)|dotnet/runtime#100765|
|[640844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640844)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640844&view=ms.vss-test-web.build-test-results-tab&runId=15798916&resultId=138288)|dotnet/runtime#100951|
|[640688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640688)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640688&view=ms.vss-test-web.build-test-results-tab&runId=15794182&resultId=152606)|dotnet/runtime#93014|
|[640353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640353)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=640353&view=ms.vss-test-web.build-test-results-tab&runId=15783968&resultId=172459)|dotnet/runtime#100743|
|[639824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639824)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639824&view=ms.vss-test-web.build-test-results-tab&runId=15769932&resultId=110885)|dotnet/runtime#100767|
|[639593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639593)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639593&view=ms.vss-test-web.build-test-results-tab&runId=15762840&resultId=152038)|dotnet/runtime#100669|
|[639437](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639437)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=639437&view=ms.vss-test-web.build-test-results-tab&runId=15759408&resultId=145373)|dotnet/runtime#100520|
|[638524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=638524)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=638524&view=ms.vss-test-web.build-test-results-tab&runId=15731988&resultId=156598)|dotnet/runtime#100767|
|[637807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637807)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637807&view=ms.vss-test-web.build-test-results-tab&runId=15710790&resultId=147670)|dotnet/runtime#100489|
|[637015](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637015)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=637015&view=ms.vss-test-web.build-test-results-tab&runId=15688136&resultId=144574)|dotnet/runtime#100828|
|[636603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636603)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636603&view=ms.vss-test-web.build-test-results-tab&runId=15675838&resultId=145076)|dotnet/runtime#100802|
|[636443](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636443)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636443&view=ms.vss-test-web.build-test-results-tab&runId=15670652&resultId=145095)|dotnet/runtime#100821|
|[635603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635603)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635603&view=ms.vss-test-web.build-test-results-tab&runId=15645056&resultId=110874)|dotnet/runtime#100743|
|[635054](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635054)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=635054&view=ms.vss-test-web.build-test-results-tab&runId=15622818&resultId=142650)|dotnet/runtime#100778|
|[633229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633229)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633229&view=ms.vss-test-web.build-test-results-tab&runId=15568666&resultId=110885)|dotnet/runtime#100731|
|[631865](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631865)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631865&view=ms.vss-test-web.build-test-results-tab&runId=15527556&resultId=153137)|dotnet/runtime#100676|
|[631246](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631246)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631246&view=ms.vss-test-web.build-test-results-tab&runId=15510212&resultId=157780)|dotnet/runtime#99659|
|[631044](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631044)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=631044&view=ms.vss-test-web.build-test-results-tab&runId=15503964&resultId=155259)|dotnet/runtime#100497|
|[630711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630711)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630711&view=ms.vss-test-web.build-test-results-tab&runId=15493944&resultId=155753)|dotnet/runtime#100650|
|[630272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630272)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630272&view=ms.vss-test-web.build-test-results-tab&runId=15484174&resultId=110919)|dotnet/runtime#100280|
|[629948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629948)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629948&view=ms.vss-test-web.build-test-results-tab&runId=15473850&resultId=140131)|dotnet/runtime#100525|
|[629121](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629121)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629121&view=ms.vss-test-web.build-test-results-tab&runId=15443642&resultId=164734)|dotnet/runtime#100489|
|[629043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629043)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=629043&view=ms.vss-test-web.build-test-results-tab&runId=15441886&resultId=155014)|dotnet/runtime#100589|
|[628975](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628975)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628975&view=ms.vss-test-web.build-test-results-tab&runId=15440042&resultId=157780)|dotnet/runtime#100141|
|[628043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628043)|dotnet/runtime|[System.Transactions.Tests.AsyncTransactionScopeTests.AsyncTSTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=628043&view=ms.vss-test-web.build-test-results-tab&runId=15413350&resultId=195234)||
|[627578](https://dev.azure.com/dnceng-public/public/_build/results?buildId=627578)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=627578&view=ms.vss-test-web.build-test-results-tab&runId=15401182&resultId=142392)|dotnet/runtime#100550|
|[626716](https://dev.azure.com/dnceng-public/public/_build/results?buildId=626716)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=626716&view=ms.vss-test-web.build-test-results-tab&runId=15372826&resultId=144456)||
|[626182](https://dev.azure.com/dnceng-public/public/_build/results?buildId=626182)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=626182&view=ms.vss-test-web.build-test-results-tab&runId=15354756&resultId=147529)|dotnet/runtime#92057|
|[625897](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625897)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625897&view=ms.vss-test-web.build-test-results-tab&runId=15347932&resultId=143602)|dotnet/runtime#100379|
|[625012](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625012)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625012&view=ms.vss-test-web.build-test-results-tab&runId=15315538&resultId=165929)|dotnet/runtime#99908|
|[624382](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624382)|dotnet/runtime|[System.Diagnostics.Tests.ProcessWaitingTests.WaitAsyncForPeerProcess](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624382&view=ms.vss-test-web.build-test-results-tab&runId=15294584&resultId=142833)||
|[623236](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623236)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623236&view=ms.vss-test-web.build-test-results-tab&runId=15264616&resultId=144027)|dotnet/runtime#100176|
|[623242](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623242)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623242&view=ms.vss-test-web.build-test-results-tab&runId=15264584&resultId=142837)|dotnet/runtime#100386|
|[623223](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623223)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=623223&view=ms.vss-test-web.build-test-results-tab&runId=15264414&resultId=145246)|dotnet/runtime#100283|
|[622469](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622469)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622469&view=ms.vss-test-web.build-test-results-tab&runId=15248566&resultId=110916)|dotnet/runtime#100141|
|[622371](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622371)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622371&view=ms.vss-test-web.build-test-results-tab&runId=15244050&resultId=167601)|dotnet/runtime#100362|
|[621284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621284)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621284&view=ms.vss-test-web.build-test-results-tab&runId=15206950&resultId=155675)|dotnet/runtime#100352|
|[621302](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621302)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621302&view=ms.vss-test-web.build-test-results-tab&runId=15207052&resultId=165320)|dotnet/runtime#100266|
|[620319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620319)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620319&view=ms.vss-test-web.build-test-results-tab&runId=15174108&resultId=157174)|dotnet/runtime#99433|
|[619690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619690)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619690&view=ms.vss-test-web.build-test-results-tab&runId=15160482&resultId=157915)|dotnet/runtime#99596|
|[619142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619142)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=619142&view=ms.vss-test-web.build-test-results-tab&runId=15143940&resultId=145982)|dotnet/runtime#99840|
|[618646](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618646)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618646&view=ms.vss-test-web.build-test-results-tab&runId=15131024&resultId=154767)|dotnet/runtime#100227|
|[618638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618638)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618638&view=ms.vss-test-web.build-test-results-tab&runId=15130398&resultId=152552)|dotnet/runtime#100272|
|[618562](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618562)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618562&view=ms.vss-test-web.build-test-results-tab&runId=15129158&resultId=172783)|dotnet/runtime#100004|
|[618336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618336)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618336&view=ms.vss-test-web.build-test-results-tab&runId=15124402&resultId=167903)|dotnet/runtime#100004|
|[617941](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617941)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617941&view=ms.vss-test-web.build-test-results-tab&runId=15116984&resultId=180507)|dotnet/runtime#100265|
|[617442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617442)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617442&view=ms.vss-test-web.build-test-results-tab&runId=15101836&resultId=143083)|dotnet/runtime#100252|
|[616081](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616081)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616081&view=ms.vss-test-web.build-test-results-tab&runId=15057834&resultId=160967)|dotnet/runtime#99860|
|[614850](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614850)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614850&view=ms.vss-test-web.build-test-results-tab&runId=15019278&resultId=158305)|dotnet/runtime#97589|
|[614368](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614368)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614368&view=ms.vss-test-web.build-test-results-tab&runId=15011180&resultId=110957)|dotnet/runtime#100152|
|[614460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614460)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614460&view=ms.vss-test-web.build-test-results-tab&runId=15009162&resultId=169815)|dotnet/runtime#100156|
|[613929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613929)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613929&view=ms.vss-test-web.build-test-results-tab&runId=15000572&resultId=110869)|dotnet/runtime#100134|
|[614036](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614036)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614036&view=ms.vss-test-web.build-test-results-tab&runId=14999608&resultId=145331)|dotnet/runtime#100146|
|[614003](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614003)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=614003&view=ms.vss-test-web.build-test-results-tab&runId=14998734&resultId=158111)|dotnet/runtime#99760|
|[613807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613807)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=613807&view=ms.vss-test-web.build-test-results-tab&runId=14994040&resultId=155841)|dotnet/runtime#100038|
|[611976](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611976)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611976&view=ms.vss-test-web.build-test-results-tab&runId=14941398&resultId=171798)|dotnet/runtime#100087|
|[611769](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611769)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611769&view=ms.vss-test-web.build-test-results-tab&runId=14938914&resultId=110922)|dotnet/runtime#100056|
|[611393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611393)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611393&view=ms.vss-test-web.build-test-results-tab&runId=14929224&resultId=110867)|dotnet/runtime#99956|
|[611360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611360)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611360&view=ms.vss-test-web.build-test-results-tab&runId=14924240&resultId=145131)||
|[610653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610653)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610653&view=ms.vss-test-web.build-test-results-tab&runId=14906270&resultId=155012)|dotnet/runtime#99973|
|[610384](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610384)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610384&view=ms.vss-test-web.build-test-results-tab&runId=14899676&resultId=142623)|dotnet/runtime#96332|
|[609332](https://dev.azure.com/dnceng-public/public/_build/results?buildId=609332)|dotnet/runtime|[System.Threading.Tests.EtwTests.WaitHandleWaitEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=609332&view=ms.vss-test-web.build-test-results-tab&runId=14865324&resultId=169020)|dotnet/runtime#99970|
|[608721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=608721)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=608721&view=ms.vss-test-web.build-test-results-tab&runId=14850944&resultId=110728)|dotnet/runtime#99956|
|[607317](https://dev.azure.com/dnceng-public/public/_build/results?buildId=607317)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=607317&view=ms.vss-test-web.build-test-results-tab&runId=14806444&resultId=136272)|dotnet/runtime#99924|
|[607174](https://dev.azure.com/dnceng-public/public/_build/results?buildId=607174)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=607174&view=ms.vss-test-web.build-test-results-tab&runId=14803204&resultId=154693)|dotnet/runtime#99920|
|[606180](https://dev.azure.com/dnceng-public/public/_build/results?buildId=606180)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=606180&view=ms.vss-test-web.build-test-results-tab&runId=14764868&resultId=172119)||
|[605861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=605861)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=605861&view=ms.vss-test-web.build-test-results-tab&runId=14753304&resultId=110911)|dotnet/runtime#97759|
|[603435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=603435)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolMinMaxThreadsEventTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=603435&view=ms.vss-test-web.build-test-results-tab&runId=14670528&resultId=172325)|dotnet/runtime#99766|
|[603223](https://dev.azure.com/dnceng-public/public/_build/results?buildId=603223)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=603223&view=ms.vss-test-web.build-test-results-tab&runId=14668386&resultId=110919)|dotnet/runtime#99761|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|5|17|71|

### PR DESCRIPTION
**Pull request by davmason**
fixes #99609

### CODE REVIEW

**Review by noahfalk — COMMENTED** [review]
Does this change fix the bug?

The callstack I see in the bug report is:
> #20 ep_rt_mono_fini () at /__w/1/s/src/mono/mono/eventpipe/ep-rt-mono.c:892
#21 0x0000ffff935b4d68 in mini_cleanup (domain=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:5259
#22 0x0000ffff937814ac in ves_icall_System_Environment_Exit (result=42) at /__w/1/s/src/mono/mono/metadata/icall.c:6151

The call being removed in this PR is:

> ep_rt_mono_fini
  ep_rt_shutdown

**Comment by davmason** [comment]
@noahfalk I think it's just getting inlined in to `mini_cleanup`. I searched src\mono and couldn't find any more references to `ep_rt_mono_fini`, other than one header file I am going to push a change to delete it from.

**Comment by davmason** [comment]
I believe `ep_rt_shutdown` is getting inlined here: https://github.com/dotnet/runtime/blob/eb4bf70637bce0abd900c59f723edaab6512615b/src/mono/mono/mini/mini-runtime.c#L5272

Since I deleted the method, we should see build errors if there are still references to the function

**Review by noahfalk — APPROVED** [review]
Makes sense, just wanted to double check. Thanks!

**Comment by lateralusX** [comment]
Fix will solve issue in the case where we do System.Environment.Exit where we won't make sure managed threads are full stopped when calling mini_cleanup that in turn will shutdown EventPipe while threads can still be active in EventPipe code. Under normal shutdown this won't be a problem so an alternative fix to still keep cleanup under normal situations could be to check if we are shutting down due to a System.Environement.Exit code in ep_rt_mono_fini like we already check mono_runtime_is_shutting_down, but I'm fine either way.

File: src/mono/mono/eventpipe/ep-rt-mono.c [hunk 1]
```diff
@@ -849,49 +849,6 @@ ep_rt_mono_init_finish (void)
...
-	_eventpipe_initialized = FALSE;
-
-	_ep_rt_mono_runtime_initialized = FALSE;
-
-	if (_ep_rt_mono_default_profiler_provider) {
-		mono_profiler_set_runtime_initialized_callback (_ep_rt_mono_default_profiler_provider, NULL);
-		mono_profiler_set_thread_started_callback (_ep_rt_mono_default_profiler_provider, NULL);
-		mono_profiler_set_thread_stopped_callback (_ep_rt_mono_default_profiler_provider, NULL);
-	}
-	_ep_rt_mono_default_profiler_provider = NULL;
```
Comment (lambdageek) [inline src/mono/mono/eventpipe/ep-rt-mono.c:876]: I think we should still unregister the profiling callbacks.  It will  prevent other potential conflicts between shutdown and EP

**Review by lambdageek — APPROVED** [review]
This is ok, but I think it's valuable to unregister the profiler callbacks.

**Review by lambdageek — APPROVED** [review]
