### PR TITLE
JIT: Keep FieldSeq in AssertionDesc

### LINKED ISSUE #64876: Constant propagation should preserve field sequences
This is a CQ-only issue. We can see cases where (local) constant propagation propagates known addresses of statics and loses field sequences for them. This causes VN to be more pessimistic about those addresses than is necessary.

Fixing this would require saving the field sequence alongside the constant itself in assertions. Unfortunately, currently there is no space available, so some refactoring would be required to make sure there would be no memory consumption regression from this change.

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/64876

This PR slightly changes memory layout in AssertionDsc ([diff](https://www.diffchecker.com/NOflYyhn)) while keeping total size the same (48 bytes) in order to save a reference to FieldSeq*.

Example:
```csharp
static byte Foo()
{
    ReadOnlySpan<byte> RVA = new byte[] { 1, 2, 3, 4, 5 };
    return RVA[3];
}
```
JITDump diff: https://www.diffchecker.com/HVVahKbd e.g.:

image

This also is required to be able to fold constant index + RVA in future.

### CODE REVIEW

File: src/coreclr/jit/gentree.h [hunk 1]
```diff
@@ -270,13 +270,14 @@ class FieldSeq
...
-        SharedStatic = 2, // Static field on a shared generic type: "Class<__Canon>.StaticField".
+        Instance                 = 0, // An instance field.
+        SimpleStatic             = 1, // Simple static field - the handle represents a unique location.
+        SimpleStaticKnownAddress = 2, // Simple static field - the handle represents a known location.
+        SharedStatic             = 3, // Static field on a shared generic type: "Class<__Canon>.StaticField".
     };
 
 private:
-    static const uintptr_t FIELD_KIND_MASK = 0b11;
+    static const uintptr_t FIELD_KIND_MASK = 0b111;
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.h:280]:
```suggestion
    static const uintptr_t FIELD_KIND_MASK = 0b11;
```

Comment (EgorBo) [reply src/coreclr/jit/gentree.h]: Good point 🙂

**Comment by EgorBo** [comment]
@SingleAccretion @jakobbotsch please, take a look
I need this PR to land another one to fold RVA + constant index

File: src/coreclr/jit/compiler.h [hunk 2]
```diff
@@ -7095,15 +7095,16 @@ class Compiler
         } op1;
         struct AssertionDscOp2
         {
-            optOp2Kind kind; // a const or copy assignment
+            optOp2Kind kind;             // a const or copy assignment
+            uint16_t   encodedIconFlags; // encoded icon gtFlags, don't use directly
```
Comment (SingleAccretion) [inline src/coreclr/jit/compiler.h:7099]: Nit: make `encodedIconFlags` private and prefix with `m_`.

File: src/coreclr/jit/compiler.h [hunk 3]
```diff
@@ -7112,6 +7113,25 @@ class Compiler
...
             };
+
+            bool HasIconFlag()
+            {
+                assert(encodedIconFlags <= 0xFF);
+                return encodedIconFlags != 0;
+            }
+            GenTreeFlags GetIconFlag()
+            {
+                GenTreeFlags flags = (GenTreeFlags)(encodedIconFlags << 24);
```
Comment (SingleAccretion) [inline src/coreclr/jit/compiler.h:7124]: Nit: named constant for the shift amount (`24`).

File: src/coreclr/jit/gentree.cpp [hunk 4]
```diff
@@ -17622,6 +17622,15 @@ bool GenTree::IsFieldAddr(Compiler* comp, GenTree** pBaseAddr, FieldSeq** pFldSe
             baseAddr = AsOp()->gtOp1;
             fldSeq   = AsOp()->gtOp2->AsIntCon()->gtFieldSeq;
             offset   = AsOp()->gtOp2->AsIntCon()->IconValue();
+
+            if ((fldSeq != nullptr) && (fldSeq->GetKind() == FieldSeq::FieldKind::SimpleStaticKnownAddress))
+            {
+                if (!baseAddr->IsIntegralConst(0))
```
Comment (SingleAccretion) [inline src/coreclr/jit/gentree.cpp:17628]: No need to check for zero, morph would remove such trees, we can just bail.

File: src/coreclr/jit/gentree.cpp [hunk 5]
```diff
@@ -17622,6 +17622,15 @@ bool GenTree::IsFieldAddr(Compiler* comp, GenTree** pBaseAddr, FieldSeq** pFldSe
...
+                {
+                    // Bail-out, base has to be zero if fldSeq represents a known address (not a small offset)
+                    return false;
+                }
+            }
         }
         else
```
Comment (SingleAccretion) [inline src/coreclr/jit/gentree.cpp:17635]: We should add an assert to the `STATIC_HDL` path that it has a field seq with known address (or `nullptr`), and remove `baseAddr = this`, since that is misleading (actual base address is zero).

File: src/coreclr/jit/importer.cpp [hunk 6]
```diff
@@ -4387,6 +4387,12 @@ GenTree* Compiler::impImportStaticFieldAccess(CORINFO_RESOLVED_TOKEN* pResolvedT
         ssize_t offset;
         if (hasConstAddr)
         {
+            if (!isSharedStatic)
+            {
+                // Change SharedStatic to SimpleStaticKnownAddress
+                assert(fieldKind == FieldSeq::FieldKind::SimpleStatic);
+                fieldKind = FieldSeq::FieldKind::SimpleStaticKnownAddress;
+            }
```
Comment (SingleAccretion) [inline src/coreclr/jit/importer.cpp:4395]: Nit: `hasConstAddr` -> `hasKnownAddr` for consistency.

There is no need to check for `!isSharedStatic`, since a constant can only refer to one location by definition.

**Review by SingleAccretion — COMMENTED** [review]
LGTM modulo minor comments.

**Review by jakobbotsch — APPROVED** [review]
