### PR TITLE
Handle struct marshal stubs in ILStubManager::TraceManager.

### LINKED ISSUE #36248: ILStubManager::TraceManager does not correctly handle struct marshalling stubs
If a managed debugger tries to place a breakpoint at the start of an IL stub, the debugger uses the ILStubManager to place the breakpoint at a location where the user would expect it. For example, for P/Invoke calls it places it at the start of the native call, and for reverse P/Invoke calls, it places it at the start of the managed method.

The ILStubManager doesn't correctly handle struct marshaling stubs. They fall down the else case at the bottom that assumes that the method at that point is a COM call. From that point on we get into a very bad state and AV down the stack, which propagates up as an ExecutionEngineException.

This is the root cause of microsoft/cswinrt#264.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #36248

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
cc: @noahfalk @hoyosjs we should try to add a test case for this if possible.

File: src/coreclr/src/vm/stubmgr.cpp [hunk 1]
```diff
@@ -1844,6 +1844,12 @@ BOOL ILStubManager::TraceManager(Thread *thread,
         trace->InitForUnmanaged(target);
     }
 #endif // FEATURE_COMINTEROP
+    else if (pStubMD->IsStructMarshalStub())
+    {
+        // There's no "target" for struct marshalling stubs
+        // so we have nowhere to tell the debugger to move the breakpoint.
+        return FALSE;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/vm/stubmgr.cpp:1851]: My only question here would be what changed that caused this failure?

Comment (jkoritzinsky) [reply src/coreclr/src/vm/stubmgr.cpp:1851]: We just happened to find the corner case that would hit this failure. This has been a latent bug ever since the struct marshal stubs were introduced. When we used to use the native "field marshalers" before https://github.com/dotnet/coreclr/pull/26340 there weren't any struct marshal stubs.

**Review by AaronRobinsonMSFT — APPROVED** [review]
