### PR TITLE
[mono][AOT] gsharedvt - stop validating generic constraints

### LINKED ISSUE #117557: [wasm][aot] gsharedvt_out_sig - RegularExpressions.Symbolic.SymbolicRegexBuilder
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107614
Build error leg or test failing: [wasm][aot] gsharedvt_out_sig - RegularExpressions.Symbolic.SymbolicRegexBuilder

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "interp.c:2737",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

[Log](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-118048-merge-7568478cd4f0488e9c/WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests/1/console.5dfb2900.log?helixlogtype=result)
```
[18:17:27] fail: [MONO] * Assertion at D:/a/_work/1/s/src/mono/mono/mini/interp/interp.c:2737, 
condition `is_ok (error)' not met, function:init_jit_call_info, 
Attempting to JIT compile method '(wrapper other) 
void object:gsharedvt_out_sig (intptr,System.Text.RegularExpressions.Symbolic.SymbolicRegexBuilder`1/NodeCacheKey<object>&,intptr)' 
while running in aot-only mode. See https://learn.microsoft.com/xamarin/ios/internals/limitations for more information.
 assembly:<unknown assembly> type:<unknown type> member:(null)

Error
    at Mc (http://127.0.0.1:49169/_framework/dotnet.runtime.js:3:172233)
    at wasm_trace_logger (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[149696]:0x2a41ac1)
    at eglib_log_adapter (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[141965]:0x285016a)
    at monoeg_g_logv_nofree (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[141891]:0x284e0fa)
    at monoeg_assertion_message (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[141894]:0x284e1f8)
    at do_jit_call (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[141263]:0x2823cab)
    at mono_interp_exec_method (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[141258]:0x2816d50)
    at interp_entry (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[141337]:0x28270bc)
    at interp_entry_instance_ret_2 (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[141348]:0x282791b)
    at aot_instances_aot_wrapper_gsharedvt_in_sig_u1_this_cl26_Mono_dValueTuple_602_3cint_2c_20int_3e_cl26_Mono_dValueTuple_602_3cint_2c_20int_3e_ (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[104406]:0x1f108f7)
    at System_Text_RegularExpressions_System_Text_RegularExpressions_Symbolic_SymbolicRegexNode_1_TSet_REF_Create_System_Text_RegularExpressions_Symbolic_SymbolicRegexBuilder_1_TSet_REF_System_Text_RegularExpressions_Symbolic_SymbolicRegexNodeKind_System_Text_RegularExpressions_Symbolic_SymbolicRegexNode_1_TSet_REF_System_Text_RegularExpressions_Symbolic_SymbolicRegexNode_1_TSet_REF_int_int_TSet_REF_System_Text_RegularExpressions_Symbolic_SymbolicRegexInfo (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[94120]:0x1a8bd5c)
    at System_Text_RegularExpressions_System_Text_RegularExpressions_Symbolic_SymbolicRegexNode_1_TSet_REF_CreateLoop_System_Text_RegularExpressions_Symbolic_SymbolicRegexBuilder_1_TSet_REF_System_Text_RegularExpressions_Symbolic_SymbolicRegexNode_1_TSet_REF_int_int_bool (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[94141]:0x1a8cea7)
    at System_Text_RegularExpressions_System_Text_RegularExpressions_Symbolic_SymbolicRegexBuilder_1_TSet_REF_CreateLoop_System_Text_RegularExpressions_Symbolic_SymbolicRegexNode_1_TSet_REF_bool_int_int (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[94071]:0x1a87de6)
    at System_Text_RegularExpressions_System_Text_RegularExpressions_Symbolic_RegexNodeConverter_ConvertToSymbolicRegexNode_System_Text_RegularExpressions_RegexNode (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[94067]:0x1a86cf0)
    at System_Text_RegularExpressions_System_Text_RegularExpressions_Symbolic_SymbolicRegexRunnerFactory__ctor_System_Text_RegularExpressions_RegexTree_System_Text_RegularExpressions_RegexOptions_System_TimeSpan (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[93494]:0x1a4d068)
    at System_Text_RegularExpressions_System_Text_RegularExpressions_Regex__ctor_string_System_Text_RegularExpressions_RegexOptions_System_TimeSpan_System_Globalization_CultureInfo (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[93487]:0x1a4cc8e)
    at System_Text_RegularExpressions_System_Text_RegularExpressions_Regex__ctor_string_System_Text_RegularExpressions_RegexOptions (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[93486]:0x1a4cbe3)
    at System_Text_RegularExpressions_Tests_System_Text_RegularExpressions_Tests_GetGroupNamesTests_GroupNumberFromName_InvalidName_ReturnsMinusOne_string_string_System_Text_RegularExpressions_RegexOptions (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[95850]:0x1b9c7a8)
    at aot_instances_aot_wrapper_gsharedvt_out_sig_void_this_objobji4 (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[105794]:0x1f6037e)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107614
**Error message validated:** `[interp.c:2737`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/29/2025 10:27:18 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1134095](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1134095)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1134095&view=ms.vss-test-web.build-test-results-tab&runId=31213784&resultId=100002)||
|[1133869](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1133869)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1133869&view=ms.vss-test-web.build-test-results-tab&runId=31210286&resultId=100002)||
|[1133715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1133715)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1133715&view=ms.vss-test-web.build-test-results-tab&runId=31199826&resultId=100001)||
|[1133415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1133415)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1133415&view=ms.vss-test-web.build-test-results-tab&runId=31190036&resultId=100002)||
|[1133193](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1133193)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1133193&view=ms.vss-test-web.build-test-results-tab&runId=31183134&resultId=100002)||
|[1132919](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132919)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132919&view=ms.vss-test-web.build-test-results-tab&runId=31176026&resultId=100002)||
|[1132478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132478)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132478&view=ms.vss-test-web.build-test-results-tab&runId=31161234&resultId=100002)||
|[1132454](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132454)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132454&view=ms.vss-test-web.build-test-results-tab&runId=31160860&resultId=100002)||
|[1132305](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132305)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132305&view=ms.vss-test-web.build-test-results-tab&runId=31160852&resultId=100002)||
|[1132127](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132127)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132127&view=ms.vss-test-web.build-test-results-tab&runId=31151184&resultId=100002)||
|[1132133](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132133)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1132133&view=ms.vss-test-web.build-test-results-tab&runId=31150980&resultId=114873)|dotnet/runtime#117585|
|[1131882](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1131882)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1131882&view=ms.vss-test-web.build-test-results-tab&runId=31143736&resultId=100002)||
|[1131505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1131505)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1131505&view=ms.vss-test-web.build-test-results-tab&runId=31130094&resultId=100002)||
|[1131491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1131491)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1131491&view=ms.vss-test-web.build-test-results-tab&runId=31129566&resultId=100002)||
|[1130996](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1130996)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1130996&view=ms.vss-test-web.build-test-results-tab&runId=31116716&resultId=100002)||
|[1130729](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1130729)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1130729&view=ms.vss-test-web.build-test-results-tab&runId=31105854&resultId=100002)||
|[1130610](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1130610)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1130610&view=ms.vss-test-web.build-test-results-tab&runId=31101736&resultId=100002)||
|[1130379](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1130379)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1130379&view=ms.vss-test-web.build-test-results-tab&runId=31092752&resultId=100002)||
|[1129517](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1129517)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1129517&view=ms.vss-test-web.build-test-results-tab&runId=31069070&resultId=100002)||
|[1129101](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1129101)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1129101&view=ms.vss-test-web.build-test-results-tab&runId=31055134&resultId=100002)||
|[1129055](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1129055)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1129055&view=ms.vss-test-web.build-test-results-tab&runId=31054166&resultId=100002)||
|[1128945](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1128945)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1128945&view=ms.vss-test-web.build-test-results-tab&runId=31050796&resultId=100002)||
|[1128703](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1128703)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1128703&view=ms.vss-test-web.build-test-results-tab&runId=31045882&resultId=100002)||
|[1128424](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1128424)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1128424&view=ms.vss-test-web.build-test-results-tab&runId=31038406&resultId=100002)||
|[1127938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1127938)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1127938&view=ms.vss-test-web.build-test-results-tab&runId=31026686&resultId=100002)||
|[1127398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1127398)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1127398&view=ms.vss-test-web.build-test-results-tab&runId=31007438&resultId=100002)||
|[1126859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1126859)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1126859&view=ms.vss-test-web.build-test-results-tab&runId=30989876&resultId=100002)||
|[1126567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1126567)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1126567&view=ms.vss-test-web.build-test-results-tab&runId=30984084&resultId=100002)||
|[1126311](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1126311)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1126311&view=ms.vss-test-web.build-test-results-tab&runId=30974548&resultId=100002)||
|[1125728](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1125728)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1125728&view=ms.vss-test-web.build-test-results-tab&runId=30957666&resultId=100002)||
|[1125220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1125220)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1125220&view=ms.vss-test-web.build-test-results-tab&runId=30941800&resultId=100002)||
|[1124846](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124846)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124846&view=ms.vss-test-web.build-test-results-tab&runId=30926564&resultId=100002)||
|[1124754](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124754)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124754&view=ms.vss-test-web.build-test-results-tab&runId=30923478&resultId=100002)||
|[1124626](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124626)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124626&view=ms.vss-test-web.build-test-results-tab&runId=30918904&resultId=100002)||
|[1124606](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124606)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124606&view=ms.vss-test-web.build-test-results-tab&runId=30916994&resultId=100002)||
|[1124503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124503)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124503&view=ms.vss-test-web.build-test-results-tab&runId=30912862&resultId=100002)||
|[1124063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124063)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1124063&view=ms.vss-test-web.build-test-results-tab&runId=30898616&resultId=100002)||
|[1123492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1123492)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1123492&view=ms.vss-test-web.build-test-results-tab&runId=30879762&resultId=100002)||
|[1122948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1122948)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1122948&view=ms.vss-test-web.build-test-results-tab&runId=30858994&resultId=100002)||
|[1122352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1122352)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1122352&view=ms.vss-test-web.build-test-results-tab&runId=30843126&resultId=100002)||
|[1121801](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1121801)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1121801&view=ms.vss-test-web.build-test-results-tab&runId=30825628&resultId=100002)||
|[1121266](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1121266)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1121266&view=ms.vss-test-web.build-test-results-tab&runId=30809374&resultId=100002)||
|[1120869](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1120869)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1120869&view=ms.vss-test-web.build-test-results-tab&runId=30793666&resultId=100002)||
|[1119240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1119240)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1119240&view=ms.vss-test-web.build-test-results-tab&runId=30743956&resultId=100002)||
|[1118935](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118935)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118935&view=ms.vss-test-web.build-test-results-tab&runId=30733476&resultId=100002)||
|[1118830](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118830)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118830&view=ms.vss-test-web.build-test-results-tab&runId=30731648&resultId=100002)||
|[1118741](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118741)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118741&view=ms.vss-test-web.build-test-results-tab&runId=30726686&resultId=100002)||
|[1118622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118622)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118622&view=ms.vss-test-web.build-test-results-tab&runId=30722908&resultId=100002)||
|[1118287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118287)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118287&view=ms.vss-test-web.build-test-results-tab&runId=30716120&resultId=100002)||
|[1117612](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1117612)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1117612&view=ms.vss-test-web.build-test-results-tab&runId=30695960&resultId=100002)||
|[1117080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1117080)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1117080&view=ms.vss-test-web.build-test-results-tab&runId=30681364&resultId=100002)||
|[1116605](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1116605)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1116605&view=ms.vss-test-web.build-test-results-tab&runId=30662532&resultId=100002)||
|[1116101](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1116101)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1116101&view=ms.vss-test-web.build-test-results-tab&runId=30641286&resultId=110830)||
|[1115438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1115438)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1115438&view=ms.vss-test-web.build-test-results-tab&runId=30630422&resultId=110830)||
|[1115257](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1115257)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1115257&view=ms.vss-test-web.build-test-results-tab&runId=30625796&resultId=110830)||
|[1114699](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1114699)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1114699&view=ms.vss-test-web.build-test-results-tab&runId=30604448&resultId=114784)|dotnet/runtime#117585|
|[1114686](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1114686)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1114686&view=ms.vss-test-web.build-test-results-tab&runId=30604556&resultId=110830)||
|[1113991](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1113991)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1113991&view=ms.vss-test-web.build-test-results-tab&runId=30587544&resultId=110830)||
|[1113411](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1113411)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1113411&view=ms.vss-test-web.build-test-results-tab&runId=30570838&resultId=110830)||
|[1112651](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112651)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112651&view=ms.vss-test-web.build-test-results-tab&runId=30547032&resultId=110830)||
|[1112367](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112367)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112367&view=ms.vss-test-web.build-test-results-tab&runId=30535772&resultId=110830)||
|[1112200](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112200)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112200&view=ms.vss-test-web.build-test-results-tab&runId=30531728&resultId=110830)||
|[1112098](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112098)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112098&view=ms.vss-test-web.build-test-results-tab&runId=30527348&resultId=110830)||
|[1111945](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111945)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111945&view=ms.vss-test-web.build-test-results-tab&runId=30522966&resultId=110830)||
|[1111636](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111636)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111636&view=ms.vss-test-web.build-test-results-tab&runId=30513856&resultId=110830)||
|[1111091](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111091)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111091&view=ms.vss-test-web.build-test-results-tab&runId=30494352&resultId=110830)||
|[1110710](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110710)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110710&view=ms.vss-test-web.build-test-results-tab&runId=30481832&resultId=110830)||
|[1110214](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110214)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110214&view=ms.vss-test-web.build-test-results-tab&runId=30467430&resultId=110830)||
|[1110201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110201)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110201&view=ms.vss-test-web.build-test-results-tab&runId=30467068&resultId=110830)||
|[1109817](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109817)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109817&view=ms.vss-test-web.build-test-results-tab&runId=30452562&resultId=110830)||
|[1109292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109292)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109292&view=ms.vss-test-web.build-test-results-tab&runId=30434866&resultId=110830)||
|[1108891](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108891)|dotnet/runtime|[WasmTestOnChrome-ST-System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108891&view=ms.vss-test-web.build-test-results-tab&runId=30416320&resultId=110830)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|22|72|

### PR DESCRIPTION
**Pull request by pavelsavara**
- stop validating generic constraints for classes created for AOT wrappers
- new field MonoClass->skip_generic_constraints
- active issue https://github.com/dotnet/runtime/issues/119143

Fixes https://github.com/dotnet/runtime/issues/117557

### CODE REVIEW

**Comment by pavelsavara** [comment]
This could enable wrappers with arguments like 
```cs
public partial struct Nullable<T> where T : struct
public struct ValueTuple<T1> : IEquatable<ValueTuple<T1>>, IStructuralEquatable, IStructuralComparable, IComparable, IComparable<ValueTuple<T1>>, IValueTupleInternal, ITuple
struct AddOperator<T> : IAggregationOperator<T> where T : IAdditionOperators<T, T, T>, IAdditiveIdentity<T, T>
struct WeakGCHandle<T> : System.IDisposable, System.IEquatable<System.Runtime.InteropServices.WeakGCHandle<T>> where T : class?
```

Quick list of [types with constraints](https://gist.github.com/pavelsavara/cc6b9b793167c31ce31c8f0af2fb4bb7)

Would that break anything ? Would that make AOT binary (much) bigger ? Would that make TensorPrimitives faster ?

File: src/mono/mono/metadata/class-accessors.c [hunk 1]
```diff
@@ -569,6 +569,25 @@ mono_class_set_failure (MonoClass *klass, MonoErrorBoxed *boxed_error)
...
 }
 
+/**
+ * mono_class_skip_generic_constraints:
+ * \param klass class in which should not validate generic constraints
+ *
+ * LOCKING: Acquires the loader lock.
+ */
+gboolean
+mono_class_skip_generic_constraints (MonoClass *klass)
```
Comment (lewing) [inline src/mono/mono/metadata/class-accessors.c]: I don't see this being called anywhere yet?

Comment (pavelsavara) [reply src/mono/mono/metadata/class-accessors.c]: thanks!! I was confused why it didn't work. I missed to merge one file 🤣

**Comment by pavelsavara** [comment]
RegularExpressions are fixed🎉 

```
[16:24:27] info: Finished:    System.Text.RegularExpressions.Tests.dll
[16:24:27] info: === TEST EXECUTION SUMMARY ===
[16:24:27] info: Tests run: 21220 Passed: 21205 Inconclusive: 0 Failed: 0 Ignored: 0 Skipped: 15
```

But as it is, it breaks `System.Text.Json.Tests` probably because of the impact to `ValueTuple`

[Log](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-119004-merge-3a0b776b9b3546e89b/WasmTestOnChrome-ST-System.Text.Json.Tests/1/console.266c4904.log?helixlogtype=result&skoid=8eda00af-b5ec-4be9-b69b-0919a2338892&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2025-08-23T17%3A46%3A22Z&ske=2025-08-23T18%3A46%3A22Z&sks=b&skv=2024-11-04&sv=2024-11-04&se=2025-08-23T18%3A46%3A22Z&sr=b&sp=rl&sig=29MBUXW8kqO2pp4YnXuibTdLIHenr27IDobe4dhs3Ss%3D)
```
[16:51:44] info: Starting:    System.Text.Json.Tests.dll
[16:52:25] info: MONO_WASM: Jiterpreter table 20 is out of space (3073 entries allocated)
[16:52:30] info: MONO_WASM: Jiterpreter table 12 is out of space (3073 entries allocated)
[16:52:32] info: MONO_WASM: Jiterpreter table 4 is out of space (3073 entries allocated)
[16:52:48] info: MONO_WASM: Jiterpreter table 11 is out of space (3073 entries allocated)
[16:53:25] fail: MONO_WASM: null function or function signature mismatch
RuntimeError: null function or function signature mismatch
    at aot_instances_aot_wrapper_gsharedvt_out_sig_obj_cl4c_Mono_dValueTuple_602_3cbyte_2c_20Mono_dValueTuple_602_3clong_2c_20long_3e_3e_ (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[64727]:0x124bbe4)
    at corlib_System_Collections_Generic_List_1_Enumerator_T_GSHAREDVT_System_Collections_IEnumerator_get_Current (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[41060]:0xa7117d)
    at ut_corlib_System_Collections_Generic_List_1_Enumerator_T_GSHAREDVT_System_Collections_IEnumerator_get_Current (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[41061]:0xa711ab)
    at System_Collections_NonGeneric_System_Collections_Queue__ctor_System_Collections_ICollection (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[10716]:0x36e085)
    at JsonSchema_Net_aot_wrapper_gsharedvt_out_sig_void_this_obj (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[1405]:0xe1bf6)
    at jit_call_cb (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[90040]:0x1874692)
    at mono_llvm_cpp_catch_exception (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[93325]:0x196775c)
    at mono_llvm_catch_exception (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[93377]:0x196bdbf)
    at do_jit_call (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[89960]:0x18711a8)
    at mono_interp_exec_method (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[89955]:0x1870669)
    at interp_entry (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[90034]:0x187431b)
    at interp_entry_static_ret_2 (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[90063]:0x1875282)
    at aot_instances_aot_wrapper_gsharedvt_in_sig_obj_objcl40_Mono_dValueTuple_601_3cMono_dValueTuple_602_3cint_2c_20int_3e_3e_ (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[64689]:0x124a425)
    at corlib_wrapper_delegate_invoke__Module_invoke_object_object_Span_1_object_object_System_Span_1_object (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[41560]:0xa8cdca)
    at corlib_System_Reflection_MethodBaseInvoker_InvokeWithOneArg_object_System_Reflection_BindingFlags_System_Reflection_Binder_object___System_Globalization_CultureInfo (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[36407]:0x956a33)
    at corlib_System_Reflection_RuntimeConstructorInfo_Invoke_System_Reflection_BindingFlags_System_Reflection_Binder_object___System_Globalization_CultureInfo (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[36553]:0x95f10a)
    at corlib_System_RuntimeType_CreateInstanceImpl_System_Reflection_BindingFlags_System_Reflection_Binder_object___System_Globalization_CultureInfo (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[25237]:0x790c5d)
    at corlib_System_Activator_CreateInstance_System_Type_System_Reflection_BindingFlags_System_Reflection_Binder_object___System_Globalization_CultureInfo_object__ (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[25968]:0x7b5197)
    at corlib_System_Activator_CreateInstance_System_Type_object__ (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[25969]:0x7b51e3)
    at aot_instances_aot_wrapper_gsharedvt_out_sig_obj_objobj (http://127.0.0.1:49170/_framework/dotnet.native.wasm:wasm-function[64647]:0x12496d1)
```

The test is `[STRT] System.Text.Json.Serialization.Tests.NumberHandlingTestsDynamic.Number_AsCollectionElement_RoundTrip`

```
[MONO] AOT NOT FOUND: System.Text.Json.Serialization.JsonConverter`1<System.Nullable`1<System.Int128>>:TryWrite (System.Text.Json.Utf8JsonWriter,System.Nullable`1<System.Int128>&,System.Text.Json.JsonSerializerOptions,System.Text.Json.WriteStack&).
dotnet.runtime.js:1415 [MONO] GC_MINOR: (Nursery full) time 1.40ms, stw 1.40ms promoted 1K major size: 15824K in use: 14434K empty reserved: 64K los size: 14844K in use: 14328K
dotnet.runtime.js:1415 [MONO] GC_MINOR: (Nursery full) time 2.70ms, stw 2.70ms promoted 168K major size: 16000K in use: 14609K empty reserved: 0K los size: 14844K in use: 14328K
dotnet.runtime.js:1415 [MONO] GC_MAJOR_SWEEP: major size: 14032K in use: 15185K empty reserved: 0K
dotnet.runtime.js:1415 [MONO] GC_MAJOR: (LOS overflow) time 78.60ms, stw 78.60ms los size: 2454K in use: 1942K
dotnet.runtime.js:1415 [MONO] GC_MINOR: (Nursery full) time 1.60ms, stw 1.90ms promoted 0K major size: 14032K in use: 10980K empty reserved: 2048K los size: 2575K in use: 2062K
dotnet.runtime.js:1415 [MONO] AOT NOT FOUND: System.Collections.Generic.List`1<System.Nullable`1<System.Int128>>:get_Item (int).
dotnet.runtime.js:1415 [MONO] AOT NOT FOUND: (wrapper other) object:gsharedvt_in_sig (int,intptr).
dotnet.runtime.js:1415 [MONO] AOT NOT FOUND: System.Nullable`1<System.Int128>:Box (System.Nullable`1<System.Int128>).
```

`Nullable<System.Int128>` seems to be the troublemaker.

**Comment by pavelsavara** [comment]
json fail is actually independent issue https://github.com/dotnet/runtime/issues/119143 which also fails on main

File: src/mono/mono/metadata/class-accessors.c (hunk 1 above)
Comment (BrzVlad) [inline src/mono/mono/metadata/class-accessors.c]: I think this should be named `mono_class_set_skip_generic_constraints`, otherwise it is somewhat confusing. Also don't see why it should return any value.

File: src/mono/mono/metadata/class-accessors.c [hunk 2]
```diff
@@ -569,6 +569,24 @@ mono_class_set_failure (MonoClass *klass, MonoErrorBoxed *boxed_error)
...
+{
+	if (klass->skip_generic_constraints)
+		return FALSE;
+
+	mono_loader_lock ();
```
Comment (BrzVlad) [inline src/mono/mono/metadata/class-accessors.c:584]: It is not clear to me whether this lock guarantees anything, but I don't have a good solution.

Comment (pavelsavara) [reply src/mono/mono/metadata/class-accessors.c:584]: Well I just copy&pasted the pattern in this file ...

This is `MonoClass` created when instantiating gsharedvt wrapper and doesn't have fields initialized yet. All of this in context of AOT compiler. Are you worried that another thread would try to create same shape and find it in some cache in this state ?

**Review by BrzVlad — APPROVED** [review]
