### PR TITLE
[wasm][debugging] Adding instructions for native debugging 

### LINKED ISSUE #69599: Can't debug C native dependency of WASM Blazor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Following this guideline 
https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-6.0#use-native-code, we can add a C library easily to a WASM Blazor project. 
But when we try to debug it using Visual Studio 2022 for Windows, for example setting a breakpoint anywhere in the C code, we get a  "The Breakpoint will not currently be hit. Unbound breakpoint" error.

### Expected Behavior

We should be able to debug C code added using the aforementioned guideline (using <NativeFileReference Include=.../>), including setting breakpoints and being able to analyze C variable contents.

### Steps To Reproduce

Copied from https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-6.0#use-native-code

1.Create a new Blazor WebAssembly project.

2.Add a Test.c file to the project.

3.Add a C function for computing factorials, for example Test.c:

```
int fact(int n)
{
    if (n == 0) return 1;
    return n * fact(n - 1);
}
```

4.Add a NativeFileReference for Test.c in the app's project file:

```
<ItemGroup>
  <NativeFileReference Include="Test.c" />
</ItemGroup>
```

5.In a Razor component, add a [DllImportAttribute] for the fact function in the generated Test library and call the fact method from .NET code in the component.

```
@page "/native-c-test"
@using System.Runtime.InteropServices

<PageTitle>Native C</PageTitle>

<h1>Native C Test</h1>

<p>
    @@fact(3) result: @fact(3)
</p>

@code {
    [DllImport("Test")]
    static extern int fact(int n);
}
```

6. set breakpoint in C file 

7. launch Blazor debugging in a browser

### Exceptions (if any)

_No response_

### .NET Version

6.0

### Anything else?

Visual Studio 2022 for Windows 17.3.0 Preview 1.0

Microsoft Visual Studio Community 2022
Version 17.3.0 Preview 1.0
VisualStudio.17.Preview/17.3.0-pre.1.0+32505.426
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA240
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.3.122.33185
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.3.122.33185
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.122.33185
Azure Functions and Web Jobs Tools

C# Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Linux Core Dump Debugging   1.0.9.32505
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.7 (c1ffb2a)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2222701+751db1ebea5e6a9ecc7fa57fe447180422afa610
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62204.01010
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10420.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.32505
Visual C++ for Linux Development

Visual F# Tools   17.1.0-beta.22178.3+6da0245a7ce4bb8483b8d1f2993c8ecaea967ad9
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.91 (main@7802af5)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.30 (remotes/origin/main@fb6442dc1)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   12.3.99.58 (main/64b22fc)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: adf1bc4
    Java.Interop: xamarin/java.interop/release/6.0.3xx@2a882d2d
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fc3c2ac

### PR DESCRIPTION
**Pull request by thaystg**
Fix https://github.com/dotnet/runtime/issues/69599

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 1]
```diff
@@ -247,12 +247,10 @@ protected override async Task<bool> AcceptEvent(SessionId sessionId, JObject par
                         switch (url)
                         {
                             case var _ when url == "":
-                            case var _ when url.StartsWith("wasm://", StringComparison.Ordinal):
-                            case var _ when url.EndsWith(".wasm", StringComparison.Ordinal):
```
Comment (lewing) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:251]: Does this have any negative interaction with the code that filters unmanaged frames out of the callstack?

Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:251]: As far as I saw no. I will check it again.

Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:251]: With this PR:
image
Without this PR:
image

File: src/mono/wasm/debugger/debugger.md [hunk 2]
```diff
@@ -0,0 +1,23 @@
+# Mono Wasm Debugger
+
+## Native debugging
+
+It's possible to debug native code and managed code using BrowserDebugProxy.
```
Comment (AaronRobinsonMSFT) [inline src/mono/wasm/debugger/debugger.md:5]:
```suggestion
It's possible to debug native code and managed code using the `BrowserDebugProxy` project.
```

File: src/mono/wasm/debugger/debugger.md [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+
+Steps:
+- Install C/C++ DevTools Support (DWARF) extension on chrome.
```
Comment (AaronRobinsonMSFT) [inline src/mono/wasm/debugger/debugger.md:8]: Is there a link that can be provided for this? How does one find this tool.

File: src/mono/wasm/debugger/debugger.md [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+- It will show something like this in the Address Bar: ``http://localhost:9222/devtools/inspector.html?ws=127.0.0.1:9300/devtools/page/97FCDA5A332CA3B72031790B26A264EF``
+- Open another tab and go to ``chrome://inspect``
+- Click on configure and add the port that was showed in the Address Bar: ``127.0.0.1:9300``
+- After some seconds it will appear the tabs available to debug
+- Choose the WebAssembly Page and click on Inspect
+- Open the Sources tab and click on ``file://``
+- You will see c# files and c files available to add breakpoint.
+
+Hint:
+- If you are running a Blazor app that has .c file(s) and you added <WasmNativeBuild>true</WasmNativeBuild> in the .csproj file, also add ``<_WasmDevel>true</_WasmDevel>`` to disable optimizations and have a better native debugging experience.
```
Comment (AaronRobinsonMSFT) [inline src/mono/wasm/debugger/debugger.md:23]: A suggestion here. I think this value should be set to `true` automatically if the user is building in `Debug`.

File: src/mono/wasm/debugger/debugger.md (hunk 3 above)
Comment (thaystg) [reply src/mono/wasm/debugger/debugger.md:8]: Do you mean like this?
https://chrome.google.com/webstore/detail/cc%20%20-devtools-support-dwa/pdcpmagijalfljmkmjngeonclgbbannb

File: src/mono/wasm/debugger/debugger.md [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+It's possible to debug native code and managed code using BrowserDebugProxy.
+
+Steps:
+- Install C/C++ DevTools Support (DWARF) extension on chrome.
+- Enable DWARF support: Open DevTools, click on the Engine, click on experiments and enable WebAssembly Debugging: Enable DWARF support.
+- Start the WebAssembly App Without Debugging from VS or dotnet run on command line.
+- Run chrome using this startup parameter: --remote-debugging-port=9222
+- Go to your Blazor App Page
+- Press Ctrl-Alt-D (windows) it will open the debugger page
+- It will show something like this in the Address Bar: ``http://localhost:9222/devtools/inspector.html?ws=127.0.0.1:9300/devtools/page/97FCDA5A332CA3B72031790B26A264EF``
```
Comment (radical) [inline src/mono/wasm/debugger/debugger.md:14]: Is this manual process needed for native debugging specifically?

And does this work with `dotnet run --debug` for a template browser app too?

File: src/mono/wasm/debugger/debugger.md [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+- Open another tab and go to ``chrome://inspect``
+- Click on configure and add the port that was showed in the Address Bar: ``127.0.0.1:9300``
+- After some seconds it will appear the tabs available to debug
+- Choose the WebAssembly Page and click on Inspect
+- Open the Sources tab and click on ``file://``
+- You will see c# files and c files available to add breakpoint.
+
+Hint:
+- If you are running a Blazor app that has .c file(s) and you added <WasmNativeBuild>true</WasmNativeBuild> in the .csproj file, also add ``<_WasmDevel>true</_WasmDevel>`` to disable optimizations and have a better native debugging experience.
```
Comment (lewing) [inline src/mono/wasm/debugger/debugger.md:23]:
```suggestion
- If you are running a Blazor app that has .c file(s) and you added <WasmBuildNative>true</WasmBuildNative> in the .csproj file, also add ``<_WasmDevel>true</_WasmDevel>`` to disable optimizations and have a better native debugging experience.
```

Also do you need to specify WasmBuildNative if you've added native assets?

File: src/mono/wasm/debugger/debugger.md (hunk 4 above)
Comment (thaystg) [reply src/mono/wasm/debugger/debugger.md]: Yes! It would be very helpful for native debugging.
So we could check, if build is debug and WasmNativeBuild is true then we set _WasmDevel to true?

File: src/mono/wasm/debugger/debugger.md [hunk 7]
```diff
@@ -0,0 +1,23 @@
+# Mono Wasm Debugger
+
+## Native debugging
+
+It's possible to debug native code and managed code using the `BrowserDebugProxy` project.
+
+Steps:
+- Install C/C++ DevTools Support (DWARF) extension on chrome.
+- Enable DWARF support: Open DevTools, click on the Engine, click on experiments and enable WebAssembly Debugging: Enable DWARF support.
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/debugger.md:9]: Probably most people would understand but I at first was not sure what Engine might mean. It's about Settings, right? 
image

File: src/mono/wasm/debugger/debugger.md [hunk 8]
```diff
@@ -0,0 +1,23 @@
+# Mono Wasm Debugger
+
+## Native debugging
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/debugger.md:3]: Isn't this document the same as https://paper.dropbox.com/doc/Blazor-Debugging-YQ5uISzLCRo9u2Oss8YTU? Can't we just copy-paste here? I like dropbox version more because it has photos, so it's easier to follow.

**Review by ilonatommy — COMMENTED** [review]
Looks good.

File: src/mono/wasm/debugger/debugger.md (hunk 8 above)
Comment (thaystg) [reply src/mono/wasm/debugger/debugger.md:3]: Yes, done.

File: src/mono/wasm/debugger/debugger.md (hunk 4 above)
Comment (thaystg) [reply src/mono/wasm/debugger/debugger.md]: I added this in the PR.

File: src/mono/wasm/debugger/debugger.md [hunk 9]
```diff
@@ -0,0 +1,28 @@
...
+
+It's possible to debug native code and managed code using the `BrowserDebugProxy` project.
+
+Steps:
+- Install C/C++ DevTools Support (DWARF) extension on chrome. https://chrome.google.com/webstore/detail/cc%20%20-devtools-support-dwa/pdcpmagijalfljmkmjngeonclgbbannb
```
Comment (radical) [inline src/mono/wasm/debugger/debugger.md:8]:
```suggestion
- Install [C/C++ DevTools Support (DWARF) extension](https://chrome.google.com/webstore/detail/cc%20%20-devtools-support-dwa/pdcpmagijalfljmkmjngeonclgbbannb) on chrome. 
```

File: src/mono/wasm/debugger/debugger.md [hunk 10]
```diff
@@ -0,0 +1,28 @@
...
+- Enable DWARF support: Open DevTools, click on the settings, click on experiments and enable WebAssembly Debugging: Enable DWARF support.<br>
+![image](https://user-images.githubusercontent.com/4503299/170745664-fc7d185c-469c-4443-9c57-545bd79588b8.png)
+- Start the WebAssembly App Without Debugging from VS or dotnet run on command line.
```
Comment (radical) [inline src/mono/wasm/debugger/debugger.md:11]:
```suggestion
- Start the WebAssembly App Without Debugging from VS, or `dotnet run` on command line.
```

File: src/mono/wasm/debugger/debugger.md [hunk 11]
```diff
@@ -0,0 +1,28 @@
...
+- Run chrome using this startup parameter: --remote-debugging-port=9222
```
Comment (radical) [inline src/mono/wasm/debugger/debugger.md:12]:
```suggestion
- Run chrome using this startup parameter: `--remote-debugging-port=9222`
```

File: src/mono/wasm/debugger/debugger.md [hunk 12]
```diff
@@ -0,0 +1,28 @@
...
+- Go to your Blazor App Page
+- Press Ctrl-Alt-D (windows) it will open the debugger page
+- It will show something like this in the Address Bar: ``http://localhost:9222/devtools/inspector.html?ws=127.0.0.1:9300/devtools/page/97FCDA5A332CA3B72031790B26A264EF``
```
Comment (radical) [inline src/mono/wasm/debugger/debugger.md:15]:
```suggestion
- It will show something like this in the address Bar: ``http://localhost:9222/devtools/inspector.html?ws=127.0.0.1:9300/devtools/page/97FCDA5A332CA3B72031790B26A264EF``
```

File: src/mono/wasm/debugger/debugger.md [hunk 13]
```diff
@@ -0,0 +1,28 @@
...
+- Open another tab and go to ``chrome://inspect``<br>
+![image](https://user-images.githubusercontent.com/4503299/170746026-8921892b-b936-458d-84f2-8a49b76755d4.png)
+- Click on configure and add the port that was showed in the Address Bar: ``127.0.0.1:9300``<br>
+![image](https://user-images.githubusercontent.com/4503299/170746126-b2edd688-dcc5-4b67-9162-465782646363.png)
+- After some seconds it will appear the tabs available to debug<br>
+![image](https://user-images.githubusercontent.com/4503299/170746234-456ac8e9-180d-4173-a2fa-93cb8293514a.png)
+- Choose the WebAssembly Page and click on Inspect<br>
+![image](https://user-images.githubusercontent.com/4503299/170746341-809f8876-3f46-4c5c-b2b3-6f92af8beaa1.png)
+- Open the Sources tab and click on ``file://``
+- You will see c# files and c files available to add breakpoint.
```
Comment (radical) [inline src/mono/wasm/debugger/debugger.md:25]:
```suggestion
- You will see c# files and c files available to add breakpoints.
```

**Review by radical — APPROVED** [review]

File: src/mono/wasm/debugger/debugger.md [hunk 14]
```diff
@@ -0,0 +1,28 @@
...
+
+Hint:
+- If you are running a Blazor app that has .c file(s) and you added <WasmBuildNative>true</WasmBuildNative> in the .csproj file, also add ``<_WasmDevel>true</_WasmDevel>`` to disable optimizations and have a better native debugging experience.
```
[the remark this answers is not in the document]
Comment (thaystg) [reply src/mono/wasm/debugger/debugger.md:28]: Yes!
