### PR TITLE
Fix SIMD case on arm64 linux with zapDisabled.

### LINKED ISSUE #33616: Assert failure(PID 396 [0x0000018c], Thread: 396 [0x018c]): Assertion failed '!"Bad type in gtNewZeroConNode"' in 'System.Runtime.Intrinsics.Vector128:AsByte(System.Runtime.Intrinsics.Vector1281[Boolean]):System.Runtime.Intrinsics.Vector1281[Byte]' during 'Morph - Global' (IL size 7)
**Job:**
[runtime-coreclr r2r-extra:20200314.1](https://dev.azure.com/dnceng/public/_build/results?buildId=559970)
**Error message:**
```
Assert failure(PID 396 [0x0000018c], Thread: 396 [0x018c]): Assertion failed '!"Bad type in gtNewZeroConNode"' in 'System.Runtime.Intrinsics.Vector128:AsByte(System.Runtime.Intrinsics.Vector1281[Boolean]):System.Runtime.Intrinsics.Vector1281[Byte]' during 'Morph - Global' (IL size 7)
File: /__w/1/s/src/coreclr/src/jit/gentree.cpp Line: 5959
Image: /root/helix/work/correlation/corerun\n\napply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9f9f126c)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9f9f126c)\napply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9f9e5ee4)
/root/helix/work/workitem/JIT/HardwareIntrinsics/General/NotSupported/NotSupported_r/NotSupported_r.sh: line 275: 396 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /root/helix/work/workitem/JIT/HardwareIntrinsics/Reports/JIT.HardwareIntrinsics/General/NotSupported/NotSupported_r/NotSupported_r.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0\nCopyright (c) Microsoft Corporation. All rights reserved.\n\nNative image NotSupported_r.dll generated successfully.
in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun NotSupported_r.dll ''
Beginning test case Vector64Zero at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64BooleanAsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64ByteAsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64DoubleAsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64Int16AsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64Int32AsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64Int64AsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64SByteAsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 3/15/2020 4:16:53 AM\nBeginning test case Vector64SingleAsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64UInt16AsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64UInt32AsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 3/15/2020 4:16:53 AM\nBeginning test case Vector64UInt64AsGeneric_Boolean at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 3/15/2020 4:16:53 AM
Beginning test case Vector64BooleanAsGeneric_Byte at 3/15/2020 4:16:53 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro 

Ending test case at 3/15/2020 4
```
**Stack trace:**
`
at JIT_HardwareIntrinsics._General_NotSupported_NotSupported_r_NotSupported_r_._General_NotSupported_NotSupported_r_NotSupported_r_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/JIT.HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.cs:line 1498
`
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=559970&view=ms.vss-test-web.build-test-results-tab&runId=17640366&resultId=109895&paneView=debug

### PR DESCRIPTION
**Pull request by sandreenko**
Fixes #33616.

jit-stress job has passed https://dev.azure.com/dnceng/public/_build/results?buildId=564359&view=ms.vss-test-web.build-test-results-tab, r2r failed on a non-related issue.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @CarolEidt @dotnet/jit-contrib , there was a case on arm64 with zapdisabled that was not covered in the initial change.

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/src/jit/morph.cpp [hunk 1]
```diff
@@ -7527,11 +7527,11 @@ GenTree* Compiler::fgMorphPotentialTailCall(GenTreeCall* call)
             {
                 callType = TYP_I_IMPL;
             }
-            else if (howToReturnStruct == SPK_ByValueAsHfa)
+            else if (howToReturnStruct == SPK_ByValueAsHfa || varTypeIsSIMD(callType))
```
Comment (CarolEidt) [inline src/coreclr/src/jit/morph.cpp]: I'm not terribly familiar with this code, but it seems that it is not attempting to actually provide a valid return value, but ensuring that there will not be downstream errors - is that right?

Comment (sandreenko) [reply src/coreclr/src/jit/morph.cpp]: Yes, it is absolutely right.  at that moment the original call is placed as the root node in the current statement, call's type is changed to void, all that we want to do - exit morphing of any parent nodes that are on the stack without errors. 

The parent nodes could be different - assignments, returns, casts.I did not see any errors when I was just returning TYP_INT 0 node always, but I can't prove that it is safe in general.

Comment (CarolEidt) [reply src/coreclr/src/jit/morph.cpp]: Thanks - it might be worth it to add a comment to the effect.

**Review by CarolEidt — APPROVED** [review]
