### PR TITLE
Fix macOS arm64 Unix breakpoint

### LINKED ISSUE #108541: Cannot step over Debugger.Break() in m3 lldb
### Description

Using lldb and sos to debug .net, while write below C# code:

```csharp
Debugger.Break();
```

it will generate below asm:

```asm
->  0x10087ba38 <+0>: brk    #0
    0x10087ba3c <+4>: ret
```

but it never step over the `brk`, the only way to modify `pc` register manually.

### Reproduction Steps

```
using System.Diagnostics;

namespace ConsoleApp1;

class Program
{
    static void Main(string[] args)
    {
        Debugger.Break();
    }
}
```

Compile and launch with lldb and run it.

### Expected behavior

Enter `ni` to step over `brk`.

### Actual behavior

Always hitting the `brk`.

### Regression?

_No response_

### Known Workarounds

Modify the `pc` register manully.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by janvorli**
Currently we use brk #0, but lldb cannot step over it. Using brk #0xf000 instead works fine on macOS arm64.
On Linux arm64, none of those can be stepped over, neither in lldb nor in gdb.

Close #108541

### CODE REVIEW

**Review by tommcdon — APPROVED** [review]

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/instrsarm64.h [hunk 1]
```diff
@@ -1596,7 +1596,7 @@ INST1(yield,       "yield",        0,      IF_SN_0A,  0xD503203F)
 INST1(brk_windows, "brk_windows",  0,      IF_SI_0A,  0xD43E0000)
                                    //  brk (windows)                SI_0A  1101010000111110 0000000000000000   D43E 0000   0xF000
 
-INST1(brk_unix,    "brk_unix",     0,      IF_SI_0A,  0xD4200000)
+INST1(brk_unix,    "brk_unix",     0,      IF_SI_0A,  0xD43E0000)
                                    //  brk     imm16                SI_0A  11010100001iiiii iiiiiiiiiii00000   D420 0000   imm16
```
Comment (huoyaoyuan) [inline src/coreclr/jit/instrsarm64.h:1600]: brk_windows and brk_unix are the same now. Does the comment need update too?

Comment (janvorli) [reply src/coreclr/jit/instrsarm64.h:1600]: Good point. Actually, it seems it would make sense to unify this so that there is no longer brk_unix and brk_windows.
