### PR TITLE
Properly report `TypedReference` with `ref` fields.

### LINKED ISSUE #71890: Test SetValueDirect_GetValueDirectRoundDataTest failed: Expected 222; Actual -1
<pre>
Starting:    System.Reflection.Tests (parallel test collections = on, max threads = 6)
    System.Reflection.Tests.FieldInfoTests.SetValueDirect_GetValueDirectRoundDataTest(value: 222) [FAIL]
      Assert.Equal() Failure
      Expected: 222
      Actual:   -1
      Stack Trace:
        /_/src/libraries/System.Reflection/tests/FieldInfoTests.cs(587,0): at System.Reflection.Tests.FieldInfoTests.SetValueDirect_GetValueDirectRoundDataTest(Object value)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(64,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
</pre>

* [Helix Logs](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71888-merge-2d294ac9048b4b829d/System.Reflection.Tests/1/console.598ffaf9.log?helixlogtype=result)

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
During the `GcScanRoots` routine we were indicating a `TypedReference` was passed by reference to all managed callers. This means that it would be tracked incorrectly across managed method calls.

Related https://github.com/dotnet/runtime/pull/71675

Fixes https://github.com/dotnet/runtime/issues/71890

/cc @jkotas @davidwrighton

### CODE REVIEW

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapBuilder.cs [hunk 1]
```diff
@@ -211,7 +211,7 @@ private void FakeGcScanRoots(MethodDesc method, ArgIterator argit, CORCOMPILE_GC
         /// <param name="type">Parameter type</param>
         /// <param name="argDest">Location of the parameter</param>
         /// <param name="frame">Frame map to update by marking GC locations</param>
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapBuilder.cs:213]:
```suggestion
        /// <param name="frame">Frame map to update by marking GC locations</param>
        /// <param name="topLevel">Indicates if the call is for a type or inner member</param>
```

**Review by jkotas — APPROVED** [review]
LGTM. Thank you!
