### PR TITLE
Prompt dialog when running GUI app and hostfxr is < 3.*

### LINKED ISSUE #617: 3.1 Runtime prompt fails if .NET Core 2.x runtime is installed
With .NET Core 3.1 the apphost now prompts on missing .NET Core runtime which is amazing. Sadly the application still silently crashes in the following scenario:

- .NET Framework 4.7 or higher installed
- .NET Core 2.1 Runtime installed

In such a scenario no prompt is shown, not even an entry in the event viewer. It might be caused by the core runtime is installed but the "desktop" stuff is not. However there should be definitely a prompt.

Demo:
ezgif com-optimize

Related #8620 and #8222 
ping @dagood @elinor-fung 

previously posted on https://github.com/dotnet/core-setup/issues/8933

### PR DESCRIPTION
**Pull request by mateoatr**
This fixes #617.

### CODE REVIEW

File: src/installer/corehost/corehost.cpp [hunk 1]
```diff
@@ -218,6 +218,22 @@ int exe_start(const int argc, const pal::char_t* argv[])
...
+
+            if (rc == StatusCode::FrameworkMissingFailure)
+            {
+                pal::string_t ver = get_directory(fxr_path);
+                remove_trailing_dir_seperator(&ver);
+
+                fx_ver_t fx_ver;
+                fx_ver_t::parse(get_filename(ver), &fx_ver, false);
+
+                if (fx_ver.get_major() < 3)
```
Comment (vitek-karas) [inline src/installer/corehost/corehost.cpp]: This will work - alternatively we could simply check for the ability to set custom error writer on the `hostfxr` - which is sort of a more precise check (as that is really the functionality we want, we don't care about versions really). I'll leave that up to you.

Comment (vitek-karas) [reply src/installer/corehost/corehost.cpp]: In any case, please add a comment describing what is this trying to achieve and why. The if as is (for the specific error code and so on) feels very arbitrary.

File: src/installer/corehost/corehost.cpp [hunk 2]
```diff
@@ -218,6 +218,22 @@ int exe_start(const int argc, const pal::char_t* argv[])
...
+                {
+                    pal::string_t url = get_download_url(nullptr, nullptr);
+                    trace::error(_X("Installing the latest runtime might help resolve this problem."));
```
Comment (vitek-karas) [inline src/installer/corehost/corehost.cpp]: Did you try this? Do we actually print out any "error" message? As in "There's no available runtime to run this app" (or something similar)... The text you're printing here is just the "How to fix it", not the "What went wrong".

**Review by vitek-karas — COMMENTED** [review]
We should add tests for this.
If you leave the check version based, then the tests are relatively simple (just put hostfxr into a different directory).
If you go with the missing error writer redirection check, the tests are a bit more complex (we would have to create a mock hostfxr - which is not a bad idea anyway - we should have that for several reasons anyway).

File: src/installer/corehost/corehost.cpp [hunk 3]
```diff
@@ -212,12 +212,24 @@ int exe_start(const int argc, const pal::char_t* argv[])
...
+            {
+                hostfxr_set_error_writer_fn set_error_writer_fn = reinterpret_cast<hostfxr_set_error_writer_fn>(custom_error_writer);
+                propagate_error_writer_t propagate_error_writer_to_hostfxr(set_error_writer_fn);
+            }
 
             rc = main_fn_v2(argc, argv, host_path_cstr, dotnet_root_cstr, app_path_cstr);
+
+            if (rc == StatusCode::FrameworkMissingFailure && !custom_error_writer)
+            {
+                pal::string_t url = get_download_url(nullptr, nullptr);
```
Comment (vitek-karas) [inline src/installer/corehost/corehost.cpp]: I don't understand the need for the special prefixes and different new-line handling. I would expect the behavior to be identical regardless of whether we got the error through the custom error writer or directly from here.

We could mimic the error produced by https://github.com/dotnet/runtime/blob/66cb5f9a1bdbb0fd0b357a0dbc862daa0b45e85a/src/installer/corehost/cli/fxr/fx_resolver.messages.cpp#L93. The framework name pretty much has to be `Microsoft.NETCore.App` and the version can be something like the current version of the apphost (so `COMMON_HOST_PKG_VER` for example - as per https://github.com/dotnet/runtime/blob/66cb5f9a1bdbb0fd0b357a0dbc862daa0b45e85a/src/installer/corehost/cli/apphost/apphost.windows.cpp#L98). Maybe we could even share that code to produce the same error message (but it would probably require some tweaking).

**Comment by mateoatr** [comment]
Example of the dialog we get now:
image

**Comment by vitek-karas** [comment]
/cc @richlander @samsp-msft - just to validate that the dialog looks reasonable.
@mateoatr could you please paste the URL this leads to when clicked Yes?

File: src/installer/corehost/corehost.cpp [hunk 4]
```diff
@@ -212,12 +212,24 @@ int exe_start(const int argc, const pal::char_t* argv[])
...
-        hostfxr_set_error_writer_fn set_error_writer_fn = reinterpret_cast<hostfxr_set_error_writer_fn>(pal::get_symbol(fxr, "hostfxr_set_error_writer"));
-
         {
-            propagate_error_writer_t propagate_error_writer_to_hostfxr(set_error_writer_fn);
+            auto custom_error_writer = pal::get_symbol(fxr, "hostfxr_set_error_writer");
+
+            if (custom_error_writer)
+            {
+                hostfxr_set_error_writer_fn set_error_writer_fn = reinterpret_cast<hostfxr_set_error_writer_fn>(custom_error_writer);
+                propagate_error_writer_t propagate_error_writer_to_hostfxr(set_error_writer_fn);
```
[the remark this answers is not in the document]
Comment (elinor-fung) [reply src/installer/corehost/corehost.cpp]: The `propagate_error_writer_t` instance is what needs to go into the outer scope. The if block here shouldn't be necessary - `propagate_error_writer_t` handles being passed nullptr.

File: src/installer/corehost/corehost.cpp [hunk 5]
```diff
@@ -213,11 +213,24 @@ int exe_start(const int argc, const pal::char_t* argv[])
         trace::info(_X("App path: [%s]"), app_path.c_str());
 
         hostfxr_set_error_writer_fn set_error_writer_fn = reinterpret_cast<hostfxr_set_error_writer_fn>(pal::get_symbol(fxr, "hostfxr_set_error_writer"));
-
         {
             propagate_error_writer_t propagate_error_writer_to_hostfxr(set_error_writer_fn);
 
             rc = main_fn_v2(argc, argv, host_path_cstr, dotnet_root_cstr, app_path_cstr);
+
+            if (rc == StatusCode::FrameworkMissingFailure && !set_error_writer_fn)
```
Comment (elinor-fung) [inline src/installer/corehost/corehost.cpp]: Should this just be for apphost GUI? In other cases (non-apphost or non-GUI apphost), the errors from hostfxr should already be traced to the terminal such that they are visible to the user.

File: src/installer/corehost/corehost.cpp [hunk 6]
```diff
@@ -213,11 +213,24 @@ int exe_start(const int argc, const pal::char_t* argv[])
...
+            {
+                pal::string_t missing_fw = L"Microsoft.NETCore.App";
+                pal::string_t fw_ver = _STRINGIFY(CUREXE_PKG_VER);
```
Comment (elinor-fung) [inline src/installer/corehost/corehost.cpp]: I think it is possible for the apphost version to be different from the framework version? If so, this could be a bit of a lie and unfortunately, we don't know the exact framework version at this point, so I'm not sure what could be a better alternative.

We currently have two dialog message scenarios:
- missing framework (specific framework not found)
- missing runtime (no hostfxr found at all)

We could:
- go through the missing framework path (what is in this change now)
  - version listed might not be correct (I think?)
- go through the missing runtime path
  - may be a bit confusing, since the message just says .NET Core needs to be installed and the user already has some version of it installed
- add different message for this case (hostfxr < 3.0, FrameworkMissingFailure)
  - not sure what exactly this should convey. Maybe that a compatible version of .NET Core was not found?

Comment (vitek-karas) [reply src/installer/corehost/corehost.cpp]: I definitely see the potential confusion. I think we could change the error message a little bit to note that the version is only approximate. I think the apphost version should pretty much always be equal or lower to the required runtime version (if the app was built with our SDK), so if we word it as "approximate" it should be good enough.

File: src/installer/corehost/corehost.cpp (hunk 5 above)
Comment (vitek-karas) [reply src/installer/corehost/corehost.cpp]: Great catch. Technically this should be done whenever the error writer for the apphost is redirected (which happens to be only for GUI apps, but maybe in the future there will be other cases). It is also easier to detect/explain than checking the GUI bit here (or somehow propagating that information).
But in that case it has to - as in if we don't redirect error writer we must not report the error second time as it will produce very confusing output.

**Comment by vitek-karas** [comment]
Note about the URL:
> URL: https://dotnet.microsoft.com/download?framework=Microsoft.NETCore.App&framework_version=5.0.0-dev.20057.1&arch=x64&rid=win10-x64&apphost_version=5.0.0-dev.20057.1

In this case we should not include the `framework_version` because we don't know that information (see the other discussion). We should leave it to the server side to handle this case and deduce the approximate version from the `apphost_version`. We can be sort of fuzzy in the dialog message (since that is best effort to help the user), but we should not be fuzzy in the URL as that is for machines to consume.

**Comment by richlander** [comment]
The dialog looks good.

**Comment by danmosemsft** [comment]
@richlander should it say ".NET" for 5.0 instead of ".NET Core"?

**Comment by richlander** [comment]
That's a great question. Let's leave it as-is for now. We haven't done the full branding exercise for .NET 5. We also have to reason about these strings for <5 and 5+. I don't want to propose maintaining conditional strings.

File: src/installer/corehost/corehost.cpp [hunk 7]
```diff
@@ -218,6 +218,7 @@ int exe_start(const int argc, const pal::char_t* argv[])
 
             rc = main_fn_v2(argc, argv, host_path_cstr, dotnet_root_cstr, app_path_cstr);
 
+#if defined(_WIN32) && defined(FEATURE_APPHOST)
```
Comment (vitek-karas) [inline src/installer/corehost/corehost.cpp]: While the ifdef is correct it does not guarantee that we will only do this for GUI apps. Win32 console app will still try to do this as well. I think the right check is to only do this if the apphost error writing is redirected (so check that the g_error_writer in trace.cpp is not null.

File: src/installer/corehost/cli/test/mockhostfxr/CMakeLists.txt [hunk 8]
```diff
@@ -0,0 +1,17 @@
+# Licensed to the .NET Foundation under one or more agreements.
+# The .NET Foundation licenses this file to you under the MIT license.
+# See the LICENSE file in the project root for more information.
+
+cmake_minimum_required (VERSION 2.6)
+project(mockhostfxr)
```
Comment (vitek-karas) [inline src/installer/corehost/cli/test/mockhostfxr/CMakeLists.txt]: Since the test relies on the fact that the hostfxr will not have custom error writer entry point, I think it would be cleaner to call this `mockhostfxr_2_2`. Basically make it obvious that this is trying to imitate the pre-3.0 hostfxr.
I can imagine that one day we'll have a 3.0 hostfxr mock, which will have the error writer.

File: src/installer/test/HostActivation.Tests/DotNetBuilder.cs [hunk 9]
```diff
@@ -65,6 +67,22 @@ public DotNetBuilder AddMicrosoftNETCoreAppFrameworkMockHostPolicy(string versio
             return this;
         }
 
+        /// <summary>
+        /// Use a mock version of HostFxr.
+        /// </summary>
+        public DotNetBuilder UseMockHostFxr()
```
Comment (vitek-karas) [inline src/installer/test/HostActivation.Tests/DotNetBuilder.cs]: This works, but I personally would do it slightly differently:
* call this AddMockHostFxr(string version)
* change the behavior to add a new version folder and into it the mock
* Add the notion of pre-3.0 hostfxr into the naming/parameters somehow
* Add another method to remove all other hostfxr versions (or maybe add one to remove all and then add)

The idea is that we should try to test as close to real world as possible - so in this case, the test would like to test against 2.2 hostfxr, so it should be in 2.2 folder.

File: src/installer/test/HostActivation.Tests/PortableAppActivation.cs [hunk 10]
```diff
@@ -405,6 +406,48 @@ public void AppHost_GUI_FrameworkDependent_MissingRuntimeFramework_ErrorReported
...
+
+            string dotnetWithMockHostFxr = SharedFramework.CalculateUniqueTestDirectory(Path.Combine(TestArtifact.TestArtifactsPath, "guiErrors"));
+            using (new TestArtifact(dotnetWithMockHostFxr))
+            {
+                Directory.CreateDirectory(dotnetWithMockHostFxr);
+                string expectedErrorCode = Constants.ErrorCode.FrameworkMissingFailure.ToString("x");
+
+                var dotnetBuilder = new DotNetBuilder(dotnetWithMockHostFxr, sharedTestState.RepoDirectories.BuiltDotnet, "hostfxrFrameworkMissingFailure");
+                var dotnet = dotnetBuilder.Build();
+                dotnetBuilder.UseMockHostFxr();
```
Comment (vitek-karas) [inline src/installer/test/HostActivation.Tests/PortableAppActivation.cs]: Logically this should be called before the call to `Build`.

**Review by vitek-karas — APPROVED** [review]
Nothing major, just test changes

File: src/installer/corehost/cli/apphost/apphost.windows.cpp [hunk 11]
```diff
@@ -61,10 +61,11 @@ namespace
         if (pal::getenv(_X("DOTNET_DISABLE_GUI_ERRORS"), &gui_errors_disabled) && pal::xtoi(gui_errors_disabled.c_str()) == 1)
             return;
 
-        pal::string_t dialogMsg = _X("To run this application, you must install .NET Core.\n\n");
+        pal::string_t dialogMsg;
```
Comment (elinor-fung) [inline src/installer/corehost/cli/apphost/apphost.windows.cpp]: Doesn't this mean that the missing framework case where 3.0+ hostfxr is present will no longer have the `To run this application...` portion of the message?

Comment (mateoatr) [reply src/installer/corehost/cli/apphost/apphost.windows.cpp]: Right, I'm adding it back. Although, I think that then the custom error message will look too repetitive `dialogMsg = "To run this application, you must install .NET Core.\n\nTo run this application, you need to install a newer version of .NET Core."`.

Comment (elinor-fung) [reply src/installer/corehost/cli/apphost/apphost.windows.cpp]: Yeah, I'd think we shouldn't have it for the custom message case (i.e. the custom message replaces `To run this application, you must install .NET Core.\n\n` instead of adding to it).

File: src/installer/test/TestUtils/HostFxrVersion.cs [hunk 12]
```diff
@@ -0,0 +1,24 @@
+﻿namespace TestUtils
+{
+    public class HostFxrVersion
```
Comment (elinor-fung) [inline src/installer/test/TestUtils/HostFxrVersion.cs]: I'm not sure having the separate class is really necessary / how much it really provides over just using the `Version` class.

**Review by elinor-fung — APPROVED** [review]

**Comment by Symbai** [comment]
@vitek-karas Now this has been merged, would it be enough as a developer downloading a daily SDK and rebuilding our .NET Core 3.1 application in order to have this fix applied into the apphost or is this .NET 5 exclusive or how does it work?

**Comment by vitek-karas** [comment]
Yes - I think that should work - but obviously, please try it to make sure.

The change is in `apphost.exe` only - so if you build your app with the new "fixed" apphost, it should work regardless of which framework version the app is for.

**Comment by Symbai** [comment]
@vitek-karas: The fix has been merged 2 days ago. Today I downloaded 3.1.2.xx SDK `(fac3a6f52f88451d2677819c413fca5634f9345e, 3.1.200-preview-014917)` and 5.0.x SDK  `(78173fe72e29807ffe33e67fbbc335781e7c911b, 5.0.100-alpha.1.20067.19)` . Tested on a WPF application targeting 3.1 and 5.0 and both will not prompt if .NET Core 2.x is installed only.

How do I know which SDK from https://github.com/dotnet/core-sdk#installers-and-binaries contains the merged commit? And are the daily SDKs still built daily (which I assume if it has been merged 2 days ago, the SDKs should contain the fix?!)

**Comment by vitek-karas** [comment]
I tried with the latest SDK from the core-sdk repo and it does work, but only for 5.0 apps. SDK should restore the matching version of apphost for the TFM of the app it's building. So when building the 3.1 app with 5.0 SDK, it should still use 3.1 apphost. That's exactly what it did on my machine. The result is that the fix is not there (as it was only merged to master).
When I build a 5.0 WinForms app and run it on a machine with only 2.0 installed I get the correct dialog now (the fix).

You could "hack" the build and somehow force the SDK to use 5.0 apphost even for 3.1 apps (some msbuild magic, I think it's possible). The downside of that approach would be that the URL the dialog leads to would still contain apphost_version=5.0. And since that's the only version info available in that scenario, downloading 5.0 would not actually make the app work anyway (although it would produce a much better error message saying install 3.1).

In order to fully fix this for 3.1 we would have to port this change to 3.1 servicing branch.

**Comment by Symbai** [comment]
@vitek-karas Downloaded 5.0 SDK today and now it's working. Guess the SDK installers on https://github.com/dotnet/core-sdk#installers-and-binaries are no longer daily built or commits take a few days longer before it goes into the SDK.

Only question will be, do you think or it is possible this can be ported to 3.1.(2) ? The .NET 5 takes probably more than half a year until its released and we currently have to rely on our own "fix" for this bug for our 3.1 applications.

**Comment by vitek-karas** [comment]
https://github.com/dotnet/core-setup/pull/8987 is the 3.1 servicing PR - note that it has not been approved yet... so no promises 😇
