### PR TITLE
Do not run crossgen2 under GC stress in tests

### LINKED ISSUE #54203: Test failure readytorun/tests/mainv1/mainv1, mainv2, BasicTestWithMcj.sh
Run: [runtime-coreclr gcstress-extra 20210613.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1185494&view=ms.vss-test-web.build-test-results-tab&runId=35636556&resultId=111121&paneView=debug)

Failed tests:
```
CoreCLR Linux arm Checked gcstress0xc_jitstress1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- readytorun/tests/mainv1/mainv1.sh

Assert failure(PID 5856 [0x000016e0], Thread: 5879 [0x16f7]): bIsRealStartFrameUnchanged
File: /__w/1/s/src/coreclr/vm/stackwalk.cpp Line: 1524
Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/readytorun/tests/mainv1/mainv1.sh: line 174:  5856 Aborted                 (core dumped) $CORE_ROOT/corerun $CORE_ROOT/crossgen2/crossgen2.dll -r:$CORE_ROOT/*.dll -r:pwd -o:mainv1.ni.dll mainv1.dll

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/readytorun.tests/mainv1/mainv1.output.txt
Raw output:
BEGIN EXECUTION
Warning: No files matching /root/helix/work/workitem/readytorun/tests/mainv1
Emitting R2R PE file: test.ni.dll
Warning: No files matching /root/helix/work/workitem/readytorun/tests/mainv1
Emitting R2R PE file: fieldgetter.ni.dll
Warning: No files matching /root/helix/work/workitem/readytorun/tests/mainv1
Gathering state for process 5856 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5856.dmp
Written 127619072 bytes (31157 pages) to core file
Dump successfully written
Crossgen failed with exitcode: 134
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/readytorun/tests/mainv1/mainv1.sh
Expected: True
Actual:   False


Stack trace
   at readytorun_tests._mainv1_mainv1_._mainv1_mainv1_sh() in readytorun.tests.XUnitWrapper.dll:token 0x600000c+0x295
```
```
CoreCLR Linux arm Checked gcstress0xc_tailcallstress @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- readytorun/tests/mainv1/mainv1.sh

Assert failure(PID 5803 [0x000016ab], Thread: 5819 [0x16bb]): (GetComponentSize() <= 2) || IsArray()
File: /__w/1/s/src/coreclr/vm/methodtable.cpp Line: 7519
Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/readytorun/tests/mainv1/mainv1.sh: line 160:  5803 Aborted                 (core dumped) $CORE_ROOT/corerun $CORE_ROOT/crossgen2/crossgen2.dll -r:$CORE_ROOT/*.dll -r:pwd -o:fieldgetter.ni.dll fieldgetter.dll

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/readytorun.tests/mainv1/mainv1.output.txt
Raw output:
BEGIN EXECUTION
Warning: No files matching /root/helix/work/workitem/readytorun/tests/mainv1
Emitting R2R PE file: test.ni.dll
Warning: No files matching /root/helix/work/workitem/readytorun/tests/mainv1
Gathering state for process 5803 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5803.dmp
Written 114253824 bytes (27894 pages) to core file
Dump successfully written
Crossgen failed with exitcode: 134
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/readytorun/tests/mainv1/mainv1.sh
Expected: True
Actual:   False


Stack trace
   at readytorun_tests._mainv1_mainv1_._mainv1_mainv1_sh() in readytorun.tests.XUnitWrapper.dll:token 0x600000c+0x295
```
```
CoreCLR Linux arm64 Checked gcstress0xc_jitstress1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- readytorun/tests/mainv1/mainv1.sh
- readytorun/tests/mainv2/mainv2.sh
- baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.sh

Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
at System.Reflection.Metadata.Ecma335.MetadataSizes.ReferenceFits(Int32 bitCount, TableIndex[] tables) in //src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/MetadataSizes.cs:line 472
at System.Reflection.Metadata.Ecma335.MetadataSizes..ctor(ImmutableArray1 rowCounts, ImmutableArray1 externalRowCounts, ImmutableArray1 heapSizes, Int32 metadataVersionByteCount, Boolean isStandaloneDebugMetadata) in /_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/MetadataSizes.cs:line 104 at System.Reflection.Metadata.Ecma335.MetadataBuilder.GetSerializedMetadata(ImmutableArray1 externalRowCounts, Int32 metadataVersionByteCount, Boolean isStandaloneDebugMetadata) in //src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/MetadataBuilder.cs:line 22
at System.Reflection.Metadata.Ecma335.MetadataRootBuilder..ctor(MetadataBuilder tablesAndHeaps, String metadataVersion, Boolean suppressValidation) in /_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/MetadataRootBuilder.cs:line 71
at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestMetadataTableNode.GetData(NodeFactory factory, Boolean relocsOnly) in ILCompiler.ReadyToRun.dll:token 0x6000562+0x251
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable() in ILCompiler.ReadyToRun.dll:token 0x6000324+0x174
at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in ILCompiler.ReadyToRun.dll:token 0x6000130+0x35
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext) in crossgen2.dll:token 0x600015a+0x5f6 at ILCompiler.Program.Run(String[] args) in crossgen2.dll:token 0x6000159+0x52e at ILCompiler.Program.Main(String[] args) in crossgen2.dll:token 0x6000161+0x5 apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fa2adad0c) /root/helix/work/workitem/readytorun/tests/mainv1/mainv1.sh: line 146: 3493 Aborted (core dumped) $CORE_ROOT/corerun $CORE_ROOT/crossgen2/crossgen2.dll -r:$CORE_ROOT/*.dll -r:pwd` -o:test.ni.dll test.dll

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/readytorun.tests/mainv1/mainv1.output.txt
Raw output:
BEGIN EXECUTION
Warning: No files matching /root/helix/work/workitem/readytorun/tests/mainv1
Emitting R2R PE file: test.ni.dll
Gathering state for process 3493 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3493.dmp
Written 137220096 bytes (33501 pages) to core file
Dump successfully written
Crossgen failed with exitcode: 134
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/readytorun/tests/mainv1/mainv1.sh
Expected: True
Actual:   False


Stack trace
   at readytorun_tests._mainv1_mainv1_._mainv1_mainv1_sh() in readytorun.tests.XUnitWrapper.dll:token 0x600000c+0x295
```

### PR DESCRIPTION
**Pull request by AntonLapounov**
Unset `COMPlus_GCName`, `COMPlus_GCStress`, `COMPlus_HeapVerify`, and `COMPlus_ReadyToRun` environment variables before running `crossgen2` for `mainv1`, `mainv2`, and `BasicTestWithMcj` tests as we already do for other tests. Use `setlocal` / `endlocal` and `export -n` / `export` commands to simplify saving and restoring original variable values.

Fixes #54203. @dotnet/crossgen-contrib

### CODE REVIEW

File: src/tests/readytorun/coreroot_determinism/coreroot_determinism.csproj [hunk 1]
```diff
@@ -4,8 +4,6 @@
     <CLRTestKind>BuildAndRun</CLRTestKind>
     <CLRTestPriority>0</CLRTestPriority>
     <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' != 'coreclr'">true</CLRTestTargetUnsupported>
-    <!-- See https://github.com/dotnet/runtime/issues/50704 -->
-    <GCStressIncompatible>true</GCStressIncompatible>
```
Comment (AntonLapounov) [inline src/tests/readytorun/coreroot_determinism/coreroot_determinism.csproj:8]: This test should pass after #56770 disabled propagating `COMPlus_GCStress` environment variable to `crossgen2`.

**Review by trylek — APPROVED** [review]
LGTM, thanks for fixing!
