### PR TITLE
Fix #70849: Print LARGEJMP instruction on ARM64

### LINKED ISSUE #70849: emitter::emitDispIns() does not print LARGEJMP instruction code on ARM64
### Description

On ARM32, [emitter::emitDispIns()](https://github.com/dotnet/runtime/blob/ab998cc9dc5dcd51881d2e98e3a35102ce83e193/src/coreclr/jit/emitarm64.cpp#L12277) has a special case for printing LARGEJMP instructions; this case does not exist on [ARM64](https://github.com/dotnet/runtime/blob/ab998cc9dc5dcd51881d2e98e3a35102ce83e193/src/coreclr/jit/emitarm64.cpp#L12277). Thus, hex-encoded instructions for LARGEJMP instructions are missing in ARM64 disassemblies. To aid debugging on ARM64, this case should be added to `emitter::emitDispIns()` in `emitarm64.cpp`.

### Reproduction Steps

* On ARM64, set `COMPlus_JitDisasm` to create a disassembly of a method containing large jumps.
  * Jumps crossing hot/cold sections are always long; enabling `COMPlus_JitFakeProcedureSplitting` and `COMPlus_JitStressProcedureSplitting` may help brute-force the reproduction.

### Expected behavior

* Jump instructions marked as `LARGEJMP` have hex-encoded instructions, like so:
`54000BC2          bhs     G_M1214_IG21`

### Actual behavior

* Jump instructions marked as `LARGEJMP` are missing their hex-encoded instruction, like so:
`                  bhs     (LARGEJMP)G_M1214_IG21`

### Regression?

No.

### Known Workarounds

N/A

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by amanasifkhalid**
These changes address #70849 by implementing the special case of printing the LARGEJMP pseudo-instruction in `emitter::emitDispIns` on ARM64. To achieve functional and organizational parity between the ARM32 and ARM64 implementations, `emitter::emitDispIns` has been re-architected as so:
* On ARM64, the method's logic has been moved to `emitter::emitDispInsHelp` (just like on ARM32). The method now checks for the special LARGEJMP case, and calls the appropriate method.
* On both architectures, the logic for printing LARGEJMP instructions has been moved to its own method.

### CODE REVIEW

File: src/coreclr/jit/emitarm.cpp [hunk 1]
```diff
@@ -7678,6 +7678,62 @@ void emitter::emitDispInsHelp(
...
+
+    // Next, display the unconditional branch
+
+    // Reset the local instrDesc
+    memset(&idJmp, 0, sizeof(idJmp));
+
+    pidJmp->idIns(INS_b);
+    pidJmp->idInsFmt(IF_T2_J2);
+    pidJmp->idInsSize(emitInsSize(IF_T2_J2));
+    pidJmp->idjShort = 0;
```
Comment (Wraith2) [inline src/coreclr/jit/emitarm.cpp:7721]: This is set to 1 above and then 0 here. Are both needed? Does pidJmp point to a different piece of memory in these cases?

Comment (amanasifkhalid) [reply src/coreclr/jit/emitarm.cpp:7721]: `idjShort` is initially set to 1 to satisfy an [assert ](https://github.com/dotnet/runtime/blob/058f83b9102aea36bab3ffe1068d2d842a07129d/src/coreclr/jit/emitarm.cpp#L7616) in `emitDispInsHelp` , as we emit a short conditional branch first for the pseudo-instruction. While the following unconditional branch is long (thus suggesting `idjShort` should be 0), I don't see any asserts in its control flow through `emitDispInsHelp` that require `idjShort == 0`, though that could change in the future.

This looks weird because `pidJmp` is used to emit both the short conditional and the long unconditional branches, but I think the logic is correct.

Comment (BruceForstall) [reply src/coreclr/jit/emitarm.cpp:7721]: The memory pointed to gets zeroed between uses (so zeroing isn't required, perhaps, but in this case it's best to be clear and have it).

File: src/coreclr/jit/emitarm64.cpp [hunk 2]
```diff
@@ -12394,31 +12509,71 @@ void emitter::emitDispIns(
...
+        }
+        break;
 
         case IF_BI_1B: // BI_1B   B.......bbbbbiii iiiiiiiiiiittttt      Rt imm6, simm14:00
+        {
             assert(insOptsNone(id->idInsOpt()));
             emitDispReg(id->idReg1(), size, true);
             emitDispImm(emitGetInsSC(id), true);
-            if (id->idIsBound())
+
```
Comment (BruceForstall) [inline src/coreclr/jit/emitarm64.cpp:12549]: The code here looks exactly the same as the code above except the `emitDispImm(emitGetInsSC(id), true);` case. Could you merge them and then put just the `emitDispImm(emitGetInsSC(id), true);` call under an `if`?

**Review by BruceForstall — CHANGES_REQUESTED** [review]
This looks great, just one request.

Can you share a before/after example of the output?

File: src/coreclr/jit/emitarm.cpp (hunk 1 above)
Comment (Wraith2) [reply src/coreclr/jit/emitarm.cpp:7721]: I agree, clarity is important. It might be worth a comment to explain that two different things are being done through the ptr but it's not a problem without.

**Comment by amanasifkhalid** [comment]
> Can you share a before/after example of the output?

Sure thing. Consider the following (large) conditional branch:
`cbz     x0, G_M55167_IG07`

The JIT converts this instruction to a "jump stub" by inverting the condition and emitting a short branch, followed by an unconditional branch to the original target. Previously, `emitDispIns` did not support printing jump stubs, and thus printed this incorrectly as so:
```
cbz     (LARGEJMP)G_M55167_IG07
```
(note the missing register argument, and no hex encoding of the instruction)

This jump stub now prints correctly, as so:
```
B5000040          cbnz    x0, pc+1 instructions
1400001B          b       (LARGEJMP)G_M55167_IG07
```
The hex encodings are now present, and both instructions in the jump stub are printed correctly.
Note that this behavior largely won't be visible until hot/cold splitting is enabled on ARM64 via this [PR.](https://github.com/dotnet/runtime/pull/70708)

**Review by BruceForstall — APPROVED** [review]
Looks good.
