### PR TITLE
JIT: Fix small->uint->float casts with AVX-512

### LINKED ISSUE #112871: JIT: Wrong result with double comparison
```csharp
// Generated by Fuzzlyn v2.4 on 2025-02-23 17:30:17
// Run on X64 Windows
// Seed: 18098778274409643257-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86avx512fx64,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 23.4 KiB to 0.4 KiB in 00:01:16
// Debug: Prints 0 line(s)
// Release: Prints 1 line(s)
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static short s_1;
    public static void Main()
    {
        ushort vr0 = default(ushort);
        s_1 = -1;
        if (((double)0 <= (uint)s_1))
        {
            System.Console.WriteLine(vr0);
        }
    }
}
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by saucecontrol**
Fixes #112871 

In lowering, we had logic that inserted an intermediate cast to int when casting small types to/from floating.  The float->small case was already handled by morph and will not appear in lowering.  The other direction doesn't require a cast as long as the small type is handled correctly in the containment check and codegen.

The extra cast that was being inserted broke small->uint->floating conversions, for which uint->floating is now handled directly by AVX-512 instructions.

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=961815&view=ms.vss-build-web.run-extensions-tab) show a few hits where the uint->floating conversion instruction is restored, but all cases are on loads of unsigned small types where it wouldn't matter.

```diff
        movzx    rax, byte  ptr [rbp-0x0F]
        vxorps   xmm0, xmm0, xmm0
-       vcvtsi2sd xmm0, xmm0, eax
+       vcvtusi2sd xmm0, xmm0, eax
```

I've added a regression test for the Fuzzlyn example, which does fail without the fix.

There are a few improvements as well.  I removed a restriction on containment of memory operands for ulong->floating casts when we can use the AVX-512 conversion instructions:

```diff
-       mov      rax, qword ptr [rdi]
        vxorps   xmm0, xmm0, xmm0
-       vcvtusi2ss xmm0, xmm0, rax
+       vcvtusi2ss xmm0, xmm0, qword ptr [rdi]
```

And we're now skipping the insertion of unnecessary int casts, which eliminates some movs:

```diff
-       mov      eax, esi
        vxorps   xmm1, xmm1, xmm1
-       vcvtsi2ss xmm1, xmm1, eax
+       vcvtsi2ss xmm1, xmm1, esi
```

### CODE REVIEW

File: src/coreclr/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -8567,26 +8545,14 @@ void Lowering::ContainCheckCast(GenTreeCast* node)
...
-                if (castOp->IsCnsNonZeroFltOrDbl())
-                {
-                    MakeSrcContained(node, castOp);
-                }
-                else
-                {
-                    srcIsContainable = true;
-                }
+                // The ulong->floating SSE2 fallback requires the source to be in register
+                srcIsContainable = !varTypeIsSmall(srcType) && ((srcType != TYP_ULONG) || comp->canUseEvexEncoding());
```
Comment (jakobbotsch) [inline src/coreclr/jit/lowerxarch.cpp:8555]: Why this `varTypeIsSmall` check? It is almost certainly wrong.

Comment (saucecontrol) [reply src/coreclr/jit/lowerxarch.cpp:8555]: I think if you read the method top to bottom it makes sense, or at least the update makes as much sense as the original.  Having the `isMemoryOp` check on this one when it's not included in the other branches would be odd.

Perhaps the name of the variable could be improved, like maybe call it `srcCanBeUsedFromMemory`, which is basically what the comment above its declaration says.

Comment (jakobbotsch) [reply src/coreclr/jit/lowerxarch.cpp:8555]: The point is that using the small type of an arbitrary operand is meaningless. Any node type can decide to store `TYP_SHORT` in its `gtType` and should be assumed throughout the JIT to produce a `TYP_INT` value. An "if this operand is a load that loads 1 or 2 bytes, then it is not containable" check makes sense, but without the "is a load" we are just querying a property that we don't know what means. In an ideal world `TypeGet()` would be returning `genActualType(gtType)`, and the only way to access the size of a load would be with something like `node->AsIndir()->GetOperationType()`.

E.g. one confusion that arises in this code is the treatment of reg-optional. It should be perfectly fine to mark a `TYP_SHORT` node as reg-optional here. When such a node is spilled it is spilled to a 4 byte stack slot, so it can be used just fine from memory. Hence small-typed indirs cannot be contained, but they can be marked reg optional. (I'm not suggesting we change that in this PR, just pointing it out.)

> I think if you read the method top to bottom it makes sense, or at least the update makes as much sense as the original. Having the isMemoryOp check on this one when it's not included in the other branches would be odd.

Yes, I see it in the other branch too. Ok, let's keep it as is then and maybe we will clean it up on another occasion.

**Review by jakobbotsch — APPROVED** [review]
Thanks for fixing this.
