### PR TITLE
[Mono] Correct the behavior of Equals

### LINKED ISSUE #69424: Vector test failures on tvos on the rolling build #1774196
### Description

Several test failures for net7.0-tvOS-Release-arm64-Mono_Release-OSX.1015.Amd64.AppleTV.Open on rolling build https://runfo.azurewebsites.net/view/build/?number=1774196. Please find below list of failing tests on tvos.

[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128DoubleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.runtime.intrinsics.tests.vectors.vector128tests.vector128doubleequalsnantest%22)
[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128SingleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.runtime.intrinsics.tests.vectors.vector128tests.vector128singleequalsnantest%22)
[System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SingleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.runtime.intrinsics.tests.vectors.vector64tests.vector64singleequalsnantest%22)
[System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64DoubleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.runtime.intrinsics.tests.vectors.vector64tests.vector64doubleequalsnantest%22)
[System.Numerics.Tests.PlaneTests.PlaneEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.planetests.planeequalsnantest%22)
[System.Numerics.Tests.QuaternionTests.QuaternionEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.quaterniontests.quaternionequalsnantest%22)
[System.Numerics.Tests.Vector2Tests.Vector2EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.vector2tests.vector2equalsnantest%22)
[System.Numerics.Tests.Matrix3x2Tests.Matrix3x2EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.matrix3x2tests.matrix3x2equalsnantest%22)
[System.Numerics.Tests.Matrix4x4Tests.Matrix4x4EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.matrix4x4tests.matrix4x4equalsnantest%22)
[System.Numerics.Tests.Vector3Tests.Vector3EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.vector3tests.vector3equalsnantest%22)
[System.Numerics.Tests.GenericVectorTests.VectorSingleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.genericvectortests.vectorsingleequalsnantest%22)
[System.Numerics.Tests.GenericVectorTests.VectorDoubleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.genericvectortests.vectordoubleequalsnantest%22)
[System.Numerics.Tests.Vector4Tests.Vector4EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.vector4tests.vector4equalsnantest%22)

From testResult.xml
image

### Reproduction Steps

Failed on rolling build https://dev.azure.com/dnceng/public/_build/results?buildId=1774196&view=logs&j=f4520fb1-1559-5885-1d9c-3cb3f6a85e23&t=6c7a8cfe-f92e-569a-eef9-b2ad3e13056d&l=56

### Expected behavior

Tests should pass

### Actual behavior

Tests are failing with exception.
image

### Regression?

_No response_

### Known Workarounds

For now we can skip on tvos failing tests.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by fanyang-mono**
There isn't a SIMD instruction could match the behavior of how .NET handles vector `Equals` when it comes to compare NaN. This PR removes the SIMD intrinsics support for `Vector<T>.Equals`, `Vector{64,128}<T>.Equals` and `Vector4.Equals`.

The corresponding CoreCLR change could be found at https://github.com/dotnet/runtime/pull/68691

Fixes #69424

### CODE REVIEW

File: src/mono/mono/mini/mini-llvm.c [hunk 1]
```diff
@@ -306,7 +306,7 @@ static LLVMIntPredicate cond_to_llvm_cond [] = {
 };
 
 static LLVMRealPredicate fpcond_to_llvm_cond [] = {
-	LLVMRealOEQ,
+	LLVMRealUEQ,
```
Comment (vargaz) [inline src/mono/mono/mini/mini-llvm.c:309]: Do all these cases need to be changed ?

Comment (fanyang-mono) [reply src/mono/mono/mini/mini-llvm.c]: Only one place should be changed. I reverted the unwanted change.

**Review by vargaz — APPROVED** [review]
