### PR TITLE
[mono] Include filename in Invalid image error messages

### LINKED ISSUE #31649: [mono] Test failed on Helix: System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath
`System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath` fails on Helix. It will be skipped with ActiveIssue in #2087.

```
System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(seek: 0) [FAIL]
      Assert.Contains() Failure
      Not found: /tmp/AssemblyTests_fhspupwv.kh4/LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath_358_649ae850
      In value:  Invalid Image
      Stack Trace:
           at System.AssertExtensions.ThrowsContains[BadImageFormatException](Action action, String expectedMessageContent)
           at System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(Int32 seek)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(seek: 5) [FAIL]
      Assert.Contains() Failure
      Not found: /tmp/AssemblyTests_ezgcvxxh.ng3/LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath_358_74e9dbc3
      In value:  Invalid Image
      Stack Trace:
           at System.AssertExtensions.ThrowsContains[BadImageFormatException](Action action, String expectedMessageContent)
           at System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(Int32 seek)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(seek: 50) [FAIL]
      Assert.Contains() Failure
      Not found: /tmp/AssemblyTests_c02d054y.sjs/LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath_358_05123eda
      In value:  Invalid Image
      Stack Trace:
           at System.AssertExtensions.ThrowsContains[BadImageFormatException](Action action, String expectedMessageContent)
           at System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(Int32 seek)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(seek: 100) [FAIL]
      Assert.Contains() Failure
      Not found: /tmp/AssemblyTests_4egqppii.day/LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath_358_3c0ef32a
      In value:  Invalid Image
      Stack Trace:
           at System.AssertExtensions.ThrowsContains[BadImageFormatException](Action action, String expectedMessageContent)
           at System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(Int32 seek)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

### LINKED ISSUE #31650: [mono] Test failed on Helix: System.Reflection.Tests.AssemblyTests.LoadFile_NoSuchPath_ThrowsFileNotFoundException
`System.Reflection.Tests.AssemblyTests.LoadFile_NoSuchPath_ThrowsFileNotFoundException` fails on Helix. It will be skipped with ActiveIssue in #2087.

```
    System.Reflection.Tests.AssemblyTests.LoadFile_NoSuchPath_ThrowsFileNotFoundException [FAIL]
      Assert.Contains() Failure
      Not found: /home/helixbot/work/A55808B3/w/992A08DD/e/41ab3668ee15411ab49704619372e9f2
      In value:  Invalid Image
      Stack Trace:
           at System.AssertExtensions.ThrowsContains[FileNotFoundException](Action action, String expectedMessageContent)
           at System.Reflection.Tests.AssemblyTests.LoadFile_NoSuchPath_ThrowsFileNotFoundException()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes #31649 
Fixes #31650 

**Testing**:
Reproduced Error via
`<Runtime Repo Root>/build.sh /p:RuntimeFlavor=mono`
Removing `[ActiveIssue("https://github.com/dotnet/runtime/issues/31650", TestRuntimes.Mono)]` in AssemblyTests.cs
Running `dotnet msbuild /t:RebuildAndTest /p:XunitMethodName=System.Reflection.Tests.AssemblyTests.LoadFile_NoSuchPath_ThrowsFileNotFoundException`

Fixing issue resulted in no errors.

### CODE REVIEW

File: src/mono/mono/metadata/icall.c [hunk 1]
```diff
@@ -6030,9 +6033,10 @@ ves_icall_System_Reflection_Assembly_InternalGetAssemblyName (MonoStringHandle f
 
 	if (!image){
 		if (status == MONO_IMAGE_IMAGE_INVALID)
-			mono_error_set_bad_image_by_name (error, filename, "Invalid Image");
-		else
-			mono_error_set_file_not_found (error, filename, "%s", "");
+			mono_error_set_bad_image_by_name (error, filename, "Invalid Image: %s", filename);
+		else {
```
Comment (CoffeeFlux) [inline src/mono/mono/metadata/icall.c]: Nit: no reason to add the curly braces here, Mono style is to omit them for one-line bodies.

**Review by CoffeeFlux — APPROVED** [review]

**Comment by mdh1418** [comment]
@monojenkins build failed
