### PR TITLE
[debugger] Fix crash during Async Break when APC and CET are enabled

### LINKED ISSUE #110552: Crashes during debugging when pausing in VS2022/.NET9
### Description

Since upgrading to .NET 9, I get frequent debugger crashes when pausing in both Debug and Release configurations for my dictionary container. I haven't been able to notice any particular pattern to it.

### Reproduction Steps

Run the 'Benchmarks' project from https://github.com/kg/SimdDictionary/ and hit Pause in VS during the self-test period while it is testing TailCollider, then make sure the Autos or Locals tab(s) are visible in the debugger. Local evaluation will fail and the application process will collapse if VectorizedDictionary code is currently running. Pausing in Main works though. This is not 100% reproducible - setting a breakpoint in a specific spot doesn't reproduce it every time - but if I run the self test and pause repeatedly it will eventually crash while evaluating locals. It seems to happen even if the autos/locals tabs aren't visible.

Image
Image

### Expected behavior

No application crash even if local evaluation fails.

### Actual behavior

Local evaluation fails and the application crashes.

```
---------------------------
Microsoft Visual Studio
---------------------------
The target process exited with code -1073740791 (0xC0000409) while evaluating the function ''.

If the problem happens regularly, consider disabling the Tools->Options setting "Debugging->General->Enable property evaluation and other implicit function calls" or debugging the cause by evaluating the expression from the Immediate window. See help for information on doing this.
---------------------------
OK   Help   
---------------------------
```

### Regression?

I was able to get debugger crashes on .NET8 but it seems much much worse on 9. Could be a regression from upgrading VS, I'm not sure.

### Known Workarounds

It looks like this could be related to some locals being NullRefs, so it's possible the workaround is to not use ref and Unsafe.NullRef at all, but that doesn't seem particularly reasonable.

### Configuration

Visual Studio 2022 Version 17.12.3

```
PS C:\Users\kg> dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

x64 on a Ryzen 7950X

### Other information

Sometimes it says evaluation failed for 'pair.Value' (but I don't have a watch on that, so what gives?)
Pair is defined like so:
```csharp
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct Pair {
    public K Key;
    public V Value;
}
```

### PR DESCRIPTION
**Pull request by thaystg**
When we are running an APC Callback we are not allowed to SetIP because when APC Callback is resuming it will check if the IP is not changed if CET is enabled.
To avoid this problem we use the APC to suspend the thread, but then we enable the single step and continue the thread execution, this will exit the apc callback and pause in the single step, so we are allowed to SetIP to FuncEvalHijack to run FuncEvals.

Fixes #110552

### CODE REVIEW

File: src/coreclr/vm/threadsuspend.cpp [hunk 1]
```diff
@@ -5744,6 +5769,58 @@ BOOL CheckActivationSafePoint(SIZE_T ip)
...
+    // then there is a special case that we need to check. See the comments in debugger.cpp for more information.
+    if (CORDebuggerAttached() && g_pDebugInterface->IsThreadContextInvalid(pThread, interruptedContext))
+        return;
+#endif // DEBUGGING_SUPPORTED && TARGET_WINDOWS
+
+    EECodeInfo codeInfo(ip);
+    if (!codeInfo.IsValid())
+        return;
+
+    DWORD addrOffset = codeInfo.GetRelOffset();
```
Comment (janvorli) [inline src/coreclr/vm/threadsuspend.cpp:5814]: This local is not used

File: src/coreclr/vm/threadsuspend.cpp [hunk 2]
```diff
@@ -5744,6 +5769,58 @@ BOOL CheckActivationSafePoint(SIZE_T ip)
...
+
+    ICodeManager *pEECM = codeInfo.GetCodeManager();
```
Comment (janvorli) [inline src/coreclr/vm/threadsuspend.cpp:5816]: The pEECM is used for assert only - is the assert valuable or was it put in just for debugging purposes during development?

File: src/coreclr/vm/threadsuspend.cpp [hunk 3]
```diff
@@ -5744,6 +5769,58 @@ BOOL CheckActivationSafePoint(SIZE_T ip)
     return isActivationSafePoint;
 }
 
+// This function is called when thread suspension is pending for debugger if APC is enabled.
+// As it's not allowed to change the IP while paused in an APC Callback for security reasons 
+// if CET is enabled, the goal of this function is to enable single step in the paused thread
+// and then pause using single step exception after exit the APC callback
+// this will allow the debugger to setIp to execute FuncEvalHijack.
+#ifdef FEATURE_SPECIAL_USER_MODE_APC
+void HandleSuspensionForInterruptedThreadForDebugger(CONTEXT *interruptedContext)
```
Comment (janvorli) [inline src/coreclr/vm/threadsuspend.cpp:5778]: Instead of cloning the `HandleSuspensionForInterruptedThread`, could you please add a bool argument indicating it is for debugger to the original function and handle it appropriately there?

File: src/coreclr/pal/inc/pal.h [hunk 4]
```diff
@@ -3722,7 +3722,7 @@ VOID
 PALAPI
 FlushProcessWriteBuffers();
 
-typedef void (*PAL_ActivationFunction)(CONTEXT *context);
+typedef void (*PAL_ActivationFunction)(CONTEXT *context, bool fromDebugger);
```
Comment (janvorli) [inline src/coreclr/pal/inc/pal.h:3725]: A nit - can you please keep this function pointer unchanged and add the following function instead?
```c++
void HandleSuspensionForInterruptedThread(CONTEXT *interruptedContext)
{
    HandleSuspensionForInterruptedThread(interruptedContext, false);
}
```

File: src/coreclr/vm/threadsuspend.cpp [hunk 5]
```diff
@@ -5759,7 +5784,7 @@ BOOL CheckActivationSafePoint(SIZE_T ip)
 //       address to take the thread to the appropriate stub (based on the return
 //       type of the method) which will then handle preparing the thread for GC.
 //
-void HandleSuspensionForInterruptedThread(CONTEXT *interruptedContext)
+void HandleSuspensionForInterruptedThread(CONTEXT *interruptedContext, bool suspendForDebugger)
```
Comment (janvorli) [inline src/coreclr/vm/threadsuspend.cpp:5787]: Looking at this and the call site, it might be nicer to pass in the ActivationReason instead of bool.

File: src/coreclr/vm/threadsuspend.cpp [hunk 6]
```diff
@@ -5795,6 +5820,18 @@ void HandleSuspensionForInterruptedThread(CONTEXT *interruptedContext)
     if (!codeInfo.IsValid())
         return;
 
+#ifdef FEATURE_SPECIAL_USER_MODE_APC
+    // It's not allowed to change the IP while paused in an APC Callback for security reasons if CET is turned on
+    // So we enable the single step in the thread that is running the APC Callback
+    // and then it will be paused using single step exception after exiting the APC callback
```
Comment (noahfalk) [inline src/coreclr/vm/threadsuspend.cpp:5826]: If I understand correctly, the pause will occur after executing forward one instruction in the jitted managed code? For example if the CONTEXT where the debugger initially suspended had IP = 0x7ffe1000, and code:
    0x7ffe1000: mov ecx, 5
    0x7ffe1005: mov rax, 0x27c3ad47000
    0x7ffe100f: jmp qword ptr [rax]
    
    
Once we set the single step bit, resume, and get notified that the single step has completed will the IP now be 0x7ffe1005 and we've executed that first mov instruction? If so that could be problematic because executing that instruction may have changed what line of source we are on, changed the value of variables, or shifted the thread from a GC-safe-point to a non-GC-safe-point.

If that is the case, a couple potential alternatives:
1. Perhaps we don't need to hijack at all and we could run the func-eval from inside the APC? The purpose of the hijack is to get control of the thread to run what code we wanted to run and the APC has already done that for us. To make this work we'd have to be sure that stack working works correctly across the APC frame and that it is legal to recursively nest APCs on the stack.
2. Instead of a single-step maybe we could use a breakpoint to stop execution instead?
3. In the worst case, we might need to disallow func-eval on threads that were suspended by APC but I'm hoping that wouldn't impact most func-evals that debuggers do. Debuggers commonly pick the thread which sent the debug event to run the func-eval and that thread shouldn't have needed the APC to transition because it was already getting sent into some exception handler or runtime helper that triggered the debug event.

Comment (thaystg) [reply src/coreclr/vm/threadsuspend.cpp:5826]: What is the problem of changing the line of source we are on, changed the value of the variables? When we ask for an APC we don't know exactly when it will be executed right? What is the problem in pausing not exactly where it was paused by the APC call, but on the next instruction?

Comment (janvorli) [reply src/coreclr/vm/threadsuspend.cpp:5826]: The APC serves us for suspending the thread. It is delivered to it at "random" place. However, with the single step issue that Noah has raised, there can be a problem. When we get the APC callback (the ApcActivationCallback is called), we first check if the context instruction pointer is at activation safe point and we don't call the HandleSuspensionForInterruptedThread if it was not. The check for the activation safe point is here:
https://github.com/dotnet/runtime/blob/dda0d4ea906a5a87f3ad2025ebaa3de89a0da16d/src/coreclr/vm/threadsuspend.cpp#L5728-L5745

Now with this single step mechanism, we could end up moving the instruction pointer to a location that's not activation safe in case the instruction was a call or jump to native code.

Comment (noahfalk) [reply src/coreclr/vm/threadsuspend.cpp:5826]: > What is the problem of changing the line of source we are on, or change the value of the variables? When we ask for an APC we don't know exactly when it will be executed right? What is the problem in pausing not exactly where it was paused by the APC call, but on the next instruction?

I'd expect some of the information that VS is showing the user comes from where the APC initially stopped and some of it is coming from after the func-eval runs. VS is trying to give the illusion that the code remained stopped the entire time so users expect all the results to be consistent. For example imagine the user wrote:
```C#
class Foo
{
    private int _x;
    public int X { get { return _x; } }
    
    Increment()
    {
       _x++; // set breakpoint here
    }
}
```

If they set a breakpoint in the right place the debugger might show them:
```
_x = 4
X = 5
```

Another possibility is that after slipping forward one instruction we are no longer at a GC safe-point (JanV's case above). Either we detect this and block executing the func-eval that we would have normally executed, or we go ahead executing the func-eval and generate some bad behavior later if the GC tries to run from within the func-eval. Bad behavior might be a GC-hole, a deadlock, or an exception depending on what our stackwalker does when run in the unexpected situation that a frame is being asked to report GC references at a non-GC safe point.

File: src/coreclr/pal/inc/pal.h (hunk 4 above)
Comment (thaystg) [reply src/coreclr/pal/inc/pal.h]: done

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by tommcdon — APPROVED** [review]

File: src/coreclr/debug/ee/debugger.cpp [hunk 7]
```diff
@@ -15026,6 +15026,14 @@ HRESULT Debugger::FuncEvalSetup(DebuggerIPCE_FuncEvalInfo *pEvalInfo,
         return CORDBG_E_ILLEGAL_IN_STACK_OVERFLOW;
     }
 
+#ifdef FEATURE_SPECIAL_USER_MODE_APC
+    if (pThread->m_hasPendingActivation)
+    {
+        //It should never get here
```
[the remark this answers is not in the document]
Comment (thaystg) [reply src/coreclr/debug/ee/debugger.cpp:15018]: I will assert, no problem

[the remark this answers is not in the document]
Comment (thaystg) [reply src/coreclr/debug/ee/debugger.cpp]: Done.
