### PR TITLE
Change g_fEEShutDown to be Volatile

### LINKED ISSUE #106242: Test failure: GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh
**Failed in:** [runtime-coreclr jitstress-isas-arm 20240810.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772008&view=ms.vss-test-web.build-test-results-tab&runId=19725850&resultId=123519&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress_isas_incompletehwintrinsic @ OSX.1200.ARM64.Open
    - GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh
```

**Error message:**
```
 
Assert failure(PID 40598 [0x00009e96], Thread: 2901095 [0x2c4467]): (g_fEEShutDown&ShutDown_Finalize1) && GetThread() == FinalizerThread::GetFinalizerThread()
    File: /Users/runner/work/1/s/src/coreclr/vm/appdomain.cpp:3670
    Image: /private/tmp/helix/working/A8B4092F/p/corerun

waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/private/tmp/helix/working/A8B4092F/w/A7A2096B/e/GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh: line 439: 40598 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/A8B4092F/w/A7A2096B/uploads/Reports/GC.API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A8B4092F/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true GetTotalAllocatedBytes.dll ''
[createdump] Gathering state for process 40598 
[createdump] Crashing thread 2c4467 signal 6 (0006)
[createdump] Writing crash report to file /cores/coredump.40598.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /cores/coredump.40598.dmp
[createdump] Written 489799848 bytes (29895 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 1319ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 8/10/2024 1:23:56 PM
Processing /cores/coredump.40598.dmp.crashreport.json
Printing stacktrace from '/cores/coredump.40598.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Errors while running llvm-symbolizer --pretty-print
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/private/tmp/helix/working/A8B4092F/w/A7A2096B/e'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, TextWriter outputWriter)
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/A8B4092F/p
> /private/tmp/helix/working/A8B4092F/w/A7A2096B/e/GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh
```

**Stack trace:**
```
   at GC_API._GC_GetTotalAllocatedBytes_GetTotalAllocatedBytes_._GC_GetTotalAllocatedBytes_GetTotalAllocatedBytes_sh()

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by jkotas**
g_fEEShutDown is read without locks. Make it volatile to ensure that the up-to-date value is read with Arm64 weak memory model.

Cleanup g_fEEShutDown flags

Fixes #106242

### CODE REVIEW

File: src/coreclr/vm/crst.h [hunk 1]
```diff
@@ -90,12 +90,8 @@
 #include <minipal/mutex.h>
 
 #define ShutDown_Start                          0x00000001
-#define ShutDown_Finalize1                      0x00000002
```
Comment (jkotas) [inline src/coreclr/vm/crst.h:93]: Debug-only bit, only used for low-value assert

File: src/coreclr/vm/crst.h [hunk 2]
```diff
@@ -90,12 +90,8 @@
...
 #define ShutDown_Finalize2                      0x00000004
 #define ShutDown_Profiler                       0x00000008
-#define ShutDown_COM                            0x00000010
-#define ShutDown_SyncBlock                      0x00000020
-#define ShutDown_IUnknown                       0x00000040
```
Comment (jkotas) [inline src/coreclr/vm/crst.h:98]: Unused or low-value debug-only bits

File: src/coreclr/vm/interoputil.cpp [hunk 3]
```diff
@@ -1209,9 +1209,6 @@ void CleanupSyncBlockComData(InteropSyncBlockInfo* pInteropInfo)
     }
     CONTRACTL_END;
 
-    if ((g_fEEShutDown & ShutDown_SyncBlock) && IsAtProcessExit() )
```
Comment (jkotas) [inline src/coreclr/vm/interoputil.cpp:1212]: `ShutDown_SyncBlock` was never set in release build, so this condition was always false in the shipping bits. Better to align non-release builds to do the same

File: src/coreclr/vm/threads.cpp [hunk 4]
```diff
@@ -865,11 +865,8 @@ void DestroyThread(Thread *th)
         th->UnmarkThreadForAbort();
     }
 
-    if (g_fEEShutDown == 0)
```
Comment (jkotas) [inline src/coreclr/vm/threads.cpp:868]: Unnecessary check (also, the way it is written triggered a build error after changing g_fEEShutDown  to Volatile)

File: src/coreclr/vm/vars.cpp [hunk 5]
```diff
@@ -151,9 +151,6 @@ GVAL_IMPL_INIT(DWORD, g_externalMethodFixupTraceActiveCount, 0);
 #endif // DEBUGGING_SUPPORTED
 
 #if defined(PROFILING_SUPPORTED_DATA) || defined(PROFILING_SUPPPORTED)
-// Profiling support
-HINSTANCE           g_pDebuggerDll = NULL;
```
Comment (jkotas) [inline src/coreclr/vm/vars.cpp:155]: Dead code that I happen to notice

File: src/coreclr/vm/vars.hpp [hunk 6]
```diff
@@ -450,7 +446,11 @@ EXTERN BOOL g_fComStarted;
 //
 // Global state variables indicating which stage of shutdown we are in
 //
+#ifdef DACCESS_COMPILE
 GVAL_DECL(DWORD, g_fEEShutDown);
+#else
+GVAL_DECL(Volatile<DWORD>, g_fEEShutDown);
```
Comment (jkotas) [inline src/coreclr/vm/vars.hpp:452]: The actual fix

File: src/coreclr/vm/crst.h [hunk 7]
```diff
@@ -90,12 +90,8 @@
 #include <minipal/mutex.h>
 
 #define ShutDown_Start                          0x00000001
-#define ShutDown_Finalize1                      0x00000002
 #define ShutDown_Finalize2                      0x00000004
```
Comment (jkoritzinsky) [inline src/coreclr/vm/crst.h]: Rename now that we don't have `ShutDown_Finalize1`?

```suggestion
#define ShutDown_Finalize                       0x00000004
```

Comment (jkotas) [reply src/coreclr/vm/crst.h]: I have deleted it after taking a closer look. The name was a left-over from how .NET Framework run finalizers during shutdown.

File: src/coreclr/vm/threads.h [hunk 8]
```diff
@@ -1395,9 +1395,8 @@ class Thread
         WRAPPER_NO_CONTRACT;
 #ifdef PROFILING_SUPPORTED
         _ASSERTE(PreemptiveGCDisabled()
-                 || CORProfilerPresent() ||    // This added to allow profiler to use GetILToNativeMapping
+                 || CORProfilerPresent());  // This added to allow profiler to use GetILToNativeMapping
```
Comment (mangod9) [inline src/coreclr/vm/threads.h:1398]: should the comment be updated?

File: src/coreclr/vm/vars.cpp [hunk 9]
```diff
@@ -183,7 +180,11 @@ GVAL_IMPL(bool, g_fProcessDetach);
 GVAL_IMPL_INIT(bool, g_metadataUpdatesApplied, false);
 #endif
 
-GVAL_IMPL_INIT(DWORD, g_fEEShutDown, 0);
+#ifdef DACCESS_COMPILE
+GVAL_IMPL(DWORD, g_fEEShutDown);
+#else
```
Comment (mangod9) [inline src/coreclr/vm/vars.cpp:185]: what is the concern if its also volatile in the DAC?

Comment (jkotas) [reply src/coreclr/vm/vars.cpp:185]: DAC won't compile when this ifdef is deleted.

DAC wraps the global variables with a complicated scheme of operators and implicit casts so that `if (g_fEEShutDown)` in DAC code actually reads the value from remote process. `Volatile<T>` implements similar operators and implicit casts so that ``if (g_fEEShutDown)`` in non-DAC code does volatile read of the value. The two sets of operator overloads do not work together. 

We have similar ifdefs in a few other places where a global variable has different definition for DAC vs. non-DAC, for example: https://github.com/dotnet/runtime/blob/f124c0efbbd527b730297c49758967ec110e35fe/src/coreclr/vm/vars.cpp#L232-L240

File: src/coreclr/vm/threads.h (hunk 8 above)
Comment (jkotas) [reply src/coreclr/vm/threads.h:1398]: I have deleted check related to shutdown.

This comment talks about steady state. I think it is part of the workaround described in https://github.com/dotnet/runtime/blob/f124c0efbbd527b730297c49758967ec110e35fe/src/coreclr/vm/proftoeeinterfaceimpl.cpp#L4832-L4836

**Review by jkoritzinsky — APPROVED** [review]

File: src/coreclr/vm/vars.cpp (hunk 9 above)
Comment (mangod9) [reply src/coreclr/vm/vars.cpp:185]: ok, interesting.
