### PR TITLE
Fix lazy machine state unwinding for MSVC epilogues on x86

### LINKED ISSUE #44519: A different and seemingly random exception occurs System.AccessViolationException/System.ExecutionEngineException/System.NullReferenceException/System.ExecutionEngineException
Running several times the same simple code below, a different and seemingly random exception occurs in different point of the code.

It only occurs on Net 5, instead it works on net core 3.1.
The problem appears to happen only on the x86 target platform.
My OS is windows 10.

Example of errors:

The following error occurs on row --> if (DebugWindowEnabled) Debug.Write(textToWrite);

    System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
System AccessViolationException

The following error occurs on row --> if (DebugWindowEnabled) Debug.Write(textToWrite);

    System.ExecutionEngineException
System ExecutionEngineException

The followingerror occurs on row --> File.AppendAllText(LogFileName, textToWrite.ToString());

    System.NullReferenceException: 'Object reference not set to an instance of an object.'
System NullReferenceException

The followingerror occurs on row --> Task.Run(() => { DequeueLog(); });

    System.ExecutionEngineException: 'Exception_WasThrown'

System ExecutionEngineException2

This is the Program class:

    class Program
    {
        static clsFileLog fileLogCyclesNumber = new clsFileLog(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + "\\Log2");
        static void Main(string[] args)
        {
            for (int i = 0; i < 1000000; i++)
                fileLogCyclesNumber.WriteLine($"Test write LOG2");
        }
    }

And this is the Log class:

    public class clsFileLog : IDisposable
    {
        public bool Enabled { get; set; } = true;
        public bool DebugWindowEnabled { get; set; } = true;
        public string LogFileName { get; set; }

        private ConcurrentQueue<string> logItems = new ConcurrentQueue<string>();
        private readonly object dequeueLocker = new object();

        public clsFileLog(string locLogFile)
        {
            LogFileName = locLogFile;
        }

        public void WriteLine(string strText)
        {
            Write(strText + "\n");
        }

        public void Write(string strText)
        {
            if (Enabled)
            {
                logItems.Enqueue(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + "|" + strText);
                Task.Run(() => { DequeueLog(); });
            }
        }
        public void DequeueLog()
        {

            if (Monitor.TryEnter(dequeueLocker))
            {
                Thread.CurrentThread.Name = $"Log: {Path.GetFileName(LogFileName)}";

                try
                {
                    bool WriteOk = false;
                    Random waitRandNumber = new Random((int)DateTime.Now.Ticks & 0x0000FFFF);
                    while (!logItems.IsEmpty)
                    {
                        string item = null;
                        StringBuilder textToWrite = new StringBuilder();
                        while (logItems.TryDequeue(out item) && textToWrite.Length < 1000000)
                            textToWrite.Append(item);
                        WriteOk = false;
                        do
                        {
                            try
                            {
                                if (DebugWindowEnabled) Debug.Write(textToWrite);

                                File.AppendAllText(LogFileName, textToWrite.ToString());
                                WriteOk = true;
                            }
                            catch
                            {
                                Thread.Sleep(waitRandNumber.Next(10, 100));
                            }
                        } while (WriteOk == false);

                        Thread.Sleep(100);
                    }
                }
                catch { }
                Monitor.Exit(dequeueLocker);
            }
        }
        public void Dispose()
        {
            DequeueLog();
        }
    }

### PR DESCRIPTION
**Pull request by hoyosjs**
MSVC introduced changes into their prologue, epilogue helpers. Particularly `_EH_prolog3_catch_GS_align`/`_EH_epilog3_GS_align` had a `mov esp, ebx` instruction the lazy unwinding didn't handle. This helper ended up getting called by 3 FCalls in all coreclr: 

- `DebugDebugger::Log`
- `StubHelpers::ValidateObjec`
- `COMDelegate::BindToMethodName`

`_EH_epilog3_align` has no direct calls for an FCall. All go though the GS variant first.

As for the other reported reliability issue in `ThreadNative::GetThreadDeserializationTracker`, that one uses another helper `_EH_prolog3_catch`/`_EH_prolog3_catch_GS`. I hand checked the helper, and there's nothing I can see the unwinder wouldn't gracefully interpret. It's also unlikely these stubs would cause an issue just given the amount of FCalls they support (roughly half the CLR's FCalls use that variant).

### CODE REVIEW

File: src/coreclr/vm/i386/gmsx86.cpp [hunk 1]
```diff
@@ -827,6 +827,8 @@ void LazyMachState::unwindLazyState(LazyMachState* baseState,
             case 0x89:                          // MOV r/m, reg
                 if (ip[1] == 0xEC)              // MOV ESP, EBP
                     goto mov_esp_ebp;
+                if (ip[1] == 0xDC)              // MOV ESP, EBP
```
Comment (jkotas) [inline src/coreclr/vm/i386/gmsx86.cpp:830]: Is "MOV ESP, EBP" correct?

Comment (hoyosjs) [reply src/coreclr/vm/i386/gmsx86.cpp:830]: No. I'll update the comment when I finish this patch. This still doesn't solve the whole issue, but I got roped into some other issues the past couple of weeks. Thanks for noting this.

**Comment by jkotas** [comment]
I have hit this crash in #46244. I am fixing it by converting the FCall w/ HMF to QCall. Identifying all FCalls with this problem and converting them to QCalls is one potential way to deal with this problem.

**Comment by janvorli** [comment]
@hoyosjs is this change finished or does it require more work?

**Comment by hoyosjs** [comment]
This hadn't fixed the debugger logging issue and i went on vacation. Jan fixed this in master by turning the FCall into a QCal. Did you find another case where this hit?

**Comment by jkotas** [comment]
Yes, there are several other FCalls that have this problem.

**Comment by hoyosjs** [comment]
I tested this again, and thought it makes sense and the first unwind and a manual walk through the yield the same ebp/esp/return address, somehow later walks end up in a bad walk - which made me wonder if it could have anything to do with tiering. Disabling tiering stops reproducing the issue (even in the absence of the fix, not sure what it changes in terms of places where this could happen). I'm going to port the debugger fix first as this seems to be getting long.

**Comment by jkotas** [comment]
Some manifestations of this bug will be masked when a method higher on the stack saves more non-volatile registers or uses different sequence to save them. It is likely why you see it no longer crash with tiering disabled.

You should check the values of all non-volatile registers after the unwind, not just ebp/esp/return address.

**Comment by hoyosjs** [comment]
The repro I was using on top of 5.0 was going from main directly to the FCall:

```c#
using System.Diagnostics;

class Program
{
    public const int NUM_ITEMS = 5_000_000;

    static void Main(string[] args)
    {
        for (int i = 0; i < NUM_ITEMS; i++)
        {
            string a = new string("Hello");
            Debugger.Log(0, null, a);
        }
    }
}
```

And on the first pass the registers in the lazy state (so `edi`, `esi`, `ebx`) also matched.

**Comment by hoyosjs** [comment]
Actually, this might have been correct all along. Having the native debugger attached with some breakpoint set might have been what tripped the FCALL. I let this run for a while under VS and see no crash, where as before it was in a sub-second manner.

**Review by jkotas — APPROVED** [review]
Looks good to me. I have double checked it under debugger and I have convinced myself that this works fine.

I think this change is low-risk enough to be ported to servicing instead of the QCall changes.
