### PR TITLE
Fix GetGenerationBounds under USE_REGIONS

### LINKED ISSUE #55965: [Regions] pCorProfilerInfo->GetObjectGeneration may fail when running under USE_REGIONS
This is a bug found when working on the [filtering issue](https://github.com/dotnet/runtime/issues/53134).

**Problem:**

The crux of the issue is that under USE_REGIONS, the GC may use some unseen memory address since the last GC during allocation. In particular, in `soh_try_fit`, it may use the `get_new_region` method to acquire a new region, chain it to the end of gen0 and allocate the object there. At that point of time, the `s_currentGenerationTable` maintained by the profiler is unaware of those new addresses, therefore during the `ObjectAllocated` callback, `GetObjectGeneration` for that newly allocated object would fail.

**Repro:**
The profiler authored for the `gcallocate` test can be repurposed to reproduce this bug. Here is the modified code. It does 3 different things:

1. It changes the flags so that it captures SOH as well
2. removed a println, and 
3. assert in failure.

```c++
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#include "gcallocateprofiler.h"

GUID GCAllocateProfiler::GetClsid()
{
    // {55b9554d-6115-45a2-be1e-c80f7fa35369}
	GUID clsid = { 0x55b9554d, 0x6115, 0x45a2,{ 0xbe, 0x1e, 0xc8, 0x0f, 0x7f, 0xa3, 0x53, 0x69 } };
	return clsid;
}

HRESULT GCAllocateProfiler::Initialize(IUnknown* pICorProfilerInfoUnk)
{
    Profiler::Initialize(pICorProfilerInfoUnk);

    HRESULT hr = S_OK;
    if (FAILED(hr = pCorProfilerInfo->SetEventMask2(COR_PRF_ENABLE_OBJECT_ALLOCATED | COR_PRF_MONITOR_OBJECT_ALLOCATED, COR_PRF_HIGH_BASIC_GC)))
    {
        printf("FAIL: ICorProfilerInfo::SetEventMask2() failed hr=0x%x", hr);
        return hr;
    }

    return S_OK;
}

HRESULT STDMETHODCALLTYPE GCAllocateProfiler::ObjectAllocated(ObjectID objectId, ClassID classId)
{
    COR_PRF_GC_GENERATION_RANGE gen;
    HRESULT hr = pCorProfilerInfo->GetObjectGeneration(objectId, &gen);
    if (FAILED(hr))
    {
        assert (false);
        printf("GetObjectGeneration failed hr=0x%x\n", hr);
        _failures++;
    }
    else if (gen.generation == COR_PRF_GC_LARGE_OBJECT_HEAP)
    {
        _gcLOHAllocations++;
    }
    else if (gen.generation == COR_PRF_GC_PINNED_OBJECT_HEAP)
    {
        _gcPOHAllocations++;
    }
    else
    {
        _failures++;
    }

    return S_OK;
}

HRESULT GCAllocateProfiler::Shutdown()
{
    Profiler::Shutdown();
    if (_gcPOHAllocations == 0)
    {
        printf("There is no POH allocations\n");
    }
    else if (_gcLOHAllocations == 0)
    {
        printf("There is no LOH allocations\n");
    }
    else if (_failures == 0)
    {
        printf("%d LOH objects allocated\n", (int)_gcLOHAllocations);
        printf("%d POH objects allocated\n", (int)_gcPOHAllocations);
        printf("PROFILER TEST PASSES\n");
    }
    fflush(stdout);

    return S_OK;
}
```

The bug can then be reproduced by setting these environment, 
```
set CORECLR_ENABLE_PROFILING=1
set CORECLR_PROFILER={55b9554d-6115-45a2-be1e-c80f7fa35369}
set CORECLR_PROFILER_PATH=C:\dev\runtime\artifacts\tests\coreclr\windows.x64.Debug\profiler\gc\gcallocate\Profiler.dll
```
and run GCPerfSim with these parameters:

```
c:\dev\runtime\artifacts\tests\coreclr\Windows.x64.Debug\Tests\Core_Root\CoreRun.exe C:\dev\performance\artifacts\bin\GCPerfSim\release\netcoreapp5.0\GCPerfSim.dll -tc 6 -tagb 100.0 -tlgb 2.0 -lohar 0 -pohar 0 -sohsi 10 -lohsi 0 -pohsi 0 -sohsr 100-4000 -lohsr 102400-204800 -pohsr 100-4000 -sohpi 10 -lohpi 0 -sohfi 0 -lohfi 0 -pohfi 0 -allocType reference -testKind time
```

### PR DESCRIPTION
**Pull request by cshung**
Fixes https://github.com/dotnet/runtime/issues/55965.

### CODE REVIEW

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -43154,6 +43173,71 @@ unsigned int GCHeap::WhichGeneration (Object* object)
...
+            {
+                generation = gen;
+                *ppStart = start;
+                *ppAllocated = end;
+                *ppReserved = reserved;
+                break;
+            }
+            end = reserved = start;
+        }
+        if (generation == -1)
```
Comment (am11) [inline src/coreclr/gc/gc.cpp:43216]:
```suggestion
        if ((ptrdiff_t)generation == -1)
```
to fix the gcc build.

Comment (cshung) [reply src/coreclr/gc/gc.cpp:43216]: Thanks!

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -43154,6 +43173,71 @@ unsigned int GCHeap::WhichGeneration (Object* object)
...
+        {
+            generation = poh_generation;
+        }
+    }
+
+    *ppStart = heap_segment_mem (hs);
+    *ppAllocated = heap_segment_allocated (hs);
+    *ppReserved = heap_segment_reserved (hs);
+#else
+    gc_heap* hp = gc_heap::heap_of ((uint8_t*)object);
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:43198]: you don't need to call heap_of here, `heap_segment_heap (hs) will get you the heap for Server GC

File: src/coreclr/gc/gc.cpp [hunk 3]
```diff
@@ -43154,6 +43173,71 @@ unsigned int GCHeap::WhichGeneration (Object* object)
...
+    if (hs == hp->ephemeral_heap_segment)
+    {
+        uint8_t* reserved = heap_segment_reserved (hs);
+        uint8_t* end = heap_segment_allocated(hs);
+        for (int gen = 0; gen < max_generation; gen++)
+        {
+            uint8_t* start = generation_allocation_start (hp->generation_of (gen));
+            if ((uint8_t*)object > start)
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:43206]: I would do '>=` insteadof `>` here - you could enumerate the objects in a generation and the first object would be the same (it would be a free object but still part of that generation)

File: src/coreclr/gc/gc.cpp [hunk 4]
```diff
@@ -43154,6 +43173,71 @@ unsigned int GCHeap::WhichGeneration (Object* object)
...
+        }
+        if (generation == -1)
+        {
+            *ppStart = heap_segment_mem (hs);
+            *ppAllocated = *ppReserved = generation_allocation_start (hp->generation_of (max_generation - 1));
+        }
+    }
+    else
+    {
+        generation = 2;
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:43224]: please always refrain from using a hard code number especially when we specifically define something for the particular number (as you already wrote above - `max_generate`)

File: src/coreclr/gc/gc.cpp [hunk 5]
```diff
@@ -43154,6 +43173,71 @@ unsigned int GCHeap::WhichGeneration (Object* object)
     return g;
 }
 
+unsigned int GCHeap::WhichRange (Object* object, uint8_t** ppStart, uint8_t** ppAllocated, uint8_t** ppReserved)
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:43176]: >WhichRange [](http://example.com/codeflow?start=21&length=10)

I would probably call this GetGenerationWithRange because generation is an important piece of info you are returning.

File: src/coreclr/gc/gc.cpp [hunk 6]
```diff
@@ -44707,9 +44791,16 @@ GCHeap::GarbageCollectGeneration (unsigned int gen, gc_reason reason)
...
         gc_heap::disable_preemptive (cooperative_mode);
         if (gc_heap::proceed_with_gc_p)
+        {
             pGenGCHeap->settings.init_mechanisms();
+        }
         else
+        {
             gc_heap::update_collection_counts_for_no_gc();
+#ifdef USE_REGIONS
+            GCToEEInterface::DiagUpdateGenerationBounds();
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:44801]: why do we need to call this for regions?

File: src/coreclr/gc/gc.cpp [hunk 7]
```diff
@@ -6683,6 +6688,9 @@ void gc_heap::gc_thread_function ()
 
             if (!should_proceed_with_gc())
             {
+#ifdef USE_REGIONS
+                GCToEEInterface::DiagUpdateGenerationBounds();
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:6692]: why are we calling these for regions instead of calling AddNewRegion in `extend_soh_for_no_gc` like we do in `soh_try_fit`?

File: src/coreclr/vm/eeprofinterfaces.h [hunk 8]
```diff
@@ -47,6 +47,8 @@ void __stdcall GarbageCollectionStartedCallback(int generation, BOOL induced);
 void __stdcall GarbageCollectionFinishedCallback();
 
 void __stdcall UpdateGenerationBounds();
+
+void __stdcall ProfAddNewRegion(int generation, uint8_t* rangeStart, uint8_t* rangeEnd, uint8_t* rangeEndReserved);
```
Comment (Maoni0) [inline src/coreclr/vm/eeprofinterfaces.h:51]: nit - rename to `ProfilerAddNewRegion` to be consistent with the above

File: src/coreclr/gc/gc.cpp [hunk 9]
```diff
@@ -44707,9 +44805,16 @@ GCHeap::GarbageCollectGeneration (unsigned int gen, gc_reason reason)
...
         gc_heap::disable_preemptive (cooperative_mode);
         if (gc_heap::proceed_with_gc_p)
+        {
             pGenGCHeap->settings.init_mechanisms();
+        }
         else
+        {
             gc_heap::update_collection_counts_for_no_gc();
+#ifdef USE_REGIONS
+            GCToEEInterface::DiagUpdateGenerationBounds();
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:44815]: you don't need this with the change in `extend_soh_for_no_gc`

**Comment by Maoni0** [comment]
I haven't really looked at the changes in proftoeeinterfaceimpl.cpp, I'll defer to @davmason.

File: src/coreclr/vm/proftoeeinterfaceimpl.cpp [hunk 10]
```diff
@@ -719,20 +719,102 @@ struct GenerationDesc
...
+        NOTHROW;
+        GC_NOTRIGGER;
+        MODE_ANY; // can be called even on GC threads
+        PRECONDITION(0 <= generation && generation <= 4);
+        PRECONDITION(CheckPointer(rangeStart));
+        PRECONDITION(CheckPointer(rangeEnd));
+        PRECONDITION(CheckPointer(rangeEndReserved));
+    } CONTRACT_END;
+
+    assert (mutex.OwnedByCurrentThread());
```
Comment (davmason) [inline src/coreclr/vm/proftoeeinterfaceimpl.cpp:779]: Is there a reason you used assert instead of _ASSERTE?

File: src/coreclr/vm/proftoeeinterfaceimpl.cpp [hunk 11]
```diff
@@ -719,20 +719,102 @@ struct GenerationDesc
...
+    if (count >= capacity)
+    {
+        ULONG newCapacity = capacity == 0 ? GenerationTable::defaultCapacity : capacity * 2;
+        GenerationDesc *newGenDescTable = new (nothrow) GenerationDesc[newCapacity];
+        if (newGenDescTable == NULL)
+        {
+            // if we can't allocate a bigger table, we'll have to ignore this call
+            RETURN;
```
Comment (davmason) [inline src/coreclr/vm/proftoeeinterfaceimpl.cpp:787]: I don't like being in a corrupted state if this alloc fails. What do you think about setting some bit that says "uh oh we lost track" and returning E_FAIL if we fail to allocate?

File: src/coreclr/vm/proftoeeinterfaceimpl.cpp [hunk 12]
```diff
@@ -769,46 +851,23 @@ static void GenWalkFunc(void * context,
...
-    genDescTable[count].rangeEndReserved = rangeEndReserved;
-
-    generationTable->count = count + 1;
+void GenerationTable::Refresh()
+{
+    // fill in the values by calling back into the gc, which will report
+    // the ranges by calling GenWalkFunc for each one
+    CrstHolder holder(&mutex);    
+    IGCHeap *hp = GCHeapUtilities::GetGCHeap();
+    hp->DiagDescrGenerations(GenWalkFunc, this);
```
Comment (davmason) [inline src/coreclr/vm/proftoeeinterfaceimpl.cpp:864]: I'm worried about a sequence like
* Thread A: GenerationTable::Refresh takes the lock
* Thread B: An allocation that triggers a new region, the GC tries to call in to the profiler and add the region
* B tries to take lock and can't because A is holding it
* Now A and B are deadlocked because A is holding the lock waiting for B to finish allocating before doing the heap walk

Comment (cshung) [reply src/coreclr/vm/proftoeeinterfaceimpl.cpp:864]: In my change, `GenerationTable::Refresh()` can be called in three places, during startup, before GC, and after GC.
The before and after GC callbacks are done within EE suspension.
So it is impossible to have a concurrent allocation happening while Refresh is happening.
The lock is only meant to protect against concurrent read (if that ever happens)

**Review by davmason — APPROVED** [review]
Just the minor things I made comments on, otherwise looks good to me. Thanks Andrew!
