### PR TITLE
Fix #48579

### LINKED ISSUE #48579: Test failure: Loader/ContextualReflection/ContextualReflection/ContextualReflection.sh
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20210221.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1005174&view=ms.vss-test-web.build-test-results-tab&runId=31384380&resultId=111057&paneView=debug)

Failed test:
```
CoreCLR Linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
 -Loader/ContextualReflection/ContextualReflection/ContextualReflection.sh
```

**Error message:**
```
Unhandled exception. TestLibrary.AssertTestException: Assert.IsTrue: 
 at TestLibrary.Assert.HandleFail(String assertionName, String message)
 at TestLibrary.Assert.IsTrue(Boolean condition, String message)
 at ContextualReflectionTest.Program.TestDefineDynamicAssembly(Boolean collectibleContext, AssemblyBuilderAccess assemblyBuilderAccess)
 at ContextualReflectionTest.Program.RunTests()
 at ContextualReflectionTest.Program.Main()
/root/helix/work/workitem/Loader/ContextualReflection/ContextualReflection/ContextualReflection.sh: line 395: 5927 Aborted (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /root/helix/work/workitem/Loader/ContextualReflection/Reports/Loader.ContextualReflection/ContextualReflection/ContextualReflection.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun ContextualReflection.dll ''
Gathering state for process 5927 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5927.dmp
Written 54902784 bytes (13404 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/ContextualReflection/ContextualReflection/ContextualReflection.sh
Expected: True
Actual: False

Stack trace
   at Loader_ContextualReflection._ContextualReflection_ContextualReflection_._ContextualReflection_ContextualReflection_sh()

```

### PR DESCRIPTION
**Pull request by Ap0k**
Fix issue #48579

### CODE REVIEW

File: src/tests/Loader/ContextualReflection/ContextualReflection.cs [hunk 1]
```diff
@@ -730,10 +730,11 @@ void TestDefineDynamicAssembly(bool collectibleContext, AssemblyBuilderAccess as
         {
             AssemblyLoadContext assemblyLoadContext = collectibleContext ? new AssemblyLoadContext("DynamicAssembly Collectable context", true) : AssemblyLoadContext.Default;
             AssemblyName dynamicAssemblyName = new AssemblyName("DynamicAssembly");
+            AssemblyBuilder assemblyBuilder;
 
             using (assemblyLoadContext.EnterContextualReflection())
             {
-                AssemblyBuilder assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(dynamicAssemblyName, assemblyBuilderAccess);
+                assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(dynamicAssemblyName, assemblyBuilderAccess);
```
Comment (stephentoub) [inline src/tests/Loader/ContextualReflection/ContextualReflection.cs:737]: I don't understand the change... what is this fixing?

Comment (Ap0k) [reply src/tests/Loader/ContextualReflection/ContextualReflection.cs:737]: The `AssemblyBuilder` was in the local scope of the `using` statement. If a dynamic assembly is created with the `AssemblyBuilderAccess.RunAndCollect` parameter, this could lead to the fact that at the time of checking the `Assert` condition it was already removed from memory. I think changing the scope of the `AsemblyBuilder` instance will solve the problem of floating test failure.

Comment (stephentoub) [reply src/tests/Loader/ContextualReflection/ContextualReflection.cs:737]: `assemblyBuilder` is never used; in a release build, these should produce exactly the same IL.  Even if this fixes it for a debug build, where this could extend the lifetime of the instance until after the using block and prevent it from being collected before then, is this test never run in a release build?

**Comment by kunalspathak** [comment]
Please revert the change in https://github.com/dotnet/runtime/pull/50592 as part of this PR.

**Comment by Ap0k** [comment]
@kunalspathak Who else can review this PR?

**Comment by kunalspathak** [comment]
> @kunalspathak Who else can review this PR?

@stephentoub has already reviewed and asked question. Could you please answer and suggest a better fix?

File: src/tests/Loader/ContextualReflection/ContextualReflection.cs (hunk 1 above)
Comment (Ap0k) [reply src/tests/Loader/ContextualReflection/ContextualReflection.cs]: Yes, the IL code was the same. Rewrote the test so that the AssemblyBuilder instance is used in the Assert test. The local load test did not issue any errors for an hour.

**Comment by Ap0k** [comment]
> @stephentoub has already reviewed and asked question. Could you please answer and suggest a better fix?

@kunalspathak @stephentoub  The question was answered, but no feedback was received.

**Comment by kunalspathak** [comment]
Looks like the test still fails for same reason, so it might not be the right fix.  https://dev.azure.com/dnceng/public/_build/results?buildId=1132503&view=ms.vss-test-web.build-test-results-tab&runId=34375692&resultId=109547&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by Ap0k** [comment]
1. Fixed a bug with the definition of ALC for dynamic assembly;
2. The test logic has been changed. Now, instead of searching for an assembly in ALC by its name, its load context is determined and compared with the reference one.

Local test results:
```
=== TEST EXECUTION SUMMARY ===
   baseservices.compilerservices.XUnitWrapper           Total:   2, Errors: 0, Failed: 0, Skipped: 0, Time:    8,620s
   baseservices.exceptions.XUnitWrapper                 Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:   67,907s
   baseservices.TieredCompilation.XUnitWrapper          Total:  13, Errors: 0, Failed: 0, Skipped: 0, Time:   52,867s
   baseservices.typeequivalence.XUnitWrapper            Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    4,692s
   baseservices.varargs.XUnitWrapper.dll                Total:   0
   CoreMangLib.system.XUnitWrapper                      Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,572s
   Exceptions.ForeignThread.XUnitWrapper                Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,959s
   GC.API.XUnitWrapper                                  Total:  32, Errors: 0, Failed: 0, Skipped: 0, Time:  199,606s
   GC.Coverage.XUnitWrapper                             Total:   2, Errors: 0, Failed: 0, Skipped: 0, Time:    8,613s
   GC.Features.XUnitWrapper                             Total:  21, Errors: 0, Failed: 0, Skipped: 0, Time:  186,054s
   GC.LargeMemory.XUnitWrapper                          Total:   3, Errors: 0, Failed: 0, Skipped: 0, Time:    6,566s
   GC.Regressions.XUnitWrapper                          Total:  10, Errors: 0, Failed: 0, Skipped: 0, Time:   20,874s
   GC.Scenarios.XUnitWrapper                            Total:  37, Errors: 0, Failed: 0, Skipped: 0, Time:  233,191s
   GC.Stress.XUnitWrapper                               Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    0,347s
   ilasm.PortablePdb.XUnitWrapper                       Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:   17,226s
   ilasm.System.XUnitWrapper                            Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    7,005s
   Loader.AssemblyDependencyResolver.XUnitWrapper       Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    4,798s
   Loader.AssemblyLoadContext30Extensions.XUnitWrapper  Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,580s
   Loader.binding.XUnitWrapper                          Total:   2, Errors: 0, Failed: 0, Skipped: 0, Time:  101,780s
   Loader.CollectibleAssemblies.XUnitWrapper            Total:   2, Errors: 0, Failed: 0, Skipped: 0, Time:    4,069s
   Loader.ContextualReflection.XUnitWrapper             Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    5,234s
   Loader.regressions.XUnitWrapper                      Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,575s
   managed.Compilation.XUnitWrapper                     Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:   74,885s
   readytorun.coreroot_determinism.XUnitWrapper         Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:  418,934s
   readytorun.crossgen2.XUnitWrapper                    Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    8,234s
   readytorun.determinism.XUnitWrapper                  Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:   77,236s
   readytorun.DynamicMethodGCStress.XUnitWrapper.dll    Total:   0
   readytorun.r2rdump.XUnitWrapper                      Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:   19,578s
   readytorun.tests.XUnitWrapper                        Total:   3, Errors: 0, Failed: 0, Skipped: 0, Time:    5,054s
   reflection.DefaultInterfaceMethods.XUnitWrapper      Total:   3, Errors: 0, Failed: 0, Skipped: 0, Time:    3,812s
   reflection.Modifiers.XUnitWrapper                    Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,600s
   reflection.RefEmit.XUnitWrapper                      Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,787s
   reflection.regression.XUnitWrapper                   Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,420s
   reflection.SetValue.XUnitWrapper                     Total:   2, Errors: 0, Failed: 0, Skipped: 0, Time:    5,323s
   reflection.StaticInterfaceMembers.XUnitWrapper       Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,465s
   Regressions.coreclr.XUnitWrapper                     Total:  23, Errors: 0, Failed: 0, Skipped: 0, Time:   15,006s
   tracing.eventactivityidcontrol.XUnitWrapper          Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,641s
   tracing.eventcounter.XUnitWrapper                    Total:   7, Errors: 0, Failed: 0, Skipped: 0, Time:    0,699s
   tracing.eventlistener.XUnitWrapper                   Total:   1, Errors: 0, Failed: 0, Skipped: 0, Time:    3,748s
   tracing.eventpipe.XUnitWrapper                       Total:  13, Errors: 0, Failed: 0, Skipped: 0, Time:   12,297s
                                                               ---          -          -           -        ---------
                                                  GRAND TOTAL: 197          0          0           0        1606,854s (1618,440s)
```

**Comment by kunalspathak** [comment]
I have kicked off another GCStress run.

> * Fixed a bug with the definition of ALC for dynamic assembly;

I do not fully understand this fix and might need to check with @stephentoub on what he thinks.

> * The test logic has been changed. Now, instead of searching for an assembly in ALC by its name, its load context is determined and compared with the reference one.

Why is the test changed? Was earlier the test was not validating the appropriate behaviour?

**Comment by Ap0k** [comment]
> Why is the test changed? Was earlier the test was not validating the appropriate behaviour?

In the previous version of the test, a dynamic assembly with the same name was created for different ALCs. This could lead to incorrect test behavior. For example, first of all, create an assembly in ALC.Default, a search took place and the test completed successfully. Then a dynamic assembly was created for the unloaded ALC, but a search by name led to the fact that the assembly was taken from ALC.Default (this is due to the peculiarities of ALC.Assemblies) and the test failed.
That is why we had to fix the mentioned error and correct the logic of the test. Since it is quite logical that if we check the creation of a dynamic assembly for the selected ALC, then it is easier and faster after its creation to try to find it in this ALC, and not iterate over all assemblies from the context.

**Comment by Ap0k** [comment]
@kunalspathak what are the test results? I see from the logs that the test we are interested in has passed :)

**Comment by kunalspathak** [comment]
> @kunalspathak what are the test results? I see from the logs that the test we are interested in has passed :)

There are lot of other failures that were not there before your changes. I have kicked off another CI job for [main](https://dev.azure.com/dnceng/public/_build/results?buildId=1137403&view=results) to double check if they are related to your changes or not. Could you also check some of the failures and see if they are related to your change?

**Comment by Ap0k** [comment]
@kunalspathak Ok, I'll check

**Comment by kunalspathak** [comment]
> @kunalspathak Ok, I'll check

From the latest main CI runs, it looks like all those test also fail on main, so might not be related to your change. @stephentoub - do you mind reviewing it once again?

**Comment by Ap0k** [comment]
@kunalspathak Who else can review this PR?

**Comment by kunalspathak** [comment]
@agocke @vitek-karas @vsadov - Can someone review this PR?

File: src/tests/Loader/ContextualReflection/ContextualReflection.cs [hunk 2]
```diff
@@ -729,14 +729,15 @@ void TestActivatorCreateInstance(bool isolated)
...
+            AssemblyName assemblyName = new AssemblyName($"DynamicAssembly_{Guid.NewGuid():N}");
 
             using (assemblyLoadContext.EnterContextualReflection())
             {
-                AssemblyBuilder assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(dynamicAssemblyName, assemblyBuilderAccess);
+                assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(assemblyName, assemblyBuilderAccess);
             }
 
-            Assert.IsTrue(assemblyLoadContext.Assemblies.Any(a => AssemblyName.ReferenceMatchesDefinition(a.GetName(), dynamicAssemblyName)));
+            Assert.IsTrue(assemblyLoadContext == AssemblyLoadContext.GetLoadContext(assemblyBuilder));
```
Comment (vitek-karas) [inline src/tests/Loader/ContextualReflection/ContextualReflection.cs:740]: With the fix in CoreLib I would expect both approaches to work - the comparison of ALC as well as searching for the assembly in ALC.Assemblies. Is that true?

File: src/coreclr/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs [hunk 3]
```diff
@@ -147,7 +147,7 @@ private static IntPtr ResolveUnmanagedDllUsingEvent(string unmanagedDllName, Ass
 
             AssemblyLoadContext? loadContextForAssembly = null;
 
-            RuntimeAssembly? rtAsm = assembly as RuntimeAssembly;
+            RuntimeAssembly? rtAsm = GetRuntimeAssembly(assembly);
```
[the remark this answers is not in the document]
Comment (Ap0k) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs:150]: Ok, I'll put this fix in a separate PR with the appropriate tests.

File: src/tests/Loader/ContextualReflection/ContextualReflection.cs (hunk 2 above)
Comment (Ap0k) [reply src/tests/Loader/ContextualReflection/ContextualReflection.cs:740]: Yes, provided that the name of the dynamic assembly is unique for each context (default and unloaded).

File: src/coreclr/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (vitek-karas) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs:150]: The same bug exists in `ValidateAssemblyNameWithSimpleName`. I filed a new issue for it: https://github.com/dotnet/runtime/issues/53181

But it might be a good idea to fix both at the same time.

[the remark this answers is not in the document]
Comment (Ap0k) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs:150]: No problem) I'll do it

File: src/tests/Loader/ContextualReflection/ContextualReflection.cs (hunk 2 above)
Comment (Ap0k) [reply src/tests/Loader/ContextualReflection/ContextualReflection.cs]: Returned the search for dynamic assembly in ALC.Assemblies. The dynamic assembly name is unique for each ALC.

File: src/tests/Loader/ContextualReflection/ContextualReflection.cs [hunk 4]
```diff
@@ -729,11 +729,12 @@ void TestActivatorCreateInstance(bool isolated)
...
+            AssemblyBuilder assemblyBuilder;
+            AssemblyName dynamicAssemblyName = new AssemblyName($"DynamicAssembly_{Guid.NewGuid():N}");
 
             using (assemblyLoadContext.EnterContextualReflection())
             {
-                AssemblyBuilder assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(dynamicAssemblyName, assemblyBuilderAccess);
+                assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(dynamicAssemblyName, assemblyBuilderAccess);
             }
 
             Assert.IsTrue(assemblyLoadContext.Assemblies.Any(a => AssemblyName.ReferenceMatchesDefinition(a.GetName(), dynamicAssemblyName)));
```
Comment (vitek-karas) [inline src/tests/Loader/ContextualReflection/ContextualReflection.cs:740]: I think it should make use of the assemblyBuilder outside of the using block - just to be on the safe side. Otherwise the compiler/JIT can throw it away before it gets to the validation.

Comment (Ap0k) [reply src/tests/Loader/ContextualReflection/ContextualReflection.cs]: Fixed

**Review by vitek-karas — APPROVED** [review]
LGTM - Thanks a lot!

**Comment by vitek-karas** [comment]
I restarted some of the CI legs as there were issues with AzDo.

**Comment by AndyAyersMS** [comment]
You can ignore the "pgo" failures -- for a short time these new pipelines were running on all PRs.

**Comment by vitek-karas** [comment]
Thank @Ap0k for the fix!
