### PR TITLE
JIT: Handle more unsupported argument conversion cases

### LINKED ISSUE #119062: JIT: jitstress-random test failure with Assertion failed 'callArg->AbiInfo.CountRegsAndStackSlots() == 2' during 'Lowering nodeinfo'
Example pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1130703&view=results
Example console log: https://helixr18s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-26f9730fb04b4c1985/Directed_3/1/console.cc33dabb.log?helixlogtype=result

```
export DOTNET_TieredCompilation=0
export DOTNET_DbgEnableMiniDump=1
export DOTNET_EnableCrashReport=1
export DOTNET_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export DOTNET_JitStress=ea
...
BEGIN EXECUTION
/root/helix/work/correlation/watchdog 119 /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true Directed_3.dll ''
...
19:17:23.372 Running test: JIT/Directed/StructABI/structreturn/structreturn.dll

Assert failure(PID 33 [0x00000021], Thread: 33 [0x0021]): Assertion failed 'callArg->AbiInfo.CountRegsAndStackSlots() == 2' in 'TestUnsafeCasts:TestCastSameSize()' during 'Lowering nodeinfo' (IL size 157; hash 0x9c854c38; FullOpts)

    File: /__w/1/s/src/coreclr/jit/lower.cpp:1565
    Image: /root/helix/work/correlation/corerun
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by jakobbotsch**
On 32-bit platforms we can end up with long operands to a function taking a parameter in a double register. We would try to create bitcasts for this case, which is not supported for 32 bit.

Generalize a condition to properly detect this unsupported case.

Fix #119062

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS 

[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1138545&view=ms.vss-build-web.run-extensions-tab)

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -1562,8 +1562,6 @@ void Lowering::LowerArg(GenTreeCall* call, CallArg* callArg)
 
     if (varTypeIsLong(arg))
     {
-        assert(callArg->AbiInfo.CountRegsAndStackSlots() == 2);
```
Comment (jakobbotsch) [inline src/coreclr/jit/lower.cpp:1565]: The code below now knows how to handle `FIELD_LIST`s that are incompatible with the registers, so the assert is not necessary.

**Review by AndyAyersMS — APPROVED** [review]
