### PR TITLE
[Tests][UserEvents] Improve test timing and re-enable tests

### LINKED ISSUE #123442: [Test][UserEvents] Trace file does not contain expected events
### Description

UserEvents tests introduced in https://github.com/dotnet/runtime/pull/122430 are flakey and sometimes don't capture the expected .NET events. 

The error will ultimately contains `Trace file <trace_file> does not contain expected events.` with a preceding message specific to the scenario. (e.g. `The trace did not contain two WorkStart events with ActivityIds for RequestA and RequestB.` for testing ActivityIDs)

The test output looks like
```
Tracee process started with PID: 29998
Waiting for tracee process to exit...
Stopping record-trace with SIGINT.
Waiting for record-trace to exit...
[record-trace] Recording started.  Press CTRL+C to stop.
[record-trace] Recording stopped.
[record-trace] Resolving symbols.
[record-trace] Finished recording trace.
[record-trace] Trace written to /datadisks/disk1/work/AABC0977/t/tmpDnj9kx.nettrace
Uploading trace file to Helix work item directory: /datadisks/disk1/work/AABC0977/w/AF9D0976/uploads/activity.nettrace
Expected: 100
Actual: 255
```

### Reproduction Steps

https://github.com/dotnet/runtime/tree/main/src/tests/tracing/userevents

### Expected behavior

The nettrace contains the expected events

### Actual behavior

Missing events

### Regression?

No, this feature was introduced in .NET 10 and these are the first functional tests added.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mdh1418**
Fix flaky userevents tracing tests

Fixes #123442

## Root Causes

Investigation identified three independent causes of test flakiness:

### 1. Race between tracee event generation and record-trace setup

record-trace must discover the tracee process, send an EventPipe IPC command (which the runtime processes to register user_events tracepoints), and enable its PerfSession (ring buffer collection) before the tracee writes any events. The tracee has no callback to know when these steps are complete. With the original 200ms delay, the tracee could write events before PerfSession was enabled — a race observed when the tracee is discovered during record-trace's `/proc` scan. Events written in this window are silently lost.

Empirically measured on a 2-core system, which CI runs on and hit the failures more frequently than my local WSL2 environment, both tracepoint registration and PerfSession enable completed within 229ms (p99). The delay is increased to 700ms, providing a ~3x safety margin.

### 2. Cross-process event contamination

record-trace captures events from all .NET processes on the machine, not just the tracee. On CI machines running multiple .NET processes, the trace validators could match events from unrelated processes or fail to find the tracee's events among the noise.

Each validator now receives the tracee's PID and filters events by `ProcessID`, ignoring events from other processes.

### 3. Permission errors cleaning up diagnostic ports

`EnsureCleanDiagnosticPorts` deletes zombie diagnostic IPC sockets in `/tmp`, but on shared CI machines these sockets may be owned by other users. `UnauthorizedAccessException` and `IOException` during deletion would crash the test before it even started.

These exceptions are now caught and logged, allowing the test to proceed.

## Additional Improvements

- **Output ordering**: Subprocess stderr is routed to stdout with `[stdout]`/`[stderr]` tags so test output appears in chronological order, making timing-sensitive failures easier to diagnose.
- **record-trace version**: Bumped from 0.1.33304 to 0.1.33421 to pick up fixes for EventPipe IPC handling.

## Validation

Stress-tested with 500 consecutive runs (100 per scenario) on a 2-core system — **500/500 passed** (0% failure rate, up from ~65% with the original code).

### CODE REVIEW

File: src/tests/tracing/userevents/common/UserEventsTestRunner.cs [hunk 1]
```diff
@@ -18,7 +18,18 @@ public class UserEventsTestRunner
         private const int SIGINT = 2;
         private const int DefaultTraceeExitTimeoutMs = 5000;
         private const int DefaultRecordTraceExitTimeoutMs = 20000;
-        private const int DefaultTraceeDelayToSetupTracepointsMs = 200;
+
+        // Delay before the tracee performs its event-generating action. record-trace
+        // must discover the process, send an EventPipe IPC command that the runtime
+        // processes to register user_events tracepoints, and enable its PerfSession
+        // (ring buffer collection). The tracee has no callback to know when these steps
+        // are complete, so this delay provides a sufficient window. Without it, events
```
Comment (noahfalk) [inline src/tests/tracing/userevents/common/UserEventsTestRunner.cs]: What about EventSource.IsEnabled() or EventSource.OnEventCommand? IsEnabled should toggle from false->true and OnEventCommand should be invoked when the runtime receives that IPC command. As long as record-trace enables the ring buffer/subscribes to the events prior to the IPC command and the runtime updates its internal filtering state prior to updating the C# visible state I'd expect an event emitted immediately after this to be captured. I'm pretty sure the runtime does use that ordering but I'm not sure about record-trace.

If that is reliable ideally we don't need a delay.

File: src/tests/tracing/userevents/common/UserEventsTestRunner.cs [hunk 2]
```diff
@@ -276,8 +283,19 @@ private static void EnsureCleanDiagnosticPorts(string diagnosticPortDir)
                 {
                     foreach (FileInfo fi in ipc)
                     {
-                        Console.WriteLine($"Deleting zombie diagnostic port: {fi.FullName}");
-                        fi.Delete();
+                        try
+                        {
+                            Console.WriteLine($"Deleting zombie diagnostic port: {fi.FullName}");
```
Comment (noahfalk) [inline src/tests/tracing/userevents/common/UserEventsTestRunner.cs:308]: Do you know why we need to do this at all? In theory the runtime should do a good enough job cleaning up after itself rather than relying on external tools to do it. I don't think we need to address it in this PR but I suspect either the test is doing needless work or the test is actively masking a runtime issue.

Comment (mdh1418) [reply src/tests/tracing/userevents/common/UserEventsTestRunner.cs:308]: It was initially added in part because the other EventPipe tests had EnsureCleanEnvironment ([diagnostics](https://github.com/dotnet/diagnostics/blob/b51d0c192667533233cf0a7027931c3643898c64/src/tests/eventpipe/common/IpcTraceTest.cs#L354) and [runtime mirror](https://github.com/dotnet/runtime/blob/b6a3e784f0bb418fd2fa7f6497f1b642210c3ea4/src/tests/tracing/eventpipe/common/IpcTraceTest.cs#L345)).

I also think I've observed a buildup of diagnostic ports on my WSL2 instance over time, so I think there are some instances where the diagnostic ports aren't cleaned up even though we have a cleanup callback https://github.com/dotnet/runtime/blob/b6a3e784f0bb418fd2fa7f6497f1b642210c3ea4/src/coreclr/vm/ceemain.cpp#L579 invoked via PROCNotifyProcessShutdown.

Also just listing `dotnet-diagnostic-*`, there are some where the process no longer exists.
```bash
root@CPC-mihw-6KMZDM:/home/mihw/repo/runtime# ls /tmp/dotnet-diagnostic-*
/tmp/dotnet-diagnostic-74529-38487011-socket  /tmp/dotnet-diagnostic-74936-38493991-socket  /tmp/dotnet-diagnostic-75224-38498766-socket
root@CPC-mihw-6KMZDM:/home/mihw/repo/runtime# ps -al
F S   UID   PID  PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
4 S  1000   446   367  0  80   0 -  2133 do_wai pts/1    00:00:00 bash
0 S  1000   554   446  0  80   0 -  2105 wait_w pts/1    00:00:00 ssh-add
4 S     0  1490  1422  0  80   0 -  2166 do_sel pts/5    00:00:00 bash
0 S  1000 74382 74320 10  80   0 - 6837391 do_epo pts/0  00:21:13 MainThread
0 S  1000 74674 74673  0  80   0 -   700 do_wai pts/3    00:00:00 sh
0 S  1000 74758 74674  0  80   0 -   700 do_wai pts/3    00:00:00 sh
0 S  1000 74762 74758  0  80   0 - 2975639 do_epo pts/3  00:00:33 node
0 S  1000 74811 74762  0  80   0 - 332778 do_epo pts/3   00:00:18 node
0 S  1000 74833 74762  4  80   0 - 13927108 do_epo pts/3 00:09:57 node
0 S  1000 74849 74762  0  80   0 - 321363 do_epo pts/3   00:00:34 node
0 S  1000 74887 74833  0  80   0 - 255074 do_epo pts/3   00:00:01 node
0 S  1000 79859 79748  3  80   0 - 6926264 do_epo pts/12 00:06:57 MainThread
0 S  1000 83414 74762  0  80   0 - 332523 do_epo pts/3   00:00:08 node
0 S  1000 83443 74762  3  80   0 - 13728458 do_epo pts/3 00:06:30 node
0 S  1000 83534 83443  0  80   0 - 254355 do_epo pts/3   00:00:01 node
0 S  1000 84937 74833  0  80   0 - 254099 do_epo pts/3   00:00:00 node
4 S     0 85041 74979  0  80   0 -  4184 do_sys pts/13   00:00:00 sudo
4 S     0 85043 85042  0  80   0 -  1950 do_wai pts/17   00:00:00 bash
4 R     0 85148 85043  0  80   0 -  2795 -      pts/17   00:00:00 ps
```

Comment (jkotas) [reply src/tests/tracing/userevents/common/UserEventsTestRunner.cs:308]: > the diagnostic ports aren't cleaned up even though we have a cleanup callback [https://github.com/dotnet/runtime/blob/b6a3e784f0bb418fd2fa7f6497f1b642210c3ea4/src/coreclr/vm/ceemain.cpp#L579](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fblob%2Fb6a3e784f0bb418fd2fa7f6497f1b642210c3ea4%2Fsrc%2Fcoreclr%2Fvm%2Fceemain.cpp%23L579&data=05%7C02%7Cjkotas%40microsoft.com%7Ca7151b30f0044491c3a808de7635511b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C639078168542365580%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=uE7VlUVBelTMiw5eSjbNhVUSCY%2FMdhbu621661jBH1o%3D&reserved=0) invoked via PROCNotifyProcessShutdown.

This cleanup won't run when the process crashes badly or gets killed. I think this build-up is by design, especially on a machine used for the runtime development.

File: src/tests/tracing/userevents/common/UserEventsTestRunner.cs (hunk 1 above)
Comment (mdh1418) [reply src/tests/tracing/userevents/common/UserEventsTestRunner.cs]: Ironically, CLI suggested a EventCommandExecuted callback during POC. It only suggested it would only work for the ManagedEvent tests and only had a simple delay for the basic test. I didn't like that split and didn't realize the native event's event source would also get that callback hit, so I went with a single delay.

I do like the "eventPipe session is enabled" gating on the event generating action, and opted for the public facing EventCommandExecuted callback since that can also apply to the internal NativeRuntimeEventSource, rather than needing to update each test scenario's EventSource.

I think we still need a delay to handle when the tracee starts up so quickly it gets detected in record-trace's "pre-existing processes" `/proc` scan, for which the IPC command would be sent before record-trace's ring buffers are ready to record events. That was how the single event emitting test custommetadata flakily failed.

**Review by noahfalk — APPROVED** [review]
