### PR TITLE
[Bug Fixed] Modify the exception handling when reading the status of /proc/ (Issue: #47566)

### LINKED ISSUE #47566: [Linux/ARM] Access permission issue for System.Diagnostics.Process.GetProcessesByName()/GetProcesses()
### Description
I ran the test code in an environment with smack applied(Tizen, 32-bit).
I called two method(```System.Diagnostics.Process.GetProcessesByName()```, ```System.Diagnostics.Process.GetProcesses()```).

* Sample code:
```
static void Main(string[] args)
{
    string name = System.Diagnostics.Process.GetCurrentProcess().ProcessName;
    Console.WriteLine(System.Diagnostics.Process.GetProcessesByName(name));
}
```

It seems to be a problem that occurs when the test app accesses the processes under ```/proc/```.
The following exception occurred. 
* Exception:
```
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/proc/1/stat' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at Interop.procfs.TryReadFile(String filePath, ReusableTextReader reusableReader, String& fileContents)
   at Interop.procfs.TryParseStatFile(String statFilePath, ParsedStat& result, ReusableTextReader reusableReader)
   at System.Diagnostics.Process.GetProcessesByName(String processName, String machineName)
   at System.Diagnostics.Process.GetProcessesByName(String processName)
   at ProcessTest.Program.Main(String[] args)
```

* Analysis:
```at Interop.procfs.TryReadFile(String filePath, ReusableTextReader reusableReader, String& fileContents)```
When I checked the part where the exception occurred, only ```IOException``` is handling the exception.
However, ```UnauthorizedAccessException``` is occurring when calling the ```FileStrem``` method.
Also, the document of the associated API is not mentioned.

So I think not only ```IOException``` but also ```UnauthorizedAccessException``` should be added.

### PR DESCRIPTION
**Pull request by JongHeonChoi**
Fixed a catch block that throws an exception when reading the state under ```/proc/```.

Fixes: #47566

### CODE REVIEW

File: src/libraries/Common/src/Interop/Linux/procfs/Interop.ProcFsStat.TryReadStatusFile.cs [hunk 1]
```diff
@@ -181,7 +181,7 @@ private static bool TryReadFile(string path, [NotNullWhen(true)] out string? con
                     }
                 }
             }
-            catch (IOException)
+            catch (IOException ex) when (ex is IOException || ex.InnerException is IOException)
```
Comment (danmosemsft) [inline src/libraries/Common/src/Interop/Linux/procfs/Interop.ProcFsStat.TryReadStatusFile.cs:184]:
```suggestion
            catch (Exception ex) when (ex is IOException || ex.InnerException is IOException)
```

**Comment by danmosemsft** [comment]
@JongHeonChoi if you edit your top comment to have a line like 
Fixes #47566
 then when this PR is merged,  it will also close the issue

**Comment by JongHeonChoi** [comment]
> @JongHeonChoi if you edit your top comment to have a line like
> Fixes #47566
> then when this PR is merged, it will also close the issue

Done. :)

**Review by danmoseley — APPROVED** [review]
Thanks!

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @JongHeonChoi !
