### PR TITLE
[wasm][debugger] Fix pause on exception behavior

### LINKED ISSUE #58509: VM6:1 Uncaught pause_on_uncaught exception in visual studio 2022 version 6.0.0 Preview 7
Hello recently I am working on new blazor webassembly project on visual studio 2022
version 6.0.0 Preview 7.Whenever I am creating any new blazor web assembly project then it is throwing an exception (Uncaught pause_on_uncaught) and I tried to make project in two different system and still the same exception is coming again and again .I tried the following references also:
1.using dotnet new blazorwasm -o WebApplication1 -ho (or dotnet new blazorwasm -au Individual -ho -o WebApplication1 for the case with authentication) generates a functional app.
2.the template generated in VS2019 with .Net 5 and adapted to .Net 6 preview 7 doesn't works fine.
 but it is also not helping, the same exception is coming again and again.
 
image

### PR DESCRIPTION
**Pull request by thaystg**
- The initial status of Pause On Exception is correctly sent to BrowserDebugProxy when the debugging is started from VS. So we don't need the hacky to discover the initial status. And we will not print the message described in the issue below anymore.

- When we debugging from chrome this is still useful, but I couldn't hide the message printed on console. 

- Added more tests when throwing an Exception and not a CustomException as we were testing in the unit test before.

Fixes https://github.com/dotnet/runtime/issues/58509#issuecomment-912058745

@lewing I would like to backport to preview 2, do you think that makes sense?

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 1]
```diff
@@ -442,23 +442,20 @@ protected override async Task<bool> AcceptCommand(MessageId id, string method, J
...
-                            {
-                                case "all":
-                                    context.PauseOnCaught = true;
-                                    context.PauseOnUncaught = true;
-                                    break;
-                                case "uncaught":
-                                    context.PauseOnUncaught = true;
-                                    break;
-                            }
+                            case "all":
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:447]: Maybe use switch expression here?
```csharp
                        context.PauseOnExceptions = state switch
                        {
                            "all"      => PauseOnExceptionsKind.All,
                            "uncaught" => PauseOnExceptionsKind.Uncaught,
                            "none"     => PauseOnExceptionsKind.None,
                            _          => // error?
                        };
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 2]
```diff
@@ -442,23 +442,20 @@ protected override async Task<bool> AcceptCommand(MessageId id, string method, J
...
+                                context.PauseOnExceptions = PauseOnExceptionsKind.Uncaught;
+                                break;
+                            case "none":
+                                context.PauseOnExceptions = PauseOnExceptionsKind.None;
+                                break;
                         }
-                        else
-                            await SdbHelper.EnableExceptions(id, state, token);
+                        if (context.IsRuntimeReady)
+                            await SdbHelper.EnableExceptions(id, context.PauseOnExceptions, token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:458]: Is the reason for not using the same checks as line 1228 (`if (context.PauseOnExceptions != PauseOnExceptionsKind.None && context.PauseOnExceptions != PauseOnExceptionsKind.Unset)`):

- it shouldn't Unset, if we handle the default case in the switch above
- and if it's None, then we do want to send that to *set* the state to that?

But in line 1228's case:
- if it's None, then we need to send it because that's the default? nit: It might useful to send in case of None anyway, just to "enforce the default".

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 3]
```diff
@@ -1392,8 +1388,19 @@ private async Task AttachToTarget(SessionId sessionId, CancellationToken token)
             // see https://github.com/mono/mono/issues/19549 for background
             if (sessions.Add(sessionId))
             {
-                string checkUncaughtExceptions = $"throw \"{sPauseOnUncaught}\";";
-                string checkCaughtExceptions = $"try {{throw \"{sPauseOnCaught}\";}} catch {{}}";
+                string checkUncaughtExceptions = "";
+                string checkCaughtExceptions = "";
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1392]: nit:
```suggestion
                string checkUncaughtExceptions = string.Empty;
                string checkCaughtExceptions = string.Empty;
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 4]
```diff
@@ -2210,7 +2210,7 @@ public async Task<JArray> GetArrayValues(SessionId sessionId, int arrayId, Cance
             }
             return array;
         }
-        public async Task<bool> EnableExceptions(SessionId sessionId, string state, CancellationToken token)
+        public async Task<bool> EnableExceptions(SessionId sessionId, PauseOnExceptionsKind state, CancellationToken token)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:2213]: nit: might be useful to add a check for `Unset` here anyway, to guard against accidentally calling this with `Unset`, and log a debug message?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 5]
```diff
@@ -1392,8 +1388,19 @@ private async Task AttachToTarget(SessionId sessionId, CancellationToken token)
...
+
+                //we only need this check if it's a non-vs debugging
+                if (sessionId == SessionId.Null)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1395]: How is this checking for non-vs debugging?
And does `SessionId.Null` represent a default context, which might have an entry in `contexts` dictionary?

**Review by radical — COMMENTED** [review]
Looking good. Just a few questions, and suggestions.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs (hunk 5 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1395]: As I could see by debugging, when I'm debugging from VS SessionId is not null, when I'm debugging from chrome SessionId is null.
Maybe @lewing knows how to explain better.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs (hunk 2 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:458]: In line 1228 we don't need to send PauseOnExceptionsKind.None because this is the default behavior on startup. 
If we receive from Debugger.setPauseOnExceptions and runtime is ready we maybe need to change the behavior to none if the behavior before wasn't none.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 4 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:2213]: Done.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs (hunk 2 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:458]: I don't think we need to send none when the VM is started only to "enforce the default".

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs (hunk 1 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs]: done, and I set the default case to unset, I don't think we need to log an error. According to the documentation this should not happen: https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setPauseOnExceptions

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs (hunk 5 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1391]: I think, the non-null sessionId means that it is a "flat access".
IIUC, chrome devtools will move to it too, so this might not be a good test. I'll defer to @lewing .

**Review by radical — COMMENTED** [review]
Except that question about the sessionId, LGTM!

**Review by lewing — APPROVED** [review]
