### PR TITLE
Unify corerun test runner

### LINKED ISSUE #5116: Missing -d and -v options on Linux for corerun
It seems that the -d and -v options (available on Windows) are missing on Linux. Shouldn't they be there as well to ensure consistency between platforms?

### LINKED ISSUE #7509: corerun needs better error messages
Often I see
```
coreclr_initialize failed - status: 0x80131534
```
or similar. This is very unfriendly. Corerun should provide better root cause error messages so you're not required to fire up a debugger to track down every configuration "mistake".

### LINKED ISSUE #35814: Make corerun easier to debug in case of initialization failure
In my PR https://github.com/dotnet/runtime/pull/35684, a couple of things are identified that we could do to make `corerun` easier to work with in case the runtime fails to initialize.

We can consider them in the future.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Rewrite `corerun` so that the same source works for all platforms instead of having a Windows and non-Windows implementation.

Fixes https://github.com/dotnet/runtime/issues/35814
Fixes https://github.com/dotnet/runtime/issues/7509
Fixes https://github.com/dotnet/runtime/issues/5116 - 'wait for debugger' attach is supported on macOS and systems with `procfs`.

The `-v` verbose flag has been removed since it didn't offer a lot of insight. New logging has been added instead. `corerun` now dumps out all the details passed to CoreCLR when it fails to initialize or if the execute call fails. See below for an example of output.

```
BEGIN: coreclr_execute_assembly failed - Error: 0xffffffff
Exe path: D:\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe
Properties:
    TRUSTED_PLATFORM_ASSEMBLIES = <The computed TPA is displayed. It has been removed here for brevity.>
    APP_PATHS = D:\runtime\artifacts\tests\coreclr\windows.x64.Debug\GC\API\WeakReference\multipleWRs_1\
    APP_NI_PATHS = D:\runtime\artifacts\tests\coreclr\windows.x64.Debug\GC\API\WeakReference\multipleWRs_1\NI\;D:\runtime\artifacts\tests\coreclr\windows.x64.Debug\GC\API\WeakReference\multipleWRs_1\
    NATIVE_DLL_SEARCH_DIRECTORIES = D:\runtime\artifacts\tests\coreclr\windows.x64.Debug\GC\API\WeakReference\multipleWRs_1\;D:\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\;
    System.GC.Server = false
    System.GC.Concurrent = true
    System.Globalization.Invariant = false
Managed assembly: D:\runtime\artifacts\tests\coreclr\windows.x64.Debug\GC\API\WeakReference\multipleWRs_1\multipleWRs_1.dll
Arguments (2): 10000 track
END: coreclr_execute_assembly failed - Error: 0xffffffff
```

### CODE REVIEW

**Comment by danmoseley** [comment]
It doesn't already?

**Comment by AaronRobinsonMSFT** [comment]
>It doesn't already?

@danmoseley It does, but there are two implementations - corerun and unixcorerun. This PR combines them.

File: src/coreclr/hosts/corerun/corerun.cpp [hunk 1]
```diff
@@ -551,308 +329,297 @@ HRESULT InitializeHost(
...
-        } else if ( stringsEqual(arg, W("/d")) || stringsEqual(arg, W("-d")) ) {
-                waitForDebugger = true;
-                return true;
-        } else if ( stringsEqual(arg, W("/?")) || stringsEqual(arg, W("-?")) || stringsEqual(arg, W("-h")) || stringsEqual(arg, W("--help")) ) {
-            helpRequested = true;
-            return true;
-        } else {
-            return false;
+#define THROW_IF_FALSE(stmt) if (!(stmt)) throw W(#stmt);
+static int self_test()
```
Comment (vitek-karas) [inline src/coreclr/hosts/corerun/corerun.cpp:565]: Could you add a comment what is the purpose of this? It's not clear from the code (at least to me) and you didn't document it in the usage.

Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/corerun/corerun.cpp:565]: This is to have a place for some testing if needed. I can remove it if that doesn't make sense. Opinions welcome. If it does make sense I will comment.

Comment (vitek-karas) [reply src/coreclr/hosts/corerun/corerun.cpp:566]: I don't mind it - I just feel the "self-test" is not good enough description 😉

**Review by vitek-karas — APPROVED** [review]
LGTM, but somebody with build system experience should probably take a second look

**Comment by AaronRobinsonMSFT** [comment]
Anyone else have feedback here?

File: src/coreclr/hosts/corerun/corerun.cpp [hunk 2]
```diff
@@ -551,308 +329,298 @@ HRESULT InitializeHost(
     //
     // NATIVE_DLL_SEARCH_DIRECTORIES
     // - The list of paths that will be probed for native DLLs called by PInvoke
-    //
-    const char* property_keys[] = {
+    const char* propertyKeys[] =
+    {
         "TRUSTED_PLATFORM_ASSEMBLIES",
         "APP_PATHS",
         "APP_NI_PATHS",
```
Comment (jkotas) [inline src/coreclr/hosts/corerun/corerun.cpp:336]: I think `APP_NI_PATHS` can be deleted. Nothing should depend on it anymore.

File: src/coreclr/hosts/corerun/corerun.cpp [hunk 3]
```diff
@@ -1,544 +1,322 @@
...
 
-    // Initialize host.
+    // Construct CoreCLR properties.
+    pal::string_utf8_t tpa_list_utf8 = pal::convert_to_utf8(std::move(tpa_list));
+    pal::string_utf8_t app_path_utf8 = pal::convert_to_utf8(std::move(app_path));
+    pal::string_utf8_t app_path_ni_utf8 = pal::convert_to_utf8(std::move(app_path_ni));
+    pal::string_utf8_t native_search_dirs_utf8 = pal::convert_to_utf8(native_search_dirs.str());
+    const char* enable_server_gc = get_envvar_as_boolean(envvar::serverGc);
+    const char* enable_concurrent_gc = get_envvar_as_boolean(envvar::concurrentGc, true /* default */);
+    const char* enable_globalization_invariant = get_envvar_as_boolean(envvar::globalizationInvariant);
```
Comment (jkotas) [inline src/coreclr/hosts/corerun/corerun.cpp:317]: We have `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` environment variable that is read and respected by the runtime. I do not think we need another one here.

File: src/coreclr/hosts/corerun/corerun.cpp (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/corerun/corerun.cpp:336]: You would think that, but unfortunately we do have tests that rely on it. That is something I was going to cleanup this is in.

File: src/coreclr/hosts/corerun/corerun.cpp (hunk 3 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/corerun/corerun.cpp:317]: This was folded in from the unix variant. I will see what sets `CORECLR_GLOBAL_INVARIANT` and convert it to that.

File: src/coreclr/hosts/corerun/corerun.cpp [hunk 4]
```diff
@@ -1,544 +1,322 @@
...
+    const char_t* mockHostPolicy = W("MOCK_HOSTPOLICY");
 
-                // Search for the last backslash and terminate it there to keep just the directory path with trailing slash
-                SString::Iterator lastBackslash = m_coreCLRDirectoryPath.End();
-                m_coreCLRDirectoryPath.FindBack(lastBackslash, W('\\'));
-                m_coreCLRDirectoryPath.Truncate(lastBackslash + 1);
+    // Name of the environment variable controlling server GC.
+    // If set to 1, server GC is enabled on startup. If 0, server GC is
+    // disabled. Server GC is off by default.
+    const char_t* serverGc = W("COMPlus_gcServer");
```
Comment (jkotas) [inline src/coreclr/hosts/corerun/corerun.cpp:64]: I believe `COMPlus_gcServer`  and `COMPlus_gcConcurrent` are also read and respected by the runtime. No sure why we have it duplicated here.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/hosts/CMakeLists.txt [hunk 5]
```diff
@@ -1,9 +1,9 @@
 include_directories(inc)
 
 if(CLR_CMAKE_HOST_WIN32)
-  add_subdirectory(corerun)
   add_subdirectory(coreshim)
 else(CLR_CMAKE_HOST_WIN32)
   add_definitions(-D_FILE_OFFSET_BITS=64)
-  add_subdirectory(unixcorerun)
```
Comment (jkotas) [inline src/coreclr/hosts/CMakeLists.txt:8]: https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#create-a-host-using-coreclrhosth has a link to this directory. The link should be deleted or updated.

File: src/coreclr/hosts/corerun/corerun.cpp (hunk 4 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/corerun/corerun.cpp:64]: I believe because of https://github.com/dotnet/runtime/blob/61c69d157a008bcee89adc234f0b2822087fc253/src/coreclr/dlls/mscoree/unixinterface.cpp#L95-L115

File: src/coreclr/hosts/CMakeLists.txt (hunk 5 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/CMakeLists.txt:8]: Will update when merged.

File: src/coreclr/hosts/corerun/corerun.cpp (hunk 3 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/corerun/corerun.cpp:317]: This looks that a no op. I don't see it consumed anywhere. Will remove.

File: src/coreclr/hosts/corerun/corerun.cpp (hunk 4 above)
Comment (jkotas) [reply src/coreclr/hosts/corerun/corerun.cpp:64]: If `COMPlus_gcServer` is not read by the runtime, it would be nice to delete it from `src\coreclr\inc\clrconfigvalues.h`

Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/corerun/corerun.cpp:64]: Okay. I am going to remove the globalization invariant first and then merge this in. These other values are going to require more inspection.

File: src/coreclr/hosts/CMakeLists.txt (hunk 5 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/CMakeLists.txt:8]: https://github.com/dotnet/docs/pull/23344

File: src/coreclr/hosts/corerun/corerun.cpp (hunk 4 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/corerun/corerun.cpp:64]: @jkotas Both the `COMPlus_gcServer` and `COMPlus_gcConcurrent` are read by the runtime. It is done first in the call to `Configuration::GetKnobBooleanValue()`. Do you have a preference here? I think I am of the opinion that special casing these in `corerun` is just adding unnecessary complexity. I vote to remove them. @vitek-karas and @janvorli for their opinions as well.

Comment (jkotas) [reply src/coreclr/hosts/corerun/corerun.cpp:64]: > I think I am of the opinion that special casing these in corerun is just adding unnecessary complexity. I vote to remove them

I agree that we should remove the special casing in corerun.

Comment (AaronRobinsonMSFT) [reply src/coreclr/hosts/corerun/corerun.cpp:64]: See https://github.com/dotnet/runtime/pull/49950
