### PR TITLE
Fix STLUR for 0 imm

### LINKED ISSUE #105906: osx-arm64 NativeAOT Debug build failing with encoding_found assert
Building commit a4fe68fcb3233b8b229444557d38c7565938de05 on ARM64 macOS with
```
./build.sh clr.aot+libs
./src/tests/build.sh -nativeaot -tree nativeaot /p:LibrariesConfiguration=Debug
```

results in
```
    ILC: /Users/filipnavara/Projects/runtime/src/coreclr/jit/emitarm64.cpp:2286
    ILC: Assertion failed 'encoding_found' in 'TimerTest:Run():int' during 'Emit code' (IL size 392; hash 0x309f3e6f; MinOpts)
    
    /var/folders/5z/h5l1chy164x4xqrg1hgkml840000gn/T/MSBuildTempfilipnavara/tmp4f965f61a935468987e7a60905a8c9eb.exec.cmd: line 2: 35532 Trace/BPT trap: 5       "/Users/filipnavara/Projects/runtime/artifacts/bin/coreclr/osx.arm64.Debug/ilc-published/ilc" @"/Users/filipnavara/Projects/runtime/artifacts/tests/coreclr/obj/osx.arm64.Debug/Managed/nativeaot/SmokeTests/UnitTests/UnitTests/native/UnitTests.ilc.rsp"
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/105906

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @dotnet/jit-contrib this unblocks Debug build for NativeAOT on macOS (or any other RCPC2 arm64 hardware).

Some code creates `LEA(addr, 0)` not sure if we should create such unscaled LEAs with 0 offset and zero index in the first place, but looks like it's valid (in this case the 0 was a field sequence ICON) - this led to `stlur` with 0 offset. stlur (and it load counterpart - ldapur) always use `IF_LS_2C` encoding, so we shouldn't use the same path as for other loads/stores.

Generally, we emit `ldapur`/`stlur` only for volatile loads/stores with LEA and a small offset (no index, no scale) since these instructions don't support any other addressing mode.

**Comment by EgorBo** [comment]
PTAL @amanasifkhalid @TIHan as emitter experts

File: src/coreclr/jit/emitarm64.cpp [hunk 1]
```diff
@@ -5633,9 +5631,7 @@ void emitter::emitIns_R_R_I(instruction     ins,
             break;
 
         case INS_ldurh:
-        case INS_ldapurh:
         case INS_sturh:
```
Comment (amanasifkhalid) [inline src/coreclr/jit/emitarm64.cpp:5634]: While you're here, could you please move these cases up to `INS_ldurb/INS_sturb` since they have the same behavior?

**Review by amanasifkhalid — APPROVED** [review]
I don't know about "emitter expert," but this LGTM.

> PS: I wasn't able to come up with a test which creates LEA(base + 0) tree, so leaving Debug repo build as a test.

It might be a good idea to add tests for this pattern to `codegenarm64test.cpp`. You can then run those tests with `DOTNET_JitEmitUnitTests="*"` and `DOTNET_JitEmitUnitTestsSections="general"`, and just replay a single method with SPMI.

Thanks!

File: src/coreclr/jit/emitarm64.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/emitarm64.cpp]: Addressed. They indeed have the same issue but we never use them 🙂
