### PR TITLE
Do not embed result type in VN for scalar hw intrinsics

### LINKED ISSUE #69551: Assertion failed 'preciseVarTypeMap[type] != TYP_UNDEF' when dumping all functions
### Description

Whilst debugging coreclr using a simple example application I wanted to dump the IR for every function. I wanted to do this to see in which functions an optimised had kicked in.

### Reproduction Steps

Arm64 Linux (not tested elsewhere).
Using a simple example test app:

`COMPlus_JitDump="*" COMPlus_TieredCompilation=0 ./bin/release/net7.0/linux-arm64/publish/corerun bin/release/net7.0/linux-arm64/example.dll`

The exact contents of example does not matter - this error occurs before the runtime gets to example.dll

### Expected behavior

The IR dumps are printed for every function executed.

### Actual behavior

```
***** BB29, STMT00041(before)
N010 (  9,  9) [000470] -A------R--                         *  ASG       int
N009 (  1,  1) [000469] D------N---                         +--*  LCL_VAR   int    V36 tmp12        d:3
N008 (  9,  9) [000207] -----------                         \--*  ADD       int
N001 (  1,  1) [000200] C----------                            +--*  LCL_VAR   int    V03 loc0         u:7 (last use)
N007 (  7,  7) [000206] -----------                            \--*  NOP       int
N006 (  7,  7) [000387] -----------                               \--*  RSH       int
N004 (  5,  4) [000425] -----------                                  +--*  HWINTRINSIC int     LeadingZeroCount
N003 (  4,  3) [000424] -----------                                  |  \--*  HWINTRINSIC long    ReverseElementBits
N002 (  3,  2) [000383] -----------                                  |     \--*  LCL_VAR   long   V33 tmp9         u:1 (last use)
N005 (  1,  2) [000386] -----------                                  \--*  CNS_INT   int    3

N001 [000200]   LCL_VAR   V03 loc0         u:7 (last use) => $1ac {$30a, int <- long}
N002 [000383]   LCL_VAR   V33 tmp9         u:1 (last use) => <l:$2d7 {HWI_Vector128_ToScalar($483, $3c8)}, c:$2d8 {HWI_Vector128_ToScalar($484, $3c8)}>
    simdTypeVN is $3c9 {
Assert failure(PID 54654 [0x0000d57e], Thread: 54654 [0xd57e]): Assertion failed 'preciseVarTypeMap[type] != TYP_UNDEF' in 'System.SpanHelpers:IndexOf(byref,ushort,int):int' during 'Do value numbering' (IL size 549; hash 0x576e6ccc; FullOpts)

    File: /home/alahay01/dotnet/runtime/src/coreclr/jit/ee_il_dll.hpp Line: 288
    Image: /home/alahay01/dotnet/conditional/bin/release/net7.0/linux-arm64/publish/corerun

[1]    54654 abort      COMPlus_JitDump="*" COMPlus_TieredCompilation=0
```

Full list of functions in the dump at the point of the error:
****** START compiling System.Runtime.CompilerServices.CastHelpers:StelemRef(System.Array,int,System.Object) (MethodHash=1b5e9e9c)
****** START compiling System.Runtime.CompilerServices.CastHelpers:LdelemaRef(System.Array,int,long):byref (MethodHash=d1234a96)
****** START compiling System.SpanHelpers:IndexOf(byref,ushort,int):int (MethodHash=576e6ccc)

### Regression?

Don't know.

### Known Workarounds

Comment out the assert on line 288 of src/coreclr/jit/ee_il_dll.hpp

    assert(preciseVarTypeMap[type] != TYP_UNDEF);

Which this done, everything dumps ok.

### Configuration

Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-126-generic aarch64)

Recent HEAD of dotnet repo
6ca8c9bc0c4 2022-05-05.. Mukund Raghav.. Fixed the yp_spin_count_unit to be a factor of the original_spin_count_unit rather than a continually increasing value (#68879)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by kunalspathak**
For scalar hw intrinsics, we were creating `VNForSimdType` and it was manifesting in `vnDumpSimdType()`.

Fixes: https://github.com/dotnet/runtime/issues/69551

### CODE REVIEW

**Comment by kunalspathak** [comment]
@SingleAccretion , @dotnet/jit-contrib , @tannergooding

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/hwintrinsic.cpp [hunk 1]
```diff
@@ -210,10 +210,17 @@ CORINFO_CLASS_HANDLE Compiler::gtGetStructHandleForHWSIMD(var_types simdType, Co
 //
 /* static */ bool Compiler::vnEncodesResultTypeForHWIntrinsic(NamedIntrinsic hwIntrinsicID)
 {
+    // No extra type information is needed for scalar HW Intrinsic.
+    //
+    if (HWIntrinsicInfo::lookupCategory(hwIntrinsicID) == HW_Category_Scalar)
+    {
+        return false;
+    }
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsic.cpp:218]: We may also want a path for `HW_Category_Special` or maybe better check for:
```suggestion
    unsigned simdSize = 0;
    if (HWIntrinsicInfo::tryLookupSimdSize(hwIntrinsicID, &simdSize) && (simdSize == 0))
    {
        return false;
    }
```

All scalar intrinsics, regardless of category, should have a `simdSize == 0`. Likewise, all SIMD intrinsics should have a size of `8`, `16`, `32`, or `-1` (where `-1` implies the intrinsic supports multiple SIMD sizes and is not a scalar).

Comment (tannergooding) [reply src/coreclr/jit/hwintrinsic.cpp:218]: I think the current check is "accurate enough" today since the few "special" scalars tend to have all `INS_invalid` entries and are specially handled in codegen instead, but its probably better to be more explicit here.

There's also a consideration for the type encoding that certain special or helper intrinsics might specify `INS_invalid` and get specialized handling in lowering/codegen and so it might be important to have the type anyways. I'm unsure if there is any actual issue here or not, but its probably worth auditing at some point in the future.

Comment (kunalspathak) [reply src/coreclr/jit/hwintrinsic.cpp:218]: I agree, except that it doesn't set the `simdSize` if it was `-1`. So probably I should initialize `simdSize` to something like `100` or something and then see if became `0`. Wil fix it.

Comment (tannergooding) [reply src/coreclr/jit/hwintrinsic.cpp]: That's what the `tryLookupSimdSize` check was for. It should return `false` if `simdSize == -1` and so the second check (`simdSize == 0`) won't get hit.

Comment (kunalspathak) [reply src/coreclr/jit/hwintrinsic.cpp]: ah. was an oversight on my part.

**Review by tannergooding — APPROVED** [review]
