### PR TITLE
Conservative fix for struct stores in optRemoveRedundantZeroInits

### LINKED ISSUE #102577: `optRemoveRedundantZeroInits` doesn't know about some safe points
Looking at https://github.com/dotnet/runtime/pull/102531, I realized the logic will miss implicit safe points created by the somewhat recent block store lowering changes.

Reproduction:
```cs
object x = null;
byte* p = stackalloc byte[1000];
Random.Shared.NextBytes(new Span<byte>(p, 1000));
Problem(p, p, &x);

[MethodImpl(MethodImplOptions.NoInlining)]
static void Problem(void* pDst, void* pSrc, object* pObj)
{
    Unsafe.CopyBlock(pDst, pSrc, 1000);
    StructWithManyObjs x = default;
    if (pDst != null)
    {
        x.ObjFour = *pObj;
        *(StructWithManyObjs*)pDst = x;
    }
}

struct StructWithManyObjs
{
    public object ObjOne;
    public object ObjTwo;
    public object ObjThree;
    public object ObjFour;
    public object ObjFive;
}
```
`DOTNET_TieredCompilation=0`, `DOTNET_GCStress=0xC`, `DOTNET_ReadyToRun=0` (it looks like GC stress doesn't apply to precompiled code).

Expected result: nothing happens.
Actual result:
```scala
Assert failure(PID 17360 [0x000043d0], Thread: 14716 [0x397c]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")
```

Cause: `optRemoveRedundantZeroInits` doesn't know that the block copy may become a safe point. Zero-init and future calls introduced late suffer from the same problem.

The most robust fix for this would probably be to move `optRemoveRedundantZeroInits` later (make it part of late liveness, say).

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/102577

### CODE REVIEW

**Comment by EgorBo** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684703&view=ms.vss-build-web.run-extensions-tab) a bit conservative. Technically, in many cases such stores won't be converted to calls but any assumptions we can make here are too fragile. I propose we merge this as is and address dotnet/performance regressions if there will be any. We can consider introducing new flags to guarantee that a store won't be converted into a call etc.

cc @SingleAccretion @dotnet/jit-contrib

**Review by SingleAccretion — COMMENTED** [review]
A test needs to be added.

File: src/coreclr/jit/optimizer.cpp [hunk 1]
```diff
@@ -5921,6 +5921,14 @@ void Compiler::optRemoveRedundantZeroInits()
                     hasGCSafePoint = true;
                 }
 
+                if (tree->OperIs(GT_STORE_BLK))
+                {
+                    // Such stores might be converted into calls (with gc safe points) in Lower.
+                    // This is quite a conservative fix as it's hard to prove Lower won't do it
+                    // at this point.
+                    hasGCSafePoint = true;
+                }
```
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/jit/optimizer.cpp]: Addressed!

File: src/coreclr/jit/optimizer.cpp [hunk 2]
```diff
@@ -6079,7 +6068,7 @@ void Compiler::optRemoveRedundantZeroInits()
                             // insert a call to CORINFO_HELP_INIT_PINVOKE_FRAME but that is not a gc-safe point.
                             assert(emitter::emitNoGChelper(CORINFO_HELP_INIT_PINVOKE_FRAME));
 
-                            if (!lclDsc->HasGCPtr() || (!GetInterruptible() && !hasGCSafePoint))
+                            if (!lclDsc->HasGCPtr() || (!GetInterruptible() && !IsPotentialGCSafePoint(tree)))
```
Comment (VSadov) [inline src/coreclr/jit/optimizer.cpp:6071]: Should the `IsPotentialGCSafePoint` be called on all trees between prolog and the first use of the local and set `hasGCSafePoint` if there is an intervening safe point that may observe unassigned state?

**Comment by VSadov** [comment]
When I added the original conservative commit to https://github.com/dotnet/runtime/pull/102415, the GC stress results have improved considerably. There were still a few failures, but a lot less than before.  

It seems the original issue could be responsible for a noticeable fraction of random failures.

File: src/coreclr/jit/optimizer.cpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/jit/optimizer.cpp]: Oops, my bad, thanks for noticing! Fixed

**Comment by EgorBo** [comment]
@VSadov @jakobbotsch can I get a green approval then? I hope it will indeed reduce number of random gc hole asserts

File: src/coreclr/jit/compiler.hpp [hunk 3]
```diff
@@ -3190,6 +3190,41 @@ inline bool Compiler::IsValidLclAddr(unsigned lclNum, unsigned offset)
...
+            // assume that we have a safe point.
+            return true;
+        }
+    }
+
+    // TYP_STRUCT-typed stores might be converted into calls (with gc safe points) in Lower.
+    // This is quite a conservative fix as it's hard to prove Lower won't do it at this point.
+    if (tree->OperIsLocalStore())
+    {
+        return lvaTable[tree->AsLclVarCommon()->GetLclNum()].TypeGet() == TYP_STRUCT;
```
Comment (jakobbotsch) [inline src/coreclr/jit/compiler.hpp:3218]:
```suggestion
        return lvaGetDesc(tree->AsLclVarCommon())->TypeGet() == TYP_STRUCT;
```

Feel free to include it in a future change...

**Review by jakobbotsch — APPROVED** [review]

**Review by VSadov — APPROVED** [review]

File: src/coreclr/jit/compiler.hpp (hunk 3 above)
Comment (SingleAccretion) [reply src/coreclr/jit/compiler.hpp:3218]: I think this should check the tree type instead of the local's type, i. e. `return tree->TypeIs(TYP_STRUCT)`. One can have struct stores for primitive locals.

Comment (jakobbotsch) [reply src/coreclr/jit/compiler.hpp:3218]: Looks simpler so I'm all for it, but it seems unlikely those would end up lowered to calls.

Comment (EgorBo) [reply src/coreclr/jit/compiler.hpp]: Ok, changed
