### PR TITLE
JIT: fix issue in conditional escape analysis

### LINKED ISSUE #111922: System.Collections.Test: Assert failure '!CREATE_CHECK_STRING(bSmallObjectHeapPtr || bLargeObjectHeapPtr)'
Hit in `libraries-pgo`. [Example run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954772&view=results) ([console log](https://helixr18s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-112639-merge-58eaeb97d9d449aba4/System.Collections.Concurrent.Tests/1/console.0d43f6bb.log?skoid=8eda00af-b5ec-4be9-b69b-0919a2338892&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2025-02-18T08%3A36%3A48Z&ske=2025-02-18T09%3A36%3A48Z&sks=b&skv=2024-11-04&sv=2024-11-04&st=2025-02-18T08%3A36%3A48Z&se=2025-02-18T09%3A36%3A48Z&sr=c&sp=r&sig=n29%2BIh5iGerTmxoFVgiT6La5LQMbs7PLwtI2IR3%2FOhs%3D)). cc @dotnet/jit-contrib 

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.Collections.Test","!CREATE_CHECK_STRING(bSmallObjectHeapPtr || bLargeObjectHeapPtr)"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=954772
**Error message validated:** `[!CREATE_CHECK_STRING(bSmallObjectHeapPtr || bLargeObjectHeapPtr)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/18/2025 8:42:54 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 7/29/2025 1:27:05 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1108628](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108628)|dotnet/runtime|[System.Collections.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108628&view=ms.vss-test-web.build-test-results-tab&runId=30405718&resultId=211227)|dotnet/runtime#116539|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Conditional escape analysis is triggered by a GDV guarded call to `GetEnumerator`. On the fast path this call is devirtualized and inlined and exposes one or more enumerator object allocations. The more case allows for collections to do optimizations like returning a special enumerator object for an empty collection.

When there is more than one enumerator object allocation under the GDV guard, ensure that only the allocation that was analyzed for conditional escape is stack allocated; the remaining enumerators will end up on the "slow path" where enumeration happens via interface calls, and so must be heap objects.

Fixes #111922.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
FYI @dotnet/jit-contrib 
@amanasifkhalid PTAL

No diffs expected. The libraries tests only occasionally tier up the method that exposes this problem. The attached repro case was reliable on linux x64.

**Comment by AndyAyersMS** [comment]
Graphically the situation is like this: BB14 is the GDV guard block; the colored boxes are the possible def values of the enumerator var. All these paths join down below at the def block (not shown).

The green allocation is the one we want to stack allocate, the yellow is an allocated array enumerator; the red is the empty static array enumerator, and the blue is the residual call to `GetEnumerator` for other collection types.

After CEA cloning, the green path will become the "fast" path where all the subsequent GDV checks on the enumerator succeed, and all enumerator methods are inlined.

The yellow/red/blue paths merged into the "slow" path where the enumerator methods are interface calls; along those paths all the enumerator objects must be on the heap. 

This fix forces the yellow allocation to the heap.

image

**Comment by AndyAyersMS** [comment]
Have some asserts to investigate...

File: src/coreclr/jit/objectalloc.cpp [hunk 1]
```diff
@@ -3861,6 +3916,35 @@ bool ObjectAllocator::CheckCanClone(CloneInfo* info)
...
+        // The allocation is conditional. See if we can find the GDV guard
+        // so we can check what other possible stack allocations might reach
+        // the def block.
+        //
+        BasicBlock* possibleGuardBlock = defBlock->bbIDom;
+        GuardInfo   gi;
+        if (IsGuard(possibleGuardBlock, &gi))
+        {
+            // Todo: validate guard is the right guard.
+            //
```
Comment (amanasifkhalid) [inline src/coreclr/jit/objectalloc.cpp:3930]: If we get this wrong, do we just pessimize stack allocation, or could this create correctness issues?

**Review by amanasifkhalid — APPROVED** [review]
LGTM

File: src/coreclr/jit/objectalloc.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/objectalloc.cpp:3930]: This would be an extra safety check. We already know that we're inside the right kind of GDV, and the def block should be (or would have been, before #116992) dominated by the right kind of guard. 

Currently we don't record enough information to check for this properly. We would need to know what collection type the guard should be checking for.
