### PR TITLE
Use similar types for self-referential generics instead of the exact canonical type

### LINKED ISSUE #6924: Unused generic type parameter should not cause loader failure
Consider the following code: 

```c#
static class Program
{
    static void Main()
    {
        var m = new M();
    }
}

struct N<T> { }
struct M { public N<M> E; }
```

This code will compile with C# 6.0 and is legal according to the CLI spec.  The type definition is recursive but the layout of the struct is not because the field involved here is an empty struct.  The CLR is unable to handle this though and fails at runtime with a `TypeLoadException`:

> 'M:Program.Main' failed: Could not load type 'M' from assembly 'ConsoleApplication1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
	**System.TypeLoadException**: Could not load type 'M' from assembly 'ConsoleApplication1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
	at Program.Main()

See also dotnet/runtime#5479

### PR DESCRIPTION
**Pull request by davidwrighton**
- Take advantage of work done a few years ago to simplify the interaction with the interop subsystem
- In the problematic case, simulate loads with two different types as instantiations which are unrelated in field layout, and see if they match up. Only enable this code in a few very small isolated parts of the runtime
- Filter more of the type loader logic through the byvalue class cache which should improve performance a bit
- Similarly when considering blittability, tweak the logic to use the special load path

- Support for self-recursive generics is not enabled for static fields, as that requires a somewhat different tweak, and there is less apparent demand. (For that scenario self-referential generics really should support having fields of type T.)
- Support for indirect self-recursive generics is also not enabled. The approach taken here is not practical for that, and there does not appear to be significant demand for that either.

Fixes #6924

### CODE REVIEW

**Comment by davidwrighton** [comment]
Fixes #6924

File: src/coreclr/vm/classlayoutinfo.cpp [hunk 1]
```diff
@@ -533,20 +534,45 @@ namespace
...
+                                                                             TRUE, NULL, NULL, NULL, 
+                                                                             &recursiveControl);
+
+                    if (typeHandleMaybe.IsNull())
+                    {
+                        // Everett C++ compiler can generate a TypeRef with RS=0
+                        // without respective TypeDef for unmanaged valuetypes,
+                        // referenced only by pointers to them.
+                        // In such case, GetTypeHandleThrowing returns null handle,
+                        // and we return E_T_VOID
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/classlayoutinfo.cpp:558]: I think we should update this.

File: src/coreclr/vm/siginfo.cpp [hunk 2]
```diff
@@ -998,6 +999,25 @@ TypeHandle SigPointer::GetTypeHandleThrowing(
     }
     CONTRACT_END
 
+    _ASSERTE(!pRecursiveFieldGenericHandling || dropGenericArgumentLevel); // pRecursiveFieldGenericHandling can only be set if dropGenericArgumentLevel is set
+    if (!!pRecursiveFieldGenericHandling)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/siginfo.cpp:1003]:
```suggestion
    if (pRecursiveFieldGenericHandling != NULL)
```

**Review by AaronRobinsonMSFT — COMMENTED** [review]
I'm still going through this.

File: src/coreclr/vm/classlayoutinfo.cpp (hunk 1 above)
Comment (davidwrighton) [reply src/coreclr/vm/classlayoutinfo.cpp:558]: Probably, but this change is confusing enough as it is without adding a known potential behavior change. I'd like to see that done as a separate PR.

Comment (davidwrighton) [reply src/coreclr/vm/classlayoutinfo.cpp:558]: If you do that, please get rid of the weirdo ThrowButNullV11McppWorkaround logic too.

File: src/coreclr/vm/fieldmarshaler.cpp [hunk 3]
```diff
@@ -201,8 +201,8 @@ VOID ParseNativeType(Module*                     pModule,
 bool IsFieldBlittable(
     Module* pModule,
     mdFieldDef fd,
-    SigPointer fieldSig,
-    const SigTypeContext* pTypeContext,
+    CorElementType corElemType,
+    TypeHandle valueTypeHandle,
     ParseNativeTypeFlags flags
 )
 {
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/fieldmarshaler.cpp:208]: Contract?

File: src/coreclr/vm/methodtable.cpp [hunk 4]
```diff
@@ -2238,11 +2239,20 @@ static SystemVClassificationType ReClassifyField(SystemVClassificationType origi
     }
 }
 
+MethodTable* ByValueClassCacheLookup(MethodTable** pByValueClassCache, unsigned index)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/methodtable.cpp:2242]:
```suggestion
static MethodTable* ByValueClassCacheLookup(MethodTable** pByValueClassCache, unsigned index)
```

File: src/coreclr/vm/siginfo.cpp [hunk 5]
```diff
@@ -1329,110 +1349,221 @@ TypeHandle SigPointer::GetTypeHandleThrowing(
...
+                                            uint32_t varIndex;
+                                            IfFailThrowBF(tempsig.GetData(&varIndex), BFA_BAD_SIGNATURE, pModule);
+                                            if (varIndex != iInstantiation)
+                                            {
+                                                recursionDetected = false;
+                                                break;
+                                            }
+                                        }
+                                    }
+                                    handlingRecursiveGenericFieldScenario = true;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/siginfo.cpp:1436]: `recursionDetected` not used?

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/vm/fieldmarshaler.cpp [hunk 6]
```diff
@@ -201,11 +201,19 @@ VOID ParseNativeType(Module*                     pModule,
...
+    CONTRACTL
+    {
+        THROWS;
+        GC_TRIGGERS;
+        MODE_ANY;
+    }
+    CONTRACTL_END;
```
Comment (jkotas) [inline src/coreclr/vm/fieldmarshaler.cpp:215]:
```suggestion
    STANDARD_VM_CONTRACT;
```

File: src/coreclr/vm/field.h [hunk 7]
```diff
@@ -324,6 +324,9 @@ class FieldDesc
     // Return -1 if the type isn't loaded yet (i.e. if LookupFieldTypeHandle() would return null)
     UINT GetSize();
 
+    // Return -1 if the type is a structure and pMTOfValueTypeField is NULL and LookupFieldTypeHandle() returns null
```
Comment (jkotas) [inline src/coreclr/vm/field.h:327]: Do we actually depend on this returning -1 anywhere? It seems we always assume that it is going to succeed. Should we make this more restrictive and assert instead of returning -1?

**Comment by jkotas** [comment]
This does not seem to handle directly self-referential generics. For example, this compiles fine, but still fails to run:
```
struct N<T> { }
struct M { public N<Nullable<M>> E; }
```
Is it expected that this does not work?

**Review by jkotas — APPROVED** [review]
