### PR TITLE
Use C EventPipe implementation by default

### LINKED ISSUE #46079: Switch to C implementation of EventPipe
~We should have a CI pipeline that tests the C version of EventPipe until we have permanently turned on the feature flag.  This will help to make sure we don't have any regressions in the meantime.~

This issue will track progress towards switching over to the C implementation of EventPipe.  Currently, it is behind a feature flag.  Before we transition, we should collect the following information:

- [x] code size comparison
  - See @am11's comment below for some rudimentary numbers
- [ ] throughput comparisons
  - We should document throughputs for both the C and C++ implementations before removing the C++ implementation.
- [x] regressions analysis with external tools
  - We have tests in the runtime repo that test the IPC protocols and EventPipe directly, but we don't have tests that cover the end-to-end scenario when it comes to dotnet-trace, etw, or other external tools (We do in dotnet/diagnostics though).  We should do some local testing to make sure we aren't breaking any scenarios (I doubt we are).
- [x] Regressions from C++
  - [x] Release builds of C impl AV inside `ep_buffer_manager_write_event` (#46158)
  - [x] Checked builds of C assert if app has is being traced during shutdown, e.g., tracing and app to completion. (#46159)
    - Perhaps this assert comes from the Mono requirement to be able to clean up an restart execution of the runtime vs CoreCLR's expectation that shutdown will lead to the OS cleaning things up?
    - Not tracked by this issue: we should add a test that tests this scenario as it is expected to work.

CC - @tommcdon @lateralusX

### PR DESCRIPTION
**Pull request by josalem**
The adaptors and shims are left as is to accommodate any future runtime targets for the EventPipe library.

The C++ source files and headers were removed as part of this switch.  It's a separate commit, so we could make it a separate PR if we feel the need to keep the files around.

closes #46079 

I ran end-to-end tests with our diagnostic tools on my MacBook locally.  Traces collected opened in PerfView fine.  `dotnet-gcdump` was able to report heap stats correctly.  `dotnet-dump` was able to generate usable memory dumps.

CC @dotnet/dotnet-diag @tommcdon @sywhang @noahfalk @lateralusX

### CODE REVIEW

File: src/native/eventpipe/ds-ipc-posix.c [hunk 1]
```diff
@@ -1,6 +1,7 @@
-#ifdef FEATURE_PERFTRACING_C_LIB_STANDALONE_PAL
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
 #define EP_NO_RT_DEPENDENCY
-#endif
 
 #include "ds-rt-config.h"
```
Comment (am11) [inline src/native/eventpipe/ds-ipc-posix.c:6]: Some legs are failing because of a missing header:
```suggestion
#include "ds-rt-config.h"
#include <string.h>
```

Comment (josalem) [reply src/native/eventpipe/ds-ipc-posix.c:6]: I think it's because I removed the `FEATURE_PERFTRACING_C_LIB_STANDALONE_PAL` feature flag and the associated `ifndef`s.  I'm guessing when Mono builds, it didn't specify that flag.  I'll push a change.

Comment (am11) [reply src/native/eventpipe/ds-ipc-posix.c]: Maybe `FEATURE_PERFTRACING_C_LIB_STANDALONE_PAL` can stay deleted and conditions can just be based on `FEATURE_CORECLR`?

File: src/coreclr/clrdefinitions.cmake [hunk 2]
```diff
@@ -104,9 +104,7 @@ add_definitions(-DFEATURE_DEFAULT_INTERFACES)
 if(FEATURE_EVENT_TRACE)
     add_compile_definitions($<$<NOT:$<BOOL:$<TARGET_PROPERTY:CROSSGEN_COMPONENT>>>:FEATURE_EVENT_TRACE>)
     add_definitions(-DFEATURE_PERFTRACING)
-    if(FEATURE_PERFTRACING_C_LIB)
-      add_definitions(-DFEATURE_PERFTRACING_C_LIB)
-    endif(FEATURE_PERFTRACING_C_LIB)
+    add_definitions(-DFEATURE_PERFTRACING_C_LIB)
```
Comment (am11) [inline src/coreclr/clrdefinitions.cmake:107]: If `FEATURE_PERFTRACING` and `FEATURE_PERFTRACING_C_LIB` are equivalent with this change, maybe we can delete the latter?

**Review by davmason — APPROVED** [review]

**Review by noahfalk — APPROVED** [review]

**Review by sywhang — APPROVED** [review]

**Review by lateralusX — APPROVED** [review]

File: src/native/eventpipe/ds-ipc-posix.c (hunk 1 above)
Comment (josalem) [reply src/native/eventpipe/ds-ipc-posix.c]: I removed the `C_LIB` part of the feature flag, but left the feature flag in general since it does represent a feature that can be disabled.  Future runtime implementations might make use of this flag.

**Comment by jkotas** [comment]
@lateralusX @josalem Thank you for making this happen!
