### PR TITLE
JIT: Make GS cookie phase run on LIR and move it after async phase

### LINKED ISSUE #122954: Test failure: _shared_generic::Async2SharedGeneric.TestEntryPoint()
**Failed in:** [runtime-coreclr jitstress 20260105.2](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1244008)

**Failed tests:**
```
coreclr windows x64 Checked jitstress1 @ Windows.10.Amd64.Open
    - _shared_generic::Async2SharedGeneric.TestEntryPoint()
```

**Error message:**
```
One or more errors occurred. (Assert.Equal() Failure: Values differ
Expected: Async2SharedGeneric+S0
Actual:   null)
```

**Stack trace:**
```
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Async2SharedGeneric.TestEntryPoint()
   at Program.<<Main>$>g__TestExecutor44|0_45(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
Functions with GS cookie checks may furthermore shadow parameters to make sure that the GS cookie ends up above all parameters on the stack. This is done by creating a copy of parameters used like a pointer and redirecting all uses to act on the shadow. IR is inserted in the beginning of the function to copy the parameters to their shadows.

For async this introduces a problem when it comes to implicit byrefs. The shadowing ceremony introduces a pointer to a local (the storage area in the caller) and that pointer remains live across suspension points, resulting in illegal IR.

This PR moves the GS phase so that it runs after the async transformation. To do so rewrite the analysis to run on LIR and the IR insertion/rewriting to be compatible with LIR.

Fix #122954

### CODE REVIEW

File: src/coreclr/jit/gschecks.cpp [hunk 1]
```diff
@@ -620,3 +541,170 @@ void Compiler::gsParamsToShadows()
...
+        if (tree->OperIsScalarLocal())
+        {
+            tree->gtType = TYP_INT;
+        }
+        else if (tree->OperIs(GT_STORE_LCL_FLD) && tree->IsPartialLclFld(this))
+        {
+            tree->gtFlags |= GTF_VAR_USEASG;
+        }
+    }
+}
```
Comment (jakobbotsch) [inline src/coreclr/jit/gschecks.cpp:572]: Pulled this logic into a helper function used from both `gsParamsToShadows` and `gsParamsToShadowsAsync`. No changes to the logic itself.

File: src/coreclr/jit/gschecks.cpp [hunk 2]
```diff
@@ -620,3 +541,170 @@ void Compiler::gsParamsToShadows()
...
+        const unsigned shadowVarNum = gsShadowVarInfo[lclNum].shadowCopy;
+        if (shadowVarNum == BAD_VAR_NUM)
+        {
+            continue;
+        }
+
+        if (varDsc->lvPromoted && !varDsc->lvDoNotEnregister)
+        {
+            lvaSetVarDoNotEnregister(lclNum DEBUGARG(DoNotEnregisterReason::BlockOp));
+        }
```
Comment (jakobbotsch) [inline src/coreclr/jit/gschecks.cpp]: Technically we could do better.. but given that promotion is expected to be removed and that async functions with GS cookie checks in them are expected to be rare, I think DNER is just fine.

File: src/coreclr/jit/lclvars.cpp [hunk 3]
```diff
@@ -2156,6 +2156,7 @@ void Compiler::lvaSetVarLiveInOutOfHandler(unsigned varNum)
     if (!lvaEnregEHVars || !varDsc->lvSingleDefRegCandidate || varDsc->lvRefCnt() <= 1)
     {
         lvaSetVarDoNotEnregister(varNum DEBUGARG(DoNotEnregisterReason::LiveInOutOfHandler));
+        JITDUMP("Single def reg candidate: %d, ref cnt: %d\n", varDsc->lvSingleDefRegCandidate, varDsc->lvRefCnt());
```
Comment (jakobbotsch) [inline src/coreclr/jit/lclvars.cpp]:
```suggestion
```

File: src/coreclr/jit/gschecks.cpp [hunk 4]
```diff
@@ -372,16 +380,91 @@ bool Compiler::gsFindVulnerableParams()
...
+                const unsigned shadowVarNum = gsShadowVarInfo[lclNum].shadowCopy;
+                if (shadowVarNum == BAD_VAR_NUM)
+                {
+                    continue;
+                }
+
+                GenTree* src   = gtNewLclVarNode(shadowVarNum);
+                GenTree* store = gtNewStoreLclVarNode(lclNum, src);
+
+                LIR::AsRange(fgFirstBB).InsertBefore(lastNode, LIR::SeqTree(this, store));
```
[the remark this answers is not in the document]
Comment (jakobbotsch) [reply src/coreclr/jit/gschecks.cpp]: Good catch!

```suggestion
                LIR::AsRange(block).InsertBefore(lastNode, LIR::SeqTree(this, store));
```

File: src/coreclr/jit/gschecks.cpp [hunk 5]
```diff
@@ -372,16 +380,91 @@ bool Compiler::gsFindVulnerableParams()
...
+        }
+    }
+}
 
+//-------------------------------------------------------------------------------
+// gsCreateShadowingLocals:
+//   For each parameter that should be shadowed, create a local variable to hold its copy.
+//
+// Returns:
+//   True if any shadowing locals were created..
```
[the remark this answers is not in the document]
Comment (jakobbotsch) [reply src/coreclr/jit/gschecks.cpp]:
```suggestion
//   True if any shadowing locals were created.
```

File: src/coreclr/jit/compiler.h [hunk 6]
```diff
@@ -11247,18 +11247,23 @@ class Compiler
...
-    GSCookie            gsGlobalSecurityCookieVal;  // Value of global cookie if addr is NULL
-    ShadowParamVarInfo* gsShadowVarInfo = nullptr;  // Table used by shadow param analysis code
+    GSCookie*           gsGlobalSecurityCookieAddr;     // Address of global cookie for unsafe buffer checks
+    GSCookie            gsGlobalSecurityCookieVal;      // Value of global cookie if addr is NULL
+    ShadowParamVarInfo* gsShadowVarInfo      = nullptr; // Table used by shadow param analysis code
+    unsigned            gsShadowVarInfoCount = 0;
 
     PhaseStatus gsPhase();
     void        gsGSChecksInitCookie();   // Grabs cookie variable
     void        gsCopyShadowParams();     // Identify vulnerable params and create dhadow copies
```
[the remark this answers is not in the document]
Comment (jakobbotsch) [reply src/coreclr/jit/compiler.h]:
```suggestion
    void        gsCopyShadowParams();     // Identify vulnerable params and create shadow copies
```

File: src/coreclr/jit/gschecks.cpp [hunk 7]
```diff
@@ -372,16 +380,91 @@ bool Compiler::gsFindVulnerableParams()
...
+
+        gsCopyIntoShadow(lclNum, shadowLclNum);
+    }
+
+    // If the method has "Jmp CalleeMethod", then we need to copy shadow params back to original
+    // params before "jmp" to CalleeMethod.
+    if (compJmpOpUsed)
+    {
+        // There could be more than one basic block ending with a "Jmp" type tail call.
+        // We would have to insert stores in all such blocks, just before GT_JMP stmnt.
```
Comment (AndyAyersMS) [inline src/coreclr/jit/gschecks.cpp]:
```suggestion
        // We have to insert stores in all such blocks, just before GT_JMP stmnt.
```

File: src/coreclr/jit/gschecks.cpp [hunk 8]
```diff
@@ -101,200 +102,207 @@ void Compiler::gsCopyShadowParams()
...
-    struct MarkPtrsInfo* pState        = (MarkPtrsInfo*)data->pCallbackData;
-    struct MarkPtrsInfo  newState      = *pState;
-    Compiler*            comp          = data->compiler;
-    GenTree*             tree          = *pTree;
-    ShadowParamVarInfo*  shadowVarInfo = pState->comp->gsShadowVarInfo;
-    assert(shadowVarInfo);
 
-    assert(!pState->isStoreSrc || (pState->lvStoreDef != BAD_VAR_NUM));
+    //
+    // Add lvAssignDef and lclNum to a common assign group
```
Comment (AndyAyersMS) [inline src/coreclr/jit/gschecks.cpp]: This comment seems stale -- even in the original.

**Review by AndyAyersMS — APPROVED** [review]
Looks good, just a few comments about comments.

**Review by steveisok — APPROVED** [review]
