### PR TITLE
Fixing a crash bug

### LINKED ISSUE #63221: Bad data can cause ILVerify to throw NRE
### Description

While attempting to use ILVerify to diagnose a compiler output problem, it instead blew up in my face, dumping a `NullReferenceException` stack trace on me.

### Reproduction Steps

1) Install .NET 5.
2) Install ILVerify.
3) Download [this test case](https://github.com/dotnet/runtime/files/7792951/testcase.zip) and unzip it to a new folder.
4) Open PowerShell and CD to that folder.
5) `ilverify .\testcase.dll -r "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.13\*.dll"`  (Adjust .NET 5 path as needed)
 

### Expected behavior

A correct program should not throw ["boneheaded exceptions."](https://ericlippert.com/2008/09/10/vexing-exceptions/)

A diagnostic tool should provide helpful diagnostic information about the nature of errors encountered.

### Actual behavior

<details>

```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
at ILVerify.ILVerifyTypeSystemContext.VerifyModuleName(String simpleName, EcmaModule module)
at ILVerify.ILVerifyTypeSystemContext.ResolveAssemblyOrNetmodule(String simpleName, String verificationName, IAssemblyDesc containingAssembly, Boolean throwIfNotFound)
at ILVerify.ILVerifyTypeSystemContext.ResolveAssembly(AssemblyName name, Boolean throwIfNotFound)
at Internal.TypeSystem.Ecma.EcmaModule.ResolveAssemblyReference(AssemblyReferenceHandle handle)
at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle)
at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior)
at Internal.TypeSystem.Ecma.EcmaModule.ResolveTypeReference(TypeReferenceHandle handle)
at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle)
at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ResolveHandle(EntityHandle handle)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl(SignatureTypeCode typeCode)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode typeCode)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl()
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType()
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl(SignatureTypeCode typeCode)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode typeCode)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl()
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType()
at Internal.TypeSystem.Ecma.EcmaModule.ResolveTypeSpecification(TypeSpecificationHandle handle)
at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle)
at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior)
at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle handle)
at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType()
at Internal.TypeSystem.Ecma.EcmaType.get_BaseType()
at Internal.TypeSystem.TypeDesc.get_IsDelegate()
at Internal.IL.ILImporter.ImportCall(ILOpcode opcode, Int32 token)
at Internal.IL.ILImporter.ImportBasicBlock(BasicBlock basicBlock)
at Internal.IL.ILImporter.ImportBasicBlocks()
at Internal.IL.ILImporter.Verify()
at ILVerify.Verifier.VerifyMethod(EcmaModule module, MethodIL methodIL, MethodDefinitionHandle methodHandle)
at ILVerify.Verifier.VerifyMethods(EcmaModule module, IEnumerable`1 methodHandles)+MoveNext()
at ILVerify.Verifier.Verify(PEReader peReader, MethodDefinitionHandle methodHandle)+MoveNext()
at ILVerify.Program.VerifyMethods(PEReader peReader, EcmaModule module, String path, Int32& numErrors, Int32& verifiedMethodCounter, Int32& methodCounter)
at ILVerify.Program.VerifyAssembly(PEReader peReader, EcmaModule module, String path)
at ILVerify.Program.Run()
at ILVerify.Program.Run(Options options)
```

</details>

### Configuration

.NET 5, Windows 10, x64

### PR DESCRIPTION
**Pull request by masonwheeler**
ILVerify will currently crash with a `NullReferenceException` if parsing a type signature referring to an assembly that was not specified as a `-r` parameter.

Fixes #63221.

### CODE REVIEW

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs [hunk 1]
```diff
@@ -585,7 +585,7 @@ private Object ResolveAssemblyReference(AssemblyReferenceHandle handle)
             an.CultureName = _metadataReader.GetString(assemblyReference.Culture);
             an.ContentType = GetContentTypeFromAssemblyFlags(assemblyReference.Flags);
 
-            var assembly = _moduleResolver.ResolveAssembly(an, throwIfNotFound: false);
+            var assembly = _moduleResolver.ResolveAssembly(an);
             if (assembly == null)
                 return ResolutionFailure.GetAssemblyResolutionFailure(an.Name);
```
Comment (CyrusNajmabadi) [inline src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:590]: the original code seems correct. is it another layer that is not properly handling the returned value from ResolutionFailure.GetAssemblyResolutionFailure?

Comment (masonwheeler) [reply src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:590]: > ResolutionFailure.GetAssemblyResolutionFailure

I assume you're referring to the call immediately after the changed line?  It never reaches it, which is why the original code is incorrect.  `ILVerifyTypeSystemContext.ResolveAssembly` calls `ILVerifyTypeSystemContext.ResolveAssemblyOrNetmodule`, which executes the following code:

```
            PEReader peReader = _resolver.Resolve(simpleName); //returns null
            if (peReader == null && throwIfNotFound) //throwIfNotFound is false
            {
                throw new VerifierException("Assembly or module not found: " + simpleName);
            }
            var module = GetModule(peReader, containingAssembly); //returns null
            VerifyModuleName(verificationName, module); //blows up because it expects module to be not null
            return module;
```

If we assume that the original code is correct, and the expected behavior is to return null here, then should a null check be added to the top of `VerifyModuleName` instead?

**Comment by masonwheeler** [comment]
Fixes #62711

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs (hunk 1 above)
Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:590]: I think it would be better to return null as soon as we find that this is not going to work:
```
            if (peReader == null)
            {
                if (throwIfNotFound)
                    throw new VerifierException("Assembly or module not found: " + simpleName);
                return null;
            }
```
I think the early out for null can be deleted from `GetModule` with this fix.

Comment (masonwheeler) [reply src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:590]: > I think the early out for null can be deleted from `GetModule` with this fix.

It can't yet.  `GetModule` is called from multiple places.  One of them is `Program.VerifyAssembly`, and there is no null check in place there.

Comment (masonwheeler) [reply src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs]: > I think it would be better to return null as soon as we find that this is not going to work

Done.  Thanks for the feedback!

**Review by jkotas — APPROVED** [review]
Thank you!
