### PR TITLE
Check if External Object Context is still active after a possible GC

### LINKED ISSUE #59072: Test Failure Interop\\COM\\ComWrappers\\GlobalInstance\\GlobalInstanceMarshallingTestsBuiltInComDisabled\\GlobalInstanceMarshallingTestsBuiltInComDisabled.cmd
Run: [runtime-coreclr r2r-extra 20210912.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1358217&view=ms.vss-test-web.build-test-results-tab&runId=39698774&paneView=debug&resultId=102814)

Failed test:
```
R2R windows arm64 Checked gcstress0xf @ Windows.10.Arm64v8.Open

- Interop\\COM\\ComWrappers\\GlobalInstance\\GlobalInstanceMarshallingTestsBuiltInComDisabled\\GlobalInstanceMarshallingTestsBuiltInComDisabled.cmd

```
**Error message:**
```
Could Not Find D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\COMNativeServer.dll.rsp
Could Not Find D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\GlobalInstanceMarshallingTestsBuiltInComDisabled.dll.rsp
Could Not Find D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\hostpolicy.dll.rsp
Could Not Find D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\MockReferenceTrackerRuntime.dll.rsp
Could Not Find D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\NETServer.dll.rsp
Could Not Find D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\TestLibrary.dll.rsp

Assert failure(PID 8476 [0x0000211c], Thread: 1800 [0x0708]): IsActive()

CORECLR! anonymous namespace'::ExtObjCxtCache::CreateManagedEnumerable + 0x344 (0x00007ff882983c2c)
CORECLR! InteropLibImports::ReleaseExternalObjectsFromCurrentThread + 0x110 (0x00007ff882985420) MOCKREFERENCETRACKERRUNTIME! UpdateTestObjectAsIDispatch + 0x1E340 (0x00007ff887c89f40)
MOCKREFERENCETRACKERRUNTIME! UpdateTestObjectAsIDispatch + 0x24704 (0x00007ff887c90304) GLOBALINSTANCEMARSHALLINGTESTSB! <no symbol> + 0x0 (0x00007ff89e635164)
GLOBALINSTANCEMARSHALLINGTESTSB! <no symbol> + 0x0 (0x00007ff89e635390) CORECLR! CallDescrWorkerInternal + 0x84 (0x00007ff882712034)
CORECLR! CallDescrWorkerWithHandler + 0x100 (0x00007ff882862f68) CORECLR! MethodDescCallSite::CallTargetWorker + 0x4CC (0x00007ff88286344c)
CORECLR! RunMainInternal + 0x250 (0x00007ff8`8272de48)
File: D:\workspace_work\1\s\src\coreclr\vm\interoplibinterface_comwrappers.cpp Line: 124
Image: D:\h\w\BF250A6D\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\BF250A6D\w\A4C60932\uploads\Reports\Interop.COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\GlobalInstanceMarshallingTestsBuiltInComDisabled.output.txt
Raw output:
BEGIN EXECUTION
COMNativeServer.dll
GlobalInstanceMarshallingTestsBuiltInComDisabled.dll
hostpolicy.dll
MockReferenceTrackerRuntime.dll
NETServer.dll
TestLibrary.dll
6 file(s) copied.
Response file: D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\COMNativeServer.dll.rsp
D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\IL-CG2\COMNativeServer.dll
-o:D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\COMNativeServer.dll
--targetarch:arm64
--verify-type-and-field-layout
-r:D:\h\w\BF250A6D\p\System..dll
-r:D:\h\w\BF250A6D\p\Microsoft..dll
-r:D:\h\w\BF250A6D\p\mscorlib.dll
-r:D:\h\w\BF250A6D\p\netstandard.dll
-O
" "dotnet" "D:\h\w\BF250A6D\p\crossgen2\crossgen2.dll" @"D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\COMNativeServer.dll.rsp"   -r:D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\IL-CG2*.dll"
No input files are loadable
Response file: D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\GlobalInstanceMarshallingTestsBuiltInComDisabled.dll.rsp
D:\h\w\BF250A6D\w\A4C60932\e\Interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTestsBuiltInComDisabled\IL-CG2\GlobalInstanceMarshallingTestsBuiltInComDisabled.dll
-o:D:\h\w\BF250A6D\w\A4C6093


Stack trace
   at Interop_COM._ComWrappers_GlobalInstance_GlobalInstanceMarshallingTestsBuiltInComDisabled_GlobalInstanceMarshallingTestsBuiltInComDisabled_._ComWrappers_GlobalInstance_GlobalInstanceMarshallingTestsBuiltInComDisabled_GlobalInstanceMarshallingTestsBuiltInComDisabled_cmd()
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Comments in this code detail the logic and reasons for failure.

This should be considered for .NET 6.

Fixes #59072

/cc @davidwrighton @jkoritzinsky @elinor-fung

### CODE REVIEW

File: src/coreclr/vm/interoplibinterface_comwrappers.cpp [hunk 1]
```diff
@@ -349,15 +356,55 @@ namespace
...
+                {
+                    // The context has been detach for this cache.
+                    // Since the state of this object is now under
+                    // the control of the Finalizer/GC, we null it out. This
+                    // allows us to ignore it when we iterate over the
+                    // collection later. The null here is needed because
+                    // it indicates the array size is going to change
+                    // and a new array allocated. That allocation is an
+                    // opportunity for the GC to remove it from this hashmap
+                    // and free the external object context.
```
Comment (elinor-fung) [inline src/coreclr/vm/interoplibinterface_comwrappers.cpp:382]:
```suggestion
                    // and a new array will be allocated. That allocation is
                    // an opportunity for the GC to remove the object from
                    // this hashmap and free the external object context.
```

File: src/coreclr/vm/interoplibinterface_comwrappers.cpp [hunk 2]
```diff
@@ -349,15 +356,55 @@ namespace
...
                 ExternalObjectContext* inst = localList[i];
-                gc.arrRef->SetAt(i, inst->GetObjectRef());
+                if (!inst->IsSet(ExternalObjectContext::Flags_Detached))
+                {
+                    gc.arrRef->SetAt(objCount, inst->GetObjectRef());
+                    objCount++;
+                }
+                else
+                {
+                    // The context has been detach for this cache.
```
Comment (elinor-fung) [inline src/coreclr/vm/interoplibinterface_comwrappers.cpp:374]:
```suggestion
                    // The context has been detached for this cache.
```

File: src/coreclr/vm/interoplibinterface_comwrappers.cpp [hunk 3]
```diff
@@ -349,15 +356,55 @@ namespace
...
+                    STRESS_LOG1(LF_INTEROP, LL_INFO100, "EOC no longer active: 0x%p\n", inst);
+                    localList[i] = NULL;
+                }
             }
 
+            // During the allocation of the array to return, a GC could have
+            // occurred and objects detach from this cache. In order to avoid
+            // having null array elements we will allocate a new array.
+            // This subsequent allocation is okay because the array we are
+            // replacing extends all object lifetimes.
```
Comment (elinor-fung) [inline src/coreclr/vm/interoplibinterface_comwrappers.cpp:392]:
```suggestion
            // occurred and objects detached from this cache. In order to avoid
            // having null array elements, we will allocate a new array.
            // This subsequent allocation is okay because the array we are
            // replacing has already extended all object lifetimes.
```

File: src/coreclr/vm/interoplibinterface_comwrappers.cpp (hunk 1 above)
Comment (elinor-fung) [reply src/coreclr/vm/interoplibinterface_comwrappers.cpp:382]: Actually this seems a bit off:

> The null here is needed because it indicates the array size is going to change

That's based on the count, not this nulling out, no?

If I'm reading the comment, right, maybe something like:

In this scenario, the array size is going to change and a new array allocated will be allocated. Because we null out the object here, that allocation of the new array is an opportunity for the GC to remove the object from this hashmap and free the external object context.

**Review by elinor-fung — APPROVED** [review]

File: src/coreclr/vm/interoplibinterface_comwrappers.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interoplibinterface_comwrappers.cpp:382]: Sure. Will update with a new comment. GitHub is being difficult.

Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/interoplibinterface_comwrappers.cpp:382]:
```suggestion
                    // Since the state of this object is now under
                    // the control of the Finalizer/GC, we null it out. 
                    // In this scenario, the array size is going to change
                    // and a new array will be allocated. We null out the
                    // object here because that allocation of the new array
                    // is an opportunity for the GC to remove the object from
                    // this hashmap and free the external object context.
```

**Comment by davidwrighton** [comment]
>             gc.arrRef = (PTRARRAYREF)AllocateObjectArray((DWORD)localList.Size(), g_pObjectClass);

This change relies on this AllocateObjectArray call not triggering multiple GCs. While I think that such behavior would be unusual, I don't think its a good practice to rely on such a detail.

---
Refers to: src/coreclr/vm/interoplibinterface_comwrappers.cpp:355 in e820da6. [](commit_id = e820da6e66c884334e5ade54e279f81c2a48b6d3, deletion_comment = False)

File: src/coreclr/vm/interoplibinterface_comwrappers.cpp [hunk 4]
```diff
@@ -369,7 +415,11 @@ namespace
                 for (SIZE_T i = 0; i < localList.Size(); i++)
                 {
                     ExternalObjectContext* inst = localList[i];
-                    InteropLib::Com::SeparateWrapperFromTrackerRuntime(inst);
+
+                    // Confirm the external object wasn't detached from the
+                    // cache during one of the previous array allocations.
+                    if (inst != NULL && !inst->IsSet(ExternalObjectContext::Flags_Detached))
```
Comment (davidwrighton) [inline src/coreclr/vm/interoplibinterface_comwrappers.cpp:421]: >Flags_Detached [](http://example.com/codeflow?start=76&length=14)

If this flag is set during GC it isn't a safe flag to check in preemptive mode.

**Review by davidwrighton — APPROVED** [review]
The allocation problem here now looks solved.
