### PR TITLE
JIT: Handle half accesses for SIMDs in local morph

### LINKED ISSUE #85359: Vectorized code in loop performance problems due to excessive stack <-> vector register moves
### Description

I am creating an implementation of [adler32 checksum](https://en.wikipedia.org/wiki/Adler-32?useskin=vector) using C# and I am getting significant performance regression in comparison with implementation written in rust - [simd-adler32](https://github.com/mcountryman/simd-adler32) by nearly 2.5 times.
[benchmark repository with source code](https://github.com/MadProbe/CSharpSimdAdler32)

### Configuration

See benchmark results

### Regression?

[Reproducible in .NET 7.0.](https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcAMACOSB0ASgK4B2wAllAKb4DCA9lAA4UA21ATgMpcBuFAMbUIAbnRZcBEuSq0AkuS4NmvTgOFiJOPETKUa+RcE4VSEIVow7p+uUfKnzl/AA0AHADZxaCQGZcBGw6bABvdGxI7ABtbhNiQWAAGTAATwZiYAAKFPTMgGkzABN8XgBHYmpZMDYAGmwABTBBAGtsAF5sJABKAF0IqOZTPjBgamxOagAzbAh4xOxuZjBSACE2Blb5Mc5Rhk4AHgAVAD4wgajB4dHxybAihlI2VMXl0mOzgH0RtkqrS8uQwoIzGE2o90ez2wZmA2E+ACMNq1uBQAF7UHwAq7Am5giFPF4wuEWdGYrHYIEg8ZEz7FagADw62AAtEgyVjogBZajAAAWDCK8hYbCy3L5AqFzDYAHlmJRHhB8ABBADmKsmEAsfGoijYZjMKr6FwBcACSxW602LW2XD2nCy5vep2wPz+9SJiKtKPR3XOaHJAL5FEV3xqfyZrpE7ID2CDIc9yLR406CZa3oxxoDcfwnxJyZdYZE+CSVRVfOwAHpsKn09HLgBfTNRU2vFYfYLETiTch+mNRLk8/mC4WiwcS4Wy+XmZVqjVanVPfWkQ39f197AqnkdM7Z0O/ETRLK7umMgBUsd5wZzNaT3Xw+F6daijbXHLFQ8lIvf46lk4oCpndURHnXUlxXJtIhbeEGAYNhsE5BhtQAOQZbJfXaM4AGpMOPUgigZbADgvK9cyTJ9ILNN520IagoDAMDe3XAdxWHKVRxYz8/wA1UgM1YEFz1UgDSNV8Y03WEMOIkNIwgQ9dzzbBz13G8fXvR8IOwF8A2Yj8R2/ViZTlf9px4ud+NAoTlxEgMW0dS0th2O12wAcR5ABRUhiBoXZgH2LJ0J3S9/mfY0dJ/L8xwMrjpyQhgLOE1dLliFoKGYJJNhqCBFAoYBEubAIyAgMApnGYgiQANWoRJ9iTIosnhVIxmiXpsCKUYwF9cJRMuCsKyVTgVS8qpgGlTJpSmQgVk3Nz6WEIzHnwI5eU4BgAHd5CmZy7h2JaViyNrgDAYtSz5epMHpBBMCuzB6lIMAaAYKZ9va7pulESsq0EFZSAYWFBrAXYlHGIqSuAF4simfZsB+1bug0yYZga0EDrAGiZk6BH4No/ZUk5AGIF5Gp8Fc4B+t2VIABF2rRrgqmEZ7DrejTKuqzgEAAVk8A5iA2ZczhGIoOE4JVPiZFnfLZzn6G26gsiQABVJIme6qJxf2DmubK8h+fuIXVigHngFFzo1clzWYROfAAC1lHI7BTY17neZVHXBa4VYRbFqqJcdnnHhd63bfh6Z7e99XOad/3XaFpUmUxgWY8+O3MYdiOteAaP3YNtgJLBGYE6zw2k+DmZU8153M84D245Dguq5Fu2y4OJHqH5lv0RWr3WcdlvLZtlafA0kZOGwbPgAgb4w5Hk2p416XwTGLIx9SvUuAgZWAybgn9gzl1HmoXN+U4XOy/nm4Dm34+TiyLJL+AboejtyGR6yTGW+wKoihrmZ5fMYraCVEUIoqxGrUHGlMCAPJX4hxRmjeoKNjrLnLMyVq7VEFll5NgAApKHbuEde70AyOQDe65f4gwUBAQBRQ5wlk1LtUg0CZiwOmPUTGn83qoMOmjb+2AyH/2VEAkBYxwGQOyJjZhUx6hNwIYwfQr1GJ9mHtWUBEAu4+ylule4fCSqMM4ajaYJDFG63drHToSo+AXQEXVOuHt6h1yVIYmMNix5MnMZYqhWRnGG3qG4hA+BOSGxXqkKhgCABWzRhpZF8f4wJUpglALCRE8g9UVH1DHhPbUrNuh2P3ofHed4lQQHlsYPwCB/KOIDPY1xFi/EePsT4mppQvJKnhBAWCmRqAUwoFMEq3ZNApLGBAOx7dlAFKKcYTwAAWcpdstLkiyE3P2fNsAbFWlwKRs804V2wMQZgzAuDoVweozw+AADqFB8IMK8TnCpUQlkqmwMYquajw4nO4F5LIqyDnYEwkc15TSoBZF2fszgvpfmn3eYCmxDi7b3MeW7YWLyzYAs8U8mFGlHTN1AWcSYdEGKdFINQVarY1hImtI5CWWKxjXxRhsvBXMZFEPvkQWi9FLIqjtmi7BnRzoADF+UKySJyhFqxuXYD5QKxWg8VaRGftgLIRIKBMhuisk6mCMasrAugvk70lVEQ4Eg3kursKdQ0pcLlmENV4vZdECg6kZUAieaKy18KY6zPQBpOAAB2eV6duhZCddg8V9J+W8qQIRIiSBPDYBgK6rgsccESrDY4uZkRKS4juA8AkswW7NVHrE1enBVEEqJTm0Bh4NaVnlXmR6t8W6+nPO4V6LVQjYFKfUPwSAO0qoQAATnqAgdwA6vUDs8AO9mA7JkDr8AOhAA6u3YEuvUJA/auhDq6COroY6ugTq6FOroM6uhzq6AupAKrV3rs3du3d+7D3HvDfWaMvVoirDpryOinAWh5QorgSZ8F/IKM0ugesQA===)

### Data

```
BenchmarkDotNet=v0.13.5, OS=Windows 10 (10.0.19043.2251/21H1/May2021Update)
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=8.0.100-preview.3.23178.7
  [Host]     : .NET 8.0.0 (8.0.23.17408), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.0 (8.0.23.17408), X64 RyuJIT AVX2


|     Method |         data |       Mean |     Error |    StdDev | Ratio | Code Size |
|----------- |------------- |-----------:|----------:|----------:|------:|----------:|
| Vectorized | Byte[102400] |   8.366 us | 0.0691 us | 0.0646 us |  0.02 |     902 B |
|      Naive | Byte[102400] | 412.368 us | 2.9653 us | 2.7738 us |  1.00 |     215 B |
```

adler32 simd implementation written in rust benchmark for avx2 using criterion.rs:
```
avx2/random-100k        time:   [3.5483 us 3.5684 us 3.5922 us]
                        thrpt:  [25.926 GiB/s 26.099 GiB/s 26.247 GiB/s]
--- some stuff is skipped
avx2/random-100k        time:   [3.5438 us 3.5655 us 3.5892 us]
                        thrpt:  [25.948 GiB/s 26.121 GiB/s 26.280 GiB/s]
                 change:
                        time:   [-1.5116% +0.2112% +2.0511%] (p = 0.82 > 0.05)
                        thrpt:  [-2.0099% -0.2107% +1.5348%]
                        No change in performance detected.
```

### Analysis

Comparing disassemblied code for rust and my c# implementation, the main problem lies in computation loop: there are too much memory <-> vector moves there and it can be much more efficient if more YMM registers were used:

[My C# code](https://github.com/MadProbe/CSharpSimdAdler32/blob/master/Program.cs#L36-L74) disassembly:

```asm
--- omitted for brevity
M00_L01:
       vmovups   ymm1,[rcx]
       vmovups   ymm2,[r10]
       vpaddq    ymm2,ymm2,[r8]
       vmovups   [r10],ymm2
       vpmaddubsw ymm2,ymm1,ymm0
       vpmaddwd  ymm2,ymm2,[7FFBA0BC7820]
       vpaddd    ymm2,ymm2,[r9]
       vmovups   [r9],ymm2
       vxorps    ymm2,ymm2,ymm2
       vpsadbw   ymm1,ymm1,ymm2
       vpaddq    ymm1,ymm1,[r8]
       vmovups   [r8],ymm1
       add       rcx,20
       cmp       rcx,r11
       jb        short M00_L01
--- omitted for brevity
```

And rust code loop:
source: https://github.com/mcountryman/simd-adler32/blob/main/src/imp/avx2.rs#L123-L132

```asm
--- Decompiled using Ghidra
                             LAB_14002ada0                                   XREF[1]:     14002adf1(j)  
       14002ada0 c5 fe 6f        VMOVDQU    YMM6,ymmword ptr [RBX + RAX*0x1 + 0x1580]
                 b4 03 80 
                 15 00 00
       14002ada9 c5 dd fe db     VPADDD     YMM3,YMM4,YMM3
       14002adad c5 cd f6 f8     VPSADBW    YMM7,YMM6,YMM0
       14002adb1 c5 dd fe e7     VPADDD     YMM4,YMM4,YMM7
       14002adb5 c4 e2 4d        VPMADDUBSW YMM6,YMM6,YMM1
                 04 f1
       14002adba c5 cd f5 f2     VPMADDWD   YMM6,YMM6,YMM2
       14002adbe c5 cd fe ed     VPADDD     YMM5,YMM6,YMM5
       14002adc2 48 85 c0        TEST       RAX,RAX
       14002adc5 0f 84 25        JZ         LAB_14002acf0
                 ff ff ff
       14002adcb c5 fe 6f        VMOVDQU    YMM6,ymmword ptr [RBX + RAX*0x1 + 0x15a0]
                 b4 03 a0 
                 15 00 00
       14002add4 c5 dd fe db     VPADDD     YMM3,YMM4,YMM3
       14002add8 c5 cd f6 f8     VPSADBW    YMM7,YMM6,YMM0
       14002addc c5 dd fe e7     VPADDD     YMM4,YMM4,YMM7
       14002ade0 c4 e2 4d        VPMADDUBSW YMM6,YMM6,YMM1
                 04 f1
       14002ade5 c5 cd f5 f2     VPMADDWD   YMM6,YMM6,YMM2
       14002ade9 c5 cd fe ed     VPADDD     YMM5,YMM6,YMM5
       14002aded 48 83 c0 40     ADD        RAX,0x40
       14002adf1 eb ad           JMP        LAB_14002ada0
```
Rust loop is cloned once, but you can see that it does almost no memory moves, and so it's 2.5x times faster than my C# implementation.

To optimize this case I think JIT should in optimization phase assess the code to not do any direct manipulation with vector data allocated in stack and, if so, move the vector variables into YMM registers, especially in loops, and move the data from vector registers back into stack if necessary.

### LINKED ISSUE #89456: JIT: Local morph GetElement/WithElement handling for Vector3 does not handle larger SIMD sources
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
private static Vector3 Foo(Vector256<byte> v)
{
    return Unsafe.As<Vector256<byte>, Vector3>(ref v);
}
```
Result:
```scala
Assert failure(PID 27156 [0x00006a14], Thread: 46384 [0xb530]): Assertion failed 'genTypeSize(varDsc) == 16' in 'Program:Foo(System.Runtime.Intrinsics.Vector256`1[ubyte]):System.Numerics.Vector3' during 'Morph - Structs/AddrExp' (IL size 13; hash 0xf577d4ba; FullOpts)

    File: C:\dev\dotnet\runtime\src\coreclr\jit\lclmorph.cpp Line: 948
    Image: C:\dev\dotnet\runtime4\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
While it's not generally expected that halves can be accessed directly (ending up with `LCL_FLD`), it sometimes happens in some of the SW implementations of Vector256/Vector512 methods. In rare cases the JIT still falls back to these even with there is HW acceleration.
In those cases we want to avoid DNER'ing the involved locals, so expand the existing recognition with these patterns.

Also add a check to the existing SIMD16 -> SIMD12 to verify the source is a SIMD16.

Fix #85359
Fix #89456

Some size wise regressions are expected, which come down to
* A large number of similar looking tests end up now enregistering some locals that cause new upper half saves/restores to be required. This accounts for most of the size-wise regressions.
* The expansions often do not result in smaller code because loading/storing the halves directly from/to stack is smaller code than the vector equivalent with extraction/insertion.

Many of the regressions are in SW implementations of Vector256/Vector512 methods that we usually do not expect to see called with HW acceleration supported.

### CODE REVIEW

File: src/coreclr/jit/lclmorph.cpp [hunk 1]
```diff
@@ -936,18 +936,51 @@ class LocalAddressVisitor final : public GenTreeVisitor<LocalAddressVisitor>
...
+                    }
+                    case TYP_SIMD12:
+                    {
+                        assert(genTypeSize(varDsc) == 16);
+                        hwiNode = m_compiler->gtNewSimdHWIntrinsicNode(elementType, lclNode, NI_Vector128_AsVector3,
+                                                                       CORINFO_TYPE_FLOAT, 16);
+                        break;
+                    }
+#if defined(FEATURE_SIMD) && defined(TARGET_XARCH)
+                    case TYP_SIMD16:
```
Comment (tannergooding) [inline src/coreclr/jit/lclmorph.cpp:956]: Do we need to handle `TYP_SIMD16` for `Arm64` since it has `TYP_SIMD8` (`Vector64<T>`) fields?

File: src/coreclr/jit/lclmorph.cpp [hunk 2]
```diff
@@ -1125,11 +1192,17 @@ class LocalAddressVisitor final : public GenTreeVisitor<LocalAddressVisitor>
                 }
                 else if (indir->TypeIs(TYP_SIMD12))
                 {
-                    if ((offset == 0) && m_compiler->IsBaselineSimdIsaSupported())
+                    if ((offset == 0) && (varDsc->TypeGet() == TYP_SIMD16) && m_compiler->IsBaselineSimdIsaSupported())
```
Comment (tannergooding) [inline src/coreclr/jit/lclmorph.cpp:1195]: We could adjust this to handle `TYP_SIMD32`/`TYP_SIMD64` if desired, correct? Just not worth it as part of this PR?

Comment (jakobbotsch) [reply src/coreclr/jit/lclmorph.cpp:1195]: Yeah, let's leave that for a separate PR if desired. This was just a drive-by fix for #89456.

File: src/coreclr/jit/lclmorph.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lclmorph.cpp:957]: Sure, I've added it for consistency.
On a side note I've also removed the quarter handling since it had no diffs and hence no coverage. I think if we want that we should add it as a separate PR that also adds some adequate testing.

Comment (tannergooding) [reply src/coreclr/jit/lclmorph.cpp:957]: With it removed, would we assert if some code did hit that code path?

Or is that mostly limited by the fact that our software fallbacks primarily defer to the next narrower size's implementation, which will be intrinsic on hardware  that does support the current size?

File: src/coreclr/jit/lclmorph.cpp [hunk 3]
```diff
@@ -936,18 +936,45 @@ class LocalAddressVisitor final : public GenTreeVisitor<LocalAddressVisitor>
...
+                        {
+                            assert(offset == genTypeSize(elementType));
+                            hwiNode = m_compiler->gtNewSimdGetUpperNode(elementType, lclNode, CORINFO_TYPE_FLOAT,
+                                                                        genTypeSize(varDsc));
+                        }
+
+                        break;
+                    }
+                    default:
+                        unreached();
```
Comment (tannergooding) [inline src/coreclr/jit/lclmorph.cpp:977]: Are we confident that `unreached()` is "correct" here or can/should we simply bail out of the transformation?

The main consideration would probably be that `Vector<T>` and `Vector64<T>` are backed by `ulong` fields. That shouldn't normally be an issue, but with all the various `Unsafe.As/BitCast` and other tricks, I'm not positive its not possible to see something here still.

**Review by tannergooding — APPROVED** [review]
LGTM. 

Left a couple questions around certainty the unreached/assertions are "safe" given the various bitcasts and such we could encounter.

Size regression is primarily in tests and won't really impact the real world code most users see. The overall codegen is better (removing two stores) and while there is some more we could do, its a step in the right direction.

-- We do probably want to check the perf scores at some point since its showing the 2x `insert` (`3 cycles, 1tp, 1uop, 1port` each) is 1 cycle slower than the 2x stores (`<11 cycles, 0.5-1tp, 1-2 uops, 2 ports` each)

File: src/coreclr/jit/lclmorph.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lclmorph.cpp:957]: > With it removed, would we assert if some code did hit that code path?

No, this code is tied together with the code in `SelectLocalIndirTransform`. I added some code there to compensate -- it only returns `GetElement`/`WithElement` for halves.

File: src/coreclr/jit/lclmorph.cpp (hunk 3 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lclmorph.cpp:977]: I think it's fine -- `SelectLocalIndirTransform` only returns `WithElement`/`GetElement` for the cases that we can handle here.
