### PR TITLE
[wasm][debugger] Enable onCallFrame evaluation of static fields in classes/interfaces from a static method.

### LINKED ISSUE #70135: [wasm][debugger] Enable onCallFrame evaluation of static fields in classes/interfaces from a static method.
Static fields evaluation works only in an instance method. Otherwise, we have to address the field with the fill namespace. It should not be required as the field belongs to locals.

- [x]  Static fields in DIMs:

Reproduction steps:
in interface `IDefaultInterface` in *src\mono\wasm\debugger\tests\debugger-test\debugger-test.cs* we have a static field: `defaultInterfaceMember`. Its visibility in interface's method is tested in `EvaluateLocalsInDefaultInterfaceMethodStatic`.

Current behavior:
When we use`EvaluateOnCallFrameAndCheck` with `defaultInterfaceMember` as evaluated value inside of interface's method, it fails. We would need to pass the full name: `IDefaultInterface.defaultInterfaceMember` to get the right value. In this location we should have access to the static fields without referencing to it with a full name.

Expected behavior:
`EvaluateOnCallFrameAndCheck` with `defaultInterfaceMember` passed (without interface name) should result in *"defaultInterfaceMember"*.

- [x]  Static fields in a static class evaluated from a static method of this class.
- [x]  Static fields in an instance class, evaluated from a static method of this class.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/70135.

Read commit history to understand the changes.

Changes:
- Adding prefix of current stack frame's namespace when trying to evaluate a static. This fixes among others: DIM problem where we did not see statics of the Interface from inside the DIM.
- Structuring struct tests and renaming them, it was a bit messy before.

### CODE REVIEW

**Review by thaystg — APPROVED** [review]

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 1]
```diff
@@ -123,6 +143,12 @@ public async Task<(JObject containerObject, ArraySegment<string> remaining)> Res
                 typeId = await FindStaticTypeId(classNameToFind);
             }
 
+            string StripAsyncPartOfFullName(string fullName)
+            {
+                // async function full name has a form: namespaceName.<currentFrame'sMethodName>d__integer
+                return fullName.Split(".<")[0];
+            }
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:150]:
```suggestion
             // async function full name has a form: namespaceName.<currentFrame'sMethodName>d__integer
            static string StripAsyncPartOfFullName(string fullName) => fullName.Split(".<")[0];
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 2]
```diff
@@ -86,8 +86,28 @@ public async Task<(JObject containerObject, ArraySegment<string> remaining)> Res
             if (methodInfo == null)
                 return (null, null);
 
+            string[] parts;
+            if (includeFullName)
+            {
+                string fullName = methodInfo.IsAsync == 0 ? methodInfo.TypeInfo?.FullName : StripAsyncPartOfFullName(methodInfo.TypeInfo?.FullName);
+                string[] fullNameParts = fullName.Split(".", StringSplitOptions.TrimEntries);
+                int overlappingPartIdx = Enumerable.Range(0, fullNameParts.Length).LastOrDefault(i => fullNameParts[i] == expressionParts[0]);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:94]: `LastOrDefault` here will be using only the parts that matched, not all. Is that the intention?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 3]
```diff
@@ -86,8 +86,28 @@ public async Task<(JObject containerObject, ArraySegment<string> remaining)> Res
...
+                if (overlappingPartIdx == 0)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:95]: Wouldn't it return `0`, if `fullNameParts[0]` matched OR if nothing matched?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 4]
```diff
@@ -86,8 +86,28 @@ public async Task<(JObject containerObject, ArraySegment<string> remaining)> Res
...
+                {
+                    // default val was returned for overlappingPartIdx
+                    overlappingPartIdx = fullNameParts.Length;
+                }
+                parts = new string[fullNameParts[..overlappingPartIdx].Length + expressionParts.Count];
+                Array.Copy(fullNameParts[..overlappingPartIdx], parts, fullNameParts[..overlappingPartIdx].Length);
+                Array.Copy(expressionParts.Array, 0, parts, fullNameParts[..overlappingPartIdx].Length, expressionParts.Count);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:102]: This is very unclear.

File: src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs [hunk 5]
```diff
@@ -1442,6 +1461,36 @@ public static void Run()
     }
 }
 
+public static class NestedWithSameNames
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs:1464]: I added some members:
```csharp
public static class NestedWithSameNames
{
    public static int StaticField1 = 30;
    public static string StaticProperty1 => "StaticProperty3";
    public static string StaticPropertyWithError => throw new Exception("not implemented V3");

    public static class B
    {
        public static int StaticField1 = 60;
        public static string StaticProperty1 => "StaticProperty6";
        public static string StaticPropertyWithError => throw new Exception("not implemented V6");

        public static class NestedWithSameNames
        {
            public static class B
            {
                public static int NestedWithSameNames = 90;
                public static int StaticField1 = 40;
                public static string StaticProperty1 => "StaticProperty4";
                public static string StaticPropertyWithError => throw new Exception("not implemented V4");

                public static void Run()
                {
                    var a = 0;
                }
            }
        }

        public static class NestedWithDifferentName
        {
            public static class B
            {
                //public static int NestedWithSameNames = 90;
                public static int StaticField1 = 70;
                public static string StaticProperty1 => "StaticProperty7";
                public static string StaticPropertyWithError => throw new Exception("not implemented V7");

                public static void Run()
                {
                    var a = 0;
                }
            }
        }
    }

    public static void Evaluate()
    {
        B.NestedWithSameNames.B.Run();
    }
}
```

.. which breaks one of the tests. Also, you can add a few more like:
`NestedWithSameNames.B.NestedWithDifferentName.B.StaticProperty1`, `NestedWithSameNames.B.NestedWithSameNames.B.StaticField1`, `B.NestedWithDifferentName.B.StaticProperty1`.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 2 above)
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:94]: Also, this is trying to match starting at the first part of the full name, but I think going from inside to out might be correct. Can you figure out a test to check whether I'm correct or not?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 6]
```diff
@@ -138,20 +164,37 @@ async Task<JObject> FindStaticMemberInType(string classNameToFind, string name,
...
+                    {
+                        var staticFieldValue = await context.SdbAgent.GetFieldValue(typeId, field.Id, token);
+                        var valueRet = await GetValueFromObject(staticFieldValue, token);
+                        // we need the full name here
+                        valueRet["className"] = classNameToFind;
+                        return valueRet;
+                    }
+                    catch (Exception ex)
+                    {
+                        logger.LogDebug(ex, $"Failed to get value of field {field.Name} on {classNameToFind} " +
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:177]: I didn't see any thing fail if I removed this catch. Can you add tests to cover this, and the other new try/catch?

**Review by radical — DISMISSED** [review]

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 2 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:94]: Yes, we need here the last part of full name that is the same as the root of the user's expression. Let's assume the expression is: `c.b.a` and we are checking if it has a part overlapping with full name: `e.d.c.b`. The expected result would be index of "c" in the full name, so that we can take everything that is before "c": `e.d` and prefix it to the user's expresssion: `e.d.c.b.a`. So yes, we are interested only in elements that are equal to "c" in this case.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 3 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:95]: Yes, if it matched for the 0th index then we can take the whole `fullNameParts` into consiferation. If there's no match it's the same story - we are interested in the whole `fullNameParts` to be our prefix. I thought that if I write 
```
// default val was returned for overlappingPartIdx
```
it would be understandable but maybe I'll change for: 
```
// either whole expression overlap or nothing matched and default value was returned
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 4 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:102]: I'll try to do sth about it.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 6 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:177]: That's strange. For me without this catch `DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "")` is failing. It's an old test, not from this PR.

**Comment by ilonatommy** [comment]
Converting to draft till the PR won't be divided into: fixed errors in old test changes + new tests PR (here) and test refactoring to bundle them more nicely together in a separate PR.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 4 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:102]: Removed.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 2 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:94]: Change into looping.
