### PR TITLE
#98551 - Regression in DI scope validation

### LINKED ISSUE #98551: Possible DependencyInjection service scope validation regression, blocking dependency flow into dotnet/aspnetcore
### Description

The automated dependency update PR from `runtime` to `aspnetcore` is currently failing: https://github.com/dotnet/aspnetcore/pull/54055

Two tests are failing:

 * `WebApplicationBuilder_EnablesServiceScopeValidationByDefaultInDevelopment` (https://github.com/dotnet/aspnetcore/blob/9db62024cbe3c3cb28efe372541fc1bdfcdb375e/src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs#L1784)
 * `Build_InDevelopment_ConfiguresWithServiceProviderWithScopeValidation` (https://github.com/dotnet/aspnetcore/blob/9db62024cbe3c3cb28efe372541fc1bdfcdb375e/src/Components/WebAssembly/WebAssembly/test/Hosting/WebAssemblyHostBuilderTest.cs#L95)

In both cases the failure is of the form "expected an exception to be thrown, but no exception was thrown". Example of failing build: https://github.com/dotnet/aspnetcore/runs/21630956214

I notice that this started after https://github.com/dotnet/runtime/pull/96254 was merged 2 days ago, and that PR changes the logic around service scope validation. The PR is not meant to affect the behavior (since it's only intended to add caching) but perhaps it does affect the behavior.

### Reproduction Steps

Example of failing build: https://github.com/dotnet/aspnetcore/runs/21630956214

### Expected behavior

Service scope validation behavior should be unchanged.

### Actual behavior

It no longer throws at the same time that it did before.

### Regression?

The behavior was correct in commit ad25468103550b322351efb21a45fb54566a8127, which is the last one we successfully ingested to `dotnet/aspnetcore`. The change must have happened since then.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by christiaanderidder**
Fixes #98551

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteValidator.cs [hunk 1]
```diff
@@ -41,18 +41,27 @@ public void ValidateResolution(ServiceCallSite callSite, IServiceScope scope, IS
...
-            // Walk the tree
-            Type? scoped = base.VisitCallSite(callSite, argument);
+                // Cache the result
+                _scopedServices[callSite.Cache.Key] = firstScopedServiceInCallSiteTree;
+            }
 
-            // Store the result for each visited service
-            _scopedServices[callSite.Cache.Key] = scoped;
+            // If there is a scoped service in the call site tree, make sure we are not resolving it from a singleton
+            if (firstScopedServiceInCallSiteTree != null && argument.Singleton != null)
```
Comment (steveharter) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteValidator.cs:54]: @benjaminpetit PTAL

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderValidationTests.cs [hunk 2]
```diff
@@ -239,6 +239,84 @@ public void GetService_DoesNotThrow_WhenGetServiceForNonScopedImplementationWith
...
+        [Fact]
+        public void BuildServiceProvider_ValidateOnBuild_Throws_WhenScopedIsInjectedIntoSingleton()
+        {
+            // Arrange
+            var serviceCollection = new ServiceCollection();
+            serviceCollection.AddScoped<IBar, Bar>();
+            serviceCollection.AddSingleton<IFoo, Foo>();
+
+            // Act + Assert
+            var aggregateException = Assert.Throws<AggregateException>(() => serviceCollection.BuildServiceProvider(new ServiceProviderOptions() { ValidateOnBuild = true, ValidateScopes = true }));
```
Comment (steveharter) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderValidationTests.cs:251]: I assume without the fix here, that no exception was thrown here.

**Review by steveharter — APPROVED** [review]
LGTM; waiting a bit for others to comment.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderValidationTests.cs (hunk 2 above)
Comment (christiaanderidder) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderValidationTests.cs:251]: An exception was thrown here, but not in the case with the reversed order. The aspnet core repo happens to test the reverse order scenario. This happened because in the previous code, the scoped-in-singleton check was not performed if a callsite was already cached. See here as well: https://github.com/dotnet/runtime/issues/98551#issuecomment-1952177976

**Review by benjaminpetit — APPROVED** [review]

**Comment by carlossanlop** [comment]
We need this backported to release/9.0-preview2, it's blocking the build. 

@steveharter @benjaminpetit can you please validate the CI failure?

**Comment by carlossanlop** [comment]
The CI failure seems pre-existing: https://github.com/dotnet/runtime/issues/98406

It's been signed-off by area owners so I'll go ahead and merge, then backport.

**Comment by hoyosjs** [comment]
@carlossanlop that's https://github.com/dotnet/runtime/issues/98406. Build analysis is green.

**Comment by carlossanlop** [comment]
> LGTM; waiting a bit for others to comment.

@steveharter please help keep an eye on this later.
