### PR TITLE
Fixing MetricEventSource tests

### LINKED ISSUE #55315: Test failure:System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesTimeSeriesWithMetadata
Run: [runtime 20210707.124](https://dev.azure.com/dnceng/public/_build/results?buildId=1225692&view=ms.vss-test-web.build-test-results-tab&runId=36531372&resultId=123413&paneView=debug)
Failed test:
```
net6.0-Linux-Release-arm64-CoreCLR_checked-(Alpine.312.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-arm64v8-20200602002604-25f8a3e

- System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesTimeSeriesWithMetadata

```
**Error message**
```
Unexpected Error event: An error occurred when writing to a listener.
at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(EventWrittenEventArgs eventCallbackArgs) in //src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs:line 2126
at System.Diagnostics.Tracing.EventSource.WriteEventVarargs(Int32 eventId, Guid* childActivityID, Object[] args) in //src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs:line 1989
at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, Object[] args) in //src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs:line 1399
at System.Diagnostics.Metrics.MetricsEventSource.CollectionStop(String sessionId, DateTime intervalStartTime, DateTime intervalEndTime) in //src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:line 92
at System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.<>c__DisplayClass2_0.<OnEventCommand>b__2(DateTime startIntervalTime, DateTime endIntervalTime) in //src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:line 299
at System.Diagnostics.Metrics.AggregationManager.CollectWorker(CancellationToken cancelToken) in //src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/AggregationManager.cs:line 196
Expected: True
Actual:   False


Stack trace
   at System.Diagnostics.Metrics.Tests.MetricsEventListener.AssertOnError() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 1005
   at System.Diagnostics.Metrics.Tests.MetricsEventListener.GetCountCollectionStops() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 1014
   at System.Diagnostics.Metrics.Tests.MetricsEventListener.WaitForCollectionStop(TimeSpan timeout, Int32 numStops) in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 937
   at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourcePublishesTimeSeriesWithMetadata() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 75
```

### PR DESCRIPTION
**Pull request by noahfalk**
I've seen two recent non-deterministic failures:
1. After starting the EventListener there is a delay of one collection
interval (currently 0.3 seconds) where we expect calls to counter.Add
and Histogram.Record() to update stats. On a fast machine this code
would run in well under a millisecond but in some test runs it still wasn't
happening fast enough.
2. We were seeing error events from a previous test get observed in a
later test because session id was being ignored for error events.

Fixes:
1. Added an initial collection interval where no counter APIs will be
invoked and the test will delay up to 5 seconds waiting for this.
Hopefully this delay makes it more likely that the Add/Record APIs
are ready to execute promptly once the 2nd interval begins. If that
still isn't sufficient we can either increase the collection intervals or
disable the tests.
2. Tightened up the session id matching so only error events with
empty id or the expected id are allowed.

Fixes #55315 and #55313 (I hope)

### CODE REVIEW

**Comment by noahfalk** [comment]
@tarekgh 
cc @dotnet/dotnet-diag

**Comment by stephentoub** [comment]
> Added an initial collection interval where no counter APIs will be
invoked and the test will delay up to 5 seconds waiting for this.
Hopefully this delay makes it more likely that the Add/Record APIs
are ready to execute promptly once the 2nd interval begins. If that
still isn't sufficient we can either increase the collection intervals or
disable the tests.

Am I understanding correctly that we expect these events to occur and if they don't the test is meant to fail?  If that's the case, I recommend using a much larger timeout than 5 seconds.  Elsewhere we generally use at least 30 if not 60 seconds in such cases: such values are much more tolerant of load in CI, you only end up paying the full time if the test is going to fail anyway, and if even occurs later in that timeframe, it's better to have spent the extra time to make the test succeed rather than having flaky tests.

**Comment by noahfalk** [comment]
> Am I understanding correctly that we expect these events to occur and if they don't the test is meant to fail?

Yep, that is correct. I can change 5 sec -> 60 sec.

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs [hunk 1]
```diff
@@ -16,13 +16,16 @@ namespace System.Diagnostics.Metrics.Tests
...
+        static readonly double s_intervalSecs = 1;
+        static readonly TimeSpan s_waitForEventTimeout = TimeSpan.FromSeconds(60);
 
         public MetricEventSourceTests(ITestOutputHelper output)
         {
             _output = output;
         }
 
         [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotBrowser))]
+        [OuterLoop("Slow and has lots of console spew")]
```
Comment (tarekgh) [inline src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:28]: >OuterLoop [](http://example.com/codeflow?start=9&length=9)

Thanks for adding this :-)

**Comment by tarekgh** [comment]
I am seeing you have added outer loop attribute to some test, do you want enable CI run the outer loops tests?

**Comment by tarekgh** [comment]
@noahfalk do you think this may help with https://github.com/dotnet/runtime/issues/55313 too?

**Review by tarekgh — APPROVED** [review]
LGTM. I hope you enable the outerloop tests before you merge to ensure running the touched tests. Thanks

**Comment by noahfalk** [comment]
> I am seeing you have added outer loop attribute to some test, do you want enable CI run the outer loops tests?

I don't care if every PR runs them, as long as they run periodically. Were you saying that as-is the automation will never run them (in which case I want to change it), or that they won't run on every PR (which I am fine with)?

**Comment by noahfalk** [comment]
> @noahfalk do you think this may help with #55313 too?

Yes I am hopeful it will resolve both of the issues. I edited the issue description at the top to include it. Thanks!

**Comment by stephentoub** [comment]
Outerloop doesn't run on any PR by default; you have to ask the bot to run the legs via a comment on a PR. Outerloop does run on various rolling builds daily.

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs [hunk 2]
```diff
@@ -16,13 +16,16 @@ namespace System.Diagnostics.Metrics.Tests
     public class MetricEventSourceTests
     {
         ITestOutputHelper _output;
+        static readonly double s_intervalSecs = 1;
+        static readonly TimeSpan s_waitForEventTimeout = TimeSpan.FromSeconds(60);
```
Comment (stephentoub) [inline src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:20]: Nits:
- These should be explicitly `private`
- s_intervalSecs should be a const rather than static readonly, and should be named IntervalSecs

**Review by stephentoub — APPROVED** [review]

**Comment by noahfalk** [comment]
> Outerloop doesn't run on any PR by default; you have to ask the bot to run the legs via a comment on a PR. Outerloop does run on various rolling builds daily.

Thanks, that sounds like a fine state of affairs for the tests I marked as outerloop.

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs (hunk 2 above)
Comment (noahfalk) [reply src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs]: fixed
