### PR TITLE
Print specific error when framework in runtimeconfig.json is missing a version

### LINKED ISSUE #3743: Missing version in framework reference leads to misleading error
New console app with framework reference to `Microsoft.NETCore.App`, remove the `version` property from `.runtimeconfig.json`, run the app:

Fails with:
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App' was not found.
  - The following frameworks were found:
    <list of frameworks on the machine>
```

Running this on a Debug build causes an assert in `fx_resolver`.

We should explicitly check for this and fail with a meaningful error message. It's not valid to have a framework reference without version.

### PR DESCRIPTION
**Pull request by elinor-fung**
Error should now call out the invalid runtimeconfig.json (rather than just failing to find a matching version later):
```
Framework '<name>' is missing a version.
Invalid runtimeconfig.json [<path>]
```

Resolves #3743

cc @dotnet/appmodel @AaronRobinsonMSFT

### CODE REVIEW

File: src/native/corehost/fxr/hostfxr.cpp [hunk 1]
```diff
@@ -623,7 +623,12 @@ SHARED_API int32_t HOSTFXR_CALLTYPE hostfxr_resolve_frameworks_for_runtime_confi
     const runtime_config_t::settings_t override_settings;
     app->parse_runtime_config(runtime_config, _X(""), override_settings);
 
-    const runtime_config_t app_config = app->get_runtime_config();
+    const runtime_config_t& app_config = app->get_runtime_config();
+    if (!app_config.is_valid())
```
Comment (AaronRobinsonMSFT) [inline src/native/corehost/fxr/hostfxr.cpp:627]: What was previously happening here? Was this the "silent failure" case discussed offline?

Comment (elinor-fung) [reply src/native/corehost/fxr/hostfxr.cpp:627]: This is different from what we were discussing offline (global.json is not involved here). For this particular API (`hostfxr_resolve_frameworks_for_runtime_config`, not part of normal app run), it depends on why exactly the config is invalid:
- malformed JSON or unexpected values (for example, runtimeOptions specified at all): success with no frameworks resolved
- framework missing name or version: FrameworkMissingFailure

For the normal app run case, malformed or unexpected JSON already failed InvalidConfigFile.

File: src/native/corehost/runtime_config.cpp [hunk 2]
```diff
@@ -359,23 +371,11 @@ bool runtime_config_t::ensure_dev_config_parsed()
...
-            break;
-        }
-
-        if (fx_out.get_fx_name().length() == 0)
-        {
-            trace::verbose(_X("No framework name specified."));
-            rc = false;
-            break;
-        }
+        if (!parse_framework(fx_json, fx_out, name_and_version_only))
```
Comment (AaronRobinsonMSFT) [inline src/native/corehost/runtime_config.cpp]: Nit: I would expect this API to have `fx_out` as the last param and the `name_and_version_only` be grouped with the "in" parameters. I see this is also done in this function, so I guess "okay". Ideally at some point in the future this could be changed?

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/native/corehost/runtime_config.cpp (hunk 2 above)
Comment (elinor-fung) [reply src/native/corehost/runtime_config.cpp]: `name_and_version_only` is optional, so I think the current order makes sense.

Whether it makes sense for `name_and_version_only` to be optional is another matter 🙂
