### PR TITLE
[wasm] Unmanaged structs are considered blittable if module has `DisableRuntimeMarshallingAttribute`

### LINKED ISSUE #61146: (Unmanaged) Structs are not considered blittable by Emscripten / Blazor WASM AOT
### Description

Unmanaged structs are not considered blittable and therefore cannot be used in pinvoke callbacks.

### Reproduction Steps

Attempt to compile code like
```cs
public struct S { public int Value; }

[UnmanagedCallersOnly]
public void M(S myStruct) { }
```
using Emscripten / WASM AOT

### Expected behavior

The above code should compile.

### Actual behavior

An error is shown, structs are not considered blittable.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

Tested on .NET 6 RC2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by maraf**
Consider all types in pinvokes from assembly marked with `DisableRuntimeMarshallingAttribute` as blittable.
Based on API proposal in https://github.com/dotnet/runtime/issues/60639.

- PInvokeTableGenerator: Avoid crash when processing unmanaged callbacks with function pointers.

Fixes #61146.

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
This is not entirely true. An unmanaged struct defined in an assembly with DisableRuntimeMarshalling isn't necessarily blittable if it is used in a P/Invoke in an assembly without DisableRuntimeMarshallingAttribute.

**Comment by maraf** [comment]
> This is not entirely true. An unmanaged struct defined in an assembly with DisableRuntimeMarshalling isn't necessarily blittable if it is used in a P/Invoke in an assembly without DisableRuntimeMarshallingAttribute.

Thanks!
Must both struct and p/invoke assemblies be marked with `DisableRuntimeMarshallingAttribute`?

**Comment by jkoritzinsky** [comment]
Only the P/Invoke assembly must be marked with the attribute.

**Review by maraf — COMMENTED** [review]
~~Look for the DisableRuntimeMarshallingAttribute on the assembly where pinvoke method is declared.~~
Mistake...

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs [hunk 1]
```diff
@@ -341,8 +341,12 @@ private static void EmitNativeToInterp(StreamWriter w, List<PInvokeCallback> cal
             MethodInfo method = cb.Method;
             bool isVoid = method.ReturnType.FullName == "System.Void";
 
+            if (method.DeclaringType != null && method.DeclaringType.Assembly.GetCustomAttributesData().Any(d => d.AttributeType.Name == "DisableRuntimeMarshallingAttribute"))
```
Comment (lambdageek) [inline src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:344]: Probably doesn't matter too much, but maybe we can keep a cache for each assembly if it has the marshaling attribute?

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs [hunk 2]
```diff
@@ -115,6 +115,43 @@ public static int Main()
             Assert.Contains("Main running", output);
         }
 
+        [Theory]
+        [BuildAndRun(host: RunHost.Chrome)]
+        public void UnmanagedStructsAreConsideredBlittable(BuildArgs buildArgs, RunHost host, string id)
```
Comment (radical) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:120]: And one variation of the test without the attribute.

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs [hunk 3]
```diff
@@ -115,6 +115,43 @@ public static int Main()
...
+
+            [assembly: DisableRuntimeMarshalling]
+
+            public class Test
+            {
+                public static int Main()
+                {
+                    var x = new S { Value = 5 };
+            
+                    Console.WriteLine("Main running " + x.Value);
```
Comment (radical) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:136]: This is using the value from the local struct. Can we call `M(..)`?

Comment (radical) [reply src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:136]: err.. get a callback?

Comment (maraf) [reply src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:185]: The error comes from the build. I'm using the struct it just don't get trimmed.

**Comment by maraf** [comment]
Failures are not relevant.

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs (hunk 3 above)
Comment (radical) [reply src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:187]: It would test whether we generated a good signature for it, right?

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs [hunk 4]
```diff
@@ -457,6 +461,16 @@ private static void EmitNativeToInterp(StreamWriter w, List<PInvokeCallback> cal
         w.WriteLine("};");
     }
 
+    private Dictionary<Assembly, bool> assemblyDisableRuntimeMarshallingAttributeCache = new Dictionary<Assembly, bool>();
```
Comment (radical) [inline src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:464]:
```suggestion
    private Dictionary<Assembly, bool> _assemblyDisableRuntimeMarshallingAttributeCache = new ();
```

And move this to the top, with the other fields.

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs [hunk 5]
```diff
@@ -457,6 +461,16 @@ private static void EmitNativeToInterp(StreamWriter w, List<PInvokeCallback> cal
...
+
+    private bool HasAssemblyDisableRuntimeMarshallingAttribute(Assembly assembly)
+    {
+        if (!assemblyDisableRuntimeMarshallingAttributeCache.TryGetValue(assembly, out var value))
+            assemblyDisableRuntimeMarshallingAttributeCache[assembly] = value = assembly.GetCustomAttributesData().Any(d => d.AttributeType.Name == "DisableRuntimeMarshallingAttribute");
```
Comment (radical) [inline src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:469]:
```suggestion
            assemblyDisableRuntimeMarshallingAttributeCache[assembly]
            		= value = assembly.GetCustomAttributesData()
            								.Any(d => d.AttributeType.Name == nameof(DisableRuntimeMarshallingAttribute));
```

nit: Change the indentation here as you want, just preferably with shorter lines.

Comment (radical) [reply src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:469]: oops, I added tabs in that.

**Comment by radical** [comment]
> Only the P/Invoke assembly must be marked with the attribute.

We need a test that covers this case also. The tests in the PR right now, have the struct, and the pinvoke are in the same assembly.

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs (hunk 3 above)
Comment (maraf) [reply src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:187]: Yes, when it succeeds it doesn't produce any warning.

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs [hunk 6]
```diff
@@ -14,6 +14,7 @@
 internal sealed class PInvokeTableGenerator
 {
     private static readonly char[] s_charsToReplace = new[] { '.', '-', '+' };
+    private Dictionary<Assembly, bool> _assemblyDisableRuntimeMarshallingAttributeCache = new Dictionary<Assembly, bool>();
```
Comment (radical) [inline src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:17]:
```suggestion
    private Dictionary<Assembly, bool> _assemblyDisableRuntimeMarshallingAttributeCache = new ();
```

**Comment by maraf** [comment]
Failures doesn't seem relevant.

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73310-merge-6827ac8318034a2eb2/Workloads-.WasmTemplateTests/1/console.88ad2f22.log?helixlogtype=result

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs [hunk 7]
```diff
@@ -119,6 +119,198 @@ public static int Main()
...
+                    InitProject: () =>
+                    {
+                        File.WriteAllText(Path.Combine(_projectDir!, "S.cs"), code);
+                    },
+                    Publish: buildArgs.AOT,
+                    DotnetWasmFromRuntimePack: false,
+                    AssertAppBundle: false
+                )
+            );
+
```
Comment (radical) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:262]:
```suggestion
```

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs [hunk 8]
```diff
@@ -119,6 +119,198 @@ public static int Main()
             Assert.Contains("Main running", output);
         }
 
+        [Theory]
+        [BuildAndRun(host: RunHost.None)]
+        public void UnmanagedStructsAreNotConsideredBlittable(BuildArgs buildArgs, string id)
```
Comment (radical) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:124]: The 3 tests seem to have lot of the same code. That can be moved to a separate method.

Comment (radical) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:124]: Maybe `UnmanagedStructsWithoutDisableMarshallingAttributeAreNotConsideredBlittable`

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs [hunk 9]
```diff
@@ -119,6 +119,198 @@ public static int Main()
...
+
+            public struct S { public int Value; }
+
+            class Program
+            {
+                public static void Main()
+                {
+                    // Noop
+                }
+            }
```
Comment (radical) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:242]: This could be dropped, and built with `<OutputType>library</OutputType>`

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs [hunk 10]
```diff
@@ -119,6 +119,198 @@ public static int Main()
...
+                    ExpectSuccess: false
+                )
+            );
+
+            Assert.Matches("error.*Parameter.*types.*pinvoke.*.*blittable", output);
+        }
+
+        [Theory]
+        [BuildAndRun(host: RunHost.Chrome)]
+        public void UnmanagedStructsAreConsideredBlittable(BuildArgs buildArgs, RunHost host, string id)
```
Comment (radical) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:175]: The name should reflect what case this is, since there are multiple here.

The cases that should be covered IMHO, are:

1. Method, and struct in same assembly with no attribute
2. Separate assemblies - only Struct one has attribute
3. Separate assemblies - only method one has attribute
4. Separate assemblies - both have attribute
5. Separate assemblies - neither have the attribute

They are very similar, so having the test as a method which gets used by different cases, should make it easier to understand too.

Comment (radical) [reply src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:175]: I'll add them.

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs [hunk 11]
```diff
@@ -119,6 +119,195 @@ public static int Main()
...
+            return (buildArgs, output);
+        }
+
+        public static IEnumerable<object?[]> SeparateAssemblyWithDisableMarshallingAttributeTestData(string config)
+            => ConfigWithAOTData(aot: false, config: config).Multiply(
+                    new object[] { /*libraryHasAttribute*/ false, /*appHasAttribute*/ false, /*expectSuccess*/ false },
+                    new object[] { /*libraryHasAttribute*/ true, /*appHasAttribute*/ false, /*expectSuccess*/ false },
+                    new object[] { /*libraryHasAttribute*/ false, /*appHasAttribute*/ true, /*expectSuccess*/ true },
+                    new object[] { /*libraryHasAttribute*/ true, /*appHasAttribute*/ true, /*expectSuccess*/ true }
+                ).WithRunHosts(RunHost.V8).UnwrapItemsAsArrays();
```
Comment (radical) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:210]:
```suggestion
                ).WithRunHosts(RunHost.Chrome).UnwrapItemsAsArrays();
```

File: src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs [hunk 12]
```diff
@@ -119,6 +119,195 @@ public static int Main()
...
+                expectSuccess: false,
+                buildArgs,
+                id
+            );
+
+            Assert.Matches("error.*Parameter.*types.*pinvoke.*.*blittable", output);
+        }
+
+        [Theory]
+        [BuildAndRun(host: RunHost.V8)]
```
Comment (radical) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/PInvokeTableGeneratorTests.cs:138]:
```suggestion
        [BuildAndRun(host: RunHost.Chrome)]
```

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
The wasm EAT/AOT test failures are https://github.com/dotnet/runtime/issues/73932 .
The Perftracing build failure is https://github.com/dotnet/runtime/issues/73933 .

**Comment by radical** [comment]
The Linux_musl x64 coreclr failure is https://github.com/dotnet/runtime/issues/73930 .

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs [hunk 13]
```diff
@@ -460,6 +486,18 @@ private static void EmitNativeToInterp(StreamWriter w, List<PInvokeCallback> cal
         w.WriteLine("};");
     }
 
+    private bool HasAssemblyDisableRuntimeMarshallingAttribute(Assembly assembly)
+    {
+        if (!_assemblyDisableRuntimeMarshallingAttributeCache.TryGetValue(assembly, out var value))
+        {
+            _assemblyDisableRuntimeMarshallingAttributeCache[assembly] = value = assembly
+                .GetCustomAttributesData()
+                .Any(d => d.AttributeType.Name == "DisableRuntimeMarshallingAttribute");
```
Comment (kasperk81) [inline src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:495]: can use `nameof(DisableRuntimeMarshallingAttribute)` with `using System.Runtime.CompilerServices;`

Comment (maraf) [reply src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:495]: The assembly is also compiled for net47 and the attribute is not available there.
