### PR TITLE
[android] Enable exceptions smoke test

### LINKED ISSUE #121353: [naot][android] Exceptions smoke test fails with exit code 42
This test fails with:
```
11-03 22:05:54.669  4329  4329 I DOTNET  : SetEnv: DOTNET_CI = true
                 11-03 22:05:54.669  4329  4329 I DOTNET  : env:DOTNET_CI=true
                 11-03 22:05:54.669  4329  4329 I DOTNET  : SetEnv: TestExclusionListPath = TestExclusionList.txt
                 11-03 22:05:54.669  4329  4329 I DOTNET  : env:TestExclusionListPath=TestExclusionList.txt
                 11-03 22:05:54.678  4329  4348 I DOTNET  : Extracting asset to /data/user/0/net.dot.Exceptions/files/Exceptions.MergedTestAssembly.0.1.MergedTestAssemblyForStress
                 11-03 22:05:54.678  4329  4348 I DOTNET  : Extracting asset to /data/user/0/net.dot.Exceptions/files/runtimeconfig.bin
                 11-03 22:05:54.679  4329  4348 I DOTNET  : Extracting asset to /data/user/0/net.dot.Exceptions/files/Exceptions.runtimeconfig.json
                 11-03 22:05:54.679  4329  4348 I DOTNET  : Extracting asset to /data/user/0/net.dot.Exceptions/files/TestExclusionList.txt
                 11-03 22:05:54.680  4329  4348 I DOTNET  : Extracting asset to /data/user/0/net.dot.Exceptions/files/xunit-excludes.txt
                 11-03 22:05:54.681  4329  4348 I DOTNET  : Extracting asset to /data/user/0/net.dot.Exceptions/files/ExpectedExitCode.txt
                 11-03 22:05:54.682  4329  4348 I DOTNET  : Extracting asset to /data/user/0/net.dot.Exceptions/files/Exceptions.MergedTestAssembly
                 11-03 22:05:54.682  4329  4348 I DOTNET  : SetEnv: HOME = /data/user/0/net.dot.Exceptions/files
                 11-03 22:05:54.682  4329  4348 I DOTNET  : SetEnv: ASSETS_DIR = /data/user/0/net.dot.Exceptions/files
                 11-03 22:05:54.682  4329  4348 I DOTNET  : SetEnv: TMPDIR = /data/user/0/net.dot.Exceptions/cache
                 11-03 22:05:54.682  4329  4348 I DOTNET  : SetEnv: TEST_RESULTS_DIR = /storage/emulated/0/Android/data/net.dot.Exceptions/files/Documents
                 11-03 22:05:54.682  4329  4348 I DOTNET  : MonoRunner initializeRuntime, entryPointLibName=libExceptions.so
                 11-03 22:05:54.688  4329  4348 I DOTNET  : Initializing Android crypto native library
                 11-03 22:05:54.688  4329  4348 D DOTNET  : AndroidCryptoNative_InitLibraryOnLoad: jint AndroidCryptoNative_InitLibraryOnLoad(JavaVM *, void *) in /__w/1/s/src/native/libs/System.Security.Cryptography.Native.Android/pal_jni.c
                 11-03 22:05:54.689  4329  4348 D DOTNET  : GetOptionalClassGRef: optional class com/android/org/conscrypt/OpenSSLEngineImpl was not found
                 11-03 22:05:54.689  4329  4348 W .dot.Exception: Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, JNI, allowed)
                 11-03 22:05:54.713  4329  4348 I DOTNET  : MonoRunner finished, return-code=42
                 11-03 22:05:54.715  1909  4349 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
                 11-03 22:05:54.715  1909  4349 W Binder  : java.lang.Throwable
                 11-03 22:05:54.715  1909  4349 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
                 11-03 22:05:54.715  1909  4349 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
                 11-03 22:05:54.715  1909  4349 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
                 11-03 22:05:54.716  4319  4319 D AndroidRuntime: Shutting down VM
                 11-03 22:05:54.735  1909  1926 W Looper  : Slow dispatch took 104ms android.fg h=com.android.server.AppStateTracker$MyHandler c=null m=12
                 11-03 22:05:54.736  1909  1924 I ActivityManager: Force stopping net.dot.Exceptions appid=10122 user=0: finished inst
                 11-03 22:05:54.737  1909  1924 I ActivityManager: Killing 4329:net.dot.Exceptions/u0a122 (adj 0): stop net.dot.Exceptions
                 11-03 22:05:54.785  1669  1669 I Zygote  : Process 4329 exited due to signal 9 (Killed)
                 11-03 22:05:54.787  1909  1935 W ActivityManager: Error shutting down UiAutomationConnection
                 11-03 22:05:54.450  4319  4319 W app_process: type=1400 audit(0.0:95): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=6676 scontext=u:r:shell:s0 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0
                 11-03 22:05:54.460  4319  4319 I chatty  : uid=2000(shell) app_process identical 1 line
                 11-03 22:05:54.460  4319  4319 W app_process: type=1400 audit(0.0:97): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=6676 scontext=u:r:shell:s0 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0
                 11-03 22:05:54.800  1909  1937 I libprocessgroup: Successfully killed process cgroup uid 10122 pid 4329 in 53ms
                 11-03 22:05:54.803  1909  1934 I RoleUserState: Wrote roles.xml successfully
                 11-03 22:05:54.650  4329  4329 W .dot.Exceptions: type=1400 audit(0.0:98): avc: denied { read } for name="memory.use_hierarchy" dev="cgroup" ino=15 scontext=u:r:untrusted_app:s0:c122,c256,c512,c768 tcontext=u:object_r:cgroup:s0 tclass=file permissive=0 app=net.dot.Exceptions
                 11-03 22:05:54.650  4329  4329 W .dot.Exceptions: type=1400 audit(0.0:99): avc: denied { read } for name="memory.limit_in_bytes" dev="cgroup" ino=10 scontext=u:r:untrusted_app:s0:c122,c256,c512,c768 tcontext=u:object_r:cgroup:s0 tclass=file permissive=0 app=net.dot.Exceptions
                 11-03 22:05:56.190  1909  1928 I DropBoxManagerService: add tag=system_server_strictmode isTagEnabled=true flags=0x2
                 
[22:05:58] fail: Non-success instrumentation exit code: 42, expected: 100
```

Likely something is wrong with the `System.Runtime.GCSettings.IsServerGC` check.

### PR DESCRIPTION
**Pull request by eduardo-vp**
Similar to #73487, we should check the processor count. If it's a single processor, server GC is not enabled.

Fixes #121353.

### CODE REVIEW

File: src/tests/nativeaot/SmokeTests/Exceptions/Exceptions.cs [hunk 1]
```diff
@@ -26,14 +26,10 @@ public BringUpTest()
...
-        if (!OperatingSystem.IsAndroid())
-        {
-            // Disabled on Android due to https://github.com/dotnet/runtime/issues/121353
 
-            // This test also doubles as server GC test
-            if (!System.Runtime.GCSettings.IsServerGC)
-                return 42;
-        }
+        // This test also doubles as server GC test
+        if (Environment.ProcessorCount > 1 && !System.Runtime.GCSettings.IsServerGC)
```
Comment (jkotas) [inline src/tests/nativeaot/SmokeTests/Exceptions/Exceptions.cs:31]: Are the Android test machines or emulators really single core?

**Review by jkotas — APPROVED** [review]
In any case, the change is good

File: src/tests/nativeaot/SmokeTests/Exceptions/Exceptions.cs (hunk 1 above)
Comment (eduardo-vp) [reply src/tests/nativeaot/SmokeTests/Exceptions/Exceptions.cs:31]: I think so, I'm basing this change on this PR https://github.com/dotnet/runtime/pull/73487.

Comment (jkotas) [reply src/tests/nativeaot/SmokeTests/Exceptions/Exceptions.cs:31]: It is surprising since all phones are many-core these days. Are we sure they are single core? We may have a bug in the core count detection logic for Android.

Comment (eduardo-vp) [reply src/tests/nativeaot/SmokeTests/Exceptions/Exceptions.cs:31]: Ah I didn't think of that, I guess it makes sense to look into that
