### PR TITLE
[wasm][debugger] Hide members from classes that don't have debug information

### LINKED ISSUE #43184: Mono WASM debugger displays private members of base class alongside other properties
### Description

When debugging a Blazor WASM application on .NET 5 RC2, I noticed that the debugger populates the locals inspector with private properties from the `ComponentBase` base class.

Screen Shot 2020-10-08 at 12 12 11 PM

The extraneous values displayed are private book-keeping properties used by Blazor's base component class ([ref](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/ComponentBase.cs#L28-L33)). The class is defined as a public abstract class.
### Configuration

* .NET 5 RC 2 (5.0.0-rc.2.20475.17)
* Windows 10
* Visual Studio 16.8 Preview 3

### Regression?

This looks like a regression from 3.2. Setting a breakpoint at the same point in a 3.2 app does not surface the issue.

Screen Shot 2020-10-08 at 12 13 40 PM

### Other information

1. Install the above version of the SDK.
2. Create a new Blazor WASM project with .NET 5 in VS's project creation view.
3. Click `F5`.
4. Set a breakpoint in the `IncrementCount` method in the `Counter.razor` page and observe the issue.

### PR DESCRIPTION
**Pull request by thaystg**
Do not show members from classes that don't have debug information if JMC is enabled.

Fixes #43184

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs [hunk 1]
```diff
@@ -216,6 +217,10 @@ async Task<JArray> GetRootHiddenChildrenForProperty()
             if (getCommandOptions.HasFlag(GetObjectCommandOptions.ForDebuggerProxyAttribute))
                 fields = fields.Where(field => field.IsNotPrivate).ToList();
 
+            var typeInfo = await sdbHelper.GetTypeInfo(containerTypeId, token);
+            if (typeInfo.Info.IsNonUserCode && getCommandOptions.HasFlag(GetObjectCommandOptions.JustMyCode))
+                return fieldValues;
+
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:223]: Can this be at line 215?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs [hunk 2]
```diff
@@ -591,6 +594,11 @@ JObject GetNotAutoExpandableObject(int methodId, string propertyName, bool isSta
                 if (!getCommandType.HasFlag(GetObjectCommandOptions.WithProperties))
                     return GetMembersResult.FromValues(allMembers.Values, sortByAccessLevel);
 
+                var typeInfo = await sdbHelper.GetTypeInfo(typeId, token);
+
+                if (typeInfo.Info.IsNonUserCode && getCommandType.HasFlag(GetObjectCommandOptions.JustMyCode))
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:599]: Wouldn't this add fields for non-my-code types? Should it moved to the beginning of the loop?

File: src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs [hunk 3]
```diff
@@ -1275,3 +1275,18 @@ public static void MethodWithHiddenLinesAtTheEnd3()
...
+        var myVar = new ClassInheritsFromClassWithoutDebugSymbols();
+        myVar.CallMethod();
+    }
+
+    public void CallMethod()
+    {
+        System.Diagnostics.Debugger.Break();
+    }
+
+    public int myField;
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:1291]: Add custom, and autogenerated properties too.

**Comment by radical** [comment]
> Do not show members from classes that don't have debug information if JMC is enabled.

I'm not sure I understand. Is this correct? :

- if JMC is not enabled, then all the members of the full hierarchy should be visible
  - What can we show if debug information is not present?
  - Why remove the stuff that we can show, if JMC is not enabled?

Also, this won't completely fix https://github.com/dotnet/runtime/issues/43184, because this is still not returning the non-public members in `privateProperties`.

**Comment by radical** [comment]
Other than the comments here, and some from discussion offline, this LGTM, assuming the tests pass 👍

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs [hunk 4]
```diff
@@ -571,9 +572,15 @@ JObject GetNotAutoExpandableObject(int methodId, string propertyName, bool isSta
                 string typeName = await sdbHelper.GetTypeName(typeId, token);
                 // 0th id is for the object itself, and then its ancestors
                 bool isOwn = i == 0;
+                var typeInfo = await sdbHelper.GetTypeInfo(typeId, token);
+
+                if (typeInfo.Info.IsNonUserCode && getCommandType.HasFlag(GetObjectCommandOptions.JustMyCode))
+                    break;
+
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:579]: This can be right after `                int typeId = typeIdsIncludingParents[I];`.

File: src/mono/wasm/debugger/tests/debugger-test-without-debug-symbols-to-load/test.cs [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+{
+    public class ClassWithoutDebugSymbolsToInherit
+    {
+        private int propA {get;}
+        public int propB {get;}
+        protected int propC {get;}
+        private int d;
+        public int e;
+        protected int f;
+        public int G
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test-without-debug-symbols-to-load/test.cs:13]:
```suggestion
        public int G
```

File: src/mono/wasm/debugger/tests/debugger-test-without-debug-symbols-to-load/test.cs [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+    {
+        private int propA {get;}
+        public int propB {get;}
+        protected int propC {get;}
+        private int d;
+        public int e;
+        protected int f;
+        public int G 
+        { 
+            get {return f + 1;}
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test-without-debug-symbols-to-load/test.cs:15]:
```suggestion
        {
            get {return f + 1;}
```

File: src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs [hunk 7]
```diff
@@ -1275,3 +1275,66 @@ public static void MethodWithHiddenLinesAtTheEnd3()
...
+{
+    private int propA {get;}
+    public int propB {get;}
+    protected int propC {get;}
+    private int d;
+    public int e;
+    protected int f;
+    public int G 
+    { 
+        get {return f + 1;}
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:1305]:
```suggestion
    public int G
    {
        get {return f + 1;}
```

File: src/mono/wasm/debugger/tests/debugger-test/debugger-test.csproj [hunk 8]
```diff
@@ -63,6 +64,7 @@
 
       <WasmAssemblySearchPaths Include="$(MicrosoftNetCoreAppRuntimePackRidDir)native"/>
       <WasmAssemblySearchPaths Include="$(MicrosoftNetCoreAppRuntimePackRidDir)lib\$(NetCoreAppCurrent)"/>
+      <WasmAssemblySearchPaths Include="$(OutDir)"/>
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-test.csproj:67]: Why was this needed?

**Review by radical — APPROVED** [review]

**Review by lewing — APPROVED** [review]
