### PR TITLE
[NativeAOT] Fix floating pointer register unwinding on Arm32

### LINKED ISSUE #118942: ARM32 unwinding issue
Linux Pri1 arm32 outerloop legs have been failing with a mysterious `AzureDevOpsServiceError: The added or subtracted value results in an un-representable DateTime.` failure for a couple weeks now. I thought it's an infra issue and filed dotnet/dnceng#6034 on it (the tests are all passing but something wrong happens during results upload).

Since there has been no progress on that, I decided to investigate on my own.

Sleuthing in the logs and infra source code, I eventually found out the problem is likely in the testresults.xml that we generate:

```
<test name="JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b51420/b51420/b51420.dll" type="ILGEN_0xbc077bd" method="Main" time="922337203685.427490" result="Pass"></test>
```

Notice very weird `time=` value.

On a hunch I tried revert of #117588 in #118919. It had a successful arm32 run. Looks like there is more to this fix.

### PR DESCRIPTION
**Pull request by jkotas**
NativeAOT specific register window implementation has to match the one in libunwind.

Fixes https://github.com/dotnet/runtime/issues/118942.

### CODE REVIEW

File: src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp [hunk 1]
```diff
@@ -354,8 +354,8 @@ struct Registers_REGDISPLAY : REGDISPLAY
     uint32_t    getRegister(int num) const;
     void        setRegister(int num, uint32_t value, uint32_t location);
 
-    double      getFloatRegister(int num) const;
-    void        setFloatRegister(int num, double value);
+    unw_fpreg_t getFloatRegister(int num) const;
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp:357]: Unlike all other architectures, [libunwind on Arm32 uses unw_fpreg_t type here](https://github.com/dotnet/runtime/blob/bf795cbcc2639460f2f2cc7a90eaee20985aa232/src/native/external/llvm-libunwind/src/Registers.hpp#L2293-L2294) that's defined as uint64_t on arm32.

**Comment by jkotas** [comment]
runtime-nativeaot-outerloop linux-arm is green with this change. This is ready for review.

**Comment by am11** [comment]
Fixes https://github.com/dotnet/runtime/issues/118942.

**Comment by MichalStrehovsky** [comment]
Do you know what was the exact condition that was triggering this? If it's something sane, I wonder if it would be worth a regression test.

If we weren't uploading XML files with test results into AzDo and AzDo wasn't rejecting the durations, we'd basically never hit this in any of our testing.

**Comment by jkotas** [comment]
> Do you know what was the exact condition that was triggering this?

The distilled repro would be a chain of multiple methods that interleave floating-point computation and exception handling in a specific shape, something like this:
```
void M1()
{
    double mustBeUsedMultipleTimesToGetEnregisteredIntoCalledSavedFPRegister;
    mustBeUsedMultipleTimesToGetEnregisteredIntoCalledSavedFPRegister = some computation;
    M2();
    do more stuff with mustBeUsedMultipleTimesToGetEnregisteredIntoCalledSavedFPRegister;
}

[NoInline]
void M2()
{
    // This method should not use any floating point
    try
    {
        M3();
    }
    catch
    {
    }
}

[NoInline]
void M3()
{
    // The JIT must enregister this into same register as the local variable in M1()
    double mustBeUsedMultipleTimesToGetEnregisteredIntoCalledSavedFPRegister;
    mustBeUsedMultipleTimesToGetEnregisteredIntoCalledSavedFPRegister = some other computation;
    M4();`
    do more stuff with mustBeUsedMultipleTimesToGetEnregisteredIntoCalledSavedFPRegister;
}

[NoInline]
void M4()
{
    throw new Exception();
}
```

I can try to add a test like this.

**Review by janvorli — COMMENTED** [review]
LGTM, thank you!

**Review by janvorli — APPROVED** [review]

**Comment by jkotas** [comment]
> I can try to add a test like this.

It turns out we have multiple tests like that, but they are non-effective for various reasons. I am just going to fix one of the existing tests do what it meant to test.

**Comment by jkotas** [comment]
Pushed test updated. #119108 validated that the updated test fails on both linux-arm and linux-arm64 without the fixes.

**Review by janvorli — APPROVED** [review]
