### PR TITLE
JIT: Fix invalid IR and weights in if-conversion

### LINKED ISSUE #124942: JIT: If-conversion phase can produce questionable IR. Return block having a successor
I am doing some work on if-conversion and noticed that it can produce IR where a block with a return statement has a successor. Consider this minimal reproducible:
```cs
static int InvalidIR(bool cond)
{
    if (cond)
    {
        return 2;
    }
    // or else {}
    return 4;
}
```
Input to if-conversion:
```
------------ BB01 [0000] [000..003) -> BB03(0.5),BB02(0.5) (cond), preds={} succs={BB02,BB03}

***** BB01 [0000]
STMT00000 ( 0x000[E--] ... 0x001 )
N005 (  7,  8) [000003] -----+-----                         *  JTRUE     void   $VN.Void
N004 (  5,  6) [000002] J----+-N---                         \--*  EQ        int    $101
N002 (  3,  4) [000008] -----+-----                            +--*  CAST      int <- ubyte <- int $100
N001 (  2,  2) [000000] -----+-----                            |  \--*  LCL_VAR   int    V00 arg0         u:1 (last use) $80
N003 (  1,  1) [000001] -----+-----                            \--*  CNS_INT   int    0 $40

------------ BB02 [0001] [003..005) (return), preds={BB01} succs={}

***** BB02 [0001]
STMT00002 ( 0x003[E--] ... 0x004 )
N002 (  2,  2) [000007] -----+-----                         *  RETURN    int    $VN.Void
N001 (  1,  1) [000006] -----+-----                         \--*  CNS_INT   int    2 $44

------------ BB03 [0002] [005..007) (return), preds={BB01} succs={}

***** BB03 [0002]
STMT00001 ( 0x005[E--] ... 0x006 )
N002 (  2,  2) [000005] -----+-----                         *  RETURN    int    $VN.Void
N001 (  1,  1) [000004] -----+-----                         \--*  CNS_INT   int    4 $43
```

Then-case is BB02, else-case is BB03. Their statements are set to null and the `SELECT` node gets created in the JTRUE block (BB01). However the JTRUE block only get's it BB02 successor removed (and is set to `BBJ_ALWAYS`):
https://github.com/dotnet/runtime/blob/b613202168f0bda853c00968238fe571643cfde4/src/coreclr/jit/ifconversion.cpp#L767-L770

Which leads to the following output where BB01 has a return statement and a successor at the same time:
```
------------ BB01 [0000] [000..003) -> BB03(1) (always), preds={} succs={BB03}

***** BB01 [0000]
STMT00000 ( 0x000[E--] ... 0x001 )
N001 (  0,  0) [000003] -----+-----                         *  NOP       void  

***** BB01 [0000]
STMT00002 ( 0x003[E--] ... 0x004 )
N008 (  9, 10) [000007] -----+-----                         *  RETURN    int    $VN.Void
N007 (  8,  9) [000009] -----------                         \--*  SELECT    int   
N004 (  5,  6) [000002] J----+-N---                            +--*  EQ        int    $101
N002 (  3,  4) [000008] -----+-----                            |  +--*  CAST      int <- ubyte <- int $100
N001 (  2,  2) [000000] -----+-----                            |  |  \--*  LCL_VAR   int    V00 arg0         u:1 (last use) $80
N003 (  1,  1) [000001] -----+-----                            |  \--*  CNS_INT   int    0 $40
N005 (  1,  1) [000004] -----+-----                            +--*  CNS_INT   int    4 $43
N006 (  1,  1) [000006] -----+-----                            \--*  CNS_INT   int    2 $44

***** BB01 [0000]
STMT00001 ( 0x005[E--] ... 0x006 )
N001 (  0,  0) [000005] -----+-----                         *  NOP       void  

------------ BB02 [0001] [003..005) (return), preds={} succs={}

------------ BB03 [0002] [005..007) (return), preds={BB01} succs={}
```
---
I think this is also the reason it fails to recognize the second (from bottom to top) if-else flow here: https://godbolt.org/z/Kb5854sM1. So fixing this should make it catch a few more cases. But I am not sure how to do so in practice.

### PR DESCRIPTION
**Pull request by BoyBaykiller**
Fix #124942.

Small diffs are expected because:
1. It allows if-conversion to recognize more cases.
For example https://godbolt.org/z/Pdj898qTT currently still produces one jmp. But with this change it's eliminated, as the search now knows when there actually is a return block (previously it wasn't marked as such).

2. The block weights changed. For example previously
```cs
static int InvalidIR(bool cond)
{
    if (cond)
    {
        return 2;
    }
    // or else {}
    return 4;
}
```
produced blocks with `bbWeight = 0.5`, now it's 1.0.

### CODE REVIEW

File: src/coreclr/jit/ifconversion.cpp [hunk 1]
```diff
@@ -384,21 +384,32 @@ void OptIfConversionDsc::IfConvertJoinStmts(BasicBlock* fromBlock)
...
         {
-            m_compiler->fgDumpBlock(dumpBlock);
+            // Dump all Else blocks
+            for (BasicBlock* bb = m_startBlock->GetTrueTarget(); bb != m_finalBlock; bb = bb->GetUniqueSucc())
+            {
+                m_compiler->fgDumpBlock(bb);
+            }
         }
     }
+    else if (m_finalBlock != nullptr)
```
Comment (a74nh) [inline src/coreclr/jit/ifconversion.cpp]: This causes the "before" and "after" to show different blocks. In the dump below, the before shows BB01,BB02,BB03.
In the after it shows BB01, BB04.

Ideally, I think it should show BB01,BB02,BB03 in both before and after.

I'd be ok with not showing BB02 and BB03 in the after stage as they are empty. But I don't think we should show BB04.

```
Conditionally executing BB02 and BB03 inside BB01

------------ BB01 [0000] [000..005) -> BB03(0.5),BB02(0.5) (cond), preds={} succs={BB02,BB03}

***** BB01 [0000]
STMT00001 ( 0x002[E--] ... 0x003 )
N005 (  7,  9) [000005] -----+-----                         *  JTRUE     void   $VN.Void
N004 (  5,  7) [000004] J----+-N---                         \--*  EQ        int    $101
N002 (  3,  4) [000013] -----+-----                            +--*  CAST      int <- ubyte <- int $100
N001 (  2,  2) [000002] -----+-----                            |  \--*  LCL_VAR   int    V00 arg0         u:1 (last use) $80
N003 (  1,  2) [000003] -----+-----                            \--*  CNS_INT   int    0 $40

------------ BB02 [0001] [005..009) -> BB04(1) (always), preds={BB01} succs={BB04}

***** BB02 [0001]
STMT00005 ( 0x005[E--] ... 0x006 )
N002 (  5,  5) [000012] DA---+-----                         *  STORE_LCL_VAR int    V01 loc0         d:3 $VN.Void
N001 (  1,  2) [000011] -----+-----                         \--*  CNS_INT   int    2 $44

------------ BB03 [0002] [009..00C) -> BB04(1) (always), preds={BB01} succs={BB04}

***** BB03 [0002]
STMT00002 ( 0x009[E--] ... 0x00B )
N002 (  5,  5) [000007] DA---+-----                         *  STORE_LCL_VAR int    V01 loc0         d:2 $VN.Void
N001 (  1,  2) [000006] -----+-----                         \--*  CNS_INT   int    9 $43
setting likelihood of BB01 -> BB04 to 1

After if conversion

------------ BB01 [0000] [000..005) -> BB04(1) (always), preds={} succs={BB04}

***** BB01 [0000]
STMT00001 ( 0x002[E--] ... 0x003 )
N001 (  0,  0) [000005] -----+-----                         *  NOP       void  

***** BB01 [0000]
STMT00005 ( 0x005[E--] ... 0x006 )
N008 ( 12, 15) [000012] DA---+-----                         *  STORE_LCL_VAR int    V01 loc0         d:3 $VN.Void
N007 (  8, 12) [000018] -----------                         \--*  SELECT    int   
N004 (  5,  7) [000004] J----+-N---                            +--*  EQ        int    $101
N002 (  3,  4) [000013] -----+-----                            |  +--*  CAST      int <- ubyte <- int $100
N001 (  2,  2) [000002] -----+-----                            |  |  \--*  LCL_VAR   int    V00 arg0         u:1 (last use) $80
N003 (  1,  2) [000003] -----+-----                            |  \--*  CNS_INT   int    0 $40
N005 (  1,  2) [000006] -----+-----                            +--*  CNS_INT   int    9 $43
N006 (  1,  2) [000011] -----+-----                            \--*  CNS_INT   int    2 $44

***** BB01 [0000]
STMT00002 ( 0x009[E--] ... 0x00B )
N001 (  0,  0) [000007] -----+-----                         *  NOP       void  

------------ BB04 [0003] [00C..013) (return), preds={BB01,BB02,BB03} succs={}

***** BB04 [0003]
STMT00003 ( 0x00C[E--] ... 0x012 )
N002 ( 17,  5) [000009] --CXG+-----                         *  CALL      void   CSharpTutorials.Program:Consume(int) $VN.Void
N001 (  3,  2) [000008] -----+----- arg0 x0                 \--*  LCL_VAR   int    V01 loc0         u:4 (last use) $140

***** BB04 [0003]
STMT00004 ( 0x012[E--] ... ??? )
N001 (  0,  0) [000010] -----+-----                         *  RETURN    void   $VN.Void
```

File: src/coreclr/jit/ifconversion.cpp [hunk 2]
```diff
@@ -763,11 +774,35 @@ bool OptIfConversionDsc::optIfConvert(int* pReachabilityBudget)
...
+        m_startBlock->SetKindAndTargetEdge(BBJ_RETURN);
+    }
+    else
+    {
+        FlowEdge* newEdge =
+            m_doElseConversion ? m_compiler->fgAddRefPred(m_finalBlock, m_startBlock) : m_startBlock->GetTrueEdge();
+        m_startBlock->SetKindAndTargetEdge(BBJ_ALWAYS, newEdge);
+    }
+
+    assert(m_startBlock->GetUniqueSucc() == m_finalBlock);
```
Comment (a74nh) [inline src/coreclr/jit/ifconversion.cpp:752]: Not sure if this is a issue...

After the If conversion, we will have empty blocks that used to have the `Then` and `Else` cases. These end up getting cleaned up in the `Optimize pre-layout` phase. I think that's fine because that's exactly what `Optimize pre-layout` is meant to do.

Alternatively, we could delete the blocks at the end of If Conversion.

Eg:
```
*************** Finishing PHASE If conversion
Trees after If conversion

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight   [IL range]   [jump]                            [EH region]        [flags]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1    [000..003)-> BB03(1)                 (always)                   i
BB02 [0001]  0                             0    [003..006)-> BB03(1)                 (always)                   i
BB03 [0002]  2       BB01,BB02             1    [006..00D)                           (return)                   i hascall gcsafe
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------ BB01 [0000] [000..003) -> BB03(1) (always), preds={} succs={BB03}

***** BB01 [0000]
STMT00000 ( 0x000[E--] ... 0x001 )
N001 (  0,  0) [000003] -----+-----                         *  NOP       void  

***** BB01 [0000]
STMT00003 ( 0x003[E--] ... 0x004 )
N008 (  8, 11) [000008] DA---+-----                         *  STORE_LCL_VAR int    V01 arg1         d:2 $VN.Void
N007 (  8, 11) [000015] -----------                         \--*  SELECT    int   
N004 (  5,  7) [000002] J----+-N---                            +--*  EQ        int    $141
N002 (  3,  4) [000009] -----+-----                            |  +--*  CAST      int <- ubyte <- int $140
N001 (  2,  2) [000000] -----+-----                            |  |  \--*  LCL_VAR   int    V00 arg0         u:1 (last use) $80
N003 (  1,  2) [000001] -----+-----                            |  \--*  CNS_INT   int    0 $40
N005 (  1,  1) [000014] -----------                            +--*  LCL_VAR   int    V01 arg1         
N006 (  1,  2) [000007] -----+-----                            \--*  CNS_INT   int    2 $44

------------ BB02 [0001] [003..006) -> BB03(1) (always), preds={} succs={BB03}

------------ BB03 [0002] [006..00D) (return), preds={BB01,BB02} succs={}

***** BB03 [0002]
STMT00001 ( 0x006[E--] ... 0x00C )
N002 ( 15,  4) [000005] --CXG+-----                         *  CALL      void   CSharpTutorials.Program:Consume(int) $VN.Void
N001 (  1,  1) [000004] -----+----- arg0 x0                 \--*  LCL_VAR   int    V01 arg1         u:3 (last use) $180

***** BB03 [0002]
STMT00002 ( 0x00C[E--] ... ??? )
N001 (  0,  0) [000006] -----+-----                         *  RETURN    void   $VN.Void

-------------------------------------------------------------------------------------------------------------------
*************** In fgDebugCheckBBlist
[deferred prior check failed -- skipping this check]

*************** Starting PHASE Optimize pre-layout

*************** In fgUpdateFlowGraph()
Before updating the flow graph:

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight   [IL range]   [jump]                            [EH region]        [flags]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1    [000..003)-> BB03(1)                 (always)                   i
BB02 [0001]  0                             0    [003..006)-> BB03(1)                 (always)                   i
BB03 [0002]  2       BB01,BB02             1    [006..00D)                           (return)                   i hascall gcsafe
---------------------------------------------------------------------------------------------------------------------------------------------------------------------


Compacting BB03 into BB02:
Second block has 1 other incoming edges
*************** In fgDebugCheckBBlist

Compacting BB02 into BB01:
*************** In fgDebugCheckBBlist

After updating the flow graph:

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight   [IL range]   [jump]                            [EH region]        [flags]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1    [000..00D)                           (return)                   i gcsafe
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

***************  Exception Handling table is empty
*************** In fgDebugCheckBBlist

*************** In fgExpandRarelyRunBlocks()

*************** Finishing PHASE Optimize pre-layout
Trees after Optimize pre-layout

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight   [IL range]   [jump]                            [EH region]        [flags]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1    [000..00D)                           (return)                   i gcsafe
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------ BB01 [0000] [000..00D) (return), preds={} succs={}

***** BB01 [0000]
STMT00000 ( 0x000[E--] ... 0x001 )
N001 (  0,  0) [000003] -----+-----                         *  NOP       void  

***** BB01 [0000]
STMT00003 ( 0x003[E--] ... 0x004 )
N008 (  8, 11) [000008] DA---+-----                         *  STORE_LCL_VAR int    V01 arg1         d:2 $VN.Void
N007 (  8, 11) [000015] -----------                         \--*  SELECT    int   
N004 (  5,  7) [000002] J----+-N---                            +--*  EQ        int    $141
N002 (  3,  4) [000009] -----+-----                            |  +--*  CAST      int <- ubyte <- int $140
N001 (  2,  2) [000000] -----+-----                            |  |  \--*  LCL_VAR   int    V00 arg0         u:1 (last use) $80
N003 (  1,  2) [000001] -----+-----                            |  \--*  CNS_INT   int    0 $40
N005 (  1,  1) [000014] -----------                            +--*  LCL_VAR   int    V01 arg1         
N006 (  1,  2) [000007] -----+-----                            \--*  CNS_INT   int    2 $44

***** BB01 [0000]
STMT00001 ( 0x006[E--] ... 0x00C )
N002 ( 15,  4) [000005] --CXG+-----                         *  CALL      void   CSharpTutorials.Program:Consume(int) $VN.Void
N001 (  1,  1) [000004] -----+----- arg0 x0                 \--*  LCL_VAR   int    V01 arg1         u:3 (last use) $180

***** BB01 [0000]
STMT00002 ( 0x00C[E--] ... ??? )
N001 (  0,  0) [000006] -----+-----                         *  RETURN    void   $VN.Void

-------------------------------------------------------------------------------------------------------------------
*************** In fgDebugCheckBBlist
[deferred prior check failed -- skipping this check]

```

**Review by a74nh — COMMENTED** [review]
I tested this with some if/then, if/then/else, if/then/else/return cases. I'm happy the IR now looks correct afterwards.

**Review by a74nh — APPROVED** [review]
Given removing the BB blocks isn't required, I'm happy with this.

File: src/coreclr/jit/ifconversion.cpp [hunk 3]
```diff
@@ -763,11 +768,35 @@ bool OptIfConversionDsc::optIfConvert(int* pReachabilityBudget)
...
-    // Update the flow from the original block.
-    FlowEdge* const removedEdge  = m_compiler->fgRemoveAllRefPreds(m_startBlock->GetFalseTarget(), m_startBlock);
-    FlowEdge* const retainedEdge = m_startBlock->GetTrueEdge();
-    m_startBlock->SetKindAndTargetEdge(BBJ_ALWAYS, retainedEdge);
-    m_compiler->fgRepairProfileCondToUncond(m_startBlock, retainedEdge, removedEdge);
+    // Update the flow graph. JTRUE block now contains the SELECT.
+    //
+
+    // Remove flow into Then/Else blocks and update their weights
+    auto RemoveFlowInto = [&](BasicBlock* block) {
```
Comment (jakobbotsch) [inline src/coreclr/jit/ifconversion.cpp]: Nit: local variables should be camelCase

File: src/coreclr/jit/ifconversion.cpp [hunk 4]
```diff
@@ -763,11 +768,35 @@ bool OptIfConversionDsc::optIfConvert(int* pReachabilityBudget)
...
+    if (m_doElseConversion)
+    {
+        RemoveFlowInto(m_startBlock->GetTrueTarget());
+    }
+
+    // Change kind of JTRUE block and make it flow
+    // directly into block where flows merge (which is null in case of GT_RETURN)
+    if (m_mainOper == GT_RETURN)
+    {
+        m_startBlock->SetKindAndTargetEdge(BBJ_RETURN);
```
Comment (jakobbotsch) [inline src/coreclr/jit/ifconversion.cpp:743]: If I understand correctly this is still leaving existing empty `BBJ_RETURN` blocks around in the flow graph  (without a terminating `GT_RETURN` node). That is still illegal IR, regardless of whether those blocks are reachable. There is also a limit on x86 on the number of `BBJ_RETURN` blocks we can have, and making it a correctness requirement that a follow-up phase cleans those unreachable blocks up is not great either. For those reasons I would suggest removing the unreachable blocks immediately here.

**Review by jakobbotsch — APPROVED** [review]
LGTM! Thanks for working on this.
