### PR TITLE
[release/6.0] Fix ReadyToRun loading on Apple Silicon

### LINKED ISSUE #64103: .NET 6 crashes on a macOS 12.x virtual machine on Apple Silicon (arm64)
### Description

.NET 6 crashes when trying to run it in a macOS 12.x virtual machine on Apple Silicon (arm64). It works fine in a virtual machine on Intel (x64), or when running directly on the host.

### Reproduction Steps

1. Create a macOS virtual machine on Apple Silicon ([MacVM](https://github.com/KhaosT/MacVM) is an open source project using Apple's [Virtualization framework](https://developer.apple.com/documentation/virtualization) that can be used)
2. Install .NET 6 runtime or SDK in the virtual machine
3. Try to run e.g. `dotnet --info` and observe the crash

### Expected behavior

.NET 6 works as well in a virtual machine as it does on the host (aka it does not crash).

### Actual behavior

```
$ dotnet --info
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Cli.Utils.Reporter' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.ConsolePal' threw an exception.
 ---> System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.ConsolePal..cctor()
   --- End of inner exception stack trace ---
   at System.Console.get_ForegroundColor()
   at Microsoft.DotNet.Cli.Utils.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.DotNet.Cli.Utils.Reporter.Reset()
   at Microsoft.DotNet.Cli.Utils.Reporter..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Cli.Utils.Reporter.get_Error()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6
```

### Regression?

_No response_

### Known Workarounds

* Running the x64 version of .NET under Rosetta 2 emulation works fine.
* Setting the environment variable `COMPlus_ReadyToRun` to `0` allows to run without crashing.

### Configuration

.NET 6.0.1
macOS 12.0.1
ARM64
Virtual Machine

### Other information

The issue comes from the fact that ReadyToRun is broken in .NET 6 on Apple Silicon because of a memory protection mishandling issue, resulting in the JIT version of the assemblies being used instead. This memory protection mishandling issue does not happen when running in a virtual machine, which does result in the ReadyToRun section of assemblies to be loaded successfully.
Unfortunately, there is a second bug in the way variadic function arguments are passed on Apple Silicon, but this only gets triggered in ReadyToRun code, not in JIT code. It happens when a new object array gets created: JIT code will use `JIT_NewMDArrNonVarArg`, but ReadyToRun code will use `JIT_NewMDArr`, passing variadic arguments in registers instead of on the stack, in contradiction to [Apple's arm64 ABI guidelines](https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Update-Code-that-Passes-Arguments-to-Variadic-Functions). This results in the crash above.
Needless to say, creating new object arrays is a pretty common operation in the .NET runtime 😅

A big side effect of this bug is that load times of .NET on Apple Silicon are slower than they should be (when running on the host of course), as only JIT version of the assemblies are used. This seems to have always been broken (since support for Apple Silicon was added to .NET).

After quite a bit of research in the background during these past 2 months, I have come up with a fix for these 2 issues.
Whilst rebasing on `main`, I have noticed that they got fixed independently in #61938 for the memory protection mishandling issue, and #62855 for the new object array creation.
However those changes are impacting a much wider area of the runtime. I would thus advocate for backporting only the relevant changes to .NET 6, as it is the LTS release. Given the focus of that release on performance, and given that ReadyToRun has always been broken on Apple Silicon, I think that fixing .NET 6 would be the way to go, instead of waiting until .NET 7 is released.

I have created #64104 to address this issue.

### PR DESCRIPTION
**Pull request by jgiannuzzi**
## Customer Impact
Slow startup of .NET applications on Apple Silicon. ReadyToRun images are not loaded correctly on Apple Silicon. All methods are JITed during startup. 

For reference, compiling a medium-size project like [ILGPU](https://github.com/m4rs-mt/ILGPU) takes ~17s on a Mac Mini M1 before this change, and ~13s after this change (about 30% faster).

## Testing
crossgen2 outerloop tests. Manually verified that the ReadyToRun images are loaded correctly on Apple Silicon.

## Risk
Low risk. These fixes have been in dotnet/runtime:main for more than a month, however there is a risk of discovering latent Apple Silicon specific bugs in ReadyToRun with this fix.

---

Fixes #64103.

This PR aims at backporting a subset of the changes introduced in #61938 and #62855. The rationale behind this change is explained in more details in #64103. I believe that this change would be limited to `osx-arm64` and introduce a substantial performance gain by enabling ReadyToRun on Apple Silicon, which I imagine was supposed to work in .NET 6 in the first place.

For reference, compiling a medium-size project like [ILGPU](https://github.com/m4rs-mt/ILGPU) takes ~17s on a Mac Mini M1 before this change, and ~13s after this change (about 30% faster). Given the focus on performance in .NET 6, I would argue that this has to be fixed in .NET 6.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=64104) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=64104) before we can accept your contribution.<br/><br/>:x: jgiannuzzi [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=64104)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=64104) it.</sub>

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -7046,6 +7049,7 @@ void Compiler::impImportNewObjArray(CORINFO_RESOLVED_TOKEN* pResolvedToken, CORI
         }
```
Comment (jkotas) [inline src/coreclr/jit/importer.cpp:7049]: We may also want to add code to `LoadDynamicInfoEntry` / `case ENCODE_READYTORUN_HELPER` that rejects R2R images that contain calls to the broken `CORINFO_HELP_NEW_MDARR`. Otherwise, trying to run the broken code in these R2R images may cause existing apps to crash after installing this update.

**Comment by VSadov** [comment]
Changes in map and layout look good. Thanks!

File: src/coreclr/jit/importer.cpp (hunk 1 above)
Comment (jgiannuzzi) [reply src/coreclr/jit/importer.cpp:7049]: Excellent point, thanks @jkotas!
I will try to add this today.

**Review by trylek — APPROVED** [review]
LGTM but my experience with Apple Silicon is very limited, I'd feel more comfortable if JanV could take a look as well.

File: src/coreclr/jit/importer.cpp (hunk 1 above)
Comment (jgiannuzzi) [reply src/coreclr/jit/importer.cpp:7049]: I have added a commit (https://github.com/dotnet/runtime/pull/64104/commits/295b0095fb38478e4fa2f20a91432d46d196a3a7) that implements just that. Thanks again for the suggestion @jkotas!

**Review by jkotas — APPROVED** [review]
LGTM! Thank you

**Comment by jgiannuzzi** [comment]
I am not sure whether the current test failures are due to my changes or not.
@jkotas @trylek @VSadov do you have any pointers to help me solve this?

**Comment by janvorli** [comment]
The JIT\Directed\rvastatics\RVAOrderingTest is failing on both windows and x64 / arm64 Linux and OSX.
The Loader\binding\tracing\BinderTracingTest.Basic is failing on Windows x64 / arm64 only. 
However, the change doesn't touch any Windows behavior (the changes are under ifdefs so that they occur only on macOS and one of them on Linux too), so it is not clear to me how it could cause these failures.

**Review by janvorli — APPROVED** [review]

**Comment by jgiannuzzi** [comment]
I have tried running the `JIT/Directed/rvastatics/RVAOrderingTest` test locally with `CompositeBuildMode=1` and `RunCrossGen2=1`.
On Linux x64, Linux arm64, and macOS x64, they fail with or without my changes (e.g. 6de5c5ba25886270bddfbd827b6cf0b7f8a178a2 – which my branch is based on – fails, but also bbfc15ca692c32a60dacee5e204e638418e5d0bd – which is the current tip of `release/6.0`).
On macOS arm64, they only fail after 6e24b2dc1fd273a9c820162235fe4909fefa8778 is applied (my commit enabling R2R loading), which makes sense as without this commit the composite R2R dll does not get loaded and the test is then equivalent to not having `RunCrossGen2=1` set.
I did not try on Windows, but I expect the results would be similar.

**Comment by jgiannuzzi** [comment]
Update: the same test also fails on `main` (869ae1a373388da43a9263d3e8782c84dd91e37b at the time of writing) and on `v6.0.0` on Linux arm64 (and potentially more platforms, but I only tested that one).
There seems to be a bug in composite crossgen2 that copies only the referenced static data, but not the rest. It results in having only `s_First`, `s_Last`, and `s_1` (referenced as `s_Another1`) being copied, leaving a bunch of data between `s_First` and `s_Last` out.

@jkotas @trylek @VSadov @janvorli what is the best course of action for this particular PR? Is there anything more that is needed to get it merged?
I would love to see it part of the next release so that I can finally [setup an osx-arm64 CI pipeline](https://github.com/G-Research/ParquetSharp/issues/233) for [ParquetSharp](https://github.com/G-Research/ParquetSharp) using a macOS VM!

**Comment by jkotas** [comment]
> what is the best course of action for this particular PR? Is there anything more that is needed to get it merged?

I have filled the request to get it approved for .NET 6 serving. Thank you for your help with this fix!

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  We will take for consideration in 6.0.x.

cc @kdubau and @safern

**Comment by kdubau** [comment]
Thanks @jeffschwMSFT - as of right now we have no immediate plan to enable R2R in VS4Mac. cc @slluis FYI

**Comment by jeffschwMSFT** [comment]
@kdubau unless the r2r is stripped from NetCoreApp you would benefit from this change as those packages have r2r enabled.

**Comment by jeffschwMSFT** [comment]
@safern I asked the same question.  These failures are unrelated, we just ran more outerloops.  It is good to merge.

**Comment by safern** [comment]
Thanks for confirming.
