### PR TITLE
[RyuJIT] Don't optimize "x < 0" to shift for unsigned cmp

### LINKED ISSUE #42719: Test failure: Microsoft.CSharp.RuntimeBinder.Tests.IntegerBinaryOperationTests.ConstantExpressions(x: 0, y: 4294967295, type: LessThanOrEqual, result: True, shouldSucceedChecked: True)
failed in job:[runtime-coreclr libraries-jitstress 20200924.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=828808&view=ms.vss-test-web.build-test-results-tab&runId=26424988&resultId=108177&paneView=debug)

net5.0-Linux-Release-x64-CoreCLR_checked-jitminopts-Ubuntu.1804.Amd64.Open

Error message
~~~
Assert.Equal() Failure
Expected: True
Actual:   False


Stack trace
   at Microsoft.CSharp.RuntimeBinder.Tests.IntegerBinaryOperationTests.ConstantExpressions(Object x, Object y, ExpressionType type, Object result, Boolean shouldSucceedChecked) in /_/src/libraries/Microsoft.CSharp/tests/IntegerBinaryOperationTests.cs:line 504
~~~

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/42719 (see https://github.com/dotnet/runtime/pull/35627#issuecomment-733376797)

It used to optimize `(-1 u< 0)` to `(-1 >> 31)` 

/cc @sandreenko

### CODE REVIEW

File: src/coreclr/src/jit/codegenxarch.cpp [hunk 1]
```diff
@@ -5941,7 +5941,8 @@ void CodeGen::genCompareInt(GenTree* treeNode)
 
         // Optimize "x<0" and "x>=0" to "x>>31" if "x" is not a jump condition and in a reg.
         // Morph/Lowering are responsible to rotate "0<x" to "x>0" so we won't handle it here.
-        if ((targetSize >= 4) && (op1Size >= 4) && (targetReg != REG_NA) && tree->OperIs(GT_LT, GT_GE))
+        if ((targetSize >= 4) && (op1Size >= 4) && (targetReg != REG_NA) && tree->OperIs(GT_LT, GT_GE) &&
```
Comment (sandreenko) [inline src/coreclr/src/jit/codegenxarch.cpp:5944]: Sorry, I have not reviewed the original PR, but was it supported to be
```
emitAttr targetSize = emitActualTypeSize(tree->TypeGet()); // tree, not op1
emitAttr op1Size    = emitActualTypeSize(op1Type); // can use op1Type, but it is a nit.
```
?

and why do we have such restrictions? The actual type can't be less than 4, can it?

**Review by sandreenko — COMMENTED** [review]
Could you please mark it as fixing https://github.com/dotnet/runtime/pull/35627 and remove the exclusion for the test at https://github.com/sandreenko/runtime/blob/8c7ecdb1fc5d4ccb6ac667d53255373ae32362b8/src/libraries/Microsoft.CSharp/tests/IntegerBinaryOperationTests.cs#L501?

**Comment by sandreenko** [comment]
PTAL @CarolEidt cc @dotnet/jit-contrib

File: src/coreclr/src/jit/codegenxarch.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/src/jit/codegenxarch.cpp:5944]: Also should we condition this under `optimizationEnabled`? Seems odd to optimize this if we're not optimizing in general.

Comment (CarolEidt) [reply src/coreclr/src/jit/codegenxarch.cpp]: @sandreenko - good catch, and sorry I missed it. In particular, the first two checks will never fail, because `emitActualTypeSize` will always return at least 4 for an integral type. I believe that they are not needed.

I would agree with @AndyAyersMS that this should be guarded by `compiler->opts.OptimizationEnabled()`

Comment (EgorBo) [reply src/coreclr/src/jit/codegenxarch.cpp]: Fixed, sorry it was a leftover from my previous commits in that PR, does it make sense to keep an assert?

**Comment by sandreenko** [comment]
LGTM with this and [a stress library run ](https://dev.azure.com/dnceng/public/_build?definitionId=833&_a=summary)

> Could you please mark it as fixing #35627 and remove the exclusion for the test at https://github.com/sandreenko/runtime/blob/8c7ecdb1fc5d4ccb6ac667d53255373ae32362b8/src/libraries/Microsoft.CSharp/tests/IntegerBinaryOperationTests.cs#L501?

**Review by sandreenko — APPROVED** [review]

**Comment by ViktorHofer** [comment]
// Auto-generated message

https://github.com/dotnet/runtime/commit/69e114c1abf91241a0eeecf1ecceab4711b8aa62 which was merged 12/7 removed the intermediate src/coreclr/**src**/ folder. This PR needs to be updated as it touches files in that directory which causes conflicts.

To update your commits you can use this bash script: https://gist.github.com/ViktorHofer/6d24f62abdcddb518b4966ead5ef3783. Feel free to use the comment section of the gist to improve the script for others.

**Comment by EgorBo** [comment]
@dotnet/jit-contrib can this be merged?
