### PR TITLE
Fix Crossgen2 of PlatformDefaultMemberFunction methods and calls.

### LINKED ISSUE #50350: Test failure JIT\\Directed\\callconv\\PlatformDefaultMemberFunction\\PlatformDefaultMemberFunctionTest\\PlatformDefaultMemberFunctionTest.cmd
Run: [runtime-coreclr crossgen2 20210327.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1060198&view=ms.vss-test-web.build-test-results-tab&runId=32681378&resultId=101363&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
 -JIT\\Directed\\callconv\\PlatformDefaultMemberFunction\\PlatformDefaultMemberFunctionTest\\PlatformDefaultMemberFunctionTest.cmd
```

**Error message:**
```
Could Not Find C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\CdeclMemberFunctionNative.dll.rsp\r
Could Not Find C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\PlatformDefaultMemberFunctionNative.dll.rsp\r
Could Not Find C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\PlatformDefaultMemberFunctionTest.dll.rsp\r
Could Not Find C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\StdCallMemberFunctionNative.dll.rsp\r
Could Not Find C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\TestLibrary.dll.rsp\r
Could Not Find C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\ThisCallNative.dll.rsp\r
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.\r
 at PlatformDefaultMemberFunctionTest.Test8ByteHFA(C*)\r
 at PlatformDefaultMemberFunctionTest.Main(System.String[])\r
\r
Return code: 1\r
Raw output file: C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\Reports\JIT.Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\PlatformDefaultMemberFunctionTest.output.txt\r
Raw output:\r
BEGIN EXECUTION\r
CdeclMemberFunctionNative.dll\r
PlatformDefaultMemberFunctionNative.dll\r
PlatformDefaultMemberFunctionTest.dll\r
StdCallMemberFunctionNative.dll\r
TestLibrary.dll\r
ThisCallNative.dll\r
 6 file(s) copied.\r
Response file: C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\\CdeclMemberFunctionNative.dll.rsp\r
C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\IL-CG2\CdeclMemberFunctionNative.dll\r
-o:C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\\CdeclMemberFunctionNative.dll\r
--targetarch:x64\r
--verify-type-and-field-layout\r
-r:C:\h\w\9D1008B0\p\System..dll\r
-r:C:\h\w\9D1008B0\p\Microsoft..dll\r
-r:C:\h\w\9D1008B0\p\mscorlib.dll\r
-r:C:\h\w\9D1008B0\p
etstandard.dll\r
-O\r
" "dotnet" "C:\h\w\9D1008B0\p\crossgen2\crossgen2.dll" @"C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\\CdeclMemberFunctionNative.dll.rsp" -r:C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\IL-CG2\.dll"\r
No input files are loadable\r
Response file: C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\\PlatformDefaultMemberFunctionNative.dll.rsp\r
C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\IL-CG2\PlatformDefaultMemberFunctionNative.dll\r
-o:C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\\PlatformDefaultMemberFunctionNative.dll\r
--targetarch:x64\r
--verify-type-and-field-layout\r
-r:C:\h\w\9D1008B0\p\System..dll\r
-r:C:\h\w\9D1008B0\p\Microsoft.*.dll\r
-r:C:\h\w\9D1008B0\p\mscorlib.dll\r
-r:C:\h\w\9D1008B0\p
etstandard.dll\r
-O\r
" "dotnet" "C:\h\w\9D1008B0\p\crossgen2\crossgen2.dll" @"C:\h\w\9D1008B0\w\A9AA096F\e\JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\\PlatformDef

Stack trace
   at JIT_Directed._callconv_PlatformDefaultMemberFunction_PlatformDefaultMemberFunctionTest_PlatformDefaultMemberFunctionTest_._callconv_PlatformDefaultMemberFunction_PlatformDefaultMemberFunctionTest_PlatformDefaultMemberFunctionTest_cmd()

```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #50350

### CODE REVIEW

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 1]
```diff
@@ -649,9 +649,9 @@ private bool TryGetUnmanagedCallingConventionFromModOpt(MethodSignature signatur
                 }
             }
 
-            if (found && memberFunctionVariant)
+            if (memberFunctionVariant)
             {
-                callConv = GetMemberFunctionCallingConventionVariant(callConv);
+                callConv = GetMemberFunctionCallingConventionVariant(found ? callConv : (CorInfoCallConvExtension)PlatformDefaultUnmanagedCallingConvention());
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:654]: It seems the other place initializes `callConv` with `(CorInfoCallConvExtension)PlatformDefaultUnmanagedCallingConvention()`, is there a reason we don't do that here?

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs (hunk 1 above)
Comment (jkoritzinsky) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:654]: I believe we want to identify the difference between specifying the default and not specifying a calling convention. This makes a difference for handling inlined P/Invoke stubs (since not specifying one counts as WinAPI)

Comment (AaronRobinsonMSFT) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:654]: Ah okay. That is worth a comment as to why the default is different.
