### PR TITLE
ComWrappers test that allocate object can't inline

### LINKED ISSUE #85262: jitstress-random ComWrappersTestsBuiltInComDisabled is failing
Failing on [jitstress-random](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249289&view=ms.vss-test-web.build-test-results-tab&runId=4820970&resultId=111632&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab)

```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=30d
```

```
      BEGIN EXECUTION
       "C:\h\w\B9AB0A63\p\corerun.exe" -p "System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ComWrappersTestsBuiltInComDisabled.dll 
      Running ValidateComInterfaceCreation...
      Running ValidateComInterfaceCreationRoundTrip...
      Running ValidateComObjectExtendsManagedLifetime...
      Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 0
      Actual:   1
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at ComWrappersTests.Program.ValidateComObjectExtendsManagedLifetime()
         at ComWrappersTests.Program.Main()
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
      Test failed. Trying to see if dump file was created in C:\cores since 4/23/2023 7:51:40 PM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\B9AB0A63\p
      > C:\h\w\B9AB0A63\w\B3B80A0B\e\Interop\COM\ComWrappers\API\ComWrappersTestsBuiltInComDisabled\ComWrappersTestsBuiltInComDisabled.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at Interop_COM._ComWrappers_API_ComWrappersTestsBuiltInComDisabled_ComWrappersTestsBuiltInComDisabled_._ComWrappers_API_ComWrappersTestsBuiltInComDisabled_ComWrappersTestsBuiltInComDisabled_cmd()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
There are some JIT stress settings that aggressively inline
functions, regardless of size/complexity. This inlining can
perturb the subtle GC assumptions inherent in the COM
wrappers tests.

Fixes #85262 

/cc @jkoritzinsky

### CODE REVIEW

File: src/tests/Interop/COM/ComWrappers/API/Program.cs [hunk 1]
```diff
@@ -311,25 +315,26 @@ static void ValidateCreateObjectGcBehavior()
             IntPtr trackerObjRaw = MockReferenceTrackerRuntime.CreateTrackerObject();
 
             // Create the first native object wrapper and run the GC.
-            CreateObject();
-            GC.Collect();
```
Comment (AustinWise) [inline src/tests/Interop/COM/ComWrappers/API/Program.cs:315]: The use of `GC.Collect` instead of `ForceGC` was intentional. The bug in NativeAOT this test exposed was that a GC could null the contents of a weak GCHandle but not run finializers to remove that GCHandle from a cache. See #85235 . The `ForceGC` function runs finalizers, so this test would no longer be testing the same thing.

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/COM/ComWrappers/API/Program.cs:315]: > The use of GC.Collect instead of ForceGC was intentional.

Ah. That needs to be a comment then.

> The bug in NativeAOT this test exposed was that a GC could null the contents of a weak GCHandle but not run finializers to remove that GCHandle from a cache. 

Hmmm. This is a rather flakey test then. There is no guarantees the finalizer isn't going to be run. I will add notes to that effect. Thanks for the details.

**Review by jkoritzinsky — APPROVED** [review]

**Comment by AustinWise** [comment]
Thanks for fixing. There should probably be a roslyn analyzer that takes you add `NoInline` everywhere when calling `GC.Collect` in a test 😁

**Comment by AaronRobinsonMSFT** [comment]
> There should probably be a roslyn analyzer that takes you add NoInline everywhere when calling GC.Collect in a test

Not sure that is good general policy as it is specific to this test and how it is run. For normal xUnit tests, this wouldn't be much of an issue because the test cases are executed via Reflection. The test pattern under `src/tests` is more akin to scenario tests and the custom source generator that we have for making them xUnit-like is basically identical to what is in this test's `Main`.

Calling `GC.Collect()` in any test, outside of the runtime repo, is likely hiding a bug or a less than ideal architecture in the majority of cases.

**Comment by AustinWise** [comment]
I was specifically thinking about the couple bugs of this type I've caused in `src/tests` when trying to write tests for things like critical finializers and ref-counted handles.

Is there a recommended way to catch these sorts of bugs before I submit a PR? Perhaps running the test in a loop with certain GC stress modes enabled? I can't find documentation what modes would be helpful for catching these sorts of problems.

**Comment by AaronRobinsonMSFT** [comment]
> Is there a recommended way to catch these sorts of bugs before I submit a PR?

Unfortunately not really. A lot of it is experience ex-post since seeing it prior to check-in is hard because of the 1000 other things you are likely worrying about during development. I've personally checked in a flakey tests that suffer from this and then had to fix them so you are in good company. The experience part comes into play when you can get the failure and quickly see where the problem is without debugging or flipping on multiple logging tools. For JIT stress the common issue is inlining which can fundamentally change the lifetime of all locals in the inlined frame.

> Perhaps running the test in a loop with certain GC stress modes enabled?

Yep, that is something I regularly do and it helps provide confidence on GC holes, but not always issues like this. Running the test in Checked with `DOTNET_GCStress=C` is typically a good start. The JIT stress side of things is much harder and I simply let the CI find issues and investigate them as they come in.

I wouldn't take any introduced test issues personally, it is hard to get tests right in general and non-determinism like the GC simply exacerbates an already very hard problem space - writing robust and accurate tests.

**Comment by AustinWise** [comment]
Thanks for the tip about `DOTNET_GCStress=C`, I'll give it a try next time I'm writing tests that involve the finalizer.
