### PR TITLE
Skip decommit for large pages and add fake large pages test mode

### LINKED ISSUE #126903: GC heap corruption with GCLargePages
## Description

We (@BenV and @andyblox) are experiencing what appears to be heap corruption when using `GCLargePages` in production.

This can be forced to happen by using `GC.Collect` with `GCCollectionMode.Aggressive` when `GCLargePages`
mode is enabled on Linux.

When `DOTNET_GCLargePages=1` is enabled (with real kernel huge pages via hugetlbfs),
calling `GC.Collect(2, GCCollectionMode.Aggressive, true, true)` can cause GC
managed heap corruption. The corruption manifests as `NullReferenceException` and/or
`AccessViolationException` inside `ConcurrentDictionary` internals, with multiple
threads faulting simultaneously, which is characteristic of a GC heap corruption event.

Switching to `GCCollectionMode.Forced` (same generation, same blocking/compacting
parameters) works as expected with no corruption.

While `GCCollectionMode.Aggressive` does appear to make the heap corruption significantly more likely to happen
we are not using that in our application, so we would like assistance in tracking down the root cause.

## Analysis

The `GCCollectionMode.Aggressive` documentation states it "requests that the garbage
collector decommit as much memory as possible." We believe the aggressive decommit
code path interacts incorrectly with the GC's large-page memory management:

When `GCLargePages` is enabled the garbage collector [skips de-commits at the OS level](https://github.com/dotnet/runtime/blob/v10.0.5/src/coreclr/gc/gc.cpp#L7588)
and also has [special logic regarding clearing regions](https://github.com/dotnet/runtime/blob/v10.0.5/src/coreclr/gc/gc.cpp#L45174).
When an aggressive GC is induced, [all regions are flagged for de-commit](https://github.com/dotnet/runtime/blob/v10.0.5/src/coreclr/gc/gc.cpp#L13445)
and since de-commit success is always true for large pages the [bookkeeping is updated](https://github.com/dotnet/runtime/blob/v10.0.5/src/coreclr/gc/gc.cpp#L7552) even though
the de-commit never really happened, which could potentially cause corruption.

It is possible that the aggressive de-commit may need to be skipped when `GCLargePages` is active,
however it is also possible that this reproduction via forcing Aggressive GC is simply exposing
existing bugs within the de-commit logic that is leading to re-using pages which have not been
zeroed out by the OS.

We discovered this issue while trying to track down a problem we're hitting recently in production
when `GCLargePages` mode is active - we are occasionally getting `NullReferenceExceptions` related
to `ConcurrentDictionary` where it does not seem possible to throw a `NullReferenceException`:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Concurrent.ConcurrentDictionary`2.GrowTable(Tables tables, Boolean resizeDesired, Boolean forceRehashIfNonRandomized)
```

We created this example program as a way to try and reproduce that original issue, and while it is possible they are
related we do not believe we are either directly or indirectly calling `GC.Collect` with `GCCollectionMode.Aggressive`.
We would be very interested in hearing your thoughts on whether there could be any bugs lurking around
that could be causing the similar issues that we are encountering in production.

### Minimal repro program
[gc-largepages-repro.zip](https://github.com/user-attachments/files/26726770/gc-largepages-repro.zip)

#### Option 1: Docker (requires `--privileged` for huge page setup)

```bash
# Triggers corruption, usually within seconds:
./run.sh aggressive

# Control, identical workload, runs clean:
./run.sh forced

# To test with a different .NET version:
DOTNET_VERSION_ARG=10.0 ./run.sh aggressive
```

#### Option 2: Run locally on Linux

Requires real kernel huge pages allocated ahead of time (at least 4000 pages = 8GB):

```bash
# Reserve huge pages (requires root):
echo 4000 | sudo tee /proc/sys/vm/nr_hugepages

# Build (env vars must NOT be set during build):
dotnet build -c Release

# Triggers corruption, usually within seconds:
DOTNET_GCLargePages=1 DOTNET_GCHeapHardLimit=0xC0000000 \
    dotnet bin/Release/net8.0/GCLargePagesRepro.dll aggressive

# Control, identical workload, runs clean:
DOTNET_GCLargePages=1 DOTNET_GCHeapHardLimit=0xC0000000 \
    dotnet bin/Release/net8.0/GCLargePagesRepro.dll forced
```

The repro:

1. Creates 4 writer threads writing to a shared `ConcurrentDictionary<string, byte[]>`
2. A separate thread allocates temporary SOH/LOH arrays (creating GC region churn) and periodically calls `GC.Collect(2, mode, true, true)`
3. With `GCCollectionMode.Aggressive`: Corruption typically occurs within seconds
4. With `GCCollectionMode.Forced`: runs clean for the full duration

### Configuration that triggers the bug

```
DOTNET_GCLargePages=1
GC.Collect(2, GCCollectionMode.Aggressive, true, true)
```

### Configurations that do NOT trigger the bug

```
DOTNET_GCLargePages=1
GC.Collect(2, GCCollectionMode.Forced, true, true)
```

```
DOTNET_GCLargePages=0
GC.Collect(2, GCCollectionMode.Aggressive, true, true)
```

## Expected behavior

`GC.Collect(2, GCCollectionMode.Aggressive, true, true)` should not corrupt the
managed heap regardless of whether large pages are enabled.

## Observed behavior

Heap corruption and access violations or null reference exceptions. Corruption typically
occurs within seconds of starting, before the first status line is printed:

```
=== GCLargePages + Aggressive GC: Heap Corruption Repro ===
GC collect mode: Aggressive
Server GC:       True
GCLargePages:    1
Runtime:         .NET 8.0.25

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryAddInternal(...)
   at Program.WriterLoop(Int32)
   at Program+<>c__DisplayClass3_1.<Main>b__0()
```

```
[11:24:19.849] *** NRE on thread 3 — HEAP CORRUPTION ***
[11:24:19.847] *** NRE on thread 1 — HEAP CORRUPTION ***
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Concurrent.ConcurrentDictionary`2.GrowTable(Tables tables, Boolean resizeDesired, Boolean forceRehashIfNonRandomized)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAddInternal(...)
   at Program.WriterLoop(Int32 tid) in /app/Program.cs
```

The corruption cascades rapidly and multiple threads fault at the same millisecond,
consistent with a single GC event corrupting a heap region that multiple threads
then read from.

### Regression?

_No response_

### Known Workarounds

_No response_

### Environment

- Versions: .NET 8.0/10.0 (for .NET 10, disabling DATAS helps reproduce)
- OS: Linux (tested on official Microsoft .NET Docker images)
- Arch: x86_64
- Server/Concurrent GC enabled
- `DOTNET_GCLargePages=1` with real kernel huge pages

### Other information

When `GCLargePages` is enabled the garbage collector [skips de-commits at the OS level](https://github.com/dotnet/runtime/blob/v10.0.5/src/coreclr/gc/gc.cpp#L7588)
and also has [special logic regarding clearing regions](https://github.com/dotnet/runtime/blob/v10.0.5/src/coreclr/gc/gc.cpp#L45174).
When an aggressive GC is induced, [all regions are flagged for de-commit](https://github.com/dotnet/runtime/blob/v10.0.5/src/coreclr/gc/gc.cpp#L13445)
and since de-commit success is always true for large pages the [bookkeeping is updated](https://github.com/dotnet/runtime/blob/v10.0.5/src/coreclr/gc/gc.cpp#L7552) even though
the de-commit never really happened, which could potentially cause corruption.

It is possible that the aggressive de-commit may need to be skipped when `GCLargePages` is active,
however it is also possible that this reproduction via forcing Aggressive GC is simply exposing
existing bugs within the de-commit logic that is leading to re-using pages which have not been
zeroed out by the OS.

### PR DESCRIPTION
**Pull request by cshung**
With large pages, VirtualDecommit is a no-op since large pages cannot be partially decommitted. PR #126929 fixed the resulting stale data corruption by adding memclr in virtual_decommit, but this approach has downsides: the memory is never returned to the OS, yet we pay for the clearing and produce misleading committed/used bookkeeping.

Instead, skip the decommit entirely for large pages:

1. distribute_free_regions: skip the aggressive tail-region decommit (the committed-but-unallocated tail of in-use regions). This was the path that caused the heap corruption in #126903.

2. decommit_heap_segment: skip the whole-segment decommit used for segment hoarding and BGC segment deletion. Same class of issue: committed/used are lowered but physical memory retains stale data.

3. decommit_region: bypass virtual_decommit and call reduce_committed_bytes directly, since decommit_region already handles large pages correctly by clearing memory itself.

4. virtual_decommit: add an assert that it is never called for heap memory when large pages are on. This catches any future caller that forgets to handle the large pages case. The end_of_data parameter and no-op ternary added by #126929 are removed.

Add GCLargePages=2 mode that simulates large pages using small pages: sets use_large_pages_p=true but reserves with normal pages and commits everything upfront. This exercises all large page GC code paths without requiring OS large page setup or privileges, enabling CI testing.

Fix #126903

### CODE REVIEW

**Comment by mangod9** [comment]
@janvorli. Thanks @cshung for making the change, I like that we can now force largePages codepath within CI.

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -2619,6 +2619,7 @@ size_t gc_heap::eph_gen_starts_size = 0;
 heap_segment* gc_heap::segment_standby_list;
 #endif //USE_REGIONS
 bool          gc_heap::use_large_pages_p = 0;
+bool          gc_heap::large_pages_fake_mode_p = 0;
```
Comment (mangod9) [inline src/coreclr/gc/gc.cpp]: probably better to name this large_pages_force_mode or something.

Comment (janvorli) [reply src/coreclr/gc/gc.cpp]: I'd prefer `large_pages_simulation_mode_p` or `large_pages_emulation_mode_p`

File: src/coreclr/gc/memory.cpp [hunk 2]
```diff
@@ -171,15 +171,12 @@ bool gc_heap::virtual_decommit (void* address, size_t size, int bucket, int h_nu
...
+    assert (!use_large_pages_p || bucket == recorded_committed_bookkeeping_bucket);
 
-    // Large pages: the decommit above is a no-op so memory retains stale data.
-    // Clear up to end_of_data if the caller provided it so that the heap never
-    // observes leftover object references after the region is reused.
-    if (use_large_pages_p && (end_of_data != nullptr) && (end_of_data > address))
-    {
-        memclr ((uint8_t*)address, (uint8_t*)end_of_data - (uint8_t*)address);
-    }
+    bool decommit_succeeded_p = GCToOSInterface::VirtualDecommit (address, size);
```
Comment (mangod9) [inline src/coreclr/gc/memory.cpp:179]: think you need a similar fix in `gc_heap::decommit_region` ?

File: src/coreclr/gc/memory.cpp [hunk 3]
```diff
@@ -347,7 +344,18 @@ size_t gc_heap::decommit_region (heap_segment* region, int bucket, int h_number)
...
     uint8_t* decommit_end = heap_segment_committed (region);
     size_t decommit_size = decommit_end - page_start;
-    bool decommit_succeeded_p = virtual_decommit (page_start, decommit_size, bucket, h_number);
+    bool decommit_succeeded_p;
+    if (use_large_pages_p)
+    {
+        // VirtualDecommit is a no-op for large pages so skip it and update
+        // committed bookkeeping directly. Memory clearing is handled below.
+        decommit_succeeded_p = true;
+        reduce_committed_bytes (page_start, decommit_size, bucket, h_number, true);
```
Comment (VSadov) [inline src/coreclr/gc/memory.cpp:353]: If decommit is a noop, why are we reducing comitted bytes?

**Comment by VSadov** [comment]
The test fails on x86. Perhaps just make the test incompatible with 32bit?

File: src/coreclr/gc/memory.cpp (hunk 3 above)
Comment (cshung) [reply src/coreclr/gc/memory.cpp:353]: `decommit_region` returns the region to the global region allocator, so it is treated as decommitted regardless. When the region is later reused, it goes through recommit (also a no-op for largepages), which increases the committed byte counter. If we don't reduce committed bytes here on the decommit side, the counter only ever goes up and we'll eventually hit the hard limit.

We could alternatively skip the counter increase on recommit, but the GC does double-entry accounting — it maintains committed byte counters incrementally, and also computes them by walking the heap data structures for validation. Since `decommit_region` removes the region from the global allocator, it won't be visited during heap walks, so we need to reduce the counter to keep the two in agreement. For large pages this is mostly moot in practice, but keeping the bookkeeping consistent avoids subtle divergence.

File: src/coreclr/gc/memory.cpp (hunk 2 above)
Comment (cshung) [reply src/coreclr/gc/memory.cpp:179]: Good catch — yes, `decommit_region` also calls `virtual_decommit`. I've updated it to bypass `virtual_decommit` for large pages and call `reduce_committed_bytes` directly instead (lines 347-354 in memory.cpp). The existing logic below already handles large pages correctly — it clears memory up to `heap_segment_used` and resets the region — so the only thing we needed was to skip the no-op `virtual_decommit` call and update the bookkeeping ourselves.

File: src/tests/GC/API/GC/Collect_Aggressive_LargePages.csproj [hunk 4]
```diff
@@ -0,0 +1,20 @@
+<Project Sdk="Microsoft.NET.Sdk">
+  <PropertyGroup>
+    <!-- Needed for CLRTestEnvironmentVariable -->
+    <RequiresProcessIsolation>true</RequiresProcessIsolation>
+    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' != 'coreclr'">true</CLRTestTargetUnsupported>
+    <!-- Large pages and GCHeapHardLimit=0xC0000000 are not supported on 32-bit -->
```
Comment (pavelsavara) [inline src/tests/GC/API/GC/Collect_Aggressive_LargePages.csproj:6]: Wasm would benefit from this work and it's 32bit system.

See https://github.com/dotnet/runtime/pull/127328#discussion_r3151471535 for context.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!
