### PR TITLE
Fix singlefile on OSX ARM64

### LINKED ISSUE #67062: .NET 7 osx-arm64 single-file crashing with sigsegv
### Description

Latest build of .NET 7 published single-file app is crashing on execution.

### Reproduction Steps

```sh
# installation
mkdir ~/.dotnet7
curl -sSL https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-osx-arm64.tar.gz | tar xzf - -C ~/.dotnet7

# publish a new app as self-contained and single app
~/.dotnet7/dotnet new console -n testapp1
cd testapp1
cat > NuGet.config << EOF
<configuration>
  <packageSources>
    <add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" />
  </packageSources>
</configuration>
EOF
~/.dotnet7/dotnet publish --use-current-runtime -p:PublishSingleFile=true --self-contained -c Release

# run the published app
bin/Release/net7.0/osx-arm64/publish/testapp1
```

### Expected behavior

Displays `Hello, World!`

### Actual behavior

```zsh
zsh: segmentation fault  bin/Release/net7.0/osx-arm64/publish/testapp1
```

### Regression?

Yes, it woks with .NET 6.

### Known Workarounds

Publish as self-contained, without `-p:PublishSingleFile=true `.

### Configuration

Daily build
```zsh
% strings ~/.dotnet7/dotnet | grep '@(#)'
@(#)Version 7.0.22.17106 @Commit: ce813882f4061459dc62b63acb75add040f1f603
```

### Other information

I tried debugging it with native symbols (of release singlefilehost), the clrstack looks like this:

```gdb
% lldb bin/Release/net7.0/osx-arm64/publish/testapp1
Added Microsoft public symbol server

(lldb) target create "bin/Release/net7.0/osx-arm64/publish/testapp1"
Current executable set to '/Users/am11/projects/testapp1/bin/Release/net7.0/osx-arm64/publish/testapp1' (arm64).

(lldb) r
Process 22685 launched: '/Users/am11/projects/testapp1/bin/Release/net7.0/osx-arm64/publish/testapp1' (arm64)
Process 22685 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001000b4c78 testapp1`DictionaryLayout::FindToken(MethodTable*, LoaderAllocator*, int, SigBuilder*, unsigned char*, DictionaryEntrySignatureSource, CORINFO_RUNTIME_LOOKUP*, unsigned short*) + 84
testapp1`DictionaryLayout::FindToken:
->  0x1000b4c78 <+84>: ldr    w8, [x22]
    0x1000b4c7c <+88>: tst    w8, #0x30
    0x1000b4c80 <+92>: cset   w9, eq
    0x1000b4c84 <+96>: orr    w8, w9, w8, lsr #31
Target 0: (testapp1) stopped.

(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001000b4c78 testapp1`DictionaryLayout::FindToken(MethodTable*, LoaderAllocator*, int, SigBuilder*, unsigned char*, DictionaryEntrySignatureSource, CORINFO_RUNTIME_LOOKUP*, unsigned short*) + 84
    frame #1: 0x000000010010bf00 testapp1`ProcessDynamicDictionaryLookup(TransitionBlock*, Module*, Module*, unsigned char, unsigned char const*, unsigned char const*, CORINFO_RUNTIME_LOOKUP*, unsigned int*) + 932
    frame #2: 0x000000010010c290 testapp1`DynamicHelperFixup(TransitionBlock*, unsigned long*, unsigned int, Module*, CORCOMPILE_FIXUP_BLOB_KIND*, TypeHandle*, MethodDesc**, FieldDesc**) + 408
    frame #3: 0x000000010010d2d0 testapp1`DynamicHelperWorker + 232
    frame #4: 0x00000001002ed34c testapp1`DelayLoad_Helper_FakeProlog + 92
    frame #5: 0x0000000176a93760
    frame #6: 0x0000000176aa86b0
    frame #7: 0x00000001766badc4
    frame #8: 0x00000001002ed830 testapp1`CallDescrWorkerInternal + 132
    frame #9: 0x0000000100162eb4 testapp1`MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int) + 852
    frame #10: 0x000000010008df44 testapp1`CorHost2::CreateAppDomainWithManager(char16_t const*, unsigned int, char16_t const*, char16_t const*, int, char16_t const**, char16_t const**, unsigned int*) + 620
    frame #11: 0x0000000100572334 testapp1`coreclr_initialize + 784
    frame #12: 0x000000010001fb70 testapp1`coreclr_t::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, char const*, coreclr_property_bag_t const&, std::__1::unique_ptr<coreclr_t, std::__1::default_delete<coreclr_t> >&) + 420
    frame #13: 0x000000010002c998 testapp1`(anonymous namespace)::create_coreclr() + 432
    frame #14: 0x000000010002c46c testapp1`corehost_main + 160
    frame #15: 0x000000010000d5c8 testapp1`fx_muxer_t::handle_exec_host_command(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, host_startup_info_t const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unordered_map<known_options, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, known_options_hash, std::__1::equal_to<known_options>, std::__1::allocator<std::__1::pair<known_options const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&, int, char const**, int, host_mode_t, bool, char*, int, int*) + 1328
    frame #16: 0x000000010000c6a4 testapp1`fx_muxer_t::execute(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, char const**, host_startup_info_t const&, char*, int, int*) + 860
    frame #17: 0x00000001000091c0 testapp1`hostfxr_main_bundle_startupinfo + 196
    frame #18: 0x000000010004c818 testapp1`exe_start(int, char const**) + 1124
    frame #19: 0x000000010004caf4 testapp1`main + 152
    frame #20: 0x00000001043610f4 dyld`start + 520

(lldb) clrstack -f
OS Thread Id: 0x30e100 (1)
        Child SP               IP Call Site
000000016FDFE1A0 00000001000B4C78 testapp1!DictionaryLayout::FindToken(MethodTable*, LoaderAllocator*, int, SigBuilder*, unsigned char*, DictionaryEntrySignatureSource, CORINFO_RUNTIME_LOOKUP*, unsigned short*) + 84
000000016FDFE230 000000010010BF00 testapp1!ProcessDynamicDictionaryLookup(TransitionBlock*, Module*, Module*, unsigned char, unsigned char const*, unsigned char const*, CORINFO_RUNTIME_LOOKUP*, unsigned int*) + 932
000000016FDFE290 000000010010C290 testapp1!DynamicHelperFixup(TransitionBlock*, unsigned long*, unsigned int, Module*, CORCOMPILE_FIXUP_BLOB_KIND*, TypeHandle*, MethodDesc**, FieldDesc**) + 408
000000016FDFE610 000000010010D2D0 testapp1!DynamicHelperWorker + 232
000000016FDFE6A0                  [DynamicHelperFrame: 000000016fdfe6a0] 
000000016FDFE730 00000001002ED34C testapp1!DelayLoad_Helper_FakeProlog + 92
000000016FDFE860 0000000176AC3760 System.Private.CoreLib.dll!System.Collections.Generic.HashSet`1[[System.__Canon, System.Private.CoreLib]].CheckUniqueAndUnfoundElements(System.Collections.Generic.IEnumerable`1<System.__Canon>, Boolean) + 112 [/_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/HashSet.cs @ 1436]
000000016FDFE910 0000000176AD86B0 System.Private.CoreLib.dll!System.Collections.Generic.Dictionary`2[[System.__Canon, System.Private.CoreLib],[System.IntPtr, System.Private.CoreLib]].TryGetValue(System.__Canon, IntPtr ByRef) + 32 [/_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs @ 1108]
000000016FDFE930 00000001766EADC4 System.Private.CoreLib.dll!System.AppContext.Setup(Char**, Char**, Int32) + 84 [/_/src/libraries/System.Private.CoreLib/src/System/AppContext.cs @ 136]
FFFFFFFFFFFFFFFF 0000000176AD86B0 
FFFFFFFFFFFFFFFF 00000001766EADC4 
FFFFFFFFFFFFFFFF 00000001002ED830 testapp1!CallDescrWorkerInternal + 132
000000016FDFE9B0 0000000100162EB4 testapp1!MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int) + 852
000000016FDFEC20 000000010008DF44 testapp1!CorHost2::CreateAppDomainWithManager(char16_t const*, unsigned int, char16_t const*, char16_t const*, int, char16_t const**, char16_t const**, unsigned int*) + 620
000000016FDFEE20 0000000100572334 testapp1!coreclr_initialize + 784
000000016FDFEEE0 000000010001FB70 testapp1!coreclr_t::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, char const*, coreclr_property_bag_t const&, std::__1::unique_ptr<coreclr_t, std::__1::default_delete<coreclr_t> >&) + 420
000000016FDFEFF0 000000010002C998 testapp1!(anonymous namespace)::create_coreclr() + 432
000000016FDFF060 000000010002C46C testapp1!corehost_main + 160
000000016FDFF1B0 000000010000D5C8 testapp1!fx_muxer_t::handle_exec_host_command(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, host_startup_info_t const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unordered_map<known_options, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, known_options_hash, std::__1::equal_to<known_options>, std::__1::allocator<std::__1::pair<known_options const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&, int, char const**, int, host_mode_t, bool, char*, int, int*) + 1328
000000016FDFF310 000000010000C6A4 testapp1!fx_muxer_t::execute(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, char const**, host_startup_info_t const&, char*, int, int*) + 860
000000016FDFF420 00000001000091C0 testapp1!hostfxr_main_bundle_startupinfo + 196
000000016FDFF4D0 000000010004C818 testapp1!exe_start(int, char const**) + 1124
000000016FDFF600 000000010004CAF4 testapp1!main + 152
000000016FDFF660 00000001043610F4 dyld!start + 520
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: https://github.com/dotnet/runtime/issues/67062 , https://github.com/dotnet/runtime/issues/68654

### CODE REVIEW

File: src/coreclr/pal/src/map/map.cpp [hunk 1]
```diff
@@ -2394,8 +2394,9 @@ void * MAPMapPEFile(HANDLE hFile, off_t offset)
         goto doneReleaseMappingCriticalSection;
     }
 
-    void* prevSectionEnd;
-    prevSectionEnd = (char*)loadedHeader + headerSize; // the first "section" for our purposes is the header
+    void* prevSectionEndAligned;
+    // the first "section" for our purposes is the header
+    prevSectionEndAligned = ALIGN_UP((char*)loadedHeader + headerSize, GetVirtualPageSize());
```
Comment (VSadov) [inline src/coreclr/pal/src/map/map.cpp:2399]: The does not change how we map.  I just renamed `prevSectionEnd` and made it always aligned. I think it is more readable.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs [hunk 2]
```diff
@@ -599,12 +599,19 @@ protected override BlobBuilder SerializeSection(string name, SectionLocation loc
...
                 if (outputSectionIndex > 0)
                 {
                     sectionStartRva = Math.Max(sectionStartRva, _sectionRVAs[outputSectionIndex - 1] + _sectionRawSizes[outputSectionIndex - 1]);
+
+                    // when assembly is stored in a singlefile bundle, an additional skew is introduced
+                    // as the streams inside the bundle are not necessarily page aligned as we do not 
+                    // know the actual page size on the target system. 
+                    // We may need one page gap of unused VA space before the next section starts.
+                    // We will assume the page size is <= RVAAlign
+                    sectionStartRva += RVAAlign;
```
Comment (VSadov) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs:612]: I think I understand the layout mechanism more now. The way we construct sectionStartRva guarantees that sections will not overlap - that is if the file starts form offset 0.
That is not the case in a singlefile bundle. 

On ARM64 the file from a bundle will start at an offset that is 4K aligned. On systems with 4K page size (i.e. default Ubuntu) such aligned offset will be as good as starting form 0. Thus we do not see asserts on Linux.

On OSX ARM64 the page size is 16K, so we may need to "spill" past the end of the target VA region. Same could happen on unusually configured Linuxes with larger page sizes.

I think we can assume that 64K is enough to cover any reasonable page size and leaving 64K unused VA gap between sections will ensure that we will not overlap.

File: src/installer/managed/Microsoft.NET.HostModel/Bundle/TargetInfo.cs [hunk 3]
```diff
@@ -57,17 +57,17 @@ public TargetInfo(OSPlatform? os, Architecture? arch, Version targetFrameworkVer
...
-                // See https://github.com/dotnet/runtime/issues/41832.
                 AssemblyAlignment = 4096;
             }
-            else if (IsWindows)
+            else if (Arch == Architecture.Arm64)
             {
-                // We align assemblies in the bundle at 4K - per requirements of memory mapping API (MapViewOfFile3, et al).
+                // We align assemblies in the bundle at 4K so that we can use mmap on Unix without changing the page alignment of ARM64 R2R code.
                 // This is only necessary for R2R assemblies, but we do it for all assemblies for simplicity.
+                // See https://github.com/dotnet/runtime/issues/41832.
```
Comment (VSadov) [inline src/installer/managed/Microsoft.NET.HostModel/Bundle/TargetInfo.cs:70]: Once you get past the assert, you may still see crashes. I think they were because of this. We align files in the bundle on 4K for Linux, to make sure that `adrp` assembly instructions (which works off a 4K offset) are stable without performing relocations. 

I think the same applies to OSX as well. The fix could be older than Apple Silicon and therefore covered Linux only.

**Comment by VSadov** [comment]
It would be nice to run Installer OSX ARM64 tests with this, but I think they are disabled in CI and broken. 

When I tried running Installer tests locally they failed before even running - the restore scripts failed. 
Something about targeting 3.1 and OSX ARM64, which is not a valid combination, etc...

File: src/installer/managed/Microsoft.NET.HostModel/Bundle/TargetInfo.cs (hunk 3 above)
Comment (VSadov) [reply src/installer/managed/Microsoft.NET.HostModel/Bundle/TargetInfo.cs:70]: This is in a compile-time tool. It cold be a completely different platform/os.
We do not want arbitrary big alignment too, since it will increase the total size of the single file app.

Comment (VSadov) [reply src/installer/managed/Microsoft.NET.HostModel/Bundle/TargetInfo.cs:70]: Also this is because of `ADRP` instruction, which operates with 4k offsets regardless of OS page.

**Review by trylek — APPROVED** [review]
LGTM, thanks Vlad for fixing this!

**Comment by VSadov** [comment]
Thanks!!
