### PR TITLE
Pop LMF frames in exception handlers on wasm, since the normal pop LMF code might not get executed in case of an exception.

### LINKED ISSUE #46613: [Wasm][AOT] Assertion at /__w/1/s/runtime/src/mono/mono/mini/exceptions-wasm.c:66, condition `(*lmf)->method
### Description

Executing the following code:
```
try
{
	var asm = Assembly.Load(new AssemblyName("invalid.resources"));
	Console.WriteLine("asm: " + asm);
}
catch
{
	Console.WriteLine("not found");
}

var s = typeof(Program).Assembly.GetSatelliteAssembly(CultureInfo.InvariantCulture);
```

fails with the following:
```
* Assertion at /__w/1/s/runtime/src/mono/mono/mini/exceptions-wasm.c:66, condition `(*lmf)->method' not met
mono_assertion_message | @ | 03e207c6:0x23f595
-- | -- | --
  | mono_arch_unwind_frame | @ | 03e207c6:0x30f8df
  | arch_unwind_frame | @ | 03e207c6:0x301bfa
  | mono_find_jit_info_ext | @ | 03e207c6:0x301caf
  | unwinder_unwind_frame | @ | 03e207c6:0x3026c1
  | mono_walk_stack_full | @ | 03e207c6:0x3015e8
  | mono_walk_stack_with_ctx | @ | 03e207c6:0x301448
  | mono_runtime_walk_stack_with_ctx | @ | 03e207c6:0x3011b6
  | mono_stack_walk_no_il | @ | 03e207c6:0x278931
  | mono_runtime_get_caller_from_stack_mark | @ | 03e207c6:0x262951
  | ves_icall_System_Reflection_Assembly_InternalLoad | @ | 03e207c6:0x246e8d
  | ves_icall_System_Reflection_Assembly_InternalLoad_raw | @ | 03e207c6:0x26ce78
  | aot_wrapper_corlib_System_dot_Reflection_System_dot_Reflection_dot_Assembly__InternalLoad_pinvoke_cls14_Reflection_dAssembly__cl6_string_bcls1c_Threading_dStackCrawlMark_26_iicls14_Reflection_dAssembly__cl6_string_bcls1c_Threading_dStackCrawlMark_26_ii | @ | 03e207c6:0x13538b
  | corlib_System_Reflection_Assembly_Load_System_Reflection_AssemblyName_System_Threading_StackCrawlMark__System_Runtime_Loader_AssemblyLoadContext | @ | 03e207c6:0x1350d2
  | invoke_iiiii | @ | dotnet.js:11666
  | corlib_System_Reflection_RuntimeAssembly_InternalGetSatelliteAssembly_System_Reflection_Assembly_System_Globalization_CultureInfo_System_Version_bool | @ | 03e207c6:0x122526
  | corlib_System_Reflection_RuntimeAssembly_GetSatelliteAssembly_System_Globalization_CultureInfo_System_Version | @ | 03e207c6:0x13b87d
  | corlib_System_Reflection_RuntimeAssembly_GetSatelliteAssembly_System_Globalization_CultureInfo | @ | 03e207c6:0x13b800
  | Bug45698__Program___Main__string__


```

### Configuration

73bce5550bc30c11953b32be554803e466f376a4

### Regression?

No.

### Other information

Related to https://github.com/dotnet/runtime/issues/45698

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/46613.

### CODE REVIEW

File: src/mono/mono/mini/mini-llvm.c [hunk 1]
```diff
@@ -4700,6 +4700,24 @@ emit_llvmonly_handler_start (EmitContext *ctx, MonoBasicBlock *bb, LLVMBasicBloc
 		mono_llvm_emit_clear_exception_call (ctx, ctx->builder);
 	}
 
+#ifdef TARGET_WASM
```
Comment (lambdageek) [inline src/mono/mono/mini/mini-llvm.c:4703]: Is this going to be called only for catch clauses?  will it pop twice if there's a catch and a finally?

Comment (vargaz) [reply src/mono/mono/mini/mini-llvm.c:4703]: Its not really a pop, it just gets rid of all lmf frames below the current one, so its ok to call it multiple times.

**Review by lambdageek — APPROVED** [review]

File: src/mono/mono/mini/llvmonly-runtime.c [hunk 2]
```diff
@@ -815,3 +815,15 @@ mini_llvmonly_throw_aot_failed_exception (const char *name)
...
+/*
+ * mini_llvmonly_pop_lmf:
+ *
+ *   Pop LMF off the LMF stack.
+ */
+void
+mini_llvmonly_pop_lmf (MonoLMF *lmf)
+{
+	if (lmf->previous_lmf)
+		mono_set_lmf (lmf->previous_lmf);
```
Comment (lambdageek) [inline src/mono/mono/mini/llvmonly-runtime.c:828]: fix C++
```suggestion
		mono_set_lmf ((MonoLMF*)lmf->previous_lmf);
```
