### PR TITLE
When marshalling a layout class, fall-back to dynamically marshalling the type if it doesn't match the static type in the signature.

### LINKED ISSUE #49857: Incorrect PInvoke when parameter has base class with no members
### Description

PInvoke marshalling is incorrect when there is a parameter whose type has a base class with no members.

I hit this when removing our manual marshaling workaround for #46643, and it feels like the same bug in a different place.

#46643 describes a problem where given:
```
[StructLayout(LayoutKind.Sequential)]
class MyClassBase { }

[StructLayout(LayoutKind.Sequential)]
class MyClass1: MyClassBase { public int Value; }
```
The result of `Marshal.StructureToPtr<MyClass1>(...)` was incorrect, containing a non-collapsed zero-field for the base type.

The fix for that is in net5.0.3, and in testing against 5.0.4, while I _do_ see the fix for `Marshal.StructureToPtr<>()`, I'm still seeing the same symptoms on a PInvoke parameter:
```
[DllImport(...)]
static extern void TakeThat(
    MyClassBase pObject,
    UIntPtr sizeOfObject);
```

### Configuration

runtime version: 5.0.4
OS: Windows 20H2 19042.867 64-bit
Arch: x64 PC, 32-bit and 64-bit runtimes
Specific to configuration: unknown

### Regression?

net5.0 regression from netfx and netcore 3.1.

The fix for the #46643 is in 5.0.3 [PR 46697](https://github.com/dotnet/runtime/pull/46697), but this related issue remains.

### Other information

With this native export:
```
extern "C" N5MNATIVE_API void TakeThat(
	void* pObject,
	size_t sizeOfObject);
```
And these managed imports:
```
static class NativeMethods
{
    [DllImport("n5mnative.dll", EntryPoint = "TakeThat", CallingConvention = CallingConvention.Cdecl)]
    public static extern void TakeThatBuffer(
        [In][MarshalAs(UnmanagedType.LPArray)] byte[] pObject,
        [In][MarshalAs(UnmanagedType.SysUInt)] UIntPtr sizeOfObject);

    [DllImport("n5mnative.dll", EntryPoint = "TakeThat", CallingConvention = CallingConvention.Cdecl)]
    public static extern void TakeThatObject(
        [In][MarshalAs(UnmanagedType.LPStruct)] MyClassBase pObject,
        [In][MarshalAs(UnmanagedType.SysUInt)] UIntPtr sizeOfObject);
}

[StructLayout(LayoutKind.Sequential)]
abstract class MyClassBase
{
}

[StructLayout(LayoutKind.Sequential)]
class MyClass1 : MyClassBase
{
    public uint Int2;
}
```
And this instance:
```
var myClass1 = new MyClass1
{
    Int2 = 0xA2A2A2A2,
};
```

Here's the output of some test code on netcoreapp 3.1.13 and net 5.0.4. (net472 is the same as netcoreapp so I won't re-paste.)

```
Environment.Version: 3.1.13
Environment.Is64BitProcess: False

Bytes from managed Marshal.StructureToPtr<MyClassBase>(myClass1):
        A2 A2 A2 A2

PInvoke NativeMethods.TakeThatBuffer():
TakeThat(): pObject is not nullptr and declared sizeOfObject is 0x00000004.
        A2 A2 A2 A2

PInvoke NativeMethods.TakeThatObject():
TakeThat(): pObject is not nullptr and declared sizeOfObject is 0x00000004.
        A2 A2 A2 A2

PInvoke NativeMethods.TakeThatObject() with size overrun:
TakeThat(): pObject is not nullptr and declared sizeOfObject is 0x00000008.
        A2 A2 A2 A2 00 00 00 00
```
```
nvironment.Version: 5.0.4
Environment.Is64BitProcess: False

Bytes from managed Marshal.StructureToPtr<MyClassBase>(myClass1):
        A2 A2 A2 A2

PInvoke NativeMethods.TakeThatBuffer():
TakeThat(): pObject is not nullptr and declared sizeOfObject is 0x00000004.
        A2 A2 A2 A2

PInvoke NativeMethods.TakeThatObject():
TakeThat(): pObject is not nullptr and declared sizeOfObject is 0x00000004.
        00 00 00 00

PInvoke NativeMethods.TakeThatObject() with size overrun:
TakeThat(): pObject is not nullptr and declared sizeOfObject is 0x00000008.
        00 00 00 00 A2 A2 A2 A2
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
When we switched the struct marshalling system to be IL based, we accidentally stopped checking if the passed in object matched the type in the signature in the "layout class" case (where we have a sequential or explicit layout `class` type). This causes failures to marshal the derived types correctly since only the base type ends up being marshalled.

This PR fixes the regression by falling back to dynamically marshalling the object if the runtime type does not match the declared type.

Fixes #49857

### CODE REVIEW

File: src/coreclr/vm/ilmarshalers.cpp [hunk 1]
```diff
@@ -2368,12 +2478,26 @@ void ILBlittablePtrMarshaler::EmitConvertContentsNativeToCLR(ILCodeStream* pslIL
...
     pslILEmit->EmitLabel(pNullRefLabel);
 }
 
 bool ILBlittablePtrMarshaler::CanMarshalViaPinning()
 {
-    return IsCLRToNative(m_dwMarshalFlags) && !IsByref(m_dwMarshalFlags) && !IsFieldMarshal(m_dwMarshalFlags);
+    return IsCLRToNative(m_dwMarshalFlags) &&
+        !IsByref(m_dwMarshalFlags) &&
+        !IsFieldMarshal(m_dwMarshalFlags) &&
+        m_pargs->m_pMT->IsSealed(); // We can't marshal via pinning if we might need to marshal differently at runtime.
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/ilmarshalers.cpp:2500]: Let's add a comment here to `EmitExactTypeCheck` for an example.

File: src/coreclr/vm/ilmarshalers.cpp [hunk 2]
```diff
@@ -2261,7 +2295,22 @@ void ILLayoutClassPtrMarshalerBase::EmitClearNativeTemp(ILCodeStream* pslILEmit)
     }
 }
 
+bool ILLayoutClassPtrMarshalerBase::EmitExactTypeCheck(ILCodeStream* pslILEmit, ILCodeLabel* isNotMatchingTypeLabel)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/ilmarshalers.cpp:2298]: Curious - would it be possible to make this a static local function to this compilation unit and not expose it on the type? If it is even marginally complicated leave as-is.

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/vm/mlinfo.cpp [hunk 3]
```diff
@@ -1133,6 +1133,8 @@ MarshalInfo::MarshalInfo(Module* pModule,
     CorElementType corElemType      = ELEMENT_TYPE_END;
     m_pMT                           = NULL;
     m_pMD                           = pMD;
+    // For backward compatibility reasons, some marshalers imply [In, Out] behavior when marked as [Out].
```
[the remark this answers is not in the document]
Comment (jkoritzinsky) [reply src/coreclr/vm/mlinfo.cpp:1136]: I'll add `[Compat]` to make this clearer at a glance.

File: src/coreclr/vm/ilmarshalers.cpp (hunk 2 above)
Comment (jkoritzinsky) [reply src/coreclr/vm/ilmarshalers.cpp:2298]: We'd have to add an extra parameter, which wouldn't be too bad.

I added it as a member of the type since it's only used in `ILLayoutClassPtrMarshalerBase` and derived classes, so I felt that putting it on the class as a protected member already scoped it pretty well.

File: src/coreclr/vm/ilmarshalers.cpp [hunk 4]
```diff
@@ -2261,7 +2295,22 @@ void ILLayoutClassPtrMarshalerBase::EmitClearNativeTemp(ILCodeStream* pslILEmit)
...
+{
+    if (m_pargs->m_pMT->IsSealed())
```
Comment (jkoritzinsky) [inline src/coreclr/vm/ilmarshalers.cpp:2300]:
```suggestion
    STANDARD_VM_CONTRACT;

    if (m_pargs->m_pMT->IsSealed())
```

File: src/coreclr/vm/ilmarshalers.cpp (hunk 1 above)
Comment (jkoritzinsky) [inline src/coreclr/vm/ilmarshalers.cpp:2500]:
```suggestion
        m_pargs->m_pMT->IsSealed(); // We can't marshal via pinning if we might need to marshal differently at runtime. See calls to EmitExactTypeCheck where we check the runtime type of the object being marshalled.
```

File: src/coreclr/vm/mlinfo.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (jkoritzinsky) [reply src/coreclr/vm/mlinfo.cpp:1136]:
```suggestion
    // [Compat] For backward compatibility reasons, some marshalers imply [In, Out] behavior when marked as [Out].
```

File: src/coreclr/vm/ilmarshalers.cpp (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/ilmarshalers.cpp:2298]: That makes sense.
