### PR TITLE
[wasm] Revert back  to eval in wasm InvokeJS with modularization support .

### LINKED ISSUE #61192: wasm InvokeJS return value is broken
### Description

The transition to using a custom closure instead of eval broke the return value of InvokeJS.

### Reproduction Steps

```csharp
        var res = Interop.Runtime.InvokeJS(@"1 + 2", out int exceptionalResult);
        if (exceptionalResult != 0)
            throw new Exception("InvokeJS failed " + res);
        else if (res != "3")
            throw new Exception("InvokeJS returned invalid result " + res);
```

### Expected behavior

Doesn't throw

### Actual behavior

Throws, exception message indicates there was no return value

### Regression?

Yes

### Known Workarounds

If you put 'return' in the JS expression it may work

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by maraf**
Wrap code to evaluate in a function with MONO, BINDING, INTERNAL
and module as local variables. Than use `eval`.

Added tests for invoking js expressions.

Fixes dotnet/runtime#61192.

### CODE REVIEW

**Review by kg — APPROVED** [review]

**Comment by pavelsavara** [comment]
Tests failed with 
`Return type of InvokeJS is string. Can't marshal response of type object.`
We also need to do `  res = res.toString ();` as in original code.

**Comment by kg** [comment]
> 
> 
> Tests failed with `Return type of InvokeJS is string. Can't marshal response of type object.` We also need to do ` res = res.toString ();` as in original code.

@maraf if you want to run the bindings tests specifically when iterating on APIs like this, this will run a sizable (but not complete!) chunk of them:
```
~/Projects/dotnet-runtime-wasm$ make -C src/mono/wasm runtime corlib CONFIG=Debug && clear &&  ./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Debug ~/Projects/dotnet-runtime-wasm/src/libraries/System.Private.Runtime.InteropServices.JavaScript/tests/
```
(replace the folder with the location of your checkout)

**Comment by pavelsavara** [comment]
Also, please add the test case which @kg mentioned in the issue.

**Comment by pavelsavara** [comment]
Windows incantation for the test same is 
```
dotnet.cmd build /bl:test.binlog /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Debug /t:Test src/libraries/System.Private.Runtime.InteropServices.JavaScript/tests
```

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=61212) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=61212) before we can accept your contribution.<br/><br/>:x: maraf [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=61212)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=61212) it.</sub>

File: src/mono/wasm/runtime/method-calls.ts [hunk 1]
```diff
@@ -541,18 +541,18 @@ export function mono_wasm_invoke_js(code: MonoString, is_exception: Int32Ptr): M
...
         };
-        const fn_body_template = `const {Module, MONO, BINDING, INTERNAL} = __closure; const __fn = function(){ ${js_code} }; return __fn.call(__closure);`;
-        const fn_defn = new Function("__closure", fn_body_template);
-        const res = fn_defn(closure);
+        let res = closedEval(Module, MONO, BINDING, INTERNAL, js_code);
         Module.setValue(is_exception, 0, "i32");
         if (typeof res === "undefined" || res === null)
             return MonoStringNull;
+
+        res = res.toString();
```
Comment (kg) [inline src/mono/wasm/runtime/method-calls.ts:555]: if res is null or undefined, this will fail. i'll check what the appropriate solution for this is

Comment (maraf) [reply src/mono/wasm/runtime/method-calls.ts:555]: Isn't it covered two lines above? 
I have also added a test, where the result of the JS expression is `null`.

Comment (kg) [reply src/mono/wasm/runtime/method-calls.ts:555]: ok, this is actually fine, I think. We already check for the type up above, the only thing this should fail for is Symbol, which already was broken

**Comment by kg** [comment]
Can you add a test that verifies the eval is not happening in global scope? I think it would invoke some JS like:

```javascript
(test_local_variable_name = 5, globalThis.test_local_variable_name)
```

InvokeJS on that will return 5 in global scope, and return undefined otherwise

File: src/mono/wasm/runtime/method-calls.ts (hunk 1 above)
Comment (kg) [reply src/mono/wasm/runtime/method-calls.ts:555]: Yeah, I misread the check above initially. Symbol is the only problem type here, and you don't need to worry about it (Symbol is generally broken even without our help)

**Comment by maraf** [comment]
@kg Was it intended to use an undeclared variable? As we are in the strict mode, one can't use undeclared variable. I can add a test with variable declaration, something like

```
var test_local_variable_name = 5; globalThis.test_local_variable_name
```

**Review by kg — APPROVED** [review]

File: src/mono/wasm/runtime/method-calls.ts [hunk 2]
```diff
@@ -541,18 +541,18 @@ export function mono_wasm_invoke_js(code: MonoString, is_exception: Int32Ptr): M
...
         if (typeof res !== "string")
```
Comment (pavelsavara) [inline src/mono/wasm/runtime/method-calls.ts:556]: This test is not necessary anomore.

Comment (maraf) [reply src/mono/wasm/runtime/method-calls.ts]: 👍 Dropped.

**Review by pavelsavara — APPROVED** [review]

**Comment by pavelsavara** [comment]
@kg @maraf guys, I think we should reconsider again. The InvokeJS is internal API and the version without eval is breaking just edge case scenario. On the other hand, we have to look at that compilation warning every day.

**Comment by kg** [comment]
If the only motivation is the compile warning, we can suppress the warning.

**Comment by maraf** [comment]
I don't see a good reason for using function instance.

- Both are basically eval (with all the bad things that come with it).
- The code is always evaluated just once. 
- For better perf, users should write a function and call it.
