### PR TITLE
[ARM] Use Math[F].Round implementation in managed code

### LINKED ISSUE #97922: [NativeAOT] Rounding helpers use wrong rounding algorithm
[RhpFltRound/RhpDblRound](https://github.com/dotnet/runtime/blob/60cfe26dcb28a7fd26c09d082466a7ea650fc505/src/coreclr/nativeaot/Runtime/MathHelpers.cpp#L81-L89) are implemented using `round`/`roundf`. That's incorrect, since .NET default is round to even. Similar issue was [recently fixed](https://github.com/dotnet/runtimelab/pull/2503) in NativeAOT-LLVM.

Unfortunately, `roundeven`/`roundevenf` methods are only available in C23 standard. They are implemented on glibc 2.25+ (current .NET requirement is 2.23) and missing on Bionic/MUSL libc. CoreCLR uses a [custom implementation](https://github.com/dotnet/runtime/blob/60cfe26dcb28a7fd26c09d082466a7ea650fc505/src/coreclr/vm/jithelpers.cpp#L519-L543) which can presumably be reused.

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #97922

I decided to go for managed implementation to make it trimmable.

### CODE REVIEW

**Comment by jkotas** [comment]
Does this work with Scanner? Can the implementation just call Math.Round instead?

I do not understand why we need these JIT intrinsics in the first place. They seem to be only used on Arm and only to morph System.Math.Round. What would break if  these JIT intrinsics are deleted?

cc @dotnet/jit-contrib

**Comment by filipnavara** [comment]
ARM doesn't have native instructions to perform the rounding (unlike eg. ARM64). I didn't realize there is actually already a managed implementation in Math.cs. I suppose it can be used.

**Comment by EgorBo** [comment]
> ARM doesn't have native instructions to perform the rounding (unlike eg. ARM64). I didn't realize there is actually already a managed implementation in Math.cs. I suppose it can be used.

Even if there were no managed impl, it could still just go the InternalCall path like most Math APIs.

I wasn't able to track who and why added those, looks like it happened before the `Initial commit to populate CoreCLR repo` commit.

**Comment by jkotas** [comment]
> I wasn't able to track who and why added those, looks like it happened before the Initial commit to populate CoreCLR repo commit.

It is likely a left over from the times before we had support for recognizing managed methods as JIT intrinsics where all JIT intrinsics had to be FCalls.

File: src/coreclr/inc/corinfo.h [hunk 1]
```diff
@@ -397,8 +397,6 @@ enum CorInfoHelpFunc
     CORINFO_HELP_DBL2ULNG_OVF,
     CORINFO_HELP_FLTREM,
     CORINFO_HELP_DBLREM,
-    CORINFO_HELP_FLTROUND,
```
Comment (jkotas) [inline src/coreclr/inc/corinfo.h:400]: This needs new JIT/EE interface GUID

**Comment by tannergooding** [comment]
Worth noting as well that `fesetround(FE_TONEAREST);` should be completely unnecessary, as we already do not support the user changing the default rounding mode. It is strictly undefined behavior if they do. `nearbyint` is notably better than `rint`, typically, but as we don't support IEEE 754 exception handling and likewise treat enabling it as UB, they should generally behave the same.

However, I also agree that having this in managed is ultimately better. Our currently implementation is notably not super efficient and we could improve it, but that can be a separate work item.

File: src/coreclr/inc/readytorun.h [hunk 2]
```diff
@@ -397,8 +397,6 @@ enum ReadyToRunHelper
     // Floating point ops
     READYTORUN_HELPER_DblRem                    = 0xE0,
     READYTORUN_HELPER_FltRem                    = 0xE1,
-    READYTORUN_HELPER_DblRound                  = 0xE2,
```
Comment (jkotas) [inline src/coreclr/inc/readytorun.h:400]: These needs to stay. It would require `MINIMUM_READYTORUN_MAJOR_VERSION` bump to get rid of them. You can add a comment that these can be deleted once `MINIMUM_READYTORUN_MAJOR_VERSION` is 10 or higher.

**Comment by jkotas** [comment]
Build break during crossgen: `Assertion failed 'unreached' in 'System.Math:IEEERemainder(double,double):double' during 'Linear scan register alloc' (IL size 150; hash 0xdbe0c805; FullOpts)`

File: src/coreclr/inc/readytorun.h (hunk 2 above)
Comment (filipnavara) [reply src/coreclr/inc/readytorun.h:400]: I was afraid of that. I'll revert that part.

**Comment by filipnavara** [comment]
> Build break during crossgen: `Assertion failed 'unreached' in 'System.Math:IEEERemainder(double,double):double' during 'Linear scan register alloc' (IL size 150; hash 0xdbe0c805; FullOpts)`

This will take me a little while to understand and resolve.

**Comment by SingleAccretion** [comment]
@filipnavara I think you need to take out `NI_System_Math_Round` from here:

https://github.com/dotnet/runtime/blob/bb2376cf22172196bcac715d2f26ddfcb1b991cf/src/coreclr/jit/importercalls.cpp#L6884-L6890

File: src/coreclr/inc/readytorun.h [hunk 3]
```diff
@@ -397,6 +397,10 @@ enum ReadyToRunHelper
     // Floating point ops
     READYTORUN_HELPER_DblRem                    = 0xE0,
     READYTORUN_HELPER_FltRem                    = 0xE1,
+
+    // These two helpers can be removed with next major version bump
```
Comment (jkotas) [inline src/coreclr/inc/readytorun.h:401]:
```suggestion
    // These two helpers can be removed once MINIMUM_READYTORUN_MAJOR_VERSION is 10+
```

Comment (tannergooding) [reply src/coreclr/inc/readytorun.h]: Should there be a comment immediately above MINIMUM_READYTORUN_MAJOR_VERSION telling people to do a grep for such cases, so we don't miss out on removing them later?

Comment (tannergooding) [reply src/coreclr/inc/readytorun.h]: Basically something like:
> // If you update this, ensure you `git grep MINIMUM_READYTORUN_MAJOR_VERSION` and handle pending work

**Review by jkotas — APPROVED** [review]
Thanks
