### PR TITLE
Fix regression caused by special marker type optimization

### LINKED ISSUE #123254: VB.NET program using .NET runtime 10.0.2 throws EntryPointNotFoundException
### Description

A specific class definition results in an `EntryPointNotFoundException` when running on the .NET runtime 10.0.2. The same code runs without error on .NET runtime 10.0.1.

### Reproduction Steps

Reproduction is here: https://github.com/reduckted/repro-dotnet-runtime

The error is:
```
> dotnet run --project VB
Unhandled exception. System.EntryPointNotFoundException: Entry point was not found.
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VB.Program.Main(String[] args) in /home/runner/work/repro-dotnet-runtime/repro-dotnet-runtime/VB/Program.vb:line 5
```

Here's a copy of the code for reference:
```vb
Public NotInheritable Class Program

    Public Shared Function Main(args() As String) As Integer
        Dim w As New Widget(Of Integer)
        w.ToList()
        Console.WriteLine("Completed")
        Return 0
    End Function

End Class

Public Class Widget(Of T)
    Implements IWidget(Of T)

    Public ReadOnly Property Count As Integer Implements IReadOnlyCollection(Of T).Count

    Public Function GetEnumerator() As IEnumerator(Of T) Implements IEnumerable(Of T).GetEnumerator
        Return Enumerable.Empty(Of T)().GetEnumerator()
    End Function

    Private Function IEnumerable_GetEnumerator() As IEnumerator Implements IEnumerable.GetEnumerator
        Return GetEnumerator()
    End Function

End Class

Public Interface IWidget(Of T)
    Inherits IReadOnlyCollection(Of T)

End Interface
```

Some things to note:
- The `IWidget` class must be generic. Changing it to `IWidget` and inheriting from `IReadOnlyCollection(Of Integer)` runs without error.
- The `Widget` class can be changed to be non-generic by implementing `IWidget(Of Integer)` and the exception still occurs.
- Equivalent code in C# runs without error.

Here is a workflow run that shows it succeeding for .NET 10.0.1 and failing for 10.0.2:
https://github.com/reduckted/repro-dotnet-runtime/actions/runs/21063712505

### Expected behavior

The code runs without error.

### Actual behavior

```
System.EntryPointNotFoundException: Entry point was not found.
```

### Regression?

Yes. This worked in .NET 10.0.1.

### Known Workarounds

None.

### Configuration

- .NET 10.0.2
- `ubuntu-latest` GitHub runner
- x64

### Other information

_No response_

### LINKED ISSUE #123318: .NET 10 - System.ExecutionEngineException in System.Reflection.MethodBaseInvoker.InvokeWithOneArg
### Description

I have generic classes/interface with 9 (or more) generic type parameters.

When the type is activated, the runtime crashes with a System.ExecutionEngineException.
There is not much information provided by the debugger: "Exception of type 'System.ExecutionEngineException' was thrown."

Everything works fine on .net 10 when having 8 or less parameters.
Everything works fine in earlier .net versions, even with 9 or more parameters.

### Reproduction Steps

``` csharp
void Test()
{
    var i = new MyEntity<string, string, string, string, string, string, string, string, string>(); // <-- Throws System.ExecutionEngineException in System.Reflection.MethodBaseInvoker.InvokeWithOneArg(...)
}

public sealed class MyEntity<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7, TItem8, TItem9> : IEditableEntity<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7, TItem8, TItem9>
{
    public TItem1 Item1 {get; set;}
    public TItem2 Item2 {get; set;}
    public TItem3 Item3 {get; set;}
    public TItem4 Item4 {get; set;}
    public TItem5 Item5 {get; set;}
    public TItem6 Item6 {get; set;}
    public TItem7 Item7 {get; set;}
    public TItem8 Item8 {get; set;}
    public TItem9 Item9 {get; set;}
}

public interface IReadonlyEntity<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7, TItem8, TItem9>
{
    TItem1 Item1 {get;}
    TItem2 Item2 {get;}
    TItem3 Item3 {get;}
    TItem4 Item4 {get;}
    TItem5 Item5 {get;}
    TItem6 Item6 {get;}
    TItem7 Item7 {get;}
    TItem8 Item8 {get;}
    TItem9 Item9 {get;}
}

public interface IEditableEntity<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7, TItem8, TItem9> : IReadonlyEntity<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7, TItem8, TItem9>
{
    new TItem1 Item1 {get;set;}
    new TItem2 Item2 {get;set;}
    new TItem3 Item3 {get;set;}
    new TItem4 Item4 {get;set;}
    new TItem5 Item5 {get;set;}
    new TItem6 Item6 {get;set;}
    new TItem7 Item7 {get;set;}
    new TItem8 Item8 {get;set;}
    new TItem9 Item9 {get;set;}
}
```

### Expected behavior

An instance of the type should be created without error.

### Actual behavior

- Runtime crashes
- System.ExecutionEngineException.
- "Exception of type 'System.ExecutionEngineException' was thrown."

### Regression?

Code works fine with
- .net Framework 4.6.2 to 4.8
- .net 3.1 to .net 9.0

Bug appeared with .net 10.
- Reproduced with 10.0.102 (and earlier)

### Known Workarounds

No workaround found.

### Configuration

- .net 10.0.102
- Windows 11, 25H2, 26200.7623
- x64
- Visual Studio 2026, v18.2.0

### Other information

The error was found in unit test (MSTest).

### PR DESCRIPTION
**Pull request by davidwrighton**
There are 2 fixes here
1. For issue #123254, the problem is that the implementation of the optimized path interface map logic for interfaces which can be expanded by just manually expanding the first 2 layers of interfaces was not wired up at all. It turns out that this path is almost exclusively only available to VB.NET programs due to differences in the metadata generation algorithms between the VB and C# compilers. Notably, the VB.NET compiler does not expand the full set of interfaces into the outermost type, and C# compilation does. The fix is to implement handling for all of the various combinations of type that can appear at that point. See the newly added regression test for details on how to get into those situations.
2. For issue #123318 there was an issue where if there are more than MaxGenericParametersForSpecialMarkerType but we may have attempted to use a special marker type to optimize type loading. The fix is to place the logic for determining if a type can be represented in an interface map via a special marker type into a common location, and to not forget the check against MaxGenericParametersForSpecialMarkerType.

Fixes #123254 and #123318

### CODE REVIEW

File: src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+        ' Test indirect implmenentation of interface
+        Dim testClassType As Type = GetType(TestClass5(Of Integer)).GetGenericTypeDefinition().MakeGenericType(GetType(ILayer1_5(Of Integer)).GetGenericTypeDefinition().GetGenericArguments()(0))
+        Console.WriteLine("testClassType first generic argument: " & testClassType.GetGenericArguments()(0).Name)
+        For Each iface As Type In testClassType.GetInterfaces()
+            Console.WriteLine("IFace name: " & iface.Name)
+            Console.WriteLine("IFace first generic argument: " & iface.GetGenericArguments()(0).Name)
+            Assert.Equal("Z", iface.GetGenericArguments()(0).Name)
+        Next
+
+        ' Test direct implmenentation of interface
```
Comment (jkotas) [inline src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb]:
```suggestion
        ' Test direct implementation of interface
```

File: src/coreclr/vm/methodtable.cpp [hunk 2]
```diff
@@ -8937,3 +8937,19 @@ void MethodTable::GetStaticsOffsets(StaticsOffsetType offsetType, bool fGenericS
         *dwGCOffset = (uint32_t)sizeof(TADDR) * 2;
     }
 }
+
+bool Instantiation::EligibleForSpecialMarkerTypeUsage(MethodTable* pOwnerMT)
```
Comment (jkotas) [inline src/coreclr/vm/methodtable.cpp]: Nit: We do not have policy heavy methods like this on `Instantiation` currently. Instead, they are on components that are coupled to the policy, for example `ClassLoader::IsSharableInstantiation`.

File: src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+
+    ' Test path for forcing the interface map out of the supporting special marker types due to a conflict with the concept of special marker types
+    <Fact>
+    Public Shared Sub Test_Method5()
+        ' I could only find a way to hit this path with reflection, and since reflection is imperfect on NativeAOT, just skip this test there.
+        if (Not TestLibrary.Utilities.IsNativeAot)
+            Return
+        End If
+
+        ' Test indirect implmenentation of interface
```
Comment (jkotas) [inline src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb]:
```suggestion
        ' Test indirect implementation of interface
```

File: src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb [hunk 4]
```diff
@@ -0,0 +1,182 @@
...
+' The .NET Foundation licenses this file to you under the MIT license.
+
+Imports System
+Imports System.Collections
+Imports System.Collections.Generic
+Imports Xunit
+
+Public Class GitHub_123254
+
+    ' Test the scenario where the implied interface is is in the interface map of a containing interface as a special marker type, and the containing interface itself is ALSO a special marker type.
```
Comment (AaronRobinsonMSFT) [inline src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb]:
```suggestion
    ' Test the scenario where the implied interface is in the interface map of a containing interface as a special marker type, and the containing interface itself is ALSO a special marker type.
```

File: src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb [hunk 5]
```diff
@@ -0,0 +1,182 @@
...
+    Public Interface ILayer2_1(Of T)
+        Inherits ILayer1_1(Of T)
+        ReadOnly Property Count As Integer
+    End Interface
+
+    Public Interface ILayer1_1(Of T)
+        Function GetEnumerator() As IEnumerator(Of T)
+    End Interface
+
+    ' Test the scenario where the implied interface is is in the interface map of a containing interface as a special marker type, and the containing interface itself is NOT a special marker type.
```
Comment (AaronRobinsonMSFT) [inline src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb]:
```suggestion
    ' Test the scenario where the implied interface is in the interface map of a containing interface as a special marker type, and the containing interface itself is NOT a special marker type.
```

File: src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb [hunk 6]
```diff
@@ -0,0 +1,182 @@
...
+    Public Interface ILayer2_2(Of T)
+        Inherits ILayer1_2(Of T)
+        ReadOnly Property Count As Integer
+    End Interface
+
+    Public Interface ILayer1_2(Of T)
+        Function GetEnumerator() As IEnumerator(Of T)
+    End Interface
+
+    ' Test the scenario where the implied interface is is in the interface map of a containing interface as a special marker type, and the containing interface itself is NOT a special marker type.
```
Comment (AaronRobinsonMSFT) [inline src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb]:
```suggestion
    ' Test the scenario where the implied interface is in the interface map of a containing interface as a special marker type, and the containing interface itself is NOT a special marker type.
```

File: src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb [hunk 7]
```diff
@@ -0,0 +1,182 @@
...
+    Public Interface ILayer2_3(Of T)
+        Inherits ILayer1_3(Of T)
+        ReadOnly Property Count As Integer
+    End Interface
+
+    Public Interface ILayer1_3(Of T)
+        Function GetEnumerator() As IEnumerator(Of T)
+    End Interface
+
+    ' Test the scenario where the implied interface is is in the interface map of a containing interface as a special marker type, and the containing interface itself is NOT a special marker type.
```
Comment (AaronRobinsonMSFT) [inline src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb]:
```suggestion
    ' Test the scenario where the implied interface is in the interface map of a containing interface as a special marker type, and the containing interface itself is NOT a special marker type.
```

File: src/coreclr/vm/methodtablebuilder.cpp
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/methodtablebuilder.cpp:1]: We should talk tomorrow so I get what is going on here :)

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 8]
```diff
@@ -9816,23 +9814,98 @@ MethodTableBuilder::LoadExactInterfaceMap(MethodTable *pMT)
...
+                        //
+                        // Then determine if all of the following conditions hold true.
+                        // 1. All generic arguments are the same (always true for cases 2 and 3 above)
+                        // 2. The first generic argument in the instantiation is exactly the value of calling GetSpecialInstantiationType on pMT (always true for case 2)
+                        //
+                        // If so, then we should insert the special marker type
+                        // Otherwise, we should insert the exact instantiation of the interface
+                        // HOWEVER: If the exact instantiation IS a special marker interface, we need to retry with exact interfaces to avoid ambiguity situations
+                        // 
+                        // NOTE: This is also part of the logic which determines if we need to call SetMayHaveOpenInterfacesInInterfaceMap. What will happen is that if we have both an case where we want to insert a special marker type
```
Comment (jkotas) [inline src/coreclr/vm/methodtablebuilder.cpp]: > ...  if we have both an case where we want to insert ...

This does not parse for me

File: src/coreclr/vm/methodtable.cpp (hunk 2 above)
Comment (davidwrighton) [reply src/coreclr/vm/methodtable.cpp]: I've moved this to ClassLoader.

File: src/coreclr/vm/methodtablebuilder.cpp (hunk 8 above)
Comment (davidwrighton) [reply src/coreclr/vm/methodtablebuilder.cpp]: I've rewritten the comment, and as a result found another weirdo case to write up as a test, and another fix to write. Comments are good. Comments are useful. The whole special marker type concept is wildly complicated and confusing, but I think I've plugged at least this set of holes in it.

File: src/tests/Loader/classloader/regressions/GitHub_123318/GitHub_123318.csproj [hunk 9]
```diff
@@ -0,0 +1,7 @@
+<Project Sdk="Microsoft.NET.Sdk">
+  <PropertyGroup>
+  </PropertyGroup>
```
Comment (jkotas) [inline src/tests/Loader/classloader/regressions/GitHub_123318/GitHub_123318.csproj]:
```suggestion
```

File: src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb [hunk 10]
```diff
@@ -0,0 +1,194 @@
...
+
+    Public Interface ILayer1_4(Of T)
+        Function GetEnumerator() As IEnumerator(Of T)
+    End Interface
+
+    ' Test path for forcing the interface map out of the supporting special marker types due to a conflict with the concept of special marker types
+    <Fact>
+    Public Shared Sub Test_Method5()
+        ' I could only find a way to hit this path with reflection, and since reflection is imperfect on NativeAOT, just skip this test there.
+        if (TestLibrary.Utilities.IsNativeAot)
```
Comment (jkoritzinsky) [inline src/tests/Loader/classloader/regressions/GitHub_123254/GitHub_123254.vb]: Either add an `ActiveIssue` attribute for "is NativeAOT" or make it a `ConditionalFact` for "IsNotNativeAot"?

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 11]
```diff
@@ -9869,7 +9956,7 @@ MethodTableBuilder::LoadExactInterfaceMap(MethodTable *pMT)
     _ASSERTE(!duplicates || !(pMT->GetModule()->IsSystem() && (pMT->IsValueType() || pMT->IsInterface())));
 
     CONSISTENCY_CHECK(duplicates || (nAssigned == pMT->GetNumInterfaces()));
-    if (duplicates)
+    if (duplicates || (nAssigned != pMT->GetNumInterfaces()))
```
Comment (jkotas) [inline src/coreclr/vm/methodtablebuilder.cpp:9959]: What is the case fixed by this change?

File: src/coreclr/vm/siginfo.cpp [hunk 12]
```diff
@@ -1618,9 +1618,17 @@ TypeHandle SigPointer::GetTypeHandleThrowing(
...
 
-                if (pMTInterfaceMapOwner != NULL && genericLoadInst.ContainsAllOneType(pMTInterfaceMapOwner->GetSpecialInstantiationType()))
+                if (ClassLoader::EligibleForSpecialMarkerTypeUsage(genericLoadInst, pMTInterfaceMapOwner))
                 {
                     thRet = ClassLoader::LoadTypeDefThrowing(pGenericTypeModule, tkGenericType, ClassLoader::ThrowIfNotFound, ClassLoader::PermitUninstDefOrRef, 0, level);
+                    if (thRet.AsMethodTable()->GetInstantiation()[0] == pMTInterfaceMapOwner->GetSpecialInstantiationType())
+                    {
+                        // We loaded the special marker type, but it is ALSO the exact expected type which isn't a valid combination
+                        // In this case return something else (object) to indicate that
+                        // we found an invalid situation and this function should be retried without the special marker type logic enabled.
```
Comment (jkotas) [inline src/coreclr/vm/siginfo.cpp:1628]: I understand what this does, but I do not see the condition that will catch System.Object returned from here and retry. Maybe highlight it with a comment so that it is easier to see?

File: src/coreclr/vm/siginfo.cpp [hunk 13]
```diff
@@ -1618,9 +1618,17 @@ TypeHandle SigPointer::GetTypeHandleThrowing(
...
+                        thRet = TypeHandle(CoreLibBinder::GetElementType(ELEMENT_TYPE_OBJECT));
```
Comment (jkotas) [inline src/coreclr/vm/siginfo.cpp]:
```suggestion
                        thRet = TypeHandle(g_pObjectClass);
```
Nit: We have a shortcut for this

**Review by jkotas — APPROVED** [review]
LGTM, it is very subtle maze of corner-cases, so it is easy to miss something.

File: src/coreclr/vm/methodtablebuilder.cpp (hunk 11 above)
Comment (davidwrighton) [reply src/coreclr/vm/methodtablebuilder.cpp:9959]: There is nothing fixed here, but previous to the fixes above, there was I believe a case where we would come out here without filling in the entire table, and that made me just add this cheap bit of insurance.

File: src/coreclr/vm/siginfo.cpp (hunk 12 above)
Comment (davidwrighton) [reply src/coreclr/vm/siginfo.cpp:1628]: It's here, and was already present in the codebase.

https://github.com/dotnet/runtime/blob/0de4dab981f8bf335eeee4b8c81f44893be019a5/src/coreclr/vm/methodtablebuilder.cpp#L9800C1-L9806C14
