### PR TITLE
profiler tests depend on jit events 

### LINKED ISSUE #34624: Test failure: profiler/eventpipe/eventpipe/eventpipe.sh
failed in job: [runtime-coreclr outerloop 20200406.5](https://dev.azure.com/dnceng/public/_build/results?buildId=590731&view=ms.vss-test-web.build-test-results-tab&runId=18616864&resultId=109463&paneView=debug)

Error message
~~~
cmdLine:/root/helix/work/workitem/profiler/eventpipe/eventpipe/eventpipe.sh Timed Out
Return code: -100
Raw output file: /root/helix/work/workitem/profiler/eventpipe/Reports/profiler.eventpipe/eventpipe/eventpipe.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation. All rights reserved.
Native image eventpipe.dll generated successfully.
in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun eventpipe.dll ''
Profiler path: /root/helix/work/workitem/profiler/eventpipe/eventpipe/libProfiler.so
Profiler path: /root/helix/work/workitem/profiler/eventpipe/eventpipe/libProfiler.so
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
This method being jitted should trigger events firing...
cmdLine:/root/helix/work/workitem/profiler/eventpipe/eventpipe/eventpipe.sh Timed Out
Test Harness Exitcode is : -100
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/profiler/eventpipe/eventpipe/eventpipe.sh
Expected: True
Actual: False


Stack trace
   at profiler_eventpipe._eventpipe_eventpipe_._eventpipe_eventpipe_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/profiler.eventpipe/profiler.eventpipe.XUnitWrapper.cs:line 140
~~~

### LINKED ISSUE #34625: Test failure: The text 'PROFILER TEST PASSES' was not found in the output
failed in job: [runtime-coreclr outerloop 20200406.5](https://dev.azure.com/dnceng/public/_build/results?buildId=590731&view=ms.vss-test-web.build-test-results-tab&runId=18616864&resultId=102170&paneView=debug)

failed tests: 
profiler/rejit/rejit/rejit.sh
profiler/unittest/metadatagetdispenser/metadatagetdispenser.sh

Error message
~~~
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in /__w/1/s/src/coreclr/tests/src/profiler/common/ProfilerTestRunner.cs:line 135
at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in /__w/1/s/src/coreclr/tests/src/profiler/common/ProfilerTestRunner.cs:line 89
at Profiler.Tests.RejitWithInlining.Main(String[] args) in /__w/1/s/src/coreclr/tests/src/profiler/rejit/rejit.cs:line 100
Assert failure(PID 79 [0x0000004f], Thread: 79 [0x004f]): !"Heap contamination detected! HeapFree was called on a heap other than the one that memory was allocated from.
" "Possible cause: you used new (executable) to allocate the memory, but didn't use DeleteExecutable() to free it."
File: /__w/1/s/src/coreclr/src/utilcode/clrhost_nodependencies.cpp Line: 297
Image: 
/root/helix/work/workitem/profiler/rejit/rejit/rejit.sh: line 275: 55 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Return code: 1
Raw output file: /root/helix/work/workitem/profiler/rejit/Reports/profiler.rejit/rejit/rejit.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation. All rights reserved.
Native image rejit.dll generated successfully.
in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun rejit.dll ''
Profiler path: /root/helix/work/workitem/profiler/rejit/rejit/libProfiler.so
Disabling tiered compilation.
Profiler path: /root/helix/work/workitem/profiler/rejit/rejit/libProfiler.so
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
INFO Initialize - Initialize started
INFO JITCompilationStarted - jitting started for StelemRef in module /root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inliner=StelemRef Inlinee=As<System.__Canon> Inlinee module name=/root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inliner=StelemRef Inlinee=GetMethodTable Inlinee module name=/root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inliner=StelemRef Inlinee=GetMethodTable Inlinee module name=/root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITCompilationStarted - jitting started for LdelemaRef in module /root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inliner=LdelemaRef Inlinee=As<System.__Canon> Inlinee module name=/root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inliner=LdelemaRef Inlinee=GetMethodTable Inlinee module name=/root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inliner=LdelemaRef Inlinee=ThrowArrayMismatchException Inlinee module name=/root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITCompilationStarted - jitting started for IndexOf in module /root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inliner=IndexOf Inlinee=Assert Inlinee module name=/root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inliner=IndexOf Inlinee=AsPointer<System.Char> Inlinee module name=/root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inliner=IndexOf Inlinee=Add<System.Char> Inlinee module name=/root/helix/work/correlation/System.Private.CoreLib.dll
INFO JITInlining - Inlining occurred! Inlin


Stack trace
   at profiler_rejit._rejit_rejit_._rejit_rejit_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/profiler.rejit/profiler.rejit.XUnitWrapper.cs:line 140
~~~

### PR DESCRIPTION
**Pull request by davmason**
Fixes #34625
Fixes #34624

The profiler tests use jit events for some synchronization, running them crossgenned causes them to break. Having them test if you can disable crossgen bits with `COR_PRF_DISABLE_ALL_NGEN_IMAGES` is an interesting scenario so I would prefer to fix it this way rather than prevent them running under crossgen.

### CODE REVIEW

**Comment by davmason** [comment]
@hoyosjs do you know how to trigger the outerloop jobs on a PR so I can validate that it fixes those tests?

**Comment by hoyosjs** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=598956&view=results

**Comment by davmason** [comment]
Thanks @hoyosjs!

**Comment by noahfalk** [comment]
> The profiler tests use jit events for some synchronization, running them crossgenned causes them to break. Having them test if you can disable crossgen bits with COR_PRF_DISABLE_ALL_NGEN_IMAGES is an interesting scenario so I would prefer to fix it this way rather than prevent them running under crossgen.

I agree that having the tests run under crossgen at all is better than having the test disabled, though better still would be having the tests work without disabling crossgen images. Presumably we'd recommend profiler vendors not to disable crossgen if they want the best performance. Generally we'd want to have the majority of our test coverage aligned with patterns we are telling profiler developers to use.

File: src/coreclr/tests/src/profiler/native/eventpipeprofiler/eventpipeprofiler.cpp [hunk 1]
```diff
@@ -24,7 +24,7 @@ HRESULT EventPipeProfiler::Initialize(IUnknown* pICorProfilerInfoUnk)
     }
 
     // No event mask, just calling the EventPipe APIs.
-    if (FAILED(hr = _pCorProfilerInfo12->SetEventMask2(COR_PRF_MONITOR_JIT_COMPILATION, 0)))
+    if (FAILED(hr = _pCorProfilerInfo12->SetEventMask2(COR_PRF_MONITOR_JIT_COMPILATION | COR_PRF_DISABLE_ALL_NGEN_IMAGES, 0)))
```
Comment (noahfalk) [inline src/coreclr/tests/src/profiler/native/eventpipeprofiler/eventpipeprofiler.cpp:27]: I would comment all of these and detail why the DISABLE_ALL_NGEN_IMAGES flag has been set. Otherwise someone might assume it is a requirement for using the feature rather than a requirement due to a specific independent implementation choice in the test code.

**Review by noahfalk — APPROVED** [review]
LGTM, modulo some comments

**Comment by davmason** [comment]
@noahfalk can you take a look again? I updated the tests to run without disabling R2R modules and found a bug in the RequestReJITWithInliners api. 

Basically it wouldn't work properly for R2R modules because the DomainAssemblyIterator won't iterate any assemblies unless the execute flag is passed in, and then the NativeImageInliningIterator also had an off by one error and would skip the first entry,

**Comment by davmason** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=601370&view=results is the new outerloop run

File: src/coreclr/src/vm/rejit.cpp [hunk 2]
```diff
@@ -462,35 +463,38 @@ HRESULT NativeImageInliningIterator::Reset(Module *pModule, MethodDesc *pInlinee
...
     m_currentPos++;
-    return m_currentPos < m_dynamicBufferSize;
+    _ASSERTE(m_currentPos >= 0);
+    return m_currentPos < m_dynamicAvailable;
 }
 
 MethodDesc *NativeImageInliningIterator::GetMethodDesc()
 {
-    if (m_currentPos == (COUNT_T)-1 || m_currentPos >= m_dynamicBufferSize)
+    if (m_currentPos == s_failurePos || m_currentPos >= m_dynamicAvailable)
```
Comment (noahfalk) [inline src/coreclr/src/vm/rejit.cpp:497]:
```suggestion
    // this evaluates true when m_currentPos == s_failurePos or m_currentPos == (COUNT_T)-1
    // m_currentPos is an unsigned type
    if (m_currentPos >= m_dynamicAvailable) 
```

File: src/coreclr/src/vm/rejit.cpp [hunk 3]
```diff
@@ -462,35 +463,38 @@ HRESULT NativeImageInliningIterator::Reset(Module *pModule, MethodDesc *pInlinee
...
 {
-    if (m_currentPos < 0)
+    if (m_currentPos == s_failurePos)
     {
         return FALSE;
     }
 
     m_currentPos++;
-    return m_currentPos < m_dynamicBufferSize;
+    _ASSERTE(m_currentPos >= 0);
```
Comment (noahfalk) [inline src/coreclr/src/vm/rejit.cpp:491]: This assert is always true, m_currentPos is an unsigned type

**Review by noahfalk — APPROVED** [review]
Couple nits in there, lgtm!

**Comment by davmason** [comment]
There appears to have been some CI issues yesterday, I just rebased on the latest master and hopefully that solves it.
