### PR TITLE
Constrained mask should take into account busy registers

### LINKED ISSUE #59916: Assertion failed 'GenTree::OperIsCommutative(oper)' during 'Generate code'
Found by Antigen, fails on windows-x86.

```c#
public class new_issue
{
    static bool s_bool_5 = true;
    byte byte_25 = 1;
    int int_30 = 5;
    public void Method0()
    {
        unchecked
        {
            byte byte_150 = 1;
            if (15 << 4 <= 15 << 4)
            {
                if (15 % 4 < 15 + 4)
                {
                    if (s_bool_5)
                    {
                    }
                    else
                    {
                        byte_25 *= byte_25 *= (byte)((byte_150 = byte_25 <<= int_30) - byte_150);
                    }
                }
            }
            return;
        }
    }
    public static void Main(string[] args)
    {
        new new_issue().Method0();
    }
}

/*
COMPlus_TieredCompilation=0
COMPlus_JitDoSsa=0
COMPlus_JitStressRegs=8

Assert failure(PID 17236 [0x00004354], Thread: 348 [0x015c]): Assertion failed 'GenTree::OperIsCommutative(oper)' in 'TestClass:Method0():this' during 'Generate code' (IL size 20866)
    File: D:\workspace\_work\1\s\src\coreclr\jit\codegenxarch.cpp Line: 925
    Image: C:\h\w\A53108F1\p\CoreRoot\corerun.exe

*/
```

I took a quick look at this and seems like while generating binary operator, we expect that when `op2
Reg == targetReg`, the operator is commutative, but in this case, it is `GT_SUB`. The 2 operands are coming from same source, so it doesn't matter that the swap of operands happen, but it looks like either the condition at https://github.com/dotnet/runtime/blob/b72b8a2a8c17c6347e99d61e08f8501aa079933d/src/coreclr/jit/codegenxarch.cpp#L923-L928 need to take that into account or there must be something wrong before codegen. I will investigate it further.

Below, before code is what is generated (if we comment out the assert that is hit), and after is the one that is generated if we also check if the `GenTree::OperIsCommutative(oper)` before swapping the operands. In the after case, the `mov` is kind of redundant, but there might be other scenarios where it could go wrong.

```diff
 G_M34695_IG03:              ;; offset=0024H
        0FB65E08     movzx    ebx, byte  ptr [esi+8]
@@ -46,7 +46,8 @@ G_M34695_IG03:              ;; offset=0024H
        885E08       mov      byte  ptr [esi+8], bl
        8BF9         mov      edi, ecx
        8BD9         mov      ebx, ecx
-       2BDF         sub      ebx, edi
+       8BDF         mov      ebx, edi
+       2BDB         sub      ebx, ebx
        0FB6DB       movzx    ebx, bl
        0FAF1C24     imul     ebx, dword ptr [esp]
        0FB6DB       movzx    ebx, bl
```

Note: In before case, `sub ebx ebx` can be peep hole optimized to `xor ebx, ebx`.

category:correctness
theme:codegen

### LINKED ISSUE #76382: JIT arm32: Assertion failed 'refPosition->RegOptional()' in 'System.Numerics.Tests.ComplexTests:Abs(double,double)' during 'LSRA build intervals'  when using non-standard arg sort
1. Comment the code in `CallArgs::SortArgs` that does the sort (everything after the initial loop that assigns `sortedArgs`)
2. Run superpmi replay over arm32 with `COMPlus_JitStressRegs=3`

Result:
```
[22:19:58] ISSUE: <ASSERT> #271154 D:\a\_work\1\s\src\coreclr\jit\lsra.cpp (11934) - Assertion failed 'refPosition->RegOptional()' in 'System.Numerics.Tests.ComplexTests:Abs(double,double)' during 'LSRA build intervals' (IL size 22; hash 0xbf3bc3d1; FullOpts)
```

category:correctness
theme:register-allocator

### LINKED ISSUE #85627: Assertion failed 'refPosition->RegOptional()' during 'LSRA build intervals'
```cs
// Found by Antigen

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
        public ulong ulong_0;
        public ulong ulong_1;
        public ulong ulong_2;
    }
    public struct S2
    {
    }
    static int s_int_10 = 4;
    static S1 s_s1_18 = new S1();
    static S2 s_s2_19 = new S2();
    int int_26 = 0;
    S1 s1_34 = new S1();
    S2 s2_35 = new S2();
    public int LeafMethod6()
    {
        unchecked
        {
            return s_int_10;
        }
    }
    public S1 Method70(out S2 p_s2_1795, ref S1 p_s1_1796, out S2 p_s2_1797, S2 p_s2_1798, decimal p_decimal_1799, ref S1 p_s1_1800, S1 p_s1_1801, ref ulong p_ulong_1802, float p_float_1803, ref S2 p_s2_1804, out int p_int_1805, out S1 p_s1_1806, out S2 p_s2_1807)
    {
        unchecked
        {
            int int_1814 = 0;
            p_int_1805 = int_1814 = 15|4;
            p_s1_1806 = p_s1_1796;
            return s_s1_18;
        }
    }
    public void Method0()
    {
        unchecked
        {
            S1 s1_2564 = new S1();
            S2 s2_2565 = new S2();
            s1_34 = Method70(out s2_35, ref s_s1_18, out s2_35, s_s2_19, 15-4, ref s1_34, s1_2564, ref s1_34.ulong_2, 15-4+ LeafMethod6() % 15|4, ref s2_2565, out int_26, out s1_34, out s2_35);
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}

/*
Environment:

set COMPlus_TieredCompilation=0
set COMPlus_JitStressRegs=2
set COMPlus_AltJitName=clrjit_universal_arm_x86.dll
set COMPlus_AltJit=Method0

Assert failure(PID 56464 [0x0000dc90], Thread: 29068 [0x718c]): Assertion failed 'refPosition->RegOptional()' in 'TestClass:Method0():this' during 'LSRA build intervals' (IL size 111; hash 0x46e9aa75; FullOpts)
    File: E:\git\runtime\src\coreclr\jit\lsra.cpp Line: 12414
    Image: e:\git\runtime\artifacts\tests\coreclr\windows.x86.checked\tests\Core_Root\CoreRun.exe
*/

```

### PR DESCRIPTION
**Pull request by kunalspathak**
When we constrained the registers under JitStressRegs, check if the constrained masks is not left with "busy registers" because in that case, we will not be able to allocate register. Relax that and do not constraint if they coincides with "busy registers".

Fixes: https://github.com/dotnet/runtime/issues/85627
(Most likely) fixes: https://github.com/dotnet/runtime/issues/76382

Also noticed a problem where we were not taking into account `SUB_HI` and `LSH_HI` for RMW analysis. Doing that discovered that we should update the assert about Commutative() to take into account if both operands are same. Both of these will fix the following issue:
Fixes: https://github.com/dotnet/runtime/issues/59916

### CODE REVIEW

**Comment by kunalspathak** [comment]
I am seeing superpmi-replay failures similar to one reported in https://github.com/dotnet/runtime/issues/59916.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/lsra.cpp [hunk 1]
```diff
@@ -450,6 +450,7 @@ RegRecord* LinearScan::getRegisterRecord(regNumber regNum)
 // minRegCount registers, otherwise returns regMaskActual.
 //
 // Arguments:
+//     Refposition        -  Refposition for which we want to constaint.
```
Comment (BruceForstall) [inline src/coreclr/jit/lsra.cpp:453]:
```suggestion
//     refPosition        -  RefPosition for which we want to constrain.
```

File: src/coreclr/jit/lsra.cpp [hunk 2]
```diff
@@ -459,15 +460,30 @@ RegRecord* LinearScan::getRegisterRecord(regNumber regNum)
 // Return Value:
 //     New regMask that has minRegCount registers after instersection.
 //     Otherwise returns regMaskActual.
-regMaskTP LinearScan::getConstrainedRegMask(regMaskTP regMaskActual, regMaskTP regMaskConstraint, unsigned minRegCount)
+regMaskTP LinearScan::getConstrainedRegMask(RefPosition* refPosition,
```
Comment (BruceForstall) [inline src/coreclr/jit/lsra.cpp:463]: Make it const?
```suggestion
regMaskTP LinearScan::getConstrainedRegMask(const RefPosition* refPosition,
```

File: src/coreclr/jit/lsra.cpp [hunk 3]
```diff
@@ -459,15 +460,30 @@ RegRecord* LinearScan::getRegisterRecord(regNumber regNum)
...
+                                            regMaskTP    regMaskActual,
+                                            regMaskTP    regMaskConstraint,
+                                            unsigned     minRegCount)
 {
     regMaskTP newMask = regMaskActual & regMaskConstraint;
-    if (genCountBits(newMask) >= minRegCount)
+    if (genCountBits(newMask) < minRegCount)
     {
-        return newMask;
+        // Constrained mask does not have minium required registers needed.
```
Comment (BruceForstall) [inline src/coreclr/jit/lsra.cpp:471]:
```suggestion
        // Constrained mask does not have minimum required registers needed.
```

File: src/coreclr/jit/lsra.cpp [hunk 4]
```diff
@@ -459,15 +460,30 @@ RegRecord* LinearScan::getRegisterRecord(regNumber regNum)
...
+        return regMaskActual;
     }
 
-    return regMaskActual;
+    if ((refPosition != nullptr) && !refPosition->RegOptional())
+    {
+        regMaskTP busyRegs = regsBusyUntilKill | regsInUseThisLocation;
+        if ((newMask & ~busyRegs) == RBM_NONE)
+        {
+            // Constrained mask do not have at least one free register to allocate.
```
Comment (BruceForstall) [inline src/coreclr/jit/lsra.cpp:480]:
```suggestion
            // Constrained mask does not have at least one free register to allocate.
```

File: src/coreclr/jit/codegenxarch.cpp [hunk 5]
```diff
@@ -1010,7 +1010,36 @@ void CodeGen::genCodeForBinary(GenTreeOp* treeNode)
...
+        else if (op2->IsCopyOrReload())
+        {
+            GenTree* copySrc = op2->AsCopyOrReload()->gtGetOp1();
+            if (copySrc->OperIsLocalRead())
+            {
+                lclNum2 = copySrc->AsLclVarCommon()->GetLclNum();
+            }
+        }
+#endif
+        noway_assert(GenTree::OperIsCommutative(oper) || (lclNum1 == lclNum2));
```
Comment (BruceForstall) [inline src/coreclr/jit/codegenxarch.cpp:1042]: In the non-DEBUG code, the noway_assert will never fail now. That seems wrong. Maybe lclNum1/lclNum2 should be initialized to different values? E.g., -1/-2?

**Review by BruceForstall — COMMENTED** [review]
Mostly nits but one question

File: src/coreclr/jit/codegenxarch.cpp (hunk 5 above)
Comment (kunalspathak) [reply src/coreclr/jit/codegenxarch.cpp:1042]: good point. Will fix it.

File: src/coreclr/jit/lsra.cpp (hunk 2 above)
Comment (kunalspathak) [reply src/coreclr/jit/lsra.cpp:463]: need to make `RegOptional()`, etc. `const` and then update its references...

File: src/coreclr/jit/codegenxarch.cpp [hunk 6]
```diff
@@ -1010,7 +1010,36 @@ void CodeGen::genCodeForBinary(GenTreeOp* treeNode)
...
+            lclNum1 = op1->AsLclVarCommon()->GetLclNum();
+        }
+        else if (op1->IsCopyOrReload())
+        {
+            GenTree* copySrc = op1->AsCopyOrReload()->gtGetOp1();
+            if (copySrc->OperIsLocalRead())
+            {
+                lclNum1 = copySrc->AsLclVarCommon()->GetLclNum();
+            }
+        }
```
Comment (BruceForstall) [inline src/coreclr/jit/codegenxarch.cpp:1028]: This could be simpler as:
```suggestion
        GenTree* op1skip = op1->gtSkipReloadOrCopy();
        if (op1skip->OperIsLocalRead())
        {
            lclNum1 = op1skip->AsLclVarCommon()->GetLclNum();
        }
```

same for op2.

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/jit/codegenxarch.cpp (hunk 6 above)
Comment (kunalspathak) [reply src/coreclr/jit/codegenxarch.cpp:1028]: ah, I forgot about `gtSkipReloadOrCopy()`. Let me change it.

File: src/coreclr/jit/codegenxarch.cpp [hunk 7]
```diff
@@ -1010,7 +1010,23 @@ void CodeGen::genCodeForBinary(GenTreeOp* treeNode)
...
+        if (op1Skip->OperIsLocalRead())
+        {
+            lclNum1 = op1Skip->AsLclVarCommon()->GetLclNum();
+        }
+        if (op2Skip->OperIsLocalRead())
+        {
+            lclNum2 = op2Skip->AsLclVarCommon()->GetLclNum();
+        }
+#endif
+        noway_assert(GenTree::OperIsCommutative(oper) || (lclNum1 == lclNum2));
```
Comment (BruceForstall) [inline src/coreclr/jit/codegenxarch.cpp:1029]: I realized this can't be a `noway_assert` now: it would mean we're asserting different things in Release and Debug: and the case where you're asserting `lclNum1 == lclNum2` would fail in Release.

**Review by BruceForstall — CHANGES_REQUESTED** [review]

**Review by BruceForstall — APPROVED** [review]
