### PR TITLE
Fix behavior of default interfaces interacting with constraints

### LINKED ISSUE #79603: Static interface implementation bug
### Description

Application crashes with Fatal error, with no understandable exception (x64) or stackoverflow exception (x86) when trying to instantate an instance of class derived from "Buggyclass" or when calling their static methods. Guess specified calls leads to JITting "Buggyclass" which ends up with exception at JIT compiler.

### Reproduction Steps

With .Net 7 create console application with the following sample:

```csharp
namespace ConsoleApp3
{
    internal class Program
    {
        static void Main(string[] args)
        {
           //both calls leads to crash BEFORE "Main" even got called.
            _ = typeof(Buggyclass).TypeHandle;
            _ = new C2();
        }
    }
    public interface IFactory<TSelf> where TSelf : IFactory<TSelf>
    {
        static abstract TSelf Create();
    }
    public interface IFactoryimpl<TSelf> : IFactory<TSelf> where TSelf : class, IFactory<TSelf>
    {
        static TSelf IFactory<TSelf>.Create() => default;
    }
    public abstract class Buggyclass : IFactoryimpl<Buggyclass> { }
    class C2 : Buggyclass { }
}
```

### Expected behavior

Normal execution expected.

### Actual behavior

Application crashes with code "-1073741819" before even entering method "Main".

### Regression?

_No response_

### Known Workarounds

Found 2 possible workaround:
1) Making "Buggyclass" not abstract – not allways applicable.
2) Making "static abstract TSelf Create()" virtual with some default implementation e.g. throw NotImplementedexception() – also not applicable for interfaces from extarnal libraries.

### Configuration

Version of .NET is 7.0
OS Windows NT 10.0.17763.0
Architecture x64
99% sure crash is not specific to configuration, but internal JIT exceptions may varry.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by davidwrighton**
Fix stack overflow caused by incorrect handling of class load levels

Fixes #79603 and #85159

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Can we rename the test to something like `RecursiveConstraintOnDefaultImplementationOfStaticAbstractMember`? I know it's wordy, but this test is so targeted at a particular scenario it would be nice to have a reference to this somewhere in the test.

File: src/tests/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_79603.cs [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+{
+    internal class Program
+    {
+        static int Main(string[] args)
+        {
+           //both calls leads to crash BEFORE "Main" even got called.
+            _ = typeof(Buggyclass).TypeHandle;
+            _ = new C2();
+            return 100;
+        }
```
Comment (AaronRobinsonMSFT) [inline src/tests/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_79603.cs:14]:
```suggestion
        [Fact]
        public static void AbstractClass()
        {
            _ = typeof(Buggyclass).TypeHandle;
        }

        [Fact]
        public static void ImplClass()
        {
            _ = new C2();
        }
```

File: src/tests/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_79603.cs [hunk 2]
```diff
@@ -0,0 +1,26 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace GitHub_79603
+{
```
Comment (AaronRobinsonMSFT) [inline src/tests/Loader/classloader/StaticVirtualMethods/RegressionTests/GitHub_79603.cs:5]:
```suggestion
using Xunit;
namespace GitHub_79603
{
```

**Review by AaronRobinsonMSFT — APPROVED** [review]
