### PR TITLE
[hot_reload] ignore modified MONO_TABLE_TYPEDEF rows in update

### LINKED ISSUE #90037: WebToolsException when using hot reload to apply change to Blazor WebAssembly app
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WebToolsException-when-using-hot-reload-/10421101)._

---
I got the following error when trying to hot reload a change to my Blazor WebAssemlby app:

```
20:46 51.50 BlazorApp14.Server (Web assembly): Sending updates to running application
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: 
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Exception thrown for Apply Code Updates: 0x80131500 - The following error occurred when trying to apply your edits to the running application. The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Stack trace for WebToolsException:
   at Microsoft.WebTools.ProjectSystem.Components.HotReload.ProjectHotReloadSession.<ApplyUpdatesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Debugger.Shared.Utilities.LoggerExtensions.<LogOnExceptionAsync>d__3.MoveNext()
20:46 51.57 An unexpected error has occurred, any pending updates have been discarded.
```

Repro steps:

- Create an ASP.NET Core hosted Blazor WebAssembly app using .NET 7
- Add Shared/MyLayout.razor to the Client project

```
@inherits LayoutComponentBase
<h1>MyLayout</h1>
<main>
    @Body
</main>
```
- Update Index.razor to include `@layout MyLayout` just below the `@page` directive
- Run the app without debugging
- Remove the `@layout MyLayout` directive from Index.Razor
- Hot reload the change to the running app

---
#### Feedback Bot on 7/23/2023, 05:58 PM: 

(private comment, text removed)
#### Feedback Bot on 7/24/2023, 01:36 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by lambdageek**
We may want to validate that Parent, Interfaces and Attributes columns haven't changed, but it's tricky and might be overly restrictive.

Fixes #90037

### CODE REVIEW

File: src/mono/mono/component/hot_reload.c [hunk 1]
```diff
@@ -1668,7 +1668,15 @@ apply_enclog_pass1 (MonoImage *image_base, MonoImage *image_dmeta, DeltaInfo *de
...
 				continue;
 			}
-			/* fallthru */
+			// don't expect to see any other func codes with this table
+			g_assert (func_code == ENC_FUNC_DEFAULT);
+			if (!is_addition) {
+				// Roslyn sometimes sends this when a custom attribute is deleted from
+				// a type definition.
+				break;
+			}
```
Comment (fanyang-mono) [inline src/mono/mono/component/hot_reload.c:1677]: This seems unnecessary.

**Review by fanyang-mono — APPROVED** [review]

File: src/mono/mono/component/hot_reload.c (hunk 1 above)
Comment (lambdageek) [reply src/mono/mono/component/hot_reload.c:1677]: Yea there was more code here initially, but I wittled it down to just a comment ;-)
