### PR TITLE
Ensure that negation of floating-point values is correctly handled

### LINKED ISSUE #105627: JIT: Wrong constant folding with -0.0f/-0.0d
```csharp
// Run on Arm64 Linux
// Seed: 10489942769529190437-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256
// Reduced from 58.9 KiB to 0.4 KiB in 00:00:28
// Debug: Outputs [9223372036854775808, 9223372036854775808]
// Release: Outputs [0, 0]
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static Vector128<double> s_9;
    public static void Main()
    {
        var vr1 = Vector128.CreateScalar(0d);
        s_9 = AdvSimd.Arm64.Negate(vr1);
        System.Console.WriteLine(s_9.AsUInt64());
    }
}
```
(`DOTNET_TieredCompilation=1` is not enough to repro the debug result, it needs `DOTNET_JITMinOpts=1` in this case)

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #105627

### CODE REVIEW

File: src/coreclr/jit/simd.h [hunk 1]
```diff
@@ -415,18 +430,7 @@ inline double EvaluateUnaryScalarSpecialized<double>(genTreeOps oper, double arg
 template <typename TBase>
 TBase EvaluateUnaryScalar(genTreeOps oper, TBase arg0)
```
Comment (EgorBo) [inline src/coreclr/jit/simd.h:431]: nit: is `EvaluateUnaryScalar` method needed then?

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/simd.h (hunk 1 above)
Comment (tannergooding) [reply src/coreclr/jit/simd.h:431]: It might not be needed, but it's consistent with the setup of other APIs.

If we were to change this, I'd probably make it `EvaluateUnaryScalar` and just specialize that directly instead. That way there isn't two differently named entry points for Unary vs Binary vs ...
