### PR TITLE
Split out and generalize tailcall IR validation/tailcall profile adjustments

### LINKED ISSUE #69939: [libraries-pgo] Assertion failed 'asgNode->OperIs(GT_ASG)' in during 'Morph - Global'
Pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1793017&view=results
Helix job name: net7.0-Linux-Release-arm-CoreCLR_checked-fullpgo-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68703-merge-33cb150c9d8b423793/System.Text.Json.Tests/1/console.9d28c6f6.log?helixlogtype=result

```scala
Assert failure(PID 61 [0x0000003d], Thread: 87 [0x0057]): Assertion failed 'asgNode->OperIs(GT_ASG)' in 'System.ValueTuple`2[__Canon,__Canon][System.__Canon,System.__Canon]:System.IComparable.CompareTo(System.Object):int:this' during 'Morph - Global' (IL size 44; hash 0x21addb67; Tier1)

    File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 6803
    Image: /root/helix/work/correlation/dotnet
```

It looks like we end up with `GT_NOP` after an implicit tailcall, and we fail when trying to validate that the post-tailcall IR looks ok.

### PR DESCRIPTION
**Pull request by jakobbotsch**
* Split the IR validation after tailcalls into a separate function.
  Previously it was intertwined with updating of profile weights for
  follow-up blocks.
* Generalize the validation to use a tree walk and handle more cases.
  This fixes #69939.
* Generalize the updating of profile weights for follow-up blocks.
  Previously this was only updating profile weights for one follow up
  blocks, but there can be an arbitrary number of successor blocks due
  to inlining.

Fix #69939

I was not able to come up with a simple test case. It requires a quite specific sequence of inlines and GDVs to produce IR that ends up with the NOP we were failing on.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS

**Comment by EgorBo** [comment]
that piece of validation caused problems many times already, maybe it's time to just delete it 😄

**Comment by jakobbotsch** [comment]
> that piece of validation caused problems many times already, maybe it's time to just delete it 😄

I think the problematic part here is having the complicated IR after tailcalls, ideally we should teach the inliner to avoid all this no-op IR it adds instead so that we can validate this condition much easier. I do think we should have validation that the tailcalls we are doing are legal.

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -7069,6 +6990,168 @@ GenTree* Compiler::fgMorphPotentialTailCall(GenTreeCall* call)
...
+                return WALK_ABORT;
+            }
+
+            // GT_NOP might appear due to assignments that end up as
+            // self-assignments, which get morphed to GT_NOP.
+            if (tree->OperIs(GT_NOP))
+            {
+            }
+            // No-op casts may appear due to normalization during inlining. Example:
+            //  ▌  RETURN    int
```
Comment (SingleAccretion) [inline src/coreclr/jit/morph.cpp:7052]: Q: are we ok with using non-ASCII characters in source code?

Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp]: Made it into the ASCII format to be safe, although we do have some unicode chars in the VM it seems (the apostrophes): https://github.com/dotnet/runtime/blob/4719135a5fd6c9f22ce429ad8a211d696eae0426/src/coreclr/vm/codeman.cpp#L1331-L1334

**Comment by jakobbotsch** [comment]
Gonna rerun jitstress now that we've merged #69946...

**Comment by jakobbotsch** [comment]
Most of the libraries-jitstress runs failed with "A call to an Azure DevOps api returned 401, which may indicate a bad 'System.AccessToken' value.", will give it another retry.

File: src/coreclr/jit/morph.cpp (hunk 1 above)
Comment (am11) [reply src/coreclr/jit/morph.cpp]: > Q: are we ok with using non-ASCII characters in source code?

Yup, it is safe. We have [`source-charset`](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170) set to `utf-8` globally:
https://github.com/dotnet/runtime/blob/842b6a87aaa6b6f25555541f541d5ee202d3972a/eng/native/configurecompiler.cmake#L648 (and Unix-y toolchains have UTF-8 by default).

**Comment by jakobbotsch** [comment]
Sigh, the failure was #69854. Hopefully I've fixed it for libraries-jitstress now.

**Review by AndyAyersMS — APPROVED** [review]
