### PR TITLE
Fix leak caused by not disposing the scoped parent service provider

### LINKED ISSUE #73832: DependencyInjectionEventSource Memory leak
.net core 6.0.400-preview.22330.6

my code

image

Memory analysis

image

reason , HubConnectionBuilder.Build function

image

Add instance to DependencyInjectionEventSource._providers when ServiceProvider is created，but it can't remove when serviceprovider has no reference

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/73832

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @ericstj

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 1]
```diff
@@ -187,12 +187,17 @@ static async ValueTask Await(int i, ValueTask vt, List<object> toDispose)
...
 
-                // ResolvedServices is never cleared for singletons because there might be a compilation running in background
-                // trying to get a cached singleton service. If it doesn't find it
-                // it will try to create a new one which will result in an ObjectDisposedException.
+            }
 
-                return _disposables;
+            if (IsRootScope)
+            {
+                RootProvider.Dispose();
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:194]: It may help to add a comment here explaining the situation and the reasoning.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs [hunk 2]
```diff
@@ -17,5 +18,16 @@ public void DoubleDisposeWorks()
             serviceProviderEngineScope.Dispose();
             serviceProviderEngineScope.Dispose();
         }
+
+        [Fact]
+        public void RootDisposeTest()
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs:23]:
```suggestion
        public void RootEngineScopeDisposeTest()
```

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 1 above)
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:194]: Are we OK with the extra loop a Dispose will cause now?

Before:
`ServiceProvider.Dispose()` => `ServiceProviderEngineScope.Dispose()`

Now:
`ServiceProvider.Dispose()` => `ServiceProviderEngineScope.Dispose()` => `ServiceProvider.Dispose()` => `ServiceProviderEngineScope.Dispose()` (which finally breaks out of the cycle.

We could fix this (if necessary) by checking `if (IsRootScope && !RootProvider._disposed)`.

Comment (tarekgh) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:194]: I thought about that and didn't like to change _disposed to be not private. I don't have a strong feeling though. If you think is worth it I can apply it.

Comment (tarekgh) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:194]: Thinking more, I think it is ok to introduce IsDisposed. I'll do that.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 3]
```diff
@@ -189,8 +189,11 @@ static async ValueTask Await(int i, ValueTask vt, List<object> toDispose)
 
             }
 
-            if (IsRootScope)
+            if (IsRootScope && !RootProvider.IsDisposed())
             {
+                // If this ServiceProviderEngineScope instance is a root scope, disposing this instance will need to dispose the RootProvider too.
+                // Otherwise the RootProvider will never get disposed and will leak.
+                // Note, if the RootProvider get disposed first, it will automatically dispose all attached ServiceProviderEngineScope objects.
                 RootProvider.Dispose();
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:197]: Why cant this just noop internally?

Comment (tarekgh) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:197]: It is simpler. no? 

More code, more bugs :-)

**Review by eerhardt — APPROVED** [review]
LGTM

**Review by davidfowl — APPROVED** [review]

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 3 above)
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:197]: > Why cant this just noop internally?

By "just noop internally", you mean adding the `if` check in `ServiceProvider` Dispose?

Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:197]: Yep.
