### PR TITLE
Restore personality routine outside Windows

### LINKED ISSUE #115321: Test failure:  JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.cmd
**Failed in:** [runtime-coreclr r2r-extra 20250504.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1033348&view=ms.vss-test-web.build-test-results-tab&runId=27761912&resultId=123376&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked jitstress1_tiered @ osx.13.arm64.open
    - JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.cmd
```

**Error message:**
```
 DOTNET_DbgEnableMiniDump is set and the createdump binary does not exist: /private/tmp/helix/working/A8B609A5/p/crossgen2/createdump

Return code:      1
Raw output file:      /tmp/helix/working/A8B609A5/w/AE6E0985/uploads/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/IL-CG2/b425314.dll
23:56:04
Response file: /private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.dll.rsp
/private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/IL-CG2/b425314.dll
-o:/private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.dll
--targetarch:arm64
--targetos:osx
--verify-type-and-field-layout
--method-layout:random
-r:/tmp/helix/working/A8B609A5/p/System.*.dll
-r:/tmp/helix/working/A8B609A5/p/Microsoft.*.dll
-r:/tmp/helix/working/A8B609A5/p/xunit.*.dll
-r:/tmp/helix/working/A8B609A5/p/mscorlib.dll
-r:/tmp/helix/working/A8B609A5/p/netstandard.dll
Running CrossGen2:  /tmp/helix/working/A8B609A5/p/crossgen2/crossgen2 @/private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.dll.rsp   -r:/private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/IL-CG2/*.dll
Emitting R2R PE file: /private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.dll
Running R2RDump:  dotnet /tmp/helix/working/A8B609A5/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.dll --out /private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.dll.r2rdump --val
23:56:04
in ReleaseLock
in takeLock
/tmp/helix/working/A8B609A5/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true b425314.dll ''
Timeout: The `CastClass' scenario exceeded the time limit (180s) without reaching the basic work thresholds.
Timeout: The `Unbox' scenario exceeded the time limit (180s) without reaching the basic work thresholds.
GenericMethod: Checks=40022194, Flips=55196664, Elapsed=00:00:03.1504940
2 exceptions were thrown
System.Exception: Timeout: The `CastClass' scenario exceeded the time limit (180s) without reaching the basic work thresholds.


System.Exception: Timeout: The `Unbox' scenario exceeded the time limit (180s) without reaching the basic work thresholds.


System.Exception: Failure
   at Mutate.TestEntryPoint()
Test FAILED
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   101
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/arcade/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 174
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/arcade/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 96
   at __GeneratedMainWrapper.Main()
in ReleaseLock
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 5/4/2025 11:56:04 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/A8B609A5/w/AE6E0985/e/JIT/Regression/Regression_1/../CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/arcade/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/arcade/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor249|0_250(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
#115083 removed this outside Windows based on the discussion https://github.com/dotnet/runtime/pull/115083#discussion_r2064004352.

But `IsIPInEpilog` seems to depend on this to be set:
https://github.com/dotnet/runtime/blob/a76c0084e9edba3aa6ed60f8d0e07e06acfef94a/src/coreclr/vm/excep.cpp#L6867-L6880

This breaks hijacking outside Windows.

Fix #115321

### CODE REVIEW

**Review by filipnavara — APPROVED** [review]

**Review by jkotas — APPROVED** [review]
Thank you for fixing this!

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -11397,7 +11397,7 @@ void reservePersonalityRoutineSpace(uint32_t &unwindSize)
     _ASSERTE(IS_ALIGNED(unwindSize, sizeof(ULONG)));
 #endif // TARGET_AMD64
 
-#if !defined(TARGET_X86) && defined(TARGET_WINDOWS)
+#ifndef TARGET_X86
     // Add space for personality routine
     unwindSize += sizeof(ULONG);
 #endif //  !TARGET_X86 && TARGET_WINDOWS
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:11403]:
```suggestion
#endif //  !TARGET_X86
```

**Comment by am11** [comment]
Thanks!
wasm build failure seem related.

**Comment by jakobbotsch** [comment]
/ba-g Installer build and test actually succeeded when looking at the console log manually (https://helix.dot.net/api/jobs/87aee799-4b70-4745-9564-0daadc53e3d0/workitems/HostActivation.Tests?api-version=2019-06-17). The other failure is a build failure being fixed by #115767
