### PR TITLE
Intrinsify Enum.Equals to avoid boxing

### LINKED ISSUE #122684: Enum.Equals boxes its arguments and is not inlined
### Description

Given a simple program
```cs
using System;

class Example
{
    static DayOfWeek day = DayOfWeek.Wednesday;

    public static bool Check() => CompareEnums(day, DayOfWeek.Monday);

    static bool CompareEnums<T>(T left, T right)
        where T : struct, Enum => left.Equals(right);
}
```
It appears that within `Check` both `day` and constant `DayOfWeek.Monday` are boxed first before calling into `Enum.Equals(object)`:
```asm
Example:Check():bool (FullOpts):
       push     r15
       push     r14
       push     rbx
       test     byte  ptr [(reloc 0x7aa30846b558)], 1      ; global ptr
       je       SHORT G_M11451_IG05
G_M11451_IG03:  ;; offset=0x000E
       mov      ebx, dword ptr [(reloc 0x7aa3071ab078)]      ; static handle
       mov      r15, 0x7AA30846B448      ; System.DayOfWeek
       mov      rdi, r15
       call     CORINFO_HELP_NEWSFAST
       mov      r14, rax
       mov      dword ptr [r14+0x08], 1
       mov      rdi, r15
       call     CORINFO_HELP_NEWSFAST
       mov      dword ptr [rax+0x08], ebx
       mov      rdi, rax
       mov      rsi, r14
       pop      rbx
       pop      r14
       pop      r15
       tail.jmp [System.Enum:Equals(System.Object):bool:this]
G_M11451_IG05:  ;; offset=0x004D
       mov      rdi, 0x7AA30846B4E0      ; Example
       call     CORINFO_HELP_GET_NONGCSTATIC_BASE
       jmp      SHORT G_M11451_IG03
```
https://godbolt.org/z/64v48e7fM

I was expecting this to be completely zero-cost but apparently not?

### Configuration

dotnet/runtime commit 671cd1276ba8aa75770deaf0a511e80d5a7dfce1

### Regression?

No

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/122684

```cs
bool Test<T>(T a, T b) => a.Equals(b);
```

Codegen for `Test<MethodImplOptions>` (before):
```asm
; Assembly listing for method Prog:Test[int](int,int):bool:this (FullOpts)
       push     rdi
       push     rsi
       push     rbp
       push     rbx
       sub      rsp, 40
       mov      ebx, edx
       mov      esi, r8d
       mov      rdi, 0x7FF955DF2D68 ; System.Runtime.CompilerServices.MethodImplOptions
       mov      rcx, rdi
       call     CORINFO_HELP_NEWSFAST
       mov      rbp, rax
       mov      dword ptr [rbp+0x08], esi
       mov      rcx, rdi
       call     CORINFO_HELP_NEWSFAST
       mov      dword ptr [rax+0x08], ebx
       mov      rcx, rax
       mov      rdx, rbp
       call     [System.Enum:Equals(System.Object):bool:this]
       nop      
       add      rsp, 40
       pop      rbx
       pop      rbp
       pop      rsi
       pop      rdi
       ret      
; Total bytes of code 70
```

Codegen for `Test<MethodImplOptions>` (after):
```asm
; Assembly listing for method Prog:Test[int](int,int):bool:this (FullOpts)
       cmp      edx, r8d
       sete     al
       movzx    rax, al
       ret      
; Total bytes of code 10
```

Technically, we could also make [Enum.Equals](https://github.com/dotnet/runtime/blob/6f515aea251306da07353628fa9036aaa965925d/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L1190-L1248) inlineable and intrinsify `InternalGetCorElementType`. but that seems to be more fragile.

### CODE REVIEW

**Comment by EgorBo** [comment]
@MihuBot

File: src/coreclr/jit/importercalls.cpp [hunk 1]
```diff
@@ -1571,7 +1581,62 @@ var_types Compiler::impImportCall(OPCODE                  opcode,
...
+    CORINFO_CLASS_HANDLE cls0 = gtGetClassHandle(arg0, &isArg0Exact, &isNonNull);
+    CORINFO_CLASS_HANDLE cls1 = gtGetClassHandle(arg1, &isArg1Exact, &isNonNull);
+
+    if ((cls0 != cls1) || (cls0 == NO_CLASS_HANDLE) || !isArg0Exact || !isArg1Exact)
+    {
+        return nullptr;
+    }
+
+    CORINFO_CLASS_HANDLE underlyingEnumCls;
+    if (info.compCompHnd->isEnum(cls1, &underlyingEnumCls) != TypeCompareState::Must)
```
Comment (jkotas) [inline src/coreclr/jit/importercalls.cpp]: Why is this check needed?

**Comment by EgorBo** [comment]
> > Technically, we could also make [Enum.Equals](https://github.com/dotnet/runtime/blob/6f515aea251306da07353628fa9036aaa965925d/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L1190-L1248) inlineable and intrinsify `InternalGetCorElementType`. but that seems to be more fragile.
> 
> Intrinsifying `InternalGetCorElementType` seems more beneficial to me, as it also covers `GetHashCode`, `GetNames`, `GetUnderlyingValue` etc. See https://github.com/search?q=repo%3Adotnet%2Fruntime%20InternalGetCorElementType&type=code

GetHashCode has no CQ issues it seems. Other use-cases seem to be in huge methods which require inlining to benefit from it and rely on escape analysis heavily. My initial impl was `InternalGetCorElementType` and the codegen was not pretty.

File: src/coreclr/jit/importercalls.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp]: > Why is this check needed?

Not really needed judging by the managed impl, although, it does have a `Debug.Assert(rt.IsActualEnum)` so I converted the check to an [assert](https://github.com/dotnet/runtime/blob/52746629166f04db4d8948f0244d002409edfa74/src/coreclr/System.Private.CoreLib/src/System/Enum.CoreCLR.cs#L20).

File: src/coreclr/jit/importercalls.cpp [hunk 2]
```diff
@@ -1003,6 +1003,16 @@ var_types Compiler::impImportCall(OPCODE                  opcode,
...
+
+                    if (call->AsCall()->IsSpecialIntrinsic(this, NI_System_Enum_Equals))
+                    {
+                        GenTree* folded = impFoldEnumEquals(call->AsCall());
+                        if (folded)
+                        {
+                            impPushOnStack(folded, typeInfo(folded->TypeGet()));
+                            return folded->TypeGet();
+                        }
+                    }
```
Comment (tannergooding) [inline src/coreclr/jit/importercalls.cpp]: It seems "unfortunate" to only do this in import, as it will miss cases that can occur post inlining or other scenarios.

We have the functionality to either import this as a `GenTreeIntrinsic` or to keep it as a `GenTreeCall` and to have value numbering, morph, and general `gtFoldExpr` light up for this at "any point" where the value becomes constant.

Is there a reason we're not taking advantage of that? Some throughput hit or similar?

**Review by tannergooding — APPROVED** [review]
Logic looks correct and fine to merge, but I think it's worth investigating if doing this in morph (ideally via handling in `gtFoldExpr`) and potentially having proper value numbering is worthwhile.

File: src/coreclr/jit/importercalls.cpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp]: @tannergooding this optimization relies on escape analysis which is, unfortunately, also only happening early (earlier than global-morph). We basically want the object-allocation phase to remove the boxing we unbox here.

Comment (tannergooding) [reply src/coreclr/jit/importercalls.cpp]: Gotcha. Makes sense why it's limited then (a comment might be nice, but isn't necessary).

I wonder if this is something that we can handle a bit later for core special intrinsics, like this one, where we can effectively state "the box here will never escape or be mutated by the call, so it is safe to look through it"

Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp]: > Gotcha. Makes sense why it's limited then (a comment might be nice, but isn't necessary).
> 
> I wonder if this is something that we can handle a bit later for core special intrinsics, like this one, where we can effectively state "the box here will never escape or be mutated by the call, so it is safe to look through it"

The optimization basically doesn't care if it escapes or not, it unboxes and compare contents for known types. If the boxing doesn't escape anywhere else (this opt can't prove it generally), the EA handles it, if it does escape - the opt still, sort of, optimizes the code, but the two (or just) allocation remains making the opt almost useless. I think the general problem is the escape analysis being early only (presumably, mainly due to struct promotion being early-only too).

Comment (tannergooding) [reply src/coreclr/jit/importercalls.cpp]: Isn't there a fairly measurable perf and potential downstream perf benefit even if the boxing isn't removed (and perhaps the boxing can be avoided later by seeing its "dead" if that was its only use)?

The boxing is an unfortunate part, but being able to get a constant out or otherwise do a direct comparison of the values seems to be beneficial as well, since it can avoid the more costly call (which does many checks and a switch over the element type).

Comment (tannergooding) [reply src/coreclr/jit/importercalls.cpp]: (and don't consider this convo blocking at all, happy to see this merged with the current handling)

Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp]: > Isn't there a fairly measurable perf and potential downstream perf benefit even if the boxing isn't removed 

It's possible, I didn't measure - the current managed impl is here https://github.com/dotnet/runtime/blob/6f515aea251306da07353628fa9036aaa965925d/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L1190-L1248 but since the original report was complaining on GC allocations, I was focusing on them 🙂

Comment (tannergooding) [reply src/coreclr/jit/importercalls.cpp]: Thanks! Makes sense.

I do think it might be worth investigating, but it can be done in the future.

Comment (AndyAyersMS) [reply src/coreclr/jit/importercalls.cpp]: Note there are ways to remove boxes later without escape analysis, `gtFoldExprSpecial` already does this (via `gtTryRemoveBoxUpstreamEffects`). Escape analysis is generally only needed when the box has multiple uses.

File: src/coreclr/jit/importercalls.cpp [hunk 3]
```diff
@@ -1003,6 +1003,16 @@ var_types Compiler::impImportCall(OPCODE                  opcode,
                 if ((callInfo->methodFlags & CORINFO_FLG_INTRINSIC) != 0)
                 {
                     call->AsCall()->gtCallMoreFlags |= GTF_CALL_M_SPECIAL_INTRINSIC;
+
+                    if (call->AsCall()->IsSpecialIntrinsic(this, NI_System_Enum_Equals))
+                    {
+                        GenTree* folded = impFoldEnumEquals(call->AsCall());
+                        if (folded)
+                        {
```
Comment (AndyAyersMS) [inline src/coreclr/jit/importercalls.cpp]: Maybe call `gtFoldExpr` here on the result?

**Review by AndyAyersMS — COMMENTED** [review]
You could also reinvoke `impFoldEnumEquals` in `fgMorphCall`, there is already a check there for retrying opts for some special intrinsics. Not sure if that will do much.

**Comment by EgorBo** [comment]
@tannergooding @AndyAyersMS moved to `gtFoldCallExpr`. I had to call it explicitly because the call appears after `impDevirtualize` so the next time we call `gtFoldExpr` is Global Morph which is too late for the escape analysis. I didn't try to remove the boxing by hands if it's there because there is just one hit across all collections we have, so just rely on the Escape Analysis to keep it simple

File: src/coreclr/jit/importercalls.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp]: Addressed

**Review by tannergooding — APPROVED** [review]
