### PR TITLE
Get ThreadContext for AVX registers

### LINKED ISSUE #78991: NullReferenceException when you use the short format of string.format $"{sample}" when debugging .NET 7 on x64 macOS
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NullReferenceException-when-you-use-the-/10205413)._

---
[severity:I'm unable to use this version] [regression] [worked-in:net 6]
When you use the short format $"{sample}" to concatenate/format a string with variables you get this if is inside a try/catch

I have this piece of code:

```
[Fact]
public void NullReferenceException()
{
    var cname = "component";
    var callerName = "caller";
    var message = "message";

    string text = null;
    string textFormat = null;
    string textNRE = null;

    textNRE = $"{cname}.{callerName}: {message}"; // this works fine ;0

    try
    {
        text = cname + "." + callerName + ": " + message;
        textFormat = string.Format("{0}.{1}: {2}", cname, callerName, message);
        textNRE = $"{cname}.{callerName}: {message}"; // this throws the NullReferenceException
    }
    catch (Exception exp)
    { }
}
```
The given exception message is:
>Object reference not set to an instance of an object.

Stack trace: 
>   at System.Buffer.Memmove(Byte& dest, Byte& src, UIntPtr len)
   at System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(String value)
   at framework.POCs.NullReferenceException() in /Users/jmrpineda/Projects/GitHub/PinedaTec.eu/InGameServices/arn/arn.test/framework/POCs.cs:line 63

I marked this issue as stopper due I have a lot of lines using this try/catch and short string format

If you need additional info, please ask me

thanks, regards

---
#### Feedback Bot on 11/17/2022, 06:08 PM: 

(private comment, text removed)
#### Josema R. Pineda on 11/17/2022, 11:15 PM: 

(private comment, text removed)
#### Josema R. Pineda on 11/18/2022, 00:13 AM: 

(private comment, text removed)
#### Feedback Bot on 11/29/2022, 08:59 AM: 

(private comment, text removed)
#### Feedback Bot on 11/29/2022, 11:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by mikelle-rogers**
In MachExceptionInfo constructor, update the AVX registers using thread_get_state.
This fixes #78991. 
We found that the null reference exception happened because we were not updating the upper half of the ymm register in the MachExceptionInfo. This caused only part of a structure to be copied from the ymm register to a new location. Instead of the second half of the structure in the new location, there were zeros.

### CODE REVIEW

File: src/coreclr/pal/src/thread/context.cpp [hunk 1]
```diff
@@ -1717,6 +1717,12 @@ CONTEXT_GetThreadContextFromThreadState(
             CONTEXT_GetThreadContextFromThreadState((thread_state_flavor_t)pState->fsh.flavor, (thread_state_t)&pState->ufs, lpContext);
         }
         break;
+    case x86_AVX_STATE:
```
Comment (jkotas) [inline src/coreclr/pal/src/thread/context.cpp:1720]: Does this need to handle `x86_AVX512_STATE` as well?

File: src/coreclr/pal/src/exception/machexception.cpp [hunk 2]
```diff
@@ -681,9 +682,24 @@ HijackFaultingThread(
     BuildExceptionRecord(exceptionInfo, &exceptionRecord);
 
 #if defined(HOST_AMD64)
+    int cpuFeatures = minipal_getcpufeatures();
```
Comment (jkotas) [inline src/coreclr/pal/src/exception/machexception.cpp:685]: `minipal_getcpufeatures` is not a cheap method. I am not sure whether it is ok to call it for each hijack.

Comment (janvorli) [reply src/coreclr/pal/src/exception/machexception.cpp:685]: This call and all of the related checks are not necessary. The `CONTEXT_GetThreadContextFromThreadState` can be passed the x86_AVX512_STATE instead of x86_FLOAT_STATE unconditionally and it will return AVX512, AVX or FLOAT state depending on what's available on the current thread. It will also update the `XStateFeaturesMask` on the context based on that.

File: src/coreclr/pal/src/thread/context.cpp (hunk 1 above)
Comment (janvorli) [reply src/coreclr/pal/src/thread/context.cpp:1720]: Is this really needed? I have thought that the x86_AVX_STATE64 / x86_AVX512_STATE64 would be the only ones that we would get on 64 bit CPUs. The x86_avx_state_t is a union containing x86_avx_state64_t or x86_avx_state32_t and we don't support 32 bit x86 on macos.

Comment (mikelle-rogers) [reply src/coreclr/pal/src/thread/context.cpp:1720]: On line 1294 of machexception.cpp, there is a call to `thread_get_state`. I tried calling `thread_get_state` with the second parameter as x86_AVX_STATE64, but that returned an invalid argument error. When I changed the second parameter to x86_AVX_STATE, `thread_get_state` returned with no errors. 

This is why I followed the convention of the other thread states and recursively called `Context_GetThreadContextFromThreadState`. At this point, the thread state will be of type: x86_AVX_STATEz.

File: src/coreclr/pal/src/exception/machexception.cpp [hunk 3]
```diff
@@ -1261,14 +1277,29 @@ MachExceptionInfo::MachExceptionInfo(mach_port_t thread, MachMessage& message)
...
+        count = x86_AVX_STATE_COUNT;
+        machret = thread_get_state(thread, x86_AVX_STATE, (thread_state_t)&AVXState, &count);
+        CHECK_MACH("thread_get_state(avx)", machret);
+    }
+    else
+    {
+        count = x86_FLOAT_STATE_COUNT;
+        machret = thread_get_state(thread, x86_FLOAT_STATE, (thread_state_t)&FloatState, &count);
+        CHECK_MACH("thread_get_state(float)", machret);
+    }
```
Comment (mikelle-rogers) [inline src/coreclr/pal/src/exception/machexception.cpp:1302]: @janvorli Are checks needed for this portion of the code? Or does it work to use lines 1287-1289?

File: src/coreclr/pal/src/thread/context.cpp (hunk 1 above)
Comment (janvorli) [reply src/coreclr/pal/src/thread/context.cpp:1720]: Ah, right, I've forgotten that the OS returns the xx_STATE and we always need to pick the 64 bit one from it (that's what the recursion does). So we need to add case for both `x86_AVX_STATE` and `x86_AVX512_STATE` here

**Comment by jkotas** [comment]
The shape of the change looks good to me now. It will defer to @janvorli to signoff.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!
