### PR TITLE
Avoid populating shared patch bypass buffer after initial creation

### LINKED ISSUE #102767: C# function pointers causes access violation upon calling from C++
### Description

This is a repost of my stackoverflow post, that I have found a temporary solution for [here](https://stackoverflow.com/questions/78510968/c-sharp-function-pointers-causes-access-violation-upon-calling-from-c/78544946#78544946)

C# function pointers causes access violation upon calling from C++

I have tried debugging, but when the issue occurs. In this case C++ calls the callback, but before it enters the function's scope the exception is thrown, but immediately returns with an error code.

For the sake of debugging, I've tried switching the calling convention from `cdecl` to `stdcall` to see if it has to do with stack corruption.

My assumptions are that:

* static functions marked with \[UnmanagedCallersOnly\] have a static address, especially when an entrypoint is defined.
* Thread.BeginThreadAffinity() followed by Thread.EndThreadAffinity() ensures that an unmanaged thread can successfully start executing managed code.

Good to know:

* The function is being invoked by a thread not created in C#, there are many threads calling this function

### Reproduction Steps

In the following bit of code, I'm using C# function pointers to omit using a delegate type, for faster performance. The code works fine when I use a delegate type marshalled as a function pointer, no exception no issues. However, when changing it from a delegate to a function pointer it sometimes throws an access violation.

Code is modified to remove namespaces and prefixes not relevant to the question
```csharp
    public static class Engine
    {
        // Causing issues with sometimes throwing access violation
        [DllImport("engine", CallingConvention = CallingConvention.Cdecl)]
        public static unsafe extern UInt32 EventScheduler_ScheduleLocalEvent(
            int priority, UInt64 delay, delegate* unmanaged[Cdecl]<nint, void> callback, nint obj);

        // Works fine every time, but is much slower seems due to delegate instatiations
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void EventScheduler_ScheduleLocalEvent_callbackDelegate(nint obj);
        [DllImport("engine", CallingConvention = CallingConvention.Cdecl)]
        public static unsafe extern UInt32 EventScheduler_ScheduleLocalEvent(
            int priority,
            UInt64 delay,
            [MarshalAs(UnmanagedType.FunctionPtr)] EventScheduler_ScheduleLocalEvent_callbackDelegate callback,
            nint obj);

    }

    public static class EventScheduler
    {
        public delegate void EventCallback();

        // attribute is only present in the function pointer senario
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl ) }, EntryPoint = "ScheduleLocalEvent_EventCallbackFunction")]
        private static void ScheduleLocalEvent_EventCallbackFunction(nint handlePtr)
        {
            Thread.BeginThreadAffinity();
            GCHandle handle = GCHandle.FromIntPtr(handlePtr);
            var cb          = (EventScheduler.EventCallback)handle.Target!;
            cb();
            handle.Free();
            Thread.EndThreadAffinity();
        }
        public static UInt32 ScheduleLocalEvent(int priority, SimulationTime delayTime, EventCallback eventCallback)
        {
            GCHandle handle  = GCHandle.Alloc(eventCallback, GCHandleType.Normal);
            IntPtr handlePtr = GCHandle.ToIntPtr(handle);
            unsafe
            {
                return Engine.EventScheduler_ScheduleLocalEvent(
                    priority, delayTime, &ScheduleLocalEvent_EventCallbackFunction, handlePtr);
            }
        }
   }
```

On the C++ side 
```c++
    #define API extern "C" __declspec(dllexport)
    
    API uint32_t EventScheduler_ScheduleLocalEvent(int priority, uint64_t delay, void(__cdecl* callback)(void* obj), void* obj)
    {
        ERSAssert(Ers::Core::InsideSubModel());
        Core::SyncManagerBase& syncManager = Ers::Core::GetSyncManagerBase();
        return syncManager.ScheduleEvent(priority, delay, [callback, obj]() { callback(obj); });
    }
```

### Expected behavior

The thread should enter and execute the static function passed using a function pointer

### Actual behavior

The thread doesn't enter the user-defined portion of the function. an Access Violation is thrown in a generated call visible in the IL during the native-to-managed-transition

### Regression?

_No response_

### Known Workarounds

Change the garbage collection mode by adding ```xml
<ServerGarbageCollection>true</ServerGarbageCollection>
<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
``` to the .csproj 

### Configuration

Tested on PC's around the office with the same behavior. All were x64, issue occurred on both Windows and Linux. The issue was reproduced on .net8.0 and .net9.0.100-preview

### Other information

The issue doesn't appear always, i think it might be a race condition inside the garbage collector.

### PR DESCRIPTION
**Pull request by tommcdon**
Fixes #102767 
This pull request changes DebuggerPatchSkip creation. Before this change we always populated the shared patch bypass buffer, which is used for patch skipping. Although the population of the patch skip buffer is done under the DebuggerController lock, as it is a shared buffer, it's possible we write to it while other threads are executing in the patch buffer which runs without the DebuggerController lock. This exposes a small race condition that can be hit with multiple threads executing on the same breakpoint location. This fix addresses the issue by effectively making the buffer read-only after it is created. There was a previous comment in the code stating that we always overwrite the buffer due to ReJIT jump stamps. Jump stamps were removed in the .NET Core 2.2 timeframe, and so it is believed that it should be safe to avoid constantly re-writing the patch buffer for each DebuggerPatchSkip creation

### CODE REVIEW

File: src/coreclr/debug/ee/controller.cpp [hunk 1]
```diff
@@ -4518,39 +4519,53 @@ DebuggerPatchSkip::DebuggerPatchSkip(Thread *thread,
...
-    CopyInstructionBlock(patchBypassRW, (const BYTE *)patch->address);
+    if (patchBypassRW != NULL)
+    {
+        // Copy the instruction block over to the patch skip
+        // WARNING: there used to be an issue here because CopyInstructionBlock copied the breakpoint from the
+        // jitted code stream into the patch buffer. Further below CORDbgSetInstruction would correct the
+        // first instruction. This buffer is shared by all threads so if another thread executed the buffer
+        // between this thread's execution of CopyInstructionBlock and CORDbgSetInstruction the wrong
+        // code would be executed. The bug has been fixed by changing CopyInstructionBlock to only copy
+        // the code bytes after the breakpoint.
```
Comment (noahfalk) [inline src/coreclr/debug/ee/controller.cpp]: This comment describes the old fix - never writing an invalid byte into the buffer. Now that we only write the buffer once it isn't relevant any more. We could just say:
// CopyInstructionBlock copies all the code bytes except the breakpoint byte(s).

File: src/coreclr/debug/ee/controller.cpp [hunk 2]
```diff
@@ -4518,39 +4519,53 @@ DebuggerPatchSkip::DebuggerPatchSkip(Thread *thread,
     // Create the shared instruction block. this will also create the shared RIP-relative buffer
     //
 
-    m_pSharedPatchBypassBuffer = patch->GetOrCreateSharedPatchBypassBuffer();
+    m_pSharedPatchBypassBuffer = patch->GetSharedPatchBypassBuffer();
```
Comment (noahfalk) [inline src/coreclr/debug/ee/controller.cpp]: You could assert that we hold the controller lock here to make it clear to readers that there is no race.

File: src/coreclr/debug/ee/controller.cpp [hunk 3]
```diff
@@ -4518,39 +4519,53 @@ DebuggerPatchSkip::DebuggerPatchSkip(Thread *thread,
...
+    {
+        // Copy the instruction block over to the patch skip
+        // WARNING: there used to be an issue here because CopyInstructionBlock copied the breakpoint from the
+        // jitted code stream into the patch buffer. Further below CORDbgSetInstruction would correct the
+        // first instruction. This buffer is shared by all threads so if another thread executed the buffer
+        // between this thread's execution of CopyInstructionBlock and CORDbgSetInstruction the wrong
+        // code would be executed. The bug has been fixed by changing CopyInstructionBlock to only copy
+        // the code bytes after the breakpoint.
+        _ASSERTE( patch->IsBound() );
+        CopyInstructionBlock(patchBypassRW, (const BYTE *)patch->address);
```
Comment (noahfalk) [inline src/coreclr/debug/ee/controller.cpp]: CopyInstructionBlock includes a call to FlushInstructionCache, but our modifications to the code lower in this method won't be covered by that call. We should move the Flush call so that it happens after all the code modifications are complete.

File: src/coreclr/debug/ee/controller.cpp [hunk 4]
```diff
@@ -4565,12 +4580,12 @@ DebuggerPatchSkip::DebuggerPatchSkip(Thread *thread,
 #endif
 
 #if defined(TARGET_AMD64)
-
     // The code below handles RIP-relative addressing on AMD64. The original implementation made the assumption that
     // we are only using RIP-relative addressing to access read-only data (see VSW 246145 for more information). This
     // has since been expanded to handle RIP-relative writes as well.
-    if (m_instrAttrib.m_dwOffsetToDisp != 0 && !IsInPlaceSingleStep())
+    if (patchBypassRW != NULL && m_instrAttrib.m_dwOffsetToDisp != 0 && !IsInPlaceSingleStep())
```
Comment (noahfalk) [inline src/coreclr/debug/ee/controller.cpp]: When the code to initialize the patch refers to field and methods on the DebuggerPatchSkip object it raises the possibility that two patchskip objects might have different values causing them to disagree on the correct bytes to initialize the patch with (imagine if one PatchSkip returned false for IsInPlaceSingleStep() and another returned true). I don't think there is any disagreement for these particular fields/calls but someone might make that mistake in the future. If it isn't too difficult I'd suggest refactoring the code so that all of buffer init happens inside DebuggerControllerPatch::CreateSharedPatchBypassBuffer().

File: src/coreclr/debug/ee/controller.cpp [hunk 5]
```diff
@@ -4518,44 +4668,18 @@ DebuggerPatchSkip::DebuggerPatchSkip(Thread *thread,
...
-    // Look at instruction to get some attributes
-    //
+    _ASSERTE(DebuggerController::HasLock());
+    m_pSharedPatchBypassBuffer = patch->GetSharedPatchBypassBuffer();
 
-    NativeWalker::DecodeInstructionForPatchSkip(patchBypassRX, &(m_instrAttrib));
+    if (m_pSharedPatchBypassBuffer == NULL)
+    {
+        // If we don't have a shared patch buffer, create one
+        m_pSharedPatchBypassBuffer = patch->CreateSharedPatchBypassBuffer(patch, &m_instrAttrib);
```
Comment (noahfalk) [inline src/coreclr/debug/ee/controller.cpp]: 'patch' is already the 'this' param, we shouldn't need to also pass it as an argument.

File: src/coreclr/debug/ee/controller.cpp [hunk 6]
```diff
@@ -4518,44 +4668,18 @@ DebuggerPatchSkip::DebuggerPatchSkip(Thread *thread,
...
+    }
+    else
+    {
+        NativeWalker::DecodeInstructionForPatchSkip(m_pSharedPatchBypassBuffer->PatchBypass, &m_instrAttrib);
```
Comment (noahfalk) [inline src/coreclr/debug/ee/controller.cpp]: How about we add `InstructionAttribute SharedPatchBypassBuffer::GetInstructionAttrib()` so we don't need to expose multiple different paths to compute the same value:
```c++
m_pSharedPatchBypassBuffer = patch->GetSharedPatchBypassBuffer();
if (m_pSharedPatchBypassBuffer == NULL)
{
    m_pSharedPatchBypassBuffer = patch->CreateSharedPatchBypassBuffer();
}
m_instrAttrib = m_pSharedPatchBypassBuffer->GetInstructionAttrib();
```

File: src/coreclr/debug/ee/controller.cpp [hunk 7]
```diff
@@ -4518,44 +4668,18 @@ DebuggerPatchSkip::DebuggerPatchSkip(Thread *thread,
     // Create the shared instruction block. this will also create the shared RIP-relative buffer
```
Comment (noahfalk) [inline src/coreclr/debug/ee/controller.cpp]: The comment above about RIP-relative writes probably makes more sense in CreateSharedPatchBypassBuffer

File: src/coreclr/debug/ee/controller.cpp [hunk 8]
```diff
@@ -67,10 +67,80 @@ bool DebuggerControllerPatch::IsSafeForStackTrace()
...
+        // exception.
+        LOG((LF_CORDB, LL_INFO10000,
+             "DCP::CIP: AV copying instruction block ignored.\n"));
+    }
+    PAL_ENDTRY
+}
+
+
+// Creates a new shared patch bypass buffer
+// Before returning it so callers only need to Release() when they're finished with it.
```
Comment (noahfalk) [inline src/coreclr/debug/ee/controller.cpp]:
```suggestion
// AddRef() before returning it so callers need to Release() when they're finished with it.
```

File: src/coreclr/debug/ee/controller.cpp [hunk 9]
```diff
@@ -79,27 +149,107 @@ SharedPatchBypassBuffer* DebuggerControllerPatch::GetOrCreateSharedPatchBypassBu
     }
     CONTRACTL_END;
 
-    if (m_pSharedPatchBypassBuffer == NULL)
+    _ASSERTE(m_pSharedPatchBypassBuffer == NULL);
+    if (m_pSharedPatchBypassBuffer != NULL)
```
Comment (noahfalk) [inline src/coreclr/debug/ee/controller.cpp:152]: If we've already got the code for GetOrCreate() semantics you could remove the asserts, rename the method GetOrCreateSharedPatchBypassBuffer and delete the unnecessary GetSharedPatchBypassBuffer() function. We only needed separate Create and Get so that DebuggerPatchSkip knew when to init the memory. Now that the memory is inited here the constructor no longer needs to distinguish them.

Currently this code path isn't initializing InstructionAttribute*. You'd either need to add init code for it or in another comment I suggested having a SharedPatchBuffer::GetInstructionAttribute() method. Either way works.

**Review by noahfalk — APPROVED** [review]
A few more style/refactoring suggestions inline. LGTM!

**Review by noahfalk — APPROVED** [review]
👍

**Comment by tommcdon** [comment]
Android timeout is unrelated, merging
