### PR TITLE
JIT: Consume FMA intrinsic operands in right order

### LINKED ISSUE #102773: SPMI Replay failing sporadically
There looks to be a non-deterministic failure occuring in some SPMI replay runs across a range of PRs:
```
[11:07:25] ISSUE: <ASSERT> #288834 D:\a\_work\1\s\src\coreclr\jit\scopeinfo.cpp (864) - Assertion failed '!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' in 'System.Numerics.Tensors.TensorPrimitives+TanOperatorDouble:Invoke(System.Runtime.Intrinsics.Vector128`1[double]):System.Runtime.Intrinsics.Vector128`1[double]' during 'Generate code' (IL size 686; hash 0x5f971363; FullOpts)
```

It looks to trigger more reliably on x86 but also fails sometimes on x64, neither platform reproduces it everytime: https://dev.azure.com/dnceng-public/public/_build?definitionId=150&_a=summary

The `Invoke` method in question isn't really doing anything particularly special, it's mostly just doing some basic arithmetic operations overall: https://source.dot.net/#System.Numerics.Tensors/System/Numerics/Tensors/netcore/TensorPrimitives.Tan.cs,b0e53fd55e442a32,references

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=689641
Build error leg or test failing: runtime-coreclr superpmi-replay (Build SuperPMI replay windows x86 checked)
Pull request: https://github.com/dotnet/runtime/pull/102702

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "'!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' in 'System.Numerics.Tensors.TensorPrimitives+TanOperatorDouble",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=689641
**Error message validated:** `['!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' in 'System.Numerics.Tensors.TensorPrimitives+TanOperatorDouble`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 5/28/2024 5:44:27 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by jakobbotsch**
The operands of the FMA intrinsics are permuted in a non-standard way during LSRA. Codegen already takes this into account, but the handling was missing when consuming the operands.

Ideally we would permute these during lowering instead to avoid these hacks.

Fix #102773

### CODE REVIEW

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 1]
```diff
@@ -3143,6 +3141,21 @@ void CodeGen::genFMAIntrinsic(GenTreeHWIntrinsic* node, insOpts instOptions)
...
+    unsigned useNum3  = op3->gtUseNum;
+    emitOp1->gtUseNum = useNum1;
+    emitOp2->gtUseNum = useNum2;
+    emitOp3->gtUseNum = useNum3;
+#endif
+
+    genConsumeRegs(emitOp1);
+    genConsumeRegs(emitOp2);
+    genConsumeRegs(emitOp3);
+
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:3158]: > Ideally we would permute these during lowering instead to avoid these hacks.

It's worth noting the reason we didn't do this in lowering (unlike most of the other cases that do swap operands) is because it would require introducing a lot of new synthetic intrinsics and it was believed to be overall more costly.

Each `FusedMultiplyAdd` intrinsic has three forms, where `op3` is always the node that can be optionally contained:
* `132` - `op1 = (op1 * op3) + op2`
* `213` - `op1 = (op2 * op1) + op3
* `231` - `op1 = (op2 * op3) + op1`

The managed API we expose is the `213` form and there are 10 different FMA intrinsics, so we'd need to expose 10 more for the `132` and 10 more for the `231` form. Then we'd need to repeat this for the `Avx512` specific variants, giving us at least 50 new synthetic intrinsics in lowering just to cover `FMA`.

Comment (tannergooding) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:3158]: We might be able to avoid new synthetic intrinsics if we had a way to track what permutation it was, but free bits are fairly sparse right now. So I think we'd need to get clever in how we tracked that.

Comment (kunalspathak) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:3158]: We cannot use `genConsumeMultiOpOperands()` here instead?

Comment (jakobbotsch) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:3158]: Right, `op1, op2, op3` (the order that `genConsumeMultiOpOperands` consumes in) is not the same as `emitOp1, emitOp2, emitOp3`, which as I understand it is the order that uses were built in by LSRA. We should consume in that order.

I don't have the context necessary to completely understand why we can't build and consume the operands in the `op1, op2, op3` order even if we end up emitting different instructions using the registers in different orders in the instruction we emit.

Comment (kunalspathak) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:3158]: @tannergooding - do you know?

Comment (tannergooding) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:3158]: That I don't. It's an area of the register allocator I'm not well versed in.

Comment (kunalspathak) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:3158]: > That I don't. It's an area of the register allocator I'm not well versed in.

Hhm, I think it is to do with how we are consuming them in codegen as opposed to the LSRA ordering.

> and consume the operands in the op1, op2, op3 order even if we end up emitting different instructions using the registers in different order
