### PR TITLE
Include the filename in the config file load errors

### LINKED ISSUE #36007: Include filename in load exception
We spent a few minutes today trying to debug a file load error only to find out that we were trying to fix the wrong file because the exception doesn't say what file failed to load.

https://github.com/aspnet/Extensions/blob/06dcb43bfb372585d3801cfc333a2d9ee9c189ea/src/Configuration/Config.FileExtensions/src/FileConfigurationProvider.cs#L90

cc @jkotalik

### PR DESCRIPTION
**Pull request by IEvangelist**
- Simplify `source` null check in `FileConfigurationProvider`
- Add error messages to _Resources/Strings.resx_
- Wrap load error with `InvalidDataException` and ensure it's captured/handled
- Add and update unit tests to cover new logic
- Added unit tests for:
  - `InvalidDataException`
  - `FileNotFoundException`
  - `DirectoryNotFoundException`
- Adjusted existing unit tests

Fixes #36007

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs [hunk 1]
```diff
@@ -34,6 +32,40 @@ public void ProviderDisposesChangeTokenRegistration()
             Assert.Empty(changeToken.Callbacks);
         }
 
+        [Theory]
+        [InlineData(@"C:\path\to\configuration.txt")]
```
Comment (safern) [inline src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs:36]: Nit, could we use random GUIDs for the path? I feel like this directory could exist on a machine and not fail with `DirectoryNotFoundException` but instead throw `FileNotFoundException` causing this test to fail?

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs [hunk 2]
```diff
@@ -118,6 +115,9 @@ static Stream OpenRead(IFileInfo fileInfo)
         /// </summary>
         /// <exception cref="FileNotFoundException">If Optional is <c>false</c> on the source and a
```
Comment (safern) [inline src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs:116]: Does it still throw a `FileNotFoundException` or is that going to be wrapped in the Inner exception?

**Review by safern — COMMENTED** [review]
It seems like this is a breaking change as `FileNotFoundException` nor `DirectoryNotFoundException` are base classes of `InvalidDataException`?

**Comment by IEvangelist** [comment]
> It seems like this is a breaking change as `FileNotFoundException` nor `DirectoryNotFoundException` are base classes of `InvalidDataException`?

Corrected in f3d2c4e

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs (hunk 2 above)
Comment (IEvangelist) [reply src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs:118]: I corrected this, it was wrong to move the `OpenRead` call within the try / catch. Addressed in f3d2c4e

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs (hunk 1 above)
Comment (IEvangelist) [reply src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs]: Updated this to use `Guid` instead, and added proper tests for:

- `InvalidDataException`
- `FileNotFoundException`
- `DirectoryNotFoundException`

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/Resources/Strings.resx [hunk 3]
```diff
@@ -118,9 +118,12 @@
     <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
   </resheader>
   <data name="Error_ExpectedPhysicalPath" xml:space="preserve">
-    <value>The expected physical path was '{0}'.</value>
+    <value> The expected physical path was '{0}'.</value>
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/Resources/Strings.resx:121]: was this diff intentional?

```suggestion
    <value>The expected physical path was '{0}'.</value>
```

**Review by maryamariyan — APPROVED** [review]

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/Resources/Strings.resx (hunk 3 above)
Comment (IEvangelist) [reply src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/Resources/Strings.resx:121]: This was an intentional change, as this is [appended to the existing error message](https://github.com/dotnet/runtime/pull/51713/files#diff-20aa89fc83dc029b19defa0ad20c6d381d0920e0016762f18de42e162a014b3bR68). Is it better in this case to have another formatting to add the space between or what is suggested here?

Comment (maryamariyan) [reply src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/Resources/Strings.resx:121]: I didn't notice the intent. I guess it is fine as-is then.

cc: @safern in case he has other recommendations.
