### PR TITLE
Keep side effects in impOptimizeCastClassOrIsInst

### LINKED ISSUE #82030: JIT\opt\ThrowHelper\NonVoidThrowHelper failing with NativeAOT
With optimizations on, it looks like we optimize

https://github.com/dotnet/runtime/blob/be84df7642f21702b0e7859f0c134e4d6cfc67eb/src/tests/JIT/opt/ThrowHelper/NonVoidThrowHelper.cs#L45-L49

Into `ret`. I guess we figured out the `is` is never true, but we forgot about the other effect of the call.

Cc @EgorBo

### PR DESCRIPTION
**Pull request by EgorBo**
Somehow we never hit this issue until recently in https://github.com/dotnet/runtime/issues/82030 as the code is not new.

Fixes https://github.com/dotnet/runtime/issues/82030

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -16115,6 +16115,11 @@ bool Compiler::gtTreeHasSideEffects(GenTree* tree, GenTreeFlags flags /* = GTF_S
         return false;
     }
 
+    if (tree->OperIs(GT_RET_EXPR))
+    {
+        return gtTreeHasSideEffects(tree->AsRetExpr()->gtInlineCandidate, flags);
+    }
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.cpp:16121]: Is this necessary for something? We give `GT_RET_EXPR` `GTF_CALL` already so I wouldn't think this would have any effect.

File: src/coreclr/jit/importer.cpp [hunk 2]
```diff
@@ -5707,7 +5706,11 @@ GenTree* Compiler::impOptimizeCastClassOrIsInst(GenTree* op1, CORINFO_RESOLVED_T
                     gtTryRemoveBoxUpstreamEffects(op1);
                 }
 
-                return result;
+                if (gtTreeHasSideEffects(op1, GTF_ALL_EFFECT))
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp:5709]:
```suggestion
                if (gtTreeHasSideEffects(op1, GTF_SIDE_EFFECT))
```

File: src/coreclr/jit/gentree.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/gentree.cpp]: @jakobbotsch you're right, just checked

**Review by jakobbotsch — APPROVED** [review]
