### PR TITLE
Fix memory leaked caused by Marshal.GetFunctionPointerForDelegate

### LINKED ISSUE #353: Marshal.GetFunctionPointerForDelegate leaks memory
Copied from a VSFeedback item.

A customer noticed that repeated calls to a p/invoke that took a delegate appeared to be leaking memory.  The underlying cause is the new way that we allocate umentrythunks and how GetFunctionPointerForDelegate caches them.  Previously, the same thunk was returned and used when run in a tight loop (see code below).  Now a new thunk is used every time, which results in memory seemingly increasing.

```using System; 
using System.Runtime.InteropServices;
 
namespace test
{
   class Program
   {
      static void Main(string[] args)
      {
         while (true)
         {
            var delg = new EnumWindowsProc(MyEnumProc);
            IntPtr ptr = Marshal.GetFunctionPointerForDelegate( delg ); 
            GC.Collect(); 
            GC.WaitForPendingFinalizers(); 
            GC.Collect(); 
         }
      }
      private static int MyEnumProc(IntPtr hwnd, IntPtr lParam)
      {
         return 0;
      }

      private delegate int EnumWindowsProc(IntPtr hwnd, IntPtr lParam);
   }
}

### PR DESCRIPTION
**Pull request by mateoatr**
We now delete the long weak handle of a `UMEntryThunk` whenever we terminate it.

Fixes #353.

### CODE REVIEW

File: src/coreclr/src/vm/dllimportcallback.cpp [hunk 1]
```diff
@@ -961,12 +961,18 @@ void UMEntryThunk::Terminate()
...
         NOTHROW;
+        MODE_ANY;
     }
     CONTRACTL_END;
 
     m_code.Poison();
 
     s_thunkFreeList.AddToList(this);
+
+    if (GetObjectHandle())
```
Comment (jkotas) [inline src/coreclr/src/vm/dllimportcallback.cpp]: This needs to be done before `s_thunkFreeList.AddToList`. Once you add it to the freelist list, some other thread can get it out and work with it.

Comment (jkotas) [inline src/coreclr/src/vm/dllimportcallback.cpp]: It maybe also nice to set the object handle field to zero when we destroy the handle.

**Review by jkotas — CHANGES_REQUESTED** [review]

File: src/coreclr/src/vm/dllimportcallback.cpp [hunk 2]
```diff
@@ -961,9 +961,16 @@ void UMEntryThunk::Terminate()
...
     {
         NOTHROW;
+        MODE_ANY;
     }
     CONTRACTL_END;
 
+    if (GetObjectHandle())
+    {
+        DestroyLongWeakHandle(GetObjectHandle());
+        this->m_pObjectHandle = 0;
```
Comment (jkotas) [inline src/coreclr/src/vm/dllimportcallback.cpp]: Nit: The rest of this file does not use `this->` to access fields, so this place should not either for consistent style.

File: src/coreclr/src/vm/dllimportcallback.cpp [hunk 3]
```diff
@@ -961,9 +961,16 @@ void UMEntryThunk::Terminate()
...
+    }
+
     m_code.Poison();
```
Comment (jkotas) [inline src/coreclr/src/vm/dllimportcallback.cpp]: It may be better to poinson the code first before freeing the handle - to make the diagnostic of the API misuse a tiny bit more reliable.

**Review by jkotas — APPROVED** [review]
Looks good. Thanks!

**Comment by jkotas** [comment]
@mateoatr Please use "Squash & Merge" to merge the PRs next time

https://github.com/dotnet/runtime/blob/master/docs/issues-pr-management.md
