### PR TITLE
Fix uses of uninitialized data

### LINKED ISSUE #46961: JIT: some jumps based on uninitialized values detected by valgrind
From @tmds, #46905 

I ran valgrind on dotnet hello world, and it pointed out a few jumps based on uninitialized values.

1. `LinearScan::buildIntervals() (src/coreclr/jit/lsrabuild.cpp:2320)`

https://github.com/dotnet/runtime/blob/b95de552f888e6294133b077885fa17ab632085c/src/coreclr/jit/lsrabuild.cpp#L2320

It looks like `firstColdLoc` is only initialized in DEBUG. Probably it should be also set to `MaxLocation` in release?

https://github.com/dotnet/runtime/blob/b95de552f888e6294133b077885fa17ab632085c/src/coreclr/jit/lsra.cpp#L719-L721

2. `FindConstReturnBlock (src/coreclr/jit/flowgraph.cpp:9189)`

https://github.com/dotnet/runtime/blob/b95de552f888e6294133b077885fa17ab632085c/src/coreclr/jit/flowgraph.cpp#L9189

`returnConstants[i]` is not initialized. I don't know what the best place is to initialize it.

3. `CodeGen::instGen(instruction) (src/coreclr/jit/instr.cpp:200)`

https://github.com/dotnet/runtime/blob/36d132e7c98098d0c5566056990f6ddb0a1aee8c/src/coreclr/jit/instr.cpp#L200

`emitNextNop` initialization is tied to `PSEUDORANDOM_NOP_INSERTION`, so this check should probably `#ifdef PSEUDORANDOM_NOP_INSERTION`?

### PR DESCRIPTION
**Pull request by BruceForstall**
Fixes #46961

### CODE REVIEW

**Comment by BruceForstall** [comment]
@AndyAyersMS PTAL
cc @dotnet/jit-contrib

File: src/coreclr/jit/flowgraph.cpp [hunk 1]
```diff
@@ -9186,18 +9186,19 @@ class MergedReturns
             // Need to check both for matching const val and for genReturnBB
             // because genReturnBB is used for non-constant returns and its
             // corresponding entry in the returnConstants array is garbage.
-            if (returnConstants[i] == constVal)
-            {
-                BasicBlock* returnBlock = returnBlocks[i];
+            // Check the returnBlocks[] first, so we don't access an uninitialized
+            // returnContants[] value (which some tools like valgrind will
```
Comment (danmosemsft) [inline src/coreclr/jit/flowgraph.cpp:9190]: typo

**Review by AndyAyersMS — APPROVED** [review]
