### PR TITLE
ImmutableDictionary.AddRange: throw if any item has a null Key.

### LINKED ISSUE #50865: AddRange() can add key-value pairs with `null` keys to ImmutableDictionary
### Description

It is not possible to add an item with a `null` key to an immutable dictionary using either the dictionary's or the builder's `.Add/.SetItem` methods:
```
ImmutableDictionary<string, int>.Empty.Add (null, 0) ; // throws ArgumentNullException
```
but it turns out that it _is_ possible to add an item with a `null` key using `.AddRange` and extension methods, such as `ToImmutableDictionary`, that rely on `.AddRange`:
```
ImmutableDictionary<string, int>.Empty.AddRange (new[] { new KeyValuePair<string, int> (null, 0) }) ; // ok???
```
This means that this natural-looking code is invalid:
```
ImmutableDictionary<K, V> Rebuild<K, V> (ImmutableDictionary<K, V> input)
{
    // NB: ignoring key comparers for simplicity
    var builder = ImmutableDictionary.CreateBuilder<K, V> () ;
    foreach (var kv in input) builder.Add (kv.Key, kv.Value) ;
    return builder.ToImmutable () ;
}
```
Given an `ImmutableDictionary`, users should be able to construct a copy of this dictionary using ordinary `.Add` methods, but this will fail if the input dictionary was constructed with `.AddRange` with `null` keys. This behavior is unexpected and so far as I am aware of, not documented. Is it an invariant of generic dictionaries with reference-typed keys that `null` is not a valid key? If it is an invariant, then `.AddRange` shouldn't construct dictionary instances that violate it. On the other hand, if it is not an invariant, then `.Add` shouldn't reject `null` keys. So the existing behavior is inconsistent whether it is an invariant or not.

### Other information

This behavior is observed in System.Collections.Immutable 5.0.0.

### PR DESCRIPTION
**Pull request by mookid**
The behavior of AddRange(items) should be the same as
foreach(var item in items) Add(item); Add(item) throws if item.Key == null,
so AddRange should it as well.

Fix #50865.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=51438) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=51438) before we can accept your contribution.<br/><br/>:x: mookid [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=51438)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=51438) it.</sub>

**Review by stephentoub — APPROVED** [review]
Thanks.

File: src/libraries/System.Collections.Immutable/tests/ImmutableDictionaryTest.cs [hunk 1]
```diff
@@ -24,6 +24,18 @@ public void AddExistingKeyDifferentValueTest()
             AddExistingKeyDifferentValueTestHelper(Empty(StringComparer.Ordinal, StringComparer.Ordinal), "Company", "Microsoft", "MICROSOFT");
         }
 
+        [Fact]
+        public void AddRangeShouldThrowOnNullKeyTest()
+        {
+            var items = new[] { new KeyValuePair<string, string>(null, "value") };
+
+            var map = Empty(StringComparer.Ordinal, StringComparer.Ordinal);
+            Assert.Throws<ArgumentNullException>(() => map.AddRange(items));
```
Comment (eiriktsarpalis) [inline src/libraries/System.Collections.Immutable/tests/ImmutableDictionaryTest.cs:33]: The same issue impacts the `SetRange` method and the corresponding methods in the builder type. Would it be possible to add tests for those as well? Thanks.

Comment (mookid) [reply src/libraries/System.Collections.Immutable/tests/ImmutableDictionaryTest.cs:33]: @eiriktsarpalis I added tests for SetItems and AddRange for the builder type. I could add the similar test for the (unaffected) classes ImmutableSortedDictionary and ImmutableHashSet if you think that it's useful.

Comment (eiriktsarpalis) [reply src/libraries/System.Collections.Immutable/tests/ImmutableDictionaryTest.cs:33]: I think this is fine 👍

**Comment by eiriktsarpalis** [comment]
Thank you for your contribution @mookid!
