### PR TITLE
Fix release build infinite loop

### LINKED ISSUE #45580: Infinite loop in stacklevelsetter
Running superpmi with a release clrjit runs into an infinite loop in stacklevelsetter due to bad IR. I’ve traced this back to the importer, when it generates two statements that reference the same CATCH_ARG node. In checked it runs into “Verification failure:  F:\git5\runtime\src\coreclr\src\jit\importer.cpp:11980 : stack must be 1 on end of filter, while compiling App.Foo:VargFuncWrapper():App.Foo:this opcode endfilter, IL offset 13”, but doesn't run into the infinite loop. I haven’t determined why the behavior is different between checked and release.

This happens with `\\jitrollingbuild\SuperPMI\Windows_NT.x64\tests.pmi.Windows_NT.x64.Release.mch` from 10/14/2020, with method context 462164 (`superpmi.exe -c 462164 clrjit.dll \SuperPmi\tests.pmi.Windows_NT.x64.Release.mch`) from `artifacts\bin\coreclr\windows.x64.Checked`. (Adjusting as needed for where you've got the mch file.)

### PR DESCRIPTION
**Pull request by BruceForstall**
The problem manifested as an infinite loop during the StackLevelSetter phase
in the release build SuperPMI replay of the tests, but also occurs as a
normal release build test run of the varargsupport.il test.

The issue is we had corrupt LIR gtPrev links, with a cycle. The problem had
nothing to do with StackLevelSetter -- it just happened to be the first phase
that iterated in reverse over the gtPrev links.

The corruption was introduced in the importer, in
`verConvertBBToThrowVerificationException`. It required a verification failure
in a filter (possibly also catch) clause where the JIT would throw away the
currently imported code and convert the block to a call to the verification
failure helper.

This was a classic case of important, functional code being under `#ifdef DEBUG`
that is needed in non-DEBUG as well.

The result was we would end up adding an `ASG(LCL_VAR, CATCH_ARG)` to the statement
list twice, with the same `CATCH_ARG` node.

Fixes #45580

### CODE REVIEW

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -5321,22 +5321,20 @@ bool Compiler::verMergeEntryStates(BasicBlock* block, bool* changed)
 /*****************************************************************************
  * 'logMsg' is true if a log message needs to be logged. false if the caller has
  *   already logged it (presumably in a more detailed fashion than done here)
- * 'bVerificationException' is true for a verification exception, false for a
```
Comment (BruceForstall) [inline src/coreclr/jit/importer.cpp:5324]: This argument no longer exists

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Comment by AndyAyersMS** [comment]
I thought all this was now dead code. How is this getting called?

**Comment by BruceForstall** [comment]
There is this:
```
    // Set to TRUE if verification cannot be skipped for this method
    // CoreCLR does not ever run IL verification. Compile out the verifier from the JIT by making this a constant.
    // TODO: Delete the verifier from the JIT? (https://github.com/dotnet/runtime/issues/32648)
    // BOOL tiVerificationNeeded;
    static const BOOL tiVerificationNeeded = FALSE;
```

The caller is https://github.com/dotnet/runtime/blob/d64c11eabf313cbd52c2f83f89d5a63ad91ddca2/src/coreclr/jit/importer.cpp#L12117

**Comment by BruceForstall** [comment]
jitstress failure is https://github.com/dotnet/runtime/issues/49954

**Comment by AndyAyersMS** [comment]
I'm still confused as to how `verConvertBBToThrowVerificationException` gets called.

What I'm wondering is whether we should BADCODE at the point we decide calling the above makes sense, instead of trying to defer things to runtime.

**Comment by BruceForstall** [comment]
When `verRaiseVerifyException` on the bad IL (a filter expression that leaves the IL stack with 2 slots when reaching an `endfilter`), it raises an exception via `RaiseException`. It's caught here:

https://github.com/dotnet/runtime/blob/389674db062acc266da55401f406d872f5d5355f/src/coreclr/jit/importer.cpp#L17785

which calls `verHandleVerificationFailure` which calls `verConvertBBToThrowVerificationException`.

You're right that perhaps BADCODE is the right behavior; I don't understand why it was originally a verification error and deferred to runtime. I guess we allowed unverifiable code to run and only lazily fail?

**Review by AndyAyersMS — APPROVED** [review]
LGTM.

We can sort out the rest when we delete all the verifier support.
