### PR TITLE
Retype calls as SIMD when applicable.

### LINKED ISSUE #52864: Guarded devirtualization assert with vector type
This modified version of JIT\Regression\JitBlue\GitHub_21546 will fail if run with
```
COMPlus_TieredPGO=1
COMPlus_TC_QuickJitForLoops=1
```
with the assert
```
Assert failure(PID 51956 [0x0000caf4], Thread: 32372 [0x7e74]): Assertion failed '(type == varDsc->lvType) || (lvaIsImplicitByRefLocal(lnum) && fgGlobalMorph && (varDsc->lvType == TYP_BYREF)) || ((varDsc->lvType == TYP_STRUCT) && (genTypeSize(type) == varDsc->lvExactSize))' in 'System.Linq.Enumerable:TryGetLast(System.Collections.Generic.IEnumerable`1[Vector2],byref):System.Numerics.Vector2' during 'Indirect call transform' (IL size 131)

    File: C:\repos\runtime2\src\coreclr\jit\gentree.cpp Line: 6483
```
Looks like the indirect call transform is perhaps not properly handling vector types
```c#
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Threading;
using System.Linq;
using System.Runtime.CompilerServices;

using Point = System.Numerics.Vector2;

namespace GitHub_21546
{
    public class test
    {
        static Point checkA;
        static Point checkB;
        static Point checkC;
        static int   returnVal;

        public const int DefaultSeed = 20010415;
        public static int Seed = Environment.GetEnvironmentVariable("CORECLR_SEED") switch
        {
            string seedStr when seedStr.Equals("random", StringComparison.OrdinalIgnoreCase) => new Random().Next(),
            string seedStr when int.TryParse(seedStr, out int envSeed) => envSeed,
            _ => DefaultSeed
        };

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void check(Point a, Point b, Point c)
        {
            if (a != checkA)
            {
                Console.WriteLine($"A doesn't match. Should be {checkA} but is {a}");
                returnVal = -1;
            }
            if (b != checkB)
            {
                Console.WriteLine($"B doesn't match. Should be {checkB} but is {b}");
                returnVal = -1;
            }
            if (c != checkC)
            {
                Console.WriteLine($"C doesn't match. Should be {checkC} but is {c}");
                returnVal = -1;
            }
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void FailureCase(List<Point> p)
        {
            Point p1 = p[0];
            Point p2 = p.Last();

            check(p1, p[1], p2);
            check(p1, p[1], p2);
            check(p1, p[1], p2);
        }

        static Point NextPoint(Random random)
        {
            return new Point(
                (float)random.NextDouble(),
                (float)random.NextDouble()
            );
        }

        static int Main()
        {
            returnVal     = 100;
            Random random = new Random(Seed);

            for (int i = 0; i < 50; i++)
            {
                List<Point> p = new List<Point>();

                checkA = NextPoint(random);
                p.Add(checkA);
                checkB = NextPoint(random);
                p.Add(checkB);
                checkC = NextPoint(random);
                p.Add(checkC);

                FailureCase(p);

                Thread.Sleep(15);
            }

            for (int i = 0; i < 50; i++)
            {
                List<Point> p = new List<Point>();

                checkA = NextPoint(random);
                p.Add(checkA);
                checkB = NextPoint(random);
                p.Add(checkB);
                checkC = NextPoint(random);
                p.Add(checkC);

                FailureCase(p);
            }

            return returnVal;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by sandreenko**
Retype calls that return System.Numerics.Vector2/3/4 as `TYP_SIMD8/12/16` between importation and lowering.

It better aligns with the fact that we retype `System.Numerics.Vector2/3/4` locals and returns as `SIMD`.

some IR diffs:
```diff
STMT00007 (IL 0x02B...  ???)
               [000027] --C-G-------              *  RETURN    simd8 
-              [000026] --C-G-------              \--*  CALL      struct Runtime_49489.Program.ReturnSIMD2
+              [000026] --C-G-------              \--*  CALL      simd8  Runtime_49489.Program.ReturnSIMD2

STMT00011 (IL 0x003...0x008)
               [000040] -ACXG-------              *  ASG       simd8  (copy)
               [000038] D------N----              +--*  LCL_VAR   simd8 <System.Numerics.Vector2> V03 tmp1         
-              [000034] --CXG+-N----              \--*  CALL      struct Runtime_49489.Program.ReturnSIMD2
+              [000034] --CXG+-N----              \--*  CALL      simd8  Runtime_49489.Program.ReturnSIMD2
```

I am not a huge fan of this retyping but the improved check in `gtNewLclvNode` should make the code overall safer in my opinion. 

No asm diffs.

Fixes https://github.com/dotnet/runtime/issues/52864.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @AndyAyersMS @dotnet/jit-contrib

**Review by AndyAyersMS — APPROVED** [review]

**Comment by sandreenko** [comment]
I have pushed a change to retype multireg returns as well, note that now the change has some diffs but they are potential bug fixes:

```diff
Generating: N065 ( 18,  3) [000012] --CXG-------        t12 = *  CALL ind unman struct REG mm0,mm1 $280
+IN0014:        vpslldq  xmm1, 12
+IN0015:        vpsrldq  xmm1, 12

                                                              /--*  t12    struct 
Generating: N081 ( 18,  3) [000015] DA-XG-------              *  STORE_LCL_VAR simd16<System.Numerics.Vector3> V06 tmp3         d:1 mm0 REG mm0
IN001c:        vshufpd  xmm0, xmm1, 0

```

as we see from
https://github.com/dotnet/runtime/blob/2c508d40de65163d11e3046891ced5419343abdf/src/coreclr/jit/codegenxarch.cpp#L5414-L5418
there were no guarantees that top bytes of xmm1 were zeroed by the native compiler.

diffs:
```
tests.pmi.Linux.arm64.checked.mch:
Total bytes of delta: 24, 
2 total files with Code Size differences (0 improved, 2 regressed), 0 unchanged.

coreclr_tests.pmi.Linux.x64.checked.mch
Total bytes of delta: 20
2 total files with Code Size differences (0 improved, 2 regressed), 0 unchanged.

tests.pmi.windows.arm64.checked.mch
Total bytes of delta: 24
2 total files with Code Size differences (0 improved, 2 regressed), 0 unchanged.
```

all in 
```
Top method regressions (bytes):
          10 ( 0.40% of base) : 229418.dasm - PInvokeTest:test():bool
          10 ( 5.88% of base) : 229416.dasm - ILStubClass:IL_STUB_PInvoke():System.Numerics.Vector3
```

cc @tannergooding

File: src/coreclr/jit/codegenxarch.cpp [hunk 1]
```diff
@@ -5414,7 +5414,7 @@ void CodeGen::genCallInstruction(GenTreeCall* call)
                 // A Vector3 return value is stored in xmm0 and xmm1.
                 // RyuJIT assumes that the upper unused bits of xmm1 are cleared but
                 // the native compiler doesn't guarantee it.
-                if (returnType == TYP_SIMD12)
+                if (call->IsUnmanaged() && (returnType == TYP_SIMD12))
```
Comment (tannergooding) [inline src/coreclr/jit/codegenxarch.cpp:5417]: Just noting, the shift left, shift right idiom isn't the "best" codegen for modern hardware. It would likely be better for us to use one of the zero insertion idioms instead.

I'll log a bug for this.

Comment (tannergooding) [reply src/coreclr/jit/codegenxarch.cpp:5417]: Logged https://github.com/dotnet/runtime/issues/53713
