### PR TITLE
Fix stack_limit handling

### LINKED ISSUE #86265: Test failure: JIT/opt/Vectorization/UnrollEqualsStartsWIth/UnrollEqualsStartsWIth.dll
https://dev.azure.com/dnceng-public/public/_build/results?buildId=272907&view=ms.vss-test-web.build-test-results-tab

coreclr windows x86 Checked jitstress2_jitstressregs0x1000 @ Windows.10.Amd64.Open

```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2
set DOTNET_JitStressRegs=0x1000
```

Looks like failure of this test brought down the whole run.

```
18:47:18.821 Running test: JIT/opt/Vectorization/UnrollEqualsStartsWIth/UnrollEqualsStartsWIth.dll
App Exit Code: 3
Expected: 100
Actual: 3
END EXECUTION - FAILED
FAILED
[XUnitLogChecker]: Item 'JIT.opt' did not finish running. Checking and fixing the log...
[XUnitLogChecker]: XUnit log file has been fixed!

211/292 tests run.
* 210 tests passed.
* 0 tests failed.
* 1 tests skipped.

[XUnitLogChecker]: Checking for dumps...
[XUnitLogChecker]: No crash dumps found. Continuing...
[XUnitLogChecker]: Finished!
```

A different run

coreclr windows x86 Checked jitstress2_jitstressregs1 @ Windows.10.Amd64.Open

with:
```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2
set DOTNET_JitStressRegs=1
```
crashed:
```
18:57:33.193 Running test: JIT/opt/Vectorization/UnrollEqualsStartsWIth/UnrollEqualsStartsWIth.dll

Assert failure(PID 3456 [0x00000d80], Thread: 4432 [0x1150]): !PreemptiveGCDisabled()

CORECLR! Thread::DetachThread + 0xCF (0x727a9aa5)
CORECLR! TlsDestructionMonitor::~TlsDestructionMonitor + 0x8F (0x72bf72f5)
CORECLR! _dyn_tls_dtor + 0x86 (0x72c099b6)
NTDLL! RtlDecompressBuffer + 0xDE (0x77aaea4e)
NTDLL! LdrShutdownThread + 0x386 (0x77a7eeb6)
NTDLL! LdrSetAppCompatDllRedirectionCallback + 0x1052A (0x77ad3c6a)
NTDLL! LdrShutdownProcess + 0x15F (0x77a92d7f)
NTDLL! RtlExitUserProcess + 0x96 (0x77a93886)
KERNEL32! ExitProcess + 0x13 (0x7795b3d3)
CORECLR! exit_or_terminate_process + 0x38 (0x72c43f08)
    File: D:\a\_work\1\s\src\coreclr\vm\threads.cpp Line: 979
    Image: C:\h\w\AA420919\p\corerun.exe

App Exit Code: -1073740286
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
[XUnitLogChecker]: Item 'JIT.opt' did not finish running. Checking and fixing the log...
[XUnitLogChecker]: XUnit log file has been fixed!

211/292 tests run.
* 210 tests passed.
* 0 tests failed.
* 1 tests skipped.

[XUnitLogChecker]: Checking for dumps...
[XUnitLogChecker]: No crash dumps found. Continuing...
[XUnitLogChecker]: Finished!
```

Another failure:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=273272&view=ms.vss-test-web.build-test-results-tab

coreclr windows x86 Checked jitstress2_jitstressregs8 @ Windows.10.Amd64.Open

```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2
set DOTNET_JitStressRegs=8
```

```
18:45:54.299 Running test: JIT/opt/Vectorization/UnrollEqualsStartsWIth/UnrollEqualsStartsWIth.dll
App Exit Code: 3
Expected: 100
Actual: 3
END EXECUTION - FAILED
FAILED
[XUnitLogChecker]: Item 'JIT.opt' did not finish running. Checking and fixing the log...
[XUnitLogChecker]: XUnit log file has been fixed!

211/292 tests run.
* 210 tests passed.
* 0 tests failed.
* 1 tests skipped.

[XUnitLogChecker]: Checking for dumps...
[XUnitLogChecker]: No crash dumps found. Continuing...
[XUnitLogChecker]: Finished!
```

@markples Another issue with merging?

cc @EgorBo

### PR DESCRIPTION
**Pull request by janvorli**
There is a problem with computing stack_limit in the presence of inactive InlinedCallFrame. We were trying to call GetCallSiteSP on that frame to get the call site SP. But when the inlined call frame is not active (there is no call to native code in progress), that method returns random junk.

But even if we checked for an active call before reading the value, it would not get correct stack limit on x86 windows when there was no active call with the inlined call frame being the topmost one. That can happen with hardware exception handling on Windows x86. On other targets, we always have other explicit frame on top of the explicit frames stack, but on windows x86, we don't use the FaultingExceptionFrame for hardware exceptions, so the inactive inlined call frame could be the topmost one when GC starts to scan stack roots.

Since the stack_limit was introduced to fix a Unix specific problem, I have fixed that by disabling the stack_limit usage for x86 windows.

Close #86265

### CODE REVIEW

File: src/coreclr/gc/gcinterface.h [hunk 1]
```diff
@@ -1066,12 +1066,18 @@ inline GC_ALLOC_FLAGS& operator&=(GC_ALLOC_FLAGS& a, GC_ALLOC_FLAGS b)
...
+#if !defined(TARGET_X86) || defined(TARGET_UNIX)
+#define USE_STACK_LIMIT
+#endif
+
 struct ScanContext
 {
     Thread* thread_under_crawl;
     int thread_number;
     int thread_count;
+#ifdef USE_STACK_LIMIT
```
Comment (jkotas) [inline src/coreclr/gc/gcinterface.h:1078]: Is this a breaking change in the GC/EE contract?

cc @dotnet/gc

Comment (janvorli) [reply src/coreclr/gc/gcinterface.h:1078]: I think so, thank you for spotting this. Let's keep this field in unconditionally.

Comment (Maoni0) [reply src/coreclr/gc/gcinterface.h:1078]: we really try to keep the #define's low in gcinterface.h because it'd require us to keep track of what version defines what. what would be the drawback to keep the code as is instead of adding this define?

Comment (janvorli) [reply src/coreclr/gc/gcinterface.h:1078]: I can leave the code in and just let the limit to be zero on x86 windows. That should work.

Comment (janvorli) [reply src/coreclr/gc/gcinterface.h]: @Maoni0 I've modified the PR to minimalize the number of ifdefs overall, no more gcinterface.h changes anymore.

Comment (Maoni0) [reply src/coreclr/gc/gcinterface.h]: awesome, thank you!

File: src/coreclr/vm/gcenv.ee.cpp [hunk 2]
```diff
@@ -91,6 +91,10 @@ VOID GCToEEInterface::AfterGcScanRoots (int condemned, int max_gen,
     Interop::OnAfterGCScanRoots(sc->concurrent);
 }
 
+#if !defined(TARGET_X86) || defined(TARGET_UNIX)
+#define USE_STACK_LIMIT
```
Comment (jkotas) [inline src/coreclr/vm/gcenv.ee.cpp:95]: Can we just use `USE_FEF` here instead of this?

File: src/coreclr/vm/gcenv.ee.cpp [hunk 3]
```diff
@@ -115,16 +119,22 @@ static void ScanStackRoots(Thread * pThread, promote_func* fn, ScanContext* sc)
...
+        // It is an InlinedCallFrame with active call. Get SP from it.
         InlinedCallFrame* pInlinedFrame = (InlinedCallFrame*)pTopFrame;
         topStack = (Object **)pInlinedFrame->GetCallSiteSP();
     }
+#endif // FEATURE_CONSERVATIVE_GC || USE_STACK_LIMIT
 
+#ifdef USE_STACK_LIMIT
     sc->stack_limit = (uintptr_t)topStack;
+#else // USE_STACK_LIMIT
+    sc->stack_limit = 0;
```
Comment (jkotas) [inline src/coreclr/vm/gcenv.ee.cpp:136]: A short comment explaining why we are not setting `stack_limit` for Windows x86 and why it is ok would be nice.

File: src/coreclr/vm/gcenv.ee.cpp (hunk 2 above)
Comment (janvorli) [reply src/coreclr/vm/gcenv.ee.cpp:95]: Sure

**Review by jkotas — APPROVED** [review]
LGTM. Thanks!
