### PR TITLE
Prevent unbounded lock holds in BufferManager of EventPipe

### LINKED ISSUE #43985: libcoreclr.so!EventPipeInternal::GetNextEvent high CPU use
# Issue Title
When using `EventListener` over prolonged periods of time, CPU consumption slowly climbs until majority of CPU time is spent forwarding events.

# General

.NET core version: v3.1.3
OS: Docker on linux (base image= `mcr.microsoft.com/dotnet/core/aspnet:3.1.3-bionic`)

When using the [prometheus-net.DotNetRuntime](https://github.com/djluck/prometheus-net.DotNetRuntime) package to capture CLR events, I see a gradual increase in CPU over many days:
image

The application itself is a simple ASP.NET core web application that does not perform intensive processing. After collecting a CPU trace using `perfcollect`, I see this call stack standing out by a mile:
image

This pattern has showed itself consistently over the last month, suggesting that the amount of CPU consumption required utilized by the event pipes increases over time to the point where we need to restart our applications.

Some notes about the prometheus-net.DotNetRuntime package (of which I authored):
- The purpose of this package is to instrument .NET runtime internals by listening to telemetry events consumed by `EventListener`s
- Multiple `EventListener` are spun up to listen to events. One listener is created per "type" of events (e.g. one for counting exceptions, one for listening to GC events, etc.)

### PR DESCRIPTION
**Pull request by josalem**
fix #43985
This should _help_, but not solve dotnet/diagnostics#1412

These changes will limit the time the BufferManager lock is held to O(N) where N is the number of _currently_ active threads. This does not alleviate the lock caravan behavior we see when N becomes sufficiently large.

Belongs to #45518

Every physical thread in a process has an EventPipeThread created the first time an event is written on that thread. These EventPipeThread objects are thread-local, ref-counted instances that live longer than the physical thread. Each of these objects has a fixed-size (64, the max number of EventPipe sessions) array of ThreadSessionStates that keep hold references to the buffers for a given thread. In addition, for every EventPipe session there is one BufferManager that manages the ThreadSessionStates on the EventPipeThreads. It holds a lock that protects access to the buffers and sequence point data for a given session.  Each of the ThreadSessionStates has a strong reference to the EventPipeThread it belongs to, keeping it alive even if the physical thread dies.

This results in a relation that looks like this:
```
Physical Thread (A) <1--1 EventPipeThread (B) <1--* ThreadSessionState (B) <*--1 BufferManager (B) <1--1 session (B)

A: lifetime A of the physical thread
B: lifetime B of the session
```

This means that the list of ThreadSessionStates is unbounded in length over the length of a session.  For a sufficiently long session in multithreaded process (or a pathologic case such as my stress tests), this means that the list can become problematically long.  For example, a process that creates a thread, then joins it in a loop will create problems for single, long-lived session.

The problem arises from the spin lock on the BufferManager. This lock can be taken in a few different situations (non-exhaustive list):
* A thread is writing its first event or has exhausted a previously allocated buffer
  * This can trigger the extra work of initializing a new sequence point
* The streaming thread is attempting to flush the oldest events from each thread
  * The streaming thread writes a sequence point
  * The streaming thread iterates all ThreadSessionStates looking for the oldest event

The selection of scenarios up above have work time of O(N) where N is the number of ThreadSessionStates.

This means that lock holding times scale with integral of all threads _ever_ created during a session.

To remedy this, I've added logic that culls ThreadSessionStates belonging to EventPipeThreads that have been orphaned and that have had all their events flushed.  In short, these ThreadSessionStates won't have any new events on them again.  The logic guarantees that at least one SequencePoint will have the last known sequence value for events on that thread.

I tested this by writing a simple stress application.  In pseudo-code it did the following:
```
function write_events:
	for i in 0..3:
		EventSource.Write(...)

function main:
	while not finished:
		t <- new thread(write_events)
		t.join()
``` 

This will create thousands of threads per second, but only one thread should ever be writing events at a time. This will minimize impacts from having many threads contending for the lock at the same time (a separate issue) while still exemplifying the underlying problem.

To measure the impact of these changes, I added some simple code during development that calculated histograms of how long the lock was held and how long the lock was waited on. With that I collected the following basic datapoints.

> Note: The histograms are written like this, `bin upper bound -> count`, with `-1` being an unbounded bin.

> Note: The time measurements are in nanoseconds.

> Note: Each thread sent 3 events before being joined.

Baseline (master + histogram code):
```
Buffer Manager Hold Histogram at lock iteration 200000
    10 -> 24120
    50 -> 29795
    100 -> 30391
    500 -> 59079
    1000 -> 3903
    2500 -> 8968
    5000 -> 14181
    10000 -> 24780
    15000 -> 3275
    50000 -> 1154
    100000 -> 229
    -1 -> 125
Buffer Manager Wait Histogram at lock iteration 200000
    10 -> 124123
    50 -> 30324
    100 -> 1196
    500 -> 3208
    1000 -> 3866
    2500 -> 10209
    5000 -> 13306
    10000 -> 12116
    15000 -> 513
    50000 -> 789
    100000 -> 225
    -1 -> 125
>81000 threads created
========================================================
**** Summary ****
iteration 1: 207,544.00 events collected, 12,227,958.00 events dropped in 64.221364 seconds - (1.67% throughput)
        (3,231.70 events/s) (4,524,376.00 bytes/s)

|-----------------------------------|--------------------|--------------------|--------------------|--------------------|
| stat                              | Min                | Max                | Average            | Standard Deviation |
|-----------------------------------|--------------------|--------------------|--------------------|--------------------|
| Events Read                       |          207,544.00|          207,544.00|          207,544.00|                0.00|
| Events Dropped                    |       12,227,958.00|       12,227,958.00|       12,227,958.00|                0.00|
| Throughput Efficiency (%)         |                1.67|                1.67|                1.67|                0.00|
| Event Throughput (events/sec)     |            3,231.70|            3,231.70|            3,231.70|                0.00|
| Data Throughput (Bytes/sec)       |        4,524,376.00|        4,524,376.00|        4,524,376.00|                0.00|
| Duration (seconds)                |           64.221364|           64.221364|           64.221364|            0.000000|
|-----------------------------------|--------------------|--------------------|--------------------|--------------------|
```

Patch:
```
Buffer Manager Hold Histogram at lock iteration 500000
    10 -> 425
    50 -> 231429
    100 -> 199302
    500 -> 67218
    1000 -> 1318
    2500 -> 164
    5000 -> 52
    10000 -> 92
    15000 -> 0
    50000 -> 0
    100000 -> 0
    -1 -> 0
Buffer Manager Wait Histogram at lock iteration 500000
    10 -> 485677
    50 -> 7712
    100 -> 5772
    500 -> 699
    1000 -> 97
    2500 -> 34
    5000 -> 2
    10000 -> 7
    15000 -> 0
    50000 -> 0
    100000 -> 0
    -1 -> 0
>196,000 threads created
========================================================
**** Summary ****
iteration 1: 589,059.00 events collected, 0.00 events dropped in 60.251668 seconds - (100.00% throughput)
        (9,776.64 events/s) (13,687,299.01 bytes/s)

|-----------------------------------|--------------------|--------------------|--------------------|--------------------|
| stat                              | Min                | Max                | Average            | Standard Deviation |
|-----------------------------------|--------------------|--------------------|--------------------|--------------------|
| Events Read                       |          589,059.00|          589,059.00|          589,059.00|                0.00|
| Events Dropped                    |                0.00|                0.00|                0.00|                0.00|
| Throughput Efficiency (%)         |              100.00|              100.00|              100.00|                0.00|
| Event Throughput (events/sec)     |            9,776.64|            9,776.64|            9,776.64|                0.00|
| Data Throughput (Bytes/sec)       |       13,687,299.01|       13,687,299.01|       13,687,299.01|                0.00|
| Duration (seconds)                |           60.251668|           60.251668|           60.251668|            0.000000|
|-----------------------------------|--------------------|--------------------|--------------------|--------------------|
```

  | baseline | patch
-- | -- | --
number of times the lock was taken | ~200,000 | ~500,000
number of threads in 60s | ~81,000 | ~196,000
number of events | 12.4 million | 589,059
events dropped | 12.2 million | 0
events received | 207,544 | 589,059
average lock hold time not counting -1 bucket (μs) | 1.6μs | 0.34μs

One observation to make with the above data is that the 12.4MM number may be erroneous.  It is possible this issue also affects the lost events count in the SequencePoints or the one that EventPipeEventSource calculates. The actual collected events for the baseline is ~240K events which does match with expectations (~81K threads * 3 events per thread).  I have not investigated this issue further while working on this patch, but it is worth a second investigation to make sure those numbers are accurate.

CC @tommcdon @sywhang @noahfalk @lateralusX @shirhatti

### CODE REVIEW

File: src/native/eventpipe/ep-buffer-manager.c [hunk 1]
```diff
@@ -1209,9 +1213,22 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
+						}
+						ep_rt_thread_sequence_number_map_add (ep_sequence_point_get_thread_sequence_numbers_ref (sequence_point), session_state, last_read_sequence_number);
+					}
+
+					// if a session_state was exhausted during this sequence point, mark it for deletion
+					if (ep_thread_session_state_get_buffer_list(session_state)->head_buffer == NULL) {
+
+						if (ep_rt_volatile_load_uint32_t_without_barrier(&(ep_thread_session_state_get_thread(session_state))->unregistered) > 0) {
+
+							ep_rt_thread_session_state_list_remove(&buffer_manager->thread_session_state_list, session_state);
```
Comment (josalem) [inline src/native/eventpipe/ep-buffer-manager.c:1229]: Potentially need to move this outside this loop.  Observed an AV at the next call to `ep_rt_thread_session_list_iterator_next` while testing.  This potentially indicates that we can't mutate the list while iterating it.

File: src/native/eventpipe/ep-rt.h [hunk 2]
```diff
@@ -780,8 +780,9 @@ ep_rt_thread_set_activity_id (
  * ThreadSequenceNumberMap.
  */
 
-EP_RT_DECLARE_HASH_MAP(thread_sequence_number_map, ep_rt_thread_sequence_number_hash_map_t, EventPipeThreadSessionState *, uint32_t)
+EP_RT_DECLARE_HASH_MAP_REMOVE(thread_sequence_number_map, ep_rt_thread_sequence_number_hash_map_t, EventPipeThreadSessionState *, uint32_t)
```
Comment (josalem) [inline src/native/eventpipe/ep-rt.h:783]: I'm pretty sure all the build failures are because Mono doesn't have this implemented.  I'll take a look at what that might entail.

**Comment by noahfalk** [comment]
In your description of issues resolved I think you mean https://github.com/dotnet/diagnostics/issues/1412 instead of #1412 ?

**Comment by josalem** [comment]
The remaining test failures appear unrelated.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 3]
```diff
@@ -1231,6 +1256,61 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
+		EP_ASSERT (thread_session_state != NULL);
+		// This may be the last reference to a given EventPipeThread, so make a ref to keep it around till we're done
+		EventPipeThreadHolder thread_holder;
+		if (ep_thread_holder_init (&thread_holder, ep_thread_session_state_get_thread (thread_session_state))) {
+
+			// briefly hold the thread lock to check it's state
+			ep_rt_spin_lock_handle_t *thread_lock = ep_thread_get_rt_lock_ref (ep_thread_session_state_get_thread (thread_session_state));
+			EP_SPIN_LOCK_ENTER (thread_lock, section5)
+				// if the thread is unregistered delete the session state from it
+				if (ep_rt_volatile_load_uint32_t_without_barrier(&(ep_thread_holder_get_thread (&thread_holder))->unregistered) > 0) {
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c:1306]: Is there some scenario where we reach this point and this if condition is false?

**Comment by noahfalk** [comment]
@davmason - do you have a bit of time to look more closely at this?

@josalem - in my cursory look this seemed fine but I'm definitely hitting a learning curve now that this code has been converted to C and I can't easily find the which macros are generating some of the code elements. I'm going to need to come back and run this through the preprocessor to better understand how the code is working post-C-conversion. None of that is specific to your change, it just slows me down from being able to evaluate it.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 4]
```diff
@@ -1209,12 +1213,33 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
 					ep_rt_thread_session_state_list_iterator_next (&thread_session_state_list_iterator);
 				}
+
+				// foreach session_state_to_delete in session_states_to_delete
+				for (ep_rt_thread_session_state_array_iterator_t thread_session_state_array_iterator = ep_rt_thread_session_state_array_iterator_begin(&session_states_to_delete);
+					 !ep_rt_thread_session_state_array_iterator_end(&session_states_to_delete, &thread_session_state_array_iterator);
+					 ep_rt_thread_session_state_array_iterator_next(&thread_session_state_array_iterator)) {
+
+					EventPipeThreadSessionState * session_state = ep_rt_thread_session_state_array_iterator_value(&thread_session_state_array_iterator);
+					ep_rt_thread_session_state_list_remove(&buffer_manager->thread_session_state_list, session_state);
```
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer-manager.c:1241]: Maybe it could be worth adding support to remove an item in list based on iterator and return a new iterator as result (similar to stl::list::erase, then there wouldn't be a need for this second loop while still holding lock.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 5]
```diff
@@ -1231,6 +1256,61 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
+			ep_rt_thread_session_state_array_iterator_next(&thread_session_state_array_iterator)) {
+
+		EventPipeThreadSessionState * thread_session_state = ep_rt_thread_session_state_array_iterator_value(&thread_session_state_array_iterator);
+		EP_ASSERT (thread_session_state != NULL);
+		// This may be the last reference to a given EventPipeThread, so make a ref to keep it around till we're done
+		EventPipeThreadHolder thread_holder;
+		if (ep_thread_holder_init (&thread_holder, ep_thread_session_state_get_thread (thread_session_state))) {
+
+			// briefly hold the thread lock to check it's state
+			ep_rt_spin_lock_handle_t *thread_lock = ep_thread_get_rt_lock_ref (ep_thread_session_state_get_thread (thread_session_state));
```
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer-manager.c:1303]: More clean if you get thread instance from the thread holder instead of mixing thread holder and thread session state when accessing EventPipeThread in this code section. Might be even more cleaner (and less code) to put EventPiptThread into a local variable and use that.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 6]
```diff
@@ -1209,12 +1213,33 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
+						} else {
 							ep_thread_addref (ep_thread_holder_get_thread (ep_thread_session_state_get_thread_holder_ref (session_state)));
+						}
+						ep_rt_thread_sequence_number_map_add (ep_sequence_point_get_thread_sequence_numbers_ref (sequence_point), session_state, last_read_sequence_number);
+					}
+
+					// if a session_state was exhausted during this sequence point, mark it for deletion
+					if (ep_thread_session_state_get_buffer_list(session_state)->head_buffer == NULL) {
+
+						if (ep_rt_volatile_load_uint32_t_without_barrier(&(ep_thread_session_state_get_thread(session_state))->unregistered) > 0) {
```
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer-manager.c:1227]: You should access unregistered filed through a getter since it is declared as part of ep-thread.c and not directly accessible to ep-buffer-manager (if compiled without inline getter/setter), so it is a "private" field.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 3 above)
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer-manager.c:1306]: You should access unregistered filed through a getter since it is declared as part of ep-thread.c and not directly accessible to ep-buffer-manager (if compiled without inline getter/setter), so it is a "private" field.

File: src/native/eventpipe/ep-thread.h [hunk 7]
```diff
@@ -45,6 +45,11 @@ struct _EventPipeThread_Internal {
 	// that pointer will be protected from deletion. See ep_disable () and
 	// ep_write () for more detail.
 	volatile uint32_t writing_event_in_progress;
+	// This is set to non-zero when the thread is unregistered from the global list of EventPpe threads.
```
Comment (lateralusX) [inline src/native/eventpipe/ep-thread.h:48]: typo, EventPpe

File: src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h [hunk 8]
```diff
@@ -48,6 +48,9 @@
 #undef DS_LOG_DEBUG_0
 #define DS_LOG_DEBUG_0(msg) STRESS_LOG0(LF_DIAGNOSTICS_PORT, LL_INFO1000, msg)
 
+#undef DS_LOG_DEBUG_1
```
Comment (lateralusX) [inline src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h:51]: Couldn't find that this was used in PR (just defined), maybe it should be added for future or just a left over?

Comment (lateralusX) [reply src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h:51]: If you would like to keep it (for future) it needs to be added to ds-rt-mono.h as well.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 9]
```diff
@@ -1209,12 +1213,33 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
 					// miscategorize it, but that seems unlikely.
 					uint32_t last_read_delta = last_read_sequence_number - thread_sequence_number;
 					if (0 < last_read_delta && last_read_delta < 0x80000000) {
-						ep_rt_thread_sequence_number_map_add_or_replace (ep_sequence_point_get_thread_sequence_numbers_ref (sequence_point), session_state, last_read_sequence_number);
```
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer-manager.c:1212]: Any reason why add_or_replace couldn't be used? In theory that method could be a little more effective when hitting the replace scenario (depending on internal implementation).

File: src/native/eventpipe/ep-buffer-manager.c (hunk 4 above)
Comment (josalem) [reply src/native/eventpipe/ep-buffer-manager.c:1241]: I'd need to go take a look at the implementation of both Mono's list and Coreclr's SList. I agree though.  I think in the long run we should implement a set of container classes that are shared between the two runtimes or at least used in shared native code like this.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 5 above)
Comment (josalem) [reply src/native/eventpipe/ep-buffer-manager.c:1303]: a remnant of refactoring the for loops several times.

File: src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h (hunk 8 above)
Comment (josalem) [reply src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h:51]: ah, leftover from the histogram code I used during development.  I can just remove it.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 9 above)
Comment (josalem) [reply src/native/eventpipe/ep-buffer-manager.c:1212]: SHash in Coreclr is implemented so it can't have the remove trait _and_ the AddOrReplace trait on it. I didn't look into why, but I see this as more evidence we may want to eventually have a shared set of containers. It would remove ambiguity and runtime differences like this.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 3 above)
Comment (josalem) [reply src/native/eventpipe/ep-buffer-manager.c:1306]: Whoops. I don't believe there is. This is another remnant from me refactoring these for loops a few times.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 5 above)
Comment (josalem) [reply src/native/eventpipe/ep-buffer-manager.c:1303]: The holder is needed cause this may be the last reference to the EventPipeThread so we need to have a strong reference to keep it alive till we finish.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 4 above)
Comment (lateralusX) [reply src/native/eventpipe/ep-buffer-manager.c]: For list I believe it could be done since iterator just needs to move to a position in the list that continue to work after the item as been removed. I believe we should be able to implement it on both list implementation and be able to drop this second loop.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 9 above)
Comment (lateralusX) [reply src/native/eventpipe/ep-buffer-manager.c:1212]: OK, since you needed additional remove scenario you hit this with both behaviours on the hash map and needed to adjust. For Mono's hash map you could have both, feels like extending SHash map to have both could make sense as well.

Comment (lateralusX) [reply src/native/eventpipe/ep-buffer-manager.c:1212]: Looks like limitation is in `SHash<TRAITS>::AddOrReplace`:

`static_assert(!TRAITS::s_supports_remove, "SHash::AddOrReplace is not implemented for SHash with support for remove operations.");`

Comment (lateralusX) [reply src/native/eventpipe/ep-buffer-manager.c:1212]: The add_or_replace function on hash map was done when porting this use case over to C library, if we nuke the user of add_or_replace, then I think it will be good to remove that function from hash map implementation altogether.

File: src/native/eventpipe/ds-rt.h [hunk 10]
```diff
@@ -19,6 +19,7 @@
 #define DS_LOG_WARNING_1(msg, data1) ds_rt_redefine
 #define DS_LOG_WARNING_2(msg, data1, data2) ds_rt_redefine
 #define DS_LOG_DEBUG_0(msg) ds_rt_redefine
+#define DS_LOG_DEBUG_1(msg, data1) ds_rt_redefine
```
Comment (lateralusX) [inline src/native/eventpipe/ds-rt.h:22]: Remove?

**Comment by davmason** [comment]
@noahfalk I am starting to take a look but so far have the same issue as you. It will be slower than normal

**Comment by noahfalk** [comment]
@josalem @lateralusX @davmason - A sidebar, but given the general learning curve to understand the structure/conventions of the code post-C-conversion it may make sense for us to start a little README.md with useful notes? If anything like that already exists let me know but if not sometimes it can be useful to have newcomers (like myself) write it as they learn.

**Comment by lateralusX** [comment]
> @josalem @lateralusX @davmason - A sidebar, but given the general learning curve to understand the structure/conventions of the code post-C-conversion it may make sense for us to start a little README.md with useful notes? If anything like that already exists let me know but if not sometimes it can be useful to have newcomers (like myself) write it as they learn.

Some smaller description in initial PR's around high level structure of the library, https://github.com/dotnet/runtime/pull/34600, there is also more info in the talk/ppt held around EventPipe C port in .net platform talks in November. Writing up a file to collect information sounds like a good idea, feel free to ping me as well with questions.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 11]
```diff
@@ -1231,6 +1256,59 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
+					// foreach (session_state in session_states_to_delete)
+					for (ep_rt_thread_session_state_array_iterator_t thread_session_state_array_iterator = ep_rt_thread_session_state_array_iterator_begin (&session_states_to_delete);
+						!ep_rt_thread_session_state_array_iterator_end (&session_states_to_delete, &thread_session_state_array_iterator);
+						ep_rt_thread_session_state_array_iterator_next (&thread_session_state_array_iterator)) {
+
+						EventPipeThreadSessionState * thread_session_state = ep_rt_thread_session_state_array_iterator_value (&thread_session_state_array_iterator);
+						uint32_t thread_sequence_number = 0;
+						bool exists = ep_rt_thread_sequence_number_map_lookup (ep_sequence_point_get_thread_sequence_numbers_cref (sequence_point), thread_session_state, &thread_sequence_number);
+						if (exists) {
+							ep_rt_thread_sequence_number_map_remove (ep_sequence_point_get_thread_sequence_numbers_ref (sequence_point), thread_session_state);
```
Comment (sywhang) [inline src/native/eventpipe/ep-buffer-manager.c:1280]: Does this not race with the call to `ep_rt_thread_sequence_number_map_free`? From what I can see, it's possible for another thread to call methods in this sequence during disable:
`disable_holding_lock` -> `ep_session_write_sequence_point_unbuffered` -> `ep_session_write_sequence_point_unbuffered` -> `ep_sequence_point_fini` -> `sequence_point_fini` -> `ep_rt_thread_sequence_number_map_free`. 

`disable_holding_lock` (or all of the subsequent callees) doesn't try to grab the buffer manager's lock and only holds the EventPipe lock, while this thread only holds the buffer manager's lock. So it looks like a use after free can happen here? Comments in SHash says:

```
// - Remove operations may be asynchronous with Lookup/Add, unless elements are also deallocated. (In which
//    case full synchronization is required)
```

File: src/native/eventpipe/ep-thread.h [hunk 12]
```diff
@@ -45,6 +45,11 @@ struct _EventPipeThread_Internal {
 	// that pointer will be protected from deletion. See ep_disable () and
 	// ep_write () for more detail.
 	volatile uint32_t writing_event_in_progress;
+	// This is set to non-zero when the thread is unregistered from the global list of EventPipe threads.
+	// This should happen when a physical thread is ending.
+	// This is a convenience marker to prevent us from having to search the global list.
+	// defaults to false.
+	volatile uint32_t unregistered;
```
Comment (sywhang) [inline src/native/eventpipe/ep-thread.h:52]: if all we do to this value is set it to 0 or 1 can we use a smaller size type instead of uint32_t?

File: src/native/eventpipe/ep-buffer-manager.c [hunk 13]
```diff
@@ -1231,6 +1256,59 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
+
+					sequence_point = ep_rt_sequence_point_list_iterator_value (&sequence_point_list_iterator);
+
+					// foreach (session_state in session_states_to_delete)
+					for (ep_rt_thread_session_state_array_iterator_t thread_session_state_array_iterator = ep_rt_thread_session_state_array_iterator_begin (&session_states_to_delete);
+						!ep_rt_thread_session_state_array_iterator_end (&session_states_to_delete, &thread_session_state_array_iterator);
+						ep_rt_thread_session_state_array_iterator_next (&thread_session_state_array_iterator)) {
+
+						EventPipeThreadSessionState * thread_session_state = ep_rt_thread_session_state_array_iterator_value (&thread_session_state_array_iterator);
+						uint32_t thread_sequence_number = 0;
```
Comment (sywhang) [inline src/native/eventpipe/ep-buffer-manager.c:1277]: Is this used anywhere after its assigned a value? Looks like you only have it here so that you can pass it to `ep_rt_thread_sequence_number_map` that presumably assigns the number to it. Maybe declare it once outside of the nested for loops and add a comment saying it's unused or name it something like `unused_thread_sequence_number`.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 14]
```diff
@@ -1209,12 +1213,33 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
+						} else {
 							ep_thread_addref (ep_thread_holder_get_thread (ep_thread_session_state_get_thread_holder_ref (session_state)));
+						}
+						ep_rt_thread_sequence_number_map_add (ep_sequence_point_get_thread_sequence_numbers_ref (sequence_point), session_state, last_read_sequence_number);
+					}
+
+					// if a session_state was exhausted during this sequence point, mark it for deletion
+					if (ep_thread_session_state_get_buffer_list (session_state)->head_buffer == NULL) {
+
+						if (ep_rt_volatile_load_uint32_t_without_barrier (ep_thread_get_unregistered_ref (ep_thread_session_state_get_thread (session_state))) > 0) {
```
Comment (sywhang) [inline src/native/eventpipe/ep-buffer-manager.c:1227]: The unregistered field is getting accessed without proper synchronization with the thread getting unregistered assigning value 1 to it but It seems like that's ok since the next time this method is called it will be marked for deletion. Can we add a comment here saying that there is a possible race here and it's ok to have that race because it'll be marked for deletion upon the next time this method is invoked by the streaming thread?

**Review by sywhang — COMMENTED** [review]
Had same issue with Noah and David so it took a while - coming together nicely!

File: src/native/eventpipe/ep-buffer-manager.c (hunk 14 above)
Comment (josalem) [reply src/native/eventpipe/ep-buffer-manager.c:1227]: Yes, this was on purpose.  It wasn't worth taking the lock if we just had to wait till the next sequence point to mark it.  I'll add a comment saying as much.

File: src/native/eventpipe/ds-rt.h (hunk 10 above)
Comment (josalem) [reply src/native/eventpipe/ds-rt.h:22]: Yup!  Missed it in my code clean.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 11 above)
Comment (josalem) [reply src/native/eventpipe/ep-buffer-manager.c:1280]: Hmmmmm.... Let me do some thinking on this. This logic _only_ happens on the streaming thread, which gets turned off before session disable. I'll look and see if I can definitively say so, though.

Comment (josalem) [reply src/native/eventpipe/ep-buffer-manager.c:1280]: I'm pretty sure we're safe here. This logic is only happening while the streaming thread is live. The disable logic disables the streaming thread before doing the unbuffered writes:

`disable_holding_lock` -> \*`ep_session_disable` (this joins the thread where the new logic is running)\* -> `ep_session_write_sequence_point_unbuffered` -> `ep_session_write_sequence_point_unbuffered` -> `ep_sequence_point_fini` -> `sequence_point_fini` -> `ep_rt_thread_sequence_number_map_free`

File: src/native/eventpipe/ep-thread.h (hunk 12 above)
Comment (davmason) [reply src/native/eventpipe/ep-thread.h:52]: Structure alignment means it would not make a difference in overall structure size if we used uint8_t, it would still be padded to a 4 byte or 8 byte boundary depending on 32/64 bit. It would only save us space if we had other bytes of data to go after.

If we were really concerned about the size of this struct we could steal a bit from some other data here. E.g. ref_count we could take the high bit, it seems unlikely we'd ever have more than 2^31 ref counts

 I don't think 4 more bytes is a big concern since it's tied 1-1 with threads, they have so much overhead already (managed Thread object, 1MB stack space by default, etc).

File: src/native/eventpipe/ep-buffer-manager.c (hunk 11 above)
Comment (josalem) [reply src/native/eventpipe/ep-buffer-manager.c:1280]: As for the comment in `SHash` I think we're also good on that front. The actual dealloc happens under the thread lock, so it is only asynchronous while the object still exists.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 15]
```diff
@@ -1145,8 +1145,12 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
 
 	*events_written = false;
 
+	ep_rt_thread_session_state_list_iterator_t thread_session_state_list_iterator = ep_rt_thread_session_state_list_iterator_begin (&buffer_manager->thread_session_state_list);
```
Comment (davmason) [inline src/native/eventpipe/ep-buffer-manager.c:1148]: `thread_session_state_list_iterator` is declared here but not used before it's assigned again at line 1205

**Comment by josalem** [comment]
remaining test failure appears to be a known issue.

**Review by noahfalk — APPROVED** [review]
I think the change is good 👍 

The learning curve for conventions coming into this code felt pretty steep but I captured a few notes that helped me and might help others: https://github.com/dotnet/runtime/pull/49542

Given that I don't spend as much time in this code as others I don't want to make undue pressure to adjust conventions, but even after I knew what the patterns were it still felt as though I was spending a lot of mental energy to grok it. I didn't get the impression I was alone so it may be worth thinking about potential adjustments for easier readability?

**Comment by lateralusX** [comment]
> Given that I don't spend as much time in this code as others I don't want to make undue pressure to adjust conventions, but even after I knew what the patterns were it still felt as though I was spending a lot of mental energy to grok it. I didn't get the impression I was alone so it may be worth thinking about potential adjustments for easier readability?

Any suggestions are highly welcomed (since I'm know this code and architecture it inside out, I'm sort of adjusted to it), would be great to get a list of things that are the top "pain points" and I'm certain we can improve going forward. Parts of the library have some complexity due to taking C++ concepts into the C world and still try to keep type safety of underlying runtime implementation, like how the definitions of the the container implementations making it possible to hook up C++ artefact's in runtime implementations and when building library using C++ compiler (like CoreClr) get type safety checks by compiler. Library also implements getter/setters and virtual inheritance, that could complicate things and give long statements and sometime hard to track function calls (due to virtual inheritance, primarily in the serializer parts of the library). I tried really hard to setup a convention and follow it thoroughly in the implementation to simplify readability as much as possible, but since another ambition was to be close to C++ naming (making it easier to transition and maintain both code bases during transition time), names tended to be long and I believe that together with the getters sometimes can produce long statements and together with the compactness of C code, could make it harder to eyeball.

**Comment by noahfalk** [comment]
> Any suggestions are highly welcomed

I added a few thoughts over at https://github.com/dotnet/runtime/pull/49542#issuecomment-797812907. I think a lot of it aligns with things you were already considering. I agree with your goal of making the original translation very mechanical and now that we've completed the port and know everything is working well we probably have more safety margin to make refactoring adjustments. Thanks!

**Comment by josalem** [comment]
If there are no opinions otherwise, I will merge this later today.

**Review by lateralusX — APPROVED** [review]
