### PR TITLE
[mono][jit] Don't inflate Mono.ValueTuple with byrefs

### LINKED ISSUE #72635: Getting a runtime crash with the interpreter and 7.0 Preview 7
### Description

I am running the MAUI unit tests and I noticed that the runtime was crashing:

Full Log (1): https://gist.github.com/mattleibow/ebd7cd0919e5989ef84c933ae020d789
Full Log (2): https://gist.github.com/mattleibow/c43f8057007370cc123491d18a6f8808
Binlog: [Essentials.DeviceTests-Debug-android.zip](https://github.com/dotnet/runtime/files/9162544/Essentials.DeviceTests-Debug-android.zip)

```
07-21 15:39:58.884  4090  4090 I DOTNET  : 	[PASS] AspectInitializesCorrectly
07-21 15:39:58.890  4090  4090 D Mono    : Running class .cctor for System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1/AsyncStateMachineBox`1<System.Threading.Tasks.VoidTaskResult, Microsoft.Maui.DeviceTests.HandlerTestBase`2/<NeedsContainerWhenInputTransparent>d__18<Microsoft.Maui.Handlers.ImageButtonHandler, Microsoft.Maui.DeviceTests.Stubs.ImageButtonStub>> from 'System.Private.CoreLib.dll'
07-21 15:39:58.895  4090  4090 I DOTNET  : 	[PASS] NeedsContainerWhenInputTransparent
07-21 15:39:58.898  4090  4090 D Mono    : Request to load xunit.core in alc 0xab144c40
07-21 15:39:58.898  4090  4090 D Mono    : Assembly already loaded in the active ALC: 'xunit.core'.
07-21 15:39:58.899  4090  4090 D Mono    : Request to load xunit.core in alc 0xab144c40
07-21 15:39:58.899  4090  4090 D Mono    : Assembly already loaded in the active ALC: 'xunit.core'.
07-21 15:39:58.899  4090  4090 D Mono    : Request to load xunit.core in alc 0xab144c40
07-21 15:39:58.899  4090  4090 D Mono    : Assembly already loaded in the active ALC: 'xunit.core'.
07-21 15:39:58.903  4090  4090 D Mono    : Running class .cctor for System.IO.Path/<>c from 'System.Private.CoreLib.dll'
07-21 15:39:58.903  4090  4090 E         : couldn't compile wrapper "(wrapper other) void object:interp_in (Mono.ValueTuple`2<intptr&, int>,intptr)" for "void System.IO.Path/<>c:<JoinInternal>b__40_0 (System.Span`1<char>,intptr)"
--------- beginning of crash
07-21 15:39:58.903  4090  4090 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 4090 (ore.devicetests)
07-21 15:39:59.010  1599  1599 I SELinux : SELinux: Loaded file_contexts contexts from /file_contexts.
07-21 15:39:59.012  1599  1599 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

```
07-21 15:54:29.180  4447  4447 I DOTNET  : 	[PASS] InvalidUri
07-21 15:54:29.184  4447  4447 D Mono    : Request to load xunit.core in alc 0xf6611350
07-21 15:54:29.184  4447  4447 D Mono    : Assembly already loaded in the active ALC: 'xunit.core'.
07-21 15:54:29.189  4447  4447 D Mono    : Running class .cctor for System.Uri/<>c from 'System.Private.Uri.dll'
07-21 15:54:29.191  4447  4447 E als.devicetest: couldn't compile wrapper "(wrapper other) void object:interp_in (Mono.ValueTuple`2<intptr&, int>,Mono.ValueTuple`2<int, int>)" for "void System.Uri/<>c:<CheckSchemeSyntax>b__159_1 (System.Span`1<char>,System.ValueTuple`2<intptr, int>)"
--------- beginning of crash
07-21 15:54:29.191  4447  4447 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4447 (als.devicetests), pid 4447 (als.devicetests)
07-21 15:54:29.248  4646  4679 W DynamiteModule: Local module descriptor class for providerinstaller not found.
07-21 15:54:29.265  4962  4962 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
07-21 15:54:29.269   271   271 I tombstoned: received crash request for pid 4447
07-21 15:54:29.270  4962  4962 I crash_dump32: performing dump of process 4447 (target tid = 4447)
07-21 15:54:29.278  4962  4962 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

### Reproduction Steps

I'll try get this to you if there is a need and I am able to.

### Expected behavior

No crash.

### Actual behavior

Crash.

### Regression?

Yes.

### Known Workarounds

```xml
<UseInterpreter>false</UseInterpreter>
```

### Configuration

This was an Android test, and the info that was changed between runs I believe is this:

```diff
-    <Dependency Name="Microsoft.Dotnet.Sdk.Internal" Version="7.0.100-preview.7.22354.2" CoherentParentDependency="Microsoft.Android.Sdk.Windows">
+    <Dependency Name="Microsoft.Dotnet.Sdk.Internal" Version="7.0.100-preview.7.22362.31" CoherentParentDependency="Microsoft.Android.Sdk.Windows">
       <Uri>https://github.com/dotnet/installer</Uri>
-      <Sha>9239e0df2d4575a89657a1cd0414881b5bb858c5</Sha>
+      <Sha>d2fff6df585efa03cbe883b4fb6ce41be8d61342</Sha>
     </Dependency>
```

### Other information

_No response_

### PR DESCRIPTION
**Pull request by BrzVlad**
Mono.ValueTuple's must have the same layout as the original vtype. Use normal IntPtr for ref fields. This also allows sharing of more signatures. Before this change the behavior was dubious when sharing valuetypes with ref fields (like Span). The value tuple class was inflated with byref types and it ended up having byref fields, even though it is not byreflike, resulting in failure during class loading.

Fixes https://github.com/dotnet/runtime/issues/72635

### CODE REVIEW

File: src/mono/mono/mini/mini-generic-sharing.c [hunk 1]
```diff
@@ -1246,6 +1246,16 @@ get_wrapper_shared_vtype (MonoType *t)
 	}
 	g_assert (tuple_class);
 
+	for (int i = 0; i < findex; i++) {
+		if (m_type_is_byref (args [i])) {
+#if TARGET_SIZEOF_VOID_P == 8
+			args [i] = m_class_get_byval_arg (mono_defaults.int_class);
+#else
```
Comment (vargaz) [inline src/mono/mono/mini/mini-generic-sharing.c:1253]: Couldn't this be int_class in both cases ?

Comment (vargaz) [reply src/mono/mono/mini/mini-generic-sharing.c:1253]: Or int32/int64 for more sharing ?

Comment (BrzVlad) [reply src/mono/mono/mini/mini-generic-sharing.c:1253]: Was following the logic from https://github.com/dotnet/runtime/blob/main/src/mono/mono/mini/mini-generic-sharing.c#L1296 so I don't happen to use different types and prevent sharing

**Comment by BrzVlad** [comment]
@vargaz @lambdageek Could I get a review please ?

**Review by lambdageek — APPROVED** [review]
