### PR TITLE
JIT: don't dead store untracked OSR locals based on ref count

### LINKED ISSUE #89666: Span<byte> from local variable bug in .net 7.x Release
### Description

When using Span<byte> to map a local variable to an array, after a certain number of iterations, changing the local variable does not change the bytes ​​in the Span<byte>

```
    int value = 0;

    Span<byte> span = MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref value, 1));

    for (int i = 0; i < numEntries; i++)
    {
        //value = 0; bug fix for .net 7.x Release

        value = random.Next();

        file.Write(span);
    }
```

### Reproduction Steps

```
using System.Runtime.InteropServices;

#if DEBUG
string config = "Deb";
#else
string config = "Rel";
#endif

string template = "{0}.{1}.dat.{2}";

test(5000, 0);
test(5000, 1);
test(5000, 2);

cmp(0, 1);
cmp(0, 2);
cmp(1, 2);

void cmp(int fIdx, int sIdx)
{
    byte[] f = File.ReadAllBytes(string.Format(template, config, Environment.Version, fIdx));
    byte[] s = File.ReadAllBytes(string.Format(template, config, Environment.Version, sIdx));

    for (int i = 0; i < f.Length; i++)
    {
        if (f[i] != s[i])
        {
            Console.WriteLine("first diff {0} ~ {1}, offset={2}, {3}/{4}", f[i], s[i], i, string.Format(template, config, Environment.Version, fIdx), string.Format(template, config, Environment.Version, sIdx));
            return;
        }
    }

    Console.WriteLine("{0}/{1} is equal", string.Format(template, config, Environment.Version, fIdx), string.Format(template, config, Environment.Version, sIdx));
}

void test(long numEntries, int idx)
{
    Random random = new Random(1);

    using var file = File.OpenWrite(string.Format(template, config, Environment.Version, idx));

    file.SetLength(0);

    int value = 0;

    Span<byte> span = MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref value, 1));

    for (int i = 0; i < numEntries; i++)
    {
        //value = 0; bug fix for .net 7.x Release

        value = random.Next();

        file.Write(span);
    }
}

```

### Expected behavior

all output files must be identical

### Actual behavior

```
Results
 
first diff 15 ~ 222, offset=19996, Rel.7.0.9.dat.0/Rel.7.0.9.dat.1
first diff 96 ~ 241, offset=3996, Rel.7.0.9.dat.0/Rel.7.0.9.dat.2
first diff 96 ~ 241, offset=3996, Rel.7.0.9.dat.1/Rel.7.0.9.dat.2

Deb.7.0.9.dat.0/Deb.7.0.9.dat.1 is equal
Deb.7.0.9.dat.0/Deb.7.0.9.dat.2 is equal
Deb.7.0.9.dat.1/Deb.7.0.9.dat.2 is equal

Rel.6.0.20.dat.0/Rel.6.0.20.dat.1 is equal
Rel.6.0.20.dat.0/Rel.6.0.20.dat.2 is equal
Rel.6.0.20.dat.1/Rel.6.0.20.dat.2 is equal

```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

.net 6.0.20 
.net 7.0.9
Windows Server 2022

### Other information

_No response_

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The local var ref count for OSR locals can be misleading, since some of the appearances may be in the "tier0" parts of the methods and won't be visible once we trim the OSR method down to just the part we're going to compile.

So, we can't rely on ref counts to enable a dead store of an OSR local.

Fixes #89666.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
We will want to port this back to 7.0.

**Comment by AndyAyersMS** [comment]
No diffs locally.

File: src/coreclr/jit/liveness.cpp [hunk 1]
```diff
@@ -1575,7 +1575,11 @@ bool Compiler::fgComputeLifeUntrackedLocal(VARSET_TP&           life,
 
     // We have accurate ref counts when running late liveness so we can eliminate
     // some stores if the lhs local has a ref count of 1.
-    if (isDef && compRationalIRForm && (varDsc.lvRefCnt() == 1) && !varDsc.lvPinned)
+    //
+    // For OSR locals we can't rely on ref counts this way, since some of the appearances
+    // of the local may be in the now-unseen Tier0 portion.
+    //
+    if (isDef && compRationalIRForm && (varDsc.lvRefCnt() == 1) && !varDsc.lvPinned && !varDsc.lvIsOSRLocal)
```
Comment (jakobbotsch) [inline src/coreclr/jit/liveness.cpp:1582]: Presumably the problem exists only for address-exposed locals (since otherwise we _can_ see all uses, even in the OSR version). Add it as a condition to make the problem more self-evident? (I had to look at the test to understand why this would be illegal.)

Comment (AndyAyersMS) [reply src/coreclr/jit/liveness.cpp:1582]: > Presumably the problem exists only for address-exposed locals (since otherwise we _can_ see all uses, even in the OSR version). Add it as a condition to make the problem more self-evident? (I had to look at the test to understand why this would be illegal.)

Yeah, I can add that.

Another option is to mark any OSR exposed local as implicitly referenced; we do that for pinned locals where we have similar issues not seeing all of the IR.

https://github.com/dotnet/runtime/blob/b5834a0b59047a2157b164fed5da6176527b1949/src/coreclr/jit/lclvars.cpp#L276-L295

Comment (AndyAyersMS) [reply src/coreclr/jit/liveness.cpp:1582]: Using `lvImplicitlyReferenced` seems likely to be a bit more robust so I think I'll change to using that.

Comment (jakobbotsch) [reply src/coreclr/jit/liveness.cpp]: Does the code in liveness also need to check for `lvImplicitlyReferenced`? Or does something guarantee that `lvRefCount` for implicitly referenced locals is something indeterminately large?

Overall I guess I would assume that all address exposed locals already have to effectively be considered implicitly referenced (whether or not we set that bit), but this seems fine with me.

**Comment by AndyAyersMS** [comment]
This revised version will have a few diffs; the implicit weight changes the overall local weights, and this sometimes perturbs LSRA.

File: src/coreclr/jit/liveness.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/liveness.cpp]: The ref count for implicit locals will be one greater than the number of actual occurrences, so will be at least 2 in this case.

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
> This revised version will have a few diffs; the implicit weight changes the overall local weights, and this sometimes perturbs LSRA.

I suppose it is a bit conservative/unnecessary to mark these as implicitly referenced; if we prove in the OSR version that it is _not_ address exposed, then that should effectively override the conservative tier0 exposure information, and we can then safely reason about all defs/uses.

**Comment by AndyAyersMS** [comment]
Errors are known. [Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359417&view=ms.vss-build-web.run-extensions-tab)
