### PR TITLE
Fix explicit layout validator memory alloc problems

### LINKED ISSUE #53559: CG2 crash in compilation of Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test3\test3.cmd
OS: Windows
Architecture: x86
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1165903&view=ms.vss-test-web.build-test-results-tab&runId=35147304&resultId=103353&paneView=debug

Diagnostic information:

<pre>
Response file: C:\h\w\9D670916\w\B1DF0987\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test3\test3.dll.rsp
C:\h\w\9D670916\w\B1DF0987\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test3\IL-CG2\test3.dll
-o:C:\h\w\9D670916\w\B1DF0987\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test3\test3.dll
--targetarch:x86
--verify-type-and-field-layout
-r:C:\h\w\9D670916\p\System..dll
-r:C:\h\w\9D670916\p\Microsoft..dll
-r:C:\h\w\9D670916\p\mscorlib.dll
-r:C:\h\w\9D670916\p\netstandard.dll
-O
" "dotnet" "C:\h\w\9D670916\p\crossgen2\crossgen2.dll" @"C:\h\w\9D670916\w\B1DF0987\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test3\test3.dll.rsp"   -r:C:\h\w\9D670916\w\B1DF0987\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test3\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
</pre>

/cc @dotnet/crossgen-contrib

### LINKED ISSUE #55164: Test failure Loader\\classloader\\explicitlayout\\Regressions\\ASURT\\ASURT150271\\test16\\test16.cmd
Run: [runtime-coreclr r2r-extra 20210703.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1219742&view=ms.vss-test-web.build-test-results-tab&runId=36364128&paneView=debug&resultId=103911)

Failed test:
```
R2R windows x86 Checked jitstress1 @ Windows.10.Amd64.Open

- Loader\\classloader\\explicitlayout\\Regressions\\ASURT\\ASURT150271\\test16\\test16.cmd

```
**Error message:**
```
Could Not Find C:\h\w\BAED0A29\w\A1350936\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test16\test16.dll.rsp
Out of memory.

Return code:      1
Raw output file:      C:\h\w\BAED0A29\w\A1350936\uploads\Reports\Loader.classloader\explicitlayout\Regressions\ASURT\ASURT150271\test16\test16.output.txt
Raw output:
BEGIN EXECUTION
test16.dll
1 file(s) copied.
Response file: C:\h\w\BAED0A29\w\A1350936\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test16\test16.dll.rsp
C:\h\w\BAED0A29\w\A1350936\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test16\IL-CG2\test16.dll
-o:C:\h\w\BAED0A29\w\A1350936\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test16\test16.dll
--targetarch:x86
--verify-type-and-field-layout
-r:C:\h\w\BAED0A29\p\System..dll
-r:C:\h\w\BAED0A29\p\Microsoft..dll
-r:C:\h\w\BAED0A29\p\mscorlib.dll
-r:C:\h\w\BAED0A29\p\netstandard.dll
-O
" "dotnet" "C:\h\w\BAED0A29\p\crossgen2\crossgen2.dll" @"C:\h\w\BAED0A29\w\A1350936\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test16\test16.dll.rsp"   -r:C:\h\w\BAED0A29\w\A1350936\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test16\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\BAED0A29\p
C:\h\w\BAED0A29\w\A1350936\e\Loader\classloader\explicitlayout\Regressions\ASURT\ASURT150271\test16\test16.cmd
Expected: True
Actual:   False


Stack trace
   at Loader_classloader._explicitlayout_Regressions_ASURT_ASURT150271_test16_test16_._explicitlayout_Regressions_ASURT_ASURT150271_test16_test16_cmd() in Loader.classloader.XUnitWrapper.dll:token 0x6000d98+0x284
```

### PR DESCRIPTION
**Pull request by davidwrighton**
The ExplicitLayoutValidator currently used an array of bytes one to one with the size of the layout of the class. However, we have some test cases for outrageously large explicit layout structures and classes which cause this approach to OOM in crossgen2.

The fix is to move to a data structure defined in terms of intervals. This is probably a bit slower, but it requires vastly less memory for pathological situations.

Fixes #55164
Fixes #53559

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/crossgen-contrib

**Comment by MichalStrehovsky** [comment]
TIL.

I suggested using a byte array when this was introduced because CoreCLR uses that and it was an easy to follow algorithm. Didn't think we allow such big classes.

```csharp
[StructLayout(LayoutKind.Explicit, Size = Int32.MaxValue)]
struct Boo { }

[StructLayout(LayoutKind.Explicit)]
class Program
{
    [FieldOffset(0)]
    Boo b;

    static void Main() { }
}
```

This crashes 5.0 CoreCLR on x86 big time (somewhere in native-land that I didn't debug). Fun.

File: src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs [hunk 1]
```diff
@@ -15,22 +16,64 @@ private enum FieldLayoutTag : byte
...
+                    Size = value - Start;
+                    Debug.Assert(Size >= 0);
+                }
+            }
+
+            public FieldLayoutTag Tag;
+
+            public int CompareTo(FieldLayoutInterval other)
+            {
+                if (other.Start == Start)
```
Comment (trylek) [inline src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs:48]: Non-blocking nit - looks like it might suffice to <code>return Start.CompareTo(other.Start)</code>.

File: src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs [hunk 2]
```diff
@@ -125,27 +179,133 @@ private void MarkORefLocations(MetadataType type, bool[] orefMap, int offset)
...
-        private void SetFieldLayout(int offset, int count, FieldLayoutTag tag)
+        private void SetFieldLayout(List<FieldLayoutInterval> fieldLayoutInterval, int offset, int count, FieldLayoutTag tag)
         {
-            for (int index = 0; index < count; index++)
+            if (count == 0)
+                return;
+
+            var newInterval = new FieldLayoutInterval(offset, count, tag);
+
+            int binarySearchIndex = fieldLayoutInterval.BinarySearch(new FieldLayoutInterval(offset, 0, FieldLayoutTag.Empty));
```
Comment (trylek) [inline src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs:189]: Nit - why can't we just <code>BinarySearch(newInterval)</code>?

**Review by trylek — APPROVED** [review]
LGTM, thanks for making this more robust!

File: src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs (hunk 2 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs:189]: We can, I just forgot to do that when I refactored the logic to make that the obvious thing to do.

File: src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs (hunk 1 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs:48]: Yeah, that's a bit more obvious.
