### PR TITLE
Http2LoopbackConnection properly handles stream termination

### LINKED ISSUE #31220: PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent - IOException: End of Stream
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent
```
System.IO.IOException : End of stream

Stack trace
   at System.Net.Test.Common.Http2LoopbackConnection.ReadBodyAsync() in /_/src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 488
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass67_0.<<PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent>b__1>d.MoveNext() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1931
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 186
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.PostAsyncExpect100Continue_NonSuccessResponse_RequestBodyNotSent() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1899
--- End of stack trace from previous location ---
```
https://dev.azure.com/dnceng/public/_build/results?buildId=393660&view=ms.vss-test-web.build-test-results-tab&runId=12233140&resultId=157765&paneView=debug

netcoreapp-Linux-Debug-x64-(Alpine.310.Amd64.Open)ubuntu.1604.amd64.Open

### PR DESCRIPTION
**Pull request by alnikola**
PR adds an optional stream termination handling to `Http2LoopbackConnection.ReadBodyAsync` and fixes `HttpClient` construction missing the `SocketHttpHandler` created in the test.

Fixes #31220

### CODE REVIEW

File: src/libraries/Common/tests/System/Net/Http/TestHelper.cs [hunk 1]
```diff
@@ -130,6 +130,23 @@ public static void EnableUnencryptedHttp2IfNecessary(HttpClientHandler handler)
             object socketsHttpHandler = socketsHttpHandlerField.GetValue(handler);
             Assert.NotNull(socketsHttpHandler);
 
+            EnableUncryptedHttp2(socketsHttpHandler);
+        }
+
+#if !NETFRAMEWORK
```
Comment (wfurt) [inline src/libraries/Common/tests/System/Net/Http/TestHelper.cs:136]: Why do we need this? Should we fix either PlatformDetection or the capability Instead?

Comment (alnikola) [reply src/libraries/Common/tests/System/Net/Http/TestHelper.cs:136]: `SocketsHttpHandler` type is not available on the full .Net Framework, so conditional compilation seems to be the only way.

Comment (stephentoub) [reply src/libraries/Common/tests/System/Net/Http/TestHelper.cs:136]: So why type it as `SocketsHttpHandler` rather than `object`, as the other functions this is called from and it's calling is doing?

Comment (alnikola) [reply src/libraries/Common/tests/System/Net/Http/TestHelper.cs:136]: It's to distinct it from the [other overload taking HttpClientHandler](https://github.com/dotnet/runtime/blob/cb60aaa2408f8423d95d3ef03ae5b6f372a1945b/src/libraries/Common/tests/System/Net/Http/TestHelper.cs#L116).

Comment (alnikola) [reply src/libraries/Common/tests/System/Net/Http/TestHelper.cs:136]: Of course, I could have made it `object`, but think an explicit type is more convenient.

File: src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs [hunk 2]
```diff
@@ -1862,16 +1862,16 @@ public async Task PostAsyncExpect100Continue_SendRequest_Ok(bool send100Continue
...
         {
             string responseContent = "no no!";
 
             await Http2LoopbackServer.CreateClientAndServerAsync(async url =>
             {
                 using (var handler = new SocketsHttpHandler())
-                using (HttpClient client = CreateHttpClient())
+                using (HttpClient client = CreateHttpClient(handler))
                 {
+                    TestHelper.EnableUnencryptedHttp2IfNecessary(handler);
```
Comment (ManickaP) [inline src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:1874]: Just a question, why do we need this here?

Comment (alnikola) [reply src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:1874]: It enables **unencrypted** HTTP/2 on platforms without ALPN support (e.g. OSX) where we cannot use SSL over HTTP/2. Check [this line](https://github.com/dotnet/runtime/pull/35100/files/cb60aaa2408f8423d95d3ef03ae5b6f372a1945b#diff-4210bd74dd22b1469b8bf0307675ed37R139).

Comment (ManickaP) [reply src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:1874]: So if I get it right, we're using here `SocketsHttpHandler` just because we need to set `Expect100ContinueTimeout`, since `HttpClientHandler` doesn't have such property.
And what we do on these 2 lines here [HttpClientHandlerTest.Http2.cs#L1874-L1875](https://github.com/dotnet/runtime/blob/cb60aaa2408f8423d95d3ef03ae5b6f372a1945b/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs#L1874-L1875) is pretty much the same as what's done in [HttpClientHandlerTestBase.SocketsHttpHandler.cs#L22-L23](https://github.com/dotnet/runtime/blob/cb60aaa2408f8423d95d3ef03ae5b6f372a1945b/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTestBase.SocketsHttpHandler.cs#L22-L23).

**Review by ManickaP — APPROVED** [review]
LGTM

File: src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs (hunk 2 above)
Comment (alnikola) [reply src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:1874]: Correct.
