### PR TITLE
[tests] Fix integer rounding error in GetTestFileName

### LINKED ISSUE #52257: [iOS][tvOS] System.IO.FileStream.Tests crashes with ((null) warning) Process terminated due to System.Diagnostics.DebugProvider.Fail
The suite continues to crash after individually skipping the test facts that cause the crash. An example of the error and stack trace obtained from a crash is 
```
info	13:37:25.840153-0400	System.IO.FileSystem.Tests	((null) warning) Process terminated due to "   at System.Diagnostics.DebugProvider.Fail(String message, String detailMessage) in System.Private.CoreLib.dll:token 0x60056e2+0x0
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in System.Private.CoreLib.dll:token 0x60056a4+0x0
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage) in System.Private.CoreLib.dll:token 0x60056a1+0x0
   at System.Diagnostics.Debug.Assert(Boolean condition) in System.Private.CoreLib.dll:token 0x600569f+0x0
   at System.IO.FileCleanupTestBase.GetTestFileName(Nullable`1 index, String memberName, Int32 lineNumber) in TestUtilities.dll:token 0x60000f1+0x0
   at System.IO.FileCleanupTestBase.GetTestFilePath(Nullable`1 index, String memberName, Int32 lineNumber) in TestUtilities.dll:token 0x60000f0+0x0
   at System.IO.Tests.FileStream_ctor_str_fm_fa_fs.FileShareDeleteExistingRename() in System.IO.FileSystem.Tests.dll:token 0x60002b4+0x0
   at System.Reflection.RuntimeMethodInfo.InternalInvoke(RuntimeMethodInfo , Object , Object[] , Exception& ) in System.Private.CoreLib.dll:token 0x0+0x0
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004a65+0x0
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in System.Private.CoreLib.dll:token 0x60049b8+0x0
   at Xunit.Sdk.TestInvoker`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].CallTestMethod(Object testClassInstance) in xunit.execution.dotnet.dll:token 0x6000103+0x0
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x600058d+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<<InvokeTestMethodAsync>b__1>d](<<InvokeTestMethodAsync>b__1>d& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].<InvokeTestMethodAsync>b__1() in xunit.execution.dotnet.dll:token 0x60004a9+0x0
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in xunit.execution.dotnet.dll:token 0x600008d+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<AggregateAsync>d__4](<AggregateAsync>d__4& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in xunit.execution.dotnet.dll:token 0x600008d+0x0
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].<InvokeTestMethodAsync>b__0() in xunit.execution.dotnet.dll:token 0x60004a8+0x0
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in xunit.core.dll:token 0x6000070+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunAsync>d__9](<RunAsync>d__9& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in xunit.core.dll:token 0x6000070+0x0
   at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__48[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x60004aa+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<InvokeTestMethodAsync>d__48](<InvokeTestMethodAsync>d__48& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestInvoker`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].InvokeTestMethodAsync(Object testClassInstance) in xunit.execution.dotnet.dll:token 0x6000106+0x0
   at Xunit.Sdk.XunitTestInvoker.InvokeTestMethodAsync(Object testClassInstance) in xunit.execution.dotnet.dll:token 0x6000175+0x0
   at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__47_0>d[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x60004ac+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<<RunAsync>b__47_0>d](<<RunAsync>b__47_0>d& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestInvoker`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].<RunAsync>b__47_0() in xunit.execution.dotnet.dll:token 0x6000108+0x0
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1[[System.Decimal, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in xunit.core.dll:token 0x60000bf+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunAsync>d__10`1](<RunAsync>d__10`1& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.ExceptionAggregator.RunAsync[Decimal](Func`1 code) in xunit.core.dll:token 0x6000071+0x0
   at Xunit.Sdk.TestInvoker`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].RunAsync() in xunit.execution.dotnet.dll:token 0x6000105+0x0
   at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator) in xunit.execution.dotnet.dll:token 0x600017d+0x0
   at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) in xunit.execution.dotnet.dll:token 0x600017c+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<InvokeTestAsync>d__4](<InvokeTestAsync>d__4& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) in xunit.execution.dotnet.dll:token 0x600017c+0x0
   at Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].<RunAsync>b__0() in xunit.execution.dotnet.dll:token 0x60004b3+0x0
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1[[System.Tuple`2[[System.Decimal, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in xunit.core.dll:token 0x60000bf+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunAsync>d__10`1](<RunAsync>d__10`1& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.ExceptionAggregator.RunAsync[Tuple`2](Func`1 code) in xunit.core.dll:token 0x6000071+0x0
   at Xunit.Sdk.TestRunner`1.<RunAsync>d__43[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x60004b4+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunAsync>d__43](<RunAsync>d__43& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestRunner`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].RunAsync() in xunit.execution.dotnet.dll:token 0x6000134+0x0
   at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync() in xunit.execution.dotnet.dll:token 0x6000153+0x0
   at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x600048f+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunAsync>d__19](<RunAsync>d__19& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestCaseRunner`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].RunAsync() in xunit.execution.dotnet.dll:token 0x60000bd+0x0
   at Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource) in xunit.execution.dotnet.dll:token 0x6000246+0x0
   at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in xunit.execution.dotnet.dll:token 0x6000179+0x0
   at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x60004b0+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunTestCasesAsync>d__32](<RunTestCasesAsync>d__32& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestMethodRunner`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].RunTestCasesAsync() in xunit.execution.dotnet.dll:token 0x600011b+0x0
   at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x60004ae+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunAsync>d__31](<RunAsync>d__31& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestMethodRunner`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].RunAsync() in xunit.execution.dotnet.dll:token 0x600011a+0x0
   at Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments) in xunit.execution.dotnet.dll:token 0x600015e+0x0
   at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x6000498+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunTestMethodsAsync>d__38](<RunTestMethodsAsync>d__38& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestClassRunner`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].RunTestMethodsAsync() in xunit.execution.dotnet.dll:token 0x60000d5+0x0
   at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x6000496+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunAsync>d__37](<RunAsync>d__37& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestClassRunner`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].RunAsync() in xunit.execution.dotnet.dll:token 0x60000d4+0x0
   at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(ITestClass testClass, IReflectionTypeInfo class, IEnumerable`1 testCases) in xunit.execution.dotnet.dll:token 0x600016e+0x0
   at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x600049f+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunTestClassesAsync>d__28](<RunTestClassesAsync>d__28& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestCollectionRunner`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].RunTestClassesAsync() in xunit.execution.dotnet.dll:token 0x60000e9+0x0
   at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x600049a+0x0
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunAsync>d__27](<RunAsync>d__27& stateMachine) in System.Private.CoreLib.dll:token 0x600464c+0x0
   at Xunit.Sdk.TestCollectionRunner`1[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].RunAsync() in xunit.execution.dotnet.dll:token 0x60000e8+0x0
   at Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(IMessageBus messageBus, ITestCollection testCollection, IEnumerable`1 testCases, CancellationTokenSource cancellationTokenSource) in xunit.execution.dotnet.dll:token 0x600013f+0x0
   at Xunit.Sdk.TestAssemblyRunner`1.<RunTestCollectionsAsync>d__42[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x600048d+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestAssemblyRunner`1.<RunTestCollectionsAsync>d__42[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].ExecutionContextCallback(Object s) in System.Private.CoreLib.dll:token 0x6004677+0x0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002b1e+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestAssemblyRunner`1.<RunTestCollectionsAsync>d__42[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext(Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x600467b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestAssemblyRunner`1.<RunTestCollectionsAsync>d__42[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in System.Private.CoreLib.dll:token 0x600467a+0x0
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in System.Private.CoreLib.dll:token 0x600309a+0x0
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in System.Private.CoreLib.dll:token 0x6002fac+0x0
   at System.Threading.Tasks.Task.FinishContinuations() in System.Private.CoreLib.dll:token 0x6002fab+0x0
   at System.Threading.Tasks.Task`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].TrySetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x6002e8b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetExistingTaskResult(Task`1 task, RunSummary result) in System.Private.CoreLib.dll:token 0x600466f+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x600466e+0x0
   at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x600049a+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].ExecutionContextCallback(Object s) in System.Private.CoreLib.dll:token 0x6004677+0x0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002b1e+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext(Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x600467b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in System.Private.CoreLib.dll:token 0x600467a+0x0
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in System.Private.CoreLib.dll:token 0x600309a+0x0
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in System.Private.CoreLib.dll:token 0x6002fac+0x0
   at System.Threading.Tasks.Task.FinishContinuations() in System.Private.CoreLib.dll:token 0x6002fab+0x0
   at System.Threading.Tasks.Task`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].TrySetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x6002e8b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetExistingTaskResult(Task`1 task, RunSummary result) in System.Private.CoreLib.dll:token 0x600466f+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x600466e+0x0
   at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x600049f+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].ExecutionContextCallback(Object s) in System.Private.CoreLib.dll:token 0x6004677+0x0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002b1e+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext(Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x600467b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in System.Private.CoreLib.dll:token 0x600467a+0x0
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in System.Private.CoreLib.dll:token 0x600309a+0x0
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in System.Private.CoreLib.dll:token 0x6002fac+0x0
   at System.Threading.Tasks.Task.FinishContinuations() in System.Private.CoreLib.dll:token 0x6002fab+0x0
   at System.Threading.Tasks.Task`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].TrySetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x6002e8b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetExistingTaskResult(Task`1 task, RunSummary result) in System.Private.CoreLib.dll:token 0x600466f+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x600466e+0x0
   at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x6000496+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].ExecutionContextCallback(Object s) in System.Private.CoreLib.dll:token 0x6004677+0x0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002b1e+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext(Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x600467b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in System.Private.CoreLib.dll:token 0x600467a+0x0
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in System.Private.CoreLib.dll:token 0x600309a+0x0
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in System.Private.CoreLib.dll:token 0x6002fac+0x0
   at System.Threading.Tasks.Task.FinishContinuations() in System.Private.CoreLib.dll:token 0x6002fab+0x0
   at System.Threading.Tasks.Task`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].TrySetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x6002e8b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetExistingTaskResult(Task`1 task, RunSummary result) in System.Private.CoreLib.dll:token 0x600466f+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x600466e+0x0
   at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x6000498+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].ExecutionContextCallback(Object s) in System.Private.CoreLib.dll:token 0x6004677+0x0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002b1e+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext(Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x600467b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in System.Private.CoreLib.dll:token 0x600467a+0x0
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in System.Private.CoreLib.dll:token 0x600309a+0x0
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in System.Private.CoreLib.dll:token 0x6002fac+0x0
   at System.Threading.Tasks.Task.FinishContinuations() in System.Private.CoreLib.dll:token 0x6002fab+0x0
   at System.Threading.Tasks.Task`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].TrySetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x6002e8b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetExistingTaskResult(Task`1 task, RunSummary result) in System.Private.CoreLib.dll:token 0x600466f+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x600466e+0x0
   at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x60004ae+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].ExecutionContextCallback(Object s) in System.Private.CoreLib.dll:token 0x6004677+0x0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002b1e+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext(Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x600467b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in System.Private.CoreLib.dll:token 0x600467a+0x0
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in System.Private.CoreLib.dll:token 0x600309a+0x0
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in System.Private.CoreLib.dll:token 0x6002fac+0x0
   at System.Threading.Tasks.Task.FinishContinuations() in System.Private.CoreLib.dll:token 0x6002fab+0x0
   at System.Threading.Tasks.Task`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].TrySetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x6002e8b+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetExistingTaskResult(Task`1 task, RunSummary result) in System.Private.CoreLib.dll:token 0x600466f+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].SetResult(RunSummary result) in System.Private.CoreLib.dll:token 0x600466e+0x0
   at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].MoveNext() in xunit.execution.dotnet.dll:token 0x60004b0+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]], xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].ExecutionContextCallback(Object s) in System.Private.CoreLib.dll:token 0x6004677+0x0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002b1e+0x0
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[Xunit.Sdk.RunSummary, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c],[Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32[[Xunit.Sdk.IXunitTestCase, xunit.core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1b<…>
```

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes #52257

There seemed to be an integer rounding error when getting a portion of the test file name. Using the suggestion https://github.com/dotnet/runtime/issues/52257#issuecomment-832163922 led to the tests running to completion with no crashes or hangs.

### CODE REVIEW

File: src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs [hunk 1]
```diff
@@ -102,7 +102,9 @@ protected string GetTestFileName(int? index = null, [CallerMemberName] string me
                 if (excessLength < memberName.Length + "...".Length)
                 {
                     // Take a chunk out of the middle as perhaps it's the least interesting part of the name
-                    memberName = memberName.Substring(0, memberName.Length / 2 - excessLength / 2) + "..." + memberName.Substring(memberName.Length / 2 + excessLength / 2);
+                    int halfMemberNameLength = (int)Math.Floor((double)memberName.Length / 2);
+                    int halfExcessLength = (int)Math.Floor((double)excessLength / 2);
```
Comment (danmoseley) [inline src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs:106]: This should probably be Ceil not Floor, and then we don't need the +1 on the math.

Comment (danmoseley) [inline src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs:106]:
```suggestion
                    int halfExcessLength = (int)Math.Ceiling((double)excessLength / 2);
```

File: src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs [hunk 2]
```diff
@@ -102,7 +102,9 @@ protected string GetTestFileName(int? index = null, [CallerMemberName] string me
...
+                    memberName = memberName.Substring(0, halfMemberNameLength - halfExcessLength) + "..." + memberName.Substring(halfMemberNameLength + halfExcessLength + 1);
```
Comment (danmoseley) [inline src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs:107]:
```suggestion
                    memberName = memberName.Substring(0, halfMemberNameLength - halfExcessLength) + "..." + memberName.Substring(halfMemberNameLength + halfExcessLength);
```

**Review by danmoseley — APPROVED** [review]
