### PR TITLE
Insert a set of known types and methods references necessary for async thunks into the mutable module

### LINKED ISSUE #121644: Fix references in generated IL with mutable module.

### LINKED ISSUE #121722: AsyncHelpers used in async thunks may not have references in the ReadyToRun version bubble
A number of AsyncHelpers methods are used in the async thunks. These method may not have methodref tokens within assemblies in the R2R version bubble. Some places in crossgen assert this, and generating fixups for these methods isn't possible without a methodref token. These should be dynamically generated in the MutableModule, and the asserts should be updated to ensure any references in generated IL outside the version bubble is a "known" exception that has been accounted for.

### PR DESCRIPTION
**Pull request by jtschuster**
Async thunk IL references methods and types that may not have MethodRef or TypeRef tokens in the assembly being crossgen'ed. There are some assertions to validate that any references in "faux il" version with the assembly, which isn't true for these types and methods. To work around this, we can inject these references into the mutable module, a synthetic module added to the assembly for things like this. When trying to compile an async thunk method, we check to see if all the required methods are already in the mutable module. If not, we note which methods need to be added during the single-threaded execution, and queue the method for recompilation next iteration.

### CODE REVIEW

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs [hunk 1]
```diff
@@ -436,5 +438,123 @@ public DummyTypeInfo GetTypeFromSpecification(MetadataReader reader, ModuleToken
...
+                    // We can skip methods that are already in the version bubble
+                    if (_compilationModuleGroup.VersionsWithMethodBody((EcmaMethod)method))
+                        continue;
+
+                    EntityHandle ? handle = _manifestMutableModule.TryGetEntityHandle(method);
+                    if (!handle.HasValue)
+                        throw new NotImplementedException($"Entity handle for known method ({method}) not found in manifest module");
+
+                    var token = new ModuleToken(_manifestMutableModule, handle.Value);
+                    this.AddModuleTokenForMethod(method, token);
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Does this mean that every R2R image is going to have metadata for references to all async helpers? 

We should be creating these metadata tokens lazily, only when the async helper is actually used.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs [hunk 2]
```diff
@@ -436,5 +438,123 @@ public DummyTypeInfo GetTypeFromSpecification(MetadataReader reader, ModuleToken
...
+            knownMethods.Add(asyncHelpers.GetKnownMethod("ValueTaskFromException"u8, new MethodSignature(MethodSignatureFlags.Static, 0, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "ValueTask"u8), new TypeDesc[] { exception })));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("TaskFromException"u8, new MethodSignature(MethodSignatureFlags.Static, 1, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "Task`1"u8).MakeInstantiatedType(CompilerContext.GetSignatureVariable(0, method: true)), new TypeDesc[] { exception })));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("ValueTaskFromException"u8, new MethodSignature(MethodSignatureFlags.Static, 1, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "ValueTask`1"u8).MakeInstantiatedType(CompilerContext.GetSignatureVariable(0, method: true)), new TypeDesc[] { exception })));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("FinalizeTaskReturningThunk"u8, new MethodSignature(MethodSignatureFlags.Static, 0, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "Task"u8), Array.Empty<TypeDesc>())));
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Given that this is somewhat setting the names of these methods in stone, we should make sure that they have good names, following the same principles we use to name public APIs.

I would expect that a method called `FinalizeFoo` is going to take `Foo` as an argument. It is not what this method does. This can use a better name.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs [hunk 3]
```diff
@@ -436,5 +438,123 @@ public DummyTypeInfo GetTypeFromSpecification(MetadataReader reader, ModuleToken
...
+            knownMethods.Add(asyncHelpers.GetKnownMethod("FinalizeTaskReturningThunk"u8, new MethodSignature(MethodSignatureFlags.Static, 1, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "Task`1"u8).MakeInstantiatedType(CompilerContext.GetSignatureVariable(0, method: true)), Array.Empty<TypeDesc>())));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("FinalizeValueTaskReturningThunk"u8, new MethodSignature(MethodSignatureFlags.Static, 1, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "ValueTask`1"u8).MakeInstantiatedType(CompilerContext.GetSignatureVariable(0, method: true)), Array.Empty<TypeDesc>())));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("TransparentAwait"u8, null));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("CompletedTask"u8, null));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("CompletedTaskResult"u8, null));
+
+            // ExecutionAndSyncBlockStore type and methods
+            var executionSyncBlockStore = CompilerContext.SystemModule.GetKnownType("System.Runtime.CompilerServices"u8, "ExecutionAndSyncBlockStore"u8);
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Similar here - `ExecutionAndSyncBlockStore` does not look like a great name to me.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs [hunk 4]
```diff
@@ -436,5 +438,123 @@ public DummyTypeInfo GetTypeFromSpecification(MetadataReader reader, ModuleToken
                 return DummyTypeInfo.Instance;
             }
         }
+
+        private ImmutableHashSet<MethodDesc> KnownMethods;
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Immutable collections are meant to be used for collections updated in lock-free way. They pay extra overhead for the lock-free nature.

If you just a have a hashtable that gets initialized once and then just used for lookups, regular HashSet is going to work just fine and be faster.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs [hunk 5]
```diff
@@ -436,5 +438,123 @@ public DummyTypeInfo GetTypeFromSpecification(MetadataReader reader, ModuleToken
...
+
+            var exception = CompilerContext.SystemModule.GetKnownType("System"u8, "Exception"u8);
+            knownTypes.Add(exception);
+
+            // AsyncHelpers type and methods
+            var asyncHelpers = CompilerContext.SystemModule.GetKnownType("System.Runtime.CompilerServices"u8, "AsyncHelpers"u8);
+            knownTypes.Add(asyncHelpers);
+
+            knownMethods.Add(asyncHelpers.GetKnownMethod("AsyncCallContinuation"u8, null));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("TaskFromException"u8, new MethodSignature(MethodSignatureFlags.Static, 0, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "Task"u8), new TypeDesc[] { exception })));
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: We may want to have some correct-by-construction scheme that guarantees that this list captures all methods used by the thunk IL emitters.

E.g. have an enum for all these methods and make sure that the thunk IL emitters get the method reference via the ID. It is going to guarantee that we do not forget to add the method here as we are changing the emitters.

**Comment by jkotas** [comment]
This is effectively creating an alternative scheme for encoding ReadyToRunHelper (https://github.com/dotnet/runtime/blob/0b9d2ccbd5e2ddbcb95fb8d7126755d160b81f64/src/coreclr/inc/readytorun.h#L307).

I expect that we will use it for encoding higher-level helpers outside async too. For example, it would be fairly natural to use it to encode `READYTORUN_HELPER_GetCurrentManagedThreadId` that is an alias for `Environment.CurrentManagedThreadId` method.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs [hunk 6]
```diff
@@ -436,5 +438,123 @@ public DummyTypeInfo GetTypeFromSpecification(MetadataReader reader, ModuleToken
...
+            knownMethods.Add(asyncHelpers.GetKnownMethod("FinalizeValueTaskReturningThunk"u8, new MethodSignature(MethodSignatureFlags.Static, 0, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "ValueTask"u8), Array.Empty<TypeDesc>())));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("FinalizeTaskReturningThunk"u8, new MethodSignature(MethodSignatureFlags.Static, 1, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "Task`1"u8).MakeInstantiatedType(CompilerContext.GetSignatureVariable(0, method: true)), Array.Empty<TypeDesc>())));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("FinalizeValueTaskReturningThunk"u8, new MethodSignature(MethodSignatureFlags.Static, 1, CompilerContext.SystemModule.GetKnownType("System.Threading.Tasks"u8, "ValueTask`1"u8).MakeInstantiatedType(CompilerContext.GetSignatureVariable(0, method: true)), Array.Empty<TypeDesc>())));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("TransparentAwait"u8, null));
+            knownMethods.Add(asyncHelpers.GetKnownMethod("CompletedTask"u8, null));
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: `CompletedTask` makes sense as a name for a property that returns completed `Task`. It does not make sense as a name for a method that consumes completed task.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs [hunk 7]
```diff
@@ -436,5 +438,123 @@ public DummyTypeInfo GetTypeFromSpecification(MetadataReader reader, ModuleToken
...
+                    Debug.Assert(!default(ModuleToken).Equals(this.GetModuleTokenForType((EcmaType)type, allowDynamicallyCreatedReference: true, throwIfNotFound: true)));
+                }
+
+                foreach (var method in KnownMethods)
+                {
+                    // We can skip methods that are already in the version bubble
+                    if (_compilationModuleGroup.VersionsWithMethodBody((EcmaMethod)method))
+                        continue;
+
+                    EntityHandle ? handle = _manifestMutableModule.TryGetEntityHandle(method);
```
[the remark this answers is not in the document]
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Fixed in 80c0a5b

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs (hunk 4 above)
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Fixed in 80c0a5b

**Comment by jkotas** [comment]
Just curious - what made you switch from the metadata encoding to the encoding via ReadyToRunHelper enum?

**Comment by jtschuster** [comment]
> Just curious - what made you switch from the metadata encoding to the encoding via ReadyToRunHelper enum?

Maybe I misunderstood, but I thought you were recommending this in your other comments.

**Comment by jkotas** [comment]
> Maybe I misunderstood, but I thought you were recommending this in your other comments.

Do you mean this comment https://github.com/dotnet/runtime/pull/121679#issuecomment-3538229885 ?

I was just trying to point out how similar helpers get encoded today. I do not have a strong opinion on whether to use the metadata-based encoding or enum-based encoding for async helpers. Each one has its pros and cons. 

I am sorry if this comment was not clear.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs (hunk 1 above)
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Updated to wait until we try to compile an async thunk to add any necessary references.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs (hunk 5 above)
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Updated the PR to use an enum in AsyncThunks.cs to list all types and methods required by the async thunks.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs (hunk 2 above)
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: This PR still doesn't enable compiling async thunks - do we still need to block this on renames, or can we make those changes separately?

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: I am fine with renaming to wait for a separate PR - as long as we have it tracked somewhere.

File: src/coreclr/tools/Common/TypeSystem/IL/Stubs/AsyncThunks.cs [hunk 8]
```diff
@@ -3,55 +3,379 @@
...
+using Internal.TypeSystem.Ecma;
+using ILCompiler;
+
+#nullable enable
 
 namespace Internal.IL.Stubs
 {
     public static class AsyncThunkILEmitter
     {
+        private enum AsyncHelper
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/IL/Stubs/AsyncThunks.cs]: We should not be building the managed helpers support as async-specific. It should be usable for any situation we need to encode a call to managed method, like `Environment.CurrentManagedThreadId` mentioned in https://github.com/dotnet/runtime/pull/121679#issuecomment-3538229885

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs [hunk 9]
```diff
@@ -778,6 +778,27 @@ public void CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger log
                     return;
                 }
 
+                if (MethodBeingCompiled.IsAsyncThunk())
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs]: If the async thunks are inlined, I believe we can encounter references for the managed helpers in methods that are not async thunks. We should not be limiting this to async thunks.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs [hunk 10]
```diff
@@ -778,6 +778,27 @@ public void CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger log
...
+                        AsyncThunkILEmitter.GetRequiredReferencesForAsyncThunk(((AsyncMethodVariant)MethodBeingCompiled).Target)
+                        : AsyncThunkILEmitter.GetRequiredReferencesForTaskReturningThunk(MethodBeingCompiled);
+                    foreach (var entity in requiredMutableModuleReferences)
+                    {
+                        // If we have a reference to the method/type already, we're okay.
+                        if (_compilation.NodeFactory.ManifestMetadataTable._mutableModule.TryGetExistingEntityHandle(entity) is null)
+                        {
+                            if (logger.IsVerbose)
+                                logger.Writer.WriteLine($"Info: Method `{MethodBeingCompiled}` triggered recompilation.");
+                            _compilation.PrepareForCompilationRetry(_methodCodeNode, null, requiredMutableModuleReferences);
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs]: Why do we need this retry logic? I would expect that we can encode the managed helpers as needed, potentially only after everything is compiled, we should not need to retry the compilation to encode them.

Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs]: To have deterministic compilations there are checks to ensure new tokens are only created during the single-threaded part of the compilation. I think it might be difficult to avoid needing valid ModuleTokens during JIT compilation, but I can look more into it.

Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs]: It looks like a lot of places in the CorInfoImpl assume they can get a valid `ModuleToken` for any `MethodDesc` or `TypeDesc`. We may be able to make `ModuleToken` more opaque and have `ModuleTokens` for `MutableModule` use an opaque handle instead of the actual `mdToken`. Then only allow the `TokenRid` to be accessed after we have sorted the metadata entries in the `MutableModule`. Let me know if that makes sense to you or if you have any other ideas.

cc @dotnet/ilc-contrib

File: src/coreclr/tools/Common/TypeSystem/IL/Stubs/AsyncThunks.cs (hunk 8 above)
Comment (jtschuster) [reply src/coreclr/tools/Common/TypeSystem/IL/Stubs/AsyncThunks.cs]: Moved the helpers code to KnownReferences.cs

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs (hunk 10 above)
Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs]: > have ModuleTokens for MutableModule use an opaque handle instead of the actual mdToken

Sounds reasonable to me.

Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs]: Tried to implement a bunch of different ways to do this and ended up just adding a check during the single-threaded portion to see if any methods being compiled are async thunks, and blocking inlining of async thunks. The existing cross-module inlining support might enable inlining already, but I haven't taken a close look or tested to validate.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs (hunk 9 above)
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs]: Added a check in `canInline` to block async thunks from being inlined to avoid this situation

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs [hunk 11]
```diff
@@ -694,6 +700,46 @@ protected override void ComputeDependencyNodeDependencies(List<DependencyNodeCor
                                 CorInfoImpl.IsMethodCompilable(this, methodCodeNodeNeedingCode.Method))
                                 _methodsWhichNeedMutableILBodies.Add(ecmaMethod);
                         }
+                        if (method.IsAsyncThunk())
+                        {
+                            // The synthetic async thunks require references to methods/types that may not have existing methodRef entries in the version bubble.
+                            // These references need to be added to the mutable module if they don't exist.
+                            var requiredMutableModuleReferences = method.IsAsyncVariant() ?
+                                AsyncThunkILEmitter.GetRequiredReferencesForAsyncThunk(((AsyncMethodVariant)method).Target)
+                                : AsyncThunkILEmitter.GetRequiredReferencesForTaskReturningThunk(method);
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs]: What is the set of methods/types this returns? Would we be able to obtain the same set of types/method by inspecting the IL of `method`?

What I'm getting at is whether we'd be able to leave AsyncThunks.cs as-is and instead here do `ilProvider.GetMethodIL(method)`, construct an `ILReader` over the body, do a for loop over all instructions and extract the dependencies from there. I'm concerned about the readability of AsyncThunks.cs basically.

Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs]: Yes, this should have all the same references as inspecting the method. I went this route for performance and ease of implementation, but creating an ILReader would make AsyncThunks much simpler and probably make this section clearer too.

Comment (MichalStrehovsky) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs]: The approach in your PR is definitely faster than parsing IL, but parsing IL stream is correct by construction. I don't think we need to squeeze out all the throughput from this; I'd go with the correct-by-construction approach if it's an option.

The loop would look similar to this:

https://github.com/dotnet/runtime/blob/55728d4db73366d1f1b276f8e60eb5581163751b/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/FlowAnnotations.cs#L684-L708

except we'd handle call/callvirt/etc (and probably the references from the exception handling info of the MethodIL).

File: src/coreclr/tools/Common/TypeSystem/IL/KnownReferences.cs [hunk 12]
```diff
@@ -0,0 +1,264 @@
...
+        ValueTask_AsTaskOrNotifier,
+        ValueTask_1_AsTaskOrNotifier,
+
+        AsyncHelperCount,
+    }
+
+    public class KnownILStubReferences
+    {
+        /// <summary>
+        /// Extracts all method and type references from the IL of a method.
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/IL/KnownReferences.cs]: If we are doing scanning to be "correct by construction", do we still need the `KnownILStubReference` enum?

Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/TypeSystem/IL/KnownReferences.cs]: I think we should be able to get rid of the enum and leave AsyncThunk.cs as it was before this PR, without the enum indirections.

If we're concerned that someone might modify AsyncThunks.cs and add references to other CoreLib internals that we did not approve as "non-versionable from R2R perspective", we could add a check to `ExtractReferencesFromIL` that checks the reference against an approved whitelist. But I don't think we need an enum for the whitelist, that's just extra indirections. This can just be a big switch block over `method.Name` with some `case "Foo" when ...`.

Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/TypeSystem/IL/KnownReferences.cs]: > This can just be a big switch block over method.Name with some case "Foo" when ....

We could also consider adding an internal attribute to CoreLib - similar to NonVersionableAttribute - that would mark APIs that are okay to generate references to from R2R IL stubs. Then the check for valid APIs could just look for the attribute, no need to duplicate things for the whitelist.

Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/IL/KnownReferences.cs]: I do not think we need a special attribute.

There are number of pre-existing cases in CoreLib where a method is a part of internal public surface that needs to remain stable or requires a special care when versioning. For example, all ForDebugger methods under System.Threading.Tasks like https://github.com/dotnet/runtime/blob/421445ed64461414dc1e99c6716e81e0b1c51b44/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs#L252-L255 . We do not have attribute for those either, comments are good enough.

Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/TypeSystem/IL/KnownReferences.cs]: If there's no concern about what methods the IL stubs can refer to, then we can just remove the enum and the validation around it. I thought we introduced the enum to have a more formal contract around what IL stubs can access.

Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/IL/KnownReferences.cs]: I have commented on this at https://github.com/dotnet/runtime/pull/121679#discussion_r2531563604

The original version of this PR had all method references needed by the async stubs duplicated in ModuleTokenResolver. The enum was introduced to make sure that the async stub emitter and the ModuleTokenResolver stay in sync. We do not have the duplication anymore.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs:1]: This file can move to ILCompiler.ReadyToRun, since the functionality and comments will likely stay R2R specific.

File: src/coreclr/tools/Common/TypeSystem/IL/ILStubReferences.cs [hunk 13]
```diff
@@ -0,0 +1,122 @@
...
+namespace Internal.IL
+{
+    public class ILStubReferences
+    {
+        /// <summary>
+        /// Extracts all method and type references from the IL of a method.
+        /// This is used to find references in synthetic IL (like async thunks) that may need
+        /// to be added to the mutable module.
+        /// </summary>
+        public static List<TypeSystemEntity> GetNecessaryReferencesFromIL(MethodIL methodIL)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/IL/ILStubReferences.cs]: Nit: returning `IEnumerable<TypeSystemEntity>` and `yield return`ing the results would likely be fewer allocations than resizing a list and then throwing it out.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs [hunk 14]
```diff
@@ -0,0 +1,118 @@
...
+        {
+            var references = new List<TypeSystemEntity>();
+            byte[] ilBytes = methodIL.GetILBytes();
+            ILReader reader = new ILReader(ilBytes);
+
+            while (reader.HasNext)
+            {
+                ILOpcode opcode = reader.ReadILOpcode();
+
+                switch (opcode)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs:50]: Do we need this to be complete? This handles many uncommon instructions, but leaves out e.g. instructions that work with fields.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs [hunk 15]
```diff
@@ -0,0 +1,118 @@
...
+            {
+                if (region.Kind == ILExceptionRegionKind.Catch && region.ClassToken != 0)
+                {
+                    object obj = methodIL.GetObject(region.ClassToken, NotFoundBehavior.ReturnNull);
+                    if (obj is TypeDesc type)
+                        references.Add(type);
+                }
+            }
+
+            foreach (var local in methodIL.GetLocals())
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs:364]: If we are looking at locals, do we need to look at the method signature too?

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs [hunk 16]
```diff
@@ -694,6 +700,50 @@ protected override void ComputeDependencyNodeDependencies(List<DependencyNodeCor
...
+                                                Debug.Assert(((CompilerTypeSystemContext)md.Context).GetTargetOfAsyncVariantMethod(md.GetTypicalMethodDefinition()) == method);
+                                                Debug.Assert(!_nodeFactory.Resolver.GetModuleTokenForMethod(method, allowDynamicallyCreatedReference: false, throwIfNotFound: true).IsNull);
+                                            }
+                                            else if (_nodeFactory.Resolver.GetModuleTokenForMethod(md, allowDynamicallyCreatedReference: true, throwIfNotFound: false).IsNull)
+                                            {
+                                                _nodeFactory.ManifestMetadataTable._mutableModule.TryGetEntityHandle(md);
+                                                Debug.Assert(!_nodeFactory.Resolver.GetModuleTokenForMethod(md, allowDynamicallyCreatedReference: true, throwIfNotFound: true).IsNull);
+                                            }
+                                            break;
+                                        case EcmaType td:
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs]: Is it fine that we're ignoring instantiated generic types?

**Review by MichalStrehovsky — APPROVED** [review]
This looks good to me modulo the questions, but ideally someone who knows about `GetModuleTokenForMethod` should have a look too.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs (hunk 14 above)
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs:50]: I don't think we generate any code that references fields, and I don't think the mutable module has a way to add references to fields yet, but it's probably a good idea to make this switch complete to decouple the async thunks and this method.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs (hunk 15 above)
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/ILStubReferences.cs:364]: Yes, I think we should.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs (hunk 2 above)
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ModuleTokenResolver.cs]: Created https://github.com/dotnet/runtime/issues/122512 to track renaming the async helpers.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs (hunk 16 above)
Comment (jtschuster) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs]: Probably not, thanks for pointing that out.

File: src/coreclr/tools/Common/TypeSystem/IL/ILStubReferences.cs (hunk 13 above)
Comment (jtschuster) [reply src/coreclr/tools/Common/TypeSystem/IL/ILStubReferences.cs]: Can't yield return while reading from an ILReader (ref struct), but updated other places to do so.
