### PR TITLE
[mono] [llvm-aot] Fixed storing Vector3 into memory

### LINKED ISSUE #110820: Class `Vector3` field assignation overwrites the next field's contents when using LLVM AOT
_From @jeromelaban on Wed, 18 Dec 2024 15:09:40 GMT_

### Apple platform

iOS, macOS, Mac Catalyst, tvOS

### Framework version

net9.0-*

### Affected platform version

9.0.101

### Description

When a class contains two consecutive `Vector3` fields, setting the value for the first will modify the first inner field (`X`) of the second field.

### Steps to Reproduce

Add the following code to an app, then run, the error message should not happen:

```csharp
public partial class MyTestClass
{
    private Vector3 _offset;
    private Vector3 _scale = new Vector3(1, 1, 1);

    internal static void RunTest()
    {
		var v1 = new MyTestClass();
		System.Console.WriteLine($"Scale: {v1.Scale} Offset: {v1.Offset} Scale: {v1.Scale}");

		var v2 = new MyTestClass() { Offset = new(1.1f, 1.1f, 5.0f) };
		System.Console.WriteLine($"Scale: {v2.Scale} Offset: {v2.Offset} Scale: {v2.Scale}");

		if(v2.Scale != new Vector3(1, 1, 1))
                {
			System.Console.WriteLine("Error: Scale is not 1, 1, 1");
                }
    }

    public Vector3 Offset
    {
        get => _offset;
        set
        {
            System.Console.WriteLine($"Before Offset: {Offset} Scale: {Scale}");

            _offset = value;

            System.Console.WriteLine($"After Offset: {Offset} Scale: {Scale}");
        }
    }

    public Vector3 Scale => _scale;
}
```

Repro project: [21825-iosllvmissue.zip](https://github.com/user-attachments/files/18184544/21825-iosllvmissue.zip)

### Did you find any workaround?

Adding a field of another type in between _seems_ to works around the issue.

### Relevant logs

_No response_

_Copied from original issue xamarin/xamarin-macios#21825_

### PR DESCRIPTION
**Pull request by jkurdek**
Fixes https://github.com/dotnet/runtime/issues/110820

Vector3 is sometimes handled as Vector4 (Vector3 + 0) for perf purposes. On mono llvm aot it was incorrectly stored into memory with the trailing 0. This change fixes that behaviour.

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

File: src/mono/mono/mini/mini-llvm.c [hunk 1]
```diff
@@ -8433,7 +8433,21 @@ MONO_RESTORE_WARNING
...
+			if (mono_class_value_size (ins->klass, NULL) == 12) {
+				const int mask_values [] = { 0, 1, 2 };
+
+				LLVMValueRef truncatedVec3 = LLVMBuildShuffleVector (
+					builder,
+					lhs,
+					LLVMGetUndef (t),
+					create_const_vector_i32 (mask_values, 3),
+					"truncated_vec3"
+				);
```
Comment (matouskozak) [inline src/mono/mono/mini/mini-llvm.c:8445]: Couldn't this be replaced by something like?
```
LLVMValueRef truncatedVec3 = LLVMBuildTrunc (builder, lhs, LLVMVectorType (LLVMFloatType (), 3), "truncated_vec3);
```

However, I haven't tried it locally so I'm unsure whether it would make the same and be more efficient or not.

File: src/mono/mono/mini/mini-llvm.c [hunk 2]
```diff
@@ -8433,7 +8433,21 @@ MONO_RESTORE_WARNING
 			LLVMValueRef dest;
 
 			dest = convert (ctx, LLVMBuildAdd (builder, convert (ctx, values [ins->inst_destbasereg], IntPtrType ()), LLVMConstInt (IntPtrType (), ins->inst_offset, FALSE), ""), pointer_type (t));
-			mono_llvm_build_aligned_store (builder, lhs, dest, FALSE, 1);
+			if (mono_class_value_size (ins->klass, NULL) == 12) {
```
Comment (matouskozak) [inline src/mono/mono/mini/mini-llvm.c:8436]: Why do we use expect that if we encounter a value type with size 12, it must be a Vector3? 
Couldn't there be a value type with size 12 that is just a plain struct, thus shouldn't be handled as a vector.

This comment is not directly related to this PR as we are using the `mono_class_value_size (ins->klass, NULL) == 12` elsewhere as well for the same check, so it is probably correct. I'm just trying to understand the logic behind.

**Review by matouskozak — APPROVED** [review]
LGTM! I put down a few comments out of curiosity so feel free to merge.

btw. nice PR number 111000

File: src/mono/mono/mini/mini-llvm.c (hunk 2 above)
Comment (jkurdek) [reply src/mono/mono/mini/mini-llvm.c:8436]: I think we only use this check in op codes dealing with SIMD vectors. When there is an ambiguity there is also an `mini_class_is_simd` check before. I agree this can be made better, but I would do this in separate PR.

Comment (matouskozak) [reply src/mono/mono/mini/mini-llvm.c:8436]: Ah right, that makes sense. I wouldn't even propose to change it, I was just getting curious :)

File: src/mono/mono/mini/mini-llvm.c (hunk 1 above)
Comment (jkurdek) [reply src/mono/mono/mini/mini-llvm.c:8445]: I think the trunc instruction does something different. Looking at the LLVM reference it seems to be casting each element of a vector to a different type - not casting a vector and dropping its last element.

Comment (matouskozak) [reply src/mono/mono/mini/mini-llvm.c:8445]: I see, I thought it works the same as on primitives. Thank you for the explanation.

File: src/mono/mono/mini/mini-llvm.c [hunk 3]
```diff
@@ -8433,7 +8433,21 @@ MONO_RESTORE_WARNING
...
+
+				LLVMValueRef truncatedVec3 = LLVMBuildShuffleVector (
+					builder,
+					lhs,
+					LLVMGetUndef (t),
+					create_const_vector_i32 (mask_values, 3),
+					"truncated_vec3"
+				);
+
+				mono_llvm_build_aligned_store (builder, truncatedVec3, dest, FALSE, 1);
```
Comment (tannergooding) [inline src/mono/mono/mini/mini-llvm.c:8447]: Why is the alignment being set to `1`? A `Vector3` is composed of `3x float` fields and so is presumed to be 4 byte aligned unless the code is explicitly using something like `Unsafe.ReadUnaligned` or `Unsafe.WriteUnaligned` (which use the IL `unaligned. ` prefix).

File: src/mono/mono/mini/mini-llvm.c [hunk 4]
```diff
@@ -8433,7 +8433,21 @@ MONO_RESTORE_WARNING
 			LLVMValueRef dest;
 
 			dest = convert (ctx, LLVMBuildAdd (builder, convert (ctx, values [ins->inst_destbasereg], IntPtrType ()), LLVMConstInt (IntPtrType (), ins->inst_offset, FALSE), ""), pointer_type (t));
-			mono_llvm_build_aligned_store (builder, lhs, dest, FALSE, 1);
+			if (mono_class_value_size (ins->klass, NULL) == 12) {
+				const int mask_values [] = { 0, 1, 2 };
+
+				LLVMValueRef truncatedVec3 = LLVMBuildShuffleVector (
```
Comment (tannergooding) [inline src/mono/mono/mini/mini-llvm.c:8439]: Why are we using `ShuffleVector` here?

In other places, we instead do this via doing `LLVMBuildExtractElement` + `LLVMBuildInsertValue` (or Store) 3x. This alternative correctly represents the primitive steps and allows LLVM to optimize it as best fit for the underlying architecture.

File: src/mono/mono/mini/mini-llvm.c (hunk 3 above)
Comment (jkurdek) [reply src/mono/mono/mini/mini-llvm.c:8447]: This change reuses existing logic. This code path was previously taken for all `VectorX` writes so I kept it consistent. I agree that this might be incorrect. We should investigate this separately.
