### PR TITLE
Fix non-deterministic trigger of struct type initializers

### LINKED ISSUE #100466: The type initializer sometimes doesn't execute for an empty struct
### Description

The type initializer sometimes doesn't execute for an empty struct, and the behavior is not consistent across different platforms + configurations. 

### Reproduction Steps

Repro:

```cs
var foo = new Foo<Bar>();
Console.WriteLine(foo.ToString());
Console.WriteLine(Bar.X);

struct Foo<T> where T : IBar
{
    static Foo()
    {
        T.Set();
    }
}

struct Bar : IBar
{
    public static int X;
    public static void Set()
    {
        X = 42;
    }
}

interface IBar
{
    abstract static void Set();
}
```

Note that the line `foo.ToString()` does an invocation to the virtual method. So according to ECMA:

```
If not marked BeforeFieldInit then that type’s initializer method is executed at
...
- first invocation of any instance or virtual method of that type if it is a value type
```

BTW the abstract static method and generic here is not necessary for the repro, the below code also reproduces this issue:

```cs
var foo = new Foo();
Console.WriteLine(foo.ToString());
Console.WriteLine(Bar.X);

struct Foo
{
    static Foo()
    {
        Bar.Set();
    }
}

struct Bar
{
    public static int X;
    public static void Set()
    {
        X = 42;
    }
}
```

### Expected behavior

Always prints
```
Foo`1[Bar]
42
```

### Actual behavior

The output from `Bar.X`:

| Platform | Configuration | TieredCompilation | Output |
| -- | -- | -- | -- |
| win-x64 | Debug | N/A | `0` |
| win-x64 | Release | true | `0` |
| win-x64 | Release | false | `0` |
| linux-x64 | Debug | N/A | `42` |
| linux-x64 | Release | true | `42` |
| linux-x64 | Release | false | `0` |
| linux-arm64 | Debug | N/A | `42` |
| linux-arm64 | Release | true | `42` |
| linux-arm64 | Release | false | `0` |
| osx-arm64 | Debug | N/A | `42` |
| osx-arm64 | Release | true | `42` |
| osx-arm64 | Release | false | `0` |

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #100466

### CODE REVIEW

**Comment by jkotas** [comment]
cc @dotnet/jit-contrib

File: src/coreclr/vm/methodtable.cpp [hunk 1]
```diff
@@ -4963,7 +4963,10 @@ OBJECTREF MethodTable::FastBox(void** data)
     if (IsNullable())
         return Nullable::Box(*data, this);
 
-    OBJECTREF ref = Allocate();
+    // Allocate without triggering cctors - boxing should not trigger cctors
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/methodtable.cpp:4966]:
```suggestion
    // MethodTable::Allocate() triggers cctors, so to avoid that we
    // allocate directly without triggering cctors - boxing should not trigger cctors.
```

File: src/coreclr/vm/object.cpp [hunk 2]
```diff
@@ -1636,7 +1636,11 @@ OBJECTREF Nullable::Box(void* srcPtr, MethodTable* nullableMT)
     OBJECTREF obj = 0;
     GCPROTECT_BEGININTERIOR (src);
     MethodTable* argMT = nullableMT->GetInstantiation()[0].AsMethodTable();
-    obj = argMT->Allocate();
+
+    // Allocate without triggering cctors - boxing should not trigger cctors
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/object.cpp:1640]:
```suggestion
    // MethodTable::Allocate() triggers cctors, so to avoid that we
    // allocate directly without triggering cctors - boxing should not trigger cctors.
```

File: src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+
+    private static bool s_cctorTriggered;
+    private static bool s_cctorTriggeredNullable;
+
+    private struct Foo
+    {
+        static Foo() => s_cctorTriggered = true;
+    }
+
+    private struct FooNullable
```
Comment (AaronRobinsonMSFT) [inline src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs:33]: Are `ref struct` types unique enough to warrant an added case here?

File: src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs [hunk 4]
```diff
@@ -0,0 +1,37 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System;
+using Xunit;
+
+public static class Runtime_100466
```
Comment (AaronRobinsonMSFT) [inline src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs:7]: Nit: I realize this is annoying, but I think this sort of test should possibly be under `runtime/src/tests/Loader`. It can also be named something like `StaticTypeInitialization`, which would be clearer. I'm also fine with it not being renamed, but the location under `Loader` does seem more appropriate.

Comment (am11) [reply src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs:7]: > `StaticTypeInitialization`

Perhaps `StaticValueTypeInitialization` to be more specific?

**Comment by AaronRobinsonMSFT** [comment]
Regardless of the test location resolution, the CI is green and the changes look good. One thing that might be worth thinking about are the ByRefLike boxing optimization tests that were written for the generics scenarios. I'm thinking about this from the perspective of cross-cutting boxing behavior we are expecting.

https://github.com/dotnet/runtime/blob/1949bd2e017a0dc1e48b7cfed263051a6ed147a5/src/tests/Loader/classloader/generics/ByRefLike/Validate.cs#L48-L56

File: src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs (hunk 4 above)
Comment (jkotas) [reply src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs:7]: I do not think about this issue as a classloader bug.

This bug was in the implementation of boxing. Boxing implementation had a superfluous cctor trigger on one path that made it do more than what it was supposed to in some cases. Boxing is a JIT-centric concept - the basic tests are under https://github.com/dotnet/runtime/tree/main/src/tests/JIT/Methodical/Boxing.

The bug intersects with cctor triggers. Cctor triggers are JIT-centric concept too - the basic tests are under https://github.com/dotnet/runtime/tree/main/src/tests/JIT/Methodical/cctor.

The bug is not in the type initialization management, like the logic that caches exceptions thrown by cctors or that breaks cycles between cctors. Type initialization management would be classloader - the basic tests are under https://github.com/dotnet/runtime/tree/main/src/tests/Loader/classloader/TypeInitialization.

The intersection of JIT/Methodical/Boxing and JIT/Methodical/cctor gives JIT/Regressions.

This is my though process for the current location, but I do not have a strong opinion about it. I am happy to move it if you tell me where you would like to see it moved to exactly.

File: src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs (hunk 3 above)
Comment (jkotas) [reply src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs:33]: The two cases in the PR provide full code coverage for the two interesting cases in the current implementation. The path taken by `ref struct`s wrt cctors is covered by the non-ref struct test cases.

It is hard to predict future interesting cases that may be introduced. If somebody changes the implementation to introduce more interesting cases in future, I hope that will do due diligence and add test coverage for it.

File: src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs (hunk 4 above)
Comment (AaronRobinsonMSFT) [reply src/tests/JIT/Regression/JitBlue/Runtime_100466/Runtime_100466.cs:7]: Okay, that makes sense.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Review by EgorBo — APPROVED** [review]
