### PR TITLE
[wasm][debugger] Do not run the test with justMyCode enabled in debug mode.

### LINKED ISSUE #86387: [wasm][debugger] KeepNativeSymbols=true breaks SteppingTests.SkipWasmFunctionsAccordinglyJustMyCode
If you build a runtime with `-p:KeepNativeSymbols=true` and then run the debugger testsuite, `SteppingTests.SkipWasmFunctionsAccordinglyJustMyCode` will fail.

Note that we don't ship `KeepNativeSymbols`, so this is purely something that is a papercut when working on dotnet/runtime itself.

Repro steps:
```
./build.sh --os browser -c Debug -bl -nr:false -p:KeepNativeSymbols=true
```

then

```
make -C src/mono/wasm run-debugger-tests CONFIG=Debug TEST_FILTER='~SteppingTests.SkipWasmFunctionsAccordinglyJustMyCode'
```

### PR DESCRIPTION
**Pull request by thaystg**
The callstack is different in debug mode, this is expected.
Fixes https://github.com/dotnet/runtime/issues/86387

### CODE REVIEW

File: src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs [hunk 1]
```diff
@@ -1237,8 +1237,8 @@ public async Task SkipWasmFunctionsAccordinglyJustMyCode(bool justMyCode)
                 Assert.False(pause_location["callFrames"].Value<JArray>().Any(f => f?["scopeChain"]?[0]?["type"]?.Value<string>()?.Equals("wasm-expression-stack") == true));
             else
                 Assert.True(pause_location["callFrames"].Value<JArray>().Any(f => f?["scopeChain"]?[0]?["type"]?.Value<string>()?.Equals("wasm-expression-stack") == true));
-            if (justMyCode)
-                await StepAndCheck(StepKind.Out, "dotnet://debugger-test.dll/debugger-test.cs", 10, 8, "Math.IntAdd", times: 4);
+            if (justMyCode && ReleaseRuntime)
+                    await StepAndCheck(StepKind.Out, "dotnet://debugger-test.dll/debugger-test.cs", 10, 8, "Math.IntAdd", times: 4);
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:1241]:
```suggestion
                await StepAndCheck(StepKind.Out, "dotnet://debugger-test.dll/debugger-test.cs", 10, 8, "Math.IntAdd", times: 4);
```

**Review by radical — APPROVED** [review]
