### PR TITLE
Fix new EH hang on DebugBreak

### LINKED ISSUE #112599: FATAL_GC_ERROR produces hard to diagnose hangs or crashes
The crashes caused by FATAL_GC_ERROR are very hard to diagnose. I helped somebody to diagnose one of these and it took more than a day to find out what's causing the problem.
  
### Repro

1. Add unconditional `FATAL_GC_ERROR();` to `gc_heap::verify_free_lists`
2. set `DOTNET_HeapVerify=1`
3. Run a simple test that just calls GC.Collect on x64 checked runtime

### Actual behavior

This is one of the possible failure modes. I have also seen other asserts or hangs with mode complex tests.
```
Assert failure(PID 24832 [0x00006100], Thread: 16656 [0x4110]): unbreakableLockCount == m_pThread->GetUnbreakableLockCount() || (!m_pThread->HasUnbreakableLock() && !m_pThread->HasThreadStateNC(Thread::TSNC_OwnsSpinLock))

CORECLR! FCallCheck::~FCallCheck + 0x40 (0x00007ffa`68c11370)
CORECLR! CallSettingFrameEncoded + 0x2A (0x00007ffa`69185c8a)
CORECLR! _FrameHandler4::FrameUnwindToState + 0x28E (0x00007ffa`691844ce)
CORECLR! _FrameHandler4::FrameUnwindToEmptyState + 0x4B (0x00007ffa`6917c1eb)
CORECLR! _InternalCxxFrameHandler<__FrameHandler4> + 0x283 (0x00007ffa`691829c3)
CORECLR! _InternalCxxFrameHandlerWrapper<__FrameHandler4> + 0x6A (0x00007ffa`69182cba)
CORECLR! _CxxFrameHandler4 + 0xFB (0x00007ffa`6917d04b)
CORECLR! _GSHandlerCheck_EH4 + 0x90 (0x00007ffa`69179070)
NTDLL! chkstk + 0x11F (0x00007ffb`04a43f8f)
NTDLL! RtlUnwindEx + 0x352 (0x00007ffb`048f4d22)
    File: C:\runtime\src\coreclr\vm\fcall.cpp:196
    Image: C:\runtime\artifacts\bin\coreclr\windows.x64.Checked\corerun.exe
```

### Expected behavior

Error message that suggests fatal GC error. No hangs or crashes.

### PR DESCRIPTION
**Pull request by janvorli**
The new exception handling doesn't work well with the DebugBreak in some cases. E.g. when it is invoked from FATAL_GC_ERROR. The new EH attempts to handle the STATUS_BREAKPOINT stemming from the DebugBreak, allocate a managed exception object and hangs since it cannot do that when the GC is running.

The cause is a missing check for the breakpoint exception in the ProcessCLRExceptionNew that is present in the old ProcessCLRException. To fix it, I've copied that code to the ProcessCLRExceptionNew.

Close #112599

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas I've also found that the presence of the DebugBreak in the FATAL_GC_ERROR prevents the following assert to occur, since the process exits on the DebugBreak. The same happens with the legacy EH. So it might make sense to remove this DebugBreak from the FATAL_GC_ERROR.

**Comment by jkotas** [comment]
> Close https://github.com/dotnet/runtime/issues/112599

Is this actually fixing the problem with debug breaks in the GC? If I am reading the code correctly, `fExternalException` is going to be false for debug break in (non-standalone) GC and we take the same path as before.

(I understand that this change makes the new EH same as the legacy EH.) 

> it might make sense to remove this DebugBreak from the FATAL_GC_ERROR.

IIRC, I wanted to do that at one point, but @Maoni0 wanted to keep it since it makes GC crashes more diagnosable. Calling the fatal error handler overwrites values of volatile registers they may contain important clues for the diagnosing the crash.

I think we should make sure that the behavior of breakpoint instructions that are statically compiled into coreclr.dll is reasonable without debugger attached. GC is not the only place where we have them. 

Would it make sense to intercept the breakpoint exceptions only when `CORDebuggerAttached` is true?

**Comment by janvorli** [comment]
> Is this actually fixing the problem with debug breaks in the GC?

Yes, it is. The instruction that triggers the STATUS_BREAKPOINT is in the DebugBreak() that is in the kernel32.dll, so it is evaluated as external. Only if we had the breakpoint instruction directly in coreclr.dll, it would be evaluated as internal.

**Comment by janvorli** [comment]
> Would it make sense to intercept the breakpoint exceptions only when `CORDebuggerAttached` is true?

Maybe, let me see how it would behave

**Review by jkotas — APPROVED** [review]
> The instruction that triggers the STATUS_BREAKPOINT is in the DebugBreak() that is in the kernel32.dll, so it is evaluated as external. 

Ah ok, I have realized that.

> CORDebuggerAttached

BTW: The managed debuggers should not need to intercept breakpoints in the native runtime once we complete the cleanup of place where we depend on it today (it breaks managed debugging on macOS Arm64 - it is not possible to set breakpoints in statically compiled code on macOS Arm64 unless you are a proper out-of-proc debugger that managed debuggers are not). https://github.com/dotnet/runtime/pull/110677 may be the last remaining change to finish this cleanup.

**Comment by janvorli** [comment]
Actually, thinking about it more, does it even make sense to handle the breakpoint using the managed exception handling code at all? It doesn't seem so. So I've tried to just return ExceptionContinueSearch when STATUS_BREAKPOINT or STATUS_SINGLE_STEP are encountered without checking for where it came from. The dotnet-diagnostictests EH tests are passing fine with it that way.

**Comment by jkotas** [comment]
That sounds even better.

File: src/coreclr/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -946,6 +946,17 @@ ProcessCLRExceptionNew(IN     PEXCEPTION_RECORD   pExceptionRecord,
 #ifndef HOST_UNIX
     if (!(pExceptionRecord->ExceptionFlags & EXCEPTION_UNWINDING))
     {
+        // If the exception is a breakpoint, but outside of the runtime or managed code,
+        //  let it go.  It is not ours, so someone else will handle it, or we'll see
+        //  it again as an unhandled exception.
```
Comment (jkotas) [inline src/coreclr/vm/exceptionhandling.cpp:951]: Is this comment correct? I do not think we know that the breakpoint is outside of the runtime or managed code.

Comment (janvorli) [reply src/coreclr/vm/exceptionhandling.cpp:951]: Oops, forgotten to remove this comment together with the other stuff.

**Review by jkotas — APPROVED** [review]
Thank you!
