### PR TITLE
[mono][interp] Fix a few local store warnings

### LINKED ISSUE #65881: [wasm] Interpreter: Local variable of function pointer type emits a warning `Test.Prepare: Store local stack type mismatch 0 7`
Warning `Test.Prepare: Store local stack type mismatch 0 7` from https://github.com/dotnet/runtime/blob/30f30a3e5b6be09eacf7ea4cf054576753ed99ca/src/mono/mono/mini/interp/transform.c#L1073-L1075

1. Put this code in `src/mono/sample/wasm/console-v8-cjs/Program.cs`

```csharp
using System;
using System.Threading.Tasks;

public class Test
{
    public static async Task<int> Main(string[] args)
    {
        await Task.Delay(1);
        Prepare();
        return 0;
    }

    public unsafe static int Prepare()
    {
        delegate*<int> value = &Prepare;
        Console.WriteLine ($"value is {value == null}");
        return 5;
    }
}
```

2. build: `make build MSBUILD_ARGS="-p:TreatWarningsAsErrors=false"`
3. make run

Output:
```
console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[MONO] Test.Prepare: Store local stack type mismatch 0 7
value is False
```

IIUC, https://github.com/dotnet/runtime/blob/30f30a3e5b6be09eacf7ea4cf054576753ed99ca/src/mono/mono/mini/interp/transform.c#L943-L951

.. this needs to map `STACK_TYPE_F` to `STACK_TYPE_I` too.

cc @lambdageek @BrzVlad

### PR DESCRIPTION
**Pull request by BrzVlad**
Fixes https://github.com/dotnet/runtime/issues/65881

### CODE REVIEW

**Review by lewing — APPROVED** [review]

File: src/mono/mono/mini/interp/transform.c [hunk 1]
```diff
@@ -908,9 +908,9 @@ shift_op(TransformData *td, int mint_op)
 static int
 can_store (int st_value, int vt_value)
 {
-	if (st_value == STACK_TYPE_O || st_value == STACK_TYPE_MP)
+	if (st_value == STACK_TYPE_O || st_value == STACK_TYPE_MP || st_value == STACK_TYPE_F)
 		st_value = STACK_TYPE_I;
-	if (vt_value == STACK_TYPE_O || vt_value == STACK_TYPE_MP)
+	if (vt_value == STACK_TYPE_O || vt_value == STACK_TYPE_MP || st_value == STACK_TYPE_F)
```
Comment (radical) [inline src/mono/mono/mini/interp/transform.c:913]: Should this be checking vt_value and not st_value?

**Review by vargaz — APPROVED** [review]
