### PR TITLE
Arm64 SVE: Fix conditionalselect with constant arguments

### LINKED ISSUE #116847: Arm64 SVE: Error when ConditionalSelect has all constant arguments
```c#
    static Vector<int> ConditionalSelect1CC()
    {
        return Sve.ConditionalSelect(
            Sve.CreateTrueMaskInt32(SveMaskPattern.VectorCount1),
            Vector.Create<int>(3),
            Vector.Create<int>(4)
        );
    }
```

```
Assert failure(PID 1207671 [0x00126d77], Thread: 1207671 [0x126d77]): Assertion failed 'OperIs(GT_CNS_VEC)' in 'ConditionalSelectConstants:ConditionalSelect1CC():System.Numerics.Vector`1[int]' during 'Morph - Global' (IL size 24; hash 0x36e039d8; FullOpts)

    File: /mnt/sdb/home/alahay01/dotnet/runtime_sve/src/coreclr/jit/gtstructs.h:64
    Image: /mnt/sdb/home/alahay01/dotnet/runtime_sve/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun
```

This is because since #115566 the mask in arg is imported as a constant mask. This now triggers the constant folding in `gtFoldExprHWIntrinsic()`.

### PR DESCRIPTION
**Pull request by a74nh**
Fixes #116847

When folding, allow arg1 to be a constant mask

### CODE REVIEW

**Comment by a74nh** [comment]
@dotnet/arm64-contrib @kunalspathak

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -18608,6 +18608,84 @@ void GenTreeVecCon::EvaluateBinaryInPlace(genTreeOps oper, bool scalar, var_type
...
+            EvaluateSimdCvtMaskToVector<simd16_t>(baseType, &otherSimdVal, other->gtSimdMaskVal);
+
+            simd16_t result = {};
+            EvaluateBinarySimd<simd16_t>(oper, scalar, baseType, &result, gtSimd16Val, otherSimdVal);
+            gtSimd16Val = result;
+            break;
+        }
+
+#if defined(TARGET_XARCH)
+        case TYP_SIMD32:
```
Comment (kunalspathak) [inline src/coreclr/jit/gentree.cpp]: so we are just adding this even though xarch is not exercising this path?

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -18608,6 +18608,84 @@ void GenTreeVecCon::EvaluateBinaryInPlace(genTreeOps oper, bool scalar, var_type
...
+//    oper     - the operation to use in the evaluation
+//    scalar   - true if this is a scalar operation; otherwise, false
+//    baseType - the base type of the constant being checked
+//    other    - the mask constant to use in the evaluation
+//
+void GenTreeVecCon::EvaluateBinaryInPlace(genTreeOps oper, bool scalar, var_types baseType, GenTreeMskCon* other)
+{
+    switch (gtType)
+    {
+        case TYP_SIMD8:
```
Comment (kunalspathak) [inline src/coreclr/jit/gentree.cpp]: I don't see why we would come in `TYP_SIMD8` and `TYP_SIMD16` for Mask constants?

File: src/coreclr/jit/simd.h [hunk 3]
```diff
@@ -1993,6 +1993,104 @@ SveMaskPattern EvaluateSimdMaskToPattern(var_types baseType, simdmask_t arg0)
...
+    {
+        TBase input0;
+        memcpy(&input0, &arg0.u8[i * sizeof(TBase)], sizeof(TBase));
+
+        // For Arm64 we have count total bits to read, but
+        // they are sizeof(TBase) bits apart. We set
+        // depending on if the corresponding input element
+        // has its least significant bit set
+
+        bool isSet = static_cast<uint64_t>(1) << (i * sizeof(TBase));
```
Comment (kunalspathak) [inline src/coreclr/jit/simd.h]: wait, we should be check `isSet` with content of `input0`, right?

File: src/coreclr/jit/simd.h [hunk 4]
```diff
@@ -1993,6 +1993,104 @@ SveMaskPattern EvaluateSimdMaskToPattern(var_types baseType, simdmask_t arg0)
...
+
+    // Find an unbroken sequence of 0s.
+    for (uint32_t i = finalOne; i < count; i++)
+    {
+        // For Arm64 we have count total bits to read, but
+        // they are sizeof(TBase) bits apart. We set
+        // depending on if the corresponding input element
+        // has its least significant bit set
+
+        bool isSet = static_cast<uint64_t>(1) << (i * sizeof(TBase));
```
Comment (kunalspathak) [inline src/coreclr/jit/simd.h]: same here

**Review by kunalspathak — CHANGES_REQUESTED** [review]
There is a bug in `EvaluateSimdVectorToPattern` where we are not validating it against the contents of `arg0`.

File: src/coreclr/jit/gentree.cpp (hunk 2 above)
Comment (a74nh) [reply src/coreclr/jit/gentree.cpp]: I was making the function target agnostic to match the other version of `EvaluateBinaryInPlace()` above it. Happy to remove everything except `TYP_SIMD16` if it's also marked as `TARGET_ARM64` only.

File: src/coreclr/jit/simd.h (hunk 3 above)
Comment (a74nh) [reply src/coreclr/jit/simd.h]: > wait, we should be check `isSet` with content of `input0`, right?

Yes, I should be checking significant bit of `input0`

**Comment by a74nh** [comment]
The simd.h changes in this PR are out of date. We should wait for #116854 to be merged first.

**Comment by kunalspathak** [comment]
i will hold off reviewing this until https://github.com/dotnet/runtime/pull/116854 is merged.

**Comment by a74nh** [comment]
Fuzzlyn was showing some errors with 

```
Assert failure(PID 1845356 [0x001c286c], Thread: 1845356 [0x1c286c]): Assertion failed 'OperIs(GT_CNS_VEC)' in 'Program:M1(byref,int,System.Runtime.Intrinsics.Vector64`1[ushort]):ushort' during 'Morph - Global' (IL size 56; hash 0xc2f1cf02; FullOpts)

    File: /mnt/sdb/home/alahay01/dotnet/runtime_madv/src/coreclr/jit/gtstructs.h:64
    Image: /mnt/sdb/home/alahay01/dotnet/runtime_madv/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun
```

This is due to `EvalHWIntrinsicFunTernary()` not treating arg1 of NI_Sve_ConditionalSelect` as a mask.

The fix is closely related to the fix in this PR, so I've put it into this PR with a test.


I've also updated simd.h to the latest from https://github.com/dotnet/runtime/pull/116854

File: src/coreclr/jit/simd.h [hunk 5]
```diff
@@ -1598,35 +1598,33 @@ void EvaluateSimdCvtVectorToMask(simdmask_t* result, TSimd arg0)
...
 #elif defined(TARGET_ARM64)
-            // For Arm64 we have count total bits to write, but
-            // they are sizeof(TBase) bits apart. We set
-            // depending on if the corresponding input element
-            // has its least significant bit set
-
+        // For Arm64 we have count total bits to write, but they are sizeof(TBase)
+        // bits apart. We set depending on if the corresponding input element has
+        // any bit set (this matches the use of cmpne in outputted assembly).
+        if (input0 != 0)
```
Comment (kunalspathak) [inline src/coreclr/jit/simd.h:1620]: we need to change this to test LSB instead, as discussed offline

File: src/coreclr/jit/simd.h [hunk 6]
```diff
@@ -1993,6 +1991,101 @@ SveMaskPattern EvaluateSimdMaskToPattern(var_types baseType, simdmask_t arg0)
...
+    // depending on if the corresponding input element has any bit set (this matches the use
+    // of cmpne in outputted assembly)
+
+    // Find an unbroken sequence of 1s.
+    for (uint32_t i = 0; i < count; i++)
+    {
+        TBase input0;
+        memcpy(&input0, &arg0.u8[i * sizeof(TBase)], sizeof(TBase));
+
+        bool isSet = input0 != 0;
```
Comment (kunalspathak) [inline src/coreclr/jit/simd.h]: >input0 != 0; [](http://example.com/codeflow?start=21&length=12)

change this to test LSB

File: src/coreclr/jit/simd.h (hunk 5 above)
Comment (a74nh) [reply src/coreclr/jit/simd.h:1620]: > we need to change this to test LSB instead, as discussed offline

Done - reverted to older version. Same with comment below.

File: src/coreclr/jit/simd.h [hunk 7]
```diff
@@ -1993,6 +1993,102 @@ SveMaskPattern EvaluateSimdMaskToPattern(var_types baseType, simdmask_t arg0)
...
     }
 }
+
+template <typename TSimd, typename TBase>
+SveMaskPattern EvaluateSimdVectorToPattern(TSimd arg0)
+{
+    uint32_t count    = sizeof(TSimd) / sizeof(TBase);
+    uint32_t finalOne = count;
+
+    TBase significantBit = 1;
```
Comment (kunalspathak) [inline src/coreclr/jit/simd.h]:
```suggestion
    TBase leastSignificantBit = 1;
```

**Review by kunalspathak — APPROVED** [review]
LGTM

File: src/coreclr/jit/simd.h [hunk 8]
```diff
@@ -1993,6 +1993,102 @@ SveMaskPattern EvaluateSimdMaskToPattern(var_types baseType, simdmask_t arg0)
         }
     }
 }
+
+template <typename TSimd, typename TBase>
+SveMaskPattern EvaluateSimdVectorToPattern(TSimd arg0)
```
Comment (kunalspathak) [inline src/coreclr/jit/simd.h]: curious, i don't see any usage of this method...am i missing something?

Comment (a74nh) [reply src/coreclr/jit/simd.h]: > curious, i don't see any usage of this method...am i missing something?

Removed

**Comment by a74nh** [comment]
I've put another closely related Fuzzlyn failure into this PR.

```
Assert failure(PID 3199223 [0x0030d0f7], Thread: 3199223 [0x30d0f7]): Assertion failed 'unreached' in 'ConditionalSelectConstants:ConditionalSelectConstsNoMaskPattern():bool' during 'Generate code' (IL size 74; hash 0xca97730c; FullOpts)

    File: /mnt/sdb/home/alahay01/dotnet/runtime_sve/src/coreclr/jit/codegenarm64.cpp:2379
    Image: /mnt/sdb/home/alahay01/dotnet/runtime_sve/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun
```

What happens here is all the inputs to the conditionalselect are constants, so it is optimised away into a single vector. It is then used as a mask in the next function call, so is optimised to a cns mask. The mask cannot be converted into a valid pattern during codegen (for use in a ptrue), so it asserts. The fix is to convert it to a constant vector with conversion to mask. Best way to do that is during lowering (see `LowerCnsMask()`), this ensures we have the registers etc required for the conversion.

**Comment by a74nh** [comment]
With #116991 applied on top I don't see any fuzzlyn errors over 50mins. I'm happy with this PR now.

File: src/coreclr/jit/compiler.h [hunk 9]
```diff
@@ -3205,7 +3205,7 @@ class Compiler
                                     unsigned    simdSize);
 
 #if defined(FEATURE_MASKED_HW_INTRINSICS)
-    GenTree* gtNewSimdCvtVectorToMaskNode(var_types type, GenTree* op1, CorInfoType simdBaseJitType, unsigned simdSize);
+    GenTreeHWIntrinsic* gtNewSimdCvtVectorToMaskNode(var_types type, GenTree* op1, CorInfoType simdBaseJitType, unsigned simdSize);
```
Comment (tannergooding) [inline src/coreclr/jit/compiler.h]: nit: We generally don't guarantee a return type from these to allow for flexibility over time, like returning constants.

It's expected the consumer validate the type of the node returned instead

File: src/coreclr/jit/gentree.cpp [hunk 10]
```diff
@@ -32838,12 +32862,26 @@ GenTree* Compiler::gtFoldExprHWIntrinsic(GenTreeHWIntrinsic* tree)
 
                 if (op2->IsCnsVec() && op3->IsCnsVec())
                 {
-                    // op2 = op2 & op1
-                    op2->AsVecCon()->EvaluateBinaryInPlace(GT_AND, false, simdBaseType, op1->AsVecCon());
+                    if (op1->IsCnsVec())
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp]: Can we move the `Sve_ConditionalSelect` logic to its own path, to help make it clear that the other intrinsics are explicitly expecting vectors and Sve is explicitly expecting a mask?

It should help avoid unnecessary checks between the two paths, even if they're similar.

File: src/coreclr/jit/gentree.cpp [hunk 11]
```diff
@@ -18608,6 +18608,30 @@ void GenTreeVecCon::EvaluateBinaryInPlace(genTreeOps oper, bool scalar, var_type
...
+// GenTreeVecCon::EvaluateUnaryInPlace: Evaluates this constant using the given operation, when the other
+//                                      operand is a constant mask
+//
+// Arguments:
+//    oper     - the operation to use in the evaluation
+//    scalar   - true if this is a scalar operation; otherwise, false
+//    baseType - the base type of the constant being checked
+//    other    - the mask constant to use in the evaluation
+//
+void GenTreeVecCon::EvaluateBinaryInPlace(genTreeOps oper, bool scalar, var_types baseType, GenTreeMskCon* other)
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp]: Do we need a general helper here?

Taking in a mask constant seems pretty unique to Sve.ConditionalSelect and we could avoid converting the constant twice by doing it as part of that code path instead

**Comment by a74nh** [comment]
Updated as per review comments. Fuzzlyn still looks good when https://github.com/dotnet/runtime/pull/116991 is applied.

File: src/coreclr/jit/gentree.cpp [hunk 12]
```diff
@@ -32820,28 +32796,65 @@ GenTree* Compiler::gtFoldExprHWIntrinsic(GenTreeHWIntrinsic* tree)
...
+            {
+                assert(!varTypeIsMask(retType));
+                assert(varTypeIsMask(op1));
+
+                if (cnsNode != op1)
+                {
+                    break;
+                }
+
+                assert(!op1->IsVectorAllBitsSet() && !op1->IsVectorZero());
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp]: This assert should be unnecessary, we've already verified it's of type mask and so it cannot be a CNS_VEC

File: src/coreclr/jit/lowerarmarch.cpp [hunk 13]
```diff
@@ -1193,9 +1193,8 @@ GenTree* Lowering::LowerCnsMask(GenTreeMskCon* mask)
     EvaluateSimdCvtMaskToVector<simd16_t>(parentBaseType, &vecCon->gtSimdVal, mask->gtSimdMaskVal);
     BlockRange().InsertBefore(mask, vecCon);
 
-    GenTreeHWIntrinsic* convertedVec =
-        comp->gtNewSimdCvtVectorToMaskNode(TYP_MASK, vecCon, parentSimdBaseJitType, parentSimdSize);
-    BlockRange().InsertBefore(mask, convertedVec->Op(1));
+    GenTree* convertedVec = comp->gtNewSimdCvtVectorToMaskNode(TYP_MASK, vecCon, parentSimdBaseJitType, parentSimdSize);
+    BlockRange().InsertBefore(mask, convertedVec->AsHWIntrinsic()->Op(1));
```
Comment (tannergooding) [inline src/coreclr/jit/lowerarmarch.cpp]: This isn't strictly related to this PR, but I don't understand why this limit is here...

This seems much more expensive than simply using `adr` to move the PC relative address into `Xn` and then `ldr (predicate)` to load that value.

It seems like that would be far cheaper than requiring a larger vector constant to exist, loading it, and then converting it. All of which will require fairly similar logic due to PC relative load limitations for vectors

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/lowerarmarch.cpp (hunk 13 above)
Comment (a74nh) [reply src/coreclr/jit/lowerarmarch.cpp]: > All of which will require fairly similar logic due to PC relative load limitations for vectors

I originally tried something similar to this in the codegen for CNS_MASK, trying to use `emitIns_R_C()`. That got gnarly quickly. But it would be worth investigating again later

**Comment by a74nh** [comment]
I've switched `EvaluateSimdCvtVectorToMask()` to check against 0 on Arm64, as per this discussion: https://github.com/dotnet/runtime/pull/116991#discussion_r2175466212

I put it in this PR as it's all related to constant vectors/masks.

With these changes, I'm not currently seeing any Fuzzlyn failures.

File: src/coreclr/jit/lowerarmarch.cpp [hunk 14]
```diff
@@ -1134,6 +1134,78 @@ void Lowering::LowerModPow2(GenTree* node)
...
+    // loading from memory. There is no way to load to a predicate from memory using a PC relative
+    // address, so instead use a constant vector plus conversion to mask.
+
+    LABELEDDISPTREERANGE("lowering cns mask to cns vector (before)", BlockRange(), mask);
+
+    LIR::Use use;
+    if (!BlockRange().TryGetUse(mask, &use))
+    {
+        unreached();
+    }
```
Comment (tannergooding) [inline src/coreclr/jit/lowerarmarch.cpp]: We shouldn't assert unreached here. There are always scenarios where unused values get preserved, such as min-opts, and so we should prefer the typical pattern of `if (foundUse) { use.ReplaceWith(node); } else { node->SetUnusedValue(); }`

File: src/coreclr/jit/simd.h [hunk 15]
```diff
@@ -1598,35 +1598,32 @@ void EvaluateSimdCvtVectorToMask(simdmask_t* result, TSimd arg0)
...
-        if ((input0 & significantBit) != 0)
-        {
 #if defined(TARGET_XARCH)
-            // For xarch we have count sequential bits to write
-            // depending on if the corresponding the input element
-            // has its most significant bit set
-
+        // For xarch we have count sequential bits to write depending on if the
+        // corresponding the input element has its most significant bit set
+        if ((input0 & MostSignificantBit) != 0)
```
Comment (tannergooding) [inline src/coreclr/jit/simd.h:1613]: This needs to be fixed for xarch as well, to ensure xplat determinism, but I'll do so in a follow up PR.

File: src/coreclr/jit/valuenum.cpp [hunk 16]
```diff
@@ -7868,6 +7868,28 @@ ValueNum EvaluateSimdCvtVectorToMask(ValueNumStore* vns, var_types simdType, var
     return vns->VNForSimdMaskCon(result);
 }
 
+#if defined(TARGET_ARM64)
+ValueNum EvaluateBinarySimdAndMask(ValueNumStore* vns,
```
Comment (tannergooding) [inline src/coreclr/jit/valuenum.cpp]: This seems similar to the folding case, it's a very specific scenario that is basically only relevant to `ConditionalSelect`, so it seems like a case we'd be better evaluting the mask to a vector VN up front and then calling `EvaluateBinarySimd` on, particularly since it avoids the double conversion of the mask.

**Comment by tannergooding** [comment]
Couple minor changes needed, but otherwise LGTM

**Comment by a74nh** [comment]
@tannergooding 

Fuzzlyn isn't completely clean, I'm seeing one issue per hour.

```c#
    public static int M12()
    {
        for (int lvar0 = 2; lvar0 > 0; lvar0--)
        {
            var vr3 = Sve.ConditionalSelect(Vector128.CreateScalar((byte)1).AsVector(), Vector.Create<byte>(0), Vector.Create<byte>(1));
            uint var1 = (uint)Sve.SaturatingIncrementByActiveElementCount(s_11, vr3);
            Consume(var1);
        }

        return 0;
    }
```

```
Assert failure(PID 3174564 [0x003070a4], Thread: 3174564 [0x3070a4]): Assertion failed 'use.User()->OperIsHWIntrinsic()' in 'Program:M12():int' during 'Lowering nodeinfo' (IL size 60; hash 0x9314a4ed; FullOpts)

    File: /home/alahay01/dotnet/runtime_sve/src/coreclr/jit/lowerarmarch.cpp:1184
    Image: /home/alahay01/dotnet/runtime_sve/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun
```

```
------------ BB01 [0000] [000..03C) (return), preds={} succs={}
               [000077] -----------                            IL_OFFSET void   INLRT @ 0x021[E-]
N001 (  3, 12) [000041] H----------                   t41 =    CNS_INT(h) long   0xf2451404b1a8 static Fseq[s_11] $c0
                                                            /--*  t41    long   
N002 (  3, 12) [000069] DA---------                         *  STORE_LCL_VAR long   V03 cse0         d:1 $VN.Void
N003 (  1,  1) [000070] -----------                   t70 =    LCL_VAR   long   V03 cse0         u:1 $c0
                                                            /--*  t70    long   
N005 (  8, 16) [000040] nA--G------                   t40 = *  IND       ushort <l:$100, c:$140>
N006 (  3,  2) [000042] -----------                   t42 =    CNS_MSK   mask  <0x0000fffe, 0x00000000> $180
                                                            /--*  t42    mask   
N007 (  3,  3) [000073] DA---------                         *  STORE_LCL_VAR mask   V04 cse1         d:1 $VN.Void
N008 (  1,  1) [000074] -----------                   t74 =    LCL_VAR   mask   V04 cse1         u:1 $180
                                                            /--*  t40    ushort 
                                                            +--*  t74    mask   
N010 ( 13, 21) [000039] -A--G------                   t39 = *  HWINTRINSIC long   16 ubyte SaturatingIncrementByActiveElementCount <l:$200, c:$201>
                                                            /--*  t39    long   
N011 ( 14, 23) [000038] -A--G------                   t38 = *  CAST      int <- uint <- long <l:$240, c:$241>
                                                            /--*  t38    int    arg0 x0
N012 ( 28, 26) [000037] -ACXG------                         *  CALL      void   Program:Consume[uint](uint) $VN.Void
               [000078] -----------                            IL_OFFSET void   INLRT @ 0x021[E-]
N001 (  1,  1) [000072] -----------                   t72 =    LCL_VAR   long   V03 cse0         u:1 $c0
                                                            /--*  t72    long   
N002 (  4,  3) [000056] n---G------                   t56 = *  IND       ushort <l:$101, c:$141>
N003 (  1,  1) [000076] -----------                   t76 =    LCL_VAR   mask   V04 cse1         u:1 $180
                                                            /--*  t56    ushort 
                                                            +--*  t76    mask   
N004 (  6,  5) [000055] ----G------                   t55 = *  HWINTRINSIC long   16 ubyte SaturatingIncrementByActiveElementCount <l:$202, c:$203>
                                                            /--*  t55    long   
N005 (  7,  7) [000054] ----G------                   t54 = *  CAST      int <- uint <- long <l:$242, c:$243>
                                                            /--*  t54    int    arg0 x0
N006 ( 21, 10) [000053] --CXG------                         *  CALL      void   Program:Consume[uint](uint) $VN.Void
               [000079] -----------                            IL_OFFSET void   INLRT @ 0x03A[E-]
N001 (  1,  2) [000028] -----+-----                   t28 =    CNS_INT   int    0 $40
                                                            /--*  t28    int    
N002 (  2,  3) [000029] -----+-----                         *  RETURN    int    $VN.Void
```


What's happening is the conditionalSelect has been optimised down to a constant vector, but it's only used as a mask, so it gets replaced with a constant mask. This mask is then _stored as a local variable._

When lowering the mask, it fails to find an SVE mask pattern, so it tries to convert it back to a constant vector. To do that it needs the type of vector type of the user of the mask. But the user is a lcl store, so it asserts.

I don't think there is any obvious way of fixing this inside lowering. Is it safe to have lcl vars stored as masks? Can we get the required base types from tree of the LCL_VAR (urgh) ? Should we just prevent constant vectors being converted to masks when being stored as local vars?

**Comment by tannergooding** [comment]
> Is it safe to have lcl vars stored as masks?

Yes, this is intentional to allow CSE and other core optimizations to lightup

> Can we get the required base types from tree of the LCL_VAR (urgh) ?

Not trivially today, and it should generally be assumed there may be cases that it is not possible.

> Should we just prevent constant vectors being converted to masks when being stored as local vars?

I don't think this is desirable. Rather you want to ensure that the `HWIntrinsicInfo::CanBenefitFromConstantProp` and `GenTree::ShouldConstantProp` methods are aware of `Sve.ConditionalSelect` and that there are cases where constants or key constant values are containable and therefore always profitable to propagate rather than CSE: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/assertionprop.cpp#L3121-L3136. We have a similar check in morph here: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/morph.cpp#L11226-L11232 (although one or both of these should be updated to also handle `CNS_MSK` rather than just `CNS_VEC`).

But, we may still get non-propagatable scenarios, so really this should be just loading a mask constant, rather than doing the `vector constant -> mask` conversion so the issue can be avoided altogether. Short of that, however, this can always be done safely presuming `byte` as the base type, as that will ensure each bit of the predicate is correctly initialized. I believe it can even just use `pmov (to predicate)` which allows this to only load 16-bits and can effectively be `CreateScalarUnsafe<ushort>(...)` followed by `pmov pg.b, zn`

File: src/coreclr/jit/lowerarmarch.cpp [hunk 17]
```diff
@@ -1176,28 +1176,44 @@ GenTree* Lowering::LowerCnsMask(GenTreeMskCon* mask)
...
+    var_types   parentBaseType        = TYP_BYTE;
+    CorInfoType parentSimdBaseJitType = CORINFO_TYPE_BYTE;
+    unsigned    parentSimdSize        = 16;
+    assert(parentSimdSize == 16 || parentSimdSize == 0);
+
     LIR::Use use;
-    if (!BlockRange().TryGetUse(mask, &use))
+    bool     foundUse = BlockRange().TryGetUse(mask, &use);
+
+    if (use.User()->OperIsHWIntrinsic())
```
Comment (tannergooding) [inline src/coreclr/jit/lowerarmarch.cpp]: This needs to check `foundUse && use.User()->...`.

However, is there actually any benefit to doing that over just always using `TYPE_BYTE`? That is, will the codegen be more optimal in such a scenario or does it boil down to the same general pattern and execution latency?

Comment (a74nh) [reply src/coreclr/jit/lowerarmarch.cpp]: > However, is there actually any benefit to doing that over just always using `TYPE_BYTE`? That is, will the codegen be more optimal in such a scenario or does it boil down to the same general pattern and execution latency?

Trying some patterns....


1)
Mask is `0001 0000 0001 0000`
Parent type is `int`

Using `int` in lowering:
In Lowering, mask is converted vector, becoming `FFFFFFFF 00000000 FFFFFFFF 00000000`
In codegen, vector is loaded, cmpne 0 is done on int sized lanes, creating an integer predicate of  `1 0 1 0`

Using `byte` in lowering:
In Lowering, mask is converted vector, becoming `000000FF 00000000 000000FF 00000000`
In codegen, vector is loaded, cmpne 0 is done on int sized lanes, creating an integer predicate of  `1 0 1 0`


2)
Mask is `0001 0000 0101 0100`
Parent type is `int`

Using `int` in lowering:
In Lowering, mask is converted vector, becoming `FFFFFFFF 00000000 FFFFFFFF 00000000`
In codegen, vector is loaded, cmpne 0 is done on int sized lanes, creating an integer predicate of  `1 0 1 0`

Using `byte` in lowering:
In Lowering, mask is converted vector, becoming `000000FF 00000000 00FF00FF 00FF0000`
In codegen, vector is loaded, cmpne 0 is done on int sized lanes, creating an integer predicate of  `1 0 1 0`

----

I will switch it to always use byte.

**Comment by a74nh** [comment]
> I believe it can even just use `pmov (to predicate)` which allows this to only load 16-bits and can effectively be `CreateScalarUnsafe<ushort>(...)` followed by `pmov pg.b, zn`

Yes it can, but that is SVE2.1 and there aren't any machines that support it yet.

**Comment by a74nh** [comment]
> I don't think this is desirable. Rather you want to ensure that the `HWIntrinsicInfo::CanBenefitFromConstantProp` and `GenTree::ShouldConstantProp` methods are aware of `Sve.ConditionalSelect` and that there are cases where constants or key constant values are containable and therefore always profitable to propagate rather than CSE: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/assertionprop.cpp#L3121-L3136. We have a similar check in morph here: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/morph.cpp#L11226-L11232 (although one or both of these should be updated to also handle `CNS_MSK` rather than just `CNS_VEC`).

If the PR is functionally ok as is, could we push this to another PR. That way we can get fuzzlyn working again with this PR.

**Comment by tannergooding** [comment]
> If the PR is functionally ok as is, could we push this to another PR. That way we can get fuzzlyn working again with this PR.

Yeah, for sure. That isn't a functionality issue just something that can help improve codegen.

Was more calling it out as what you'd want to do to avoid the more expensive path if we have places that can otherwise optimize.

**Comment by a74nh** [comment]
This PR is looking good now. Fuzzlyn looks happy (except for hitting the known #113940). CI failures aren't related to this PR. @amanasifkhalid

File: src/coreclr/jit/gentree.cpp [hunk 18]
```diff
@@ -33560,18 +33595,30 @@ GenTree* Compiler::gtFoldExprHWIntrinsic(GenTreeHWIntrinsic* tree)
...
                 {
                     return gtWrapWithSideEffects(op3, op2, GTF_ALL_EFFECT);
                 }
 
                 if (op2->IsCnsVec() && op3->IsCnsVec())
                 {
+                    assert(op2->gtType == TYP_SIMD16);
+                    assert(op3->gtType == TYP_SIMD16);
+
+                    simd16_t op1SimdVal;
```
Comment (amanasifkhalid) [inline src/coreclr/jit/gentree.cpp:33608]: nit:
```suggestion
                    simd16_t op1SimdVal = {};
```

for consistency -- feel free to include in a follow-up

**Review by amanasifkhalid — COMMENTED** [review]
@tannergooding any other comments?

File: src/coreclr/jit/gentree.cpp (hunk 18 above)
Comment (a74nh) [reply src/coreclr/jit/gentree.cpp:33608]: > for consistency -- feel free to include in a follow-up

Happy to throw into the next PR if it's going to delay this one

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:33608]: Lets do it in the next PR. I do have to mark this comment as resolved to merge the PR, however.
