### PR TITLE
Fix infinite recursion in configuration manager

### LINKED ISSUE #41496: [5.0.100-rc.1.20427.10] Nuget Package Explorer System.StackOverflowException at launch
**Application Name:** Nuget Package Explorer (.net5 version)
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 5.0.100-rc.1.20427.10
**App Source on GitHub :** https://github.com/NuGetPackageExplorer/NuGetPackageExplorer
**Location:** \\dtacttestresult\E\HelixTest\ApplicationPayloads\NugetPackageExplorer\Payload\applications\NuGetPackageExplorer

**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build 5.0.100-rc.1.20427.10: **Fail**
2). Windows 10 RS5 X64 + .NET Core SDK build 5.0.100-preview 8 : **Pass**

**Repro steps:**
1) Copy application to machine, launch NuGetPackageExplorer.exe 

Expected Result:
App should start

Actual Result:
App crash, StackOverflowException

**Findings :**
We created a simple project to repro this issue:
[https://github.com/jiangzeng01/WindowsFormsApp5](https://github.com/jiangzeng01/WindowsFormsApp5)

To reproduce this issue : 
In Winforms app, create a class, inherit from ApplicationSettingsBase and override OnSettingsLoaded method, change property value, such as :  

```
using System;
using System.Configuration;
 //Application settings wrapper class
    sealed class FormSettings : ApplicationSettingsBase
    {
        [UserScopedSettingAttribute()]
        public String FormText
        {
            get { return (String)this["FormText"]; }
            set { this["FormText"] = value; }
        }
        protected override void OnSettingsLoaded(object sender, SettingsLoadedEventArgs e)
        {
            if (string.IsNullOrEmpty(FormText))
            {
                FormText = "override OnSettingsLoaded";
            }
        }
    }
```

In main form, we can call  like : 
 
```
private FormSettings frmSettings1 = new FormSettings();
label1.Text = frmSettings1.FormText;

```
This will get Stackoverflow exception in 5.0.100-rc.1.20427.10, Preview .net5 versions works fine.

**Exception from NugetPackage Explorer :** 

  ```
at PackageExplorer.Properties.Settings.get_FontSize()
   at PackageExplorer.Properties.Settings.OnSettingsLoaded(System.Object, System.Configuration.SettingsLoadedEventArgs)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at PackageExplorer.Properties.Settings.get_FontSize()
   at PackageExplorer.Properties.Settings.OnSettingsLoaded(System.Object, System.Configuration.SettingsLoadedEventArgs)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at PackageExplorer.Properties.Settings.get_IsFirstTime()
   at PackageExplorer.App.MigrateSettings()
   at PackageExplorer.App+<Application_Startup>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at PackageExplorer.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run()
   at PackageExplorer.App.Main()
```

cc @dotnet-actwx-bot

### PR DESCRIPTION
**Pull request by safern**
This was introduced by: https://github.com/dotnet/runtime/pull/40583
Fixes: https://github.com/dotnet/runtime/issues/41496

I confirmed that the test I'm adding if we remove this property I get a repro of the infinite recursion.

### CODE REVIEW

File: src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ApplicationSettingsBase.cs [hunk 1]
```diff
@@ -725,6 +725,9 @@ private object GetPropertyValue(string propertyName)
                     }
                 }
 
+                // we query the value first so that we initialize all values from value providers and so that we don't end up
+                // on an infinite recursion when calling Properties[propertyName] as that calls this.
+                object _ = base[propertyName];
```
Comment (eerhardt) [inline src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ApplicationSettingsBase.cs:730]: (nit) can you just use 

```suggestion
                _ = base[propertyName];
```

**Review by eerhardt — APPROVED** [review]
Looks good to me. Thanks for adding the regression test.

**Review by ericstj — APPROVED** [review]
