### PR TITLE
JIT: fix issue in assertion prop phi inference

### LINKED ISSUE #116212: [libraries-pgo] Microsoft.Extensions.Hosting.Unit.Tests fails in OSR stress
Pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1056248&view=results
Example console log: https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-47f137d3961544ab84/Microsoft.Extensions.Hosting.Unit.Tests/1/console.2a54c506.log?helixlogtype=result

```
set DOTNET_TieredCompilation=1
set DOTNET_TC_OnStackReplacement=1
set DOTNET_TC_QuickJitForLoops=1
set DOTNET_TC_OnStackReplacement_InitialCounter=1
set DOTNET_OSR_HitLimit=1
...
Starting:    Microsoft.Extensions.Hosting.Unit.Tests (parallel test collections = on [4 threads], stop on fail = off)
    Microsoft.Extensions.Hosting.Tests.LifecycleTests.CallbackOrder(concurrently: True) [FAIL]
      System.InvalidOperationException : Unable to activate type 'Microsoft.Extensions.Logging.LoggerFactory'. The following constructors are ambiguous:
      Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.Extensions.Logging.LoggerFilterOptions], Microsoft.Extensions.Options.IOptions`1[Microsoft.Extensions.Logging.LoggerFactoryOptions], Microsoft.Extensions.Logging.IExternalScopeProvider)
      Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Logging.LoggerFilterOptions)
```

This fails on multiple platforms under OSR stress. cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Unreachable preds may give conflicting assertions; check both for an assertion that agrees and the absence of one that disagrees.

Also add the ability to dump the flow graph via hash.

Fixes #116212.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib 

Open to other ideas on how to fix this, though this one has fairly minimal diffs.

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
@EgorBo @jakobbotsch I changed this up a bit, take another look?

File: src/coreclr/jit/assertionprop.cpp [hunk 1]
```diff
@@ -4295,6 +4300,22 @@ Compiler::AssertVisit Compiler::optVisitReachingAssertions(ValueNum vn, TAssertV
...
             return AssertVisit::Abort;
         }
+        BitVecOps::AddElemD(&traits, visitedBlocks, phiArg->gtPredBB->bbNum);
+    }
+
+    // Verify the set of phi-preds covers the set of block preds
+    //
+    for (BasicBlock* const pred : ssaDef->GetBlock()->PredBlocks())
+    {
+        if (!BitVecOps::IsMember(&traits, visitedBlocks, pred->bbNum))
```
Comment (EgorBo) [inline src/coreclr/jit/assertionprop.cpp:4310]: Doesn't it mean the SSA is basically stale?

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/assertionprop.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/assertionprop.cpp:4310]: Yes, RBO messes up SSA, though in the past we've argued that it generally doesn't lead to making bad assumptions. This is one case where it does.

**Comment by AndyAyersMS** [comment]
/ba-g installer build and test failed with no log.
