### PR TITLE
Remove DSA from macOS

### LINKED ISSUE #118107: Consider fully retiring FF-DSA from macOS
FF-DSA (henceforth “DSA”) has always been an oddity on Apple platforms. This is a proposal to remove it from macOS.

* FIPS 186-5 has withdrawn recommendation for DSA.
* Apple never fully supported it. It was never supported on iOS / tvOS at all.
* The support that Apple does have on macOS is limited to importing existing keys. It cannot generate DSA keys.
* It never supported FIPS 186-3 DSA keys, limiting it to DSA 1024 with SHA-1.
* Apple’s implementation is based on CSSM. It is not thread safe in certain circumstances and results in crashes. https://github.com/dotnet/runtime/issues/71738 https://github.com/dotnet/runtime/issues/104172
* It is the only remaining use of Apple’s deprecated SecurityTransforms API. Apple never implemented DSA elsewhere like RSA, ECDSA, etc.
* DSA is not supported in many contexts in .NET already. They don’t work with `SslStreamCertificateContext`, `CertificateRequest`, etc.

Seems like there is very little reason to keep it around on macOS.

### PR DESCRIPTION
**Pull request by vcsjones**
This removes DSA (FF-DSA) from macOS.

Closes #71738
Fixes #118107

### CODE REVIEW

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSAImportExport.cs [hunk 1]
```diff
@@ -5,13 +5,13 @@
 
 namespace System.Security.Cryptography.Dsa.Tests
 {
-    [SkipOnPlatform(TestPlatforms.Browser | TestPlatforms.iOS | TestPlatforms.tvOS | TestPlatforms.MacCatalyst, "Not supported on Browser/iOS/tvOS/MacCatalyst")]
+    [ConditionalClass(typeof(DSAFactory), nameof(DSAFactory.IsSupported))]
     public partial class DSAImportExport
     {
         public static bool SupportsFips186_3 => DSAFactory.SupportsFips186_3;
-        public static bool SupportsKeyGeneration => DSAFactory.SupportsKeyGeneration;
+        public static bool IsSupported => DSAFactory.IsSupported;
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSAImportExport.cs]: Since the class is conditional on DSAFactory.IsSupported, I don't think you need the repeated static here.

File: src/libraries/System.Security.Cryptography/tests/DSACreateTests.cs [hunk 2]
```diff
@@ -6,13 +6,13 @@
 
 namespace System.Security.Cryptography.Tests
 {
-    [SkipOnPlatform(TestPlatforms.Browser | TestPlatforms.iOS | TestPlatforms.tvOS | TestPlatforms.MacCatalyst, "Not supported on Browser/iOS/tvOS/MacCatalyst")]
+    [ConditionalClass(typeof(DSAFactory), nameof(DSAFactory.IsSupported))]
     public static class DSACreateTests
     {
-        public static bool SupportsKeyGeneration => DSAFactory.SupportsKeyGeneration;
+        public static bool IsSupported => DSAFactory.IsSupported;
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/tests/DSACreateTests.cs]: I believe this one can also be deleted

File: src/libraries/System.Security.Cryptography/tests/SignatureDescriptionTests.cs [hunk 3]
```diff
@@ -154,7 +155,7 @@ public void Digest()
         }
 
         [Fact]
-        [SkipOnPlatform(TestPlatforms.iOS | TestPlatforms.tvOS | TestPlatforms.MacCatalyst, "Not supported on iOS/tvOS/MacCatalyst")]
+        [SkipOnPlatform(PlatformSupport.AppleCrypto, "DSA is not supported on Apple platforms")]
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/tests/SignatureDescriptionTests.cs]: Why is this one SkipOnPlatform when the previous one got changed to ConditionalFact?

File: src/libraries/System.Security.Cryptography/tests/SignatureDescriptionTests.cs [hunk 4]
```diff
@@ -4,6 +4,8 @@
 // (C) 2002 Motus Technologies Inc. (http://www.motus.com)
 // (C) 2004 Novell  http://www.novell.com
 
+using System.Security.Cryptography.Dsa.Tests;
+using Test.Cryptography;
 using Xunit;
 
 namespace System.Security.Cryptography.Tests
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/tests/SignatureDescriptionTests.cs:11]: Constructor_SecurityElement_DSA has SkipOnPlatform for iOS.  Seems it should either change to DSAFactory.IsSupported, or run on all OSes (looks like it should run fine?)

File: src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.cs [hunk 5]
```diff
@@ -428,7 +428,7 @@ public static void AssociatePersistedKey_CNG_DSA()
         }
 
         [Fact]
-        [SkipOnPlatform(PlatformSupport.MobileAppleCrypto, "DSA is not available")]
+        [SkipOnPlatform(PlatformSupport.AppleCrypto, "DSA is not available")]
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.cs]: I'm continuing to be slightly confused as to the distinction between SkipOnPlatform tests and IsSupported tests.

Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.cs]: Yeah, I will normalize all of them. I just wanted to get a full run through CI to make sure the skips worked the way I wanted them to.

Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.cs]: Okay, the reason is because tests that actually use the DSAFactory as a factory ask the DSAFactory. If the test is just doing `DSA.Create()` then it uses SkipOnPlatform.

Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.cs]: I can use the DSAFactory as a guard but it feels like we are asking the wrong thing.

Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.cs]: I guess I didn't apply that super consistently. Hm.

Comment (bartonjs) [reply src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.cs]: My initial feeling is that we should just add `IsDSASupported` next to `IsRC2Supported` in `PlatformSupport`, and change any "DSA.Create()" callers to be conditional on that.

At which point we probably don't need the distinction on DSAFactory.

So... it's sort of "move the static from DSAFactory to PlatformSupport, and use it everywhere".  If we end up having a mismatch between CAPI and CNG then it'd make sense on DSAFactory, since it'd cease having a simple answer.

Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/tests/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.cs]: That's fair. I over fixated on re-using the key generation one.

File: src/libraries/System.Security.Cryptography/tests/PKCS1MaskGenerationMethodTest.cs [hunk 6]
```diff
@@ -71,7 +71,7 @@ public static void NegativeReturnParameterTest()
 
         [Theory]
         [InlineData("DoesntExist")]
-        [InlineData("DSA")]
+        [InlineData("RSA")]
```
[the remark this answers is not in the document]
Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/tests/PKCS1MaskGenerationMethodTest.cs:74]: It's correct to test that a signature algorithm is not a hash algorithm. That is the point of the test.

File: src/libraries/System.Security.Cryptography.Pkcs/tests/SignedCms/SignedCmsTests.cs [hunk 7]
```diff
@@ -1126,8 +1125,8 @@ public static void EnsureExtraCertsAdded(bool newDocument)
             {
                 cms = new SignedCms();
 
-                // DSA is not supported on mobile Apple platforms, so use ECDsa signed document instead
-                if (PlatformDetection.UsesMobileAppleCrypto)
+                // DSA is not supported on Apple platforms, so use ECDsa signed document instead
+                if (PlatformDetection.UsesAppleCrypto)
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography.Pkcs/tests/SignedCms/SignedCmsTests.cs]: The if isn't really about Apple, it's about "when DSA isn't available".  Rather than chasing down other platforms in the future, let's just use the one DSA lever.

```suggestion
                // When DSA isn't available, use ECDsa instead
                if (!PlatformDetection.IsDSASupported)
```

File: src/libraries/System.Security.Cryptography.Pkcs/tests/SignedCms/SignerInfoTests.cs [hunk 8]
```diff
@@ -676,7 +675,7 @@ public static void AddCounterSignerToUnsortedAttributeSignature()
         }
 
         [ConditionalFact(typeof(SignatureSupport), nameof(SignatureSupport.SupportsRsaSha1Signatures))]
-        [SkipOnPlatform(PlatformSupport.MobileAppleCrypto, "DSA is not available")]
+        [SkipOnPlatform(PlatformSupport.AppleCrypto, "DSA is not available")]
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography.Pkcs/tests/SignedCms/SignerInfoTests.cs]: If at all possible, ConditionalFact.  But since it's already conditional on something else, maybe this is the best we can get?

File: src/libraries/System.Security.Cryptography.Xml/tests/Samples/SigningVerifyingX509Cert.cs [hunk 9]
```diff
@@ -78,7 +78,7 @@ public void SignedXmlHasCertificateVerifiableSignature()
         }
 
         [Fact]
-        [SkipOnPlatform(TestPlatforms.iOS | TestPlatforms.tvOS | TestPlatforms.MacCatalyst, "DSA is not available")]
+        [SkipOnPlatform(TestPlatforms.iOS | TestPlatforms.tvOS | TestPlatforms.MacCatalyst | TestPlatforms.OSX, "DSA is not available")]
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography.Xml/tests/Samples/SigningVerifyingX509Cert.cs]: ConditionalFact

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
Breaking change doc: https://github.com/dotnet/docs/issues/48201
