### PR TITLE
Reset the bbNatLoopNum of block for removed loop

### LINKED ISSUE #68769: Assertion failed '(l2 < optLoopCount) || (l2 == BasicBlock::NOT_IN_LOOP)' during 'Do value numbering'
```c#
// Found by Antigen
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
        public ulong ulong_0;
    }
    static bool s_bool_4 = false;
    static char s_char_6 = '5';
    static int s_int_10 = 1;
    static long s_long_11 = -1;
    static sbyte s_sbyte_12 = 2;
    static uint s_uint_16 = 23;
    static S1 s_s1_18 = new S1();
    bool bool_20 = false;
    char char_22 = 'Q';
    decimal decimal_23 = 23m;
    int int_26 = 0;
    long long_27 = 23;
    ulong ulong_33 = 23;
    static int s_loopInvariant = 2;
    public int LeafMethod6()
    {
        unchecked
        {
            return 15<<4;
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public long LeafMethod7()
    {
        unchecked
        {
            return s_long_11 >>= 15*4;
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public ulong LeafMethod13()
    {
        unchecked
        {
            return 15+4;
        }
    }
    public void Method0()
    {
        unchecked
        {
            bool bool_85 = false;
            char char_87 = 'V';
            int int_91 = 23;
            switch (LeafMethod7() >> LeafMethod6())
            {
                case 1:
                {
                    break;
                }
                case 5:
                {
                    break;
                }
                case -5:
                {
                    if (15<4)
                    {
                    }
                    else
                    {
                        switch (long_27 + 15-4)
                        {
                            case 2:
                            {
                                break;
                            }
                            case 23:
                            {
                                break;
                            }
                            case 5:
                            {
                                break;
                            }
                            case 1:
                            {
                                break;
                            }
                            case -2147483647:
                            {
                                break;
                            }
                            case -1:
                            {
                                break;
                            }
                            case 0:
                            {
                                if (bool_85 = s_bool_4)
                                {
                                }
                                else
                                {
                                }
                                break;
                            }
                            case -5:
                            {
                                break;
                            }
                            default:
                            {
                                break;
                            }
                        }
                    }
                    break;
                }
                case 2:
                {
                    if (15<=4)
                    {
                    }
                    else
                    {
                        switch (s_char_6 = char_87 = char_22)
                        {
                            case '7':
                            {
                                break;
                            }
                            case '9':
                            {
                                break;
                            }
                            case 'E':
                            {
                                break;
                            }
                            case 'K':
                            {
                                break;
                            }
                            case 'V':
                            {
                                break;
                            }
                            case 'T':
                            {
                                if ((int_26 = int_91 = LeafMethod6())< 15+4)
                                {
                                }
                                else
                                {
                                    for (;;)
                                    {
                                        int __loopvar51 = 15-4;
                                        while (s_bool_4 = bool_85 = bool_85)
                                        {
                                            if (__loopvar51 >= s_loopInvariant)
                                                break;
                                        }
                                    }
                                }
                                break;
                            }
                            case 'Z':
                            {
                                break;
                            }
                            case 'B':
                            {
                                break;
                            }
                            case 'X':
                            {
                                break;
                            }
                            default:
                            {
                                break;
                            }
                        }
                    }
                    break;
                }
                case 23:
                {
                    break;
                }
                default:
                {
                    break;
                }
            }
            int __loopvar82 = 15-4;
            for (; s_int_10 < (15^4); __loopvar82++, long_27 %= 15+4)
            {
                if (__loopvar82 > s_loopInvariant)
                    break;
                if (bool_85)
                {
                    for (; s_int_10 < (int_26 ^= 15*4); decimal_23 -= 15%4)
                    {
                        switch (int_26 + 15+4)
                        {
                            case -1:
                            {
                                break;
                            }
                            case 0:
                            {
                                break;
                            }
                            case 2:
                            {
                                break;
                            }
                            case -5:
                            {
                                break;
                            }
                            case 2147483647:
                            {
                                break;
                            }
                            case 23:
                            {
                                break;
                            }
                            case 1:
                            {
                                break;
                            }
                            case 5:
                            {
                                break;
                            }
                            case -2:
                            {
                                try
                                {
                                    s_int_10 |= int_91 |= int_91 |= 15*4;
                                }
                                catch (System.UnauthorizedAccessException)
                                {
                                    if (bool_20)
                                    {
                                    }
                                    else
                                    {
                                        for (int __loopvar74 = s_loopInvariant;;)
                                        {
                                        }
                                    }
                                }
                                break;
                            }
                            default:
                            {
                                break;
                            }
                        }
                        int __loopvar78 = 15-4, __loopSecondaryVar78_0 = s_loopInvariant;
                        for (;;)
                        {
                            if (__loopvar78 >= s_loopInvariant)
                                break;
                            if ((s_sbyte_12 /= 15+4)!= (s_sbyte_12 = 15+4))
                            {
                            }
                            else
                            {
                                switch (s_char_6)
                                {
                                    case 'I':
                                    {
                                        break;
                                    }
                                    case '8':
                                    {
                                        break;
                                    }
                                    case 'X':
                                    {
                                        break;
                                    }
                                    case '0':
                                    {
                                        break;
                                    }
                                    case '4':
                                    {
                                        if (s_s1_18.ulong_0 + (ulong_33 ^= LeafMethod13())< (ulong_33 >>= 15^4))
                                        {
                                        }
                                        else
                                        {
                                        }
                                        break;
                                    }
                                    case 'E':
                                    {
                                        break;
                                    }
                                    default:
                                    {
                                        break;
                                    }
                                }
                                s_uint_16 ^= 15&4;
                            }
                        }
                    }
                }
                else
                {
                }
            }
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}
/*
--------- Test ---------  

Environment:

set COMPlus_JitOptRepeat=*
set COMPlus_JitNoHoist=1
set COMPlus_AltJitName=clrjit_universal_arm64_x64.dll
set COMPlus_AltJit=Method0

Assert failure(PID 76880 [0x00012c50], Thread: 60856 [0xedb8]): Assertion failed '(l2 < optLoopCount) || (l2 == BasicBlock::NOT_IN_LOOP)' in 'TestClass:Method0():this' during 'Do value numbering' (IL size 765; hash 0x46e9aa75; Tier0-FullOpts)
    File: D:\git\runtime\src\coreclr\jit\optimizer.cpp Line: 3010
    Image: D:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
*/
```

### PR DESCRIPTION
**Pull request by kunalspathak**
When a loop is removed, we should also reset the `bbNatLoopNum` present at the blocks to reflect the updated information.

Fixes: https://github.com/dotnet/runtime/issues/68769

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/optimizer.cpp [hunk 1]
```diff
@@ -9589,6 +9590,16 @@ void Compiler::optMarkLoopRemoved(unsigned loopNum)
...
+    for (BasicBlock* const auxBlock : Blocks())
+    {
+        if (auxBlock->bbNatLoopNum == loopNum)
+        {
+            JITDUMP("Resetting loop number for " FMT_BB " from " FMT_LP " to " FMT_LP ".\n", auxBlock->bbNum, loopNum,
+                    loop.lpParent);
+            auxBlock->bbNatLoopNum = loop.lpParent;
+        }
+    }
+
```
Comment (BruceForstall) [inline src/coreclr/jit/optimizer.cpp:9602]: Comments:
1. This should not be inside `#ifdef DEBUG`; it should always run.
2. I'd put it before marking the loop removed.
3. Use `loop.LoopBlocks()` to only iterate over the loop blocks, not all the function blocks.

Comment (kunalspathak) [reply src/coreclr/jit/optimizer.cpp]: > This should not be inside #ifdef DEBUG; it should always run.

Ah, missed that.

**Comment by kunalspathak** [comment]
I intentionally added an assert about `assert(auxBlock->bbNatLoopNum == loopNum);` and realized that this is not always true and we hit the assert even while compiling SPC because `auxBlock` could be inside a nested loop and `bbNatLoopNum` could be pointing to that. 

But I also realized that we don't update the `lpParent` field of child loops if a parent is removed and that is one of the reason we have this:
https://github.com/dotnet/runtime/blob/6111bc7fcfc5445e8d48b2321edb5ba2b1461ae5/src/coreclr/jit/optimizer.cpp#L9587-L9590

https://github.com/dotnet/runtime/blob/6111bc7fcfc5445e8d48b2321edb5ba2b1461ae5/src/coreclr/jit/optimizer.cpp#L9537-L9539

If we have live children, at the minimal, we should at least update the `lpParent` to record that `lpParent` is no longer its parent.

File: src/coreclr/jit/optimizer.cpp [hunk 2]
```diff
@@ -9581,6 +9583,34 @@ void Compiler::optMarkLoopRemoved(unsigned loopNum)
...
+         l != BasicBlock::NOT_IN_LOOP;                             //
+         l = optLoopTable[l].lpSibling)
+    {
+        if ((optLoopTable[l].lpFlags & LPFLG_REMOVED) == 0)
+        {
+            JITDUMP("Resetting parent of loop number " FMT_LP " from " FMT_LP " to " FMT_LP ".\n", l,
+                    optLoopTable[l].lpParent, optLoopTable[loopNum].lpParent);
+            optLoopTable[l].lpParent = optLoopTable[loopNum].lpParent;
+        }
+    }
```
Comment (BruceForstall) [inline src/coreclr/jit/optimizer.cpp:9612]:
```suggestion
    for (BasicBlock::loopNumber l = loop.lpChild; //
         l != BasicBlock::NOT_IN_LOOP;                             //
         l = optLoopTable[l].lpSibling)
    {
        if ((optLoopTable[l].lpFlags & LPFLG_REMOVED) == 0)
        {
            JITDUMP("Resetting parent of loop number " FMT_LP " from " FMT_LP " to " FMT_LP ".\n", l,
                    optLoopTable[l].lpParent, loop.lpParent);
            optLoopTable[l].lpParent = loop.lpParent;
        }
    }
```

**Review by BruceForstall — APPROVED** [review]
