### PR TITLE
Don't swap base and index if index is float reg

### LINKED ISSUE #33363: Assertion failed 'id->idCodeSize() >= csz'
failed in job: [runtime-coreclr jitstress2-jitstressregs 20200308.1](https://dev.azure.com/dnceng/public/_build/results?buildId=551621&view=ms.vss-test-web.build-test-results-tab&runId=17417508&resultId=107797&paneView=debug)

failed test:
JIT/HardwareIntrinsics/X86/Avx2/GatherMaskVector128_ro/GatherMaskVector128_ro.sh
JIT/HardwareIntrinsics/X86/Avx2/GatherMaskVector128_r/GatherMaskVector128_r.sh
JIT/HardwareIntrinsics/X86/Avx2/GatherMaskVector256_ro/GatherMaskVector256_ro.sh
JIT/HardwareIntrinsics/X86/Avx2/GatherMaskVector256_r/GatherMaskVector256_r.sh

Error message:
```
Assert failure(PID 30242 [0x00007622], Thread: 30242 [0x7622]): Assertion failed 'id->idCodeSize() >= csz' in 'System.Runtime.Intrinsics.X86.Avx2:GatherMaskVector128(System.Runtime.Intrinsics.Vector1281[Int64],long,System.Runtime.Intrinsics.Vector1281[Int32],System.Runtime.Intrinsics.Vector1281[Int64],ubyte):System.Runtime.Intrinsics.Vector1281[Int64]' during 'Emit code' (IL size 97)
File: /__w/17/s/src/coreclr/src/jit/emit.cpp Line: 3477
 Image: /home/helixbot/work/B01009CD/p/corerun
/home/helixbot/work/B01009CD/w/98B3091D/e/JIT/HardwareIntrinsics/X86/Avx2/GatherMaskVector128_r/GatherMaskVector128_r.sh: line 275: 30242 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Return code: 1
Raw output file: /home/helixbot/work/B01009CD/w/98B3091D/e/JIT/HardwareIntrinsics/Reports/JIT.HardwareIntrinsics/X86/Avx2/GatherMaskVector128_r/GatherMaskVector128_r.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/B01009CD/p/corerun GatherMaskVector128_r.dll ''
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.30242.dmp
Written 63651840 bytes (15540 pages) to core file
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/B01009CD/p
> /home/helixbot/work/B01009CD/w/98B3091D/e/JIT/HardwareIntrinsics/X86/Avx2/GatherMaskVector128_r/GatherMaskVector128_r.sh
Expected: True
Actual: False
```

category:correctness
theme:emitter
skill-level:intermediate
cost:small

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #33363

### CODE REVIEW

File: src/coreclr/src/jit/emitxarch.cpp [hunk 1]
```diff
@@ -2322,7 +2322,8 @@ UNATIVE_OFFSET emitter::emitInsSizeAM(instrDesc* id, code_t code)
         }
         else
         {
-            if (dspIsZero && baseRegisterRequiresDisplacement(reg) && !baseRegisterRequiresDisplacement(rgx))
+            if (dspIsZero && baseRegisterRequiresDisplacement(reg) && !baseRegisterRequiresDisplacement(rgx) &&
+                !isFloatReg(rgx))
```
Comment (CarolEidt) [inline src/coreclr/src/jit/emitxarch.cpp:2326]: This was failing for a gather instruction, which uses the VSIB format, but for which we can't reverse `reg` and `rgx` since the latter is a vector instruction.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib @tannergooding PTAL

**Review by tannergooding — APPROVED** [review]
LGTM.

Is there possibly an assert we can/should add when encoding the registers to help catch any future issues like this?

File: src/coreclr/src/jit/emitxarch.cpp (hunk 1 above)
Comment (sandreenko) [reply src/coreclr/src/jit/emitxarch.cpp:2326]: I would find the change confusing without this explanation, should it be added as a comment?

**Review by sandreenko — APPROVED** [review]
LGTM

**Comment by CarolEidt** [comment]
> Is there possibly an assert we can/should add when encoding the registers to help catch any future issues like this?

The bug was found by an assert, though not directly related to this. When RBP is used as a base in the SIB or VSIB format, it requires at least a 1 byte displacement, and that wasn't accounted for in the estimate. I can't think of a good candidate for an assert.
