### PR TITLE
NativeAOT: Ignore preferSize and always expand TLS

### LINKED ISSUE #97168: System.NotImplementedException:: ILCompiler.DependencyAnalysis.ReadyToRunHelperNode.EmitInlineTLSAccess
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=531462
Build error leg or test failing: Build / windows-x64 Release NativeAOT_Checked_Libs_SizeOpt / Build product
Pull request: https://github.com/dotnet/runtime/pull/97062

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "ILCompiler.DependencyAnalysis.ReadyToRunHelperNode.EmitInlineTLSAccess",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=531462
**Error message validated:** `ILCompiler.DependencyAnalysis.ReadyToRunHelperNode.EmitInlineTLSAccess`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/18/2024 6:35:26 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[532499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=532499)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/532499/logs/82)||
|[531604](https://dev.azure.com/dnceng-public/public/_build/results?buildId=531604)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/531604/logs/82)||
|[531462](https://dev.azure.com/dnceng-public/public/_build/results?buildId=531462)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/531462/logs/67)|dotnet/runtime#97062|
|[530911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=530911)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/530911/logs/82)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|4|4|

### PR DESCRIPTION
**Pull request by kunalspathak**
Ignore the `preferSize` and always expand TLS. Relevant discussion in https://github.com/dotnet/runtime/pull/89472#discussion_r1445668804

Fixes: https://github.com/dotnet/runtime/issues/97168

### CODE REVIEW

File: src/coreclr/jit/helperexpansion.cpp [hunk 1]
```diff
@@ -444,7 +444,13 @@ PhaseStatus Compiler::fgExpandThreadLocalAccess()
 
     // Always expand for NativeAOT because the TLS access will not be generated by NativeAOT
```
Comment (jkotas) [inline src/coreclr/jit/helperexpansion.cpp:445]:
```suggestion
    // Always expand for NativeAOT because the slow TLS access helper will not be generated by NativeAOT
```

**Review by jkotas — APPROVED** [review]
Thanks
