### PR TITLE
Fix fd leak in Diagnostics Server and add better error handling

### LINKED ISSUE #38156: Test failure: tracing/eventpipe/reverse/reverse/reverse.sh
Happened again: https://helix.dot.net/api/2019-06-17/jobs/24babe78-7797-4a21-b7d0-6157ef54bf62/workitems/PayloadGroup0/console

Any update on this?

_Originally posted by @safern in https://github.com/dotnet/runtime/issues/35270#issuecomment-646379270_

### PR DESCRIPTION
**Pull request by josalem**
The Diagnostics Server would call `socket` every time it attempted to connect to a reverse connection, but wouldn't call `close` on that fd if the subsequent `connect` failed.  I believe this is what was causing test failures in CI (#38156).  ~I have temporarily turned on these tests and moved them all back to Pri0 to test while this is in draft mode.~

Turns reverse server testing back on.

I also increased the error handling for `GetNextAvailableStream`.

fixes #38156

CC @tommcdon @lateralusX @janvorli @BruceForstall @jashook @noahfalk @sywhang

### CODE REVIEW

**Comment by josalem** [comment]
Got one all green CI, but I'm going to run it again before marking for review.  I noticed that the clean environment check in `IpcTest` has failed in a couple places, but I think it is a race condition with other CI tests running at the same time.  I don't think it is worth validating that the environment is "clean" after deleting zombied pipes.  I'll make that change in another PR to keep this one targeted.

File: src/coreclr/src/vm/ipcstreamfactory.cpp [hunk 1]
```diff
@@ -178,22 +179,33 @@ IpcStream *IpcStreamFactory::GetNextAvailableStream(ErrorCallback callback)
...
+                        STRESS_LOG2(LF_DIAGNOSTICS_PORT, LL_INFO10, "IpcStreamFactory::GetNextAvailableStream - ERR :: Poll attempt: %d, connection %d errored.\n", nPollAttempts, i);
+                        fSawError = true;
+                        break;
+                    case IpcStream::DiagnosticsIpc::PollEvents::NONE:
+                        STRESS_LOG2(LF_DIAGNOSTICS_PORT, LL_INFO10, "IpcStreamFactory::GetNextAvailableStream - NON :: Poll attempt: %d, connection %d had no events.\n", nPollAttempts, i);
+                        fSawError = true;
+                        break;
                     default:
-                        // TODO: Error handling
+                        STRESS_LOG2(LF_DIAGNOSTICS_PORT, LL_INFO10, "IpcStreamFactory::GetNextAvailableStream - UNK :: Poll attempt: %d, connection %d had invalid PollEvent.\n", nPollAttempts, i);
```
Comment (sywhang) [inline src/coreclr/src/vm/ipcstreamfactory.cpp:199]: Should we add `fSawError = true` here?

**Review by sywhang — APPROVED** [review]

File: src/coreclr/src/vm/ipcstreamfactory.cpp (hunk 1 above)
Comment (josalem) [reply src/coreclr/src/vm/ipcstreamfactory.cpp:199]: Whoops!  The `fSawError = true;` from line 196 was supposed to be here and not under `PollEventS::NONE`.  So... yes we should.

**Comment by josalem** [comment]
Rebasing again to try and fix CI issues.  They all appear to be unrelated to these changes, but they're preventing the pri0 tests from running on this PR.  I think this change should go in for preview 8 snap this afternoon.  There are a few previously clean CI runs in case we run up against the time limit.

**Comment by josalem** [comment]
CoreCLR Pri0 Runtime Tests Run OSX x64 checked passed all tracing tests.  Failure is a timeout in [crossgen determinism](https://dev.azure.com/dnceng/public/_build/results?buildId=731272&view=ms.vss-test-web.build-test-results-tab&runId=22622576&resultId=102559&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab).  I believe this to be unrelated to these changes.

**Comment by josalem** [comment]
Remaining failures appear to be coming from `Microsoft.Extensions.*`.

**Comment by BruceForstall** [comment]
@josalem Should this fix https://github.com/dotnet/runtime/issues/38843 and https://github.com/dotnet/runtime/issues/38801?

**Comment by josalem** [comment]
Yes to #38843, but I'm not sure this would fix #38801.  I'm still looking at that one.

File: src/coreclr/tests/issues.targets [hunk 2]
```diff
@@ -24,9 +24,6 @@
         <ExcludeList Include="$(XunitTestBinBase)/JIT/SIMD/Vector3Interop_ro/*">
             <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
         </ExcludeList>
-        <ExcludeList Include = "$(XunitTestBinBase)/tracing/eventpipe/pauseonstart/pauseonstart/**">
-            <Issue>https://github.com/dotnet/runtime/issues/38847</Issue>
-        </ExcludeList>
```
Comment (briansull) [inline src/coreclr/tests/issues.targets:29]: This test is still failing

Comment (josalem) [reply src/coreclr/tests/issues.targets:29]: The failure in your PR was fixed in #39686.  If you rebase it should resolve those.
