### PR TITLE
Force storing GC state until we see a labeled IG

### LINKED ISSUE #113553: Test failure in RunReflectionScenario_UnsafeRead
Failed in [runtime-coreclr gcstress-extra](https://dev.azure.com/dnceng-public/public/_build?definitionId=113&_a=summary)/[20250312.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=978389)

coreclr linux x64 Checked gcstress0xc_jitstress2 @ azurelinux.3.amd64.open
coreclr windows x86 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open

```
Beginning scenario: RunReflectionScenario_UnsafeRead

Assert failure(PID 1816 [0x00000718], Thread: 3180 [0x0c6c]): SanityCheck()

CORECLR! MethodTable::Validate + 0x31 (0x71b7836c)
CORECLR! Object::ValidateInner + 0x12D (0x71b830ed)
CORECLR! Object::Validate + 0x98 (0x71b82f78)
CORECLR! WKS::GCHeap::Promote + 0x8F (0x71ea9f4f)
CORECLR! PromoteCarefully + 0x7B (0x71bc0a9b)
CORECLR! GcEnumObject + 0x63 (0x71c9bbd3)
CORECLR! EnumGcRefsX86 + 0x125A (0x71aabd9a)
CORECLR! EECodeManager::EnumGcRefs + 0x114 (0x71aaaaf4)
CORECLR! GcStackCrawlCallBack + 0x129 (0x71c9be19)
CORECLR! Thread::MakeStackwalkerCallback + 0x48 (0x71bc2beb)
    File: D:\a\_work\1\s\src\coreclr\vm\methodtable.cpp:8502
    Image: C:\h\w\A16A0907\p\corerun.exe

App Exit Code: -1073740286
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
```

```
Beginning scenario: RunReflectionScenario_UnsafeRead
[createdump] Gathering state for process 5349 corerun
[createdump] Crashing thread 14e5 signal 11 (000b)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.5349.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5349.dmp
[createdump] Written 187011072 bytes (45657 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 749ms
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
App Exit Code: 22
Expected: 100
Actual: 22
END EXECUTION - FAILED
+ test_exit_code=1
+ /datadisks/disk1/work/AB240976/p/XUnitLogChecker --results-path JIT/HardwareIntrinsics/HardwareIntrinsics_General_ro --test-wrapper HardwareIntrinsics_General_ro --dumps-path /home/helixbot/dotnetbuild/dumps
```

### PR DESCRIPTION
**Pull request by kunalspathak**
This is very odd and corner case scenario. We have a loop after epilog (with stress block layout, we might have something like that). If there are IGs after epilog, the epilog creates additional dummy IG to store GC state in it. We also update the GC vars global variables `emitPrevGCrefVars` and `emitInitGCrefVars` to have most up to date information. Whenever their values are different, we mark such IGs with `IGF_GC_VARS` stating that the IG contains gc information that the gcinfo should record. 

The loop that is immediately after the epilog is marked for alignment, and so we create a new label IG for it. At this point, the GC vars information `emitPrevGCrefVars == emitInitGCrefVars` and so we skip marking this IG with `IGF_GC_VARS`. As a result, it inherits the GC var liveness information from the previous block (which is the dummy block after the epilog) which is wrong.

The fix is to force store the GC state on all IGs until we come across a valid labeled IG. 

Attached is the dump from failing test. Here, `IG14` is the epilog and `IG15` is the dummy IG for which we add all the GC-vars like `V73` etc. When we create `IG16`, we do not add any new GC vars and hence inherit those from `IG15`

[617.dump.asm.zip](https://github.com/user-attachments/files/19678864/617.dump.asm.zip)

Here is the diff after the fix:

image

Thanks @BruceForstall for brainstorming this scenario with me.

Fixes: https://github.com/dotnet/runtime/issues/113553

### CODE REVIEW

**Comment by kunalspathak** [comment]
As imagined, [no diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1011799&view=ms.vss-build-web.run-extensions-tab) because of this being a corner scenario.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/emit.cpp [hunk 1]
```diff
@@ -2839,6 +2845,11 @@ void* emitter::emitAddLabel(VARSET_VALARG_TP GCvars, regMaskTP gcrefRegs, regMas
         }
     }
 
+    if (emitForceStoreGCState)
```
Comment (BruceForstall) [inline src/coreclr/jit/emit.cpp:2848]: This doesn't need to be conditional; you could always set `emitAddedLabel`.

File: src/coreclr/jit/emit.h [hunk 2]
```diff
@@ -2761,6 +2761,14 @@ class emitter
 
     bool emitForceStoreGCState;
 
+    // This flag is used together with `emitForceStoreGCState`. After we set
+    // emitForceStoreGCState = true, we will mark `emitAddedLabel` to true whenever
+    // we see a label IG. In emitSavIG, we will reset `emitForceStoreGCState = false`
+    // only after seeing `emitAddedLabel == true`. Until then, we will keep recording
+    // GC_VARS on the IGs.
+
+    bool emitAddedLabel;
```
Comment (BruceForstall) [inline src/coreclr/jit/emit.h:2770]: Maybe for cleanliness you should initialize `emitAddedLabel = false` in `emitter::emitBegFN`, alongside the existing `emitForceStoreGCState = false`

File: src/coreclr/jit/emit.cpp [hunk 3]
```diff
@@ -1007,8 +1007,14 @@ insGroup* emitter::emitSavIG(bool emitAdd)
         VarSetOps::Assign(emitComp, emitPrevGCrefVars, emitThisGCrefVars);
         emitPrevGCrefRegs = emitThisGCrefRegs;
         emitPrevByrefRegs = emitThisByrefRegs;
+    }
 
+    if (emitAddedLabel)
```
Comment (BruceForstall) [inline src/coreclr/jit/emit.cpp:1012]: I would leave this whole `if` within the above `if (!emitAdd)` clause. Though it probably doesn't matter.

**Review by BruceForstall — APPROVED** [review]
A few suggestions.

File: src/coreclr/jit/emit.cpp (hunk 3 above)
Comment (kunalspathak) [reply src/coreclr/jit/emit.cpp:1012]: ah, makes sense. We might not want to do it for extended blocks.

**Review by BruceForstall — APPROVED** [review]

**Comment by kunalspathak** [comment]
format job failures are unrelated.
