### PR TITLE
Fix PKCS#12 to use SHA1 MAC

### LINKED ISSUE #108815: ReadECDsaPrivateKey_BrainpoolP160r1_Pfx test failure on windows
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=840920
Build error leg or test failing: System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx
Pull request: https://github.com/dotnet/runtime/pull/103375

Related to https://github.com/dotnet/runtime/pull/108795

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Is Windows 10",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=840920
**Error message validated:** `[Is Windows 10`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 10/13/2024 12:01:39 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[841441](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841441)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841441&view=ms.vss-test-web.build-test-results-tab&runId=21862626&resultId=191426)|dotnet/runtime#108789|
|[842067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842067)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842067&view=ms.vss-test-web.build-test-results-tab&runId=21848736&resultId=184754)|dotnet/runtime#108547|
|[842272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842272)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842272&view=ms.vss-test-web.build-test-results-tab&runId=21844604&resultId=179978)||
|[842247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842247)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842247&view=ms.vss-test-web.build-test-results-tab&runId=21843788&resultId=175879)|dotnet/runtime#108572|
|[842229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842229)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842229&view=ms.vss-test-web.build-test-results-tab&runId=21843734&resultId=172659)|dotnet/runtime#108771|
|[842170](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842170)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842170&view=ms.vss-test-web.build-test-results-tab&runId=21843234&resultId=180000)|dotnet/runtime#108685|
|[842124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842124)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842124&view=ms.vss-test-web.build-test-results-tab&runId=21840992&resultId=182542)|dotnet/runtime#106695|
|[841965](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841965)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841965&view=ms.vss-test-web.build-test-results-tab&runId=21838760&resultId=186333)|dotnet/runtime#108336|
|[842057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842057)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842057&view=ms.vss-test-web.build-test-results-tab&runId=21838498&resultId=178466)|dotnet/runtime#108748|
|[842042](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842042)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842042&view=ms.vss-test-web.build-test-results-tab&runId=21837916&resultId=177666)|dotnet/runtime#108765|
|[842036](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842036)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842036&view=ms.vss-test-web.build-test-results-tab&runId=21837790&resultId=176676)|dotnet/runtime#108853|
|[841950](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841950)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841950&view=ms.vss-test-web.build-test-results-tab&runId=21835612&resultId=180304)|dotnet/runtime#108837|
|[841920](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841920)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841920&view=ms.vss-test-web.build-test-results-tab&runId=21834974&resultId=176698)|dotnet/runtime#108848|
|[841853](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841853)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841853&view=ms.vss-test-web.build-test-results-tab&runId=21833296&resultId=184423)|dotnet/runtime#108711|
|[841833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841833)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841833&view=ms.vss-test-web.build-test-results-tab&runId=21832336&resultId=191851)|dotnet/runtime#102069|
|[841208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841208)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841208&view=ms.vss-test-web.build-test-results-tab&runId=21829300&resultId=179327)|dotnet/runtime#108824|
|[841627](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841627)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841627&view=ms.vss-test-web.build-test-results-tab&runId=21827248&resultId=188171)|dotnet/runtime#108838|
|[841616](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841616)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841616&view=ms.vss-test-web.build-test-results-tab&runId=21827102&resultId=181481)|dotnet/runtime#108748|
|[841512](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841512)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841512&view=ms.vss-test-web.build-test-results-tab&runId=21824714&resultId=182379)|dotnet/runtime#108836|
|[841455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841455)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841455&view=ms.vss-test-web.build-test-results-tab&runId=21821406&resultId=177569)|dotnet/runtime#108819|
|[841336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841336)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841336&view=ms.vss-test-web.build-test-results-tab&runId=21816782&resultId=178252)||
|[841312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841312)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841312&view=ms.vss-test-web.build-test-results-tab&runId=21815210&resultId=181118)|dotnet/runtime#108819|
|[841284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841284)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841284&view=ms.vss-test-web.build-test-results-tab&runId=21813494&resultId=182780)|dotnet/runtime#108757|
|[841237](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841237)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841237&view=ms.vss-test-web.build-test-results-tab&runId=21811102&resultId=181671)||
|[2559540](https://dev.azure.com/dnceng/internal/_build/results?buildId=2559540)|dotnet-runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng//internal/_build/results?buildId=2559540&view=ms.vss-test-web.build-test-results-tab&runId=54342519&resultId=199117)||
|[841200](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841200)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841200&view=ms.vss-test-web.build-test-results-tab&runId=21810314&resultId=181231)|dotnet/runtime#103375|
|[841175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841175)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841175&view=ms.vss-test-web.build-test-results-tab&runId=21809430&resultId=177897)|dotnet/runtime#108818|
|[841163](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841163)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841163&view=ms.vss-test-web.build-test-results-tab&runId=21809332&resultId=178787)|dotnet/runtime#108581|
|[841160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841160)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841160&view=ms.vss-test-web.build-test-results-tab&runId=21809244&resultId=186368)|dotnet/runtime#108581|
|[841121](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841121)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841121&view=ms.vss-test-web.build-test-results-tab&runId=21808588&resultId=186738)|dotnet/runtime#103375|
|[841088](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841088)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841088&view=ms.vss-test-web.build-test-results-tab&runId=21808346&resultId=196712)|dotnet/runtime#108707|
|[841080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841080)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841080&view=ms.vss-test-web.build-test-results-tab&runId=21807776&resultId=183693)|dotnet/runtime#108757|
|[841028](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841028)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841028&view=ms.vss-test-web.build-test-results-tab&runId=21805996&resultId=179523)|dotnet/runtime#103375|
|[841021](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841021)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841021&view=ms.vss-test-web.build-test-results-tab&runId=21805738&resultId=177871)|dotnet/runtime#108819|
|[841002](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841002)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841002&view=ms.vss-test-web.build-test-results-tab&runId=21804950&resultId=179305)||
|[840977](https://dev.azure.com/dnceng-public/public/_build/results?buildId=840977)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=840977&view=ms.vss-test-web.build-test-results-tab&runId=21804154&resultId=179385)|dotnet/runtime#108818|
|[840933](https://dev.azure.com/dnceng-public/public/_build/results?buildId=840933)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=840933&view=ms.vss-test-web.build-test-results-tab&runId=21802914&resultId=179771)|dotnet/runtime#108808|
|[840920](https://dev.azure.com/dnceng-public/public/_build/results?buildId=840920)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxTests.ReadECDsaPrivateKey_BrainpoolP160r1_Pfx](https://dev.azure.com/dnceng-public/public/_build/results?buildId=840920&view=ms.vss-test-web.build-test-results-tab&runId=21801950&resultId=181367)|dotnet/runtime#103375|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|18|38|38|

### PR DESCRIPTION
**Pull request by vcsjones**
In #108795 I re-encoded two PKCS#12 documents to use 3DES instead of RC2 so they work on platforms that do not have RC2 available. However, the MAC on the PKCS#12 also changed from SHA-1 to SHA-256. Older Windows 10 (pre 1703, I think) does not support SHA-2 algorithms for the MAC, so this puts it back to SHA-1.

In addition, the test failure output for this is not particularly helpful. This changes the test to preserve the original exception thrown instead of swallowing it and failing with "Is Windows 10".

Contributes to https://github.com/dotnet/runtime/issues/108815.

### CODE REVIEW

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -7730,7 +7730,7 @@ GenTree* Compiler::fgMorphSmpOp(GenTree* tree, MorphAddrContext* mac, bool* optA
 #ifndef TARGET_64BIT
             if (typ == TYP_LONG)
             {
-                // For (long)int1 * (long)int2, we dont actually do the
+                // For (long)int1 * (long)int2, we don't actually do the
```
Comment (bartonjs) [inline src/coreclr/jit/morph.cpp:7733]: Unrelated edit.

**Review by bartonjs — APPROVED** [review]
LGTM once the unrelated edit is reverted.
