### PR TITLE
JIT: Fix profiler tail call insertion logic for FIELD_LIST

### LINKED ISSUE #76879: Assertion failed 'putArgRegNode->gtOper == GT_PUTARG_REG'
osx-arm64 random JitStress

Test: JIT/HardwareIntrinsics/General/Vector128_1/Vector128_1_ro/Vector128_1_ro.sh

https://dev.azure.com/dnceng-public/public/_build/results?buildId=47392&view=ms.vss-test-web.build-test-results-tab&runId=953920&resultId=103768&paneView=debug

```
export COMPlus_TieredCompilation=0
export COMPlus_JitStress=35a

    JIT/HardwareIntrinsics/General/Vector128_1/Vector128_1_ro/Vector128_1_ro.sh [FAIL]
      
      Assert failure(PID 12800 [0x00003200], Thread: 8914595 [0x8806a3]): Assertion failed 'putArgRegNode->gtOper == GT_PUTARG_REG' in 'JIT.HardwareIntrinsics.General.VectorExtend__ToVector256UInt64:RunReflectionScenario():this' during 'Generate code' (IL size 233; hash 0x76b37d97; FullOpts)
      
          File: /Users/runner/work/1/s/src/coreclr/jit/codegenarmarch.cpp Line: 3085
          Image: /private/tmp/helix/working/B5B60A2F/p/corerun
      
      [createdump] Invalid process id: task_for_pid(12800) FAILED (os/kern) failure (5)
      [createdump] This failure may be because createdump or the application is not properly signed and entitled.
      [createdump] Failure took 0ms
      [createdump] waitpid() returned successfully (wstatus 0000ff00)
      /private/tmp/helix/working/B5B60A2F/w/A9B00977/e/JIT/HardwareIntrinsics/General/Vector128_1/Vector128_1_ro/Vector128_1_ro.sh: line 396: 12800 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
```

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by jakobbotsch**
This logic was not handling FIELD_LIST and was also not handling linear order appropriately.

The logic is still a bit odd, it would probably be better to use the same kind of logic as CFG (moving PUTARG nodes ahead of the profiler hook instead), but in practice this seems to be ok.

Fix #76879

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @BruceForstall @kunalspathak 

Failures are #76880, #76836 and #76910

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -1711,45 +1711,104 @@ void Lowering::InsertProfTailCallHook(GenTreeCall* call, GenTree* insertionPoint
...
+// Arguments:
+//    call - the call
+//
+// Returns:
+//    A PUTARG_* node that is the earliest of the call, or nullptr if the call
+//    has no arguments.
+//
+GenTree* Lowering::FindEarliestPutArg(GenTreeCall* call)
+{
+    size_t numMarkedNodes = 0;
```
Comment (BruceForstall) [inline src/coreclr/jit/lower.cpp:1744]: Do we need a 2-pass system? Is it the case that we have a required ordering where the putarg under the field_list are in order, such that we can (1) look for the first field_list and then (2) look for the first putarg under that, in list order?

I guess your solution seems more robust and doesn't require strict list ordering, but does require more traversals.

File: src/coreclr/jit/lower.cpp [hunk 2]
```diff
@@ -1711,45 +1711,104 @@ void Lowering::InsertProfTailCallHook(GenTreeCall* call, GenTree* insertionPoint
...
+    {
+        for (GenTreeFieldList::Use& operand : node->AsFieldList()->Uses())
+        {
+            assert(operand.GetNode()->OperIsPutArg());
+            result += MarkPutArgNodes(operand.GetNode());
+        }
+    }
+    else
+    {
+        node->gtLIRFlags |= LIR::Flags::Mark;
```
Comment (BruceForstall) [inline src/coreclr/jit/lower.cpp:1805]: Would it be appropriate to add:
```
assert((node->gtLIRFlags & LIR::Flags::Mark) == 0);
```

I.e., how do we know the LIR doesn't have any `Mark` set at this point of compilation?

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/jit/lower.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp:1744]: Personally I'd prefer that we don't make any assumptions on linear order vs operand order in LIR after rationalization. For example, it might be reasonable in the future to allow some trivial scheduling/reordering of the `PUTARG_REG` order in lowering. One place today we are moving these nodes already is when control-flow guard is enabled (`MoveCFGCallArg` -- but I think this ends up keeping the nodes in order).

File: src/coreclr/jit/lower.cpp (hunk 2 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp:1805]: Yes that would be appropriate, I can add the assert.

> I.e., how do we know the LIR doesn't have any Mark set at this point of compilation?

Same assumption is made by `LIR::Range::GetTreeRange` that we are using from lowering already. This code is somewhat like `LIR::Range::GetMarkedRange`.

File: src/coreclr/jit/lower.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp:1744]: Is that really true? I think the order matches execution order, but the arguments are pushed so they end up on stack in opposite order.

Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp:1744]: Ah, for the `FIELD_LIST` operands. Ok, interesting, was not aware of this. This logic skips x86 anyway.

**Comment by jakobbotsch** [comment]
Few diffs where we now place the profiler hook a bit earlier, and some TP improvements from removing the `gtSkipCopyOrReload`.

The failures look known according to build analysis.
