### PR TITLE
Fix CFB8 with Zero padding

### LINKED ISSUE #44949: CFB8 mode with zero padding produces exception when encrypting
### Description

The following code will produce an exception inside of `UniversalCryptoEncryptor`:

```c#
using System.Security.Cryptography;

using Aes aes = Aes.Create();
aes.Mode = CipherMode.CFB;
aes.FeedbackSize = 8;
aes.Padding = PaddingMode.Zeros;

using var transform = aes.CreateEncryptor();

byte[] data = new byte[7];
byte[] result = transform.TransformFinalBlock(data, 0, data.Length);
```

results in:

```
Unhandled exception. System.ArgumentException: Destination is too short. (Parameter 'destination')
   at Internal.Cryptography.UniversalCryptoEncryptor.PadBlock(ReadOnlySpan`1 block, Span`1 destination)
   at Internal.Cryptography.UniversalCryptoEncryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at Internal.Cryptography.UniversalCryptoEncryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
```

Doesn't seem that the size of `data` matters, it will always produce an exception.

### Configuration

.NET 5, Linux.

### Regression?

The mode is new in .NET 5, but is a regression against .NET Framework.

### PR DESCRIPTION
**Pull request by vcsjones**
Fix using CFB8 modes with `PaddingMode.Zero`.

Closes #44949

### CODE REVIEW

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherTests.cs [hunk 1]
```diff
@@ -682,95 +682,107 @@ public static void VerifyKnownTransform_CFB8_128_PKCS7_4()
                 feedbackSize: 8);
         }
 
-        [Fact]
-        public static void VerifyKnownTransform_CFB8_128_NoPadding_0_Extended()
+        [Theory]
+        [InlineData(PaddingMode.None)]
+        [InlineData(PaddingMode.Zeros)]
+        public static void VerifyKnownTransform_CFB8_128_NoOrZeroPadding_0_Extended(PaddingMode paddingMode)
```
Comment (vcsjones) [inline src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherTests.cs:688]: Since `Zero` padding does nothing when the input is aligned correctly, and for CFB8 means "any length is aligned correctly", there is no meaningful difference between `None` and `Zeros` when using CFB8, so we can re-use that existing tests.

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherTests.cs [hunk 2]
```diff
@@ -927,18 +939,32 @@ public static void VerifyKnownTransform_CFB128_256_NoPadding_1_Extended()
...
+                {
+                    aes.FeedbackSize = 128;
+                    alignBytes = aes.FeedbackSize / 8;
+                }
+                else
+                {
+                    alignBytes = aes.BlockSize / 8;
+                }
+
+                int missingBytes = alignBytes - (s_multiBlockBytes.Length % alignBytes);
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherTests.cs:967]: Since this test is using the block size as the feedback size, wouldn't it be simpler to just set `aes.FeedbackSize = 128` regardless of the mode up where the padding mode and block mode are set?

Comment (vcsjones) [reply src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/AES/AesCipherTests.cs]: Yes, yes it would.

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
Failures appear unrelated.

**Comment by vcsjones** [comment]
@bartonjs I can backport if you would like.

**Comment by bartonjs** [comment]
> I can backport if you would like.

Much appreciated :smile:.
