### PR TITLE
[runtime] Add remaining runtime events and fix some existing ones on netcore

### LINKED ISSUE #16246: [netcore] Set up static ALC events
Tests:
- [x] Make System.Tests.AppDomainTests.TypeResolve pass (#18141)
- [x] Make System.Tests.AppDomainTests.ResourceResolve pass (https://github.com/dotnet/runtime/pull/36658)
- [x] Make System.Tests.AppDomainTests.AssemblyLoad pass (#18143)
- [x] Make System.Tests.AppDomainTests.FirstChanceException_Called pass (https://github.com/dotnet/runtime/pull/36658)
- [ ] Make System.Tests.AppDomainTests.AssemblyResolve_FirstChanceException pass (dependent on FirstChanceException)
- [x] Make System.Tests.AppDomainTests.AssemblyResolveInvalidAssemblyName pass (#18157)

Tasks (in flux):
- [x] Copy CoreCLR code into our ALC implementation, marking the region (#16256)
- [x] PR CoreCLR to move the code to shared (https://github.com/dotnet/coreclr/pull/26248)
- [x] Remove our copied implementation (#17767)
- [x] Wire up OnAssemblyResolve (see #15081)
- [x] Wire up OnAssemblyLoad (#18143)
- [ ] Only set RequestingAssembly when appropriate (see https://docs.microsoft.com/en-us/dotnet/api/system.resolveeventargs.requestingassembly?view=netcore-3.0#remarks)
- [x] Wire up OnTypeResolve (#18141)
- [x] Wire up OnResourceResolve (https://github.com/dotnet/runtime/pull/36658)
- [x] Wire up FirstChanceException (https://github.com/dotnet/runtime/pull/36658)
- [x] Remove old MonoDomain Do*Resolve methods and ensure nothing calls them from netcore (#18139, #18141, #18143, https://github.com/dotnet/runtime/pull/36658)

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Fixes https://github.com/mono/mono/issues/16246

Contributes to https://github.com/mono/mono/issues/14788

The commits here should be reasonably chunked up, but a summary of what this accomplishes:

* Wires up OnResourceResolve
* Fixes our corlib satellite assembly check in netcore_load_reference (we were previously comparing "System.Private.Corelib" to "System.Private.Corelib.resources", which does not work)
* Adds some useful classes to mono_defaults
* Removes legacy events from MonoDomain and prevents calling them on netcore
* Fixes UnhandledException to call the correct event
* Wires up FirstChanceException

`AppDomainTests.AssemblyResolve_FirstChanceException` is now failing because of the exception type, so it should work once I sort out https://github.com/dotnet/runtime/issues/34030. Until then, keep it disabled.

### CODE REVIEW

File: src/mono/mono/metadata/assembly-internals.h [hunk 1]
```diff
@@ -13,8 +13,10 @@
 
 #ifndef ENABLE_NETCORE
 #define MONO_ASSEMBLY_CORLIB_NAME "mscorlib"
+#define MONO_ASSEMBLY_CORLIB_RESOURCE_NAME "mscorlib.resources"
 #else
 #define MONO_ASSEMBLY_CORLIB_NAME "System.Private.CoreLib"
+#define MONO_ASSEMBLY_CORLIB_RESOURCE_NAME "System.Private.CoreLib.resources"
 #endif
```
Comment (lambdageek) [inline src/mono/mono/metadata/assembly-internals.h:20]:
```suggestion
#else
#define MONO_ASSEMBLY_CORLIB_NAME "System.Private.CoreLib"
#endif
#define MONO_ASSEMBLY_CORLIB_RESOURCE_NAME (MONO_ASSEMBLY_CORLIB_NAME ".resources")
```

not sure about this.  string literal concatenation might be a bit too esoteric.

Comment (CoffeeFlux) [reply src/mono/mono/metadata/assembly-internals.h:20]: Yeah, I had that at first and decided it wasn't worth it. I have no strong opinion though, so happy to switch back.

File: src/mono/mono/metadata/object.c [hunk 2]
```diff
@@ -5073,6 +5081,34 @@ mono_unhandled_exception_checked (MonoObjectHandle exc, MonoError *error)
...
+	MonoVTable *vt = mono_class_vtable_checked (current_domain, mono_defaults.appcontext_class, error);
+	goto_if_nok (error, leave);
+
+	// TODO: use handles directly
+	mono_field_static_get_value_checked (vt, field, &delegate, MONO_HANDLE_NEW (MonoString, NULL), error);
+	goto_if_nok (error, leave);
+	delegate_handle = MONO_HANDLE_NEW (MonoObject, delegate);
+
+	// Unhandled exception callbacks must not be aborted
+	mono_threads_begin_abort_protected_block ();
```
Comment (lambdageek) [inline src/mono/mono/metadata/object.c]: Not sure we need these. netcore doesn't have Thread.Abort.

File: src/mono/mono/metadata/assembly-internals.h (hunk 1 above)
Comment (CoffeeFlux) [reply src/mono/mono/metadata/assembly-internals.h:20]: Also not sure if it works the same way in C++. Maybe? I guess I could try and see if the build breaks 😄

File: src/mono/mono/metadata/object.c (hunk 2 above)
Comment (CoffeeFlux) [reply src/mono/mono/metadata/object.c]: Removed in a followup commit after we chatted on Slack.

File: src/mono/mono/mini/mini-exceptions.c [hunk 3]
```diff
@@ -2693,6 +2693,9 @@ mono_handle_exception_internal (MonoContext *ctx, MonoObject *obj, gboolean resu
 		MONO_PROFILER_RAISE (exception_throw, (obj));
 		jit_tls->orig_ex_ctx_set = FALSE;
 
+		mono_first_chance_exception_checked (MONO_HANDLE_NEW (MonoObject, obj), error);
+		mono_error_assert_ok (error); // Is this safe to assert? Or will it just hide managed exceptions in weird scenarios?
```
Comment (lambdageek) [inline src/mono/mono/mini/mini-exceptions.c]: maybe `g_warning` and `mono_error_cleanup` would be less intrusive

File: src/mono/mono/metadata/object.c [hunk 4]
```diff
@@ -5013,6 +5014,85 @@ mono_unhandled_exception (MonoObject *exc)
...
+	MonoVTable *vt = mono_class_vtable_checked (domain, mono_defaults.appcontext_class, error);
+	return_if_nok (error);
+
+	// TODO: use handles directly
+	mono_field_static_get_value_checked (vt, field, &delegate, MONO_HANDLE_NEW (MonoString, NULL), error);
+	return_if_nok (error);
+	delegate_handle = MONO_HANDLE_NEW (MonoObject, delegate);
+
+	// TODO: is this necessary here?
+	mono_threads_begin_abort_protected_block ();
```
Comment (lambdageek) [inline src/mono/mono/metadata/object.c]: Don't think we need this.

**Review by lambdageek — APPROVED** [review]

File: src/mono/mono/metadata/assembly-internals.h (hunk 1 above)
Comment (lambdageek) [reply src/mono/mono/metadata/assembly-internals.h:20]: I also don't have a strong opinion about it.

> Also not sure if it works the same way in C++

It's apparently "translation phase 6" https://en.cppreference.com/w/cpp/language/translation_phases

File: src/mono/mono/mini/mini-exceptions.c [hunk 5]
```diff
@@ -2693,6 +2693,11 @@ mono_handle_exception_internal (MonoContext *ctx, MonoObject *obj, gboolean resu
 		MONO_PROFILER_RAISE (exception_throw, (obj));
 		jit_tls->orig_ex_ctx_set = FALSE;
 
+#ifdef ENABLE_NETCORE
+		mono_first_chance_exception_checked (MONO_HANDLE_NEW (MonoObject, obj), error);
+		mono_error_assert_ok (error); // Should we swallow any errors here instead?
```
Comment (lambdageek) [inline src/mono/mono/mini/mini-exceptions.c:2698]: maybe `g_warning` and `mono_error_cleanup` would be less intrusive

File: src/mono/mono/metadata/assembly-internals.h (hunk 1 above)
Comment (imhameed) [reply src/mono/mono/metadata/assembly-internals.h:20]: Doing this would make grepping the source for the string "System.Private.CoreLib.resources" (or "mscorlib.resources") a little harder.

String literal concatenation works the same way in both C and C++. It's used here: [[1]](https://github.com/mono/mono/blob/98320ecbde70b29db4c2591f9a8ae82ee60a2b52/mono/mini/llvm-jit.cpp#L460) [[2]](https://github.com/mono/mono/blob/98320ecbde70b29db4c2591f9a8ae82ee60a2b52/mono/mini/llvm-jit.cpp#L165)
