### PR TITLE
[SuperFileCheck] Added verification when using 'FULL-LINE-NEXT'. Fixing ARM64 comparison tests.

### LINKED ISSUE #81531: JIT/opt/Compares/compares should seemingly not be passing file-check on arm64
https://github.com/dotnet/runtime/blob/9e8d0a81a35f05eaa2c4d0ab258ed9a1f4e2ec76/src/tests/JIT/opt/Compares/compares.cs#L126-L133

`ge` is a signed comparison. If I try this function locally via altjit I get:
```asm
; Assembly listing for method Program:Ge_uint_consume(uint,uint)
; Emitting BLENDED_CODE for generic ARM64 CPU - Windows
; optimized code
; fp based frame
; partially interruptible
; No PGO data
; invoked as altjit
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  6,  6   )     int  ->   x0
;  V01 arg1         [V01,T01] (  4,  4   )     int  ->   x1         single-def
;# V02 OutArgs      [V02    ] (  1,  1   )  lclBlk ( 0) [sp+00H]   "OutgoingArgSpace"
;
; Lcl frame size = 0

G_M25905_IG01:              ;; offset=0000H
        A9BF7BFD          stp     fp, lr, [sp, #-0x10]!
        910003FD          mov     fp, sp
                                                ;; size=8 bbWeight=1 PerfScore 1.50
G_M25905_IG02:              ;; offset=0008H
        528001E2          mov     w2, #15
        6B01001F          cmp     w0, w1
        1A802040          csel    w0, w2, w0, hs
        D2929602          movz    x2, #0x94B0      // code for Program:consume[uint](uint,uint)
        F2B96B42          movk    x2, #0xCB5A LSL #16
        F2CFFFC2          movk    x2, #0x7FFE LSL #32
        F9400042          ldr     x2, [x2]
        D63F0040          blr     x2
                                                ;; size=32 bbWeight=1 PerfScore 7.00
G_M25905_IG03:              ;; offset=0028H
        A8C17BFD          ldp     fp, lr, [sp], #0x10
        D65F03C0          ret     lr
                                                ;; size=8 bbWeight=1 PerfScore 2.00

; Total bytes of code 48, prolog size 8, PerfScore 15.30, instruction count 12, allocated bytes for code 48 (MethodHash=96c19ace) for method Program:Ge_uint_consume(uint,uint)
; ============================================================
```

So the JIT is emitting `hs`, an unsigned comparison, as expected. But then why is the test passing?

cc @markples @TIHan

### PR DESCRIPTION
**Pull request by TIHan**
## Description
Resolves https://github.com/dotnet/runtime/issues/81531

This also adds verification if the user accidently uses an incorrect directive such as `-NEXT-FULL-LINE:`.
I made an issue to consider changing the `FULL-LINE` to use FileCheck's modifier syntax: https://github.com/dotnet/runtime/issues/82134

### CODE REVIEW

File: src/tests/JIT/opt/Compares/compares.cs [hunk 1]
```diff
@@ -142,7 +142,7 @@ public static void Gt_ushort_consume(ushort a1, ushort a2)
     public static void Ge_uint_consume(uint a1, uint a2)
     {
         // ARM64-FULL-LINE:      cmp {{w[0-9]+}}, {{w[0-9]+}}
-        // ARM64-NEXT-FULL-LINE: csel {{w[0-9]+}}, {{w[0-9]+}}, {{w[0-9]+}}, {{ge|lt}}
+        // ARM64-FULL-LINE-NEXT: csel {{w[0-9]+}}, {{w[0-9]+}}, {{w[0-9]+}}, hs
```
Comment (jakobbotsch) [inline src/tests/JIT/opt/Compares/compares.cs:145]:
```suggestion
        // ARM64-FULL-LINE-NEXT: csel {{w[0-9]+}}, {{w[0-9]+}}, {{w[0-9]+}}, {{hs|lo}}
```

Just to make these test less fragile (e.g. `csel x0, x1, x2, hs` is equivalent to `csel x0, x2, x1, lo` and the JIT may flip it for any reason)

File: src/coreclr/tools/SuperFileCheck/Program.cs [hunk 2]
```diff
@@ -80,6 +80,20 @@ static bool ContainsCheckPrefixes(string str, string[] checkPrefixes)
...
+        /// </summary>
+        static void VerifyCheckPrefixes(string str, string[] checkPrefixes)
+        {
+            var invalidFullLinePattern = $"({String.Join('|', checkPrefixes)})+?({{LITERAL}})?(-NEXT-FULL-LINE:)";
+            var invalidRegex = new System.Text.RegularExpressions.Regex(invalidFullLinePattern);
+            if (invalidRegex.Count(str) > 0)
+            {
+                throw new SuperFileCheckException("'NEXT-FULL-LINE' is an invalid directive. Use 'FULL-LINE-NEXT'.");
+            }
+        }
```
Comment (jakobbotsch) [inline src/coreclr/tools/SuperFileCheck/Program.cs:95]: Is it possible to have a whitelist instead of blacklist for this?

Comment (TIHan) [reply src/coreclr/tools/SuperFileCheck/Program.cs:95]: Given that we really just want to check for `-NEXT-FULL-LINE:` and because this syntax may change in the future, I don't think we really need to do more work here.

Comment (jakobbotsch) [reply src/coreclr/tools/SuperFileCheck/Program.cs:95]: Well, the point is to catch unrecognized directives that are noops, not just this one particular case.

Comment (jakobbotsch) [reply src/coreclr/tools/SuperFileCheck/Program.cs:95]: I guess ideally filecheck itself would warn for them though

Comment (TIHan) [reply src/coreclr/tools/SuperFileCheck/Program.cs:95]: That makes sense. I do think this is fine for now though. I'm a little hesitant to try to do a catch-all for the directives considering the possibilities of the FileCheck syntax in general.

Comment (TIHan) [reply src/coreclr/tools/SuperFileCheck/Program.cs:95]: Added an issue regarding it: https://github.com/dotnet/runtime/issues/82139

**Review by jakobbotsch — APPROVED** [review]
