### PR TITLE
Don't throw when deserializing SettingsPropertyValue that's not byte[]

### LINKED ISSUE #29429: LocalFileSettingsProviderTests.GetPropertyValues_NotStoredProperty_ValueEqualsNull failing sporadically in CI
```
System.ConfigurationTests.LocalFileSettingsProviderTests.GetPropertyValues_NotStoredProperty_ValueEqualsNull


Error message
System.Configuration.ConfigurationErrorsException : An error occurred loading a configuration file: The process cannot access the file 'C:\\Users\\runner\\AppData\\Local\\Microsoft_Corporation\\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\\2.5.1.0\\user.config' because it is being used by another process. (C:\\Users\\runner\\AppData\\Local\\Microsoft_Corporation\\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\\2.5.1.0\\user.config)\r\n---- System.IO.IOException : The process cannot access the file 'C:\\Users\\runner\\AppData\\Local\\Microsoft_Corporation\\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\\2.5.1.0\\user.config' because it is being used by another process.

Stack trace
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\ConfigurationSchemaErrors.cs:line 76
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3659
   at System.Configuration.BaseConfigurationRecord.RefreshFactoryRecord(String configKey) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 747
   at System.Configuration.BaseConfigurationRecord.HlClearResultRecursive(String configKey, Boolean forceEvaluatation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3378
   at System.Configuration.BaseConfigurationRecord.HlClearResultRecursive(String configKey, Boolean forceEvaluatation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3421
   at System.Configuration.BaseConfigurationRecord.HlClearResultRecursive(String configKey, Boolean forceEvaluatation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3421
   at System.Configuration.BaseConfigurationRecord.HlClearResultRecursive(String configKey, Boolean forceEvaluatation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3421
   at System.Configuration.Internal.InternalConfigRoot.ClearResult(BaseConfigurationRecord configRecord, String configKey, Boolean forceEvaluation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\Internal\InternalConfigRoot.cs:line 288
   at System.Configuration.BaseConfigurationRecord.RefreshSection(String configKey) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 268
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String sectionName) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientConfigurationSystem.cs:line 61
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\ConfigurationManager.cs:line 173
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientSettingsStore.cs:line 96
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\LocalFileSettingsProvider.cs:line 91
   at System.ConfigurationTests.LocalFileSettingsProviderTests.GetPropertyValues_NotStoredProperty_ValueEqualsNull() in D:\a\1\s\src\System.Configuration.ConfigurationManager\tests\System\Configuration\LocalFileSettingsProviderTests.cs:line 27
----- Inner Stack Trace -----
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\IO\FileStream.Windows.cs:line 1643
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\IO\FileStream.Win32.cs:line 45
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\IO\FileStream.cs:line 238
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) in F:\workspace\_wor
```
cc: @JeremyKuhne

### LINKED ISSUE #104914: BinaryFormatter exception in ConfigurationManager when accessing non-existing key
.NET 6
Console application

Why does this create an exception regarding BinaryFormatter not supported?
I am not using any binary formatter, and SettingsSerializeAs is set to XML.

`using System.Configuration;`

`var provider = new LocalFileSettingsProvider();`
`var context = new SettingsContext();`

`var attributes = new SettingsAttributeDictionary();`
`var attr = new UserScopedSettingAttribute()`;
`attributes.Add(attr.TypeId, attr);`

`var prop = new SettingsProperty(`
`    "Test",`
`    typeof(bool),`
`    provider,`
`    false,`
`    default(bool),`
`    SettingsSerializeAs.Xml,`
`    attributes,`
`    false,`
`    false);`

`var propertyCollection = new SettingsPropertyCollection { prop };`
`var propertyValueCollection = provider.GetPropertyValues(context, propertyCollection);`
`var pv = propertyValueCollection["Test"];`
`var value = pv.PropertyValue;`

### PR DESCRIPTION
**Pull request by ericstj**
Fixes: #104914, #29429

As mentioned in the issue, this problem was introduced in net6.0 when `EnableUnsafeBinaryFormatterInPropertyValueSerialization` check was added.

Previously this would not even hit BinaryFormatter, it would thow when casting to `byte[]` and that would be caught and execution would continue.

With the change in 6.0 it began throwing when `EnableUnsafeBinaryFormatterInPropertyValueSerialization` was not set.  To avoid this, we'll test first if we could even use `BinaryFormatter` before consulting the flag to throw.

This also fixes #29429 which was caused by contention for user.config between the tests in `LocalFileSettingsProviderTests`.

### CODE REVIEW

File: src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsPropertyValue.cs [hunk 1]
```diff
@@ -95,11 +95,11 @@ private object Deserialize()
                     {
                         value = GetObjectFromString(Property.PropertyType, Property.SerializeAs, (string)SerializedValue);
                     }
-                    else
+                    else if (SerializedValue is byte[] serializedBytes)
                     {
                         if (SettingsProperty.EnableUnsafeBinaryFormatterInPropertyValueSerialization)
                         {
-                            using (MemoryStream ms = new MemoryStream((byte[])SerializedValue))
+                            using (MemoryStream ms = new MemoryStream(serializedBytes))
```
Comment (stephentoub) [inline src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsPropertyValue.cs:102]: Not related to your change, but is anything in the catch block below still relevant?

**Review by stephentoub — APPROVED** [review]

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @ericstj !

File: src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsPropertyValue.cs (hunk 1 above)
Comment (ericstj) [reply src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsPropertyValue.cs:102]: That's a good point.  This implementation only ever runs on .NETCore, and noone defines `RaisePropertyDeserializationWebErrorEvent` any more.  We can just delete it that - but this still needs the catch-all exceptions path.  I'll make a follow up PR and we can decide when to take it.
