### PR TITLE
Fix HTTP SchSendAuxRecordTest

### LINKED ISSUE #24776: Test failure: System.Net.Http.Functional.Tests.SchSendAuxRecordHttpTest / HttpClient_ClientUsesAuxRecord_Ok
## Type of failures

```
System.TimeoutException : Task timed out after 15000
at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
at System.Net.Http.Functional.Tests.SchSendAuxRecordHttpTest.<HttpClient_ClientUsesAuxRecord_Ok>d__2.MoveNext() in E:\A\_work\2359\s\corefx\src\System.Net.Http\tests\FunctionalTests\SchSendAuxRecordHttpTest.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
```

## History of failures

Day | Build | OS | Details
-- | -- | -- | -- 
1/3 | 20180103.03 | Win7 |
1/20 | 20180120.02 | Win7 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180120.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SchSendAuxRecordHttpTest~2FHttpClient_ClientUsesAuxRecord_Ok)
1/20 | 20180120.02 | Win7 | [ManagedHandler] [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180120.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_SchSendAuxRecordHttpTest~2FHttpClient_ClientUsesAuxRecord_Ok)
1/28 | 20180128.04 | Win7 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180128.04/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_SchSendAuxRecordHttpTest~2FHttpClient_ClientUsesAuxRecord_Ok)
3/23 | 20180323.03 | Win10 | PlatformHandler
3/23 | 20180323.03 | Win10 | SocketsHttpHandler

### PR DESCRIPTION
**Pull request by aik-jahoda**
Explicitly wait for HTTP end fixed flaky test.

Before it failed locally approximately every 10 runs, now it has 11k successful runs.

fixes #24776

### CODE REVIEW

File: src/libraries/Common/tests/System/Net/Http/SchSendAuxRecordHttpTest.cs [hunk 1]
```diff
@@ -10,16 +10,50 @@
...
 #endif
 
-    [ActiveIssue("https://github.com/dotnet/runtime/issues/24776")]    // Flaky test
     public abstract class SchSendAuxRecordHttpTest : HttpClientHandlerTestBase
     {
         public SchSendAuxRecordHttpTest(ITestOutputHelper output) : base(output) { }
 
+        class CircularBuffer
+        {
+
```
Comment (stephentoub) [inline src/libraries/Common/tests/System/Net/Http/SchSendAuxRecordHttpTest.cs]: Nit: remove blank line

File: src/libraries/Common/tests/System/Net/Http/SchSendAuxRecordHttpTest.cs [hunk 2]
```diff
@@ -10,16 +10,50 @@
...
 #if WINHTTPHANDLER_TEST
     using HttpClientHandler = System.Net.Http.WinHttpClientHandler;
 #endif
 
-    [ActiveIssue("https://github.com/dotnet/runtime/issues/24776")]    // Flaky test
     public abstract class SchSendAuxRecordHttpTest : HttpClientHandlerTestBase
     {
         public SchSendAuxRecordHttpTest(ITestOutputHelper output) : base(output) { }
 
+        class CircularBuffer
```
Comment (stephentoub) [inline src/libraries/Common/tests/System/Net/Http/SchSendAuxRecordHttpTest.cs]: Nit: private

**Review by stephentoub — APPROVED** [review]

**Comment by davidsh** [comment]
@aik-jahoda Thanks for the PR!

I made a change to your PR title to make it clearer what it is. It isn't necessary to have your username or bug number in the title of the PR itself. The bug number is already listed in the commit description.

File: src/libraries/Common/tests/System/Net/Http/SchSendAuxRecordHttpTest.cs [hunk 3]
```diff
@@ -41,8 +74,13 @@ public async Task HttpClient_ClientUsesAuxRecord_Ok()
                 int serverTotalBytesReceived = 0;
                 int serverChunks = 0;
 
+                CircularBuffer buffer = new CircularBuffer(4);
```
Comment (davidsh) [inline src/libraries/Common/tests/System/Net/Http/SchSendAuxRecordHttpTest.cs]: nit: It would be ok to use `var` here instead of the explicit type. `var` is used when the type is obvious such as when doing a `new` or a cast operation.

i.e.

```c#
var buffer = new CircularBuffer(4);
```

**Review by davidsh — APPROVED** [review]
LGTM with comments.

**Comment by davidsh** [comment]
I'm curious about one thing.

>Before it failed locally approximately every 10 runs, now it has 11k successful runs.

You fixed the hanging of the test. But I'm wondering if the test actually is doing what we expect it to do.

For example:

```c#
                if (serverAuxRecordDetectedInconclusive)
                {
                    _output.WriteLine("Test inconclusive: The Operating system preferred a non-CBC or Null cipher.");
                }
                else
                {
                    Assert.True(serverAuxRecordDetected, "Server reports: Client auxiliary record not detected.");
                }
```

Did you look at the TestOutput.xml and see whether or not the test is really ending up with `serverAuxRecordDetectedInconclusive`?  I.e. did you see any "Test inconclusive" output in the test output?

**Comment by aik-jahoda** [comment]
@davidsh I can't see any "Test inconclusive" on the testresult.xml. 

I don't know the background of this test, can you please share your thoughts?

There is a similar test: https://github.com/dotnet/runtime/blob/60d1224ddd68d8ac0320f439bb60ac1f0e9cdb27/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamSchSendAuxRecordTest.cs#L27

Should I merge this ticket and create new for "Test inconclusive"?

**Comment by davidsh** [comment]
> I can't see any "Test inconclusive" on the testresult.xml.

That's good! I just wanted to check to make sure that we are getting a positive test which helps to verify that the mitigation is actually working (i.e. splitting the packet in 1/n-1 sizes).

>Should I merge this ticket and create new for "Test inconclusive"?

This is ok to merge now. You don't need to create a new test for "inconclusive".  Thanks!
