### PR TITLE
Fix some issues with background thread compilation

### LINKED ISSUE #3566: Background thread can execute user code with captured ExecutionContext when compiling service IL
### Describe the bug
Today we compile an optimized delegate on a background after 2 service resolutions. The assumption is that this background thread should be compiling only after resolving the service twice but it's possible for the second call to outrun the first call resulting in the background thread capturing the execution context of the original thread and calling back into user code. This in itself isn't a bug but can result in bugs if there's strange interactions with async locals that hold onto an `IServiceProvider` and resolve services during this background thread compilation.

### To Reproduce
Hard, extremely hard 😄.

### Expected behavior
The background thread should discard the current execution context and not call back into user code.

### Scenario
Here's where this showed up.

Thread1: Singleton (takes lock) -> Scoped (waiting for scope lock)
Thread2: Scoped (takes scope lock) -> Singleton (waiting for singleton lock)

The DI container makes it illegal for singleton instances to depend on scoped instances so how did this happen? Well in the repro scenario, the background thread inside of the container kicked off and started to resolve singletons before the main thread could. Since we use `Task.Run`, it captures all async locals and that in turn resulted in having access to a scoped service provider via an async local (IHttpContextAccessor). This combination of events results in the above dependency graph that causes a deadlock.

### PR DESCRIPTION
**Pull request by maryamariyan**
- Resolve dependencies before counting to avoid the race
where its possible for the background thread to run before
the main thread resulting in singletons being resolved during
compilation (it's meant to be side effect free).

- We also avoid capturing the ExecutionContext on the background thread
to avoid capture of async locals.

Fixes dotnet/extensions#3566

Simply a port taken from @davidfowl 's PR https://github.com/dotnet/extensions/pull/3569

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/DynamicServiceProviderEngine.cs [hunk 1]
```diff
@@ -20,12 +20,30 @@ public DynamicServiceProviderEngine(IEnumerable<ServiceDescriptor> serviceDescri
...
+                    // resolve function
+                    ThreadPool.UnsafeQueueUserWorkItem(state =>
+                    {
+                        try
+                        {
+                            base.RealizeService(callSite);
+                        }
+                        catch
+                        {
+                            // Swallow the exception, we should log this via the event source in a non-patched release
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/DynamicServiceProviderEngine.cs:39]: Were we going to handle this comment here? Or should an issue be logged for it?

Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/DynamicServiceProviderEngine.cs:39]: I'd log an issue.

Comment (maryamariyan) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/DynamicServiceProviderEngine.cs:39]: Created https://github.com/dotnet/runtime/issues/43083

**Comment by maryamariyan** [comment]
@ericstj this PR targets master, for a patch fix which branch needs to be targeted?

**Review by ericstj — APPROVED** [review]

**Comment by ericstj** [comment]
Not sure it’s possible to reliable test but we should add a regression test if possible.

**Review by eerhardt — APPROVED** [review]

**Comment by Pilchie** [comment]
The patch PR is against the extensions repo, and we'll watch that for 3.1.x, but this needs to make it into 5.0 GA as well.  Presumably a backport `release/5.0`.

**Comment by maryamariyan** [comment]
> The patch PR is against the extensions repo, and we'll watch that for 3.1.x, but this needs to make it into 5.0 GA as well. Presumably a backport release/5.0.

5.0 PR: https://github.com/dotnet/runtime/pull/43098
