### PR TITLE
RyuJIT: Fix logic to test bits in a constant vector (Vector256)

### LINKED ISSUE #47236: Incorrect codegen for Vector256.Create(0, 0, 0, 0, 1, 1, 1, 1)
### Description
Stumbled upon this issue while working on https://github.com/SixLabors/ImageSharp/pull/1513.
Looks like that `Vector256.Create(0, 0, 0, 0, 1, 1, 1, 1)` results in just a `vxorps`, so it effectively just zeroes the register.
You can repro this by just creating a value into a local and calling `ToString()` on it: all values are just 0.

### Configuration
- .NET 5.0.101
- Checked with both sharplab, and locally with disasmo on a recent CoreCLR build

### Regression?
Yes, it seems to work fine on .NET Core 3.1.

### Codegen (disasmo)

```csharp
public static void Foo(ref Vector256<int> x)
{
    x = Vector256.Create(0, 0, 0, 0, 1, 1, 1, 1);
}
```
```asm
; Assembly listing for method Vector256CreateRepro.Program:Foo(byref)
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  3,  3   )   byref  ->  rcx        
;# V01 OutArgs      [V01    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]   "OutgoingArgSpace"
;
; Lcl frame size = 0

G_M21017_IG01:
       vzeroupper 
						;; bbWeight=1    PerfScore 1.00
G_M21017_IG02:
       vxorps   ymm0, ymm0, ymm0
       vmovupd  ymmword ptr[rcx], ymm0
						;; bbWeight=1    PerfScore 3.33
G_M21017_IG03:
       vzeroupper 
       ret      
						;; bbWeight=1    PerfScore 2.00

; Total bytes of code 15, prolog size 3, PerfScore 8.03, instruction count 5 (MethodHash=f2a3ade6) for method Vector256CreateRepro.Program:Foo(byref)
; ============================================================
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/47236 bug

The bug was introduced in .NET 5 (doesn't reproduce on `netcoreapp3.1`) - do we want to backport the fix?

/cc @dotnet/jit-contrib

### CODE REVIEW

File: src/coreclr/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -1517,8 +1517,16 @@ void Lowering::LowerHWIntrinsicCreate(GenTreeHWIntrinsic* node)
 
         assert((simdSize == 8) || (simdSize == 12) || (simdSize == 16) || (simdSize == 32));
 
-        if ((argCnt == 1) ||
-            ((vecCns.i64[0] == vecCns.i64[1]) && ((simdSize <= 16) || (vecCns.i64[2] == vecCns.i64[3]))))
+        bool allBytesAreSame = true;
+        for (UINT32 i = 0; i < simdSize; i++)
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:1521]: Can this loop over `i32`/`i64` elements to keep the number of comparisons to a minimum?

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/lowerxarch.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/lowerxarch.cpp]: Sure!

**Comment by EgorBo** [comment]
🤔 the code in my PR is not used on arm64 but arm64 legs crash with 
```
Assert failure(PID 6060 [0x000017ac], Thread: 7556 [0x1d84]): Assertion failed 'isValidArrangement(size, opt)' in 'Program:TestVector64()' during 'Generate code' (IL size 1221)

    File: F:\workspace\_work\1\s\src\coreclr\jit\emitarm64.cpp Line: 380
``` 
on my tests.

File: src/coreclr/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -1517,8 +1517,16 @@ void Lowering::LowerHWIntrinsicCreate(GenTreeHWIntrinsic* node)
 
         assert((simdSize == 8) || (simdSize == 12) || (simdSize == 16) || (simdSize == 32));
 
-        if ((argCnt == 1) ||
-            ((vecCns.i64[0] == vecCns.i64[1]) && ((simdSize <= 16) || (vecCns.i64[2] == vecCns.i64[3]))))
+        bool i64ComponentsEqual = true;
+        for (UINT32 i = 0; i < simdSize / 8; i++)
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:1521]: There's actually a small bug here. `simdSize / 8` will be `1` for `simdSize == 12` and so it will miss the upper 4 bytes.
Likewise, doing a full secondary 8-byte comparison will fail for `simdSize == 12` because the unused bytes 12-15 will always be zero.

The general intent of the first group is to catch the case where all elements are functionally equal and therefore replacing it with `get_Zero` or `get_AllBitsSet` is possible and so future replacements can likewise take place, if appropriate (e.g. it might be better to optimize to be `broadcast` or `shuffle` in some cases, like `Clang` does).

In practice, it handles this for `argCnt == 1` by ensuring all elements are filled in here: https://github.com/dotnet/runtime/pull/47385/files#diff-8fe1c38ca575e327ad3227c06d009135287a438045cecbe3301d9a633a46cf0cR1465

However, I think it misses the mark when the args are explicitly defined or when `simdSize == 12` and so the logic here likely needs adjusting.
The bytewise comparison that was being done before also misses the mark on checking "are all elements the same"

Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp:1521]: Given this probably needs to be backported, it might be good to have a simple fix there and to have a slightly more complex fix for .NET 6+?

In particular, the logic to determine "are all elements equal?" could be put into the `HandleArgForHWIntrinsicCreate` logic here: https://github.com/dotnet/runtime/pull/47385/files#diff-8fe1c38ca575e327ad3227c06d009135287a438045cecbe3301d9a633a46cf0cR1430-R1470, so we aren't looping or checking values unnecessarily.

We could then trivially check:
```
if (allElementsEqual)
{
    if (allBitsZero)
    {
    }
    else if (allBitsSet)
    {
    }
    // future logic handling other cases
}
```

Thoughts?

File: src/coreclr/jit/lowerxarch.cpp [hunk 3]
```diff
@@ -1517,30 +1517,43 @@ void Lowering::LowerHWIntrinsicCreate(GenTreeHWIntrinsic* node)
...
-        if ((argCnt == 1) ||
-            ((vecCns.i64[0] == vecCns.i64[1]) && ((simdSize <= 16) || (vecCns.i64[2] == vecCns.i64[3]))))
-        {
-            // If we are a single constant or if all parts are the same, we might be able to optimize
-            // this even further for certain values, such as Zero or AllBitsSet.
-
-            if (vecCns.i64[0] == 0)
+        bool allBitsAreUnset        = true;
+        bool allBitsAreSet          = true;
+        int  i32ComponentsToInspect = argCnt == 1 ? 2 : simdSize / 4;
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:1522]: Should we assert that `simdSize % 4 == 0`?

Comment (EgorBo) [reply src/coreclr/jit/lowerxarch.cpp:1522]: yeah sure, I was about to comment on your feedback but wanted to fix the arm64 issue first which is unrelated to my changes but fails on CI on my new tests.

**Comment by EgorBo** [comment]
@tannergooding PTAL new approach, IMO should be the most transparent in case of back-porting.

**Review by tannergooding — APPROVED** [review]
This looks correct and like it matches the existing functionality without the bug minus the handling for `simdSize == 12` on x86 when all elements are `0`.

I think we want to visit this again for .NET 6 and better handle the intended use-case for this scenario and so we can ensure all the relevant sizes are handled.

**Comment by EgorBo** [comment]
@dotnet/jit-contrib PTAL and do we want to backport it?

**Comment by EgorBo** [comment]
@sandreenko does it look good?

File: src/coreclr/jit/lower.h [hunk 4]
```diff
@@ -348,6 +348,28 @@ class Lowering final : public Phase
...
+    //  Arguments:
+    //     vecCns  - Constant vector
+    //     count   - Amount of i64 components to compare
+    //
+    //  Returns:
+    //     true if N i64 elements of the given vector are equal
+    static bool VectorConstantIsBroadcastedI64(VectorConstant& vecCns, int count)
+    {
+        assert(count >= 1 && count <= 4);
+        for (int i = 0; i < count; i++)
```
Comment (sandreenko) [inline src/coreclr/jit/lower.h:363]: Nit:
```suggestion
        for (int i = 1; i < count; i++)
```

File: src/coreclr/jit/lowerarmarch.cpp [hunk 5]
```diff
@@ -969,25 +969,23 @@ void Lowering::LowerHWIntrinsicCreate(GenTreeHWIntrinsic* node)
 
         assert((simdSize == 8) || (simdSize == 16));
 
-        if ((argCnt == 1) || (simdSize == 8) || (vecCns.i64[0] == vecCns.i64[1]))
+        if (VectorConstantIsBroadcastedI64(vecCns, (argCnt == 1) ? argCnt : (simdSize / 8)))
```
Comment (sandreenko) [inline src/coreclr/jit/lowerarmarch.cpp:972]: Nit:
```suggestion
        if ((argCnt == 1) || VectorConstantIsBroadcastedI64(vecCns, simdSize / 8))
```

would it be wrong to always call `VectorConstantIsBroadcastedI64(vecCns, simdSize / 8)` for simplicity?

File: src/coreclr/jit/lowerxarch.cpp [hunk 6]
```diff
@@ -1517,26 +1517,24 @@ void Lowering::LowerHWIntrinsicCreate(GenTreeHWIntrinsic* node)
 
         assert((simdSize == 8) || (simdSize == 12) || (simdSize == 16) || (simdSize == 32));
 
-        if ((argCnt == 1) ||
-            ((vecCns.i64[0] == vecCns.i64[1]) && ((simdSize <= 16) || (vecCns.i64[2] == vecCns.i64[3]))))
+        if (((simdSize == 16) || (simdSize == 32)) &&
+            VectorConstantIsBroadcastedI64(vecCns, (argCnt == 1) ? argCnt : (simdSize / 8)))
```
Comment (sandreenko) [inline src/coreclr/jit/lowerxarch.cpp:1521]: same question, if `argCnt == 1` does not it mean `VectorConstantIsBroadcastedI64(vecCns, simdSize / 8)` returns true?

**Review by sandreenko — APPROVED** [review]
LGTM, few nits/questions.

File: src/coreclr/jit/lowerxarch.cpp (hunk 6 above)
Comment (EgorBo) [reply src/coreclr/jit/lowerxarch.cpp]: I've just checked - yeah we can omit argCnt==1 logic for simplicity here, thanks
