### PR TITLE
Convert non-blittable delegate usage in System.DirectoryServices to function pointers.

### LINKED ISSUE #65259: Disabling runtime marshaling broke DomainControllerTests.FindAll_NoSuchName_ReturnsEmpty()
```
     <test name="System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests.FindAll_NoSuchName_ReturnsEmpty" type="System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests" method="FindAll_NoSuchName_ReturnsEmpty" time="0.0115152" result="Fail">
        <failure exception-type="System.Runtime.InteropServices.MarshalDirectiveException">
          <message><![CDATA[System.Runtime.InteropServices.MarshalDirectiveException : Cannot marshal 'parameter #7': Cannot marshal managed types when the runtime marshalling system is disabled.]]></message>
          <stack-trace><![CDATA[   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointerInternal(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t) in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs:line 1122
   at System.DirectoryServices.ActiveDirectory.Utils.GetDNFromDnsName(String dnsName) in C:\git\runtime\src\libraries\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\Utils.cs:line 204
   at System.DirectoryServices.ActiveDirectory.DomainController.FindAllInternal(DirectoryContext context, String domainName, Boolean isDnsDomainName, String siteName) in C:\git\runtime\src\libraries\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DomainController.cs:line 1069
   at System.DirectoryServices.ActiveDirectory.DomainController.FindAll(DirectoryContext context) in C:\git\runtime\src\libraries\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DomainController.cs:line 259
   at System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests.FindAll_NoSuchName_ReturnsEmpty() in C:\git\runtime\src\libraries\System.DirectoryServices\tests\System\DirectoryServices\ActiveDirectory\DomainControllerTests.cs:line 121]]></stack-trace>
        </failure>
      </test>
```
https://github.com/dotnet/runtime/blob/a1f0147eb6cefaeff012879dbaf637297736ed3f/src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/Utils.cs#L204

It seems it cannot marshal this 
https://github.com/dotnet/runtime/blob/a1f0147eb6cefaeff012879dbaf637297736ed3f/src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/NativeMethods.cs#L494

This may have been an edit that was missed from #64279 perhaps because the codepath didn't exercise due to different network config. @jkoritzinsky can you advise here? Looking at the other changes you made, I'm unclear what is needed.

as an aside this code change seems like it should be made at the same time
```C#
-                NativeMethods.DsCrackNames dsCrackNames = Marshal.GetDelegateForFunctionPointer(functionPtr, typeof(NativeMethods.DsCrackNames));
+               NativeMethods.DsCrackNames dsCrackNames = Marshal.GetDelegateForFunctionPointer<NativeMethods.DsCrackNames>(functionPtr);
```
this is on CoreCLR `build clr+libs+libs.tests -rc release -lc debug -test`

### PR DESCRIPTION
**Pull request by jkoritzinsky**
All of the delegates used very simple marshalling and they were all used in one or two places immediately after a GetProcAddress call for them, so it seemed like it was worthwhile to go all the way to function pointers instead of just manually pinning the parameters and still allocating delegates.

Fixes #65259

@danmoseley is there a particular CI pipeline I can trigger to validate that the failing tests are passing now?

cc: @dotnet/interop-contrib

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ActiveDirectorySite.cs [hunk 1]
```diff
@@ -1302,16 +1302,18 @@ private void GetDomains()
 
                 IntPtr info = (IntPtr)0;
                 // call DsReplicaSyncAllW
-                IntPtr functionPtr = global::Interop.Kernel32.GetProcAddress(DirectoryContext.ADHandle, "DsListDomainsInSiteW");
-                if (functionPtr == (IntPtr)0)
+                var dsListDomainsInSiteW = (delegate* unmanaged<IntPtr, char*, IntPtr*, int>)global::Interop.Kernel32.GetProcAddress(DirectoryContext.ADHandle, "DsListDomainsInSiteW");
```
Comment (tannergooding) [inline src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ActiveDirectorySite.cs:1305]: Is it desirable that this is `IntPtr*` rather than `DS_NAME_RESULT*`?

What about `int` rather than `uint` (since its a `DWORD`)?

Comment (jkoritzinsky) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ActiveDirectorySite.cs:1305]: I wanted to match the existing delegate signatures to ensure I wouldn't have to add a ton of casts.

Comment (jkotas) [inline src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ActiveDirectorySite.cs:1305]: This library targets netstandard2.0. The default unmanaged calling convention is not supported for netstandard2.0. I think these needs to be explicit StdCall to make it work for netstandard2.0.

Comment (jkoritzinsky) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ActiveDirectorySite.cs:1305]: It looks like the `netstandard2.0` implementation is a PlatformNotSupported-stubbed out implementation, so it doesn't compile this code.

Comment (AaronRobinsonMSFT) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ActiveDirectorySite.cs:1305]: > It looks like the `netstandard2.0` implementation is a PlatformNotSupported-stubbed out implementation, so it doesn't compile this code.

That is good. I had thought that targeting `netstandard2.0` without stating the calling convention would result in a compiler error. Right?

Comment (jkoritzinsky) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ActiveDirectorySite.cs:1305]: Yep. The feature is conditionally available based on a RuntimeFeature field/property.
