### PR TITLE
Fix HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext

### LINKED ISSUE #112426: [8.0] [.NET Framework 4.8] [x86] System.Diagnostics HttpHandler test failure: Remote process failed with an unhandled exception
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=948105
Build error leg or test failing: System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeaders
Pull request: https://github.com/dotnet/runtime/pull/112381

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext [FAIL]", "Remote process failed with an unhandled exception."],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

- Log: https://helixr1107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-80-staging-8d0c495689284416bf/System.Diagnostics.DiagnosticSource.Tests/1/console.f9ee6957.log?helixlogtype=result
- Output:
```
===========================================================================================================

C:\h\w\A3E308EF\w\A0FF090D\e>xunit.console.exe System.Diagnostics.DiagnosticSource.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing  
  Discovering: System.Diagnostics.DiagnosticSource.Tests (app domain = on [no shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.DiagnosticSource.Tests (found 47 of 257 test cases)
  Starting:    System.Diagnostics.DiagnosticSource.Tests (parallel test collections = on, max threads = 2)

Unhandled Exception: Xunit.Sdk.NullException: Assert.Null() Failure
Expected: (null)
Actual:   |5c332e6c-4a6282b9037c78e1.
   at System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.<>c.<<TestW3CHeadersTraceStateAndCorrelationContext>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
    System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.NullException: Assert.Null() Failure
        Expected: (null)
        Actual:   |5c332e6c-4a6282b9037c78e1.
           at System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.<>c.<<TestW3CHeadersTraceStateAndCorrelationContext>b__6_0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
        
        Child process:
          System.Diagnostics.DiagnosticSource.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests+<>c System.Threading.Tasks.Task <TestW3CHeadersTraceStateAndCorrelationContext>b__6_0()
        
        

Unhandled Exception: Xunit.Sdk.EqualException: Assert.Equal() Failure
                                 ↓ (pos 41)
Expected: ···op.HttpRequestOut.Stop
Actual:   ···op.HttpRequestOut.Start
                                 ↑ (pos 41)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences)
   at System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.<>c.<<TestW3CHeaders>b__5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
    System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeaders [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.EqualException: Assert.Equal() Failure
                                         ↓ (pos 41)
        Expected: ···op.HttpRequestOut.Stop
        Actual:   ···op.HttpRequestOut.Start
                                         ↑ (pos 41)
           at System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.<>c.<<TestW3CHeaders>b__5_0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
        
        Child process:
          System.Diagnostics.DiagnosticSource.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests+<>c System.Threading.Tasks.Task <TestW3CHeaders>b__5_0()
```
- 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=948105
**Error message validated:** `[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext [FAIL] Remote process failed with an unhandled exception.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/11/2025 4:35:21 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[977058](https://dev.azure.com/dnceng-public/public/_build/results?buildId=977058)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=977058&view=ms.vss-test-web.build-test-results-tab&runId=26035542&resultId=100416)||
|[977079](https://dev.azure.com/dnceng-public/public/_build/results?buildId=977079)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=977079&view=ms.vss-test-web.build-test-results-tab&runId=26035524&resultId=100416)||
|[977054](https://dev.azure.com/dnceng-public/public/_build/results?buildId=977054)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=977054&view=ms.vss-test-web.build-test-results-tab&runId=26035522&resultId=100417)||
|[977063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=977063)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=977063&view=ms.vss-test-web.build-test-results-tab&runId=26035512&resultId=100407)||
|[975508](https://dev.azure.com/dnceng-public/public/_build/results?buildId=975508)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=975508&view=ms.vss-test-web.build-test-results-tab&runId=25998838&resultId=100417)||
|[975513](https://dev.azure.com/dnceng-public/public/_build/results?buildId=975513)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=975513&view=ms.vss-test-web.build-test-results-tab&runId=25998856&resultId=100416)||
|[975524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=975524)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=975524&view=ms.vss-test-web.build-test-results-tab&runId=25998848&resultId=100417)||
|[975520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=975520)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeaders](https://dev.azure.com/dnceng-public/public/_build/results?buildId=975520&view=ms.vss-test-web.build-test-results-tab&runId=25998832&resultId=100429)||
|[973846](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973846)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973846&view=ms.vss-test-web.build-test-results-tab&runId=25960868&resultId=100415)||
|[973858](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973858)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973858&view=ms.vss-test-web.build-test-results-tab&runId=25960828&resultId=100414)||
|[973847](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973847)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973847&view=ms.vss-test-web.build-test-results-tab&runId=25960764&resultId=100407)||
|[973836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973836)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973836&view=ms.vss-test-web.build-test-results-tab&runId=25960666&resultId=100396)||
|[973212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973212)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973212&view=ms.vss-test-web.build-test-results-tab&runId=25944376&resultId=100417)||
|[973208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973208)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973208&view=ms.vss-test-web.build-test-results-tab&runId=25944374&resultId=100416)||
|[973209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973209)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973209&view=ms.vss-test-web.build-test-results-tab&runId=25944320&resultId=100417)||
|[973194](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973194)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=973194&view=ms.vss-test-web.build-test-results-tab&runId=25944308&resultId=100416)||
|[972899](https://dev.azure.com/dnceng-public/public/_build/results?buildId=972899)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=972899&view=ms.vss-test-web.build-test-results-tab&runId=25930400&resultId=100416)||
|[972902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=972902)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=972902&view=ms.vss-test-web.build-test-results-tab&runId=25930390&resultId=100415)||
|[972892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=972892)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=972892&view=ms.vss-test-web.build-test-results-tab&runId=25930374&resultId=100416)||
|[972900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=972900)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=972900&view=ms.vss-test-web.build-test-results-tab&runId=25930370&resultId=100415)||
|[971728](https://dev.azure.com/dnceng-public/public/_build/results?buildId=971728)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=971728&view=ms.vss-test-web.build-test-results-tab&runId=25901236&resultId=100417)||
|[971724](https://dev.azure.com/dnceng-public/public/_build/results?buildId=971724)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=971724&view=ms.vss-test-web.build-test-results-tab&runId=25901234&resultId=100417)||
|[971716](https://dev.azure.com/dnceng-public/public/_build/results?buildId=971716)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=971716&view=ms.vss-test-web.build-test-results-tab&runId=25901210&resultId=100417)||
|[971713](https://dev.azure.com/dnceng-public/public/_build/results?buildId=971713)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=971713&view=ms.vss-test-web.build-test-results-tab&runId=25901202&resultId=100416)||
|[970636](https://dev.azure.com/dnceng-public/public/_build/results?buildId=970636)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=970636&view=ms.vss-test-web.build-test-results-tab&runId=25862998&resultId=100417)||
|[970624](https://dev.azure.com/dnceng-public/public/_build/results?buildId=970624)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=970624&view=ms.vss-test-web.build-test-results-tab&runId=25862974&resultId=100416)||
|[970612](https://dev.azure.com/dnceng-public/public/_build/results?buildId=970612)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=970612&view=ms.vss-test-web.build-test-results-tab&runId=25862922&resultId=100415)||
|[970608](https://dev.azure.com/dnceng-public/public/_build/results?buildId=970608)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=970608&view=ms.vss-test-web.build-test-results-tab&runId=25862910&resultId=100417)||
|[969482](https://dev.azure.com/dnceng-public/public/_build/results?buildId=969482)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=969482&view=ms.vss-test-web.build-test-results-tab&runId=25834828&resultId=100416)||
|[969480](https://dev.azure.com/dnceng-public/public/_build/results?buildId=969480)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=969480&view=ms.vss-test-web.build-test-results-tab&runId=25834808&resultId=100416)||
|[969484](https://dev.azure.com/dnceng-public/public/_build/results?buildId=969484)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=969484&view=ms.vss-test-web.build-test-results-tab&runId=25834788&resultId=100416)||
|[969468](https://dev.azure.com/dnceng-public/public/_build/results?buildId=969468)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=969468&view=ms.vss-test-web.build-test-results-tab&runId=25834792&resultId=100416)||
|[968438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=968438)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=968438&view=ms.vss-test-web.build-test-results-tab&runId=25808770&resultId=100416)||
|[968433](https://dev.azure.com/dnceng-public/public/_build/results?buildId=968433)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=968433&view=ms.vss-test-web.build-test-results-tab&runId=25808754&resultId=100416)||
|[968434](https://dev.azure.com/dnceng-public/public/_build/results?buildId=968434)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=968434&view=ms.vss-test-web.build-test-results-tab&runId=25808740&resultId=100417)||
|[968432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=968432)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=968432&view=ms.vss-test-web.build-test-results-tab&runId=25808732&resultId=100417)||
|[967338](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967338)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967338&view=ms.vss-test-web.build-test-results-tab&runId=25775882&resultId=100416)||
|[967318](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967318)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967318&view=ms.vss-test-web.build-test-results-tab&runId=25775804&resultId=100415)||
|[967334](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967334)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967334&view=ms.vss-test-web.build-test-results-tab&runId=25775800&resultId=100417)||
|[967311](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967311)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967311&view=ms.vss-test-web.build-test-results-tab&runId=25775784&resultId=100417)||
|[966643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966643)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966643&view=ms.vss-test-web.build-test-results-tab&runId=25757502&resultId=100416)||
|[966645](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966645)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966645&view=ms.vss-test-web.build-test-results-tab&runId=25757498&resultId=100416)||
|[966650](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966650)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966650&view=ms.vss-test-web.build-test-results-tab&runId=25757476&resultId=100417)||
|[966629](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966629)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966629&view=ms.vss-test-web.build-test-results-tab&runId=25757458&resultId=100417)||
|[966356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966356)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966356&view=ms.vss-test-web.build-test-results-tab&runId=25746348&resultId=100417)||
|[966350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966350)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966350&view=ms.vss-test-web.build-test-results-tab&runId=25746340&resultId=100417)||
|[966343](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966343)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966343&view=ms.vss-test-web.build-test-results-tab&runId=25746316&resultId=100416)||
|[966341](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966341)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=966341&view=ms.vss-test-web.build-test-results-tab&runId=25746314&resultId=100415)||
|[965560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=965560)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=965560&view=ms.vss-test-web.build-test-results-tab&runId=25727004&resultId=100415)||
|[965549](https://dev.azure.com/dnceng-public/public/_build/results?buildId=965549)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=965549&view=ms.vss-test-web.build-test-results-tab&runId=25726966&resultId=100417)||
|[965536](https://dev.azure.com/dnceng-public/public/_build/results?buildId=965536)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=965536&view=ms.vss-test-web.build-test-results-tab&runId=25726962&resultId=100469)||
|[965554](https://dev.azure.com/dnceng-public/public/_build/results?buildId=965554)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=965554&view=ms.vss-test-web.build-test-results-tab&runId=25726936&resultId=100416)||
|[964656](https://dev.azure.com/dnceng-public/public/_build/results?buildId=964656)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=964656&view=ms.vss-test-web.build-test-results-tab&runId=25702522&resultId=100417)||
|[964629](https://dev.azure.com/dnceng-public/public/_build/results?buildId=964629)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=964629&view=ms.vss-test-web.build-test-results-tab&runId=25702514&resultId=100417)||
|[964657](https://dev.azure.com/dnceng-public/public/_build/results?buildId=964657)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=964657&view=ms.vss-test-web.build-test-results-tab&runId=25702504&resultId=100415)||
|[964633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=964633)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=964633&view=ms.vss-test-web.build-test-results-tab&runId=25702502&resultId=100417)||
|[963589](https://dev.azure.com/dnceng-public/public/_build/results?buildId=963589)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=963589&view=ms.vss-test-web.build-test-results-tab&runId=25673794&resultId=100416)||
|[963588](https://dev.azure.com/dnceng-public/public/_build/results?buildId=963588)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=963588&view=ms.vss-test-web.build-test-results-tab&runId=25673784&resultId=100415)||
|[963601](https://dev.azure.com/dnceng-public/public/_build/results?buildId=963601)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=963601&view=ms.vss-test-web.build-test-results-tab&runId=25673782&resultId=100417)||
|[963577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=963577)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=963577&view=ms.vss-test-web.build-test-results-tab&runId=25673744&resultId=100417)||
|[962212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=962212)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=962212&view=ms.vss-test-web.build-test-results-tab&runId=25630038&resultId=100416)||
|[962201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=962201)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=962201&view=ms.vss-test-web.build-test-results-tab&runId=25630010&resultId=100417)||
|[962208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=962208)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=962208&view=ms.vss-test-web.build-test-results-tab&runId=25629978&resultId=100417)||
|[962200](https://dev.azure.com/dnceng-public/public/_build/results?buildId=962200)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=962200&view=ms.vss-test-web.build-test-results-tab&runId=25629968&resultId=100416)||
|[960929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960929)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960929&view=ms.vss-test-web.build-test-results-tab&runId=25585766&resultId=100417)||
|[960922](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960922)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeaders](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960922&view=ms.vss-test-web.build-test-results-tab&runId=25585738&resultId=100428)||
|[960915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960915)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960915&view=ms.vss-test-web.build-test-results-tab&runId=25585710&resultId=100417)||
|[960913](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960913)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960913&view=ms.vss-test-web.build-test-results-tab&runId=25585578&resultId=100417)||
|[960189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960189)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960189&view=ms.vss-test-web.build-test-results-tab&runId=25562648&resultId=100417)||
|[960184](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960184)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960184&view=ms.vss-test-web.build-test-results-tab&runId=25562622&resultId=100417)||
|[960173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960173)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960173&view=ms.vss-test-web.build-test-results-tab&runId=25562618&resultId=100416)||
|[960174](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960174)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=960174&view=ms.vss-test-web.build-test-results-tab&runId=25562612&resultId=100416)||
|[959807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=959807)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=959807&view=ms.vss-test-web.build-test-results-tab&runId=25550700&resultId=100417)||
|[959813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=959813)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=959813&view=ms.vss-test-web.build-test-results-tab&runId=25550696&resultId=100417)||
|[959818](https://dev.azure.com/dnceng-public/public/_build/results?buildId=959818)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=959818&view=ms.vss-test-web.build-test-results-tab&runId=25550676&resultId=100415)||
|[959814](https://dev.azure.com/dnceng-public/public/_build/results?buildId=959814)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=959814&view=ms.vss-test-web.build-test-results-tab&runId=25550664&resultId=100416)||
|[958840](https://dev.azure.com/dnceng-public/public/_build/results?buildId=958840)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=958840&view=ms.vss-test-web.build-test-results-tab&runId=25519166&resultId=100415)||
|[958827](https://dev.azure.com/dnceng-public/public/_build/results?buildId=958827)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeaders](https://dev.azure.com/dnceng-public/public/_build/results?buildId=958827&view=ms.vss-test-web.build-test-results-tab&runId=25519134&resultId=100430)||
|[958817](https://dev.azure.com/dnceng-public/public/_build/results?buildId=958817)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=958817&view=ms.vss-test-web.build-test-results-tab&runId=25519110&resultId=100415)||
|[958824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=958824)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=958824&view=ms.vss-test-web.build-test-results-tab&runId=25519102&resultId=100424)||
|[957722](https://dev.azure.com/dnceng-public/public/_build/results?buildId=957722)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=957722&view=ms.vss-test-web.build-test-results-tab&runId=25486298&resultId=100417)||
|[957725](https://dev.azure.com/dnceng-public/public/_build/results?buildId=957725)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=957725&view=ms.vss-test-web.build-test-results-tab&runId=25486290&resultId=100417)||
|[957720](https://dev.azure.com/dnceng-public/public/_build/results?buildId=957720)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=957720&view=ms.vss-test-web.build-test-results-tab&runId=25486256&resultId=100417)||
|[957704](https://dev.azure.com/dnceng-public/public/_build/results?buildId=957704)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=957704&view=ms.vss-test-web.build-test-results-tab&runId=25486228&resultId=100417)||
|[956372](https://dev.azure.com/dnceng-public/public/_build/results?buildId=956372)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=956372&view=ms.vss-test-web.build-test-results-tab&runId=25451626&resultId=100417)||
|[956362](https://dev.azure.com/dnceng-public/public/_build/results?buildId=956362)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=956362&view=ms.vss-test-web.build-test-results-tab&runId=25451610&resultId=100416)||
|[956361](https://dev.azure.com/dnceng-public/public/_build/results?buildId=956361)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=956361&view=ms.vss-test-web.build-test-results-tab&runId=25451602&resultId=100417)||
|[956364](https://dev.azure.com/dnceng-public/public/_build/results?buildId=956364)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=956364&view=ms.vss-test-web.build-test-results-tab&runId=25451608&resultId=100416)||
|[955171](https://dev.azure.com/dnceng-public/public/_build/results?buildId=955171)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=955171&view=ms.vss-test-web.build-test-results-tab&runId=25411168&resultId=100415)||
|[955150](https://dev.azure.com/dnceng-public/public/_build/results?buildId=955150)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=955150&view=ms.vss-test-web.build-test-results-tab&runId=25411136&resultId=100417)||
|[955168](https://dev.azure.com/dnceng-public/public/_build/results?buildId=955168)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=955168&view=ms.vss-test-web.build-test-results-tab&runId=25411146&resultId=100416)||
|[955161](https://dev.azure.com/dnceng-public/public/_build/results?buildId=955161)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=955161&view=ms.vss-test-web.build-test-results-tab&runId=25411134&resultId=100417)||
|[954421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954421)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeaders](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954421&view=ms.vss-test-web.build-test-results-tab&runId=25383714&resultId=100430)||
|[954422](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954422)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954422&view=ms.vss-test-web.build-test-results-tab&runId=25383716&resultId=100416)||
|[954415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954415)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954415&view=ms.vss-test-web.build-test-results-tab&runId=25383676&resultId=100415)||
|[954405](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954405)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954405&view=ms.vss-test-web.build-test-results-tab&runId=25383672&resultId=100417)||
|[953880](https://dev.azure.com/dnceng-public/public/_build/results?buildId=953880)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=953880&view=ms.vss-test-web.build-test-results-tab&runId=25365524&resultId=100417)||
|[953871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=953871)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=953871&view=ms.vss-test-web.build-test-results-tab&runId=25365518&resultId=100417)||
|[953881](https://dev.azure.com/dnceng-public/public/_build/results?buildId=953881)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=953881&view=ms.vss-test-web.build-test-results-tab&runId=25365486&resultId=100417)||
|[953864](https://dev.azure.com/dnceng-public/public/_build/results?buildId=953864)|dotnet/runtime|[System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestW3CHeadersTraceStateAndCorrelationContext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=953864&view=ms.vss-test-web.build-test-results-tab&runId=25365454&resultId=100415)||
Displaying 100 of 117 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|28|112|

### PR DESCRIPTION
**Pull request by antonfirsov**
It's unclear to me how did this test pass before, but given it's testing W3C tracestate format behavior on .NET Framework, `ActivityIdFormat.W3C` should be explicitly set as `DefaultIdFormat` in the test. This will ensure that the `Request-Id` header (that is specific to the Hierarchical format) will be absent, making the last Assert pass.

Fixes #112426

### CODE REVIEW

**Comment by tarekgh** [comment]
@antonfirsov the issue https://github.com/dotnet/runtime/issues/112426 is opened against .NET 8.0. This PR will force closing the issue which will make the failure still show in .NET 8 builds. Will you port this fix to 8.0 and possibly 9.0? 

CC @noahfalk

**Review by tarekgh — APPROVED** [review]

**Comment by antonfirsov** [comment]
> Will you port this fix to 8.0 and possibly 9.0?

Sure, thanks for the heads-up!

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/HttpHandlerDiagnosticListenerTests.cs [hunk 1]
```diff
@@ -145,6 +145,7 @@ public async Task TestBasicReceiveAndResponseEvents()
             }
         }
 
+        [ActiveIssue("https://github.com/dotnet/runtime/issues/112792")]
```
Comment (antonfirsov) [inline src/libraries/System.Diagnostics.DiagnosticSource/tests/HttpHandlerDiagnosticListenerTests.cs:148]: I almost missed that this test is also failing. It seems to be a [product bug](https://github.com/dotnet/runtime/issues/112792), disabling for now. cc @tarekgh in case you have concerns.

**Comment by antonfirsov** [comment]
/ba-g unrelated test failures reported in #112837
