### PR TITLE
Fix inconsistent newline format when logging exceptions to console.

### LINKED ISSUE #114579: The Android logging support has broken a diagnostics exception handling test
The change #113416 has broken the UnhandledExceptionTest in the dotnet diagnostic tests. It looks like the test can see added extra newlines in the unhandled exception stack trace dumped to the console. The test verifies that the output matches an expected result and it fails due to that.
Interestingly, when the output is printed to console, there are no extra newlines, it only happens when the output is redirected. Even redirecting to a file causes this problem.

### PR DESCRIPTION
**Pull request by lateralusX**
The introduction of `minipal_log_write` API's have flushed out some inconsistency in newline format used on Windows. Previously the Windows implementation logged exceptions to console using `WriteFile` together with `STD_ERR_HANDLE`. It turns out that the file mode of this handle is binary, while the file mode for regular stdout/stderr is text mode. `minipal_log_write` API uses underlying _write instead of `WriteFile` and the fd associated with stdout/stderr, but since they are in text mode, pre-formatted data intended for binary output will expand `\r\n` to `\r\r\n` that could cause side effects due to additional `\r` character in the stream. The use of `WriteFile` handled this case, but we also mixed regular `\n` using the same API, that won't be expanded to `\r\n` when written to a file in binary mode leaving us with output using different line endings through the same logging.

Normally all logging performed from native code use `\n` and expects it to be replaced to `\r\n` on Windows as part of logging through a file in text mode. Some data formatted in managed code intended for output is already pre-formatted, using `\r\n`, intended for files in binary mode. One area where we mix line ending formats is the logging of unhandled exception call stacks, where we currently mix formatted newlines `\r\n` with `\n`.

This fix implement support in `minipal_log_write` to detect if logging should go through binary file mode on Windows, and since this is the default on none Windows platforms its a noop on all other platforms. Since we already needed to take strlen in minipal_log_write, the fix integrate logic to also check for \r\n pattern while calculating the length, leading to no additional pass over the string to detect if a logging needs to go into binary mode instead of default mode..

Fixes https://github.com/dotnet/runtime/issues/114579

### CODE REVIEW

**Comment by lateralusX** [comment]
Looking into taking this fix closer to minipal_log_write internals, stay tuned.

File: src/native/minipal/log.c [hunk 1]
```diff
@@ -280,25 +293,47 @@ static int sync_file(minipal_log_flags flags)
...
-    size_t bytes_to_write = strlen(msg);
+    size_t bytes_to_write = 0;
     size_t bytes_written = 0;
 
-    int fd = fileno(get_std_file(flags));
+    write_file_fnptr write_fnptr = write_file;
+
+#ifdef HOST_WINDOWS
+    const char* msg_char = msg;
+    while (*msg_char)
```
Comment (janvorli) [inline src/native/minipal/log.c:317]: A nit - you can use `msg_char = strstr(msg, "\r\n")` for a shorter code

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

File: src/native/minipal/log.c (hunk 1 above)
Comment (lateralusX) [reply src/native/minipal/log.c:317]: Its actually intentional to take strlen as well as check for the pattern in one loop over the string. If we used strstrs we would need to do strlen as well, meaning two passes over the string, so this does both in one pass.

File: src/native/minipal/log.c [hunk 2]
```diff
@@ -224,33 +224,46 @@ void minipal_log_flush_all(void)
...
-static int sync_file(minipal_log_flags flags)
+static HANDLE get_std_handle(minipal_log_flags flags)
 {
     switch(flags)
     {
     case minipal_log_flags_fatal:
     case minipal_log_flags_error:
-        FlushFileBuffers(GetStdHandle(STD_ERROR_HANDLE));
+        return GetStdHandle(STD_ERROR_HANDLE);
         break;
```
Comment (jkotas) [inline src/native/minipal/log.c:234]:
```suggestion
```

File: src/native/minipal/log.c [hunk 3]
```diff
@@ -224,33 +224,46 @@ void minipal_log_flush_all(void)
...
     case minipal_log_flags_warning:
     case minipal_log_flags_info:
     case minipal_log_flags_debug:
     case minipal_log_flags_verbose:
     default:
-        FlushFileBuffers(GetStdHandle(STD_OUTPUT_HANDLE));
+        return GetStdHandle(STD_OUTPUT_HANDLE);
         break;
```
Comment (jkotas) [inline src/native/minipal/log.c:241]:
```suggestion
```

File: src/native/minipal/log.c [hunk 4]
```diff
@@ -224,33 +224,46 @@ void minipal_log_flush_all(void)
...
     case minipal_log_flags_fatal:
     case minipal_log_flags_error:
-        FlushFileBuffers(GetStdHandle(STD_ERROR_HANDLE));
+        return GetStdHandle(STD_ERROR_HANDLE);
         break;
     case minipal_log_flags_warning:
     case minipal_log_flags_info:
     case minipal_log_flags_debug:
     case minipal_log_flags_verbose:
     default:
```
Comment (jkotas) [inline src/native/minipal/log.c:239]:
```suggestion
```

**Comment by lateralusX** [comment]
Looks like the failure in NET481 happened on other PR\s as well, https://[helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-114783-merge-677c12ce065b4a5b86/System.Net.Http.WinHttpHandler.Functional.Tests/3/console.24750079.log?helixlogtype=result](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-114783-merge-677c12ce065b4a5b86/System.Net.Http.WinHttpHandler.Functional.Tests/3/console.24750079.log?helixlogtype=result)

**Comment by lateralusX** [comment]
So if we end up with that as the only failure blocking build analysis, I think we can override and merge.

**Review by janvorli — APPROVED** [review]

**Comment by lateralusX** [comment]
/ba-g Failing test has been fixed here, https://github.com/dotnet/runtime/issues/114790.
