### PR TITLE
Fix: Assert failure: Thread::IsObjRefValid

### LINKED ISSUE #117961: System.ComponentModel.TypeConverter.Tests.WorkItemExecution failure
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1102173
Build error leg or test failing: System.ComponentModel.TypeConverter.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/117684

```
Assert failure(PID 6296 [0x00001898], Thread: 3876 [0x0f24]): Thread::IsObjRefValid(&objref)

CORECLR! OBJECTREF::operator= + 0x3D (0x730cbde5)
CORECLR! RuntimeMethodHandle_InvokeMethod + 0x826 (0x732c1b06)
<no module>! <no symbol> + 0x0 (0x0bf8f4cf)
<no module>! <no symbol> + 0x0 (0x0bfa2824)
<no module>! <no symbol> + 0x0 (0x0d6c813c)
<no module>! <no symbol> + 0x0 (0x0bf81a37)
<no module>! <no symbol> + 0x0 (0x0bead71e)
<no module>! <no symbol> + 0x0 (0x0d5c8a03)
<no module>! <no symbol> + 0x0 (0x0f88e87b)
<no module>! <no symbol> + 0x0 (0x0f88e683)
    File: D:\a\_work\1\s\src\coreclr\vm\object.cpp:1265
    Image: C:\h\w\A4360949\p\dotnet.exe
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Assert failure.*: Thread::IsObjRefValid",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102173
**Error message validated:** `[Assert failure.*: Thread::IsObjRefValid`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/23/2025 12:51:54 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1102173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102173)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102173&view=ms.vss-test-web.build-test-results-tab&runId=30181624&resultId=219772)|dotnet/runtime#117684|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1111849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111849)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111849&view=ms.vss-test-web.build-test-results-tab&runId=30534824&resultId=220018)|dotnet/runtime#118301|
|[1112282](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112282)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112282&view=ms.vss-test-web.build-test-results-tab&runId=30533944&resultId=220088)|dotnet/runtime#118241|
|[1112079](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112079)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112079&view=ms.vss-test-web.build-test-results-tab&runId=30526322&resultId=220018)|dotnet/runtime#118304|
|[1112063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112063)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112063&view=ms.vss-test-web.build-test-results-tab&runId=30525844&resultId=220018)|dotnet/runtime#118303|
|[1112022](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112022)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1112022&view=ms.vss-test-web.build-test-results-tab&runId=30524546&resultId=220018)|dotnet/runtime#118165|
|[1111964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111964)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111964&view=ms.vss-test-web.build-test-results-tab&runId=30523496&resultId=220018)|dotnet/runtime#118295|
|[1111734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111734)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111734&view=ms.vss-test-web.build-test-results-tab&runId=30516676&resultId=220018)|dotnet/runtime#117398|
|[1111637](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111637)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111637&view=ms.vss-test-web.build-test-results-tab&runId=30514074&resultId=220018)|dotnet/runtime#118282|
|[1111621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111621)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111621&view=ms.vss-test-web.build-test-results-tab&runId=30513836&resultId=220018)|dotnet/runtime#118291|
|[1111484](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111484)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111484&view=ms.vss-test-web.build-test-results-tab&runId=30508856&resultId=220018)|dotnet/runtime#118277|
|[1111448](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111448)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111448&view=ms.vss-test-web.build-test-results-tab&runId=30508274&resultId=220018)|dotnet/runtime#118180|
|[1111415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111415)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111415&view=ms.vss-test-web.build-test-results-tab&runId=30507218&resultId=220018)|dotnet/runtime#118280|
|[1111381](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111381)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111381&view=ms.vss-test-web.build-test-results-tab&runId=30506072&resultId=220018)|dotnet/runtime#118277|
|[1111154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111154)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111154&view=ms.vss-test-web.build-test-results-tab&runId=30497700&resultId=220018)|dotnet/runtime#116359|
|[1111137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111137)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111137&view=ms.vss-test-web.build-test-results-tab&runId=30496592&resultId=220018)|dotnet/runtime#118270|
|[1111001](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111001)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1111001&view=ms.vss-test-web.build-test-results-tab&runId=30490942&resultId=220018)|dotnet/runtime#118060|
|[1110943](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110943)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110943&view=ms.vss-test-web.build-test-results-tab&runId=30488634&resultId=220018)|dotnet/runtime#118249|
|[1110767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110767)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110767&view=ms.vss-test-web.build-test-results-tab&runId=30484044&resultId=220018)|dotnet/runtime#118027|
|[1110637](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110637)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1110637&view=ms.vss-test-web.build-test-results-tab&runId=30481056&resultId=220018)|dotnet/runtime#118037|
|[1109939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109939)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109939&view=ms.vss-test-web.build-test-results-tab&runId=30456946&resultId=220008)|dotnet/runtime#118037|
|[1109830](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109830)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109830&view=ms.vss-test-web.build-test-results-tab&runId=30453512&resultId=219992)|dotnet/runtime#118214|
|[1109787](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109787)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109787&view=ms.vss-test-web.build-test-results-tab&runId=30451878&resultId=219984)|dotnet/runtime#118037|
|[1109404](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109404)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109404&view=ms.vss-test-web.build-test-results-tab&runId=30441510&resultId=219984)|dotnet/runtime#118206|
|[1109177](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109177)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109177&view=ms.vss-test-web.build-test-results-tab&runId=30427202&resultId=219984)|dotnet/runtime#118194|
|[1108991](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108991)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108991&view=ms.vss-test-web.build-test-results-tab&runId=30419354&resultId=220023)|dotnet/runtime#118190|
|[1108962](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108962)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108962&view=ms.vss-test-web.build-test-results-tab&runId=30418900&resultId=219984)|dotnet/runtime#118183|
|[1108811](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108811)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108811&view=ms.vss-test-web.build-test-results-tab&runId=30413894&resultId=219984)|dotnet/runtime#118183|
|[1108738](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108738)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108738&view=ms.vss-test-web.build-test-results-tab&runId=30411990&resultId=219984)|dotnet/runtime#118178|
|[1108628](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108628)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108628&view=ms.vss-test-web.build-test-results-tab&runId=30405940&resultId=219984)|dotnet/runtime#116539|
|[1108551](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108551)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108551&view=ms.vss-test-web.build-test-results-tab&runId=30402510&resultId=219984)|dotnet/runtime#118154|
|[1107973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107973)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107973&view=ms.vss-test-web.build-test-results-tab&runId=30380164&resultId=219983)|dotnet/runtime#118140|
|[1107625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107625)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107625&view=ms.vss-test-web.build-test-results-tab&runId=30367878&resultId=219983)|dotnet/runtime#118101|
|[1107592](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107592)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107592&view=ms.vss-test-web.build-test-results-tab&runId=30367162&resultId=219983)|dotnet/runtime#118048|
|[1107459](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107459)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107459&view=ms.vss-test-web.build-test-results-tab&runId=30363490&resultId=219983)|dotnet/runtime#118078|
|[1107118](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107118)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107118&view=ms.vss-test-web.build-test-results-tab&runId=30347574&resultId=219983)|dotnet/runtime#117593|
|[1107077](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107077)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1107077&view=ms.vss-test-web.build-test-results-tab&runId=30346546&resultId=219983)|dotnet/runtime#118101|
|[1106925](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106925)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106925&view=ms.vss-test-web.build-test-results-tab&runId=30339970&resultId=209478)|dotnet/runtime#118101|
|[1106912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106912)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106912&view=ms.vss-test-web.build-test-results-tab&runId=30339248&resultId=219969)||
|[1106740](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106740)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106740&view=ms.vss-test-web.build-test-results-tab&runId=30333546&resultId=219983)|dotnet/runtime#118045|
|[1106679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106679)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106679&view=ms.vss-test-web.build-test-results-tab&runId=30331018&resultId=219967)||
|[1106507](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106507)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106507&view=ms.vss-test-web.build-test-results-tab&runId=30324854&resultId=219981)|dotnet/runtime#118045|
|[1106415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106415)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106415&view=ms.vss-test-web.build-test-results-tab&runId=30322222&resultId=219981)|dotnet/runtime#118078|
|[1106378](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106378)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106378&view=ms.vss-test-web.build-test-results-tab&runId=30321320&resultId=219981)|dotnet/runtime#118077|
|[1106366](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106366)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106366&view=ms.vss-test-web.build-test-results-tab&runId=30321066&resultId=219981)|dotnet/runtime#118020|
|[1106281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106281)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1106281&view=ms.vss-test-web.build-test-results-tab&runId=30319322&resultId=219981)|dotnet/runtime#117868|
|[1105955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105955)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105955&view=ms.vss-test-web.build-test-results-tab&runId=30309300&resultId=219968)|dotnet/runtime#118020|
|[1105838](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105838)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105838&view=ms.vss-test-web.build-test-results-tab&runId=30305974&resultId=219968)|dotnet/runtime#117980|
|[1105787](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105787)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105787&view=ms.vss-test-web.build-test-results-tab&runId=30303764&resultId=219968)|dotnet/runtime#118020|
|[1105309](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105309)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105309&view=ms.vss-test-web.build-test-results-tab&runId=30288962&resultId=219968)|dotnet/runtime#118046|
|[1105233](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105233)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105233&view=ms.vss-test-web.build-test-results-tab&runId=30285920&resultId=219968)|dotnet/runtime#118020|
|[1105083](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105083)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105083&view=ms.vss-test-web.build-test-results-tab&runId=30281540&resultId=219954)||
|[1105001](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105001)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1105001&view=ms.vss-test-web.build-test-results-tab&runId=30278784&resultId=219968)|dotnet/runtime#117837|
|[1104886](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1104886)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1104886&view=ms.vss-test-web.build-test-results-tab&runId=30274824&resultId=219968)|dotnet/runtime#117991|
|[1104415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1104415)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1104415&view=ms.vss-test-web.build-test-results-tab&runId=30255204&resultId=220752)|dotnet/runtime#118011|
|[1103496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1103496)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1103496&view=ms.vss-test-web.build-test-results-tab&runId=30222656&resultId=219966)|dotnet/runtime#116383|
|[1102489](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102489)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102489&view=ms.vss-test-web.build-test-results-tab&runId=30216870&resultId=219772)|dotnet/runtime#117727|
|[1102078](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102078)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102078&view=ms.vss-test-web.build-test-results-tab&runId=30212470&resultId=219772)|dotnet/runtime#117885|
|[1102859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102859)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102859&view=ms.vss-test-web.build-test-results-tab&runId=30211678&resultId=219772)|dotnet/runtime#117960|
|[1102985](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102985)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102985&view=ms.vss-test-web.build-test-results-tab&runId=30211074&resultId=219951)||
|[1102877](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102877)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102877&view=ms.vss-test-web.build-test-results-tab&runId=30204880&resultId=218771)|dotnet/runtime#117965|
|[1102844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102844)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102844&view=ms.vss-test-web.build-test-results-tab&runId=30202866&resultId=219771)|dotnet/runtime#117949|
|[1102810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102810)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102810&view=ms.vss-test-web.build-test-results-tab&runId=30201578&resultId=219772)|dotnet/runtime#117845|
|[1102776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102776)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102776&view=ms.vss-test-web.build-test-results-tab&runId=30200024&resultId=219772)|dotnet/runtime#108655|
|[1102484](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102484)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102484&view=ms.vss-test-web.build-test-results-tab&runId=30197668&resultId=219772)|dotnet/runtime#117945|
|[1102265](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102265)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102265&view=ms.vss-test-web.build-test-results-tab&runId=30184612&resultId=219772)|dotnet/runtime#117797|
|[1102173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102173)|dotnet/runtime|[System.ComponentModel.TypeConverter.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1102173&view=ms.vss-test-web.build-test-results-tab&runId=30181624&resultId=219772)|dotnet/runtime#117684|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|38|66|

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #117961

### CODE REVIEW

File: src/coreclr/vm/reflectioninvocation.cpp [hunk 1]
```diff
@@ -617,7 +617,7 @@ extern "C" void QCALLTYPE RuntimeMethodHandle_InvokeMethod(
         // We have a special case for Strings...The object is returned...
         if (fCtorOfVariableSizedObject) {
             PVOID pReturnValue = &callDescrData.returnValue;
-            gc.retVal = *(OBJECTREF *)pReturnValue;
+            gc.retVal = ObjectToOBJECTREF(*(Object**)pReturnValue);
```
Comment (jkotas) [inline src/coreclr/vm/reflectioninvocation.cpp:620]: Apply recommended fix from 
https://github.com/dotnet/runtime/blob/215a79a3f37a3afec0ac2c418b6fbeacb26e1585/src/coreclr/vm/object.cpp#L1135-L1136

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/vm/reflectioninvocation.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/reflectioninvocation.cpp:620]: Should we search the codebase for these pattern? `*(OBJECTREF*)` and `*(OBJECTREF *)`.

I see candidates in `comtoclrcall.cpp` in `InvokeStub()` and `CLRToCOMEventCallWorker()`. Something suspect in `EEDbgInterfaceImpl::GetObjectFromHandle()`. `CopyOBJECTREFToStack()` in `callsiteinspect.cpp` has two. In `interpexec.cpp`, there is something to consider under `INTOP_LDELEM_REF`.
