### PR TITLE
Fix null reference handling in VSD stub for x86

### LINKED ISSUE #35188: Test failure: Regressions\\coreclr\\GitHub_35000\\test35000\\test35000.cmd
failed in job: [runtime-coreclr outerloop 20200419.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=607697&view=ms.vss-test-web.build-test-results-tab&runId=19093218&resultId=110452&paneView=debug)

Error message
~~~
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at Test35000.<>c__DisplayClass2_0`2.<CreateFunc>b__0(Object o) in F:\workspace\_work\1\s\src\coreclr\tests\src\Regressions\coreclr\GitHub_35000\test35000.cs:line 56
Return code: 1
Raw output file: C:\h\w\CB590A31\w\9D1408DE\e\Regressions\coreclr\Reports\Regressions.coreclr\GitHub_35000\test35000\test35000.output.txt
Raw output:
BEGIN EXECUTION
1 file(s) copied.
" "C:\h\w\CB590A31\p\crossgen.exe" /Platform_Assemblies_Paths C:\h\w\CB590A31\p;C:\h\w\CB590A31\w\9D1408DE\e\Regressions\coreclr\GitHub_35000\test35000 /in C:\h\w\CB590A31\w\9D1408DE\e\Regressions\coreclr\GitHub_35000\test35000\test35000.org /out C:\h\w\CB590A31\w\9D1408DE\e\Regressions\coreclr\GitHub_35000\test35000\\test35000.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation. All rights reserved.
Native image C:\h\w\CB590A31\w\9D1408DE\e\Regressions\coreclr\GitHub_35000\test35000\\test35000.dll generated successfully.
"C:\h\w\CB590A31\p\corerun.exe" test35000.dll 
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\CB590A31\p
> C:\h\w\CB590A31\w\9D1408DE\e\Regressions\coreclr\GitHub_35000\test35000\test35000.cmd
Expected: True
Actual: False


Stack trace
   at Regressions_coreclr._GitHub_35000_test35000_test35000_._GitHub_35000_test35000_test35000_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\Regressions.coreclr\Regressions.coreclr.XUnitWrapper.cs:line 7221
~~~

### PR DESCRIPTION
**Pull request by janvorli**
The regression test that I've added recently to accompany a fix for null
reference handling in VSD stub for x64 is failing for x86. The problem
is that the null reference handling in VSD dispatch and resolve stubs
was broken in another way due to the x86 calling convention. When the
call went through a shuffle thunk that removes one stack argument due to
the shuffle, the manual unwinding in AdjustContextForVirtualStub was
getting an ESP that was off by one stack slot and exception handling
wasn't able to correctly unwind from that location to the caller.

This change fixes it by letting the AdjustContextForVirtualStub manually
unwind to the instruction after the call to the shuffle thunk / VSD stub
and updating the ESP according to the number of stack arguments of the
target method.

I have also modified the regression test. One change was to make a call
with multiple parameters to verify that the logic to get stack arguments
size is working correctly. Another change was to make sure that both
dispatch and resolve stub cases are tested.

Close #35188

### CODE REVIEW

File: src/coreclr/src/vm/virtualcallstub.cpp [hunk 1]
```diff
@@ -1914,7 +1914,11 @@ PCODE VirtualCallStubManager::ResolveWorker(StubCallSite* pCallSite,
                         {
                             pResolveHolder = GenerateResolveStub(pResolverFcn,
                                                              pBackPatchFcn,
-                                                             token.To_SIZE_T());
+                                                             token.To_SIZE_T()
+#ifdef TARGET_X86
+                                                             , objectType
```
Comment (jkotas) [inline src/coreclr/src/vm/virtualcallstub.cpp:1919]: Does the `objectType` have the right lifetime? Can the resolve stub outlive it?

(Look for `bCallToShorterLivedTarget` above for some context.)

Comment (janvorli) [reply src/coreclr/src/vm/virtualcallstub.cpp:1919]: Thank you for pointing it out, it seems it can happen. It seems that I can fix that by storing the stack arguments size in the stub instead of the MethodTable for the resolve stub.

Comment (janvorli) [reply src/coreclr/src/vm/virtualcallstub.cpp]: I've just pushed a commit that replaces the usage of MethodTable by the size of stack arguments in the ResolveStub.

File: src/coreclr/src/vm/i386/virtualcallstubcpu.hpp [hunk 2]
```diff
@@ -329,6 +331,7 @@ struct ResolveStub
     DISPL _backpatcherDispl;        // xx xx xx xx          backpatcherWorker  == BackPatchWorkerAsmStub
     BYTE  part11 [1];               // eb           jmp
     BYTE toResolveStub;             // xx                   resolveStub, i.e. go back to _resolveEntryPoint
+    size_t _stackArgumentsSize;     // xx xx xx xx
```
Comment (jkotas) [inline src/coreclr/src/vm/i386/virtualcallstubcpu.hpp:334]: Should all this be under `#ifndef UNIX_X86_ABI` ?

Comment (janvorli) [reply src/coreclr/src/vm/i386/virtualcallstubcpu.hpp:334]: You are right, I've forgotten that on x86 Linux we use caller side stack arguments cleanup.

**Review by jkotas — APPROVED** [review]
