### PR TITLE
Fix JitStackChecks failures

### LINKED ISSUE #74280: Test failures with COMPlus_JitStackChecks=1
win-x86

`COMPlus_JitStackChecks=1` checks that SP is the same before returning that it was on entry. It is failing in a few Interop tests:

(also, set `COMPlus_TieredCompilation=0`)

Interop\DisabledRuntimeMarshalling\DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled\DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.dll

```
0337E298 05c74bf5 (MethodDesc 09206e78 + 0x85 DisabledRuntimeMarshalling.PInvokeAssemblyMarshallingEnabled.DelegatesFromExternalAssembly.StructWithDefaultNonBlittableFields())
0337E2E0 05c74aad (MethodDesc 08fe8bd0 + 0x1d Program.<Main>$(System.String[])), calling (MethodDesc 09206e78 + 0 DisabledRuntimeMarshalling.PInvokeAssemblyMarshallingEnabled.DelegatesFromExternalAssembly.StructWithDefaultNonBlittableFields())
0337E300 5d6855c1 coreclr!CallDescrWorkerInternal + 0x34
0337E30C 5d0ed557 coreclr!CallDescrWorker + 0xd7 [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:123], calling coreclr!CallDescrWorkerInternal
0337E734 5d0ed7cc coreclr!CallDescrWorkerWithHandler + 0x1bc [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:69], calling coreclr!CallDescrWorker [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:78]
0337E7BC 5cc50fe1 coreclr!GetThread + 0x51 [C:\gh\runtime\src\coreclr\vm\threads.inl:45], calling coreclr!_RTC_CheckEsp [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\rtc\stack.cpp:21]
0337E7C4 5d0ed690 coreclr!CallDescrWorkerWithHandler + 0x80 [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:65], calling coreclr!_alloca_probe_16 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\misc\i386\alloca16.asm:44]
0337E810 5d0ee1dd coreclr!MethodDescCallSite::CallTargetWorker + 0x98d [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:565], calling coreclr!CallDescrWorkerWithHandler [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:54]
0337E860 5d0edede coreclr!MethodDescCallSite::CallTargetWorker + 0x68e [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:376], calling coreclr!_alloca_probe_16 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\misc\i386\alloca16.asm:44]
0337EC10 5cc86acf coreclr!MethodDescCallSite::Call_RetArgSlot + 0xef [C:\gh\runtime\src\coreclr\vm\callhelpers.h:458], calling coreclr!MethodDescCallSite::CallTargetWorker [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:260]
0337ECC4 5cc94cf5 coreclr!RunMainInternal + 0x1e5 [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1367], calling coreclr!MethodDescCallSite::Call_RetArgSlot [C:\gh\runtime\src\coreclr\vm\callhelpers.h:458]
0337EDB8 5cc94645 coreclr!``RunMain'::`29'::__Body::Run'::`5'::__Body::Run + 0x75 [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1437], calling coreclr!RunMainInternal [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1335]
0337EDE4 5cc62b21 coreclr!Thread::PreemptiveGCDisabled + 0x41 [C:\gh\runtime\src\coreclr\vm\threads.h:1838], calling coreclr!Volatile<unsigned long>::LoadWithoutBarrier [C:\gh\runtime\src\coreclr\inc\volatile.h:381]
0337EDFC 5cc94797 coreclr!`RunMain'::`29'::__Body::Run + 0xa7 [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1437], calling coreclr!``RunMain'::`29'::__Body::Run'::`5'::__Body::Run [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1433]
0337EE78 5cc949ee coreclr!RunMain + 0x15e [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1437], calling coreclr!`RunMain'::`29'::__Body::Run [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1433]
0337EF14 5cc8ad95 coreclr!Assembly::ExecuteMainMethod + 0x455 [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1562], calling coreclr!RunMain [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1384]
0337F348 5cd8adea coreclr!CorHost2::ExecuteAssembly + 0x6ca [C:\gh\runtime\src\coreclr\vm\corhost.cpp:360], calling coreclr!Assembly::ExecuteMainMethod [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1496]
0337F5C0 5d96c5c0 coreclr!coreclr_execute_assembly + 0xe0 [C:\gh\runtime\src\coreclr\dlls\mscoree\exports.cpp:430]
0337F640 0085c3f5 corerun!run + 0xce5 [C:\gh\runtime\src\coreclr\hosts\corerun\corerun.cpp:368]
0337FB78 008617db corerun!wmain + 0x12b [C:\gh\runtime\src\coreclr\hosts\corerun\corerun.cpp:563], calling corerun!run [C:\gh\runtime\src\coreclr\hosts\corerun\corerun.cpp:209]
0337FC40 00871fa3 corerun!invoke_main + 0x33 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90], calling corerun!wmain [C:\gh\runtime\src\coreclr\hosts\corerun\corerun.cpp:555]
0337FC60 00871df7 corerun!__scrt_common_main_seh + 0x157 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288], calling corerun!invoke_main [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:89]
0337FCBC 00871c8d corerun!__scrt_common_main + 0xd [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331], calling corerun!__scrt_common_main_seh [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:236]
0337FCC4 00872028 corerun!wmainCRTStartup + 0x8 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_wmain.cpp:17], calling corerun!__scrt_common_main [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:324]
0337FCCC 75ac6739 KERNEL32!BaseThreadInitThunk + 0x19 [clientcore\base\win32\client\thread.c:77]
0337FCDC 779490af ntdll!__RtlUserThreadStart + 0x2b [minkernel\ntdll\rtlstrt.c:1152]
0337FD34 7794907d ntdll!_RtlUserThreadStart + 0x1b [minkernel\ntdll\rtlstrt.c:1069], calling ntdll!__RtlUserThreadStart [minkernel\ntdll\rtlstrt.c:1109]
```

Interop\ICustomMarshaler\Primitives\ICustomMarshaler_TargetWindows\ICustomMarshaler_TargetWindows.dll
```
0:000> !DumpStack
OS Thread Id: 0x53500 (0)
Current frame: (MethodDesc 08ab2c8c + 0xed ILStubClass.IL_STUB_PInvoke(System.String))
ChildEBP RetAddr  Caller, Callee
02B7DE4C 5d6858a2 coreclr!ThePreStub + 0x11, calling coreclr!PreStubWorker [C:\gh\runtime\src\coreclr\vm\prestub.cpp:1856]
02B7DE70 08604c0e (MethodDesc 087e8c80 + 0x26 System.Runtime.InteropServices.Tests.ICustomMarshalerTests.CustomMarshaler_StringType_Success()), calling 085e8ba0 (stub for System.Runtime.InteropServices.Tests.ICustomMarshalerTests.MarshalerOnStringTypeMethod(System.String))
02B7DE94 086046a6 (MethodDesc 087e99e8 + 0x26 System.Runtime.InteropServices.Tests.ICustomMarshalerTests.Main(System.String[])), calling (MethodDesc 087e8c80 + 0 System.Runtime.InteropServices.Tests.ICustomMarshalerTests.CustomMarshaler_StringType_Success())
02B7DED0 5d6855c1 coreclr!CallDescrWorkerInternal + 0x34
02B7DEDC 5d0ed557 coreclr!CallDescrWorker + 0xd7 [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:123], calling coreclr!CallDescrWorkerInternal
02B7E304 5d0ed7cc coreclr!CallDescrWorkerWithHandler + 0x1bc [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:69], calling coreclr!CallDescrWorker [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:78]
02B7E38C 5cc50fe1 coreclr!GetThread + 0x51 [C:\gh\runtime\src\coreclr\vm\threads.inl:45], calling coreclr!_RTC_CheckEsp [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\rtc\stack.cpp:21]
02B7E394 5d0ed690 coreclr!CallDescrWorkerWithHandler + 0x80 [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:65], calling coreclr!_alloca_probe_16 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\misc\i386\alloca16.asm:44]
02B7E3E0 5d0ee1dd coreclr!MethodDescCallSite::CallTargetWorker + 0x98d [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:565], calling coreclr!CallDescrWorkerWithHandler [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:54]
02B7E434 5d0edede coreclr!MethodDescCallSite::CallTargetWorker + 0x68e [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:376], calling coreclr!_alloca_probe_16 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\misc\i386\alloca16.asm:44]
02B7E7E4 5cc86acf coreclr!MethodDescCallSite::Call_RetArgSlot + 0xef [C:\gh\runtime\src\coreclr\vm\callhelpers.h:458], calling coreclr!MethodDescCallSite::CallTargetWorker [C:\gh\runtime\src\coreclr\vm\callhelpers.cpp:260]
02B7E898 5cc94cf5 coreclr!RunMainInternal + 0x1e5 [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1367], calling coreclr!MethodDescCallSite::Call_RetArgSlot [C:\gh\runtime\src\coreclr\vm\callhelpers.h:458]
02B7E98C 5cc94645 coreclr!``RunMain'::`29'::__Body::Run'::`5'::__Body::Run + 0x75 [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1437], calling coreclr!RunMainInternal [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1335]
02B7E9B8 5cc62b21 coreclr!Thread::PreemptiveGCDisabled + 0x41 [C:\gh\runtime\src\coreclr\vm\threads.h:1838], calling coreclr!Volatile<unsigned long>::LoadWithoutBarrier [C:\gh\runtime\src\coreclr\inc\volatile.h:381]
02B7E9D0 5cc94797 coreclr!`RunMain'::`29'::__Body::Run + 0xa7 [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1437], calling coreclr!``RunMain'::`29'::__Body::Run'::`5'::__Body::Run [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1433]
02B7EA4C 5cc949ee coreclr!RunMain + 0x15e [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1437], calling coreclr!`RunMain'::`29'::__Body::Run [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1433]
02B7EAE8 5cc8ad95 coreclr!Assembly::ExecuteMainMethod + 0x455 [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1562], calling coreclr!RunMain [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1384]
02B7EF1C 5cd8adea coreclr!CorHost2::ExecuteAssembly + 0x6ca [C:\gh\runtime\src\coreclr\vm\corhost.cpp:360], calling coreclr!Assembly::ExecuteMainMethod [C:\gh\runtime\src\coreclr\vm\assembly.cpp:1496]
02B7F194 5d96c5c0 coreclr!coreclr_execute_assembly + 0xe0 [C:\gh\runtime\src\coreclr\dlls\mscoree\exports.cpp:430]
02B7F214 0085c3f5 corerun!run + 0xce5 [C:\gh\runtime\src\coreclr\hosts\corerun\corerun.cpp:368]
02B7F74C 008617db corerun!wmain + 0x12b [C:\gh\runtime\src\coreclr\hosts\corerun\corerun.cpp:563], calling corerun!run [C:\gh\runtime\src\coreclr\hosts\corerun\corerun.cpp:209]
02B7F814 00871fa3 corerun!invoke_main + 0x33 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90], calling corerun!wmain [C:\gh\runtime\src\coreclr\hosts\corerun\corerun.cpp:555]
02B7F834 00871df7 corerun!__scrt_common_main_seh + 0x157 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288], calling corerun!invoke_main [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:89]
02B7F890 00871c8d corerun!__scrt_common_main + 0xd [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331], calling corerun!__scrt_common_main_seh [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:236]
02B7F898 00872028 corerun!wmainCRTStartup + 0x8 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_wmain.cpp:17], calling corerun!__scrt_common_main [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:324]
02B7F8A0 75ac6739 KERNEL32!BaseThreadInitThunk + 0x19 [clientcore\base\win32\client\thread.c:77]
02B7F8B0 779490af ntdll!__RtlUserThreadStart + 0x2b [minkernel\ntdll\rtlstrt.c:1152]
02B7F908 7794907d ntdll!_RtlUserThreadStart + 0x1b [minkernel\ntdll\rtlstrt.c:1069], calling ntdll!__RtlUserThreadStart [minkernel\ntdll\rtlstrt.c:1109]
```

@dotnet/interop-contrib @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Disable tests that actively mess up parameter marshalling on x86 (which passes arguments on the stack instead of registers)

Fix calling conventions

Fixes #74280

### CODE REVIEW

File: src/tests/Interop/DisabledRuntimeMarshalling/PInvokeAssemblyMarshallingEnabled/Delegates.cs [hunk 1]
```diff
@@ -21,8 +24,8 @@ public static void StructWithDefaultNonBlittableFields()
 
         Assert.False(cb(new StructWithShortAndBool(s, b), s, b));
     }
-
-    [Fact]
+
```
Comment (AaronRobinsonMSFT) [inline src/tests/Interop/DisabledRuntimeMarshalling/PInvokeAssemblyMarshallingEnabled/Delegates.cs:27]:
```suggestion

```

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Review by elinor-fung — APPROVED** [review]
