### PR TITLE
Fix Globalization Tests

### LINKED ISSUE #79867: Some culture tests failing on latest Windows 11 builds
We're switching to a new Windows 11 ARM64 test queue in #77764. This queue uses a newer Windows 11 build than what we run on x64. We're seeing some failing tests on the new Windows build.

Going to disable these tests on ARM64 Windows, but the failure is likely not ARM64 specific, just "newer Windows build" specific.

```
    System.Globalization.Tests.CultureInfoConstructor.Ctor_String(name: "prs", expectedNames: ["prs"], expectToThrowOnBrowser: True) [FAIL]
      Assert.Contains() Failure
      Not found: fa
      In value:  String[] ["prs"]
      Stack Trace:
        /_/src/libraries/System.Globalization/tests/CultureInfo/CultureInfoCtor.cs(394,0): at System.Globalization.Tests.CultureInfoConstructor.Ctor_String(String name, String[] expectedNames, Boolean expectToThrowOnBrowser)
           at InvokeStub_CultureInfoConstructor.Ctor_String(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
    System.Globalization.Tests.CultureInfoConstructor.Ctor_String(name: "prs-AF", expectedNames: ["prs-AF"], expectToThrowOnBrowser: True) [FAIL]
      Assert.Contains() Failure
      Not found: fa-AF
      In value:  String[] ["prs-AF"]
      Stack Trace:
        /_/src/libraries/System.Globalization/tests/CultureInfo/CultureInfoCtor.cs(394,0): at System.Globalization.Tests.CultureInfoConstructor.Ctor_String(String name, String[] expectedNames, Boolean expectToThrowOnBrowser)
           at InvokeStub_CultureInfoConstructor.Ctor_String(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
    System.Globalization.Tests.NumberFormatInfoPercentPositivePattern.PercentPositivePattern_Get_ReturnsExpected_ICU [SKIP]
      Condition(s) not met: "IsIcuGlobalization"
    System.Globalization.Tests.NumberFormatInfoPercentNegativePattern.PercentNegativePattern_Get_ReturnsExpected_ICU [SKIP]
      Condition(s) not met: "IsIcuGlobalization"
    System.Globalization.Tests.NumberFormatInfoCurrencyGroupSizes.CurrencyGroupSizes_Get_ReturnsExpected(format: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 1, ... }, expected: [3, 2]) [FAIL]
      Assert.Equal() Failure
                     (pos 1)
      Expected: [3, 2]
      Actual:   [3]
      Stack Trace:
        /_/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrencyGroupSizes.cs(26,0): at System.Globalization.Tests.NumberFormatInfoCurrencyGroupSizes.CurrencyGroupSizes_Get_ReturnsExpected(NumberFormatInfo format, Int32[] expected)
           at InvokeStub_NumberFormatInfoCurrencyGroupSizes.CurrencyGroupSizes_Get_ReturnsExpected(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/79867

Fixing these tests is failing in the main, servicing branches, and causing some noises. 

https://github.com/dotnet/runtime/issues/86338
https://github.com/dotnet/runtime/issues/88740

### CODE REVIEW

File: src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrencyGroupSizes.cs [hunk 1]
```diff
@@ -10,21 +10,44 @@ public class NumberFormatInfoCurrencyGroupSizes
...
         }
 
+        private static bool ArrayEqual<T>(T[] a, T[] b)
+        {
+            if (a == null || b == null)
+            {
+                return a == b;
+            }
+
+            if (a.Length != b.Length)
```
Comment (eiriktsarpalis) [inline src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrencyGroupSizes.cs:29]: I think you can replace this whole section with `a.SequenceEquals(b)`

**Review by eiriktsarpalis — APPROVED** [review]

File: src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrencyGroupSizes.cs (hunk 1 above)
Comment (filipnavara) [reply src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrencyGroupSizes.cs:29]: (or `a.AsSpan().SequenceEqual(b.AsSpan())` if you want to avoid LINQ)
