### PR TITLE
Fix for RoslynPad crash found in targeted preview testing

### LINKED ISSUE #50472: [6.0.100-preview.4.21178.2] System.AccessViolationException at RoslynPad when run against 6.0.100-preview.4.21178.2
**Application Name:**  RoslynPad(.net core 3.1 app)
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-preview.4.21178.2
**Source Code, App & CrashDump :** check at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1303709
**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build  6.0.100-preview.4.21178.2 - main branch: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build  6.0.100-preview.3.21180.8 - Preview 3 branch: Fail
3). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-preview.2.21158.2: Pass
4). Windows 10 RS5 X64 + .NET Core SDK build 5.0.104 : Pass
5). Windows 10 RS5 X64 + .NET Core SDK build 3.1.300 Pass

**Repro steps to run**
1) Copy app from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1303709
2) Run RoslynPad.exe
3) in document, input : 
```
#r "framework:Microsoft.WindowsDesktop.App"

using System.Windows;
using System.Windows.Controls;

await Helpers.RunWpfAsync(); // initializes a dispatcher thread

var w = new Window { Content = new Button { Content = "Hello, World!", IsCancel = true } };
w.ShowDialog()     
```    
4) Click Run button

**Expected Result:**
It should open WPF window

**Actual Result:**
App crashes [crash also could happen after closing WPF window)

**Error Log :**
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Stack Trace**
```
System_Collections_Immutable!System.Collections.Immutable.ImmutableList`1+Enumerator[[System.Collections.Generic.KeyValuePair`2[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]].Dispose()+0x20fcab0
01 0000004e`0c4bdb30 00007ff9`8180c998 System_Collections_Immutable!System.Collections.Immutable.ImmutableDictionary`2+<get_Values>d__27[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].System.IDisposable.Dispose()+0x7c
02 0000004e`0c4bdb80 00007ff9`8180d771 System_Linq!System.Linq.Enumerable+SelectManySingleSelectorIterator`2[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].Dispose()+0xffffffff`95ed5658*** WARNING: Unable to verify checksum for C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0-preview.4.21177.4\System.Linq.dll
*** ERROR: Module load completed but symbols could not be loaded for C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0-preview.4.21177.4\System.Linq.dll
```

**Findings:**
Error comes from System.Collections.Immutable.dll, when we replace dll with older version, app works.

@dotnet-actwx-bot @dotnet/compat

### PR DESCRIPTION
**Pull request by trylek**
I found out that the crash was caused by an incompletely handled
corner case in generic lookup - for method generic lookups, we
were always requesting instantiation stubs even when not appropriate.
I have updated the condition for emitting an instantiation stub,
please review it and let me know if you think the check is incomplete.

Thanks

Tomas

Fixes: https://github.com/dotnet/runtime/issues/50472

### CODE REVIEW

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GenericLookupSignature.cs [hunk 1]
```diff
@@ -107,12 +107,15 @@ public override ObjectData GetData(NodeFactory factory, bool relocsOnly = false)
             {
                 Debug.Assert(_methodArgument.Unboxing == false);
 
+                bool useInstantiatingStub = (_methodArgument.Method.IsSharedByGenericInstantiations &&
+                    (_methodArgument.Method.Signature.IsStatic || _methodArgument.Method.HasInstantiation));
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GenericLookupSignature.cs:111]: Does this check also need to include value types?

Or should this condition be just `RequiresInstArg`?

**Comment by davidwrighton** [comment]
Please add a testcase for this to crossgen2smoke.

**Review by davidwrighton — APPROVED** [review]
Now this looks right. I would still like to see a repro case, but I don't want work on that to delay getting this fix into place for the next preview.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GenericLookupSignature.cs (hunk 1 above)
Comment (trylek) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GenericLookupSignature.cs]: I have reverted this part of the change which doesn't work anyway as the method in question is "runtime determined", not "canonical". According to David Wrighton's analysis it turned out the problem had a different cause, namely imprecise comparison of generic context keys that could in very complex cases end up replacing a generic lookup with a different one.

**Comment by trylek** [comment]
Thanks David for your review. In accordance with your feedback I have merged the change in to give it at least some bake time before the P4 fork. I'll create the regression test as the next step.
