### PR TITLE
Call the Copy Constructor for stack arguments in C++/CLI on x86

### LINKED ISSUE #100033: C++/CLI x86 marshalling misses copy ctor/dtor calls resulting in C++ STL iterator debugging breaking
### Description

This issue is a mirror of [DTS bug 1949402](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1949402), meant to track it on Github.

@jkoritzinsky is looking at this issue.

### Reproduction Steps

The DTS bug contains the repro. Essentially, a copy ctor of `std::vector<>::iterator` is not called when pushing the argument onto the stack for the call to the native method, which takes an argument of type `iterator`. This leads to STL's iterator debugging book-keeping code to later assert.

This happens only for x86 and does not repro in the desktop framework where the copy ctor is correctly called. 

### Expected behavior

The copy ctor is correctly called and no assert fails in STL iterator debugging code.

### Actual behavior

STL iterator debugging assert popup.

### Regression?

Yes. From desktop framework behavior. Customer is blocked from adopting Net 8.0

### Known Workarounds

Disabling iterator debugging. But this still leaves open the question of silent bad codegen happening for similar code that is not protected by asserts.

### Configuration

.NET 8 x86

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes https://github.com/dotnet/runtime/issues/100033

### CODE REVIEW

File: src/coreclr/vm/dllimport.cpp [hunk 1]
```diff
@@ -2071,6 +2092,8 @@ void NDirectStubLinker::End(DWORD dwStubFlags)
     }
 }
 
+EXTERN_C void STDCALL CopyConstructorCallStub(void);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/dllimport.cpp:2095]: It isn't obvious if this is conditioned on WIndows and x86. Is it?

File: src/coreclr/vm/dllimport.cpp [hunk 2]
```diff
@@ -1630,6 +1630,10 @@ NDirectStubLinker::NDirectStubLinker(
         m_pcsSetup->EmitSTLOC(m_dwTargetInterfacePointerLocalNum);
     }
 #endif // FEATURE_COMINTEROP
+
+#if defined(TARGET_WINDOWS) && defined(TARGET_X86)
+    m_dwCopyCtorChainLocalNum = -1;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/dllimport.cpp:1635]:
```suggestion
    m_dwCopyCtorChainLocalNum = (DWORD)-1;
```

File: src/coreclr/vm/dllimport.cpp [hunk 3]
```diff
@@ -6101,5 +6139,24 @@ PCODE GetILStubForCalli(VASigCookie *pVASigCookie, MethodDesc *pMD)
...
+EXTERN_C void* STDCALL CallCopyConstructorsWorker(void* esp)
+{
+    STATIC_CONTRACT_THROWS;
+    STATIC_CONTRACT_GC_TRIGGERS;
+    STATIC_CONTRACT_MODE_PREEMPTIVE; // we've already switched to preemptive
+
+    using ExecuteCallback = void*(STDMETHODCALLTYPE*)(void*);
+    ExecuteCallback pExecute;
+    {
+        GCX_COOP();
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp:6153]:
```suggestion
```
This should not be needed.

File: src/coreclr/vm/dllimport.cpp [hunk 4]
```diff
@@ -2071,6 +2092,10 @@ void NDirectStubLinker::End(DWORD dwStubFlags)
     }
 }
 
+#if defined(TARGET_WINDOWS) && defined(TARGET_X86)
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp:2095]: Why is some of this ifdefed out for Windows x86, and some this only for x86?

Comment (jkoritzinsky) [reply src/coreclr/vm/dllimport.cpp:2095]: Due to how we have the copy-constructor marshaller defined, it's less disruptive to the code to not add `TARGET_WINDOWS` checking everywhere and just use `TARGET_X86` for the general feature.

Since we're likely to backport this fix to .NET 8, I wanted to keep the changes a little less disruptive to existing code. Basically, the marshaller changes are guarded by `TARGET_X86` and the actual thunk (assembly and the callback) is guarded by `TARGET_WINDOWS` and `TARGET_X86`, as the copy constructor marshaller exists in CoreCLR on non-Windows platforms today (though triggering it requires custom IL to define the well-known member names).

If we wanted to unify the checks, we have two paths:

- Write the little assembly stub for Linux_x86 as well to maintain parity.
- `#ifdef` out the marshaller on non-Windows, which would technically be a back-compat break.

I'll look at writing the assembly stub for Linux_x86 as it should be very simple and then everything can be `TARGET_X86`.

**Comment by jkotas** [comment]
> I'll look at writing the assembly stub for Linux_x86 

I do not think we want to be enabling any of this on Linux x86. This is Windows-only feature to support IJW.

**Comment by jkoritzinsky** [comment]
> > I'll look at writing the assembly stub for Linux_x86
> 
> I do not think we want to be enabling any of this on Linux x86. This is Windows-only feature to support IJW.

If we're looking at backporting this to .NET 8 (which I believe we are given where this issue originated, I really don't want to break back-compat here as we already know that customers do strange things and are prone to using features we never thought they would. I'd rather write the 5 lines of code to get this to compile equally everywhere than remove what currently exists.

**Comment by AaronRobinsonMSFT** [comment]
[like]  Aaron Robinson reacted to your message:
________________________________

File: src/coreclr/vm/dllimport.cpp (hunk 4 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp]: > #ifdef out the marshaller on non-Windows, which would technically be a back-compat break.

How is this a visible back-compat break? Is the marshaller usable in any way on non-Windows?

Comment (jkoritzinsky) [reply src/coreclr/vm/dllimport.cpp]: Yes, today if you use IL to write your type with the correctly named `<MarshalCopy>` method and a P/Invoke with the right modopts, we'll use this marshaller. The `Interop/PInvoke/Miscallaneous/CopyCtor` test runs on all CoreCLR platforms and passes today.

Comment (jkotas) [reply src/coreclr/vm/dllimport.cpp]: I do not think it is desirable for these IJW features to work outside Windows.

Comment (jkoritzinsky) [reply src/coreclr/vm/dllimport.cpp]: I agree, but I'm very hesitant to remove it for the backport as I've broken customers by removing thought-to-be-unused features before. We can follow up this PR with a full removal of the copy-constructor marshaler on non-Windows, but I don't want to do it in this PR.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas I am good with this change based on Jeremy's response in https://github.com/dotnet/runtime/pull/100050#discussion_r1534939652. Do you have concerns moving forward, for now, as is or is removing the non-Windows support a hard requirement?

**Comment by jkotas** [comment]
The change includes Linux x86 specific code. What kind of testing have we done on this change on Linux x86? If we have not tested it, we should not be pushing it to servicing and limit it to Windows x86 instead (e.g. find&replace the ifdefs around the changes with `TARGET_X86 && TARGET_WINDOWS`).

I am fine with cleaning up IJW-specific features that leaked to non-Windows later. It may be nice to introduce a FEATURE_ define for it (we used to have one in the old days).

**Comment by AaronRobinsonMSFT** [comment]
> The change includes Linux x86 specific code. What kind of testing have we done on this change on Linux x86?

There is a test case that runs on all platforms. I'm not convinced it should be there, but it does exist and runs/passes.

**Comment by jkotas** [comment]
> There is a test case that runs on all platforms. I'm not convinced it should be there, but it does exist and runs/passes.

The CI does not run any tests on Linux x86.

**Comment by AaronRobinsonMSFT** [comment]
> > There is a test case that runs on all platforms. I'm not convinced it should be there, but it does exist and runs/passes.
> 
> The CI does not run any tests on Linux x86.

Shoot. I saw Linux x86 and assumed it was testing too. It is just build. Well this sucks. Let me see what I can do here.

File: src/coreclr/vm/dllimport.cpp (hunk 4 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp]: > I've broken customers by removing thought-to-be-unused features before

This is not a supported scenario in any capacity and requires writing in IL directly. I appreciate the concern here but it is unlikely anyone relying on this is something we would accept as valid.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas PTAL

File: src/coreclr/vm/corelib.h [hunk 5]
```diff
@@ -1040,6 +1040,21 @@ DEFINE_METHOD(HANDLE_MARSHALER,          CONVERT_SAFEHANDLE_TO_NATIVE,ConvertSaf
 DEFINE_METHOD(HANDLE_MARSHALER,          THROW_SAFEHANDLE_FIELD_CHANGED, ThrowSafeHandleFieldChanged, SM_RetVoid)
 DEFINE_METHOD(HANDLE_MARSHALER,          THROW_CRITICALHANDLE_FIELD_CHANGED, ThrowCriticalHandleFieldChanged, SM_RetVoid)
 
+#ifdef TARGET_WINDOWS
```
Comment (jkotas) [inline src/coreclr/vm/corelib.h:1043]: I assume that this is two-liner because ILLINK chokes on `#if defined(TARGET_X86) && defined(TARGET_WINDOWS)`

**Review by jkotas — APPROVED** [review]
LGTM

File: src/coreclr/vm/corelib.h (hunk 5 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/corelib.h:1043]: Sadly, yes.
