### PR TITLE
JIT: fix arm64 issue around flags and neg with contained operand

### LINKED ISSUE #113320: JIT: Bad result with modulo on linux-arm64
```csharp
// Generated by Fuzzlyn v2.4 on 2025-03-09 16:30:39
// Run on Arm64 Linux
// Seed: 8543882715922286200-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256,armsve
// Reduced from 59.2 KiB to 0.4 KiB in 00:00:34
// Debug: Outputs 0
// Release: Outputs 1
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static ushort s_12;
    public static uint[, ] s_13 = new uint[, ]
    {
        {
            1
        }
    };
    public static void Main()
    {
        if (((0 % s_13[0, 0]) > 0))
        {
            s_12 = 1;
        }

        System.Console.WriteLine(s_12);
    }
}
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
If `neg` has a contained operand (`mul`) it cannot set flags.

Fixes #113320

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Also fixes issue I ran into in #112998.

@dotnet/jit-contrib PTAL

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -19978,17 +19978,21 @@ bool GenTree::SupportsSettingZeroFlag()
...
 #endif
 #elif defined(TARGET_ARM64)
-    if (OperIs(GT_AND, GT_AND_NOT, GT_NEG))
+    if (OperIs(GT_AND, GT_AND_NOT))
     {
         return true;
     }
 
     // We do not support setting zero flag for madd/msub.
+    if (OperIs(GT_NEG) && (!gtGetOp1()->OperIs(GT_MUL) || !gtGetOp1()->isContained()))
```
Comment (EgorBo) [inline src/coreclr/jit/gentree.cpp:19987]: I presume just `if (OperIs(GT_NEG) && !gtGetOp1()->isContained())` would be enough since NEG can't contain anything. Also I presume we should've had a separate node type for MUL+ADD/SUB

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -19978,17 +19978,21 @@ bool GenTree::SupportsSettingZeroFlag()
     }
 #endif
 #elif defined(TARGET_ARM64)
-    if (OperIs(GT_AND, GT_AND_NOT, GT_NEG))
+    if (OperIs(GT_AND, GT_AND_NOT))
     {
         return true;
     }
 
     // We do not support setting zero flag for madd/msub.
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.cpp:19986]:
```suggestion
    // We do not support setting zero flag for mneg/madd/msub.
```
feel free to skip to avoid CI rerun...
