### PR TITLE
[mono] generic wrapper methods for unsafe accessors

### LINKED ISSUE #92883: [mono][aot] Baseservices runtime tests failed in Mono fullAOT llvm job
Below are the tests that failed in the test run https://dev.azure.com/dnceng-public/public/_build/results?buildId=422831&view=logs&jobId=c38ec756-eb98-514e-2413-35443f23bc13.

UnsafeAccessorsTests.dll
```
BEGIN EXECUTION
/datadisks/disk1/work/A41708E9/p/corerun -p Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability=true -p System.ComponentModel.TypeConverter.EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization=false -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Resources.ResourceManager.AllowCustomResourceTypes=false -p System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false -p System.Runtime.InteropServices.EnableConsumingManagedCodeFromNativeHosting=false -p System.Runtime.InteropServices.EnableCppCLIHostActivation=false -p System.Runtime.InteropServices.Marshalling.EnableGeneratedComInterfaceComImportInterop=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true -p System.StartupHookProvider.IsSupported=false -p System.Text.Encoding.EnableUnsafeUTF7Encoding=false -p System.Text.Json.JsonSerializer.IsReflectionEnabledByDefault=false -p System.Threading.Thread.EnableAutoreleasePool=false UnsafeAccessorsTests.dll ''
Running Verify_CallDefaultCtorClass
Running Verify_CallCtorClass
Running Verify_CallCtorValue
Running Verify_CallCtorWithEmptyNotNullName
Running Verify_CallCtorAsMethod
Running Verify_CallCtorAsMethodValue
Running Verify_AccessStaticFieldClass
Running Verify_AccessFieldClass
Running Verify_AccessStaticFieldValue
Running Verify_AccessFieldValue
Running Verify_AccessStaticMethodClass
Running Verify_AccessMethodClass
Running Verify_AccessStaticMethodVoidClass
Running Verify_AccessMethodVoidClass
Running Verify_AccessStaticMethodValue
Running Verify_AccessMethodValue
Running Verify_IgnoreCustomModifier
Running Verify_PreciseMatchCustomModifier
Running Verify_UnmanagedCallConvBitAreTreatedAsCustomModifiersAndIgnored
Running Verify_ManagedUnmanagedFunctionPointersDontMatch
Running Verify_InheritanceMethodResolution
Running Verify_InheritanceFieldResolution
Running Verify_InvalidTargetUnsafeAccessor
Running Verify_InvalidTargetUnsafeAccessorAmbiguousMatch
Running Verify_InvalidUseUnsafeAccessor
Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.BadImageFormatException)
Actual:   typeof(System.ExecutionEngineException): Attempting to JIT compile method '(wrapper other) string UnsafeAccessorsTests/Invalid:CallToString (string)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
          
   at UnsafeAccessorsTests.<>c.<Verify_InvalidUseUnsafeAccessor>b__41_13()
   at Xunit.Assert.RecordException(Func`1 testCode)
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 9/29/2023 7:23:18 PM
Test Harness Exitcode is : 1
```

TieredVtableMethodTests.dll
```
BEGIN EXECUTION
/datadisks/disk1/work/A41708E9/p/corerun -p Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability=true -p System.ComponentModel.TypeConverter.EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization=false -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Resources.ResourceManager.AllowCustomResourceTypes=false -p System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false -p System.Runtime.InteropServices.EnableConsumingManagedCodeFromNativeHosting=false -p System.Runtime.InteropServices.EnableCppCLIHostActivation=false -p System.Runtime.InteropServices.Marshalling.EnableGeneratedComInterfaceComImportInterop=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true -p System.StartupHookProvider.IsSupported=false -p System.Text.Encoding.EnableUnsafeUTF7Encoding=false -p System.Text.Json.JsonSerializer.IsReflectionEnabledByDefault=false -p System.Threading.Thread.EnableAutoreleasePool=false TieredVtableMethodTests.dll ''
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 9/29/2023 7:23:22 PM
Test Harness Exitcode is : 1
```

varargsupport.dll and varargsupport_r.dll
```
BEGIN EXECUTION
/datadisks/disk1/work/A41708E9/p/corerun -p Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability=true -p System.ComponentModel.TypeConverter.EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization=false -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Resources.ResourceManager.AllowCustomResourceTypes=false -p System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false -p System.Runtime.InteropServices.EnableConsumingManagedCodeFromNativeHosting=false -p System.Runtime.InteropServices.EnableCppCLIHostActivation=false -p System.Runtime.InteropServices.Marshalling.EnableGeneratedComInterfaceComImportInterop=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true -p System.StartupHookProvider.IsSupported=false -p System.Text.Encoding.EnableUnsafeUTF7Encoding=false -p System.Text.Json.JsonSerializer.IsReflectionEnabledByDefault=false -p System.Threading.Thread.EnableAutoreleasePool=false varargsupport_r.dll ''
Test failed as InvalidProgramException was not raised.
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 9/29/2023 7:23:18 PM
Test Harness Exitcode is : 1
```

### PR DESCRIPTION
**Pull request by lambdageek**
1. Adds support for compiling generic wrapper methods to Mono.  In some situations we need to emit a wrapper method that is generic.  This makes the MethodBuilder infrastructure support that.
2. Adds support for inflating generic wrapper data.  Wrappers have pointer data associated with them that is used by the code generator (For example instead of emitting field tokens, we record the `MonoClassField*` directly and then emit a fake token that is just the index of the `MonoClassField*` in the `MonoMethodWrapper:method_data` array).  The pointer data associated with a wrapper is normally just consumed verbatim.  But if the wrapper is part of a generic class, or if the wrapper is a generic method, the wrapper data might have generic parameters (for example it might be a MonoClassField for `MyList<T>` instead of `MyList<string>`).  Add support for tagging the data with its kind and inflating it if the wrapper method is inflated.
3. Applies (1) and (2) to unsafe accessor methods - the unsafe accesor wrapper generation now always tries to get the generic definition and to generate a wrapper for that generic definition and then inflate it.
4. Some AOT changes so that FullAOT substitutes lookups for an unsafe accessor by lookups for the wrapper.  Including if the unsafe accessor or wrapper is generic.  This also enabled gshared and gsharedvt for unsafe accessor wrappers.  This also fixes https://github.com/dotnet/runtime/issues/92883

Contributes to https://github.com/dotnet/runtime/issues/99830, https://github.com/dotnet/runtime/issues/89439

**NOT DONE**
- We don't check constraints on the generic target types yet

### CODE REVIEW

File: src/mono/mono/metadata/marshal-lightweight.c [hunk 1]
```diff
@@ -2424,22 +2430,29 @@ emit_unsafe_accessor_ctor_wrapper (MonoMethodBuilder *mb, MonoMethod *accessor_m
...
 
 	if (target_type == NULL || m_type_is_byref (target_type) || unsafe_accessor_target_type_forbidden (target_type)) {
 		mono_mb_emit_exception_full (mb, "System", "BadImageFormatException", "Invalid usage of UnsafeAccessorAttribute.");
 		return;
 	}
+	
+	gboolean inflate_generic_data = FALSE;
+	if ((accessor_method->is_generic || to_be_inflated)) {
+		// We want to do a static lookup: target type must be G<T>, not just !T or !!T
+		g_assert (target_type->type != MONO_TYPE_VAR && target_type->type != MONO_TYPE_MVAR);
```
Comment (fanyang-mono) [inline src/mono/mono/metadata/marshal-lightweight.c:2442]: Remove this check.

File: src/mono/mono/metadata/marshal-lightweight.c [hunk 2]
```diff
@@ -2472,7 +2487,20 @@ emit_unsafe_accessor_method_wrapper (MonoMethodBuilder *mb, MonoMethod *accessor
...
+
+	if (sig->param_count < 1 || target_type == NULL || unsafe_accessor_target_type_forbidden (target_type)) {
+		mono_mb_emit_exception_full (mb, "System", "BadImageFormatException", "Invalid usage of UnsafeAccessorAttribute.");
+		return;
+	}
+
+	gboolean inflate_generic_data = FALSE;
+	if ((accessor_method->is_generic || to_be_inflated)) {
+		// We want to do a static lookup: target type must be G<T>, not just !T or !!T
+		g_assert (target_type->type != MONO_TYPE_VAR && target_type->type != MONO_TYPE_MVAR);
```
Comment (fanyang-mono) [inline src/mono/mono/metadata/marshal-lightweight.c:2500]: Remove this check.

File: src/mono/mono/metadata/marshal-lightweight.c [hunk 3]
```diff
@@ -2424,22 +2430,29 @@ emit_unsafe_accessor_ctor_wrapper (MonoMethodBuilder *mb, MonoMethod *accessor_m
...
+
+	MonoClass *target_class = mono_class_from_mono_type_internal (target_type);
+
+	ERROR_DECL(find_method_error);
 
-	MonoMethodSignature *member_sig = ctor_sig_from_accessor_sig (mb, sig, ctx);
+	MonoMethodSignature *member_sig = ctor_sig_from_accessor_sig (mb, sig);
 	
-	MonoClass *in_class = mono_class_get_generic_type_definition (target_class);
+	MonoClass *in_class = target_class; // mono_class_get_generic_type_definition (target_class);
```
Comment (fanyang-mono) [inline src/mono/mono/metadata/marshal-lightweight.c:2455]: Remove the comment here? It will be confusing to read later, since it will be the generic type already.

File: src/mono/mono/metadata/marshal-lightweight.c [hunk 4]
```diff
@@ -2482,19 +2510,10 @@ emit_unsafe_accessor_method_wrapper (MonoMethodBuilder *mb, MonoMethod *accessor
...
-	if (sig->param_count < 1 || target_type == NULL || unsafe_accessor_target_type_forbidden (target_type)) {
-		mono_mb_emit_exception_full (mb, "System", "BadImageFormatException", "Invalid usage of UnsafeAccessorAttribute.");
-		return;
-	}
 
-	MonoMethodSignature *member_sig = method_sig_from_accessor_sig (mb, hasthis, sig, ctx);
+	MonoMethodSignature *member_sig = method_sig_from_accessor_sig (mb, hasthis, sig);
 
-	MonoClass *in_class = mono_class_get_generic_type_definition (target_class);
+	MonoClass *in_class = target_class; // mono_class_get_generic_type_definition (target_class);
```
Comment (fanyang-mono) [inline src/mono/mono/metadata/marshal-lightweight.c:2516]: Remove the comment here?

**Review by fanyang-mono — COMMENTED** [review]
I've reviewed the unsafe accessor related change. Will review the method builder related change then AOT related change.

File: src/mono/mono/metadata/marshal.c [hunk 5]
```diff
@@ -5226,39 +5226,129 @@ mono_marshal_get_unsafe_accessor_wrapper (MonoMethod *accessor_method, MonoUnsaf
...
+	
+	mb = mono_mb_new (accessor_method->klass, accessor_method->name, MONO_WRAPPER_OTHER);
+	if (generic_wrapper) {
+		// If the accessor method was generic, make the wrapper generic, too.
 
-	sig = mono_metadata_signature_dup_full (get_method_image (accessor_method), mono_method_signature_internal (accessor_method));
-	sig->pinvoke = 0;
+		// Load a copy of the generic params of the accessor method
+		mb->method->is_generic = generic_wrapper;
+		container = mono_class_try_get_generic_container (accessor_method->klass);
```
[the remark this answers is not in the document]
Comment (lambdageek) [reply src/mono/mono/metadata/marshal.c:5319]: No, it can't. It's used as an argument to `mono_metadata_load_generic_params` in the next line.

File: src/mono/mono/metadata/marshal.c [hunk 6]
```diff
@@ -5226,39 +5226,129 @@ mono_marshal_get_unsafe_accessor_wrapper (MonoMethod *accessor_method, MonoUnsaf
...
+		container = mono_metadata_load_generic_params (m_class_get_image (accessor_method->klass), accessor_method->token, container, /*owner:*/mb->method);
+		mono_method_set_generic_container (mb->method, container);
 
-	mb = mono_mb_new (accessor_method->klass, accessor_method->name, MONO_WRAPPER_OTHER);
+		MonoGenericContext inst_ctx = {0,};
+		// FIXME: if is_inflated, do we need to mess with ctx?
+		inst_ctx.method_inst = container->context.method_inst;
```
[the remark this answers is not in the document]
Comment (lambdageek) [reply src/mono/mono/metadata/marshal.c:5325]: So conceptually if both the class is generic and the `static extern` accessor method is generic, when we make a wrapper we want its signature to use the same exact class gparams as the accessor method (conceptually both the accessor method and the wrapper are members of the class).  But we want it to use its own brand new method gparams.  So we take the original signature of hte access method and replace the method gparams:

```csharp

class G<T> {
   public static extern Tuple<T,U> Accessor<U>(T t, U u);
   // wrapper:
   // public static extern Tuple<T, U2> Accessor<U2>(T t, U2 u);
}
```

so it's as if the wrapper instead of having a gparam named `U` has a gparam named `U2`. And so if we just take signature of the accessor, we have to replace all `U`s by `U2`.  But the `T` is the same

File: src/mono/mono/metadata/class.c [hunk 7]
```diff
@@ -1263,6 +1264,17 @@ mono_class_inflate_generic_method_full_checked (MonoMethod *method, MonoClass *k
...
+		if (mw->inflate_wrapper_data) {
+			mono_mb_inflate_generic_wrapper_data (context, (gpointer*)resw->method_data, error);
+			if (!is_ok (error)) {
+				g_free (resw->method_data);
+				goto fail;
+			}
+			// we can't set inflate_wrapper_data to 0 on the result, it's possible it
+			// will need to be inflated again (for example in the method_inst ==
+			// generic_container->context.method_inst case, below)
+			resw->inflate_wrapper_data = 1;
```
Comment (kotlarmilos) [inline src/mono/mono/metadata/class.c:1276]: Nit: Consistency between `1` and `TRUE`.

File: src/mono/mono/metadata/marshal.c [hunk 8]
```diff
@@ -5226,39 +5226,126 @@ mono_marshal_get_unsafe_accessor_wrapper (MonoMethod *accessor_method, MonoUnsaf
...
+			generic_wrapper = TRUE;
+		}
+		is_inflated = TRUE;
+	}
+
+	if (accessor_method->is_generic) {
+		generic_wrapper = TRUE;
+	}
+
+	if (is_inflated) {
```
Comment (kotlarmilos) [inline src/mono/mono/metadata/marshal.c:5263]: The `is_inflated` appears redundant since `accessor_method` is already passed to the `emit_unsafe_accessor_[field/ctor/method]_wrapper` function.

Can `accessor_method->is_inflated` be used directly instead of the `is_inflated` variable? The idea is to make the wrapper inflated if the accessor method is inflated and remove `gboolean to_be_inflated`.

File: src/mono/mono/metadata/method-builder-ilgen.c [hunk 9]
```diff
@@ -652,3 +700,73 @@ mono_mb_set_param_names (MonoMethodBuilder *mb, const char **param_names)
...
+	mb->wrapper_data_inflate_info = g_list_prepend (mb->wrapper_data_inflate_info, info);
+}
+
+gboolean
+mono_mb_inflate_generic_wrapper_data (MonoGenericContext *context, gpointer *method_data, MonoError *error)
+{
+	MonoMethodBuilderInflateWrapperData* inflate_info = (MonoMethodBuilderInflateWrapperData*)method_data[MONO_MB_ILGEN_INFLATE_WRAPPER_INFO_IDX];
+	MonoMethodBuilderInflateWrapperData* p = inflate_info;
+	int count = 0;
+	while (p->idx != 0) {p++; count++;}
```
Comment (kotlarmilos) [inline src/mono/mono/metadata/method-builder-ilgen.c:725]: Is this necessary?

File: src/mono/mono/metadata/class.c (hunk 7 above)
Comment (lambdageek) [reply src/mono/mono/metadata/class.c:1276]: `MonoMethodWrapper:inflate_wrapper_data` is a bitfield, so I use `1`

`MonoMethodBuilder:inflate_wrapper_data` is a gboolean, so I use `TRUE`

File: src/mono/mono/metadata/method-builder-ilgen.c (hunk 9 above)
Comment (kotlarmilos) [reply src/mono/mono/metadata/method-builder-ilgen.c:725]: I am wondering why it can't be done in the while loop?

Comment (lambdageek) [reply src/mono/mono/metadata/method-builder-ilgen.c:725]: oh. I see what you mean.  Yea good point

**Review by fanyang-mono — COMMENTED** [review]
These are my feedback for the method builder part.

File: src/mono/mono/metadata/method-builder-ilgen.c [hunk 10]
```diff
@@ -214,6 +250,18 @@ create_method_ilgen (MonoMethodBuilder *mb, MonoMethodSignature *signature, int
...
 	}
 
+	if (mb->method->is_generic) {
+		method->is_generic = TRUE;
+		MonoGenericContainer *container = mono_method_get_generic_container (mb->method);
+		mono_method_set_generic_container (method, container);
+		g_assert (!container->is_anonymous);
+		g_assert (container->is_method);
+		g_assert (container->owner.method == mb->method);
+		// HACK: reassign container owner from the method builder placeholder to the
```
[the remark this answers is not in the document]
Comment (lambdageek) [reply src/mono/mono/metadata/method-builder-ilgen.c:260]: Yea, or doing another call to `mono_metadata_load_generic_params` and inflating the signature again

File: src/mono/mono/metadata/method-builder-ilgen.c [hunk 11]
```diff
@@ -652,3 +700,75 @@ mono_mb_set_param_names (MonoMethodBuilder *mb, const char **param_names)
...
+			// until https://github.com/dotnet/runtime/issues/102080
+			//
+			// But if we have other kinds of generic wrappers, we may need to do it sooner.
+			g_assert (!m_field_is_from_update (field));
+			int i = GPTRDIFF_TO_INT (field - m_class_get_fields (m_field_get_parent (field)));
+			gpointer dummy = NULL;
+
+			mono_metadata_free_type (inflated_type);
+
+			mono_class_get_fields_internal (inflated_class, &dummy);
```
[the remark this answers is not in the document]
Comment (lambdageek) [reply src/mono/mono/metadata/method-builder-ilgen.c:752]: Fields on inflated classes might not be initialized yet (for example if we never called any method on it before - that can happen if we're JITing a deserializer for that inflated class)

File: src/mono/mono/mini/aot-compiler.c [hunk 12]
```diff
@@ -13047,6 +13132,20 @@ collect_methods (MonoAotCompile *acfg)
 		method = mono_get_method_checked (acfg->image, token, NULL, NULL, error);
 		report_loader_error (acfg, error, TRUE, "Failed to load method token 0x%x due to %s\n", i, mono_error_get_message (error));
 
+		if (mono_aot_mode_is_full (&acfg->aot_opts) && !mono_method_metadata_has_header (method)) {
+			// if the method has no body, see if it's an [UnsafeAccessor] method and replace it by the wrapper.
+			char *member_name = NULL;
+			int accessor_kind = -1;
+			if (mono_method_get_unsafe_accessor_attr_data (method, &accessor_kind, &member_name, error)) {
+				MonoMethod *wrapper = mono_marshal_get_unsafe_accessor_wrapper (method, (MonoUnsafeAccessorKind)accessor_kind, member_name);
```
Comment (fanyang-mono) [inline src/mono/mono/mini/aot-compiler.c:13140]: I wonder why inflation is not needed here? i.e. calling `replace_generated_method` instead.

File: src/mono/mono/mini/aot-runtime.c [hunk 13]
```diff
@@ -940,6 +941,14 @@ typedef struct {
 	gboolean no_aot_trampoline;
 } MethodRef;
 
+static MonoMethod*
+inflate_unsafe_accessor_wrapper (MonoMethod *extern_decl, MonoGenericContext *ctx, MonoUnsafeAccessorKind accessor_kind, const char *member_name, MonoError *error)
```
Comment (fanyang-mono) [inline src/mono/mono/mini/aot-runtime.c:945]: `inflate_unsafe_accessor_wrapper` is a sub-routine of `inflate_unsafe_accessor_like_decl`. `inflate_unsafe_accessor_like_decl` could be refactored with a call to `inflate_unsafe_accessor_wrapper`,

File: src/mono/mono/mini/aot-runtime.c [hunk 14]
```diff
@@ -5049,24 +5120,63 @@ mono_aot_get_method (MonoMethod *method, MonoError *error)
...
+				}
+			}
 		}
 
 		if (method_index == 0xffffff && method->is_inflated && mono_method_is_generic_sharable_full (method, FALSE, FALSE, TRUE)) {
 			MonoMethod *shared;
 			/* gsharedvt */
 			/* Use the all-vt shared method since this is what was AOTed */
 			shared = mini_get_shared_method_full (method, SHARE_MODE_GSHAREDVT, error);
+			if (shared && !mono_method_metadata_has_header (shared)) {
```
Comment (fanyang-mono) [inline src/mono/mono/mini/aot-runtime.c:5143]: Same question here.

File: src/mono/mono/mini/aot-runtime.c [hunk 15]
```diff
@@ -5049,24 +5120,63 @@ mono_aot_get_method (MonoMethod *method, MonoError *error)
...
 			if (method_index != 0xffffff) {
+				// XXX AK: I don't understand why we call mini_get_shared_method_full twice
+				// in the gshared case, above, we just say method = shared, which seems right.
 				method = mini_get_shared_method_full (method, SHARE_MODE_GSHAREDVT, error);
 				if (!method)
 					return NULL;
 			}
 		}
 
+		if (method_index == 0xffffff && !mono_method_metadata_has_header (method)) {
```
Comment (fanyang-mono) [inline src/mono/mono/mini/aot-runtime.c:5169]: Here as well.

**Review by fanyang-mono — COMMENTED** [review]
These are my feedbacks for the aot part of change.

**Review by fanyang-mono — APPROVED** [review]
Thanks for making this infrastructure change!

File: src/mono/mono/mini/aot-compiler.c (hunk 12 above)
Comment (lambdageek) [reply src/mono/mono/mini/aot-compiler.c:13140]: This part is iterating over the method definitions in the `MONO_TABLE_METHOD` table.  None of them are inflated.

File: src/mono/mono/mini/aot-runtime.c [hunk 16]
```diff
@@ -5049,24 +5068,63 @@ mono_aot_get_method (MonoMethod *method, MonoError *error)
 			method_index = find_aot_method (shared, &amodule);
 			if (method_index != 0xffffff)
 				method = shared;
+			if (method_index == 0xffffff && !mono_method_metadata_has_header (method)) {
```
Comment (fanyang-mono) [inline src/mono/mono/mini/aot-runtime.c:5071]: Is it true that method without header will always be extern method with unsafe accessor attribute?

File: src/mono/mono/mini/aot-runtime.c (hunk 14 above)
Comment (fanyang-mono) [reply src/mono/mono/mini/aot-runtime.c:5091]: My question got lost from this list for some reason. I asked again. See the latest comment.
