### PR TITLE
Delete `GTF_VAR_CAST`

### LINKED ISSUE #74259: dnSpy: Assertion failed '(varDsc->TypeGet() == TYP_I_IMPL) && lcl->TypeIs(TYP_BYREF)'
I tried to update [dnSpy](https://github.com/dnSpy/dnSpy) project to net7.0 but it crashes at some point with:
```
Assert failure(PID 38008 [0x00009478], Thread: 42384 [0xa590]): Assertion failed '(varDsc->TypeGet() == TYP_I_IMPL) && lcl->TypeIs(TYP_BYREF)' in 'MS.Internal.Text.TextInterface.FontCollection:FindFamilyName(System.String,byref):bool:this' during 'Do value numbering' (IL size 76; hash 0x31ca3e43; Tier1)

    File: C:\prj\runtime\src\coreclr\jit\valuenum.cpp Line: 8438
    Image: C:\prj\runtime\artifacts\bin\coreclr\windows.x64.Checked\corerun.ex
```
with Checked JIT

### PR DESCRIPTION
**Pull request by SingleAccretion**
It is unused.

Tighten an assert in the ref counter and relax one in VN.

[Diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1963573&view=ms.vss-build-web.run-extensions-tab) - we now contain more in-memory locals under bounds checks because they have the proper `INT` type. Also a nice TP win from downgrading the `noway_assert` to an ordinary `assert`.

Fixes #74259.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
Will rerun CI on this one.

File: src/coreclr/jit/valuenum.cpp [hunk 1]
```diff
@@ -8443,7 +8443,8 @@ void Compiler::fgValueNumberTree(GenTree* tree)
                             }
                             else
                             {
-                                assert((varDsc->TypeGet() == TYP_I_IMPL) && lcl->TypeIs(TYP_BYREF));
+                                assert(((varDsc->TypeGet() == TYP_I_IMPL) && lcl->TypeIs(TYP_BYREF)) ||
+                                       ((varDsc->TypeGet() == TYP_BYREF) && lcl->TypeIs(TYP_LONG)));
```
Comment (jakobbotsch) [inline src/coreclr/jit/valuenum.cpp:8447]: Should be
```suggestion
                                       ((varDsc->TypeGet() == TYP_BYREF) && lcl->TypeIs(TYP_I_IMPL)));
```
?

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Failure looks like the same as https://github.com/dotnet/runtime/pull/75990#issuecomment-1254369698
