### PR TITLE
Fix SIGILL crash on ARM64 platforms with SME but no SVE 

### LINKED ISSUE #122608: .NET 10 SDK ARM64: Illegal instruction (SIGILL) on Apple M4 with macOS Virtualization.Framework
### Description

When building .NET 10 applications in Docker on Apple M4 hardware, the .NET 10 SDK (version 10.0.101) crashes with "Illegal instruction (core dumped)" on ARM64 images. The crash occurs intermittently during various .NET CLI operations including `dotnet new`, `dotnet add package`, and `dotnet build`.

**Environment:**
- **Host**: macOS (Sequoia) on Apple M4 Pro
- **Virtualization**: macOS Virtualization.Framework (VZ) via Colima
  - Colima config: `vmType: vz`, `arch: aarch64`, `rosetta: false`
- **VM OS**: Ubuntu 24.04.1 LTS (Noble Numbat)
- **VM Architecture**: aarch64 (native ARM64, not emulated)
- **.NET SDK**: 10.0.101
- **Docker Image**: `mcr.microsoft.com/dotnet/sdk:10.0` (ARM64 variant, sha256:d1823fecac...)

**Key Observations:**
- ✅ Works perfectly when using `--platform linux/amd64` (via Rosetta translation)
- ❌ Fails on native ARM64 (`--platform linux/arm64`)
- The bug is intermittent but consistently reproducible with `--no-cache` builds
- Multi-project solutions with references trigger it more reliably than single projects
- Exit code: 132 (SIGILL - Illegal Instruction)

**Impact:**
Cannot build .NET 10 applications natively on ARM64 in macOS VZ environment. Workaround is to build for AMD64 and rely on Rosetta, but this defeats the purpose of native ARM64 support.

### Reproduction Steps

```
docker run --rm --platform linux/arm64 mcr.microsoft.com/dotnet/sdk:10.0 \
  sh -c 'dotnet new classlib -n Test'
```

The above fails intermittently but regularly, see sample output below:

```
> docker run --rm --platform linux/arm64 mcr.microsoft.com/dotnet/sdk:10.0 \
  sh -c 'dotnet new classlib -n Test'
The template "Class Library" was created successfully.

Processing post-creation actions...
Restoring /Test/Test.csproj:
  Determining projects to restore...
  Restored /Test/Test.csproj (in 30 ms).
Restore succeeded.


> docker run --rm --platform linux/arm64 mcr.microsoft.com/dotnet/sdk:10.0 \
  sh -c 'dotnet new classlib -n Test'
Illegal instruction (core dumped)
> docker run --rm --platform linux/arm64 mcr.microsoft.com/dotnet/sdk:10.0 \
  sh -c 'dotnet new classlib -n Test'
The template "Class Library" was created successfully.

Processing post-creation actions...
Restoring /Test/Test.csproj:
  Determining projects to restore...
  Restored /Test/Test.csproj (in 33 ms).
Restore succeeded.


> docker run --rm --platform linux/arm64 mcr.microsoft.com/dotnet/sdk:10.0 \
  sh -c 'dotnet new classlib -n Test'
Illegal instruction (core dumped)
```

### Expected behavior

Build succeeds

### Actual behavior

Build fails (intermittently)

### Regression?

_No response_

### Known Workarounds

Build an AMD64 image instead

### Configuration

Using SDK 10.0

### System Information

```bash
# Host CPU
$ sysctl machdep.cpu.brand_string
machdep.cpu.brand_string: Apple M4 Pro

# Docker/VM architecture
$ docker info | grep Architecture
Architecture: aarch64

# .NET SDK version in container
$ docker run --rm mcr.microsoft.com/dotnet/sdk:10.0 dotnet --version
10.0.101

# CPU features visible in container
$ docker run --rm mcr.microsoft.com/dotnet/sdk:10.0 cat /proc/cpuinfo | grep Features
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp sve2 flagm2 frint svei8mm svebf16 bf16 afp sme smei16i64 smef64f64 smei8i32 smef16f32 smeb16f32 smef32f32 sme2 smei16i32 smebi32i32
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Replace CONTEXT_GetSveLengthFromOS() calls in signal context handling with direct reads of sve->vl from the kernel-provided signal frame. The CONTEXT_GetSveLengthFromOS function executes the SVE 'rdvl' instruction, which causes SIGILL on platforms that have SME (streaming SVE) but not standalone SVE — such as Apple M4 under macOS Virtualization.Framework with Podman/Colima.

On these platforms, the Linux kernel includes an SVE_MAGIC record in signal frames (with vl=0 and minimal size) due to SME's streaming SVE mode, but the CPU does not support SVE instructions. When a signal fires (e.g. SIGUSR1 for activation injection), CONTEXTFromNativeContext sees the SVE record and calls rdvl, which triggers SIGILL. The SIGILL handler then tries to capture context again, hitting rdvl recursively.

The fix uses sve->vl from the signal frame directly, which is always available when an SVE context record is present. On real SVE hardware, sve->vl equals what rdvl would return. On SME-only platforms, sve->vl is 0, so the SVE register save/restore is correctly skipped.

Fixes #122608

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@janvorli PTAL

Pre-fix, `dotnet new classlib` run in a linux container on an M4 would fail about 5% of the time. Post-fix no failures were observed.

File: src/coreclr/pal/src/thread/context.cpp [hunk 1]
```diff
@@ -1255,7 +1259,11 @@ void CONTEXTFromNativeContext(const native_context_t *native, LPCONTEXT lpContex
...
         {
             //TODO-SVE: This only handles vector lengths of 128bits.
-            if (CONTEXT_GetSveLengthFromOS() == 16)
+            // Use sve->vl from the signal frame instead of CONTEXT_GetSveLengthFromOS()
+            // (which executes the SVE rdvl instruction) to avoid SIGILL on platforms
+            // that provide an SVE context record without supporting SVE instructions
+            // (e.g. Apple M4 with SME streaming SVE under Virtualization.Framework).
+            if (sve->vl == 16)
             {
                 _ASSERTE((sve->vl > 0) && (sve->vl % 16 == 0));
```
Comment (janvorli) [inline src/coreclr/pal/src/thread/context.cpp]: A nit - this assert is now useless

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by am11** [comment]
These are the only two usages, we can delete its definition:

```
src/coreclr/pal/src/arch/arm64/context2.S:303:    LEAF_ENTRY CONTEXT_GetSveLengthFromOS, _TEXT
src/coreclr/pal/src/arch/arm64/context2.S:306:    LEAF_END CONTEXT_GetSveLengthFromOS, _TEXT
src/coreclr/pal/src/include/pal/context.h:1628:    CONTEXT_GetSveLengthFromOS
src/coreclr/pal/src/include/pal/context.h:1637:CONTEXT_GetSveLengthFromOS(
```

Also, the comment can be reworded to avoid mentions of `CONTEXT_GetSveLengthFromOS` (after the definitions are deleted).

File: src/coreclr/pal/src/thread/context.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/pal/src/thread/context.cpp]: Do you want to replace this with the other assert suggested above?

**Comment by am11** [comment]
Other places using rdvl:

```
src/coreclr/jit/codegenarm64test.cpp:6016:    theEmitter->emitIns_R_I(INS_sve_rdvl, EA_8BYTE, REG_R0, -32); // RDVL <Xd>, #<imm>
src/coreclr/jit/codegenarm64test.cpp:6017:    theEmitter->emitIns_R_I(INS_sve_rdvl, EA_8BYTE, REG_R5, 0);   // RDVL <Xd>, #<imm>
src/coreclr/jit/codegenarm64test.cpp:6018:    theEmitter->emitIns_R_I(INS_sve_rdvl, EA_8BYTE, REG_R10, 5);  // RDVL <Xd>, #<imm>
src/coreclr/jit/codegenarm64test.cpp:6019:    theEmitter->emitIns_R_I(INS_sve_rdvl, EA_8BYTE, REG_R15, 31); // RDVL <Xd>, #<imm>
src/coreclr/jit/emitarm64.cpp:1134:        case IF_SVE_BC_1A: // rdvl
src/coreclr/jit/emitarm64sve.cpp:1627:        case INS_sve_rdvl:
src/coreclr/jit/instrsarm64sve.h:2103:INST1(rdvl,              "rdvl",                  0,                       IF_SVE_BC_1A,            0x04BF5000                                   )
src/coreclr/vm/arm64/asmhelpers.S:29:        rdvl    x0, 1
src/coreclr/vm/arm64/asmhelpers.asm:92:        rdvl    x0, 1
```

**Comment by AndyAyersMS** [comment]
> Other places using rdvl:

JIT usage should be ok. Let me check the helpers. Looks like they're only invoked after we have verified SVE support. So they seem ok too.
