### PR TITLE
Fix intrinsic testing add and subtract overflow helpers

### LINKED ISSUE #122728: Test failure: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddSaturate_short()
**Failed in:** [runtime-coreclr pgo 20251224.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1238670)

**Failed tests:**
```
coreclr windows arm64 Checked defaultpgo @ Windows.11.Arm64.Open
    - _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddSaturate_short()
```

**Error message:**
```
One or more scenarios did not complete as expected.
```

**Stack trace:**
```
   at JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddSaturate_short() in /__w/1/s/artifacts/tests/coreclr/obj/AnyOS.x64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/Sve.AddSaturate.short.cs:line 81
   at Program.<<Main>$>g__TestExecutor3544|0_3545(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by a74nh**
Fixes #122728

### CODE REVIEW

File: src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs [hunk 1]
```diff
@@ -3095,122 +3095,53 @@ private static byte UnsignedShift(byte op1, sbyte op2, bool rounding = false, bo
...
-            if ((op1 > 0) && (op2 > 0))
-            {
-                ovf = (result < 0);
-            }
-            else if ((op1 < 0) && (op2 < 0))
-            {
-                ovf = (result > 0);
-            }
-
-            return (result, ovf);
```
Comment (tannergooding) [inline src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs:3113]: Following the standard .NET pattern, this should be:
```csharp
private static bool TryAddSigned<T>(T left, T right, out T result)
    where T : IBinaryInteger<T>, ISignedNumber<T>
{
        result = left + right;
        return ((result ^ left) & ~(left ^ right)) < 0;
}

private static bool TryAddUnsigned<T>(T left, T right, out T result)
    where T : IBinaryInteger<T>, IUnsignedNumber<T>
{
        result = left + right;
        return result < left;
}
```

We have existing internal helpers that are well tested for saturation/overflow detection and documentation on how/why it works here: https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Scalar.cs,605fc3f5131cb762

```csharp
// For unsigned types, addition can only overflow up
// so we need to check if the result is less than one
// of the inputs and return MaxValue if it is.
//
// For signed types, addition can overflow in either
// direction. However, this can only occur if the signs
// of the inputs are the same and the sign of the result
// then differs. This simplifies to, given a = b + c:
//    ((a ^ b) & ~(b ^ c)) < 0
//
// This simplification works because all negative values
// have their most significant bit set, while all positive
// values have it clear. Consider the below:
//
//  p = p + p:    (0 ^ 0) & ~(0 ^ 0)  ->  0 & ~0  ->  0 & 1  ->  0        can  overflow and didnt
//  p = p + n:    (0 ^ 0) & ~(0 ^ 1)  ->  0 & ~1  ->  0 & 0  ->  0        cant overflow
//  p = n + p:    (0 ^ 1) & ~(1 ^ 0)  ->  1 & ~1  ->  1 & 0  ->  0        cant overflow
//  p = n + n:    (0 ^ 1) & ~(1 ^ 1)  ->  1 & ~0  ->  1 & 1  ->  1        can  overflow and did
//  n = p + p:    (1 ^ 0) & ~(0 ^ 0)  ->  1 & ~0  ->  1 & 1  ->  1        can  overflow and did
//  n = p + n:    (1 ^ 0) & ~(0 ^ 1)  ->  1 & ~1  ->  1 & 0  ->  0        cant overflow
//  n = n + p:    (1 ^ 1) & ~(1 ^ 0)  ->  0 & ~1  ->  0 & 0  ->  0        cant overflow
//  n = n + n:    (1 ^ 1) & ~(1 ^ 1)  ->  0 & ~0  ->  0 & 1  ->  0        can  overflow and didnt
//               |_______| |________|    |_| |__|    |_| |_|    |_|
//                   |          \_________|____\______|___\______|_______ produces 1 if the signs are the same, meaning overflow could occur
//                   |                    |           |          |
//                   \____________________\___________\__________|_______ produces 1 if the output signs differs from the first input, meaning overflow could occur
//                                                               |
//                                                               \_______ produces 1 if the input signs are the same and the output sign differs from that, meaning overflow did occur
//
// If we did overflow then a negative result needs to
// become MaxValue, while a positive result needs to become
// MinValue.
```

We then have an equivalent helper for subtraction further down from that.

Comment (tannergooding) [reply src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs:3113]: Reusing the existing logic and generic constraints helps remove much of the complexity here while still keeping it fast/efficient.

Comment (a74nh) [reply src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs:3113]: Agreed we should use existing routines. Not sure why they weren't used when this was added way back when. It's possible a that lot of this file could be factored away to generic routines.

Comment (a74nh) [reply src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs:3113]: Ah - the code you pointed to is in `System/Runtime/Intrinsics/Scalar.cs`, which I don't think we can just call because I don't think we can depend on an intrinsic in the intrinsic testing. I'll make a copy of the function instead.

Comment (a74nh) [reply src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs:3113]: Updated to use the suggested style, including Sub functions.

File: src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs [hunk 2]
```diff
@@ -3095,122 +3096,52 @@ private static byte UnsignedShift(byte op1, sbyte op2, bool rounding = false, bo
...
+            result = unchecked(left - right);
+            return left < right;
         }
 
-        public static sbyte AbsSaturate(sbyte op1) => op1 < 0 ? NegateSaturate(op1) : op1;
-
-        public static sbyte AddSaturate(sbyte op1, sbyte op2)
+        public static T1 AddSaturate<T1, T2>(T1 op1, T2 op2)
```
Comment (tannergooding) [inline src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs]: This one can also be simpler. It's just:
```csharp
if (!TryAddSigned(op1, op2, out T result))
{
    result = (result < 0) ? T.MaxValue : T.MinValue;
}
return result;
```

and
```csharp
if (!TryAddUnsigned(op1, op2, out T result))
{
    result = T.MaxValue;
}
return result;
```

-- same overall logic from: https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Scalar.cs,605fc3f5131cb762

Comment (a74nh) [reply src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs]: Done.

Had to remove the templating of AddSaturate, as otherwise it becomes `AddSaturateSigned()` and `AddSaturateUnsigned()`, and then many other files need updating.

Also had to add `TryAddSignedUnsigned<TSigned, TUnsigned>()` and `TryAddUnsignedSigned<TUnsigned, TSigned>()`

File: src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs [hunk 3]
```diff
@@ -3070,7 +3070,8 @@ private static byte UnsignedShift(byte op1, sbyte op2, bool rounding = false, bo
                 }
             }
 
-            (byte result, bool addOvf) = AddOvf(op1, rndCns);
+            byte result;
+            bool addOvf = TryAddUnsigned(op1, rndCns, out result);
```
Comment (tannergooding) [inline src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs]: nit: No need to fix this, but just as FYI you can do this, which is a bit more idiomatic in modern C#:
```suggestion
            bool addOvf = TryAddUnsigned(op1, rndCns, out byte result);
```

File: src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs [hunk 4]
```diff
@@ -3095,122 +3096,98 @@ private static byte UnsignedShift(byte op1, sbyte op2, bool rounding = false, bo
...
+            where TSigned   : IBinaryInteger<TSigned>, ISignedNumber<TSigned>
+            where TUnsigned : IBinaryInteger<TUnsigned>, IUnsignedNumber<TUnsigned>
         {
-            byte result = (byte)(op1 + op2);
-
-            bool ovf = (result < op1);
-
-            return (result, ovf);
+            result = unchecked(left + TSigned.CreateChecked(right));
+            return result < left;
```
Comment (tannergooding) [inline src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs]: Is this one correct? 

Presumably this is for `SUQADD` (signed saturating addition of unsigned value), in which case the implementation is converting `right` from `unsigned to signed` which will throw if it is greater than `TSigned.MaxValue`.

That seems incorrect because I'd expect, for example, that `-128 + 128` was valid and would produce `0`

File: src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs [hunk 5]
```diff
@@ -3095,122 +3096,98 @@ private static byte UnsignedShift(byte op1, sbyte op2, bool rounding = false, bo
...
+            TUnsigned left, TSigned right, out TUnsigned result)
+            where TUnsigned : IBinaryInteger<TUnsigned>, IUnsignedNumber<TUnsigned>
+            where TSigned   : IBinaryInteger<TSigned>, ISignedNumber<TSigned>
         {
-            sbyte result = (sbyte)(op1 - op2);
-
-            bool ovf;
-
-            if (op2 < 0)
+            if (right < TSigned.Zero)
```
Comment (tannergooding) [inline src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs]: nit:
```suggestion
            if (TSigned.IsNegative(right))
```

File: src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs [hunk 6]
```diff
@@ -3095,122 +3096,98 @@ private static byte UnsignedShift(byte op1, sbyte op2, bool rounding = false, bo
...
             {
-                ovf = (result < op1);
+                var mag = TUnsigned.CreateChecked(-right);
```
Comment (tannergooding) [inline src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs]: This seems "wrong" since it will fail for `TSigned.MinValue`.

I believe you rather just want `TUnsigned.CreateTruncating(-right)`, since all other values will have become positive while `right` and the two's complement representation is the same between `MinValue` and `(MaxValue + 1)`.

-- Noting this is only sensible if `TSigned` and `TUnsigned` are the same width.

File: src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs [hunk 7]
```diff
@@ -3095,122 +3096,98 @@ private static byte UnsignedShift(byte op1, sbyte op2, bool rounding = false, bo
...
+                result = unchecked(left - mag);
+                return left < mag;
```
Comment (tannergooding) [inline src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs]: Shouldn't this be checking `result > left`?

That is, we're subtracting two unsigned values, so we overflow if the new result is greater than the original input.

**Review by tannergooding — APPROVED** [review]
