### PR TITLE
Extend static constructor interpreter to support vtable-like structures

### LINKED ISSUE #114024: Support precompiling CCW vtables in ILC cctor interpreter (Native AOT)
### Related to #79204

As we're migrating the Microsoft Store to Native AOT, and also adopting Native AOT in Windows components, we're investigating all opportunities to improve performance and reduce size, as well as regressions from things that were handled better on .NET Native. One area that seems to be quite impactful due to the way the WinRT projections and interop stack work, is the codegen around CCW vtables. Currently, ILC is not able to fold these into constant blobs, meaning that we pay the initialization cost + **the static constructor** (and the cctor checks on every access) for:
- Every single IDIC implementation (ie. for every single projected interface)
- Every single statically visible generic instantiation (for async tasks, delegate types, collection types)

These add up to **thousands of types**, so there's a pretty good opportunity for improvements. .NET Native handled this via some special logic to initialize constant blobs for vtables, which Native AOT doesn't have. However, my thinking is that we could simply extend the support in ILC to interpret static constructor by making a couple of required APIs intrinsics, and making sure it can recognize common patterns.

For APIs that would need to be handled as intrinsics by ILC:
- [`ComWrappers.GetIUnknownImpl`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.comwrappers.getiunknownimpl)
- [`RuntimeHelpers.AllocateTypeAssociatedMemory`](https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.runtimehelpers.allocatetypeassociatedmemory)

Next to this, it should also be able to handle common patterns around:
- Copying constant vtables (from other pre-initialized vtable pointers) to memory locations
- Assigning `[UnmanagedCallersOnly]` method addresses to vtable slots

The idea is that ideally, ILC should be able to fold all of these vtables into a constant blob (like an RVA span field), and trim the cctor entirely.

Our expectation is that this should be doable because Native AOT can rely on the fact that:
- Types aren't unloaded (so it doesn't matter where each vtable is allocated, it can be any memory)
- The address of all `[UnmanagedCallersOnly]` method (or, any method in general) should be a constant
- The address of each entry from `ComWrappers.GetIUnknownImpl` should also be a constant that can be hardcoded by ILC

### Common patterns

I've prepared [a sharplab snippet](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ZEMfKhKV6mjQDEYqNgDm+bAwDu2KF15cnDABNeXGxgaRtqAHpIhnIASgYAITwYBgMAVS4Aay4Idy4GBQxQ8OpfDBkubEltJAZuEIAzVLI0zJy8rgNxSRoAbxoGIaYAZlqGHx4GAEFgXgAVCAAFKAgAKxgwPgguADVG4rCYJYwoBj6GJxgMNQYAXwYAXgYAcWvZheXVja3eHf3DtITlAABRxDTUQbDBy8BTYCrjSYYV7vOaLFbrTbbPYHErHU5gqFDAbUYZktrZXL5AFhABUhQOYSeDBBGUpnRpklpcV0fAEAAkYJIxDJcCxppJJBAwPCYPMAJ4i6a4XDS3iygIAWRg+Gg8pBGEVMAgjVZ7SpXR6cTQDFwvAAXsbTWyOtTGZI4uCIuThiJ8AB1RxiEVQMVvDAui3dMSSEFEn3DRpiACKHBk8qMFSgjWwKhADAgHGRtJBSO5ADIFO64AA+VPpzMyHMqNDxhMMJPTAIBNgwRr5wvF0vlCtVjBhWtdnt91uk9uJsS96QpAdFhglstxSvVmtLmApL2Quc+4gAdhZSLiY7CELJdxo96P0QYpASAFEENgeqkiniPLwMAAC0CXhYC2Bg8DtJwuAEHhcBocpKmqcYGmwZomFINIjFwEUtjxaNJCoagSTJYgxmYOokRmNEvkxX5/lxI5gXOS5rluB5nnDD50W+LE/hxQF8VBQ94xhOEEQoiZyhRDBuNon5sQBPFgUJY9zjbYZiBQWl6WvGpnhBLSdJ5bg+RgQVhVFcVJWlWUFSVFU1Q1bVdSgfVDRFE1WWw3DBII+IbTtR0vKMhJ6SQES1LJEtIw5d1uT05kYvNOLxy5OJYvyAjxRojEFP4pSmNOCENKGPSAG0RgAXWZEEAiFGAnFleluFcKorgCcqXOAGRiAAVmxKqAB4jJtDgRxtF5xoCHSbXKGst3DAxeACawouGCqUBqgz6ukJqKhamDsHamBOu63qBv44bRqknhaTmngFvLcNeX0IRJEggA5L8YFvBMKr67aWV2xrmvqI6TrOnUeqgfrBpG7SHowe6GHmxbrnmKAOFwDAABkYAUIUSvWoYzwvcor3dP6hkfeNysyNrnFOoRqmkUMAHkuEkfUWclEQuAUXBmXKjynRBXnJH5hRzthy6djiKqFdEqBYVlcZpKWlbcEM7SGCA4JgTGkdUZWkRTMm6adJN1a4njEiE1pXhTcLKZnjoanyUdrXmS4DhJWJ9syfd+NabU+mIaZgIJdFTnufF1mpaF54RaNLyJalmW4f4hWlbUsS1ckjXrlegR3q+n6dfpfXcEN27kYw76BFttT7Z9WkyEb1JnnqnM/Zub0EyDj3Q7JcPGY66OOa5nmE52QXhdFtPZ4FzO5a4HOquV1WJPIOoi4wTHsbxgmhUrvXAIN04karrGcfxwmPTt0r11OI/76FZlg6PQPzy/u8HwiM+EY75PzfkKIJf8QFwF/kgrwaCsEMDwTKMYbwyFJKoXQq0AwPksT4R6KQfo8YyKImknJPKfEGKCWYhcK4Nx7jMi4rlXi9EBLKQJJFMk+cd6UX3mQ5hilGJAnYU/EmWEuA4VwUcTkul3S1WweI3yeJpEmT0AKIUIYxQSilDKCo9kYDKlVGAdUFQtQ6j1AaVOzocF4SOARV8gUHRi3kRImx0hOSegDg7M07I3RpQSrI54yUfECTpBlFKWUeg5U+OQlhhUhFQE8T6PStZNarWZM9a4y1VoezJMkmsL1TJvQ+iqTu6SCmqJgGXEpP0ckbR3OGQ+d8T76QYBkg+t9j4P0SeSMmw4eCUzSsPAeQwx7HUjpPXAscZ58znknBgKdPKmnTnPVe2IN5b3Ei0XeqMpipO1kZc+l8oBGzutbM2PALYrStk7G2Ij2xeyji7ZEbtalDAeXM32/thk9N/kM7+wxRmQwmVM+OMyBZzIWWLZZK9oYXTWYrTeecVabPVrs4uhTS7FNwJ3M+1da5lgbj9ZuZJW6ew7j9ZkPdsB926aRX5IdvmAvGazGO09QWS1mQvSx7KM6wtlvC3OnDkUF22fvRpnTT4HLxVfHZ9dX5NIfsS4YpLoryolS0r+z8h4MuoKHYhGDUg4yxuBTKITejESIWMEG+0YCHXHqdLqfKs47GuojV4lsbRGRRvNBg9Y3KNmzLmX6lrAgNRtXasZHVHX4Bhs6rgrqUbjUejMbsvZGge2IdasGrVI0OtWVdBGiafV7hSBCUOiFUE1ANbaV+JrrGCU5IQtSmaw3ZojlG/NLrC2XJmp67S3rk1+ozCg5swbm1WtbQdcG9qoYxrhQWm6SaMA1hTdOdNIas1TpzZDaNsa14JpOcuhgJbcBjtIhOvabaZ27vnV2xdE13VXIHUevZGaL2gy3e2vNTr93drrs+ld5SzJVOxTUjdk7bXTtzbOvd8MboPp9Q0jp79JBlqAA) with the common patterns we'd need handling:
- `IUnknown` vtable
- Vtables built by directly assigning to vtable offsets
- Vtables built by assigning through a vtable type

cc. @jevansaks

### LINKED ISSUE #114133: [API Proposal]: 'ComWrappers' methods to get runtime-provided 'IUnknown' CCW vtable entries
#### Contributes to #114024

Same motivation and context as the linked issue. This proposal is for an ILC-friendly set of APIs to build `IUnknown` CCW vtables.
Original suggestion for the shape by @jkotas in https://github.com/dotnet/runtime/issues/114024#issuecomment-2770306888.

> [!IMPORTANT]
> We **can't** just use the existing `ComWrappers.GetIUnknownImpl`, as its shape is too difficult for ILC to interpret it.

### API Proposal

```csharp
namespace System.Runtime.InteropServices;

public abstract class ComWrappers
{
    public static IntPtr GetIUnknownQueryInterfaceImpl();
    public static IntPtr GetIUnknownAddRefImpl();
    public static IntPtr GetIUnknownReleaseImpl();
}
```

### API Usage

```csharp
// Eg. in WinRT.Runtime.dll
internal unsafe struct IInspectableVftbl
{
    public delegate* unmanaged[MemberFunction]<void*, Guid*, void**, int> QueryInterface;
    public delegate* unmanaged[MemberFunction]<void*, uint> AddRef;
    public delegate* unmanaged[MemberFunction]<void*, uint> Release;
    public delegate* unmanaged[MemberFunction]<void*, uint*, Guid**, int> GetIids;
    public delegate* unmanaged[MemberFunction]<void*, nint*, int> GetRuntimeClassName;
    public delegate* unmanaged[MemberFunction]<void*, int*, int> GetTrustLevel;
}

internal static unsafe class IInspectableImpl
{
    [FixedAddressValueType]
    private static readonly IInspectableVftbl Vftbl;
    
    public static nint AbiToProjectionVftablePtr => (nint)Unsafe.AsPointer(ref Unsafe.AsRef(in Vftbl));

    static IInspectableImpl()
    {
        Vftbl.QueryInterface = (delegate* unmanaged[MemberFunction]<void*, Guid*, void**, int>)ComWrappers.GetIUnknownQueryInterfaceImpl();
        Vftbl.AddRef = (delegate* unmanaged[MemberFunction]<void*, uint>)ComWrappers.GetIUnknownAddRefImpl();
        Vftbl.Release = (delegate* unmanaged[MemberFunction]<void*, uint>)ComWrappers.GetIUnknownReleaseImpl();
        Vftbl.GetIids = &GetIids;
        Vftbl.GetRuntimeClassName = &GetRuntimeClassName;
        Vftbl.GetTrustLevel = &GetTrustLevel;
    }

    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvMemberFunction)])]
    private static int GetIids(void* thisPtr, uint* iidCount, Guid** iids)
    {
        *iidCount = 0;
        *iids = null;

        return 0;
    }

    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvMemberFunction)])]
    private static int GetRuntimeClassName(void* thisPtr, nint* className)
    {
        *className = default;

        return 0;
    }

    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvMemberFunction)])]
    private static int GetTrustLevel(void* thisPtr, int* trustLevel)
    {
        *trustLevel = 0;

        return 0;
    }
}
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
This makes it possible to identify `struct`s that look like vtables (all fields are `delegate*` and some extras) and represents them differently within the interpreter. The different representation allows the interpreter to capture relocs within the data structure (the normal byte array approach wouldn't be able to represent these since the numerical value of a function pointer is only known at runtime).

I had to extend things so that we can allow byrefs to pass through as nint in places. Hopefully I found all the places where we would try to cast things to `ValueTypeValue` within the interpreter and we now allow `nint`-typed stack slots to also hold a byref.

Fixes #114024
Resolves #114133

Cc @dotnet/ilc-contrib

@Sergio0694 please have a look at the test to see if this is the pattern that would work for CsWinRT.

### CODE REVIEW

File: src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs [hunk 1]
```diff
@@ -1674,6 +1675,82 @@ public static void Run()
...
+    }
+
+    public static unsafe class IInspectableImpl
+    {
+        [FixedAddressValueType]
+        public static readonly IInspectableVftbl Vtbl;
+
+        static IInspectableImpl()
+        {
+            *(IUnknownVftbl*)Unsafe.AsPointer(ref Vtbl) = IUnknownImpl.Vtbl;
```
Comment (Sergio0694) [inline src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs:1701]: Oh interesting, I thought the plan was not to support this. Is the advice for us to just do this in all our vtables then, rather than doing `ComWrappers.GetIUnknownImpl` for the `IUnknown` slots every time? Does this mean we can also do the same to copy the `IInspectable` vtable too as the first 6 slots, for CCW vtables that are inspectables?

Comment (MichalStrehovsky) [reply src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs:1701]: Yes, it looked allowable, hopefully Roslyn won't come up with too many ways to emit this in IL. The interpreter can be fragile, this has a happy path around `stobj` instruction.

Comment (MichalStrehovsky) [reply src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs:1701]: (Like I wrote in the issue, we can only make guarantees around IL sequences, not about C# source code. But since this is now a test in the repo, we'll get an advance notice if a break is incoming...)

**Comment by am11** [comment]
Does it also resolve/help with https://github.com/dotnet/runtime/issues/83043?

**Review by jkotas — APPROVED** [review]
LGTM, assuming outer loop passed. Thank you!

File: src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs [hunk 2]
```diff
@@ -1674,6 +1675,82 @@ public static void Run()
...
+    }
+
+    public unsafe struct IUnknownVftbl
+    {
+        public delegate* unmanaged[MemberFunction]<void*, Guid*, void**, int> QueryInterface;
+        public delegate* unmanaged[MemberFunction]<void*, uint> AddRef;
+        public delegate* unmanaged[MemberFunction]<void*, uint> Release;
+    }
+
+    public unsafe struct IInspectableVftbl
```
Comment (Sergio0694) [inline src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs:1725]: Can we also add a test for:
  - A vtable that builds on top of `IInspectable`, for good measure? So that we'd have both one that has `IUnknown` as base (ie. `IInspectable`), and one that has another combined vtable as a base (ie. `IInspectable`).
  - Having derived vtables copy the base via a property (with a cast), not via the field. We'd like to keep the vtable fields internal and an implementation detail, if possible.

Basically these changes:

```csharp
// Add this to IInspectableImpl
public static nint AbiToProjectionVftablePtr
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    get => (nint)Unsafe.AsPointer(ref Unsafe.AsRef(in Vtbl));
}

// Add these new types
internal unsafe struct IStringableVftbl
{
    public delegate* unmanaged[MemberFunction]<void*, Guid*, void**, int> QueryInterface;
    public delegate* unmanaged[MemberFunction]<void*, uint> AddRef;
    public delegate* unmanaged[MemberFunction]<void*, uint> Release;
    public delegate* unmanaged[MemberFunction]<void*, uint*, Guid**, int> GetIids;
    public delegate* unmanaged[MemberFunction]<void*, nint*, int> GetRuntimeClassName;
    public delegate* unmanaged[MemberFunction]<void*, int*, int> GetTrustLevel;
    public new delegate* unmanaged[MemberFunction]<void*, nint*, HRESULT> ToString;
}

internal static unsafe class IStringableImpl
{
    public static readonly IStringableVftbl Vtbl;

    static IStringableImpl()
    {
        *(IInspectableVftbl*)Unsafe.AsPointer(ref Vtbl) = *(IInspectableVftbl*)IInspectableImpl.AbiToProjectionVftablePtr;

        Vtbl.ToString = &ToString;
    }

    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvMemberFunction)])]
    private static HRESULT ToString(void* thisPtr, nint* value)
    {
        return 0;
    }
}
```

With these too, we should pretty much cover all scenarios we'd have in CsWinRT 🙂

**Comment by MichalStrehovsky** [comment]
> Does it also resolve/help with #83043?

No, this is not usable for that. This is a special happy path for structs that look like vtables only.

File: src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs (hunk 2 above)
Comment (MichalStrehovsky) [reply src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs:1725]: > Having derived vtables copy the base via a property (with a cast), not via the field. We'd like to keep the vtable fields internal and an implementation detail, if possible.

This will have to be a separate PR, that very likely requires _several_ new features.

Comment (jkotas) [reply src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs:1725]: > We'd like to keep the vtable fields internal and an implementation detail, if possible.

Is it really an implementation detail?

The public contract is that it points to a vtable with slots of specific pointer types. If we were to expose an API like this in .NET runtime, I do not expect that we would try to hide the public contract behind opaque nint. We would use the precise strong types instead.

Comment (Sergio0694) [reply src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs:1725]: > "If we were to expose an API like this in .NET runtime, I do not expect that we would try to hide the public contract behind opaque nint. We would use the precise strong types instead."

For context, one of the reasons we use `nint` for all these vtables is also to match what ComWrappers does. All of these vtables are ultimately assigned to `ComInterfaceEntry` values, which all just have a `nint Vtable` field. That's where our design in CsWinRT comes from here.

**Comment by MichalStrehovsky** [comment]
/ba-g no need to wait for outerloop, win-x86 build is now good

**Comment by AaronRobinsonMSFT** [comment]
@MichalStrehovsky Thanks for making this work without a new API <3
