### PR TITLE
Fixing test failing on arm64

### LINKED ISSUE #36087: System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected fails on Linux ARM64
```
System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected(format: "tetie", values: [-1, 0, 1, 2, 3], expected: [10, 1, 0, 1, 1, ...]) [FAIL]
      Exception of type 'Xunit.Sdk.AssertActualExpectedException' was thrown.
      Expected: 10, 1, 0, 1, 1, 2, 10, 1, 3
      Actual:   255, 255, 255, 255, 1, 0, 1, 1, 2, 10, 1, 3
      Stack Trace:
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(368,0): at System.AssertExtensions.Equal[T](T[] expected, T[] actual)
        /_/src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs(49,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected(String format, Object[] values, Byte[] expected)
    System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected(format: "{tetie}", values: [-1, 0, 1, 2, 3], expected: [48, 9, 10, 1, 0, ...]) [FAIL]
      Exception of type 'Xunit.Sdk.AssertActualExpectedException' was thrown.
      Expected: 48, 9, 10, 1, 0, 1, 1, 2, 10, 1, 3
      Actual:   48, 12, 255, 255, 255, 255, 1, 0, 1, 1, 2, 10, 1, 3
      Stack Trace:
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(368,0): at System.AssertExtensions.Equal[T](T[] expected, T[] actual)
        /_/src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs(49,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected(String format, Object[] values, Byte[] expected)
```

Failed on rolling build:
- Linux_arm64
- Alpine.38_arm64

https://dev.azure.com/dnceng/public/_build/results?buildId=635948&view=ms.vss-test-web.build-test-results-tab

This failed from a manual build I queued and these tests where just added in: 
https://github.com/dotnet/runtime/pull/35380

cc: @joperezr @dotnet/runtime-infrastructure

### PR DESCRIPTION
**Pull request by joperezr**
Fixes #36087 

The test was sending the wrong object which made it behave differently on arm64 and x64 archs. This fix will now send a valid payload that matches the format, which could now be converted and should have the same expected values across OSes and platforms.

cc: @bartonjs

### CODE REVIEW

**Comment by joperezr** [comment]
FYI: I've manually triggered a rolling build from my PR to ensure the tests run on arm64 and pass.

File: src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs [hunk 1]
```diff
@@ -30,8 +30,8 @@ public static IEnumerable<object[]> Encode_TestData()
             yield return new object[] { "[]", new object[] { "a" }, (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) ? new byte[] { 49, 132, 0, 0, 0, 0 } : new byte[] { 49, 0 } };
             yield return new object[] { "n", new object[] { "a" }, new byte[] { 5, 0 } };
 
-            yield return new object[] { "tetie", new object[] { -1, 0, 1, 2, 3 }, (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) ? new byte[] { 255, 1, 0, 1, 1, 2, 10, 1, 3 } : new byte[] { 10, 1, 0, 1, 1, 2, 10, 1, 3 } };
-            yield return new object[] { "{tetie}", new object[] { -1, 0, 1, 2, 3 }, (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) ? new byte[] { 48, 132, 0, 0, 0, 9, 255, 1, 0, 1, 1, 2, 10, 1, 3 } : new byte[] { 48, 9, 10, 1, 0, 1, 1, 2, 10, 1, 3 } };
+            yield return new object[] { "tetie", new object[] { 128, 0, 133, 2, 3 }, new byte[] { 128, 1, 0, 133, 1, 2, 10, 1, 3 } };
+            yield return new object[] { "{tetie}", new object[] { 128, 0, 133, 2, 3 }, (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) ? new byte[] { 48, 132, 0, 0, 0, 9, 128, 1, 0, 133, 1, 2, 10, 1, 3 } : new byte[] { 48, 9, 128, 1, 0, 133, 1, 2, 10, 1, 3 } };
```
Comment (safern) [inline src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs:34]: Nit: to be consistent we could use PlatformDetecion.IsWindows

**Review by safern — APPROVED** [review]

File: src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs (hunk 1 above)
Comment (joperezr) [reply src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs:34]: That is what I initially had on my original PR, but @bartonjs suggested to use RuntimeInformation.IsOSPlatform instead (which is what PlatformDetection is doing anyways). I'm happy to change it either way, don't really have a preference, although this whole test assmbly is using RuntimeInformation so if we want to change it I'll  have to do it for the rest of the test project.

Comment (safern) [reply src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs:34]: Ok, leave as is for the reason that all the test assembly uses it that way, but I believe most of the test assemblies use PlatformDetection, either way is fine.

**Review by bartonjs — APPROVED** [review]
