### PR TITLE
Frozen objects should be identified as Gen2 in the handle table

### LINKED ISSUE #85234: Test failure Interop\\MarshalAPI\\IUnknown\\IUnknownTest\\IUnknownTest.cmd
**Failed in:** [runtime-coreclr gcstress-extra 20230423.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249374&view=ms.vss-test-web.build-test-results-tab&runId=4822668&resultId=120375&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open
    - Interop\\MarshalAPI\\IUnknown\\IUnknownTest\\IUnknownTest.cmd
coreclr windows x86 Checked gcstress0xc_zapdisable_heapverify1 @ Windows.10.Amd64.Open
    - Interop\\MarshalAPI\\IUnknown\\IUnknownTest\\IUnknownTest.cmd
coreclr windows x86 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open
    - Interop\\MarshalAPI\\IUnknown\\IUnknownTest\\IUnknownTest.cmd
coreclr windows x64 Checked gcstress0xc_zapdisable_heapverify1 @ Windows.10.Amd64.Open
    - Interop\\MarshalAPI\\IUnknown\\IUnknownTest\\IUnknownTest.cmd
coreclr windows arm64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.11.Arm64.Open
    - Interop\\MarshalAPI\\IUnknown\\IUnknownTest\\IUnknownTest.cmd
coreclr windows arm64 Checked gcstress0xc_zapdisable_heapverify1 @ Windows.11.Arm64.Open
    - Interop\\MarshalAPI\\IUnknown\\IUnknownTest\\IUnknownTest.cmd
```

**Error message:**
```
 
Assert failure(PID 3424 [0x00000d60], Thread: 1892 [0x0764]): !&quot;Fatal Error in HandleTable.&quot;

CORECLR! BlockVerifyAgeMapForBlocks + 0x12C (0x00007fff`4507d98c)
CORECLR! TableScanHandles + 0x24D (0x00007fff`4507e15d)
CORECLR! HndVerifyTable + 0xE2 (0x00007fff`4507b4e2)
CORECLR! Ref_VerifyHandleTable + 0x11F (0x00007fff`45081ecf)
CORECLR! WKS::gc_heap::verify_heap + 0xD2A (0x00007fff`4510333a)
CORECLR! WKS::gc_heap::gc1 + 0x95F (0x00007fff`450e531f)
CORECLR! WKS::gc_heap::garbage_collect + 0x74A (0x00007fff`450e495a)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x452 (0x00007fff`450cc592)
CORECLR! WKS::GCHeap::GarbageCollect + 0x246 (0x00007fff`450cc0c6)
CORECLR! WKS::GCHeap::StressHeap + 0x5F0 (0x00007fff`450cf4f0)
    File: D:\a\_work\1\s\src\coreclr\gc\handletablescan.cpp Line: 929
    Image: C:\h\w\BCAA0A12\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\BCAA0A12\w\A2980904\uploads\Reports\Interop.MarshalAPI\IUnknown\IUnknownTest\IUnknownTest.output.txt
Raw output:
BEGIN EXECUTION
 &quot;C:\h\w\BCAA0A12\p\corerun.exe&quot; -p &quot;System.Reflection.Metadata.MetadataUpdater.IsSupported=false&quot; -p &quot;System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true&quot;  IUnknownTest.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 4/23/2023 11:15:48 PM
Processing C:\cores\corerun.exe.3424.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe -c &quot;$&lt;C:\h\w\BCAA0A12\t\tmpscz23x.tmp&quot; -z &quot;C:\cores\corerun.exe.3424.dmp&quot;
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.3424.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\BCAA0A12\p\PDB
Symbol search path is: C:\h\w\BCAA0A12\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Sun Apr 23 23:15:52.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:42:04.209
Process Uptime: 0 days 0:00:04.000
...............................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(d60.764): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
KERNELBASE!RaiseFailFastException+0xae:
00007fff`72bb98ce 803d4d76120000  cmp     byte ptr [KERNELBASE!local_unwind+0x7fd2 (00007fff`72ce0f22)],0 ds:00007fff`72ce0f22=00
0:006&gt; cdb: Reading initial command &#39;$&lt;C:\h\w\BCAA0A12\t\tmpscz23x.tmp&#39;
0:006&gt; .load C:\Users\runner\.dotnet\sos\sos.dll
0:006&gt; ~*k

   0  Id: d60.f48 Suspend: 0 Teb: 00000078`8d824000 Unfrozen
Child-SP          RetAddr           Call Site
00000078`8db7dd08 00007fff`72b34d7f ntdll!ZwWaitForMultipleObjects+0x14
00000078`8db7dd10 00007fff`44c55a76 KERNELBASE!WaitForMultipleObjectsEx+0xef
00000078`8db7e010 00007fff`44c56023 coreclr!Thread::DoAppropriateAptStateWait+0x116
00000078`8db7e0e0 00007fff`44c5fc5d coreclr!Thread::DoAppropriateWaitWorker+0x3b3
00000078`8db7e330 00007fff`44c55bb6 coreclr!`Thread::DoAppropriateWait&#39;::`11&#39;::__Body::Run+0x9d
00000078`8db7e390 00007
```

**Stack trace:**
```
    at Interop_MarshalAPI._IUnknown_IUnknownTest_IUnknownTest_._IUnknown_IUnknownTest_IUnknownTest_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by cshung**
Fixes #85234

### CODE REVIEW

File: src/coreclr/gc/handletablescan.cpp [hunk 1]
```diff
@@ -271,6 +271,17 @@ struct ScanQNode
...
 
+/**
+ * WhichGeneration
+ *
+ * Determine the generation of an object (in which frozen objects are identified as Gen2)
+ */
+int WhichGeneration(_UNCHECKED_OBJECTREF * obj)
+{
+    int generation = g_theGCHeap->WhichGeneration(obj);
+    return generation == g_theGCHeap->GetMaxGeneration() : generation;
```
Comment (jkotas) [inline src/coreclr/gc/handletablescan.cpp:282]: (I do not think this is going to compile. It is missing `?`.)

`GetMaxGeneration` is a virtual call. Should we use `max_generation` constant instead? It should be accessible in this file already.

**Comment by jkotas** [comment]
Does `HndWriteBarrierWorker` need the same change? `

Is there going to be perf impact from this change? Would it be better to allow the clump generation to be truncted int32 maxvalue?

File: src/coreclr/gc/handletablepriv.h [hunk 2]
```diff
@@ -942,3 +942,7 @@ void CALLBACK BlockVerifyAgeMapForBlocks(PTR_TableSegment pSegment, uint32_t uBl
 PTR_TableSegment CALLBACK xxxAsyncSegmentIterator(PTR_HandleTable pTable, TableSegment *pPrevSegment, CrstHolderWithState *pCrstHolder);
 
 /*--------------------------------------------------------------------------*/
+
+#ifndef DACCESS_COMPILE
+int WhichGeneration(_UNCHECKED_OBJECTREF obj);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/gc/handletablepriv.h:947]: A comment here is likely warranted. The policy decision being made here is something that could be confusing, especially since this is in the handle table header.

File: src/coreclr/gc/handletable.cpp [hunk 3]
```diff
@@ -24,6 +24,19 @@
 DWORD g_dwHandles = 0;
 #endif // ENABLE_PERF_COUNTERS || FEATURE_EVENT_TRACE
 
+#ifndef DACCESS_COMPILE
+
+#ifndef INT_MAX
+#define INT_MAX       2147483647
+#endif
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/gc/handletable.cpp:31]: Under what conditions is this value not set?

Comment (cshung) [reply src/coreclr/gc/handletable.cpp:31]: Linux. the previous CI build indicates that and I can repro that locally.

Comment (AaronRobinsonMSFT) [reply src/coreclr/gc/handletable.cpp:31]: Okay. Thanks.

Comment (jkotas) [reply src/coreclr/gc/handletable.cpp:31]: Include the right header instead?

**Comment by AaronRobinsonMSFT** [comment]
I have verified locally that this fixes https://github.com/dotnet/runtime/issues/85234

**Review by Maoni0 — APPROVED** [review]
LGTM, just a trivial comment I had when doing CR with Andrew which was to change the `WhichGeneration` to a more descriptive name so someone who reads the code doesn't always have to come to the header file to read that comment.
