### PR TITLE
JIT: fix incorrect scale in genCreateAddrMode + no-opt

### LINKED ISSUE #75312: Calling GetControllingUnknown () generates an assert
Reported by @ocallesp. 

[severity:I’m unable to use this version]

I have a project dll ATL (COM).

The project has enabled .NET Core Runtime Support (/ clr: netcore) (NET 6.0).

In this project when the GetControllingUnknown() function is called we have an assert.

image

IUnknown* _GetRawUnknown() throw() 

{ ATLASSERT(_GetEntries()[0].pFunc == _ATL_SIMPLEMAPENTRY); return (IUnknown*)((INT_PTR)this+_GetEntries()->dw); } \

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/75312

The problem is basically an incorrect behavior of genCreateAddrMode for the following tree:
```
N009 ( 11,  9) [000008] -------N---                         *  ADD       int
N007 ( 10,  8) [000006] -------N---                         +--*  ADD       int
N001 (  3,  2) [000000] -c---------                         |  +--*  LCL_VAR   int    V00 arg0
N006 (  7,  6) [000005] -------N---                         |  \--*  LSH       int
N004 (  6,  5) [000003] -----------                         |     +--*  MUL       int
N002 (  1,  1) [000001] -----------                         |     |  +--*  CNS_INT   int    3
N003 (  1,  1) [000002] -c---------                         |     |  \--*  CNS_INT   int    0
N005 (  1,  1) [000004] -c---------                         |     \--*  CNS_INT   int    2
N008 (  1,  1) [000007] -c---------                         \--*  CNS_INT   int    1
```
for which, `genCreateAddrMode` returns:

base = arg0
idx = nullptr
scale = 0
offset = 4

while offset should be 1

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
cc @jeffschwMSFT. Once we complete this PR, we will backport this to 7.0 and 6.0.

**Comment by AndyAyersMS** [comment]
Jit stress failures look like known issues:
* https://github.com/dotnet/runtime/issues/74900 (fix in PR)
* https://github.com/dotnet/runtime/issues/74631 (test was supposed to be disabled, but isn't yet)

**Comment by AndyAyersMS** [comment]
So the bug was an uninitialized local? How could we have not caught this before now?

**Comment by kunalspathak** [comment]
> So the bug was an uninitialized local? How could we have not caught this before now?

That's exactly I was wondering. Why it needed complex C++ / CLI *only* to reproduce?

**Comment by EgorBo** [comment]
> So the bug was an uninitialized local? How could we have not caught this before now?

Ah, no, that change is unrelated, let me remove the redundant initialization actually,
the problem is in zero scale, it's not respected.

**Comment by EgorBo** [comment]
> Why it needed complex C++ / CLI only to reproduce?

It's not C++ specific, it's just that `x * 0` _rarely_ makes it to genAddrMode phase - when optimizations are enabled it's folded long before it reach the phase. In debug mode it's hard to get it anyhow since e.g. Roslyn folds `x * 0` to `0` even in Debug mode with `<Optimize>false</Optimize>`

**Comment by kunalspathak** [comment]
> the problem is in zero scale, it's not respected.

Make sense.

**Review by kunalspathak — APPROVED** [review]
LGTM

File: src/coreclr/jit/codegencommon.cpp [hunk 1]
```diff
@@ -1410,14 +1417,22 @@ bool CodeGen::genCreateAddrMode(
...
             /* Get hold of the array index and see if it's a constant */
-            if (index->IsIntCnsFitsInI32())
+            else if (index->IsIntCnsFitsInI32())
             {
                 /* Get hold of the index value */
                 ssize_t ixv = index->AsIntConCommon()->IconValue();
 
                 /* Scale the index if necessary */
-                ixv *= tmpMul;
+                if (tmpMul)
```
Comment (kunalspathak) [inline src/coreclr/jit/codegencommon.cpp:1432]: So its ok to have `tmpMul == 0` here from the `else` on line 1417 and not scale?

Comment (EgorBo) [reply src/coreclr/jit/codegencommon.cpp:1432]: Looks like it can be but only only if we also disable jit optimizations and write IL for `array[1 + 2]` because Roslyn will fold cns + cns too again (even in Debug mode)

Comment (EgorBo) [reply src/coreclr/jit/codegencommon.cpp:1432]: Actually, let me run a few more tests, probably some parts of this logic can be removed

Comment (EgorBo) [reply src/coreclr/jit/codegencommon.cpp]: @kunalspathak so I've slightly changed the logic - the whole block can be removed in theory but it produced several Tier0 regressions so I decided to keep it + special handled zero index or zero scale, so if `optGetArrayRefScaleAndIndex` returns either 0 or non-zero but `index` represents `0` then we drop the whole index part.

Comment (kunalspathak) [reply src/coreclr/jit/codegencommon.cpp]: What happens for `!(rv2->OperIs(GT_MUL, GT_LSH) && (rv2->gtGetOp2()->IsCnsIntOrI()))` where we set `index = rv2`?

```c++
else
{
    /* May be a simple array. rv2 will points to the actual index */

    index  = rv2;
    tmpMul = mul;
}
```

Comment (EgorBo) [reply src/coreclr/jit/codegencommon.cpp]: @kunalspathak good point, it explains a single regression in the jit-diffs, but overall the code as is correct, it's just that the block you highlighted handles constant index that is converted to constant offset (this path is never hit in optimized code from what I see)

Comment (EgorBo) [reply src/coreclr/jit/codegencommon.cpp]: Let me push a quick change

Comment (EgorBo) [reply src/coreclr/jit/codegencommon.cpp]: @kunalspathak should be correct now and zero diff

**Review by kunalspathak — APPROVED** [review]
LGTM. Just double check if there are zero diffs for all archs before merging.

**Comment by EgorBo** [comment]
Yeah, the diff is empty but there is a conflict

**Comment by EgorBo** [comment]
@kunalspathak could you also approve the backport - https://github.com/dotnet/runtime/pull/75560
