### PR TITLE
Fix a race condition in the thread pool

### LINKED ISSUE #67545: [arm64] Perf_FileStream.FlushAsync benchmark hangs on Debian 11
Reported by @carlossanlop offline. Carlos has hit this issue on Debian 11 arm64 with WSL2.

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
python3 ./performance/scripts/benchmarks_ci.py --architecture arm64 -f net7.0 --filter '*Perf_FileStream.FlushAsync*'
```

[Source](https://github.com/dotnet/performance/blob/3edf4c3149f5c903777f13af9b08b562b1672302/src/benchmarks/micro/libraries/System.IO.FileSystem/Perf.FileStream.cs#L418-L426):

```log
using (FileStream fileStream = new FileStream("repro.txt", FileMode.Create, FileAccess.Write, FileShare.Read, 4096, FileOptions.None))
{
    for (int i = 0; i < 1024; i++)
    {
        fileStream.WriteByte(default);

        await fileStream.FlushAsync();
    }
}
```

In theory it could be an IO issue, but we have not touched `FileStream` for a few months and I suspect that it's a runtime bug similar to #64980.

@janvorli @jkotas what would be the best way to determine the reason of the hang on Linux?

### PR DESCRIPTION
**Pull request by kouvel**
There is a case where on a work-stealing queue, both `LocalPop()` and `TrySteal()` fail when running concurrently, and lead to a case where there is a work item but no threads are released to process it. Fixed to always ensure that there's a thread request when there was a missed steal. Also when `LocalPop()` fails, the thread does not attempt to pop anymore and that can be an issue if that thread is the last thread to look for work items. Fixed to always check the local queue. The issues were introduced by https://github.com/dotnet/runtime/pull/64834.

Fixes https://github.com/dotnet/runtime/issues/67545

### CODE REVIEW

**Comment by danmoseley** [comment]
Is a unit test feasible here? If nothing else, something derived from the perf test, even if it only would catch this bug sporadically.

**Review by mangod9 — APPROVED** [review]

**Comment by adamsitnik** [comment]
@kouvel @mangod9 is there any chance we could include this fix in Preview4 (snaps today at 2 PM?)? This would allow to cover it in Perf Run for Preview4

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by kouvel** [comment]
> is there any chance we could include this fix in Preview4 (snaps today at 2 PM?)? This would allow to cover it in Perf Run for Preview4

The test appears to occasionally be timing out on Linux_musl x64. I'd like to get this fix into preview 4 if possible. I think I'll disable it for this PR with an active issue and investigate that separately, if it's a product issue it would likely be a different one.

**Comment by danmoseley** [comment]
You can add `PlatformDetection.IsNotAlpine` and `[ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotAlpine))]` of course.

**Comment by kouvel** [comment]
It didn't fail in the first set of runs and failed in the second set. I'm not sure where else it may fail occasionally.

**Comment by kouvel** [comment]
It might just be a few too many iterations on some machines, especially with a checked runtime. I'll try reducing the iterations.

**Comment by kouvel** [comment]
Combined with the previous CI runs and the latest harmless commit I'll go ahead and merge to make it into preview 4

File: src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs [hunk 1]
```diff
@@ -1020,6 +1021,65 @@ public static void CooperativeBlockingWithProcessingThreadsAndGoalThreadsAndAddW
...
+                const int FileSize = 1024;
+
+                string destinationFilePath = null;
+                try
+                {
+                    destinationFilePath = CreateFileWithRandomContent(FileSize);
+
+                    static string CreateFileWithRandomContent(int fileSize)
+                    {
+                        string filePath = Path.GetTempFileName();
```
Comment (danmoseley) [inline src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:1042]: aside, better to use the TempFile class, which allows the using pattern instead of writing out try/finally. It also avoids the problematic Path.GetTempFileName() which fails if someone else has leaked temp files.
https://github.com/dotnet/runtime/blob/19eb98df125a6bc766acdb8aacfc36c7d2a75403/src/libraries/Common/tests/System/IO/TempFile.cs#L22

Comment (kouvel) [reply src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:1042]: Oh ok, I'll fix it up in a follow-up PR

**Comment by AndyAyersMS** [comment]
@kouvel there seem to be some persistent regressions in ping-pong tests that may be a result of this change: https://github.com/dotnet/perf-autofiling-issues/issues/4817

Is this expected?
