### PR TITLE
Fixes for disassembly support in x86-hosted R2RDump

### LINKED ISSUE #10928: R2RDump with x86 disassembler architecture fails to disassemble R2R images
On my x64 machine I generated a R2R image with crossgen then tried to disassemble with two different R2RDump builds. The x64 version of the tools will disassemble correctly, but the x86 version of the tools will fail with an AV. This has been replaced with an exception for the time being but the behavior needs to be fixed

## x64 CoreDisTools disassembling an x64 R2R image
1. dotnet build --runtime win-x64
2. E:\git\dotnet\coreclr\bin\Product\Windows_NT.x64.Debug\netcoreapp2.0\win-x64\R2RDump.exe --in MultipleRuntimeFunctions.ni.dll --disasm

```
MultipleRuntimeFunctions.MultipleRuntimeFunctions.MethodWithMultipleRuntimeFunctions()
Id: 0
StartAddress: 0x00002800
Size: 36 bytes
UnwindRVA: 0x0000289C
    2800: 55                    push    rbp
    2801: 48 83 ec 10           sub     rsp, 16
    2805: 48 8d 6c 24 10        lea     rbp, [rsp + 16]
    280a: 48 89 65 f0           mov     qword ptr [rbp - 16], rsp
    280e: 90                    nop
    280f: 90                    nop
    2810: 90                    nop
    2811: 90                    nop
    2812: eb 00                 jmp     0
    2814: 48 8b cc              mov     rcx, rsp
    2817: e8 08 00 00 00        call    8
    281c: 90                    nop
    281d: 90                    nop
    281e: 48 8d 65 00           lea     rsp, [rbp]
    2822: 5d                    pop     rbp
    2823: c3                    ret
```

## x86 CoreDisTools disassembling an x86 R2R image
1. dotnet build --runtime win-x86
2. E:\git\dotnet\coreclr\bin\Product\Windows_NT.x64.Debug\netcoreapp2.0\win-x86\R2RDump.exe --in MultipleRuntimeFunctions.ni.dll --disasm

```
MultipleRuntimeFunctions.MultipleRuntimeFunctions.MethodWithMultipleRuntimeFunctions()
Id: 0
StartAddress: 0x00002800
Size: 36 bytes
UnwindRVA: 0x0000289C
[AV thrown here]
```

In the meantime, this AV has been replaced with the following exception:
```
Error: System.ArgumentException: The architecture of input file MultipleRuntimeFunctions.ni.dll is Amd64 and does not match the architecture of the disassembler tools X86
```

### LINKED ISSUE #45857: X86 R2RDump cannot load coredistools on x64 machine
OS: Windows
Architecture: x86

The managed R2RDump project needs to be tweaked so that, in x86-targeting build, its PE header forces 32-bit execution. Today it's run under the x64 runtime on an x64 machine and subsequently it cannot load the x86-targeting coredistools.dll with the error

<pre>
d:\git\runtime>artifacts\bin\coreclr\windows.x86.Release\R2RDump\r2rdump.exe --header --disasm --gc --sc --in artifacts\bin\coreclr\windows.x86.Release\System.Private.CoreLib.dll --out d:\triage\SPC-new-raw.r2r
Error: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at R2RDump.CoreDisTools.InitBufferedDisasm(TargetArch Target)
   at R2RDump.CoreDisTools.GetDisasm(Machine machine) in D:\git\runtime\src\coreclr\src\tools\r2rdump\CoreDisTools.cs:line 81
   at R2RDump.R2RDump.Run() in D:\git\runtime\src\coreclr\src\tools\r2rdump\R2RDump.cs:line 581
</pre>

@dotnet/crossgen-contrib

### PR DESCRIPTION
**Pull request by trylek**
1) We need to remove the PlatformTarget spec to make sure
x86-hosted R2RDump actually runs under 32-bit host, otherwise it
fails to load x86-targeting coredistools.dll. Thanks to Michal
for pointing that out.

2) I have removed Zach's workaround blocking disassembly on x86.

3) Based on JanV's advice I have marked all the interface methods
as using the cdecl calling convention in accordance with the
native declarations.

4) I found out that Address was incorrectly declared as a 64-bit
integer in the PInvoke declaration while in reality it should be
an IntPtr (native int).

With these changes I'm for the first time able to disassemble
x86-targeting System.Private.CoreLib using the x86-hosted R2RDump.

Thanks

Tomas

/cc @dotnet/crossgen-contrib 

Fixes: https://github.com/dotnet/runtime/issues/45857
Fixes: https://github.com/dotnet/runtime/issues/10928

### CODE REVIEW

File: src/coreclr/tools/r2rdump/CoreDisTools.cs [hunk 1]
```diff
@@ -24,23 +24,23 @@ public enum TargetArch
...
         public static extern IntPtr InitBufferedDisasm(TargetArch Target);
 
-        [DllImport(_dll)]
-        public static extern void DumpCodeBlock(IntPtr Disasm, ulong Address, IntPtr Bytes, int Size);
+        [DllImport(_dll, CallingConvention = CallingConvention.Cdecl)]
+        public static extern void DumpCodeBlock(IntPtr Disasm, IntPtr Address, IntPtr Bytes, int Size);
 
-        [DllImport(_dll)]
+        [DllImport(_dll, CallingConvention = CallingConvention.Cdecl)]
         [return: MarshalAs(UnmanagedType.I4)]
```
Comment (jkotas) [inline src/coreclr/tools/r2rdump/CoreDisTools.cs:34]:
```suggestion
```
Unnecessary

**Review by jkotas — APPROVED** [review]

**Review by janvorli — APPROVED** [review]

File: src/coreclr/tools/r2rdump/CoreDisTools.cs (hunk 1 above)
Comment (trylek) [reply src/coreclr/tools/r2rdump/CoreDisTools.cs:34]: Great, thanks for confirming, I was also wondering what's the use of this clause ;-).

Comment (trylek) [reply src/coreclr/tools/r2rdump/CoreDisTools.cs]: Removed in 2nd commit.

File: src/coreclr/tools/r2rdump/CoreDisTools.cs [hunk 2]
```diff
@@ -24,23 +24,22 @@ public enum TargetArch
...
         };
 
-        [DllImport(_dll)]
+        [DllImport(_dll, CallingConvention = CallingConvention.Cdecl)]
         public static extern IntPtr InitBufferedDisasm(TargetArch Target);
 
-        [DllImport(_dll)]
-        public static extern void DumpCodeBlock(IntPtr Disasm, ulong Address, IntPtr Bytes, int Size);
+        [DllImport(_dll, CallingConvention = CallingConvention.Cdecl)]
+        public static extern void DumpCodeBlock(IntPtr Disasm, IntPtr Address, IntPtr Bytes, int Size);
```
Comment (echesakovMSFT) [inline src/coreclr/tools/r2rdump/CoreDisTools.cs:31]: `int Size` here corresponds to `size_t Size` in https://github.com/dotnet/jitutils/blob/d9d36de5fb445662b56e583cf00746969f1bfab3/src/coredistools/coredistools.cpp#L816

Shouldn't we update that one as well?

Comment (trylek) [reply src/coreclr/tools/r2rdump/CoreDisTools.cs]: Thanks Egor for pointing that out, fixed in 3rd commit.

**Review by echesakov — APPROVED** [review]

**Review by cshung — APPROVED** [review]
LGTM

File: src/coreclr/crossgen-corelib.proj [hunk 3]
```diff
@@ -75,7 +75,7 @@
     </PropertyGroup>
     
     <PropertyGroup Condition="$(BuildPdb)">
-      <CrossGenPdbCmd>$(DotNetCli) $(BinDir)\r2rdump\r2rdump.dll</CrossGenPdbCmd>
+      <CrossGenPdbCmd>$(BinDir)\r2rdump\r2rdump.exe</CrossGenPdbCmd>
```
Comment (jkotas) [inline src/coreclr/crossgen-corelib.proj:78]: Is this going to use some random .NET runtime installed on the machine? That does not sound good.

Comment (trylek) [reply src/coreclr/crossgen-corelib.proj:78]: Hmm, I don't see any trivial way to fix this as part of this PR. I'm going to revert this last commit and I'll tackle this as part of the switch-over of SPC to use CG2, probably by prioritizing my in progress change to enable building the PDB directly from Crossgen2, that should remove the need to run r2rdump from CoreCLR build.

Comment (trylek) [reply src/coreclr/crossgen-corelib.proj]: Reverted in 5th commit.
