### PR TITLE
Adjust IP after an AV during an STEP with FEATURE_EMULATE_SINGLESTEP enabled

### LINKED ISSUE #95189: vsdbg quits when resuming from a breakpoint if stepping over a line that throws an exception
### Description

I noticed some odd behavior with how vsdbg v17.0.10712.2 behaves when running after stopping on a breakpoint on a line that will throw an exception. I am using dotnet 6.0.11.

If I stop at a breakpoint on a line that will throw a null reference exception, the debugger halts as expected. If I then try to step, the program quits. If I were to run, the program executes as expected.

### Reproduction Steps
```
            try
            {
                string a = null;
                a.Trim();
            }
            catch 
            {
            
            }
```

Put a breakpoint on a.Trim();
Run the debugger on this code. Then step. Program quits.
Run the debugger on this code. Then run. Program proceeds.
Run the debugger on this code without a breakpoint. The debugger halts, if you've elected to stop on first-chance exceptions, but runs fine if you step or run after.

### Expected behavior

Program should not quit when attempting to resume from a breakpoint, on a line with a null reference exception.

### Actual behavior

Program crashes when attempting to resume from a breakpoint by stepping over a line with a null reference exception.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by thaystg**
Fix step in a line that will throw an AV

Without this PR in this function `IsSafeToHandleHardwareException` this other function `ExecutionManager::IsManagedCode(controlPc)` was returning FALSE, basically because we were trying to find the patched IP in the Jitted code and then it wasn't found, right now I'm adjusting the patched IP to the original IP before trying to check the is it's in a managed code. 

Fixes #95189

### CODE REVIEW

File: src/coreclr/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -5424,6 +5429,22 @@ BOOL IsSafeToCallExecutionManager()
            GCStress<cfg_instr_ngen>::IsEnabled();
 }
 
+#ifdef FEATURE_EMULATE_SINGLESTEP
+BOOL HandleSingleStepAfterException(PCONTEXT contextRecord, PEXCEPTION_RECORD exceptionRecord)
+{
+    Thread *pThread = GetThreadNULLOk();
+    if (pThread && pThread->IsSingleStepEnabled() &&
```
Comment (noahfalk) [inline src/coreclr/vm/exceptionhandling.cpp:5436]: Any reason why we only invoke pThread->HandleSingleStep() in some cases and not others? Could we do something like this in IsSafeToHandleHardwareException() and remove the HandleSingleStep call from HandleHardwareException? 

```
#ifdef FEATURE_EMULATE_SINGLESTEP
Thread *pThread = GetThreadNULLOk();
if (pThread != NULL && g_pDebugInterface != NULL)
{
    HandleSingleStep(contextRecord, exceptionRecord, pThread);
}
#endif
```

It feels easier to understand if we always invoke it from one place rather than conditionally invoke it from two different place.

**Comment by thaystg** [comment]
@tommcdon the tests are passing.
@noahfalk I think I addressed all your comments.

**Review by tommcdon — APPROVED** [review]

File: src/coreclr/vm/exceptionhandling.cpp [hunk 2]
```diff
@@ -5426,6 +5426,17 @@ BOOL IsSafeToCallExecutionManager()
...
 BOOL IsSafeToHandleHardwareException(PCONTEXT contextRecord, PEXCEPTION_RECORD exceptionRecord)
 {
+#ifdef FEATURE_EMULATE_SINGLESTEP    
+    Thread *pThread = GetThreadNULLOk();
+    if (pThread && pThread->IsSingleStepEnabled() &&
+        exceptionRecord->ExceptionCode != STATUS_BREAKPOINT &&
+        exceptionRecord->ExceptionCode != STATUS_SINGLE_STEP &&
+        exceptionRecord->ExceptionCode != STATUS_STACK_OVERFLOW)
+    {
+        pThread->HandleSingleStep(contextRecord, exceptionRecord->ExceptionCode);
```
Comment (noahfalk) [inline src/coreclr/vm/exceptionhandling.cpp:5436]: The updated version of the change looks like it still calls HandleSingleStep from two different places, once here and once over in [HandleHardwareException](https://github.com/dotnet/runtime/blob/cc2f60147dece0797d19f4aa6a12c44201ecfee4/src/coreclr/vm/exceptionhandling.cpp#L5606).

I was suggesting that we converge those into a single call here. Is there a reason we need two different calls? If yes it would be great to add a comment saying why we have both, and if not it would be nice to get rid of the HandleHardwareException portion and do it all here.
