### PR TITLE
Fix failed assertion 'FPbased == FPbased2'

### LINKED ISSUE #111777: JIT: Assertion failed 'FPbased == FPbased2' during 'Emit code'
Failing in arm64 `libraries-jitstress` legs. [Example run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=927163&view=results). cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by filipnavara**
When `lvaFrameAddress` optimizes one of the temporary variables (referenced as FP-m) to be placed next to existing SP+n variable (eg. `OutgoingArgSpace` at SP+0) we may end up coalescing a pair-wise load/store between them. A previous attempt to handle the case only accounted for the `lvaFrameAddress` optimization being applied to both of the variables or neither of them, but it didn't correctly handle the mixed variant.

Fixes #111777

### CODE REVIEW

**Comment by filipnavara** [comment]
Can someone trigger `runtime-coreclr libraries-jitstress` pipelien on this PR please?

**Comment by filipnavara** [comment]
Still failed on linux-arm64 :-/ I tested the same change locally on win-arm64 on some of the failing samples and it no longer triggered. I'll need to run more tests locally I guess.

**Comment by filipnavara** [comment]
Can we run `/azp run runtime-coreclr gcstress0x3-gcstress0xc, runtime-coreclr gcstress-extra` to make sure that I didn't miss anything?

**Comment by filipnavara** [comment]
The `CrossApartmentQueryInterface_NoDeadlock` test failure seems new and unrelated to this PR. The test was added 3 weeks ago and it likely only happens in the GC stress runs. /cc @jkoritzinsky

**Comment by filipnavara** [comment]
> That's a known issue. It's on my list of things to look at.

I didn't see any other failure in the Azure history which is why I asked. I'm happy to know it's on the radar.

**Comment by AndyAyersMS** [comment]
@egorbo are you the right reviewer for this?

File: src/coreclr/jit/emitarm64.cpp [hunk 1]
```diff
@@ -12311,7 +12311,7 @@ size_t emitter::emitOutputInstr(insGroup* ig, instrDesc* id, BYTE** dp)
 
                 // If there are 2 GC vars in this instrDesc, get the 2nd variable
                 // that should be tracked.
-                adr2     = emitComp->lvaFrameAddress(varNum2, &FPbased2, true);
+                adr2     = emitComp->lvaFrameAddress(varNum2, &FPbased2, FPbased);
```
Comment (kunalspathak) [inline src/coreclr/jit/emitarm64.cpp:12314]: I forgot to tell, but can you add a comment about `suppressFPtoSPRewrite` in the method docs of `lvaFrameAddress`? OK to do in separate PR.

**Review by kunalspathak — APPROVED** [review]
LGTM
