### PR TITLE
Handle Counter Polling Interval of 0

### LINKED ISSUE #53564: EventCounter publishing thread can hang
### Description

When listening to EventCounters there is a dedicated thread that is supposed to publish the metric values via EventSource on a periodic timer. However due a bug it is possible to put it into an infinite loop [here](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs#L254-L257). This occurs any time _pollingIntervalMilliseconds <= 0, which could occur for a few reasons:
1. The listener specified EventCounterIntervalSec=0 after previously specifying a non-zero value. We would never expect a well-behaved listener to request a 0 sec interval, but the runtime shouldn't blindly trust this input.
2. The listener enables and then disables the EventSource. Due to a race the infinite loop code could be run prior to re-checking _eventSource.IsEnabled() and it would observe _pollingIntervaMilliseconds=0

### Configuration

.NET 5 (but presumably also reproable in .NET 3 and 3.1)

### Regression?

The underlying bug was [introduced](https://github.com/dotnet/runtime/commit/a8c5b844dbbc5845fcdfc37c425648c021adbb02#diff-20a39a3638ea5f2050f8670551a2408a7bd56bb95de9943ebcfdbc1bf8bc72db) in 2019 and shipped in .NET Core 3, 3.1, and 5: 
However at this point only failure reason (1) above would have been able to trigger it.

In August 2020 [an additional change](https://github.com/dotnet/runtime/commit/c67684bead32185f086c3d376c6914dfbd0d4b6a#diff-20a39a3638ea5f2050f8670551a2408a7bd56bb95de9943ebcfdbc1bf8bc72db) was made in .NET Core 5 (and backported to 3.1) which opened the race condition allowing failure reason (2) above to be hit. 

### Repro

```C#
using System;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

internal sealed class RuntimeEventListener : EventListener
{
    protected override void OnEventSourceCreated(EventSource source)
    {
        if (source.Name.Equals("System.Runtime"))
        {
            EnableEvents(source, EventLevel.LogAlways, EventKeywords.None, new Dictionary<string, string>()
                { { "EventCounterIntervalSec", "1" } });
            
            // The next line makes the example fail, comment this out to see it work normally
            EnableEvents(source, EventLevel.LogAlways, EventKeywords.None, new Dictionary<string, string>()
                { { "EventCounterIntervalSec", "0" } });
        }
    }

    protected override void OnEventWritten(EventWrittenEventArgs eventData)
    {
        Console.WriteLine(eventData.TimeStamp + " " + eventData.EventName);
    }
}

class Program
{
    static void Main(string[] args)
    {
        RuntimeEventListener listener = new RuntimeEventListener();
        Console.ReadLine();
    }
}
```

Expected behavior: No threads should spin in the counter [infinite loop](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs#L254-L257)
Actual behavior: A thread will hang in that loop

Note: this repro only shows technique (1) to repro the problem. Any fix still needs to account for technique (2) as well.

### PR DESCRIPTION
**Pull request by josalem**
Fixes #53564 

* default internal state to DateTime.MaxValue
* re-check IsEnabled after not holding lock
* add test for setting interval to 0

This will need to be backported to 3.1 _and_ 5.0.

CC @tommcdon

### CODE REVIEW

File: src/tests/tracing/eventcounter/gh53564.cs [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+                // first set interval to 1 seconds
+                refreshInterval["EventCounterIntervalSec"] = "1";
+                EnableEvents(source, EventLevel.Informational, (EventKeywords)(-1), refreshInterval);
+
+                // wait a moment to get some events
+                Thread.Sleep(TimeSpan.FromSeconds(3));
+
+                // then set interval to 0
+                Console.WriteLine($"[{DateTime.Now:hh:mm:ss.fff}] Setting interval to 0");
+                refreshInterval["EventCounterIntervalSec"] = "0";
```
Comment (noahfalk) [inline src/tests/tracing/eventcounter/gh53564.cs:41]:
```suggestion
                refreshInterval["EventCounterIntervalSec"] = "0.00001";
```
I suspect this slightly more evil version of the test still hangs? It will no longer go into the `if(pollingIntervalInSeconds <= 0)` branch but due to the floating point math it is still going to set `_pollingIntervalInMilliseconds = 0`

I'd suggest rather than trying to identify every possible flow of code and data that can get that loop to spin infinitely eliminate the possibility by making it a for loop with a limited number of possible iterations. We'd never expect it to go more than a couple iterations so if for some reason it looped 1000 times then something is clearly not running properly and we should just give up.
The other issue is that every additional line changed outside that do/while loop raises the question "given that this change will happen even when the app is not in the infinite loop situation, what if this is introducing a new bug somewhere else?" If we can avoid making changes to any other lines its less code we have to carefully analyze and defend the correctness of.

**Review by noahfalk — CHANGES_REQUESTED** [review]
I'm hoping we can go even more targetted, suggestion inline : )

**Review by davmason — APPROVED** [review]
This version LGTM

**Comment by lateralusX** [comment]
Looks like I managed to repro/investigate/fix this issue when testing on iOS in parallel to this fix/investigation, https://github.com/dotnet/runtime/pull/53887.

File: src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs [hunk 2]
```diff
@@ -251,10 +251,10 @@ private void OnTimer()
                 lock (s_counterGroupLock)
                 {
                     _timeStampSinceCollectionStarted = now;
-                    do
+                    for (int i = 0; i < 1000 && _nextPollingTimeStamp < now; i++)
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs:254]: Where does this `1000` come from?

Also, why does this require a loop?  It can't just be done with some match to figure out the next time stamp?

Comment (josalem) [reply src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs:254]: The 1000 is arbitrary with the assumption that `now` is not more than 1000 intervals in the future. If I recall correctly, this code is meant to prevent drift in the polling interval due to work time. For example, if the polling interval is 1 second (the smallest unit we allow), but the counter takes more than 1 second to collect, we don't want that work time to drift the next polling timestamp. The alternative would be to measure the time it took to calculate the counter then do a calculation comparing the work time, the interval, and `now` to get to the same result.

Comment (stephentoub) [reply src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs:254]: Thanks.  I'm wondering why the loop is needed.  Why can't it be something along the lines of...
```C#
TimeSpan diff = now - _nextPollingTimeStamp;
if (diff > TimeSpan.Zero)
{
    _nextPollingTimeStamp += TimeSpan.FromMilliseconds(_pollingIntervalInMilliseconds * Math.Ceiling(diff.TotalMilliseconds / _pollingIntervalInMilliseconds));
}
```
Am I misreading what the loop is doing?

Comment (josalem) [reply src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs:254]: I think you're right. That looks to achieve the same original intent. I prefer that over the loop. @noahfalk thoughts on using this change in terms of servicing? It's not quite as targeted, but I prefer _removing_ the loop over fixing the loop.

Comment (davmason) [reply src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs:254]: The loop was added in https://github.com/dotnet/coreclr/pull/25864. It was an attempt to account for a situation where something (probably threadpool starvation) forces the timer to run significantly later than it should have. I.e. skip forward to the next counter if we run later than expected. https://github.com/dotnet/coreclr/pull/25864#discussion_r307058733

Comment (noahfalk) [reply src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs:254]: I'm also fine removing the loop and replacing it with Stephen's calculation that computes the same result. Certainly whatever final form we use needs to handle _pollingIntervalInMilliseconds = 0. Currently for the loop we get infinite loop and for Stephen's math we'd get division by zero error. But as long as we've done something to handle that case gracefully then all good : )

Comment (davmason) [reply src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs]: Re-reading my comment, if it seems like I was pushing for one outcome or another I wasn't. I was just providing context, I think the loopless method is a good solution.

**Review by noahfalk — APPROVED** [review]
LGTM

**Comment by josalem** [comment]
\backport to release/5.0
