### PR TITLE
[browser][http] Fix blocking of streaming response and abort

### LINKED ISSUE #79238: StreamReader.ReadLineAsync() does not return before its internal buffer is full
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

That bug report is about a regression between Blazor 6.0.11 and Blazor 7.0.0

Conditions:
* An API endpoint on the server produces a stream of data (text) slowly: A single line of text is added to the response every second.
* A method on the client side (Blazor WASM) reads that stream of data line-by-line using StreamReader.ReadLineAsync().
* All prerequisites to enable response streaming are met (HttpRequestMessage.SetBrowserResponseStreamingEnabled(true), HttpCompletionOption.ResponseHeadersRead)

When using Blazor 6.0.11, each time a line-break is received in the stream of data, the method StreamReader.ReadLineAsync() returns the text that was preceding that line-break.

With Blazor 7.0.0, the method StreamReader.ReadLineAsync() will not return before the StreamReader's internal buffer has been entirely filled, which means that several lines of text can be received before StreamReader.ReadLineAsync() returns them all consecutively.

When reading the data directly from the response stream, that behavior disappear and all the data is available as soon as it is received. That seems to suggest that the issue is only due to the StreamReader. 

However, that issue cannot be reproduced when the client code is executed from a console application: The behavior is then exactly the same when using .Net 6 and .Net 7: StreamReader.ReadLineAsync() returns on every line break without waiting for the buffer to be full.

### Expected Behavior

The StreamReader should behave the same way when using Blazor 6.0.11 and Blazor 7.0.0: StreamReader.ReadLineAsync() should return as soon as a line-break is available from the input stream.

### Steps To Reproduce

A minimal project to reproduce the issue is available here:
https://github.com/oleneveu/BlazorStreamReaderIssue

It is based on the template from Visual Studio. The code that reproduces the issue is located here:
* Server side: DataStreamingController.cs
* Client side: StreamData.razor

The project currently targets Blazor 7.0.0.
To compare the behavior with Blazor 6.0.11, all projects files must be modified to target .Net 6 and all packages references must be changed from 7.0.0 to 6.0.11. No other changes should be required.

Steps to reproduce:
* Start the project
* Open the 'Stream data' menu from the Blazor application
* Blazor 7: The text 'Streamed data: Waiting for server data...' is displayed for about 17 seconds before being updated. It is then updated every 17 seconds or so.
* Blazor 6: The text 'Streamed data: Waiting for server data...' is updated immediately and then every 1 second or so.

Note: Each line of text sent by the server contains 7 bytes (5 digits + CR/LF) . Within 17 seconds, 18 lines or 126 bytes are sent. When the 19th line is sent, the total size exceeds the buffer size of the StreamReader (configured to 128 bytes in the sample project).
When changing the buffer size of the StreamReader, the delay before the first update changes accordingly.

Update: I have added a console application to the solution ('ConsoleStreaming') to perform the same test that is made from the Blazor component and highlight the difference in behavior. To run this test:
* Start the server (BlazorStreaming.Server)
* Start the console app (ConsoleStreaming)
When a line of text is added to the response from the 'DataStreamingController.Get()' endpoint, that line is immediately displayed in the console.

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### LINKED ISSUE #80696: Uncaught (in promise) DOMException: The user aborted a request. when Virtualize cancels the gRPC-Web call (Blazor WASM, net7 regression)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using gRPC-Web (Grpc.Net.Client.Web) call to server from `Virtualize.ItemsProvider` and Virtualize cancels the call, the browser sometimes (race-condition?) fails with `Uncaught (in promise) DOMException: The user aborted a request.`
image

Sometimes, the `Virtualize` component continues working, sometimes it is kept broken.

The issue was introduced starting net7.0, when I downgrade the project to net6.0, the issue disappears.

### Expected Behavior

Correct handling of the request cancellation (without any browser error).

(If the error is caused by incorrect Grpc.Net.Client.Web implementation, the WASM/Blazor still should fail with regular exception and not with this type of DOM error.)

### Steps To Reproduce

repro: https://github.com/hakenr/VirtualizeGrpcRepro
Start the project.
Scroll the list quickly up/down/up/down/..., the issue usually appears within few seconds.
If not reproduced, try to set browser CU throttling to 6x slowdown, the issue will appear much more likely.

### Exceptions (if any)

```
Uncaught (in promise) DOMException: The user aborted a request.
oa	@	dotnet.7.0.2.tt5z2s8frk.js:5
_bound_js_INTERNAL_http_wasm_abort_response	@	_bound_js_INTERNAL_h…sm_abort_response:7
Ss	@	dotnet.7.0.2.tt5z2s8frk.js:5
_mono_wasm_invoke_bound_function	@	dotnet.7.0.2.tt5z2s8frk.js:14
$func313	@	00992bd6:0x1d40d
$func283	@	00992bd6:0x1c906
$func221	@	00992bd6:0xdff6
$func220	@	00992bd6:0xce95
$func8115	@	00992bd6:0x1a2195
$func2054	@	00992bd6:0x85bba
$func2059	@	00992bd6:0x86222
$func2086	@	00992bd6:0x882e1
$mono_wasm_invoke_method_bound	@	00992bd6:0x9c6c
Module._mono_wasm_invoke_method_bound	@	dotnet.7.0.2.tt5z2s8frk.js:14
Ws	@	dotnet.7.0.2.tt5z2s8frk.js:5
b.javaScriptExports.complete_task	@	dotnet.7.0.2.tt5z2s8frk.js:5
(anonymous)	@	dotnet.7.0.2.tt5z2s8frk.js:5
Promise.catch (async)		
Kr	@	dotnet.7.0.2.tt5z2s8frk.js:5
_bound_js_INTERNAL_http_wasm_get_streamed_response_bytes	@	_bound_js_INTERNAL_h…d_response_bytes:10
Ss	@	dotnet.7.0.2.tt5z2s8frk.js:5
_mono_wasm_invoke_bound_function	@	dotnet.7.0.2.tt5z2s8frk.js:14
$func313	@	00992bd6:0x1d40d
$func283	@	00992bd6:0x1c906
$func221	@	00992bd6:0xdff6
$func220	@	00992bd6:0xce95
$func8115	@	00992bd6:0x1a2195
$func2054	@	00992bd6:0x85bba
$func2059	@	00992bd6:0x86222
$func2086	@	00992bd6:0x882e1
$mono_wasm_invoke_method_bound	@	00992bd6:0x9c6c
Module._mono_wasm_invoke_method_bound	@	dotnet.7.0.2.tt5z2s8frk.js:14
Ws	@	dotnet.7.0.2.tt5z2s8frk.js:5
b.javaScriptExports.complete_task	@	dotnet.7.0.2.tt5z2s8frk.js:5
(anonymous)	@	dotnet.7.0.2.tt5z2s8frk.js:5
Promise.then (async)		
Kr	@	dotnet.7.0.2.tt5z2s8frk.js:5
_bound_js_INTERNAL_http_wasm_fetch_bytes	@	_bound_js_INTERNAL_h…wasm_fetch_bytes:15
Ss	@	dotnet.7.0.2.tt5z2s8frk.js:5
_mono_wasm_invoke_bound_function	@	dotnet.7.0.2.tt5z2s8frk.js:14
$func313	@	00992bd6:0x1d40d
$func283	@	00992bd6:0x1c906
$func221	@	00992bd6:0xdff6
$func220	@	00992bd6:0xce95
$func8115	@	00992bd6:0x1a2195
$func2054	@	00992bd6:0x85bba
$func2052	@	00992bd6:0x85b30
$func1395	@	00992bd6:0x68681
$func313	@	00992bd6:0x1d491
$func283	@	00992bd6:0x1c906
$func221	@	00992bd6:0xdff6
$func220	@	00992bd6:0xce95
$func8115	@	00992bd6:0x1a2195
$func2054	@	00992bd6:0x85bba
$func2059	@	00992bd6:0x86222
$func2086	@	00992bd6:0x882e1
$mono_wasm_invoke_method_ref	@	00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref	@	dotnet.7.0.2.tt5z2s8frk.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet	@	_Microsoft_AspNetCor…eginInvokeDotNet:29
beginInvokeDotNetFromJS	@	blazor.webassembly.js:1
b	@	blazor.webassembly.js:1
invokeMethodAsync	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
(anonymous)
```

### .NET Version

7.0.2

### Anything else?

I published the repro to https://VirtualizeGrpcRepro.azurewebsites.net

### PR DESCRIPTION
**Pull request by pavelsavara**
- return bytes of streaming response as soon as available
- fix unhandled error in reader.cancel() promise
- return cancelable promise from `http_wasm_get_streamed_response_bytes`
- unit test for slowly streamed chunks
- unit test for streaming and default cancellation

Fixes https://github.com/dotnet/runtime/issues/79238
Fixes https://github.com/dotnet/runtime/issues/80696

Should be merged back to Net7

### CODE REVIEW

**Review by maraf — APPROVED** [review]
LGTM 👍

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs [hunk 1]
```diff
@@ -984,13 +984,14 @@ public async Task SendAsync_ReadFromSlowStreamingServer_PartialDataReturned()
...
 
         [Theory]
-        [InlineData(true, true)]
-        [InlineData(true, false)]
-        [InlineData(false, true)]
-        [InlineData(false, false)]
-        [InlineData(null, false)]
+        [InlineData(true, true, true)]
+        [InlineData(true, true, false)]
+        [InlineData(true, false, false)]
```
Comment (ilonatommy) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:989]: Why we're not testing slow chunks when `chunked` == true and `enableWasmStreaming` == false? As far as I can see, usage of `slowChunks` 
https://github.com/dotnet/runtime/blob/0516f2cd7d1051a8c9db05dcd35e2536e0fb5dd0/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs#L1197
depends only on `chunked` and it makes sense to test slow chunks only when `chunked` is true. For `enableWasmStreaming` we don't have such a relation, it makes sense to test slow chunks for all values of `enableWasmStreaming`, doesn't it?

File: src/mono/wasm/runtime/http.ts [hunk 2]
```diff
@@ -21,7 +21,9 @@ export function http_wasm_abort_request(abort_controller: AbortController): void
 export function http_wasm_abort_response(res: ResponseExtension): void {
     res.__abort_controller.abort();
     if (res.__reader) {
-        res.__reader.cancel();
+        res.__reader.cancel().catch(() => {
+            //we ignore the error
```
Comment (ilonatommy) [inline src/mono/wasm/runtime/http.ts:25]: Why? Even logging e.g. "Reading the steam was canceled" is not desirable?

Comment (pavelsavara) [reply src/mono/wasm/runtime/http.ts:25]: It's the direct consequence of the `__abort_controller.abort()` above. 
The user is asking for it. It's expected to happen.

We could possibly test if the error is something else than we expected and log that.

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs (hunk 1 above)
Comment (pavelsavara) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:989]: thanks, `enableWasmStreaming` makes no sense outside of browser. I will improve it.

Comment (ilonatommy) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:989]: We established that in this PR we are not planning to handle the case `[InlineData(true, false, true)]`, even though technically such a case is possible for coreCLR.

**Review by ilonatommy — APPROVED** [review]

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs [hunk 3]
```diff
@@ -1295,6 +1322,73 @@ public async Task ReadAsStreamAsync_EmptyResponseBody_HandlerProducesWellBehaved
...
         }
 
+        [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsBrowser))]
+        public async Task ReadAsStreamAsync_StreamingCancellation()
+        {
+            var tcs = new TaskCompletionSource<bool>();
+            await LoopbackServerFactory.CreateClientAndServerAsync(async uri =>
+            {
+                var request = new HttpRequestMessage(HttpMethod.Get, uri) { Version = UseVersion };
+#if !NETFRAMEWORK
```
Comment (maraf) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1332]: Do we need to keep ifdefs when the test is guarded to run only on wasm?

File: src/mono/wasm/runtime/http.ts [hunk 4]
```diff
@@ -21,7 +22,12 @@ export function http_wasm_abort_request(abort_controller: AbortController): void
 export function http_wasm_abort_response(res: ResponseExtension): void {
     res.__abort_controller.abort();
     if (res.__reader) {
-        res.__reader.cancel();
+        res.__reader.cancel().catch((err) => {
+            if (err && err.name !== "AbortError") {
+                Module.printErr("MONO_WASM: Error in http_wasm_abort_response: " + err);
```
Comment (maraf) [inline src/mono/wasm/runtime/http.ts:27]: Shouldn't we throw in such case? The user wanted to cancel, but it probably failed on something different. I see it as catching `Exception` in .NET code when I want to catch just `OperationCancelledException`.

**Review by ilonatommy — APPROVED** [review]
👍 I don't have any more ideas for improvement.

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs (hunk 3 above)
Comment (pavelsavara) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1332]: it would not compile otherwise

File: src/mono/wasm/runtime/http.ts (hunk 4 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/http.ts:27]: The caller of cancel() is called from cancellation token registration, which probably doesn't propagate further ? Anyway, that only returns promise.
But the caller of `catch` here is a browser I think. I don't know who to propagate it to the user code.
Also, the user doesn't have corrective action probably.
Overall I think logging is fine until we know what are other ways how it could fail.

Comment (maraf) [reply src/mono/wasm/runtime/http.ts:27]: I see, and we can't make `http_wasm_abort_response` async, because on the side, `HttpContent` doesn't implement `IAsyncDisposable`.

Okay than 👍 Thanks for the explanation.

**Review by maraf — APPROVED** [review]

**Comment by pavelsavara** [comment]
@hakenr, would you please have time to test it ?

**Comment by hakenr** [comment]
@pavelsavara Yes, I'm happy to test it, I just don't know how to get the new version into my own project. Yes, I'm happy to test it, I just don't know how to get the new version into my own project. Can you please direct me where I can find some instructions?

**Comment by pavelsavara** [comment]
> Can you please direct me where I can find some instructions?

I will have to figure it out. My naive attempt to use net8 runtime in net7 blazor project didn't work.
Maybe it would be easier for me to backport it to net7 before we test it with old blazor.

There are NodeJS CI failures which I need to handle first.

Will ping you again, thanks!
