### PR TITLE
Fix binder gen compile issues due to inaccessible members and identifier name clashes

### LINKED ISSUE #90909: Config binder generator generates uncompilable code when a private nested type is used
This compiles fine:
```C#
using Microsoft.Extensions.Configuration;

internal class Program
{
    private static void Main() { }

    private static C Foo(IConfiguration configuration)
    {
        C c = new();
        configuration.Bind(c);
        return c;
    }

    internal sealed class C
    {
        public int Value { get; set; }
    }
}
```
but changing:
```C#
internal sealed class C
```
to
```C#
private sealed class C
```
produces an error about `C` being inaccessible, as the generator emits code into another class that tries to access that property.

### PR DESCRIPTION
**Pull request by layomia**
Fixes https://github.com/dotnet/runtime/issues/90909 and https://github.com/dotnet/runtime/issues/90976. RC-2 candidate.

cc @ericstj.

### CODE REVIEW

File: src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+            foreach (ITypeSymbol genericArg in namedType.GetAllTypeArgumentsInScope())
+            {
+                sb.Append(ToIdentifierCompatibleSubstring(genericArg));
+            }
+
+            return sb.ToString();
+
+            string GetName(ITypeSymbol type) => useUniqueName
+                ? ToIdentifierCompatibleSubstring(type.ToMinimalDisplayString())
+                : type.Name;
```
Comment (tarekgh) [inline src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs:48]: Why we prefer this style? this is called once in the code and can be in lined in the code . 

string name = useUniqueName 
                ? ToIdentifierCompatibleSubstring(type.ToMinimalDisplayString())
                : type.Name;

just wondering :-)

File: src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+        }
+
+        /// <summary>
+        /// Type name, prefixed with containing type names if it is nested (e.g. ContainingType.NestedType).
+        /// </summary>
+        /// <returns></returns>
```
Comment (tarekgh) [inline src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs:54]: >  /// <returns></returns> [](http://example.com/codeflow?start=6&length=25)

do you want to fill this?

File: src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+        public static string ToMinimalDisplayString(this ITypeSymbol type) => type.ToDisplayString(s_minimalDisplayFormat);
+
+        private static ITypeSymbol[] GetAllTypeArgumentsInScope(this INamedTypeSymbol type)
```
Comment (tarekgh) [inline src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs:57]: >ITypeSymbol[] [](http://example.com/codeflow?start=23&length=13)

what can't returning List<ITypeSymbol> instead of array here? avoid the array allocation

File: src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+
+            foreach (ITypeSymbol genericArg in namedType.GetAllTypeArgumentsInScope())
+            {
+                sb.Append(ToIdentifierCompatibleSubstring(genericArg));
+            }
+
+            return sb.ToString();
+
+            string GetName(ITypeSymbol type) => useUniqueName
+                ? ToIdentifierCompatibleSubstring(type.ToMinimalDisplayString())
```
Comment (tarekgh) [inline src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs:47]: >ToIdentifierCompatibleSubstring [](http://example.com/codeflow?start=18&length=31)

You can pass the created `sb` here instead of creating another StringBuilder object inside this method.

File: src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+            }
+        }
+
+        private static string ToIdentifierCompatibleSubstring(string input)
+        {
+            StringBuilder sb = new();
+
+            foreach (char c in input)
+            {
+                if (c is '[')
```
Comment (tarekgh) [inline src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs:85]: >if (c is '[') [](http://example.com/codeflow?start=16&length=13)

Is it possible you can get characters between `[` and `]`?

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs [hunk 6]
```diff
@@ -70,6 +70,7 @@ private static bool IsValidRootConfigType(ITypeSymbol? type)
             {
                 if (type is null ||
                     type.SpecialType is SpecialType.System_Object or SpecialType.System_Void ||
+                    !IsAccessibleFromGenBinders(type) ||
```
Comment (tarekgh) [inline src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:73]: >!IsAccessibleFromGenBinders(type) || [](http://example.com/codeflow?start=20&length=36)

Is this mean we'll have a difference between the source gen and the runtime in such cases?

Comment (layomia) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:73]: In a sense... we won't generate a replacement interceptor for the invocation, meaning that it will always fallback to reflection. AOT users will get a warning and the fix would be to adjust the visibility.

File: src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs (hunk 5 above)
Comment (layomia) [reply src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs:85]: Perhaps multi-dim arrays. I think the current code handles it okay; I'll add a test. We also have existing tests that show we skip multidim arrays as unsupported, consistent with reflection. So we shouldn't hit this codepath for multi-dim arrays.

I'll adjust the code as necessary.

File: src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs (hunk 4 above)
Comment (layomia) [reply src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs:47]: Will switch thanks. There was a reason I didn't do that in an earlier iteration but it no longer holds.

File: src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs (hunk 3 above)
Comment (layomia) [reply src/libraries/Common/src/SourceGenerators/TypeModelHelpers.cs:57]: Was just porting the code from JSON. Makes sense to optimize it here.

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs (hunk 6 above)
Comment (tarekgh) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:73]: Will the users get anything to help them tell them what to do? I mean how the users know the source gen didn't handle it because of the class visibility? Would it make sense to produce info diagnostics for this one? It doesn't have to be part of this PR.

Comment (layomia) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:73]: Yup, should have mentioned this -- we produce a diagnostic for this. Hence, we need these suppressions:

https://github.com/dotnet/runtime/pull/91657/files#diff-81e6cde105e57e3f3b3a0107c173264b96aee943a0faa6b8f1bd72d7a57a43a3R333-R343

**Review by tarekgh — APPROVED** [review]

**Review by tarekgh — APPROVED** [review]

**Comment by layomia** [comment]
CI failures unrelated; referenced above.

File: src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs [hunk 7]
```diff
@@ -589,17 +590,19 @@ private TypeGenerationSpec ParseTypeGenerationSpec(in TypeToGenerate typeToGener
...
-                string typeInfoPropertyName = typeToGenerate.TypeInfoPropertyName ?? GetTypeInfoPropertyName(type);
+                string typeInfoPropertyName = typeToGenerate.TypeInfoPropertyName ??
+                    type.ToIdentifierCompatibleSubstring(useUniqueName: false /* We leave identifier name conflicts to users, as codified below. */);
 
                 if (classType is ClassType.TypeUnsupportedBySourceGen)
                 {
                     ReportDiagnostic(DiagnosticDescriptors.TypeNotSupported, typeToGenerate.AttributeLocation ?? typeToGenerate.Location, type.ToDisplayString());
                 }
 
+                // Workaround for https://github.com/dotnet/roslyn/issues/54185 by keeping track of the file names we've used.
```
Comment (eiriktsarpalis) [inline src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs:601]: The issue as described in https://github.com/dotnet/roslyn/issues/54185 hasn't been fixed in Roslyn 3.11 (and won't be fixed). We should keep this comment (and possibly with a TODO explaining that we should remove it once Roslyn 3.11 support is removed).

File: src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs [hunk 8]
```diff
@@ -1589,34 +1592,6 @@ private static string DeterminePropertyNameFieldName(string effectiveJsonPropert
                 return null;
             }
 
-            private static string GetTypeInfoPropertyName(ITypeSymbol type)
```
Comment (eiriktsarpalis) [inline src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs:1592]: Changing the identifier generation algorithm can be a potential source breaking change, since user code referencing source generated members from earlier SG versions could fail to compile.

Even if the new logic is equivalent to the old one, this will get backported to RC2 and it's not clear to me why we should take the risk this late.

File: src/libraries/Common/src/SourceGenerators/TypeModelHelper.cs [hunk 9]
```diff
@@ -0,0 +1,120 @@
...
+{
+    internal static class TypeModelHelper
+    {
+        private static readonly SymbolDisplayFormat s_minimalDisplayFormat = new SymbolDisplayFormat(
+            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
+            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypes,
+            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
+            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes);
+
+        public static string ToIdentifierCompatibleSubstring(this ITypeSymbol type, bool useUniqueName)
```
Comment (eiriktsarpalis) [inline src/libraries/Common/src/SourceGenerators/TypeModelHelper.cs:19]: I don't think this algorithm should live in shared code. It should be specific to each application since changing the algorithm in the future is a potential breaking change, and what we have here isn't perfect.

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs [hunk 10]
```diff
@@ -78,6 +80,27 @@ private static bool IsValidRootConfigType(ITypeSymbol? type)
                 }
 
                 return true;
+
+                static bool IsAccessibleFromGenBinders(ITypeSymbol type)
```
Comment (eiriktsarpalis) [inline src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:84]: Couldn't you use `IsSymbolAccessibleWithin` instead?

https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation.issymbolaccessiblewithin?view=roslyn-dotnet-4.6.0

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs [hunk 11]
```diff
@@ -78,6 +80,27 @@ private static bool IsValidRootConfigType(ITypeSymbol? type)
...
+                        foreach (ITypeSymbol genericArg in typeArgsInScope)
+                        {
+                            if (!IsAccessibleFromGenBinders(genericArg))
+                            {
+                                return false;
+                            }
+                        }
+                    }
+
+                    return type.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.Friend;
```
Comment (eiriktsarpalis) [inline src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:102]: What about `internal` members that are in referenced assemblies?

File: src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs [hunk 12]
```diff
@@ -589,17 +590,19 @@ private TypeGenerationSpec ParseTypeGenerationSpec(in TypeToGenerate typeToGener
                 }
 
                 var typeRef = new TypeRef(type);
-                string typeInfoPropertyName = typeToGenerate.TypeInfoPropertyName ?? GetTypeInfoPropertyName(type);
+                string typeInfoPropertyName = typeToGenerate.TypeInfoPropertyName ??
```
Comment (eiriktsarpalis) [inline src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs:593]: I'm not comfortable making cross-cutting changes in RC2 backports. To minimize risk, we should be making targeted changes even if it results in temporary code duplication.

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs (hunk 10 above)
Comment (layomia) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:84]: I don't have a "within" symbol. The symbol would be the generated binder extension class which doesn't exist yet.

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs (hunk 11 above)
Comment (layomia) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:102]: We shouldn't be seeing those in this routine. This method is for root binding types only. `InternalsVisibleTo` usage is interesting but the current logic handles the scenario.

For transitive types - the generator only inspects public properties. The compiler would have complained if a type had a public member whose declared type is internal. So we don't have to guard against that explicitly

File: src/libraries/Common/src/SourceGenerators/TypeModelHelper.cs (hunk 9 above)
Comment (layomia) [reply src/libraries/Common/src/SourceGenerators/TypeModelHelper.cs:19]: Okay I'll revert in this PR. 

---

For 9.0, I still think we should at least have the separate implementations live next to each other so they can be kept in sync. If one generator makes an important improvement, then we would address the other one if needed.

IMO this would also increase discoverability of common concerns when handling type graphs in source-gen (formatting identifiers, visibility checks, formatting names with special syntax e.g. `@int` etc.) Authors would know to check the shared code dir for helper APIs that already exist and they might not need to rewrite.

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs (hunk 10 above)
Comment (eiriktsarpalis) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:84]: Couldn't you use another type symbol in the same assembly as a proxy for the one that will be generated?

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs (hunk 11 above)
Comment (eiriktsarpalis) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:102]: My point is we should try to use IsSymbolAccessibleWithin rather than attempt to reimplement accessibility resolution.

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs (hunk 10 above)
Comment (eiriktsarpalis) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:84]: It should be possible to use the current IAsse blySymbol as the 'within' parameter although I haven't tested that myself.

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs (hunk 11 above)
Comment (layomia) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:102]: Yeah I fully intended to use it; will do if possible per discussion here https://github.com/dotnet/runtime/pull/91657#discussion_r1318574410.

File: src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs (hunk 10 above)
Comment (layomia) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:84]: Yes I considered the proxy approach. It didn't feel deterministic on first thought, but yes it would be a correct/better check. I'll also try using the assembly symbol.

Comment (layomia) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:84]: Using a proxy would work in the common case, but we'd need to account for the edge case of the assembly having just one (e.g. a singular, simple target-config POCO with primitive fields). Any handwritten fallback would have a vastly different impl.

Comparing with assembly doesn't work - nested privates aren't visible.

Comment (eiriktsarpalis) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:84]: > Comparing with assembly doesn't work - nested privates aren't visible.

Are any of the types being generated nested within user-defined types? If not, I would expect its visibility to be equivalent to that of the assembly?

Comment (layomia) [reply src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs:84]: > Comparing with assembly doesn't work - nested privates aren't visible.

I tried it again; the assembly check works. Must have not used the `!` operator when I tried. Thanks.
