### PR TITLE
Ensure vextractf64x4 and vextracti64x4 aren't marked DstDstSrc

### LINKED ISSUE #84967: Coredistools failure to disassemble vextracti64x4
SuperPMI is reporting an asm diff in:

```
JIT.HardwareIntrinsics.General._Vector512_1.VectorGetAndWithLowerAndUpper__GetAndWithLowerAndUpperByte:RunBasicScenario():this
```

but no textual diff, for both x64 and x86. For x64, it is in 236d7997-3d71-45f9-b7d7-5241ad89a56f.windows.x64\coreclr_tests.run.windows.x64.checked.mch.

The superpmi log shows:

```
[10:34:40] ERROR: Decode Failure Left@ offset 1fb4f77e456
[10:34:40] ERROR: Decode Failure Right@ offset 1fb52ec6816
[10:34:40] ERROR: Decode Failure Left@ offset 1fb4f77e456
[10:34:40] ERROR: Decode Failure Right@ offset 1fb52ec6816
```

The issue is that coredistools is failing to disassemble:

```
62D3BD483BF001       vextracti64x4 ymm8, zmm6, 1
```

coredistools was last updated based on LLVM 13.0.1 in March 2022 with https://github.com/dotnet/jitutils/pull/351 (and related). The most recent version is LLVM 16.0.0 released March 2023 (https://releases.llvm.org/). Does it have a fix for this?

I verified that this disassembles correctly in Visual Studio.

Are there other cases where vextracti64x4 is properly decoded so it's not all cases, just some?

If we can't update coredistools with a fix, we'll have to do something so SuperPMI doesn't display spurious diffs. E.g., filter out the failing MCs.

@dotnet/avx512-contrib @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #84967

### CODE REVIEW

File: src/coreclr/jit/instrsxarch.h [hunk 1]
```diff
@@ -611,8 +611,8 @@ INST3(FIRST_AVX512_INSTRUCTION, "FIRST_AVX512_INSTRUCTION", IUM_WR, BAD_CODE, BA
...
 INST3(kmovw_msk,        "kmovw",            IUM_WR, PCKFLT(0x91),           BAD_CODE,     PCKFLT(0x90),                  INS_TT_NONE,                                          REX_W0                       | Encoding_VEX                                                                                                   | KInstruction)
 INST3(kortestw,         "kortestw",         IUM_WR, BAD_CODE,               BAD_CODE,     PCKFLT(0x98),                  INS_TT_NONE,                                          REX_W0                       | Encoding_VEX | Resets_OF      | Resets_SF     | Writes_ZF     | Resets_AF     | Resets_PF     | Writes_CF      | KInstruction)
-INST3(vextractf64x4,    "extractf64x4",     IUM_WR, SSE3A(0x1B),            BAD_CODE,     BAD_CODE,                      INS_TT_TUPLE4,                       Input_64Bit    | REX_W1_EVEX                  | Encoding_EVEX  | INS_Flags_IsDstDstSrcAVXInstruction)                                                                                           // Extract 256-bit packed double-precision floating point values
```
Comment (tannergooding) [inline src/coreclr/jit/instrsxarch.h:614]: `DstDstSrc`, `DstSrcSrc`, and others are somewhat "poor" names.

They originally existed because we didn't have proper VEX support and everything was considered RMW. So, we went from encoding things in `ModRM:reg` and `ModRM:r/m` into also having a new `VEX.vvvv` "field".

Since the vast majority of instructions were of the form `ins reg, r/m` this was basically used to indicate whether we duplicated the `Dst` (`ModRM:reg`) or `Src` (`ModRM:r/m`) register into the `VEX.vvvv` field. -- This "worked" because we also didn't really support containment for stores at all, so we never really had to care about `ModRM:r/m` being the `Dst`.

Today, we do support VEX properly, don't require everything to be viewed as `RMW`, and do also support generating stores for HWIntrinsics. So, it might be good to rethink the flag names a bit in the future. Namely, we really just care about which operands go into which of the three `ModRM:reg`, `VEX.vvvv`, and `ModRM:r/m` (with that particular order for `Dst, Op1, Op2` being the most common).

**Comment by tannergooding** [comment]
CC. @BruceForstall, @dotnet/avx512-contrib, @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]
