### PR TITLE
JIT: Fix repeatable failure for max CALLSITE_DEPTH

### LINKED ISSUE #63942: Inline depth of 0 causes an assertion during inlining
```c#
// Found by Antigen

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
        public float float_0;
    }
    public struct S2
    {
        public struct S2_D1_F2
        {
            public S1 s1_2;
        }
    }
    private static List<string> toPrint = new List<string>();
    public void Method0()
    {
        unchecked
        {
            S2.S2_D1_F2 s2_s2_d1_f2_72 = new S2.S2_D1_F2();
            S2.S2_D1_F2 s2_s2_d1_f2_73 = s2_s2_d1_f2_72;
            Log("s2_s2_d1_f", s2_s2_d1_f2_73.s1_2.float_0);
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void Log(string varName, object varValue)
    {
        toPrint.Add($"{varName}={varValue}");
    }
}

/*
COMPlus_AltJit=IcuGetLocaleInfo
COMPlus_AltJitName=clrjit_universal_arm64_x64.dll
COMPlus_EnableHWIntrinsic=0
COMPlus_JITInlineDepth=0
COMPlus_TieredCompilation=0
*/

Assert failure(PID 78956 [0x0001346c], Thread: 60264 [0xeb68]): Assertion failed 'm_IsPrejitRoot || (obs == InlineObservation::CALLSITE_TOO_MANY_LOCALS)' in 'System.Globalization.CultureData:IcuGetLocaleInfo(System.String,int,System.String):System.String:this' during 'Morph - Inlining' (IL size 105)

    File: D:\git\dotnet-runtime\src\coreclr\jit\inlinepolicy.cpp Line: 187
    Image: D:\git\dotnet-runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe


```

### PR DESCRIPTION
**Pull request by EgorBo**
Fix for a debug-only artificial assert 
Closes https://github.com/dotnet/runtime/issues/63942

### CODE REVIEW

File: src/coreclr/jit/fginline.cpp [hunk 1]
```diff
@@ -47,7 +47,9 @@ unsigned Compiler::fgCheckInlineDepthAndRecursion(InlineInfo* inlineInfo)
             // This inline candidate has the same IL code buffer as an already
             // inlined method does.
             inlineResult->NoteFatal(InlineObservation::CALLSITE_IS_RECURSIVE);
-            break;
+
+            // No need to note CALLSITE_DEPTH we're already rejecting this candidate
+            return depth;
```
Comment (EgorBo) [inline src/coreclr/jit/fginline.cpp:52]: otherwise we exit this loop and note one more "NoteFatal" while inliner in general don't expect from us multiple Fatal reasons, see https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/inlinepolicy.cpp#L187

Comment (kunalspathak) [reply src/coreclr/jit/fginline.cpp:52]: Did anything changed recently that caught this or is this a pre-existing bug?

**Review by kunalspathak — APPROVED** [review]
LGTM

File: src/coreclr/jit/fginline.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/fginline.cpp:52]: pre-existing one, it's super hard to reproduce in real world and it's absolutely harmless in Release.
In order to reproduce it without the test case you need Checked config and do 20 inlines (in deep) and 20th one should be recursive - almost impossible to meet in real world 🙂
