### PR TITLE
JIT ARM32: Force tailcall nullchecks with LR

### LINKED ISSUE #66563: Test failure JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.sh
Run: [runtime-coreclr jitstress2-jitstressregs 20220313.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1661184&view=ms.vss-test-web.build-test-results-tab&runId=45722840&resultId=108981&paneView=debug)

Failed test:
```
CoreCLR Linux arm Checked jitstress2_jitstressregs0x80 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.sh

```
**Error message:**
```
Assert failure(PID 3872 [0x00000f20], Thread: 3872 [0x0f20]): Assertion failed 'refPosition->RegOptional()' in 'MS.Internal.Xml.Cache.XPathDocumentBuilder:WriteEndAttribute():this' during 'LSRA build intervals' (IL size 175; hash 0xa29b3bbb; FullOpts)

File: /__w/1/s/src/coreclr/jit/lsra.cpp Line: 11883
Image: /root/helix/work/correlation/corerun
/root/helix/work/workitem/e/JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.sh: line 379:  3872 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false DevDiv_461649.dll ''
Gathering state for process 3872 corerun
Crashing thread 00000f20 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3872.dmp
Written 63852544 bytes (15589 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_DevDiv_461649_DevDiv_461649_DevDiv_461649_._JitBlue_DevDiv_461649_DevDiv_461649_DevDiv_461649_sh()
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
For interface tail calls we need to allocate registers for both the
target and a null-check. The register that can be used for the target is
highly constrained: it essentially only go into r12 as the arg registers
may be busy and that is the only volatile register left that will not be
overridden by the epilog. This leaves
just `LR` left for the null check, and LSRA does not seem to handle the
low amount of freedom too well (these are all allocated at the same
location, which might have something to do with it).

To help LSRA just force the null-check to happen with LR for fast
tailcalls, which is going to be killed going into the epilog anyway.

Fix #66563

cc @dotnet/jit-contrib @kunalspathak, this is the alternative fix

### CODE REVIEW

File: src/coreclr/jit/lsraarmarch.cpp [hunk 1]
```diff
@@ -207,9 +207,14 @@ int LinearScan::BuildCall(GenTreeCall* call)
 
     if (call->NeedsNullCheck())
     {
-        buildInternalIntRegisterDefForNode(call);
+        // For fast tailcalls we are very constrained here as the only two
+        // volatile registers left are lr and r12 and r12 might be needed for
+        // the target. We do not handle these constraints on the same
+        // refposition too well so we help ourselves a bit here by forcing the
+        // null check with LR.
+        regMaskTP candidates = call->IsFastTailCall() ? RBM_LR : 0;
```
Comment (kunalspathak) [inline src/coreclr/jit/lsraarmarch.cpp:215]:
```suggestion
        regMaskTP candidates = call->IsFastTailCall() ? RBM_LR : RBM_NONE;
```

**Review by kunalspathak — APPROVED** [review]
LGTM
