### PR TITLE
Handle multi-reg copies/reloads

### LINKED ISSUE #36619: Assertion failed '!"Invalid node type for GetRegTypeByIndex"'
Failure in libraries System.Xml.XmlSerializer.Tests: release libraries, checked coreclr with:
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStressRegs=8
```

Windows x86

This is pervasive in the various System.Xml tests with `JitStressRegs=8`; this is just one example.

E.g.,
```
build -s libs+libs.tests -runtimeConfiguration checked -c Release -arch x86 /p:ArchiveTests=true
```

(the `/p:ArchiveTests=true` is required to build the RunTests.cmd wrapper scripts)

```
C:\gh\runtime\artifacts\bin\System.Xml.XmlSerializer.Tests\net5.0-Release>call .\RunTests.cmd -r C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x86
```

```
----- start Sun 05/17/2020 12:19:11.04 ===============  To repro directly: =====================================================
pushd C:\gh\runtime\artifacts\bin\System.Xml.XmlSerializer.Tests\net5.0-Release\
"C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x86\dotnet.exe" exec --runtimeconfig System.Xml.XmlSerializer.Tests.runtimeconfig.json --depsfile System.Xml.XmlSerializer.Tests.deps.json xunit.console.dll System.Xml.XmlSerializer.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

C:\gh\runtime\artifacts\bin\System.Xml.XmlSerializer.Tests\net5.0-Release>"C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x86\dotnet.exe" exec --runtimeconfig System.Xml.XmlSerializer.Tests.runtimeconfig.json --depsfile System.Xml.XmlSerializer.Tests.deps.json xunit.console.dll System.Xml.XmlSerializer.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing

Assert failure(PID 23280 [0x00005af0], Thread: 31260 [0x7a1c]): Assertion failed '!"Invalid node type for GetRegTypeByIndex"' in 'System.Text.RegularExpressions.RegexNode:<ComputeMinLength>g__ComputeMinLength|87_0(System.Text.RegularExpressions.RegexNode,int):int' during 'Generate code' (IL size 406)

    File: C:\gh\runtime\src\coreclr\src\jit\gentree.h Line: 7307
    Image: C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x86\dotnet.exe

----- end Sun 05/17/2020 12:19:15.41 ----- exit code -1073740286 ----------------------------------------------------------
```

@CarolEidt

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #36619

### CODE REVIEW

File: src/coreclr/src/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -1402,7 +1402,7 @@ void CodeGen::genMultiRegStoreToLocal(GenTree* treeNode)
         // Insert pieces in reverse order
         for (int i = regCount - 1; i >= 0; --i)
         {
-            var_types type = op1->GetRegTypeByIndex(i);
+            var_types type = op1->gtSkipReloadOrCopy()->GetRegTypeByIndex(i);
```
Comment (CarolEidt) [inline src/coreclr/src/jit/codegenarmarch.cpp:1405]: A `GenTreeCopyOrReload` doesn't have reg types, so we need to skip it to get the types from its source.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Review by sandreenko — APPROVED** [review]
