### PR TITLE
Ignore CLR_DOTNET_RID when using stub cdac

### LINKED ISSUE #114538: CLR_DOTNET_RID is not set
`Format JIT codebase` legs are failing with:

```sh
1T09:34:08.2269009Z BUILD: Error: failed to generate native component build project
2025-04-11T09:34:08.2269390Z -- Compiler is not EMSCRIPTEN
2025-04-11T09:34:08.2269774Z CMake Error at debug/runtimeinfo/CMakeLists.txt:46 (message):
2025-04-11T09:34:08.2270212Z   CLR_DOTNET_RID is not set.  Please ensure it is being set to the portable
2025-04-11T09:34:08.2270622Z   RID of the target platform by runtime.proj.
```
https://github.com/dotnet/runtime/actions/runs/14400066142/job/40383649589

cc @max-charlamb related to https://github.com/dotnet/runtime/pull/113899.

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by am11**
When using stub cdac (i.e. when building just runtime without msbuild: `src/coreclr/build-runtime.sh`), it shouldn't validate `CLR_DOTNET_RID`.

Fix #114538.

### CODE REVIEW

File: src/coreclr/jit/compiler.h [hunk 1]
```diff
@@ -16,6 +16,8 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 */
 
+// dummy change to trigger formatting job
+
 /*****************************************************************************/
```
Comment (am11) [inline src/coreclr/jit/compiler.h:21]: Formatting jobs are green, undoing the dummy change.
```suggestion
/*****************************************************************************/
```

**Review by max-charlamb — APPROVED** [review]
LGTM. Shouldn't impact cDAC builds.

**Comment by am11** [comment]
@jkoritzinsky, side note for ongoing RID convergence; we can define `CLR_DOTNET_RID` cmake arg in top level project, and delete  `CLI_CMAKE_PKG_RID` from corehost. Their values seem to be computed in same way.

**Review by jkoritzinsky — APPROVED** [review]
