### PR TITLE
Fix VM calling convention detection for some pinvokes

### LINKED ISSUE #62696: Test failure Interop\\COM\\Activator\\Activator\\Activator.cmd
Run: [runtime-coreclr gcstress-extra 20211210.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1507987&view=ms.vss-test-web.build-test-results-tab&runId=42959250&paneView=debug&resultId=101012)

Failed test:
```
CoreCLR windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

- Interop\\COM\\Activator\\Activator\\Activator.cmd

```
**Error message:**
```
Assert failure(PID 8124 [0x00001fbc], Thread: 6804 [0x1a94]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

CORECLR! Object::ValidateInner + 0x149 (0x704aca49)
CORECLR! Object::Validate + 0xAF (0x704ac8bf)
CORECLR! WKS::GCHeap::Promote + 0x77 (0x7082d2a7)
CORECLR! GcEnumObject + 0x57 (0x705d3597)
CORECLR! EECodeManager::EnumGcRefs + 0x825 (0x703e97c5)
CORECLR! GcStackCrawlCallBack + 0x152 (0x705d3802)
CORECLR! Thread::MakeStackwalkerCallback + 0x48 (0x704e5ac0)
CORECLR! Thread::StackWalkFramesEx + 0x186 (0x704e71b1)
CORECLR! Thread::StackWalkFrames + 0x159 (0x704e6fab)
CORECLR! ScanStackRoots + 0x196 (0x705d2a94)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 514
Image: C:\h\w\BE790A71\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\BE790A71\w\A87C0991\uploads\Reports\Interop.COM\Activator\Activator\Activator.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\BE790A71\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Activator.dll
Built-in COM Disabled?: False
Running InvalidInterfaceRequest...
Running ClassNotRegistered...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\BE790A71\p
C:\h\w\BE790A71\w\A87C0991\e\Interop\COM\Activator\Activator\Activator.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_COM._Activator_Activator_Activator_._Activator_Activator_Activator_cmd()
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The previous calling convention logic was written
assuming the `CallConv*` collection of types were
in FQTN, including an assembly. However, if the
type is being used in the assembly it is defined,
SPCL, then we fail to match the name of the type.

Fixes #62696.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Note stacks in x86 can get out of sync like this for long stretches in EBP frames without causing obvious problems.

**Comment by AndyAyersMS** [comment]
PTAL @kunalspathak @AaronRobinsonMSFT

File: src/coreclr/vm/callconvbuilder.cpp [hunk 1]
```diff
@@ -60,7 +60,7 @@ namespace
     {
 #define BASE_CALL_CONV(name, flag) { \
         MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME_PREFIX(name), \
-        STRING_LENGTH(MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME_PREFIX(name)), \
+        STRING_LENGTH(MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME_PREFIX(name)) - 1, \
```
Comment (am11) [inline src/coreclr/vm/callconvbuilder.cpp:63]: nit: we can use `ARRAY_SIZE(MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME_PREFIX(name))` (without -1) for these, since `STRING_LENGTH` is defined as: https://github.com/dotnet/runtime/blob/69679789fba3c377b1d14689ebab2e30a9f9ad8a/src/native/minipal/utils.h#L10

**Review by am11 — COMMENTED** [review]
Thanks for fixing these. Sorry for the oversight.

File: src/coreclr/vm/callconvbuilder.cpp (hunk 1 above)
Comment (am11) [inline src/coreclr/vm/callconvbuilder.cpp:63]: Should it be instead:
```suggestion
        ARRAY_SIZE(MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME_PREFIX(name)) - 1, \
```
(or -2 with `STRING_LENGTH`). It is defined here:
https://github.com/dotnet/runtime/blob/0df121458740db1d0dd6cbe2c24bd0c94fb0af5e/src/native/minipal/utils.h#L7-L10
Previously, it was `lengthof(MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME_PREFIX(name)) - 1, \` where `lengthof` was defined as `#define lengthof(rg)    (sizeof(rg)/sizeof(rg[0]))`.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/callconvbuilder.cpp:63]: I'm missing something here. As noted above the `lengthof` approach was previously identical to `ARRAY_SIZE`. The update in the referenced PR was then converted to `STRING_LENGTH`, which is `ARRAY_SIZE - 1`. The intent here, if I recall, is to get the string character count, minus the `null`. That seems to be `STRING_LENGTH`? Subtracting another 1, means we are not removing characters from the string. I've no doubt there could be an issue here, but I am missing how this change fixes a problem.

Comment (am11) [reply src/coreclr/vm/callconvbuilder.cpp:63]: You are correct, Disregard my comment. :)

`lengthof - 1` to `STRING_LENGTH` change was correct going by the definition of `lengthof` which was deleted in https://github.com/dotnet/runtime/pull/61537.

**Comment by BruceForstall** [comment]
How could we have gone so long without seeing a failure except for in GCStress? Do we need some kind of pre-/post-call SP checking stress mode?

Would it be possible/easy to add a unit test?

**Comment by jkotas** [comment]
> Change https://github.com/dotnet/runtime/pull/61537 inadvertently left off a - 1 in some string length
computation

I do not see the problem in this change. I have checked multiple times and lengths are same before and after the change as far as I can tell. Am I missing something?

Maybe we are reading uninitialized data somewhere and this change made the uninitialized data different?

**Comment by AndyAyersMS** [comment]
In particular we had:

https://github.com/dotnet/runtime/blob/fee2bc2762f7eff616d274c57331299bd552f1f3/src/coreclr/vm/callconvbuilder.cpp#L20-L29

image

**Comment by AaronRobinsonMSFT** [comment]
I think I see the issue here. The proposed fix isn't the correct solution, but it is in the vein. @AndyAyersMS The area you pointed out is the problem space for sure. Let me see what I can root out. It would seem we made an assumptions on the definition of FullyQualifiedTypeName that aren't be held up in this scenario.

**Comment by AaronRobinsonMSFT** [comment]
Sigh... The issue here is we defined FullyQualifiedTypeName (FQTN) as described at https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/specifying-fully-qualified-type-names. This works in all public scenarios for the calling convention types because the FQTN defined SPCL and thus has the expected trialing `,`. However, if the type is in the assembly in question it doesn't have the trailing `,` and thus fails.

I need to think about this but it is clearly a case where we failed to consider internal use cases of the attributes. This is an interop bug.

/cc @dotnet/interop-contrib

**Comment by AndyAyersMS** [comment]
@AaronRobinsonMSFT happy to let you take this over. And I'll update https://github.com/dotnet/runtime/issues/62696.

File: src/coreclr/vm/callconvbuilder.cpp [hunk 2]
```diff
@@ -11,9 +11,12 @@
...
 // looking for type names that are equivalent in ASCII and UTF-8,
-// using a const char constant is acceptable. Type name strings are
-// in Fully Qualified form, so we include the ',' delimiter.
-#define MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME_PREFIX(callConvTypeName) CMOD_CALLCONV_NAMESPACE "." callConvTypeName ","
+// using a const char constant is acceptable.
+#define MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME(callConvTypeName) CMOD_CALLCONV_NAMESPACE "." callConvTypeName
+
+// We can include the ',' delimiter, when a type name is in Fully Qualified
+// form outside its declaring assembly - most common scenario.
+#define MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME_PREFIX(callConvTypeName) MAKE_FULLY_QUALIFIED_CALLCONV_TYPE_NAME(callConvTypeName) ","
```
Comment (jkotas) [inline src/coreclr/vm/callconvbuilder.cpp:19]: Instead of duplicating the type names once without `,` and second time with `,`, would it better to introduce `EqualsSimpleTypeName` matching method that succeeds when we have end-of-string or comma after the match?

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/callconvbuilder.cpp:19]: I was curious if someone was going to balk at the duplicate string arrangement. I can reduce it for sure.

**Review by jkotas — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
All relevant tests have passed. The failures are from the AzDO failures and are in the outer-loop.
