### PR TITLE
Fix issues with virtuals and mdarrays

### LINKED ISSUE #52444: Managed type system has trouble resolving virtual methods
I assume this is a regression from #51764.

In the \src\tests\JIT\Generics\Instantiation\Interfaces\Class05.cs test, we have a situation where:

```csharp
public interface IGen<T>
{
    void _Init(T fld1);
    bool InstVerify(System.Type t1);
}

public interface IGenSub2DStringArray : IGen<string[,]> { }

public class Gen2DStringArray : IGenSub2DStringArray
{
    public void _Init(string[,] fld1)
    {
    }
}
```

When the managed type system tries to find implementation of `IGen<string[]>._Init` on `Gen2DStringArray`, it will try to match up the signature of `_Init` between those two types. The signatures don't match because the signature of `_Init` on `Gen2DStringArray` has EmbeddedSignatureData of type ArrayShape with contents `1.2.2.1||0,0`, while the signature on the interface doesn't have an ArrayShape. The Equals check on the signature fails at callstack:

```
>	ILCompiler.TypeSystem.dll!Internal.TypeSystem.MethodSignature.Equals(Internal.TypeSystem.MethodSignature otherSignature, bool allowCovariantReturn) Line 220	C#
 	ILCompiler.TypeSystem.dll!Internal.TypeSystem.MethodSignature.Equals(Internal.TypeSystem.MethodSignature otherSignature) Line 185	C#
 	ILCompiler.TypeSystem.dll!Internal.TypeSystem.MetadataVirtualMethodAlgorithm.FindMatchingVirtualMethodOnTypeByNameAndSig(Internal.TypeSystem.MethodDesc targetMethod, Internal.TypeSystem.DefType currentType, bool reverseMethodSearch, System.Func<Internal.TypeSystem.MethodDesc, Internal.TypeSystem.MethodDesc, bool> nameSigMatchMethodIsValidCandidate) Line 340	C#
 	ILCompiler.TypeSystem.dll!Internal.TypeSystem.MetadataVirtualMethodAlgorithm.ResolveInterfaceMethodToVirtualMethodOnType(Internal.TypeSystem.MethodDesc interfaceMethod, Internal.TypeSystem.MetadataType currentType) Line 601	C#
 	ILCompiler.TypeSystem.dll!Internal.TypeSystem.MetadataVirtualMethodAlgorithm.ResolveInterfaceMethodToVirtualMethodOnType(Internal.TypeSystem.MethodDesc interfaceMethod, Internal.TypeSystem.TypeDesc currentType) Line 565	C#
 	ILCompiler.TypeSystem.dll!Internal.TypeSystem.TypeSystemHelpers.ResolveInterfaceMethodToVirtualMethodOnType(Internal.TypeSystem.TypeDesc type, Internal.TypeSystem.MethodDesc interfaceMethod) Line 275	C#

```

There are more tests where this is failing, but I assume in crossgen2 this only means a failure to devirtualize in these tests. The failure mode is more brutal in NativeAOT.

But this can result in incorrect devirtualization with crossgen2 if there's a matching signature in one of the base types - I assume we don't have tests for that.

Cc @dotnet/crossgen-contrib

### PR DESCRIPTION
**Pull request by davidwrighton**
- Change up the definition of an MDArray which doesn't need a special descriptor in the embedded signature data to match the type of mdarray thay everyone always uses. This fixes the virtual function handling behavior for all reasonable cases. (All cases where the MDArray is used for a base type in the expected fashion.)
- Add a devirtualization test for this specific scenario

Fixes #52444

### CODE REVIEW

File: src/coreclr/tools/Common/TypeSystem/MetadataEmitter/TypeSystemMetadataEmitter.cs [hunk 1]
```diff
@@ -424,10 +424,22 @@ public void EmitArrayShapeAtCurrentIndexStack(BlobBuilder signatureBuilder, int
 
                 if (!emittedWithShape)
                 {
-                    shapeEncoder.Shape(rank, ImmutableArray<int>.Empty, ImmutableArray<int>.Empty);
+                    shapeEncoder.Shape(rank, ImmutableArray<int>.Empty, ImmutableArraysFilledWithZeroes[rank]);
                 }
             }
 
+            static ImmutableArray<int>[] ImmutableArraysFilledWithZeroes = CreateStaticArrayOfImmutableArraysFilledWithZeroes(33); // The max rank of an array is 32
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/MetadataEmitter/TypeSystemMetadataEmitter.cs:431]: If this can come from user code, might not hurt to add a fallback that just creates a fresh immutable array if rank is more than 32. C# has no problem emitting such array.

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs [hunk 2]
```diff
@@ -169,10 +169,16 @@ private TypeDesc ParseTypeImpl(SignatureTypeCode typeCode)
...
-                                lowerBounds[j] = _reader.ReadCompressedSignedInteger();
+                            {
+                                int loBound = _reader.ReadCompressedSignedInteger();
+                                if (loBound != 0)
+                                    nonZeroLowerBounds = true;
+                                lowerBounds[j] = loBound;
+                            }
 
-                            if (boundsCount != 0 || lowerBoundsCount != 0)
+                            if (boundsCount != 0 || lowerBoundsCount != rank || nonZeroLowerBounds)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:181]: Is there a reason why this is `lowerBoundsCount != rank || nonZeroLowerBounds` instead of just `nonZeroLowerBounds`? It seems natural that if we treat `[0..,0..]` same as `[,]`, we should also treat `[0..,]` the same.

**Review by trylek — APPROVED** [review]
LGTM modulo Michal's feedback that seems reasonable and might be worth adding one or two more test cases to the IL test. Thank you!

File: src/coreclr/tools/Common/TypeSystem/MetadataEmitter/TypeSystemMetadataEmitter.cs (hunk 1 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/MetadataEmitter/TypeSystemMetadataEmitter.cs:431]: Sure, seems reasonable.

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs (hunk 2 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:181]: We don't want to treat [,] the same as [0...,0...] those are considered incompatible in a signature. Only [0...,0...] would be a valid scenario for a rank 2 mdarray to not carry the extra signature data.

**Review by phocodes — APPROVED** [review]

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!
