### PR TITLE
Ensure that InstructionSetFlags are correctly fixed up for unmatched VM

### LINKED ISSUE #41518: Consider defaulting AltJIT to all ISAs enabled
The AltJIT allows one to preview the jitted code for other architectures (such as ARM from x64) or platforms (such as Linux from Windows).

However, certain JIT settings, such as the ISAs used, are largely dependent on the machine being run against and so you cannot currently check codegen for something like `X86.Avx2` if your underlying hardware doesn't support it. Nor can you check for something like `Arm.Dp` from a x64 machine.

It would therefore be beneficial to default the AltJIT such that all ISAs are enabled by default. Individual ISAs can then be disabled by using the `COMPlus_Enable{IsaName}=0` flags (e.g. `COMPlus_EnableAvx2=0`).

This will allow codegen via an altjit to be easily checked against multiple different hardware configurations.

category:implementation
theme:altjit
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #41518 by ensuring that the JIT correctly fixes up the instruction set flags for unmatched VMs in both directions.

This allows developers to use an altJIT to debug, diagnose, and get generally accurate disassembly when working on a different architecture (such as more easily diagnosing ARM64 codegen on an x64 machine). This should be technically extensible to altJIT on the same architecture as well (i.e. we should be able to extend this so that you could use a x64 altJit to get AVX2 codegen on a machine without AVX support).

This should also allow tooling, such as @EgorBo's https://github.com/EgorBo/Disasmo, to provide disassembly for other architectures or even SxS views of different ISAs/architectures.

### CODE REVIEW

File: src/coreclr/jit/compiler.cpp [hunk 1]
```diff
@@ -5524,24 +5524,163 @@ int Compiler::compCompile(CORINFO_MODULE_HANDLE classPtr,
 
     if (!info.compMatchedVM)
```
Comment (tannergooding) [inline src/coreclr/jit/compiler.cpp:5525]: CC. @davidwrighton; would be good if you could review this since it modifies the logic you originally added.

I'd expect this is never hit for Crossgen/Crossgen2/R2R or NativeAOT as they should all have matching VMs and so I'd expect this is largely just hit for `AltJit`, is that correct?

Is there a different or better check we could do to ensure this covers "any altJit" (such as x64 on x64 even) and still ensure we don't impact the scenarios we shouldn't?

Should we add a comment explicitly clarifying this consideration (that this shouldn't impact CG2/R2R/NAOT)?

**Comment by tannergooding** [comment]
This is done and ready for review. It's going to need @davidwrighton to take a look when he has time.

**Comment by danmoseley** [comment]
Is this still waiting on @davidwrighton ?

**Comment by tannergooding** [comment]
Yes. It needs review/sign-off that there are no missed corner/edge cases around the logic and CG2

**Review by davidwrighton — APPROVED** [review]
LGTM, Sorry about the delay, I didn't realize that this was waiting on me. I assume you've validated that crossgen2 is never affected by this?

**Comment by tannergooding** [comment]
> I assume you've validated that crossgen2 is never affected by this?

As best as I can tell, that's correct. I'm not 100% however hence why I tagged you on https://github.com/dotnet/runtime/pull/64158#discussion_r790233427

**Comment by tannergooding** [comment]
Pushed a merge commit with dotnet/main. CI needs to rerun since its been over a month.
