### PR TITLE
JIT: Set edge likelihoods during patchpoint transformation

### LINKED ISSUE #97892: [jitstress] Assertion failed '!"Inconsistent profile data"'
### Error Blob

Widespread jitstress/libraries-jitstress failures with this assertion message.

```json
{
  "ErrorMessage": "Assertion failed '!\"Inconsistent profile data\"'",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

Example pipeline: https://dev.azure.com/dnceng-public/public/_build/results?buildId=550450&view=results
Example console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d022f8bbd699475db6/Regression_2/1/console.cbe04cdd.log?helixlogtype=result

cc @dotnet/jit-contrib @AndyAyersMS 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=550450
**Error message validated:** `Assertion failed '!"Inconsistent profile data"'`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/2/2024 7:43:36 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[552811](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552811)|dotnet/runtime|Summarize (windows x64)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/552811/logs/459)||

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[553217](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553217)|dotnet/runtime|[GC\\API\\GCHandleCollector\\Count\\Count.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553217&view=ms.vss-test-web.build-test-results-tab&runId=13169966&resultId=103853)|dotnet/runtime#97921|
|[553218](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553218)|dotnet/runtime|[System.Globalization.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553218&view=ms.vss-test-web.build-test-results-tab&runId=13168216&resultId=100100)|dotnet/runtime#97921|
|[553047](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553047)|dotnet/runtime|[JIT/opt/Devirtualization/GDV_GenericInterface/GDV_GenericInterface.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553047&view=ms.vss-test-web.build-test-results-tab&runId=13160432&resultId=115997)||
|[553064](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553064)|dotnet/runtime|[System.Globalization.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553064&view=ms.vss-test-web.build-test-results-tab&runId=13160218&resultId=100100)||
|[553018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553018)|dotnet/runtime|[GC\\API\\GCSettings\\InputValidation\\InputValidation.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=553018&view=ms.vss-test-web.build-test-results-tab&runId=13158662&resultId=103836)||
|[552955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552955)|dotnet/runtime|[GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552955&view=ms.vss-test-web.build-test-results-tab&runId=13157130&resultId=109497)||
|[552889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552889)|dotnet/runtime|[JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552889&view=ms.vss-test-web.build-test-results-tab&runId=13153740&resultId=164750)||
|[552851](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552851)|dotnet/runtime|[JIT/PGO/InstrumentedTiers/InstrumentedTiers/InstrumentedTiers.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552851&view=ms.vss-test-web.build-test-results-tab&runId=13152546&resultId=119740)||
|[552846](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552846)|dotnet/runtime|[JIT/opt/OSR/largefuncletframe/largefuncletframe.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552846&view=ms.vss-test-web.build-test-results-tab&runId=13152416&resultId=120797)||
|[552837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552837)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552837&view=ms.vss-test-web.build-test-results-tab&runId=13151878&resultId=115441)||
|[552638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552638)|dotnet/runtime|[System.Globalization.CalendarsWithConfigSwitch.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552638&view=ms.vss-test-web.build-test-results-tab&runId=13146920&resultId=100099)||
|[552620](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552620)|dotnet/runtime|[JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552620&view=ms.vss-test-web.build-test-results-tab&runId=13146828&resultId=159505)||
|[552584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552584)|dotnet/runtime|[GC/Scenarios/ServerModel/servermodel/servermodel.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552584&view=ms.vss-test-web.build-test-results-tab&runId=13145198&resultId=104224)||
|[552537](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552537)|dotnet/runtime|[GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552537&view=ms.vss-test-web.build-test-results-tab&runId=13144656&resultId=110183)||
|[552486](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552486)|dotnet/runtime|[JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552486&view=ms.vss-test-web.build-test-results-tab&runId=13142434&resultId=191797)||
|[552459](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552459)|dotnet/runtime|[JIT/opt/Devirtualization/GDV_GenericInterface/GDV_GenericInterface.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552459&view=ms.vss-test-web.build-test-results-tab&runId=13141548&resultId=118868)||
|[552404](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552404)|dotnet/runtime|[JIT/opt/OSR/largefuncletframe/largefuncletframe.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552404&view=ms.vss-test-web.build-test-results-tab&runId=13140092&resultId=116727)||
|[552400](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552400)|dotnet/runtime|[System.Globalization.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552400&view=ms.vss-test-web.build-test-results-tab&runId=13139314&resultId=100100)||
|[552079](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552079)|dotnet/runtime|[System.Globalization.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552079&view=ms.vss-test-web.build-test-results-tab&runId=13131160&resultId=100100)||
|[552059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552059)|dotnet/runtime|[GC\\API\\WeakReference\\Finalize2\\Finalize2.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552059&view=ms.vss-test-web.build-test-results-tab&runId=13131066&resultId=100025)||
|[552011](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552011)|dotnet/runtime|[GC/Scenarios/BinTree/thdtreegrowingobj/thdtreegrowingobj.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=552011&view=ms.vss-test-web.build-test-results-tab&runId=13129504&resultId=104501)||
|[551018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=551018)|dotnet/runtime|[GC\\Scenarios\\ServerModel\\servermodel\\servermodel.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=551018&view=ms.vss-test-web.build-test-results-tab&runId=13102520&resultId=104488)|dotnet/runtime#97865|
|[551019](https://dev.azure.com/dnceng-public/public/_build/results?buildId=551019)|dotnet/runtime|[System.Globalization.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=551019&view=ms.vss-test-web.build-test-results-tab&runId=13101684&resultId=100100)|dotnet/runtime#97865|
|[550508](https://dev.azure.com/dnceng-public/public/_build/results?buildId=550508)|dotnet/runtime|[System.Formats.Tar.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=550508&view=ms.vss-test-web.build-test-results-tab&runId=13085926&resultId=100100)||
|[550450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=550450)|dotnet/runtime|[GC\\API\\GCHandleCollector\\Count\\Count.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=550450&view=ms.vss-test-web.build-test-results-tab&runId=13084318&resultId=103870)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|9|26|26|

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #97892. During patchpoint expansion, make sure to set edge likelihoods for transformed blocks.

### CODE REVIEW

File: src/coreclr/jit/patchpoint.cpp [hunk 1]
```diff
@@ -151,8 +151,21 @@ class PatchpointTransformer
...
+        FlowEdge* const trueEdge  = compiler->fgGetPredForBlock(remainderBlock, block);
+
+        if (trueEdge->hasLikelihood())
+        {
+            falseEdge->setLikelihood(1.0 - trueEdge->getLikelihood());
+        }
+        else
+        {
+            trueEdge->setLikelihood(0.5);
+            falseEdge->setLikelihood(0.5);
```
Comment (jakobbotsch) [inline src/coreclr/jit/patchpoint.cpp:164]: The test actually passing should be very rare (I believe the threshold is 1/10000). Also, isn't `trueEdge` always going to be the `BBJ_ALWAYS` edge inserted by `fgSplitBlockAtBeginning` above, so the check here is a bit meaningless?

Comment (amanasifkhalid) [reply src/coreclr/jit/patchpoint.cpp:164]: > Also, isn't trueEdge always going to be the BBJ_ALWAYS edge inserted by fgSplitBlockAtBeginning above, so the check here is a bit meaningless?

Ah you're right, so `trueEdge` should always have an edge likelihood here. I'll remove the branch.

> The test actually passing should be very rare (I believe the threshold is 1/10000).

Is there any value to being more precise than 0.1/0.9 for `trueEdge`/`falseEdge`'s likelihoods?

Comment (jakobbotsch) [reply src/coreclr/jit/patchpoint.cpp:164]: In tier0? Doubtful. Also 1/10000 is not entirely accurate since I believe multiple patchpoints share the counter, but @AndyAyersMS can correct me if I'm wrong...

Comment (amanasifkhalid) [reply src/coreclr/jit/patchpoint.cpp:164]: I see below this snippet that `helperBlock` inherits 1% of `block`'s weight; should we have the edge likelihoods match that? So `trueEdge` is 0.99, and `falseEdge` is 0.01.

Comment (jakobbotsch) [reply src/coreclr/jit/patchpoint.cpp:164]: Makes sense to me to be consistent with that. On further look it looks like `TC_OnStackReplacement_InitialCounter` is 1000. Not sure if the mismatch is intentional or not; in a way, the most accurate guess we could make is probably `1 / <that value>`.

Comment (AndyAyersMS) [reply src/coreclr/jit/patchpoint.cpp:164]: Overall it probably doesn't matter since (at least for now) we only have patchpoints in unoptimized code. I guess I'd go with the precedent already there and use the 0.99/0.01 split.

File: src/coreclr/jit/patchpoint.cpp [hunk 2]
```diff
@@ -151,8 +151,13 @@ class PatchpointTransformer
 
         helperBlock->SetFlags(BBF_BACKWARD_JUMP | BBF_NONE_QUIRK);
 
-        compiler->fgAddRefPred(helperBlock, block);
-        compiler->fgAddRefPred(remainderBlock, helperBlock);
+        FlowEdge* const falseEdge = compiler->fgAddRefPred(helperBlock, block);
+        FlowEdge* const trueEdge  = compiler->fgGetPredForBlock(remainderBlock, block);
+        trueEdge->setLikelihood(HIGH_PROBABILITY / 100);
+        falseEdge->setLikelihood((100 - HIGH_PROBABILITY) / 100);
```
Comment (jakobbotsch) [inline src/coreclr/jit/patchpoint.cpp:157]:
```suggestion
        trueEdge->setLikelihood(HIGH_PROBABILITY / 100.0);
        falseEdge->setLikelihood((100 - HIGH_PROBABILITY) / 100.0);
```
?

**Review by jakobbotsch — APPROVED** [review]

**Comment by amanasifkhalid** [comment]
@AndyAyersMS this isn't wholly related to this change, but I wonder if we should initialize all edge likelihoods to `(1.0 / NumSucc())` (maybe in `fgLinkBasicBlocks`), so that if we encounter an edge without a likelihood, it's because we didn't set it during/after some call to `fgAddRefPred` in that phase. In the follow-up work to #97740, I'm encountering methods where we initialize the likelihoods using profile data in `fgIncorporateProfileData`, and then while inlining a method call, we don't initialize the new blocks' edge likelihoods due to a lack of profile data for the inlinee. If we have some guarantee that likelihoods will always be initialized regardless of whether `fgIncorporateProfileData` can leverage profile data, then I think the logic for setting/updating likelihoods in later phases will be simpler. What do you think?

**Comment by AndyAyersMS** [comment]
> @AndyAyersMS this isn't wholly related to this change, but I wonder if we should initialize all edge likelihoods to `(1.0 / NumSucc())` (maybe in `fgLinkBasicBlocks`), so that if we encounter an edge without a likelihood, it's because we didn't set it during/after some call to `fgAddRefPred` in that phase. In the follow-up work to #97740, I'm encountering methods where we initialize the likelihoods using profile data in `fgIncorporateProfileData`, and then while inlining a method call, we don't initialize the new blocks' edge likelihoods due to a lack of profile data for the inlinee. If we have some guarantee that likelihoods will always be initialized regardless of whether `fgIncorporateProfileData` can leverage profile data, then I think the logic for setting/updating likelihoods in later phases will be simpler. If our initial guesses for the successor edges of `BBJ_COND`, `BBJ_SWITCH`, etc don't match the profile data, then `fgIncorporateProfileData` can just overwrite them.
> 
> What do you think?

That's more or less what happens in profile synthesis, with the potential of being a bit more clever over time. Right now it is optional and off by default. So you could try turning it on when profile data is absent (just "AssignLikelihoods", not full synthesis, for now).
