### PR TITLE
Fix `UnsafeAccessor`s with enum fields

### LINKED ISSUE #102792: UnsafeAccessor throws MissingFieldException on enum fields
### Description

UnsafeAccessor throws MissingFieldException on enum fields

### Reproduction Steps

```C#
[UnsafeAccessor(UnsafeAccessorKind.Field, Name = "Enum1")]
static extern ref AnEnum GetEnum1(PrincipalBase @this);

public class PrincipalBase
{
    public AnEnum Enum1;
}

public enum AnEnum
{
    A = 1,
    B
}
```

### Expected behavior

Gets field

### Actual behavior

> System.MissingFieldException: Field not found: 'PrincipalBase.Enum1'.

### Regression?

Yes, from 9.0.100-preview.3.24204.13

### Known Workarounds

_No response_

### Configuration

.NET SDK 9.0.100-preview.6.24278.19

### Other information

_No response_

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Instead of using naive `CorElementType` and `TypeHandle` comparrisons for Fields, we now use signature comparrisons. This is both more reliable and fixes issues with Enums and previously untested scenarios with generics.

Add tests for all support `CorElementType`s.
Add test for generic enums.

Fixes https://github.com/dotnet/runtime/issues/102792

### CODE REVIEW

File: src/coreclr/vm/prestub.cpp [hunk 1]
```diff
@@ -1417,7 +1417,7 @@ namespace
 
         MethodTable* pMT = targetType.AsMethodTable();
 
-        CorElementType elemType = fieldType.GetSignatureCorElementType();
+        CorElementType elemType = fieldType.GetVerifierCorElementType();
```
Comment (jkotas) [inline src/coreclr/vm/prestub.cpp:1420]: Is this going to allow mixing and matching the enum and the underlying type (e.g. the accessor can be `int` and the actual field can be `enum Something`)?

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/prestub.cpp:1420]: Yes it will. Would you prefer I be more strict? To be fair that was the previous behavior as well.

Comment (davidwrighton) [reply src/coreclr/vm/prestub.cpp:1420]: I think so. I'm not sure if that's desirable (it might be), but in any case we need to have tests which cover that, positive or negative.

Comment (jkotas) [reply src/coreclr/vm/prestub.cpp:1420]: Do the method accessors work the same way?

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/prestub.cpp:1420]: I believe they need to be exact since we are parsing method signatures. I will see about them being precise.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/prestub.cpp:1420]: Forget this approach. I need to compare signatures.

**Review by davidwrighton — APPROVED** [review]

File: src/coreclr/vm/prestub.cpp [hunk 2]
```diff
@@ -1185,10 +1185,8 @@ namespace
             return false;
         }
 
-        BYTE callConvDecl = *pSig1;
-        BYTE callConvMethod = *pSig2;
-        pSig1++;
-        pSig2++;
+        ULONG callConvDecl = CorSigUncompressCallingConv(pSig1);
+        ULONG callConvMethod = CorSigUncompressCallingConv(pSig2);
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/prestub.cpp:1189]: I'd like to delete them, but they are being used.
