### PR TITLE
Removed unwanted ManualResetEvent from ServiceController

### LINKED ISSUE #44699: ServiceController._waitForStatusSignal is never signaled nor disposed
### Description

The System.ServiceProcess.ServiceController._waitForStatusSignal field refers to a ManualResetEvent that is constructed and possibly waited for, but never signaled nor disposed. It just causes useless work for the garbage collector and the kernel.

Constructed:
<https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs#L24>

Waited for:
<https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs#L907>

The field is private, and ServiceController is not a partial class, so there cannot be references in other files.

### Configuration

.NET v5.0.0-rtm.20519.4 on Windows, any architecture.

### Regression?

Not a regression from previous versions of .NET Core.

However, .NET Framework uses Thread.Sleep instead: <https://github.com/microsoft/referencesource/blob/f461f1986ca4027720656a0c77bede9963e20b7e/System.ServiceProcess/ServiceController.cs#L1272>

### Other information

I noticed this while looking at how <https://github.com/dotnet/runtime/issues/35284> could be implemented.

The useless ManualResetEvent was discussed in <https://github.com/dotnet/corefx/pull/627/files#r24084380> when it was first added in 2015. It was intended to be "scrapped soon".

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Fixes https://github.com/dotnet/runtime/issues/44699

### CODE REVIEW

**Comment by MCCshreyas** [comment]
image

File: src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs [hunk 1]
```diff
@@ -963,8 +961,6 @@ public void WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeou
       {
         if (DateTime.UtcNow - start > timeout)
           throw new System.ServiceProcess.TimeoutException(SR.Format(SR.Timeout, ServiceName));
-
-        _waitForStatusSignal.WaitOne(250);
```
Comment (KalleOlaviNiemitalo) [inline src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:967]: You still need some kind of wait here, to avoid wasting 100% CPU time.

Comment (MCCshreyas) [reply src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:967]: Yeah, I thought the same.
So Thread.Sleep(250) would correct here?

Comment (KalleOlaviNiemitalo) [reply src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:967]: In <https://github.com/dotnet/corefx/pull/627/files#r24128155>, Thread.Sleep was called a "legacy contract", but I think it is still the best thing to use here… unless you want to go all the way and call [NotifyServiceStatusChange](https://docs.microsoft.com/windows/win32/api/winsvc/nf-winsvc-notifyservicestatuschangew), which does not look easy; I'm not even sure how to make .NET do an alertable wait so that the asynchronous procedure call can be dequeued.

Comment (KalleOlaviNiemitalo) [reply src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:967]: If I understand correctly, WaitHandle.WaitOne can call SynchronizationContext.Current.Wait, while Thread.Sleep cannot. So if an application is using a custom SynchronizationContext, then it can detect whether ServiceController uses WaitHandle.WaitOne or Thread.Sleep.

Comment (stephentoub) [reply src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:967]: Yes, this should be `Thread.Sleep(250);`.

Comment (MCCshreyas) [reply src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:967]: OK @stephentoub. Thanks for confirmation! I will get this added with next commit!

**Review by stephentoub — APPROVED** [review]

**Comment by MCCshreyas** [comment]
@stephentoub Will this PR will get auto-merged as it's approved now? Or need to do explicitly by someone!
