### PR TITLE
Fix clrjit exports on non-Windows platforms.

### LINKED ISSUE #38189: Interop/UnmanagedCallersOnly fails on OSX.
See examples in https://dev.azure.com/dnceng/public/_build/results?buildId=697078&view=ms.vss-test-web.build-test-results-tab:
```
 Starting:    Interop.UnmanagedCallersOnly.XUnitWrapper
    Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/UnmanagedCallersOnlyTest.sh [FAIL]
      corerun(40162,0x7000034a6000) malloc: *** error for object 0x7ff51f42ac90: pointer being freed was not allocated
      *** set a breakpoint in malloc_error_break to debug
      /private/tmp/helix/working/AB440946/w/B9E409AE/e/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/UnmanagedCallersOnlyTest.sh: line 317: 40162 Illegal instruction: 4  $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /private/tmp/helix/working/AB440946/w/B9E409AE/e/Interop/UnmanagedCallersOnly/Reports/Interop.UnmanagedCallersOnly/UnmanagedCallersOnlyTest/UnmanagedCallersOnlyTest.output.txt
      Raw output:
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #38189 

/cc @janvorli @jkoritzinsky @elinor-fung

### CODE REVIEW

File: src/coreclr/tests/src/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyDll.cpp [hunk 1]
```diff
@@ -36,20 +36,33 @@ namespace
...
+
+#ifdef _WIN32
     std::thread newThreadToRuntime{ ProxyCall, &cxt };
 
     // Wait for new thread to complete
     newThreadToRuntime.join();
 
+#else // _WIN32
+    pthread_t newThreadToRuntime;
+    int ret = pthread_create(&newThreadToRuntime, NULL, ProxyCall, &cxt);
```
Comment (danmosemsft) [inline src/coreclr/tests/src/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyDll.cpp:59]: Do you receive the return value that you don't use just to avoid linter warnings?

**Comment by AaronRobinsonMSFT** [comment]
Thanks @jkotas for pressing me to root cause this. It was introduced in https://github.com/dotnet/runtime/commit/43ae9afecb6f8307afe91d73bff7435176beef56#diff-447ca31fa36a141e124dda8eab0a539c.

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
cc @janvorli

**Comment by jkotas** [comment]
cc @am11

**Comment by am11** [comment]
> It was introduced in 

Thanks for the fix. Wonder why the CI didn't caught it there.. Second, I think it would be better to bring about consistency in names, to avoid such accidents. For cmake configuration, prefixing names with JIT_ is redundant when `jit` is already in file path.

**Comment by janvorli** [comment]
@am11, I've actually wanted to ask you for one change that when I was reviewing your change - to add the name of the variable that we set the option as a parameter to the `set_exports_linker_option` instead of assuming it is `EXPORTS_LINKER_OPTION`. But I've somehow forgotten to push the comment button and then forgotten about it in the final review.
I think it would be good to do it that way - would you mind making such a change?

**Review by janvorli — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
ARM64 Failure is known: https://github.com/dotnet/runtime/issues/36681
