### PR TITLE
[JIT] Fixed improper peephole zero-extension removal when cdq/cwde instructions are involved

### LINKED ISSUE #82685: JIT: Incorrectly eliminated zero-extending mov after `cdqe`
```csharp
// Generated by Fuzzlyn v1.5 on 2023-02-26 16:54:59
// Run on X64 Linux
// Seed: 15812590312404596729
// Reduced from 254.7 KiB to 0.5 KiB in 00:04:05
// Debug: Outputs 18446744069414584320
// Release: Outputs 0
public class C0
{
    public ulong F2;
    public C0(ulong f2)
    {
        F2 = f2;
    }
}

public class Program
{
    public static ushort s_2;
    public static C0 s_7;
    public static void Main()
    {
        for (int vr0 = 0; vr0 < 2; vr0++)
        {
            s_7 = M5();
            ulong vr1 = s_7.F2;
            System.Console.WriteLine(vr1);
        }
    }

    public static C0 M5()
    {
        return new C0(~(ulong)(4294967295U & (-(1 % (s_2-- | 1)))));
    }
}
```

Diff with cac06a5d2c0787719d62aca746b0ea48c91092fe:
```diff
@@ -34,19 +34,18 @@ G_M25892_IG02:
        mov      eax, edx
        neg      eax
        cdqe     
-       mov      eax, eax
        not      rax
        mov      qword ptr [rcx+08H], rax
        mov      rax, rcx
-						;; size=67 bbWeight=1 PerfScore 33.50
+						;; size=65 bbWeight=1 PerfScore 33.25
 G_M25892_IG03:
        add      rsp, 32
        pop      rsi
        ret      
 						;; size=6 bbWeight=1 PerfScore 1.75
 
-; Total bytes of code 78, prolog size 5, PerfScore 44.30, instruction count 23, allocated bytes for code 78 (MethodHash=b6c79adb) for method Program:M5():C0
+; Total bytes of code 76, prolog size 5, PerfScore 43.85, instruction count 22, allocated bytes for code 76 (MethodHash=b6c79adb) for method Program:M5():C0
 ; ============================================================
 
 18446744073709551615
-18446744069414584320
+0

```

cc @TIHan

### PR DESCRIPTION
**Pull request by TIHan**
Resolves https://github.com/dotnet/runtime/issues/82685

### CODE REVIEW

File: src/coreclr/jit/emitxarch.cpp [hunk 1]
```diff
@@ -526,6 +526,16 @@ bool emitter::AreUpper32BitsZero(regNumber reg)
             }
         }
 
+        // This is a special case for cdq/cdqe/cwde.
+        // They always write to and sign-extend RAX.
```
[the remark this answers is not in the document]
Comment (TIHan) [reply src/coreclr/jit/emitxarch.cpp:530]: Will need to check `cdq` for EDX.

[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/emitxarch.cpp:530]: `cmpxchg16b` also can write `RDX:RAX` (and reads `RCX:RBX`)

`div`, `idiv`, `imul`, and `mul` writes `RDX:RAX`

Might be others that I'm forgetting.

[the remark this answers is not in the document]
Comment (TIHan) [reply src/coreclr/jit/emitxarch.cpp]: I don't think we emit `cmpxchg16b` or even `cmpxchg8b` AFAIK. But I did need to check for `cmpxchg`.

[the remark this answers is not in the document]
Comment (kunalspathak) [reply src/coreclr/jit/emitxarch.cpp]: I am wondering if there is a good way to track such instructions or generalize the process with adequate asserts so we can catch the issues earlier? Tracking these issues with bad code gen are really hard to investigate.

File: src/tests/JIT/opt/Regressions/Regression6.cs [hunk 2]
```diff
@@ -0,0 +1,40 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+// Generated by Fuzzlyn v1.5 on 2023-02-26 16:54:59
```
Comment (kunalspathak) [inline src/tests/JIT/opt/Regressions/Regression6.cs:4]: Do you mind replacing the fuzzlyn comment with something about the test case, basically what was the problem with below code that we fixed? I know we do not add such descriptions in lot of test cases, but will be good to have whenever possible for future maintenance.

Comment (TIHan) [reply src/tests/JIT/opt/Regressions/Regression6.cs:4]: Sure, makes sense to me.

File: src/coreclr/jit/emitxarch.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (TIHan) [reply src/coreclr/jit/emitxarch.cpp]: All I can think of is to make it more table-driven, otherwise a function that asks the question should be adequate.

Given we are only doing these checks here, we probably could create a function that simply asks "Did the instruction write to this register?" and the result is either 'true' or 'false', and if 'true' we can also provide if it zero-extended or not.
I think I'm going to have to do this anyway for https://github.com/dotnet/runtime/pull/82733 because I need to re-use the checks of whether or not a register was written to.

[the remark this answers is not in the document]
Comment (kunalspathak) [reply src/coreclr/jit/emitxarch.cpp]: I am more worried if we miss an entry of one of the instructions that we support, we might have similar bug. Is there a manual that we can refer and put all those instructions in the table or whatever data structure we have and also post the link of the manual so someone looking at the code in future can know where it is coming from?

[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/emitxarch.cpp]: The Intel and AMD architecture manuals are the relevant resource.

The ones I listed are the ones that write two registers. There are others, like `cmpxchg`, which may write a single dedicated register.

It's likely just going to require someone going through the instructions and checking for cases that use a fixed/non-specified register (for input and/or output)

**Comment by TIHan** [comment]
@dotnet/jit-contrib @kunalspathak this is ready

**Comment by TIHan** [comment]
Hardly any diffs https://dev.azure.com/dnceng-public/public/_build/results?buildId=187475&view=ms.vss-build-web.run-extensions-tab

File: src/coreclr/jit/emitxarch.cpp [hunk 3]
```diff
@@ -526,6 +526,35 @@ bool emitter::AreUpper32BitsZero(regNumber reg)
...
+                {
+                    if (reg == REG_RDX)
+                    {
+                        return PEEPHOLE_ABORT;
+                    }
+                    break;
+                }
+
+                default:
+                    break;
```
Comment (jakobbotsch) [inline src/coreclr/jit/emitxarch.cpp:554]: Should we add unreachable/an assert here? Or maybe make `instrHasImplicitRegSingleDest` also return the written register to avoid duplicating the check for instructions?

Comment (TIHan) [reply src/coreclr/jit/emitxarch.cpp:554]: I was thinking this too. I'm going to bring in some of the work I was doing in the 'redundant cmp' for this PR.

**Comment by TIHan** [comment]
@dotnet/jit-contrib This is ready again. I introduced a function, `emitIsInstrWritingToReg` to contain all the logic to determine if a register was written to - pulled it from https://github.com/dotnet/runtime/pull/82750

File: src/coreclr/jit/emitxarch.cpp [hunk 4]
```diff
@@ -677,6 +589,156 @@ bool emitter::AreUpper32BitsSignExtended(regNumber reg)
...
+// Return Value:
+//    true if the instruction writes to the given register.
+//    false if it did not, or if we can't safely determine.
+//
+bool emitter::emitIsInstrWritingToReg(instrDesc* id, regNumber reg)
+{
+    instruction ins = id->idIns();
+
+    // These are special cases since they modify one or more register(s) implicitly.
+    switch (ins)
```
Comment (tannergooding) [inline src/coreclr/jit/emitxarch.cpp:608]: Some other instructions that might need to be covered based on the architecture manual + what's defined in `instrsxarch.h`:
* `movsb/d/q` - modifies `rdi` and `rsi` (this copies `ds:rsi` to `es:rdi` and increments or decrements `rdi` and `rsi`)
* `stosb/d/q` - modifies `rdi` (this copies `rax` to `es:rdi` and increments or decrements `rdi` )
* `r_movsb/d/q` - modifies `rdi`, `rsi`, and `rcx` (rep prefix executes the instruction `rcx` times)
* `r_stosb/d/q` - modifies `rdi` and `rcx` (rep prefix executes the instruction `rcx` times)
* `xchg` - modifies both registers, so may need special handling

We don't expose things like `cmpxchg8b/16b` or other "string" functions like `lodsb/d/q`, `cmpsb/d/q`, etc.

This doesn't include special cases for SIMD registers.

Comment (TIHan) [reply src/coreclr/jit/emitxarch.cpp:608]: I'll update this list accordingly.
As for SIMD, for now I'll only accept integer registers.

Comment (TIHan) [reply src/coreclr/jit/emitxarch.cpp:608]: `xchg` should be handled by the format since it doesn't look like they are implicit.

Comment (kunalspathak) [reply src/coreclr/jit/emitxarch.cpp:613]: @tannergooding  - The instructions that you mentioned, aren't those registers are encoded in `instrDesc*`? If yes, can we just use `id->idReg1() == reg`  to compare. I can see that sometimes we might have to check for `idReg2()` or `idReg3()`, but it might vary case to case basis.

**Review by BruceForstall — APPROVED** [review]
