### PR TITLE
Fix GC stress log and analysis

### LINKED ISSUE #108628: Enable TRACE_GC validation build once the build has been fixed
https://github.com/dotnet/runtime/pull/108089 adds a (currently commented-out) validation build for the TRACE_GC flag that the GC team uses (only triggered when GC changes are made). Uncomment this once the reasons the build is broken (>16 args on the "detailed GC start" stresslog message) is fixed.

### PR DESCRIPTION
**Pull request by markples**
Summary: This includes multiple fixes to reenable the viewing of GC stress log events (from GC dprintf) in StressLogAnalyzer.  It makes a small subset of the events available in all _DEBUG builds, which provides a build check in CI without overwhelming the stress log or runtime.  This includes an audit of dprintf(1, ...) sites.  More detailed GC stress logs can be enabled by changing the sources (as before).

Fixes to StressLogAnalyzer are least-effort because it is intended to be replaced by a C# version in #104999.

Details:
- `gcDetailedStartMsg`
  - Split `gcDetailedStartMsg` to fit under the 16-argument limit for the stress log but keep all arguments for `SIMPLE_DPRINTF`
  - Cleanup
- StressLogAnalyzer
  - Handle 16-argument messages
  - Look for a prefix for `IS_GCSTART`
  - Avoid buffer over-reads
  - Avoid crash on `%5s`
- `TRACE_GC`
  - Enable `TRACE_GC` in `_DEBUG` builds
  - Change default behavior to not (re)use upper bits of LogFacility.  Leave the mechanism for private builds.
  - Audit dprintf(1) sites and change frequent ones to other values

Includes #108089 until it is merged
Fixes #108628

### CODE REVIEW

File: src/coreclr/gc/gc.h [hunk 1]
```diff
@@ -344,7 +344,7 @@ inline bool IsServerHeap()
 #define MAX_LONGPATH 1024
 #endif // MAX_LONGPATH
 
-// #define TRACE_GC
+#define TRACE_GC
```
Comment (markples) [inline src/coreclr/gc/gc.h:347]: Undo this

also check that SIMPLE_DPRINTF build still works as expected

File: src/coreclr/tools/StressLogAnalyzer/StressLogPlugin.cpp [hunk 2]
```diff
@@ -1299,6 +1295,7 @@ int ProcessStressLog(void* baseAddress, int argc, char* argv[])
     memset(&mapImageToStringId, 0, sizeof(mapImageToStringId));
     memset(s_interestingStringFilter, 0, sizeof(s_interestingStringFilter));
     memset(s_interestingStringMatchMode, 0, sizeof(s_interestingStringMatchMode));
+    s_interestingStringMatchMode[IS_GCSTART] = true;
```
Comment (markples) [inline src/coreclr/tools/StressLogAnalyzer/StressLogPlugin.cpp:1298]: This is an unfortunate detail to have here, but I don't think we want to generalize the `InterestingStrings` table to have a prefix bool.

Comment (jkoritzinsky) [reply src/coreclr/tools/StressLogAnalyzer/StressLogPlugin.cpp:1298]: This will be a little easier to do in the managed implementation I think.

File: src/coreclr/gc/gcpriv.h [hunk 3]
```diff
@@ -1578,6 +1578,10 @@ class gc_heap
 
 private:
 
+#ifdef BACKGROUND_GC
+    PER_HEAP_ISOLATED_METHOD const char* str_gc_type();
```
Comment (markples) [inline src/coreclr/gc/gcpriv.h:1582]: get_str_gc_type

File: src/coreclr/gc/gc.cpp [hunk 4]
```diff
@@ -50440,17 +50451,17 @@ void gc_heap::do_pre_gc()
...
-        (settings.concurrent ? "BGC" : (gc_heap::background_running_p() ? "FGC" : "NGC")),
+        str_gc_type(),
         settings.b_state,
-        n_heaps,
-        (heap_size_before / 1000.0 / 1000.0),
-        (max_peak_heap_size / 1000.0 / 1000.0)));
+        n_heaps
+        SIMPLE_DPRINTF_ARG(heap_size_before / 1000.0 / 1000.0)
+        SIMPLE_DPRINTF_ARG(max_peak_heap_size / 1000.0 / 1000.0)));
 #else
```
Comment (markples) [inline src/coreclr/gc/gc.cpp:50459]: remove #else

**Comment by markples** [comment]
"ILC: error IL1013: Error processing 'name'" is #108031

File: src/coreclr/gc/gc.h [hunk 5]
```diff
@@ -344,9 +344,23 @@ inline bool IsServerHeap()
 #define MAX_LONGPATH 1024
 #endif // MAX_LONGPATH
 
-// #define TRACE_GC
+// TRACE_GC has two sub-modes: the standard VM stress log mechanism and
+// SIMPLE_DPRINTF, which is text output.  By default, we enable TRACE_GC (not
+// SIMPLE_DPRINTF) for debug/checked builds so that we can catch build breaks.
+// HOST_64BIT is required because logging dprintf to the stress log us only
```
Comment (markples) [inline src/coreclr/gc/gc.h:350]: is

**Review by Maoni0 — APPROVED** [review]
other than the few minor changes you took notes of, the rest LGTM!

**Comment by mangod9** [comment]
@Maoni0, is this good to merge or there are some changes still needed?

**Comment by Maoni0** [comment]
I see the typos in the 2 comments in gcpriv.h were still not fixed...

`// HOST_64BIT is required because logging dprintf to the stress log us only`
should be
`// HOST_64BIT is required because logging dprintf to the stress log is only`

`// similarly on log messages.  A dprintf(1) is generally called about once per`
should be
`// similarly on log messages.  A dprintf(1) is generally called about a few times per`

**Comment by mangod9** [comment]
Ok, thanks. @mrsharm, can you please look into merging this PR (looks like some conflicts need to be resolved and the comments updated per Maoni above). Thx!

**Comment by mrsharm** [comment]
@mangod9 / @Maoni0: addressed the merge conflict + the comment update. Do let me know if any more changes are needed.

**Comment by jkoritzinsky** [comment]
@mrsharm You've added back the native version of the StressLogAnalyzer. Can you apply the changes that were in conflict to the managed implementation and delete the native implementation? In particular the changes to the recognition of GCStart messages

**Comment by mrsharm** [comment]
Thanks for catching that, @jkoritzinsky! Removed the old files and updated the comment. And checked the build. Do let me know if any other changes are needed.

File: src/coreclr/inc/gcmsg.inl [hunk 6]
```diff
@@ -41,12 +41,33 @@
...
+        return GC_DETAILED_START_PREFIX;
+    }
+
+    static const char* gcDetailedStartMsg(bool compatibleWithStressLog)
     {
         STATIC_CONTRACT_LEAF;
-        return "*GC* %d(gen0:%d)(%d)(alloced for %.3fms, g0 %zd (b: %zd, %zd/h) (%.3fmb/ms), g3 %zd (%.3fmb/ms), g4 %zd (%.3fmb/ms))(%s)(%d)(%d)(heap size: %.3fmb max: %.3fmb)";
+        if (compatibleWithStressLog)
+        {
+            return GC_DETAILED_START_PREFIX GC_DETAILED_START_STRESSLOG;
```
Comment (jkoritzinsky) [inline src/coreclr/inc/gcmsg.inl:59]: Can you update the GCSTART message at the following spot in StressLogAnalyzer to match the message format returned here?

https://github.com/dotnet/runtime/blob/main/src/tools/StressLogAnalyzer/src/InterestingStringFinder.cs#L28

Once that's updated, then you'll have the expected experience.

**Review by jkoritzinsky — APPROVED** [review]
