### PR TITLE
[JIT] Fixed regression for `AND(X, CNS(-1))` lowering optimization

### LINKED ISSUE #82654: JIT: Assertion failed '!arg->OperIsPutArg()' during 'Lowering nodeinfo'
```csharp
// Generated by Fuzzlyn v1.5 on 2023-02-24 23:07:44
// Run on Arm64 MacOS
// Seed: 7217345272271671129
// Reduced from 8.8 KiB to 1.2 KiB in 00:00:06
// Hits JIT assert in Release:
// Assertion failed '!arg->OperIsPutArg()' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Lowering nodeinfo' (IL size 45; hash 0xade6b36b; FullOpts)
// 
//     File: /Users/runner/work/1/s/src/coreclr/jit/lower.cpp Line: 1566
// 
public class Program
{
    public static IRuntime s_rt;
    public static long[] s_2;
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[]{System.Activator.CreateInstance(runtimeTy)});
    }

    public static void MainInner(IRuntime rt)
    {
        var vr1 = new ulong[]{0};
        byte vr2 = (byte)(M4(vr1) & ~(sbyte)(0 & s_2[0]));
        s_rt.WriteLine("c_40", vr2);
    }

    public static uint M4(ulong[] arg0)
    {
        s_rt.WriteLine("c_26", arg0[0]);
        return 0;
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC(): base(true)
    {
    }
}
```

cc @TIHan, this looks caused by #82276. It looks like we are lowering the same node multiple times because `TryLowerAndNegativeOne` returns a previous node.

### PR DESCRIPTION
**Pull request by TIHan**
Resolves https://github.com/dotnet/runtime/issues/82654

### CODE REVIEW

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -7801,43 +7801,45 @@ void Lowering::TryRetypingFloatingPointStoreToIntegerStore(GenTree* store)
...
 //    node - GT_AND node of integral type
+//    nextNode - out parameter that represents the 'gtNext' of the given node if the transformation was successful
 //
 // Return Value:
-//    Returns the replacement node if one is created else nullptr indicating no replacement
-GenTree* Lowering::TryLowerAndNegativeOne(GenTreeOp* node)
+//    Returns the true if the transformation was successful; false if it was not.
+bool Lowering::TryLowerAndNegativeOne(GenTreeOp* node, GenTree** nextNode)
 {
     assert(node->OperIs(GT_AND));
```
Comment (tannergooding) [inline src/coreclr/jit/lower.cpp:7810]: nit: Also `assert(nextNode != nullptr)` given that you're not checking for `null` below (we have a lot of methods that allow `null` for such scenarios).

File: src/coreclr/jit/lower.cpp [hunk 2]
```diff
@@ -7801,43 +7801,45 @@ void Lowering::TryRetypingFloatingPointStoreToIntegerStore(GenTree* store)
...
+        return false;
 
 #ifndef TARGET_64BIT
     assert(op2->TypeIs(TYP_INT));
 #endif // !TARGET_64BIT
 
     LIR::Use use;
     if (!BlockRange().TryGetUse(node, &use))
-        return nullptr;
+        return false;
```
Comment (tannergooding) [inline src/coreclr/jit/lower.cpp:7832]: It's worth noting that we can still do the optimization here. It just involves doing:
```cpp
if (BlockRange().TryGetUse(node, &use))
{
    use.ReplaceWith(op1);
}
else
{
    op1->SetUnusedValue();
}

*nextNode = node->gtNext;

BlockRange().Remove(op2);
BlockRange().Remove(node);

return true;
```

Comment (TIHan) [reply src/coreclr/jit/lower.cpp:7832]: Ah, interesting, I should try this.

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/lower.cpp (hunk 2 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp]: It's fine to do this since we've done the work anyway – but note that we expect dead code elimination to remove the unused nodes anyway, so there's no reason to go out of your way to do this if it required something more complicated.
