### PR TITLE
[mono] Fix virtual method resolution in mono_delegate_trampoline ().

### LINKED ISSUE #83003: [mono] Incorrect target method resolution in ldvirtftn+delegate creation
### Description

Testcase:
```
using System;

class Foo
{
	public virtual void foo () {
		Console.WriteLine ("BASE");
	}
}

class Derived : Foo
{
	void foo2 (Action a) {
		a ();
	}

	public override void foo () {
		Console.WriteLine ("DERIVED");
		foo2 (base.foo);
	}

	public static void Main(string[] args) {
		var d = new Derived ();
		d.foo ();
    }
}
```

Expected results:
```
DERIVED
BASE
```

Actual result: recursive calls to Derived:foo () causing a stack overflow and crash.
Environment: dotnet/runtime master on arm64

This is caused by this code path in mini-trampolines.c:
```
		if (delegate->method_ptr == NULL && tramp_info->method == NULL && delegate->target != NULL && method->flags & METHOD_ATTRIBUTE_VIRTUAL) {
			/* tramp_info->method == NULL happens when someone asks us to JIT some delegate's
			 * Invoke method (see compile_special).  In that case if method is virtual, the target
			 * could be some derived class, so we need to find the correct override.
			 */
```
This only happens on arm64 because arm64 doesn't have fast virtual delegate invoke trampolines, so we bail out of
handle_delegate_ctor ():
```
		if (invoke_context_used || !mono_get_delegate_virtual_invoke_impl (mono_method_signature_internal (invoke), target_method_context_used ? NULL : method))
			return NULL;
```

### Reproduction Steps

...

### Expected behavior

...

### Actual behavior

...

### Regression?

...

### Known Workarounds

...

### Configuration

...

### Other information

_No response_

### PR DESCRIPTION
**Pull request by vargaz**
Use delegate->method_is_virtual instead of complicated conditions. That flag is set by the code generated in handle_delegate_ctor () if an ldvirtftn instruction was skipped, and thus virtual method resolution needs to be done at call time.

Fixes https://github.com/dotnet/runtime/issues/83003.

### CODE REVIEW

File: src/mono/mono/mini/mini-trampolines.c [hunk 1]
```diff
@@ -1063,18 +1063,11 @@ mono_delegate_trampoline (host_mgreg_t *regs, guint8 *code, gpointer *arg, guint
 			}
 		}
 
-		if (delegate->method_ptr == NULL && tramp_info->method == NULL && delegate->target != NULL && method->flags & METHOD_ATTRIBUTE_VIRTUAL) {
-			/* tramp_info->method == NULL happens when someone asks us to JIT some delegate's
-			 * Invoke method (see compile_special).  In that case if method is virtual, the target
-			 * could be some derived class, so we need to find the correct override.
+		if (delegate->method_is_virtual) {
```
Comment (BrzVlad) [inline src/mono/mono/mini/mini-trampolines.c:1066]: Shouldn't we still do the check if `delegate->target` is non null, otherwise we crash during lookup ?

Comment (vargaz) [reply src/mono/mono/mini/mini-trampolines.c:1066]: There is a null check emitted by handle_delegate_ctor ().

Comment (BrzVlad) [reply src/mono/mono/mini/mini-trampolines.c:1066]: Isn't that just the fastpath delegate creation ? So we might have delegates from other sources with NULL targets.

Comment (vargaz) [reply src/mono/mono/mini/mini-trampolines.c:1066]: method_is_virtual is only set by the fast path which does a null check.

**Review by BrzVlad — APPROVED** [review]
