### PR TITLE
Replace assert with BADCODE

### LINKED ISSUE #74593: Assertion failed 'opcode == CEE_LDFLD && objType != nullptr' in 'ReturnTestsType:Return.LocalStructFieldByRef_Invalid_ReturnPtrToStack(Struct):byref:this' during 'Importation'
I noticed this assertion in a SuperPMI collection: PMI of coreclr_tests on Linux/arm64 (I didn't check to see if the assertion happens on other platforms).

Relevant portion of the collection log:
```
[12:52:50] '/root/helix/work/correlation/superpmi/corerun /root/helix/work/correlation/superpmi/pmi.dll DRIVEALL /root/helix/work/workitem/u/binaries/ilverify/Tests/ReturnTests.dll': Error return code: 200
[12:52:50] ============== Contents of /tmp/tmps8iwmo3z/pmi__root_helix_work_workitem_u_binaries_ilverify_Tests_ReturnTests_dll_79dffvvh.stdout
[12:52:50] DRIVEALL: Invoking /root/helix/work/correlation/superpmi/corerun /root/helix/work/correlation/superpmi/pmi.dll PREPALL /root/helix/work/workitem/u/binaries/ilverify/Tests/ReturnTests.dll 0
[12:52:50] PrepAll for ReturnTests
[12:52:50] Start type Struct
[12:52:50] Completed type Struct, elapsed ms: 17.41
[12:52:50] Start type ReturnTestsType
[12:52:50] PREPALL type# 1 method# 0 ReturnTestsType::Return.Void_Valid
[12:52:50] Completed type# 1 method# 0 ReturnTestsType::Return.Void_Valid, elapsed ms: 1.22
[12:52:50] PREPALL type# 1 method# 1 ReturnTestsType::Return.VoidNonEmptyStack_Invalid_ReturnVoid
[12:52:50] 
[12:52:50] InvalidProgramException ReturnTestsType::Return.VoidNonEmptyStack_Invalid_ReturnVoid
[12:52:50] Failed type# 1 method# 1 ReturnTestsType::Return.VoidNonEmptyStack_Invalid_ReturnVoid
[12:52:50] PREPALL type# 1 method# 2 ReturnTestsType::Return.Int32_Valid
[12:52:50] Completed type# 1 method# 2 ReturnTestsType::Return.Int32_Valid, elapsed ms: 0.95
[12:52:50] PREPALL type# 1 method# 3 ReturnTestsType::Return.Int32EmptyStack_Invalid_ReturnMissing
[12:52:50] 
[12:52:50] InvalidProgramException ReturnTestsType::Return.Int32EmptyStack_Invalid_ReturnMissing
[12:52:50] Failed type# 1 method# 3 ReturnTestsType::Return.Int32EmptyStack_Invalid_ReturnMissing
[12:52:50] PREPALL type# 1 method# 4 ReturnTestsType::Return.Int32StackLeft_Invalid_ReturnEmpty
[12:52:50] 
[12:52:50] InvalidProgramException ReturnTestsType::Return.Int32StackLeft_Invalid_ReturnEmpty
[12:52:50] Failed type# 1 method# 4 ReturnTestsType::Return.Int32StackLeft_Invalid_ReturnEmpty
[12:52:50] PREPALL type# 1 method# 5 ReturnTestsType::Return.FromTry_Invalid_ReturnFromTry
[12:52:50] 
[12:52:50] InvalidProgramException ReturnTestsType::Return.FromTry_Invalid_ReturnFromTry
[12:52:50] Failed type# 1 method# 5 ReturnTestsType::Return.FromTry_Invalid_ReturnFromTry
[12:52:50] PREPALL type# 1 method# 6 ReturnTestsType::Return.FromCatch_Invalid_ReturnFromHandler
[12:52:50] 
[12:52:50] InvalidProgramException ReturnTestsType::Return.FromCatch_Invalid_ReturnFromHandler
[12:52:50] Failed type# 1 method# 6 ReturnTestsType::Return.FromCatch_Invalid_ReturnFromHandler
[12:52:50] PREPALL type# 1 method# 7 ReturnTestsType::Return.FromFilter_Invalid_ReturnFromFilter
[12:52:50] 
[12:52:50] InvalidProgramException ReturnTestsType::Return.FromFilter_Invalid_ReturnFromFilter
[12:52:50] Failed type# 1 method# 7 ReturnTestsType::Return.FromFilter_Invalid_ReturnFromFilter
[12:52:50] PREPALL type# 1 method# 8 ReturnTestsType::Return.ObjectForInt32_Invalid_StackUnexpected
[12:52:50] Completed type# 1 method# 8 ReturnTestsType::Return.ObjectForInt32_Invalid_StackUnexpected, elapsed ms: 1.19
[12:52:50] PREPALL type# 1 method# 9 ReturnTestsType::Return.LocalArgByRef_Invalid_ReturnPtrToStack
[12:52:50] Completed type# 1 method# 9 ReturnTestsType::Return.LocalArgByRef_Invalid_ReturnPtrToStack, elapsed ms: 0.99
[12:52:50] PREPALL type# 1 method# 10 ReturnTestsType::Return.InstanceFieldByRef_Valid
[12:52:50] Completed type# 1 method# 10 ReturnTestsType::Return.InstanceFieldByRef_Valid, elapsed ms: 0.92
[12:52:50] PREPALL type# 1 method# 11 ReturnTestsType::Return.StaticFieldByRef_Valid
[12:52:50] Completed type# 1 method# 11 ReturnTestsType::Return.StaticFieldByRef_Valid, elapsed ms: 1.12
[12:52:50] PREPALL type# 1 method# 12 ReturnTestsType::Return.LocalStructFieldByRef_Invalid_ReturnPtrToStack
[12:52:50] Assert failure(PID 527 [0x0000020f], Thread: 527 [0x020f]): Assertion failed 'opcode == CEE_LDFLD && objType != nullptr' in 'ReturnTestsType:Return.LocalStructFieldByRef_Invalid_ReturnPtrToStack(Struct):byref:this' during 'Importation' (IL size 7; hash 0x5f78597c; FullOpts)    File: /__w/1/s/src/coreclr/jit/importer.cpp Line: 15980    Image: /root/helix/work/correlation/superpmi/corerun
```

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/74593

The test does:
```
.method public hidebysig instance int32& LocalStructFieldByRef_Invalid_ReturnPtrToStack(valuetype Struct s) cil managed
{
    ldarg.1
    ldflda      int32 Struct::instanceField
    ret
}
```

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
@EgorBo are you going to backport this to 7.0?

**Comment by EgorBo** [comment]
> @EgorBo are you going to backport this to 7.0?

No, it's just a test with an invalid IL

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -15989,8 +15989,12 @@ void Compiler::impImportBlockCode(BasicBlock* block)
                         // for the field to operate on the address of the struct.
                         if (!varTypeGCtype(obj->TypeGet()) && impIsValueType(tiObj))
                         {
-                            assert(opcode == CEE_LDFLD && objType != nullptr);
-
+                            if ((opcode != CEE_LDFLD) || (objType == nullptr))
+                            {
+                                BADCODE3("Unexpected opcode (has to be LDFLD) or struct type to access instance field "
```
Comment (AndyAyersMS) [inline src/coreclr/jit/importer.cpp:15994]: I don't know if this error text surfaces anywhere. If not, what you have is OK.

But if so, it might be better to have two separate checks and two BADCODEs.

The `objType == nullptr` is the case where we don't have a struct type, right? The current error text doesn't spell that out very clearly, and we might want to use ECMA-335 language here. So for the second part, how about something like:

"top of stack was not a value type"

or

"top of stack must be a value type"

**Review by jakobbotsch — APPROVED** [review]
