### PR TITLE
Fix issue 44646 - ILAsm incorrectly handles method .custom attribute when we have generic type constraint

### LINKED ISSUE #32400: ILAsm does not handle special-purpose generic constraints correctly
Recent versions of ILAsm do not seem to correctly handle special-purpose generic constraints (`class`, `valuetype`, `.ctor`) when followed by one or more type constraints and drops them from the method signature. I believe this started happening after support for `.param constraint` was added.

This results in fairly serious issues and compilation errors when referencing and interacting with the compiled assemblies; for example, the following is what Visual Studio displays for the assembly provided below when using "Go To Defintion":

image

Tested with version `5.0.0-preview.1.20116.1` of ILAsm/ILDAsm.

## Steps to reproduce
1. Pass the following IL file to `ilasm.exe` with the arguments `/DLL`:

<details>
<summary>[Click to view]</summary>

```

//  Microsoft (R) .NET Framework IL Disassembler.  Version 4.5.30319.0



// Metadata version: v4.0.30319
.assembly extern netstandard
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 2:0:0:0
}
.assembly ClassLibrary1
{
  .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
  .custom instance void [netstandard]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
  .custom instance void [netstandard]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                                63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.

  // --- The following custom attribute is added automatically, do not uncomment -------
  //  .custom instance void [netstandard]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [netstandard]System.Diagnostics.DebuggableAttribute/DebuggingModes) = ( 01 00 02 00 00 00 00 00 ) 

  .custom instance void [netstandard]System.Runtime.Versioning.TargetFrameworkAttribute::.ctor(string) = ( 01 00 19 2E 4E 45 54 53 74 61 6E 64 61 72 64 2C   // ....NETStandard,
                                                                                                           56 65 72 73 69 6F 6E 3D 76 32 2E 30 01 00 54 0E   // Version=v2.0..T.
                                                                                                           14 46 72 61 6D 65 77 6F 72 6B 44 69 73 70 6C 61   // .FrameworkDispla
                                                                                                           79 4E 61 6D 65 00 )                               // yName.
  .custom instance void [netstandard]System.Reflection.AssemblyCompanyAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
                                                                                                   00 00 ) 
  .custom instance void [netstandard]System.Reflection.AssemblyConfigurationAttribute::.ctor(string) = ( 01 00 07 52 65 6C 65 61 73 65 00 00 )             // ...Release..
  .custom instance void [netstandard]System.Reflection.AssemblyFileVersionAttribute::.ctor(string) = ( 01 00 07 31 2E 30 2E 30 2E 30 00 00 )             // ...1.0.0.0..
  .custom instance void [netstandard]System.Reflection.AssemblyInformationalVersionAttribute::.ctor(string) = ( 01 00 05 31 2E 30 2E 30 00 00 )                   // ...1.0.0..
  .custom instance void [netstandard]System.Reflection.AssemblyProductAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
                                                                                                   00 00 ) 
  .custom instance void [netstandard]System.Reflection.AssemblyTitleAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
                                                                                                 00 00 ) 
  .hash algorithm 0x00008004
  .ver 1:0:0:0
}
.module ClassLibrary1.dll
// MVID: {A9852A19-024B-4E57-BB2D-21C16A2C4625}
.imagebase 0x10000000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00000001    //  ILONLY
// Image base: 0x0000015B773C0000


// =============== CLASS MEMBERS DECLARATION ===================

.class public abstract auto ansi sealed beforefieldinit ClassLibrary1.Constraints
       extends [netstandard]System.Object
{
  .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
  .method public hidebysig static int32  A<T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.0
    IL_0001:  ret
  } // end of method Constraints::A

  .method public hidebysig static int32  B<valuetype .ctor ([netstandard]System.ValueType) T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.1
    IL_0001:  ret
  } // end of method Constraints::B

  .method public hidebysig static int32  C<class T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.2
    IL_0001:  ret
  } // end of method Constraints::C

  .method public hidebysig static int32  D<([netstandard]System.Enum) T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.3
    IL_0001:  ret
  } // end of method Constraints::D

  .method public hidebysig static int32  E<valuetype .ctor ([netstandard]System.Enum, [netstandard]System.ValueType) T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.4
    IL_0001:  ret
  } // end of method Constraints::E

  .method public hidebysig static int32  F<([netstandard]System.Delegate) T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.5
    IL_0001:  ret
  } // end of method Constraints::F

  .method public hidebysig static int32  G<class ([netstandard]System.Delegate) T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.6
    IL_0001:  ret
  } // end of method Constraints::G

  .method public hidebysig static int32  H<(class [netstandard]System.IEquatable`1<!!T>) T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.7
    IL_0001:  ret
  } // end of method Constraints::H

  .method public hidebysig static int32  I<class (class [netstandard]System.IEquatable`1<!!T>) T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.8
    IL_0001:  ret
  } // end of method Constraints::I

  .method public hidebysig static int32  J<valuetype .ctor (class [netstandard]System.IEquatable`1<!!T>, [netstandard]System.ValueType) T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       3 (0x3)
    .maxstack  8
    IL_0000:  ldc.i4.s   9
    IL_0002:  ret
  } // end of method Constraints::J

} // end of class ClassLibrary1.Constraints


// =============================================================

// *********** DISASSEMBLY COMPLETE ***********************
// WARNING: Created Win32 resource file ClassLibrary1.res

```

</details>

2. Pass the resulting DLL to `ildasm.exe` and receive the following output:

<details>
<summary>[Click to expand]</summary>

```

//  Microsoft (R) .NET Framework IL Disassembler.  Version 4.5.30319.0



// Metadata version: v4.0.30319
.assembly extern netstandard
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 2:0:0:0
}
.assembly ClassLibrary1
{
  .custom instance void [netstandard]System.Reflection.AssemblyProductAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
                                                                                                   00 00 ) 
  .custom instance void [netstandard]System.Reflection.AssemblyInformationalVersionAttribute::.ctor(string) = ( 01 00 05 31 2E 30 2E 30 00 00 )                   // ...1.0.0..
  .custom instance void [netstandard]System.Reflection.AssemblyTitleAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
                                                                                                 00 00 ) 
  .custom instance void [netstandard]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                                63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.
  .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
  .custom instance void [netstandard]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
  .custom instance void [netstandard]System.Reflection.AssemblyCompanyAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
                                                                                                   00 00 ) 
  .custom instance void [netstandard]System.Reflection.AssemblyFileVersionAttribute::.ctor(string) = ( 01 00 07 31 2E 30 2E 30 2E 30 00 00 )             // ...1.0.0.0..
  .custom instance void [netstandard]System.Runtime.Versioning.TargetFrameworkAttribute::.ctor(string) = ( 01 00 19 2E 4E 45 54 53 74 61 6E 64 61 72 64 2C   // ....NETStandard,
                                                                                                           56 65 72 73 69 6F 6E 3D 76 32 2E 30 01 00 54 0E   // Version=v2.0..T.
                                                                                                           14 46 72 61 6D 65 77 6F 72 6B 44 69 73 70 6C 61   // .FrameworkDispla
                                                                                                           79 4E 61 6D 65 00 )                               // yName.
  .custom instance void [netstandard]System.Reflection.AssemblyConfigurationAttribute::.ctor(string) = ( 01 00 07 52 65 6C 65 61 73 65 00 00 )             // ...Release..
  .hash algorithm 0x00008004
  .ver 1:0:0:0
}
.module ClassLibrary1.dll
// MVID: {DF6C6DD8-C2D5-4E9C-9F25-3EBD85D0C326}
.imagebase 0x10000000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00000001    //  ILONLY
// Image base: 0x00000232550B0000


// =============== CLASS MEMBERS DECLARATION ===================

.class public abstract auto ansi sealed beforefieldinit ClassLibrary1.Constraints
       extends [netstandard]System.Object
{
  .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
  .method public hidebysig static int32  A<T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.0
    IL_0001:  ret
  } // end of method Constraints::A

  .method public hidebysig static int32  B<([netstandard]System.ValueType) T>(!!T a) cil managed
  {
    .param constraint   T, [netstandard]System.ValueType
      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.1
    IL_0001:  ret
  } // end of method Constraints::B

  .method public hidebysig static int32  C<class T>(!!T a) cil managed
  {
    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.2
    IL_0001:  ret
  } // end of method Constraints::C

  .method public hidebysig static int32  D<([netstandard]System.Enum) T>(!!T a) cil managed
  {
    .param constraint   T, [netstandard]System.Enum
      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.3
    IL_0001:  ret
  } // end of method Constraints::D

  .method public hidebysig static int32  E<([netstandard]System.Enum, [netstandard]System.ValueType) T>(!!T a) cil managed
  {
    .param constraint   T, [netstandard]System.ValueType
      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.4
    IL_0001:  ret
  } // end of method Constraints::E

  .method public hidebysig static int32  F<([netstandard]System.Delegate) T>(!!T a) cil managed
  {
    .param constraint   T, [netstandard]System.Delegate
      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.5
    IL_0001:  ret
  } // end of method Constraints::F

  .method public hidebysig static int32  G<([netstandard]System.Delegate) T>(!!T a) cil managed
  {
    .param constraint   T, [netstandard]System.Delegate
      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.6
    IL_0001:  ret
  } // end of method Constraints::G

  .method public hidebysig static int32  H<(class [netstandard]System.IEquatable`1<!!T>) T>(!!T a) cil managed
  {
    .param constraint   T, class [netstandard]System.IEquatable`1<!!T>
      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.7
    IL_0001:  ret
  } // end of method Constraints::H

  .method public hidebysig static int32  I<(class [netstandard]System.IEquatable`1<!!T>) T>(!!T a) cil managed
  {
    .param constraint   T, class [netstandard]System.IEquatable`1<!!T>
      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       2 (0x2)
    .maxstack  8
    IL_0000:  ldc.i4.8
    IL_0001:  ret
  } // end of method Constraints::I

  .method public hidebysig static int32  J<(class [netstandard]System.IEquatable`1<!!T>, [netstandard]System.ValueType) T>(!!T a) cil managed
  {
    .param constraint   T, [netstandard]System.ValueType
      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
    // Code size       3 (0x3)
    .maxstack  8
    IL_0000:  ldc.i4.s   9
    IL_0002:  ret
  } // end of method Constraints::J

} // end of class ClassLibrary1.Constraints


// =============================================================

// *********** DISASSEMBLY COMPLETE ***********************

```

</details>

3. Diff the two files and note the missing special-purpose constraints:

<details>
<summary>[Click to view]</summary>

```diff
diff --git a/ClassLibrary1.il b/ClassLibrary1-roundtrip.il
index a08c838..b43067c 100644
--- a/ClassLibrary1.il
+++ b/ClassLibrary1-roundtrip.il
@@ -11,38 +11,34 @@
 }
 .assembly ClassLibrary1
 {
-  .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
-  .custom instance void [netstandard]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 )
+  .custom instance void [netstandard]System.Reflection.AssemblyProductAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
+                                                                                                   00 00 ) 
+  .custom instance void [netstandard]System.Reflection.AssemblyInformationalVersionAttribute::.ctor(string) = ( 01 00 05 31 2E 30 2E 30 00 00 )                   // ...1.0.0..
+  .custom instance void [netstandard]System.Reflection.AssemblyTitleAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
+                                                                                                 00 00 ) 
   .custom instance void [netstandard]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                                 63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.
-
-  // --- The following custom attribute is added automatically, do not uncomment -------
-  //  .custom instance void [netstandard]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [netstandard]System.Diagnostics.DebuggableAttribute/DebuggingModes) = ( 01 00 02 00 00 00 00 00 )
-
+  .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
+  .custom instance void [netstandard]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
+  .custom instance void [netstandard]System.Reflection.AssemblyCompanyAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
+                                                                                                   00 00 ) 
+  .custom instance void [netstandard]System.Reflection.AssemblyFileVersionAttribute::.ctor(string) = ( 01 00 07 31 2E 30 2E 30 2E 30 00 00 )             // ...1.0.0.0..
   .custom instance void [netstandard]System.Runtime.Versioning.TargetFrameworkAttribute::.ctor(string) = ( 01 00 19 2E 4E 45 54 53 74 61 6E 64 61 72 64 2C   // ....NETStandard,
                                                                                                            56 65 72 73 69 6F 6E 3D 76 32 2E 30 01 00 54 0E   // Version=v2.0..T.
                                                                                                            14 46 72 61 6D 65 77 6F 72 6B 44 69 73 70 6C 61   // .FrameworkDispla
                                                                                                            79 4E 61 6D 65 00 )                               // yName.
-  .custom instance void [netstandard]System.Reflection.AssemblyCompanyAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
-                                                                                                   00 00 )
   .custom instance void [netstandard]System.Reflection.AssemblyConfigurationAttribute::.ctor(string) = ( 01 00 07 52 65 6C 65 61 73 65 00 00 )             // ...Release..
-  .custom instance void [netstandard]System.Reflection.AssemblyFileVersionAttribute::.ctor(string) = ( 01 00 07 31 2E 30 2E 30 2E 30 00 00 )             // ...1.0.0.0..
-  .custom instance void [netstandard]System.Reflection.AssemblyInformationalVersionAttribute::.ctor(string) = ( 01 00 05 31 2E 30 2E 30 00 00 )                   // ...1.0.0..
-  .custom instance void [netstandard]System.Reflection.AssemblyProductAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
-                                                                                                   00 00 )
-  .custom instance void [netstandard]System.Reflection.AssemblyTitleAttribute::.ctor(string) = ( 01 00 0D 43 6C 61 73 73 4C 69 62 72 61 72 79 31   // ...ClassLibrary1
-                                                                                                 00 00 )
   .hash algorithm 0x00008004
   .ver 1:0:0:0
 }
 .module ClassLibrary1.dll
-// MVID: {A9852A19-024B-4E57-BB2D-21C16A2C4625}
+// MVID: {DF6C6DD8-C2D5-4E9C-9F25-3EBD85D0C326}
 .imagebase 0x10000000
 .file alignment 0x00000200
 .stackreserve 0x00100000
 .subsystem 0x0003       // WINDOWS_CUI
 .corflags 0x00000001    //  ILONLY
-// Image base: 0x0000015B773C0000
+// Image base: 0x00000199264E0000
 
 
 // =============== CLASS MEMBERS DECLARATION ===================
@@ -50,19 +46,20 @@
 .class public abstract auto ansi sealed beforefieldinit ClassLibrary1.Constraints
        extends [netstandard]System.Object
 {
-  .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+  .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
   .method public hidebysig static int32  A<T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       2 (0x2)
     .maxstack  8
     IL_0000:  ldc.i4.0
     IL_0001:  ret
   } // end of method Constraints::A
 
-  .method public hidebysig static int32  B<valuetype .ctor ([netstandard]System.ValueType) T>(!!T a) cil managed
+  .method public hidebysig static int32  B<([netstandard]System.ValueType) T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .param constraint   T, [netstandard]System.ValueType
+      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       2 (0x2)
     .maxstack  8
     IL_0000:  ldc.i4.1
@@ -71,7 +68,7 @@
 
   .method public hidebysig static int32  C<class T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       2 (0x2)
     .maxstack  8
     IL_0000:  ldc.i4.2
@@ -80,16 +77,18 @@
 
   .method public hidebysig static int32  D<([netstandard]System.Enum) T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .param constraint   T, [netstandard]System.Enum
+      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       2 (0x2)
     .maxstack  8
     IL_0000:  ldc.i4.3
     IL_0001:  ret
   } // end of method Constraints::D
 
-  .method public hidebysig static int32  E<valuetype .ctor ([netstandard]System.Enum, [netstandard]System.ValueType) T>(!!T a) cil managed
+  .method public hidebysig static int32  E<([netstandard]System.Enum, [netstandard]System.ValueType) T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .param constraint   T, [netstandard]System.ValueType
+      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       2 (0x2)
     .maxstack  8
     IL_0000:  ldc.i4.4
@@ -98,16 +97,18 @@
 
   .method public hidebysig static int32  F<([netstandard]System.Delegate) T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .param constraint   T, [netstandard]System.Delegate
+      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       2 (0x2)
     .maxstack  8
     IL_0000:  ldc.i4.5
     IL_0001:  ret
   } // end of method Constraints::F
 
-  .method public hidebysig static int32  G<class ([netstandard]System.Delegate) T>(!!T a) cil managed
+  .method public hidebysig static int32  G<([netstandard]System.Delegate) T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .param constraint   T, [netstandard]System.Delegate
+      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       2 (0x2)
     .maxstack  8
     IL_0000:  ldc.i4.6
@@ -116,25 +117,28 @@
 
   .method public hidebysig static int32  H<(class [netstandard]System.IEquatable`1<!!T>) T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .param constraint   T, class [netstandard]System.IEquatable`1<!!T>
+      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       2 (0x2)
     .maxstack  8
     IL_0000:  ldc.i4.7
     IL_0001:  ret
   } // end of method Constraints::H
 
-  .method public hidebysig static int32  I<class (class [netstandard]System.IEquatable`1<!!T>) T>(!!T a) cil managed
+  .method public hidebysig static int32  I<(class [netstandard]System.IEquatable`1<!!T>) T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .param constraint   T, class [netstandard]System.IEquatable`1<!!T>
+      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       2 (0x2)
     .maxstack  8
     IL_0000:  ldc.i4.8
     IL_0001:  ret
   } // end of method Constraints::I
 
-  .method public hidebysig static int32  J<valuetype .ctor (class [netstandard]System.IEquatable`1<!!T>, [netstandard]System.ValueType) T>(!!T a) cil managed
+  .method public hidebysig static int32  J<(class [netstandard]System.IEquatable`1<!!T>, [netstandard]System.ValueType) T>(!!T a) cil managed
   {
-    .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 )
+    .param constraint   T, [netstandard]System.ValueType
+      .custom instance void [netstandard]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
     // Code size       3 (0x3)
     .maxstack  8
     IL_0000:  ldc.i4.s   9
@@ -147,4 +151,3 @@
 // =============================================================
 
 // *********** DISASSEMBLY COMPLETE ***********************
-// WARNING: Created Win32 resource file ClassLibrary1.res

```

</details>

### LINKED ISSUE #44646: ilasm doesn't generate "this" keyword on some generic extension methods
### Description

When generating an assembly using ilasm/ildasm, some generic extensions methods don't seem to have their `this` keyword generated correctly.  Specifically, all of the methods that have a `where` constraint are missing the `this` keyword.  One other as well, but I'm not sure what the pattern is there.  See repro steps.

This issue is blocking source-build from building reference packages for 5.0 GA.

### Steps to reproduce:

1. Round trip a version of System.Xml.XDocument.dll
2. Inspect newly built System.Xml.XDocument.dll
3. Note that in the System.Xml.Linq.Extensions class, extension methods that have a `where` constraint and one other (`GetAttributes()`) are missing the `this` keyword.

```
public static class Extensions
{
	public static IEnumerable<XAttribute> Attributes(this IEnumerable<XElement> source);
	public static IEnumerable<XAttribute> Attributes(this IEnumerable<XElement> source, XName name);
	public static IEnumerable<XElement> Ancestors<T>(IEnumerable<T> source) where T : XNode;
	public static IEnumerable<XElement> Ancestors<T>(IEnumerable<T> source, XName name) where T : XNode;
	public static IEnumerable<XElement> AncestorsAndSelf(this IEnumerable<XElement> source);
	public static IEnumerable<XElement> AncestorsAndSelf(this IEnumerable<XElement> source, XName name);
	public static IEnumerable<XNode> Nodes<T>(IEnumerable<T> source) where T : XContainer;
	public static IEnumerable<XNode> DescendantNodes<T>(IEnumerable<T> source) where T : XContainer;
	public static IEnumerable<XElement> Descendants<T>(IEnumerable<T> source) where T : XContainer;
	public static IEnumerable<XElement> Descendants<T>(IEnumerable<T> source, XName name) where T : XContainer;
	public static IEnumerable<XNode> DescendantNodesAndSelf(this IEnumerable<XElement> source);
	public static IEnumerable<XElement> DescendantsAndSelf(this IEnumerable<XElement> source);
	public static IEnumerable<XElement> DescendantsAndSelf(this IEnumerable<XElement> source, XName name);
	public static IEnumerable<XElement> Elements<T>(IEnumerable<T> source) where T : XContainer;
	public static IEnumerable<XElement> Elements<T>(IEnumerable<T> source, XName name) where T : XContainer;
	public static IEnumerable<T> InDocumentOrder<T>(IEnumerable<T> source) where T : XNode;
   	private static IEnumerable<T> DocumentOrderIterator<T>(IEnumerable<T> source) where T : [IteratorStateMachine(typeof(<DocumentOrderIterator>d__17<>))] XNode;
	public static void Remove(this IEnumerable<XAttribute> source);
	public static void Remove<T>(IEnumerable<T> source) where T : XNode;
	private static IEnumerable<XAttribute> GetAttributes(IEnumerable<XElement> source, XName name);
	private static IEnumerable<XElement> GetAncestors<T>(IEnumerable<T> source, XName name, bool self) where T : [IteratorStateMachine(typeof(<GetAncestors>d__21<>))] XNode;
	private static IEnumerable<XNode> GetDescendantNodes<T>(IEnumerable<T> source, bool self) where T : [IteratorStateMachine(typeof(<GetDescendantNodes>d__22<>))] XContainer;
	private static IEnumerable<XElement> GetDescendants<T>(IEnumerable<T> source, XName name, bool self) where T : [IteratorStateMachine(typeof(<GetDescendants>d__23<>))] XContainer;
	private static IEnumerable<XElement> GetElements<T>(IEnumerable<T> source, XName name) where T : [IteratorStateMachine(typeof(<GetElements>d__24<>))] XContainer;
}
```

### PR DESCRIPTION
**Pull request by briansull**
The IL Assembler incorrectly dropped a .custom attribute for a method
This only occurs when the inline syntax for generic type parameters is used in the method definition.
This behavior can also occur for a generic class definition.
This changes fixes this issue for both generic classes and generic methods

#44646

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet/jit-contrib @BruceForstall PTAL

**Comment by briansull** [comment]
This also fixes #32400

File: src/coreclr/src/ilasm/assembler.cpp [hunk 1]
```diff
@@ -2545,13 +2554,20 @@ void Assembler::AddGenericParamConstraint(int index, char * pStrGenericParam, md
...
-    bool newlyAdded = CheckAddGenericParamConstraint(&m_pCurClass->m_GPCList, index, tkTypeConstraint);
+
+    // pass true for isParamDirective, we are parsing a .param directive for a class here
+    //
+    CheckAddGenericParamConstraint(&m_pCurClass->m_GPCList, index, tkTypeConstraint, true);
 }
 
-// returns true if we create a new GenericParamConstraintDescriptor
-// reurns false if we return an already existing GenericParamConstraintDescriptor
+// CheckAddGenericParamConstraint is called when we have to handle a generic parameter constariant
```
Comment (BruceForstall) [inline src/coreclr/src/ilasm/assembler.cpp:2563]: typo: constariant

**Review by BruceForstall — APPROVED** [review]
