### PR TITLE
[wasm][debugger] Implement Runtime.evaluate.

### LINKED ISSUE #61974: The value of the parameter cannot be changed when debugging the WASM project.
### Description

Changing a value during a debugger breakpoint does not work in a Blazor WASM project. This was found as part of exploratory testing.

### Reproduction Steps

**Repro Steps**
1. Create a Blazor WASM 6.0 project.
1. Open Pages/Counter.razor, place a breakpoint at method @code{}.
1. Run the project with F5
1. Click Counter>Click me on webpage 
1. After the breakpoint get hit on Counter.razor 
1. Change the value of currentCount to 8

### Expected behavior

Value does not change

### Actual behavior

**Actual Result**

The value of currentCount can be changed

DebugBlazor

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by thaystg**
Implement Runtime.Evaluate, the behavior is the same of Debugger.EvaluateOnCallFrame and use the first frame to evaluate.
Implementing it make possible to set variable value from VSCode and Visual Studio.

Fixes [#61974](https://github.com/dotnet/runtime/issues/61974)
Original Issues: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1366427/
JSDebugger Issue: https://github.com/microsoft/vscode-js-debug/issues/1143

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 1]
```diff
@@ -329,7 +329,7 @@ internal static async Task<JObject> CompileAndRunTheExpression(string expression
             expression = expression.Trim();
             if (!expression.StartsWith('('))
             {
-                expression = "(" + expression + ")";
+                expression = "(" + expression + "\n)";
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:332]: Is this just for readability?

Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:332]: No! The code that VS tries to evaluate is like I added in the test case.
Something like this:
`15 //evaluate from VS`
So I added this \n to avoid to comment the ")".

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 2]
```diff
@@ -401,7 +401,17 @@ protected override async Task<bool> AcceptCommand(MessageId id, string method, J
...
                     }
-
+                case "Runtime.evaluate":
+                    {
+                        if (context.CallStack != null)
+                        {
+                            Frame scope = context.CallStack.First<Frame>();
+                            return await OnEvaluateOnCallFrame(id,
+                                    scope.Id,
+                                    args?["expression"]?.Value<string>(), token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:411]: super-nit:

```suggestion
                        if (context.CallStack?.Length > 0)
                        {
                            return await OnEvaluateOnCallFrame(id,
                                    context.CallStack[0].Id,
                                    args?["expression"]?.Value<string>(), token);
```

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs (hunk 1 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:332]: can you add that as a code comment here? And maybe a `\n` before the expression too?

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
btw, can you add to the PR description why this is being added, referencing the original issue, and the jsdebugger issue too?
