### PR TITLE
Fix Culture Native and Display Names

### LINKED ISSUE #53362: [.NET 5] Proper DisplayName in CultureInfo "aa" missing
### Description

`CultureInfo` for `aa` (Afar) does not contain a proper `DisplayName` nor the `NativeName`. Both fields contain only `aa`.

**Reproduce:**

```csharp
var aa = CultureInfo.GetCultureInfo( "aa" );
```

**Expected Behaviour**

```csharp
aa.DisplayName == "Afar"
aa.NativeName == "Qafaraf"
```

**Actual Behaviour**

```csharp
aa.DisplayName == "aa"
aa.NativeName == "aa"
```

### Configuration

* Framework: `net5.0-windows10.0.19041`
* Platform: Windows 10 20H2
* Arch: x64
* Local culture: reproducible with German and English system

### Regression?

+ in .NET Framework 4.8: `aa.DisplayName == "Afar"`
+ in .NET 3.1: `aa.DisplayName == "Qafar"`

Cheers,
Georg

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/53362

This change is fixing the wrong behavior of the Culture Native and Display names. We had the following behavior:
- Display names were cached which is wrong. The display names should be treated as the localized resources and should be retrieved every time using the CurrentUICulture.
- There is some old special case for supplemental culture which is not applying anymore because Windows already using supplemental culture LCID values for some of its built-in cultures. 
- When requesting the native or display names using ICU, if ICU couldn't find a suitable resource for the request, it just return the culture name e.g. `en-US instead of English (United States) ` which is not suitable to use in the UI apps.

The fix here is doing the following:

- For display names now, we use CurrentUICulture to retrieve the name.
- Removed the supplemental culture special case. 
- When requesting the display and native names from ICU, we fallback to English names if couldn't find resources for the requested culture. 
- Added some test

### CODE REVIEW

**Comment by tarekgh** [comment]
@maryamariyan @michaelgsharp @eerhardt (My POD's fellows), could you help reviewing this change as @safern is out? feel free to ask any clarifying question if there is anything unclear here. Thanks. 

CC @stephentoub if interested to review it too.

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+        [InlineData("", "", "Invariant Language (Invariant Country)", "Invariant Language (Invariant Country)")]
+        public void TestDisplayName(string cultureName, string uiCultureName, string nativeName, string displayName)
+        {
+            RemoteExecutor.Invoke((locale, uiLocale, native, display) =>
+            {
+                CultureInfo ci = CultureInfo.GetCultureInfo(locale);
+                CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo(uiLocale);
+
+                Assert.Equal(native, ci.NativeName);
+                Assert.Equal(display, ci.DisplayName);
```
Comment (eerhardt) [inline src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:33]: Do you want to add a test that:

1. Sets the CurrentUICulture to a culture
2. Verifies `ci.DisplayName` is correct
3. Sets the CurrentUICulture to a different culture
4. Verifies `ci.DisplayName` is correct for the new culture

?

File: src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c [hunk 2]
```diff
@@ -221,28 +224,59 @@ int32_t GlobalizationNative_GetLocaleInfoString(const UChar* localeName,
     switch (localeStringData)
     {
         case LocaleString_LocalizedDisplayName:
-            uloc_getDisplayName(locale, DetectDefaultLocaleName(), value, valueLength, &status);
+            assert(uiLocaleName != NULL);
```
Comment (eerhardt) [inline src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c:227]: The `uiLocaleName` was defaulted to `null` in all the calls to the P/Invoke. Since we are asserting it is not `NULL` here, would it be better to not have the `= null` on the C# side and force callers to explicitly pass `null` in?

File: src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c [hunk 3]
```diff
@@ -221,28 +224,59 @@ int32_t GlobalizationNative_GetLocaleInfoString(const UChar* localeName,
...
             uloc_getDisplayName(locale, locale, value, valueLength, &status);
+            if (status == U_USING_DEFAULT_WARNING)
+            {
+                // The default locale data was used. i.e. couldn't find suitable resources for the requested input locale. Fallback to English instead.
+                uloc_getDisplayName(locale, ULOC_ENGLISH, value, valueLength, &status);
+            }
+
             break;
         case LocaleString_LocalizedLanguageName:
-            uloc_getDisplayLanguage(locale, DetectDefaultLocaleName(), value, valueLength, &status);
```
Comment (eerhardt) [inline src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c:233]: Is the `DetectDefaultLocaleName()` method still used anywhere? Can it be removed now?

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs [hunk 4]
```diff
@@ -1158,15 +1118,15 @@ private string LocalizedLanguageName
                         ((ci = CultureInfo.GetUserDefaultCulture()) != null) &&
                         !CultureInfo.DefaultThreadCurrentUICulture!.Name.Equals(ci.Name))
                     {
-                        _sLocalizedLanguage = NativeLanguageName;
+                        sLocalizedLanguage = NativeLanguageName;
```
Comment (eerhardt) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:1121]: Why do we need to set `sLocalizedLanguage = NativeLanguageName` here when it was set to that above?

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:33]: We already have tests validating setting the CurrentUICulture:

https://github.com/dotnet/runtime/blob/190c69d78f42f6d312d66e3676eef3a714f7bdf2/src/libraries/System.Globalization/tests/CultureInfo/CultureInfoCurrentCulture.cs#L43

https://github.com/dotnet/runtime/blob/190c69d78f42f6d312d66e3676eef3a714f7bdf2/src/libraries/System.Globalization/tests/CultureInfo/CultureInfoAsync.cs#L17

Comment (eerhardt) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:33]: Those tests are obviously not testing the scenario I described above, or else they aren't running.

From your description of this change:

> Display names were cached which is wrong. The display names should be treated as the localized resources and should be retrieved every time using the CurrentUICulture.

I'm asking for a test of this functionality.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs (hunk 4 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:1121]: This is native language and not native name.

File: src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c (hunk 3 above)
Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c:233]: This still needed here 

https://github.com/dotnet/runtime/blob/190c69d78f42f6d312d66e3676eef3a714f7bdf2/src/libraries/Native/Unix/System.Globalization.Native/pal_locale.c#L217

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs (hunk 4 above)
Comment (eerhardt) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:1121]: I don't follow.

```C#
string sLocalizedLanguage = NativeLanguageName;

// some ifs, and no one touches `sLocalizedLanguage`
...

    sLocalizedLanguage = NativeLanguageName;
```

Why are we re-setting it to the same thing?

Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:1121]: Sorry, I thought this code in the DisplayName property. you are right we don't have to reset it here. I'll remove it.

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:33]: I was trying to say, Current UI Culture wouldn't be cached if you reset it and we are already testing that. It doesn't matter the scenario you are using it for (getting resources, display names...etc.). Adding the suggested test is just testing the UI culture is not cached. I'll add the test if you think this adding any value.

File: src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c (hunk 2 above)
Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c:227]: The pinvoke is not the issue but the wrapper of the pinvoke will need to do the same (make the parameter not defaulted). If we do the wrapper too, that means we are going to touch too many places in the code, almost all callers of `IcuGetLocaleInfo` and `GetLocaleInfoCore`. I don't think we need to go to that level while we are asserting on the concerned cases.

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs (hunk 1 above)
Comment (eerhardt) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:33]: > Adding the suggested test is just testing the UI culture is not cached.

This is not true. The suggested test is testing the `ci.DisplayName` is not cached. It is to test the following change being made, from the description above:

> Display names were cached which is wrong. The display names should be treated as the localized resources and should be retrieved every time using the CurrentUICulture.

File: src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c (hunk 2 above)
Comment (eerhardt) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_localeStringData.c:227]: OK, that makes sense to me.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs [hunk 5]
```diff
@@ -1141,32 +1100,23 @@ internal string SpecificCultureName
...
-        /// Localized name for this language (Windows Only) ie: Inglis
-        /// This is only valid for Windows 8 and higher neutrals:
+        /// Localized name for this language
         /// </summary>
         private string LocalizedLanguageName
         {
             get
             {
-                if (_sLocalizedLanguage == null && !GlobalizationMode.Invariant)
+                string sLocalizedLanguage = NativeLanguageName;
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:1109]: Nit: as long as we're touching the code, can we avoid the Hungarian notation? :)

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs [hunk 6]
```diff
@@ -931,74 +927,37 @@ internal string DisplayName
...
+                        else if (Name.Equals(ZH_CHS, StringComparison.OrdinalIgnoreCase))
                         {
-                            localizedDisplayName = NativeLanguageName;
+                            localizedDisplayName = GetLanguageDisplayNameCore("zh-Hans");
                         }
                         else
                         {
-                            localizedDisplayName = NativeName;
+                            localizedDisplayName = GetLanguageDisplayNameCore(Name);
                         }
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:949]:
```C#
localizedDisplayName = GetLanguageDisplayNameCore(
    Name.Equals(ZH_CHT, StringComparison.OrdinalIgnoreCase) ? "zh-Hant" :
    Name.Equals(ZH_CHS, StringComparison.OrdinalIgnoreCase) ? "zh-Hans" :
    Name);
```
?

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs [hunk 7]
```diff
@@ -1141,32 +1100,23 @@ internal string SpecificCultureName
...
                 {
-                    // Usually the UI culture shouldn't be different than what we got from WinRT except
-                    // if DefaultThreadCurrentUICulture was set
-                    CultureInfo ci;
-
-                    if (CultureInfo.DefaultThreadCurrentUICulture != null &&
-                        ((ci = CultureInfo.GetUserDefaultCulture()) != null) &&
-                        !CultureInfo.DefaultThreadCurrentUICulture!.Name.Equals(ci.Name))
+                    // If ICU is enabled we call it anyway. If NLS, we call it only if the Windows UI language match the Current UI language
+                    if (!GlobalizationMode.UseNls || CultureInfo.UserDefaultUICulture?.Name == CultureInfo.CurrentUICulture.Name)
```
Comment (eerhardt) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:1113]: The original check was checking `DefaultThreadCurrentUICulture`, but we are no longer checking that. Is that intentional?

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs [hunk 8]
```diff
@@ -931,74 +927,37 @@ internal string DisplayName
...
-                if (localizedDisplayName == null && !GlobalizationMode.Invariant)
+                string? localizedDisplayName = NativeName;
+                if (!GlobalizationMode.Invariant && Name.Length > 0)
                 {
-                    if (IsSupplementalCustomCulture)
+                    try
                     {
-                        if (IsNeutralCulture)
+                        const string ZH_CHT = "zh-CHT";
+                        const string ZH_CHS = "zh-CHS";
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:936]: Nit: I don't think these consts help with anything... the strings are each used once, and the consts are the exact same letters as in the strings

**Review by eerhardt — APPROVED** [review]
Looks good. I just had one additional question.

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs [hunk 9]
```diff
@@ -0,0 +1,54 @@
...
+                Assert.Equal("English (United States)", ci.DisplayName);
+
+                CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("fr-FR");
+                Assert.Equal("anglais (États-Unis)", ci.DisplayName);
+
+                CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("de-DE");
+                Assert.Equal("Englisch (Vereinigte Staaten)", ci.DisplayName);
+            }).Dispose();
+        }
+    }
```
Comment (stephentoub) [inline src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:53]: Why do these tests need RemoteExecutor?

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs (hunk 7 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:1113]: Yes, that is right. The old logic was wrong especially for Windows. We should always check `CurrentUICulture` instead.

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs [hunk 10]
```diff
@@ -0,0 +1,54 @@
...
+using Microsoft.DotNet.RemoteExecutor;
+using System.Collections.Generic;
+using System.Reflection;
+using Xunit;
+
+namespace System.Globalization.Tests
+{
+    public class CultureInfoNames
+    {
+        private static bool IsIcuAndRemoteExecutionSupported => RemoteExecutor.IsSupported && PlatformDetection.IsIcuGlobalization;
```
[the remark this answers is not in the document]
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:13]: This change will depend on the ICU localized resources which I expect for the trimmed ICU will not be there. That is why I wanted to test to be scoped for the cases ensuring these resources are there. If you have better idea to try I can consider it.

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs (hunk 9 above)
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:53]: I want to have Current UI culture always be set in isolated execution environment. This to void resetting it every time we use it. The other reason I want to restrict the test to the platforms support remote execution as ICU in such environments are trimmed and I expect the ICU there will not have all needed resources we depend on.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs (hunk 5 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:1109]: Sure. I'll fix that.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs (hunk 8 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs:936]: I'll apply your suggestion you mentioned in the comment https://github.com/dotnet/runtime/pull/53468#discussion_r643993864

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs]: I removed the remote execution from the tests and I'll the CI tell if this will succeed.

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs (hunk 9 above)
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:63]: I removed the remote execution from the tests and I'll the CI tell if this will succeed.

Comment (stephentoub) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:63]: > I want to have Current UI culture always be set in isolated execution environment. This to void resetting it every time we use it.

What's the problem with resetting it every time we use it?  We use the ThreadCultureChange helper in tons of tests:
https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrentInfo.cs#L25-L28
There's an issue with using it here?  To be clear, my concern is simply that the remote execution stuff adds considerable overhead, and we've culled back usage of it to only the cases where we really do need a clean slate where we fully control everything that gets run... I'm not clear why this falls into that category (if it does, though, ok).

Comment (stephentoub) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:63]: > I removed the remote execution from the tests and I'll let CI tell if this will succeed.

Ah, great, thanks!

Comment (tarekgh) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs:47]: @stephentoub 
I am wondering about the behavior of the `ThreadCultureChange` if the execution code inside the using scope throw exception. does the dispose will get a chance to execute and restore the original cultures?

File: src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (lewing) [reply src/libraries/System.Globalization/tests/CultureInfo/CultureInfoNames.cs]: Yeah, I think we've trimmed that data so my concern is around making sure this doesn't assert in a new place.  The display names are actually something we might be able to get from the browser so there is a possibility that we could we could improve the situation on browser in the long run, but I'm not sure about the other mobile platforms.
