### PR TITLE
Remove unwanted ternary node in lowering

### LINKED ISSUE #115488: Assertion failed '!(checkUnusedValues && def->IsUnusedValue()) && "operands should never be marked as unused values"' during 'Lowering nodeinfo'
superpmi collection

[unused_value.zip](https://github.com/user-attachments/files/20174084/unused_value.zip)

```c#
// Found by Antigen
// Reduced from 50.68 KB to 1.71 KB.


using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
public class TestClass
{
    static Vector512<double> s_v512_double_51 = Vector512.Create(5.033707865168539);
    Vector512<double> v512_double_113 = Vector512.Create(-1.8461538461538463, 0, -4.942857142857143, 3.0576923076923075, 0.06382978723404255, -1.9444444444444444, 3.1363636363636362, 5.2105263157894735);
    public void Method0()
    {
        unchecked
        {
            byte byte_221 = 0;
            s_v512_double_51 = Avx512F.TernaryLogic(v512_double_113, v512_double_113, v512_double_113, byte_221);
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}
/*
Environment:

set DOTNET_TieredCompilation=0

JIT assert failed:
Assertion failed '!(checkUnusedValues && def->IsUnusedValue()) && "operands should never be marked as unused values"' in 'TestClass:Method0():this' during 'Lowering nodeinfo' (IL size 379; hash 0x46e9aa75; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\lir.cpp Line: 1649


*/

```

### PR DESCRIPTION
**Pull request by kunalspathak**
Fixes: #115488

### CODE REVIEW

File: src/coreclr/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -4052,6 +4052,7 @@ GenTree* Lowering::LowerHWIntrinsicTernaryLogic(GenTreeHWIntrinsic* node)
                             replacementNode = comp->gtNewAllBitsSetConNode(simdType);
                         }
 
+                        BlockRange().Remove(op4);
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:4055]: This should be removable for the `TernaryLogicUseFlags::C` path as well, so can likely be removed alongside `node` if `replacementNode != nullptr`

File: src/coreclr/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -4125,6 +4126,9 @@ GenTree* Lowering::LowerHWIntrinsicTernaryLogic(GenTreeHWIntrinsic* node)
                     {
                         replacementNode->SetUnusedValue();
                     }
+
+                    BlockRange().Remove(node);
+                    return node->gtNext;
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:4131]: Once it's been removed then `node->gtNext` will be `nullptr`.

You'll need to cache `gtNext`, remove `node`, then return the cached next node.

**Review by tannergooding — APPROVED** [review]

**Comment by kunalspathak** [comment]
superpmi-diff is timing out for tpdiff.
