### PR TITLE
Fix a few gcc warnings in jit

### LINKED ISSUE #57861: GCC build failure for JIT code
I hit some GCC build failure in JIT code in my PR [here](https://github.com/dotnet/runtime/pull/57101), and I don't think it has to do with my changes.

The official build log simply repeated these few failures many times:
```
In file included from /__w/1/s/src/coreclr/jit/compiler.h:30,
                 from /__w/1/s/src/coreclr/jit/jit.h:758,
                 from /__w/1/s/src/coreclr/jit/jitpch.h:18,
                 from /__w/1/s/src/coreclr/jit/alloc.cpp:4:
/__w/1/s/src/coreclr/jit/lir.h:301:30: warning: extra qualification 'LIR::' on member 'AsRange' [-fpermissive]
   301 |     static const LIR::Range& LIR::AsRange(const BasicBlock* block);
       |                              ^~~
 In file included from /__w/1/s/src/coreclr/jit/codegeninterface.h:26,
                  from /__w/1/s/src/coreclr/jit/compiler.h:51,
                  from /__w/1/s/src/coreclr/jit/jit.h:758,
                  from /__w/1/s/src/coreclr/jit/jitpch.h:18,
                  from /__w/1/s/src/coreclr/jit/alloc.cpp:4:
 /__w/1/s/src/coreclr/jit/emit.h:536:25: warning: 'emitter::emitAddrMode::amScale' is too small to hold all values of 'enum emitter::opSize'
   536 |         emitter::opSize amScale : 2;
       |                         ^~~~~~~
 /__w/1/s/src/coreclr/jit/emit.h:855:27: warning: 'emitter::instrDesc::idAddrUnion::<unnamed struct>::_idReg3' is too small to hold all values of 'regNumber' {aka 'enum _regNumber_enum'}
   855 |                 regNumber _idReg3 : REGNUM_BITS;
       |                           ^~~~~~~
 /__w/1/s/src/coreclr/jit/emit.h:856:27: warning: 'emitter::instrDesc::idAddrUnion::<unnamed struct>::_idReg4' is too small to hold all values of 'regNumber' {aka 'enum _regNumber_enum'}
   856 |                 regNumber _idReg4 : REGNUM_BITS;
       |                           ^~~~~~~
 /__w/1/s/src/coreclr/jit/emit.h:669:19: warning: 'emitter::instrDesc::_idReg1' is too small to hold all values of 'regNumber' {aka 'enum _regNumber_enum'}
   669 |         regNumber _idReg1 : REGNUM_BITS; // register num
       |                   ^~~~~~~
 /__w/1/s/src/coreclr/jit/emit.h:671:19: warning: 'emitter::instrDesc::_idReg2' is too small to hold all values of 'regNumber' {aka 'enum _regNumber_enum'}
   671 |         regNumber _idReg2 : REGNUM_BITS;
```
The warning on line 301 is obvious. All we needed to do is to get rid of the extra qualification.

The warning on line 536 is valid, there are 7 distinct values for `opSize`, but we are allocating only 2 bits for `amScale`.
https://github.com/dotnet/runtime/blob/c5f5b99ae1f084b802a91bf632b3e784cea7bb1e/src/coreclr/jit/emit.h#L457-L471

It is unclear what's wrong with the `REGNUM_BITS`. This is a failure on x64, and on x64 we should have 36 distinct enum values, and we gave 6 bits, that should be enough, but somehow GCC complains.

```
0:000> dt clrjit!emitter::instrDesc
   +0x000 _idIns           : Pos 0, 10 Bits
   +0x000 _idInsFmt        : Pos 10, 7 Bits
   +0x000 _idCodeSize      : Pos 17, 4 Bits
   +0x000 _idOpSize        : Pos 21, 3 Bits
   +0x000 _idGCref         : Pos 24, 2 Bits
   +0x000 _idReg1          : Pos 26, 6 Bits
   +0x004 _idReg2          : Pos 0, 6 Bits
   +0x004 _idSmallDsc      : Pos 6, 1 Bit
   +0x004 _idLargeCns      : Pos 7, 1 Bit
   +0x004 _idLargeDsp      : Pos 8, 1 Bit
   +0x004 _idLargeCall     : Pos 9, 1 Bit
   +0x004 _idBound         : Pos 10, 1 Bit
   +0x004 _idCallRegPtr    : Pos 11, 1 Bit
   +0x004 _idCallAddr      : Pos 12, 1 Bit
   +0x004 _idNoGC          : Pos 13, 1 Bit
   +0x004 _idCnsReloc      : Pos 14, 1 Bit
   +0x004 _idDspReloc      : Pos 15, 1 Bit
   +0x004 _idSmallCns      : Pos 16, 16 Bits
   +0x008 _idDebugOnlyInfo : Ptr64 emitter::instrDescDebugInfo
   +0x010 _idAddrUnion     : emitter::instrDesc::idAddrUnion
0:000> dt clrjit!_regNumber_enum
   REG_RAX = 0n0
   REG_RCX = 0n1
   REG_RDX = 0n2
   REG_RBX = 0n3
   REG_RSP = 0n4
   REG_RBP = 0n5
   REG_RSI = 0n6
   REG_RDI = 0n7
   REG_R8 = 0n8
   REG_R9 = 0n9
   REG_R10 = 0n10
   REG_R11 = 0n11
   REG_R12 = 0n12
   REG_R13 = 0n13
   REG_R14 = 0n14
   REG_R15 = 0n15
   REG_EAX = 0n0
   REG_ECX = 0n1
   REG_EDX = 0n2
   REG_EBX = 0n3
   REG_ESP = 0n4
   REG_EBP = 0n5
   REG_ESI = 0n6
   REG_EDI = 0n7
   REG_XMM0 = 0n16
   REG_XMM1 = 0n17
   REG_XMM2 = 0n18
   REG_XMM3 = 0n19
   REG_XMM4 = 0n20
   REG_XMM5 = 0n21
   REG_XMM6 = 0n22
   REG_XMM7 = 0n23
   REG_XMM8 = 0n24
   REG_XMM9 = 0n25
   REG_XMM10 = 0n26
   REG_XMM11 = 0n27
   REG_XMM12 = 0n28
   REG_XMM13 = 0n29
   REG_XMM14 = 0n30
   REG_XMM15 = 0n31
   REG_STK = 0n32
   REG_COUNT = 0n33
   REG_NA = 0n33
   ACTUAL_REG_COUNT = 0n32
```

This [post](https://stackoverflow.com/questions/36005063/gcc-suppress-warning-too-small-to-hold-all-values-of) on StackOverflow seems to imply that the warning is independent on the enum values. If that's the case then it at least makes sense, but I wonder what should we do about that, we can't just leave the warning there.

### PR DESCRIPTION
**Pull request by am11**
Fixes #57861

Cleans up 1045 occurrences of warning from gcc debug build logs. Remaining one compiler warning related to 'bit field width overflow', which has 2565 occurrences, is tracked by #33541.

### CODE REVIEW

**Comment by am11** [comment]
Some more  details..
The warn-as-error `-Wall` compiler flag is enabled for all compilers, for all non-mono subsets. The exception is jit with gcc, where `-Wall` is explicitly disabled due to log flood caused by bit field width overflow issue (see https://github.com/dotnet/runtime/issues/33541#issuecomment-754285791). Aside from that issue, there were a couple of warnings found in the build logs by applying the following filter, that this PR aims to fix:
`./build.sh clr -gcc 2>&1 | grep -i warn | sort -u | grep -v "too small to hold all values"`

There is one occurrence of a warning from gas assembler 'Warning: ignoring changed section attributes for .rodata' and that is _not_ related to gs_cookie (instead it's some intermediate assembly generated in /tmp; I'll investigate if there is anything actionable). All remaining 2564 warnings are in jit related to the same bit field width.

**Comment by SingleAccretion** [comment]
I think a proper way to fix the range checks is to use the `FitsIn<T>()` method (e. g. `FitsIn<int32_t>(value)`).

**Comment by am11** [comment]
> I think the proper way to fix the range checks is to use the `FitsIn<T>()` method (e. g. `FitsIn<int32_t>(value)`).

Thanks, wow didn't realize something like that exists. I will try `FitsIn<T>` next. 👍
I was looking a way to plumb [`std::numeric_limits<T>::max`](https://en.cppreference.com/w/cpp/types/numeric_limits/max) and friends through PAL, experimented with it a bit, but unsurprisingly it had longer tail (works on one platform doesn't meant it'd cover the matrix). 😅

File: src/coreclr/jit/codegenxarch.cpp [hunk 1]
```diff
@@ -2511,7 +2511,7 @@ void CodeGen::genLclHeap(GenTree* tree)
             amount /= STACK_ALIGN;
         }
 
-        genSetRegToIcon(regCnt, amount, ((int)amount == amount) ? TYP_INT : TYP_LONG);
+        genSetRegToIcon(regCnt, amount, FitsIn<int>(amount) ? TYP_INT : TYP_LONG);
```
Comment (jakobbotsch) [inline src/coreclr/jit/codegenxarch.cpp:2514]: This is a behavior change on 32-bit platforms when `amount` has the upper bit set. It will make a `TYP_LONG` node after this.
I think the equivalent expression that GCC should not warn about is `(size_t)(int)amount == amount`.

Comment (am11) [reply src/coreclr/jit/codegenxarch.cpp:2514]: > This is a behavior change on 32-bit platforms when `amount` has the upper bit set. 

AFAICT, `FitsIn<T>` (from safemath) should expand to same expression as written before.

Comment (am11) [reply src/coreclr/jit/codegenxarch.cpp:2514]: https://godbolt.org/z/8G7dedrYs (with -m32)

Comment (am11) [reply src/coreclr/jit/codegenxarch.cpp:2514]: Ah right, I can see the difference. :)

Comment (jakobbotsch) [reply src/coreclr/jit/codegenxarch.cpp:2514]: I don't see any test with `FitsIn<int>`.

Comment (am11) [reply src/coreclr/jit/codegenxarch.cpp]: Updated all callsites with suggested approach.

File: src/coreclr/jit/emitarm.cpp [hunk 2]
```diff
@@ -6790,7 +6790,7 @@ void emitter::emitDispImm(int imm, bool addComma, bool alwaysHex /* =false */)
         printf("%d", imm);
     else if ((imm > 0) ||
              (imm == -imm) || // -0x80000000 == 0x80000000. So we don't want to add an extra "-" at the beginning.
-             (emitComp->opts.disDiffable && (imm == 0xD1FFAB1E))) // Don't display this as negative
+             (emitComp->opts.disDiffable && (imm == 0xD1FFAB1EL))) // Don't display this as negative
```
Comment (jakobbotsch) [inline src/coreclr/jit/emitarm.cpp:6793]: Sorry I didn't notice this earlier, but I think this needs to be:
```suggestion
             (emitComp->opts.disDiffable && (imm == (int)0xD1FFAB1E))) // Don't display this as negative
```

I'm surprised that GCC doesn't warn here, isn't this comparison always false?

Comment (am11) [reply src/coreclr/jit/emitarm.cpp]: Yes, it seems clang and gcc have different sensitivity/tolerance levels for that value that has just overflown the type limit https://godbolt.org/z/KPof67PY3 😄

**Comment by am11** [comment]
@jakobbotsch, should we worry about other usages of `FitsIn<T>()` on 32-bit platforms and fix that for cases like `FitsIn<int>(anUnsignedInt)`? Note that we have globally turned off family of tautological comparison warnings, so bug in utility function can get slipped rather easily.

**Comment by jakobbotsch** [comment]
> @jakobbotsch, should we worry about other usages of FitsIn<T>() on 32-bit platforms and fix that for cases like FitsIn<int>(anUnsignedInt)?

I don't think so, `FitsIn` is a quite semantic operation, asking if the "semantic" value can be represented in another data type. It's not always the operation we want in the JIT when we want to cast between signed/unsigned values for various reasons.

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Thanks!
