### PR TITLE
Ensure the scalar Reciprocal*Estimate APIs use AVX512 where possible

### LINKED ISSUE #98732: Test failure Assert.All() Failure: 12 out of 256 items in the collection did not pass
**Failed in:** [runtime-coreclr libraries-jitstress 20240219.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=572369&view=ms.vss-test-web.build-test-results-tab&runId=13716158&resultId=208265&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
net9.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
```

**Error message:**
```
Assert.All() Failure: 12 out of 256 items in the collection did not pass.
[3]:  Item:  4
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.151808769
             Actual:   0.153238416
[4]:  Item:  5
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.253379166
             Actual:   0.370503962
[5]:  Item:  6
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.344092488
             Actual:   -0.385987788
[6]:  Item:  7
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.410494238
             Actual:   -0.477760583
[7]:  Item:  8
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.114995345
             Actual:   0.115108378
[8]:  Item:  9
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.307092249
             Actual:   0.334470063
[9]:  Item:  10
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.0431030653
             Actual:   0.0478207767
[10]: Item:  11
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.565155208
             Actual:   -0.611512542
[11]: Item:  12
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.120973401
             Actual:   0.142828137
[12]: Item:  13
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.177610368
             Actual:   -0.228073046
[13]: Item:  14
      Error: Assert.Equal() Failure: Values differ
             Expected: -0.0260503069
             Actual:   -0.0323534235
[14]: Item:  15
      Error: Assert.Equal() Failure: Values differ
             Expected: 0.301667929
             Actual:   0.351612419
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 738
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

### LINKED ISSUE #101721: System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanScalarDestination_SpecialValues fails
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=660483
Build error leg or test failing: System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanScalarDestination_SpecialValues
Pull request: https://github.com/dotnet/runtime/pull/101713

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanScalarDestination_SpecialValues.*FAIL",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=660483
**Error message validated:** `[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanScalarDestination_SpecialValues.*FAIL`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/30/2024 3:25:18 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[662495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662495)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/662495/logs/1925)|dotnet/runtime#101781|
|[661992](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661992)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/661992/logs/1091)|dotnet/runtime#101652|
|[660080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660080)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/660080/logs/942)|dotnet/runtime#101701|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[665288](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665288)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665288&view=ms.vss-test-web.build-test-results-tab&runId=16500476&resultId=178781)|dotnet/runtime#101773|
|[665282](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665282)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665282&view=ms.vss-test-web.build-test-results-tab&runId=16500394&resultId=176850)|dotnet/runtime#101856|
|[665258](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665258)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665258&view=ms.vss-test-web.build-test-results-tab&runId=16500238&resultId=176111)|dotnet/runtime#101867|
|[665261](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665261)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665261&view=ms.vss-test-web.build-test-results-tab&runId=16500234&resultId=180136)|dotnet/runtime#99183|
|[665255](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665255)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665255&view=ms.vss-test-web.build-test-results-tab&runId=16500230&resultId=175983)|dotnet/runtime#101580|
|[665245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665245)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665245&view=ms.vss-test-web.build-test-results-tab&runId=16500110&resultId=177566)|dotnet/runtime#101836|
|[665208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665208)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665208&view=ms.vss-test-web.build-test-results-tab&runId=16499388&resultId=177223)|dotnet/runtime#101865|
|[665198](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665198)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665198&view=ms.vss-test-web.build-test-results-tab&runId=16499256&resultId=180812)|dotnet/runtime#99871|
|[665182](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665182)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665182&view=ms.vss-test-web.build-test-results-tab&runId=16499104&resultId=183710)|dotnet/runtime#101864|
|[665137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665137)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665137&view=ms.vss-test-web.build-test-results-tab&runId=16498080&resultId=176493)|dotnet/runtime#101277|
|[665103](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665103)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665103&view=ms.vss-test-web.build-test-results-tab&runId=16497772&resultId=178678)|dotnet/runtime#101856|
|[665109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665109)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665109&view=ms.vss-test-web.build-test-results-tab&runId=16497770&resultId=177139)|dotnet/runtime#101613|
|[665043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665043)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665043&view=ms.vss-test-web.build-test-results-tab&runId=16496668&resultId=174888)|dotnet/runtime#101379|
|[665040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665040)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665040&view=ms.vss-test-web.build-test-results-tab&runId=16496664&resultId=182144)|dotnet/runtime#101379|
|[665016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665016)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanScalarDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665016&view=ms.vss-test-web.build-test-results-tab&runId=16496380&resultId=178808)|dotnet/runtime#101859|
|[665005](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665005)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665005&view=ms.vss-test-web.build-test-results-tab&runId=16496200&resultId=176012)|dotnet/runtime#101858|
|[665008](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665008)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665008&view=ms.vss-test-web.build-test-results-tab&runId=16496188&resultId=168777)|dotnet/runtime#99183|
|[664964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664964)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664964&view=ms.vss-test-web.build-test-results-tab&runId=16495598&resultId=177694)|dotnet/runtime#101834|
|[664898](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664898)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664898&view=ms.vss-test-web.build-test-results-tab&runId=16494636&resultId=171669)|dotnet/runtime#101855|
|[664884](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664884)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664884&view=ms.vss-test-web.build-test-results-tab&runId=16494402&resultId=173132)|dotnet/runtime#101854|
|[664858](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664858)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664858&view=ms.vss-test-web.build-test-results-tab&runId=16493056&resultId=177188)|dotnet/runtime#101853|
|[664821](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664821)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664821&view=ms.vss-test-web.build-test-results-tab&runId=16491964&resultId=176617)|dotnet/runtime#101836|
|[664813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664813)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664813&view=ms.vss-test-web.build-test-results-tab&runId=16491882&resultId=175171)|dotnet/runtime#101295|
|[664804](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664804)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664804&view=ms.vss-test-web.build-test-results-tab&runId=16491736&resultId=177010)|dotnet/runtime#101851|
|[664785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664785)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664785&view=ms.vss-test-web.build-test-results-tab&runId=16490866&resultId=177869)|dotnet/runtime#99818|
|[664148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664148)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664148&view=ms.vss-test-web.build-test-results-tab&runId=16490680&resultId=176394)|dotnet/runtime#101834|
|[664770](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664770)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664770&view=ms.vss-test-web.build-test-results-tab&runId=16490348&resultId=177071)|dotnet/runtime#101849|
|[664752](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664752)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664752&view=ms.vss-test-web.build-test-results-tab&runId=16489858&resultId=175406)|dotnet/runtime#101848|
|[664722](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664722)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664722&view=ms.vss-test-web.build-test-results-tab&runId=16488904&resultId=176357)|dotnet/runtime#101843|
|[664716](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664716)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664716&view=ms.vss-test-web.build-test-results-tab&runId=16488494&resultId=175153)|dotnet/runtime#101761|
|[664710](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664710)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664710&view=ms.vss-test-web.build-test-results-tab&runId=16488466&resultId=177064)|dotnet/runtime#101801|
|[664701](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664701)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664701&view=ms.vss-test-web.build-test-results-tab&runId=16488254&resultId=181290)|dotnet/runtime#101836|
|[664608](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664608)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664608&view=ms.vss-test-web.build-test-results-tab&runId=16487192&resultId=176109)|dotnet/runtime#101717|
|[664560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664560)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664560&view=ms.vss-test-web.build-test-results-tab&runId=16486450&resultId=176277)|dotnet/runtime#101844|
|[664531](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664531)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664531&view=ms.vss-test-web.build-test-results-tab&runId=16484718&resultId=169530)|dotnet/runtime#101842|
|[664434](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664434)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664434&view=ms.vss-test-web.build-test-results-tab&runId=16479136&resultId=177598)|dotnet/runtime#101340|
|[664426](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664426)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664426&view=ms.vss-test-web.build-test-results-tab&runId=16479018&resultId=180387)|dotnet/runtime#101763|
|[664405](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664405)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664405&view=ms.vss-test-web.build-test-results-tab&runId=16478554&resultId=176500)|dotnet/runtime#101640|
|[664408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664408)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664408&view=ms.vss-test-web.build-test-results-tab&runId=16478538&resultId=175546)|dotnet/runtime#101640|
|[664396](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664396)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664396&view=ms.vss-test-web.build-test-results-tab&runId=16478414&resultId=179832)|dotnet/runtime#101801|
|[664382](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664382)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664382&view=ms.vss-test-web.build-test-results-tab&runId=16477556&resultId=175122)|dotnet/runtime#101836|
|[664378](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664378)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanScalarDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664378&view=ms.vss-test-web.build-test-results-tab&runId=16477474&resultId=175826)|dotnet/runtime#101624|
|[664282](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664282)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664282&view=ms.vss-test-web.build-test-results-tab&runId=16474138&resultId=175196)|dotnet/runtime#101836|
|[664217](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664217)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664217&view=ms.vss-test-web.build-test-results-tab&runId=16472364&resultId=176977)|dotnet/runtime#99490|
|[664190](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664190)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664190&view=ms.vss-test-web.build-test-results-tab&runId=16471418&resultId=170384)|dotnet/runtime#101717|
|[664184](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664184)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664184&view=ms.vss-test-web.build-test-results-tab&runId=16471382&resultId=175756)|dotnet/runtime#101379|
|[664056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664056)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664056&view=ms.vss-test-web.build-test-results-tab&runId=16466924&resultId=175139)|dotnet/runtime#101827|
|[664029](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664029)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=664029&view=ms.vss-test-web.build-test-results-tab&runId=16466490&resultId=175880)|dotnet/runtime#101826|
|[663938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663938)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663938&view=ms.vss-test-web.build-test-results-tab&runId=16463032&resultId=176565)|dotnet/runtime#101825|
|[663922](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663922)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663922&view=ms.vss-test-web.build-test-results-tab&runId=16462878&resultId=185245)|dotnet/runtime#101824|
|[663755](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663755)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663755&view=ms.vss-test-web.build-test-results-tab&runId=16459852&resultId=177113)|dotnet/runtime#101806|
|[663715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663715)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663715&view=ms.vss-test-web.build-test-results-tab&runId=16458882&resultId=184880)|dotnet/runtime#101811|
|[663696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663696)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663696&view=ms.vss-test-web.build-test-results-tab&runId=16458136&resultId=176183)|dotnet/runtime#101773|
|[663591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663591)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663591&view=ms.vss-test-web.build-test-results-tab&runId=16455494&resultId=177588)|dotnet/runtime#101277|
|[663551](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663551)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663551&view=ms.vss-test-web.build-test-results-tab&runId=16454850&resultId=175215)|dotnet/runtime#101473|
|[663503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663503)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663503&view=ms.vss-test-web.build-test-results-tab&runId=16453816&resultId=175476)|dotnet/runtime#101811|
|[663429](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663429)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663429&view=ms.vss-test-web.build-test-results-tab&runId=16451418&resultId=176635)|dotnet/runtime#101640|
|[663406](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663406)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663406&view=ms.vss-test-web.build-test-results-tab&runId=16450612&resultId=176034)|dotnet/runtime#101739|
|[663401](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663401)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663401&view=ms.vss-test-web.build-test-results-tab&runId=16450462&resultId=176916)|dotnet/runtime#101806|
|[663336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663336)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663336&view=ms.vss-test-web.build-test-results-tab&runId=16449186&resultId=172675)|dotnet/runtime#101762|
|[663287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663287)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663287&view=ms.vss-test-web.build-test-results-tab&runId=16447170&resultId=176755)|dotnet/runtime#101781|
|[663268](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663268)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663268&view=ms.vss-test-web.build-test-results-tab&runId=16446644&resultId=176817)|dotnet/runtime#101800|
|[663248](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663248)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663248&view=ms.vss-test-web.build-test-results-tab&runId=16446138&resultId=175143)|dotnet/runtime#101473|
|[663239](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663239)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663239&view=ms.vss-test-web.build-test-results-tab&runId=16445880&resultId=175684)|dotnet/runtime#101799|
|[663227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663227)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663227&view=ms.vss-test-web.build-test-results-tab&runId=16445756&resultId=173505)|dotnet/runtime#101798|
|[663222](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663222)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663222&view=ms.vss-test-web.build-test-results-tab&runId=16445410&resultId=175786)|dotnet/runtime#101797|
|[663200](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663200)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663200&view=ms.vss-test-web.build-test-results-tab&runId=16444738&resultId=175498)|dotnet/runtime#101624|
|[663177](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663177)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663177&view=ms.vss-test-web.build-test-results-tab&runId=16443792&resultId=177416)|dotnet/runtime#101792|
|[663164](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663164)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663164&view=ms.vss-test-web.build-test-results-tab&runId=16443558&resultId=183337)|dotnet/runtime#101640|
|[663151](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663151)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663151&view=ms.vss-test-web.build-test-results-tab&runId=16443212&resultId=181688)|dotnet/runtime#101763|
|[662930](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662930)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662930&view=ms.vss-test-web.build-test-results-tab&runId=16442780&resultId=174658)|dotnet/runtime#101761|
|[663140](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663140)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanScalarDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663140&view=ms.vss-test-web.build-test-results-tab&runId=16442668&resultId=177239)|dotnet/runtime#101716|
|[663068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663068)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663068&view=ms.vss-test-web.build-test-results-tab&runId=16441808&resultId=173296)|dotnet/runtime#101717|
|[663004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663004)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=663004&view=ms.vss-test-web.build-test-results-tab&runId=16438304&resultId=168454)|dotnet/runtime#101794|
|[662957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662957)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662957&view=ms.vss-test-web.build-test-results-tab&runId=16437750&resultId=182579)|dotnet/runtime#101762|
|[662949](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662949)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662949&view=ms.vss-test-web.build-test-results-tab&runId=16437566&resultId=175883)|dotnet/runtime#101767|
|[662907](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662907)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662907&view=ms.vss-test-web.build-test-results-tab&runId=16435280&resultId=178821)|dotnet/runtime#101792|
|[662886](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662886)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662886&view=ms.vss-test-web.build-test-results-tab&runId=16434960&resultId=175429)|dotnet/runtime#101791|
|[662816](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662816)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662816&view=ms.vss-test-web.build-test-results-tab&runId=16432776&resultId=176239)|dotnet/runtime#101789|
|[662790](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662790)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662790&view=ms.vss-test-web.build-test-results-tab&runId=16432118&resultId=179142)|dotnet/runtime#101739|
|[662716](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662716)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662716&view=ms.vss-test-web.build-test-results-tab&runId=16429270&resultId=171643)|dotnet/runtime#101473|
|[662625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662625)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662625&view=ms.vss-test-web.build-test-results-tab&runId=16428200&resultId=173904)|dotnet/runtime#101739|
|[662542](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662542)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662542&view=ms.vss-test-web.build-test-results-tab&runId=16427124&resultId=170773)|dotnet/runtime#101761|
|[662578](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662578)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662578&view=ms.vss-test-web.build-test-results-tab&runId=16426896&resultId=171333)|dotnet/runtime#101782|
|[662557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662557)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanScalarDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662557&view=ms.vss-test-web.build-test-results-tab&runId=16426446&resultId=169320)|dotnet/runtime#101580|
|[662312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662312)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662312&view=ms.vss-test-web.build-test-results-tab&runId=16423292&resultId=174958)|dotnet/runtime#99490|
|[662382](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662382)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662382&view=ms.vss-test-web.build-test-results-tab&runId=16422424&resultId=176924)|dotnet/runtime#99183|
|[662347](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662347)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662347&view=ms.vss-test-web.build-test-results-tab&runId=16420928&resultId=176112)|dotnet/runtime#101624|
|[662098](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662098)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662098&view=ms.vss-test-web.build-test-results-tab&runId=16419370&resultId=177859)|dotnet/runtime#95565|
|[662251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662251)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662251&view=ms.vss-test-web.build-test-results-tab&runId=16417308&resultId=175282)|dotnet/runtime#101613|
|[662225](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662225)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662225&view=ms.vss-test-web.build-test-results-tab&runId=16416980&resultId=176368)|dotnet/runtime#101151|
|[662209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662209)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662209&view=ms.vss-test-web.build-test-results-tab&runId=16416962&resultId=180710)|dotnet/runtime#99183|
|[662174](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662174)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662174&view=ms.vss-test-web.build-test-results-tab&runId=16416118&resultId=175879)|dotnet/runtime#101773|
|[662154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662154)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662154&view=ms.vss-test-web.build-test-results-tab&runId=16415774&resultId=178010)|dotnet/runtime#101277|
|[662142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662142)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanScalarDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662142&view=ms.vss-test-web.build-test-results-tab&runId=16415416&resultId=177843)|dotnet/runtime#100716|
|[661471](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661471)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661471&view=ms.vss-test-web.build-test-results-tab&runId=16414446&resultId=175561)|dotnet/runtime#101754|
|[662112](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662112)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662112&view=ms.vss-test-web.build-test-results-tab&runId=16414412&resultId=175364)|dotnet/runtime#101451|
|[662090](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662090)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662090&view=ms.vss-test-web.build-test-results-tab&runId=16414218&resultId=168084)|dotnet/runtime#101473|
|[662033](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662033)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=662033&view=ms.vss-test-web.build-test-results-tab&runId=16412948&resultId=176331)|dotnet/runtime#101767|
|[661923](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661923)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661923&view=ms.vss-test-web.build-test-results-tab&runId=16411752&resultId=175219)|dotnet/runtime#101151|
Displaying 100 of 161 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|47|164|164|

### LINKED ISSUE #101731: Test failure in System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues
Failed in [runtime-coreclr libraries-jitstress2-jitstressregs](https://dev.azure.com/dnceng-public/public/_build?definitionId=119&_a=summary)
- [20240429.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660140)
- [console log](https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-8bfb3cfe8cbf4b3ab3/System.Numerics.Tensors.Net8.Tests/1/console.50d9efb8.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-8bfb3cfe8cbf4b3ab3/System.Numerics.Tensors.Net8.Tests/1/console.50d9efb8.log?helixlogtype=result))

```
Stack Trace:
        /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitives.Generic.cs(444,0): at System.Numerics.Tensors.Tests.GenericFloatingPointNumberTensorPrimitivesTests`1.SpanDestinationFunctions_SpecialValues(SpanDestinationDelegate tensorPrimitivesMethod, Func`2 expectedMethod, Nullable`1 tolerance)
           at InvokeStub_GenericFloatingPointNumberTensorPrimitivesTests`1.SpanDestinationFunctions_SpecialValues(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    System.Numerics.Tensors.Net8.Tests
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "GenericFloatingPointNumberTensorPrimitivesTests`1.SpanDestinationFunctions_SpecialValues",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=660140
**Error message validated:** `[GenericFloatingPointNumberTensorPrimitivesTests`1.SpanDestinationFunctions_SpecialValues`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/1/2024 3:48:58 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[673838](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673838)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673838&view=ms.vss-test-web.build-test-results-tab&runId=16707954&resultId=182964)|dotnet/runtime#101089|
|[673835](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673835)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673835&view=ms.vss-test-web.build-test-results-tab&runId=16708250&resultId=205283)|dotnet/runtime#101089|
|[673791](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673791)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673791&view=ms.vss-test-web.build-test-results-tab&runId=16707218&resultId=203770)|dotnet/runtime#102071|
|[673764](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673764)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673764&view=ms.vss-test-web.build-test-results-tab&runId=16706982&resultId=207782)|dotnet/runtime#101796|
|[673751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673751)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673751&view=ms.vss-test-web.build-test-results-tab&runId=16706760&resultId=206188)|dotnet/runtime#102153|
|[673739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673739)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673739&view=ms.vss-test-web.build-test-results-tab&runId=16706652&resultId=205299)|dotnet/runtime#102094|
|[673732](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673732)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673732&view=ms.vss-test-web.build-test-results-tab&runId=16706254&resultId=208961)|dotnet/runtime#102073|
|[673659](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673659)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673659&view=ms.vss-test-web.build-test-results-tab&runId=16704286&resultId=197496)|dotnet/runtime#101801|
|[673625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673625)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673625&view=ms.vss-test-web.build-test-results-tab&runId=16703986&resultId=200222)|dotnet/runtime#100141|
|[673533](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673533)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673533&view=ms.vss-test-web.build-test-results-tab&runId=16703248&resultId=183477)|dotnet/runtime#101717|
|[673376](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673376)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673376&view=ms.vss-test-web.build-test-results-tab&runId=16697094&resultId=200325)|dotnet/runtime#102133|
|[673360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673360)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673360&view=ms.vss-test-web.build-test-results-tab&runId=16696480&resultId=207112)|dotnet/runtime#102076|
|[2449946](https://dev.azure.com/dnceng/internal/_build/results?buildId=2449946)|dotnet-runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng//internal/_build/results?buildId=2449946&view=ms.vss-test-web.build-test-results-tab&runId=53594395&resultId=174302)||
|[673323](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673323)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673323&view=ms.vss-test-web.build-test-results-tab&runId=16694744&resultId=207588)|dotnet/runtime#102146|
|[673321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673321)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673321&view=ms.vss-test-web.build-test-results-tab&runId=16693800&resultId=181007)||
|[673269](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673269)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673269&view=ms.vss-test-web.build-test-results-tab&runId=16691464&resultId=209338)|dotnet/runtime#102139|
|[673259](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673259)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673259&view=ms.vss-test-web.build-test-results-tab&runId=16691458&resultId=205508)|dotnet/runtime#101938|
|[673175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673175)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673175&view=ms.vss-test-web.build-test-results-tab&runId=16687716&resultId=209192)|dotnet/runtime#102139|
|[2449760](https://dev.azure.com/dnceng/internal/_build/results?buildId=2449760)|dotnet-runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng//internal/_build/results?buildId=2449760&view=ms.vss-test-web.build-test-results-tab&runId=53592561&resultId=199578)||
|[673149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673149)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673149&view=ms.vss-test-web.build-test-results-tab&runId=16686954&resultId=194490)||
|[673144](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673144)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673144&view=ms.vss-test-web.build-test-results-tab&runId=16686800&resultId=205299)|dotnet/runtime#102094|
|[673122](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673122)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673122&view=ms.vss-test-web.build-test-results-tab&runId=16686368&resultId=199325)|dotnet/runtime#102103|
|[673116](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673116)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673116&view=ms.vss-test-web.build-test-results-tab&runId=16686310&resultId=204105)|dotnet/runtime#102132|
|[673112](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673112)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673112&view=ms.vss-test-web.build-test-results-tab&runId=16686306&resultId=208040)|dotnet/runtime#102117|
|[2449738](https://dev.azure.com/dnceng/internal/_build/results?buildId=2449738)|dotnet-runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng//internal/_build/results?buildId=2449738&view=ms.vss-test-web.build-test-results-tab&runId=53592463&resultId=175597)||
|[673059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673059)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673059&view=ms.vss-test-web.build-test-results-tab&runId=16685202&resultId=198908)|dotnet/runtime#102133|
|[673035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673035)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673035&view=ms.vss-test-web.build-test-results-tab&runId=16685016&resultId=197498)|dotnet/runtime#102129|
|[672997](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672997)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672997&view=ms.vss-test-web.build-test-results-tab&runId=16684506&resultId=204191)|dotnet/runtime#102132|
|[672936](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672936)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672936&view=ms.vss-test-web.build-test-results-tab&runId=16684042&resultId=203198)|dotnet/runtime#101977|
|[672919](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672919)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672919&view=ms.vss-test-web.build-test-results-tab&runId=16683834&resultId=197467)|dotnet/runtime#101975|
|[672901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672901)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672901&view=ms.vss-test-web.build-test-results-tab&runId=16683120&resultId=199772)|dotnet/runtime#102126|
|[672831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672831)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672831&view=ms.vss-test-web.build-test-results-tab&runId=16680190&resultId=187156)||
|[672823](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672823)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672823&view=ms.vss-test-web.build-test-results-tab&runId=16680148&resultId=199803)|dotnet/runtime#102103|
|[672709](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672709)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672709&view=ms.vss-test-web.build-test-results-tab&runId=16679038&resultId=206658)|dotnet/runtime#102084|
|[672661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672661)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672661&view=ms.vss-test-web.build-test-results-tab&runId=16678984&resultId=207811)|dotnet/runtime#102115|
|[672788](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672788)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672788&view=ms.vss-test-web.build-test-results-tab&runId=16678962&resultId=197496)|dotnet/runtime#102126|
|[672783](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672783)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672783&view=ms.vss-test-web.build-test-results-tab&runId=16678908&resultId=197982)|dotnet/runtime#102059|
|[672395](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672395)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672395&view=ms.vss-test-web.build-test-results-tab&runId=16671074&resultId=197621)|dotnet/runtime#102101|
|[672392](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672392)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672392&view=ms.vss-test-web.build-test-results-tab&runId=16671042&resultId=197496)|dotnet/runtime#102101|
|[672246](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672246)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672246&view=ms.vss-test-web.build-test-results-tab&runId=16668868&resultId=197273)|dotnet/runtime#102104|
|[672212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672212)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672212&view=ms.vss-test-web.build-test-results-tab&runId=16668146&resultId=173999)|dotnet/runtime#101580|
|[672195](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672195)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672195&view=ms.vss-test-web.build-test-results-tab&runId=16667862&resultId=206218)|dotnet/runtime#101938|
|[672189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672189)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672189&view=ms.vss-test-web.build-test-results-tab&runId=16667780&resultId=195904)|dotnet/runtime#101938|
|[672168](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672168)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672168&view=ms.vss-test-web.build-test-results-tab&runId=16667476&resultId=207112)|dotnet/runtime#102059|
|[672162](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672162)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672162&view=ms.vss-test-web.build-test-results-tab&runId=16667364&resultId=194382)|dotnet/runtime#101652|
|[672137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672137)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672137&view=ms.vss-test-web.build-test-results-tab&runId=16667136&resultId=199578)|dotnet/runtime#102098|
|[672029](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672029)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672029&view=ms.vss-test-web.build-test-results-tab&runId=16665578&resultId=207588)|dotnet/runtime#102084|
|[671966](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671966)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671966&view=ms.vss-test-web.build-test-results-tab&runId=16664378&resultId=198683)|dotnet/runtime#101994|
|[671945](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671945)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671945&view=ms.vss-test-web.build-test-results-tab&runId=16663800&resultId=196454)|dotnet/runtime#102007|
|[671929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671929)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671929&view=ms.vss-test-web.build-test-results-tab&runId=16662278&resultId=195266)||
|[671855](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671855)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671855&view=ms.vss-test-web.build-test-results-tab&runId=16659340&resultId=172230)|dotnet/runtime#101580|
|[671775](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671775)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671775&view=ms.vss-test-web.build-test-results-tab&runId=16657130&resultId=197273)|dotnet/runtime#102089|
|[671766](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671766)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671766&view=ms.vss-test-web.build-test-results-tab&runId=16656334&resultId=198171)|dotnet/runtime#101938|
|[671694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671694)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671694&view=ms.vss-test-web.build-test-results-tab&runId=16654854&resultId=197496)|dotnet/runtime#85694|
|[671685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671685)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671685&view=ms.vss-test-web.build-test-results-tab&runId=16654766&resultId=207588)|dotnet/runtime#101994|
|[671671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671671)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671671&view=ms.vss-test-web.build-test-results-tab&runId=16654444&resultId=198624)|dotnet/runtime#101950|
|[671627](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671627)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671627&view=ms.vss-test-web.build-test-results-tab&runId=16653424&resultId=207936)|dotnet/runtime#101683|
|[671606](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671606)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671606&view=ms.vss-test-web.build-test-results-tab&runId=16652644&resultId=201148)|dotnet/runtime#102074|
|[671571](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671571)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671571&view=ms.vss-test-web.build-test-results-tab&runId=16652180&resultId=199576)|dotnet/runtime#101976|
|[671557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671557)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671557&view=ms.vss-test-web.build-test-results-tab&runId=16652136&resultId=207813)|dotnet/runtime#101295|
|[671510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671510)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671510&view=ms.vss-test-web.build-test-results-tab&runId=16651824&resultId=206628)|dotnet/runtime#102076|
|[671494](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671494)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671494&view=ms.vss-test-web.build-test-results-tab&runId=16651726&resultId=206277)|dotnet/runtime#101717|
|[671452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671452)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671452&view=ms.vss-test-web.build-test-results-tab&runId=16651108&resultId=198879)|dotnet/runtime#101975|
|[671428](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671428)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671428&view=ms.vss-test-web.build-test-results-tab&runId=16649316&resultId=208453)|dotnet/runtime#102024|
|[671436](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671436)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671436&view=ms.vss-test-web.build-test-results-tab&runId=16649986&resultId=186221)|dotnet/runtime#101801|
|[671306](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671306)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671306&view=ms.vss-test-web.build-test-results-tab&runId=16645900&resultId=199325)||
|[671274](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671274)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671274&view=ms.vss-test-web.build-test-results-tab&runId=16645038&resultId=205508)|dotnet/runtime#101938|
|[671231](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671231)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671231&view=ms.vss-test-web.build-test-results-tab&runId=16643984&resultId=199578)|dotnet/runtime#102007|
|[671217](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671217)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671217&view=ms.vss-test-web.build-test-results-tab&runId=16643408&resultId=200986)|dotnet/runtime#101994|
|[671098](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671098)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671098&view=ms.vss-test-web.build-test-results-tab&runId=16639142&resultId=198879)|dotnet/runtime#101701|
|[671020](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671020)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=671020&view=ms.vss-test-web.build-test-results-tab&runId=16637896&resultId=183939)|dotnet/runtime#102062|
|[670921](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670921)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670921&view=ms.vss-test-web.build-test-results-tab&runId=16636212&resultId=201403)|dotnet/runtime#102058|
|[670861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670861)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670861&view=ms.vss-test-web.build-test-results-tab&runId=16634936&resultId=199098)|dotnet/runtime#101938|
|[670895](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670895)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670895&view=ms.vss-test-web.build-test-results-tab&runId=16634292&resultId=191167)||
|[670824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670824)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670824&view=ms.vss-test-web.build-test-results-tab&runId=16633938&resultId=174931)|dotnet/runtime#101580|
|[670810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670810)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670810&view=ms.vss-test-web.build-test-results-tab&runId=16632678&resultId=188777)||
|[670746](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670746)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670746&view=ms.vss-test-web.build-test-results-tab&runId=16631606&resultId=186228)|dotnet/runtime#102054|
|[670704](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670704)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670704&view=ms.vss-test-web.build-test-results-tab&runId=16630982&resultId=202024)|dotnet/runtime#100745|
|[670675](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670675)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670675&view=ms.vss-test-web.build-test-results-tab&runId=16630194&resultId=205514)|dotnet/runtime#102036|
|[670627](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670627)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670627&view=ms.vss-test-web.build-test-results-tab&runId=16629316&resultId=199100)|dotnet/runtime#101938|
|[670590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670590)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670590&view=ms.vss-test-web.build-test-results-tab&runId=16627852&resultId=182236)|dotnet/runtime#101801|
|[665989](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665989)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=665989&view=ms.vss-test-web.build-test-results-tab&runId=16626592&resultId=198427)|dotnet/runtime#101848|
|[670466](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670466)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670466&view=ms.vss-test-web.build-test-results-tab&runId=16625456&resultId=199770)|dotnet/runtime#101796|
|[670463](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670463)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670463&view=ms.vss-test-web.build-test-results-tab&runId=16625414&resultId=201403)|dotnet/runtime#101976|
|[670443](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670443)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670443&view=ms.vss-test-web.build-test-results-tab&runId=16624750&resultId=201181)|dotnet/runtime#101801|
|[670387](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670387)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670387&view=ms.vss-test-web.build-test-results-tab&runId=16622450&resultId=188189)|dotnet/runtime#101620|
|[670311](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670311)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670311&view=ms.vss-test-web.build-test-results-tab&runId=16619596&resultId=197271)|dotnet/runtime#100266|
|[670269](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670269)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670269&view=ms.vss-test-web.build-test-results-tab&runId=16618690&resultId=197688)|dotnet/runtime#102041|
|[670263](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670263)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670263&view=ms.vss-test-web.build-test-results-tab&runId=16618260&resultId=194547)||
|[670214](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670214)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670214&view=ms.vss-test-web.build-test-results-tab&runId=16617340&resultId=205883)|dotnet/runtime#101938|
|[670169](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670169)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670169&view=ms.vss-test-web.build-test-results-tab&runId=16616256&resultId=200569)|dotnet/runtime#98127|
|[670074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670074)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670074&view=ms.vss-test-web.build-test-results-tab&runId=16614226&resultId=208128)|dotnet/runtime#101886|
|[670041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670041)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670041&view=ms.vss-test-web.build-test-results-tab&runId=16612572&resultId=197496)|dotnet/runtime#101994|
|[670017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670017)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=670017&view=ms.vss-test-web.build-test-results-tab&runId=16612470&resultId=207586)|dotnet/runtime#102036|
|[669967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669967)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669967&view=ms.vss-test-web.build-test-results-tab&runId=16611798&resultId=199770)|dotnet/runtime#102035|
|[669961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669961)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669961&view=ms.vss-test-web.build-test-results-tab&runId=16611664&resultId=176484)|dotnet/runtime#102034|
|[669779](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669779)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669779&view=ms.vss-test-web.build-test-results-tab&runId=16611034&resultId=201626)|dotnet/runtime#101886|
|[669929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669929)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669929&view=ms.vss-test-web.build-test-results-tab&runId=16610942&resultId=201181)|dotnet/runtime#100823|
|[669901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669901)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669901&view=ms.vss-test-web.build-test-results-tab&runId=16610680&resultId=172674)|dotnet/runtime#101580|
|[669854](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669854)|dotnet/runtime|[System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues](https://dev.azure.com/dnceng-public/public/_build/results?buildId=669854&view=ms.vss-test-web.build-test-results-tab&runId=16609830&resultId=182178)|dotnet/runtime#102003|
Displaying 100 of 211 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|24|148|211|

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #98732, resolves #101721, and resolves #101731

The general issue was that the `TensorPrimitives` APIs used AVX512 or SSE, depending on availability while the scalar APIs only used SSE. -- This was not reproducing everywhere as it only reproduces on AVX512 capable hardware, which not all CI machines are.

There is a subtle difference between the handling of denormalized values between the AVX512 and SSE instructions where AVX512 treats them negatives while SSE treats them as flushed to zero, which in turn causes a difference in result. This difference is fine and expected since this is explicitly an `Estimate` API and doesn't impact calls within a single process.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
> This resolves https://github.com/dotnet/runtime/issues/98732, resolves https://github.com/dotnet/runtime/issues/101721, and resolves https://github.com/dotnet/runtime/issues/101731

Some of the failures linked in those issues were for other than the reciprocals, e.g.
```
    System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanSpanDestination_SpecialValues(tensorPrimitivesMethod: SpanSpanDestinationDelegate { Method = Void MaxNumber[Single](System.ReadOnlySpan`1[System.Single], System.ReadOnlySpan`1[System.Single], System.Span`1[System.Single]), Target = null }, expectedMethod: Func`3 { Method = Single MaxNumber(Single, Single), Target = null }, tolerance: null) [FAIL]
      Assert.All() Failure: 253 out of 256 items in the collection did not pass.
      [3]:   Item:  4
             Error: Assert.All() Failure: 18 out of 24 items in the collection did not pass.
                    [3]:  Item:  NaN
                          Error: Assert.Equal() Failure: Values differ
                                 Expected: 0.112421386
                                 Actual:   NaN
...
```
so this might not fully resolve it.

File: src/coreclr/jit/importercalls.cpp [hunk 1]
```diff
@@ -8730,6 +8743,121 @@ void Compiler::impCheckCanInline(GenTreeCall*           call,
...
+// Arguments:
+//   method        - The handle of the method being imported
+//   callType      - The underlying type for the call
+//   intrinsicName - The intrinsic being imported
+//   tailCall      - true if the method is a tail call; otherwise false
+//   isMax         - true if the intrinsic computes the max; false for the min
+//   isMagnitude   - true if the intrinsic compares using the absolute value of the inputs
+//   isNumber      - true if the intrinsic propagates the number; false for NaN
+//
+GenTree* Compiler::impEstimateIntrinsic(CORINFO_METHOD_HANDLE method,
```
Comment (tannergooding) [inline src/coreclr/jit/importercalls.cpp:8758]: CC. @dotnet/jit-contrib, this did end up being a runtime issue of sorts.

There's a general assumption made by R2R that the managed implementation (for Corelib in particular) will be consistent across all paths. That was strictly not the case for the `*Estimate` APIs where they are non-deterministic across hardware by design. -- Put another way, `R2R` essentially assumes that `Isa.IsSupported` is equivalent to `compOpportunisticallyDependsOn(Isa)` for corelib, but it assumes its equivalent to `compExactlyDependsOn(Isa)` for other libraries.

As such, the only fix we have today is to move it into the JIT where we can explicitly use `compExactlyDependsOn(Isa)` instead and force things to be annotated correctly. This has a minor added bonus in that it improves codegen around the method slightly for more complex scenarios and makes it more consistent with the handling of other math APIs.

Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp:8766]: Can it be solved via ExactlyDependsOn attributes on C# side?

Comment (tannergooding) [reply src/coreclr/jit/importercalls.cpp:8766]: Not from what I saw. The analyzer will actually warn in the case that you try to do something like that, because of the expectation that the paths are semantically equivalent.

It's detailed more in depth here with some explanations of what is safe vs not safe for corelib: https://github.com/dotnet/runtime/blob/40c024f69ab1c39982c043277e2bb90d2e510a24/docs/design/coreclr/botr/vectors-and-intrinsics.md?plain=1#L67

Doing it in the JIT, which is how all the other APIs that map down to 1 instruction are handled, ended up being the simpler approach.

File: src/coreclr/jit/importercalls.cpp [hunk 2]
```diff
@@ -8730,6 +8751,120 @@ void Compiler::impCheckCanInline(GenTreeCall*           call,
...
+// impMinMaxIntrinsic: Imports a min or max intrinsic
+//
+// Arguments:
+//   method        - The handle of the method being imported
+//   callType      - The underlying type for the call
+//   intrinsicName - The intrinsic being imported
+//   tailCall      - true if the method is a tail call; otherwise false
+//   isMax         - true if the intrinsic computes the max; false for the min
+//   isMagnitude   - true if the intrinsic compares using the absolute value of the inputs
+//   isNumber      - true if the intrinsic propagates the number; false for NaN
```
Comment (EgorBo) [inline src/coreclr/jit/importercalls.cpp:8764]: the comments seem to be stale, also nit: Return Value:

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/importercalls.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp:8766]: @tannergooding so does this PR solve the non-determinism? R2R still may prejit functions with these math functions, right?

Comment (tannergooding) [reply src/coreclr/jit/importercalls.cpp:8766]: > so does this PR solve the non-determinism

No, the non-determinism is intentional for these APIs. They are explicitly `estimating` APIs that are allowed to differ in result based on the hardware they're running on.

> R2R still may prejit functions with these math functions, right?

The use of `compExactlyDependsOn` basically tells R2R that this method requires `Avx512F` and if it isn't present the functionality may differ. That will mark methods that call it as requiring themselves to be jitted.

If we made these `recursive` and therefore `mustExpand`, then R2R could leave a call to the method and only have the method jitted instead. But, that's a more complicated change since `ReciprocalSqrtEstimate` requires us to emit a call to `System.Math.Sqrt` in the worst case and requires adding handling for that to platforms that don't currently have hardware intrinsic support (like Arm32).

This is a relatively uncommon API (basically just used in specialized high-perf scenarios), so fixing the failing CI legs seemed more important than worrying about the handful of APIs that would be disqualified from R2R.

File: src/coreclr/jit/importercalls.cpp (hunk 2 above)
Comment (tannergooding) [reply src/coreclr/jit/importercalls.cpp]: Fixed.

**Comment by EgorBo** [comment]
Improvements on arm64:

- https://github.com/dotnet/perf-autofiling-issues/issues/34055
