### PR TITLE
[RuntimeAsync] Fix Await pattern detection for ValueTask in ConfigureAwait cases.

### LINKED ISSUE #119617: [RuntimeAsync] ConfigureAwait(bool) is not optimized for ValueTask-returning method.
Observed while enabling rt async in Libraires partition - https://github.com/dotnet/runtime/pull/119432

While the optimization should not be needed for correctness, thus not the first priority to fix, it is certainly not the intention to leave this unoptimized.

The reason why we do not recognize the await pattern in `Await(call).ConfigureAwait(false)` when call returns ValueTask is because we expect `ConfigureAwait` applied to the result, but the IL contains `stloc;ldloca` in between. 

The importer (`impMatchTaskAwaitPattern`) needs to learn about this.

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #119617

Since ValueTask is a struct, we need to see through `stloc; ldloca;` sequence when matching `ConfigureAwait` call

### CODE REVIEW

File: src/coreclr/inc/clrconfigvalues.h [hunk 1]
```diff
@@ -715,7 +715,7 @@ RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableRiscV64Zbb,             W("EnableRiscV64
 #endif
 
 // Runtime-async
-RETAIL_CONFIG_DWORD_INFO(UNSUPPORTED_RuntimeAsync, W("RuntimeAsync"), 0, "Enables runtime async method support")
+RETAIL_CONFIG_DWORD_INFO(UNSUPPORTED_RuntimeAsync, W("RuntimeAsync"), 1, "Enables runtime async method support")
```
Comment (VSadov) [inline src/coreclr/inc/clrconfigvalues.h]: TODO: before merging remove the commit that enables async feature/tests

File: src/coreclr/jit/importer.cpp [hunk 2]
```diff
@@ -6011,11 +6019,75 @@ bool Compiler::impMatchTaskAwaitPattern(const BYTE* codeAddr, const BYTE* codeEn
...
+                    break;
+                case CEE_LDLOCA:
+                    ldlocaNum = getU2LittleEndian(nextTmp);
+                    nextTmp += 2;
+                    break;
+            }
+
+            // no ldloca or locals did not match, this can't be await pattern
+            if (stlocNum != ldlocaNum)
+                return NULL;
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp]:
```suggestion
                return nullptr;
```

File: src/coreclr/jit/importer.cpp [hunk 3]
```diff
@@ -6011,11 +6019,75 @@ bool Compiler::impMatchTaskAwaitPattern(const BYTE* codeAddr, const BYTE* codeEn
...
+
+            // locals match, but no space for ConfigureAwait call, this can't be await pattern
+            if (nextTmp + 2 * (1 + sizeof(mdToken)) >= codeEndp)
+                return NULL;
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp]:
```suggestion
                return nullptr;
```

File: src/coreclr/jit/importer.cpp [hunk 4]
```diff
@@ -6011,11 +6019,75 @@ bool Compiler::impMatchTaskAwaitPattern(const BYTE* codeAddr, const BYTE* codeEn
...
+
         uint8_t nextOp     = getU1LittleEndian(nextOpcode);
         uint8_t nextNextOp = getU1LittleEndian(nextOpcode + 1);
         if ((nextOp != CEE_LDC_I4_0 && nextOp != CEE_LDC_I4_1) ||
             (nextNextOp != CEE_CALL && nextNextOp != CEE_CALLVIRT))
         {
+            if (stlocNum != -1)
+            {
+                // we had stloc/ldloca, we must see ConfigAwait
+                return NULL;
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp]:
```suggestion
                return nullptr;
```

File: src/coreclr/jit/importer.cpp [hunk 5]
```diff
@@ -6026,6 +6098,12 @@ bool Compiler::impMatchTaskAwaitPattern(const BYTE* codeAddr, const BYTE* codeEn
         if (!eeIsIntrinsic(nextCallTok.hMethod) ||
             lookupNamedIntrinsic(nextCallTok.hMethod) != NI_System_Threading_Tasks_Task_ConfigureAwait)
         {
+            if (stlocNum != -1)
+            {
+                // we had stloc/ldloca, we must see ConfigAwait
+                return NULL;
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp]:
```suggestion
                return nullptr;
```

Comment (jakobbotsch) [reply src/coreclr/jit/importer.cpp]: Also a few below this.

**Review by jakobbotsch — APPROVED** [review]
LGTM except the nits about `nullptr` vs `NULL`

**Comment by hez2010** [comment]
Wondering whether such optimization can be done in VN as well instead of the importer only so that it can capture more patterns that are not awaiting the Task/ValueTask{.ConfigureAwait()} directly?
For example,
```cs
var t = FooAsync();
Bar();
await t.ConfigureAwait(false);
```

**Comment by jakobbotsch** [comment]
> Wondering whether such optimization can be done in VN as well instead of the importer only so that it can capture more patterns that are not awaiting the Task/ValueTask{.ConfigureAwait()} directly? For example,
> 
> ```cs
> var t = FooAsync();
> Bar();
> await t.ConfigureAwait(false);
> ```

It would not help your case. There is no way to call the async version of `FooAsync` without waiting for its completion, which is not the semantics of this program that runs `Bar` after starting `FooAsync`.

We may still do an optimization like this in the future of we find that some cases we aren't getting (perhaps after inlining). But it is not so simple because currently finding the async variant of a method requires token information, and we do not keep token information around. We will either need to do that or only do the optimization for statically resolvable calls.

**Comment by VSadov** [comment]
GCC complained that CEE_STLOC and CEE_LDLOCA are out of range of the switch value (uint8_t). I think GCC is right about this. These are wide opcodes.
