### PR TITLE
[mono] Fix `LLVMArgWasmVtypeAsScalar` when a method doesn't set its return value

### LINKED ISSUE #101104: [browser] Wasm linux/windows HighResource LibrariestTests AOT are failing on build
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=644416
Build error leg or test failing: Build product
Failing jobs on `runtime-extra-platforms`:
- `browser-wasm windows Release LibraryTests_HighResource_AOT`
- `browser-wasm linux Release LibraryTests_HighResource_AOT`

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "Assertion at .*mini-llvm\\.c:6194, condition `lhs' not met",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=644416
**Error message validated:** `[Assertion at .*mini-llvm\.c:6194, condition `lhs' not met`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/16/2024 6:29:40 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[651298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=651298)|dotnet/runtime|[WasmTestOnChrome-System.Reflection.MetadataLoadContext.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=651298&view=ms.vss-test-web.build-test-results-tab&runId=16102506&resultId=169823)||
|[649141](https://dev.azure.com/dnceng-public/public/_build/results?buildId=649141)|dotnet/runtime|[WasmTestOnChrome-System.Reflection.MetadataLoadContext.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=649141&view=ms.vss-test-web.build-test-results-tab&runId=16045806&resultId=169793)||
|[644416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644416)|dotnet/runtime|[normal-System.Reflection.MetadataLoadContext.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644416&view=ms.vss-test-web.build-test-results-tab&runId=15898504&resultId=164499)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|2|3|

### PR DESCRIPTION
**Pull request by kotlarmilos**
## Description

This PR should fix an assertion in cases when a method doesn't set its return value. Additionally, it should fix trimming-related issues introduced in https://github.com/dotnet/runtime/issues/101104#issuecomment-2069238760. 

Fixes https://github.com/dotnet/runtime/issues/101104

### CODE REVIEW

File: src/mono/mono/mini/mini-llvm.c [hunk 1]
```diff
@@ -6189,11 +6189,11 @@ process_bb (EmitContext *ctx, MonoBasicBlock *bb)
 					}
 					break;
 				case LLVMArgWasmVtypeAsScalar:
-					if (!addresses [ins->sreg1]) {
+					if (!addresses [ins->sreg1] && lhs) {
```
Comment (radekdoulik) [inline src/mono/mono/mini/mini-llvm.c:6192]: Shouldn't this case, when the methods just throw, be handled here? https://github.com/dotnet/runtime/pull/101299/files#diff-cc4f4d3a653b6ac0bc4a6a001e4f0321e94ce51cc16ec85dc18675d1f8976365R6124-R6131

Comment (kotlarmilos) [reply src/mono/mono/mini/mini-llvm.c:6192]: You are right, but the condition seems te be false in case of `LLVMArgWasmVtypeAsScalar` due to `src_in_reg=FALSE` in:
```c
if (src_in_reg && (!lhs || ctx->is_dead [ins->sreg1])) {
```

Do you think that we should update `case LLVMArgNormal: src_in_reg = TRUE; break;` to include `LLVMArgWasmVtypeAsScalar`?

Comment (radekdoulik) [reply src/mono/mono/mini/mini-llvm.c:6192]: I think we should handle it similar to `LLVMArgVtypeAsScalar`, see my commit. (github didn't want me to allow to commit it as suggestion, so I committed it directly)

Then the rest of the changes should not be needed.

Comment (kotlarmilos) [reply src/mono/mono/mini/mini-llvm.c]: Thanks for help!

File: src/mono/mono/mini/mini-llvm.c [hunk 2]
```diff
@@ -6119,7 +6119,7 @@ process_bb (EmitContext *ctx, MonoBasicBlock *bb)
 				gboolean is_simd = mini_class_is_simd (ctx->cfg, mono_class_from_mono_type_internal (sig->ret));
 				switch (linfo->ret.storage) {
 				case LLVMArgNormal: src_in_reg = TRUE; break;
-				case LLVMArgVtypeInReg: case LLVMArgVtypeAsScalar: src_in_reg = is_simd; break;
+				case LLVMArgVtypeInReg: case LLVMArgVtypeAsScalar: case LLVMArgWasmVtypeAsScalar: src_in_reg = is_simd; break;
```
Comment (lambdageek) [inline src/mono/mono/mini/mini-llvm.c:6122]:
```suggestion
				case LLVMArgVtypeInReg:
				case LLVMArgVtypeAsScalar:
				case LLVMArgWasmVtypeAsScalar:
					src_in_reg = is_simd;
					break;
```

follow-up idea: this function with a ton of nested switch statements is hard to think about.  Let's make helper methods.

Comment (kotlarmilos) [reply src/mono/mono/mini/mini-llvm.c]: https://github.com/dotnet/runtime/issues/101412

**Comment by kotlarmilos** [comment]
According to the build analysis, the failures are known and shouldn't be related. The wasm-extra-platforms failures seem to be the same as in https://dev.azure.com/dnceng-public/public/_build?definitionId=151&_a=summary.

I've created a tracking issue: https://github.com/dotnet/runtime/issues/101482

**Review by radekdoulik — APPROVED** [review]
