### PR TITLE
Fix arm64 MacOS and Linux Managed Debugging

### LINKED ISSUE #104816: ICorDebugRegisterSet.GetThreadContext fails on macOS arm64
### Description

In .NET 9 preview 7 builds, ICorDebugRegisterSet.GetThreadContext is failing on macOS arm64 with HRESULT_FROM_WIN32(ERROR_INSUFFICIENT_BUFFER) (-2147024774). 

### Reproduction Steps

1. Install latest .NET
2. Create a console application
3. Open the folder in VS Code
4. Set a breakpoint on the Console.WriteLine line
5. Run

### Expected behavior

Debugger should successfully produce a call stack

### Actual behavior

Debugger fails to produce a call stack when the breakpoint is hit

### Regression?

Regression from preview 6

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mikelle-rogers**
A recent change to the size of T_CONTEXT broke managed debugging. This adds ARM64 to a check for the extended register state to unblock managed debugging. Fixes #104816

### CODE REVIEW

**Review by tommcdon — APPROVED** [review]
LGTM, thank you!!

**Review by tommcdon — CHANGES_REQUESTED** [review]
Actually, there seems to be a linux build failure that needs to be fixed

File: src/coreclr/debug/inc/common.h [hunk 1]
```diff
@@ -92,12 +92,14 @@ ULONG32 ContextSizeForFlags(ULONG32 flags)
...
     {
-#if !defined(CROSS_COMPILE) && !defined(TARGET_WINDOWS) && defined(TARGET_AMD64)
+#if !defined(CROSS_COMPILE) && !defined(TARGET_WINDOWS)
+    #if defined(TARGET_AMD64) || defined(TARGET_ARM64)
         if ((flags & CONTEXT_XSTATE) == CONTEXT_XSTATE)
         {
             return sizeof(T_CONTEXT);
         }
         return offsetof(T_CONTEXT, XStateFeaturesMask);
+    #endif
```
Comment (tommcdon) [inline src/coreclr/debug/inc/common.h:102]:
```c++
#if !defined(CROSS_COMPILE) && !defined(TARGET_WINDOWS) && (defined(TARGET_AMD64) || defined(TARGET_ARM64))
         if ((flags & CONTEXT_XSTATE) == CONTEXT_XSTATE)
         {
             return sizeof(T_CONTEXT);
         }
         return offsetof(T_CONTEXT, XStateFeaturesMask);
```

Comment (mikelle-rogers) [reply src/coreclr/debug/inc/common.h]: Yep, that's what I did!

**Review by tommcdon — APPROVED** [review]
