### PR TITLE
Fix race condition in WASM crypto worker

### LINKED ISSUE #69806: Test failures in hashing on Browser
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69668-merge-9dd411182c95433daa/WasmTestOnBrowser-System.Security.Cryptography.Tests/1/console.fdc2faf5.log?helixlogtype=result

```
[08:20:42] info: Starting:    System.Security.Cryptography.Tests.dll
[08:20:46] fail: [FAIL] System.Security.Cryptography.Tests.Sha1ManagedTests.Sha1_Rfc3174_3_Async
[08:20:46] info: Showing first 10 differences
[08:20:46] info:   Position 0: Expected: 52, Actual: 217
[08:20:46] info:   Position 1: Expected: 170, Actual: 73
[08:20:46] info:   Position 2: Expected: 151, Actual: 231
[08:20:46] info:   Position 3: Expected: 60, Actual: 108
[08:20:46] info:   Position 4: Expected: 212, Actual: 115
[08:20:46] info:   Position 5: Expected: 196, Actual: 7
[08:20:46] info:   Position 6: Expected: 218, Actual: 236
[08:20:46] info:   Position 7: Expected: 164, Actual: 195
[08:20:46] info:   Position 8: Expected: 246, Actual: 62
[08:20:46] info:   Position 9: Expected: 30, Actual: 42
[08:20:46] info: Total number of differences: 20 out of 20
[08:20:46] info:    at System.AssertExtensions.SequenceEqual[Byte](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual)
[08:20:46] info:    at System.AssertExtensions.SequenceEqual[Byte](Span`1 expected, Span`1 actual)
[08:20:46] info:    at System.Security.Cryptography.Tests.HashAlgorithmTestDriver.VerifyOneShotStreamAsync(Stream input, String output)
[08:20:46] info:    at System.Security.Cryptography.Tests.HashAlgorithmTestDriver.VerifyRepeatingAsync(String input, Int32 repeatCount, String output)
[08:20:46] info:    at System.Security.Cryptography.Tests.Sha1Tests.Sha1_Rfc3174_3_Async()
[08:20:46] info: --- End of stack trace from previous location ---
[08:21:07] info: Finished:    System.Security.Cryptography.Tests.dll
[08:21:07] info: 
[08:21:07] info: === TEST EXECUTION SUMMARY ===
[08:21:07] info: Total: 1163, Errors: 0, Failed: 1, Skipped: 1, Time: 24.820985s
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69786-merge-4202b33d23d54c99bd/WasmTestOnBrowser-System.Security.Cryptography.Tests/1/console.99f7714c.log?helixlogtype=result

```
[10:47:51] info: Starting:    System.Security.Cryptography.Tests.dll
[10:47:55] fail: [FAIL] System.Security.Cryptography.Tests.Sha256Tests.Sha256_Fips180_3
[10:47:55] info: Assert.Equal() Failure
[10:47:55] info:            ↓ (pos 0)
[10:47:55] info: Expected: [205, 199, 110, 92, 153, ...]
[10:47:55] info: Actual:   [156, 156, 59, 215, 224, ...]
[10:47:55] info:            ↑ (pos 0)
[10:47:55] info:    at System.Security.Cryptography.Tests.HashAlgorithmTestDriver.VerifyOneShotAllocatingStream(Stream input, String output)
[10:47:55] info:    at System.Security.Cryptography.Tests.HashAlgorithmTestDriver.VerifyRepeating(String input, Int32 repeatCount, String output)
[10:47:55] info:    at System.Security.Cryptography.Tests.Sha256Tests.Sha256_Fips180_3()
[10:47:55] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[10:48:00] fail: [out of order message from the browser]: http://127.0.0.1:35197/dotnet.js 2:70309 Uncaught
[11:02:46] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
/datadisks/disk1/work/A6E90937/w/A157086B/e /datadisks/disk1/work/A6E90937/w/A157086B/e
----- end Wed May 25 11:02:46 UTC 2022 ----- exit code 71 ----------------------------------------------------------
```

Both of these tests are testing the hash of one million ASCII lowercase a characters.

Having run through hashes of `{}`, `{'a'}`, `{'a', 'a'}`, all the way up to 5 million, for both SHA-1 and SHA-2-256, I can't reproduce either of these error values.

It seems like, somehow, bad data got into the pipeline... it's not a case of too much, or too little.

Also noteworthy is that each of these failed in the allocating one-shots over streams (`public static byte[] HashData(Stream)`, and the async variant), after successfully doing it via other methods.

### PR DESCRIPTION
**Pull request by eerhardt**
When sending a message between LibraryChannel and ChannelWorker, there is a race condition where both threads are reading/writing to shared memory at the same time. This can cause message pages to be skipped.

To fix this, add a shared mutex lock so only one side is reading/writing to shared memory at the same time.

Fix #69806

### CODE REVIEW

File: src/mono/wasm/runtime/dotnet-crypto-worker.js [hunk 1]
```diff
@@ -3,9 +3,14 @@
...
 var ChannelWorker = {
     _impl: class {
+        // LOCK states
+        get LOCK_UNLOCKED() { return 0; } // 0 means the lock is unlocked
+        get LOCK_OWNED() { return 2; } // 2 means the ChannelWorker owns the lock
+
         // BEGIN ChannelOwner contract - shared constants.
         get STATE_IDX() { return 0; }
         get MSG_SIZE_IDX() { return 1; }
+        get LOCK_IDX() { return 2; }
```
Comment (bartonjs) [inline src/mono/wasm/runtime/dotnet-crypto-worker.js:13]: This is fine, and probably simplifies things, but I'm surprised the state machine isn't handling it, since it uses atomics for transitions.  Do you know how the state machine is getting desynced?

Comment (eerhardt) [reply src/mono/wasm/runtime/dotnet-crypto-worker.js:13]: I haven't worked out the exact way the race condition happens. What I do know is that when the race happens, the `ChannelWorker` reads `0` for the `MSG_SIZE`. The only way that can happen is that the `ChannelWorker` runs twice in succession, and it is reading the `0` it wrote itself to the `MSG_SIZE` field in the previous page:

https://github.com/dotnet/runtime/blob/54f104a16489b7a2fa5b9661e8030aa23aa494b0/src/mono/wasm/runtime/dotnet-crypto-worker.js#L69-L70

I've verified this by changing that line to `-1`, and when the race happens, the `ChannelWorker` reads `-1` for the `MSG_SIZE`.

Then, when the race condition happens, I logged what the total amount of data received by the `ChannelWorker` was. And when the test fails, the total amount is always `1024` chars (one page size) less than when the test passes. Upping the test from one million `a`s to ten million `a`s, and running the test in a loop on a 2-core machine seems to consistently repro the problem after 5-10 iterations of the loop. (I set the loop for 50, and it never reached the full 50 before reproing.)

My guessing here is that it isn't a simple race condition, but a combination of race conditions that need to happen in a specific order for the code to get into this state.

The "write" side:

https://github.com/dotnet/runtime/blob/54f104a16489b7a2fa5b9661e8030aa23aa494b0/src/mono/wasm/runtime/crypto-worker.ts#L122-L152

The "read" side:
https://github.com/dotnet/runtime/blob/54f104a16489b7a2fa5b9661e8030aa23aa494b0/src/mono/wasm/runtime/dotnet-crypto-worker.js#L51-L73

The first race is at the bottom of the methods - the "write" side doesn't wait to be notified, but instead spins until it reads a new "state". That means the write side can get unblocked before the "read" side calls ".wait". 

Then another race is between lines 139-140 of the "write" and 71-72 of the "read". The "write" side can change the state in between the "read" side moving to 'state = AWAIT' and calling ".wait". So now the "read" side doesn't wait on line 72 (because the state is no longer 'AWAIT'). It then loops around and reads another page of data, sets the state, and then calls ".wait". Meanwhile, the "write" side is after 139, but before 140. Now it runs to call "notify" to wake up the "read" side one more time - and the "read" side now reads `0` for `MSG_SIZE`.

The part I haven't worked out is how that causes the skipping of a page. But given that you can see these two sides running concurrently, and causing unintended state transitions, adding the lock to ensure only one side is in the "critical section" at a time seems like the most appropriate way to fix it.

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
Just to ask, is this worth considering back porting to `release/7.0-preview5`?

**Comment by eerhardt** [comment]
> Just to ask, is this worth considering back porting to release/7.0-preview5?

I believe we have already built the final "runtime" build for preview5. According to the schedule the build happened on June 1 (which was also the last commit to the preview5 branch).

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by radical** [comment]
The wasm/AOT failure is https://github.com/dotnet/runtime/issues/70304 .
The WBT ones are https://github.com/dotnet/runtime/issues/69860 .

Both can be ignored for this PR.

File: src/mono/wasm/runtime/dotnet-crypto-worker.js [hunk 2]
```diff
@@ -101,6 +116,8 @@ var ChannelWorker = {
                 // Update the state
                 Atomics.store(this.comm, this.STATE_IDX, state);
 
+                this._release_lock();
```
Comment (radical) [inline src/mono/wasm/runtime/dotnet-crypto-worker.js:119]: should this be released if there was any error thrown?

Comment (eerhardt) [reply src/mono/wasm/runtime/dotnet-crypto-worker.js:119]: What kind of error are you thinking?

Comment (radical) [reply src/mono/wasm/runtime/dotnet-crypto-worker.js:119]: A bug in our code that causes an error to be thrown, for example. Do IIUC that the app would be stuck in that case as  the main thread would be spinning?

Comment (eerhardt) [reply src/mono/wasm/runtime/dotnet-crypto-worker.js:119]: > Do IIUC that the app would be stuck in that case as the main thread would be spinning?

Yeah, probably.

Comment (eerhardt) [reply src/mono/wasm/runtime/dotnet-crypto-worker.js:119]: I think a lot more work would be necessary to make this code "reentrant" on an error. It would probably be better tracked by https://github.com/dotnet/runtime/issues/69740, than in this PR.

File: src/mono/wasm/runtime/crypto-worker.ts [hunk 3]
```diff
@@ -202,6 +218,19 @@ class LibraryChannel {
         return String.fromCharCode.apply(null, slicedMessage);
     }
 
+    private acquire_lock() {
+        while (Atomics.compareExchange(this.comm, this.LOCK_IDX, this.LOCK_UNLOCKED, this.LOCK_OWNED) !== this.LOCK_UNLOCKED) {
```
[the remark this answers is not in the document]
Comment (eerhardt) [reply src/mono/wasm/runtime/crypto-worker.ts:222]: I learned a lot from reading https://hacks.mozilla.org/2017/06/avoiding-race-conditions-in-sharedarraybuffers-with-atomics/. And the [basic lock implementation](https://github.com/lars-t-hansen/js-lock-and-condition) it links to.

**Comment by eerhardt** [comment]
Merging to fix the random CI failures.

**Comment by eerhardt** [comment]
> Would it make sense to put this in "known issues" for preview 5 then?

Good idea. I've opened https://github.com/dotnet/core/pull/7524
