### PR TITLE
Fix loop cloning of array of struct with array field

### LINKED ISSUE #66254: Accessing an array of ValueTuple<int[], int, ...> throws exception if code is optimized
### Describe the bug

The compiler optimization seems to be too aggressive in some cases with ValueTuple arrays.

My ValueTuple array:
```
var a = new ValueTuple<int[], int>[]
{
	new (new[] { 0 }, 1),
	new (new[] { 1 }, 1)
};
```

Now I loop through the Item1 arrays with two nested for loops:

```
for (var i1 = 0; i1 < a.Length; i1++)
{
	var length = a[i1].Item1.Length;
	
	for (var i2 = 0; i2 < length; i2++)
	{
		var elem = a[i1].Item1[i2];
		
		Console.WriteLine(elem);
	}
}
```

This works as expected in the debug configuration. If I run the same code in the release configuration (with optimizations), a **NullReferenceException** is thrown. This also happens in the debug configuration when I enable optimizations.

The error does not occur if the value 0 is assigned to Item2 when defining the array:

```
var a = new ValueTuple<int[], int>[]
{
	new (new[] { 0 }, 0),
	new (new[] { 1 }, 0)
};
```

The ValueTuple can also be defined with 3 types:

```
var a = new ValueTuple<int[], int, int>[]
{
	new (new[] { 0 }, 1, 1),
	new (new[] { 1 }, 1, 1)
};
```
In this case, an **AccessViolationException** is thrown instead of a NullReferenceException.

If the nested for loops are implemented differently, e.g..

```
for (var i1 = 0; i1 < a.Length; i1++)
{
	for (var i2 = 0; i2 < a[i1].Item1.Length; i2++)
	{
		var elem = a[i1].Item1[i2];
		Console.WriteLine(elem);
	}
}
```

or

```
foreach (var aElem in a) {
  foreach (var elem in aElem.Item1) {
    Console.WriteLine(elem);
  }
}
```

everything works as expected even when optimized.

### To Reproduce

You can find the initial sample [here](https://github.com/DerNairolf/ValueTupleSample)

### Exceptions (if any)

NullReferenceException
AccessViolationException

### Further technical details

No IDE used.

```
dotnet run --configuration Release
dotnet run --configuration Debug
```

dotnet --info:
.NET SDK (gemäß "global.json"):
 Version:   6.0.200
 Commit:    4c30de7899

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### PR DESCRIPTION
**Pull request by BruceForstall**
Loop cloning needs to parse what morph creates from GT_INDEX nodes
to determine if there are array accesses with bounds checks that
could potentially be optimized. For jagged array access, this can
be a "comma chain" of bounds checks and array element address expressions.
For a case where an array of structs had a struct field, such as
`ValueTuple<int[], int>[]`, cloning was confusing the expression
`a[i].Item1[j]` for the jagged array access `a[i][j]`.

The fix here is to keep track of the type of the `GT_INDEX` node that is
being morphed, in the `GT_BOUNDS_CHECK` node that is created for it.
(This is the only thing cloning parses, to avoid the need to parse
the very complex trees morph can create.) This type is then checked
when parsing the "comma chain" trees. If a non-`TYP_REF` is found (such
as a `TYP_STRUCT` in the above example), no more levels of array indexing
are considered. (`TYP_REF` is what an array object would have, for a jagged
array.)

Fixes #66254.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@AndyAyersMS PTAL
cc @dotnet/jit-contrib

File: src/coreclr/jit/loopcloning.cpp [hunk 1]
```diff
@@ -2246,37 +2247,26 @@ bool Compiler::optExtractArrIndex(GenTree* tree, ArrIndex* result, unsigned lhsN
...
-//
-//  Operation:
-//      Recursively look for a list of array indices. For example, if the tree is
-//          V03 = (V05 = V00[V01]), V05[V02]
-//      that corresponds to access of V00[V01][V02]. The return value would then be:
-//      ArrIndex result { arrLcl: V00, indLcls: [V01, V02], rank: 2 }
+//      tree             the tree to be checked if it is an array [][][] operation.
+//      result           OUT: the extracted GT_INDEX information.
+//      lhsNum           var number of array object we're looking for.
+//      topLevelIsFinal  OUT: set to `true` if we reached a non-TYP_REF element type array.
```
Comment (AndyAyersMS) [inline src/coreclr/jit/loopcloning.cpp:2264]: Document the return value?

File: src/coreclr/jit/loopcloning.cpp [hunk 2]
```diff
@@ -2246,37 +2247,26 @@ bool Compiler::optExtractArrIndex(GenTree* tree, ArrIndex* result, unsigned lhsN
     result->useBlock = compCurBB;
     result->rank++;
 
+    // If the array element type (saved from the GT_INDEX node during morphing) is anything but
+    // TYP_REF, then it must the the final level of jagged array.
+    *topLevelIsFinal = (arrBndsChk->gtInxType != TYP_REF);
```
Comment (AndyAyersMS) [inline src/coreclr/jit/loopcloning.cpp:2252]: assert `arrBndsChk->gtInxType != TYP_VOID`?

**Review by AndyAyersMS — APPROVED** [review]
Presumably we'll want to port this?

**Comment by BruceForstall** [comment]
> Presumably we'll want to port this?

Yes.
