### PR TITLE
Use the register of CAST for contained index operator

### LINKED ISSUE #74117: Assertion failed 'isGeneralRegister(reg3)'
With:
```
COMPlus_JitStress=2c
COMPlus_TieredCompilation=0
```

```
D:\h\w\AF170944\w\A85C08F8\e>call RunTests.cmd --runtime-path D:\h\w\AF170944\p 
----- start Wed 08/17/2022 16:58:42.37 ===============  To repro directly: ===================================================== 
pushd D:\h\w\AF170944\w\A85C08F8\e\
"D:\h\w\AF170944\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.DiagnosticSource.Tests.runtimeconfig.json --depsfile System.Diagnostics.DiagnosticSource.Tests.deps.json xunit.console.dll System.Diagnostics.DiagnosticSource.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

D:\h\w\AF170944\w\A85C08F8\e>"D:\h\w\AF170944\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.DiagnosticSource.Tests.runtimeconfig.json --depsfile System.Diagnostics.DiagnosticSource.Tests.deps.json xunit.console.dll System.Diagnostics.DiagnosticSource.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Diagnostics.DiagnosticSource.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.DiagnosticSource.Tests (found 223 of 242 test cases)
  Starting:    System.Diagnostics.DiagnosticSource.Tests (parallel test collections = on, max threads = 8)

Assert failure(PID 10944 [0x00002ac0], Thread: 12260 [0x2fe4]): Assertion failed 'isGeneralRegister(reg3)' in 'System.Diagnostics.ActivityTraceId:SetSpanFromHexChars(System.ReadOnlySpan`1[Char],System.Span`1[Byte])' during 'Generate code' (IL size 57; hash 0xb99cb8f0; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\emitarm64.cpp Line: 6853
    Image: D:\h\w\AF170944\p\dotnet.exe
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1950188&view=results

@dotnet/jit-contrib A new random JitStress failure

### PR DESCRIPTION
**Pull request by kunalspathak**
If index is contained and the underlying operator is `GT_CAST` we were not handling that case and that led to using `REG_COUNT` register from `index` in `genScaledAdd()` . I have fixed it and also added checks to see if more such cases are missing.

Fixes: https://github.com/dotnet/runtime/issues/74117

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -4404,12 +4404,24 @@ void CodeGen::genLeaInstruction(GenTreeAddrMode* lea)
...
+                {
+                    // Handle LEA with "contained" BFIZ
+                    assert(scale == 0);
+                    scale = (DWORD)index->gtGetOp2()->AsIntConCommon()->IconValue();
+                    index = index->gtGetOp1()->gtGetOp1();
+                }
+                else if (index->OperIs(GT_CAST))
+                {
+                    index = index->AsCast()->gtGetOp1();
+                }
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenarmarch.cpp:4420]: What kind of cast gets here? `CAST<long>(int)`? But then what is doing the sign/zero-extension?

Comment (kunalspathak) [reply src/coreclr/jit/codegenarmarch.cpp:4420]:
```
N006 (  4,  6) [000018] -c--G----U-                   t18 = *  CAST      long <- uint $1c0
                                                            /--*  t19    byref  
                                                            +--*  t18    long   
N007 (  6,  8) [000020] -----------                   t20 = *  LEA(b+(i*1)+0) byref 
```

Comment (SingleAccretion) [reply src/coreclr/jit/codegenarmarch.cpp:4420]: Hmm, so it is indeed `CAST<long>(int)`. There is still the question of what is doing the extension (is it perhaps unnecessary)?

**Comment by JulieLeeMSFT** [comment]
@kunalspathak, @dotnet/jit-contrib, are we going to backport it to 7?

**Comment by kunalspathak** [comment]
> @kunalspathak, @dotnet/jit-contrib, are we going to backport it to 7?

Probably. This issue is around the code that was introduced in .NET 7.

File: src/coreclr/jit/lower.cpp [hunk 2]
```diff
@@ -5345,29 +5345,36 @@ bool Lowering::TryCreateAddrMode(GenTree* addr, bool isContainable, GenTree* par
...
-
-        const unsigned shiftBy = (unsigned)index->gtGetOp2()->AsIntCon()->IconValue();
-
-        // 'scale' and 'offset' have to be unset since we're going to use [base + index * SXTW/UXTW scale] form
-        // where there is no room for additional offsets/scales on ARM64. 'shiftBy' has to match target's width.
-        if (cast->CastOp()->TypeIs(TYP_INT) && cast->TypeIs(TYP_LONG) && (genTypeSize(targetType) == (1U << shiftBy)) &&
-            (scale == 1) && (offset == 0))
+        if (!IsSafeToContainMem(parent, index))
+        {
+            index->ClearContained();
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:5353]: There is no need to clear containment here, it has just been cleared above in the method:
```c
    // Neither the base nor the index should now be contained.
    if (base != nullptr)
    {
        base->ClearContained();
    }
    if (index != nullptr)
    {
        index->ClearContained();
    }
```

File: src/coreclr/jit/lower.cpp [hunk 3]
```diff
@@ -5345,29 +5345,36 @@ bool Lowering::TryCreateAddrMode(GenTree* addr, bool isContainable, GenTree* par
...
-        GenTreeCast* cast = index->gtGetOp1()->AsCast();
-        assert(cast->isContained());
-
-        const unsigned shiftBy = (unsigned)index->gtGetOp2()->AsIntCon()->IconValue();
-
-        // 'scale' and 'offset' have to be unset since we're going to use [base + index * SXTW/UXTW scale] form
-        // where there is no room for additional offsets/scales on ARM64. 'shiftBy' has to match target's width.
-        if (cast->CastOp()->TypeIs(TYP_INT) && cast->TypeIs(TYP_LONG) && (genTypeSize(targetType) == (1U << shiftBy)) &&
-            (scale == 1) && (offset == 0))
+        if (!IsSafeToContainMem(parent, index))
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:5351]: We should add a comment on why we're checking against the parent:
```
// Check containment safety against the parent node - this will ensure that LEA with the contained
// index will itself always be contained. We do not support uncontained LEAs with contained indices.
```

File: src/coreclr/jit/lower.cpp (hunk 2 above)
Comment (kunalspathak) [reply src/coreclr/jit/lower.cpp]: ah, true. Revised the code.

**Review by SingleAccretion — APPROVED** [review]
Code changes LGTM. We may find out the upfront `IsSafeToContainMem` it too expensive TP-wise and will need to move it down after the other checks, but hopefully not.

I've also filed #74448 to track the complete fix, you could add a link to it from codegen (or not).

Also it would be nice to add a regression test, say:
```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static void Problem(ref byte x, int a)
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static byte GetByte() => 1;

    JitUse(&a);
    Unsafe.Add(ref x, a) = GetByte();
}

[MethodImpl(MethodImplOptions.NoInlining)]
public static void JitUse<T>(T* arg) where T : unmanaged { }
```

File: src/coreclr/jit/lower.cpp [hunk 4]
```diff
@@ -5362,29 +5362,44 @@ bool Lowering::TryCreateAddrMode(GenTree* addr, bool isContainable, GenTree* par
...
+    if (index != nullptr)
     {
-        // BFIZ node is a binary op where op1 is GT_CAST and op2 is GT_CNS_INT
-        GenTreeCast* cast = index->gtGetOp1()->AsCast();
-        assert(cast->isContained());
-
-        const unsigned shiftBy = (unsigned)index->gtGetOp2()->AsIntCon()->IconValue();
+        if (index->OperIs(GT_CAST) && (scale == 1) && (offset == 0) && varTypeIsByte(targetType))
+        {
+            index->AsCast()->CastOp()->ClearContained(); // Uncontain any memory operands.
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:5370]: I think this was meant to go into the `IsSafeToContainMem` block.

Comment (kunalspathak) [reply src/coreclr/jit/lower.cpp:5370]: Ah, that's true. Missed that during merging.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib - can someone review it?

**Comment by kunalspathak** [comment]
@EgorBo - can you take a look?

File: src/coreclr/jit/codegenarmarch.cpp [hunk 5]
```diff
@@ -4458,12 +4458,24 @@ void CodeGen::genLeaInstruction(GenTreeAddrMode* lea)
...
+                else
+                {
+                    assert(!"There are more unhandled nodes for contained index for ARM64");
```
Comment (BruceForstall) [inline src/coreclr/jit/codegenarmarch.cpp:4477]: Would this be better:
```suggestion
                    unreached();
```
since it's a noway_assert?

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/jit/codegenarmarch.cpp (hunk 5 above)
Comment (kunalspathak) [reply src/coreclr/jit/codegenarmarch.cpp:4477]: sure, fixed it and added a comment.

**Comment by EgorBo** [comment]
> @EgorBo - can you take a look?

oops, sorry for the delay - didn't notice this mention, something wrong with my mail filters. LGTM btw
