### PR TITLE
[wasm][debugger] Support calling `get_Item` passing decimal, float or double as parameter.

### LINKED ISSUE #76014: [wasm][debugger] Support indexing Dictionary by object key
Tests: in DebuggerTests.EvaluateOnCallFrameTests.EvaluateUserDefinedIndexingByNonIntLocals uncomment lines:
```
// ("f[aDecimal]", TNumber(3))
```
and fix. Decimal is treated as an object. We can handle indexing by it e.g. by adding in `GetElementIndexInfo` in case of `(arg.Expression is IdentifierNameSyntax)`
```
// indexObject={
//   "type": "object",
//   "value": null,
//   "description": "3.34",
//   "className": "System.Decimal",
//   "objectId": "dotnet:valuetype:9",
//   "isValueType": true
// }
                        if (indexObject["type"].ToString() == "object") // e.g. System.Decimal behaves this way
                        {
                            elementIdxStr.Append(indexObject["description"].ToString()); // or resolving value
                        }
                        else
                        {
                            elementIdxStr.Append(indexObject["value"].ToString());
                        }
```
But when one class has multiple indexers like we have in our tests, then in `Task<JObject> Resolve(ElementAccessExpressionSyntax elementAccess, Dictionary<string, JObject> memberAccessValues, JObject indexObject, List<string> variableDefinitions, CancellationToken token)` we'll get multiple "get_Item" methods. In case of Decimal, it is sent as 4th method out of 6 and the 2nd method is `public bool this[string key3] => key3.Length > 3;`. We are trying all possible methods till one works (does not throw an exception) and by coincidence the boolean-returning method does not throw. That's why we resolve a wrong value by mistake. We return 
```
{
  "type": "boolean",
  "value": true,
  "description": "true",
  "className": "System.Boolean"
}
```
instead of "number" 3.

### PR DESCRIPTION
**Pull request by thaystg**
Fixes #76014

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 1]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
...
+                case ElementType.I8:
+                case ElementType.R4:
+                case ElementType.R8:
+                case ElementType.U2:
+                case ElementType.U4:
+                case ElementType.U8:
+                    if (parameterType != "number")
+                        return false;
+                    if (parameterType == "object")
+                        return false;
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:572]: Is it possible to enter `if (parameterType == "object")` when we already returned false when checking `if (parameterType != "number")`? We can remove this check.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 2]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
...
+                    break;
+                case ElementType.Char:
+                    if (parameterType != "string" && parameterType != "symbol")
+                        return false;
+                    break;
+                case ElementType.Boolean:
+                    if (parameterType == "boolean")
+                        return true;
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:580]: What if `parameterType` is "string" for ElementType.Boolean? Then we will break and return true. Let's change to:
```suggestion
                    if (parameterType != "boolean")
                        return false;
```
and remove the remaining if-conditions in this case.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 3]
```diff
@@ -715,14 +715,19 @@ public async Task<bool> WriteConst(LiteralExpressionSyntax constValue, MonoSDBHe
...
                 {
-                    // FixMe: what if the number is not int but single/double?
-                    Write(ElementType.I4, objValue["value"].Value<int>());
+                    var expected = expectedType is not null ? expectedType.Value : ElementType.I4;
+                    if (expected == ElementType.R4)
+                        Write(expected, objValue["value"].Value<float>());
+                    else if (expected == ElementType.R8)
+                        Write(expected, objValue["value"].Value<double>());
+                    else
+                        Write(expected, objValue["value"].Value<int>());
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:730]: If we cast then we probably need all cases:
- [ ] ElementType.I2,
- [ ] ElementType.I4,
- [ ] ElementType.I8,
- [x] ElementType.R4,
- [x] ElementType.R8,
- [ ] ElementType.U2,
- [ ] ElementType.U4,
- [ ] ElementType.U8.
Or..let's test if adding tests with them won't throw here, maybe cast to int to all other cases is enough.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 4]
```diff
@@ -659,12 +659,10 @@ public async Task EvaluatePropertyThatThrows()
...
-                    ("f[shortString]", TBool(false))
-                    // ("f[aFloat]", TNumber(1)),
-                    // ("f[aDouble]", TNumber(2)),
-
-                    // FixMe: https://github.com/dotnet/runtime/issues/76014
-                    // ("f[aDecimal]", TNumber(3)) // object
+                    ("f[shortString]", TBool(false)),
+                    ("f[aFloat]", TNumber(1)),
+                    ("f[aDouble]", TNumber(2)),
+                    ("f[aDecimal]", TNumber(3)) // object
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:665]: Tests corresponding to the comment in MonoSDBHelper.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 5]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
...
+                        return false;
+                    if (parameterType == "object")
+                        return false;
+                    break;
+                case ElementType.String:
+                    if (parameterType != "string")
+                        return false;
+                    break;
+                default:
+                    return true;
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:591]: We're missing on this list:
- [ ] ElementType.U1,
- [ ] ElementType.Ptr,
- [ ] ElementType.I1,
- [ ] ElementType.ValueType,
- [ ] ElementType.Ptr,
- [ ] ElementType.Void,

**Review by ilonatommy — APPROVED** [review]
Awesome job

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 6]
```diff
@@ -436,6 +437,11 @@ public ParameterInfo[] GetParametersInfo()
             if (_parametersInfo != null)
                 return _parametersInfo;
 
+            var signature = methodDef.Signature;
+            var sigReader = Assembly.asmMetadataReader.GetBlobReader(signature);
+            var decoder = new SignatureDecoder<ElementType, object>(_signatureTypeProvider, Assembly.asmMetadataReader, genericContext: null);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:442]: `genericContext: null` - 👍 for adding the param name!

File: src/mono/wasm/debugger/BrowserDebugProxy/SignatureTypeProvider.cs [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+using System;
+using System.Collections.Generic;
+using System.Collections.Immutable;
+using System.Linq;
+using System.Reflection.Metadata;
+using System.Text;
+using System.Threading.Tasks;
+using Microsoft.WebAssembly.Diagnostics;
+
+namespace Microsoft.WebAssembly.Diagnostics
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/SignatureTypeProvider.cs:13]: File-scoped namespace:
```suggestion
namespace Microsoft.WebAssembly.Diagnostics;
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 8]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
...
+                case ElementType.U2:
+                case ElementType.U4:
+                case ElementType.U8:
+                    if (parameterType != "number")
+                        return false;
+                    if (parameterType == "object")
+                        return false;
+                    break;
+                case ElementType.Char:
+                    if (parameterType != "string" && parameterType != "symbol")
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:575]: Does this also need a `== "object"` check?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 9]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
             }
         }
 
+        private static bool CheckParametersCompatibility(ElementType? typeCode, JObject value)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:548]: nit: `typeCode` -> `paramTypeCode`

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 10]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
...
+        {
+            if (!typeCode.HasValue)
+                return true;
+            var parameterType = value["type"]?.Value<string>();
+            var parameterClassName = value["className"]?.Value<string>();
+
+            switch (typeCode.Value)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:555]: Do IIUC that we are checking if `value` can be passed as an argument to a method with parameter type `typeCode`?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 11]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
...
+            {
+                case ElementType.Object:
+                    if (parameterType != "object")
+                        return false;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:559]: Do IIUC that we are checking if value can be passed as an argument to a method with parameter type typeCode?
If so, then shouldn't param type == `object` accept anything?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 12]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
             }
         }
 
+        private static bool CheckParametersCompatibility(ElementType? typeCode, JObject value)
+        {
+            if (!typeCode.HasValue)
+                return true;
+            var parameterType = value["type"]?.Value<string>();
+            var parameterClassName = value["className"]?.Value<string>();
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:553]: Should these instead be `argumentType`, and `argumentClassName`?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 13]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
...
+                    break;
+                case ElementType.I2:
+                case ElementType.I4:
+                case ElementType.I8:
+                case ElementType.R4:
+                case ElementType.R8:
+                case ElementType.U2:
+                case ElementType.U4:
+                case ElementType.U8:
+                    if (parameterType != "number")
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:569]: Does this work if the argument is being cast from something else, like `foo((int) 'x')` ?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 14]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
...
+                    if (parameterType == "number" && (parameterClassName == "Single" || parameterClassName == "Double"))
+                        return false;
+                    if (parameterType == "object")
+                        return false;
+                    break;
+                case ElementType.String:
+                    if (parameterType != "string")
+                        return false;
+                    break;
+                default:
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:590]: How do we handle a nullable parameter type?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 15]
```diff
@@ -545,6 +545,54 @@ async Task<ArraySegment<byte>> WriteLiteralExpressionAsIndex(DotnetObjectId root
             }
         }
 
+        private static bool CheckParametersCompatibility(ElementType? typeCode, JObject value)
+        {
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:549]: Don't we already do this kind of parameter/argument type compatibility check for regular method calls? Can that be used here?

**Review by radical — CHANGES_REQUESTED** [review]

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 2 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:580]: No, we can't to it, because we accept number as parameter for methods that accept boolean.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 10 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:555]: yes.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 11 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:559]: If a method is expecting an object, can we call it passing a integer? I don't think so.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 13 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:569]: no, we don't support casting.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 14 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:590]: we don't handle it right now.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 15 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:549]: No, we don't do, we only believe that the customer is calling with the correct parameters and try to run it on runtime side, if we have a type mismatch the runtime will return an error and we return the error to the ide.

**Review by radical — APPROVED** [review]
