### PR TITLE
Invoke members for dispatch interfaces on that interface's corresponding IDispatch pointer, not on the canonical one

### LINKED ISSUE #122175: `DISP_E_UNKNOWNNAME` for non-default interface members
### Description

My server object implements two interfaces with one being default.
I can access members of the default interface but not of the non-default one.
Instead, I get `Unknown name. (0x80020006 (DISP_E_UNKNOWNNAME))` on such access.

### Reproduction Steps

My server exposes such COM object:
```cs
[ComVisible(true)]
[CLSCompliant(true)]
[ProgId("MyCompany.MyObject")]
[Guid("{CF824E95-642E-4F8D-8CD1-F67BC588B107}")]
[ClassInterface(ClassInterfaceType.None)]
[ComDefaultInterface(typeof(IFirst))]
public sealed class MyObject : IFirst, ISecond
{
    public void Invoke1() {}
    public void Invoke2() {}
}

[ComVisible(true)]
[CLSCompliant(true)]
[Guid("{59DAED5B-726B-4DDD-8F07-9236382038F7}")]
[InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
public interface IFirst
{
    void Invoke1();
}

[ComVisible(true)]
[Guid("{88C3FF65-0155-48A9-917D-E96DFAC8409B}")]
[InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
public interface ISecond
{
    void Invoke2();
}
```

My client does this:
```cs
var myObjectType = Type.GetTypeFromProgID("MyCompany.MyObject", throwOnError: true)!;
dynamic first = Activator.CreateInstance(myObjectType);
first.Invoke1(); // works well
var second = (ISecond)first; // get to an explicit interface implementation
second.Invoke2(); // throws COMException with DISP_E_UNKNOWNNAME
```

I followed a solution from "Custom wrappers" section of [Generating Metadata](https://learn.microsoft.com/en-us/dotnet/framework/interop/importing-a-type-library-as-an-assembly#generating-metadata).

### Expected behavior

I can access members of non-default interfaces of COM objects.

### Actual behavior

I get `COMException` with `DISP_E_UNKNOWNNAME` on access of non-default interface members of COM objects.

### Regression?

Works in .NET Framework and .NET 8. Not working since .NET 9.

### Known Workarounds

_No response_

### Configuration

Windows 11
.NET 8.0.404
.NET 9.0.308
.NET 10.0.100

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkoritzinsky**
We need to invoke the method on the exact IDispatch pointer that's returned to ensure that members on that dispatch interface will be resolved. The default IDispatch pointer will only resolve members for its corresponding interface.

Fixes #122175

Regression introduced in https://github.com/dotnet/runtime/pull/104406

Test helper code adapted from #122195 (can be consolidated in the future).

### CODE REVIEW

File: src/tests/Interop/common/ComActivationHelpers.cs [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+{
+    public static IDisposable RegisterTypeForActivation<T>()
+        where T: new()
+    {
+        Factory factory = new(() => new T());
+        CoRegisterClassObject(
+            typeof(T).GUID,
+            factory,
+            1, // CLSCTX_INPROC_SERVER
+            2, // REGCLS_MULTIPLEUSE
```
Comment (AaronRobinsonMSFT) [inline src/tests/Interop/common/ComActivationHelpers.cs]:
```suggestion
            1, // REGCLS_MULTIPLEUSE
```

File: src/tests/Interop/common/ComActivationHelpers.cs [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+                Marshal.Release(ccw);
+            }
+        }
+
+        public void LockServer(bool fLock)
+        {
+            // No-op
+        }
+    }
+
```
Comment (AaronRobinsonMSFT) [inline src/tests/Interop/common/ComActivationHelpers.cs]:
```suggestion
```

**Review by AaronRobinsonMSFT — COMMENTED** [review]
Thank you! We should also backport this to .NET 10. I don't think it needs to go further back.

**Comment by jkoritzinsky** [comment]
@AaronRobinsonMSFT any more feedback or is this good to go?

**Review by AaronRobinsonMSFT — APPROVED** [review]
Thank you!
