### PR TITLE
Use the latest base register while accessing the stack

### LINKED ISSUE #35501: Test failure: JIT\\jit64\\mcc\\interop\\mcc_i77\\mcc_i77.cmd
failed in job: [runtime-coreclr jitstress2-jitstressregs 20200426.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=618314&view=ms.vss-test-web.build-test-results-tab&runId=19367528&resultId=108715&paneView=debug)

Error message
~~~
Return code: 1
Raw output file: D:\h\w\AE9209A9\w\AC300922\e\JIT\jit64\Reports\JIT.jit64\mcc\interop\mcc_i74\mcc_i74.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\AE9209A9\p\corerun.exe" mcc_i74.dll 
FAILED: [field f152] => expected = 2.1219957944E-314, actual = 12
FAILED
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\AE9209A9\p
> D:\h\w\AE9209A9\w\AC300922\e\JIT\jit64\mcc\interop\mcc_i74\mcc_i74.cmd
Expected: True
Actual: False


Stack trace
   at JIT_jit64._mcc_interop_mcc_i74_mcc_i74_._mcc_interop_mcc_i74_mcc_i74_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm.Checked\TestWrappers\JIT.jit64\JIT.jit64.XUnitWrapper.cs:line 12944
~~~

### PR DESCRIPTION
**Pull request by kunalspathak**
When we try to access a field of a struct parameter, we calculate the offset of field using wrong base register. The struct that is getting accessed has 257 fields and we use `sp` as a base register to calculate the offset. However at 152nd field we reach the encoding limit of `0xFF8` and hence decide to use `fp` as a new base register to calculate the offset from. But we don't take the new base register into account when calculating the final indirect of the field. 

Here is the snippet of code that loads each field .   

```asm
    
    movw    r10, 0xfe8
    add     r10, sp
    vldr    d10, [r10]  ; field access
    movw    r10, 0xff0
    add     r10, sp
    vldr    d10, [r10]  ; field access
 
    movw    r10, 0xff8
    add     r10, sp
    vldr    d10, [r10]   ; field access
 
    movw    r10, 0x4c0
    add     r10, sp     ; <-- this should be "add     r10, r11"
    vldr    d10, [r10]
 
    movw    r10, 0x4c8
    add     r10, sp
    vldr    d10, [r10]

```

The fix is to use the latest base register we find out (through `lvaFrameAddress`) inside `emitIns_R_S()` when called with `INS_movw` and propagate it via `emitIns_genStackOffset()`. In order to come up with a small repro case, I wanted to see how this situation arises with stress flags, but couldn't find exact reason. One thing that I noticed was in repro case, the `compLclFrameSize` is lot bigger than the non-repro case, but again was not sure enough.

I ran various jitstress pipelines and looks like the `mcc_i*` tests are passing. [Here](https://helix.dot.net/api/2019-06-17/jobs/abd11cf7-8881-4647-a9c5-d42d2e043d85/workitems/JIT.jit64.mcc/files) is the test log.

Fixes: https://github.com/dotnet/runtime/issues/35501 and https://github.com/dotnet/runtime/issues/36199

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/src/jit/emitarm.cpp [hunk 1]
```diff
@@ -3514,7 +3514,7 @@ void emitter::emitIns_S(instruction ins, emitAttr attr, int varx, int offs)
  *
  *  Add an instruction referencing a register and a stack-based local variable.
  */
-void emitter::emitIns_R_S(instruction ins, emitAttr attr, regNumber reg1, int varx, int offs)
+void emitter::emitIns_R_S(instruction ins, emitAttr attr, regNumber reg1, int varx, int offs, regNumber* baseReg)
```
Comment (CarolEidt) [inline src/coreclr/src/jit/emitarm.cpp:3517]: I would suggest to rename this `pBaseReg` to make it clear that it's a pointer.

File: src/coreclr/src/jit/codegen.h [hunk 2]
```diff
@@ -1406,8 +1406,6 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     void inst_SA_RV(instruction ins, unsigned ofs, regNumber reg, var_types type);
     void inst_SA_IV(instruction ins, unsigned ofs, int val, var_types type);
 
-    void inst_RV_ST(
```
Comment (CarolEidt) [inline src/coreclr/src/jit/codegen.h:1409]: I take it that this is an unrelated change, in that it was unused.

File: src/coreclr/src/jit/emitarm.cpp [hunk 3]
```diff
@@ -3663,7 +3674,8 @@ void emitter::emitIns_R_S(instruction ins, emitAttr attr, regNumber reg1, int va
 }
 
 // generate the offset of &varx + offs into a register
-void emitter::emitIns_genStackOffset(regNumber r, int varx, int offs, bool isFloatUsage)
+// also capture the 'baseReg' used for generating movw/movt
```
Comment (CarolEidt) [inline src/coreclr/src/jit/emitarm.cpp:3677]: Could you add a standard function header here? And I would also rename this parameter as `pBaseReg` and describe it as "an out parameter to capture the 'baseReg' used ..."

**Review by CarolEidt — COMMENTED** [review]
The changes seem reasonable, but I would probably have used a return value for the base register (since these methods are currently `void`) rather than adding a pointer as an "out" parameter.

**Comment by kunalspathak** [comment]
> The changes seem reasonable, but I would probably have used a return value for the base register (since these methods are currently `void`) rather than adding a pointer as an "out" parameter.

Thanks @CarolEidt . My first thought was to return a value but since it was one of the `emitIns_*` methods which has return signature as `void`, I didn't wanted to break the consistency. If it is ok with you, I will change it to return instead of `out` parameter.

**Comment by CarolEidt** [comment]
> If it is ok with you, I will change it to return instead of out parameter.

To me, the inconsistency actually makes it clearer that these methods are "special", though I supposed there's also the danger that the caller will ignore the return value, since C++ makes it easy to do so. Do others have different opinions? @dotnet/jit-contrib

**Comment by echesakovMSFT** [comment]
> Do others have different opinions? @dotnet/jit-contrib

I would just go with return type = void and returning the base register via out parameter (that should be named pBaseReg)

File: src/coreclr/src/jit/emitarm.cpp [hunk 4]
```diff
@@ -3513,8 +3513,10 @@ void emitter::emitIns_S(instruction ins, emitAttr attr, int varx, int offs)
 /*****************************************************************************
  *
  *  Add an instruction referencing a register and a stack-based local variable.
+ *
+ *  Stores the base register used for accessing the offset of stack in "pBaseReg".
  */
-void emitter::emitIns_R_S(instruction ins, emitAttr attr, regNumber reg1, int varx, int offs, regNumber* baseReg)
+void emitter::emitIns_R_S(instruction ins, emitAttr attr, regNumber reg1, int varx, int offs, regNumber* pBaseReg)
```
Comment (CarolEidt) [inline src/coreclr/src/jit/emitarm.cpp:3519]: It would be nice to change this to a standard function header: https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/clr-jit-coding-conventions.md#94-function-header-comment (we have been gradually adding these as we touch the many methods that don't yet have them), but I wouldn't necessarily hold this up for that.

**Review by CarolEidt — APPROVED** [review]
LGTM

**Comment by CarolEidt** [comment]
> added standard function header

Thanks!
