### PR TITLE
Ensure that WaitForPendingFinalizers has seen the expected Full GC count

### LINKED ISSUE #104218: Test failure: System.Tests.GCTests.KeepAlive_Null
**Failed in:** [runtime-coreclr libraries-jitstressregs 20240630.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=725300&view=ms.vss-test-web.build-test-results-tab&runId=18212684&resultId=180944&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstressregs0x80-Ubuntu.2204.Amd64.Open
    - System.Tests.GCTests.KeepAlive_Null
```

**Error message:**
```
 Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at System.Tests.GCTests.KeepAliveNullTest.Run() in /_/src/libraries/System.Runtime/tests/System.Runtime.Tests/System/GCTests.cs:line 211
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: https://github.com/dotnet/runtime/issues/104218

- [x] CoreCLR
- [x] NativeAOT
- [x] add a test
- [x] make the test outerloop

This fixes a long known race that was very rare in the past, but recently started becoming a nuisance. It goes like this:

- Some unrelated GC happens, completes, and finalization cycle starts
- Finalization thread drains the queue and is just about to report that it is done draining, but gets preempted
- User thread makes allocations, calls `Collect`, calls `WaitForPendingFinalizers`
- Collect runs, pends more items into the queue
- User thread waits in `WaitForPendingFinalizers` on the queue-empty event
- The Finalization thread gets to run and signals the event (while the queue is no longer empty)

This forced people to do unnatural things like calling `Collect(); WaitForPendingFinalizers();` a few times in a row "to be sure". 
That would not help if the objects expected to be finalized are not guaranteed to be unreachable, of course. No number of repeating this would help.  
Otherwise doing `Collect(); WaitForPendingFinalizers();` just once should be enough.

The fix makes sure that a waiter for the queue drain completion event and the releaser of that water are in agreement on what Full GCs have been certainly handled in the finalization cycle. 
In a rare case if the release is too old (in Full GC time), then waiter asks for one more cycle - to make sure there is nothing left in the queue, that the waiter waits for.

### CODE REVIEW

**Comment by VSadov** [comment]
I think this is ready for a review.

File: src/coreclr/vm/finalizerthread.cpp [hunk 1]
```diff
@@ -580,6 +592,15 @@ void FinalizerThread::FinalizerThreadWait()
 
         DWORD status;
         status = hEventFinalizerDone->Wait(INFINITE,TRUE);
+
+        if (desiredFullGcCount - g_fullGcCountSeenByFinalization > 0)
```
Comment (jkotas) [inline src/coreclr/vm/finalizerthread.cpp:596]: I assume that the subtraction and > 0 are to handle GC counts wrapping around. Signed integer overflows are undefined behavior in C++. I am not sure whether it can bite us here. Unsigned integer overflows have behavior in C++, so it would be more portable to do this with unsigned types.

**Review by jkotas — APPROVED** [review]
Nice. Thanks!

File: src/libraries/System.Runtime/tests/System.Runtime.Tests/System/GCTests.cs [hunk 2]
```diff
@@ -292,6 +293,50 @@ private class TestObject
...
+
+            [MethodImpl(MethodImplOptions.NoInlining)]
+            static void MakeAndNull(bool* flag)
+            {
+                var deadObj = new TestObjectWithFinalizer(flag);
+                // it's dead here
+            };
+        }
+
+        unsafe class TestObjectWithFinalizer
```
Comment (mangod9) [inline src/libraries/System.Runtime/tests/System.Runtime.Tests/System/GCTests.cs:328]: is unsafe implementation required here?

File: src/coreclr/vm/finalizerthread.cpp (hunk 1 above)
Comment (VSadov) [reply src/coreclr/vm/finalizerthread.cpp:596]: Yes, a billion of gen2 gc would be a rare, but plausible scenario for a long term service. 
I’d prefer the API to return size_t or uint64_t here, but it is what it is. Not sure why signed int was chosen.

We do know it is a monotonically growing count that may wrap around. I’ll throw in some unsigned casts, just in case the compiler does something unexpected with compares.

Comment (VSadov) [reply src/coreclr/vm/finalizerthread.cpp:596]: One billion seconds is about 30 years. ;)

1-10 times per second is the rough guess for gen2 frequency, I think, excluding stress scenarios.

File: src/libraries/System.Runtime/tests/System.Runtime.Tests/System/GCTests.cs (hunk 2 above)
Comment (VSadov) [reply src/libraries/System.Runtime/tests/System.Runtime.Tests/System/GCTests.cs:328]: > is unsafe implementation required here?

Not required. I could allocate a mutable class and change a field. It is a testcase, so I used whatever was simpler. 
Accessing a local on another thread's stack is technically a UB in the memory model, so perhaps should change this to a class.

**Review by mangod9 — APPROVED** [review]

File: src/coreclr/nativeaot/Runtime/FinalizerHelpers.cpp [hunk 3]
```diff
@@ -135,7 +135,10 @@ EXTERN_C void QCALLTYPE RhWaitForPendingFinalizers(UInt32_BOOL allowReentrantWai
         // Wait for the finalizer thread to get back to us.
         g_FinalizerDoneEvent.Wait(INFINITE, false, allowReentrantWait);
 
-        if (desiredFullGcCount - g_fullGcCountSeenByFinalization > 0)
+        // we use unsigned math here as the collection counts, which are size_t internally,
+        // can in theory overflow an int and wrap around.
+        // unsigned math would have more defined/portable behavior in such case
+        if ((unsigned int)desiredFullGcCount - (unsigned int)g_fullGcCountSeenByFinalization > 0)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/FinalizerHelpers.cpp:141]: Do you need to cast the result back to `int`?

`unsigned` minus `unsigned` is going to be unsigned. It means that the current version is same as `if (desiredFullGcCount != g_fullGcCountSeenByFinalization)`.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/FinalizerHelpers.cpp:141]: Yes, I think I need a cast to `int`. The result of unsigned subtraction is indeed unsigned.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/FinalizerHelpers.cpp:141]: Also, I think we see that in gcstress taking long time.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/FinalizerHelpers.cpp:141]: It is relatively fast to run gcstress these days (about 1 - 1.5 hours), but in this PR it's been 2+ hours and nothing completed yet.

**Comment by VSadov** [comment]
Thanks!!!
