### PR TITLE
Don't consider `lvSpillAtSingleDef` in `WritesAnyLocation`

### LINKED ISSUE #78023: [jitstress] Assertion failed 'isContainable || supportsRegOptional' in 'JIT.HardwareIntrinsics.General.Program:AbsDouble()' during 'Generate code'
```
:\h\w\BD5F09D0\w\B7CA09CB\e>type C:\h\w\BD5F09D0\w\B7CA09CB\u\SetStressModes_jitstress2.cmd 
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2

  Starting:    JIT.HardwareIntrinsics.XUnitWrapper (parallel test collections = on, max threads = 4)
    JIT\HardwareIntrinsics\General\Vector128\Vector128_ro\Vector128_ro.cmd [FAIL]
      
      Assert failure(PID 964 [0x000003c4], Thread: 540 [0x021c]): Assertion failed 'isContainable || supportsRegOptional' in 'JIT.HardwareIntrinsics.General.Program:AbsDouble()' during 'Generate code' (IL size 74; hash 0xa20af912; FullOpts)
      
          File: D:\a\_work\1\s\src\coreclr\jit\hwintrinsiccodegenxarch.cpp Line: 61
          Image: C:\h\w\BD5F09D0\p\corerun.exe
```

Work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=76043&view=ms.vss-test-web.build-test-results-tab&runId=1574484&resultId=102263&paneView=debug
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76793-merge-bb14f9f0b05e4fd1ab/JIT.HardwareIntrinsics.General.Vector128/1/console.03aa098f.log?helixlogtype=result

cc @dotnet/jit-contrib @tannergooding

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/78023

### CODE REVIEW

File: src/coreclr/jit/sideeffects.h [hunk 1]
```diff
@@ -128,8 +128,12 @@ class AliasSet final
 
             if ((m_flags & ALIAS_WRITES_LCL_VAR) != 0)
             {
+                // Stores to 'lvLiveInOutOfHndlr' locals cannot be reordered with
+                // exception-throwing nodes so we conservatively consider them
+                // globally visible.
+
                 LclVarDsc* const varDsc = m_compiler->lvaGetDesc(LclNum());
-                return varDsc->IsAlwaysAliveInMemory();
+                return varDsc->lvLiveInOutOfHndlr != 0;
```
Comment (tannergooding) [inline src/coreclr/jit/sideeffects.h:136]: Worked with @SingleAccretion on this fix.

The premise is that `IsAlwaysAliveInMemory` checks both `lvLiveInOutOfHndlr` and `lvSpillAtSingleDef`. The latter is only set in LSRA and shouldn't have any significance with regards to side effect checking since such spills can't interfere.

This solves the inconsistency between the check in lowering and the assert in codegen.

**Review by jakobbotsch — APPROVED** [review]
