### PR TITLE
[NativeAOT] Initial osx-arm64 bring up

### LINKED ISSUE #64337: NativeAOT for osx-arm64
Hello,
I've tried to build my app with NativeAOT for osx-arm64, but it says that it's not supported:
`.nuget/packages/microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/build/Microsoft.NETCore.Native.Publish.targets(66,5): error : Native compilation does not support targeting osx-arm64 yet. https://github.com/dotnet/corert/issues/4589`
The issue links to "CoreRT" which seems to be archived and no other info is present.
What's the status for it for .NET 7, how can I compile my app with NativeAOT for M1 Mac ?

### LINKED ISSUE #67232: Reloc failures with NativeAOT on Apple Silicon
I am trying to enable NativeAOT on OSX arm64. With this patch https://github.com/dotnet/runtime/compare/main...am11:feature/nativeaot/osx-arm64 (tested with both `@GOTPAGE` and `@PAGE` assembler directives), it builds the nupkg. Consuming that package results in the following errors during the `ilc` step:

```sh
# with `<add key="TestSource" value="/Users/am11/projects/runtime/artifacts/packages/Release/Shipping" />`
# in NuGet.config
$ dotnet nuget locals all --clear && rm -rf obj bin && dotnet publish --use-current-runtime -v:diag ...
... snip ...
21:06:05.007   1:7>Target "IlcCompile: (TargetId:181)" in file "/Users/am11/.nuget/packages/microsoft.dotnet.ilcompiler/7.0.0-dev/build/Microsoft.NETCore.Native.targets" from project "/Users/am11/projects/naot1/naot1.csproj" (target "LinkNative" depends on it):
                   Building target "IlcCompile" completely.
                   Output file "obj/release/net7.0/osx-arm64/native/naot1.o" does not exist.
                   Task "Message" skipped, due to false condition; ($(_BuildingInCompatibleMode) != 'true') was evaluated as (true != 'true').
                   Task "Message" (TaskId:126)
                     Task Parameter:Text=Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT (TaskId:126)
                     Task Parameter:Importance=high (TaskId:126)
                     Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT (TaskId:126)
                   Done executing task "Message". (TaskId:126)
                   Task "Exec" (TaskId:127)
                     Task Parameter:Command="/Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/tools/ilc" @"obj/release/net7.0/osx-arm64/native/naot1.ilc.rsp" (TaskId:127)
                     "/Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/tools/ilc" @"obj/release/net7.0/osx-arm64/native/naot1.ilc.rsp" (TaskId:127)
                     <unknown>:0: error: ADR/ADRP relocations must be GOT relative (TaskId:127)
                     <unknown>:0: error: unknown AArch64 fixup kind! (TaskId:127)
                     <unknown>:0: error: unknown AArch64 fixup kind! (TaskId:127)
                     <unknown>:0: error: fixup value out of range (TaskId:127)
                     <unknown>:0: error: ADR/ADRP relocations must be GOT relative (TaskId:127)
                     <unknown>:0: error: unknown AArch64 fixup kind! (TaskId:127)
                     <unknown>:0: error: unknown AArch64 fixup kind! (TaskId:127)
                     <unknown>:0: error: fixup value out of range (TaskId:127)
... repeats 1000s of times ...
```

somewhere after the objwriter has succeeded: https://github.com/dotnet/runtime/blob/071e772d9d3bd8b50a5380bce6214277a1e61c98/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ObjectWriter.cs#L1183 and before the `clang` command is executed. While the ilc task does not fail, MSBuild fails on the clang step:

```sh
                 Set Property: _IgnoreLinkerWarnings=false
                   Set Property: _IgnoreLinkerWarnings=true
                   Task "Exec" (TaskId:129)
                     Task Parameter:IgnoreStandardErrorWarningFormat=True (TaskId:129)
                     Task Parameter:Command=clang "obj/release/net7.0/osx-arm64/native/naot1.o" -o "bin/release/net7.0/osx-arm64/native/naot1" /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/sdk/libbootstrapper.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/sdk/libRuntime.WorkstationGC.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Globalization.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.IO.Compression.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Net.Security.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Security.Cryptography.Native.Apple.a -g -Wl,-rpath,'@executable_path' -lstdc++ -ldl -lm -lz -licucore -framework CoreFoundation -framework Foundation -framework Security -framework GSS (TaskId:129)
                     clang "obj/release/net7.0/osx-arm64/native/naot1.o" -o "bin/release/net7.0/osx-arm64/native/naot1" /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/sdk/libbootstrapper.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/sdk/libRuntime.WorkstationGC.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Globalization.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.IO.Compression.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Net.Security.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Security.Cryptography.Native.Apple.a -g -Wl,-rpath,'@executable_path' -lstdc++ -ldl -lm -lz -licucore -framework CoreFoundation -framework Foundation -framework Security -framework GSS (TaskId:129)
                     ld: malformed __LD,__compact_unwind section, bad length file 'obj/release/net7.0/osx-arm64/native/naot1.o' (TaskId:129)
                     clang: error: linker command failed with exit code 1 (use -v to see invocation) (TaskId:129)
21:06:12.873   1:7>/Users/am11/.nuget/packages/microsoft.dotnet.ilcompiler/7.0.0-dev/build/Microsoft.NETCore.Native.targets(337,5): error MSB3073: The command "clang "obj/release/net7.0/osx-arm64/native/naot1.o" -o "bin/release/net7.0/osx-arm64/native/naot1" /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/sdk/libbootstrapper.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/sdk/libRuntime.WorkstationGC.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Globalization.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.IO.Compression.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Net.Security.Native.a /Users/am11/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/7.0.0-dev/framework/libSystem.Security.Cryptography.Native.Apple.a -g -Wl,-rpath,'@executable_path' -lstdc++ -ldl -lm -lz -licucore -framework CoreFoundation -framework Foundation -framework Security -framework GSS" exited with code 1. [/Users/am11/projects/naot1/naot1.csproj]
                   Done executing task "Exec" -- FAILED. (TaskId:129)
21:06:12.873   1:7>Done building target "LinkNative" in project "naot1.csproj" -- FAILED.: (TargetId:182)
```

With objdump, that `__LD,__compact_unwind` section looks like:

```asm
Disassembly of section __LD,__compact_unwind:

00000000003b2858 <ltmp8>:
  3b2858: 40 4b 00 00   udf     #19264
  3b285c: 00 00 00 00   udf     #0
  3b2860: 74 00 00 00   udf     #116
  3b2864: 00 00 00 03   <unknown>
                ...
  3b2874: c0 4b 00 00   udf     #19392
  3b2878: 00 00 00 00   udf     #0
  3b287c: 74 00 00 00   udf     #116
  3b2880: 00 00 00 03   <unknown>
                ...
  3b2890: 40 4c 00 00   udf     #19520
  3b2894: 00 00 00 00   udf     #0
  3b2898: 74 00 00 00   udf     #116
  3b289c: 00 00 00 03   <unknown>
                ...
  3b28ac: c0 4c 00 00   udf     #19648
  3b28b0: 00 00 00 00   udf     #0
  3b28b4: 74 00 00 00   udf     #116
  3b28b8: 00 00 00 03   <unknown>
... repeats ...
```

### PR DESCRIPTION
**Pull request by filipnavara**
Depends on https://github.com/dotnet/llvm-project/pull/185.
Fixes #67232
Fixes #64337

Thanks to @am11 @MichalStrehovsky and @jkotas for the help with pushing this forward and analysing all the issues that came up.

### CODE REVIEW

File: src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp [hunk 1]
```diff
@@ -755,6 +755,206 @@ void Registers_REGDISPLAY::setVectorRegister(int num, libunwind::v128 value)
     D[num] = (uint64_t)value.vec[2] << 32 | (uint64_t)value.vec[3];
 }
 
+/// CompactUnwinder_arm64 uses a compact unwind info to virtually "step" (aka
+/// unwind) by modifying a Registers_arm64 register set
+template <typename A>
```
Comment (am11) [inline src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp:760]: llvm-libunwind is only used for NativeAOT, you can make the required changes there. This way we can keep track of how much we have diverged from upstream. Long term plan is to upstream the changes (#72655).

File: src/coreclr/gc/unix/gcenv.unix.cpp [hunk 2]
```diff
@@ -633,7 +633,7 @@ void GCToOSInterface::YieldThread(uint32_t switchCount)
 static void* VirtualReserveInner(size_t size, size_t alignment, uint32_t flags, uint32_t hugePagesFlag = 0)
 {
     assert(!(flags & VirtualReserveFlags::WriteWatch) && "WriteWatch not supported on Unix");
-    if (alignment == 0)
+    if (alignment < OS_PAGE_SIZE)
```
Comment (am11) [inline src/coreclr/gc/unix/gcenv.unix.cpp:636]: Wrap under `#if defined(HOST_ARM64) && defined(TARGET_OSX) && defined(FEATURE_NATIVEAOT)` to limit the scope of this change?

File: src/coreclr/nativeaot/Runtime/CommonMacros.h [hunk 3]
```diff
@@ -155,8 +155,12 @@ inline bool IS_ALIGNED(T* val, uintptr_t alignment);
 
 #define DATA_ALIGNMENT  8
 #ifndef OS_PAGE_SIZE
+#if __APPLE__
```
Comment (am11) [inline src/coreclr/nativeaot/Runtime/CommonMacros.h:158]: nit:
```suggestion
#ifdef HOST_OSX
```

File: src/coreclr/nativeaot/Runtime/unix/unixasmmacrosarm64.inc [hunk 4]
```diff
@@ -73,6 +73,7 @@ C_FUNC(\Name):
 #if defined(__APPLE__)
         adrp \HelperReg, C_FUNC(\Name)@GOTPAGE
         ldr  \HelperReg, [\HelperReg, C_FUNC(\Name)@GOTPAGEOFF]
+        ldr  \HelperReg, [\HelperReg]
```
Comment (am11) [inline src/coreclr/nativeaot/Runtime/unix/unixasmmacrosarm64.inc:76]: Good catch, I missed it in #72733. Does it fix any smoke test?

**Review by am11 — APPROVED** [review]

File: src/native/external/llvm-libunwind/src/DwarfParser.hpp [hunk 5]
```diff
@@ -269,7 +269,7 @@ bool CFI_Parser<A>::findFDE(A &addressSpace, pint_t pc, pint_t ehSectionStart,
           pint_t pcRange = addressSpace.getEncodedP(
               p, nextCFI, cieInfo->pointerEncoding & 0x0F);
           // Test if pc is within the function this FDE covers.
-          if ((pcStart < pc) && (pc <= pcStart + pcRange)) {
+          if ((pcStart <= pc) && (pc < pcStart + pcRange)) {
```
Comment (filipnavara) [inline src/native/external/llvm-libunwind/src/DwarfParser.hpp:272]: Note: This should be upstreamed.

With pure DWARF CFI unwinding it was mostly harmless bug. Unless the offset was in epilog or prolog it would return the correct thing. If it was the very first instruction then it would either not find the method, or find the previous one. That could result in silent errors but usually not a crash.

However, with combined compact and DWARF unwinding there's often a case where the compact unwinding table contains an entry that says to use DWARF (with hint offset into the DWARF table). It would correctly process the compact unwinding entry but fail to find the DWARF one. That resulted in internal unwinder state where it provided some information but noticeably the LSDA pointer was `NULL`. That would get dereferenced and crash the application.

File: src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp (hunk 1 above)
Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp:760]: I can easily do that. Not sure how much it is frowned upon in regard to local vs upstreamed changes.

File: src/coreclr/gc/unix/gcenv.unix.cpp (hunk 2 above)
Comment (filipnavara) [reply src/coreclr/gc/unix/gcenv.unix.cpp:636]: I would still like to know why CoreCLR doesn't hit this but I assume that it's because of some GC feature switch (such as `FEATURE_MANUALLY_MANAGED_CARD_BUNDLES`).

While I can add the `#if` guards the code would still misbehave fatally when `alignment < OS_PAGE_SIZE` so I think the change is quite safe.

File: src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp (hunk 1 above)
Comment (am11) [reply src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp:760]: I didn't meant to upstream the change, just move it under `src/native/external/llvm-libunwind` instead of copy/pasting this whole class.

Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp:760]: Sure, I will do that. I was just not sure what's the policy about modifying the code in `src/native/external/llvm-libunwind` at all...

Comment (am11) [reply src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp:760]: It goes like this: make a change in `external/{xyz}/` in a separate commit and add `Apply {commit-sha}` line in `/src/native/external/{xyz}-version.txt`. That's all. :)

next to: https://github.com/dotnet/runtime/blob/a62d237af3608d846ffcb0e4d2edc4eca09bbd0a/src/native/external/llvm-libunwind-version.txt#L5

File: src/native/external/llvm-libunwind/src/DwarfParser.hpp (hunk 5 above)
Comment (am11) [reply src/native/external/llvm-libunwind/src/DwarfParser.hpp:272]: Please also pull this change in a separate commit and drop a line (`Apply {commit-sha}`) in `src/native/external/llvm-libunwind-version.txt`. We are tracking these changes for upstream in groups: https://github.com/dotnet/runtime/issues/72655. (your standalone commit will outlive when PR is squashed+merged and branch is deleted)

File: src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp (hunk 1 above)
Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp]: So I essentially need to submit one PR for the `external/...` change and then second one for `llvm-libunwind-version.txt` update (since I don't know the commit hash until it's merged on top of `main`)?

Comment (am11) [reply src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp]: It can be done in the same PR, just push separate commit(s). Those commits won't be lost. This way we can reconstruct the dependency tree by looking at the version.txt file like so:

```sh
$ cd src/native/external/llvm-libunwind; cd $_
$ git clone https://github.com/llvm/llvm-libunwind --single-branch --depth 1 - b llvmorg-15.0.0 # or whatever
$ rm -rf .git; cd ../../../../
$ curl -sSL https://github.com/dotnet/runtime/commit/e57194552327bccaf2b45a9190f0e6e1289472e4.patch |\
     git apply -
$ curl -sSL https://github.com/dotnet/runtime/commit/db7ed089a9e20a391a53e0b547f95dc8bf916765.patch |\
     git apply -
```

It helps when updating the dependency (and changes are not upstreamed). It also keeps track of things to be upstreamed.

Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp]: Ah, I see. If you fetch it from GitHub it goes directly to the über-repo that has commits from all forks.

File: src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp [hunk 6]
```diff
@@ -1030,7 +1037,7 @@ REDHAWK_PALEXPORT void REDHAWK_PALAPI PalHijack(HANDLE hThread, _In_opt_ void* p
     }
 #endif
 
-    if ((status != 0) && (status != EAGAIN))
+    if ((status != 0) && (status != EAGAIN) && (status != ESRCH))
```
Comment (VSadov) [inline src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:1040]: Why are we getting ESRCH here?

Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:1040]: This was happening in the threading smoke test. I assume it happens if the thread is dying at the same time as we try to suspend it (but I did not retry with your GC fix). Mono handled the error code so I assumed that it makes sense to do it here too.

Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:1040]: I can still hit it even with #75298 applied.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:1040]: It is suspisious. We are holding threadstore lock at this point, so a thread can't exit.
 
Perhaps GC crash causes rude termination of a thread, which leaves threadstore corrupted. 
I such case I am not sure if ignoring is better than aborting as we could get stuck trying to suspend a thread that does not exist. 
Let's see if this happens after the fix.

Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:1040]: I can check it under debugger now that I know what to look for.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:1040]: > I can still hit it even with https://github.com/dotnet/runtime/pull/75298 applied.

Ok, you can keep it as a workaround, but this needs to be investigated. Maybe there is another more transient reason, besides "the thread is dead" for this.

Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:1040]: The thread that is being signalled has this stack trace when it happens:
```
  thread #66
    frame #0: 0x00000001003dfe2c UnitTests`_S_P_CoreLib_System_Threading_WaitSubsystem_HandleManager__FromHandle(handle=4330599712) at WaitSubsystem.HandleManager.Unix.cs:29
    frame #1: 0x00000001002b7cdc UnitTests`_S_P_CoreLib_System_Threading_WaitSubsystem__SetEvent(handle=4330599712) at WaitSubsystem.Unix.cs:244
    frame #2: 0x00000001002a8328 UnitTests`_S_P_CoreLib_System_Threading_EventWaitHandle__Set(this=0x00000001047b1838) at EventWaitHandle.Unix.cs:48
    frame #3: 0x00000001002a4100 UnitTests`_S_P_CoreLib_System_Threading_Thread__OnThreadExit at Thread.NativeAot.Unix.cs:53
    frame #4: 0x00000001000a5220 UnitTests`::PalDetachThread(thread=0x00000001025044b0) at PalRedhawkUnix.cpp:502:9
    frame #5: 0x000000010002cdec UnitTests`ThreadStore::DetachCurrentThread(shutdownStarted=false) at threadstore.cpp:162:10
    frame #6: 0x0000000100027e6c UnitTests`RuntimeThreadShutdown(thread=0x00000001025044b0) at startup.cpp:452:5
    frame #7: 0x00000001000a6edc UnitTests`TlsDestructionMonitor::~TlsDestructionMonitor(this=0x00000001025045a8) at PalRedhawkUnix.cpp:451:13
    frame #8: 0x00000001000a5158 UnitTests`TlsDestructionMonitor::~TlsDestructionMonitor(this=0x00000001025045a8) at PalRedhawkUnix.cpp:448:5
    frame #9: 0x00000001a0085cc0 dyld`invocation function for block in dyld4::RuntimeState::_finalizeListTLV(void*) + 56
    frame #10: 0x00000001a0085c28 dyld`dyld4::RuntimeState::_finalizeListTLV(void*) + 116
    frame #11: 0x00000001a039a968 libsystem_pthread.dylib`_pthread_tsd_cleanup + 488
    frame #12: 0x00000001a039d760 libsystem_pthread.dylib`_pthread_exit + 84
    frame #13: 0x00000001a039d078 libsystem_pthread.dylib`_pthread_start + 160
```

Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:1040]: FWIW this is on `macOS Ventura 13.0 Beta (22A5321d)`. It could be some pthread behavior specific to it.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:1040]: The thread is exiting gracefully and in the process of being trapped on the thread store lock. I guess OS already considers it dead and does not want to or cannot deliver signals to it.   

We would need to allow `ESRCH` on OSX - the same way we allow `ENOTSUP`.

The thread is not running managed code and we will ignore it when we retry hijacking, so it is ok to ignore.

File: src/coreclr/gc/unix/gcenv.unix.cpp (hunk 2 above)
Comment (MichalStrehovsky) [reply src/coreclr/gc/unix/gcenv.unix.cpp:636]: > I would still like to know why CoreCLR doesn't hit this

AFAIK gcenv.unix.cpp is only used by CoreCLR when standalone GC is used (i.e. COMPlus_GCName is set to point to a standalone GC instead of the one in coreclr.dll/.so). @mangod9 @dotnet/gc can you have a look at this change?

Comment (MichalStrehovsky) [reply src/coreclr/gc/unix/gcenv.unix.cpp:636]: > AFAIK, there is no azp run trigger for that pipeline, someone with access will need to trigger it manually.

I tried to trigger it but it's complaining about the pool. It doesn't look like the gc-standalone pipeline ran for a week or so. It coincides with the pool changes. Cc @dotnet/gc.

The interesting thing about the `gc-standalone` pipeline is that it doesn't test mac at all. So if there was a arm64 macOS issue with standalone GC, we wouldn't even know it.

File: src/native/external/llvm-libunwind/src/CompactUnwinder.hpp [hunk 7]
```diff
@@ -28,34 +28,34 @@ namespace libunwind {
 #if defined(_LIBUNWIND_TARGET_I386)
 /// CompactUnwinder_x86 uses a compact unwind info to virtually "step" (aka
 /// unwind) by modifying a Registers_x86 register set
-template <typename A>
+template <typename A, typename R>
```
Comment (am11) [inline src/native/external/llvm-libunwind/src/CompactUnwinder.hpp:31]: nit: we can use default parameter to avoid retyping the second argument from all callsites, and revert changes in `UnwindCursor.hpp`.
```suggestion
template <typename A, typename R = Registers_x86>
```
(same for other archs below)

File: src/coreclr/gc/unix/gcenv.unix.cpp (hunk 2 above)
Comment (am11) [reply src/coreclr/gc/unix/gcenv.unix.cpp:636]: > if there was a arm64 macOS issue with standalone GC, we wouldn't even know it.

This change as written is not specific to arm64 macOS, other platforms can break. My original commit was https://github.com/am11/runtime/commit/45f3a4844126da5013980873af76fc3bd06e01f1, but it was recreated without the guard which has potential to break existing code.

Comment (filipnavara) [reply src/coreclr/gc/unix/gcenv.unix.cpp:636]: The specific call with the "invalid" `alignment` parameter is macOS arm64 specific though. It happens because of 16Kb page sizes and `GC_PAGE_SIZE != OS_PAGE_SIZE`.

File: src/native/external/llvm-libunwind/src/CompactUnwinder.hpp (hunk 7 above)
Comment (filipnavara) [reply src/native/external/llvm-libunwind/src/CompactUnwinder.hpp:31]: Good idea. 👍 I am bit rusty on C++ already.

**Comment by filipnavara** [comment]
The last two commits unblock the library tests. It seems to work quite well, so we may try to get a full run on the CI once this is merged.

File: src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/FatFunctionPointerNode.cs [hunk 8]
```diff
@@ -60,8 +60,9 @@ public override ObjectData GetData(NodeFactory factory, bool relocsOnly = false)
         {
             var builder = new ObjectDataBuilder(factory, relocsOnly);
 
-            // These need to be aligned the same as methods because they show up in same contexts
-            builder.RequireInitialAlignment(factory.Target.MinimumFunctionAlignment);
+            // These need to be aligned the same as method pointers because they show up in same contexts
+            // (macOS ARM64 has even stricter alignment requirement for the linker, so round up to pointer size)
+            builder.RequireInitialAlignment(factory.Target.PointerSize);
```
Comment (filipnavara) [inline src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/FatFunctionPointerNode.cs:65]: This one is actually hell to diagnose because it produces no error but causes corruption when linking. If absolute relocation of a symbols is 4-byte aligned and spans between two pages in the executable then only the lower part of the relocation is written correctly into the final executable.

This was the root cause of the [intermittent problem](https://github.com/dotnet/runtime/issues/67232#issuecomment-1240624936) I've hit earlier.

**Comment by filipnavara** [comment]
I ran the library test locally and the results look promising:

```
/Users/filipnavara/Projects/runtime/eng/testing/tests.targets(181,5): error : One or more tests failed while running tests from 'System.Console.Tests'. [/Users/filipnavara/Projects/runtime/src/libraries/System.Console/tests/System.Console.Tests.csproj]
/Users/filipnavara/Projects/runtime/eng/testing/tests.targets(181,5): error : One or more tests failed while running tests from 'System.Diagnostics.Process.Tests'. [/Users/filipnavara/Projects/runtime/src/libraries/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj]
/Users/filipnavara/Projects/runtime/eng/testing/tests.targets(181,5): error : One or more tests failed while running tests from 'System.Security.Cryptography.OpenSsl.Tests'. [/Users/filipnavara/Projects/runtime/src/libraries/System.Security.Cryptography.OpenSsl/tests/System.Security.Cryptography.OpenSsl.Tests.csproj]
/Users/filipnavara/Projects/runtime/eng/testing/tests.targets(181,5): error : One or more tests failed while running tests from 'System.Runtime.Extensions.Tests'. [/Users/filipnavara/Projects/runtime/src/libraries/System.Runtime.Extensions/tests/System.Runtime.Extensions.Tests.csproj]
```

Specifically, System.Runtime.Extensions.Tests has single failure related to macOS Ventura:
```
  [FAIL] System.Tests.EnvironmentTests.OSVersion_ValidVersion_OSX
  Assert.Contains() Failure
  Not found: 13
  In value:  osx-arm64
     at System.Tests.EnvironmentTests.OSVersion_ValidVersion_OSX() + 0x68
     at System.Runtime.Extensions!<BaseAddress>+0x1256b74
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x40
     at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x27c
```

System.Security.Cryptography.OpenSsl.Tests fails because of missing OpenSSL library (expected):
```
  Running assembly:System.Security.Cryptography.OpenSsl.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
  No usable version of libssl was found
  /Users/filipnavara/Projects/runtime/artifacts/bin/System.Security.Cryptography.OpenSsl.Tests/Debug/net7.0-unix/publish/RunTests.sh: line 168: 63790 Abort trap: 6           ./System.Security.Cryptography.OpenSsl.Tests -notrait category=OuterLoop -notrait category=failing -xml testResults.xml $RSP_FILE
  ~/Projects/runtime/src/libraries/System.Security.Cryptography.OpenSsl/tests
  ----- end Fri Sep 9 19:49:15 CEST 2022 ----- exit code 134 ----------------------------------------------------------
  exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
  ulimit -c value: 0
/Users/filipnavara/Projects/runtime/eng/testing/tests.targets(181,5): error : One or more tests failed while running tests from 'System.Security.Cryptography.OpenSsl.Tests'. [/Users/filipnavara/Projects/runtime/src/libraries/System.Security.Cryptography.OpenSsl/tests/System.Security.Cryptography.OpenSsl.Tests.csproj]
```

System.Diagnostics.Process.Tests has one failure:
```
  [FAIL] System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessName_ReturnsExpected
  Assert.All() Failure: 1 out of 2 items in the collection did not pass.
  [0]: Item: System.Diagnostics.Process (System.Diagnost)
       Xunit.Sdk.EqualException: Assert.Equal() Failure
       Expected: 2022-09-09T19:49:07.9700180+02:00
       Actual:   2022-09-09T19:49:07.9916470+02:00
          at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) + 0x16c
          at Xunit.Assert.Equal[T](T expected, T actual) + 0x40
          at System.Diagnostics.Tests.ProcessTests.<>c__DisplayClass90_0.<GetProcessesByName_ProcessName_ReturnsExpected>b__3(Process process) + 0x40
          at Xunit.Assert.<>c__DisplayClass11_0`1.<All>b__0(T item, Int32 index) + 0x3c
          at Xunit.Assert.All[T](IEnumerable`1 collection, Action`2 action) + 0xf0
     at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessName_ReturnsExpected() + 0x350
     at System.Diagnostics.Process!<BaseAddress>+0x11234f4
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x40
     at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x27c
```

System.Console.Tests has couple of failures related to Remote Executor:
```
[FAIL] Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(envVar: null)
  System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) + 0xb8
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) + 0x6c
     at Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(String envVar) + 0x174
     at System.Console!<BaseAddress>+0x10c0ad8
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x40
     at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x358
  [FAIL] Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(envVar: "1")
  System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) + 0xb8
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) + 0x6c
     at Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(String envVar) + 0x174
     at System.Console!<BaseAddress>+0x10c0ad8
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x40
     at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x358
  [FAIL] Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(envVar: "true")
  System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) + 0xb8
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) + 0x6c
     at Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(String envVar) + 0x174
     at System.Console!<BaseAddress>+0x10c0ad8
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x40
     at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x358
  [FAIL] Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(envVar: "tRuE")
  System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) + 0xb8
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) + 0x6c
     at Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(String envVar) + 0x174
     at System.Console!<BaseAddress>+0x10c0ad8
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x40
     at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x358
  [FAIL] Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(envVar: "0")
  System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) + 0xb8
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) + 0x6c
     at Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(String envVar) + 0x174
     at System.Console!<BaseAddress>+0x10c0ad8
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x40
     at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x358
  [FAIL] Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(envVar: "false")
  System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) + 0xb8
     at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) + 0x6c
     at Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes(String envVar) + 0x174
     at System.Console!<BaseAddress>+0x10c0ad8
     at System.Runtime.RawCalliHelper.Call(IntPtr, Void*, Byte&, Byte&, Void*) + 0x40
     at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x358
```

**Review by jkotas — APPROVED** [review]

File: src/coreclr/nativeaot/Runtime/ThunksMapping.cpp [hunk 9]
```diff
@@ -121,6 +121,9 @@ EXTERN_C NATIVEAOT_API void* __cdecl RhAllocateThunksMapping()
         return NULL;
     }
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/ThunksMapping.cpp:122]: Should the `PalVirtualProtect`s be ifdefed out for osx-arm64 so that it is symmetric with what we do at the end?
```
#if defined(HOST_OSX) && defined(HOST_ARM64)
    pthread_jit_write_protect_np(...)
#else
   PalVirtualProtect(...)
#endif
```

Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/ThunksMapping.cpp:122]: The `PalVirtualProtect` on the data part is actually necessary. I don't remember off-hand the exact reason but it's probably because the data pages are modified from the managed code without `pthread_jit_write_protect_np` guards.

I can change it to skip the other call but I was not sure if it's worth it.

Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/ThunksMapping.cpp:122]: I think skipping the other call on osx would look better to make the pre- and post- logic symmetric.

File: src/native/external/llvm-libunwind-version.txt [hunk 10]
```diff
@@ -3,3 +3,5 @@ https://github.com/llvm/llvm-project/releases/tag/llvmorg-14.0.6
 
 Apply https://github.com/dotnet/runtime/commit/e57194552327bccaf2b45a9190f0e6e1289472e4
 Apply https://github.com/dotnet/runtime/commit/db7ed089a9e20a391a53e0b547f95dc8bf916765
+Apply https://github.com/dotnet/runtime/commit/828c8d0b2a8cdc2479524c5229939641d3610a1b
```
Comment (jkotas) [inline src/native/external/llvm-libunwind-version.txt:6]: These are sha in your branch. They will change once this is merged.

Could you please submit these two llvm changes (without the change in llvm-libunwind-version.txt) in separate PR?

Comment (am11) [reply src/native/external/llvm-libunwind-version.txt:6]: > These are sha in your branch.

When a commit is pushed to an active PR, it is associated to the target GitHub repository. We can get any PR commit (attached or orphaned alike) with `https://github.com/dotnet/runtime/commit/{sha}.patch`.

If the contents of commit are not changing, this reference will remain valid.

Comment (jkotas) [reply src/native/external/llvm-libunwind-version.txt:6]: ok, I thought that we maintain these as links into the main branch history, but I see that it is not the case.

File: src/coreclr/nativeaot/Runtime/ThunksMapping.cpp (hunk 9 above)
Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/ThunksMapping.cpp:122]: I rechecked and actually both `PalVirtualProtect` calls are needed. It's possible to fold the other one into `PalVirtualAlloc` on macOS but it's not necessarily more readable.

**Comment by filipnavara** [comment]
Rebased after #75393 merge.

File: src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp [hunk 11]
```diff
@@ -776,8 +776,15 @@ REDHAWK_PALEXPORT _Ret_maybenull_ _Post_writable_byte_size_(size) void* REDHAWK_
         static const size_t Alignment = 64 * 1024;
 
         size_t alignedSize = size + (Alignment - OS_PAGE_SIZE);
+        int flags = MAP_ANON | MAP_PRIVATE;
 
-        void * pRetVal = mmap(pAddress, alignedSize, unixProtect, MAP_ANON | MAP_PRIVATE, -1, 0);
+#if defined(HOST_OSX) && defined(HOST_ARM64)
+        if (unixProtect & PROT_EXEC) {
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:782]:
```suggestion
        if (unixProtect & PROT_EXEC)
        {
```
Style nit

**Comment by jkotas** [comment]
@filipnavara Thank you!

**Comment by tgjones** [comment]
@filipnavara thank you for this!

A general question: is there an intention to backport this to 7.0, or is it strictly an 8.0 thing?

**Comment by filipnavara** [comment]
> A general question: is there an intention to backport this to 7.0, or is it strictly an 8.0 thing?

It missed the 7.0 deadline by a lot. However, it is possible to consume the ILCompiler package from NuGet so I think the realistic goal is to make it possible to use that with .NET 7 SDK.

**Comment by jkotas** [comment]
The instructions for using daily build packages are at https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#using-daily-builds
