### PR TITLE
[browser][wasm][bindings] Handle case where AsyncStateMachineBox`1 is…

### LINKED ISSUE #38328: [browser][wasm] Exception in InteropServices JavaScript with Tasks
The bindings do not handle `AsyncStateMachineBox` correctly.

Tasks are still be handled but the JS needs to support the `AsyncStateMachineBox`

### PR DESCRIPTION
**Pull request by kjpou1**
… returned

- There are cases where AsyncStateMachineBox`1 is returned instead of Task`1 within the bindings.  This was causing exceptions with Promise processing.

Close https://github.com/dotnet/runtime/issues/38328

### CODE REVIEW

File: src/mono/wasm/runtime/driver.c [hunk 1]
```diff
@@ -491,6 +491,9 @@ mono_wasm_string_from_js (const char *str)
 static int
 class_is_task (MonoClass *klass)
 {
+	if (!strcmp ("AsyncStateMachineBox`1", mono_class_get_name (klass)))
```
Comment (marek-safar) [inline src/mono/wasm/runtime/driver.c:494]: I'd rather avoid hardcoding all classes which derive from Task even if it's unlikely there will be many.

@vargaz @lambdageek is there a cheap way to check for MonoClass to derive from Task?

Comment (stephentoub) [reply src/mono/wasm/runtime/driver.c:494]: > I'd rather avoid hardcoding all classes which derive from Task even if it's unlikely there will be many.

Yeah, this is very fragile. There are others that can be returned as well.

Comment (kjpou1) [reply src/mono/wasm/runtime/driver.c]: Recent commit should be better uses `is_subclass_of`.

Local tests show that it works for `Task`, ```Task`1``` and ```AsyncStateMachineBox`1```.

**Review by marek-safar — APPROVED** [review]
