### PR TITLE
Remove locks from COM events delegate management.

### LINKED ISSUE #73754: COM event with recursion .net 6 problem
### Description

We are using a system that exposes UI interface using COM objects. It is an external application so I cannot send a minimal reproduction source code of a problem.  I will try to explain the whole workflow.

#### Background information

There is an application interface (COM) that exposes event.

Event declaration in the App interface:

```c#
event _IApplicationEvents_StatusBarEventEventHandler StatusBarEvent;
```

Delegate definition:

```c#
public delegate void _IApplicationEvents_StatusBarEventEventHandler([In][MarshalAs(UnmanagedType.BStr)] string Text, [In] BoStatusBarMessageType messageType);
```

There is also a StatusBarControl that allows us to set up the ProgressBarMessage:

```c#
application.StatusBar.SetText(“some text”);
```

When we set the text to the status bar Event is fired.

### Reproduction Steps

UseCase: When the StatusBarEvent fires with text equal to “crush” we want to change this to "****" on the status bar

EventHandler implementation:

```c#
public override void OnStatusBarDisplayed(string text, BoStatusBarMessageType messageType)
{
    if (text.Equals("crush",StringComparison.CurrentCultureIgnoreCase))
    {
        application.StatusBar.SetText("*****");
    }
}
```

I will provide some screenshots of the debugging session:

1. Set "crush" to the status bar. image
2. We get the Event notification and call the setText("****").
3. System freezes. We can see that the event handler thread freezes on the set text method. image
4. We can see that in the separate thread invoking a method the foreach loop of _delegateWrapper. image

### Expected behavior

What should happen: this thread @29816 should invoke this method and Call the OnStatusBarDisplayed event again. This is working correctly when running in the .net framework.

Below is the same call stack of the .net framework debugging session. image

Calling SetText in another thread is not an option for us.

### Actual behavior

System freezes. We can see that the event handler thread freezes on the set text method. image

### Regression?

This is working correctly when running in the .net framework.

### Known Workarounds

Calling SetText in another thread but this is not an option for us.

### Configuration

.NET 6.0
Windows 11
x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
This removes locks and instead assumes the collection is immutable.

Fixes #73754

### CODE REVIEW

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs [hunk 1]
```diff
@@ -99,7 +100,7 @@ private void PreProcessSignature()
         /// Since multicast delegate's built-in chaining supports only chaining instances of the same type,
         /// we need to complement this design by using an explicit linked list data structure.
         /// </summary>
-        private readonly List<DelegateWrapper> _delegateWrappers = new List<DelegateWrapper>();
+        private List<DelegateWrapper> _delegateWrappers = new List<DelegateWrapper>();
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:103]: Does `List<T>` by you much at this point?  Now that you're creating a new instance each time, adding is allocate+copy+store and remove is allocate+copy+copy.  You might slim it down slightly by just using an array directly.

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs [hunk 2]
```diff
@@ -156,19 +157,21 @@ public bool Empty
         {
             get
             {
-                lock (_delegateWrappers)
-                {
-                    return _delegateWrappers.Count == 0;
-                }
+                var wrappers = _delegateWrappers;
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:160]:
```suggestion
                List<DelegateWrapper> wrappers = _delegateWrappers;
```

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs [hunk 3]
```diff
@@ -246,27 +260,38 @@ public void RemoveDelegates(Func<Delegate, bool> condition)
...
+            } while (!PublishNewWrappers(newWrappers, wrappers));
         }
 
         public object? Invoke(object[] args)
         {
             Debug.Assert(!Empty);
             object? result = null;
 
-            lock (_delegateWrappers)
+            var wrappers = _delegateWrappers;
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:282]:
```suggestion
            List<DelegateWrapper> wrappers = _delegateWrappers;
```

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:103]: That is true, but then we do need to handle the removal case and that can be far more cumbersome. The add is simple, but removal requires me to copy, null and then shift > delete index down by one. I can do that but I think it is going to require more code unless there is as simple - remove and shift for arrays?

Comment (stephentoub) [reply src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:103]:
```C#
var newArr = new DelegateWrapper[oldArr.Length - 1];
oldArr.AsSpan(0, i).CopyTo(newArr);
oldArr.AsSpan(i + 1).CopyTo(newArr.AsSpan(i));
```
? Regardless, it's up to you.  I don't know how much the extra allocation for lists matter here, especially since we're creating a new array now on every mutation.

Comment (davidfowl) [reply src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:103]: ImmutableArray?

Comment (jkoritzinsky) [reply src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:103]: I don’t believe that’s available at the later this code compiled into (it’s compiled into CoreLib amongst other places)

Comment (AaronRobinsonMSFT) [reply src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:103]: > ```csharp
> var newArr = new DelegateWrapper[oldArr.Length - 1];
> oldArr.AsSpan(0, i).CopyTo(newArr);
> oldArr.AsSpan(i + 1).CopyTo(newArr.AsSpan(i));
> ```

Ah. I regularly forget going to `Span` for these sorts of things.

Comment (stephentoub) [reply src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:103]: (It could also just use Array.Copy instead of AsSpan(...).Copy.)

**Comment by AaronRobinsonMSFT** [comment]
@stephentoub The CI is green. Any other thoughts?

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs [hunk 4]
```diff
@@ -177,21 +180,28 @@ public void AddDelegate(Delegate d, bool wrapArgs = false)
...
                 int removeIdx = -1;
                 DelegateWrapper? wrapper = null;
-                for (int i = 0; i < _delegateWrappers.Count; i++)
+                for (int i = 0; i < wrappers.Count; i++)
                 {
-                    DelegateWrapper wrapperMaybe = _delegateWrappers[i];
+                    DelegateWrapper wrapperMaybe = wrappers[i];
                     if (wrapperMaybe.Delegate.GetType() == d.GetType() && wrapperMaybe.WrapArgs == wrapArgs)
                     {
                         removeIdx = i;
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:207]: Mainly I'm curious: are enough COM events subscribed to by multiple delegates in order to warrant this optimization of using Delegate.Combine rather than just having each delegate be its own entry in the list?  It looks safe from a cursory inspection, but it's a lot easier to prove correctness when the list being used is entirely immutable, whereas here the published list instance is having its contents modified.

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs [hunk 5]
```diff
@@ -246,27 +260,38 @@ public void RemoveDelegates(Func<Delegate, bool> condition)
...
+                    // Nothing to remove
+                    return;
+                }
+
+                newWrappers = wrappers.GetRange(0, wrappers.Count);
                 foreach (int idx in toRemove)
                 {
-                    _delegateWrappers.RemoveAt(idx);
+                    newWrappers.RemoveAt(idx);
                 }
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:273]: If you simplified the storage such that you didn't bother with Delegate.Combine, then it seems like tthis loop could be simplified as well to something along the lines of:
```C#
List<DelegateWrapper> oldWrappers, newWrappers;
do
{
    oldWrappers = _delegateWrappers;
    newWrappers  = new List<DelegateWrapper>(oldWrappers);
    if (newList.RemoveAll(w => condition(w.Delegate)) == 0)
    {
        return;
    }
}
while (!PublishNewWrappers(newWrappers, oldWrappers));
```

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs (hunk 1 above)
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:103]: It seems like optimization of this code / reduction in allocation isn't needed.  But if we decide to in the future, there are various things that could be done.  For example, this empty list could be a singleton, or null could be special-cased to mean empty.  And if one handler is common, rather than being a list this could be an object, which could then store either a DelegateWrapper directly or a list of them.

**Review by stephentoub — APPROVED** [review]

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs (hunk 4 above)
Comment (jkotas) [reply src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:207]: I think there is a bug when `Remove` is called on two threads in parallel:

First thread starts creates a new array with the delegate removed
Second thread removes the delegate in-place without creating a new array
First thread swaps in its array, reverting the affect of the second remove.

Comment (stephentoub) [reply src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:207]: > I think there is a bug when Remove is called on two threads in parallel:

Yeah, this is an example of the kind of issue that comes from trying to get sneaky (I hadn't noticed this particular case, but I believe you're right).

I think it'd be better to just do the simple thing and actually have the list be immutable; then the only concurrency management need be the simple act of publishing safely.

Or if our goal is to stick with what netfx had, just revert the locking entirely and go back to exactly what netfx had :)

**Comment by jkotas** [comment]
> Use array instead of List<T>
> Revert "Use array instead of List<T>" 

Was there an actual problem or you did not like the result? (It looks better to me with arrays instead of List.)

**Comment by AaronRobinsonMSFT** [comment]
> > Use array instead of List
> > Revert "Use array instead of List"
> 
> Was there an actual problem or you did not like the result? (It looks better to me with arrays instead of List.)

It was an option. However, I needed to create a `RemoveAll` local with annoying logic so deferred to just using `List<T>`. Either works and appear correct, other than the "Remove" logic you pointed out above. Let me see about simplifying it further.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas @stephentoub I switched back to using arrays, let me know if you prefer `List<T>`. I also removed the `Delegate.Combine` logic. My biggest concern with changing that related to threading since this is a COM code path. Looking through it, I no longer have any concerns so it was removed.

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs]: Switched back to arrays and am now using `Array.Empty<T>` for this. It isn't non-allocating, but it is now a single allocation for this code path for process lifetime.

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs [hunk 6]
```diff
@@ -206,50 +203,64 @@ public void RemoveDelegate(Delegate d, bool wrapArgs = false)
...
+                    {
+                        ri++;
+                        continue;
+                    }
+
+                    newCol[ni] = oldCol[oi];
+                    ni++;
+                }
+
+                return newCol;
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:263]: Seems like this whole thing could just be:
```C#
DelegateWrapper[] oldWrappers, newWrappers;
do
{
    oldWrappers = _delegateWrappers;
    var tmp = new List<DelegateWrapper>(oldWrappers);
    tmp.RemoveAll(w => condition(w.Delegate));
    newWrappers = tmp.ToArray();
}
while (!PublishNewWrappers(newWrappers, oldWrappers));
```
I'm just not clear on what overheads we're trying to avoid and which we're not.

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs [hunk 7]
```diff
@@ -206,67 +201,44 @@ public void RemoveDelegate(Delegate d, bool wrapArgs = false)
...
         }
 
         public object? Invoke(object[] args)
         {
             Debug.Assert(!Empty);
             object? result = null;
 
-            lock (_delegateWrappers)
+            DelegateWrapper[] wrappers = _delegateWrappers;
+            foreach (DelegateWrapper wrapper in wrappers)
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:230]: Nit: there's no need for the local here, it could just be:
```C#
foreach (DelegateWrapper wrapper in _delegateWrappers)
```
as was there previously, but if you prefer this style, it doesn't hurt

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs [hunk 8]
```diff
@@ -156,46 +157,40 @@ public bool Empty
         {
             get
             {
-                lock (_delegateWrappers)
-                {
-                    return _delegateWrappers.Count == 0;
-                }
+                DelegateWrapper[] wrappers = _delegateWrappers;
+                return wrappers.Length == 0;
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:161]: Nit: Could just be `get => _delegateWrappers.Length == 0;`, but if you prefer having the local, ok

File: src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs [hunk 9]
```diff
@@ -156,46 +157,40 @@ public bool Empty
...
             }
         }
 
         public void AddDelegate(Delegate d, bool wrapArgs = false)
         {
-            lock (_delegateWrappers)
+            DelegateWrapper[] wrappers;
+            DelegateWrapper[] newWrappers;
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Runtime/InteropServices/ComEventsMethod.cs:168]: Nit: could be `DelegateWrapper[] wrappers, newWrappers;`

**Review by stephentoub — APPROVED** [review]
