### PR TITLE
Fix BeginSendRequest and EndSendRequest on LdapConnection

### LINKED ISSUE #36690: LdapConnection.BeginSendRequest uses defunct Delegate.BeginInvoke
https://github.com/dotnet/runtime/blob/55d3260ad5dc48988228ac0cb1278541e87e513d/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs#L382

Delegate.BeginInvoke throws PlatformNotSupportedException on .NET Core.  So it appears LdapConnection.BeginSendRequest is broken (and we don't have tests for it).

cc: @joperezr

### PR DESCRIPTION
**Pull request by joperezr**
Fixes: #36690

cc: @tarekgh  @stephentoub 

LdapConnection had Async APM methods that never really worked in .NET Core as they were using Delegate.BeginInvoke and Delegate.EndInvoke which are not supported in .NET Core. These changes will make it so that they don't use that anymore and instead use Tasks and polling in order to not block a thread in the threadpool.

FYI: @blowdart @Tratcher @JunTaoLuo

### CODE REVIEW

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs [hunk 1]
```diff
@@ -379,7 +378,30 @@ public IAsyncResult BeginSendRequest(DirectoryRequest request, TimeSpan requestT
 
                     s_asyncResultTable.Add(asyncResult, messageID);
 
-                    _fd.BeginInvoke(messageID, operation, ResultAll.LDAP_MSG_ALL, requestTimeout, true, new AsyncCallback(ResponseCallback), requestState);
+                    ResponseCallback(ConstructResponseAsync(messageID, operation, ResultAll.LDAP_MSG_ALL, requestTimeout, true, sync: false), requestState);
+
+                    static async void ResponseCallback(ValueTask<DirectoryResponse> vt, LdapRequestState requestState)
```
Comment (stephentoub) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:383]: Probably best to use Task instead of void. If you get a warning at the call site about an unused task, you can suppress it with `_ = `.

File: src/libraries/System.DirectoryServices.Protocols/tests/DirectoryServicesProtocolsTests.cs [hunk 2]
```diff
@@ -17,6 +19,12 @@ public partial class DirectoryServicesProtocolsTests
         [ConditionalFact(nameof(IsLdapConfigurationExist))]
         public void TestAddingOU()
         {
+            while(!Debugger.IsAttached)
+            {
+                Thread.Sleep(5000);
+            }
+            Debugger.Break();
```
Comment (stephentoub) [inline src/libraries/System.DirectoryServices.Protocols/tests/DirectoryServicesProtocolsTests.cs:26]: Did you mean to commit this?

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs [hunk 3]
```diff
@@ -1436,7 +1433,30 @@ internal DirectoryResponse ConstructResponse(int messageId, LdapOperation operat
...
 
-            int error = LdapPal.GetResultFromAsyncOperation(_ldapHandle, messageId, (int)resultType, timeout, ref ldapResult);
+            int error;
+            if (sync)
+            {
+                error = LdapPal.GetResultFromAsyncOperation(_ldapHandle, messageId, (int)resultType, timeout, ref ldapResult);
+            }
+            else
+            {
+                // Given that we will be polling every millisecond, we need a stopwatch to make sure we track the timeout
```
Comment (stephentoub) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:1443]: Probably worth a comment about polling because there's no callback-based function to use.

**Comment by joperezr** [comment]
Unfortunately the APM async methods can't be easily tested with our UnitTests without using an actual LDAP server, but I have ran them locally against one in all Windows, Linux and OSX and they all work now using APM methods.

**Review by stephentoub — APPROVED** [review]

**Comment by joperezr** [comment]
Merging since the two test runs that are timing out are unrelated to this PR.

Thanks for the help with this @stephentoub
