### PR TITLE
[mono] Add monovm_initialize_preparsed for Android

### LINKED ISSUE #48416: [net6] monovm_initialize should allow an alternative to properties for initialization
## Background and Motivation

`monovm_initialize` takes a list of properties (specified as two arrays of keys and values) and parses them in order to set certain parameters for VM initialization. 
This parsing not only adds an initialization overhead but also makes the initialization awkward and insecure in certain cases. For instance, the `PINVOKE_OVERRIDE`
property is assumed to be an integer, which is to be converted to a pointer to a callback function. This requires the host application to:

  1. Take the pointer to the function
  2. Convert it to a string
  3. Allocate two string arrays
  4. Place the `PINVOKE_OVERRIDE` in the keys array and the pointer string in the values array
  5. Call `monovm_initialize` which then parses the pointer value into `unsigned long long`, casts it to `uintptr_t` and then casts it to the expected callback type.

Not only the process is unnecessarily verbose and wasteful, but it is also potentially insecure - should there be any problem with pointer->string->integer->pointer conversion 
or should there be a discrepancy between the signature of the callback in the host versus the one expected by the VM, the developer will get NO warning about the problem until
a mysterious crash during application execution.

Other properties, for instance those specifying a list of paths (e.g. `TRUSTED_PLATFORM_ASSEMBLIES` or `APP_PATHS`) also require that the host first constructs the array
(with the indicated separators) only for it to be deconstructed (with memory allocation for each path extracted from the list) moments later. This not only makes the process longer,
it also uses more memory than necessary (which is important especially on mobile or embedded devices).

## Proposed API

I understand that the above pattern is preferred by the dotnet runtime and that it will most likely remain available, but I suggest that an alternative initialization function is added which
takes a `struct` with properly typed and declared members that can be filled with all the necessary information for the known properties. The struct could include an optional key:value
array to pass properties that aren't standard and thus aren't included in the structure definition. Sample structure and init function declarations:

```c
struct _MonoVmInitProperty
{
   const char* name;
   const char* value;
};

struct _MonoVmInit
{
   size_t trusted_platform_assemblies_count;
   char** trusted_platform_assemblies; // Or remove the count member above and require this array to be NULL-terminated
   PInvokeOverrideFn pinvoke_override_cb;
   bool system_globalization_invariant;

   size_t other_properties_count;
   struct _MonoVmInitProperty* other_properties;
};

int monovm_initialize_fast (struct _MonoVmInit *init_data);
```

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Naming on the new structs TBD

Fixes https://github.com/dotnet/runtime/issues/48416

cc: @grendello

### CODE REVIEW

File: src/mono/mono/mini/mono-private-unstable.h [hunk 1]
```diff
@@ -47,6 +67,10 @@ monovm_initialize (int propertyCount, const char **propertyKeys, const char **pr
 MONO_API int 
 monovm_runtimeconfig_initialize (MonovmRuntimeConfigArguments *arg, MonovmRuntimeConfigArgumentsCleanup cleanup_fn, void *user_data);
 
+// The wrapper MonoCoreRuntimeProperties struct can be stack-allocated or freed, but any of the structs inside it will *not* be copied and need to be heap-allocated
+MONO_API int
+monovm_initialize_preparsed (MonoCoreRuntimeProperties *parsed_properties, int propertyCount, const char **propertyKeys, const char **propertyValues);
```
Comment (lambdageek) [inline src/mono/mono/mini/mono-private-unstable.h:72]: we can try to futureproof this by asking for a `sizeof (MonoCoreRuntimeProperties)` argument (assuming that in the future we only ever add fields and never remove them)

File: src/mono/mono/mini/mono-private-unstable.h [hunk 2]
```diff
@@ -47,6 +67,10 @@ monovm_initialize (int propertyCount, const char **propertyKeys, const char **pr
 MONO_API int 
 monovm_runtimeconfig_initialize (MonovmRuntimeConfigArguments *arg, MonovmRuntimeConfigArgumentsCleanup cleanup_fn, void *user_data);
 
+// The wrapper MonoCoreRuntimeProperties struct can be stack-allocated or freed, but any of the structs inside it will *not* be copied and need to be heap-allocated
```
Comment (lambdageek) [inline src/mono/mono/mini/mono-private-unstable.h:70]: nit: maybe be more explicit that they have to be heap-allocated and can't be freed at all.

File: src/mono/mono/mini/monovm.c [hunk 3]
```diff
@@ -213,9 +197,43 @@ monovm_initialize (int propertyCount, const char **propertyKeys, const char **pr
...
 	return 0;
 }
+/*typedef struct {
+	MonoCoreTrustedPlatformAssemblies *trusted_platform_assemblies;
+	MonoCoreLookupPaths *app_paths;
+	MonoCoreLookupPaths *app_ni_paths;
+	MonoCoreLookupPaths *platform_resource_roots;
+	MonoCoreLookupPaths *native_dll_search_directories;
+	PInvokeOverrideFn *pinvoke_override;
+} MonoCoreRuntimeProperties;*/
```
Comment (lambdageek) [inline src/mono/mono/mini/monovm.c:236]: nit: remove comment?

File: src/mono/mono/mini/mono-private-unstable.h (hunk 1 above)
Comment (lambdageek) [reply src/mono/mono/mini/mono-private-unstable.h:72]: I mean I understand this is an unstable header, but this will let us push runtime changes without having a Xamarin.Android PR ready as soon as they take a new preview of the runtime.

Comment (CoffeeFlux) [reply src/mono/mono/mini/mono-private-unstable.h:72]: I had that originally, but I decided we want to just not allow people to link against a different version of the runtime than they built against. If you do that, you're on your own. Unless I'm missing a reason that you'd want that?

File: src/mono/mono/mini/mono-private-unstable.h (hunk 2 above)
Comment (CoffeeFlux) [reply src/mono/mono/mini/mono-private-unstable.h:70]: Sure

File: src/mono/mono/mini/monovm.c (hunk 3 above)
Comment (CoffeeFlux) [reply src/mono/mono/mini/monovm.c:236]: Oops

File: src/mono/mono/mini/mono-private-unstable.h (hunk 1 above)
Comment (CoffeeFlux) [reply src/mono/mono/mini/mono-private-unstable.h:72]: They wouldn't need to update the code as long as they're building against the new runtime though? Unless they're declaring the struct separately instead of using our header, which we also really don't want.

Comment (grendello) [reply src/mono/mono/mini/mono-private-unstable.h:72]: The struct could have its first field to specify its own size - similar to how sockaddr works in POSIX. The caller would have to set that property and MonoVM would be able to tell the struct "version" this way. Nothing should be ever removed or rearranged, things could be added only at the end of the struct. I think it would make for nice future proofing, fully agreed with @lambdageek

Comment (CoffeeFlux) [reply src/mono/mono/mini/mono-private-unstable.h:72]: I'm confused - what scenario is the size supposed to solve here? What are we future proofing against?

As far as I know X-A no longer redeclares all the functions it uses and can just use our headers directly, and we make no ABI guarantees so you *must* build and link against the same version of Mono. Given that, your build isn't broken as long as we don't remove elements from the struct, even if we rearrange them, so what would we be future-proofing against?

I'm happy to add this sort of thing if there's a clear scenario where it would add value, but I don't see one in a net6 world.

Comment (lambdageek) [reply src/mono/mono/mini/mono-private-unstable.h:72]: How did/does the XA Shared Runtime stuff work? Does it rely on an ABI guarantee or is there some versioning built in?

**Review by lambdageek — APPROVED** [review]

File: src/mono/mono/mini/mono-private-unstable.h (hunk 1 above)
Comment (grendello) [reply src/mono/mono/mini/mono-private-unstable.h:72]: > How did/does the XA Shared Runtime stuff work? Does it rely on an ABI guarantee or is there some versioning built in?
> 
> Otherwise it does seem like there's not much need for this.

You mean the shared runtime we install on debug builds? We dropped that. As for XA proper, we link directly against `libmonosgen-2.0.so`

Comment (grendello) [reply src/mono/mono/mini/mono-private-unstable.h:72]: > I'm confused - what scenario is the size supposed to solve here? What are we future proofing against?
> 
> As far as I know X-A no longer redeclares all the functions it uses and can just use our headers directly, and we make no ABI guarantees so you _must_ build and link against the same version of Mono. Given that, your build isn't broken as long as we don't remove elements from the struct, even if we rearrange them, so what would we be future-proofing against?
> 
> I'm happy to add this sort of thing if there's a clear scenario where it would add value, but I don't see one in a net6 world.

My only worry is what happens if someone locally overrides the NET6 Mono Android runtime nugets so that Xamarin.Android applications will suddenly be **compiled** against a different version of the MonoVM runtime and running against **another** MonoVM version. In the "legacy" world we always shipped Mono with XA, so the chance for above was slim to none. In the nuget world... you never know.

Comment (CoffeeFlux) [reply src/mono/mono/mini/mono-private-unstable.h:72]: I think I've convinced myself that I'm not too worried about that scenario, and if it comes up we should have a more proper, global solution rather than trying to patch functions like this. At the end of the day, we aren't making ABI guarantees and if people are violating that, it's on them.
