### PR TITLE
Fix SampleType field in ThreadSample event from SampleProfiler

### LINKED ISSUE #123996: `SampleType` field in `ThreadSample` event  from Microsoft-DotNETCore-SampleProfiler is reported incorrectly since .NET 9
### Description

`SampleType` field in `ThreadSample` event from Microsoft-DotNETCore-SampleProfiler is supposed to report if the thread was executing a managed code when the sample was taken. It should have the value `EP_SAMPLE_PROFILER_SAMPLE_TYPE_MANAGED` in this case and `EP_SAMPLE_PROFILER_SAMPLE_TYPE_EXTERNAL` otherwise.

It was working as expected until .NET 9, but doesn't work anymore.

### Reproduction Steps

Actually, it's enough to take any application that performs active calculation in C#. We expect a majority of samples to have `SampleType == EP_SAMPLE_PROFILER_SAMPLE_TYPE_MANAGED` in this case.
As an example, https://github.com/JetBrains/DPA-demo can be taken.

Then run an EventPipe session with enabled sampling for the corresponding application, and look at `ThreadSample` event from Microsoft-DotNETCore-SampleProfiler.

### Expected behavior

A majority of samples has `SampleType == EP_SAMPLE_PROFILER_SAMPLE_TYPE_MANAGED`.

### Actual behavior

All (or almost all) samples have `SampleType == EP_SAMPLE_PROFILER_SAMPLE_TYPE_EXTERNAL`.

### Regression?

Yes, it was working as expected in .NET 8 and earlier, but doesn't work in .NET 9 and .NET 10.

### Known Workarounds

No workarounds

### Configuration

I have checked the following .NET versions:
* 8.0.15 ✅
* 9.0.12 ❌
* 10.0.2 ❌

I reproduced it on macOS 15.7.3 (aarch64), but it definitely reproduces on Linux x64 too.
I don't think that the issue relates to a specific OS, it looks like some common problem in .NET runtime 9+.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by steveisok**
Fix SampleType field in ThreadSample event from SampleProfiler
    
The SampleType field was always reporting EP_SAMPLE_PROFILER_SAMPLE_TYPE_EXTERNAL
even when threads were executing managed code. This regressed in .NET 9 when
SuspendAllThreads was ported from NativeAOT to CoreCLR (commit 00a897369db).

Instead of iterating all threads during SuspendAllThreads (which scales poorly
on many-core machines), each thread now saves its own GC mode when it
voluntarily suspends:
- In RareDisablePreemptiveGC when hitting the IsTrappingThreadsForSuspension check

This is pay-for-play: only threads that were actually executing managed code
participate, and only during suspension.

Fixes #123996

### CODE REVIEW

**Comment by noahfalk** [comment]
You need to save the state before suspension begins (or at least before the m_fPreemptiveGCDisabled field is changed during the suspension process).

File: src/coreclr/vm/threadsuspend.cpp [hunk 1]
```diff
@@ -3261,6 +3261,19 @@ void ThreadSuspend::SuspendAllThreads()
     // See VSW 475315 and 488918 for details.
     minipal_memory_barrier_process_wide();
 
+#ifdef FEATURE_PERFTRACING
+    // Save the GC mode for each thread. This must be done after the memory barrier
+    // to get a reliable reading, but before suspension changes thread states.
+    // Used by the sample profiler to determine if the thread was executing managed code.
```
Comment (jkotas) [inline src/coreclr/vm/threadsuspend.cpp]: Going through all threads and reading/writing to their thread local state scales poorly on many core machines with a lot of threads.

Can we make this pay for play and do this only when we are suspending for the event pipe sampler?

Alternatively, we can set/reset a thread local flag around `ThreadStore::IsTrappingThreadsForSuspension()` path in threadsuspend.cpp. We should hit that path only if the thread has been executing managed code.

Comment (steveisok) [reply src/coreclr/vm/threadsuspend.cpp]: I tried the alternate path you suggested. That's how I thought of it initially, but didn't quite understand how to get there. Let me know if we're on the right track.

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by lateralusX** [comment]
Just curious, so if we set the state when moving back from preemptive to cooperate suspend mode to indicate that a thread is running managed code, would that mean we would potentially report more code as being in managed depending on the time it takes to iterate over all "suspended" threads and capture their managed callstacks, checking this new flag and external code get enough time to complete and transition back into rutnime and getting trapped by  `RareDisablePreemptiveGC`?

Looking through the CoreCLR suspension code this is my understanding:

For threads already in preemptive mode, leave them running, they will eventually suspend if they are trying to re-enter runtime as part of `RareDisablePreemptiveGC`. For threads in cooperate mode, use different techniques to let them toggle GC mode, cooperate->preemptive->cooperate trapped by `RareDisablePreemptiveGC` since we are trapping threads returning to cooperate mode.

When we do CPU samples in EventPipe we first suspend all threads, then iterate over the thread list and capture managed stack traces for each thread, part of that process is also classifying if a thread was running managed or external code when suspended. But since threads already being in preemptive code will continue running, that means they might end up trying to re-enter cooperate suspend mode and getting blocked by `RareDisablePreemptiveGC` before sample profiler have got around to that thread in `walk_managed_stack_for_threads`, reporting the thread as being in managed when it actually was running external code at point of suspension.

I guess this is less of a concern since the sample profiler is just sampling and maybe previous solution didn't see difference between a thread trapped when running in cooperate mode vs trying to re-enter runtime from preemptive mode. I guess this is also a definition on when a thread sample actually occurs, in CoreCLR it means the thread sample is not the state when all threads suspended, but when the actual thread is processed by sample profilers `walk_managed_stack_for_threads` loop.

In Mono we handle this a little different, when runtime uses the full cooperate suspend model, it will do the suspension of threads moving from external code back to managed code as part of stub frame that stack walker identifies as external code, so even if the thread is trying to transition back into managed code, it will be trapped in the stub frame and stack-walker will classify that as still being in external code.

**Comment by steveisok** [comment]
I do like the current change where each thread is noting its state. If reporting more is an edge case or in the end doesn't really matter, I'd say keep the current change as is. 

@jkotas @lateralusX you guys are the experts, so whatever you prefer...

**Comment by steveisok** [comment]
/ba-g Unclear error in tvOS leg. Unrelated to PR.
