### PR TITLE
Provide ALC name in DispatchProxy for proxies in custom ALC

### LINKED ISSUE #82969: Provide ALC name in DispatchProxy for proxies in custom ALC
With https://github.com/dotnet/runtime/pull/62095 issues with proxies loaded from custom ALC is fixed and the ALC name was passed to the `AssemblyName` used for creating the Proxy type, but [that was causing issues for ALC that include paths in its name](https://github.com/dotnet/runtime/issues/80387). We reverted that part as it was causing a regression. 

Though passing ALC name to the proxy assembly could be useful for debugging purposes and @jkotas suggested a good way for fixing it in https://github.com/dotnet/runtime/pull/82807#discussion_r1125160686:

### PR DESCRIPTION
**Pull request by pedrobsaila**
Fixes #82969

### CODE REVIEW

File: src/libraries/System.Reflection/tests/AssemblyNameTests.cs [hunk 1]
```diff
@@ -86,7 +86,6 @@ public void Ctor_String_Public_Key(string name, string expectedName)
         [InlineData("", typeof(ArgumentException))]
         [InlineData("\0", typeof(ArgumentException))]
         [InlineData("\0a", typeof(ArgumentException))]
-        [InlineData("/a", typeof(FileLoadException))]
```
Comment (jkotas) [inline src/libraries/System.Reflection/tests/AssemblyNameTests.cs:89]: These tests should be replaced by positive tests

File: src/coreclr/vm/assembly.cpp [hunk 2]
```diff
@@ -397,10 +397,7 @@ Assembly *Assembly::CreateDynamic(AssemblyBinder* pBinder, NativeAssemblyNamePar
     if (pAssemblyNameParts->_pName == NULL || pAssemblyNameParts->_pName[0] == '\0')
         COMPlusThrow(kArgumentException, W("ArgumentNull_AssemblyNameName"));
 
-    if (COMCharacter::nativeIsWhiteSpace(pAssemblyNameParts->_pName[0])
-        || u16_strchr(pAssemblyNameParts->_pName, '\\') != NULL
-        || u16_strchr(pAssemblyNameParts->_pName, ':') != NULL
-        || u16_strchr(pAssemblyNameParts->_pName, '/') != NULL)
+    if (COMCharacter::nativeIsWhiteSpace(pAssemblyNameParts->_pName[0]))
```
Comment (jkotas) [inline src/coreclr/vm/assembly.cpp:400]: Delete this check as well?

**Review by jkotas — APPROVED** [review]
Thank you!
