### PR TITLE
[mono][arm64] Fixed passing/receiving hfa structures with fixed buffers.

### LINKED ISSUE #90423: Mono arm64 runtime does not correctly return structs that contain a pointer type
### Description

When returning a struct that contains a `float*` the contents are not preserved when the structure is a value type. Reference types work fine. This issue is isolated to the mono runtime on arm64 devices.

### Reproduction Steps

Build & run the following. If it runs successfully it should have no output.

```
using System;

namespace Repro_UUM_30210
{
    internal class Program
    {
        public BaconClass.BaconStruct foo;

        public unsafe Program()
        {
            foo = BaconClass.GetBacon();
            
            for (int i = 0; i < BaconClass.BaconStruct.RESOLUTION; i++)
            {
                if (Math.Abs(foo.table[i] - BaconClass.foo.table[i]) > float.Epsilon)
                    Console.WriteLine("entry: " + i + " = " + foo.table[i] + " != " +
                              BaconClass.foo.table[i]);
            }
        }
        
        
        public static void Main(string[] args)
        {
            new Program();
        }
    }

    public class BaconClass
    {
        public unsafe struct BaconStruct
        {
            public float length;
            public const int RESOLUTION = 5;
            public fixed float table[RESOLUTION];
        }
        
        public static BaconStruct foo;
        
        public unsafe static BaconStruct GetBacon()
        {
            const int resolution = BaconStruct.RESOLUTION;
            var length = 1;
            BaconStruct lut = new BaconStruct()
            {
                length = length
            };
            foo = new BaconStruct(){length = length};
		
            float[] bacon = new float[] { 1.1f, 1.2f, 1.3f, 1.4f, 1.5f };
            for (int x = 0; x < BaconStruct.RESOLUTION; x++)
            {
                lut.table[x] = bacon[x];
                foo.table[x] = bacon[x];
            }
            return lut;
        }
    }
}
```

### Expected behavior

No output (the static and passed by value tables match)

### Actual behavior

Random values are provided such as the following output:
```
entry: 1 = 3.602042E-36 != 1.2
entry: 2 = 1E-45 != 1.3
entry: 3 = 2.8520998E+26 != 1.4
entry: 4 = 1E-45 != 1.5
```

### Regression?

Unknown

### Known Workarounds

Use a reference type to pass between functions.

### Configuration

version: `8.0.100-preview.3.23178.7`
OS: Mac OSX 13.4.1
Arch: arm64

Yes it is specific to arm64, x64 on Mac and Windows is fine.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/90423.

### CODE REVIEW

File: src/mono/mono/mini/mini-arm64.c [hunk 1]
```diff
@@ -1497,16 +1498,30 @@ is_hfa (MonoType *t, int *out_nfields, int *out_esize, int *field_offsets)
...
 			int nested_field_offsets [16];
 
-			if (!is_hfa (ftype, &nested_nfields, &nested_esize, nested_field_offsets))
-				return FALSE;
+			MonoType *fixed_etype;
+			int fixed_len;
+			if (mono_marshal_shared_get_fixed_buffer_attr (field, &fixed_etype, &fixed_len)) {
+				if (fixed_etype->type != MONO_TYPE_R4 && fixed_etype->type != MONO_TYPE_R8)
+					return FALSE;
+				if (fixed_len > 16)
```
Comment (kg) [inline src/mono/mono/mini/mini-arm64.c:1506]: for it to be an HFA doesn't it need to be 2-4 items, so we need to make sure fixed_len >= (sizeof (etype) * 2)? not that a fixed array of size 1 makes sense but you could do it

Comment (kg) [reply src/mono/mono/mini/mini-arm64.c:1506]: EDIT: I see this is bounds checking against nested_field_offsets now, not against 16 / sizeof(etype)

**Review by kg — APPROVED** [review]
Looks right to me, will note however that https://learn.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=msvc-170#definitions says an HFA must have at least two values in it, but we appear to return `TRUE` from is_hfa if `nfields` is 1.
