### PR TITLE
[wasm][debugger] Breakpoint stopping after it's removed

### LINKED ISSUE #41447: When debugging a Blazor WebAssembly project, removing a breakpoint while paused then refreshing the page (while still paused) causes the breakpoint to still be hit
### Describe the bug

While paused on a breakpoint, if a user removes the breakpoint, then refreshes the page while still paused, the deleted breakpoint is still hit, and will be until the debug session is restarted (or chrome/edge devtools is closed and reopened).

### To Reproduce

Using the default Blazor template from Visual Studio,

1. Set a breakpoint in the `IncrementCount()` method in counter.razor.
2. Trigger the breakpoint by pressing the "Click Me" button on the counter page
3. While paused, delete the breakpoint set in step 1
4. While still paused, refresh the page in the browser
5. Press "Click Me" again, and see that the breakpoint is still hit even after it was removed.

BlazorBreakpointRefreshBugGif

### Further technical details

I'm able to reproduce this bug on Visual Studio, VS Code, and in Chrome/Edge devtools.

#### dotnet --info output:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20314.3 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20412.11 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20412.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by thaystg**
Remove unnecessary WriteLine.
Fixing after a breakpoint is removed and the page is refreshed the breakpoint was still stopping.
Trying to create a test.

Fixes #41447.

### CODE REVIEW

File: src/mono/wasm/debugger/DebuggerTestSuite/Support.cs [hunk 1]
```diff
@@ -852,6 +852,18 @@ internal async Task<(JToken, Result)> EvaluateOnCallFrame(string id, string expr
...
         }
 
+        internal async Task<Result> RemoveBreakpoint(string id)
+        {
+            var remove_bp = JObject.FromObject(new
+            {
+                breakpointId = id
+            });
+
+            var bp1_res = await ctx.cli.SendCommand("Debugger.removeBreakpoint", remove_bp, ctx.token);
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/Support.cs:862]: nit: `s,bp1_res,res,`

Comment (radical) [reply src/mono/wasm/debugger/DebuggerTestSuite/Support.cs:862]: Also, `Assert.True(bp1_res.IsOk, "Failed to remove breakpoint");`

File: src/mono/wasm/debugger/DebuggerTestSuite/Tests.cs [hunk 2]
```diff
@@ -1523,6 +1523,38 @@ async Task<Result> _invoke_getter(string obj_id, string property_name, bool expe
             }
         }
 
+        [Fact]
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/Tests.cs:1526]: Maybe also add a test for removing the breakpoint again, once it has already been removed?

File: src/mono/wasm/debugger/DebuggerTestSuite/Tests.cs [hunk 3]
```diff
@@ -1523,6 +1523,38 @@ async Task<Result> _invoke_getter(string obj_id, string property_name, bool expe
...
+                    "window.setTimeout(function() { invoke_add(); invoke_add()}, 1);",
+                    "dotnet://debugger-test.dll/debugger-test.cs",  10, 8,
+                    "IntAdd",
+                    wait_for_event_fn: (pause_location) =>
+                    {   
+                        Assert.Equal("other", pause_location["reason"]?.Value<string>());
+                        Assert.Equal(bp.Value["breakpointId"]?.ToString(), pause_location["hitBreakpoints"]?[0]?.Value<string>());
+                        return Task.CompletedTask;
+                    }
+                );
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/Tests.cs:1551]: We're trying to avoid too many nested calls. So, you could restructure this to be:
```csharp
                var wait_res = await EvaluateAndCheck(
                      "window.setTimeout(function() { invoke_add(); invoke_add()}, 1);",
                      "dotnet://debugger-test.dll/debugger-test.cs",  10, 8,
                      "IntAdd");

                Assert.Equal("other", wait_res["reason"]?.Value<string>());
                Assert.Equal(bp.Value["breakpointId"]?.ToString(), wait_res["hitBreakpoints"]?[0]?.Value<string>());
```

File: src/mono/wasm/debugger/DebuggerTestSuite/Tests.cs (hunk 2 above)
Comment (radical) [reply src/mono/wasm/debugger/DebuggerTestSuite/Tests.cs:1526]: And maybe a test for 1. set, hit, remove, run-don't-hit, set again, hit ?

Comment (radical) [reply src/mono/wasm/debugger/DebuggerTestSuite/Tests.cs:1526]: These don't need to block the PR, if we want to get it in today.

**Review by radical — CHANGES_REQUESTED** [review]

**Review by radical — APPROVED** [review]
Thanks for addressing the feedback! LGTM 👍

**Comment by thaystg** [comment]
@lewing , Diego asked me about when this will be released, maybe we should backport this one too?

**Comment by radical** [comment]
It's included in https://github.com/dotnet/runtime/pull/42057
