### PR TITLE
Change gtGetThisArg not to return nullptr.

### LINKED ISSUE #298: Assertion failed 'op1 != nullptr' in 'TestUtil.TestLog:VerifyOutput():int:this' during 'Morph - Global' (IL size 130)
This is a new failure that started showing up in the Pri-0 test suite.

```
>	clrjitilc.dll!Compiler::optNonNullAssertionProp_Call(unsigned __int64 * const & assertions, GenTreeCall * call) Line 3838	C++
 	clrjitilc.dll!Compiler::optAssertionProp_Call(unsigned __int64 * const & assertions, GenTreeCall * call, Statement * stmt) Line 3881	C++
 	clrjitilc.dll!Compiler::optAssertionProp(unsigned __int64 * const & assertions, GenTree * tree, Statement * stmt, BasicBlock * block) Line 4161	C++
 	clrjitilc.dll!Compiler::fgMorphTree(GenTree * tree, Compiler::MorphAddrContext * mac) Line 15507	C++
 	clrjitilc.dll!Compiler::fgMorphCast(GenTree * tree) Line 519	C++
 	clrjitilc.dll!Compiler::fgMorphSmpOp(GenTree * tree, Compiler::MorphAddrContext * mac) Line 11810	C++
 	clrjitilc.dll!Compiler::fgMorphTree(GenTree * tree, Compiler::MorphAddrContext * mac) Line 15544	C++
 	clrjitilc.dll!Compiler::fgMorphSmpOp(GenTree * tree, Compiler::MorphAddrContext * mac) Line 12465	C++
 	clrjitilc.dll!Compiler::fgMorphTree(GenTree * tree, Compiler::MorphAddrContext * mac) Line 15544	C++
 	clrjitilc.dll!Compiler::fgMorphSmpOp(GenTree * tree, Compiler::MorphAddrContext * mac) Line 12465	C++
 	clrjitilc.dll!Compiler::fgMorphTree(GenTree * tree, Compiler::MorphAddrContext * mac) Line 15544	C++
 	clrjitilc.dll!Compiler::fgMorphStmts(BasicBlock * block, bool * lnot, bool * loadw) Line 16430	C++
 	clrjitilc.dll!Compiler::fgMorphBlocks() Line 16673	C++
```

We're hitting this for code in the shape of:

```csharp
if (String.Empty.Equals(diff))
```

The problem is that `String.Empty` field is an intrinsic, so we import it specially (as a literal string), and there's super special handling for CoreRT because empty string can be referred to as IAT_VALUE (no need for an indirection like on CoreCLR):

https://github.com/dotnet/runtimelab/blob/ca9bccd956465a349bfc73a74dcbcadd5e9e03df/src/coreclr/src/jit/gentree.cpp#L6072-L6086

Note we're wrapping the literal in a GT_NOP to prevent constant folding.

We then hit the GT_NOP handling here (because this argument to the Equals method call is the GT_NOP):

https://github.com/dotnet/runtimelab/blob/dc7b1d2c942b44bcdb2fbd12727a495cf8d57d9e/src/coreclr/src/jit/gentree.cpp#L8546-L8552

And end up returning null from `gtGetThisArg` which asserts `optNonNullAssertionProp_Call`.

This error mode can probably be simulated on CoreCLR by just whacking `CEEJitInfo::emptyStringLiteral` to return `IAT_VALUE` (it would generate bad code, but the assert is hit before the code finishes generating) and compiling `String.Empty.Equals("some other string")`.

@sandreenko Would you be able to recommend the best course of action for this?

### PR DESCRIPTION
**Pull request by sandreenko**
bb0c5dc69ee: Don't wrap string literal const as nop for CoreRT.

It was probably an old workaround for another Jit bug, it is most likely fixed by now.

2ae10db1383: Change `gtGetThisArg` not to return `nullptr`.

There was only 1 case where a null return was tolerated - for a tail call marked as virtual in `optAssertionGen`.
Check this case before we call `gtGetThisArg`.

Fixes https://github.com/dotnet/runtimelab/issues/298

### CODE REVIEW

File: src/coreclr/src/jit/assertionprop.cpp [hunk 1]
```diff
@@ -2163,22 +2163,20 @@ void Compiler::optAssertionGen(GenTree* tree)
             break;
 
         case GT_CALL:
+        {
             // A virtual call can create a non-null assertion. We transform some virtual calls into non-virtual calls
             // with a GTF_CALL_NULLCHECK flag set.
-            if ((tree->gtFlags & GTF_CALL_NULLCHECK) || tree->AsCall()->IsVirtual())
+            // Ignore tail calls because they have 'this` pointer in the regular arg list and an implicit null check.
+            GenTreeCall* const call = tree->AsCall();
+            if (call->NeedsNullCheck() || (call->IsVirtual() && !call->IsTailCall()))
```
Comment (sandreenko) [inline src/coreclr/src/jit/assertionprop.cpp:2171]: In `fgMorphTailCallViaJitHelper` we clear `NeedsNullCheck`, should not we also clear `IsVirtual`?
Then this condition will be just `if (call->NeedsNullCheck() || call->IsVirtual())`

Comment (sandreenko) [reply src/coreclr/src/jit/assertionprop.cpp:2171]: @jakobbotsch could you please advise me here?

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

File: src/coreclr/src/jit/assertionprop.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/src/jit/assertionprop.cpp:2171]: Sorry I don't know. `fgMorphTailCallViaJitHelper` is the old (from before #341) tailcall mechanism used only on x86. This mechanism might be used directly for virtual calls (or VSDs), but I don't remember how the address is computed in those cases.

File: src/coreclr/src/jit/morph.cpp [hunk 2]
```diff
@@ -7783,6 +7783,12 @@ GenTree* Compiler::fgMorphTailCallViaHelpers(GenTreeCall* call, CORINFO_TAILCALL
         call->gtFlags &= ~GTF_CALL_VIRT_STUB;
```
Comment (sandreenko) [inline src/coreclr/src/jit/morph.cpp:7783]: We do it for `stub` and in my understanding for `vtable` we should do the same, let's see what ci thinks.

Comment (jakobbotsch) [reply src/coreclr/src/jit/morph.cpp:7783]: This is `fgMorphTailCallViaHelpers` which is for the new mechanism. Indeed those turn into normal direct calls always.

Comment (sandreenko) [reply src/coreclr/src/jit/morph.cpp:7783]: it looks like I will need the same fix for `fgMorphTailCallViaJitHelper`: **https://github.com/sandreenko/runtime/commit/53cea4e4038ad5b3821a7a6b3734364f71ec7514** , but I want to see if our ci catches it.

Comment (jakobbotsch) [reply src/coreclr/src/jit/morph.cpp:7783]: It looks like we remove all virtual kinds below: https://github.com/dotnet/runtime/blob/dc3101bc11eeef183b6d7c3ab38f0a13248c7783/src/coreclr/src/jit/morph.cpp#L7917-L7921

I guess this line is not required but doesn't hurt since this is where we remove the arg for virtual stubs.

Comment (sandreenko) [reply src/coreclr/src/jit/morph.cpp]: I see, thank you. I removed changes in `fgMorphTailCallViaHelpers` and fixed `fgMorphTailCallViaJitHelper` in the same way.

File: src/coreclr/src/jit/morph.cpp [hunk 3]
```diff
@@ -8435,6 +8435,10 @@ void Compiler::fgMorphTailCallViaJitHelper(GenTreeCall* call)
             thisPtr = objp;
         }
 
+        // TODO-Cleanup: we leave it as a virtual stub call to
```
Comment (sandreenko) [inline src/coreclr/src/jit/morph.cpp:8438]: I made a try to clear `GTF_CALL_VIRT_KIND_MASK ` here but it caused failures because logic in `LowerCall` depends on this flag to be set in some cases, so I reverted that change.

It would be nice to clear it and fix the failures but it is out of the scope of this bug fix for CoreRT.

**Comment by sandreenko** [comment]
ping @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]

**Comment by sandreenko** [comment]
Thanks @BruceForstall for the review!
