### PR TITLE
Fix concurrency issue with metrics gauge value collection

### LINKED ISSUE #91591: System.Diagnostics.Metrics.LastValue looks like it could experience torn reads
`LastValue`, which is used by `ObservableGauge<>`, has an `Update(double value)` method that just does:
```C#
        private double? _lastValue;

        public override void Update(double value)
        {
            _lastValue = value;
        }
```
Writing a `double` on a 32-bit platform is not guaranteed to be an atomic operation, and regardless of bitness, writing a `double?` is not guaranteed to be an atomic operation. We could thus end up in a situation where, for example, `_lastValue` reports it contains a value but the value hasn't actually been initialized, or where the reported value is an amalgum of an old value and one currently being written.

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/91591

### CODE REVIEW

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs [hunk 1]
```diff
@@ -1290,36 +1292,40 @@ public void EventSourcePublishesEndEventsOnMeterDispose()
...
+                                                new TagList() { { "ogk1", "ogv1" } });
+                Histogram<int> h = meterB.CreateHistogram<int>("histogram1", "a unit", "the description", new TagList() { { "hk1", "hv1" }, { "hk2", "" }, {"hk3", null } });
+                UpDownCounter<int> udc = meterA.CreateUpDownCounter<int>("upDownCounter1", "udc unit", "udc description", new TagList() { { "udk1", "udv1" } });
+                int upDownCounterState = 0;
+                ObservableUpDownCounter<int> oudc = meterA.CreateObservableUpDownCounter<int>("observableUpDownCounter1", () => { upDownCounterState += 11; return upDownCounterState; }, "oudc unit", "oudc description");
 
-            AssertInstrumentPublishingEventsPresent(events, c, oc, og, h, udc, oudc, g);
-            AssertInitialEnumerationCompleteEventPresent(events);
+                EventWrittenEventArgs[] events;
+                using (MetricsEventListener listener = new MetricsEventListener(NullTestOutputHelper.Instance, MetricsEventListener.InstrumentPublishing, null, "*"))
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:1320]: Is the change from "" -> "*" required to make the test work? If so that suggests we've created an unintended breaking change in the MetricsEventSource syntax and ideally we'd undo that break.

cc @CodeBlanch

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/AggregationManagerTests.cs [hunk 2]
```diff
@@ -16,6 +16,12 @@ public void GetDefaultAggregator()
 
             Assert.NotNull(val);
             Assert.Equal(val, store.GetAggregator());
+
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/tests/AggregationManagerTests.cs:19]: I think you could remove all the changes from this file. These unit tests are validating the behavior of the AggregatorStore type which should be indifferent to the type of Aggregator stored inside. Using LastValue was an arbitrary choice because I needed any type that derived from Aggregator.

**Review by noahfalk — APPROVED** [review]
Product part looked good, I think part of the tests aren't needed and potentially we had an unintended compat break on MetricsEventSource arguments.

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:1320]: I can fix this allowing empty string behave as "*" listening to all instruments. Yes, if we don't do that there will be breaking change. It took me some time trying to figure out what was the problem.

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/AggregationManagerTests.cs (hunk 2 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/tests/AggregationManagerTests.cs]: I reverted the changes in this file.

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs]: I have added the fix to allow empty string to listen to all instruments as we used to do before.

**Review by noahfalk — APPROVED** [review]
LGTM!

**Comment by sebastienros** [comment]
This PR is probably introducing some perf regression (here is one when using HttpClient in a proxy)

image

I think we should build a dedicated web app made for tracking telemetry/metrics performance (open to suggestions). It's a very important domain and its performance can be really impactful on apps. That would allow us to estimate the cost of changes, and detect regressions in related domains. We could also run this app retroactively and see if past changes have introduced changes we may have missed.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs [hunk 3]
```diff
@@ -649,6 +649,12 @@ private void ParseSpecs(string? metricsSpecs)
                     return;
                 }
 
+                if (metricsSpecs.Length == 0)
+                {
+                    _aggregationManager!.IncludeAll();
+                    return;
+                }
```
Comment (MihaZupan) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:656]: Could this be enabling all metrics in a process that was otherwise subscribed to none?

I added a simple
```c#
var meter = new Meter("TestMeter");
var testCounter = meter.CreateCounter<int>("test.testCounter");

_ = Task.Run(async () =>
{
    while (true)
    {
        await Task.Delay(1000);
        Console.WriteLine($"Enabled: {testCounter.Enabled}");
    }
});
```

into the benchmark project in question and it appears to be enabled after this change.

**Comment by tarekgh** [comment]
> Could this be enabling all metrics in a process that was otherwise subscribed to none?

This part of the change was fixing a regression occurred by other changes. When you have empty specs, it means you need to subscribe to all metrics in the process. This was the .NET 8.0 behavior. Recently, we have added the System.Runtime meter reporting metrics for different runtime areas GC, jit,....etc.

@sebastienros how is the perf test written for the regressed part? does it listen to all meters? or just listen to the concerned meter? I expect some minor hits with the Gauge instrument as we started to synchronize the collected values but shouldn't be that much. 

CC @noahfalk

**Comment by sebastienros** [comment]
> does it listen to all meters?

There could be an issue in Crank then. I will review all the arguments we pass for this specific app (it doesn't show up in other ones) and how meters are recorded.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs (hunk 3 above)
Comment (noahfalk) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:656]: Previously my understanding was that one of Blanch's changes during Preview7 had regressed this behavior and @tarekgh's change here was intended to restore the previous .NET 8 behavior. However doing some testing now, thats not what I see. What I see in my test for .NET 8 is omitting the Metrics argument did not enable any metrics.

We probably need to dig deeper and make sure we understand exactly what happened, but now it looks like this change that was intended to re-align us to .NET 8 behavior instead changed us away from .NET 8 behavior. This is my test case:

```C#
internal class Program
{
    static void Main(string[] args)
    {
        Meter m = new Meter("MyMeter");
        m.CreateObservableCounter("MyCounter", () => 1);
        MyEventListener listener = new MyEventListener();
        Console.ReadLine();
    }
}

class MyEventListener : EventListener
{
    protected override void OnEventSourceCreated(EventSource eventSource)
    {
        Console.WriteLine(eventSource.Name);
        if(eventSource.Name == "System.Diagnostics.Metrics")
        {
            EnableEvents(eventSource, EventLevel.Informational, (EventKeywords)0x7/*, new Dictionary<string,string?>() { { "Metrics", "MyMeter" } }*/);
        }
    }

    protected override void OnEventWritten(EventWrittenEventArgs eventData)
    {
        if(eventData.EventSource.Name == "System.Runtime")
        {
            return;
        }
        Console.WriteLine(eventData.EventName);
        for (int i = 0; i < eventData.Payload.Count; i++)
        {
            Console.WriteLine($"\t{eventData.PayloadNames[i]}: {eventData.Payload[i]}");
        }
    }
}
```

Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:656]: I tried this code on .NET 8.0 and I am seeing `MyMeter` get reported as expected:

```
Microsoft Windows 10.0.22631
.NET 8.0.8
System.Diagnostics.DiagnosticSource.dll 8.00.824.36612
```

```
Microsoft-Windows-DotNETRuntime
System.Runtime
System.Buffers.ArrayPoolEventSource
System.Diagnostics.Metrics
Message
        Message: New session started. SessionId auto-generated: 919cfab8-dc80-4eb5-af66-0ba09cfb9e42
Message
        Message: No RefreshInterval argument received. Using default 1s.
Message
        Message: No MaxTimeSeries argument received. Using default 1000
Message
        Message: No MaxHistograms argument received. Using default 20
Message
        Message: No Metrics argument received
InstrumentPublished
        sessionId: 919cfab8-dc80-4eb5-af66-0ba09cfb9e42
        meterName: MyMeter
        meterVersion:
        instrumentName: MyCounter
        instrumentType: ObservableCounter`1
        unit:
        description:
        instrumentTags:
        meterTags:
        meterScopeHash:
```

Comment (noahfalk) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:656]: You will always see the InstrumentPublished events for all metrics, but you won't see the CounterRatePayload events that transmit the values of the counter. Sending CounterRatePayload is what requires the AggregationManager to allocate storage.

Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:656]: I have submitted the PR https://github.com/dotnet/runtime/pull/107267 to fix the issue.
