### PR TITLE
JIT: Fix too wide loads on arm64 for small structs

### LINKED ISSUE #76194: Unsafe.ReadUnaligned causes System.AccessViolationException on Windows ARM64
Hi!

I faced with `System.AccessViolationException` when reading 5-byte structure in .NET 6 / .NET 7 RC1 / Arm64 .NET Framework 4.8.1 app on Windows ARM64, here is demo app:
```csharp
using System.IO.MemoryMappedFiles;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

class Program
{
    [StructLayout(LayoutKind.Explicit, Size = 5)]
    public struct Data
    {
        [FieldOffset(0)]
        public byte Byte;

        [FieldOffset(1)]
        public int Int;
    }
    static unsafe void Main(string[] args)
    {
        var mappedFile = MemoryMappedFile.CreateNew(null, 0x1000);
        var viewAccessor = mappedFile.CreateViewAccessor();
        byte* viewPtr = null;
        viewAccessor.SafeMemoryMappedViewHandle.AcquirePointer(ref viewPtr);
        Unsafe.InitBlock(viewPtr, 0x01, (uint)viewAccessor.Capacity);

        IntPtr viewStart = new IntPtr(viewPtr);
        IntPtr viewEnd = viewStart + (int)viewAccessor.Capacity;
        IntPtr last = viewEnd - Unsafe.SizeOf<Data>();
        Console.WriteLine($"view {viewStart:X16} - {viewEnd:X16} last {last:X16}");

        Data x = Unsafe.ReadUnaligned<Data>(last.ToPointer());
        Console.WriteLine($"{x.Byte:X} {x.Int:X}");
    }
}
```

Output:
```
view 0000023537440000 - 0000023537441000 last 0000023537440FFB
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.CompilerServices.Unsafe.ReadUnaligned[[Program+Data, Program, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](Void*)
   at Program.Main(System.String[])

...\bin\Debug\net6.0\Program.exe (process 13224) exited with code -1073741819.
```

Looks like it tries to load 8 bytes from x0:
```
System.Runtime.CompilerServices.Unsafe.dll!System.Runtime.CompilerServices.Unsafe.ReadUnaligned<T>(void*):
00007FF7F8F0CBF0  stp         fp,lr,[sp,#-0x10]!
00007FF7F8F0CBF4  mov         fp,sp
00007FF7F8F0CBF8  ldr         x0,[x0]  <-- here, x0 is 0x0000023537440FFB
00007FF7F8F0CBFC  ldp         fp,lr,[sp],#0x10
00007FF7F8F0CC00  ret
```

.NET 6.0.401
.NET 7.0.100-rc.1.22431.12
.NET Framework 4.8.1 ARM64 4.8.9093.0
Windows 11 21H2 22000.978

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/76194
using @SingleAccretion's snippet since mine was uglier. 

We've had similar issues in the past e.g. https://github.com/dotnet/runtime/pull/64683 (reproduces even on .NET Framework x64)
it's just that normally it's an extremely rare case, perhaps, still worth backporting to .NET 7.0

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @jakobbotsch @SingleAccretion

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -3654,12 +3654,27 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
...
 
         case GT_OBJ:
-            retVal->ChangeOper(GT_IND);
-            FALLTHROUGH;
         case GT_IND:
+        {
+            // Spill to a local if sizes don't match so we can avoid the "load more than requested"
+            // problem, e.g. struct size is 5 and we emit "ldr x0, [x1]"
+            unsigned realSize = retVal->OperIs(GT_OBJ) ? retVal->AsObj()->Size() : retVal->AsIndir()->Size();
+            if (genTypeSize(nativeReturnType) != realSize && realSize != 0)
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:3662]: It is still a problem if `realSize` is zero - it means there was a `GT_FIELD` node under the return, which could have also been for a small struct. To know the real size of such an `IND<struct>` you'd need to query `info.compMethodInfo->args.retTypeClass`). If you're going to go with this (instead of accepting the regression for small struct fields), it would be good to add `TODO-ADDR: delete once "IND<struct>" nodes are no more` there.

Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:3662]: Let's go with the 2nd option then

Comment (SingleAccretion) [reply src/coreclr/jit/lower.cpp:3662]: To be clear, I meant that the `&& realSize != 0` check makes it a correctness issue as-is. Something like below:
```c
SmallStruct Get(LargeStruct* p)
{
    return p->SmallStructField;
}
```
Will load out-of-bounds.

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -15725,8 +15725,18 @@ GenTree* Compiler::gtNewTempAssign(
...
+        {
+            valStructHnd = lvaGetStruct(genReturnLocal);
+        }
+        else
+        {
+            // We're spilling IND<struct> to a temp from RETURN(IND<struct>) expression
+            // TODO-ADDR: delete once "IND<struct>" nodes are no more
+            assert(genReturnLocal == BAD_VAR_NUM);
+            genReturnLocal = tmp;
+            valStructHnd   = info.compMethodInfo->args.retTypeClass;
```
Comment (SingleAccretion) [inline src/coreclr/jit/gentree.cpp:15738]: This is an ugly workaround... I would recommend doing `lvaGrabTemp + lvaSetStruct` manually instead of this (`ReplaceWithLclVar` accepts a `tempNum` parameter for this).

File: src/coreclr/jit/lower.cpp [hunk 3]
```diff
@@ -3777,12 +3777,47 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
...
         case GT_BLK:
         case GT_OBJ:
-            retVal->ChangeOper(GT_IND);
-            FALLTHROUGH;
         case GT_IND:
+        {
+            // Spill to a local if sizes don't match so we can avoid the "load more than requested"
+            // problem, e.g. struct size is 5 and we emit "ldr x0, [x1]"
+            unsigned realSize = retVal->OperIs(GT_OBJ) ? retVal->AsObj()->Size() : retVal->AsIndir()->Size();
+            CORINFO_CLASS_HANDLE structCls = NO_CLASS_HANDLE;
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:3785]:
```suggestion
            CORINFO_CLASS_HANDLE structCls = comp->info.compMethodInfo->args.retTypeClass;
```
(And corresponding change below)

We should always use a custom temp, even if we know the size, because we have `GT_BLK` indirs that will have the size but not the handle.

File: src/coreclr/jit/lower.cpp [hunk 4]
```diff
@@ -3777,12 +3777,47 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
 
         case GT_BLK:
         case GT_OBJ:
-            retVal->ChangeOper(GT_IND);
-            FALLTHROUGH;
         case GT_IND:
+        {
+            // Spill to a local if sizes don't match so we can avoid the "load more than requested"
+            // problem, e.g. struct size is 5 and we emit "ldr x0, [x1]"
+            unsigned realSize = retVal->OperIs(GT_OBJ) ? retVal->AsObj()->Size() : retVal->AsIndir()->Size();
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:3784]:
```suggestion
            unsigned realSize = retVal->AsIndir()->Size();
```

File: src/coreclr/jit/lower.cpp [hunk 5]
```diff
@@ -3777,12 +3777,47 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
...
+                realSize  = comp->info.compCompHnd->getClassSize(structCls);
+            }
+
+            if (genTypeSize(nativeReturnType) > realSize)
+            {
+                LIR::Use retValUse(BlockRange(), &ret->gtOp1, ret);
+                unsigned tmpNum = BAD_VAR_NUM;
+                if (structCls != NO_CLASS_HANDLE)
+                {
+                    tmpNum               = comp->lvaGrabTemp(true DEBUGARG("spilling IND(X)"));
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:3804]:
```suggestion
                    tmpNum               = comp->lvaGrabTemp(true DEBUGARG("mis-sized struct return"));
```
Nit: a bit clearer.

File: src/coreclr/jit/lower.cpp [hunk 6]
```diff
@@ -3777,12 +3777,47 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
...
+                }
+                ReplaceWithLclVar(retValUse, tmpNum);
+                LowerRetSingleRegStructLclVar(ret);
+                break;
+            }
+
+            if (retVal->OperIs(GT_OBJ))
+            {
+                retVal->ChangeOper(GT_IND);
+            }
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:3816]:
```suggestion
            retVal->ChangeOper(GT_IND);
```
Should work as it did before? In any case, `BLK`s also need to be turned into `IND`s.

File: src/coreclr/jit/lower.cpp [hunk 7]
```diff
@@ -3777,12 +3777,47 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
...
         case GT_IND:
+        {
+            // Spill to a local if sizes don't match so we can avoid the "load more than requested"
+            // problem, e.g. struct size is 5 and we emit "ldr x0, [x1]"
+            unsigned realSize = retVal->OperIs(GT_OBJ) ? retVal->AsObj()->Size() : retVal->AsIndir()->Size();
+            CORINFO_CLASS_HANDLE structCls = NO_CLASS_HANDLE;
+            if (realSize == 0)
+            {
+                assert(retVal->gtNext->OperIs(GT_RETURN));
+
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:3789]:
```suggestion
```
Not necessary and in principle not correct.

File: src/coreclr/jit/lower.cpp [hunk 8]
```diff
@@ -3777,12 +3777,47 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
...
+                // We have an IND<struct> node, assuming it's used in a return statement, take target size
+                // from the current method's signature (it's only used to decide whether we need to spill it to
+                // a local or not, so the actual size won't be used).
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:3792]:
```suggestion
```
I think it is fairly obvious why we need to query the signature here given the reference to `IND<struct>` below.

File: src/coreclr/jit/lower.cpp (hunk 7 above)
Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:3789]: I didn't plan to check-in it, I used it for a local spmi run 🙂

File: src/coreclr/jit/lower.cpp [hunk 9]
```diff
@@ -3777,12 +3777,41 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
...
+            if (genTypeSize(nativeReturnType) > realSize)
+            {
+                LIR::Use retValUse(BlockRange(), &ret->gtOp1, ret);
+                unsigned tmpNum = BAD_VAR_NUM;
+                if (structCls != NO_CLASS_HANDLE)
+                {
+                    tmpNum               = comp->lvaGrabTemp(true DEBUGARG("mis-sized struct return"));
+                    comp->genReturnLocal = tmpNum;
+                    comp->lvaSetStruct(tmpNum, structCls, true);
+                }
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:3804]:
```suggestion
                LIR::Use retValUse(BlockRange(), &ret->gtOp1, ret);
                unsigned tmpNum = comp->lvaGrabTemp(true DEBUGARG("mis-sized struct return"));
                comp->lvaSetStruct(tmpNum, structCls, false);
```

1) `genReturnLocal` has a very specific purpose, no reason to set it here.
2) No unsafe value class checks needed (in principle, in practice it doesn't matter) since the address of this local won't escape.

Comment (EgorBo) [reply src/coreclr/jit/lower.cpp]: > genReturnLocal has a very specific purpose, no reason to set it here.

Tests assert after this patch: Assertion failed 'tmp == genReturnLocal'

Comment (EgorBo) [reply src/coreclr/jit/lower.cpp]: I reverted some suggestions if you don't mind because we hit the path for non-structs as well so now it's cleaner that we have a special case for that rare case with IND<struct>.

Comment (SingleAccretion) [reply src/coreclr/jit/lower.cpp]: We still need to handle the case with handle-less `BLK` nodes though.

Reproduction:
```cs
struct Sx3
{
    public byte A, B, C;
}

[MethodImpl(MethodImplOptions.NoInlining)]
private static Sx3 Problem(StructWithIndex* s)
{
    Sx3 a;
    Unsafe.CopyBlock(&a, s, 3);
    return a;
}
```

Comment (EgorBo) [reply src/coreclr/jit/lower.cpp]: thanks, reverted the revert. @SingleAccretion does it look good to you? I assume it's just your change written with my hands 😄

**Review by SingleAccretion — APPROVED** [review]
Yep, looks good!

**Comment by EgorBo** [comment]
@jakobbotsch could you please take a look and sign it off?

**Review by jakobbotsch — APPROVED** [review]

**Comment by EgorBo** [comment]
LLVMAOT failure was known and already fixed in Main

File: src/coreclr/jit/lower.cpp [hunk 10]
```diff
@@ -3777,12 +3777,34 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
...
         case GT_IND:
+        {
+            // Spill to a local if sizes don't match so we can avoid the "load more than requested"
+            // problem, e.g. struct size is 5 and we emit "ldr x0, [x1]"
+            unsigned             realSize  = retVal->AsIndir()->Size();
+            CORINFO_CLASS_HANDLE structCls = comp->info.compMethodInfo->args.retTypeClass;
+            if (realSize == 0)
+            {
+                // TODO-ADDR: delete once "IND<struct>" nodes are no more
+                realSize = comp->info.compCompHnd->getClassSize(structCls);
```
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:3789]: Not that the current behavior tries to be careful in such cases, I've just tried and got an AccessViolationException in Main for it when I changed return type to int while was trying to return a small struct.

File: src/tests/JIT/Regression/JitBlue/Runtime_76194/Runtime_76194.cs [hunk 11]
```diff
@@ -0,0 +1,168 @@
...
+            const int PROT_NONE = 0x0;
+            const int PROT_READ = 0x1;
+            const int PROT_WRITE = 0x2;
+            const int MAP_PRIVATE = 0x02;
+            const int MAP_ANONYMOUS = 0x20;
+
+            _ptr = mmap(null, 2 * PageSize, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
+            if (_ptr != null && mprotect(_ptr + PageSize, PageSize, PROT_NONE) != 0)
+            {
+                munmap(_ptr, 2 * PageSize);
```
Comment (jakobbotsch) [inline src/tests/JIT/Regression/JitBlue/Runtime_76194/Runtime_76194.cs:129]: This looks like it will result in a double free

Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_76194/Runtime_76194.cs:129]: (But I doubt that's the cause of #78758)

Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_76194/Runtime_76194.cs:129]: Ah, I see the reason now:
```scala
On success, mmap() returns a pointer to the mapped area.  On
       error, the value MAP_FAILED (that is, (void *) -1) is returned,
       and [errno](https://man7.org/linux/man-pages/man3/errno.3.html) is set to indicate the error.
```

So this does not correctly check that we failed to allocate the memory.
