### PR TITLE
Resolving an antigen failure

### LINKED ISSUE #105255: Some hwintrinsic related antigen failures
A few antigen failures have shown up in https://dev.azure.com/dnceng-public/public/_build/results?buildId=749361&view=ms.vss-build-web.run-extensions-tab and should be resolved

```csharp
using System.Runtime.Intrinsics;

#nullable disable
public class TestClass
{
    private static Vector512<uint> s_v512_uint_62 = Vector512<uint>.Zero;

    public void Method0()
    {
        s_v512_uint_62 = Vector512.LessThan<uint>(s_v512_uint_62, Vector512<uint>.Zero);
        try
        {
        }
        finally
        {
            while (true) ;
        }
    }

    public static void Main(string[] args) => new TestClass().Method0();
}

/*
Assert failure(PID 5828 [0x000016c4], Thread: 6044 [0x179c]): Assertion failed '((tree->gtDebugFlags & GTF_DEBUG_NODE_MORPHED) == 0) && "ERROR: Already morphed this node!"' in 'TestClass:Method0():this' during 'Morph - Global' (IL size 22846; hash 0x46e9aa75; Tier0-FullOpts)
    File: D:\a\_work\1\s\src\coreclr\jit\morph.cpp:12227
    Image: C:\h\w\A715090A\p\CoreRoot\corerun.exe

Assertion failed '((tree->gtDebugFlags & GTF_DEBUG_NODE_MORPHED) == 0) && "ERROR: Already morphed this node!"' during 'Morph - Global'
*/
```

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #105255

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -30360,8 +30360,11 @@ GenTree* Compiler::gtFoldExprHWIntrinsic(GenTreeHWIntrinsic* tree)
 #endif // !TARGET_XARCH && !TARGET_ARM64
 
                     DEBUG_DESTROY_NODE(op, tree);
-                    INDEBUG(vectorNode->gtDebugFlags |= GTF_DEBUG_NODE_MORPHED);
 
+                    if (fgGlobalMorph)
+                    {
+                        INDEBUG(vectorNode->gtDebugFlags |= GTF_DEBUG_NODE_MORPHED);
+                    }
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:30367]: The other `INDEBUG(vectorNode->gtDebugFlags |= GTF_DEBUG_NODE_MORPHED);` are properly under `if (fgGlobalMorph)` already

File: src/coreclr/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -1570,6 +1570,21 @@ GenTree* Lowering::LowerHWIntrinsic(GenTreeHWIntrinsic* node)
...
+
+                                if (nextNode == op1)
+                                {
+                                    nextNode = nextNode->gtNext;
+                                }
+
+                                if (nextNode == user)
+                                {
+                                    nextNode = nextNode->gtNext;
+                                }
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:1586]: This isn't my favorite fix, but given where we are in .NET 9 it's probably the safest one.

The `TernaryLogic` lowering being done by looking at the `user` is already a little different compared to other lowering logic, but it's how it got introduced several months back. More ideally we'd be handling this closer to how general containment gets handled, which is looking at the operands of a node instead.

That is, rather than saying "I am a `BitwiseOper`, is the node that consumes me also a `BitwiseOper`, we should probably be saying `I am a `BitwiseOper`, are either of my operands also `BitwiseOper`.

Such handling would avoid issues like this and also allow us to more easily take into account whether the `ternarylogic` usage is "profitable" (since it may not be if the two individual nodes could have been contained, as an example).

Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp:1586]: I notably wasn't able to get a simplified repro for this either, even running through the Antigen trimmer the smallest repro it found was 2100 lines of code.

Morph and other phases normally recognize/handle the double NOT much earlier and so its not typically found in practice.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by tannergooding** [comment]
CC. @JulieLeeMSFT, this fixes a codegen issue and would be good to take for .NET 9 still

File: src/coreclr/jit/gentree.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/gentree.cpp:30367]: generally, it's enough to call `fgMorphTreeDone(vectorNode)` in these `gtFoldExpr*` apis - it will take care about `fgGlobalMorph` and the `GTF_DEBUG_NODE_MORPHED` flag (it also clears local assertionprop info, but that is important only if your function is called from morph and on an existing tree).

File: src/coreclr/jit/lowerxarch.cpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/jit/lowerxarch.cpp:1586]: I think I can understand the logic and the reason why you have to skip `op1` and `user` for gtNext (I wonder if it's possible to just mark them as UnusedValue to keep them in LIR chain and continue LIR walk normally, but probably not). 
And I agree that'd be much more natural to do this op while visiting the root XOR instead.

**Review by EgorBo — APPROVED** [review]

**Comment by tannergooding** [comment]
Confirmed over teams this is good to merge.
