### PR TITLE
Disable array support for the COM variant wrapper classes when built-in COM is disabled.

### LINKED ISSUE #55600: TypeBuilder.CreateType doesn't work on Windows in a trimmed app due to BuiltInComInterop being disabled
### Description

When trimming an app that uses Ref.Emit to generate a Type, it fails by default on Windows due to BuiltInComInterop being disabled.

Using a recent .NET 6 SDK, `dotnet publish` the following app:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
</Project>
```

```C#
using System;
using System.Reflection;
using System.Reflection.Emit;

AssemblyBuilder assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("GeneratedAssembly"), AssemblyBuilderAccess.Run);
ModuleBuilder module = assembly.DefineDynamicModule("GeneratedModule");
TypeBuilder genericType = module.DefineType("GeneratedType");
genericType.DefineField("_int", typeof(int), FieldAttributes.Private);
genericType.DefineProperty("Prop", PropertyAttributes.None, typeof(string), null);

Type generatedType = genericType.CreateType();
Console.WriteLine(generatedType);
```

```
❯ .\bin\Debug\net6.0\win-x64\publish\HelloWorld.exe
Unhandled exception. System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.DispatchWrapper' from assembly 'System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at System.Reflection.Emit.TypeBuilder.SetMethodIL(QCallModule , Int32 , Boolean , Byte[] , Int32 , Byte[] , Int32 , Int32 , ExceptionHandler[] , Int32 , Int32[] , Int32 )
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock() in System.Private.CoreLib.dll:token 0x60025e7+0x37f
   at System.Reflection.Emit.TypeBuilder.CreateType() in System.Private.CoreLib.dll:token 0x60025e6+0x11
   at <Program>$.<Main>$(String[] ) in C:\DotNetTest\HelloWorld\Program.cs:line 11
```

### Configuration

* Which version of .NET is the code running on? `.NET 6.0.0-preview5+`
* What OS and version, and what distro if applicable? `Windows`
* What is the architecture (x64, x86, ARM, ARM64)? `x64`
* Do you know whether it is specific to that configuration? `yes`

### Regression?

Yes, this worked before 6.0.0-preview5 because BuiltInComInterop wasn't disabled by default. We disable BuiltInComInterop by default starting in 6.0.0-preview5.

cc @LakshanF @agocke @vitek-karas @sbomer

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #55600

### CODE REVIEW

File: src/coreclr/vm/olevariant.cpp [hunk 1]
```diff
@@ -329,20 +329,24 @@ VARTYPE OleVariant::GetVarTypeForTypeHandle(TypeHandle type)
...
+            return VT_BSTR;
 
-    // VariantWrappers cannot be stored in VARIANT's.
-    if (CoreLibBinder::IsClass(pMT, CLASS__VARIANT_WRAPPER))
-        COMPlusThrow(kArgumentException, IDS_EE_COM_UNSUPPORTED_SIG);
+        // VariantWrappers cannot be stored in VARIANT's.
+        if (CoreLibBinder::IsClass(pMT, CLASS__VARIANT_WRAPPER))
+            COMPlusThrow(kArgumentException, IDS_EE_COM_UNSUPPORTED_SIG);
+    }
 #endif // FEATURE_COMINTEROP
```
Comment (LakshanF) [inline src/coreclr/vm/olevariant.cpp:351]: This is a more surgical fix than I was thinking and thanks for doing this!

I assume the code under the other #FEATURE_COMINTEROP in this method will not cause a problem?

Comment (jkoritzinsky) [reply src/coreclr/vm/olevariant.cpp:351]: The other ones won't cause problems.

We'll always have SafeHandle and CriticalHandle (which arrays of are always unsupported in interop).

And then the rest is based on RCW/CCW support having been used to create a wrapper, which is already blocked previously.

File: src/coreclr/vm/olevariant.cpp [hunk 2]
```diff
@@ -329,20 +329,24 @@ VARTYPE OleVariant::GetVarTypeForTypeHandle(TypeHandle type)
...
-    if (CoreLibBinder::IsClass(pMT, CLASS__BSTR_WRAPPER))
-        return VT_BSTR;
+    // The wrapper types are only available when built-in COM is supported.
+    if (g_pConfig->IsBuiltInCOMSupported())
+    {
+        if (CoreLibBinder::IsClass(pMT, CLASS__DISPATCH_WRAPPER))
+            return VT_DISPATCH;
+        if (CoreLibBinder::IsClass(pMT, CLASS__UNKNOWN_WRAPPER))
+            return VT_UNKNOWN;
+        if (CoreLibBinder::IsClass(pMT, CLASS__ERROR_WRAPPER))
```
Comment (elinor-fung) [inline src/coreclr/vm/olevariant.cpp:339]: Is there more we need to block `ArrayMarshalInfo::InitElementInfo`? For example:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/vm/mlinfo.cpp#L3866

**Review by elinor-fung — COMMENTED** [review]
@LakshanF - is there some sort of trimming test in libraries that could be added that would have caught this? (Those actually create a separate app and trim, right?)

**Comment by LakshanF** [comment]
> @LakshanF - is there some sort of trimming test in libraries that could be added that would have caught this? (Those actually create a separate app and trim, right?)

It doesn't look like we have that many library tests that have a trim mode as well. But we should do more test runs with built-in COM disabled

- I did a couple of manual CI runs with built-in COM disabled but didn't see unusual failures including reflection emit tests (I didn't comprehensively look at all failures though)
- #54523 should expand to include areas like `TypeBuilder `tests

**Comment by jkoritzinsky** [comment]
These failures only show up when the linker has run, not when the feature flag has been flipped.

**Comment by elinor-fung** [comment]
The issue here wasn't having it disabled though - it was actually trimming.

**Comment by elinor-fung** [comment]
I was talking about having/adding something for this in the tests in the `TrimmingTests` subfolders, not just tests that turn off the feature flag.

**Comment by jkoritzinsky** [comment]
It might be worth adding static constructors on these wrapper types that makes them throw when built-in COM is disabled by the feature flag.

Otherwise we can get into the following situation:

1. User uses `DispatchWrapper[]` in their code.
2. User tests their app without setting the BuiltInComSupported feature flag to `false`.
3. User trims their app with the `BuildInComSupported` feature flag kept to it's default of `false`.
4. Since user code kept the `DispatchWrapper` type around but the runtime support for the type is disabled, behavior changes (the `DispatchWrapper` object is marshalled, not the underlying object)

**Comment by jkoritzinsky** [comment]
Then again, the changed behavior is the same as the non-Windows behavior, so I'd be ok saying that it's the expected behavior.

**Comment by LakshanF** [comment]
Yes, you and @jkoritzinsky are right in that the `corelib `needs to be trimmed and we should look to expand the trimming tests under library.

I wonder though if it is possible to have a test mode in Windows where built-in COM is disabled without going the trimming route. In some sense, this is what is happening in non-Windows platforms where built-in COM is disabled and runtime 'knows' that and it doesn't ask for COM types inside the native code. Currently, Windows have both modes and runtime doesn't have a good way to distinguish that.

**Comment by eerhardt** [comment]
> something for this in the tests in the TrimmingTests subfolders

Yes, this bug was caught by our TrimmingTests - see https://github.com/dotnet/runtime/pull/55283#issuecomment-879365577.

In our current infra, we are using the 6.0-preview4 SDK which doesn't disable COM by default. In that PR, we are upgrading to 6.0-preview5 which is disabling COM by default, and exposed the bug.

So once #55283 is merged, we will have all our TrimmingTests running with COM disabled, like a normal user will be.

**Comment by eerhardt** [comment]
Can we add a new TrimmingTest that tests the repro scenario in #55600? I believe that will ensure this doesn't regress in the future.

It can be added to 

https://github.com/dotnet/runtime/tree/main/src/libraries/System.Runtime/tests/TrimmingTests

or 

https://github.com/dotnet/runtime/tree/main/src/libraries/System.Reflection.Emit/tests/TrimmingTests

**Comment by elinor-fung** [comment]
> User tests their app without setting the BuiltInComSupported feature flag to false.

If they have `PublishTrimmed=true`, the SDK should automatically set this, right? So it would only be if they don't set that?

Yeah, I was also wondering if we should make the `*Wrapper` types explicitly throw if built-in COM was disabled, but decided that having the expected behaviour with built-in COM disabled be the same as the non-Windows behaviour made sense to me.

> test mode in Windows where built-in COM is disabled without going the trimming route

I think that would basically be not setting `FEATURE_COMINTEROP` (although I'm sure it is not that clean and assorted refactoring would be needed). Unless we actually start going down the route of building/shipping/publishing different runtimes for different feature flags, I don't think it would make sense to invest in testing that way. Using the TrimmingTests seems like the right thing to me.

> Yes, this bug was caught by our TrimmingTests

Ah, missed that it was found from a test failure - glad there is some testing that hit this. I agree we should add one specifically for `TypeBuilder.CreateType`.

Maybe this is a point-in-time thing, but would it be useful to have some way to set additional runtime config / trimmer args for all the trimmer tests? Not necessarily actually checked in, but at least to be able to kick off a run with changes/defaults that aren't in the repo's SDK version yet.

**Comment by jkoritzinsky** [comment]
I've added a trimming test to validate this behavior. @eerhardt can you check that I configured it correctly?

File: src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj [hunk 3]
```diff
@@ -35,6 +35,9 @@
       as this test will ensure exceptions are using Resource keys -->
       <ExtraTrimmerArgs>--feature System.Resources.UseSystemResourceKeys true</ExtraTrimmerArgs>
     </TestConsoleAppSourceFiles>
+    <TestConsoleAppSourceFiles Include="TypeBuilderComDisabled.cs">
+      <ExtraTrimmerArgs>--feature System.Runtime.InteropServices.BuiltInComInterop.IsSupported false</ExtraTrimmerArgs>
```
Comment (agocke) [inline src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj:39]: I assume this is run against the live runtime we just built?

If so, I think we should consider moving the default feature switch configuration for the linker into the runtime and try to insert it into the SDK. That would help catch issues like this much faster than waiting for the next SDK update.

Comment (eerhardt) [reply src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj:39]: > I assume this is run against the live runtime we just built?

correct.

File: src/libraries/System.Runtime/tests/TrimmingTests/TypeBuilderComDisabled.cs [hunk 4]
```diff
@@ -0,0 +1,12 @@
...
+using System.Reflection;
+using System.Reflection.Emit;
+
+AssemblyBuilder assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("GeneratedAssembly"), AssemblyBuilderAccess.Run);
+ModuleBuilder module = assembly.DefineDynamicModule("GeneratedModule");
+TypeBuilder genericType = module.DefineType("GeneratedType");
+genericType.DefineField("_int", typeof(int), FieldAttributes.Private);
+genericType.DefineProperty("Prop", PropertyAttributes.None, typeof(string), null);
+
+Type generatedType = genericType.CreateType();
```
Comment (eerhardt) [inline src/libraries/System.Runtime/tests/TrimmingTests/TypeBuilderComDisabled.cs:11]: Can we assert something simple about the Type? Just to ensure that it works. For example, maybe create an instance of the Type, call ToString(), and ensure the string is correct.

File: src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj (hunk 3 above)
Comment (eerhardt) [reply src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj:39]: > consider moving the default feature switch configuration for the linker into the runtime and try to insert it into the SDK

I don't think that is fully worth the engineering and servicing effort of shipping "tooling" out of the runtime. The defaulting belongs in the `dotnet/sdk` IMO - that is the SDK for the runtime. It would just be great if we weren't 2-3 previews behind in the SDK we are using to build the dotnet/runtime.

Comment (vitek-karas) [reply src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj:39]: +1 on the defaults belonging to SDK. Even more so because different SDKs have different defaults.

Comment (agocke) [reply src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj:39]: In that case, is the proposal to upgrade the SDK used in runtime much more frequently? This could cause a lot of unrelated churn, and we would probably have to be on nightly builds in order to catch things quickly.

If we could somehow enable feature switches faster though, then we wouldn't be dependent on SDK updates.

Comment (eerhardt) [reply src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj:39]: > If we could somehow enable feature switches faster though

We can set feature switches in the tests, like this new test is doing. If required, we could set some feature switches for all tests. But for BuiltInCOMInterop, we will get it for free once #55283 is merged.

Here are the other switches that are defaulted based on PublishTrimmed:

https://github.com/dotnet/sdk/blob/0ce0580f222ff42a1a14eed42f01dcf2f41ea82f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L35-L45

```xml
  <PropertyGroup Condition="'$(PublishTrimmed)' == 'true' And
                            $([MSBuild]::VersionGreaterThanOrEquals($(_TargetFrameworkVersionWithoutV), '6.0'))">
    <StartupHookSupport Condition="'$(StartupHookSupport)' == ''">false</StartupHookSupport>
    <CustomResourceTypesSupport Condition="'$(CustomResourceTypesSupport)' == ''">false</CustomResourceTypesSupport>
    <EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization Condition="'$(EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization)' == ''">false</EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization>
    <EnableUnsafeBinaryFormatterSerialization Condition="'$(EnableUnsafeBinaryFormatterSerialization)' == ''">false</EnableUnsafeBinaryFormatterSerialization>
    <EnableUnsafeUTF7Encoding Condition="'$(EnableUnsafeUTF7Encoding )' == ''">false</EnableUnsafeUTF7Encoding >
    <BuiltInComInteropSupport Condition="'$(BuiltInComInteropSupport)' == ''">false</BuiltInComInteropSupport>
    <AutoreleasePoolSupport Condition="'$(AutoreleasePoolSupport)' == ''">false</AutoreleasePoolSupport>
    <EnableCppCLIHostActivation Condition="'$(EnableCppCLIHostActivation)' == ''">false</EnableCppCLIHostActivation>
    <_EnableConsumingManagedCodeFromNativeHosting Condition="'$(_EnableConsumingManagedCodeFromNativeHosting)' == ''">false</_EnableConsumingManagedCodeFromNativeHosting>
```

BuiltInCOM is definitely the most likely to cause issues across the stack (like we saw here).

Comment (eerhardt) [reply src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj:39]: @Anipik @ViktorHofer - thoughts on upgrading the SDK more frequently? preview6 shipped yesterday and we are just trying to update to preview5 now.

Comment (agocke) [reply src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj:39]: Right we could update the feature switches manually like we did here, but it seems like we would want them all to be enabled ASAP, which is why I proposed moving the feature switch code into the runtime. Otherwise it seems too easy to forget to change the tests.

File: eng/testing/linker/trimmingTests.targets [hunk 5]
```diff
@@ -68,6 +69,16 @@
...
     </ItemGroup>
 
+    <ItemGroup>
+      <_switchesAsItems Include="%(TestConsoleApps.DisabledFeatureSwitches)" Value="false" />
+      <_switchesAsItems Include="%(TestConsoleApps.EnabledFeatureSwitches)" Value="true" />
+    </ItemGroup>
+
+    <PropertyGroup>
+      <_extraTrimmerArgs>$(_extraTrimmerArgs) @(_switchesAsItems->'--feature %(Identity) %(Value)', ' ')</_extraTrimmerArgs>
+      <_runtimeHostConfigruationOptionsString>@(_switchesAsItems->'&lt;RuntimeHostConfigurationOption Include=&quot;%(Identity)&quot; Value=&quot;%(Value)&quot; /&gt;', '%0a    ')</_runtimeHostConfigruationOptionsString>
```
Comment (eerhardt) [inline eng/testing/linker/trimmingTests.targets:79]:
```suggestion
      <_runtimeHostConfigurationOptionsString>@(_switchesAsItems->'&lt;RuntimeHostConfigurationOption Include=&quot;%(Identity)&quot; Value=&quot;%(Value)&quot; /&gt;', '%0a    ')</_runtimeHostConfigurationOptionsString>
```

File: eng/testing/linker/trimmingTests.targets [hunk 6]
```diff
@@ -68,6 +69,16 @@
       <_additionalProjectSourceFiles Include="%(TestConsoleApps.AdditionalSourceFiles)" />
     </ItemGroup>
 
+    <ItemGroup>
+      <_switchesAsItems Include="%(TestConsoleApps.DisabledFeatureSwitches)" Value="false" />
+      <_switchesAsItems Include="%(TestConsoleApps.EnabledFeatureSwitches)" Value="true" />
+    </ItemGroup>
+
+    <PropertyGroup>
+      <_extraTrimmerArgs>$(_extraTrimmerArgs) @(_switchesAsItems->'--feature %(Identity) %(Value)', ' ')</_extraTrimmerArgs>
```
Comment (eerhardt) [inline eng/testing/linker/trimmingTests.targets:78]: You don't have to do this. Instead, just set `Trim=true` on the `RuntimeHostConfigurationOption` below - like we do in the SDK:

https://github.com/dotnet/sdk/blob/714082d0e96cef8c3a5f5d04a08d18baaf036f21/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L437-L440

File: eng/testing/linker/trimmingTests.targets (hunk 5 above)
Comment (elinor-fung) [reply eng/testing/linker/trimmingTests.targets:79]: 🤦

File: eng/testing/linker/trimmingTests.targets [hunk 7]
```diff
@@ -78,7 +89,8 @@
                                                  .Replace('{RuntimeIdentifier}','%(TestConsoleApps.TestRuntimeIdentifier)')
                                                  .Replace('{UseMonoRuntime}','$(UseMonoRuntime)')
                                                  .Replace('{MicrosoftNETILLinkTasksVersion}', '$(MicrosoftNETILLinkTasksVersion)')
-                                                 .Replace('{ExtraTrimmerArgs}', '%(TestConsoleApps.ExtraTrimmerArgs)')
+                                                 .Replace('{ExtraTrimmerArgs}', '$(_extraTrimmerArgs)')
+                                                 .Replace('{RuntimeHostConfigurationOptions}', '$(_runtimeHostConfigruationOptionsString)')
```
Comment (elinor-fung) [inline eng/testing/linker/trimmingTests.targets:93]:
```suggestion
                                                 .Replace('{RuntimeHostConfigurationOptions}', '$(_runtimeHostConfigurationOptionsString)')
```

File: eng/testing/linker/trimmingTests.targets (hunk 6 above)
Comment (elinor-fung) [reply eng/testing/linker/trimmingTests.targets:78]: Ah, right. Thanks - forgot about that.

File: eng/testing/linker/trimmingTests.targets (hunk 5 above)
Comment (eerhardt) [reply eng/testing/linker/trimmingTests.targets:79]: Actually, do we really need this extra layer of infrastructure? Why not just continue with the test setting `--feature` in the ExtraTrimmerArgs? That has been working so far.

Comment (elinor-fung) [reply eng/testing/linker/trimmingTests.targets]: The feature switch for built-in COM reaches across libraries and runtime, so it needs to actually be set in the runtime config properties instead of just relying on the linker to substitute on the libraries side.

(It could also make sense to make the other ones use this since I think it is closer to the SDK experience? Unless we are intentionally checking that just passing the linker args is sufficient)

Comment (eerhardt) [reply eng/testing/linker/trimmingTests.targets]: >  it needs to actually be set in the runtime config properties instead of just relying on the linker to substitute on the libraries side.

Ah, that makes sense.

> It could also make sense to make the other ones use this since I think it is closer to the SDK experience?

If you wanted to convert those other ones as well, I think that would be great.

Comment (elinor-fung) [reply eng/testing/linker/trimmingTests.targets]: I will do a follow-up to convert the others once we get this in.

File: src/libraries/System.Runtime/tests/TrimmingTests/TypeBuilderComDisabled.cs [hunk 8]
```diff
@@ -0,0 +1,28 @@
+using System;
```
Comment (eerhardt) [inline src/libraries/System.Runtime/tests/TrimmingTests/TypeBuilderComDisabled.cs:1]: copyright on new code files

**Review by eerhardt — APPROVED** [review]
Looks good. Thanks for fixing this.

**Comment by ViktorHofer** [comment]
> @Anipik @ViktorHofer - thoughts on upgrading the SDK more frequently? preview6 shipped yesterday and we are just trying to update to preview5 now.

I'm all for ingesting fresh SDK bits more frequently but it comes with a significant burden. In Tactics we agreed on that we want to depend on publicly available, singed SDK bits only when building our repositories. As we don't sign nightly builds and we don't want to force community members and us to install nightly SDKs on our machines we want to depend on publicly announced and released SDKs only which usually release on a monthly basis until a major version ships.

I discussed with @Anipik in the past that it would be great to have a validation job running which ingests newer SDK bits to detect regressions / changes that need reaction earlier. The current process is very manual and requires significant amount of work.

cc @marek-safar and @mmitche as we had a meeting for this some months ago. Unsure where we currently stand with automatically updating Arcade's SDK when a new SDK is released?

**Comment by mmitche** [comment]
There's no automatic update, and no plans to implement the necessary workflow to get it done. It looks like the last update was for p4. https://github.com/dotnet/arcade/pull/7657
