### PR TITLE
JIT: Avoid boxing ArgumentNullException.ThrowIfNull arguments in Tier-0

### LINKED ISSUE #104512: Avoid boxing ArgumentNullException.ThrowIfNull arguments in Tier-0
ArgumentNullException.ThrowIfNull can incur boxing when applied to argument of generic type. Tier-1 JIT optimizations are able to optimize this boxing in steady state, but Tier-0 JIT optimization are not. It can result into excessive allocations during startup.

> @dotnet/jit-contrib What would it take to augment Tier-0 to avoid boxing in this case?

From @AndyAyersMS: We'd have to mark the method as intrinsic and add new logic to `impBoxPatternMatch`.

More context and discussion of alternatives:

https://github.com/dotnet/runtime/pull/104504
https://github.com/dotnet/runtime/issues/82227
https://github.com/dotnet/runtime/issues/100406

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/104512

Example:
```cs
static void Test<T>(T a)
{
    ArgumentNullException.ThrowIfNull(a);
}
```
Current codegen for `Test<int>` in Tier0:
```asm
; Assembly listing for method Program:Test[int](int) (Tier0)
; Tier0 code
       push     rbp
       sub      rsp, 48
       lea      rbp, [rsp+0x30]
       xor      eax, eax
       mov      qword ptr [rbp-0x08], rax
       mov      dword ptr [rbp+0x10], ecx
       mov      rcx, 0x7FFD546561B0      ; System.Int32
       call     CORINFO_HELP_NEWSFAST
       mov      gword ptr [rbp-0x08], rax
       mov      rax, gword ptr [rbp-0x08]
       mov      ecx, dword ptr [rbp+0x10]
       mov      dword ptr [rax+0x08], ecx
       mov      rcx, gword ptr [rbp-0x08]
       mov      rdx, 0x203802095B0      ; 'a'
       call     [System.ArgumentNullException:ThrowIfNull(System.Object,System.String)]
       nop      
       add      rsp, 48
       pop      rbp
       ret     
```
New codegen for `Test<int>` in Tier0:
```asm
; Assembly listing for method Program:Test[int](int) (Tier0)
; Tier0 code
       push     rbp
       sub      rsp, 16
       lea      rbp, [rsp+0x10]
       xor      eax, eax
       mov      qword ptr [rbp-0x08], rax
       mov      dword ptr [rbp+0x10], ecx
       add      rsp, 16
       pop      rbp
       ret
```

@AndyAyersMS I hope I didn't step on your foot since it's was assigned to you, it's just that it looked trivial and I decided to file a quick fix 🙂 

In theory, we could solve this by a limitted version of inlining in tier0, but that is tricky and may regress startup time/lead to unnecessary type load events, etc.

### CODE REVIEW

**Review by AndyAyersMS — APPROVED** [review]
I was thinking we'd catch this in `impBoxPatternMatch` to avoid creating and then removing all the BOX IR, but that would require recognizing and intrinsic from its IL, which I guess could be clunky. This works too.

**Comment by AndyAyersMS** [comment]
> @AndyAyersMS I hope I didn't step on your foot since it's was assigned to you, it's just that it looked trivial and I decided to file a quick fix 🙂

No worries, I hadn't gotten around to this yet.

File: src/coreclr/jit/importercalls.cpp [hunk 1]
```diff
@@ -3786,6 +3789,32 @@ GenTree* Compiler::impIntrinsic(CORINFO_CLASS_HANDLE    clsHnd,
...
+            case NI_System_ArgumentNullException_ThrowIfNull:
+            {
+                // void ThrowIfNull(object? argument, string? paramName = null)
+                // void ThrowIfNull(object? argument, ExceptionArgument paramName)
+                assert(sig->numArgs == 2);
+                assert(sig->retType == CORINFO_TYPE_VOID);
+
+                // if we see:
+                //
+                //   ArgumentNullException_ThrowIfNull(GT_BOX(...), ...)
```
Comment (stephentoub) [inline src/coreclr/jit/importercalls.cpp:3801]: Will this work correctly for `Nullable<>`?

**Comment by EgorBo** [comment]
> I was thinking we'd catch this in `impBoxPatternMatch` to avoid creating and then removing all the BOX IR, but that would require recognizing and intrinsic from its IL, which I guess could be clunky. This works too.

The problem with that, - we'd need to do a redundant "resolveToken" call on `call`, yeah

File: src/coreclr/jit/importercalls.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp:3801]: > Will this work correctly for `Nullable<>`?

Ah, good question - it does work correctly now, but doesn't remove the boxing for e.g. `Test<int?>`, let me think

Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp:3801]: hm.. I don't see how we can easily handle Nullable<> in Tier0 unfortunately 🙁 

for non-nullable we do something like this:
```
ArgumentNullException.ThrowIfNull(BOX(val), name);
```
is transformed into:
```
_ = val; // preserve side-effects
_ = name;  // preserve side-effects
```
For Nullable it won't work, we have this:
```
ArgumentNullException.ThrowIfNull(CORINFO_HELP_BOX_NULLABLE(cls, val), name);
```
and in this case we can't remove the call - it is still needed in case if our `Nullable<T>._hasValue` is `false`. So in theory we can import it like this:
```
var valTmp = val;
var nameTmp = name;
if (!valTmp._hasValue)
    ArgumentNullException.ThrowIfNull(null, nametmp);
```
but I don't see a simple way to perform such a transformation in Tier0, it's definitely not in importer (and not in morph).
And no, we can't emit our own `CORINFO_HELP_THROW_NRE` becasue we still need to preserve `ThrowIfNull`'s behavior (e.g. it passes arg name (or ExceptionValue)).

any ideas @AndyAyersMS @jakobbotsch @dotnet/jit-contrib ?

Comment (jakobbotsch) [reply src/coreclr/jit/importercalls.cpp:3801]: You could create a `QMARK` for it?

Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp:3801]: > You could create a `QMARK` for it?

Not in `impIntrinsic` since the actual method is not yet materialized, but maybe I can do it when it is 🤔

Comment (AndyAyersMS) [reply src/coreclr/jit/importercalls.cpp:3801]: QMARK, or defer until you can create flow.

Comment (stephentoub) [reply src/coreclr/jit/importercalls.cpp:3856]: (If we can't address nullable, it's not a big deal.)

Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp:3856]: > (If we can't address nullable, it's not a big deal.)

I've already addressed 🙂

**Comment by EgorBo** [comment]
@jakobbotsch @AndyAyersMS could you please review the Nullable<> part?

**Review by AndyAyersMS — APPROVED** [review]

File: src/coreclr/jit/importercalls.cpp [hunk 2]
```diff
@@ -1528,6 +1532,69 @@ var_types Compiler::impImportCall(OPCODE                  opcode,
...
+    impStoreToTemp(boxedArgNameTmp, valueName, CHECK_SPILL_ALL);
+
+    // Change arguments to 'ThrowIfNull(null, valueNameTmp)'
+    call->gtArgs.GetUserArgByIndex(0)->EarlyNodeRef() = gtNewNull();
+    call->gtArgs.GetUserArgByIndex(1)->EarlyNodeRef() = gtNewLclvNode(boxedArgNameTmp, valueName->TypeGet());
+
+    // This is Tier0 specific, so we create a raw indir node to access Nullable<T>.hasValue field
+    // which is the first field of Nullable<T> struct and is of type 'bool'.
+    //
+    GenTree*   hasValueField = gtNewIndir(TYP_UBYTE, gtNewLclvNode(boxedValTmp, boxHelperAddrArg->TypeGet()));
```
Comment (jakobbotsch) [inline src/coreclr/jit/importercalls.cpp:1592]:
```suggestion
    static_assert_no_msg(OFFSETOF__CORINFO_NullableOfT__hasValue == 0);
    GenTree*   hasValueField = gtNewIndir(TYP_UBYTE, gtNewLclvNode(boxedValTmp, boxHelperAddrArg->TypeGet()));
```

File: src/coreclr/jit/importercalls.cpp [hunk 3]
```diff
@@ -3786,6 +3857,47 @@ GenTree* Compiler::impIntrinsic(CORINFO_CLASS_HANDLE    clsHnd,
...
+                //
+                GenTree* arg = impStackTop(1).val;
+                if (arg->OperIs(GT_BOX))
+                {
+                    impSpillSideEffects(true, CHECK_SPILL_ALL DEBUGARG("spill side effects for ThrowIfNull"));
+                    gtTryRemoveBoxUpstreamEffects(arg, BR_REMOVE_AND_NARROW);
+                    impPopStack();
+                    impPopStack();
+                    retNode = gtNewNothingNode();
+                }
```
Comment (jakobbotsch) [inline src/coreclr/jit/importercalls.cpp:3888]: Would it be harder to handle both cases from `impThrowIfNull` to keep the handling in one place?

File: src/coreclr/jit/importercalls.cpp [hunk 4]
```diff
@@ -1528,6 +1532,70 @@ var_types Compiler::impImportCall(OPCODE                  opcode,
...
+    // Now we need to spill the addr and argName arguments in the correct order
+    // to preserve possible side effects.
+    unsigned boxedValTmp     = lvaGrabTemp(true DEBUGARG("boxedVal spilled"));
+    unsigned boxedArgNameTmp = lvaGrabTemp(true DEBUGARG("boxedArg spilled"));
+    impStoreToTemp(boxedValTmp, boxHelperAddrArg, CHECK_SPILL_ALL);
+    impStoreToTemp(boxedArgNameTmp, valueName, CHECK_SPILL_ALL);
+
+    // Change arguments to 'ThrowIfNull(null, valueNameTmp)'
+    call->gtArgs.GetUserArgByIndex(0)->EarlyNodeRef() = gtNewNull();
+    call->gtArgs.GetUserArgByIndex(1)->EarlyNodeRef() = gtNewLclvNode(boxedArgNameTmp, valueName->TypeGet());
```
Comment (jakobbotsch) [inline src/coreclr/jit/importercalls.cpp:1587]:
```suggestion
    call->gtArgs.GetUserArgByIndex(0)->SetEarlyNode(gtNewNull());
    call->gtArgs.GetUserArgByIndex(1)->SetEarlyNode(gtNewLclvNode(boxedArgNameTmp, valueName->TypeGet()));
```

Maybe do a manual CSE of these `CallArg` to avoid the repeated `GetUserArgByIndex` calls?

File: src/coreclr/jit/importercalls.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp]: Moved

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/gentree.h [hunk 5]
```diff
@@ -10500,7 +10501,12 @@ inline bool GenTree::IsCnsVec() const
...
 inline bool GenTree::IsHelperCall()
 {
-    return OperGet() == GT_CALL && AsCall()->IsHelperCall();
+    return IsCall() && AsCall()->IsHelperCall();
+}
+
+inline bool GenTree::IsHelperCall(Compiler* compiler, unsigned helper)
+{
+    return IsCall() && AsCall()->IsHelperCall(compiler, helper);
 }
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.h:10510]: Looks like this ended up unused?

Comment (jakobbotsch) [reply src/coreclr/jit/gentree.h:10510]: Ah, nevermind, I see the use now.
