### PR TITLE
Fix GC hole with `rorx` instruction

### LINKED ISSUE #114445: Assert failure: !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")
pipeline: runtime-coreclr gcstress-extra
job: coreclr windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open
HardwareIntrinsics_X86_Avx512_ro.1.2 Work Item

Looks like all x64 GCStress=C JitStress=2 jobs fail

https://dev.azure.com/dnceng-public/public/_build/results?buildId=1010014&view=ms.vss-test-web.build-test-results-tab&runId=26981562&paneView=debug&resultId=170653

```
03:09:36.156 Running test: _Avx512F_ro::JIT.HardwareIntrinsics.X86._Avx512F.Program.RotateLeftInt321()
Beginning scenario: RunBasicScenario_UnsafeRead

Assert failure(PID 4200 [0x00001068], Thread: 1192 [0x04a8]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! `Object::ValidateInner'::`1'::catch$13 + 0x10B (0x00007ffb`7c5a504b)
CORECLR! CallSettingFrame_LookupContinuationIndex + 0x20 (0x00007ffb`7c4e70b0)
CORECLR! _FrameHandler4::CxxCallCatchBlock + 0x1DE (0x00007ffb`7c4e4e7e)
NTDLL! RtlCaptureContext + 0x3C3 (0x00007ffb`b978a173)
CORECLR! Object::ValidateInner + 0xE8 (0x00007ffb`7bde7588)
CORECLR! Object::Validate + 0xA1 (0x00007ffb`7bde7461)
CORECLR! TGcInfoDecoder<AMD64GcInfoEncoding>::ReportRegisterToGC + 0x1A8 (0x00007ffb`7c231358)
CORECLR! TGcInfoDecoder<AMD64GcInfoEncoding>::EnumerateLiveSlots + 0x14D2 (0x00007ffb`7c22fbc2)
CORECLR! EECodeManager::EnumGcRefs + 0x2A1 (0x00007ffb`7bcb30e1)
CORECLR! GcStackCrawlCallBack + 0x52B (0x00007ffb`7bf86b1b)
    File: D:\a\_work\1\s\src\coreclr\vm\object.cpp:638
    Image: C:\h\w\AA350926\p\corerun.exe

App Exit Code: -1073740286
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
```

### PR DESCRIPTION
**Pull request by BruceForstall**
The `rorx` instruction uses format IF_RWR_ARD_CNS. This format was not handled when killing GC refs in `emitOutputAM`.

I added other cases of register write "ARD" address mode formats to the same case as "defense in depth" -- most or all of them are probably SIMD instructions with SIMD destination registers, and won't go down this code path.

Diffs include cases in the HardwareIntrinsics tests, but also in the libraries code, for both x64 and x86.

Fixes #114445

### CODE REVIEW

**Comment by BruceForstall** [comment]
The bug was introduced with https://github.com/dotnet/runtime/pull/111778, cc @saucecontrol

**Comment by BruceForstall** [comment]
@kunalspathak @tannergooding PTAL
cc @dotnet/jit-contrib @dotnet/avx512-contrib

File: src/coreclr/jit/emitxarch.cpp [hunk 1]
```diff
@@ -15331,8 +15331,14 @@ BYTE* emitter::emitOutputAM(BYTE* dst, instrDesc* id, code_t code, CnsVal* addc)
             {
                 case IF_RWR_ARD:
```
Comment (tannergooding) [inline src/coreclr/jit/emitxarch.cpp:15332]: This and other places likely shouldn't be switching on the format at all. The `emitfmtsxarch.h` entries (https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/emitfmtsxarch.h) all have relevant flags indicating whether given registers a read, write, or read-write (tracked via `IS_INFO`).

We should probably have this be, instead:
```cpp
if (id->idIsReg1Write())
{
    emitGCregDeadUpd(id->idReg1(), dst);
}

if (id->idIsReg2Write())
{
    emitGCregDeadUpd(id->idReg2(), dst);
}
```

Technically we also define `idIsReg3Write()` and `idIsReg4Write()` for parity, but these are completely unused today and could be commented out. 

Realistically we could be centralizing these checks for all instructions in some `emitGCregDeadUpd(id, dst)` helper given we don't need to be checking specific formats at all, which seems much more robust and less error prone.

**Review by tannergooding — APPROVED** [review]
LGTM as it appears to fix the issue, but I think in general this is still error prone and could be made significantly more robust if we centralized the GC updates for all emitted instructions using the `IS_INFO` available for each `instrDesc`

**Comment by BruceForstall** [comment]
I agree that a more robust, generalized checking refactoring would be good. It also seems weird to call `emitInsCanOnlyWriteSSE2OrAVXReg` instead of just checking the register number to determine if it's a GPR or not (and it seems bad that `emitInsCanOnlyWriteSSE2OrAVXReg` has a list of instructions that might write GPRs, which it already has a comment about generalizing).
