### PR TITLE
#76881 internal properties in GetRuntimeProperties are not shown

### LINKED ISSUE #76881: [Android] Inherited internal properties are not returned via reflection
### Description

Issue started from https://github.com/xamarin/xamarin-android/issues/7445

Type.GetRuntimeProperties(), Type.GetProperties(..), etc. don't return internal properties that are defined in a base class of the given type when running on net6.0-android. When I run the same code as a net6.0 console application or a Xamarin.Android app, the properties are correctly returned.

### Reproduction Steps

1. Create a new .NET 6 Android application. Add the code below and run the `Test.Execute` method.

```
    public static class Test
    {
        public static void Execute()
        {
            var obj = new Class2();
            var properties = obj.GetType().GetRuntimeProperties();

            var names = properties.Select(x => x.Name).ToList();
            Console.WriteLine($"Found {names.Count} properties: {string.Join(", ", names)}");

            // Xamarin.Android: Found 2 properties: TestProp2, TestProp1
            // net6.0:          Found 2 properties: TestProp2, TestProp1
            // net6.0-android:  Found 1 properties: TestProp2
        }
    }

    public class Class1
    {
        internal int TestProp1 { get; set; }
    }

    public class Class2 : Class1
    {
        internal int TestProp2 { get; set; }
    }
```

### Expected behavior

The sample should produce `Found 2 properties: TestProp2, TestProp1` as output

### Actual behavior

The output produces `Found 1 properties: TestProp2`

### Regression?

In terms of migrating from xamarin-android to .net android, yes.

### Known Workarounds

_No response_

### Configuration

net6-android, VS 2022 17.3.5

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mkhamoyan**
Type.GetRuntimeProperties(), Type.GetProperties(..), etc. don't return internal properties that are defined in a base class of the given type when running on net6.0-android. When running the same code as a net6.0 console application or a Xamarin.Android app, the properties are correctly returned.

Fix #76881

### CODE REVIEW

File: src/mono/mono/metadata/icall.c [hunk 1]
```diff
@@ -4106,9 +4106,7 @@ ves_icall_RuntimeType_GetPropertiesByName_native (MonoQCallTypeHandle type_handl
 		g_hash_table_insert (properties, prop, prop);
 	}
 	if (!(bflags & BFLAGS_DeclaredOnly) && (klass = m_class_get_parent (klass))) {
-		// BFLAGS_NonPublic should be excluded for base classes
-		bflags &= ~BFLAGS_NonPublic;
```
Comment (mdh1418) [inline src/mono/mono/metadata/icall.c:4110]: The rationale for excluding this flag on base classes previously, does it no longer apply anymore?
Does the test `System.Reflection.Tests.TypeTests_HiddenTestingOrder.HideDetectionHappensAfterPrivateInBaseClassChecks` still pass then? `BFLAGS_NonPublic` was being unset here https://github.com/mono/mono/pull/14449 to fix that test.

Comment (mkhamoyan) [reply src/mono/mono/metadata/icall.c:4110]: It was passing locally, waiting for CI to see.

Comment (mdh1418) [reply src/mono/mono/metadata/icall.c:4110]: I dont think it will run on CI for Android, it seems like only runtime tests are ran right now. https://github.com/dotnet/runtime/pull/77280 is looking to change that.

Comment (mdh1418) [reply src/mono/mono/metadata/icall.c:4110]: Looks like the test suite System.Reflection.Tests is disabled on Android on CI right now because of crashes in the past. 

I think if we remove this, it would make this condition https://github.com/dotnet/runtime/blob/bbcff6bc422da3d9b1904281a86014236ce50f2e/src/mono/mono/metadata/icall.c#L4075 always true (since we will never make the bit 0 and it will be set to 1 in the beginning of the function). So we might be able to clean up some things like remove https://github.com/dotnet/runtime/blob/1c265ec2e006c569e538792a65bcef77146af8e6/src/mono/mono/metadata/icall.c#L4035-L4036 and collapsing https://github.com/dotnet/runtime/blob/1c265ec2e006c569e538792a65bcef77146af8e6/src/mono/mono/metadata/icall.c#L4075-L4076 into just 
```
else if (property_accessor_nonpublic(prop->get, startklass == klass) ||
				property_accessor_nonpublic(prop->set, startklass == klass)) {
				match++;
			} 
```

From what I've seen, I'm not actually sure why "`BFLAGS_NonPublic` should be excluded for base classes" was the fix for `HideDetectionHappensAfterPrivateInBaseClassChecks` as the current test does not have base classes with non public properties.

Comment (mkhamoyan) [reply src/mono/mono/metadata/icall.c:4110]: I'm also not sure why we need to exclude non public properties for base class as initial issue was that private properties in subclasses can hide public properties with the same name in Parents, and bflags &= ~BFLAGS_NonPublic will hide ALL non-public base class props.

**Review by mdh1418 — APPROVED** [review]
Looks good to me, assuming `System.Reflection.Tests.TypeTests_HiddenTestingOrder.HideDetectionHappensAfterPrivateInBaseClassChecks` (or whichever test [this](https://github.com/mono/mono/pull/14449) fixes) passes (hoping the suite doesn't crash)

**Comment by steveisok** [comment]
@mkhamoyan when you want to run android tests only, you can `/azp run runtime-android` and `/azp run runtime-androidemulator`.

**Comment by steveisok** [comment]
@mkhamoyan There's a crash in the system.reflection suite when the runtime tries to load an assembly. Can you try running the whole suite locally and see if you can reproduce?  If you can, try and print out the assembly it's trying to load before it errors out.

**Comment by mkhamoyan** [comment]
> @mkhamoyan There's a crash in the system.reflection suite when the runtime tries to load an assembly. Can you try running the whole suite locally and see if you can reproduce? If you can, try and print out the assembly it's trying to load before it errors out.

It shows "assembly_preload_hook: UnloadableAssembly  /data/user/0/net.dot.System.Reflection.Tests/files". 
In mono_assembly_open filename is /data/user/0/net.dot.System.Reflection.Tests/files/UnloadableAssembly.dll.

**Review by vargaz — APPROVED** [review]

**Review by thaystg — APPROVED** [review]

**Review by steveisok — APPROVED** [review]

**Comment by ivanpovazan** [comment]
@steveisok @mkhamoyan looking at the changes this PR introduced, it seems it also fixed: https://github.com/dotnet/runtime/issues/86149 (and other duplicates) 
Is this change going to be backported to net7 ?

**Comment by steveisok** [comment]
@ivanpovazan Yes, I think we should backport it.

**Comment by ivanpovazan** [comment]
Thanks.
Let me doublecheck locally if it would fix the issue before backporting.

**Comment by mkhamoyan** [comment]
> @mkhamoyan verified locally with `release/7.0-staging` branch that this change fixes #86149
> 
> should we backport it to `release/7.0` or `release/7.0-staging` ?

Thanks. `release/7.0-staging ` should be.
