### PR TITLE
JIT: Remove tailcall "has GC safe point" assert

### LINKED ISSUE #122481: Assertion failed 'comp->compCurBB->HasFlag(BBF_GC_SAFE_POINT) || comp->fgFirstBB->HasFlag(BBF_GC_SAFE_POINT)' in 'Newtonsoft.Json.JsonTextReader:ReadStringValue(int):System.Object:this' during 'Lowering nodeinfo'
Failed pipeline: [runtime-coreclr jitstress](https://dev.azure.com/dnceng-public/public/_build?definitionId=109&_a=summary)/[20251211.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1228532)

Failed test
```
coreclr windows x86 Checked tailcallstress @ Windows.10.Amd64.Open
coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT.performance Work Item
```

Error Message
```
Assert failure(PID 4112 [0x00001010], Thread: 3120 [0x0c30]): Assertion failed 'comp->compCurBB->HasFlag(BBF_GC_SAFE_POINT) || comp->fgFirstBB->HasFlag(BBF_GC_SAFE_POINT)' in 'Newtonsoft.Json.JsonTextReader:ReadStringValue(int):System.Object:this' during 'Lowering nodeinfo' (IL size 770; hash 0x5112c1c6; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\lower.cpp:3529
    Image: C:\h\w\B3950A3B\p\corerun.exe

App Exit Code: -1073740286
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
```

Stack trace
```
03379bfc 7363121b coreclr!FailFastOnAssert+0x21
0337ac84 7383deff coreclr!_DbgBreakCheck+0x335
*** WARNING: Unable to verify checksum for clrjit.dll
0337acfc 71b14666 coreclr!CEEInfo::doAssert+0x7f
0337cd2c 71bee49f clrjit!assertAbort+0xe2
0337cd74 71bea5bb clrjit!Lowering::LowerTailCallViaJitHelper+0x12d
0337cda0 71beb8a9 clrjit!Lowering::LowerCall+0x276
0337cdbc 71bea27d clrjit!Lowering::LowerNode+0x5ca
0337cdd4 71be7694 clrjit!Lowering::LowerBlock+0x6b
0337ce00 71c25592 clrjit!Lowering::DoPhase+0xa4
0337ce34 71afe440 clrjit!Phase::Run+0x42
0337d2e8 71affb5d clrjit!Compiler::compCompile+0xa89
0337d360 71afeee4 clrjit!Compiler::compCompileHelper+0x6ed
(Inline) -------- clrjit!Compiler::compCompileAfterInit::__l136::__Body::Run+0x12
...
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
`BBF_GC_SAFE_POINT` is not kept up to date so we cannot reliably assert this. The assert was already disabled for fast tailcalls for that reason, so remove it from there and from JIT helper based tailcalls as well.

Fix #122481

### CODE REVIEW

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -3612,6 +3606,52 @@ GenTree* Lowering::LowerTailCallViaJitHelper(GenTreeCall* call, GenTree* callTar
...
+        {
+            return true;
+        }
+
+        if (visitBlock->HasFlag(BBF_GC_SAFE_POINT))
+        {
+            continue;
+        }
+
+        block->VisitAllSuccs(comp, [&](BasicBlock* succ) {
```
Comment (jakobbotsch) [inline src/coreclr/jit/lower.cpp]:
```suggestion
        visitBlock->VisitAllSuccs(comp, [&](BasicBlock* succ) {
```

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/lower.h [hunk 2]
```diff
@@ -198,6 +198,7 @@ class Lowering final : public Phase
     GenTree* LowerDirectCall(GenTreeCall* call);
     GenTree* LowerNonvirtPinvokeCall(GenTreeCall* call);
     GenTree* LowerTailCallViaJitHelper(GenTreeCall* callNode, GenTree* callTarget);
+    bool     IsBlockReachableWithoutGCSafePoint(BasicBlock* block);
```
Comment (jakobbotsch) [inline src/coreclr/jit/lower.h]:
```suggestion
```
