### PR TITLE
Make initialization more consistent in `gc.cpp`

### LINKED ISSUE #75893: Remove redundant initialization to keep consistent style
In https://github.com/dotnet/runtime/pull/74363, an inconsistency was introduced in `gc.cpp` with respect to initialization. This inconsistency is related to use of `{}` vs `memset`. This was done to remove UB with using `memset` on non-trivial types, in this case containing a user defined constructor. This introduced a regression due to how some constructors were defined, but also introduced inconsistent style. We should remove this inconsistency since these fields are static anyways and will be properly initialized during library load.

```c++
    last_ephemeral_gc_info = {};
    last_full_blocking_gc_info = {};
#ifdef BACKGROUND_GC
    memset (&last_bgc_info, 0, sizeof (last_bgc_info));
#endif //BACKGROUND_GC
```

/cc @dotnet/gc

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Use `= default;` for `class Volatile` ctor since it permits the compiler to optimize when used in a static context. This also makes the previously troublesome UB issue fixed in https://github.com/dotnet/runtime/pull/74363 no longer exist - calling `memset` on a non-trivial type. Reverting some of the changes in `gc.cpp`.

Fixes #75893 

/cc @Maoni0 @dotnet/gc

### CODE REVIEW

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -295,9 +295,9 @@ size_t gc_heap::bgc_tuning::gen1_index_last_bgc_start;
 size_t gc_heap::bgc_tuning::gen1_index_last_bgc_sweep;
 size_t gc_heap::bgc_tuning::actual_num_gen1s_to_trigger;
 
-gc_heap::bgc_tuning::tuning_calculation gc_heap::bgc_tuning::gen_calc[2];
-gc_heap::bgc_tuning::tuning_stats gc_heap::bgc_tuning::gen_stats[2];
-gc_heap::bgc_tuning::bgc_size_data gc_heap::bgc_tuning::current_bgc_end_data[2];
+gc_heap::bgc_tuning::tuning_calculation gc_heap::bgc_tuning::gen_calc[] = {};
```
Comment (mangod9) [inline src/coreclr/gc/gc.cpp:298]: feels like explicit array sizes are better for readability, no?

Comment (AaronRobinsonMSFT) [reply src/coreclr/gc/gc.cpp:298]: They are redundant in this case. I mentioned that above and I can put them back if that is preferred.

Comment (Maoni0) [reply src/coreclr/gc/gc.cpp:298]: I also think using explicit sizes makes it more readable :)

just making sure - 
if I only do 
`gc_heap::bgc_tuning::tuning_calculation gc_heap::bgc_tuning::gen_calc[2];`
means `memset` will be called on memory `gen_calc[2]` occupies (or some other form of zeroing will happen to make this memory zeroed)

`gc_heap::bgc_tuning::tuning_calculation gc_heap::bgc_tuning::gen_calc[2] = {};`
means it also calls constructors?

Comment (AaronRobinsonMSFT) [reply src/coreclr/gc/gc.cpp:298]: > I also think using explicit sizes makes it more readable :)

Okay, will put back.

> if I only do
gc_heap::bgc_tuning::tuning_calculation gc_heap::bgc_tuning::gen_calc[2];
means memset will be called on memory gen_calc[2] occupies (or some other form of zeroing will happen to make this memory zeroed)

> if I do
gc_heap::bgc_tuning::tuning_calculation gc_heap::bgc_tuning::gen_calc[2] = {};
means it also calls constructors?

The C++ `{}` is defined as "uniform initialization" - see [3](https://en.cppreference.com/w/cpp/language/initialization). It exists because it should always do the "right thing". Because these fields are declared at global scope they will be initialized properly, both will call the default constructor. This means the `= {};` isn't needed, it simply conveys they are being initialized and could be copied as is in a local context and mean the same thing. I can remove them because they aren't needed, but they convey the intent which I generally prefer.

**Review by mangod9 — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@Maoni0 and I spoke offline. Since this PR is also making `class Volatile` have a compiler generated default ctor so we can now use `memset` on instances. I reverted changes to GC code from https://github.com/dotnet/runtime/pull/74363.

**Review by Maoni0 — APPROVED** [review]
thanks so much @AaronRobinsonMSFT. this looks great!

**Comment by AaronRobinsonMSFT** [comment]
Shoot. It seems I missed something when creating a small repro outside of dotnet/runtime and my "fix" wasn't complete. The `class Volatile` also has a user-defined copy-constructor - ugh. There is only one use of it in `gc.cpp` on 20140:

```cpp
gc_mechanisms temp_settings = settings;
```

I'll see what I can do tomorrow.

**Comment by Maoni0** [comment]
new changes look good to me. thanks @AaronRobinsonMSFT!
