### PR TITLE
JIT: Use sentinel arg to clear error register pre-Swift call

### LINKED ISSUE #99414: [jitstressregs] Interop/Swift/SwiftErrorHandling/SwiftErrorHandling fails
Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=588357&view=results
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-99093-merge-3e961c67e325430c8b/Interop/1/console.dcc96f17.log?helixlogtype=result

```
BEGIN EXECUTION
/tmp/helix/working/A16108B8/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true SwiftErrorHandling.dll ''
[createdump] Gathering state for process 61532 
[createdump] Crashing thread 40c016 signal 11 (000b)
[createdump] Writing crash report to file /cores/coredump.61532.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /cores/coredump.61532.dmp
[createdump] Written 360276104 bytes (87958 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 6660ms
Expected: 100
Actual: 139
END EXECUTION - FAILED
```

FYI @amanasifkhalid cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #99414. By adding a well-known zero argument to Swift calls with error handling that is always passed via the error register, we can get the JIT to clear the error register before the call, and also prevent the function address from being passed in the error register.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
@jakobbotsch PTAL, thanks!

File: src/coreclr/jit/lsrabuild.cpp [hunk 1]
```diff
@@ -885,9 +885,7 @@ regMaskTP LinearScan::getKillSetForCall(GenTreeCall* call)
 #ifdef SWIFT_SUPPORT
     // Swift calls that throw may trash the callee-saved error register,
     // so don't use the register post-call until it is consumed by SwiftError.
-    // GTF_CALL_M_SWIFT_ERROR_HANDLING indicates the call has a SwiftError* argument,
-    // so the error register value will eventually be consumed post-call.
-    if ((call->gtCallMoreFlags & GTF_CALL_M_SWIFT_ERROR_HANDLING) != 0)
+    if (call->HasSwiftErrorHandling())
```
Comment (jakobbotsch) [inline src/coreclr/jit/lsrabuild.cpp:888]: If this ends up being expensive TP wise you can add some handling in `AddedWellKnownArg` to make it cheaper.

File: src/coreclr/jit/gentree.h [hunk 2]
```diff
@@ -5221,6 +5218,15 @@ struct GenTreeCall final : public GenTree
         return (gtFlags & GTF_CALL_INLINE_CANDIDATE) != 0;
     }
 
+#ifdef SWIFT_SUPPORT
+    bool HasSwiftErrorHandling()
+    {
+        // Most calls aren't Swift calls, so short-circuit this check by checking the calling convention first.
+        return (unmgdCallConv == CorInfoCallConvExtension::Swift) &&
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.h:5225]: Accessing `unmgdCallConv` here is UB when that's not the active union member, so this probably needs a few other checks.

File: src/coreclr/jit/lsrabuild.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lsrabuild.cpp:888]: I guess it'll be cheap with the check for the calling convention in `HasSwiftErrorHandling`

Comment (amanasifkhalid) [reply src/coreclr/jit/lsrabuild.cpp:888]: Yeah, I don't think this will be too expensive in the general case, though if we want to speed up the Swift error handling case, I can add some new state to `CallArgs` to avoid the lookup.

Comment (amanasifkhalid) [reply src/coreclr/jit/lsrabuild.cpp:888]: Actually, updating this state in `AddedWellKnownArg` would probably affect TP in the general case, so maybe it's best to leave the unusual case slower than it could be, if it means the general case is untouched.

**Comment by amanasifkhalid** [comment]
[jitstressregs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=594079&view=results) passed. Gonna push a trivial revision.

File: src/coreclr/jit/gentree.h [hunk 3]
```diff
@@ -4785,6 +4785,10 @@ class CallArgs
     // Updateable flag, set to 'true' after we've done any required alignment.
     bool m_alignmentDone : 1;
 #endif
+#ifdef SWIFT_SUPPORT
+    // True if we are calling a Swift method that may throw.
+    bool m_hasSwiftErrorHandling : 1;
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.h:4790]: Was the other approach costing TP, or why are we going with this?

I would follow the pattern in `AddedWellKnownArg` instead, unless it really turns out to be costly. I think the consistency and correct-by-construction handling is preferable.

Comment (jakobbotsch) [reply src/coreclr/jit/gentree.h:4790]: (But I liked your initial approach. I don't think the iteration of the args for swift calls is a problem.)

Comment (amanasifkhalid) [reply src/coreclr/jit/gentree.h:4790]: > Was the other approach costing TP, or why are we going with this?

The cost of that approach was trivial, though I realized we check if a call uses Swift error handling in a few places where the call may be managed, so we'd have to call `GetUnmanagedCallConv` instead of checking `unmgdCallConv` directly to avoid UB. Considering we already use this `AddedWellKnownArg` state handling in a few places, it seemed cleaner to just copy that approach.

> I would follow the pattern in AddedWellKnownArg instead, unless it really turns out to be costly. I think the consistency and correct-by-construction handling is preferable.

Got it, fixed.

File: src/coreclr/jit/gentree.cpp [hunk 4]
```diff
@@ -1730,6 +1733,11 @@ void CallArgs::AddedWellKnownArg(WellKnownArg arg)
         case WellKnownArg::RetBuffer:
             m_hasRetBuffer = true;
             break;
+#ifdef SWIFT_SUPPORT
+        case WellKnownArg::SwiftError:
+            m_hasSwiftErrorHandling = true;
+            break;
+#endif // SWIFT_SUPPORT
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.cpp:1740]: `RemovedWellKnownArg` should also be updated.

File: src/coreclr/jit/gentree.h (hunk 3 above)
Comment (jakobbotsch) [reply src/coreclr/jit/gentree.h:4790]: `AddedWellKnownArg` is used just to improve performance. If we can avoid introducing extra state to maintain and there is no discernable TP cost of it, then I think we should do that.

Comment (amanasifkhalid) [reply src/coreclr/jit/gentree.h:4790]: I checked the TP impact locally, and the `AddedWellKnownArg` actually seems to be a bit more costly in the general case (~0.01-0.02% impact versus 0.07%). Even with the additional branch in `HasSwiftErrorHandling` from the call to `GetUnmanagedCallConv`, that seems like the way to go. I'll revert to it.

**Review by jakobbotsch — APPROVED** [review]
