### PR TITLE
Annotate System.ServiceModel.Syndication for trimming and AOT

### LINKED ISSUE #65218: MissingRuntimeArtifactException on ServiceModel.Syndication.SyndicationFeed.Load
### Description

I got:
```
System.Reflection.MissingRuntimeArtifactException
  HResult=0x8013151A
  Message=Cannot retrieve a MethodInfo for this delegate because the method it targeted (System.ServiceModel.Syndication.SyndicationFeedFormatter.DefaultUriParser(XmlUriData, Uri&)) was not enabled for metadata using the Dynamic attribute. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=616868
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

on Load:
```
            Using oReader As Xml.XmlReader = Xml.XmlReader.Create(New IO.StringReader(sPage))
                oRssFeed = ServiceModel.Syndication.SyndicationFeed.Load(oReader)
            End Using
```

I tried it with nuget 4.5.0, 5.0.0, 6,0,0,, and 6.0.2-mauipre.1.22054.8.
It happens only when building as Release, doesn't happen in Debug build.
Initially, this Load was in Class Library .Net Standard 2,0; as it has errors, I moved it into normal UWP app. But error persist.
I also tried to switch off "Enable optimizations" in project options, "Compile", "Advanced Compile Options".

### Reproduction Steps

See above.

### Expected behavior

Ability to build Release version.

### Actual behavior

See above.

### Regression?

_No response_

### Known Workarounds

Using RSS from UWP, but I want to use RSS in Class Library, and reuse it in both Platform Uno and MAUI project

### Configuration

Both in Class Library .Net Standard 2.0 and in standard UWP app.
Microsoft Windows [Version 10.0.19044.1526]
Architecture x86

### Other information

_No response_

### LINKED ISSUE #113990: IL2067 shown when publishing NativeAOT app with System.ServiceModel.Syndication in use
### Description

When publishing an app with System.ServiceModel.Syndication added and used inside it (loading a simple feed is enough) it will trigger the IL2067 trim warning.

### Reproduction Steps

```cs
using System.ServiceModel.Syndication;
using System.Xml;

namespace TestApp;

public sealed class RssFeedService
{
    public void GetFeeds()
    {
        using XmlReader reader = XmlReader.Create("someRssFeed");
        SyndicationFeed feed = SyndicationFeed.Load(reader);
    }
}
```

### Expected behavior

No Trim Warning visible when publishing the app.

### Actual behavior

ILC: Trim analysis warning IL2067:
System.ServiceModel.Syndication.SyndicationFeedFormatter.CreateFeedInstance(Type): 'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Activator.CreateInstance(Type)'.
The parameter 'feedType' of method 'System.ServiceModel.Syndication.SyndicationFeedFormatter.CreateFeedInstance(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

.NET Version: 9.0.3 with SDK 9.0.201
OS: Windows 11 Pro 26120.3585
Arch: x64
Only occurs when trimming is active (aka published with NAOT)

### Other information

Possibly related to https://github.com/dotnet/runtime/issues/75480

### PR DESCRIPTION
**Pull request by reflectronic**
Despite the closeness of this library to XML and WCF, the reflection usage in this library is nicely cordoned off and mostly limited to convenience methods. Thus, the library is largely trimming-compatible.

Fixes https://github.com/dotnet/runtime/issues/113990, https://github.com/dotnet/runtime/issues/65218
Contributes to https://github.com/dotnet/runtime/issues/75480

### CODE REVIEW

File: src/libraries/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/SyndicationElementExtension.cs [hunk 1]
```diff
@@ -41,20 +42,24 @@ public SyndicationElementExtension(XmlReader xmlReader)
...
         }
 
+        [RequiresUnreferencedCode(SyndicationFeedFormatter.RequiresUnreferencedCodeWarning)]
         public SyndicationElementExtension(string outerName, string outerNamespace, object dataContractExtension)
             : this(outerName, outerNamespace, dataContractExtension, null)
         {
         }
 
+        [RequiresUnreferencedCode(SyndicationFeedFormatter.RequiresUnreferencedCodeWarning)]
         public SyndicationElementExtension(string outerName, string outerNamespace, object dataContractExtension, XmlObjectSerializer dataContractSerializer)
```
Comment (reflectronic) [inline src/libraries/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/SyndicationElementExtension.cs:63]: `DataContractSerializer`'s constructor is not `RequiresUnreferencedCode`, but all of the methods on it are. Technically, since this method just creates a `DataContractSerializer` without using it, the method doesn't need `RequiresUnreferencedCode`. 

But, since `WriteTo` uses that `DataContractSerializer` instance, removing the attribute from here would just move it to `WriteTo`.

If you use the constructor taking `XmlReader`, there is no serializer involved, and `WriteTo` will be perfectly trim-compatible. So, I think it's better to leave the attribute on this constructor, since `DataContractSerializer` is not trim-compatible anyway. That way, the path in `WriteTo` which uses the serializer is unreachable, as long as you use trim-compatible constructors.

Does that make sense?

File: src/libraries/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/SyndicationElementExtension.cs [hunk 2]
```diff
@@ -109,6 +118,8 @@ public string OuterName
 
         public string OuterNamespace
         {
+            [UnconditionalSuppressMessage("Trimming", "IL2026:RequiresUnreferencedCode", Justification = "Constructors not marked RequiresUnreferencedCode always set _outerName to a non-null value.")]
+            [UnconditionalSuppressMessage("AOT", "IL3050:RequiresDynamicCode", Justification = "Constructors not marked RequiresUnreferencedCode always set _outerName to a non-null value.")]
             get
             {
                 if (_outerName == null)
```
Comment (reflectronic) [inline src/libraries/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/SyndicationElementExtension.cs:125]: Since this path is statically reachable, I suspect the linker will keep around bits of `XmlSerializer` and `DataContractSerializer`, even though it's never dynamically reachable from an app with no trim warnings. Is that right? Is there something simple we can do about it?

Comment (teo-tsirpanis) [reply src/libraries/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/SyndicationElementExtension.cs:125]: You can split the `ExtensionDataWriter` nested class into a base abstract class (or interface) and a concrete implementation, and create the latter only in the trim-unsafe constructors.

**Comment by StephenMolloy** [comment]
I believe this would also address #65218.

File: src/libraries/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/SyndicationElementExtension.cs (hunk 2 above)
Comment (reflectronic) [reply src/libraries/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/SyndicationElementExtension.cs:129]: On second thought, since `ExtensionDataWriter` is never instantiated from unannotated methods, its methods don't need to be kept. So, there's no concern here.

**Review by StephenMolloy — APPROVED** [review]
Added some dynamic-access attributes that weren't as obvious when the PR was first created. Looks good now.

File: src/libraries/System.ServiceModel.Syndication/ref/System.ServiceModel.Syndication.cs [hunk 3]
```diff
@@ -98,6 +100,7 @@ public AtomPub10ServiceDocumentFormatter() { }
         public AtomPub10ServiceDocumentFormatter(TServiceDocument documentToWrite) { }
         protected override System.ServiceModel.Syndication.ServiceDocument CreateDocumentInstance() { throw null; }
     }
+    [System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembersAttribute(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]
```
[the remark this answers is not in the document]
Comment (StephenMolloy) [reply src/libraries/System.ServiceModel.Syndication/ref/System.ServiceModel.Syndication.cs:103]: Yes, `CategoriesDocument` itself is abstract with an internal constructor - nobody will instantiate it directly. But the attribute isn't about the base class; it's about establishing the contract for the hierarchy. The concrete types `InlineCategoriesDocument` and `ReferencedCategoriesDocument` do have public parameterless constructors, and any other custom subtype must too because `AtomPub10CategoriesDocumentFormatter` calls `Activator.CreateInstance()` on types derived from `CategoriesDocument`.

**Review by mangod9 — APPROVED** [review]
