### PR TITLE
Fix x64 and x86 emulation on arm64 Windows

### LINKED ISSUE #71856: Emulated x86 and x64 .NET 7 on ARM64 can't create new project
### Description

The ARM64 version of .NET 7 preview 5 seems to work well, but even following the Hello World instructions does not work for the x86 and x64 versions when running on ARM64.

The x86 version hits an error and bails out when trying to create a new console app:

> Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_AccessViolationException

The x64 version instead hangs on running dotnet restore (with a CPU core spinning endlessly):

> The template "Console App" was created successfully.
> 
> Processing post-creation actions...
> Running 'dotnet restore' on C:\Users\Marc\source\repos\MyAppx64\MyAppx64.csproj...

### Reproduction Steps

1. Install x86 or x64 dotnet 7 sdk on Windows on Arm
2. Confirm the architecture of dotnet with dotnet --info
3. dotnet new console -o MyApp -f net7.0

### Expected behavior

Expected behavior is documented at https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Actual behavior

The x86 version:

> C:\Users\Marc\source\repos>dotnet new console -o MyAppX86 -f net7.0
> The template "Console App" was created successfully.
> 
> Processing post-creation actions...
> Running 'dotnet restore' on C:\Users\Marc\source\repos\MyAppX86\MyAppX86.csproj...
> Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_AccessViolationException
>    at System.Environment.FailFast(System.String)
>    at System.SR.InternalGetResourceString(System.String)
>    at System.SR.GetResourceString(System.String)
>    at System.AccessViolationException..ctor()
>    at System.SR.InternalGetResourceString(System.String)
>    at System.SR.GetResourceString(System.String)
>    at System.AccessViolationException..ctor()
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadPack(Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadPackId, Utf8JsonStreamReader ByRef)
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadPacks(Utf8JsonStreamReader ByRef)
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadManifest(System.String, System.String, LocalizationCatalog, Utf8JsonStreamReader ByRef)
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadManifest(System.String, System.IO.Stream, System.IO.Stream, System.String)
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(Microsoft.NET.Sdk.WorkloadManifestReader.IWorkloadManifestProvider)
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(Microsoft.NET.Sdk.WorkloadManifestReader.IWorkloadManifestProvider, System.String, System.String, System.String)
>    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(System.String, System.String, System.String, System.String)
>    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(Microsoft.Build.Framework.SdkReference, Microsoft.Build.Framework.SdkResolverContext, Microsoft.Build.Framework.SdkResultFactory)
>    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(System.Collections.Generic.IList`1<Microsoft.Build.Framework.SdkResolver>, Int32, Microsoft.Build.Framework.SdkReference, Microsoft.Build.BackEnd.Logging.LoggingContext, Microsoft.Build.Construction.ElementLocation, System.String, System.String, Boolean, Boolean, Microsoft.Build.BackEnd.SdkResolution.SdkResult ByRef)
>    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdkUsingResolversWithPatternsFirst(Int32, Microsoft.Build.Framework.SdkReference, Microsoft.Build.BackEnd.Logging.LoggingContext, Microsoft.Build.Construction.ElementLocation, System.String, System.String, Boolean, Boolean)
>    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32, Microsoft.Build.Framework.SdkReference, Microsoft.Build.BackEnd.Logging.LoggingContext, Microsoft.Build.Construction.ElementLocation, System.String, System.String, Boolean, Boolean)
>    at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService+<>c__DisplayClass3_0.<ResolveSdk>b__2()
>    at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(System.Threading.LazyThreadSafetyMode)
>    at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(System.LazyHelper, Boolean)
>    at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
>    at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
>    at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.ResolveSdk(Int32, Microsoft.Build.Framework.SdkReference, Microsoft.Build.BackEnd.Logging.LoggingContext, Microsoft.Build.Construction.ElementLocation, System.String, System.String, Boolean, Boolean)
>    at Microsoft.Build.BackEnd.SdkResolution.MainNodeSdkResolverService.ResolveSdk(Int32, Microsoft.Build.Framework.SdkReference, Microsoft.Build.BackEnd.Logging.LoggingContext, Microsoft.Build.Construction.ElementLocation, System.String, System.String, Boolean, Boolean)
>    at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(System.String, Microsoft.Build.Construction.ProjectImportElement, System.Collections.Generic.List`1<Microsoft.Build.Construction.ProjectRootElement> ByRef, Microsoft.Build.BackEnd.SdkResolution.SdkResult ByRef, Boolean)
>    at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExpandAndLoadImports(System.String, Microsoft.Build.Construction.ProjectImportElement, Microsoft.Build.BackEnd.SdkResolution.SdkResult ByRef)
>    at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].EvaluateImportElement(System.String, Microsoft.Build.Construction.ProjectImportElement)
>    at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement)
>    at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Evaluate()
>    at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Evaluate(Microsoft.Build.Evaluation.IEvaluatorData`4<System.__Canon,System.__Canon,System.__Canon,System.__Canon>, Microsoft.Build.Evaluation.Project, Microsoft.Build.Construction.ProjectRootElement, Microsoft.Build.Evaluation.ProjectLoadSettings, Int32, Microsoft.Build.Collections.PropertyDictionary`1<Microsoft.Build.Execution.ProjectPropertyInstance>, Microsoft.Build.BackEnd.Logging.ILoggingService, Microsoft.Build.Evaluation.IItemFactory`2<System.__Canon,System.__Canon>, Microsoft.Build.Evaluation.IToolsetProvider, Microsoft.Build.Evaluation.ProjectRootElementCacheBase, Microsoft.Build.Framework.BuildEventContext, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService, Int32, Microsoft.Build.Evaluation.Context.EvaluationContext, Boolean)
>    at Microsoft.Build.Execution.ProjectInstance.Initialize(Microsoft.Build.Construction.ProjectRootElement, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.String, System.String, Int32, Microsoft.Build.Execution.BuildParameters, Microsoft.Build.BackEnd.Logging.ILoggingService, Microsoft.Build.Framework.BuildEventContext, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService, Int32, System.Nullable`1<Microsoft.Build.Evaluation.ProjectLoadSettings>, Microsoft.Build.Evaluation.Context.EvaluationContext)
>    at Microsoft.Build.BackEnd.BuildRequestConfiguration+<>c__DisplayClass60_0.<LoadProjectIntoConfiguration>b__0()
>    at Microsoft.Build.BackEnd.BuildRequestConfiguration.InitializeProject(Microsoft.Build.Execution.BuildParameters, System.Func`1<Microsoft.Build.Execution.ProjectInstance>)
>    at Microsoft.Build.BackEnd.BuildRequestConfiguration.LoadProjectIntoConfiguration(Microsoft.Build.BackEnd.IBuildComponentHost, Microsoft.Build.Execution.BuildRequestDataFlags, Int32, Int32)
>    at Microsoft.Build.BackEnd.RequestBuilder+<BuildProject>d__68.MoveNext()
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Build.BackEnd.RequestBuilder+<BuildProject>d__68, Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<BuildProject>d__68 ByRef)
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.Build.BackEnd.RequestBuilder+<BuildProject>d__68, Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<BuildProject>d__68 ByRef)
>    at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()
>    at Microsoft.Build.BackEnd.RequestBuilder+<BuildAndReport>d__59.MoveNext()
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Build.BackEnd.RequestBuilder+<BuildAndReport>d__59, Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<BuildAndReport>d__59 ByRef)
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Build.BackEnd.RequestBuilder+<BuildAndReport>d__59, Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<BuildAndReport>d__59 ByRef)
>    at Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()
>    at Microsoft.Build.BackEnd.RequestBuilder+<RequestThreadProc>d__58.MoveNext()
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Build.BackEnd.RequestBuilder+<RequestThreadProc>d__58, Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<RequestThreadProc>d__58 ByRef)
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Build.BackEnd.RequestBuilder+<RequestThreadProc>d__58, Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<RequestThreadProc>d__58 ByRef)
>    at Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(Boolean)
>    at Microsoft.Build.BackEnd.RequestBuilder.<StartBuilderThread>b__53_2()
>    at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
>    at System.Threading.Tasks.Task+<>c.<.cctor>b__273_0(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
>    at System.Threading.Tasks.Task.ExecuteEntry()
>    at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
>    at Microsoft.Build.BackEnd.RequestBuilder+DedicatedThreadsTaskScheduler.<InjectThread>b__6_0()
>    at System.Threading.Thread+StartHelper.Callback(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Threading.Thread.StartCallback()

The x64 version:

> C:\Users\Marc\source\repos>dotnet new console -o MyAppx64 -f net7.0
> The template "Console App" was created successfully.
> 
> Processing post-creation actions...
> Running 'dotnet restore' on C:\Users\Marc\source\repos\MyAppx64\MyAppx64.csproj...

Followed by endless spinning of dotnet.exe using one core:

image

This is on a 3-core VM.  On 8-core device it uses 12-15% CPU.

### Regression?

This works with the released version of .NET 6.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by janvorli**
The runtime was hanging or crashing when running on x64 and x86
emulation on Windows ARM64. Most of these failures were caused by
missing cache flushes after code updates where the emulator kept
executing arm64 code that it has jitted from the previous state of
the code.

There were also two `CONTEXT` related issues. One was that we were
assuming that AVX state is always supported. However, the emulator
doesn't support it, so `SetXStateFeaturesMask(pCtx, XSTATE_MASK_AVX)`
was failing and we have considered that a failure to capture thread
context.
The other one was that we have assumed that the `CONTEXT` we get in
`Thread::RedirectCurrentThreadAtHandledJITCase` is `CONTEXT_COMPLETE`,
but with the emulation, we one get `CONTEXT_FULL`, that means
`CONTEXT_COMPLETE` without the debug registers.

There were also two CoreCLR tests issues that caused failures under the
emulation, I have fixed those.

Close #71856

### CODE REVIEW

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -12996,7 +12996,7 @@ PCODE UnsafeJitFunction(PrepareCodeConfig* config,
         //DbgPrintf("Jitted Entry at" FMT_ADDR "method %s::%s %s size %08x\n", DBG_ADDR(nativeEntry),
         //          pszDebugClassName, pszDebugMethodName, pszDebugMethodSignature, sizeOfCode);
 
-        ClrFlushInstructionCache(nativeEntry, sizeOfCode);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:12999]: Do we need to fix the implementation of `ClrFlushInstructionCache` instead?

Comment (janvorli) [reply src/coreclr/vm/jitinterface.cpp:12999]: That would be too big hammer. Almost all usages of it don't require flushing of cache on intel.

Comment (janvorli) [reply src/coreclr/vm/jitinterface.cpp:12999]: Btw, this is needed only because we reuse code heap memory for dynamic methods. It took me a while to figure it out.

File: src/coreclr/vm/amd64/jitinterfaceamd64.cpp [hunk 2]
```diff
@@ -296,6 +296,7 @@ int WriteBarrierManager::ChangeWriteBarrierTo(WriteBarrierType newWriteBarrier,
     {
         ExecutableWriterHolder<void> writeBarrierWriterHolder(GetWriteBarrierCodeLocation((void*)JIT_WriteBarrier), GetCurrentWriteBarrierSize());
         memcpy(writeBarrierWriterHolder.GetRW(), (LPVOID)GetCurrentWriteBarrierCode(), GetCurrentWriteBarrierSize());
+        stompWBCompleteActions |= SWB_ICACHE_FLUSH;
```
Comment (jkotas) [inline src/coreclr/vm/amd64/jitinterfaceamd64.cpp:299]: It sounds like `SWB_ICACHE_FLUSH` is required on all write barrier updates now. Are there any situations where it is not required/set?

File: src/coreclr/vm/jitinterface.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp:12999]: > Almost all usages of it don't require flushing of cache on intel.

So it soft flush can be only used in places where the code was never executed before. I think that we have more of those, for example `Precode::Reset` should use also use the hard flush.

Would it make sense to add `bool codeNeverExecutedBefore` argument to `ClrFlushInstructionCache` and switch all places to call `ClrFlushInstructionCache` with the right true/false argument? We can then audit it more easily. Also, it would allow us to centralize the policy and do things like only do the hard flushes when emulating if it has material overhead.

File: src/coreclr/vm/amd64/jitinterfaceamd64.cpp (hunk 2 above)
Comment (janvorli) [reply src/coreclr/vm/amd64/jitinterfaceamd64.cpp:299]: It is needed whenever we change the code of the barrier. So for this `ChangeWriteBarrierTo`, it is needed always, because we always switch the write barrier kind. Only the `WriteBarrierManager::UpdateEphemeralBounds` and `WriteBarrierManager::UpdateWriteWatchAndCardTableLocations` have it optional, since if the bounds and barrier kind doesn't change, there is no code change.

I am actually considering making most of these changes conditional on W^X enabled. Since without W^X enabled, things work fine even with the emulation. That's because the emulator doesn't see the connection between the write location and execute location.

I just wonder - why were we flushing the instruction cache for some of the changes, but not for all of them before?

Comment (jkotas) [reply src/coreclr/vm/amd64/jitinterfaceamd64.cpp:299]: > WriteBarrierManager::UpdateEphemeralBounds and WriteBarrierManager::UpdateWriteWatchAndCardTableLocations have it optional, since if the bounds and barrier kind doesn't change, there is no code change.

`UpdateEphemeralBounds` and `UpdateWriteWatchAndCardTableLocations ` will change immediates baked into the code. The emulator JIT has to flush the caches and rejit the code.

Comment (jkotas) [reply src/coreclr/vm/amd64/jitinterfaceamd64.cpp:299]: > I just wonder - why were we flushing the instruction cache for some of the changes, but not for all of them before?

This is not the first time we are trying to make the updateable code work on some sort of emulator. Some of the existing hard flushes are left-overs from the earlier efforts.

Comment (janvorli) [reply src/coreclr/vm/amd64/jitinterfaceamd64.cpp:299]: Ah, makes sense

Comment (janvorli) [reply src/coreclr/vm/amd64/jitinterfaceamd64.cpp:299]: > UpdateEphemeralBounds and UpdateWriteWatchAndCardTableLocations will change immediates baked into the code. The emulator JIT has to flush the caches and rejit the code.

Only if the limits really change. That's not always the case.

**Comment by janvorli** [comment]
@jkotas btw, we could also just disable W^X when we detect emulation (like we do on Rosetta) instead of all these changes. I just felt it was worth the effort to find and fix the real culprits.

File: src/coreclr/vm/threadsuspend.cpp [hunk 3]
```diff
@@ -2877,7 +2877,7 @@ BOOL Thread::RedirectThreadAtHandledJITCase(PFN_REDIRECTTARGET pTgt)
     // This should not normally fail.
     // The system silently ignores any feature specified in the FeatureMask
     // which is not enabled on the processor.
-    bRes &= SetXStateFeaturesMask(pCtx, XSTATE_MASK_AVX);
+    SetXStateFeaturesMask(pCtx, XSTATE_MASK_AVX);
```
Comment (VSadov) [inline src/coreclr/vm/threadsuspend.cpp:2880]: Did this actually return a failure?

Comment (VSadov) [reply src/coreclr/vm/threadsuspend.cpp:2880]: I think the actual implementation would filter the mask with available features and then apply, thus it would not fail for unavailable features. 
 Maybe that is different under the emulation.

Comment (janvorli) [reply src/coreclr/vm/threadsuspend.cpp:2880]: Yes, it always returned `FALSE` and `GetLastError` returned `ERROR_INVALID_PARAMETER`.

**Review by jkotas — APPROVED** [review]
LGTM
