### PR TITLE
Avoid reporting frozen segments in GetGenerationBounds

### LINKED ISSUE #87834: [ProfilerAPI] Different reserved region sizes reported for frozen segment
### Description

I see different region reserved sizes for the same frozen segment reported by `GetGenerationBounds` (`type=soh2` in log) and `GetNonGCHeapBounds` (`type=foh` in log) calls:
```
0000449C 1 0000027202149FE0 GG::Heaps c=7
	#0 type=poh  base=0000027280000028 size=0000000000003FF0 reservedSize=0000000001FFFFD8 objectSizeAlignment=8
	#1 type=loh  base=0000027282C00028 size=0000000000050820 reservedSize=0000000001FFFFD8 objectSizeAlignment=8
	#2 type=soh2 base=0000027202170008 size=0000000000007020 reservedSize=00000000003FFFF8 objectSizeAlignment=8 // <=== here
	#3 type=soh2 base=0000027282800028 size=00000000000151B8 reservedSize=00000000003FFFD8 objectSizeAlignment=8
	#4 type=soh1 base=0000027282000028 size=0000000000000000 reservedSize=00000000003FFFD8 objectSizeAlignment=8
	#5 type=soh0 base=0000027284C00028 size=000000000010B0A0 reservedSize=00000000003FFFD8 objectSizeAlignment=8
	#6 type=foh  base=0000027202170008 size=0000000000007020 reservedSize=0000000000400000 objectSizeAlignment=8 // <=== here
```

### Reproduction Steps

Application to reproduce the issue:
```
Console.WriteLine("Hello, World!");
Console.ReadLine();
```

### Expected behavior

`base=0000027202170008 size=0000000000007020 reservedSize=00000000003FFFF8`

### Actual behavior

`base=0000027202170008 size=0000000000007020 reservedSize=0000000000400000`

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

.NET 8.0-preview.5
Windows 10 Pro 22H2 x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by cshung**
Fixes dotnet/runtime#87834

- Avoid reporting the frozen segments through `GetGenerationBounds`, this would be a duplicate with `GetNonGCHeapBounds`.

- Reporting a slightly reduced value for `reservedLength` in `GetNonGCHeapBounds` to be consistent with `GetGenerationBounds`

- Avoid reporting the `GCGenerationBounds` event for frozen segments.

- Rename the `GCHeapCollect` keyword to `ManagedHeapCollect`.

Would love to merge this PR if there is no issue with the current code - customers are starting to notice the bug - if we found anything additional that will increase the scope of this PR we can address them later before .net 8.

### CODE REVIEW

File: src/tests/profiler/native/nongcheap/nongcheap.cpp [hunk 1]
```diff
@@ -59,11 +60,14 @@ HRESULT NonGcHeapProfiler::GarbageCollectionFinished()
 
     _garbageCollections++;
 
+    std::vector<ULONG> segment_starts;
+    std::vector<ULONG> segment_ends;
     const int MAX_NON_GC_HEAP_SEGMENTS = 16;
-    COR_PRF_NONGC_HEAP_RANGE segments[MAX_NON_GC_HEAP_SEGMENTS];
+    COR_PRF_NONGC_HEAP_RANGE frozen_segments[MAX_NON_GC_HEAP_SEGMENTS];
```
Comment (noahfalk) [inline src/tests/profiler/native/nongcheap/nongcheap.cpp:66]:
```suggestion
    COR_PRF_NONGC_HEAP_RANGE nongc_segments[MAX_SEGMENTS];
```

File: src/tests/profiler/native/nongcheap/nongcheap.cpp [hunk 2]
```diff
@@ -59,11 +60,14 @@ HRESULT NonGcHeapProfiler::GarbageCollectionFinished()
...
+    COR_PRF_GC_GENERATION_RANGE normal_segments[MAX_NON_GC_HEAP_SEGMENTS];
```
Comment (noahfalk) [inline src/tests/profiler/native/nongcheap/nongcheap.cpp:67]:
```suggestion
    COR_PRF_GC_GENERATION_RANGE gc_segments[MAX_SEGMENTS];
```

File: src/tests/profiler/native/nongcheap/nongcheap.cpp [hunk 3]
```diff
@@ -59,11 +60,14 @@ HRESULT NonGcHeapProfiler::GarbageCollectionFinished()
 
     _garbageCollections++;
 
+    std::vector<ULONG> segment_starts;
+    std::vector<ULONG> segment_ends;
     const int MAX_NON_GC_HEAP_SEGMENTS = 16;
```
Comment (noahfalk) [inline src/tests/profiler/native/nongcheap/nongcheap.cpp:65]:
```suggestion
    const int MAX_SEGMENTS = 16;
```

File: src/tests/profiler/native/nongcheap/nongcheap.cpp [hunk 4]
```diff
@@ -77,28 +81,84 @@ HRESULT NonGcHeapProfiler::GarbageCollectionFinished()
...
             {
                 printf("GetNonGCHeapBounds: rangeStart is null");
                 _failures++;
             }
+            segment_starts.emplace_back((ULONG)frozen_segments[i].rangeStart);
+            segment_ends.emplace_back((ULONG)frozen_segments[i].rangeStart + (ULONG)frozen_segments[i].rangeLengthReserved);
         }
         printf("\n");
     }
+    hr = pCorProfilerInfo->GetGenerationBounds(MAX_NON_GC_HEAP_SEGMENTS, &segCount, normal_segments);
```
Comment (noahfalk) [inline src/tests/profiler/native/nongcheap/nongcheap.cpp:108]: I'm guessing we already have other tests that validate GetGenerationBounds() in isolation (@davmason probably knows better exactly what is tested). It seems like the valuable new invariant to test for is confirming that GetGenerationBounds() and GetNonGCHeapBounds() aren't both enumerating the same region of memory.

File: src/coreclr/vm/proftoeeinterfaceimpl.cpp [hunk 5]
```diff
@@ -7667,7 +7670,7 @@ HRESULT ProfToEEInterfaceImpl::GetNonGCHeapBounds(ULONG cObjectRanges,
             ranges[segIdx].rangeStart = (ObjectID)firstObj;
 
             // Total size reserved for a segment
-            ranges[segIdx].rangeLengthReserved = (UINT_PTR)segments[segIdx]->m_Size;
+            ranges[segIdx].rangeLengthReserved = (UINT_PTR)segments[segIdx]->m_Size - sizeof(ObjHeader);
```
Comment (noahfalk) [inline src/coreclr/vm/proftoeeinterfaceimpl.cpp:7673]: segments[segIdx]->m_Size isn't the size of the reserved memory region?

File: src/coreclr/gc/gcee.cpp [hunk 6]
```diff
@@ -62,6 +62,11 @@ void GCHeap::ReportGenerationBounds()
     {
         g_theGCHeap->DiagDescrGenerations([](void*, int generation, uint8_t* rangeStart, uint8_t* rangeEnd, uint8_t* rangeEndReserved)
         {
+            // TODO: What shall we do with the GCGenerationRange event with frozen segments?
```
Comment (noahfalk) [inline src/coreclr/gc/gcee.cpp:65]: The model that we are presenting to users is that these segments are not part of the GC so I would not expect them to be emitted in a GCGenerationRange event. I'd suggest we define a new event that triggers when the nongc segments are first allocated.

File: src/coreclr/gc/gcee.cpp [hunk 7]
```diff
@@ -451,6 +456,7 @@ segment_handle GCHeap::RegisterFrozenSegment(segment_info *pseginfo)
     heap_segment_used(seg) = heap_segment_allocated(seg);
     heap_segment_plan_allocated(seg) = 0;
 #ifdef USE_REGIONS
+    // TODO - that can be interesting
```
Comment (noahfalk) [inline src/coreclr/gc/gcee.cpp:459]: I have no idea what this comment is intended to convey, but if it makes sense to GC team it won't matter to me.

**Review by noahfalk — COMMENTED** [review]
Thanks Andrew!

**Comment by noahfalk** [comment]
> Do we want to set heap_segment_gen_num of a frozen segment to be INT32_MAX?

Thats fine by me.

> What do we want to do with the GCGenerationRange event?

We should not emit non-gc segments from a GCGenerationRange event, it doesn't match the abstraction we are trying to present to users.

File: src/coreclr/vm/proftoeeinterfaceimpl.cpp (hunk 5 above)
Comment (cshung) [reply src/coreclr/vm/proftoeeinterfaceimpl.cpp:7673]: ### Synopsis
This change is meant to be consistent with the inaccurate convention that already exists in `GetGenerationBounds`. 

### Root Cause Explained
The real problem is that `GetGenerationBounds` always report a number that is less than the actual reserved memory.

Here is how a segment/region is typically described in the GC.

```
heap_segment_reserved  <- the end address of the reservation
...
heap_segment_allocated <- the end of the last object in the segment/region
...
heap_segment_mem       <- where it points to the first object
...
unnamed                <- where the memory reservation actually starts
```

> As usual, higher means bigger address.

When we report the segments through `DiagDescrGenerations`, we reported

`heap_segment_mem`, `heap_segment_allocated` and `heap_segment_reserved` as `rangeStart`, `rangeEnd` and `rangeEndReserved` respectively.

Therefore when `GetGenerationBounds` reported the `rangeLengthReserved` as `rangeEndReserved - rangeStart`, it is not actually reporting the full memory reservation range, instead, the distance between `heap_segment_mem` and `unnamed` is omitted.

That length is variable depending on build flavor and runtime switches. It must at least allow for the object header to stay, but it also needs to fit some other GC needs. For example, the GC reserves a whole page there in case we are in segments with background GC enabled, or it could be `sizeof(aligned_plug_and_gap)` in case of regions to store relocation information.

For frozen segments created by `FrozenObjectHeap`, it doesn't need anything else but the object header, so the slack space between `unnamed` and `heap_segment_reserved` is exactly `sizeof(ObjHeader)`.

### Engineering trade-offs 
An alternative approach, obviously, is to fix `GetGenerationBounds`, and I chose not to. The mistake is actually consistently made in multiple places. Obviously, this also impacts the `GCGenerationBounds` event, but the mistake is also made through the DAC as well. Making fixes in all these places is a much bigger risk to take.

Yet another alternative is to ignore that. In which we risk inconsistency with what the DAC already reported.

The inaccuracies were probably always there since the beginning. It was initially reported as https://github.com/dotnet/diagnostics/issues/3482. The issue is currently closed. The fix is to adjust those values by the consumer of the DAC APIs. I expect if the profiler needs the exact number, they can do the same.

It is unfortunate that we chose to live with inaccuracies, but if we have to, let's at least be consistent.

File: src/coreclr/gc/gcee.cpp (hunk 6 above)
Comment (noahfalk) [reply src/coreclr/gc/gcee.cpp:65]: > The more interesting part of this is that in order for the generation-aware analysis to work in PerfView, we need the ranges for the frozen segments

What is the dependency there? My understanding is that prior .NET 8 frozen segments were unused (aside from select special-case customers) so I wouldn't have expected any dependency to be there.

File: src/coreclr/vm/proftoeeinterfaceimpl.cpp (hunk 5 above)
Comment (noahfalk) [reply src/coreclr/vm/proftoeeinterfaceimpl.cpp:7673]: I see, m_size is the size but firstObject wasn't the true start of the range. Got it.

File: src/coreclr/gc/gcee.cpp (hunk 6 above)
Comment (cshung) [reply src/coreclr/gc/gcee.cpp:65]: > What is the dependency there? My understanding is that prior .NET 8 frozen segments were unused (aside from select special-case customers) so I wouldn't have expected any dependency to be there.

Generation Aware analysis depended on being able to determine the generation of every object it enumerates from the heap. Currently, it does so using the GCGenerationRange events.

It would be bad if heap enumeration comes up with an object that is not within any range. So either we have a range event for the frozen segments so that we can resolve its generation, or we make sure that the ETW-based heap enumeration skips frozen objects. In the latter case, PerfView will not be aware of the frozen object, and that may or may not be sufficient, I don't know for sure yet.

Comment (noahfalk) [reply src/coreclr/gc/gcee.cpp:65]: > So either we have a range event for the frozen segments so that we can resolve its generation, or we make sure that the ETW-based heap enumeration skips frozen objects. In the latter case, PerfView will not be aware of the frozen object, and that may or may not be sufficient, I don't know for sure yet.

Given that the keyword is called `GCHeapCollectKeyword` and the model we are presenting to users is that objects in the nongc segments are not part of the GC heap then I'd say we shouldn't be enumerating nongc objects there. If needed in the future we could add a NonGCHeapCollectKeyword that has its own enumeration events.

Comment (cshung) [reply src/coreclr/gc/gcee.cpp:65]: Overall it is a good idea. However, it is legal (and expected) to have objects in the GC heap referencing objects in the NonGC heap. Not sure how exactly we can split them cleanly.

Comment (noahfalk) [reply src/coreclr/gc/gcee.cpp:65]: I think you could either pretend the references aren't present, assume references to out-of-bounds objects are immutable, or ask that we implement a NonGCHeap enumeration now.

Comment (cshung) [reply src/coreclr/gc/gcee.cpp:65]: Actually, I prefer what I said in the initial message, leave it as is for now. We can address this set of work together (i.e. remove non-gc objects from GC heap enumeration, remove non-gc object bounds, add non-gc object enumeration, add non-gc bounds) together as a whole.

This will keep the analysis tooling working while we are still working on it.

Comment (noahfalk) [reply src/coreclr/gc/gcee.cpp:65]: > leave it as is for now.

I just want to make sure we agree on how long 'for now' is :) Not touching it in this PR is fine, but by the time we ship .NET 8, non-gc segments should not be present in GCGenerationRange events.

Comment (cshung) [reply src/coreclr/gc/gcee.cpp:65]: Sounds good to me.

Comment (cshung) [reply src/coreclr/gc/gcee.cpp]: Fixed

File: src/coreclr/vm/ClrEtwAll.man [hunk 8]
```diff
@@ -7451,8 +7451,8 @@
                              message="$(string.MonoProfilerPublisher.GCAllocationKeywordMessage)" symbol="CLR_MONO_PROFILER_GC_ALLOCATION_KEYWORD" />
                     <keyword name="GCMovesKeyword" mask="0x400000"
                              message="$(string.MonoProfilerPublisher.GCMovesKeywordMessage)" symbol="CLR_MONO_PROFILER_GC_MOVES_KEYWORD" />
-                    <keyword name="GCHeapCollectKeyword" mask="0x800000"
-                             message="$(string.MonoProfilerPublisher.GCHeapCollectKeywordMessage)" symbol="CLR_MONO_PROFILER_GC_HEAPCOLLECT_KEYWORD" />
+                    <keyword name="ManagedHeapCollectKeyword" mask="0x800000"
```
Comment (brianrob) [inline src/coreclr/vm/ClrEtwAll.man:7454]: Are we also wanting to make this change for the Mono provider?  Seems reasonable, but I want to explicitly ask.

Comment (cshung) [reply src/coreclr/vm/ClrEtwAll.man:7454]: Thanks for the catch! It wasn't my intent, I was just doing a find-and-replace.

**Comment by ww898** [comment]
Hi @cshung,

My questin is about the following statement:
>Avoid reporting the frozen segments through `GetGenerationBounds`, this would be a duplicate with `GetNonGCHeapBounds`

I may wrong, but I see the issue with old profilers which does not known about `ICorProfilerInfo14`. The statement above breaks following rule: all objects reported by `ICorProfilerCallback::ObjectReferences` should be inside GC regoins reported by `ICorProfilerInfo2::GetGenerationBounds`. Is it correct that the object from any heap (SOH, LOH, POH) can reference the object from FOH? Then `ICorProfilerCallback::ObjectReferences` will report about FOH objects, but they will be absent in `ICorProfilerInfo2::GetGenerationBounds` output. It is the issue I would point to.

**Comment by cshung** [comment]
> Is it correct that objects from any heap (SOH, LOH, POH) can reference objects from FOH?

Yes.

> Then `ICorProfilerCallback::ObjectReferences` will report about FOH objects, but they will be absent in `ICorProfilerInfo2::GetGenerationBounds` output

Yes.

> The statement above breaks the following rule ...

Yes. And this is part of the intentional breaking change related to NonGC heap diagnostics, see https://github.com/dotnet/runtime/issues/75836 for more details.

**Review by davmason — APPROVED** [review]
LGTM
