### PR TITLE
SPMI: Implement missing NAOT support (and fix garbage values passed to JIT in expandRawHandleIntrinsic)

### LINKED ISSUE #76925: SPMI does not cleanly record/replay NAOT compilations
When recording a collection through ilc I get a lot of the following messages when replaying the collection:

```scala
ERROR: Hit unimplemented expandRawHandleIntrinsic
ERROR: Exception thrown: DebugBreak or AV Exception 129
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
We have a few upcoming JIT-EE changes that we can take together.

Fix #76925

### CODE REVIEW

File: src/coreclr/jit/codegencommon.cpp [hunk 1]
```diff
@@ -1785,6 +1785,10 @@ void CodeGen::genGenerateMachineCode()
         {
             printf("; Tier-1 compilation\n");
         }
+        else if (compiler->IsTargetAbi(CORINFO_NATIVEAOT_ABI))
```
Comment (EgorBo) [inline src/coreclr/jit/codegencommon.cpp:1788]: I did it in https://github.com/dotnet/runtime/pull/75425 just completely forgot about that PR 😄

Comment (jakobbotsch) [reply src/coreclr/jit/codegencommon.cpp:1788]: Ah, I can revert it from here now that you've remembered :-)

**Review by BruceForstall — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Resolved the conflict due to the JIT-EE GUID update conflict and merged this together with #77423.
