### PR TITLE
fix proxy detection for websockets on Windows

### LINKED ISSUE #43656: Websockets Not Detecting Proxy Correctly on .Net Core
### Description

Using the sample code below works correctly with .Net Framework 4.8. However if you execute the exact same code on .Net Core 3.1, it fails to connect. 

The issue has been tracked into  the HttpConnectionPoolManager.cs file and the call to GetProxy. 
* In Framework 4.8, the URI is changed from a 'ws' scheme to an 'http' scheme via the 'internal.cs' file and a public WebRequest Create(Uri) method
* In Core 3.1, the URI is not changed (so the request to _proxy.GetProxy is a 'ws' scheme) and proxy detection fails

### Configuration

I'm using Windows 10 1909.
*** IMPORTANT *** -> I am behind a corporate proxy, with a .pac autodetection script

### Other information

Sample Code:
``` C#
using System;
using System.Net.WebSockets;
using System.Threading;

namespace Basic_Websocket_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("HTTP_PROXY", null);
            Environment.SetEnvironmentVariable("HTTPS_PROXY", null);

            var client = new ClientWebSocket();
            var uri = new Uri("ws://echo.websocket.org");
            try
            {
                var task = client.ConnectAsync(uri, new CancellationToken());
                task.Wait();
            }
            catch (Exception e)
            {
                // with .Net Core, I always get here, with an exception 
                // "Unable to connect to the remote server
                // with an inner exception ("no such host is known")
                Console.WriteLine("\nException Caught!");
                Console.WriteLine("Message :{0} ", e.Message);
            }
            Console.WriteLine("Done");
        }
    }
}

```

[My SO issue](https://stackoverflow.com/questions/64437705/clientwebsocket-throws-exception-with-corporate-proxy-and-net-core-3-1)

### PR DESCRIPTION
**Pull request by wfurt**
Using WebSockets & proxies works on Unix as well as in case of manual configuration on Windows as we use IsSecureUri() wrapper.  However passing 'ws://..' or 'wss://` URI to WinHttp helper may not work. 
This is small fix-up to match Framework behavior.

It seems like on Framework this works because we override the WebSocket uri early on:
https://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs,5755

I did not figure out how to write good test as this really depends on internal pac processing. 

fixes #43656

### CODE REVIEW

File: src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs [hunk 1]
```diff
@@ -117,13 +117,25 @@ public WinInetProxyHelper()
...
+
+            string destination = uri.AbsoluteUri;
+            // Underlying code does not understand WebSockets so we need to convert it to http or https.
+            if (uri.Scheme == UriScheme.Wss)
+            {
+                destination = "https" + destination.Substring(3);
+            }
+            else if (uri.Scheme == UriScheme.Ws)
+            {
+                destination = "http" + destination.Substring(2);
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs:129]: Does this need to compile into any non-netcoreapp projects?  If it's just netcoreapp, it could be:
```C#
destination = string.Concat("http", destination.AsSpan(2));
```
to save a string allocation (and same with similar case above).

Comment (wfurt) [reply src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs:129]: I will check. I think this is shared with WinHttp package but I'm not sure what they target.

Comment (wfurt) [reply src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs:129]: it seems like WinHttp targets netstandard2.0 and possibly net461. (the configuration is there but I'm not sure if we really build it) 
Is this worth of something like `#if NETCOREAPP` ? (or the other way)

Comment (stephentoub) [reply src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs:129]: Thanks. Probably not worth it if we're talking one string per ClientWebSocket.

File: src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs [hunk 2]
```diff
@@ -117,13 +117,25 @@ public WinInetProxyHelper()
             //    fAutoLogonIfChallenged member set to TRUE.
             //
             // We match behavior of WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY and ignore errors.
+
+            string destination = uri.AbsoluteUri;
+            // Underlying code does not understand WebSockets so we need to convert it to http or https.
+            if (uri.Scheme == UriScheme.Wss)
+            {
+                destination = "https" + destination.Substring(3);
```
Comment (geoffkizer) [inline src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs:125]: nit: can we do UriScheme.Wss.Length here instead of hardcoding "3"?

Similarly below.

Comment (geoffkizer) [reply src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs:125]: And, we should probably use UriScheme.Http and UriScheme.Https rather than hardcoded string values.

Comment (wfurt) [reply src/libraries/Common/src/System/Net/Http/WinInetProxyHelper.cs]: updated.

**Review by stephentoub — APPROVED** [review]
