### PR TITLE
Intrinsify Unsafe.Read/Write/Copy, handle struct BitCast

### LINKED ISSUE #55357: Unsafe.As resulting in lots of unnecessary moves.
### Description

Using Unsafe.As on a struct results in a lot of unnecessary asm move instructions, especially when on method return and causes even more of them after inlining.

### Configuration

Sharplab Core CLR v5.0.721.25508

### Regression?

No idea

### Data

[Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBJFqVp3KzC4aADQAcSANwBYAFBlKtRi3aceGPgKG5ZCitXrM2HGgGEI+AA6sANjCgBlBwDchMXfMWGVJ9SwcIK2coNzAPPS8AZiUkcmZcbAAzGEoAJnIAFQ8MeQBveXIiyhjqOIBVDSo08XIAQQAKSpZq2pcASkLigrlivsoAdnJHAAtWJIxGjr0+gF8uooWS2PIANRgwDGhWgB5gAE8MGAA+cgAhBvXN7Zq9w5PyDqWe/uLiIdHxjAvppfne4pLADaAFkYBgRhAACZcay2BpgiHQ2FWWwAeSsbAgAhodQA5njYLhBC4YDxbPx+Hj2gBdJbEUpUCpVGrDMYTRrNDCtchgToAoovV7kcbkBqOXAwNLcXCOBhWKzQI5Q/kASFVQuFxSuWyguwOR1OLmwtio5AAvMNJdLPhMADIwe0QPFCE2tM6sDB27BMGANJZavrlATJTh1XA7LmtNBrDa6/X3Y7HBqwJK89oxqjtGaBorvcjBxIpXERnU3cR3Q0xqM1ZOpx5u7PydX/LUB4oAeg75CYEAwIusSp9/f45AhrFwvLwMHbeaGUMd2AYtgwOaKrcBAvIoPBkJhcIRu+RcIxWJx+MJHhJZKYFKYVNp9MZcTLetuBoetu+lzj5crDz5Z5ZxFNNxWtGU5QVJUYBVZsNWAvp8wlKUaC/B0nRdMA3RqD0vR9P0wEzJs5BbYDgK7Hs+wHRUoAwYcRSYMcxknLDJTg/MFySJcVzXcgN0WLcgUcTQGE2b19ggBgMAacTJIwABpfgoRoABRBBUSET0Y0cVgAC9UktJlHy3BlyFgbAoWxWx9nIXARM2AsWXEICtz6IEADFWBgWwoTRJIkklaTSGMrVTPMyzbxs5dsTxchbBiqheLczzvN8/zAoacQQuFMKYAsqyoviphYqKvE0iSzdQpiGtxAaaLivIbAY3q2LgH5LVNUDUqzUtbAKteUqMktYB+r4v55FmIA=)

```csharp
using System.Runtime.Intrinsics.X86;
using System.Runtime.Intrinsics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

public static unsafe class Test
{
    public static UInt128 A(UInt128 v)
    {
        return ShiftA(v);
    }
    
    public static Vector128<byte> B(Vector128<byte> v)
    {
        return ShiftB(v);
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static UInt128 ShiftA(UInt128 c)
    {
        if (Sse2.IsSupported)
		{
            Vector128<byte> val1 = Sse2.ShiftLeftLogical128BitLane(
                Unsafe.As<UInt128, Vector128<byte>>(ref c), 1);
            return Unsafe.As<Vector128<byte>, UInt128>(ref val1);
		}
        
        // not important in this case
        return default;
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vector128<byte> ShiftB(Vector128<byte> c)
    {
        if (Sse2.IsSupported)
		{
            return Sse2.ShiftLeftLogical128BitLane(c, 1);
		}
        
        // not important in this case
		return default;
    }
    
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public readonly struct UInt128
    {
        [FieldOffset(0)]
        public readonly ulong long1;
        [FieldOffset(8)]
        public readonly ulong long2;
        
        public UInt128(ulong a, ulong b)
        {
            long1 = a;
            long2 = b;
        }
    }
}
```

Output:
```
; Core CLR 5.0.921.35908 on amd64

Test.A(UInt128)
    L0000: sub rsp, 0x28
    L0004: vzeroupper
    L0007: mov rax, [rdx]
    L000a: mov rax, [rdx+8]
    L000e: vmovupd xmm0, [rsp]
    L0013: vpslldq xmm0, xmm0, 1
    L0018: vmovapd [rsp], xmm0
    L001d: vmovdqu xmm0, [rsp]
    L0022: vmovdqu [rsp+0x18], xmm0
    L0028: vmovdqu xmm0, [rsp+0x18]
    L002e: vmovdqu [rcx], xmm0
    L0032: mov rax, rcx
    L0035: add rsp, 0x28
    L0039: ret

Test.B(System.Runtime.Intrinsics.Vector128`1<Byte>)
    L0000: vzeroupper
    L0003: vmovupd xmm0, [rdx]
    L0007: vpslldq xmm0, xmm0, 1
    L000c: vmovupd [rcx], xmm0
    L0010: mov rax, rcx
    L0013: ret

Test.ShiftA(UInt128)
    L0000: sub rsp, 0x18
    L0004: vzeroupper
    L0007: vmovupd xmm0, [rdx]
    L000b: vpslldq xmm0, xmm0, 1
    L0010: vmovapd [rsp], xmm0
    L0015: vmovdqu xmm0, [rsp]
    L001a: vmovdqu [rcx], xmm0
    L001e: mov rax, rcx
    L0021: add rsp, 0x18
    L0025: ret

Test.ShiftB(System.Runtime.Intrinsics.Vector128`1<Byte>)
    L0000: vzeroupper
    L0003: vmovupd xmm0, [rdx]
    L0007: vpslldq xmm0, xmm0, 1
    L000c: vmovupd [rcx], xmm0
    L0010: mov rax, rcx
    L0013: ret

Test+UInt128..ctor(UInt64, UInt64)
    L0000: mov [rcx], rdx
    L0003: mov [rcx+8], r8
    L0007: ret

```

category:cq
theme:structs
skill-level:expert
cost:medium
impact:medium

### PR DESCRIPTION
**Pull request by MichalPetryka**
Implements Unsafe.Read/Write/Copy (and the unaligned versions) as JIT intrinsics.

Fixes bugs with small type params not being correctly extended in bitcast.

Handles structs in Unsafe.BitCast via intrinsic.

Contributes to #69220.
Fixes #55357.

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -15937,7 +15937,9 @@ GenTree* Compiler::gtNewRefCOMfield(GenTree*                objPtr,
             // helper needs pointer to struct, not struct itself
             if (pFieldInfo->helper == CORINFO_HELP_SETFIELDSTRUCT)
             {
-                assg = impGetStructAddr(assg, structType, CHECK_SPILL_ALL, true);
+                // TODO: deal with flags
+                GenTreeFlags flags = GTF_EMPTY;
```
Comment (SingleAccretion) [inline src/coreclr/jit/gentree.cpp:15941]: Nit: `flags` -> `indirFlags`, here and everywhere else, for consistency.

File: src/coreclr/jit/importercalls.cpp [hunk 2]
```diff
@@ -4410,28 +4399,25 @@ GenTree* Compiler::impSRCSUnsafeIntrinsic(NamedIntrinsic        intrinsic,
...
-            // unaligned. 0x01
-            // stobj !!T
-            // ret
+            CORINFO_CLASS_HANDLE typeHnd = sig->sigInst.methInst[0];
+            ClassLayout*         layout  = nullptr;
+            var_types            type    = TypeHandleToVarType(typeHnd, &layout);
+            GenTreeFlags         flags   = intrinsic == NI_SRCS_UNSAFE_WriteUnaligned ? GTF_IND_UNALIGNED : GTF_EMPTY;
 
-            return nullptr;
+            return gtNewAssignNode(gtNewLoadValueNode(type, layout, op2, flags), op1);
```
Comment (SingleAccretion) [inline src/coreclr/jit/importercalls.cpp:4420]: This needs to call `impAssignStruct` for `varTypeIsStruct(type)` values, otherwise it won't work correct for calls with return buffers and `MKREFANY`s.

**Comment by MichalPetryka** [comment]
I'll be unable to respond to reviews for a few weeks, I've asked @thatbakamono to apply any feedback though.

File: src/coreclr/inc/targetosarch.h [hunk 3]
```diff
@@ -35,6 +35,11 @@ class TargetOS
 class TargetArchitecture
 {
 public:
+#ifdef TARGET_64BIT
+    static const bool Is64Bit = true;
```
Comment (EgorBo) [inline src/coreclr/inc/targetosarch.h:39]: nit: `Is64Bit = TARGET_POINTER == 8;`

File: src/coreclr/jit/gentree.cpp [hunk 4]
```diff
@@ -16201,7 +16201,9 @@ GenTree* Compiler::gtNewRefCOMfield(GenTree*                objPtr,
             // helper needs pointer to struct, not struct itself
             if (pFieldInfo->helper == CORINFO_HELP_SETFIELDSTRUCT)
             {
-                assg = impGetStructAddr(assg, CHECK_SPILL_ALL, true);
+                // TODO: deal with flags
```
Comment (EgorBo) [inline src/coreclr/jit/gentree.cpp:16204]: what does "deal with flags" mean?

File: src/coreclr/jit/importercalls.cpp [hunk 5]
```diff
@@ -4415,28 +4371,26 @@ GenTree* Compiler::impSRCSUnsafeIntrinsic(NamedIntrinsic        intrinsic,
...
             // ldarg.0
             // ldarg.1
+            // if NI_SRCS_UNSAFE_WriteUnaligned: unaligned. 0x01
             // stobj !!T
             // ret
 
-            return nullptr;
-        }
-
-        case NI_SRCS_UNSAFE_WriteUnaligned:
```
Comment (EgorBo) [inline src/coreclr/jit/importercalls.cpp:4429]: Can we now remove these from VM?

Comment (MichalPetryka) [reply src/coreclr/jit/importercalls.cpp:4429]: They're still used for indirect calls for now, the rest intrinsics are still there as well. I'd just remove them all at once when all are made JIT intrinsics.

File: src/coreclr/jit/gentree.cpp (hunk 4 above)
Comment (MichalPetryka) [reply src/coreclr/jit/gentree.cpp:16204]: The code should be audited whether flags matter or not, and if yes we should probably read the address with them and use a temp and its address.

File: src/coreclr/jit/importercalls.cpp [hunk 6]
```diff
@@ -4042,57 +4036,26 @@ GenTree* Compiler::impSRCSUnsafeIntrinsic(NamedIntrinsic        intrinsic,
...
-                }
-            }
-            else if (toType == TYP_STRUCT)
-            {
-                involvesStructType = true;
-            }
+            GenTree* op1 = impPopStack().val;
 
-            if (involvesStructType)
+            if ((fromTypeHnd == toTypeHnd) || (varTypeIsIntegral(fromType) && varTypeIsIntegral(toType)) ||
```
Comment (SingleAccretion) [inline src/coreclr/jit/importercalls.cpp:4049]: >  `(varTypeIsIntegral(fromType) && varTypeIsIntegral(toType))`

I don't think this is correct for small types. Consider: `BitCast<short, ushort>(*pShort)` - this should clear the upper bits.

File: src/coreclr/jit/importer.cpp [hunk 7]
```diff
@@ -1094,47 +1099,50 @@ GenTree* Compiler::impAssignStructPtr(GenTree* destAddr, GenTree* src, unsigned
...
+    switch (val->OperGet())
     {
         case GT_BLK:
         case GT_IND:
-            if (willDeref)
+            if (pDerefFlags != nullptr)
             {
-                return structVal->AsIndir()->Addr();
+                *pDerefFlags |= (val->gtFlags & GTF_IND_FLAGS);
+                return val->AsIndir()->Addr();
```
Comment (SingleAccretion) [inline src/coreclr/jit/importer.cpp:1124]: I think we should limit the set of flags here to `(GTF_IND_VOLATILE | GTF_IND_NONFAULTING | GTF_IND_UNALIGNED | GTF_IND_INITCLASS)`, same as physical promotion does. The other flags are more likely to be incorrect w.r.t. applying them to arbitrary callers. This set should also be documented in the method header.

Also, the Jit convention is that we should initialize `pDerefFlags` to `GTF_EMPTY` if passed (s. t. the callers don't have to).

File: src/coreclr/jit/gentree.cpp [hunk 8]
```diff
@@ -16201,7 +16201,9 @@ GenTree* Compiler::gtNewRefCOMfield(GenTree*                objPtr,
             // helper needs pointer to struct, not struct itself
             if (pFieldInfo->helper == CORINFO_HELP_SETFIELDSTRUCT)
             {
-                assg = impGetStructAddr(assg, CHECK_SPILL_ALL, true);
+                // TODO: verify if flags matter here
```
Comment (SingleAccretion) [inline src/coreclr/jit/gentree.cpp:16204]: Can you please open an issue about this as well and tag all of these with `TODO-Bug?`?

I see some places here are definitely bugs, esp. w.r.t. missed volatiles.

Comment (MichalPetryka) [reply src/coreclr/jit/gentree.cpp:16204]: I'll open one after the PR gets merged.

**Comment by JulieLeeMSFT** [comment]
@MichalPetryka, please resolve the merge conflict.

File: src/tests/JIT/Intrinsics/BitCast.il [hunk 9]
```diff
@@ -0,0 +1,250 @@
...
+  .ver 1:0:0:0
+}
+.module Bitcast.dll
+.custom instance void [System.Runtime]System.Security.UnverifiableCodeAttribute::.ctor() = ( 01 00 00 00 )
+.custom instance void [System.Runtime]System.Runtime.CompilerServices.RefSafetyRulesAttribute::.ctor(int32) = ( 01 00 0B 00 00 00 00 00 )
+.imagebase 0x0000000180000000
+.file alignment 0x00001000
+.stackreserve 0x0000000000400000
+.subsystem 0x0003       // WINDOWS_CUI
+.corflags 0x00000004    //  IL_LIBRARY
```
Comment (EgorBo) [inline src/tests/JIT/Intrinsics/BitCast.il:31]: it looks like this fil has many redundant things like `.publickeytoken`, `.ver`, `permissionset`, `UnverifiableCodeAttribute`, these `subsystem` fields - can you clean it up please?

File: src/coreclr/jit/importercalls.cpp [hunk 10]
```diff
@@ -4372,26 +4366,21 @@ GenTree* Compiler::impSRCSUnsafeIntrinsic(NamedIntrinsic          intrinsic,
...
             // ldobj !!T
             // ret
 
-            return nullptr;
+            CORINFO_CLASS_HANDLE typeHnd = sig->sigInst.methInst[0];
+            ClassLayout*         layout  = nullptr;
+            var_types            type    = TypeHandleToVarType(typeHnd, &layout);
+            GenTreeFlags         flags   = intrinsic == NI_SRCS_UNSAFE_ReadUnaligned ? GTF_IND_UNALIGNED : GTF_EMPTY;
+
+            return gtNewLoadValueNode(type, layout, impPopStack().val, flags);
```
Comment (EgorBo) [inline src/coreclr/jit/importercalls.cpp:4383]: Do we have a test where we do `Unsafe.ReadUnligned/WriteUnligned for a struct with _Canon? e.g. 
`Unsafe.ReadUnalinged<FooStruct<T>>` ? can you please add one to make sure

File: src/coreclr/jit/importercalls.cpp [hunk 11]
```diff
@@ -4213,14 +4181,33 @@ GenTree* Compiler::impSRCSUnsafeIntrinsic(NamedIntrinsic          intrinsic,
                         return gtNewDconNode(BitOperations::UInt32BitsToSingle(u32Cns), TYP_FLOAT);
                     }
                 }
-                else
+                // TODO-CQ: We should support this on 32-bit via decomposition
+                else if (TargetArchitecture::Is64Bit || (toType == TYP_FLOAT))
```
Comment (EgorBo) [inline src/coreclr/jit/importercalls.cpp:4185]: can you explain to me the `toType == FLOAT` please

File: src/coreclr/jit/importer.cpp [hunk 12]
```diff
@@ -807,8 +807,10 @@ GenTree* Compiler::impStoreStruct(GenTree*         store,
             WellKnownArg wellKnownArgType =
                 srcCall->ShouldHaveRetBufArg() ? WellKnownArg::RetBuffer : WellKnownArg::None;
 
-            GenTree*   destAddr = impGetStructAddr(store, CHECK_SPILL_ALL, /* willDeref */ true);
-            NewCallArg newArg   = NewCallArg::Primitive(destAddr).WellKnown(wellKnownArgType);
+            // TODO-Bug?: verify if flags matter here
```
Comment (EgorBo) [inline src/coreclr/jit/importer.cpp:810]: Can you explain this TODO please?

File: src/coreclr/jit/importercalls.cpp (hunk 11 above)
Comment (MichalPetryka) [reply src/coreclr/jit/importercalls.cpp:4185]: On 32bit only 4 byte bitcast node in supported.

File: src/coreclr/jit/importer.cpp (hunk 12 above)
Comment (MichalPetryka) [reply src/coreclr/jit/importer.cpp:810]: This will now return flags like volatile or unaligned if the previous load contained them, as such I've marked all places that use this API where I wasn't sure if dropping them was okay.

File: src/coreclr/jit/importercalls.cpp (hunk 10 above)
Comment (MichalPetryka) [reply src/coreclr/jit/importercalls.cpp:4383]: Added a new test.

File: src/tests/JIT/Intrinsics/BitCast.il (hunk 9 above)
Comment (EgorBo) [inline src/tests/JIT/Intrinsics/BitCast.il:31]:
```suggestion
.assembly extern System.Runtime {}
.assembly extern System.Console {}
.assembly Bitcast {}
```

**Review by EgorBo — APPROVED** [review]
LGTM, but let's run some outerloop jobs to make sure, will trigger ones once inner loop finishes

**Comment by MichalPetryka** [comment]
@MihuBot -hetzner

**Comment by EgorBo** [comment]
Can you please rebase it - CI should be better now

**Comment by MichalPetryka** [comment]
@MihuBot

**Comment by EgorBo** [comment]
Thanks!

**Comment by AndyAyersMS** [comment]
Improvments:
- https://github.com/dotnet/perf-autofiling-issues/issues/20166

**Comment by AndyAyersMS** [comment]
Possible regressions:
- https://github.com/dotnet/perf-autofiling-issues/issues/20151
