### PR TITLE
Unify unroll limits in a single entry point

### LINKED ISSUE #82529: Investigate adjusting herustics for unrolled block copies/initialization
Zero initialization becomes expensive with two bytes struct fields are involved:

Given:
```c#
unsafe struct S1
{
    fixed byte a[10];
    int b;
    fixed byte c[23];
    fixed byte d[24];
    fixed byte e[25];
}

unsafe struct S2
{
    fixed short a[10];
    int b;
    fixed short c[23];
    fixed short d[24];
    fixed short e[25];
}
```

Unlike S1, initializing S2 does not inline the `CORINFO_HELP_MEMSET` call and fail to make use of vectors:

```asm
;   S1 X1() { S1 s = default; return s; }

C:X1():S1:this:
       sub      rsp, 24
       vzeroupper 
       mov      rax, qword ptr [(reloc)]
       mov      qword ptr [rsp+10H], rax
       xor      eax, eax
       vxorps   ymm0, ymm0
       vmovdqu  ymmword ptr[rsi], ymm0
       vmovdqu  ymmword ptr[rsi+20H], ymm0
       vmovdqu  xmmword ptr [rsi+40H], xmm0
       mov      qword ptr [rsi+50H], rax
       mov      rax, rsi
       lea      rdi, [(reloc)]
       mov      rdi, qword ptr [rdi]
       cmp      qword ptr [rsp+10H], rdi
       je       SHORT G_M61359_IG03
       call     [CORINFO_HELP_FAIL_FAST]
G_M61359_IG03:
       nop      
       add      rsp, 24
       ret      

;   S2 X2() { S2 s = default; return s; }

C:X2():S2:this:
       push     rbx
       sub      rsp, 16
       mov      rax, qword ptr [(reloc)]
       mov      qword ptr [rsp+08H], rax
       mov      rbx, rsi
       xor      esi, esi
       mov      rdi, rbx
       mov      edx, 168
       call     [CORINFO_HELP_MEMSET]
       mov      rax, rbx
       lea      rdi, [(reloc)]
       mov      rdi, qword ptr [rdi]
       cmp      qword ptr [rsp+08H], rdi
       je       SHORT G_M46095_IG03
       call     [CORINFO_HELP_FAIL_FAST]
G_M46095_IG03:
       nop      
       add      rsp, 16
       pop      rbx
       ret      
```

The codegen can try to match that of C++ compiler:

```asm
X2():                                  # @X2()
        mov     rax, rdi
        vxorps  xmm0, xmm0, xmm0
        vmovups ymmword ptr [rdi + 128], ymm0
        vmovups ymmword ptr [rdi + 96], ymm0
        vmovups ymmword ptr [rdi + 64], ymm0
        vmovups ymmword ptr [rdi + 32], ymm0
        vmovups ymmword ptr [rdi], ymm0
        mov     qword ptr [rdi + 160], 0
        vzeroupper
        ret
```

https://godbolt.org/z/a3WsPdd4M

### PR DESCRIPTION
**Pull request by EgorBo**
The current limits were a bit odd, e.g. hard limit of 128 bytes on x64 no matter if it supports AVX or not (2x less instructions).

Also, the new limits overall match whatever native compilers do for memset/memcpy unroll in -Os (size-aware): https://godbolt.org/z/dW1qqaP9a

Closes https://github.com/dotnet/runtime/issues/82529

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Fixes #82529?

**Comment by EgorBo** [comment]
> Fixes #82529?

Ah, didn't see this one. Yeah, it does. It zeroes `S2` struct via:
```
       xor      eax, eax
       vxorps   ymm0, ymm0
       vmovdqu  ymmword ptr[rdx], ymm0
       vmovdqu  ymmword ptr[rdx+20H], ymm0
       vmovdqu  ymmword ptr[rdx+40H], ymm0
       vmovdqu  ymmword ptr[rdx+60H], ymm0
       vmovdqu  ymmword ptr[rdx+80H], ymm0
       mov      qword ptr [rdx+A0H], rax
```
For some reason JIT doesn't want to overlap when it zeroes memory, hence, it used GPR here - will file an issue

**Comment by EgorBo** [comment]
Bencmarks:

### Memset
```csharp
public unsafe class MemsetBenchmarks
{
    private static readonly byte[] Data1 = new byte[1024];

    [Benchmark] public void Memset8() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 8);
    [Benchmark] public void Memset10() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 10);
    [Benchmark] public void Memset14() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 14);
    [Benchmark] public void Memset16() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 16);
    [Benchmark] public void Memset17() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 17);
    [Benchmark] public void Memset20() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 20);
    [Benchmark] public void Memset32() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 32);
    [Benchmark] public void Memset33() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 33);
    [Benchmark] public void Memset40() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 40);
    [Benchmark] public void Memset50() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 50);
    [Benchmark] public void Memset64() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 64);
    [Benchmark] public void Memset65() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 65);
    [Benchmark] public void Memset80() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 80);
    [Benchmark] public void Memset90() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 90);
    [Benchmark] public void Memset110() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 110);
    [Benchmark] public void Memset128() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 128);
    [Benchmark] public void Memset129() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 129);
    [Benchmark] public void Memset200() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 200);
    [Benchmark] public void Memset256() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 256);
    [Benchmark] public void Memset257() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 257);
    [Benchmark] public void Memset300() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 300);
    [Benchmark] public void Memset400() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 400);
    [Benchmark] public void Memset512() => Unsafe.InitBlockUnaligned(ref Data1[0], 0, 512);
}
```
image

### Memcpy
```csharp
public unsafe class MemcpyBenchmarks
{
    private static readonly byte[] Data1 = new byte[1024];
    private static readonly byte[] Data2 = new byte[1024];

    [Benchmark] public void Memcpy8() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 8);
    [Benchmark] public void Memcpy10() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 10);
    [Benchmark] public void Memcpy14() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 14);
    [Benchmark] public void Memcpy16() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 16);
    [Benchmark] public void Memcpy17() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 17);
    [Benchmark] public void Memcpy20() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 20);
    [Benchmark] public void Memcpy32() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 32);
    [Benchmark] public void Memcpy33() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 33);
    [Benchmark] public void Memcpy40() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 40);
    [Benchmark] public void Memcpy50() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 50);
    [Benchmark] public void Memcpy64() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 64);
    [Benchmark] public void Memcpy65() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 65);
    [Benchmark] public void Memcpy80() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 80);
    [Benchmark] public void Memcpy90() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 90);
    [Benchmark] public void Memcpy110() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 110);
    [Benchmark] public void Memcpy128() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 128);
    [Benchmark] public void Memcpy129() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 129);
    [Benchmark] public void Memcpy200() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 200);
    [Benchmark] public void Memcpy256() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 256);
    [Benchmark] public void Memcpy257() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 257);
    [Benchmark] public void Memcpy300() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 300);
    [Benchmark] public void Memcpy400() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 400);
    [Benchmark] public void Memcpy512() => Unsafe.CopyBlockUnaligned(ref Data1[0], ref Data2[0], 512);
}
```

image

File: src/coreclr/jit/targetx86.h [hunk 1]
```diff
@@ -13,8 +13,6 @@
 
   // TODO-CQ: Fine tune the following xxBlk threshold values:
```
Comment (ANahr) [inline src/coreclr/jit/targetx86.h:14]: remove this?

**Comment by EgorBo** [comment]
@dotnet/jit-contrib PTAL
This PR unifies various unrolling strategies to a single entry point and fixes some oddities, e.g. on X64 we have a hard limit 128 bytes for memset and it doesn't matter whether we can use AVX or not or only GPR (in case of GC fields).

Visible things this PR fixes:
- ARM32 used to have memset=32b and memcpy=64b - aparently whoever set those mixed them up, I made it memset=64b, memcpy=32 (large negative diffs)
- Changed memset to 256b (with AVX available) and memcpy to 128b on AMD64 (used to be 128/64b) - see benchmarks above + this matches clang/LLVM with -Os (size) behavior for a generic cpu -- this is also needed for faster stackalloc zeroing, see https://user-images.githubusercontent.com/523221/224337267-efa1e0c9-5684-4c53-ab52-6154106d8d80.png

Diffs are not too big outside of coreclr_tests collection - around +2k-3k for libraries.pmi: [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201521&view=ms.vss-build-web.run-extensions-tab)

To improve some of them I filed:

- https://github.com/dotnet/runtime/issues/83277
- https://github.com/dotnet/runtime/issues/83297

A typical size regression looks like this:
```diff
        mov      qword ptr [rbp-C8H], rdx
        mov      rdx, bword ptr [rbp+18H]
        ; byrRegs +[rdx]
-       lea      rcx, bword ptr [rbp-B8H]
-       ; byrRegs +[rcx]
-       mov      r8d, 80
-       call     CORINFO_HELP_MEMCPY
-       ; byrRegs -[rcx rdx]
+       vmovdqu  ymm0, ymmword ptr[rdx]
+       vmovdqu  ymmword ptr[rbp-B8H], ymm0
+       vmovdqu  ymm0, ymmword ptr[rdx+20H]
+       vmovdqu  ymmword ptr[rbp-98H], ymm0
+       vmovdqu  xmm0, xmmword ptr [rdx+40H]
+       vmovdqu  xmmword ptr [rbp-78H], xmm0
        mov      rdx, qword ptr [rbp-C0H]
+       ; byrRegs -[rdx]
        mov      r8, qword ptr [rbp-C8H]
        lea      r9, [rbp-B8H]
        lea      rcx, [rbp-40H]
 ```
which is 2x faster on all machines I tested. There are several cases where unrolling produces more compact code than `call memset/memcpy` presumably, due to reg spills.

File: src/coreclr/jit/compiler.h [hunk 2]
```diff
@@ -8950,22 +8950,34 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
...
+            // ldp/stp instructions can load/store two 16-byte vectors at once, e.g.:
+            //
+            //   ldp q0, q1, [x1]
+            //   stp q0, q1, [x0]
+            //
+            threshold *= 2;
 #elif defined(TARGET_XARCH)
-        // Ignore AVX-512 for now
-        threshold = max(threshold, YMM_REGSIZE_BYTES);
+            // Ignore AVX-512 for now
```
Comment (tannergooding) [inline src/coreclr/jit/compiler.h:8979]: can you make this a `TODO-XARCH-AVX512` so we can track it alongside any other AVX-512 cleanup/considerations after more support is added?

Comment (EgorBo) [reply src/coreclr/jit/compiler.h]: Sure, added

**Comment by EgorBo** [comment]
@tannergooding @dotnet/jit-contrib PTAL

**Review by tannergooding — APPROVED** [review]

**Comment by EgorBo** [comment]
image

Improved parsing of doubles
