### PR TITLE
Fixes race condition on captive scoped services

### LINKED ISSUE #52863: Race in scoped services promoted to singleton caching
The https://github.com/dotnet/runtime/pull/52484 attempted to fix the race where `CallSiteRuntimeResolver.Instance.Resolve` and compiled service accessors have a different source of truth for a scoped services promoted to singletons caching location.

The former presumes the value is cached in callSite.Value the latter in `ResolvedServices` dictionary on the scope.

The problem with the fix is that it only tightened the race for directly resolved services but did nothing for indirectly-resolved ones.

For the following chain:

`A(Singleton)->B(Scoped)`

When A is resolved B is also resolved and cached into the `callSite.Value`. When a direct compiled accessor for `B` is executed on the root scope it would bypass the logic in the fix and would use the ResolvedService collection, skipping `callSite.Value` entirely.

### PR DESCRIPTION
**Pull request by maryamariyan**
Fixes: #52863

TODO:
- [x] Consider changing IL generated code instead

### CODE REVIEW

**Comment by gfoidl** [comment]
@maryamariyan I think you have linked the wrong issue. Should be https://github.com/dotnet/runtime/issues/52863?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 1]
```diff
@@ -309,8 +326,36 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
...
+                context.Generator.Emit(OpCodes.Callvirt, ScopeIsRootScope);
+                context.Generator.Emit(OpCodes.Stloc_3);
+                context.Generator.Emit(OpCodes.Ldloc_3);
+                context.Generator.Emit(OpCodes.Brfalse_S, defaultLabel);
+                context.Generator.Emit(OpCodes.Nop);
+
+                // Return resolved value from CallSiteRuntimeResolver for root scope
+                if (true || CallSiteGetter != null)
+                {
+                    // TODO - find out what in else condition is broken
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:343]: - [ ] find out what portion in else block is wrong

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 2]
```diff
@@ -52,7 +66,10 @@ public ILEmitResolverBuilder(ServiceProvider serviceProvider)
 
         public Func<ServiceProviderEngineScope, object> Build(ServiceCallSite callSite)
         {
-            return BuildType(callSite).Lambda;
+            Func<ServiceProviderEngineScope, object> lambda = BuildType(callSite).Lambda;
+
+            return (scope) => scope.IsRootScope ?
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:71]: - [ ] undo once IL logic is completed

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 3]
```diff
@@ -309,8 +326,36 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
 
                 Label skipCreationLabel = context.Generator.DefineLabel();
                 Label returnLabel = context.Generator.DefineLabel();
+                Label defaultLabel = context.Generator.DefineLabel();
+
+                // Check if scope IsRootScope
+                context.Generator.Emit(OpCodes.Nop);
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:332]: Do you need the nop?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 4]
```diff
@@ -309,8 +326,36 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
...
+                context.Generator.Emit(OpCodes.Ldarg_1);
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:333]: Add a comment showing what C# this maps to above it.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 5]
```diff
@@ -309,8 +326,36 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
...
+                context.Generator.Emit(OpCodes.Callvirt, ScopeIsRootScope);
+                context.Generator.Emit(OpCodes.Stloc_3);
+                context.Generator.Emit(OpCodes.Ldloc_3);
+                context.Generator.Emit(OpCodes.Brfalse_S, defaultLabel);
+                context.Generator.Emit(OpCodes.Nop);
+
+                // Return resolved value from CallSiteRuntimeResolver for root scope
+                if (true || CallSiteGetter != null)
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:341]: What's this check for?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 6]
```diff
@@ -309,8 +326,36 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
...
+                    context.Generator.Emit(OpCodes.Nop); 
+                }
+                else
+                {
+                    context.Generator.Emit(OpCodes.Call, CallSiteRuntimeResolverInstanceField);
+                    context.Generator.Emit(OpCodes.Ldarg_0);
+                    context.Generator.Emit(OpCodes.Callvirt, CallSiteGetter);
+                    context.Generator.Emit(OpCodes.Ldarg_1);
+                    context.Generator.Emit(OpCodes.Callvirt, CallSiteRuntimeResolverResolveMethod);
+                    context.Generator.Emit(OpCodes.Stloc_S, 4);
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:353]: we should use a LocalBuilder for local variables instead of indexes, here and elsewhere

**Comment by maryamariyan** [comment]
Updated IL generation logic and applied feedback.

The Expression tree side will need to be changed as well, that would be run for .NET Core 2.1.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 7]
```diff
@@ -309,8 +326,21 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
...
                 Label returnLabel = context.Generator.DefineLabel();
+                Label defaultLabel = context.Generator.DefineLabel();
+
+                // Check if scope IsRootScope
+                context.Generator.Emit(OpCodes.Ldarg_1);
+                context.Generator.Emit(OpCodes.Callvirt, ScopeIsRootScope);
+                context.Generator.Emit(OpCodes.Brfalse_S, defaultLabel);
+
+                context.Generator.Emit(OpCodes.Call, CallSiteRuntimeResolverInstanceField);
+                AddConstant(context, callSite);
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:337]: This is a nice change. @pakrym but we're paying for bounds checks!! 😄

Comment (pakrym) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:337]: We can change AddConstant to produce unsafe code with `fixed`.

Comment (pakrym) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:337]: Don't think it matters though.

Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:337]: This method is locking and has a try finally so I'd be surprised if it mattered as well.

> We can change AddConstant to produce unsafe code with fixed.

`Unsafe.Add`

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 8]
```diff
@@ -52,7 +62,10 @@ public ILEmitResolverBuilder(ServiceProvider serviceProvider)
 
         public Func<ServiceProviderEngineScope, object> Build(ServiceCallSite callSite)
         {
-            return BuildType(callSite).Lambda;
+            Func<ServiceProviderEngineScope, object> lambda = BuildType(callSite).Lambda;
+
+            return (scope) => scope.IsRootScope ?
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:67]: Undo this.

**Comment by maryamariyan** [comment]
Fixed the Expression Resolver Builder portion as well. Marked PR as ready for review.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 9]
```diff
@@ -1103,6 +1103,49 @@ public void ScopedServiceResolvedFromSingletonAfterCompilation()
...
+        {
+            ServiceProvider sp = new ServiceCollection()
+                                .AddScoped<A>()
+                                .AddSingleton<IFakeOpenGenericService<A>, FakeOpenGenericService<A>>()
+                                .BuildServiceProvider(mode);
+
+            var scope = sp.CreateScope();
+            for (int i = 0; i < 50; i++)
+            {
+                scope.ServiceProvider.GetRequiredService<A>();
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:1122]: Should we be `Assert.Same` in this loop, like we are in the other tests?

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 10]
```diff
@@ -1103,6 +1103,49 @@ public void ScopedServiceResolvedFromSingletonAfterCompilation()
...
+                                .BuildServiceProvider(ServiceProviderMode.ILEmit);
+
+            var scope = sp.CreateScope();
+            for (int i = 0; i < 50; i++)
+            {
+                Assert.Same(sp.GetRequiredService<IFakeOpenGenericService<Aa>>().Value.PropertyA, sp.GetRequiredService<A>());
+                Thread.Sleep(10); // Give the background thread time to compile
+            }
+
+            Assert.Same(sp.GetRequiredService<IFakeOpenGenericService<Aa>>().Value.PropertyA, sp.GetRequiredService<A>());
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:1146]: Does this one more `Assert.Same` add value over the 50 that happen in the loop above?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/Expressions/ExpressionResolverBuilder.cs [hunk 11]
```diff
@@ -27,12 +28,19 @@ internal sealed class ExpressionResolverBuilder : CallSiteVisitor<object, Expres
...
         private static readonly ParameterExpression ResolvedServices = Expression.Variable(typeof(IDictionary<ServiceCacheKey, object>), ScopeParameter.Name + "resolvedServices");
         private static readonly ParameterExpression Sync = Expression.Variable(typeof(object), ScopeParameter.Name + "sync");
+        private static readonly ParameterExpression IsRootScope = Expression.Variable(typeof(bool), ScopeParameter.Name + "isRootScope");
         private static readonly BinaryExpression ResolvedServicesVariableAssignment =
             Expression.Assign(ResolvedServices,
                 Expression.Property(
                     ScopeParameter,
                     typeof(ServiceProviderEngineScope).GetProperty(nameof(ServiceProviderEngineScope.ResolvedServices), BindingFlags.Instance | BindingFlags.NonPublic)));
 
+        private static readonly BinaryExpression IsRootScopeVariableAssignment =
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/Expressions/ExpressionResolverBuilder.cs:38]: Do we need an assignment? Can we use `Expression.Property(
                    ScopeParameter,
                    typeof(ServiceProviderEngineScope).GetProperty(nameof(ServiceProviderEngineScope.IsRootScope), BindingFlags.Instance | BindingFlags.Public))` in the condition directly?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/Expressions/ExpressionResolverBuilder.cs [hunk 12]
```diff
@@ -203,6 +212,20 @@ protected override Expression VisitScopeCache(ServiceCallSite callSite, object c
         // Move off the main stack
         private Expression BuildScopedExpression(ServiceCallSite callSite)
         {
+            ConstantExpression callSiteExpression = Expression.Constant(
+                callSite,
+                typeof(ServiceCallSite));
+
+            ConstantExpression resolverExpression = Expression.Constant(
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/Expressions/ExpressionResolverBuilder.cs:219]: This one can be made a static

**Comment by pakrym** [comment]
@maryamariyan please make sure modified tets still reproduce the original issue.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 13]
```diff
@@ -1103,6 +1103,45 @@ public void ScopedServiceResolvedFromSingletonAfterCompilation()
...
+        [InlineData(ServiceProviderMode.Expressions)]
+        [InlineData(ServiceProviderMode.ILEmit)]
+        private void ScopedServiceResolvedFromSingletonAfterCompilation2(ServiceProviderMode mode)
+        {
+            ServiceProvider sp = new ServiceCollection()
+                                .AddScoped<A>()
+                                .AddSingleton<IFakeOpenGenericService<A>, FakeOpenGenericService<A>>()
+                                .BuildServiceProvider(mode);
+
+            var scope = sp.CreateScope();
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:1119]: Is the scope not used?

**Comment by pakrym** [comment]
Can you please add the test from the original issue?

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 14]
```diff
@@ -1119,11 +1119,9 @@ private void ScopedServiceResolvedFromSingletonAfterCompilation2(ServiceProvider
             var scope = sp.CreateScope();
             for (int i = 0; i < 50; i++)
             {
-                scope.ServiceProvider.GetRequiredService<A>();
+                Assert.Same(sp.GetRequiredService<IFakeOpenGenericService<A>>().Value, sp.GetRequiredService<A>());
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:1122]: The scope is supposed to be used here no?

**Comment by maryamariyan** [comment]
> Can you please add the test from the original issue?

> The scope is supposed to be used here no?

I confirmed that we get a repro with the unit tests as-is without the fix.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/CallSiteTests.cs [hunk 15]
```diff
@@ -174,9 +174,10 @@ public void BuildExpressionAddsDisposableCaptureForDisposableFactoryServices(Ser
         }
 
         [Theory]
+        [ActiveIssue("https://github.com/dotnet/runtime/issues/52863")]
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/CallSiteTests.cs:177]: This PR closes the linked issue.

Comment (maryamariyan) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/CallSiteTests.cs:177]: yes but I'm trying to first add this one liner to confirm no other tests failing. 

Meanwhile trying to figure out if this failure and `BuildExpressionElidesDisposableCaptureForEnumerableServices` for scoped failure is expected...

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 16]
```diff
@@ -11,7 +11,7 @@ namespace Microsoft.Extensions.DependencyInjection.ServiceLookup
     internal sealed class ServiceProviderEngineScope : IServiceScope, IServiceProvider, IAsyncDisposable, IServiceScopeFactory
     {
         // For testing only
-        internal Action<object> _captureDisposableCallback;
+        internal IList<object> Disposables => _disposables ?? (IList<object>)Array.Empty<object>();
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:14]: Removes a pointer 😄. Saving the planet.

**Comment by maryamariyan** [comment]
Test failure:

```
Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.AddAndReplaceEntries_AreThreadSafe

Assert.Equal() Failure
Expected: 3
Actual:   7
```

On `Libraries Test Run release coreclr Linux x64 Debug` Didn't repro locally. Rerunning to check if intermittent.

**Review by davidfowl — APPROVED** [review]
Let's see how this affects the performance of scoped service resolution.

**Comment by davidfowl** [comment]
I think we can also remove these checks in the dynamic resolver:

https://github.com/dotnet/runtime/blob/86719086d9fa65e004763b85a8bb560ec505ec2b/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/DynamicServiceProviderEngine.cs#L26

and 

https://github.com/dotnet/runtime/blob/86719086d9fa65e004763b85a8bb560ec505ec2b/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/DynamicServiceProviderEngine.cs#L39

**Review by davidfowl — APPROVED** [review]
