### PR TITLE
Fix assert for chain of ASG nodes after tail-calls

### LINKED ISSUE #59665: JIT: Libraries Regex PGO tests failing with assert
Libraries Regex PGO tests are failing with the following assert that tries to verify the post-tail-call IR in the jit is all stuff that we can safely ignore.

Seems to happen on a variety of os/arch combos. Linux x64 for instance.
```
COMPlus_ReadyToRun=0
COMPlus_TC_QuickJitForLoops=1
COMPlus_TieredCompilation=1
COMPlus_TieredPGO=1

dotnet exec --runtimeconfig System.Text.RegularExpressions.Tests.runtimeconfig.json --depsfile System.Text.RegularExpressions.Tests.deps.json xunit.console.dll System.Text.RegularExpressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 

  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 199 of 221 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 2)

Assert failure(PID 4906 [0x0000132a], Thread: 4912 [0x1330]): Assertion failed 'lcl == rhs->AsLclVarCommon()->GetLclNum()' in 'Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertyAccessorSymbol:get_AreLocalsZeroed():bool:this' during 'Morph - Global' (IL size 22)

    File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 7778
    Image: /datadisks/disk1/work/B24B09B5/p/dotnet
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/59665

We were saving incorrect value to lcl, it was supposed to be the left-side of ASG nodes.
It was changed here: https://github.com/dotnet/runtime/pull/51903/files#diff-5b83397bbbdd17bb9457998b520fdaaa474d165390985b66f32371561b6d0bacL7678

NOTE: it's a Checked-specific assert so I guess no need to backport this fix to 6.0

### CODE REVIEW

**Comment by EgorBo** [comment]
cc @AndyAyersMS @jakobbotsch

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -7773,7 +7773,7 @@ GenTree* Compiler::fgMorphPotentialTailCall(GenTreeCall* call)
                             }
 
                             assert(lcl == rhs->AsLclVarCommon()->GetLclNum());
-                            lcl = rhs->AsLclVarCommon()->GetLclNum();
+                            lcl = asgNode->gtGetOp1()->AsLclVarCommon()->GetLclNum();
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:7776]: This code took me quite a while to understand. I have a few of suggestions:
1. Can we rename `nextNextBlock` to `retBlock`?
2. Can we mark the parts that are debug only checks under #ifdef DEBUG? E.g. the loop above is debug only now.
3. Maybe add some comments with the shapes we allow? If I understand correctly we allow an arbitrary amount of blocks containing nops or successive assignments, so basically the allowed sequences are:
```
{ GT_ASG(t_0, GT_CALL(...)) }
{ GT_ASG(t_1, t0) } (with casts on rhs potentially)
...
{ GT_ASG(t_n, t_(n - 1)) }
{ GT_RET t_n }
...
```
? Do I understand that right?

By the way, it is unclear to me that we can allow all forms of casts here.

Comment (AndyAyersMS) [reply src/coreclr/jit/morph.cpp:7776]: This is a very late validation that the tail call is plausible based on the residual IR from the call site to the ret.

If the casts we see here shouldn't be allowed we should have have blocked the tail call earlier on.

Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp:7776]: Right, I get that this is validation, but even the validation code is overly relaxed since certain casts would not be safe to have. Given that, how useful is this validation? It also seems like it would look simpler in LIR.

Comment (AndyAyersMS) [reply src/coreclr/jit/morph.cpp:7776]: I don't think the validation is all that useful. I'd be fine if we just deleted it -- this is just the latest in a series of tweaks to keep it from reporting false positives.

Comment (EgorBo) [reply src/coreclr/jit/morph.cpp:7782]: I've addressed your feedback, feel free to remove it or move to lower, I was just wanting to unblock tests

**Review by jakobbotsch — APPROVED** [review]
