### PR TITLE
[NativeAOT] Fix floating pointer register unwinding

### LINKED ISSUE #116276: TimeSpan overflowed because the duration is too long.
```
System.OverflowException: TimeSpan overflowed because the duration is too long.
   at System.TimeSpan.op_Subtraction(TimeSpan, TimeSpan) + 0x34
   at Program.<<Main>$>g__TestExecutor123|0_124(StreamWriter tempLogSw, StreamWriter statsCsvSw, Program.<>c__DisplayClass0_0&) + 0x138
Failed test: JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1057538
Build error leg or test failing: JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll
Pull request: https://github.com/dotnet/runtime/pull/115339

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "TimeSpan overflowed because the duration is too long.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1057538
**Error message validated:** `[TimeSpan overflowed because the duration is too long. Runtime_108612`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/3/2025 6:28:20 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1057538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1057538)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1057538&view=ms.vss-test-web.build-test-results-tab&runId=28518044&resultId=119457)|dotnet/runtime#115339|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1057538
**Error message validated:** `[TimeSpan overflowed because the duration is too long.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/3/2025 7:45:55 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1057538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1057538)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1057538&view=ms.vss-test-web.build-test-results-tab&runId=28518044&resultId=119457)|dotnet/runtime#115339|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1093055](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1093055)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1093055&view=ms.vss-test-web.build-test-results-tab&runId=29807230&resultId=122160)||
|[1092504](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1092504)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1092504&view=ms.vss-test-web.build-test-results-tab&runId=29788120&resultId=108641)||
|[1091984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1091984)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1091984&view=ms.vss-test-web.build-test-results-tab&runId=29772578&resultId=120902)||
|[1089326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1089326)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1089326&view=ms.vss-test-web.build-test-results-tab&runId=29765954&resultId=115012)|dotnet/runtime#117315|
|[1090886](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1090886)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1090886&view=ms.vss-test-web.build-test-results-tab&runId=29726308&resultId=113400)||
|[1090289](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1090289)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1090289&view=ms.vss-test-web.build-test-results-tab&runId=29705248&resultId=117704)||
|[1088856](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1088856)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1088856&view=ms.vss-test-web.build-test-results-tab&runId=29662406&resultId=121822)||
|[1088184](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1088184)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1088184&view=ms.vss-test-web.build-test-results-tab&runId=29642890&resultId=112088)|dotnet/runtime#117315|
|[1088074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1088074)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1088074&view=ms.vss-test-web.build-test-results-tab&runId=29638740&resultId=118594)||
|[1086934](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1086934)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1086934&view=ms.vss-test-web.build-test-results-tab&runId=29597178&resultId=104691)||
|[1086742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1086742)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1086742&view=ms.vss-test-web.build-test-results-tab&runId=29587084&resultId=120452)|dotnet/runtime#117345|
|[1086695](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1086695)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1086695&view=ms.vss-test-web.build-test-results-tab&runId=29582240&resultId=107954)||
|[1086188](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1086188)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1086188&view=ms.vss-test-web.build-test-results-tab&runId=29565782&resultId=114594)||
|[1085899](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1085899)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1085899&view=ms.vss-test-web.build-test-results-tab&runId=29560786&resultId=119438)||
|[1085478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1085478)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1085478&view=ms.vss-test-web.build-test-results-tab&runId=29541904&resultId=100460)||
|[1083776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083776)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083776&view=ms.vss-test-web.build-test-results-tab&runId=29495652&resultId=121272)||
|[1083496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083496)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083496&view=ms.vss-test-web.build-test-results-tab&runId=29483534&resultId=101884)|dotnet/runtime#117187|
|[1083461](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083461)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083461&view=ms.vss-test-web.build-test-results-tab&runId=29483334&resultId=102953)|dotnet/runtime#116903|
|[1082689](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082689)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082689&view=ms.vss-test-web.build-test-results-tab&runId=29461052&resultId=112562)||
|[1082528](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082528)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082528&view=ms.vss-test-web.build-test-results-tab&runId=29450506&resultId=119682)|dotnet/runtime#117130|
|[1082282](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082282)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082282&view=ms.vss-test-web.build-test-results-tab&runId=29443930&resultId=121130)||
|[1081472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081472)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081472&view=ms.vss-test-web.build-test-results-tab&runId=29418216&resultId=121713)|dotnet/runtime#117139|
|[1081379](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081379)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081379&view=ms.vss-test-web.build-test-results-tab&runId=29407146&resultId=113594)||
|[1081246](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081246)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081246&view=ms.vss-test-web.build-test-results-tab&runId=29398452&resultId=113290)||
|[1081213](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081213)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081213&view=ms.vss-test-web.build-test-results-tab&runId=29397176&resultId=120353)|dotnet/runtime#117125|
|[1080947](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1080947)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1080947&view=ms.vss-test-web.build-test-results-tab&runId=29387172&resultId=121328)||
|[1080534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1080534)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1080534&view=ms.vss-test-web.build-test-results-tab&runId=29380814&resultId=120848)||
|[1079346](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1079346)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1079346&view=ms.vss-test-web.build-test-results-tab&runId=29338572&resultId=107230)||
|[1079031](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1079031)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1079031&view=ms.vss-test-web.build-test-results-tab&runId=29334312&resultId=120260)|dotnet/runtime#116903|
|[1078662](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1078662)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1078662&view=ms.vss-test-web.build-test-results-tab&runId=29322948&resultId=121114)||
|[1077870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1077870)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1077870&view=ms.vss-test-web.build-test-results-tab&runId=29292512&resultId=112781)|dotnet/runtime#116310|
|[1077576](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1077576)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1077576&view=ms.vss-test-web.build-test-results-tab&runId=29281206&resultId=120016)|dotnet/runtime#116958|
|[1077219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1077219)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1077219&view=ms.vss-test-web.build-test-results-tab&runId=29254316&resultId=115310)|dotnet/runtime#116865|
|[1077214](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1077214)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1077214&view=ms.vss-test-web.build-test-results-tab&runId=29254310&resultId=120585)|dotnet/runtime#116958|
|[1076870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1076870)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1076870&view=ms.vss-test-web.build-test-results-tab&runId=29237062&resultId=120827)|dotnet/runtime#116961|
|[1073281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1073281)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1073281&view=ms.vss-test-web.build-test-results-tab&runId=29104802&resultId=106969)||
|[1072917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1072917)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1072917&view=ms.vss-test-web.build-test-results-tab&runId=29098022&resultId=118592)||
|[1071237](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1071237)|dotnet/runtime|[JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1071237&view=ms.vss-test-web.build-test-results-tab&runId=29020774&resultId=113461)||
|[1070592](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1070592)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1070592&view=ms.vss-test-web.build-test-results-tab&runId=28995136&resultId=118450)||
|[1069986](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1069986)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1069986&view=ms.vss-test-web.build-test-results-tab&runId=28974890&resultId=105745)||
|[1068594](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1068594)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1068594&view=ms.vss-test-web.build-test-results-tab&runId=28916092&resultId=115121)||
|[1068498](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1068498)|dotnet/runtime|[JIT/Regression/JitBlue/Runtime_108612/Runtime_108612/Runtime_108612.dll](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1068498&view=ms.vss-test-web.build-test-results-tab&runId=28911178&resultId=112117)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|9|42|

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #116276

### CODE REVIEW

**Comment by risc-vv** [comment]
@dotnet/samsung Could you please take a look? These changes may be related to riscv64.

**Comment by jkotas** [comment]
The unwinder tried to treat floating point registers as vector registers. It led to all sorts of problems with storage size (8 byte storage for double vs. 16 byte storage for vector registers).

This bug was originally introduced by https://github.com/dotnet/corert/pull/8290/ . It is surprising that it took years to uncover it.

The bug got copied from arm64 unwinder to arm, riscv and loongarch unwinders in various forms. I have fixed those as well.

**Comment by risc-vv** [comment]
<details>
<summary>RISC-V Release-CLR-QEMU: 9083 / 9113 (99.67%)</summary>

```
=======================
      passed: 9083
      failed: 2
     skipped: 597
      killed: 28
------------------------
 TOTAL tests: 9710
VIRTUAL time: 37h 33min 25s 850ms
   REAL time: 38min 15s 882ms
=======================
```
[report.xml](https://gist.githubusercontent.com/risc-vv/f59d1152b8f5b92d5b1b1b32223a9557/raw/3fd5801aef4a9b25066594b7fcc49d330a027dd0/Release-CLR-QEMU-a76fcf3a5593a61df9555e5e1202244b46d29877.xml), [report.md](https://gist.githubusercontent.com/risc-vv/855d6e77ec02f575e7475e09305e5c5a/raw/b3b6130a6f28121d04293b5f3f6db27511eb2e53/Release-CLR-QEMU-a76fcf3a5593a61df9555e5e1202244b46d29877.md), [failures.xml](http://127.0.0.1/pipelines/Release-CLR-QEMU/274/run-tests/1/run-tests/failures.xml), [testclr_details.tar.zst](http://127.0.0.1/pipelines/Release-CLR-QEMU/274/run-tests/1/run-tests/testclr_details.Release.tar.zst)
</details>
<details>
<summary>RISC-V Release-CLR-VF2: 9084 / 9114 (99.67%)</summary>

```
=======================
      passed: 9084
      failed: 2
     skipped: 597
      killed: 28
------------------------
 TOTAL tests: 9711
VIRTUAL time: 11h 58min 52s 922ms
   REAL time: 48min 22s 894ms
=======================
```
[report.xml](https://gist.githubusercontent.com/risc-vv/54f7d178acfee47c804129512fedc318/raw/eeba45f6d0dae36038876284b051adef9c95ca78/Release-CLR-VF2-a76fcf3a5593a61df9555e5e1202244b46d29877.xml), [report.md](https://gist.githubusercontent.com/risc-vv/b37d69ed61d0acf5a331618468d181d5/raw/0896d018231076718ef11144d0afb40812b2ea4d/Release-CLR-VF2-a76fcf3a5593a61df9555e5e1202244b46d29877.md), [failures.xml](http://127.0.0.1/pipelines/Release-CLR-VF2/282/run-tests/1/run-tests/failures.xml), [testclr_details.tar.zst](http://127.0.0.1/pipelines/Release-CLR-VF2/282/run-tests/1/run-tests/testclr_details.Release.tar.zst)
</details>
<details>
<summary>RISC-V Release-FX-QEMU: 283771 / 284850 (99.62%)</summary>

```
=======================
      passed: 283771
      failed: 1070
     skipped: 39
      killed: 9
------------------------
 TOTAL tests: 284889
VIRTUAL time: 32h 18min 24s 649ms
   REAL time: 1h 10min 32s 31ms
=======================
```
[report.xml](https://gist.githubusercontent.com/risc-vv/5da7c7ee001dc676769d5cb65466ab9f/raw/1afe7533202007dc41967d41d8d53cfda111f6f7/Release-FX-QEMU-a76fcf3a5593a61df9555e5e1202244b46d29877.xml), [report.md](https://gist.githubusercontent.com/risc-vv/3243eba7b97b7459779e15027f2347fd/raw/aa24d10966ad3c43488f751ab40c1f7f6c27c419/Release-FX-QEMU-a76fcf3a5593a61df9555e5e1202244b46d29877.md), [failures.xml](http://127.0.0.1/pipelines/Release-FX-QEMU/259/run-tests/1/run-tests/failures.xml), [testclr_details.tar.zst](http://127.0.0.1/pipelines/Release-FX-QEMU/259/run-tests/1/run-tests/testfx_details.Release.tar.zst)
</details>
<details>
<summary>RISC-V Release-FX-VF2: 309260 / 311009 (99.44%)</summary>

```
=======================
      passed: 309260
      failed: 1741
     skipped: 39
      killed: 8
------------------------
 TOTAL tests: 311048
VIRTUAL time: 21h 18min 26s 682ms
   REAL time: 2h 10min 49s 503ms
=======================
```
[report.xml](https://gist.githubusercontent.com/risc-vv/aa70155c221f32d4f3f838ccd634eb96/raw/33ad30a335c246193f27bbea6f060d4219e21b6e/Release-FX-VF2-a76fcf3a5593a61df9555e5e1202244b46d29877.xml), [report.md](https://gist.githubusercontent.com/risc-vv/df39f32bf832ef6e678d497b7ac9731e/raw/986b5ff7fefaefe7610ab7d590605f310f579d22/Release-FX-VF2-a76fcf3a5593a61df9555e5e1202244b46d29877.md), [failures.xml](http://127.0.0.1/pipelines/Release-FX-VF2/254/run-tests/1/run-tests/failures.xml), [testclr_details.tar.zst](http://127.0.0.1/pipelines/Release-FX-VF2/254/run-tests/1/run-tests/testfx_details.Release.tar.zst)
</details><details>
<summary>Build information and commands</summary>

GIT: `a76fcf3a5593a61df9555e5e1202244b46d29877`
CI: `d6c9c1ab3a7411819463edc05ded301e89ba586a`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: `main`
CONFIG: `Release`
LIB_CONFIG: `Release`

</details>

File: src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp [hunk 1]
```diff
@@ -25,6 +25,15 @@
 #endif
 #include <external/llvm-libunwind/src/UnwindCursor.hpp>
 
+template <class To, class From>
+inline To unwindhelpers_bitcast(From from)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp:29]: This is needed to convert double (used by libunwind) to uint64 bits (used by PAL_LIMITED_CONTEXT), and vice versa.

**Comment by filipnavara** [comment]
Wow, amazing work on getting to the bottom of it!

(I guess I'll need to re-read the DWARF specs to figure out how platforms with overlapping vector and FP registers should behave. _I assume that most platforms don't save the high bits of vector registers but I am not sure if that's universally true._)

**Comment by jkotas** [comment]
> I assume that most platforms don't save the high bits of vector registers but I am not sure if that's universally true.

Right, it is the case for default calling conventions of all platforms that we support currently.

**Comment by filipnavara** [comment]
It rechecked the specs and seems to be fine for ARM64 and LA64.

RV64 ratified an optional vector calling convention last year (https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#calling-convention-variant) so we may eventually need to support that. However, that was already broken prior to this PR and I don't have any hardware or toolchain that supports this. (cc @am11 FYI)

**Review by filipnavara — APPROVED** [review]

**Comment by am11** [comment]
> However, that was already broken prior to this PR

I think we are not emitting RVV types from JIT and neither are we compiling with `rv64gcv` (yet).

> I don't have any hardware or toolchain that supports this.

Going by https://godbolt.org/z/d43s88nfE, at least it seems to know how to pass RVV types in v‑register.

File: src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp [hunk 2]
```diff
@@ -25,6 +25,15 @@
...
+{
+  static_assert(sizeof(From)==sizeof(To), "Sizes must match");
+
+  To to;
+  memcpy(&to, &from, sizeof(To));
+  return to;
```
Comment (am11) [inline src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp]: nit: four space indent.

Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/unix/UnwindHelpers.cpp]:
```suggestion
    static_assert(sizeof(From)==sizeof(To), "Sizes must match");

    To to;
    memcpy(&to, &from, sizeof(To));
    return to;
```

**Comment by risc-vv** [comment]
<details>
<summary>RISC-V Release-CLR-VF2: 9083 / 9113 (99.67%)</summary>

```
=======================
      passed: 9083
      failed: 2
     skipped: 597
      killed: 28
------------------------
 TOTAL tests: 9710
VIRTUAL time: 11h 5min 47s 145ms
   REAL time: 45min 18s 492ms
=======================
```
[report.xml](https://gist.githubusercontent.com/risc-vv/5c3e27d038f7881633ca22eef9298963/raw/1c15ea9c58f8e87ae377fe79bfd3e42845314cb4/Release-CLR-VF2-5543649c55213eef586b31081a059b12ee0af99f.xml), [report.md](https://gist.githubusercontent.com/risc-vv/88fe3a9180c56aaf4e60c3abe63b576b/raw/d3a92bd1ab02f7e49ce1ac99c281cdf9eaf9b4c2/Release-CLR-VF2-5543649c55213eef586b31081a059b12ee0af99f.md), [failures.xml](http://127.0.0.1/pipelines/Release-CLR-VF2/283/run-tests/1/run-tests/failures.xml), [testclr_details.tar.zst](http://127.0.0.1/pipelines/Release-CLR-VF2/283/run-tests/1/run-tests/testclr_details.Release.tar.zst)
</details>
<details>
<summary>RISC-V Release-FX-QEMU: 283858 / 284941 (99.62%)</summary>

```
=======================
      passed: 283858
      failed: 1074
     skipped: 39
      killed: 9
------------------------
 TOTAL tests: 284980
VIRTUAL time: 32h 34min 23s 945ms
   REAL time: 1h 11min 0s 439ms
=======================
```
[report.xml](https://gist.githubusercontent.com/risc-vv/a6502aca1dd140f1d26fb7e9c3e904d9/raw/e213f9055ec9d78ab56933386c04a02f351ad588/Release-FX-QEMU-5543649c55213eef586b31081a059b12ee0af99f.xml), [report.md](https://gist.githubusercontent.com/risc-vv/ba94ddfd5f60ecb46c79aed439318663/raw/a394d294a8eb9d74e755f8b1e7d7ef61a1e2fb65/Release-FX-QEMU-5543649c55213eef586b31081a059b12ee0af99f.md), [failures.xml](http://127.0.0.1/pipelines/Release-FX-QEMU/260/run-tests/1/run-tests/failures.xml), [testclr_details.tar.zst](http://127.0.0.1/pipelines/Release-FX-QEMU/260/run-tests/1/run-tests/testfx_details.Release.tar.zst)
</details><details>
<summary>Build information and commands</summary>

GIT: `5543649c55213eef586b31081a059b12ee0af99f`
CI: `d6c9c1ab3a7411819463edc05ded301e89ba586a`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: `main`
CONFIG: `Release`
LIB_CONFIG: `Release`

</details>

**Comment by jkotas** [comment]
> RV64 ratified an optional vector calling convention last year (https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#calling-convention-variant) so we may eventually need to support that. 

It is in the same category as https://github.com/dotnet/runtime/issues/8300 or https://github.com/dotnet/runtime/issues/5040 . 

Also, RISCV vector extension is variable length like ARM SVE, so I expect we would want to finish implementing ARM SVE first and then base RISCV vector extension on that.

**Comment by filipnavara** [comment]
> I think we are not emitting RVV types from JIT and neither are we compiling with `rv64gcv` (yet).

Right. I don't think there's currently a code path that could hit it.

> It is in the same category as https://github.com/dotnet/runtime/issues/8300 or https://github.com/dotnet/runtime/issues/5040 .

I was thinking more in the terms of unwinding native code like the GC poll code path. We likely cannot hit any vectorized code there (yet).

**Review by janvorli — APPROVED** [review]
LGTM, thank you!
