### PR TITLE
Fix Windows AccessViolationException in FileSystemWatcher when monitoring network share for changes

### LINKED ISSUE #40412: w3wp.exe crash in FileSystemWatcher after 2.2 -> 3.1 migration (c0000005 Access Violation)
We've started seeing several crashes in production services after migrating from 2.2 to 3.1. The services run fine for several hours but then will suddenly crash and recycle.

For example:

```
Dump Summary
------------
Dump File:	memory.hdmp : C:\tmp\dumps\Dump1\memory.hdmp
Last Write Time:	8/3/2020 11:35:41 AM
Process Name:	w3wp.exe : c:\Windows\System32\inetsrv\w3wp.exe
Process Architecture:	x64
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Present

System Information
------------------
OS Version:	6.3.9600
CLR Version(s):	4.700.20.26901

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
w3wp.exe	c:\Windows\System32\inetsrv\w3wp.exe	8.5.9600.16384
ntdll.dll	C:\Windows\System32\ntdll.dll	6.3.9600.19678
kernel32.dll	C:\Windows\System32\kernel32.dll	6.3.9600.19719
CyMemDef64.dll	C:\Program Files\Cylance\Desktop\CyMemDef64.dll	2.0.1530.14
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.3.9600.19724
sysfer.dll	C:\Windows\System32\sysfer.dll	14.3.227.0
advapi32.dll	C:\Windows\System32\advapi32.dll	6.3.9600.18895
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.9600.17415
combase.dll	C:\Windows\System32\combase.dll	6.3.9600.19724
iisutil.dll	c:\Windows\System32\inetsrv\iisutil.dll	8.5.9600.19467
sechost.dll	C:\Windows\System32\sechost.dll	6.3.9600.19749
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.3.9600.19538
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.3.9600.18340
sspicli.dll	C:\Windows\System32\sspicli.dll	6.3.9600.17415
pcwum.dll	C:\Windows\System32\pcwum.dll	6.3.9600.16384
nsi.dll	C:\Windows\System32\nsi.dll	6.3.9600.17415
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	6.3.9600.17415
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	6.3.9600.17415
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.3.9600.18895
ntmarta.dll	C:\Windows\System32\ntmarta.dll	6.3.9600.17415
user32.dll	C:\Windows\System32\user32.dll	6.3.9600.19747
gdi32.dll	C:\Windows\System32\gdi32.dll	6.3.9600.19758
w3wphost.dll	c:\Windows\System32\inetsrv\w3wphost.dll	8.5.9600.18538
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.3.9600.19750
nativerd.dll	c:\Windows\System32\inetsrv\nativerd.dll	8.5.9600.19467
xmllite.dll	C:\Windows\System32\xmllite.dll	6.3.9600.19416
ktmw32.dll	C:\Windows\System32\ktmw32.dll	6.3.9600.17415
iisres.dll	c:\Windows\System32\inetsrv\iisres.dll	8.5.9600.16384
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.3.9600.17415
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.3.9600.18191
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.3.9600.18541
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10530.17415
mlang.dll	C:\Windows\System32\mlang.dll	6.3.9600.17415
iiscore.dll	C:\Windows\System32\inetsrv\iiscore.dll	8.5.9600.18735
w3tp.dll	c:\Windows\System32\inetsrv\w3tp.dll	8.5.9600.18538
w3dt.dll	c:\Windows\System32\inetsrv\w3dt.dll	8.5.9600.18735
httpapi.dll	C:\Windows\System32\httpapi.dll	6.3.9600.17415
NapiNSP.dll	C:\Windows\System32\NapiNSP.dll	6.3.9600.17415
nlaapi.dll	C:\Windows\System32\nlaapi.dll	6.3.9600.18895
mswsock.dll	C:\Windows\System32\mswsock.dll	6.3.9600.18340
dnsapi.dll	C:\Windows\System32\dnsapi.dll	6.3.9600.19060
winrnr.dll	C:\Windows\System32\winrnr.dll	6.3.9600.17415
rasadhlp.dll	C:\Windows\System32\rasadhlp.dll	6.3.9600.17415
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	6.3.9600.18264
winnsi.dll	C:\Windows\System32\winnsi.dll	6.3.9600.17415
FWPUCLNT.DLL	C:\Windows\System32\FWPUCLNT.DLL	6.3.9600.19644
cachuri.dll	C:\Windows\System32\inetsrv\cachuri.dll	8.5.9600.16384
cachfile.dll	C:\Windows\System32\inetsrv\cachfile.dll	8.5.9600.16384
cachtokn.dll	C:\Windows\System32\inetsrv\cachtokn.dll	8.5.9600.16384
cachhttp.dll	C:\Windows\System32\inetsrv\cachhttp.dll	8.5.9600.16384
compstat.dll	C:\Windows\System32\inetsrv\compstat.dll	8.5.9600.16384
defdoc.dll	C:\Windows\System32\inetsrv\defdoc.dll	8.5.9600.16384
dirlist.dll	C:\Windows\System32\inetsrv\dirlist.dll	8.5.9600.16384
protsup.dll	C:\Windows\System32\inetsrv\protsup.dll	8.5.9600.16384
static.dll	C:\Windows\System32\inetsrv\static.dll	8.5.9600.16384
authanon.dll	C:\Windows\System32\inetsrv\authanon.dll	8.5.9600.16384
modrqflt.dll	C:\Windows\System32\inetsrv\modrqflt.dll	8.5.9600.19364
custerr.dll	C:\Windows\System32\inetsrv\custerr.dll	8.5.9600.18591
loghttp.dll	C:\Windows\System32\inetsrv\loghttp.dll	8.5.9600.16384
isapi.dll	C:\Windows\System32\inetsrv\isapi.dll	8.5.9600.16384
filter.dll	C:\Windows\System32\inetsrv\filter.dll	8.5.9600.16384
validcfg.dll	C:\Windows\System32\inetsrv\validcfg.dll	8.5.9600.16384
aspnetcore.dll	C:\Windows\System32\inetsrv\aspnetcore.dll	12.2.18316.0
winhttp.dll	C:\Windows\System32\winhttp.dll	6.3.9600.19254
authsspi.dll	C:\Windows\System32\inetsrv\authsspi.dll	8.5.9600.16384
wkscli.dll	C:\Windows\System32\wkscli.dll	6.3.9600.17415
netutils.dll	C:\Windows\System32\netutils.dll	6.3.9600.17415
warmup.dll	C:\Windows\System32\inetsrv\warmup.dll	8.5.9600.16384
aspnetcorev2.dll	C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll	13.1.20169.6
api-ms-win-crt-heap-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-heap-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-runtime-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-runtime-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-stdio-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-stdio-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-string-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-string-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-filesystem-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-filesystem-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-math-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-math-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-convert-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-convert-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-locale-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-locale-l1-1-0.dll	10.0.14393.2247
shell32.dll	C:\Windows\System32\shell32.dll	6.3.9600.19750
version.dll	C:\Windows\System32\version.dll	6.3.9600.17415
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.3.9600.17415
ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	10.0.14393.2990
crypt32.dll	C:\Windows\System32\crypt32.dll	6.3.9600.18653
msasn1.dll	C:\Windows\System32\msasn1.dll	6.3.9600.17415
dpapi.dll	C:\Windows\System32\dpapi.dll	6.3.9600.17415
gzip.dll	C:\Windows\System32\inetsrv\gzip.dll	8.5.9600.16384
hostfxr.dll	C:\Program Files\dotnet\host\fxr\3.1.6\hostfxr.dll	3.100.620.31604
api-ms-win-crt-time-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-time-l1-1-0.dll	10.0.14393.2247
hostpolicy.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\hostpolicy.dll	3.100.620.31604
aspnetcorev2_inprocess.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\aspnetcorev2_inprocess.dll	13.1.20169.6
coreclr.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\coreclr.dll	4.700.20.26901
ole32.dll	C:\Windows\System32\ole32.dll	6.3.9600.19724
api-ms-win-crt-utility-l1-1-0.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\api-ms-win-crt-utility-l1-1-0.dll	10.0.17134.12
System.Private.CoreLib.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Private.CoreLib.dll	4.700.20.26901
clrjit.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\clrjit.dll	4.700.20.26901
ECIFileMonitor.dll	D:\webapps\ECI_FileMonitor\ECIFileMonitor.dll	1.0.0.0
System.Runtime.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.dll	4.700.20.31603
Microsoft.AspNetCore.Server.IIS.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Server.IIS.dll	3.100.620.31714
System.Runtime.Extensions.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.Extensions.dll	4.700.20.31603
Microsoft.Extensions.Hosting.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Hosting.Abstractions.dll	3.100.620.31605
Microsoft.Extensions.Hosting.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Hosting.dll	3.100.620.31605
Microsoft.AspNetCore.Hosting.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Hosting.Abstractions.dll	3.100.620.31714
Microsoft.AspNetCore.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.dll	3.100.620.31714
Microsoft.Extensions.DependencyInjection.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.DependencyInjection.dll	3.100.620.31605
Microsoft.Extensions.Configuration.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Configuration.Abstractions.dll	3.100.620.31605
Microsoft.Extensions.DependencyInjection.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.DependencyInjection.Abstractions.dll	3.100.620.31605
Microsoft.Extensions.Logging.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Logging.dll	3.100.620.31605
System.Collections.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Collections.dll	4.700.20.31603
netstandard.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\netstandard.dll	4.700.20.31603
System.ComponentModel.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.ComponentModel.dll	4.700.20.31603
System.IO.FileSystem.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.IO.FileSystem.dll	4.700.20.31603
Microsoft.AspNetCore.Hosting.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Hosting.dll	3.100.620.31714
Microsoft.Extensions.Configuration.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Configuration.dll	3.100.620.31605
Microsoft.Extensions.Configuration.EnvironmentVariables.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Configuration.EnvironmentVariables.dll	3.100.620.31605
Microsoft.Extensions.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Primitives.dll	3.100.620.31605
System.Threading.Tasks.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Threading.Tasks.dll	4.700.20.31603
System.Linq.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Linq.dll	4.700.20.31603
System.Threading.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Threading.dll	4.700.20.31603
Microsoft.AspNetCore.Server.Kestrel.Core.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Server.Kestrel.Core.dll	3.100.620.31714
Microsoft.AspNetCore.Server.Kestrel.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Server.Kestrel.dll	3.100.620.31714
System.Runtime.InteropServices.RuntimeInformation.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.InteropServices.RuntimeInformation.dll	4.700.20.31603
Microsoft.AspNetCore.Server.IISIntegration.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Server.IISIntegration.dll	3.100.620.31714
Serilog.AspNetCore.dll	D:\webapps\ECI_FileMonitor\Serilog.AspNetCore.dll	3.2.0.0
Serilog.dll	D:\webapps\ECI_FileMonitor\Serilog.dll	2.9.0.0
Serilog.Extensions.Logging.dll	D:\webapps\ECI_FileMonitor\Serilog.Extensions.Logging.dll	3.0.1.0
Microsoft.Extensions.Configuration.CommandLine.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Configuration.CommandLine.dll	3.100.620.31605
Microsoft.AspNetCore.Mvc.Core.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.Core.dll	3.100.620.31714
Microsoft.Extensions.FileProviders.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.FileProviders.Abstractions.dll	3.100.620.31605
Microsoft.Extensions.FileProviders.Physical.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.FileProviders.Physical.dll	3.100.620.31605
System.Memory.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Memory.dll	4.700.20.31603
Microsoft.Extensions.Configuration.FileExtensions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Configuration.FileExtensions.dll	3.100.620.31605
Microsoft.Extensions.Configuration.Json.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Configuration.Json.dll	3.100.620.31605
System.Runtime.InteropServices.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.InteropServices.dll	4.700.20.31603
System.IO.FileSystem.Watcher.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.IO.FileSystem.Watcher.dll	4.700.20.31603
System.ComponentModel.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.ComponentModel.Primitives.dll	4.700.20.31603
System.Collections.Concurrent.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Collections.Concurrent.dll	4.700.20.31603
Microsoft.Extensions.FileSystemGlobbing.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.FileSystemGlobbing.dll	3.100.620.31605
System.Threading.Timer.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Threading.Timer.dll	4.700.20.31603
System.Threading.Overlapped.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Threading.Overlapped.dll	4.700.20.31603
Microsoft.Win32.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\Microsoft.Win32.Primitives.dll	4.700.20.31603
System.Text.Json.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Text.Json.dll	4.700.20.31603
System.Text.Encoding.Extensions.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Text.Encoding.Extensions.dll	4.700.20.31603
System.Buffers.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Buffers.dll	4.700.20.31603
System.Numerics.Vectors.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Numerics.Vectors.dll	4.700.20.31603
System.Runtime.CompilerServices.Unsafe.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.CompilerServices.Unsafe.dll	4.700.20.31603
Microsoft.Extensions.Options.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Options.dll	3.100.620.31605
Microsoft.Extensions.Logging.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Logging.Abstractions.dll	3.100.620.31605
Microsoft.Extensions.Logging.EventLog.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Logging.EventLog.dll	3.100.620.31605
Microsoft.Extensions.Logging.Configuration.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Logging.Configuration.dll	3.100.620.31605
Microsoft.Extensions.Options.ConfigurationExtensions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Options.ConfigurationExtensions.dll	3.100.620.31605
Microsoft.Extensions.Logging.Console.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Logging.Console.dll	3.100.620.31605
Microsoft.Extensions.Logging.Debug.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Logging.Debug.dll	3.100.620.31605
Microsoft.Extensions.Logging.EventSource.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Logging.EventSource.dll	3.100.620.31605
System.Diagnostics.Tracing.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Diagnostics.Tracing.dll	4.700.20.31603
System.Diagnostics.DiagnosticSource.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Diagnostics.DiagnosticSource.dll	4.700.20.31603
Microsoft.AspNetCore.Http.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Http.Abstractions.dll	3.100.620.31714
Microsoft.AspNetCore.Http.Features.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Http.Features.dll	3.100.620.31714
Microsoft.AspNetCore.Http.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Http.dll	3.100.620.31714
Microsoft.AspNetCore.Connections.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Connections.Abstractions.dll	3.100.620.31714
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll	3.100.620.31714
System.Net.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Net.Primitives.dll	4.700.20.31603
Microsoft.AspNetCore.Hosting.Server.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll	3.100.620.31714
Microsoft.AspNetCore.HostFiltering.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.HostFiltering.dll	3.100.620.31714
Microsoft.AspNetCore.HttpOverrides.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.HttpOverrides.dll	3.100.620.31714
Microsoft.AspNetCore.Routing.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Routing.dll	3.100.620.31714
Microsoft.Extensions.ObjectPool.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.ObjectPool.dll	3.100.620.31605
Microsoft.AspNetCore.Routing.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Routing.Abstractions.dll	3.100.620.31714
System.ObjectModel.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.ObjectModel.dll	4.700.20.31603
Microsoft.AspNetCore.Authentication.Core.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Authentication.Core.dll	3.100.620.31714
Microsoft.AspNetCore.Authentication.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Authentication.Abstractions.dll	3.100.620.31714
System.Security.Claims.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Security.Claims.dll	4.700.20.31603
Txm.Cdc.Configuration.dll	D:\webapps\ECI_FileMonitor\Txm.Cdc.Configuration.dll	1.0.3.0
Microsoft.Extensions.Configuration.Binder.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Configuration.Binder.dll	3.100.620.31605
System.ComponentModel.TypeConverter.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.ComponentModel.TypeConverter.dll	4.700.20.31603
System.Collections.Specialized.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Collections.Specialized.dll	4.700.20.31603
System.Private.Uri.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Private.Uri.dll	4.700.20.31603
System.Drawing.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Drawing.Primitives.dll	4.700.20.31603
System.Net.Http.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Net.Http.dll	4.700.20.31603
Txm.Cdc.AspNetCore.dll	D:\webapps\ECI_FileMonitor\Txm.Cdc.AspNetCore.dll	1.0.0.0
Microsoft.Extensions.Http.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Http.dll	3.100.620.31605
Polly.dll	D:\webapps\ECI_FileMonitor\Polly.dll	7.2.1.0
Newtonsoft.Json.dll	D:\webapps\ECI_FileMonitor\Newtonsoft.Json.dll	12.0.3.23909
Txm.Cdc.Logging.dll	D:\webapps\ECI_FileMonitor\Txm.Cdc.Logging.dll	1.0.2.0
Microsoft.AspNetCore.Mvc.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.dll	3.100.620.31714
Microsoft.AspNetCore.HttpsPolicy.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.HttpsPolicy.dll	3.100.620.31714
Swashbuckle.AspNetCore.SwaggerGen.dll	D:\webapps\ECI_FileMonitor\Swashbuckle.AspNetCore.SwaggerGen.dll	5.5.1.0
Microsoft.AspNetCore.Authentication.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Authentication.dll	3.100.620.31714
Microsoft.AspNetCore.Authentication.JwtBearer.dll	D:\webapps\ECI_FileMonitor\Microsoft.AspNetCore.Authentication.JwtBearer.dll	3.100.520.27105
Microsoft.AspNetCore.Authorization.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Authorization.dll	3.100.620.31714
Microsoft.AspNetCore.Authorization.Policy.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Authorization.Policy.dll	3.100.620.31714
Microsoft.Extensions.Http.Polly.dll	D:\webapps\ECI_FileMonitor\Microsoft.Extensions.Http.Polly.dll	3.100.520.27009
Polly.Extensions.Http.dll	D:\webapps\ECI_FileMonitor\Polly.Extensions.Http.dll	3.0.0.0
System.Reflection.Emit.Lightweight.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Reflection.Emit.Lightweight.dll	4.700.20.31603
System.Console.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Console.dll	4.700.20.31603
System.Threading.Thread.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Threading.Thread.dll	4.700.20.31603
System.Diagnostics.EventLog.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\System.Diagnostics.EventLog.dll	4.700.19.56404
System.Net.Security.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Net.Security.dll	4.700.20.31603
System.Security.Cryptography.X509Certificates.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Security.Cryptography.X509Certificates.dll	4.700.20.31603
System.Linq.Expressions.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Linq.Expressions.dll	4.700.20.31603
System.Reflection.Emit.ILGeneration.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Reflection.Emit.ILGeneration.dll	4.700.20.31603
System.Reflection.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Reflection.Primitives.dll	4.700.20.31603
System.Diagnostics.Debug.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Diagnostics.Debug.dll	4.700.20.31603
dhcpcsvc6.DLL	C:\Windows\System32\dhcpcsvc6.DLL	6.3.9600.19423
dhcpcsvc.dll	C:\Windows\System32\dhcpcsvc.dll	6.3.9600.19423
System.Text.RegularExpressions.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Text.RegularExpressions.dll	4.700.20.31603
System.Net.Sockets.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Net.Sockets.dll	4.700.20.31603
System.Net.NameResolution.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Net.NameResolution.dll	4.700.20.31603
System.Security.Cryptography.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Security.Cryptography.Primitives.dll	4.700.20.31603
System.Collections.NonGeneric.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Collections.NonGeneric.dll	4.700.20.31603
System.Security.Principal.Windows.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Security.Principal.Windows.dll	4.700.20.31603
System.Security.Principal.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Security.Principal.dll	4.700.20.31603
schannel.dll	C:\Windows\System32\schannel.dll	6.3.9600.19747
normaliz.dll	C:\Windows\System32\normaliz.dll	6.3.9600.17415
System.Threading.ThreadPool.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Threading.ThreadPool.dll	4.700.20.31603
ncrypt.dll	C:\Windows\System32\ncrypt.dll	6.3.9600.18970
ntasn1.dll	C:\Windows\System32\ntasn1.dll	6.3.9600.17415
ncryptsslp.dll	C:\Windows\System32\ncryptsslp.dll	6.3.9600.19420
System.Security.Cryptography.Encoding.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Security.Cryptography.Encoding.dll	4.700.20.31603
gpapi.dll	C:\Windows\System32\gpapi.dll	6.3.9600.18339
System.Runtime.Serialization.Formatters.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.Serialization.Formatters.dll	4.700.20.31603
System.Diagnostics.TraceSource.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Diagnostics.TraceSource.dll	4.700.20.31603
System.Runtime.Numerics.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.Numerics.dll	4.700.20.31603
System.Runtime.Serialization.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.Serialization.Primitives.dll	4.700.20.31603
System.Data.Common.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Data.Common.dll	4.700.20.31603
System.Xml.ReaderWriter.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Xml.ReaderWriter.dll	4.700.20.31603
System.Private.Xml.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Private.Xml.dll	4.700.20.31603
secur32.dll	C:\Windows\System32\secur32.dll	6.3.9600.17415
Serilog.Enrichers.Thread.dll	D:\webapps\ECI_FileMonitor\Serilog.Enrichers.Thread.dll	3.1.0.0
Serilog.Enrichers.Environment.dll	D:\webapps\ECI_FileMonitor\Serilog.Enrichers.Environment.dll	2.1.3.0
Serilog.Exceptions.dll	D:\webapps\ECI_FileMonitor\Serilog.Exceptions.dll	5.5.0.0
Serilog.Sinks.Debug.dll	D:\webapps\ECI_FileMonitor\Serilog.Sinks.Debug.dll	1.0.1.0
Serilog.Sinks.Elasticsearch.dll	D:\webapps\ECI_FileMonitor\Serilog.Sinks.Elasticsearch.dll	8.1.0.0
Serilog.Sinks.File.dll	D:\webapps\ECI_FileMonitor\Serilog.Sinks.File.dll	4.1.0.0
System.Text.Encoding.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Text.Encoding.dll	4.700.20.31603
Serilog.Sinks.TestCorrelator.dll	D:\webapps\ECI_FileMonitor\Serilog.Sinks.TestCorrelator.dll	3.2.0.0
Serilog.Sinks.Console.dll	D:\webapps\ECI_FileMonitor\Serilog.Sinks.Console.dll	3.1.1.0
System.Resources.ResourceManager.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Resources.ResourceManager.dll	4.700.20.31603
System.Globalization.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Globalization.dll	4.700.20.31603
System.IO.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.IO.dll	4.700.20.31603
System.IO.FileSystem.Primitives.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.IO.FileSystem.Primitives.dll	4.700.20.31603
Microsoft.AspNetCore.Mvc.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.Abstractions.dll	3.100.620.31714
Microsoft.AspNetCore.Mvc.ApiExplorer.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.ApiExplorer.dll	3.100.620.31714
Microsoft.AspNetCore.Mvc.Cors.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.Cors.dll	3.100.620.31714
Microsoft.AspNetCore.Cors.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Cors.dll	3.100.620.31714
Microsoft.AspNetCore.Mvc.DataAnnotations.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.DataAnnotations.dll	3.100.620.31714
Microsoft.AspNetCore.Mvc.ViewFeatures.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.ViewFeatures.dll	3.100.620.31714
Microsoft.AspNetCore.Components.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Components.dll	3.100.620.31714
Microsoft.JSInterop.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.JSInterop.dll	3.100.620.31605
Microsoft.AspNetCore.DataProtection.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.DataProtection.dll	3.100.620.31714
Microsoft.AspNetCore.DataProtection.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.DataProtection.Abstractions.dll	3.100.620.31714
Microsoft.AspNetCore.Cryptography.Internal.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Cryptography.Internal.dll	3.100.620.31714
Microsoft.AspNetCore.Antiforgery.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Antiforgery.dll	3.100.620.31714
Microsoft.Extensions.WebEncoders.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.WebEncoders.dll	3.100.620.31605
System.Text.Encodings.Web.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Text.Encodings.Web.dll	4.700.20.31603
Microsoft.AspNetCore.Mvc.Razor.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.Razor.dll	3.100.620.31714
Microsoft.Extensions.Caching.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Caching.Abstractions.dll	3.100.620.31605
Microsoft.Extensions.Caching.Memory.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Caching.Memory.dll	3.100.620.31605
Microsoft.AspNetCore.Mvc.TagHelpers.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.TagHelpers.dll	3.100.620.31714
Microsoft.AspNetCore.Razor.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Razor.dll	3.100.620.31714
Microsoft.AspNetCore.Mvc.RazorPages.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Mvc.RazorPages.dll	3.100.620.31714
Swashbuckle.AspNetCore.Swagger.dll	D:\webapps\ECI_FileMonitor\Swashbuckle.AspNetCore.Swagger.dll	5.5.1.0
Microsoft.OpenApi.dll	D:\webapps\ECI_FileMonitor\Microsoft.OpenApi.dll	1.1.4.0
Serilog.Extensions.Hosting.dll	D:\webapps\ECI_FileMonitor\Serilog.Extensions.Hosting.dll	3.0.0.0
Microsoft.Win32.Registry.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\Microsoft.Win32.Registry.dll	4.700.20.31603
SHCore.dll	C:\Windows\System32\SHCore.dll	6.3.9600.19750
System.Xml.XDocument.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Xml.XDocument.dll	4.700.20.31603
System.Private.Xml.Linq.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Private.Xml.Linq.dll	4.700.20.31603
System.Security.Cryptography.Algorithms.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Security.Cryptography.Algorithms.dll	4.700.20.31603
Swashbuckle.AspNetCore.SwaggerUI.dll	D:\webapps\ECI_FileMonitor\Swashbuckle.AspNetCore.SwaggerUI.dll	5.5.1.0
Microsoft.AspNetCore.Diagnostics.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Diagnostics.dll	3.100.620.31714
Microsoft.Extensions.Localization.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.Localization.Abstractions.dll	3.100.620.31605
Microsoft.Net.Http.Headers.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Net.Http.Headers.dll	3.100.620.31714
Microsoft.AspNetCore.Html.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Html.Abstractions.dll	3.100.620.31714
Microsoft.AspNetCore.Razor.Runtime.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Razor.Runtime.dll	3.100.620.31714
System.ComponentModel.Annotations.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.ComponentModel.Annotations.dll	4.700.20.31603
Microsoft.AspNetCore.Metadata.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Metadata.dll	3.100.620.31714
Microsoft.AspNetCore.StaticFiles.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.StaticFiles.dll	3.100.620.31714
Microsoft.Extensions.FileProviders.Embedded.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.Extensions.FileProviders.Embedded.dll	3.100.620.31605
System.IO.Pipelines.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\System.IO.Pipelines.dll	4.700.20.12001
System.Xml.XPath.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Xml.XPath.dll	4.700.20.31603
Microsoft.AspNetCore.Diagnostics.Abstractions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Diagnostics.Abstractions.dll	3.100.620.31714
Microsoft.AspNetCore.Http.Extensions.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.Http.Extensions.dll	3.100.620.31714
Microsoft.AspNetCore.WebUtilities.dll	C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.6\Microsoft.AspNetCore.WebUtilities.dll	3.100.620.31714
System.Net.WebSockets.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Net.WebSockets.dll	4.700.20.31603
System.Net.Http.Formatting.dll	D:\webapps\ECI_FileMonitor\System.Net.Http.Formatting.dll	5.2.61128.0
System.Runtime.Serialization.Json.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.Serialization.Json.dll	4.700.20.31603
System.Private.DataContractSerialization.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Private.DataContractSerialization.dll	4.700.20.31603
System.Runtime.Serialization.Xml.dll	C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.Serialization.Xml.dll	4.700.20.31603

```

```
ntdll.dll!RtlpExecuteHandlerForException()
ntdll.dll!RtlDispatchException()
ntdll.dll!RtlRaiseException()
[External Code]
[Managed to Native Transition]
System.IO.FileSystem.Watcher.dll!System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(byte[] buffer) Line 283
	at /_/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs(283)
System.IO.FileSystem.Watcher.dll!System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* overlappedPointer) Line 226
	at /_/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs(226)
System.Private.CoreLib.dll!System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped) Line 50
	at /_/src/System.Private.CoreLib/src/System/Threading/ClrThreadPoolBoundHandleOverlapped.cs(50)
System.Private.CoreLib.dll!System.Threading._IOCompletionCallback.IOCompletionCallback_Context(object state) Line 51
	at /_/src/System.Private.CoreLib/src/System/Threading/Overlapped.cs(51)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 172
	at /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs(172)
System.Private.CoreLib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pNativeOverlapped) Line 74
	at /_/src/System.Private.CoreLib/src/System/Threading/Overlapped.cs(74)
[Native to Managed Transition]
[External Code]

```

### PR DESCRIPTION
**Pull request by carlossanlop**
This issue was reported for 3.1 twice:
- https://github.com/dotnet/runtime/issues/40412 - w3wp.exe crash in FileSystemWatcher after 2.2 -> 3.1 migration (c0000005 Access Violation)
- https://github.com/dotnet/runtime/issues/42108 - FileSystemWatcher crash UNALIGNED_STACK_POINTER

When monitoring a network share with `FileSystemWatcher`, if there are network issues that could cause the data to arrive malformed, then after casting the byte array to a `FILE_NOTIFY_INFORMATION`, attempts to access the struct fields can throw an AV.

The issue was also reported internally by one of the customers. Our CSS partner was able to reproduce it locally (I couldn't).

I provided him a private binary of System.IO.FileSystem.Watcher.dll with the changes in this fix, and he confirmed the AV no longer happens.

We need this change to be backported to 5.0 and 3.1.

Here is a small repro code, which was executed along with [clumsy](https://github.com/jagt/clumsy), which can alter the network quality.

<details>
  <summary>Code</summary>

  ```cs
using System;
using System.IO;

namespace FileWatcherConsole
{
    class Program
    {
        static void Main()
        {
            try
            {
                var w = new Watcher();
                w.InitializeFilewatcher();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
        }
    }

    class Watcher
    {
        const string WatchPath = @"\\remote\location\goes\here";
        FileSystemWatcher _watcher = new FileSystemWatcher();

        public void InitializeFilewatcher()
        {
            _watcher = new FileSystemWatcher(WatchPath);
            _watcher.InternalBufferSize = 65536;
            _watcher.NotifyFilter = NotifyFilters.LastWrite | NotifyFilters.FileName;
            _watcher.Changed += new FileSystemEventHandler(FileChanged);
            _watcher.Created += new FileSystemEventHandler(FileCreated);
            _watcher.Renamed += new RenamedEventHandler(FileRenamed);
            _watcher.Deleted += new FileSystemEventHandler(FileDeleted);
            _watcher.Error += Watcher_Error;
            _watcher.EnableRaisingEvents = true;
        }

        private void FileRenamed(object sender, RenamedEventArgs e) => Console.WriteLine($"Renamed: {e.OldName} -> {e.Name}");

        private void FileCreated(object sender, FileSystemEventArgs e) => Console.WriteLine($"Created: {e.Name} - {e.FullPath}");

        private void FileChanged(object sender, FileSystemEventArgs e) => Console.WriteLine($"Changed: {e.Name} - {e.FullPath}");

        private void FileDeleted(object sender, FileSystemEventArgs e) => Console.WriteLine($"Deleted: {e.Name} - {e.FullPath}");

        private void Watcher_Error(object sender, ErrorEventArgs e)
        {
            Exception ex = e.GetException();
            Console.WriteLine(ex.Message);
            Console.WriteLine(ex.StackTrace);
        }
    }
}
  ```
</details>

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadDirectoryChangesW.cs [hunk 1]
```diff
@@ -28,8 +28,8 @@ internal struct FILE_NOTIFY_INFORMATION
             internal FileAction Action;
 
             // Note that the file name is not null terminated
-            private uint FileNameLength;
-            private char _FileName;
+            internal uint FileNameLength;
+            internal char _FileName;
```
Comment (danmosemsft) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadDirectoryChangesW.cs:32]: If you're making this internal you may want a better name than the leading underscore one. Maybe `FileNamePtr` and it's a `char*`  ? Also should these fields be `readonly` ?

However, as written, it would be easy for someone to write code that uses this struct and either forget to validate bounds, or forget to do so before reading `FileName`, as that will AV when it constructs the span, presumably. Would it help if the struct was simply
```c#
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        internal struct FILE_NOTIFY_INFORMATION
        {
            internal readonly uint NextEntryOffset;
            internal readonly FileAction Action;

            // Note that the file name is not null terminated
            internal readonly uint FileNameLength;
            internal readonly byte* _FileName;
        }
```

By getting rid of the attractive looking getter that returns a string (but can AV) it's more clear that the caller needs to do validation.

This code below is the only place where FILE_NOTIFY_INFORMATION is used. The `new ReadOnlySpan` stuff would move there.

Comment (ericstj) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadDirectoryChangesW.cs:32]: Could you avoid this change by just using span length?

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs [hunk 2]
```diff
@@ -245,20 +245,39 @@ private void ReadDirectoryChangesCallback(uint errorCode, uint numBytes, AsyncRe
...
+
                 Interop.Kernel32.FILE_NOTIFY_INFORMATION* info = (Interop.Kernel32.FILE_NOTIFY_INFORMATION*)b;
 
                 ReadOnlySpan<char> oldName = ReadOnlySpan<char>.Empty;
 
                 // Parse each event from the buffer and notify appropriate delegates
                 do
                 {
+                    // Validate the data we received in case it's corrupted. This can happen
+                    // if we are watching files over the network with a poor connection.
```
Comment (ericstj) [inline src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:266]: That shouldn’t be the case.  Windows needs to maintain the contract of ReadDirectoryChanges.  We shouldn’t have to do this but are doing so defensively.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs [hunk 3]
```diff
@@ -245,20 +245,39 @@ private void ReadDirectoryChangesCallback(uint errorCode, uint numBytes, AsyncRe
             }
         }
 
-        private unsafe void ParseEventBufferAndNotifyForEach(byte[] buffer)
+        private unsafe void ParseEventBufferAndNotifyForEach(byte[] buffer, uint numBytes)
         {
             Debug.Assert(buffer != null);
             Debug.Assert(buffer.Length > 0);
+            Debug.Assert(numBytes <= buffer.Length);
```
Comment (ericstj) [inline src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:252]: This should be stronger than an Assert. Since we're guarding against Windows giving us garbage we should guard against this being invalid as well. We should take min of numBytes and buffer.Length below.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs [hunk 4]
```diff
@@ -245,20 +245,39 @@ private void ReadDirectoryChangesCallback(uint errorCode, uint numBytes, AsyncRe
...
 
             fixed (byte* b = buffer)
             {
+                byte* pBufferLimit = b + numBytes;
+
                 Interop.Kernel32.FILE_NOTIFY_INFORMATION* info = (Interop.Kernel32.FILE_NOTIFY_INFORMATION*)b;
```
Comment (jkotas) [inline src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:258]: It is better to do the cast to `NOTIFY_INFORMATION*` only after you have validated the size. (Defensive coding.)

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadDirectoryChangesW.cs (hunk 1 above)
Comment (jkotas) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadDirectoryChangesW.cs:32]: >            // Note that the file name is not null terminated
>            internal readonly uint FileNameLength;
>            internal readonly byte* FileNamePtr;

This would not be correct. 

It should be either this:
```
            // Note that the file name is not null terminated
            internal readonly uint FileNameLength;
            internal readonly char FileName;
```
or this: 
```
            // Note that the file name is not null terminated
            internal readonly uint FileNameLength;
            internal fixed char FileName[1];
```

Comment (jkotas) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadDirectoryChangesW.cs:32]: > Could you avoid this change by just using span length?

It is best to convert buffer to Span only after the buffer bounds have been validated. Having API that returns Span that points to potentially invalid memory is not a good pattern.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 4 above)
Comment (carlossanlop) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:258]: I prefer to keep it as it is right now. The size validation depends on the casted object. Also, the next offset needs to cast.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 2 above)
Comment (carlossanlop) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:266]: I'll contact Windows to continue the conversation with them about this issue.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 3 above)
Comment (carlossanlop) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:252]: Fixed by getting the min.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadDirectoryChangesW.cs (hunk 1 above)
Comment (carlossanlop) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ReadDirectoryChangesW.cs:32]: I will be using this:
`internal readonly char FileName;`
Because the unit tests passed with it.

I tested this suggestion, but it caused test failures:
`internal fixed char FileName[1];`

<details>
  <summary>Failures</summary>

  ```
  Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. System.ArgumentException: Illegal characters in path. (Parameter 'path')
     at System.IO.Path.GetFullPath(String path) in D:\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Path.Windows.cs:line 52
     at System.IO.Tests.FileSystemWatcherTest.<>c__DisplayClass11_0.<WatchRenamed>b__0(Object o, RenamedEventArgs e) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\tests\Utility\FileSystemWatcherTest.cs:line 146
     at System.IO.FileSystemWatcher.NotifyRenameEventArgs(WatcherChangeTypes action, ReadOnlySpan`1 name, ReadOnlySpan`1 oldName) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs:line 425
     at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 317
     at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 238
     at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__84_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 63
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\ClrThreadPoolBoundHandleOverlapped.cs:line 48
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\Overlapped.cs:line 62
  System.ArgumentException: Illegal characters in path. (Parameter 'path')
     at System.IO.Path.GetFullPath(String path) in D:\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Path.Windows.cs:line 52
     at System.IO.Tests.FileSystemWatcherTest.<>c__DisplayClass10_0.<WatchDeleted>b__0(Object o, FileSystemEventArgs e) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\tests\Utility\FileSystemWatcherTest.cs:line 111
     at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs:line 454
     at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 337
     at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 238
     at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__84_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 63
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\ClrThreadPoolBoundHandleOverlapped.cs:line 48
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\Overlapped.cs:line 62
  System.ArgumentException: Illegal characters in path. (Parameter 'path')
     at System.IO.Path.GetFullPath(String path) in D:\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Path.Windows.cs:line 52
     at System.IO.Tests.FileSystemWatcherTest.<>c__DisplayClass10_0.<WatchDeleted>b__0(Object o, FileSystemEventArgs e) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\tests\Utility\FileSystemWatcherTest.cs:line 111
     at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs:line 454
     at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 337
     at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 238
     at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__84_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 63
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\ClrThreadPoolBoundHandleOverlapped.cs:line 48
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\Overlapped.cs:line 62
  System.ArgumentException: Illegal characters in path. (Parameter 'path')
     at System.IO.Path.GetFullPath(String path) in D:\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Path.Windows.cs:line 52
     at System.IO.Tests.FileSystemWatcherTest.<>c__DisplayClass9_0.<WatchCreated>b__0(Object o, FileSystemEventArgs e) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\tests\Utility\FileSystemWatcherTest.cs:line 76
     at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs:line 454
     at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 334
     at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 238
     at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__84_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 63
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\ClrThreadPoolBoundHandleOverlapped.cs:line 48
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\Overlapped.cs:line 62
  System.ArgumentException: Illegal characters in path. (Parameter 'path')
     at System.IO.Path.GetFullPath(String path) in D:\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Path.Windows.cs:line 52
     at System.IO.Tests.FileSystemWatcherTest.<>c__DisplayClass11_0.<WatchRenamed>b__0(Object o, RenamedEventArgs e) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\tests\Utility\FileSystemWatcherTest.cs:line 146
     at System.IO.FileSystemWatcher.NotifyRenameEventArgs(WatcherChangeTypes action, ReadOnlySpan`1 name, ReadOnlySpan`1 oldName) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs:line 425
     at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 317
     at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 238
     at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__84_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer) in D:\runtime\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs:line 63
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\ClrThreadPoolBoundHandleOverlapped.cs:line 48
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in D:\runtime\src\coreclr\src\System.Private.CoreLib\src\System\Threading\Overlapped.cs:line 62
  ```
</details>

**Review by carlossanlop — COMMENTED** [review]
@jkotas @ericstj @danmosemsft I would like to point out that we sent a private DLL to the customer with the changes up to this point, and they got back to us last night confirming that the issue is gone with the fix.

I address almost all feedback I got, but I would like to emphasize that we are actively trying to backport this change to 5.0 and 3.1, so I would like to minimize the number of changes as much as we can.

The FileSystemWatcher unit tests passed locally.

I'm working on getting these suggestions addressed in the 5.0 and 3.1 backports as well.

cc @jeffhandley @tarekgh

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 2 above)
Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:267]: > We shouldn’t have to do this but are doing so defensively.

The comment should capture this information.

Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:267]: Also, it would be nice to add `Debug.Assert` for this to validate the this is not happening in the tests.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs [hunk 5]
```diff
@@ -245,20 +245,40 @@ private void ReadDirectoryChangesCallback(uint errorCode, uint numBytes, AsyncRe
             }
         }
 
-        private unsafe void ParseEventBufferAndNotifyForEach(byte[] buffer)
+        private unsafe void ParseEventBufferAndNotifyForEach(byte[] buffer, uint numBytes)
         {
             Debug.Assert(buffer != null);
             Debug.Assert(buffer.Length > 0);
 
+            numBytes = Math.Min(numBytes, (uint)buffer.Length);
```
Comment (jkotas) [inline src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:253]: Do we expect wrong `numBytes` to be actually passed in, or are we just doing this defensively?

Comment (tarekgh) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:253]: It is done defensively. it was suggested by @ericstj

**Comment by jkotas** [comment]
>  we are actively trying to backport this change to 5.0 and 3.1, so I would like to minimize the number of changes as much as we can.

It is not unusual to do a servicing change that has minimal changes and that is coded in less than ideal way; and do a different cleaner change for the tip.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 5 above)
Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:253]: We should add assert and comment to make it clear.

Comment (carlossanlop) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:253]: Defensively in case the number of bytes provided by Windows does not match the length in the buffer.

Comment (tarekgh) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:253]: We had the assert and removed it to add the check :-) I think it is fine to return back the assert.

**Comment by carlossanlop** [comment]
> It is not unusual to do a servicing change that has minimal changes and that is coded in less than ideal way; and do a different cleaner change for the tip.

I'd be happy to update the backport PRs with the suggestions provided here, if there's enough time after merging this change.

**Comment by tarekgh** [comment]
> I'd be happy to update the backport PRs with the suggestions provided here, if there's enough time after merging this change.

I think the changes here is reasonable for the service release too. I am not seeing high risk with it. I am not sure if there is any more strong feedback need to be addressed here.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs [hunk 6]
```diff
@@ -245,20 +245,40 @@ private void ReadDirectoryChangesCallback(uint errorCode, uint numBytes, AsyncRe
...
                 ReadOnlySpan<char> oldName = ReadOnlySpan<char>.Empty;
 
                 // Parse each event from the buffer and notify appropriate delegates
                 do
                 {
+                    // Validate the data we received in case it's corrupted. This can happen
+                    // if we are watching files over the network with a poor connection.
+
+                    // Verify the info object is within the expected bounds
+                    if (info < b || (((byte*)info) + sizeof(Interop.Kernel32.FILE_NOTIFY_INFORMATION)) > pBufferLimit)
```
Comment (Jozkee) [inline src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:271]:
```suggestion
                    if (info < b || ((byte*)info) + sizeof(Interop.Kernel32.FILE_NOTIFY_INFORMATION) > pBufferLimit)
```

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs [hunk 7]
```diff
@@ -245,20 +245,40 @@ private void ReadDirectoryChangesCallback(uint errorCode, uint numBytes, AsyncRe
...
+                    {
+                        break;
+                    }
+
+                    // Verify the file path is within the bounds
+                    byte* pFileEnd = ((byte*)&(info->FileName)) + info->FileNameLength;
```
Comment (Jozkee) [inline src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:277]: create a local for `info->FileName` and `info->FileNameLength` since they are also referenced below.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 6 above)
Comment (Jozkee) [inline src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:271]: I wonder if its worth moving `sizeof(Interop.Kernel32.FILE_NOTIFY_INFORMATION)` outside of the loop.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 5 above)
Comment (carlossanlop) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:254]: I brought back the assert and I updated the backport PRs to ensure the CI finishes on time before 4pm.

**Review by jozkee — COMMENTED** [review]
Just nits, hold-off addressing my comments to avoid restarting CI.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 6 above)
Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:271]: `sizeof(Interop.Kernel32.FILE_NOTIFY_INFORMATION)` will JIT into a constant. You won't gain anything by manually hoisting it out.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 5 above)
Comment (carlossanlop) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:254]: >we could be asserting in the break statements added below

The suggestion makes sense to me. Can I add it those asserts in a separate PR?

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 7 above)
Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:277]: To improve readability or to improve performance? It won't help to improve performance.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 6 above)
Comment (Jozkee) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:271]: What's the reason that the compiler does not allow me to do this?
```
struct MyStruct { }

private unsafe void M()
{
    const int sizeOfMyStruct = sizeof(MyStruct);
    /// Do Something...
}
```

It gives me the following error:
> CS0133: The expression being assigned to 'sizeOfMyStruct' must be constant

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 5 above)
Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:254]: Fine with me. Also, please add comments like: "This is defensive check in case the number of bytes provided by Windows is wrong. We have not seen this situation in practice.".

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 6 above)
Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:271]: It is not C# constant, but it is a JIT-time constant.

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 7 above)
Comment (Jozkee) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:277]: To improve readability.

Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:277]: I have submitted https://github.com/dotnet/runtime/pull/42474 that shows how this can be rewritten using Span<T> - to both improve reliability and improve security.

**Comment by carlossanlop** [comment]
CI failures:
- OSX x64 release and Browser wasm Release - Unrelated to this change. Timeouts while attempting to build.
  ```
  ##[error]The job running on agent Azure Pipelines 52 ran longer than the maximum time of 120 minutes.
  ```

File: src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs (hunk 7 above)
Comment (carlossanlop) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:277]: @jkotas is the intention of that fix to be the backport for 3.1 and 5.0? In that case, I can close my 3 PRs and I can let you submit the backports as well.

Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:277]: I think it is fine to use your original fix for servicing. It is less a bit less invasive.

Comment (carlossanlop) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:277]: Okay great. So the only one I'll close is the one for master.

Comment (carlossanlop) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:277]: On a second thought, if we want to preserve consistency, I should also merge the master change and your PR can go on top of that.

Comment (jkotas) [reply src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:277]: Merging your PR to master sounds good to me.
