### PR TITLE
Return singleton enumerators from IEnumerable.GetEnumerator for empty collections

### LINKED ISSUE #59596: Eliminate allocations when enumerating empty collections
Turns out the world is full of empty collections. Empty lists, empty dictionaries, empty sets. The world is also full of code that ends up enumerating these empty collections. And if this code happens to hold an interface type such as IList&lt;T> or IReadOnlyList&lt;T>, then enumerating these empty collections causes a heap allocation:

```csharp
IReadOnlyList<int> l = new List<int>();
foreach (var foo in l)   // <-- allocates an enumerator, *sigh*
{
}
```

It should be possible to eliminate these allocations by adding a teeny bit of logic to the collection types. For example, consider List&lt;T>:

```csharp
public class List<T>
{
    IEnumerator<T> IEnumerable<T>.GetEnumerator()
        => (_size == 0) ? _staticEmptyEnumerator : new Enumerator(this);

    private static readonly EmptyEnumerator _staticEmptyEnumerator = new ();

    private sealed class EmptyEnumerator : IEnumerator<T>
    {
        public void Dispose() {}
        public bool MoveNext() => false;
        public void Reset() {}
        public T Current => throw new NotSupportedException();
        object IEnumerator.Current => throw new NotSupportedException();
    }
}
```

The above code detects if the collection is empty and then returns a static enumerator instance to the caller. No allocation occurs, the world is a slightly better place as a result.

### PR DESCRIPTION
**Pull request by stephentoub**
Change the `IEnumerable<T>.GetEnumerator()` implementations on our core collection types to special-case Count==0 in order to return a single enumerator instead of allocating one a new each time.  This saves an allocation when enumerating these collections via the interface in exchange for an extra length check as part of GetEnumerator.

This changes `List<>`, `Queue<>`, `Stack<>`, `LinkedList<>`, `PriorityQueue<,>`, `SortedDictionary<,>`, `SortedList<,>`, `SortedSet<>`, `HashSet<>`, `Dictionary<,>`, and `ArraySegment<>`.

Fixes https://github.com/dotnet/runtime/issues/59596

Relates to https://github.com/dotnet/runtime/issues/81523, as this means that code like:
```C#
var list = new List<int>();
IEnumerator<int> e = list.GetEnumerator();
list.Add(42);
e.MoveNext();
```
which would previously have thrown an exception on the `MoveNext` call will no longer throw an exception.

|   Method |         Toolchain |      Mean |     Error |    StdDev |    Median | Ratio | Allocated | Alloc Ratio |
|--------- |------------------ |----------:|----------:|----------:|----------:|------:|----------:|------------:|
| SumEmpty | \main\corerun.exe | 14.920 ns | 0.3240 ns | 0.6396 ns | 14.642 ns |  1.00 |      40 B |        1.00 |
| SumEmpty |   \pr\corerun.exe |  5.496 ns | 0.0202 ns | 0.0157 ns |  5.491 ns |  0.36 |         - |        0.00 |
|          |                   |           |           |           |           |       |           |             |
|   SumOne | \main\corerun.exe | 20.182 ns | 0.1604 ns | 0.1500 ns | 20.160 ns |  1.00 |      40 B |        1.00 |
|   SumOne |   \pr\corerun.exe | 20.068 ns | 0.0642 ns | 0.0501 ns | 20.066 ns |  0.99 |      40 B |        1.00 |

```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Collections.Generic;

[MemoryDiagnoser(false)]
public partial class Program
{
    static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);

    private IEnumerable<int> _empty = new List<int>();
    private IEnumerable<int> _one = new List<int>() { 42 };

    [Benchmark]
    public int SumEmpty()
    {
        int sum = 0;
        foreach (int i in _empty) sum += i;
        return sum;
    }

    [Benchmark]
    public int SumOne()
    {
        int sum = 0;
        foreach (int i in _one) sum += i;
        return sum;
    }
}
```

### CODE REVIEW

File: src/libraries/System.Collections/src/System/Collections/Generic/PriorityQueue.cs [hunk 1]
```diff
@@ -961,9 +961,11 @@ void IEnumerator.Reset()
             /// <returns>An <see cref="Enumerator"/> for the <see cref="UnorderedItems"/>.</returns>
             public Enumerator GetEnumerator() => new Enumerator(_queue);
 
-            IEnumerator<(TElement Element, TPriority Priority)> IEnumerable<(TElement Element, TPriority Priority)>.GetEnumerator() => GetEnumerator();
+            IEnumerator<(TElement Element, TPriority Priority)> IEnumerable<(TElement Element, TPriority Priority)>.GetEnumerator() =>
+                _queue.Count == 0 ? ((IEnumerable<(TElement Element, TPriority Priority)>)Array.Empty<(TElement Element, TPriority Priority)>()).GetEnumerator() :
```
Comment (eiriktsarpalis) [inline src/libraries/System.Collections/src/System/Collections/Generic/PriorityQueue.cs:965]: Nit: it might not be immediately evident to the reader without context that this expression is intended to return a singleton enumerator. Perhaps extract to a shared helper method named appropriately?
```suggestion
                _queue.Count == 0 ? GetEmptyEnumeratorSingleton<(TElement Element, TPriority Priority)>() :
```

File: src/libraries/Common/tests/System/Collections/IList.Generic.Tests.cs [hunk 2]
```diff
@@ -630,7 +630,7 @@ public void IList_Generic_CurrentAtEnd_AfterAdd(int count)
                     {
                         collection.Add(CreateT(seed++));
 
-                        if (Enumerator_Current_UndefinedOperation_Throws)
+                        if (count == 0 ? Enumerator_Empty_Current_UndefinedOperation_Throws : Enumerator_Current_UndefinedOperation_Throws)
```
Comment (eiriktsarpalis) [inline src/libraries/Common/tests/System/Collections/IList.Generic.Tests.cs:633]: Do we need tests validating that empty collections return the same instance on `GetEnumerator()` calls?

**Review by eiriktsarpalis — APPROVED** [review]
Thanks

File: src/libraries/Common/tests/System/Collections/IList.Generic.Tests.cs (hunk 2 above)
Comment (stephentoub) [reply src/libraries/Common/tests/System/Collections/IList.Generic.Tests.cs:633]: Added

File: src/libraries/System.Collections/src/System/Collections/Generic/PriorityQueue.cs (hunk 1 above)
Comment (stephentoub) [reply src/libraries/System.Collections/src/System/Collections/Generic/PriorityQueue.cs]: Added
