### PR TITLE
Fix Unnecessary sign-extension for `(nuint)span.Length`

### LINKED ISSUE #84564: Unnecessary sign-extension for `(nuint)span.Length`
> @EgorBo In theory, the length in `(nuint)span.Length` should be recognized as never negative, and the sign-extension elided, but doesn't appear to be the case (at least in R2R), see https://csharp.godbolt.org/z/14oW68fqz.

_Originally posted by @xtqqczze in https://github.com/dotnet/runtime/issues/84524#issuecomment-1500999983_

```csharp
static nuint Span0(ReadOnlySpan<byte> span) => (nuint)span.Length;
static nuint Span1(ReadOnlySpan<byte> span) => (uint)span.Length;
```

```asm
// crossgen2 8.0.0-preview.4.23208.99+07f00dc2f624946c54dbf85fea79c600a690f634

C:Span0(System.ReadOnlySpan`1[ubyte]):ulong:
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
						;; size=0 bbWeight=1 PerfScore 0.00
       movsxd   rax, dword ptr [rcx+08H]
						;; size=4 bbWeight=1 PerfScore 4.00
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00

C:Span1(System.ReadOnlySpan`1[ubyte]):ulong:
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
						;; size=0 bbWeight=1 PerfScore 0.00
       mov      eax, dword ptr [rcx+08H]
						;; size=3 bbWeight=1 PerfScore 2.00
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00
```

### PR DESCRIPTION
**Pull request by En3Tho**
Fixes #84564

After review upd:
This adds a new CORINFO_FLG_SPAN flag and a IsSpan property to simplify handling of unpromoted span.Length loads and possibly other optimizations of Spans

### CODE REVIEW

**Comment by En3Tho** [comment]
Thank you! If adding ```CORINFO_FLG_SPAN``` is preferred then I can look into that instead. I've decided to allocate more time to architectures/compilers so RyuJit is kinda obvious option for me. This issue looked "easy" but w.o context it's obviously hard to know where things are going and what change is actually worthy and what is just useless/harmful.

Otherwise should I set ```lvIsSpan``` for both ```varDsc``` and ```fieldVarDsc```?

**Comment by jakobbotsch** [comment]
> If adding CORINFO_FLG_SPAN is preferred then I can look into that instead. I've decided to allocate more time to architectures/compilers so RyuJit is kinda obvious option for me. This issue looked "easy" but w.o context it's obviously hard to know where things are going and what change is actually worthy and what is just useless/harmful.

Awesome! Looking forward to more PRs!

> Otherwise should I set `lvIsSpan` for both `varDsc` and `fieldVarDsc` like I do with `lvIsNeverNegative` now?

`varDsc` should be set as `lvIsSpan` and `fieldVarDsc` should be set as `lvIsNeverNegative` (when `isSpanLength`) is true.

File: src/coreclr/jit/assertionprop.cpp [hunk 1]
```diff
@@ -168,6 +168,17 @@ bool IntegralRange::Contains(int64_t value) const
             }
             break;
 
+        case GT_IND:
+        {
+            if (node->gtGetOp1()->OperGet() == GT_ADD
+                && node->gtGetOp1()->gtGetOp1()->OperGet() == GT_LCL_VAR
+                && node->gtGetOp1()->gtGetOp1()->AsLclVar()->IsNeverNegative(compiler))
```
Comment (AndyAyersMS) [inline src/coreclr/jit/assertionprop.cpp:175]: Don't we also need to check that `op2` is also never negative? 

Or, if it can be negative, that it's most negative possible value won't make the sum negative?

Comment (En3Tho) [reply src/coreclr/jit/assertionprop.cpp:175]: Yes, you're right and this is fragile and most likely won't work. I will redo this. Op2 should contain exactly the const offset of span.Length but adding another check might be too costly to cover the gains?

Is there a faster way to check if "this tree is Span.Length"? We have this information on gtFieldAddr but then it gets transformed to indir -> add (span, offset) and so information is lost. I may be wrong here, I will look more.

I looked at spmi diffs and they aren't huge. Around 700+800 bytes combined. FullOpt is around 450 bytes.

Not sure if some of those are actually bugs.

**Comment by En3Tho** [comment]
Adding GT_LCL_FLD did not affect arm. On linux x64 the field is already promoted it seems. So for now keep this strictly for win x64. I will look more closely at arm.

**Comment by jakobbotsch** [comment]
> Adding GT_LCL_FLD did not affect arm. On linux x64 the field is already promoted it seems. So for now keep this strictly for win x64. I will look more closely at arm.

I'd add the `GT_LCL_FLD` handling, if only for consistency. It should be a quite simple check to add.

File: src/coreclr/jit/assertionprop.cpp [hunk 2]
```diff
@@ -168,6 +168,25 @@ bool IntegralRange::Contains(int64_t value) const
             }
             break;
 
+        case GT_IND:
+        {
+#if defined(_WIN64)
```
Comment (jakobbotsch) [inline src/coreclr/jit/assertionprop.cpp:173]: The right check would be `#ifdef WINDOWS_AMD64_ABI`, but I would honestly just leave it out, looks like this doesn't have measurable impact on throughput from SPMI.

File: src/coreclr/jit/assertionprop.cpp [hunk 3]
```diff
@@ -168,6 +168,25 @@ bool IntegralRange::Contains(int64_t value) const
...
+            if (node->gtGetOp1()->OperGet() == GT_ADD
+                && node->gtGetOp1()->gtGetOp1()->OperGet() == GT_LCL_VAR
+                && node->gtGetOp1()->gtGetOp2()->IsIntegralConst(OFFSETOF__CORINFO_Span__length))
+            {
+                GenTreeLclVar* const lclVar = node->gtGetOp1()->gtGetOp1()->AsLclVar();
```
Comment (jakobbotsch) [inline src/coreclr/jit/assertionprop.cpp:178]:
```suggestion
            GenTree* addr = node->AsIndir()->Addr();
            if (node->TypeIs(TYP_INT) && addr->OperIs(GT_ADD)
                && addr->gtGetOp1()->OperIs(GT_LCL_VAR)
                && addr->gtGetOp2()->IsIntegralConst(OFFSETOF__CORINFO_Span__length))
            {
                GenTreeLclVar* const lclVar = addr->gtGetOp1()->AsLclVar();
```

File: src/coreclr/jit/assertionprop.cpp [hunk 4]
```diff
@@ -168,6 +168,25 @@ bool IntegralRange::Contains(int64_t value) const
...
+                if (lclVar->IsSpan(compiler))
+                {
+                    // TODO: this check can be moved inside isSpan?
```
Comment (jakobbotsch) [inline src/coreclr/jit/assertionprop.cpp:181]: No, normal locals can be spans too, not just implicit byref params.

Comment (En3Tho) [reply src/coreclr/jit/assertionprop.cpp:181]: Thanks

**Comment by En3Tho** [comment]
I've applied you suggestion and ran jit-format on it too.
Also, I've added GT_LCL_FLD check too which only includes IsNeverNegative. From what I've understood lvNormalizeOnStore applies only to GT_LCL_VAR?

File: src/coreclr/jit/assertionprop.cpp [hunk 5]
```diff
@@ -168,6 +168,35 @@ bool IntegralRange::Contains(int64_t value) const
...
+        {
+            LclVarDsc* const varDsc = compiler->lvaGetDesc(node->AsLclFld());
+
+            if (varDsc->IsNeverNegative())
+            {
+                return {SymbolicIntegerValue::Zero, UpperBoundForType(rangeType)};
+            }
+
+            break;
+        }
```
[the remark this answers is not in the document]
Comment (En3Tho) [reply src/coreclr/jit/assertionprop.cpp:198]: I will check this. Thank you.

File: src/coreclr/vm/jitinterface.cpp [hunk 6]
```diff
@@ -3767,8 +3767,15 @@ uint32_t CEEInfo::getClassAttribsInternal (CORINFO_CLASS_HANDLE clsHnd)
             ret |= CORINFO_FLG_VALUECLASS;
 
             if (pMT->IsByRefLike())
+            {
                 ret |= CORINFO_FLG_BYREF_LIKE;
 
+                if (pMT == CoreLibBinder::GetClass(CLASS__SPAN) || pMT == CoreLibBinder::GetClass(CLASS__READONLY_SPAN))
```
Comment (jakobbotsch) [inline src/coreclr/vm/jitinterface.cpp:3773]: I think this needs to use `pMT->HasSameTypeDefAs`.

File: src/coreclr/jit/lclvars.cpp [hunk 7]
```diff
@@ -2914,15 +2914,17 @@ void Compiler::lvaSetStruct(unsigned varNum, ClassLayout* layout, bool unsafeVal
 
         if (layout->IsValueClass())
         {
-            varDsc->lvType = layout->GetType();
+            varDsc->lvType                          = layout->GetType();
+            CORINFO_CLASS_HANDLE const classHandle  = layout->GetClassHandle();
+            unsigned const             corinfoFlags = this->info.compCompHnd->getClassAttribs(classHandle);
+            varDsc->SetIsSpan(corinfoFlags & CORINFO_FLG_SPAN);
```
Comment (jakobbotsch) [inline src/coreclr/jit/lclvars.cpp:2920]: This should be unified with the code below that calls `getClassAttribs`.

Note that the code below was refactored a bit to only call `getClassAttribs` when `unsafeValueClsCheck` is true; it's fine to turn it back to look more like what it was before.

Comment (En3Tho) [reply src/coreclr/jit/lclvars.cpp]: Missed the fact the same call was made below. Sorry.

File: src/coreclr/jit/lclvars.cpp [hunk 8]
```diff
@@ -2959,6 +2959,9 @@ void Compiler::lvaSetStruct(unsigned varNum, ClassLayout* layout, bool unsafeVal
         assert(layout->IsBlockLayout() || (layout->GetSize() != 0));
     }
 
+    unsigned classAttribs = info.compCompHnd->getClassAttribs(layout->GetClassHandle());
+    varDsc->SetIsSpan(classAttribs & CORINFO_FLG_SPAN);
```
Comment (jakobbotsch) [inline src/coreclr/jit/lclvars.cpp:2912]: This should be inside the `!layout->IsBlockLayout()` check (block layouts do not have class handles)

Comment (En3Tho) [reply src/coreclr/jit/lclvars.cpp:2912]: I should write this all down somewhere. Thank you.

Comment (En3Tho) [reply src/coreclr/jit/lclvars.cpp:2912]: My main was old and I didn't see the call was under a condition like you've said. :(

**Comment by EgorBo** [comment]
@MihuBot

File: src/coreclr/jit/compiler.h [hunk 9]
```diff
@@ -658,6 +658,8 @@ class LclVarDsc
 private:
     unsigned char lvIsNeverNegative : 1; // The local is known to be never negative
 
+    unsigned char lvIsSpan : 1; // The local is a Span<T>
```
Comment (EgorBo) [inline src/coreclr/jit/compiler.h:661]: would be nice to check that a new bit field doesn't mess the overall type layout?

Comment (En3Tho) [reply src/coreclr/jit/compiler.h:661]: The plan is to remove lvIsNeverNegative (maybe in this PR too) so it shouldn't affect the layout.

Comment (EgorBo) [reply src/coreclr/jit/compiler.h:661]: ah, makes sense then

File: src/coreclr/inc/corinfo.h [hunk 10]
```diff
@@ -850,6 +850,7 @@ enum CorInfoFlag
 //  CORINFO_FLG_UNUSED                = 0x40000000,
 
     // These are internal flags that can only be on Classes
+    CORINFO_FLG_SPAN                  = 0x00008000, // is the class a Span<T>/ReadOnlySpan<T>
```
Comment (jkotas) [inline src/coreclr/inc/corinfo.h:853]: The default pattern for special casing types in the JIT is to mark the type with `[Intrinsic]`, call `isIntrinsicType` on the class handle, and check the name if `isIntrinsicType` returns true. It is how we are special casing the SIMD Vector types. My guess that the default pattern would cheaper overall than computing all type flags just to figure out whether the type is a Span or ReadOnlySpan.

If this check is very hot and we cannot afford to use the default pattern for it, it should be a dedicated `isSpanOrReadOnlySpanType` method on JIT/EE interface so that we do not pay the full cost of getting all flags that `getClassAttributes` returns.

Comment (jakobbotsch) [reply src/coreclr/inc/corinfo.h:853]: I suggested to @En3Tho to add `CORINFO_FLG_SPAN` mainly based on the fact that it is on the same level of information as `CORINFO_FLG_ARRAY` and `CORINFO_FLG_DELEGATE`,  but it is reasonable to me to switch this to `isSpanOrReadOnlySpanType`. I am not so sure that we want to switch `lvaSetStruct` to be doing the same style of recognition as the SIMD recognition we do today.

> > My guess that the default pattern would cheaper overall than computing all type flags just to figure out whether the type is a Span or ReadOnlySpan.

Note that we have been calling `getClassStribs` from `lvaSetStruct` since forever. It was only recently removed in #87967.

Comment (jkotas) [reply src/coreclr/inc/corinfo.h:853]: > CORINFO_FLG_SPAN mainly based on the fact that it is on the same level of information as CORINFO_FLG_ARRAY and CORINFO_FLG_DELEGATE

Nit: Arrays or Delegates are core type system entities that one cannot identify via a simple name check. Span/ReadOnlySpan is just an ordinary type that the JIT is recognizing as intrinsic. 

> I am not so sure that we want to switch lvaSetStruct to be doing the same style of recognition as the SIMD recognition we do today.

Are you worried about throughput? The name check behind the `isIntrinsicType` early out is fairly cheap overall. We have intentionally switched to allow JIT to identify intrinsics by name, so that the JIT/EE interface does not need to know about all ordinary types and methods that the JIT wants to special case as an intrinsic.

If we are worried about throughout, a dedicated `isSpanOrReadOnlySpanType` method would be the way to go.

Comment (jakobbotsch) [reply src/coreclr/inc/corinfo.h:853]: > Nit: Arrays or Delegates are core type system entities that one cannot identify via a simple name check. Span/ReadOnlySpan is just an ordinary type that the JIT is recognizing as intrinsic.

Fair point.

> Are you worried about throughput? The name check behind the isIntrinsicType early out is fairly cheap overall. We have intentionally switched to allow JIT to identify intrinsics by name, so that the JIT/EE interface does not need to know about all ordinary types and methods that the JIT wants to special case as an intrinsic.

Yes, I was mainly worried about throughput -- we have been quite careful in the JIT to only do SIMD recognition from the paths where we know it is relevant, instead of, say, a general function like `lvaSetStruct`. But SIMD recognition also has much more to recognize, so if you say that the `isIntrinsic` + metadata lookup is cheap, then I think we should just do it this way and avoid the JIT-EE change.

Comment (jkotas) [reply src/coreclr/inc/corinfo.h:853]: We can keep track of it only when optimizing.

**Comment by JulieLeeMSFT** [comment]
@En3Tho, please address feedback from JanK like introducing isSpanOrReadOnlySpanType API.

**Comment by En3Tho** [comment]
@JulieLeeMSFT Sure! I will try to find time this week

**Comment by JulieLeeMSFT** [comment]
Hi @En3Tho, this is a kindly reminder.

**Comment by En3Tho** [comment]
Went with Jan's suggestions of using IsIntrinsic check. I guess generally it should be quite fast but if it isn't then something like static table can be introduced like simd one or simd one turned into a bigger general intrinsic table.

Let's see what spmi will show.

**Comment by MichalPetryka** [comment]
@MihuBot

**Comment by En3Tho** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=373037&view=ms.vss-build-web.run-extensions-tab

Diffs are mostly like these:
`
-       movsxd   rdx, dword ptr [rcx+0x08]
+       mov      edx, dword ptr [rcx+0x08]
`

Some of them are more interesting but rare:
`
-       mov      eax, ecx
-       mov      edx, dword ptr [rbx+0x08]
-       movsxd   r8, edx
-       cmp      rax, r8
-       jge      SHORT G_M58051_IG15
-       cmp      ecx, edx
-       jae      G_M58051_IG20
+       mov      eax, dword ptr [rbx+0x08]
+       cmp      ecx, eax
+       jae      SHORT G_M58051_IG15
`

Windows x86/64 benefits the most. Linux and MacOS have very small amout of hits. TP diff is negative -0.01%.

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch, please review this community PR.

**Comment by AndyAyersMS** [comment]
Sorry for not seeing this sooner. Looks like we've lost the asm diffs. Let me bounce this to get a fresh set.

> Windows x86/64 benefits the most. Linux and MacOS have very small amout of positive hits.

Any idea why this is? Is most of the benefit from implicit byref cases?

**Comment by En3Tho** [comment]
@AndyAyersMS I believe this has to do with unpromoted spans which are a very rare case on Linux/MacOS and not so (but still rare) on Windows. But I don't know why it is like that.

@SingleAccretion can you please explain the thing again?

Also tagging @jakobbotsch and @EgorBo for a quick look on again, I'd you have the time.

File: src/coreclr/jit/lclmorph.cpp [hunk 11]
```diff
@@ -1317,7 +1317,13 @@ class LocalAddressVisitor final : public GenTreeVisitor<LocalAddressVisitor>
...
         if (addr->IsLclVarAddr())
         {
-            const LclVarDsc* varDsc = m_compiler->lvaGetDesc(addr->AsLclVarCommon());
+            LclVarDsc* varDsc = m_compiler->lvaGetDesc(addr->AsLclVarCommon());
+
+            // addr is a span field so this lclVar must be a span
+            if (isSpanLength)
+            {
+                varDsc->SetIsSpan(true);
+            }
```
Comment (jakobbotsch) [inline src/coreclr/jit/lclmorph.cpp:1326]: With the handling in `lvaSetStruct` I wouldn't expect this to be necessary.

File: src/coreclr/jit/gentree.cpp [hunk 12]
```diff
@@ -26150,6 +26150,21 @@ bool GenTreeLclVar::IsNeverNegative(Compiler* comp) const
...
+//    comp - the compiler instance
+//
+// Return Value:
+//    true if the lcl var is a Span<T>; otherwise false.
+//
+bool GenTreeLclVar::IsSpan(Compiler* comp) const
+{
+    assert(OperIs(GT_LCL_VAR));
+    return comp->lvaGetDesc(GetLclNum())->IsSpan();
+}
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.cpp:26166]: I would remove this and just check the property on `LclVarDsc` directly in the two places we are using it. Mainly it looks a bit weird to be because it will return true for the implicit byref `LCL_VARs` which really are pointers to spans.

**Review by jakobbotsch — COMMENTED** [review]
Looks fine to me, just a few nits. The diffs are small, but I think taking this change anyway is fine since adding `LclVarDsc::IsSpan` seems good and we'll likely need it for #82946 too.

**Comment by jakobbotsch** [comment]
@MihuBot

File: src/coreclr/jit/lclmorph.cpp (hunk 11 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lclmorph.cpp:1326]: OTOH, I think it would be beneficial to do this in the other direction inside `PromoteStructVar`. When we create the local for the length field there we can mark it as never negative for spans.

Comment (En3Tho) [reply src/coreclr/jit/lclmorph.cpp:1326]: Afaik optimization in this PR only kicked in when span was unpromoted. At least that's what I heard before.

Comment (jakobbotsch) [reply src/coreclr/jit/lclmorph.cpp:1326]: The optimization you added in `IntegralRange` only kicks in then, but we no longer need to mark as `varDsc` as a span when we see the length intrinsic -- the code you added in `lvaSetStruct` handles that much more generally.

**Comment by jakobbotsch** [comment]
> @jakobbotsch Is it okay that we now have both `lvIsNeverNegative` and `lvIsSpan` fields in `LclVarDsc`? I remember the plan was to remove `lvIsNeverNegative` to keep the type from growing but I don't see how it can be removed because it seems quite generic unlike `lvIsSpan`

I think it's fine, we can leave it for now.

> Also, jit-diffs are zero? This is weird.

@MihaZupan's bot runs on linux-x64 where spans are passed by value. It means we always promote them so your optimization does not kick in.

**Comment by En3Tho** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=422571&view=ms.vss-build-web.run-extensions-tab
Small positive diffs - win86/64 benefits the most and even a small win for non-win systems in `System.Security.Cryptography.SP800108HmacCounterKdfImplementationManaged:DeriveBytesOneShot(System.ReadOnlySpan`1` method

**Comment by En3Tho** [comment]
Removed some code changes in lclmorph (basically restored the original state). Let's see if my changes were redundant.

**Comment by jakobbotsch** [comment]
The SPMI collection I did yesterday failed. I'm still trying to make a collection based on this PR. Currently the diffs are misleading due to the misses.

**Comment by En3Tho** [comment]
New spmi diff result is even weirder than no diffs at all :D

https://dev.azure.com/dnceng-public/public/_build/results?buildId=425438&view=ms.vss-build-web.run-extensions-tab

**Comment by jakobbotsch** [comment]
> New spmi diff result is even weirder than no diffs at all :D
> 
> https://dev.azure.com/dnceng-public/public/_build/results?buildId=425438&view=ms.vss-build-web.run-extensions-tab

Those diffs look like they are correct, some of the collection from yesterday succeeded and those diffs are in the collections with low amount of misses.
Though most of these diffs look to be from the JIT being able to fold out debug asserts (SPMI uses checked libraries, it's on our TODO to use release libraries). Specifically this assert can frequently be folded away when there's an implicit `ReadOnlySpan` conversion:
https://github.com/dotnet/runtime/blob/7abea9ea6ac3cde23fe1a890338e22a5a58a51b6/src/libraries/System.Private.CoreLib/src/System/Span.cs#L133

The implicit conversion from `ReadOnlySpan` accesses the `_length` field directly, so it does not go through the existing intrinsic importation path in the JIT, and thus does not get the non-negative annotation. With the new approach (and doing it from promotion) it does.

Sadly I'm still hitting issues getting a full clean SPMI collection... I don't think we can merge this PR until we get that since otherwise we will have too many misses.

**Comment by En3Tho** [comment]
It's no problem. I will try find another small thing to work on meanwhile. Thank you for your help again!

File: src/coreclr/jit/lclvars.cpp [hunk 13]
```diff
@@ -2933,6 +2938,8 @@ void Compiler::lvaSetStruct(unsigned varNum, ClassLayout* layout, bool unsafeVal
         }
 #endif // not TARGET_64BIT
 
+        varDsc->SetIsSpan(this->isSpanClass(layout->GetClassHandle()));
```
Comment (jakobbotsch) [inline src/coreclr/jit/lclvars.cpp:2941]: Can you move this under an `opts.OptimizationEnabled()` check?

Comment (En3Tho) [reply src/coreclr/jit/lclvars.cpp]: Done

Comment (jakobbotsch) [reply src/coreclr/jit/lclvars.cpp]: It looks like we have an ordering issue -- we don't yet know if we will be optimizing or not when `lvaSetStruct` is called for some locals. Can you revert the change and I'll think about if we can move this somewhere else separately.

Comment (En3Tho) [reply src/coreclr/jit/lclvars.cpp]: Sure. I will do it tomorrow.

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Thank you!
