### PR TITLE
Fixing the per object hard limit support for regions

### LINKED ISSUE #36828: Implement committed_by_oh_per_heap
In https://github.com/dotnet/runtime/pull/36731#issuecomment-631912090, @Maoni0 suggested that we can simplify the testing code significantly. This issue is filed to track the work to implement that idea.

### LINKED ISSUE #71790: Fix per object heap commit tracking for regions
We need to make sure the per object heap commit tracking feature works correctly under regions.

Right now, when a region are obtained from or returned to the regions free list, the `committed_by_oh` array is not updated. As a result, the memory is repurposed but the arrays are not updated, we need to fix that.

### PR DESCRIPTION
**Pull request by cshung**
Fixes #71790
Fixes https://github.com/dotnet/runtime/issues/36828

In regions, we can move regions from/to free lists, so just keeping track of the commits for which object-heap during commit/decommit time is no longer enough, we also need to update our accounting when we move them around.

This change created a new bucket for free, that counts the committed memory in the region free lists.

Much of the diff is a refactoring that change the value of `total_oh_count` from `4` to `3`, which is more correct IMO. Many lines were doing `-1` which is no longer needed.

The `commit-accounting` logging statements are intentionally structured so that they can be used to reconstruct the committed region ranges if we have all of them. These can be useful for future tooling purposes (e.g. creating an animated map of how the regions evolves over time)

### CODE REVIEW

File: src/coreclr/gc/gcpriv.h [hunk 1]
```diff
@@ -419,8 +419,10 @@ enum gc_oh_num
     soh = 0,
     loh = 1,
     poh = 2,
-    none = 3,
-    total_oh_count = 4
+    free = 3,
+    none = 4,
+    total_oh_count = 3,
+    total_bucket_count = 5
```
Comment (Maoni0) [inline src/coreclr/gc/gcpriv.h:425]: let's not use seemingly random integer values here. could replace by for example (poh + 1) for total_oh_count

Comment (Maoni0) [inline src/coreclr/gc/gcpriv.h:425]: > total_bucket_count = 5 [](http://example.com/codeflow?start=3&length=23)

I would actually take this out of the gc_oh_num and make it a global variable like recorded_committed_bucket_count

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -2198,7 +2198,7 @@ CLRCriticalSection gc_heap::check_commit_cs;
 
 size_t      gc_heap::current_total_committed = 0;
 
-size_t      gc_heap::committed_by_oh[total_oh_count] = {0, 0, 0, 0};
+size_t      gc_heap::committed_by_oh[gc_oh_num::total_bucket_count] = {0, 0, 0, 0, 0};
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:2201]: instead of writing a lot of 0s here, you could use memset to init this with the size like what we do in init_semi_shared for other global variables.

File: src/coreclr/gc/gc.cpp [hunk 3]
```diff
@@ -2275,7 +2275,7 @@ uint64_t    gc_heap::entry_available_physical_mem = 0;
 
 size_t      gc_heap::heap_hard_limit = 0;
 
-size_t      gc_heap::heap_hard_limit_oh[total_oh_count - 1] = {0, 0, 0};
+size_t      gc_heap::heap_hard_limit_oh[gc_oh_num::total_oh_count] = {0, 0, 0};
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:2278]: same as above

File: src/coreclr/gc/gc.cpp [hunk 4]
```diff
@@ -13743,13 +13807,21 @@ void gc_heap::add_saved_spinlock_info (
...
-gc_heap::init_gc_heap (int  h_number)
+gc_heap::init_gc_heap (int h_number)
 {
 #ifdef MULTIPLE_HEAPS
+#ifdef _DEBUG
+    for (int i = 0; i < gc_oh_num::total_oh_count; i++)
+    {
+        committed_by_oh_per_heap[i] = 0;
+    }
+#endif
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:13818]: could replace this by memset

File: src/coreclr/gc/gc.cpp [hunk 5]
```diff
@@ -13743,13 +13807,21 @@ void gc_heap::add_saved_spinlock_info (
...
+
+    g_heaps [h_number] = this;
 
     time_bgc_last = 0;
 
-    for (int oh_index = 0; oh_index < (gc_oh_num::total_oh_count - 1); oh_index++)
+    for (int oh_index = 0; oh_index < gc_oh_num::total_oh_count; oh_index++)
         allocated_since_last_gc[oh_index] = 0;
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:13825]: let's replace this with memset as well

File: src/coreclr/gc/gc.cpp [hunk 6]
```diff
@@ -13999,7 +14071,7 @@ gc_heap::init_gc_heap (int  h_number)
     generation_of (loh_generation)->free_list_allocator = allocator(NUM_LOH_ALIST, BASE_LOH_ALIST_BITS, loh_alloc_list);
     generation_of (poh_generation)->free_list_allocator = allocator(NUM_POH_ALIST, BASE_POH_ALIST_BITS, poh_alloc_list);
 
-    for (int oh_index = 0; oh_index < (gc_oh_num::total_oh_count - 1); oh_index++)
+    for (int oh_index = 0; oh_index < gc_oh_num::total_oh_count; oh_index++)
         etw_allocation_running_amount[oh_index] = 0;
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:14076]: and this

File: src/coreclr/gc/gc.cpp [hunk 7]
```diff
@@ -22613,6 +22683,18 @@ heap_segment* gc_heap::unlink_first_rw_region (int gen_idx)
     assert (!heap_segment_read_only_p (region));
     dprintf (REGIONS_LOG, ("unlink_first_rw_region on heap: %d gen: %d region: %Ix", heap_number, gen_idx, heap_segment_mem (region)));
 
+    int old_oh = heap_segment_oh (region);
+    int old_heap = heap_segment_heap (region)->heap_number;
+    dprintf(3, ("commit-accounting:  from %d to temp [%Ix, %Ix) for heap %d", old_oh, get_region_start (region), heap_segment_committed (region), old_heap));
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:22688]: should also be under the #ifdef _DEBUG check

File: src/coreclr/gc/gc.cpp [hunk 8]
```diff
@@ -22635,6 +22717,18 @@ void gc_heap::thread_rw_region_front (int gen_idx, heap_segment* region)
     }
     dprintf (REGIONS_LOG, ("thread_rw_region_front on heap: %d gen: %d region: %Ix", heap_number, gen_idx, heap_segment_mem (region)));
 
+    int new_oh = gen_to_oh (gen_idx);
+    int new_heap = this->heap_number;
+    dprintf(3, ("commit-accounting:  from temp to %d [%Ix, %Ix) for heap %d", new_oh, get_region_start (region), heap_segment_committed (region), new_heap));
+
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:22723]: same here

File: src/coreclr/gc/gc.cpp [hunk 9]
```diff
@@ -29835,6 +29929,59 @@ void gc_heap::plan_phase (int condemned_gen_number)
...
+                    for (int i = 0; i < total_generation_count; i++)
+                    {
+                        int oh = i - max_generation;
+#ifdef MULTIPLE_HEAPS
+                        for (int hn = 0; hn < gc_heap::n_heaps; hn++)
+                        {
+                            gc_heap* hp = gc_heap::g_heaps[hn];
+#else
+                        {
+                            gc_heap* hp = nullptr;
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:29945]: the convention to write this for WKS GC is
`gc_heap* hp = pGenGCHeap;`

File: src/coreclr/gc/gc.cpp [hunk 10]
```diff
@@ -30555,7 +30702,8 @@ heap_segment* gc_heap::get_new_region (int gen_number, size_t size)
         heap_segment_next (generation_tail_region (gen)) = new_region;
         generation_tail_region (gen) = new_region;
 
-        verify_regions (gen_number, false, settings.concurrent);
+        size_t unused_total_committed;
+        verify_regions (gen_number, false, settings.concurrent, unused_total_committed);
     }
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:30707]: could get rid of this unused var by checking for null in `verify_regions` (change to a pointer type)

File: src/coreclr/gc/gc.cpp [hunk 11]
```diff
@@ -43217,10 +43366,56 @@ inline bool is_user_alloc_gen (int gen_number)
...
+            }
+#ifdef MULTIPLE_HEAPS
+#ifdef _DEBUG
+            size_t total_accounted = committed_by_oh_per_heap[i - max_generation];
+#else
+            size_t total_accounted = total_committed;
+#endif
+#else
+            size_t total_accounted = committed_by_oh[i - max_generation];
+#endif
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:43410]: please add the actual thing this is check for #endif

File: src/coreclr/gc/gc.cpp [hunk 12]
```diff
@@ -241,6 +241,7 @@ gc_oh_num gen_to_oh(int gen)
         case poh_generation:
             return gc_oh_num::poh;
         default:
+            assert(false);
             return gc_oh_num::none;
```
Comment (cshung) [inline src/coreclr/gc/gc.cpp:245]: >none [](http://example.com/codeflow?start=30&length=4)

rename none to unknown

File: src/coreclr/gc/gc.cpp [hunk 13]
```diff
@@ -43856,6 +44051,8 @@ HRESULT GCHeap::Initialize()
 {
     HRESULT hr = S_OK;
 
+    memset (gc_heap::committed_by_oh, 0, sizeof (gc_heap::committed_by_oh));
```
Comment (cshung) [inline src/coreclr/gc/gc.cpp:44054]: >committed_by_oh [](http://example.com/codeflow?start=58&length=15)

Make this 64 bit only

**Review by Maoni0 — APPROVED** [review]
