### PR TITLE
Fix VN incorrect optimizations with a new JitEEInterface function.

### LINKED ISSUE #42517: Test failure: System.Buffers.Tests.ArrayBufferWriterTests_Char.Advance
failed in job: [runtime-coreclr libraries-jitstress 20200920.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=822733&view=ms.vss-test-web.build-test-results-tab&runId=26190590&resultId=160130&paneView=debug)

failed tests: 
System.Buffers.Tests.ArrayBufferWriterTests_Char.Advance
System.Buffers.Tests.ArrayBufferWriterTests_Byte.Advance

net5.0-Linux-Release-arm-CoreCLR_checked-tailcallstress-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

Error message
~~~
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Buffers.Tests.ArrayBufferWriterTests`1.Advance() in /_/src/libraries/System.Memory/tests/ArrayBufferWriter/ArrayBufferWriterTests.T.cs:line 71
~~~

category:correctness
theme:value-numbering
skill-level:expert
cost:medium

### LINKED ISSUE #49954: Test failure: JIT\\opt\\Structs\\structcopies\\structcopies.cmd in jitstress
https://dev.azure.com/dnceng/public/_build/results?buildId=1048985&view=ms.vss-test-web.build-test-results-tab

Test introduced by https://github.com/dotnet/runtime/pull/48377

### LINKED ISSUE #54102: Invalid CSE with field seqs
```csharp
// Generated by Fuzzlyn v1.1 on 2021-06-12 11:06:35
// Seed: 8276490119048877745
// Reduced from 962.5 KiB to 0.6 KiB in 00:05:32
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public ushort F1;
    public uint F2;
    public byte F3;
    public int F5;
    public S0(byte f3): this()
    {
        F3 = f3;
    }
}

struct S1
{
    public S0 F0;
    public S0 F4;
    public S1(S0 f0): this()
    {
        F0 = f0;
    }
}

struct S2
{
    public S1 F0;
    public S2(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S2 vr0 = new S2(new S1(new S0(1)));
        System.Console.WriteLine(vr0.F0.F0.F3);
        System.Console.WriteLine(vr0.F0.F4.F1);
    }
}
```
We end up CSE'ing the two field seqs and print `1` twice in release.
cc @dotnet/jit-contrib

### LINKED ISSUE #56980: JITted code throws NullRefException in release
Run on x64 Windows:
```csharp
// Generated by Fuzzlyn v1.2 on 2021-07-06 09:46:44
// Seed: 16635934940619066544
// Reduced from 447.5 KiB to 0.6 KiB in 00:02:24
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
struct S0
{
    public uint F1;
    public byte F3;
    public long F4;
    public uint F5;
    public S0(long f4): this()
    {
        F4 = f4;
    }
}

class C0
{
    public S0 F4;
}

struct S1
{
    public C0 F2;
    public S0 F8;
    public S1(C0 f2, S0 f8): this()
    {
        F2 = f2;
        F8 = f8;
    }
}

struct S2
{
    public S1 F0;
    public S2(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S2 vr0 = new S2(new S1(new C0(), new S0(0)));
        M17(ref vr0.F0.F2.F4.F1);
    }

    static void M17(ref uint arg2)
    {
    }
}
```

Disassembly looks quite strange:
```asm
; Assembly listing for method Program:Main()
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; No PGO data
; 0 inlinees with PGO data; 5 single block inlinees; 0 inlinees without PGO data
; Final local variable assignments
;
;  V00 OutArgs      [V00    ] (  1,  1   )  lclBlk (32) [rsp+00H]   "OutgoingArgSpace"
;  V01 tmp1         [V01,T02] (  2,  4   )     ref  ->  rcx         class-hnd exact single-def "NewObj constructor temp"
;* V02 tmp2         [V02    ] (  0,  0   )  struct (24) zero-ref    "NewObj constructor temp"
;* V03 tmp3         [V03,T01] (  0,  0   )  struct (32) zero-ref    do-not-enreg[SFB] single-def "NewObj constructor temp"
;* V04 tmp4         [V04,T03] (  0,  0   )  struct (32) zero-ref    do-not-enreg[SFB] "NewObj constructor temp"
;* V05 tmp5         [V05,T00] (  0,  0   )  struct (24) zero-ref    do-not-enreg[SFB] "Inlining Arg"
;* V06 tmp6         [V06    ] (  0,  0   )  struct (32) zero-ref    do-not-enreg[S] single-def "Inlining Arg"
;* V07 tmp7         [V07,T08] (  0,  0   )     int  ->  zero-ref    V02.F1(offs=0x00) P-INDEP "field V02.F1 (fldOffset=0x0)"
;* V08 tmp8         [V08,T05] (  0,  0   )   ubyte  ->  zero-ref    V02.F3(offs=0x04) P-INDEP "field V02.F3 (fldOffset=0x4)"
;* V09 tmp9         [V09,T06] (  0,  0   )    long  ->  zero-ref    V02.F4(offs=0x08) P-INDEP "field V02.F4 (fldOffset=0x8)"
;* V10 tmp10        [V10,T04] (  0,  0   )     int  ->  zero-ref    V02.F5(offs=0x10) P-INDEP "field V02.F5 (fldOffset=0x10)"
;* V11 tmp11        [V11,T07] (  0,  0   )     ref  ->  zero-ref    single-def "Big Offset Morphing"
;
; Lcl frame size = 40

G_M27646_IG01:              ;; offset=0000H
       4883EC28             sub      rsp, 40
                                                ;; bbWeight=1    PerfScore 0.25
G_M27646_IG02:              ;; offset=0004H
       48B9D0C3EE8CFB7F0000 mov      rcx, 0x7FFB8CEEC3D0
       E89D95E35E           call     CORINFO_HELP_NEWSFAST
       488BC8               mov      rcx, rax
       E8BD15FEFF           call     System.Object:.ctor():this
       8B042500000000       mov      eax, dword ptr [0000H]
                                                ;; bbWeight=1    PerfScore 4.50
G_M27646_IG03:              ;; offset=0022H
       4883C428             add      rsp, 40
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.25

; Total bytes of code 39, prolog size 4, PerfScore 9.90, instruction count 8, allocated bytes for code 39 (MethodHash=cb019401) for method Program:Main()
; ============================================================
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by sandreenko**
This is an alternative for #57076 that gets VM help to avoid non-unique fieldSeq in VN maps.

The main advantage of this approach is that we keep ValueNumbering changes small (and I personally can't be confident in any VN changes) and we don't change other phases to carry any information that was not there. Instead, we ask JitEEInterface where we need to restore field->struct information.

Thanks to @davidwrighton for the VM part of this change.

No pmi diffs, can't do SPMI because the GUID has changed. Will post crossgen2 diffs later, we expect small regressions there.

Fixes #42517, fixes #49954, fixes #54102, fixes #56980.

https://github.com/dotnet/runtime/pull/57076#issue-706770197 has a detailed explanation of the issue, but it is probably faster to look at the test cases added in this PR.

### CODE REVIEW

File: src/coreclr/jit/valuenum.cpp [hunk 1]
```diff
@@ -8006,10 +8006,11 @@ void Compiler::fgValueNumberTree(GenTree* tree)
                                         rhsVNPair.SetBoth(vnStore->VNForExpr(compCurBB, lclVarTree->TypeGet()));
                                     }
 
+                                    lclDefSsaNum = GetSsaNumForLocalVarDef(lclVarTree);
```
Comment (sandreenko) [inline src/coreclr/jit/valuenum.cpp:8009]: For a tree like:
```
N005 ( 11, 10) [001400] -A------R----             *  ASG       long
N004 (  6,  5) [001401] *------N-----             +--*  IND       long
N003 (  3,  3) [001402] -------------             |  \--*  ADDR      byref  Zero Fseq[_00]
N002 (  3,  2) [001403] U------N-----             |     \--*  LCL_VAR   struct<System.Runtime.Intrinsics.Vector128`1[Byte], 16> V45 tmp38        ud:3->4
N001 (  1,  1) [001404] -------------             \--*  LCL_VAR   long   V69 tmp62        u:2 (last use)
```
SSA was working correctly and printing that `001403` is using SSA-3 and defining SSA-4. However, this code, for some reason, was writing the result as a define for SSA-3.

So when at the next tree we were asking for `GetPerSsaData(4)` we were not getting an initialized value.

File: src/coreclr/jit/valuenum.cpp [hunk 2]
```diff
@@ -7273,6 +7269,29 @@ void Compiler::fgValueNumberBlockAssignment(GenTree* tree)
                     isNewUniq = true;
                 }
 
+                if (!isNewUniq && (rhsVarDsc != nullptr) && (lhsVarDsc != nullptr))
```
Comment (sandreenko) [inline src/coreclr/jit/valuenum.cpp:7272]: the check `isNewUniq` is weak here because it is possible that we have already generated a unique VN for rhs but did not report it here.
Because of that we can't narrow the cases that go inside this block to `assert(ClassLayout::AreCompatible(rhsVarDsc->GetLayout(), lhsVarDsc->GetLayout()))`.
However, all cases that pass all these "if" should have unique VN, we just ask for it twice for some trees.

**Comment by sandreenko** [comment]
PTAL @AndyAyersMS  @briansull @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
This fixes the vast majority of my remaining examples, but there are still a few unfixed cases that look similar:
```csharp
// Generated by Fuzzlyn v1.2 on 2021-08-16 12:59:38
// Run on .NET 6.0.0-dev on X64 Windows
// Seed: 9053537220764489964
// Reduced from 104.8 KiB to 0.8 KiB in 00:00:44
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public short F1;
    public ushort F4;
    public S0(short f1): this()
    {
        F1 = f1;
    }
}

struct S1
{
    public S0 F0;
    public S1(S0 f0): this()
    {
        F0 = f0;
    }
}

struct S2
{
    public S1 F1;
    public S0 F2;
    public S2(S1 f1): this()
    {
        F1 = f1;
    }
}

struct S3
{
    public S2 F0;
    public S3(S2 f0): this()
    {
        F0 = f0;
    }
}

struct S4
{
    public sbyte F4;
    public S3 F5;
    public S4(S3 f5): this()
    {
        F5 = f5;
    }
}

public class Program
{
    public static void Main()
    {
        S4 vr0 = new S4(new S3(new S2(new S1(new S0(1)))));
        System.Console.WriteLine(vr0.F5.F0.F1.F0.F1);
        System.Console.WriteLine(vr0.F5.F0.F1.F0.F4);
    }
}
```

```csharp
// Generated by Fuzzlyn v1.2 on 2021-07-08 15:29:32
// Seed: 7236086658031669214
// Reduced from 46.4 KiB to 0.7 KiB in 00:00:28
// Debug: Outputs True
// Release: Outputs False
struct S0
{
}

struct S1
{
    public bool F1;
    public S0 F3;
    public S1(bool f1): this()
    {
        F1 = f1;
    }
}

struct S2
{
    public long F0;
    public S1 F1;
    public S2(S1 f1): this()
    {
        F1 = f1;
    }
}

struct S3
{
    public S2 F0;
    public S3(S2 f0): this()
    {
        F0 = f0;
    }
}

struct S4
{
    public bool F1;
    public S3 F2;
    public S4(S3 f2): this()
    {
        F2 = f2;
    }
}

public class Program
{
    public static void Main()
    {
        S4 vr0 = new S4(new S3(new S2(new S1(true))));
        System.Console.WriteLine(vr0.F1);
        System.Console.WriteLine(vr0.F2.F0.F1.F1);
    }
}
```

**Comment by jakobbotsch** [comment]
Also this one:
```csharp
// Generated by Fuzzlyn v1.2 on 2021-08-16 12:56:37
// Run on .NET 6.0.0-dev on X64 Windows
// Seed: 10782465293682251646
// Reduced from 129.7 KiB to 0.8 KiB in 00:01:40
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public short F0;
    public short F1;
    public int F2;
    public short F3;
    public short F4;
    public S0(short f4): this()
    {
        F4 = f4;
    }
}

struct S1
{
    public S0 F0;
    public int F3;
    public S1(S0 f0): this()
    {
        F0 = f0;
    }
}

struct S3
{
    public S1 F0;
    public S3(S1 f0): this()
    {
        F0 = f0;
    }
}

struct S4
{
    public ushort F3;
    public S3 F4;
    public S4(S3 f4): this()
    {
        F4 = f4;
    }
}

public class Program
{
    static S0[] s_9 = new S0[]{new S0(0)};
    public static void Main()
    {
        S0 vr4 = default(S0);
        S4 vr5 = new S4(new S3(new S1(new S0(1))));
        s_9[0].F4 = vr5.F4.F0.F0.F4;
        System.Console.WriteLine(vr4.F1);
    }
}
```
VN thinks `vr5.F4.F0.F0.F4` is 0 and then CSEs it and `vr4.F1` to the same variable.

File: src/tests/JIT/Regression/JitBlue/Runtime_57282/Runtime_57282_2.cs [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+    {
+        if (Test() == 1)
+        {
+            return 100;
+        }
+        return 101;
+
+    }
+
+}
```
Comment (jakobbotsch) [inline src/tests/JIT/Regression/JitBlue/Runtime_57282/Runtime_57282_2.cs:78]: Looks like this is identical to 57282_1

File: src/coreclr/jit/valuenum.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/valuenum.cpp:8034]: Maybe this comes up now because we no longer set `lvOverlappingFields` in the importer?

File: src/coreclr/jit/valuenum.cpp [hunk 4]
```diff
@@ -7273,6 +7269,54 @@ void Compiler::fgValueNumberBlockAssignment(GenTree* tree)
...
+                            CORINFO_CLASS_HANDLE rhsStructHnd = NO_CLASS_HANDLE;
+                            CORINFO_CLASS_HANDLE lhsStructHnd = NO_CLASS_HANDLE;
+
+                            if (rhsFldSeq == nullptr)
+                            {
+                                rhsStructHnd = rhsVarDsc->GetStructHnd();
+                            }
+                            else
+                            {
+                                CORINFO_FIELD_HANDLE fldHnd = rhsFldSeq->GetTail()->GetFieldHandle();
```
Comment (AndyAyersMS) [inline src/coreclr/jit/valuenum.cpp:7290]: Presumably we've weeded out the `NotAField` cases above?

Maybe assert for it here, as calling `getFieldClass` on a null handle will cause an AV.

File: src/coreclr/jit/valuenum.cpp [hunk 5]
```diff
@@ -7273,6 +7269,54 @@ void Compiler::fgValueNumberBlockAssignment(GenTree* tree)
...
+                                rhsStructHnd                = info.compCompHnd->getFieldClass(fldHnd);
+                            }
+
+                            if (lhsFldSeq == nullptr)
+                            {
+                                lhsStructHnd = lhsVarDsc->GetStructHnd();
+                            }
+                            else
+                            {
+                                CORINFO_FIELD_HANDLE fldHnd = lhsFldSeq->GetTail()->GetFieldHandle();
```
Comment (AndyAyersMS) [inline src/coreclr/jit/valuenum.cpp:7300]: ditto here

File: src/coreclr/jit/valuenum.cpp [hunk 6]
```diff
@@ -7273,6 +7269,54 @@ void Compiler::fgValueNumberBlockAssignment(GenTree* tree)
...
+                            CORINFO_CLASS_HANDLE lhsStructHnd = NO_CLASS_HANDLE;
+
+                            if (rhsFldSeq == nullptr)
+                            {
+                                rhsStructHnd = rhsVarDsc->GetStructHnd();
+                            }
+                            else
+                            {
+                                CORINFO_FIELD_HANDLE fldHnd = rhsFldSeq->GetTail()->GetFieldHandle();
+                                rhsStructHnd                = info.compCompHnd->getFieldClass(fldHnd);
```
Comment (AndyAyersMS) [inline src/coreclr/jit/valuenum.cpp:7291]: There's a bit of a divergence between `doesFieldBelongToClass` and `getFieldClass` -- otherwise you would not have needed this new interface method. Can that cause problems here?

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 7]
```diff
@@ -3531,6 +3531,42 @@ private uint getExpectedTargetArchitecture()
...
+
+            Debug.Assert(!field.IsStatic);
+
+            // doesFieldBelongToClass implements the predicate of...
+            // if field is not associated with the class in any way, return false.
+            // if field is the only FieldDesc that the JIT might see for a given class handle
+            // and logical field pair then return true. This is needed as the field handle here
+            // is used as a key into a hashtable mapping writes to fields to value numbers.
+            //
+            // In this implmentation this is made more complex as the JIT is exposed to CORINFO_FIELD_STRUCT
```
Comment (AndyAyersMS) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:3547]: Maybe make it clearer that the crossgen2 behavior is different than the runtime behavior?

Is this something we should fix down the road? Seems like it would make us more conservative in places when doing R2R codegen.

File: src/coreclr/jit/lclmorph.cpp [hunk 8]
```diff
@@ -246,14 +247,80 @@ class LocalAddressVisitor final : public GenTreeVisitor<LocalAddressVisitor>
...
+                                //       \--*  ADDR      byref
+                                //          \--*  LCL_VAR   struct<Interop+NtDll+IO_STATUS_BLOCK, 16> V08 tmp7
+                                haveCorrectFieldForVN = false;
+                            }
+                            else
+                            {
+
+                                haveCorrectFieldForVN =
+                                    compiler->info.compCompHnd->doesFieldBelongToClass(field->gtFldHnd, clsHnd);
+                                assert(haveCorrectFieldForVN);
```
Comment (AndyAyersMS) [inline src/coreclr/jit/lclmorph.cpp:308]: If we're going to assert like this (as opposed to say `noway` which might be appropriate here, if we think the only ways we can get confused about fields is when optimizing) then you might as well only call the interface method under DEBUG.

**Review by AndyAyersMS — COMMENTED** [review]
Overall this looks to be in good shape.

Left you a few notes.

File: src/coreclr/jit/valuenum.cpp (hunk 1 above)
Comment (briansull) [reply src/coreclr/jit/valuenum.cpp:8034]: It looks like this could be moved to come before line 8051, as that is the first use of this value,

File: src/coreclr/tools/Common/JitInterface/CorInfoBase.cs [hunk 9]
```diff
@@ -2549,10 +2549,25 @@ static uint _getJitFlags(IntPtr thisHandle, IntPtr* ppException, CORJIT_FLAGS* f
...
+        {
+            var _this = GetThis(thisHandle);
+            try
+            {
+                return _this.doesFieldBelongToClass(fldHnd, cls) ? (byte)1 : (byte)0;
+            }
+            catch (Exception ex)
+            {
+                *ppException = _this.AllocException(ex);
+                return default;
```
Comment (briansull) [inline src/coreclr/tools/Common/JitInterface/CorInfoBase.cs:2563]: Shouldn't this be `(byte)0` as above?
I'm not sure why you would want to use `default` here

**Review by briansull — APPROVED** [review]

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs (hunk 7 above)
Comment (sandreenko) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:3547]: >> Maybe make it clearer that the crossgen2 behavior is different than the runtime behavior?

I will add a comment.

>> Is this something we should fix down the road? Seems like it would make us more conservative in places when doing R2R codegen.

I hope we will target to get rid of FldSeq and its dependency on FIELD_HANDLE and STRUCT_HANDLE.

If not we can do:
```
if (crossgen2)
{
 canonFieldHandle = JitEEInterface::getCanonField(fieldHandle);
  bool doesBelong = JitEEInterface::doesFieldBelongToClass(canonFieldHandle , clsHnd);
}
```

but I don't like such a solution, it hammers JIT to VM behavior, we can do it always, not only for crossgen2, but then it is an unnecessary VM call.

File: src/coreclr/jit/lclmorph.cpp (hunk 8 above)
Comment (sandreenko) [reply src/coreclr/jit/lclmorph.cpp:308]: changed to a noway assert. 

> I thought that when using UnsafeAs to change the struct type to a different struct type, we would get a false back from doesFieldBelongToClass

yes, but they have to stay in the same tree without spilling, so something like:
```
struct1 s1 = new S1();
Unsafe.As<s1, s2>(ref s1).fieldOfS2 = 10;
```
if this is imported as one field:
```
FIELD fieldOfS2 
\-- OBJ(struct2)
   \-- ADDR byref
     \--LCL_VAR struct1 
```
here we should catch it and transform as
```
LCL_FLD struct1 (NotAField)
```
instead of
```
LCL_FLD struct1 (fieldOfS2)
```

but I could not create a test where we keep the source as 1 tree so I added an assert that it is unreachable for now.

File: src/coreclr/tools/Common/JitInterface/CorInfoBase.cs (hunk 9 above)
Comment (sandreenko) [reply src/coreclr/tools/Common/JitInterface/CorInfoBase.cs:2563]: I think the current version is correct. It is what most other calls are doing in case of exception, probably the idea is that the value won't be read when `ppException` is set.

**Comment by sandreenko** [comment]
The only failure is `test45929` but it was failing like this in other test runs (checked with kusto), for example, in https://dev.azure.com/dnceng/public/_build/results?buildId=1277844&view=ms.vss-test-web.build-test-results-tab&runId=37787400&resultId=110575&paneView=debug.
