### PR TITLE
Avoid combining conditional select for reduction instrinsics

### LINKED ISSUE #106868: JIT SVE: Assertion failed '!"Got unexpected instruction format after MOVPRFX"' during 'Emit code'
```csharp
// Generated by Fuzzlyn v2.3 on 2024-08-23 10:17:54
// Run on Arm64 Windows
// Seed: 14752078066107523191-vectort,vector64,vector128,armsve
// Reduced from 52.7 KiB to 0.7 KiB in 00:00:54
// Hits JIT assert in Release:
// Assertion failed '!"Got unexpected instruction format after MOVPRFX"' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Emit code' (IL size 54; hash 0xade6b36b; FullOpts)
//
//     File: C:\dev\dotnet\runtime2\src\coreclr\jit\emitarm64sve.cpp Line: 18623
//
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public struct S2
{
    public Vector<int> F2;
}

public class Program
{
    public static S2 s_1;
    public static void Main()
    {
        var vr12 = Vector.Create<int>(0);
        var vr13 = Vector.Create<int>(0);
        var vr14 = M4();
        var vr15 = Vector128.CreateScalar(vr14).AsVector();
        var vr16 = Sve.AndAcross(vr13);
        s_1.F2 = Sve.ConditionalSelect(vr12, vr16, vr15);
    }

    public static int M4()
    {
        Vector<long> vr17 = default(Vector<long>);
        var vr11 = Vector.Create<long>(0);
        var vr8 = Sve.SubtractSaturate(vr17, vr11);
        return 1;
    }
}
```

cc @dotnet/arm64-contrib @dotnet/jit-contrib

### LINKED ISSUE #106871: JIT SVE: Bad codegen with `TestFirstTrue`
```csharp
// Generated by Fuzzlyn v2.3 on 2024-08-23 10:47:43
// Run on Arm64 Windows
// Seed: 6363239363759785984-vectort,vector64,vector128,armsve
// Reduced from 29.6 KiB to 0.8 KiB in 00:00:27
// Debug: Prints 0 line(s)
// Release: Prints 1 line(s)
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static void Main()
    {
        var vr11 = (byte)1;
        var vr12 = Vector128.CreateScalar(vr11).AsVector();
        var vr13 = Vector.Create<double>(1);
        var vr14 = Vector.Create<double>(1);
        var vr15 = (byte)Sve.ConditionalExtractAfterLastActiveElement(vr13, 0, vr14);
        var vr16 = Vector128.CreateScalar(vr15).AsVector();
        var vr17 = Vector.Create<byte>(0);
        var vr18 = (byte)1;
        var vr19 = Vector128.CreateScalar(vr18).AsVector();
        var vr20 = Sve.MinAcross(vr19);
        var vr21 = Sve.ConditionalSelect(vr16, vr20, vr17);
        if (Sve.TestFirstTrue(vr12, vr21))
        {
            System.Console.WriteLine(0);
        }
    }
}
```

cc @dotnet/arm64-contrib @dotnet/jit-contrib

### LINKED ISSUE #106872: JIT SVE: Assertion failed 'intrin.op3->IsVectorZero()' during 'Generate code'
```csharp
// Generated by Fuzzlyn v2.3 on 2024-08-23 10:51:00
// Run on Arm64 Windows
// Seed: 11139641262794602128-vectort,vector64,vector128,armsve
// Reduced from 38.6 KiB to 0.6 KiB in 00:00:32
// Hits JIT assert in Release:
// Assertion failed 'intrin.op3->IsVectorZero()' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 100; hash 0xade6b36b; FullOpts)
//
//     File: C:\dev\dotnet\runtime2\src\coreclr\jit\hwintrinsiccodegenarm64.cpp Line: 755
//
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class C2
{
    public Vector<double> F3;
}

public class Program
{
    public static C2[] s_1;
    public static void Main()
    {
        var vr4 = Vector128.CreateScalar(728.8837854670671d).AsVector();
        var vr5 = Vector128.CreateScalar(1103.750484880559d).AsVector();
        var vr6 = Vector128.CreateScalar(-1881.6772519539704d).AsVector();
        var vr7 = s_1[0].F3;
        s_1[0].F3 = Sve.ConditionalSelect(vr4, Sve.AddSequentialAcross(vr6, vr7), vr5);
    }
}
```

cc @dotnet/arm64-contrib @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by SwapnilGaikwad**
Fixes #106868
Fixes #106871
Fixes #106872

@a74nh @kunalspathak @dotnet/arm64-contrib @arch-arm64-sve @TIHan @amanasifkhalid

### CODE REVIEW

**Comment by SwapnilGaikwad** [comment]
Added a few conditional select tests for reduction intrinsics.
<details>
<summary>Passes all stress tests.</summary>

```
===================Running default===================
------------------- {} -------------------
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector64_Byte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector64_Int16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector64_SByte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector64_UInt16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector128_Byte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector128_Int16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector128_Int32() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector128_SByte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector128_UInt16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcross_Vector128_UInt32() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector64_Byte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector64_Int16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector64_SByte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector64_UInt16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector128_Byte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector128_Int16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector128_Int32() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector128_SByte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector128_UInt16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.AddAcrossWidening_Vector128_UInt32() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector64_Byte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector64_Int16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector64_SByte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector64_UInt16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector128_Byte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector128_Int16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector128_Int32() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector128_SByte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector128_Single() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector128_UInt16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxAcross_Vector128_UInt32() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MaxNumberAcross_Vector128_Single() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector64_Byte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector64_Int16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector64_SByte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector64_UInt16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector128_Byte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector128_Int16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector128_Int32() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector128_SByte() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector128_Single() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector128_UInt16() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinAcross_Vector128_UInt32() : 7
Passed test: _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.MinNumberAcross_Vector128_Single() : 7
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_float() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_double() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_long_sbyte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_long_short() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_long_int() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_long() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_ulong_byte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_ulong_ushort() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_ulong_uint() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddAcross_ulong() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddSequentialAcross_float() : 7
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AddSequentialAcross_double() : 7
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AndAcross_sbyte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AndAcross_short() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AndAcross_int() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AndAcross_long() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AndAcross_byte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AndAcross_ushort() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AndAcross_uint() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_AndAcross_ulong() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_float() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_double() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_sbyte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_short() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_int() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_long() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_byte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_ushort() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_uint() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxAcross_ulong() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxNumberAcross_float() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MaxNumberAcross_double() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_float() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_double() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_sbyte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_short() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_int() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_long() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_byte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_ushort() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_uint() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinAcross_ulong() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinNumberAcross_float() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_MinNumberAcross_double() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_OrAcross_sbyte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_OrAcross_short() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_OrAcross_int() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_OrAcross_long() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_OrAcross_byte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_OrAcross_ushort() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_OrAcross_uint() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_OrAcross_ulong() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_XorAcross_sbyte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_XorAcross_short() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_XorAcross_int() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_XorAcross_long() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_XorAcross_byte() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_XorAcross_ushort() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_XorAcross_uint() : 19
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_XorAcross_ulong() : 19
===================Running jitstress===================
------------------- {'JitMinOpts': '1'} -------------------
------------------- {'JitStress': '1'} -------------------
------------------- {'JitStress': '2'} -------------------
------------------- {'JitStress': '1', 'TieredCompilation': '1'} -------------------
------------------- {'JitStress': '2', 'TieredCompilation': '1'} -------------------
------------------- {'TailcallStress': '1'} -------------------
------------------- {'ReadyToRun': '0'} -------------------
===================Running jitstressregs===================
------------------- {'JitStressRegs': '1'} -------------------
------------------- {'JitStressRegs': '2'} -------------------
------------------- {'JitStressRegs': '3'} -------------------
------------------- {'JitStressRegs': '4'} -------------------
------------------- {'JitStressRegs': '8'} -------------------
------------------- {'JitStressRegs': '0x10'} -------------------
------------------- {'JitStressRegs': '0x80'} -------------------
------------------- {'JitStressRegs': '0x1000'} -------------------
------------------- {'JitStressRegs': '0x2000'} -------------------
===================Running jitstress2-jitstressregs===================
------------------- {'JitStress': '2', 'JitStressRegs': '1'} -------------------
------------------- {'JitStress': '2', 'JitStressRegs': '2'} -------------------
------------------- {'JitStress': '2', 'JitStressRegs': '3'} -------------------
------------------- {'JitStress': '2', 'JitStressRegs': '4'} -------------------
------------------- {'JitStress': '2', 'JitStressRegs': '8'} -------------------
------------------- {'JitStress': '2', 'JitStressRegs': '0x10'} -------------------
------------------- {'JitStress': '2', 'JitStressRegs': '0x80'} -------------------
------------------- {'JitStress': '2', 'JitStressRegs': '0x1000'} -------------------
------------------- {'JitStress': '2', 'JitStressRegs': '0x2000'} -------------------
```
</details>

File: src/coreclr/jit/lowerarmarch.cpp [hunk 1]
```diff
@@ -4055,9 +4055,10 @@ GenTree* Lowering::LowerHWIntrinsicCndSel(GenTreeHWIntrinsic* cndSelNode)
         NamedIntrinsic nestedOp2Id = nestedOp2->AsHWIntrinsic()->GetHWIntrinsicId();
 
         // If the nested op uses Pg/Z, then inactive lanes will result in zeros, so can only transform if
-        // op3 is all zeros.
+        // op3 is all zeros. Such a Csel operation is absorbed into the instruction when emitted. Skip this optimisation
+        // when the nestedOp is a reduce operation.
 
-        if (nestedOp1->IsMaskAllBitsSet() &&
+        if (nestedOp1->IsMaskAllBitsSet() && (!HWIntrinsicInfo::IsReduceOperation(nestedOp2Id)) &&
```
Comment (amanasifkhalid) [inline src/coreclr/jit/lowerarmarch.cpp:4061]: Nit:
```suggestion
        if (nestedOp1->IsMaskAllBitsSet() && !HWIntrinsicInfo::IsReduceOperation(nestedOp2Id) &&
```

File: src/tests/JIT/Regression/JitBlue/Runtime_106868/Runtime_106868.cs [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+        Vector<long> vr17 = default(Vector<long>);
+        var vr11 = Vector.Create<long>(0);
+        var vr8 = Sve.SubtractSaturate(vr17, vr11);
+        return 1;
+    }
+
+    [Fact]
+    public static void TestEntryPoint()
+    {
+        var vr12 = Vector.Create<int>(0);
```
Comment (amanasifkhalid) [inline src/tests/JIT/Regression/JitBlue/Runtime_106868/Runtime_106868.cs:41]: I think you need to wrap all of your tests with `if (Sve.IsSupported)`.

Comment (SwapnilGaikwad) [reply src/tests/JIT/Regression/JitBlue/Runtime_106868/Runtime_106868.cs:41]: oops... missed that again!

File: src/coreclr/jit/lowerarmarch.cpp (hunk 1 above)
Comment (SwapnilGaikwad) [reply src/coreclr/jit/lowerarmarch.cpp]: Done

File: src/tests/JIT/Regression/JitBlue/Runtime_106868/Runtime_106868.cs (hunk 2 above)
Comment (SwapnilGaikwad) [reply src/tests/JIT/Regression/JitBlue/Runtime_106868/Runtime_106868.cs]: Done

File: src/tests/JIT/Regression/JitBlue/Runtime_106868/Runtime_106868.cs [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+            s_1.F2 = Sve.ConditionalSelect(vr12, vr16, vr15);
+            Consume(s_1.F2);
+        }
+    }
+
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    private static void Consume(Vector<int> v)
+    {
+    }
+}
```
Comment (a74nh) [inline src/tests/JIT/Regression/JitBlue/Runtime_106868/Runtime_106868.cs:57]: Nit: missing newline at the end and all the other new files

**Review by a74nh — APPROVED** [review]
LGTM. Happy we've got the extra template testing added too.

File: src/tests/JIT/Regression/JitBlue/Runtime_106868/Runtime_106868.cs (hunk 3 above)
Comment (SwapnilGaikwad) [reply src/tests/JIT/Regression/JitBlue/Runtime_106868/Runtime_106868.cs]: Done

**Review by amanasifkhalid — APPROVED** [review]
LGTM too. Thanks!

File: src/coreclr/jit/lowerarmarch.cpp [hunk 4]
```diff
@@ -4055,9 +4055,10 @@ GenTree* Lowering::LowerHWIntrinsicCndSel(GenTreeHWIntrinsic* cndSelNode)
         NamedIntrinsic nestedOp2Id = nestedOp2->AsHWIntrinsic()->GetHWIntrinsicId();
 
         // If the nested op uses Pg/Z, then inactive lanes will result in zeros, so can only transform if
-        // op3 is all zeros.
+        // op3 is all zeros. Such a Csel operation is absorbed into the instruction when emitted. Skip this optimisation
+        // when the nestedOp is a reduce operation.
 
-        if (nestedOp1->IsMaskAllBitsSet() &&
+        if (nestedOp1->IsMaskAllBitsSet() && !HWIntrinsicInfo::IsReduceOperation(nestedOp2Id) &&
```
Comment (tannergooding) [inline src/coreclr/jit/lowerarmarch.cpp:4061]: The reduction operations are notably a case where the pattern we want is somewhat inversed.

Rather than `CndSel(mask, Op(value), merge)` we want to instead want to check for `Op(CndSel(mask, value, zero))` or similar.

We should have a tracking issue to ensure that happens for .NET 10

Comment (a74nh) [reply src/coreclr/jit/lowerarmarch.cpp:4061]: Being looked at in #101973

**Comment by kunalspathak** [comment]
@amanasifkhalid - any reason why this was not backported to release/9.0?

**Comment by amanasifkhalid** [comment]
@kunalspathak sorry I missed this one -- I'll kick off the backport now
