### PR TITLE
[android] Fix crash in method_to_ir

### LINKED ISSUE #109111: Native SIGSEGV crashes in mono_method_to_ir
### Android framework version

net8.0-android, net9.0-android

### Affected platform version

.NET 8.0.303, .NET 9-rc2

### Description

After switching from Xamarin.Android to .Net8 (and later to .Net9) a new native crash group has appeared in the GooglePlay Console, which seems to be related to the Jit compiler optimizations.

Here are some stacktrace examples from .Net8 releases:
```
#00  pc 0x000000000008ec8c  /data/app/~~Z3FH7HAOgjF8X0p3LrPs3A==/<app.bundle.id>-5Duvjw6R3ilSFqdOL95IVQ==/split_config.armeabi_v7a.apk!libmonosgen-2.0.so (mono_method_to_ir+5763)
dotnet/android#1  pc 0x00000000000844db  /data/app/~~Z3FH7HAOgjF8X0p3LrPs3A==/<app.bundle.id>-5Duvjw6R3ilSFqdOL95IVQ==/split_config.armeabi_v7a.apk!libmonosgen-2.0.so (inline_method+4863)
dotnet/android#2  pc 0x000000000009773f  /data/app/~~Z3FH7HAOgjF8X0p3LrPs3A==/<app.bundle.id>-5Duvjw6R3ilSFqdOL95IVQ==/split_config.armeabi_v7a.apk!libmonosgen-2.0.so (mono_method_to_ir+8082)
dotnet/android#3  pc 0x0000000000077b8b  /data/app/~~Z3FH7HAOgjF8X0p3LrPs3A==/<app.bundle.id>-5Duvjw6R3ilSFqdOL95IVQ==/split_config.armeabi_v7a.apk!libmonosgen-2.0.so (mini_method_compile+3510)
dotnet/android#4  pc 0x0000000000079b71  /data/app/~~Z3FH7HAOgjF8X0p3LrPs3A==/<app.bundle.id>-5Duvjw6R3ilSFqdOL95IVQ==/split_config.armeabi_v7a.apk!libmonosgen-2.0.so (mono_jit_compile_method_inner+4153)
dotnet/android#5  pc 0x000000000007d849  /data/app/~~Z3FH7HAOgjF8X0p3LrPs3A==/<app.bundle.id>-5Duvjw6R3ilSFqdOL95IVQ==/split_config.armeabi_v7a.apk!libmonosgen-2.0.so (jit_compile_method_with_opt+2829)
dotnet/android#6  pc 0x000000000007cdef  /data/app/~~Z3FH7HAOgjF8X0p3LrPs3A==/<app.bundle.id>-5Duvjw6R3ilSFqdOL95IVQ==/split_config.armeabi_v7a.apk!libmonosgen-2.0.so (mono_jit_compile_method+2911)
dotnet/android#7  pc 0x00000000000f49bb  /data/app/~~Z3FH7HAOgjF8X0p3LrPs3A==/<app.bundle.id>-5Duvjw6R3ilSFqdOL95IVQ==/split_config.armeabi_v7a.apk!libmonosgen-2.0.so (common_call_trampoline+628)
dotnet/android#8  pc 0x00000000000f464b  /data/app/~~Z3FH7HAOgjF8X0p3LrPs3A==/<app.bundle.id>-5Duvjw6R3ilSFqdOL95IVQ==/split_config.armeabi_v7a.apk!libmonosgen-2.0.so (mono_magic_trampoline+782)
dotnet/android#9  pc 0x000000000000006a 
```
```
#00  pc 0x00000000000d770c  /data/app/~~-rAQpqUqyTqj-baEpS-Wbw==/<app.bundle.id>-IoSfRyrENCUl2s9Fv_CpjA==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_method_to_ir+5714)
dotnet/android#1  pc 0x00000000000bb2a8  /data/app/~~-rAQpqUqyTqj-baEpS-Wbw==/<app.bundle.id>-IoSfRyrENCUl2s9Fv_CpjA==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mini_method_compile+3498)
dotnet/android#2  pc 0x00000000000bd8e4  /data/app/~~-rAQpqUqyTqj-baEpS-Wbw==/<app.bundle.id>-IoSfRyrENCUl2s9Fv_CpjA==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_jit_compile_method_inner+4132)
dotnet/android#3  pc 0x00000000000c25b0  /data/app/~~-rAQpqUqyTqj-baEpS-Wbw==/<app.bundle.id>-IoSfRyrENCUl2s9Fv_CpjA==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (jit_compile_method_with_opt+2813)
dotnet/android#4  pc 0x00000000000c1a1c  /data/app/~~-rAQpqUqyTqj-baEpS-Wbw==/<app.bundle.id>-IoSfRyrENCUl2s9Fv_CpjA==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_jit_compile_method+2903)
dotnet/android#5  pc 0x0000000000152194  /data/app/~~-rAQpqUqyTqj-baEpS-Wbw==/<app.bundle.id>-IoSfRyrENCUl2s9Fv_CpjA==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (common_call_trampoline+628)
dotnet/android#6  pc 0x0000000000151cf8  /data/app/~~-rAQpqUqyTqj-baEpS-Wbw==/<app.bundle.id>-IoSfRyrENCUl2s9Fv_CpjA==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_magic_trampoline+769)
dotnet/android#7  pc 0x0000000000004300
```
and from .Net9 release:
```
#00  pc 0x00000000000d7f00  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_method_to_ir+5763)
dotnet/android#1  pc 0x00000000000ca404  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (inline_method+4863)
dotnet/android#2  pc 0x00000000000e44e0  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_method_to_ir+8082)
dotnet/android#3  pc 0x00000000000ca404  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (inline_method+4863)
dotnet/android#4  pc 0x00000000000e44e0  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_method_to_ir+8082)
dotnet/android#5  pc 0x00000000000bb234  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mini_method_compile+3510)
dotnet/android#6  pc 0x00000000000bd7e4  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_jit_compile_method_inner+4153)
dotnet/android#7  pc 0x00000000000c26ac  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (jit_compile_method_with_opt+2829)
dotnet/android#8  pc 0x00000000000c1a48  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_jit_compile_method+2911)
dotnet/android#9  pc 0x0000000000152f00  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (common_call_trampoline+628)
dotnet/android#10  pc 0x0000000000152a64  /data/app/~~GaCtuPzjxWKrSIFNyHY-hA==/<app.bundle.id>-dM5thvJqBwaCMFkr6FakqQ==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_magic_trampoline+782)
dotnet/android#11  pc 0x00000000000042e8 
```
```
#00  pc 0x00000000000d7f00  /data/app/~~ebJiSdU6hearCKhMyulx4Q==/<app.bundle.id>-bcccKKnXiArEo-Q4jsVmTw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_method_to_ir+5763)
dotnet/android#1  pc 0x00000000000bb234  /data/app/~~ebJiSdU6hearCKhMyulx4Q==/<app.bundle.id>-bcccKKnXiArEo-Q4jsVmTw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mini_method_compile+3510)
dotnet/android#2  pc 0x00000000000bd7e4  /data/app/~~ebJiSdU6hearCKhMyulx4Q==/<app.bundle.id>-bcccKKnXiArEo-Q4jsVmTw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_jit_compile_method_inner+4153)
dotnet/android#3  pc 0x00000000000c26ac  /data/app/~~ebJiSdU6hearCKhMyulx4Q==/<app.bundle.id>-bcccKKnXiArEo-Q4jsVmTw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (jit_compile_method_with_opt+2829)
dotnet/android#4  pc 0x00000000000c1a48  /data/app/~~ebJiSdU6hearCKhMyulx4Q==/<app.bundle.id>-bcccKKnXiArEo-Q4jsVmTw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_jit_compile_method+2911)
dotnet/android#5  pc 0x0000000000152f00  /data/app/~~ebJiSdU6hearCKhMyulx4Q==/<app.bundle.id>-bcccKKnXiArEo-Q4jsVmTw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (common_call_trampoline+628)
dotnet/android#6  pc 0x0000000000152a64  /data/app/~~ebJiSdU6hearCKhMyulx4Q==/<app.bundle.id>-bcccKKnXiArEo-Q4jsVmTw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (mono_magic_trampoline+782)
dotnet/android#7  pc 0x00000000000042e8 
```

### Steps to Reproduce

Unfortunately, we don't have exact steps to reproduce. We can't (at least reliably) reproduce it during testing phase, but we see a crash group in the GooglePlay Console with a noticeable counter every time we try `.net-android` instead of `Xamarin.Android`.

### Did you find any workaround?

No workaround found yet

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by steveisok**
There exists a possibility where the klass being passed to try_prepare_objaddr_callvirt_optimization is not legit. This can result in unpredictable crashes.

To fix, we pass the MonoType and flush out the MonoClass by calling mono_class_from_mono_type_internal.

Fixes https://github.com/dotnet/runtime/issues/109111

### CODE REVIEW

File: src/mono/mono/mini/method-to-ir.c [hunk 1]
```diff
@@ -5756,8 +5756,10 @@ check_get_virtual_method_assumptions (MonoClass* klass, MonoMethod* method)
  * Returns null, if the optimization cannot be performed.
  */
 static MonoMethod*
-try_prepare_objaddr_callvirt_optimization (MonoCompile *cfg, guchar *next_ip, guchar* end, MonoMethod *method, MonoGenericContext* generic_context, MonoClass *klass)
+try_prepare_objaddr_callvirt_optimization (MonoCompile *cfg, guchar *next_ip, guchar* end, MonoMethod *method, MonoGenericContext* generic_context, MonoType *param_type)
 {
+	MonoClass *klass = mono_class_from_mono_type_internal (param_type);
```
Comment (lambdageek) [inline src/mono/mono/mini/method-to-ir.c:5761]: I'm not sure why the old code checked for `!klass` but we should not pass a null param_type to "class from mono type" so maybe bail if param_type is null just in case?

**Review by lambdageek — APPROVED** [review]

**Comment by srxqds** [comment]
hop you can backport to release/9.0 and release/8.0 branch
