### PR TITLE
Fix alternate stack overflow with superpmi

### LINKED ISSUE #111707: linux/x64: superpmi collection failing during ExecuteHandlerOnCustomStack
The coreclr/libraries tests works on normal but failing since 12/15/2024 for superpmi collection. From the dump, here is the call stack:

Image

### PR DESCRIPTION
**Pull request by janvorli**
The superpmi-shim-collector shared library registers sigsegv handler so that it can flush out the logged data in case the JIT crashes due to some null reference. The sigsegv handler of the superpmi then calls the previous handler, which is the one of coreclr. Both of these handlers run on the alternate stack. Each sigsegv handler has stack frame of about 0xd70 bytes mostly due to the `SignalHandlerWorkerReturnPoint` structure that contains `CONTEXT` structure.
The alternate stack size that we allocate is then on the tipping point of not being sufficient and some variation on how much of the alternate stack is used by the unix kernel causes it to tip over in some cases. This started to happen on x64 Linux after we've added the APX registers to the context.

The problem actually happens due to the `SwitchStackAndExecuteHandler` being inlined into the `sigsegv_handler`. That moves the large `SignalHandlerWorkerReturnPoint` structure to the frame of the `sigsegv_handler`.

This change fixes the problem by marking the
`SwitchStackAndExecuteHandler` as noinline. That makes the `sigsegv_handler` frame significantly smaller.

Close #111707

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @kunalspathak

**Review by jkotas — APPROVED** [review]

File: src/coreclr/pal/src/exception/signal.cpp [hunk 1]
```diff
@@ -582,6 +582,7 @@ Parameters :
 Return :
     The return value from the signal handler
 --*/
+__attribute__((noinline))
```
Comment (jkotas) [inline src/coreclr/pal/src/exception/signal.cpp:585]: Comment explaining the reason for noinline would be nice

**Review by kunalspathak — APPROVED** [review]
I have triggered superpmi collection pipeline internally. ~I will report back if this fixes the issues we are seeing.~

Edit: The internal one will make sure the collections are uploaded.

File: src/coreclr/pal/src/exception/signal.cpp (hunk 1 above)
Comment (janvorli) [reply src/coreclr/pal/src/exception/signal.cpp:585]: I will add one

**Comment by janvorli** [comment]
@kunalspathak there are some superpmi tests failures, but I have hard time deciphering what they mean. Have your internal tests run passed ok?

**Comment by kunalspathak** [comment]
> @kunalspathak there are some superpmi tests failures, but I have hard time deciphering what they mean. Have your internal tests run passed ok?

The failures are infrastructure related, but the ones that we saw failing are fixed with your PR. Thank you!

**Review by jkotas — APPROVED** [review]
