### PR TITLE
Workaround an MSVC bug with __libm_sse2_sincos_

### LINKED ISSUE #98204: double.Cos and double.SinCos can produce very different results
Repro:
```C#
double d = 1e18;
double cos1 = double.Cos(d);
(_, double cos2) = double.SinCos(d);
Console.WriteLine(cos1);
Console.WriteLine(cos2);
```
outputs:
```
0.11837199021871073
-0.9929693207404051
```
on .NET 8

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #98204 

There is currently a bug in MSVCRT where `__libm_sse2_sincos` (which is used by `fp:fast`) is trying to rely on the fact that `sin(x + PI / 2) == cos(x)` and so calls into `__vdecl_sin2` when it should instead call `__vdecl_sincos2`. This causes it to return `sin` for both results given a large enough input, which leads to incorrect results.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @jkoritzinsky and @jkotas, this will somewhat conflict with #98048.

I think it'd be good to get this in first as it likely needs backporting to .NET 8 (customer reported, unintentional regression not caused by us, in API surface that's existed since .NET 6).

File: src/tests/JIT/Regression/JitBlue/Runtime_98204/Runtime_98204.cs [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System;
+using System.Runtime.CompilerServices;
+using Xunit;
+
+public static class Runtime_98068
+{
+    [Fact]
+    [InlineData(1e18)]
```
Comment (jkotas) [inline src/tests/JIT/Regression/JitBlue/Runtime_98204/Runtime_98204.cs:11]: Can this be added to the existing SinCos test under libraries instead of creating a whole new core runtime test for it?

**Comment by jkotas** [comment]
> There is currently a bug in MSVCRT where __libm_sse2_sincos (which is used by fp:fast) calls __vdecl_sin2 when it should instead call __vdecl_sincos2. This causes it to return sin for both results, which leads to incorrect results.

Why was this bug missed by our existing SinCos tests?

**Comment by stephentoub** [comment]
> customer reported

I'm not exactly "customer" :)

**Comment by tannergooding** [comment]
> Why was this bug missed by our existing SinCos tests?

It looks like `__libm_sse2_sincos` is trying to rely on the fact that `sin(x + PI / 2) == cos(x)` and so adjusts the second input by that much. This is correct for infinitely precise arithmetic, but for floating-point means that `cos` is less accurate than it should be for regular values and will not work at all for large values due to the increasing gap between which numbers are representable (it breaks down entirely around `1e16`, but starts showing issues far earlier).

Given that its just calling into SVML and SVML provides a dedicated `__vdecl_sincos2`, that should really be getting used instead.

We missed this because we were testing normal input ranges and not testing anything quite so large, effectively relying on the fact that the underlying `libm` implementation is expected to be largely correct, and that we simply want to minimally validate the bindings are accurate and that it matches any IEEE 754 required behavior (such as `sin(+0) == +0` and `sin(-0) == -0`, with no exception)

**Comment by stephentoub** [comment]
For reference, I found it because I'd implemented a vectorized TensorPrimitives.SinCos and our tests that validate it against the scalar T.SinCos were failing a bunch of tests where we do exercise a wide range of values.

File: src/tests/JIT/Regression/JitBlue/Runtime_98204/Runtime_98204.cs (hunk 1 above)
Comment (tannergooding) [reply src/tests/JIT/Regression/JitBlue/Runtime_98204/Runtime_98204.cs]: Fixed.

**Review by jkotas — COMMENTED** [review]
Thanks

File: src/coreclr/classlibnative/float/floatdouble.cpp [hunk 2]
```diff
@@ -253,6 +253,12 @@ FCIMPL1_V(double, COMDouble::Sin, double x)
     return sin(x);
 FCIMPLEND
 
+#if defined(_MSC_VER)
+// The /fp:fast form of `sincos` for xarch returns sin twice, rather than sincos
```
Comment (stephentoub) [inline src/coreclr/classlibnative/float/floatdouble.cpp:257]: maybe include the link to the issue you opened?

**Review by stephentoub — APPROVED** [review]
thanks
