### PR TITLE
[wasm][debugger] Fix behavior of JMC

### LINKED ISSUE #75763: Web Assembly Blazor debug issue - Childeren could not be evulated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I debug wasm .net 7 preview project,  I am not able to see the details of the object. 
Version of Wasm Sever Projects : 7.0.100-rc.1.22431.12
Version of Microsoft.AspNetCore.Components.WebAssembly.Server : 7.0.0-rc.1.22427.2
you can find the debugger log file as attachment visualstudio-js-debugger.txt
debug view
[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/9583708/visualstudio-js-debugger.txt)

### Expected Behavior

When I debug I should able to see the value of objects.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

7.0.100-rc.1.22431.12

### Anything else?

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.4.0 Preview 2.0

### PR DESCRIPTION
**Pull request by thaystg**
We only should hide private members from types that are not UserCode when JMC is enabled.
I understood it wrongly when I implemented, fixing it now.

Fixes #75763

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs [hunk 1]
```diff
@@ -454,7 +461,7 @@ async Task UpdateBackingFieldWithPropertyAttributes(JObject backingField, string
             {
                 string returnTypeName = await sdbHelper.GetReturnType(getMethodId, token);
                 JObject propRet = null;
-                if (isAutoExpandable || (state is DebuggerBrowsableState.RootHidden && IsACollectionType(returnTypeName)))
+                if (getCommandOptions.HasFlag(GetObjectCommandOptions.AutoExpandable) || getCommandOptions.HasFlag(GetObjectCommandOptions.ForDebuggerProxyAttribute) || (state is DebuggerBrowsableState.RootHidden && IsACollectionType(returnTypeName)))
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:464]: The original code was passing `isAutoExpandable: getCommandOptions.HasFlag(GetObjectCommandOptions.ForDebuggerProxyAttribute)`, but here we are adding `HasFlag(AutoExpandable)` also. Is that deliberate? If we just want to match the old code then I would keep `isAutoExpandable`, and add `getCommandOptions` to the parameters, so the caller keeps control of when to treat something as autoexpandable.

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:464]: Oh, sorry, I just saw that `AutoExpandable` is new. Ignore that comment above.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs [hunk 2]
```diff
@@ -604,7 +607,7 @@ JObject GetNotAutoExpandableObject(int methodId, string propertyName, bool isSta
                     typeId,
                     typeName,
                     getPropertiesParamBuffer,
-                    getCommandType.HasFlag(GetObjectCommandOptions.ForDebuggerProxyAttribute),
+                    getCommandType,
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:610]: You can add `GetObjectCommandOptions.AutoExpandable` when passing this.

**Comment by radical** [comment]
This applies to static members too, correct? Can we adjust any tests for that?

**Comment by radical** [comment]
Would this work for derived classes shadowing private members in base classes?

**Review by radical — APPROVED** [review]
