### PR TITLE
Rework unloadability fix

### LINKED ISSUE #68112: Test failure: Loader\\CollectibleAssemblies\\ResolvedFromDifferentContext\\ResolvedFromDifferentContext\\ResolvedFromDifferentContext.cmd
```
Assert failure(PID 5456 [0x00001550], Thread: 10976 [0x2ae0]): refRetVal->GetAt(i) != NULL

CORECLR! RuntimeTypeHandle::GetInterfaces + 0x4A8 (0x00007ffba633e958) SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ffba5a12078)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ffba5a0f9f8) SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ffba5a0f634)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ffba5546958) <no module>! <no symbol> + 0x0 (0x00007ffb46b42924)
File: D:\a_work\1\s\src\coreclr\vm\runtimehandles.cpp Line: 785
Image: D:\h\w\BB20096C\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\BB20096C\w\A3480908\uploads\Reports\Loader.CollectibleAssemblies\ResolvedFromDifferentContext\ResolvedFromDifferentContext\ResolvedFromDifferentContext.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\BB20096C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ResolvedFromDifferentContext.dll
Running test case LoadOverride
Loading TestInterface by alc "Dependencies" System.Runtime.Loader.AssemblyLoadContext #1 for alc "Test2" TestAssemblyLoadContext #0
Load done, type TestClass.Class obtained
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\BB20096C\p
D:\h\w\BB20096C\w\A3480908\e\Loader\CollectibleAssemblies\ResolvedFromDifferentContext\ResolvedFromDifferentContext\ResolvedFromDifferentContext.cmd
Expected: True
Actual:   False
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1721802&view=ms.vss-test-web.build-test-results-tab&runId=46735808&resultId=108688&paneView=debug

Fails for:
coreclr windows arm64 Checked gcstress0x3
coreclr Linux arm Checked gcstress0x3
coreclr OSX arm64 Checked gcstress0x3
coreclr Linux arm64 Checked gcstress0x3
coreclr Linux arm64 Checked gcstress0xc
coreclr Linux x64 Checked gcstress0xc 

Also fails with a different message:
```
Assert failure(PID 3348 [0x00000d14], Thread: 3084 [0x0c0c]): Postcondition failure: FAILED: GetWriteableData()->m_hExposedClassObject != 0

CORECLR! CHECK::Trigger + 0x2D1 (0x00007fffe310c1d1) CORECLR! MethodTable::GetManagedClassObject + 0x1B6 (0x00007fffe2b640d6)
CORECLR! RuntimeTypeHandle::GetInterfaces + 0x5BF (0x00007fffe2eae72f) SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007fffe22c8ac0)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007fffe22c6f04) SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007fffe22c6c54)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007fffe1f9309f) <no module>! <no symbol> + 0x0 (0x00007fff837f2686)
<no module>! <no symbol> + 0x0 (0x000001de5dca8d20) <no module>! <no symbol> + 0x0 (0x000001de56f0a4d0)
File: D:\a_work\1\s\src\coreclr\vm\methodtable.cpp Line: 3629
Image: C:\h\w\B611097B\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\B611097B\w\A0D70927\uploads\Reports\Loader.CollectibleAssemblies\ResolvedFromDifferentContext\ResolvedFromDifferentContext\ResolvedFromDifferentContext.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B611097B\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ResolvedFromDifferentContext.dll
Running test case LoadOverride
Loading TestInterface by alc "Dependencies" System.Runtime.Loader.AssemblyLoadContext #1 for alc "Test2" TestAssemblyLoadContext #0
Load done, type TestClass.Class obtained
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B611097B\p
C:\h\w\B611097B\w\A0D70927\e\Loader\CollectibleAssemblies\ResolvedFromDifferentContext\ResolvedFromDifferentContext\ResolvedFromDifferentContext.cmd
Expected: True
Actual:   False
```

for:
coreclr windows x64 Checked gcstress0x3
coreclr windows x86 Checked gcstress0x3

### PR DESCRIPTION
**Pull request by janvorli**
This change reworks the recent fix of dependency between two collectible `AssemblyLoadContext`'s when one context uses the other one for resolving its assemblies. There was a problem with the previous solution that has shown up in the newly added test when running with GCStress 3 enabled. 
When we create the reference between the related native LoaderAllocator instances, the managed `LoaderAllocator` of the `AssemblyLoadContext` that was used to resolve the assembly needs to be alive so that we can create a handle to it in the context of the parent `AssemblyLoadContext` and keep it alive for the lifetime of the parent `AssemblyLoadContext`. 
With the previous change, if the `AssemblyLoadContext` that was used to resolve the assembly was collected before the `AssemblyLoadContext.Load` override or the related Resolving event returned and the managed representation of the resolved assembly was collected too, we would not be able to create managed `System.Reflection.Type` instances for the types from the resolved assembly after that. So e.g. calling `GetInterfaces` on a `Type` would fail or crash.

This change fixes the problem by moving the creation of reference between the native `LoaderAllocator`s to the `RuntimeInvokeHostAssemblyResolver` where the managed `Assembly` reference is still alive and thus the related managed `LoaderAllocator` must be alive too. 

Close #68112

### CODE REVIEW

File: src/coreclr/binder/assemblybindercommon.cpp [hunk 1]
```diff
@@ -1153,9 +1154,10 @@ namespace BINDER_SPACE
 
 #if !defined(DACCESS_COMPILE)
 HRESULT AssemblyBinderCommon::BindUsingHostAssemblyResolver(/* in */ INT_PTR pManagedAssemblyLoadContextToBindWithin,
```
Comment (elinor-fung) [inline src/coreclr/binder/assemblybindercommon.cpp:1156]: We can probably do some cleanup around just getting the managed ALC pointer from the AssemblyBinder now that we have the binder - after this change goes in, since we want to backport this.

File: src/coreclr/vm/appdomain.cpp [hunk 2]
```diff
@@ -5115,6 +5084,17 @@ HRESULT RuntimeInvokeHostAssemblyResolver(INT_PTR pManagedAssemblyLoadContextToB
                 COMPlusThrowHR(COR_E_INVALIDOPERATION, IDS_HOST_ASSEMBLY_RESOLVER_DYNAMICALLY_EMITTED_ASSEMBLIES_UNSUPPORTED, name);
             }
 
+            // For collectible assemblies, ensure that the parent loader allocator keeps the assembly's loader allocator
+            // alive for all its lifetime.
+            if (pDomainAssembly->IsCollectible())
```
[the remark this answers is not in the document]
Comment (janvorli) [reply src/coreclr/vm/appdomain.cpp:5089]: Hmm, but we need to create the link even in that case (and also in case of non-default non-collectible context) or rather prevent that from happening by throwing an exception, otherwise the ALC we've resolved from would get collected and we would end up with the issue as before. I have thought we do prevent that already, but local testing has revealed we don't.

[the remark this answers is not in the document]
Comment (elinor-fung) [reply src/coreclr/vm/appdomain.cpp:5089]: Oh, hm, yeah, we are definitely missing that case then, since `EnsureReference` also won't add the reference for non-collectible.

Looks like we error out on collectible assemblies resolved by `AppDomain.AssemblyResolve`.
https://github.com/dotnet/runtime/blob/eb9dd67ce9fc64c468cf5c795fda7057310c22fc/src/coreclr/vm/appdomain.cpp#L4640-L4643
But we don't check the results of other extension points.

[the remark this answers is not in the document]
Comment (janvorli) [reply src/coreclr/vm/appdomain.cpp:5089]: @elinor-fung I've added the exception throwing for NULL parent loader allocator.

File: src/coreclr/vm/appdomain.cpp [hunk 3]
```diff
@@ -5115,6 +5084,22 @@ HRESULT RuntimeInvokeHostAssemblyResolver(INT_PTR pManagedAssemblyLoadContextToB
...
+            {
+                LoaderAllocator *pResultAssemblyLoaderAllocator = pDomainAssembly->GetLoaderAllocator();
+                LoaderAllocator *pParentLoaderAllocator = pBinder->GetLoaderAllocator();
+                if (pParentLoaderAllocator == NULL)
+                {
+                    // The AssemblyLoadContext for which we are resolving the the Assembly is not collectible.
+                    COMPlusThrow(kNotSupportedException, W("NotSupported_CollectibleBoundNonCollectible"));
```
Comment (elinor-fung) [inline src/coreclr/vm/appdomain.cpp:5096]: We should add a test for this (fine with doing it later).

Comment (janvorli) [reply src/coreclr/vm/appdomain.cpp:5096]: Makes sense. I can extend the test I've added previously  to have new test case(s) for that.

Comment (elinor-fung) [reply src/coreclr/vm/appdomain.cpp:5096]: Actually, I think this is technically a breaking change? I agree it is the right thing, but I'm not sure what the appetite for backporting to 6.0 would be (all about it for 7.0 though).

Comment (janvorli) [reply src/coreclr/vm/appdomain.cpp:5096]: For the 6.0, I'll let the shiproom decide whether to do that or just omit the check. You are right that for some apps, this might accidentally work without this check and now it would always throw an exception.

Comment (elinor-fung) [reply src/coreclr/vm/appdomain.cpp:5096]: Sounds good to me.

**Review by elinor-fung — APPROVED** [review]
We should also file a docs issue for how we're now explicitly blocking the non-collectible to collectible assembly: https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md
Or I think marking this with the 'breaking-change' label gives you all the instructions for that.

File: src/coreclr/vm/appdomain.cpp (hunk 3 above)
Comment (janvorli) [reply src/coreclr/vm/appdomain.cpp:5096]: Done
