### PR TITLE
Make `ExceptionHandling.RaiseAppDomainUnhandledExceptionEvent()` thread safe.

### LINKED ISSUE #117840: ExceptionHandling.RaiseAppDomainUnhandledExceptionEvent: Prevent handlers from being invoked multiple times
Perhaps we can put the ExceptionHandling.RaiseAppDomainUnhandledExceptionEvent change to prevent multiple threads for invoking it into a subsequent PR, so that we can unblock this one for crash dump analysis/testing?

_Originally posted by @tommcdon in https://github.com/dotnet/runtime/pull/117832#discussion_r2216993745_

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
The `ExceptionHandling.RaiseAppDomainUnhandledExceptionEvent()` API is permitted to be called by multiple threads but only one should be triggering the event handlers.

Fixes #117840

### CODE REVIEW

File: src/tests/baseservices/exceptions/RaiseAppDomainUnhandledExceptionEvent/RaiseEvent.cs [hunk 1]
```diff
@@ -19,7 +20,14 @@ public HandlerRegistration(UnhandledExceptionEventHandler handler)
...
         {
             AppDomain.CurrentDomain.UnhandledException -= _handler;
+
+            // See usage of s_unhandledExceptionInProgress in the ExceptionHandling class.
+            // This is to ensure that the static field is reset after the test.
+            GetUnhandledExceptionInProgress(null) = 0;
         }
+
+        [UnsafeAccessor(UnsafeAccessorKind.StaticField, Name = "s_unhandledExceptionInProgress")]
+        private static extern ref int GetUnhandledExceptionInProgress([UnsafeAccessorType("System.Runtime.ExceptionServices.ExceptionHandling")] object? obj);
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/tests/baseservices/exceptions/RaiseAppDomainUnhandledExceptionEvent/RaiseEvent.cs]: Good suggestion, but this is intentional.

File: src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs [hunk 2]
```diff
@@ -48,12 +50,33 @@ public static void SetUnhandledExceptionHandler(Func<Exception, bool> handler)
...
         /// </remarks>
         public static void RaiseAppDomainUnhandledExceptionEvent(object exception)
         {
             ArgumentNullException.ThrowIfNull(exception);
 
-            AppContext.OnUnhandledException(exception);
+            if (Interlocked.CompareExchange(ref s_unhandledExceptionInProgress, -1, 0) == 0)
+            {
+                AppContext.OnUnhandledException(exception);
+                s_unhandledExceptionInProgress = 1;
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs]: Good suggestion, but in this case the above approach is acceptable.

File: src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs [hunk 3]
```diff
@@ -48,12 +50,33 @@ public static void SetUnhandledExceptionHandler(Func<Exception, bool> handler)
...
+            {
+                // If we are already in the process of handling an unhandled
+                // exception, we do not want to raise the event again. We wait
+                // here until the other thread finishes raising the unhandled exception.
+                // Waiting is important because it is possible upon returning, this thread
+                // could call some rude abort method that would terminate the process
+                // before the other thread finishes raising the unhandled exception.
+                while (s_unhandledExceptionInProgress != 1)
+                {
+                    Thread.Sleep(1);
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs]: Good suggestion, but in this case a `Sleep(1)` is more appropriate. We would prefer if the thread sleeps rather than simply yields.

**Review by jkotas — APPROVED** [review]
Thanks!

File: src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs [hunk 4]
```diff
@@ -48,12 +50,33 @@ public static void SetUnhandledExceptionHandler(Func<Exception, bool> handler)
...
+        /// This API is thread safe and can be called from multiple threads. However, only one thread
+        /// will trigger the event handlers, while other threads will wait until the event is raised
+        /// and return without raising the event again.
         /// </remarks>
         public static void RaiseAppDomainUnhandledExceptionEvent(object exception)
         {
             ArgumentNullException.ThrowIfNull(exception);
 
-            AppContext.OnUnhandledException(exception);
+            if (Interlocked.CompareExchange(ref s_unhandledExceptionInProgress, -1, 0) == 0)
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs]: Do we need to avoid using monitors here because of runtime shutdown or something? I'm wondering why this isn't a less complicated pattern using `lock`.

Comment (AaronRobinsonMSFT) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs]: We need a triple state of sorts. We need one thread to win and the other threads to wait and then also indicate that any future operations are nops. This approach seems to me to the be the clearest and simplest. The `lock` approach could be made to work but is comparatively heavier weight and would need two variables, `lock` and "state".

I can rework it if you prefer. This is during an exceptional path for process termination so I assume simplest is better. Open to other opinions though.

Comment (jkotas) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs]: This is executed right before the application is going to crash. We want to make it pay as little as possible for it and make it as simple and bullet proof as possible. Regular Monitor Lock is not simple.

Thinking about bullet proofing this further: The current implementation is going to hang if there is a nested crash and UnhandledExceptionEvent is called recursively on the same thread. Would it better if the second call hangs or fail-fasts when this gets called for the second time?

Something like:
```
long currentThreadId = Thread.CurrentOSThreadId;

long previousCrashingThread = Interlocked.CompareExchange(ref s_crashingThread, currentThreadId, 0);
if (previousCrashingThread == 0)
{
     ....
}
else
{
    if (s_crashingThread == previousCrashingThread)
    {
        Environment.FailFast("UnhandledExceptionEvent called recursively");
    }

    // Wait for the crashing thread to finish crashing
    Thread.Sleep(-1);
}
```

Comment (stephentoub) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs]: >  We want to make it pay as little as possible for it

That's one of the reasons I was asking whether monitor would be acceptable. Thread.Sleep(1) could be upwards of 15ms.

> The current implementation is going to hang if there is a nested crash

That was the other reason, as monitor supports reentrancy.

But if the extra low lock complexity is warranted here, that's fine.

Comment (jkotas) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs]: FWIW, we use similar pattern that lets first thread handle the crash and blocks secondary crashing threads in other places:

https://github.com/dotnet/runtime/blob/d757c03be2c39968bca1db2ce9349fce8f1463a3/src/coreclr/vm/eepolicy.cpp#L345-L357

https://github.com/dotnet/runtime/blob/d757c03be2c39968bca1db2ce9349fce8f1463a3/src/coreclr/pal/src/thread/process.cpp#L2195-L2208

File: src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs [hunk 5]
```diff
@@ -48,12 +50,33 @@ public static void SetUnhandledExceptionHandler(Func<Exception, bool> handler)
...
+            {
+                AppContext.OnUnhandledException(exception);
```
Comment (jkotas) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs]: I think this logic should be moved to OnUnhandledException. We want to avoid duplicate invocation of unhandled exception handlers when one thread is crashing with regular unhandled exception and another thread is crashing via RaiseAppDomainUnhandledExceptionEvent.

Comment (AaronRobinsonMSFT) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionHandling.cs]: Okay. I wanted to put it in there, but assumed there was a reason `RaiseAppDomainUnhandledExceptionEvent` has been suggested. Will move.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas @tommcdon Would you like me to remove the locking additions in `RuntimeExceptionHelpers.SerializeCrashInfo()`, introduced in https://github.com/dotnet/runtime/pull/117832?

**Comment by jkotas** [comment]
> Would you like me to remove the locking additions in RuntimeExceptionHelpers.SerializeCrashInfo(), introduced in https://github.com/dotnet/runtime/pull/117832?

It should stay. `RuntimeExceptionHelpers.SerializeCrashInfo` can be called by FailFast without going through OnUnhandledException. We want to prevent the race condition when one thread calls FailFast and other thread hits regular unhandled exception.

**Review by jkotas — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@jkotas Thoughts on https://dev.azure.com/dnceng-public/public/_build/results?buildId=1100021&view=ms.vss-test-web.build-test-results-tab&runId=30092706&resultId=100479&paneView=debug

**Comment by AaronRobinsonMSFT** [comment]
> @jkotas Thoughts on https://dev.azure.com/dnceng-public/public/_build/results?buildId=1100021&view=ms.vss-test-web.build-test-results-tab&runId=30092706&resultId=100479&paneView=debug

Nevermind. I see the issue here. We now have global state for this handler and it needs to be reflected in the testing.

**Comment by jkotas** [comment]
> Thoughts on https://dev.azure.com/dnceng-public/public/_build/results?buildId=1100021&view=ms.vss-test-web.build-test-results-tab&runId=30092706&resultId=100479&paneView=debug

As far as I can tell, there are no unhandled exceptions in this test - the exceptions are handled in native code. It looks like a pre-existing bug to me that UnhandledException event is invoked in this test. @janvorli thoughts about this?

**Comment by jkotas** [comment]
> It looks like a pre-existing bug to me that UnhandledException event is invoked in this test

Related #117620

**Comment by janvorli** [comment]
Let me take a look why we invoke the handler.

**Comment by janvorli** [comment]
Currently, any managed exception that goes through a reverse pinvoke transition and there are no more managed frames on the stack is reported as unhandled, because we really cannot know whether it would be handled or not in the native caller. We invoke the `InternalUnhandledExceptionFilter_Worker` on the first pass and then on the 2nd pass on Windows, we re-raise the exception to let it flow into the external code just in case the code would end up handling it.

As discussed in the #117620, we want to change that behavior to let the exception always flow into the external native calling code on Windows. However, there are some gotchas. Let me discuss those in the #117620 though.

**Comment by AaronRobinsonMSFT** [comment]
> As discussed in the https://github.com/dotnet/runtime/pull/117620, we want to change that behavior to let the exception always flow into the external native calling code on Windows. However, there are some gotchas. Let me discuss those in the https://github.com/dotnet/runtime/pull/117620 though.

Thanks JanV. I'll hold off on this PR until we get some resolution here.

**Comment by janvorli** [comment]
> I'll hold off on this PR until we get some resolution here.

@AaronRobinsonMSFT I actually cannot repro the CI failures locally with your branch checked out. While the failing test reports the exception as unhandled via the event, it still passes for me.

**Comment by AaronRobinsonMSFT** [comment]
> > I'll hold off on this PR until we get some resolution here.
> 
> @AaronRobinsonMSFT I actually cannot repro the CI failures locally with your branch checked out. While the failing test reports the exception as unhandled via the event, it still passes for me.

I believe the failure is only on Windows, the test passes for me too on non-Windows. I've not tried Windows yet. I think there might be some trickiness here based on the predicate for the failfast, it needs the same thread. Is it possible this is a flaky issue? Let me try triggering the CI and see if it fails again.

**Comment by AaronRobinsonMSFT** [comment]
@janvorli This hit the first time I ran it locally on Windows Debug.

```
...\runtime\artifacts\tests\coreclr\windows.x64.Debug\Exceptions\ForeignThread\ForeignThreadExceptions>ForeignThreadExceptions.cmd
BEGIN EXECUTION
 "...\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ForeignThreadExceptions.dll 
Caught exception thrown in a function called by a delegate called through Reverse PInvoke.
Caught exception thrown in a delegate called through Reverse PInvoke on a foreign thread.
Caught hardware exception in a delegate called through Reverse PInvoke on a foreign thread.
Unhandled exception. System.Exception: Exception unhandled in any managed code
   at ForeignThreadExceptionsTest.<>c.<RunTest>b__5_3() in ...\runtime\src\tests\Exceptions\ForeignThread\ForeignThreadExceptions.cs:line 69
Caught exception once
Process terminated.
OnUnhandledException called recursively
   at System.Environment.FailFast(System.Runtime.CompilerServices.StackCrawlMarkHandle, System.String, System.Runtime.CompilerServices.ObjectHandleOnStack, System.String)
   at System.Environment.FailFast(System.Threading.StackCrawlMark ByRef, System.String, System.Exception, System.String)
   at System.Environment.FailFast(System.String)
   at System.AppContext.OnUnhandledException(System.Object)
   at System.Runtime.ExceptionServices.InternalCalls.RhpSfiNext(System.Runtime.StackFrameIterator ByRef, UInt32*, Boolean*, Boolean*)   
   at System.Runtime.EH.DispatchEx(System.Runtime.StackFrameIterator ByRef, ExInfo ByRef)
   at System.Runtime.EH.RhThrowEx(System.Object, ExInfo ByRef)
   at ForeignThreadExceptionsTest+<>c.<RunTest>b__5_3()
Expected: 100
Actual: -2146232797
END EXECUTION - FAILED
FAILED
```

**Comment by janvorli** [comment]
@AaronRobinsonMSFT I wonder what's different for me. I have checked out your branch, built it on Windows x64 in Debug and yet I don't get the crash, neither with nor without debugger attached. I'll try to rebuild everything...

**Comment by janvorli** [comment]
I cannot repro it even after a full clean build of both the repo and tests

**Comment by AaronRobinsonMSFT** [comment]
> I cannot repro it even after a full clean build of both the repo and tests

Okay. It might have to wait until tomorrow, but what can I get for you? Full heap DMP? Anything else?

**Comment by janvorli** [comment]
> Full heap DMP? Anything else?

Dump plus pdbs of the build would be great, thank you!

**Comment by janvorli** [comment]
@AaronRobinsonMSFT  Sigh, my mistake. While I have pulled down your branch, by accident I had checked out another one. I am sorry for the confusion.

**Comment by janvorli** [comment]
The problem causing the failure is that the test really causes an unhandled exception twice on the same thread. The foreign thread catches the exception that runtime considers unhandled because it has flown to external native code with no more managed frames and then it calls a reverse pinvoke on the same thread and it throws again, causing second "unhandled" exception.

**Comment by janvorli** [comment]
Thus your logic thinks there was a recursion. To fix that on the EH side, the processing of exceptions that escape into foreign native code with no more managed frames on top of it will need to be changed so that they are no longer considered unhandled.

**Comment by jkotas** [comment]
> it will need to be changed so that they are no longer considered unhandled.

The current behavior is a regression introduced by EH unification and follow up bug fixes. These exceptions should be considered handled - like it was in .NET Framework and in .NET Core before EH unification. Is this correct?

**Comment by janvorli** [comment]
> The current behavior is a regression introduced by EH unification and follow up bug fixes. These exceptions should be considered handled - like it was in .NET Framework and in .NET Core before EH unification. Is this correct?

Right. Although there will always be some differences in the EH due to the new EH not using SEH. The question will be which way of handling the differences is more acceptable than others. I have originally thought the concept of considering exceptions escaping last managed frame on a foreign thread unhandled from the managed code point of view was reasonable, but the recent issues related to that has proven me wrong.

**Comment by jkotas** [comment]
@AaronRobinsonMSFT I think this one is good to go in now.
