### PR TITLE
Fix System.DirectoryServices.Protocols to work on Linux

### LINKED ISSUE #66243: System.DirectoryServices.Protocols.CompareRequest fails on Linux when invoked with string attribute value
### Description

Using `CompareRequest (string distinguishedName, string attributeName, string value)` always fails on Linux. 

`LdapPal.CompareDirectoryEntries` from [LdapPal.Linux.cs](https://github.com/dotnet/runtime/blob/3ede8095da51d5d27a890020b61376155e9a61c2/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/Interop/LdapPal.Linux.cs#L15) does not pass `strValue` parameter to `Interop.Ldap.ldap_compare` from [Interop.Ldap.cs](https://github.com/dotnet/runtime/blob/3ede8095da51d5d27a890020b61376155e9a61c2/src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs#L256)

### Reproduction Steps

```csharp
        [TestMethod]
        public void Test1()
        {
            var server = new LdapDirectoryIdentifier("db.debian.org", 389);
            var connection = new LdapConnection(server);
            connection.AuthType = AuthType.Anonymous;
            connection.SessionOptions.ProtocolVersion = 3;
            var response = connection.SendRequest(new CompareRequest("dc=debian,dc=org", "dc", "debian"));
            Assert.AreEqual(ResultCode.CompareTrue, response.ResultCode);
        }
```

### Expected behavior

Should not fail

### Actual behavior

Fails with error DirectoryOperationException: A protocol error occurred

```
  Error Message:
   Test method CompareRequest1.UnitTest1.Test1 threw exception:
System.DirectoryServices.Protocols.DirectoryOperationException: A protocol error occurred. A protocol error occurred.
  Stack Trace:
      at System.DirectoryServices.Protocols.LdapConnection.ConstructResponseAsync(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, Boolean exceptionOnTimeOut, Boolean sync)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request)
   at CompareRequest1.UnitTest1.Test1()
```

### Regression?

_No response_

### Known Workarounds

Use `CompareRequest (string distinguishedName, string attributeName, byte[] value)` by converting string attribute value to byte array 

```csharp
        [TestMethod]
        public void Test2()
        {
            var server = new LdapDirectoryIdentifier("db.debian.org", 389);
            var connection = new LdapConnection(server);
            connection.AuthType = AuthType.Anonymous;
            connection.SessionOptions.ProtocolVersion = 3;
            var response = connection.SendRequest(new CompareRequest("dc=debian,dc=org", "dc", Encoding.UTF8.GetBytes("debian")));
            Assert.AreEqual(ResultCode.CompareTrue, response.ResultCode);
        }
```

### Configuration

dotnet --info

.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.200/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### Other information

_No response_

### PR DESCRIPTION
**Pull request by psteniusubi**
Fix #66243 

LdapPal.CompareDirectoryEntries on Linux does not pass strValue to Interop.Ldap.ldap_compare

This fix always converts CompareRequest.Assertion to byte array

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=67338) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=67338) before we can accept your contribution.<br/><br/>:x: psteniusubi [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=67338)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=67338) it.</sub>

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs [hunk 1]
```diff
@@ -634,30 +634,39 @@ private int SendRequestHelper(DirectoryRequest request, ref int messageID)
...
-                            };
-                            Marshal.Copy(byteArray, 0, berValuePtr.bv_val, byteArray.Length);
-                        }
+                        var encoder = new UTF8Encoding();
+                        byteArray = encoder.GetBytes(str);
+                    }
+                    else if (assertion[0] is Uri uri)
+                    {
+                        var encoder = new UTF8Encoding();
+                        byteArray = encoder.GetBytes(uri.ToString());
```
Comment (gfoidl) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:646]:
```suggestion
                        byteArray = Encoding.UTF8.GetBytes(uri.ToString());
```

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs [hunk 2]
```diff
@@ -634,30 +634,39 @@ private int SendRequestHelper(DirectoryRequest request, ref int messageID)
...
-                        stringValue = assertion[0].ToString();
+                        throw new ArgumentException(SR.ValidValueType);
                     }
 
+                    berValuePtr = new BerVal
+                    {
+                        bv_len = byteArray.Length,
+                        bv_val = Marshal.AllocHGlobal(byteArray.Length)
+                    };
+                    Marshal.Copy(byteArray, 0, berValuePtr.bv_val, byteArray.Length);
```
Comment (gfoidl) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:662]: I wonder if `byte[] byteArray` is needed or if this can be stackallocated (and the copied)?

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs [hunk 3]
```diff
@@ -634,30 +634,39 @@ private int SendRequestHelper(DirectoryRequest request, ref int messageID)
...
-                        {
-                            berValuePtr = new BerVal
-                            {
-                                bv_len = byteArray.Length,
-                                bv_val = Marshal.AllocHGlobal(byteArray.Length)
-                            };
-                            Marshal.Copy(byteArray, 0, berValuePtr.bv_val, byteArray.Length);
-                        }
+                        var encoder = new UTF8Encoding();
+                        byteArray = encoder.GetBytes(str);
```
[the remark this answers is not in the document]
Comment (psteniusubi) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:641]: Hi @gfoidl. Thank you for your comments. I'm following style and conventions elsewhere in this component. More specifically implementation of BuildAttributes method:

https://github.com/dotnet/runtime/blob/d64b8af65e7eecc52bf81d40315fa80c64c818c1/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs#L1277

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs (hunk 2 above)
Comment (psteniusubi) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:662]: This code follows how BuildAttributes method does the same conversions. I don't think improving this is within scope of this fix.

Comment (gfoidl) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:662]: > improving this is within scope of this fix.

You are right, that's going beyond the fix.

The code here seems pretty old, and was written before span came around. So there could be a general overhaul -- but I don't know the plans here and if it is worth, as such an upgrade comes with cost and this code seems to be battle-tested, which a re-write has to prove first.

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs [hunk 4]
```diff
@@ -634,30 +634,39 @@ private int SendRequestHelper(DirectoryRequest request, ref int messageID)
...
+                    }
+                    else if (assertion[0] is Uri uri)
+                    {
+                        var encoder = new UTF8Encoding();
```
Comment (joperezr) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:645]: Looks like the test you are adding is only covering when the assertion is a string. Can you please turn your Fact into a Theory instead that uses both string and URI in order to make sure we have coverage for both?

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs [hunk 5]
```diff
@@ -634,30 +634,39 @@ private int SendRequestHelper(DirectoryRequest request, ref int messageID)
...
+                        byteArray = encoder.GetBytes(uri.ToString());
+                    }
+                    else if (assertion[0] is byte[] bytes)
+                    {
+                        byteArray = bytes;
                     }
                     else
                     {
-                        stringValue = assertion[0].ToString();
+                        throw new ArgumentException(SR.ValidValueType);
```
Comment (joperezr) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:654]: Can we also add a tests that ensures that this Argument Exception gets thrown?

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs [hunk 6]
```diff
@@ -634,30 +634,39 @@ private int SendRequestHelper(DirectoryRequest request, ref int messageID)
...
+                        byteArray = encoder.GetBytes(str);
+                    }
+                    else if (assertion[0] is Uri uri)
+                    {
+                        var encoder = new UTF8Encoding();
+                        byteArray = encoder.GetBytes(uri.ToString());
+                    }
+                    else if (assertion[0] is byte[] bytes)
+                    {
+                        byteArray = bytes;
```
Comment (joperezr) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:650]: What happens if the bytes were not utf8 encoded?

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs (hunk 2 above)
Comment (joperezr) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:662]: I don't think we should stackalloc this particular array since it is based on user input, so we want to make sure that we don't call stackalloc from arbitriary input size.

Comment (psteniusubi) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:662]: Using something like Marshal.StringToCoTaskMemUTF8 could save one allocation. But as I said I don't think this should be within scope of this fix.

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs (hunk 5 above)
Comment (psteniusubi) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:654]: I had a look at this. Turns out DirectoryAttribute rejects other value types than string, Uri and byte[]. So this condition never happens.

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs (hunk 6 above)
Comment (psteniusubi) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:650]: CompareRequest operation returns ResultCode.CompareFalse. I added a test case for this.

Comment (joperezr) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:650]: Right, but I guess my question is: should we support that? Or is it expected that bytes will always be UTF8 encoded? I quickly looked at our [docs](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.protocols.comparerequest.-ctor?view=dotnet-plat-ext-6.0#system-directoryservices-protocols-comparerequest-ctor(system-string-system-string-system-byte())) and we don't seem to mention anywhere that the bytes need to be UTF8 encoded.

Comment (joperezr) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:650]: I don't want to block your contribution on that, if we think UTF8 is what should be expected then we can just update our docs to point that out, and perhaps consider in the future add another constructor to CompareRequest that takes in bytes[] and Encoding.

Comment (psteniusubi) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:650]: String values are always utf-8 encoded on the wire (per [ldap spec](https://datatracker.ietf.org/doc/html/rfc4511#section-4.1.2)). The byte[] value is as-is on the wire.

Comment (joperezr) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:650]: Sounds good, we can update the docs then to call this out, but we can do that separately from your PR

**Review by joperezr — APPROVED** [review]
Thanks for the contribution!

**Comment by danmoseley** [comment]
Yes, thanks @psteniusubi . We would welcome other contributions, if you are interested.
