### PR TITLE
Return actual LoadLibrary failures for IJW scenarios.

### LINKED ISSUE #45611: Improve the failure messaging for C++/CLI binaries that are missing dependencies
### Description

When loading a C++/CLI assembly if there are missing native dependencies the error message is always `COR_E_BADIMAGEFORMAT`.

https://github.com/dotnet/runtime/blob/7e9dee84a91560dc8e3fda8bf1ddef664d07aa99/src/coreclr/src/vm/peimage.cpp#L1059-L1062

This is confusing when examining the assembly because it is typically of the correct bitness, but the error message indicates otherwise.

https://github.com/dotnet/runtime/blob/29e9b5b7fd95231d9cd9d3ae351404e63cbb6d5a/src/coreclr/src/inc/corerror.xml#L2356-L2360

### Configuration

All Windows platforms that support C++/CLI.

### Regression?

This is a regression from the behavior on .NET Framework when the correct failure was propagated.

/cc @jkoritzinsky @elinor-fung @tgani-msft

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #45611

/cc @jkoritzinsky @elinor-fung

### CODE REVIEW

File: src/coreclr/vm/peimage.cpp [hunk 1]
```diff
@@ -1045,21 +1047,24 @@ PTR_PEImageLayout PEImage::CreateLayoutMapped()
...
-                // IJW images must be loaded, not mapped
-                ThrowHR(COR_E_BADIMAGEFORMAT);
+                // For compat with older CoreCLR versions we will fallback to the
+                // COR_E_BADIMAGEFORMAT error code if a failure wasn't indicated.
+                loadFailure = FAILED(loadFailure) ? loadFailure : COR_E_BADIMAGEFORMAT;
+                EEFileLoadException::Throw(GetPath(), loadFailure);
             }
+
+            // IL only images will always be mapped. We also dont bother doing the conversion of PE header on 64bit,
+            // as done below for the desktop case, as there is no appcompat burden for CoreCLR on 64bit to have that conversion done.
```
Comment (elinor-fung) [inline src/coreclr/vm/peimage.cpp:1066]: > conversion of PE header on 64bit, as done below for the desktop case

I don't see what this comment is referring to - is this still applicable?

**Review by elinor-fung — APPROVED** [review]

File: src/coreclr/vm/peimage.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/peimage.cpp:1066]: It is because it was done in .NET Framework. I meant to keep part of it to indicate that it was done on .NET Framework.

**Comment by AaronRobinsonMSFT** [comment]
Last change is comment update only so will skip validation.
