### PR TITLE
Type equivalence support in Crossgen2

### LINKED ISSUE #67855: crossgen2 fails on assemblies that include embedded types
### Description

The .NET 6 runtime supports type equivalence which comes from embedding types (EmbedInteropTypes=true on a reference, or using the `/link` parameter to csc.exe instead of `/reference` for an embeddable assembly).
Crossgen2 fails to compile assemblies that contain embedded types (one that was compiled with `/link`).

### Reproduction Steps

The minimal embeddable type in the assembly doesn't seem to repro the problem. So all I can do is offer the full original repro, ready to run (😉): [via OneDrive for Business](https://microsoft-my.sharepoint.com/:u:/p/andarno/ERzsLZk6lvRBqEQ-b3OU0fkBw2qDsSPBI-gqCGu1yWqdrw?e=WEkR7Z). 
Just extract the .zip and run `repro.cmd`.

### Expected behavior

crossgen completes successfully.

### Actual behavior

crossgen2 crashes with this exception:

```
Error: [embedding-referenced-assembly]embedded-type
System.NotImplementedException: [embedding-referenced-assembly]embedded-type
   at ILCompiler.DependencyAnalysis.ReadyToRun.ModuleTokenResolver.GetModuleTokenForType(EcmaType type, Boolean throwIfNotFound)
   at ILCompiler.DependencyAnalysis.ReadyToRun.SignatureContext.GetTargetModule(TypeDesc type)
   at ILCompiler.DependencyAnalysis.ReadyToRun.TypeFixupSignature.GetData(NodeFactory factory, Boolean relocsOnly)
   at ILCompiler.DependencyAnalysis.ReadyToRun.ImportSectionNode.MaterializeSignature(NodeFactory r2rFactory)
   at ILCompiler.DependencyAnalysis.ReadyToRun.ImportSectionsTableNode.MaterializeSignature()
   at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestMetadataTableNode.ComputeLastSetOfModuleIndices()
   at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestMetadataTableNode.GetManifestAssemblyMvidTableData()
   at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestAssemblyMvidHeaderNode.GetData(NodeFactory factory, Boolean relocsOnly)
   at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable()
   at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)
   at ILCompiler.Program.RunSingleCompilation(Dictionary`2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary`2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
   at ILCompiler.Program.Run(String[] args)
   at ILCompiler.Program.Main(String[] args)
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by davidwrighton**
We currently have a small behavior hole on Windows where if a binary uses TypeEquivalence, it is technically possible to get crossgen2 to generate invalid code.

This fixes that by adding support for type equivalence to the managed type system, and adjusting crossgen2 to use it. This is complicated by the detail that this may generate some type references which cannot be referenced from an R2R file, so additional error checking was needed (this additional error checking is what fixes #67855).

However, while basic support for type equivalence has been added to the type system, support for actually performing type equivalent interface resolution has not been, so devirtualization of type equivalent interface calls is disabled. At this time, I do not expect to see a customer need for implementing that fairly complicated feature

Fixes #67855

### CODE REVIEW

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+        {
+            get
+            {
+                if (_data != null)
+                {
+                    if (object.ReferenceEquals(_data, TypeIdentifierData.Empty))
+                        return null;
+                    return _data;
+                }
+                lock(this)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs:104]: We don't generally lock on type system objects because with enough unchecked locks we'll eventually get deadlocks (see another spot where I'm policing this: https://github.com/dotnet/runtime/pull/87532#discussion_r1228848088). Would CompareExchange be unacceptable?

Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs:104]: Yes. This was just a bit of laziness on my part.

**Comment by davidwrighton** [comment]
@trylek the tests are passing, (except for a couple mono issues that are known). Could you take a look and let me know what you can sign off on, and what I need to find someone else to sign off on?

File: src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs [hunk 2]
```diff
@@ -0,0 +1,312 @@
...
+                for (int i = 0; i < thisType.Instantiation.Length; i++)
+                {
+                    if (!thisType.Instantiation[i].IsEquivalentTo(otherType.Instantiation[i], visited))
+                    {
+                        return false;
+                    }
+                }
+
+                // Generic equivalence only allows the instantiation to be non-equal
+                return thisType.HasSameTypeDefinition(otherType);
```
Comment (trylek) [inline src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs:76]: Perf nit - wouldn't it be faster to first check whether the two types have the same type definition and only then traverse the instantiations?

File: src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs [hunk 3]
```diff
@@ -0,0 +1,312 @@
...
+                if ((containingType1 != null) && !IsEquivalentTo_TypeDefinition(containingType1, containingType2, visited))
+                {
+                    return false;
+                }
+
+                if (type1.IsInterface != type2.IsInterface)
+                    return false;
+                if (type1.IsInterface)
+                {
+                    if (!type2.IsInterface)
```
Comment (trylek) [inline src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs:136]: Nit - I believe this check is superfluous; you have already made sure at line 132 that <code>type1.IsInterface</code> is the same as <code>type2.IsInterface</code> so it seems to me that you should be able to safely <code>return true</code> in this conditional statement.

File: src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs [hunk 4]
```diff
@@ -0,0 +1,312 @@
...
+                        return false;
+
+                    return true;
+                }
+                else if ((type1.IsEnum != type2.IsEnum) ||  (type1.IsValueType != type2.IsValueType))
```
Comment (trylek) [inline src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs:141]: Nit - it might make the code slightly easier to read if you removed the <code>else</code> statement at line 141 - the previous conditional statements act as "filters" that either directly return the result or proceed to the next statement.

File: src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs [hunk 5]
```diff
@@ -0,0 +1,312 @@
...
+                    }
+
+                    if ((field1 == null) || (field2 == null))
+                    {
+                        // we ran out of fields on 1 type.
+                        return false;
+                    }
+
+                    // Compare the field signatures for equivalence
+                    // TODO: Technically this comparison should include custom modifiers on the field signatures
```
Comment (trylek) [inline src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs:217]: Is this a real possibility that we should track with an issue?

File: src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs [hunk 6]
```diff
@@ -0,0 +1,312 @@
...
+                    fieldNotValidInEquivalentTypeFound = false;
+                    while (fieldEnum.MoveNext())
+                    {
+                        var field = fieldEnum.Current;
+
+                        if (field.GetEffectiveVisibility() == EffectiveVisibility.Public && !field.IsStatic)
+                            return field;
+
+                        // Only public instance fields, and literal fields on enums are permitted in type equivalent structures
+                        if (!enumMode || field.IsLiteral)
```
Comment (trylek) [inline src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs:301]: I may be missing something but shouldn't this check be negated? I would assume that <code>!field.IsLiteral</code> is what signifies that the type doesn't support equivalence.

File: src/coreclr/tools/Common/TypeSystem/Common/MethodDesc.cs [hunk 7]
```diff
@@ -284,6 +294,21 @@ private bool Equals(MethodSignature otherSignature, bool allowCovariantReturn)
             }
 
             return false;
+
+            static bool CompareTypeHelper(TypeDesc type1, TypeDesc type2, bool allowEquivalence, StackOverflowProtect visited)
```
Comment (trylek) [inline src/coreclr/tools/Common/TypeSystem/Common/MethodDesc.cs:298]: Naming nit - both my old C++ background and Compare-like C# APIs typically return plus / minus / zero result of the comparison whereas this feels more like something in the vein of <code>IsTypeEqualHelper</code>. Not a big deal but I had to fight this mental model half a dozen times while reviewing this change.

**Review by trylek — APPROVED** [review]
In general the Crossgen2 logic looks reasonable to me. I'm not a COM expert so that the craziness around GUIDs is somewhat beyond my comprehension, I guess Aaron would be a great pick if you're after more detailed scrutiny in this area. I have shared a couple of observations including one place that I believe to be a bug but I'm not blocking my approval on that as I'm well aware of your long-standing engineering diligence in addressing all review feedback.

File: src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs (hunk 5 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs:217]: Eh, no. We don't even check field types on fields correctly today for normal field references, much less custom modifiers.

File: src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs (hunk 3 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs:136]: Thank you

File: src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs (hunk 2 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs:76]: Good point. Changed

File: src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs (hunk 6 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/CastingHelper.TypeEquivalence.cs:301]: Yes. Good catch, that inspired me to build a whole test suite, so I found some more issues. Sigh. Thank you though.

File: src/coreclr/tools/aot/ILCompiler.TypeSystem.Tests/TypeEquivalenceAssembly/TypesWhichDoNotLoad.cs [hunk 8]
```diff
@@ -0,0 +1,68 @@
...
+namespace TypesWhichDoNotLoad
+{
+    // A case where a field is not public
+    [TypeIdentifier("TypesWhichDoNotMatch", "Type1")]
+    public struct Type1
+    {
+        int field;
+    }
+
+    // A case where the type is not both public
```
Comment (trylek) [inline src/coreclr/tools/aot/ILCompiler.TypeSystem.Tests/TypeEquivalenceAssembly/TypesWhichDoNotLoad.cs:15]: Nit - I'm missing the purpose of the word *both* in this code comment (unless *both public* is a technical term I haven't yet come across); dtto for the next two test cases.

**Review by trylek — APPROVED** [review]
LGTM, thanks for implementing the extensive test suite!
