### PR TITLE
Avoid discarding upper bits when folding GT_SWITCH

### LINKED ISSUE #68568: Dead code after switch over int64 influences result
### Description

I attached two .il files, they are almost the same. In Switch0.il.txt the trailing dead code is commented out, in Switch4.il.txt it is not. The two programs have different results.

### Reproduction Steps

[Switch0.il.txt](https://github.com/dotnet/runtime/files/8566128/Switch0.il.txt)
$ ~/dotnet-bld/artifacts/bin/coreclr/Linux.x64.Release/ilasm -output:Switch0.exe Switch0.il.txt 

Microsoft (R) .NET IL Assembler.  Version 5.0.0
[...]
Operation completed successfully
$ ~/dotnet-bld/artifacts/bin/coreclr/Linux.x64.Release/corerun -c ~/dotnet-bld/.dotnet/shared/Microsoft.NETCore.App/5.0.0-rc.2.20475.5/ Switch0.exe
$ echo $?
0

[Switch4.il.txt](https://github.com/dotnet/runtime/files/8566129/Switch4.il.txt)
$ ~/dotnet-bld/artifacts/bin/coreclr/Linux.x64.Release/ilasm -output:Switch4.exe Switch4.il.txt 

Microsoft (R) .NET IL Assembler.  Version 5.0.0
[...]
Operation completed successfully
$ ~/dotnet-bld/artifacts/bin/coreclr/Linux.x64.Release/corerun -c ~/dotnet-bld/.dotnet/shared/Microsoft.NETCore.App/5.0.0-rc.2.20475.5/ Switch4.exe
$ echo $?
4

### Expected behavior

Both programs should return the same exitcode.

### Actual behavior

Switch0.exe returns 0, Switch4.exe returns 4.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

$ cd ~/dotnet-bld/
$ git log                                                                                                         
commit cf258a14b70ad9069470a108f13765e0e5988f51 (HEAD, tag: v5.0.0-rtm.20519.4, tag: v5.0.0)
[...]
$ uname -a
Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jakobbotsch**
For better or worse the JIT allows switches on up to native int sized discriminees.
This particular optimization that folds for a constant discriminee was discarding the upper bits.

I've also added some extra logging.

Fix #68568

### CODE REVIEW

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -14885,17 +14883,13 @@ Compiler::FoldResult Compiler::fgFoldConditional(BasicBlock* block)
...
-            unsigned switchVal;
-            switchVal = (unsigned)cond->AsIntCon()->gtIconVal;
-            unsigned jumpCnt;
-            jumpCnt = block->bbJumpSwt->bbsCount;
-            BasicBlock** jumpTab;
-            jumpTab = block->bbJumpSwt->bbsDstTab;
-            bool foundVal;
-            foundVal = false;
+            // Find the actual jump target
+            size_t       switchVal = (size_t)cond->AsIntCon()->gtIconVal;
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:14889]: Actual fix is on this line.

Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:14889]: Actual fix is on this line.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Review by AndyAyersMS — APPROVED** [review]
