### PR TITLE
Fix mismatch between boxed/unboxed method entrypoints

### LINKED ISSUE #99198: Native AOT bad code gen for constrained call
This looks to be a complicated set of GVMs and direct dispatches to the same interface.

Works on CoreCLR, produces either a null-ref or AV with Native AOT. Core problem is that the call to `TryGetNextEntry` has two locations in the program: one through a GVM, and one through a constrained invocation on a struct. It appears that the constrained invocation is somehow taking the GVM path, causing an erroneous unbox node to appear that causes memory corruption.
 
project:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <IlcGenerateMstatFile>true</IlcGenerateMstatFile>
    <IlcGenerateDgmlFile>true</IlcGenerateDgmlFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serde" Version="0.6.0-preview6" />
  </ItemGroup>

</Project>
```

src:
```C#
Console.WriteLine("Hello, World!");

var sampleJson = """
{"latestVersion":{"version":"1.6.8","artifacts":{"linux-x64":"http://localhost:64922/dnvm/dnvm.tar.gz",
"osx-x64":"http://localhost:64922/dnvm/dnvm.tar.gz","win-x64":"http://localhost:64922/dnvm/dnvm.zip"}}}
""";

var release = JsonSerializer.Deserialize<DnvmReleases>(sampleJson);
Console.WriteLine(release);

[GenerateSerde]
public partial record struct DnvmReleases(DnvmReleases.Release LatestVersion)
{
    [GenerateSerde]
    public partial record struct Release(
        string Version,
        Dictionary<string, string> Artifacts);
}
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #99198.

### CODE REVIEW

**Comment by filipnavara** [comment]
Are there any more places that still use `MethodFlags.FunctionPointerIsUSG`?

**Comment by MichalStrehovsky** [comment]
> Are there any more places that still use `MethodFlags.FunctionPointerIsUSG`?

The AOT compiler. I haven't started ripping out USG support from it.

**Comment by filipnavara** [comment]
> The AOT compiler. I haven't started ripping out USG support from it.

A quick search shows that this PR removes all the remaining uses except for the one setting the flag (and the flag definition itself).

**Comment by agocke** [comment]
@davidwrighton When you get a chance could you take a look at this and see if this seems like the right fix for the problem?

File: src/tests/nativeaot/SmokeTests/UnitTests/Generics.cs [hunk 1]
```diff
@@ -3480,6 +3481,48 @@ public static void Run()
...
+            {
+                Cookie1 = 42;
+            }
+        }
+
+        class C<T> where T : IFoo
+        {
+            public static void Set(ref T t)
+            {
+                t.Do<T>();
```
Comment (davidwrighton) [inline src/tests/nativeaot/SmokeTests/UnitTests/Generics.cs:3508]: In general, looking at the fix, the only significant change I see is in `TypeBuilder.ParseNativeLayoutInfo` where we don't set the native function pointer on the non-template method in places where we used to do so, so I'd like to enhance this test to cover other cases where we might need to use the template.

Please update this test to make the Set method NoInline, as well as test the GVM pathway for invoking `Do<T>`.

``` csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public static void Set(ref T t, IFoo ifoo)
{
    t.Do<T>();
    ifoo.Do<T>();
}
```

Then in the Run method, please allocate an instance of the Foo<object> type (or any other canonically compatible type) where we create the `EEType` for the IFoo instance dynamically instead of having the compiler generate it. (You're probably more familiar with the shenanigans to make that happen than I am at this point).

Please also test the case of calling the `Do<T>` method directly through reflection Invoke instead of going through the `Set` method.

Also, please take an audit to see what other paths use template methods, and see if they need to be tested here too.

**Review by davidwrighton — APPROVED** [review]
