### PR TITLE
Improve S.DS.P tests, fix async API, and improve error messages

### LINKED ISSUE #46005: BeginSendRequest from  System.DirectoryServices.Protocols not working for receiving LDAP notifications
Having trouble using System.DirectoryServices.Protocols to receive LDAP notifications. See this code for best sample C# program online:

http://dunnry.com/blog/ImplementingChangeNotificationsInNET.aspx

This works fine in .NET Framework 4.72, but I am unable to get it working in any version of .NET Core, including .NET5, despite the fixes mentioned here:

https://github.com/dotnet/runtime/issues/36690

https://github.com/dotnet/runtime/issues/28470

@joperezr - any thoughts? I believe you were the last to look at this issue earlier this year.

### LINKED ISSUE #46021: LdapException messages on Unix do not include detail
Right now, many LdapException messages on Unix look like:
```
System.DirectoryServices.Protocols.LdapException: The LDAP server returned an unknown error.
    at System.DirectoryServices.Protocols.LdapConnection.BeginSendRequest(DirectoryRequest request, TimeSpan requestTimeout, PartialResultProcessing partialMode, AsyncCallback callback, Object state)
```

There is no way to tell from this message what the error was. For example in the case above say the ErrorCode was -7, then the exception message should include text like `The search filter is invalid.` .  As it is you need to run under the debugger to get it, then look up in ldap.h to translate it. Examples of bugs where the specific message would have helped: https://github.com/dotnet/runtime/issues/43621 https://github.com/dotnet/runtime/issues/41617 https://github.com/dotnet/runtime/issues/36947

Generally these codes are dictated by an RFC that all platforms follow. A subset are represented in our code, across two enums:

* ResultCode matches `LDAP_SUCCESS` through `LDAP_OTHER` in `LDAP_RETCODE` in Winldap.h (excepting `LDAP_IS_LEAF` and `LDAP_INVALID_CREDENTIALS`)
* LdapError matches `LDAP_IS_LEAF`, `LDAP_INVALID_CREDENTIALS`, and `LDAP_SERVER_DOWN` through `LDAP_REFERRAL_LIMIT_EXCEEDED` plus `LDAP_OPT_REFERRAL_CALLBACK` in `LDAP_RETCODE` in Winldap.h

I went through every one and they all match in name and value between Winldap.h and the Unix ones in ldap.h, except most of ResultCode have different values: `LDAP_SERVER_DOWN` through `LDAP_REFERRAL_LIMIT_EXCEEDED` have the values -1 through -17, whereas in Windows they have values 0x51-0x61

(There are various other codes on both sides that aren't represented in the enumerations, but presumably we'll spot those if they ever happen and extend the enum/add messages.)

The fix is simply to extract the `LdapError` enum into LdapError.Windows.cs and LdapError.Linux.cs with the appropriate values for the platform. We should append the error code in the case that there is no mapping (ie `The LDAP server returned an unknown error '{0}'.`)

<details>
  <summary>mappings required</summary>

For reference, here's the Unix values
```
#define LDAP_SERVER_DOWN				(-1)
#define LDAP_LOCAL_ERROR				(-2)
#define LDAP_ENCODING_ERROR				(-3)
#define LDAP_DECODING_ERROR				(-4)
#define LDAP_TIMEOUT					(-5)
#define LDAP_AUTH_UNKNOWN				(-6)
#define LDAP_FILTER_ERROR				(-7)
#define LDAP_USER_CANCELLED				(-8)
#define LDAP_PARAM_ERROR				(-9)
#define LDAP_NO_MEMORY					(-10)
#define LDAP_CONNECT_ERROR				(-11)
#define LDAP_NOT_SUPPORTED				(-12)
#define LDAP_CONTROL_NOT_FOUND			(-13)
#define LDAP_NO_RESULTS_RETURNED		(-14)
#define LDAP_MORE_RESULTS_TO_RETURN		(-15)	/* Obsolete */
#define LDAP_CLIENT_LOOP				(-16)
#define LDAP_REFERRAL_LIMIT_EXCEEDED	(-17)
```
and here's the Windows values
```
    LDAP_OTHER                      =   0x50,
    LDAP_SERVER_DOWN                =   0x51,
    LDAP_LOCAL_ERROR                =   0x52,
    LDAP_ENCODING_ERROR             =   0x53,
    LDAP_DECODING_ERROR             =   0x54,
    LDAP_TIMEOUT                    =   0x55,
    LDAP_AUTH_UNKNOWN               =   0x56,
    LDAP_FILTER_ERROR               =   0x57,
    LDAP_USER_CANCELLED             =   0x58,
    LDAP_PARAM_ERROR                =   0x59,
    LDAP_NO_MEMORY                  =   0x5a,
    LDAP_CONNECT_ERROR              =   0x5b,
    LDAP_NOT_SUPPORTED              =   0x5c,
    LDAP_NO_RESULTS_RETURNED        =   0x5e,
    LDAP_CONTROL_NOT_FOUND          =   0x5d,
    LDAP_MORE_RESULTS_TO_RETURN     =   0x5f,

    LDAP_CLIENT_LOOP                =   0x60,
    LDAP_REFERRAL_LIMIT_EXCEEDED    =   0x61
```
</details>

### PR DESCRIPTION
**Pull request by danmoseley**
Fixes https://github.com/dotnet/runtime/issues/46021
Fixes https://github.com/dotnet/runtime/issues/46005

Separated cleanly into commits.

1. Add the error message carried on the DirectoryResponse to the message in the DirectoryOperationException. See note below.
2. Tell server we want v3 protocol version before attempting to Bind. (We only support v3 anyway.) Without this change, the tests give 'protocol error' against slapd.
3. Fix the async API - the refactoring in #38161 removed an unused field, but had the side-effect of removing the place we start up the thread that services the async results list. Note there is already test coverage: this test now passes - we hadn't run these tests because they require server setup.
4. Improve test configuration system and replace rotted test instructions. It is now easy to test against two different OpenLDAP based servers using docker, as well as against an Active Directory DC. (I haven't investigated testing against an AD container - I set up a DC manually). This change also clarifies that the 'domain' in the configuration file refers to the root DN, which is not the same as the user domain for the AD user account.
5. Noted whether LDAP_OPT_SERVER_ERROR gives useful text, it does not, against any of the servers on either OS. As noted in #46021, there is a bug here because  this is a Windows-only LDAP option, and the other servers map the same value to LDAP_OPT_MATCHED_DN which is unrelated. I didn't fix that here; the fix would be to somehow determine the nature of the server. This text is not included in any exception messages, and I left it that way.
6. Fix the negative error codes noted in #46021. On servers based on openLDAP headers, some of the error codes are unexpectedly negative values, leading to numerous bug reports containing the exception message `The LDAP server returned an unknown error.`. Fortunately, Windows does not use negative codes; if the code is negative, pull it into the correct range. Now the error messages are meaningful.
7. Add a bunch of unit tests for various error cases to protect this fix and also validate other error codes. I used these to generate the messages below.
8. Where the error code is still unknown, which hopefully will no longer occur, include the error code in the exception message to help us diagnose it.
9. Note the ambiguity in LDAP_OPT mentioned above.

Ran all tests on Windows and all tests on Linux, each against each of the three servers, and all now pass. 

Note that one test is conditionalized on `IsActiveDirectoryServer`. This test will skip except on Windows->AD. It skips on Linux->AD because it uses the DirectoryEntry type to look for LDAP_CAP_ACTIVE_DIRECTORY_OID and DirectoryEntry does not exist on Linux (it's part of System.DirectoryServices.dll). I did not investigate whether there is another way to do this check that would work on Linux.

After this we should have a good foundation to investigate some of the other open issues in this area.

Note about (1) above. Including the error message from the response can make the exceptions more informative, at the expense of being ugly against some servers. Below are some examples, pulled from testing against each of the three servers. The first sentence (italicised) is what you get today. The rest comes from the appended response error text. Active Directory's text is particularly ugly. However I have found some of these and others helpful when figuring out why a request is failing. If users don't show these messages to their users, the extra text might be fine. If they do, I could make it debug-only, but they would have to swap our our dll in order to get better messages. Other options are an environment variable, and simply putting it on a second line. I think I am leaning towards opting in with an environment variable - if that sounds reasonable I'll push that change.

#### Active Directory

*The distinguished name contains invalid syntax.* 0000208F: NameErr: DSID-0310022E, problem 2006 (BAD_NAME), data 8350, best match of:
        '==invaliddn=='

*The server does not support the control.* The control is critical. 00000057: LdapErr: DSID-0C090B26, comment: Error processing control, data 0, v4563

*The object does not exist.* 0000208D: NameErr: DSID-03100288, problem 2001 (NO_OBJECT), data 0, best match of:
        'DC=danmose-ldap,DC=com'

*The attribute exists or the value has been assigned.* 00002083: AtrErr: DSID-031519F7, 1:
        0: 00002083: DSID-031519F7, problem 1006 (ATT_OR_VALUE_EXISTS), data 0, Att d (description):len 34

*The attribute exists or the value has been assigned.* 00002083: AtrErr: DSID-031519F7, 2:
        0: 00002083: DSID-031519F7, problem 1006 (ATT_OR_VALUE_EXISTS), data 0, Att d (description):len 26
        1: 00002083: DSID-031519F7, problem 1006 (ATT_OR_VALUE_EXISTS), data 0, Att 10 (postalAddress):len 60

*An operation error occurred*. 000004DC: LdapErr: DSID-0C091080, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563

#### OpenDJ

*The distinguished name contains invalid syntax.* The provided value "==invaliddn==" could not be parsed as a valid distinguished name because character '=' at position 0 is not allowed in an attribute name
*The server does not support the control.* The control is critical. The search request cannot be processed because it contains a critical control with OID ==invalid-control== that is not supported by the Directory Server for this type of operation
*The object does not exist.* Entry cn=protocolUser7.1,ou=ProtocolsGroup7.1,DC=example,DC=com does not exist in the Directory Server
*The attribute exists or the value has been assigned.* Entry ou=ProtocolsGroup3,DC=example,DC=com cannot be modified because it would have resulted in one or more duplicate values for attribute description: Protocols Group 3

#### SlapD

*The distinguished name contains invalid syntax.* invalid DN
*The server does not support the control.* The control is critical. critical extension is not recognized
*The object does not exist.*
*The attribute exists or the value has been assigned.* modify/add: postalAddress: value \#0 already exists

### CODE REVIEW

**Comment by danmosemsft** [comment]
I only tested basic auth.

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/common/DirectoryException.cs [hunk 1]
```diff
@@ -38,22 +39,37 @@ public class DirectoryOperationException : DirectoryException, ISerializable
...
+        {
+            var sb = new StringBuilder();
+            sb.Append(message ?? SR.DefaultOperationsError);
+            if (!string.IsNullOrEmpty(response?.ErrorMessage))
+            {
+                sb.Append(' ');
+                sb.Append(response.ErrorMessage);
+            }
+            return sb.ToString();
+        }
```
Comment (stephentoub) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/common/DirectoryException.cs:72]: This doesn't need a string builder (not that perf matters here, but that'll actually be worse).  It can instead be the simpler:
```C#
string result = message ?? SR.DefaultOperationsError;
if (!string.IsNullOrEmpty(response?.ErrorMessage))
{
    result += " " + response.ErrorMessage;
}
return result;
```

Comment (danmosemsft) [reply src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/common/DirectoryException.cs:72]: Ah leftovers from appending the server error.

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs [hunk 2]
```diff
@@ -43,6 +43,9 @@ internal enum LdapResult
         private static readonly LdapPartialResultsProcessor s_partialResultsProcessor = new LdapPartialResultsProcessor(s_waitHandle);
 
         private AuthType _connectionAuthType = AuthType.Negotiate;
+#pragma warning disable CA1823 // this constructor must run; it starts a thread
+        private static readonly PartialResultsRetriever s_retriever = new PartialResultsRetriever(s_waitHandle, s_partialResultsProcessor);
```
Comment (stephentoub) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs:47]: Seems like this should be part of the LdapPartialResultsProcessor ctor instead.

File: src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs [hunk 3]
```diff
@@ -110,7 +118,14 @@ internal static LdapConfiguration GetConfiguration(string configFile)
 
                     child = config.Element("Password");
                     if (child != null)
-                        password = child.Value;
+                    {
+                        string val = child.Value;
+                        if (val.StartsWith("%") && val.EndsWith("%"))
```
Comment (tarekgh) [inline src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs:123]: nit: use '%' instead of "%"

Comment (tarekgh) [inline src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs:123]: I believe you need to check for the string length here be greater than 1.

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapException.cs [hunk 4]
```diff
@@ -56,17 +60,38 @@ internal class LdapErrorMappings
             { LdapError.SendTimeOut, SR.LDAP_SEND_TIMEOUT }
         };
 
+        internal static int NormalizeResultCode(int errorCode)
+        {
+            // OpenLDAP codes -1 to -17 should map to 81 to 97 respectively;
+            // See note above.
+            return errorCode < 0 ? 80 - errorCode : errorCode;
```
Comment (tarekgh) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapException.cs:67]: should we check the error code is really between -1 and -17 here?

File: src/libraries/System.DirectoryServices.Protocols/tests/DirectoryServicesProtocolsTests.cs [hunk 5]
```diff
@@ -570,8 +570,11 @@ private LdapConnection GetConnection()
                 AuthType = AuthType.Basic
             };
 
-            connection.Bind();
+            // Set server protocol before bind; OpenLDAP servers default
+            // to LDAP v2, which we do not support, and will return LDAP_PROTOCOL_ERROR
             connection.SessionOptions.ProtocolVersion = 3;
```
Comment (joperezr) [inline src/libraries/System.DirectoryServices.Protocols/tests/DirectoryServicesProtocolsTests.cs:632]: I wonder if we should default to version 3 when creating the LdapConnection object since that will be what you want more than 90% of the time. I saw other libraries do default to 3 as well, for example: [https://github.com/flamencist/ldap4net/blob/41a6397d6ad2c3cbaad65aa39b637dfc81ffac49/LdapForNet/ILdapConnection.cs#L13](https://github.com/flamencist/ldap4net/blob/41a6397d6ad2c3cbaad65aa39b637dfc81ffac49/LdapForNet/ILdapConnection.cs#L13)

File: src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs (hunk 3 above)
Comment (danmosemsft) [reply src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs:123]: This builds against .NET Framework or I would..

**Review by tarekgh — APPROVED** [review]
added a minor comments/questions. LGTM otherwise

File: src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapSessionOptions.cs [hunk 6]
```diff
@@ -524,6 +524,7 @@ public VerifyServerCertificateCallback VerifyServerCertificate
             }
         }
 
+        // In practice, this apparently rarely if ever contains useful text
```
Comment (joperezr) [inline src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapSessionOptions.cs:527]: Not that you need to fix it here, but LdapSessionOptions currently has a split implementation between Linux and Windows, so if the server error is retrieved with different options, we can move the implementation of this internal string to the RID-specific files and use the right option on each case.

**Review by joperezr — APPROVED** [review]
Thanks a bunch for fixing all these error handling and for the added coverage!

**Comment by danmosemsft** [comment]
I want to get the S.DS.AM and S.DS tests working against these servers too.

File: src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs (hunk 3 above)
Comment (danmosemsft) [reply src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs:123]: "".StartsWith("%") just returns false.

**Comment by joperezr** [comment]
I'll check again to confirm, but IIRC S.DS.AM is Active Directory specific, and S.DS could work with some non-AD ldap servers but not all. Last time I checked, S.DS.P was the library that worked with most ldap servers since it really just is a thin layer of c# on top of two different native libraries which simply implement the ldap protocol.

**Comment by danmoseley** [comment]
Still working on getting a setup for S.DS and S.DS.AM tests to pass against AD...

**Comment by danmoseley** [comment]
closing for now , will reopen.

**Comment by joperezr** [comment]
@danmoseley given that this PR was only targeting S.DS.P, I think there is value in merging this and then subsequently make the required modifications for the other two libraries. Would you consider reopening and merging this as-is and then figure out the other two libraries? Maybe I'm just missing something but I don't feel this PR to be "incomplete"

**Comment by danmoseley** [comment]
In my previous attempts, I was running the tests from a machine joined to corp domain. Instead I set up a 2nd VM as the test machine, added the test DC as a DNS server, joined the test machine to the test domain, and logged in as the user on the test domain. After doing this, I have all the S.DS.P and S.DS.AM tests passing against AD. There are a few failures left in S.DS tests:

1. TestInvalidSearchFilter (which passes a bad password) and TestInvalidUserAndPassword expect a DirectoryServicesCOMException but are getting a COMException. this is because AdGetLastError is returning no error after the failed bind. I do not know why. The same failure occurs when I run the tests on .NET Framework, so it's a configuration or test issue.
2. TestMissingUserAndPasswordInfo expects to get an exception when enumerating the directory, but it does not.  As far as I can tell it is not a matter of the AD server enabling anonymous access. Again, same on .NET Framework.
3. TestComInterfaces fails because it expects the security descriptor of a new OU it creates to correspond to the user it's bound as but instead it's BUILTIN. This does not occur on .NET Framework. I do not know why.

That's from Windows against AD. All the tests of all libraries pass against the non AD servers, from Windows and Linux. I will try Linux against AD from S.DS and S.DS.AM now.

**Comment by danmoseley** [comment]
I think this should be ready to merge now though.

**Comment by danmoseley** [comment]
Unless I hear otherwise, I plan to leave the "extended" exception strings shown above enabled. They're ugly, but we have evidence how tricky it can be to diagnose why some of these exceptions appear, and they will sometimes help. We can see whether we get preview feedback.

**Comment by danmoseley** [comment]
So everything is tested again except S.DS.P on Linux to AD. This was working before, but something changed as I now get `In order to perform this operation a successful bind must be completed on the connection`. I verified a bind did occur successfully.

I don't think I changed anything, so I'm at a loss right now.

**Comment by danmoseley** [comment]
Next step may be trying the same thing with ldap4net on Linux.

**Comment by danmoseley** [comment]
@joperezr I am out of ideas for how to get the tests working from Linux to AD. I still get `In order to perform this operation a successful bind must be completed on the connection`. This is what I have tried

* Running tests in WSL2 on a new test VM not domain joined, rather than WSL2 on my dev box, same result
* debugged through our code to ensure the bind is happening
* wrote a minimal test that just does bind, search, same result
* ip address instead of server name, same result
 * various tracing settings on the AD server didn't show anything helpful.
* ldapsearch _does_ work. built ldapsearch and enabled packet tracing - nothing stands out except it uses `ldap_sasl_bind( ld, binddn, LDAP_SASL_SIMPLE...` for the bind wheras we use `ldap_simple_bind_s` - which seemed potentially interesting, but, ldap4net has a mode that does the former, and it still fails.
* different user instead of admin. no difference
* double check user/password - they are good, if I change either, it will fail with bad credentials
* port 3268 - this is the general catalog port - it works! but this is a read only port.

It is definitely not an issue with my changes -
* test program using ldap4net has the same problem - it doesn't use any of our S.DS.* code.
* master branch has the same problem (ie without my changes)
* with my branch 100% pass against both slapd and opendj servers (they only fail against AD from Linux)
* with my branch 100% pass against slapd, opendj, and AD when run on Windows

At this point I'm out of ideas short of attaching a kernel debugger to the AD server, which really is out of my depth.

Given it is definitely not something I've introduced, and coverage on all the other combinations works including AD from Windows, I believe we should commit this as is. It's clearly important that we test AD from Linux before we ship, but it seems like I can't solve that right now unless @tquerec sees something obvious that I'm missing.

What do you think?

**Comment by danmoseley** [comment]
cc @tarekgh

File: src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs [hunk 7]
```diff
@@ -77,77 +80,95 @@ internal bool IsActiveDirectoryServer
         internal static LdapConfiguration GetConfiguration(string configFile)
         {
             if (!File.Exists(configFile))
+                Environment.FailFast("LDAP test configuration file not found: " + configFile);
```
Comment (tarekgh) [inline src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs:83]: > Environment.FailFast("LDAP test c [](start = 15, length = 34)

Why we fail fast the tests when there is no provided configuration file. Sorry if I missed in earlier comments but will try to read the whole thread.

**Review by tarekgh — APPROVED** [review]
LGTM. Thanks for the cleaning up and have more reliable testing with the configuration. 

I left one question regarding `Fail Fast` which is not clear to me yet why we are doing that?

File: src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs (hunk 7 above)
Comment (danmoseley) [reply src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs:83]: The config file is copied by the build: it should always be present. I had an error earlier where it wasn't, and the tests don't fail, just skip, which is less obvious. I can revert that if you want but I figured it was helpful

Comment (tarekgh) [reply src/libraries/Common/tests/System/DirectoryServices/LdapConfiguration.cs:83]: I am fine with what you have. Let's see how it'll goes.

**Comment by danmoseley** [comment]
Thanks both. At some point before we ship please let's remember to be sure to run these tests again and get Linux-to-AD passing.🙂

I wonder whether we should maintain and check in a list of all manual testing activities. Eg @eiriktsarpalis  has some manual console tests, and there are others that are easy to forget about.

**Comment by danmoseley** [comment]
It occurs to me that one avenue of investigation could be to change our API calls to match ldapsearch, which works, and then bisect. I'm done with this for now though.

**Comment by tarekgh** [comment]
@danmoseley should we have a sign off release sheet to list all things should be done before every release?

**Comment by danmoseley** [comment]
Sure, might be a good idea, but even just manual tests was all I was thinking of. Perhaps someone is interested on looking into that a bit more.
