### PR TITLE
JIT: Fix GenTreeCall::Equals for virtual vs static calls

### LINKED ISSUE #77710: [libraries-pgo arm32/x86] Failure in System.Threading.Tasks.Tests.AggregateExceptionTests.Flatten
Work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=67378&view=ms.vss-test-web.build-test-results-tab&runId=1372088&resultId=148625&paneView=debug
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5f5da2462e484cb28f/System.Threading.Tasks.Tests/1/console.5c26a5b6.log?helixlogtype=result

```scala
    System.Threading.Tasks.Tests.AggregateExceptionTests.Flatten [FAIL]
      Assert.Equal() Failure
                                   ↓ (pos 19)
      Expected: message (A) (B) (C)
      Actual:   message (A) (B) (C) (A) (B) (C)
                                   ↑ (pos 19)
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #77710

### CODE REVIEW

**Comment by jakobbotsch** [comment]
I'll add a test here.

File: src/tests/JIT/Regression/JitBlue/Runtime_77710/Runtime_77710.cs [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+            if (callBase)
+            {
+                base.M(false, true);
+            }
+            else
+            {
+                M(false, true);
+            }
+
+            return 0;
```
Comment (jakobbotsch) [inline src/tests/JIT/Regression/JitBlue/Runtime_77710/Runtime_77710.cs:71]: @AndyAyersMS is it expected that tail merging does not kick in without this extra successor block? For
```csharp
        [MethodImpl(MethodImplOptions.NoInlining)]
        public override void M(bool callBase, bool recursing)
        {
            if (recursing)
            {
                DerivedCalls++;
                return;
            }

            if (callBase)
            {
                base.M(false, true);
            }
            else
            {
                M(false, true);
            }
         }
```

tail merging was not kicking in.

Comment (AndyAyersMS) [reply src/tests/JIT/Regression/JitBlue/Runtime_77710/Runtime_77710.cs:76]: I wonder if the tail call -> loop stuff runs even if the method is marked `NoInlining`?

**Review by AndyAyersMS — APPROVED** [review]

File: src/tests/JIT/Regression/JitBlue/Runtime_77710/Runtime_77710.cs (hunk 1 above)
Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_77710/Runtime_77710.cs:76]: I don't think it's related to that, the IR looks like something we should be able to tail merge (assuming this bug isn't fixed). Here's the relevant jitdump, taken with a build before this fix. I would've expected to see tail merging.
```scala
*************** Finishing PHASE Compute preds
Trees after Compute preds

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..003)-> BB03 ( cond )                     i 
BB02 [0001]  1       BB01                  1       [003..010)        (return)                     i 
BB03 [0002]  1       BB01                  1       [010..013)-> BB05 ( cond )                     i 
BB04 [0003]  1       BB03                  1       [013..01C)        (return)                     i 
BB05 [0004]  1       BB03                  1       [01C..025)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------

------------ BB01 [000..003) -> BB03 (cond), preds={} succs={BB02,BB03}

***** BB01
STMT00000 ( 0x000[E-] ... 0x001 )
               [000003] -----------                         ▌  JTRUE     void  
               [000002] -----------                         └──▌  EQ        int   
               [000000] -----------                            ├──▌  LCL_VAR   bool   V02 arg2         
               [000001] -----------                            └──▌  CNS_INT   int    0

------------ BB02 [003..010) (return), preds={BB01} succs={}

***** BB02
STMT00006 ( 0x003[E-] ... 0x00A )
               [000022] -A--G------                         ▌  ASG       int   
               [000021] ----G--N---                         ├──▌  FIELD     int    DerivedCalls
               [000020] ----G------                         └──▌  ADD       int   
               [000018] ----G------                            ├──▌  FIELD     int    DerivedCalls
               [000019] -----------                            └──▌  CNS_INT   int    1

***** BB02
STMT00007 ( 0x00F[E-] ... 0x00F )
               [000023] -----------                         ▌  RETURN    void  

------------ BB03 [010..013) -> BB05 (cond), preds={BB01} succs={BB04,BB05}

***** BB03
STMT00001 ( 0x010[E-] ... 0x011 )
               [000007] -----------                         ▌  JTRUE     void  
               [000006] -----------                         └──▌  EQ        int   
               [000004] -----------                            ├──▌  LCL_VAR   bool   V01 arg1         
               [000005] -----------                            └──▌  CNS_INT   int    0

------------ BB04 [013..01C) (return), preds={BB03} succs={}

***** BB04
STMT00004 ( 0x013[E-] ... 0x01B )
               [000016] --C-G------                         ▌  CALL      void   Base.M
               [000013] ----------- this                    ├──▌  LCL_VAR   ref    V00 this         
               [000014] ----------- arg1                    ├──▌  CNS_INT   int    0
               [000015] ----------- arg2                    └──▌  CNS_INT   int    1

***** BB04
STMT00005 ( 0x01B[E-] ... ??? )
               [000017] -----------                         ▌  RETURN    void  

------------ BB05 [01C..025) (return), preds={BB03} succs={}

***** BB05
STMT00002 ( 0x01C[E-] ... 0x024 )
               [000011] --C-G------                         ▌  CALLV vt-ind void   Base.M
               [000008] ----------- this                    ├──▌  LCL_VAR   ref    V00 this         
               [000009] ----------- arg1                    ├──▌  CNS_INT   int    0
               [000010] ----------- arg2                    └──▌  CNS_INT   int    1

***** BB05
STMT00003 ( 0x024[E-] ... ??? )
               [000012] -----------                         ▌  RETURN    void  

-------------------------------------------------------------------------------------------------------------------

*************** Starting PHASE Tail merge

*************** Finishing PHASE Tail merge [no changes]
```

Comment (AndyAyersMS) [reply src/tests/JIT/Regression/JitBlue/Runtime_77710/Runtime_77710.cs:76]: The algorithm looks for common predecessor sequences so it nees some sort of join point to get started.

There is no successor block for those returns, so no merging happens. I suppose we could treat all the `BBJ_RETURNs` as if they all had a common successor. Shouldn't be too hard to do...

Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_77710/Runtime_77710.cs:76]: I see. Yeah, this might be a pretty common case where tail merging would kick in.
