### PR TITLE
Fix unloadability issue

### LINKED ISSUE #116953: Access Violation Exception During AssemblyLoadContext Unloading
### Description

During the unloading process of an AssemblyLoadContext, coreclr attempts to release a GCHandle but accesses an empty handle value, resulting in an access violation exception. This issue occurs when multiple interdependent AssemblyLoadContexts are being unloaded, particularly when they are processed in a specific order. The root cause is that LoaderAllocator attempts to access an already collected DomainAssembly pointer a second time.

Image

Image

## Steps to Reproduce
1. Create three ALCs named ALC_A, ALC_B, and ALC_C
2. Create three assemblies: AssemblyA, AssemblyB, and AssemblyC, each loaded in their corresponding ALC
3. Configure AssemblyB to depend on both AssemblyA and AssemblyC
4. Call a method in AssemblyB
5. Unload all three ALCs
6. Repeat the above steps multiple times - the access violation exception will occur occasionally

### Reproduction Code:
1.Test code:
```csharp
    // ALC For AssemblyB
    public class AssemblyLoadContextB : AssemblyLoadContext
    {
        public AssemblyLoadContextB(string name, bool isCollectible) : base(name, isCollectible)
        {
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            if (assemblyName.Name == "AssemblyC")
            {
                UELog.Log($"AssemblyB is resolving C");
                return AssemblyLoadContextTest.AssemblyC;
            }

            if (assemblyName.Name == "AssemblyA")
            {
                UELog.Log($"AssemblyB is resolving A");
                return AssemblyLoadContextTest.AssemblyA;
            }

            return null;
        }
    }

    class AssemblyLoadContextTest
    {
        public static Assembly AssemblyA;
        public static Assembly AssemblyC;

        public static void Run()
        {
            for (int i = 0; i < 10; i++)
            {
                UELog.Log($"Test #{i}");
                RunOneTest();
            }
        }

        private static void RunOneTest()
        {
            // Create three collectible ALCs
            var alcB = new AssemblyLoadContextB("ALC_B", isCollectible: true);
            var alcC = new AssemblyLoadContext("ALC_C", isCollectible: true);
            var alcA = new AssemblyLoadContext("ALC_A", isCollectible: true);

            // Track ALCs with weak references
            WeakReference alcCRef = new WeakReference(alcC, trackResurrection: true);
            WeakReference alcBRef = new WeakReference(alcB, trackResurrection: true);
            WeakReference alcARef = new WeakReference(alcA, trackResurrection: true);

            // Load assembly A
            AssemblyA = PluginInitiator.LoadAssembly(alcA, "AssemblyA");

            // Load assembly C
            AssemblyC = PluginInitiator.LoadAssembly(alcC, "AssemblyC");

            // Load assembly B (depends on assemblies A and C)
            Assembly assemblyB = PluginInitiator.LoadAssembly(alcB, "AssemblyB");

            // Call method in assembly B
            UELog.Log("\nTesting call to method in assembly B:");
            Type? typeBClass = assemblyB.GetType("AssemblyB.ClassB");
            if (typeBClass != null)
            {
                object bInstance = Activator.CreateInstance(typeBClass)!;
                string resultB = (string)typeBClass.GetMethod("GetMessage").Invoke(bInstance, null);
                UELog.Log($"B method returns: {resultB}");
            }

            AssemblyA = null;
            AssemblyC = null;

            // Unload the three ALCs
            UELog.Log("\nStarting to unload ALCs...");

            alcA.Unload();
            alcC.Unload();
            alcB.Unload();

            alcA = null;
            alcB = null;
            alcC = null;

            for (int i = 0; i < 100 &&
                (alcARef.IsAlive || alcBRef.IsAlive || alcCRef.IsAlive); i++)
            {
                Thread.Sleep(1);
                UELog.Log("Running GC...");
                GC.Collect();
                GC.WaitForPendingFinalizers();
            }

            UELog.Log($"ALC_A status: {(alcARef.IsAlive ? "still in memory" : "unloaded")}");
            UELog.Log($"ALC_B status: {(alcBRef.IsAlive ? "still in memory" : "unloaded")}");
            UELog.Log($"ALC_C status: {(alcCRef.IsAlive ? "still in memory" : "unloaded")}");

            UELog.Log("Test completed");
        }
    }
```

2.Code for AssemblyA:
```csharp
namespace AssemblyA;

public class ClassA
{
}
```

3.Code for AssemblyB:
```csharp
using AssemblyC;

namespace AssemblyB;

public class ClassB
{
    public string GetMessage()
    {
        var b = new GenericClass<AssemblyA.ClassA>();
        var c = new ClassC();
        return $"Hello from Assembly B! -> {c.GetMessage()} -> {b.ToString()}";
    }
}

public class GenericClass<T>
{
}
```

4.Code for AssemblyC:
```csharp
namespace AssemblyC;

public class ClassC
{
    public string GetMessage()
    {
        return "Hello from Assembly C!";
    }
}
```

### Expected behavior

The AssemblyLoadContext should unload correctly without errors, regardless of dependencies and processing order.

### Actual behavior

During the unloading process of an AssemblyLoadContext, there may be an access violation exception.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

- .NET version: 9.0.5
- Operating System: Windows 11
- Architecture: x64

## Root Cause Analysis
1. When ALCs unload, `LoaderAllocator_Destroy`(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L638) is called for their corresponding LoaderAllocator (LA)
2. The issue occurs specifically when LA_B is processed first, followed by LA_C, then LA_A
3. When LoaderAllocator_Destroy processes LA_B:
    1. It iterates through `m_LoaderAllocatorReferences`, `decrements m_cReferences`(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L186) for both LA_A and LA_C to 1(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L684)
    2. It decrements its own m_cReferences value(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L692)
    3. Since its m_cReferences is not zero, LoaderAllocator::GCLoaderAllocators is not called(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L698)

4. When LoaderAllocator_Destroy processes LA_C:
    1. It decrements its own m_cReferences value
    2. With m_cReferences now at zero, it calls LoaderAllocator::GCLoaderAllocators
    3. GCLoaderAllocators_RemoveAssemblies returns null and fails to remove the DomainAssembly* for AssemblyC from the AppDomain(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L520)
        - The reason for not collecting the DestroyedLoaderAllocator:
            - When iterating to AssemblyA, the Mark operation for live LoaderAllocators also marks LA_C(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L406)
            - When later processing LA_C, it doesn't execute the !IsAlive() related logic(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L430)
        - Without collecting DestroyedLoaderAllocator, the corresponding DomainAssembly* is not removed(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L476)
    4. LoaderAllocator::GCLoaderAllocators continues by releasing the LongWeakHandle (ReleaseManagedAssemblyLoadContext) and delete DomainAssembly*
        After delete DomainAssembly*, the DomainAssembly* cached in AppDomain becomes a dangling pointer
(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L569)
(https://github.com/dotnet/runtime/blob/e36e4d1a8f8dfb08d7e3a6041459c9791d732c01/src/coreclr/vm/loaderallocator.cpp#L576)

5. When LoaderAllocator_Destroy processes LA_A:
    1. It decrements its own m_cReferences value
    2. With m_cReferences now at zero, it calls LoaderAllocator::GCLoaderAllocators
    3. In GCLoaderAllocators_RemoveAssemblies, it encounters the dangling pointer from the previous step, possibly retrieving LA_C associated with the already collected DomainAssembly*, and records LA_C in m_pLoaderAllocatorDestroyNext
    4. When iterating through DestroyedLoaderAllocators in LoaderAllocator::GCLoaderAllocators, it performs a second Release operation on LA_C (ReleaseManagedAssemblyLoadContext), resulting in accessing a null pointer

### PR DESCRIPTION
**Pull request by davidwrighton**
There is a rare case when attempt to unload an assembly load context in multi-assembly load context scenario leads to access violation in the runtime.

The crash is caused by a DomainAssembly pointer in the AppDomain assembly list not being removed while the DomainAssembly was deleted. The fix is to defer deletion of the DomainAssembly until after all dependencies on the LoaderAllocator have notified the runtime that they are freed. Notably, the fix is to adjust a bit of logic where we were forcing the original LoaderAllocator to be cleaned up even if it wasn't found as free-able during the GCLoaderAllocator's logic. That needed to exist to handle the case of a LoaderAllocator without any associated DomainAssembly objects, but we can special case that specific scenario.

There is a detailed analysis in the https://github.com/dotnet/runtime/issues/116953.

This change fixes it and adds a regression test that is a repro app provided in the issue converted to coreclr test.

Close https://github.com/dotnet/runtime/issues/116953

### CODE REVIEW

File: src/coreclr/vm/loaderallocator.hpp [hunk 1]
```diff
@@ -229,9 +229,17 @@ class LoaderAllocatorID
     LoaderAllocatorID(LoaderAllocatorType laType=LAT_Invalid, VOID* value = 0)
     {
         m_type = laType;
-        m_pValue = value;
+        m_pValue = 0;
```
[the remark this answers is not in the document]
Comment (janvorli) [reply src/coreclr/vm/loaderallocator.hpp]: I also wonder what was the purpose of this change.

File: src/coreclr/vm/loaderallocator.cpp [hunk 2]
```diff
@@ -550,10 +570,13 @@ void LoaderAllocator::GCLoaderAllocators(LoaderAllocator* pOriginalLoaderAllocat
         pDomainLoaderAllocatorDestroyIterator = pDomainLoaderAllocatorDestroyIterator->m_pLoaderAllocatorDestroyNext;
     }
 
-    // If the original LoaderAllocator was not processed, it is most likely a LoaderAllocator without any loaded DomainAssembly
+    // If the original LoaderAllocator was not processed, it is a LoaderAllocator without any loaded DomainAssembly
     // But we still want to collect it so we add it to the list of LoaderAllocator to destroy
-    if (!isOriginalLoaderAllocatorFound && !pOriginalLoaderAllocator->IsAlive())
+    if (!isOriginalLoaderAllocatorFound && !pOriginalLoaderAllocator->Id()->HasAttachedDynamicAssemblies() && !pOriginalLoaderAllocator->IsAlive())
```
Comment (janvorli) [inline src/coreclr/vm/loaderallocator.cpp:575]: When does the original loader allocator get destroyed when it has some attached dynamic assemblies?

Comment (davidwrighton) [reply src/coreclr/vm/loaderallocator.cpp:575]: It gets destroyed in a future call to destroy when there are no longer any paths through the LoaderAllocator graph to find the LoaderAllocator. This in fact is the entire purpose of the GC system, and why it isn't just reference counting. Consider the case of 

LoaderAllocators A -> B -> C -> A.   The arrows represent the dependency relationships. Now, when looking at reference counts, we only increment the count on each assembly by 1 for the dependencies and the circular dependency isn't track in the reference count at all. Also, the cleanup path in CoreCLR isn't clean where if one of these is destroyed, its safe to begin the destruction process later. Mind you, it looks like we haven't been testing this situation since collectible assemblies were backported back into CoreCLR, so that's exciting.

What we do with the GC is ensure that we don't actually start cleaning any of these things up until ALL have received their LoaderAllocator::Destroy calls. So we will get 3 calls to LoaderAllocator::Destroy, 1 for each LoaderAllocator, and this change will ensure we only cleanup the LoaderAllocators when all 3 calls have been made.

Comment (janvorli) [reply src/coreclr/vm/loaderallocator.cpp:575]: Ok, but if the `LoaderAllocator::Destroy`, that is called from the `LoaderAllocatorScout` finalizer, calls `LoaderAllocator::GCLoaderAllocators`, then if the loader allocator is not destroyed due to the condition you have added, we won't get any other call to `LoaderAllocator::Destroy` for that loader allocator, as the `LoaderAllocatorScout` is not re-registered for finalization in this case. So it is not clear to me how we get to destroying that `LoaderAllocator` later.

Comment (davidwrighton) [reply src/coreclr/vm/loaderallocator.cpp:575]: Correct, we don't re-run the LoaderAllocator::Destroy, but we will build a list of which loader allocators to really clean up,  so we don't need to actually re-run it. The critical parts end up getting run later through the GC process. What parts of LoaderAllocator::Destroy are you interested in?

Comment (janvorli) [reply src/coreclr/vm/loaderallocator.cpp:575]: I am curious about all the cleanup that happens in the last loop in the GCLoaderAllocators, e.g.
```
        pDomainLoaderAllocatorDestroyIterator->ReleaseManagedAssemblyLoadContext();

        pDomainLoaderAllocatorDestroyIterator->CleanupDependentHandlesToNativeObjects();

        ExecutionManager::Unload(pDomainLoaderAllocatorDestroyIterator);

        pDomainLoaderAllocatorDestroyIterator->UninitVirtualCallStubManager();
```

I don't see these being called from anywhere else, so if we don't add the pOriginalLoaderAllocator to the "pFirstDestroyedLoaderAllocator" list, then these will never be called for that one.

Comment (davidwrighton) [reply src/coreclr/vm/loaderallocator.cpp:575]: When the original loader allocator isn't freed as part of the `LoaderAllocator::Destroy` call, it will get freed on a subsequent call to `LoaderAllocator::Destroy`. In that case the `pDomainLoaderAllocatorDestroyIterator` variable will end up pointing to a linked list with multiple `LoaderAllocator`'s in it.

Imagine a `LoaderAllocator` dependency chain which is circular.

A->B->A

Since the Destroy always happens on the finalization thread, we necessarily always call one of them before the other. So, either A or B will get called first. (There is NO way to reliably predict the order of calls to `LoaderAllocator::Destroy`.). But the idea is that the loop at the bottom with the `pDomainLoaderAllocatorDestroyIterator` variable will be empty for the first call, and have both A and B in it for the second call, thus the second loop will continue to call the api's you are concerned about for both assemblies A and B, but it will call all of them on the second call to `LoaderAllocator::Destroy`.

Comment (janvorli) [reply src/coreclr/vm/loaderallocator.cpp:575]: I think I understand it now. The thing that I was missing was the fact that the `LoaderAllocatorID` keeps a linked list of `DomainAssembly` instances that only grows and never shrinks. So once any assembly is loaded into the related ALC, from that point on, the `LoaderAllocator` will always be reachable via those `DomainAssembly` instances even after the `LoaderAllocator::Destroy` that doesn't end up destroying that `LoaderAllocator`.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by srxqds** [comment]
backport to release/10.0 and release/9.0 ？
