### PR TITLE
Make longjmp over managed frames work

### LINKED ISSUE #111242: SEHException with new Exception behavior in .NET 9
### Description

Starting in .NET 9, pinvoking Lua's [`luaL_error`](https://www.lua.org/source/5.4/lauxlib.c.html#luaL_error) can raise a `SEHException`.

I believe this is due to `luaL_error` being a relatively thin wrapper over `longjmp`.

I narrowed this down to the newly defaulted on improved exception handling in .NET 9.

Note that while I use [KeraLua](https://github.com/NLua/KeraLua) in my repro, the same thing happens if you pinvoke Lua directly - KeraLua is just a convenient way to package up a pre-built Lua 5.4 binary, and eliminate some of my own pinvoke definition from the repro.

### Reproduction Steps

`csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KeraLua" Version="1.4.1" />
  </ItemGroup>

</Project>
```

`Program.cs`
```csharp
using KeraLua;

namespace LongJumpRepro
{
    public class Program
    {
        private const string ErrorMsg = "!!RAISED!!";

        private static Lua? lua;

        public static void Main(string[] args)
        {
            // This works as expected in .NET 8
            // It raises a SEHException in .NET 9
            // The exception in .NET 9 goes away if you set environment variable DOTNET_LegacyExceptionHandling=1

            Console.WriteLine($".NET version: {Environment.Version}");
            Console.WriteLine($"DOTNET_LegacyExceptionHandling: {Environment.GetEnvironmentVariable("DOTNET_LegacyExceptionHandling")}");

            try
            {
                lua = new Lua();
                lua.PushCFunction(RaiseLuaError);
                var status = lua.PCall(0, 0, 0);
                Console.WriteLine($"Status (Expected {LuaStatus.ErrRun}): {status}");

                var errMsg = lua.CheckString(1);
                Console.WriteLine($"Error Message (Expected '{ErrorMsg}'): {ErrorMsg}");
            }
            finally
            {
                lua?.Dispose();
            }
        }

        private static int RaiseLuaError(nint luaState)
        => lua!.Error(ErrorMsg);
    }
}
```

### Expected behavior

Expected behavior is either the .NET 8:
Image
or .NET 9 with DOTNET_LegacyExceptionHandling=1 behavior:
Image

Where `luaL_error` works when pinvoked.

### Actual behavior

A `SEHException` is raised:
Image

### Regression?

Yes, this worked in earlier versions of .NET.  I have confirmed it worked in .NET 8, and this was reported when first running the code on .NET 9.

### Known Workarounds

Setting DOTNET_LegacyExceptionHandling=1 fixes the issue in .NET 9.

Discussion on [the PR that introduced](https://github.com/dotnet/runtime/pull/98570) it suggests it is temporary however, if it is removed in a later .NET release we will no longer have a workaround.

### Configuration

 - .NET 8 and .NET 9
 - Windows 11
 - x64
 - I have not tested on other configurations
 - I am not using Blazor

### Other information

While I admit longjmp is weird, embedding Lua is pretty popular.

### PR DESCRIPTION
**Pull request by janvorli**
The new exception handling has broken hosting Lua on Windows when a Lua code throws an exception that ends up crossing managed frames. Lua uses longjmp for its exception handling mechanism and the new exception handling reported the longjmp as an unhandled `SEHException`.

This change makes the new EH behave like the legacy one w.r.t. the longjmp propagation over managed frames on Windows. It is a best effort fix though just to get rid of the regression related to the legacy exception handling. New code should not rely on this. And it doesn't work on non-windows targets (neither did it work with the legacy exception handling).

Close #111242

### CODE REVIEW

File: src/coreclr/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -932,6 +932,13 @@ ProcessCLRExceptionNew(IN     PEXCEPTION_RECORD   pExceptionRecord,
 
     Thread* pThread         = GetThread();
 
+    if (pExceptionRecord->ExceptionCode == STATUS_LONGJUMP)
+    {
+        // This is an exception used to unwind during longjmp function. We just let it pass through managed
```
Comment (jkotas) [inline src/coreclr/vm/exceptionhandling.cpp:937]: Do we need to unwind Frames to avoid corrupting runtime data structures?

**Comment by jkotas** [comment]
If we want to "support this", should we add a test?

File: src/coreclr/vm/exceptionhandling.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/vm/exceptionhandling.cpp:937]: And if we are unwinding Frames, is it that hard to call finallys too to match the old behavior?

Comment (janvorli) [reply src/coreclr/vm/exceptionhandling.cpp:937]: I had it implemented by propagating the exception through the managed frames as usual, so the finallys were called, and then re-issued the longjmp after processing them. The only missing part to do was preventing calling catch handlers. The old EH doesn't call those "naturally", as the longjmp runs only the unwind pass.
And then you've mentioned it was not supported, so I have deleted that code :-).
But anyways, I can change it back to that, the change wasn't complicated. The only thing is that the Unix handling would then be different.

Comment (jkotas) [reply src/coreclr/vm/exceptionhandling.cpp:937]: > The only thing is that the Unix handling would then be different.

longjump over managed code does not and cannot work well on Unix, so I do not think it is a problem

File: src/tests/Regressions/coreclr/GitHub_11242/CMakeLists.txt [hunk 2]
```diff
@@ -0,0 +1,15 @@
+project (Test11242Lib)
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_11242/CMakeLists.txt:1]: The issue number is `111242`

Comment (janvorli) [reply src/tests/Regressions/coreclr/GitHub_11242/CMakeLists.txt]: Thank you for spotting this, fixed.

**Comment by jkotas** [comment]
It may be worth noting that this is best effort for backward compatibility. Skipping over managed frames using setjmp/longjmp is unsupported.

File: src/coreclr/vm/exceptionhandling.cpp [hunk 3]
```diff
@@ -8151,6 +8192,13 @@ extern "C" BOOL QCALLTYPE EHEnumNext(EH_CLAUSE_ENUMERATOR* pEHEnum, RhEHClause*
         {
             result = FALSE;
         }
+#ifdef HOST_WINDOWS
+        // When processing longjmp, only finally clauses are considered.
```
Comment (jkotas) [inline src/coreclr/vm/exceptionhandling.cpp:8196]: This is one of the reasons for not supporting setjmp/longjmp. setjmp/longjmp behaves like uncatchable exception - managed code is not generally robust against uncatchable exceptions.

**Comment by jkotas** [comment]
LGTM otherwise

File: src/coreclr/vm/exceptionhandling.cpp (hunk 3 above)
Comment (janvorli) [reply src/coreclr/vm/exceptionhandling.cpp:8196]: I completely agree. The intent is really just to fix the regression on Windows w.r.t. the legacy EH. It is a best effort and not something people should use in new code. I hope that the fact that it doesn't work on Linux is enough reason for trying to stay away from using longjmp over managed code.

**Comment by janvorli** [comment]
> It may be worth noting that this is best effort for backward compatibility. Skipping over managed frames using setjmp/longjmp is unsupported.

I've added a comment to the code and updated the PR description to be explicit about this.

File: src/coreclr/vm/exceptionhandling.cpp [hunk 4]
```diff
@@ -5660,14 +5660,30 @@ VOID DECLSPEC_NORETURN DispatchManagedException(OBJECTREF throwable, CONTEXT* pE
...
+    newExceptionRecord.ExceptionRecord = NULL;
 
-    ExInfo exInfo(pThread, &exceptionRecord, pExceptionContext, ExKind::Throw);
+    ExInfo exInfo(pThread, &newExceptionRecord, pExceptionContext, ExKind::Throw);
+
+#ifdef HOST_WINDOWS
+    // On Windows, this enables the possibility to propagate a longjmp across managed frames. Longjmp
+    // behaves like a SEH exception, but only runs the second (unwinding) pass.
+    // NOTE: This is a best effort purely for back compatibility with the legacy exception handling.
+    // It is not guaranteed to work in all cases, and it is not recommended to use it in new code.
```
Comment (jkotas) [inline src/coreclr/vm/exceptionhandling.cpp:5676]:
```suggestion
    // Skipping over managed frames using setjmp/longjmp is
    // is unsupported and it is not guaranteed to work reliably in all cases.
    // https://learn.microsoft.com/dotnet/standard/native-interop/exceptions-interoperability#setjmplongjmp-behaviors
```

File: src/coreclr/vm/exceptionhandling.cpp [hunk 5]
```diff
@@ -5660,14 +5660,32 @@ VOID DECLSPEC_NORETURN DispatchManagedException(OBJECTREF throwable, CONTEXT* pE
...
+    newExceptionRecord.NumberParameters = MarkAsThrownByUs(newExceptionRecord.ExceptionInformation, hr);
+    newExceptionRecord.ExceptionRecord = NULL;
 
-    ExInfo exInfo(pThread, &exceptionRecord, pExceptionContext, ExKind::Throw);
+    ExInfo exInfo(pThread, &newExceptionRecord, pExceptionContext, ExKind::Throw);
+
+#ifdef HOST_WINDOWS
+    // On Windows, this enables the possibility to propagate a longjmp across managed frames. Longjmp
+    // behaves like a SEH exception, but only runs the second (unwinding) pass.
+    // NOTE: This is a best effort purely for back compatibility with the legacy exception handling.
```
Comment (jkotas) [inline src/coreclr/vm/exceptionhandling.cpp:5675]:
```suggestion
    // NOTE: This is a best effort purely for backward compatibility with the legacy exception handling.
```

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by janvorli** [comment]
@MichalStrehovsky this fix was made just for backward compatibility with the old exception handling, we don't want to fix it for NativeAOT. I am sorry for forgetting disabling the test for NativeAOT.

**Comment by badrishc** [comment]
Will this fix make it to the .NET 9 releases? We need it for Lua support in Garnet to handle unknown commands properly.

**Comment by jkotas** [comment]
@badrishc It is hard to justify backporting this fix to .NET 9. setjmp/longjmp interop is not supported by .NET: https://learn.microsoft.com/en-us/dotnet/standard/native-interop/exceptions-interoperability#setjmplongjmp-behaviors . This fix does not make it work or supported. It just makes it about as broken as it was, on Windows only. It was and it is still completely broken on Linux. It is not possible to fix that on non-Windows as described in the linked doc. We had a lot of debate whether to bother with fixing this on Windows at all. 

My understanding is that https://github.com/microsoft/Garnet supports both Windows and non-Windows platforms. Is that correct? If it is the case, you will need to avoid depending on setjmp/longjmp interop to make the Lua integration work on non-Windows platforms.

**Comment by jkotas** [comment]
The runtime keeps track of the managed/native and native/managed transitions. The transitions are structures allocated on the stack and the runtime Thread data structure keeps pointer (`Thread::m_pFrame`) to the inner-most transition. 

`longjmp` on Unix will unwind the stack, without updating the `m_pFrame` pointer in the Thread structure. It means that it is going to be a dangling pointer for a while that violates the runtime invariants. I guess you are getting lucky in your tests that the stack region where this dangling pointer points to is not overwritten and/or that the dangling pointer gets overwritten with a valid transition pointer before you managed to hit a crash.

**Comment by kevin-montrose** [comment]
> `longjmp` on Unix will unwind the stack, without updating the `m_pFrame` pointer in the Thread structure. It means that it is going to be a dangling pointer for a while that violates the runtime invariants. I guess you are getting lucky in your tests that the stack region where this dangling pointer points to is not overwritten and/or that the dangling pointer gets overwritten with a valid transition pointer before you managed to hit a crash.

Well, that's fffffffffff-un 🫠.

I'll spend some more time trying to come up with a design that lets Garnet embed Lua on Linux w/o the possibility of `longjmp`ing over any managed frames.  The tricky bit is Lua uses it for implicit failures, like OOMs - which are hard to avoid, and basically impossible to patch out.

**Comment by badrishc** [comment]
> @badrishc It is hard to justify backporting this fix to .NET 9. setjmp/longjmp interop is not supported by .NET: https://learn.microsoft.com/en-us/dotnet/standard/native-interop/exceptions-interoperability#setjmplongjmp-behaviors . This fix does not make it work or supported. It just makes it about as broken as it was, on Windows only. It was and it is still completely broken on Linux. It is not possible to fix that on non-Windows as described in the linked doc. We had a lot of debate whether to bother with fixing this on Windows at all.
> 
> My understanding is that https://github.com/microsoft/Garnet supports both Windows and non-Windows platforms. Is that correct? If it is the case, you will need to avoid depending on setjmp/longjmp interop to make the Lua integration work on non-Windows platforms.

Thanks for the details and context! I want to mention that beyond Garnet, there is fairly wide production use of Lua across Microsoft and outside, and often via the NLua C# library that interops into Lua, and often on Windows. This is also evidenced by @stephentoub's [comment](https://github.com/NLua/NLua/pull/531#issuecomment-2142801625) and [PR](https://github.com/NLua/NLua/pull/531) into NLua last year.

Since Lua uses `longjmp` as its exception handling mechanism (other C libraries might also do the same, perhaps), it would be great to see: (1) how best we can support this on windows, e.g., by backporting this fix to .NET 9; and (2) what, if anything, can .NET do as a _best effort_ to make specifically Lua's style of exception handling work on unix (even though I fully understand your point about it being generally unsupported). Just my 2 cents.
