### PR TITLE
JIT: defer crossgen update when trying to call unboxed entry

### LINKED ISSUE #52450: Assert failure: !"embedClassHandle"
Starting with:

https://dev.azure.com/dnceng/public/_build/results?buildId=1126222&view=results

All outerloop R2R jobs are failing to crossgen the framework:
```
4 / 259 (0%, 1 failed): failed in 10798 msecs, exit code 134, expected 0: crossgen @/__w/1/s/artifacts/tests/coreclr/obj/Linux.x64.Checked/crossgen.out/System.Private.Xml.dll.rsp
!! Assert failure(PID 6565 [0x000019a5], Thread: 6565 [0x19a5]): !"embedClassHandle"
!!     File: /__w/1/s/src/coreclr/zap/zapinfo.cpp Line: 1580
!!     Image: /__w/1/s/artifacts/bin/coreclr/Linux.x64.Checked/crossgen
  Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
  Copyright (c) Microsoft Corporation.  All rights reserved.
5 / 259 (0%, 1 failed): launching: /__w/1/s/artifacts/bin/coreclr/Linux.x64.Checked/crossgen @/__w/1/s/artifacts/tests/coreclr/obj/Linux.x64.Checked/crossgen.out/Microsoft.Diagnostics.Tracing.TraceEvent.dll.rsp
...
8 / 259 (1%, 2 failed): failed in 584 msecs, exit code 134, expected 0: crossgen @/__w/1/s/artifacts/tests/coreclr/obj/Linux.x64.Checked/crossgen.out/System.Data.Common.dll.rsp
!! Assert failure(PID 6583 [0x000019b7], Thread: 6583 [0x19b7]): !"embedClassHandle"
!!     File: /__w/1/s/src/coreclr/zap/zapinfo.cpp Line: 1580
!!     Image: /__w/1/s/artifacts/bin/coreclr/Linux.x64.Checked/crossgen
  Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
  Copyright (c) Microsoft Corporation.  All rights reserved.
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Some unboxed entries require an additional generic context argument, and
finding the right form for this argument when prejitting is more complex than
it is for jitting. So, defer this update when prejitting.

Resolves #52450.

### CODE REVIEW

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -21146,58 +21146,70 @@ void Compiler::impDevirtualizeCall(GenTreeCall*            call,
...
-                        const DWORD derivedClassAttribs = info.compCompHnd->getClassAttribs(derivedClass);
-
-                        if ((derivedClassAttribs & CORINFO_FLG_SHAREDINST) != 0)
+                        // Defer if prejitting as working backwards from the class handle to the right
+                        // representation is messy.
+                        if (opts.jitFlags->IsSet(JitFlags::JIT_FLAG_PREJIT))
                         {
-                            JITDUMP(
-                                "unboxed entry needs MT arg, but the handle we have is shared. Deferring update.\n");
+                            JITDUMP("unboxed entry needs MT arg, embedding this is complicated for prejit. Deferring "
```
Comment (jkotas) [inline src/coreclr/jit/importer.cpp:21153]: I believe that we have done work to embed this in crossgen2. Is this just a problem for old crossgen?

We should just throw an NYI exception in old crossgen instead of asserting. It is what we have been doing in other similar situations. We are generally not spending time on keeping parity in old crossgen.

Comment (AndyAyersMS) [reply src/coreclr/jit/importer.cpp:21153]: Yes, it's just a problem for crossgen, and only for a relatively small number of methods.

So I'll revise per your suggestion.

Comment (AndyAyersMS) [reply src/coreclr/jit/importer.cpp:21153]: Crossgen is already throwing here -- but it is asserting first. So looks like I can just remove the assert.

https://github.com/dotnet/runtime/blob/98ac23212e6017c615e7e855e676fc43c8e44cb8/src/coreclr/zap/zapinfo.cpp#L1578-L1582

**Review by BruceForstall — APPROVED** [review]

**Review by jkotas — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Failure is known: #52464

**Comment by AndyAyersMS** [comment]
I ran crossgen locally on the two examples with asserts, so don't see the need to run outerloop here.
