### PR TITLE
Small clean up in gtMarkAddrMode

### LINKED ISSUE #103577: [jitstress] JIT\Regression\JitBlue\Runtime_90423 fails with "Assertion failed '(op2 == idx) || (op2->gtEffectiveVal() == idx)' during 'Find oper order'"
jitstress is red due to this assertion failure: https://dev.azure.com/dnceng-public/public/_build?definitionId=109&_a=summary
Example console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-103559-merge-65fba342677a469aac/Regression_2/1/console.ff49ede3.log?helixlogtype=result

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/103577

### CODE REVIEW

**Comment by EgorBo** [comment]
@MihuBot

**Comment by EgorBo** [comment]
PTAL @jakobbotsch @AndyAyersMS @dotnet/jit-contrib

Diffs. A few small regressions where we no longer have "DONT_CSE" where we used to. I am rewriting the whole `gtMarkAddrMode` currently, decided to push this clean up to unblock jitstress blocked by https://github.com/dotnet/runtime/issues/103577

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -4845,95 +4833,9 @@ bool Compiler::gtMarkAddrMode(GenTree* addr, int* pCostEx, int* pCostSz, var_typ
...
-                        }
-                    }
-                    assert((op2 == idx) || (op2->gtEffectiveVal() == idx));
-                }
-            }
-            else
-            {
-                // op1 isn't base or idx. Is this possible? Or should there be an assert?
-            }
+            op2->gtFlags |= GTF_ADDRMODE_NO_CSE;
```
Comment (EgorBo) [inline src/coreclr/jit/gentree.cpp:4838]: a temp quirk to revert some size regressions

**Review by jakobbotsch — APPROVED** [review]
