### PR TITLE
Revisit `PatternContext<TFrame>.PushDataFrame` nullable annotation

### LINKED ISSUE #65590: Revisit PatternContext<TFrame>.PushDataFrame nullable annotation
### Description

See the conversation here: https://github.com/dotnet/core/pull/7211#discussion_r810075469

https://github.com/dotnet/runtime/pull/57398 annotated `PushDataFrame` as allowing a nullable `TFrame` argument. However, it doesn't make sense to push a `null` frame, and would lead to other issues if we did.

Note that the `TFrame` is currently only ever used with a `struct` type, which can never be `null`.

### Reproduction Steps

Call `PatternContext<TFrame>.PushDataFrame` with a `null`.

### Expected behavior

It should give a "this parameter should not be `null`" warning.

### Actual behavior

It allows `null` values without a warning.

### Regression?

No.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by maxkoshevoi**
Fixes: #65590 

`where TFrame : struct` needs to be added here, right? Otherwise there's a possibility of `protected TFrame Frame;` being `null` and therefore `null` being pushed.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.cs [hunk 1]
```diff
@@ -247,14 +247,14 @@ public partial class PatternContextRaggedInclude : Microsoft.Extensions.FileSyst
         public override void Declare(System.Action<Microsoft.Extensions.FileSystemGlobbing.Internal.IPathSegment, bool> onDeclare) { }
         public override bool Test(Microsoft.Extensions.FileSystemGlobbing.Abstractions.DirectoryInfoBase directory) { throw null; }
     }
-    public abstract partial class PatternContext<TFrame> : Microsoft.Extensions.FileSystemGlobbing.Internal.IPatternContext
+    public abstract partial class PatternContext<TFrame> : Microsoft.Extensions.FileSystemGlobbing.Internal.IPatternContext where TFrame : struct
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.cs:250]: I believe this is a breaking change. The type is in an `Internal` namespace and I'm not sure others actually use this.

cc @terrajobst @adamsitnik @Jozkee - thoughts on whether this break is "worth it"?

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.cs [hunk 2]
```diff
@@ -247,14 +247,14 @@ public partial class PatternContextRaggedInclude : Microsoft.Extensions.FileSyst
...
     {
-        protected TFrame? Frame;
+        protected TFrame Frame;
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.cs:252]: Couldn't we just leave this as `protected TFrame? Frame;` and just change `protected void PushDataFrame(TFrame? frame)` => `protected void PushDataFrame(TFrame frame)`?

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.cs (hunk 1 above)
Comment (Jozkee) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.cs:250]: Welp, people is not supposed to use this type. As per the [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing.internal.patterncontexts.patterncontext-1.pushdataframe?view=dotnet-plat-ext-6.0):
> This API supports infrastructure and is not intended to be used directly from your code. This API may change or be removed in future releases.

IMO is not worth correcting (file a breaking change doc for something that no one is supposed to use) "internal" APIs like this one.

Comment (Jozkee) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.cs:250]: > (file a breaking change doc for something that no one is supposed to use)

OTOH, If this is not an inconvenient at all, we can do whatever we want to this API.

Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.cs:250]: Well the docs say "This API may change". So I'm OK with changing it. Are the area-owners OK with it?  @dotnet/area-extensions-filesystem ?

Comment (Jozkee) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.cs:250]: I'm one owner and I'm OK with it :)

**Review by eerhardt — APPROVED** [review]
LGTM.

**Comment by eerhardt** [comment]
Breaking change issue written: https://github.com/dotnet/docs/issues/28705.
