### PR TITLE
JIT: Fix GC hole for Armv8.1 Atomics

### LINKED ISSUE #79431: Test failure ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd
Run: [runtime-coreclr gcstress-extra 20221208.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106070&view=ms.vss-test-web.build-test-results-tab&runId=2271196&resultId=122031&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked gcstress0xc_zapdisable @ Windows.10.Arm64v8.Open

- ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd

coreclr windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open

- JIT\\Regression\\JitBlue\\Runtime_45557\\Runtime_45557\\Runtime_45557.cmd
```

**Error message:**
```
Assert failure(PID 11016 [0x00002b08], Thread: 13944 [0x3678]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! Object::ValidateInner'::1'::catch$12 + 0x138 (0x00007fff23436698) CORECLR! CallSettingFrame + 0x68 (0x00007fff22e82e60)
CORECLR! _FrameHandler3::CxxCallCatchBlock + 0x134 (0x00007fff23393544) NTDLL! RtlRestoreContext + 0xEC (0x00007fff69fe369c)
CORECLR! Object::ValidateInner + 0x144 (0x00007fff22f7763c) CORECLR! Object::Validate + 0xA4 (0x00007fff22f7743c)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007fff2318c898) CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1274 (0x00007fff2318b6ac)
CORECLR! EECodeManager::EnumGcRefs + 0x2D0 (0x00007fff22eea470) CORECLR! GcStackCrawlCallBack + 0x434 (0x00007fff230499b4)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 600
Image: D:\h\w\B3B209DA\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\B3B209DA\w\A5E508F1\uploads\Reports\ilasm.PortablePdb\IlasmPortablePdbTests\IlasmPortablePdbTests.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B3B209DA\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  IlasmPortablePdbTests.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B3B209DA\p
D:\h\w\B3B209DA\w\A5E508F1\e\ilasm\PortablePdb\IlasmPortablePdbTests\IlasmPortablePdbTests.cmd
Expected: True
Actual:   False


Stack trace
   at ilasm_PortablePdb._IlasmPortablePdbTests_IlasmPortablePdbTests_._IlasmPortablePdbTests_IlasmPortablePdbTests_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### LINKED ISSUE #80582: Possible ARM64 GC Hole - `JIT/HardwareIntrinsics/General/Vector256_1/Vector256_1_ro/Vector256_1_ro`
`coreclr windows arm64 Checked gcstress0xc_zapdisable_heapverify1 @ Windows.11.Arm64.Open`

```
Assert failure(PID 9600 [0x00002580], Thread: 8996 [0x2324]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

CORECLR! Object::ValidateInner + 0x190 (0x00007ffd`16586bf0)
CORECLR! Object::Validate + 0xA4 (0x00007ffd`165869a4)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007ffd`167991b8)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1274 (0x00007ffd`16797fcc)
CORECLR! EECodeManager::EnumGcRefs + 0x2D0 (0x00007ffd`164fa440)
CORECLR! GcStackCrawlCallBack + 0x434 (0x00007ffd`16658cc4)
CORECLR! Thread::StackWalkFramesEx + 0x240 (0x00007ffd`165b3c70)
CORECLR! Thread::StackWalkFrames + 0x158 (0x00007ffd`165b3988)
CORECLR! ScanStackRoots + 0x288 (0x00007ffd`16657b30)
CORECLR! GCToEEInterface::GcScanRoots + 0x1AC (0x00007ffd`16656a0c)
    File: D:\a\_work\1\s\src\coreclr\vm\object.cpp Line: 522
    Image: C:\h\w\B8BE0A37\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B8BE0A37\w\C7300A7C\uploads\General\Vector256_1\Vector256_1_ro\output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B8BE0A37\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Vector256_1_ro.dll 
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunGenericScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:\h\w\B8BE0A37\w\C7300A7C\e\JIT\HardwareIntrinsics\HardwareIntrinsics_ro\../General/Vector256_1/Vector256_1_ro/Vector256_1_ro.cmd
```

### LINKED ISSUE #80583: X86 Assert failure - `baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd`
`coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open`

```
Assert failure(PID 2100 [0x00000834], Thread: 1112 [0x0458]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! DoJITFailFast + 0xBA (0x70290cbc)
CORECLR! CrawlFrame::SetCurGSCookie + 0x2F (0x7016399e)
CORECLR! StackFrameIterator::PreProcessingForManagedFrames + 0x51 (0x70163459)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x21C (0x701637bd)
CORECLR! StackFrameIterator::NextRaw + 0x9E0 (0x701630dd)
CORECLR! StackFrameIterator::Next + 0x50 (0x701626b7)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x70163d15)
CORECLR! Thread::StackWalkFrames + 0x159 (0x70163afd)
CORECLR! ScanStackRoots + 0x196 (0x70239e24)
CORECLR! GCToEEInterface::GcScanRoots + 0xF1 (0x7023817f)
    File: D:\a\_work\1\s\src\coreclr\vm\jithelpers.cpp Line: 4351
    Image: C:\h\w\AB7F0927\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\AB7F0927\w\ABF80962\uploads\Reports\baseservices.callconvs\TestCallingConventions\TestCallingConventions.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AB7F0927\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestCallingConventions.dll 
Running BlittableFunctionPointers...
 -- unmanaged
 -- unmanaged cdecl
 -- unmanaged stdcall
 -- unmanaged modopt(cdecl)
 -- unmanaged modopt(stdcall)
 -- unmanaged modopt unrecognized
 -- unmanaged modopt(stdcall) modopt(cdecl)
 -- unmanaged modopt(stdcall) modopt(unrecognized)
 -- unmanaged cdecl modopt(stdcall)
 -- unmanaged stdcall modopt(cdecl)
Running NonblittableFunctionPointers...
 -- unmanaged
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AB7F0927\p
> C:\h\w\AB7F0927\w\ABF80962\e\baseservices\callconvs\TestCallingConventions\TestCallingConventions.cmd

```

### LINKED ISSUE #80584: Possible ARM64 GC Hole - `JIT\\Regression\\JitBlue\\DevDiv_461649\\DevDiv_461649\\DevDiv_461649.cmd`
`coreclr windows arm64 Checked gcstress0xc_zapdisable @ Windows.11.Arm64.Open`

```
Assert failure(PID 7292 [0x00001c7c], Thread: 1828 [0x0724]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! `Object::ValidateInner'::`1'::catch$12 + 0x138 (0x00007fff`28dd03a4)
CORECLR! CallSettingFrame + 0x68 (0x00007fff`28822e60)
CORECLR! _FrameHandler3::CxxCallCatchBlock + 0x134 (0x00007fff`28d2d1f4)
NTDLL! RtlCaptureContext + 0x1B8 (0x00007fff`8fcc2248)
CORECLR! Object::ValidateInner + 0x15C (0x00007fff`28916bbc)
CORECLR! Object::Validate + 0xA4 (0x00007fff`289169a4)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007fff`28b291b8)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1274 (0x00007fff`28b27fcc)
CORECLR! EECodeManager::EnumGcRefs + 0x2D0 (0x00007fff`2888a440)
CORECLR! GcStackCrawlCallBack + 0x434 (0x00007fff`289e8cc4)
    File: D:\a\_work\1\s\src\coreclr\vm\object.cpp Line: 600
    Image: C:\h\w\A6170910\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A6170910\w\BB360A33\uploads\Reports\JIT.Regression\JitBlue\DevDiv_461649\DevDiv_461649\DevDiv_461649.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A6170910\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  DevDiv_461649.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A6170910\p
> C:\h\w\A6170910\w\BB360A33\e\JIT\Regression\JitBlue\DevDiv_461649\DevDiv_461649\DevDiv_461649.cmd
```

### LINKED ISSUE #80585: Possible ARM64 GC Hole - `Regressions\\coreclr\\GitHub_16833\\Test16833\\Test16833.cmd`
`coreclr windows arm64 Checked gcstress0xc_zapdisable @ Windows.11.Arm64.Open`

```

Assert failure(PID 6384 [0x000018f0], Thread: 1224 [0x04c8]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

CORECLR! Object::ValidateInner + 0x190 (0x00007ffc`6e156bf0)
CORECLR! Object::Validate + 0xA4 (0x00007ffc`6e1569a4)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007ffc`6e3691b8)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1274 (0x00007ffc`6e367fcc)
CORECLR! EECodeManager::EnumGcRefs + 0x2D0 (0x00007ffc`6e0ca440)
CORECLR! GcStackCrawlCallBack + 0x434 (0x00007ffc`6e228cc4)
CORECLR! Thread::StackWalkFramesEx + 0x240 (0x00007ffc`6e183c70)
CORECLR! Thread::StackWalkFrames + 0x158 (0x00007ffc`6e183988)
CORECLR! ScanStackRoots + 0x288 (0x00007ffc`6e227b30)
CORECLR! GCToEEInterface::GcScanRoots + 0x1AC (0x00007ffc`6e226a0c)
    File: D:\a\_work\1\s\src\coreclr\vm\object.cpp Line: 522
    Image: C:\h\w\A6170910\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A6170910\w\9CD508B8\uploads\Reports\Regressions.coreclr\GitHub_16833\Test16833\Test16833.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A6170910\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Test16833.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A6170910\p
> C:\h\w\A6170910\w\9CD508B8\e\Regressions\coreclr\GitHub_16833\Test16833\Test16833.cmd

```

### LINKED ISSUE #80586: Possible ARM64 GC Hole - `Loader\\CollectibleAssemblies\\ByRefLocals\\ByRefLocals\\ByRefLocals.cmd`
`coreclr windows arm64 Checked gcstress0xc_zapdisable @ Windows.11.Arm64.Open`

```
Assert failure(PID 5176 [0x00001438], Thread: 2940 [0x0b7c]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

CORECLR! Object::ValidateInner + 0x190 (0x00007ffc`6e156bf0)
CORECLR! Object::Validate + 0xA4 (0x00007ffc`6e1569a4)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007ffc`6e3691b8)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1274 (0x00007ffc`6e367fcc)
CORECLR! EECodeManager::EnumGcRefs + 0x2D0 (0x00007ffc`6e0ca440)
CORECLR! GcStackCrawlCallBack + 0x434 (0x00007ffc`6e228cc4)
CORECLR! Thread::StackWalkFramesEx + 0x240 (0x00007ffc`6e183c70)
CORECLR! Thread::StackWalkFrames + 0x158 (0x00007ffc`6e183988)
CORECLR! ScanStackRoots + 0x288 (0x00007ffc`6e227b30)
CORECLR! GCToEEInterface::GcScanRoots + 0x1AC (0x00007ffc`6e226a0c)
    File: D:\a\_work\1\s\src\coreclr\vm\object.cpp Line: 522
    Image: C:\h\w\A6170910\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A6170910\w\9CD508B8\uploads\Reports\Loader.CollectibleAssemblies\ByRefLocals\ByRefLocals\ByRefLocals.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A6170910\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ByRefLocals.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A6170910\p
> C:\h\w\A6170910\w\9CD508B8\e\Loader\CollectibleAssemblies\ByRefLocals\ByRefLocals\ByRefLocals.cmd
```

### LINKED ISSUE #80587: Possible ARM64 GC Hole - `Loader\\classloader\\StaticVirtualMethods\\NegativeTestCases\\CuriouslyRecurringGenericWithUnimplementedMethod\\CuriouslyRecurringGenericWithUnimplementedMethod.cmd`
`coreclr windows arm64 Checked gcstress0xc_zapdisable @ Windows.11.Arm64.Open`

```
Assert failure(PID 2404 [0x00000964], Thread: 5892 [0x1704]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

CORECLR! Object::ValidateInner + 0x190 (0x00007ff8`ac4b6bf0)
CORECLR! Object::Validate + 0xA4 (0x00007ff8`ac4b69a4)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007ff8`ac6c91b8)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1274 (0x00007ff8`ac6c7fcc)
CORECLR! EECodeManager::EnumGcRefs + 0x2D0 (0x00007ff8`ac42a440)
CORECLR! GcStackCrawlCallBack + 0x434 (0x00007ff8`ac588cc4)
CORECLR! Thread::StackWalkFramesEx + 0x240 (0x00007ff8`ac4e3c70)
CORECLR! Thread::StackWalkFrames + 0x158 (0x00007ff8`ac4e3988)
CORECLR! ScanStackRoots + 0x288 (0x00007ff8`ac587b30)
CORECLR! GCToEEInterface::GcScanRoots + 0x1AC (0x00007ff8`ac586a0c)
    File: D:\a\_work\1\s\src\coreclr\vm\object.cpp Line: 522
    Image: C:\h\w\A6170910\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A6170910\w\AB4E0947\uploads\Reports\Loader.classloader\StaticVirtualMethods\NegativeTestCases\CuriouslyRecurringGenericWithUnimplementedMethod\CuriouslyRecurringGenericWithUnimplementedMethod.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A6170910\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  CuriouslyRecurringGenericWithUnimplementedMethod.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A6170910\p
> C:\h\w\A6170910\w\AB4E0947\e\Loader\classloader\StaticVirtualMethods\NegativeTestCases\CuriouslyRecurringGenericWithUnimplementedMethod\CuriouslyRecurringGenericWithUnimplementedMethod.cmd
```

### LINKED ISSUE #80588: Possible ARM64 GC Hole - `JIT\\Regression\\JitBlue\\Runtime_64208\\Runtime_64208\\Runtime_64208.cmd`
`coreclr windows arm64 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.11.Arm64.Open`
```
Assert failure(PID 8344 [0x00002098], Thread: 1944 [0x0798]): SanityCheck()

CORECLR! MethodTable::Validate + 0x44 (0x00007ff9`bad7f8fc)
CORECLR! Object::ValidateInner + 0x15C (0x00007ff9`bad86bbc)
CORECLR! Object::Validate + 0xA4 (0x00007ff9`bad869a4)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007ff9`baf991b8)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1274 (0x00007ff9`baf97fcc)
CORECLR! EECodeManager::EnumGcRefs + 0x2D0 (0x00007ff9`bacfa440)
CORECLR! GcStackCrawlCallBack + 0x434 (0x00007ff9`bae58cc4)
CORECLR! Thread::StackWalkFramesEx + 0x240 (0x00007ff9`badb3c70)
CORECLR! Thread::StackWalkFrames + 0x158 (0x00007ff9`badb3988)
CORECLR! ScanStackRoots + 0x288 (0x00007ff9`bae57b30)
    File: D:\a\_work\1\s\src\coreclr\vm\methodtable.cpp Line: 8700
    Image: C:\h\w\AD4C09C6\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\AD4C09C6\w\C0480A34\uploads\Reports\JIT.Regression\JitBlue\Runtime_64208\Runtime_64208\Runtime_64208.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AD4C09C6\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Runtime_64208.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AD4C09C6\p
> C:\h\w\AD4C09C6\w\C0480A34\e\JIT\Regression\JitBlue\Runtime_64208\Runtime_64208\Runtime_64208.cmd
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
Unlike seemingly all other ARM instructions, the set of instructions marked by this PR actually write their result in the second operand register instead of the first. This means we were incorrectly updating GC info when emitting these instructions.

Fix #79431
Fix #80582
Fix #80584
Fix #80585
Fix #80586
Fix #80587
Fix #80588

I have not checked all the above issues, but I think it is likely they are all this underlying problem. We can reopen them if they keep reproing in GC stress.

Some more context in the investigation: https://github.com/dotnet/runtime/issues/79431#issuecomment-1385522143

### CODE REVIEW

File: src/coreclr/jit/emitarm64.cpp [hunk 1]
```diff
@@ -10729,6 +10744,24 @@ size_t emitter::emitOutputInstr(insGroup* ig, instrDesc* id, BYTE** dp)
...
+                if (id->idGCref() != GCT_NONE)
+                {
+                    emitGCregLiveUpd(id->idGCref(), id->idReg2(), dst);
+                }
+                else
+                {
+                    emitGCregDeadUpd(id->idReg2(), dst);
+                }
+
+                goto SKIP_GC_UPDATE;
```
Comment (kunalspathak) [inline src/coreclr/jit/emitarm64.cpp:10762]: Question - Natural place to do this is down below before `SKIP_GC_UPDATE`, but you prefer to update it here, so most of the other formats don't have to execute this extra ` if (emitInsDestIsOp2(ins))`?

**Review by kunalspathak — APPROVED** [review]
Thanks for the quick fix.

File: src/coreclr/jit/emitarm64.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/emitarm64.cpp:10762]: Yes, exactly, I did first try to check it down there but it had some TP cost.

**Review by BruceForstall — APPROVED** [review]

**Comment by jakobbotsch** [comment]
GC stress jobs are not completely green with this change but this does seem to fix the vast majority of the failures.

**Comment by jakobbotsch** [comment]
For posterity, I think this was exposed by #79181, before that change we would not see these instructions used with GC refs.
