### PR TITLE
[JIT] ARM32/ARM64 - Fixed zero/sign-extension for `GT_STORE_LCL_VAR` in codegen

### LINKED ISSUE #84693: [Fuzzlyn] Arm64 failure for negation, cast, bitwise-and
# 1 reduced examples are available
```csharp
// Generated by Fuzzlyn v1.5 on 2023-04-12 13:58:51
// Run on Arm64 MacOS
// Seed: 15653303803842509097
// Reduced from 14.3 KiB to 0.3 KiB in 00:00:10
// Debug: Outputs 255
// Release: Outputs -1
public class Program
{
    public static short s_2;
    public static void Main()
    {
        sbyte vr5 = (sbyte)M8(1);
    }

    public static uint M8(byte arg0)
    {
        s_2 = 1;
        arg0 = (byte)(-s_2);
        var vr1 = arg0 & arg0;
        System.Console.WriteLine(vr1);
        return 0;
    }
}
```

### PR DESCRIPTION
**Pull request by TIHan**
Resolves https://github.com/dotnet/runtime/issues/84693

We were not handling zero/sign-extends for NormalizeOnLoad local stores correctly on ARM.

### CODE REVIEW

**Comment by TIHan** [comment]
@dotnet/jit-contrib @kunalspathak This is ready pending CI.

File: src/coreclr/jit/codegenarm.cpp [hunk 1]
```diff
@@ -1120,7 +1120,16 @@ void CodeGen::genCodeForStoreLclVar(GenTreeLclVar* tree)
             else // store into register (i.e move into register)
             {
                 // Assign into targetReg when dataReg (from op1) is not the same register
-                inst_Mov(targetType, targetReg, dataReg, /* canSkip */ true);
+                if (!data->isUsedFromReg())
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenarm.cpp:1123]: When is this branch taken?

Comment (TIHan) [reply src/coreclr/jit/codegenarm.cpp:1123]: From the xarch side of things, this is the comment:
```cpp
            if (!op1->isUsedFromReg())
            {
                // Currently, we assume that the non-reg source of a GT_STORE_LCL_VAR writing to a register
                // must be a constant. However, in the future we might want to support an operand used from
                // memory.  This is a bit tricky because we have to decide it can be used from memory before
                // register allocation,
                // and this would be a case where, once that's done, we need to mark that node as always
                // requiring a register - which we always assume now anyway, but once we "optimize" that
                // we'll have to take cases like this into account.
                assert((op1->GetRegNum() == REG_NA) && op1->OperIsConst());
                genSetRegToConst(targetReg, targetType, op1);
            }
            else
            {
                assert(targetReg == lclNode->GetRegNum());
                assert(op1->GetRegNum() != REG_NA);
                inst_Mov_Extend(targetType, /* srcInReg */ true, targetReg, op1->GetRegNum(), /* canSkip */ true,
                                emitTypeSize(targetType));
            }
```

Off the top of my head, I don't know what code causes to go to that path.

Comment (TIHan) [reply src/coreclr/jit/codegenarm.cpp:1123]: Well, I just tried and the assertion gets hit :) 
>   Assertion failed 'data->OperIsConst()' in 'System.Enum:ToObject(System.Type,System.Object):System.Object' during 'Gen
  erate code' (IL size 355; hash 0x13b8126d; FullOpts)

Comment (SingleAccretion) [reply src/coreclr/jit/codegenarm.cpp:1123]: `!isUsedFromReg()` would imply here that the source is contained (or used from a spill temp).

The former implementation did not expect any contained operands, so I do not see the need for this branch.

**Comment by SingleAccretion** [comment]
What was the underlying problem here (perhaps the one we discussed a while back)?

If it was NOL, that implies fixing the "store" part of code is a workaround.

**Comment by TIHan** [comment]
@SingleAccretion From the issue, we were not zero-extending on store for a NOL, here is the before and after diffs in regards to that example in the issue:
image

**Comment by SingleAccretion** [comment]
In principle this should not matter, since upper bits of a NOL local have to be assumed to be random. Is the dump available?

**Comment by TIHan** [comment]
On x64, we do the zero-extend:
```asm
       mov      rax, 0xD1FFAB1E      ; data for test.Program:s_2
       mov      word  ptr [rax], 1
       movsx    rax, word  ptr [rax]
       neg      eax
       movzx    rcx, al
       and      ecx, ecx
       call     [System.Console:WriteLine(int)]
       xor      eax, eax
```

File: src/coreclr/jit/codegenarm.cpp (hunk 1 above)
Comment (TIHan) [reply src/coreclr/jit/codegenarm.cpp:1123]: Well, I can't simply remove the branch and always call `inst_Mov_Extend` as I get a lot of asserts.

**Comment by SingleAccretion** [comment]
So this is a variation of the "NOL does not work well with VN" issue. In particular, the problem is how `[000012]` is numbered here:
```scala
***** BB01, STMT00002(before)
N005 ( 20, 10) [000013] --CXG------                         *  CALL      void   System.Console:WriteLine(int)
N004 (  6,  7) [000016] ----------- arg0 in x0              \--*  CAST      int <- ubyte <- int
N003 (  5,  5) [000012] -----------                            \--*  AND       int   
N001 (  2,  2) [000010] -----------                               +--*  LCL_VAR   int    V00 arg0         u:2
N002 (  2,  2) [000011] -----------                               \--*  LCL_VAR   int    V00 arg0         u:2 (last use)

N001 [000010]   LCL_VAR   V00 arg0         u:2 => <l:$46 {IntCns 255}, c:$200 {$1c0, int <- ubyte <- int}>
N002 [000011]   LCL_VAR   V00 arg0         u:2 (last use) => <l:$46 {IntCns 255}, c:$200 {$1c0, int <- ubyte <- int}>
N003 [000012]   AND       => <l:$46 {IntCns 255}, c:$200 {$1c0, int <- ubyte <- int}>
N004 [000016]   CAST      => <l:$46 {IntCns 255}, c:$201 {$200, int <- ubyte <- int}>
  fgCurMemoryVN[GcHeap] assigned for CALL at [000013] to VN: $c1.
N005 [000013]   CALL      => $VN.Void

***** BB01, STMT00002(after)
N005 ( 20, 10) [000013] --CXG------                         *  CALL      void   System.Console:WriteLine(int) $VN.Void
N004 (  6,  7) [000016] ----------- arg0 in x0              \--*  CAST      int <- ubyte <- int <l:$46, c:$201>
N003 (  5,  5) [000012] -----------                            \--*  AND       int    <l:$46, c:$200>
N001 (  2,  2) [000010] -----------                               +--*  LCL_VAR   int    V00 arg0         u:2 <l:$46, c:$200>
N002 (  2,  2) [000011] -----------                               \--*  LCL_VAR   int    V00 arg0         u:2 (last use) <l:$46, c:$200>
```
In reality, the value of `AND`'s upper bits is undefined (and equal to `V00`'s). A denormalized NOL local without a cast on top of it is not legal (so one can view the original bug to be in the morph's transform which pushed the cast up).

That said, I would not have objections against merging this change anyway, for consistency between platforms if nothing else (if so, we should also fix LA64 and RISC-V).

File: src/coreclr/jit/codegenarm.cpp (hunk 1 above)
Comment (SingleAccretion) [reply src/coreclr/jit/codegenarm.cpp:1123]: That goes back to my original question then: when is `!isUsedFromReg()` `true` here?

Comment (TIHan) [reply src/coreclr/jit/codegenarm.cpp:1123]: Trying to only use `inst_Mov_Extend` but the assertions are because of vector and zero registers. So, instead of using `!isUsedFromReg` for the branch, I will check to see if we are using a general register.

Comment (TIHan) [reply src/coreclr/jit/codegenarm.cpp:1123]: Ok, for ARM32 it looks like we should be able to get rid of the branch, but not for ARM64.

**Comment by TIHan** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=238515&view=ms.vss-build-web.run-extensions-tab)
No regressions for arm64. There are some regressions for arm32, but that is fine since this fixes a correctness issue.

**Comment by kunalspathak** [comment]
Based on https://github.com/dotnet/runtime/issues/84693#issuecomment-1505651594, does this need to be backported to 7.0?

File: src/tests/JIT/Regression/JitBlue/Runtime_84693/Runtime_84693.cs [hunk 2]
```diff
@@ -0,0 +1,39 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System;
+using System.Collections;
+using System.Collections.Generic;
+using System.Runtime.CompilerServices;
+using Xunit;
+
+public class Test
```
Comment (kunalspathak) [inline src/tests/JIT/Regression/JitBlue/Runtime_84693/Runtime_84693.cs:10]: nit: I typically write a comment about what this test case is trying to verify and what was the underlying problem.

**Review by kunalspathak — APPROVED** [review]
I believe you will have to fix the formatting issues before merging.

**Comment by TIHan** [comment]
> does this need to be backported to 7.0?

Yes we should backport this since it is a correctness issue.

**Comment by TIHan** [comment]
CI failures are unrelated. Merging.
