### PR TITLE
[wasm][debugger] Run getter using Runtime.GetProperties

### LINKED ISSUE #62774: [wasm][debugger] Display custom accessors the same way as in Console Application
Currently:
```
    public class Test
    {
        public List<int> list { get { return new List<int>() { 1, 2 }; } }
        public int[] array { get { return new int[] { 11, 22 }; } }
        public string text { get { return "text"; } }
    }
```

Custom getters are displayed in Visual Studio as:
```
{{
  "get": {
    "type": "function",
    "objectId": "dotnet:object:2:methodId:8",
    "className": "Function",
    "description": "get list ()",
    "methodId": 8,
    "objectIdValue": "dotnet:object:2"
  },
  "name": "list",
  "isOwn": true
}}
```
and arrow used to expand properties triggers "Runtime.callFunctionOn".
In Browser no custom getter values are displayed because arrow triggers "Runtime.getProperties" and we are getting exception caused by casting string to integer in RuntimeGetPropertiesInternal.

Goal:
both in VS and Browser display the accessor in a form of values, not an expendable function, so like in Console App:
```
{
    "value": {
      "type": "object",
      "value": null,
      "description": "Count = 2",
      "className": "System.Collections.Generic.List<int>",
      "objectId": "dotnet:object:3"
    },
    "writable": false,
    "isOwn": true,
    "name": "list"
  }
```

### PR DESCRIPTION
**Pull request by thaystg**
Implementing support on running getters using Runtime.GetProperties as it's done by CDP.

Behavior on VS (not related to this PR)
image

Bahavior on Chrome (using this PR)
image

Fixes #62774

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs [hunk 1]
```diff
@@ -61,6 +61,8 @@ internal class DotnetObjectId
     {
         public string Scheme { get; }
         public string Value { get; }
+        public string SubScheme { get; }
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:64]: I think it would be useful to add a deconstructor which returns `int` values?
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct#user-defined-types

```sharp
public void Deconstruct(out string scheme, out int value, out string subscheme, out int? subvalue)
{..}
```

.. and use it as (example):
```csharp
var (_, value, subscheme, _) = dotnetObjectId;
```

`int value` - so the callers don't have to worry about `int.Parse` failing. And IIUC, the `string value` should always parse as an int.

And `int? subValue as a `null` value would indicate a missing value.

File: src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs [hunk 2]
```diff
@@ -73,20 +75,22 @@ public static bool TryParse(string id, out DotnetObjectId objectId)
...
-        public DotnetObjectId(string scheme, string value)
+        public DotnetObjectId(string scheme, string value, string subscheme = "", string subvalue = "")
         {
             Scheme = scheme;
             Value = value;
+            SubScheme = subscheme;
+            SubValue = subvalue;
         }
 
         public override string ToString() => $"dotnet:{Scheme}:{Value}";
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:96]: This should be updated too

File: src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs [hunk 3]
```diff
@@ -73,20 +75,22 @@ public static bool TryParse(string id, out DotnetObjectId objectId)
...
                 return false;
 
-            objectId = new DotnetObjectId(parts[1], parts[2]);
+            objectId = new DotnetObjectId(parts[1], parts[2], parts.Length > 3 ? parts[3] : "", parts.Length > 3 ? parts[4] : "");
 
             return true;
         }
 
-        public DotnetObjectId(string scheme, string value)
+        public DotnetObjectId(string scheme, string value, string subscheme = "", string subvalue = "")
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:88]: wouldn't `null` be better default values for these?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 4]
```diff
@@ -1537,6 +1537,13 @@ public async Task<JObject> InvokeMethod(ArraySegment<byte> valueTypeBuffer, int
             return await CreateJObjectForVariableValue(retDebuggerCmdReader, varName, false, -1, false, token);
         }
 
+        public async Task<JObject> InvokeMethodInObject(int objectId, int methodId, string varName, CancellationToken token)
+        {
+            using var commandParamsObjWriter = new MonoBinaryWriter();
+            commandParamsObjWriter.Write(ElementType.Class, objectId);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1543]: Would this work for structs too?

File: src/mono/wasm/debugger/DebuggerTestSuite/GetPropertiesTests.cs [hunk 5]
```diff
@@ -350,9 +350,9 @@ public async Task GetObjectValueWithInheritance()
                 j = TNumber(20),
                 i = TNumber(50),
                 k = TNumber(30),
-                GetJ = TGetter("GetJ"),
-                GetI = TGetter("GetI"),
-                GetK = TGetter("GetK")
+                GetJ = TGetter("GetJ", TNumber(20)),
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/GetPropertiesTests.cs:353]: Should other tests with `TGetter` also be updated, like the datetime ones?

File: src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs (hunk 1 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:64]: Also, we should maybe use an enum for this, even if it has only one value `MethodId` to start with. That would avoid callers having to check for `== "methodId"`, and having any typos.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 6]
```diff
@@ -688,7 +688,14 @@ internal async Task<JToken> RuntimeGetPropertiesInternal(SessionId id, DotnetObj
                     case "array":
                         return await context.SdbAgent.GetArrayValues(int.Parse(objectId.Value), token);
                     case "object":
+                    {
+                        if (objectId.SubScheme == "methodId") //getter
+                        {
+                            var objRet = await context.SdbAgent.InvokeMethodInObject(int.Parse(objectId.Value), int.Parse(objectId.SubValue), "", token);
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:694]: What about moving the call: *InvokeMethodInObject()* into https://github.com/dotnet/runtime/blob/09bb80e003b09ed5f451e2029ea0bb29e65c42a0/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L1601? This way we will avoid double clicking (in Console App the *subScheme* values are unfolded directly by a single call on *getProperties*, no need for double call). 
I tried to move the function there but so far I didn't get the right result - it seems as if I was getting into infinite loop or something. Maybe that's the reason why someone used this condition on *isAutoExpandable* but if fixing it was possible then it would be prefect.

**Review by ilonatommy — CHANGES_REQUESTED** [review]

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs (hunk 6 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:694]: The reason for infinite loop in objects: we are calling GetObjectValues => CreateJObjectForVariableValue => CreateJObjectForObject => GetValueFromDebuggerDisplayAttribute => GetObjectValues. Can we avoid it somehow?

File: src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs [hunk 7]
```diff
@@ -73,20 +75,22 @@ public static bool TryParse(string id, out DotnetObjectId objectId)
             if (!id.StartsWith("dotnet:"))
                 return false;
 
-            string[] parts = id.Split(":", 3);
+            string[] parts = id.Split(":", 5);
 
             if (parts.Length < 3)
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:80]: Please, change to:
```
if (parts.Length < 3 || parts.Length == 4)
```
because when running *DebuggerTests.ArrayTests.InvalidArrayId* we are passing 4 part ID: 
dotnet:array:{ "arrayId": 234980 }. 
After split we are left with 4 elements so the condition is false and we are reaching for non-existing element: parts[4] in the following lines. Without this change the test is failing.

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:80]: I would suggest doing something like https://github.com/dotnet/runtime/blob/release/5.0/src/mono/wasm/runtime/library_mono.js#L508-L512 . 3 parts, `dotnet`, `scheme`, and the `rest`. How to parse the `rest` part would depend on the scheme.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 4 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1543]: No.

**Review by ilonatommy — APPROVED** [review]
