### PR TITLE
Fix loading component when application was started with `dotnet` instead of apphost

### LINKED ISSUE #42745: Using dotnet instead of apphost causes managed component load failure
This was discovered on macOS when trying to load a managed component using nethost from a console application.

Repro:
1) Create a console application.
    - In project file, set `UseAppHost` to `false`.
    - Note that `UseAppHost` is `false` by default on macOS.
1) Create a class library.
1) Add a reference to [DNNE](https://github.com/AaronRobinsonMSFT/DNNE) in the class library project.
1) Create a native export in the class library:
    ```CSharp
     [UnmanagedCallersOnly(EntryPoint = "sumi")]
     public static int Sum(int a, int b)
     {
         return a + b;
     }
     ```
1) Consume the native export from the application:
    ```CSharp
    [DllImport("ClassLibrary", EntryPoint = "sumi")]
    static extern int Sum(int a, int b);
    ```

When not using the AppHost loading the class library with the native exports via nethost fails to reactivate the runtime a second time.

```
    frame #1: 0x000000010113c55f libhostpolicy.dylib`corehost_init(hostpolicy_init=0x00000001011bc3f0, argc=0, argv=0x0000000000000000, location="corehost_initialize", args=0x00007ffeefbfdb80) at hostpolicy.cpp:347:10
    frame #2: 0x000000010113d740 libhostpolicy.dylib`corehost_libhost_init(hostpolicy_init=0x00000001011bc3f0, location="corehost_initialize", args=0x00007ffeefbfdb80) at hostpolicy.cpp:449:12
    frame #3: 0x000000010113da2a libhostpolicy.dylib`::corehost_initialize(init_request=0x00007ffeefbfde28, options=2147483649, context_contract=0x00007ffeefbfdde0) at hostpolicy.cpp:701:14
    frame #4: 0x000000010045e924 libhostfxr.dylib`(anonymous namespace)::create_context_common(hostpolicy_contract=0x00000001002065e8, host_interface=0x0000000000000000, init_request=0x00007ffeefbfde28, initialization_options=2147483649, already_loaded=true, hostpolicy_context_contract=0x00007ffeefbfdde0) at host_context.cpp:39:22
    frame #5: 0x000000010045ec8f libhostfxr.dylib`host_context_t::create_secondary(hostpolicy_contract=0x00000001002065e8, config_properties=size=0, initialization_options=1, context=0x00007ffeefbfdfa8) at host_context.cpp:88:14
    frame #6: 0x0000000100434478 libhostfxr.dylib`fx_muxer_t::initialize_for_runtime_config(host_info=0x00007ffeefbfe068, runtime_config_path="/Users/aaronrrobinson/src/runtimelab/DllImportGenerator/Demo/bin/Debug/net5.0/NativeExports.runtimeconfig.json", host_context_handle=0x00007ffeefbfe0f8) at fx_muxer.cpp:792:14
    frame #7: 0x000000010042cdab libhostfxr.dylib`::hostfxr_initialize_for_runtime_config(runtime_config_path="/Users/aaronrrobinson/src/runtimelab/DllImportGenerator/Demo/bin/Debug/net5.0/NativeExports.runtimeconfig.json", parameters=0x0000000000000000, host_context_handle=0x00007ffeefbfe0f8) at hostfxr.cpp:492:12
```

`hostpolicy` code returning `false`:
https://github.com/dotnet/runtime/blob/627f13336d51b466bc4ee00dfbbc2328f6244b29/src/installer/corehost/cli/hostpolicy/args.cpp#L81-L85 

/cc @vitek-karas @elinor-fung

### PR DESCRIPTION
**Pull request by elinor-fung**
`hostpolicy` maintains global initialization info - including the mode (e.g. `muxer`, `apphost`, `libhost`) - based on the way it was first initialized through `corehost_load`. This information is used in `corehost_initialize` to create a context (`hostpolicy_context_t`) for starting the runtime.

When running an application using `dotnet` and then loading a component, as part of loading the component, we would parse arguments for creating the context in `muxer` mode (since the application was started with `dotnet`), but using arguments that would be expected in `libhost`. The argument parsing is only needed for actually creating a `hostpolicy_context`. There can only be one context, so the argument parsing is just extra work and not necessary if a context already exists.

- Don't try to parse arguments needed for creating a context until we actually need to create the context
- Explicitly error on invalid startup info in `hostfxr_main_startupinfo` and `hostfxr_main_bundle_startupinfo`
  - We were always failing in this case with an AV in `host_startup_info_t` constructor. This makes it log and return invalid arg instead.
- Update tests for native hosting to imitate running in `muxer` mode
  - Moved the inline data for tests cases for `HostContext.CompatibilityCheck_Frameworks` to a member function. They were getting a bit long / hard to read in my opinion.

Fixes #42745

cc @AaronRobinsonMSFT @jkoritzinsky This should allow us to run our integration tests for the P/Invoke source generator through `dotnet test` on non-Windows.

### CODE REVIEW

File: src/installer/corehost/cli/test/nativehost/host_context_test.h [hunk 1]
```diff
@@ -57,6 +57,7 @@ namespace host_context_test
         const pal::char_t *config_path,
         int argc,
         const pal::char_t *argv[],
+        bool as_dotnet,
```
Comment (AaronRobinsonMSFT) [inline src/installer/corehost/cli/test/nativehost/host_context_test.h:60]: Can we instead call this `launch_as_if_dotnet`? I assume that is the intent of this statement. Perhaps a comment would be sufficient. The statement of `as_dotnet` initially implied to me this isn't a .NET scenario rather than meaning the `dotnet` binary.

**Review by AaronRobinsonMSFT — COMMENTED** [review]
LGTM

File: src/installer/corehost/cli/test/nativehost/host_context_test.h (hunk 1 above)
Comment (elinor-fung) [reply src/installer/corehost/cli/test/nativehost/host_context_test.h]: Renamed to `launch_as_if_dotnet` and added a comment.

File: src/installer/corehost/cli/hostpolicy/hostpolicy.cpp [hunk 2]
```diff
@@ -708,7 +737,7 @@ SHARED_API int HOSTPOLICY_CALLTYPE corehost_initialize(const corehost_initialize
     // Trace entry point information and initialize args using previously set init information.
     // This function does not modify any global state.
     arguments_t args;
```
Comment (mateoatr) [inline src/installer/corehost/cli/hostpolicy/hostpolicy.cpp:739]: I think this is no longer needed.

**Review by mateoatr — APPROVED** [review]

File: src/installer/corehost/cli/hostpolicy/hostpolicy.cpp [hunk 3]
```diff
@@ -386,18 +408,19 @@ int corehost_main_init(
         }
     }
 
-    return corehost_init(hostpolicy_init, argc, argv, location, args);
+    trace_corehost_init(hostpolicy_init, argc, argv, location);
+    return StatusCode::Success;
```
Comment (mateoatr) [inline src/installer/corehost/cli/hostpolicy/hostpolicy.cpp:412]: Should we call `parse_arguments` before returing?

File: src/installer/corehost/cli/hostpolicy/hostpolicy.cpp [hunk 4]
```diff
@@ -410,13 +433,18 @@ SHARED_API int HOSTPOLICY_CALLTYPE corehost_main(const int argc, const pal::char
...
     if (rc != StatusCode::Success)
         return rc;
 
     if (g_init.host_command == _X("get-native-search-directories"))
     {
+        arguments_t args;
+        if (!parse_arguments(g_init, argc, argv, args))
+            return StatusCode::LibHostInvalidArgs;
+
+        args.trace();
```
Comment (vitek-karas) [inline src/installer/corehost/cli/hostpolicy/hostpolicy.cpp:446]: Can we move the `args.trace()` inside the `parse_arguments`? It seems that all places where we call `parse_arguments` also call `args.trace()`.

File: src/installer/corehost/cli/hostpolicy/hostpolicy.cpp [hunk 5]
```diff
@@ -448,15 +476,16 @@ SHARED_API int HOSTPOLICY_CALLTYPE corehost_main_with_output_buffer(const int ar
     return rc;
 }
 
-int corehost_libhost_init(const hostpolicy_init_t &hostpolicy_init, const pal::string_t& location, arguments_t& args)
+int corehost_libhost_init(const hostpolicy_init_t &hostpolicy_init, const pal::string_t& location)
```
Comment (vitek-karas) [inline src/installer/corehost/cli/hostpolicy/hostpolicy.cpp:479]: We should rename this as well - `trace_corehost_libhost_init`. It would make it consistent with the new `trace_corehost_init` and it would also nicely document that it doesn't change any state.

Comment (vitek-karas) [reply src/installer/corehost/cli/hostpolicy/hostpolicy.cpp:479]: Also - no reason to return status code - it can't fail.

**Review by vitek-karas — COMMENTED** [review]
Sorry for being late to this PR - just a couple of minor comments.
