### PR TITLE
Fix TryInvokeICustomQueryInterface exception handling

### LINKED ISSUE #117393: Crash in managed exception handler in ComWrappers in .NET 10
### Description

Talked with @jkoritzinsky offline, opening this for tracking.
I can't get an exact dump from here, but the issue is in:
- TTD trace: https://microsoft-my.sharepoint-df.com/:u:/p/sergiopedri/EX97KedFFwpInTS6T3OWLMYBg-QKV0sd9t5-Jw8AedL5jw?e=cf4pKf
- Position `26FCA73:0`

### Reproduction Steps

This repros very frequently when trying to run the Microsoft Store on .NET 10.

### Expected behavior

Should not throw an exception.

### Actual behavior

Throws an exception.

### Regression?

Yes (at least for CoreCLR).

### Known Workarounds

_No response_

### Configuration

- .NET 10 Preview 5

### Other information

_No response_

### PR DESCRIPTION
**Pull request by janvorli**
When the `InteropLibImports::TryInvokeICustomQueryInterface` is called
from a native thread and a managed exception occurs in the managed
`ICustomQueryInterface` interface implementation, the exception handling
reports that exception as unhandled because it doesn't know tha the
`InteropLibImports::TryInvokeICustomQueryInterface` catches managed
exceptions and converts them to `HRESULT`s.
This change fixes it by adding `DebuggerU2MCatchHandlerFrame` to the
`InteropLibImports::TryInvokeICustomQueryInterface`. That allows EH to
understand that the exception that flows to native code will be caught
and so it should not report it as unhandled.

Close #117393

### CODE REVIEW

File: src/coreclr/vm/interoplibinterface_comwrappers.cpp [hunk 1]
```diff
@@ -355,14 +355,18 @@ namespace InteropLibImports
...
         }
 
+        // Switch to Cooperative mode since object references
+        // are being manipulated and the catchFrame needs that so that it can push
+        // itself to the explicit frame stack.
+        GCX_COOP();
+        // Indicate to the debugger and exception handling that managed exceptions are being caught
+        // here.
+        DebuggerU2MCatchHandlerFrame catchFrame(true /* catchesAllExceptions */);
+
```
Comment (jkoritzinsky) [inline src/coreclr/vm/interoplibinterface_comwrappers.cpp:365]: Could/should we integrate this into `EX_TRY`? Or can we update the `docs/design/coreclr/botr/exceptions.md` doc to say that this is now necessary when expecting to catch an exception from managed code in the native runtime?

Comment (jkotas) [reply src/coreclr/vm/interoplibinterface_comwrappers.cpp:365]: `BEGIN_EXTERNAL_ENTRYPOINT` macro mentioned above has been historically used in situations like this one - when the code can be entered from outside.

Do all places that reference `BEGIN_EXTERNAL_ENTRYPOINT` have this problem?

Comment (janvorli) [reply src/coreclr/vm/interoplibinterface_comwrappers.cpp:365]: The problem in general only happens when the exception flowing into foreign native code with no further managed frames was thrown by managed code or thrown by native runtime and propagated through managed code before reaching that foreign native code.
The only case when this can occur is when a foreign thread code calls into the native runtime and native runtime ends up calling `CallDescrWorker` and the managed method that it calls throws. This is very rare, with this fix, we only have three places in the runtime. 

@jkotas let me check all of those to see if there are possibly other ones with this issue. But I'd prefer getting this PR in as-is before that, as it blocks our partner.
And thank you for pointing out the BEGIN_EXTERNAL_ENTRYPOINT, I was not aware of this macro before. Maybe adding the `DebuggerU2MCatchHandlerFrame` frame creation to that one is the right thing to do.

@jkoritzinsky documenting this thing in the `docs/design/coreclr/botr/exceptions.md` is a good idea, I'll do that as a follow up.

Comment (janvorli) [reply src/coreclr/vm/interoplibinterface_comwrappers.cpp:365]: I am also considering (for later) a way that would be kind of inverse. That means, instead of marking the places where the exception should be propagated to external code and not reported as unhandled, I would mark the ones where it should be reported as unhandled. That would mean `ManagedThreadBase_DispatchOuter` and `CorHost2::ExecuteAssembly`. It seems that these are the only cases when the `SfiNext` needs to report the exception as unhandled instead of propagating it further. I could e.g. create a new kind of explicit frame for this purpose.
That way, by default, managed exceptions would be propagated to native code and only in those two cases, they would not.
The reason for reporting exceptions unhandled in the `SfiNext` is to make sure the managed frame that triggered the exception is still on the stack. It ensures that when we generate a dump or run under a debugger when the unhandled exception occurs, the stack would still contain the managed frame that has thrown the exception.

**Review by jkoritzinsky — APPROVED** [review]

**Comment by janvorli** [comment]
I've created issue #117544 to track future improvements that I've mentioned in my comments above.

**Comment by jkotas** [comment]
> I've created issue https://github.com/dotnet/runtime/issues/117544 to track future improvements

I see that you have set #117544 to 11.0. We should get it fixed for .NET 10. It is not a nice to have improvements. Customers have reported other of crashes similar to this one, we have been fixing them one at a time, and it looks like we still have number of them still left. We should do a pass to fix all of them so that we do not need to deal with that in servicing.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
@janvorli the newly added test is failing native AOT outerloops. Is that expected?

**Comment by janvorli** [comment]
@MichalStrehovsky haven't noticed that. But if that fails, it means that NativeAOT has the same problem as I've fixed in coreclr.

**Comment by Sergio0694** [comment]
Oh no. Can we still make it with a fix for that before the P7 snap? Otherwise we'd be blocked for another month 🥲

Related question: how can NAOT have the same problem, if the ComWrappers implementation it used in .NET 9 was already the same, yet it was working fine and without crashing? Did something else change in .NET 10 that caused this issue there?

**Comment by janvorli** [comment]
> how can NAOT have the same problem, if the ComWrappers implementation it used in .NET 9 was already the same, yet it was working fine and without crashing? Did something else change in .NET 10 that caused this issue there?

@Sergio0694 maybe that with NativeAOT, the problematic exception doesn't occur.

**Comment by Sergio0694** [comment]
Mmh. @jkoritzinsky do you think it's possible the behavior there on NAOT would be different? I can't think of a reason why, especially now with the shared implementation, that `ICustomQueryInterface` causing issues would only kick in for CoreCLR, or alternatively that it would do the same on NAOT but then not cause that exception, if the rest of the code is the same 🤔

Just trying to understand this better.

**Comment by jkoritzinsky** [comment]
I'm betting that there was some difference in GC behavior that caused this to not repro in NAOT previously.

I think we can add an exception handler in NAOT to unblock (I don't think there's the same catch semantics in the NAOT ComWrappers impl, which should be fixed)

**Comment by janvorli** [comment]
@jkoritzinsky  I am preparing a PR with the added catch
