### PR TITLE
Fix check for equal compare operands

### LINKED ISSUE #36616: Test failure: System.Runtime.Numerics.Tests
Failure in libraries System.Runtime.Numerics.Tests: release libraries, checked coreclr with:
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStressRegs=3
```

Windows x64

E.g.,
```
build -s libs+libs.tests -runtimeConfiguration checked -c Release -arch x64 /p:ArchiveTests=true
```

(the `/p:ArchiveTests=true` is required to build the RunTests.cmd wrapper scripts)

```
C:\gh\runtime\artifacts\bin\System.Runtime.Numerics.Tests\net5.0-Release>call .\RunTests.cmd -r C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64
```

```
----- start Sun 05/17/2020 12:04:53.65 ===============  To repro directly: =====================================================
pushd C:\gh\runtime\artifacts\bin\System.Runtime.Numerics.Tests\net5.0-Release\
"C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\dotnet.exe" exec --runtimeconfig System.Runtime.Numerics.Tests.runtimeconfig.json --depsfile System.Runtime.Numerics.Tests.deps.json xunit.console.dll System.Runtime.Numerics.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

C:\gh\runtime\artifacts\bin\System.Runtime.Numerics.Tests\net5.0-Release>"C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\dotnet.exe" exec --runtimeconfig System.Runtime.Numerics.Tests.runtimeconfig.json --depsfile System.Runtime.Numerics.Tests.deps.json xunit.console.dll System.Runtime.Numerics.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
  Discovering: System.Runtime.Numerics.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Numerics.Tests (found 220 of 225 test cases)
  Starting:    System.Runtime.Numerics.Tests (parallel test collections = on, max threads = 8)
    System.Numerics.Tests.ComplexTests.Pow(real: 1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(2006,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(1303,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(1274,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(2006,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(1303,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(1274,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: 1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1
      Expected: True
      Actual:   False
      Stack Trace:
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(2006,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(1303,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(1274,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1
      Expected: True
      Actual:   False
      Stack Trace:
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(2006,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(1303,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        C:\gh\runtime\src\libraries\System.Runtime.Numerics\tests\ComplexTests.cs(1274,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
  Finished:    System.Runtime.Numerics.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Numerics.Tests  Total: 2087, Errors: 0, Failed: 4, Skipped: 0, Time: 9.513s
----- end Sun 05/17/2020 12:05:08.33 ----- exit code 1 ----------------------------------------------------------
```

@CarolEidt

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #36616

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

File: src/coreclr/src/jit/codegenlinear.cpp [hunk 1]
```diff
@@ -2382,7 +2382,8 @@ void CodeGen::genCodeForJumpTrue(GenTreeOp* jtrue)
 
 #if defined(TARGET_XARCH)
     if ((condition.GetCode() == GenCondition::FNEU) &&
-        (relop->gtGetOp1()->GetRegNum() == relop->gtGetOp2()->GetRegNum()))
+        (relop->gtGetOp1()->GetRegNum() == relop->gtGetOp2()->GetRegNum()) &&
+        !relop->gtGetOp1()->isUsedFromSpillTemp() && !relop->gtGetOp2()->isUsedFromSpillTemp())
```
Comment (CarolEidt) [inline src/coreclr/src/jit/codegenlinear.cpp:2386]: We can have the same register assigned to the two operands, even if they are not the same, if one of them is spilled and marked `RegOptional`. This was exposed by a jitStressRegs test run where the available register set is intentionally limited.

**Review by BruceForstall — APPROVED** [review]
