### PR TITLE
Do not print anything to stderr running SCD app without deps.json

### LINKED ISSUE #64606: Cannot use file stream for [*.deps.json]: No such file or directory
### Description

Why is a published app with 

	<GenerateDependencyFile>false</GenerateDependencyFile>
	<GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>

Still trying to locate the "*.deps.json" ?

How do I turn this warning off ?

### Reproduction Steps

dotnet publish -c Release -r linux-x64 --self-contained
a exe file with:

	<GenerateDependencyFile>false</GenerateDependencyFile>
	<GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>

### Expected behavior

Running with out warning about "*.deps.json"

### Actual behavior

Cannot use file stream for [*.deps.json]: No such file or directory

### Regression?

No

### Known Workarounds

Create the "*.deps.json"

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by vitek-karas**
When we're running self-contained app the `hostfxr` tries to figure out the location of `hostpolicy.dll`. This is done also by looking into the `.deps.json` for the app (which should have a record for `hostpolicy.dll` in it). If the file is missing the code will move on and find the `hostpolicy.dll` in the app's folder, but it will also print out a message to stderr.

This means that running such app will actually work, but the host outputs a message to stderr - effectively "corrupting" the app's own output.

Note that this doesn't affects framework dependent apps without `.deps.json` since they look into the framework's `.deps.json` for `hostpolicy.dll`.

Fixes https://github.com/dotnet/runtime/issues/64606

### CODE REVIEW

File: src/native/corehost/fxr/standalone/hostpolicy_resolver.cpp [hunk 1]
```diff
@@ -242,11 +242,15 @@ bool hostpolicy_resolver::try_get_dir(
...
-            resolved_deps.c_str(), _STRINGIFY(HOST_POLICY_PKG_NAME));
+        version = resolve_hostpolicy_version_from_deps(resolved_deps);
+        if (trace::is_enabled() && version.empty())
+        {
+            trace::warning(_X("Dependency manifest %s does not contain an entry for %s"),
+                resolved_deps.c_str(), _STRINGIFY(HOST_POLICY_PKG_NAME));
+        }
     }
 
     // Check if the given version of the hostpolicy exists in servicing.
```
Comment (elinor-fung) [inline src/native/corehost/fxr/standalone/hostpolicy_resolver.cpp:256]: Can probably move this under the check above, since we'll never find it if the deps didn't exist or we didn't get a version to look for.

**Review by elinor-fung — APPROVED** [review]
