### PR TITLE
Fix FnPtrTypeDesc::GetManagedClassObject

### LINKED ISSUE #82252: Assertion failed: GCHeapUtilities::GetGCHeap()->IsInFrozenSegment(obj)
Pipeline runtime-coreclr gcstress-extra
Configuration: `coreclr linux arm Checked gcstress0xc_zapdisable_heapverify1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7`

https://dev.azure.com/dnceng-public/public/_build/results?buildId=174092&view=ms.vss-test-web.build-test-results-tab&runId=3460326&paneView=debug&resultId=112277

Environment:
```
export DOTNET_TieredCompilation=0
export DOTNET_DbgEnableMiniDump=1
export DOTNET_EnableCrashReport=1
export DOTNET_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export DOTNET_GCStress=0xC
export DOTNET_HeapVerify=1
export DOTNET_ReadyToRun=0
export DOTNET_ZapDisable=1
```

Log fragment:
```
08:36:02.691 Running test: Loader/classloader/TypeGeneratorTests/TypeGeneratorTest868/Generated868/Generated868.dll
========================== Method Calling Test ==========================
========================================================================


========================== Constrained Calls Test ==========================

Assert failure(PID 21 [0x00000015], Thread: 21 [0x0015]): GCHeapUtilities::GetGCHeap()->IsInFrozenSegment(obj)
    File: /__w/1/s/src/coreclr/vm/syncblk.cpp Line: 2048
    Image: /root/helix/work/correlation/corerun

[createdump] Gathering state for process 21 corerun
[createdump] Crashing thread 00000015 signal 00000006
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.21.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.21.dmp
[createdump] Written 114569216 bytes (27971 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 251ms
[createdump] waitpid() returned successfully (wstatus 00000000)
Loader/classloader/TypeGeneratorTests/TypeGeneratorTests800-899/TypeGeneratorTests800-899.sh: line 425:    21 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Expected: 100
Actual: 134
END EXECUTION - FAILED
```

### PR DESCRIPTION
**Pull request by jkotas**
The code was missing support for allocating RuntimeType objects on frozen heap

Fixes #82252

### CODE REVIEW

File: src/coreclr/vm/typehandle.cpp [hunk 1]
```diff
@@ -349,8 +349,7 @@ bool TypeHandle::IsManagedClassObjectPinned() const
 {
     LIMITED_METHOD_DAC_CONTRACT;
 
-    // Function pointers are always mapped to typeof(IntPtr)
-    return !GetLoaderAllocator()->CanUnload() || IsFnPtrType();
+    return !GetLoaderAllocator()->CanUnload();
```
Comment (steveharter) [inline src/coreclr/vm/typehandle.cpp:352]: Missed this -- prevents FPs from being moved during GC \ causing GC holes perhaps?

File: src/coreclr/vm/typedesc.cpp [hunk 2]
```diff
@@ -522,26 +522,9 @@ OBJECTREF FnPtrTypeDesc::GetManagedClassObject()
...
-        // Only the winner can set m_hExposedClassObject from NULL.
-        LOADERHANDLE hExposedClassObject = pLoaderAllocator->AllocateHandle(refClass);
-
-        if (InterlockedCompareExchangeT(&m_hExposedClassObject, hExposedClassObject, static_cast<LOADERHANDLE>(NULL)))
-        {
-            pLoaderAllocator->FreeHandle(hExposedClassObject);
-        }
-
-        GCPROTECT_END();
+    if (m_hExposedClassObject == NULL)
```
Comment (steveharter) [inline src/coreclr/vm/typedesc.cpp:525]: I see that this pattern was recently changed to support frozen heaps, so this copy-paste above was stale.

**Review by steveharter — APPROVED** [review]
Thanks!

File: src/coreclr/vm/typehandle.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/vm/typehandle.cpp:352]: The logic in this method has to be in sync with what GetManagedClassObject returns. If it is not in sync, it will lead to all sorts of problems.

File: src/coreclr/vm/typedesc.cpp (hunk 2 above)
Comment (jkotas) [reply src/coreclr/vm/typedesc.cpp:525]: Right

**Comment by EgorBo** [comment]
Ouch, thanks! It turns out to be a FOH-related issue indeed 😞
