### PR TITLE
Fix handling of Arm32 struct with 8-byte alignment and 12-byte rounded size.

### LINKED ISSUE #46239: Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global'
[runtime-coreclr outerloop #20201218.4](https://dev.azure.com/dnceng/public/_build/results?buildId=926781)

```
    JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh [FAIL]
      
      Assert failure(PID 941 [0x000003ad], Thread: 941 [0x03ad]): Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global' (IL size 3136)
      
          File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 4143
          Image: /root/helix/work/correlation/corerun
      
      /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh: line 365:   941 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun expl_obj_1_d.dll ''
      Gathering state for process 941 corerun
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.941.dmp
      Written 50401280 bytes (12305 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs(101482,0): at JIT_Methodical._explicit_coverage_expl_obj_1_d_expl_obj_1_d_._explicit_coverage_expl_obj_1_d_expl_obj_1_d_sh()
      Output:
        
        Assert failure(PID 941 [0x000003ad], Thread: 941 [0x03ad]): Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global' (IL size 3136)
        
            File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 4143
            Image: /root/helix/work/correlation/corerun
        
        /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh: line 365:   941 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun expl_obj_1_d.dll ''
        Gathering state for process 941 corerun
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.941.dmp
        Written 50401280 bytes (12305 pages) to core file
        Dump successfully written
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh
    JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh [FAIL]
      
      Assert failure(PID 1491 [0x000005d3], Thread: 1491 [0x05d3]): Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global' (IL size 3136)
      
          File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 4143
          Image: /root/helix/work/correlation/corerun
      
      /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh: line 365:  1491 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun expl_obj_1_r.dll ''
      Gathering state for process 1491 corerun
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.1491.dmp
      Written 50298880 bytes (12280 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs(101589,0): at JIT_Methodical._explicit_coverage_expl_obj_1_r_expl_obj_1_r_._explicit_coverage_expl_obj_1_r_expl_obj_1_r_sh()
      Output:
        
        Assert failure(PID 1491 [0x000005d3], Thread: 1491 [0x05d3]): Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global' (IL size 3136)
        
            File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 4143
            Image: /root/helix/work/correlation/corerun
        
        /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh: line 365:  1491 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun expl_obj_1_r.dll ''
        Gathering state for process 1491 corerun
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.1491.dmp
        Written 50298880 bytes (12280 pages) to core file
        Dump successfully written
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh

```

### PR DESCRIPTION
**Pull request by sandreenko**
In the previous change I was using type alignment to get rounded type size and it was working well except for one case:
```
    internal struct S3
    {
        [FieldOffset(0)]
        public ulong tmp1;
        [FieldOffset(8)]
        public Object tmp2;
    }
```
on arm32 it has 12 bytes size with 8-byte alignment because:
1. a struct with long requires double alignment;
2. it is not blittable because of the managed object so we are not trying to match native layout (S4 with int instead of obj takes 16);

and we end up with a type which `size % alignment != 0`.

To fix this do exactly what ABI says about type widening and extending:
```
If the argument is a composite type, its size is rounded up to the nearest multiple of the pointer size.
```
with the exception for arm64 apple primitive types and HFA<float>.

Fixes #46239.

### CODE REVIEW

**Comment by sandreenko** [comment]
Thanks @AndyAyersMS and @jkoritzinsky for the help with understanding this, could you please take a look at the change and the test? Any other cases that would be interesting to add here?

Also, @jkoritzinsky we wanted to discuss what would it take to return 16 for such a struct, because we don't expect it to be used in native/managed interactions it should live only in managed code that we control so it won't be a breaking change.
Also, is it expected that `Marshal.SizeOf(typeof(T));` works differently on Windows (passes and returns a result) and on Unix (throws exception `System.ArgumentException: Type 'Runtime_46239.S1' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed` ).

cc @dotnet/jit-contrib

File: src/coreclr/jit/compiler.h [hunk 1]
```diff
@@ -1798,26 +1797,50 @@ struct fgArgTabEntry
...
     }
 
-    void SetByteSize(unsigned byteSize, unsigned byteAlignment)
+    void SetByteSize(unsigned byteSize, bool isStruct, bool isFloatHfa)
     {
-        assert(byteAlignment != 0);
-        const unsigned alignedByteSize = roundUp(byteSize, byteAlignment);
+
+#ifdef OSX_ARM64_ABI
+        unsigned roudnedByteSize;
```
Comment (AndyAyersMS) [inline src/coreclr/jit/compiler.h:1804]: Typo (here and below)
```suggestion
        unsigned roundedByteSize;
```

File: src/tests/JIT/Regression/JitBlue/Runtime_46239/Runtime_46239.cs [hunk 2]
```diff
@@ -0,0 +1,193 @@
+using System;
```
Comment (AndyAyersMS) [inline src/tests/JIT/Regression/JitBlue/Runtime_46239/Runtime_46239.cs:1]: Add the standard header.

**Review by AndyAyersMS — APPROVED** [review]
Looks good, just two small cleanup comments.

File: src/tests/JIT/Regression/JitBlue/Runtime_46239/Runtime_46239.cs (hunk 2 above)
Comment (sandreenko) [reply src/tests/JIT/Regression/JitBlue/Runtime_46239/Runtime_46239.cs]: Fixed, thanks
