### PR TITLE
Don't allow preinitialization to skip dataflow

### LINKED ISSUE #97286: Type preinitialization skips dataflow analysis
There's an assignment to a DAM member but since we interpret the cctor instead of executing it, it bypasses the DAM annotations: this program will nullref at runtime.

This is a regression in 9.0.

```csharp
using System;
using System.Diagnostics.CodeAnalysis;

Preinit.TheType.GetMethod("TheMethod").Invoke(null, []);

class Preinit
{
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods)]
    public static Type TheType = typeof(Preinit);

    public static void TheMethod() => Console.WriteLine("Hello");
}
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #97286.

This just aborts preinitialization if we see dataflow might be involved. It's a conservative fix. We don't have a good spot to communicate dataflow need (e.g. _everything_ from the cctor could potentially be optimized away if the codegen inlines that knowledge).

Cc @dotnet/ilc-contrib

### CODE REVIEW

File: src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs [hunk 1]
```diff
@@ -1310,15 +1311,17 @@ public static void Run()
 
 class TestIndirectLoads
 {
-    static unsafe U Read<T, U>(T val) where T : unmanaged where U : unmanaged
```
Comment (MichalStrehovsky) [inline src/tests/nativeaot/SmokeTests/Preinitialization/Preinitialization.cs:1313]: Roslyn generates this as `new()` constraint which is very unfortunate because it requires dataflow.

**Review by jkotas — APPROVED** [review]
Thanks
