### PR TITLE
Fix ARM64 unsigned div by const perf regression

### LINKED ISSUE #54166: [Perf] Regressions in Integer Formatting
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a](https://github.com/dotnet/runtime/commit/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a)
Compare | [8fb2eb53f75971ce492f14bebb93ed7a236bcd6e](https://github.com/dotnet/runtime/commit/8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a...8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)

### Regressions in System.Tests.Perf_Int32

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ToString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_Int32.ToString(value%3a%202147483647).html>) | 24.70 ns | 34.44 ns | 1.39 | 0.21 | | |
[TryFormat - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_Int32.TryFormat(value%3a%202147483647).html>) | 19.39 ns | 21.12 ns | 1.09 | 0.17 | | |

graph
graph
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_Int32.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Int32*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-09b0e867-d918-493d-8f94-1ed57e7c008ca6480ee76424784ac/d17f1bb6-cf7d-43e9-82f4-d7b958031de9.zip?sv=2019-07-07&se=2021-06-17T14%3A13%3A59Z&sr=c&sp=rl&sig=4y%2FfMT1VANdqOiV7YklImmCgyUNsLeW1vgMV5YQWdCo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9a10712e-55d4-4710-8cc4-a7764f27676722b004842d841ee99/e20c8586-25be-495a-9117-95dd22f83a6e.zip?sv=2019-07-07&se=2021-06-17T20%3A36%3A56Z&sr=c&sp=rl&sig=QKoTBO7ix54nB3Ag0uJir2PLiqWfCxIxMffTt5tLT4w%3D>)

#### System.Tests.Perf_Int32.ToString(value: 2147483647)

```log

```
#### System.Tests.Perf_Int32.TryFormat(value: 2147483647)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a](https://github.com/dotnet/runtime/commit/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a)
Compare | [8fb2eb53f75971ce492f14bebb93ed7a236bcd6e](https://github.com/dotnet/runtime/commit/8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a...8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)

### Regressions in System.Tests.Perf_UInt64

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[TryFormat - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_UInt64.TryFormat(value%3a%2012345).html>) | 10.78 ns | 12.11 ns | 1.12 | 0.13 | | |

graph
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_UInt64.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_UInt64*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-09b0e867-d918-493d-8f94-1ed57e7c008ca6480ee76424784ac/d17f1bb6-cf7d-43e9-82f4-d7b958031de9.zip?sv=2019-07-07&se=2021-06-17T14%3A13%3A59Z&sr=c&sp=rl&sig=4y%2FfMT1VANdqOiV7YklImmCgyUNsLeW1vgMV5YQWdCo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9a10712e-55d4-4710-8cc4-a7764f27676722b004842d841ee99/e20c8586-25be-495a-9117-95dd22f83a6e.zip?sv=2019-07-07&se=2021-06-17T20%3A36%3A56Z&sr=c&sp=rl&sig=QKoTBO7ix54nB3Ag0uJir2PLiqWfCxIxMffTt5tLT4w%3D>)

#### System.Tests.Perf_UInt64.TryFormat(value: 12345)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a](https://github.com/dotnet/runtime/commit/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a)
Compare | [8fb2eb53f75971ce492f14bebb93ed7a236bcd6e](https://github.com/dotnet/runtime/commit/8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a...8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)

### Regressions in System.Tests.Perf_Version

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[TryFormatL - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_Version.TryFormatL.html>) | 96.02 ns | 103.50 ns | 1.08 | 0.15 | | |

graph
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_Version.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Version*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-09b0e867-d918-493d-8f94-1ed57e7c008ca6480ee76424784ac/d17f1bb6-cf7d-43e9-82f4-d7b958031de9.zip?sv=2019-07-07&se=2021-06-17T14%3A13%3A59Z&sr=c&sp=rl&sig=4y%2FfMT1VANdqOiV7YklImmCgyUNsLeW1vgMV5YQWdCo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9a10712e-55d4-4710-8cc4-a7764f27676722b004842d841ee99/e20c8586-25be-495a-9117-95dd22f83a6e.zip?sv=2019-07-07&se=2021-06-17T20%3A36%3A56Z&sr=c&sp=rl&sig=QKoTBO7ix54nB3Ag0uJir2PLiqWfCxIxMffTt5tLT4w%3D>)

#### System.Tests.Perf_Version.TryFormatL

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [28e63279342bd2f6ca43442d864f487613a53bc9](https://github.com/dotnet/runtime/commit/28e63279342bd2f6ca43442d864f487613a53bc9)
Compare | [d49bcbe0441f5c954cddcbe28a222eb34917bcaf](https://github.com/dotnet/runtime/commit/d49bcbe0441f5c954cddcbe28a222eb34917bcaf)
Diff | [Diff](https://github.com/dotnet/runtime/compare/28e63279342bd2f6ca43442d864f487613a53bc9...d49bcbe0441f5c954cddcbe28a222eb34917bcaf)

### Regressions in System.Tests.Perf_UInt32

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ToString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_UInt32.ToString(value%3a%204294967295).html>) | 22.92 ns | 25.28 ns | 1.10 | 0.24 | | |
[TryFormat - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_UInt32.TryFormat(value%3a%204294967295).html>) | 17.54 ns | 20.77 ns | 1.18 | 0.01 | | |

graph
graph
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_UInt32.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_UInt32*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-f2d20920-0bc0-4bb9-9d1d-8d34eb6d47c6c216c972f62465292/99063571-1fe1-4096-8569-59b2e86938a4.zip?sv=2019-07-07&se=2021-06-18T18%3A28%3A15Z&sr=c&sp=rl&sig=CuaIYn6sp0EYxmgqo1u%2FF5V2IjlpjtZgzufOov%2B2mm0%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-f7b88df2-2a36-4dbd-a714-925cb640fe3c2d7e9db63214e9fbe/bc83e467-c725-44b8-a0ae-9c7b252f25ee.zip?sv=2019-07-07&se=2021-06-19T01%3A07%3A40Z&sr=c&sp=rl&sig=jgPCNxUQFidzmxgWf%2BJL4S1pK8dKXjvRl2T99A2SlQw%3D>)

#### System.Tests.Perf_UInt32.ToString(value: 4294967295)

```log

```
#### System.Tests.Perf_UInt32.TryFormat(value: 4294967295)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by pentp**
This fixes #54166. This is the alternative version of #57372 that just improves `GT_MUL` codegen for arm64. Diffs are identical.

Diff: https://www.diffchecker.com/9mkVf4se
Diff with baseline (no #52893): https://www.diffchecker.com/x2SRZJvW

Unfortunately this doesn't yet solve #47490, probably because the operand nodes are extended to 64-bit earlier.

cc @AndyAyersMS @echesakovMSFT

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
CC @AndyAyersMS please review the code.

**Comment by AndyAyersMS** [comment]
Changes look reasonable to me, but I'll defer to @echesakov here...

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -5254,7 +5254,11 @@ bool Lowering::LowerUnsignedDivOrMod(GenTreeOp* divMod)
             BlockRange().InsertBefore(divMod, preShiftBy, adjustedDividend);
             firstNode = preShiftBy;
         }
-        else if (type != TYP_I_IMPL)
+        else if (type != TYP_I_IMPL
+#ifdef TARGET_ARM64
+                 && !simpleMul
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:5259]:
```suggestion
                 && !simpleMul // On ARM64 we will use a 32x32->64 bit multiply as that's faster.
```

File: src/coreclr/jit/lower.cpp [hunk 2]
```diff
@@ -5268,7 +5272,7 @@ bool Lowering::LowerUnsignedDivOrMod(GenTreeOp* divMod)
             adjustedDividend->SetRegNum(REG_RAX);
 #endif
 
-        divisor->gtType = TYP_I_IMPL;
+        divisor->gtType = simpleMul ? TYP_INT : TYP_I_IMPL;
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:5275]: This will only happen for this ARM64 case, right? The Jit doesn't expect `TYP_INT`/`TYP_LONG` mixes in binary operands.

File: src/coreclr/jit/codegenarm64.cpp [hunk 3]
```diff
@@ -1853,8 +1853,17 @@ void CodeGen::genCodeForBinary(GenTreeOp* treeNode)
...
-    regNumber r = emit->emitInsTernary(ins, emitActualTypeSize(treeNode), treeNode, op1, op2);
+    // UMULL/SMULL is twice as fast for 32*32->64bit MUL
+    if (oper == GT_MUL && EA_SIZE(attr) == EA_8BYTE && !varTypeIsFloating(treeNode->TypeGet()) &&
+        EA_SIZE(emitActualTypeSize(op1)) == EA_4BYTE && EA_SIZE(emitActualTypeSize(op2)) == EA_4BYTE)
+    {
+        ins  = (treeNode->gtFlags & GTF_UNSIGNED) ? INS_umull : INS_smull;
+        attr = EA_4BYTE;
+    }
+
+    regNumber r = emit->emitInsTernary(ins, attr, treeNode, op1, op2);
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenarm64.cpp:1866]:
```suggestion
    // UMULL/SMULL is twice as fast for 32*32->64bit MUL.
    if ((oper == GT_MUL) && (targetType == TYP_LONG) && genActualTypeIsInt(op1) && genActualTypeIsInt(op2))
    {
        ins  = treeNode->IsUnsigned() ? INS_umull : INS_smull;
        attr = EA_4BYTE;
    }

    regNumber r = emit->emitInsTernary(ins, attr, treeNode, op1, op2);
```
Just a suggestion on how to write the same code using a bit terser APIs.

**Review by SingleAccretion — COMMENTED** [review]
I suppose this is a low risk change for .NET 6, but longer term I'd think we'd want to support `GT_MUL_LONG` in ARM64 codegen directly and use the existing methods to detect it in lowering.

**Comment by echesakovMSFT** [comment]
I ran `System.Tests.Perf_Int32*` benchmarks on my Surface Pro X.

Here are the results (baseline is e0f6071a0f8e6d8ce9ec788ef1444fe631efd664):

``` ini

BenchmarkDotNet=v0.12.1.1466-nightly, OS=Windows 10.0.19043
Microsoft SQ2 3.15 GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.100-preview.7.21379.14
  [Host]     : .NET 5.0.9 (5.0.921.35908), Arm64 RyuJIT
  Job-TRWEYK : .NET 6.0.0 (42.42.42.42424), Arm64 RyuJIT
  Job-OBGLQV : .NET 6.0.0 (42.42.42.42424), Arm64 RyuJIT
  Job-COTIHO : .NET 6.0.0 (42.42.42.42424), Arm64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:DebugType=portable  IterationTime=250.0000 ms  
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1  

```
|       Method |        Job |                                Toolchain |       value |      Mean |     Error |    StdDev |    Median |       Min |       Max | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |----------- |----------------------------------------- |------------ |----------:|----------:|----------:|----------:|----------:|----------:|------:|--------:|-------:|------:|------:|----------:|
|     **ToString** | **Job-TRWEYK** | **\baseline-no-52893\Core_Root\corerun.exe** | **-2147483648** | **39.744 ns** | **0.1694 ns** | **0.1414 ns** | **39.681 ns** | **39.605 ns** | **40.040 ns** |  **0.99** |    **0.00** | **0.0228** |     **-** |     **-** |      **48 B** |
|     ToString | Job-OBGLQV |          \baseline\Core_Root\corerun.exe | -2147483648 | 40.222 ns | 0.0537 ns | 0.0448 ns | 40.223 ns | 40.145 ns | 40.325 ns |  1.00 |    0.00 | 0.0229 |     - |     - |      48 B |
|     ToString | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 37.945 ns | 0.2733 ns | 0.2422 ns | 37.874 ns | 37.714 ns | 38.488 ns |  0.94 |    0.01 | 0.0228 |     - |     - |      48 B |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|  ToStringHex | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 24.111 ns | 0.3061 ns | 0.2556 ns | 24.056 ns | 23.857 ns | 24.774 ns |  0.93 |    0.01 | 0.0191 |     - |     - |      40 B |
|  ToStringHex | Job-OBGLQV |          \baseline\Core_Root\corerun.exe | -2147483648 | 26.056 ns | 0.0165 ns | 0.0138 ns | 26.057 ns | 26.034 ns | 26.083 ns |  1.00 |    0.00 | 0.0191 |     - |     - |      40 B |
|  ToStringHex | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 24.636 ns | 0.2250 ns | 0.1995 ns | 24.537 ns | 24.481 ns | 25.101 ns |  0.95 |    0.01 | 0.0191 |     - |     - |      40 B |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|        Parse | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 27.414 ns | 0.0657 ns | 0.0582 ns | 27.429 ns | 27.272 ns | 27.487 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|        Parse | Job-OBGLQV |          \baseline\Core_Root\corerun.exe | -2147483648 | 27.517 ns | 0.0786 ns | 0.0735 ns | 27.518 ns | 27.391 ns | 27.640 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|        Parse | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 27.487 ns | 0.1171 ns | 0.1038 ns | 27.449 ns | 27.369 ns | 27.676 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     TryParse | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 25.944 ns | 0.0910 ns | 0.0806 ns | 25.918 ns | 25.850 ns | 26.121 ns |  0.99 |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-OBGLQV |          \baseline\Core_Root\corerun.exe | -2147483648 | 26.296 ns | 0.0755 ns | 0.0589 ns | 26.288 ns | 26.224 ns | 26.419 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 26.364 ns | 0.1250 ns | 0.1044 ns | 26.349 ns | 26.192 ns | 26.617 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|    ParseSpan | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 27.809 ns | 0.1477 ns | 0.1309 ns | 27.744 ns | 27.704 ns | 28.087 ns |  1.01 |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-OBGLQV |          \baseline\Core_Root\corerun.exe | -2147483648 | 27.489 ns | 0.0464 ns | 0.0388 ns | 27.481 ns | 27.415 ns | 27.568 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 27.995 ns | 0.0504 ns | 0.0446 ns | 27.987 ns | 27.936 ns | 28.093 ns |  1.02 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|    TryFormat | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 29.781 ns | 0.0288 ns | 0.0270 ns | 29.782 ns | 29.726 ns | 29.827 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-OBGLQV |          \baseline\Core_Root\corerun.exe | -2147483648 | 29.698 ns | 0.0301 ns | 0.0251 ns | 29.691 ns | 29.654 ns | 29.739 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 28.576 ns | 0.0633 ns | 0.0561 ns | 28.584 ns | 28.442 ns | 28.663 ns |  0.96 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
| TryParseSpan | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 27.286 ns | 0.0451 ns | 0.0377 ns | 27.281 ns | 27.240 ns | 27.373 ns |  1.04 |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-OBGLQV |          \baseline\Core_Root\corerun.exe | -2147483648 | 26.344 ns | 0.0931 ns | 0.0777 ns | 26.326 ns | 26.233 ns | 26.529 ns |  1.00 |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 27.561 ns | 0.0279 ns | 0.0233 ns | 27.562 ns | 27.517 ns | 27.601 ns |  1.05 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|        **Parse** | **Job-TRWEYK** | **\baseline-no-52893\Core_Root\corerun.exe** |       **12345** | **18.392 ns** | **0.0723 ns** | **0.0641 ns** | **18.413 ns** | **18.284 ns** | **18.480 ns** |  **0.99** |    **0.01** |      **-** |     **-** |     **-** |         **-** |
|        Parse | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |       12345 | 18.542 ns | 0.1281 ns | 0.1136 ns | 18.549 ns | 18.298 ns | 18.708 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|        Parse | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 18.602 ns | 0.1030 ns | 0.0963 ns | 18.594 ns | 18.465 ns | 18.762 ns |  1.00 |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     TryParse | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |       12345 | 18.210 ns | 0.0423 ns | 0.0354 ns | 18.205 ns | 18.161 ns | 18.275 ns |  1.07 |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |       12345 | 16.967 ns | 0.0498 ns | 0.0416 ns | 16.980 ns | 16.890 ns | 17.014 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 16.943 ns | 0.0839 ns | 0.0743 ns | 16.931 ns | 16.854 ns | 17.088 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|    ParseSpan | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |       12345 | 18.727 ns | 0.0993 ns | 0.0881 ns | 18.718 ns | 18.561 ns | 18.920 ns |  0.99 |    0.01 |      - |     - |     - |         - |
|    ParseSpan | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |       12345 | 18.973 ns | 0.1717 ns | 0.1606 ns | 18.987 ns | 18.654 ns | 19.276 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 18.871 ns | 0.0787 ns | 0.0736 ns | 18.861 ns | 18.739 ns | 19.000 ns |  0.99 |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
| TryParseSpan | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |       12345 | 17.014 ns | 0.0616 ns | 0.0546 ns | 16.999 ns | 16.964 ns | 17.134 ns |  0.98 |    0.01 |      - |     - |     - |         - |
| TryParseSpan | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |       12345 | 17.426 ns | 0.0763 ns | 0.0677 ns | 17.403 ns | 17.310 ns | 17.528 ns |  1.00 |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 17.415 ns | 0.1091 ns | 0.0967 ns | 17.371 ns | 17.300 ns | 17.644 ns |  1.00 |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     **ToString** | **Job-TRWEYK** | **\baseline-no-52893\Core_Root\corerun.exe** |           **4** |  **2.244 ns** | **0.0037 ns** | **0.0033 ns** |  **2.244 ns** |  **2.239 ns** |  **2.251 ns** |  **1.17** |    **0.01** |      **-** |     **-** |     **-** |         **-** |
|     ToString | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |           4 |  1.926 ns | 0.0092 ns | 0.0082 ns |  1.923 ns |  1.917 ns |  1.948 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|     ToString | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |           4 |  2.559 ns | 0.0045 ns | 0.0042 ns |  2.558 ns |  2.554 ns |  2.569 ns |  1.33 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|  ToStringHex | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |           4 | 16.723 ns | 0.0333 ns | 0.0278 ns | 16.724 ns | 16.673 ns | 16.767 ns |  0.96 |    0.00 | 0.0114 |     - |     - |      24 B |
|  ToStringHex | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |           4 | 17.433 ns | 0.0233 ns | 0.0207 ns | 17.434 ns | 17.406 ns | 17.474 ns |  1.00 |    0.00 | 0.0115 |     - |     - |      24 B |
|  ToStringHex | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 17.159 ns | 0.0298 ns | 0.0264 ns | 17.143 ns | 17.133 ns | 17.213 ns |  0.98 |    0.00 | 0.0115 |     - |     - |      24 B |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|    TryFormat | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |           4 |  4.325 ns | 0.0141 ns | 0.0132 ns |  4.322 ns |  4.301 ns |  4.356 ns |  1.00 |    0.01 |      - |     - |     - |         - |
|    TryFormat | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |           4 |  4.314 ns | 0.0305 ns | 0.0271 ns |  4.314 ns |  4.262 ns |  4.362 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |           4 |  4.355 ns | 0.0801 ns | 0.0669 ns |  4.365 ns |  4.139 ns |  4.404 ns |  1.01 |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     **ToString** | **Job-TRWEYK** | **\baseline-no-52893\Core_Root\corerun.exe** |       **12345** | **15.389 ns** | **0.0222 ns** | **0.0196 ns** | **15.386 ns** | **15.364 ns** | **15.422 ns** |  **0.98** |    **0.00** | **0.0153** |     **-** |     **-** |      **32 B** |
|     ToString | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |       12345 | 15.712 ns | 0.0332 ns | 0.0294 ns | 15.706 ns | 15.685 ns | 15.775 ns |  1.00 |    0.00 | 0.0153 |     - |     - |      32 B |
|     ToString | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 15.967 ns | 0.0312 ns | 0.0244 ns | 15.961 ns | 15.944 ns | 16.017 ns |  1.02 |    0.00 | 0.0152 |     - |     - |      32 B |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|  ToStringHex | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |       12345 | 20.870 ns | 0.0241 ns | 0.0188 ns | 20.866 ns | 20.850 ns | 20.909 ns |  0.99 |    0.00 | 0.0152 |     - |     - |      32 B |
|  ToStringHex | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |       12345 | 21.097 ns | 0.0186 ns | 0.0155 ns | 21.099 ns | 21.070 ns | 21.128 ns |  1.00 |    0.00 | 0.0153 |     - |     - |      32 B |
|  ToStringHex | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 21.499 ns | 0.0833 ns | 0.0738 ns | 21.470 ns | 21.426 ns | 21.669 ns |  1.02 |    0.00 | 0.0153 |     - |     - |      32 B |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|    TryFormat | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |       12345 |  8.604 ns | 0.0245 ns | 0.0229 ns |  8.600 ns |  8.567 ns |  8.643 ns |  0.94 |    0.01 |      - |     - |     - |         - |
|    TryFormat | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |       12345 |  9.157 ns | 0.0546 ns | 0.0484 ns |  9.137 ns |  9.092 ns |  9.282 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |       12345 |  7.470 ns | 0.0449 ns | 0.0420 ns |  7.451 ns |  7.432 ns |  7.549 ns |  0.82 |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     **ToString** | **Job-TRWEYK** | **\baseline-no-52893\Core_Root\corerun.exe** |  **2147483647** | **24.385 ns** | **0.0255 ns** | **0.0213 ns** | **24.385 ns** | **24.357 ns** | **24.420 ns** |  **0.93** |    **0.00** | **0.0229** |     **-** |     **-** |      **48 B** |
|     ToString | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |  2147483647 | 26.237 ns | 0.0528 ns | 0.0441 ns | 26.229 ns | 26.177 ns | 26.332 ns |  1.00 |    0.00 | 0.0230 |     - |     - |      48 B |
|     ToString | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 23.810 ns | 0.0387 ns | 0.0362 ns | 23.806 ns | 23.769 ns | 23.871 ns |  0.91 |    0.00 | 0.0229 |     - |     - |      48 B |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|  ToStringHex | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 31.299 ns | 0.0229 ns | 0.0192 ns | 31.299 ns | 31.270 ns | 31.332 ns |  0.97 |    0.00 | 0.0190 |     - |     - |      40 B |
|  ToStringHex | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |  2147483647 | 32.250 ns | 0.0377 ns | 0.0295 ns | 32.239 ns | 32.217 ns | 32.325 ns |  1.00 |    0.00 | 0.0191 |     - |     - |      40 B |
|  ToStringHex | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 32.213 ns | 0.0422 ns | 0.0395 ns | 32.201 ns | 32.169 ns | 32.308 ns |  1.00 |    0.00 | 0.0191 |     - |     - |      40 B |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|        Parse | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 27.039 ns | 0.0452 ns | 0.0423 ns | 27.036 ns | 26.962 ns | 27.121 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|        Parse | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |  2147483647 | 27.154 ns | 0.0870 ns | 0.0727 ns | 27.130 ns | 27.053 ns | 27.303 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|        Parse | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 27.142 ns | 0.0360 ns | 0.0319 ns | 27.143 ns | 27.070 ns | 27.205 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     TryParse | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 29.551 ns | 1.2489 ns | 1.4383 ns | 30.448 ns | 27.200 ns | 30.594 ns |  1.15 |    0.06 |      - |     - |     - |         - |
|     TryParse | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |  2147483647 | 25.355 ns | 0.0951 ns | 0.0843 ns | 25.357 ns | 25.213 ns | 25.474 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 25.746 ns | 0.1240 ns | 0.1160 ns | 25.744 ns | 25.550 ns | 25.913 ns |  1.02 |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|    ParseSpan | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 27.279 ns | 0.1212 ns | 0.1074 ns | 27.262 ns | 27.117 ns | 27.484 ns |  1.00 |    0.01 |      - |     - |     - |         - |
|    ParseSpan | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |  2147483647 | 27.163 ns | 0.0991 ns | 0.0879 ns | 27.176 ns | 26.987 ns | 27.312 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 27.393 ns | 0.0950 ns | 0.0794 ns | 27.393 ns | 27.281 ns | 27.554 ns |  1.01 |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|    TryFormat | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 17.958 ns | 0.0621 ns | 0.0550 ns | 17.939 ns | 17.871 ns | 18.055 ns |  0.89 |    0.01 |      - |     - |     - |         - |
|    TryFormat | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |  2147483647 | 20.189 ns | 0.1346 ns | 0.1259 ns | 20.203 ns | 20.002 ns | 20.370 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 15.742 ns | 0.0202 ns | 0.0168 ns | 15.745 ns | 15.715 ns | 15.771 ns |  0.78 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
| TryParseSpan | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 25.832 ns | 0.0682 ns | 0.0570 ns | 25.831 ns | 25.730 ns | 25.949 ns |  1.01 |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |  2147483647 | 25.676 ns | 0.0767 ns | 0.0717 ns | 25.675 ns | 25.576 ns | 25.809 ns |  1.00 |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 25.683 ns | 0.0457 ns | 0.0405 ns | 25.684 ns | 25.608 ns | 25.758 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     **ParseHex** | **Job-TRWEYK** | **\baseline-no-52893\Core_Root\corerun.exe** |        **3039** | **16.210 ns** | **0.0248 ns** | **0.0232 ns** | **16.212 ns** | **16.169 ns** | **16.247 ns** |  **1.01** |    **0.00** |      **-** |     **-** |     **-** |         **-** |
|     ParseHex | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |        3039 | 16.030 ns | 0.0260 ns | 0.0244 ns | 16.029 ns | 15.994 ns | 16.067 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |        3039 | 16.292 ns | 0.0274 ns | 0.0229 ns | 16.295 ns | 16.244 ns | 16.330 ns |  1.02 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|        **Parse** | **Job-TRWEYK** | **\baseline-no-52893\Core_Root\corerun.exe** |           **4** | **15.177 ns** | **0.0214 ns** | **0.0179 ns** | **15.186 ns** | **15.143 ns** | **15.195 ns** |  **0.99** |    **0.00** |      **-** |     **-** |     **-** |         **-** |
|        Parse | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |           4 | 15.365 ns | 0.0540 ns | 0.0479 ns | 15.377 ns | 15.255 ns | 15.410 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|        Parse | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 15.270 ns | 0.0263 ns | 0.0233 ns | 15.271 ns | 15.215 ns | 15.303 ns |  0.99 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     ParseHex | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |           4 | 10.832 ns | 0.0156 ns | 0.0130 ns | 10.825 ns | 10.822 ns | 10.867 ns |  1.02 |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |           4 | 10.607 ns | 0.0059 ns | 0.0046 ns | 10.607 ns | 10.599 ns | 10.615 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 10.552 ns | 0.0052 ns | 0.0043 ns | 10.552 ns | 10.546 ns | 10.558 ns |  0.99 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     TryParse | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |           4 | 13.632 ns | 0.0293 ns | 0.0260 ns | 13.634 ns | 13.582 ns | 13.665 ns |  0.99 |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |           4 | 13.732 ns | 0.0648 ns | 0.0574 ns | 13.734 ns | 13.635 ns | 13.845 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 14.016 ns | 0.0284 ns | 0.0266 ns | 14.027 ns | 13.965 ns | 14.055 ns |  1.02 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|    ParseSpan | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |           4 | 15.500 ns | 0.0044 ns | 0.0037 ns | 15.501 ns | 15.492 ns | 15.506 ns |  1.02 |    0.02 |      - |     - |     - |         - |
|    ParseSpan | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |           4 | 15.261 ns | 0.2620 ns | 0.2451 ns | 15.316 ns | 14.867 ns | 15.597 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 14.885 ns | 0.1309 ns | 0.1160 ns | 14.929 ns | 14.658 ns | 14.996 ns |  0.98 |    0.02 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
| TryParseSpan | Job-TRWEYK | \baseline-no-52893\Core_Root\corerun.exe |           4 | 14.640 ns | 0.0122 ns | 0.0108 ns | 14.638 ns | 14.624 ns | 14.660 ns |  1.04 |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |           4 | 14.014 ns | 0.0144 ns | 0.0127 ns | 14.011 ns | 13.987 ns | 14.033 ns |  1.00 |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 13.150 ns | 0.0175 ns | 0.0155 ns | 13.153 ns | 13.127 ns | 13.179 ns |  0.94 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     **ParseHex** | **Job-TRWEYK** | **\baseline-no-52893\Core_Root\corerun.exe** |    **7FFFFFFF** | **23.449 ns** | **0.0273 ns** | **0.0228 ns** | **23.456 ns** | **23.408 ns** | **23.485 ns** |  **0.99** |    **0.00** |      **-** |     **-** |     **-** |         **-** |
|     ParseHex | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |    7FFFFFFF | 23.616 ns | 0.0729 ns | 0.0682 ns | 23.587 ns | 23.544 ns | 23.786 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |    7FFFFFFF | 23.755 ns | 0.0309 ns | 0.0258 ns | 23.756 ns | 23.695 ns | 23.790 ns |  1.01 |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |         |        |       |       |           |
|     **ParseHex** | **Job-TRWEYK** | **\baseline-no-52893\Core_Root\corerun.exe** |    **80000000** | **23.799 ns** | **0.0266 ns** | **0.0236 ns** | **23.801 ns** | **23.756 ns** | **23.840 ns** |  **1.00** |    **0.00** |      **-** |     **-** |     **-** |         **-** |
|     ParseHex | Job-OBGLQV |          \baseline\Core_Root\corerun.exe |    80000000 | 23.806 ns | 0.0134 ns | 0.0112 ns | 23.808 ns | 23.784 ns | 23.824 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-COTIHO |  \diff-apply-57400\Core_Root\corerun.exe |    80000000 | 23.742 ns | 0.0212 ns | 0.0177 ns | 23.744 ns | 23.714 ns | 23.768 ns |  1.00 |    0.00 |      - |     - |     - |         - |

**Comment by JulieLeeMSFT** [comment]
@echesakov diff seems improvements. Do you approve the change?

**Comment by echesakovMSFT** [comment]
@JulieLeeMSFT Yes, the numbers were mostly improvements with an exception of `ToString(4)` benchmark and that was confusing to me, so I re-ran the benchmarks again:

|       Method |        Job |                                Toolchain |       value |      Mean |     Error |    StdDev |    Median |       Min |       Max | Ratio | MannWhitney(3ms) | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |----------- |----------------------------------------- |------------ |----------:|----------:|----------:|----------:|----------:|----------:|------:|----------------- |--------:|-------:|------:|------:|----------:|
|     **ToString** | **Job-JDYPAF** | **\baseline-no-52893\Core_Root\corerun.exe** | **-2147483648** | **39.708 ns** | **0.1531 ns** | **0.1195 ns** | **39.677 ns** | **39.579 ns** | **39.940 ns** |  **0.98** |             **Same** |    **0.01** | **0.0228** |     **-** |     **-** |      **48 B** |
|     ToString | Job-QVHRJM |          \baseline\Core_Root\corerun.exe | -2147483648 | 40.359 ns | 0.3125 ns | 0.2610 ns | 40.258 ns | 40.164 ns | 41.000 ns |  1.00 |             Base |    0.00 | 0.0229 |     - |     - |      48 B |
|     ToString | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 38.054 ns | 0.0332 ns | 0.0311 ns | 38.054 ns | 38.009 ns | 38.105 ns |  0.94 |             Same |    0.01 | 0.0228 |     - |     - |      48 B |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|  ToStringHex | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 24.460 ns | 0.0731 ns | 0.0683 ns | 24.456 ns | 24.334 ns | 24.563 ns |  0.94 |             Same |    0.00 | 0.0191 |     - |     - |      40 B |
|  ToStringHex | Job-QVHRJM |          \baseline\Core_Root\corerun.exe | -2147483648 | 26.016 ns | 0.1281 ns | 0.1136 ns | 26.012 ns | 25.705 ns | 26.169 ns |  1.00 |             Base |    0.00 | 0.0191 |     - |     - |      40 B |
|  ToStringHex | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 24.655 ns | 0.0927 ns | 0.0867 ns | 24.633 ns | 24.534 ns | 24.823 ns |  0.95 |             Same |    0.01 | 0.0191 |     - |     - |      40 B |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|        Parse | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 27.672 ns | 0.2437 ns | 0.2160 ns | 27.595 ns | 27.439 ns | 28.069 ns |  0.94 |             Same |    0.01 |      - |     - |     - |         - |
|        Parse | Job-QVHRJM |          \baseline\Core_Root\corerun.exe | -2147483648 | 29.433 ns | 0.1123 ns | 0.0938 ns | 29.417 ns | 29.300 ns | 29.630 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|        Parse | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 27.642 ns | 0.1468 ns | 0.1302 ns | 27.628 ns | 27.491 ns | 27.951 ns |  0.94 |             Same |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     TryParse | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 27.568 ns | 0.1200 ns | 0.1002 ns | 27.530 ns | 27.485 ns | 27.805 ns |  1.06 |             Same |    0.01 |      - |     - |     - |         - |
|     TryParse | Job-QVHRJM |          \baseline\Core_Root\corerun.exe | -2147483648 | 26.011 ns | 0.1456 ns | 0.1136 ns | 25.984 ns | 25.849 ns | 26.244 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 26.265 ns | 0.0789 ns | 0.0738 ns | 26.257 ns | 26.117 ns | 26.407 ns |  1.01 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|    ParseSpan | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 27.555 ns | 0.0339 ns | 0.0301 ns | 27.555 ns | 27.520 ns | 27.598 ns |  1.00 |             Same |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-QVHRJM |          \baseline\Core_Root\corerun.exe | -2147483648 | 27.592 ns | 0.0385 ns | 0.0361 ns | 27.587 ns | 27.539 ns | 27.672 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 27.645 ns | 0.1365 ns | 0.1140 ns | 27.615 ns | 27.584 ns | 28.014 ns |  1.00 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|    TryFormat | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 30.085 ns | 0.0277 ns | 0.0216 ns | 30.079 ns | 30.059 ns | 30.125 ns |  1.01 |             Same |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-QVHRJM |          \baseline\Core_Root\corerun.exe | -2147483648 | 29.799 ns | 0.0418 ns | 0.0349 ns | 29.799 ns | 29.756 ns | 29.880 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 28.352 ns | 0.0847 ns | 0.0661 ns | 28.332 ns | 28.293 ns | 28.483 ns |  0.95 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
| TryParseSpan | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe | -2147483648 | 26.390 ns | 0.0736 ns | 0.0615 ns | 26.406 ns | 26.269 ns | 26.477 ns |  1.00 |             Same |    0.01 |      - |     - |     - |         - |
| TryParseSpan | Job-QVHRJM |          \baseline\Core_Root\corerun.exe | -2147483648 | 26.343 ns | 0.1202 ns | 0.1065 ns | 26.326 ns | 26.141 ns | 26.589 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe | -2147483648 | 25.998 ns | 0.0586 ns | 0.0489 ns | 26.011 ns | 25.901 ns | 26.057 ns |  0.99 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|        **Parse** | **Job-JDYPAF** | **\baseline-no-52893\Core_Root\corerun.exe** |       **12345** | **19.614 ns** | **0.0439 ns** | **0.0389 ns** | **19.610 ns** | **19.555 ns** | **19.684 ns** |  **1.04** |             **Same** |    **0.01** |      **-** |     **-** |     **-** |         **-** |
|        Parse | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |       12345 | 18.805 ns | 0.1517 ns | 0.1419 ns | 18.785 ns | 18.631 ns | 19.057 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|        Parse | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 18.586 ns | 0.0770 ns | 0.0683 ns | 18.580 ns | 18.494 ns | 18.720 ns |  0.99 |             Same |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     TryParse | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |       12345 | 16.933 ns | 0.0885 ns | 0.0785 ns | 16.917 ns | 16.840 ns | 17.087 ns |  0.97 |             Same |    0.01 |      - |     - |     - |         - |
|     TryParse | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |       12345 | 17.393 ns | 0.0613 ns | 0.0543 ns | 17.397 ns | 17.295 ns | 17.488 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 18.084 ns | 0.3170 ns | 0.2965 ns | 18.163 ns | 17.326 ns | 18.260 ns |  1.04 |             Same |    0.02 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|    ParseSpan | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |       12345 | 18.724 ns | 0.0615 ns | 0.0514 ns | 18.742 ns | 18.629 ns | 18.798 ns |  1.01 |             Same |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |       12345 | 18.529 ns | 0.0630 ns | 0.0589 ns | 18.519 ns | 18.441 ns | 18.639 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 18.779 ns | 0.0511 ns | 0.0453 ns | 18.779 ns | 18.705 ns | 18.845 ns |  1.01 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
| TryParseSpan | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |       12345 | 17.516 ns | 0.0414 ns | 0.0388 ns | 17.510 ns | 17.463 ns | 17.597 ns |  1.00 |             Same |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |       12345 | 17.534 ns | 0.0205 ns | 0.0191 ns | 17.536 ns | 17.506 ns | 17.568 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 17.268 ns | 0.0402 ns | 0.0314 ns | 17.272 ns | 17.213 ns | 17.314 ns |  0.98 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     **ToString** | **Job-JDYPAF** | **\baseline-no-52893\Core_Root\corerun.exe** |           **4** |  **1.933 ns** | **0.0042 ns** | **0.0037 ns** |  **1.932 ns** |  **1.928 ns** |  **1.941 ns** |  **0.86** |             **Same** |    **0.00** |      **-** |     **-** |     **-** |         **-** |
|     ToString | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |           4 |  2.248 ns | 0.0047 ns | 0.0042 ns |  2.247 ns |  2.244 ns |  2.256 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|     ToString | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |           4 |  2.247 ns | 0.0042 ns | 0.0035 ns |  2.247 ns |  2.242 ns |  2.255 ns |  1.00 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|  ToStringHex | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |           4 | 16.304 ns | 0.0309 ns | 0.0274 ns | 16.298 ns | 16.269 ns | 16.366 ns |  0.94 |             Same |    0.00 | 0.0114 |     - |     - |      24 B |
|  ToStringHex | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |           4 | 17.420 ns | 0.0203 ns | 0.0170 ns | 17.418 ns | 17.391 ns | 17.454 ns |  1.00 |             Base |    0.00 | 0.0114 |     - |     - |      24 B |
|  ToStringHex | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 16.871 ns | 0.0304 ns | 0.0237 ns | 16.863 ns | 16.845 ns | 16.930 ns |  0.97 |             Same |    0.00 | 0.0115 |     - |     - |      24 B |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|    TryFormat | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |           4 |  4.317 ns | 0.0127 ns | 0.0113 ns |  4.318 ns |  4.291 ns |  4.333 ns |  1.10 |             Same |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |           4 |  3.928 ns | 0.0102 ns | 0.0085 ns |  3.929 ns |  3.909 ns |  3.940 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |           4 |  3.963 ns | 0.0087 ns | 0.0073 ns |  3.963 ns |  3.952 ns |  3.975 ns |  1.01 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     **ToString** | **Job-JDYPAF** | **\baseline-no-52893\Core_Root\corerun.exe** |       **12345** | **15.369 ns** | **0.0146 ns** | **0.0129 ns** | **15.367 ns** | **15.355 ns** | **15.400 ns** |  **0.98** |             **Same** |    **0.00** | **0.0153** |     **-** |     **-** |      **32 B** |
|     ToString | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |       12345 | 15.670 ns | 0.0131 ns | 0.0122 ns | 15.669 ns | 15.654 ns | 15.693 ns |  1.00 |             Base |    0.00 | 0.0153 |     - |     - |      32 B |
|     ToString | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 16.022 ns | 0.0883 ns | 0.0689 ns | 16.001 ns | 15.971 ns | 16.185 ns |  1.02 |             Same |    0.00 | 0.0153 |     - |     - |      32 B |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|  ToStringHex | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |       12345 | 20.823 ns | 0.0191 ns | 0.0169 ns | 20.823 ns | 20.800 ns | 20.858 ns |  0.98 |             Same |    0.00 | 0.0152 |     - |     - |      32 B |
|  ToStringHex | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |       12345 | 21.278 ns | 0.0682 ns | 0.0569 ns | 21.257 ns | 21.230 ns | 21.425 ns |  1.00 |             Base |    0.00 | 0.0152 |     - |     - |      32 B |
|  ToStringHex | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |       12345 | 21.460 ns | 0.0230 ns | 0.0203 ns | 21.453 ns | 21.439 ns | 21.505 ns |  1.01 |             Same |    0.00 | 0.0153 |     - |     - |      32 B |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|    TryFormat | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |       12345 |  8.446 ns | 0.0238 ns | 0.0223 ns |  8.451 ns |  8.401 ns |  8.481 ns |  0.94 |             Same |    0.01 |      - |     - |     - |         - |
|    TryFormat | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |       12345 |  9.019 ns | 0.0402 ns | 0.0357 ns |  9.019 ns |  8.959 ns |  9.102 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |       12345 |  7.641 ns | 0.0459 ns | 0.0407 ns |  7.645 ns |  7.551 ns |  7.682 ns |  0.85 |             Same |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     **ToString** | **Job-JDYPAF** | **\baseline-no-52893\Core_Root\corerun.exe** |  **2147483647** | **24.423 ns** | **0.0170 ns** | **0.0142 ns** | **24.423 ns** | **24.396 ns** | **24.448 ns** |  **0.93** |             **Same** |    **0.00** | **0.0229** |     **-** |     **-** |      **48 B** |
|     ToString | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |  2147483647 | 26.286 ns | 0.0313 ns | 0.0261 ns | 26.285 ns | 26.256 ns | 26.336 ns |  1.00 |             Base |    0.00 | 0.0228 |     - |     - |      48 B |
|     ToString | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 23.761 ns | 0.0205 ns | 0.0160 ns | 23.760 ns | 23.734 ns | 23.797 ns |  0.90 |             Same |    0.00 | 0.0229 |     - |     - |      48 B |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|  ToStringHex | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 31.639 ns | 0.0938 ns | 0.0832 ns | 31.608 ns | 31.571 ns | 31.810 ns |  0.99 |             Same |    0.00 | 0.0191 |     - |     - |      40 B |
|  ToStringHex | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |  2147483647 | 31.879 ns | 0.0269 ns | 0.0251 ns | 31.878 ns | 31.846 ns | 31.923 ns |  1.00 |             Base |    0.00 | 0.0191 |     - |     - |      40 B |
|  ToStringHex | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 32.232 ns | 0.0257 ns | 0.0228 ns | 32.234 ns | 32.195 ns | 32.262 ns |  1.01 |             Same |    0.00 | 0.0191 |     - |     - |      40 B |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|        Parse | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 27.098 ns | 0.0929 ns | 0.0775 ns | 27.080 ns | 27.016 ns | 27.284 ns |  1.00 |             Same |    0.00 |      - |     - |     - |         - |
|        Parse | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |  2147483647 | 27.120 ns | 0.0578 ns | 0.0451 ns | 27.129 ns | 27.048 ns | 27.188 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|        Parse | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 27.091 ns | 0.0694 ns | 0.0649 ns | 27.081 ns | 26.975 ns | 27.214 ns |  1.00 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     TryParse | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 27.051 ns | 0.4004 ns | 0.3549 ns | 27.160 ns | 25.832 ns | 27.224 ns |  1.02 |             Same |    0.01 |      - |     - |     - |         - |
|     TryParse | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |  2147483647 | 26.477 ns | 0.5097 ns | 0.4519 ns | 26.672 ns | 25.474 ns | 26.827 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 25.740 ns | 0.1641 ns | 0.1371 ns | 25.726 ns | 25.565 ns | 26.073 ns |  0.97 |             Same |    0.02 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|    ParseSpan | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 28.507 ns | 0.2006 ns | 0.1675 ns | 28.553 ns | 28.045 ns | 28.695 ns |  1.04 |             Same |    0.01 |      - |     - |     - |         - |
|    ParseSpan | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |  2147483647 | 27.452 ns | 0.1014 ns | 0.0847 ns | 27.455 ns | 27.300 ns | 27.580 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 27.457 ns | 0.0986 ns | 0.0874 ns | 27.447 ns | 27.309 ns | 27.644 ns |  1.00 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|    TryFormat | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 18.392 ns | 0.0297 ns | 0.0248 ns | 18.389 ns | 18.352 ns | 18.442 ns |  0.89 |             Same |    0.01 |      - |     - |     - |         - |
|    TryFormat | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |  2147483647 | 20.583 ns | 0.1339 ns | 0.1187 ns | 20.569 ns | 20.428 ns | 20.833 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|    TryFormat | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 15.823 ns | 0.0220 ns | 0.0206 ns | 15.821 ns | 15.791 ns | 15.858 ns |  0.77 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
| TryParseSpan | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |  2147483647 | 25.774 ns | 0.0481 ns | 0.0426 ns | 25.782 ns | 25.698 ns | 25.849 ns |  1.00 |             Same |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |  2147483647 | 25.746 ns | 0.0519 ns | 0.0433 ns | 25.750 ns | 25.671 ns | 25.816 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |  2147483647 | 26.787 ns | 0.0205 ns | 0.0171 ns | 26.787 ns | 26.762 ns | 26.822 ns |  1.04 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     **ParseHex** | **Job-JDYPAF** | **\baseline-no-52893\Core_Root\corerun.exe** |        **3039** | **16.045 ns** | **0.0615 ns** | **0.0514 ns** | **16.028 ns** | **15.991 ns** | **16.170 ns** |  **1.00** |             **Same** |    **0.00** |      **-** |     **-** |     **-** |         **-** |
|     ParseHex | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |        3039 | 16.081 ns | 0.0682 ns | 0.0604 ns | 16.059 ns | 16.014 ns | 16.217 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |        3039 | 16.295 ns | 0.0336 ns | 0.0298 ns | 16.295 ns | 16.236 ns | 16.338 ns |  1.01 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|        **Parse** | **Job-JDYPAF** | **\baseline-no-52893\Core_Root\corerun.exe** |           **4** | **15.251 ns** | **0.0164 ns** | **0.0137 ns** | **15.251 ns** | **15.233 ns** | **15.269 ns** |  **0.98** |             **Same** |    **0.00** |      **-** |     **-** |     **-** |         **-** |
|        Parse | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |           4 | 15.499 ns | 0.0133 ns | 0.0118 ns | 15.495 ns | 15.480 ns | 15.522 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|        Parse | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 15.141 ns | 0.0289 ns | 0.0241 ns | 15.139 ns | 15.098 ns | 15.180 ns |  0.98 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     ParseHex | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |           4 | 10.518 ns | 0.0060 ns | 0.0047 ns | 10.516 ns | 10.513 ns | 10.529 ns |  0.97 |             Same |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |           4 | 10.828 ns | 0.0252 ns | 0.0211 ns | 10.819 ns | 10.815 ns | 10.875 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 10.844 ns | 0.0936 ns | 0.0830 ns | 10.861 ns | 10.557 ns | 10.889 ns |  1.00 |             Same |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     TryParse | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |           4 | 13.629 ns | 0.0223 ns | 0.0174 ns | 13.630 ns | 13.596 ns | 13.662 ns |  1.05 |             Same |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |           4 | 13.042 ns | 0.0208 ns | 0.0174 ns | 13.040 ns | 13.018 ns | 13.079 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|     TryParse | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 14.013 ns | 0.0750 ns | 0.0702 ns | 14.026 ns | 13.908 ns | 14.131 ns |  1.07 |             Same |    0.01 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|    ParseSpan | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |           4 | 14.721 ns | 0.3387 ns | 0.3168 ns | 14.878 ns | 13.947 ns | 15.026 ns |  0.97 |             Same |    0.02 |      - |     - |     - |         - |
|    ParseSpan | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |           4 | 15.109 ns | 0.1887 ns | 0.1765 ns | 15.113 ns | 14.813 ns | 15.381 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|    ParseSpan | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 15.110 ns | 0.2967 ns | 0.2630 ns | 15.222 ns | 14.553 ns | 15.400 ns |  1.00 |             Same |    0.02 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
| TryParseSpan | Job-JDYPAF | \baseline-no-52893\Core_Root\corerun.exe |           4 | 13.511 ns | 0.0152 ns | 0.0127 ns | 13.509 ns | 13.483 ns | 13.531 ns |  0.98 |             Same |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |           4 | 13.819 ns | 0.0134 ns | 0.0112 ns | 13.819 ns | 13.802 ns | 13.841 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
| TryParseSpan | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |           4 | 13.493 ns | 0.0067 ns | 0.0052 ns | 13.492 ns | 13.487 ns | 13.506 ns |  0.98 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     **ParseHex** | **Job-JDYPAF** | **\baseline-no-52893\Core_Root\corerun.exe** |    **7FFFFFFF** | **23.781 ns** | **0.0225 ns** | **0.0199 ns** | **23.781 ns** | **23.743 ns** | **23.813 ns** |  **1.01** |             **Same** |    **0.00** |      **-** |     **-** |     **-** |         **-** |
|     ParseHex | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |    7FFFFFFF | 23.648 ns | 0.0432 ns | 0.0337 ns | 23.661 ns | 23.591 ns | 23.683 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |    7FFFFFFF | 23.729 ns | 0.0246 ns | 0.0192 ns | 23.728 ns | 23.702 ns | 23.761 ns |  1.00 |             Same |    0.00 |      - |     - |     - |         - |
|              |            |                                          |             |           |           |           |           |           |           |       |                  |         |        |       |       |           |
|     **ParseHex** | **Job-JDYPAF** | **\baseline-no-52893\Core_Root\corerun.exe** |    **80000000** | **23.708 ns** | **0.0091 ns** | **0.0080 ns** | **23.709 ns** | **23.692 ns** | **23.720 ns** |  **1.00** |             **Same** |    **0.00** |      **-** |     **-** |     **-** |         **-** |
|     ParseHex | Job-QVHRJM |          \baseline\Core_Root\corerun.exe |    80000000 | 23.769 ns | 0.0170 ns | 0.0142 ns | 23.768 ns | 23.743 ns | 23.799 ns |  1.00 |             Base |    0.00 |      - |     - |     - |         - |
|     ParseHex | Job-XFIGBI |  \diff-apply-57400\Core_Root\corerun.exe |    80000000 | 23.587 ns | 0.1120 ns | 0.1048 ns | 23.515 ns | 23.476 ns | 23.761 ns |  0.99 |             Same |    0.00 |      - |     - |     - |         - |

**Comment by echesakovMSFT** [comment]
The spmi-asmdiffs are also mostly positive with an exception of `lclfldrem:Main():int` that took pretty high hit on both linux-arm64 and windows-arm64.

I will take a look at the diff to understand what is going on.

## benchmarks.run.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 156732
Total bytes of diff: 155316
Total bytes of delta: -1416 (-0.90% of base)
Total relative delta: -0.79
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
        -304 : 8088.dasm (-1.21% of base)
        -216 : 12966.dasm (-1.11% of base)
         -80 : 12980.dasm (-0.75% of base)
         -80 : 8282.dasm (-0.75% of base)
         -48 : 7168.dasm (-3.03% of base)
         -44 : 19221.dasm (-3.42% of base)
         -44 : 10508.dasm (-2.75% of base)
         -44 : 9594.dasm (-0.79% of base)
         -40 : 5771.dasm (-1.55% of base)
         -40 : 19522.dasm (-0.73% of base)
         -32 : 13977.dasm (-2.43% of base)
         -32 : 5811.dasm (-2.31% of base)
         -28 : 2896.dasm (-1.19% of base)
         -28 : 5723.dasm (-1.16% of base)
         -24 : 5774.dasm (-1.62% of base)
         -24 : 21699.dasm (-1.29% of base)
         -24 : 21371.dasm (-1.56% of base)
         -16 : 6602.dasm (-0.28% of base)
         -12 : 22702.dasm (-0.57% of base)
         -12 : 21698.dasm (-0.94% of base)

58 total files with Code Size differences (58 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
        -304 (-1.21% of base) : 8088.dasm - DynamicClass:_DynamicMethod0(System.IO.TextWriter,MicroBenchmarks.Serializers.MyEventsListerItem,int)
        -216 (-1.11% of base) : 12966.dasm - DynamicClass:_DynamicMethod0(System.IO.TextWriter,MicroBenchmarks.Serializers.IndexViewModel,int)
         -80 (-0.75% of base) : 12980.dasm - Jil.Deserialize.Methods:ParseISO8601DateThunkReader(byref,System.Char[],int,int):System.DateTime
         -80 (-0.75% of base) : 8282.dasm - Jil.Deserialize.Methods:ParseISO8601Date(System.IO.TextReader,System.Char[],int,int):System.DateTime
         -48 (-3.03% of base) : 7168.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeO(System.DateTime,System.TimeSpan,System.Span`1[Byte],byref):bool
         -44 (-3.42% of base) : 19221.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeG(System.DateTime,System.TimeSpan,System.Span`1[Byte],byref):bool
         -44 (-2.75% of base) : 10508.dasm - System.DateTimeFormat:TryFormatO(System.DateTime,System.TimeSpan,System.Span`1[Char],byref):bool
         -44 (-0.79% of base) : 9594.dasm - DynamicClass:_DynamicMethod0(System.IO.TextWriter,MicroBenchmarks.Serializers.CollectionsOfPrimitives,int)
         -40 (-1.55% of base) : 5771.dasm - System.TimeZoneInfo:GetIsDaylightSavingsFromUtc(System.DateTime,int,System.TimeSpan,AdjustmentRule,System.Nullable`1[Int32],byref,System.TimeZoneInfo):bool
         -40 (-0.73% of base) : 19522.dasm - Utf8Json.Formatters.ISO8601DateTimeFormatter:Deserialize(byref,Utf8Json.IJsonFormatterResolver):System.DateTime:this
         -32 (-2.43% of base) : 13977.dasm - System.DateTimeFormat:TryFormatR(System.DateTime,System.TimeSpan,System.Span`1[Char],byref):bool
         -32 (-2.31% of base) : 5811.dasm - System.TimeZoneInfo:GetIsDaylightSavings(System.DateTime,AdjustmentRule,System.Globalization.DaylightTimeStruct):bool
         -28 (-1.19% of base) : 2896.dasm - System.Globalization.TimeSpanFormat:TryFormatStandard(System.TimeSpan,int,System.String,System.Span`1[Char],byref):bool
         -28 (-1.16% of base) : 5723.dasm - System.TimeZoneInfo:TryCreateAdjustmentRules(System.String,byref,byref,byref,int):bool
         -24 (-1.62% of base) : 5774.dasm - System.TimeZoneInfo:TransitionTimeToDateTime(int,TransitionTime):System.DateTime
         -24 (-1.29% of base) : 21699.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTime
         -24 (-1.56% of base) : 21371.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTimeOffset
         -16 (-0.28% of base) : 6602.dasm - System.DateTimeFormat:FormatCustomized(System.DateTime,System.ReadOnlySpan`1[Char],System.Globalization.DateTimeFormatInfo,System.TimeSpan,System.Text.StringBuilder):System.Text.StringBuilder
         -12 (-0.57% of base) : 22702.dasm - System.Xml.XmlConverter:TryParseDateTime(System.Byte[],int,int,byref):bool
         -12 (-0.94% of base) : 21698.dasm - System.Xml.XmlConvert:ToDateTime(System.String,int):System.DateTime

Top method improvements (percentages):
          -4 (-4.35% of base) : 8100.dasm - System.DateTime:get_Hour():int:this
          -4 (-3.85% of base) : 949.dasm - System.Number:UInt32ToDecChars(long,int,int):long
          -4 (-3.85% of base) : 6614.dasm - System.Number:UInt32ToDecChars(long,int,int):long
         -44 (-3.42% of base) : 19221.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeG(System.DateTime,System.TimeSpan,System.Span`1[Byte],byref):bool
         -48 (-3.03% of base) : 7168.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeO(System.DateTime,System.TimeSpan,System.Span`1[Byte],byref):bool
         -44 (-2.75% of base) : 10508.dasm - System.DateTimeFormat:TryFormatO(System.DateTime,System.TimeSpan,System.Span`1[Char],byref):bool
          -8 (-2.50% of base) : 1114.dasm - System.DateTime:.ctor(int,int,int):this
         -12 (-2.50% of base) : 12922.dasm - BenchmarksGame.Fasta_1:SelectNucleotides(BenchmarksGame.Fasta_1+Frequency[],System.Int32[]):System.Byte[]
         -32 (-2.43% of base) : 13977.dasm - System.DateTimeFormat:TryFormatR(System.DateTime,System.TimeSpan,System.Span`1[Char],byref):bool
         -32 (-2.31% of base) : 5811.dasm - System.TimeZoneInfo:GetIsDaylightSavings(System.DateTime,AdjustmentRule,System.Globalization.DaylightTimeStruct):bool
          -4 (-2.17% of base) : 6866.dasm - System.DateTime:DaysInMonth(int,int):int
          -8 (-2.17% of base) : 22787.dasm - System.Globalization.JapaneseCalendar:GetJapaneseEraStartDate(int,byref):bool
          -8 (-2.04% of base) : 3685.dasm - Microsoft.Extensions.DependencyInjection.DependencyInjectionEventSource:CallSiteBuilt(Microsoft.Extensions.DependencyInjection.ServiceProvider,System.Type,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite):this
          -8 (-1.98% of base) : 1102.dasm - System.DateTime:CreateDateTimeFromSystemTime(byref,long):System.DateTime
          -8 (-1.79% of base) : 1993.dasm - System.DateTime:GetDate(byref,byref,byref):this
          -8 (-1.64% of base) : 5674.dasm - System.DateTime:GetDatePart(int):int:this
         -24 (-1.62% of base) : 5774.dasm - System.TimeZoneInfo:TransitionTimeToDateTime(int,TransitionTime):System.DateTime
         -24 (-1.56% of base) : 21371.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTimeOffset
         -40 (-1.55% of base) : 5771.dasm - System.TimeZoneInfo:GetIsDaylightSavingsFromUtc(System.DateTime,int,System.TimeSpan,AdjustmentRule,System.Nullable`1[Int32],byref,System.TimeZoneInfo):bool
          -8 (-1.50% of base) : 1992.dasm - System.DateTime:AddYears(int):System.DateTime:this

58 total methods with Code Size differences (58 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## coreclr_tests.pmi.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 358676
Total bytes of diff: 358632
Total bytes of delta: -44 (-0.01% of base)
Total relative delta: -0.97
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         352 : 225381.dasm (1.39% of base)

Top file improvements (bytes):
        -220 : 218513.dasm (-0.14% of base)
         -56 : 218413.dasm (-0.04% of base)
         -12 : 239427.dasm (-2.54% of base)
          -8 : 225371.dasm (-0.03% of base)
          -4 : 134702.dasm (-0.74% of base)
          -4 : 233820.dasm (-0.14% of base)
          -4 : 253577.dasm (-1.33% of base)
          -4 : 87100.dasm (-0.98% of base)
          -4 : 242584.dasm (-4.00% of base)
          -4 : 135112.dasm (-0.85% of base)
          -4 : 223970.dasm (-0.75% of base)
          -4 : 84819.dasm (-0.32% of base)
          -4 : 242898.dasm (-6.67% of base)
          -4 : 84803.dasm (-0.58% of base)
          -4 : 242900.dasm (-6.25% of base)
          -4 : 84840.dasm (-0.65% of base)
          -4 : 242924.dasm (-8.33% of base)
          -4 : 242926.dasm (-8.33% of base)
          -4 : 242928.dasm (-8.33% of base)
          -4 : 84781.dasm (-0.60% of base)

30 total files with Code Size differences (29 improved, 1 regressed), 0 unchanged.

Top method regressions (bytes):
         352 ( 1.39% of base) : 225381.dasm - lclfldrem:Main():int

Top method improvements (bytes):
        -220 (-0.14% of base) : 218513.dasm - u4rem:Main():int
         -56 (-0.04% of base) : 218413.dasm - u4div:Main():int
         -12 (-2.54% of base) : 239427.dasm - BenchmarksGame.Fasta_1:SelectNucleotides(BenchmarksGame.Fasta_1+Frequency[],System.Int32[]):System.Byte[]
          -8 (-0.03% of base) : 225371.dasm - lclfldrem:Main():int
          -4 (-0.74% of base) : 134702.dasm - testout1:Func_0_3_6_4_4():long
          -4 (-0.14% of base) : 233820.dasm - MemoryAlloc:SteadyState():this
          -4 (-1.33% of base) : 253577.dasm - Test:Main(System.String[]):int
          -4 (-0.98% of base) : 87100.dasm - ILGEN_0xa83217d:Method_0xf3555db(long,long,int,int,short,byte):int
          -4 (-4.00% of base) : 242584.dasm - Tests:ModInBounds(System.Int32[],int)
          -4 (-0.85% of base) : 135112.dasm - testout1:Func_0_6_1_3_3():double
          -4 (-0.75% of base) : 223970.dasm - SoDBench.Program:DeleteDirectory(System.IO.DirectoryInfo,int)
          -4 (-0.32% of base) : 84819.dasm - ILGEN_0xbc077bd:Method_0xa67f86e1(long,double,short,int,float,int,short,int,int):int
          -4 (-6.67% of base) : 242898.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns5(System.Int32[]):int
          -4 (-0.58% of base) : 84803.dasm - ILGEN_0xc2d6ebd8:Method_0x6228(ushort,short,int,long,short,long,int):int
          -4 (-6.25% of base) : 242900.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns10(System.Int32[]):int
          -4 (-0.65% of base) : 84840.dasm - ILGEN_0xd4820a77:Method_0x1a2ad58f(ubyte,long,byte,float):int
          -4 (-8.33% of base) : 242924.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns3(System.Int32[]):int
          -4 (-8.33% of base) : 242926.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns5(System.Int32[]):int
          -4 (-8.33% of base) : 242928.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns10(System.Int32[]):int
          -4 (-0.60% of base) : 84781.dasm - ILGEN_0xcd4c3cc0:main():int

Top method regressions (percentages):
         352 ( 1.39% of base) : 225381.dasm - lclfldrem:Main():int

Top method improvements (percentages):
          -4 (-9.09% of base) : 246881.dasm - UDivConst:U4_Div_3(int):int
          -4 (-9.09% of base) : 246882.dasm - UDivConst:U4_Div_5(int):int
          -4 (-8.33% of base) : 242924.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns3(System.Int32[]):int
          -4 (-8.33% of base) : 242926.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns5(System.Int32[]):int
          -4 (-8.33% of base) : 242928.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns10(System.Int32[]):int
          -4 (-7.14% of base) : 246913.dasm - UModConst:U4_Mod_3(int):int
          -4 (-7.14% of base) : 246914.dasm - UModConst:U4_Mod_5(int):int
          -4 (-6.67% of base) : 242898.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns5(System.Int32[]):int
          -4 (-6.67% of base) : 242950.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns3(System.Int32[]):int
          -4 (-6.25% of base) : 242900.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns10(System.Int32[]):int
          -4 (-4.00% of base) : 242584.dasm - Tests:ModInBounds(System.Int32[],int)
          -4 (-3.57% of base) : 85032.dasm - Runtime_55141_2:Main():int
         -12 (-2.54% of base) : 239427.dasm - BenchmarksGame.Fasta_1:SelectNucleotides(BenchmarksGame.Fasta_1+Frequency[],System.Int32[]):System.Byte[]
          -4 (-1.96% of base) : 87077.dasm - ILGEN_0x68eb95f0:Method_0x2dae(byte,int,long,byte,ushort,long):float
          -4 (-1.39% of base) : 249215.dasm - AA:Static4():System.Char[]
          -4 (-1.33% of base) : 253577.dasm - Test:Main(System.String[]):int
          -4 (-0.98% of base) : 87100.dasm - ILGEN_0xa83217d:Method_0xf3555db(long,long,int,int,short,byte):int
          -4 (-0.97% of base) : 87111.dasm - ILGEN_0x1ad7535f:Method_0x2ddbcfb4(short):int
          -4 (-0.85% of base) : 135112.dasm - testout1:Func_0_6_1_3_3():double
          -4 (-0.75% of base) : 223970.dasm - SoDBench.Program:DeleteDirectory(System.IO.DirectoryInfo,int)

30 total methods with Code Size differences (29 improved, 1 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.crossgen2.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 68796
Total bytes of diff: 67896
Total bytes of delta: -900 (-1.31% of base)
Total relative delta: -1.43
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -48 : 37620.dasm (-2.49% of base)
         -44 : 37622.dasm (-2.90% of base)
         -44 : 43749.dasm (-2.30% of base)
         -40 : 40598.dasm (-1.36% of base)
         -32 : 37621.dasm (-2.71% of base)
         -32 : 40601.dasm (-1.86% of base)
         -32 : 43748.dasm (-2.32% of base)
         -32 : 37619.dasm (-2.71% of base)
         -28 : 46416.dasm (-1.51% of base)
         -28 : 37922.dasm (-0.77% of base)
         -28 : 37590.dasm (-1.11% of base)
         -28 : 40567.dasm (-0.84% of base)
         -24 : 40590.dasm (-1.76% of base)
         -20 : 43751.dasm (-3.70% of base)
         -16 : 43750.dasm (-2.07% of base)
         -12 : 43753.dasm (-1.83% of base)
         -12 : 62321.dasm (-0.40% of base)
         -12 : 46406.dasm (-1.08% of base)
         -12 : 43752.dasm (-2.73% of base)
         -12 : 43746.dasm (-3.23% of base)

79 total files with Code Size differences (79 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -48 (-2.49% of base) : 37620.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeO(System.DateTime,System.TimeSpan,System.Span`1[System.Byte],byref):bool
         -44 (-2.90% of base) : 37622.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeG(System.DateTime,System.TimeSpan,System.Span`1[System.Byte],byref):bool
         -44 (-2.30% of base) : 43749.dasm - System.DateTimeFormat:TryFormatO(System.DateTime,System.TimeSpan,System.Span`1[System.Char],byref):bool
         -40 (-1.36% of base) : 40598.dasm - System.TimeZoneInfo:GetIsDaylightSavingsFromUtc(System.DateTime,int,System.TimeSpan,System.TimeZoneInfo+AdjustmentRule,System.Nullable`1[System.Int32],byref,System.TimeZoneInfo):bool
         -32 (-2.71% of base) : 37621.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeL(System.DateTime,System.Span`1[System.Byte],byref):bool
         -32 (-1.86% of base) : 40601.dasm - System.TimeZoneInfo:GetIsDaylightSavings(System.DateTime,System.TimeZoneInfo+AdjustmentRule,System.Globalization.DaylightTimeStruct):bool
         -32 (-2.32% of base) : 43748.dasm - System.DateTimeFormat:TryFormatR(System.DateTime,System.TimeSpan,System.Span`1[System.Char],byref):bool
         -32 (-2.71% of base) : 37619.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeR(System.DateTime,System.Span`1[System.Byte],byref):bool
         -28 (-1.51% of base) : 46416.dasm - DecCalc:ScaleResult(long,int,int):int
         -28 (-0.77% of base) : 37922.dasm - System.Globalization.TimeSpanFormat:TryFormatStandard(System.TimeSpan,int,System.String,System.Span`1[System.Char],byref):bool
         -28 (-1.11% of base) : 37590.dasm - System.Buffers.Text.Utf8Formatter:TryFormat(System.TimeSpan,System.Span`1[System.Byte],byref,System.Buffers.StandardFormat):bool
         -28 (-0.84% of base) : 40567.dasm - System.TimeZoneInfo:TryCreateAdjustmentRules(System.String,byref,byref,byref,int):bool
         -24 (-1.76% of base) : 40590.dasm - System.TimeZoneInfo:TransitionTimeToDateTime(int,System.TimeZoneInfo+TransitionTime):System.DateTime
         -20 (-3.70% of base) : 43751.dasm - System.DateTimeFormat:TryFormatDateOnlyO(int,int,int,System.Span`1[System.Char]):bool
         -16 (-2.07% of base) : 43750.dasm - System.DateTimeFormat:TryFormatDateOnlyR(int,int,int,int,System.Span`1[System.Char]):bool
         -12 (-1.83% of base) : 43753.dasm - System.DateTimeFormat:TryFormatTimeOnlyO(int,int,int,long,System.Span`1[System.Char]):bool
         -12 (-0.40% of base) : 62321.dasm - BigNumber:DblToRgbFast(double,System.Byte[],byref,byref):bool
         -12 (-1.08% of base) : 46406.dasm - DecCalc:VarDecFromR4(float,byref)
         -12 (-2.73% of base) : 43752.dasm - System.DateTimeFormat:TryFormatTimeOnlyR(int,int,int,System.Span`1[System.Char]):bool
         -12 (-3.23% of base) : 43746.dasm - System.DateTimeFormat:WriteFourDecimalDigits(int,System.Span`1[System.Char],int)

Top method improvements (percentages):
          -4 (-7.14% of base) : 212246.dasm - System.Net.Sockets.IOControlKeepAlive:MillisecondsToSeconds(int):int
          -4 (-4.76% of base) : 44209.dasm - System.DateTime:DaysToYear(int):int
          -4 (-3.85% of base) : 37634.dasm - System.Buffers.Text.FormattingHelpers:CountDecimalTrailingZeros(int,byref):int
          -4 (-3.85% of base) : 44184.dasm - System.DateTime:get_Hour():int:this
         -20 (-3.70% of base) : 43751.dasm - System.DateTimeFormat:TryFormatDateOnlyO(int,int,int,System.Span`1[System.Char]):bool
          -8 (-3.51% of base) : 212250.dasm - System.Net.Sockets.IOControlKeepAlive:Get(System.Net.Sockets.SafeSocketHandle,int):int
          -4 (-3.45% of base) : 42703.dasm - System.Number:UInt32ToDecChars(long,int,int):long
          -4 (-3.45% of base) : 42702.dasm - System.Number:UInt32ToDecChars(long,int,int):long
         -12 (-3.37% of base) : 37628.dasm - System.Buffers.Text.FormattingHelpers:WriteFourDecimalDigits(int,System.Span`1[System.Byte],int)
         -12 (-3.23% of base) : 43746.dasm - System.DateTimeFormat:WriteFourDecimalDigits(int,System.Span`1[System.Char],int)
          -4 (-3.03% of base) : 164025.dasm - Number:Int32ToDecChars(long,byref,int,int)
         -44 (-2.90% of base) : 37622.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeG(System.DateTime,System.TimeSpan,System.Span`1[System.Byte],byref):bool
          -8 (-2.90% of base) : 37662.dasm - System.Buffers.StandardFormat:Format(System.Span`1[System.Char]):int:this
         -12 (-2.73% of base) : 43752.dasm - System.DateTimeFormat:TryFormatTimeOnlyR(int,int,int,System.Span`1[System.Char]):bool
         -32 (-2.71% of base) : 37621.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeL(System.DateTime,System.Span`1[System.Byte],byref):bool
         -32 (-2.71% of base) : 37619.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeR(System.DateTime,System.Span`1[System.Byte],byref):bool
         -48 (-2.49% of base) : 37620.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeO(System.DateTime,System.TimeSpan,System.Span`1[System.Byte],byref):bool
          -4 (-2.44% of base) : 44172.dasm - System.DateTime:IsLeapYear(int):bool
         -32 (-2.32% of base) : 43748.dasm - System.DateTimeFormat:TryFormatR(System.DateTime,System.TimeSpan,System.Span`1[System.Char],byref):bool
         -44 (-2.30% of base) : 43749.dasm - System.DateTimeFormat:TryFormatO(System.DateTime,System.TimeSpan,System.Span`1[System.Char],byref):bool

79 total methods with Code Size differences (79 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 97564
Total bytes of diff: 96888
Total bytes of delta: -676 (-0.69% of base)
Total relative delta: -0.85
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -32 : 130561.dasm (-0.90% of base)
         -32 : 130558.dasm (-0.95% of base)
         -24 : 130828.dasm (-1.27% of base)
         -24 : 130829.dasm (-1.55% of base)
         -16 : 130617.dasm (-0.39% of base)
         -16 : 130659.dasm (-0.40% of base)
         -12 : 180422.dasm (-0.27% of base)
         -12 : 131318.dasm (-0.30% of base)
         -12 : 123794.dasm (-1.61% of base)
         -12 : 123795.dasm (-1.44% of base)
          -8 : 130433.dasm (-0.97% of base)
          -8 : 133599.dasm (-0.41% of base)
          -8 : 58274.dasm (-0.21% of base)
          -8 : 130426.dasm (-0.95% of base)
          -8 : 210010.dasm (-0.27% of base)
          -8 : 201097.dasm (-3.28% of base)
          -8 : 105000.dasm (-1.19% of base)
          -8 : 130431.dasm (-0.97% of base)
          -8 : 130594.dasm (-0.69% of base)
          -8 : 130438.dasm (-0.95% of base)

83 total files with Code Size differences (83 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -32 (-0.90% of base) : 130561.dasm - System.Xml.Schema.XmlDateTimeConverter:ToDateTimeOffset(System.String):System.DateTimeOffset:this
         -32 (-0.95% of base) : 130558.dasm - System.Xml.Schema.XmlDateTimeConverter:ToDateTime(System.String):System.DateTime:this
         -24 (-1.27% of base) : 130828.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTime
         -24 (-1.55% of base) : 130829.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTimeOffset
         -16 (-0.39% of base) : 130617.dasm - System.Xml.Schema.XmlUntypedConverter:ChangeType(System.String,System.Type,System.Xml.IXmlNamespaceResolver):System.Object:this
         -16 (-0.40% of base) : 130659.dasm - System.Xml.Schema.XmlUntypedStringConverter:FromString(System.String,System.Type,System.Xml.IXmlNamespaceResolver):System.Object:this
         -12 (-0.27% of base) : 180422.dasm - System.Formats.Asn1.AsnDecoder:ParseGeneralizedTime(int,System.ReadOnlySpan`1[Byte]):System.DateTimeOffset
         -12 (-0.30% of base) : 131318.dasm - BigNumber:DblToRgbFast(double,System.Byte[],byref,byref):bool
         -12 (-1.61% of base) : 123794.dasm - System.Xml.BinXmlDateTime:GetFractions(System.DateTime):int
         -12 (-1.44% of base) : 123795.dasm - System.Xml.BinXmlDateTime:GetFractions(System.DateTimeOffset):int
          -8 (-0.97% of base) : 130433.dasm - System.Xml.Schema.XmlBaseConverter:StringToGYear(System.String):System.DateTime
          -8 (-0.41% of base) : 133599.dasm - System.Xml.Xsl.Runtime.XmlQueryRuntime:ChangeTypeXsltArgument(System.Xml.Xsl.XmlQueryType,System.Object,System.Type):System.Object:this
          -8 (-0.21% of base) : 58274.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.Scanner:ScanDateLiteral(Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.SyntaxList`1[[Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.VisualBasicSyntaxNode, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]):Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.SyntaxToken:this
          -8 (-0.95% of base) : 130426.dasm - System.Xml.Schema.XmlBaseConverter:UntypedAtomicToDateTimeOffset(System.String):System.DateTimeOffset
          -8 (-0.27% of base) : 210010.dasm - System.Numerics.BigNumber:FormatBigInteger(bool,System.Numerics.BigInteger,System.String,System.ReadOnlySpan`1[Char],System.Globalization.NumberFormatInfo,System.Span`1[Char],byref,byref):System.String
          -8 (-3.28% of base) : 201097.dasm - System.Net.Sockets.IOControlKeepAlive:Get(System.Net.Sockets.SafeSocketHandle,int):int
          -8 (-1.19% of base) : 105000.dasm - Newtonsoft.Json.Utilities.DateTimeUtils:CreateDateTime(Newtonsoft.Json.Utilities.DateTimeParser):System.DateTime
          -8 (-0.97% of base) : 130431.dasm - System.Xml.Schema.XmlBaseConverter:StringToGMonth(System.String):System.DateTime
          -8 (-0.69% of base) : 130594.dasm - System.Xml.Schema.XmlUntypedConverter:ToDateTimeOffset(System.Object):System.DateTimeOffset:this
          -8 (-0.95% of base) : 130438.dasm - System.Xml.Schema.XmlBaseConverter:StringToGMonthOffset(System.String):System.DateTimeOffset

Top method improvements (percentages):
          -4 (-9.09% of base) : 201101.dasm - System.Net.Sockets.IOControlKeepAlive:MillisecondsToSeconds(int):int
          -4 (-3.33% of base) : 209770.dasm - Number:Int32ToDecChars(long,byref,int,int)
          -8 (-3.28% of base) : 201097.dasm - System.Net.Sockets.IOControlKeepAlive:Get(System.Net.Sockets.SafeSocketHandle,int):int
          -8 (-2.08% of base) : 145681.dasm - Microsoft.Extensions.DependencyInjection.DependencyInjectionEventSource:CallSiteBuilt(Microsoft.Extensions.DependencyInjection.ServiceProvider,System.Type,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite):this
          -8 (-1.92% of base) : 169690.dasm - System.Data.ProviderBase.DbBuffer:ReadDate(int):System.DateTime:this
          -8 (-1.92% of base) : 168395.dasm - System.Data.ProviderBase.DbBuffer:ReadDate(int):System.DateTime:this
         -12 (-1.61% of base) : 123794.dasm - System.Xml.BinXmlDateTime:GetFractions(System.DateTime):int
         -24 (-1.55% of base) : 130829.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTimeOffset
          -4 (-1.47% of base) : 104381.dasm - Newtonsoft.Json.JsonTextWriter:WriteNumberToBuffer(int,bool):int:this
         -12 (-1.44% of base) : 123795.dasm - System.Xml.BinXmlDateTime:GetFractions(System.DateTimeOffset):int
          -8 (-1.41% of base) : 130813.dasm - System.Xml.Schema.XsdDateTime:InitiateXsdDateTime(Parser):this
          -8 (-1.33% of base) : 130838.dasm - System.Xml.Schema.XsdDateTime:.ctor(Parser):this
          -8 (-1.32% of base) : 123810.dasm - System.Xml.BinXmlDateTime:XsdDateToDateTime(long):System.DateTime
          -8 (-1.28% of base) : 145686.dasm - Microsoft.Extensions.DependencyInjection.DependencyInjectionEventSource:WriteServiceProviderBuilt(Microsoft.Extensions.DependencyInjection.ServiceProvider):this
         -24 (-1.27% of base) : 130828.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTime
          -4 (-1.23% of base) : 181279.dasm - System.IO.Compression.ZipHelper:DateTimeToDosTime(System.DateTime):int
          -4 (-1.20% of base) : 123787.dasm - System.Xml.BinXmlDateTime:XsdKatmaiTimeToString(System.Byte[],int):System.String
          -8 (-1.19% of base) : 105000.dasm - Newtonsoft.Json.Utilities.DateTimeUtils:CreateDateTime(Newtonsoft.Json.Utilities.DateTimeParser):System.DateTime
          -8 (-1.19% of base) : 150718.dasm - Newtonsoft.Json.Bson.Utilities.DateTimeUtils:CreateDateTime(Newtonsoft.Json.Bson.Utilities.DateTimeParser):System.DateTime
          -8 (-1.18% of base) : 169694.dasm - System.Data.ProviderBase.DbBuffer:ReadDateTime(int):System.DateTime:this

83 total methods with Code Size differences (83 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries_tests.pmi.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 346404
Total bytes of diff: 341864
Total bytes of delta: -4540 (-1.31% of base)
Total relative delta: -13.37
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -56 : 293569.dasm (-1.79% of base)
         -48 : 79168.dasm (-0.24% of base)
         -40 : 293554.dasm (-1.42% of base)
         -40 : 293558.dasm (-1.42% of base)
         -40 : 293565.dasm (-0.87% of base)
         -32 : 324658.dasm (-1.11% of base)
         -32 : 323956.dasm (-1.10% of base)
         -20 : 73882.dasm (-0.45% of base)
         -20 : 293356.dasm (-2.27% of base)
         -16 : 324657.dasm (-0.31% of base)
         -16 : 323955.dasm (-0.31% of base)
         -16 : 73714.dasm (-0.74% of base)
         -12 : 79209.dasm (-1.28% of base)
         -12 : 73884.dasm (-0.34% of base)
         -12 : 79195.dasm (-1.16% of base)
         -12 : 293244.dasm (-1.90% of base)
         -12 : 309295.dasm (-1.73% of base)
         -12 : 75094.dasm (-0.81% of base)
          -8 : 252076.dasm (-2.90% of base)
          -8 : 252101.dasm (-2.90% of base)

583 total files with Code Size differences (583 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -56 (-1.79% of base) : 293569.dasm - <GetYear_TestData>d__0:MoveNext():bool:this
         -48 (-0.24% of base) : 79168.dasm - <ParseExact_ValidInput_Succeeds_MemberData>d__149:MoveNext():bool:this
         -40 (-1.42% of base) : 293554.dasm - <GetEra_TestData>d__0:MoveNext():bool:this
         -40 (-1.42% of base) : 293558.dasm - <GetMonth_TestData>d__0:MoveNext():bool:this
         -40 (-0.87% of base) : 293565.dasm - <GetWeekOfYear_TestData>d__6:MoveNext():bool:this
         -32 (-1.11% of base) : 324658.dasm - DataContractJsonSerializerTests:DCJS_VerifyDateTimeForDateTimeFormat()
         -32 (-1.10% of base) : 323956.dasm - DataContractJsonSerializerTests:DCJS_VerifyDateTimeForDateTimeFormat()
         -20 (-0.45% of base) : 73882.dasm - System.Tests.DateTimeOffsetTests:Ctor_DateTime()
         -20 (-2.27% of base) : 293356.dasm - System.Globalization.Tests.TaiwanCalendarGetWeekOfYear:GetWeekOfYear_LastDayOfYear():this
         -16 (-0.31% of base) : 324657.dasm - DataContractJsonSerializerTests:DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings()
         -16 (-0.31% of base) : 323955.dasm - DataContractJsonSerializerTests:DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings()
         -16 (-0.74% of base) : 73714.dasm - System.Tests.DateTimeTests:Today_Get_ReturnsExpected():this
         -12 (-1.28% of base) : 79209.dasm - <>c__DisplayClass6_0:<Ctor_DateTime_TimeSpan_Invalid>b__7():System.Object:this
         -12 (-0.34% of base) : 73884.dasm - System.Tests.DateTimeOffsetTests:Ctor_DateTime_TimeSpan()
         -12 (-1.16% of base) : 79195.dasm - <>c__DisplayClass4_0:<Ctor_DateTime_Invalid>b__0():System.Object:this
         -12 (-1.90% of base) : 293244.dasm - System.Globalization.Tests.GregorianCalendarIsLeapYear:IsLeapYearTest(int):this
         -12 (-1.73% of base) : 309295.dasm - System.Net.Primitives.Functional.Tests.CookieTest:Timestamp_GetSet_Success()
         -12 (-0.81% of base) : 75094.dasm - System.Tests.TimeZoneTests:TransitionTimeToDateTime(int,TransitionTime):System.DateTime
          -8 (-2.90% of base) : 252076.dasm - April:get_The17th():System.DateTime
          -8 (-2.90% of base) : 252101.dasm - May:get_The11th():System.DateTime

Top method improvements (percentages):
          -8 (-3.23% of base) : 251310.dasm - Humanizer.In:SeptemberOf(int):System.DateTime
          -8 (-3.23% of base) : 251296.dasm - Humanizer.In:FebruaryOf(int):System.DateTime
          -8 (-3.23% of base) : 251314.dasm - Humanizer.In:NovemberOf(int):System.DateTime
          -8 (-3.23% of base) : 251302.dasm - Humanizer.In:MayOf(int):System.DateTime
          -8 (-3.23% of base) : 251316.dasm - Humanizer.In:DecemberOf(int):System.DateTime
          -8 (-3.23% of base) : 251300.dasm - Humanizer.In:AprilOf(int):System.DateTime
          -8 (-3.23% of base) : 251304.dasm - Humanizer.In:JuneOf(int):System.DateTime
          -8 (-3.23% of base) : 251293.dasm - Humanizer.In:TheYear(int):System.DateTime
          -8 (-3.23% of base) : 251312.dasm - Humanizer.In:OctoberOf(int):System.DateTime
          -8 (-3.23% of base) : 251308.dasm - Humanizer.In:AugustOf(int):System.DateTime
          -8 (-3.23% of base) : 251306.dasm - Humanizer.In:JulyOf(int):System.DateTime
          -8 (-3.23% of base) : 251298.dasm - Humanizer.In:MarchOf(int):System.DateTime
          -8 (-2.99% of base) : 246728.dasm - FluentAssertions.FluentDateTimeExtensions:March(int,int):System.DateTime
          -8 (-2.99% of base) : 246731.dasm - FluentAssertions.FluentDateTimeExtensions:June(int,int):System.DateTime
          -8 (-2.99% of base) : 251294.dasm - Humanizer.In:get_January():System.DateTime
          -8 (-2.99% of base) : 251305.dasm - Humanizer.In:get_July():System.DateTime
          -8 (-2.99% of base) : 246736.dasm - FluentAssertions.FluentDateTimeExtensions:November(int,int):System.DateTime
          -8 (-2.99% of base) : 251303.dasm - Humanizer.In:get_June():System.DateTime
          -8 (-2.99% of base) : 246726.dasm - FluentAssertions.FluentDateTimeExtensions:January(int,int):System.DateTime
          -8 (-2.99% of base) : 251309.dasm - Humanizer.In:get_September():System.DateTime

583 total methods with Code Size differences (583 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## coreclr_tests.pmi.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 357444
Total bytes of diff: 358644
Total bytes of delta: 1200 (0.34% of base)
Total relative delta: -0.93
    diff is a regression.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         712 : 227461.dasm (2.84% of base)
         712 : 229521.dasm (2.87% of base)

Top file improvements (bytes):
         -56 : 212961.dasm (-0.04% of base)
         -56 : 221323.dasm (-0.04% of base)
         -12 : 238045.dasm (-2.54% of base)
          -4 : 243599.dasm (-6.67% of base)
          -4 : 85864.dasm (-0.97% of base)
          -4 : 128215.dasm (-0.74% of base)
          -4 : 216414.dasm (-0.75% of base)
          -4 : 84608.dasm (-0.57% of base)
          -4 : 128625.dasm (-0.85% of base)
          -4 : 243601.dasm (-6.25% of base)
          -4 : 86755.dasm (-2.00% of base)
          -4 : 251938.dasm (-1.33% of base)
          -4 : 243625.dasm (-8.33% of base)
          -4 : 243627.dasm (-8.33% of base)
          -4 : 243629.dasm (-8.33% of base)
          -4 : 243651.dasm (-6.67% of base)
          -4 : 250064.dasm (-9.09% of base)
          -4 : 245536.dasm (-0.14% of base)
          -4 : 84544.dasm (-0.65% of base)
          -4 : 246854.dasm (-1.39% of base)

30 total files with Code Size differences (28 improved, 2 regressed), 0 unchanged.

Top method regressions (bytes):
         712 ( 2.84% of base) : 227461.dasm - lclfldrem:Main():int
         712 ( 2.87% of base) : 229521.dasm - lclfldrem:Main():int

Top method improvements (bytes):
         -56 (-0.04% of base) : 212961.dasm - u4div:Main():int
         -56 (-0.04% of base) : 221323.dasm - u4rem:Main():int
         -12 (-2.54% of base) : 238045.dasm - BenchmarksGame.Fasta_1:SelectNucleotides(BenchmarksGame.Fasta_1+Frequency[],System.Int32[]):System.Byte[]
          -4 (-6.67% of base) : 243599.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns5(System.Int32[]):int
          -4 (-0.97% of base) : 85864.dasm - ILGEN_0x1ad7535f:Method_0x2ddbcfb4(short):int
          -4 (-0.74% of base) : 128215.dasm - testout1:Func_0_3_6_4_4():long
          -4 (-0.75% of base) : 216414.dasm - SoDBench.Program:DeleteDirectory(System.IO.DirectoryInfo,int)
          -4 (-0.57% of base) : 84608.dasm - ILGEN_0xc2d6ebd8:Method_0x6228(ushort,short,int,long,short,long,int):int
          -4 (-0.85% of base) : 128625.dasm - testout1:Func_0_6_1_3_3():double
          -4 (-6.25% of base) : 243601.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns10(System.Int32[]):int
          -4 (-2.00% of base) : 86755.dasm - ILGEN_0x68eb95f0:Method_0x2dae(byte,int,long,byte,ushort,long):float
          -4 (-1.33% of base) : 251938.dasm - Test:Main(System.String[]):int
          -4 (-8.33% of base) : 243625.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns3(System.Int32[]):int
          -4 (-8.33% of base) : 243627.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns5(System.Int32[]):int
          -4 (-8.33% of base) : 243629.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns10(System.Int32[]):int
          -4 (-6.67% of base) : 243651.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns3(System.Int32[]):int
          -4 (-9.09% of base) : 250064.dasm - UDivConst:U4_Div_5(int):int
          -4 (-0.14% of base) : 245536.dasm - MemoryAlloc:SteadyState():this
          -4 (-0.65% of base) : 84544.dasm - ILGEN_0xd4820a77:Method_0x1a2ad58f(ubyte,long,byte,float):int
          -4 (-1.39% of base) : 246854.dasm - AA:Static4():System.Char[]

Top method regressions (percentages):
         712 ( 2.87% of base) : 229521.dasm - lclfldrem:Main():int
         712 ( 2.84% of base) : 227461.dasm - lclfldrem:Main():int

Top method improvements (percentages):
          -4 (-9.09% of base) : 250064.dasm - UDivConst:U4_Div_5(int):int
          -4 (-9.09% of base) : 250063.dasm - UDivConst:U4_Div_3(int):int
          -4 (-8.33% of base) : 243625.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns3(System.Int32[]):int
          -4 (-8.33% of base) : 243627.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns5(System.Int32[]):int
          -4 (-8.33% of base) : 243629.dasm - ArrayLengthArithmeticTests:ArrayLengthDiv_cns10(System.Int32[]):int
          -4 (-7.14% of base) : 246891.dasm - UModConst:U4_Mod_3(int):int
          -4 (-7.14% of base) : 246892.dasm - UModConst:U4_Mod_5(int):int
          -4 (-6.67% of base) : 243599.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns5(System.Int32[]):int
          -4 (-6.67% of base) : 243651.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns3(System.Int32[]):int
          -4 (-6.25% of base) : 243601.dasm - ArrayLengthArithmeticTests:ArrayLengthMod_cns10(System.Int32[]):int
          -4 (-4.00% of base) : 235643.dasm - Tests:ModInBounds(System.Int32[],int)
          -4 (-3.57% of base) : 81810.dasm - Runtime_55141_2:Main():int
         -12 (-2.54% of base) : 238045.dasm - BenchmarksGame.Fasta_1:SelectNucleotides(BenchmarksGame.Fasta_1+Frequency[],System.Int32[]):System.Byte[]
          -4 (-2.00% of base) : 86755.dasm - ILGEN_0x68eb95f0:Method_0x2dae(byte,int,long,byte,ushort,long):float
          -4 (-1.39% of base) : 246854.dasm - AA:Static4():System.Char[]
          -4 (-1.33% of base) : 251938.dasm - Test:Main(System.String[]):int
          -4 (-0.97% of base) : 85864.dasm - ILGEN_0x1ad7535f:Method_0x2ddbcfb4(short):int
          -4 (-0.97% of base) : 87522.dasm - ILGEN_0xa83217d:Method_0xf3555db(long,long,int,int,short,byte):int
          -4 (-0.85% of base) : 128625.dasm - testout1:Func_0_6_1_3_3():double
          -4 (-0.75% of base) : 216414.dasm - SoDBench.Program:DeleteDirectory(System.IO.DirectoryInfo,int)

30 total methods with Code Size differences (28 improved, 2 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.crossgen2.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 69452
Total bytes of diff: 68536
Total bytes of delta: -916 (-1.32% of base)
Total relative delta: -1.36
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -48 : 25882.dasm (-2.49% of base)
         -44 : 25884.dasm (-2.90% of base)
         -44 : 31960.dasm (-2.30% of base)
         -40 : 28832.dasm (-1.36% of base)
         -32 : 28835.dasm (-1.86% of base)
         -32 : 25883.dasm (-2.71% of base)
         -32 : 31959.dasm (-2.32% of base)
         -32 : 25881.dasm (-2.71% of base)
         -32 : 28811.dasm (-0.74% of base)
         -28 : 26184.dasm (-0.77% of base)
         -28 : 34583.dasm (-1.51% of base)
         -28 : 25852.dasm (-1.11% of base)
         -24 : 28824.dasm (-1.76% of base)
         -20 : 31962.dasm (-3.70% of base)
         -16 : 26713.dasm (-1.58% of base)
         -16 : 31961.dasm (-2.07% of base)
         -12 : 5774.dasm (-0.40% of base)
         -12 : 26603.dasm (-1.28% of base)
         -12 : 31963.dasm (-2.73% of base)
         -12 : 32422.dasm (-1.60% of base)

78 total files with Code Size differences (78 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -48 (-2.49% of base) : 25882.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeO(System.DateTime,System.TimeSpan,System.Span`1[System.Byte],byref):bool
         -44 (-2.90% of base) : 25884.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeG(System.DateTime,System.TimeSpan,System.Span`1[System.Byte],byref):bool
         -44 (-2.30% of base) : 31960.dasm - System.DateTimeFormat:TryFormatO(System.DateTime,System.TimeSpan,System.Span`1[System.Char],byref):bool
         -40 (-1.36% of base) : 28832.dasm - System.TimeZoneInfo:GetIsDaylightSavingsFromUtc(System.DateTime,int,System.TimeSpan,System.TimeZoneInfo+AdjustmentRule,System.Nullable`1[System.Int32],byref,System.TimeZoneInfo):bool
         -32 (-1.86% of base) : 28835.dasm - System.TimeZoneInfo:GetIsDaylightSavings(System.DateTime,System.TimeZoneInfo+AdjustmentRule,System.Globalization.DaylightTimeStruct):bool
         -32 (-2.71% of base) : 25883.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeL(System.DateTime,System.Span`1[System.Byte],byref):bool
         -32 (-2.32% of base) : 31959.dasm - System.DateTimeFormat:TryFormatR(System.DateTime,System.TimeSpan,System.Span`1[System.Char],byref):bool
         -32 (-2.71% of base) : 25881.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeR(System.DateTime,System.Span`1[System.Byte],byref):bool
         -32 (-0.74% of base) : 28811.dasm - System.TimeZoneInfo:GetAdjustmentRules():System.TimeZoneInfo+AdjustmentRule[]:this
         -28 (-0.77% of base) : 26184.dasm - System.Globalization.TimeSpanFormat:TryFormatStandard(System.TimeSpan,int,System.String,System.Span`1[System.Char],byref):bool
         -28 (-1.51% of base) : 34583.dasm - DecCalc:ScaleResult(long,int,int):int
         -28 (-1.11% of base) : 25852.dasm - System.Buffers.Text.Utf8Formatter:TryFormat(System.TimeSpan,System.Span`1[System.Byte],byref,System.Buffers.StandardFormat):bool
         -24 (-1.76% of base) : 28824.dasm - System.TimeZoneInfo:TransitionTimeToDateTime(int,System.TimeZoneInfo+TransitionTime):System.DateTime
         -20 (-3.70% of base) : 31962.dasm - System.DateTimeFormat:TryFormatDateOnlyO(int,int,int,System.Span`1[System.Char]):bool
         -16 (-1.58% of base) : 26713.dasm - System.Globalization.HebrewCalendar:HebrewToGregorian(int,int,int,int,int,int,int):System.DateTime
         -16 (-2.07% of base) : 31961.dasm - System.DateTimeFormat:TryFormatDateOnlyR(int,int,int,int,System.Span`1[System.Char]):bool
         -12 (-0.40% of base) : 5774.dasm - BigNumber:DblToRgbFast(double,System.Byte[],byref,byref):bool
         -12 (-1.28% of base) : 26603.dasm - System.Globalization.ISOWeek:ToDateTime(int,int,int):System.DateTime
         -12 (-2.73% of base) : 31963.dasm - System.DateTimeFormat:TryFormatTimeOnlyR(int,int,int,System.Span`1[System.Char]):bool
         -12 (-1.60% of base) : 32422.dasm - System.DateTime:AddMonths(int):System.DateTime:this

Top method improvements (percentages):
          -4 (-4.76% of base) : 32413.dasm - System.DateTime:DaysToYear(int):int
          -4 (-3.85% of base) : 32388.dasm - System.DateTime:get_Hour():int:this
          -4 (-3.85% of base) : 25896.dasm - System.Buffers.Text.FormattingHelpers:CountDecimalTrailingZeros(int,byref):int
         -20 (-3.70% of base) : 31962.dasm - System.DateTimeFormat:TryFormatDateOnlyO(int,int,int,System.Span`1[System.Char]):bool
          -4 (-3.45% of base) : 30914.dasm - System.Number:UInt32ToDecChars(long,int,int):long
          -4 (-3.45% of base) : 30915.dasm - System.Number:UInt32ToDecChars(long,int,int):long
         -12 (-3.37% of base) : 25890.dasm - System.Buffers.Text.FormattingHelpers:WriteFourDecimalDigits(int,System.Span`1[System.Byte],int)
         -12 (-3.23% of base) : 31957.dasm - System.DateTimeFormat:WriteFourDecimalDigits(int,System.Span`1[System.Char],int)
          -4 (-3.03% of base) : 197790.dasm - Number:Int32ToDecChars(long,byref,int,int)
         -44 (-2.90% of base) : 25884.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeG(System.DateTime,System.TimeSpan,System.Span`1[System.Byte],byref):bool
          -8 (-2.90% of base) : 25924.dasm - System.Buffers.StandardFormat:Format(System.Span`1[System.Char]):int:this
         -12 (-2.73% of base) : 31963.dasm - System.DateTimeFormat:TryFormatTimeOnlyR(int,int,int,System.Span`1[System.Char]):bool
         -32 (-2.71% of base) : 25883.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeL(System.DateTime,System.Span`1[System.Byte],byref):bool
         -32 (-2.71% of base) : 25881.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeR(System.DateTime,System.Span`1[System.Byte],byref):bool
         -48 (-2.49% of base) : 25882.dasm - System.Buffers.Text.Utf8Formatter:TryFormatDateTimeO(System.DateTime,System.TimeSpan,System.Span`1[System.Byte],byref):bool
          -4 (-2.44% of base) : 32376.dasm - System.DateTime:IsLeapYear(int):bool
         -32 (-2.32% of base) : 31959.dasm - System.DateTimeFormat:TryFormatR(System.DateTime,System.TimeSpan,System.Span`1[System.Char],byref):bool
         -44 (-2.30% of base) : 31960.dasm - System.DateTimeFormat:TryFormatO(System.DateTime,System.TimeSpan,System.Span`1[System.Char],byref):bool
          -8 (-2.25% of base) : 27426.dasm - System.Globalization.CalendricalCalculationsHelper:CenturiesFrom1900(int):double
          -4 (-2.13% of base) : 32395.dasm - System.DateTime:GetTime(byref,byref,byref):this

78 total methods with Code Size differences (78 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 102260
Total bytes of diff: 101644
Total bytes of delta: -616 (-0.60% of base)
Total relative delta: -0.71
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -24 : 122361.dasm (-1.55% of base)
         -24 : 122093.dasm (-0.92% of base)
         -24 : 122360.dasm (-1.27% of base)
         -24 : 122090.dasm (-0.98% of base)
         -16 : 122149.dasm (-0.41% of base)
         -16 : 122191.dasm (-0.41% of base)
         -12 : 115322.dasm (-1.59% of base)
         -12 : 210392.dasm (-0.28% of base)
         -12 : 122849.dasm (-0.30% of base)
         -12 : 115321.dasm (-1.82% of base)
          -8 : 121964.dasm (-1.03% of base)
          -8 : 33406.dasm (-0.67% of base)
          -8 : 121966.dasm (-1.03% of base)
          -8 : 121971.dasm (-1.01% of base)
          -8 : 121967.dasm (-1.01% of base)
          -8 : 115337.dasm (-1.31% of base)
          -8 : 121972.dasm (-1.01% of base)
          -8 : 121959.dasm (-1.03% of base)
          -8 : 121976.dasm (-1.03% of base)
          -8 : 122345.dasm (-1.48% of base)

76 total files with Code Size differences (76 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -24 (-1.55% of base) : 122361.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTimeOffset
         -24 (-0.92% of base) : 122093.dasm - System.Xml.Schema.XmlDateTimeConverter:ToDateTimeOffset(System.String):System.DateTimeOffset:this
         -24 (-1.27% of base) : 122360.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTime
         -24 (-0.98% of base) : 122090.dasm - System.Xml.Schema.XmlDateTimeConverter:ToDateTime(System.String):System.DateTime:this
         -16 (-0.41% of base) : 122149.dasm - System.Xml.Schema.XmlUntypedConverter:ChangeType(System.String,System.Type,System.Xml.IXmlNamespaceResolver):System.Object:this
         -16 (-0.41% of base) : 122191.dasm - System.Xml.Schema.XmlUntypedStringConverter:FromString(System.String,System.Type,System.Xml.IXmlNamespaceResolver):System.Object:this
         -12 (-1.59% of base) : 115322.dasm - System.Xml.BinXmlDateTime:GetFractions(System.DateTimeOffset):int
         -12 (-0.28% of base) : 210392.dasm - System.Formats.Asn1.AsnDecoder:ParseGeneralizedTime(int,System.ReadOnlySpan`1[Byte]):System.DateTimeOffset
         -12 (-0.30% of base) : 122849.dasm - BigNumber:DblToRgbFast(double,System.Byte[],byref,byref):bool
         -12 (-1.82% of base) : 115321.dasm - System.Xml.BinXmlDateTime:GetFractions(System.DateTime):int
          -8 (-1.03% of base) : 121964.dasm - System.Xml.Schema.XmlBaseConverter:StringToGMonthDay(System.String):System.DateTime
          -8 (-0.67% of base) : 33406.dasm - Microsoft.VisualBasic.DateAndTime:DateSerial(int,int,int):System.DateTime
          -8 (-1.03% of base) : 121966.dasm - System.Xml.Schema.XmlBaseConverter:StringToGYearMonth(System.String):System.DateTime
          -8 (-1.01% of base) : 121971.dasm - System.Xml.Schema.XmlBaseConverter:StringToGMonthDayOffset(System.String):System.DateTimeOffset
          -8 (-1.01% of base) : 121967.dasm - System.Xml.Schema.XmlBaseConverter:StringToDateOffset(System.String):System.DateTimeOffset
          -8 (-1.31% of base) : 115337.dasm - System.Xml.BinXmlDateTime:XsdDateToDateTime(long):System.DateTime
          -8 (-1.01% of base) : 121972.dasm - System.Xml.Schema.XmlBaseConverter:StringToGYearOffset(System.String):System.DateTimeOffset
          -8 (-1.03% of base) : 121959.dasm - System.Xml.Schema.XmlBaseConverter:StringToDateTime(System.String):System.DateTime
          -8 (-1.03% of base) : 121976.dasm - System.Xml.Schema.XmlBaseConverter:StringToTime(System.String):System.DateTime
          -8 (-1.48% of base) : 122345.dasm - System.Xml.Schema.XsdDateTime:InitiateXsdDateTime(Parser):this

Top method improvements (percentages):
          -4 (-3.33% of base) : 194251.dasm - Number:Int32ToDecChars(long,byref,int,int)
          -8 (-2.08% of base) : 221230.dasm - Microsoft.Extensions.DependencyInjection.DependencyInjectionEventSource:CallSiteBuilt(Microsoft.Extensions.DependencyInjection.ServiceProvider,System.Type,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite):this
          -8 (-1.94% of base) : 160242.dasm - System.Data.ProviderBase.DbBuffer:ReadDate(int):System.DateTime:this
         -12 (-1.82% of base) : 115321.dasm - System.Xml.BinXmlDateTime:GetFractions(System.DateTime):int
         -12 (-1.59% of base) : 115322.dasm - System.Xml.BinXmlDateTime:GetFractions(System.DateTimeOffset):int
         -24 (-1.55% of base) : 122361.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTimeOffset
          -8 (-1.48% of base) : 122345.dasm - System.Xml.Schema.XsdDateTime:InitiateXsdDateTime(Parser):this
          -4 (-1.47% of base) : 135404.dasm - Newtonsoft.Json.JsonTextWriter:WriteNumberToBuffer(int,bool):int:this
          -8 (-1.44% of base) : 122370.dasm - System.Xml.Schema.XsdDateTime:.ctor(Parser):this
          -8 (-1.35% of base) : 136020.dasm - Newtonsoft.Json.Utilities.DateTimeUtils:CreateDateTime(Newtonsoft.Json.Utilities.DateTimeParser):System.DateTime
          -8 (-1.35% of base) : 164107.dasm - Newtonsoft.Json.Bson.Utilities.DateTimeUtils:CreateDateTime(Newtonsoft.Json.Bson.Utilities.DateTimeParser):System.DateTime
          -8 (-1.32% of base) : 221235.dasm - Microsoft.Extensions.DependencyInjection.DependencyInjectionEventSource:WriteServiceProviderBuilt(Microsoft.Extensions.DependencyInjection.ServiceProvider):this
          -8 (-1.31% of base) : 115337.dasm - System.Xml.BinXmlDateTime:XsdDateToDateTime(long):System.DateTime
          -8 (-1.31% of base) : 160246.dasm - System.Data.ProviderBase.DbBuffer:ReadDateTime(int):System.DateTime:this
         -24 (-1.27% of base) : 122360.dasm - System.Xml.Schema.XsdDateTime:op_Implicit(System.Xml.Schema.XsdDateTime):System.DateTime
          -4 (-1.23% of base) : 207341.dasm - System.IO.Compression.ZipHelper:DateTimeToDosTime(System.DateTime):int
          -4 (-1.20% of base) : 115314.dasm - System.Xml.BinXmlDateTime:XsdKatmaiTimeToString(System.Byte[],int):System.String
          -4 (-1.14% of base) : 33893.dasm - Microsoft.VisualBasic.VBMath:GetTimer():float
          -8 (-1.12% of base) : 122369.dasm - System.Xml.Schema.XsdDateTime:.ctor(System.String,int):this
          -8 (-1.10% of base) : 122346.dasm - System.Xml.Schema.XsdDateTime:TryParse(System.String,int,byref):bool

76 total methods with Code Size differences (76 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries_tests.pmi.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 342340
Total bytes of diff: 337808
Total bytes of delta: -4532 (-1.32% of base)
Total relative delta: -13.54
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -56 : 310094.dasm (-1.81% of base)
         -48 : 49104.dasm (-0.24% of base)
         -40 : 310079.dasm (-1.43% of base)
         -40 : 310083.dasm (-1.43% of base)
         -40 : 310090.dasm (-0.87% of base)
         -32 : 275957.dasm (-1.11% of base)
         -32 : 287626.dasm (-1.10% of base)
         -20 : 43803.dasm (-0.46% of base)
         -20 : 309884.dasm (-2.28% of base)
         -16 : 287625.dasm (-0.30% of base)
         -16 : 275956.dasm (-0.30% of base)
         -16 : 43635.dasm (-0.76% of base)
         -12 : 43805.dasm (-0.34% of base)
         -12 : 49130.dasm (-1.27% of base)
         -12 : 295849.dasm (-1.64% of base)
         -12 : 309776.dasm (-1.90% of base)
         -12 : 49144.dasm (-1.42% of base)
         -12 : 45018.dasm (-0.81% of base)
          -8 : 139504.dasm (-3.03% of base)
          -8 : 292318.dasm (-3.28% of base)

581 total files with Code Size differences (581 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -56 (-1.81% of base) : 310094.dasm - <GetYear_TestData>d__0:MoveNext():bool:this
         -48 (-0.24% of base) : 49104.dasm - <ParseExact_ValidInput_Succeeds_MemberData>d__149:MoveNext():bool:this
         -40 (-1.43% of base) : 310079.dasm - <GetEra_TestData>d__0:MoveNext():bool:this
         -40 (-1.43% of base) : 310083.dasm - <GetMonth_TestData>d__0:MoveNext():bool:this
         -40 (-0.87% of base) : 310090.dasm - <GetWeekOfYear_TestData>d__6:MoveNext():bool:this
         -32 (-1.11% of base) : 275957.dasm - DataContractJsonSerializerTests:DCJS_VerifyDateTimeForDateTimeFormat()
         -32 (-1.10% of base) : 287626.dasm - DataContractJsonSerializerTests:DCJS_VerifyDateTimeForDateTimeFormat()
         -20 (-0.46% of base) : 43803.dasm - System.Tests.DateTimeOffsetTests:Ctor_DateTime()
         -20 (-2.28% of base) : 309884.dasm - System.Globalization.Tests.TaiwanCalendarGetWeekOfYear:GetWeekOfYear_LastDayOfYear():this
         -16 (-0.30% of base) : 287625.dasm - DataContractJsonSerializerTests:DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings()
         -16 (-0.30% of base) : 275956.dasm - DataContractJsonSerializerTests:DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings()
         -16 (-0.76% of base) : 43635.dasm - System.Tests.DateTimeTests:Today_Get_ReturnsExpected():this
         -12 (-0.34% of base) : 43805.dasm - System.Tests.DateTimeOffsetTests:Ctor_DateTime_TimeSpan()
         -12 (-1.27% of base) : 49130.dasm - <>c__DisplayClass4_0:<Ctor_DateTime_Invalid>b__0():System.Object:this
         -12 (-1.64% of base) : 295849.dasm - System.Net.Primitives.Functional.Tests.CookieTest:Timestamp_GetSet_Success()
         -12 (-1.90% of base) : 309776.dasm - System.Globalization.Tests.GregorianCalendarIsLeapYear:IsLeapYearTest(int):this
         -12 (-1.42% of base) : 49144.dasm - <>c__DisplayClass6_0:<Ctor_DateTime_TimeSpan_Invalid>b__7():System.Object:this
         -12 (-0.81% of base) : 45018.dasm - System.Tests.TimeZoneTests:TransitionTimeToDateTime(int,TransitionTime):System.DateTime
          -8 (-3.03% of base) : 139504.dasm - FluentAssertions.FluentDateTimeExtensions:June(int,int):System.DateTime
          -8 (-3.28% of base) : 292318.dasm - Humanizer.In:FebruaryOf(int):System.DateTime

Top method improvements (percentages):
          -8 (-3.28% of base) : 292318.dasm - Humanizer.In:FebruaryOf(int):System.DateTime
          -8 (-3.28% of base) : 292328.dasm - Humanizer.In:JulyOf(int):System.DateTime
          -8 (-3.28% of base) : 292324.dasm - Humanizer.In:MayOf(int):System.DateTime
          -8 (-3.28% of base) : 292334.dasm - Humanizer.In:OctoberOf(int):System.DateTime
          -8 (-3.28% of base) : 292315.dasm - Humanizer.In:TheYear(int):System.DateTime
          -8 (-3.28% of base) : 292336.dasm - Humanizer.In:NovemberOf(int):System.DateTime
          -8 (-3.28% of base) : 292322.dasm - Humanizer.In:AprilOf(int):System.DateTime
          -8 (-3.28% of base) : 292332.dasm - Humanizer.In:SeptemberOf(int):System.DateTime
          -8 (-3.28% of base) : 292326.dasm - Humanizer.In:JuneOf(int):System.DateTime
          -8 (-3.28% of base) : 292320.dasm - Humanizer.In:MarchOf(int):System.DateTime
          -8 (-3.28% of base) : 292330.dasm - Humanizer.In:AugustOf(int):System.DateTime
          -8 (-3.28% of base) : 292338.dasm - Humanizer.In:DecemberOf(int):System.DateTime
          -8 (-3.03% of base) : 139504.dasm - FluentAssertions.FluentDateTimeExtensions:June(int,int):System.DateTime
          -8 (-3.03% of base) : 293174.dasm - July:get_The1st():System.DateTime
          -8 (-3.03% of base) : 293301.dasm - November:get_The1st():System.DateTime
          -8 (-3.03% of base) : 139506.dasm - FluentAssertions.FluentDateTimeExtensions:August(int,int):System.DateTime
          -8 (-3.03% of base) : 293080.dasm - April:get_The1st():System.DateTime
          -8 (-3.03% of base) : 139503.dasm - FluentAssertions.FluentDateTimeExtensions:May(int,int):System.DateTime
          -8 (-3.03% of base) : 292329.dasm - Humanizer.In:get_August():System.DateTime
          -8 (-3.03% of base) : 293111.dasm - May:get_The1st():System.DateTime

581 total methods with Code Size differences (581 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

**Comment by JulieLeeMSFT** [comment]
> Yes, the numbers were mostly improvements with an exception of `ToString(4)` benchmark and that was confusing to me, so I re-ran the benchmarks again:

@echesakov ToString numbers show some improvments and some regression. So, do you want that to be addressed before approving the code?

**Comment by echesakovMSFT** [comment]
@JulieLeeMSFT I wouldn't worry about `ToString(4)` but I want to understand why `lclfldrem:Main():int` regressed.

**Comment by SingleAccretion** [comment]
@echesakovMSFT watch out for spurious diffs due to #53773. I've seen these tests show big differences in the past (see diffs in #53748).

**Comment by echesakovMSFT** [comment]
Thanks for the note @SingleAccretion - I wasn't aware of that issue. 
I looked at the jitdumps and the regressions are indeed due to #53773.

File: src/coreclr/jit/codegenarm64.cpp (hunk 3 above)
Comment (echesakovMSFT) [reply src/coreclr/jit/codegenarm64.cpp:1866]: I like the code suggested by @SingleAccretion.
@pentp can you please consider the change?

File: src/coreclr/jit/lower.cpp (hunk 2 above)
Comment (echesakovMSFT) [reply src/coreclr/jit/lower.cpp:5275]: Yes, this should be under `TARGET_ARM64`.

**Comment by echesakovMSFT** [comment]
@pentp Can you please address the feedback by @SingleAccretion, so we can merge the PR before RC1?

**Comment by AndyAyersMS** [comment]
@echesakov do you want to push the changes discussed above? We are running out of time for RC1.

**Comment by echesakovMSFT** [comment]
@pentp I pushed the changes suggested by @SingleAccretion. 
I hope you don't mind me pushing to your branch as we are eager to merge this before noon today...

**Review by echesakov — APPROVED** [review]

**Comment by echesakovMSFT** [comment]
@AndyAyersMS Can you please also take a look? In case I missed anything

**Review by EgorBo — APPROVED** [review]

**Review by AndyAyersMS — APPROVED** [review]
LGTM too.

**Comment by echesakovMSFT** [comment]
**runtime (Libraries Test Run checked coreclr windows x86 Release)** failure is due to #57471

**Comment by AndyAyersMS** [comment]
Since the change is arm64 specific I think we can merge despite those failures. Anyone disagree?

**Comment by kunalspathak** [comment]
Improvements: https://github.com/dotnet/perf-autofiling-issues/issues/828 and https://github.com/dotnet/perf-autofiling-issues/issues/1109
