### PR TITLE
[EventPipe] Block EventPipeProvider Deletion for ongoing callbacks

### LINKED ISSUE #80666: tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror failure
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=137937
Build error leg or test failing: Build / coreclr  Pri1 Runtime Tests Run  osx x64 checked / Send tests to Helix (Unix)
Pull request: https://github.com/dotnet/runtime/pull/80626

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorPattern": "eventsourceerror\\.sh:.*Segmentation fault",
  "BuildRetry": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 7/21/2024 2:00:18 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[766419](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766419)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766419&view=ms.vss-test-web.build-test-results-tab&runId=19532444&resultId=111397)||
|[757010](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757010)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757010&view=ms.vss-test-web.build-test-results-tab&runId=19198684&resultId=111397)||
|[756145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756145)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=756145&view=ms.vss-test-web.build-test-results-tab&runId=19171508&resultId=111397)|dotnet/runtime#105535|
|[754023](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754023)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754023&view=ms.vss-test-web.build-test-results-tab&runId=19111704&resultId=111387)||
|[753599](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753599)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753599&view=ms.vss-test-web.build-test-results-tab&runId=19100226&resultId=106007)|dotnet/runtime#105372|
|[752189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752189)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752189&view=ms.vss-test-web.build-test-results-tab&runId=19058272&resultId=111397)||
|[751644](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751644)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751644&view=ms.vss-test-web.build-test-results-tab&runId=19039920&resultId=111397)|dotnet/runtime#101143|
|[751444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751444)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751444&view=ms.vss-test-web.build-test-results-tab&runId=19030702&resultId=111387)|dotnet/runtime#105236|
|[751086](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751086)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751086&view=ms.vss-test-web.build-test-results-tab&runId=19020094&resultId=111388)|dotnet/runtime#105260|
|[750999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750999)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750999&view=ms.vss-test-web.build-test-results-tab&runId=19018506&resultId=111397)|dotnet/runtime#105284|
|[750809](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750809)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750809&view=ms.vss-test-web.build-test-results-tab&runId=19013570&resultId=111380)||
|[750696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750696)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750696&view=ms.vss-test-web.build-test-results-tab&runId=19009170&resultId=108836)|dotnet/runtime#104399|
|[750584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750584)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750584&view=ms.vss-test-web.build-test-results-tab&runId=19006384&resultId=108816)|dotnet/runtime#104999|
|[750239](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750239)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750239&view=ms.vss-test-web.build-test-results-tab&runId=18998258&resultId=111397)|dotnet/runtime#105030|
|[749625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749625)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749625&view=ms.vss-test-web.build-test-results-tab&runId=18972706&resultId=111397)||
|[749490](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749490)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749490&view=ms.vss-test-web.build-test-results-tab&runId=18965740&resultId=111370)|dotnet/runtime#105178|
|[749184](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749184)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749184&view=ms.vss-test-web.build-test-results-tab&runId=18953996&resultId=111397)|dotnet/runtime#105194|
|[749057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749057)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749057&view=ms.vss-test-web.build-test-results-tab&runId=18949658&resultId=111387)|dotnet/runtime#105127|
|[747806](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747806)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747806&view=ms.vss-test-web.build-test-results-tab&runId=18910126&resultId=111397)|dotnet/runtime#105131|
|[747753](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747753)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747753&view=ms.vss-test-web.build-test-results-tab&runId=18909426&resultId=111387)|dotnet/runtime#105129|
|[747532](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747532)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=747532&view=ms.vss-test-web.build-test-results-tab&runId=18900466&resultId=111397)|dotnet/runtime#105109|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|21|

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes https://github.com/dotnet/runtime/issues/80666

This PR aims to align behavior between [EventPipe's Unregister logic](https://github.com/dotnet/runtime/blob/7dd55a0aa662dc70e85149e66b8c3f19456408ed/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventPipeEventProvider.cs#L92) and [ETW's Unregister logic]( https://github.com/dotnet/runtime/blob/7dd55a0aa662dc70e85149e66b8c3f19456408ed/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs#L858) by blocking EventPipe's DeleteProvider for in-flight callbacks, so that the gchandle will not be [freed](https://github.com/dotnet/runtime/blob/7dd55a0aa662dc70e85149e66b8c3f19456408ed/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventPipeEventProvider.cs#L97) before the callback [completes](https://github.com/dotnet/runtime/blob/7dd55a0aa662dc70e85149e66b8c3f19456408ed/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventPipeEventProvider.cs#L65-L69). ([ETW has its own lock for ETW commands/callbacks](https://github.com/dotnet/runtime/blob/7dd55a0aa662dc70e85149e66b8c3f19456408ed/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs#L157-L163)).

Our [initial attempt to add a corresponding EventPipe lock](https://github.com/dotnet/runtime/pull/105734) revealed to us that locks should not be taken around the callback (specifically performing the callback within a lock) because it [breaks concurrent callbacks scenarios](https://github.com/dotnet/runtime/pull/105734#issuecomment-2263786867).

In this PR, we track the EventPipeProvider's callbacks that have been [prepared](https://github.com/dotnet/runtime/blob/5fb42a458bc9c476978ec45092cc398f92371186/src/native/eventpipe/ep-provider.c#L70) but not yet [invoked](https://github.com/dotnet/runtime/blob/5fb42a458bc9c476978ec45092cc398f92371186/src/native/eventpipe/ep-provider.c#L419) (i.e. in-flight callbacks), and leverage a signal set/wait to block the [EventPipe Provider's deferred deletion](https://github.com/dotnet/runtime/blob/5fb42a458bc9c476978ec45092cc398f92371186/src/native/eventpipe/ep.c#L1319).

-------------------------------------------
## Repro

Reproduced the crash by:
```C#
Console.WriteLine("MIHW Ready to create TestEventSource");
Console.ReadKey();
var testEventSource = new TestEventSource();
Console.WriteLine("MIHW Ready to dispose TestEventSource");
Console.ReadKey();
testEventSource.Dispose();
Console.WriteLine($"MIHW TestEventSource disposed.");

[EventSource(Name = "TestEventSource")]
public class TestEventSource : EventSource
...
```

1. Launching the above sample app in windbg
2. Connecting an EventPipe session via `dotnet-trace collect --providers TestEventSource -p <pid of app from dotnet-trace ps>`
3. Setting a breakpoint in ep-provider.c provider_invoke_callback at callback invocation
4. Closing the EventPipe session (enter || ctrl + c) to hit that breakpoint and freezing the thread
5. Continuing the application logic by disposing the EventSource
6. Unfreezing the previously frozen thread and continuing

Resulted in a NullReferenceException crash.

## Testing

Performed the same steps as above with the changes in this PR, Dispose is blocked until the callback completes.

### CODE REVIEW

**Comment by jkotas** [comment]
Can you re-enable the disabled test?

**Comment by jkotas** [comment]
The change LGTM, but I am not deeply familiar with EventPipe code.

File: src/native/eventpipe/ep.c [hunk 1]
```diff
@@ -1313,15 +1317,25 @@ ep_delete_provider (EventPipeProvider *provider)
...
+			// otherwise callbacks might never stop coming
+			EP_ASSERT (provider->callback_func == NULL);
+			if (provider->uninvoked_prepared_callbacks_counter > 0)
+				wait_for_provider_callbacks_completion = true;
 		} else {
 			config_delete_provider (ep_config_get (), provider);
 		}
 	EP_LOCK_EXIT (section1)
 
+	if (wait_for_provider_callbacks_completion)
```
Comment (davmason) [inline src/native/eventpipe/ep.c:1336]: It's not immediately obvious to me why we need to wait here, can you add a comment explaining what it prevents?

Comment (davmason) [reply src/native/eventpipe/ep.c:1336]: From looking at the issue I see that the issue is that the GCHandle gets deleted on the managed code side of things, but how does this blocking wait prevent that?

File: src/native/eventpipe/ep.c [hunk 2]
```diff
@@ -1313,15 +1317,25 @@ ep_delete_provider (EventPipeProvider *provider)
...
 	EP_LOCK_ENTER (section1)
 		if (enabled ()) {
 			// Save the provider until the end of the tracing session.
 			ep_provider_set_delete_deferred (provider, true);
+
+			// the callback func must be previously set to null,
+			// otherwise callbacks might never stop coming
+			EP_ASSERT (provider->callback_func == NULL);
+			if (provider->uninvoked_prepared_callbacks_counter > 0)
+				wait_for_provider_callbacks_completion = true;
```
Comment (noahfalk) [inline src/native/eventpipe/ep.c:1330]: I'd add a comment on EventPipeEventProvider.Unregister() and here in ep_delete_provider() that if these functions are called within a callback the current behavior is a deadlock. That deadlock condition already exists for ETW and we have [an assert](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs,165) that would fire in debug builds, but nothing actually prevents users from writing their code to hit it. Its possible we'll see someone who has written an EventSource which does this and they never encountered the deadlock before because they always used EventPipe instead of ETW to do their tracing.

I'd recommend we open a bug describing that issue but I'd be fine if it gets fixed separately as the ETW portion is a pre-existing problem. A repro is roughly:

```C#
MyEventSource eventSource = new MyEventSource();
Console.WriteLine("MyEventSource is read to be enabled");
Console.ReadLine();

[EventSource(Name ="MyEventSource")]
class MyEventSource : EventSource
{
    override protected void OnEventCommand(EventCommandEventArgs command)
    {
        Console.WriteLine($"Command: {command.Command}");
        this.Dispose();
        Console.WriteLine($"Dispose() complete");
    }
}
```

If you use ETW to enable the provider you will see 'Command' get printed, but not 'Dispose()' because the thread hangs. After this PR the same behavior will also be true for EventPipe.

File: src/native/eventpipe/ep-provider.c [hunk 3]
```diff
@@ -78,6 +78,11 @@ provider_prepare_callback_data (
 	EP_ASSERT (provider != NULL);
 	EP_ASSERT (provider_callback_data != NULL);
 
+	ep_requires_lock_held ();
+
+	if (provider->callback_func != NULL)
```
Comment (lateralusX) [inline src/native/eventpipe/ep-provider.c:83]: Any reason why this can't go inside ep_provider_callback_data_init and then do the decrement and potential signaling in ep_provider_callback_data_fini when callback data gets freed?

File: src/native/eventpipe/ep-provider.c [hunk 4]
```diff
@@ -427,6 +440,19 @@ provider_invoke_callback (EventPipeProviderCallbackData *provider_callback_data)
 			callback_data /* CallbackContext */);
 	}
 
+	// The callback completed, can take the lock again.
```
Comment (lateralusX) [inline src/native/eventpipe/ep-provider.c:443]: Couldn't this be done inside ep_provider_callback_data_fini to prevent logic to spread out? Provider callback data will always be allocated/inited and when done used fini/freed after being used.

**Review by noahfalk — APPROVED** [review]
Few comments inline but mostly looks good!

File: src/native/eventpipe/ep.c (hunk 1 above)
Comment (noahfalk) [reply src/native/eventpipe/ep.c:1336]: Right before managed code deletes the GCHandle it calls DeleteProvider() which comes into this code. Blocking ensures that all the callbacks running asynchronously which might have tried to use that GCHandle are complete before the GCHandle gets deleted.

Separately it also just gives ETW and EventPipe the same blocking behavior for Unregister() so that users+ourselves don't have to reason about two different synchronization patterns depending on whether EventPipe or ETW was used.

File: src/native/eventpipe/ep-provider.c (hunk 3 above)
Comment (noahfalk) [reply src/native/eventpipe/ep-provider.c:83]: I'd be fine with that but I'm curious, do you want to just get rid of provider_prepare_callback_data and the caller should directly invoke provider_callback_data_init? It doesn't seem like prepare has a reason to exist if we'll move all the logic into init.

File: src/native/eventpipe/ep-provider.c (hunk 4 above)
Comment (noahfalk) [reply src/native/eventpipe/ep-provider.c:443]: It looks like some places which call fini hold the lock and others do not hold the lock. Does EP_LOCK_ENTER support re-entrancy? I didn't recall that we made use of recursive locking anywhere else.

Comment (lateralusX) [reply src/native/eventpipe/ep-provider.c:443]: No we should not use recursive locking. init/fini is normally not aware of locking since its setting up the local instance, so maybe it will be problematic to actually introduce that by moving code into fini that needs locking.

Comment (lateralusX) [reply src/native/eventpipe/ep-provider.c:443]: So then fini is probably not a good place to lock/decrease/signal.

Comment (lateralusX) [reply src/native/eventpipe/ep-provider.c:443]: My initial thought was to try to keep the increase/decrease closer together and not spread out.

File: src/native/eventpipe/ep-provider.c (hunk 3 above)
Comment (lateralusX) [reply src/native/eventpipe/ep-provider.c:83]: I guess the same point applies here then, since we need to hold lock when working with the provider, we don't want to add locking into the init function since it can be called with or without holding the lock (since its mainly setting up the internals of the callback data).

Comment (noahfalk) [reply src/native/eventpipe/ep-provider.c:83]: yeah, if we don't want init/fini to use any locking (which feels like a reasonable invariant to me) then how it is now seems good to me. We still only have one place we are incrementing and one place we are decrementing. If there is ever a need in the future to have more than one place we could do some refactoring at that time.

Comment (lateralusX) [reply src/native/eventpipe/ep-provider.c:83]: Agree, my feeling is that all this should probably happen closer to the callback invocation and not when preparing the callback data and then decrement after the running the callback since those two places can be spread out over time and code location, but as long its only in one place, we could hold that refactoring.

File: src/native/eventpipe/ep-provider.c (hunk 4 above)
Comment (lateralusX) [reply src/native/eventpipe/ep-provider.c:443]: Lets save this for future potential refactoring if pattern expands for some reasons.

**Review by lateralusX — APPROVED** [review]

File: src/native/eventpipe/ep.c (hunk 1 above)
Comment (mdh1418) [reply src/native/eventpipe/ep.c:1344]: Added a comment there describing the blocking behavior

File: src/native/eventpipe/ep-provider.c [hunk 5]
```diff
@@ -78,6 +78,11 @@ provider_prepare_callback_data (
 	EP_ASSERT (provider != NULL);
 	EP_ASSERT (provider_callback_data != NULL);
 
+	ep_requires_lock_held ();
+
+	if (provider->callback_func != NULL)
+		provider->uninvoked_prepared_callbacks_counter++;
```
[the remark this answers is not in the document]
Comment (mdh1418) [reply src/native/eventpipe/ep-provider.c]: Changed! Thanks for the suggestion

File: src/native/eventpipe/ep-provider.h [hunk 6]
```diff
@@ -42,6 +42,13 @@ struct _EventPipeProvider_Internal {
 	// True if the provider has been deleted, but that deletion
 	// has been deferred until tracing is stopped.
 	bool delete_deferred;
+	// The number of EventPipeProvider callbacks that have been
+	// prepared but not yet invoked.
```
[the remark this answers is not in the document]
Comment (mdh1418) [reply src/native/eventpipe/ep-provider.h]: Good catch, adjusted to "callbacks that have not completed"

File: src/native/eventpipe/ep.c (hunk 2 above)
Comment (mdh1418) [reply src/native/eventpipe/ep.c:1334]: Added the comment and [created an issue for the deadlock](https://github.com/dotnet/runtime/issues/106087)

**Comment by mdh1418** [comment]
/ba-g The failing tests uncaught by build analysis are https://github.com/dotnet/runtime/issues/104905 and https://github.com/dotnet/runtime/issues/103347, not sure why build analysis didn't recognize the match in 103347.
