### PR TITLE
[debugger][mono] Fix failing test `CheckVSCodeTestFunction1`

### LINKED ISSUE #95950: [wasm][debugger] Failing test - `DebuggerTests.CallFunctionOnTests.CheckVSCodeTestFunction1`
Hit on https://github.com/dotnet/runtime/pull/95832

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=494540
Build error leg or test failing: DebuggerTests.CallFunctionOnTests.DebuggerTests.CallFunctionOnTests.CheckVSCodeTestFunction1
Pull request: https://github.com/dotnet/runtime.git/pull/95832

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "cfo-res.*Value for json property named description didn't match",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
 Assert.Equal() Failure: [[cfo-res] Value for json property named description didn't match.]
 
 Expected: Array(10)
 Actual:   Array 
 Expected: {
   "type": "object",
   "className": "Array",
   "description": "Array(10)",
   "subtype": "array"
 } 
 Actual: {
   "type": "object",
   "className": "Array",
   "description": "Array",
   "objectId": "5084384295708308525.1.9"
 }
```

The actual object is missing the `subtype`, which might be because something went wrong. This is for a js object, so it isn't controlled by our debug proxy. If it isn't an error then we should update the test. That could be tested by checking some contents of the array.

Update: `CheckVSCodeTestFunction2` passes though.

cc @ilonatommy 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/95950. After updating chrome to new version, the messages about Arrays we are getting from chrome are different.
This is fixing error:
```
 Expected: {
   "type": "object",
   "className": "Array",
   "description": "Array(10)"
 } 
 Actual: {
   "type": "object",
   "className": "Array",
   "description": "Array",
   "objectId": "5084384295708308525.1.9"
 }
```

### CODE REVIEW

File: src/mono/wasm/debugger/DebuggerTestSuite/CallFunctionOnTests.cs [hunk 1]
```diff
@@ -951,9 +951,10 @@ async Task CheckCFOResult(Result result)
                 if (res_array_len < 0)
                     await CheckValue(result.Value["result"], TObject("Object"), $"cfo-res");
                 else
-                    await CheckValue(result.Value["result"], TArray("Array", $"Array({res_array_len})"), $"cfo-res");
+                    // using TArrayJS instead of TArray because "result" value is purely JS and 
+                    // might differ from debuggerProxy's messages on each devtool protocol change
+                    await CheckValue(result.Value["result"], TArrayJS("Array", $"Array({res_array_len})"), $"cfo-res");
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/CallFunctionOnTests.cs:956]: This is the only special test where we have this case, so directly use `JObject.FromObject(new { type = "object", className, description })` here.

**Review by radical — APPROVED** [review]
