### PR TITLE
When cloning method descs be careful with fields that have different offsets between the source and destination. 

### LINKED ISSUE #115667: [runtime-async] Calling interface Task<T> methods on structs crash the runtime when invoked in an ALC
The following program compiled as a Roslyn async state machine (i.e. not new-style) crashes the runtime when `FEATURE_RUNTIME_ASYNC` is enabled.

```csharp
// Generated by Fuzzlyn v3.1 on 2025-05-16 13:28:12
// Run on X64 Windows
// Seed: 6767841392543623596-async,vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86pclmulqdqv256,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 333.1 KiB to 1.3 KiB in 00:23:17
// Exits with error:
// Fatal error.
// 0xC0000005
//
using System.Threading.Tasks;

public interface I0
{
    Task<bool> M8();
}

public struct S1 : I0
{
    public async Task<bool> M8()
    {
        return false;
    }
}

public class Program
{
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[] { System.Activator.CreateInstance(runtimeTy) });
    }

    public static void MainInner(IRuntime rt)
    {
        bool vr1 = new S1().M8().GetAwaiter().GetResult();
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC() : base(true)
    {
    }
}
```

It seems when calling the prestub for `S1.M8` we somehow end up with the code address 0x1. The JIT itself seems to succeed, but we fail here which ends up returning `pOtherCode == 0x1`:

https://github.com/dotnet/runtime/blob/98bb641b628447e2dc1b64faaa36172ce8c4316b/src/coreclr/vm/prestub.cpp#L989-L1004

cc @VSadov

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #115667

When cloning methoddescs into destination that has a different layout, memcopy only the base portion, then copy remaining fields individually.

If we memcopy the whole thing, non-base fields would be copied to wrong locations. Even if we subsequently copy the non-base fields individually, the initial memcopy may corrupt destination fields that are not present in the source.

The issue appears to be not new, but somehow did not cause problems until now.

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @jakobbotsch - the fix for the async issue.

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 1]
```diff
@@ -7298,16 +7298,14 @@ VOID MethodTableBuilder::AllocAndInitMethodDescChunk(COUNT_T startIndex, COUNT_T
...
-            memcpy(pUnboxedMD, pMD, pMD->SizeOf());
-
-            // Reset the chunk index
-            pUnboxedMD->SetChunkIndex(pChunk);
-
-            if (bmtGenerics->GetNumGenericArgs() == 0) {
-                pUnboxedMD->SetHasNonVtableSlot();
+            if (bmtGenerics->GetNumGenericArgs() == 0)
+            {
+                memcpy(pUnboxedMD, pMD, pMD->GetBaseSize());
```
Comment (VSadov) [inline src/coreclr/vm/methodtablebuilder.cpp:7303]: This is basically the fix. `memcpy(pUnboxedMD, pMD, pMD->SizeOf());` vs. `memcpy(pUnboxedMD, pMD, pMD->GetBaseSize());`. 

`memcpy(pUnboxedMD, pMD, pMD->SizeOf());` may copy a few fields to wrong locations. Then it is not enough to write correct values to the new locations, we would also need to clean up wrong locations.

It is better for the initial memcopy to do only the base portion, which is the same between different layouts. The rest stays zero-inited.

Comment (VSadov) [reply src/coreclr/vm/methodtablebuilder.cpp:7303]: The problem that we see now is that we are corrupting a slot that is later set via interlocked exchange, which expects 0 comparand. 
Since we have junk in the slot, the exchange does not happen and the junk stays in the slot and causes crashes.

**Comment by jakobbotsch** [comment]
I suspect the new test will need to be disabled in various places that do not support collectible ALCs or loading files from disk.

File: src/tests/Regressions/coreclr/GitHub_115667/test115667.cs [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+{
+#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
+    public async Task<bool> M8()
+#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
+    {
+        return false;
+    }
+}
+
+public class Program
```
Comment (jakobbotsch) [inline src/tests/Regressions/coreclr/GitHub_115667/test115667.cs:22]:
```suggestion
public class Runtime_115667
```

File: src/tests/Regressions/coreclr/GitHub_115667/test115667.cs [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+    [Fact]
+    public static int TestEntryPoint()
+    {
+        System.Runtime.Loader.AssemblyLoadContext alc = new CollectibleALC();
+        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
+        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
+        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
+        mi.Invoke(null, new object[] { System.Activator.CreateInstance(runtimeTy) });
+
+        return 100;
```
Comment (jakobbotsch) [inline src/tests/Regressions/coreclr/GitHub_115667/test115667.cs:33]: This is unnecessary (and will fail a build analyzer we have in some builds). The test can return void instead.

**Review by jakobbotsch — APPROVED** [review]
LGTM, but I am not familiar with this part of the code so you probably want to wait for David's review too.

**Review by davidwrighton — APPROVED** [review]

**Comment by VSadov** [comment]
Thanks!
