### PR TITLE
Propagate c++ unhandled exception to previous handler

### LINKED ISSUE #70136: Loading a .NET host in a C++ program seems to change exception handling behavior
### Description

I'm trying to write a C++ program which loads the .NET host using `hostfxr.dll`.
However I noticed that after loading a .NET host, unhandled C++ exceptions no longer triggers `std::terminate`.

### Reproduction Steps

1. set a terminate handler with `std::set_terminate()`. 
2. load the .NET host (I'm using `hostfxr_initialize_for_runtime_config` of `hostfxr.dll`)
3. throw an `std::runtime_error` without any `try` / `catch`, observe that terminate handler will NOT be invoked

If step 2 is skipped (i.e. do not load the .NET host), then terminate handler will be invoked as usual

### Expected behavior

`std::terminate` should be invoked for unhandled exceptions

### Actual behavior

`std::terminate` is not invoked for unhandled exceptions.

However, manually calling `std::terminate()` can still trigger the terminate handler.
Violating a `noexcept` specification, destroying a non-joined `std::thread` etc. all still correctly invoke `std::terminate`, even after .NET host is loaded.
This issue only affects unhandled exceptions.

### Regression?

_No response_

### Known Workarounds

Catch all C++ exceptions manually with `try` / `catch`, instead relying on the terminate handler

### Configuration

.NET version: 6.0.5
OS: Windows 10
Architecture: x86, compiled with MSVC v143

### Other information

_No response_

### PR DESCRIPTION
**Pull request by janvorli**
Currently runtime doesn't propagate c++ unhandled exceptions to a handler
registered by the `std::set_terminate`. That is problematic for custom
hosts that want e.g. to log such exceptions.

This change adds chaining unhandled C++ exception to the previously
registered handler.

Close #70136

### CODE REVIEW

File: src/coreclr/vm/excep.cpp [hunk 1]
```diff
@@ -4968,47 +4968,19 @@ LONG InternalUnhandledExceptionFilter(
...
-    // For CoreCLR, this will not be an issue. See
-    // http://sharepoint/sites/clros/Shared%20Documents/Design%20Documents/EH/Chaining%20in%20%20UEF%20-%20One%20Pager.docx
-    // for details.
-    //
-    // Note: Also see the conditional UEF registration with the OS in EEStartupHelper.
-
-    // We would be here only on CoreCLR for WLC since we dont register
-    // the UEF with the OS for SL.
+    // http://uninformed.org/index.cgi?v=4&a=5&p=1 for details.
+    // Thus we are allowing only C++ exceptions to be chained to the previous handler.
```
Comment (jkotas) [inline src/coreclr/vm/excep.cpp:4972]: How does only allowing C++ exceptions avoids the security risks?

The security risk has to do with out of order unregistration. CoreCLR does not unload and unregister so it is not introducing this risk. If there is some other component in the process that does out of order unregistration, we cannot really protect against that.

Comment (janvorli) [reply src/coreclr/vm/excep.cpp:4972]: I guess I've misunderstood the point of the article. It keeps talking about NULL reference exceptions as being the source of the exploitation. My understanding was that an attacker would just cause some reference to be NULL to trigger the behavior, which could be achieved without executing any external code. To throw a C++ exception, it would have to be already running its own code in the process, which sounded like too late for any mitigations.

Comment (janvorli) [reply src/coreclr/vm/excep.cpp]: I've pushed a change that removes the comment and check and forwards all exceptions to the previous handler.

Comment (jkotas) [reply src/coreclr/vm/excep.cpp]: I would also delete the unregistration during shutdown at least.

Comment (janvorli) [reply src/coreclr/vm/excep.cpp]: Our messages have crossed, makes sense, I've pushed another commit with these changes.

File: src/coreclr/vm/excep.cpp [hunk 2]
```diff
@@ -4474,46 +4466,18 @@ BOOL InstallUnhandledExceptionFilter() {
     STATIC_CONTRACT_FORBID_FAULT;
 
 #ifndef TARGET_UNIX
-    // We will be here only for CoreCLR on WLC since we dont
-    // register UEF for SL.
-    if (g_pOriginalUnhandledExceptionFilter == FILTER_NOT_INSTALLED) {
+    #pragma prefast(push)
+    #pragma prefast(suppress:28725, "Calling to SetUnhandledExceptionFilter is intentional in this case.")
+    g_pOriginalUnhandledExceptionFilter = SetUnhandledExceptionFilter(COMUnhandledExceptionFilter);
+    #pragma prefast(pop)
```
Comment (jkotas) [inline src/coreclr/vm/excep.cpp:4472]:
```suggestion
    g_pOriginalUnhandledExceptionFilter = SetUnhandledExceptionFilter(COMUnhandledExceptionFilter);
```

**Review by jkotas — APPROVED** [review]
