### PR TITLE
x86/funclets: Handle longjmp

### LINKED ISSUE #115701: Missing GCX_PREEMP_NO_DTOR in PropagateLongJmpThroughNativeFrames
When exploring how to get the `longjmp` working on x86/funclets I noticed that the code path going through `PropagateLongJmpThroughNativeFrames` never switches back from cooperative mode to preemptive one. Presumably it should call `GCX_PREEMP_NO_DTOR();` like `PropagateForeignExceptionThroughNativeFrames` does.

### PR DESCRIPTION
**Pull request by filipnavara**
Implement basic support for unwinding longjmp across managed frames to match x64 and old EH behavior.

Like other Windows platforms we get our exception handler called with `STATUS_LONGJMP` exception. However, unlike 64-bit platforms we don't get the original `jmp_buf` and return value in the `ExceptionInformation` parameters. In order to handle the longjmp we need to return back from the `ProcessCLRException` call which is currently not done anywhere else.

The solution is a bit of an abuse. We create our own `setjmp` trampoline from `ProcessCLRException` and use that to return from last `CallCatchFunclet` at the end of `DispatchEx`. In order not to interfere with C++ unwinding we need to extract the `setjmp` into its own function with no C++ destructors on the frame.

Also fix #115701 by calling `GCX_PREEMP_NO_DTOR` in `PropagateLongJmpThroughNativeFrames` while I am at it.

Contributes to #113985

### CODE REVIEW

**Comment by filipnavara** [comment]
The alternative solution would be to just detect `STATUS_LONGJMP` and fail fast on the spot with a meaningful message but since I already got far enough with a viable workaround I thought we could just do that.

File: src/coreclr/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -521,6 +521,39 @@ static void PopExplicitFrames(Thread *pThread, void *targetSp, void *targetCalle
...
+    // Emulate the parameters that are passed on 64-bit systems and expected by
+    // DispatchManagedException.
+    EXCEPTION_RECORD newExceptionRecord = *pExceptionRecord;
+    newExceptionRecord.NumberParameters = 2;
+    newExceptionRecord.ExceptionInformation[0] = (DWORD_PTR)&jumpBuffer;
+    newExceptionRecord.ExceptionInformation[1] = 1;
+
+    OBJECTREF oref = ExInfo::CreateThrowable(&newExceptionRecord, FALSE);
+    DispatchManagedException(oref, pContextRecord, &newExceptionRecord);
+}
```
Comment (filipnavara) [inline src/coreclr/vm/exceptionhandling.cpp:554]:
```suggestion
    UNREACHABLE();
}
```

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

File: src/coreclr/vm/exceptionhandling.cpp [hunk 2]
```diff
@@ -613,14 +646,22 @@ ProcessCLRException(IN     PEXCEPTION_RECORD   pExceptionRecord,
...
     {
         ContinueExceptionInterceptionUnwind();
         UNREACHABLE();
     }
+#if defined(HOST_WINDOWS) && defined(HOST_X86)
+    else if (pExceptionRecord->ExceptionCode == STATUS_LONGJUMP)
+    {
+        DispatchLongJmp(pExceptionRecord, pEstablisherFrame, pContextRecord);
+        GCX_COOP_NO_DTOR_END();
+        return ExceptionContinueSearch;
```
Comment (jkotas) [inline src/coreclr/vm/exceptionhandling.cpp:662]:
```suggestion
        UNREACHABLE();
```
