### PR TITLE
 Ensure to use float reserved register for TYP_SIMD12

### LINKED ISSUE #108609: osx/arm64: Assertion failed 'genExactlyOneBit(availableSet)'  during 'Generate code'
Repros on osx/arm64:

```csharp
// Found by Antigen
// Reduced from 50.05 KB to 4.88 KB.


using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;
using System.Numerics;
public class TestClass
{
    public struct S1
    {
        public Vector3 v3_0;
        public short short_1;
    }
    static bool s_bool_4 = true;
    static char s_char_6 = 'I';
    static int s_int_10 = 5;
    static sbyte s_sbyte_12 = -5;
    static ulong s_ulong_17 = 0;
    static Vector64<int> s_v64_int_23 = Vector64<int>.Zero;
    static Vector64<double> s_v64_double_28 = Vector64.Create(-4.956521739130435);
    static Vector128<sbyte> s_v128_sbyte_30 = Vector128<sbyte>.Zero;
    static Vector128<short> s_v128_short_31 = Vector128.Create(0, 2, -5, 0, 1, 0, 2, 2);
    static Vector128<ulong> s_v128_ulong_36 = Vector128<ulong>.Zero;
    static Vector128<double> s_v128_double_38 = Vector128.Create(1.0769230769230769, 72.01666666666667);
    static Vector<ulong> s_v_ulong_46 = Vector.Create((ulong)1);
    static Vector<float> s_v_float_47 = Vector<float>.Zero;
    static S1 s_s1_52 = new S1();
    char char_56 = 'K';
    int int_60 = -1;
    Vector64<int> v64_int_73 = Vector64.Create(2147483646, -1);
    Vector64<double> v64_double_78 = Vector64.Create(-0.9420289855072463);
    Vector128<sbyte> v128_sbyte_80 = Vector128.Create(-2, -2, -1, 0, 5, -1, -1, -1, 1, 2, -1, 0, -1, 72, -5, 0);
    Vector128<short> v128_short_81 = Vector128.CreateScalar((short)-1);
    Vector128<ulong> v128_ulong_86 = Vector128<ulong>.AllBitsSet;
    Vector<ulong> v_ulong_96 = Vector.Create((ulong)1);
    Vector<float> v_float_97 = Vector.Create(2f);
    Vector3 v3_100 = Vector3.Create(0.09090909f, 2.4f, -0.94f);
    S1 s1_102 = new S1();
    static int s_loopInvariant = 4;
    private static List<string> toPrint = new List<string>();
    [MethodImpl(MethodImplOptions.NoInlining)]
    public decimal LeafMethod3()
    {
        unchecked
        {
            return 15+4;
        }
    }
    public Vector<float> Method2(decimal p_decimal_130, decimal p_decimal_131, sbyte p_sbyte_132, out Vector128<ulong> p_v128_ulong_133, S1 p_s1_134)
    {
        unchecked
        {
            p_v128_ulong_133 = s_v128_ulong_36;
            return s_v_float_47 = Vector<float>.Zero| s_v_float_47+ v_float_97^ s_v_float_47;
        }
    }
    public Vector128<sbyte> Method3(sbyte p_sbyte_152, Vector<ulong> p_v_ulong_153, S1 p_s1_154, uint p_uint_155, S1 p_s1_156, decimal p_decimal_157, Vector64<double> p_v64_double_158)
    {
        unchecked
        {
            return s_v128_sbyte_30 = s_v128_sbyte_30;
        }
    }
    public void Method0()
    {
        unchecked
        {
            S1 s1_218 = new S1();
            do
            {
                if (s_bool_4)
                {
                }
                else
                {
                    switch (s_char_6 = char_56)
                    {
                        case '6':
                        {
                            int __loopvar0 = s_loopInvariant;
                            for (int __loopSecondaryVar0_0 = 15-4; s_int_10 < Vector64.GetElement(s_v64_int_23 - Vector64<int>.Zero * (15+4)| (s_v64_int_23 += AdvSimd.Max(Vector64<int>.Zero, v64_int_73)), 15&4); __loopvar0--, __loopSecondaryVar0_0++, s_s1_52.short_1 = Vector128.Sum(AdvSimd.ShiftLogicalRoundedSaturate(Vector128<short>.AllBitsSet, v128_short_81) & Vector128.AsInt16(s_v128_double_38)- (15|4)* (v128_short_81 *= s_v128_short_31)))
                            {
                                v3_100 *= s1_218.v3_0 - (s1_218.v3_0 = s1_218.v3_0 = s1_218.v3_0 *= s1_218.v3_0)* Vector3.RadiansToDegrees(Vector3.Zero + s_s1_52.v3_0+ v3_100 * v3_100)- Vector3.Sin(s1_218.v3_0 *= v3_100* (s1_218.v3_0 *= s1_218.v3_0)- v3_100 * s_s1_52.v3_0);
                            }
                            break;
                        }
                        default:
                        {
                            break;
                        }
                    }
                }
            }
            while ((s_ulong_17 = 15*4)>= (ulong)(int_60 = int_60% 15|4));
            v_float_97 = Method2(15%4, LeafMethod3(), s_sbyte_12, out v128_ulong_86, s1_218);
            v128_sbyte_80 = Method3(15%4, s_v_ulong_46 *= s_v_ulong_46 += v_ulong_96 = s_v_ulong_46 ^ v_ulong_96* (15-4), s1_218, 15&4, s1_102, LeafMethod3(), v64_double_78 * s_v64_double_28- (s_v64_double_28 = v64_double_78)| Vector64.GreaterThan(v64_double_78, v64_double_78) | (s_v64_double_28 = Vector64<double>.Zero + v64_double_78)| (s_v64_double_28 = v64_double_78)| Vector64.GreaterThan(v64_double_78, v64_double_78) | (s_v64_double_28 = Vector64<double>.Zero + v64_double_78)| s_v64_double_28);
            return;
        }
    }
    public static void Main(string[] args)
    {
    }
    public static int Antigen()
    {
        new TestClass().Method0();
        return string.Join(Environment.NewLine, toPrint).GetHashCode();
    }
}
/*
Environment:

set DOTNET_JitDoReversePostOrderLayout=1
set DOTNET_JitStressEvexEncoding=1
set DOTNET_ReadyToRun=1
set DOTNET_JitEdgeProfiling=0
set DOTNET_TailcallStress=1
set DOTNET_JitObjectStackAllocation=1
set DOTNET_TieredCompilation=0
set DOTNET_MaxVectorTBitWidth=128
set DOTNET_PreferredVectorBitWidth=0
set DOTNET_EnableHWIntrinsic=0
set DOTNET_JitStressRegs=2
set DOTNET_JitThrowOnAssertionFailure=1
set DOTNET_LegacyExceptionHandling=1

Debug: -1287671553

Release: 0
JIT assert failed:
Assertion failed 'genExactlyOneBit(availableSet)' in 'TestClass:Method0():this' during 'Generate code' (IL size 782; hash 0x46e9aa75; FullOpts)

    File: /Users/runner/work/1/s/src/coreclr/jit/codegencommon.cpp Line: 133


*/

```

### PR DESCRIPTION
**Pull request by kunalspathak**
For storing SIMD12, we sometimes use int register and other times float register. Because of this, the reserved register pool might have more than one register leading to assert. The fix is to make the reserved register requirement consistent for arm64, loongarch and risc.

Fixes: https://github.com/dotnet/runtime/issues/108609

### CODE REVIEW

**Comment by kunalspathak** [comment]
@shushanhf  @dotnet/samsung @dotnet/jit-contrib

File: src/coreclr/jit/lsrariscv64.cpp [hunk 1]
```diff
@@ -812,8 +812,8 @@ int LinearScan::BuildIndir(GenTreeIndir* indirTree)
         assert(!addr->isContained());
 
         // Vector3 is read/written as two reads/writes: 8 byte and 4 byte.
-        // To assemble the vector properly we would need an additional int register
-        buildInternalIntRegisterDefForNode(indirTree);
+        // To assemble the vector properly we would need an additional float register
+        buildInternalFloatRegisterDefForNode(indirTree);
```
Comment (tomeksowi) [inline src/coreclr/jit/lsrariscv64.cpp:816]: RISC-V doesn't define FEATURE_SIMD yet but I think it can stay.

**Review by tomeksowi — APPROVED** [review]

**Comment by risc-vv** [comment]
<details><summary>147f189f is being scheduled for building and testing</summary>

GIT: `147f189f58bc72581420232a98aebe0b2e218aba`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>147f189f is being scheduled for building and testing</summary>

GIT: `147f189f58bc72581420232a98aebe0b2e218aba`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by sirntar** [comment]
I've scheduled tests to make sure it doesn't affect rv64, but it is as @tomeksowi said: we don't support SIMD yet. Although there are plans to support it in the following year.

**Review by sirntar — APPROVED** [review]

**Comment by kunalspathak** [comment]
> I guess failures are related? I am puzzled why it needs a float rather than int temp for Simd12 store

Yes, it is related. I didn't any spec that says which register to pick, so to make it consistent with x86, i picked floating register and also given the fact that GPRs are more common than floating registers. I will investigate the test failure.

**Comment by kunalspathak** [comment]
> > I guess failures are related? I am puzzled why it needs a float rather than int temp for Simd12 store
> 
> Yes, it is related. I didn't any spec that says which register to pick, so to make it consistent with x86, i picked floating register and also given the fact that GPRs are more common than floating registers. I will investigate the test failure.

Turns out that we end up generating wrong instruction if we use floating point as scratch register:

image

https://github.com/dotnet/runtime/blob/87273d64859e8bf5856d176915624e6f92ed3baf/src/coreclr/jit/emitarm64.cpp#L5216-L5224

I converted all the places to instead create int internal register. To fix the original issue, since we can have multiple internal registers specially for TYP_SIMD12 (one for `PutArgStk` and other for storeloc, for example) and we might assign different registers to them, the fix was to `Extract` instead of using `GetSingle()`.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
@EgorBo @dotnet/jit-contrib PTAL

File: src/coreclr/jit/emitarm64.cpp [hunk 2]
```diff
@@ -17424,7 +17424,7 @@ void emitter::emitStoreSimd12ToLclOffset(unsigned varNum, unsigned offset, regNu
     else
     {
         // Extract upper 4-bytes from data
-        regNumber tmpReg = codeGen->internalRegisters.GetSingle(tmpRegProvider);
+        regNumber tmpReg = codeGen->internalRegisters.Extract(tmpRegProvider);
```
Comment (EgorBo) [inline src/coreclr/jit/emitarm64.cpp:17427]: Interesting, this function checks whether we don't have any spare temps at all - it does the store using two shuffles without temps, otherwise, do a simpler routine with temp, but looks like in some cases we over-allocate temps for it? Given that diffs are fine I guess it's ok

**Review by EgorBo — APPROVED** [review]
Stores for SIMD12 are a popular trouble (we had like 3 or 4 bugs with them already) 😢

File: src/coreclr/jit/emitarm64.cpp (hunk 2 above)
Comment (kunalspathak) [reply src/coreclr/jit/emitarm64.cpp:17427]: right, we may have more than 1 temps and `Extract` make sure to get the first available and remove it from the pool.
