### PR TITLE
[browser] firefox testing

### LINKED ISSUE #100955: [browser][hybrid][firefox] RangeError: invalid value "Cyrl" for option region
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100697-merge-b6a36d4cb999420e8f/WasmTestOnFirefox-System.Globalization.Hybrid.WASM.Tests/1/console.2422b918.log?helixlogtype=result)

```
[20:29:32] info: [FAIL] System.Globalization.Tests.DateTimeFormatInfoAbbreviatedMonthGenitiveNames.TestAbbreviatedGenitiveNamesWithAllCultures
[20:29:32] info: System.Exception : RangeError: invalid value "Cyrl" for option region
[20:29:32] info: ol<@mono_background_exec (http://127.0.0.1:35869/_framework/dotnet.runtime.js:3:185682
```

There are many more in the log:
```
 [FAIL] System.Globalization.Tests.CultureInfoConstructor.Ctor_String(name: "tzm-Latn", expectedNames: ["tzm-Latn"])
[20:29:35] info: System.Exception : RangeError: invalid value "Latn" for option region
```
```
[FAIL] System.Globalization.Tests.DateTimeFormatInfoNativeCalendarName.NativeCalendarName_Get_ReturnsExpected_HybridGlobalization(format: DateTimeFormatInfo { AbbreviatedDayNames = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", ···], AbbreviatedMonthGenitiveNames = ["محرم", "صفر", "ربيع الأول", "ربيع الآخر", "جمادى الأولى", ···], AbbreviatedMonthNames = ["محرم", "صفر", "ربيع الأول", "ربيع الآخر", "جمادى الأولى", ···], AMDesignator = "ص", Calendar = UmAlQuraCalendar { AlgorithmType = LunarCalendar, Eras = [···], IsReadOnly = False, MaxSupportedDateTime = 2077-11-16T23:59:59.9999999, MinSupportedDateTime = 1900-04-30T00:00:00.0000000, ··· }, ··· }, expected: "islamic-umalqura")
[20:29:38] info: Assert.Equal() Failure: Strings differ
[20:29:38] info:            ↓ (pos 0)
[20:29:38] info: Expected: "islamic-umalqura"
[20:29:38] info: Actual:   "UMALQURA"
```
```
[FAIL] System.Globalization.Tests.DateTimeFormatInfoNativeCalendarName.NativeCalendarName_Get_ReturnsExpected_HybridGlobalization(format: DateTimeFormatInfo { AbbreviatedDayNames = ["እሑድ", "ሰኞ", "ማክሰ", "ረቡዕ", "ሐሙስ", ···], AbbreviatedMonthGenitiveNames = ["ጃንዩ", "ፌብሩ", "ማርች", "ኤፕሪ", "ሜይ", ···], AbbreviatedMonthNames = ["ጃንዩ", "ፌብሩ", "ማርች", "ኤፕሪ", "ሜይ", ···], AMDesignator = "ጥዋት", Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [···], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ··· }, ··· }, expected: "gregory")
[20:29:38] info: Assert.Equal() Failure: Strings differ
[20:29:38] info:            ↓ (pos 0)
[20:29:38] info: Expected: "gregory"
[20:29:38] info: Actual:   "GREGORIAN"
```
```
[FAIL] System.Globalization.Tests.DateTimeFormatInfoFirstDayOfWeek.FirstDayOfWeekHybridGlobalization(culture: "en-AU", expected: Monday)
[20:29:39] info: Failed for culture: en-AU. Expected: Monday, Actual: Sunday
```
```
[FAIL] System.Globalization.Tests.CompareInfoTests.GetCompareInfo(name: "zh-Hans")
[20:29:43] info: System.Exception : RangeError: invalid value "Hans" for option region
```
```
[FAIL] System.Globalization.Tests.CompareInfoTests.GetCompareInfo(name: "zh-Hant")
[20:29:43] info: System.Exception : RangeError: invalid value "Hant" for option region
```

[Other log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100697-merge-b6a36d4cb999420e8f/WasmTestOnFirefox-System.Globalization.Tests/1/console.97cd7cd0.log?helixlogtype=result)

```
[FAIL] System.Globalization.Tests.RegionInfoPropertyTests.Ctor_InvalidName_ThrowsArgumentException(name: "no-such-culture")
[20:30:05] info: Assert.Throws() Failure: Exception type was not an exact match
[20:30:05] info: Expected: typeof(System.ArgumentException)
[20:30:05] info: Actual:   typeof(System.Exception)
[20:30:05] info: ---- System.Exception : RangeError: invalid value "culture" for option region
```
```
 [FAIL] System.Globalization.Tests.CultureInfoConstructor.TestCreationWithMangledSortName(cultureName: "de-DE-u-co-phonebk-t-xx-u-yy", expectedCultureName: "de-DE-t-xx-u-yy", expectedSortName: "de-DE-t-xx-u-yy_phoneboo")
[20:30:29] info: System.Exception : RangeError: invalid value "de-DE-t-xx-u" for option language
```

### PR DESCRIPTION
**Pull request by pavelsavara**
- enables testing on Firefox - to understand when our MT problems are actually chrome problems 
- Solves differences in Firefox hybrid globalization
    - Fixes https://github.com/dotnet/runtime/issues/100955
- Disables testing with HTTPS with Firefox - because trusting self signed certificate is too difficult
    - created https://github.com/dotnet/runtime/issues/101115 for disabled scenarios
- installs Firefox also on Windows

### CODE REVIEW

**Comment by pavelsavara** [comment]
`The geckodriver file does not exist in the current directory or in a directory on the PATH environment variable.`
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100697-merge-b1eab1afd52e4d53b2/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.30f60b8f.log?helixlogtype=result)

Make `DownloadAndInstallFirefox` work

https://github.com/dotnet/runtime/blob/e1f53785bfc203cd70aac486f49e269e9033f639/eng/testing/wasm-provisioning.targets#L181

**Comment by pavelsavara** [comment]
`src\libraries\sendtohelix-browser.targets` `$HELIX_CORRELATION_PAYLOAD`

File: src/mono/browser/test-main.js [hunk 1]
```diff
@@ -24,6 +24,7 @@ export const ENVIRONMENT_IS_SIDECAR = ENVIRONMENT_IS_WEB_WORKER && typeof dotnet
 export const ENVIRONMENT_IS_WORKER = ENVIRONMENT_IS_WEB_WORKER && !ENVIRONMENT_IS_SIDECAR; // we redefine what ENVIRONMENT_IS_WORKER, we replace it in emscripten internals, so that sidecar works
 export const ENVIRONMENT_IS_WEB = typeof window == "object" || (ENVIRONMENT_IS_WEB_WORKER && !ENVIRONMENT_IS_NODE);
 export const ENVIRONMENT_IS_SHELL = !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_NODE;
+export const isFirefox = ENVIRONMENT_IS_WEB && navigator.userAgent.includes("Firefox");
```
Comment (ilonatommy) [inline src/mono/browser/test-main.js:27]: `// keep in sync with src\mono\browser\runtime\loader\globals.ts and src\mono\browser\runtime\globals.ts`
do we treat it as binding for variables not beginning with `ENVIRONMENT`?

Comment (pavelsavara) [reply src/mono/browser/test-main.js:27]: those `ENVIRONMENT`* things are kin to emscripten for the same thing.

File: src/libraries/System.Runtime/tests/System.Globalization.Calendars.Tests/Hybrid/System.Globalization.Calendars.Hybrid.WASM.Tests.csproj [hunk 2]
```diff
@@ -4,6 +4,8 @@
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
     <TestRuntime>true</TestRuntime>
     <HybridGlobalization>true</HybridGlobalization>
+    <!-- Active issue https://github.com/dotnet/runtime/issues/100955 remove the next line -->
```
Comment (ilonatommy) [inline src/libraries/System.Runtime/tests/System.Globalization.Calendars.Tests/Hybrid/System.Globalization.Calendars.Hybrid.WASM.Tests.csproj:7]: When you finish, could you enable? They pass already.

File: src/libraries/System.Runtime/tests/System.Globalization.Tests/Hybrid/System.Globalization.Hybrid.WASM.Tests.csproj [hunk 3]
```diff
@@ -5,6 +5,8 @@
     <TestRuntime>true</TestRuntime>
     <IncludeRemoteExecutor>true</IncludeRemoteExecutor>
     <HybridGlobalization>true</HybridGlobalization>
+    <!-- Active issue https://github.com/dotnet/runtime/issues/100955 remove the next line -->
```
Comment (ilonatommy) [inline src/libraries/System.Runtime/tests/System.Globalization.Tests/Hybrid/System.Globalization.Hybrid.WASM.Tests.csproj:8]: Same as Calendars, they pass.

File: src/libraries/sendtohelix-browser.targets [hunk 4]
```diff
@@ -32,7 +32,8 @@
 
   <PropertyGroup>
     <_ShippingPackagesPath>$([MSBuild]::NormalizeDirectory($(ArtifactsDir), 'packages', $(Configuration), 'Shipping'))</_ShippingPackagesPath>
-    <WorkItemPrefix Condition="'$(WorkItemPrefix)' == ''">$(Scenario)-</WorkItemPrefix>
+    <WorkItemPrefix Condition="'$(WorkItemPrefix)' == '' and '$(WasmEnableThreads)' != 'true'">$(Scenario)-ST-</WorkItemPrefix>
```
Comment (maraf) [inline src/libraries/sendtohelix-browser.targets:35]: You already set in `src/libraries/sendtohelix-wasm.targets`

File: src/libraries/sendtohelix-wasm.targets [hunk 5]
```diff
@@ -31,6 +31,8 @@
       <WorkItemPrefix Condition="'$(TestUsingWorkloads)' == 'true'">Workloads-</WorkItemPrefix>
       <WorkItemPrefix Condition="'$(TestUsingWorkloads)' != 'true'">NoWorkload-</WorkItemPrefix>
       <WorkItemPrefix Condition="'$(TestUsingWebcil)' == 'false'">$(WorkItemPrefix)NoWebcil-</WorkItemPrefix>
+      <WorkItemPrefix Condition="'$(WasmEnableThreads)' != 'true'">$(WorkItemPrefix)ST-</WorkItemPrefix>
+      <WorkItemPrefix Condition="'$(WasmEnableThreads)' == 'true'">$(WorkItemPrefix)MT-</WorkItemPrefix>
```
Comment (maraf) [inline src/libraries/sendtohelix-wasm.targets:35]:
```suggestion
      <WorkItemPrefix Condition="'$(WasmEnableThreads)' != 'true'">$(WorkItemPrefix)-ST-</WorkItemPrefix>
      <WorkItemPrefix Condition="'$(WasmEnableThreads)' == 'true'">$(WorkItemPrefix)-MT-</WorkItemPrefix>
```

**Review by maraf — DISMISSED** [review]
Looks good to me 👍

File: src/libraries/sendtohelix-browser.targets (hunk 4 above)
Comment (pavelsavara) [reply src/libraries/sendtohelix-browser.targets:35]: I think that's only for `BuildWasmApps` and it happens later, not earlier ?

File: src/libraries/sendtohelix-wasm.targets (hunk 5 above)
Comment (pavelsavara) [reply src/libraries/sendtohelix-wasm.targets:35]: nope, at that point `WorkItemPrefix` is already set with the dash at the end

File: src/libraries/sendtohelix-browser.targets (hunk 4 above)
Comment (maraf) [reply src/libraries/sendtohelix-browser.targets:35]: It's included from sendtohelixhelp, so later, but it shouldn't be specific for WBT.

Comment (maraf) [reply src/libraries/sendtohelix-browser.targets:35]: The file is imported above this property group. Yeah, the place where you set it in there has a condition for `BuildWasmApps`, but I don't see a reason not to refactor it to a single place

**Comment by pavelsavara** [comment]
somehow Firefox on windows [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100697-merge-9124aa1e66334a6e8a/WasmTestOnFirefox-ST-Common.Tests/1/console.55a34be8.log?helixlogtype=result)

```
set RuntimeIdentifier=browser-wasm
The system cannot find the drive specified.
--browser=Firefox
```

**Comment by pavelsavara** [comment]
Filled https://github.com/dotnet/runtime/issues/101497

File: src/libraries/sendtohelix-browser.targets [hunk 6]
```diff
@@ -182,7 +175,13 @@
   <Import Project="$(RepositoryEngineeringDir)testing\wasm-provisioning.targets" />
 
   <Target Name="PrepareHelixCorrelationPayload_Wasm">
-    <Error Condition="'$(Scenario)' == '' or '$(Scenario)' == 'normal'" Text="Only supported scenarios are WasmTestOnV8, WasmTestOnNodeJS, WasmTestOnChrome, WasmTestOnFirefox, WasmDebuggerTests and BuildWasmApps at the moment." />
+    <Error Condition="'$(Scenario)' != 'WasmTestOnV8' and
```
Comment (maraf) [inline src/libraries/sendtohelix-browser.targets:178]: Can we refactor to a more common place, so that local run will have the same validation?

File: src/mono/sample/Directory.Build.props [hunk 7]
```diff
@@ -6,13 +6,17 @@
...
+    <ExecXHarnessVar>$HARNESS_RUNNER</ExecXHarnessVar>
+    <XHarnessOutputVar>$XHARNESS_OUT</XHarnessOutputVar>
+    <XHarnessCommandVar>$XHARNESS_COMMAND</XHarnessCommandVar>
+    <WasmXHarnessArgsVar>$XHARNESS_ARGS</WasmXHarnessArgsVar>
   </PropertyGroup>
 
   <PropertyGroup Condition="'$(BrowserHost)' == 'windows'">
-    <ExecXHarnessCmd>%HARNESS_RUNNER%</ExecXHarnessCmd>
-    <XHarnessOutput>%XHARNESS_OUT%</XHarnessOutput>
+    <ExecXHarnessVar>%HARNESS_RUNNER%</ExecXHarnessVar>
```
Comment (maraf) [inline src/mono/sample/Directory.Build.props:16]: Why the rename? The value is not required to be a variable, isn't it?

File: src/libraries/sendtohelix-wasi.targets [hunk 8]
```diff
@@ -104,6 +104,10 @@
   <Import Project="$(RepositoryEngineeringDir)testing\wasi-provisioning.targets" />
 
   <Target Name="PrepareHelixCorrelationPayload_Wasi">
+    <Error Condition="'$(Scenario)' != 'WasmTestOnWasmtime' and
```
Comment (maraf) [inline src/libraries/sendtohelix-wasi.targets:107]: The same ask for browser

File: eng/testing/WasmRunnerTemplate.cmd [hunk 9]
```diff
@@ -56,11 +60,25 @@ if /I [%XHARNESS_COMMAND%] == [test] (
...
+        if [%BROWSER_PATH%] == [] if not [%HELIX_CORRELATION_PAYLOAD%] == [] (
+            set "BROWSER_PATH=--browser-path^=%HELIX_CORRELATION_PAYLOAD%\chrome-win\chrome.exe"
+        )
+        if [%JS_ENGINE_ARGS%] == [] (
+            set "JS_ENGINE_ARGS=--browser-arg^=--js-flags^=--stack-trace-limit^=1000"
+        )
+    ) else (
+        if /I [%SCENARIO%] == [WasmTestOnFirefox] (
+            if [%BROWSER_PATH%] == [] if not [%HELIX_CORRELATION_PAYLOAD%] == [] (
+                set "BROWSER_PATH=--browser-path^=%HELIX_CORRELATION_PAYLOAD%\firefox\firefox.exe"
```
Comment (maraf) [inline eng/testing/WasmRunnerTemplate.cmd:73]: nit: The chrome folder is `chrome-win`, can we have `firefox-win`? Or drop the suffix for both?

File: eng/pipelines/common/templates/wasm-library-aot-tests.yml [hunk 10]
```diff
@@ -1,7 +1,7 @@
 parameters:
   alwaysRun: false
   extraBuildArgs: ''
-  extraHelixArgs: ''
+  extraHelixArguments: ''
```
Comment (maraf) [inline eng/pipelines/common/templates/wasm-library-aot-tests.yml:4]: Why the rename? Are you planning to expand `extraBuildArgs` to `extraBuildArguments` as well?

File: src/mono/sample/Directory.Build.props (hunk 7 above)
Comment (pavelsavara) [reply src/mono/sample/Directory.Build.props:16]: this is just a way how to differentiate windows/linux way how variables are expanded when you are writing a script. It is NOT the actual value. That value will get expanded later on helix. 
That's why the rename, it was confusing me.
I will add comment to that.

File: eng/pipelines/common/templates/wasm-library-aot-tests.yml (hunk 10 above)
Comment (pavelsavara) [reply eng/pipelines/common/templates/wasm-library-aot-tests.yml:4]: unification, so that copy&paste works without thinking about the context. All places now have `extraHelixArguments` an `extraBuildArgs`

File: eng/testing/WasmRunnerTemplate.cmd (hunk 9 above)
Comment (pavelsavara) [reply eng/testing/WasmRunnerTemplate.cmd:73]: this is inside `chrome-win.zip` and FF doesn't have it. There is also `chrome-linux` I'm not going to fiddle with that, sorry.

File: src/libraries/sendtohelix-browser.targets (hunk 6 above)
Comment (pavelsavara) [reply src/libraries/sendtohelix-browser.targets:178]: I can't refactor that because locally empty scenario is valid choice and will get a default. I will add validation of wrong values, bu that would not be shared

File: eng/pipelines/common/templates/wasm-library-aot-tests.yml (hunk 10 above)
Comment (maraf) [reply eng/pipelines/common/templates/wasm-library-aot-tests.yml:4]: I just don't understand why have `args` for one and `arguments` for other 🤷‍♂️

File: eng/testing/WasmRunnerTemplate.cmd (hunk 9 above)
Comment (maraf) [reply eng/testing/WasmRunnerTemplate.cmd:73]: Ook

File: src/libraries/sendtohelix-browser.targets (hunk 6 above)
Comment (maraf) [reply src/libraries/sendtohelix-browser.targets:178]: We can have only the default set locally and later have the same validation

File: eng/pipelines/common/templates/wasm-library-aot-tests.yml (hunk 10 above)
Comment (pavelsavara) [reply eng/pipelines/common/templates/wasm-library-aot-tests.yml:4]: you are asking me to fix something which is far beyond scope of this PR

**Review by maraf — APPROVED** [review]
After offline discussion, all my suggestions are only about making things slightly more clean.
Postponing them at the moment to get this in
