### PR TITLE
Fix Type.ContainsGenericParameters for function pointers

### LINKED ISSUE #84916: ContainsGenericParameters not reported for function pointer types
I would expect below to write True/True, but it writes False/True.

```csharp
using System;
using System.Diagnostics;

Console.WriteLine(typeof(Gen<>).GetField("MyField1").FieldType.ContainsGenericParameters);
Console.WriteLine(typeof(Gen<>).GetField("MyField2").FieldType.ContainsGenericParameters);

unsafe class Gen<T>
{
    public static delegate*<T> MyField1;
    public static T[] MyField2;
}
```

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #84916

### CODE REVIEW

File: src/coreclr/vm/typedesc.cpp [hunk 1]
```diff
@@ -104,6 +104,31 @@ BOOL TypeDesc::IsSharedByGenericInstantiations()
     return FALSE;
 }
 
+BOOL TypeDesc::ContainsGenericVariables(BOOL methodOnly)
```
Comment (jkotas) [inline src/coreclr/vm/typedesc.cpp:107]: The implementation mirrors structure of IsSharedByGenericInstantiations

File: src/coreclr/vm/typedesc.cpp [hunk 2]
```diff
@@ -104,6 +104,31 @@ BOOL TypeDesc::IsSharedByGenericInstantiations()
...
+        if (!methodOnly)
+            return TRUE;
+
+        PTR_TypeVarTypeDesc pTyVar = dac_cast<PTR_TypeVarTypeDesc>(this);
+        return TypeFromToken(pTyVar->GetTypeOrMethodDef()) == mdtMethodDef;
+    }
+
+    if (HasTypeParam())
+    {
+        return GetRootTypeParam().ContainsGenericVariables(methodOnly);
```
Comment (steveharter) [inline src/coreclr/vm/typedesc.cpp:120]: The similar code that was in `TypeHandle::ContainsGenericVariables` used `GetTypeParam()` instead of `GetRootTypeParam()` - is this change necessary?

File: src/libraries/Common/tests/System/FunctionPointerTests.cs [hunk 3]
```diff
@@ -156,6 +156,11 @@ public static unsafe void FunctionPointerReturn()
             Assert.True(fcnPtr2.IsFunctionPointer);
 
             Assert.True(fcnPtr1.IsFunctionPointerEqual(fcnPtr2));
+
+            MethodInfo m3 = t.GetMethod(nameof(FunctionPointerHolder.GenericMethodReturnValue), Bindings);
+            Type fcnPtr3 = m3.ReturnType;
+            Assert.True(fcnPtr3.IsFunctionPointer);
+            Assert.True(fcnPtr3.ContainsGenericParameters);
```
Comment (steveharter) [inline src/libraries/Common/tests/System/FunctionPointerTests.cs:163]: It would be good to add a test for FP generic arguments as well (in addition to return type here); can be done later.

**Review by steveharter — APPROVED** [review]
Thanks

File: src/coreclr/vm/typedesc.cpp (hunk 2 above)
Comment (jkotas) [reply src/coreclr/vm/typedesc.cpp:120]: `GetRootParamType` returns the root param type that works better for nested param types. It is used in similar situations in this file.

For example, `int* [][]`. With `GetTypeParam`, we would have 3 recursive calls. With `GetRootParamType`, there won't be any recursive calls since `GetRootParamType` skips all the way to `int` immediately.

**Review by ivanpovazan — APPROVED** [review]
The Mono part looks good, thank you!

**Comment by steveharter** [comment]
Consider backporting to release/8.0; missing functionality for new feature added in 8.0.

cc @ericstj
