### PR TITLE
Fix DispatchProxy not working with in parameters

### LINKED ISSUE #47522: Add support for 'in' decorator on method parameters for DispatchProxy
This code:
```cs
       public interface ISample
        {
            void Foo(in int bar);
        }

        public class SampleProxy : DispatchProxy
        {
            public static ISample CreateProxy()
            {
                return DispatchProxy.Create<ISample, SampleProxy>();
            }

            protected override object Invoke(MethodInfo targetMethod, object[] args)
            {
                return null;
            }
        }

        [Test]
        public void CreateProxyTest()
        {
            var proxy = SampleProxy.CreateProxy();
        }
```

throws the exception
```
System.TypeLoadException : Signature of the body and declaration in a method implementation do not match.  Type: 'generatedProxy_1'.  Assembly: 'ProxyBuilder, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at System.Reflection.DispatchProxyGenerator.ProxyBuilder.CreateType()
   at System.Reflection.DispatchProxyGenerator.GenerateProxyType(Type baseType, Type interfaceType)
   at System.Reflection.DispatchProxyGenerator.GetProxyType(Type baseType, Type interfaceType)
   at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(Type baseType, Type interfaceType)
   at System.Reflection.DispatchProxy.Create[T,TProxy]()
```

### PR DESCRIPTION
**Pull request by wzchua**
Resolves https://github.com/dotnet/runtime/issues/47522

### CODE REVIEW

File: src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs [hunk 1]
```diff
@@ -394,9 +394,25 @@ internal void AddInterfaceImpl([DynamicallyAccessedMembers(DynamicallyAccessedMe
...
+                for (int i = 0; i < parameters.Length; i++)
+                {
+                    paramTypes[i] = parameters[i].ParameterType;
+                    paramReqMods[i] = parameters[i].GetRequiredCustomModifiers();
+                    paramOptMods[i] = parameters[i].GetOptionalCustomModifiers();
+                }
+
+                ParameterInfo returnParameter = mi.ReturnParameter;
+                Type[] returnReqMods = returnParameter.GetRequiredCustomModifiers();
+                Type[] returnOptMods = returnParameter.GetRequiredCustomModifiers();
```
Comment (watfordgnf) [inline src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs:410]: Typo?
```suggestion
                Type[] returnOptMods = returnParameter.GetOptionalCustomModifiers();
```

Comment (wzchua) [reply src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs]: opps

File: src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs [hunk 2]
```diff
@@ -394,9 +394,25 @@ internal void AddInterfaceImpl([DynamicallyAccessedMembers(DynamicallyAccessedMe
...
+                    paramOptMods[i] = parameters[i].GetOptionalCustomModifiers();
+                }
+
+                ParameterInfo returnParameter = mi.ReturnParameter;
+                Type[] returnReqMods = returnParameter.GetRequiredCustomModifiers();
+                Type[] returnOptMods = returnParameter.GetOptionalCustomModifiers();
+
+                MethodBuilder mdb = _tb.DefineMethod(mi.Name, MethodAttributes.Public | MethodAttributes.Virtual, CallingConventions.HasThis,
+                    returnParameter.ParameterType, returnReqMods, returnOptMods,
+                    paramTypes, paramReqMods, paramOptMods);
```
Comment (buyaa-n) [inline src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs:414]: Thanks, @wzchua , looks good to me.
To avoid side effects I would pass null for unnecessary parameters, plus i believe it's better to use the CallingConventions.Standard which was used by default in the previous call
```suggestion
                MethodBuilder mdb = _tb.DefineMethod(mi.Name, MethodAttributes.Public | MethodAttributes.Virtual, CallingConventions.Standard,
                    mi.ReturnType, null, null,
                    paramTypes, paramReqMods, null);
```

File: src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs [hunk 3]
```diff
@@ -394,9 +394,25 @@ internal void AddInterfaceImpl([DynamicallyAccessedMembers(DynamicallyAccessedMe
...
+                for (int i = 0; i < parameters.Length; i++)
+                {
+                    paramTypes[i] = parameters[i].ParameterType;
+                    paramReqMods[i] = parameters[i].GetRequiredCustomModifiers();
+                    paramOptMods[i] = parameters[i].GetOptionalCustomModifiers();
+                }
+
+                ParameterInfo returnParameter = mi.ReturnParameter;
+                Type[] returnReqMods = returnParameter.GetRequiredCustomModifiers();
+                Type[] returnOptMods = returnParameter.GetOptionalCustomModifiers();
```
Comment (buyaa-n) [inline src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs:410]: Please remove all unneeded variables here and above
```suggestion
```

File: src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs (hunk 2 above)
Comment (wzchua) [reply src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs:414]: ok. I thought it would be more correct for all the mods to be included.
I made a mistake with the CallingConventions.

File: src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs [hunk 4]
```diff
@@ -394,9 +394,19 @@ internal void AddInterfaceImpl([DynamicallyAccessedMembers(DynamicallyAccessedMe
             private MethodBuilder AddMethodImpl(MethodInfo mi, int methodInfoIndex)
             {
                 ParameterInfo[] parameters = mi.GetParameters();
-                Type[] paramTypes = ParamTypes(parameters, false);
+                Type[] paramTypes = new Type[parameters.Length];
```
Comment (krwq) [inline src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs:397]: Is ParamBytes still used anywhere?

File: src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs (hunk 2 above)
Comment (buyaa-n) [reply src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs]: > ok. I thought it would be more correct for all the mods to be included.

Understand your motive, but adding those could affect performance, as we don't have a known issue with not adding them I prefer keep the existing behavior

**Review by buyaa-n — APPROVED** [review]
Thanks, @wzchua LGTM

**Review by krwq — APPROVED** [review]

**Comment by krwq** [comment]
I've closed, reopened to restart the CI

File: src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs (hunk 4 above)
Comment (campersau) [reply src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs:397]: It is used on this line but it seems that it is also not needed there. I will create a PR for that.
