### PR TITLE
Don't scan bricks of frozen segments in verify_heap

### LINKED ISSUE #75819: Test failure JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh
Run: [runtime-coreclr gcstress-extra 20220917.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=21282&view=ms.vss-test-web.build-test-results-tab&runId=427634&resultId=104537&paneView=debug)

Failed test:
```
coreclr Linux arm Checked gcstress0xc_zapdisable_heapverify1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/jit64/regress/vsw/539509/test1/test1.sh
- JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.sh
- JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b309539/b309539/b309539.sh
- JIT/Regression/JitBlue/GitHub_19438/GitHub_19438/GitHub_19438.sh
- GC/Coverage/LargeObjectAlloc/LargeObjectAlloc.sh
- JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b091942/b091942/b091942.sh
- GC/Coverage/LargeObjectAlloc2/LargeObjectAlloc2.sh
... ...
```
**Error message:**
```
[createdump] waitpid() returned successfully (wstatus 00000000)
/root/helix/work/workitem/e/JIT/jit64/regress/vsw/539509/test1/test1.sh: line 405:   266 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.jit64/regress/vsw/539509/test1/test1.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false test1.dll ''
Testing AA::Method1
Exception handled: System.InvalidCastException: Unable to cast object of type 'BB' to type 'AA6[System.SByte,System.Byte,System.UInt32,System.UInt32,System.Int64,System.Boolean]'. at App.Main() Testing AA::Static1 Exception handled: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. at AA6.Static1(TF param1)
at App.Main()
Testing AA::Static2
Exception handled: System.InvalidCastException: Unable to cast object of type 'AA6[System.SByte,System.Byte,System.UInt32,System.UInt32,System.Int64,System.Boolean]' to type 'System.SByte[][,,,]'. at AA6.Static2(UInt64 param1, Int16 param2, UInt32& param3, TA& param4)
at App.Main()
Testing AA::Static3
Exception handled: System.NullReferenceException: Object reference not set to an instance of an object.
at AA`6.Static3(TestEnum param1, Int16 param2)
at App.Main()
Testing AA::Static4
Testing AA::Static5
[createdump] Gathering state for process 266 corerun
[createdump] Crashing thread 0000010a signal 00000005
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.266.dmp
[createdump] Written 200278016 bytes (48896 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 3640ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/jit64/regress/vsw/539509/test1/test1.sh
Expected: True
Actual:   False


Stack trace
   at JIT_jit64._regress_vsw_539509_test1_test1_._regress_vsw_539509_test1_test1_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### LINKED ISSUE #75820: Test failure readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd
Run: [runtime-coreclr gcstress-extra 20220917.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=21282&view=ms.vss-test-web.build-test-results-tab&runId=427766&resultId=108497&paneView=debug)

Failed test:
```
coreclr windows x86 Checked heapverify1 @ Windows.10.Amd64.Open
- readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd
- JIT\\Stress\\ABI\\pinvokes_do\\pinvokes_do.cmd
- JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
- readytorun\\r2rdump\\FrameworkTests\\R2RDumpTests\\R2RDumpTests.cmd
- JIT\\Regression\\VS-ia64-JIT\\V2.0-Beta2\\b309539\\b309539\\b309539.cmd
... ...
coreclr windows x86 Checked gcstress0xc_zapdisable_heapverify1 @ Windows.10.Amd64.Open
- GC\\API\\WeakReference\\multipleWRs_1\\multipleWRs_1.cmd
- JIT\\Regression\\VS-ia64-JIT\\V2.0-Beta2\\b309539\\b309539\\b309539.cmd
- GC\\API\\WeakReference\\multipleWRs\\multipleWRs.cmd
- GC\\Coverage\\LargeObjectAlloc\\LargeObjectAlloc.cmd
- GC\\Coverage\\LargeObjectAlloc2\\LargeObjectAlloc2.cmd
... ...
coreclr windows x86 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open
- JIT\\Regression\\VS-ia64-JIT\\V2.0-Beta2\\b309539\\b309539\\b309539.cmd
- GC\\API\\WeakReference\\multipleWRs\\multipleWRs.cmd
- GC\\API\\WeakReference\\multipleWRs_1\\multipleWRs_1.cmd
- GC\\Coverage\\LargeObjectAlloc\\LargeObjectAlloc.cmd
- GC\\Coverage\\LargeObjectAlloc2\\LargeObjectAlloc2.cmd
... ...
```
**Error message:**
```
Assert failure(PID 5080 [0x000013d8], Thread: 6064 [0x17b0]): CONTRACT VIOLATION by EntryPointFilter at "D:\a_work\1\s\src\coreclr\vm\excep.cpp" @ 4969

THROWS called in a NOTHROW region.

                    CONTRACT in EntryPointFilter at "D:\a\_work\1\s\src\coreclr\vm\excep.cpp" @ 4969
VIOLATED-->  CONTRACT in WKS::GCHeap::Alloc at "D:\a_work\1\s\src\coreclr\gc\gc.cpp" @ 45830
CONTRACT in Alloc at "D:\a_work\1\s\src\coreclr\vm\gchelpers.cpp" @ 207
CONTRACT in AllocateSzArray at "D:\a_work\1\s\src\coreclr\vm\gchelpers.cpp" @ 371
CONTRACT in MethodDescCallSite::CallTargetWorker at "D:\a_work\1\s\src\coreclr\vm\callhelpers.cpp" @ 280
GCX_COOP in Assembly::ExecuteMainMethod at "D:\a_work\1\s\src\coreclr\vm\assembly.cpp" @ 1522
CONTRACT in Assembly::ExecuteMainMethod at "D:\a_work\1\s\src\coreclr\vm\assembly.cpp" @ 1506
GCX_COOP in CorHost2::ExecuteAssembly at "D:\a_work\1\s\src\coreclr\vm\corhost.cpp" @ 339
CONTRACT in CorHost2::ExecuteAssembly at "D:\a_work\1\s\src\coreclr\vm\corhost.cpp" @ 288

CORECLR! CONTRACT_ASSERT + 0x2E4 (0x6fb82a6d)
CORECLR! ClrDebugState::CheckOkayToThrow + 0x23 (0x6fb8404d)
CORECLR! BaseContract::DoChecks + 0x122 (0x6fb883be)
CORECLR! EEContract::DoChecks + 0x4B (0x6fe06bef)
CORECLR! EntryPointFilter + 0x7E (0x6fc592f4)
CORECLR! RunMain + 0xE5 (0x6fbaeec1)
CORECLR! EH4_CallFilterFunc + 0x12 (0x701ec7c2)
CORECLR! except_handler4 + 0xD4 (0x701e8774)
NTDLL! RtlConvertUlongToLargeInteger + 0xA2 (0x76f23292)
NTDLL! RtlConvertUlongToLargeInteger + 0x74 (0x76f23264)
File: D:\a_work\1\s\src\coreclr\vm\excep.cpp Line: 4969
Image: C:\h\w\A6BD09A0\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A6BD09A0\w\B6D20A0F\uploads\Reports\readytorun.coreroot_determinism\coreroot_determinism\coreroot_determinism.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A6BD09A0\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  coreroot_determinism.dll
================================== Compiling with seed 1 ==================================
Locating output folder C:\h\w\A6BD09A0\w\B6D20A0F\e\readytorun\coreroot_determinism\coreroot_determinism\seed1
Deleting 0 output folders
Successfully deleted 0 output folders in 302 msecs
Using dotnet: C:\h\w\A6BD09A0\p\corerun.exe
1 / 1 (0%, 0 failed): launching: C:\h\w\A6BD09A0\p\corerun.exe C:\h\w\A6BD09A0\p\crossgen2\crossgen2.dll @C:\h\w\A6BD09A0\w\B6D20A0F\e\readytorun\coreroot_determinism\coreroot_determinism\seed1\CPAOT-ret.out\System.Private.CoreLib.dll.rsp
1 / 1 (100%, 0 failed): succeeded in 68953 msecs: corerun.exe C:\h\w\A6BD09A0\p\crossgen2\crossgen2.dll @C:\h\w\A6BD09A0\w\B6D20A0F\e\readytorun\coreroot_determinism\coreroot_determinism\seed1\CPAOT-ret.out\System.Private.CoreLib.dll.rsp
================================== Compiling with seed 2 ==================================
Locating output folder C:\h\w\A6BD09A0\w\B6D20A0F\e\readytorun\coreroot_determinism\coreroot_determinism\seed2
Deleting 0 output folders
Successfully deleted 0 output folders in 298 msecs
Using dotnet: C:\h\w\A6BD09A0\p\corerun.exe
1 / 1 (0%, 0 failed): launching: C:\h\w\A6BD09A0\p\corerun.exe C:\h\w\A6BD09A0\p\crossgen2\crossgen2.dll @C:\h\w\A6BD09A0\w\B6D20A0F\e\readytorun\coreroot_determinism\coreroot_determinism\seed2\CPAOT-ret.out\System.Private.CoreLib.dll.rsp
1 / 1 (100%, 0 failed): succeeded in 68813 msecs: corerun.exe C:\h\w\A6BD09A0\p\crossgen2\crossgen2.dll @C:\h\w\A6BD09A0\w\B6D20A0F\e\readytorun\coreroot_determinism\coreroot_determinism\seed2\CPAOT-ret.out\System.Private.CoreLib.dll.rsp
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A6BD09A0\p
C:\h\w\A6BD09A0\w\B6D20A0F\e\readytorun\coreroot_determinism\coreroot_de


Stack trace
   at readytorun_coreroot_determinism._coreroot_determinism_coreroot_determinism_._coreroot_determinism_coreroot_determinism_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/75819
Fixes https://github.com/dotnet/runtime/issues/75820

As it turns out it's not a product issue and just HeapVerify specific, the fix is written by @Maoni0 and @cshung, I'm filing a PR because I had a reproduction setup.

For readers, there is a good read https://cshung.github.io/posts/brick/ that explains the "brick table" concept.

### CODE REVIEW

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -44422,7 +44422,27 @@ void gc_heap::verify_heap (BOOL begin_gc_p)
             uint8_t*        curr_object = heap_segment_mem (seg);
             uint8_t*        prev_object = 0;
 
+            bool verify_bricks_p = true;
 #ifdef USE_REGIONS
+            assert (!heap_segment_read_only_p (seg));
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:44427]: let's make this `FATAL_GC_ERROR` too.
```suggestion
            if (heap_segment_read_only_p (seg))
            {
                dprintf (1, ("seg %Ix is ro! Shouldn't happen with regions", (size_t)seg));
                FATAL_GC_ERROR();
            }
```

**Review by Maoni0 — APPROVED** [review]
rest LGTM!

File: src/coreclr/gc/gc.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/gc/gc.cpp:44427]: ugh, no matter how many times I tried github refuses to apply this diff: 
image

so I'm going to apply by hands and add you as co-authored
