### PR TITLE
Fix bug in RangeOps::ShiftRight

### LINKED ISSUE #123790: JIT: Wrong result with comparisons
```csharp
// Generated by Fuzzlyn v3.3 on 2026-01-30 00:24:21
// Run on Arm Linux
// Seed: 1258975953768210879
// Reduced from 90.6 KiB to 0.3 KiB in 00:00:49
// Debug: Outputs 0
// Release: Outputs 1
public class Program
{
    public static ushort s_3;
    public static ulong s_4;
    public static sbyte s_9 = -1;
    public static void Main()
    {
        if (1 >= ((ushort)s_9 >> s_3))
        {
            s_4 = 1;
        }

        System.Console.WriteLine(s_4);
    }
}
```
Repros on win-x64 too. Lots of similar looking failures in latest Fuzzlyn run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1272835&view=ms.vss-build-web.run-extensions-tab
Bisected to #123233, cc @EgorBo

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/123790

For e.g. `[0..65535] >> [0..31]` I didn't realize I need to swap lower and upper bound for r2, so the result should be:
`[0 >> 31 .. 65535 >> 0]`, not `[0 >> 0 .. 65535 >> 31]`

No [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1273474&view=ms.vss-build-web.run-extensions-tab)

### CODE REVIEW

File: src/coreclr/jit/rangecheck.h [hunk 1]
```diff
@@ -279,17 +279,6 @@ struct Range
         return lLimit.IsConstant() && uLimit.IsConstant() && IsValid();
     }
 
-    // Check if the range represents a single constant value. Example: [7..7]
-    bool IsSingleConstValue(int* pConstVal) const
```
Comment (EgorBo) [inline src/coreclr/jit/rangecheck.h:283]: Two PRs introduced similar helpers, removed one of them.

**Review by jakobbotsch — APPROVED** [review]
