### PR TITLE
[Arm64] Don't generate hardware intrinsic method bodies

### LINKED ISSUE #39618: Test failure: JIT/HardwareIntrinsics/Arm/ArmBase.Arm64/ArmBase.Arm64_ro/ArmBase.Arm64_ro.sh
failed in job: [runtime-coreclr jitstress-isas-arm 20200718.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=736979&view=ms.vss-test-web.build-test-results-tab&runId=22826408&resultId=108736&paneView=debug)

failed tests: 
JIT/HardwareIntrinsics/Arm/ArmBase.Arm64/ArmBase.Arm64_ro/ArmBase.Arm64_ro.sh
JIT/HardwareIntrinsics/Arm/ArmBase/ArmBase_ro/ArmBase_ro.sh
JIT/HardwareIntrinsics/Arm/ArmBase.Arm64/ArmBase.Arm64_r/ArmBase.Arm64_r.sh
JIT/HardwareIntrinsics/Arm/ArmBase/ArmBase_r/ArmBase_r.sh

Error message
~~~
Return code:      1
Raw output file:      /root/helix/work/workitem/JIT/HardwareIntrinsics/Reports/JIT.HardwareIntrinsics/Arm/ArmBase.Arm64/ArmBase.Arm64_ro/ArmBase.Arm64_ro.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun ArmBase.Arm64_ro.dll ''
Supported ISAs:
  AdvSimd:   False
  Aes:       False
  ArmBase:   False
  Crc32:     False
  Dp:        False
  Rdm:       False
  Sha1:      False
  Sha256:    False

Beginning test case LeadingSignCount.Int32 at 7/18/2020 8:37:01 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunUnsupportedScenario
Beginning scenario: RunBasicScenario_UnsafeRead
ERROR!!!-System.Exception: One or more scenarios did not complete as expected.

Ending test case at 7/18/2020 8:37:02 PM
Beginning test case LeadingSignCount.Int64 at 7/18/2020 8:37:02 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunUnsupportedScenario
Beginning scenario: RunBasicScenario_UnsafeRead
ERROR!!!-System.Exception: One or more scenarios did not complete as expected.

Ending test case at 7/18/2020 8:37:02 PM
Beginning test case LeadingZeroCount.Int64 at 7/18/2020 8:37:02 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunUnsupportedScenario
Beginning scenario: RunBasicScenario_UnsafeRead
ERROR!!!-System.Exception: One or more scenarios did not complete as expected.

Ending test case at 7/18/2020 8:37:02 PM
Beginning test case LeadingZeroCount.UInt64 at 7/18/2020 8:37:02 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunUnsupportedScenario
Beginning scenario: RunBasicScenario_UnsafeRead
ERROR!!!-System.Exception: One or more scenarios did not complete as expected.

Ending test case at 7/18/2020 8:37:02 PM
Beginning test case ReverseElementBits.Int64 at 7/18/2020 8:37:02 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunUnsupportedScenario
Beginning scenario: RunBasicScenario_UnsafeRead
ERROR!!!-System.Exception: One or more scenarios did not complete as expected.

Ending test case at 7/18/2020 8:37:02 PM
Beginning test case ReverseElementBits.UInt64 at 7/18/2020 8:37:02 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunUnsupportedScenario
Beginning scenario: RunBasicScenario_UnsafeRead
ERROR!!!-System.Exception: One or more scenarios did not complete as expected.

Ending test case at 7/18/2020 8:37:02 PM
Expected: 100
Actual: 0
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/HardwareIntrinsics/Arm/ArmBase.Arm64/ArmBase.Arm64_ro/ArmBase.Arm64_ro.sh
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._Arm_ArmBase_Arm64_ArmBase_Arm64_ro_ArmBase_Arm64_ro_._Arm_ArmBase_Arm64_ArmBase_Arm64_ro_ArmBase_Arm64_ro_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/JIT.HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.cs:line 2371
~~~

### PR DESCRIPTION
**Pull request by echesakov**
Fixes #39618

### CODE REVIEW

File: src/coreclr/src/zap/zapinfo.cpp [hunk 1]
```diff
@@ -2150,15 +2150,19 @@ DWORD FilterNamedIntrinsicMethodAttribs(ZapInfo* pZapInfo, DWORD attribs, CORINF
...
-        // For Arm64, AdvSimd/ArmBase is the baseline that is suported and hence we do pregenerate the method bodies
-        // of ARM64 harware intrinsic.
         fTreatAsRegularMethodCall = (fIsGetIsSupportedMethod && fIsPlatformHWIntrinsic);
-#if !defined(TARGET_ARM64)
-        fTreatAsRegularMethodCall |= (!fIsPlatformHWIntrinsic && fIsHWIntrinsic);
+
+#if defined(TARGET_ARM64)
+        if (!fIsPlatformHWIntrinsic && fIsHWIntrinsic)
+        {
+            fTreatAsRegularMethodCall = (strcmp(className, "Vector64`1") != 0) && (strcmp(className, "Vector128`1") != 0);
```
Comment (tannergooding) [inline src/coreclr/src/zap/zapinfo.cpp:2162]: Why don't we need something similar for `Vector128<T>` and `Vector256<T>` on x86?

Comment (tannergooding) [reply src/coreclr/src/zap/zapinfo.cpp:2162]: (I might just be missing where we cover it, if it exists somewhere)

Comment (kunalspathak) [inline src/coreclr/src/zap/zapinfo.cpp:2162]: you are missing `|=`. It should be `fTreatAsRegularMethodCall |= (strcmp(className, "Vector64`1") != 0) && (strcmp(className, "Vector128`1") != 0);`

Comment (echesakovMSFT) [reply src/coreclr/src/zap/zapinfo.cpp:2162]: No, I am not.

Consider this:
1) If `fTreatAsRegularMethodCall=true` before line 2160, then it means `fIsPlatformHWIntrinsic=true` and the if-condition is false.
2) If `fTreatAsRegularMethodCall=false` before line 2160, then `fTreatAsRegularMethodCall = fTreatAsRegularMethodCall || (if-cond-expr)` is equvalent to `fTreatAsRegularMethodCall = (if-cond-expr)`.

I could've written this as 
```c++
fTreatAsRegularMethodCall = (fIsGetIsSupportedMethod && fIsPlatformHWIntrinsic) || (!fIsPlatformHWIntrinsic && fIsHWIntrinsic 
#if defined(TARGET_ARM64)
    && ((strcmp(className, "Vector64`1") == 0) || (strcmp(className, "Vector128`1") == 0))
#endif
);
```

Comment (echesakovMSFT) [reply src/coreclr/src/zap/zapinfo.cpp:2162]: My understanding (that could be incorrect) is that on x86 in R2R code we want to treat all calls outside of System.Runtime.Intrinsics.X86 as regular calls since there is no guarantee what ISAs will be supported on target platform while on Arm64 - ArmBase and AdvSimd are baseline and always supported.

@davidwrighton Is it correct interpretation of discussion in https://github.com/dotnet/runtime/pull/38060?

Comment (tannergooding) [reply src/coreclr/src/zap/zapinfo.cpp:2162]: Ah right. I remember this reasoning now. It always confuses me at first 😄

Comment (kunalspathak) [reply src/coreclr/src/zap/zapinfo.cpp:2162]: Yes either that or something like this:
```cpp
        fTreatAsRegularMethodCall = (fIsGetIsSupportedMethod && fIsPlatformHWIntrinsic);

        if (!fIsPlatformHWIntrinsic && fIsHWIntrinsic)
        {
#if defined(TARGET_ARM64)
            // For ARM64, treat as method calls if HWIntrinsic is not the one supported.
            fTreatAsRegularMethodCall |= (strcmp(className, "Vector64`1") != 0) && (strcmp(className, "Vector128`1") != 0);
#else
            // For XArch, always treat HWIntrinsic as method calls.
  	    fTreatAsRegularMethodCall |= true;
#endif 
        }
```

Currently, it just feels like we override the `fTreatAsRegularMethodCall` without carefully inspecting the code the way you pointed.

Comment (echesakovMSFT) [reply src/coreclr/src/zap/zapinfo.cpp]: I pushed the simpler change. I think it's better to repeat `(!fIsPlatformHWIntrinsic && fIsHWIntrinsic)` twice.

File: src/coreclr/src/zap/zapinfo.cpp [hunk 2]
```diff
@@ -450,7 +450,7 @@ void ZapInfo::CompileMethod()
     }
 #endif
 
-#if defined(TARGET_X86) || defined(TARGET_AMD64)
+#if defined(TARGET_X86) || defined(TARGET_AMD64) || defined(TARGET_ARM64)
     if (methodAttribs & CORINFO_FLG_JIT_INTRINSIC)
```
Comment (echesakovMSFT) [inline src/coreclr/src/zap/zapinfo.cpp:454]: @AntonLapounov Can you please show me the place when I can disable pre-generation of the intrinsics bodies on Arm64 in CrossGen2?

**Review by kunalspathak — APPROVED** [review]
LGTM

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/src/zap/zapinfo.cpp (hunk 2 above)
Comment (AntonLapounov) [reply src/coreclr/src/zap/zapinfo.cpp:454]: I think `CorInfoImpl.ShouldSkipCompilation` controls that.

Comment (echesakovMSFT) [reply src/coreclr/src/zap/zapinfo.cpp:454]: It looks it already does this right
https://github.com/dotnet/runtime/blob/557c7aff0d63fbb1bf687be215ec1726625abc2a/src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs#L190-L193

Thanks!
