### PR TITLE
Fix il verification tests

### LINKED ISSUE #39504: JitStress job is failing to build ILVerification.Tests.csproj
Build test job is failing with:
```
2020-07-17T05:03:25.9257110Z /Users/runner/work/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/Microsoft.Common.CurrentVersion.targets(3036,5): error MSB3552: Resource file "../Common/TypeSystem/Common/Properties/Resources.resx" cannot be found. [/Users/runner/work/1/s/src/tests/ilverify/ILVerification.Tests.csproj]
2020-07-17T05:03:25.9354070Z ##[error].dotnet/sdk/5.0.100-preview.8.20362.3/Microsoft.Common.CurrentVersion.targets(3036,5): error MSB3552: Resource file "../Common/TypeSystem/Common/Properties/Resources.resx" cannot be found.
```
[Ci link (note that it is a scheduled run, not a manual one)
](https://dev.azure.com/dnceng/public/_build/results?buildId=734828&view=results)I could repro that locally and found that it stopped working after https://github.com/dotnet/runtime/pull/39340

The strange thing is that it is passing in the outerloop: 
```
2020-07-15T22:40:40.4502140Z   ILVerification.Tests -> /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/ilverify/ILVerification.Tests.dll
2020-07-15T22:40:40.6241280Z   IsInst001 -> /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/Loader/classloader/generics/Variance/IL/IsInst001/IsInst001.dll
```

I was not able to find what is the difference between these two.

@davidwrighton could you please take a look?
cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by davidwrighton**
- Re-enable the test project build
- Change string resources in type system to directly use ResourceManager instead of SR abstraction which is unavaliable in the test build tree
- Add test to verify that all ExceptionStringID values have associated strings
- Use ToolsCommonPath property to successfully reference the correct resource file

Fixes #39504

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/crossgen-contrib 
@sandreenko

**Comment by davidwrighton** [comment]
As a side benefit I tweaked the source so that it uses `Path.Combine` to handle directory work, so this test now passes on Linux as well as on Windows.

File: src/coreclr/src/tools/Common/TypeSystem/Common/TypeSystemException.cs [hunk 1]
```diff
@@ -13,6 +16,9 @@ public abstract class TypeSystemException : Exception
     {
         private string[] _arguments;
 
+        private static Lazy<ResourceManager> s_stringResourceManager =
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/Common/TypeSystem/Common/TypeSystemException.cs:19]: Would it be possible to pull this out of `TypeSystemException` into a separate file? This will not work the the type system is used as a runtime type system (we need to be able to get rid of `ResourceManager` in the [UseSystemResourceKeys](https://github.com/dotnet/runtime/blob/master/docs/workflow/trimming/feature-switches.md) mode and that one relies on the SR type.

I think now I'm remembering why these were `[TEMPORARY EXCEPTION MESSAGE]` for such a long time...

Comment (davidwrighton) [reply src/coreclr/src/tools/Common/TypeSystem/Common/TypeSystemException.cs:19]: Yes, I'll pull these out into a separate file. Good point on the CoreRT impact. I had forgotten some of these details. Someone in the CoreRT repo will need to implement the resource lookup function in whatever way actually makes sense at runtime.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!
