### PR TITLE
[wasm][debugger] Fix get properties from an object of a library without pdb

### LINKED ISSUE #71456: [wasm][debugger] Debugger not working when managed libraries don't have pdb file
In a Blazor Wasm App:

Change the content of the Counter.razor:

```
@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        var temp = new Exception("throwing new ex");
        Console.WriteLine(temp);
        currentCount++;
    }
}
```

Add a breakpoint on line currentCount++;
Try to expand variable `temp`.
If we are using a release build of the runtime, or a installed version of .net7.
We cannot get this information https://github.com/dotnet/runtime/blob/cd553b7208db0df889d8fbb325de65182443bb31/src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs#L329

This returns null, as we don't have debug symbols, then we throw an exception and cannot get any value if this variable `temp`.
We need to refactor this code to be able to get the values even in a release version of managed libraries.

### PR DESCRIPTION
**Pull request by thaystg**
When we don't have pdb we still can get some information about the methods like attributes (public, private, protected, etc) which are used for a better debugger experience.

Before this implementation when we call:
```
MethodInfoWithDebugInformation getterInfo = await sdbHelper.GetMethodInfo(getMethodId, token);
MethodAttributes getterAttrs = getterInfo.Info.Attributes;
```
`GetMethodInfo` returned `null` because we didn't add method without debug info and then it throws an exception on `getterInfo.Info.Attributes` because `getterInfo` was null.

Fixes #71456

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 1]
```diff
@@ -333,6 +333,7 @@ internal sealed class MethodInfo
         public MethodDebugInformation DebugInformation;
         public MethodDefinitionHandle methodDefHandle;
         private MetadataReader pdbMetadataReader;
+        private bool hasDebugInformation;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:336]: nit: IIUC, we can skip this, and just check `DebugInformation is not null` in the two places we use this?

**Review by radical — APPROVED** [review]
Other than the one comment, LGTM 👍
