### PR TITLE
JIT: Fix initblk/cpblk and STORE_DYN_BLK size mismatch

### LINKED ISSUE #78912: System.Net.Http.Unit.Tests failing under jitstress
Failure: https://dev.azure.com/dnceng-public/public/_build/results?buildId=94300&view=ms.vss-test-web.build-test-results-tab
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ab9b9480b24c424cbe/System.Net.Http.Unit.Tests/1/console.eb002831.log?helixlogtype=result

After some bisection it looks related to ``System.Net.Http.Unit.Tests.HPack.HPackRoundtripTests:HPackEncode(System.Net.Http.Headers.HttpHeaders,System.Text.Encoding):System.Memory`1[ubyte]``. The bug repros with
```bash
export DOTNET_JitStressRange=27a5bb45-ffffffff
```

but not with
```bash
export DOTNET_JitStressRange=27a5bb46-ffffffff
```

and that hash corresponds to `HPackEncode`. But, strangely, it also does not repro with just that hash in the range.

### PR DESCRIPTION
**Pull request by jakobbotsch**
STORE_DYN_BLK turns into a call to JIT_MemSet/JIT_MemCpy that go quite directly to memset/memcpy, so the size is actually a native uint. This can cause problems since the JIT does not make any normalization guarantees above 32 bits.

Fix #78912

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

Small number of [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=95473&view=ms.vss-build-web.run-extensions-tab). Alternatively we could move the normalization into `JIT_MemSet`/`JIT_MemCpy` and change the argument to a 32-bit integer.

**Review by EgorBo — APPROVED** [review]

**Comment by jakobbotsch** [comment]
> I assume you meant to add new 32bit overloads instead of changing existing ones, right?

I don't think introducing overloads would be necessary, there are very few uses of these helpers.

**Comment by EgorBo** [comment]
> > I assume you meant to add new 32bit overloads instead of changing existing ones, right?
> 
> I don't think introducing overloads would be necessary, there are very few uses of these helpers.

Ah I thought that `Unsafe.InitBlockUnaligned` had `nuint` length

File: src/coreclr/jit/morphblock.cpp [hunk 1]
```diff
@@ -1571,9 +1571,8 @@ GenTree* Compiler::fgMorphStoreDynBlock(GenTreeStoreDynBlk* tree)
     if (tree->gtDynamicSize->IsIntegralConst())
     {
         int64_t size = tree->gtDynamicSize->AsIntConCommon()->IntegralValue();
-        assert(FitsIn<int32_t>(size));
 
-        if (size != 0)
+        if ((size != 0) && FitsIn<int32_t>(size))
```
Comment (kunalspathak) [inline src/coreclr/jit/morphblock.cpp:1575]: If i understand correctly, with your casting changes in importer, we would hit this assert and hence moving this to if-check is necessary?

**Comment by kunalspathak** [comment]
I am wondering what exposed this bug now?

File: src/coreclr/jit/morphblock.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/morphblock.cpp:1575]: We should not see this in practice since we only create these nodes in very limited circumstances, when we see `initblk`/`cpblk`. But it wouldn't be considered illegal to have a `CNS_INT` node in this position with a native int > 2^31 anymore, so we shouldn't have asserts about that.

**Comment by jakobbotsch** [comment]
> I am wondering what exposed this bug now?

Don't know, unfortunately that's not easy to figure out. The repro requires a small property to not be inlined which is occurring in stress, so perhaps inlining changes or stress decision changes caused it to be exposed.

**Review by kunalspathak — APPROVED** [review]
