### PR TITLE
[mono][debugger] Fix inspect Span<byte>

### LINKED ISSUE #8792: Crash on android device with "Assertion at /__w/1/s/src/mono/mono/component/debugger-agent.c:5652"
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS 2022 17.9.2

### Description

My android app starts on an android device, and quickly crashes with this in the debug output window:

> Assertion at /__w/1/s/src/mono/mono/component/debugger-agent.c:5652, condition `extra_space != NULL && *extra_space != NULL' not met
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5599 (bank.eZcash.App), pid 5599 (bank.eZcash.App)

### Steps to Reproduce

This doesn't repro on the most simple app that executes the same code that crashes in the original, so I'm not sure what else the app is doing or has done previously to get it into a state where the code fails. But for what it's worth, the method that just starts when the app crashes is:

```cs
public static Bip39Mnemonic Create(int entropyLengthInBits, ReadOnlyMemory<char> password)
{
	Requires.Argument(entropyLengthInBits % 32 == 0, nameof(entropyLengthInBits), Strings.MustBeNonZeroMultipleOf32);
	Span<byte> entropy = stackalloc byte[entropyLengthInBits / 8];
	RandomNumberGenerator.Fill(entropy);
	return new(entropy, password);
}
```

Note that a breakpoint set on the opening `{` is hit, but before I can even hit F10 to Step in the debugger, the app then crashes. It crashes whether or not the debugger is attached, though the crash without the debugger might be for another cause -- I can't tell.

### Did you find any workaround?

No

### Relevant log output

```shell
Here is the tail of the debug log:


[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Primitives.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encoding.Extensions.dll
Loaded assembly: /data/data/com.Nerdbank.eZcash.App/files/.__override__/System.Text.Encoding.Extensions.dll [External]
Resolved pending breakpoint at 'Bip39Mnemonic.cs:94,1' to Nerdbank.Bitcoin.Bip39Mnemonic Nerdbank.Bitcoin.Bip39Mnemonic.Create (int entropyLengthInBits, System.ReadOnlyMemory<char> password) [0x00000].
[bank.eZcash.App] * Assertion at /__w/1/s/src/mono/mono/component/debugger-agent.c:5652, condition `extra_space != NULL && *extra_space != NULL' not met
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5599 (bank.eZcash.App), pid 5599 (bank.eZcash.App)
[bank.eZcash.App] Background concurrent mark compact GC freed 12233(6984KB) AllocSpace objects, 0(0B) LOS objects, 91% free, 2221KB/26MB, paused 523us,5.172ms total 17.965ms
```
```

### PR DESCRIPTION
**Pull request by thaystg**
Fix https://github.com/xamarin/xamarin-android/issues/8792

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

File: src/mono/mono/component/debugger-agent.c [hunk 1]
```diff
@@ -5581,6 +5581,7 @@ decode_value_compute_size (MonoType *t, int type, MonoDomain *domain, guint8 *bu
 	if (type != t->type && !MONO_TYPE_IS_REFERENCE (t) &&
 		!(t->type == MONO_TYPE_I && type == MONO_TYPE_VALUETYPE) &&
 		!(type == VALUE_TYPE_ID_FIXED_ARRAY) &&
+		!(type == MDBGPROT_VALUE_TYPE_ID_NULL) &&
 		!(t->type == MONO_TYPE_U && type == MONO_TYPE_VALUETYPE) &&
 		!(t->type == MONO_TYPE_PTR && type == MONO_TYPE_I8) &&
 		!(t->type == MONO_TYPE_FNPTR && type == MONO_TYPE_I8) &&
```
Comment (lambdageek) [inline src/mono/mono/component/debugger-agent.c:5587]: future cleanup: this should be a separate helper function. maybe `gboolean valuetype_is_blittable_assignable_from(MonoType *debugger_type, MonoType *expected_type)` ?  and make the condition `if (type != t->type && !MONO_TYPE_IS_REFERENCE(t) && !valuetype_is_blittable_assignable_from(type, t->type)) { ... error ... }`  (I'm not sure that is the best name)

**Review by lambdageek — APPROVED** [review]

File: src/mono/mono/component/debugger-agent.c (hunk 1 above)
Comment (thaystg) [reply src/mono/mono/component/debugger-agent.c:5587]: Thanks, @lambdageek , I will do it in my next PR on debugger-agent.
