### PR TITLE
JIT: Refactor async-to-sync call optimization

### LINKED ISSUE #124545: Static virtual calls go through task-returning thunks always
Example from @MichalStrehovsky:
```csharp
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Xunit;

public class StaticVirtual
{
    interface IHaveStaticVirtuals
    {
        static abstract Task DoTask();
    }

    class ClassWithStaticVirtuals : IHaveStaticVirtuals
    {
        public static async Task DoTask() => await Task.Yield();
    }

    static async Task CallDoTask<T>() where T : IHaveStaticVirtuals => await T.DoTask();

    [Fact]
    public static void TestEntryPoint()
    {
        CallDoTask<ClassWithStaticVirtuals>().Wait();
    }
}
```

We see task-returning thunk created for `DoTask`. This is a regression introduced by #124283. We do not properly detect that this is a virtual call.

### PR DESCRIPTION
**Pull request by jakobbotsch**
- Introduce `getAsyncOtherVariant` JIT-EE API that returns the other async variant of an async/task-returning method
- Remove the `AwaitVirtual` token kind that was used to allow the VM to tell the JIT to prefer a task-returning instead of async variant
- Implement the same optimization on the JIT side instead using the `getAsyncOtherVariant`, when we notice that a call will be direct
- Fix ilc.slnx and crossgen2.slnx to compile from VS
- `ActiveIssue` async EH tests under interpreter against #124044

Fix #124545

### CODE REVIEW

File: src/coreclr/inc/corinfo.h [hunk 1]
```diff
@@ -2288,6 +2287,12 @@ class ICorStaticInfo
         CORINFO_CLASS_HANDLE* classArg
         ) = 0;
 
+    // Get the other variant of an async method, if possible.
```
Comment (janvorli) [inline src/coreclr/inc/corinfo.h:2290]: Could you please add some more detail to the comment on what the "other" variant is?

File: src/coreclr/interpreter/compiler.cpp [hunk 2]
```diff
@@ -4576,14 +4577,30 @@ void InterpCompiler::EmitCall(CORINFO_RESOLVED_TOKEN* pConstrainedToken, bool re
...
-            BADCODE("We're trying to emit an async call, but the async resolved context didn't find one");
+            bool isSyncCallThunk;
+            m_compHnd->getAsyncOtherVariant(callInfo.hMethod, &isSyncCallThunk);
+            if (!isSyncCallThunk)
+            {
+                // The async variant that we got is a thunk. Switch back to the
+                // non-async task-returning call. There is no reason to create
+                // and go through the thunk.
+                ResolveToken(token, CORINFO_TOKENKIND_Method, &resolvedCallToken);
+                m_ip = origIP + 5;
```
Comment (janvorli) [inline src/coreclr/interpreter/compiler.cpp:4599]: It seems we don't need to save the origIP as at this point the m_ip would always be the same as origIP, unless I am mising something.

File: src/coreclr/interpreter/compiler.cpp [hunk 3]
```diff
@@ -4576,14 +4577,30 @@ void InterpCompiler::EmitCall(CORINFO_RESOLVED_TOKEN* pConstrainedToken, bool re
...
+                continuationContextHandling = ContinuationContextHandling::None;
+                m_compHnd->getCallInfo(&resolvedCallToken, pConstrainedToken, m_methodInfo->ftn, flags, &callInfo);
+            }
+        }
+
+        if (callInfo.sig.isVarArg())
```
Comment (janvorli) [inline src/coreclr/interpreter/compiler.cpp:4605]: A nit - can we move this block back to where it was before to minimize the diff?

**Review by janvorli — APPROVED** [review]
LGTM (I haven't looked at the JIT changes), I have just few nits.

File: src/coreclr/inc/corinfo.h (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/inc/corinfo.h:2290]: Sure, but this is the existing terminology used by e.g. `MethodDesc::GetAsyncOtherVariant`, `AsyncVariantLookup::AsyncOtherVariant` etc. So perhaps the JIT-EE interface would not be the right place to document it?

File: src/coreclr/interpreter/compiler.cpp (hunk 2 above)
Comment (jakobbotsch) [reply src/coreclr/interpreter/compiler.cpp:4599]: `m_ip` gets changed by `AsyncCallPeeps.FindAndApplyPeep` above -- this is undoing the change when we decide to not actually dispatch through the async call. Let me add a comment.

File: src/coreclr/interpreter/compiler.cpp (hunk 3 above)
Comment (jakobbotsch) [reply src/coreclr/interpreter/compiler.cpp:4605]: The reason I moved it down here is that `callInfo` is getting updated above, and only at this point do we have the call info for the final call we will make. In practice that doesn't really matter since async calls cannot be varargs, through, so we can move it. Would you still like me to do that?

File: src/coreclr/inc/corinfo.h (hunk 1 above)
Comment (janvorli) [reply src/coreclr/inc/corinfo.h:2290]: Ah ok, I haven't realized that. Then there is no need to change the comment.

File: src/coreclr/interpreter/compiler.cpp (hunk 2 above)
Comment (janvorli) [reply src/coreclr/interpreter/compiler.cpp:4599]: Ah, makes sense.

File: src/coreclr/interpreter/compiler.cpp (hunk 3 above)
Comment (janvorli) [reply src/coreclr/interpreter/compiler.cpp:4605]: Ok, then leave your change as is.

**Review by davidwrighton — APPROVED** [review]
