### PR TITLE
Fix for arm64 outerloop jitstress failures in FMA

### LINKED ISSUE #126379: Test Failure: _AdvSimd_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Program.MultiplyBySelectedScalarWideningUpperAndAdd_Vector128_Int16_Vector128_Int16_7()
**Summary:**
**3152 ARM64 HW intrinsic test failures** across all jitstress2_jitstressregs modes (0x80, 8, 1, 3) on linux, windows, and osx. All failures occur in the RunReflectionScenario_UnsafeRead scenario. Affected operations include BySelectedScalar (1674), ShiftLeftAndInsert (324), ShiftRightAndInsert (210), BySelectedQuadruplet (36), and Sve2 shift/multiply operations. Non-reflection scenarios (BasicScenario, LclVarScenario, ClassFldScenario, StructFldScenario) pass.

**Failed in (1):**
- [runtime-coreclr jitstress2-jitstressregs 20260330.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1359061)

**Console Log:** [Console Log](https://helix.dot.net/api/2019-06-17/jobs/3f513d19-f4b2-4ea8-b4bc-5c357232c80c/workitems/HardwareIntrinsics_Arm_r/console)
-  **Source:** [runtime-coreclr jitstress2-jitstressregs / coreclr linux arm64 Checked jitstress2_jitstressregs1 @ AzureLinux.3.Arm64.Open / _AdvSimd_Arm64_r::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.FusedMultiplyAddBySelectedScalar_Vector64_Single_Vector128_Single_3()](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1359061&view=ms.vss-test-web.build-test-results-tab)

**Error Message:**
```
Arm64.FusedMultiplyAddBySelectedScalar<Single>(Vector64<Single>, Vector64<Single>, Vector128<Single>): RunReflectionScenario_UnsafeRead failed:
   firstOp: (0.2073351, 0.2636208)
  secondOp: (0.7460422, 0.16575699)
System.Exception: One or more scenarios did not complete as expected.
```

**Stack Trace:**
```
   at JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.FusedMultiplyAddBySelectedScalar_Vector64_Single_Vector128_Single_3() in gen/FusedMultiplyAddBySelectedScalar.Vector64.Single.Vector128.Single.3.cs:line 61
```

**Analysis:**
Root cause: The JIT generates incorrect code for ARM64 hardware intrinsic methods when invoked via reflection (RunReflectionScenario_UnsafeRead) under JitStress2 + JitStressRegs stress modes. The reflection path goes through a different JIT compilation path that is sensitive to register allocation stress. The failures are consistent across all arm64 platforms (linux, windows, osx) and all jitstressregs modes (0x80, 8, 1, 3), producing wrong results (not crashes). The affected intrinsics span AdvSimd, AdvSimd.Arm64, Rdm, Rdm.Arm64, Dp, and Sve2 instruction sets. No existing GitHub issue found matching this pattern.

### PR DESCRIPTION
**Pull request by dhartglassMSFT**
Previous codegen for FMLA, when supplied with a non-constant operand, looked something like:
```
mov     v0.8b, v8.8b // fill in RMW operand
br      x20
fmla    v0.2s, v9.2s, v10.s[0]
b       G_M19624_IG23
fmla    v0.2s, v9.2s, v10.s[1]
b       G_M19624_IG23
// and so on for each of the immediates
```
With the recent refactor to move the mov-emit-for-RMW down into the emit routines, the mov is emitted instead when codegen happens for each arm of the jump table:
```
br      x20
mov     v0.8b, v8.8b                    // fill in RMW operand
fmla    v0.2s, v9.2s, v10.s[0]
b       G_M19624_IG24
mov     v0.8b, v8.8b                   // fill in RMW operand
fmla    v0.2s, v9.2s, v10.s[1]
b       G_M19624_IG24
// etc...
```
Bug happens because the jump table builder thought each case would contain only 1 instruction, not two.

@a74nh Another option to fix this is to undo the refactor just for this case, and not duplicate the mov in each branch.  This would yield slightly smaller codesize.  I think it shouldn't matter much overall because the size difference is small, and the non-constant-operand case is rare.  Let me know if we should go this route instead

fixes #126379

### CODE REVIEW

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp [hunk 1]
```diff
@@ -469,7 +473,10 @@ void CodeGen::genHWIntrinsic(GenTreeHWIntrinsic* node)
                     {
                         assert(isRMW);
 
-                        HWIntrinsicImmOpHelper helper(this, intrin.op4, node);
+                        // emitIns_R_R_R_R_I may emit a mov (when not redundant) for RMW instructions;
+                        // the ImmOpHelper must account for that mov
+                        int                    numInstrs = (targetReg != op1Reg) ? 2 : 1;
```
Comment (a74nh) [inline src/coreclr/jit/hwintrinsiccodegenarm64.cpp:478]: We could add some extra abstraction here:
`bool willEmitMovprfx(ins, targetReg, op1Reg);`

Which would essentially check if `ins` is `RMW`, and then that `targetReg != op1Reg`.

I'm happy to not do that because I suspect it'll be more complicated than that

**Review by AndyAyersMS — APPROVED** [review]

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp (hunk 1 above)
Comment (dhartglassMSFT) [reply src/coreclr/jit/hwintrinsiccodegenarm64.cpp:478]: Thanks.  You're right that this logic should be abstracted out.

May I ask you or ylpoonlg to do this as part of the upcoming movprfx part2 change?  I don't know whether Long has needed to duplicate this check again in that PR, but it seems likely as hes touching this area anyway
