### PR TITLE
Fix JIT debugger notification location

### LINKED ISSUE #53508: COR_E_EXECUTIONENGINE when debugging any managed code
## Repro Steps

Regression on a daily runtime build 

1. Checkout https://github.com/dotnet/winforms/commit/7c212247eb7757187612b5340b5d075fe43654e9 (the previous working commit)

2. `.\start-vs.cmd`

3. Set “WinformsControlsTest” as the start project

4. F5 and observe the project running

5. Close VS

6. Checkout https://github.com/dotnet/winforms/commit/542c6129652d47aa4f1b726208c8fe068f264973 (the problematic commit)

7. `.\start-vs.cmd`

8. Set “WinformsControlsTest” as the start project

9. F5 and observe the immediate crash:

```
The program '[20668] WinformsControlsTest.exe: Program Trace' has exited with code 0 (0x0).
The program '[20668] WinformsControlsTest.exe' has exited with code -2146233082 (0x80131506).
```

## Notes

The app can be executed from cli just fine though, so it is VS / .NET Runtime/SDK issue.

To verify:

1. Checkout https://github.com/dotnet/winforms/commit/542c6129652d47aa4f1b726208c8fe068f264973 (the problematic commit)

2. `.\start-code.cmd`

3. From console in VS Code run the following:
```
.\build.cmd
pushd .\artifacts\bin\WinformsControlsTest\Debug\net6.0
WinformsControlsTest.exe
```

### PR DESCRIPTION
**Pull request by janvorli**
My recent change to enable jitting into a scratch buffer has broken
debugging due to the notification to debugger being sent too early. This
change moves the notification after the call to WriteCode and also
removes the CallCompileMethodWithSEHWrapper completely, since its only
purpose was to call the notification in PAL_FINALLY and only when the
JITting succeeded.

Close #53508

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @tommcdon

**Comment by stephentoub** [comment]
Thanks for the quick fix.

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -13355,6 +13277,29 @@ PCODE UnsafeJitFunction(PrepareCodeConfig* config,
...
+                //
+                if (g_pDebugInterface)
+                {
+                    if (!jitInfo.JitAgain())
+                    {
+                        g_pDebugInterface->JITComplete(nativeCodeVersion, (TADDR)nativeEntry);
+                    }
+                }
+            }
+#endif // DEBUGGING_SUPPORTED && !CROSSGEN_COMPILE
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:13302]:
```suggestion
#endif // DEBUGGING_SUPPORTED
```

**Review by jkotas — APPROVED** [review]
Thanks

**Review by hoyosjs — APPROVED** [review]

**Comment by eerhardt** [comment]
@janvorli - any chance this also fixes https://github.com/dotnet/runtime/issues/53448? I see the error codes are the same - `0x80131506`

**Comment by hoyosjs** [comment]
> @janvorli - any chance this also fixes https://github.com/dotnet/runtime/issues/53448? I see the error codes are the same - `0x80131506`

This would affect all apps, trimmed or not, if a method gets jitted while the debugger is attached. So yeah, it's likely this.
