### PR TITLE
Check return types in isCompatibleMethodGDV

### LINKED ISSUE #117867: Parameter Count Mismatch:  when using a Delegate during an async / await call via a lambda expression
### Description

I'm seeing a parameter count mismatch exception from a System.Reflection usage of a Delegate - which is declared via a lambda expression:

    public static class DialogEventHandlers
    {
        /// <summary>
        /// Delegate for updating dialog progress. The parameters translate into the view model for the LoadingView.
        /// </summary>
        public delegate void DialogProgressHandler(int taskCount, int tasksComplete, int tasksError, string message);
    }

            await viewModelController.Initialize((taskCount, tasksComplete, tasksError, message) =>
            {
                  // Code to call the Application Dispatcher was removed until this bug gets fixed.
            });

The delegate "DialogProgressHandler" is passed through a tree of tasks, each using it and invoking it with the primitive arguments (thread safe) seen above. The fact that the instance of this delegate was produced using a lambda came to mind as there may be Task issues associated with sharing a delegate. However, it didn't seem to matter for other uses of the same TPL pattern.

The bug is seen when calling the handler - but not right away:

            var artistCount = artistEntities.Count();
            var artistIndex = 0;

            // Load the album collection
            foreach (var artist in artistEntities.OrderBy(x => x.Name))
            {
                // Progress Update
                progressHandler.Invoke(artistCount, ++artistIndex, 0, "Loading Artists...");
            }

The foreach loop above will execute several (hundred) times. After some (delayed execution) time, the exception is thrown without any explanation - already having (successfully??) called the delegate(!!!) Imagine that the below code (where execution calls back the UI) will run - except for some other delayed invoke(?!)

            // (see DialogEventHandlers.cs)
            await viewModelController.Initialize((taskCount, tasksComplete, tasksError, message) =>
            {
                // This code will execute properly; and even without the dispatcher invoke here - which
                // also executes properly.
                ApplicationHelpers.InvokeDispatcher(() =>
                {
                    dialogViewModel.Progress = tasksComplete / (double)taskCount;
                    dialogViewModel.Message = message;

                }, DispatcherPriority.Background);
            });

Here is the Exception Stack:

   at System.Reflection.MethodBaseInvoker.ThrowTargetParameterCountException() in System.Reflection\MethodBaseInvoker.cs:line 76
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Reflection\RuntimeMethodInfo.cs:line 567
   at System.Delegate.DynamicInvokeImpl(Object[] args) in System\Delegate.cs:line 55
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Threading\ExecutionContext.cs:line 138
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Threading\ExecutionContext.cs:line 153
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at AudioStation.App.Main()

### Reproduction Steps

(seen above)

### Expected behavior

Handler should run synchronously - which it does - until some other unknown behavior in the .NET framework causes this exception.

### Actual behavior

Parameter count mismatch is thrown.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by EgorBo**
I've hacked a stress mode for GDV delegate inlining and found an issue that we don't validate return types.

Might fix https://github.com/dotnet/runtime/issues/117867

### CODE REVIEW

**Comment by jakobbotsch** [comment]
> Might fix #117867

That seems unlikely, this check should never fail with dynamic PGO, only with potentially outdated static PGO.

**Comment by EgorBo** [comment]
> > Might fix #117867
> 
> That seems unlikely, this check should never fail with dynamic PGO, only with potentially outdated static PGO.

Yeah, but I think even for Dynamic PGO we should be resilient there (I know there is a debug assert there, but who knows).

**Comment by EgorBo** [comment]
Still, the issue might be the Static PGO? The one that we ship BCL with,.

**Comment by jakobbotsch** [comment]
> I've hacked a stress mode for GDV delegate inlining and found an issue that we don't validate return types.

How did this issue surface? The point of the check is just to ensure that the JIT does not blow up. If the signatures don't match then the guard will never pass at runtime, so I don't think it would ever result in bad codegen.

**Comment by EgorBo** [comment]
> > I've hacked a stress mode for GDV delegate inlining and found an issue that we don't validate return types.
> 
> How did this issue surface? The point of the check is just to ensure that the JIT does not blow up. If the signatures don't match then the guard will never pass at runtime, so I don't think it would ever result in bad codegen.

Makes sense, but in my case it just threw a bunch of JIT asserts here and there

**Comment by EgorBo** [comment]
Does it look good? @jakobbotsch cc @dotnet/jit-contrib

File: src/coreclr/jit/importercalls.cpp [hunk 1]
```diff
@@ -7202,6 +7202,38 @@ bool Compiler::isCompatibleMethodGDV(GenTreeCall* call, CORINFO_METHOD_HANDLE gd
...
     unsigned                numArgs   = 0;
+
+    var_types gdvType  = JITtype2varType(sig.retType);
+    var_types callType = call->gtReturnType;
+
+    // Bail if return types do not match.
+    if (!impCheckImplicitArgumentCoercion(gdvType, callType) ||
+        // We should rely only on impCheckImplicitArgumentCoercion here, but the following check
+        // conservatively disables some cases that we don't handle well today (e.g. DOUBLE<->FLOAT).
+        (genActualType(gdvType) != genActualType(callType)))
```
Comment (jakobbotsch) [inline src/coreclr/jit/importercalls.cpp]: Is `call->gtReturnType` normalized for SIMD types or is it `TYP_STRUCT`? I don't quite recall. Can you verify this check doesn't filter out delegates returning SIMD types?

File: src/coreclr/jit/importercalls.cpp [hunk 2]
```diff
@@ -7202,6 +7202,38 @@ bool Compiler::isCompatibleMethodGDV(GenTreeCall* call, CORINFO_METHOD_HANDLE gd
...
+    {
+        JITDUMP("Incompatible method GDV: Return types do not match - bail out.\n");
+        return false;
+    }
+    if (varTypeIsStruct(gdvType))
+    {
+        assert(varTypeIsStruct(callType));
+        CORINFO_SIG_INFO callSig;
+        info.compCompHnd->getMethodSig(call->gtCallMethHnd, &callSig);
```
Comment (jakobbotsch) [inline src/coreclr/jit/importercalls.cpp:7263]: Isn't this unnecessary? You can get the class handle from the call node.

File: src/coreclr/jit/importercalls.cpp [hunk 3]
```diff
@@ -7202,6 +7202,38 @@ bool Compiler::isCompatibleMethodGDV(GenTreeCall* call, CORINFO_METHOD_HANDLE gd
...
+
+        structPassingKind callRetKind;
+        structPassingKind gdvRetKind;
+        getReturnTypeForStruct(callSig.retTypeClass, call->GetUnmanagedCallConv(), &callRetKind);
```
Comment (jakobbotsch) [inline src/coreclr/jit/importercalls.cpp:7267]: Was this check necessary? I wouldn't expect the frontend to care this deeply about ABI during inlining. Maybe just validate that the callee and call node agree on whether a return buffer is present. (I want to remove this function in the near future.)

Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp:7267]: this was done mainly for retbuffer, otherwise I hit some assert expecting it to present

Comment (jakobbotsch) [reply src/coreclr/jit/importercalls.cpp:7267]: I think we can keep it, I can find an alternative once I remove the function.

File: src/coreclr/jit/importercalls.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp]: I've just checked - works normally:
```cs
static void Main(string[] args)
{
    for (int i = 0; i < 200; i++)
    {
        Test(() => Vector128.Create(42));
        Thread.Sleep(16);
    }
}

[MethodImpl(MethodImplOptions.NoInlining)]
static uint Test(Func<Vector128<int>> func) => 
    func().ExtractMostSignificantBits();
```

```asm
; Assembly listing for method Program:Test(System.Func`1[System.Runtime.Intrinsics.Vector128`1[int]]):uint (Tier1)
; Emitting BLENDED_CODE for generic X64 + VEX + EVEX on Windows
; Tier1 code
; optimized code
; rsp based frame
; partially interruptible
; 0 inlinees with PGO data; 1 single block inlinees; 0 inlinees without PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  5,  3   )     ref  ->  rax         class-hnd single-def <System.Func`1[System.Runtime.Intrinsics.Vector128`1[int]]>
;  V01 OutArgs      [V01    ] (  1,  1   )  struct (32) [rsp+0x00]  do-not-enreg[XS] addr-exposed "OutgoingArgSpace" <UNNAMED>
;  V02 tmp1         [V02,T01] (  3,  3   )  simd16  ->  [rsp+0x20]  do-not-enreg[HS] hidden-struct-arg "spilled call-like call argument"
;* V03 tmp2         [V03    ] (  0,  0   )     ref  ->  zero-ref    class-hnd "guarded devirt this exact temp" <Program+<>c>
;
; Lcl frame size = 56

G_M9792_IG01:  ;; offset=0x0000
       sub      rsp, 56
       mov      rax, rcx
						;; size=7 bbWeight=1 PerfScore 0.50
G_M9792_IG02:  ;; offset=0x0007
       mov      rdx, 0x7FFA8AA408A0      ; code for Program+<>c:<Main>b__0_0():System.Runtime.Intrinsics.Vector128`1[int]:this
       cmp      qword ptr [rax+0x18], rdx
       jne      SHORT G_M9792_IG06
						;; size=16 bbWeight=1 PerfScore 4.25
G_M9792_IG03:  ;; offset=0x0017
       vbroadcastss xmm0, dword ptr [reloc @RWD00]
       vmovaps  xmmword ptr [rsp+0x20], xmm0
						;; size=15 bbWeight=0.50 PerfScore 2.00
G_M9792_IG04:  ;; offset=0x0026
       vmovaps  xmm0, xmmword ptr [rsp+0x20]
       vmovmskps rax, xmm0
						;; size=10 bbWeight=1 PerfScore 5.00
G_M9792_IG05:  ;; offset=0x0030
       add      rsp, 56
       ret      
						;; size=5 bbWeight=1 PerfScore 1.25
G_M9792_IG06:  ;; offset=0x0035
       lea      rdx, [rsp+0x20]
       mov      rcx, gword ptr [rax+0x08]
       call     [rax+0x18]System.Func`1[System.Runtime.Intrinsics.Vector128`1[int]]:Invoke():System.Runtime.Intrinsics.Vector128`1[int]:this
       jmp      SHORT G_M9792_IG04
						;; size=14 bbWeight=0 PerfScore 0.00
RWD00  	dd	0000002Ah		; 5.88545e-44


; Total bytes of code 67,
```

File: src/coreclr/jit/importercalls.cpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp:7263]: Addressed

File: src/coreclr/jit/importercalls.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/importercalls.cpp]: @jakobbotsch I've changed the check to match what we have in the inliner (in its assert)

**Review by jakobbotsch — APPROVED** [review]

**Comment by EgorBo** [comment]
Reverted to getMethodSig because `call->gtRetClsHnd` is not set at that point (it's set in impFixupCallStructReturn which is called later). Since delegate devirtualization is a rare event, I guess it's not a big deal to call it here once again.
