### PR TITLE
Delete `GT_DYN_BLK`

### LINKED ISSUE #62014: Ordering issues with `DYN_BLK` nodes
The `ASG(DYN_BLK, IND)` representation makes it (almost) impossible, by design, to maintain the proper ordering.

Dynamic blocks are imported for two instructions: `cpblk` and `initblk`. It is the first one that has issues. The order in which the operands are pushed onto the stack (and thus the proper evaluation order for the resulting tree) is as follows:
```
push dst
push src
push size
```
Yet, we import the following code:
```cs
public static void CpBlk(void* dst, void* src, uint count)
{
    IL.Emit.Ldarg(0);
    IL.Emit.Ldarg(1);
    IL.Emit.Ldarg(2);
    IL.Emit.Cpblk();
}
```
As the following tree:
```scala
***** BB01
STMT00000 ( 0x000[E-] ... 0x004 )
               [000005] -A-XG-------              *  ASG       struct (copy)
               [000003] ---XG--N----              +--*  DYN_BLK   struct
               [000000] ------------              |  +--*  LCL_VAR   long   V00 arg0  // dst   
               [000002] ------------              |  \--*  LCL_VAR   int    V02 arg2  // size
               [000004] -------N----              \--*  IND       struct
               [000001] ------------                 \--*  LCL_VAR   long   V01 arg1  // src
```
The order of evaluation for `size` and `src` has been swapped.

This does not matter for locals of course, but let's see what happens if we change our example to something like:
```cs
public static void CpBlkSimpleSideEffects(void* dst, void** pSrc, long count)
{
    IL.Emit.Ldarg(0);
    IL.Emit.Ldarg(1);
    IL.Emit.Ldind_I();
    IL.Emit.Ldarg(2);
    IL.Emit.Conv_Ovf_U4();
    IL.Emit.Cpblk();
}
```
Actually - this sample ends up generating correct code! And the reason for this is the fact that `gtSetEvalOrder` swaps the assignment order, which it always does for LHS indirections with addresses represented by locals:
https://github.com/dotnet/runtime/blob/90773ac32a6ac44daa00f10eda80d51fc04290fb/src/coreclr/jit/gentree.cpp#L4350-L4355

So we end up with this threaded code, which has correct evaluation order:
```scala
N008 ( 16, 15) [000007] -A-XG---R---              *  ASG       struct (copy)
N007 (  9, 10) [000005] D--XG--N----              +--*  DYN_BLK   struct
N004 (  1,  1) [000000] ------------              |  +--*  LCL_VAR   long   V00 arg0         u:1 (last use)
N006 (  8,  9) [000004] ---X--------              |  \--*  CAST_ovfl int <- uint <- long
N005 (  1,  1) [000003] ------------              |     \--*  LCL_VAR   long   V02 arg2         u:1 (last use)
N003 (  6,  4) [000006] ---XG--N----              \--*  IND       struct
N002 (  3,  2) [000002] *--XG-------                 \--*  IND       long  
N001 (  1,  1) [000001] ------------                    \--*  LCL_VAR   long   V01 arg1         u:1 (last use)
```
Of course, things don't work out quite so well if we have a more complex expression for the destination address:
```scala
public static void CpBlkSideEffects(void** dst, void*[] src, long count)
{
    IL.Emit.Ldarg(0);
    IL.Emit.Ldind_I();
    IL.Emit.Ldarg(1);
    IL.Emit.Ldc_I4(0);
    IL.Emit.Ldelem_I();
    IL.Emit.Ldarg(2);
    IL.Emit.Conv_Ovf_U4();
    IL.Emit.Cpblk();
}
```
And this program happily throws `OverflowException`, while it should have thrown `IndexOutOfRangeException`:
```cs
int  dstSrc = 0;
int* dst    = &dstSrc;
var  src    = new void*[0];
CpBlkSideEffects((void**)&dst, src, long.MaxValue);
```

Fortunately:
1) This bug is only reproducible in pure IL, as the inliner will spill side-effecting arguments for `Unsafe.CopyBlock`.
2) It has been there for a very long time.
3) No one uses `cpblk`.

So we're in no rush to fix it (which, I suspect, would involve getting rid of `DYN_BLK` and importing `STORE_DYN_BLK` directly).

### PR DESCRIPTION
**Pull request by SingleAccretion**
The current representation for `GT_DYN_BLK` + `GT_ASG` is fundamentally not correct, as it is ordered `dst, size, src`, while the IL order is `dst, src, size`. This change does away with the `DYN_BLK`, instead importing `GT_STORE_SYN_BLK` directly and adding support for it in the frontend (the amount of which is minimal because the node is treated opaquely, a lot like the HWIntrinsic stores).

The current representation is still not "ideal", because it uses "fake" `IND(struct)` nodes for the source, that still generate non-null assertions. It would have been more true to the nature of the node to use `DYN_BLK` as the source, but that would mean we'd need a new `DYN_INIT_VAL` sort of node with the `Size()` member, and that would mean touching a lot of the common logic for block stores, for not very clear benefits. All in all, I felt it was not worth it, and the existing `GT_STORE_DYN_BLK` representation is "good enough" as-is.

Some minimal [diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1522729&view=ms.vss-build-web.run-extensions-tab) due to slightly different ordering and thus register allocation.

Fixes #62014.
Contributes to #62328.
Contributes to #10873.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
@BruceForstall want to review this one?

File: src/coreclr/jit/compiler.h [hunk 1]
```diff
@@ -11490,42 +11491,14 @@ class GenTreeVisitor
...
                 GenTree** op3Use = &dynBlock->gtDynamicSize;
 
-                if (TVisitor::UseExecutionOrder)
-                {
-                    if (dynBlock->IsReverseOp())
-                    {
-                        std::swap(op1Use, op2Use);
-                    }
-                }
-
```
Comment (BruceForstall) [inline src/coreclr/jit/compiler.h:11528]: Maybe I haven't seen it yet, but why get rid of the reverse ops option? Isn't that used to improve codegen if the order doesn't matter, so we can execute the heavier op first?

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -15274,33 +15209,16 @@ bool GenTree::DefinesLocal(Compiler* comp, GenTreeLclVarCommon** pLclVarTree, bo
...
         unsigned width    = blkNode->Size();
         // Do we care about whether this assigns the entire variable?
-        if (pIsEntire != nullptr && blkNode->OperIs(GT_DYN_BLK))
+        if (pIsEntire != nullptr && blkNode->OperIs(GT_STORE_DYN_BLK))
         {
-            GenTree* blockWidth = blkNode->AsDynBlk()->gtDynamicSize;
+            GenTree* blockWidth = blkNode->AsStoreDynBlk()->gtDynamicSize;
             if (blockWidth->IsCnsIntOrI())
             {
-                if (blockWidth->IsIconHandle())
```
Comment (BruceForstall) [inline src/coreclr/jit/gentree.cpp:15282]: Why is it safe to remove the cases: (1) where the int constant is actually a class handle (although this case seems very odd; why wouldn't we do this getClassSize when creating the DynBlk node in the first place?); (2) the zero-sized constant case that returns `false`? Maybe DefinesLocalAddr handles width==0?

**Review by BruceForstall — COMMENTED** [review]
The changes look good; I just have a few questions

File: src/coreclr/jit/importer.cpp [hunk 3]
```diff
@@ -16996,19 +16995,29 @@ void Compiler::impImportBlockCode(BasicBlock* block)
...
+
+                    op1  = new (this, GT_STORE_DYN_BLK) GenTreeStoreDynBlk(op1, op2, op3);
                     size = 0;
+
+                    if ((prefixFlags & PREFIX_VOLATILE) != 0)
+                    {
+                        op1->gtFlags |= GTF_BLK_VOLATILE;
+                    }
                 }
-                op1 = gtNewBlkOpNode(op1, op2, (prefixFlags & PREFIX_VOLATILE) != 0, false);
```
[the remark this answers is not in the document]
Comment (SingleAccretion) [reply src/coreclr/jit/importer.cpp:17011]: Yes. `gtBlockOpInit`:
1) Checks for self-assignment to not confuse liveness. Doesn't matter for `STORE_DYN_BLK` because any local possibly defined by it will be address-exposed.
2) Propagates side effects flags. `StoreDynBlk`'s constructor already does that.
3) Sets `GTF_BLK_VOLATILE`. We do it here manually.
4) Labels assignments to SIMD locals so that later we know not try to promote them (optional optimization). Doesn't matter for `STORE_DYN_BLK` because, as above, any locals possibly defined by it will be address-exposed and thus not subject for enregistration anyway.

File: src/coreclr/jit/importer.cpp [hunk 4]
```diff
@@ -16996,19 +16995,29 @@ void Compiler::impImportBlockCode(BasicBlock* block)
...
                 if (op3->IsCnsIntOrI())
                 {
                     size = (unsigned)op3->AsIntConCommon()->IconValue();
                     op1  = new (this, GT_BLK) GenTreeBlk(GT_BLK, TYP_STRUCT, op1, typGetBlkLayout(size));
+                    op1  = gtNewBlkOpNode(op1, op2, (prefixFlags & PREFIX_VOLATILE) != 0, false);
                 }
                 else
                 {
-                    op1  = new (this, GT_DYN_BLK) GenTreeDynBlk(op1, op3);
+                    if (!op2->IsIntegralConst(0))
```
[the remark this answers is not in the document]
Comment (SingleAccretion) [reply src/coreclr/jit/importer.cpp:17008]: > Looks like the existing gtNewBlkOpNode would also check varTypeIsStruct(op1) here; is that not necessary?

Yes. `gtNewBlkOpNode` expects the "LHS" `BLK/OBJ` for the `dst`, here `op1` will be the `TYP_I_IMPL/TYP_BYREF` address.

File: src/coreclr/jit/gentree.cpp (hunk 2 above)
Comment (SingleAccretion) [reply src/coreclr/jit/gentree.cpp:15282]: > (1) where the int constant is actually a class handle (although this case seems very odd; why wouldn't we do this getClassSize when creating the DynBlk node in the first place?)

Indeed, this is some rather odd code that looks like a leftover from the `COPYBLK` representation. `blockWidth` will always be the actual size, not a handle representing one (there is no code in the compiler that creates such a tree).

> Maybe DefinesLocalAddr handles width==0?

Yes, sort of. There's a comment in it:
```
// If we just adding a zero then we allow an IsEntire match against width
//  otherwise we change width to zero to disallow an IsEntire Match
```
But of course, it is not actually equivalent to returning `false` from `DefinesLocal` (it "just" sets `pIsEntire` to `false`). So what this actually does is harmonizes the behavior of `ASG(BLK<0>, ...)` and `STORE_DYN_BLK<0>` (one can notice how the `return false` is was under `if (GT_DYN_BLK)`).

That said, this is some half-dead code (what it does will not really matter because the local in question will be address-exposed) that is probably better left exactly as it was. I will push a change to bring back `return false`.

File: src/coreclr/jit/compiler.h (hunk 1 above)
Comment (SingleAccretion) [reply src/coreclr/jit/compiler.h:11528]: This was dead code - nothing sets `GTF_REVERSE_OPS` on a `STORE_DYN_BLK` node. `GTF_REVERSE_OPS` is only supported for (most) binary nodes and 2-operand `GenTreeMultiOp`s.

However, what did happen is that we reversed `ASG`s that would later turn into `STORE_DYN_BLK`s and now we don't. The handling could be added, but it would have to be "non-standard" because `STORE_DYN_BLK` is a tertiary operator, and I believe, based on the diffs for this change, that it would not be worth it at this point.

Side note: we could get all the 6 permutations of order "for free" if we changed `STORE_DYN_BLK` from a tertiary operator with `DynamicSize` as its member into two binary operators: `STORE_DYN_BLK(DstAddr, Data)` where `Data` would be `DYN_BLK(Addr, Size) | DYN_BLK_INIT_VAL(InitVal, Size)`, and also solve the problem with the "dummy" `IND struct` node. But as I note in the description it would be a larger change with quite a bit of churn to it.

**Comment by SingleAccretion** [comment]
There was a build break that prevented stress from running, I've pushed out a rebased change (no functional changes except fro the last commit).

@BruceForstall could you please retrigger the stress?

**Review by BruceForstall — APPROVED** [review]
LGTM (assuming tests pass)

Thanks for the answers to my questions, and great cleanup!
