### PR TITLE
Get rid of hardcoded sleep in tracing/runtimeeventsource/nativeruntimeeventsource

### LINKED ISSUE #68690: Test failure tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh
Run: [runtime-coreclr jitstress 20220427.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1741797&view=ms.vss-test-web.build-test-results-tab&runId=47084030&paneView=debug&resultId=110761)

Failed test:
```
coreclr Linux arm Checked zapdisable @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh

coreclr Linux arm64 Checked zapdisable @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh

```
**Error message:**
```
Unhandled exception. System.Exception: Condition 'listener.EventCount > 0' is not true
at Tracing.Tests.Common.Assert.True(String name, Boolean condition)
at Tracing.Tests.NativeRuntimeEventSourceTest.Main(String[] args)
/root/helix/work/workitem/e/tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh: line 396:  8731 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false nativeruntimeeventsource.dll ''
[Simple] ThreadID = 8731 ID = 200 Name = IncreaseMemoryPressure
TimeStamp: 4/28/2022 7:01:36 AM
LocalTime: 4/28/2022 7:01:39 AM
Difference: 00:00:02.7967207
Name = "BytesAllocated" Value = "2208"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 8731 ID = 70 Name = ThreadCreating
TimeStamp: 4/28/2022 7:01:36 AM
LocalTime: 4/28/2022 7:01:39 AM
Difference: 00:00:02.8911418
Name = "ID" Value = "197155056"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 8743 ID = 85 Name = ThreadCreated
TimeStamp: 4/28/2022 7:01:36 AM
LocalTime: 4/28/2022 7:01:39 AM
Difference: 00:00:02.8924231
Name = "ManagedThreadID" Value = "197155056"
Name = "AppDomainID" Value = "192675600"
Name = "Flags" Value = "0"
Name = "ManagedThreadIndex" Value = "4"
Name = "OSThreadID" Value = "8743"
Name = "ClrInstanceID" Value = "0"

[createdump] Gathering state for process 8731 corerun
[createdump] Crashing thread 0000221b signal 00000006
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.8731.dmp
[createdump] Written 99774464 bytes (24359 pages) to core file
[createdump] Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh
Expected: True
Actual:   False


Stack trace
   at tracing_runtimeeventsource._nativeruntimeeventsource_nativeruntimeeventsource_._nativeruntimeeventsource_nativeruntimeeventsource_sh()
```
Queued | OS | Arch | Pipeline
-- | -- | -- | --
2022-04-28T10:45:26.665Z | osx.1200.arm64.open | arm64 | [runtime-coreclr pgo   Checked-dynamicpgo](https://dev.azure.com/dnceng/public/_build/results?buildId=1741965&view=ms.vss-test-web.build-test-results-tab&runId=47088304&resultId=109936&paneView=debug)
2022-04-28T10:38:59.831Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr pgo   Checked-fullpgo_random_edge](https://dev.azure.com/dnceng/public/_build/results?buildId=1741965&view=ms.vss-test-web.build-test-results-tab&runId=47088268&resultId=106988&paneView=debug)
2022-04-28T10:10:29.059Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr pgo   Checked-fullpgo](https://dev.azure.com/dnceng/public/_build/results?buildId=1741965&view=ms.vss-test-web.build-test-results-tab&runId=47088118&resultId=106988&paneView=debug)
2022-04-28T06:44:51.718Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress   Checked-zapdisable](https://dev.azure.com/dnceng/public/_build/results?buildId=1741797&view=ms.vss-test-web.build-test-results-tab&runId=47084852&resultId=110685&paneView=debug)
2022-04-28T06:28:04.155Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress   Checked-zapdisable](https://dev.azure.com/dnceng/public/_build/results?buildId=1741797&view=ms.vss-test-web.build-test-results-tab&runId=47084030&resultId=110761&paneView=debug)

### LINKED ISSUE #70966: Test failure tracing\\runtimeeventsource\\nativeruntimeeventsource\\nativeruntimeeventsource.cmd
Run: [runtime-coreclr jitstress-isas-x86 20220618.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1832542&view=ms.vss-test-web.build-test-results-tab&runId=48487108&resultId=107041&paneView=debug)

Failed test:
```
coreclr windows x86 Checked jitstress_isas_1_x86_nosse2 @ Windows.10.Amd64.Open

- tracing\\runtimeeventsource\\nativeruntimeeventsource\\nativeruntimeeventsource.cmd

```
**Error message:**
```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
at Tracing.Tests.NativeRuntimeEventSourceTest.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A9D3098C\w\C6B10ADC\uploads\Reports\tracing.runtimeeventsource\nativeruntimeeventsource\nativeruntimeeventsource.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A9D3098C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  nativeruntimeeventsource.dll
DOOVERLAPPEDIO
[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:49 AM
Difference: 00:00:01.6342478
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "30.555555555555557"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9051356
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "22.916666666666668"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9054275
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "20.408163265306122"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9056008
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "22"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9057753
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "20"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9059585
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "21.568627450980394"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9061277
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "21.568627450980394"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9063118
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "21.568627450980394"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 200 Name = IncreaseMemoryPressure
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9063122
Name = "BytesAllocated" Value = "2176"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 8932 ID = 70 Name = ThreadCreating
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9154906
Name = "ID" Value = "139857664"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 6740 ID = 85 Name = ThreadCreated
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9382517
Name = "ManagedThreadID" Value = "139857664"
Name = "AppDomainID" Value = "49677472"
Name = "Flags" Value = "0"
Name = "ManagedThreadIndex" Value = "4"
Name = "OSThreadID" Value = "6740"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 6740 ID = 71 Name = ThreadRunning
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9392748
Name = "ID" Value = "139857664"
Name


Stack trace
   at tracing_runtimeeventsource._nativeruntimeeventsource_nativeruntimeeventsource_._nativeruntimeeventsource_nativeruntimeeventsource_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
No Kusto information.

### LINKED ISSUE #71331: [runtime-coreclr pgo] nativeruntimeeventsource test fails arm32 and x86
```
Unhandled exception. System.Exception: Condition 'Saw the ThreadPoolIOPack event' is not true
at Tracing.Tests.Common.Assert.True(String name, Boolean condition)
at Tracing.Tests.NativeRuntimeEventSourceTest.Main(String[] args)
```
Fails in various PRs, e.g.:
https://dev.azure.com/dnceng/public/_build/results?buildId=1843344&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=1832137&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=1840992&view=ms.vss-test-web.build-test-results-tab

### PR DESCRIPTION
**Pull request by davmason**
Fixes #71331

This test was failing because in some runs the event would take longer than 2 seconds to get all the way through the eventing pipeline.

### CODE REVIEW

**Review by EgorBo — APPROVED** [review]

File: src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs [hunk 1]
```diff
@@ -31,14 +32,19 @@ static int Main(string[] args)
...
                     GC.Collect(2, GCCollectionMode.Forced);
 
-                    // Wait for more events.
-                    Thread.Sleep(1000);
+                    Stopwatch sw = Stopwatch.StartNew();
+
+                    while (sw.Elapsed <= TimeSpan.FromMinutes(1))
+                    {
+                        Thread.Sleep(100);
+                        if (listener.SeenProvidersAndEvents.Contains("Microsoft-Windows-DotNETRuntime/EVENTID(65)"))
```
Comment (jakobbotsch) [inline src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs:43]: Does this mean that if someone adds proper "support" for this event and makes it named this will stop working and the loop will run for 1 minute?

Comment (aromaa) [inline src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs:43]: Might also want to guard these with lock to avoid race conditions. Contains can throw NRE on concurrent access and the foreach below IOE.

Comment (noahfalk) [inline src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs:43]: It appears that we don't expect to see the ThreadPoolIOPack event on non-windows platforms which would make the test spin for 1 minute waiting. We probably want a different loop exit condition in that case.

**Review by noahfalk — APPROVED** [review]
LGTM modulo comments

File: src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs (hunk 1 above)
Comment (davmason) [reply src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs]: Ah, good catch. I can change the condition so it breaks if it's Windows and we see the ThreadPack event, or if it's any other platform and we've seen any events.

Comment (davmason) [reply src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs]: Yes, but the support is in the TraceEvent nuget package so it will happen when someone purposefully updates the package, and the test will fail when that happens. It should be fairly obvious what the failure is

Comment (davmason) [reply src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs]: Thanks, switched to ConcurrentBag for ease of implementation.

Comment (davmason) [reply src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs]: Actually, almost none of what I said was accurate - I was assuming things. This test uses EventListener and does it all in proc, so it's actually fine and won't break in the future. The eventlistener formats the strings with the provider and event id.

**Comment by davmason** [comment]
Fixes https://github.com/dotnet/runtime/issues/70966

**Comment by davmason** [comment]
This fixes #70966 (unsafe multithreaded hashset access) and #68690 (we would occasionally see no events at all in GCStress/JITStress) as well.
