### PR TITLE
[NativeAOT] Initialize COM before initializing FLS slot.

### LINKED ISSUE #113040: [Native AOT] Initialize COM eagerly
Port the COM initialization changes implemented in https://github.com/dotnet/runtime/pull/112809 to native AOT.

Native AOT is susceptible to the ordering problem between .NET and COM FLS callbacks that were addressed by initializing COM eagerly. (I am on an email thread where a real world UWP app crashed due to this problem.)

cc @VSadov

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #113040

Order FLS slot initialization after ensuring that COM is initialized. This is to ensure that deinitialization of COM happen before detachment of a thread - as COM deinitialization may want to run managed code.

### CODE REVIEW

File: src/coreclr/nativeaot/Runtime/threadstore.cpp [hunk 1]
```diff
@@ -110,9 +110,16 @@ void ThreadStore::AttachCurrentThread(bool fAcquireThreadStoreLock)
     // we want to avoid at construction time because the loader lock is held then.
     Thread * pAttachingThread = RawGetCurrentThread();
 
-    // The thread was already initialized, so it is already attached
+    if (pAttachingThread->IsDetached())
+    {
+        ASSERT_UNCONDITIONALLY("The thread has been detached already");
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/threadstore.cpp:115]: Can we make the error message to be identical to the CoreCLR one? https://github.com/dotnet/runtime/pull/112809/files#diff-63935b2e5a324d25feff725f83200eaa716c69fdef7529d2bd3cfa35620105aeR1776

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/threadstore.cpp:115]: > Can we make the error message to be identical to the CoreCLR one?

Yes, we can do that. 

Technically, with this change, a NativeAOT thread will not have a "destroyed" state. There is "detached" when we can't run managed code any more and then there is "thread is gone, because native TLS is gone".  It seems we do not need a state in between and things gets simpler without it.  

For the purpose of error message the difference is too subtle though.

**Comment by VSadov** [comment]
I have confirmed that problematic scenario (running managed code on detached thread) is reachable on baseline NativeAOT SDK and that this fix prevents it.

Here is my repro:

```cs
using System.Collections;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace ConsoleApp57
{
    internal class Program
    {
        [DllImport("oleaut32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        private static extern int SetErrorInfo(uint dwReserved, IntPtr perrinfo);

        static void Main(string[] args)
        {
            Thread thr1 = new Thread(Test);
            thr1.Start();
            System.Console.ReadLine();
        }

        private static void Test()
        {
            var cw = new ComWrappersImpl();
            IntPtr iUnknown = cw.GetOrCreateComInterfaceForObject(new object(), CreateComInterfaceFlags.None);

            SetErrorInfo(0, iUnknown);

            System.Console.WriteLine(Marshal.Release(iUnknown));
        }
    }
}


public class ComWrappersImpl : ComWrappers
{
    public const string IID_IErrorInfo = "1CF2B120-547D-101B-8E65-08002B2BD119";

    protected unsafe override ComInterfaceEntry* ComputeVtables(object obj, CreateComInterfaceFlags flags, out int count)
    {
        IntPtr fpQueryInterface = default;
        IntPtr fpAddRef = default;
        IntPtr fpRelease = default;
        ComWrappers.GetIUnknownImpl(out fpQueryInterface, out fpAddRef, out fpRelease);

        var vtblRaw = (IntPtr*)RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(ComWrappersImpl), IntPtr.Size * 3);
        vtblRaw[0] = fpQueryInterface;
        vtblRaw[1] = fpAddRef;
        vtblRaw[2] = fpRelease;

        var entryRaw = (ComInterfaceEntry*)RuntimeHelpers.AllocateTypeAssociatedMemory(typeof(ComWrappersImpl), sizeof(ComInterfaceEntry));
        entryRaw->IID = new Guid(IID_IErrorInfo);
        entryRaw->Vtable = (IntPtr)vtblRaw;

        count = 1;
        return entryRaw;
    }

    protected override object CreateObject(IntPtr externalComObject, CreateObjectFlags flag)
        => throw new NotImplementedException();

    protected override void ReleaseObjects(IEnumerable objects)
        => throw new NotImplementedException();
}
```

If I run this compiled with baseline SDK, COM FLS callback fires after ours and runs managed `S_P_CoreLib_System_Runtime_InteropServices_ComWrappers__IUnknown_Release` on a detached thread. That typically does not cause problems by itself, since the default `Release` just decrements a counter and does not touch GC. I can imagine worse outcomes if GC is touched - like if something is allocated.

In this PR we are introducing a FailFast to catch such scenario and deterministically fail.

If I run same code with current PR, but with the call to `CoInitialize` removed, I get (as expected) a FailFast crash:

```
[0x0]   ntdll!NtRaiseException+0x14   0xcc5cff058   0x7ffaa2944182   
[0x1]   KERNELBASE!RaiseFailFastException+0x152   0xcc5cff060   0x7ff7446e8c1c   
[0x2]   ConsoleApp57!ThreadStore::AttachCurrentThread+0x36   (Inline Function)   (Inline Function)   
[0x3]   ConsoleApp57!ThreadStore::AttachCurrentThread+0x3c   0xcc5cff640   0x7ff7446e4e26   
[0x4]   ConsoleApp57!Thread::ReversePInvokeAttachOrTrapThread+0x85   (Inline Function)   (Inline Function)   
[0x5]   ConsoleApp57!RhpReversePInvokeAttachOrTrapThread2+0x96   0xcc5cff670   0x7ff7446b1b52   
[0x6]   ConsoleApp57!S_P_CoreLib_System_Runtime_InteropServices_ComWrappers__IUnknown_Release+0x12   0xcc5cff6a0   0x7ffaa3b4ae08   
[0x7]   combase!Microsoft::WRL::ComPtr<IUnknown>::InternalRelease+0x1e3   (Inline Function)   (Inline Function)   
[0x8]   combase!Microsoft::WRL::ComPtr<IUnknown>::{dtor}+0x1e3   (Inline Function)   (Inline Function)   
[0x9]   combase!TlsClearErrorInfo+0x22b   (Inline Function)   (Inline Function)   
[0xa]   combase!CoSetErrorInfo+0x244   (Inline Function)   (Inline Function)   
[0xb]   combase!wCoUninitialize+0x280   0xcc5cff6e0   0x7ffaa3b4b764   
[0xc]   combase!CoUninitialize+0x104   0xcc5cff750   0x7ffaa3b7a833   
[0xd]   combase!DoThreadSpecificCleanup+0x6b   0xcc5cff840   0x7ffaa3b7a769   
[0xe]   combase!FlsThreadCleanupCallback+0x29   0xcc5cff870   0x7ffaa4baf3a5   
[0xf]   ntdll!RtlpFlsDataCleanup+0x121   0xcc5cff8a0   0x7ffaa4b67498   
[0x10]   ntdll!LdrShutdownThread+0x48   0xcc5cff8e0   0x7ffaa4b9ec6e   
[0x11]   ntdll!RtlExitUserThread+0x3e   0xcc5cff9e0   0x7ffaa4a5737d   
[0x12]   KERNEL32!BaseThreadInitThunk+0x1d   0xcc5cffa20   0x7ffaa4b9cc91   
[0x13]   ntdll!RtlUserThreadStart+0x21   0xcc5cffa50   0x0   
```

And if I run the repro sample with complete fix, I see no crash. 

With the complete fix COM calls the Release while the thread is still attached and has no problems with running managed code.

**Review by jkotas — APPROVED** [review]
LGTM. Thank you!

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 2]
```diff
@@ -53,15 +53,49 @@ static uint32_t g_flsIndex = FLS_OUT_OF_INDEXES;
...
+    CoInitializeEx(NULL, COINIT_MULTITHREADED);
+
+    // We use fiber detach callbacks to run our thread shutdown code because the fiber detach
+    // callback is made without the OS loader lock
+    g_flsIndex = FlsAlloc(FiberDetachCallback);
+    if (g_flsIndex == FLS_OUT_OF_INDEXES)
     {
-        // The current fiber is the home fiber of a thread, so the thread is shutting down
-        RuntimeThreadShutdown(lpFlsData);
+        ASSERT_UNCONDITIONALLY("Could not allocate an FLS slot.");
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:74]: Would it be better to return false from the runtime init method when this happens?

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:74]: > Would it be better to return false from the runtime init method when this happens?

We cannot handle a failure to initialize FLS slot, so we have to bail one way or another. 
But, yes, we could handle this failure the same way as an OOM on init path - no failfast, just return from `InitializeGC` with a failure/false.

File: src/coreclr/nativeaot/Runtime/FinalizerHelpers.cpp [hunk 3]
```diff
@@ -29,14 +29,25 @@ CLREventStatic g_FinalizerDoneEvent;
...
-// Unmanaged front-end to the finalizer thread. We require this because at the point the GC creates the
-// finalizer thread we can't run managed code. Instead this method waits
+// Unmanaged front-end to the finalizer thread. We require this because at the point when this thread is
+// created we can't run managed code. Instead this method waits
 // for the first finalization request (by which time everything must be up and running) and kicks off the
 // managed portion of the thread at that point
 uint32_t WINAPI FinalizerStart(void* pContext)
 {
+#ifdef TARGET_WINDOWS
+    g_FlsInitSucceeded = PalInitComAndFlsSlot();
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/FinalizerHelpers.cpp:45]: Do we need to exit the finalizer thread when this fails? Otherwise, we call `ThreadStore::AttachCurrentThread` below that is going to call `FlsSetValue` on uninitialized `g_flsIndex` and things will just go bad from there.

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 4]
```diff
@@ -53,13 +53,45 @@ static uint32_t g_flsIndex = FLS_OUT_OF_INDEXES;
...
+    RuntimeThreadShutdown(lpFlsData);
+}
+
+REDHAWK_PALEXPORT bool REDHAWK_PALAPI PalInitComAndFlsSlot()
+{
+    ASSERT(g_flsIndex == FLS_OUT_OF_INDEXES);
+
+    // Making finalizer thread MTA early ensures that COM is initialized before we initialize our thread
+    // termination callback.
+    CoInitializeEx(NULL, COINIT_MULTITHREADED);
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:69]: We can check for bad HRESULT from CoInitializeEx as well.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:69]: Can COM be somehow unavailable to the app? Like turned off for the platform or the app? 

I think in such case we'd want to ignore a failure and continue, since we do not actually require that init succeeded, just want to be sure it succeeds early enough.

Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:69]: COM is part of Windows. Windows without COM is not a thing.

The current COM init logic propagates the errors from CoInitialize: 
https://github.com/dotnet/runtime/blob/88494801cdf4ddb496e78bf4d9165fe7f9273206/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs#L320-L335

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 5]
```diff
@@ -53,13 +53,45 @@ static uint32_t g_flsIndex = FLS_OUT_OF_INDEXES;
...
+    RuntimeThreadShutdown(lpFlsData);
+}
+
+REDHAWK_PALEXPORT bool REDHAWK_PALAPI PalInitComAndFlsSlot()
+{
+    ASSERT(g_flsIndex == FLS_OUT_OF_INDEXES);
+
+    // Making finalizer thread MTA early ensures that COM is initialized before we initialize our thread
+    // termination callback.
+    HRESULT hr = CoInitializeEx(NULL, COINIT_MULTITHREADED);
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:69]:
```suggestion
    HRESULT hr = CoInitializeEx(NULL, COINIT_MULTITHREADED);
    if (FAILED(hr))
        return false;
```

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 6]
```diff
@@ -53,13 +53,45 @@ static uint32_t g_flsIndex = FLS_OUT_OF_INDEXES;
...
+
+    // We use fiber detach callbacks to run our thread shutdown code because the fiber detach
+    // callback is made without the OS loader lock
+    g_flsIndex = FlsAlloc(FiberDetachCallback);
+    return SUCCEEDED(hr) && g_flsIndex != FLS_OUT_OF_INDEXES;
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:74]:
```suggestion
    return g_flsIndex != FLS_OUT_OF_INDEXES;
```

**Review by jkotas — APPROVED** [review]
