### PR TITLE
Fix interleaved heap RW commit failure handling

### LINKED ISSUE #71624: Test failure GC\\LargeMemory\\API\\gc\\keepalive\\keepalive.cmd
Run: [runtime-coreclr outerloop 20220704.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1860208&view=ms.vss-test-web.build-test-results-tab&runId=48881550&resultId=106188&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- GC\\LargeMemory\\API\\gc\\keepalive\\keepalive.cmd
- GC\\LargeMemory\\API\\gc\\suppressfinalize\\suppressfinalize.cmd
- GC\\LargeMemory\\Allocation\\largeexceptiontest\\largeexceptiontest.cmd
- GC\\LargeMemory\\API\\gc\\gettotalmemory\\gettotalmemory.cmd
```
**Error message:**
```
Assert failure(PID 4576 [0x000011e0], Thread: 10792 [0x2a28]): Consistency check failed: AV in clr at this callstack:
CORECLR! Precode::Init + 0x68 (0x00007fff85a92208) CORECLR! Precode::AllocateTemporaryEntryPoints + 0x230 (0x00007fff85a91d78)
CORECLR! MethodDescChunk::CreateTemporaryEntryPoints + 0x4C (0x00007fff85a5fd04) CORECLR! MethodTableBuilder::SetupMethodTable2 + 0x12AC (0x00007fff85bc2d74)
CORECLR! MethodTableBuilder::BuildMethodTableThrowing + 0x1508 (0x00007fff85ba99a0) CORECLR! ClassLoader::CreateTypeHandleForTypeDefThrowing + 0xBCC (0x00007fff85bae1cc)
CORECLR! ClassLoader::CreateTypeHandleForTypeKey + 0xCC (0x00007fff859d734c) CORECLR! ClassLoader::DoIncrementalLoad + 0x214 (0x00007fff859d7c24)
CORECLR! ClasagedThreadBase_DispatchOuter'::11'::_ + 0xAC8 (0x00007fff859dc328)
CORECLR! ClassLoader::LoadTypeHandleForTypeKey + 0x154 (0x00007fff859db5dc) CORECLR! ClassLoader::LoadTypeDefThrowing + 0x4CC (0x00007fff859db324)
CORECLR! ClassLoader::LoadTypeDefOrRefThrowing + 0x3D8 (0x00007fff859dadb8) CORECLR! SigPointer::GetTypeHandleThrowing + 0x11B8 (0x00007fff85aac060)
CORECLR! ZapSig::DecodeType + 0x6C (0x00007fff85afd6f4) CORECLR! LoadDynamicInfoEntry + 0x1FFC (0x00007fff85a3bbf4)
CORECLR! Module::FixupNativeEntry + 0x64 (0x00007fff859be874) CORECLR! Module::FixupDelayListAux<Module *,int (__cdecl Module::*)(READYTORUN_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x204 (0x00007fff85afe5b4)
CORECLR! ReadyToRunInfo::GetEntryPoint + 0x2F0 (0x00007fff85b003c8) CORECLR! MethodDesc::GetPrecompiledR2RCode + 0x48 (0x00007fff85a97570)
.AV on tid=0x2a28 (10792), cxr=0000005804D760E0, exr=0000005804D76470
FAILED: false
File: D:\a_work\1\s\src\coreclr\vm\excep.cpp Line: 7178
Image: D:\h\w\AA7B0947\p\corerun.exe

Assert failure(PID 4576 [0x000011e0], Thread: 14088 [0x3708]): Consistency check failed: AV in clr at this callstack:
CORECLR! Precode::Init + 0x68 (0x00007fff85a92208) CORECLR! Precode::Allocate + 0x158 (0x00007fff85a91988)
CORECLR! CallCountingManager::SetCodeEntryPoint + 0x998 (0x00007fff859b8198) CORECLR! TieredCompilationManager::TryDeactivateTieringDelay + 0x408 (0x00007fff85ad4b10)
CORECLR! TieredCompilationManager::BackgroundWorkerStart + 0x128 (0x00007fff85ad3118) CORECLR! TieredCompilationManager::BackgroundWorkerBootstrapper1 + 0x2C (0x00007fff85ad2fdc)
CORECLR! ManagedThreadBase_DispatchMiddle + 0x128 (0x00007fff85acb380) CORECLR!ManagedThreadBase_DispatchOuter'::11'::__Body::Run + 0x24 (0x00007fff85accf9c)
CORECLR! ManagedThreadBase_DispatchOuter + 0xB4 (0x00007fff85acb464) CORECLR! ManagedThreadBase::KickOff + 0x1C (0x00007fff85acafcc)
CORECLR! TieredCompilationManager::BackgroundWorkerBootstrapper0 + 0x110 (0x00007fff85ad2f80) KERNEL32! BaseThreadInitThunk + 0x34 (0x00007fffc0d5cc64)
NTDLL! RtlUserThreadStart + 0x44 (0x00007fff`c1a0b1f4)
.AV on tid=0x3708 (14088), cxr=00000058057FECD0, exr=00000058057FF060
FAILED: false

CORECLR! CHECK::Trigger + 0x1E0 (0x00007fff85d5a2c0) CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x218 (0x00007fff85a00ea8)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x64 (0x00007fff85a00a6c) CORECLR! CLRVectoredExceptionHandler + 0x1B8 (0x00007fff85a009e8)
CORECLR! CLRVectoredExceptionHandlerShim + 0x248 (0x00007fff85a011b8) NTDLL! RtlGetSaclSecurityDescriptor + 0x180 (0x00007fffc1a0c700)
NTDLL! LdrControlFlowGuardEnforced + 0x6D4 (0x00007fffc1a45df4) NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007fffc19e3434)
CORECLR! Precode::Init + 0x68 (0x00007fff85a92208) CORECLR! Precode::Allocate + 0x158 (0x00007fff85a91988)
File: D:\a_work\1\s\src\coreclr\vm\excep.cpp Line: 7178
Image: D:\h\w\AA7B0947\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\AA7B0947\w\A0D508BB\uploads\Reports\GC.LargeMemory\API\gc\keepalive\keepalive.output.txt
Raw output:
BEGIN EXECUTION
keepalive.dll
largeobject.dll
memcheck.d


Stack trace
   at GC_LargeMemory._API_gc_keepalive_keepalive_._API_gc_keepalive_keepalive_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by janvorli**
We were not checking the result of the `ExecutableAllocator::Commit` call
for mapping the RW page in the case of interleaved heaps. I've seen a
failure in the CI that seems to be caused by this - when we succeeded
committing the RX page, but failed to commit the related RW page, we
have then crashed when trying to initialize the precode stubs data.

This change adds the check to fix the problem. This causes the
`LoaderHeap` allocation to fail as expected in such case.

Close #71624

### CODE REVIEW

File: src/coreclr/utilcode/loaderheap.cpp [hunk 1]
```diff
@@ -1304,14 +1304,17 @@ BOOL UnlockedLoaderHeap::GetMoreCommittedPages(size_t dwMinSize)
         void *pData = ExecutableAllocator::Instance()->Commit(m_pPtrToEndOfCommittedRegion, dwSizeToCommitPart, IsExecutable());
         if (pData == NULL)
         {
-            _ASSERTE(!"Unable to commit a loaderheap page");
```
Comment (janvorli) [inline src/coreclr/utilcode/loaderheap.cpp:1307]: I have removed this assert since I've noticed the same CI test that uncovered the issue has failed due to this assert in another run. We should just return FALSE and let the caller handle the memory allocation failure.

Comment (jakobbotsch) [reply src/coreclr/utilcode/loaderheap.cpp:1307]: I've seen this assert occasionally on macOS-arm64 Fuzzlyn runs but have not had time to create a repro case. When would we expect this to occur? In low memory situations or for other reasons too?

Comment (janvorli) [reply src/coreclr/utilcode/loaderheap.cpp:1307]: In low memory situation only.

**Comment by janvorli** [comment]
The only failure in the CI tests is the known GetGCMemoryInfo failure on arm32.

**Comment by mangod9** [comment]
> The only failure in the CI tests is the known GetGCMemoryInfo failure on arm32.

believe a change which might have caused this failure was reverted which should have avoided the failure. Perhaps your CI didnt pickup that change?

**Review by mangod9 — APPROVED** [review]

**Comment by janvorli** [comment]
> Perhaps your CI didnt pickup that change?

I think it didn't. I would have to close and reopen the PR to pick the latest changes in main. Since it was the only issue in the CI and it was known, I would just merge this. I was just waiting for an approval.
