### PR TITLE
Fix x64 macOS and Linux managed debugging

### LINKED ISSUE #84466: [NETSDKE2E] With .NET 8.0 Preview4, debugging does not work normally on Mac X64
### Description

With .NET 8.0 Preview4, debugging does not work normally on Mac X64

### Reproduction Steps

1.VSCode: Install version 1.77.1:https://code.visualstudio.com/download
2.Install C# extension 1.25.5 : https://github.com/OmniSharp/omnisharp-vscode/releases/
3.Install SDK:.NET 8.0.100-preview.4.23205.4 (runtime- 8.0.0-preview.4.23181.2):[GitHub - dotnet/installer: .NET SDK Installer](https://github.com/dotnet/installer)
4.Create a new project via CLI (For example: Console).
5.Open the project in VSCode and hit F5.

dotnet --info:
MicrosoftTeams-image (2)

### Expected behavior

Debugging works fine and see "Hello,World!"
MicrosoftTeams-image3

### Actual behavior

Debugging could not be finished normally, could not see "Hello, World!"
MicrosoftTeams-image (1)

### Regression?

Yes. This issue is not repro with .NET 8 Preview3, Preview2

### Known Workarounds

_No response_

### Configuration

Version: .NET 8.0.100-preview.4.23205.4 (runtime- 8.0.0-preview.4.23181.2)
OS: Big Sur(11.7.5), Ventura(13.3)
Architecture: Mac X64
This issue is only repro on Mac X64, not repro on Mac M1 and Windows.

### Other information

-->The OmniSharp Log:
[OmniSharpLog.txt](https://github.com/dotnet/runtime/files/11175425/OmniSharpLog.txt)

### PR DESCRIPTION
**Pull request by tommcdon**
A recent change to T_CONTEXT size breaks managed debugging.  This addresses the necessary debugger API's to unblock managed debugging.

Fixes #84466

### CODE REVIEW

**Comment by tannergooding** [comment]
This was probably caused by my thread suspend/restore changes, sorry!

Is there anything we can do to catch such breaks in the future?

**Comment by tommcdon** [comment]
Hi @tannergooding!   No worries!  We have tests in the dotnet/diagnostics repo that would catch this issue but there were unrelated problems that was preventing a runtime update.  Our plan/thinking to address this in the future is to add some static asserts to the code that would at least alert folks to the debugger's dependency on context sizes.

File: src/coreclr/debug/daccess/dacdbiimpl.cpp [hunk 1]
```diff
@@ -5199,7 +5199,7 @@ void DacDbiInterfaceImpl::Hijack(
     HRESULT hr = m_pTarget->GetThreadContext(
         dwThreadId,
         CONTEXT_FULL,
-        sizeof(ctx),
+        sizeof(DT_CONTEXT),
```
Comment (tommcdon) [inline src/coreclr/debug/daccess/dacdbiimpl.cpp:5202]: Is DacDbiInterfaceImpl::Hijack is Windows-only and if 'yes', is this change needed?

File: src/coreclr/debug/daccess/dacdbiimpl.cpp [hunk 2]
```diff
@@ -5346,7 +5346,7 @@ void DacDbiInterfaceImpl::Hijack(
     //
     // Commit the context.
     //
-    hr = m_pMutableTarget->SetThreadContext(dwThreadId, sizeof(ctx), reinterpret_cast<BYTE*> (&ctx));
+    hr = m_pMutableTarget->SetThreadContext(dwThreadId, sizeof(DT_CONTEXT), reinterpret_cast<BYTE*> (&ctx));
```
Comment (tommcdon) [inline src/coreclr/debug/daccess/dacdbiimpl.cpp:5349]: Same as above

File: src/coreclr/debug/daccess/dacdbiimpl.cpp [hunk 3]
```diff
@@ -5717,7 +5717,7 @@ void DacDbiInterfaceImpl::GetContext(VMPTR_Thread vmThread, DT_CONTEXT * pContex
         pContextBuffer->ContextFlags = DT_CONTEXT_ALL;
         HRESULT hr = m_pTarget->GetThreadContext(pThread->GetOSThreadId(),
                                                 pContextBuffer->ContextFlags,
-                                                sizeof(*pContextBuffer),
+                                                sizeof(DT_CONTEXT),
```
Comment (tommcdon) [inline src/coreclr/debug/daccess/dacdbiimpl.cpp:5720]: Is this change for clarity? I believe sizeof(*pContextBuffer) is already DT_CONTEXT

**Review by tommcdon — COMMENTED** [review]
I left a few comments for your consideration otherwise the changes look good to me!  I would approve the PR but I am unable to as I am the owner of it :).

File: src/coreclr/debug/daccess/dacdbiimpl.cpp (hunk 3 above)
Comment (mikem8361) [reply src/coreclr/debug/daccess/dacdbiimpl.cpp:5720]: All of these sizeof(DT_CONTEXT) changes are to make it clearer than we always (even on Windows where the T_CONTEXT/DT_CONTEXT are the same size) pass the size of the original context (DT_CONTEXT).

**Review by mikem8361 — APPROVED** [review]
