### PR TITLE
Avoid long busy-waiting between hijack retries.

### LINKED ISSUE #102832: [Performance] Regression in multiple scenarios, Linux, more significant on ARM64
image

Windows is not impacted
NativeAOT is not impacted
Visible on x86, but even more on ARM64 with 28 cores, not visible when running with 80 cores on ARM64.

Minimal commits range: https://github.com/dotnet/runtime/compare/70375162014e...56d7e5d80ed6

Command lines to repro using Plaintext MVC on Ampere with 28 cores:

Latency ~ 0.9, RPS ~ 4.2M

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/azure.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario mvc --profile arm-lin-28-app --profile intel-load2-load --application.framework net9.0 --application.collectDependencies true --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.5.24256.2 --application.sdkVersion 9.0.100-preview.5.24267.1 --application.runtimeVersion 9.0.0-preview.5.24259.7
```

Latency ~ 1.3ms, RPS ~ 3.9M

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/azure.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario mvc --profile arm-lin-28-app --profile intel-load2-load --application.framework net9.0 --application.collectDependencies true --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.5.24256.2 --application.sdkVersion 9.0.100-preview.5.24267.1 --application.runtimeVersion 9.0.0-preview.5.24260.2
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: https://github.com/dotnet/runtime/issues/102832

- refactors the pause routine into `minipal_microdelay` - to have the same implementation for CoreCLR and NativeAOT
- use sub-millisecond sleep API, when available, for long(ish) pauses.
- couple minor fixes around sending suspension signals. 
(not responsible for the regression, just possible corner cases noticed while investigating)

### CODE REVIEW

File: src/native/minipal/time.c [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+        SleepEx(usecs / 1000, FALSE);
+        if (usecsSinceYield)
+        {
+            usecsSinceYield = 0;
+        }
+
+        return;
+    }
+#else
+    if (usecs > 10)
```
Comment (VSadov) [inline src/native/minipal/time.c:94]: This is the actual fix. When we need to pause for longer than 10 microseconds, we sleep instead, thus freeing compute resources to other threads (including ones that we want to suspend).

Comment (VSadov) [reply src/native/minipal/time.c:94]: `10` is a somewhat arbitrary number in the order of a context switch cost. (2-10 microseconds). 
We are not very sensitive to the exact value. It just means "if pausing for less, might be ok to spin-wait".

**Comment by VSadov** [comment]
Performance impact on Stage1 ASP.Net benchmark

========================================================   arm
```
======= before regression

| First Request (ms)      | 171        |
| Requests/sec            | 760,970    |
| Requests                | 11,490,582 |
| Mean latency (ms)       | 0.78       |
| Max latency (ms)        | 38.00      |


======== after regression

| First Request (ms)      | 164       |
| Requests/sec            | 627,518   |
| Requests                | 9,458,579 |
| Mean latency (ms)       | 1.65      |
| Max latency (ms)        | 54.40     |


======== after the fix

| First Request (ms)      | 160        |
| Requests/sec            | 770,416    |
| Requests                | 11,632,411 |
| Mean latency (ms)       | 0.78       |
| Max latency (ms)        | 40.54      |

```

======================================================= x64

```
======= before regression

| First Request (ms)      | 181        |
| Requests/sec            | 813,308    |
| Requests                | 12,280,780 |
| Mean latency (ms)       | 0.46       |
| Max latency (ms)        | 44.08      |

======== after regression

| First Request (ms)      | 179        |
| Requests/sec            | 771,124    |
| Requests                | 11,643,639 |
| Mean latency (ms)       | 0.56       |
| Max latency (ms)        | 43.84      |

======== after the fix

| Start Time (ms)         | 0          |
| First Request (ms)      | 185        |
| Requests/sec            | 803,472    |
| Requests                | 12,132,099 |
| Mean latency (ms)       | 0.44       |
| Max latency (ms)        | 36.27      |
```

commands used:

```
===================  arm64

crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario basicminimalapivanilla --profile arm-lin-28-app --profile amd-lin-load --profile amd-lin2-db --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.5.24256.2 --application.sdkVersion 9.0.100-preview.5.24267.1 --application.runtimeVersion 9.0.0-preview.5.24259.7


crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario basicminimalapivanilla --profile arm-lin-28-app --profile amd-lin-load --profile amd-lin2-db --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.5.24256.2 --application.sdkVersion 9.0.100-preview.5.24267.1 --application.runtimeVersion 9.0.0-preview.5.24260.2


crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario basicminimalapivanilla --profile arm-lin-28-app --profile amd-lin-load --profile amd-lin2-db --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.5.24256.2 --application.sdkVersion 9.0.100-preview.5.24267.1 --application.runtimeVersion 9.0.0-preview.5.24260.2   --application.options.outputFiles armFix\libcoreclr.so


=================== x64

crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario basicminimalapivanilla --profile intel-lin-app --profile intel-load-load --profile intel-db-db --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.5.24256.2 --application.sdkVersion 9.0.100-preview.5.24267.1 --application.runtimeVersion 9.0.0-preview.5.24259.7


crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario basicminimalapivanilla --profile intel-lin-app --profile intel-load-load --profile intel-db-db --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.5.24256.2 --application.sdkVersion 9.0.100-preview.5.24267.1 --application.runtimeVersion 9.0.0-preview.5.24260.2


crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario basicminimalapivanilla --profile intel-lin-app --profile intel-load-load --profile intel-db-db --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net9.0 --application.options.collectCounters true --load.options.reuseBuild true --application.aspNetCoreVersion 9.0.0-preview.5.24256.2 --application.sdkVersion 9.0.100-preview.5.24267.1 --application.runtimeVersion 9.0.0-preview.5.24260.2   --application.options.outputFiles x64Fix\libcoreclr.so

```

File: src/native/minipal/time.c (hunk 1 above)
Comment (VSadov) [reply src/native/minipal/time.c:94]: The other reason for `10` is that the default timer slack on Linux is 50 microseconds. So the shortest sleep could be on average 25 microseconds anyways if our wakeups are bunched up with other sleepers.
 
Thus `10` seems like a reasonable threshold to use sleep.

File: src/native/minipal/time.c [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+{
+#if HAVE_CLOCK_GETTIME_NSEC_NP
+    return (int64_t)clock_gettime_nsec_np(CLOCK_UPTIME_RAW);
+#else
+    struct timespec ts;
+    int result = clock_gettime(CLOCK_MONOTONIC, &ts);
+    if (result != 0)
+    {
+        assert(!"clock_gettime(CLOCK_MONOTONIC) failed");
+        __builtin_unreachable();
```
Comment (jkotas) [inline src/native/minipal/time.c:71]:
```suggestion
```
This does not seem to serve any purpose

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by VSadov** [comment]
Thanks!
