### PR TITLE
Fix reported string issue in ildasm

### LINKED ISSUE #124073: [metainfo] Buffer overflow in ConvertToUtf8 when WszWideCharToMultiByte fails
### Description

Found by Linux Verification Center (linuxtesting.org) with SVACE.

### Description
Buffer overflow in `ConvertToUtf8` when `WszWideCharToMultiByte` returns 0 (conversion error).  
The function writes `buffer[bufLen] = '\0'`, which is one byte beyond the allocated array bounds.

Affected code (mdinfo.cpp):

```cpp
int iLen = 1 + (ULONG32)qSigName.Size();
LPSTR pzSig = (LPSTR)(new char[iLen]);
VWrite(" :: %s", ConvertToUtf8((LPWSTR)qSigName.Ptr(), pzSig, iLen));
delete [] pzSig;


Inside ConvertToUtf8 (approximate):
C++int res = WszWideCharToMultiByte(CP_UTF8, 0, name, -1, buffer, bufLen, NULL, NULL);
if (res == 0)
    buffer[bufLen] = '\0';  // ← out-of-bounds write!

### Reproduction Steps

Trigger DisplayCustomAttributeInfo with metadata where WszWideCharToMultiByte fails (e.g. very long or invalid UTF-16 string).
Hard to reproduce reliably without modifying metadata, but the overflow is clear from static analysis.

### Expected behavior

On conversion failure (res == 0), the buffer should remain safe (e.g. set to empty string without writing beyond bounds).

### Actual behavior

Out-of-bounds write (buffer[bufLen]) → heap corruption / crash / potential security impact.

### Regression?

No 

### Known Workarounds

None practical — requires avoiding conversion failures (not controllable).

### Configuration

.NET Runtime tools (metainfo tool)
Platforms: all — the issue is platform-independent
Found via static analysis (SVACE) in recent versions of dotnet/runtime
No specific runtime version / OS / architecture tested — detected purely by static analysis in mdinfo.cpp

### Other information

Found by Linux Verification Center (linuxtesting.org) with SVACE.
Suggested fix (minimal and safe):
static const char* ConvertToUtf8(LPCWSTR name, char* buffer, ULONG bufLen)
{
    if (bufLen == 0 || buffer == nullptr) {
        return "";
    }

    int res = WszWideCharToMultiByte(CP_UTF8, 0, name, -1, buffer, bufLen, NULL, NULL);

    if (res > 0) {
        // Success — string is already null-terminated inside buffer
    } else {
        // Error — make empty string safely
        buffer[0] = '\0';
    }

    return buffer;
}

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Introduced in https://github.com/dotnet/runtime/pull/78894
Fixes https://github.com/dotnet/runtime/issues/124073

### CODE REVIEW

File: src/coreclr/tools/metainfo/mdinfo.cpp [hunk 1]
```diff
@@ -199,7 +199,7 @@ static const char* ConvertToUtf8(LPCWSTR name, _Out_writes_(bufLen) char* buffer
 {
     int res = WideCharToMultiByte(CP_UTF8, 0, name, -1, buffer, bufLen, NULL, NULL);
     if (res == 0)
-        buffer[bufLen] = '\0';
+        buffer[0] = '\0';
```
Comment (jkotas) [inline src/coreclr/tools/metainfo/mdinfo.cpp:202]: Do all callers pass in `bufLen` > 0? Maybe this should `return "";` instead?

Comment (AaronRobinsonMSFT) [reply src/coreclr/tools/metainfo/mdinfo.cpp:202]: Yes. It is a bit convoluted, but all direct callers pass in an `ARRAY_SIZE()` from a stack allocated array or for indirect calls, the forwared size/buffer is also a `ARRAY_SIZE()` on a stack allocated array.

Comment (AaronRobinsonMSFT) [reply src/coreclr/tools/metainfo/mdinfo.cpp:202]: I'm also fine passing back `""` if that is preferred.

Comment (AaronRobinsonMSFT) [inline src/coreclr/tools/metainfo/mdinfo.cpp:202]:
```suggestion
        return "";
```

**Review by jkotas — APPROVED** [review]

File: src/coreclr/tools/metainfo/mdinfo.cpp [hunk 2]
```diff
@@ -199,7 +199,7 @@ static const char* ConvertToUtf8(LPCWSTR name, _Out_writes_(bufLen) char* buffer
 {
     int res = WideCharToMultiByte(CP_UTF8, 0, name, -1, buffer, bufLen, NULL, NULL);
     if (res == 0)
-        buffer[bufLen] = '\0';
+        return "";
     return buffer;
```
[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/tools/metainfo/mdinfo.cpp:203]: It sounds like copilot disagrees with `""`. I am fine with the original fix assuming you have checked that all callers pass in non-empty buffer.

File: src/coreclr/tools/metainfo/mdinfo.cpp [hunk 3]
```diff
@@ -199,7 +199,7 @@ static const char* ConvertToUtf8(LPCWSTR name, _Out_writes_(bufLen) char* buffer
 {
     int res = WideCharToMultiByte(CP_UTF8, 0, name, -1, buffer, bufLen, NULL, NULL);
     if (res == 0)
-        buffer[bufLen] = '\0';
+        return "";
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/tools/metainfo/mdinfo.cpp]:
```suggestion
    {
        if (buffer != NULL) buffer[0] = '\0';
        return "";
    }
```

File: src/coreclr/tools/metainfo/mdinfo.cpp [hunk 4]
```diff
@@ -199,7 +199,10 @@ static const char* ConvertToUtf8(LPCWSTR name, _Out_writes_(bufLen) char* buffer
 {
     int res = WideCharToMultiByte(CP_UTF8, 0, name, -1, buffer, bufLen, NULL, NULL);
     if (res == 0)
-        buffer[bufLen] = '\0';
+    {
+        if (buffer != NULL) buffer[0] = '\0';
+        return "";
+    }
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/tools/metainfo/mdinfo.cpp]:
```suggestion
        buffer[0] = '\0';
```
