### PR TITLE
Fix: SettingsProperty constructor ignores serializeAs parameter if it is not SettingsSerializeAs.Binary

### LINKED ISSUE #104732: SettingsProperty constructor ignores serializeAs parameter if it is not SettingsSerializeAs.Binary
### Description

The SettingsProperty constructor ignores the serializeAs parameter if it is not SettingsSerializeAs.Binary.

### Reproduction Steps

```
using System.Configuration;

var settingsProperty = new SettingsProperty("Name", typeof(string), new LocalFileSettingsProvider(), false, "", SettingsSerializeAs.Xml, new SettingsAttributeDictionary(), false, false);

Console.WriteLine(settingsProperty.SerializeAs);
```

### Expected behavior

Outputs "Xml"

### Actual behavior

Outputs "String"

### Regression?

Yes, worked before v6.0.0-preview.5.21301.5.
Caused by https://github.com/dotnet/runtime/pull/50531
Related to https://github.com/dotnet/runtime/issues/39295

### Known Workarounds

Set SettingsProperty.SerializeAs property directly after creating the object.

### Configuration

.NET 8

### Other information

Easy to fix by inserting the following lines in line 55 of https://github.com/dotnet/runtime/blob/main/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsProperty.cs

```
else
{
    SerializeAs = serializeAs;
}
```

### PR DESCRIPTION
**Pull request by buyaa-n**
As mentioned in the [issue](https://github.com/dotnet/runtime/issues/104732) the `SettingsProperty` constructor ignores `serializeAs` parameter if it is not `SettingsSerializeAs.Binary`, the regression caused by https://github.com/dotnet/runtime/pull/50531 which allows `BinaryFormatter` serialization only when an `AppContext` switch: `System.Configuration.ConfigurationManager.EnableUnsafeBinaryFormatterInPropertyValueSerialization` is set, and throws otherwise.

The current fix is setting the `SerializeAs` property with the `serializeAs` parameter when it is not `SettingsSerializeAs.Binary`, though we might want to remove the `AppContext` switch logic and throw for `SettingsSerializeAs.Binary` as now the `BinaryFormatter` is removed and accessing the property values throws `PlatformNotSupportedException` on serialization even if the switch is on. The related test `SerializeAndDeserializeWithSettingsSerializeAsBinary` now throws PNSE on VS, skipped when run from command line.

Fixes https://github.com/dotnet/runtime/issues/104732

### CODE REVIEW

File: src/libraries/System.Configuration.ConfigurationManager/tests/System/Configuration/SettingsPropertyTests.cs [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+        {
+            var settingsProperty = new SettingsProperty(
+                "TestName",
+                typeof(string),
+                null,
+                true,
+                "TestDefaultValue",
+                serializeAs,
+                new SettingsAttributeDictionary(),
+                true,
```
Comment (steveharter) [inline src/libraries/System.Configuration.ConfigurationManager/tests/System/Configuration/SettingsPropertyTests.cs:40]: Comment
nit: add parameter name - e.g. `throwOnErrorDeserializing : true` - here and elsewhere for the various bools\nulls.

**Review by steveharter — APPROVED** [review]
