### PR TITLE
JIT: verify containment safety before forming address modes

### LINKED ISSUE #64936: Assertion failed 'isGeneralRegister(reg3)' on R2R_CG2 linux-arm64 outerloop
`Generate CORE_ROOT` step of `CoreCLR Pri1 Runtime Tests Run R2R_CG2 Linux arm64 checked` leg failed this assertion https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1597389/logs/1104:

```
  8 / 261 (2%, 1 failed): failed in 3497 msecs, exit code 134, expected 0: dotnet /__w/1/s/artifacts/bin/coreclr/Linux.arm64.Checked/x64/crossgen2/crossgen2.dll @/__w/1/s/artifacts/tests/coreclr/obj/Linux.arm64.Checked/crossgen.out/System.Security.Cryptography.dll.rsp
    /__w/1/s/src/coreclr/jit/emitarm64.cpp:6821
    Assertion failed 'isGeneralRegister(reg3)' in 'System.Security.Cryptography.X509Certificates.OpenSslX509ChainProcessor:FindChainViaAia(byref):Interop+Crypto+X509VerifyStatusCode:this' during 'Generate code' (IL size 473)
  10 / 261 (2%, 1 failed): launching: /__w/1/s/.dotnet/dotnet /__w/1/s/artifacts/bin/coreclr/Linux.arm64.Checked/x64/crossgen2/crossgen2.dll @/__w/1/s/artifacts/tests/coreclr/obj/Linux.arm64.Checked/crossgen.out/System.Net.Http.dll.rsp
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
At least on arm64, where LEAs must be contained.

Fixes #64936.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib 

My local jit-format runs insist this is how things should format. Seems odd.

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -7065,7 +7065,16 @@ void Lowering::ContainCheckBitCast(GenTree* node)
...
-    TryCreateAddrMode(ind->Addr(), true, ind);
+
+#if defined(TARGET_ARM64)
+    // Verify containment safety before creating an LEA that must be contained.
+    //
+    const bool isContainable = IsSafeToContainMem(ind, ind->Addr());
+#else
+    const bool     isContainable         = true;
+#endif
+    TryCreateAddrMode(ind->Addr(), isContainable, ind);
```
Comment (EgorBo) [inline src/coreclr/jit/lower.cpp:7076]: `TryCreateAddrMode` is called with `true` from other places too so I wonder if those need this check as well

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/lower.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lower.cpp:7076]: We should be doing the "right" safety checks later when we actually mark the node contained.

So the issue is whether the target can handle a non-contained LEA. arm64 can't handle a non-contained LEA but xarch/arm32 can.

**Comment by AndyAyersMS** [comment]
Handful of diffs, all regressions (not surprisingly). Many look to be gratuitous, perhaps spurious flags.
```asm
;; libraries.pmi

;; Internal.TypeSystem.Interop.ArrayMarshaller:GetElementMarshaller(int):Internal.TypeSystem.Interop.Marshaller:this

;; BEFORE
            ldr     w14, [x19,#96]
            str     w14, [x0,#88]

;; AFTER
            add     x14, x0, #88
            ldr     w15, [x19,#96]
            str     w15, [x14]

;; BEFORE
            ldrb    w14, [x19,#110]
            strb    w14, [x0,#110]

;; AFTER
            add     x14, x0, #110
            ldrb    w15, [x19,#110]
            strb    w15, [x14]

;;Number:NumberToString(byref,byref,ushort,int,System.Globalization.NumberFormatInfo,bool)

;; BEFORE
            ldrh    w1, [x1,#12]
            strh    w1, [x2, w0, UXTW #2]

;; AFTER
            ubfiz   x3, x0, #1, #32
            add     x2, x2, x3
            ldrh    w1, [x1,#12]
            strh    w1, [x2]
```

Let me look at a few of these in more detail.

**Comment by AndyAyersMS** [comment]
Not clear to me if the failure this issue is addressing is still happening.

**Comment by AndyAyersMS** [comment]
Outerloop had two failures -- one looks like an OOM while jitting that we see from time to time (crossgen2, x86, hugeexpr1). The other looks like a flaky CI issue. Retrying the latter.
