### PR TITLE
Fix auto layout algorithm to compute structure alignment correctly

### LINKED ISSUE #65281: Test failure JIT\\HardwareIntrinsics\\Arm\\AdvSimd.Arm64\\AdvSimd.Arm64_Part2_r\\AdvSimd.Arm64_Part2_r.cmd
Run: [runtime-coreclr outerloop 20220213.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1610455&view=ms.vss-test-web.build-test-results-tab&runId=44863868&paneView=debug&resultId=100371)

Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- JIT\\HardwareIntrinsics\\Arm\\AdvSimd.Arm64\\AdvSimd.Arm64_Part2_ro\\AdvSimd.Arm64_Part2_ro.cmd
- JIT\\HardwareIntrinsics\\Arm\\AdvSimd.Arm64\\AdvSimd.Arm64_Part2_r\\AdvSimd.Arm64_Part2_r.cmd

R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- JIT\\HardwareIntrinsics\\Arm\\AdvSimd.Arm64\\AdvSimd.Arm64_Part2_ro\\AdvSimd.Arm64_Part2_ro.cmd
- JIT\\HardwareIntrinsics\\Arm\\AdvSimd.Arm64\\AdvSimd.Arm64_Part2_r\\AdvSimd.Arm64_Part2_r.cmd

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_r/AdvSimd.Arm64_Part2_r.sh

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_r/AdvSimd.Arm64_Part2_r.sh

R2R-CG2 Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_ro/AdvSimd.Arm64_Part2_ro.sh
- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_r/AdvSimd.Arm64_Part2_r.sh

R2R-CG2 Linux arm64 Checked @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_ro/AdvSimd.Arm64_Part2_ro.sh
- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_r/AdvSimd.Arm64_Part2_r.sh
```
**Error message:**
```
Could Not Find D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\AdvSimd.Arm64_Part2_ro.dll.rsp
Could Not Find D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\TestLibrary.dll.rsp

Assert failure(PID 5444 [0x00001544], Thread: 12672 [0x3180]): Verify_TypeLayout 'TestStruct' failed to verify type layout

CORECLR! LoadDynamicInfoEntry + 0x10C0 (0x00007ff8132d27d8) CORECLR! Module::FixupNativeEntry + 0x6C (0x00007ff81325077c)
CORECLR! Module::FixupDelayListAux<Module ,int (__cdecl Module::)(CORCOMPILE_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x18C (0x00007ff813393094) CORECLR! ReadyToRunInfo::GetEntryPoint + 0x2F4 (0x00007ff813394224)
CORECLR! MethodDesc::GetPrecompiledR2RCode + 0x38 (0x00007ff81332e5e0) CORECLR! MethodDesc::GetPrecompiledCode + 0x28 (0x00007ff81332e3b8)
CORECLR! MethodDesc::PrepareILBasedCode + 0x2AC (0x00007ff813330404) CORECLR! MethodDesc::PrepareCode + 0x54 (0x00007ff81333014c)
CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x2A8 (0x00007ff813277100) CORECLR! MethodDesc::DoPrestub + 0x344 (0x00007ff81332c054)
File: D:\a_work\1\s\src\coreclr\vm\jitinterface.cpp Line: 13513
Image: D:\h\w\A1B208CC\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\A1B208CC\w\A405093D\uploads\Reports\JIT.HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\AdvSimd.Arm64_Part2_ro.output.txt
Raw output:
BEGIN EXECUTION
AdvSimd.Arm64_Part2_ro.dll
TestLibrary.dll
2 file(s) copied.
Response file: D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\AdvSimd.Arm64_Part2_ro.dll.rsp
D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\IL-CG2\AdvSimd.Arm64_Part2_ro.dll
-o:D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\AdvSimd.Arm64_Part2_ro.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A1B208CC\p\System..dll
-r:D:\h\w\A1B208CC\p\Microsoft..dll
-r:D:\h\w\A1B208CC\p\mscorlib.dll
-r:D:\h\w\A1B208CC\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A1B208CC\p\crossgen2\crossgen2.dll" @"D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\AdvSimd.Arm64_Part2_ro.dll.rsp"   -r:D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\AdvSimd.Arm64_Part2_ro.dll
Response file: D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\TestLibrary.dll.rsp
D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\IL-CG2\TestLibrary.dll
-o:D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\TestLibrary.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A1B208CC\p\System..dll
-r:D:\h\w\A1B208CC\p\Microsoft..dll
-r:D:\h\w\A1B208CC\p\mscorlib.dll
-r:D:\h\w\A1B208CC\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A1B208CC\p\crossgen2\crossgen2.dll" @"D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\TestLibrary.dll.rsp"   -r:D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A1B208CC\w\A405093D\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro\TestLibrary.dll
"D:\h\w\A1B208CC\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  AdvSimd.Arm64_Part2_ro.dll
Supported ISAs:
AdvSimd:   True
Aes:       True
ArmBase:   True


Stack trace
   at JIT_HardwareIntrinsics._Arm_AdvSimd_Arm64_AdvSimd_Arm64_Part2_ro_AdvSimd_Arm64_Part2_ro_._Arm_AdvSimd_Arm64_AdvSimd_Arm64_Part2_ro_AdvSimd_Arm64_Part2_ro_cmd()
```

**NOTE**: `AdvSimd.Arm64\AdvSimd.Arm64_Part2_r` and `AdvSimd.Arm64\AdvSimd.Arm64_Part2_ro` are disabled by https://github.com/dotnet/runtime/pull/65227. 

Please re-enable these tests when the issue is fixed!

### PR DESCRIPTION
**Pull request by davidwrighton**
- In particular:
  1. The alignment requirement imposed by of a non-primitive, non-enum valuetype field is the alignment of that field
  2. The alignment requirement imposed by a primitive is the pointer size of the target platform, unless running on Arm32, in which case if the primitive or enum is 8 bytes in size, the alignment requirement is 8.

- The previous implementation produced an alignment of pointer size, unless running on Arm32 and one of the fields had an alignment requirement of 8 (in which case the alignment requirement computed for the structure would be 8)

In addition, add a test which verifies that the instance field layout test types are actually producing R2R compatible results at runtime.
 - This test shows that we have some issues around explicit layout, so I was forced to disable that portion of the test for now.

Fixes #65281

### CODE REVIEW

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 1]
```diff
@@ -520,25 +520,41 @@ protected ComputedInstanceFieldLayout ComputeAutoFieldLayout(MetadataType type,
...
+                            // Handle alignment of long/ulong/double on ARM32
+                            largestAlignmentRequired = LayoutInt.Max(context.Target.GetObjectAlignment(fieldSizeAndAlignment.Size), largestAlignmentRequired);
+                        }
+                    }
                 }
             }
 
-            largestAlignmentRequired = context.Target.GetObjectAlignment(largestAlignmentRequired);
-            bool requiresAlign8 = !largestAlignmentRequired.IsIndeterminate && largestAlignmentRequired.AsInt > 4;
+            bool requiresAlign8 = !largestAlignmentRequired.IsIndeterminate && context.Target.PointerSize == 4 && context.Target.GetObjectAlignment(largestAlignmentRequired).AsInt > 4 && context.Target.PointerSize == 4;
```
Comment (trylek) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:557]: Nit - you're checking <code>context.Target.PointerSize == 4</code> twice.

**Review by trylek — APPROVED** [review]
Looks good, thanks for making another iteration in untangling this non-trivial algorithm!

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 2]
```diff
@@ -520,25 +520,41 @@ protected ComputedInstanceFieldLayout ComputeAutoFieldLayout(MetadataType type,
...
-                }
                 else
                 {
-                    int log2size = CalculateLog2(fieldSizeAndAlignment.Size.AsInt);
-                    instanceNonGCPointerFieldsArr[log2size][instanceNonGCPointerFieldsCount[log2size]++] = field;
+                    // non-value-type fields always require pointer alignment
+                    // This does not account for types that are marked IsAlign8Candidate due to 8-byte fields
+                    // but that is explicitly handled when we calculate the final alignment for the type.
+
+                    // This behavior is extremely strange for primitive types, as it makes a struct with a single byte in it
```
Comment (tannergooding) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:534]: Can you elaborate on this? Wouldn't `struct S { byte x; }` hit `IsByValueClass(fieldType)` above and so it would be `1-byte alignment`?

Should this instead say `class` since it looks like `class C { byte x; }` would hit this case and it would be `align: sizeof(void*)`?

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 3]
```diff
@@ -520,25 +520,41 @@ protected ComputedInstanceFieldLayout ComputeAutoFieldLayout(MetadataType type,
...
+                    else
+                    {
+                        int log2size = CalculateLog2(fieldSizeAndAlignment.Size.AsInt);
+                        instanceNonGCPointerFieldsArr[log2size][instanceNonGCPointerFieldsCount[log2size]++] = field;
+
+                        if (fieldType.IsPrimitive || fieldType.IsEnum)
+                        {
+                            // Handle alignment of long/ulong/double on ARM32
+                            largestAlignmentRequired = LayoutInt.Max(context.Target.GetObjectAlignment(fieldSizeAndAlignment.Size), largestAlignmentRequired);
+                        }
```
Comment (tannergooding) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:552]: What about `Vector128<T>`? Don't we want that to have 16-byte packing (on supported platforms) even if the GC only guarantees `8-byte` alignment?

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs (hunk 2 above)
Comment (trylek) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:534]: Hmm, these questions need David's response but he's on vacation next week. Should we hold off merging this change until he's back so that he can answer them?

Comment (tannergooding) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:534]: Was this targeting .NET 7?

If so then for this one, its just a question on comment wording, I don't think it's worth blocking over.

For the one below, I think it's worth confirming that CG2 is at least matching what the RyuJIT VM does. If it is, then I think its fine to merge.

Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:534]: The comment needs clarity, and possibly a test about this particularly odd behavior. From my reading, the rules are that:
```
struct S1
{
    byte b;
}
[StructLayout(LayoutKind.Auto)]
struct S1_Auto
{
    byte b;
}
struct S2
{
    S1 fld1;
    S1_Auto fld2;
}
```

Assuming 64bit...
This will result in `S1` having size of 1, and alignment of 1, `S1_Auto` having size of 8 and alignment of 8, and `S2` having size of 16, and alignment of 8. Note that this wacky behavior is exclusive to auto layout structures.

Largest alignment rules for classes are less interesting in general, and pretty much just impact ARM32, where a class alignment of 8 is significant, and triggers the 8 byte alignment behavior. However, we still calculate them, in case we add support for 16 byte or higher object alignment rules in the future.

Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:534]: Also `IsByValueClass(t)` is false for primitive and enum types, and so doesn't go into the structure alignment path.

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs (hunk 3 above)
Comment (tannergooding) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:552]: Right, `struct S1 { byte x; Vector128<...> y; }` and `struct S2 { Vector128<...> x; byte y }` should both be `Pack = 16` and therefore `size = 32`. Therefore a struct containing `S1` or `S2` should likewise be `Pack = 16` so that the `S1/S2` field are at the correct offset.

So shouldn't this factor into `largestAlignmentRequired`? If not, could you explain the difference between this and the other algorithm and why they are distinct/separate?

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs (hunk 2 above)
Comment (tannergooding) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:534]: > Note that this wacky behavior is exclusive to auto layout structures.

I thought we fixed some of this for `generics` so that `Nullable<T>` wasn't "too large" anymore? Or was that a different fix since its generic but sequential?

This, more generally, seems like something which may have undesirable consequences and which we may want to look at more in depth for .NET 8. Consider types like `ValueTuple` which are frequently used for tuples of primitives and where its marked `Auto` with the intent that the BCL optimizes the layout to be more efficient. If the alignment of fields is treated as `8`, that is not going to be the case and many usages will end up more expensive instead.

Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:534]: Mmm... maybe? I've been writing tests, and to get the wacky layout behavior, I need to make the auto layout structure be larger than a pointer, so the tests that cover these boundary conditions are even dumber than I thought.

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs (hunk 3 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:559]: Yes, that's all correct, and does funnel into this algorithm, but the portion you commented on is exclusively for primitives, enums, and pointers (of various types). Normal valuetypes, and the various vector things (and Int128, etc) are not part of this.

Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:559]: Also, this is the auto layout algorithm, not the sequential layout algorithm. Note, in addition, I'm looking at adding some tests to look at the behavior of classes with fields of higher than pointer alignment, but we'll see where that goes. My suspicion is that the current model for 16 byte structures in class types, in the presence of derived types across R2R version boundaries, does not actually reliably result in aligned 16byte fields.

Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:559]: But that is irrelevant to the thrust of these changes, which are about allowing higher alignment to affect auto layout fields at all within crossgen2.

**Comment by danmoseley** [comment]
.NET 7 backport candidate?
