### PR TITLE
Fix RHEL7 socket dispose hang, and extend coverage

### LINKED ISSUE #42686: Socket Dispose during synchronous operation hangs on RedHat 7
Disposing a Socket that has a pending synchronous Connect/Accept operation intermittently hangs on RedHat7 and CentOS7 x64 in CI.

```c#
using var client = new Socket(SocketType.Stream, ProtocolType.Tcp);

Exception ex = await Assert.ThrowsAnyAsync<Exception>(async () =>
{
    Task connectTask = Task.Run(() => client.Connect(endPoint));
    await WaitForEventAsync(events, "ConnectStart"); // Wait until the operation starts
    Task disposeTask = Task.Run(() => client.Dispose());
    await new[] { connectTask, disposeTask }.WhenAllOrAnyFailed(); // Hang
});
```

Existing [Connect](https://github.com/dotnet/runtime/blob/1bc493ab8b65d167180ad1f41f3a6292d28d7094/src/libraries/System.Net.Sockets/tests/FunctionalTests/Connect.cs#L125) and [Accept](https://github.com/dotnet/runtime/blob/1bc493ab8b65d167180ad1f41f3a6292d28d7094/src/libraries/System.Net.Sockets/tests/FunctionalTests/Accept.cs#L293) tests are potentially masking this failure with the use of a timeout/retry combo.

Example [CI Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42188-merge-8f4f5063b5cf4b0fba/System.Net.Sockets.Tests/console.de4ca856.log?sv=2019-02-02&se=2020-10-13T06%3A28%3A45Z&sr=c&sp=rl&sig=PxZsuxlyOrsTmWiLwX5U0Qjchb9GyLItifD4845u%2FIY%3D)

### PR DESCRIPTION
**Pull request by antonfirsov**
The PR:
- Fixes  #42686 by doing a graceful close in case if the abortive `connect(AF_UNSPEC)` call fails on Linux.
- Includes test improvements from #42725 making sure that we don't mask failed cancellations by our retry logic.
- Extends Tom's tests so Connect, Accept, Send and Receive cancellations are also tested with IPV6 and DualMode sockets

~Unfortunately, my new IPV6 Receive cancellation test keeps failing on RHEL7, even with the change in `pal_networking.c`. So far I was not able to reproduce this in native code, `shutdown(s, SHUT_RDWR)` seems to work nicely with raw sockets. I suggest to disable that test case for now, open a new issue, and do a separate investigation.~

@tmds @geoffkizer PTAL

### CODE REVIEW

File: src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs [hunk 1]
```diff
@@ -38,14 +38,21 @@ public static void ForceNonBlocking(this Socket socket, bool force)
             }
         }
 
-        public static (Socket, Socket) CreateConnectedSocketPair()
+        public static (Socket client, Socket server) CreateConnectedSocketPair() => CreateConnectedSocketPair(IPAddress.Loopback, false);
+
+        public static (Socket client, Socket server) CreateConnectedSocketPair(IPAddress serverAddress, bool dualModeClient)
```
Comment (geoffkizer) [inline src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs:43]: Nit: It doesn't make any sense to pass in anything other than either Loopback or IPv6Loopback here, right? So I'd suggest just changing this to "bool ipv6" or similar, just to make this clearer.

Comment (geoffkizer) [reply src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs:43]: Also, may as well use default arguments here.

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/Accept.cs [hunk 2]
```diff
@@ -330,20 +340,33 @@ public async Task AcceptGetsCanceledByDispose()
...
+                        Assert.Equal(SocketError.Interrupted, localSocketError);
+                    }
+                    else
+                    {
+                        Assert.Equal(SocketError.OperationAborted, localSocketError);
+                    }
+                    break;
                 }
-                else
+                catch
```
Comment (geoffkizer) [inline src/libraries/System.Net.Sockets/tests/FunctionalTests/Accept.cs:360]: Should we catch a specific exception here, like some XUnit exception class? Seems like that would be safer and clearer. Similarly below.

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs [hunk 3]
```diff
@@ -1052,46 +1093,59 @@ public async Task TcpReceiveSendGetsCanceledByDispose(bool receiveOrSend)
...
-                            {
-                                peerSocketError = se.SocketErrorCode;
-                                break;
-                            }
+                            Assert.Equal(SocketError.ConnectionReset, peerSocketError);
                         }
-                        Assert.Equal(SocketError.ConnectionReset, peerSocketError);
+                        break;
+                    }
+                    catch
```
Comment (geoffkizer) [inline src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1138]: This catch in particular worries me because it's wrapping a bunch of code, including the ReceiveAsync call above, and by eating all exceptions we could be masking unexpected exceptions.

Seems like maybe we shouldn't use try/catch at all to trigger retries, but instead just look at the results and determine whether a retry is needed. That seems safest.

**Review by geoffkizer — CHANGES_REQUESTED** [review]
The fix itself looks fine. Some comments on the tests.

File: src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs (hunk 1 above)
Comment (antonfirsov) [reply src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs]: fixed

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs [hunk 4]
```diff
@@ -978,34 +989,65 @@ public async Task UdpReceiveGetsCanceledByDispose()
...
+        [Theory(Timeout = 40000)]
+        [MemberData(nameof(TcpReceiveSendGetsCanceledByDispose_Data))]
+        public async Task TcpReceiveSendGetsCanceledByDispose(bool receiveOrSend, bool ipv6Server, bool dualModeClient)
         {
+            if (UsesSync && PlatformDetection.IsRedHatFamily7 &&
+                receiveOrSend && (ipv6Server || dualModeClient))
+            {
+                // The IPV6 synchronous Receive case times out on RedHat7 systems
+                // TODO: open a new issue for this case, if the PR gets accepted.
+                return;
```
Comment (antonfirsov) [inline src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1040]: I tried to use `SkipTestException` here, but it got reported as a failure on CI. Probably doesn't work in async context.

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs (hunk 3 above)
Comment (antonfirsov) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: @geoffkizer that happened here mostly was that `RetryHelper` got unrolled to a manual loop, we are not any more permissive than before the change. However, if we are this concerned about fatal exceptions triggering unwanted retries, we should be probably much more careful about using `RetryHelper` or stop using it in general.

My original suggestion was to actually extend it with a `FatalException` to escape retries (see https://github.com/dotnet/runtime/commit/1339f52abb60c4af73306cd3776cb969ed898762), but that idea got some pushback from @tmds.

Maybe we need to do it the other way around: define a `RetryException` or some sort of exception filter to detect the permissive cases and and fail on everything else?

@stephentoub any thoughts about this?

File: src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs [hunk 5]
```diff
@@ -38,14 +38,21 @@ public static void ForceNonBlocking(this Socket socket, bool force)
             }
         }
 
-        public static (Socket, Socket) CreateConnectedSocketPair()
+        public static (Socket client, Socket server) CreateConnectedSocketPair(bool ipv6 = false, bool dualModeClient = false)
```
Comment (tmds) [inline src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs:41]: Nit: these are not `client` and `server`, but two connected TCP peers. The `server` Socket doesn't leave the method, and it looks like we are not Disposing it, which we probably should.

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs (hunk 4 above)
Comment (tmds) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1040]: We'll be able to remove this when the RHEL7 fix is available, and CI machines are updated for it.

File: src/libraries/Native/Unix/System.Native/pal_networking.c [hunk 6]
```diff
@@ -3085,6 +3085,11 @@ int32_t SystemNative_Disconnect(intptr_t socket)
     addr.sa_family = AF_UNSPEC;
 
     err = connect(fd, &addr, sizeof(addr));
+    if (err != 0) 
+    {
+        // On some older kernels connect(AF_UNSPEC) may fail. Fall back to shutdown in these cases:
```
Comment (tmds) [inline src/libraries/Native/Unix/System.Native/pal_networking.c:3090]: `connect(AF_UNSPEC)` has worked since old kernels. It's an issue in SELinux that caused this to fail. That's why it is affecting SELinux based distros. You don't need to update the comment, this is background info.

**Comment by tmds** [comment]
> my new IPV6 Receive cancellation test keeps failing on RHEL7, even with the change in pal_networking.c. So far I was not able to reproduce this in native code, shutdown(s, SHUT_RDWR) seems to work nicely with raw sockets. I suggest to disable that test case for now, open a new issue, and do a separate investigation.

Let's spend a bit more time trying to understand this before creating a new issue.

File: src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs (hunk 5 above)
Comment (antonfirsov) [reply src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs:41]: > Nit: these are not client and server, but two connected TCP peers. 

The terminology reflects their roles during the establishment of the connection. I understand that this information is not needed afterwards, but still I find the labels useful for convenience, because it helps me mentally map the tests to a common real-world scenarios. For example `dualModeClient = false` refers to the first `Socket client`. and it sounds more natural than `bool dualModeSocket1`, which would be the case if we'd rename the tuple. We use this terminology in other tests, although it's not necessary or meaningful to label anything as client/server.

> The `server` Socket doesn't leave the method, and it looks like we are not Disposing it, which we probably should.

You mean the `listner` I guess. I also don't like this, but this problem is not specific to the PR. We should fix it on all call sites which I would do separately.

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs (hunk 3 above)
Comment (stephentoub) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: My initial inclination is to add a filter func to the retry helper methods that decides whether to handle the exception or not, e.g.
https://github.com/dotnet/runtime/blob/c788fe1786ffc9295f1c469e506e26ff2ff4f94c/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs#L56
becomes
```C#
public static async Task ExecuteAsync(Func<Task> test, int maxAttempts = 5, Func<int, int> backoffFunc = null, Func<Exception, bool> filterFunc = null)
```
and
https://github.com/dotnet/runtime/blob/c788fe1786ffc9295f1c469e506e26ff2ff4f94c/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs#L77
becomes
```C#
catch (Exception e) when (filterFunc is null || filterFunc(e))
```

Comment (antonfirsov) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: @stephentoub I think without further sugar this API would only complicate call sites (test-specifc custom exception types and/or complicated filter methods), making readability even worse. If I could design `RetryHelper` from scratch, I would do something like this:
https://gist.github.com/antonfirsov/d5cf9e01b065e58420080d0e9c31e548

In this PR, I will go with the simplest possible fix now, and not touch `RetryHelper`, since it looks like we don't have consensus and sufficient attention span here, but I believe this is a question that's worth coming back to later.

Comment (stephentoub) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: >  I think without further sugar this API would only complicate call sites

Every existing usage would be unchanged unless it actually wanted to restrict the retry conditions.  If you wanted to only retry RetryExceptions, you'd just add `IsRetryException` or `e =>  e is RetryException` to the call site.

So I'm not seeing the complication...?

**Comment by antonfirsov** [comment]
> Let's spend a bit more time trying to understand this before creating a new issue.

@tmds here is my attempt to repro the issue in native code, let me know if you have any ideas:
https://gist.github.com/antonfirsov/36f2121a3a0efb13ac6988fcc293e6e0

I will try to debug into the C# test case in the meanwhile.

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs (hunk 4 above)
Comment (antonfirsov) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1040]: I'm not sure if it's exactly the same problem as we had with `Connect`.  The native repro does not hang. See:
 https://github.com/dotnet/runtime/pull/43409#issuecomment-709980516.

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs (hunk 3 above)
Comment (antonfirsov) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: By "complication" I meant boilerplate code. If we introduce a `RetryException` inside `RetryHelper.cs` instead of doing it repeatedly in individual test libraries, and maybe also add the `TryAssert` utility I suggested, then the extra `e => e is RetryException` parameter would be the only boilerplate which is fine for me.

Comment (stephentoub) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: I'm not clear on why any of that is necessary.  Are you saying in this example that you want to retry for some of the asserts but not for others?

Comment (antonfirsov) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: Yes. in this PR we want to retry on some assertions/exceptions, but not on others. We masked some fatal exceptions in socket tests by retrying. My concern is that we probably want to fail immediately on a bigger portion of asserts (or exceptions) than we thought before, but I'm not familiar with `RetryHelper` usages outside of socket tests.

Comment (stephentoub) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: I'm specifically asking about asserts, though.  In this test,  for example,  for what do we want to retry and what do we not want to retry?

Comment (antonfirsov) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: In this particular test we want to retry on these asserts:
https://github.com/dotnet/runtime/blob/1da5006d99c0de404cdc2678b20bcf9cf9e62175/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs#L994-L1007

But not on this one (and not any other non-xunit exceptions):
https://github.com/dotnet/runtime/blob/1da5006d99c0de404cdc2678b20bcf9cf9e62175/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs#L972

Of course, with a simple filter func we could retry on `XunitException` and throw some arbitrary exception instead of the second assert. But this doesn't feel like an ideal solution, would be harder to follow such a test code if I was new to the repo.

Comment (stephentoub) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: > But not on this one

Those four lines should just be:
```C#
await Task.WhenAny(disposeTask, receiveTask).WithTimeout(30000);
```

Comment (antonfirsov) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: Ok, I will give such a refactor a try, and see how the code will look and how will people react.

Comment (stephentoub) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1139]: Sounds good.  If it works well,  great.  If not,  we can explore other options.

**Comment by antonfirsov** [comment]
@tmds the following code prints `ConnectionAborted` with this fix, so the skipped failure only repros on CI:
https://gist.github.com/antonfirsov/9bcd49ea956644cc9069e5d5a00ee2e6

**Comment by antonfirsov** [comment]
@geoffkizer @tmds I've redone the test hardening on top of `RetryHelper` after extending it. I believe the resulting code is simpler and shorter + the volume of the changes in the PR is much smaller now.

Can you have another look?

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs [hunk 7]
```diff
@@ -1088,10 +1105,18 @@ public async Task TcpReceiveSendGetsCanceledByDispose(bool receiveOrSend)
...
-                        Assert.Equal(SocketError.ConnectionReset, peerSocketError);
+
+                        if (!expectGracefulShutdown)
+                        {
+                            Assert.Equal(SocketError.ConnectionReset, peerSocketError);
+                        }
+                        else
+                        {
+                            Assert.Null(peerSocketError);
+                        }
```
Comment (antonfirsov) [inline src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:1116]: @tmds the test failure I referred to turned out to be quite simple to fix.

**Review by geoffkizer — APPROVED** [review]
LGTM

**Comment by antonfirsov** [comment]
OuterLoop failures are #41531, #32955 and a timeout (?) in `System.Text.RegularExpressions.Tests`.
