### PR TITLE
Fix propagation of basic block flags for inlinee return expressions.

### LINKED ISSUE #37574: Test failure: JIT/Performance/CodeQuality/BenchmarksGame/reverse-complement/reverse-complement-1/reverse-complement-1.sh
failed in job: [runtime-coreclr jitstress 20200606.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=675191&view=ms.vss-test-web.build-test-results-tab&runId=20927598&resultId=109242&paneView=debug)

failed tests:
JIT/Performance/CodeQuality/BenchmarksGame/reverse-complement/reverse-complement-1/reverse-complement-1.sh
Loader/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions.sh

Error message
~~~
Assert failure(PID 481 [0x000001e1], Thread: 481 [0x01e1]): Assertion failed 'false' in 'BenchmarksGame.ReverseComplement_1:MatchesChecksum(System.Byte[],System.String):bool' during 'Early Value Propagation' (IL size 41)

 File: /__w/1/s/src/coreclr/src/jit/earlyprop.cpp Line: 189
 Image: /home/helixbot/work/B4920A0B/p/corerun

/home/helixbot/work/B4920A0B/w/B99A09D6/e/JIT/Performance/CodeQuality/BenchmarksGame/reverse-complement/reverse-complement-1/reverse-complement-1.sh: line 317: 481 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /home/helixbot/work/B4920A0B/w/B99A09D6/e/JIT/Performance/Reports/JIT.Performance/CodeQuality/BenchmarksGame/reverse-complement/reverse-complement-1/reverse-complement-1.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/B4920A0B/p/corerun reverse-complement-1.dll ''
>ONE Homo sapiens alu
TCGGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACCGCGCCCGGCC
>TWO IUB ambiguity codes
AATAGGCTHAHAGTACGACVGAATTATAAAGAHCCVAYHGHTTTACATSTTTATGNCCMT
AGCATATGATAVAAG
>THREE Homo sapiens frequency
AGGTCCGAAGAAACAACATGAGAGAAGTATGTGTGTTGCCCAGAGTATCTTTGTTAACGC
CGTCAGATCAAAAGACGTCATTTGACCATACTGTGTCCACAAATAGACTATAACGCAACA
CAAAC

BBF_HAS_IDX_LEN is not set on BB04 but is required because of the following tree 
N005 ( 3, 3) [000133] ---X-------- * ARR_LENGTH int 
N004 ( 1, 1) [000134] ------------ \--* LCL_VAR ref V03 loc1 u:2
Writing minidump to file /home/helixbot/dotnetbuild/dumps/coredump.481.dmp
Written 71610368 bytes (17483 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/B4920A0B/p
> /home/helixbot/work/B4920A0B/w/B99A09D6/e/JIT/Performance/CodeQuality/BenchmarksGame/reverse-complement/reverse-complement-1/reverse-complement-1.sh
Expected: True
Actual: False


Stack trace
   at JIT_Performance._CodeQuality_BenchmarksGame_reverse_complement_reverse_complement_1_reverse_complement_1_._CodeQuality_BenchmarksGame_reverse_complement_reverse_complement_1_reverse_complement_1_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.x64.Checked/TestWrappers/JIT.Performance/JIT.Performance.XUnitWrapper.cs:line 1498
~~~

### PR DESCRIPTION
**Pull request by erozenfeld**
#37335 introduced a new more precise way of propagating basic
block flags from inlinee return expressions. The assumption there
was that `fgUpdateInlineReturnExpressionPlaceHolder` is the only
place where `GT_RET_EXPR`'s are replaced with the actual nodes
from inlinees. That assumption was incorrect and this change fixes
the remaining places.

Fixes #37574.

### CODE REVIEW

**Comment by erozenfeld** [comment]
No diffs in x64 pmi framewors and benchmarks.

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib @AndyAyersMS PTAL

File: src/coreclr/src/jit/inline.h [hunk 1]
```diff
@@ -541,9 +541,11 @@ struct InlineCandidateInfo : public GuardedDevirtualizationCandidateInfo
 
 struct InlArgInfo
 {
-    GenTree* argNode;                     // caller node for this argument
-    GenTree* argBashTmpNode;              // tmp node created, if it may be replaced with actual arg
-    unsigned argTmpNum;                   // the argument tmp number
+    GenTree*         argNode;             // caller node for this argument
+    GenTree*         argBashTmpNode;      // tmp node created, if it may be replaced with actual arg
+    unsigned         argTmpNum;           // the argument tmp number
+    unsigned __int64 bbFlags;             // basic block flags that need to be added when replacing GT_RET_EXPR
```
Comment (AndyAyersMS) [inline src/coreclr/src/jit/inline.h:547]: Nit: I'd place this field first to minimize the amount of padding we might end up with here.

**Review by AndyAyersMS — APPROVED** [review]
I owe you an apology -- when I looked at your first fix for this I thought to ask if you handled the ret expr tunneling, but didn't. Sorry about that.

File: src/coreclr/src/jit/inline.h (hunk 1 above)
Comment (erozenfeld) [reply src/coreclr/src/jit/inline.h]: Sure, done.
