### PR TITLE
[wasm][globalization] `HybridGlobalization` fix bug in change case

### LINKED ISSUE #86794: [wasm][hybridglobalization] ToUpper/ToLower does not work correctly when the length of character changes
### Description

For some chars, e.g. "ß" the lenght changes when we change its case -> "SS".

### Reproduction Steps

using System;
using System.Globalization;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine("Straße".ToUpper(new CultureInfo("de-DE")));
		Console.WriteLine("Straße".ToUpperInvariant());
	}
}

### Expected behavior

The most correct behavior would be to return:
````
STRASSE
STRASSE
```

However, in non-hybrid it returns:
```
STRAßE
STRAßE
```
so we should align with the non-hybrid.

### Actual behavior

```
STRAße
STRAße
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/86794.

We should not allow the codepoints to expand because hybrid should work as much similar to ICU as possible.

ICU4C ignores "final sigma rule" (see documentation in the changes). We could support the inccorect ICU behavior but it's costly - e.g. by calling replace("\u03A3", "\u03C3") on each input string.

### CODE REVIEW

File: src/mono/wasm/runtime/hybrid-globalization/change-case.ts [hunk 1]
```diff
@@ -39,12 +61,34 @@ export function mono_wasm_change_case(culture: MonoStringRef, src: number, srcLe
...
             throw new Error("Cannot change case, the culture name is null.");
         const input = get_utf16_string(src, srcLength);
-        let result = toUpper ? input.toLocaleUpperCase(cultureName) : input.toLocaleLowerCase(cultureName);
-        if (result.length > destLength)
-            result = input;
+        const result = toUpper ? input.toLocaleUpperCase(cultureName) : input.toLocaleLowerCase(cultureName);
 
-        for (let i = 0; i < destLength; i++)
-            setU16(dst + i*2, result.charCodeAt(i));
+        if (result.length <= destLength)
```
Comment (pavelsavara) [inline src/mono/wasm/runtime/hybrid-globalization/change-case.ts:66]: would length report 2 for multi-surrogate characters like U+10437 (𐐷) ?

Comment (pavelsavara) [reply src/mono/wasm/runtime/hybrid-globalization/change-case.ts:66]: All good 
image

File: src/mono/wasm/runtime/hybrid-globalization/change-case.ts [hunk 2]
```diff
@@ -13,15 +13,37 @@ export function mono_wasm_change_case_invariant(src: number, srcLength: number,
...
-            setU16(dst + i*2, result.charCodeAt(i));
-        wrap_no_error_root(is_exception, exceptionRoot);
+        // workaround to maintain the ICU-like behavior
+        if (toUpper)
+        {
+            for (let i=0; i < input.length; i++)
+            {
+                const upperChar = input[i].toUpperCase();
+                const appendedChar = upperChar.length > 1 ? input[i] : upperChar;
+                setU16(dst + i*2, appendedChar.charCodeAt(0));
```
Comment (pavelsavara) [inline src/mono/wasm/runtime/hybrid-globalization/change-case.ts:35]: After we merge this https://github.com/dotnet/runtime/pull/86664 we should use `localHeapViewI16()` and `setU16_local` for better MT performance.

File: src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs [hunk 3]
```diff
@@ -394,6 +394,7 @@ public static IEnumerable<object[]> ToUpper_TestData()
                 // we also don't preform.
                 // es-zed does not case to SS when uppercased.
                 yield return new object[] { cultureName, "\u00DF", "\u00DF" };
+                yield return new object[] { cultureName, "stra\u00DFe", "STRA\u00DFE" };
```
Comment (pavelsavara) [inline src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs:397]: What is the browser behavior for `toUpperCase()` ?

File: src/mono/wasm/runtime/hybrid-globalization/change-case.ts [hunk 4]
```diff
@@ -13,15 +13,37 @@ export function mono_wasm_change_case_invariant(src: number, srcLength: number,
...
 
-        for (let i = 0; i < result.length; i++)
-            setU16(dst + i*2, result.charCodeAt(i));
-        wrap_no_error_root(is_exception, exceptionRoot);
+        // workaround to maintain the ICU-like behavior
+        if (toUpper)
+        {
+            for (let i=0; i < input.length; i++)
+            {
+                const upperChar = input[i].toUpperCase();
```
Comment (pavelsavara) [inline src/mono/wasm/runtime/hybrid-globalization/change-case.ts:33]: Are there any multi surrogate characters which would break with this operation ?

File: src/mono/wasm/runtime/hybrid-globalization/change-case.ts [hunk 5]
```diff
@@ -13,15 +13,37 @@ export function mono_wasm_change_case_invariant(src: number, srcLength: number,
...
     try{
         const input = get_utf16_string(src, srcLength);
-        let result = toUpper ? input.toUpperCase() : input.toLowerCase();
+        const result = toUpper ? input.toUpperCase() : input.toLowerCase();
+
         // Unicode defines some codepoints which expand into multiple codepoints,
         // originally we do not support this expansion
-        if (result.length > dstLength)
-            result = input;
+        if (result.length <= dstLength)
```
Comment (pavelsavara) [inline src/mono/wasm/runtime/hybrid-globalization/change-case.ts:20]: should this be compared with `input.length` instead of size of the buffer ? This will change behavior if there is buffer of different size.

File: src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs (hunk 3 above)
Comment (ilonatommy) [reply src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs:397]: image

File: src/mono/wasm/runtime/hybrid-globalization/change-case.ts (hunk 4 above)
Comment (ilonatommy) [reply src/mono/wasm/runtime/hybrid-globalization/change-case.ts:31]: Yes, lower "\uD801\uDC37" -> upper "\uD801\uDC0F"

File: src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs (hunk 3 above)
Comment (pavelsavara) [reply src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs:397]: That looks correct to me :)

Comment (ilonatommy) [reply src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs:397]: It is. But here we're keeping the ICU's behavior, so no codepoint expansion.

File: src/mono/wasm/runtime/hybrid-globalization/change-case.ts [hunk 6]
```diff
@@ -97,3 +158,18 @@ export function mono_wasm_change_case(culture: MonoStringRef, src: number, srcLe
         exceptionRoot.release();
     }
 }
+
+function IsSurrogate(str: string, startIdx: number) : boolean
```
Comment (pavelsavara) [inline src/mono/wasm/runtime/hybrid-globalization/change-case.ts:162]: nit: JS methods start with lowerCase

**Review by pavelsavara — APPROVED** [review]

File: src/mono/wasm/runtime/hybrid-globalization/change-case.ts [hunk 7]
```diff
@@ -49,4 +157,19 @@ export function mono_wasm_change_case(culture: MonoStringRef, src: number, srcLe
         cultureRoot.release();
         exceptionRoot.release();
     }
-}
\ No newline at end of file
+}
+
+function IsSurrogate(str: string, startIdx: number) : boolean
```
Comment (ilonatommy) [inline src/mono/wasm/runtime/hybrid-globalization/change-case.ts:162]:
```suggestion
function isSurrogate(str: string, startIdx: number) : boolean
```

**Comment by ilonatommy** [comment]
ios failures not connected
