### PR TITLE
Fix RVA field access in composite Crossgen2 build (#78723)

### LINKED ISSUE #78723: [Crossgen2] Fix RVA field access in composite mode
As the issue

https://github.com/dotnet/runtime/issues/65879

revealed, access to RVA fields in composite mode is partially incorrect. In WPF, the library DirectWriteForwarder is apparently Managed C++; for initializing global objects it uses the common pattern of using the method <code>initterm_m</code> cycling through an array of function pointers and calling them in sequence. The array is modelled in IL as an RVA field array and in single-file compilation mode it just works because we retain the RVA field file in its entirety. In composite mode however, when we encounter an RVA field access in the dependency analysis, we copy just the one field to the composite image and use it from there. This naturally breaks the array of initializer function pointers as these are not directly visible to the dependency analysis.

I believe that, on top of this functional error, it is wasteful - as we retain the RVA fields in the original component assemblies and we always load the component assembly before loading the composite image, we can easily access the RVA fields in the original locations in the component assemblies. That can be done in two ways:

1) [Easier and somewhat less performant] Introduce a new fixup with signature involving a module and RVA field row index that would make the CoreCLR runtime return the address of the RVA field in the ECMA RVA field metadata table in the given module.

2) [Harder and somewhat more performant] Introduce a new fixup returning the address of a given component module and make JIT emit the RVA field access as a sum of the component module base and module-relative RVA of the RVA field. The catch is that it would introduce the first dependency of composite image build on rewriting of the component assemblies that may alter the RVA field addresses.

/cc @dotnet/crossgen-contrib

### PR DESCRIPTION
**Pull request by trylek**
The pre-existing behavior was copying all RVA fields in single-file builds and only selectively copying explicitly referenced fields in composite builds. This has bitten us in WPF where Managed C++ emits an array of early initializers that are marked by an initial and final RVA field. By only selectively copying those two without the remaining entries in-between we end up crashing later on as the app is not fully initialized.

Based on David Wrighton's advice I have kept the logic for copying RVA fields in case of array initializers that seem to be hot in terms of performance. For the remaining field access I have ended up constructing a new precode fixup RVA_FIELD_ADDRESS for this purpose.

Fixes: #78723

Thanks

Tomas

/cc @dotnet/crossgen-contrib

### CODE REVIEW

File: src/coreclr/tools/Common/Internal/Runtime/ReadyToRunConstants.cs [hunk 1]
```diff
@@ -165,6 +165,8 @@ public enum ReadyToRunFixupKind
         Check_IL_Body              = 0x35, /* Check to see if an IL method is defined the same at runtime as at compile time. A failed match will cause code not to be used. */
         Verify_IL_Body             = 0x36, /* Verify an IL body is defined the same at compile time and runtime. A failed match will cause a hard runtime failure. */
 
+        RvaFieldAddress            = 0x37, /* Used in Crossgen2 to address RVA fields in their original MSIL images */
```
Comment (jkotas) [inline src/coreclr/tools/Common/Internal/Runtime/ReadyToRunConstants.cs:168]: Can we just use existing `FieldAddress` fixup for this?

Comment (trylek) [reply src/coreclr/tools/Common/Internal/Runtime/ReadyToRunConstants.cs:168]: I hoped we could but it looks like <code>FieldAddress</code> is specific to instance fields and cannot be used as a precode. The newly introduced fixup is the most similar to <code>StaticFieldAddress</code> but that one does something weird around storing the result next to the fixup cell, I guess that's something specific to runtime JIT behavior.

Comment (trylek) [reply src/coreclr/tools/Common/Internal/Runtime/ReadyToRunConstants.cs:168]: Please see

https://github.com/dotnet/runtime/blob/f924d6b5f69792f33a507b47a1fc870a185ad638/src/coreclr/vm/jitinterface.cpp#L13825

Comment (jkotas) [reply src/coreclr/tools/Common/Internal/Runtime/ReadyToRunConstants.cs:168]: I do not see the problem. The comment on `FieldAddress` says that it is for static fields:

FieldAddress = 0x20, // For accessing a cross-module static fields

If FieldAddress cannot be used as precode fixup, we can make it usable as precode fixup. We have other fixups like that. The encoding is designed to allow the same `ReadyToRunFixupKind` to be used in different modes.

Comment (trylek) [reply src/coreclr/tools/Common/Internal/Runtime/ReadyToRunConstants.cs:168]: OK, thanks for the feedback, I'll take look into making <code>FieldAddress</code> work for this purpose.

Comment (jkotas) [reply src/coreclr/tools/Common/Internal/Runtime/ReadyToRunConstants.cs:168]: > Please see
> https://github.com/dotnet/runtime/blob/f924d6b5f69792f33a507b47a1fc870a185ad638/src/coreclr/vm/jitinterface.cpp#L13825

You can delete `ENCODE_STATIC_FIELD_ADDRESS` while you are on it. It looks like a left-over from fragile NGen.

Comment (trylek) [reply src/coreclr/tools/Common/Internal/Runtime/ReadyToRunConstants.cs]: Fixed in 2nd commit, thanks for the suggestions!

File: src/coreclr/inc/corcompile.h [hunk 2]
```diff
@@ -161,10 +161,10 @@ enum CORCOMPILE_FIXUP_BLOB_KIND
 
     ENCODE_CHECK_IL_BODY,                           /* Check to see if an IL method is defined the same at runtime as at compile time. A failed match will cause code not to be used. */
     ENCODE_VERIFY_IL_BODY,                          /* Verify an IL body is defined the same at compile time and runtime. A failed match will cause a hard runtime failure. */
-
+    
     ENCODE_MODULE_HANDLE                = 0x50,     /* Module token */
-    ENCODE_STATIC_FIELD_ADDRESS,                    /* For accessing a static field */
-    ENCODE_MODULE_ID_FOR_GENERIC_STATICS,           /* For accessing static fields */
+    // obsolete: ENCODE_STATIC_FIELD_ADDRESS = 0x51, /* For accessing a static field */
+    ENCODE_MODULE_ID_FOR_GENERIC_STATICS = 0x52,    /* For accessing static fields */
```
Comment (jkotas) [inline src/coreclr/inc/corcompile.h:167]:
```suggestion
    ENCODE_MODULE_ID_FOR_GENERIC_STATICS, /* For accessing static fields */
```
These are not part of the stable R2R format. They should be all deleted (it can be separate change).

File: src/coreclr/inc/corcompile.h [hunk 3]
```diff
@@ -161,9 +161,8 @@ enum CORCOMPILE_FIXUP_BLOB_KIND
 
     ENCODE_CHECK_IL_BODY,                           /* Check to see if an IL method is defined the same at runtime as at compile time. A failed match will cause code not to be used. */
     ENCODE_VERIFY_IL_BODY,                          /* Verify an IL body is defined the same at compile time and runtime. A failed match will cause a hard runtime failure. */
-
+
```
Comment (jkotas) [inline src/coreclr/inc/corcompile.h:164]:
```suggestion

```

File: src/coreclr/inc/corcompile.h [hunk 4]
```diff
@@ -161,9 +161,7 @@ enum CORCOMPILE_FIXUP_BLOB_KIND
 
     ENCODE_CHECK_IL_BODY,                           /* Check to see if an IL method is defined the same at runtime as at compile time. A failed match will cause code not to be used. */
     ENCODE_VERIFY_IL_BODY,                          /* Verify an IL body is defined the same at compile time and runtime. A failed match will cause a hard runtime failure. */
```
Comment (jkotas) [inline src/coreclr/inc/corcompile.h:163]:
```suggestion
    ENCODE_VERIFY_IL_BODY,                          /* Verify an IL body is defined the same at compile time and runtime. A failed match will cause a hard runtime failure. */

```

**Review by jkotas — APPROVED** [review]
LGTM!

**Comment by trylek** [comment]
The outerloop failure is known, https://github.com/dotnet/runtime/issues/85663, merging in. I'll be happy to address any additional feedback in a follow-up change. I'll also put up a PR for blocking the test in issues.targets to make outerloop clean again.
