### PR TITLE
[wasm][debugger] Fix exceptions on eval

### LINKED ISSUE #61665: [wasm][debugger] Handle exceptions while evaluating expressions
Look at @radical comments in this PR https://github.com/dotnet/runtime/pull/61470 and fix it.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes #61665.

- Added a mechanism that allows us to show some exceptions (of ReturnAsErrorException type) to users.
- Divided exceptions on script evaluation into 2 categories: thrown by user's error inside the script (compilation error) and all the other exceptions that should be hidden and are for our info only.
- Removes *IsErr* property from result. Now only *IsOk* can be used to determine if Result has error or not.

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 1]
```diff
@@ -435,16 +439,29 @@ public ReturnAsErrorException(JObject error)
...
+                    exceptionDetails = new
+                    {
+                        exception = result,
+                        stackTrace = StackTrace
+                    }
+                }),
+                surfaceError: true); ;
+        }
+
+        public void UpdateStakTrace()
```
Comment (lewing) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:462]:
```suggestion
        public void UpdateStackTrace()
```

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 2]
```diff
@@ -1009,6 +1009,10 @@ public object ToScriptSource(int executionContextId, object executionContextAuxD
                 executionContextId,
                 executionContextAuxData,
                 //hash:  should be the v8 hash algo, managed implementation is pending
+                isLiveEdit = false,
```
Comment (lewing) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:1012]: The changes here look unrelated?

**Review by lewing — COMMENTED** [review]
A couple of issues.  I think we might want to see if we can clean up the error result handling a bit too.

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs (hunk 2 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs]: Yes, I checked and without sending this info the exceptions work as desired as well. Removing.

**Review by lewing — APPROVED** [review]

**Comment by radical** [comment]
Can you share how it looks different in practice?
1. how do the errors show up now, compared to earlier? For the user, and in the log
2. How does the stack trace show up for the user?

**Comment by ilonatommy** [comment]
> Can you share how it looks different in practice?
> 
> 1. how do the errors show up now, compared to earlier? 
> a) For the user:

Sure. So before there was no exception information shown, here we break and evaluate *sda* variable that does not exist and we got nothing after hovering over the <not available> text.
image

How it looks like now - evaluation of non existing variable + hovering over results in showing a window with exception details:
image

This PR has no effect on user defined exceptions.

> b) and in the log:

no change, before and after applying the PR:
image

> 2. How does the stack trace show up for the user?

No change as well,
image

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 3]
```diff
@@ -390,17 +390,21 @@ internal static async Task<JObject> CompileAndRunTheExpression(string expression
...
 
                 var state = await newScript.RunAsync(cancellationToken: token);
-
                 return JObject.FromObject(ConvertCSharpToJSType(state.ReturnValue, state.ReturnValue.GetType()));
             }
-            catch (Exception)
+            catch (CompilationErrorException cee)
             {
-                throw new ReturnAsErrorException($"Cannot evaluate '{expression}'.", "CompilationError");
+                throw new ReturnAsErrorException($"Running expression: {expression} failed with error: {cee.Message}. Check if the expression is correct.", "CompilationError");
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:403]: I think we can use the simpler message here - `Cannot evaluate '{expression}': {cee.Message}`

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 4]
```diff
@@ -435,16 +439,28 @@ public ReturnAsErrorException(JObject error)
...
+                        exception = result,
+                        stackTrace = StackTrace
+                    }
+                }));
+        }
+
+        public void UpdateStackTrace()
+        {
+            Error.Value["exceptionDetails"]["stackTrace"] = StackTrace;
         }
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:464]: That's a great idea, thank you

File: src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs [hunk 5]
```diff
@@ -128,39 +128,40 @@ public struct Result
         public bool IsOk => Value != null;
         public bool IsErr => Error != null;
 
-        private Result(JObject result, JObject error)
+        private Result(JObject resultOrError, bool isError, JObject error = null)
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:131]: Actually I leaved it only because of the FromJson function:
```
        public static Result FromJson(JObject obj)
        {
            //Log ("protocol", $"from result: {obj}");
            return new Result(obj["result"] as JObject, false, obj["error"] as JObject);
        }
```
that I did not want to change but now I did it and the version with 2 arguments works equally good. Thanks!
