### PR TITLE
Use CopyContext to restore saved context on X86

### LINKED ISSUE #65292: [x86] SequenceEqual returns false for equal spans
Run: [runtime-libraries-coreclr outerloop 20220213.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1610237&view=ms.vss-test-web.build-test-results-tab&runId=44860608&paneView=debug&resultId=102808)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.IO.Tests.UnseekableDeviceFileStreamConnectedConformanceTests.ReadWrite_Success_Large(mode: AsyncMemory, writeSize: 10485760, startWithFlush: True)
- System.IO.Tests.AnonymousPipeFileStreamConnectedConformanceTests.ReadWrite_Success_Large(mode: SyncArray, writeSize: 10485760, startWithFlush: False)

```
**Error message:**
```
Showing first 10 differences
Total number of differences: 0 out of 10485760


Stack trace
   at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 473
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1765
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success_Large(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1719
--- End of stack trace from previous location ---
```

|Build|Kind|Start Time|
|---|---|---|
[1612202](https://dev.azure.com/dnceng/public/_build/results?buildId=1612202)|Rolling|2022-14-02|
[1613425](https://dev.azure.com/dnceng/public/_build/results?buildId=1613425)|Rolling|2022-15-02|
[1616198](https://dev.azure.com/dnceng/public/_build/results?buildId=1616198)|Rolling|2022-16-02|
[1616876](https://dev.azure.com/dnceng/public/_build/results?buildId=1616876)|Rolling|2022-16-02|
[1617545](https://dev.azure.com/dnceng/public/_build/results?buildId=1617545)|Rolling|2022-17-02|
[1618267](https://dev.azure.com/dnceng/public/_build/results?buildId=1618267)|Rolling|2022-17-02|

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: https://github.com/dotnet/runtime/issues/65292

### CODE REVIEW

**Comment by jkotas** [comment]
Any chance we can switch to `RtlRestoreContext` on x86 and make it more similar to how other platforms work?

**Comment by adamsitnik** [comment]
@VSadov I have built your PR and I can't repro the issue anymore (AMD, x86, Win11) 👍

**Comment by filipnavara** [comment]
I've backported the fix on top of release/6.0 branch and built it locally. I can also confirm that the issue no longer reproduces.

File: src/coreclr/vm/threadsuspend.cpp [hunk 1]
```diff
@@ -2577,7 +2577,13 @@ int RedirectedHandledJITCaseExceptionFilter(
...
 
     // Copy the saved context record into the EH context;
-    ReplaceExceptionContextRecord(pExcepPtrs->ContextRecord, pCtx);
+    // NB: cannot use ReplaceExceptionContextRecord here.
+    //     these contexts may contain extended registers and may have different format
+    //     for reasons such as alignment or context compaction
+    //
+    // REVIEW: CopyContext may fail. in theory. How should we handle that? FailFast?
+    CONTEXT* pTarget = pExcepPtrs->ContextRecord;
+    CopyContext(pTarget, pTarget->ContextFlags, pCtx);
```
Comment (janvorli) [inline src/coreclr/vm/threadsuspend.cpp:2586]: It seems it would make sense to modify the ReplaceExceptionContextRecord to use CopyContext instead.

Comment (VSadov) [reply src/coreclr/vm/threadsuspend.cpp:2586]: I was not sure if `ReplaceExceptionContextRecord` can be used outside of Windows. Can it?

**Comment by VSadov** [comment]
> Any chance we can switch to RtlRestoreContext on x86 and make it more similar to how other platforms work?

I think it is worth trying. The reson for current approach could be compatibility with no longer interesting platforms. (Win95?)

**Comment by filipnavara** [comment]
> Any chance we can switch to `RtlRestoreContext` on x86 and make it more similar to how other platforms work?

Seems reasonable going forward but I assume that this will need servicing for 6.0 and it looks like too big of a change for backporting?

File: src/coreclr/vm/threadsuspend.cpp (hunk 1 above)
Comment (VSadov) [reply src/coreclr/vm/threadsuspend.cpp:2586]: I also wonder if `ReplaceExceptionContextRecord` needs to handle extended context at all if suspension resume switches completely to the `RtlRestoreContext` plan.

**Comment by VSadov** [comment]
I have looked into unifying on use of `RtlRestoreContext` and it is promising, but not completely straightforward. 

The level of API that we are targeting does not include `RtlRestoreContext` on x86. We would have to dynamically query/bind to it and use if present. We may also have to keep the old codepath, unless we find some other pattern that is guaranteed to work on all platforms that we support.

I think we might want to take the current fix first though - to unblock clean CI, since the issue causes random failures.

File: src/coreclr/vm/threadsuspend.cpp (hunk 1 above)
Comment (VSadov) [reply src/coreclr/vm/threadsuspend.cpp]: > I was not sure if ReplaceExceptionContextRecord can be used outside of Windows. Can it?

I have tried moving the fix into `ReplaceExceptionContextRecord ` and that did not build on Linux, so that answer this.

**Comment by VSadov** [comment]
CC: @davidwrighton

File: src/coreclr/vm/threadsuspend.cpp [hunk 2]
```diff
@@ -2577,7 +2577,13 @@ int RedirectedHandledJITCaseExceptionFilter(
     pFrame->Pop();
 
     // Copy the saved context record into the EH context;
-    ReplaceExceptionContextRecord(pExcepPtrs->ContextRecord, pCtx);
+    // NB: cannot use ReplaceExceptionContextRecord here.
+    //     these contexts may contain extended registers and may have different format
+    //     for reasons such as alignment or context compaction
+    //
+    // REVIEW: CopyContext may fail. in theory. How should we handle that? FailFast?
```
Comment (davidwrighton) [inline src/coreclr/vm/threadsuspend.cpp:2584]: Yes, FailFast is appropriate for failure here.

Comment (davidwrighton) [reply src/coreclr/vm/threadsuspend.cpp:2584]: However, be careful calling new functions from this function. If they have destructors and the compiler chooses to inline them, the runtime will start crashing.

**Review by davidwrighton — APPROVED** [review]
As a quick fix to unblock testing, I approve of this, but I'm not confident this is the right long term fix. IMO, we should change to `RtlRestoreContext` on operating systems that support it, and keep the existing horrifying logic for the older OS. Then of course, once we have that, we should backport the fix to servicing.

File: src/coreclr/vm/threadsuspend.cpp (hunk 2 above)
Comment (VSadov) [reply src/coreclr/vm/threadsuspend.cpp:2584]: I was thinking of code like:
```c
            if (!CopyContext(pTarget, pTarget->ContextFlags, pCtx))
            {
                STRESS_LOG1(LF_EH, LL_ERROR, "ERROR: Could not set context record, lastError = 0x%x\n", GetLastError());
                ThrowLastError();
            }
```

Would that fit here?

It is highly unlikely that copy would fail, but it'd be nice to have some diagnostics if that start happenning.

File: src/coreclr/vm/threadsuspend.cpp [hunk 3]
```diff
@@ -2509,6 +2509,18 @@ void RedirectedThreadFrame::ExceptionUnwind()
 #ifndef TARGET_UNIX
 
 #ifdef TARGET_X86
+
+// a helper to make sure these calls are not inlined into a filter function.
+// in particular we do not want a possibility of inlined destructor calls.
```
Comment (jkotas) [inline src/coreclr/vm/threadsuspend.cpp:2514]: This should not be a concern once you change it to `EEPOLICY_HANDLE_FATAL_ERROR`. `EEPOLICY_HANDLE_FATAL_ERROR` is non-inlineable.

**Comment by jkotas** [comment]
> As a quick fix to unblock testing, I approve of this, but I'm not confident this is the right long term fix.

+1. It is likely that the OS treatment of context will evolving over time that is going to break the exception filter hack again.

**Comment by VSadov** [comment]
> It is likely that the OS treatment of context will evolving over time that is going to break the exception filter hack again.

Agree on this as well.

**Comment by VSadov** [comment]
Thanks!!!
