### PR TITLE
[coreclr] Fix LoadLibraryInitializer test

### LINKED ISSUE #124899: [coreclr] LoadLibraryInitializer throws exception
Reproduction:
Run Wasm.Build.Tests.LibraryInitializerTests (currently disabled in eng/testing/scenarios/BuildWasmAppsJobsListCLR.txt)

error:
```
          Waiting for additional 10secs to see if any errors are reported
          [error] DOTNET: Exiting during runtime startup:  Error thrown from library initializer
          [info] DOTNET: Aborting startup, reason: Error: Error thrown from library initializer
          [ERROR] PageError: Error: Error thrown from library initializer
          [ERROR] PageError: Error: Error thrown from library initializer
```

<details>
 Wasm.Build.Tests.LibraryInitializerTests.AbortStartupOnError [FAIL]
        System.Exception : Timed out after 10s waiting for 'WASM EXIT' message
        Stack Trace:
          C:\Users\itomkowicz\repros\runtime2\src\mono\wasm\Wasm.Build.Tests\BrowserRunner.cs(234,0): at Wasm.Build.Tests.BrowserRunner.WaitForExitMessageAsync(TimeSpan timeout)
             at System.Runtime.CompilerServices.AsyncHelpers.RuntimeAsyncTask`1.DispatchContinuations()
          --- End of stack trace from previous location ---
          C:\Users\itomkowicz\repros\runtime2\src\mono\wasm\Wasm.Build.Tests\Templates\WasmTemplateTestsBase.cs(431,0): at Wasm.Build.Tests.WasmTemplateTestsBase.BrowserRun(ToolCommand cmd, String runArgs, RunOptions runOptions)
          --- End of stack trace from previous location ---
          C:\Users\itomkowicz\repros\runtime2\src\mono\wasm\Wasm.Build.Tests\Templates\WasmTemplateTestsBase.cs(435,0): at Wasm.Build.Tests.WasmTemplateTestsBase.BrowserRun(ToolCommand cmd, String runArgs, RunOptions runOptions)
             at System.Runtime.CompilerServices.AsyncHelpers.RuntimeAsyncTask`1.DispatchContinuations()
          --- End of stack trace from previous location ---
          C:\Users\itomkowicz\repros\runtime2\src\mono\wasm\Wasm.Build.Tests\Templates\WasmTemplateTestsBase.cs(389,0): at Wasm.Build.Tests.WasmTemplateTestsBase.BrowserRunTest(String runArgs, String workingDirectory, RunOptions runOptions)
             at System.Runtime.CompilerServices.AsyncHelpers.RuntimeAsyncTask`1.DispatchContinuations()
          --- End of stack trace from previous location ---
          --- End of stack trace from previous location ---
        Output:
          
          ** -------- publish -------- **
          
          Binlog path: C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\xharness-output\logs\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\WasmBasicTestApp-publish.binlog
          [] Executing (Captured Output) - C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none\dotnet.exe publish -bl:C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\xharness-output\logs\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\WasmBasicTestApp-publish.binlog -p:Configuration=Debug -nr:false -p:CompressionEnabled=false -p:WasmEnableHotReload=false  -  in pwd C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\App
          	[DOTNET_ROOT] = C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none
          	[DOTNET_INSTALL_DIR] = C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none
          	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
          	[PATH] = C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none;C:\Users\itomkowicz\repros\runtime2\.dotnet;C:\Program Files\PowerShell\7;c:\Users\itomkowicz\AppData\Roaming\Code\User\globalStorage\github.copilot-chat\debugCommand;c:\Users\itomkowicz\AppData\Roaming\Code\User\globalStorage\github.copilot-chat\copilotCli;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Azure Dev CLI;C:\Program Files\GitHub CLI\;C:\Users\vmadmin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\.tools\dotnet;C:\.tools\.npm-global;C:\Users\vmadmin\.dotnet\tools;C:\Program Files\NuGet;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft Dev Box Agent\Scripts;C:\Program Files\dotnet\;C:\Program Files\CMake\bin;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Users\itomkowicz\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\itomkowicz\AppData\Local\Programs\Python\Python311\;C:\Users\itomkowicz\AppData\Local\Microsoft\WindowsApps;C:\Program Files\ninja;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64;C:\Users\itomkowicz\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\v8;C:\Users\itomkowicz\AppData\Local\Microsoft\WinGet\Links;C:\Users\itomkowicz\AppData\Roaming\npm;C:\Users\itomkowicz\.dotnet\tools
          	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
          	[WasmEnableWebCil] = false
          	[WasmTestSupport] = true
          	[WasmTestExitOnUnhandledError] = true
          	[WasmTestLogExitCode] = true
          	[NUGET_PACKAGES] = C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\nuget\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg
          	[TreatPreviousAsCurrent] = false
          [] 
          []   Determining projects to restore...
          []   Restored C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\ResourceLibrary\ResourceLibrary.csproj (in 122 ms).
          []   Restored C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\LazyLibrary\LazyLibrary.csproj (in 122 ms).
          []   Restored C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\Json\Json.csproj (in 122 ms).
          []   Restored C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\App\WasmBasicTestApp.csproj (in 2.89 sec).
          [] C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none\sdk\11.0.100-preview.3.26124.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(383,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\App\WasmBasicTestApp.csproj]
          [] C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none\sdk\11.0.100-preview.3.26124.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(383,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\LazyLibrary\LazyLibrary.csproj]
          [] C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none\sdk\11.0.100-preview.3.26124.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(383,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\Json\Json.csproj]
          []   Json -> C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\Json\bin\Debug\net11.0\Json.dll
          []   LazyLibrary -> C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\LazyLibrary\bin\Debug\net11.0\browser-wasm\LazyLibrary.dll
          []   ResourceLibrary -> C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\ResourceLibrary\bin\Debug\net11.0\ResourceLibrary.dll
          []   WasmBasicTestApp -> C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\App\bin\Debug\net11.0\WasmBasicTestApp.dll
          []   ** MicrosoftNetCoreAppRuntimePackDir : 'C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\nuget\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\microsoft.netcore.app.runtime.browser-wasm\11.0.0-dev'
          []   Optimizing assemblies for size. This process might take a while.
          []   Publishing without optimizations. Although it's optional for Blazor, we strongly recommend using `wasm-tools` workload! You can install it by running `dotnet workload install wasm-tools` from the command line.
          []   WasmBasicTestApp -> C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\App\bin\Debug\net11.0\publish\
          Replacing dotnet process output with messages from binlog
          [] Executing - C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none\dotnet.exe xharness wasm webserver --app=. --web-server-use-default-files  in pwd C:\Users\itomkowicz\repros\runtime2\artifacts\bin\Wasm.Build.Tests\Release\net11.0\win-x64\wbt artifacts\LibraryInitializerTests_AbortStartupOnError_Debug_False_13b0pa24_xkg\App\bin\Debug\net11.0\publish\wwwroot
          	[DOTNET_ROOT] = C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none
          	[DOTNET_INSTALL_DIR] = C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none
          	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
          	[PATH] = C:\Users\itomkowicz\repros\runtime2\artifacts\bin\dotnet-none;C:\Users\itomkowicz\repros\runtime2\.dotnet;C:\Program Files\PowerShell\7;c:\Users\itomkowicz\AppData\Roaming\Code\User\globalStorage\github.copilot-chat\debugCommand;c:\Users\itomkowicz\AppData\Roaming\Code\User\globalStorage\github.copilot-chat\copilotCli;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Azure Dev CLI;C:\Program Files\GitHub CLI\;C:\Users\vmadmin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\.tools\dotnet;C:\.tools\.npm-global;C:\Users\vmadmin\.dotnet\tools;C:\Program Files\NuGet;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft Dev Box Agent\Scripts;C:\Program Files\dotnet\;C:\Program Files\CMake\bin;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Users\itomkowicz\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\itomkowicz\AppData\Local\Programs\Python\Python311\;C:\Users\itomkowicz\AppData\Local\Microsoft\WindowsApps;C:\Program Files\ninja;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64;C:\Users\itomkowicz\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\v8;C:\Users\itomkowicz\AppData\Local\Microsoft\WinGet\Links;C:\Users\itomkowicz\AppData\Roaming\npm;C:\Users\itomkowicz\.dotnet\tools
          	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
          	[WasmEnableWebCil] = false
          	[WasmTestSupport] = true
          	[WasmTestExitOnUnhandledError] = true
          	[WasmTestLogExitCode] = true
          [] [11.0.0-prerelease.26064.3+31e0b8e08f57890f7b7004b93361d69cd4b21079] XHarness command issued: wasm webserver --app=. --web-server-use-default-files
          [] info: Now listening on: http://127.0.0.1:50408
          Launching chrome ('C:\Program Files\Google\Chrome\Application\chrome.exe') via playwright with args = --explicitly-allowed-ports=50408,--ignore-certificate-errors,--lang=en-US,--headless
          Waiting for page to load
          Waiting for additional 10secs to see if any errors are reported
          [error] DOTNET: Exiting during runtime startup:  Error thrown from library initializer
          [info] DOTNET: Aborting startup, reason: Error: Error thrown from library initializer
          [ERROR] PageError: Error: Error thrown from library initializer
          [ERROR] PageError: Error: Error thrown from library initializer
          Browser has been disconnected
</details>

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/124899.

The CoreCLR WASM loader had several gaps preventing library initializers from working correctly. This PR fixes the loader and adds a CoreCLR-specific test.

  Loader changes (run.ts, exit.ts)

   1. run.ts: `invokeLibraryInitializers` now takes an `args` parameter — passes `loaderConfig` for `onRuntimeConfigLoaded` and `dotnetApi` for `onRuntimeReady` (which has `getAssemblyExports`/`getConfig`, matching what Mono does)
   2. exit.ts: Restored `runtimeState.creatingRuntime` check (needed because `dotnetReady` is already true when `onRuntimeReady` throws)
   3. run.ts: Call `onRuntimeReady` on all library initializers (both `modulesAfterConfigLoaded` and `modulesAfterRuntimeReady`), since the SDK only lists lib modules in `modulesAfterConfigLoaded`
   4. run.ts: Wrap library initializer errors with script name in a shared `invokeLibraryInitializers` helper

  Test changes

   - Made `AbortStartupOnError` Mono-only; added `AbortStartupOnError_CoreCLR` that throws in `onRuntimeReady` and checks for the abort message with script name
   - Added `throwErrorOnReady` query param support to WasmBasicTestApp.lib.module.js
   - Added `IsCoreClrRuntime` helper to `BuildTestBase.cs`
   - Added `LibraryInitializerTests` to BuildWasmAppsJobsListCoreCLR.txt to re-enable it

### CODE REVIEW

File: src/native/libs/Common/JavaScript/loader/run.ts [hunk 1]
```diff
@@ -14,6 +14,18 @@ import { validateEngineFeatures } from "./bootstrap";
 
 const runMainPromiseController = createPromiseCompletionSource<number>();
 
+async function callLibraryInitializers(modules: JsModuleExports[], resources: any[], methodName: string, args: any): Promise<void> {
+    for (let i = 0; i < modules.length; i++) {
+        try {
+            await (modules[i] as any)[methodName]?.(args);
```
Comment (pavelsavara) [inline src/native/libs/Common/JavaScript/loader/run.ts]: this is making the initializers to run sequentially, not in parallel. They are blocking startup already (which I hate).

@maraf do we really need it sequential ?

**Review by pavelsavara — APPROVED** [review]

File: src/native/libs/Common/JavaScript/loader/run.ts (hunk 1 above)
Comment (maraf) [reply src/native/libs/Common/JavaScript/loader/run.ts]: I don't think we need them sequential.

I understand you hate anything that is happening during startup, but it's an important hook that allows to modify the startup. We are not advertising it as everything should be done with them, but it has it's use-cases.

File: src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs [hunk 2]
```diff
@@ -64,6 +64,7 @@ public abstract class BuildTestBase : IClassFixture<SharedBuildPerTestClassFixtu
         public static bool IsNotUsingWorkloads => !s_buildEnv.IsWorkload;
         public static bool IsWorkloadWithMultiThreadingForDefaultFramework => s_buildEnv.IsWorkloadWithMultiThreadingForDefaultFramework;
         public static bool IsMonoRuntime => s_buildEnv.IsMonoRuntime;
+        public static bool IsCoreClrRuntime => s_buildEnv.IsCoreClrRuntime;
```
Comment (maraf) [inline src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs:67]: I think we already have some places that check for RuntimeFlavor. Could we unify them to use this flag?

File: src/mono/wasm/Wasm.Build.Tests/LibraryInitializerTests.cs [hunk 3]
```diff
@@ -55,4 +58,22 @@ public async Task AbortStartupOnError()
         RunResult result = await RunForPublishWithWebServer(options);
         Assert.True(result.ConsoleOutput.Any(m => AbortStartupOnErrorRegex.IsMatch(m)), "The library initializer test didn't emit expected error message");
     }
+
+    [ConditionalFact(typeof(BuildTestBase), nameof(IsCoreClrRuntime)), TestCategory("bundler-friendly")]
+    public async Task AbortStartupOnError_CoreCLR()
```
Comment (maraf) [inline src/mono/wasm/Wasm.Build.Tests/LibraryInitializerTests.cs]: Could we just parametrize the test we already have instead of creating a separate one for CoreCLR? Or is it too different?

**Review by maraf — APPROVED** [review]

File: src/native/libs/Common/JavaScript/loader/run.ts [hunk 4]
```diff
@@ -14,6 +14,18 @@ import { validateEngineFeatures } from "./bootstrap";
...
+async function callLibraryInitializers(modules: JsModuleExports[], resources: any[], methodName: string, args: any): Promise<void> {
+    await Promise.all(modules.map(async (module, i) => {
+        try {
+            await (module as any)[methodName]?.(args);
+        } catch (err) {
+            const name = (resources[i] as any).name || "unknown";
+            const message = err instanceof Error ? err.message : String(err);
+            throw new Error(`Failed to invoke '${methodName}' on library initializer '${name}': ${message}`, { cause: err });
+        }
+    }));
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/native/libs/Common/JavaScript/loader/run.ts:26]: It's in line with https://github.com/dotnet/runtime/pull/125176#discussion_r2885518882.

File: src/native/libs/Common/JavaScript/loader/run.ts [hunk 5]
```diff
@@ -95,12 +107,14 @@ export async function createRuntime(downloadOnly: boolean): Promise<any> {
...
-        for (const afterRuntimeReadyModule of modulesAfterRuntimeReady) {
-            await afterRuntimeReadyModule.onRuntimeReady?.(loaderConfig);
+        if (!downloadOnly) {
+            if (typeof Module.onDotnetReady === "function") {
+                await Module.onDotnetReady();
+            }
+            const modulesAfterRuntimeReady = await modulesAfterRuntimeReadyPromise;
+            const allRuntimeReadyModules = [...modulesAfterConfigLoaded, ...modulesAfterRuntimeReady];
+            const allRuntimeReadyResources = [...afterConfigLoadedResources, ...afterRuntimeReadyResources];
+            await callLibraryInitializers(allRuntimeReadyModules, allRuntimeReadyResources, "onRuntimeReady", dotnetApi);
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/native/libs/Common/JavaScript/loader/run.ts:117]: Duplicate calls would be called rather by a user misconfiguration than SDK itself. Skipping.
