### PR TITLE
[debugger] Support step into a tail call

### LINKED ISSUE #110441: Cannot step into a Tail Call
### Description

A customer ships a compiler that uses tail calls and when their customers are debugging the app generated by this compiler and try to step into a tail call and it behaves like a resume.

### Reproduction Steps

Get this code:
https://github.com/dotnet/runtime/blob/e99557baffbe864d624cc1c95c9cbf2eefae684f/src/tests/JIT/Regression/JitBlue/Runtime_39581/Runtime_39581.il 
Add a breakpoint on line 94 and try to step into.

### Expected behavior

Pause on line 60.

### Actual behavior

Resume.

### Regression?

It worked before .NET 6.

### Known Workarounds

Remove the tailcall usage.

### Configuration

.NET 8.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by thaystg**
I got this test case:
https://github.com/dotnet/runtime/blob/80d8c46f071d9e3d8ede2d98cb2c918d9b0d7d31/src/tests/JIT/Regression/JitBlue/Runtime_39581/Runtime_39581.il
Added a breakpoint on line 93 and tried to step into to Runtime_39581.Program::Callee and it behaves like a step over.
With this change the step into works correctly.

Fixes https://github.com/dotnet/runtime/issues/110441

### CODE REVIEW

**Review by mikem8361 — APPROVED** [review]
I'm not an expert on this code but it looks good to me.

File: src/coreclr/debug/shared/dbgtransportsession.cpp [hunk 1]
```diff
@@ -2203,6 +2203,7 @@ DWORD DbgTransportSession::GetEventSize(DebuggerIPCEvent *pEvent)
     case DB_IPCE_AFTER_GARBAGE_COLLECTION:
     case DB_IPCE_DISABLE_OPTS_RESULT:
     case DB_IPCE_CATCH_HANDLER_FOUND_RESULT:
+    case DB_IPCE_SET_ENABLE_CUSTOM_NOTIFICATION_RESULT:
```
Comment (tommcdon) [inline src/coreclr/debug/shared/dbgtransportsession.cpp:2206]: Is this intentionally part of this PR?

File: src/coreclr/debug/ee/controller.cpp [hunk 2]
```diff
@@ -5826,6 +5826,23 @@ static bool IsTailCallThatReturns(const BYTE * ip, ControllerStackInfo* info)
...
+    TraceDestination trace;
+    if (!g_pEEInterface->TraceStub(ip, &trace) || !g_pEEInterface->FollowTrace(&trace))
+    {
+        return false;
+    }
+
+    MethodDesc* pTargetMD =
+        trace.GetTraceType() == TRACE_UNJITTED_METHOD
+        ? trace.GetMethodDesc()
+        : g_pEEInterface->GetNativeCodeMethodDesc(trace.GetAddress());
```
Comment (tommcdon) [inline src/coreclr/debug/ee/controller.cpp:5840]: Very minor nit: this looks like a copy of the code in `IsTailCallThatReturns`, can we consolidate this into a shared function?

https://github.com/dotnet/runtime/blob/ecefb5e0412bd05841012efe3d7fd914c400343a/src/coreclr/debug/ee/controller.cpp#L5642-L5651

**Review by tommcdon — APPROVED** [review]
This looks good to me! Left a couple comments for your review.

File: src/coreclr/debug/shared/dbgtransportsession.cpp (hunk 1 above)
Comment (thaystg) [reply src/coreclr/debug/shared/dbgtransportsession.cpp:2206]: This was causing a boring assertion in the debug build, I can open a separate PR with this fix but it can be here together.

Comment (tommcdon) [reply src/coreclr/debug/shared/dbgtransportsession.cpp:2206]: I don't have a strong preference.  Would we want to include that changes as part of a backport to .NET servicing?

Comment (thaystg) [reply src/coreclr/debug/shared/dbgtransportsession.cpp:2206]: Ah, okay, I will remove it, it will be better for backporting only the change.

File: src/coreclr/debug/ee/controller.cpp [hunk 3]
```diff
@@ -6039,6 +6056,11 @@ bool DebuggerStepper::TrapStep(ControllerStackInfo *info, bool in)
                     fCallingIntoFunclet = IsAddrWithinMethodIncludingFunclet(ji, info->m_activeFrame.md, walker.GetNextIP()) &&
                         ((CORDB_ADDRESS)(SIZE_T)walker.GetNextIP() != ji->m_addrOfCode);
 #endif
+                    if (in && IsStoreTailCallArgs(walker.GetNextIP()))
```
Comment (mikelle-rogers) [inline src/coreclr/debug/ee/controller.cpp:6059]: Nit: I am just wondering if you want to add some kind of comment regarding which case we are in. This function seems to have a comment about each case.

File: src/coreclr/debug/ee/controller.cpp [hunk 4]
```diff
@@ -25,6 +25,8 @@ const char *GetTType( TraceType tt);
 
 #define IsSingleStep(exception) ((exception) == EXCEPTION_SINGLE_STEP)
 
+#define TailCallThatReturns 1
+#define StoreTailCallArgs 2
```
Comment (tommcdon) [inline src/coreclr/debug/ee/controller.cpp:29]: nit: I suggest making these enum's and adding them to controller.h for consistency with the rest of the controller code.  for example:

```c++
enum TAILCALL_TYPE
{
    TAILCALL_ RETURNS               = 0x1
    TAILCALL_STORE_CALL_ARGS = 0x2
};
```

File: src/coreclr/debug/ee/controller.cpp [hunk 5]
```diff
@@ -5789,10 +5791,15 @@ static bool IsTailCallJitHelper(const BYTE * ip)
 // control flow will be a little peculiar in that the function will return
 // immediately, so we need special handling in the debugger for it. This
 // function detects that case to be used for those scenarios.
-static bool IsTailCallThatReturns(const BYTE * ip, ControllerStackInfo* info)
+static bool IsTailCall(const BYTE * ip, ControllerStackInfo* info, char type)
```
Comment (tommcdon) [inline src/coreclr/debug/ee/controller.cpp:5794]:
```suggestion
static bool IsTailCall(const BYTE * ip, ControllerStackInfo* info, TAILCALL_TYPE type)
```

File: src/coreclr/debug/ee/controller.cpp [hunk 6]
```diff
@@ -5789,10 +5791,15 @@ static bool IsTailCallJitHelper(const BYTE * ip)
...
 {
     MethodDesc* pTailCallDispatcherMD = TailCallHelp::GetTailCallDispatcherMD();
-    if (pTailCallDispatcherMD == NULL)
+    if (type != TailCallThatReturns && type != StoreTailCallArgs)
```
Comment (tommcdon) [inline src/coreclr/debug/ee/controller.cpp:5797]:
```suggestion
    if (type != TAILCALL_RETURNS && type != TAILCALL_STORE_CALL_ARGS)
```

File: src/coreclr/debug/ee/controller.cpp [hunk 7]
```diff
@@ -5789,10 +5791,15 @@ static bool IsTailCallJitHelper(const BYTE * ip)
...
+    {
+        return false;
+    }
+
+    if (pTailCallDispatcherMD == NULL && type == TailCallThatReturns)
```
Comment (tommcdon) [inline src/coreclr/debug/ee/controller.cpp:5802]:
```suggestion
    if (pTailCallDispatcherMD == NULL && type == TAILCALL_RETURNS)
```

File: src/coreclr/debug/ee/controller.cpp [hunk 8]
```diff
@@ -6072,7 +6069,7 @@ bool DebuggerStepper::TrapStep(ControllerStackInfo *info, bool in)
                     // is done by stepping out to the previous user function
                     // (non IL stub).
                     if ((fIsJump && !fCallingIntoFunclet) || IsTailCallJitHelper(walker.GetNextIP()) ||
-                        IsTailCallThatReturns(walker.GetNextIP(), info))
+                        IsTailCall(walker.GetNextIP(), info, TailCallThatReturns))
```
Comment (tommcdon) [inline src/coreclr/debug/ee/controller.cpp:6072]:
```suggestion
                        IsTailCall(walker.GetNextIP(), info, TAILCALL_RETURNS))
```

File: src/coreclr/debug/ee/controller.cpp [hunk 9]
```diff
@@ -6218,7 +6215,7 @@ bool DebuggerStepper::TrapStep(ControllerStackInfo *info, bool in)
                 return true;
             }
 
-            if (IsTailCallJitHelper(walker.GetNextIP()) || IsTailCallThatReturns(walker.GetNextIP(), info))
+            if (IsTailCallJitHelper(walker.GetNextIP()) || IsTailCall(walker.GetNextIP(), info, TailCallThatReturns))
```
Comment (tommcdon) [inline src/coreclr/debug/ee/controller.cpp:6218]:
```suggestion
            if (IsTailCallJitHelper(walker.GetNextIP()) || IsTailCall(walker.GetNextIP(), info, TAILCALL_RETURNS))
```

File: src/coreclr/debug/ee/controller.cpp [hunk 10]
```diff
@@ -6056,7 +6051,9 @@ bool DebuggerStepper::TrapStep(ControllerStackInfo *info, bool in)
                     fCallingIntoFunclet = IsAddrWithinMethodIncludingFunclet(ji, info->m_activeFrame.md, walker.GetNextIP()) &&
                         ((CORDB_ADDRESS)(SIZE_T)walker.GetNextIP() != ji->m_addrOfCode);
 #endif
-                    if (in && IsStoreTailCallArgs(walker.GetNextIP()))
+                    // If we are stepping into a tail call that uses the StoreTailCallArgs 
+                    // we need to enable the method enter, otherwise it behave like a resume
+                    if (in && IsTailCall(walker.GetNextIP(), info, StoreTailCallArgs))
```
Comment (tommcdon) [inline src/coreclr/debug/ee/controller.cpp:6056]:
```suggestion
                    if (in && IsTailCall(walker.GetNextIP(), info, TAILCALL_STORE_CALL_ARGS))
```

**Review by tommcdon — APPROVED** [review]
LGTM, thanks!!
