### PR TITLE
Fix deadlock when creating threads from ModuleInitializer in a shared library

### LINKED ISSUE #107699: [NativeAOT] possible deadlock due to InitializeRuntime reentrancy if ModuleInitializer launches threads.
While playing with alternatives for stress testing, I tried spawning a thread from a module initializer, that would do GC.Collect in a loop. 
Some tests (**but not all**, not sure why...) seems to hang: 
- InitializeRuntime calls module initializers, which is arbitrary app code.
- launching a thread waits for the thread to start running.
- to start running a thread needs to do reverse PInvoke, which spin-waits for InitializeRuntime to complete.

Perhaps we should finish runtime initialization before calling into module initializers?

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
The problem is that the first time we reverse p/invoke into an API in the shared library, we need to do two things: initialize runtime and run module initializers. Running module initializers is done as part of runtime initialization in the shared library case because it was convenient to do it there (in the EXE case, we run them after runtime initialization, right before Main).

The problem with running it as part of the runtime initialization is that the arbitrary user code can deadlock us (see the issues for stack).

This fixes the problem by attaching the newly created thread to the runtime before we do the reverse p/invoke. Since thread is already attached, we don't wait for runtime initialization. Waiting is unnecessary because the runtime needs to be really far along the initialization path if we got to a managed `Thread.Start` call.

Fixes #118773. Fixes #107699.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by VSadov** [comment]
> This also fixes a potential issue in the EXE case where threads created from module initializers could start running before we're finished running module initializers. Instead, this introduces a new opportunity for deadlocking :(.

I think also if a module initializer drops a finalizable object, finalizer thread may run without waiting. That is because we pre-attach the finalizer thread. Perhaps we should not. I do not think it is necessary to pre-attach.

File: src/coreclr/nativeaot/Runtime/thread.cpp [hunk 1]
```diff
@@ -1341,7 +1368,18 @@ FCIMPL1(void, RhpReversePInvoke, ReversePInvokeFrame * pFrame)
...
-    RhpReversePInvokeAttachOrTrapThread2(pFrame);
+    RhpReversePInvokeAttachOrTrapThread2(pFrame, true);
+}
+FCIMPLEND
+
+FCIMPL1(void, RhpReversePInvokeNoModuleInitializer, ReversePInvokeFrame * pFrame)
+{
+    Thread * pCurThread = ThreadStore::RawGetCurrentThread();
+    pFrame->m_savedThread = pCurThread;
+    if (pCurThread->InlineTryFastReversePInvoke(pFrame))
```
Comment (VSadov) [inline src/coreclr/nativeaot/Runtime/thread.cpp]: The Inline portion will always fail here since the thread is not supposed to be attached, right?

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 2]
```diff
@@ -3552,6 +3552,18 @@ private void getHelperFtn(CorInfoHelpFunc ftnNum, CORINFO_CONST_LOOKUP *pNativeE
                     entryPoint = GetHelperFtnUncached(ftnNum);
                     _helperCache.Add(ftnNum, entryPoint);
                 }
+
+#if !READYTORUN
+                if (ftnNum == CorInfoHelpFunc.CORINFO_HELP_JIT_REVERSE_PINVOKE_ENTER
```
Comment (jkotas) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs]: Instead of teaching compiler about the special P/Invoke transition, we can route the new thread creation through a C/C++ method that would make the new thread skip waiting for finalizers (e.g. by setting a new ThreadStateFlags flag). It would keep the hack contained in the runtime.

Comment (VSadov) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs]: There is a place in `AttachCurrentThread` that assumes if any flags set, then we've already attached. That is just a convenience. 
It can as well check for `IsStateSet(TSF_Attached)`

```c
    // The thread was already initialized, so it is already attached.
    if (pAttachingThread->IsInitialized())
```

similar pattern in `DetachCurrentThread` - can check for `TSF_Attached`
```c
    // The thread was not initialized yet, so it was not attached
    if (!pDetachingThread->IsInitialized())
    {
        return;
    }
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.cs [hunk 3]
```diff
@@ -450,6 +450,11 @@ private static void StartThread(IntPtr parameter)
                 IncrementRunningForeground();
             }
 
+            while (Internal.Runtime.CompilerHelpers.StartupCodeHelpers.s_runningModuleInitializers)
+            {
+                Yield();
```
Comment (VSadov) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.cs]: Perhaps use Sleep(1) for consistency with the spinwait in native code.

**Comment by VSadov** [comment]
> I don't actually like this fix. But we need to do something about it because EventSource does exactly this (#118773).

I kind of feel the same. We may yet find some other ways the scenario can get us in trouble. The fix does seem to solve the issue at hand.

File: src/coreclr/nativeaot/Runtime/thread.cpp (hunk 1 above)
Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/Runtime/thread.cpp]: This was a copypaste from the other transition, but maybe we don't need this.

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs (hunk 2 above)
Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs]: > Instead of teaching compiler about the special P/Invoke transition, we can route the new thread creation through a C/C++ method that would make the new thread skip waiting for finalizers (e.g. by setting a new ThreadStateFlags flag). It would keep the hack contained in the runtime.

Gave this a try, hopefully what I came with is legitimate and won't cause problems for something!

File: src/coreclr/nativeaot/Runtime/thread.cpp [hunk 4]
```diff
@@ -1278,6 +1279,44 @@ FCIMPL0(Object**, RhGetThreadStaticStorage)
 }
 FCIMPLEND
 
+#ifdef TARGET_UNIX
+#define NEWTHREAD_RETURN_TYPE size_t
+#else
+#define NEWTHREAD_RETURN_TYPE uint32_t
+#endif
+
+FCIMPL1(NEWTHREAD_RETURN_TYPE, RhThreadEntryPoint, void* pContext)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/thread.cpp]: FCIMPL macros should be only used for methods with managed calling convention. This has unmanaged calling convention, so using FCIMPL macro for it is sketchy.

I would turn `RhGetThreadEntryPointAddress` itself into an FCALL that returns address of `RhThreadEntryPoint`, and make RhThreadEntryPoint to be a regular unmanaged C method.

Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/Runtime/thread.cpp]: Ah yeah, good point!

File: src/coreclr/nativeaot/Runtime/thread.cpp [hunk 5]
```diff
@@ -1278,6 +1279,49 @@ FCIMPL0(Object**, RhGetThreadStaticStorage)
 }
 FCIMPLEND
 
+#ifdef TARGET_UNIX
+#define NEWTHREAD_RETURN_TYPE size_t
+#else
+#define NEWTHREAD_RETURN_TYPE uint32_t
+#endif
+
+EXTERN_C STDCALL NEWTHREAD_RETURN_TYPE RhThreadEntryPoint(void* pContext)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/thread.cpp]:
```suggestion
static NEWTHREAD_RETURN_TYPE RhThreadEntryPoint(void* pContext)
```
Less ceremony? We prefer to omit explicit calling conventions if possible.

**Review by jkotas — APPROVED** [review]
LGTM otherwise. Thanks!

**Comment by MichalStrehovsky** [comment]
@jkotas @VSadov what do you think about the risk with taking this to .NET 10? From what I can judge, this is not doing anything too special/new, but I'm no GC expert. Maybe we could take this to 10?

**Comment by jkotas** [comment]
It is fine with me to take it for .NET 10.
