### PR TITLE
Fix incorrect time patterns for some cultures on browser in `HybridGlobalization`

### LINKED ISSUE #103745: Incorrect time patterns for some cultures on browser in `HybridGlobalization`
### Description

On browser when `HybridGlobalization` is on, some cultures (specifically, `fr-CA`) have incorrect time patterns, causing `DateTime.ToString(IFormatProvider)` to produce badly formatted strings.

### Reproduction Steps

Consider the following code:

```cs
new DateTime(2000, 1, 1, 20, 0, 0).ToString("T", new CultureInfo("fr-CA"));
```

### Expected behavior

A correctly formatted string (like `20 h 00 min 00 s` with the long time pattern `HH 'h' mm 'min' ss 's'`) is returned.

### Actual behavior

A badly formatted string `20 8 00 0in 00 0` is returned, with the long time pattern being `HH h mm min ss s`.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

- .NET version: 8.0
- Target platform: Browser
- Web browser: Chrome, Firefox
- `HybridGlobalization`

### Other information

The incorrect patterns in the browser environment is caused by the following code, which does not handle literal texts and copies them into the pattern as is.

https://github.com/dotnet/runtime/blob/8ab80b9af668601ebc102760b4c4e60d23ba8d8f/src/mono/browser/runtime/hybrid-globalization/culture-info.ts#L77

This issue was found during the process of fixing #103592 and the PR #103681.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/103745.

This PR makes improvements to values returned in date/time format APIs. It does not make all the locales' values match ICU's values due to Web API responses differences, but corrects majority of them.
Originally the ICU's expected behavior was saved in a form of a comment next to the specific test case. If this PR's fix made `HybridGlobalization` response match the comment , the comment got removed. If there are still discrepancies (e.g. node behaves different than chrome) the ICU value is left in the comment.

### CODE REVIEW

File: src/mono/browser/runtime/hybrid-globalization/calendar.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable no-console */
```
Comment (pavelsavara) [inline src/mono/browser/runtime/hybrid-globalization/calendar.ts:1]: please revert this line

**Comment by ilonatommy** [comment]
cc @PopSlime, `HybridGlobalization` relies on JS methods and there's no method in `Intl` that would return a "format" of date. We are workign it around by taking a specific date, formatting it using among others `toLocaleString` and then we parse the result to determin the generic format of date / time for the given locale. I added a function that tries to find the parts of the already formatted format that are "fixed" and these that are "variant" and put the fixed ones in quotes. If you have any suggestions how to improve this process, I would be glad to talk about it.

File: src/mono/browser/runtime/hybrid-globalization/calendar.ts [hunk 2]
```diff
@@ -326,3 +329,37 @@ function getEraNames (date: Date, locale: string | undefined, calendarId: number
...
+// transform e.g. "dddd, d MMMM yyyy г." into "dddd, d MMMM yyyy 'г'."
+function wrapSubstrings (str: string, locale: string | undefined) {
+    const words = str.split(" ");
+    // locales that write date nearly without spaces should not have format parts quoted - "ja", "zh"
+    // "ko" format parts should not be quoted but processing it would overcomplicate the logic
+    if (words.length <= 2 || locale?.startsWith("ko")) {
+        return str;
+    }
+
+    const keyWords = [MONTH_CODE, YEAR_CODE, DAY_CODE, WEEKDAY_CODE];
```
Comment (pavelsavara) [inline src/mono/browser/runtime/hybrid-globalization/calendar.ts:343]: move this out of the function, to avoid allocation on each call

File: src/mono/browser/runtime/hybrid-globalization/calendar.ts [hunk 3]
```diff
@@ -326,3 +329,37 @@ function getEraNames (date: Date, locale: string | undefined, calendarId: number
...
+    for (let i = 0; i < words.length; i++) {
+        if (!keyWords.includes(words[i].replace(",", "")) &&
```
Comment (pavelsavara) [inline src/mono/browser/runtime/hybrid-globalization/calendar.ts:345]: could all of the `replace()` be moved before the `str.split` ?

File: src/mono/browser/runtime/hybrid-globalization/culture-info.ts [hunk 4]
```diff
@@ -111,3 +119,20 @@ function getShortTimePattern (pattern: string): string {
     }
     return pattern;
 }
+
+// wraps all substrings in the format in quotes, except for key words
+// transform e.g. "HH h mm min ss s" into "HH 'h' mm 'min' ss 's'"
+// problem with "h" that can be both hour code and a fixed (quoted) part of the format
+// workaround for "fr-CA" by preventing quoting of "HH"
+function wrapSubstrings (str: string) {
+    const keyWords = [SECONDS_CODE, MINUTES_CODE, DESIGNATOR_CODE, PREFIX_24H];
```
Comment (pavelsavara) [inline src/mono/browser/runtime/hybrid-globalization/culture-info.ts:128]: also move the array out of the function.

File: src/mono/browser/runtime/hybrid-globalization/culture-info.ts [hunk 5]
```diff
@@ -111,3 +119,20 @@ function getShortTimePattern (pattern: string): string {
...
+    const words = str.split(" ");
```
Comment (pavelsavara) [inline src/mono/browser/runtime/hybrid-globalization/culture-info.ts:129]: is that always space ?  what about tab or another whitespaces ?

File: src/mono/browser/runtime/hybrid-globalization/calendar.ts (hunk 3 above)
Comment (ilonatommy) [reply src/mono/browser/runtime/hybrid-globalization/calendar.ts:345]: yes

**Comment by pavelsavara** [comment]
are we going to backport it to Net8 ?

File: src/mono/browser/runtime/hybrid-globalization/culture-info.ts (hunk 5 above)
Comment (ilonatommy) [reply src/mono/browser/runtime/hybrid-globalization/culture-info.ts:129]: we cannot predict what it will be, in the current form this implementation is test driven only and it does not try to predict the future editions to unicode standard. This one can be easily changed to `str.split(/\s+/);`

**Comment by ilonatommy** [comment]
> are we going to backport it to Net8 ?

I would like to.

File: src/mono/browser/runtime/hybrid-globalization/calendar.ts (hunk 3 above)
Comment (ilonatommy) [reply src/mono/browser/runtime/hybrid-globalization/calendar.ts:345]: Wait, why? It is more costly to do so

Comment (pavelsavara) [reply src/mono/browser/runtime/hybrid-globalization/calendar.ts:344]: okay, could we rewrite the whole loop + if into single compiled regex ?
`(MMMM|d|dddd)` for matching keywords and capture groups around them.
Compiled regex is fast, because it will typically only scan the input once. There is state machine/parser it will generate internally.

Comment (ilonatommy) [reply src/mono/browser/runtime/hybrid-globalization/calendar.ts:344]: This regex would be very complex and in case something changes in unicode standare, debugging would be a nightmare. It's not about just grepping "MMMM" etc. It's about recognizing substrings that should be in quotes and putting them into these quotes. There's a couple of edge cases, e.g.
- "yyyy. MMMM d., dddd" - we have to differentiate between "d.," that is typically a placeholder for day number in  "hu-HU" format from "d.," that is short from "diena" in "yyyy 'm'. MMMM d 'd'., dddd" - "lt-LT" format
- "dddd, yyyy. 'gada' d. MMMM" in "lv-LV" has "d." but it is a day placeholder, not a fixed expression.

Even if we made a compromise:
leaving the loop but using regex instead of long "if-case" inside of the loop then we have a problem with JS lacking support of lookbehinds in regular expressions. We need them because we want to clean the substrings that we got by splitting the format, from "," "." "\u05d1" and "\u060c" simultaneously not cleaning up ".,".

```
const words = str.split(/\s+/);
for (let i = 0; i < words.length; i++) {
        const cleanedWord = words[i].replace(/[.,\u060c\u05d1]/g, "");
        if (!keyWords.includes(cleanedWord)) {
               // ......wrap in quotes
       }
       return words.join(" ");
```

Comment (ilonatommy) [reply src/mono/browser/runtime/hybrid-globalization/calendar.ts:344]: Sorry, there is lookbehind:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion

Comment (pavelsavara) [reply src/mono/browser/runtime/hybrid-globalization/calendar.ts:344]: we can drop it if it's complex rabbit hole. Nobody loves debugging regex.

File: src/mono/browser/runtime/hybrid-globalization/culture-info.ts [hunk 6]
```diff
@@ -84,22 +93,22 @@ function getLongTimePattern (locale: string | undefined, designators: any): stri
...
+        hourPattern = hasPrefix ? PREFIX_24H : NO_PREFIX_24H;
         pattern = pattern.replace(localizedHour24, hourPattern);
     } else { // 12h
         const hasPrefix = h12Style.includes(hour12WithPrefix);
-        hourPattern = hasPrefix ? "hh" : "h";
+        hourPattern = hasPrefix ? PREFIX_12H : NO_PREFIX_12H;
         pattern = pattern.replace(hasPrefix ? hour12WithPrefix : localizedHour12, hourPattern);
     }
-    return pattern;
+    return wrapSubstrings(pattern);
```
Comment (mkhamoyan) [inline src/mono/browser/runtime/hybrid-globalization/culture-info.ts:103]: As `wrapSubstrings` is workaround for `"fr-CA"` do we need to call it for all cultures ?

Comment (ilonatommy) [reply src/mono/browser/runtime/hybrid-globalization/culture-info.ts:103]: You can take a look at the test files changed in this PR, it is not only "fr-CA". The best result would be to have a generic way of processing JS output, with as little if-else are possible.

Comment (mkhamoyan) [reply src/mono/browser/runtime/hybrid-globalization/culture-info.ts:103]: I see, comments on the `wrapSubstrings` were confusing for me.
Nit: 
```
// Note: The character "h" can be ambiguous as it might represent an hour code hour code and a fixed (quoted) part of the format.
// Special Case for "fr-CA": Always recognize "HH" as a keyword and do not quote it, to avoid formatting issues.

```

Comment (ilonatommy) [reply src/mono/browser/runtime/hybrid-globalization/culture-info.ts:103]: I understand. We used `PREFIX_24H` in `keyWords` but not other hour codes. I thought it might be confusing for the reader and added this comment. How can we change the comment to be more understandable? We can also move it closer to `keyWords` initialization.

**Comment by mkhamoyan** [comment]
Can we also enable test cases from https://github.com/dotnet/runtime/pull/103681 ?

**Review by mkhamoyan — APPROVED** [review]
