### PR TITLE
JIT: Fix `genHWIntrinsic_R_R_RM_I` assertion handling when ins is `INS_insertps`

### LINKED ISSUE #105467: JIT: Assertion failed 'isContainable || supportsRegOptional' during 'Generate code'
```csharp
// Generated by Fuzzlyn v1.7 on 2024-07-25 11:29:20
// Run on X64 Windows
// Seed: 17281006834984098297-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 159.4 KiB to 0.4 KiB in 00:00:57
// Hits JIT assert in Release:
// Assertion failed 'isContainable || supportsRegOptional' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 47; hash 0xade6b36b; FullOpts)
//
//     File: C:\dev\dotnet\runtime4\src\coreclr\jit\hwintrinsiccodegenxarch.cpp Line: 61
//
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static Vector128<float>[] s_6;
    public static void Main()
    {
        var vr3 = s_6[0];
        var vr4 = Vector128.Create<float>(0);
        s_6[0] = Sse41.Insert(vr3, vr4, 254);
    }
}
```

### PR DESCRIPTION
**Pull request by TIHan**
Resolves https://github.com/dotnet/runtime/issues/105467

### CODE REVIEW

File: src/coreclr/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -9415,6 +9415,29 @@ bool Lowering::IsContainableHWIntrinsicOp(GenTreeHWIntrinsic* parentNode, GenTre
                             supportsSIMDScalarLoads = (ival <= 0x3F);
                             supportsGeneralLoads    = supportsSIMDScalarLoads;
                         }
+
+                        if (supportsGeneralLoads && childNode->IsVectorZero() && ((op1 == childNode) || (op2 == childNode)))
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:9419]: This probably isn't the desired fix and regresses some scenarios.

What we basically have here is:
* zmask: bits 0-3
* count_D: bits 4-5
* count_S: bits 6-7

`count_S` indicates which source index is being inserted while `count_D` indicates the destination index that value is being inserted.

So `Vector128<float> Insert(Vector128<float> value, Vector128<float> data, [ConstantExpected] byte index)` is effectively doing `result = value.WithElement(count_D, data.GetElement(count_S)`

`zmask` is then indicating that individual additional elements are zeroed in addition to this extract and insert.

-------------

I think then that we're missing a bit of logic in https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L2107-L2312

When both `op1` and `op2` are zero, we replace ourselves with constant zero already.

When `op1` is zero, we're correctly setting `zmask` to clear everything except the bit we're inserting: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L2181-L2191, we then mark `op1` as contained (https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L11350-L11370), and then in codegen handle this by reusing the target register (https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1101-L1106). This all looks correct except that we should be checking `op1->isContained()` rather than `op1Reg == REG_NA`.

When `op2` is zero, we are equally setting `zmask` to handle the zeroing itself (https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L2192-L2202), we mark `op2` as contained (https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L11371-L11392), and then codegen special cases this by reusing `op1Reg`: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1108-L1115

What's firing is the assert here: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1093-L1097

This is failing because we think that general loads are only containable when `ival <= 0x3F` (https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerxarch.cpp#L9412-L9446) and that would be true if this were coming from memory. It's not, however, and so is failing to account for the fact that `op2` is being specially handled, so the assert itself is what's "bad".

The "proper" fix here would likely be to update the assert here to special-case the fact that `zero` is containable for `insertps` and that it isn't coming from memory: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1093-L1097. This could be handled by simply moving those 5 lines after the initial `if (ins == INS_insertps) { }` block

**Comment by TIHan** [comment]
@jit-contrib @tannergooding this is ready

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 2]
```diff
@@ -1090,12 +1090,6 @@ void CodeGen::genHWIntrinsic_R_R_RM_I(
...
 
-    if (op2->isContained() || op2->isUsedFromSpillTemp())
-    {
-        assert(HWIntrinsicInfo::SupportsContainment(node->GetHWIntrinsicId()));
-        assertIsContainableHWIntrinsicOp(compiler->m_pLowering, node, op2);
-    }
-
     if (ins == INS_insertps)
     {
         if (op1Reg == REG_NA)
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1095]: Could you also fix this line to check `op1->isContained()`, just to make it more explicit.

We have some contexts where register assignments are left in some nodes even if `isUsedFromReg` is false and it should help ensure we aren't doing the incorrect thing: https://github.com/dotnet/runtime/issues/105837

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 3]
```diff
@@ -1092,10 +1092,11 @@ void CodeGen::genHWIntrinsic_R_R_RM_I(
 
     if (ins == INS_insertps)
     {
-        if (op1Reg == REG_NA)
+        if (op1->isContained())
         {
             // insertps is special and can contain op1 when it is zero
-            assert(op1->isContained() && op1->IsVectorZero());
+            assert(op1->IsVectorZero());
+            assert(op1Reg == REG_NA);
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1099]: We don't want this assert because registers can sometimes be set even if they're unused, such as to support spilling or use/defs

**Review by tannergooding — APPROVED** [review]

**Comment by TIHan** [comment]
Current failures are unrelated; Pri0 tests passed. Also, the second previous run ran all green. Merging.
