### PR TITLE
Handle success case for overlapped IO in Windows Diagnostics IPC PAL

### LINKED ISSUE #38847: pauseonstart test failures
tracing\\eventpipe\\pauseonstart\\pauseonstart\\pauseonstart.cmd has failed in multiple CI runs:

`R2R Windows_NT x64 Checked forcerelocs @ Windows.10.Amd64.Open`

```
set RunCrossGen=1 
set COMPlus_TieredCompilation=0
set COMPlus_ForceRelocs=1
```

https://dev.azure.com/dnceng/public/_build/results?buildId=716943&view=ms.vss-test-web.build-test-results-tab&runId=22218608&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=110533

```
Collected crash dump C:\cores\crashdump_6592.dmp
    tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.cmd [FAIL]
      
      cmdLine:C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.cmd Timed Out
      
      Return code:      -100
      Raw output file:      C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\Reports\tracing.eventpipe\pauseonstart\pauseonstart\pauseonstart.output.txt
      Raw output:
      BEGIN EXECUTION
              1 file(s) copied.
      " "C:\h\w\977C081E\p\crossgen.exe"  /Platform_Assemblies_Paths C:\h\w\977C081E\p;C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart /in C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.org /out C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\\pauseonstart.dll"
      Microsoft (R) CoreCLR Native Image Generator - Version 5.0.0-ci
      Copyright (c) Microsoft Corporation.  All rights reserved.
      
      Native image C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\\pauseonstart.dll generated successfully.
       "C:\h\w\977C081E\p\corerun.exe" pauseonstart.dll 
        0.0s: ::== Running test: TEST_RuntimeResumesExecutionWithCommand
        0.1s: Server name is 'DOTNET_TRACE_TESTS_4hx5s0ds.ucu'
        0.7s: running sub-process: C:\h\w\977C081E\p\CoreRun.exe C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.dll 0
        1.2s: subprocess started: True
        1.2s: subprocess PID: 5256
        2.8s: { Magic=System.Byte[]; ClrInstanceId=fe0342ed-a66a-d806-9784-9bed6388f8fc; ProcessId=5256; Unused=0; }
        2.9s: Sent: { Header={ Magic=System.Byte[]; Size=20; CommandSet=255; CommandId=1; Reserved=0 }; }
        3.1s: received: { Header={ Magic=System.Byte[]; Size=24; CommandSet=255; CommandId=0; Reserved=0 }; Payload=[ '0000' '0000' '0000' '0000'  ]}
        3.1s: Sending 'exit' to subprocess stdin
        3.9s: ================= Subprocess Exited =================
        3.9s: SubProcess exited - Exit code: 0
        3.9s: Subprocess stdout: 
        1.0s: The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a server at 'DOTNET_TRACE_TESTS_4hx5s0ds.ucu'.
        3.1s: Subprocess started!  Waiting for input...
        3.1s: Received 'exit'.  Exiting...
        3.9s: Subprocess stderr: 
        4.0s: Test passed: True
        4.0s: 
        4.0s: ::== Running test: TEST_TracesHaveRelevantEvents
        4.1s: Server name is 'DOTNET_TRACE_TESTS_5oyavcdg.fvm'
        4.1s: running sub-process: C:\h\w\977C081E\p\CoreRun.exe C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.dll 0
        4.1s: subprocess started: True
        4.1s: subprocess PID: 2216
        4.1s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
        4.3s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
        4.5s: { Magic=System.Byte[]; ClrInstanceId=fd234556-3fe8-a13b-8e71-270d82f351c3; ProcessId=2216; Unused=0; }
        4.6s: Starting EventPipeSession over standard connection
        4.7s: Started EventPipeSession over standard connection with session id: 0x21112581990
        4.8s: Send ResumeRuntime Diagnostics IPC Command
        4.8s: Sent: { Header={ Magic=System.Byte[]; Size=20; CommandSet=255; CommandId=1; Reserved=0 }; }
        4.8s: received: { Header={ Magic=System.Byte[]; Size=24; CommandSet=255; CommandId=0; Reserved=0 }; Payload=[ '0000' '0000' '0000' '0000'  ]}
        6.8s: Stopping EventPipeSession over standard connection
        7.0s: Stopped EventPipeSession over standard connection
        7.0s: Sending 'exit' to subprocess stdin
        7.1s: ================= Subprocess Exited =================
        7.1s: SubProcess exited - Exit code: 0
        7.1s: Subprocess stdout: 
        0.3s: The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a server at 'DOTNET_TRACE_TESTS_5oyavcdg.fvm'.
        1.8s: Subprocess started!  Waiting for input...
        3.0s: Received 'exit'.  Exiting...
        7.1s: Subprocess stderr: 
        7.8s: isStartupEventPresent: True
        7.8s: Test passed: True
        7.8s: 
        7.8s: ::== Running test: TEST_MultipleSessionsCanBeStartedWhilepaused
        7.8s: Server name is 'DOTNET_TRACE_TESTS_m2gvge2y.off'
        7.8s: running sub-process: C:\h\w\977C081E\p\CoreRun.exe C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.dll 0
        7.8s: subprocess started: True
        7.8s: subprocess PID: 7056
        7.8s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
        8.1s: { Magic=System.Byte[]; ClrInstanceId=8c074577-3971-cf98-8fa7-a94ed870796a; ProcessId=7056; Unused=0; }
        8.1s: Starting EventPipeSession over standard connection
        8.2s: Started EventPipeSession over standard connection with session id: 0x1dc8bd901c0
        8.2s: Starting EventPipeSession over standard connection
        8.2s: Started EventPipeSession over standard connection with session id: 0x1dc8bd8ffc0
        8.2s: Starting EventPipeSession over standard connection
        8.2s: Started EventPipeSession over standard connection with session id: 0x1dc8bd8fd40
        8.2s: Send ResumeRuntime Diagnostics IPC Command
        8.2s: Sent: { Header={ Magic=System.Byte[]; Size=20; CommandSet=255; CommandId=1; Reserved=0 }; }
        8.2s: received: { Header={ Magic=System.Byte[]; Size=24; CommandSet=255; CommandId=0; Reserved=0 }; Payload=[ '0000' '0000' '0000' '0000'  ]}
       10.9s: Stopping EventPipeSession over standard connection
       11.2s: Stopped EventPipeSession over standard connection
       11.2s: Sending 'exit' to subprocess stdin
       11.3s: ================= Subprocess Exited =================
       11.3s: SubProcess exited - Exit code: 0
       11.3s: Subprocess stdout: 
        0.3s: The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a server at 'DOTNET_TRACE_TESTS_m2gvge2y.off'.
        1.3s: Subprocess started!  Waiting for input...
        3.5s: Received 'exit'.  Exiting...
       11.3s: Subprocess stderr: 
       11.3s: nStartupEventsSeen: 3
       11.3s: Test passed: True
       11.3s: 
       11.3s: ::== Running test: TEST_CanStartAndStopSessionWhilepaused
       11.3s: Server name is 'DOTNET_TRACE_TESTS_eqlrpwut.bif'
       11.3s: running sub-process: C:\h\w\977C081E\p\CoreRun.exe C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.dll 0
       11.4s: subprocess started: True
       11.4s: subprocess PID: 2616
       11.4s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
       11.7s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
       11.9s: { Magic=System.Byte[]; ClrInstanceId=67f94336-c91d-3fa7-a884-938f26d09ca4; ProcessId=2616; Unused=0; }
       11.9s: Starting EventPipeSession over standard connection
       11.9s: Started EventPipeSession over standard connection with session id: 0x1dbd77632b0
       11.9s: Starting EventPipeSession over standard connection
       11.9s: Started EventPipeSession over standard connection with session id: 0x1dbd7762e30
       11.9s: Starting EventPipeSession over standard connection
       11.9s: Started EventPipeSession over standard connection with session id: 0x1dbd7762f30
       12.9s: Stopping EventPipeSession over standard connection
       12.9s: Stopped EventPipeSession over standard connection
       12.9s: Send ResumeRuntime Diagnostics IPC Command
       12.9s: Sent: { Header={ Magic=System.Byte[]; Size=20; CommandSet=255; CommandId=1; Reserved=0 }; }
       12.9s: received: { Header={ Magic=System.Byte[]; Size=24; CommandSet=255; CommandId=0; Reserved=0 }; Payload=[ '0000' '0000' '0000' '0000'  ]}
       12.9s: Sending 'exit' to subprocess stdin
       13.9s: ================= Subprocess Exited =================
       13.9s: SubProcess exited - Exit code: 0
       13.9s: Subprocess stdout: 
        0.3s: The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a server at 'DOTNET_TRACE_TESTS_eqlrpwut.bif'.
        2.4s: Subprocess started!  Waiting for input...
        2.5s: Received 'exit'.  Exiting...
       13.9s: Subprocess stderr: 
       13.9s: Test passed: True
       13.9s: 
       13.9s: ::== Running test: TEST_DisabledCommandsError
       13.9s: Server name is 'DOTNET_TRACE_TESTS_r0gx5vln.r1j'
       13.9s: running sub-process: C:\h\w\977C081E\p\CoreRun.exe C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.dll 0
       13.9s: subprocess started: True
       13.9s: subprocess PID: 3304
       13.9s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
       14.3s: { Magic=System.Byte[]; ClrInstanceId=b77c4a04-4e10-da4e-9134-cb0a04cf210e; ProcessId=3304; Unused=0; }
       14.3s: Send profiler attach Diagnostics IPC Command
       14.3s: Sent: { Header={ Magic=System.Byte[]; Size=20; CommandSet=3; CommandId=1; Reserved=0 }; }
       14.3s: received: { Header={ Magic=System.Byte[]; Size=24; CommandSet=255; CommandId=255; Reserved=0 }; Payload=[ '005B' '0013' '0013' '0080'  ]}
       14.6s: { Magic=System.Byte[]; ClrInstanceId=b77c4a04-4e10-da4e-9134-cb0a04cf210e; ProcessId=3304; Unused=0; }
       14.6s: Send ResumeRuntime Diagnostics IPC Command
       14.6s: Sent: { Header={ Magic=System.Byte[]; Size=20; CommandSet=255; CommandId=1; Reserved=0 }; }
      
      cmdLine:C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.cmd Timed Out
      Test Harness Exitcode is : -100
      To run the test:
      > set CORE_ROOT=C:\h\w\977C081E\p
      > C:\h\w\977C081E\w\A174094B\e\tracing\eventpipe\pauseonstart\pauseonstart\pauseonstart.cmd
      Expected: True
      Actual:   False
```

Also: all the Windows x86 legs of `runtime-coreclr jitstress-isas-x86`:
https://dev.azure.com/dnceng/public/_build/results?buildId=716582&view=ms.vss-test-web.build-test-results-tab&runId=22207570&resultId=110525&paneView=debug

@josalem

### PR DESCRIPTION
**Pull request by josalem**
fixes #38847 (see the issue for more details on my investigation)

There is a missing `else` condition on the error checking for a call to `Read` with OverlappedIO.  In this case, the value in `pHandles[0]` is unset.  `pHandles[0]` could be:
1. complete junk -> `WaitForMultipleObjects` will fail and everything corrects on the second call to `Poll`
2. _any_ other waitable handle -> `WaitForMultipleObjects` is now waiting on the forward server connection which won't signal and _some other_ handle which presumably also won't signal.

In the second case, we will hang and timeout the test.  The runtime is effectively single threaded in this state, because the only other thread is waiting in `ceemain.cpp` on the Pause On Start event.

CC @tommcdon @BruceForstall @dotnet/dotnet-diag

### CODE REVIEW

**Comment by josalem** [comment]
AzDO says the legs marked "running" actually completed successfully, so the CI is actually all green.  This happened on another PR of mine.

**Comment by josalem** [comment]
#39789 didn't automerge and turn the pauseonstart test off (due to the same GH issue I mentioned above).  This worked out in my favor since it used the new dumping logic that I added to CI and the dump shows the same symptom that I believe this PR is fixing, i.e., `WaitForMultipleObjects` getting a "junk" value that is a valid handle from elsewhere in the process.  I believe this PR should resolve the issue.

```
0:001> ?? pHandles[0]
void * 0x0000012c <----- SERVER handle
0:001> ?? pHandles[1]
void * 0x0000012c <----- SERVER handle
0:001> ?? rgIpcPollHandles[0]
struct IpcStream::DiagnosticsIpc::IpcPollHandle
   +0x000 pIpc             : (null) 
   +0x004 pStream          : 0x03550710 IpcStream
   +0x008 revents          : 0 ''
   +0x00c pUserData        : 0x0351ffd8 Void
0:001> dx -r1 ((coreclr!IpcStream *)0x3550710)
((coreclr!IpcStream *)0x3550710)                 : 0x3550710 [Type: IpcStream *]
    InfiniteTimeout  : -1 [Type: int]
    [+0x000] _hPipe           : 0x130 [Type: void *]
    [+0x004] _oOverlap        [Type: _OVERLAPPED]
    [+0x018] _isTestReading   : 1 [Type: int]
    [+0x01c] _mode            : CLIENT (0) [Type: IpcStream::DiagnosticsIpc::ConnectionMode]
0:001> dx -r1 (*((coreclr!_OVERLAPPED *)0x3550714))
(*((coreclr!_OVERLAPPED *)0x3550714))                 [Type: _OVERLAPPED]
    [+0x000] Internal         : 0x0 [Type: unsigned long]
    [+0x004] InternalHigh     : 0x0 [Type: unsigned long]
    [+0x008] Offset           : 0x0 [Type: unsigned long]
    [+0x00c] OffsetHigh       : 0x0 [Type: unsigned long]
    [+0x008] Pointer          : 0x0 [Type: void *]
    [+0x010] hEvent           : 0x138 [Type: void *] <------- CLIENT handle
0:001> ?? rgIpcPollHandles[1]
struct IpcStream::DiagnosticsIpc::IpcPollHandle
   +0x000 pIpc             : 0x035396f8 IpcStream::DiagnosticsIpc
   +0x004 pStream          : (null) 
   +0x008 revents          : 0 ''
   +0x00c pUserData        : 0x0351fef8 Void
0:001> dx -r1 ((coreclr!IpcStream::DiagnosticsIpc *)0x35396f8)
((coreclr!IpcStream::DiagnosticsIpc *)0x35396f8)                 : 0x35396f8 [Type: IpcStream::DiagnosticsIpc *]
    [+0x000] mode             : SERVER (1) [Type: IpcStream::DiagnosticsIpc::ConnectionMode]
    MaxNamedPipeNameLength : 0x100 [Type: unsigned int]
    [+0x004] _pNamedPipeName  : "\\.\pipe\dotnet-diagnostic-5352" [Type: char [256]]
    [+0x104] _hPipe           : 0x128 [Type: void *]
    [+0x108] _oOverlap        [Type: _OVERLAPPED]
    [+0x11c] _isListening     : true [Type: bool]
0:001> dx -r1 (*((coreclr!_OVERLAPPED *)0x3539800))
(*((coreclr!_OVERLAPPED *)0x3539800))                 [Type: _OVERLAPPED]
    [+0x000] Internal         : 0x103 [Type: unsigned long]
    [+0x004] InternalHigh     : 0x0 [Type: unsigned long]
    [+0x008] Offset           : 0x0 [Type: unsigned long]
    [+0x00c] OffsetHigh       : 0x0 [Type: unsigned long]
    [+0x008] Pointer          : 0x0 [Type: void *]
    [+0x010] hEvent           : 0x12c [Type: void *] <------- SERVER handle
```

**Comment by josalem** [comment]
Happened again: The CI is green according to AzDO, but GH hasn't updated to show the jobs as completed or successful.

File: src/coreclr/src/debug/debug-pal/win/diagnosticsipc.cpp [hunk 1]
```diff
@@ -119,6 +119,7 @@ bool IpcStream::DiagnosticsIpc::Listen(ErrorCallback callback)
                 _hPipe = INVALID_HANDLE_VALUE;
                 ::CloseHandle(_oOverlap.hEvent);
                 _oOverlap.hEvent = INVALID_HANDLE_VALUE;
+                memset(&_oOverlap, 0, sizeof(OVERLAPPED)); // clear the overlapped objects state
```
Comment (davmason) [inline src/coreclr/src/debug/debug-pal/win/diagnosticsipc.cpp:122]: This will overwrite _oOverlap.hEvent (currently INVALID_HANDLE_VALUE==-1) with 0, so the check on 249 `if (_oOverlap.hEvent != INVALID_HANDLE_VALUE)` won't do the right thing.

File: src/coreclr/src/debug/debug-pal/win/diagnosticsipc.cpp [hunk 2]
```diff
@@ -193,27 +194,38 @@ IpcStream *IpcStream::DiagnosticsIpc::Connect(ErrorCallback callback)
...
 }
 
-void IpcStream::DiagnosticsIpc::Close(bool isShutdown, ErrorCallback)
+void IpcStream::DiagnosticsIpc::Close(bool isShutdown, ErrorCallback callback)
 {
     // don't attempt cleanup on shutdown and let the OS handle it
     if (isShutdown)
+    {
+        if (callback != nullptr)
+            callback("Closing without cleaning underlying handles", 100);
```
Comment (davmason) [inline src/coreclr/src/debug/debug-pal/win/diagnosticsipc.cpp:203]: All the ErrorCallbacks just write to the stress log, right? Seeing the codes makes me suspicious that the callback will terminate the pipe and send an error code back, which would cause some bad assumptions below. From looking at the source it seems like it's just a logging thing though.

**Review by davmason — APPROVED** [review]

File: src/coreclr/src/debug/debug-pal/win/diagnosticsipc.cpp (hunk 2 above)
Comment (josalem) [reply src/coreclr/src/debug/debug-pal/win/diagnosticsipc.cpp:203]: yes, the `ErrorCallback` is just to allow the diag PAL to call back out to `STRESS_LOG`.

File: src/coreclr/src/debug/debug-pal/win/diagnosticsipc.cpp (hunk 1 above)
Comment (josalem) [reply src/coreclr/src/debug/debug-pal/win/diagnosticsipc.cpp:121]: Moved the memset to before setting the handle to INVALID_HANDLE_VALUE

**Comment by josalem** [comment]
GH isn't seeing the AzDO job has finished and succeeded:
image

CI is all green.  I'm going to kick an outer loop to be doubly sure and then merge in the morning.

**Comment by josalem** [comment]
outerloop didn't seem to kick off correctly because the OSX leg hit a homebrew error so the tests never built for running on other platforms.  Innerloop passed all green, so I'll merge this morning if there are no objections.

**Comment by hoyosjs** [comment]
The OSX issue has been fixed, but it was after the PR was opened, so probably would require rebasing. Not sure it's justified.

**Comment by josalem** [comment]
> Not sure it's justified.

Agreed.  I'll give it another moment for people to air their opinions and then merge it in.

**Comment by davmason** [comment]
:shipit:

**Review by sywhang — APPROVED** [review]
the changes LGTM but we should make sure OSX legs pass before we check this in

**Comment by josalem** [comment]
@sywhang I don't think any changes here would affect the OSX legs.  It sounds like that's an infrastructure bug.  I can rebase and rerun outer loop, but I'm not sure it would do much at this point.

**Comment by josalem** [comment]
Windows failures are unrelated (Interop PInvoke CopyCtor test), and the mac failure is a known issue unrelated to these changes being investigated in #39979.

**Comment by josalem** [comment]
Remaining test failures are unrelated.  I'll merge without if there's no further objection.
