### PR TITLE
Ensure the layout of `StackAllocatedBox<T>` matches boxed layouts

### LINKED ISSUE #106947: Test failure: System.Text.Json.SourceGeneration.Tests.NumberHandlingTests_Default.Number_AsRootType_RoundTrip
**Failed in:** [runtime-coreclr libraries-jitstress-random 20240824.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=787545&view=ms.vss-test-web.build-test-results-tab&runId=20231008&resultId=178159&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress_random_1-Windows.10.Amd64.Open
    - System.Text.Json.SourceGeneration.Tests.NumberHandlingTests_Default.Number_AsRootType_RoundTrip
    - System.Text.Json.SourceGeneration.Tests.NumberHandlingTests_Default.EscapingTest
    - System.Text.Json.SourceGeneration.Tests.NumberHandlingTests_Default.Number_AsCollectionElement_RoundTrip
    - System.Text.Json.SourceGeneration.Tests.NumberHandlingTests_Metadata.Number_AsCollectionElement_RoundTrip
    - System.Text.Json.SourceGeneration.Tests.NumberHandlingTests_Metadata.EscapingTest
    - System.Text.Json.SourceGeneration.Tests.NumberHandlingTests_Metadata.Number_AsRootType_RoundTrip
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 9223372036854775808
Actual:   0
```

**Stack trace:**
```
   at System.Text.Json.Serialization.Tests.NumberHandlingTests.PerformAsRootTypeSerialization[T](T number, String jsonWithNumberAsNumber, String jsonWithNumberAsString) in /_/src/libraries/System.Text.Json/tests/Common/NumberHandlingTests.cs:line 116
   at System.Text.Json.Serialization.Tests.NumberHandlingTests.RunAsRootTypeTest[T](List`1 numbers) in /_/src/libraries/System.Text.Json/tests/Common/NumberHandlingTests.cs:line 96
   at System.Text.Json.Serialization.Tests.NumberHandlingTests.Number_AsRootType_RoundTrip() in /_/src/libraries/System.Text.Json/tests/Common/NumberHandlingTests.cs:line 67
--- End of stack trace from previous location ---
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
The boxed layout of a struct always has its data at +8, as evidenced by `Object::UnBox`. This means that `StackAllocatedBox<T>` should have `Pack = 1`, otherwise this may not be the case. In the test failure we had a `StackAllocatedBox<Int128>` which had its `_value` field at offset
16. After object stack allocation this meant that we were saving data in padding of the structure, which promotion does not guarantee to preserve.

Fix #106947

### CODE REVIEW

File: src/coreclr/jit/valuenum.cpp [hunk 1]
```diff
@@ -10299,7 +10299,7 @@ void ValueNumStore::vnDumpSimdType(Compiler* comp, VNFuncApp* simdType)
     int         simdSize    = ConstantValue<int>(simdType->m_args[0]);
     CorInfoType baseJitType = (CorInfoType)ConstantValue<int>(simdType->m_args[1]);
 
-    printf("%s(simd%d, %s)", VNFuncName(simdType->m_func), simdSize, varTypeName(JitType2PreciseVarType(baseJitType)));
+    printf("%s(simd%d, %s)", VNFuncName(simdType->m_func), simdSize, baseJitType == TYP_UNDEF ? varTypeName(TYP_UNDEF) : varTypeName(JitType2PreciseVarType(baseJitType)));
```
Comment (jakobbotsch) [inline src/coreclr/jit/valuenum.cpp:10302]: I hit assert inside `JitType2PreciseVarType` with `JitDump` enabled while investigating -- this fixes the problem.

**Review by jkotas — APPROVED** [review]

**Review by AndyAyersMS — APPROVED** [review]

**Comment by jakobbotsch** [comment]
/ba-g There are no machines in the Helix queue for Ubuntu.2204.amd64.open.rt, so the jobs are going to time out. There is current investigation happening about the issue.
