### PR TITLE
JIT: fix out of bounds read during SPMI collection

### LINKED ISSUE #76991: superpmicollect access violation in pgo Bytemark
win-arm64 superpmicollect pgo
(may be broader than pgo - full superpmi collection runs have been failing at times on arm64)

https://dev.azure.com/dnceng-public/public/_build/results?buildId=49331&view=logs&j=63f2a02a-7891-5505-e9da-45b13105e16b
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bb1a6462f51c458492/JIT.1/1/console.516d02e2.log?helixlogtype=result

```
set COMPlus_TieredCompilation=1
set COMPlus_ReadyToRun=0
set COMPlus_TC_QuickJitForLoops=1
set COMPlus_TieredPGO=1
set COMPlus_JitClassProfiling=0
set COMPlus_JitDelegateProfiling=1
set COMPlus_JitVTableProfiling=1
set COMPlus_JitRandomGuardedDevirtualization=1
set COMPlus_JitRandomlyCollect64BitCounts=1

D:\h\w\A77F0919\w\BEF10A17\e>set PATH=D:\h\w\A77F0919\p\dotnet-cli;C:\python3.7.0\lib\site-packages\pywin32_system32;C:\python3.7.0\lib\site-packages\pywin32_system32;C:\python3.7.0\Scripts\;C:\python3.7.0\;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Windows\System32\OpenSSH\;D:\Users\runner\AppData\Local\Microsoft\WindowsApps 

D:\h\w\A77F0919\w\BEF10A17\e>set DOTNET_ROOT=D:\h\w\A77F0919\p\dotnet-cli 

D:\h\w\A77F0919\w\BEF10A17\e>set DOTNET_CLI_TELEMETRY_OPTOUT=1 

D:\h\w\A77F0919\w\BEF10A17\e>set DOTNET_CLI_HOME=D:\h\w\A77F0919\w\BEF10A17\e\.dotnet 

D:\h\w\A77F0919\w\BEF10A17\e>set NUGET_PACKAGES=D:\h\w\A77F0919\w\BEF10A17\e\.nuget 

D:\h\w\A77F0919\w\BEF10A17\e>dotnet D:\h\w\A77F0919\p\xunit\xunit.console.dll JIT\BBT\JIT.BBT.XUnitWrapper.dll JIT\CheckProjects\JIT.CheckProjects.XUnitWrapper.dll JIT\opt\JIT.opt.XUnitWrapper.dll JIT\Performance\JIT.Performance.XUnitWrapper.dll JIT\RyuJIT\JIT.RyuJIT.XUnitWrapper.dll JIT\superpmi\JIT.superpmi.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml 
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.0-rc.1.22426.10)
  Discovering: JIT.BBT.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.BBT.XUnitWrapper (found 1 test case)
  Starting:    JIT.BBT.XUnitWrapper (parallel test collections = on, max threads = 8)
  Finished:    JIT.BBT.XUnitWrapper
  Discovering: JIT.CheckProjects.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.CheckProjects.XUnitWrapper (found 1 test case)
  Starting:    JIT.CheckProjects.XUnitWrapper (parallel test collections = on, max threads = 8)
  Finished:    JIT.CheckProjects.XUnitWrapper
  Discovering: JIT.opt.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.opt.XUnitWrapper (found 247 test cases)
  Starting:    JIT.opt.XUnitWrapper (parallel test collections = on, max threads = 8)
  Finished:    JIT.opt.XUnitWrapper
  Discovering: JIT.Performance.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.Performance.XUnitWrapper (found 101 test cases)
  Starting:    JIT.Performance.XUnitWrapper (parallel test collections = on, max threads = 8)
  Finished:    JIT.Performance.XUnitWrapper
  Discovering: JIT.RyuJIT.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.RyuJIT.XUnitWrapper (found 1 test case)
  Starting:    JIT.RyuJIT.XUnitWrapper (parallel test collections = on, max threads = 8)
  Finished:    JIT.RyuJIT.XUnitWrapper
  Discovering: JIT.superpmi.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.superpmi.XUnitWrapper (found 3 test cases)
  Starting:    JIT.superpmi.XUnitWrapper (parallel test collections = on, max threads = 8)
    JIT\superpmi\superpmicollect\superpmicollect.cmd [FAIL]
      
      Assert failure(PID 3040 [0x00000be0], Thread: 18220 [0x472c]): !"Access violation while Jitting!"
      
      CORECLR! EEFilterException + 0x60 (0x00007ff8`c26d6bb8)
      CORECLR! `CEEInfo::runWithErrorTrap'::`1'::filt$0 + 0x60 (0x00007ff8`c2be3740)
      CORECLR! _C_ExecuteExceptionFilter + 0x38 (0x00007ff8`c2632d88)
      CORECLR! _C_specific_handler + 0x214 (0x00007ff8`c2b40584)
      NTDLL! chkstk + 0x1CC (0x00007ff9`06e2387c)
      NTDLL! LdrControlFlowGuardEnforced + 0x8D4 (0x00007ff9`06e85ff4)
      NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007ff9`06e23434)
      SUPERPMI-SHIM-COLLECTOR! <no symbol> + 0x0 (0x00007ff8`e3a71660)
      SUPERPMI-SHIM-COLLECTOR! jitStartup + 0x205C (0x00007ff8`e3a7b20c)
      SUPERPMI-SHIM-COLLECTOR! jitStartup + 0x1695C (0x00007ff8`e3a8fb0c)
          File: D:\a\_work\1\s\src\coreclr\vm\jitinterface.cpp Line: 10346
          Image: D:\h\w\A77F0919\p\corerun.exe
      
      ERROR: Test D:\h\w\A77F0919\w\BEF10A17\e\JIT\superpmi\superpmicollect\Bytemark\Bytemark.cmd failed
      
      Return code:      1
      Raw output file:      D:\h\w\A77F0919\w\BEF10A17\uploads\Reports\JIT.superpmi\superpmicollect\superpmicollect.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\A77F0919\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  superpmicollect.dll 
      SuperPMI collection and playback - BEGIN
      Setting environment variables:
          SuperPMIShimLogPath=D:\h\w\A77F0919\t\ifdy230s.3lcSPMI
          SuperPMIShimPath=D:\h\w\A77F0919\p\clrjit.dll
          COMPlus_JitName=superpmi-shim-collector.dll
      Running: D:\Windows\system32\cmd.exe /c D:\h\w\A77F0919\w\BEF10A17\e\JIT\superpmi\superpmicollect\Bytemark\Bytemark.cmd
      BEGIN EXECUTION
       "D:\h\w\A77F0919\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Bytemark.dll 
      BBBBBB   YYY   Y  TTTTTTT  EEEEEEE
      BBB   B  YYY   Y    TTT    EEE
      BBB   B  YYY   Y    TTT    EEE
      BBBBBB    YYY Y     TTT    EEEEEEE
      BBB   B    YYY      TTT    EEE
      BBB   B    YYY      TTT    EEE
      BBBBBB     YYY      TTT    EEEEEEE
      
      BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
      NUMERIC SORT(jagged):  Iterations/sec: 1003.96474  Index: 25.74731
      NUMERIC SORT(rectangle):Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
      SuperPMI collection and playback - FAILED
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\A77F0919\p
      > D:\h\w\A77F0919\w\BEF10A17\e\JIT\superpmi\superpmicollect\superpmicollect.cmd
```

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
When recording the profile data into the method context, SPMI was assuming all data items were `sizeof(uintptr_t)` which is not guaranteed. Use the proper size.

Fixes #76991.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

See #76991 for analysis of the issue.

File: src/coreclr/tools/superpmi/superpmi-shared/methodcontext.cpp [hunk 1]
```diff
@@ -5664,6 +5664,34 @@ HRESULT MethodContext::repAllocPgoInstrumentationBySchema(
...
+            return 0;
+        case ICorJitInfo::PgoInstrumentationKind::FourByte:
+            return 4;
+        case ICorJitInfo::PgoInstrumentationKind::EightByte:
+            return 8;
+        case ICorJitInfo::PgoInstrumentationKind::TypeHandle:
+        case ICorJitInfo::PgoInstrumentationKind::MethodHandle:
+            return sizeof(uintptr_t);
+        default:
+            LogError("Unexpedted pgo schema data size (kind = %d)", kind);
```
Comment (BruceForstall) [inline src/coreclr/tools/superpmi/superpmi-shared/methodcontext.cpp:5688]: typo: Unexpedted

**Review by BruceForstall — APPROVED** [review]

**Review by jakobbotsch — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Windows x64 NAOT looks like #76801
OSX x64 NAOT failed during a restore step.
