### PR TITLE
Ordered evaluation in FileSystemGlobbing Matcher

### LINKED ISSUE #109408: Ordered evaluation in FileSystemGlobbing Matcher
### Background and Motivation

The current `Microsoft.Extensions.FileSystemGlobbing.Matcher` does not evaluate include and exclude patterns in the order they are added, which leads to limitations when trying to achieve more complex file-matching behavior. Specifically, includes added after an exclude do not override the exclude, resulting in unexpected or undesired results.

In scenarios where finer control over the inclusion and exclusion of files is needed, the inability to specify an ordered evaluation can prevent the desired matches. Adding an option to allow ordered evaluation of patterns would offer more intuitive control, empowering developers to achieve more precise and flexible file selection.

_Originally posted by @Benjin https://github.com/dotnet/runtime/issues/21362#issuecomment-1311106263_

### Current Behavior

Consider the following setup in `Matcher`:

```csharp
Matcher m = new();
m.AddInclude("**/*");
m.AddExclude("ExcludeMe/**/*");
m.AddInclude("ExcludeMe/ButActuallyIncludeMe/**/*");
```

Given this directory structure:

```
root/
  - helloWorld.txt
  - ExcludeMe/
      - notIncluded.txt
      - ButActuallyIncludeMe/
          - hiEarth.txt
```

The output is currently:

- `root/helloWorld.txt`
- *(Does NOT include `root/ExcludeMe/ButActuallyIncludeMe/hiEarth.txt`)*

### Expected Behavior

With ordered evaluation, the output would instead be:

- `root/helloWorld.txt`
- `root/ExcludeMe/ButActuallyIncludeMe/hiEarth.txt`

## Revised Proposal

The matcher is just a builder that calls into `MatcherContext` internally to do the work. That class takes in the include and exclude patterns separately so change should be made at that level as well.

The ordering is a configuration of the Matcher, so logically it should be passed into the Matcher (either in the constructor or as a property/field) instead of as an argument to `Execute`. This is the API I would suggest:

## Proposed API

```cs
namespace Microsoft.Extensions.FileSystemGlobbing;

public class Matcher
{
    public Matcher() { }
    public Matcher(StringComparison comparisonType) { }
+    public Matcher(bool ordered) { }
+    public Matcher(StringComparison comparisonType, bool ordered) { }
}
```

```cs
namespace Microsoft.Extensions.FileSystemGlobbing.Internal;

/// <summary>
/// This API supports infrastructure and is not intended to be used
/// directly from your code. This API may change or be removed in future releases.
/// </summary>
public class MatcherContext
+    : MatcherContextBase
{
    public MatcherContext(
        IEnumerable<IPattern> includePatterns,
        IEnumerable<IPattern> excludePatterns,
        DirectoryInfoBase directoryInfo,
        StringComparison comparison) { }
}
```

```cs
namespace Microsoft.Extensions.FileSystemGlobbing.Internal;

public class OrderedMatcherContext
    : MatcherContextBase
{
    public OrderedMatcherContext(
        IEnumerable<SelectionPattern> patterns,
        DirectoryInfoBase directoryInfo,
        StringComparison comparison) { }
}

public abstract class MatcherContextBase
{
    protected abstract PatternTestResult MatchPatternContexts<TFileInfoBase>(
        TFileInfoBase fileinfo, Func<IPatternContext, TFileInfoBase, PatternTestResult> test)
}

public struct SelectionPattern
{
    public IPattern pattern;
    public SelectionType selectionType;
}

public enum SelectionType
{
    Include,
    Exclude
}
```

## Usage

```cs
var m = new Matcher(true);
m.AddInclude("**/*");
m.AddExclude("ExcludeMe/**/*");
m.AddInclude("ExcludeMe/ButActuallyIncludeMe/**/*");

var result = m.Execute(new DirectoryInfoWrapper(new DirectoryInfo("root")));
foreach (var file in result.Files)
{
    Console.WriteLine(file.Path);
}
```

<details>
<summary>Original Proposal</summary>

### API Proposal

To introduce ordered evaluation without altering existing behavior by default, we propose adding an optional `ordered` parameter to the `Execute` method. This would allow users to explicitly enable ordered evaluation when required.

#### Proposed API Changes

```diff
public virtual Microsoft.Extensions.FileSystemGlobbing.PatternMatchingResult Execute(
-  DirectoryInfoBase directoryInfo);
+  DirectoryInfoBase directoryInfo, bool ordered = false);
```

- **Execute Method Parameter**: Adds an `ordered` parameter to the `Execute` method, allowing ordered evaluation to be enabled per execution while keeping current behavior as the default.

### API Usage

```csharp
// Execute with ordered evaluation
Matcher m = new();
m.AddInclude("**/*");
m.AddExclude("ExcludeMe/**/*");
m.AddInclude("ExcludeMe/ButActuallyIncludeMe/**/*");

var result = m.Execute(new DirectoryInfoWrapper(new DirectoryInfo("root")), ordered: true);
foreach (var file in result.Files)
{
    Console.WriteLine(file.Path);
}
```

Expected output:

- `root/helloWorld.txt`
- `root/ExcludeMe/ButActuallyIncludeMe/hiEarth.txt`

### Alternative Designs

1. **Matcher Constructor with Ordered Parameter**:
   Another approach could be adding an `ordered` parameter to the `Matcher` constructor to set the evaluation order for the entire lifecycle of the `Matcher` instance, rather than on a per-execution basis:

   ```csharp
   public Matcher(bool ordered = false);
   public Matcher(StringComparison comparisonType, bool ordered = false);
   ```

   This approach makes `ordered` a property of the `Matcher` instance, reducing the need to specify it with each execution. However, this would make it less flexible for scenarios where a developer may want to toggle ordered evaluation for different executions.

2. **Separate `ExecuteInOrder` Method**:
   Another alternative is to create a separate method, `ExecuteInOrder`, which explicitly indicates ordered evaluation:

   ```csharp
   public virtual PatternMatchingResult ExecuteInOrder(DirectoryInfoBase directoryInfo);
   ```

   This approach would keep `Execute` unchanged and provide a clear distinction in the API. However, it would increase the API surface.

### Risks

Enabling ordered evaluation may introduce a minor performance cost due to tracking evaluation order. However, this impact is expected to be minimal and only relevant when `ordered` is set to `true`.
</details>

### PR DESCRIPTION
**Pull request by PranavSenthilnathan**
Adds the `preserveFilterOrdering` flag to FileSystemGlobbing matcher. See #114720 for original PR.

/cc @kasperk81 

Fixes #109408

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Internal/PatternContexts/CompositePatternContext.cs [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+{
+    internal abstract class CompositePatternContext : IPatternContext
+    {
+        public abstract void Declare(Action<IPathSegment, bool> onDeclare);
+        public abstract void PopDirectory();
+        public abstract void PushDirectory(DirectoryInfoBase directory);
+
+        protected internal abstract PatternTestResult MatchPatternContexts<TFileInfoBase>(
+            TFileInfoBase fileInfo,
+            Func<IPatternContext, TFileInfoBase, PatternTestResult> test);
```
Comment (jozkee) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Internal/PatternContexts/CompositePatternContext.cs:17]: Not need to be generic.
```suggestion
        protected internal abstract PatternTestResult MatchPatternContexts(
            FileSystemInfoBase fileSystemInfo,
            Func<IPatternContext, PatternTestResult> test);
```

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+using Xunit;
+
+namespace Microsoft.Extensions.FileSystemGlobbing.Tests
+{
+    public class OrderedPatternMatchingTests : PatternMatchingTests
+    {
+        protected override bool PreserveFilterOrder => true;
+
+        [Fact]
+        public void ComplexPatternSequence_SimpleFilters()
```
Comment (jozkee) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs:16]: What's the meaning of Complex?

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+
+        [Fact]
+        public void NoFilterExcludes()
+        {
+            var scenario = new FileSystemGlobbingTestContext(@"c:/data/", true)
+                .Files("a.txt")
+                .Execute();
+
+            scenario.AssertExact();
+        }
```
Comment (jozkee) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs:178]: I don't fully grasp the ordering logic, but I wrote a test and didn't match my expectations.
```cs
  [Fact]
  public void ReIncludeSubdir()
  {
      var scenario = new FileSystemGlobbingTestContext(@"c:/project/", true)
          .Include("src/")
          .Exclude("src/Internal/")
          .Include("src/Internal/PetternContexts/")
          .Files(
              "src/Internal/PatternContexts/PatternContext.cs",
              "src/Internal/PatternSegments/CurrentPathSegment.cs"
          )
          .Execute();

      scenario.AssertExact(
          "src/Internal/PatternContexts/PatternContext.cs"
      );
  }
```

I was expecting that re-including a subdirectory, after an exclude, would match files in the re-included dir.
If I remove `.Exclude("src/Internal/")`, it matches both files, which seems expected.

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs [hunk 4]
```diff
@@ -0,0 +1,180 @@
...
+
+            scenario.AssertExact(
+                "Program.cs",
+                "lib/generated/AutoGen.cs",
+                "tests/manual/VisualTests.cs"
+            );
+        }
+
+        [Fact]
+        public void MixOfPatternsAcrossVariousFileTypes()
```
Comment (jozkee) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs:64]: Seems like Complex means `Include -> Exclude -> Include` or `Exclude -> Include -> Exclude`, if so, this test should also be prefixed as Complex?

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Internal/PatternContexts/CompositePatternContext.cs (hunk 1 above)
Comment (PranavSenthilnathan) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Internal/PatternContexts/CompositePatternContext.cs:17]: The type argument's naming is confusing since we don't actually care that it's a file info. This is instead using a `TState` pattern, so the implementation will just call the `test` with their `IPatternContext` and pass in this opaque state for the ride. It could also just be:

```cs
protected internal abstract PatternTestResult MatchPatternContexts(Func<IPatternContext, PatternTestResult> test);
```

which would force us to have a closure. I don't know if that matters so much here, but this method is from the existing code and I decided to just leave it as is.

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs (hunk 3 above)
Comment (PranavSenthilnathan) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs:178]: There's a typo - `Pettern` in `.Include("src/Internal/PetternContexts/")`. With the correct spelling this test passes.

I was ready to spend time debugging this but thankfully the VS spell checker caught and underlined this. One of the few times it was actually useful 😄

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs (hunk 4 above)
Comment (PranavSenthilnathan) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs:64]: Removed the `Complex` naming.

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs (hunk 2 above)
Comment (PranavSenthilnathan) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/OrderedPatternMatchingTests.cs:16]: removed

**Review by jozkee — APPROVED** [review]
