### PR TITLE
[wasm][AOT] fix codegen for small structs on stack

### LINKED ISSUE #117169: WasmTestOnChrome-ST-System.Memory.Tests errors
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1073221
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Buffers.Text.Tests.Base64ValidationUnitTests",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```
Console log: https://helixr1107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-100-preview6504d1246db64978ad/WasmTestOnChrome-ST-System.Memory.Tests/1/console.3c327d03.log?helixlogtype=result

### PR DESCRIPTION
**Pull request by pavelsavara**
Fixes https://github.com/dotnet/runtime/issues/117169

### CODE REVIEW

File: src/mono/mono/mini/mini-wasm.c [hunk 1]
```diff
@@ -808,8 +808,22 @@ mini_wasm_is_scalar_vtype (MonoType *type, MonoType **etype)
...
+				case 1:
+					*etype = m_class_get_byval_arg (mono_defaults.sbyte_class);
+					break;
+				case 2:
+					*etype = m_class_get_byval_arg (mono_defaults.int16_class);
+					break;
+				case 4:
+					*etype = mono_get_int32_type ();
+					break;
+				default:
```
Comment (kg) [inline src/mono/mono/mini/mini-wasm.c]: Should we also handle 8 bytes here?

**Review by kg — APPROVED** [review]
Great job finding this

File: src/mono/mono/mini/mini-wasm.c [hunk 2]
```diff
@@ -808,8 +808,22 @@ mini_wasm_is_scalar_vtype (MonoType *type, MonoType **etype)
 	}
 
 	if (etype) {
-		if (!(*etype))
-			*etype = mono_get_int32_type ();
+		if (!(*etype)) {
```
Comment (BrzVlad) [inline src/mono/mono/mini/mini-wasm.c]: For what kind of structs are we reaching this ? At a first glance it would seem like all cases should be handled above ? Could you add a comment ?

Comment (pavelsavara) [reply src/mono/mono/mini/mini-wasm.c]: The broken case is about empty struct, which has size 1. 
But @lewing suggested that maybe we don't want to scalarize empty structs anyway, so I'm testing that now with different code.

File: src/mono/mono/mini/mini-wasm.c (hunk 1 above)
Comment (pavelsavara) [reply src/mono/mono/mini/mini-wasm.c]: Yes, if we return to that version of the code. Thanks for noticing the gap.

**Comment by pavelsavara** [comment]
So, the current code fails with new [Log](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-118355-merge-aceb1fbb054d4794b8/WasmTestOnChrome-ST-System.Text.Json.Tests/1/console.d220f0b8.log?helixlogtype=result&skoid=8eda00af-b5ec-4be9-b69b-0919a2338892&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2025-08-05T13%3A31%3A26Z&ske=2025-08-05T14%3A31%3A26Z&sks=b&skv=2024-11-04&sv=2024-11-04&se=2025-08-05T14%3A31%3A26Z&sr=b&sp=rl&sig=dpM2bkN0RsrpEUTOYHgWV10FGOTurG6w5c68RzOFSUA%3D)

```
[12:47:40] fail: MONO_WASM: null function or function signature mismatch
RuntimeError: null function or function signature mismatch
    at aot_instances_aot_wrapper_gsharedvt_out_sig_u1_ (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[65086]:0x125abe1)
    at jit_call_cb (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[90060]:0x1873858)
    at mono_llvm_cpp_catch_exception (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[93346]:0x1966a01)
    at mono_llvm_catch_exception (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[93398]:0x196b064)
    at do_jit_call (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[89980]:0x1870381)
    at mono_interp_exec_method (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[89975]:0x1863188)
    at interp_entry (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[90054]:0x18734f4)
    at interp_entry_instance_0 (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[90072]:0x1874032)
    at aot_instances_aot_wrapper_gsharedvt_in_sig_void_this_ (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[64638]:0x124908b)
    at corlib_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_REF_TStateMachine_REF_ (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[35968]:0x940a1e)
    at corlib_System_Runtime_CompilerServices_AsyncIteratorMethodBuilder_MoveNext_TStateMachine_REF_TStateMachine_REF_ (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[35958]:0x9404bd)
    at aot_instances_aot_wrapper_gsharedvt_in_sig_void_this_cl40_Mono_dValueTuple_601_3cMono_dValueTuple_602_3cint_2c_20int_3e_3e_ (http://127.0.0.1:49169/_framework/dotnet.native.wasm:wasm-function[64707]:0x124bac3)
```

But it doesn't fail with the new assert I added. Right now, I'm confused about it.

**Review by lewing — APPROVED** [review]

File: src/mono/mono/mini/mini-wasm.c [hunk 3]
```diff
@@ -799,18 +799,20 @@ mini_wasm_is_scalar_vtype (MonoType *type, MonoType **etype)
...
 			if (etype)
 				*etype = t;
 		}
 	}
 
-	if (etype) {
-		if (!(*etype))
-			*etype = mono_get_int32_type ();
+	// empty struct
+	if (nfields == 0) {
```
Comment (lewing) [inline src/mono/mono/mini/mini-wasm.c]:
```suggestion
	if (nfields == 0 && etype) {
```
