### PR TITLE
Check Locations length before accessing

### LINKED ISSUE #87647: `ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer` threw an exception of type 'System.IndexOutOfRangeException'
Using fe866e6485e1ba4423e879c9d00a6c0edeecea4f I can't build `dotnet new wasmconsole` projects:

```
                     Microsoft (R) Visual C# Compiler version 4.7.0-3.23315.1 (7a7690ea) (TaskId:107)
                     Copyright (C) Microsoft Corporation. All rights reserved. (TaskId:107)
19:39:42.736   1:7>CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'. [/workspaces/runtime/artifacts/bin/Wasm.Build.Tests/Release/net8.0/browser-wasm/wbt/Debug_w1hn3hlk.m21/Debug_w1hn3hlk.m21.csproj]
                     Exception occurred with following context: (TaskId:107)
                     Compilation: Debug_w1hn3hlk.m21 (TaskId:107)
                     ISymbol: <Main>$ (Method) (TaskId:107)
                     System.IndexOutOfRangeException: Index was outside the bounds of the array. (TaskId:107)
                     at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__7_3(SymbolAnalysisContext context) (TaskId:107)
                     at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken) (TaskId:107)
                     ----- (TaskId:107)
                     Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111 (TaskId:107)
                     CompilerServer: server - server processed compilation - 9624bd43-5dab-4d62-9e51-fbed45800538 (TaskId:107)
                   Done executing task "Csc" -- FAILED. (TaskId:107)
```

- The failing build uses `microsoft.net.illink.tasks/8.0.0-preview.6.23314.14`, the changes for which include:
- The last passing build on CI was for 3c2ebd58 
   - which used sdk `8.0.100-preview.6.23314.19` to build WBT
	  - this sdk corresponds to https://github.com/dotnet/sdk/commit/6ce52a339247f9a848ff97fa418070b65de92b4d

- I tested with fe866e6485e1ba4423e879c9d00a6c0edeecea4f
   - which used sdk `8.0.100-preview.6.23315.7` to build WBT
	  - this sdk corresponds to https://github.com/dotnet/sdk/commit/1a17b18064c9bbf7dcb2155a03f2c92fe657fba1

- The changes in sdk (`6ce52a339247f9a848ff97fa418070b65de92b4d..1a17b18064c9bbf7dcb2155a03f2c92fe657fba1`) include:

```diff
+    <Dependency Name="Microsoft.NET.ILLink.Tasks" Version="8.0.0-preview.6.23314.14">
       <Uri>https://github.com/dotnet/runtime</Uri>
-      <Sha>54dab738de58291ebefc8ff0569a799efaff5d82</Sha>
+      <Sha>0a0fa137097595ad8ec0e2aa9ecffb524cd5df95</Sha>
     </Dependency>
```

And that includes https://github.com/dotnet/runtime/pull/87156 `Fix trim analyzer warning for inferred type arguments #87156`.

cc @sbomer

I will open a PR to use the older sdk for now, for Wasm.Build.Tests . And to trigger wasm jobs on linker changes.

### PR DESCRIPTION
**Pull request by sbomer**
Fixes an `IndexOutOfRangeException` thrown by the analyzer when analyzing method parameters for the implicitly generated Main method when using top-level statements. These method parameters don't have location info because they are not in user code.

I'm also adding checks in the other places this analyzer accesses `Locations[0]`, to be safe. But only one of these accesses was causing the crash reported in https://github.com/dotnet/runtime/issues/87647. @vitek-karas @agocke please let me know if you have opinions on whether we should do a more targeted fix.

Fixes https://github.com/dotnet/runtime/issues/87647

### CODE REVIEW

File: src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs [hunk 1]
```diff
@@ -94,13 +94,17 @@ public override void Initialize (AnalysisContext context)
 						return;
 
 					if (type.BaseType is INamedTypeSymbol baseType) {
-						foreach (var diagnostic in ProcessGenericParameters (baseType, type.Locations[0]))
-							context.ReportDiagnostic (diagnostic);
+						if (type.Locations.Length > 0) {
+							foreach (var diagnostic in ProcessGenericParameters (baseType, type.Locations[0]))
```
Comment (agocke) [inline src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs:98]: Seems like we could just return at the top if the type doesn't have a location.

**Comment by radical** [comment]
Wasm tests are still failing with the same error: 
`error AD0001: Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'. `

We use the latest 8.0 sdk to run the tests, so we would need to wait for this change to show up in a new sdk.
They can be ignored here.

File: src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs [hunk 2]
```diff
@@ -111,17 +113,23 @@ public override void Initialize (AnalysisContext context)
 						return;
 
 					var returnType = method.ReturnType;
-					foreach (var diagnostic in ProcessGenericParameters (returnType, method.Locations[0]))
-						context.ReportDiagnostic (diagnostic);
+					if (method.Locations.Length > 0) {
+						foreach (var diagnostic in ProcessGenericParameters (returnType, method.Locations[0]))
```
Comment (agocke) [inline src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs:117]: Looks like it still might be worth defining a new helper for this, since we're repeating the same code quite a bit.

Also -- is skipping the diagnostic in this instance the right behavior? Are we always guaranteed that a diagnostic cannot occur without a location?

Comment (vitek-karas) [reply src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs:117]: +1 to not feeling comfortable disabling the code if there's no location. Pretty much any compiler generated code will not have a location. For the most part the analyzer should not see it, but if it does happen, I think we should still analyze it. Unless not having location is defined to mean something in Roslyn... and that meaning would imply that analyzing it is not a good idea.

File: src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs [hunk 3]
```diff
@@ -364,12 +379,15 @@ static void VerifyDamOnPropertyAndAccessorMatch (SymbolAnalysisContext context,
...
-					DiagnosticDescriptors.GetDiagnosticDescriptor (DiagnosticId.DynamicallyAccessedMembersConflictsBetweenPropertyAndAccessor),
-					methodSymbol.AssociatedSymbol!.Locations[0],
-					methodSymbol.AssociatedSymbol!.GetDisplayName (),
-					methodSymbol.GetDisplayName ()
-				));
+				var associatedSymbol = methodSymbol.AssociatedSymbol!;
+				if (associatedSymbol.Locations.Length > 0) {
+					context.ReportDiagnostic (Diagnostic.Create (
+						DiagnosticDescriptors.GetDiagnosticDescriptor (DiagnosticId.DynamicallyAccessedMembersConflictsBetweenPropertyAndAccessor),
+						associatedSymbol.Locations[0],
```
Comment (vitek-karas) [inline src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs:386]: The diagnostics doesn't seem to require location (it's explicitly annotated as nullable), so I think a better solution would be to just pass in null if we don't have it.

**Review by vitek-karas — CHANGES_REQUESTED** [review]

File: src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs (hunk 3 above)
Comment (agocke) [reply src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs:386]: There's also a singleton Location.None

**Review by agocke — APPROVED** [review]
LGTM, thanks!

File: src/tools/illink/test/ILLink.RoslynAnalyzer.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs [hunk 4]
```diff
@@ -39,9 +39,14 @@ public static DiagnosticResult Diagnostic (DiagnosticId diagnosticId)
 			=> CSharpAnalyzerVerifier<TAnalyzer, XUnitVerifier>.Diagnostic (DiagnosticDescriptors.GetDiagnosticDescriptor (diagnosticId));
 
 		/// <inheritdoc cref="AnalyzerVerifier{TAnalyzer, TTest, TVerifier}.VerifyAnalyzerAsync(string, DiagnosticResult[])"/>
-		public static async Task VerifyAnalyzerAsync (string src, (string, string)[]? analyzerOptions = null, IEnumerable<MetadataReference>? additionalReferences = null, params DiagnosticResult[] expected)
+		public static async Task VerifyAnalyzerAsync (
+			string src,
+			bool consoleApplication,
```
Comment (vitek-karas) [inline src/tools/illink/test/ILLink.RoslynAnalyzer.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs:44]: Nit: Make it `false` by default to avoid changing so many lines - and also to simplify the most common usage.

**Review by vitek-karas — APPROVED** [review]
