### PR TITLE
[wasm][debugger] Optional param fix 56251

### LINKED ISSUE #56251: [wasm][debugger] method call that skips optional parameters, fails on preview7
In the blazorwasm template project, `FetchData.razor`, I added a new `WeatherForecast.GetTempFWithBias` method:

```csharp
   public class WeatherForecast
    {
		...

        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
        public int GetTempFWithBias(int bias=0) => TemperatureF + bias;
    }
```

```csharp
    protected override async Task OnInitializedAsync()
    {
        forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("sample-data/weather.json");
		var f1 = forecasts[0];
		Console.WriteLine($"f1: {f1}"); // <--- breakpoint
	}
```

In the immediate window:
1. `f1.GetTempFWithBias(3)` works fine
2. but `f1.GetTempFWithBias()` doesn't return anything

cc @thaystg

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/56251.

Enables evaluation of functions with default parameters.

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 1]
```diff
@@ -406,6 +406,31 @@ public MethodInfo(AssemblyInfo assembly, MethodDefinitionHandle methodDefHandle,
             localScopes = pdbMetadataReader.GetLocalScopes(methodDefHandle);
         }
 
+        public List<ParameterInfo> GetMethodParams()
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:409]: This is already in `MethodInfo` class.
```suggestion
        public List<ParameterInfo> GetParameters()
```

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 2]
```diff
@@ -529,6 +554,31 @@ public bool IsLexicallyContainedInMethod(MethodInfo containerMethod)
                     (EndLocation.Line == containerMethod.EndLocation.Line && EndLocation.Column < containerMethod.EndLocation.Column));
     }
 
+    internal class ParameterInfo
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:557]: This can be a C# record.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 3]
```diff
@@ -417,24 +419,46 @@ public async Task<JObject> Resolve(InvocationExpressionSyntax method, Dictionary
...
                     if (isTryingLinq == 0)
                         commandParamsObjWriter.WriteObj(objectId, context.SdbAgent);
+
                     if (method.ArgumentList != null)
                     {
-                        commandParamsObjWriter.Write((int)method.ArgumentList.Arguments.Count + isTryingLinq);
+                        var methodInfo = await context.SdbAgent.GetMethodInfo(methodId, token);
+                        int passedParamCnt = method.ArgumentList.Arguments.Count;
+                        var methodParamsInfo = new List<ParameterInfo>();
+                        if (methodInfo?.Info != null)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:428]: When can this be null?

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 4]
```diff
@@ -406,6 +406,31 @@ public MethodInfo(AssemblyInfo assembly, MethodDefinitionHandle methodDefHandle,
             localScopes = pdbMetadataReader.GetLocalScopes(methodDefHandle);
         }
 
+        public List<ParameterInfo> GetMethodParams()
+        {
+            var paramsInfo = new List<ParameterInfo>();
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:411]: Keep this as a field, and populate it only the first time.
And this should be an array, since its size is going to be fixed, and known.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 5]
```diff
@@ -417,24 +419,46 @@ public async Task<JObject> Resolve(InvocationExpressionSyntax method, Dictionary
...
+                        {
+                            methodParamsInfo = methodInfo.Info.GetMethodParams();
+                            // if less params then the function has was passed then some of them may be optional
+                            // if more, it will ensure to produce an error
+                            var optionalParamsCnt = methodParamsInfo.Count(p => p.HasDefaultValue);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:433]: Number of options params can be a property of methodInfo

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 6]
```diff
@@ -417,24 +419,46 @@ public async Task<JObject> Resolve(InvocationExpressionSyntax method, Dictionary
...
+                                if (arg.Expression is IdentifierNameSyntax)
+                                {
+                                    var argParm = arg.Expression as IdentifierNameSyntax;
+                                    if (!await commandParamsObjWriter.WriteJsonValue(memberAccessValues[argParm.Identifier.Text], context.SdbAgent, token))
+                                        return null;
+                                }
                             }
+                            // optional arguments that were not overritten
+                            else if (!await commandParamsObjWriter.WriteConst(methodParamsInfo[i].TypeCode, methodParamsInfo[i].Value, context.SdbAgent, token))
+                                return null;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:461]: just to make it slightly easier to read.

```suggestion
                            else
                            {
                                if (!await commandParamsObjWriter.WriteConst(methodParamsInfo[i].TypeCode, methodParamsInfo[i].Value, context.SdbAgent, token))
                                    return null;
                            }
```

Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:461]: This should throw an exception, since failing to write the const here shouldn't be normal.

File: src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs [hunk 7]
```diff
@@ -851,6 +851,33 @@ public static void Evaluate()
...
+            public short GetInt16(short param = 1) => param;
+            public ushort GetUInt16(ushort param = 1) => param;
+            public int GetInt32(int param = 1) => param;
+            public uint GetUInt32(uint param = 1) => param;
+            public long GetInt64(long param = 1) => param;
+            public ulong GetUInt64(ulong param = 1) => param;
+            public float GetSingle(float param = 1.23f) => param;
+            public double GetDouble(double param = 1.23) => param;
+            public string GetString(string param = "1.23") => param;
+            public bool GetNull(object param = null) => param == null ? true : false;
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs:872]: Add tests for `string?`, and `int?` also

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 8]
```diff
@@ -1038,6 +1038,34 @@ public async Task EvaluateLocalObjectFromAssemblyNotRelatedButLoaded()
...
             });
+
+        [Fact]
+        public async Task EvaluateMethodWithDefaultParam() => await CheckInspectLocalsAtBreakpointSite(
+            $"DebuggerTests.DefaultParamMethods", "Evaluate", 2, "Evaluate",
+            $"window.setTimeout(function() {{ invoke_static_method ('[debugger-test] DebuggerTests.DefaultParamMethods:Evaluate'); 1 }})",
+            wait_for_event_fn: async (pause_location) =>
+            {
+                var id = pause_location["callFrames"][0]["callFrameId"].Value<string>();
+                await EvaluateOnCallFrameAndCheck(id,
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1049]: Add tests that pass value for the optional params.
And also maybe a test to mix some of these.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 9]
```diff
@@ -1038,6 +1038,34 @@ public async Task EvaluateLocalObjectFromAssemblyNotRelatedButLoaded()
...
+                   ("test.GetByte()", TNumber(1)),
+                   ("test.GetSByte()", TNumber(1)),
+                   ("test.GetInt16()", TNumber(1)),
+                   ("test.GetUInt16()", TNumber(1)),
+                   ("test.GetInt32()", TNumber(1)),
+                   ("test.GetUInt32()", TNumber(1)),
+                   ("test.GetInt64()", TNumber(1)),
+                   ("test.GetUInt64()", TNumber(1)),
+                //    ("test.GetChar()", TString("A")), //fails, Evaluate of this datatype symbol not implemented yet (for non optional parameters either)
+                   ("test.GetString()", TString("1.23")),
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1059]: Test with passing a string, and passing a null also.

**Comment by radical** [comment]
```
  Failed DebuggerTests.EvaluateOnCallFrameTests.EvaluateMethodWithDefaultParam [217 ms]
  Error Message:
   [[test.GetSingle()] Value for json property named description didn't match.]

Expected: 1,23
Actual:   1.23
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 3 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:428]: E.g calling .ToList() on an object. So each non-user function.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs (hunk 8 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1049]: They were already there, I will change the name for *GetInt32DefaultAndRequiredParam* so that it will be better visible.
```
("test.GetInt32TwoParams(2)", TNumber(5)),
 ("test.GetInt32TwoParams(3, 2)", TNumber(5))
```

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 10]
```diff
@@ -529,6 +561,15 @@ public bool IsLexicallyContainedInMethod(MethodInfo containerMethod)
...
     }
 
+    internal record ParameterInfo(string name, ConstantTypeCode? typeCode = null, byte[] value = null)
+    {
+        public string Name => name;
+        public ConstantTypeCode? TypeCode => typeCode;
+        public byte[] Value => value;
+
+        public bool HasDefaultValue = value != null;
+    }
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:571]: You only need to add `HasDefaultValue` property.
```suggestion
    internal record ParameterInfo(string Name, ConstantTypeCode? TypeCode = null, byte[] Value = null)
    {
        public bool HasDefaultValue => value != null;
    }
```

The rest will get declared as properties automatically, because this is a `record`.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 11]
```diff
@@ -527,6 +528,65 @@ public void WriteByteArray(byte[] bytes)
...
+                case ConstantTypeCode.Single:
+                    Write(ElementType.R4, BitConverter.ToSingle(bytes, 0));
+                    return true;
+                case ConstantTypeCode.Double:
+                    Write(ElementType.R8, BitConverter.ToDouble(bytes, 0));
+                    return true;
+                case ConstantTypeCode.String:
+                    // encoded chars are separated by trailing nulls: '\0' that indicate the end of string,
+                    // leaving them results in cutting the string after 1st char
+                    var stringVal = Encoding.UTF8.GetString(bytes).Replace("\0", "");
```
Comment (lewing) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:577]: These are going to be utf-16 strings so use
```suggestion
                    var stringVal = Encoding.Unicode.GetString(bytes);
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 12]
```diff
@@ -527,6 +528,65 @@ public void WriteByteArray(byte[] bytes)
             Write(bytes);
         }
 
+        public async Task<bool> WriteConst(ConstantTypeCode? type, byte[] bytes, MonoSDBHelper SdbHelper, CancellationToken token)
```
Comment (lewing) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:531]: Would it make sense to move the Default extraction logic into ParameterInfo and avoid having the binary writer understand the details of the typecode and byte packing?

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 13]
```diff
@@ -231,7 +232,8 @@ private string ConvertJSToCSharpLocalVariableAssignment(string idName, JToken va
                         break;
                     }
                     case "number":
-                        valueRet = value?.Value<double>();
+                        //casting to double and back to string would loose precision; so casting straight to string
```
Comment (lewing) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:235]: was this causing an issue?  I think the json representation should round trip?

**Review by lewing — COMMENTED** [review]
Looking good, I've added a couple comments.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 14]
```diff
@@ -417,23 +419,48 @@ public async Task<JObject> Resolve(InvocationExpressionSyntax method, Dictionary
...
+                        int passedParamCnt = method.ArgumentList.Arguments.Count;
+                        ParameterInfo[] methodParamsInfo = methodInfo.Info.ParametersInfo;
+
+                        // if less params then the function has was passed then some of them may be optional
+                        // if more, it will ensure to produce an error
+                        int methodParamsCnt = methodParamsInfo.Length;
+                        int optionalParamsCnt = methodInfo.Info.OptionalParametersCnt;
+                        int sentToDebuggerParamsCnt = methodParamsCnt;
+                        if (passedParamCnt > methodParamsCnt || passedParamCnt + optionalParamsCnt < methodParamsCnt)
+                            sentToDebuggerParamsCnt = passedParamCnt;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:435]: `sentToDebuggerParamsCnt` should always be equal to `methodParamsCnt`.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 15]
```diff
@@ -417,23 +419,48 @@ public async Task<JObject> Resolve(InvocationExpressionSyntax method, Dictionary
...
+                                {
+                                    if (!await commandParamsObjWriter.WriteConst(arg.Expression as LiteralExpressionSyntax, context.SdbAgent, token))
+                                        return null;
+                                }
+                                if (arg.Expression is IdentifierNameSyntax)
+                                {
+                                    var argParm = arg.Expression as IdentifierNameSyntax;
+                                    if (!await commandParamsObjWriter.WriteJsonValue(memberAccessValues[argParm.Identifier.Text], context.SdbAgent, token))
+                                        return null;
+                                }
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:457]: Add an `else` to fail in any other case.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 11 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:577]: And add a test for such utf-16 strings ;)

**Review by radical — CHANGES_REQUESTED** [review]

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 16]
```diff
@@ -530,6 +562,84 @@ public bool IsLexicallyContainedInMethod(MethodInfo containerMethod)
                     (EndLocation.Line == containerMethod.EndLocation.Line && EndLocation.Column < containerMethod.EndLocation.Column));
     }
 
+    internal class ParameterInfo
+    {
+        public string Name { get; private set; }
+
+        public bool HasDefaultValue { get; private set; }
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:569]: Do we really need this separately? How about we remove this, and rename `Value` to `DefaultValue`? The caller can easily check `DefaultValue != null` to see if there is a valid or not.

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 17]
```diff
@@ -530,6 +562,84 @@ public bool IsLexicallyContainedInMethod(MethodInfo containerMethod)
...
+
+        public ElementType? TypeCode { get; private set; }
+
+        public object Value { get; set; }
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:573]: You can use `init` instead of all `private set` for the properties. It will allow setting the values only in the constructor.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 18]
```diff
@@ -417,23 +419,61 @@ public async Task<JObject> Resolve(InvocationExpressionSyntax method, Dictionary
...
+                        var methodInfo = await context.SdbAgent.GetMethodInfo(methodId, token);
+                        if (methodInfo != null) //null for e.g. ToList()
+                        {
+                            methodParamsInfo = methodInfo.Info.ParametersInfo.ToList();
+                            int methodParamsCnt = methodParamsInfo.Count;
+                            if (passedArgsCnt > methodParamsCnt)
+                                throw new ReturnAsErrorException($"Unable to evaluate method '{methodName}. Too many arguments passed.", "ArgumentError");
+                            int optionalParamsCnt = methodInfo.Info.OptionalParametersCnt;
+                            if (passedArgsCnt + optionalParamsCnt >= methodParamsCnt)
+                                sentToDebuggerParamsCnt = methodParamsCnt;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:437]: `sentToDebuggerParamsCnt` should always be equal to `methodParamsCnt`. CLR doesn't really support optional parameters. It's a C# language level feature. If you call a method with some optional args missing, then the compiler use the default param values for them. So, the method is always called with all the args.

@thaystg I'm assuming that this holds true when using the debug api too.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 19]
```diff
@@ -417,23 +419,61 @@ public async Task<JObject> Resolve(InvocationExpressionSyntax method, Dictionary
...
                         commandParamsObjWriter.WriteObj(objectId, context.SdbAgent);
+
                     if (method.ArgumentList != null)
                     {
-                        commandParamsObjWriter.Write((int)method.ArgumentList.Arguments.Count + isTryingLinq);
+                        int passedArgsCnt = method.ArgumentList.Arguments.Count;
+                        int sentToDebuggerParamsCnt = passedArgsCnt;
+                        var methodParamsInfo = new List<ParameterInfo>();
+                        var methodInfo = await context.SdbAgent.GetMethodInfo(methodId, token);
+                        if (methodInfo != null) //null for e.g. ToList()
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:429]: Why would it be null for `ToList()`? Is it because it's an extension method?
If so, and we are not supporting that in this PR, then this should fail with a message, if `methodInfo == null`.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 20]
```diff
@@ -17,6 +17,7 @@
 using System.Text;
 using System.Runtime.CompilerServices;
 using System.Diagnostics;
+using System.Reflection.Metadata;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:20]: Is this needed?

**Review by radical — CHANGES_REQUESTED** [review]
This is looking good! The only remaining comment I have is that we should be populating `ParametersInfo[]` lazy as it is used in only a narrow, uncommon case.

File: src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs [hunk 21]
```diff
@@ -851,6 +851,55 @@ public static void Evaluate()
...
+            public short GetInt16(short param = 1) => param;
+            public ushort GetUInt16(ushort param = 1) => param;
+            public int GetInt32(int param = 1) => param;
+            public uint GetUInt32(uint param = 1) => param;
+            public long GetInt64(long param = 1) => param;
+            public ulong GetUInt64(ulong param = 1) => param;
+            public float GetSingle(float param = 1.23f) => param;
+            public double GetDouble(double param = 1.23) => param;
+            public string GetString(string param = "1.23") => param;   
+            public string GetUnicodeString(string param = "żółć") => param;
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs:875]:
```suggestion
            public string GetString(string param = "1.23") => param;
            public string GetUnicodeString(string param = "żółć") => param;
```

**Review by radical — APPROVED** [review]
Looks great 👍
