### PR TITLE
Correctly identify when an unmanaged exception hijack is occurring and display unmanaged frames in callstack

### LINKED ISSUE #105116: x86 Interop Call stack incorrect when stopped in native exception filter
### Description

In .NET 9 preview 6 there is a regression in x86 interop call stacks. When stopped in a native exception filter, the leaf native code range is hidden and only the managed range is shown.

### Reproduction Steps

1. Extract this solution: [x86InteropTest.zip](https://github.com/user-attachments/files/16289299/x86InteropTest.zip)
2. Open the solution in Visual Studio
3. Open NativeLib\dllmain.cpp, and set a breakpoint on line 25
4. Start debugging

### Expected behavior

ICorDebugThread.EnumerateChains should return a leaf chain which is unmanaged

### Actual behavior

ICorDebugThread.EnumerateChains returns a managed leaf chain. Here is the chain object (mscordbi.dll!ShimChain):

| Name | Value | Type |
|-|-|-|
| ICorDebugChain | {...} | mscordbi.dll!ICorDebugChain |
| m_context | {ContextFlags=0x00010007 Dr0=0x07d1c9b0 Dr1=0x5b68240b ...} | mscordbi.dll!DT_CONTEXT |
| m_fpRoot | {m_sp=0x00c0eeb4 } | mscordbi.dll!FramePointer |
| m_pStackWalk | 0x0873c430 {m_stackChains={...} m_stackFrames={...} m_pChainEnumList=0x086eb860 {m_pStackWalk=0x0873c430 {...} ...} ...} | mscordbi.dll!ShimStackWalk * |
| m_refCount | {m_val=0x00000002 } | mscordbi.dll!Volatile<unsigned long> |
| m_chainIndex | 0x00000000 | unsigned int |
| m_frameStartIndex | 0x00000000 | unsigned int |
| m_frameEndIndex | 0x00000001 | unsigned int |
| m_chainReason | CHAIN_ENTER_MANAGED (0x00000080) | mscordbi.dll!CorDebugChainReason |
| m_fIsManaged | 0x00000001 | int |
| m_fIsNeutered | 0x00000000 | int |

### Regression?

This is a regression from .NET 9 preview 5

### Known Workarounds

None

### Configuration

Interop debugging is only on win-x86 and win-x64. Of the two, this only repros on x86.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tommcdon**
Fixes https://github.com/dotnet/runtime/issues/105116

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]

File: src/coreclr/debug/di/rspriv.h [hunk 1]
```diff
@@ -2879,6 +2879,10 @@ class IProcessShimHooks
     virtual void RequestSyncAtEvent()= 0;
 
     virtual bool IsThreadSuspendedOrHijacked(ICorDebugThread * pThread) = 0;
+
+#ifdef FEATURE_INTEROP_DEBUGGING
+    virtual bool IsUnmanagedThreadHijacked(ICorDebugThread * pICorDebugThread) = 0;
```
Comment (mikelle-rogers) [inline src/coreclr/debug/di/rspriv.h:2884]: Why did you need this here and something very similar on line 3470?

**Review by mikelle-rogers — COMMENTED** [review]
Looks good to me.

File: src/coreclr/debug/di/rspriv.h (hunk 1 above)
Comment (tommcdon) [reply src/coreclr/debug/di/rspriv.h:2884]: > Why did you need this here and something very similar on line 3470?

We need to access the `IsUnmanagedThreadHijacked` API from `ShimStackWalk`, which stores `CordbProcess` via a `IProcessShimHooks` interface:
 https://github.com/dotnet/runtime/blob/432c4a09418b52cc8b19c385504f14aae2a39038/src/coreclr/debug/di/shimpriv.h#L571

Since we do not wish to add a new public API to `ICorDebugProcess`, the `IsUnmanagedThreadHijacked` API must be declared in both the `IProcessShimHooks` interface  as well as the `CordbProcess` implementation class in rspriv.h for `ShimStackWalk` to use it.  

Hope this helps!
