### PR TITLE
ARM64-SVE: Emit `AddSequentialAcross` correctly

### LINKED ISSUE #106180: ARM-SVE: AddSequentialAcross() is defined incorrectly
Note how the C++ API uses floats, but C# uses vectors:
```
        /// <summary>
        /// float64_t svadda[_f64](svbool_t pg, float64_t initial, svfloat64_t op)
        ///   FADDA Dtied, Pg, Dtied, Zop.D
        /// </summary>
        public static unsafe Vector<double> AddSequentialAcross(Vector<double> initial, Vector<double> value) => AddSequentialAcross(initial, value);
```

[FADDA](https://docsmirror.github.io/A64/2023-09/fadda_v_p_z.html) instruction:
`FADDA <V><dn>, <Pg>, <V><dn>, <Zm>.<T>`

Output from coreclr:
`IN0021:             fadda   z17, p0, z17, z16.s`

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #106180. `AddSequentialAcross` now looks like this in JIT disasms:
```asm
ptrue   p0.d
fadda   v17.d, p0, v17.d, z16.d
```

We no longer emit `movprfx`, and the destination SIMD register is printed correctly (I think this is everything we needed to fix for this intrinsic). I also found a couple of other nearby instruction formats that needed to be fixed in `emitDispInsSveHelp`.

`AddSequentialAcross` stress tests are passing. @dotnet/arm64-contrib PTAL, thanks!

### CODE REVIEW

File: src/coreclr/jit/emitarm64sve.cpp [hunk 1]
```diff
@@ -14823,27 +14823,38 @@ void emitter::emitDispInsSveHelp(instrDesc* id)
...
         case IF_SVE_CO_3A: // ........xx...... ...gggmmmmmddddd -- SVE conditionally extract element to general register
-        case IF_SVE_HJ_3A: // ........xx...... ...gggmmmmmddddd -- SVE floating-point serial reduction (predicated)
             emitDispReg(id->idReg1(), size, true);                                                 // ddddd
             emitDispLowPredicateReg(id->idReg2(), insGetPredicateType(fmt), id->idInsOpt(), true); // ggg
             emitDispReg(id->idReg1(), size, true);                                                 // ddddd
             emitDispSveReg(id->idReg3(), id->idInsOpt(), false);                                   // mmmmm
             break;
 
+        // <V><dn>, <Pg>, <V><dn>, <Zm>.<T>
+        case IF_SVE_HJ_3A: // ........xx...... ...gggmmmmmddddd -- SVE floating-point serial reduction (predicated)
```
Comment (a74nh) [inline src/coreclr/jit/emitarm64sve.cpp:14836]: I'm surprised this was never caught in the codegen testing. Although it's possible something else changed around it.

**Review by a74nh — APPROVED** [review]
This LGTM

**Comment by amanasifkhalid** [comment]
@TIHan can you PTAL? Thanks!

**Comment by JulieLeeMSFT** [comment]
@TIHan, @dotnet/arm64-contrib, please review this PR before RC1 snap.

**Review by TIHan — APPROVED** [review]
LGTM, straightforward change.
