### PR TITLE
Make WindowsServiceLifetime gracefully stop

### LINKED ISSUE #62579: Windows service infrequently results in error 1067 on stop operation
### Description

.NET 6 published application sometimes crashes on service stop operation. I created a web application from the template and only added the `Microsoft.Extensions.Hosting.WindowsServices` (version 6.0.0) package and called `UseWindowsService()` to make sure the application listens for service controller requests.

Here is the code:
```csharp
using Microsoft.Extensions.Hosting.WindowsServices;

var options = new WebApplicationOptions
{
    Args = args,
    ContentRootPath = WindowsServiceHelpers.IsWindowsService() ? AppContext.BaseDirectory : default
};

var builder = WebApplication.CreateBuilder(options);

// Add services to the container.
builder.Services.AddRazorPages();
builder.Host.UseWindowsService();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
}

app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();
```

### Reproduction Steps

Repository with code, script and repro steps: https://github.com/zryska/net6-repro

1. Create a new Web application using a template
2. Make the changes to add UseWindowsService() call as shown above
2. Publish the application as SFD or FDD for win-x64 runtime
2. Create a new service using `sc create` command
3. Start the service and verify it's running
4. Stop the service
5. Start the service
6. Repeat steps 4 and 5 until the issue is reproduced

It can be done through the services UI or using a script. On my system it usually happens 1 time out of 10 graceful shutdowns - but it isn't deterministic.

When done through services UI the following will be displayed:
image

Even log => `Windows Logs -> System` will contain the following message (when done through script or UI):

```
The .NET6 test service service terminated unexpectedly.  It has done this 26 time(s).
```

### Expected behavior

Service stops gracefully every time.

### Actual behavior

Non-graceful shutdowns are happening.

### Regression?

_No response_

### Known Workarounds

Explicitly assigning value to `ServiceName` fixes the problem.
```
builder.Host.UseWindowsService(o => o.ServiceName = "AnyServiceName");
```

### Configuration

.NET version: .NET 6.0.100
OS version: Windows 10 pro build 19044.1348
Architecture: x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ericstj**
WindowsServiceLifetime was not waiting for ServiceBase to stop the service.  As a result we would sometimes end the process before notifying service control manager that the service had stopped -- resulting in an error in the eventlog and sometimes a service restart.

We also were permitting multiple calls to Stop to occur - through SCM callbacks, and through public API.  We must not call SetServiceStatus again once the service is marked as stopped.

Fixes: #62579

### CODE REVIEW

File: src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs [hunk 1]
```diff
@@ -647,6 +647,12 @@ public static void Run(ServiceBase service)
 
         public void Stop()
         {
+            if (_status.currentState == ServiceControlStatus.STATE_STOPPED || _status.currentState == default)
```
Comment (ericstj) [inline src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs:650]: The docs for [SetServiceStatus](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-setservicestatus) mention it must never be called after the service state is stopped:
> If the status is SERVICE_STOPPED, perform all necessary cleanup and call SetServiceStatus one time only. This function makes an LRPC call to the SCM. The first call to the function in the SERVICE_STOPPED state closes the RPC context handle and any subsequent calls can cause the process to crash.

We were actually hitting this in the common case, since we'd call back into the IHostLifetime StopAsync when SCM stopped the service.  Depending on how long it was since the first stop call we were seeing crashes (this was much more common when I inserted delay).  This check just prevents that re-entrancy.

It doesn't solve a race condition where Stop might be called from multiple threads (resulting in violating this constraint) or if an application itself called Stop at same time SCM was sending the stop message.  If we wanted to solve for these cases we'd need to introduce locking.

Comment (ericstj) [reply src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs:650]: That latter case might actually be important -- since IHostLifetime.StopAsync gets called on a different thread and there is no guaranteed ordering that it happens after SCM's queued DeferredStop completes (that's the whole reason we had to wait in StopAsync), the two could be running concurrently.  I think we need better protection against this.

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs [hunk 2]
```diff
@@ -92,14 +93,14 @@ private void Run()
...
             }
+            _serviceStopped.TrySetResult(null);
         }
 
         public Task StopAsync(CancellationToken cancellationToken)
         {
-            // Avoid deadlock where host waits for StopAsync before firing ApplicationStopped,
-            // and Stop waits for ApplicationStopped.
+            // Stop will cause the ServiceBase.Run method to complete and return, which completes _serviceStopped.
             Task.Run(Stop, CancellationToken.None);
```
Comment (ericstj) [inline src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:102]: This stop is redundant in the case that we received a stop signal from SCM.  It's here for the case where the app is deciding to stop the service itself.  We should try to avoid having this run concurrently with SCM's DeferredStop.

**Review by stephentoub — APPROVED** [review]
Is there any kind of test that can be added here?

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 2 above)
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:102]: One thing that would be ordered is the call of OnStop.  We could set a flag at that point and honor here to avoid calling Stop if OnStop has already been called.

**Comment by ericstj** [comment]
> Is there any kind of test that can be added here?

Yeah but needs some work as we need a service project.  Plan to do so before moving out of draft.

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs [hunk 3]
```diff
@@ -18,8 +18,10 @@ namespace Microsoft.Extensions.Hosting.WindowsServices
     public class WindowsServiceLifetime : ServiceBase, IHostLifetime
     {
         private readonly TaskCompletionSource<object?> _delayStart = new TaskCompletionSource<object?>(TaskCreationOptions.RunContinuationsAsynchronously);
+        private readonly TaskCompletionSource<object?> _serviceStopped = new TaskCompletionSource<object?>(TaskCreationOptions.RunContinuationsAsynchronously);
         private readonly ManualResetEventSlim _delayStop = new ManualResetEventSlim();
         private readonly HostOptions _hostOptions;
+        private bool _isStopped;
```
Comment (stephentoub) [inline src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:24]: The naming here between "isStopped" and "serviceStopped" is a little confusing.  What is the "is" referring to if not "service"?  I'm interpreting "isStopped" more as "stopRequested"?

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs [hunk 4]
```diff
@@ -92,14 +94,18 @@ private void Run()
...
 
         public Task StopAsync(CancellationToken cancellationToken)
         {
-            // Avoid deadlock where host waits for StopAsync before firing ApplicationStopped,
-            // and Stop waits for ApplicationStopped.
-            Task.Run(Stop, CancellationToken.None);
-            return Task.CompletedTask;
+            if (!_isStopped)
+            {
+                Task.Run(Stop, CancellationToken.None);
```
Comment (stephentoub) [inline src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:104]: What do you want to have happen if Stop throws an exception?  Right now that exception is going to be eaten by the Task that's returned from Run and ignored (and at some point later the TaskSchedule.UnobservedTaskException event might be raised).

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 3 above)
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:24]: I was trying to represent what SCM thought about the service state.  I was running into a conflict in name between the task `serviceStopped` and this flag (I even inadvertently named them the same thing at first).  I'm open to other naming suggestions that would be clearer.

Maybe for the task use `serviceRunComplete` or `serviceDispatcherStopped` then for the flag use `serviceStopped`?

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 4 above)
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:104]: It was previously ignored, so I left it that way.  I suppose it wouldn't hurt to throw here?  
This is the body of that task.  It would throw if for some reason it failed to set the service state to stopped.
https://github.com/dotnet/runtime/blob/3f5cb1805ea040e0869c1da8b8a7476a223ce4d2/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs#L502-L527
This is the caller:
https://github.com/dotnet/runtime/blob/3f5cb1805ea040e0869c1da8b8a7476a223ce4d2/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L149

To capture the exception would you reccomend `return Task.Run(Stop, CancellationToken.None).ContinueWith(_serviceStopped.Task)`?

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs [hunk 5]
```diff
@@ -92,14 +94,18 @@ private void Run()
             {
                 _delayStart.TrySetException(ex);
             }
+            _serviceStopped.TrySetResult(null);
```
[the remark this answers is not in the document]
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:97]: Your other question about exceptions makes me wonder who would ever observe an exception thrown from this.  I think we could also propagate an exception if one occurred during stop - though it would likely be our own, since the only thing running on the dispatcher thread is ServiceBase.

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 4 above)
Comment (stephentoub) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:104]: It depends on what we want to have happen.

If Stop throws an exception, does that mean _serviceStopped will never complete?  If that were the case someone doing `await StopAsync()` would hang, because the Task they're awaiting would never complete.  If it's really the case that either both complete successfully or at most one fails, then I think we want to do this:
```C#
public async Task StopAsync(CancellationToken cancellationToken)
{
    if (!isStopped)
    {
        await Task.Run(Stop, CancellationToken.None).ConfigureAwait(false);
    }

    return await _serviceStopped.Task;
}
```

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (stephentoub) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:97]: >  I think we could also propagate an exception if one occurred during stop - though it would likely be our own, since the only thing running on the dispatcher thread is ServiceBase.

That's another answer to the other question: if we catch all exceptions inside of Stop and use one to complete _serviceStopped, then the code in StopAsync can remain as is, as Stop itself would never fail and would instead propagate its exception to _serviceStopped.

[the remark this answers is not in the document]
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:97]: I think I'll do this for correctness.  There's no reason to hide exceptions from framework code -- even if we don't expect them.  That just makes things harder to debug in the future.

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 4 above)
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:104]: Got it.  This is where I landed as well after reding your comments.  Thanks for reminding me about `async` keyword to save my hackery with ContinueWith. 

I think I can actually force this path to throw as well, with user-code that overrides OnStop.  I'll write some tests for that.

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs [hunk 6]
```diff
@@ -92,14 +94,18 @@ private void Run()
...
         }
 
         public Task StopAsync(CancellationToken cancellationToken)
```
[the remark this answers is not in the document]
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:100]: Yes it's part of the interface https://github.com/dotnet/runtime/blob/967250cc86b4c613015066b47b882e7424fdb590/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/IHostLifetime.cs#L27
Funny enough, none of the other implementations of this interface actually do anything in StopAsync so the cancellationToken is likely there because we asked for it in FxDC ;).

While we can't cancel the call to Stop, we could check before running it (throwing OCE right before the call to Stop by passing in the token), we could also cancel waiting for Run to complete.  That doesn't really cancel the work since the thread would still be active running the native service dispatcher loop.  We cannot "rollback" anything once the `Stop` method has been called - that's a one way operation.

What's our thinking on this - what's the right meaning for cancel on a Stop operation?

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 3 above)
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:24]: I gave another try at the naming.  Will see if that's better.

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (stephentoub) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:100]: > we could check before running it (throwing OCE right before the call to Stop by passing in the token), we could also cancel waiting for Run to complete

We should do that upfront check.  We could also pass the token to Task.Run, which will cause that task to be canceled if cancellation is requested before the delegate has been invoked.  Canceling the wait on that Task.Run (e.g. via a WaitAsync) is a larger leap, as it means you end up having work that's pending out there that's become disconnected from the caller's Task and they have no way to track it at that point; we should avoid doing that unless we have a very good reason. Of course, if you're about to tear down the process anyway, maybe it doesn't matter.

[the remark this answers is not in the document]
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs]: Sounds good I made this change and added a test.

> Of course, if you're about to tear down the process anyway, maybe it doesn't matter.

I'm reluctant to do this.  Not allowing Run to exit gracefully means SCM may not treat the service as stopped, and if it's an auto-start service, it will *restart* it.

**Comment by ericstj** [comment]
These tests are failing in CI but passing locally:
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-83892-merge-4425fb85bd7d4689a3/Microsoft.Extensions.Hosting.WindowsServices.Tests/1/console.f3be89b1.log?helixlogtype=result
I pulled the test payload and it's missing bindingRedirects for System.Runtime.CompilerServices.Unsafe 😕 I have those when building locally - emitted by RAR.  Might need to pull the binlogs from the test build to see what's going wrong on the build machine.

**Comment by ericstj** [comment]
So it looks like this difference is due to the following.

In CI builds we don't reference Microsoft.NET.Test.Sdk: 
https://github.com/dotnet/runtime/blob/ef6b6d581fbcdf65516d59c0597288755d46cb57/eng/testing/xunit/xunit.props#L26

The Microsoft.NET.Test.Sdk sets `GenerateBindingRedirectsOutputType` to true.
https://github.com/microsoft/vstest/blob/681849f4dced5de25b330cf9d20fe643de9e6924/src/package/Microsoft.NET.Test.Sdk/netfx/Microsoft.NET.Test.Sdk.targets#L22

Arcade sets the property, but does so after RAR, so it doesn't help (I have no idea why it's done after RAR):
https://github.com/dotnet/arcade/blob/747f53d751983dd062f39f4654bff074536e0012/src/Microsoft.DotNet.Arcade.Sdk/tools/Workarounds.targets#L6

So nothing is telling RAR to find and generate bindingRedirects in our test projects.

So that raises the question -- how are these loads succeeding for our test projects in helix today?  The answer is they aren't, initially:
```
LOG: Assembly download was successful. Attempting setup of file: C:\src\dotnet\runtime\artifacts\bin\Microsoft.Extensions.Hosting.WindowsServices.Tests\Debug\net462\System.Runtime.CompilerServices.Unsafe.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: The assembly reference did not match the assembly definition found.
```

What happens is Xunit has installed an AssemblyResolve handler that probes the [test directory](https://github.com/xunit/xunit/blob/1892224c60f8499b42ee1d8a521d65995ef32aea/src/xunit.runner.utility/Frameworks/v2/Xunit2Discoverer.cs#L95) and ignores assembly version completely:
https://github.com/xunit/xunit/blob/1892224c60f8499b42ee1d8a521d65995ef32aea/src/common/AssemblyResolution/AssemblyHelper_Desktop.cs#L53

So this will break anything in remote-executor scenarios that requires bindingRedirects, since they won't be using that runner to set up the AssemblyResolve handler -- they need the bindingRedirects to be correct.

**Comment by ericstj** [comment]
This should fix the tests 🤞

**Comment by ericstj** [comment]
@buyaa-n can I get your review of this?

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs [hunk 7]
```diff
@@ -18,8 +18,10 @@ namespace Microsoft.Extensions.Hosting.WindowsServices
     public class WindowsServiceLifetime : ServiceBase, IHostLifetime
     {
         private readonly TaskCompletionSource<object?> _delayStart = new TaskCompletionSource<object?>(TaskCreationOptions.RunContinuationsAsynchronously);
+        private readonly TaskCompletionSource<object?> _serviceDispatcherStopped = new TaskCompletionSource<object?>(TaskCreationOptions.RunContinuationsAsynchronously);
         private readonly ManualResetEventSlim _delayStop = new ManualResetEventSlim();
         private readonly HostOptions _hostOptions;
+        private bool _serviceStopped;
```
Comment (buyaa-n) [inline src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:24]: NIT: it looks to me like used for checking if `_stopRequested`

**Review by buyaa-n — APPROVED** [review]
LGTM, thanks for the broad testing!

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 7 above)
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:24]: @buyaa-n was a naming suggestion?

Comment (buyaa-n) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:24]: Yeah, if it makes sense for you

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceLifetimeTests.cs [hunk 8]
```diff
@@ -0,0 +1,338 @@
...
+                            await Assert.ThrowsAsync<Exception>(async () => 
+                                await lifetime.WaitForStartAsync(CancellationToken.None)));
+                }
+            });
+
+            serviceTester.Start();
+
+            serviceTester.WaitForStatus(ServiceControllerStatus.Stopped);
+            var status = serviceTester.QueryServiceStatus();
+            Assert.Equal(1064, status.win32ExitCode);
```
[the remark this answers is not in the document]
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceLifetimeTests.cs:81]: Yeah, I can use the errors from https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--1000-1299-  good suggestion.

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs [hunk 9]
```diff
@@ -116,6 +125,7 @@ protected override void OnStart(string[] args)
         /// <remarks>This might be called multiple times by service Stop, ApplicationStopping, and StopAsync. That's okay because StopApplication uses a CancellationTokenSource and prevents any recursion.</remarks>
```
Comment (ericstj) [inline src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:125]: This comment is now wrong and in fact was a signal that there was an issue here.

I fixed the extra call from `StopAsync`, the call from `ApplicationStopping` existed at [the time of this comment](https://github.com/dotnet/extensions/commit/05d1a6eb0e051a0cbadc64246f77fe9b836d33a6#diff-e4d0d3a9aa655704afc92739fc3402911ce12676b9e316d14f45cbc16f3fca4eR38) but was removed [later](https://github.com/dotnet/extensions/commit/43435a80d007d568aa17d891ea32ca87363716fc#diff-899fddd5f7ff286e68af676af2b391e6e284d41a2c02ed3e1678c997dd843e06L38).  At this point `OnStop` should only ever be called once.

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs (hunk 7 above)
Comment (ericstj) [reply src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:24]: I'll make it `_serviceStopRequested` -- though at this point it's irreversible.  I tried to fix up some of the public docs to reflect this.

File: src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs [hunk 10]
```diff
@@ -87,19 +89,30 @@ private void Run()
...
-            Task.Run(Stop, CancellationToken.None);
-            return Task.CompletedTask;
+            cancellationToken.ThrowIfCancellationRequested();
+
+            if (!_serviceStopRequested)
+            {
+                await Task.Run(Stop, cancellationToken).ConfigureAwait(false);
+            }
+
+            // When the underlying service is stopped this will cause the ServiceBase.Run method to complete and return, which completes _serviceStopRequested.
```
Comment (buyaa-n) [inline src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetime.cs:114]: NIT: Seems it is about `_serviceDispatcherStopped`
```suggestion
            // When the underlying service is stopped this will cause the ServiceBase.Run method to complete and return, which completes _serviceDispatcherStopped.
```

**Comment by ericstj** [comment]
JIT test failure is https://github.com/dotnet/runtime/issues/84398.
