### PR TITLE
Fixes for LLVM AOT on Windows from @lateralusX

### LINKED ISSUE #92031: Precompiling failed error after enabling LLVM on Android release builds
### Description

Unable to run Android release builds after enabling LLVM

Error List

### Steps to Reproduce

1. Create a new MAUI project
2. Enable the option to **Use LLVM optimising compiler** for **Release & net8.0-android**
3. Run release build for Android

### Link to public reproduction project repository

https://github.com/phillipjt/maui-reproductions/tree/llvm-precompiling-failed

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.86

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell
1>[_Microsoft.Android.Resource.Designer.dll] Exec (with response file contents expanded) in C:\Repositories\maui-reproductions\SampleApp\SampleApp: MONO_PATH=C:\Repositories\maui-reproductions\SampleApp\SampleApp\obj\Release\net8.0-android\android-arm\linked; MONO_ENV_OPTIONS= C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm\8.0.0-preview.7.23375.6\Sdk\..\tools\mono-aot-cross.exe --debug --llvm "--aot=asmwriter,temp-path=obj\Release\net8.0-android\android-arm\aot\armeabi-v7a\_Microsoft.Android.Resource.Designer,profile-only,profile=C:\Nuget\microsoft.maui.controls.build.tasks\8.0.0-preview.7.8842\buildTransitive\netstandard2.0\maui.aotprofile,profile=C:\Nuget\microsoft.maui.controls.build.tasks\8.0.0-preview.7.8842\buildTransitive\netstandard2.0\maui-blazor.aotprofile,nodebug,llvm-path=C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm\8.0.0-preview.7.23375.6\Sdk\..\tools,mtriple=armv7-linux-gnueabi,tool-prefix=C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\tools\binutils\bin\arm-linux-androideabi-,outfile=obj\Release\net8.0-android\android-arm\aot\_Microsoft.Android.Resource.Designer.dll.so,llvm-outfile=obj\Release\net8.0-android\android-arm\aot\_Microsoft.Android.Resource.Designer.dll-llvm.o,temp-path=obj\Release\net8.0-android\android-arm\_Microsoft.Android.Resource.Designer.dll.tmp,ld-name=ld,ld-flags=\"C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\tools\libstubs\android-arm\libc.so\";\"C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\tools\libstubs\android-arm\libm.so\" --no-relax -s" "obj\Release\net8.0-android\android-arm\linked\_Microsoft.Android.Resource.Designer.dll"
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : Precompiling failed for C:\Repositories\maui-reproductions\SampleApp\SampleApp\obj\Release\net8.0-android\android-arm\linked\_Microsoft.Android.Resource.Designer.dll with exit code 1.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : The system cannot find the file specified.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : AOT of image C:\Repositories\maui-reproductions\SampleApp\SampleApp\obj\Release\net8.0-android\android-arm\linked\_Microsoft.Android.Resource.Designer.dll failed.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : Mono Ahead of Time compiler - compiling assembly C:\Repositories\maui-reproductions\SampleApp\SampleApp\obj\Release\net8.0-android\android-arm\linked\_Microsoft.Android.Resource.Designer.dll
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : AOTID 40A9BA1C-82AE-5CB2-92C4-E5B57ED51BDA
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : Using profile data file 'C:\Nuget\microsoft.maui.controls.build.tasks\8.0.0-preview.7.8842\buildTransitive\netstandard2.0\maui.aotprofile'
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : Using profile data file 'C:\Nuget\microsoft.maui.controls.build.tasks\8.0.0-preview.7.8842\buildTransitive\netstandard2.0\maui-blazor.aotprofile'
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : Added 0 methods from profile.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : Added 0 methods from profile.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.7.382\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : Executing opt: "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm\8.0.0-preview.7.23375.6\Sdk\..\tools\opt" -f -disable-tail-calls -passes='default<O2>,place-safepoints' -spp-all-backedges -o "obj\Release\net8.0-android\android-arm\_Microsoft.Android.Resource.Designer.dll.tmp\temp.opt.bc" "obj\Release\net8.0-android\android-arm\_Microsoft.Android.Resource.Designer.dll.tmp\temp.bc"
```

### PR DESCRIPTION
**Pull request by directhex**
This avoids calling `opt` and `llc` on Windows, where the .exe extension is needed

Closes: #92031

### CODE REVIEW

File: src/mono/mono/mini/aot-compiler.c [hunk 1]
```diff
@@ -10708,6 +10708,18 @@ execute_system (const char * command)
...
+#define OPT_NAME "opt.exe"
+#else
+#define OPT_NAME "opt"
+#endif
+
+#ifdef TARGET_WIN32
+#define LLC_NAME "llc.exe"
+#else
+#define LLC_NAME "llc"
+#endif
```
Comment (lambdageek) [inline src/mono/mono/mini/aot-compiler.c:10721]: should be `HOST_WIN32`, I think?

AOT compiler targets are like "Android", "Wasm", etc, I think?

**Review by steveisok — APPROVED** [review]

**Comment by steveisok** [comment]
@directhex please backport to RC2

File: src/mono/mono/mini/aot-compiler.c (hunk 1 above)
Comment (lateralusX) [reply src/mono/mono/mini/aot-compiler.c]: That file actually uses TARGET_* for most of the platform tooling, clang, gcc, as, ld etc, so using this change just followed along. I would say that parts of this is host and parts of this is target, since some platforms might use different tooling depending on TARGET, but I agree that just the file extension is part of host.
