### PR TITLE
Fix sporadic AccessViolation in compressed single-file apps on Apple Silicon

### LINKED ISSUE #123324: .NET 10, 9, 8, 7, osx-arm64: AccessViolationException in a single-file compressed app
### Description

On Apple Silicon, my single-file app with compression enabled crashes ~90% of the time with `AccessViolationException`. The app simply spawns two child processes concurrently. The exact stack trace varies, which is typical of memory corruption.

### Reproduction Steps

[repro.zip](https://github.com/user-attachments/files/24695845/repro.zip)

csproj:
```
  <Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net10.0</TargetFramework>
      <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
      <ImplicitUsings>enable</ImplicitUsings>
      <SelfContained>true</SelfContained>
      <PublishSingleFile>true</PublishSingleFile>
      <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    </PropertyGroup>
  </Project>
```

Program.cs:
```cs
  using System.Diagnostics;

  var tasks = Enumerable.Range(0, 2)
      .Select(i => Task.Run(async () =>
      {
          var psi = new ProcessStartInfo
          {
              FileName = "/bin/echo",
              Arguments = "hello!",
          };
          using var process = Process.Start(psi)!;
          await process.WaitForExitAsync();
      }));

  await Task.WhenAll(tasks);
```

```pwsh
  dotnet publish -c Release
  ./bin/Release/net10.0/osx-arm64/publish/Repro
```

```
➜  repro git:(main) ✗ ./bin/Release/net10.0/osx-arm64/publish/Repro
hello!
hello!
➜  repro git:(main) ✗ ./bin/Release/net10.0/osx-arm64/publish/Repro
Fatal error.
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Span`1[[System.Char, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(Void*, Int32)
   at System.Diagnostics.Process.GetNextArgument(System.String, Int32 ByRef)
   at System.Diagnostics.Process.ParseArgumentsIntoList(System.String, System.Collections.Generic.List`1<System.String>)
   at System.Diagnostics.Process.ParseArgv(System.Diagnostics.ProcessStartInfo, System.String, Boolean)
   at System.Diagnostics.Process.StartCore(System.Diagnostics.ProcessStartInfo)
   at System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
   at Program+<>c+<<<Main>$>b__0_1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Program+<>c+<<<Main>$>b__0_1>d, Repro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<<Main>$>b__0_1>d ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Program+<>c+<<<Main>$>b__0_1>d, Repro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<<Main>$>b__0_1>d ByRef)
   at Program+<>c.<<Main>$>b__0_1()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
hello!
[1]    24480 abort      ./bin/Release/net10.0/osx-arm64/publish/Repro
➜  repro git:(main) ✗ ./bin/Release/net10.0/osx-arm64/publish/Repro
Fatal error.
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.ArgumentNullException.ThrowIfNull(System.Object, System.String)
   at System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
   at Program+<>c+<<<Main>$>b__0_1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Program+<>c+<<<Main>$>b__0_1>d, Repro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<<Main>$>b__0_1>d ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Program+<>c+<<<Main>$>b__0_1>d, Repro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<<Main>$>b__0_1>d ByRef)
   at Program+<>c.<<Main>$>b__0_1()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[1]    24498 abort      ./bin/Release/net10.0/osx-arm64/publish/Repro
hello!
```

### Expected behavior

Process completes without error.

### Actual behavior

Crashes with `AccessViolationException: Attempted to read or write protected memory`.

### Regression?

Reproduces on .NET 7, 8, 9, and 10, with varying failure rates. .NET 6 shows "bus error" 100% of the time.

| Framework | Failures | Failure Rate |
  |-----------|----------|--------------|
  | net10.0   | 90       | 90%          |
  | net9.0    | 94       | 94%          |
  | net8.0    | 89       | 89%          |
  | net7.0    | 93       | 93%          |
  | net6.0    | 100      | 100% |

### Known Workarounds

- Set `EnableCompressionInSingleFile=false`.
- Putting a `Task.Delay` at process start reduces but does not eliminate the failure rate.

Image

### Configuration

  - macOS 15.7.1
  - Apple M4 Max (ARM64)
  - SDK 10.0.101 (/usr/local/share/dotnet/sdk)
  - Runtime: Microsoft.NETCore.App 10.0.1

### Other information

Likely related to:
  - #88288
  - #112167

Those issues report ~5-9% failure rates. This minimal repro has a ~90% failure rate, which may help isolate the root cause.

### PR DESCRIPTION
**Pull request by elinor-fung**
> [!NOTE]
> This pull request was generated with AI assistance (GitHub Copilot CLI).

Fixes #123324.

cc @dotnet/appmodel @AaronRobinsonMSFT 

## Problem

On macOS Apple Silicon (observed on macOS 15), compressed self-contained single-file apps intermittently hit `AccessViolationException` crashes.  With the repro provided in the issue, the failure rate was roughly 75% in a local run.

`FlatImageLayout::LoadImageByCopyingParts` allocates the image region with `MEM_RESERVE_EXECUTABLE` (which maps to `MAP_JIT` on macOS) as `PAGE_READWRITE`, copies in all section bytes, then promotes executable sections to `PAGE_EXECUTE_READWRITE` via a second `mprotect`. On Apple Silicon, this `RW → RWX` transition on MAP_JIT memory has been observed to intermittently succeed at the API level but leave pages non-executable at the kernel level, producing the sporadic AVs.

## Fix

On Apple Silicon (`HOST_OSX && HOST_ARM64`), avoid the unreliable transition: reserve the whole image region as `PAGE_NOACCESS` up front, then commit each section directly with its final runtime protection (`PAGE_EXECUTE_READWRITE` for exec, `PAGE_READWRITE` otherwise), copying executable content under `PAL_JitWriteProtect`. The `PROT_NONE → RWX` direction via a fresh commit is reliable; the problematic `RW → RWX` transition no longer occurs. Read-only sections are still downgraded from `PAGE_READWRITE` to `PAGE_READONLY` after the copy, which is a W-removing transition and is not implicated in the original bug.

The non-Apple-Silicon code path is unchanged.

## Testing

New test: `AppHost.Bundle.Tests.AppLaunch.SelfContained_Compressed_SpawnsChildren` (OSX-only). Adds a `launch_self` option to the `HelloWorld` test asset that spawns 5 copies of itself in parallel, and asserts the parent runs to completion.

Local validation on Apple Silicon:

- Without fix: parent crash with `AccessViolationException` in ~74% of trials at N=5 children (rises to ~98% at N≥12).
- With fix: 0 failures across 50+ trials at N=5.

### CODE REVIEW

File: src/coreclr/vm/peimagelayout.cpp [hunk 1]
```diff
@@ -877,34 +877,90 @@ void* FlatImageLayout::LoadImageByCopyingParts(SIZE_T* m_imageParts) const
...
         ThrowLastError();
 
     // when loading by copying we have only one part to free.
     m_imageParts[0] = AllocatedPart(base);
 
+    IMAGE_SECTION_HEADER* sectionStart = IMAGE_FIRST_SECTION(FindNTHeaders());
+    IMAGE_SECTION_HEADER* sectionEnd = sectionStart + VAL16(FindNTHeaders()->FileHeader.NumberOfSections);
+
+#if defined(HOST_OSX) && defined(HOST_ARM64)
+    DWORD sizeOfHeaders = VAL32(FindNTHeaders()->OptionalHeader.SizeOfHeaders);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/peimagelayout.cpp:917]: I think we should assert a few things on this `ifdef`. I'd suggest making sure that the `allocationType` doesn't have `MEM_COMMIT` set and that `initialProtection` isn't `PAGE_READWRITE`.

File: src/coreclr/vm/peimagelayout.cpp [hunk 2]
```diff
@@ -877,34 +877,90 @@ void* FlatImageLayout::LoadImageByCopyingParts(SIZE_T* m_imageParts) const
...
+    // Commit and copy headers, then apply read-only protection.
+    if (ClrVirtualAlloc(base, sizeOfHeaders, MEM_COMMIT, PAGE_READWRITE) == NULL)
+        ThrowLastError();
+
+    CopyMemory(base, (void*)GetBase(), sizeOfHeaders);
+
+    DWORD oldProtection;
+    if (!ClrVirtualProtect((void*)base, sizeOfHeaders, PAGE_READONLY, &oldProtection))
+        ThrowLastError();
+
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/peimagelayout.cpp:928]: Should we assert that `oldProtection` is `PAGE_READWRITE`?

I'm asking about all this because it seems we're making a lot of assumptions about the steps we're performing here and I'd like to assert where we can.

File: src/coreclr/vm/peimagelayout.cpp [hunk 3]
```diff
@@ -877,34 +877,90 @@ void* FlatImageLayout::LoadImageByCopyingParts(SIZE_T* m_imageParts) const
...
+    // Commit and copy each section with its desired protection.
+    IMAGE_SECTION_HEADER* section = sectionStart;
+    while (section < sectionEnd)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/peimagelayout.cpp]:
```suggestion    
    for (IMAGE_SECTION_HEADER* section = sectionStart; section < sectionEnd; section++)
```

File: src/coreclr/vm/peimagelayout.cpp [hunk 4]
```diff
@@ -877,34 +877,90 @@ void* FlatImageLayout::LoadImageByCopyingParts(SIZE_T* m_imageParts) const
...
+            PAL_JitWriteProtect(false);
+        }
+        else if ((section->Characteristics & IMAGE_SCN_MEM_WRITE) == 0)
+        {
+            DWORD oldProt;
+            if (!ClrVirtualProtect(sectionBase, virtualSize, PAGE_READONLY, &oldProt))
+                ThrowLastError();
+        }
+
+        section++;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/peimagelayout.cpp]:
```suggestion
```

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/vm/peimagelayout.cpp [hunk 5]
```diff
@@ -877,34 +877,91 @@ void* FlatImageLayout::LoadImageByCopyingParts(SIZE_T* m_imageParts) const
...
+    // Commit and copy headers, then apply read-only protection.
+    if (ClrVirtualAlloc(base, sizeOfHeaders, MEM_COMMIT, PAGE_READWRITE) == NULL)
+        ThrowLastError();
+
+    CopyMemory(base, (void*)GetBase(), sizeOfHeaders);
+
+    DWORD oldProtection;
+    if (!ClrVirtualProtect((void*)base, sizeOfHeaders, PAGE_READONLY, &oldProtection))
+        ThrowLastError();
+    _ASSERTE(oldProtection == PAGE_READWRITE);
```
Comment (elinor-fung) [inline src/coreclr/vm/peimagelayout.cpp]:
```suggestion
    DWORD oldProtection; // PAL layer doesn't properly set the previous protection, so we don't try to validate it here.
    if (!ClrVirtualProtect((void*)base, sizeOfHeaders, PAGE_READONLY, &oldProtection))
        ThrowLastError();
```

**Review by AaronRobinsonMSFT — APPROVED** [review]
