### PR TITLE
Fix size used for vectorization check in BitArray (#111558)

### LINKED ISSUE #111558: Wrong size used for bounds check in BitArray
`Vector512` should be `Vector128`: https://github.com/dotnet/runtime/blob/a73f1637cbd74e3048bd420e876113f94f650996/src/libraries/System.Collections/src/System/Collections/BitArray.cs#L888

Found by @saucecontrol

### PR DESCRIPTION
**Pull request by AnsBalin**
This PR resolves #111558 by correcting the vector size used in the vectorization check within BitArray.

### CODE REVIEW

File: src/libraries/System.Collections/src/System/Collections/BitArray.cs [hunk 1]
```diff
@@ -885,7 +885,7 @@ public unsafe void CopyTo(Array array, int index)
                         }
                     }
                 }
-                else if (Ssse3.IsSupported && ((uint)m_length >= Vector512<byte>.Count * 2u))
+                else if (Ssse3.IsSupported && ((uint)m_length >= Vector128<byte>.Count * 2u))
```
Comment (EgorBo) [inline src/libraries/System.Collections/src/System/Collections/BitArray.cs:888]: I think while you're on it, we can also replace various Sse2.And with just plain operators, e.g.
```cs
Vector128<byte> extractedLower = Sse2.And(shuffledLower, bitMask128);
```
to
```cs
Vector128<byte> extractedLower = shuffledLower & bitMask128;
```
but that's optional

**Review by stephentoub — APPROVED** [review]
Thanks

**Comment by jkotas** [comment]
Run a quick perf test that shows this is a perf improvement for all affected sizes?

**Comment by MihaZupan** [comment]
FWIW this would only affect pre-AVX2 X86 CPUs
```c#
else if (Avx2.IsSupported && (uint)m_length >= Vector256<byte>.Count)
...
else if (Ssse3.IsSupported && ((uint)m_length >= Vector128<byte>.Count * 2u))
```

**Comment by eiriktsarpalis** [comment]
Let's merge and retrigger to see what happens.

**Comment by AnsBalin** [comment]
> Let's merge and retrigger to see what happens.

@eiriktsarpalis I still do not think the remaining failures are related as they seem to be timeouts. Are they expected to pass? Let me know what else I can do! Thanks

**Comment by jkotas** [comment]
@EgorBot -intel --envvars DOTNET_EnableAVX=0
```
using System.Collections;
using BenchmarkDotNet.Attributes;

public class Benchmarks
{
    bool[] buffer = new bool[1000];

    [Benchmark]
    [ArgumentsSource(nameof(TestData))]
    public void BitArrayCopyTo(BitArray bitArray) => bitArray.CopyTo(buffer, 0);

    public IEnumerable<BitArray> TestData()
    {
        yield return new BitArray(31);
        yield return new BitArray(32);
        yield return new BitArray(33);
        yield return new BitArray(64);
        yield return new BitArray(127);
        yield return new BitArray(128);
        yield return new BitArray(129);
        yield return new BitArray(256);
    }
}
```

**Comment by EgorBo** [comment]
@jkotas `--envvars` expects `VAR:VALUE` format (https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/guides/console-args.md#more) 🙂

**Comment by EgorBo** [comment]
@EgorBot -intel --envvars DOTNET_EnableAVX:0
```
using System.Collections;
using BenchmarkDotNet.Attributes;

public class Benchmarks
{
    bool[] buffer = new bool[1000];

    [Benchmark]
    [ArgumentsSource(nameof(TestData))]
    public void BitArrayCopyTo(BitArray bitArray) => bitArray.CopyTo(buffer, 0);

    public IEnumerable<BitArray> TestData()
    {
        yield return new BitArray(31);
        yield return new BitArray(32);
        yield return new BitArray(33);
        yield return new BitArray(64);
        yield return new BitArray(127);
        yield return new BitArray(128);
        yield return new BitArray(129);
        yield return new BitArray(256);
    }
}
```

**Comment by jkotas** [comment]
> Run a quick perf test that shows this is a perf improvement for all affected sizes?

This change makes improves the perf 3x-7x for the affected sizes (on machines without AVX): https://github.com/EgorBot/runtime-utils/issues/296#issuecomment-2661203135

**Comment by jkotas** [comment]
> I still do not think the remaining failures are related

Right, the failures are unrelated.
