### PR TITLE
System.Configuration.ConfigurationManager.Tests: use Assembly.Location to determine ThisApplicationPath.

### LINKED ISSUE #108476: exePath_UserLevelNone failing when testing against source-build config
In our internal CI, the exePath_UserLevelNone test is failing on the main branch.

The stacktrace looks as follows:
```
System.Configuration.ConfigurationErrorsException: System.Configuration.ConfigurationErrorsException : An error occurred loading a configuration file: The parameter 'exePath' is invalid. (Parameter 'exePath')\n---- System.ArgumentException : The parameter 'exePath' is invalid. (Parameter 'exePath')
        at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ConfigurationSchemaErrors.cs:line 71
at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs:line 3640
at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors() in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs:line 258
at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/Configuration.cs:line 75
at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigurationHost.cs:line 485
at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ConfigurationManager.cs:line 214
at System.Configuration.ConfigurationManager.OpenExeConfiguration(String exePath) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ConfigurationManager.cs:line 186
at MonoTests.System.Configuration.ConfigurationManagerTest.exePath_UserLevelNone() in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/tests/Mono/ConfigurationManagerTest.cs:line 139
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
----- Inner Stack Trace -----
at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:line 49
at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:line 208
at System.Configuration.ClientConfigurationHost.get_ConfigPaths() in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigurationHost.cs:line 40
at System.Configuration.ClientConfigurationHost.GetStreamName(String configPath) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigurationHost.cs:line 244
at System.Configuration.Internal.DelegatingConfigHost.GetStreamName(String configPath) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/Internal/DelegatingConfigHost.cs:line 70
at System.Configuration.Internal.DelegatingConfigHost.GetStreamName(String configPath) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/Internal/DelegatingConfigHost.cs:line 70
at System.Configuration.ImplicitMachineConfigHost.GetStreamName(String configPath) in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs:line 48
at System.Configuration.BaseConfigurationRecord.InitConfigFromFile() in /home/tester/runtime/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/BaseConfigurationRecord.cs:line 551

```

From looking through some CI logs: 5fd3f22b98cb0d126e4f6328f5a0bf922a532f69 is good, and ef0c712f1ffcc48da481e44fb2981bf4de191eac is bad.

The test failure happens on the main branch. The test is passing on the 9.0 branch.

cc @ViktorHofer @omajid

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/runtime/issues/108476.

@ViktorHofer @steveharter ptal.

### CODE REVIEW

File: src/libraries/System.Configuration.ConfigurationManager/tests/Mono/TestUtil.cs [hunk 1]
```diff
@@ -58,8 +58,10 @@ public static string ThisApplicationPath
         {
             get
             {
-                return Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
-                    Assembly.GetEntryAssembly().ManifestModule.Name);
+                Assembly assembly = Assembly.GetEntryAssembly();
+                string directory = Path.GetDirectoryName(assembly.Location);
```
Comment (jkotas) [inline src/libraries/System.Configuration.ConfigurationManager/tests/Mono/TestUtil.cs:62]: BaseDirectory is typically the directory of the entry assembly. Where is the difference in your test environment come from? Are you running the tests in some kind of atypical setup that makes BaseDirectory different from entry assembly?

Comment (jkotas) [reply src/libraries/System.Configuration.ConfigurationManager/tests/Mono/TestUtil.cs:62]: This was done originally to make the test compatible with single file form factors. The description of the old PR that you have linked says that it is fixing the tests for uap-aot (aka .NET Native) that was the first single file form factor.

The problem with single file is that Assembly.Location returns empty string.

I think it would be best to delete the `ThisApplicationPath` property and the one test that uses it.  There are other more comprehensive tests [OpenExeConfiguration2](https://github.com/dotnet/runtime/blob/497236a2359f9de4b70b1dbd00e55449823e6f63/src/libraries/System.Configuration.ConfigurationManager/tests/Mono/ConfigurationManagerTest.cs#L79) and [OpenExeConfiguration2_ExePath_DoesNotExist](https://github.com/dotnet/runtime/blob/497236a2359f9de4b70b1dbd00e55449823e6f63/src/libraries/System.Configuration.ConfigurationManager/tests/Mono/ConfigurationManagerTest.cs#L107C21-L107C63) to exercise this scenario. These other tests create the files in known locations and so they do not depend on the deployment details that may change over time.

Comment (tmds) [reply src/libraries/System.Configuration.ConfigurationManager/tests/Mono/TestUtil.cs]: Thanks for your insights! I've removed the test.

**Review by jkotas — APPROVED** [review]
