### PR TITLE
Disable R2R code for all associated components of a composite image

### LINKED ISSUE #61471: ReadyToRun images crash if compiled for AVX2 but run on non-AVX2 CPU
_**Update:**_ Crash also happens if R2R image is built for SSE4.2 and run on CPU that only supports SSSE3 (I added a reply below)

### Description

I'm using `crossgen2` and .NET 6.0.0 GA with the following options to build a composite R2R image for my app (Paint.NET),

` --targetos:windows --targetarch:x64 --optimize-time --composite --inputbubble --compilebubblegenerics --instruction-set:avx2,bmi,bmi2,lzcnt,popcnt,fma`

From what I'm told, this image should still run fine on systems without support for these instruction sets, but the precompiled code will be ignored in favor of JITting. (or at least, any precompiled code which uses those instructions will be discarded -- still haven't heard conclusively if it's selective exclusion or if the whole native image is ignored)

However, I received a report from a private tester that the app just crashes. Their CPU is a Pentium(R) Dual-Core CPU T4400 which supports up through SSSE3.

If I use `bcdedit /set xsavedisable 1` on my own system, which is a Ryzen 5000 series CPU, I'm also able to reproduce the crash.

So it looks like ReadyToRun is doing something wrong here.

cc @tannergooding @EgorBo @AndyAyersMS 

### Reproduction Steps

Compile an app using crossgen2 and ` --targetos:windows --targetarch:x64 --optimize-time --composite --inputbubble --compilebubblegenerics --instruction-set:avx2,bmi,bmi2,lzcnt,popcnt,fma`

Run the app on an older CPU that lacks AVX2, or run `bcdedit /set xsavedisable 1` and reboot and run it on a CPU that is more recent.

### Expected behavior

Everything works fine

### Actual behavior

Crashes. Event Viewer has an entry for the app showing that it crashed.

### Regression?

Not sure if this is a regression.

### Known Workarounds

Compile with `--instruction-set:sse2` instead.

### Configuration

.NET 6.0.0
Windows 10/11
x64
CPU that lacks AVX2, or on one that does have AVX2 but first run `bcdedit /set xsavedisable 1` and reboot

### Other information

_No response_

### PR DESCRIPTION
**Pull request by davidwrighton**
- When loading a composite image, capture the detail that the composite image code cannot be used into the NativeImage structure, and flow that data into all associated ReadyToRunInfo structures.

Fixes #61471

### CODE REVIEW

**Comment by davidwrighton** [comment]
@tannergooding fyi

File: src/coreclr/vm/ceeload.cpp [hunk 1]
```diff
@@ -4615,16 +4615,16 @@ void Module::RunEagerFixups()
...
         // from multiple threads so we need to lock their resolution.
-        if (compositeNativeImage->EagerFixupsHaveRun())
-        {
-            return;
-        }
         CrstHolder compositeEagerFixups(compositeNativeImage->EagerFixupsLock());
         if (compositeNativeImage->EagerFixupsHaveRun())
         {
+            if (compositeNativeImage->ReadyToRunCodeDisabled())
+                GetReadyToRunInfo()->DisableAllR2RCode();
```
Comment (tannergooding) [inline src/coreclr/vm/ceeload.cpp:4622]: So this is basically just propagating up the information from `compositeNativeImage`, is that right? The issue being that we weren't before and so `compositeNativeImage` might have flagged itself as not being R2R compatible but the corresponding module loaded in the VM wouldn't track that?

**Review by tannergooding — APPROVED** [review]
LGTM.

File: src/coreclr/vm/ceeload.cpp (hunk 1 above)
Comment (davidwrighton) [reply src/coreclr/vm/ceeload.cpp:4622]: The issue was that the first module in the composite image would trigger the code to be disabled, but the second module and subsequent modules would just use the code in the composite image.

**Comment by rickbrew** [comment]
Will this be backported to 6.0.x servicing?

**Comment by davidwrighton** [comment]
@rickbrew, yes this will fix the issue for `--instruction-set:sse42`. I'll put in a request for this to be considered in servicing. It may not be approved, as I'm not certain that we've declared that use of the `--instruction-set` switch is supported. (There are a number of crossgen2 switches that are not reliable and are used for engineering purposes on our team, and we only documented those which we were extremely confident were well tested.)

File: src/coreclr/vm/readytoruninfo.h [hunk 2]
```diff
@@ -66,7 +66,7 @@ class ReadyToRunInfo
     PTR_CORCOMPILE_IMPORT_SECTION   m_pImportSections;
     DWORD                           m_nImportSections;
 
-    bool                            m_readyToRunCodeDisabled;
+    bool                            m_readyToRunCodeDisabled; // Is
```
Comment (trylek) [inline src/coreclr/vm/readytoruninfo.h:69]: Nit - looks like an unfinished comment. If the purpose of the one-word comment is just to indicate that the flag states whether ready to run code is disabled, would it be perhaps better to directly rename the identifier to something like <code>m_isReadyToRunCodeDisabled</code>?

**Review by trylek — COMMENTED** [review]
LGTM, thanks David for fixing this so quickly!
