### PR TITLE
fix infinite recursion in crossgen2 on ARM

### LINKED ISSUE #32120: Infinite recursion while computing instance layout in crossgen2
Crossgen2 falls into infinite recursion for some types on ARM.
Trace of recursion follows:
```
1. DefType::ComputeInstanceLayout
2. MetadataFieldLayoutAlgorithm::ComputeInstanceLayout
3. ReadyToRunMetadataFieldLayoutAlgorithm::ComputeInstanceFieldLayout
4. MetadataFieldLayoutAlgorithm::ComputeAutoFieldLayout
5. ReadyToRunMetadataFieldLayoutAlgorithm::AlignBaseOffsetIfNecessary
6. TypeExtensions::RequiresAlign8
7. DefType::InstanceByteAlignment
8. and (1) again and so on
```
`DefType::InstanceByteAlignment` expects that instance layout may be computed already, but in this case it obviously is not.
`TypeExtensions::RequiresAlign8` exits with `false` if target architecture is not ARM, so that case is not replicable on other machines.

Can you help us find a way to properly fix it?

@jkotas @alpencolt

### PR DESCRIPTION
**Pull request by y-yamshchikov**
This PR fixes https://github.com/dotnet/runtime/issues/32120.

Despite it is not used in `ReadyToRunMetadataFieldLayoutAlgorithm::AlignBaseOffsetIfNecessary` I think we should pass proper default alignment, but I don't sure it is `4`: now field's alignment requirements are tracking by `MetadataFieldLayoutAlgorithm::ComputeAutoFieldLayout`.

Also if we try to call `TypeExtensions::RequiredAlign8(this TypeDesc)` just from `MetadataFieldLayoutAlgorithm`'s method we face missing dependency, so I decided to have `virtual` method to `override` in `ReadyToRunMetadataFieldLayoutAlgorithm`.

### CODE REVIEW

**Comment by y-yamshchikov** [comment]
@jkotas @alpencolt

**Comment by jkotas** [comment]
cc @dotnet/crossgen-contrib

**Comment by MichalStrehovsky** [comment]
I would prefer we do what @jkotas originally suggested in the issue: "Keep track of maximum alignment in `// Iterate over all fields and do the following` loop in ComputeAutoFieldLayout". To do that see how we do `largestAlignmentRequirement` elsewhere in the file - it's just about calling `ComputeFieldSizeAndAlignment` and sending that value through `LayoutInt.Max`. Once we have the largest one, we can call `type.Context.Target.GetObjectAlignment(alignment)` to get the object alignment. If that value is more than 4, it's an align8 type.

I would also change the `int` parameter to `AlignBaseOffsetIfNecessary` to be a bool so that we don't have to compare with integer constants.

Computing the `align8` bit will be useful later anyway. It doesn't look like `ComputeAutoFieldLayout` marks classes correctly as requiring 8-byte alignment right now (see the code around the `// The JITs like to copy full machine words,` comment - there is the same comment in the CoreCLR VM, but the logic is slightly different for `FEATURE_64BIT_ALIGNMENT`.

**Comment by y-yamshchikov** [comment]
@MichalStrehovsky 
Could you please take a look?

File: src/coreclr/src/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 1]
```diff
@@ -452,13 +450,19 @@ protected ComputedInstanceFieldLayout ComputeAutoFieldLayout(MetadataType type,
...
+            LayoutInt largestAlignmentRequired = LayoutInt.One;
 
             foreach (var field in type.GetFields())
             {
                 if (field.IsStatic)
                     continue;
 
                 TypeDesc fieldType = field.FieldType;
+
+                var fieldSizeAndAlignment = ComputeFieldSizeAndAlignment(fieldType, packingSize);
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs]: Could you please do this in the `// Iterate over all fields and do the following` foreach loop?

That loop already calls ComputeFieldSizeAndAlignment in one of the branches and we can save us a call.

File: src/coreclr/src/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 2]
```diff
@@ -471,11 +475,19 @@ protected ComputedInstanceFieldLayout ComputeAutoFieldLayout(MetadataType type,
...
                     Debug.Assert(fieldType.IsPrimitive || fieldType.IsPointer || fieldType.IsFunctionPointer || fieldType.IsEnum);
 
-                    var fieldSizeAndAlignment = ComputeFieldSizeAndAlignment(fieldType, packingSize);
                     instanceNonGCPointerFieldsCount[CalculateLog2(fieldSizeAndAlignment.Size.AsInt)]++;
                 }
             }
 
+            largestAlignmentRequired = type.Context.Target.GetObjectAlignment(largestAlignmentRequired);
+
+            if (largestAlignmentRequired.IsIndeterminate)
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs]: This check is not necessary. Calling AsInt is going to throw if the value is indeterminate. This might actually be reachable at some point. Once it is we will deal with it.

File: src/coreclr/src/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs (hunk 1 above)
Comment (y-yamshchikov) [reply src/coreclr/src/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs]: oh, I didn't notice that the comment addresses specified place in code and picked the first loop of in the body

File: src/coreclr/src/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 3]
```diff
@@ -517,11 +517,15 @@ protected ComputedInstanceFieldLayout ComputeAutoFieldLayout(MetadataType type,
                 else
                 {
                     var fieldSizeAndAlignment = ComputeFieldSizeAndAlignment(fieldType, packingSize);
+                    largestAlignmentRequired = LayoutInt.Max(fieldSizeAndAlignment.Alignment, largestAlignmentRequired);
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs]: This needs to go above the cascading `if` block, together with the line above it.

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

**Comment by y-yamshchikov** [comment]
Thank you for your help!
