### PR TITLE
Issue 36212: Remove space in parameter name

### LINKED ISSUE #36212: ParamName in an ArgumentException has a space
That seems a bit strange:

image

---

https://github.com/dotnet/runtime/blob/8527a991b91cabc9bec6f6abe57a52b5bb5e154d/src/coreclr/src/vm/comutilnative.cpp#L920

### PR DESCRIPTION
**Pull request by weitzhandler**
Fixes #36212

### CODE REVIEW

**Comment by weitzhandler** [comment]
But the question is really if we need to allow `WeakReference(null)` in the first place.

File: src/coreclr/src/vm/comutilnative.cpp [hunk 1]
```diff
@@ -917,7 +917,7 @@ FCIMPL1(int, GCInterface::GetGenerationWR, LPVOID handle)
     OBJECTREF temp;
     temp = ObjectFromHandle((OBJECTHANDLE) handle);
     if (temp == NULL)
-        COMPlusThrowArgumentNull(W("weak handle"));
+        COMPlusThrowArgumentNull(W("handle"));
```
Comment (stephentoub) [inline src/coreclr/src/vm/comutilnative.cpp:920]:
```suggestion
        COMPlusThrowArgumentNull(W("wo"));
```

**Comment by stephentoub** [comment]
> But the question is really if we need to allow WeakReference(null) in the first place.

The docs say it throws an exception if "Garbage collection has already been performed on wo." Are you suggesting that should be changed?

**Review by stephentoub — APPROVED** [review]
