### PR TITLE
Fix break in DirectoryServices SearchResultCollection

### LINKED ISSUE #113265: SearchResultCollection does not work with the IEnumerable extension methods in .Net 9.
### Description

We have some code that returns a `SearchResultCollection`. After the collection is returned, we execute the following line of code:

```C#
var results = searchResults.Cast<SearchResult>().ToList();
```

In .Net 8 this line works as expected. The `results` list contains the correct number of search results.

In .Net 9 this line produces an empty list.

NOTE that the following workaround does work as expected:

```C#
List<SearchResult> results = [];
foreach (var result in searchResults)
{
    results.Add((SearchResult)result);
}
```

### Reproduction Steps

```C#
using (SearchResultCollection searchResults = GetSearchResults())
{
    var results = searchResults.Cast<SearchResult>().ToList();
    Console.WriteLine($"results contains {results.Count} items.");
}
```

### Expected behavior

A list is created with all of the results.

### Actual behavior

An empty list is created.

### Regression?

It works in .Net 8.

### Known Workarounds

Manually enumerate through the results to build the list instead of using platform extension methods.

### Configuration

Windows X64 .Net 9 Console application.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by IDisposable**
Added enumeration handling when the internal ArrayList has already been loaded but an enumeration follows. This fixes the issue with 9.x Linq statements against the collection caused by the access of the .Count

Fixes #113265

I am not entirely sure the best way to test this, as we never had tests for this class until now so I created a new DirectorySearcherTests.cs (conditionally run when LDAP is available) using the setup shown in the bug report.

### CODE REVIEW

**Comment by IDisposable** [comment]
I think the code is the simplest way to fix this issue without making tons more changes. I'm not sure my test class is useful/valid because I'm not on a LDAP domain-joined machine so it simply bypasses for me in local runs.

:pointup: @BillArmstrong @stephentoub @tarekgh

File: src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs [hunk 1]
```diff
@@ -214,6 +214,49 @@ void ICollection.CopyTo(Array array, int index)
             InnerList.CopyTo(array, index);
         }
 
+        /// <devdoc>
+        /// Supports a simple type-specific wrapper for the underlying cached list
+        /// </devdoc>
+        private sealed class AlreadyReadResultsEnumerator : IEnumerator
```
Comment (tarekgh) [inline src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:220]: >class [](http://example.com/codeflow?start=23&length=5)

can this be a struct?

**Review by tarekgh — APPROVED** [review]
LGTM, thanks @IDisposable 

@stephentoub @steveharter could you please have a quick look? Note, this is a candidate for 9.0 service porting .

File: src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs (hunk 1 above)
Comment (IDisposable) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:220]: Good point, I will adjust after the Blues game.

Comment (IDisposable) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:220]: Switched to `struct`

**Comment by IDisposable** [comment]
Push PR review updates and improved the unit tests. Can anyone do the `/azp` magic to trigger the tests for `IsLdapConfigurationExist` since I can't run those local, nor does the normal build run them?

File: src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs [hunk 2]
```diff
@@ -214,6 +214,49 @@ void ICollection.CopyTo(Array array, int index)
             InnerList.CopyTo(array, index);
         }
 
+        /// <devdoc>
```
[the remark this answers is not in the document]
Comment (IDisposable) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:217]: I just took the existing enumerator's framework and dropped it back to standard enumeration. I can add `inheritdocs` if desired.

File: src/libraries/System.DirectoryServices/tests/System.DirectoryServices.Tests.csproj [hunk 3]
```diff
@@ -9,6 +9,7 @@
     <Compile Include="System\DirectoryServices\ActiveDirectory\DomainControllerTests.cs" />
     <Compile Include="System\DirectoryServices\DirectoryEntryTests.cs" />
     <Compile Include="System\DirectoryServices\DirectoryServicesPermissionTests.cs" />
+    <Compile Include="System\DirectoryServices\DirectorySearcherTests.cs" />
```
[the remark this answers is not in the document]
Comment (IDisposable) [reply src/libraries/System.DirectoryServices/tests/System.DirectoryServices.Tests.csproj:12]: Oh, sorry... I just added it, will resort.

File: src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs [hunk 4]
```diff
@@ -214,6 +214,49 @@ void ICollection.CopyTo(Array array, int index)
...
+        /// Supports a simple type-specific wrapper for the underlying cached list
+        /// </devdoc>
+        private struct AlreadyReadResultsEnumerator : IEnumerator
```
[the remark this answers is not in the document]
Comment (IDisposable) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:220]: We certainly could, except this enumerator matches the existing lazy one in that the `Current` method is declared to return a `SearchResult` (e.g. correct type information). If I just used `ArrayList.GetEnumerator`, then `Current` would be returning `object`, which is inconsistent between the two (lazy/eager) enumerators.

Please let me know if you want that change made.

File: src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectorySearcherTests.cs [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+    public partial class DirectorySearcherTests
+    {
+        internal static bool IsLdapConfigurationExist => LdapConfiguration.Configuration != null;
+        internal static bool IsActiveDirectoryServer => IsLdapConfigurationExist && LdapConfiguration.Configuration.IsActiveDirectoryServer;
+
+        private const int ADS_SYSTEMFLAG_CR_NTDS_NC = 0x1;
+        private const int ADS_SYSTEMFLAG_CR_NTDS_DOMAIN = 0x2;
+
+        [ConditionalFact(nameof(IsLdapConfigurationExist))]
+        public void DirectorySearch_IteratesCorrectly_SimpleEnumeration()
```
[the remark this answers is not in the document]
Comment (IDisposable) [reply src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectorySearcherTests.cs:22]: There was never any tests against this class as far as I could find, so no :)

The two tests come from from @stephentoub's minimal reproduction [in this comment](https://github.com/dotnet/runtime/issues/113265#issuecomment-2714683962)

File: src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectorySearcherTests.cs [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+                seen = true;
+            }
+
+            Assert.True(seen);
+        }
+
+        private static SearchResultCollection GetDomains()
+        {
+            using var entry = new DirectoryEntry("LDAP://rootDSE");
+            var namingContext = entry.Properties["configurationNamingContext"][0]!.ToString();
```
[the remark this answers is not in the document]
Comment (IDisposable) [reply src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectorySearcherTests.cs:57]: This was from the original bug report, would it be better to mimic that code or write it "better"?

File: src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs [hunk 7]
```diff
@@ -47,15 +47,17 @@ private ArrayList InnerList
...
                         this,
                         _rootEntry.GetUsername(),
                         _rootEntry.GetPassword(),
                         _rootEntry.AuthenticationType);
 
                     while (enumerator.MoveNext())
-                        _innerList.Add(enumerator.Current);
+                        eagerList.Add(enumerator.Current);
+
+                    _innerList = eagerList;
```
Comment (IDisposable) [inline src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:60]: The change to build the inner list in it's entirety _and then_ set the member is to ensure that if an exception in thrown while populating this inner list we do NOT memoize the incomplete list because then we would (if enumerated again) not throw again and would instead silently only yield the entries we previously gathered. Of course anyone attempting _re_enumeration of a list that yielded an error the first time is probably wrong, but why add to the problem?

File: src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectorySearcherTests.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (steveharter) [reply src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectorySearcherTests.cs:57]: We should follow the coding guidelines, especially for obvious cases for readability\understandability, although for some things like using underscores in test names we don't necessarily follow.

[the remark this answers is not in the document]
Comment (IDisposable) [reply src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectorySearcherTests.cs]: Done

**Comment by steveharter** [comment]
PTAL @BRDPM @grubioe @jay98014

**Review by steveharter — APPROVED** [review]

**Comment by steveharter** [comment]
FYI link to coding guidelines: https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md which do discuss the use of "var".

File: src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectorySearcherTests.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (IDisposable) [reply src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectorySearcherTests.cs:22]: Sorry, that might have been unclear... the first test would have always succeeded (and I put this test in to ensure I didn't break anything). The second test would have failed without the changes in this PR.

File: src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs [hunk 8]
```diff
@@ -214,6 +214,51 @@ void ICollection.CopyTo(Array array, int index)
             InnerList.CopyTo(array, index);
         }
 
+        /// <summary>Provides an enumerator implementation for the array of <see cref="SearchResult"/>.</summary>
+        private struct AlreadyReadResultsEnumerator : IEnumerator
```
Comment (stephentoub) [inline src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:218]: Why struct?

Comment (tarekgh) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:218]: This was my suggestion; I thought it may save some allocations in some scenarios?

Comment (stephentoub) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:218]: It looks like the only place it's used is here:
https://github.com/dotnet/runtime/pull/113775/files#diff-c9880e3568259df335f4e47504988814365bc6213087cd341b8939595f1fd988R194
in which case it's always immediately cast to an IEnumerator, boxing it.

Comment (tarekgh) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:218]: We can change it back to class if it makes a difference.

Comment (IDisposable) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:218]: Happy to swap it back, I did look for some other uses when it was suggested.

Comment (tarekgh) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:218]: go ahead and change it back.

Comment (IDisposable) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/SearchResultCollection.cs:218]: PR #113927 submitted.
