### PR TITLE
[browser] fix JSExport in lazy loaded assembly

### LINKED ISSUE #117780: [browser] JSExport in lazy loaded assembly
1. Add JSExport to a class library
2. Mark that library with `<BlazorWebAssemblyLazyLoad Include="ClassLibrary" />`
3. Load the assembly and get exports

```js
await INTERNAL.loadLazyAssembly("ClassLibrary");
await getAssemblyExports("ClassLibrary");
```

Throws `RuntimeError: memory access out of bounds`

### PR DESCRIPTION
**Pull request by pavelsavara**
- remove DLL suffix for GetAssemblyExport
- don't stackRestore on aborted runtime
- add lazy WBT

Fixes https://github.com/dotnet/runtime/issues/117780

### CODE REVIEW

**Comment by pavelsavara** [comment]
expected BTW output
```
[debug] MONO_WASM: Binding [JSExport] .SatelliteAssembliesTest:Run from WasmBasicTestApp assembly
[debug] MONO_WASM: Attempting to download 'http://127.0.0.1:56058/_framework/Json.8lyzvxjbal.wasm' for Json.8lyzvxjbal.wasm
[debug] MONO_WASM: Attempting to download 'http://127.0.0.1:56058/_framework/Json.02sl3e3dwj.pdb' for Json.02sl3e3dwj.pdb
[log] TestOutput -> {"FirstName":"John","LastName":"Doe"}
[debug] MONO_WASM: Attempting to download 'http://127.0.0.1:56058/_framework/LazyLibrary.atba1goc0h.wasm' for LazyLibrary.atba1goc0h.wasm
[debug] MONO_WASM: Attempting to download 'http://127.0.0.1:56058/_framework/LazyLibrary.0oyotd78vm.pdb' for LazyLibrary.0oyotd78vm.pdb
[debug] MONO_WASM: Binding [JSExport] LazyLibrary.Foo:Bar from LazyLibrary assembly
[log] Hello from Foo.Bar!
Exited with 0
[info] WASM EXIT 0
```

**Comment by pavelsavara** [comment]
`\Microsoft.NET.Sdk.WebAssembly.Browser.targets(803,5): error BLAZORSDK1001: Unable to find 'Json.dll;LazyLibrary.dll' to be lazy`

@maraf hints ?

**Comment by maraf** [comment]
My first guess would be that the assembly was trimmed away. Binlog would help to validate it

EDIT: But a) that should not happen if there is JSExport b) it shouldn't scream with both assemblies

File: src/mono/browser/runtime/managed-exports.ts [hunk 1]
```diff
@@ -90,7 +91,8 @@ export function load_satellite_assembly (dll: Uint8Array): void {
         marshal_array_to_cs(arg1, dll, MarshalerType.Byte);
         invoke_sync_jsexport(managedExports.LoadSatelliteAssembly, args);
     } finally {
-        Module.stackRestore(sp);
+        if (loaderHelpers.is_runtime_running()) Module.stackRestore(sp);
+
```
Comment (maraf) [inline src/mono/browser/runtime/managed-exports.ts:95]: not: These new lines are not needed

**Review by maraf — APPROVED** [review]
