### PR TITLE
[mono][interp] Add missing GC wbarriers for static field stores with hotreload enabled

### LINKED ISSUE #100065: mono gc not set static field back after object moved when enable interp mode
### Description

We are embeding mono in UnrealEngine, when we upgrade .ne8.0(v8.0.2), we found sgen-gc will not set static field back after object move when enable hotreloadcomponent.

### Reproduction Steps

We have not separate code to reproduct it, but I will describe it as detailed as possible.

we have restore object in static field, when next pass it to internal call the object address after the gc have move it, the value not set back.
I show the code first:
```c#
public partial class FTicker : ScriptingWrapperOfType
{
	public static FTicker Internal_GetCoreTicker_Cache = null;
	[MethodImpl(MethodImplOptions.InternalCall)]
	private static extern FTicker Internal_GetCoreTicker();

	public static FTicker GetCoreTicker() 
	{
		if(Internal_GetCoreTicker_Cache == null)
		{
			Internal_GetCoreTicker_Cache = Internal_GetCoreTicker();
		}

		return Internal_GetCoreTicker_Cache;
	}

	[MethodImpl(MethodImplOptions.InternalCall)]
	public static extern void TearDownCoreTicker();

	[MethodImpl(MethodImplOptions.InternalCall)]
	public extern FDelegateHandle AddTicker(TDelegate__float_Ret_bool InDelegate, float InDelay = 0.0f);
}
```
the internal call 

```c++
static FDelegateHandle_Proxy Internal_FTicker_AddTicker(MonoObject* self, MonoDelegate* InDelegate, float InDelay)
{
        // these code is use for debug this problem
	MonoImage* EngineImage = GetScriptingAssemblyManager().FindImage("UnrealEngine");
	if (EngineImage)
	{
		MonoClass* TickerClass = mono_class_from_name(EngineImage, "UnrealEngine", "FTicker");
		if (TickerClass)
		{
			MonoClassField* Internal_GetCoreTicker_Cache = mono_class_get_field_from_name(TickerClass, "Internal_GetCoreTicker_Cache");
			if (Internal_GetCoreTicker_Cache)
			{
				MonoObject* data = nullptr;
				MONO_ENTER_GC_UNSAFE
				mono_field_static_get_value(mono_class_vtable(mono_domain_get(), TickerClass), Internal_GetCoreTicker_Cache, &data);
				MONO_EXIT_GC_UNSAFE
			}
		}
	}
        // below is the real logic
	TRACE_INTERALCALL_PROFILER_EVENT_SCOPE
	TDelegate<bool(float)> InDelegate__Temp;
	BindScriptIfException<bool, float>(InDelegate__Temp, InDelegate, true);
	return FDelegateHandle_Proxy::Proxy(ReadonlyScriptingObjectConverter<FTicker>(self)->AddTicker(InDelegate__Temp, InDelay));
}
```

the code logic execute as below :
```c#
tickHandle = FTicker.GetCoreTicker().AddTicker(OnTick);
// gc occured
tickHandle1 = FTicker.GetCoreTicker().AddTicker(OnTick1);

// but the second call `Internal_FTicker_AddTicker` the `self` object the vtable have set null and then can't get the object class. 
```

I show the behaviors with hotreload component enable or not.

**if we not enable hotreload component, just use jit execute mode, it work correctly:**

the first call `AddTicker`, we can checkout the `self` object:

image

and we check the `Internal_GetCoreTicker_Cache ` static field:

image

the second call the `self` object address have changed:

image

**if we enable hotreload component, the static field will not write back:**
the first call:

image

the second call: the self object address have not been changed but the `vtable` is null
 
image

### Expected behavior

work correctly

### Actual behavior

crash

### Regression?

.net7.0 work correctly

### Known Workarounds

no

### Configuration

windows 
build v8.0.2 tag
set excute mode `mono_jit_set_aot_mode(MONO_AOT_MODE_INTERP_ONLY);`

### Other information

_No response_

### PR DESCRIPTION
**Pull request by BrzVlad**
By default, static fields are stored in malloced memory that is registered and always scanned as roots. With hotreload, new static data is allocated inside newly created objects, so storing into it will require write barriers. In order to avoid slowing the normal execution, for fields from metadata updates, we will store into them via ldflda + stobj instead.

Fixes https://github.com/dotnet/runtime/issues/100065

### CODE REVIEW

File: src/mono/mono/mini/interp/transform.c [hunk 1]
```diff
@@ -4606,6 +4606,14 @@ interp_emit_sfld_access (TransformData *td, MonoClassField *field, MonoClass *fi
 			}
 			interp_ins_set_dreg (td->last_ins, td->sp [-1].var);
 		} else {
+			// if (G_UNLIKELY (m_field_is_from_update (field)))
```
Comment (lambdageek) [inline src/mono/mono/mini/interp/transform.c:4609]: This should be uncommented? Or are you just checking if doing it for all fields is good enough?

Comment (BrzVlad) [reply src/mono/mono/mini/interp/transform.c]: I just wanted to ensure that this emit pattern is thoroughly tested since I'm not sure what kind of hot reload tests we have, if any.

**Comment by BrzVlad** [comment]
@srxqds If you could double check that this also fixed the issue, it would be great.

**Comment by srxqds** [comment]
> @srxqds If you could double check that this also fixed the issue, it would be great.

yeah, thank, lgtm

**Comment by srxqds** [comment]
but hope you can fix `MINT_STSFLD_O` and ``MINT_STSFLD_VT` opcode, when alc enable collctiable. Although it is not turned on now, it is still a precautionary measure.

**Comment by BrzVlad** [comment]
@lambdageek How would this check look in order to handle also static data from collectible assemblies ?

**Comment by srxqds** [comment]
when enable collectiable alc, the static variable will be reference in LoaderAlloc, the ref link will be : ALC -> LoaderAlloc -> Object[] -> static variable.

**Review by lambdageek — APPROVED** [review]

**Review by lambdageek — APPROVED** [review]
