### PR TITLE
Delete runtime built-in handling for SIGTERM

### LINKED ISSUE #83093: CoreCLR's CNTRL_SHUTDOWN_EVENT handler prevents graceful exit of services during system shutdown
### Description

I am not sure if this belongs here, but this is a new weird behaviour I have been fighting with lately.

I have a service, where the 'Main_Worker' is a 'IHostedService' and a 'BackgroundService'. I have overriden the 'StopAsync' function and the only thing it really does is write to the Windows Event Log a message and save a txt file with some data.

While I was working with this structure in .NET 6, it all worked preatty well. Then I upgraded to .Net 7, and it seems that now 'StopAsync' is not triggering when I turn of the PC by a normal Power -> Shutdown or if I use 'Process.Start("cmd", @"/c shutdown -s -t 0");'

When in .NET 6, both ways it worked without problems. 

### Reproduction Steps

`    public async override Task<Task> StopAsync(CancellationToken cancellationToken) {
         Log.Text("Stopping Worker_Main service...");
         logger.LogWarning("Test Service is Stopping...");
         await Log.SaveCurrentLog();
         return base.StopAsync(cancellationToken);
     }
`

That is my StopAsync function, it used to work like this with no problems. But now, even if you take away the await line, not even the logger is appearing.

### Expected behavior

At least I would expect to see the logged message in the Windows Event Logger when the PC is turned on again.

### Actual behavior

No trace of the message being logged or the file being written. The service probably closes, yet I have no idea if it is in a forced mode or if it is actually being closed in a gracefull way.

### Regression?

_No response_

### Known Workarounds

I do not have workarounds at the moment.

### Configuration

Have tested in Windows 10 & 11
Both are x64

### Other information

_No response_

### LINKED ISSUE #115206: IHostedService.StopAsync not invoked with `8.0-windowsservercore-ltsc2019` image
### Describe the bug

We are using A .NET 8.0 hosted service application on a windows container based on `mcr.microsoft.com/dotnet/runtime:8.0-windowsservercore-ltsc2019` as base.  

We are getting a weird behavior where the `HostedService.StopAsync` is not invoked on container shut down.

The same application is working fine when 
`mcr.microsoft.com/dotnet/runtime:8.0-nanoserver-1809' is used.

### Which .NET image(s) are you using?

`mcr.microsoft.com/dotnet/runtime:8.0-windowsservercore-ltsc2019`, `mcr.microsoft.com/dotnet/runtime:8.0-nanoserver-1809'

### Steps to reproduce

Minimal Repro project in  https://github.com/SaurabhSunil/Shutdown

##Steps to Reproduce
Build the shutdown project in Debug mode. This is required as docker file uses ./bin/Debug/net8.0 to copy from.
Build the docker image. For this navigate to the Shutdown project location docker build . -t shutdown-trial
Run a container using the image shutdown-trial
Stop the container after starting

### Other information

When does this issue occur? 
When using `mcr.microsoft.com/dotnet/runtime:8.0-windowsservercore-ltsc2019`

Does it occur consistently?  
Yes

Do you know of any workarounds?
No

### Output of `docker version`

```console
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:17:17 2024
 OS/Arch:           windows/amd64
 Context:           desktop-windows

Server: Docker Desktop 4.34.2 (167172)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:16:14 2024
  OS/Arch:          windows/amd64
  Experimental:     false
```

### Output of `docker info`

```console
Client:
 Version:    27.2.0
 Context:    desktop-windows
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 11
 Server Version: 27.2.0
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19045 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Microsoft Windows Version 22H2 (OS Build 19045.5737)
 OSType: windows
 Architecture: x86_64
 CPUs: 24
 Total Memory: 63.69GiB
 Name: XXXXXXXX
 ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### PR DESCRIPTION
**Pull request by jkotas**
The runtime built-in handling for SIGTERM signals is not correct for all appmodels. It is better to leave it to each model appmodel to handle it in appmodel specific way if necessary. The popular console appmodel based on HostingHostBuilderExtensions.UseConsoleLifetime does that already.

Fixes #83093

### CODE REVIEW

File: src/coreclr/vm/ceemain.cpp [hunk 1]
```diff
@@ -372,13 +372,6 @@ static BOOL WINAPI DbgCtrlCHandler(DWORD dwCtrlType)
     else
 #endif // DEBUGGING_SUPPORTED
     {
-        if (dwCtrlType == CTRL_CLOSE_EVENT || dwCtrlType == CTRL_SHUTDOWN_EVENT)
-        {
-            // Initiate shutdown so the ProcessExit handlers run
-            ForceEEShutdown(SCA_ReturnWhenShutdownComplete);
-        }
-
-        g_fInControlC = true;     // only for weakening assertions in checked build.
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:381]: There is no reason to weaken assertions after Ctrl+C has been pressed. The runtime should still function fine until all signal handlers finish.

**Comment by jkotas** [comment]
cc @am11 @tmds @omajid

**Comment by am11** [comment]
I think we should `/azp run runtime-coreclr outerloop` on this one which covers some relevant cases in PALTests etc.

**Review by am11 — APPROVED** [review]
LGTM 👍

**Review by jkoritzinsky — APPROVED** [review]

**Comment by tmds** [comment]
Indeed runtime doesn't need to do much on SIGTERM except inform the managed side. This is a nice cleanup!

To be sure: does `AppDomain.CurrentDomain.ProcessExit` still fire on `SIGTERM`?

**Comment by jkotas** [comment]
> To be sure: does AppDomain.CurrentDomain.ProcessExit still fire on SIGTERM?

It won't unless the app subscribes to the signal and does graceful exit in the signal handler. Typical ASP.NET app does that via ConsoleLifetime today: https://github.com/dotnet/runtime/blob/c53ccee795268bb2e816f42e4c9e973c50fbd9c3/src/libraries/Microsoft.Extensions.Hosting/src/Internal/ConsoleLifetime.netcoreapp.cs#L20-L23 .

The default handling of SIGTERM will be identical to handling of SIGQUIT or SIGINT with this change. No handler registered by default. E.g. Python is on the same plan according to https://stackoverflow.com/questions/9930576/python-what-is-the-default-handling-of-sigterm

**Comment by jkotas** [comment]
On Windows, this reverts the behavior to what it used to be in .NET Framework.
On Unix, this reverts the behavior to what it used to be in classic Mono.

**Comment by tmds** [comment]
I'm asking because before `PosixSignalRegistration` was introduced, `AppDomain.CurrentDomain.ProcessExit` was the (only) API for setting up a `SIGTERM` handler.

It's probably worth calling out explicitly in the breaking change doc.

**Review by tmds — APPROVED** [review]

**Review by BrzVlad — APPROVED** [review]

File: src/libraries/System.Runtime/tests/System.Runtime.Tests/System/ExitCodeTests.Unix.cs [hunk 2]
```diff
@@ -58,8 +58,8 @@ public void SigTermExitCode(int? exitCodeOnSigterm)
                 bool exited = process.WaitForExit(RemoteExecutor.FailWaitTimeoutMilliseconds);
                 Assert.True(exited);
 
-                // Check exit code
-                Assert.Equal(exitCodeOnSigterm ?? 128 + SIGTERM, process.ExitCode);
+                // Check that the exit code is 143 (128 + SIGTERM).
+                Assert.Equal(143, process.ExitCode);
```
Comment (tmds) [inline src/libraries/System.Runtime/tests/System.Runtime.Tests/System/ExitCodeTests.Unix.cs:62]: This test is was written to check `AppDomain.CurrentDomain.ProcessExit` is called on `SIGTERM`. The `exitCodeOnSigterm` variable no longer makes sense.

File: src/libraries/System.Runtime/tests/System.Runtime.Tests/System/ExitCodeTests.Unix.cs [hunk 3]
```diff
@@ -15,23 +15,16 @@ public class ExitCodeTests
...
-        [InlineData(null)]
-        [InlineData(0)]
-        [InlineData(42)]
+        [ConditionalFact(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported))]
         [PlatformSpecific(TestPlatforms.AnyUnix)] // SIGTERM signal.
-        public void SigTermExitCode(int? exitCodeOnSigterm)
+        public void SigTermExitCode()
         {
-            Action<string> action = (string sigTermExitCode) =>
+            Action<string> action = () =>
```
Comment (jkotas) [inline src/libraries/System.Runtime/tests/System.Runtime.Tests/System/ExitCodeTests.Unix.cs:22]:
```suggestion
            Action action = () =>
```

**Comment by jkotas** [comment]
Breaking change issue created: https://github.com/dotnet/docs/issues/46226

**Comment by rhuijben** [comment]
Do I read this correctly? I hope not.

So ^C will now just exit the application on linux without running exception handers/finally and everything? (kill %app is like kill -9 %app, unless the app introduces .Net 10 specific code)
That is quite a breaking change for every console app that assumes that they can cleanup after themselves.... Like compilers, etc. How can a .Net 8 application prepare for that?

I understand that applications should register what they want, but this default is -if I read this correctly- extremely breaking for all old applications.

On Windows an application has to opt-in on the ^C handler so there it is less troublesome.

**Comment by ericstj** [comment]
Removing `needs-breaking-change-doc-created` label as this PR already has a documentation issue: https://github.com/dotnet/docs/issues/46226
