### PR TITLE
Call the jit shutdown logic on crossgen2 shutdown

### LINKED ISSUE #49525: crossgen2 doesn't call DllMain on the JIT
This is specific to PAL, Linux implementations.

The JIT uses the DllMain() `DLL_PROCESS_DETACH` event to call `jitShutdown()`, which is output various information under various debugging modes, and close stdout if being unloaded.

More importantly, SuperPMI uses `DLL_PROCESS_ATTACH` to initialize the PAL (on Unix), initialize the logger, and `DLL_PROCESS_DETACH` to shutdown the logger. Because the PAL isn't initialized, SuperPMI crashes (issue: https://github.com/dotnet/runtime/issues/47960)

@dotnet/crossgen-contrib @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by davidwrighton**
- Allows the jit shutdown logic to execute reliably on both Windows and Unix

Fixes #49525

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/crossgen-contrib

**Review by BruceForstall — APPROVED** [review]
LGTM. Thanks!

**Review by trylek — APPROVED** [review]
Nice, thank you!

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 1]
```diff
@@ -74,8 +74,38 @@ private struct PgoInstrumentationResults
...
+                if (s_jit != IntPtr.Zero)
+                {
+                    return s_jit;
+                }
+
+                lock(typeof(JitPointerAccessor))
+                {
+                    s_jit = getJit();
+                    return s_jit;
+                }
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:93]: What thread safety guarantees is the `lock` giving us here? I would expect a double-checked locking pattern at least.
