### PR TITLE
Ignoring failures due to the test machine insufficient memory

### LINKED ISSUE #69113: GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.cmd failed in rolling with "Large Memory Machine required"
Job: https://dev.azure.com/dnceng/public/_build/results?buildId=1760633&view=results
Test: https://dev.azure.com/dnceng/public/_build/results?buildId=1760633&view=ms.vss-test-web.build-test-results-tab&runId=47405440&resultId=101792&paneView=debug
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-3e33c16d75004b5c98/PayloadGroup0/1/console.c2d85ac2.log?helixlogtype=result

The log shows:
```scala
  Starting:    GC.LargeMemory.XUnitWrapper (parallel test collections = on, max threads = 4)
    GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\A70D08E8\w\B10209D6\uploads\Reports\GC.LargeMemory\API\gc\gettotalmemory\gettotalmemory.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\A70D08E8\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  gettotalmemory.dll 2048 
      Large Memory Machine required
      Test failed
      Expected: 100
      Actual: 0
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\A70D08E8\p
      > C:\h\w\A70D08E8\w\B10209D6\e\GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at GC_LargeMemory._API_gc_gettotalmemory_gettotalmemory_._API_gc_gettotalmemory_gettotalmemory_cmd()
      Output:
        
        Return code:      1
        Raw output file:      C:\h\w\A70D08E8\w\B10209D6\uploads\Reports\GC.LargeMemory\API\gc\gettotalmemory\gettotalmemory.output.txt
        Raw output:
        BEGIN EXECUTION
         "C:\h\w\A70D08E8\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  gettotalmemory.dll 2048 
        Large Memory Machine required
        Test failed
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=C:\h\w\A70D08E8\p
        > C:\h\w\A70D08E8\w\B10209D6\e\GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.cmd
```

Note that we are running these in parallel and IIUC, they allocate a large chunk of memory. @dotnet/gc, is it ok to change these LargeMemory tests to succeed instead of fail on `OutOfMemoryException`? Or otherwise maybe we can force them to run sequentially instead?

### PR DESCRIPTION
**Pull request by cshung**
Fixes #69113

This will at least unblock the CI

### CODE REVIEW

File: src/tests/GC/LargeMemory/API/gc/collect.cs [hunk 1]
```diff
@@ -25,7 +25,7 @@ public sealed class CollectTest {
             CreateLargeObject();
         } catch (OutOfMemoryException) {
             Console.WriteLine("Large Memory Machine required");
-            return false;
+            return true;
```
Comment (mangod9) [inline src/tests/GC/LargeMemory/API/gc/collect.cs:28]: would it be possible to check that the machine indeed has small memory (which couldnt accommodate the allocation requirement? I worry that in case we have a bug that incorrectly throws OOM this might just mask that issue?

Comment (cshung) [reply src/tests/GC/LargeMemory/API/gc/collect.cs:28]: As @jakobbotsch pointed out, the issue is not the machine, it is because multiple tests are running concurrently and they could be allocating large memory at the same time. Allocating a large object right at that point in time is the easiest way to check if we could get that much memory at that point in time.

**Review by mangod9 — APPROVED** [review]
