### PR TITLE
Use emitLastGroup that works for single/multi align instructions

### LINKED ISSUE #116836: Assertion failed 'markedLastLoop && markedCurrLoop' during 'Generate code'
Started seeing these lately in superpmi-replay pipelines

e.g.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=1072803&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=2694d93b-a574-5310-1876-2e252085b877
https://dev.azure.com/dnceng-public/public/_build/results?buildId=1072803&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=2694d93b-a574-5310-1876-2e252085b877

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by kunalspathak**
In https://github.com/dotnet/runtime/issues/114569, I was relying on `emitAlignLast` to update the pred head, if we end up creating an extra IG. However, for arm64, since we emit 4 align instructions and just keep the first of those align instructions with updates, it is not accurate to rely on `emitAlignLast` because it points to the last of the 4 align instructions. Instead use `emitAlignLastGroup` which is more accurate and designed for such purposes.

Fixes: https://github.com/dotnet/runtime/issues/116836

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @AndyAyersMS PTAL

File: src/coreclr/jit/emit.cpp [hunk 1]
```diff
@@ -2856,16 +2856,17 @@ void* emitter::emitAddLabel(VARSET_VALARG_TP GCvars, regMaskTP gcrefRegs, regMas
...
+            (emitAlignLastGroup->idaLoopHeadPredIG->igNext == emitCurIG))
         {
             // If the emitCurIG was thought to be a loop-head, but if it didn't turn out that way and we end up
             // creating a new IG from which the loop starts, make sure to update the LoopHeadPred of last align
             // instruction emitted. This will guarantee that the information stays up-to-date. Later if we
             // notice a loop that encloses another loop, this information helps in removing the align field from
             // such loops.
             // We need to only update emitAlignLast because we do not align intermingled or overlapping loops.
-            emitAlignLast->idaLoopHeadPredIG = emitCurIG;
+            emitAlignLastGroup->idaLoopHeadPredIG = emitCurIG;
```
Comment (AndyAyersMS) [inline src/coreclr/jit/emit.cpp:2869]: You should update the last line in the comment just above.

Does `emitAlignLast` need to be reset too?

**Comment by amanasifkhalid** [comment]
Looks like CI is being uncooperative, though superpmi-diffs is clean. @kunalspathak do you know why we started seeing this failure all of a sudden?

**Comment by kunalspathak** [comment]
> @kunalspathak do you know why we started seeing this failure all of a sudden?

This is another case of stressing of block layout where the backedges are spread, enclosing other loops that are alignment candidate.

**Comment by kunalspathak** [comment]
> /azp run runtime-coreclr superpmi-replay

yeah, we cannot trigger this anymore. I even tried to do it manually but didn't see a way to do it.

**Comment by kunalspathak** [comment]
@amanasifkhalid - anything else needed for this PR?

**Review by amanasifkhalid — APPROVED** [review]
No, LGTM

File: src/coreclr/jit/emit.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/emit.cpp:2869]: Thought I had submitted this yesterday, sorry for not getting to you sooner.

Comment (kunalspathak) [reply src/coreclr/jit/emit.cpp:2869]: > You should update the last line in the comment just above.

sent out https://github.com/dotnet/runtime/pull/116869

> Does `emitAlignLast` need to be reset too?

Not needed, `emitAlignLast` and `emitAlignLastGroup` should point to the same object (for xarch). It is only different for arm, and we were incorrectly referring to the last align instruction instead of the first one of the 4-align instructions we insert. 

https://github.com/dotnet/runtime/blob/296780df4ebeb237455f7e465cbf1df181da277d/src/coreclr/jit/emit.cpp#L5738-L5741
