### PR TITLE
[mono] Fix the race condition issue of aot_module loading

### LINKED ISSUE #103782: AndroidStripILAfterAOT causing "InvalidProgramException: Invalid IL code in Xunit.Assert:True(bool)"
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS 2022 17.8.5

### Description

When setting `AndroidStripILAfterAOT=true` in a test app, some tests are failing the first time we run them, but then they'll pass if we run them again. 
The error is 100% reproducible when starting the app again.
Here is the error: `InvalidProgramException: Invalid IL code in Xunit.Assert:True(bool): method body is empty`.
No issue in Debug. No issue when removing `AndroidStripILAfterAOT=true`.
This is similar to dotnet/android#8562, but no BroadcastReceiver is involved here.

### Steps to Reproduce

1. Open [repro](https://git.histb.com/tranb3r/Issues/tree/main/MauiAppXunitInvalidILCode) in visual studio.
2. Run app in Release on android emulator.
3. Run all tests: one of the test fails.
4. Run all tests again: both tests succeed.

### Did you find any workaround?

Remove `AndroidStripILAfterAOT=true`.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by fanyang-mono**
Fixes #103782

### CODE REVIEW

File: src/mono/mono/mini/aot-runtime.c [hunk 1]
```diff
@@ -4920,14 +4920,35 @@ mono_aot_get_method (MonoMethod *method, MonoError *error)
...
 	error_init (error);
 
-	if (!amodule)
+	if (!(image->aot_module)) {
+		// aot_module was uninitialized
+		MonoMethodHeader *header = mono_method_get_header_checked (method, error);
+		if (!header) {
+			return NULL;
+		} else if (header->code_size != 0) {
+			return NULL;
```
Comment (lambdageek) [inline src/mono/mono/mini/aot-runtime.c:4936]: this needs to be something like `header->code_size != 0  && !(fullaot && !interpreter)`.
If we're in full AOT without an interpreter we have no choice but to wait for the AOT module to get loaded - there's no other fallback

File: src/mono/mono/mini/aot-runtime.c [hunk 2]
```diff
@@ -4920,14 +4920,35 @@ mono_aot_get_method (MonoMethod *method, MonoError *error)
...
+		} else {
+			// IL code for the method body doesn't exist. Try waiting for aot_module to be loaded probably by another thread
+			int count = 0;
+			while (!(image->aot_module) && (count < 10)) {
+				g_usleep (100);
+				count++;
```
Comment (lambdageek) [inline src/mono/mono/mini/aot-runtime.c:4942]: This isn't 100% correct (if the current thread is holding the loader lock, while another thread is trying to load some assemblies while loading hte AOT module, the other thread won't make progress).  But it should handle 80% of the cases (where we just had a simple race, rather than a potential deadlock).

File: src/mono/mono/mini/aot-runtime.c (hunk 1 above)
Comment (lambdageek) [reply src/mono/mono/mini/aot-runtime.c:4936]: > It would go through the next branch after this.

oh, because with fullaot we always strip the IL so `code_size` will be 0?

> We wait until aot_module is not NULL any more.

Let's not do that.  That will deadlock.  Actually, can you add a comment next to the loop to remind us not to do that in the future.

**Review by lambdageek — COMMENTED** [review]
Need to also set the module to `AOT_MODULE_NOT_FOUND` here:

https://github.com/dotnet/runtime/blob/c5e8f83db1606a89e70a9f4a0ac2fc03dea2418c/src/mono/mono/mini/aot-runtime.c#L2086-L2096

File: src/mono/mono/mini/aot-runtime.c (hunk 1 above)
Comment (fanyang-mono) [reply src/mono/mono/mini/aot-runtime.c:4937]: iOS app always has IL stripped out. I would expect `code_size` to be 0.

Will add a comment.

**Review by lambdageek — APPROVED** [review]

**Review by steveisok — APPROVED** [review]
The android and ios/tvos failures are known. LGTM!

**Comment by gabriel-kozma** [comment]
Is this issue going to be merged back on .net 8.0? I'm having an issue when IL stripping assemblies on Android

**Comment by fanyang-mono** [comment]
@gabriel-kozma Yes, I've opened an PR to backport this fix to .NET8.
