### PR TITLE
[mono][simd] Add MONO_TYPE_I and MONO_TYPE_U types for OP_NEGATION on amd64

### LINKED ISSUE #87606: [mono][simd] Mono functional tests failing due to invalid OP_NEGATION instruction type
## Description

The Mono functional tests are failing during AOT compilation on iossimulator/tvossimulator. It appears that there is an issue with decoding the `ins->inst_c1` type in `OP_NEGATION`.

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=307044
Build error leg or test failing: Build / iossimulator-x64 Release AllSubsets_Mono / Build product
Pull request: https://github.com/dotnet/runtime/pull/87260

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Assertion: should not be reached at /Users/runner/work/1/s/src/mono/mono/mini/mini-amd64.c:6802",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=307044
**Result validation: :white_check_mark:** Known issue matched with the provided build.

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[308234](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308234)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/308234/logs/101)|dotnet/runtime#87260|
|[308235](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308235)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/308235/logs/67)|dotnet/runtime#87260|
|[308148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=308148)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/308148/logs/1029)||
|[307044](https://dev.azure.com/dnceng-public/public/_build/results?buildId=307044)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/307044/logs/77)|dotnet/runtime#87260|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|4|4|

### PR DESCRIPTION
**Pull request by kotlarmilos**
The Mono functional tests are failing during AOT compilation on iossimulator/tvossimulator. It appears that there is an issue with decoding the ins->inst_c1 type in OP_NEGATION. Assumption is that the MONO_TYPE_I and MONO_TYPE_U types for OP_NEGATION on amd64 are missing.

Fixes https://github.com/dotnet/runtime/issues/87606

This PR should verify whether the change resolves the issue causing the CI failures.

/cc: @vargaz @jandupej

### CODE REVIEW

File: src/mono/mono/mini/mini-amd64.c [hunk 1]
```diff
@@ -6798,6 +6798,18 @@ mono_arch_output_basic_block (MonoCompile *cfg, MonoBasicBlock *bb)
 				amd64_sse_xorps_reg_reg (code, ins->dreg, SIMD_TEMP_REG);
 				break;
 			}
+			case MONO_TYPE_I:
+			case MONO_TYPE_U:
+#if TARGET_SIZEOF_VOID_P == 8
```
Comment (BrzVlad) [inline src/mono/mono/mini/mini-amd64.c:6803]: is this always true ?

Comment (vargaz) [reply src/mono/mono/mini/mini-amd64.c:6803]: These should be added to the MONO_TYPE_I8 block above.

**Comment by vargaz** [comment]
Why isn't this problem hit by the normal desktop test suites ?

**Review by vargaz — APPROVED** [review]

**Review by jandupej — APPROVED** [review]
LGTM.
