### PR TITLE
Don't set security descriptor if the mutex is not owned/new

### LINKED ISSUE #110454: System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters Failed
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=887390
Build error leg or test failing: System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters
Pull request: https://github.com/dotnet/runtime/pull/110378

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### LINKED ISSUE #116014: System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_IncrementBy_IncrementByReadOnly failed with "Attempted to perform an unauthorized operation"
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1051241
Build error leg or test failing: System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_IncrementBy_IncrementByReadOnly
Pull request: https://github.com/dotnet/runtime/pull/115993

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.UnauthorizedAccessException : Attempted to perform an unauthorized operation", "System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_IncrementBy_IncrementByReadOnly [FAIL]"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### PR DESCRIPTION
**Pull request by jozkee**
Fixes https://github.com/dotnet/runtime/issues/116014.
Fixes https://github.com/dotnet/runtime/issues/110454.

### CODE REVIEW

File: src/libraries/Common/src/System/Diagnostics/NetFrameworkUtils.cs [hunk 1]
```diff
@@ -22,14 +22,17 @@ internal static void EnterMutex(string name, ref Mutex mutex)
...
+            Mutex tmpMutex = new Mutex(false, mutexName, out bool createdNew);
+
+            if (createdNew)
+            {
+                // Specify a SID in case the mutex has not yet been created; this prevents it from using the SID from the current thread.
+                // This SID (AuthenticatedUserSid) is the same one used by .NET Framework.
+                MutexSecurity sec = new MutexSecurity();
+                SecurityIdentifier authenticatedUserSid = new SecurityIdentifier(WellKnownSidType.AuthenticatedUserSid, null);
+                sec.AddAccessRule(new MutexAccessRule(authenticatedUserSid, MutexRights.Synchronize | MutexRights.Modify, AccessControlType.Allow));
+                tmpMutex.SetAccessControl(sec);
```
Comment (jozkee) [inline src/libraries/Common/src/System/Diagnostics/NetFrameworkUtils.cs:34]: See https://github.com/dotnet/runtime/issues/120085 for context on why MutexAcl.Create wouldn't work.

Comment (ericstj) [reply src/libraries/Common/src/System/Diagnostics/NetFrameworkUtils.cs:34]: I see, do we introduce any sort of race condition here?  Can some other thread/process do something to interrupt between the creation of the mutex and our changing of the ACL such that it prevents our changing the ACL?

IIRC we added all the creation static methods to address race conditions like that.

Comment (ericstj) [reply src/libraries/Common/src/System/Diagnostics/NetFrameworkUtils.cs:34]: Per offline discussion - the race condition was here already and solving #120085 is too risky for .NET 10.0.  This change is minimal to resolve the regression in .NET 10.0.

**Review by ericstj — APPROVED** [review]
As discussed - you've done manual testing involving multiple users to ensure this is fixed.  I imagine we cannot cover this easily in CI.

File: src/libraries/Common/src/System/Diagnostics/NetFrameworkUtils.cs (hunk 1 above)
Comment (jozkee) [reply src/libraries/Common/src/System/Diagnostics/NetFrameworkUtils.cs:34]: To be clear, I think the race condition was introduced by https://github.com/dotnet/runtime/pull/110416 but we think it won't surface in normal cases because CreateMutexEx will not return createdNew incorrectly.  
Is only possible if someone else creates/opens the named mutex and sets an ACL without looking at createdNew.
