### PR TITLE
Move GenTreeIntCon::gtCompileTimeHandle field to be a global map

### LINKED ISSUE #114823: Test crashes in arm32 `runtime-coreclr libraries-jitstress-random` pipeline
pipeline: runtime-coreclr libraries-jitstress-random
job: `net10.0-linux-Release-arm-jitstress_random_1-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7`
Tests:
```
Microsoft.Bcl.Cryptography.Tests Work Item
System.Net.Security.Tests Work Item
System.Net.Security.Unit.Tests Work Item
System.Net.Security.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=1020494&view=ms.vss-test-web.build-test-results-tab

e.g.,
```
DOTNET_EnableCrashReport=1
DOTNET_TieredCompilation=0
DOTNET_JitStress=d6
DOTNET_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
DOTNET_DbgEnableMiniDump=1
...
========================= Begin custom configuration settings ==============================
export __IsXUnitLogCheckerSupported=1
export XUNIT_HIDE_PASSING_OUTPUT_DIAGNOSTICS=1
========================== End custom configuration settings ===============================
----- start Fri Apr 18 05:43:28 PM UTC 2025 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Net.Security.Tests.runtimeconfig.json --depsfile System.Net.Security.Tests.deps.json xunit.console.dll System.Net.Security.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Security.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Security.Tests (found 319 of 511 test cases)
  Starting:    System.Net.Security.Tests (parallel test collections = on [2 threads], stop on fail = off)
[createdump] Gathering state for process 65 dotnet
[createdump] Crashing thread 0054 signal 11 (000b)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.65.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.65.dmp
[createdump] Written 280678400 bytes (68525 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 265ms
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
./RunTests.sh: line 178:    65 Segmentation fault      (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Net.Security.Tests.runtimeconfig.json --depsfile System.Net.Security.Tests.deps.json xunit.console.dll System.Net.Security.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/root/helix/work/workitem/e
----- end Fri Apr 18 05:43:52 PM UTC 2025 ----- exit code 139 ----------------------------------------------------------
```

Kicked off another run to see if it repros:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=1020635&view=results

### PR DESCRIPTION
**Pull request by EgorBo**
This PR removes `GenTreeIntCon::gtCompileTimeHandle` field in favor of a global hashmap (we already had it in VN).

- This allows to remove a TODO where we used to give on 0 compile time handles in VN
- Fixes a bug @kunalspathak found

Fixes: https://github.com/dotnet/runtime/issues/114823

### CODE REVIEW

**Comment by jakobbotsch** [comment]
> we already had it in VN

Having internal maps in phases that keep them maintained is not as problematic as having global ambient state throughout the JIT that must be maintained by all phases and becomes part of the IR invariants.

Though, given that this is a map from the value itself and not from `GenTree*`, it probably does not come with the same downsides, so perhaps it's not too bad.

**Comment by SingleAccretion** [comment]
An alternative to this would be to introduce a JIT-EE API for `embedded handle -> compile time handle`.

**Comment by EgorBo** [comment]
Ok I ended up reverting my attempts to either use a global hash or JIT-EE - they both were not trivial, and just removed unused JIT-EE calls and add "!=0" checks to the VN's compilteTimeHandle cache. We already had that `!=0` check here 
https://github.com/dotnet/runtime/blob/dcf79a484f0c19ea70e58a38cee2e9d5e1939cec/src/coreclr/jit/valuenum.cpp#L4696-L4706

I just added it to other uses of that map.


PTAL @jakobbotsch @kunalspathak @dotnet/jit-contrib

File: src/coreclr/inc/corinfo.h [hunk 1]
```diff
@@ -1204,7 +1204,7 @@ enum CorInfoAccessAllowedHelperArgType
     CORINFO_HELPER_ARG_TYPE_Field   = 1,
     CORINFO_HELPER_ARG_TYPE_Method  = 2,
     CORINFO_HELPER_ARG_TYPE_Class   = 3,
-    CORINFO_HELPER_ARG_TYPE_Module  = 4,
+    // CORINFO_HELPER_ARG_TYPE_Module  = 4,
```
Comment (jakobbotsch) [inline src/coreclr/inc/corinfo.h:1207]: Can we remove it and change the values if we are changing JIT-EE GUID anyway?

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/inc/corinfo.h (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/inc/corinfo.h:1207]: Doesn't it need r2r bump then?

File: src/coreclr/jit/compiler.hpp [hunk 2]
```diff
@@ -1489,13 +1489,7 @@ inline GenTreeIntCon* Compiler::gtNewIconHandleNode(size_t value, GenTreeFlags f
...
 inline GenTree* Compiler::gtNewIconEmbScpHndNode(CORINFO_MODULE_HANDLE scpHnd)
 {
-    void *embedScpHnd, *pEmbedScpHnd;
-
-    embedScpHnd = (void*)info.compCompHnd->embedModuleHandle(scpHnd, &pEmbedScpHnd);
-
-    assert((!embedScpHnd) != (!pEmbedScpHnd));
-
-    return gtNewIconEmbHndNode(embedScpHnd, pEmbedScpHnd, GTF_ICON_SCOPE_HDL, scpHnd);
+    return gtNewIconEmbHndNode((void*)scpHnd, nullptr, GTF_ICON_SCOPE_HDL, scpHnd);
```
Comment (jkotas) [inline src/coreclr/jit/compiler.hpp:1492]: Isn't this introducing an abstraction violation? `CORINFO_XXX_HANDLE`s are not meant to be embedded in the code. We have an intentional distinction between the `CORINFO_XXX_HANDLE` handles used to represent type system entities on JIT/EE interface and how these values get embedded into the code.

It happens to work since these module handles are only used with JIT currently, but this change does not look like an improvement to me.

File: src/coreclr/jit/compiler.hpp [hunk 3]
```diff
@@ -1528,13 +1529,7 @@ inline GenTree* Compiler::gtNewIconEmbMethHndNode(CORINFO_METHOD_HANDLE methHnd)
...
 inline GenTree* Compiler::gtNewIconEmbFldHndNode(CORINFO_FIELD_HANDLE fldHnd)
 {
-    void *embedFldHnd, *pEmbedFldHnd;
-
-    embedFldHnd = (void*)info.compCompHnd->embedFieldHandle(fldHnd, &pEmbedFldHnd);
-
-    assert((!embedFldHnd) != (!pEmbedFldHnd));
-
-    return gtNewIconEmbHndNode(embedFldHnd, pEmbedFldHnd, GTF_ICON_FIELD_HDL, fldHnd);
+    return gtNewIconEmbHndNode((void*)fldHnd, nullptr, GTF_ICON_FIELD_HDL, fldHnd);
```
Comment (jkotas) [inline src/coreclr/jit/compiler.hpp:1532]: Same here

File: src/coreclr/jit/compiler.hpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/jit/compiler.hpp:1492]: @jkotas I just assumed that almost 300 LOC is too much for an API that is just no-op (and CoreCLR) only, I can revert this part.

Looks like the only case where we need to embed a field handle is CoreCLR jitting a method that accesses a field it has no access for, so JIT emits an exception telling about the field access violation. Isn't part of the IL verification that we got rid some time ago?
