### PR TITLE
[JIT] Improve inliner: new heuristics, rely on PGO data

### LINKED ISSUE #7651: Generic Type Check Inlining
@manixrock commented on [Sat Mar 18 2017](https://github.com/dotnet/corefx/issues/17273)

When writing performance-critical code it often leads to code duplication.

Let's say we wanted to make a method that applies an effect on an image, in our case we want to apply a gray-scale and an optional invert. The code could look like this:

```C#
public class Effect
{
    public static void Apply(Bitmap bmp, GreyscaleMethod grayscaleMethod, bool invert)
    {
        // read bitmap data
        int w = bmp.Width, h = bmp.Height;
        var data = bmp.LockBits(new Rectangle(0, 0, w, h), ImageLockMode.ReadWrite, bmp.PixelFormat);
        if (bmp.PixelFormat != PixelFormat.Format32bppArgb)
            throw new InvalidOperationException($"Unsupported pixel format: {bmp.PixelFormat}");
        var s = data.Stride;

        unsafe
        {
            var ptr = (byte*)data.Scan0;
            for (int y = 0; y < h; y++) {
                for (int x = 0; x < w; x++) {
                    // read RGB (not quite optimized, but that's not the point)
                    int offset = y * s + x;
                    int r = ptr[offset + 1];
                    int g = ptr[offset + 2];
                    int b = ptr[offset + 3];

                    // apply effects per pixel
                    if (grayscaleMethod == GreyscaleMethod.Average) {
                        r = g = b = (r + g + b) / 3;
                    } else if (grayscaleMethod == GreyscaleMethod.Luminance) {
                        r = g = b = (int)(r * 0.2126 + g * 0.7152 + b * 0722);
                    }
                    if (invert) {
                        r = 255 - r;
                        g = 255 - g;
                        b = 255 - b;
                    }

                    // write RGB
                    ptr[offset + 1] = (byte)r;
                    ptr[offset + 2] = (byte)g;
                    ptr[offset + 3] = (byte)b;
                }
            }
        }

        bmp.UnlockBits(data);
    }
}

public enum GreyscaleMethod
{
    None,
    Average,
    Luminance,
}
```

However if we expect the invert to be only rarely used, that code is slower than it can be because of the constant `if (invert)` check inside the performance-critical inner loop. We could of course create another method that gets called when `invert` is false, but that leads to code duplication, is harder to maintain, etc.

What we would need to have both optimal performance and code reuse is a way to get the compiler to generate 2 methods at compile time depending on the value of `invert`. Without any new syntax the code might look like this:

```C#
public class Effect
{
    private static void Apply<invert>(Bitmap bmp, GreyscaleMethod grayscaleMethod)
        where invert : Bool
    {
        // [...] read bitmap data

        unsafe
        {
            var ptr = (byte*)data.Scan0;
            for (int y = 0; y < h; y++) {
                for (int x = 0; x < w; x++) {
                    // [...] read RGB

                    // apply effects per pixel
                    if (grayscaleMethod == GreyscaleMethod.Average) {
                        r = g = b = (r + g + b) / 3;
                    } else if (grayscaleMethod == GreyscaleMethod.Luminance) {
                        r = g = b = (int)(r * 0.2126 + g * 0.7152 + b * 0722);
                    }
                    if (typeof(invert) == typeof(True)) { // type check
                        r = 255 - r;
                        g = 255 - g;
                        b = 255 - b;
                    }

                    // [...] write RGB
                }
            }
        }

        bmp.UnlockBits(data);
    }
}

public class False : Bool { }
public class True : Bool { }
public class Bool { }
```

Now that check if a compile-time constant, so the compiler *could* remove the type-condition and its block away when `invert` is `False`, and remove the type-condition but leave its block when `True`, leading to performance optimal code in both cases without code duplication.

However does the compiler (or even the JIT) do that? According to [this stackoverflow answer](http://stackoverflow.com/questions/34306049/will-this-comparison-be-compiled-into-a-constant-boolean-value-in-a-generic-clas) it currently does not.

This is a proposal to improve the compiler (or JIT) to do that sort of code inlining (through method duplication) for compile-time constant checks.

If this were implemented, we can optimize the code even further by doing the same with the `grayscaleMethod` parameter:

```C#
public class Effect
{
    private static void Apply<invert, greyscaleMethod>(Bitmap bmp)
        where invert : Bool
        where greyscaleMethod : GreyscaleMethodEnum
    {
        // [...] read bitmap data

        unsafe
        {
            var ptr = (byte*)data.Scan0;
            for (int y = 0; y < h; y++) {
                for (int x = 0; x < w; x++) {
                    // [...] read RGB

                    // apply effects per pixel
                    if (typeof(greyscaleMethod) == typeof(GreyscaleMethod_Average)) {
                        r = g = b = (r + g + b) / 3;
                    } else if (typeof(greyscaleMethod) == typeof(GreyscaleMethod_Luminance)) {
                        r = g = b = (int)(r * 0.2126 + g * 0.7152 + b * 0722);
                    }
                    if (typeof(invert) == typeof(True)) {
                        r = 255 - r;
                        g = 255 - g;
                        b = 255 - b;
                    }

                    // [...] write RGB
                }
            }
        }

        bmp.UnlockBits(data);
    }
}

public class GreyscaleMethod_None : GreyscaleMethodEnum { }
public class GreyscaleMethod_Average : GreyscaleMethodEnum { }
public class GreyscaleMethod_Luminance : GreyscaleMethodEnum { }
public class GreyscaleMethodEnum { }
```

Doing the same optimization through code duplication would require 6 methods, and the number would increase exponentially with the number of parameters. However the compiler would know to only generate the methods which are actually used in the code.

---

@mikedn commented on [Sat Mar 18 2017](https://github.com/dotnet/corefx/issues/17273#issuecomment-287551967)

This is a runtime/compiler/language issue (coreclr/roslyn repositories), the framework (corefx) doesn't have much to do with this.

> However does the compiler (or even the JIT) do that? According to this stackoverflow answer it currently does not.

The .NET JIT usually does that if you use value types. As in:
```C#
public struct False : IBool { }
public struct True : IBool { }
public interface IBool { }
```
When generic arguments are value types the JIT has to generate specialized code for each value type. That enables some optimization including recognizing that `typeof(invert) == typeof(True)` is always true when `invert` = `True`.

Though there recently a bug was introduced that prevented this optimization from working. It's fixed now in the latest CoreCLR builds but it's still present in some .NET Framework builds (e.g. the one that comes with the current Win 10 Preview).

> Doing the same optimization through code duplication would require 6 methods, and the number would increase exponentially with the number of parameters.

That's why when the code is shared between instantiations when reference types are used. 

> However the compiler would know the only generate the methods which are actually used in the code.

Well, if you call all variants it will still have to generate code for all of them. It is what it is, a trade off between code size and performance.

category:cq
theme:generics
skill-level:expert
cost:large

### LINKED ISSUE #10303: JIT: have inlining heuristics look for cases where inlining might enable devirtualization
When a caller argument is an exact type and feeds a virtual or interface call in the callee, we might want to inline more aggressively.

A toy example of this can be found in [this BenchmarkDotNet sample](https://github.com/dotnet/BenchmarkDotNet/blob/master/samples/BenchmarkDotNet.Samples/JIT/Jit_InterfaceMethod.cs). Here `Run`, if inlined, would allow the interface calls to devirtualize.

`Run` is currently pretty far from being a viable inline candidate:
```
Inline candidate callsite is boring.  Multiplier increased to 1.3.
calleeNativeSizeEstimate=545
callsiteNativeSizeEstimate=115
benefit multiplier=1.3
threshold=149
Native estimate for function size exceeds threshold for inlining 54.5 > 14.9 (multiplier = 1.3)

Inline expansion aborted, inline not profitable

INLINER: during 'fgInline' result 'failed this call site' reason 'unprofitable inline' for
'Jit_InterfaceMethod:Run1():double:this' calling 'Jit_InterfaceMethod:Run(ref):double:this'
```
Caller knows that the argument to `Run` is exact:
```
lvaUpdateClass: Updating class for V01 (00007FF966344CD0) Foo1 to be exact

               [000029] ------------              *  STMT      void  (IL 0x00C...  ???)
               [000027] I-C-G-------              \--*  CALL      double Jit_InterfaceMethod.Run
               [000025] ------------ this in rcx     +--*  LCL_VAR   ref    V00 this         
               [000026] ------------ arg1            \--*  LCL_VAR   ref    V01 loc0         
```

Likely we would not give a ~3.65x boost to inlining benefit based on one argument reaching one call site. But if we also realized the call site was in a loop perhaps the net effect would be enough to justify an inline.

Currently we don't know when observing arg uses whether that use is in a loop or not. But if we were to associate uses with callee IL offsets we could circle back after finding all the branch targets and develop a crude estimator for loop depth, then sum up the weighted observations.

It would also be nice to tabulate a few more opportunities of this kind. The basic observational part change is simple enough to prototype that perhaps just building it is one way to make forward progress.

category:cq
theme:inlining
skill-level:intermediate
cost:medium

### LINKED ISSUE #33338: RyuJIT: optimize comparisons for const strings
Let's say I have a code:
```csharp
public bool Test()
{
    return Validate("FAILED");
}

bool Validate(string name)
{
    return name != "FAILED";
}
```
`Validate` is inlined into `Test` like this:
```csharp
public bool Test(string name)
{
    return !string.Equals("FAILED", "FAILED");
}
```
And it's not optimized into just `false` constant. 
There are 3 solutions to fix it:
1) Intrinsify `string.Equals`, working prototype: https://github.com/EgorBo/runtime-1/commit/06eca1c41039e95415eee0fb42b29ddfc81b4c8c
2) Make `string.Equals` always inlineable via `[MethodImpl(MethodImplOptions.AggressiveInlining)]` and it will work! However, it will significantly regress non-constant cases - definitely not an option.
3) Tweak the inliner a bit, because it almost passes the threshold due to constant args + conditions, a simple repro:
```csharp
public bool Test()
{
    // should be inlined but currently is not.
    return !String_Equals("hello", "hello");
}

public static bool String_Equals(string a, string b) // Code size: 36
{
    if (object.ReferenceEquals(a, b))
    {
        return true;
    }
    // `a is null` and `b is null` increase the multiplier (constant args into constant tests), good
    if (a is null || b is null || a.Length != b.Length) // jit doesn't know `a.Length` and `b.Length
                                                        // will be optimized into constants (see https://github.com/dotnet/runtime/pull/1378)
    {
        return false;
    }

    return EqualsHelper(a, b);
}

[MethodImpl(MethodImplOptions.NoInlining)]
private static bool EqualsHelper(string a, string b) => false;
```
```
Inline candidate looks like a wrapper method.  Multiplier increased to 1.
Inline candidate has an arg that feeds a constant test.  Multiplier increased to 2.
Inline candidate has const arg that feeds a conditional.  Multiplier increased to 5.
Inline candidate callsite is boring.  Multiplier increased to 6.3.
calleeNativeSizeEstimate=521
callsiteNativeSizeEstimate=115
benefit multiplier=6.3
threshold=724
Native estimate for function size is within threshold for inlining 52.1 <= 72.4 (multiplier = 6.3)
// but doesn't pass max amount of BB check :-( 
```
E.g. if I remove `object.ReferenceEquals(a, b)` it will be inlined!

category:cq
theme:inlining
skill-level:intermediate
cost:medium

### LINKED ISSUE #33349: Utf8Formatter.TryFormat causes massive code bloat when used with a constant StandardFormat
The following function compiles to ~900 bytes of code when jitted on x64.

```cs
private static bool Format(Span<byte> span, int value)
{
    return Utf8Formatter.TryFormat(value, span, out _, new StandardFormat('D', 2));
}
```
Adding `AggressiveInlining` to `StandardFormat.ctor` allows the JIT to reduce the `TryFormat` call to a single call to `TryFormatUInt64D`, resulting in a code size of less than 100 bytes.

### LINKED ISSUE #41923: RyuJIT: Don't inline calls inside rarely used basic-blocks
Let's not inline calls inside rarely used basic blocks, e.g. blocks with `throw` (we already don't do it inside `catch` and `filter` ones).
An example with `throw`:
```csharp
Exception GetMyException() => new ArgumentException("should not be zero");

int DoWork(int x)
{
    if (x == 0)
        throw GetMyException();

    return x * 1000;
}
```
#### Current Codegen (inliner inlines `GetMyException()`):
```asm
; Method Program:DoWork(int):int:this
G_M62105_IG01:
       push     rsi
       sub      rsp, 32
						;; bbWeight=1    PerfScore 1.25
G_M62105_IG02:
       test     edx, edx
       je       SHORT G_M62105_IG05
						;; bbWeight=1    PerfScore 1.25
G_M62105_IG03:
       imul     eax, edx, 0x3E8
						;; bbWeight=1    PerfScore 2.00
G_M62105_IG04:
       add      rsp, 32
       pop      rsi
       ret      
						;; bbWeight=1    PerfScore 1.75
G_M62105_IG05: ; <--- cold block
       mov      rcx, 0xD1FFAB1E
       call     CORINFO_HELP_NEWSFAST
       mov      rsi, rax
       mov      ecx, 7
       mov      rdx, 0xD1FFAB1E
       call     CORINFO_HELP_STRCNS
       mov      rdx, rax
       mov      rcx, rsi
       call     System.ArgumentException:.ctor(System.String):this
       mov      rcx, rsi
       call     CORINFO_HELP_THROW
       int3     
						;; bbWeight=0    PerfScore 0.00
; Total bytes of code: 79
```
#### Expected Codegen ([my prototype](https://github.com/EgorBo/runtime-1/commit/5e02b19c21ee03d24a4a7b8859a4c3a754e63f4e)):
```asm
G_M62105_IG01:
       sub      rsp, 40
						;; bbWeight=1    PerfScore 0.25
G_M62105_IG02:
       test     edx, edx
       je       SHORT G_M62105_IG05
						;; bbWeight=1    PerfScore 1.25
G_M62105_IG03:
       imul     eax, edx, 0x3E8
						;; bbWeight=1    PerfScore 2.00
G_M62105_IG04:
       add      rsp, 40
       ret      
						;; bbWeight=1    PerfScore 1.25
G_M62105_IG05:
       call     Program:GetMyException():System.Exception:this
       mov      rcx, rax
       call     CORINFO_HELP_THROW
       int3     
						;; bbWeight=0    PerfScore 0.00
; Total bytes of code: 33
```
-46 bytes of code.

It shouldn't also inline various `SR.get_...()` calls (used a lot across the BCL) string properties for exceptions, e.g.:
```csharp
int DoWork(int x)
{
    if (x == 0)
        throw new ArgumentNullException(SR.InvalidArgument); // get_InvalidArgument() is inlined here

    return x * 1000;
}
```

jit-diff from my [prototype ](https://github.com/EgorBo/runtime-1/commit/5e02b19c21ee03d24a4a7b8859a4c3a754e63f4e)(Release, -pmi -f):
```
C:\prj>jit-diff diff --output C:\prj\jitdiffs -f --core_root C:\prj\runtime-1\artifacts\tests\coreclr\Windows_NT.x64.Release\Tests\Core_Root --base C:\prj\runtime-1\artifacts\bin\coreclr\Windows_NT.x64.Checked_base --diff C:\prj\runtime-1\artifacts\bin\coreclr\Windows_NT.x64.Checked --pmi
Beginning PMI CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies
| Finished 267/267 Base 267/267 Diff [444.3 sec]
Completed PMI CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies in 444.39s
Diffs (if any) can be viewed by comparing: C:\prj\jitdiffs\dasmset_25\base C:\prj\jitdiffs\dasmset_25\diff
Analyzing CodeSize diffs...
Found 166 files with textual diffs.
PMI CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies for  default jit
Summary of Code Size diffs:
(Lower is better)
Total bytes of diff: -701786 (-1.39% of base)
    diff is an improvement.
Top file regressions (bytes):
         400 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.01% of base)
         110 : Microsoft.CodeAnalysis.CSharp.dasm (0.00% of base)
          21 : xunit.core.dasm (0.03% of base)
          21 : xunit.execution.dotnet.dasm (0.01% of base)
          14 : Microsoft.Extensions.FileProviders.Abstractions.dasm (1.63% of base)
           7 : Microsoft.Extensions.FileProviders.Physical.dasm (0.05% of base)
           5 : System.Net.WebProxy.dasm (0.17% of base)
Top file improvements (bytes):
     -103711 : System.Private.CoreLib.dasm (-2.31% of base)
      -64416 : System.Data.Common.dasm (-4.34% of base)
      -55982 : System.Private.Xml.dasm (-1.57% of base)
      -51052 : FSharp.Core.dasm (-1.55% of base)
      -33522 : System.Linq.Queryable.dasm (-12.00% of base)
      -29048 : System.Linq.Expressions.dasm (-3.80% of base)
      -21736 : System.Collections.dasm (-4.80% of base)
      -18318 : System.Private.DataContractSerialization.dasm (-2.43% of base)
      -13409 : Microsoft.VisualBasic.Core.dasm (-2.82% of base)
      -12690 : System.DirectoryServices.dasm (-2.92% of base)
      -12608 : System.Configuration.ConfigurationManager.dasm (-3.63% of base)
      -12391 : Newtonsoft.Json.dasm (-1.43% of base)
      -12161 : System.Security.Cryptography.Algorithms.dasm (-3.78% of base)
      -11517 : System.Threading.Tasks.Dataflow.dasm (-1.36% of base)
      -11124 : System.Collections.Concurrent.dasm (-3.33% of base)
       -9320 : System.Data.OleDb.dasm (-3.14% of base)
       -8294 : System.Net.Http.dasm (-1.12% of base)
       -6524 : System.DirectoryServices.AccountManagement.dasm (-1.81% of base)
       -6445 : System.ComponentModel.Composition.dasm (-1.94% of base)
       -6433 : System.Security.Cryptography.Pkcs.dasm (-1.64% of base)
166 total files with Code Size differences (159 improved, 7 regressed), 101 unchanged.
Top method regressions (bytes):
         129 (17.32% of base) : System.DirectoryServices.dasm - DomainController:GetRoles():ArrayList:this
          83 ( 7.94% of base) : System.DirectoryServices.dasm - Forest:GetSites():ArrayList:this
          76 ( 4.26% of base) : Microsoft.CodeAnalysis.CSharp.dasm - LookupPosition:GetFirstExcludedToken(StatementSyntax):SyntaxToken
          53 ( 6.44% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - SyntaxNodeExtensions:QueryClauseKeywordOrRangeVariableIdentifier(VisualBasicSyntaxNode):SyntaxToken
          45 ( 3.42% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:BindSubsequentQueryOperators(BoundQueryClauseBase,Enumerator,DiagnosticBag):BoundQueryClauseBase:this
          43 ( 3.74% of base) : System.DirectoryServices.dasm - DomainController:GetDomainControllerInfo():this
          37 (17.96% of base) : System.Data.Common.dasm - DataRow:SetParentRowToDBNull(DataRelation):this
          35 (350.00% of base) : System.Configuration.ConfigurationManager.dasm - ConfigurationSectionCollection:.ctor(SerializationInfo,StreamingContext):this
          35 (350.00% of base) : System.Management.dasm - ManagementNamedValueCollection:.ctor(SerializationInfo,StreamingContext):this
          35 (350.00% of base) : System.Net.Requests.dasm - FileWebResponse:.ctor(SerializationInfo,StreamingContext):this
          35 (250.00% of base) : System.Net.Requests.dasm - HttpWebResponse:.ctor(SerializationInfo,StreamingContext):this
          35 (350.00% of base) : System.Security.Cryptography.X509Certificates.dasm - X509Certificate2:.ctor(SerializationInfo,StreamingContext):this
          33 (31.73% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:GetQueryLambdaParameterNameRight(ImmutableArray`1):String
          32 ( 7.24% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:BindXmlContent(XmlNodeSyntax,XmlElementRootInfo,DiagnosticBag):BoundExpression:this
          31 ( 6.70% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - DocumentationCommentCrefBinder:CollectCrefNameSymbolsStrict(TypeSyntax,int,Dictionary`2,ArrayBuilder`1,bool,byref):this
          31 ( 3.73% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - DeclarationTreeBuilder:GetModifiers(SyntaxTokenList):int
          30 ( 0.83% of base) : Microsoft.CodeAnalysis.CSharp.dasm - SourceNamedTypeSymbol:MakeTypeParameters(DiagnosticBag):ImmutableArray`1:this
          30 ( 1.19% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:BindArgumentsAndNames(ImmutableArray`1,byref,byref,byref,DiagnosticBag):this
          29 ( 9.76% of base) : System.Private.Xml.dasm - ReflectionXmlSerializationWriter:WriteArray(Object,Object,ref,TextAccessor,ChoiceIdentifierAccessor,TypeDesc):this
          28 ( 1.21% of base) : System.Numerics.Tensors.dasm - DenseTensor`1:.ctor(Memory`1,ReadOnlySpan`1,bool):this (7 methods)
Top method improvements (bytes):
       -4214 (-31.03% of base) : System.Linq.Queryable.dasm - EnumerableQuery`1:System.Linq.IQueryProvider.CreateQuery(Expression):IQueryable`1:this (49 methods)
       -2058 (-12.05% of base) : System.Data.Common.dasm - EnumerableRowCollection`1:AddSortExpression(Func`2,IComparer`1,bool,bool):this (49 methods)
       -1659 (-29.15% of base) : System.Collections.Concurrent.dasm - BlockingCollection`1:ValidateCollectionsArray(ref,bool) (7 methods)
       -1554 (-25.99% of base) : System.Private.Xml.dasm - FunctionInfo`1:CastArguments(IList`1,String,XPathQilFactory):this (7 methods)
       -1470 (-13.35% of base) : System.Linq.Queryable.dasm - Queryable:Sum(IQueryable`1,Expression`1):Nullable`1 (35 methods)
       -1470 (-13.26% of base) : System.Linq.Queryable.dasm - Queryable:Average(IQueryable`1,Expression`1):Nullable`1 (35 methods)
       -1456 (-19.35% of base) : System.Linq.Parallel.dasm - PartitionerQueryOperatorResults:GivePartitionedStream(IPartitionedStreamRecipient`1):this (7 methods)
       -1358 (-14.67% of base) : System.Configuration.ConfigurationManager.dasm - ConfigurationElement:DeserializeElement(XmlReader,bool):this
       -1309 (-28.33% of base) : System.Data.Common.dasm - ExpressionParser:Parse():ExpressionNode:this
       -1232 (-27.72% of base) : FSharp.Core.dasm - Array:permute(FSharpFunc`2,ref):ref (7 methods)
       -1200 (-22.45% of base) : System.Private.CoreLib.dasm - UnmanagedMemoryAccessor:ReadArray(long,ref,int,int):int:this (6 methods)
       -1200 (-24.84% of base) : System.Private.CoreLib.dasm - UnmanagedMemoryAccessor:WriteArray(long,ref,int,int):this (6 methods)
       -1050 (-12.10% of base) : System.Collections.dasm - Enumerator:System.Collections.IEnumerator.get_Current():Object:this (56 methods)
        -998 (-42.41% of base) : System.Data.Common.dasm - DataColumnCollection:CanRemove(DataColumn,bool):bool:this
        -981 (-12.74% of base) : Newtonsoft.Json.dasm - <ExecuteFilter>d__4:MoveNext():bool:this (8 methods)
        -924 (-19.00% of base) : System.Private.CoreLib.dasm - SafeBuffer:ReadArray(long,ref,int,int):this (6 methods)
        -924 (-19.00% of base) : System.Private.CoreLib.dasm - SafeBuffer:WriteArray(long,ref,int,int):this (6 methods)
        -903 (-10.67% of base) : System.Collections.dasm - Enumerator:MoveNext():bool:this (56 methods)
        -897 (-41.84% of base) : System.Linq.Expressions.dasm - LabelInfo:ValidateJump(LabelScopeInfo):this (2 methods)
        -882 (-13.60% of base) : System.Linq.Queryable.dasm - Queryable:Average(IQueryable`1,Expression`1):double (21 methods)
Top method regressions (percentages):
          35 (350.00% of base) : System.Configuration.ConfigurationManager.dasm - ConfigurationSectionCollection:.ctor(SerializationInfo,StreamingContext):this
          35 (350.00% of base) : System.Management.dasm - ManagementNamedValueCollection:.ctor(SerializationInfo,StreamingContext):this
          35 (350.00% of base) : System.Net.Requests.dasm - FileWebResponse:.ctor(SerializationInfo,StreamingContext):this
          35 (350.00% of base) : System.Security.Cryptography.X509Certificates.dasm - X509Certificate2:.ctor(SerializationInfo,StreamingContext):this
          35 (250.00% of base) : System.Net.Requests.dasm - HttpWebResponse:.ctor(SerializationInfo,StreamingContext):this
          33 (31.73% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:GetQueryLambdaParameterNameRight(ImmutableArray`1):String
          12 (31.58% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - OverloadResolution:.ctor():this
           7 (26.92% of base) : System.Private.Xml.dasm - XmlSchemaSet:InternalValidationCallback(Object,ValidationEventArgs):this
           5 (26.32% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Conversions:.ctor():this (2 methods)
          22 (23.66% of base) : xunit.console.dasm - CommandLine:GuardNoOptionValue(KeyValuePair`2)
          20 (22.47% of base) : System.Data.Common.dasm - DataRow:CheckColumn(DataColumn):this
           8 (20.00% of base) : System.Private.DataContractSerialization.dasm - XmlDictionaryWriter:StartCanonicalization(Stream,bool,ref):this
           8 (20.00% of base) : System.Private.DataContractSerialization.dasm - XmlDictionaryWriter:EndCanonicalization():this
           8 (20.00% of base) : System.Private.DataContractSerialization.dasm - XmlDictionaryReader:StartCanonicalization(Stream,bool,ref):this
           8 (20.00% of base) : System.Private.DataContractSerialization.dasm - XmlDictionaryReader:EndCanonicalization():this
           8 (20.00% of base) : System.Private.DataContractSerialization.dasm - XmlDictionaryReader:ReadValueAsBase64(ref,int,int):int:this
           8 (20.00% of base) : System.Private.DataContractSerialization.dasm - XmlObjectSerializer:InternalWriteStartObject(XmlWriterDelegator,Object):this
           8 (20.00% of base) : System.Private.DataContractSerialization.dasm - XmlObjectSerializer:InternalWriteObjectContent(XmlWriterDelegator,Object):this
           8 (20.00% of base) : System.Private.DataContractSerialization.dasm - XmlObjectSerializer:InternalWriteEndObject(XmlWriterDelegator):this
           8 (20.00% of base) : System.Private.DataContractSerialization.dasm - XmlObjectSerializer:InternalIsStartObject(XmlReaderDelegator):bool:this
Top method improvements (percentages):
        -115 (-86.47% of base) : System.Data.Common.dasm - DataView:System.Collections.IList.set_Item(int,Object):this
        -115 (-86.47% of base) : System.Data.Common.dasm - DataView:System.Collections.IList.Clear():this
        -115 (-86.47% of base) : System.Data.Common.dasm - DataView:System.Collections.IList.Insert(int,Object):this
        -115 (-86.47% of base) : System.Data.Common.dasm - DataViewManager:System.Collections.IList.set_Item(int,Object):this
        -115 (-86.47% of base) : System.Data.Common.dasm - DataViewManager:System.Collections.IList.Add(Object):int:this
        -115 (-86.47% of base) : System.Data.Common.dasm - DataViewManager:System.Collections.IList.Clear():this
        -115 (-86.47% of base) : System.Data.Common.dasm - DataViewManager:System.Collections.IList.Insert(int,Object):this
        -115 (-86.47% of base) : System.Data.Common.dasm - DataViewManager:System.Collections.IList.Remove(Object):this
        -115 (-86.47% of base) : System.Data.Common.dasm - DataViewManager:System.Collections.IList.RemoveAt(int):this
        -115 (-86.47% of base) : System.Data.Common.dasm - LookupNode:Eval():Object:this
        -115 (-86.47% of base) : System.Data.Common.dasm - NameNode:Eval():Object:this
        -115 (-86.47% of base) : System.Data.OleDb.dasm - DbConnectionClosed:get_ServerVersion():String:this
        -115 (-86.47% of base) : System.Data.OleDb.dasm - DbConnectionClosed:Activate(Transaction):this
        -115 (-86.47% of base) : System.Data.OleDb.dasm - DbConnectionClosed:BeginTransaction(int):DbTransaction:this
        -115 (-86.47% of base) : System.Data.OleDb.dasm - DbConnectionClosed:Deactivate():this
        -115 (-86.47% of base) : System.Data.OleDb.dasm - DbConnectionClosed:EnlistTransaction(Transaction):this
        -115 (-86.47% of base) : System.Data.OleDb.dasm - DbConnectionClosed:GetSchema(DbConnectionFactory,DbConnectionPoolGroup,DbConnection,String,ref):DataTable:this
        -115 (-86.47% of base) : System.Data.OleDb.dasm - DbConnectionClosed:CreateReferenceCollection():DbReferenceCollection:this
         -88 (-83.02% of base) : System.Data.Common.dasm - DataAdapter:FillSchema(DataSet,int):ref:this
         -88 (-83.02% of base) : System.Data.Common.dasm - DataAdapter:Fill(DataSet):int:this
12274 total methods with Code Size differences (11855 improved, 419 regressed), 247173 unchanged.
Completed analysis in 35.55s
```
[crossgen2 diff](https://gist.github.com/EgorBo/1b3ff277114016f5ffab36880a138a12):
```
Total bytes of diff: -274844 (-0.73% of base)
```

As far as I understand, such blocks won't be even compiled in future (@AndyAyersMS 's https://github.com/dotnet/runtime/pull/34522) but I guess it still makes sense to abort inlining inside them?

@dotnet/jit-contrib 

category:cq
theme:inlining
skill-level:intermediate
cost:medium

### LINKED ISSUE #47434: Weird inlining of methods optimized by JIT
### Description

I've spotted some weird behavior in code generated by JIT. The image below is self-explaining but a short description from me: we have two similar methods, optimized to the same form (which is just a simple asm instruction, like `blsr` here). In theory, both should be inlined just looking at their size, but apparently, JIT does it only for the first method as shown below.

### Data

image

Here is the link to this snippet: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsAChlTbB1x9sM8gAUIfADK5gAFVkZlAb2Xk7lAEyUqAdlv2bS+9+dJyDQQgmAHNyBEUvHztqP2IUcgBZbFYmAAoASncozyiohHIAXj0DY2AqVKpSUnSI3J98ov0jEwcKqpqsnwBfTu9e+xj/QJDi5rLUgKDQiWxBBhhMyOz+qOIXZ3pmNg4aAEkWKBTcaVwaAA0ADiQaACF8Vloz1HpZGAxDCAB3C3EMG9YMKkZnMFrVcj0lj4Vr4hlNRqVWpMRsD5os6jk6vZWAAzcipaibFjsTj7DCHJjHMCnS7XO4PPa4UQMPh8aAYGAAEzRmLsGJ53jWG0YRJ2pPJlOpV1u90ezzor3eXx+b3+gJRoOh3gh/PIMEEuBgmo8RtW63V5AAZHjzXByFQOpC6trwZ0IV0gA==

### Analysis

We can force the second method to be inlined by `[MethodImpl(MethodImplOptions.AggressiveInlining)]`, in this case, it behaves exactly the same as the first one. 

category:cq
theme:inlining
skill-level:expert
cost:large

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/33338 optimize comparisons for const strings
Closes https://github.com/dotnet/runtime/issues/7651 Generic Type Check Inlining
Closes https://github.com/dotnet/runtime/issues/10303 have inlining heuristics look for cases where inlining might enable devirtualization
Closes https://github.com/dotnet/runtime/issues/47434 Weird inlining of methods optimized by JIT
Closes https://github.com/dotnet/runtime/issues/41923 Don't inline calls inside rarely used basic-blocks
Closes https://github.com/dotnet/runtime/issues/33349 Utf8Formatter.TryFormat causes massive code bloat when used with a constant StandardFormat

This PR was split, the first part is https://github.com/dotnet/runtime/pull/53670

**Inlining** is one of the most important compiler optimizations - it significantly widens opportunities for other optimizations such as Constant Folding, CSE, Devirtualization, etc. Unfortunately, there is no Silver Bullet to do it right and it's essentially a sort of an NP complete [Knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem), especially in JIT environments where we don't see the whole graph of all calls, new types can be loaded/added dynamically, and we're limited in time, e.g. we can't just try to import all the possible callees into JIT's IR nodes, apply all the existing optimizations we have and decide whether it was profitable or not - we only have time to quickly inspect raw IL and note some useful patterns (furthermore, we ask R2R to bake "noinline" into non-profitable methods forever).

It's important to note possible **regressions** due to bad Inlining decisions:
  - Significant codegen size increase - it can be noticeable for the AOT'd (R2R) code. There are cases where inlining actually reduces size of callers, but mostly it's a trade-off between size and performance.
  - Always regresses JIT's throughput (we analyze/inline more and it's not cheap). Visible effect - it takes longer to warmup/start an app/process first request.
  - CPUs have limited sets of registers, so if we inline a callee with a lot of temps inside - we might cause serious problems for the Register Allocator (that, just like the inliner, also uses heuristics 🙂). 
  - Bigger functions/loop bodies may not fit into CPU caches.
  - Jit has a hard-coded limit of locals it can track (`lclMAX_TRACKED=512`) - a good example is this [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9JqwBCHAGb6ZuFjt5dsUAJ4bqmgMxNSDIQwDeNBl4afvxFAwAKqoYABSyYthcADzAVhgwAHwMuORoDBFRsfFJKaQAlL5eHtTeZQwAggAmVaGp6bgFtuXe1bX1efnNLZU1dWmd3S1t/Q1NReUjHY1dE2VTAzNDk33T46U9C2OzG8Ori+s9ve0HO0dbgzRz3gD0dzcM3JD4AjwMGAAWvLgMkuYwDCiVQYz0isBBECqMAA5jAuNcvPcHlYIBwGAB3KSSFIwAGfb4gBgfDAYMS4EB3dFUlhVXiGMAfGBgADWMhYzxuvAAahwPgBOexVABWCIYdwuSwmAF8rrsGABtACyME+kIAkuJJKFlaqqhqxJIAPJiPgQLgmCrQ6GwXC4XgKGBqrh/LjmaH5AC6E38x3CkRicQSyQ6mQDOWDBQmJSO5gwDF4DAAvAwzBZrAAFKD8Xh8B0mNgwbB6nj2UhmaEAUS4tKi/TOPVTlismezudULAA6lmEk6MKXy1Wa1w6qR0rx614ZdQpUA=) snippet.

## Current approach in RyuJIT
In RyuJIT we have several strategies (or policies) such as `DefaultPolicy`, `ModelPolicy` (based on some ML model to estimate impact), `SizePolicy` (prefers size over perf) and `ProfilePolicy` (heavily relies on PGO data). But only `DefaultPolicy` is used in Production. Its algorithm can be explained in 5 steps:
1) Make some quick pre-checks, e.g.:
    - Callee is less than 16 bytes of IL code or has `AggressiveInlining` attribute - always inline
    - Callee is larger than 100 bytes of IL code or has `NoInlinine` - always ignore
    - Callee has EH, stackalloc (and callsite is in a loop), etc - always ignore
    - Check that we don't exceed depth of calls, amount of basic-block and time budget.
2) Roughly estimate codegen size of the callsite (NOTE: we don't take current caller's size into account directly)
3) Roughly estimate codegen size of the inline candidate by using a state-machine that accepts raw IL code and applies some weight for all IL opcodes.
4) Inspect **raw IL** and try to find some useful observations (heuristics) and compose a so called "Benefit multiplier"
5) Make a decision using the following formula: `bool toInline = callsiteNativeSize * BenefitMultiplier > calleeNativeSize`
An example with logs:
image
_(BTW, in this PR this method is inlined)_

## Things this PR tries to improve
1) Add more observations (it's done in https://github.com/dotnet/runtime/pull/53670) on top of raw IL, such as
    - Inline candidate has some abstract class in its signature for one of the arguments and we pass something known at the callsite. If we inline it we'll be able to devirtualize all calls inside the callee even without the GDV (Guarded Devirtualization).
    - Inline candidate is generic when caller is not
    - Inline candidate has foldable unary/binary expressions and even branches when we pass a constant argument(s).
    - Inline candidate has foldable BOX/UNBOX operations (generics emit a lot of them).
    - Inline candidate has an expensive "X / Arg" expression and we pass a constant at the callsite for the Arg - if we inline it - we'll avoid expensive `idiv`.
    - It now is able to recognize more potentially foldable branches, even patterns like `typeof(T1) == typeof(T2)` or `argStr.Length == 10` when `argStr` is a string literal at the callsite. (NOTE: only during prejitting or when a method was promoted to tier1 naturally. Won't work for methods with loops or with TieredCompilation=0).
    - Inline candidates pass/returns a large struct by value - we might avoid redundant copies if we inline.
    - there are few more
A small example that covers some of the new observations inliner makes:
image

Thanks to @tannergooding's work we can now resolve some `call` tokens and recognize intrinsics.

2) Refactor `fgFindJumpTarget` and `PushedStack`: We pushed opcodes to that two-slots stack in order to recognize some patterns in the next (binary/unary) opcodes - unfortunately we ignored a lot of opcodes and it led to invalid state in that stack => invalid observations. Such invalid observations were the main source of regressions in my PR because some of them led to a better performance for some reason 😐.

3) Find more optimal multipliers for the observations (using micro/TE benchmarks, deep performance analysis of traces/regressions, example: https://github.com/dotnet/runtime/pull/52708#issuecomment-864066466).
4) Rely on PGO data - the most important part. We try harder to inline what was recognized as hot. Unfortunately, there are cases where a profile can be misleading/polluted and mark hot or semi-hot blocks as cold:

    - We don't support context-sensitive instrumentation in Dynamic PGO mode (see example in https://github.com/dotnet/runtime/pull/53840)
    - The Static PGO that we ship can be irrelevant for some apps.
    - We don't support deoptimizations so we can't re-collect profiles if something changes in the workflow over time.
    - Sometimes it's still makes sense to inline methods in cold blocks to improve type/escape analysis for the whole caller. Example: [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNYgGYmpBkMl5cVagG8GlhjStNdvHgwAqqjAAoHGBtgCUNq2b+tpYK2FAMEMAAVgwAvAxcMADuBka4Jm4+GtTBVkHBvABmDG7YDAA8DHQ+DAD0tQwAMjAYAOS43ukcAgwYABa8HZBcACa8fBBcDIMJMAoyvVAcMPm2gTm5wfUMuBC9A0PYkpLTQxCSIwxw3qMMSTAMI5OtXg6SDg/jDMAwYNgcuAeEGKAC8ZHt7rwAOZ9DCrTYiC4AWRafQgIzckSiWXhuWIAHYqtlNgwAL64hgwSSAinrEm2bZorxibD9Cm2AkMFCkYmbckbSz82z5bYAOQgKVg+Ag832M3FAEkuO8uA4oTdLpFAVBZWiUv0HpARjAoTApmA+tguKbcPkANoo/rohXiSRuR1okYusSSADyYgmXFwLEVyocap8AF18jomCgDOcRh70W5fdFfl4IH4BQw6ZttpMVHdPmHEtMvBg9i5cF5rtWvEkpCdCtCOLAIhwK5bM9FTrN5uEATARhTtlbLo3jgxTV4oLxNcUDd5jhA/oGWPl+aSgA=)

5) Allow JIT to inline bigger functions if really needed: more than 5 basic-blocks and more than 100 bytes of IL.

## Metodology
For now, I mostly run various benchmarks (TE, dotnet/performance, PowerShell, Kestrel, SignalR), analyze collected samples (flamegraphs) produced by profilers/dotnet trace/BDN itself in hot spots where I inspect all calls in the chains and if I see a method that looks like it should be inlined - I try to find what kind of observations (and corresponding benefit multipliers) can make it happen, example:
image

There are some thoughts on how to automatize it using ML/Genetic Algorithms.

## Benchmarks

I use [PerfLab machines](https://github.com/aspnet/Benchmarks/tree/main/scenarios#profiles) for TE/SignalR/YARP benchmarks. Besides that, I have locally:

- **Win** - Windows 10 x64, Core i7 8700K (4 cores, 3.7Ghz, Coffee Lake, AVX2)
- **Linux** - Ubuntu 20.04 x64, Core i7 4930K (6 cores, 3.4Ghz, Ivy Bridge E, AVX1)
- **Arm64** - macOS 11.5 arm64 (Mac Mini M1, arm64-v8.3(or higher?))

Also, I use different JIT modes:
- **Default** - Default arguments.
- **NoPGO** - same as **Default**, but without static PGO collected from various benchmarks/workloads. I use this mode to estimate overall impact from PGO when compared against **FullPGO** (in .NET 5.0 we didn't have any static profile so it kind of simulates net5.0).
- **DynPGO**:
    - `DOTNET_TieredPGO=1` - collect profile in tier0. 
    - `DOTNET_TC_QuickJitForLoops=1` - so we also instrument methods with loops on tier0. By default they bypass tier0 to avoid "cold loops with hot bodies" problem (OSR is not enabled by default yet).
- **FullPGO**: same as **DynPGO** but with:
    - `DOTNET_ReadyToRun=0` - ignore all AOT code and re-collect actual profile (with better class probes).
    
## Results
It seems like this PR unlocks PGO and GDV potential in FullPGO mode. Many high-load benchmarks show +10-20% improvements. I tried to avoid startup/time-to-first-request regressions in the Default mode so the RPS numbers are not as great as they could be with a more aggressive inliner. In order to avoid size regressions in R2R, we use the "old" inliner - it leads to zero improvements when we benchmark R2R'd code in `DOTNET_TieredCompilation=0` mode (e.g. `dotnet/performance` microbenchmarks). Also, prejitter bakes "noinline" into thousands of method using the old algorithm and kind of limits possibilities for the new one during prejitting.

The latest run of TE benchmarks on aspnet-citrine-lin:
Linux-lessagr-1
^ some P90-P99 numbers regressed because, I believe, they include the warmup stage, so when I try to run a specific benchmark and ask it to run longer than 30 seconds - P99 numbers are greatly improved)
Also, don't expect large numbers from Platform-* benchmarks, those are heavily optimized by hands 😐.
**UPD**: the latest numbers: https://github.com/dotnet/runtime/pull/52708#issuecomment-869024952

NoPGO vs FullPGO (mainly to estimate impact of PGO and show room for improvements for the Default mode, NOTE: NoPGO numbers should be slightly better than the current results for .NET 5.0 in the Default mode):
nopgo-vs-fullpgo **UPD** new numbers: https://github.com/dotnet/runtime/pull/52708#issuecomment-870860458

JIT ET events show that the improved inliner usually inlines 10-20% more functions, e.g.:
Plaintext-MVC (Default mode):
image

Orchard CMS (Default mode):
image

YARP Proxy (Default mode):
image

### CODE REVIEW

File: src/coreclr/jit/fgbasic.cpp [hunk 1]
```diff
@@ -908,13 +937,14 @@ void Compiler::fgFindJumpTargets(const BYTE* codeAddr, IL_OFFSET codeSize, Fixed
             opts.lvRefCount++;
         }
 
-        if (makeInlineObservations && (opcode >= CEE_LDNULL) && (opcode <= CEE_LDC_R8))
+        if (makeInlineObservations &&
+            (((opcode >= CEE_LDNULL) && (opcode <= CEE_LDC_R8)) || ((opcode == CEE_LDSTR) && (opcode == CEE_LDTOKEN))))
```
Comment (tannergooding) [inline src/coreclr/jit/fgbasic.cpp:941]: > (opcode == CEE_LDSTR) && (opcode == CEE_LDTOKEN)

This will always be false, should it have been `||`?

File: src/coreclr/jit/fgbasic.cpp [hunk 2]
```diff
@@ -955,35 +1000,126 @@ void Compiler::fgFindJumpTargets(const BYTE* codeAddr, IL_OFFSET codeSize, Fixed
...
                 }
 
                 if (isJitIntrinsic)
                 {
-                    intrinsicCalls++;
                     ni = lookupNamedIntrinsic(methodHnd);
 
+                    bool foldableIntrinsc = false;
+
+                    if (IsMathIntrinsic(ni) && FgStack::IsConstant(pushedStack.Pop()))
```
Comment (tannergooding) [inline src/coreclr/jit/fgbasic.cpp:1019]: Notably certain intrinsics are only foldable when we aren't in prejit scenarios due to xplat differences.

Others, like `sqrt`, are always emitted as an instruction rather than a call (we have some existing helper methods for differentiating some of these).

File: src/coreclr/jit/fgbasic.cpp [hunk 3]
```diff
@@ -955,35 +1000,126 @@ void Compiler::fgFindJumpTargets(const BYTE* codeAddr, IL_OFFSET codeSize, Fixed
...
                         case NI_IsSupported_True:
                         case NI_IsSupported_False:
                         {
+                            foldableIntrinsc = true;
                             pushedStack.PushConstant();
                             break;
                         }
+#if defined(TARGET_XARCH) && defined(FEATURE_HW_INTRINSICS)
+                        case NI_Vector128_get_Count:
+                        case NI_Vector256_get_Count:
```
Comment (tannergooding) [inline src/coreclr/jit/fgbasic.cpp:1086]: These ones also allow loop unrolling.

File: src/coreclr/jit/fgbasic.cpp [hunk 4]
```diff
@@ -955,35 +1000,126 @@ void Compiler::fgFindJumpTargets(const BYTE* codeAddr, IL_OFFSET codeSize, Fixed
...
+                        case NI_Vector64_get_Count:
+                            foldableIntrinsc = true;
+                            pushedStack.PushConstant();
+                            break;
+                        case NI_Vector128_get_Zero:
+                        case NI_Vector128_get_AllBitsSet:
+                            foldableIntrinsc = true;
+                            pushedStack.PushUnknown();
+                            break;
+#endif
```
Comment (tannergooding) [inline src/coreclr/jit/fgbasic.cpp:1106]: Create is another interesting case, currently if all arguments are constant we'll fold it to a constant.

In the future we would ideally also do folding if "most" inputs are constant.

Comment (EgorBo) [reply src/coreclr/jit/fgbasic.cpp:1116]: Good catch, for now I'll leave it as "if first arg is a const - we most likely will fold it" - I mean how popular patterns such as `Vector.Create(cns, x, x2, ...)` anyway

File: src/coreclr/jit/fgbasic.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/jit/fgbasic.cpp:1095]: left a comment about it, thanks!

**Comment by EgorBo** [comment]
@tannergooding Thanks for the feedback! Yeah it's early stage WIP but still open for any feedback :)

File: src/coreclr/jit/fgbasic.cpp [hunk 5]
```diff
@@ -810,36 +819,45 @@ class FgStack
...
+    {
+        FgSlot const top = Pop();
+        Push(top);
+        Push(top);
+    }
+    FgSlot Pop()
+    {
+        if (depth == 0)
+        {
+            // We don't maintain a 100% precise stack
```
Comment (tannergooding) [inline src/coreclr/jit/fgbasic.cpp:832]: What's stopping us from doing so? We are resolving the call tokens and so should know argument counts and therefore how many values to push/pop for any given opcode, right?

Comment (EgorBo) [reply src/coreclr/jit/fgbasic.cpp:832]: @tannergooding I hope eventually it will be so 🙂 maybe even some sort of a lightweight IR - at the moment it handle only a limitted set of opcodes and pushes just a single SLOT_UNKNOWN for everything else.

**Comment by EgorBo** [comment]
[PowerShell benchmarks](https://github.com/PowerShell/PowerShell/tree/master/test/perf/benchmarks):



### EgorPR vs Main (both use default options)
```
| Faster                                                                           | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| -------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "[System.IO.Path]::HasExtensio |      1.14 |          1391.54 |          1221.81 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "'String'.GetType()")          |      1.12 |          1388.71 |          1237.80 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$fs=New-Object -ComObject scr |      1.03 |         51735.42 |         50022.99 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$sh=New-Object -ComObject She |      1.01 |        800938.54 |        791337.34 |         |
```

### EgorPR vs Main (both with `TieredPGO=1`)
```
| Faster                                                                           | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| -------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "[System.IO.Path]::HasExtensio |      1.11 |          1380.31 |          1238.58 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "'String'.GetType()")          |      1.08 |          1328.81 |          1225.96 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$fs=New-Object -ComObject scr |      1.04 |         52990.23 |         50767.35 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$sh=New-Object -ComObject She |      1.00 |        800167.43 |        797408.22 |         |
```
### EgorPR vs Main (both with `TieredPGO=1`, `TC_QJFL=1`, `R2R=0`)
```
| Faster                                                                           | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| -------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "[System.IO.Path]::HasExtensio |      1.13 |          1255.56 |          1111.88 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "'String'.GetType()")          |      1.11 |          1264.97 |          1142.72 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$fs=New-Object -ComObject scr |      1.09 |         50208.35 |         46165.40 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$sh=New-Object -ComObject She |      0.99 |        796278.44 |        791500.94 |         |
```

### EgorPR vs Main (both with `TieredPGO=1`, `TC_QJFL=1`, `R2R=0`, `OSR=1`)
```
| Faster                                                                           | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| -------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "'String'.GetType()")          |      1.15 |          1246.77 |          1086.10 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "[System.IO.Path]::HasExtensio |      1.14 |          1254.56 |          1103.60 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$fs=New-Object -ComObject scr |      1.08 |         49737.66 |         46118.86 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$sh=New-Object -ComObject She |      0.99 |        792781.88 |        796818.28 |         |
```
### Main (Default options) vs Main (`TieredPGO=1`, `R2R=0`, `TC_QJFL=1`, `OSR=1`)
```
| Faster                                                                           | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| -------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "'String'.GetType()")          |      1.11 |          1388.71 |          1246.77 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "[System.IO.Path]::HasExtensio |      1.11 |          1391.54 |          1254.56 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$fs=New-Object -ComObject scr |      1.04 |         51735.42 |         49737.66 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$sh=New-Object -ComObject She |      1.01 |        800938.54 |        792781.88 |         |
```
### Main (Default options) vs EgorPR (`TieredPGO=1`, `R2R=0`, `TC_QJFL=1`, `OSR=1`)
```
| Faster                                                                           | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| -------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "'String'.GetType()")          |      1.28 |          1388.71 |          1086.10 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "[System.IO.Path]::HasExtensio |      1.26 |          1391.54 |          1103.60 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$fs=New-Object -ComObject scr |      1.12 |         51735.42 |         46118.86 |         |
| Engine.Scripting.InvokeMethod(InvokeMethodScript: "$sh=New-Object -ComObject She |      1.01 |        800938.54 |        796818.28 |         |
```

**Comment by EgorBo** [comment]
GRPC benchmarks https://github.com/LesnyRumcajs/grpc_bench/ - not much
+0.5% in the default mode (ThisPR vs Main)
+1.1% for ThisPR+DynPGO vs Main-Default.

(with `GRPC_SERVER_CPUS=3` and `GRPC_CLIENT=3`)

**Comment by EgorBo** [comment]
JSON deserialization example over a quite complicate file: [Perf_Enumerable-report-full.json](https://gist.github.com/EgorBo/8787a54cccc8e2ef020231f911fd1881)
```csharp
[Benchmark]
public RootObj ParseTextJson() => JsonSerializer.Deserialize<RootObj>(TestFileBytes);
```
```
|             Method |        Job |                    Toolchain |       Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------- |----------- |----------------------------- |-----------:|---------:|---------:|------:|--------:|
|      ParseTextJson | Job-VFKUTY | \runtime-main\..\corerun.exe |   900.7 us | 13.95 us | 13.05 us |  1.10 |    0.02 |
|      ParseTextJson | Job-BYFRBX |   \runtime-pr\..\corerun.exe |   817.9 us |  1.18 us |  0.92 us |  1.00 |    0.00 |
```

**Comment by EgorBo** [comment]
aspnet Kestrel microbenchmarks: (150 benchmarks) https://gist.github.com/EgorBo/719020f50575c34c146be535d44721ce
```
--threshold 1% --noise 10ns
summary:
better: 59, geomean: 1.159
worse: 1, geomean: 1.026
total diff: 60
```

**Comment by danmoseley** [comment]
Detailed PR descriptions like this are great for curious observers like me. Kudos!

**Comment by EgorBo** [comment]
> Detailed PR descriptions like this are great for curious observers like me. Kudos!

Thanks!
Here is a python script I used to run the TE benchmarks via crank: https://gist.github.com/EgorBo/467ace3ed0bb38db62b5979c2722e1c7

**Comment by sebastienros** [comment]
We usually base the acceptance criteria on citrine. I appreciate that you did you investigations on the small machines, but it will be preferable to share the final results from citrine here. Might be even better gains!

**Comment by EgorBo** [comment]
> We usually base the acceptance criteria on citrine. I appreciate that you did you investigations on the small machines, but it will be preferable to share the final results from citrine here. Might be even better gains!
> 
> Update:
> Can this be run on Linux too? Since official TE is Linux only.

Initially I just wanted to tests some configs, didn't plan to publish any results, but the numbers looked too nice 🙂 I'll publish both Windows and Linux citrine once I validate some theories

**Comment by EgorBo** [comment]
Citrine-Linux (Intel, 28 cores, Ubuntu 18.04, 40Gb bandwidth):

image

Each config was ran twice, "Platform *" benchmarks were expected to have a small diff since they're heavily optimized by hands but still quite some numbers.

Let me know if I should also test some other configurations (e.g. Multiquery, etc).

**Comment by EgorBo** [comment]
Latest round `aspnet-citrine-lin` with a slightly less aggressive inliner:







Time-to-first-request noticeably regressed (it was even worse in the previous results) but I believe I managed to cut it in half in the latest commits (testing now).

Also, I introduced two new global options:

- `DOTNET_JitConservativeInliner=0` - allows to switch to the previous ("conservative") version of the inliner.
- `DOTNET_JitMaxLocalsToTrack=512` - Configurable limit of locals jit can track. 

Current state:
System.Private.CoreLib.dll 9.54 -> 9.83Mb (+3%)

I believe I can mark it as ready-to-review. 
There is a failing test I am currently look at. I guess the additional mutlitplier (10) our jit stress tests use was not enough to uncover it.

/cc @AndyAyersMS

File: src/coreclr/jit/compiler.h [hunk 6]
```diff
@@ -10363,9 +10363,11 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     static fgWalkPreFn gsMarkPtrsAndAssignGroups; // Shadow param analysis tree-walk
     static fgWalkPreFn gsReplaceShadowParams;     // Shadow param replacement tree-walk
 
-#define DEFAULT_MAX_INLINE_SIZE 100 // Methods with >  DEFAULT_MAX_INLINE_SIZE IL bytes will never be inlined.
+#define DEFAULT_MAX_INLINE_SIZE 300 // Methods with >  DEFAULT_MAX_INLINE_SIZE IL bytes will never be inlined.
```
Comment (tannergooding) [inline src/coreclr/jit/compiler.h:10366]: I wonder if this (and other inlining variables) should be customizable via config knobs (assuming they aren't already).

It seems like the kind of thing that would be good to allow tweaking/customization of without recompiling so we can more easily get perf numbers or run stress tests.

File: src/coreclr/jit/importer.cpp [hunk 7]
```diff
@@ -20611,16 +20608,6 @@ bool Compiler::IsTargetIntrinsic(NamedIntrinsic intrinsicName)
         case NI_System_Math_Round:
             return compOpportunisticallyDependsOn(InstructionSet_SSE41);
 
-        case NI_System_Math_FusedMultiplyAdd:
```
Comment (tannergooding) [inline src/coreclr/jit/importer.cpp:20614]: Now that we are calling this (`isTargetIntrinsic`) as part of the early inlining observations, we might want to observe `Math.FMA` calls as target intrinsics, right?

File: src/coreclr/jit/compiler.h (hunk 6 above)
Comment (EgorBo) [reply src/coreclr/jit/compiler.h:10366]: These already are, but in Debug only. I have an improvement in works to make this limit more dynamic and depend on:
1) Profile data
2) NonGenericCallsGeneric observation

File: src/coreclr/jit/importer.cpp (hunk 7 above)
Comment (EgorBo) [reply src/coreclr/jit/importer.cpp:20614]: Indeed, thanks!

**Comment by EgorBo** [comment]
Plaintext MVC benchmark looks even nicer when it's compared against .NET5.0 🙂:
```
.NET 5.0 Default: 1,781,948 requests/s
.NET 6.0 FullPGO: 2,820,839 requests/s
```

File: src/coreclr/jit/jitconfigvalues.h [hunk 8]
```diff
@@ -383,6 +383,15 @@ CONFIG_INTEGER(JitAggressiveInlining, W("JitAggressiveInlining"), 0) // Aggressi
...
 CONFIG_INTEGER(JitInlineSIMDMultiplier, W("JitInlineSIMDMultiplier"), 3)
 
+// Use a less aggressive and profile-independent inliner (which was the default one for < .NET 6.0).
+CONFIG_INTEGER(JitConservativeInliner, W("JitConservativeInliner"), 0)
+
+// Ex lclMAX_TRACKED constant.
+// Tested various sizes for max tracked locals. The largest value for which no throughput regression
+// could be measured was 512. Going to 1024 showed the first throughput regressions.
+// We anticipate the larger size will be needed to support better inlining.
+CONFIG_INTEGER(JitMaxLocalsToTrack, W("JitMaxLocalsToTrack"), 512)
```
Comment (AndyAyersMS) [inline src/coreclr/jit/jitconfigvalues.h:393]: Note integer values here are parsed as hex, so 512 is actually 1298; for 500 you'd want 200.

File: src/coreclr/jit/jitconfigvalues.h [hunk 9]
```diff
@@ -383,6 +383,15 @@ CONFIG_INTEGER(JitAggressiveInlining, W("JitAggressiveInlining"), 0) // Aggressi
 CONFIG_INTEGER(JitELTHookEnabled, W("JitELTHookEnabled"), 0)         // If 1, emit Enter/Leave/TailCall callbacks
 CONFIG_INTEGER(JitInlineSIMDMultiplier, W("JitInlineSIMDMultiplier"), 3)
 
+// Use a less aggressive and profile-independent inliner (which was the default one for < .NET 6.0).
+CONFIG_INTEGER(JitConservativeInliner, W("JitConservativeInliner"), 0)
+
+// Ex lclMAX_TRACKED constant.
+// Tested various sizes for max tracked locals. The largest value for which no throughput regression
+// could be measured was 512. Going to 1024 showed the first throughput regressions.
+// We anticipate the larger size will be needed to support better inlining.
```
Comment (AndyAyersMS) [inline src/coreclr/jit/jitconfigvalues.h:392]: Would be good to redo these studies; a lot has changed since we last measured this.

File: src/coreclr/jit/inlinepolicy.cpp [hunk 10]
```diff
@@ -711,7 +711,23 @@ void DefaultPolicy::NoteInt(InlineObservation obs, int value)
...
+                    {
+                        basicBlockLimit += static_cast<unsigned>(min(m_ProfileFrequency, 1.0) * 3.0);
+                    }
+                    basicBlockLimit = min(12, basicBlockCount);
+                }
+                if (basicBlockCount > basicBlockLimit)
+                {
+                    JITDUMP("basicBlockCount=%d > basicBlockLimit=%d\n", basicBlockCount, basicBlockLimit);
+                    SetNever(InlineObservation::CALLEE_TOO_MANY_BASIC_BLOCKS);
+                }
```
Comment (AndyAyersMS) [inline src/coreclr/jit/inlinepolicy.cpp:730]: I never really understood why we had this limit in the first place. And with the new logic it looks even more arbitrary than before. So I would strongly consider not having a block limit for the "new" inliner.

Ideally I'd like to see this sort of behavior encapsulated via a new policy rather than a check like you're doing above -- that is we'd always observe the number of blocks but this new policy would simply ignore the observation.

File: src/coreclr/jit/fgbasic.cpp [hunk 11]
```diff
@@ -855,9 +893,8 @@ void Compiler::fgFindJumpTargets(const BYTE* codeAddr, IL_OFFSET codeSize, Fixed
     const bool  isPreJit               = opts.jitFlags->IsSet(JitFlags::JIT_FLAG_PREJIT);
     const bool  resolveTokens          = makeInlineObservations && (isTier1 || isPreJit);
     unsigned    retBlocks              = 0;
-    unsigned    intrinsicCalls         = 0;
     int         prefixFlags            = 0;
-    int         value                  = 0;
+    bool        conservativeInliner    = JitConfig.JitConservativeInliner();
```
Comment (AndyAyersMS) [inline src/coreclr/jit/fgbasic.cpp:897]: You should make the fidelity of the stack model be a property of the inline policy.

File: src/coreclr/jit/fgbasic.cpp [hunk 12]
```diff
@@ -899,9 +936,24 @@ void Compiler::fgFindJumpTargets(const BYTE* codeAddr, IL_OFFSET codeSize, Fixed
...
+    OPCODE opcode     = CEE_NOP;
+    OPCODE prevOpcode = CEE_NOP;
+    bool   handled    = false;
     while (codeAddr < codeEndp)
     {
-        OPCODE opcode = (OPCODE)getU1LittleEndian(codeAddr);
+        if (!handled && !conservativeInliner)
+        {
+            // Push SLOT_UNKNOWN to the stack since the current opcode was not handled
+            pushedStack.PushUnknown();
```
Comment (AndyAyersMS) [inline src/coreclr/jit/fgbasic.cpp:947]: This still leaves us with potentially bogus non-top stack values for operations that do multiple pops, right?

How hard would it be to get the stack model "correct"? 

For everything but calls we should be able to make it table driven as the information is in `opcode.def`.

File: src/coreclr/jit/fgbasic.cpp [hunk 13]
```diff
@@ -999,28 +1097,145 @@ void Compiler::fgFindJumpTargets(const BYTE* codeAddr, IL_OFFSET codeSize, Fixed
                     isJitIntrinsic = eeIsJitIntrinsic(methodHnd);
                 }
 
-                if (isJitIntrinsic)
+                if (isJitIntrinsic && conservativeInliner)
```
Comment (AndyAyersMS) [inline src/coreclr/jit/fgbasic.cpp:1100]: Consider moving some of this logic to helper methods; this method is already huge.

File: src/coreclr/jit/inlinepolicy.cpp [hunk 14]
```diff
@@ -1058,41 +1163,95 @@ double DefaultPolicy::DetermineMultiplier()
...
     {
-        const bool callSiteIsInLoop = m_CallsiteFrequency == InlineCallsiteFrequency::LOOP;
-        JITDUMP("\nInline has %d backward jumps (loops?).", m_BackwardJump);
-        if (callSiteIsInLoop)
+        // m_ProfileFrequency values:
+        //   > 1  -- the callsite is inside a hot loop
+        //   1    -- the callsite is as hot as its method's first block
+        //   ~= 0 -- the callsite is cold.
+        //
+        multiplier *= min(0.5 + m_ProfileFrequency * 15.0, 6.0);
```
Comment (AndyAyersMS) [inline src/coreclr/jit/inlinepolicy.cpp:1201]: Whenever there's some complex logic like this, please add a comment explaining the reasoning behind it.

The system of magic weights here is already pretty obscure; formulas like this are doubly so.

File: src/coreclr/jit/inlinepolicy.cpp [hunk 15]
```diff
@@ -1058,41 +1163,95 @@ double DefaultPolicy::DetermineMultiplier()
...
     {
         // E.g. callee has "x / arg0" where arg0 is a const at the call site -
         // we'll avoid a very expensive DIV instruction after inlining.
-        JITDUMP("\nInline has %d Div-by-constArg expressions.", m_DivByCns);
+        // multiplier += 3.0 + m_DivByCns;
+        JITDUMP("\nInline has %d Div-by-constArg expressions.  Multiplier increased to %g.", m_DivByCns, multiplier);
     }
 
-    if (m_BackwardJump)
+    if (m_HasProfile && (m_CallsiteFrequency != InlineCallsiteFrequency::RARE))
```
Comment (AndyAyersMS) [inline src/coreclr/jit/inlinepolicy.cpp:1194]: Does this rare exclusion still make sense? Seems like if the call site frequency is low enough it could naturally suppress inlining, if the multiplier value was < 1.0?

**Review by AndyAyersMS — COMMENTED** [review]
I'd much rather see the new behavior captured by a new policy rather than by a global switch that is used in a bunch of places in the jit and alters the existing default policy behavior. That's the reason these policies exist -- to encapsulate this sort of behavior. The config option would then determine which policy to use (as we do for other policies).

I'm ambivalent about whether this new policy should be on by default or not. I'm not sure what that extra 3% code size in a prejitted SPC is buying us since none of that code is normally perf critical.

So consider perhaps only enabling by default for jitted code? You will need to keep an eye on startup impact in more boring scenarios like .NET CLI, etc.

**Comment by AndyAyersMS** [comment]
> So consider perhaps only enabling by default for jitted code? You will need to keep an eye on startup impact in more boring scenarios like .NET CLI, etc.

Actually we need to be careful with the inline policy being too restrictive when prejitting. When we prejit methods we make a determination as to whether the methods will ever be viable inline candidates. So for the "prejit root" analysis we may still want to use your new heuristics, but for prejit inlining use the old ones.

One way to check this is to show that the only impact of this prejit root noinline classification is to speed up jitting. That is, if you disable the classification, we should produce exactly the same jitted code as before, but more slowly. I can show you how to do this analysis. 

If we get the prejit classification wrong we'll either waste time when jitting looking at methods that can never be inlined (*false negative* -- prejit classffied the method as not inlinable, but the method never actually was inlined), or miss opportunities inlining methods that we prematurely concluded could never be inlined (*false negative*, we marked a method as noinline when prejitting, when in fact it could have been inlined at times). 

In the past I've tried to bias this classification so that we false negatives while keeping false positives still somewhat minimal.

See also #6249.

**Comment by AndyAyersMS** [comment]
>
> I can show you how to do this analysis.

Set up two matching repos with your changes.  Change the inline policy's implementation of `PropagateNeverToRuntime` to the one used by the discretionary policy:

https://github.com/dotnet/runtime/blob/17481fef502ee6aed6f9e8fc76e45bb5863c68b5/src/coreclr/jit/inlinepolicy.cpp#L1947-L1965

Do clean builds in each repo. Then compare codegen (say using PMI, run via separate jit-diff invocations) across some set of methods and verify they're identical.

**Comment by EgorBo** [comment]
@AndyAyersMS so to make sure I understand:
I have a `Main` that calls `Foo`
Let's say the "old" inliner currently gives up on inlining Foo into Main. So the crossgen should basically make two Inline analysis: run the "new" inliner and record its result somewhere, e.g. "inlineable=true". Then use the old inliner for actual inlining - it won't inline `Foo` but at least when we'll be rejitting Main we won't get "noinline" from VM for `Foo` and will use the "new" inliner.

**Comment by AndyAyersMS** [comment]
What I'd suggest is that when we do this bit of analysis:
https://github.com/dotnet/runtime/blob/6474c725025a8b29b4265c4d9485018982ee6b16/src/coreclr/jit/compiler.cpp#L6351-L6412

we use the new more aggressive policy. We want to be optimistic here since we don't know anything about the caller or call site, so if there's any chance the caller or call site info would make this method an attractive inline, we want to keep it inlineable.

But when we do actual inlining analysis, and we're prejitting we use the current policy.

To accomplish this, `InlinePolicy::GetPolicy` would vary which policy it chooses based in part on the `isPrejitRoot` parameter.

**Comment by EgorBo** [comment]
@AndyAyersMS Could you please re-review, I believe I've addressed your feedback.

My heuristics rely on callsite quite a lot - its weight (profile) and which args are constants - I guess we still will mark lots of useful methods as noinline in root-prejit mode? 🙁

**Comment by EgorBo** [comment]
Can we use method's call count as callsite's weight in Prejit-root mode?

**Comment by AndyAyersMS** [comment]
> I guess we still will mark lots of useful methods as noinline in root-prejit mode? 

You may need to bias your benefit computation to "assume the best" when evaluating the prejit root. That is, imagine there's a caller that does all sorts of good things.

There's already an instance of this in the old code -- I'd expect you will need more:
```C++
    // For prejit roots we do not see the call sites. To be suitably optimistic
    // assume that call sites may pass constants.
    else if (m_IsPrejitRoot && ((m_ArgFeedsConstantTest > 0) || (m_ArgFeedsTest > 0)))
    {
        multiplier += 3.0;
        JITDUMP("\nPrejit root candidate has arg that feeds a conditional.  Multiplier increased to %g.", multiplier);
    }
```

If you are too pessimistic you'll block inlining of some prejitted methods that would be good inline candidates. If you're too optimistic you will spend a lot of jit time analyzing methods that can never be inlined. So try and strike the right balance... just enough optimism.

**Comment by EgorBo** [comment]
> There's already an instance of this in the old code -- I'd expect you will need more:

Yeah, I've added a similiar one in my PR:
```
    if (m_IsPrejitRoot && (m_BinaryExprWithCns > 0)) // we assume it could be a foldable expr 
    {
        multiplier += m_BinaryExprWithCns;
    }
```

File: src/coreclr/jit/fgbasic.cpp [hunk 16]
```diff
@@ -1975,7 +1935,6 @@ void Compiler::fgFindJumpTargets(const BYTE* codeAddr, IL_OFFSET codeSize, Fixed
                 if (makeInlineObservations)
                 {
                     pushedStack.PushArrayLen();
-                    handled = true;
```
Comment (AndyAyersMS) [inline src/coreclr/jit/fgbasic.cpp]: Don't you still want this?

File: src/coreclr/jit/jitconfigvalues.h [hunk 17]
```diff
@@ -463,6 +460,7 @@ CONFIG_STRING(JitNoInlineRange, W("JitNoInlineRange"))
 CONFIG_STRING(JitInlineReplayFile, W("JitInlineReplayFile"))
 #endif // defined(DEBUG) || defined(INLINE_DATA)
 
+CONFIG_INTEGER(JitExtendedDefaultPolicyModel, W("JitExtendedDefaultPolicyModel"), 1)
```
Comment (AndyAyersMS) [inline src/coreclr/jit/jitconfigvalues.h:463]:
```suggestion
CONFIG_INTEGER(JitExtendedDefaultPolicy, W("JitExtendedDefaultPolicy"), 1)
```
I was using `Model` as an indicator that this policy was based on machine learning models.

File: src/coreclr/jit/fgbasic.cpp (hunk 12 above)
Comment (EgorBo) [reply src/coreclr/jit/fgbasic.cpp:925]: `PushUnknown` means we didn't find anything interesting for inliner in the previous opcode. I like the idea of making it table driven but in a separate PR if you don't mind. It works fine with the current implementation and doesn't change anything for the `DefaultPolicy` basically (when `preciseScan` is false)

File: src/coreclr/jit/fgbasic.cpp (hunk 11 above)
Comment (EgorBo) [reply src/coreclr/jit/fgbasic.cpp]: Done

File: src/coreclr/jit/inlinepolicy.cpp (hunk 10 above)
Comment (EgorBo) [reply src/coreclr/jit/inlinepolicy.cpp]: Fixed to ignore this limit in `ExtendedDefaultPolicy` - will check perf impact.

File: src/coreclr/jit/jitconfigvalues.h (hunk 9 above)
Comment (EgorBo) [reply src/coreclr/jit/jitconfigvalues.h:389]: Yeah, will test TP impact of 1024.

File: src/coreclr/jit/jitconfigvalues.h (hunk 8 above)
Comment (EgorBo) [reply src/coreclr/jit/jitconfigvalues.h]: Fixed

File: src/coreclr/jit/inlinepolicy.cpp [hunk 18]
```diff
@@ -1656,6 +1248,466 @@ void RandomPolicy::DetermineProfitability(CORINFO_METHOD_INFO* methodInfo)
...
+//    value    - the value being observed
+
+void ExtendedDefaultPolicy::NoteDouble(InlineObservation obs, double value)
+{
+    // So far, CALLSITE_PROFILE_FREQUENCY is the only "double" property.
+    assert(obs == InlineObservation::CALLSITE_PROFILE_FREQUENCY);
+    m_ProfileFrequency = value;
+}
+
+double ExtendedDefaultPolicy::DetermineMultiplier()
```
Comment (AndyAyersMS) [inline src/coreclr/jit/inlinepolicy.cpp:1387]: Add the normal header comment here

File: src/coreclr/jit/inlinepolicy.cpp (hunk 14 above)
Comment (EgorBo) [reply src/coreclr/jit/inlinepolicy.cpp]: Added notes

File: src/coreclr/jit/fgbasic.cpp (hunk 12 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/fgbasic.cpp:926]: Doing it as a follow up is fine.

File: src/coreclr/jit/fgbasic.cpp (hunk 4 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/fgbasic.cpp:1174]: I thought I had suggested this, but we should consider refactoring this method so it's not so large. Likely it would improve jit throughput and make things more understandable.

Consider this as a follow-up activity, since it's best to verify changes like this don't cause diffs.

File: src/coreclr/jit/inlinepolicy.cpp [hunk 19]
```diff
@@ -94,8 +94,16 @@ InlinePolicy* InlinePolicy::GetPolicy(Compiler* compiler, bool isPrejitRoot)
         return new (compiler, CMK_Inlining) ProfilePolicy(compiler, isPrejitRoot);
     }
 
-    // Use the default policy by default
-    return new (compiler, CMK_Inlining) DefaultPolicy(compiler, isPrejitRoot);
+    const bool useExtendedDefaultPolicy = JitConfig.JitExtendedDefaultPolicyModel() != 0;
+
+    if (!useExtendedDefaultPolicy || (!isPrejitRoot && compiler->opts.IsReadyToRun()))
```
Comment (AndyAyersMS) [inline src/coreclr/jit/inlinepolicy.cpp:99]: I find the second clause easier to parse written the other way. Also we should probably use the more general check for prejitting

```suggestion
    if (!useExtendedDefaultPolicy || (compiler->opts.jitFlags->IsSet(JitFlags::JIT_FLAG_PREJIT) && !isPrejitRoot))
```

File: src/coreclr/jit/inlinepolicy.cpp [hunk 20]
```diff
@@ -94,8 +94,16 @@ InlinePolicy* InlinePolicy::GetPolicy(Compiler* compiler, bool isPrejitRoot)
...
+    {
+        // DefaultPolicy is better for AOT in terms of code-size.
+        return new (compiler, CMK_Inlining) DefaultPolicy(compiler, isPrejitRoot);
```
Comment (AndyAyersMS) [inline src/coreclr/jit/inlinepolicy.cpp:102]: CoreRT may well want the CQ benefits from the more aggressive policy, so this may need adjusting.

File: src/coreclr/jit/inlinepolicy.cpp [hunk 21]
```diff
@@ -539,13 +459,13 @@ void DefaultPolicy::NoteBool(InlineObservation obs, bool value)
 
 #if defined(DEBUG) || defined(INLINE_DATA)
 //------------------------------------------------------------------------
-// DumpXml: Dump DefaultPolicy data as XML
+// DumpXml: Dump ExtendedDefaultPolicy data as XML
```
Comment (AndyAyersMS) [inline src/coreclr/jit/inlinepolicy.cpp:462]: Does `DefaultPolicy` no longer override `DumpXml`? Seems like it should, and the extended policy dump should layer on top of it (or something).

**Review by AndyAyersMS — COMMENTED** [review]
Thanks, looks like this is getting close.

**Comment by AndyAyersMS** [comment]
> Can we use method's call count as callsite's weight in Prejit-root mode?

I think this is somewhat risky, as the current static PGO generation (afaik) does not guarantee methods stay in Tier0 forever, so we don't have confidence the PGO counts are the total call counts. 

@jakobbotsch do you know if we ever changed that aspect?

**Comment by jakobbotsch** [comment]
That wasn't changed since the counters may overflow if we let training scenarios stay in tier 0 indefinitely.

**Review by AndyAyersMS — APPROVED** [review]
Latest changes LGTM.

**Comment by EgorBo** [comment]
An example where 3 frames are inlined in a hot path of Json deserializer (makes it 5% faster)
image

**Comment by AndyAyersMS** [comment]
@EgorBo when do you think this will be merged?

**Comment by EgorBo** [comment]
> @EgorBo when do you think this will be merged?

@AndyAyersMS I'm preparing final reports (TE citrine-linux, citrine-windows, YARP) with some notes at the moment, will be ready in 8 hours or so.

**Comment by EgorBo** [comment]
So I guess it's ready, I've updated the description with the most recent numbers collected from TE benchmarks (I'm having problems with collecting the numbers for Windows atm - the jobs I send via crank just hang all the time, but the last numbers for random benchmarks were pretty much the same as on Linux. I'm also trying to collect some numbers for ARM atm. CLI tools don't show any noticeable regressions during startup (e.g. start powershell, process a simple script and exit) - mostly because R2R code was not touched. There are some questionable numbers in "first request" and "P99" (see Results section in the description).

**Comment by jkotas** [comment]
> PR doesn't change inliner for R2R so there are no size regressions

What would be the size regression for R2R if it is enabled? It does not sound right to pessimize R2R like this. Note that some important 1st party teams are running R2R code without tiered compilation. If the size regression is non-acceptable, maybe this should be configurable?

Also, note that it is not unusual to see workloads that are instruction cache bound, and increasing the code size will not help or even hurt them, even though the microbenchmarks show improvements.

**Comment by EgorBo** [comment]
> What would be the size regression for R2R if it is enabled? It does not sound right to pessimize R2R like this. Note that some important 1st party teams are running R2R code without tiered compilation. If the size regression is non-acceptable, maybe this should be configurable?

Yes, it's configurable, customers can re-AOT CoreLib by using `DOTNET_JitExtendedDefaultPolicyPrejit=1` to use the new one.

Currently it adds around +1 Mb: 9.8Mb -> 10.8Mb (+10%) and depends on:
1) Max IL size (512 bytes of IL, used to be 100)
2) Max BB count (unlimited, used to be 5)
3) We currently apply quite some big multiplier for methods with profile (in case if there are also other profitable observations).

So that +1Mb doesn't bring much value for customers who use Tiered JIT. However, @AndyAyersMS, correct me if I'm wrong, but when the default inliner prejits code it also asks VM to save "noinline" for failed attempts, not only in the PrejitRoot mode (as I hoped) so it limits opportunities for the new one during re-jitting. 

I've just launched a couple of TE benchmarks to check ExtendedDefaultPolicy for R2R + TieredCompilation=0.

**Comment by jkotas** [comment]
> it adds around +1 Mb: 9.8Mb -> 10.8Mb (+10%)

It means that the actual code size regressed by about 15% (the R2R binary has more that just the code). It feels like a lot.

Have you looked at asm diffs and examined several different methods with the worst size regressions?

**Comment by AndyAyersMS** [comment]
> when the default inliner prejits code it also asks VM to save "noinline" for failed attempts, not only in the PrejitRoot mode

My impression was that  the "non-prejit-root" inline failures the JIT reports to the VM should only happen for methods that can truly never be inlined -- methods that are unprofitable to inline with the current policy shouldn't be marked this way, since some subsequent policy may be more aggressive.

eg
```C++
        if (!shouldInline)
        {
            // Fail the inline
            if (m_IsPrejitRoot)
            {
                SetNever(InlineObservation::CALLEE_NOT_PROFITABLE_INLINE);
            }
            else
            {
                SetFailure(InlineObservation::CALLSITE_NOT_PROFITABLE_INLINE);
            }
        }
```
Unprofitable, non-prejit root is a CALLER NEVER failure.

Unprofitable otherwise is a simple CALLSITE failure.

You should double-check that this is working as expected.

**Comment by EgorBo** [comment]
@jkotas I managed to reduce the R2R size when ExtDefaultPolicy is turned on for it (10.81 Mb -> 10.21 Mb where the default one was 9.63 Mb) , some observations:
1) I don't give boost for methods with "throw" any more <-- "throw" usually comes with a big size overhead (but doesn't regress performance since we put it to the cold section of methods always). Some benchmarks slightly regressed because of that (many methods have quick prechecks e.g. `if (value == null) throw`), but I hope we'll just convert those "throw" in hot paths to throw helpers or eventually will fix with a partial compilation.

2) Most of the size overhead comes from 3 sources:
    * if I remove profile-based multiplier: 10.21 Mb -> 10.04 Mb
    * if I limit BB to 5 (just like it was in DefaultPolicy): 10.21 Mb -> 10.02 Mb
    * if I limit BB to 5 and remove profile-based multiplier: 10.21 Mb -> 9.89
    * The rest mostly comes from "foldablebranch", "struct is passed/returned by value", "ldfld over struct arg" and "binary expr against const".

Here is an IL size and profile histograms for callsites eligible for inlining:
image
So it's around 6500 callsites with zero weight and 8500 with 1.0 (hot) one.

I'm still analyzing the diff results (a lot of diffs in Task-related sources, many MoveNext are inlined in various iterators
```
Top file regressions (bytes):
      284095 : System.Private.CoreLib.dasm (7.85% of base)

2273 total methods with Code Size differences (296 improved, 1977 regressed), 20493 unchanged.
```
(PMI mode)

What value for the size regression can be acceptable?

PS: a quote from [An Optimization-Driven Incremental Inline Substitution Algorithm for Just-in-Time Compilers](http://aleksandar-prokopec.com/resources/docs/prio-inliner-final.pdf)
```
As argued before [80, 64], and as showed here, Graal’s optimizations are already very good. A 10%
performance increase is regarded as a significant improvement, while a code size increase of up 
to 100% is typically tolerable (for example, GCC inliners report 44% binary size growth
[35], and ≈ 100% increase is acceptable in some WCET-aware optimizations [42]).
```

**Comment by jkotas** [comment]
Can you share some examples of asm diffs for methods with largest growth? Are they all good?

**Comment by EgorBo** [comment]
> Can you share some examples of asm diffs for methods with largest growth? Are they all good?

Sure, will share some in a few hours

**Comment by jkotas** [comment]
Also, do you have results for Roslyn compilation benchmark with this change?

**Comment by EgorBo** [comment]
> Also, do you have results for Roslyn compilation benchmark with this change?

I have two here - an app that compiles a runtime test into a dll:
```csharp

private static string TestCs =
    File.ReadAllText(@"C:\prj\runtime-base\src\tests\JIT\opt\Loops\SearchLoopTail.cs");

[Benchmark]
public void Roslyn()
{
    var parseOptions = new CSharpParseOptions(kind: SourceCodeKind.Regular, documentationMode: DocumentationMode.None);
    var options = new CSharpCompilationOptions(outputKind: OutputKind.DynamicallyLinkedLibrary, concurrentBuild: false);
    var tree = SyntaxFactory.ParseSyntaxTree(TestCs, parseOptions);
    var reference = MetadataReference.CreateFromFile(
        @"C:\prj\runtime\artifacts\bin\coreclr\windows.x64.Release\System.Private.CoreLib.dll");
    var comp = CSharpCompilation.Create("assemblyName", 
        new SyntaxTree[] { tree }, references: new MetadataReference[] { reference }, options: options);

    var result = comp.Emit(@"test.dll");
    File.Delete("test.dll");
}
```
and a Roslyn analyzer that uses a custom `CSharpSyntaxRewriter` for some folder with C# files.
Both more or less unchanged, but when I change `DOTNET_JitExtDefaultPolicyMaxBB=7` (was `5`) and `DOTNET_JitExtDefaultPolicyProfBB=4` (was `4`) I start to see 3-6% improvements.

**Comment by EgorBo** [comment]
Main's corelib is 9.63 Mb (R2R'd)
`ExtendedDefaultPolicy` without taking PGO into account: 9.83 Mb
`ExtendedDefaultPolicy` with PGO `JitExtDefaultPolicyProfTrust=10`: 10.10 Mb
`ExtendedDefaultPolicy` with PGO `JitExtDefaultPolicyProfTrust=0`: 10.17 Mb

`JitExtDefaultPolicyProfTrust=10` means we're fine that inliner won't inline anything in cold blocks (call-sites with profiles)
`JitExtDefaultPolicyProfTrust=0` means it doesn't affect the BenefitMultiplier anyhow for cold blocks (so we still can inline calls in them).

Here is the asm diff without taking PGO into account: 

Improvements
Most of the size improvements come from "don't inline anything in BBJ_THROW blocks", e.g.:
```

**Comment by EgorBo** [comment]
Main's corelib is 9.63 Mb (R2R'd)

- `ExtendedDefaultPolicy` without taking PGO into account: 9.83 Mb
- `ExtendedDefaultPolicy` with PGO `JitExtDefaultPolicyProfTrust=10`: 10.10 Mb
- `ExtendedDefaultPolicy` with PGO `JitExtDefaultPolicyProfTrust=0`: 10.17 Mb

`JitExtDefaultPolicyProfTrust=10` means we're fine that inliner won't inline anything in cold blocks (call-sites with real profiles)
`JitExtDefaultPolicyProfTrust=0` means it doesn't affect the BenefitMultiplier anyhow for cold blocks (so we still can inline calls in them). By default, I use `5` as a balance.

Here is the jit-diff (PMI mode) without taking PGO into account: https://gist.github.com/EgorBo/8e44063324ec21ba29c636a79d7e871c

### Improvements
Most of the size improvements come from "don't inline anything in BBJ_THROW blocks", e.g.:
```csharp
if (x == null)
    throw new ArgumentNullException(SR.InvalidArgument); // get_InvalidArgument() is inlined here
```
both `ArgumentNullException.ctor` and `get_InvalidArgument` aren't inlined anymore. A good example is  `LowLevelLifoSemaphore:ReleaseCore(int):this` diff: https://www.diffchecker.com/Wlfl2Lde
***
There are some interesting examples where inlining leads to smaller size, e.g. 
```csharp
static GCHandle Test(object? value) => GCHandle.Alloc(value);
```
Diff: https://www.diffchecker.com/kCYnyUge
^ Inliner managed to detect foldable branches in the `GCHandle`'s constructor and inlined it, see [here](https://github.com/dotnet/runtime/blob/fc4a42746d9cf65ad3db4074207069ab9c168bc9/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/GCHandle.cs#L62) and its [ctor](https://github.com/dotnet/runtime/blob/fc4a42746d9cf65ad3db4074207069ab9c168bc9/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/GCHandle.cs#L32-L54).
***
Another example - it's now able to inline `string.Equals` when we compare literals, e.g. `if (strArg.Length == 0)` is recognized as a foldable branch due to the fact we can now recognize 'get_Length' call, example:
```csharp
bool foo(string str) => str == "hello";

bool test() => foo("hello");
```
Diff for `test`: https://www.diffchecker.com/vPVxpDl1
***
There are some diffs due to PMI trying to instantiate `Vector<T>` with unsupported T (e.g. char) and inliner helpes here too, e.g. https://www.diffchecker.com/ElRZpnyh
***
`GC:AllocateArray(int,bool):ref` is smaller after inlining: https://www.diffchecker.com/AZKH3aiG
***
Same for `ASCIIUtility:NarrowUtf16ToAscii(long,long,long):long`: https://www.diffchecker.com/yS7ttpfS
***
There are cases where ExtendedDefaultPolicy doesn't inline what was inlined by the previous inliner - I tried to avoid it, but there were cases where I'm not sure we should inline, e.g this call https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Directory.cs#L63 is inlined despite being quite complex: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/IO/FileSystem.Attributes.Windows.cs#L25-L35
Old inliner detected here "arg feeds const test" and added a big multiplier. It did so because IL scan was not quite accurate and had many false positives. However, this method will still be inlined with PGO (and I am sure we have one for this in the static profile we ship). **UPD** I slightly added some boost in .

## Size regressions
These are the cases where inlining increases the size but hopefully for better performance.
```
        2846 (357.54% of base) : System.Private.CoreLib.dasm - Array:Sort(Array,Array,int,int,IComparer)
```
InlineTree diff: https://www.diffchecker.com/nEAcbTWc It decided to inline `ArraySortHelper.IntrospectiveSort` here (e.g. because of "non-generic code calls generic").
***
```
1483 (131.71% of base) : System.Private.CoreLib.dasm - Guid:TryFormat(Span`1,byref,ReadOnlySpan`1):bool:this
```
Diff https://www.diffchecker.com/KgWTWBug - it inlined all `HexToChars` calls.
***
```
        1248 (56.12% of base) : System.Private.CoreLib.dasm - Task`1:ContinueWith(Func`2,TaskScheduler,CancellationToken,int):Task`1:this (8 methods)
```
Diff https://www.diffchecker.com/Y26QhTNV, explanation: [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwFgAoAAQAYACUgRgFYBuEk0gZmoCZKBhSgbxKUhlQcLbUk3CADsM2aQFcAhnJkB5AA6rpAZ0oBZGgApSkmXMUrs6rdd2UIASn7Niw95QD0nygCUIOrgAntKUACYQMDrSAOQYlABmELhhlBgAFlEwabDZCbhKAOY6oh5ePjoQaZmUAJLSuPIwUJQ6MFGUAERJKUrAuNkwCBqwOjp2Op2lHt51lNLtqRhVCdgIdQ1NLcuUsJCF0tgAXtndyWF9A5RDI1HjMpMODUHT7rMA7pmhkLoYcEpQQqUAHZeQAN2SYJgYQAdK8xAB2ByUfAiNxlDFCUxSWTyZTaTTaHQwgByEAwamk3CU0jAMAGqSI6MxZWx5jxVhsRNJ5MpADElApcBhoSj4SyJDiLPi7ISJjyKdJfDSACoQKQAWw0A20TGZlAAvtNjfrxGzcZYCbYHgYOCYzBaZVyJg5nAJiOLyn4AsFQhEOj0lpk2jl2okCsVPaQkZ7MebpZzpHKHgrKdTafTRUyJayHQmrdyyYqBUKRYzYxj4xyC/Ki5TldI1ZrtTBtCiHHr3EbiAagA==)
***
Overall I don't see anything terribly wrong so far (e.g. terrible spills because of too-many-locals), I spent the whole week on fixing the regressions and now it's more or less fine.
Performance benefits aren't as good as they used to be with a way more aggressive inliner but I'm going to investigate what exactly led to such improvements and send separate PRs. At least currently I don't see any impact on "time to first request", I'll publish the first results once my [script](https://gist.github.com/EgorBo/a1ab453bf41a5369aa54b4c4fba6bea5) finishes.

@jkotas you can pick any method from the jit-diff and I'll explain with the diffs what exactly happened.

**Comment by jkotas** [comment]
I see lines like `[10 IL=0025 TR=000142 06005F3B] [profitable inline] System.Diagnostics.Debug:Assert(bool)` in https://www.diffchecker.com/nEAcbTWc. Are you doing the analysis on debug CoreLib? That does not sound right.

**Comment by EgorBo** [comment]
> I see lines like `[10 IL=0025 TR=000142 06005F3B] [profitable inline] System.Diagnostics.Debug:Assert(bool)` in https://www.diffchecker.com/nEAcbTWc. Are you doing the analysis on debug CoreLib? That does not sound right.

The jit-diff was collected on a release version of CoreLib so it should be fine. I just used my [Disasmo](https://github.com/EgorBo/Disasmo/) add-in to collect the inliner dump in the IDE for the `Array.Sort` method and totally forgot that it uses Checked.

**Comment by jkotas** [comment]
Yes, this looks more reasonable that the original size regressions. 

With relatively large internal methods fully inlined (like your `Array:Sort` or `MoveNext` examples), we should tech crossgen2 to not compile these internal methods separately. Their body will never be used since they are fully inlined.

**Comment by EgorBo** [comment]
> Yes, this looks more reasonable that the original size regressions.
> 
> With relatively large internal methods fully inlined (like your `Array:Sort` or `MoveNext` examples), we should tech crossgen2 to not compile these internal methods separately. Their body will never be used since they are fully inlined.

Good idea, but I thought it already worked like that 🙂.


Unrelatated: I've just built a histogram on amount of locals in callers during inlining (crossgen2 + ExtDefaultPolicy + Release + PGO data):
image

So doesn't look like we inline too much often, but just in case I added a check to decrease the benefit mutliplier if we have to many locals already (say, 1/4 of MaxLocalsToTrack). Currently, MaxLocalsToTrack is 1024, and the biggest amount of locals after inlining is 463.

**Comment by EgorBo** [comment]
The latest run of TE benchmarks on aspnet-perf-linux (citrine was busy): 
image

**Comment by EgorBo** [comment]
Citrine-Linux results (the difference is smaller):
image

File: src/coreclr/jit/jitconfigvalues.h [hunk 22]
```diff
@@ -454,6 +457,14 @@ CONFIG_STRING(JitNoInlineRange, W("JitNoInlineRange"))
 CONFIG_STRING(JitInlineReplayFile, W("JitInlineReplayFile"))
 #endif // defined(DEBUG) || defined(INLINE_DATA)
 
+CONFIG_INTEGER(JitExtDefaultPolicy, W("JitExtDefaultPolicy"), 1)
+CONFIG_INTEGER(JitExtDefaultPolicyPrejit, W("JitExtDefaultPolicyPrejit"), 0)
```
Comment (jkotas) [inline src/coreclr/jit/jitconfigvalues.h:461]: Instead of attaching the policy to prejit flag, would it be better to attach the polity to the existing `CORJIT_FLAG_SPEED_OPT` and `CORJIT_FLAG_SIZE_OPT` options?

I am not fan on attaching the optimization policies to the prejit flag.

Comment (EgorBo) [reply src/coreclr/jit/jitconfigvalues.h:461]: hm.. for some reason when I invoke crossgen2 with --optimize-time (or --Ot) - CORJIT_FLAG_SPEED_OPT  is still not set in jit 🤔

Comment (EgorBo) [reply src/coreclr/jit/jitconfigvalues.h]: I was wrong, it's set. I verified that -O (blended) and --Os (opt for size) both use DefaultPolicy and --Ot (opt for speed) uses ExtendedDefaultPolicy in crossgen2.

**Comment by EgorBo** [comment]
@jkotas Any objections to merging this?

**Comment by EgorBo** [comment]
Windows TE aspent-citrine-win results (less stable as expected):
image

**Comment by jkotas** [comment]
No objections. I think that the defaults for R2R can probably can use more tuning, but that can be done separately.

@mangod9 @dotnet/crossgen-contrib The optimization for time (`-Ot` crossgen2 option - not enabled by default) will have very material impact after this change. We should make sure to turn it on for workloads that use R2R with tiered JIT compilation disabled.

**Comment by mangod9** [comment]
Thanks, assume these the gains would be most pronounced with R2R composite mode?

**Comment by jkotas** [comment]
> assume these the gains would be most pronounced with R2R composite mode?

It depends. I would expect it to impact both composite and non-composite cases.

**Comment by EgorBo** [comment]
It can be merged then. This PR mostly unlocks dynamic PGO's potential which we won't use by default in .NET 6, but users, who care less about slower start, can set the following variables for "FullPGO + Aggressive Inliner" mode:
```bash
DOTNET_TieredPGO=1                        # enable PGO instrumentation in tier0
DOTNET_TC_QuickJitForLoops=1              # don't bypass tier0 for methods with loops
DOTNET_ReadyToRun=0                       # don't use prejitted code and collect a better profile for everything
DOTNET_JitExtDefaultPolicyMaxIL=0x200     # allow inlining for large methods
DOTNET_JitExtDefaultPolicyMaxBB=15        # same here
DOTNET_JitExtDefaultPolicyProfScale=0x40  # try harder inlining hot methods
```
Here are the results for TE benchmarks on citrine-linux for `Main-default` (Static PGO is included) vs `ThisPR + FullPGO + aggressive inliner` ^:
image

This PR also improves the default mode, but only by a few %s in general. And, just a reminder: if we use/benchmark something with `DOTNET_TieredCompilation=0` we won't see any benefits since we use the old inlining policy for AOT and will never re-jit it for the BCL (don't expect any improvements for `dotnet/performance` micro-benchmarks if we use TC=0 there).

What is not done, but nice to have:
1) It doesn't fix https://github.com/dotnet/runtime/issues/41692, https://github.com/dotnet/runtime/issues/43761 and https://github.com/dotnet/runtime/issues/51587 since it doesn't touch "EstimateTime" yet.
2) It should ignore methods with insufficient samples (currently if callsite's profile >= callsite's fgFirstBb->weight -- we consider it as hot) e.g. static constructors, etc
3) Re-vise "report noinline to vm" logic, sometimes it might bake "noinline" for methods which are good candidates for inlining within specific call-sites (e.g. with const args).
4) "resolve call token" logic currently doesn't work for methods with loops.

If something goes wrong we can easily switch to the previous (more conservative and PGO-independent) policy.

**Comment by EgorBo** [comment]
The example from https://github.com/dotnet/runtime/issues/33349 is my favorite one:
```csharp
private static bool Format(Span<byte> span, int value)
{
    return Utf8Formatter.TryFormat(value, span, out _, new StandardFormat('D', 2));
}
```
Codegen in this PR:
```asm
; Method Program:Format(System.Span`1[Byte],int):bool
G_M58631_IG01:
       sub      rsp, 88
       vxorps   xmm4, xmm4
       vmovdqa  xmmword ptr [rsp+30H], xmm4
       vmovdqa  xmmword ptr [rsp+40H], xmm4
       xor      eax, eax
       mov      qword ptr [rsp+50H], rax
						;; bbWeight=1    PerfScore 3.83

G_M58631_IG02:
       mov      r8, bword ptr [rcx]
       mov      ecx, dword ptr [rcx+8]
       movsxd   rdx, edx
       jmp      SHORT G_M58631_IG04
						;; bbWeight=1    PerfScore 6.25

G_M58631_IG03:
       add      rsp, 88
       ret      
						;; bbWeight=1    PerfScore 1.25

G_M58631_IG04:
       xor      r9d, r9d
       test     rdx, rdx
       jge      SHORT G_M58631_IG05
       mov      r9d, 1
       neg      rdx
						;; bbWeight=0.50 PerfScore 1.00

G_M58631_IG05:
       mov      bword ptr [rsp+30H], r8
       mov      dword ptr [rsp+38H], ecx
       lea      rcx, [rsp+50H]
       mov      qword ptr [rsp+20H], rcx
       mov      rcx, rdx
       mov      edx, 2
       lea      r8, bword ptr [rsp+30H]
       call     System.Buffers.Text.Utf8Formatter:TryFormatUInt64D(long,ubyte,System.Span`1[Byte],bool,byref):bool
       movzx    rax, al
       jmp      SHORT G_M58631_IG03
						;; bbWeight=0.50 PerfScore 3.88
; Total bytes of code: 102
```
Codegen in Main:
```asm
; Method Program:Format(System.Span`1[Byte],int):bool
G_M58631_IG01:
       push     rdi
       push     rsi
       push     rbp
       push     rbx
       sub      rsp, 88
       vxorps   xmm4, xmm4
       vmovdqa  xmmword ptr [rsp+30H], xmm4
       vmovdqa  xmmword ptr [rsp+40H], xmm4
       xor      eax, eax
       mov      qword ptr [rsp+50H], rax
       mov      rsi, rcx
       mov      edi, edx
						;; bbWeight=1    PerfScore 8.33

G_M58631_IG02:
       mov      word  ptr [rsp+48H], 0
       lea      rcx, bword ptr [rsp+48H]
       mov      edx, 68
       mov      r8d, 2
       call     System.Buffers.StandardFormat:.ctor(ushort,ubyte):this
       mov      rbx, bword ptr [rsi]
       mov      esi, dword ptr [rsi+8]
       movzx    rax, byte  ptr [rsp+48H]
       movzx    rdx, byte  ptr [rsp+49H]
       movsxd   rdi, edi
       mov      byte  ptr [rsp+40H], al
       mov      byte  ptr [rsp+41H], dl
       cmp      byte  ptr [rsp+40H], 0
       jne      G_M58631_IG20
						;; bbWeight=1    PerfScore 13.25

G_M58631_IG03:
       cmp      byte  ptr [rsp+41H], 0
       sete     al
       movzx    rax, al
       test     eax, eax
       je       G_M58631_IG20
       cmp      rdi, 10
       jae      SHORT G_M58631_IG06
       test     esi, esi
       jne      SHORT G_M58631_IG04
       xor      eax, eax
       mov      dword ptr [rsp+50H], eax
       jmp      SHORT G_M58631_IG05
						;; bbWeight=0.50 PerfScore 4.62

G_M58631_IG04:
       add      edi, 48
       mov      byte  ptr [rbx], dil
       mov      dword ptr [rsp+50H], 1
       mov      eax, 1
						;; bbWeight=0.50 PerfScore 1.25

G_M58631_IG05:
       jmp      G_M58631_IG19
						;; bbWeight=0.50 PerfScore 1.00

G_M58631_IG06:
       test     rdi, rdi
       jge      G_M58631_IG18
       neg      rdi
       mov      ebp, 1
       cmp      rdi, 0xD1FFAB1E
       jb       SHORT G_M58631_IG08
       mov      rax, 0xD1FFAB1E
       cmp      rdi, rax
       jb       SHORT G_M58631_IG07
       mov      rdx, 0xD1FFAB1E
       mov      rax, rdi
       mul      rdx:rax, rdx
       shr      rdx, 42
       mov      ecx, edx
       mov      ebp, 15
       jmp      SHORT G_M58631_IG09
						;; bbWeight=0.50 PerfScore 5.50

G_M58631_IG07:
       mov      rdx, 0xD1FFAB1E
       mov      rax, rdi
       mul      rdx:rax, rdx
       shr      rdx, 23
       mov      ecx, edx
       mov      ebp, 8
       jmp      SHORT G_M58631_IG09
						;; bbWeight=0.50 PerfScore 3.25

G_M58631_IG08:
       mov      ecx, edi
						;; bbWeight=0.50 PerfScore 0.12

G_M58631_IG09:
       cmp      ecx, 10
       jb       SHORT G_M58631_IG16
       cmp      ecx, 100
       jae      SHORT G_M58631_IG10
       inc      ebp
       jmp      SHORT G_M58631_IG16
						;; bbWeight=0.50 PerfScore 2.38

G_M58631_IG10:
       cmp      ecx, 0x3E8
       jae      SHORT G_M58631_IG11
       add      ebp, 2
       jmp      SHORT G_M58631_IG16
						;; bbWeight=0.50 PerfScore 1.75

G_M58631_IG11:
       cmp      ecx, 0x2710
       jae      SHORT G_M58631_IG12
       add      ebp, 3
       jmp      SHORT G_M58631_IG16
						;; bbWeight=0.50 PerfScore 1.75

G_M58631_IG12:
       cmp      ecx, 0x186A0
       jae      SHORT G_M58631_IG13
       add      ebp, 4
       jmp      SHORT G_M58631_IG16
						;; bbWeight=0.50 PerfScore 1.75

G_M58631_IG13:
       cmp      ecx, 0xD1FFAB1E
       jae      SHORT G_M58631_IG14
       add      ebp, 5
       jmp      SHORT G_M58631_IG16
						;; bbWeight=0.50 PerfScore 1.75

G_M58631_IG14:
       cmp      ecx, 0xD1FFAB1E
       setb     cl
       movzx    rcx, cl
       mov      rdx, 0xD1FFAB1E
       mov      rdx, gword ptr [rdx]
       test     ecx, ecx
       jne      SHORT G_M58631_IG15
       mov      rcx, rdx
       call     System.Diagnostics.Debug:Fail(System.String,System.String)
						;; bbWeight=0.50 PerfScore 3.12

G_M58631_IG15:
       add      ebp, 6
						;; bbWeight=0.50 PerfScore 0.12

G_M58631_IG16:
       cmp      ebp, esi
       jl       SHORT G_M58631_IG17
       xor      ecx, ecx
       mov      dword ptr [rsp+50H], ecx
       xor      eax, eax
       jmp      SHORT G_M58631_IG19
						;; bbWeight=0.50 PerfScore 2.38

G_M58631_IG17:
       test     esi, esi
       je       G_M58631_IG33
       mov      byte  ptr [rbx], 45
       lea      ecx, [rbp+1]
       mov      dword ptr [rsp+50H], ecx
       mov      ecx, ebp
       inc      rcx
       mov      eax, esi
       cmp      rcx, rax
       ja       G_M58631_IG31
       mov      ecx, ebp
       not      ecx
       shr      ecx, 31
       call     System.Diagnostics.Debug:Assert(bool)
       inc      rbx
       mov      bword ptr [rsp+30H], rbx
       mov      dword ptr [rsp+38H], ebp
       mov      rcx, rdi
       lea      rdx, bword ptr [rsp+30H]
       call     System.Buffers.Text.FormattingHelpers:WriteDigits(long,System.Span`1[Byte])
       mov      eax, 1
       jmp      SHORT G_M58631_IG19
						;; bbWeight=0.50 PerfScore 7.00

G_M58631_IG18:
       mov      rcx, rdi
       mov      bword ptr [rsp+30H], rbx
       mov      dword ptr [rsp+38H], esi
       lea      rdx, bword ptr [rsp+30H]
       lea      r8, [rsp+50H]
       call     System.Buffers.Text.Utf8Formatter:TryFormatUInt64MultipleDigits(long,System.Span`1[Byte],byref):bool
       movzx    rax, al
						;; bbWeight=0.50 PerfScore 2.25

G_M58631_IG19:
       jmp      SHORT G_M58631_IG22
						;; bbWeight=0.50 PerfScore 1.00

G_M58631_IG20:
       mov      ecx, dword ptr [rsp+40H]
       movzx    rbp, cl
       cmp      ebp, 88
       ja       G_M58631_IG24
       cmp      ebp, 71
       ja       SHORT G_M58631_IG23
       cmp      ebp, 68
       je       G_M58631_IG26
       cmp      ebp, 71
       jne      G_M58631_IG30
						;; bbWeight=0.50 PerfScore 3.12

G_M58631_IG21:
       lea      rcx, bword ptr [rsp+40H]
       call     System.Buffers.StandardFormat:get_HasPrecision():bool:this
       test     eax, eax
       jne      G_M58631_IG32
       mov      rcx, rdi
       mov      edx, dword ptr [rsp+41H]
       movzx    rdx, dl
       mov      bword ptr [rsp+30H], rbx
       mov      dword ptr [rsp+38H], esi
       lea      r8, bword ptr [rsp+30H]
       lea      r9, [rsp+50H]
       call     System.Buffers.Text.Utf8Formatter:TryFormatInt64D(long,ubyte,System.Span`1[Byte],byref):bool
       movzx    rax, al
						;; bbWeight=0.50 PerfScore 4.25

G_M58631_IG22:
       add      rsp, 88
       pop      rbx
       pop      rbp
       pop      rsi
       pop      rdi
       ret      
						;; bbWeight=1    PerfScore 3.25

G_M58631_IG23:
       cmp      ebp, 78
       je       G_M58631_IG28
       cmp      ebp, 88
       jne      G_M58631_IG30
       mov      ecx, 0xD1FFAB1E
       and      rcx, rdi
       mov      edx, dword ptr [rsp+41H]
       movzx    rdx, dl
       mov      bword ptr [rsp+30H], rbx
       mov      dword ptr [rsp+38H], esi
       lea      r9, [rsp+50H]
       mov      qword ptr [rsp+20H], r9
       lea      r9, bword ptr [rsp+30H]
       xor      r8d, r8d
       call     System.Buffers.Text.Utf8Formatter:TryFormatUInt64X(long,ubyte,bool,System.Span`1[Byte],byref):bool
       jmp      SHORT G_M58631_IG22
						;; bbWeight=0.50 PerfScore 5.75

G_M58631_IG24:
       cmp      ebp, 103
       ja       SHORT G_M58631_IG25
       cmp      ebp, 100
       je       SHORT G_M58631_IG26
       cmp      ebp, 103
       jne      G_M58631_IG30
       jmp      G_M58631_IG21
						;; bbWeight=0.50 PerfScore 2.88

G_M58631_IG25:
       cmp      ebp, 110
       je       G_M58631_IG28
       cmp      ebp, 120
       jne      G_M58631_IG30
       mov      ecx, 0xD1FFAB1E
       and      rcx, rdi
       mov      edx, dword ptr [rsp+41H]
       movzx    rdx, dl
       mov      bword ptr [rsp+30H], rbx
       mov      dword ptr [rsp+38H], esi
       lea      r9, [rsp+50H]
       mov      qword ptr [rsp+20H], r9
       lea      r9, bword ptr [rsp+30H]
       mov      r8d, 1
       call     System.Buffers.Text.Utf8Formatter:TryFormatUInt64X(long,ubyte,bool,System.Span`1[Byte],byref):bool
       jmp      G_M58631_IG22
						;; bbWeight=0.50 PerfScore 5.75

G_M58631_IG26:
       mov      rcx, rdi
       mov      edx, dword ptr [rsp+41H]
       movzx    rdx, dl
       mov      r8, rbx
       mov      r9d, esi
       xor      eax, eax
       test     rcx, rcx
       jge      SHORT G_M58631_IG27
       mov      eax, 1
       neg      rcx
						;; bbWeight=0.50 PerfScore 2.00

G_M58631_IG27:
       mov      bword ptr [rsp+30H], r8
       mov      dword ptr [rsp+38H], r9d
       lea      r8, [rsp+50H]
       mov      qword ptr [rsp+20H], r8
       lea      r8, bword ptr [rsp+30H]
       mov      r9d, eax
       call     System.Buffers.Text.Utf8Formatter:TryFormatUInt64D(long,ubyte,System.Span`1[Byte],bool,byref):bool
       movzx    rax, al
       jmp      G_M58631_IG22
						;; bbWeight=0.50 PerfScore 3.75

G_M58631_IG28:
       mov      rcx, rdi
       mov      edx, dword ptr [rsp+41H]
       movzx    rdx, dl
       mov      r8, rbx
       mov      r9d, esi
       xor      eax, eax
       test     rcx, rcx
       jge      SHORT G_M58631_IG29
       mov      eax, 1
       neg      rcx
						;; bbWeight=0.50 PerfScore 2.00

G_M58631_IG29:
       mov      bword ptr [rsp+30H], r8
       mov      dword ptr [rsp+38H], r9d
       lea      r8, [rsp+50H]
       mov      qword ptr [rsp+20H], r8
       lea      r8, bword ptr [rsp+30H]
       mov      r9d, eax
       call     System.Buffers.Text.Utf8Formatter:TryFormatUInt64N(long,ubyte,System.Span`1[Byte],bool,byref):bool
       movzx    rax, al
       jmp      G_M58631_IG22
						;; bbWeight=0.50 PerfScore 3.75

G_M58631_IG30:
       xor      eax, eax
       mov      dword ptr [rsp+50H], eax
       call     System.ThrowHelper:ThrowFormatException_BadFormatSpecifier()
       int3     
						;; bbWeight=0    PerfScore 0.00

G_M58631_IG31:
       call     System.ThrowHelper:ThrowArgumentOutOfRangeException()
       int3     
						;; bbWeight=0    PerfScore 0.00

G_M58631_IG32:
       mov      rcx, 0xD1FFAB1E
       call     CORINFO_HELP_NEWSFAST
       mov      rsi, rax
       call     System.SR:get_Argument_GWithPrecisionNotSupported():System.String
       mov      rdx, rax
       mov      rcx, rsi
       call     System.NotSupportedException:.ctor(System.String):this
       mov      rcx, rsi
       call     CORINFO_HELP_THROW
       int3     
						;; bbWeight=0    PerfScore 0.00

G_M58631_IG33:
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
						;; bbWeight=0    PerfScore 0.00
; Total bytes of code: 973
```
diffchecker: https://www.diffchecker.com/WFVcKhJm

**Comment by EgorBo** [comment]
`CoreCLR Pri0 Runtime Tests Run windows arm64 checked` keeps getting timeouts (200 minutes)
