### PR TITLE
[Wasm RyuJIT] Block Stores pt. 2

### LINKED ISSUE #124903: [Wasm RyuJIT] Local field/var stores are broken
```csharp
    [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
    static void manipulateLocal (double arg) {
        double d = 17;
        d += arg;
    }
```

```
[CompileError: WebAssembly.compile(): Compiling function #3 failed: not enough arguments on the stack for f64.store (need 2, got 1) @+660]
```

```wasm
#3 wasm_test_Program__manipulateLocal ( i32, f64, i32 ) -> none (49 byte(s))

0630 2000       get_local i32 arg0
0632 4114       i32_const 0x00000014 20
0634 6B         i32_sub
0635 2100       set_local i32 arg0
0637 2000       get_local i32 arg0
0639 2001       get_local f64 arg1
0641 39000C     f64_store +12
0644 2000       get_local i32 arg0
0646 2002       get_local i32 arg2
0648 360008     i32_store +8
0651 440000000000 ...
003140          f64_const 0x4031000000000000 17
0660 390000     f64_store +0
0663 2000       get_local i32 arg0
0665 2B0000     f64_load +0
0668 2000       get_local i32 arg0
0670 2B000C     f64_load +12
0673 A0         f64_add
0674 390000     f64_store +0
0677 0B         end
```

### PR DESCRIPTION
**Pull request by kg**
* Implement genCodeForCpObj
* Fix two NIY scenarios in the stackifier
* Fix generated stores not being lowered after RewriteLocalStackStore
* Implement isContainableMemoryOp
* Expand and add comments to ease development

This is sufficient to compile the following to valid WASM (It crashes when attempting to call the write barrier helper):
```csharp
    [StructLayout(LayoutKind.Explicit)]
    public struct S2 {
        [FieldOffset(0)]
        public string A;
        [FieldOffset(8)]
        public int b;
        [FieldOffset(16)]
        public string C;
        [FieldOffset(24)]
        public int d;
    }

    [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
    static unsafe void copyStructWithRefs (ref S2 a, ref S2 b) {
        a = b;
    }
```

And the following just plain works, since copies to the stack don't need a write barrier:
```csharp
    [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
    static unsafe void loadStructWithRefs (ref S2 src) {
        S2 local = src;
    }
```

The following now works thanks to implementing isContainableMemoryOp and fixing a related bug:
```csharp
    [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
    static unsafe void fillStructFromLocal (ref S2 dest) {
        S2 local = default;
        local.b = 37;
        dest = local;
    }
```

Fixes #124903

### CODE REVIEW

File: src/coreclr/jit/lowerwasm.cpp [hunk 1]
```diff
@@ -512,6 +522,60 @@ void Lowering::AfterLowerBlock()
...
+
+                        unsigned lclNum = nodeUse.ReplaceWithLclVar(m_lower->m_compiler);
+                        GenTree* newNode = nodeUse.Def();
+                        JITDUMP("Stackifier replaced node [%06u] with lcl var %u\n", Compiler::dspTreeID(node), lclNum);
+                        m_lower->BlockRange().Remove(newNode);
+                        m_lower->BlockRange().InsertAfter(prev, newNode);
+                        JITDUMP("Stackifier moved new node [%06u] after [%06u]\n", Compiler::dspTreeID(newNode),
+                    Compiler::dspTreeID(prev)); break;
+                    }
+                    */
```
[the remark this answers is not in the document]
Comment (kg) [reply src/coreclr/jit/lowerwasm.cpp]: This is here because I'm not sure whether we should add it or not. I tested it and it does work for some cases but it's no longer exercised by any of my test cases so I can't say whether it's actually mergeable for sure.

File: src/coreclr/jit/codegenwasm.cpp [hunk 2]
```diff
@@ -2420,9 +2426,99 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
...
+            emit->emitIns_I(INS_local_get, attrDstAddr, WasmRegToIndex(dstReg));
+            emit->emitIns_I(INS_I_const, attrDstAddr, offset);
+            emit->emitIns(INS_I_add);
+            emit->emitIns_I(INS_local_get, attrSrcAddr, WasmRegToIndex(srcReg));
+            emit->emitIns_I(INS_I_const, attrSrcAddr, offset);
+            emit->emitIns(INS_I_add);
+            // Call the byref assign helper. On other targets this updates the dst/src regs but here it won't,
+            //  so we have to do the local.get+i32.const+i32.add dance every time.
+            genEmitHelperCall(CORINFO_HELP_ASSIGN_BYREF, 0, EA_PTRSIZE);
+            gcPtrCount--;
```
[the remark this answers is not in the document]
Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp:2543]: I think we are going to do something so that HELP_ASSIGN_BYREF specifically only takes two args (dest and src) to reduce code size and improve performance for write barriers. That's not implemented yet though.

File: src/coreclr/jit/codegenwasm.cpp [hunk 3]
```diff
@@ -2420,9 +2426,102 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
...
+
+    regNumber srcReg = GetMultiUseOperandReg(source);
+    regNumber dstReg = GetMultiUseOperandReg(dstAddr);
+
+    if (cpObjNode->IsVolatile())
+    {
+        // TODO-WASM: Memory barrier
+    }
+
+    // TODO: Do we need an implicit null check here?
```
Comment (EgorBo) [inline src/coreclr/jit/codegenwasm.cpp]: Yes

File: src/coreclr/jit/codegenwasm.cpp [hunk 4]
```diff
@@ -2420,9 +2426,102 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
     }
 }
 
+//------------------------------------------------------------------------
+// genCodeForCpObj: Produce code for a GT_STORE_BLK node that represents a cpobj operation.
+//
+// Arguments:
+//    cpObjNode - the node
+//
 void CodeGen::genCodeForCpObj(GenTreeBlk* cpObjNode)
```
Comment (EgorBo) [inline src/coreclr/jit/codegenwasm.cpp:2444]: We probably can never get here if we extend `TryLowerBlockStoreAsGcBulkCopyCall` to never bail. So all cpobj will go through the batch helper

Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp:2444]: Is that bad?

File: src/coreclr/jit/lowerwasm.cpp [hunk 5]
```diff
@@ -244,6 +244,11 @@ void Lowering::LowerBlockStore(GenTreeBlk* blkNode)
         ClassLayout* layout  = blkNode->GetLayout();
         bool         doCpObj = layout->HasGCPtr();
 
+        // If copying to the stack instead of the heap, we should treat it as a raw memcpy for
+        //  smaller generated code and potentially better performance.
+        if (blkNode->IsAddressNotOnHeap(m_compiler))
+            doCpObj = false;
```
Comment (EgorBo) [inline src/coreclr/jit/lowerwasm.cpp:250]: other targets do this only under size check + they set `blkNode->gtBlkOpGcUnsafe = true;`

Comment (kg) [reply src/coreclr/jit/lowerwasm.cpp:250]: We're trying always using the native wasm memcpy/memset opcodes because the VMs unroll them for us, which should provide both optimal code size and perf. So I think omitting the size check is okay.

Great point on gc unsafe.

File: src/coreclr/jit/codegenwasm.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/jit/codegenwasm.cpp:2444]: > Is that bad?

I mean for simplicity. The bulk helper is likely a bit less efficient for small object copies with just 1 gc ref where we can emit just one write-barrier, otherwise it's better. It also is simdified.

File: src/coreclr/jit/lowerwasm.cpp (hunk 5 above)
Comment (EgorBo) [reply src/coreclr/jit/lowerwasm.cpp:250]: Yeah it's fine. `gtBlkOpGcUnsafe` is needed for correctness, I'm not sure wasm can run into this, but for other targets we put copy into a nogc region in this case so we can ignore potential atomicity issues

File: src/coreclr/jit/codegenwasm.cpp (hunk 4 above)
Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp:2444]: Oh I misunderstood. So for a struct that has i.e. 4 gc ptrs at the head and then some random ints and floats at the tail, TryLowerBlockStoreAsGcBulkCopyCall will just lower this away entirely in theory. I've been testing with interleaved ptrs where a bulk one isn't possible.
I was definitely thinking we'd want to use bulk copies if possible.

File: src/coreclr/jit/lowerwasm.cpp (hunk 5 above)
Comment (SingleAccretion) [reply src/coreclr/jit/lowerwasm.cpp:250]: `gtBlkOpGcUnsafe` is not needed on WASM. There is no emitter-level tracking of no-gc regions on WASM.

File: src/coreclr/jit/codegenwasm.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/jit/codegenwasm.cpp:2444]: TryLowerBlockStoreAsGcBulkCopyCall can handle any layout, even if there are no gc refs at all (although, in that case we should never be in cpobj, because we rely on the fact that the size is divisble by pointer size).

File: src/coreclr/jit/lowerwasm.cpp (hunk 5 above)
Comment (EgorBo) [reply src/coreclr/jit/lowerwasm.cpp:250]: well, we can do what other targets do and then just ignore it in the emitter till we implement threads, interruptible gc or whatever?

Comment (EgorBo) [reply src/coreclr/jit/lowerwasm.cpp:250]: It feels like `LowerBlockStore` should be just shared between all impl, currently it's copy-paste for all 6 or so targets (not for this PR)

Comment (SingleAccretion) [reply src/coreclr/jit/lowerwasm.cpp:250]: > well, we can do what other targets do and then just ignore it in the emitter till we implement threads, interruptible gc or whatever?

We won't need it for those things either. We will only need it if a WASM proposal comes around which makes stack walking in the traditional sense possible, which is exceedingly unlikely.

File: src/coreclr/jit/regallocwasm.cpp [hunk 6]
```diff
@@ -50,7 +52,19 @@ void WasmRegAlloc::dumpLsraStatsSummary(FILE* file)
...
+    }
+    if (node->IsLocal())
+    {
+        if (!m_compiler->compEnregLocals())
+        {
+            return true;
+        }
+        const LclVarDsc* varDsc = m_compiler->lvaGetDesc(node->AsLclVar());
+        return varDsc->lvDoNotEnregister;
+    }
```
Comment (kg) [inline src/coreclr/jit/regallocwasm.cpp]: @SingleAccretion @AndyAyersMS thoughts? I had to do this for some of my test cases to work.

Comment (SingleAccretion) [reply src/coreclr/jit/regallocwasm.cpp]: Since this is just a copy from lsrabuild.cpp, it should live in regalloc.cpp with the other shared bits.

By the way, you will also need to add an NYI for contained `BITCAST` operands I suspect.

File: src/coreclr/jit/codegenwasm.cpp [hunk 7]
```diff
@@ -2420,9 +2428,126 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
...
+        noway_assert(source->OperIs(GT_LCL_FLD, GT_LCL_VAR));
+        GenTreeLclVarCommon* lclVar = source->AsLclVarCommon();
+        bool                 fpBased;
+        srcOffset = m_compiler->lvaFrameAddress(lclVar->GetLclNum(), &fpBased) + lclVar->GetLclOffs();
+        noway_assert(fpBased);
+        srcReg = GetFramePointerReg();
+    }
+
+    noway_assert(source->IsLocal());
+
```
[the remark this answers is not in the document]
Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp]: I'm leaving this as-is because I haven't come up with a test case that fails the assert yet so I'd rather not remove this restriction until we're sure it will work. If anyone else disagrees I'm happy to delete this assert.

[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/jit/codegenwasm.cpp]: I think it can be easily anything other than local in case if source was GT_IND, e.g. GT_ADD ?

[the remark this answers is not in the document]
Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp]: Will try something with Unsafe.Add or pointer arithmetic and see if that repros it.

File: src/coreclr/jit/lowerwasm.cpp [hunk 8]
```diff
@@ -512,6 +513,60 @@ void Lowering::AfterLowerBlock()
...
+                    //  is not possible for contained nodes like an IND inside a STORE_BLK. However, the few types of
+                    //  contained nodes we have in Wasm should be safe to move freely since the lack of 'dup' or
+                    //  persistent registers in Wasm means that the actual codegen will trigger the side effect(s) and
+                    //  store the result into a Wasm local for any later uses during the containing node's execution,
+                    //  i.e. cpobj where the src and dest get stashed at the start and then used as add operands
+                    //  repeatedly.
+                    // Locals can also be safely moved as long as they aren't address-exposed due to local var nodes
+                    // being
+                    //  implicitly pseudo-contained.
+                    // TODO-WASM: Verify that it is actually safe to do this for all contained nodes.
```
Comment (AndyAyersMS) [inline src/coreclr/jit/lowerwasm.cpp:540]: Feels like we should invoke lower's `IsInvariantInRange` here. It should do the proper checking.

Something like
```C++
if (m_lower->IsInvariantInRange(node, prev->gtNext))
```

FYI @jakobbotsch

File: src/coreclr/jit/regallocwasm.cpp (hunk 6 above)
Comment (kg) [reply src/coreclr/jit/regallocwasm.cpp]: How do I do that? WasmRegAlloc doesn't have a base class to house code, it looks like.

File: src/coreclr/jit/codegenwasm.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/jit/codegenwasm.cpp]: is there a reason this assert is needed? I don't see anything that depends on the tree being a local in the code

File: src/coreclr/jit/regallocwasm.cpp (hunk 6 above)
Comment (kg) [reply src/coreclr/jit/regallocwasm.cpp]: Ah, found the RegAllocImpl trick. I didn't realize that was even legal to do in C++, clever.

File: src/coreclr/jit/lowerwasm.cpp (hunk 8 above)
Comment (kg) [reply src/coreclr/jit/lowerwasm.cpp:540]: Done, did you want any other changes here?

File: src/coreclr/jit/regallocwasm.cpp (hunk 6 above)
Comment (kg) [reply src/coreclr/jit/regallocwasm.cpp]: OK, done. What's the details of the NYI? Check whether the parent node is a BITCAST? Or NYI for bitcast nodes themselves?

File: src/coreclr/jit/codegenwasm.cpp (hunk 3 above)
Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp]: For this scenario should I generate an explicit GT_NULLCHECK node in lowering? Or do i call the emitter code to generate a nullcheck directly from inside this node? Not clear on whether the latter would mess up control flow assumptions

File: src/coreclr/jit/codegenwasm.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp]: It was there in the other architecture I modeled this on. But I don't think it's needed, you're right.

File: src/coreclr/jit/regallocwasm.cpp (hunk 6 above)
Comment (SingleAccretion) [reply src/coreclr/jit/regallocwasm.cpp]: > What's the details of the NYI

Something like: `if (op1->isContained()) NYI_WASM(...)` in `genCodeForBitCast`.

File: src/coreclr/jit/codegenwasm.cpp (hunk 3 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/codegenwasm.cpp]: You can do it here in codegen -- ensure the node you want to null check is multi-use, extract its register, and then call `genEmitNullCheck(reg)`.

File: src/coreclr/jit/codegenwasm.cpp [hunk 9]
```diff
@@ -427,7 +431,9 @@ void CodeGen::WasmProduceReg(GenTree* node)
 //
 // If the operand is a candidate, we use that candidate's current register.
 // Otherwise it must have been allocated into a temporary register initialized
-// in 'WasmProduceReg'.
+// in 'WasmProduceReg'. To do this, call treeNode->SetMultiplyUsed() during
+// lowering or other pre-regalloc phases, and ensure that regalloc is updated to
+// call CollectReferences on the node(s) that need to be used multiple times.
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenwasm.cpp]:
```suggestion
// in 'WasmProduceReg'. To do this, call treeNode->SetMultiplyUsed() during
// lowering and ensure that regalloc is updated to call 'ConsumeTemporaryRegForOperand'
// on the node(s) that need to be used multiple times.
```

File: src/coreclr/jit/lowerwasm.cpp (hunk 8 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lowerwasm.cpp:540]: Just calling `IsInvariantInRange` should be sufficient, I think? So you can drop the other `||` clauses.

File: src/coreclr/jit/codegenwasm.cpp [hunk 10]
```diff
@@ -2420,9 +2428,124 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
...
+
+    emitter* emit = GetEmitter();
+
+    // TODO-WASM: Implicit null check
+
+    // TODO-WASM: Remove the need to do this somehow
+    // The dst and src may be on the evaluation stack, but we can't reliably use them, so drop them.
+    emit->emitIns(INS_drop);
+    if (!source->isContained())
+        emit->emitIns(INS_drop);
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenwasm.cpp:2499]: I am confused by the need for this `drop`. These operands are already in the right order for the first helper call / load/store pair.

(Assuming we implement the write barrier calling convention opt below)

File: src/coreclr/jit/codegenwasm.cpp [hunk 11]
```diff
@@ -2420,9 +2428,124 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
...
+            emit->emitIns_I(INS_local_get, attrDstAddr, WasmRegToIndex(dstReg));
+            emit->emitIns_I(INS_local_get, attrSrcAddr, WasmRegToIndex(srcReg));
+            emit->emitIns_I(INS_I_load, EA_PTRSIZE, srcOffset);
+            emit->emitIns_I(INS_I_store, EA_PTRSIZE, dstOffset);
+        }
+        else
+        {
+            // Load the sp onto the stack for the helper call.
+            // TODO-WASM: Implement a special calling convention for this helper that doesn't accept sp/pep.
+            emit->emitIns_I(INS_local_get, EA_PTRSIZE, WasmRegToIndex(GetStackPointerReg()));
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenwasm.cpp:2531]:
```suggestion
```
I think we add code that is closer to what we want to be the end state.

File: src/coreclr/jit/codegenwasm.cpp [hunk 12]
```diff
@@ -2420,9 +2428,124 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
...
+            // Compute the actual dest/src of the slot being copied to pass to the helper.
+            emit->emitIns_I(INS_local_get, attrDstAddr, WasmRegToIndex(dstReg));
+            emit->emitIns_I(INS_I_const, attrDstAddr, dstOffset);
+            emit->emitIns(INS_I_add);
+            emit->emitIns_I(INS_local_get, attrSrcAddr, WasmRegToIndex(srcReg));
+            emit->emitIns_I(INS_I_const, attrSrcAddr, srcOffset);
+            emit->emitIns(INS_I_add);
+            // TODO-WASM: Load the PEP value for the helper onto the stack here? Right now genEmitHelperCall does it.
+            // Call the byref assign helper. On other targets this updates the dst/src regs but here it won't,
+            //  so we have to do the local.get+i32.const+i32.add dance every time.
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenwasm.cpp]:
```suggestion
            // TODO-WASM: don't load PEP in genEmitHelperCall for write barriers.
            // TODO-WASM-CQ: add a version of CORINFO_HELP_ASSIGN_BYREF that returns the updated dest/src
            // pointers as a multi-value tuple and use it here.
```

File: src/coreclr/jit/codegenwasm.cpp [hunk 13]
```diff
@@ -2420,9 +2428,124 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
...
+    }
+
+    assert(gcPtrCount == 0);
+
+    if (cpObjNode->IsVolatile())
+    {
+        // TODO-WASM: Memory barrier
+    }
+
+    WasmProduceReg(cpObjNode);
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenwasm.cpp]:
```suggestion
    genUpdateLife(cpObjNode);
```
These nodes don't produce any values.

It would be better to move this call to the caller of this method so that it is called for call 'block' operations.

File: src/coreclr/jit/gentree.h [hunk 14]
```diff
@@ -1228,6 +1228,11 @@ struct GenTree
     // LIR flags
     //   These helper methods, along with the flag values they manipulate, are defined in lir.h
     //
+#ifdef TARGET_WASM
+    // Asks the register allocator to allocate a dedicated register for this node so we can use its value multiple
+    // times.
+    inline void SetMultiplyUsed();
```
Comment (SingleAccretion) [inline src/coreclr/jit/gentree.h:1234]: I would make this a `static` method in `lowerwasm.cpp`. This way we have fewer ifdefs in common code (and less code overall).

File: src/coreclr/jit/lowerwasm.cpp [hunk 15]
```diff
@@ -512,6 +513,62 @@ void Lowering::AfterLowerBlock()
...
+                    if (
+                        m_lower->IsInvariantInRange(node, prev->gtNext) ||
+                        node->isContained() ||
+                        (node->OperIs(GT_LCL_VAR) &&
+                         !m_lower->m_compiler->lvaGetDesc(node->AsLclVarCommon())->IsAddressExposed()))
```
Comment (SingleAccretion) [inline src/coreclr/jit/lowerwasm.cpp]:
```suggestion
                    if (CanMove(node))
```
Let's move into its own method so that the top-level algorithm doesn't get cluttered.

Also `IsInvariantInRange` is NOT needed for these hand-picked special case conditions. That's kind of the point, to avoid the checking of `IsInvariantInRange`.

The general version of this could indeed be built on top of `IsInvariantInRange`, but it would be quadratic (this is what `...avoid quadratic behavior...` refers to).

File: src/coreclr/jit/lowerwasm.cpp [hunk 16]
```diff
@@ -512,6 +513,62 @@ void Lowering::AfterLowerBlock()
...
+
+                        unsigned lclNum = nodeUse.ReplaceWithLclVar(m_lower->m_compiler);
+                        GenTree* newNode = nodeUse.Def();
+                        JITDUMP("Stackifier replaced node [%06u] with lcl var %u\n", Compiler::dspTreeID(node), lclNum);
+                        m_lower->BlockRange().Remove(newNode);
+                        m_lower->BlockRange().InsertAfter(prev, newNode);
+                        JITDUMP("Stackifier moved new node [%06u] after [%06u]\n", Compiler::dspTreeID(newNode),
+                    Compiler::dspTreeID(prev)); break;
+                    }
+                    */
```
Comment (SingleAccretion) [inline src/coreclr/jit/lowerwasm.cpp]:
```suggestion
```
Since this is a pretty big change already, let's defer this.

File: src/coreclr/jit/compiler.h [hunk 17]
```diff
@@ -2566,6 +2566,10 @@ class Compiler
     friend class ReplaceVisitor;
     friend class FlowGraphNaturalLoop;
 
+#ifdef TARGET_WASM
+    friend class WasmRegAlloc; // For m_pLowering
```
Comment (SingleAccretion) [inline src/coreclr/jit/compiler.h]: Let's avoid this and add a public accessor like:
```
Lowering* GetLowering() const
{
    return m_pLowering;
}
```
to `Compiler` instead.

File: src/coreclr/jit/regallocwasm.cpp [hunk 18]
```diff
@@ -476,6 +491,9 @@ void WasmRegAlloc::RewriteLocalStackStore(GenTreeLclVarCommon* lclNode)
     CurrentRange().InsertAfter(lclNode, store);
     CurrentRange().Remove(lclNode);
     CurrentRange().InsertBefore(insertionPoint, lclNode);
+
+    auto tempRange = LIR::ReadOnlyRange(store, store);
+    m_compiler->m_pLowering->LowerRange(m_currentBlock, tempRange);
```
Comment (SingleAccretion) [inline src/coreclr/jit/regallocwasm.cpp]:
```suggestion
    LIR::ReadOnlyRange storeRange(store, store);
    m_compiler->m_pLowering->LowerRange(m_currentBlock, storeRange);
```
We generally like to avoid `auto`.

File: src/coreclr/jit/regallocwasm.cpp [hunk 19]
```diff
@@ -539,6 +557,8 @@ void WasmRegAlloc::RequestTemporaryRegisterForMultiplyUsedNode(GenTree* node)
     // Note how due to the fact we're processing nodes in stack order,
     // we don't need to maintain free/busy sets, only a simple stack.
     regNumber reg = AllocateTemporaryRegister(genActualType(node));
+    // If the node already has a regnum, trying to assign it a second one is no good.
+    assert(node->GetRegNum() == REG_NA);
```
Comment (SingleAccretion) [inline src/coreclr/jit/regallocwasm.cpp]:
```suggestion
    assert((node->GetRegNum() == REG_NA) && "Trying to double-assign a temporary register");
```
We can use this trick to save some looking into the source.

File: src/coreclr/jit/regallocwasm.cpp [hunk 20]
```diff
@@ -561,6 +581,7 @@ void WasmRegAlloc::ConsumeTemporaryRegForOperand(GenTree* operand DEBUGARG(const
     }
 
     regNumber reg = ReleaseTemporaryRegister(genActualType(operand));
+    // If this assert fails you likely called ConsumeTemporaryRegForOperand on your operands in the wrong order.
     assert(reg == operand->GetRegNum());
```
Comment (SingleAccretion) [inline src/coreclr/jit/regallocwasm.cpp]:
```suggestion
assert((reg == operand->GetRegNum()) && "Temporary reg being consumed out of order");
```

File: src/coreclr/jit/regallocwasm.cpp [hunk 21]
```diff
@@ -605,6 +626,8 @@ void WasmRegAlloc::ResolveReferences()
     {
         TemporaryRegStack& temporaryRegs          = m_temporaryRegs[static_cast<unsigned>(type)];
         TemporaryRegBank&  allocatedTemporaryRegs = temporaryRegMap[static_cast<unsigned>(type)];
+        // If temporaryRegs.Count != 0 that means CollectReferences failed to CollectReference one or more multiply-used
+        // nodes.
         assert(temporaryRegs.Count == 0);
```
Comment (SingleAccretion) [inline src/coreclr/jit/regallocwasm.cpp]:
```suggestion
assert((temporaryRegs.Count == 0) && "Some temporary regs were not consumed/released");
```

File: src/coreclr/jit/regallocwasm.h [hunk 22]
```diff
@@ -125,6 +125,7 @@ class WasmRegAlloc : public RegAllocInterface
     void      CollectReferencesForCast(GenTreeOp* castNode);
     void      CollectReferencesForBinop(GenTreeOp* binOpNode);
     void      CollectReferencesForLclVar(GenTreeLclVar* lclVar);
+    void      CollectReferencesForBlockStore(GenTreeBlk* node);
```
Comment (SingleAccretion) [inline src/coreclr/jit/regallocwasm.h]:
```suggestion
    void      CollectReferencesForBlockStore(GenTreeBlk* node);
    void      CollectReferencesForLclVar(GenTreeLclVar* lclVar);
```
We're trying to match the decl and impl orders.

File: src/coreclr/jit/codegenwasm.cpp [hunk 23]
```diff
@@ -2420,9 +2428,124 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
...
+    {
+        source = source->gtGetOp1();
+        assert(!source->isContained());
+        srcAddrType = source->TypeGet();
+        srcReg      = GetMultiUseOperandReg(source);
+        srcOffset   = 0;
+    }
+    else
+    {
+        noway_assert(source->OperIs(GT_LCL_FLD, GT_LCL_VAR));
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenwasm.cpp]:
```suggestion
        assert(source->OperIs(GT_LCL_FLD, GT_LCL_VAR));
```

File: src/coreclr/jit/codegenwasm.cpp [hunk 24]
```diff
@@ -2420,9 +2428,124 @@ void CodeGen::genCodeForStoreBlk(GenTreeBlk* blkOp)
...
+        GenTreeLclVarCommon* lclVar = source->AsLclVarCommon();
+        bool                 fpBased;
+        srcOffset = m_compiler->lvaFrameAddress(lclVar->GetLclNum(), &fpBased) + lclVar->GetLclOffs();
+        noway_assert(fpBased);
```
Comment (SingleAccretion) [inline src/coreclr/jit/codegenwasm.cpp]:
```suggestion
        assert(fpBased);
```
It is rare that you need a `noway_assert`.

`noway_assert` is a Release-mode assert. You only should need for cases where you suspect it may not be hit in our extensive testing.

File: src/coreclr/jit/lowerwasm.cpp (hunk 8 above)
Comment (SingleAccretion) [reply src/coreclr/jit/lowerwasm.cpp:540]: > Just calling IsInvariantInRange should be sufficient, I think? So you can drop the other || clauses.

It would be sufficient, but it would not be linear, since it would need to be called for each subnode of a 'far' tree. Furthermore, I suspect it won't be optimal since, e. g. say we're trying to stackify an `ADD`, which itself can be moved. But then it becomes a possibility that > 1 of its sub-operands cannot be moved, which would force us to introduce > 1 temporaries (where we would otherwise only need one, for the `ADD` itself).

File: src/coreclr/jit/codegenwasm.cpp (hunk 3 above)
Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp]: When I do that I hit an assert:
```
Z:\runtime\src\coreclr\jit\flowgraph.cpp:3399
Assertion failed '!fgRngChkThrowAdded' in 'Program:copyStructWithRefs(byref,byref)' during 'Generate code' (IL size 13; hash 0x75fea2d4; MinOpts)

Z:\runtime\src\coreclr\jit\flowgraph.cpp:3399
Assertion failed '!fgRngChkThrowAdded' in 'Program:fillStructFromLocal(byref)' during 'Generate code' (IL size 25; hash 0x3b263e03; MinOpts)
```

File: src/coreclr/jit/codegenwasm.cpp (hunk 10 above)
Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp:2499]: Yes, once we optimize the write barrier calling convention the stack will be in the right shape. It's not yet though hence the drop(s).

File: src/coreclr/jit/codegenwasm.cpp (hunk 11 above)
Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp:2531]: This will produce modules that don't compile, but maybe that's fine for now?

File: src/coreclr/jit/codegenwasm.cpp (hunk 3 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/codegenwasm.cpp]: In `StackLevelSetter::SetThrowHelperBlocks` you need to record that these operators can cause null checks.

https://github.com/dotnet/runtime/blob/7356734a70e52816c9768009bafb4ff24e32b7d4/src/coreclr/jit/stacklevelsetter.cpp#L287-L299

Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp]: That fixed it, the module just fails to compile now due to the signature of the throw helper call.

File: src/coreclr/jit/codegenwasm.cpp (hunk 11 above)
Comment (SingleAccretion) [reply src/coreclr/jit/codegenwasm.cpp:2531]: > modules that don't compile

Hmm, I would've expected all this to not compile currently anyway since we don't produce the right `call_indirect` types yet.

Comment (kg) [reply src/coreclr/jit/codegenwasm.cpp:2531]: The helper calls happen to have the right signature for the write barriers, so everything compiles and runs in this PR (except for the actual helper calls) until I add null checks (which break because the helper signature is wrong)

File: src/coreclr/jit/lowerwasm.cpp (hunk 8 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lowerwasm.cpp:540]: Hmm, ok. Well maybe we can call it in an assert, just to be sure we're not moving things improperly.

File: src/coreclr/jit/codegenwasm.cpp (hunk 11 above)
Comment (SingleAccretion) [reply src/coreclr/jit/codegenwasm.cpp:2531]: I see. Let's leave this as-is then (including `drop`s). I've added a note about this into https://github.com/dotnet/runtime/issues/121865.

Comment (AndyAyersMS) [reply src/coreclr/jit/codegenwasm.cpp:2531]: Getting the helper call sigs right in general is going to take some work, since there's no description of them. I opened this issue to keep track of this:

https://github.com/dotnet/runtime/issues/124978

File: src/coreclr/jit/lowerwasm.cpp [hunk 25]
```diff
@@ -512,6 +513,63 @@ void Lowering::AfterLowerBlock()
...
+                    // being
+                    //  implicitly pseudo-contained.
+                    // TODO-WASM: Verify that it is actually safe to do this for all contained nodes.
+                    if (node->IsInvariant() || node->isContained() ||
+                        (node->OperIs(GT_LCL_VAR) &&
+                         !m_lower->m_compiler->lvaGetDesc(node->AsLclVarCommon())->IsAddressExposed()))
+                    {
+                        JITDUMP("Stackifier moving node [%06u] after [%06u]\n", Compiler::dspTreeID(node),
+                                Compiler::dspTreeID(prev));
+#if DEBUG
```
Comment (SingleAccretion) [inline src/coreclr/jit/lowerwasm.cpp]: Note: you don't need to wrap `assert`s in `#ifdef DEBUG`. Their bodies are already automatically erased under `!DEBUG`.

**Review by SingleAccretion — APPROVED** [review]
LGTM modulo `SetMultiplyUsed` nit.

File: src/coreclr/jit/gentree.h (hunk 14 above)
Comment (kg) [reply src/coreclr/jit/gentree.h:1234]: I would prefer to do that in a follow-up to avoid adding more changes to this PR but if anyone thinks it's urgent I can revise this PR to make the change. I agree that making it a static in lowerwasm is ideal.

File: src/coreclr/jit/regallocwasm.cpp [hunk 26]
```diff
@@ -417,6 +417,21 @@ void WasmRegAlloc::CollectReferencesForBinop(GenTreeOp* binopNode)
...
 
+// CollectReferencesForBlockStore: Collect virtual register references for a block store.
+//
+// Arguments:
+//    node - The GT_STORE_BLK node
+//
+void WasmRegAlloc::CollectReferencesForBlockStore(GenTreeBlk* node)
+{
+    GenTree* src = node->Data();
+    if (src->OperIs(GT_IND))
```
Comment (AndyAyersMS) [inline src/coreclr/jit/regallocwasm.cpp:428]: Nit: braces

File: src/coreclr/jit/lowerwasm.cpp [hunk 27]
```diff
@@ -254,6 +259,9 @@ void Lowering::LowerBlockStore(GenTreeBlk* blkNode)
             }
 
             blkNode->gtBlkOpKind = GenTreeBlk::BlkOpKindCpObjUnroll;
+            dstAddr->SetMultiplyUsed();
+            if (src->OperIs(GT_IND))
+                src->gtGetOp1()->SetMultiplyUsed();
```
Comment (AndyAyersMS) [inline src/coreclr/jit/lowerwasm.cpp:264]: Nit: braces

File: src/coreclr/jit/lowerwasm.cpp (hunk 5 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lowerwasm.cpp:250]: Nit: braces

**Review by AndyAyersMS — APPROVED** [review]
LGTM overall, just a few formatting nits you can fix in a follow-up PR.
