### PR TITLE
[EventTrace] Update check for provider triggered GC

### LINKED ISSUE #99487: CLR_GCHEAPCOLLECT_KEYWORD triggers a GC twice
### Description

I've looked into how to trigger a GC remotely using `dotnet-trace` (by enabling keyword 0x800000) and noticed that it actually triggered two GCs: one when the keyword is enabled, and one when it's disabled.

It _looks_ like an bug in the code.

If I look at the corresponding code in the early days of coreclr, I can see that the call is wrapped in a `if(bEnabled)` condition, itself set as `((ControlCode == EVENT_CONTROL_CODE_ENABLE_PROVIDER) || (ControlCode == EVENT_CONTROL_CODE_CAPTURE_STATE))`: https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/eventtrace.cpp#L4400

Now in the current version of the code, `ControlCode` is not checked anymore and so `ForceGC` is call even when disabling the keyword: https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/eventtrace.cpp#L2425

### Reproduction Steps

Run `dotnet-trace collect -p <pid> --providers Microsoft-Windows-DotNETRuntime:800000`.

### Expected behavior

One GC is triggered when opening the session.

### Actual behavior

One GC is triggered when opening the session, but then another one is triggered when closing the session.

### Regression?

The problem was not there in .NET Framework, I believe it was introduced with eventpipes.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes https://github.com/dotnet/runtime/issues/99487

This PR follows-up on https://github.com/dotnet/runtime/pull/102612/files#r1649499169 by returning the control code filtering for ETW providers and leveraging EventPipe SessionId's to differentiate between a EventPipe session being enabled or disabled to determine whether or not a GC should be forced.

## Testing

Checked whether [ForceGC](https://github.com/dotnet/runtime/blob/6d23ef4d68bbcdb38fdc22218d1073c5083ac6a1/src/coreclr/vm/eventtrace.cpp#L2423) was hit following each step.
1. Enabled an EventPipe session with `dotnet-trace collect -n sampleApp --providers Microsoft-Windows-DotNETRuntime:800000`.
2. Enabled a second EventPipe session with `dotnet-trace collect -n sampleApp --providers Microsoft-Windows-DotNETRuntime:800000`.
3. Disabled one of the EventPipe sessions by pressing Enter in one of the dotnet-trace windows.

### Debugging a simple .NET app before the changes
1. hit
2. hit
3. **HIT**.

### While debugging a simple .NET app built with the changes
1. hit
2. hit
3. **NOT HIT**

### CODE REVIEW

**Comment by jkotas** [comment]
Do we need the same change in https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/Runtime/eventtrace.cpp too?

File: src/coreclr/vm/eventtrace.cpp [hunk 1]
```diff
@@ -2403,10 +2410,25 @@ VOID EtwCallbackCommon(
...
+    // 2. The public provider is requesting GC.
+    // 3. The provider's ManagedHeapCollectKeyword is enabled.
+    // 4. If it is an ETW provider, the control code is to enable or capture the state of the provider.
+    // 5. If it is an EventPipe provider, the session is not being disabled.
+    bool bValidGCRequest =
+        g_fEEStarted && !g_fEEShutDown &&
+        bIsPublicTraceHandle &&
+        ((MatchAnyKeyword & CLR_MANAGEDHEAPCOLLECT_KEYWORD) != 0) &&
+#if !defined(HOST_UNIX)
+        ((ControlCode == EVENT_CONTROL_CODE_ENABLE_PROVIDER) ||
```
Comment (noahfalk) [inline src/coreclr/vm/eventtrace.cpp:2425]: When you have multiple sessions running via ETW and disable only one of them, does it report ENABLE_PROVIDER or DISABLE_PROVIDER in the callback? I'm trying to figure out if there are still going to be some cases where it is impossible for us to disambiguate because of limitations in the ETW provided data. I'm also curious if we need to maintain both a ControlCode and a SessionChange parameter when they seem to have overlapping info.

Comment (mdh1418) [reply src/coreclr/vm/eventtrace.cpp:2425]: After enabling multiple ETW trace sessions, disabling one of them will hit here for the DotNETRuntime provider 2x 
with MatchAnyFilter (0x8000000000000008 and 0x0000000000000008) both with ControlCode 0x00000001.

I also noticed that trying to close the second session, it doesn't actually hit this path as it seemed to have failed. 
Screenshot 2024-11-08 150212

Maybe because both ETW sessions I used the same command and so it already triggered rundown?

Comment (noahfalk) [reply src/coreclr/vm/eventtrace.cpp:2425]: OK, so it sounds like with ETW and multiple sessions using the ENABLE_PROVIDER control code will just be unavoidably ambiguous and the runtime would continue to trigger multiple GCs in that case. ETW tools users would need to use the CAPTURE_STATE control code instead if they wanted to avoid the duplicates. For EventPipe at least the issue is resolved.

I was pondering if there was some better way to factor ControlCode, SessionChange, and the isEventPipeCallback bit but I concluded the way you have it seems good. A couple improvements I would suggest:
- Lets define the same values for EVENT_CONTROL_CODE_* on HOST_UNIX too so that we don't have to ifdef the checks. We could do that in eventtracebase.h. Above EventPipe was asserting ControlCode == 0 || ControlCode == 1 and ideally that would be use the named defines too rather than hardcoding magic constants.
- I would add some explicit documentation above the EtwCommonCallback describing that even when a session is disabled the control code will still be ENABLE_PROVIDER if some other session remains active. I think mis-interpreting that parameter has caused confusion and bugs on multiple occasions.

Comment (noahfalk) [reply src/coreclr/vm/eventtrace.cpp:2425]: > I also noticed that trying to close the second session, it doesn't actually hit this path as it seemed to have failed.

Not sure what would cause that. It certainly might be a bug, but if the behavior is the same before and after this change I'm fine assuming it is orthogonal to the current issue.

Comment (mdh1418) [reply src/coreclr/vm/eventtrace.cpp:2488]: Sorry, just to clarify my previous statement, disabling a session after having multiple sessions enabled will hit the callback and evaluate `bValidGCRequest` but will NOT trigger a ForceGC, as the MatchAnyKeywords will not have the bitmask enabled.

Going through the scenario of enabling multiple ETW sessions with the provider `Microsoft-Windows-DotNETRuntime:800000`, I'm observing the following sequence:

### Enabling First PerfView ETW Session with keyword

| ControlCode | MatchAnyKeyword | ProviderIndex | Level | ForceGC |
|--------|--------|--------|--------|--------|
| 1 | 0x8000 0000 0000 0000 | DotNETRuntime | 0xff | NO |
| 1 | 0x8000 0000 0080 0000 | DotNETRuntime | 0xff | YES |

### Enabling Second PerfView ETW Session with keyword

| ControlCode | MatchAnyKeyword | ProviderIndex | Level | ForceGC |
|--------|--------|--------|--------|--------|
| 1 | 0x0000 0000 0080 0000 | DotNETRuntime | 0x05 | YES |
| 1 | 0x8000 0000 0080 0000 | DotNETRuntime | 0xff | YES |
| 1 | 0x0000 0000 0000 0000 | DotNETRuntime | 0xff | NO |
| 1 | 0x8000 0000 0080 0000 | DotNETRuntime | 0xff | YES |

### Disabling one of the PerfView ETW Sessions (Stopping with 's')

| ControlCode | MatchAnyKeyword | ProviderIndex | Level | ForceGC |
|--------|--------|--------|--------|--------|
| 1 | 0x8000 0000 0000 0000 | DotNETRuntime | 0xff | NO |
| 1 | 0x8000 0000 0000 0000 | DotNETRuntimeRundown | 0xff | NO |
| 1 | 0x0000 0000 0000 0000 | DotNETRuntime | 0x05 | NO |
| 0 | 0x0000 0000 0000 0000 | DotNETRuntimeRundown | 0x00 | NO |

For what its worth, there was one instance where I observed a ControlCode 0 for DotNETRuntime when disabling the ETW session, and that had Level 0x00, but after many attempts, I haven't been able to reproduce it.

Comment (mdh1418) [reply src/coreclr/vm/eventtrace.cpp:2486]: Added the keywords to HOST_UNIX and added the note to EtwCallbackCommon

File: src/coreclr/nativeaot/Runtime/eventtrace.cpp [hunk 2]
```diff
@@ -189,7 +198,7 @@ void EtwCallbackCommon(
     // This callback gets called on both ETW/EventPipe session enable/disable.
     // We need toupdate the EventPipe provider context if we are in a callback
     // from EventPipe, but not from ETW.
-    if (isEventPipeCallback)
+    if (Change == EventPipeSessionEnable || Change == EventPipeSessionDisable)
```
Comment (noahfalk) [inline src/coreclr/nativeaot/Runtime/eventtrace.cpp:201]: Can you update the 0/1 magic constants at line 208 just below as well?

**Review by noahfalk — APPROVED** [review]
Looks good! You fixed one spot where 0/1 was hardcoded but it would be good to get the other one too.

File: src/coreclr/nativeaot/Runtime/eventtrace.cpp (hunk 2 above)
Comment (mdh1418) [reply src/coreclr/nativeaot/Runtime/eventtrace.cpp:201]: Done! Thanks for the catch.

**Comment by mdh1418** [comment]
/ba-g The System.Linq.Queryable.Tests WorkItem passed, but there was an UploadError that is being tracked by https://github.com/dotnet/dnceng/issues/4463
