### PR TITLE
Change Linux fetch timeout behavior for chain building

### LINKED ISSUE #40578: Constrain X509ChainPolicy.UrlRetrievalTimeout to acceptable ranges
The [`X509ChainPolicy.UrlRetrievalTimeout`][1] property is a `TimeSpan` that currently does not throw when given a value less than zero, or `TotalMilliseconds` larger than `int.MaxValue`. A negative value for this property behaves differently from Linux and Windows. Linux treats a negative value as-is and every network operation during chain building will time out (all time-budget has been used). Windows ends up treating the negative value as an unsigned value, so -1 ends up being treated as `uint.MaxValue` for example. However, Win32 appears to cap the value at 1 minute anyway, so all negative values are currently being treated as 1 minute.

I propose that the `set` for `UrlRetrievalTimeout` throw an `ArgumentOutOfRangeException` if it is less than zero or greater than `TimeSpan.FromMilliseconds(int.MaxValue)`. Using a negative value likely isn't intentional and more likely a `DateTime` arithmetic mistake or a typo. Using a large value like `TimeSpan.MaxValue` may be done as an attempt to have no timeout.

This would be a breaking behavioral change, though a small one in my opinion.

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainpolicy.urlretrievaltimeout?view=netcore-3.1

### PR DESCRIPTION
**Pull request by vcsjones**
This gets the ball rolling on what I guess is going to require some discussion to unify UrlRetreivalTimeout on Windows / Linux.

Change the UrlRetrievalTimeout behavior on Linux to match Windows' existing behavior of using a per-operation timeout rather than cumulative.

Add some tests for operations that time out.

Contributes to #38875
Closes #40578

### CODE REVIEW

File: src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/RevocationResponder.cs [hunk 1]
```diff
@@ -30,6 +30,9 @@ internal sealed class RevocationResponder : IDisposable
 
         public bool RespondEmpty { get; set; }
 
+        public TimeSpan RespondDelay { get; set; }
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/RevocationResponder.cs:33]:
```suggestion
        public TimeSpan ResponseDelay { get; set; }
```

Reads a bit better to me, particularly in the formatted strings.

File: src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs [hunk 2]
```diff
@@ -35,10 +35,10 @@ public static bool ReleaseSafeX509ChainHandle(IntPtr handle)
             TimeSpan timeout,
             bool disableAia)
         {
-            // An input value of 0 on the timeout is "take all the time you need".
+            // An input value of 0 on the timeout is treated as 15 seconds, to match Windows.
             if (timeout == TimeSpan.Zero)
             {
-                timeout = TimeSpan.MaxValue;
+                timeout = TimeSpan.FromSeconds(15);
             }
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:43]: Shouldn't there also be an "if it's bigger than 15 seconds, clamp it"?

Comment (vcsjones) [reply src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:43]: Eh I was waiting on "go ahead" from #40578, but I guess this is breaking enough as it is.

File: src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs [hunk 3]
```diff
@@ -0,0 +1,201 @@
...
+        [PlatformSpecific(TestPlatforms.Windows | TestPlatforms.Linux)]
+        public static void RevocationCheckingDelayed(PkiOptions pkiOptions)
+        {
+            CertificateAuthority.BuildPrivatePki(
+                pkiOptions,
+                out RevocationResponder responder,
+                out CertificateAuthority rootAuthority,
+                out CertificateAuthority intermediateAuthority,
+                out X509Certificate2 endEntityCert,
+                nameof(RevocationCheckingDelayed));
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs:26]: Isn't this parameter defaulted to [CallerMemberName]?

File: src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs [hunk 4]
```diff
@@ -0,0 +1,201 @@
...
+            using (X509Certificate2 rootCert = rootAuthority.CloneIssuerCert())
+            using (X509Certificate2 intermediateCert = intermediateAuthority.CloneIssuerCert())
+            {
+                TimeSpan delay = TimeSpan.FromSeconds(3);
+
+                X509Chain chain = holder.Chain;
+                responder.RespondDelay = delay;
+                responder.DelayedActions = RevocationResponder.DelayedActionsFlag.All;
+
+
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs:42]: NIt: too many blank lines

File: src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs [hunk 5]
```diff
@@ -0,0 +1,201 @@
...
+                chain.ChainPolicy.DisableCertificateDownloads = true;
+
+                Assert.False(chain.Build(endEntityCert));
+
+                const X509ChainStatusFlags ExpectedFlags =
+                    X509ChainStatusFlags.RevocationStatusUnknown |
+                    X509ChainStatusFlags.OfflineRevocation;
+
+                X509ChainStatusFlags eeFlags = GetFlags(chain, endEntityCert.Thumbprint);
+                X509ChainStatusFlags intermediateFlags = GetFlags(chain, intermediateCert.Thumbprint);
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs:110]: Why match by thumbprint? You know the expected index.

File: src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs (hunk 3 above)
Comment (vcsjones) [reply src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs:26]: Nope https://github.com/dotnet/runtime/blob/3642deea8235ce8316db8c37cc3e8f4ad5b15380/src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs#L821

File: src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs (hunk 5 above)
Comment (vcsjones) [reply src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs:110]: The intent is less clear to me in a test. "I am looking for flags in for a cert with this thumbprint" reads better to me than "Get the flags at 1", also because for the EE I can never remember if it is at 0 or at Length - 1.

File: src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs (hunk 3 above)
Comment (bartonjs) [reply src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs:26]: Ah, the DynamicRevocationTest wrapper is:

https://github.com/dotnet/runtime/blob/3642deea8235ce8316db8c37cc3e8f4ad5b15380/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs#L1273-L1281

You could local wrap here, or call that one.  Or just specify the names.

**Comment by bartonjs** [comment]
@vcsjones This portion of the change seems reasonable to me... are you expecting anything else to come in to it soon, or should we just check outerloop and merge this, with followups done in a different PR? (Just getting sensitive about timing)

**Comment by vcsjones** [comment]
@bartonjs I think outerloop is going to fail; I'm looking at fixing a Windows test today. Should be in by COB.

File: src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs [hunk 6]
```diff
@@ -0,0 +1,200 @@
...
+                Assert.Equal(ExpectedFlags, eeFlags);
+                Assert.Equal(ExpectedFlags, intermediateFlags);
+            }
+        }
+
+        [Fact]
+        [PlatformSpecific(TestPlatforms.Linux)]
```
Comment (vcsjones) [inline src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs:116]: This one could pass on Windows, but I was chasing down a `NotSignatureValid` locally because I think my trust store is screwed up. Anyway, since URT doesn't impact Windows' AIA anyway, I think it's okay to mark this Linux only for now and think about this more later.

**Comment by vcsjones** [comment]
@bartonjs this is ready for review and and outerloop run, assuming there is nothing else that needs to be addressed immediately.

**Comment by vcsjones** [comment]
Random thought: we could do it both ways if we wanted to. Windows lets you have a cumulative timeout with CERT_CHAIN_REVOCATION_ACCUMULATIVE_TIMEOUT. Would there be interest in an API that lets folks get the old behavior back on Linux, and use this in Windows? (Post 5, of course)

File: src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs (hunk 2 above)
Comment (bartonjs) [reply src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:43]: I don't see the upper bound clamping behavior as having been applied.

I think I'm OK with making the policy property setter throw for negative inputs (but have pinged @terrajobst offline for a conscience/reality check)... so maybe we don't need to deal with negative numbers here.

Comment (bartonjs) [reply src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:43]: Just as I said what I said about the negative numbers he convinced me that any mistakes in the wild have been accruing for 15 years (since .NET Framework 2.0); so we should just stick with "all negative numbers mean one minute".

Comment (vcsjones) [reply src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs:52]: Okay, I am not convinced that Windows' max is 1 minute, that is the behavior I have observed so far. Regardless, negative values "work" on Windows, so we can at least make it work on Linux with a 1 minute timeout.

**Comment by bartonjs** [comment]
> Would there be interest in an API that lets folks get the old behavior back on Linux, and use this in Windows? 

I'm open to the idea, especially if it seems like anyone actually wants it.  Clearly it's how I thought the Windows one worked, but early in .NET Core we didn't have the capability of writing the tests reliably (Since it wasn't until after CertificateRequest/AsnReader/AsnWriter/CustomRootTrust that we could do it in a reasonable/self-contained way).

* https://apisof.net/catalog/System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2) has 4.8% usage
* https://apisof.net/catalog/System.Security.Cryptography.X509Certificates.X509Chain.ChainPolicy has 3.8% (79% of X509Chain usage)
* https://apisof.net/catalog/System.Security.Cryptography.X509Certificates.X509ChainPolicy.UrlRetrievalTimeout has 0.6% (12.5% of X509Chain, 15.8% of ChainPolicy usage).

So it's unclear how relevant such an option would be to anyone, but I'm happy to entertain things if we feel it's relevant.  (Maybe all 0.6%/12.5%/15.8% want the feature, maybe it's none.)

**Comment by vcsjones** [comment]
> especially if it seems like anyone actually wants it

I have no idea. I'm easily excited by things 7 people on the planet want.

Innerloop failure seems unrelated, I can address any additional feedback Thursday AM.

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
Hmm. Looking at failure.

**Comment by bartonjs** [comment]
In case you hadn't had these observations already:

* The test only failed on Win8.1, it passed on Win10
* It failed by succeeding the chain, after 1 minute, 30 seconds.

Conclusion: Win8.1 had a bigger max value than Win10.

Solution1: Figure out the Win8.1 limit, and if it's acceptable, change the test to use that on Win8.1.
Solution2: Make the test just exit immediately if running on Windows8.1 or lower.

**Comment by vcsjones** [comment]
I went with solution 2 in the interest of time, and I at risk of losing power / internet due to weather, so wanted to get something in.

**Comment by vcsjones** [comment]
None of the failures appear related to this PR.
