### PR TITLE
DependencyContextWriter.WritePortableTarget(): write the duplicate key name when duplicate keys are detected

### LINKED ISSUE #57649: DependencyContextWriter.WritePortableTarget() does not write the duplicate key name when duplicate keys are detected
Some csproj files contain a combination of runtime and compilation libraries that cause the [.ToDictionary<T>() calls in DependencyContextWriter.WritePortableTarget()](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.DependencyModel/src/DependencyContextWriter.cs#L152) to throw "System.ArgumentException: An item with the same key has already been added." (See full sample stack below)

This output, while clear enough, is impossible to debug. Assuming these duplicate entries should cause a build break, we should update this .ToDictionary() logic to throw the name of the duplicate key to aid .csproj maintainers in identifying the pattern that's causing the break.

Assuming triage agrees that this is worth fixing, I will to take on implementing it and you may assign the issue to me. 

--
Stack trace:
C:\Program Files\dotnet\sdk\5.0.303\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(154,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [C:\foo.csproj]
System.ArgumentException: An item with the same key has already been added. [C:\foo.csproj]
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) [C:\foo.csproj]
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) [C:\foo.csproj]
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) [C:\foo.csproj]
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WritePortableTarget(String key, IReadOnlyList`1 runtimeLibraries, IReadOnlyList`1 compilationLibraries, UnifiedJsonWriter& jsonWriter) [C:\foo.csproj]
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WriteTargets(DependencyContext context, UnifiedJsonWriter& jsonWriter) [C:\foo.csproj]
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WriteCore(DependencyContext context, UnifiedJsonWriter jsonWriter) [C:\foo.csproj]
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write(DependencyContext context, Stream stream) [C:\foo.csproj]
   at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) [C:\foo.csproj]
   at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() [C:\foo.csproj]
   at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\foo.csproj]
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\foo.csproj]
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\foo.csproj]
    51 Warning(s)
    1 Error(s)

### PR DESCRIPTION
**Pull request by eocrawford**
Incorrectly authored csproj files (e.g., those with undetected circular references) can contain duplicate entries in library lists that cause the .ToDictionary() calls in DependencyContextWriter.WritePortableTarget() to throw "System.ArgumentException: An item with the same key has already been added." This by-design behavior can be hard to debug for complex projects, so this PR adds code to to provide the name of the duplicate key when throwing the ArgumentException to aid .csproj maintainers in identifying the dependency that's causing the break.

Fixes https://github.com/dotnet/runtime/issues/57649

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.DependencyModel/src/LibraryCollectionExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+    internal static class LibraryCollectionExtensions
+    {
+        public static Dictionary<string, T> LibraryCollectionToDictionary<T>(this IReadOnlyList<T> collection) where T : Library
+        {
+            var dictionary = new Dictionary<string, T>(StringComparer.OrdinalIgnoreCase);
+
+            foreach (var element in collection)
+            {
+                if (dictionary.ContainsKey(element.Name))
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyModel/src/LibraryCollectionExtensions.cs:17]: I wonder if instead of having to check `ContainsKey` on every element, and then check again in `.Add`, if we just had a try-catch around the foreach, caught ArgumentException, and only then wrapped the exception with the `element.Name`. That way we wouldn't need to double-check for every element.

File: src/libraries/Microsoft.Extensions.DependencyModel/src/LibraryCollectionExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,28 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace Microsoft.Extensions.DependencyModel
+{
+    using System;
+    using System.Collections.Generic;
+
+    internal static class LibraryCollectionExtensions
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyModel/src/LibraryCollectionExtensions.cs:9]: This may make more sense as an internal method in https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyModel/src/CollectionExtensions.cs

File: src/libraries/Microsoft.Extensions.DependencyModel/src/LibraryCollectionExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+    {
+        public static Dictionary<string, T> LibraryCollectionToDictionary<T>(this IReadOnlyList<T> collection) where T : Library
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyModel/src/LibraryCollectionExtensions.cs:11]: This should only be necessary when building for .NET Framework. On .NET Core, `Dictionary.Add` already adds the duplicate key value to the exception message.

https://github.com/dotnet/runtime/blob/3d5d26181cd7bc07ea6c6f87710c14ccd043b415/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs#L546-L548

You can use `#if NETFRAMEWORK` for the work-around code to check for duplicates manually. And when not on .NET Framework, just straight call `.ToDictionary` as before.

**Comment by eerhardt** [comment]
@eocrawford - are you planning on finishing this PR?

File: src/libraries/Microsoft.Extensions.DependencyModel/src/LibraryCollectionExtensions.cs (hunk 1 above)
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.DependencyModel/src/LibraryCollectionExtensions.cs:17]: I did a really quick benchmark of this:

```C#
    [MemoryDiagnoser(displayGenColumns: false)]
    public class CollectionBenchmarks
    {
        private IReadOnlyList<RuntimeLibrary> _libraries;

        public CollectionBenchmarks()
        {
            const string depsFilePath = @"C:\Users\eerhardt\source\repos\CollectionBenchmark\CollectionBenchmark\bin\Release\net462\CollectionBenchmark.deps.json";
            _libraries = new DependencyContextJsonReader().Read(File.OpenRead(depsFilePath)).RuntimeLibraries;
        }

        [Benchmark(Baseline = true)]
        public Dictionary<string, RuntimeLibrary> LibraryCollectionToDictionary1() => _libraries.LibraryCollectionToDictionary1();

        [Benchmark]
        public Dictionary<string, RuntimeLibrary> LibraryCollectionToDictionary2() => _libraries.LibraryCollectionToDictionary2();
    }

    internal static class MyExtensions
    {
        internal static Dictionary<string, T> LibraryCollectionToDictionary1<T>(this IReadOnlyList<T> collection) where T : Library
        {
            var dictionary = new Dictionary<string, T>(StringComparer.OrdinalIgnoreCase);

            foreach (var element in collection)
            {
                if (dictionary.ContainsKey(element.Name))
                {
                    throw new ArgumentException("duplicate");
                }

                dictionary.Add(element.Name, element);
            }

            return dictionary;
        }

        internal static Dictionary<string, T> LibraryCollectionToDictionary2<T>(this IReadOnlyList<T> collection) where T : Library
        {
            var dictionary = new Dictionary<string, T>(StringComparer.OrdinalIgnoreCase);

            foreach (var element in collection)
            {
                try
                {
                    dictionary.Add(element.Name, element);
                }
                catch (ArgumentException)
                {
                    throw new ArgumentException("duplicate");
                }
            }

            return dictionary;
        }
    }
```

The deps.json file I'm pointing to has 69 RuntimeLibraries in it, which is a relatively small .deps.json file.

With the following results:

|                         Method |     Mean |     Error |    StdDev | Ratio | Allocated |
|------------------------------- |---------:|----------:|----------:|------:|----------:|
| LibraryCollectionToDictionary1 | 8.436 us | 0.1090 us | 0.0910 us |  1.00 |      5 KB |
| LibraryCollectionToDictionary2 | 4.797 us | 0.0632 us | 0.0591 us |  0.57 |      5 KB |

**Review by eerhardt — APPROVED** [review]
Thanks @eocrawford for the contribution. This should help diagnose these issues in the future.
