### PR TITLE
[mono] Unify invoke code with coreclr

### LINKED ISSUE #67457: Update runtime Invoke exception handling
### Description

There are some exception behavioral changes in the native Core Invoke implementation in https://github.com/dotnet/runtime/pull/66357. Previously, exceptions thrown by the native code were not wrapped with `TargetInvocationException` and now they are. Mono should uptake these changes.

The changes are consistent with other exceptions thrown when Invoking - mainly exceptions are not wrapped when the caller's parameters are bad (wrong number of arguments, or wrong types) but are wrapped when the Target throws or does something incorrectly. This change also facilitates the design to move native code to managed by performing validation logic on the managed side and allows for other implementations of Invoke (such as future IL-emit version) to be simpler.

A breaking change issue will be created for consumers, but for now the Mono runtime should adjust to this by not catching these exceptions specially and let the normal `TargetInvocationException` logic wrap the exceptions.

### Reproduction Steps

See the tests flags with `ActiveIssue` for this issue.

### Expected behavior

The Mono runtime should let exceptions be re-thrown as `TargetInvocationException`.

### Actual behavior

The Mono runtime does not re-throw as `TargetInvocationException`.

### Regression?

Not really; semantic \ breaking change.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### LINKED ISSUE #68928: Mono work necessary to support IL-based invoke
Per this [issue ](https://github.com/dotnet/runtime/pull/67917)and [comment](https://github.com/dotnet/runtime/pull/67917#issuecomment-1112282560) here's the Mono work necessary to support the IL Emit fast-path. This effort will also be used to support the planned new Invoke() APIs to support byref-like types.

### Native changes
In `RuntimeMethodInfo.InternalInvoke`, apply the same changes as made to CoreClr's `RuntimeMethodHandle::Invoke` including:
- Pass parameters byref instead of by `System.Object`. This primarily means value types are no longer required to be boxed; this will be leveraged more when we support byref-like types later. Also, when we do that the return value and `obj` parameter will also need to be changed to be byref or use `TypedReference` pending design. 
- All conversions removed such as from Int to Long (moved to managed).
- No exception handling for `TargetInvocationException` (moved to managed). Also see the [breaking change](https://github.com/dotnet/docs/issues/29199) issue.
  - A `null` byref for a byref-like parameter should just throw now instead of passing `default()`.
  - Invalid ctor parameters for size should just throw wrapped in TIE instead of outside the TIE.
  - See https://github.com/dotnet/runtime/issues/67457
- `Nullable<T>` is now passed as a true `Nullable<T>`, not as a boxed `T` or `null`.

### Managed changes
- Change the various Invoker and shared invoke code to remove Mono special casing.
  - Search for `// Temporary until Mono is updated` and remove the corresponding `#if`s.
  - In the Method and Constructor invoker classes, Mono should use the same exception handling as Core which is basically `try\catch(Exception)` without any one-off catches for misc exception types.
- Update `RuntimeType.CheckValue()` (see the Core implementation)
  - Perform validation and conversions that were probably handled in native code before; Core added `InvokeUtils.ConvertOrWiden` which should be able to be re-used.
  - Add special `Nullable<T>` calls to create true nullables (see the Core implementation)

### PR DESCRIPTION
**Pull request by BrzVlad**
Unification of invoke paths enables use of IL Emit Invoke also on mono.

InternalInvoke now receives arguments byref, enabling support for future APIs making use of this.

Fixes https://github.com/dotnet/runtime/issues/68928
Fixes https://github.com/dotnet/runtime/issues/67457

### CODE REVIEW

File: src/mono/mono/metadata/icall.c [hunk 1]
```diff
@@ -1795,6 +1799,41 @@ ves_icall_RuntimeTypeHandle_IsInstanceOfType (MonoQCallTypeHandle type_handle, M
 	return !MONO_HANDLE_IS_NULL (inst);
 }
 
+MonoObjectHandle
+ves_icall_RuntimeMethodHandle_ReboxToNullable (MonoObjectHandle obj, MonoQCallTypeHandle type_handle, MonoError *error)
+{
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:1804]: These two can return a value using a MonoObjectHandleOnStack.

File: src/mono/mono/metadata/icall.c [hunk 2]
```diff
@@ -3360,13 +3399,63 @@ ves_icall_RuntimeMethodInfo_GetGenericArguments (MonoReflectionMethodHandle ref_
 	return res;
 }
 
+static gpointer
+invoke_byrefs_extract_argument (gpointer *params_byref, int i, MonoType *t, MonoError *error)
+{
+	gpointer result = NULL;
+	error_init (error);
+again:
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:3407]: No need to init the error.

File: src/mono/mono/metadata/icall.c [hunk 3]
```diff
@@ -3436,19 +3524,87 @@ ves_icall_InternalInvoke (MonoReflectionMethodHandle method_handle, MonoObjectHa
...
+			}
+		}
+
+		if (!obj) {
+			MonoObjectHandle obj_h = mono_object_new_handle (m->klass, error);
+			goto_if_nok (error, return_null);
+			obj = MONO_HANDLE_RAW (obj_h);
+			g_assert (obj); /*maybe we should raise a TLE instead?*/
+			if (m_class_is_valuetype (m->klass))
+				o = (MonoObject *)mono_object_unbox_internal ((MonoObject *)obj);
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:3570]: This cast is not needed.

File: src/mono/mono/metadata/icall.c [hunk 4]
```diff
@@ -3436,19 +3524,87 @@ ves_icall_InternalInvoke (MonoReflectionMethodHandle method_handle, MonoObjectHa
...
+				result = mono_value_box_checked (m_class_get_cast_class (m->klass), pa [0], error);
+				goto exit;
+			}
+		}
+
+		if (!obj) {
+			MonoObjectHandle obj_h = mono_object_new_handle (m->klass, error);
+			goto_if_nok (error, return_null);
+			obj = MONO_HANDLE_RAW (obj_h);
+			g_assert (obj); /*maybe we should raise a TLE instead?*/
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:3568]: Its ok to assert, obj==null can't happen.

File: src/mono/mono/metadata/icall.c [hunk 5]
```diff
@@ -3436,19 +3524,87 @@ ves_icall_InternalInvoke (MonoReflectionMethodHandle method_handle, MonoObjectHa
...
+			if (m_class_is_valuetype (m->klass))
+				o = (MonoObject *)mono_object_unbox_internal ((MonoObject *)obj);
+			else
+				o = obj;
+		} else if (m_class_is_valuetype (m->klass)) {
+			MonoObjectHandle obj_h = mono_value_box_handle (m->klass, obj, error);
+			goto_if_nok (error, return_null);
+			obj = MONO_HANDLE_RAW (obj_h);
+		}
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:3577]: Shouldn't this set 'o' ?

File: src/mono/mono/metadata/icall.c [hunk 6]
```diff
@@ -3436,19 +3524,87 @@ ves_icall_InternalInvoke (MonoReflectionMethodHandle method_handle, MonoObjectHa
...
+				goto_if_nok (error, return_null);
+			} else {
+				result = mono_value_box_checked (m_class_get_cast_class (m->klass), pa [0], error);
+				goto exit;
+			}
+		}
+
+		if (!obj) {
+			MonoObjectHandle obj_h = mono_object_new_handle (m->klass, error);
+			goto_if_nok (error, return_null);
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:3566]: Might be better to use the non _handle functions and MONO_HANDLE_PIN () in this function.

File: src/mono/mono/metadata/icall.c [hunk 7]
```diff
@@ -3436,19 +3524,87 @@ ves_icall_InternalInvoke (MonoReflectionMethodHandle method_handle, MonoObjectHa
...
+		if (mono_class_is_nullable (m->klass)) {
+			if (m->flags & METHOD_ATTRIBUTE_STATIC) {
+				obj = NULL;
+			} else {
+				/* Convert the unboxed vtype into a Nullable structure */
+				MonoObjectHandle nullable_h = mono_object_new_handle (m->klass, error);
+				goto_if_nok (error, return_null);
+				MonoObject* nullable = MONO_HANDLE_RAW (nullable_h);
+
+				MonoObjectHandle boxed_h = mono_value_box_handle (m_class_get_cast_class (m->klass), obj, error);
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:3591]: Might be easier to use mono_nullable_init_unboxed ().

**Comment by srxqds** [comment]
hi, this will merge to rc1?

**Comment by marek-safar** [comment]
Could you look into fixing this for DynamicMethod as well?

**Comment by BrzVlad** [comment]
> Could you look into fixing this for DynamicMethod as well?

Not sure what you mean by this. Most of the code for invoking a DynamicMethod is shared now.

**Comment by BrzVlad** [comment]
> > Not sure what you mean by this. Most of the code for invoking a DynamicMethod is shared now.
> 
> Code like
> 
> https://github.com/dotnet/runtime/blob/561b0974793ba91936f151eab07875938e853694/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/DynamicMethod.CoreCLR.cs#L160

@marek-safar It's not quite clear to me why that code is like that. Seems like duplicated code from `RuntimeMethodInfo` which mono calls directly instead. I'd rather leave it out of this PR anyway.

File: src/mono/System.Private.CoreLib/src/System/Collections/Generic/EqualityComparer.Mono.cs [hunk 8]
```diff
@@ -39,6 +39,11 @@ private static EqualityComparer<T> CreateComparer()
             {
                 return (EqualityComparer<T>)(object)(new ByteEqualityComparer());
             }
+            else if (t == typeof(string))
```
Comment (AaronRobinsonMSFT) [inline src/mono/System.Private.CoreLib/src/System/Collections/Generic/EqualityComparer.Mono.cs:42]: There is a comment on line 34 about "METHOD-TO-IR.C should be kept in sync. Is that still valid?

File: src/mono/mono/mini/mini-amd64.c [hunk 9]
```diff
@@ -2544,7 +2544,7 @@ mono_arch_emit_setret (MonoCompile *cfg, MonoMethod *method, MonoInst *val)
 typedef struct {
 	MonoMethodSignature *sig;
 	CallInfo *cinfo;
-	int nstack_args, nullable_area;
+	int nstack_args;
```
[the remark this answers is not in the document]
Comment (BrzVlad) [reply src/mono/mono/mini/mini-amd64.c:2547]: @vargaz This PR removes special handling of nullables from the runtime invoke paths. The corresponding change in runtime invoke wrapper is made in `emit_invoke_call` in commit `[mono] Implement new version of InternalInvoke icall`. There is a risk for breaking changes with embedders but I don't think it is worthwhile to maintain separate versions of invoke wrappers and code.

[the remark this answers is not in the document]
Comment (lambdageek) [reply src/mono/mono/mini/mini-amd64.c:2547]: > There is a risk for breaking changes with embedders 

How does this affect embedders? Do they need to manually box nullable arguments before calling `mono_runtime_invoke`? That seems like a pretty big change

[the remark this answers is not in the document]
Comment (BrzVlad) [reply src/mono/mono/mini/mini-amd64.c:2547]: @lambdageek So consider the case where we do a runtime invoke into a method receiving a nullable argument. This method will expect to receive a nullable structure. The old Invoke API would receive an array of objects, so the caller of the Invoke API, when converting the argument into an object it will result a boxed value type. The invoke wrapper used to receive this boxed value type and it would unbox it into a nullable structure to pass it along. The new API would pass directly a ref to the nullable structure to the `InternalInvoke`, so the runtime invoke wrapper doesn't need to do anything else.

Now considering the case for embedders, this behavior of unboxing a valuetype into a nullable structure doesn't really seem to be documented and I figure it was just something for us to easily support the InternalInvoke behavior. The documentation of `mono_runtime_invoke` states that it should receive a `MonoObject*` for objects and a pointer to the value type for valuetypes, so this implementation still follows the documentation for the invokes. It just stops supporting, the apparently undocumented, behavior of allowing to pass a boxed valuetype as an argument for a method receiving a nullable.

[the remark this answers is not in the document]
Comment (BrzVlad) [reply src/mono/mono/mini/mini-amd64.c:2547]: I think we could also do the conversion from boxed vt to unboxed nullable only for `mono_runtime_invoke` and `mono_runtime_invoke_array`, just to preserve behavior

[the remark this answers is not in the document]
Comment (vargaz) [reply src/mono/mono/mini/mini-amd64.c:2547]: That should work.

File: src/mono/mono/metadata/class-setup-vtable.c [hunk 10]
```diff
@@ -1065,7 +1065,7 @@ handle_dim_conflicts (MonoMethod **vtable, MonoClass *klass, GHashTable *conflic
 		int nentries = 0;
 		MonoMethod *impl = NULL;
 		for (l = entries; l; l = l->next) {
-			if (l->data) {
+			if (l->data && l->data != impl) {
 				nentries ++;
```
Comment (vargaz) [inline src/mono/mono/metadata/class-setup-vtable.c:1069]: Is this part of the PR ?

Comment (BrzVlad) [reply src/mono/mono/metadata/class-setup-vtable.c:1069]: looks like rebase leftover

File: src/mono/mono/metadata/icall.c [hunk 11]
```diff
@@ -1795,6 +1799,48 @@ ves_icall_RuntimeTypeHandle_IsInstanceOfType (MonoQCallTypeHandle type_handle, M
...
+	MonoType *type = type_handle.type;
+	MonoClass *klass = mono_class_from_mono_type_internal (type);
+
+	mono_class_init_checked (klass, error);
+	if (!is_ok (error)) {
+		HANDLE_ON_STACK_SET (res_handle, NULL);
+		return;
+	}
+
+	MonoObjectHandle res = mono_object_new_handle (klass, error);
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:1814]: This could use the newer way of handles, i.e. using raw object references and MONO_HANDLE_PIN ().

File: src/mono/mono/metadata/icall.c [hunk 12]
```diff
@@ -1795,6 +1799,48 @@ ves_icall_RuntimeTypeHandle_IsInstanceOfType (MonoQCallTypeHandle type_handle, M
...
+	MonoClass *klass = vtable->klass;
+
+	if (!mono_class_is_nullable (klass)) {
+		HANDLE_ON_STACK_SET (res_handle, MONO_HANDLE_RAW (obj));
+		return;
+	}
+
+	gpointer vbuf = mono_object_unbox_internal (MONO_HANDLE_RAW (obj));
+	MonoObjectHandle res = mono_nullable_box_handle (vbuf, klass, error);
+
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:1840]: Ditto.

File: src/mono/mono/metadata/class-setup-vtable.c (hunk 10 above)
Comment (BrzVlad) [reply src/mono/mono/metadata/class-setup-vtable.c:1069]: it was actually a bug that I forgot that I fixed

**Comment by BrzVlad** [comment]
@vargaz @lambdageek I'm not aware of any issues with this PR and I also updated the code to preserve behavior with embedders when passing nullables. Could I get a final review on this ?

File: src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs [hunk 13]
```diff
@@ -90,7 +90,25 @@ internal bool IsNullHandle()
             return value == IntPtr.Zero;
         }
 
-        // Temporary placeholder until Mono adds support for supporting boxing true Nullables.
-        internal static object? ReboxFromNullable(object? src) => src;
+        [MethodImplAttribute(MethodImplOptions.InternalCall)]
+        internal static extern void ReboxFromNullable (object? src, ObjectHandleOnStack res);
+
```
Comment (vargaz) [inline src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs:95]: This could be private ?

File: src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs [hunk 14]
```diff
@@ -90,7 +90,25 @@ internal bool IsNullHandle()
...
+        [MethodImplAttribute(MethodImplOptions.InternalCall)]
+        internal static extern void ReboxToNullable (object? src, QCallTypeHandle destNullableType, ObjectHandleOnStack res);
+
```
Comment (vargaz) [inline src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs:98]: Ditto.

File: src/mono/mono/metadata/class-setup-vtable.c (hunk 10 above)
Comment (vargaz) [inline src/mono/mono/metadata/class-setup-vtable.c:1069]: How is this related to the PR ?

File: src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs [hunk 15]
```diff
@@ -90,7 +90,25 @@ internal bool IsNullHandle()
...
+        internal static object ReboxFromNullable (object? src)
```
Comment (vargaz) [inline src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs:99]: Why are these methods in RuntimeMethodHandle ?

File: src/mono/mono/metadata/icall.c [hunk 16]
```diff
@@ -2089,31 +2136,9 @@ ves_icall_RuntimeFieldInfo_SetValueInternal (MonoReflectionFieldHandle field, Mo
 			MonoGenericClass *gclass = type->data.generic_class;
 			g_assert (!gclass->context.class_inst->is_open);
 
-			if (mono_class_is_nullable (mono_class_from_mono_type_internal (type))) {
-				MonoClass *nklass = mono_class_from_mono_type_internal (type);
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:2093]: Why is this removed ?

File: src/mono/mono/metadata/icall.c [hunk 17]
```diff
@@ -6138,6 +6163,25 @@ ves_icall_System_RuntimeType_CreateInstanceInternal (MonoQCallTypeHandle type_ha
 	return mono_object_new_handle (klass, error);
 }
 
+/* Only used for value types */
+MonoObjectHandle
+ves_icall_System_RuntimeType_AllocateValueType (MonoQCallTypeHandle type_handle, MonoObjectHandle value_h, MonoError *error)
+{
```
Comment (vargaz) [inline src/mono/mono/metadata/icall.c:6169]: This could return a result using a MonoObjectHandleOnStack.

File: src/mono/mono/mini/mini-amd64.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (vargaz) [reply src/mono/mono/mini/mini-amd64.c:2547]: So the nullable behavior is going to be handled in the invoke wrapper, so the dyn call code doesn't need these special cases anymore ?

File: src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs (hunk 15 above)
Comment (BrzVlad) [reply src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs]: Just because they live in the same class on CoreCLR side

File: src/mono/mono/metadata/icall.c (hunk 16 above)
Comment (BrzVlad) [reply src/mono/mono/metadata/icall.c:2118]: The nullable boxing is no longer done here but from managed code via the Rebox{To/From}Nullable, from `RuntimeType.CheckValue`

File: src/mono/mono/metadata/class-setup-vtable.c (hunk 10 above)
Comment (BrzVlad) [reply src/mono/mono/metadata/class-setup-vtable.c:1069]: I stumbled across this bug after changing the invoke machinery. I don't remember exactly why the test was passing before.

File: src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs [hunk 18]
```diff
@@ -90,7 +90,24 @@ internal bool IsNullHandle()
             return value == IntPtr.Zero;
         }
 
-        // Temporary placeholder until Mono adds support for supporting boxing true Nullables.
-        internal static object? ReboxFromNullable(object? src) => src;
+        [MethodImplAttribute(MethodImplOptions.InternalCall)]
+        private static extern void ReboxFromNullable (object? src, ObjectHandleOnStack res);
```
Comment (marek-safar) [inline src/mono/System.Private.CoreLib/src/System/RuntimeMethodHandle.cs:94]: Are these same as https://github.com/dotnet/runtime/blob/main/src/mono/System.Private.CoreLib/src/System/Nullable.Mono.cs#L17-L39 ?

**Comment by BrzVlad** [comment]
can we merge this ?

**Review by vargaz — APPROVED** [review]
