### PR TITLE
[wasm][test] install handlers for unhandled exceptions on browser

### LINKED ISSUE #73330: [wasm] `test-main.js` needs an unhandled exception handler
When running tests with xharness on browser, we are not able to get the traces for uncaught exceptions. A handler for that can print the trace which can be usable by anyone looking at test logs.

```
[11:20:03] info: Starting:    System.Runtime.Tests.dll
[11:21:00] fail: [out of order message from the browser]: http://127.0.0.1:49197/dotnet.js 1880:6 Uncaught
[11:21:00] fail: [out of order message from the browser]: http://127.0.0.1:49197/dotnet.js 1880:6 Uncaught
[11:21:00] fail: [out of order message from the browser]: http://127.0.0.1:49197/dotnet.js 1880:6 Uncaught
[11:34:33] fail: Tests timed out. Killing driver service pid 7840
[11:34:33] fail: Application has finished with exit code TIMED_OUT but 0 was expected
```

Also, note the timings above. `xharness` continues to wait for 13mins after the `uncaught` exception, because the app did not signal that it had crashed.

### PR DESCRIPTION
**Pull request by pavelsavara**
Fixes https://github.com/dotnet/runtime/issues/73330

### CODE REVIEW

File: src/mono/wasm/runtime/run-outer.ts [hunk 1]
```diff
@@ -57,6 +57,35 @@ class HostBuilder implements DotnetHostBuilder {
...
+                    }
+                });
+                window.addEventListener("error", (event: ErrorEvent) => {
+                    event.preventDefault();
+                    try {
+                        mono_exit(1, event.error);
+                    } catch (err) {
+                        // no not re-throw from the error handler
+                    }
+                });
```
Comment (maraf) [inline src/mono/wasm/runtime/run-outer.ts:80]: Can we share the handler?

```suggestion
                const handler = (event: Event) => {
                    event.preventDefault();
                    try {
                        mono_exit(1, event.reason);
                    } catch (err) {
                        // no not re-throw from the unhandledrejection handler
                    }
                }
                window.addEventListener("unhandledrejection", handler);
                window.addEventListener("error", handler);
```

File: src/mono/wasm/runtime/run-outer.ts [hunk 2]
```diff
@@ -57,6 +57,35 @@ class HostBuilder implements DotnetHostBuilder {
         }
     }
 
+    // internal
+    withExitOnUnhandledError(): DotnetHostBuilder {
+        try {
+            // it seems that emscripten already does the right thing for NodeJs and that there is no good solution for V8 shell.
+            if (ENVIRONMENT_IS_WEB) {
```
Comment (maraf) [inline src/mono/wasm/runtime/run-outer.ts:64]: Should we throw or log warning on other platforms in these platform-specific methods?

File: src/mono/wasm/runtime/run-outer.ts (hunk 1 above)
Comment (maraf) [reply src/mono/wasm/runtime/run-outer.ts:80]: Oh, I see, `event.error` vs `error.reason`.

Comment (maraf) [reply src/mono/wasm/runtime/run-outer.ts:80]: Updated

**Review by maraf — APPROVED** [review]
