### PR TITLE
Fix FailFast message formatting race

### LINKED ISSUE #47096: Test failed: baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
Job : [runtime-coreclr jitstressregs 20210117.1](https://dev.azure.com/dnceng/public/_build/results?buildId=954707&view=results)

Failed test : 
```
CoreCLR OSX x64 Checked jitstressregs0x1000 @ OSX.1013.Amd64.Open
        - baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
```
Error message:
```
Process terminated. Parallel crash in thread 6!

{0x1bc56e-0x10e475d40} ASSERT [DEBUG  ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
   at System.Environment.FailFast(System.String)
   at ParallelCrash.CrashInParallel()
   at System.Threading.Thread.StartCallback()
../ParallelCrash/ParallelCrash.sh: line 388: 47592 Trace/BPT trap: 5       $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /private/tmp/helix/working/B90009AF/w/B8D909CB/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/private/tmp/helix/working/B90009AF/w/B8D909CB/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '2'
BEGIN EXECUTION
/tmp/helix/working/B90009AF/p/corerun ParallelCrash.dll '2'
Expected: 134
Actual: 133
END EXECUTION - FAILED
Expected: 0
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/B90009AF/p
> /private/tmp/helix/working/B90009AF/w/B8D909CB/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh

stack trace:
at baseservices_exceptions._simple_ParallelCraWorkerThreads_ParallelCraWorkerThreads_._simple_ParallelCrashWorkerThreads_ParallelCrashWorkerThreads_sh()
```

### PR DESCRIPTION
**Pull request by janvorli**
SystemNative::GenericFailFast uses a global buffer for messages shorter than certain size.
When multiple threads call FailFast at the same time, they all use the same buffer,
overwriting each other's message. That leads to a problem on Unix when the message is
converted to UTF-8 using two calls to WideCharToMultiByte and another thread changes
the message to a longer one between those two calls. So the buffer size the first
call determines is no longer sufficient.

Close #47096

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

File: src/coreclr/classlibnative/bcltype/system.cpp [hunk 1]
```diff
@@ -273,19 +277,22 @@ void SystemNative::GenericFailFast(STRINGREF refMesgString, EXCEPTIONREF refExce
...
 
-    if (cchMessage == 0) {
+    if (pszMessage == NULL) {
+        WszOutputDebugString(W("CLR: Managed code called FailFast, but there is not enough memory to print the supplied message.\r\n"));
+    }
+    else if (cchMessage == 0) {
         WszOutputDebugString(W("CLR: Managed code called FailFast without specifying a reason.\r\n"));
     }
     else {
         WszOutputDebugString(W("CLR: Managed code called FailFast, saying \""));
```
Comment (danmoseley) [inline src/coreclr/classlibnative/bcltype/system.cpp:288]: Not your change, but to be consistent with the other CLR termination messages, this would be `...called FailFast. "));`. They all suffix the message after a period.

**Comment by janvorli** [comment]
I actually made a mistake in handling the OOM case, fixing it now.

**Comment by janvorli** [comment]
I've fixed the issue and also made the message in the OOM case to propagate to the `EEPolicy::HandleFatalError` so that it is actually printed to the user. With the previous state, the message would be just printed in the debugger and the message a user would see would be empty.

File: src/coreclr/classlibnative/bcltype/system.cpp (hunk 1 above)
Comment (danmoseley) [reply src/coreclr/classlibnative/bcltype/system.cpp:288]: I suggest to keep it on one line (ie, space instead of `\r\n`). That is the existing pattern and it works well with logs and concurrent console output where the two lines can otherwise get separated.

**Comment by danmoseley** [comment]
Just curious, in what circumstances do we end up with this "CLR: ... " fail fast message, as opposed to what I get from `Environment.FailFast(...)`, eg.,
```
Process terminated. Some message here.
   at System.Environment.FailFast(System.String)
   at <Program>$.<Main>$(System.String[])
```

**Comment by janvorli** [comment]
> Just curious, in what circumstances do we end up with this "CLR: ... " fail fast message

This is just OutputDebugString message in the debugger. It is not printed to the console. The fixed function calls EEPolicy::HandleFatalError at the end which does the regular console printing.
