### PR TITLE
Fix COM + dynamic tests

### LINKED ISSUE #33611: Test failure: Interop\\COM\\Dynamic\\Dynamic\\Dynamic.cmd
**Job:**
[runtime-coreclr jitstressregs:20200315.1](https://dev.azure.com/dnceng/public/_build/results?buildId=560117&view=results)
**Error message:**
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at DynamicClass.IDispatchInvoke(IntPtr, Int32, System.Runtime.InteropServices.ComTypes.INVOKEKIND, System.Runtime.InteropServices.ComTypes.DISPPARAMS ByRef, System.Runtime.InteropServices.Variant ByRef, Microsoft.CSharp.RuntimeBinder.ComInterop.ExcepInfo ByRef, UInt32 ByRef)
at Microsoft.CSharp.RuntimeBinder.ComInterop.UnsafeMethods.IDispatchInvoke(IntPtr, Int32, System.Runtime.InteropServices.ComTypes.INVOKEKIND, System.Runtime.InteropServices.ComTypes.DISPPARAMS ByRef, System.Runtime.InteropServices.Variant ByRef, Microsoft.CSharp.RuntimeBinder.ComInterop.ExcepInfo ByRef, UInt32 ByRef)
at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Microsoft.CSharp.RuntimeBinder.ComInterop.ComObject, Int32[])
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon) 
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon) 
at Dynamic.CollectionTest.Array() 
at Dynamic.CollectionTest.Run()
at Dynamic.Program.Main(System.String[])

Return code: 1
Raw output file: C:\h\w\B3270979\w\A25008FC\e\Interop\COM\Reports\Interop.COM\Dynamic\Dynamic\Dynamic.output.txt
Raw output:
BEGIN EXECUTION 
"C:\h\w\B3270979\p\corerun.exe" Dynamic.dll
Running BasicTest
Running CollectionTest
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B3270979\p
> C:\h\w\B3270979\w\A25008FC\e\Interop\COM\Dynamic\Dynamic\Dynamic.cmd
Expected: True
Actual: False
```
**Stack trace:**
`
at Interop_COM._Dynamic_Dynamic_Dynamic_._Dynamic_Dynamic_Dynamic_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 334
`
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=560117&view=ms.vss-test-web.build-test-results-tab&runId=17643978&resultId=100159&paneView=debug

### PR DESCRIPTION
**Pull request by elinor-fung**
Ref-counting fail...

Fix #33611

### CODE REVIEW

File: src/coreclr/tests/src/Interop/COM/Dynamic/Server/DispatchImpl.cpp [hunk 1]
```diff
@@ -44,6 +44,9 @@ HRESULT DispatchImpl::DoGetTypeInfo(UINT iTInfo, ITypeInfo** ppTInfo)
     if (iTInfo != 0)
         return DISP_E_BADINDEX;
 
+    assert(_typeInfo != nullptr);
+
+    _typeInfo->AddRef();
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/tests/src/Interop/COM/Dynamic/Server/DispatchImpl.cpp]: Instead of doing this the canonical approach of using `QueryInterface()` should be used to return a COM interface.

```c++
return _typeInfo->QueryInterface(__uuidof(*ppTInfo), (void**)ppTInfo);
```

Depending on compiler settings the following may also work.

```c++
return _typeInfo->QueryInterface(ppTInfo);
```

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/tests/src/Interop/COM/Dynamic/Server/DispatchImpl.cpp [hunk 2]
```diff
@@ -26,7 +26,7 @@ DispatchImpl::DispatchImpl(GUID guid, void *instance, const wchar_t* tlb)
 
 DispatchImpl::~DispatchImpl()
 {
-    if (_typeInfo != nullptr)
+    if (_typeLib != nullptr)
```
Comment (lpereira) [inline src/coreclr/tests/src/Interop/COM/Dynamic/Server/DispatchImpl.cpp]: Good catch.

Comment (elinor-fung) [reply src/coreclr/tests/src/Interop/COM/Dynamic/Server/DispatchImpl.cpp]: Oh, didn't even notice we actually have our own [`ComSmartPtr`](https://github.com/dotnet/runtime/blob/master/src/coreclr/tests/src/Interop/common/ComHelpers.h#L336).
