### PR TITLE
Share SingleFileTest publishing between test classes

### LINKED ISSUE #43316: Bundle_Is_Extracted test failing intermittently on Linux
<!-- runfo report start -->
Runfo Tracking Issue: [Bundle_Is_Extracted test failing intermittently on Linux](https://runfo.azurewebsites.net/tracking/issue/14)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[1306544](https://dev.azure.com/dnceng/public/_build/results?buildId=1306544)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 57707](https://github.com/dotnet/runtime/pull/57707)|Installer-coreclr-Linux_x64-Release|
|[1306544](https://dev.azure.com/dnceng/public/_build/results?buildId=1306544)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 57707](https://github.com/dotnet/runtime/pull/57707)|Installer-coreclr-Linux_musl_x64-Release|
|[1303326](https://dev.azure.com/dnceng/public/_build/results?buildId=1303326)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 57613](https://github.com/dotnet/runtime/pull/57613)|Installer-coreclr-Linux_musl_x64-Release|
|[1299064](https://dev.azure.com/dnceng/public/_build/results?buildId=1299064)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56501](https://github.com/dotnet/runtime/pull/56501)|Installer-coreclr-Linux_musl_x64-Release|
|[1298012](https://dev.azure.com/dnceng/public/_build/results?buildId=1298012)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 57274](https://github.com/dotnet/runtime/pull/57274)|Installer-coreclr-Linux_x64-Release|
|[1295343](https://dev.azure.com/dnceng/public/_build/results?buildId=1295343)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Linux_musl_x64-Release|
|[1295250](https://dev.azure.com/dnceng/public/_build/results?buildId=1295250)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 57471](https://github.com/dotnet/runtime/pull/57471)|Installer-coreclr-Linux_x64-Release|
|[1292506](https://dev.azure.com/dnceng/public/_build/results?buildId=1292506)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 57357](https://github.com/dotnet/runtime/pull/57357)|Installer-coreclr-Linux_x64-Release|
|[1289058](https://dev.azure.com/dnceng/public/_build/results?buildId=1289058)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 57155](https://github.com/dotnet/runtime/pull/57155)|Installer-coreclr-Linux_x64-Release|
|[1278169](https://dev.azure.com/dnceng/public/_build/results?buildId=1278169)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56907](https://github.com/dotnet/runtime/pull/56907)|Installer-coreclr-Linux_musl_x64-Release|
|[1276600](https://dev.azure.com/dnceng/public/_build/results?buildId=1276600)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56859](https://github.com/dotnet/runtime/pull/56859)|Installer-coreclr-Linux_x64-Release|
|[1272901](https://dev.azure.com/dnceng/public/_build/results?buildId=1272901)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Linux_musl_x64-Release|
|[1271025](https://dev.azure.com/dnceng/public/_build/results?buildId=1271025)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56714](https://github.com/dotnet/runtime/pull/56714)|Installer-coreclr-Linux_musl_x64-Release|
|[1270207](https://dev.azure.com/dnceng/public/_build/results?buildId=1270207)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56669](https://github.com/dotnet/runtime/pull/56669)|Installer-coreclr-Linux_x64-Release|
|[1270207](https://dev.azure.com/dnceng/public/_build/results?buildId=1270207)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56669](https://github.com/dotnet/runtime/pull/56669)|Installer-coreclr-Linux_musl_x64-Release|
|[1270083](https://dev.azure.com/dnceng/public/_build/results?buildId=1270083)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56669](https://github.com/dotnet/runtime/pull/56669)|Installer-coreclr-Linux_x64-Release|
|[1270083](https://dev.azure.com/dnceng/public/_build/results?buildId=1270083)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56669](https://github.com/dotnet/runtime/pull/56669)|Installer-coreclr-Linux_musl_x64-Release|
|[1268562](https://dev.azure.com/dnceng/public/_build/results?buildId=1268562)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56316](https://github.com/dotnet/runtime/pull/56316)|Installer-coreclr-Linux_x64-Release|
|[1268095](https://dev.azure.com/dnceng/public/_build/results?buildId=1268095)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56455](https://github.com/dotnet/runtime/pull/56455)|Installer-coreclr-Linux_musl_x64-Release|
|[1265180](https://dev.azure.com/dnceng/public/_build/results?buildId=1265180)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56324](https://github.com/dotnet/runtime/pull/56324)|Installer-coreclr-Linux_x64-Release|
|[1260507](https://dev.azure.com/dnceng/public/_build/results?buildId=1260507)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56363](https://github.com/dotnet/runtime/pull/56363)|Installer-coreclr-Linux_x64-Release|
|[1260448](https://dev.azure.com/dnceng/public/_build/results?buildId=1260448)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 56360](https://github.com/dotnet/runtime/pull/56360)|Installer-coreclr-Linux_x64-Release|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|4|19|

<!-- runfo report end -->

### PR DESCRIPTION
**Pull request by agocke**
Tests in the AppHost.Bundle.Tests assembly seem to randomly fail due to a race condition
with the file system. They try to create separate '0','1','2'... subdirectories to isolate
the published files for each test, but I think what's happening is that files may be
marked for deletion, but then not deleted until a later write. For instance, files in
'2' may be marked for deletion and some may fail a File.Exists check, which leads to
'2' being recreated, at which point deletion may occur, which will cause the current test
to fail due to a concurrent write operation.

This change tries to simplify the system by sharing the test state across all the classes
in the assembly, instead of per-class, and then cleaning up only when all of them are
finished executing.

Fixes #43316

### CODE REVIEW

**Review by vitek-karas — APPROVED** [review]

**Comment by vitek-karas** [comment]
I think that if your theory is correct then we should actually change the way TestFixtures are created in the test infra - instead of trying to reuse folders (`1`, `2`, ...) we should generate a random unique name (GUID?) each time - if one of the fixtures fails to delete itself properly due to file system races it will leave garbage on disk, but it will NOT fail the tests.

**Comment by agocke** [comment]
I can do that too -- GUID works but is probably overkill tbh. There's a GetTempFileName that's probably sufficient for lower levels of contention.

I'll add that in a second commit

**Comment by elinor-fung** [comment]
+1 for @vitek-karas's suggestion for changing how we create the new path for test fixtures. If we do that, we shouldn't need to have the collection grouping, right? (So we can keep running the tests in parallel to avoid increasing test run times?)

That approach should also handle other cases like the StaticHost tests (failed in this PR: https://dev.azure.com/dnceng/public/_build/results?buildId=906837&view=ms.vss-test-web.build-test-results-tab&runId=28928456&resultId=100001&paneView=debug) - assuming your theory applies to that as well

**Comment by danmosemsft** [comment]
@JeremyKuhne just curious, does this theory match your knowledge of how filesystems can work on Linux? I remember something similar on Windows.

**Comment by JeremyKuhne** [comment]
> does this theory match your knowledge of how filesystems can work on Linux?

Historically Windows marked files for deletion and would remove them once all file handles were closed. That was recently changed so that the file is immediately moved to a new, "hidden" entry to open up the named location, specifically to better support Linux scenarios.

`File.Exists` is particularly evil, as @jaredpar will happily attest to. It returns `true` for "this existed at some point after you asked me" and  `false` for "I can't tell you if it exists". It's use is often a red flag that code will not handle contention. :)

Best practice for tests is to _always_ use a randomly generated sub-folder name. `Path.GetRandomFileName()` is a safe enough bet to avoid contention and only needs 12 characters (vs 36 with a guid).

File: src/installer/tests/TestUtils/TestArtifact.cs [hunk 1]
```diff
@@ -70,22 +78,23 @@ public virtual void Dispose()
...
+                var artifactPath = Path.Combine(parentPath, artifactName);
                 try
                 {
                     File.Open(lockPath, FileMode.CreateNew, FileAccess.Write).Dispose();
-                    return path;
-                } catch
+                }
+                catch
                 {
                     // Lock file cannot be created, potential collision
```
Comment (vitek-karas) [inline src/installer/tests/TestUtils/TestArtifact.cs:93]: There should probably be some retry count and a escape/failure when nothing works. For example if the test doesn't have access right to write the file (for some weird reason) it would hang. It would better to get a clear error message (with the last exception in it). By now I expect the unexpected from CI 😉

File: src/installer/tests/TestUtils/TestArtifact.cs [hunk 2]
```diff
@@ -57,7 +57,15 @@ public virtual void Dispose()
...
-                Directory.Delete(Location, true);
+                try
+                {
+                    Directory.Delete(Location, true);
+
+                    // Delete lock file last
+                    Debug.Assert(!Directory.Exists(Location));
+                    var lockPath = Directory.GetParent(Location) + ".lock";
+                    File.Delete(lockPath);
+                } catch {}
```
Comment (vitek-karas) [inline src/installer/tests/TestUtils/TestArtifact.cs:68]: Can we at least write out to console in the case the delete fails (non-error, but get some log)? It may come handy when we're to diagnose the next super-weird behavior in CI.

File: src/installer/tests/TestUtils/TestArtifact.cs (hunk 1 above)
Comment (agocke) [reply src/installer/tests/TestUtils/TestArtifact.cs:93]: I usually find hangs slightly easier to diagnose -- Roslyn used to find all the test exes that were still running and create minidumps for them. But if that infrastructure doesn't work so well in runtime I can produce a log message instead.

File: src/installer/tests/TestUtils/TestArtifact.cs (hunk 2 above)
Comment (agocke) [reply src/installer/tests/TestUtils/TestArtifact.cs:68]: Sure. However, I don't think Delete failing should be a problem -- it just means we can't clean up, which shouldn't be fatal.
