### PR TITLE
Fix ProfileEnter when called on a foreign thread

### LINKED ISSUE #115617: ProfileEnter crashes for UnmanagedCallersOnly methods invoked from foreign threads not registered with runtime yet.
### Discussed in https://github.com/dotnet/runtime/discussions/115511

<div type='discussions-op-text'>

<sup>Originally posted by **AlexeiNaabal** May 13, 2025</sup>
Greetings coreclr devs.  

This question is about CoreCLR profiler components and native thread that created outside coreclr runtime.

Right now we are trying to add custom profiler to an embedded coreclr runtime, and it works as expected when under single thread mode, but meets some thread exits check failure under multi thread mode.   

The multi thread scenario is like:
We launched the embedded coreclr runtime with hostfxr api, then invoke some native function to feed native async task into a native task producer with managed function callback pointer for task consumer to invoke when task finished. When interacting with the task producer, we are under main thread so everything works fine.

The producer create native thread that the coreclr runtime is not aware of, like async loading resources on native code, once load done, pass the loaded resource to the managed function callback that hooked before.  That means we have a native thread invoking managed code, it works as expected too.  

Then we enable a coreclr profiler that implemented the ICorProfiler interface, and redo the process above, it triggers the runtime enter ProfileEnter, where there are thread valid check in proftoeeinterfaceimpl.cpp, like 
```c++
GCX_COOP_THREAD_EXISTS(GET_THREAD());
// where expanded with
inline Thread* GetThread()
{
    Thread* pThread = gCurrentThreadInfo.m_pThread;
    _ASSERTE(pThread);  // pThread will be invalid as currently we are in the native thread that created outside
    return pThread;
}
```
and the assert will fail as the pThread is invalid value like 0xc0000005. By looking at the Thread info in visual studio, we confirm that current thread is a host's native thread.  

We would like to know if coreclr exposes api to register or attach the native thread to runtime before the ProfileEnter stage, to have the gCurrentThreadInfo contains necessary thread info representing the thread, other than invalid value?

</div>

### PR DESCRIPTION
**Pull request by janvorli**
When ProfileEnter is called on a foreign thread that the runtime has not seen yet, which can happen for UnmanagedCallersOnly marked methods, it crashes in the GCX_COOP_THREAD_EXISTS(GET_THREAD()); That was left in by accident in my change I've made a long time ago and should not be there.
This change removes that switch, we switch to cooperative mode later in the ProfileEnter and setup the thread for runtime before that.

Close #115617

### CODE REVIEW

File: src/coreclr/vm/proftoeeinterfaceimpl.cpp [hunk 1]
```diff
@@ -10666,9 +10666,7 @@ void __stdcall ProfilerUnmanagedToManagedTransitionMD(MethodDesc *pMD,
 // These do a lot of work for us, setting up Frames, gathering arg info and resolving generics.
   //*******************************************************************************************
 
-HCIMPL2_RAW(EXTERN_C void, ProfileEnter, UINT_PTR clientData, void * platformSpecificHandle)
-GCX_COOP_THREAD_EXISTS(GET_THREAD());
-HCIMPL_PROLOG(ProfileEnter)
+HCIMPL2(EXTERN_C void, ProfileEnter, UINT_PTR clientData, void * platformSpecificHandle)
```
Comment (jkotas) [inline src/coreclr/vm/proftoeeinterfaceimpl.cpp:10669]: Should we fix `ProfileLeave` to look the same?

Comment (janvorli) [reply src/coreclr/vm/proftoeeinterfaceimpl.cpp:10669]: Is it possible that the ProfileLeave would get called without the ProfileEnter? It seemed to me that the ProfileEnter would setup the thread and ProfileLeave would then always have it set up already.

Comment (jkotas) [reply src/coreclr/vm/proftoeeinterfaceimpl.cpp:10669]: Right.

I meant that ProfileLeave looks like this currenly:

```
HCIMPL2_RAW(EXTERN_C void, ProfileLeave, UINT_PTR clientData, void * platformSpecificHandle)
GCX_COOP();
HCIMPL_PROLOG(ProfileLeave)
```

Should it be changed to just this:

`HCIMPL2(EXTERN_C void, ProfileLeave, UINT_PTR clientData, void * platformSpecificHandle)`

Comment (janvorli) [reply src/coreclr/vm/proftoeeinterfaceimpl.cpp:10669]: Ah, so we would move the GCX_COOP inside of the body, makes sense.

Comment (janvorli) [reply src/coreclr/vm/proftoeeinterfaceimpl.cpp:10669]: Ah, I guess the GCX_COOP is not needed as the ProfileLeave is always called in coop mode?

Comment (jkotas) [reply src/coreclr/vm/proftoeeinterfaceimpl.cpp:10669]: I would expect it to be symmetric with `ProfileEnter`. If `ProfileEnter` needs `GCX_COOP`, `ProfileLeave` should have it too.   My comment was primarily about `HCIMPL2` vs. `HCIMPL2_RAW` difference.

So: 
```
HCIMPL2(EXTERN_C void, ProfileEnter, UINT_PTR clientData, void * platformSpecificHandle)
{
    FCALL_CONTRACT;

    GCX_COOP();
...
````

**Review by jkotas — APPROVED** [review]

**Review by noahfalk — APPROVED** [review]
thanks @janvorli!
