### PR TITLE
JIT: Expand loop detection in if-conversion

### LINKED ISSUE #82106: Regressions in System.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock

### PR DESCRIPTION
**Pull request by jakobbotsch**
The BB weight approach does not detect unnatural loops.

Fix #82106

For more context, see https://github.com/dotnet/runtime/issues/82106#issuecomment-1431474418

### CODE REVIEW

**Comment by jakobbotsch** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=173049&view=ms.vss-build-web.run-extensions-tab)

Surprisingly, not too impactful. cc @dotnet/jit-contrib PTAL @a74nh @AndyAyersMS
Ideally we should be smarter and allow some if-conversion within loops, but I'm not sure what the right conditions would be and it's unlikely we even have the information available. Presumably the analysis would need to take into account that if-conversion can introduce new data/control-flow dependencies across loop iterations.

**Review by AndyAyersMS — APPROVED** [review]

File: src/coreclr/jit/ifconversion.cpp [hunk 1]
```diff
@@ -769,6 +760,25 @@ bool OptIfConversionDsc::optIfConvert()
...
+    if (!m_comp->compStressCompile(Compiler::STRESS_IF_CONVERSION_INNER_LOOPS, 25))
+    {
+        // Don't optimise the block if it is inside a loop
+        // When inside a loop, branches are quicker than selects.
+        // Detect via the block weight as that will be high when inside a loop.
+        if (m_startBlock->getBBWeight(m_comp) > BB_UNITY_WEIGHT)
+        {
+            JITDUMP("Skipping if-conversion inside loop (via weight)\n");
+            return false;
+        }
```
Comment (BruceForstall) [inline src/coreclr/jit/ifconversion.cpp:772]: Would it be better to leave this "cheap" weight check first in the function, and only insert the "expensive" check here, after the long sequence of potentially expensive (appearing) checks above?

Comment (jakobbotsch) [reply src/coreclr/jit/ifconversion.cpp:772]: I actually tried this locally, but I did not see any impact from moving the cheap check.

Comment (jakobbotsch) [reply src/coreclr/jit/ifconversion.cpp:772]: It seems like that would do the `optReachable` check before identifying the candidate which is what I wanted to avoid, as the flow-graph walk is expensive. Also, it is using `m_finalBlock` which is found as part of identifying the candidate. I moved the other check to simplify the code (as it does not have noticeable impact).

Of course if the flow graph walk was prohibitively expensive we could just compute reachability sets in this phase, but since the TP impact of this approach didn't turn out too bad I think we can leave it like this.

Comment (a74nh) [reply src/coreclr/jit/ifconversion.cpp:772]: ah, didn't spot the use of final block, ok, agreed, leave as is.

**Comment by a74nh** [comment]
I'd be curious to see any diffs or performance changes for Arm64. Otherwise looks good to me.

**Comment by jakobbotsch** [comment]
> I'd be curious to see any diffs or performance changes for Arm64. Otherwise looks good to me.

Let's see during perf triage. FWIW, the benchmark I looked at originally regressed with if-conversion on arm64 as well: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_arm64_ubuntu%2020.04%2fSystem.Text.RegularExpressions.Tests.Perf_Regex_Industry_RustLang_Sherlock.Count(Pattern%3a%20%22aei%22%2c%20Options%3a%20Compiled).html

Here's a benchmark that improved a bit on arm64 when else-conditions were added to if-conversion, but that this PR is affecting: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_arm64_ubuntu%2020.04%2fBilinearTest.Interpol_Scalar.html
So likely this will regress it back to pre Nov 30th levels, but the if-conversion is happening [inside a loop](https://github.com/dotnet/performance/blob/97d6fce6eef2ed61355baac321a1b057b13346ca/src/benchmarks/micro/runtime/BilinearInterpol/BilinearInterpol.cs#L80) in this benchmark today.

I'm not sure there is so much we can do about this without investing in much more expensive/complicated analysis (that would probably be easier if the pass was still at a point where we had SSA). I assume the existing logic actually did mean to check for any kind of loop construct?
