### PR TITLE
KeyedCollection debug view doesn't work

### LINKED ISSUE #96116: KeyedCollection debug view doesn't work
### Description

`KeyedCollection` abstract base class has a debug proxy defined: https://github.com/dotnet/runtime/blob/7bb99e9f58d7bbaac53e7cf48c8ca1a9d17e216e/src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs#L10-L14

However, I don't believe it works correctly because it assumes one open generic type and `KeyedCollection` has two.

And no debug proxy is used when viewing a type that inherits from `KeyedCollection` with the debugger:
image

### Reproduction Steps

```cs
var c = new MyKeyedCollection();
c.Add(new KeyValuePair<string, string>("Name", "Value"));

internal class MyKeyedCollection : KeyedCollection<string, KeyValuePair<string, string>>
{
    protected override string GetKeyForItem(KeyValuePair<string, string> item)
    {
        return item.Key;
    }
}
```

### Expected behavior

A user-friendly debug view.

Should the debug view be a list or a name/value collection? A list is probably more appropriate.

### Actual behavior

Default debug view.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

net9.0

### Other information

_No response_

### PR DESCRIPTION
**Pull request by pedrobsaila**
Fixes #96116

### CODE REVIEW

File: src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs [hunk 1]
```diff
@@ -280,5 +280,53 @@ private void RemoveKey(TKey key)
                 keyCount--;
             }
         }
+
+        internal sealed class KeyedCollectionDebugView
```
Comment (stephentoub) [inline src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs:284]: private?

File: src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs [hunk 2]
```diff
@@ -280,5 +280,53 @@ private void RemoveKey(TKey key)
...
+                        TItem item = _collection[i];
+                        items[i] = new KeyedCollectionDebugViewItem(_collection.GetKeyForItem(item), item);
+                    }
+                    return items;
+                }
+            }
+        }
+
+        [DebuggerDisplay("{Value}", Name = "[{Key}]")]
+        internal readonly struct KeyedCollectionDebugViewItem
```
Comment (stephentoub) [inline src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs:311]: private and nested inside of KeyedCollectionDebugView above?

File: src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs [hunk 3]
```diff
@@ -280,5 +280,53 @@ private void RemoveKey(TKey key)
...
+        {
+            public KeyedCollectionDebugViewItem(TKey key, TItem value)
+            {
+                Key = key;
+                Value = value;
+            }
+
+            public KeyedCollectionDebugViewItem(KeyValuePair<TKey, TItem> keyValue)
```
Comment (stephentoub) [inline src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs:319]: Where is this used?

File: src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs (hunk 2 above)
Comment (pedrobsaila) [reply src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs:311]: Tried making KeyedCollectionDebugViewItem nested inside KeyedCollectionDebugView  but got :

```
error CS0053: Inconsistent accessibility: property type 'KeyedCollection<TKey, TItem>.KeyedC
ollectionDebugView.KeyedCollectionDebugViewItem[]' is less accessible than property 'KeyedCollection<TKey, TItem>.KeyedCollectionDebugView.Items
```

Comment (stephentoub) [reply src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs]: You'd fix that by making KeyedCollectionDebugViewItem public and nested. It wouldn't actually be visible outside of the assembly because it's contained inside something not public.

File: src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs [hunk 4]
```diff
@@ -280,5 +280,47 @@ private void RemoveKey(TKey key)
                 keyCount--;
             }
         }
+
+        private sealed class KeyedCollectionDebugView
```
[the remark this answers is not in the document]
Comment (pedrobsaila) [reply src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs:284]: I cannot use IDictionaryDebugView because it expects a IDictionary whereas KeyedCollection is not

[the remark this answers is not in the document]
Comment (eiriktsarpalis) [reply src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs:284]: Doesn't the KeyedCollection implementation use a dictionary under wraps?

[the remark this answers is not in the document]
Comment (JamesNK) [reply src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs:284]: Only if it grows past a certain threshold.

https://github.com/dotnet/runtime/blob/17335f452dd158e84fe949632ea5a298f507b05a/src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs#L242-L246

[the remark this answers is not in the document]
Comment (eiriktsarpalis) [reply src/libraries/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs:284]: Ah ok, current approach should be fine in that case.

**Review by eiriktsarpalis — APPROVED** [review]

**Comment by eiriktsarpalis** [comment]
@pedrobsaila before we get this merged, has the new proxy type been tested? I believe we write unit tests for a few other collections types, for example this one:

https://github.com/dotnet/runtime/blob/c31a2173e5a8b2cdef94b986504cf23b9a6bb175/src/libraries/Common/tests/System/Collections/DebugView.Tests.cs

**Comment by pedrobsaila** [comment]
Tested it only locally inside VS, did not make a unit test yet.

**Comment by eiriktsarpalis** [comment]
Would you be ok adding a unit test in the mold of what I shared from collections?

**Comment by pedrobsaila** [comment]
> Would you be ok adding a unit test in the mold of what I shared from collections?

yes for sure. I'll push the tests whthin a few hours

File: src/libraries/Common/tests/System/Collections/DebugView.Tests.cs [hunk 5]
```diff
@@ -206,5 +217,32 @@ public static void TestDebuggerAttributes_Null(object obj)
...
+
+            public CustomKeyedCollection(IEqualityComparer<TKey> comparer) : base(comparer)
+            {
+            }
+
+            public CustomKeyedCollection(IEqualityComparer<TKey> comparer, int dictionaryCreationThreshold) : base(comparer, dictionaryCreationThreshold)
+            {
+            }
+
+            public Func<TValue, TKey> GetKeyForItemHandler { get; set; }
```
Comment (eiriktsarpalis) [inline src/libraries/Common/tests/System/Collections/DebugView.Tests.cs:235]: Nit: I think some of that indirection could be removed if you just made the derived type non-generic and inlined the GetKeyBehavior in the implementation.

**Review by eiriktsarpalis — APPROVED** [review]
LGTM. I left some feedback on a minor nitpick on the test, but it's up to you if you want to address it. Thanks!
