### PR TITLE
Clear gcServer before running the scenario

### LINKED ISSUE #66905: gc-standalone: baseservices/RuntimeConfiguration/TestConfig/TestConfig.sh [FAIL]
logs: https://helix.dot.net/api/2019-06-17/jobs/40391257-2561-4750-ac32-1324c53e1d80/workitems/baseservices.RuntimeConfiguration/console
```
  Starting:    baseservices.RuntimeConfiguration.XUnitWrapper (parallel test collections = on, max threads = 4)
    baseservices/RuntimeConfiguration/TestConfig/TestConfig.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/baseservices.RuntimeConfiguration/TestConfig/TestConfig.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false TestConfig.dll ''
      Running: "/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfig/TestConfig.dll" Verify_ServerGC_Env_Enable
          set DOTNET_gcServer=1
      Running: -p DOTNET_gcServer=0 "/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfig/TestConfig.dll" Verify_ServerGC_Env_Disable
      Failed: Verify_ServerGC_Env_Disable
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfig/TestConfig.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at baseservices_RuntimeConfiguration._TestConfig_TestConfig_._TestConfig_TestConfig_sh()
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/baseservices.RuntimeConfiguration/TestConfig/TestConfig.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false TestConfig.dll ''
        Running: "/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfig/TestConfig.dll" Verify_ServerGC_Env_Enable
            set DOTNET_gcServer=1
        Running: -p DOTNET_gcServer=0 "/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfig/TestConfig.dll" Verify_ServerGC_Env_Disable
        Failed: Verify_ServerGC_Env_Disable
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfig/TestConfig.sh
```

### PR DESCRIPTION
**Pull request by am11**
Fixes #66905.

### CODE REVIEW

**Comment by am11** [comment]
@AaronRobinsonMSFT, I was able to repro it locally with `export COMPlus_gcServer=1` (or 0) as well as `export DOTNET_gcServer=1` (or 0). With values 0, `Verify_ServerGC_Env_Enable` was failing.

This is one way to fix the issue. Another approach is make this setting more conditional (based on the project name, for example?): https://github.com/dotnet/runtime/blob/fa1f2834dace0a34c53f1e1039b5af640fe51576/src/tests/Common/testenvironment.proj#L212-L213 but I liked this self-contained approach in `Main` method. Wdyt?

File: src/tests/baseservices/RuntimeConfiguration/TestConfig.cs [hunk 1]
```diff
@@ -64,6 +64,9 @@ static int Verify_ServerGC_Env_Override_Prop(string[] _)
 
     static int Main(string[] args)
     {
+        ClearEnvironmentVariable("DOTNET_gcServer");
```
Comment (AaronRobinsonMSFT) [inline src/tests/baseservices/RuntimeConfiguration/TestConfig.cs:67]: I think we should only do this in the `RunTests()` method or perhaps before we call it within the branch below.

**Comment by AaronRobinsonMSFT** [comment]
> I liked this self-contained approach in Main method. Wdyt?

Agree.

File: src/tests/baseservices/RuntimeConfiguration/TestConfig.cs (hunk 1 above)
Comment (am11) [reply src/tests/baseservices/RuntimeConfiguration/TestConfig.cs]: Moved to `RunTests()`.

**Comment by am11** [comment]
Although `/azp list` doesn't show gc-standalone pipeline, I think it can be ran directly from DevOps UI against the PR https://dev.azure.com/dnceng/public/_build?definitionId=1017

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@am11 I don't think we can target any PR, but rather only branches that are in dotnet/runtime. In this case, you would need to push your branch to dotnet/runtime and then I could run that pipeline. Once this goes in, I will trigger a run manually.

**Comment by am11** [comment]
Apparently Jan knows how to do that https://github.com/dotnet/runtime/pull/62066#issuecomment-980035669 :)

I don't think if I have access to push branch to dotnet/runtime.

File: src/tests/baseservices/RuntimeConfiguration/TestConfig.cs [hunk 2]
```diff
@@ -156,4 +159,13 @@ static string GetCorerunPath()
         }
         return Path.Combine(Environment.GetEnvironmentVariable("CORE_ROOT"), corerunName);
     }
-}
\ No newline at end of file
+
+    static void ClearEnvironmentVariable(string name)
+    {
+        string value = Environment.GetEnvironmentVariable(name);
```
Comment (danmoseley) [inline src/tests/baseservices/RuntimeConfiguration/TestConfig.cs:165]: Nit: easier and cheaper to just set both to null without get.

File: src/tests/baseservices/RuntimeConfiguration/TestConfig.cs [hunk 3]
```diff
@@ -156,4 +159,13 @@ static string GetCorerunPath()
...
+        if (!string.IsNullOrEmpty(value))
+        {
+            Environment.SetEnvironmentVariable(name, null);
```
Comment (danmoseley) [inline src/tests/baseservices/RuntimeConfiguration/TestConfig.cs:168]: After @AaronRobinsonMSFT 's change to enable the DOTNET_ prefix, I believe the CLR reads both the DOTNET and COMPlus prefixes case-insensitively on Linux. (Used to be case sensitive)
https://github.com/dotnet/runtime/pull/50507/files#diff-ca28f8b9cc75904774104e92e308462d908149b3e95288e37acd5b719bf6e0e9R643

This makes it difficult to clear them on Linux, since you don't know the casing. I guess you have to enumerate all variables, pick out any with these prefixes case insensitively, then use those names to clear them?

Comment (am11) [reply src/tests/baseservices/RuntimeConfiguration/TestConfig.cs]: > The test infrastructure always seems to use the `COMPlus_` prefix

(separate from this PR) At some point, we can update the test infra to use `DOTNET_` prefixes.

**Comment by jkotas** [comment]
> Specify refs/pull/<PR #>/merge as the branch to trigger the pipeline against

Actually, it has to be `refs/pull/<PR #>/head` to make the results show up in github UI.

**Comment by AaronRobinsonMSFT** [comment]
triggered.

**Comment by AaronRobinsonMSFT** [comment]
Looks good @am11. Thanks!
