### PR TITLE
[wasm] fix error cases in assets loading

### LINKED ISSUE #73673: [wasm] Regression: Crash on running debugger tests on Codespaces
Running debugger tests on codespaces now breaks with:

```
  Error Message:
   System.ArgumentException : {
  "timestamp": 1660098231978.708,
  "exceptionDetails": {
    "exceptionId": 1,
    "text": "Uncaught (in promise)",
    "lineNumber": 2,
    "columnNumber": 64026,
    "scriptId": "6",
    "url": "http://localhost:9400/dotnet.js",
    "exception": {
      "type": "object",
      "subtype": "error",
      "className": "TypeError",
      "description": "TypeError: Failed to fetch\n    at Object._s [as fetch_like] (http://localhost:9400/dotnet.js:3:64027)\n    at Do (http://localhost:9400/dotnet.js:3:51275)\n    at Po (http://localhost:9400/dotnet.js:3:51927)\n    at Uo (http://localhost:9400/dotnet.js:3:52273)\n    at Mo (http://localhost:9400/dotnet.js:3:50662)\n    at ko (http://localhost:9400/dotnet.js:3:50245)\n    at Ec (http://localhost:9400/dotnet.js:5:48267)\n    at http://localhost:9400/dotnet.js:5:46311",
      "objectId": "8367169025981544960.1.1",
      "preview": {
        "type": "object",
        "subtype": "error",
        "description": "TypeError: Failed to fetch\n    at Object._s [as fetch_like] (http://localhost:9400/dotnet.js:3:64027)\n    at Do (http://localhost:9400/dotnet.js:3:51275)\n    at Po (http://localhost:9400/dotnet.js:3:51927)\n    at Uo (http://localhost:9400/dotnet.js:3:52273)\n    at Mo (http://localhost:9400/dotnet.js:3:50662)\n    at ko (http://localhost:9400/dotnet.js:3:50245)\n    at Ec (http://localhost:9400/dotnet.js:5:48267)\n    at http://localhost:9400/dotnet.js:5:46311",
        "overflow": false,
        "properties": [
          {
            "name": "stack",
            "type": "string",
            "value": "TypeError: Failed to fetch\n    at Object._s [as fe…7)\n    at http://localhost:9400/dotnet.js:5:46311"
          },
          {
            "name": "message",
            "type": "string",
            "value": "Failed to fetch"
          }
        ]
      }
    },
    "executionContextId": 1,
    "exceptionMetaData": {
      "requestId": "3089.71"
    }
  },
  "__forMethod": "Runtime.exceptionThrown"
}
  Stack Trace:
     at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, TimeSpan span) in /workspaces/runtime/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 343
   at DebuggerTests.DebuggerTestBase.InitializeAsync() in /workspaces/runtime/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 149
```

.. making codespaces completely unusable for debugger work.
Reverting de03d8a8c84062e04c5c7ad574bd7bb7e58db9a9 fixes it.

```
commit de03d8a8c84062e04c5c7ad574bd7bb7e58db9a9
Author: Pavel Savara <pavel.savara@gmail.com>
Date:   Tue Aug 9 18:54:49 2022 +0200

    [wasm] asset loading for workers (#73484)

    - move asset related logic to separate file`assets.ts`
    - split logging code into separate file `logging.ts`
    - add `dotnet.wasm` and `dotnet-crypto-worker.js` to mono-config.json
    - moved `readSymbolMapFile()` call to `startup.ts`
    - fixed bug in `setup_proxy_console()` which didn't really copy the original `log` and `error` functions of the console and caused recursion on error.
    - moved `init_crypto` after `mono_wasm_load_config` in `mono_wasm_pre_init_essential_async`
    - added new resource type `js-module-crypto` and `js-module-threads`
    - changed the detection of blazor startup sequence to not be disabled by presence of config, but only by config.assets having some assembly in it.

    Co-authored-by: Marek Fišera <mara@neptuo.com>
```

Users could probably run into this too.

### PR DESCRIPTION
**Pull request by pavelsavara**
- fix bad rename of `maxParallelDownloads`  - throttling
- fix re-try logic
- fixed counting of loaded assets
- catching more error cases
- fix blazor detection

Fixes https://github.com/dotnet/runtime/issues/73673

### CODE REVIEW

File: src/mono/wasm/runtime/assets.ts [hunk 1]
```diff
@@ -5,14 +5,16 @@ import { mono_wasm_load_bytes_into_heap } from "./memory";
...
-import { AssetBehaviours, AssetEntry, LoadingResource, mono_assert, ResourceRequest } from "./types";
+import { abort_startup, beforeOnRuntimeInitialized } from "./startup";
+import { AssetBehaviours, AssetEntry, AssetEntryInternal, LoadingResource, mono_assert, ResourceRequest } from "./types";
 import { InstantiateWasmSuccessCallback, VoidPtr } from "./types/emscripten";
 
 const allAssetsInMemory = createPromiseController<void>();
 const allDownloadsQueued = createPromiseController<void>();
-let downloded_assets_count = 0;
-let instantiated_assets_count = 0;
+let actual_downloded_assets_count = 0;
```
Comment (kg) [inline src/mono/wasm/runtime/assets.ts:14]: if it's not too hard, fix these to be `downloaded`, not `downloded`

File: src/mono/wasm/runtime/assets.ts [hunk 2]
```diff
@@ -76,72 +126,65 @@ export async function mono_download_assets(): Promise<void> {
     }
 }
 
-export async function start_asset_download(asset: AssetEntry): Promise<AssetEntry | undefined> {
+export async function start_asset_download(asset: AssetEntryInternal, downloadData: boolean): Promise<ArrayBuffer | undefined> {
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:129]: nit: `start_asset_download_with_retries`

File: src/mono/wasm/runtime/assets.ts [hunk 3]
```diff
@@ -76,72 +126,65 @@ export async function mono_download_assets(): Promise<void> {
...
     try {
-        return await start_asset_download_throttle(asset);
+        return await start_asset_download_throttle(asset, downloadData);
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:131]: This whole function should be refactored to support `n` retries. That should work for n==0 too.

File: src/mono/wasm/runtime/assets.ts [hunk 4]
```diff
@@ -76,72 +126,65 @@ export async function mono_download_assets(): Promise<void> {
...
     } catch (err: any) {
+        asset.internalPending = undefined;
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:133]: Are there cases (maybe node?) where we are not fetching from http* but from a filesystem? In that case do we have any need to retry?

File: src/mono/wasm/runtime/assets.ts [hunk 5]
```diff
@@ -76,72 +126,65 @@ export async function mono_download_assets(): Promise<void> {
...
         if (err && err.status == 404) {
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:134]: How does this `err.status` get populated? When I try locally, I see that we get a `TypeError: Failed to fetch` in `start_asset_download_sources`, but then we throw through `mono_assert` - `Error: Assert failed: Response undefined`.

Can we get the http status, and condition on that? If so, what code do we get in the codespaces case? Maybe we can have a narrow set of cases where we do retries?

File: src/mono/wasm/runtime/assets.ts [hunk 6]
```diff
@@ -24,6 +26,18 @@ const skipDownloadsAssetTypes: {
     "js-module-crypto": true,
     "js-module-threads": true,
 };
+const skipBufferAssetTypes: {
+    [k: string]: boolean
+} = {
+    "dotnetwasm": true,
```
[the remark this answers is not in the document]
Comment (kg) [reply src/mono/wasm/runtime/assets.ts:32]: you need some sort of value to store a key in a dict

File: src/mono/wasm/runtime/assets.ts [hunk 7]
```diff
@@ -38,34 +52,70 @@ export async function mono_download_assets(): Promise<void> {
...
-                })());
-            }
+        for (const downloadPromise of buffer_promises) {
+            asset_promises.push((async () => {
+                const downloadedAsset = await downloadPromise as AssetEntryInternal;
+                if (downloadedAsset) {
+                    if (!skipInstantiateAssetTypes[downloadedAsset.behavior]) {
+                        const url = downloadedAsset.internalPending!.url;
+                        const data = new Uint8Array(downloadedAsset.buffer!);
+                        downloadedAsset.internalPending = undefined; //GC
```
Comment (kg) [inline src/mono/wasm/runtime/assets.ts:99]: I would prefer null for these, so it's obvious that someone erased them and they aren't missing

File: src/mono/wasm/runtime/assets.ts [hunk 8]
```diff
@@ -181,52 +225,87 @@ async function start_asset_download_sources(asset: AssetEntry): Promise<AssetEnt
...
+        const response = runtimeHelpers.fetch_like(request.resolvedUrl!, options);
+        return {
+            name: request.name, url: request.resolvedUrl!, response
+        };
+    } catch (err) {
+        const response = <Response><any>{
+            ok: false,
+            url: request.resolvedUrl,
+            status: 500,
+            statusText: "ERR28: " + err,
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:302]: What is `ERR28`?

File: src/mono/wasm/runtime/assets.ts (hunk 4 above)
Comment (kg) [reply src/mono/wasm/runtime/assets.ts:133]: yeah, for filesystem access we shouldn't retry and should fail-fast. theoretically the config in browser could also be fetching from file:// or blob:

File: src/mono/wasm/runtime/assets.ts [hunk 9]
```diff
@@ -76,72 +126,65 @@ export async function mono_download_assets(): Promise<void> {
...
+            return undefined;
+        }
+        return await response.arrayBuffer();
     }
-    const options: any = {};
-    if (request.hash) {
-        options.integrity = request.hash;
+    finally {
+        --parallel_count;
+        if (throttling && parallel_count == runtimeHelpers.maxParallelDownloads - 1) {
```
Comment (kg) [inline src/mono/wasm/runtime/assets.ts:172]: the name throttling sounds like a bool, we should name it something like throttlingFuture

File: src/mono/wasm/runtime/assets.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (radical) [reply src/mono/wasm/runtime/assets.ts:32]: right, I was thinking of an array, but this would provide a faster lookup! 👍

File: src/mono/wasm/runtime/assets.ts [hunk 10]
```diff
@@ -181,52 +225,87 @@ async function start_asset_download_sources(asset: AssetEntry): Promise<AssetEnt
...
+            ++actual_downloded_assets_count;
+            return response;
         }
         catch (err) {
             continue; //next source
         }
     }
-    throw response;
+    const isOkToFail = asset.isOptional || (asset.name.match(/\.pdb$/) && runtimeHelpers.config.ignorePdbLoadErrors);
+    mono_assert(response, "Response undefined");
```
Comment (kg) [inline src/mono/wasm/runtime/assets.ts:241]: update this error message to specify the url or name of the asset

File: src/mono/wasm/runtime/assets.ts [hunk 11]
```diff
@@ -181,52 +225,87 @@ async function start_asset_download_sources(asset: AssetEntry): Promise<AssetEnt
...
-        ++parallel_count;
-        if (parallel_count == runtimeHelpers.maxParallelDownloads) {
-            if (runtimeHelpers.diagnosticTracing)
-                console.debug("MONO_WASM: Throttling further parallel downloads");
-            throttling = createPromiseController<void>();
+function resolve_path(asset: AssetEntry, sourcePrefix: string): string {
+    let attemptUrl;
+    const assemblyRootFolder = runtimeHelpers.config.assemblyRootFolder;
+    if (!asset.resolvedUrl) {
+        if (sourcePrefix === "") {
```
Comment (kg) [inline src/mono/wasm/runtime/assets.ts:262]: this can't be undefined, right?

File: src/mono/wasm/runtime/assets.ts [hunk 12]
```diff
@@ -38,34 +52,70 @@ export async function mono_download_assets(): Promise<void> {
...
+        for (const a of runtimeHelpers.config.assets!) {
+            const asset: AssetEntryInternal = a;
+            if (!skipInstantiateAssetTypes[asset.behavior]) {
+                expected_instantiated_assets_count++;
+            }
+            if (!skipDownloadsAssetTypes[asset.behavior]) {
+                const dontTouchBuffer = skipBufferAssetTypes[asset.behavior];
+                expected_downloded_assets_count++;
+                if (asset.pending) {
+                    asset.internalPending = asset.pending;
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:66]: Do IIUC, that `asset.pending` is not being set anywhere right now, but the intention is that it can be set for some kinda "pre-loaded asset", or some "asset with custom loading" - so we won't attempt to fetch it?

Also, is `assert.InternalPending` being used because `asset.pending` could be modified by someone once `mono_download_assets` has started executing?

File: src/mono/wasm/runtime/assets.ts [hunk 13]
```diff
@@ -181,52 +225,87 @@ async function start_asset_download_sources(asset: AssetEntry): Promise<AssetEnt
...
-                console.debug("MONO_WASM: Throttling further parallel downloads");
-            throttling = createPromiseController<void>();
+function resolve_path(asset: AssetEntry, sourcePrefix: string): string {
+    let attemptUrl;
+    const assemblyRootFolder = runtimeHelpers.config.assemblyRootFolder;
+    if (!asset.resolvedUrl) {
+        if (sourcePrefix === "") {
+            if (asset.behavior === "assembly" || asset.behavior === "pdb")
+                attemptUrl = assemblyRootFolder + "/" + asset.name;
+            else if (asset.behavior === "resource") {
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:265]: nit: 
```suggestion
            if (asset.behavior === "assembly" || asset.behavior === "pdb") {
                attemptUrl = assemblyRootFolder + "/" + asset.name;
            } else if (asset.behavior === "resource") {
```

File: src/mono/wasm/runtime/assets.ts [hunk 14]
```diff
@@ -181,52 +225,87 @@ async function start_asset_download_sources(asset: AssetEntry): Promise<AssetEnt
...
-            if (runtimeHelpers.diagnosticTracing)
-                console.debug("MONO_WASM: Throttling further parallel downloads");
-            throttling = createPromiseController<void>();
+function resolve_path(asset: AssetEntry, sourcePrefix: string): string {
+    let attemptUrl;
+    const assemblyRootFolder = runtimeHelpers.config.assemblyRootFolder;
+    if (!asset.resolvedUrl) {
+        if (sourcePrefix === "") {
+            if (asset.behavior === "assembly" || asset.behavior === "pdb")
+                attemptUrl = assemblyRootFolder + "/" + asset.name;
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:264]: `assemblyRootFolder`'s type suggests that it can be undefined.

File: src/mono/wasm/runtime/assets.ts [hunk 15]
```diff
@@ -181,52 +225,87 @@ async function start_asset_download_sources(asset: AssetEntry): Promise<AssetEnt
...
+                attemptUrl = assemblyRootFolder + "/" + path;
+            }
+            else {
+                attemptUrl = asset.name;
+            }
+        } else {
+            attemptUrl = sourcePrefix + asset.name;
         }
-        return await start_asset_download_sources(asset);
+        attemptUrl = runtimeHelpers.locateFile(attemptUrl);
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:275]: Can this return undefined/"" ?

Comment (radical) [reply src/mono/wasm/runtime/assets.ts:275]: If so, then maybe we should check if `attemptUrl` has a value at the end, and use `asset.name` if it doesn't? Or error?

File: src/mono/wasm/runtime/assets.ts [hunk 16]
```diff
@@ -401,9 +479,8 @@ export async function wait_for_all_assets() {
     // wait for all assets in memory
     await allAssetsInMemory.promise;
     if (runtimeHelpers.config.assets) {
-        const expected_asset_count = runtimeHelpers.config.assets.filter(a => !skipDownloadsAssetTypes[a.behavior]).length;
-        mono_assert(downloded_assets_count == expected_asset_count, "Expected assets to be downloaded");
-        mono_assert(instantiated_assets_count == expected_asset_count, "Expected assets to be in memory");
+        mono_assert(actual_downloded_assets_count == expected_downloded_assets_count, "Expected assets to be downloaded");
+        mono_assert(actual_instantiated_assets_count == expected_instantiated_assets_count, "Expected assets to be in memory");
```
Comment (radical) [inline src/mono/wasm/runtime/assets.ts:483]: These will throw an error without details of what the mismatching values were.

File: src/mono/wasm/runtime/imports.ts [hunk 17]
```diff
@@ -39,12 +39,13 @@ export function set_imports_exports(
...
 
-export const runtimeHelpers: RuntimeHelpers = <any>{
-    javaScriptExports: {},
+const initialRuntimeHelpers: Partial<RuntimeHelpers> =
+{
+    javaScriptExports: {} as any,
     mono_wasm_load_runtime_done: false,
     mono_wasm_bindings_is_ready: false,
-    max_parallel_downloads: 16,
+    maxParallelDownloads: 16,
```
Comment (radical) [inline src/mono/wasm/runtime/imports.ts:47]: What does the style difference between this, and other fields mean?

File: src/mono/wasm/runtime/startup.ts [hunk 18]
```diff
@@ -53,7 +53,7 @@ export function configure_emscripten_startup(module: DotnetModule, exportedAPI:
     // eslint-disable-next-line @typescript-eslint/no-empty-function
     const userOnRuntimeInitialized: () => void = module.onRuntimeInitialized ? module.onRuntimeInitialized : () => { };
     // when assets don't contain DLLs it means this is Blazor or another custom startup
-    isCustomStartup = !module.configSrc && (!module.config || !module.config.assets || module.config.assets.findIndex(a => a.behavior === "assembly") != -1); // like blazor
+    isCustomStartup = !module.configSrc && (!module.config || !module.config.assets || module.config.assets.findIndex(a => a.behavior === "assembly") == -1); // like blazor
```
Comment (radical) [inline src/mono/wasm/runtime/startup.ts:56]: Why the change?

File: src/mono/wasm/runtime/assets.ts [hunk 19]
```diff
@@ -24,6 +26,18 @@ const skipDownloadsAssetTypes: {
...
 };
+const skipBufferAssetTypes: {
+    [k: string]: boolean
+} = {
+    "dotnetwasm": true,
+};
+const skipInstantiateAssetTypes: {
+    [k: string]: boolean
+} = {
+    "js-module-crypto": true,
```
[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:37]: dictionary lookup if faster than scanning array.

File: src/mono/wasm/runtime/assets.ts [hunk 20]
```diff
@@ -38,34 +52,70 @@ export async function mono_download_assets(): Promise<void> {
...
-        for (const asset of runtimeHelpers.config.assets!) {
-            if (!asset.pending && !skipDownloadsAssetTypes[asset.behavior]) {
-                download_promises.push(start_asset_download(asset));
+        for (const a of runtimeHelpers.config.assets!) {
+            const asset: AssetEntryInternal = a;
+            if (!skipInstantiateAssetTypes[asset.behavior]) {
+                expected_instantiated_assets_count++;
+            }
+            if (!skipDownloadsAssetTypes[asset.behavior]) {
+                const dontTouchBuffer = skipBufferAssetTypes[asset.behavior];
```
[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:63]: `response.arrayBuffer()` can't be called twice and wasm instantiation needs to do it itself. renamed and commented.

File: src/mono/wasm/runtime/assets.ts [hunk 21]
```diff
@@ -38,34 +52,70 @@ export async function mono_download_assets(): Promise<void> {
...
+                    const waitForExternalData: () => Promise<AssetEntry | undefined> = async () => {
+                        const response = await asset.internalPending!.response;
+                        ++actual_downloded_assets_count;
+                        if (dontTouchBuffer) {
+                            return undefined;
+                        }
+                        asset.buffer = await response.arrayBuffer();
+                        return asset;
+                    };
+                    buffer_promises.push(waitForExternalData());
```
[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:76]: renamed

File: src/mono/wasm/runtime/assets.ts [hunk 22]
```diff
@@ -38,34 +52,70 @@ export async function mono_download_assets(): Promise<void> {
...
         // start fetching and instantiating all assets in parallel
-        for (const asset of runtimeHelpers.config.assets!) {
-            if (!asset.pending && !skipDownloadsAssetTypes[asset.behavior]) {
-                download_promises.push(start_asset_download(asset));
+        for (const a of runtimeHelpers.config.assets!) {
+            const asset: AssetEntryInternal = a;
+            if (!skipInstantiateAssetTypes[asset.behavior]) {
+                expected_instantiated_assets_count++;
+            }
+            if (!skipDownloadsAssetTypes[asset.behavior]) {
```
[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:62]: I don't like `break;` I find it error prone.

File: src/mono/wasm/runtime/assets.ts [hunk 23]
```diff
@@ -38,34 +52,70 @@ export async function mono_download_assets(): Promise<void> {
...
-        const download_promises: Promise<AssetEntry | undefined>[] = [];
+        const buffer_promises: Promise<AssetEntry | undefined>[] = [];
         // start fetching and instantiating all assets in parallel
-        for (const asset of runtimeHelpers.config.assets!) {
-            if (!asset.pending && !skipDownloadsAssetTypes[asset.behavior]) {
-                download_promises.push(start_asset_download(asset));
+        for (const a of runtimeHelpers.config.assets!) {
+            const asset: AssetEntryInternal = a;
+            if (!skipInstantiateAssetTypes[asset.behavior]) {
+                expected_instantiated_assets_count++;
```
[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:60]: those conditions are on same level and both would be evaluated.

File: src/mono/wasm/runtime/assets.ts [hunk 24]
```diff
@@ -76,72 +126,65 @@ export async function mono_download_assets(): Promise<void> {
...
         if (err && err.status == 404) {
             throw err;
         }
         // second attempt only after all first attempts are queued
         await allDownloadsQueued.promise;
         try {
-            return await start_asset_download_throttle(asset);
+            return await start_asset_download_throttle(asset, downloadData);
         } catch (err) {
+            asset.internalPending = undefined;
```
[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:142]: if the first attempt on same url was 404, we will not try again.
If the first was something else, like connection reset, the second probably would  not be 404 ?

File: src/mono/wasm/runtime/assets.ts (hunk 8 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:302]: We are numbering some of the errors so that they are easier to find, when they happen. Search `/ERR[0-9]+/` in the code
This one should have new number, tho.

File: src/mono/wasm/runtime/assets.ts (hunk 11 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:262]: it can't. added assert for it, just to make it clear.

File: src/mono/wasm/runtime/assets.ts (hunk 12 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:66]: the `pending` is a contract with Blazor, their cache is giving that out. The shape of it is pre-existing design.
We have  `internalPending` which is almost the same semantics, but not 100%. So we disconnected those concepts with @maraf yesterday.

File: src/mono/wasm/runtime/imports.ts (hunk 17 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/imports.ts:47]: This fix of a is bad merge,  when I renamed stuff last week. This is what broke throttling.

File: src/mono/wasm/runtime/assets.ts (hunk 23 above)
[the remark this answers is not in the document]
Comment (radical) [reply src/mono/wasm/runtime/assets.ts:60]: So, you can have an asset that will be instantiated, but not downloaded? I guess, `dotnet.wasm` would be one of them?

File: src/mono/wasm/runtime/imports.ts (hunk 17 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/imports.ts:47]: we could rename the rest of them at some point. They are all internal.

File: src/mono/wasm/runtime/assets.ts (hunk 12 above)
Comment (radical) [reply src/mono/wasm/runtime/assets.ts:66]: Can we make that difference clearer in code?

Comment (radical) [reply src/mono/wasm/runtime/assets.ts:66]: Maybe by naming the objects accordingly

File: src/mono/wasm/runtime/startup.ts (hunk 18 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/startup.ts:56]: it's a bug. 

if there are assemblies in the list of assets, it means that:
a) it's not blazor
b) it's blazor fully converted to use full, non-custom startup sequence (net8)

if there are NO assemblies in the list of assets, it means that:
c) it's blazor and it still needs custom startup sequence (net7)

File: src/mono/wasm/runtime/assets.ts (hunk 23 above)
[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:60]: I just wanted to keep the skip logic separate, not nested.
`dotnet.wasm` is actually attempted to download twice. 
once from `instantiate_wasm_module` and second from `mono_download_assets`, the second call would be just `await asset.internalPending`

File: src/mono/wasm/runtime/assets.ts (hunk 5 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:134]: search for `err.status = response.status;`

File: src/mono/wasm/runtime/assets.ts (hunk 15 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:275]: I added assert

File: src/mono/wasm/runtime/assets.ts (hunk 12 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:66]: any hint ?

**Review by radical — APPROVED** [review]
I'm no expert on JS/TS, and reviewed whatever I could. Other than my comments, it looks good to me.

File: src/mono/wasm/runtime/assets.ts (hunk 24 above)
[the remark this answers is not in the document]
Comment (radical) [reply src/mono/wasm/runtime/assets.ts:148]: Connection reset is probably the only good one for which we should retry, I think. But is that detectable? Not for this PR necessarily, just thinking aloud.

File: src/mono/wasm/runtime/assets.ts (hunk 12 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:72]: we settled on `pendingDownload?: LoadingResource` and doc

File: src/mono/wasm/runtime/assets.ts (hunk 24 above)
[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts:148]: the error is cryptic and probably different on different engines. Not this PR.

File: src/mono/wasm/runtime/assets.ts (hunk 3 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts]: different PR

File: src/mono/wasm/runtime/assets.ts [hunk 25]
```diff
@@ -181,52 +245,94 @@ async function start_asset_download_sources(asset: AssetEntry): Promise<AssetEnt
...
+        err.status = response.status;
+        throw err;
+    } else {
+        Module.print(`MONO_WASM: download '${response.url}' for ${asset.name} failed ${response.status} ${response.statusText}`);
+        if (!skipDownloadsByAssetTypes[asset.behavior]) {
+            expected_downloaded_assets_count--;
+        }
+        if (skipInstantiateByAssetTypes[asset.behavior]) {
+            expected_instantiated_assets_count--;
+        }
```
Comment (maraf) [inline src/mono/wasm/runtime/assets.ts:273]: How can we get here? It's already guarded in the `mono_download_assets`, right?

File: src/mono/wasm/runtime/assets.ts [hunk 26]
```diff
@@ -76,72 +132,79 @@ export async function mono_download_assets(): Promise<void> {
...
 
-function download_resource(request: ResourceRequest): LoadingResource {
-    if (typeof Module.downloadResource === "function") {
-        const loading = Module.downloadResource(request);
-        if (loading) return loading;
+        const response = await start_asset_download_sources(asset);
+        if (!response) return undefined;
+        if (!downloadData) {
+            return undefined;
+        }
```
Comment (maraf) [inline src/mono/wasm/runtime/assets.ts:187]:
```suggestion
        if (!response || !downloadData) {
            return undefined;
        }
```

File: src/mono/wasm/runtime/assets.ts (hunk 25 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/assets.ts]: it's about optional downloads, I moved it now.

**Review by thaystg — APPROVED** [review]
LGTM. I also tested it on codespaces :)

**Review by maraf — APPROVED** [review]

**Comment by pavelsavara** [comment]
All the failures are https://github.com/dotnet/runtime/issues/73721
