### PR TITLE
Fix flags in EarlyProp after nullcheck is removed

### LINKED ISSUE #112333: Test failure: JIT/Regression/JitBlue/Runtime_82535/Runtime_82535/Runtime_82535.dll
**Failed in:** [runtime-coreclr jitstress-random 20250209.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=945874&view=ms.vss-test-web.build-test-results-tab&runId=25112494&resultId=109318&paneView=debug)

**Failed tests:**
```
coreclr linux x64 Checked jitstress_random_2 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/Runtime_82535/Runtime_82535/Runtime_82535.dll
```

**Error message:**
```
 Object reference not set to an instance of an object.
```

**Stack trace:**
```
   at Program.TestEntryPoint()
   at Program.<<Main>$>g__TestExecutor445|0_446(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/112333

When we have:
```
NULLCHECK(addr)
IND(addr)
```
if we decide to remove the nullcheck (when it is followed by an indirect which is recognized as an implicit nullcheck for the same address), we should update the flags in that indirect as it's no longer non-faulting.

### CODE REVIEW

File: src/coreclr/jit/earlyprop.cpp [hunk 1]
```diff
@@ -457,6 +457,10 @@ bool Compiler::optFoldNullCheck(GenTree* tree, LocalNumberToNullCheckTreeMap* nu
         nullCheckTree->SetHasOrderingSideEffect();
         nullCheckTree->gtFlags |= GTF_IND_NONFAULTING;
 
+        // The current indir is no longer non-faulting.
+        tree->gtFlags &= ~GTF_IND_NONFAULTING;
+        tree->SetIndirExceptionFlags(this);
```
Comment (EgorBo) [inline src/coreclr/jit/earlyprop.cpp:462]: I presume in theory we can avoid removing GTF_IND_NONFAULTING and adding GTF_EXCEPT if the leading (if it is in fact leading) nullcheck had them, but wanted to be on a safe side

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/earlyprop.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/earlyprop.cpp:462]: IS the `SetIndirExceptionFlags` necessary? I assume it should be recomputed below when all side effect flags are updated.

Comment (EgorBo) [reply src/coreclr/jit/earlyprop.cpp:462]: Correct, GTF_EXCEPT is set later via gtUpdateNodeOperSideEffects, so this one is redundant
