### PR TITLE
Fix full-aot support for unmanaged function pointers.

### LINKED ISSUE #44779: [aot] Mono does not add wrappers for UnmanagedCallersOnly methods to AOT images
Compile the following example (easiest way is to use this as the body of src/mono/netcore/sample/HelloWorld/Program.cs)
```csharp
using System;

using System.Runtime.InteropServices;

[System.AttributeUsage(System.AttributeTargets.Method)]
public class MonoPInvokeCallbackAttribute : Attribute {
    public MonoPInvokeCallbackAttribute (Type t) {}
}

public class A {
    [DllImport ("Foo", EntryPoint="bar")]
    public static extern unsafe void Foo(delegate* unmanaged<int,int> f);

    [UnmanagedCallersOnly]
    private static int Bar (int x) => x + 1;


    [DllImport ("Foo", EntryPoint="bar2")]
    public static extern unsafe void Foo2(Func<int,int> f);

    [MonoPInvokeCallback(typeof (Func<int,int>))]
    private static int Bar2 (int x) => x + 1;

    public static void Caller () {
        unsafe {
            Foo (&Bar);
        }
    }

    public static void Caller2 () {
        unsafe {
            Foo2 (Bar2);
        }
    }

    public static void Main () {
        Caller ();
        Caller2 ();
    }
}
```

Now publish with `dotnet.sh public -c [CONFIG] -r [RID]` and go into the publish folder and run
```
MONO_PATH=. ~/working/dotnet-runtime/artifacts/obj/mono/Linux.x64.Debug/mono/mini/mono-sgen --aot=full -v HelloWorld.dll
``` 

Expected result all the methods are AOTd and emitted. In particular `A:Caller` should be emitted.

Actual result
```
Method void MonoPInvokeCallbackAttribute:.ctor (System.Type) emitted as .Lm_0
Method int A:Bar (int) emitted as .Lm_2
Method int A:Bar2 (int) emitted as .Lm_4
Method void A:Caller2 () emitted as .Lm_6
Method void A:Main () emitted as .Lm_7
Method void A:.ctor () emitted as .Lm_8
Method (wrapper delegate-invoke) int System.Func`2<int, int>:invoke_TResult_T (int) emitted as .Lm_e
Method (wrapper managed-to-native) void A:Foo (*()) emitted as .Lm_f
Method (wrapper managed-to-native) void A:Foo2 (System.Func`2<int, int>) emitted as .Lm_10
Method (wrapper native-to-managed) int A:Bar2 (int) emitted as .Lm_11
Compiled: 10/11
```

Note that `A:Caller` is not emitted.
And also there is no `Method (wrapper native-to-managed) int A:Bar (int) emitted` - which we would expect from `UnmanagedCallersOnly` and `&Bar`

---

Another instance of the same issue is if you AOT the (original in-repo) HelloWorld sample, it will fail at runtime with
```
Unhandled Exception:
System.ExecutionEngineException: Attempting to JIT compile method 'void System.ConsolePal:EnsureInitializedCore ()' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
```
Which happens because `ConsolePal:EnsureInitializedCore` has this line:
```csharp
    Interop.Sys.SetTerminalInvalidationHandler(&InvalidateTerminalSettings);
```

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/44779.

### CODE REVIEW

**Review by BrzVlad — APPROVED** [review]

File: src/mono/mono/mini/aot-compiler.c [hunk 1]
```diff
@@ -5054,6 +5054,19 @@ MONO_RESTORE_WARNING
...
+#ifdef ENABLE_NETCORE
+			for (j = 0; j < cattr->num_attrs; ++j)
+				if (cattr->attrs [j].ctor && mono_is_corlib_image (m_class_get_image (cattr->attrs [j].ctor->klass)) && !strcmp (m_class_get_name (cattr->attrs [j].ctor->klass), "UnmanagedCallersOnlyAttribute"))
+					break;
+			if (j < cattr->num_attrs) {
+				MonoMethod *wrapper = mono_marshal_get_managed_wrapper (method, NULL, 0, error);
+				mono_error_assert_ok (error);
+
+				add_method (acfg, wrapper);
+			}
```
Comment (lambdageek) [inline src/mono/mono/mini/aot-compiler.c:5067]: LGTM. Would be nice to also add [`EntryPoint`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedcallersonlyattribute.entrypoint?view=net-5.0) support for providing an exported name.

Comment (lambdageek) [reply src/mono/mono/mini/aot-compiler.c:5067]: I made a new issue about it https://github.com/dotnet/runtime/issues/44803
