### PR TITLE
Remove CONTEXT_XSTATE in FaultingExceptionFrame::UpdateRegDisplay

### LINKED ISSUE #105483: AV in runtime when catching exception thrown in other ALC with new EH on win-arm64
Run the following program on win-arm64:

```csharp
using System;
using System.Runtime.Intrinsics;

public class C0
{
    public ulong F1;
}

public class Program
{
    public static IRuntime s_rt;
    public static Vector64<ushort> s_1;
    public static double s_7;
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        try
        {
            mi.Invoke(null, new object[] { System.Activator.CreateInstance(runtimeTy) });
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }

    public static void MainInner(IRuntime rt)
    {
        C0 vr0 = default(C0);
        C0 vr1 = default(C0);
        vr1.F1 = vr0.F1;
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC() : base(true)
    {
    }
}
```

The exception seems to be catchable only without legacy exception handling:
```
PS C:\jakob\publish> $env:DOTNET_LegacyExceptionHandling=0
PS C:\jakob\publish> C:\jakob\Core_Root\corerun.exe "C:\jakob\playground\playground.dll"
PS C:\jakob\publish> echo $LASTEXITCODE
-1073741819
PS C:\jakob\publish> $env:DOTNET_LegacyExceptionHandling=1
PS C:\jakob\publish> C:\jakob\Core_Root\corerun.exe "C:\jakob\playground\playground.dll"
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.MainInner(IRuntime rt)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Program.Main()
PS C:\jakob\publish> echo $LASTEXITCODE
0
PS C:\jakob\publish>
```

### PR DESCRIPTION
**Pull request by janvorli**
There is a bug in updating `REGDISPLAY` from a faulting exception frame. The context stored in the frame can contain extended state, but we only copy the basic `CONTEXT` part. But we are not removing the `CONTEXT_XSTATE` flag. There was an issue found on arm64 Windows with SVE enabled. The context from a hardware exception contains the SVE extended state and when we resume after catch for the exception or start propagating it through native frames, the `RtlRestoreContext` uses some garbage to try to restore the extended state and ends up corrupting memory.

The fix is to remove the `CONTEXT_XSTATE` flag from the context after we copy it to the `REGDISPLAY`.

While we have hit this problem on Windows ARM64 with SVE only, I have made the same change for other targets that can have extended state too.

Close #105483

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @jakobbotsch

File: src/coreclr/vm/arm64/cgencpu.h [hunk 1]
```diff
@@ -620,4 +620,22 @@ struct ThisPtrRetBufPrecode {
 };
 typedef DPTR(ThisPtrRetBufPrecode) PTR_ThisPtrRetBufPrecode;
 
+// Mirror the XSTATE_ARM64_SVE flags from winnt.h
```
Comment (jkotas) [inline src/coreclr/vm/arm64/cgencpu.h:623]: `inc\clrnt.h` may be a better place for this

**Review by jkotas — APPROVED** [review]
