### PR TITLE
Fixes DI deadlock when resolving singletons 

### LINKED ISSUE #35986: Deadlock when creating typed HttpClient with DI and HttpClientFactory
### Describe the bug

We have a .net core web service with, for simplicity, two controllers, each with one route. One of the controllers, let's say 'scoped' controller, has typed http client injected directly. Other one, - 'singleton' controller, - has some singleton service injected, which, in its turn, has the same typed http client injected. The typed http client itself is registered with headers propagation - but it could be any additional .AddHttpMessageHandler(Func<IServiceProvider, DelegatingHandler>) registered which makes calls similar to IServiceProvider.GetRequiredService for any singleton dependency.

At first time after web service start when there is two (or more) concurrent requests on routes in both controllers, and route in 'scoped' controller starts processing just a bit earlier, than route in 'singleton' controller, there is a deadlock in DI. 

### To Reproduce

Take the solution from https://github.com/meareindel/DI-deadlock/tree/master and run the single test in it. It could be needed to modify the value of seconds to wait between requesting tasks depending on a machine configuration. The value also needs to be other for debugging (a little bit more, around 10ms on my machine, for example).

### Expected behavior

No deadlock occurs, http client created successfully  --OR-- validation error when injecting transient service into singleton.

### Additional context
Include the output of `dotnet --info`

stacks of route threads
'singleton' controller route:

```
Lazy<ActiveHandlerTrackingEntry>.ExecutionAndPublication()
Lazy<ActiveHandlerTrackingEntry>.CreateValue()
Lazy<__Canon>.get_Value()
DefaultHttpClientFactory.CreateHandler()
DefaultHttpClientFactory.CreateClient()
HttpClientBuilderExtensions.<>c__DisplayClass10_0<TypedHttpClient>.<AddTypedClientCore>b__0()
CallSiteRuntimeResolver.VisitFactory()
CallSiteVisitor<RuntimeResolverContext, object>.VisitCallSiteMain() [2]
CallSiteRuntimeResolver.VisitDisposeCache()
CallSiteVisitor<RuntimeResolverContext, object>.VisitCallSite() [2]
CallSiteRuntimeResolver.VisitConstructor()
CallSiteVisitor<RuntimeResolverContext, object>.VisitCallSiteMain() [1]
CallSiteRuntimeResolver.VisitCache()
CallSiteRuntimeResolver.VisitRootCache()
CallSiteVisitor<RuntimeResolverContext, object>.VisitCallSite() [1]
CallSiteRuntimeResolver.Resolve()
DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0()
ServiceProviderEngine.GetService()
ServiceProviderEngineScope.GetService()
ActivatorUtilities.GetService()
[Lightweight Method Call]
ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0()
ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0()
ControllerActionInvoker.Next()
ControllerActionInvoker.InvokeInnerFilterAsync()
ResourceInvoker.Next()
ResourceInvoker.InvokeFilterPipelineAsync()
ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d>()
ResourceInvoker.<InvokeAsync>g__Logged|17_1()
ResourceInvoker.InvokeAsync()
ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0()
EndpointMiddleware.Invoke()
AuthorizationMiddleware.<Invoke>d__5.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__5>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__5>()
AuthorizationMiddleware.Invoke()
EndpointRoutingMiddleware.SetRoutingAndContinue()
EndpointRoutingMiddleware.Invoke()
HeaderPropagationMiddleware.<Invoke>d__4.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.HeaderPropagation.HeaderPropagationMiddleware.<Invoke>d__4>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.HeaderPropagation.HeaderPropagationMiddleware.<Invoke>d__4>()
HeaderPropagationMiddleware.Invoke()
HttpsRedirectionMiddleware.Invoke()
DeveloperExceptionPageMiddleware.<Invoke>d__9.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__9>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__9>()
DeveloperExceptionPageMiddleware.Invoke()
HostFilteringMiddleware.Invoke()
HostingApplication.ProcessRequestAsync()
ApplicationWrapper<HostingApplication.Context>.Microsoft.AspNetCore.Hosting.Server.IHttpApplication<TContext>.ProcessRequestAsync()
ApplicationWrapper<HostingApplication.Context>.ProcessRequestAsync()
HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d>()
HttpContextBuilder.<>c__DisplayClass23_0.<SendAsync>g__RunRequestAsync|0()
HttpContextBuilder.<>c__DisplayClass23_0.<SendAsync>b__1()
QueueUserWorkItemCallbackDefaultContext.Execute()
ThreadPoolWorkQueue.Dispatch()
_ThreadPoolWaitCallback.PerformWaitCallback()
[Native to Managed Transition]
```

'scoped' controller route:

```
Monitor.Enter()
CallSiteRuntimeResolver.VisitCache()
CallSiteRuntimeResolver.VisitRootCache()
CallSiteVisitor<RuntimeResolverContext, object>.VisitCallSite() [2]
CallSiteRuntimeResolver.Resolve() [2]
DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0() [2]
ServiceProviderEngine.GetService() [2]
ServiceProviderEngineScope.GetService() [2]
ServiceProviderServiceExtensions.GetRequiredService()
ServiceProviderServiceExtensions.GetRequiredService<Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.HeaderPropagation.HeaderPropagationOptions>>()
HeaderPropagationHttpClientBuilderExtensions.<>c.<AddHeaderPropagation>b__0_0()
HttpClientBuilderExtensions.<>c__DisplayClass3_0.<AddHttpMessageHandler>b__1()
DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0()
LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass2_0.<Configure>b__0()
DefaultHttpClientFactory.CreateHandlerEntry()
DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__1()
Lazy<ActiveHandlerTrackingEntry>.ViaFactory()
Lazy<__Canon>.ExecutionAndPublication()
Lazy<ActiveHandlerTrackingEntry>.CreateValue()
Lazy<__Canon>.get_Value()
DefaultHttpClientFactory.CreateHandler()
DefaultHttpClientFactory.CreateClient()
HttpClientBuilderExtensions.<>c__DisplayClass10_0<TypedHttpClient>.<AddTypedClientCore>b__0()
CallSiteRuntimeResolver.VisitFactory()
CallSiteVisitor<RuntimeResolverContext, object>.VisitCallSiteMain()
CallSiteRuntimeResolver.VisitDisposeCache()
CallSiteVisitor<RuntimeResolverContext, object>.VisitCallSite() [1]
CallSiteRuntimeResolver.Resolve() [1]
DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0() [1]
ServiceProviderEngine.GetService() [1]
ServiceProviderEngineScope.GetService() [1]
ActivatorUtilities.GetService()
[Lightweight Method Call]
ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0()
ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0()
ControllerActionInvoker.Next()
ControllerActionInvoker.InvokeInnerFilterAsync()
ResourceInvoker.Next()
ResourceInvoker.InvokeFilterPipelineAsync()
ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d>()
ResourceInvoker.<InvokeAsync>g__Logged|17_1()
ResourceInvoker.InvokeAsync()
ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0()
EndpointMiddleware.Invoke()
AuthorizationMiddleware.<Invoke>d__5.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__5>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__5>()
AuthorizationMiddleware.Invoke()
EndpointRoutingMiddleware.SetRoutingAndContinue()
EndpointRoutingMiddleware.Invoke()
HeaderPropagationMiddleware.<Invoke>d__4.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.HeaderPropagation.HeaderPropagationMiddleware.<Invoke>d__4>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.HeaderPropagation.HeaderPropagationMiddleware.<Invoke>d__4>()
HeaderPropagationMiddleware.Invoke()
HttpsRedirectionMiddleware.Invoke()
DeveloperExceptionPageMiddleware.<Invoke>d__9.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__9>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__9>()
DeveloperExceptionPageMiddleware.Invoke()
HostFilteringMiddleware.Invoke()
HostingApplication.ProcessRequestAsync()
ApplicationWrapper<HostingApplication.Context>.Microsoft.AspNetCore.Hosting.Server.IHttpApplication<TContext>.ProcessRequestAsync()
ApplicationWrapper<HostingApplication.Context>.ProcessRequestAsync()
HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d>()
HttpContextBuilder.<>c__DisplayClass23_0.<SendAsync>g__RunRequestAsync|0()
HttpContextBuilder.<>c__DisplayClass23_0.<SendAsync>b__1()
QueueUserWorkItemCallbackDefaultContext.Execute()
ThreadPoolWorkQueue.Dispatch()
_ThreadPoolWaitCallback.PerformWaitCallback()
[Native to Managed Transition]
```

dotnet --info:
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   3.1.101
 Commit:    b377529961

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

The workaround is to register singleton service as scoped, of course. But I mainly expects some guidelines/documentation notes about such case. Is it a real bug to fix or is it unsupported servces scopes configuration - then the DI runtime validation could be expanded to such cases?

### PR DESCRIPTION
**Pull request by maryamariyan**
Introducing per singleton lock for the code path which resolves singletons.

The repro test case in https://github.com/dotnet/runtime/issues/35986#issuecomment-670302230 gets fixed with this change.

Fixes: https://github.com/dotnet/runtime/issues/35986

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs [hunk 1]
```diff
@@ -55,26 +57,61 @@ protected override object VisitConstructor(ConstructorCallSite constructorCallSi
...
 
-        protected override object VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
+        protected override object VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         {
             // Check if we are in the situation where scoped service was promoted to singleton
             // and we need to lock the root
             RuntimeResolverLock requiredScope = context.Scope == context.Scope.Engine.Root ?
                 RuntimeResolverLock.Root :
                 RuntimeResolverLock.Scope;
+            // treat as singleton:
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:104]: - [ ] simplify here

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 2]
```diff
@@ -375,6 +375,98 @@ public async Task AddDisposablesAndAsyncDisposables_DisposeAsync_AllDisposed(boo
             }
         }
 
+        [ThreadStatic]
+        public static int ThreadId;
+
+        [Fact]
+        public async Task TestDeadlock()
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:382]: - [ ] clean up test, or prepare a simpler one.

**Comment by davidfowl** [comment]
I think you should try to use the call site itself as the lock for singletons

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 3]
```diff
@@ -406,6 +406,242 @@ public void Dispose()
...
+        private class Thing0
+        {
+            public Thing0()
+            {
+            }
+        }
+
+        [Fact]
+        [ActiveIssue("https://github.com/dotnet/runtime/issues/36458")]
+        public void GetRequiredService_CircularReference_ThrowsSOEAndHangs()
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:612]: I'm a bit confused by this test. We are adding a new test for an issue that we know is currently broken? Why not add this test when we fix #36458?

**Comment by eerhardt** [comment]
Since this is pretty core logic that affects a lot of ASP.NET, is it possible to run all of ASP.NET's tests on this change before merging? How easy would that be @davidfowl @Tratcher @pranavkm ?

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs (hunk 3 above)
Comment (maryamariyan) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:612]: sure, makes sense to remove this test.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs [hunk 4]
```diff
@@ -55,26 +57,46 @@ protected override object VisitConstructor(ConstructorCallSite constructorCallSi
...
 
-        protected override object VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
+        protected override object VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         {
             // Check if we are in the situation where scoped service was promoted to singleton
             // and we need to lock the root
             RuntimeResolverLock requiredScope = context.Scope == context.Scope.Engine.Root ?
                 RuntimeResolverLock.Root :
                 RuntimeResolverLock.Scope;
+            if (requiredScope == RuntimeResolverLock.Root)
```
Comment (pranavkm) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:90]: This needs braces. You could also consider rewriting this method:

```C#
return context.Scope == context.Scope.Engine.Root ?
   VisitRootCache(callSite, context) :
   VisitCache(callSite, context, context.Scope, RuntimeResolverLock.Scope);
```

**Review by pranavkm — COMMENTED** [review]
> How easy would that be

You could create a draft PR pointing to a build of this package and let the public CI do it's job. That shouldn't be too hard and could instill some confidence prior to merging this change.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 5]
```diff
@@ -406,6 +406,207 @@ public void Dispose()
...
+                thing0 = sp.GetRequiredService<Thing0>();
+                return new Thing1(thing0);
+            });
+
+            services.AddSingleton<Thing0>();
+            services.AddTransient(sp =>
+            {
+                if (ThreadId == 1)
+                {
+                    Thread.Sleep(1000);
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:445]: Instead of `Thread.Sleep` calls here, can we instead pass in a Task(s) (or ManualResetEvents) that can be awaited on? Then we can control the timing outside of these threads and ensure the ordering happens as we want it.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 6]
```diff
@@ -406,6 +406,207 @@ public void Dispose()
...
+        private class Thing2
+        {
+            public Thing2(Thing1 thing1)
+            {
+            }
+        }
+
+        private class Thing1
+        {
+            public Thing1(Thing0 thing2)
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:598]:
```suggestion
            public Thing1(Thing0 thing0)
```

or 

```suggestion
            public Thing1(Thing0 thing)
```

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 7]
```diff
@@ -406,6 +406,219 @@ public void Dispose()
...
+            await t1;
+            await t2;
+
+            // Assert
+            Assert.NotNull(thing0);
+            Assert.NotNull(thing1);
+            Assert.NotNull(thing2);
+        }
+
+        private ManualResetEvent _manualResetEvent = new ManualResetEvent(false);
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:483]: Instead of an instance member, can you create new ones of these in each test? Currently you aren't resetting the event in between tests, so I'm not sure the 2nd test is testing the scenario properly.

Comment (pranavkm) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:483]: From https://xunit.net/docs/shared-context#constructor, 

> xUnit.net creates a new instance of the test class for every test that is run, so any code which is placed into the constructor of the test class will be run for every single test.

**Comment by maryamariyan** [comment]
> You could create a draft PR pointing to a build of this package and let the public CI do it's job. That shouldn't be too hard and could instill some confidence prior to merging this change.

As part of this exercise I downloaded the DI package from this PR (postfixed with -ci). But it's not straightforward to test the package against aspnetcore CI since they also need the package to point to a nuget source somewhere the CI can access. 

Testing the DI package against all aspnetcore projects locally is a bit of a hassle too. I'm working with @pranavkm on this and perhaps worst case we could merge this, and test off the published package from merge, and if problems occur to revert accordingly.

**Comment by maryamariyan** [comment]
as per @eerhardt 's recommendation updated the tests to use two ManualResetEvents so we can enforce the expected order of execution we want to test for deadlock.

**Comment by maryamariyan** [comment]
Added an aspnetcore PR for preliminary testing changes here: https://github.com/dotnet/aspnetcore/pull/29437

**Review by eerhardt — APPROVED** [review]
LGTM.

The tests changes look good, and are deterministic now. Thanks for the good work here.

**Comment by davidfowl** [comment]
If github supported gifs, I would post a happy dance! This is a long standing issue with the DI container that has crippled many services.

**Review by davidfowl — APPROVED** [review]

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs [hunk 8]
```diff
@@ -55,26 +57,42 @@ protected override object VisitConstructor(ConstructorCallSite constructorCallSi
...
         }
 
-        protected override object VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
+        protected override object VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         {
-            return VisitCache(singletonCallSite, context, context.Scope.Engine.Root, RuntimeResolverLock.Root);
+            var lockType = RuntimeResolverLock.Root;
+            bool lockTaken = false;
+
+            if ((context.AcquiredLocks & lockType) == 0)
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:65]: @pakrym notice that this check here is problematic and can no longer be used since we're taking a unique lock per singleton. We don't want to skip it here anymore.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs [hunk 9]
```diff
@@ -110,6 +116,24 @@ private object VisitCache(ServiceCallSite callSite, RuntimeResolverContext conte
             }
         }
 
+        private object ResolveService(ServiceCallSite callSite, RuntimeResolverContext context, RuntimeResolverLock lockType, ServiceProviderEngineScope serviceProviderEngine)
+        {
+            Dictionary<ServiceCacheKey, object> resolvedServices = serviceProviderEngine.ResolvedServices;
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:121]: Another issue pointed out by @pakrym is that we're not synchronizing access to the dictionary, so multiple resolves can happen concurrently now and we'll try to add them to the dictionary concurrently without a lock. We may want to change the singleton dictionary to be a concurrent dictionary.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs (hunk 8 above)
Comment (maryamariyan) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:65]: I see. I'll fix both comments with test. Thanks.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs (hunk 9 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:121]: Actually a simple lock will suffice.

Comment (maryamariyan) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:121]: but if they have the same type they share a lock. is that not enough?

Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteRuntimeResolver.cs:121]: Consider 2 different threads resolving 2 different singletons at the same time. They'll each have their own lock and will resolve abs party on the same non concurrent dictionary
