### PR TITLE
JIT: Fix over-shifting logic when constant-folding `AdvSimd.ShiftRight*` and `AdvSimd.ShiftLeft*`

### LINKED ISSUE #105817: JIT: Bad result with `AdvSimd.ShiftRightLogical`
```csharp
// Generated by Fuzzlyn v2.2 on 2024-08-01 14:37:47
// Run on Arm64 MacOS
// Seed: 14773448547728333023-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256
// Reduced from 270.2 KiB to 0.4 KiB in 00:01:48
// Debug: Outputs 0
// Release: Outputs 1
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static void Main()
    {
        var vr6 = Vector128.Create<short>(1);
        var vr7 = AdvSimd.ShiftRightLogical(vr6, 16);
        var vr8 = AdvSimd.Extract(vr7, 0);
        System.Console.WriteLine(vr8);
    }
}
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #105817. `AdvSimd.ShiftRightLogical`, `AdvSimd.ShiftRightLogicalScalar`, `AdvSimd.ShiftRightArithmetic`, and `AdvSimd.ShiftRightArithmeticScalar` all have immediate bounds of `[1, sizeof(T) * 8]`, meaning they support "over-shifting" values by `sizeof(T) * 8` bits such that they become zero. The constant folding logic for these shift operations erroneously assumes over-shifting is unique to xarch intrinsics; since the above intrinsics are the only ARM64 intrinsics that leverage this folding logic at the moment, allowing over-shifting on these paths for ARM64 intrinsics seems to be the simplest solution.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib, @tannergooding PTAL, thanks!

File: src/tests/JIT/Regression/JitBlue/Runtime_105817/Runtime_105817.cs [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+        }
+    }
+
+    [Fact]
+    public static void TestOverShiftRightLogicalScalar()
+    {
+        if (AdvSimd.IsSupported)
+        {
+            var vr6 = Vector64.Create<long>(1);
+            var vr7 = AdvSimd.ShiftRightLogicalScalar(vr6, 64);
```
Comment (tannergooding) [inline src/tests/JIT/Regression/JitBlue/Runtime_105817/Runtime_105817.cs:34]: Can we also check an out of range value like `65`? With the other change it should now be executing the `ShiftLogical` path rather than throwing, so we want to ensure its computing the right result between the two scenarios as well.

Comment (amanasifkhalid) [reply src/tests/JIT/Regression/JitBlue/Runtime_105817/Runtime_105817.cs:34]: Sure thing. #105777 only added the fallback implementation for `ShiftRightLogical`, so `ShiftRightLogicalScalar`, `ShiftRightArithmetic`, and `ShiftRightArithmeticScalar` still throw in Debug. Are you ok with me adding their fallback implementations in this PR, or would you prefer that work in a separate one?

Comment (amanasifkhalid) [reply src/tests/JIT/Regression/JitBlue/Runtime_105817/Runtime_105817.cs:34]: We weren't using the fallback APIs for non-const immediates either, so I added the `HW_Flag_NoJmpTableIMM` flag to the `ShiftRight*` APIs so we always use the fallback instead of a jump table.

**Comment by amanasifkhalid** [comment]
Using the fallback intrinsics instead of jump tables has some [nice diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763647&view=ms.vss-build-web.run-extensions-tab).

File: src/tests/JIT/Regression/JitBlue/Runtime_105621/Runtime_105621.cs [hunk 2]
```diff
@@ -35,4 +39,114 @@ public static void TestShiftToZero()
...
+        }
+    }
+
+    [Fact]
+    public static void TestShiftRightArithmeticScalarToZeroNonConst()
+    {
+        if (AdvSimd.IsSupported)
+        {
+            var vr3 = Vector64.Create<long>(128);
+            var vr4 = AdvSimd.ShiftRightArithmeticScalar(vr3, getLongImmOOB());
```
Comment (tannergooding) [inline src/tests/JIT/Regression/JitBlue/Runtime_105621/Runtime_105621.cs:148]: Could you also add equivalent tests for `ShiftLeftLogical` and `ShiftLeftLogicalScalar`?

It should help ensure we don't have `+1` more issues to handle from some missed edge case and will help ensure correct behavior in any future refactorings.

**Review by tannergooding — APPROVED** [review]
Changes LGTM. Would be nice to explicitly cover `ShiftLeftLogical` in the tests as well

File: src/tests/JIT/Regression/JitBlue/Runtime_105621/Runtime_105621.cs (hunk 2 above)
Comment (amanasifkhalid) [reply src/tests/JIT/Regression/JitBlue/Runtime_105621/Runtime_105621.cs:148]: Sure thing, looks like `ShiftLeft*` suffers from the same issues we ran into initially with `ShiftRight*`. In Debug, we don't use `ShiftLogical` as a fallback intrinsic, and we end up throwing an exception for out-of-range immediates. In Release, we constant-fold `GT_LSH` operands, but we don't allow over-shifting on ARM64, so the constant-folded behavior doesn't match what `ShiftLogical` would do. I'll add the fallback implementation in this PR to fix this in one go.

**Comment by amanasifkhalid** [comment]
@tannergooding I added fallback intrinsics for the shift-left APIs, and added test coverage. Can you PTAL? Thanks!

**Review by tannergooding — APPROVED** [review]
