### PR TITLE
Move vzeroupper emit back to JIT

### LINKED ISSUE #115672: [NETSDKE2E][ARM64][VMR]Using .NET 10 Preview 5 x64 SDK on ARM64 OS causes ".NET Host has stopped working" error.
**Affected build:**
NET 10 VMR x64 SDK:10.0.100-preview.5.25263.104(runtime-10.0.0-preview.5.25263.104)

**Steps to Reproduce:**
1.install Net 10.0.100-preview.5.25263.104 x64 SDK on win-arm64OS.
2.Add environment variables.
3.In CLI, run `dotnet --info`.

**Expected Behavior:**
dotnet --info displays normally.

**Actual Behavior:**
dotnet --info returns exception cmd stopped working.
Image
Unhandled exception. System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 80040154 Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.AllocateComObject(Void* pClassFactory)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at Microsoft.DotNet.Cli.Commands.Workload.List.VisualStudioWorkloads.GetVisualStudioInstances()
   at Microsoft.DotNet.Cli.Commands.Workload.List.VisualStudioWorkloads.GetInstalledWorkloads(IWorkloadResolver workloadResolver, InstalledWorkloadsCollection installedWorkloads, Nullable`1 sdkFeatureBand)
   at Microsoft.DotNet.Cli.Commands.Workload.WorkloadInfoHelper.AddInstalledVsWorkloads(IEnumerable`1 sdkWorkloadIds)
   at Microsoft.DotNet.Cli.Commands.Workload.WorkloadCommandParser.ShowWorkloadsInfo(ParseResult parseResult, WorkloadInfoHelper workloadInfoHelper, IReporter reporter, String dotnetDir, Boolean showVersion)
   at Microsoft.DotNet.Cli.CommandLineInfo.PrintWorkloadsInfo()
   at Microsoft.DotNet.Cli.CommandLineInfo.PrintInfo()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Fatal error.
0xC000001D
   at System.Runtime.EH.InvokeSecondPass(ExInfo ByRef, UInt32, UInt32)
   at System.Runtime.EH.DispatchEx(System.Runtime.StackFrameIterator ByRef, ExInfo ByRef)
   at System.Runtime.EH.RhThrowEx(System.Object, ExInfo ByRef)
   at System.RuntimeTypeHandle.AllocateComObject(Void*)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean)
   at Microsoft.DotNet.Cli.Commands.Workload.List.VisualStudioWorkloads.GetVisualStudioInstances()
   at Microsoft.DotNet.Cli.Commands.Workload.List.VisualStudioWorkloads.GetInstalledWorkloads(Microsoft.NET.Sdk.WorkloadManifestReader.IWorkloadResolver, Microsoft.DotNet.Cli.Commands.Workload.List.InstalledWorkloadsCollection, System.Nullable`1<Microsoft.NET.Sdk.WorkloadManifestReader.SdkFeatureBand>)
   at Microsoft.DotNet.Cli.Commands.Workload.WorkloadInfoHelper.AddInstalledVsWorkloads(System.Collections.Generic.IEnumerable`1<Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadId>)
   at Microsoft.DotNet.Cli.Commands.Workload.WorkloadCommandParser.ShowWorkloadsInfo(System.CommandLine.ParseResult, Microsoft.DotNet.Cli.Commands.Workload.WorkloadInfoHelper, Microsoft.DotNet.Cli.Utils.IReporter, System.String, Boolean)
   at Microsoft.DotNet.Cli.CommandLineInfo.PrintWorkloadsInfo()
   at Microsoft.DotNet.Cli.CommandLineInfo.PrintInfo()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(System.String[], System.TimeSpan, Microsoft.DotNet.Cli.Telemetry.ITelemetry)
   at Microsoft.DotNet.Cli.Program.Main(System.String[])

**Note:**
1.This behavior does not repro on win-x64OS.
Image
2.This issue does not repro on regular build. --Version 10.0.100-preview.5.25263.6
Image
3.The same issue occurs with the x64.zip on win-arm64 OS.

dotnet --info:
.NET SDK:
 Version:           10.0.100-preview.5.25263.104
 Commit:            5d437e96e4
 Workload version:  10.0.100-manifests.422acc65
 MSBuild version:   17.15.0-preview-25263-104+5d437e96e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-arm64
 Base Path:   C:\Program Files\dotnet\sdk\10.0.100-preview.5.25263.104\

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
Workloads are configured to install and update using workload versions, but none were found. Run "dotnet workload restore" to install a workload version.

Host:
  Version:      10.0.0-preview.5.25263.104
  Architecture: arm64
  Commit:       5d437e96e4

.NET SDKs installed:
  10.0.100-preview.5.25263.104 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 10.0.0-preview.5.25263.104 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 10.0.0-preview.5.25263.104 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 10.0.0-preview.5.25263.104 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### PR DESCRIPTION
**Pull request by jkotas**
vzeroupper is AVX instruction and so it cannot be executed unconditionally in static asm helpers

Fixes #115672

### CODE REVIEW

File: src/coreclr/jit/codegenxarch.cpp [hunk 1]
```diff
@@ -4879,7 +4879,8 @@ void CodeGen::genCodeForShift(GenTree* tree)
         {
             int shiftByValue = (int)shiftBy->AsIntConCommon()->IconValue();
 
-            if (tree->OperIsRotate() && compiler->compOpportunisticallyDependsOn(InstructionSet_BMI2) && !tree->gtSetFlags())
+            if (tree->OperIsRotate() && compiler->compOpportunisticallyDependsOn(InstructionSet_BMI2) &&
```
Comment (jkotas) [inline src/coreclr/jit/codegenxarch.cpp:4882]: Changes from jit format

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/codegencommon.cpp [hunk 2]
```diff
@@ -5285,8 +5285,10 @@ void CodeGen::genFnProlog()
 #endif // TARGET_ARMARCH
 
 #if defined(TARGET_XARCH)
+    genClearAvxStateInProlog();
+
     // Preserve callee saved float regs to stack.
-    genPreserveCalleeSavedFltRegs(compiler->compLclFrameSize);
+    genPreserveCalleeSavedFltRegs();
```
Comment (tannergooding) [inline src/coreclr/jit/codegencommon.cpp:5291]: Any reason why you call it before rather than just as part of `genPreserveCalleeSavedFltRegs`?

I don't expect us to get more calls to preserve registers in the future, but seems like something that "could" be grouped

File: src/coreclr/jit/codegenxarch.cpp [hunk 3]
```diff
@@ -10452,8 +10454,10 @@ void CodeGen::genFnEpilog(BasicBlock* block)
     }
 #endif
 
+    genClearAvxStateInEpilog();
+
     // Restore float registers that were saved to stack before SP is modified.
-    genRestoreCalleeSavedFltRegs(compiler->compLclFrameSize);
+    genRestoreCalleeSavedFltRegs();
```
Comment (tannergooding) [inline src/coreclr/jit/codegenxarch.cpp:10460]: Similar question here around the epilog and just calling `genClearAvxStateInEpilog` as part of `genRestoreCalleeSavedFltRegs`

File: src/coreclr/jit/codegenxarch.cpp [hunk 4]
```diff
@@ -11470,6 +11449,45 @@ void CodeGen::genRestoreCalleeSavedFltRegs(unsigned lclFrameSize)
     }
 }
 
+//-----------------------------------------------------------------------------------
+// genClearAvxStateInProlog: Generate vzeroupper instruction to clear AVX state if necessary in a prolog
+//
+void CodeGen::genClearAvxStateInProlog()
+{
+    if (GetEmitter()->ContainsCallNeedingVzeroupper() && !GetEmitter()->Contains256bitOrMoreAVX())
```
Comment (tannergooding) [inline src/coreclr/jit/codegenxarch.cpp:11457]: Just double checking, the funclet calls will return `true` for `ContainsCallNeedingVzeroupper`, correct?

Comment (jkotas) [reply src/coreclr/jit/codegenxarch.cpp:11457]: Yes, the flag is for the whole method. It is approximation. We will emit vzeroupper even when there is no actual call needing it in the given funclet.

File: src/coreclr/jit/codegencommon.cpp (hunk 2 above)
Comment (jkotas) [reply src/coreclr/jit/codegencommon.cpp:5291]: I have done it this was so that the flow of genFnProlog/genFnEpilog is more similar to the flow of genFuncletProlog/Epilog.

The first iteration of the fix had just called genPreserveCalleeSavedFltRegs/genRestoreCalleeSavedFltRegs with RBM_NONE from genFuncletProlog/Epilog, but that looked odd since the funclet prolog/epilog won't actually save/restore any floating-point registers. It made me to factor it out to a separate method.
