### PR TITLE
Stop throwing when attempting to validate a JObject.

### LINKED ISSUE #64207: Validator.TryValidateObject on JObject throws System.ArgumentException
### Description

When a JObject class object is validated by System.ComponentModel.DataAnnotations.Validator ArgumentException is thrown.

### Reproduction Steps

```
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json.Linq;

namespace JObjectTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var data = JObject.Parse("{\"Enabled\":true}");

            var results = new List<ValidationResult>();

            var r = Validator.TryValidateObject(data, new (data), results, true);
        }
    }
}
```

### Expected behavior

TryValidate should return true and no validation error are produced.

### Actual behavior

Following exception is thrown:
```
Unhandled exception. System.ArgumentException: The type 'JObject' does not contain a public property named 'Enabled'. (Parameter 'propertyName')
   at System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.GetPropertyStoreItem(String propertyName)
   at System.ComponentModel.DataAnnotations.ValidationAttributeStore.GetPropertyValidationAttributes(ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.Validator.GetPropertyValues(Object instance, ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.TryValidateObject(Object instance, ValidationContext validationContext, ICollection`1 validationResults, Boolean validateAllProperties)
   at JObjectTest.Program.Main(String[] args) in ...\Program.cs:line 15
```

### Regression?

Provided example is working with .NET 5.

### Known Workarounds

_No response_

### Configuration

.NET 6, x64, Windows 10

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #64207

Use the type to get property descriptors, rather than the instance, since the instance can return dynamic property descriptors that are not found on the underlying type, but the rest of validation code does not support this and uses the type.

The case of JObject would always throw on .NET Framework. It stopped throwing when the code diverged in core, and people started relying on this. Once we brought back the Framework code, it started to throw again, which broke people who had been using the Core code in the meantime.

### CODE REVIEW

File: src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/Validator.cs [hunk 1]
```diff
@@ -518,7 +518,7 @@ private static void EnsureValidPropertyType(string propertyName, Type propertyTy
         private static ICollection<KeyValuePair<ValidationContext, object?>> GetPropertyValues(object instance,
             ValidationContext validationContext)
         {
-            var properties = TypeDescriptor.GetProperties(instance);
+            var properties = TypeDescriptor.GetProperties(instance.GetType());
```
Comment (bricelam) [inline src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/Validator.cs:521]: But this will break instance-registered type descriptors...

```cs
TypeDescriptor.Add(..., instance);
Validator.TryValidateObject(instance, ...);
```

Comment (ajcvickers) [reply src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/Validator.cs:521]: But how would this ever work, since everything in `ValidationAttributeStore` is based only on the type?

Comment (bricelam) [reply src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/Validator.cs:521]: For example, you can have a separate buddy type that you use for certain objects:

```cs
TypeDescriptor.AddProvider(
    new AssociatedMetadataTypeTypeDescriptionProvider(
        typeof(User),
        typeof(SpecialUserMetadata)),
    specialUser);
```
```cs
class SpecialUserMetadata
{
    // Special users can have really long usernames.
    [StringLength(1000)]
    public string Username { get; set; }
}
```

Comment (ajcvickers) [reply src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/Validator.cs:521]: @bricelam I'm not sure how to use this. Running on .NET Framework 4.8 with the code below, the output is:

```
True
0
```

That is, the validation doesn't happen. Changing:

```C#
TypeDescriptor.AddProvider(
    new AssociatedMetadataTypeTypeDescriptionProvider(
        typeof(ThisIsTheEntity),
        typeof(ThisIsTheBuddy)),
    specialUser);
```

to

```C#
TypeDescriptor.AddProvider(
    new AssociatedMetadataTypeTypeDescriptionProvider(
        typeof(ThisIsTheEntity),
        typeof(ThisIsTheBuddy)),
    new ThisIsTheEntity());
```

Does result in validation happening.

Can you provide more information on how passing the instance is supposed to work? Is there something wrong with my test code?

```C#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ConsoleApplication1
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            var specialUser = new ThisIsTheEntity();

            TypeDescriptor.AddProvider(
                new AssociatedMetadataTypeTypeDescriptionProvider(
                    typeof(ThisIsTheEntity),
                    typeof(ThisIsTheBuddy)),
                specialUser);

            var results = new List<ValidationResult>();
            Console.WriteLine(Validator.TryValidateObject(specialUser, new ValidationContext(specialUser), results, true));
            Console.WriteLine(results.Count);
        }
    }
    
    public class ThisIsTheEntity
    {
        public string Username { get; set; }
    }

    public class ThisIsTheBuddy
    {
        [Required]
        public string Username { get; set; }
    }
}
```

**Review by bricelam — APPROVED** [review]
