### PR TITLE
JIT: emit gc updates from RRR instruction forms

### LINKED ISSUE #2186: jit\HardwareIntrinsics\X86\Bmi1\Bmi1_ro fails under jitstress/gcstress
With
```
set COMPlus_GCStress=0xC
set COMPlus_JitStress=2
set COMPlus_TieredCompilation=0
```
we get a runtime assertion failure:
```
Assert failure(PID 24128 [0x00005e40], Thread: 21576 [0x5448]): 
!CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! Object::ValidateInner + 0x65D (0x5e94950d)
CORECLR! Object::Validate + 0x181 (0x5e948e71)
CORECLR! Object::ValidatePromote + 0xB (0x5e9495c1)
CORECLR! WKS::GCHeap::Promote + 0x79 (0x5ec2e1b9)
CORECLR! GcEnumObject + 0x57 (0x5eb76ff7)
```
Failing method is `JIT.HardwareIntrinsics.X86.ScalarBinaryOpTest__BitFieldExtractUInt32:RunClassLclFldScenario`

The jit reports `eax` as gc live just after the `bextr`, when it has just been killed.
```asm
000035 call     CORINFO_HELP_NEWSFAST
00003A mov      byte  ptr [eax+10], 1
00003E mov      dword ptr [eax+4], 0x1E000000
000045 mov      word  ptr [eax+8], 0x419
00004B mov      dword ptr [classVar[0x7a034c0]], 0x1E000000
000055 mov      word  ptr [classVar[0x7a034d0]], 0x419
00005E movzx    edx, word  ptr [eax+8]
000062 mov      ecx, dword ptr [eax+4]
000065 bextr    eax, ecx, edx                       
00006A mov      dword ptr [V02+0x2 esp+06H], eax   ;; eax's gc life should end here
00006E push     edx
00006F mov      edx, dword ptr [V02+0x2 esp+06H]
000073 push     edx
000074 mov      edx, gword ptr [05EF34BCH]      'RunClassLclFldScenario'
00007A push     edx
00007B mov      edx, ecx
00007D mov      ecx, esi
00007F call     ...ValidateResult
000084 cmp      dword ptr [V06 esp+0CH], 0x1234567

F3 75          | 0025        reg ESI becoming live
4E             | 002B        reg ECX becoming live
0D             | 0030        reg ECX becoming dead
F0 42          | 003A        reg EAX becoming live
F5 B5          | 006F        push non-ptr (1)
B5             | 0074        push non-ptr (2)
56             | 007A        reg EDX becoming live
12             | 007D        reg EDX becoming dead
4A             | 007F        reg ECX becoming live
05             | 0084        reg EAX becoming dead
```
Have not done stress mode isolation yet.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
These do not produce GC refs, so make sure we end any GC liveness for the
destination register.

Also, make sure all gc stress modes announce themselves in the jit dump log.

Fixes #2186.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@tannergooding PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
The one test failure seems to be common to many test runs, so I think we can ignore it.

File: src/coreclr/src/jit/emitxarch.cpp [hunk 1]
```diff
@@ -11575,6 +11575,21 @@ BYTE* emitter::emitOutputRRR(BYTE* dst, instrDesc* id)
 
     noway_assert(!id->idGCref());
 
+    if (!emitInsCanOnlyWriteSSE2OrAVXReg(id))
```
Comment (mikedn) [inline src/coreclr/src/jit/emitxarch.cpp]: Odd that it checks the instruction instead of just checking if reg1 is XMM or GPR.

Comment (AndyAyersMS) [reply src/coreclr/src/jit/emitxarch.cpp]: That seems to be the prevailing pattern.

If the `IF_xxx` were fully descriptive, seems like we could sink all these register write GC updates into the tail end of some higher-level emit method and rely on the form to tell us which registers were written... then we'd only need to special case calls and such.

**Comment by AndyAyersMS** [comment]
@tannergooding ping...

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/src/jit/emitxarch.cpp [hunk 2]
```diff
@@ -11575,6 +11575,21 @@ BYTE* emitter::emitOutputRRR(BYTE* dst, instrDesc* id)
...
+    {
+        switch (id->idInsFmt())
+        {
+            case IF_RWR_RRD_RRD:
+            case IF_RWR_RRD_RRD_CNS:
+            case IF_RWR_RRD_RRD_RRD:
```
Comment (tannergooding) [inline src/coreclr/src/jit/emitxarch.cpp]: Any particular reason why these IF, I would think the latter two don't have any which write to an integer register.

Comment (AndyAyersMS) [reply src/coreclr/src/jit/emitxarch.cpp]: It wasn't obvious to me how to go from an IF_xxx to all the instructions that it might represent.

Comment (tannergooding) [reply src/coreclr/src/jit/emitxarch.cpp]: It isn't very straightforward/easy.

The various `emitIns_*` methods say the format via `id->idInsFmt` (e.g. https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/emitxarch.cpp#L4386).

So, AFAIK, you have to reverse your way back through the calls to those methods (and in some cases back to other callers or tables, where `ins` is picked up and passed in separately; as is the case with many HWIntrinsics).

Comment (AndyAyersMS) [reply src/coreclr/src/jit/emitxarch.cpp]: How about I add an assert that those forms aren't expected here, because of the guarding `canOnlyWrite...`.

Comment (tannergooding) [reply src/coreclr/src/jit/emitxarch.cpp]: I dont think there is any harm in having them here, was mostly just interested.

It might be nice if we had a better way to map these in the future :)

Comment (AndyAyersMS) [reply src/coreclr/src/jit/emitxarch.cpp]: Ah, ok. Will go ahead and merge then.
