### PR TITLE
Ensure all types are loaded when methods are accessed as function pointers

### LINKED ISSUE #62067: Test failure Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20211124.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1485225&view=ms.vss-test-web.build-test-results-tab&runId=42488674&paneView=debug&resultId=103086)

Failed test:
```
CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd

CoreCLR windows x64 Checked gcstress0x3 @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd

CoreCLR windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd

CoreCLR windows x64 Checked gcstress0xc @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd
```
**Error message:**
```
Assert failure(PID 3468 [0x00000d8c], Thread: 4896 [0x1320]): !th.IsNull()

CORECLR! SigPointer::GetTypeHandleThrowing + 0x620 (0x70dce98d)
CORECLR! SigPointer::PeekElemTypeNormalized + 0x1D7 (0x70dd2f32)
CORECLR! MetaSig::PeekArgNormalized + 0x20 (0x70dd2aae)
CORECLR! ArgIteratorTemplate<ArgIteratorBase>::ForceSigWalk + 0x189 (0x70c1b603)
CORECLR! ArgIteratorTemplate<ArgIteratorBase>::SizeOfArgStack + 0x10 (0x70c372cb)
CORECLR! ArgIteratorTemplate<ArgIteratorBase>::GetNextOffset + 0x66 (0x70c36338)
CORECLR! TransitionFrame::PromoteCallerStackHelper + 0x113 (0x70d0ba35)
CORECLR! TransitionFrame::PromoteCallerStack + 0xEE (0x70d0b91b)
CORECLR! GcStackCrawlCallBack + 0x1EA (0x70ec3c1a)
CORECLR! Thread::MakeStackwalkerCallback + 0x48 (0x70dd5e83)
File: D:\a_work\1\s\src\coreclr\vm\siginfo.cpp Line: 1112
Image: C:\h\w\A93B08DB\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A93B08DB\w\A06008C3\uploads\Reports\Interop.COM\Activator\ActivatorBuiltInComDisabled\ActivatorBuiltInComDisabled.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A93B08DB\p\corerun.exe" -p "System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ActivatorBuiltInComDisabled.dll
Built-in COM Disabled?: True
Running InvalidInterfaceRequest...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A93B08DB\p
C:\h\w\A93B08DB\w\A06008C3\e\Interop\COM\Activator\ActivatorBuiltInComDisabled\ActivatorBuiltInComDisabled.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_COM._Activator_ActivatorBuiltInComDisabled_ActivatorBuiltInComDisabled_._Activator_ActivatorBuiltInComDisabled_ActivatorBuiltInComDisabled_cmd()
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #62067

This issue was occurring due to Type punning using C# function pointers. Consider the following where using a function pointer can circumvent type safety. Using function pointers enables a vast array of scenarios where type loading can occur at invalid times. This PR handles cases involving Type Equivalence, direct `ldftn` and `ldvirtftn`, indirect `ldftn` and `ldvirtftn` via `Delegate` activation, and scenarios involving Generics.

``` csharp
IntPtr fptr = typeof(A.Class).GetMethod("CallMe").MethodHandle.GetFunctionPointer();
unsafe
{
    ((delegate*<B.Struct, int>)fptr)(new B.Struct() { Field = 0 });
}
namespace A
{
    struct Struct
    {
        public int Field;
    }
    class Class
    {
        public static int CallMe(Struct s) => s.Field;
    }
}
namespace B
{
    struct Struct
    {
        public int Field;
    }
}
```

/cc @jkotas @davidwrighton @AndyAyersMS @jkoritzinsky @elinor-fung

### CODE REVIEW

**Comment by jkotas** [comment]
The change is fixing the GC stress crash. On a second thought, I am wondering whether we want to make this work; or whether we should declare this invalid code and fix the test instead (e.g. by passing the struct by reference). If we decide to make this work, I think there are more places that will need the same fix.

@davidwrighton Could you please take a look and share your opinion?

The problem is:
- The test gets function pointer by calling `RuntimeMethodHandle.GetFunctionPointer`
- The target method has value type argument
- Unsafe code calls the method via function pointer with value type that has same layout, but different identify

This fails under GC stress with "valuetype type not loaded" crash when we are in the prestub of the function.

**Comment by davidwrighton** [comment]
Type punning like this isn't something that we generally support throughout the runtime, but we do support it as part of type equivalence. So, at the very minimum, we need to have the valuetypes loaded eagerly if the function pointer utilizes any type equivalent types, so a fix here is needed to some extent.

However, the fix as written makes me uncomfortable in several ways.
1. The fix will cause a potentially significant amount of work (walking the signature) each time the GetFunctionPointer api is used. We generally try to avoid repeated unnecessary work on non-initialization code paths.
2. The fix does not cover the case of function pointers created via ldftn and ldvirtftn. Those may already be covered for the type equivalence case, but I doubt they are fully covered for this type punning case.

OTOH, type punning of this form is likely common in C++/CLI and the fact that we still have this issue is likely indicative of a lack of GC stress testing on complex C++/CLI scenarios.

I think we should either scale back the fix to only cover type equivalent structures, or go the extra mile to make sure that ldftn and ldvirtftn instructions when not paired with a delegate allocation force the more complete parameter type load. Scaling back could be done by just calling `MethodDesc::HasTypeEquivalentStructParameters` from within the new `PrepareForUseAsAFunctionPointer` function. I believe that would cover the type equivalence scenario well enough.

Also, this should be tested with a type system test which is explicitly testing this, not an artifact of the COM test suite. I'd like to know if we really need this construct of type punning to use the COM api, or if something else is going on here.

**Comment by davidwrighton** [comment]
@AaronRobinsonMSFT As a set of tests covering the type punning scenarios, that looks good. Please don't check in until we conclude we actually want to support punning.

**Comment by AaronRobinsonMSFT** [comment]
An outstanding case is when `ldftn` is used for `Delegate` instantiation. Since the `Delegate` case is type safe there is no need for the full signature walk and value type load that is being done in the unsafe C# function pointer case.

It would be helpful if someone from the @dotnet/jit-contrib could provide some guidance on how one could detect the `Delegate` case in the importer. Based on debugging it appears the broad strokes are check if the next instruction is a `CEE_NEWOBJ` and then interrogate the token if it inherits from `Delegate`. I can make this check in `CEE_LDFTN` but want to ensure I'm not missing some existing helper.

https://github.com/dotnet/runtime/blob/70d20f1445127d6473283047d0a551ccf85f897f/src/coreclr/jit/importer.cpp#L14605-L14624

File: src/coreclr/ToolBox/superpmi/superpmi-shared/methodcontext.cpp [hunk 1]
```diff
@@ -4551,7 +4551,7 @@ void MethodContext::dmpGetFunctionFixedEntryPoint(DWORDLONG key, const Agnostic_
     printf("GetFunctionFixedEntryPoint key ftn-%016llX, value %s", key,
            SpmiDumpHelper::DumpAgnostic_CORINFO_CONST_LOOKUP(value).c_str());
 }
-void MethodContext::repGetFunctionFixedEntryPoint(CORINFO_METHOD_HANDLE ftn, CORINFO_CONST_LOOKUP* pResult)
+void MethodContext::repGetFunctionFixedEntryPoint(CORINFO_METHOD_HANDLE ftn, bool prepareForFPtr, CORINFO_CONST_LOOKUP* pResult)
```
Comment (AndyAyersMS) [inline src/coreclr/ToolBox/superpmi/superpmi-shared/methodcontext.cpp:4554]: This method may need to be updated to incorporate the value of `prepareForFPtr` in the key.

If `prepareForPtr` just causes different side effects in the runtime and doesn't change the return value -- which seems to be the case -- then it is ok as is, but we should leave a comment here to this effect.

File: src/coreclr/jit/morph.cpp [hunk 2]
```diff
@@ -9555,6 +9555,37 @@ GenTree* Compiler::fgMorphLeaf(GenTree* tree)
     }
     else if (tree->gtOper == GT_FTN_ADDR)
     {
+        // A function pointer address is being used. If this is for a Delegate scenario
+        // we don't need to prepare the method. However, if the function pointer is being used in
+        // an unsafe manner, as a raw function pointer, the the signature should be walked.
+        // The below logic is attempting to see if the function pointer is being passed
+        // to a Delegate .ctor.
```
Comment (AndyAyersMS) [inline src/coreclr/jit/morph.cpp:9562]: This seems potentially fragile since you're not connecting up the function pointer with its use. So in a complex tree it seems like we could deduce preparation isn't needed when it is.

So you should also check that the user of the `GT_FTN_ADDR` is an arg to the call. You can do this by walking the call arguments.

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:9562]: How does this work?

If I do the simple and naive thing for a delegate:
```cs
private static Func<int> Problem()
{
    static int Get() => 1;

    return Get;
}
```
Then by morph I see we have inlined the `.ctor` and have multiple statements around:
```scala
*************** In fgMarkAddressExposedLocals()
LocalAddressVisitor visiting statement:
STMT00000 ( 0x000[E-] ... 0x00C )
               [000005] -AC---------              *  ASG       ref   
               [000004] D------N----              +--*  LCL_VAR   ref    V01 tmp1         
               [000003] --C---------              \--*  CALL help ref    HELPER.CORINFO_HELP_NEWSFAST
               [000002] H----------- arg0            \--*  CNS_INT(h) long   0xd1ffab1e token

LocalAddressVisitor visiting statement:
STMT00003 ( INL01 @ 0x000[E-] ... ??? ) <- INLRT @ ???
               [000013] -A-XG-------              *  ASG       ref   
               [000012] ---XG--N----              +--*  FIELD     ref    _target
               [000006] ------------              |  \--*  LCL_VAR   ref    V01 tmp1         
               [000011] ------------              \--*  LCL_VAR   ref    V01 tmp1         

LocalAddressVisitor visiting statement:
STMT00004 ( INL01 @ 0x007[E-] ... ??? ) <- INLRT @ ???
               [000017] -A-XG-------              *  ASG       long  
               [000016] ---XG--N----              +--*  FIELD     long   _methodPtr
               [000014] ------------              |  \--*  LCL_VAR   ref    V01 tmp1         
               [000015] H-----------              \--*  CNS_INT(h) long   0xd1ffab1e ftn

LocalAddressVisitor visiting statement:
STMT00005 ( INL01 @ 0x00E[E-] ... ??? ) <- INLRT @ ???
               [000021] -A-XG-------              *  ASG       long  
               [000020] ---XG--N----              +--*  FIELD     long   _methodPtrAux
               [000018] ------------              |  \--*  LCL_VAR   ref    V01 tmp1         
               [000001] ------------              \--*  FTN_ADDR  long   RyuJitReproduction.Program.<Problem>g__Get|11_0


LocalAddressVisitor visiting statement:
STMT00002 ( 0x00C[--] ... ??? )
               [000010] ------------              *  RETURN    ref   
               [000009] ------------              \--*  LCL_VAR   ref    V01 tmp1         
```
Since this seems like an optimization (in other words, walking the signature is always correct, but we want to avoid it if possible), it seems like we could mark the `GT_FTN_ADDR` node with some flag, in, say, `fgOptimizeDelegateConstructor` and then look at the flag here.

File: src/coreclr/ToolBox/superpmi/superpmi-shared/methodcontext.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/ToolBox/superpmi/superpmi-shared/methodcontext.cpp:4554]: Will do. It is entirely a runtime side-effect so there should be no impact on the returned value. However, I can't be certain that will always be the case. Let me see how troublesome it is to include it in the key. If it becomes annoying, I will add a comment instead.

File: src/coreclr/jit/morph.cpp (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/jit/morph.cpp:9562]: > it seems like we could mark the GT_FTN_ADDR node with some flag, in, say, fgOptimizeDelegateConstructor and then look at the flag here.

That is an interesting idea. @AndyAyersMS ?

Comment (AndyAyersMS) [reply src/coreclr/jit/morph.cpp:9562]: Yes, this is probably a better way to go about it. `fgOptimizeDelegateConstructor ` already finds the target function node and checks for `GT_FTN_ADDR`.

Comment (AaronRobinsonMSFT) [reply src/coreclr/jit/morph.cpp]: @AndyAyersMS I added a new `GenTreeFlags` value &ndash; `GTF_DELEGATE_TGT`?

File: src/coreclr/ToolBox/superpmi/superpmi-shared/methodcontext.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/ToolBox/superpmi/superpmi-shared/methodcontext.cpp:4554]: I included the value in the key and added a comment.

File: src/coreclr/jit/morph.cpp [hunk 3]
```diff
@@ -9565,7 +9574,8 @@ GenTree* Compiler::fgMorphLeaf(GenTree* tree)
         else
 #endif
         {
-            info.compCompHnd->getFunctionFixedEntryPoint(tree->AsFptrVal()->gtFptrMethod, &addrInfo);
+            info.compCompHnd->getFunctionFixedEntryPoint(tree->AsFptrVal()->gtFptrMethod,
+                                                         prepareForUnsafeFunctionPointer, &addrInfo);
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:9578]: Can we name this something that's not so coupled to the runtime? For example flip it to `forDelegate`?

Comment (AaronRobinsonMSFT) [reply src/coreclr/jit/morph.cpp:9578]: I originally had that. I switched it to function pointer as it seems less coupled to the runtime. But the current impl does seem heavily coupled to the Delegate concept so I can switch it.

File: src/coreclr/jit/morph.cpp (hunk 2 above)
Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp]: Hmm, I don't think adding a new "shared" flag value is needed (and it would require some review to make sure there is enough space available, and it won't quite work as a "shared" one right now anyway, since the common mask wasn't adjusted). Can we not make this `GT_FTN_ADDR`-only?

File: src/coreclr/jit/morph.cpp (hunk 3 above)
Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp:9578]: The part I find coupled is the `prepare`. `isRawFptr` or `isExposedFptr` also seem fine with me.

File: src/coreclr/jit/morph.cpp (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/jit/morph.cpp]: >since the common mask wasn't adjusted

That was a mistake. Fixed.

> Can we not make this GT_FTN_ADDR-only?

I can, but that isn't the only case where it is a target. I'd prefer to have it on the `GenTree` since it seems there are cases where having a complex tree as a target is possible. I can add this somewhere else on `GenTree` but it isn't obvious where.

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp]: > I can add this somewhere else on GenTree but it isn't obvious where.

Right, the only place where this can be put is in the flags.

> I can, but that isn't the only case where it is a target. I'd prefer to have it on the GenTree since it seems there are cases where having a complex tree as a target is possible.

That is true, but it is also true that we only _need_ this information for `GT_FTN_ADDR`, it seems. Slots in the shared flags are somewhat high in value, in general, and in maintenance cost. Concretely: only the `IAT_VALUE` constant address case in `fgMorphLeaf` will preserve the flag today. Is that bug, do we need to preserve the flag? When do we need to preserve the flag? What breaks if we don't? The answers are "no", "we don't" and "nothing", but they need to be found first, with a non-shared flag they would simply not exist.

That aside, `cTreeFlags` also needs to be updated to display the flag.

Comment (AaronRobinsonMSFT) [reply src/coreclr/jit/morph.cpp]: Moved to `GenTreeFptrVal`.

**Comment by AaronRobinsonMSFT** [comment]
@davidwrighton I've pushed up all the tests for this scenario. The failing scenario was only occurring during a GCStress run so in order to confirm that needs to happen. I believe this PR is now in a good state. and can be merged unless there are further JIT or Type system concerns.

**Review by AndyAyersMS — APPROVED** [review]
LGTM.

**Comment by jkotas** [comment]
Does the fix work for crossgen/R2R?

**Comment by AaronRobinsonMSFT** [comment]
> Does the fix work for crossgen/R2R?

No. That needs to be looked at. @davidwrighton is going to pick this up next week. I might look into this weekend if I have time.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas Is there an example in CrossGen2 that I could look at that would help me to understand how to fix this there? I assume I need some new helper to call prior to the PreStub being executed.

**Comment by jkoritzinsky** [comment]
@AaronRobinsonMSFT looks like there's a sample using the old `classMustBeLoadedBeforeCodeIsRun` mechanism that you changed from here.

https://github.com/dotnet/runtime/blob/f7544966e98977232522dbee9c13530a9a604aa6/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs#L1832

Maybe you could add the checks in `CorInfoImpl.ReadyToRun.cs` in the `getCallInfo` implementation? I think you'd want to add the `WalkValueTypeParameters` function and for each value type parameter, call `classMustBeLoadedBeforeCodeIsRun` for each type. That should add the fixups that you need.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Thanks. That helped and I was able to get `ldvirtftn` and the Generics cases working. However, the `ldftn` case doesn't seem to be handled on that path. See https://github.com/dotnet/runtime/blob/f7544966e98977232522dbee9c13530a9a604aa6/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs#L1877-L1884

I am trying to figure out why. I don't see the JIT involved at all during run-time so I am confused. I could be not understanding how to debug this though.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Oops. Wrong. I misread that `if`. Let me try this again.

**Comment by AaronRobinsonMSFT** [comment]
Thanks @jkoritzinsky ! That worked and was simple to follow.

@jkotas and @davidwrighton The tests now pass under CrossGen/R2R.

@MichalStrehovsky Please take a look at the CrossGen changes and let me know if there is a better way.

File: src/coreclr/vm/method.cpp [hunk 4]
```diff
@@ -4124,6 +4072,54 @@ void MethodDesc::PrepareForUseAsADependencyOfANativeImageWorker()
     EX_END_CATCH(RethrowTerminalExceptions);
     _ASSERTE(HaveValueTypeParametersBeenWalked());
 }
+
+static void CheckForEquivalenceAndLoadType(Module *pModule, mdToken token, Module *pDefModule, mdToken defToken, const SigParser *ptr, SigTypeContext *pTypeContext, void *pData)
```
Comment (davidwrighton) [inline src/coreclr/vm/method.cpp:4076]: This function no longer behaves like the copy of `CheckForEquivalenceAndLoadType` that is in methodtable.cpp. In particular, it unconditionally loads the type unlike the code in methodtable.cpp which is carefully constructed to not trigger additional loads. Also given that both of these paths set the HaveValueTypeParametersBeenWalked flag, I think we may not have a fully functional implementation. In particular, imagine the case where a virtual function is loaded, and then later `ldftn` is used on it. I believe that the HaveValueTypeParametersBeenWalked flag will already be set, but we may not have loaded all the parameters.

**Review by davidwrighton — CHANGES_REQUESTED** [review]
Please look into the scenario of using ldftn involving type punning with a virtual method.

File: src/coreclr/vm/method.cpp (hunk 4 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/method.cpp:4076]: Just to be clear with respect to the `CheckForEquivalenceAndFullyLoadType` in `methodtable.cpp` &mdash; I assume you mean `CheckForEquivalenceAndFullyLoadType` because I can't find `CheckForEquivalenceAndLoadType` &mdash; the logic was different even before I changed anything. The one in `methodtable.cpp` has extra logic that `CheckForEquivalenceAndLoadType` never had. Specifically, a call to `DoFullyLoad()`

https://github.com/dotnet/runtime/blob/27226f631ff5e6019b7da78d350636a6e964aa3c/src/coreclr/vm/methodtable.cpp#L3908-L3916

whereas `CheckForEquivalenceAndLoadType` never had that call:

https://github.com/dotnet/runtime/blob/27226f631ff5e6019b7da78d350636a6e964aa3c/src/coreclr/vm/method.cpp#L4018-L4023

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/method.cpp:4076]: Spoke offline. This seems okay, but a new test is warranted.

**Comment by AaronRobinsonMSFT** [comment]
@davidwrighton Please take another look. I added a test for using `ldftn` on a virtual function.

**Review by davidwrighton — APPROVED** [review]
