### PR TITLE
[arm64] JIT: Enable CSE/hoisting for "arrayBase + elementOffset"

### LINKED ISSUE #35618: Code inefficiencies in loop array indexing
With a simple `for` loop around array access of an `int` array, various inefficiencies are seen in x64 and arm64 generated code, when using different loop/array index types.

Related: Induction Variable widening https://github.com/dotnet/runtime/issues/7312

Consider:
```C#
public static int arr_index_int(int[] a)
{
    int sum = 0;
    for (int i = 0; i < a.Length; i++)
    {
        sum += a[i];
    }
    return sum;
}
```
For x64, we have a sign extend in the loop because the index type is 32-bit `int` but the register is 64-bit. We should be able to eliminate this sign extension because the max array size is unsigned 31 bits (?), so the sign bits will never be used. We eliminate the bounds check presumably because of a comparison against the array Length, and Length will never have the sign bits set.

For arm64, we have the sign extension, but we also have inefficient array index calculation because it doesn't have `base + scale*index + offset` addressing mode. We currently are careful to only add a fully computed index offset to the base `ref` type, to avoid creating intermediate `byref` types: there have been bugs before with certain (negative) index expressions that led the JIT to create illegal byrefs (pointing out of the object). The index expression here is:
```asm
sxtw    x4, x2
lsl     x4, x4, #2
add     x4, x4, #16
ldr     w4, [x0, x4]
```
If we could hoist the array base address computation out of the loop (`x0 + #16`), eliminate the sign extend (see above), and use the `LSL` addressing mode, we could have:
```asm
ldr     w4, [x0, x4, LSL #2]
```
We don't even need to eliminate the sign extend, as we can use the base + offset (Extended Register) form:
```asm
ldr     w4, [x0, w4, SXTW #2]
```
Hoisting the `x0 + #16` out of the loop isn't required here: simply changing the way the index expression is generated plus enhancing support for addressing modes would be a first step; hoisting the loop-invariant `x0 + #16` would be an additional win.

<details>
  <summary>x64 assembly</summary>

```asm
G_M5005_IG01:
                                                ;; bbWeight=1    PerfScore 0.00
G_M5005_IG02:
       33C0                 xor      eax, eax
       33D2                 xor      edx, edx
       448B4108             mov      r8d, dword ptr [rcx+8]
       4585C0               test     r8d, r8d
       7E0F                 jle      SHORT G_M5005_IG04
                                                ;; bbWeight=1    PerfScore 3.75
G_M5005_IG03:
       4C63CA               movsxd   r9, edx
       4203448910           add      eax, dword ptr [rcx+4*r9+16]
       FFC2                 inc      edx
       443BC2               cmp      r8d, edx
       7FF1                 jg       SHORT G_M5005_IG03
                                                ;; bbWeight=4    PerfScore 15.00
G_M5005_IG04:
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.00
```
</details>
<details>
  <summary>arm64 assembly</summary>

```asm
G_M5005_IG01:
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
                                                ;; bbWeight=1    PerfScore 1.50
G_M5005_IG02:
        52800001          mov     w1, #0
        52800002          mov     w2, #0
        B9400803          ldr     w3, [x0,#8]
        7100007F          cmp     w3, #0
        5400012D          ble     G_M5005_IG04
                                                ;; bbWeight=1    PerfScore 5.50
G_M5005_IG03:
        93407C44          sxtw    x4, x2
        D37EF484          lsl     x4, x4, #2
        91004084          add     x4, x4, #16
        B8646804          ldr     w4, [x0, x4]
        0B010081          add     w1, w4, w1
        11000442          add     w2, w2, #1
        6B02007F          cmp     w3, w2
        54FFFF2C          bgt     G_M5005_IG03
                                                ;; bbWeight=4    PerfScore 30.00
G_M5005_IG04:
        2A0103E0          mov     w0, w1
                                                ;; bbWeight=1    PerfScore 0.50
G_M5005_IG05:
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
                                                ;; bbWeight=1    PerfScore 2.00
```
</details>

```C#
public static int arr_index_long(int[] a)
{
    int sum = 0;
    for (long i = 0; i < a.Length; i++)
    {
        sum += a[i];
    }
    return sum;
}
```
If the loop / array index variable is changed from `int` to `long`, there are some unexpected effects: (1) the JIT sign-extends the array size. The array size can never be negative, so this seems unnecessary. (2) the JIT doesn't eliminate the bounds check in the loop body.

The sign extend is eliminated, however, as expected.
<details>
  <summary>x64 assembly</summary>

```asm
G_M57268_IG01:
       4883EC28             sub      rsp, 40
                                                ;; bbWeight=1    PerfScore 0.25
G_M57268_IG02:
       33C0                 xor      eax, eax
       33D2                 xor      rdx, rdx
       448B4108             mov      r8d, dword ptr [rcx+8]
       4D63C0               movsxd   r8, r8d
       4D85C0               test     r8, r8
       7E11                 jle      SHORT G_M57268_IG04
                                                ;; bbWeight=1    PerfScore 4.00
G_M57268_IG03:
       493BD0               cmp      rdx, r8
       7311                 jae      SHORT G_M57268_IG05
       03449110             add      eax, dword ptr [rcx+4*rdx+16]
       48FFC2               inc      rdx
       4C3BC2               cmp      r8, rdx
       7FEF                 jg       SHORT G_M57268_IG03
                                                ;; bbWeight=4    PerfScore 19.00
G_M57268_IG04:
       4883C428             add      rsp, 40
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.25
G_M57268_IG05:
       E8A10D415E           call     CORINFO_HELP_RNGCHKFAIL
       CC                   int3
                                                ;; bbWeight=0    PerfScore 0.00
```
</details>
<details>
  <summary>arm64 assembly</summary>

```asm
G_M57268_IG01:
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
                                                ;; bbWeight=1    PerfScore 1.50
G_M57268_IG02:
        52800001          mov     w1, #0
        D2800002          mov     x2, #0
        B9400803          ldr     w3, [x0,#8]
        93407C63          sxtw    x3, x3
        F100007F          cmp     x3, #0
        5400014D          ble     G_M57268_IG04
                                                ;; bbWeight=1    PerfScore 6.00
G_M57268_IG03:
        EB03005F          cmp     x2, x3
        54000162          bhs     G_M57268_IG06
        D37EF444          lsl     x4, x2, #2
        91004084          add     x4, x4, #16
        B8646804          ldr     w4, [x0, x4]
        0B010081          add     w1, w4, w1
        91000442          add     x2, x2, #1
        EB02007F          cmp     x3, x2
        54FFFF0C          bgt     G_M57268_IG03
                                                ;; bbWeight=4    PerfScore 34.00
G_M57268_IG04:
        2A0103E0          mov     w0, w1
                                                ;; bbWeight=1    PerfScore 0.50
G_M57268_IG05:
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
                                                ;; bbWeight=1    PerfScore 2.00
G_M57268_IG06:
        94000000          bl      CORINFO_HELP_RNGCHKFAIL
        D43E0000          bkpt
                                                ;; bbWeight=0    PerfScore 0.00
```
</details>

```C#
public static int arr_index_uint(int[] a)
{
    int sum = 0;
    for (uint i = 0; i < a.Length; i++)
    {
        sum += a[i];
    }
    return sum;
}
```
Changing the index variable to `uint` retains the bounds check and array length sign extend, as for `long`. Oddly, it also adds a sign extend of the index variable before the addressing mode.

<details>
  <summary>x64 assembly</summary>

```asm
G_M57944_IG01:
       4883EC28             sub      rsp, 40
                                                ;; bbWeight=1    PerfScore 0.25
G_M57944_IG02:
       33C0                 xor      eax, eax
       33D2                 xor      edx, edx
       448B4108             mov      r8d, dword ptr [rcx+8]
       4D63C8               movsxd   r9, r8d
       4D85C9               test     r9, r9
       7E17                 jle      SHORT G_M57944_IG04
                                                ;; bbWeight=1    PerfScore 4.00
G_M57944_IG03:
       413BD0               cmp      edx, r8d
       7317                 jae      SHORT G_M57944_IG05
       4C63D2               movsxd   r10, edx
       4203449110           add      eax, dword ptr [rcx+4*r10+16]
       FFC2                 inc      edx
       448BD2               mov      r10d, edx
       4D3BCA               cmp      r9, r10
       7FE9                 jg       SHORT G_M57944_IG03
                                                ;; bbWeight=4    PerfScore 21.00
G_M57944_IG04:
       4883C428             add      rsp, 40
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.25
G_M57944_IG05:
       E84B0D405E           call     CORINFO_HELP_RNGCHKFAIL
       CC                   int3
                                                ;; bbWeight=0    PerfScore 0.00
```
</details>
<details>
  <summary>arm64 assembly</summary>

```asm
G_M57944_IG01:
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
                                                ;; bbWeight=1    PerfScore 1.50
G_M57944_IG02:
        52800001          mov     w1, #0
        52800002          mov     w2, #0
        B9400803          ldr     w3, [x0,#8]
        93407C64          sxtw    x4, x3
        F100009F          cmp     x4, #0
        5400018D          ble     G_M57944_IG04
                                                ;; bbWeight=1    PerfScore 6.00
G_M57944_IG03:
        6B03005F          cmp     w2, w3
        540001A2          bhs     G_M57944_IG06
        93407C45          sxtw    x5, x2
        D37EF4A5          lsl     x5, x5, #2
        910040A5          add     x5, x5, #16
        B8656805          ldr     w5, [x0, x5]
        0B0100A1          add     w1, w5, w1
        11000442          add     w2, w2, #1
        2A0203E5          mov     w5, w2
        EB05009F          cmp     x4, x5
        54FFFECC          bgt     G_M57944_IG03
                                                ;; bbWeight=4    PerfScore 38.00
G_M57944_IG04:
        2A0103E0          mov     w0, w1
                                                ;; bbWeight=1    PerfScore 0.50
G_M57944_IG05:
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
                                                ;; bbWeight=1    PerfScore 2.00
G_M57944_IG06:
        94000000          bl      CORINFO_HELP_RNGCHKFAIL
        D43E0000          bkpt
                                                ;; bbWeight=0    PerfScore 0.00
```
</details>

```C#
public static int arr_index_ulong(int[] a)
{
    int sum = 0;
    for (ulong i = 0; i < (ulong)a.Length; i++)
    {
        sum += a[i];
    }
    return sum;
}
```
Changing the index variable to `ulong` adds an overflow check to the loop as well as a range check. Why is the overflow check necessary?

<details>
  <summary>x64 assembly</summary>

```asm
G_M30337_IG01:
       4883EC28             sub      rsp, 40
                                                ;; bbWeight=1    PerfScore 0.25
G_M30337_IG02:
       33C0                 xor      eax, eax
       33D2                 xor      rdx, rdx
       448B4108             mov      r8d, dword ptr [rcx+8]
       4D63C0               movsxd   r8, r8d
       4D85C0               test     r8, r8
       741A                 je       SHORT G_M30337_IG04
                                                ;; bbWeight=1    PerfScore 4.00
G_M30337_IG03:
       4885D2               test     rdx, rdx
       7C1A                 jl       SHORT G_M30337_IG05
       4C8BCA               mov      r9, rdx
       4D3BC8               cmp      r9, r8
       7318                 jae      SHORT G_M30337_IG06
       4203448910           add      eax, dword ptr [rcx+4*r9+16]
       48FFC2               inc      rdx
       4C3BC2               cmp      r8, rdx
       77E6                 ja       SHORT G_M30337_IG03
                                                ;; bbWeight=4    PerfScore 25.00
G_M30337_IG04:
       4883C428             add      rsp, 40
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.25
G_M30337_IG05:
       E8B82F425E           call     CORINFO_HELP_OVERFLOW
       CC                   int3
                                                ;; bbWeight=0    PerfScore 0.00
G_M30337_IG06:
       E8F20C425E           call     CORINFO_HELP_RNGCHKFAIL
       CC                   int3
                                                ;; bbWeight=0    PerfScore 0.00
```
</details>
<details>
  <summary>arm64 assembly</summary>

```asm
G_M30337_IG01:
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
                                                ;; bbWeight=1    PerfScore 1.50
G_M30337_IG02:
        52800001          mov     w1, #0
        D2800002          mov     x2, #0
        B9400803          ldr     w3, [x0,#8]
        93407C63          sxtw    x3, x3
        B40001A3          cbz     x3, G_M30337_IG04
                                                ;; bbWeight=1    PerfScore 5.50
G_M30337_IG03:
        F100005F          cmp     x2, #0
        540001CB          blt     G_M30337_IG06
        AA0203E4          mov     x4, x2
        EB03009F          cmp     x4, x3
        54000182          bhs     G_M30337_IG07
        D37EF484          lsl     x4, x4, #2
        91004084          add     x4, x4, #16
        B8646804          ldr     w4, [x0, x4]
        0B010081          add     w1, w4, w1
        91000442          add     x2, x2, #1
        EB02007F          cmp     x3, x2
        54FFFEA8          bhi     G_M30337_IG03
                                                ;; bbWeight=4    PerfScore 42.00
G_M30337_IG04:
        2A0103E0          mov     w0, w1
                                                ;; bbWeight=1    PerfScore 0.50
G_M30337_IG05:
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
                                                ;; bbWeight=1    PerfScore 2.00
G_M30337_IG06:
        94000000          bl      CORINFO_HELP_OVERFLOW
                                                ;; bbWeight=0    PerfScore 0.00
G_M30337_IG07:
        94000000          bl      CORINFO_HELP_RNGCHKFAIL
        D43E0000          bkpt
                                                ;; bbWeight=0    PerfScore 0.00
```
</details>

category:cq
theme:loop-opt
skill-level:intermediate
cost:medium

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/35618, https://github.com/dotnet/runtime/issues/34810

Usually, for a typical array access we create the following tree
```
arrRef + (index + elemOffset)
```
which is basically `invariant1 + (X + invariant2)`, if we change it to:
```
(arrRef + elemOffset) + index
```
_I assume it's safe from GC's point of view, both ADDs are byref and within the objects_ 

we'll be able to hoist/CSE the invariant part `arrRef + elemOffset` on arm/arm64. We don't really need it on XArch because it will be handled by a more powerful addressing mode such as `mov      r9d, dword ptr [rdx+4*r9+16]`.
So, essentially, this PR changes morphing of GT_INDEX like this:
  
image

**UPD** Also, this PR folds LEA(BFIZ) into load/store with scale and sign/zero extension.

Example:
```csharp
int Test(int[] array, int i, int j) 
    => array[i] + array[j];

int Sum(int[] array)
{
    int sum = 0;
    foreach (int item in array)
        sum += item;
    return sum;
}
```
codegen diff:
```diff
; Method Tests:Test(System.Int32[],int,int):int:this
G_M15096_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
G_M15096_IG02:
            ldr     w0, [x1,#8]
            cmp     w2, w0
            bhs     G_M15096_IG04
-           ubfiz   x2, x2, #2, #32
            add     x2, x2, #16
-           ldr     w2, [x1, x2]
+           ldr     w2, [x1, w2, UXTW #2]
            cmp     w3, w0
            bhs     G_M15096_IG04
-           ubfiz   x0, x3, #2, #32
-           add     x0, x0, #16     ;; CSE'd
-           ldr     w0, [x1, x0]
+           ldr     w0, [x1, w3, UXTW #2]
            add     w0, w2, w0
G_M15096_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
G_M15096_IG04:
            bl      CORINFO_HELP_RNGCHKFAIL
            bkpt    
-; Total bytes of code: 72
+; Total bytes of code: 60


; Method Tests:Sum(System.Int32[]):int:this
G_M56165_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
G_M56165_IG02:
            mov     w0, wzr
            mov     w2, wzr
            ldr     w3, [x1,#8]
            cmp     w3, #0
            ble     G_M56165_IG04
+           add     x1, x1, #16    ;; 'baseRef + elemOffset' is hoisted
G_M56165_IG03:
-           ubfiz   x4, x2, #2, #32
-           add     x4, x4, #16
-           ldr     w4, [x1, x4]    ;; -2 4byte instructions from the loop body, it has now a perfect codegen
+           ldr     w4, [x1, w2, UXTW #2]
            add     w0, w0, w4
            add     w2, w2, #1
            cmp     w3, w2
            bgt     G_M56165_IG03
G_M56165_IG04:
            ldp     fp, lr, [sp],#16
            ret     lr
-; Total bytes of code: 64
+; Total bytes of code: 60


```
Benchmark: "Sum all elements in an array":
```csharp
[Benchmark]
[ArgumentsSource(nameof(TestData))]
public int Sum(int[] array)
{
    int sum = 0;
    foreach (int t in array)
        sum += t;
    return sum;
}
```
Benchmark results on Apple M1 arm64:
```
                             | Method |         array |     Mean |    Error |
                             |------- |-------------- |---------:|---------:|
Main without #61045 + #61035 |    Sum | Int32[100000] | 60,08 us | 0.015 us | .NET 6.0 codegen
                Current Main |    Sum | Int32[100000] | 53.78 us | 0.007 us |
                     This PR |    Sum | Int32[100000] | 32.61 us | 0.082 us | ~2x faster than .NET 6.0 here
```
_^ tested with and without loop-alignment_

Codegen diff:
- Main before #61045 and #61035 (basically, it's .NET 6.0 codegen) vs This PR https://www.diffchecker.com/smwmMHvi

Diffs are big but in both - and + directions:

## benchmarks.run.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 7603860 (overridden on cmd)
Total bytes of diff: 7582960 (overridden on cmd)
Total bytes of delta: -20900 (-0.27 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
          48 : 1745.dasm (2.82% of base)
          48 : 3317.dasm (2.86% of base)
          48 : 6982.dasm (2.12% of base)
          36 : 829.dasm (3.00% of base)
          32 : 19120.dasm (8.33% of base)
          28 : 8405.dasm (2.06% of base)
          24 : 21759.dasm (1.59% of base)
          24 : 18601.dasm (7.79% of base)
          24 : 6662.dasm (6.00% of base)
          24 : 14412.dasm (1.42% of base)
          24 : 8565.dasm (2.90% of base)
          20 : 1037.dasm (4.46% of base)
          16 : 11927.dasm (3.10% of base)
          16 : 2104.dasm (1.38% of base)
          16 : 416.dasm (2.35% of base)
          16 : 6641.dasm (1.98% of base)
          16 : 1734.dasm (2.20% of base)
          12 : 12997.dasm (0.54% of base)
          12 : 16129.dasm (5.88% of base)
          12 : 3046.dasm (3.37% of base)

Top file improvements (bytes):
        -660 : 3506.dasm (-6.48% of base)
        -520 : 19287.dasm (-8.86% of base)
        -512 : 12906.dasm (-12.77% of base)
        -508 : 23202.dasm (-8.34% of base)
        -504 : 15238.dasm (-8.21% of base)
        -500 : 13550.dasm (-2.09% of base)
        -484 : 21964.dasm (-8.85% of base)
        -436 : 14847.dasm (-11.83% of base)
        -344 : 2494.dasm (-1.85% of base)
        -324 : 1245.dasm (-4.29% of base)
        -324 : 2715.dasm (-3.20% of base)
        -324 : 11506.dasm (-3.20% of base)
        -248 : 19341.dasm (-4.62% of base)
        -248 : 21403.dasm (-2.68% of base)
        -244 : 6643.dasm (-1.40% of base)
        -240 : 12513.dasm (-5.37% of base)
        -236 : 2714.dasm (-2.38% of base)
        -236 : 22578.dasm (-2.41% of base)
        -220 : 18295.dasm (-3.24% of base)
        -220 : 11505.dasm (-3.13% of base)

1220 total files with Code Size differences (1136 improved, 84 regressed), 368 unchanged.

Top method regressions (bytes):
          48 ( 2.82% of base) : 1745.dasm - System.Reflection.Emit.MethodBuilder:CreateMethodBodyHelper(System.Reflection.Emit.ILGenerator):this
          48 ( 2.12% of base) : 6982.dasm - System.Runtime.Serialization.Formatters.Binary.ObjectWriter:WriteArray(System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo,System.Runtime.Serialization.Formatters.Binary.NameInfo,System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo):this
          48 ( 2.86% of base) : 3317.dasm - System.Xml.XmlConvert:EncodeName(System.String,bool,bool):System.String
          36 ( 3.00% of base) : 829.dasm - System.Sha1ForNonSecretPurposes:Finish(System.Span`1[Byte]):this
          32 ( 8.33% of base) : 19120.dasm - System.Collections.Concurrent.ConcurrentBag`1[Int32][System.Int32]:ToArray():System.Int32[]:this
          28 ( 2.06% of base) : 8405.dasm - System.Diagnostics.StackFrameHelper:InitializeSourceInfo(int,bool,System.Exception):this
          24 ( 7.79% of base) : 18601.dasm - Benchstone.BenchI.AddArray:Test():bool:this
          24 ( 1.42% of base) : 14412.dasm - MessagePack.Formatters.MicroBenchmarks_Serializers_CollectionsOfPrimitivesFormatter1:Deserialize(System.Byte[],int,MessagePack.IFormatterResolver,byref):MicroBenchmarks.Serializers.CollectionsOfPrimitives:this
          24 ( 1.59% of base) : 21759.dasm - System.Buffers.Text.Utf8Formatter:TryFormat(System.Decimal,System.Span`1[Byte],byref,System.Buffers.StandardFormat):bool
          24 ( 6.00% of base) : 6662.dasm - System.Text.RegularExpressions.RegexCompiler:Goto(int):this
          24 ( 2.90% of base) : 8565.dasm - Utf8Json.JsonSerializer:Deserialize(System.IO.Stream,Utf8Json.IJsonFormatterResolver):System.__Canon
          20 ( 4.46% of base) : 1037.dasm - System.TimeZoneInfo:TryConvertIanaIdToWindowsId(System.String,bool,byref):bool
          16 ( 3.10% of base) : 11927.dasm - Benchstone.BenchI.XposMatrix:Inner(System.Int32[][],int)
          16 ( 1.38% of base) : 2104.dasm - System.DefaultBinder:FindMostSpecific(System.Reflection.ParameterInfo[],System.Int32[],System.Type,System.Reflection.ParameterInfo[],System.Int32[],System.Type,System.Type[],System.Object[]):int
          16 ( 2.35% of base) : 416.dasm - System.Reflection.Associates:AssignAssociates(int,System.RuntimeType,System.RuntimeType):System.Reflection.RuntimeMethodInfo
          16 ( 2.20% of base) : 1734.dasm - System.Reflection.Emit.__ExceptionInfo:MarkHelper(int,int,System.Type,int):this
          16 ( 1.98% of base) : 6641.dasm - System.Text.RegularExpressions.RegexCompiler:GenerateForwardSection():this
          12 ( 1.86% of base) : 20019.dasm - Benchstone.BenchI.Array2:Bench(int):bool
          12 ( 2.11% of base) : 20022.dasm - Benchstone.BenchI.Array2:VerifyCopy(System.Int32[][][],System.Int32[][][]):bool
          12 ( 1.03% of base) : 10242.dasm - EMFloat:AddSubInternalFPF(ubyte,byref,byref,byref)

Top method improvements (bytes):
        -660 (-6.48% of base) : 3506.dasm - System.Text.RegularExpressions.RegexInterpreter:Go():this
        -520 (-8.86% of base) : 19287.dasm - DynamicClass:Regex4_Go(System.Text.RegularExpressions.RegexRunner)
        -512 (-12.77% of base) : 12906.dasm - DynamicClass:Regex3_Go(System.Text.RegularExpressions.RegexRunner)
        -508 (-8.34% of base) : 23202.dasm - DynamicClass:Regex1_Go(System.Text.RegularExpressions.RegexRunner)
        -504 (-8.21% of base) : 15238.dasm - DynamicClass:Regex4_Go(System.Text.RegularExpressions.RegexRunner)
        -500 (-2.09% of base) : 13550.dasm - DynamicClass:_DynamicMethod0(System.IO.TextWriter,MicroBenchmarks.Serializers.MyEventsListerItem,int)
        -484 (-8.85% of base) : 21964.dasm - DynamicClass:Regex1_Go(System.Text.RegularExpressions.RegexRunner)
        -436 (-11.83% of base) : 14847.dasm - DynamicClass:Regex3_Go(System.Text.RegularExpressions.RegexRunner)
        -344 (-1.85% of base) : 2494.dasm - DynamicClass:_DynamicMethod0(System.IO.TextWriter,MicroBenchmarks.Serializers.IndexViewModel,int)
        -324 (-3.20% of base) : 11506.dasm - Jil.Deserialize.Methods:ParseISO8601Date(System.IO.TextReader,System.Char[],int,int):System.DateTime
        -324 (-3.20% of base) : 2715.dasm - Jil.Deserialize.Methods:ParseISO8601DateThunkReader(byref,System.Char[],int,int):System.DateTime
        -324 (-4.29% of base) : 1245.dasm - System.Text.RegularExpressions.RegexWriter:EmitFragment(int,System.Text.RegularExpressions.RegexNode,int):this
        -248 (-2.68% of base) : 21403.dasm - DynamicClass:Regex2_Go(System.Text.RegularExpressions.RegexRunner)
        -248 (-4.62% of base) : 19341.dasm - Utf8Json.Formatters.ISO8601DateTimeFormatter:Deserialize(byref,Utf8Json.IJsonFormatterResolver):System.DateTime:this
        -244 (-1.40% of base) : 6643.dasm - System.Text.RegularExpressions.RegexCompiler:GenerateOneCode():this
        -240 (-5.37% of base) : 12513.dasm - Utf8Json.Formatters.ISO8601DateTimeOffsetFormatter:Deserialize(byref,Utf8Json.IJsonFormatterResolver):System.DateTimeOffset:this
        -236 (-2.41% of base) : 22578.dasm - Jil.Deserialize.Methods:_ReadISO8601DateThunkReader(byref,System.Char[]):System.DateTime
        -236 (-2.38% of base) : 2714.dasm - Jil.Deserialize.Methods:_ReadISO8601DateWithOffsetThunkReader(byref,System.Char[]):System.DateTimeOffset
        -220 (-3.24% of base) : 18295.dasm - Jil.Deserialize.Methods:_ReadISO8601Date(System.IO.TextReader,System.Char[]):System.DateTime
        -220 (-3.13% of base) : 11505.dasm - Jil.Deserialize.Methods:_ReadISO8601DateWithOffset(System.IO.TextReader,System.Char[]):System.DateTimeOffset

Top method regressions (percentages):
          32 ( 8.33% of base) : 19120.dasm - System.Collections.Concurrent.ConcurrentBag`1[Int32][System.Int32]:ToArray():System.Int32[]:this
          24 ( 7.79% of base) : 18601.dasm - Benchstone.BenchI.AddArray:Test():bool:this
          12 ( 7.50% of base) : 14104.dasm - System.Collections.CreateAddAndClear`1[Int32][System.Int32]:Array():System.Int32[]:this
          24 ( 6.00% of base) : 6662.dasm - System.Text.RegularExpressions.RegexCompiler:Goto(int):this
          12 ( 5.88% of base) : 16129.dasm - Microsoft.CodeAnalysis.Collections.ByteSequenceComparer:Equals(System.Collections.Immutable.ImmutableArray`1[Byte],System.Collections.Immutable.ImmutableArray`1[Byte]):bool
          12 ( 5.88% of base) : 17988.dasm - System.Reflection.Internal.ByteSequenceComparer:Equals(System.Collections.Immutable.ImmutableArray`1[Byte],System.Collections.Immutable.ImmutableArray`1[Byte]):bool
          12 ( 5.17% of base) : 5864.dasm - SslCredKey:Equals(SslCredKey):bool:this
          12 ( 4.48% of base) : 5945.dasm - System.Security.Cryptography.Primitives.Tests.Performance.Perf_FixedTimeEquals:Setup(System.String,System.String):this
          20 ( 4.46% of base) : 1037.dasm - System.TimeZoneInfo:TryConvertIanaIdToWindowsId(System.String,bool,byref):bool
           8 ( 4.35% of base) : 6659.dasm - System.Text.RegularExpressions.RegexCompiler:TrackUnique(int):this
           8 ( 4.00% of base) : 9847.dasm - System.Reflection.Metadata.MetadataReader:CombineRowCounts(System.Int32[],System.Int32[],ubyte):System.Int32[]
          12 ( 4.00% of base) : 2564.dasm - System.RuntimeTypeHandle:CopyRuntimeTypeHandles(System.Type[],byref):System.IntPtr[]
          12 ( 3.85% of base) : 9862.dasm - System.Diagnostics.StackFrame:.ctor(System.Diagnostics.StackFrameHelper,int,bool):this
           8 ( 3.77% of base) : 4816.dasm - ListPartition`1[Char][System.Char]:ToArray():System.Char[]:this
          12 ( 3.70% of base) : 6980.dasm - System.Collections.HashHelpers:GetPrime(int):int
          12 ( 3.70% of base) : 6.dasm - System.Collections.HashHelpers:GetPrime(int):int
           4 ( 3.57% of base) : 10237.dasm - EMFloat:memmove(byref,byref)
          12 ( 3.37% of base) : 3046.dasm - Newtonsoft.Json.DefaultJsonNameTable:Add(System.String):System.String:this
           4 ( 3.33% of base) : 11430.dasm - EMFloatClass:memmove(InternalFPF,InternalFPF)
           8 ( 3.33% of base) : 20974.dasm - SelectIListIterator`2[Int32,Int32][System.Int32,System.Int32]:ToArray():System.Int32[]:this

Top method improvements (percentages):
         -60 (-20.00% of base) : 20833.dasm - Benchstone.BenchI.BubbleSort2:Test():bool:this
         -20 (-17.24% of base) : 12447.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush(int,int):this
        -176 (-17.12% of base) : 13511.dasm - IDEAEncryption:de_key_idea(System.Char[],System.Char[])
         -20 (-16.67% of base) : 14479.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush2(int,int):this
         -92 (-15.75% of base) : 6845.dasm - Benchstone.BenchI.HeapSort:Inner(System.Int32[],int)
         -32 (-15.69% of base) : 8335.dasm - V8.Crypto.Arcfour:next():int:this
         -52 (-15.48% of base) : 14989.dasm - Span.Sorting:TestQuickSortArray(System.Int32[],int,int)
         -24 (-15.00% of base) : 2375.dasm - <>c__DisplayClass14_0:<_ReadFieldOperands>b__0(int):int:this
         -40 (-13.70% of base) : 14518.dasm - Parser:Parse4Dig(int,byref):bool:this
         -40 (-13.51% of base) : 6150.dasm - Newtonsoft.Json.Utilities.DateTimeParser:Parse4Digit(int,byref):bool:this
         -24 (-13.33% of base) : 19671.dasm - Benchstone.BenchI.Array1:VerifySort(System.Int32[]):bool
         -12 (-13.04% of base) : 3510.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush(int):this
        -512 (-12.77% of base) : 12906.dasm - DynamicClass:Regex3_Go(System.Text.RegularExpressions.RegexRunner)
         -24 (-12.50% of base) : 9549.dasm - System.Net.Internals.SocketAddress:CopyAddressSizeIntoBuffer():this
         -12 (-12.50% of base) : 15559.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush2(int):this
         -12 (-12.50% of base) : 7516.dasm - System.Xml.XmlException:BuildCharExceptionArgs(System.String,int):System.String[]
         -24 (-12.24% of base) : 20517.dasm - Benchstone.BenchI.BubbleSort:VerifySort(System.Int32[],int):bool
        -436 (-11.83% of base) : 14847.dasm - DynamicClass:Regex3_Go(System.Text.RegularExpressions.RegexRunner)
         -52 (-11.50% of base) : 11618.dasm - System.SpanHelpers:LastIndexOf(byref,int,int):int
         -52 (-11.21% of base) : 10989.dasm - System.SpanHelpers:LastIndexOf(byref,ushort,int):int

1220 total methods with Code Size differences (1136 improved, 84 regressed), 368 unchanged.

```

</details>

--------------------------------------------------------------------------------

## coreclr_tests.pmi.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 165345900 (overridden on cmd)
Total bytes of diff: 165319844 (overridden on cmd)
Total bytes of delta: -26056 (-0.02 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         104 : 239428.dasm (2.61% of base)
          68 : 167158.dasm (9.04% of base)
          68 : 100367.dasm (8.99% of base)
          68 : 101273.dasm (9.04% of base)
          68 : 166934.dasm (9.09% of base)
          68 : 166744.dasm (9.04% of base)
          68 : 167347.dasm (9.09% of base)
          68 : 100446.dasm (9.04% of base)
          68 : 101196.dasm (8.99% of base)
          68 : 166823.dasm (9.09% of base)
          68 : 101385.dasm (9.04% of base)
          68 : 100557.dasm (9.04% of base)
          68 : 167235.dasm (9.09% of base)
          64 : 100560.dasm (10.74% of base)
          64 : 101356.dasm (10.74% of base)
          64 : 101433.dasm (10.74% of base)
          64 : 166952.dasm (10.74% of base)
          64 : 166965.dasm (8.51% of base)
          64 : 166968.dasm (8.51% of base)
          64 : 100465.dasm (8.33% of base)

Top file improvements (bytes):
       -1548 : 242531.dasm (-14.79% of base)
        -664 : 94.dasm (-6.53% of base)
        -560 : 234600.dasm (-3.52% of base)
        -556 : 234597.dasm (-3.50% of base)
        -544 : 189301.dasm (-18.63% of base)
        -544 : 189050.dasm (-18.63% of base)
        -544 : 188745.dasm (-18.63% of base)
        -448 : 189025.dasm (-17.55% of base)
        -448 : 189276.dasm (-17.55% of base)
        -448 : 188720.dasm (-17.55% of base)
        -324 : 62.dasm (-4.29% of base)
        -300 : 189046.dasm (-14.85% of base)
        -300 : 189297.dasm (-14.85% of base)
        -300 : 188741.dasm (-14.85% of base)
        -252 : 189024.dasm (-13.82% of base)
        -252 : 189275.dasm (-13.82% of base)
        -252 : 188719.dasm (-13.82% of base)
        -196 : 189049.dasm (-18.15% of base)
        -196 : 189300.dasm (-18.15% of base)
        -196 : 188744.dasm (-18.15% of base)

5575 total files with Code Size differences (4500 improved, 1075 regressed), 1309 unchanged.

Top method regressions (bytes):
         104 ( 2.61% of base) : 239428.dasm - Co1245GetBytes_double:runTest():bool:this
          68 ( 9.09% of base) : 166934.dasm - testout1:Sub_Funclet_207():int
          68 ( 9.09% of base) : 167347.dasm - testout1:Sub_Funclet_207():int
          68 ( 9.04% of base) : 101385.dasm - testout1:Sub_Funclet_207():int
          68 ( 9.04% of base) : 100557.dasm - testout1:Sub_Funclet_207():int
          68 ( 9.04% of base) : 101273.dasm - testout1:Sub_Funclet_287():int
          68 ( 9.04% of base) : 100446.dasm - testout1:Sub_Funclet_287():int
          68 ( 9.09% of base) : 166823.dasm - testout1:Sub_Funclet_287():int
          68 ( 9.09% of base) : 167235.dasm - testout1:Sub_Funclet_287():int
          68 ( 9.04% of base) : 167158.dasm - testout1:Sub_Funclet_399():int
          68 ( 8.99% of base) : 100367.dasm - testout1:Sub_Funclet_399():int
          68 ( 9.04% of base) : 166744.dasm - testout1:Sub_Funclet_399():int
          68 ( 8.99% of base) : 101196.dasm - testout1:Sub_Funclet_399():int
          64 (10.74% of base) : 167029.dasm - testout1:Sub_Funclet_111():int
          64 ( 9.41% of base) : 102268.dasm - testout1:Sub_Funclet_111():int
          64 (10.67% of base) : 100652.dasm - testout1:Sub_Funclet_111():int
          64 ( 9.47% of base) : 167841.dasm - testout1:Sub_Funclet_111():int
          64 (10.53% of base) : 100655.dasm - testout1:Sub_Funclet_114():int
          64 ( 9.30% of base) : 102271.dasm - testout1:Sub_Funclet_114():int
          64 (10.60% of base) : 167032.dasm - testout1:Sub_Funclet_114():int

Top method improvements (bytes):
       -1548 (-14.79% of base) : 242531.dasm - SimpleArray_01.Test:Test1()
        -664 (-6.53% of base) : 94.dasm - System.Text.RegularExpressions.RegexInterpreter:Go():this
        -560 (-3.52% of base) : 234600.dasm - StrAccess2:Main():int
        -556 (-3.50% of base) : 234597.dasm - StrAccess2:Main():int
        -544 (-18.63% of base) : 189301.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetHexadecaDataPoint(int):System.ValueTuple`8[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`1]:this
        -544 (-18.63% of base) : 189050.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetHexadecaDataPoint(int):System.ValueTuple`8[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`1]:this
        -544 (-18.63% of base) : 188745.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetHexadecaDataPoint(int):System.ValueTuple`8[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`1]:this
        -448 (-17.55% of base) : 189025.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:CheckUnpack(IntelHardwareIntrinsicTest.CheckMethodSixteenOfAll`2[Byte,Int64]):bool:this
        -448 (-17.55% of base) : 189276.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:CheckUnpack(IntelHardwareIntrinsicTest.CheckMethodSixteenOfAll`2[Byte,Int64]):bool:this
        -448 (-17.55% of base) : 188720.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:CheckUnpack(IntelHardwareIntrinsicTest.CheckMethodSixteenOfAll`2[Byte,Int64]):bool:this
        -324 (-4.29% of base) : 62.dasm - System.Text.RegularExpressions.RegexWriter:EmitFragment(int,System.Text.RegularExpressions.RegexNode,int):this
        -300 (-14.85% of base) : 189046.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetCheckMethodSixteen4DataPoint(int):System.ValueTuple`6[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8]:this
        -300 (-14.85% of base) : 189297.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetCheckMethodSixteen4DataPoint(int):System.ValueTuple`6[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8]:this
        -300 (-14.85% of base) : 188741.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetCheckMethodSixteen4DataPoint(int):System.ValueTuple`6[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8]:this
        -252 (-13.82% of base) : 189024.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:CheckPackSaturate(IntelHardwareIntrinsicTest.CheckMethodSixteen`2[Byte,Int64]):bool:this
        -252 (-13.82% of base) : 189275.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:CheckPackSaturate(IntelHardwareIntrinsicTest.CheckMethodSixteen`2[Byte,Int64]):bool:this
        -252 (-13.82% of base) : 188719.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:CheckPackSaturate(IntelHardwareIntrinsicTest.CheckMethodSixteen`2[Byte,Int64]):bool:this
        -196 (-7.69% of base) : 191680.dasm - AssignRect:second_assignments(System.Int32[,],System.Int16[,])
        -196 (-18.15% of base) : 189049.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetOcta88DataPoint(int):System.ValueTuple`4[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8]:this
        -196 (-18.15% of base) : 189300.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetOcta88DataPoint(int):System.ValueTuple`4[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8]:this

Top method regressions (percentages):
          52 (15.66% of base) : 167440.dasm - testout1:Sub_Funclet_111():int
          52 (15.66% of base) : 167048.dasm - testout1:Sub_Funclet_79():int
          52 (15.66% of base) : 167424.dasm - testout1:Sub_Funclet_95():int
          52 (15.48% of base) : 101478.dasm - testout1:Sub_Funclet_111():int
          52 (15.48% of base) : 167443.dasm - testout1:Sub_Funclet_114():int
          52 (15.48% of base) : 167174.dasm - testout1:Sub_Funclet_354():int
          52 (15.48% of base) : 100671.dasm - testout1:Sub_Funclet_79():int
          52 (15.48% of base) : 167470.dasm - testout1:Sub_Funclet_82():int
          52 (15.48% of base) : 101462.dasm - testout1:Sub_Funclet_95():int
          52 (15.48% of base) : 167427.dasm - testout1:Sub_Funclet_98():int
          52 (15.29% of base) : 101481.dasm - testout1:Sub_Funclet_114():int
          52 (15.29% of base) : 167809.dasm - testout1:Sub_Funclet_143():int
          52 (15.29% of base) : 167613.dasm - testout1:Sub_Funclet_319():int
          52 (15.29% of base) : 167203.dasm - testout1:Sub_Funclet_319():int
          52 (15.29% of base) : 101212.dasm - testout1:Sub_Funclet_354():int
          52 (15.29% of base) : 167584.dasm - testout1:Sub_Funclet_354():int
          52 (15.29% of base) : 101508.dasm - testout1:Sub_Funclet_82():int
          52 (15.29% of base) : 101465.dasm - testout1:Sub_Funclet_98():int
          52 (15.12% of base) : 102236.dasm - testout1:Sub_Funclet_143():int
          52 (15.12% of base) : 101241.dasm - testout1:Sub_Funclet_319():int

Top method improvements (percentages):
         -60 (-21.13% of base) : 253147.dasm - Benchstone.BenchI.BubbleSort2:Bench():bool
        -544 (-18.63% of base) : 189301.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetHexadecaDataPoint(int):System.ValueTuple`8[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`1]:this
        -544 (-18.63% of base) : 189050.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetHexadecaDataPoint(int):System.ValueTuple`8[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`1]:this
        -544 (-18.63% of base) : 188745.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetHexadecaDataPoint(int):System.ValueTuple`8[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`1]:this
        -196 (-18.15% of base) : 189049.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetOcta88DataPoint(int):System.ValueTuple`4[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8]:this
        -196 (-18.15% of base) : 189300.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetOcta88DataPoint(int):System.ValueTuple`4[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8]:this
        -196 (-18.15% of base) : 188744.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:GetOcta88DataPoint(int):System.ValueTuple`4[ValueTuple`8,ValueTuple`8,ValueTuple`8,ValueTuple`8]:this
        -448 (-17.55% of base) : 189025.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:CheckUnpack(IntelHardwareIntrinsicTest.CheckMethodSixteenOfAll`2[Byte,Int64]):bool:this
        -448 (-17.55% of base) : 189276.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:CheckUnpack(IntelHardwareIntrinsicTest.CheckMethodSixteenOfAll`2[Byte,Int64]):bool:this
        -448 (-17.55% of base) : 188720.dasm - IntelHardwareIntrinsicTest.TestTableSse2`2[Byte,Int64][System.Byte,System.Int64]:CheckUnpack(IntelHardwareIntrinsicTest.CheckMethodSixteenOfAll`2[Byte,Int64]):bool:this
        -176 (-17.12% of base) : 191740.dasm - IDEAEncryption:de_key_idea(System.Char[],System.Char[])
         -92 (-15.75% of base) : 253126.dasm - Benchstone.BenchI.HeapSort:Inner(System.Int32[],int)
         -32 (-15.69% of base) : 218958.dasm - V8.Crypto.Arcfour:next():int:this
         -52 (-15.48% of base) : 218785.dasm - Span.SpanBench:TestQuickSortArray(System.Int32[],int,int)
         -12 (-15.00% of base) : 120787.dasm - JIT.HardwareIntrinsics.Arm.Helpers:AddPairwiseWidening(System.Int16[],int):int
         -12 (-15.00% of base) : 129310.dasm - JIT.HardwareIntrinsics.Arm.Helpers:AddPairwiseWidening(System.Int16[],int):int
         -12 (-15.00% of base) : 175043.dasm - JIT.HardwareIntrinsics.Arm.Helpers:AddPairwiseWidening(System.Int16[],int):int
         -12 (-15.00% of base) : 179759.dasm - JIT.HardwareIntrinsics.Arm.Helpers:AddPairwiseWidening(System.Int16[],int):int
         -12 (-15.00% of base) : 185916.dasm - JIT.HardwareIntrinsics.Arm.Helpers:AddPairwiseWidening(System.Int16[],int):int
         -12 (-15.00% of base) : 172310.dasm - JIT.HardwareIntrinsics.Arm.Helpers:AddPairwiseWidening(System.Int16[],int):int

5575 total methods with Code Size differences (4500 improved, 1075 regressed), 1309 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.crossgen2.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 51752168 (overridden on cmd)
Total bytes of diff: 51718316 (overridden on cmd)
Total bytes of delta: -33852 (-0.07 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
          52 : 152304.dasm (1.72% of base)
          52 : 176886.dasm (1.89% of base)
          52 : 52935.dasm (1.56% of base)
          48 : 62973.dasm (2.41% of base)
          44 : 56894.dasm (4.37% of base)
          40 : 50715.dasm (4.72% of base)
          40 : 207810.dasm (0.74% of base)
          40 : 191694.dasm (34.48% of base)
          28 : 60814.dasm (1.72% of base)
          28 : 210039.dasm (5.34% of base)
          28 : 57374.dasm (9.59% of base)
          28 : 169928.dasm (1.34% of base)
          24 : 126981.dasm (1.43% of base)
          24 : 72390.dasm (3.33% of base)
          24 : 203421.dasm (1.92% of base)
          20 : 220105.dasm (1.27% of base)
          20 : 176779.dasm (4.24% of base)
          20 : 199662.dasm (1.15% of base)
          20 : 165747.dasm (1.29% of base)
          20 : 117447.dasm (2.81% of base)

Top file improvements (bytes):
        -672 : 122317.dasm (-13.29% of base)
        -524 : 194617.dasm (-5.36% of base)
        -348 : 124789.dasm (-11.97% of base)
        -348 : 124957.dasm (-13.45% of base)
        -304 : 124942.dasm (-12.12% of base)
        -304 : 124771.dasm (-10.75% of base)
        -276 : 194411.dasm (-3.46% of base)
        -252 : 194285.dasm (-0.90% of base)
        -252 : 169762.dasm (-13.82% of base)
        -228 : 124769.dasm (-11.18% of base)
        -228 : 124938.dasm (-15.32% of base)
        -188 : 151581.dasm (-0.68% of base)
        -152 : 74518.dasm (-2.90% of base)
        -152 : 182290.dasm (-3.04% of base)
        -140 : 124751.dasm (-9.62% of base)
        -140 : 124927.dasm (-12.46% of base)
        -128 : 128968.dasm (-12.45% of base)
        -128 : 129063.dasm (-19.51% of base)
        -128 : 87315.dasm (-8.74% of base)
        -124 : 195000.dasm (-2.50% of base)

3343 total files with Code Size differences (3003 improved, 340 regressed), 1088 unchanged.

Top method regressions (bytes):
          52 ( 1.56% of base) : 52935.dasm - Microsoft.CodeAnalysis.COFFResourceReader:ReadWin32ResourcesFromCOFF(System.IO.Stream):Microsoft.Cci.ResourceSection
          52 ( 1.72% of base) : 152304.dasm - Microsoft.VisualBasic.CompilerServices.LateBinding:LateIndexSet(System.Object,System.Object[],System.String[])
          52 ( 1.89% of base) : 176886.dasm - System.Runtime.Serialization.Formatters.Binary.ObjectWriter:WriteArray(System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo,System.Runtime.Serialization.Formatters.Binary.NameInfo,System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo):this
          48 ( 2.41% of base) : 62973.dasm - System.Reflection.Emit.MethodBuilder:CreateMethodBodyHelper(System.Reflection.Emit.ILGenerator):this
          44 ( 4.37% of base) : 56894.dasm - Newtonsoft.Json.Serialization.JsonSerializerInternalWriter:SerializeMultidimensionalArray(Newtonsoft.Json.JsonWriter,System.Array,Newtonsoft.Json.Serialization.JsonArrayContract,Newtonsoft.Json.Serialization.JsonProperty,int,System.Int32[]):this
          40 ( 0.74% of base) : 207810.dasm - Internal.TypeSystem.MetadataFieldLayoutAlgorithm:ComputeAutoFieldLayout(Internal.TypeSystem.MetadataType,int):Internal.TypeSystem.ComputedInstanceFieldLayout:this
          40 ( 4.72% of base) : 50715.dasm - Microsoft.CodeAnalysis.Text.SourceText:ContentEqualsImpl(Microsoft.CodeAnalysis.Text.SourceText):bool:this
          40 (34.48% of base) : 191694.dasm - System.Net.WebClient:ByteArrayHasPrefix(System.Byte[],System.Byte[]):bool
          28 ( 1.34% of base) : 169928.dasm - Microsoft.CSharp.RuntimeBinder.Errors.ErrorHandling:Error(int,Microsoft.CSharp.RuntimeBinder.Errors.ErrArg[]):Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
          28 ( 9.59% of base) : 57374.dasm - Newtonsoft.Json.Utilities.MiscellaneousUtils:ByteArrayCompare(System.Byte[],System.Byte[]):int
          28 ( 5.34% of base) : 210039.dasm - System.Configuration.MgmtConfigurationRecord:CheckPreamble(System.Byte[],System.Configuration.XmlUtilWriter,System.Byte[]):this
          28 ( 1.72% of base) : 60814.dasm - System.Diagnostics.StackFrameHelper:InitializeSourceInfo(int,bool,System.Exception):this
          24 ( 1.92% of base) : 203421.dasm - System.Reflection.Metadata.Ecma335.MetadataAggregator:CalculateHeapSizes(System.Collections.Generic.IReadOnlyList`1[System.Int32],System.Collections.Generic.IReadOnlyList`1[System.Reflection.Metadata.MetadataReader]):System.Collections.Immutable.ImmutableArray`1[System.Collections.Immutable.ImmutableArray`1[System.Int32]]
          24 ( 3.33% of base) : 72390.dasm - System.TimeZoneInfo:TryConvertWindowsIdToIanaId(System.String,System.String,bool,byref):bool
          24 ( 1.43% of base) : 126981.dasm - System.Xml.XmlTextReaderImpl:ParseElementContentAsync():System.Threading.Tasks.Task`1[System.Boolean]:this
          20 ( 6.25% of base) : 167348.dasm - Internal.Cryptography.Helpers:FixupKeyParity(System.Byte[]):System.Byte[]
          20 ( 1.29% of base) : 165747.dasm - System.Collections.Concurrent.ConcurrentDictionary`2:GrowTable(System.Collections.Concurrent.ConcurrentDictionary`2+Tables[System.__Canon, System.__Canon]):this
          20 ( 1.27% of base) : 220105.dasm - System.Diagnostics.EventLogInternal:InternalWriteEvent(int,ushort,int,System.String[],System.Byte[],System.String):this
          20 ( 4.24% of base) : 176779.dasm - System.DomainNameHelper:IdnEquivalent(System.String):System.String
          20 ( 1.15% of base) : 199662.dasm - System.ServiceProcess.ServiceController:Start(System.String[]):this

Top method improvements (bytes):
        -672 (-13.29% of base) : 122317.dasm - System.Xml.Schema.XmlSchemaInference:InferSimpleType(System.String,byref):int
        -524 (-5.36% of base) : 194617.dasm - System.Text.RegularExpressions.RegexInterpreter:Go():this
        -348 (-11.97% of base) : 124789.dasm - <ScanSubsetContentAsync>d__174:MoveNext():this
        -348 (-13.45% of base) : 124957.dasm - System.Xml.DtdParser:ScanSubsetContent():int:this
        -304 (-10.75% of base) : 124771.dasm - <ScanAttlist2Async>d__183:MoveNext():this
        -304 (-12.12% of base) : 124942.dasm - System.Xml.DtdParser:ScanAttlist2():int:this
        -276 (-3.46% of base) : 194411.dasm - System.Text.RegularExpressions.RegexWriter:EmitFragment(int,System.Text.RegularExpressions.RegexNode,int):this
        -252 (-0.90% of base) : 194285.dasm - System.Text.RegularExpressions.RegexCompiler:GenerateOneCode():this
        -252 (-13.82% of base) : 169762.dasm - Xunit.Sdk.Sha1Digest:ProcessBlock():this
        -228 (-11.18% of base) : 124769.dasm - <ScanAttlist6Async>d__184:MoveNext():this
        -228 (-15.32% of base) : 124938.dasm - System.Xml.DtdParser:ScanAttlist6():int:this
        -188 (-0.68% of base) : 151581.dasm - Microsoft.VisualBasic.CompilerServices.VBBinder:BindToMethod(int,System.Reflection.MethodBase[],byref,System.Reflection.ParameterModifier[],System.Globalization.CultureInfo,System.String[],byref):System.Reflection.MethodBase:this
        -152 (-3.04% of base) : 182290.dasm - Number:NumberToStringFormat(byref,byref,System.ReadOnlySpan`1[System.Char],System.Globalization.NumberFormatInfo)
        -152 (-2.90% of base) : 74518.dasm - System.Number:NumberToStringFormat(byref,byref,System.ReadOnlySpan`1[System.Char],System.Globalization.NumberFormatInfo)
        -140 (-9.62% of base) : 124751.dasm - <ScanCondSection1Async>d__193:MoveNext():this
        -140 (-12.46% of base) : 124927.dasm - System.Xml.DtdParser:ScanCondSection1():int:this
        -128 (-12.45% of base) : 128968.dasm - <WriteCDataAsync>d__109:MoveNext():this
        -128 (-8.74% of base) : 87315.dasm - System.Xml.UniqueId:UnsafeParse(long,int):this
        -128 (-19.51% of base) : 129063.dasm - System.Xml.XmlEncodedRawTextWriter:WriteCData(System.String):this
        -124 (-2.50% of base) : 195000.dasm - System.Text.RegularExpressions.Symbolic.SymbolicRegexMatcher`1:FindFinalStatePosition(System.String,int,int,int,byref,byref):int:this

Top method regressions (percentages):
          40 (34.48% of base) : 191694.dasm - System.Net.WebClient:ByteArrayHasPrefix(System.Byte[],System.Byte[]):bool
          28 ( 9.59% of base) : 57374.dasm - Newtonsoft.Json.Utilities.MiscellaneousUtils:ByteArrayCompare(System.Byte[],System.Byte[]):int
          16 ( 7.14% of base) : 193949.dasm - System.Text.RegularExpressions.Symbolic.BV:op_BitwiseAnd(System.Text.RegularExpressions.Symbolic.BV,System.Text.RegularExpressions.Symbolic.BV):System.Text.RegularExpressions.Symbolic.BV
          16 ( 7.14% of base) : 193948.dasm - System.Text.RegularExpressions.Symbolic.BV:op_BitwiseOr(System.Text.RegularExpressions.Symbolic.BV,System.Text.RegularExpressions.Symbolic.BV):System.Text.RegularExpressions.Symbolic.BV
          16 ( 7.14% of base) : 193922.dasm - System.Text.RegularExpressions.Symbolic.BVAlgebra:And(System.Text.RegularExpressions.Symbolic.BV,System.Text.RegularExpressions.Symbolic.BV):System.Text.RegularExpressions.Symbolic.BV:this
          16 ( 7.14% of base) : 193919.dasm - System.Text.RegularExpressions.Symbolic.BVAlgebra:Or(System.Text.RegularExpressions.Symbolic.BV,System.Text.RegularExpressions.Symbolic.BV):System.Text.RegularExpressions.Symbolic.BV:this
          12 ( 6.52% of base) : 19567.dasm - Microsoft.Diagnostics.Symbols.SourceFile:ArrayEquals(System.Byte[],System.Byte[]):bool
          12 ( 6.38% of base) : 187336.dasm - Microsoft.Extensions.FileProviders.Physical.PollingWildCardChangeToken:ArrayEquals(System.Byte[],System.Byte[]):bool
          20 ( 6.25% of base) : 167348.dasm - Internal.Cryptography.Helpers:FixupKeyParity(System.Byte[]):System.Byte[]
          12 ( 6.25% of base) : 124372.dasm - System.Xml.Schema.DatatypeImplementation:Compare(System.Byte[],System.Byte[]):int:this
          12 ( 6.00% of base) : 192892.dasm - System.DirectoryServices.ActiveDirectory.ActiveDirectorySchedule:.ctor(System.Boolean[]):this
          12 ( 5.88% of base) : 116075.dasm - ILCompiler.DependencyAnalysis.ReadyToRun.ByteArrayComparer:Equals(System.Byte[],System.Byte[]):bool:this
          16 ( 5.80% of base) : 53506.dasm - Microsoft.CodeAnalysis.CommandLineParser:RemoveTrailingSpacesAndDots(System.String):System.String
          12 ( 5.77% of base) : 206951.dasm - Internal.Cryptography.Helpers:ContentsEqual(System.Byte[],System.Byte[]):bool
          16 ( 5.71% of base) : 175796.dasm - System.DirectoryServices.AccountManagement.SidList:.ctor(System.DirectoryServices.AccountManagement.UnsafeNativeMethods+SID_AND_ATTR[]):this
           8 ( 5.71% of base) : 194550.dasm - System.Text.RegularExpressions.RegexParser:Escape(System.String):System.String
          12 ( 5.66% of base) : 50281.dasm - Microsoft.CodeAnalysis.Collections.ByteSequenceComparer:Equals(System.Byte[],System.Byte[]):bool
          12 ( 5.66% of base) : 203365.dasm - System.Reflection.Internal.ByteSequenceComparer:Equals(System.Byte[],System.Byte[]):bool
          12 ( 5.56% of base) : 197637.dasm - System.Security.AccessControl.CommonAcl:AceOpaquesMatch(System.Security.AccessControl.QualifiedAce,System.Security.AccessControl.QualifiedAce):bool
          12 ( 5.56% of base) : 194397.dasm - System.Text.RegularExpressions.RegexCompiler:AddGoto(int):int:this

Top method improvements (percentages):
         -40 (-20.00% of base) : 129121.dasm - System.Xml.HtmlEncodedRawTextWriter:OutputRestAmps():this
        -128 (-19.51% of base) : 129063.dasm - System.Xml.XmlEncodedRawTextWriter:WriteCData(System.String):this
         -28 (-18.42% of base) : 194642.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush(int,int,int):this
         -20 (-15.62% of base) : 194643.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush(int,int):this
         -16 (-15.38% of base) : 157838.dasm - System.Linq.Parallel.FixedMaxHeap`1:Swap(int,int):this
        -228 (-15.32% of base) : 124938.dasm - System.Xml.DtdParser:ScanAttlist6():int:this
         -20 (-15.15% of base) : 194640.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush2(int,int):this
         -52 (-14.94% of base) : 124919.dasm - System.Xml.DtdParser:EatPublicKeyword():bool:this
         -52 (-14.94% of base) : 124918.dasm - System.Xml.DtdParser:EatSystemKeyword():bool:this
         -60 (-14.71% of base) : 129062.dasm - System.Xml.XmlEncodedRawTextWriter:WriteComment(System.String):this
          -4 (-14.29% of base) : 75455.dasm - System.DateTimeRawInfo:GetNumber(int):int:this
         -44 (-14.10% of base) : 1229.dasm - Microsoft.Diagnostics.Tracing.Ctf.CtfMetadataLegacyParser:FindCloseBrace(System.String,int):int
        -252 (-13.82% of base) : 169762.dasm - Xunit.Sdk.Sha1Digest:ProcessBlock():this
        -120 (-13.70% of base) : 127108.dasm - System.Xml.XmlTextReaderImpl:ParseNamedCharRefInline(int,bool,System.Text.StringBuilder):int:this
         -24 (-13.64% of base) : 54409.dasm - Microsoft.Cci.MetadataWriter:ReadInt32(System.Collections.Immutable.ImmutableArray`1[System.Byte],int):int
         -24 (-13.64% of base) : 48379.dasm - PublicKeyDecoder:ToUInt32(System.Collections.Immutable.ImmutableArray`1[System.Byte],int):int
        -348 (-13.45% of base) : 124957.dasm - System.Xml.DtdParser:ScanSubsetContent():int:this
        -672 (-13.29% of base) : 122317.dasm - System.Xml.Schema.XmlSchemaInference:InferSimpleType(System.String,byref):int
         -40 (-13.16% of base) : 122405.dasm - Parser:Parse4Dig(int,byref):bool:this
         -80 (-13.16% of base) : 128853.dasm - System.Xml.XmlUtf8RawTextWriter:WriteCData(System.String):this

3343 total methods with Code Size differences (3003 improved, 340 regressed), 1088 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 51211268 (overridden on cmd)
Total bytes of diff: 51114988 (overridden on cmd)
Total bytes of delta: -96280 (-0.19 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
          56 : 161922.dasm (7.14% of base)
          52 : 212400.dasm (2.11% of base)
          48 : 149928.dasm (1.95% of base)
          48 : 124065.dasm (2.92% of base)
          40 : 193300.dasm (7.81% of base)
          40 : 203157.dasm (34.48% of base)
          40 : 155695.dasm (10.99% of base)
          36 : 9317.dasm (5.70% of base)
          36 : 9319.dasm (4.84% of base)
          36 : 9321.dasm (5.11% of base)
          36 : 9323.dasm (9.89% of base)
          36 : 9083.dasm (10.71% of base)
          36 : 145523.dasm (1.34% of base)
          32 : 156445.dasm (8.70% of base)
          32 : 164263.dasm (10.39% of base)
          32 : 164876.dasm (2.67% of base)
          32 : 168398.dasm (5.97% of base)
          32 : 181825.dasm (2.03% of base)
          32 : 205688.dasm (10.39% of base)
          28 : 74951.dasm (9.72% of base)

Top file improvements (bytes):
        -684 : 130305.dasm (-13.13% of base)
        -664 : 94.dasm (-6.53% of base)
        -348 : 127693.dasm (-14.01% of base)
        -336 : 127798.dasm (-12.30% of base)
        -324 : 62.dasm (-4.29% of base)
        -308 : 150656.dasm (-1.29% of base)
        -304 : 127708.dasm (-12.73% of base)
        -300 : 127816.dasm (-11.35% of base)
        -252 : 236122.dasm (-14.00% of base)
        -252 : 224756.dasm (-1.41% of base)
        -228 : 127712.dasm (-15.75% of base)
        -220 : 127818.dasm (-10.96% of base)
        -160 : 100386.dasm (-4.07% of base)
        -160 : 94515.dasm (-3.59% of base)
        -156 : 211618.dasm (-3.49% of base)
        -156 : 93329.dasm (-3.95% of base)
        -152 : 100373.dasm (-4.16% of base)
        -148 : 100435.dasm (-4.19% of base)
        -148 : 100364.dasm (-4.17% of base)
        -144 : 99195.dasm (-4.27% of base)

5932 total files with Code Size differences (5552 improved, 380 regressed), 2049 unchanged.

Top method regressions (bytes):
          56 ( 7.14% of base) : 161922.dasm - System.Collections.Generic.SortedSet`1[Byte][System.Byte]:OnDeserialization(System.Object):this
          52 ( 2.11% of base) : 212400.dasm - System.Runtime.Serialization.Formatters.Binary.ObjectWriter:WriteArray(System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo,System.Runtime.Serialization.Formatters.Binary.NameInfo,System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo):this
          48 ( 1.95% of base) : 149928.dasm - Microsoft.VisualBasic.CompilerServices.LateBinding:LateIndexSet(System.Object,System.Object[],System.String[])
          48 ( 2.92% of base) : 124065.dasm - System.Xml.XmlConvert:EncodeName(System.String,bool,bool):System.String
          40 ( 7.81% of base) : 193300.dasm - AppendPrependN`1[Byte][System.Byte]:ToArray():System.Byte[]:this
          40 (10.99% of base) : 155695.dasm - System.Collections.Concurrent.ConcurrentBag`1[Byte][System.Byte]:ToArray():System.Byte[]:this
          40 (34.48% of base) : 203157.dasm - System.Net.WebClient:ByteArrayHasPrefix(System.Byte[],System.Byte[]):bool
          36 ( 1.34% of base) : 145523.dasm - Microsoft.CSharp.RuntimeBinder.Errors.ErrorHandling:Error(int,Microsoft.CSharp.RuntimeBinder.Errors.ErrArg[]):Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
          36 ( 5.70% of base) : 9317.dasm - Microsoft.FSharp.Collections.ArrayModule:splitAt$cont@130(int,System.Byte[],Microsoft.FSharp.Core.Unit):System.Tuple`2[[System.Byte[], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Byte[], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
          36 ( 4.84% of base) : 9319.dasm - Microsoft.FSharp.Collections.ArrayModule:SplitAt(int,System.Byte[]):System.Tuple`2[[System.Byte[], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Byte[], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
          36 ( 5.11% of base) : 9321.dasm - Microsoft.FSharp.Collections.ArrayModule:Take(int,System.Byte[]):System.Byte[]
          36 ( 9.89% of base) : 9323.dasm - Microsoft.FSharp.Collections.ArrayModule:TakeWhile(Microsoft.FSharp.Core.FSharpFunc`2[Byte,Boolean],System.Byte[]):System.Byte[]
          36 (10.71% of base) : 9083.dasm - Microsoft.FSharp.Collections.ArrayModule:Truncate(int,System.Byte[]):System.Byte[]
          32 (10.39% of base) : 164263.dasm - Microsoft.Internal.Collections.CollectionServices:IsArrayEqual(System.Byte[],System.Byte[]):bool
          32 ( 5.97% of base) : 168398.dasm - System.Configuration.MgmtConfigurationRecord:CheckPreamble(System.Byte[],System.Configuration.XmlUtilWriter,System.Byte[]):this
          32 ( 2.67% of base) : 164876.dasm - System.Drawing.ColorConverterCommon:ConvertFromString(System.String,System.Globalization.CultureInfo):System.Drawing.Color
          32 ( 2.03% of base) : 181825.dasm - System.Drawing.ColorConverterCommon:ConvertFromString(System.String,System.Globalization.CultureInfo):System.Drawing.Color
          32 ( 8.70% of base) : 156445.dasm - System.Linq.ImmutableArrayExtensions:SequenceEqual(System.Collections.Immutable.ImmutableArray`1[Byte],System.Collections.Immutable.ImmutableArray`1[Byte],System.Collections.Generic.IEqualityComparer`1[Byte]):bool
          32 (10.39% of base) : 205688.dasm - System.Reflection.Context.CollectionServices:CompareArrays(System.Byte[],System.Byte[]):bool
          28 ( 9.72% of base) : 74951.dasm - Microsoft.Cci.ContentId:FromHash(System.Collections.Immutable.ImmutableArray`1[Byte]):Microsoft.Cci.ContentId

Top method improvements (bytes):
        -684 (-13.13% of base) : 130305.dasm - System.Xml.Schema.XmlSchemaInference:InferSimpleType(System.String,byref):int
        -664 (-6.53% of base) : 94.dasm - System.Text.RegularExpressions.RegexInterpreter:Go():this
        -348 (-14.01% of base) : 127693.dasm - System.Xml.DtdParser:ScanSubsetContent():int:this
        -336 (-12.30% of base) : 127798.dasm - <ScanSubsetContentAsync>d__174:MoveNext():this
        -324 (-4.29% of base) : 62.dasm - System.Text.RegularExpressions.RegexWriter:EmitFragment(int,System.Text.RegularExpressions.RegexNode,int):this
        -308 (-1.29% of base) : 150656.dasm - Microsoft.VisualBasic.CompilerServices.VBBinder:BindToMethod(int,System.Reflection.MethodBase[],byref,System.Reflection.ParameterModifier[],System.Globalization.CultureInfo,System.String[],byref):System.Reflection.MethodBase:this
        -304 (-12.73% of base) : 127708.dasm - System.Xml.DtdParser:ScanAttlist2():int:this
        -300 (-11.35% of base) : 127816.dasm - <ScanAttlist2Async>d__183:MoveNext():this
        -252 (-1.41% of base) : 224756.dasm - System.Text.RegularExpressions.RegexCompiler:GenerateOneCode():this
        -252 (-14.00% of base) : 236122.dasm - Xunit.Sdk.Sha1Digest:ProcessBlock():this
        -228 (-15.75% of base) : 127712.dasm - System.Xml.DtdParser:ScanAttlist6():int:this
        -220 (-10.96% of base) : 127818.dasm - <ScanAttlist6Async>d__184:MoveNext():this
        -160 (-4.07% of base) : 100386.dasm - Microsoft.Diagnostics.Tracing.Parsers.ApplicationServer.Multidata6TemplateHATraceData:ToXml(System.Text.StringBuilder):System.Text.StringBuilder:this
        -160 (-3.59% of base) : 94515.dasm - Microsoft.Diagnostics.Tracing.Parsers.Kernel.MemoryProcessMemInfoTraceData:ToXml(System.Text.StringBuilder):System.Text.StringBuilder:this
        -156 (-3.95% of base) : 93329.dasm - Microsoft.Diagnostics.Tracing.Parsers.MicrosoftWindowsTCPIP.TcpGlobalParametersArgs:ToXml(System.Text.StringBuilder):System.Text.StringBuilder:this
        -156 (-3.49% of base) : 211618.dasm - Number:NumberToStringFormat(byref,byref,System.ReadOnlySpan`1[Char],System.Globalization.NumberFormatInfo)
        -152 (-4.16% of base) : 100373.dasm - Microsoft.Diagnostics.Tracing.Parsers.ApplicationServer.Multidata3TemplateHATraceData:ToXml(System.Text.StringBuilder):System.Text.StringBuilder:this
        -148 (-4.19% of base) : 100435.dasm - Microsoft.Diagnostics.Tracing.Parsers.ApplicationServer.Multidata13TemplateHATraceData:ToXml(System.Text.StringBuilder):System.Text.StringBuilder:this
        -148 (-4.17% of base) : 100364.dasm - Microsoft.Diagnostics.Tracing.Parsers.ApplicationServer.Multidata4TemplateHATraceData:ToXml(System.Text.StringBuilder):System.Text.StringBuilder:this
        -144 (-4.23% of base) : 100347.dasm - Microsoft.Diagnostics.Tracing.Parsers.ApplicationServer.Multidata10TemplateHATraceData:ToXml(System.Text.StringBuilder):System.Text.StringBuilder:this

Top method regressions (percentages):
          40 (34.48% of base) : 203157.dasm - System.Net.WebClient:ByteArrayHasPrefix(System.Byte[],System.Byte[]):bool
          28 (11.11% of base) : 117595.dasm - System.Xml.XmlConverter:StripWhitespace(System.String):System.String
          40 (10.99% of base) : 155695.dasm - System.Collections.Concurrent.ConcurrentBag`1[Byte][System.Byte]:ToArray():System.Byte[]:this
          36 (10.71% of base) : 9083.dasm - Microsoft.FSharp.Collections.ArrayModule:Truncate(int,System.Byte[]):System.Byte[]
          32 (10.39% of base) : 164263.dasm - Microsoft.Internal.Collections.CollectionServices:IsArrayEqual(System.Byte[],System.Byte[]):bool
          32 (10.39% of base) : 205688.dasm - System.Reflection.Context.CollectionServices:CompareArrays(System.Byte[],System.Byte[]):bool
          36 ( 9.89% of base) : 9323.dasm - Microsoft.FSharp.Collections.ArrayModule:TakeWhile(Microsoft.FSharp.Core.FSharpFunc`2[Byte,Boolean],System.Byte[]):System.Byte[]
          28 ( 9.72% of base) : 74951.dasm - Microsoft.Cci.ContentId:FromHash(System.Collections.Immutable.ImmutableArray`1[Byte]):Microsoft.Cci.ContentId
          20 ( 9.09% of base) : 104690.dasm - Newtonsoft.Json.Utilities.MiscellaneousUtils:ByteArrayCompare(System.Byte[],System.Byte[]):int
          32 ( 8.70% of base) : 156445.dasm - System.Linq.ImmutableArrayExtensions:SequenceEqual(System.Collections.Immutable.ImmutableArray`1[Byte],System.Collections.Immutable.ImmutableArray`1[Byte],System.Collections.Generic.IEqualityComparer`1[Byte]):bool
          16 ( 8.00% of base) : 225435.dasm - System.Text.RegularExpressions.Symbolic.BV:op_BitwiseAnd(System.Text.RegularExpressions.Symbolic.BV,System.Text.RegularExpressions.Symbolic.BV):System.Text.RegularExpressions.Symbolic.BV
          16 ( 8.00% of base) : 225436.dasm - System.Text.RegularExpressions.Symbolic.BV:op_BitwiseOr(System.Text.RegularExpressions.Symbolic.BV,System.Text.RegularExpressions.Symbolic.BV):System.Text.RegularExpressions.Symbolic.BV
          16 ( 8.00% of base) : 225467.dasm - System.Text.RegularExpressions.Symbolic.BVAlgebra:And(System.Text.RegularExpressions.Symbolic.BV,System.Text.RegularExpressions.Symbolic.BV):System.Text.RegularExpressions.Symbolic.BV:this
          16 ( 8.00% of base) : 225470.dasm - System.Text.RegularExpressions.Symbolic.BVAlgebra:Or(System.Text.RegularExpressions.Symbolic.BV,System.Text.RegularExpressions.Symbolic.BV):System.Text.RegularExpressions.Symbolic.BV:this
          40 ( 7.81% of base) : 193300.dasm - AppendPrependN`1[Byte][System.Byte]:ToArray():System.Byte[]:this
          12 ( 7.50% of base) : 224833.dasm - System.Text.RegularExpressions.RegexCompiler:AddGoto(int):int:this
          56 ( 7.14% of base) : 161922.dasm - System.Collections.Generic.SortedSet`1[Byte][System.Byte]:OnDeserialization(System.Object):this
          12 ( 6.98% of base) : 25644.dasm - Microsoft.CodeAnalysis.CSharp.DocumentationCommentCompiler:FindMultiLineCommentPattern(System.String):System.String
          12 ( 6.98% of base) : 83875.dasm - Microsoft.Diagnostics.Symbols.SourceFile:ArrayEquals(System.Byte[],System.Byte[]):bool
          12 ( 6.82% of base) : 76007.dasm - Microsoft.CodeAnalysis.ArrayElement`1[Byte][System.Byte]:MakeArray(Microsoft.CodeAnalysis.ArrayElement`1[System.Byte][]):System.Byte[]

Top method improvements (percentages):
         -40 (-21.28% of base) : 123360.dasm - System.Xml.HtmlEncodedRawTextWriter:OutputRestAmps():this
         -28 (-20.00% of base) : 224532.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush(int,int,int):this
        -128 (-18.39% of base) : 123505.dasm - System.Xml.XmlEncodedRawTextWriter:WriteCData(System.String):this
         -16 (-17.39% of base) : 191546.dasm - System.Linq.Parallel.FixedMaxHeap`1[Byte][System.Byte]:Swap(int,int):this
         -20 (-17.24% of base) : 224531.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush(int,int):this
         -20 (-16.67% of base) : 224534.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush2(int,int):this
        -228 (-15.75% of base) : 127712.dasm - System.Xml.DtdParser:ScanAttlist6():int:this
         -44 (-14.67% of base) : 101825.dasm - Microsoft.Diagnostics.Tracing.Ctf.CtfMetadataLegacyParser:FindCloseBrace(System.String,int):int
         -64 (-14.55% of base) : 123506.dasm - System.Xml.XmlEncodedRawTextWriter:WriteComment(System.String):this
         -52 (-14.44% of base) : 110471.dasm - System.Data.Select:Sort(int,int):this
        -120 (-14.08% of base) : 125466.dasm - System.Xml.XmlTextReaderImpl:ParseNamedCharRefInline(int,bool,System.Text.StringBuilder):int:this
        -348 (-14.01% of base) : 127693.dasm - System.Xml.DtdParser:ScanSubsetContent():int:this
        -252 (-14.00% of base) : 236122.dasm - Xunit.Sdk.Sha1Digest:ProcessBlock():this
         -16 (-13.79% of base) : 123532.dasm - <>c:<WriteStartAttributeAsync>b__103_0(System.Xml.XmlEncodedRawTextWriter):this
         -16 (-13.79% of base) : 112076.dasm - System.Data.Common.CharStorage:Compare(int,int):int:this
         -16 (-13.79% of base) : 112859.dasm - System.Data.Common.Int16Storage:Compare(int,int):int:this
         -16 (-13.79% of base) : 113057.dasm - System.Data.Common.UInt16Storage:Compare(int,int):int:this
         -16 (-13.79% of base) : 123491.dasm - System.Xml.XmlEncodedRawTextWriter:WriteStartAttribute_SetInAttribute():this
         -40 (-13.70% of base) : 130220.dasm - Parser:Parse4Dig(int,byref):bool:this
         -80 (-13.70% of base) : 123728.dasm - System.Xml.XmlUtf8RawTextWriter:WriteCData(System.String):this

5932 total methods with Code Size differences (5552 improved, 380 regressed), 2049 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries_tests.pmi.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 116768772 (overridden on cmd)
Total bytes of diff: 116728516 (overridden on cmd)
Total bytes of delta: -40256 (-0.03 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         124 : 23577.dasm (2.45% of base)
         124 : 23583.dasm (2.44% of base)
         124 : 23589.dasm (2.45% of base)
         124 : 23595.dasm (2.44% of base)
         124 : 23604.dasm (2.44% of base)
         124 : 23610.dasm (2.45% of base)
         124 : 23616.dasm (2.45% of base)
         124 : 23622.dasm (2.44% of base)
         124 : 23694.dasm (2.44% of base)
         124 : 23529.dasm (2.44% of base)
         124 : 23535.dasm (2.44% of base)
         124 : 23541.dasm (2.44% of base)
         124 : 23553.dasm (2.44% of base)
         124 : 23559.dasm (2.44% of base)
         124 : 23565.dasm (2.44% of base)
         124 : 23571.dasm (2.44% of base)
         100 : 23547.dasm (1.55% of base)
          96 : 187243.dasm (4.77% of base)
          76 : 19812.dasm (3.56% of base)
          72 : 290472.dasm (2.98% of base)

Top file improvements (bytes):
        -664 : 94.dasm (-6.53% of base)
        -332 : 201220.dasm (-8.51% of base)
        -324 : 332397.dasm (-4.29% of base)
        -324 : 62.dasm (-4.29% of base)
        -144 : 118819.dasm (-4.96% of base)
        -140 : 332423.dasm (-0.68% of base)
        -124 : 131944.dasm (-8.18% of base)
        -116 : 118818.dasm (-4.68% of base)
        -108 : 223100.dasm (-7.44% of base)
         -96 : 332344.dasm (-2.93% of base)
         -96 : 178189.dasm (-10.81% of base)
         -92 : 332226.dasm (-6.01% of base)
         -88 : 332167.dasm (-9.17% of base)
         -80 : 168719.dasm (-2.80% of base)
         -80 : 168720.dasm (-2.38% of base)
         -76 : 142106.dasm (-0.08% of base)
         -72 : 118676.dasm (-5.33% of base)
         -68 : 300276.dasm (-6.34% of base)
         -64 : 168350.dasm (-2.89% of base)
         -64 : 168351.dasm (-2.69% of base)

6352 total files with Code Size differences (5573 improved, 779 regressed), 1768 unchanged.

Top method regressions (bytes):
         124 ( 2.44% of base) : 23694.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.add001.add001.Test:MainMethod():int
         124 ( 2.44% of base) : 23622.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.devide001.devide001.Test:MainMethod():int
         124 ( 2.45% of base) : 23616.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.equal001.equal001.Test:MainMethod():int
         124 ( 2.45% of base) : 23610.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.greater001.greater001.Test:MainMethod():int
         124 ( 2.44% of base) : 23604.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.greaterequal001.greaterequal001.Test:MainMethod():int
         124 ( 2.44% of base) : 23595.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.leftshift001.leftshift001.Test:MainMethod():int
         124 ( 2.45% of base) : 23589.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.less001.less001.Test:MainMethod():int
         124 ( 2.44% of base) : 23583.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.lessequal001.lessequal001.Test:MainMethod():int
         124 ( 2.45% of base) : 23577.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.logicaland001.logicaland001.Test:MainMethod():int
         124 ( 2.44% of base) : 23571.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.logicalor001.logicalor001.Test:MainMethod():int
         124 ( 2.44% of base) : 23565.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.logicalxor001.logicalxor001.Test:MainMethod():int
         124 ( 2.44% of base) : 23559.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.multi001.multi001.Test:MainMethod():int
         124 ( 2.44% of base) : 23553.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.notequal001.notequal001.Test:MainMethod():int
         124 ( 2.44% of base) : 23541.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.remainder001.remainder001.Test:MainMethod():int
         124 ( 2.44% of base) : 23535.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.rightshift001.rightshift001.Test:MainMethod():int
         124 ( 2.44% of base) : 23529.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.sub001.sub001.Test:MainMethod():int
         100 ( 1.55% of base) : 23547.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.IndexerOperator.Binary.or001.or001.Test:MainMethod():int
          96 ( 4.77% of base) : 187243.dasm - System.Tests.StringTests:EndsWithNoMatch_StringComparison()
          76 ( 3.56% of base) : 19812.dasm - System.Collections.Tests.LinkedList_Generic_Tests`1[Byte][System.Byte]:FindLast_T():this
          72 ( 2.98% of base) : 290472.dasm - System.IO.Ports.Tests.Read_char_int_int:Read_ResizeBuffer():this

Top method improvements (bytes):
        -664 (-6.53% of base) : 94.dasm - System.Text.RegularExpressions.RegexInterpreter:Go():this
        -332 (-8.51% of base) : 201220.dasm - RegexTestNamespace.RegexRunnerTestClass:Go():this
        -324 (-4.29% of base) : 332397.dasm - System.Text.RegularExpressions.RegexWriter:EmitFragment(int,System.Text.RegularExpressions.RegexNode,int):this
        -324 (-4.29% of base) : 62.dasm - System.Text.RegularExpressions.RegexWriter:EmitFragment(int,System.Text.RegularExpressions.RegexNode,int):this
        -144 (-4.96% of base) : 118819.dasm - Microsoft.Build.Evaluation.ExpressionShredder:GetReferencedItemNamesAndMetadata(System.String,int,int,byref,int)
        -140 (-0.68% of base) : 332423.dasm - System.Text.RegularExpressions.Generator.RegexGenerator:<EmitCompleteGo>g__EmitOneCode|11_2(System.String,byref)
        -124 (-8.18% of base) : 131944.dasm - Microsoft.Diagnostics.Runtime.Desktop.DesktopHeapType:FixGenericsWorker(System.String,int,int,System.Text.StringBuilder):int
        -116 (-4.68% of base) : 118818.dasm - Microsoft.Build.Evaluation.ExpressionShredder:GetReferencedItemExpressions(System.String,int,int):System.Collections.Generic.List`1[[Microsoft.Build.Evaluation.ExpressionShredder+ItemExpressionCapture, Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]
        -108 (-7.44% of base) : 223100.dasm - DiffPlex.Differ:CalculateEditLength(System.Int32[],int,int,System.Int32[],int,int,System.Int32[],System.Int32[]):DiffPlex.Model.EditLengthResult
         -96 (-10.81% of base) : 178189.dasm - DigestResponse:GetNextValue(System.String,int,bool,byref):System.String:this
         -96 (-2.93% of base) : 332344.dasm - System.Text.RegularExpressions.RegexParser:ScanGroupOpen():System.Text.RegularExpressions.RegexNode:this
         -92 (-6.01% of base) : 332226.dasm - System.Text.RegularExpressions.RegexCode:OpcodeDescription(int,System.Int32[],System.String[]):System.String
         -88 (-9.17% of base) : 332167.dasm - System.Text.RegularExpressions.RegexBoyerMoore:.ctor(System.String,bool,bool,System.Globalization.CultureInfo):this
         -80 (-2.80% of base) : 168719.dasm - System.Linq.Tests.TakeTests:MutableSource():this
         -80 (-2.38% of base) : 168720.dasm - System.Linq.Tests.TakeTests:MutableSourceNotList():this
         -76 (-0.08% of base) : 142106.dasm - <ValidateIdentifiers_Invalid_TestData>d__2:MoveNext():bool:this
         -72 (-5.33% of base) : 118676.dasm - Microsoft.Build.Evaluation.Scanner:Advance():bool:this
         -68 (-6.34% of base) : 300276.dasm - System.IPv6AddressHelper:Parse(System.ReadOnlySpan`1[Char],System.Span`1[UInt16],int,byref)
         -64 (-2.68% of base) : 242194.dasm - Microsoft.DotNet.ProjectModel.FileSystemGlobbing.Internal.Patterns.PatternBuilder:Build(System.String):Microsoft.DotNet.ProjectModel.FileSystemGlobbing.Internal.IPattern:this
         -64 (-2.89% of base) : 168350.dasm - System.Linq.Tests.SelectTests:Select_SourceIsListSkipTakeCount():this

Top method regressions (percentages):
          24 (10.00% of base) : 1595.dasm - Roslyn.Utilities.PathUtilities:PathsEqual(System.String,System.String,int):bool
          28 ( 8.43% of base) : 307752.dasm - System.Numerics.Tests.GenericVectorTests:TestDotProduct():this
          28 ( 7.95% of base) : 3578.dasm - Microsoft.CodeAnalysis.ImmutableArrayExtensions:SequenceEqual(System.Collections.Immutable.ImmutableArray`1[Byte],System.Collections.Immutable.ImmutableArray`1[Byte],System.Nullable`1[Int32],System.Func`4[Byte,Byte,Nullable`1,Boolean]):bool
           8 ( 7.69% of base) : 1055.dasm - Roslyn.Utilities.ObjectReader:ReadInt8ArrayElements(System.SByte[]):System.SByte[]:this
          12 ( 7.50% of base) : 308494.dasm - System.Numerics.Tests.Util:AllEqual(System.Byte[],System.Byte[]):bool
          12 ( 7.50% of base) : 308493.dasm - System.Numerics.Tests.Util:AnyEqual(System.Byte[],System.Byte[]):bool
          12 ( 7.32% of base) : 193092.dasm - System.Security.Cryptography.Encryption.TripleDes.Tests.TripleDesTests:RemoveDesParityBits(System.Byte[]):System.Byte[]
          40 ( 7.25% of base) : 115886.dasm - Microsoft.Build.Shared.FileUtilities:PathsEqual(System.String,System.String):bool
          40 ( 7.25% of base) : 238332.dasm - Microsoft.Build.Shared.FileUtilities:PathsEqual(System.String,System.String):bool
          40 ( 7.25% of base) : 122227.dasm - Microsoft.Build.Shared.FileUtilities:PathsEqual(System.String,System.String):bool
          12 ( 6.98% of base) : 153990.dasm - BasicEventSourceTests.TestsWriteEvent:Equal(System.Byte[],System.Byte[]):bool
          12 ( 6.98% of base) : 338690.dasm - System.Transactions.Tests.NonMsdtcPromoterTests:PromotedTokensMatch(System.Byte[],System.Byte[]):bool
          12 ( 6.82% of base) : 251089.dasm - Microsoft.VisualStudio.Composition.Utilities:EqualsByValue(System.Collections.Immutable.ImmutableArray`1[Byte],System.Collections.Immutable.ImmutableArray`1[Byte]):bool
          12 ( 6.67% of base) : 224173.dasm - ImTools.ArrayTools:Copy(System.Byte[]):System.Byte[]
          12 ( 6.67% of base) : 284829.dasm - System.IO.Compression.Tests.ZipFileTestBase:ArraysEqual(System.Byte[],System.Byte[]):bool
          12 ( 6.67% of base) : 285293.dasm - System.IO.Compression.Tests.ZipFileTestBase:ArraysEqual(System.Byte[],System.Byte[]):bool
           8 ( 6.67% of base) : 100111.dasm - System.Text.Json.Serialization.Tests.StreamTests:GetArr_TypedElements(int):System.Byte[]
           8 ( 6.45% of base) : 167542.dasm - System.Linq.Tests.EnumerableTests:Repeat(System.Func`2[Int32,Byte],int):System.Byte[]
          12 ( 6.25% of base) : 251288.dasm - BufferComparer:Equals(System.Byte[],System.Byte[]):bool:this
          12 ( 6.25% of base) : 3620.dasm - Microsoft.CodeAnalysis.ImmutableArrayExtensions:All(System.Collections.Immutable.ImmutableArray`1[Byte],System.Func`3[Byte,Nullable`1,Boolean],System.Nullable`1[Int32]):bool

Top method improvements (percentages):
         -16 (-16.67% of base) : 112477.dasm - Piles@527-4:Invoke(int,int):Microsoft.FSharp.Core.Unit:this
         -16 (-16.67% of base) : 112412.dasm - Shuffle@437-5[Byte][System.Byte]:Invoke(int,int):Microsoft.FSharp.Core.Unit:this
         -16 (-16.67% of base) : 112394.dasm - shuffleInPlace@426-3[Byte][System.Byte]:Invoke(int,int):Microsoft.FSharp.Core.Unit:this
         -56 (-15.38% of base) : 133225.dasm - Microsoft.Diagnostics.Runtime.Utilities.Pdb.BitAccess:ReadInt64(byref):this
         -16 (-14.29% of base) : 22692.dasm - <>c__DisplayClass16_1[__Canon][System.__Canon]:<GetRangeValidations>b__0():System.Object:this
         -16 (-14.29% of base) : 22693.dasm - <>c__DisplayClass16_1[Byte][System.Byte]:<GetRangeValidations>b__0():System.Object:this
         -16 (-14.29% of base) : 22694.dasm - <>c__DisplayClass16_2[__Canon][System.__Canon]:<GetRangeValidations>b__1():System.Object:this
         -16 (-14.29% of base) : 22695.dasm - <>c__DisplayClass16_2[Byte][System.Byte]:<GetRangeValidations>b__1():System.Object:this
         -52 (-14.29% of base) : 118981.dasm - Microsoft.Build.Internal.Utilities:ContainsNoTagsOtherThanComments(System.String,int):bool
         -24 (-13.95% of base) : 315605.dasm - BR:ReadInt32():int:this
         -16 (-13.33% of base) : 202361.dasm - <>c__DisplayClass14_0:<NamedBlocksInclusionsExpected>b__0(ushort):bool:this
         -12 (-13.04% of base) : 97.dasm - System.Text.RegularExpressions.RegexInterpreter:TrackPush(int):this
         -24 (-12.77% of base) : 133224.dasm - Microsoft.Diagnostics.Runtime.Utilities.Pdb.BitAccess:ReadInt32(byref):this
         -20 (-12.50% of base) : 298243.dasm - System.Net.Mime.MailBnfHelper:IsFWSAt(System.String,int):bool
         -24 (-12.50% of base) : 300731.dasm - System.Net.SocketAddress:CopyAddressSizeIntoBuffer():this
         -24 (-12.50% of base) : 300440.dasm - System.Net.SocketAddress:CopyAddressSizeIntoBuffer():this
         -28 (-11.67% of base) : 238449.dasm - Microsoft.Build.Shared.FileMatcher:HasMisplacedRecursiveOperator(System.String):bool
         -28 (-11.67% of base) : 116026.dasm - Microsoft.Build.Shared.FileMatcher:HasMisplacedRecursiveOperator(System.String):bool
         -28 (-11.67% of base) : 122216.dasm - Microsoft.Build.Shared.FileMatcher:HasMisplacedRecursiveOperator(System.String):bool
         -56 (-11.48% of base) : 217495.dasm - System.Data.SqlClient.TdsParser:WriteLong(long,System.Data.SqlClient.TdsParserStateObject):this

6352 total methods with Code Size differences (5573 improved, 779 regressed), 1768 unchanged.

```

</details>

--------------------------------------------------------------------------------

some diffs we weren't able to fold cloned loops because of it, e.g. for:
```csharp
private static bool Test(byte[] prefix, byte[] byteArray)
{
    if (prefix == null || byteArray == null || prefix.Length > byteArray.Length)
        return false;
    for (int i = 0; i < prefix.Length; i++)
    {
        if (prefix[i] != byteArray[i])
            return false;
    }
    return true;
}
```
^ diff: https://www.diffchecker.com/oUPb1br3
We clone the loop in both my PR and Main, but in Main we then are able to drop it, but not it "PR" due to that CSE of ADD. Both loops don't have bound checks. Btw, number of `bl CORINFO_HELP_RNGCHKFAIL` is the same in base and diff diffs so I assume this PR doesn't regress bound check elimination.

A couple of size-regression examples:
https://www.diffchecker.com/VkGHhEin
https://www.diffchecker.com/nOuaRBkO
https://www.diffchecker.com/LDIAWDHY

improvements:
https://www.diffchecker.com/zxoJy9vQ

### CODE REVIEW

**Comment by EgorBo** [comment]
I ran a couple of dotnet/performance benchmarks:
```
| Faster                                                          | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| --------------------------------------------------------------- | ---------:| ----------------:| ----------------:| -------- |
| Benchstone.BenchI.TreeInsert.Test                               |      1.56 |         47667.43 |         30543.60 | bimodal |
| SeekUnroll.Test(boxedIndex: 27)                                 |      1.50 |     938645542.00 |     625722750.00 |         |
| SeekUnroll.Test(boxedIndex: 3)                                  |      1.50 |     938589521.00 |     625770375.00 |         |
| SciMark2.kernel.benchSparseMult                                 |      1.15 |     469878458.00 |     407268833.00 |         |
| System.Numerics.Tests.Perf_BitOperations.LeadingZeroCount_uint  |      1.15 |           597.57 |           520.92 |         |
| System.Numerics.Tests.Perf_BitOperations.LeadingZeroCount_ulong |      1.14 |           598.13 |           522.41 |         |
| Benchstone.BenchI.CSieve.Test                                   |      1.14 |       4139455.41 |       3623725.51 |         |
| Benchstone.BenchI.AddArray2.Test                                |      1.12 |       5261706.59 |       4687558.60 |         |
| Burgers.Test1                                                   |      1.10 |     138233916.50 |     125235312.50 |         |
| Burgers.Test2                                                   |      1.09 |     137031989.50 |     125238250.00 |         |
| System.Numerics.Tests.Perf_BitOperations.PopCount_uint          |      1.08 |           515.04 |           475.31 |         |
| System.Numerics.Tests.Perf_BitOperations.Log2_ulong             |      1.08 |           609.98 |           563.30 |         |
| System.Numerics.Tests.Perf_BitOperations.Log2_uint              |      1.08 |           608.38 |           562.71 |         |
| SciMark2.kernel.benchFFT                                        |      1.07 |     520232666.00 |     485479459.00 |         |
| ByteMark.BenchNumericSortJagged                                 |      1.07 |    1061907479.50 |     994064208.00 |         |
| Burgers.Test0                                                   |      1.06 |     174896583.00 |     164355125.00 |         |
| Benchstone.BenchI.XposMatrix.Test                               |      1.06 |         12267.20 |         11569.69 |         |
| SciMark2.kernel.benchmarkLU                                     |      1.05 |     467178750.00 |     443115708.00 |         |
```

**Comment by EgorBo** [comment]
`CopyArray` benchmark from here https://github.com/dotnet/runtime/pull/61045#issuecomment-956006143 got additional +10% improvement

**Comment by EgorBo** [comment]
Next step is simple: fold
```asm
ubfiz   x4, x2, #2, #32
ldr     w4, [x1, x4]
```
into just
```asm
w4, [x1, x2, uxtw]
```
and we'll get a perfect codegen for cases when "arrRef + elemOffset" is CSE'd/hoisted.

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -5465,11 +5465,21 @@ GenTree* Compiler::fgMorphArrayIndex(GenTree* tree)
 
     GenTree* cns = gtNewIconNode(elemOffs, TYP_I_IMPL);
 
+// We're going to create a platform-specific address:
+//
+// XArch:   "arrRef + (index + elemOffset)"
+// ArmArch: "(arrRef + elemOffset) + index" // both ADD are BYREF here
+//
+// It'll allow us to hoist/CSE the invariant part which is "arrRef + elemOffset" on ArmArch.
+// We don't really need it on XArch because of more powerful addressing modes such as [base + index*scale + offset]
```
Comment (SingleAccretion) [inline src/coreclr/jit/morph.cpp:5474]: I would like to understand how this impacts `ParseArrayAddress`: are there any diffs in what it returned before and what it returns now?

Comment (EgorBo) [reply src/coreclr/jit/morph.cpp:5474]: ParseArrayAddressWork seems to be handling well this pattern and recognizes indices just fine for my samples, not sure about other methods in the diffs - there is too many of them

**Comment by EgorBo** [comment]
With `LEA(BFIZ)` optimization:
```csharp
[Benchmark]
[ArgumentsSource(nameof(TestData))]
public int Sum(int[] array)
{
    int sum = 0;
    for (int i = 0; i < array.Length; i++)
    {
        sum += array[i];
    }
    return sum;
}
```
Benchmark results on Apple M1 arm64:
```
                             | Method |         array |     Mean |     Error |
                             |------- |-------------- |---------:|----------:|
Main without #61045 + #61035 |    Sum | Int32[100000] | 60,08 ns | 15.321 ns |
                Current Main |    Sum | Int32[100000] | 53.78 us |  0.007 us |
                     This PR |    Sum | Int32[100000] | 32.61 us |  0.082 us |
```
Codegen diff:
- Main vs This PR: https://www.diffchecker.com/4BPIsvbp
- Main before #61045 and #61035  vs This PR https://www.diffchecker.com/smwmMHvi

**Comment by EgorBo** [comment]
Diffs are much better when LEA(BFIZ) is enabled for short/char but there is an issue in the emitter (emits incorrect shift)

**Comment by kunalspathak** [comment]
@EgorBo  - It might be good to post PerfScore diff as well, will be good to understand if there is lot of regression in it. Also, do you mind posting the diffs for benchmark collection?

**Comment by kunalspathak** [comment]
From the diffs, it looks like most of them are also coming from loop alignment. Might be worth turning loop alignment off for baseline/test to see the real code size impact.

**Comment by EgorBo** [comment]
> @EgorBo - It might be good to post PerfScore diff as well, will be good to understand if there is lot of regression in it. Also, do you mind posting the diffs for benchmark collection?

How do I ask superpmi to generate perfscore btw?

> diffs for benchmark collection

it looks like it's not available for altjit mode I am running spmi under (I wasn't able to run spmi on my apple-m1)

**Comment by SingleAccretion** [comment]
> How do I ask superpmi to generate perfscore btw?

FWIW, I usually just `cd` into the directory SPMI created for diffs and `jit-analyze -b base -d diff -m PerfScore` directly.

**Comment by kunalspathak** [comment]
> How do I ask superpmi to generate perfscore btw?
> 
> >

It is only available for windows arm64.

```
D:\git\runtime>python src\coreclr\scripts\superpmi.py list-collections -target_arch arm64
================ Logging to E:\spmi\superpmi.364.log
Using JIT/EE Version from jiteeversionguid.h: 3df3e3ec-b1f6-4e6d-8439-2e7f3f7fa2ac
SuperPMI list-collections

5 collections for 3df3e3ec-b1f6-4e6d-8439-2e7f3f7fa2ac/windows/arm64/

https://clrjit2.blob.core.windows.net/superpmi/collections/3df3e3ec-b1f6-4e6d-8439-2e7f3f7fa2ac/windows/arm64/benchmarks.run.windows.arm64.checked.mch.zip
https://clrjit2.blob.core.windows.net/superpmi/collections/3df3e3ec-b1f6-4e6d-8439-2e7f3f7fa2ac/windows/arm64/coreclr_tests.pmi.windows.arm64.checked.mch.zip
https://clrjit2.blob.core.windows.net/superpmi/collections/3df3e3ec-b1f6-4e6d-8439-2e7f3f7fa2ac/windows/arm64/libraries.crossgen2.windows.arm64.checked.mch.zip
https://clrjit2.blob.core.windows.net/superpmi/collections/3df3e3ec-b1f6-4e6d-8439-2e7f3f7fa2ac/windows/arm64/libraries.pmi.windows.arm64.checked.mch.zip
https://clrjit2.blob.core.windows.net/superpmi/collections/3df3e3ec-b1f6-4e6d-8439-2e7f3f7fa2ac/windows/arm64/libraries_tests.pmi.windows.arm64.checked.mch.zip
```

You can use windows collection by passing `-target_os windows -target_arch arm64` to the `superpmi.py`.

File: src/coreclr/jit/morph.cpp [hunk 2]
```diff
@@ -5562,48 +5572,61 @@ GenTree* Compiler::fgMorphArrayIndex(GenTree* tree)
...
-    if (addr->OperGet() == GT_ADD)
+    if (addr->OperIs(GT_ADD))
     {
-        assert(addr->TypeGet() == TYP_BYREF);
-        assert(addr->AsOp()->gtOp1->TypeGet() == TYP_REF);
-
-        addr = addr->AsOp()->gtOp2;
+#ifdef TARGET_ARMARCH
+        // On arm/arm64 addr tree is a bit different, see above ^
+        if (addr->gtGetOp1()->OperIs(GT_ADD) && addr->gtGetOp1()->gtGetOp2()->IsCnsIntOrI())
```
Comment (kunalspathak) [inline src/coreclr/jit/morph.cpp:5592]: nit: It might be that `morph.cpp` is filled with `gtGetOp1()` , but it will be good to extract it in a variable with meaningful name for ease understanding specially things like `addr->gtGetOp1()->gtGetOp2()`

File: src/coreclr/jit/lower.cpp [hunk 3]
```diff
@@ -5033,6 +5033,28 @@ bool Lowering::TryCreateAddrMode(GenTree* addr, bool isContainable, var_types ta
...
+        assert(cast->isContained());
+
+        const unsigned shiftBy = (unsigned)index->gtGetOp2()->AsIntCon()->IconValue();
+
+        // 'scale' and 'offset' have to be unset since we're going to use [base + index * SXTW/UXTW scale] form
+        // where there is no room for additional offsets/scales on ARM64. 'shiftBy' has to match target's width.
+        if (varTypeIsInt(cast->CastFromType()) && varTypeIsLong(cast->CastToType()) &&
+            (genTypeSize(targetType) == (1U << shiftBy)) && (scale == 1) && (offset == 0))
+        {
+            // TODO: Make sure that genCreateAddrMode marks such BFIZ candidates as GTF_DONT_CSE for better CQ.
```
Comment (kunalspathak) [inline src/coreclr/jit/lower.cpp:5052]: Will you be verifying it as part of this PR?

**Review by kunalspathak — APPROVED** [review]
LGTM.

File: src/coreclr/jit/emitarm64.cpp [hunk 4]
```diff
@@ -13481,8 +13481,24 @@ void emitter::emitInsLoadStoreOp(instruction ins, emitAttr attr, regNumber dataR
...
-                    emitIns_R_R_R(ins, attr, dataReg, memBase->GetRegNum(), index->GetRegNum());
+                    if (index->OperIs(GT_BFIZ) && index->isContained())
+                    {
+                        // Then load/store dataReg from/to [memBase + index*scale with sign/zero extension]
+                        GenTreeCast* cast = index->gtGetOp1()->AsCast();
+
+                        // For now, this code only supports extensions from i32/u32
+                        assert(cast->isContained() && varTypeIsInt(cast->CastFromType()));
+
+                        const bool isZeroExtended = cast->IsUnsigned() || varTypeIsUnsigned(cast->CastToType());
```
Comment (SingleAccretion) [inline src/coreclr/jit/emitarm64.cpp:13492]: This should be just `cast->IsUnsigned()` because for `int -> long` that's what decides whether the cast is zero-extending or not. There are casts that have `TYP_ULONG` as the target type but no `GTF_UNSIGNED` set, they are sign-extending.

File: src/coreclr/jit/lower.cpp [hunk 5]
```diff
@@ -5033,6 +5033,28 @@ bool Lowering::TryCreateAddrMode(GenTree* addr, bool isContainable, var_types ta
...
+        // BFIZ node is a binary op where op1 is GT_CAST and op2 is GT_CNS_INT
+        GenTreeCast* cast = index->gtGetOp1()->AsCast();
+        assert(cast->isContained());
+
+        const unsigned shiftBy = (unsigned)index->gtGetOp2()->AsIntCon()->IconValue();
+
+        // 'scale' and 'offset' have to be unset since we're going to use [base + index * SXTW/UXTW scale] form
+        // where there is no room for additional offsets/scales on ARM64. 'shiftBy' has to match target's width.
+        if (varTypeIsInt(cast->CastFromType()) && varTypeIsLong(cast->CastToType()) &&
+            (genTypeSize(targetType) == (1U << shiftBy)) && (scale == 1) && (offset == 0))
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:5050]: It would be cheaper to rewrite these checks as the equivalent `cast->CastOp()->TypeIs(TYP_INT) && cast->TypeIs(TYP_LONG)`.

File: src/coreclr/jit/lower.cpp [hunk 6]
```diff
@@ -5033,6 +5033,28 @@ bool Lowering::TryCreateAddrMode(GenTree* addr, bool isContainable, var_types ta
         }
     }
 
+#ifdef TARGET_ARM64
+    // Check if we can "contain" LEA(BFIZ) in order to extend 32bit index to 64bit as part of load/store.
+    if (index != nullptr && index->OperIs(GT_BFIZ) && index->gtGetOp1()->OperIs(GT_CAST) &&
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:5038]:
```suggestion
    if ((index != nullptr) && index->OperIs(GT_BFIZ) && index->gtGetOp1()->OperIs(GT_CAST) &&
```

File: src/coreclr/jit/morph.cpp [hunk 7]
```diff
@@ -5562,48 +5572,61 @@ GenTree* Compiler::fgMorphArrayIndex(GenTree* tree)
 
     if (fgIsCommaThrow(tree))
     {
-        if ((arrElem != indTree) ||         // A new tree node may have been created
-            (indTree->OperGet() != GT_IND)) // The GT_IND may have been changed to a GT_CNS_INT
+        if ((arrElem != indTree) ||    // A new tree node may have been created
+            (indTree->OperIs(GT_IND))) // The GT_IND may have been changed to a GT_CNS_INT
```
Comment (BruceForstall) [inline src/coreclr/jit/morph.cpp:5576]: Shouldn't this be `!indTree->OperIs(GT_IND)` (i.e., you dropped the `!`)?

File: src/coreclr/jit/morph.cpp [hunk 8]
```diff
@@ -5465,11 +5465,21 @@ GenTree* Compiler::fgMorphArrayIndex(GenTree* tree)
...
     GenTree* cns = gtNewIconNode(elemOffs, TYP_I_IMPL);
 
+// We're going to create a platform-specific address:
+//
+// XArch:   "arrRef + (index + elemOffset)"
+// ArmArch: "(arrRef + elemOffset) + index" // both ADD are BYREF here
+//
+// It'll allow us to hoist/CSE the invariant part which is "arrRef + elemOffset" on ArmArch.
+// We don't really need it on XArch because of more powerful addressing modes such as [base + index*scale + offset]
+//
```
Comment (BruceForstall) [inline src/coreclr/jit/morph.cpp:5475]: You can use the ` CLANG_FORMAT_COMMENT_ANCHOR;` hack here to fix the comment indenting.

File: src/coreclr/jit/morph.cpp [hunk 9]
```diff
@@ -5465,11 +5465,21 @@ GenTree* Compiler::fgMorphArrayIndex(GenTree* tree)
 
     GenTree* cns = gtNewIconNode(elemOffs, TYP_I_IMPL);
 
+// We're going to create a platform-specific address:
```
Comment (BruceForstall) [inline src/coreclr/jit/morph.cpp:5468]: You should add a note to the comment above (starting "// Be careful to only create the byref") explaining why this change here is ok.

File: src/coreclr/jit/lower.cpp (hunk 5 above)
Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:5050]: @SingleAccretion what do you mean cheaper - it will skip cases when e.g. cast->CastToType() is TYP_ULONG

**Review by BruceForstall — CHANGES_REQUESTED** [review]
Looks like very good results.

A few minor questions.

File: src/coreclr/jit/morph.cpp (hunk 7 above)
Comment (EgorBo) [reply src/coreclr/jit/morph.cpp:5576]: oh, it explains some regressions 🤦‍♂️ thanks for noticing it!

File: src/coreclr/jit/lower.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:5052]: I think I better do it in a follow up one when diffs from this one will settle down 🙂

File: src/coreclr/jit/emitarm64.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/jit/emitarm64.cpp:13492]: hm, good point!

**Comment by BruceForstall** [comment]
You should probably trigger jitstress, and also gcstress0xc to validate our assumption that GC will be happy with this new form of byref

File: src/coreclr/jit/lower.cpp (hunk 5 above)
Comment (SingleAccretion) [reply src/coreclr/jit/lower.cpp:5050]: > it will skip cases when e.g. cast->CastToType() is TYP_ULONG won't it?

I don't believe so. If `CastToType` is `TYP_LONG/TYP_ULONG`, the type of the cast node itself is always `TYP_LONG`.

Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:5050]: I put
```
            assert(cast->CastFromType() == TYP_INT);
            assert(cast->CastToType() == TYP_LONG);
```
and SPMI failed immediately

Comment (SingleAccretion) [reply src/coreclr/jit/lower.cpp:5050]: On the first or the second assert?

Failure on the first assert means something is creating `TYP_UINT`s in IR (this is a bug).
The second assert failure is expected, `CastToType` can be `TYP_ULONG`.

What I asserted would be equivalent to this: `assert(!varTypeIsLong(cast->CastToType()) || !cast->TypeIs(TYP_LONG))`.

Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:5050]: @SingleAccretion it's the second assert - so I guess the check you suggest `cast->CastOp()->TypeIs(TYP_INT) && cast->TypeIs(TYP_LONG)` will skip cases with it

Comment (SingleAccretion) [reply src/coreclr/jit/lower.cpp:5050]: I do not see how that is the case. The current check is `CastToType() == TYP_LONG || CastToType() == TYP_ULONG`.

If the `CastToType` is one of those two, the cast node's type (i .e `cast->TypeGet()`, which is what `TypeIs` tests) will be `TYP_LONG`, the reverse is also true. This follows from the fact that nodes do not (and cannot) have `TYP_ULONG`.

FWIW, I have built a cast checker in the past that asserted these invariants, and it did not fail (for them at least, there were a lot of other asserts in it that did fail 😄), so I am pretty confident in this.

Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:5050]: @SingleAccretion ah, I am blind 🤦‍♂️, I didn't notice that you check `cast->TypeIs(TYP_LONG)`, I thought you was proposing `cast->CastToType() == TYP_LONG` 😄

**Comment by EgorBo** [comment]
Regression example:
```csharp
private static int[] _goto;

private static int Test(int destpos)
{
    _goto[destpos] = AddBacktrackNote();
    return _goto[destpos];
}
```
Here index is invariant but `_goto` arrayref is not (it can be changed in `AddBacktrackNote`) so in this case the default `"arrRef + (index + elemOffset)"` shape works better as we will be able to do CSE for `(index + elemOffset)`. Unfortunately I don't know how can I detect patterns like this early in morph. Naïve approaches like "if index is lvParam" don't really work well.
So I'm suggesting we merge it as is and look at regressions in dotnet/performance on perf triage meetings (if there will be a lot of them - address them or revert the commit completely).

A possible solution is a sort of tree re-association phase during CSE/LoopHoisting/VN e.g.
`(invarian1 + x) + invariant2` --reassoc--> `(invariant1 + invariant2) + x`

**Comment by EgorBo** [comment]
@BruceForstall does it look good now? gcstress test failures are timeouts in Vector64_ro/Vector128_ro/Vector256_ro tests which are huge, I guess we might want to disable them for gcstress.

> @EgorBo - It might be good to post PerfScore diff as well, will be good to understand if there is lot of regression in it. Also, do you mind posting the diffs for benchmark collection?

I added the Benchmarks collection to the list (-20kb diff). PerfScore diffs can be found here https://gist.github.com/EgorBo/7ed76fb5bb5a38cc56bae20306b8e080

Thoughts on reducing regressions in follow up PRs are here: https://github.com/dotnet/runtime/pull/61293#issuecomment-964146497

**Comment by kunalspathak** [comment]
> PerfScore diffs can be found here https://gist.github.com/EgorBo/7ed76fb5bb5a38cc56bae20306b8e080

Thanks! There are quite some benchmarks that regressed. Do they fall under same category that you listed an example of?

```
Top method regressions (PerfScoreUnits):
     1750.98 ( 1.82% of base) : 3379.dasm - System.Reflection.Emit.CustomAttributeBuilder:.ctor(System.Reflection.ConstructorInfo,System.Object[],System.Reflection.PropertyInfo[],System.Object[],System.Reflection.FieldInfo[],System.Object[]):this
     1048.40 ( 3.10% of base) : 16191.dasm - Microsoft.CodeAnalysis.CommonReferenceManager`2[__Canon,__Canon][System.__Canon,System.__Canon]:ReuseAssemblySymbols(Microsoft.CodeAnalysis.CommonReferenceManager`2+BoundInputAssembly[System.__Canon,System.__Canon][],System.__Canon[],System.Collections.Immutable.ImmutableArray`1[__Canon],int):this
      415.12 (10.04% of base) : 1003.dasm - JetStream.Statistics:findOptimalSegmentationInternal(System.Single[][],System.Int32[][],System.Double[],JetStream.SampleVarianceUpperTriangularMatrix,int)
      364.16 ( 5.26% of base) : 20019.dasm - Benchstone.BenchI.Array2:Bench(int):bool
      337.20 ( 4.43% of base) : 23223.dasm - Benchstone.BenchF.LLoops:Init():this
      292.90 (14.08% of base) : 4690.dasm - System.Drawing.Imaging.ImageCodecInfo:ConvertFromMemory(long,int):System.Drawing.Imaging.ImageCodecInfo[]
      277.17 ( 2.97% of base) : 1915.dasm - System.DefaultBinder:BindToMethod(int,System.Reflection.MethodBase[],byref,System.Reflection.ParameterModifier[],System.Globalization.CultureInfo,System.String[],byref):System.Reflection.MethodBase:this
      223.74 (12.76% of base) : 1283.dasm - System.DefaultBinder:SelectMethod(int,System.Reflection.MethodBase[],System.Type[],System.Reflection.ParameterModifier[]):System.Reflection.MethodBase:this
      180.12 ( 6.93% of base) : 14874.dasm - LUDecomp:Run():double:this
      162.05 ( 4.30% of base) : 12999.dasm - MessagePack.Formatters.MicroBenchmarks_Serializers_MyEventsListerItemTaskFormatter3:Deserialize(System.Byte[],int,MessagePack.IFormatterResolver,byref):MicroBenchmarks.Serializers.MyEventsListerItemTask:this
      137.12 ( 7.09% of base) : 1745.dasm - System.Reflection.Emit.MethodBuilder:CreateMethodBodyHelper(System.Reflection.Emit.ILGenerator):this
      133.00 ( 2.48% of base) : 1141.dasm - ProtoBuf.Meta.MetaType:ResolveTupleConstructor(System.Type,byref):System.Reflection.ConstructorInfo
      129.60 ( 1.50% of base) : 16691.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol:MakeTypeParameters(Microsoft.CodeAnalysis.DiagnosticBag):System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]:this
       93.74 ( 4.71% of base) : 20022.dasm - Benchstone.BenchI.Array2:VerifyCopy(System.Int32[][][],System.Int32[][][]):bool
       82.00 ( 1.46% of base) : 13932.dasm - NeuralJagged:read_data_file():this
       79.20 ( 3.91% of base) : 13941.dasm - NeuralJagged:move_wt_changes()
       74.10 (11.71% of base) : 11425.dasm - EMFloatClass:Run():double:this
       72.00 (10.69% of base) : 22951.dasm - ConstructorMatcher:Match(System.Object[]):int:this
       62.40 ( 3.31% of base) : 13948.dasm - NeuralJagged:adjust_mid_wts(int)
       62.25 ( 7.46% of base) : 3540.dasm - System.Xml.Serialization.TypeScope:Popu
```

**Review by BruceForstall — APPROVED** [review]

**Comment by EgorBo** [comment]
@kunalspathak I changed the code slight, the diff is slightly misleading but what I've done is basically converted ifdef-else into normal if-else and enabled that new shape `(arrRef + elemOffset) + index` only for primitive types, it significantly improved diffs, e.g. Benchmarks collections was:
1332 improved, 365 regressed
now:
1136 improved, 84 regressed

Most of the benchmarks you listed got fixed, BenchI.AddArray is still a size regression but overall it looks like a perf improvement actually: https://www.diffchecker.com/Msv0RBMs (less code in loops)

New diffs: https://gist.github.com/EgorBo/dd3b682f69ce2a530a8019c0e8bf46b2

**Comment by EgorBo** [comment]
arm64 improvements https://github.com/dotnet/perf-autofiling-issues/issues/2248

**Comment by DrewScoggins** [comment]
More Arm64 improvements https://github.com/dotnet/perf-autofiling-issues/issues/2419

**Comment by AndyAyersMS** [comment]
More improvements: https://github.com/dotnet/perf-autofiling-issues/issues/2406

**Comment by AndyAyersMS** [comment]
Arm64 regression: https://github.com/dotnet/perf-autofiling-issues/issues/2401
newplot (87)

also https://github.com/dotnet/perf-autofiling-issues/issues/2400
newplot (88)
