### PR TITLE
[mono] Fix aot compiler crash when checking for method signature

### LINKED ISSUE #103901: AOT compiler should error out gracefully instead of crashing
### Description

AOT compiler crashes with invalid input.

The underlying cause for the failure is that the project file is adding references (using Reference items) to assemblies that reference assemblies that are not referenced. If the project used a ProjectReference or PackageReference, there would be a build warning or error complaining about something at some point when computing which assemblies to reference, but when using Reference items directly, the csproj author is responsible for getting it right.

The csproj author didn't get it right, and the set of assemblies to AOT compile isn't a coherent set of assemblies.

The bug is that the AOT compiler shouldn't crash when it encounters such invalid output, it should fail gracefully.

### Reproduction Steps

Test project: [aot-compiler-crash-deaab45.zip](https://github.com/user-attachments/files/15957860/aot-compiler-crash-deaab45.zip)

Build the project to reproduce:

```console
 dotnet build /p:RuntimeIdentifier=ios-arm64 -c Debug
```

### Expected behavior

An error message explaining what went wrong.

### Actual behavior

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1215,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 139.
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1215,3): error : Failed to AOT compile Microsoft.Maui.Controls.HotReload.Forms.dll, the AOT compiler exited with code 139.
```

### Regression?

Probably not.

### Known Workarounds

Don't make mistakes?

### Configuration

```
$ dotnet --info
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.3a2c5bc5
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.301/

.NET workloads installed:
 [maui-maccatalyst]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.21/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.21/WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8473-ci.main/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.ios/17.2.8473-ci.main/WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8473-ci.main/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maccatalyst/17.2.8473-ci.main/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-preview.4.24266.19
  Architecture: arm64
  Commit:       d0d6fed6c0

.NET SDKs installed:
  7.0.311 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]
  8.0.104 [/usr/local/share/dotnet/sdk]
  8.0.201 [/usr/local/share/dotnet/sdk]
  8.0.301 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.3.24153.2 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.4.24260.3 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.4.24267.66 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.3.24151.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24260.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24267.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24129.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24260.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24266.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/rolf/test/dotnet/aot-compiler-crash/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Other information

_No response_

### PR DESCRIPTION
**Pull request by steveisok**
This fixes a problem with the aot compiler where it tries to get a generic parameter count from a method, but instead crashes because the reference is null.

The problem stemmed from loading an assembly that had references to other assemblies that were not found. The aot compiler eventually figures out it can't do anything and exits. The crash occurred in between the validation process.

Fixes https://github.com/dotnet/runtime/issues/103901

### CODE REVIEW

**Review by fanyang-mono — APPROVED** [review]
LGTM

File: src/mono/mono/mini/aot-compiler.c [hunk 1]
```diff
@@ -12948,13 +12948,21 @@ should_emit_extra_method_for_generics (MonoMethod *method, gboolean reference_ty
 	MonoGenericParam *gen_param = NULL;
 	unsigned int gen_param_count;
 
+	ERROR_DECL (error);
```
Comment (lambdageek) [inline src/mono/mono/mini/aot-compiler.c:12951]: Add an extra `MonoError*` argument to `should_emit_extra_method_for_generics` and to `should_emit_gsharedvt_method` and pass in an error from the caller (it's `collect_methods` for both).

If the error is not `is_ok (error)` at the call sites, you need to call `mono_error_cleanup` on it to deallocate it.  (if the error is `ok`, there's nothing to cleanup, but it also is harmless to call `mono_error_cleanup`)

**Review by lambdageek — COMMENTED** [review]
it's better to let the errors percolate to the callers, not to consume them locally.  Also if there's an error, you have to clean up

File: src/mono/mono/mini/aot-compiler.c [hunk 2]
```diff
@@ -13098,7 +13097,7 @@ collect_methods (MonoAotCompile *acfg)
 			}
 		}
 
-		if ((method->is_generic || mono_class_is_gtd (method->klass)) && should_emit_gsharedvt_method (acfg, method)) {
```
Comment (lambdageek) [inline src/mono/mono/mini/aot-compiler.c:13093]: I think this now needs an `else if (!is_ok (error))` branch.  at the very least to call `mono_error_cleanup`, but also maybe to show a warning

File: src/mono/mono/mini/aot-compiler.c [hunk 3]
```diff
@@ -13055,15 +13053,16 @@ collect_methods (MonoAotCompile *acfg)
...
 			method = mini_get_shared_method_full (method, SHARE_MODE_NONE, error);
-			if (!method) {
-				aot_printerrf (acfg, "Failed to load method 0x%x from '%s' due to %s.\n", token, image->name, mono_error_get_message (error));
-				aot_printerrf (acfg, "Run with MONO_LOG_LEVEL=debug for more information.\n");
-				mono_error_cleanup (error);
-				return FALSE;
-			}
+		}
+
+		if (!is_ok (error) || !method) {
```
Comment (lambdageek) [inline src/mono/mono/mini/aot-compiler.c:13061]: I believe it is the case that we only ever get to this line with `method == NULL` if `should_emit_...` returns TRUE, but it's very hard to figure that out.

what if you had something like:
```c
gboolean warn_and_skip = FALSE;
if (should_emit (...)) {
   mono_error_assert_ok (error);
    method = mini_get_(...);
    
   if (!method || !is_ok (error)) {
       warn_and_skip = TRUE;
    }
} else if (!is_ok (error)) {
   warn_and_skip = TRUE;
}

if (warn_and_skip) {
    aot_printerrf(...);
}
```

**Review by lambdageek — APPROVED** [review]
looks good, but you need to `mono_error_cleanup` the error after the gsharedvt check.  Also a suggestion to make the `should_emit` failure case a bit easier to follow.

**Review by lambdageek — APPROVED** [review]
