### PR TITLE
Change reinterpret_cast use to memcpy

### LINKED ISSUE #2067: Bus error when parsing EventPipeProviderConfiguration
Target platform: **Tizen armel** (32bit ARM processes on 64bit HW)

SIGBUS is raised at the following line if `bufferCursor` points to an unaligned address.

https://github.com/dotnet/runtime/blob/03f8ed5f9eb6fb8f4667f14e0d83a77434dad179/src/coreclr/src/vm/eventpipeprotocolhelper.cpp#L159-L161

```cpp
Thread 7 "dotnet-launcher" received signal SIGBUS, Bus error.
(gdb) bt
#0  EventPipeProtocolHelper::TryParseProviderConfiguration (bufferCursor=@0xf0843aa0: 0xf360bb05 "\377\377\377\377", bufferLen=@0xf0843a9c: 102, result=...)
    at /usr/src/debug/coreclr-3.0.0/src/vm/eventpipeprotocolhelper.cpp:160
#1  0xf5412174 in EventPipeCollectTracing2CommandPayload::TryParse (lpBuffer=0xf360baf8 "", BufferSize=@0xf0843ad2: 115) at /usr/src/debug/coreclr-3.0.0/src/vm/eventpipeprotocolhelper.cpp:70
#2  0xf54127ca in DiagnosticsIpc::IpcMessage::TryParsePayloadImpl<EventPipeCollectTracing2CommandPayload, 0> (this=0xf0843b30) at /usr/src/debug/coreclr-3.0.0/src/vm/diagnosticsprotocol.h:519
#3  DiagnosticsIpc::IpcMessage::TryParsePayload<EventPipeCollectTracing2CommandPayload> (this=0xf0843b30) at /usr/src/debug/coreclr-3.0.0/src/vm/diagnosticsprotocol.h:293
#4  EventPipeProtocolHelper::CollectTracing2 (message=..., pStream=0xf3608bf0) at /usr/src/debug/coreclr-3.0.0/src/vm/eventpipeprotocolhelper.cpp:265
#5  0xf5406bf8 in DiagnosticsServerThread (lpThreadParameter=0xf7a3aa18) at /usr/src/debug/coreclr-3.0.0/src/vm/diagnosticserver.cpp:76
#6  0xf565c726 in CorUnix::CPalThread::ThreadEntry (pvParam=0xf7a3f248) at /usr/src/debug/coreclr-3.0.0/src/pal/src/thread/thread.cpp:1807
#7  0xf7315f04 in start_thread (arg=0xf0844180) at pthread_create.c:335
#8  0xf708c7d8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:86 from /lib/libc.so.6
```

- It tries to parse 8 bytes (`uint64_t`) from `0xf360bb05` (unaligned) but it seems it's not allowed for this platform.
- Reading a 4-byte (`uint32_t`) value is completely okay.
- The cursor points at an odd number address because `TryParseRundownRequested()` increases it by a boolean size.
- To reproduce the error, just run [_dotnet-counters monitor_](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-counters-instructions.md) with default providers. However I couldn't reproduce on non-Tizen armel machine.

/cc @jkotas @alpencolt

### PR DESCRIPTION
**Pull request by josalem**
* prevents unaligned address access on some ARM OSes that fault on that
---
Changes use of `reinterpret_cast` to `memcpy` in EventPipe IPC read/write operations.

resolves #2067 

I'm going to be doing some local tests to convince myself that memory is still being accounted for.  I'll flip the bit on PR status after that.

CC - @tommcdon

### CODE REVIEW

File: src/coreclr/src/vm/diagnosticsprotocol.h [hunk 1]
```diff
@@ -516,8 +530,14 @@ namespace DiagnosticsIpc
...
-            const U* payload = reinterpret_cast<const U*>(m_pData);
-            m_pData = nullptr; // user is expected to clean up buffer when finished with it
+            // don't have std::is_trivially_copyable
+            // static_assert(std::is_trivially_copyable<U>::value, "Can only directly parse trivially copyable types.");
+
+            const U *payload = new (nothrow) U;
+            if (payload == nullptr)
+                return nullptr;
+            memcpy((void *)payload, m_pData, sizeof(U));
+            delete[] m_pData;
```
Comment (lpereira) [inline src/coreclr/src/vm/diagnosticsprotocol.h]: Can `delete[]` be used when paired with a non-array `new`?

Comment (josalem) [reply src/coreclr/src/vm/diagnosticsprotocol.h]: `m_pData` is `new`'d up above using `new (nothrow) BYTE[m_Size]`

File: src/coreclr/src/vm/diagnosticsprotocol.h [hunk 2]
```diff
@@ -24,7 +24,7 @@ bool TryParse(uint8_t *&bufferCursor, uint32_t &bufferLen, T &result)
 
     if (bufferLen < sizeof(T))
         return false;
-    result = *(reinterpret_cast<T *>(bufferCursor));
+    memcpy(&result, bufferCursor, sizeof(T));
```
Comment (lpereira) [inline src/coreclr/src/vm/diagnosticsprotocol.h]: Might consider something like:

```C
template <typename T>
static inline T unaligned_reinterpret_cast(const void* ptr)
{
   T tmp; 
   memcpy(&tmp, ptr, sizeof(T));
   return tmp;
}
```

Then just use it like:

```C
result = unaligned_reinterpret_cast<T>(bufferCursor);
```

At least, for fundamental types such as `int` and `float`, this generates pretty good code that does not involve copies.

File: src/coreclr/src/vm/diagnosticsprotocol.h [hunk 3]
```diff
@@ -47,11 +47,19 @@ bool TryParseString(uint8_t *&bufferCursor, uint32_t &bufferLen, const T *&resul
...
         return false;
-    result = reinterpret_cast<const T *>(bufferCursor);
+
+    T *resultBuffer = new (nothrow) T[stringLen];
+    if (resultBuffer == nullptr)
+        return nullptr; // OOM
 
     const uint32_t TotalStringLength = stringLen * sizeof(T);
+    memcpy(resultBuffer, bufferCursor, TotalStringLength);
+
```
Comment (lpereira) [inline src/coreclr/src/vm/diagnosticsprotocol.h]: Is `resultBuffer` supposed to leak here?

File: src/coreclr/src/vm/diagnosticsprotocol.h (hunk 1 above)
Comment (lpereira) [reply src/coreclr/src/vm/diagnosticsprotocol.h]: Oh, I misread. Thought it was `payload`.

File: src/coreclr/src/vm/diagnosticsprotocol.h (hunk 2 above)
Comment (josalem) [reply src/coreclr/src/vm/diagnosticsprotocol.h]: I'm not sure I see how refactoring that code removes the need for a copy.  `memcpy` happens either way.  Are you suggesting replacing the entirety of `TryParse` with the above code?

Comment (lpereira) [reply src/coreclr/src/vm/diagnosticsprotocol.h]: Oh, I mean, it still calls `memcpy()` (which might not even copy, just load it in a register), but there's no additional copy because it's returning `tmp`.

File: src/coreclr/src/vm/diagnosticsprotocol.h [hunk 4]
```diff
@@ -516,8 +531,14 @@ namespace DiagnosticsIpc
...
-            const U* payload = reinterpret_cast<const U*>(m_pData);
-            m_pData = nullptr; // user is expected to clean up buffer when finished with it
+            // don't have std::is_trivially_copyable
+            // static_assert(std::is_trivially_copyable<U>::value, "Can only directly parse trivially copyable types.");
+
+            const U *payload = new (nothrow) U;
+            if (payload == nullptr)
+                return nullptr;
+            memcpy((void *)payload, m_pData, sizeof(U));
+            delete[] m_pData;
```
Comment (noahfalk) [inline src/coreclr/src/vm/diagnosticsprotocol.h]: m_pData is also deleted in the destructor, this looks like it would double free?

File: src/coreclr/src/vm/diagnosticsprotocol.h [hunk 5]
```diff
@@ -47,11 +47,20 @@ bool TryParseString(uint8_t *&bufferCursor, uint32_t &bufferLen, const T *&resul
...
         return false;
-    if ((reinterpret_cast<const T *>(bufferCursor))[stringLen - 1] != 0)
+
+    T terminator;
+    memcpy(&terminator, bufferCursor + stringLen - 1, sizeof(T));
+    if (terminator != 0)
         return false;
-    result = reinterpret_cast<const T *>(bufferCursor);
+
+    T *resultBuffer = new (nothrow) T[stringLen];
```
[the remark this answers is not in the document]
Comment (josalem) [reply src/coreclr/src/vm/diagnosticsprotocol.h]: I just updated the code so that strings are held in `NewHolder|NewArrayHolder`s so they should get deleted correctly.  I'm going to see about running Valgrind over it to make sure.

File: src/coreclr/src/vm/diagnosticsprotocol.h (hunk 4 above)
Comment (josalem) [reply src/coreclr/src/vm/diagnosticsprotocol.h]: Yup!  I caught that one 😄

File: src/coreclr/src/vm/diagnosticsprotocol.h (hunk 2 above)
Comment (swift-kim) [inline src/coreclr/src/vm/diagnosticsprotocol.h]: Testing with this single line change, it just worked in my case.

File: src/coreclr/src/vm/eventpipeprotocolhelper.h [hunk 6]
```diff
@@ -43,14 +41,17 @@ struct EventPipeCollectTracing2CommandPayload
     bool rundownRequested;
     CQuickArray<EventPipeProviderConfiguration> providerConfigs;
     static const EventPipeCollectTracing2CommandPayload* TryParse(BYTE* lpBuffer, uint16_t& BufferSize);
+
+    ~EventPipeCollectTracing2CommandPayload()
+    {
+        providerConfigs.Destroy();
```
Comment (jkotas) [inline src/coreclr/src/vm/eventpipeprotocolhelper.h]: Is this necessary? CQuickArray has destructor that should take care of it.

File: src/coreclr/src/vm/eventpipeprotocolhelper.h [hunk 7]
```diff
@@ -63,6 +64,11 @@ struct EventPipeCollectTracingCommandPayload
     EventPipeSerializationFormat serializationFormat;
     CQuickArray<EventPipeProviderConfiguration> providerConfigs;
     static const EventPipeCollectTracingCommandPayload* TryParse(BYTE* lpBuffer, uint16_t& BufferSize);
+
+    ~EventPipeCollectTracingCommandPayload()
+    {
+        providerConfigs.Destroy();
```
Comment (jkotas) [inline src/coreclr/src/vm/eventpipeprotocolhelper.h]: Dtto

File: src/coreclr/src/vm/dumpdiagnosticprotocolhelper.cpp [hunk 8]
```diff
@@ -55,17 +55,19 @@ const GenerateCoreDumpCommandPayload* GenerateCoreDumpCommandPayload::TryParse(B
         return nullptr;
     }
 
-    payload->incomingBuffer = lpBuffer;
-    uint8_t* pBufferCursor = payload->incomingBuffer;
+    uint8_t* pBufferCursor = lpBuffer;
```
Comment (jkotas) [inline src/coreclr/src/vm/dumpdiagnosticprotocolhelper.cpp]: Does `GenerateCoreDumpCommandPayload*` above need to be `NewArrayHolder` now?

Comment (josalem) [reply src/coreclr/src/vm/dumpdiagnosticprotocolhelper.cpp]: The user is expected to handle the memory `new`'d here.  Down on line 88, the `GenerateCoreDumpPayload` is put into a `NewHolder`.

File: src/coreclr/src/vm/eventpipeprotocolhelper.h (hunk 6 above)
Comment (josalem) [reply src/coreclr/src/vm/eventpipeprotocolhelper.h]: You're correct.  I somehow missed the constructor when I was looking at the class.

File: src/coreclr/src/vm/dumpdiagnosticprotocolhelper.cpp (hunk 8 above)
Comment (janvorli) [reply src/coreclr/src/vm/dumpdiagnosticprotocolhelper.cpp]: It is a good practice to assign a newly allocated memory to a holder immediately. That way, you would not need to delete it at line 65 and it is also future proof when someone might add another return path to this function. The final return in this function would then use payload->Extract() or just call SuppressRelease() before the return.

**Comment by josalem** [comment]
After some discussion with @noahfalk last week, I'm going top scale back the scope of this PR to just the line that @swift-kim said solved their issue.  This is minimally invasive and solves the issue.  Once the PR is scaled back, I'll mark the PR as ready for review.

**Comment by swift-kim** [comment]
@josalem Is there any news?

**Comment by josalem** [comment]
> @josalem Is there any news?

@swift-kim I was offline last week, but I should be able to modify the PR this week to only include the line that fixes your issue and mark the PR for review.

**Review by noahfalk — APPROVED** [review]

**Review by sywhang — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]
