### PR TITLE
[Mono] Look for Native Signal SIMD Context

### LINKED ISSUE #62201: [android] arm64 running on x64 emulator unexpected FPSIMD_MAGIC assert
Recent versions (API 30 x86_64) of the Android emultator can run arm64 binaries on an x86_64 emultator using some kind of binary translation.  When an app is running in this environment, it looks like the `struct sigcontext` `__reserved` field is not laid out with the `fpsimd_context` first.

As a result this code asserts:

https://github.com/dotnet/runtime/blob/b1b7ad47e2d0bef37fa2fb3b1075cdeabf561c04/src/mono/mono/utils/mono-context.c#L536-L539

[Linux kernel `sigcontext` `__reserved` note](https://elixir.bootlin.com/linux/latest/source/arch/arm64/include/uapi/asm/sigcontext.h#L40)

Instead of looking at the first context in `__reserved` and asserting that it has `FPSIMD_MAGIC`, we should check `head.magic == FPSIMD_MAGIC` and if not, move forward by `head.size` bytes and try again until we see `head.magic == 0` (the last block).

Potentially we can assume that the offset won't change between calls to `mono_sigctx_to_monoctx` and cache the pre-computed offset (and assert that the magic is the right one).

---

Reproduction steps for XA:

1. Turn off fast deployment by adding `<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>` to the csproj file
2. Remove definition for `$(AndroidSupportedAbis)` if there is any in the .csproj file
3. Add `<RuntimeIdentifiers>android-arm;android-arm64</RuntimeIdentifiers>` to the csproj file
4. Build and run the app in Release mode on x86_64 emulator crashes using `dotnet build -c Release -t:Run`

### PR DESCRIPTION
**Pull request by fanyang-mono**
This PR add the logic to find the native signal SIMD context, instead of assuming the first one in the array is the one. If not found, it is okay to proceed from the first context as well.

Somehow, when running android arm64 apps on x64 emulators, the SIMD context doesn't exist.

Testing: Followed the reproduction steps provided by the customer using VS 2022 (https://github.com/dotnet/runtime/issues/62201#issuecomment-1645169782)

Fixes #62201

### CODE REVIEW

File: src/mono/mono/utils/mono-context.c [hunk 1]
```diff
@@ -534,10 +534,28 @@ mono_sigctx_to_monoctx (void *sigctx, MonoContext *mctx)
 #endif
 #ifdef __linux__
 	struct fpsimd_context *fpctx = (struct fpsimd_context*)&((ucontext_t*)sigctx)->uc_mcontext.__reserved;
-	int i;
 
-	g_assert (fpctx->head.magic == FPSIMD_MAGIC);
-	for (i = 0; i < 32; ++i)
+	size_t size = 0;
+    do
```
Comment (vargaz) [inline src/mono/mono/utils/mono-context.c:539]: This should use mono coding conventions.

**Review by vargaz — APPROVED** [review]

File: src/mono/mono/utils/mono-context.c (hunk 1 above)
Comment (fanyang-mono) [reply src/mono/mono/utils/mono-context.c]: Fixed.

File: src/mono/mono/utils/mono-context.c [hunk 2]
```diff
@@ -534,10 +534,27 @@ mono_sigctx_to_monoctx (void *sigctx, MonoContext *mctx)
...
+			break;
+		}
+
+		if (fpctx_temp->head.size == 0)
+			break;
+
+		size += fpctx_temp->head.size;
+	} while (size + sizeof (struct fpsimd_context) <= sizeof (((ucontext_t*)sigctx)->uc_mcontext.__reserved));
+
+	for (int i = 0; i < 32; ++i)
```
Comment (lambdageek) [inline src/mono/mono/utils/mono-context.c:557]: @fanyang-mono if we don't find the FPSIMD_MAGIC, we just write into `mctx->fregs[i] = fpctx->vregs [i]` - while `fpctx` is just pointing to the beginning of `__reserved`?  So we fill it with junk.  That seems a little fragile.  Can we write 0's into `fregs` if we don't find `FPSIMD_MAGIC`?

I think you said in the "arm64 app on x64 Android emultator" scenario we don't see any FPSIMD_MAGIC at all, right? so we should definitely handle that case in a reasonable way instead of just copying some random values into the MonoContext.

**Review by lambdageek — CHANGES_REQUESTED** [review]

File: src/mono/mono/utils/mono-context.c (hunk 2 above)
Comment (fanyang-mono) [reply src/mono/mono/utils/mono-context.c:557]: Oh, yeah. That makes sense.

**Review by lambdageek — APPROVED** [review]

**Comment by fanyang-mono** [comment]
Test failures on CI are unrelated.
