### PR TITLE
Test issue for reference tracking in Objective-C

### LINKED ISSUE #53359: Test failure Interop/ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.sh
This test failed in a current GCStress0x3 run:

https://dev.azure.com/dnceng/public/_build/results?buildId=1158649&view=ms.vss-test-web.build-test-results-tab&runId=34974862&resultId=101901&paneView=debug

```
Return code:      1
Raw output file:      /private/tmp/helix/working/B3D10A12/w/A55408C1/e/Interop/ObjectiveC/Reports/Interop.ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/B3D10A12/p/corerun ObjectiveCMarshalAPI.dll ''
Running Validate_ReferenceTrackingAPIs_InvalidArgs...
Running Validate_ReferenceTracking_Scenario...
Test Failure: TestLibrary.AssertTestException: Assert.AreEqual: Expected: [2]. Actual: [4].
at TestLibrary.Assert.HandleFail(String assertionName, String message) in TestLibrary.dll:token 0x6000021+0x11
at TestLibrary.Assert.AreEqual[T](T expected, T actual, String message) in TestLibrary.dll:token 0x6000010+0x3d
at ObjectiveCMarshalAPI.Program.Validate_ReferenceTracking_Scenario() in ObjectiveCMarshalAPI.dll:token 0x600000d+0xbe
at ObjectiveCMarshalAPI.Program.Main(String[] doNotUse) in ObjectiveCMarshalAPI.dll:token 0x6000015+0x0
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/B3D10A12/p
/private/tmp/helix/working/B3D10A12/w/A55408C1/e/Interop/ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.sh
Expected: True
Actual:   False
```

See https://github.com/dotnet/runtime/issues/52829

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #53359

Reenable test from https://github.com/dotnet/runtime/pull/54532

/cc @jkoritzinsky @elinor-fung

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

File: src/tests/Interop/ObjectiveC/ObjectiveCMarshalAPI/NativeObjCMarshalTests.cpp [hunk 1]
```diff
@@ -47,20 +47,18 @@ namespace
...
-
         if (cxt->RefCountDown == 0)
         {
             // No more references
             return 0;
         }
         else
         {
+            cxt->RefCountDown--;
+            cxt->RefCountUp++;
```
Comment (elinor-fung) [inline src/tests/Interop/ObjectiveC/ObjectiveCMarshalAPI/NativeObjCMarshalTests.cpp:61]: The callback is going to return that there's no references one call later than before - this is fine because we always explicitly trigger the GC more than the initial count, right? And the test relies on the initial count being at least one less than the number of times we explicitly trigger the GC (otherwise it will be unreliable)?
https://github.com/dotnet/runtime/blob/1f3d36a323c9efb5e9a0f1f539332cc745c90c21/src/tests/Interop/ObjectiveC/ObjectiveCMarshalAPI/Program.cs#L152
https://github.com/dotnet/runtime/blob/1f3d36a323c9efb5e9a0f1f539332cc745c90c21/src/tests/Interop/ObjectiveC/ObjectiveCMarshalAPI/Program.cs#L208
If so, could we add some sort of comment or make const variable to make it clear those are connected for the test to be reliable?

**Review by elinor-fung — APPROVED** [review]

File: src/tests/Interop/ObjectiveC/ObjectiveCMarshalAPI/NativeObjCMarshalTests.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/tests/Interop/ObjectiveC/ObjectiveCMarshalAPI/NativeObjCMarshalTests.cpp:61]: Sure. I will add a comment.

**Review by elinor-fung — APPROVED** [review]
