### PR TITLE
Single-file apps should not use copy-on-write mapping of the .exe on windows.

### LINKED ISSUE #55405: App published as single file fails to run in Windows 10.0.17763 containers
### Description

Attempting to run the Hello World console app, that was published as a single file deployment, in a Windows 10.0.17763 container will fail with an error message similar to the following:

```
Failed to map file. CreateFileMappingW(C:\app\app.exe) failed with error 5
Failure processing application bundle.
Failed to map bundle file [C:\app\app.runtimeconfig.json]
```

This behavior applies to both 5.0 and 6.0. It works in .NET Core 2.1 and 3.1. And it only occurs when targeting a Windows 10.0.17763 container (this version maps to Windows 10 version 1809 and Windows Server 2019). Targeting newer or older versions of Windows containers also works. I've attempted to repro this outside of a container environment, just on a Windows Server 2019 machine directly and it worked fine. Things also work fine if you attempt to run an app that was published _without_ the single file option so the failure is specific to that option.

### Repro

On a machine with Docker installed and targeting Windows containers:

1. Create a new empty directory
2. Add a file named `Dockerfile` with the following content:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

RUN dotnet new console

RUN dotnet publish -c release -o /out -r win-x64 /p:PublishSingleFile=true

FROM mcr.microsoft.com/windows/nanoserver:1809
WORKDIR /app
COPY --from=build /out .

ENTRYPOINT ["app"]
```

3. `docker build -t app .`
4. `docker run --rm app`

### Configuration

The environment I'm running:
* Windows 10, version 21H1
* Docker
```
❯ docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           desktop-windows
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:41 2021
  OS/Arch:          windows/amd64
  Experimental:     true
```

### Regression?

This works in .NET Core 2.1 and 3.1.  It started failing with 5.0.100.

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: https://github.com/dotnet/runtime/issues/55405     (App published as single file fails to run in Windows 10.0.17763 containers)

## Customer Impact

Regression from  .NET Core 2.1 and 3.1 causing failure when a single-file app runs in a Windows 10.0.17763 container. 

```
Failed to map file. CreateFileMappingW(C:\app\app.exe) failed with error 5
Failure processing application bundle.
Failed to map bundle file [C:\app\app.runtimeconfig.json]
```
(This is a relatively old 2018 RS5 build, but it is an LTS so it will be around for a while)

## Testing

Manually verified in an actual container. Regular Unit tests.

## Risk

Very low. 

We do not benefit from copy-on-write part of the mapping on Windows since we do not do in-situ json parsing due to UTF8/UTF16 differences. We basically request COW for consistency with Unix. Somehow it triggers unexpected "access denied" failure for superhost-style single-file apps on this particular build/container. 

Since we do not do in-situ parsing on Windows, a read-only mapping is sufficient and we should request just what we need.

### CODE REVIEW

**Comment by agocke** [comment]
Is it confirmed that this fixes the problem?

**Comment by VSadov** [comment]
@agocke 
> Is it confirmed that this fixes the problem?

At this moment I think it is a very likely reason for the failure. It is also a case where we ask for extra permissions from the OS while we do not need them. It may make sense to make this change regardless.

I have not confirmed yet whether it actually fixes the issue and whether this is the only reason for the failure. (otherwise it would not need to be in 6.0)  - Just need to figure how to get locally compiled app into the same container as in the repro and run it. There should be a way.

**Comment by VSadov** [comment]
The repro turned out even more bizarre than reported. - The reported error is observed only on the _first_ execution of the app. If the app is launched again in the same container instance, it runs fine, although "please run the app twice" does not look like a a reasonable workaround, so it is still looks bad.

I.E:
```
Microsoft Windows [Version 10.0.17763.2114]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\app>app.exe
Failed to map file. CreateFileMappingW(C:\app\app.exe) failed with error 5
Failure processing application bundle.
Failed to map bundle file [C:\app\app.runtimeconfig.json]

C:\app>app.exe
Hello, World!

C:\app>
```


Anyways, I did confirm that with this fix the strange behavior is not triggered and the app runs fine on the first run (and subsequent runs too :).

After the fix:

```
Microsoft Windows [Version 10.0.17763.2114]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\app>app.exe
Hello, World!

C:\app>app.exe
Hello, World!

C:\app>app.exe
Hello, World!

C:\app>app.exe
Hello, World!

C:\app>app.exe
Hello, World!

C:\app>
```

**Review by agocke — APPROVED** [review]
LGTM

File: src/native/corehost/bundle/info.cpp [hunk 1]
```diff
@@ -108,7 +108,14 @@ char* info_t::config_t::map(const pal::string_t& path, const location_t* &locati
     // * There is no performance limitation due to a larger sized mapping, since we actually only read the pages with relevant contents.
     // * Files that are too large to be mapped (ex: that exhaust 32-bit virtual address space) are not supported. 
 
+#ifdef _WIN32
+    // Since we can't use in-situ parsing on Windows, as JSON data is encoded in
+    // UTF-8 and the host expects wide strings.
```
Comment (am11) [inline src/native/corehost/bundle/info.cpp:113]: Is this part of the comment related to the code below on line 115 or above line 88?

**Review by vitek-karas — APPROVED** [review]

File: src/native/corehost/bundle/info.cpp (hunk 1 above)
Comment (agocke) [reply src/native/corehost/bundle/info.cpp:113]: This is about 115 -- the RapidJson parser used in `json_parser.cpp` modifies the buffer on Linux, but not on Windows, so the CoW permissions are not useful on Windows.

**Comment by VSadov** [comment]
Thanks!!
