### PR TITLE
fix InstanceDataCollectionCollection_CopyTo by retrying on 0 values

### LINKED ISSUE #68291: System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_CopyTo failing in CI
Configuration: `net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open`

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1721549

```
    System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_CopyTo [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs(122,0): at System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_CopyTo()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs(379,0): at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)

Informaci�n: Los contadores de rendimiento se instalaron correctamente en C:\h\w\B1040971\t\h2gyudok.4kw\provider.man.    System.Diagnostics.Tests.PerformanceDataTests.PerformanceCounter_PerformanceData [SKIP]
      Condition(s) not met: "IsRunnableEnvironment"

Informaci�n: Desinstalaci�n correcta de los contadores de rendimiento del archivo XML de definici�n de contadores C:\h\w\B1040971\t\h2gyudok.4kw\provider.man.  Finished:    System.Diagnostics.PerformanceCounter.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.PerformanceCounter.Tests  Total: 90, Errors: 0, Failed: 1, Skipped: 1, Time: 30,024s
```
<!-- runfo report start -->
Runfo Tracking Issue: [system.diagnostics.tests.instancedatatests.instancedatacollectioncollection_copyto](https://runfo.azurewebsites.net/tracking/issue/327)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1799703](https://dev.azure.com/dnceng/public/_build/results?buildId=1799703)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 70062](https://github.com/dotnet/runtime/pull/70062)|net7.0-windows-Release-x64-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-70062-merge-c36dcb1ecf1a443aa9/System.Diagnostics.PerformanceCounter.Tests/1/console.2630913f.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-70062-merge-c36dcb1ecf1a443aa9/System.Diagnostics.PerformanceCounter.Tests/a4c9d949-92bb-44c8-b465-dcf68f173bf9.log?%3F%253Fhelixlogtype%253Dresult)|
|[1757267](https://dev.azure.com/dnceng/public/_build/results?buildId=1757267)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 68993](https://github.com/dotnet/runtime/pull/68993)|net7.0-windows-Debug-x64-CoreCLR_release-Windows.11.Amd64.ClientPre.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68993-merge-3d16df5378484e3e8b/System.Diagnostics.PerformanceCounter.Tests/1/console.b7c90cbb.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68993-merge-3d16df5378484e3e8b/System.Diagnostics.PerformanceCounter.Tests/d7ba7845-43d3-4db1-9d9c-e7511cffc130.log?%3F%253Fhelixlogtype%253Dresult)|
|[1744574](https://dev.azure.com/dnceng/public/_build/results?buildId=1744574)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.ClientPre.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-preview48b9a52f6c21f4cd4b2/System.Diagnostics.PerformanceCounter.Tests/1/console.65baaa23.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-preview48b9a52f6c21f4cd4b2/System.Diagnostics.PerformanceCounter.Tests/60224bb2-9a3d-49a0-89c0-2f8550efd8e4.log?%3F%253Fhelixlogtype%253Dresult)|
|[1725393](https://dev.azure.com/dnceng/public/_build/results?buildId=1725393)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 67883](https://github.com/dotnet/runtime/pull/67883)|net48-windows-Release-x86-Windows.10.Amd64.Client21H1.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67883-merge-2b47ce30e286441db7/System.Diagnostics.PerformanceCounter.Tests/1/console.a0c9b49a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-09T04%25253A31%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D%25252BdAfvHpgk%25252BJckuGBeMCgH9%25252BguHskyy0BnOBR1YYVsYo%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67883-merge-2b47ce30e286441db7/System.Diagnostics.PerformanceCounter.Tests/e4dcfd02-62bb-416f-98ae-ef92c55c1c96.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-09T04%25253A31%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D%25252BdAfvHpgk%25252BJckuGBeMCgH9%25252BguHskyy0BnOBR1YYVsYo%25253D)|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|1|2|

<!-- runfo report end -->

### PR DESCRIPTION
**Pull request by smasher164**
Previously, when pcc.ReadCategory() returned 0 values, we did not retry,
which broke the test that asserted its length > 0. This time, we retry
when there are 0 values, by triggering the RetryHelper's exception
handler.

Fixes #68291

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
Thank you. LGTM

File: src/libraries/System.Diagnostics.PerformanceCounter/tests/ZeroDataException.cs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace System.Diagnostics.Tests
```
Comment (danmoseley) [inline src/libraries/System.Diagnostics.PerformanceCounter/tests/ZeroDataException.cs:4]: I don't think it's worth creating a new exception type for this. Especially because any exception type will have exactly the same  effect. 

Just `Assert.InRange(idcc.Values.Count, 1, int.MaxValue);` should do it. It will throw an XunitException.

File: src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs [hunk 2]
```diff
@@ -124,8 +124,16 @@ public static void InstanceDataCollectionCollection_CopyTo()
...
         {
-            PerformanceCounterCategory pcc =  Helpers.RetryOnAllPlatforms(() => new PerformanceCounterCategory("Processor"));
-            return Helpers.RetryOnAllPlatforms(() => pcc.ReadCategory());
+            PerformanceCounterCategory pcc = Helpers.RetryOnAllPlatforms(() => new PerformanceCounterCategory("Processor"));
+            return Helpers.RetryOnAllPlatforms(() =>
+            {
+                var idcc = pcc.ReadCategory();
+                if (idcc.Values.Count == 0)
+                {
+                    Assert.InRange(idcc.Values.Count, 1, int.MaxValue);
```
Comment (ViktorHofer) [inline src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs:133]: Unsure if I understand the actual issue but can't you just `throw new Exception();` to cause a retry?

**Review by danmoseley — APPROVED** [review]

File: src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs (hunk 2 above)
Comment (danmoseley) [reply src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs]: It's also a little more self documenting to assert rather than simply throw

**Comment by danmoseley** [comment]
thanks!

**Comment by danmoseley** [comment]
Do we need the same fix at https://github.com/dotnet/runtime/blob/1601356c968d83359e1e46a7dd3680d1cc99205e/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs#L299 ?

Does this fix #60933 as well? 

BTW, perf counter tests have had other random failures (eg https://github.com/dotnet/runtime/issues/60933#issuecomment-957826632) .. I'm not clear what is left after fixing ReadCategory(). in such cases it can be interesting to data dive into test history to see what failure modes there were. this can either be done with [runfo](https://runfo.azurewebsites.net/) or against the raw tables with Kusto. If at some point you're interested in learning how to get to this data, you can ask folks such as @ViktorHofer to show you how to use runfo, or I'd be happy to show you Kusto. either work.
