### PR TITLE
Fix missing case for function pointer signatures in Crossgen2

### LINKED ISSUE #72822: Test failure JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd
Run: [runtime-coreclr outerloop 20220725.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481962&resultId=103627&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux arm64 Checked @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux x64 Checked @ Ubuntu.1804.Amd64.Open

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 OSX x64 Checked @ OSX.1200.Amd64.Open

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1200.Amd64.Open

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh
```

**Error message:**
```
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
at ILCompiler.DependencyAnalysis.ReadyToRun.SignatureBuilder.EmitTypeSignature(TypeDesc typeDesc, SignatureContext context) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:line 329
at ILCompiler.DependencyAnalysis.ReadyToRun.NewArrayFixupSignature.GetData(NodeFactory factory, Boolean relocsOnly) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/NewArrayFixupSignature.cs:line 35
at ILCompiler.DependencyAnalysis.ReadyToRun.ImportSectionNode.MaterializeSignature(NodeFactory r2rFactory) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionNode.cs:line 61
at ILCompiler.DependencyAnalysis.ReadyToRun.ImportSectionsTableNode.MaterializeSignature() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionsTableNode.cs:line 27
at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestMetadataTableNode.ComputeLastSetOfModuleIndices() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ManifestMetadataTableNode.cs:line 277
at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestMetadataTableNode.GetManifestAssemblyMvidTableData() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ManifestMetadataTableNode.cs:line 324
at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestAssemblyMvidHeaderNode.GetData(NodeFactory factory, Boolean relocsOnly) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ManifestAssemblyMvidHeaderNode.cs:line 58
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:line 256
at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 354
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 882
at ILCompiler.Program.Run(String[] args) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 583
at ILCompiler.Program.Main(String[] args) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 1159

Return code:      1
Raw output file:      D:\h\w\A58708E6\w\B03A09BA\uploads\Reports\JIT.opt\ValueNumbering\TypeTestFolding\TypeTestFolding.output.txt
Raw output:
BEGIN EXECUTION
TypeTestFolding.dll
1 file(s) copied.
15:21:46.60
Response file: D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.dll.rsp
D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\IL-CG2\TypeTestFolding.dll
-o:D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A58708E6\p\System..dll
-r:D:\h\w\A58708E6\p\Microsoft..dll
-r:D:\h\w\A58708E6\p\mscorlib.dll
-r:D:\h\w\A58708E6\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A58708E6\p\crossgen2\crossgen2.dll" @"D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.dll.rsp"   -r:D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.dll
15:21:55.44
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\A58708E6\p
D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.cmd
Expe


Stack trace
   at JIT_opt._ValueNumbering_TypeTestFolding_TypeTestFolding_._ValueNumbering_TypeTestFolding_TypeTestFolding_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by trylek**
As Andy Ayers conjectured in the issue #72822 and I confirmed,
Crossgen2 signature emitter was missing the code path for
emitting function pointer signatures. This change fixes this
deficiency. The change also removes the issues.targets exclusion
of the affected test that Andy originally merged in to mitigate
the issue.

Thanks

Tomas

P.S. Even though MethodSignatureFlags more or less corresponds
to CoreCLR runtime calling convention, I have ignored this fact
and implemented an explicit conversion as I find it cleaner, please
let me know if you think otherwise. I would also appreciate
double-checking of the logic around Static vs. HASTHIS as I'm not
completely sure about the exact interpretation of this runtime flag.

/cc @dotnet/crossgen-contrib 

Fixes: https://github.com/dotnet/runtime/issues/72822

### CODE REVIEW

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs [hunk 1]
```diff
@@ -366,6 +370,35 @@ private void EmitPointerTypeSignature(PointerType type, SignatureContext context
...
+                MethodSignatureFlags.CallingConventionVarargs => CorCallingConvention.IMAGE_CEE_CS_CALLCONV_VARARG,
+                MethodSignatureFlags.UnmanagedCallingConvention => CorCallingConvention.IMAGE_CEE_CS_CALLCONV_UNMANAGED,
+                _ => throw new NotSupportedException()
+            };
+
+            if ((type.Signature.Flags & MethodSignatureFlags.Static) == 0)
+            {
+                callingConvention |= CorCallingConvention.IMAGE_CEE_CS_CALLCONV_HASTHIS | CorCallingConvention.IMAGE_CEE_CS_CALLCONV_EXPLICITTHIS;
+            }
+
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:390]: Does this need to emit modops / modreqs, or are those intentionally skipped here?

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs [hunk 2]
```diff
@@ -366,6 +370,35 @@ private void EmitPointerTypeSignature(PointerType type, SignatureContext context
...
+                MethodSignatureFlags.UnmanagedCallingConventionStdCall => CorCallingConvention.IMAGE_CEE_CS_CALLCONV_STDCALL,
+                MethodSignatureFlags.UnmanagedCallingConventionThisCall => CorCallingConvention.IMAGE_CEE_CS_CALLCONV_THISCALL,
+                MethodSignatureFlags.CallingConventionVarargs => CorCallingConvention.IMAGE_CEE_CS_CALLCONV_VARARG,
+                MethodSignatureFlags.UnmanagedCallingConvention => CorCallingConvention.IMAGE_CEE_CS_CALLCONV_UNMANAGED,
+                _ => throw new NotSupportedException()
+            };
+
+            if ((type.Signature.Flags & MethodSignatureFlags.Static) == 0)
+            {
+                callingConvention |= CorCallingConvention.IMAGE_CEE_CS_CALLCONV_HASTHIS | CorCallingConvention.IMAGE_CEE_CS_CALLCONV_EXPLICITTHIS;
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:388]: Is `IMAGE_CEE_CS_CALLCONV_EXPLICITTHIS` right here?

Comment (trylek) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:388]: Hmm, that's exactly what I'm trying to get my head around. I believe that ECMA managed method signatures do include the <code>this</code> pointer so I would assume it's explicit but I may be misunderstanding the purpose of the flag, it's not used very broadly in the CoreCLR native runtime.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs (hunk 1 above)
Comment (trylek) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:390]: Well, we probably do, I'll try to fix this but the problem is that apparently there's no pre-existing coverage for function pointer signatures in CoreCLR testing so I guess I'll need to create some dedicated tests to verify this works as expected especially as this is the first place in Crossgen2 where we'll be emitting these signature modifiers.

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:390]: Actually - if we are ever only going to use signature to create type handle at runtime, we should not need to emit the modopts/modreqs. They are not part of the type handle at runtime.

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:390]: Also, the function pointer support in reflection is broken and inconsistent in various ways today. We hope to fix that as part of https://github.com/dotnet/runtime/issues/69273 in .NET 8.

Comment (trylek) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:390]: That's exactly why I asked for a broad review, this is obviously new functionality with very limited test coverage (amounting to the one JIT test I'm re-enabling in this PR).

File: src/coreclr/tools/Common/Internal/Runtime/CorConstants.cs [hunk 3]
```diff
@@ -95,4 +95,36 @@ public enum CorTokenType
         mdtName = 0x71000000,
         mdtBaseType = 0x72000000,
     }
+
+    [Flags]
+    public enum CorUnmanagedCallingConvention
```
Comment (jkotas) [inline src/coreclr/tools/Common/Internal/Runtime/CorConstants.cs:100]: These constants are defined by System.Reflection.Metadata as `SignatureCallingConvention` and `SignatureAttributes`. We can just use those definitions instead of having yet another copy.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs (hunk 2 above)
Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:388]: The MethodSignature initialization only uses `HasThis` to initialize the `Static` bit:

https://github.com/dotnet/runtime/blob/83bd401b112f2deb0db516300f72eb9d1579751d/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs#L399-L400

so the reverse should do the same.

If we need to preserve HasExplicitThis too (I do not think we need to), we would need to store it in MethodSignature.

**Comment by jkotas** [comment]
>  I have ignored this fact
and implemented an explicit conversion as I find it cleaner,

FWIW, the type system takes the casting shortcut:

https://github.com/dotnet/runtime/blob/83bd401b112f2deb0db516300f72eb9d1579751d/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs#L389-L394

File: src/coreclr/tools/Common/Internal/Runtime/CorConstants.cs (hunk 3 above)
Comment (trylek) [reply src/coreclr/tools/Common/Internal/Runtime/CorConstants.cs]: Thanks Jan for pointing that out, I have reverted the additions to CorConstants and modified the code to reuse the pre-existing constants.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs (hunk 2 above)
Comment (trylek) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs]: Based on your clarification I have removed the <code>ExplicitThis</code> flag when emitting the non-static function pointer signatures.

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs]: I am still not sure about the ExplicitThis. I think we should probably store it on MethodSignature when we are initializing it from Ecma metadata, store it here; and also send it to the JIT so that the JIT can do the right thing with it.

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs]: We have number of IL tests that exercise explicit this (look for "explicit instance" in *.il under tests). I am surprised that none of them fails.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs (hunk 1 above)
Comment (davidwrighton) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:377]: We have logic to handle emission of modopts/modreqs, but that should only be needed for function signatures, and those are already handled correctly so far as I'm aware. For this support I do not believe we need to handle modreqs/modopts at all, ever.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs (hunk 2 above)
Comment (davidwrighton) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs]: Ack, yes, we should handle explicitthis, although fixing all the places that work with that may be beyond the scope of what we should try to fix with this PR. I think it will likely be a fairly large fix to a bunch of places unrelated to the general thrust of the code written here.

**Review by davidwrighton — APPROVED** [review]
I believe we should probably fix the explicit this problem, but I'd like to see such a fix done as part of fixing explicit this throughout our product, not just in this situation.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs (hunk 2 above)
Comment (trylek) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs]: I have created a .NET 8 tracking issue for this task, https://github.com/dotnet/runtime/issues/73407.
