### PR TITLE
Do not fold mismatched `OBJ(ADDR(LCL_VAR))`

### LINKED ISSUE #69232: Test failure JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_r\\NotSupported_r.cmd
Run: [runtime-coreclr outerloop 20220511.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1766348&view=ms.vss-test-web.build-test-results-tab&runId=47509898&paneView=debug&resultId=100077)

Failed test:
```
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_r\\NotSupported_r.cmd
- JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_ro\\NotSupported_ro.cmd

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_r/NotSupported_r.sh
- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_ro/NotSupported_ro.sh

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_ro/NotSupported_ro.sh
- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_r/NotSupported_r.sh

coreclr windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_r\\NotSupported_r.cmd
- JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_ro\\NotSupported_ro.cmd

coreclr Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_r/NotSupported_r.sh
- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_ro/NotSupported_ro.sh

coreclr Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_r/NotSupported_r.sh
- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_ro/NotSupported_ro.sh

coreclr OSX arm64 Checked no_tiered_compilation @ OSX.1200.ARM64.Open

- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_r/NotSupported_r.sh
- JIT/HardwareIntrinsics/General/NotSupported/NotSupported_ro/NotSupported_ro.sh
```
**Error message:**
```
Assert failure(PID 11196 [0x00002bbc], Thread: 11888 [0x2e70]): Assertion failed 'effectiveVal->TypeIs(asgType) || (varTypeIsSIMD(asgType) && varTypeIsStruct(effectiveVal))' in 'System.Runtime.Intrinsics.Vector1281[Boolean][System.Boolean]:get_AllBitsSet():System.Runtime.Intrinsics.Vector1281[Boolean]' during 'Morph - Global' (IL size 17; hash 0xf5a638eb; FullOpts)

File: D:\a\_work\1\s\src\coreclr\jit\morph.cpp Line: 9867
Image: D:\h\w\BF810A31\p\corerun.exe
Return code:      1
Raw output file:      D:\h\w\BF810A31\w\BA0B096E\uploads\Reports\JIT.HardwareIntrinsics\General\NotSupported\NotSupported_r\NotSupported_r.output.txt
Raw output:
BEGIN EXECUTION
NotSupported_r.dll
TestLibrary.dll
2 file(s) copied.
21:06:47.42
Response file: D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\NotSupported_r.dll.rsp
D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\IL-CG2\NotSupported_r.dll
-o:D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\NotSupported_r.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\BF810A31\p\System..dll
-r:D:\h\w\BF810A31\p\Microsoft..dll
-r:D:\h\w\BF810A31\p\mscorlib.dll
-r:D:\h\w\BF810A31\p\netstandard.dll
-O
" "dotnet" "D:\h\w\BF810A31\p\crossgen2\crossgen2.dll" @"D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\NotSupported_r.dll.rsp"   -r:D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\NotSupported_r.dll
21:06:49.81
21:06:49.81
Response file: D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\TestLibrary.dll.rsp
D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\IL-CG2\TestLibrary.dll
-o:D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\TestLibrary.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\BF810A31\p\System..dll
-r:D:\h\w\BF810A31\p\Microsoft..dll
-r:D:\h\w\BF810A31\p\mscorlib.dll
-r:D:\h\w\BF810A31\p\netstandard.dll
-O
" "dotnet" "D:\h\w\BF810A31\p\crossgen2\crossgen2.dll" @"D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\TestLibrary.dll.rsp"   -r:D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\BF810A31\w\BA0B096E\e\JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\TestLibrary.dll
21:06:52.12
"D:\h\w\BF810A31\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  NotSupported_r.dll
Beginning test case Vector64BooleanZero at 5/11/2022 9:06:52 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 5/11/2022 9:06:52 PM
Beginning test case Vector64BooleanAllBitsSet at 5/11/2022 9:06:52 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 5/11/2022 9:06:52 PM
Beginning test case Vector64BooleanAsGeneric_Boolean at 5/11/2022 9:06:52 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 5/11/2022 9:06:52 PM
Beginning test case Vector64ByteAsGeneric_Boolean at 5/11/2022 9:06:52 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 5/11/2022 9:06:52 PM
Beginning test case Vector64DoubleAsGeneric_Boolean at 5/11/2022 9:06:52 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Ending test case at 5/11/2022 9:06:52 PM
Beginning test case Vector64Int16AsGeneric_Boolean at 5/11/2022 9:06:52 PM
Random seed: 20


Stack trace
   at JIT_HardwareIntrinsics._General_NotSupported_NotSupported_r_NotSupported_r_._General_NotSupported_NotSupported_r_NotSupported_r_cmd()
```

### PR DESCRIPTION
**Pull request by SingleAccretion**
The transforms in question could fold, e. g., `OBJ<8>(ADDR(LCL_VAR<16>))` to just the `LCL_VAR`, necessitating workarounds in  block morphing that had to rematerialize the block node to restore IR's validity.

It is better to simply not create questionable IR in the first place.

We're expecting a small number of diffs due to using `OBJ`s instead of `IND`s in more cases.

Fixes #69232.

<details>
<summary>What was the problem in #69232?</summary>

  
It was a problem introduced by #68712 and exposed with #68739.

Minimal reproduction:
```cs
[StructLayout(LayoutKind.Sequential, Size = 16)]
struct FakeVtor
{

}

[MethodImpl(MethodImplOptions.NoInlining)]
private static FakeVtor Problem()
{
    FakeVtor GetFakeVtor(Vector128<int> v) => *(FakeVtor*)&v;

    Vector128<int> b = default;
    FakeVtor a = GetFakeVtor(b);
    Use(&a);

    return a;
}
```
Importation, through the magic of skipping `ADDR`s in `gtNewCpObjNode` and `gtNewBlkOpNode` created the following type-mismatched tree:
```scala
               [000025] -A---------                         *  ASG       struct (copy)
               [000009] D----+-N---                         +--*  LCL_VAR   struct<RyuJitReproduction.Program+FakeVtor, 16> V00 loc0         
               [000004] -----+-----                         \--*  LCL_VAR   simd16<System.Runtime.Intrinsics.Vector128`1[System.Int32]> V01 loc1         
```
This on its own should be "fine" since block morphing is supposed to compensate for this mismatch, by wrapping the local in an `OBJ(ADDR)` here:

https://github.com/dotnet/runtime/blob/e502177bf535c47d58948054231f71cb02d370a4/src/coreclr/jit/morph.cpp#L9833-L9865

However, it fails, because it creates an `OBJ` node of `TYP_SIMD16` (using `V01`'s handle). Before #68712, it would have created a handle-less `IND` node and not run into this problem.

I decided to fix the source of the problem instead of extending the workaround in morph because: a) it was simpler, b) I wanted to delete this questionable folding for quite some time as it was causing similar problems elsewhere.

</details>

### CODE REVIEW

**Comment by jakobbotsch** [comment]
@SingleAccretion is this ready?

**Comment by SingleAccretion** [comment]
Unfortunately not yet, the updated SPMI collections have uncovered a couple regressions that have to be solved.

**Comment by SingleAccretion** [comment]
The diffs look more reasonable with the fix: [SPMI in CI](https://dev.azure.com/dnceng/public/_build/results?buildId=1771393&view=ms.vss-build-web.run-extensions-tab).

There are still regressions, caused by the fix itself, where we forward-substitute a multi-reg call and the new local defined by it marked as multi-reg, excluding it from SSA-based optimizations. I think the low number of said regressions (and the fact there are some improvements too) makes the change overall acceptable.

File: src/coreclr/jit/layout.h [hunk 1]
```diff
@@ -35,6 +35,9 @@ class ClassLayout
         BYTE  m_gcPtrsArray[sizeof(BYTE*)];
     };
 
+    // The normalized type to use in IR for block nodes with this layout.
+    const var_types m_type;
```
Comment (SingleAccretion) [inline src/coreclr/jit/layout.h:39]: This increases the size of `ClassLayout` by one pointer. I measured the overall impact on memory consumption and CG-ing x64 CoreLib, it looked insignificant:
```
./diff-mem x64
Relative difference is: 0.007%
```
(This is a memory-CPU tradeoff: `impNormStructType` is not a cheap function)

File: src/coreclr/jit/layout.cpp [hunk 2]
```diff
@@ -400,7 +403,11 @@ void ClassLayout::InitializeGCPtrs(Compiler* compiler)
 // static
 bool ClassLayout::AreCompatible(const ClassLayout* layout1, const ClassLayout* layout2)
 {
-    assert((layout1 != nullptr) && (layout2 != nullptr));
+    if ((layout1 == nullptr) || (layout2 == nullptr))
+    {
+        return false;
+    }
```
Comment (jakobbotsch) [inline src/coreclr/jit/layout.cpp:409]: When does this happen now?

Comment (SingleAccretion) [reply src/coreclr/jit/layout.cpp:409]: It's a convenience feature (I can revert and null check at the call site if you think that'd be better).

The scenario when it happens is when we have a SIMD type local without a layout.

File: src/coreclr/jit/layout.cpp [hunk 3]
```diff
@@ -419,6 +426,11 @@ bool ClassLayout::AreCompatible(const ClassLayout* layout1, const ClassLayout* l
         return false;
     }
 
+    if (layout1->GetType() != layout2->GetType())
+    {
+        return false;
+    }
```
Comment (jakobbotsch) [inline src/coreclr/jit/layout.cpp:432]: Can we assert this in the next `then` instead? It's implied by the sizes being the same if they do not have GC pointers, right?

Comment (jakobbotsch) [reply src/coreclr/jit/layout.cpp:432]: And also when they do have GC pointers I assume (both should be `TYP_STRUCT`). In fact, it seems kind of redundant? Can't we just get this from `HasGCPtr()` and `GetSize()` by calling `getSIMDTypeForSize` which should not be that expensive?

Comment (SingleAccretion) [reply src/coreclr/jit/layout.cpp:432]: Do you mean like this?
```cs
    if (!layout1->HasGCPtr() && !layout2->HasGCPtr())
    {
        return true;
    }
    else
    {
         assert(layout1->GetType() == layout2->GetType());
    }
```
?

The intent of this check is to disallow compatibility between `struct<16>` and `simd16` (which what the assert in #69232 was complaining about).

Comment (jakobbotsch) [reply src/coreclr/jit/layout.cpp:432]: > The intent of this check is to disallow compatibility between struct<16> and simd16

It is confusing to me that such two layouts are incompatible when neither have GC pointers. It is my understanding that `ClassLayout::AreCompatible` has primarily been used for copy purposes before, are we starting to use it for ABI purposes as well?

Comment (SingleAccretion) [reply src/coreclr/jit/layout.cpp:432]: > It is confusing to me that such two layouts are incompatible when neither have GC pointers.

Indeed, it is a questionable behavior. One can "justify" it by asking a question akin to "are `TYP_INT` variables "compatible" with `struct<4>` variables"?

However, this behavior is also pre-existing. Today, if you do this:
```cs
simd16 b = { ... };
struct<16> a = *(struct<16>*)&b;
```
You will get this tree after block morphing:
```scala
Local V01 should not be enregistered because: cast takes addr
MorphCopyBlock (after):
               [000009] -A-X-------                         *  ASG       struct (copy)
               [000008] ---X-+-N---                         +--*  BLK       struct<RyuJitReproduction.Program+Struct16, 16>
               [000007] -----+-----                         |  \--*  LCL_VAR   byref  V00 RetBuf       
               [000006] n----+-----                         \--*  OBJ       struct<RyuJitReproduction.Program+Struct16, 16>
               [000005] -----+-----                            \--*  ADDR      long  
               [000004] -----+-N---                               \--*  LCL_VAR   simd16<System.Runtime.Intrinsics.Vector128`1[System.Int32]> V01 loc0         
```
(You can note that `cast takes addr` DNER reason)

So, this purely reflects what behavior the of block copying is today.

We should of course fix this pessimization; but it's not yet totally clear how (canonicalizing to `TYP_STRUCT` / to `TYP_SIMD` / just fully supporting the mismatch -- but then we should perhaps support mismatches with all primitives...?)

File: src/coreclr/jit/layout.cpp (hunk 2 above)
Comment (jakobbotsch) [reply src/coreclr/jit/layout.cpp:409]: Sounds reasonable to me

File: src/coreclr/jit/layout.cpp (hunk 3 above)
Comment (jakobbotsch) [reply src/coreclr/jit/layout.cpp:432]: Alright, in that case this looks fine to me.

**Review by jakobbotsch — APPROVED** [review]
