### PR TITLE
Vector128.WithElement codegen regression in .NET 9.0

### LINKED ISSUE #108197: Vector128.WithElement codegen regression in .NET 9.0
```cs
struct HBOARD
{
    Vector128<byte> data;

    public void Test(int i, byte b)
    {
        data = data.WithElement(i, b);
    }
}
```
.NET 8.0:
```asm
; Assembly listing for method HBOARD:Test(int,ubyte):this (FullOpts)
G_M000_IG01:                ;; offset=0x0000
       sub      rsp, 56
       vzeroupper 
G_M000_IG02:                ;; offset=0x0007
       vmovups  xmm0, xmmword ptr [rcx]
       cmp      edx, 16
       jae      SHORT G_M000_IG04
       vmovaps  xmmword ptr [rsp+0x20], xmm0
       lea      rax, bword ptr [rsp+0x20]
       movsxd   rdx, edx
       mov      byte  ptr [rax+rdx], r8b
       vmovaps  xmm0, xmmword ptr [rsp+0x20]
       vmovups  xmmword ptr [rcx], xmm0
G_M000_IG03:                ;; offset=0x002C
       add      rsp, 56
       ret      
G_M000_IG04:                ;; offset=0x0031
       mov      ecx, 21
       call     [System.ThrowHelper:ThrowArgumentOutOfRangeException(int)]
       int3     
; Total bytes of code 61
```
.NET 9.0:
```asm
; Assembly listing for method HBOARD:Test(int,ubyte):this (FullOpts)
G_M56601_IG01:  ;; offset=0x0000
       push     rbx
       sub      rsp, 64
       mov      rbx, rcx
       mov      eax, edx
G_M56601_IG02:  ;; offset=0x000A
       vmovups  xmm0, xmmword ptr [rbx]
       vmovaps  xmmword ptr [rsp+0x20], xmm0
       lea      rdx, [rsp+0x20]
       lea      rcx, [rsp+0x30]
       movzx    r9, r8b
       mov      r8d, eax
       call     [System.Runtime.Intrinsics.Vector128:WithElement[ubyte](System.Runtime.Intrinsics.Vector128`1[ubyte],int,ubyte):System.Runtime.Intrinsics.Vector128`1[ubyte]]
       vmovaps  xmm0, xmmword ptr [rsp+0x30]
       vmovups  xmmword ptr [rbx], xmm0
G_M56601_IG03:  ;; offset=0x0035
       add      rsp, 64
       pop      rbx
       ret      
; Total bytes of code 59
```

### PR DESCRIPTION
**Pull request by kendall1997**
# Description
Fixes [https://github.com/dotnet/runtime/issues/108197](https://github.com/dotnet/runtime/issues/108197).

Removes the handling of  `NI_Vector*_WithElement` as a user call and mirrors the behavior of `GetElement` to emit the spill, set the value and then reload the vector.

### CODE REVIEW

**Comment by kendall1997** [comment]
@dotnet-policy-service agree company="Intel"

**Comment by kendall1997** [comment]
@dotnet/intel

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 1]
```diff
@@ -1968,6 +1969,59 @@ void CodeGen::genBaseIntrinsic(GenTreeHWIntrinsic* node, insOpts instOptions)
             break;
         }
 
+        case NI_Vector128_WithElement:
+        case NI_Vector256_WithElement:
+        case NI_Vector512_WithElement:
+        {
+            // Optimize the case where op2 is not a constant.
+            if (!op2->OperIsConst())
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1977]: Should we add a path, like GetElement has, that optimizes for `!op1->isUsedFromReg()`, that is the case where `op1` already exists in memory and we're trying to replace the nth element?

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 2]
```diff
@@ -1968,6 +1969,59 @@ void CodeGen::genBaseIntrinsic(GenTreeHWIntrinsic* node, insOpts instOptions)
...
+                                            indexReg,                                 // Indexed
+                                            genTypeSize(baseType),                    // by the size of the baseType
+                                            offs);                                    // Offset
+                
+                // Write back the modified vector to the original location.
+                GetEmitter()->emitIns_R_S(ins_Store(simdType, compiler->isSIMDTypeLocalAligned(simdInitTempVarNum)),
+                                          emitTypeSize(simdType), targetReg, simdInitTempVarNum, 0);
+
+            }
+            break;
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:2021]: We're either missing an assert or missing handling here.

There's only a path for `!op2->OperIsConst()` which means if `op2` is a constant we'd get no code generated. I believe we shouldn't hit this path if `op1` is already in register and `op2` is a constant because lowering should've rewritten it to be the relevant `Insert` intrinsic instead. But in that case, we should have be asserting that condition

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp (hunk 1 above)
Comment (tannergooding) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1977]: Actually, nevermind, that would only be valid in the case we have some `Load(addr).WithElement(n, value).Store(addr)`, so nothing to do here.

Comment (tannergooding) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1977]: Might be an additional optimization to look at in the future, but not necessary for this PR.

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp (hunk 2 above)
Comment (kendall1997) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:2023]: Assert added for `!op2->OperIsConst()` path.

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 3]
```diff
@@ -1968,6 +1969,59 @@ void CodeGen::genBaseIntrinsic(GenTreeHWIntrinsic* node, insOpts instOptions)
...
+                                            emitTypeSize(baseType),                   // Of the vector baseType
+                                            valueReg,                                 // From valueReg
+                                            (isEBPbased) ? REG_EBP : REG_ESP,         // Stack-based
+                                            indexReg,                                 // Indexed
+                                            genTypeSize(baseType),                    // by the size of the baseType
+                                            offs);                                    // Offset
+                
+                // Write back the modified vector to the original location.
+                GetEmitter()->emitIns_R_S(ins_Store(simdType, compiler->isSIMDTypeLocalAligned(simdInitTempVarNum)),
+                                          emitTypeSize(simdType), targetReg, simdInitTempVarNum, 0);
```
[the remark this answers is not in the document]
Comment (kendall1997) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp]: Changed from `ins_Store` to `ins_Load`.

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 4]
```diff
@@ -1973,6 +1973,8 @@ void CodeGen::genBaseIntrinsic(GenTreeHWIntrinsic* node, insOpts instOptions)
         case NI_Vector256_WithElement:
         case NI_Vector512_WithElement:
         {
+            assert(!op2->OperIsConst());
+
             // Optimize the case where op2 is not a constant.
             if (!op2->OperIsConst())
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1979]: We can remove this check with the assert now existing, since it should always be `true`

Comment (kendall1997) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp]: Updated :)

**Review by tannergooding — APPROVED** [review]
LGTM. CC. @dotnet/jit-contrib, @BruceForstall for secondary review

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by kendall1997** [comment]
Created [https://github.com/dotnet/runtime/pull/115416](https://github.com/dotnet/runtime/pull/115416) to try fix the issue.
