### PR TITLE
Take the memory operand size for some hw intrinsic instructions

### LINKED ISSUE #57458: Test failure:Regressions\\coreclr\\GitHub_34094\\Test34094\\Test34094.cmd
Run: [runtime-coreclr jitstress 20210814.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1294461&view=ms.vss-test-web.build-test-results-tab&runId=38187710&resultId=110653&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
- Regressions\\coreclr\\GitHub_34094\\Test34094\\Test34094.cmd

CoreCLR OSX x64 Checked jitstress2 @ OSX.1013.Amd64.Open
- Regressions/coreclr/GitHub_34094/Test34094/Test34094.sh

CoreCLR Linux x64 Checked jitstress2 @ Ubuntu.1804.Amd64.Open
- Regressions/coreclr/GitHub_34094/Test34094/Test34094.sh

CoreCLR OSX x64 Checked jitstress1 @ OSX.1013.Amd64.Open
- Regressions/coreclr/GitHub_34094/Test34094/Test34094.sh

```
**One of error message:**
```
Assert failure(PID 5988 [0x00001764], Thread: 3976 [0x0f88]): Assertion failed '(emitChkAlign == false) || (ins == INS_lea) || ((emitComp->compCodeOpt() == Compiler::SMALL_CODE) && (((size_t)addr & 3) == 0)) || (((size_t)addr & (byteSize - 1)) == 0)' in 'Test34094:TestAvxCompareGreaterThanOrEqualDouble():bool' during 'Emit code' (IL size 270)

File: D:\workspace\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 11534
Image: C:\h\w\9FF408CA\p\corerun.exe
Return code:      1
Raw output file:      C:\h\w\9FF408CA\w\A79708F5\uploads\Reports\Regressions.coreclr\GitHub_34094\Test34094\Test34094.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\9FF408CA\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" Test34094.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\9FF408CA\p
C:\h\w\9FF408CA\w\A79708F5\e\Regressions\coreclr\GitHub_34094\Test34094\Test34094.cmd
Expected: True
Actual:   False


Stack trace
   at Regressions_coreclr._GitHub_34094_Test34094_Test34094_._GitHub_34094_Test34094_Test34094_cmd()
```

### PR DESCRIPTION
**Pull request by kunalspathak**
For certain HW intrinsic instructions like insert/extract, during outputting, we should check the memory operand size rather than the data operand size to determine if the memory is correctly aligned. We already have special handling during `emitDispIns()` but should be done also during outputting.

I tried searching around `id->idOpSize()` for other places this must be happening and don't see anything except at the code path I updated. While I was there, also pass precalculated `simdSize` value instead of recalculating it again.

Fixes: https://github.com/dotnet/runtime/issues/57458

### CODE REVIEW

**Comment by kunalspathak** [comment]
Failures are related to https://github.com/dotnet/runtime/issues/57620

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @tannergooding

File: src/coreclr/jit/emit.h [hunk 1]
```diff
@@ -2793,6 +2794,58 @@ inline unsigned emitter::emitGetInsCIargs(instrDesc* id)
     }
 }
 
+//-----------------------------------------------------------------------------
+//  emitGetMemOpSize: Get the memory operand size of instrDesc.
+//
+//  Arguments:
+//       id - Instruction descriptor
+//
```
Comment (tannergooding) [inline src/coreclr/jit/emit.h:2802]: Is it worth a remark that this exists because certain instructions have differing register and memory operand sizes?

e.g. `vextractf128` has a `128-bit` output (register or memory) but a `256-bit` input (register).
`vinsertf128` is the inverse with a `256-bit` output (register), a `256-bit` input (register), and a `128-bit` input (register or memory)
etc

**Review by tannergooding — APPROVED** [review]
LGTM.

I'm not sure if we've exhaustively checked instructions for places where the `attr` size and the `memory size` can differ. The display handling was best effort based on known issues, afair.

File: src/coreclr/jit/emit.h (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/emit.h:2802]: Sure, The method should also be under `#ifdef DEBUG` because it is only used in `emitDispIns()` and assert.
