### PR TITLE
Fix non-standard modifiers of printf in GC

### LINKED ISSUE #8737: Address non-standard printf formatting in printf
The `dprintf` logging mechanism in the GC uses some non-standard formatting sequences that may not work as expected with a non-windows CRT. We should settle on standard formatting sequences so that we can use this mechanism on non-Windows platforms.

The standalone GC build currently builds with `-Wno-format` in order to silence the warnings raised about these non-standard formatting sequences.

cc @Maoni0

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #8737

This is a huge change delta. The only changes that exist are within message formats to `dprintf()`.

/cc @dotnet/gc @jkotas @janvorli

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Nice!

File: src/coreclr/gc/gcpriv.h [hunk 1]
```diff
@@ -3088,7 +3088,7 @@ class gc_heap
 
         void print()
         {
-            dprintf (3, ("last plug: %Ix, last plug reloc: %Ix, before last: %Ix, b: %Ix",
+            dprintf (3, ("last plug: %p, last plug reloc: %zu, before last: %p, b: %zu",
```
Comment (am11) [inline src/coreclr/gc/gcpriv.h:3091]: mono uses `Iu` on win 64-bit and `u` on win 32-bit against `zu` on unix. Should we align it?
https://github.com/dotnet/runtime/blob/e6700ea21bbb17ca5058801259bc2d05957814d4/src/mono/CMakeLists.txt#L768

**Comment by cshung** [comment]
Shall we update these as well?
https://github.com/dotnet/runtime/blob/main/src/coreclr/inc/gcmsg.inl

File: src/coreclr/gc/gcpriv.h (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/gc/gcpriv.h:3091]: This was merely to avoid the build issues and remove the suppression. We've loads of other places that need to be updated. This needs to be folded into that effort.

**Comment by AaronRobinsonMSFT** [comment]
@cshung As mentioned in https://github.com/dotnet/runtime/pull/77627#discussion_r1009778404, this was merely to remove the suppression. Yes, all these instances need to be updated. This was by far the biggest lift and was very tedious. I don't think the remaining will take up much, but I wanted to get the `gc.cpp` file done in one shot.

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -3992,7 +3992,7 @@ void region_allocator::delete_region_impl (uint8_t* region_start)
     uint32_t current_val = *current_index;
     assert (!is_unit_memory_free (current_val));
 
-    dprintf (REGIONS_LOG, ("----DEL %d (%u units)-----", (current_index - region_map_left_start), current_val));
+    dprintf (REGIONS_LOG, ("----DEL %d (%u units)-----", (*current_index - *region_map_left_start), current_val));
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/gc/gc.cpp:3995]: Yep, this was intentional. I should have mentioned there were a few issues in the logging that were off.

**Review by janvorli — APPROVED** [review]
