### PR TITLE
Do not perform vector save/restore around call that will never return

### LINKED ISSUE #62005: Assertion failed 'block->bbJumpKind == BBJ_NONE || block->bbJumpKind == BBJ_ALWAYS'
superpmi replay pipeline has been failing with this assert for a while on Linux/Windows arm64:

    ISSUE: <ASSERT> D:\a\_work\1\s\src\coreclr\jit\lsra.cpp (6423) - Assertion failed 'block->bbJumpKind == BBJ_NONE || block->bbJumpKind == BBJ_ALWAYS' in 'Internal.Cryptography.PemKeyHelpers:TryExportToEncryptedPem(System.Numerics.Vector`1[Single],System.ReadOnlySpan`1[Char],System.Security.Cryptography.PbeParameters,TryExportEncryptedKeyAction`1[Vector`1],System.Span`1[Char],byref):bool' during 'LSRA allocate' (IL size 128)
    ISSUE: <ASSERT> D:\a\_work\1\s\src\coreclr\jit\lsra.cpp (6423) - Assertion failed 'block->bbJumpKind == BBJ_NONE || block->bbJumpKind == BBJ_ALWAYS' in 'Internal.Cryptography.PemKeyHelpers:TryExportToPem(System.Numerics.Vector`1[Single],System.String,TryExportKeyAction`1[Vector`1],System.Span`1[Char],byref):bool' during 'LSRA allocate' (IL size 121)

https://dev.azure.com/dnceng/public/_build?definitionId=1055&_a=summary

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by kunalspathak**
We were inserting vector save/restore moves around `ThrowException` that never returns. As such, we hit an assert because the code doesn't expect the restore generated in the end of blocks other than `BBJ_COND`, `BBJ_NONE`, `BBJ_SWITCH` or `BBJ_ALWAYS`. In this case, it was `BBJ_THROW`.

The fix is to not generate save/restore around such calls. We were hitting this issue while jitting a method that was added in #61439.

Fixes: #62005

### CODE REVIEW

File: src/coreclr/jit/lsra.cpp [hunk 1]
```diff
@@ -6274,6 +6274,15 @@ void LinearScan::insertUpperVectorSave(GenTree*     tree,
         return;
     }
 
+#ifdef DEBUG
+    GenTreeCall* call = tree->AsCall();
+    if ((call != nullptr) && (call->gtOper == GT_CALL))
+    {
+        // Make sure that we do not insert vector save before calls that does not return.
+        assert((call->AsCall()->gtCallMoreFlags & GTF_CALL_M_DOES_NOT_RETURN) == 0);
```
Comment (BruceForstall) [inline src/coreclr/jit/lsra.cpp:6282]:
```suggestion
        assert(!call->IsNoReturn());
```

File: src/coreclr/jit/lsrabuild.cpp [hunk 2]
```diff
@@ -1481,6 +1481,16 @@ Interval* LinearScan::getUpperVectorInterval(unsigned varIndex)
...
 {
+    GenTreeCall* call = tree->AsCall();
+    if ((call != nullptr) && (call->gtOper == GT_CALL))
+    {
+        if ((call->AsCall()->gtCallMoreFlags & GTF_CALL_M_DOES_NOT_RETURN) != 0)
+        {
+            // No point in having vector save/restore if the call will not return.
+            return;
+        }
+    }
```
Comment (BruceForstall) [inline src/coreclr/jit/lsrabuild.cpp:1492]: Same comments as above

**Comment by kunalspathak** [comment]
@BruceForstall  - can you review the changes?

**Review by BruceForstall — APPROVED** [review]
