### PR TITLE
Fix HFA/HVA classification

### LINKED ISSUE #35144: [ARM64] Incorrect HFA/HVA property calculation
While reviewing changes in dotnet/coreclr#23675, I noticed that the code added to `EEClass::CheckForHFA` does not handle wrapped `Vector64`, `Vector128`, and  `Vector256` intrinsic types correctly.  For instance, it does not distinguish a wrapped `Vector64` and a `double`.  Moreover, the `elemSize` check is skipped for wrapped `Vector128` and  `Vector256` types.  As a result, the HFA/HVA property may be calculated incorrectly.  For instance (here `{ }` denotes a struct):
* `{{Vector64}, Vector64}` is incorrectly treated as non-HVA.
* `{{Vector64}, double}` is incorrectly treated as HFA(double).
* `{Vector128, {Vector256}}` is incorrectly treated as HVA(simd16).

The code in question: https://github.com/dotnet/runtime/blob/ce416f4c8ba1556bbb8e3d0b0a1a3ee7f16fbc7f/src/coreclr/src/vm/class.cpp#L1345-L1381

The repro program (`set COMPlus_JITDisasm=C::*` to see HFA/HVA properties and registers used):
```C#
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;

#pragma warning disable 0169 // warning CS0169: The field '{0}' is never used
struct WrappedVector64  { Vector64<byte> _; }
struct WrappedVector128 { Vector128<byte> _; }
struct WrappedVector256 { Vector256<byte> _; }

// Incorrectly treated as non-HVA: passed in x0, x1
struct S1 { WrappedVector64 x; Vector64<byte> y; }

// Incorrectly treated as HFA(double): passed in d0, d1
struct S2 { WrappedVector64 x; double y; }

// Incorrectly treated as HVA(simd16): passed in q0, q1, q2
struct S3 { Vector128<byte> x; WrappedVector256 y; }

static class C
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Foo<T>(T x) { }

    static void Main()
    {
        Foo(new S1());
        Foo(new S2());
        Foo(new S3());
    }
}
```
@CarolEidt @echesakovMSFT @sdmaclea

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #35144 and #35976

### CODE REVIEW

File: src/coreclr/src/vm/fieldmarshaler.h [hunk 1]
```diff
@@ -260,34 +253,34 @@ class EEClassNativeLayoutInfo
...
-        return m_hfaType != HFAType::Unset;
+        return m_hfaType != CORINFO_HFA_ELEM_NONE;
     }
 
-    CorElementType GetNativeHFAType() const
+    CorInfoHFAElemType GetNativeHFAType() const
     {
         LIMITED_METHOD_CONTRACT;
-        return (CorElementType)m_hfaType;
+        return (CorInfoHFAElemType)m_hfaType;
```
Comment (sandreenko) [inline src/coreclr/src/vm/fieldmarshaler.h:268]:
```suggestion
        return m_hfaType;
```

File: src/coreclr/src/vm/fieldmarshaler.h [hunk 2]
```diff
@@ -260,34 +253,34 @@ class EEClassNativeLayoutInfo
...
 
-    void SetHFAType(CorElementType hfaType)
+    void SetHFAType(CorInfoHFAElemType hfaType)
     {
         LIMITED_METHOD_CONTRACT;
         // We should call this at most once.
-        _ASSERTE(m_hfaType == HFAType::Unset);
-        m_hfaType = (HFAType)hfaType;
+        _ASSERTE(m_hfaType == CORINFO_HFA_ELEM_NONE);
+        m_hfaType = (CorInfoHFAElemType)hfaType;
```
Comment (sandreenko) [inline src/coreclr/src/vm/fieldmarshaler.h:276]:
```suggestion
        m_hfaType = hfaType;
```

File: src/coreclr/src/jit/codegencommon.cpp [hunk 3]
```diff
@@ -10108,30 +10108,14 @@ unsigned Compiler::GetHfaCount(GenTree* tree)
...
-        CorInfoType corType = info.compCompHnd->getHFAType(hClass);
-#if defined(TARGET_ARM64) && defined(FEATURE_SIMD)
-        if (corType == CORINFO_TYPE_VALUECLASS)
-        {
-            // This is a vector type.
-            // HVAs are only supported on ARM64, and only for homogeneous aggregates of 8 or 16 byte vectors.
-            // For 8-byte vectors corType will be returned as CORINFO_TYPE_DOUBLE.
-            result = TYP_SIMD16;
-            // This type may not appear elsewhere, but it will occupy a floating point register.
-            compFloatingPointUsed = true;
```
Comment (sandreenko) [inline src/coreclr/src/jit/codegencommon.cpp:10124]: is it safe to drop `compFloatingPointUsed = true;`?

File: src/coreclr/src/jit/morph.cpp [hunk 4]
```diff
@@ -4423,11 +4424,7 @@ GenTree* Compiler::fgMorphMultiregStructArg(GenTree* arg, fgArgTabEntry* fgEntry
                 )
         {
             // We have a HFA struct.
-            // Note that GetHfaType may not be the same as elemType, since TYP_SIMD8 is handled the same as TYP_DOUBLE.
             var_types useElemType = elemType;
```
Comment (sandreenko) [inline src/coreclr/src/jit/morph.cpp:4427]:
```suggestion
```

File: src/coreclr/src/jit/morph.cpp [hunk 5]
```diff
@@ -4423,11 +4424,7 @@ GenTree* Compiler::fgMorphMultiregStructArg(GenTree* arg, fgArgTabEntry* fgEntry
...
-#if defined(TARGET_ARM64) & defined(FEATURE_SIMD)
-            useElemType = (elemType == TYP_SIMD8) ? TYP_DOUBLE : useElemType;
-#endif // TARGET_ARM64 && FEATURE_SIMD
             noway_assert(useElemType == varDsc->GetHfaType());
```
Comment (sandreenko) [inline src/coreclr/src/jit/morph.cpp:4428]:
```suggestion
            noway_assert(elemType== varDsc->GetHfaType());
```

**Review by sandreenko — COMMENTED** [review]
Jit/ToolBox changes look good, with one question about `compFloatingPointUsed`.
I like how clean it looks with `DOUBLE\Vector64` separation.

File: src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_35144/Runtime_35144.cs [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+struct WrappedVector64  { Vector64<byte> _; }
+struct WrappedVector128 { Vector128<byte> _; }
+struct WrappedVector256 { Vector256<byte> _; }
+
+// Was incorrectly treated as non-HVA: passed in x0, x1.
+// Should be recognized as HVA(SIMD8) and passed in d0, d1.
+struct S1 { WrappedVector64 x; Vector64<byte> y; }
+
+// Was incorrectly treated as HFA(double): passed in d0, d1.
+// Should be passed as non-NFA in x0, x1.
```
Comment (sandreenko) [inline src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_35144/Runtime_35144.cs:23]:
```suggestion
// Should be passed as non-HFA in x0, x1.
```

**Comment by CarolEidt** [comment]
@davidwrighton - the crossgen2 tests are failing in CI, but passing on my local system. Can you advise me what I might be missing?

**Comment by CarolEidt** [comment]
@dotnet/dnceng - is this a known issue? I see it on two of my PRs, and at least one other as well:
```
##[error].packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20280.1/tools/RepositoryValidation.proj(33,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) License file content '/Users/runner/runners/2.169.1/work/1/s/LICENSE.TXT' doesn't match the expected license '/Users/runner/runners/2.169.1/work/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20280.1/tools/Licenses/MIT.txt'.
```

**Comment by premun** [comment]
@CarolEidt looks like folks are aware and fixed it already here: https://github.com/dotnet/runtime/pull/37626

Rebase should get you going

File: src/coreclr/src/jit/codegencommon.cpp (hunk 3 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/codegencommon.cpp:10124]: No, that was a mistake

**Comment by CarolEidt** [comment]
@jkoritzinsky @davidwrighton @sandreenko PTAL
@dotnet/jit-contrib

**Review by sandreenko — APPROVED** [review]
Jit/ToolBox changes LGTM.

**Review by jkoritzinsky — APPROVED** [review]
VM interop code LGTM

File: src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_35144/Runtime_35144.cs [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+struct S2 { WrappedVector64 x; double y; }
+
+// Incorrectly treated as HVA(simd16): passed in q0, q1, q2.
+// Should be passed by reference as non-HFA.
+struct S3 { Vector128<byte> x; WrappedVector256 y; }
+
+static class Runtime_35144
+{
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    static void Foo<T>(T x) { }
```
Comment (davidwrighton) [inline src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_35144/Runtime_35144.cs:33]: Could you change this test to pass an object after the T parameter? I would like it for GC Stress to cover the case where we use the calling convention processing logic of the VM to parse all of this.

Comment (davidwrighton) [reply src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_35144/Runtime_35144.cs:33]: In particular make the function be written as:

```
static void Foo<T>(T x, object o)
{
    if (o.GetType() != typeof(string)) throw new Exception();
    if (((string)o) != "SomeString") throw new Exception();
}
```
and call it passing a string "SomeString" as the extra parameter.

Comment (davidwrighton) [reply src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_35144/Runtime_35144.cs:33]: Also, if you could mark the Foo<T> method as AggressiveOptimization so that it isn't compiled by crossgen that will also help chase down the case where crossgen compiles this different from what the normal runtime does.

**Review by davidwrighton — CHANGES_REQUESTED** [review]
As far as the change to the product goes, it looks ok, although sufficiently complex that I don't have complete confidence that I can review it to complete correctness. So I've made some suggestions of making the test more complex in ways that will cause our various automated runs to find bugs more effectively.

**Review by davidwrighton — APPROVED** [review]

File: src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_35144/Runtime_35144.cs (hunk 7 above)
Comment (CarolEidt) [reply src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_35144/Runtime_35144.cs]: @davidwrighton - Thanks for the review, and for the suggestions for improving the test!
