### PR TITLE
Ensure BitArray fill operations do not set bits out of range

### LINKED ISSUE #38059: BitArray(Int32, bool) constructor can leave dirty bits causing RightShift() to later fail
### Description

The BitArray(Int32, bool) constructor appears to leave dirty bits in the internal storage array. This breaks an assumption by (at least) RightShift(Int32) such that it can fail.

For Example:

BitArray ba = new BitArray(500, true);

will completely fill the internal array of 16 ints with 0xFFFFFFFF from the call m_array.AsSpan().Fill(-1). 

This causes RightShift() to fail:

BitArray ba = new BitArray(1000, true);
ba.RightShift(500);
for (int i = 0; i < 500; i++)
    Assert.IsTrue(ba[i] == (i < 500)); // will fail at 500 (500 is true)

### Configuration

.NET Core 3.0
Windows 10 1909
x64

(should not be specific to this configuration)

### Regression?

No

### Other information

By modifying the constructor as follows, the issue is resolved. It is also probably bad that RightShift() has this dependency. 

```
            if (defaultValue)
            {
                m_array.AsSpan().Fill(-1);

                Div64Rem(m_length, out int extraBits);
                if (extraBits > 0)
                {
                    m_array[^1] &= (long)((1UL << extraBits) - 1);
                }
            }
```

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Addresses an issue where calling the `BitArray(length, true)` constructor or the `BitArray.SetAll(true)` method results in the remainder bits of the buffer to also be set. These dirty bits can under certain circumstances result in the `RightShift()` method producing incorrect results.

Fixes #38059.

### CODE REVIEW

File: src/libraries/System.Collections/tests/BitArray/BitArray_CtorTests.cs [hunk 1]
```diff
@@ -66,6 +66,17 @@ public static void Ctor_Int_Bool(int length, bool defaultValue)
             Assert.False(collection.IsSynchronized);
         }
 
+        [Fact]
+        public static void Ctor_Int_Bool_ShouldNotLeaveDirtyBits()
+        {
+            BitArray bitArray = new BitArray(33, true);
```
Comment (stephentoub) [inline src/libraries/System.Collections/tests/BitArray/BitArray_CtorTests.cs:72]: Given that we're indexing into the underlying array's last element, consider adding a test for `new BitArray(0, true)` as well.

Comment (stephentoub) [reply src/libraries/System.Collections/tests/BitArray/BitArray_CtorTests.cs:72]: Nevermind, I see we already have one above.

**Review by stephentoub — APPROVED** [review]

**Comment by eiriktsarpalis** [comment]
The `BinaryFormatterTests.ValidateAgainstBlobs` failures seem unrelated to this change (I can see them manifest in other builds as well).

**Review by stephentoub — APPROVED** [review]
