### PR TITLE
[RateLimiting] Fix test race with timer

### LINKED ISSUE #72060: System.Threading.RateLimiting.Tests.PartitionedRateLimiterTests.AllIdleLimitersCleanedUp_DisposeThrows failed in rolling build on net7.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open
[Build](https://runfo.azurewebsites.net/view/build/?number=1873896), [Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5928ea518b814997b5/System.Threading.RateLimiting.Tests/1/console.d9650dfa.log?%3Fhelixlogtype%3Dresult)

```
Starting:    System.Threading.RateLimiting.Tests (parallel test collections = on, max threads = 4)
    System.Threading.RateLimiting.Tests.PartitionedRateLimiterTests.AllIdleLimitersCleanedUp_DisposeThrows [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.AggregateException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/libraries/System.Threading.RateLimiting/tests/PartitionedRateLimiterTests.cs(541,0): at System.Threading.RateLimiting.Tests.PartitionedRateLimiterTests.AllIdleLimitersCleanedUp_DisposeThrows()
        --- End of stack trace from previous location ---
```

First instance of the test failing

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/runtime/issues/72060

### CODE REVIEW

File: src/libraries/System.Threading.RateLimiting/tests/Infrastructure/Utils.cs [hunk 1]
```diff
@@ -13,7 +13,7 @@ namespace System.Threading.RateLimiting.Tests
 {
     internal static class Utils
     {
-        internal static Func<Task> StopTimerAndGetTimerFunc<T>(PartitionedRateLimiter<T> limiter)
+        internal static async Task<Func<Task>> StopTimerAndGetTimerFunc<T>(PartitionedRateLimiter<T> limiter)
```
Comment (halter73) [inline src/libraries/System.Threading.RateLimiting/tests/Infrastructure/Utils.cs:16]: This type signature! 😆 It looks like this should fix the bug, but can we just add a private/internal ctor to `DefaultPartitionedRateLimiter` that doesn't start the timer?

**Review by halter73 — APPROVED** [review]

File: src/libraries/System.Threading.RateLimiting/tests/Infrastructure/Utils.cs (hunk 1 above)
Comment (BrennanConroy) [reply src/libraries/System.Threading.RateLimiting/tests/Infrastructure/Utils.cs]: Tried out the private ctor approach. Definitely removes the possibility of test races now.
