### PR TITLE
Fix fast-path support for ignoring nullable value types

### LINKED ISSUE #96404: Fast-path source generator not honoring `JsonIgnoreCondition.WhenWritingNull` for `Nullable<T>` properties.
Shouldn't these two serialization methods output the same format in NET 8? It does in NET 6/7. If not, is there a way to use source generation and ignore writing null int? values to reduce string/file size?

```
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TestJsonSerialization
{
    public class Forecast
    {
        public DateTime Date { get; set; }

        public int TemperatureC { get; set; }

        public string? Summary { get; set; }

        public int? SomeCounter { get; set; }
    };

    [JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonSerializable(typeof(Forecast))]
    public partial class ForecastSerializationContext: JsonSerializerContext
    { }


    [TestClass]
    public class TestIgnoreNullPolicies
    {
        [TestMethod]
        public void TestIgnoreNull()
        {
            var f = new Forecast { Date = new DateTime(2021,12,01), TemperatureC = 30, Summary = null, SomeCounter = null };
            var sourceGenResult = JsonSerializer.Serialize(f, ForecastSerializationContext.Default.Forecast); //{"Date":"2021-12-01T00:00:00","TemperatureC":30,"SomeCounter":null}


            JsonSerializerOptions options = new()
            {
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            };
            var reflectionResult = JsonSerializer.Serialize(f, options);  //{"Date":"2021-12-01T00:00:00","TemperatureC":30}

            Assert.AreEqual(sourceGenResult, reflectionResult, true);  
        }
    }
}
```

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Fix #96404. Should be backported to .NET 8.

### CODE REVIEW

File: src/libraries/Common/src/SourceGenerators/TypeRef.cs [hunk 1]
```diff
@@ -19,7 +19,7 @@ public TypeRef(ITypeSymbol type)
             FullyQualifiedName = type.GetFullyQualifiedName();
             IsValueType = type.IsValueType;
             TypeKind = type.TypeKind;
-            SpecialType = type.SpecialType;
+            SpecialType = type.OriginalDefinition.SpecialType;
```
Comment (eiriktsarpalis) [inline src/libraries/Common/src/SourceGenerators/TypeRef.cs:22]: The root cause of the issue is that only the generic type definition of `Nullable<T>` is reported as `SpecialType.System_Nullable_T` resulting in the `CanBeNull` property in line 36 of this file to report incorrect values.

**Review by tarekgh — APPROVED** [review]
LGTM!
