### PR TITLE
Protect against ODE when accessing configuration providers

### LINKED ISSUE #117491: Fix regression which could cause ODE during configuration binding
Prior to #116677, did ConfigurationBinder directly reference IConfigurationRoot.Providers for anything? Or did it just use the IConfiguration indexer to read values? I'm a little worried that we've introduced a race condition when combining this new binding logic with ConfigurationManager which is mutable and implements both IConfigurationSource and IConfigurationRoot meaning that the IConfigurationProvider in the list might be disposed by the time you access it leading to an ODE. This is the type returned by WebApplicationBuilder.Configuration and WebApplication.Configuration, so it's pretty widely used.

The indexer works around this issue via reference counting. It prevents the disposal of the IConfigurationProvider until the indexing operation completes. Unfortunately, it's impossible for ConfigurationManager to guarantee any IConfigurationProvider returned by IConfigurationRoot.Providers will never be disposed.

https://github.com/dotnet/runtime/blob/bdf59c626d8f871478e8e3dcdb9801a02822cf8a/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs#L53-L65

https://github.com/dotnet/runtime/blob/bdf59c626d8f871478e8e3dcdb9801a02822cf8a/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs#L78-L81

ConfigurationManager does at least create a new `List<IConfigurationProvider>` after any modification to the configuration sources, so the reverse looping itself should be safe. Long term, I think we need to fix the ConfigurationBinder logic so that it iterates over an immutable reference counted list of providers like the indexer does.

_Originally posted by @halter73 in https://github.com/dotnet/runtime/pull/117474#discussion_r2195875533_

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/117491

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs [hunk 1]
```diff
@@ -51,9 +51,20 @@ internal static bool TryGetConfiguration(this IConfigurationRoot root, string ke
...
+                        return true;
+                    }
+                }
+                catch (ObjectDisposedException)
                 {
-                    return true;
+                    // Skip disposed providers to avoid exceptions during access.
+                    // This is especially relevant for cases like ConfigurationManager,
+                    // which implements IConfigurationRoot and may mutate the providers
+                    // collection and dispose replaced providers.
```
Comment (halter73) [inline src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs:67]:
```suggestion
                    // Skip disposed providers to avoid exceptions during access.
                    // This is especially relevant for cases like ConfigurationManager,
                    // which implements IConfigurationRoot and may dispose providers
                    // if configuration sources are concurrently modified. A new collection
                    // is created in this case, so it's still safe to iterate over it.
                    //
                    // If we want to avoid this possible exception altogether, we could update
                    // ConfigurationSection.TryGetValue to be virtual and have ConfigurationManager
                    // implement it with reference counting like it does for the indexer.
```

I reworded the comment to make it clear that the collection itself does not mutate, so the iteration should be safe. I also point out that we could update TryGetValue to do reference counting like we do in the indexer to avoid this exception. Most of the hard work has already been done for that other than the public API change to make TryGetValue virtual.

However, given our built-in providers like FileConfigurationProvider don't throw and ODE from TryGet after being disposed, I understand going for the simpler change.

**Review by halter73 — APPROVED** [review]

File: src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs (hunk 1 above)
Comment (halter73) [inline src/libraries/Microsoft.Extensions.Configuration/src/InternalConfigurationRootExtensions.cs]:
```suggestion
                    // Skip disposed providers to avoid exceptions during access.
                    // This is especially relevant for cases like ConfigurationManager,
                    // which implements IConfigurationRoot and may dispose providers
                    // if configuration sources are concurrently modified. A new collection
                    // is created in this case, so it's still safe to iterate over it.
                    //
                    // If we want to avoid this possible exception altogether, we could update
                    // ConfigurationSection.TryGetValue to be virtual and have ConfigurationManager
                    // implement it with reference counting like it does for the indexer.
```

I reworded the comment to make it clear that the collection itself does not mutate, so the iteration should be safe. I also point out that we could update TryGetValue to do reference counting like we do in the indexer to avoid this exception. Most of the hard work has already been done for that other than the public API change to make TryGetValue virtual.

However, given our built-in providers like FileConfigurationProvider don't throw and ODE from TryGet after being disposed, I understand going for the simpler change.
