### PR TITLE
Add RL non-generic fixed window, sliding window implementations

### LINKED ISSUE #37381: Finish implementations for non-generic rate limiters (Fixed windows, Sliding windows, Token bucket, Concurrency limiter)
We will be providing the following non generic implementations for Rate Limiting: 

- [ ] Fixed windows (@shreyaverma165 )
- [ ] Sliding windows (@shreyaverma165 )
- [x] [Token bucket](https://github.com/aspnet/AspLabs/pull/390) (@BrennanConroy)
- [x] [Concurrency limiter](https://github.com/aspnet/AspLabs/pull/387) (@BrennanConroy )

### PR DESCRIPTION
**Pull request by shreyaverma165**
Fixes: https://github.com/dotnet/aspnetcore/issues/37381

** Updating this PR with comments and test cases.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=68087) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=68087) before we can accept your contribution.<br/><br/>:x: shreyaverma165 [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=68087)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=68087) it.</sub>

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 1]
```diff
@@ -0,0 +1,412 @@
...
+        public SlidingWindowRateLimiter(SlidingWindowRateLimiterOptions options!!)
+        {
+            _options = options;
+            _requestCount = options.PermitLimit;
+            _requestsPerSegment = new int[options.SegmentsPerWindow];
+            _currentSegmentIndex = 0;
+
+            if (_options.AutoReplenishment)
+            {
+                _renewTimer = new Timer(Replenish, this, _options.Window, _options.Window);
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:57]: This should trigger every `(Window / SegmentsPerWindow)`

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 2]
```diff
@@ -0,0 +1,412 @@
...
+                {
+                    return;
+                }
+
+                if ((long)((nowTicks - _lastReplenishmentTick) * TickFrequency) < _options.Window.Ticks)
+                {
+                    return;
+                }
+
+                SlidingWindowRateLimiterOptions options = _options;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:235]: nit: don't need to assign this to a local variable

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 3]
```diff
@@ -0,0 +1,412 @@
...
+        {
+            // method is re-entrant (from Timer), lock to avoid multiple simultaneous replenishes
+            lock (Lock)
+            {
+                if (_disposed)
+                {
+                    return;
+                }
+
+                if ((long)((nowTicks - _lastReplenishmentTick) * TickFrequency) < _options.Window.Ticks)
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:230]: This should be checking against `windowSegmentInterval`

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 4]
```diff
@@ -0,0 +1,412 @@
...
+                    return;
+                }
+
+                SlidingWindowRateLimiterOptions options = _options;
+
+                TimeSpan windowSegmentInterval = options.Window / options.SegmentsPerWindow;
+                _lastReplenishmentTick = nowTicks + windowSegmentInterval.Ticks;
+
+                _currentSegmentIndex = (_currentSegmentIndex + 1) % options.SegmentsPerWindow;
+                int wrappedRequestCount = _requestsPerSegment[_currentSegmentIndex];
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:241]: nit: `int oldSegmentRequestCount`

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 5]
```diff
@@ -0,0 +1,412 @@
...
+                _requestsPerSegment[_currentSegmentIndex] = 0;
+
+                if (wrappedRequestCount == 0)
+                    return;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:245]:
```suggestion
                {
                    return;
                }
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 6]
```diff
@@ -0,0 +1,412 @@
...
+
+                // Process queued requests
+                Deque<RequestRegistration> queue = _queue;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:248]: Don't need to assign to local variable

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 7]
```diff
@@ -0,0 +1,412 @@
...
+                    if (_requestCount >= nextPendingRequest.Count)
+                    {
+                        // Request can be fulfilled
+                        nextPendingRequest =
+                            options.QueueProcessingOrder == QueueProcessingOrder.OldestFirst
+                            ? queue.DequeueHead()
+                            : queue.DequeueTail();
+
+                        _queueCount -= nextPendingRequest.Count;
+                        _requestCount -= nextPendingRequest.Count;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:268]: Segment array should be updated here

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 8]
```diff
@@ -0,0 +1,412 @@
...
+                        Debug.Assert(_requestCount >= 0);
+
+                        if (!nextPendingRequest.Tcs.TrySetResult(SuccessfulLease))
+                        {
+                            // Queued item was canceled so add count back
+                            _requestCount += nextPendingRequest.Count;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:274]: Segment array should be updated here

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiterOptions.cs [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+    public sealed class FixedWindowRateLimiterOptions
+    {
+        /// <summary>
+        /// Initializes the <see cref="FixedWindowRateLimiterOptions"/>.
+        /// </summary>
+        /// <param name="permitLimit">Maximum number of requests that can be served in the window.</param>
+        /// <param name="queueProcessingOrder"></param>
+        /// <param name="queueLimit">Maximum number of unprocessed request counters waiting via <see cref="RateLimiter.WaitAsync(int, CancellationToken)"/>.</param>
+        /// <param name="window">
+        /// Specifies how often request counters can be replenished. Replenishing is triggered either by an internal timer if <paramref name="autoReplenishment"/> is true, or by calling <see cref="FixedWindowRateLimiter.TryRefresh"/>.
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiterOptions.cs:18]:
```suggestion
        /// Specifies how often request counters can be replenished. Replenishing is triggered either by an internal timer if <paramref name="autoReplenishment"/> is true, or by calling <see cref="FixedWindowRateLimiter.TryReplenish"/>.
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiterOptions.cs [hunk 10]
```diff
@@ -0,0 +1,77 @@
...
+        /// </param>
+        /// <param name="autoReplenishment">
+        /// Specifies whether request replenishment will be handled by the <see cref="FixedWindowRateLimiter"/> or by another party via <see cref="FixedWindowRateLimiter.TryReplenish"/>.
+        /// </param>
+        /// <exception cref="ArgumentOutOfRangeException">When <paramref name="permitLimit"/> or <paramref name="queueLimit"/> are less than 0
+        /// or when <paramref name="window"/> is more than 49 days.</exception>
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiterOptions.cs:24]:
```suggestion
        /// <exception cref="ArgumentOutOfRangeException">When <paramref name="permitLimit"/> or <paramref name="queueLimit"/> are less than 0.</exception>
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiterOptions.cs (hunk 9 above)
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiterOptions.cs:18]:
```suggestion
        /// Specifies how often request counters can be replenished. Replenishing is triggered either by an internal timer if <paramref name="autoReplenishment"/> is true, or by calling <see cref="FixedWindowRateLimiter.TryReplenish"/>.
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiter.cs [hunk 11]
```diff
@@ -0,0 +1,427 @@
...
+        public override TimeSpan? IdleDuration => _idleSince is null ? null : new TimeSpan((long)((Stopwatch.GetTimestamp() - _idleSince) * TickFrequency));
+
+        /// <inheritdoc />
+        public override bool IsAutoReplenishing => _options.AutoReplenishment;
+
+        /// <inheritdoc />
+        public override TimeSpan ReplenishmentPeriod => _options.Window;
+
+
+
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiter.cs:42]:
```suggestion

```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiter.cs [hunk 12]
```diff
@@ -0,0 +1,427 @@
...
+        /// <summary>
+        /// Initializes the <see cref="FixedWindowRateLimiter"/>.
+        /// </summary>
+        /// <param name="options">Options to specify the behavior of the <see cref="FixedWindowRateLimiter"/>.</param>
+        public FixedWindowRateLimiter(FixedWindowRateLimiterOptions options!!)
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/FixedWindowRateLimiter.cs:47]: The `!!` is actually being removed, see https://github.com/dotnet/runtime/pull/68178
```suggestion
        public FixedWindowRateLimiter(FixedWindowRateLimiterOptions options)
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiterOptions.cs [hunk 13]
```diff
@@ -0,0 +1,89 @@
...
+        /// <param name="queueLimit">Maximum number of unprocessed request counters waiting via <see cref="RateLimiter.WaitAsync(int, CancellationToken)"/>.</param>
+        /// <param name="window">
+        /// Specifies how often requests can be replenished. Replenishing is triggered either by an internal timer if <paramref name="autoReplenishment"/> is true, or by calling <see cref="SlidingWindowRateLimiter.TryReplenish"/>.
+        /// </param>
+        /// <param name="segmentsPerWindow">Specified how many segments a window can be divided into. The total requests a segment can serve cannot exceed the max limit.<paramref name="permitLimit"/>.</param>
+        /// <param name="autoReplenishment">
+        /// Specifies whether request replenishment will be handled by the <see cref="SlidingWindowRateLimiter"/> or by another party via <see cref="SlidingWindowRateLimiter.TryReplenish"/>.
+        /// </param>
+        /// <exception cref="ArgumentOutOfRangeException">When <paramref name="permitLimit"/>, <paramref name="queueLimit"/>, or <paramref name="segmentsPerWindow"/> are less than 0
+        /// or when <paramref name="window"/> is more than 49 days.</exception>
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiterOptions.cs:25]:
```suggestion
        /// <exception cref="ArgumentOutOfRangeException">When <paramref name="permitLimit"/>, <paramref name="queueLimit"/>, or <paramref name="segmentsPerWindow"/> are less than 0.</exception>
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 14]
```diff
@@ -0,0 +1,415 @@
...
+        private static readonly double TickFrequency = (double)TimeSpan.TicksPerSecond / Stopwatch.Frequency;
+
+        /// <inheritdoc />
+        public override TimeSpan? IdleDuration => _idleSince is null ? null : new TimeSpan((long)((Stopwatch.GetTimestamp() - _idleSince) * TickFrequency));
+
+        /// <inheritdoc />
+        public override bool IsAutoReplenishing => _options.AutoReplenishment;
+
+        /// <inheritdoc />
+        public override TimeSpan ReplenishmentPeriod => _options.Window;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:42]: This also should be windowSegmentInterval

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 15]
```diff
@@ -0,0 +1,415 @@
...
+        /// <summary>
+        /// Initializes the <see cref="SlidingWindowRateLimiter"/>.
+        /// </summary>
+        /// <param name="options">Options to specify the behavior of the <see cref="SlidingWindowRateLimiter"/>.</param>
+        public SlidingWindowRateLimiter(SlidingWindowRateLimiterOptions options!!)
+        {
+            _options = options;
+            _requestCount = options.PermitLimit;
+            _requestsPerSegment = new int[options.SegmentsPerWindow];
+            TimeSpan _windowSegmentInterval = _options.Window / _options.SegmentsPerWindow;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:53]: Local variables don't have the `_` prefix
```suggestion
            TimeSpan windowSegmentInterval = _options.Window / _options.SegmentsPerWindow;
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 16]
```diff
@@ -0,0 +1,415 @@
...
+            _currentSegmentIndex = 0;
+
+            if (_options.AutoReplenishment)
+            {
+                _renewTimer = new Timer(Replenish, this, _windowSegmentInterval, _windowSegmentInterval);
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:58]:
```suggestion
                _renewTimer = new Timer(Replenish, this, windowSegmentInterval, windowSegmentInterval);
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 17]
```diff
@@ -0,0 +1,415 @@
...
+            }
+        }
+
+        /// <inheritdoc/>
+        public override int GetAvailablePermits() => _options.PermitLimit - _requestCount;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:63]: I think this is just `_requestCount`?

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 18]
```diff
@@ -0,0 +1,415 @@
...
+                {
+                    return;
+                }
+
+                if ((long)((nowTicks - _lastReplenishmentTick) * TickFrequency) < _windowSegmentInterval.Ticks)
+                {
+                    return;
+                }
+
+                _lastReplenishmentTick = nowTicks + _windowSegmentInterval.Ticks;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:238]: We shouldn't be adding the segment interval.

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 19]
```diff
@@ -0,0 +1,415 @@
...
+
+            // Use Environment.TickCount instead of DateTime.UtcNow to avoid issues on systems where the clock can change
+            long nowTicks = Stopwatch.GetTimestamp();
+            limiter!.ReplenishInternal(nowTicks);
+        }
+
+        // Used in tests that test behavior with specific time intervals
+        private void ReplenishInternal(long nowTicks)
+        {
+            TimeSpan _windowSegmentInterval = _options.Window / _options.SegmentsPerWindow;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:223]: Same here, local variables shouldn't have `_` prefix

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 20]
```diff
@@ -0,0 +1,415 @@
...
+
+                if ((long)((nowTicks - _lastReplenishmentTick) * TickFrequency) < _windowSegmentInterval.Ticks)
+                {
+                    return;
+                }
+
+                _lastReplenishmentTick = nowTicks + _windowSegmentInterval.Ticks;
+
+                _currentSegmentIndex = (_currentSegmentIndex + 1) % _options.SegmentsPerWindow;
+                int _oldSegmentRequestCount = _requestsPerSegment[_currentSegmentIndex];
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:241]: And here, change to `oldSegmentRequestCount`

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 21]
```diff
@@ -0,0 +1,415 @@
...
+
+                        _requestCount -= nextPendingRequest.Count;
+                        _requestsPerSegment[_currentSegmentIndex] += _requestCount;
+                        Debug.Assert(_requestCount >= 0);
+
+                        if (!nextPendingRequest.Tcs.TrySetResult(SuccessfulLease))
+                        {
+                            // Queued item was canceled so add count back
+                            _requestCount += nextPendingRequest.Count;
+                            _requestsPerSegment[_currentSegmentIndex] += _requestCount;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:277]:
```suggestion
                            _requestsPerSegment[_currentSegmentIndex] -= _requestCount;
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs (hunk 17 above)
Comment (shreyaverma165) [reply src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:63]: Ya, I didn't consider reducing it in ReplenishInternal. Thank you for pointing that out.

**Comment by BrennanConroy** [comment]
I think the ref file needs to be updated. `dotnet msbuild /t:GenerateReferenceAssemblySource`

File: src/libraries/Microsoft.Bcl.AsyncInterfaces/ref/Microsoft.Bcl.AsyncInterfaces.cs [hunk 22]
```diff
@@ -4,93 +4,3 @@
 // Changes to this file must follow the https://aka.ms/api-review process.
 // ------------------------------------------------------------------------------
 
-namespace System
```
Comment (BrennanConroy) [inline src/libraries/Microsoft.Bcl.AsyncInterfaces/ref/Microsoft.Bcl.AsyncInterfaces.cs:7]: Revert the changes to this file

File: src/libraries/System.Threading.RateLimiting/ref/System.Threading.RateLimiting.cs [hunk 23]
```diff
@@ -40,19 +58,6 @@ public sealed partial class MetadataName<T> : System.IEquatable<System.Threading
         public static bool operator !=(System.Threading.RateLimiting.MetadataName<T> left, System.Threading.RateLimiting.MetadataName<T> right) { throw null; }
         public override string ToString() { throw null; }
     }
-    public abstract partial class PartitionedRateLimiter<TResource> : System.IAsyncDisposable, System.IDisposable
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/ref/System.Threading.RateLimiting.cs:43]: This file didn't seem to get updated correctly.

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 24]
```diff
@@ -0,0 +1,412 @@
...
+        private static readonly double TickFrequency = (double)TimeSpan.TicksPerSecond / Stopwatch.Frequency;
+
+        /// <inheritdoc />
+        public override TimeSpan? IdleDuration => _idleSince is null ? null : new TimeSpan((long)((Stopwatch.GetTimestamp() - _idleSince) * TickFrequency));
+
+        /// <inheritdoc />
+        public override bool IsAutoReplenishing => _options.AutoReplenishment;
+
+        /// <inheritdoc />
+        public override TimeSpan ReplenishmentPeriod => _options.Window / _options.SegmentsPerWindow;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:42]: Sadly divide on TimeSpan wasn't implemented in netstandard2.0 so we need to fallback to implementing it ourselves. `new TimeSpan(_options.Windows.Ticks / _options.SegmentsPerWindow)`

File: src/libraries/System.Threading.RateLimiting/tests/SlidingWindowRateLimiterTests.cs [hunk 25]
```diff
@@ -0,0 +1,696 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using Xunit;
```
[the remark this answers is not in the document]
Comment (shreyaverma165) [reply src/libraries/System.Threading.RateLimiting/tests/SlidingWindowRateLimiterTests.cs:4]: Checking test cases

File: src/libraries/System.Threading.RateLimiting/tests/FixedWindowRateLimiterTests.cs [hunk 26]
```diff
@@ -0,0 +1,696 @@
...
+
+            // second queued item completes first with NewestFirst
+            lease = await wait2;
+            Assert.True(lease.IsAcquired);
+            Assert.False(wait1.IsCompleted);
+
+            lease.Dispose();
+            Assert.Equal(1, limiter.GetAvailablePermits());
+            Assert.True(limiter.TryReplenish());
+            Assert.True(limiter.TryReplenish());
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/tests/FixedWindowRateLimiterTests.cs:108]: nit: remove the second TryReplenish, it makes sense for TokenBucket since it has a replenish rate, but for fixed window it replenishes everything.

File: src/libraries/System.Threading.RateLimiting/tests/FixedWindowRateLimiterTests.cs [hunk 27]
```diff
@@ -0,0 +1,696 @@
...
+
+            var wait3 = limiter.WaitAsync(2);
+            var lease1 = await wait;
+            var lease2 = await wait2;
+            Assert.False(lease1.IsAcquired);
+            Assert.False(lease2.IsAcquired);
+            Assert.False(wait3.IsCompleted);
+
+            limiter.TryReplenish();
+            limiter.TryReplenish();
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/tests/FixedWindowRateLimiterTests.cs:169]: nit: remove second TryReplenish

File: src/libraries/System.Threading.RateLimiting/tests/SlidingWindowRateLimiterTests.cs [hunk 28]
```diff
@@ -0,0 +1,638 @@
...
+
+            var failedLease = await limiter.WaitAsync(2);
+            Assert.False(failedLease.IsAcquired);
+
+            limiter.TryReplenish();
+            lease = await wait;
+            Assert.True(lease.IsAcquired);
+
+            wait = limiter.WaitAsync(2);
+            Assert.False(wait.IsCompleted);
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/tests/SlidingWindowRateLimiterTests.cs:212]: Should add another replenish here and verify that the lease is acquired.

File: src/libraries/System.Threading.RateLimiting/tests/SlidingWindowRateLimiterTests.cs [hunk 29]
```diff
@@ -0,0 +1,638 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Diagnostics;
+using System.Threading.Tasks;
+using Xunit;
+
+namespace System.Threading.RateLimiting.Test
+{
+    public class SlidingWindowRateLimiterTests : BaseRateLimiterTests
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/tests/SlidingWindowRateLimiterTests.cs:10]: None of the tests actually make use the sliding window all the segment sizes are 1.

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 30]
```diff
@@ -0,0 +1,414 @@
...
+
+                if ((long)((nowTicks - _lastReplenishmentTick) * TickFrequency) < ReplenishmentPeriod.Ticks)
+                {
+                    return;
+                }
+
+                _lastReplenishmentTick = nowTicks;
+
+                int oldSegmentRequestCount = _requestsPerSegment[_currentSegmentIndex];
+                _currentSegmentIndex = (_currentSegmentIndex + 1) % _options.SegmentsPerWindow;
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:240]: Why was this moved after grabbing the `oldSegmentRequestCount`? Shouldn't it be before so we add back the correct number of requests? If it should be moved back, can we add a test that verifies the behavior?

File: src/libraries/System.Threading.RateLimiting/tests/SlidingWindowRateLimiterTests.cs [hunk 31]
```diff
@@ -0,0 +1,713 @@
...
+            var wait2 = limiter.WaitAsync(2);
+            Assert.False(wait2.IsCompleted);
+
+            Assert.True(limiter.TryReplenish());
+
+            Assert.True((await wait2).IsAcquired);
+        }
+
+        [Fact]
+        public async Task CanAcquireMulitpleRequestsAsync()
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/tests/SlidingWindowRateLimiterTests.cs:66]: Can we add comments in this test? I already forgot what scenario it was testing specifically

Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/tests/SlidingWindowRateLimiterTests.cs:66]:
```suggestion
        public async Task CanAcquireMultipleRequestsAsync()
```

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs [hunk 32]
```diff
@@ -0,0 +1,422 @@
...
+
+                if ((long)((nowTicks - _lastReplenishmentTick) * TickFrequency) < ReplenishmentPeriod.Ticks)
+                {
+                    return;
+                }
+
+                _lastReplenishmentTick = nowTicks;
+
+                // Increament the current segment index while move the window
+                // We need to know the no. of requests that were acquired in a segment perviously to ensure that we don't acquire more than the permit limit.
```
Comment (BrennanConroy) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/SlidingWindowRateLimiter.cs:245]:
```suggestion
                // Increment the current segment index while move the window
                // We need to know the no. of requests that were acquired in a segment previously to ensure that we don't acquire more than the permit limit.
```

**Review by BrennanConroy — APPROVED** [review]
