### PR TITLE
Provide fix for #81093 - "Mono does not emit ProcessExit event on SIGTERM"

### LINKED ISSUE #81093: Mono does not emit ProcessExit event on SIGTERM.
To reproduce:

```
dotnet new web -o web
cd web
dotnet run
```
Find the pid of the `dotnet run` process, and send it SIGTERM from another terminal:
```
kill -SIGTERM <pid>
```

With CoreCLR, the application shuts down, and the exit code is `0`:
```
...
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
$ echo $?
0
```

With Mono, the application keeps running, the `dotnet run` process gets terminated:
```
Terminated
$ echo $?
143
```
The `web` process is still running, you can send it SIGTERM seperately and it terminates nicely.
```
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

This difference in behavior is causing one of the source-build smoke tests to fail: https://github.com/dotnet/source-build/issues/3174.

cc @akoeplinger

### PR DESCRIPTION
**Pull request by nealef**
Supersedes https://github.com/dotnet/runtime/pull/82813
Fixes https://github.com/dotnet/runtime/issues/81093

* src/mono/mono/mini/mini-posix.c
  - Add signal handler for SIGTERM

* src/mono/mono/mini/mini-windows.c
  - Add signal handler for SIGTERM
  - Use the correct signal for handler

* src/mono/mono/mini/mini-runtime.c
  - Add mono_sigterm_signal_handler to process SIGTERM that will set a global variable to be monitored by the GC finalizer thread
  - Set a default exit code before setting the term_signaled variable that gets checked in gc

* src/mono/mono/mini/mini-runtime.h
  - Define prototype for mono_sigterm_signal_handler()

* src/mono/mono/metadata/gc.c
  - Monitor for sigterm and kick off the shutdown process when encountered by calling mono_runtime_try_shutdown().
  - Exit with either the user set exitcode (System.Environment.ExitCode) or SIGTERM + 128.
  - Simplify use of exit code now that a default is being set
  - Rename term_signaled to match mono style
  - Remove volatile attribute
  - Move testing of shutdown until after the sem wait

* src/libraries/System.Runtime/tests/System/ExitCodeTests.Unix.cs
  - Re-enable ExitCodeTests for mono

* src/mono/mono/mini/exceptions-amd64.c src/mono/mono/mini/exceptions-x86.c
  - Add control event handling for windows

__Note__: The comments in the original PR regarding possible memory barriers and acquire/release are still to be addressed.

### CODE REVIEW

**Comment by lewing** [comment]
I cycled CI just to have up to date checks

File: src/mono/mono/mini/exceptions-x86.c [hunk 1]
```diff
@@ -272,6 +298,11 @@ void win32_seh_set_handler(int type, MonoW32ExceptionHandler handler)
 	case SIGSEGV:
 		segv_handler = handler;
 		break;
+	case SIGTERM:
+		term_handler = handler;
+		if (!SetConsoleCtrlHandler(mono_win_ctrl_handler, TRUE))
```
Comment (kg) [inline src/mono/mono/mini/exceptions-x86.c:303]: This adds a new handler, so if win32_seh_set_handler was previously called to install a different term_handler, shouldn't we uninstall the old one first?

Comment (kg) [reply src/mono/mono/mini/exceptions-x86.c:303]: actually, i misread, but i think this would add a copy of our handler each time you set a term handler, so we might end up with 3 copies of the same one installed unless the kernel removes duplicates. the docs don't say whether it does

if an application calls AllocConsole or AttachConsole this handler will get uninstalled, but that's probably fine to consider as a 'don't do that' problem

**Comment by kg** [comment]
lgtm but i'm not an expert on our EH internals or signals

**Review by lambdageek — APPROVED** [review]
thanks!

**Comment by directhex** [comment]
/ba-g all dead lettering on some tests, signed off by various managers & engineers who know relevant areas
