### PR TITLE
Mono: increase default stack size on s390x/ppc64le; support DOTNET_Thread_DefaultStackSize for setting stack size.

### LINKED ISSUE #124368: Default stack size Mono vs CoreCLR
I debugged a crash of vmr which occurred while building fsharp repo on s390x. Looking at the crash, the stack had overflowed.

I had not seen such an overflow on x64/arm64 (using CoreCLR). Looking closer at the implementation, with CoreCLR, the stack size follows the Linux configured limit (`ulimit -s`, typically 8MB), while for Mono it is hard-coded to 2MB (on 64-bit, and 1MB on 32-bit):

https://github.com/dotnet/runtime/blob/f7ccc3cd23eb4f1b354772f8dc0f9637c83ff889/src/mono/mono/utils/mono-threads-posix.c#L77

When I changed the hard-coded size to 8MB on Mono, the stack overflow crash no longer occurred.

This issue is for changing the stack size on Mono so it matches with what CoreCLR does (in a similar environment).

cc @jkotas @akoeplinger @omajid

### PR DESCRIPTION
**Pull request by tmds**
This increases the default stack size on s390x and ppc64le. Due to missing implementation for tail call optimization, the vmr build exhaust the stack while building the fsharp repo. With an 8MB stack, the build can complete.

Additionally this adds support for a user to control the stack size using the DOTNET_Thread_DefaultStackSize envvar.

Fixes https://github.com/dotnet/runtime/issues/124368.

@jkotas @akoeplinger @hamarb123 ptal.

### CODE REVIEW

File: src/mono/mono/utils/mono-threads-posix.c [hunk 1]
```diff
@@ -72,10 +73,30 @@ mono_thread_platform_create_thread (MonoThreadStart thread_fn, gpointer thread_d
...
-#else
-		set_stack_size = (SIZEOF_VOID_P / 4) * 1024 * 1024;
 #endif
+		{
+			if (system_stacksize == 0) {
+				// Use RLIMIT_STACK as the default stack size.
+				// This matches the default stack size of pthreads on glibc Linux distros.
+				// On Musl Linux, pthread defaults to a small size of 128KB. Using RLIMIT_STACK aligns the behavior with glibc Linux.
+				struct rlimit lim;
+				if (getrlimit (RLIMIT_STACK, &lim) == 0) {
```
Comment (jkotas) [inline src/mono/mono/utils/mono-threads-posix.c]: I do not see any code in CoreCLR that reads RLIMIT_STACK. Why do we need to read it in Mono? I would expect both CoreCLR and Mono to depend on the same APIs if the behavior is meant to be aligned.

Comment (tmds) [reply src/mono/mono/utils/mono-threads-posix.c]: The default behavior of pthreads with glibc is that when you don't specify a stack size, it uses RLIMIT_STACK.

The default behavior of pthreads with musl is that it uses a 128KB stack that is too small for .NET.

I've implemented this to not treat either glibc or Musl special and everywhere get the RLIMIT_STACK and use that.

For CoreCLR, the current behavior with glibc is not specify a stack size (-> use RLIMIT_STACK) and for Musl it uses a hard coded 1.5MB (per ENSURE_PRIMARY_STACK_SIZE).

I think we should also use RLIMIT_STACK with Musl with CoreCLR. This isn't included in this PR. I'd like to look at if we can't eliminate ENSURE_PRIMARY_STACK_SIZE (it is a guess for RLIMIT_STACK).

Comment (jkotas) [reply src/mono/mono/utils/mono-threads-posix.c]: musl made an explicit decision to not respect RLIMIT_STACK. Is it really an improvement to override their decision?

Comment (tmds) [reply src/mono/mono/utils/mono-threads-posix.c]: We need to anyhow increase what they use per default and by aligning with glibc we eliminate an unexpected difference and provide a way for the user to control the size.

Comment (tmds) [reply src/mono/mono/utils/mono-threads-posix.c]: The Alpine maintainers also build for s390x. Without this change, it's expected they'll run into the fsharp build issue.

Comment (jkotas) [reply src/mono/mono/utils/mono-threads-posix.c]: Mono workload owners should comment on the impact of reading RLIMIT in Mono by default.

CoreCLR allows configuration of the default stack size via `Thread_DefaultStackSize`. Reading this config in Mono would align it with CoreCLR.

**Comment by jkotas** [comment]
> Should we consider just using getrlimit on coreclr/naot also on all unix platforms? macOS defaults to 8MB for main thread by default (from that value), but then 512kB for secondary threads - we currently override manually to 1.5MB, but maybe it makes sense to just use logic this everywhere

I am hesitant to bump the default stack sizes further. This was discussed before in https://github.com/dotnet/runtime/pull/98007

File: src/mono/mono/utils/mono-threads-posix.c (hunk 1 above)
Comment (tmds) [reply src/mono/mono/utils/mono-threads-posix.c]: I think the change is meaningful in particular for when we're source-building .NET on Linux and use Mono instead of CoreCLR. It matches the stack sizes with those of CoreCLR.

I'm not sure what other builds this affects. If desired, we could make this conditional to the source-build use-case.

We can add support for `Thread_DefaultStackSize` too to provide a consistent way to control the stack size.

File: src/mono/mono/utils/mono-threads-posix.c [hunk 2]
```diff
@@ -72,10 +73,30 @@ mono_thread_platform_create_thread (MonoThreadStart thread_fn, gpointer thread_d
...
+					if (lim.rlim_cur == RLIM_INFINITY)
+						rlim_stack_size = 8 * 1024 * 1024;
+					else
+						rlim_stack_size = (size_t)lim.rlim_cur;
+
+					system_stacksize = (rlim_stack_size > (size_t)UINT32_MAX) ? UINT32_MAX : (guint32)rlim_stack_size;
+				}
+				// If we can't get a limit from the system, default to Windows stack size (1.5MB).
+				if (system_stacksize == 0)
+					system_stacksize = 1536 * 1024;
```
Comment (akoeplinger) [inline src/mono/mono/utils/mono-threads-posix.c]: should we use the original values as fallback here (1MB on 32bit, 2MB on 64bit)?

File: src/mono/mono/utils/mono-threads-posix.c (hunk 1 above)
Comment (akoeplinger) [reply src/mono/mono/utils/mono-threads-posix.c]: I'm fine with reading RLIMIT, but ideally we'd be consistent with CoreCLR.

If we can't agree on that for now, we could also just default to a higher default hardcoded limit on platforms that don't support tailcalls

Comment (tmds) [reply src/mono/mono/utils/mono-threads-posix.c]: This aligns with glibc behavior on CoreCLR.

I will add changes to CoreCLR to have a similar implementation as added here for Mono. This will have the (intended) effect that on Musl Linux the behavior will be the same too.

Comment (jkotas) [reply src/mono/mono/utils/mono-threads-posix.c]: I do not think we want to be regressing Musl by respecting RLIMIT in CoreCLR. Musl differentiates from glibc by being leaner, and the smaller default stack size is one of the many ways it does that.

Comment (tmds) [reply src/mono/mono/utils/mono-threads-posix.c]: We can keep the stack behavior for Musl on CoreCLR like it is now if that is preferred.

So then we won't change CoreCLR to match the behavior which is currently here: read RLIMIT and use it as a stack size.

The issue I'm actually trying to address is architectures where tail call optimizations are lacking on Mono run out of stack space.

So, we could just bump the stack size to 8MB on s390x/ppc64le (on Mono).

And then additionally, we can introduce the `Thread_DefaultStackSize` to enable configuring the stack size also on Mono which gives users control over this.

How does that sound?

Comment (jkotas) [reply src/mono/mono/utils/mono-threads-posix.c]: > we could just bump the stack size to 8MB on s390x/ppc64le (on Mono).

That sounds fine to me.

File: src/mono/mono/metadata/threads.c [hunk 3]
```diff
@@ -1445,6 +1445,21 @@ mono_threads_set_default_stacksize (guint32 stacksize)
 guint32
 mono_threads_get_default_stacksize (void)
 {
+	if (default_stacksize == ~0)
+	{
+		unsigned long stacksize = 0;
+
+		const char *value = getenv ("DOTNET_Thread_DefaultStackSize");
```
Comment (akoeplinger) [inline src/mono/mono/metadata/threads.c]: this should use g_getenv

```suggestion
		const char *value = g_getenv ("DOTNET_Thread_DefaultStackSize");
```

File: src/mono/mono/utils/mono-threads-wasm.c [hunk 4]
```diff
@@ -224,37 +224,6 @@ mono_thread_platform_create_thread (MonoThreadStart thread_fn, gpointer thread_d
 	if (res != 0)
 		g_error ("%s: pthread_attr_init failed, error: \"%s\" (%d)", __func__, g_strerror (res), res);
 
-#if 0
```
Comment (akoeplinger) [inline src/mono/mono/utils/mono-threads-wasm.c:227]: this is disabled anyway but I'd prefer keeping and fixing the disabled code so that we don't diverge with mono-threads-posix.c

**Review by akoeplinger — COMMENTED** [review]
LGTM with small comments. please fix the PR description/title

**Comment by tmds** [comment]
I've updated the title/description.

Thanks for reviewing and feedback @akoeplinger and @jkotas!

**Review by akoeplinger — APPROVED** [review]
