### PR TITLE
[browser][coreCLR] async main, thread pool, timers

### LINKED ISSUE #120211: [browser][coreclr] implement C# timers via browser timers
See `SystemJS_ScheduleTimer`

### LINKED ISSUE #120212: [browser][coreclr] implement async main and ST thread pool
It would unlock following features that depend on yielding to browser event loop
- Threadpool
- GC Finalizer
- Timers
- HTTP & WS clients

## implementation notes

- make `BrowserHost_ExecuteAssembly` to yield
- `ICLRRuntimeHost4->ExecuteAssembly(domainId, managedAssemblyPathW, argc, argvW, (DWORD *)exitCode)`
- `src\coreclr\vm\corhost.cpp` - `CorHost2::ExecuteAssembly`
- `src\coreclr\vm\assembly.cpp` - `Assembly::ExecuteMainMethod`
- `RunMain` -> `ValidateMainMethod`, `RunMainInternal`
- 
- `SystemJS_ScheduleBackgroundJob`

```cs
        public static void MainWrapper(string[] args, Func<string[], Task<int>> original, Action<int> resolve, Action<string> reject)
        {
            var task = original(args);

            task.ContinueWith(t =>
            {
                if (t.IsFaulted)
                {
                    reject(t.Exception.Message);
                }
                else
                {
                    resolve(t.Result);
                }
            }, TaskScheduler.Default);
        }
```

https://github.com/dotnet/runtime/blob/3149da88f74c2a014fad0c770618f7102755f8f2/src/libraries/System.Runtime.InteropServices.JavaScript/src/System/Runtime/InteropServices/JavaScript/JSHostImplementation.cs#L208

https://github.com/dotnet/runtime/blob/3149da88f74c2a014fad0c770618f7102755f8f2/src/mono/browser/runtime/corebindings.c#L115

### LINKED ISSUE #121046: [API Proposal]: Provide an async entry point helper to enable platforms that need an async return from `Main()`
### Background and motivation

All .NET main entrypoints are expected to be synchronous. In C# 7.1, the ability to [mark `Main` as `async` was introduced](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.1/async-main.md), but the actual entry point of the .NET assembly remained synchronous. For browser scenarios, the entrypoint must be asynchronous so that the JavaScript message loop can continue to run and handle various requests for browser provided services (for example, I/O).

The proposed API would allow for Roslyn to emit a consistent API call for all scenarios. The runtime implementation would be different based on target and allow for the desired behavior when running in a browser environment.

See https://github.com/dotnet/runtime/pull/120976#discussion_r2453536838 for additional context.

### API Proposal

```diff
namespace System.Runtime.CompilerServices;

[EditorBrowsable(EditorBrowsableState.Never)]
public static partial class AsyncHelpers
{
+    public static void ExecuteAsyncEntryPoint(Task main);
+    public static int ExecuteAsyncEntryPoint(Task<int> main);
}
```

### API Usage

Roslyn would generate the following code for async `Main`.

## `Main` returns `void`
```csharp
static async void Main() { }

// Roslyn generated
static void <Main>(string[] args) => AsyncHelpers.ExecuteAsyncEntryPoint(Main(args));
```

## `Main` returns `int`
```csharp
static async int Main() { return 0; }

// Roslyn generated
static int <Main>(string[] args) => AsyncHelpers.ExecuteAsyncEntryPoint(Main(args));
```

### Alternative Designs

An alternative to this is to embed in the runtime how to determine from the official synchronous entry point the actual user defined asynchronous entrypoint. Given the current generated code by Roslyn the runtime would discover the entrypoint, that is `<Main>`, if the user defined entrypoint was called `Main`, extract the name between the `<>` and look up that name in class.

It is desired to avoid embedding this logic in the runtime, which would limit Roslyn from changing how name mangling of an `async` main entry point is done.

### Risks

_No response_

### PR DESCRIPTION
**Pull request by pavelsavara**
work in progress:
- `-sEXIT_RUNTIME=0` for coreRun too
- don't call `coreclr_shutdown2_func` in coreRun/browserHost
- new `AsyncHelpers.Browser.cs` with
    - `ExecuteAsyncEntryPoint` that would call `SystemJS_RejectMainPromise` or `SystemJS_ResolveMainPromise`
- change `Assembly::GetEntryPoint` to find original async `Main()`
    - the roslyn wrapper contains blocking `TaskAwaiter<int>.GetResult()` which is not possible on ST browser.
    - use `MemberLoader::FindMethodByName` by original name, but ignoring return type
- change `ValidateMainMethod` to allow for signatures with `Task` or `Task<int>`
    - detect new `CorEntryPointType.EntryManagedMainAsync` and `CorEntryPointType.EntryManagedMainAsyncVoid`
- new `SystemJS_ExecuteTimerCallback` and `SystemJS_ExecuteBackgroundJobCallback`
   - ideally this would be `[UnmanagedCallersOnly]`
   - into `src\coreclr\vm\wasm\helpers.cpp` and `src\coreclr\vm\corelib.h` for now

Fixes https://github.com/dotnet/runtime/issues/120212
Fixes https://github.com/dotnet/runtime/issues/120211
Fixes https://github.com/dotnet/runtime/issues/121046

This work with the PR
```cs
public static async Task<int> Main()
{
    Console.WriteLine("Hello, World! " + DateTime.Now);
    await Task.Delay(1000);
    Console.WriteLine("After Task.Delay() " + DateTime.Now);
    return 42;
}
```

### TODO
- [x] implement and test also `Task Main()` of void signature.
- [x] make sure that synchronous main still works
- [x] test exception marshaling
- [x] fix browserHost
- [x] test Release version JS name mangling
- [x] process commandline args

### CODE REVIEW

File: src/coreclr/vm/siginfo.cpp [hunk 1]
```diff
@@ -4549,6 +4549,40 @@ MetaSig::CompareMethodSigs(
...
+MetaSig::CompareMethodSigs(
+    PCCOR_SIGNATURE      pSignature1,
+    DWORD                cSig1,
+    ModuleBase *         pModule1,
+    const Substitution * pSubst1,
+    PCCOR_SIGNATURE      pSignature2,
+    DWORD                cSig2,
+    ModuleBase *         pModule2,
+    const Substitution * pSubst2,
+    BOOL                 skipReturnTypeSig,
```
Comment (jkotas) [inline src/coreclr/vm/siginfo.cpp]: This should be turned into flags instead of passing another bool

File: src/coreclr/vm/corhost.cpp [hunk 2]
```diff
@@ -359,10 +359,12 @@ HRESULT CorHost2::ExecuteAssembly(DWORD dwAppDomainId,
     UNINSTALL_UNWIND_AND_CONTINUE_HANDLER;
     UNINSTALL_UNHANDLED_MANAGED_EXCEPTION_TRAP;
 
+#if !defined(TARGET_BROWSER)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/corhost.cpp]: This shouldn't be needed. The `LOG_EXECUTABLE_ALLOCATOR_STATISTICS` isn't normally set. How was this hit?

File: src/native/libs/System.Native.Browser/libSystem.Native.Browser.footer.js [hunk 3]
```diff
@@ -37,7 +37,10 @@
         for (const exportName of Reflect.ownKeys(exports)) {
             const name = String(exportName);
             if (name === "dotnetInitializeModule") continue;
-            lib[name] = exports[name];
+            const fn = lib[name] = exports[name];
+            if(fn.__deps) {
+                lib[name + "__deps"] = fn.__deps;
+            }
```
Comment (AaronRobinsonMSFT) [inline src/native/libs/System.Native.Browser/libSystem.Native.Browser.footer.js:43]: Why is this needed now?

File: src/native/libs/System.Native.Browser/native/main.ts [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+import { } from "./cross-linked"; // ensure ambient symbols are declared
+
+export function SystemJS_ResolveMainPromise(exitCode:number) {
+    if (dotnetLoaderExports.resolveRunMainPromise) {
+        dotnetLoaderExports.resolveRunMainPromise(exitCode);
+    }
+}
+
+export function SystemJS_RejectMainPromise(reason:any) {
+    // todo UNMARSHAL utf16 LPWSTR
```
Comment (AaronRobinsonMSFT) [inline src/native/libs/System.Native.Browser/native/main.ts]: What does this mean? What are we marshalling?

File: src/native/libs/System.Native.Browser/native/index.ts [hunk 5]
```diff
@@ -6,6 +6,8 @@ import { InternalExchangeIndex } from "../types";
 
 export { SystemJS_RandomBytes } from "./crypto";
 export { SystemJS_GetLocaleInfo } from "./globalization-locale";
+export { SystemJS_RejectMainPromise, SystemJS_ResolveMainPromise } from "./main";
+export { SystemJS_ScheduleTimer, SystemJS_ScheduleBackgroundJob } from "./timer";
```
Comment (AaronRobinsonMSFT) [inline src/native/libs/System.Native.Browser/native/index.ts:10]: I don't see any of these types being used. Why are they needed here?

File: src/native/corehost/browserhost/libBrowserHost.footer.js [hunk 6]
```diff
@@ -68,6 +68,10 @@
             if (name === "dotnetInitializeModule") continue;
             lib[name] = () => "dummy";
             assignExportsBuilder += `_${String(name)} = exports.${String(name)};\n`;
+            const fn = exports[name];
+            if(fn.__deps) {
```
Comment (AaronRobinsonMSFT) [inline src/native/corehost/browserhost/libBrowserHost.footer.js]: Another instance of this, why is this now needed?

File: src/native/corehost/browserhost/CMakeLists.txt [hunk 7]
```diff
@@ -111,8 +111,8 @@ target_link_options(browserhost PRIVATE
     -sMODULARIZE=1
     -sEXPORT_ES6=1
     -sEXIT_RUNTIME=0
-    -sEXPORTED_RUNTIME_METHODS=UTF8ToString,cwrap,ccall,HEAPU8,HEAPU32,HEAPU64,BROWSER_HOST
-    -sEXPORTED_FUNCTIONS=_posix_memalign,_free,stackAlloc,stackRestore,stackSave,_BrowserHost_InitializeCoreCLR,_BrowserHost_ExecuteAssembly,___cpp_exception
+    -sEXPORTED_RUNTIME_METHODS=UTF8ToString,cwrap,ccall,HEAPU8,HEAPU32,HEAPU64,BROWSER_HOST,safeSetTimeout,maybeExit
+    -sEXPORTED_FUNCTIONS=_posix_memalign,_free,stackAlloc,stackRestore,stackSave,___cpp_exception,_GetDotNetRuntimeContractDescriptor,_BrowserHost_InitializeCoreCLR
```
Comment (AaronRobinsonMSFT) [inline src/native/corehost/browserhost/CMakeLists.txt]: Thank you!

File: src/libraries/System.Private.CoreLib/src/System/Threading/TimerQueue.Browser.cs [hunk 8]
```diff
@@ -32,8 +32,13 @@ private TimerQueue(int _)
         }
 
         // This replaces the current pending setTimeout with shorter one
+#if MONO
         [MethodImplAttribute(MethodImplOptions.InternalCall)]
         private static extern unsafe void MainThreadScheduleTimer(void* callback, int shortestDueTimeMs);
+#else
+        [LibraryImport(RuntimeHelpers.QCall, EntryPoint = "SystemJS_ScheduleTimer")]
```
Comment (AaronRobinsonMSFT) [inline src/libraries/System.Private.CoreLib/src/System/Threading/TimerQueue.Browser.cs]: If the names match, there is no need to specify the `EntryPoint`.

File: src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.Browser.cs [hunk 9]
```diff
@@ -115,8 +122,14 @@ private static RegisteredWaitHandle RegisterWaitForSingleObject(
             throw new PlatformNotSupportedException();
         }
 
+
+#if MONO
         [MethodImplAttribute(MethodImplOptions.InternalCall)]
         internal static extern unsafe void MainThreadScheduleBackgroundJob(void* callback);
+#else
+        [LibraryImport(RuntimeHelpers.QCall, EntryPoint = "SystemJS_ScheduleBackgroundJob")]
```
Comment (AaronRobinsonMSFT) [inline src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.Browser.cs]: Remove duplicate `EntryPoint` property.

File: src/coreclr/vm/siginfo.cpp [hunk 10]
```diff
@@ -4579,7 +4613,7 @@ MetaSig::CompareMethodSigs(
         return TRUE;
     }
 
-    if ((*pSig1 & ~CORINFO_CALLCONV_PARAMTYPE) != (*pSig2 & ~CORINFO_CALLCONV_PARAMTYPE))
+    if (!skipCallConv && (*pSig1 & ~CORINFO_CALLCONV_PARAMTYPE) != (*pSig2 & ~CORINFO_CALLCONV_PARAMTYPE))
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/siginfo.cpp]: I would like to understand why the calling convention mismatch is happening. It isn't intuitive to me on why that is the case.

File: src/coreclr/vm/qcallentrypoints.cpp [hunk 11]
```diff
@@ -75,6 +75,11 @@
 
 #include "versionresilienthashcode.h"
 
+#ifdef TARGET_BROWSER
+#include "wasm/wasm-entrypoints.h"
+#endif
+
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/qcallentrypoints.cpp:81]:
```suggestion
```

File: src/coreclr/vm/qcallentrypoints.cpp [hunk 12]
```diff
@@ -75,6 +75,11 @@
 
 #include "versionresilienthashcode.h"
 
+#ifdef TARGET_BROWSER
+#include "wasm/wasm-entrypoints.h"
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/qcallentrypoints.cpp]: This should just be `entrypoints.h` if we are nesting it in a `wasm` subdirectory.

File: src/coreclr/vm/qcallentrypoints.cpp [hunk 13]
```diff
@@ -544,6 +549,12 @@ static const Entry s_QCall[] =
     DllImportEntry(IsInstanceOf_NoCacheLookup)
     DllImportEntry(VersionResilientHashCode_TypeHashCode)
     DllImportEntry(TailCallHelp_AllocTailCallArgBufferInternal)
+#ifdef TARGET_BROWSER
+    DllImportEntry(SystemJS_ResolveMainPromise)
+    DllImportEntry(SystemJS_RejectMainPromise)
+    DllImportEntry(SystemJS_ScheduleTimer)
+    DllImportEntry(SystemJS_ScheduleBackgroundJob)
+#endif
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/qcallentrypoints.cpp]:
```suggestion
#endif // TARGET_BROWSER
```

File: src/coreclr/vm/qcallentrypoints.cpp [hunk 14]
```diff
@@ -75,6 +75,11 @@
 
 #include "versionresilienthashcode.h"
 
+#ifdef TARGET_BROWSER
+#include "wasm/wasm-entrypoints.h"
+#endif
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/qcallentrypoints.cpp]:
```suggestion
#endif // TARGET_BROWSER
```

File: src/coreclr/vm/wasm/helpers.cpp [hunk 15]
```diff
@@ -649,3 +649,19 @@ void InvokeUnmanagedMethod(MethodDesc *targetMethod, int8_t *pArgs, int8_t *pRet
 {
     PORTABILITY_ASSERT("Attempted to execute unmanaged code from interpreter on wasm, this is not yet implemented");
 }
+
+// WASM-TODO: use [UnmanagedCallersOnly] once is supported in wasm
+extern "C" void SystemJS_ExecuteTimerCallback (void)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/wasm/helpers.cpp]:
```suggestion
extern "C" void SystemJS_ExecuteTimerCallback()
```

File: src/coreclr/vm/wasm/helpers.cpp [hunk 16]
```diff
@@ -649,3 +649,19 @@ void InvokeUnmanagedMethod(MethodDesc *targetMethod, int8_t *pArgs, int8_t *pRet
...
+{
+    ARG_SLOT stackVarWrapper[] = { };
+    MethodDescCallSite timerHandler(METHOD__TIMER_QUEUE__TIMER_HANDLER);
+    timerHandler.Call(stackVarWrapper);
+}
+
+// WASM-TODO: use [UnmanagedCallersOnly] once is supported in wasm
+extern "C" void SystemJS_ExecuteBackgroundJobCallback (void)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/wasm/helpers.cpp]:
```suggestion
extern "C" void SystemJS_ExecuteBackgroundJobCallback()
```

File: src/coreclr/vm/wasm/helpers.cpp [hunk 17]
```diff
@@ -649,3 +649,19 @@ void InvokeUnmanagedMethod(MethodDesc *targetMethod, int8_t *pArgs, int8_t *pRet
 {
     PORTABILITY_ASSERT("Attempted to execute unmanaged code from interpreter on wasm, this is not yet implemented");
 }
+
+// WASM-TODO: use [UnmanagedCallersOnly] once is supported in wasm
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/wasm/helpers.cpp:653]: Please file an issue on this.

File: src/coreclr/vm/assembly.cpp [hunk 18]
```diff
@@ -1127,30 +1129,126 @@ void ValidateMainMethod(MethodDesc * pFD, CorEntryPointType *pType)
...
          ThrowMainMethodException(pFD, IDS_EE_MAIN_METHOD_HAS_INVALID_RTN);
 
     if (nParamCount == 0)
+    {
         *pType = EntryCrtMain;
-    else {
-        *pType = EntryManagedMain;
+        return;
+    }
+#else
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
#else // TARGET_BROWSER
```

File: src/coreclr/vm/assembly.cpp [hunk 19]
```diff
@@ -1127,30 +1129,126 @@ void ValidateMainMethod(MethodDesc * pFD, CorEntryPointType *pType)
...
+    // validate that the return type is Task or Task<int>
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
    // Early check for the common main return types.
```

File: src/coreclr/vm/assembly.cpp [hunk 20]
```diff
@@ -1127,30 +1129,126 @@ void ValidateMainMethod(MethodDesc * pFD, CorEntryPointType *pType)
...
+            if (FAILED(pImport->GetNameOfTypeRef(tk, &nameSpace, &name)))
                 ThrowMainMethodException(pFD, BFA_BAD_SIGNATURE);
+        }
+        else
+        {
+            ThrowMainMethodException(pFD, IDS_EE_MAIN_METHOD_HAS_INVALID_RTN);
+        }
+
+        // Verify it's Task`1
+        if (strcmp(name, "Task`1") != 0 || strcmp(nameSpace, "System.Threading.Tasks") != 0)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]: This approach means anyone can define their own `Task<T>` in their own namespace of `System.Threading.Tasks` and it will work. That is fine, but we should be make a note here. One could also verify the associated module is SPCL and that would provide the additional verification.

File: src/coreclr/vm/assembly.cpp [hunk 21]
```diff
@@ -1127,30 +1129,126 @@ void ValidateMainMethod(MethodDesc * pFD, CorEntryPointType *pType)
...
+            ThrowMainMethodException(pFD, IDS_EE_MAIN_METHOD_HAS_INVALID_RTN);
+
+        *pType = EntryManagedMainAsyncVoid;
+        return;
+    }
+#endif // !TARGET_BROWSER
+
+    *pType = EntryManagedMain;
+
+    if (nParamCount != 1)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]: I don't see the zero case handled for the browser. Are we requiring an argument for WASM scenarios?

File: src/coreclr/vm/assembly.cpp [hunk 22]
```diff
@@ -1172,7 +1270,10 @@ static void RunMainInternal(Param* pParam)
     GCPROTECT_BEGIN(StrArgArray);
 
     // Build the parameter array and invoke the method.
-    if (pParam->EntryType == EntryManagedMain) {
+    if (pParam->EntryType == EntryManagedMain
+        || pParam->EntryType == EntryManagedMainAsync
+        || pParam->EntryType == EntryManagedMainAsyncVoid
+        ) {
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
        || pParam->EntryType == EntryManagedMainAsyncVoid)
    {
```

File: src/coreclr/vm/assembly.cpp [hunk 23]
```diff
@@ -1197,8 +1298,38 @@ static void RunMainInternal(Param* pParam)
     }
     else
     {
-        *pParam->piRetVal = (INT32)threadStart.Call_RetArgSlot(&stackVar);
-        SetLatchedExitCode(*pParam->piRetVal);
+#if !defined(TARGET_BROWSER)
+        if(pParam->EntryType == EntryManagedMainAsync)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
        if (pParam->EntryType == EntryManagedMainAsync)
```

File: src/coreclr/vm/assembly.cpp [hunk 24]
```diff
@@ -1197,8 +1298,38 @@ static void RunMainInternal(Param* pParam)
     }
     else
     {
-        *pParam->piRetVal = (INT32)threadStart.Call_RetArgSlot(&stackVar);
-        SetLatchedExitCode(*pParam->piRetVal);
+#if !defined(TARGET_BROWSER)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
#if defined(TARGET_BROWSER)
```

Isn't this path for the browser case?

File: src/coreclr/vm/assembly.cpp [hunk 25]
```diff
@@ -1197,8 +1298,38 @@ static void RunMainInternal(Param* pParam)
...
+            OBJECTREF exitCodeTask = threadStart.Call_RetOBJECTREF(&stackVar);
+            ARG_SLOT stackVarWrapper[] =
+            {
+                ObjToArgSlot(exitCodeTask)
+            };
+
+            MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__MAIN_WRAPPER);
+            mainWrapper.Call(stackVarWrapper);
+        }
+        else if(pParam->EntryType == EntryManagedMainAsyncVoid)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
        else if (pParam->EntryType == EntryManagedMainAsyncVoid)
```

File: src/coreclr/vm/assembly.cpp [hunk 26]
```diff
@@ -1197,8 +1298,38 @@ static void RunMainInternal(Param* pParam)
...
+            ARG_SLOT stackVarWrapper[] =
+            {
+                ObjToArgSlot(exitCodeTask)
+            };
+
+            MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__MAIN_WRAPPER_VOID);
+            mainWrapper.Call(stackVarWrapper);
+        }
+        else
+#endif // !TARGET_BROWSER
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
#endif // TARGET_BROWSER
```

File: src/coreclr/vm/assembly.cpp [hunk 27]
```diff
@@ -1499,8 +1635,52 @@ MethodDesc* Assembly::GetEntryPoint()
     }
     else
     {
+#if defined(TARGET_BROWSER)
+        // we only support IL entrypoints in browser
+        COMPlusThrowHR(COR_E_BADIMAGEFORMAT);
+#endif // TARGET_BROWSER
         m_pEntryPoint = pModule->FindMethod(mdEntry);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
#if defined(TARGET_BROWSER)
        // we only support IL entrypoints in browser
        COMPlusThrowHR(COR_E_BADIMAGEFORMAT);
#else // !TARGET_BROWSER
        m_pEntryPoint = pModule->FindMethod(mdEntry);
#endif // TARGET_BROWSER
```

File: src/coreclr/vm/assembly.cpp [hunk 28]
```diff
@@ -1499,8 +1635,52 @@ MethodDesc* Assembly::GetEntryPoint()
...
     }
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp:1563]:
```suggestion
    }
    _ASSERTE(m_pEntryPoint != NULL);
```

File: src/coreclr/vm/assembly.cpp [hunk 29]
```diff
@@ -1499,8 +1635,52 @@ MethodDesc* Assembly::GetEntryPoint()
...
+#if defined(TARGET_BROWSER)
+    // if this is async method we need to find the original method, instead of the roslyn generated wrapper
+    if (m_pEntryPoint) {
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
    if (m_pEntryPoint)
    {
```

File: src/coreclr/vm/assembly.cpp [hunk 30]
```diff
@@ -1499,8 +1635,52 @@ MethodDesc* Assembly::GetEntryPoint()
...
     else
     {
+#if defined(TARGET_BROWSER)
+        // we only support IL entrypoints in browser
+        COMPlusThrowHR(COR_E_BADIMAGEFORMAT);
+#endif // TARGET_BROWSER
         m_pEntryPoint = pModule->FindMethod(mdEntry);
     }
+#if defined(TARGET_BROWSER)
+    // if this is async method we need to find the original method, instead of the roslyn generated wrapper
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]: We shouldn't be trying to reverse engineer the output of the Roslyn compiler without having a conversation with them. Please reach out to @jaredpar and @333fred to discuss what we can/can't assume in this area. At a minimum we need to agree on a contract here. This approach, without them in the conversation, is a no go.

Comment (333fred) [reply src/coreclr/vm/assembly.cpp]: What's the goal here?

Comment (jkotas) [reply src/coreclr/vm/assembly.cpp]: Historically, Mono support for Wasm has a dependency on implementation details of async Main wrapper generated by Roslyn. It needs to unwrap the wrapper, find the actual async Main and call it in different way.

This PR is replicating this logic in CoreCLR. It is not really making the situation worse.

The question is whether we are happy with this dependency or whether we want to do something better.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/assembly.cpp]: > The question is whether we are happy with this dependency or whether we want to do something better.

Agree. I _think_ this might be my fault on some guidance I provided a while ago. I personally do not like this now that I see it, sorry @pavelsavara. Let's sync and discuss options.

@333fred The issue here is the entry point that Roslyn defines when the `Main()` is marked `async` isn't callable from WASM (that is, it makes the entry point synchronous). What WASM needs is to call the entry point that is actually asynchronous because we need to return to the JavaScript message loop or else the message queue isn't going to ever move. This is bad for a myriad of reasons. The approach being taken here is to rely on knowledge of how Roslyn generates symbols for the `async` entry point and call the one that returns a `Task`. Naively one could imagine the following approach

```
async Task Main(string[] args) { }

// Generated by some tool
async Task WasmMain(string args) => await Main(args);
```

`Main()` would be treated by Roslyn as the entry point, but set the currently defined `<Main>` "mangled" name as the entry point in the assembly. This would continue to ensure the .NET entry point is synchronous and the runtime or some other alchemy could "discover" the actual asynchronous entry point, `WasmMain`.

I personally don't like rummaging around trying to parse Roslyn generated names. I think it also helped me understand why we have a new "ignore calling conventions" flags.

Comment (333fred) [reply src/coreclr/vm/assembly.cpp]: I assume this is only an issue in top-level statements? Since in the standard form, `Main` isn't mangled in any fashion?

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/assembly.cpp]: > I assume this is only an issue in top-level statements? Since in the standard form, `Main` isn't mangled in any fashion?

No, this is the same in the class form as well. At least with what I was testing (that is, .NET 9).

The `Main()` exists, but the entrypoint is the sync version which is called `<Main>()`.

Comment (333fred) [reply src/coreclr/vm/assembly.cpp]: > The Main() exists, but the entrypoint is the sync version which is called <Main>().

Right, but my point is that there's no guessing as to the naming convention in this case. Am I missing something?

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/assembly.cpp]: The convention is the name is wrapped in `<>`. Which means it could be `<Foo>` and then that reduces to `Foo`. My concern is we will be baking into the runtime that the convention will always be the user written entry point name will always be wrapped in `<>` and that won't change. That doesn't seem like a guarantee that Roslyn wants to provide, but I could be wrong.

Comment (jkotas) [reply src/coreclr/vm/assembly.cpp]: I can think about a few different ways how to make this much cleaner. The simplest one is to Introduce a new API that Roslyn would use to await the result of async Main instead of what it generates today. The synhetized Main would become `static int <Main>() => AsyncHelpers.AwaitMain(Main(args))`. Wasm runtime can run the message loop in `AwaitMain`. @pavelsavara Would that work?

> Generated by some tool

If we want to avoid dependency on Roslyn naming conventions, this needs to be handled inside Roslyn. Otherwise, we would be just moving the dependency from the runtime to some tool that's not an improvement.

In any case, this should not block this PR.

Comment (333fred) [reply src/coreclr/vm/assembly.cpp]: > The synhetized Main would become `static int <Main>() => AsyncHelpers.AwaitMain(Main(args))`

That seems reasonable from the roslyn side.

Comment (pavelsavara) [reply src/coreclr/vm/assembly.cpp]: > I think this might be my fault on some guidance I provided a while ago.

No, I knew what I'm replicating when I asked you few weeks ago. And I'm OK with this being end to end POC.
I'm also happy that this gave me opportunity to learn about signatures in coreCLR.

> I personally don't like rummaging around trying to parse Roslyn generated names. 

Same here. 
Note approach this has one benefit: It's backward compatible, it can execute existing assemblies.

> I think it also helped me understand why we have a new "ignore calling conventions" flags.

Yes. There is possibly alternate strategy, we could build expected signature from scratch or copy and modify what we got from wrapped Main. There is some signature "compression" which I didn't understand so I avoided it.

> The synthesized Main would become `static int <Main>() => AsyncHelpers.AwaitMain(Main(args))`. 
> Wasm runtime can run the message loop in AwaitMain. Would that work?

The WASM version needs to yield (synchronously return to browser) at first await. That means it can't return real `int` exit code.
It can return arbitrary dummy value on WASM.

The implementation of `AsyncHelpers.AwaitMain` on wasm would be same as `AsyncHelpers.MainWrapper` in this PR. Essentially `ContinueWith` registration and immediate synchronous return. It would not loop there.

> The simplest one is to Introduce a new API that Roslyn would use.

How would the main wrapper look like for asyncV2 assemblies ?

Maybe the Roslyn main wrapper is just a legacy pattern.
Perhaps the whole wrapper could disappear and it would become completely runtime problem.

That is runtime/host would
- block the thread as it does today for multi-threaded runtimes
- yield - for single threaded runtimes (WASM)

Such approach would not even need new API.

> It is not really making the situation worse.

Doing Roslyn change would create blocking dependency on
- API review
- Roslyn change
- Code flow from Roslyn

Without async main, almost nothing works in browser. 
So I would rather make this "future improvement".

File: src/coreclr/vm/wasm/helpers.cpp (hunk 17 above)
Comment (pavelsavara) [reply src/coreclr/vm/wasm/helpers.cpp:653]: https://github.com/dotnet/runtime/issues/121006

File: src/coreclr/vm/corhost.cpp (hunk 2 above)
Comment (pavelsavara) [reply src/coreclr/vm/corhost.cpp]: reverted

File: src/native/libs/System.Native.Browser/libSystem.Native.Browser.footer.js (hunk 3 above)
Comment (pavelsavara) [reply src/native/libs/System.Native.Browser/libSystem.Native.Browser.footer.js:43]: So that the C or JS symbol I call from inside of the JS method is not trimmed by the emcc linker.
Note that emcc doesn't really parse the JS code.

in `src\native\libs\System.Native.Browser\native\timer.ts` I use the function as property bag.
I put `SystemJS_ScheduleTimer["__deps"] = ['SystemJS_ExecuteTimerCallback'];`
And here I'm lifting it into "library" level, which is what the `autoAddDeps` expects.

I still need to test that this works even with JS name mangling in Release configuration.

see also https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#javascript-limits-in-library-files

File: src/native/libs/System.Native.Browser/native/main.ts (hunk 4 above)
Comment (pavelsavara) [reply src/native/libs/System.Native.Browser/native/main.ts]: `reason` here arrives as JS `number` which is a pointer/offset into WASM linear memory. 
It points to the UTF16 buffer of a C# string with the stack trace. 
Here we need to convert it into JS `string` type and wrap it with JS `Error` instance.

https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/decode
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

File: src/native/libs/System.Native.Browser/native/index.ts (hunk 5 above)
Comment (pavelsavara) [reply src/native/libs/System.Native.Browser/native/index.ts:10]: note this is `export` which makes it visible outside of JS module (file).
Later we enumerate those in `libSystem.Native.Browser.footer.js` and feed them to emcc linker as a "library".

File: src/native/corehost/browserhost/libBrowserHost.footer.js (hunk 6 above)
Comment (pavelsavara) [reply src/native/corehost/browserhost/libBrowserHost.footer.js]: Previously I used `-sEXPORTED_FUNCTIONS` and `Module.ccall` and I found this is better way.
This way, we are not leaking that internal symbols out of the dotnet.native.js inner namespace.

File: src/coreclr/vm/siginfo.cpp (hunk 10 above)
Comment (pavelsavara) [reply src/coreclr/vm/siginfo.cpp]: I don't know either. I know why return type is different.

File: src/coreclr/vm/assembly.cpp (hunk 20 above)
Comment (pavelsavara) [reply src/coreclr/vm/assembly.cpp]: Well, this is 50+25 lines of defensive code, just to abort if something unexpected happened. 
I generated this with copilot to quickly unblock myself. 
I hope there is simpler way how to check the type ?

File: src/coreclr/vm/assembly.cpp (hunk 30 above)
Comment (333fred) [reply src/coreclr/vm/assembly.cpp]: > How would the main wrapper look like for asyncV2 assemblies

As of right now, no different, since the asyncV2 only applies to Task/ValueTask returning methods, and the real Main is either void or int returning.

File: src/coreclr/vm/assembly.cpp (hunk 20 above)
Comment (jkotas) [reply src/coreclr/vm/assembly.cpp]: I think we should open an issue to get this cleaned up using the new API or in some other way, and put all the relevant code under `#ifdef TARGET_BROWSER // Delete once ... is fixed` and do a minimal unpolished logic necessary to unblock progress.

File: src/coreclr/vm/assembly.cpp (hunk 30 above)
Comment (jkotas) [reply src/coreclr/vm/assembly.cpp]: > The implementation of AsyncHelpers.AwaitMain on wasm would be same as AsyncHelpers.MainWrapper in this PR.

Sounds good.

> > How would the main wrapper look like for asyncV2 assemblies

> As of right now, no different

Right, there are no plans to change how async main works with asyncV2.

> It's backward compatible, it can execute existing assemblies.

This is not important. It is fine to require wasm app recompilation to run on new major runtime version.

File: src/coreclr/vm/assembly.cpp (hunk 20 above)
Comment (jkotas) [reply src/coreclr/vm/assembly.cpp]: > minimal unpolished logic necessary to unblock progress

The minimal unpolished logic does not need to have defensive checks, etc. It can just find the method by name without checking signature.

File: src/coreclr/vm/assembly.cpp (hunk 30 above)
Comment (333fred) [reply src/coreclr/vm/assembly.cpp]: > Right, there are no plans to change how async main works with asyncV2.

I'm not advocating for this, but another potential option we could consider here is to allow `.entrypoint` on `Task` or `ValueTask` returning methods, and have the runtime be responsible for invoking it asyncronously/waiting for the result. Then the WASM runtime could directly locate the entrypoint and do whatever it wants.

Comment (jkotas) [reply src/coreclr/vm/assembly.cpp]: > another potential option we could consider here is to allow .entrypoint on Task or ValueTask returning methods

Yes, this is potential option. It is more breaking. Code (e.g. tools and libraries) that inspects entrypoint and expects it to be in certain shapes would have to learn about the new shape. Example of such code in this repo: https://github.com/dotnet/runtime/blob/f3c990f1644836bbb892cadcb4e0d9230d01c150/src/libraries/System.Private.CoreLib/src/System/AppDomain.cs#L136-L146

Comment (333fred) [reply src/coreclr/vm/assembly.cpp]: > It is more breaking. Code (e.g. tools and libraries) that inspects entrypoint and expects it to be in certain shapes would have to learn about the new shape.

Yep, definitely. Just wanted to make sure that we're considering all the options available to us here.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/assembly.cpp]: > > The synhetized Main would become `static int <Main>() => AsyncHelpers.AwaitMain(Main(args))`
> 
> That seems reasonable from the roslyn side.

API proposal https://github.com/dotnet/runtime/issues/121046

File: src/coreclr/vm/assembly.cpp (hunk 20 above)
Comment (pavelsavara) [reply src/coreclr/vm/assembly.cpp]: I created https://github.com/dotnet/runtime/issues/121064 and will put it there as TODO

File: src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.Browser.cs [hunk 31]
```diff
@@ -0,0 +1,63 @@
...
+using System.Runtime.InteropServices;
+using System.Threading.Tasks;
+
+namespace System.Runtime.CompilerServices
+{
+    public static partial class AsyncHelpers
+    {
+        [DynamicDependency(nameof(MainWrapper))]
+        [DynamicDependency(nameof(MainWrapperVoid))]
+        static AsyncHelpers()
```
Comment (jkotas) [inline src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.Browser.cs]: Empty explicit static constructor adds overhead to all static methods on the type. Why is this needed?

File: src/coreclr/vm/memberload.cpp [hunk 32]
```diff
@@ -1033,7 +1033,9 @@ static BOOL CompareMethodSigWithCorrectSubstitution(
             ModuleBase* pModule,
             MethodDesc *pCurDeclMD,
             const Substitution *pDefSubst,
-            MethodTable *pCurMT
+            MethodTable *pCurMT,
+            bool ignoreReturnType = false,
```
Comment (jkotas) [inline src/coreclr/vm/memberload.cpp]: If we plan to clean this up, we may want to do a simple match via name only and revert these changes.

Comment (pavelsavara) [reply src/coreclr/vm/memberload.cpp]: Thanks, I will try that. We were also discussing constructing the exact expected signatures from scratch.

File: src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.Browser.cs (hunk 31 above)
Comment (pavelsavara) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.Browser.cs]: Just quick hack to have something that can have `DynamicDependency` on it. 
It could be moved on any other SPC method that survives IL trimming on browser. Do you have a preference ?

Comment (jkotas) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.Browser.cs]: Why is this needed in the first place? What is going to break if you delete this static cctor and `DynamicDependency` attributes?

Comment (pavelsavara) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.Browser.cs]: Those managed methods would be IL trimmed and then not found when I want to call them from C. See `METHOD__ASYNC_HELPERS__MAIN_WRAPPER` on this PR

Comment (jkotas) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.Browser.cs]: The trimmer keeps all methods that are referenced from C code using `METHOD_...` alive. There is a special build tooling around this in CoreCLR build: https://github.com/dotnet/runtime/blob/main/src/coreclr/System.Private.CoreLib/CreateRuntimeRootILLinkDescriptorFile.targets#L24-L48

Comment (pavelsavara) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.Browser.cs]: thanks, `#if defined(TARGET_BROWSER)`->`#ifdef TARGET_BROWSER` fixed it

File: src/coreclr/vm/assembly.cpp (hunk 21 above)
Comment (pavelsavara) [reply src/coreclr/vm/assembly.cpp]: fixed

File: src/coreclr/vm/memberload.cpp (hunk 32 above)
Comment (pavelsavara) [reply src/coreclr/vm/memberload.cpp]: done, simplest possible way

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs [hunk 33]
```diff
@@ -237,5 +237,65 @@ public static T Await<T>(ConfiguredValueTaskAwaitable<T> configuredAwaitable)
         [RequiresPreviewFeatures]
         public static T Await<T>(System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<T> configuredAwaitable) { throw new NotImplementedException(); }
 #endif
+
+#if !TARGET_BROWSER
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs]: We generally prefer to split such methods across files, e.g. AsyncHelpers.browser.cs.

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs [hunk 34]
```diff
@@ -237,5 +237,65 @@ public static T Await<T>(ConfiguredValueTaskAwaitable<T> configuredAwaitable)
...
+        public static int HandleAsyncEntryPoint(Task<int> task)
+        {
+            return task.GetAwaiter().GetResult();
+        }
+#else
+        public static void HandleAsyncEntryPoint(Task task)
+        {
+            task.ContinueWith(t =>
+            {
+                if (t.IsFaulted)
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs]: What if it's canceled?

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs [hunk 35]
```diff
@@ -237,5 +237,65 @@ public static T Await<T>(ConfiguredValueTaskAwaitable<T> configuredAwaitable)
...
+                {
+                    RejectMainPromise(t.Exception);
+                }
+                else
+                {
+                    SystemJS_ResolveMainPromise(t.Result);
+                }
+            }, TaskScheduler.Default);
+            // dummy exit code, real exit code will be passed via SystemJS_ResolveMainPromise
+            return 0;
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs]: Should this return something other than a success code?

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs [hunk 36]
```diff
@@ -237,5 +237,65 @@ public static T Await<T>(ConfiguredValueTaskAwaitable<T> configuredAwaitable)
...
+        }
+
+        private static void RejectMainPromise(Exception ex)
+        {
+            var inner= ex.InnerException ?? ex;
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs]:
```suggestion
            var inner = ex.InnerException ?? ex;
```

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs [hunk 37]
```diff
@@ -237,5 +237,65 @@ public static T Await<T>(ConfiguredValueTaskAwaitable<T> configuredAwaitable)
...
+            var message = inner.GetType().Name + ": " + (inner.Message ?? "");
+            var stackTrace = inner.StackTrace ?? "";
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs]: For all of these we'd prefer to use the explicit type rather than var

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs (hunk 35 above)
Comment (pavelsavara) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs]: It doesn't matter. It's ignored by the caller for browser. I can change it to -123 or something in case someone calls this by mistake

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs (hunk 34 above)
Comment (pavelsavara) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.cs]: thanks, I will reject the JS promise

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs
Comment (AaronRobinsonMSFT) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs:1]: This should just be called `AsyncHelpers.cs`. The `NonBrowser` approach is a bit wonky. I would instead fold this into the existing `AsyncHelpers.cs` and define them out there. I'm saying that because this is the common case can just be folded into the main file people will see.

Comment (jkotas) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs:1]: This was done to address https://github.com/dotnet/runtime/pull/120976#discussion_r2473012285

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs [hunk 38]
```diff
@@ -0,0 +1,20 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Threading.Tasks;
+
+namespace System.Runtime.CompilerServices
+{
+    public static partial class AsyncHelpers
+    {
+        public static void HandleAsyncEntryPoint(Task task)
```
Comment (jkotas) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs:18]: This needs docs comment that official docs will be eventually generated from.

File: src/libraries/System.Runtime/ref/System.Runtime.cs [hunk 39]
```diff
@@ -14172,6 +14172,8 @@ public static void AwaitAwaiter<TAwaiter>(TAwaiter awaiter) where TAwaiter : INo
         public static T Await<T>(System.Runtime.CompilerServices.ConfiguredTaskAwaitable<T> configuredAwaitable) { throw null; }
         [System.Runtime.Versioning.RequiresPreviewFeaturesAttribute]
         public static T Await<T>(System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<T> configuredAwaitable) { throw null; }
+        public static void HandleAsyncEntryPoint(System.Threading.Tasks.Task task) { throw null; }
```
Comment (jkotas) [inline src/libraries/System.Runtime/ref/System.Runtime.cs]:
```suggestion
        public static void HandleAsyncEntryPoint(System.Threading.Tasks.Task task) { }
```

File: src/coreclr/vm/assembly.cpp [hunk 40]
```diff
@@ -1197,8 +1225,40 @@ static void RunMainInternal(Param* pParam)
...
+            mainWrapper.Call(stackVarWrapper);
+        }
+        else
+#endif // TARGET_BROWSER
+        {
+            // Call the main method
+            *pParam->piRetVal = (INT32)threadStart.Call_RetArgSlot(&stackVar);
+            SetLatchedExitCode(*pParam->piRetVal);
+        }
     }
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
// WASM-TODO: remove this
// https://github.com/dotnet/runtime/issues/121064
#if defined(TARGET_BROWSER)
else if (pParam->EntryType == EntryManagedMainAsync)
{
    *pParam->piRetVal = 0;
    OBJECTREF exitCodeTask = threadStart.Call_RetOBJECTREF(&stackVar);
    ARG_SLOT stackVarWrapper[] =
    {
        ObjToArgSlot(exitCodeTask)
    };

    MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__HANDLE_ASYNC_ENTRYPOINT);
    mainWrapper.Call(stackVarWrapper);
}
else if (pParam->EntryType == EntryManagedMainAsyncVoid)
{
    *pParam->piRetVal = 0;
    OBJECTREF exitCodeTask = threadStart.Call_RetOBJECTREF(&stackVar);
    ARG_SLOT stackVarWrapper[] =
    {
        ObjToArgSlot(exitCodeTask)
    };

    MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__HANDLE_ASYNC_ENTRYPOINT_VOID);
    mainWrapper.Call(stackVarWrapper);
}
#endif // TARGET_BROWSER
else
{
        // Call the main method
        *pParam->piRetVal = (INT32)threadStart.Call_RetArgSlot(&stackVar);
        SetLatchedExitCode(*pParam->piRetVal);
}
```

File: src/coreclr/vm/assembly.cpp [hunk 41]
```diff
@@ -1392,7 +1452,9 @@ INT32 Assembly::ExecuteMainMethod(PTRARRAYREF *stringArgs, BOOL waitForOtherThre
 
             hr = RunMain(pMeth, 1, &iRetVal, stringArgs);
 
+#if !defined(TARGET_BROWSER)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]: Why is this defined away? This should be a nop on system where Objective-C isn't enabled. Was this causing issues?

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/assembly.cpp]: Is this because `RunMain` returns without exiting on browser? If so, that deserves a comment. Just defining it away is confusing.

File: src/coreclr/vm/assembly.cpp [hunk 42]
```diff
@@ -1499,8 +1564,42 @@ MethodDesc* Assembly::GetEntryPoint()
     }
     else
     {
+#if defined(TARGET_BROWSER)
+        // we only support IL entrypoints in browser
+        COMPlusThrowHR(COR_E_BADIMAGEFORMAT);
+#else // !TARGET_BROWSER
```
Comment (jkotas) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
```
This ifdef should not be needed. The path handles global function IL entrypoint - the comment is misleading. 

You cannot generate these using C#, so this path is probably not going to be reached in practice. We may have some tests that hit it.

File: src/coreclr/vm/assembly.cpp (hunk 41 above)
Comment (pavelsavara) [reply src/coreclr/vm/assembly.cpp]: Yes, we want the thread to keep "attached". I will add comment

File: src/coreclr/vm/assembly.cpp [hunk 43]
```diff
@@ -1392,7 +1449,11 @@ INT32 Assembly::ExecuteMainMethod(PTRARRAYREF *stringArgs, BOOL waitForOtherThre
 
             hr = RunMain(pMeth, 1, &iRetVal, stringArgs);
 
+// Keep the thread attached, because in the browser we keep the runtime alive.
```
Comment (jkotas) [inline src/coreclr/vm/assembly.cpp]: `CleanUpForManagedThreadInNative` is not detaching anything. It is doing Apple-specific per-workitem cleanup. The same cleanup is done on thread pool after each workitem executes (see `DispatchItemWithAutoreleasePool`).

This comment should be deleted. The BROWSER ifdef is unnecessary - it is ifdefing a call to a empty function that the compiler should have no problem optimizing out - so it can be deleted too.

**Comment by pavelsavara** [comment]
is there more feedback ?

File: src/coreclr/vm/assembly.cpp [hunk 44]
```diff
@@ -1195,8 +1223,41 @@ static void RunMainInternal(Param* pParam)
...
+
+        MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__HANDLE_ASYNC_ENTRYPOINT);
+        mainWrapper.Call(stackVarWrapper);
+        GCPROTECT_END();
+    }
+    else if (pParam->EntryType == EntryManagedMainAsyncVoid)
+    {
+        *pParam->piRetVal = 0;
+        OBJECTREF exitCodeTask = threadStart.Call_RetOBJECTREF(&stackVar);
+        GCPROTECT_BEGIN(exitCodeTask)
```
Comment (jkotas) [inline src/coreclr/vm/assembly.cpp]: This GCPROTECT is unnecessary. These is nothing that triggers GC between this line and the line below that stores the reference into ARG_SLOT array.

Comment (pavelsavara) [reply src/coreclr/vm/assembly.cpp]: What makes the ARG_SLOT visible to GC ?

Comment (jkotas) [reply src/coreclr/vm/assembly.cpp]: If you run into problems with this, it is because the value in the ARG_SLOT array is unprotected. The right fix that is to move `MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__HANDLE_ASYNC_ENTRYPOINT_VOID);` line up before you create ARG_SLOT array.

MethodDescCallSite is GC triggers, so you need to protect all GC references when it is called.

If you move it to be right before `*pParam->piRetVal = 0;`, the GC_PROTECT is unnecessary.

File: src/coreclr/vm/assembly.cpp [hunk 45]
```diff
@@ -1195,8 +1223,41 @@ static void RunMainInternal(Param* pParam)
...
         threadStart.Call(&stackVar);
     }
+// WASM-TODO: remove this
+// https://github.com/dotnet/runtime/issues/121064
+#if defined(TARGET_BROWSER)
+    else if (pParam->EntryType == EntryManagedMainAsync)
+    {
+        *pParam->piRetVal = 0;
+        OBJECTREF exitCodeTask = threadStart.Call_RetOBJECTREF(&stackVar);
+        GCPROTECT_BEGIN(exitCodeTask)
```
Comment (jkotas) [inline src/coreclr/vm/assembly.cpp]: Dtto

File: src/coreclr/vm/assembly.cpp (hunk 44 above)
Comment (pavelsavara) [reply src/coreclr/vm/assembly.cpp]: > If you run into problems with this, it is because the value in the ARG_SLOT array is unprotected. 

I don't have any evidence this is actual issue. I'm just learning how this works.

I understand that moving `MethodDescCallSite mainWrapper` helps to avoid it's allocation, but I think it doesn't help with 
`mainWrapper.Call(stackVarWrapper);` which is invoking user managed code, so it can also trigger GC.

File: src/coreclr/vm/assembly.cpp [hunk 46]
```diff
@@ -1195,8 +1223,41 @@ static void RunMainInternal(Param* pParam)
...
+        ARG_SLOT stackVarWrapper[] =
+        {
+            ObjToArgSlot(exitCodeTask)
+        };
+
+        MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__HANDLE_ASYNC_ENTRYPOINT);
+        mainWrapper.Call(stackVarWrapper);
+        GCPROTECT_END();
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
        *pParam->piRetVal = 0;
        MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__HANDLE_ASYNC_ENTRYPOINT);
        
        OBJECTREF exitCodeTask = threadStart.Call_RetOBJECTREF(&stackVar);
        ARG_SLOT stackVarWrapper[] =
        {
            ObjToArgSlot(exitCodeTask)
        };
        mainWrapper.Call(stackVarWrapper);
```

File: src/coreclr/vm/assembly.cpp [hunk 47]
```diff
@@ -1195,8 +1223,41 @@ static void RunMainInternal(Param* pParam)
...
+        OBJECTREF exitCodeTask = threadStart.Call_RetOBJECTREF(&stackVar);
+        GCPROTECT_BEGIN(exitCodeTask)
+        ARG_SLOT stackVarWrapper[] =
+        {
+            ObjToArgSlot(exitCodeTask)
+        };
+
+        MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__HANDLE_ASYNC_ENTRYPOINT_VOID);
+        mainWrapper.Call(stackVarWrapper);
+        GCPROTECT_END();
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
        *pParam->piRetVal = 0;
        MethodDescCallSite mainWrapper(METHOD__ASYNC_HELPERS__HANDLE_ASYNC_ENTRYPOINT_VOID);
        
        OBJECTREF exitCodeTask = threadStart.Call_RetOBJECTREF(&stackVar);
        ARG_SLOT stackVarWrapper[] =
        {
            ObjToArgSlot(exitCodeTask)
        };
        mainWrapper.Call(stackVarWrapper);
```

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs [hunk 48]
```diff
@@ -0,0 +1,32 @@
...
+using System.Threading.Tasks;
+
+namespace System.Runtime.CompilerServices
+{
+    public static partial class AsyncHelpers
+    {
+        /// <summary>
+        /// This method is intended to be used by Roslyn-generated async entry point.
+        /// On multi-threaded environments, it would block and await the specified task and return when the task has completed.
+        /// On single-threaded environments (e.g., browser), it would register a continuation and yield to the browser event loop immediately.
```
Comment (AaronRobinsonMSFT) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs]:
```suggestion
        /// On single-threaded environments (for example, browser), it would register a continuation and yield to the browser event loop immediately.
```

https://learn.microsoft.com/style-guide/a-z-word-list-term-collections/e/eg same for https://learn.microsoft.com/style-guide/a-z-word-list-term-collections/i/ie

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs [hunk 49]
```diff
@@ -0,0 +1,32 @@
...
+
+using System.Threading.Tasks;
+
+namespace System.Runtime.CompilerServices
+{
+    public static partial class AsyncHelpers
+    {
+        /// <summary>
+        /// This method is intended to be used by Roslyn-generated async entry point.
+        /// On multi-threaded environments, it would block and await the specified task and return when the task has completed.
```
Comment (AaronRobinsonMSFT) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs]:
```suggestion
        /// On multi-threaded environments, it will block and await the specified task, returning when the task has completed.
```

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs [hunk 50]
```diff
@@ -0,0 +1,32 @@
...
+        /// </summary>
+        /// <param name="task">The result from the main entrypoint to await.</param>
+        public static void HandleAsyncEntryPoint(Task task)
+        {
+            task.GetAwaiter().GetResult();
+        }
+
+        /// <summary>
+        /// This method is intended to be used by Roslyn-generated async entry point.
+        /// On multi-threaded environments, it would block and await the specified task and return when the task has completed.
```
Comment (AaronRobinsonMSFT) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs]:
```suggestion
        /// On multi-threaded environments, it will block and await the specified task, returning when the task has completed.
```

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs
Comment (AaronRobinsonMSFT) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs:1]: @gewarren Please help with documentation phrasing here.

File: src/coreclr/vm/assembly.cpp (hunk 44 above)
Comment (pavelsavara) [reply src/coreclr/vm/assembly.cpp]: Could you please explain what protects `ARG_SLOT` from `mainWrapper.Call`, thank you

Comment (pavelsavara) [reply src/coreclr/vm/assembly.cpp]: spoke to Aaron offline and now I understand

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs [hunk 51]
```diff
@@ -0,0 +1,32 @@
...
+namespace System.Runtime.CompilerServices
+{
+    public static partial class AsyncHelpers
+    {
+        /// <summary>
+        /// This method is intended to be used by Roslyn-generated async entry point.
+        /// On multi-threaded environments, it would block and await the specified task and return when the task has completed.
+        /// On single-threaded environments (e.g., browser), it would register a continuation and yield to the browser event loop immediately.
+        /// </summary>
+        /// <param name="task">The result from the main entrypoint to await.</param>
```
Comment (gewarren) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs]:
```suggestion
        /// <summary>
        /// This method is intended to be used by a Roslyn-generated async entry point.
        /// </summary>
        /// <remarks>
        /// On multi-threaded environments, this method blocks and awaits the specified task, and returns when the task has completed.
        /// On single-threaded environments (for example, browser), it registers a continuation and yields to the browser event loop immediately.
        /// </remarks>
        /// <param name="task">The result from the main entry point to await.</param>
```

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs [hunk 52]
```diff
@@ -0,0 +1,32 @@
...
+        {
+            task.GetAwaiter().GetResult();
+        }
+
+        /// <summary>
+        /// This method is intended to be used by Roslyn-generated async entry point.
+        /// On multi-threaded environments, it would block and await the specified task and return when the task has completed.
+        /// On single-threaded environments (e.g., browser), it would register a continuation and yield to the browser event loop immediately.
+        /// </summary>
+        /// <param name="task">The result from the main entrypoint to await.</param>
```
Comment (gewarren) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs]:
```suggestion
        /// <summary>
        /// This method is intended to be used by a Roslyn-generated async entry point.
        /// </summary>
        /// <remarks>
        /// On multi-threaded environments, this method blocks and awaits the specified task, and returns when the task has completed.
        /// On single-threaded environments (for example, browser), it registers a continuation and yields to the browser event loop immediately.
        /// </remarks>
        /// <param name="task">The result from the main entry point to await.</param>
```

**Review by gewarren — COMMENTED** [review]
Left some doc suggestions.

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs (hunk 51 above)
Comment (jkotas) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.NonBrowser.cs]: Roslyn is our internal codename. It should not be used in public docs. Also, I would expect we would like to see other compilers like FSharp to use this method as well.

I think we should say "compiler-generated async entrypoint".

File: src/coreclr/vm/assembly.cpp [hunk 53]
```diff
@@ -1060,8 +1060,10 @@ void Assembly::AddDiagnosticStartupHookPath(LPCWSTR wszPath)
 
 enum CorEntryPointType
 {
-    EntryManagedMain,                   // void main(String[])
-    EntryCrtMain                        // unsigned main(void)
+    EntryManagedMain,                   // void Main(String[])
+    EntryCrtMain,                       // unsigned main(void)
```
Comment (jkotas) [inline src/coreclr/vm/assembly.cpp]:
```suggestion
    EntryManagedMain,                   // void/int/uint Main(string[])
    EntryCrtMain,                       // void/int/uint Main(void)
```

**Comment by jkotas** [comment]
LGTM (the parts that I understand). Somebody with understanding of the JavaScript layer should review and signoff on that part.

**Review by maraf — APPROVED** [review]

**Review by radekdoulik — APPROVED** [review]

**Comment by pavelsavara** [comment]
/ba-g CI timeouts and https://github.com/dotnet/runtime/issues/114924
