### PR TITLE
Fix remaining uses of hccall

### LINKED ISSUE #110512: Test failure: readytorun/tests/mainv2/mainv2.cmd
**Failed in:** [runtime-coreclr gcstress-extra 20241208.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889450&view=ms.vss-test-web.build-test-results-tab&runId=23290916&resultId=158163&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked gcstress0xc_tailcallstress @ Windows.10.Amd64.Open
    - readytorun/tests/mainv2/mainv2.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hwACE2097EwA88508FFuploads	estsmainv2output.txt
Raw output:
BEGIN EXECUTION
        1 file(s) copied.
        1 file(s) copied.
Emitting R2R PE file: test.dll
Emitting map file: test.map
Emitting R2R PE file: fieldgetter.dll
Emitting map file: fieldgetter.map
Emitting R2R PE file: mainv2.dll
Emitting map file: mainv2.map
 "C:hwACE2097Epcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  mainv2.dll 
TestVirtualMethodCalls
TestMovedVirtualMethod
TestThrowHelpers
TestConstrainedMethodCalls
TestConstrainedMethodCalls_Unsupported
TestInterop
TestStaticFields
TestPreInitializedArray
TestMultiDimmArray
TestGenericVirtualMethod
TestMovedGenericVirtualMethod
TestGenericNonVirtualMethod
TestGenericOverStruct
TestInstanceFields
TestInstanceFieldsWithLayout
TestInheritingFromGrowingBase
TestGrowingStruct
TestChangingStruct
TestChangingHFAStruct
TestGetType
TestMultipleLoads
TestFieldLayoutNGenMixAndMatch
TestStaticBaseCSE
TestIsInstCSE
TestCastClassCSE
TestRangeCheckElimination
TestOpenClosedDelegate
GenericLdtokenFieldsTest
RVAFieldTest
TestLoadR2RImageFromByteArray
TestILBodyChange
2
TestDefaultVsExactStaticVirtualMethodImplementation
ILInliningVersioningTest cross module inlined methods
     120 | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__RunAllTests  (MethodWithGCInfo)
      79 | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestGenericLdtokenFields  (MethodWithGCInfo)
      33 | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestStaticFields  (MethodWithGCInfo)
0x00003B70 | 0x000067 |     12 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestVirtualMethodCalls  (MethodWithGCInfo)
0x00003BE0 | 0x00003F |      7 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestMovedVirtualMethods  (MethodWithGCInfo)
0x00003C20 | 0x00002B |      2 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestConstrainedMethodCalls  (MethodWithGCInfo)
0x00003C50 | 0x000013 |      1 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestConstrainedMethodCallsOnEnum  (MethodWithGCInfo)
0x00003C70 | 0x000011 |      2 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestInterop  (MethodWithGCInfo)
0x00003C90 | 0x0001F8 |     33 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestStaticFields  (MethodWithGCInfo)
0x00003E90 | 0x00005F |      7 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestPreInitializedArray  (MethodWithGCInfo)
0x00003EF0 | 0x0000FB |      4 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestMultiDimmArray  (MethodWithGCInfo)
0x00003FF0 | 0x00002B |      4 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestGenericVirtualMethod  (MethodWithGCInfo)
0x00004020 | 0x000063 |      9 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestMovedGenericVirtualMethod  (MethodWithGCInfo)
0x00004090 | 0x000029 |      5 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestGenericNonVirtualMethod  (MethodWithGCInfo)
0x000040C0 | 0x000087 |     13 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestGenericOverStruct  (MethodWithGCInfo)
0x00004150 | 0x0000F8 |     25 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestInstanceFields  (MethodWithGCInfo)
0x00004250 | 0x00005E |      9 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestInstanceFieldsWithLayout  (MethodWithGCInfo)
0x000042B0 | 0x00005E |      9 | .text   | test_ILInliningVersioningTest_1<mainv2_LocallyDefinedStructure>__TestInheritingFromGrowingBase  (MethodWithGCInfo)
0x00004310 | 0x000024 |   
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor25|0_26(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by davidwrighton**
It is not generally safe to call jit helpers from native code anymore, and as such we don't need the HCCALL macro anymore. 
 
This should fix #110512 and #116360

### CODE REVIEW

File: src/coreclr/vm/interpexec.cpp [hunk 1]
```diff
@@ -532,23 +532,23 @@ void InterpExecMethod(InterpreterFrame *pInterpreterFrame, InterpMethodContextFr
                     ip += 3;
                     break;
                 case INTOP_CONV_R4_I4:
-                    LOCAL_VAR(ip[1], float) = HCCALL1(JIT_Lng2Flt, (int64_t)LOCAL_VAR(ip[2], int32_t));
+                    LOCAL_VAR(ip[1], float) = JIT_Lng2Flt((int64_t)LOCAL_VAR(ip[2], int32_t));
```
Comment (jkotas) [inline src/coreclr/vm/interpexec.cpp]:
```suggestion
                    LOCAL_VAR(ip[1], float) = (float)LOCAL_VAR(ip[2], int32_t));
```
We can just do it, no need to indirect through the JIT helper.

File: src/coreclr/vm/interpexec.cpp [hunk 2]
```diff
@@ -532,23 +532,23 @@ void InterpExecMethod(InterpreterFrame *pInterpreterFrame, InterpMethodContextFr
...
                     ip += 3;
                     break;
                 case INTOP_CONV_R4_I8:
-                    LOCAL_VAR(ip[1], float) = HCCALL1(JIT_Lng2Flt, LOCAL_VAR(ip[2], int64_t));
+                    LOCAL_VAR(ip[1], float) = JIT_Lng2Flt(LOCAL_VAR(ip[2], int64_t));
```
Comment (jkotas) [inline src/coreclr/vm/interpexec.cpp]:
```suggestion
                    LOCAL_VAR(ip[1], float) = (float)LOCAL_VAR(ip[2], int64_t);
```

File: src/coreclr/vm/interpexec.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/vm/interpexec.cpp]: Also, delete the forward decl at the top of the file

File: src/coreclr/vm/interpexec.cpp (hunk 2 above)
Comment (janvorli) [reply src/coreclr/vm/interpexec.cpp]: It seems we can do the same for `JIT_Lng2Dbl`, as it is also just a cast to double.

**Comment by davidwrighton** [comment]
/ba-g The errors here are unrelated and not new

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by jkotas — APPROVED** [review]
