### PR TITLE
[wasm] Make some libc stubs return an error instead of asserting.

### LINKED ISSUE #38164: [WASM] Environment.UserName raises "not supported" exception
**Update:** UserName now fails with `System.IO.IOException : Not supported`

~~This is causing `System.Runtime.Extensions.Tests` to crash.~~

~~Crashes with:~~
<details>
```
at 205708 (dotnet.js:1858:32)
    at _emscripten_asm_const_iii (dotnet.js:1863:27)
    at wasm_logger (<anonymous>:wasm-function[7791]:0x1f3d0d)
    at eglib_log_adapter (<anonymous>:wasm-function[6303]:0x1abc50)
    at monoeg_g_logstr (<anonymous>:wasm-function[7225]:0x1ced8d)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[7223]:0x1cecb4)
    at monoeg_g_logv (<anonymous>:wasm-function[7222]:0x1cec11)
    at monoeg_g_log (<anonymous>:wasm-function[7226]:0x1ceded)
    at getpwuid_r (<anonymous>:wasm-function[1131]:0x6e9e5)
    at SystemNative_GetPwUidR (<anonymous>:wasm-function[7726]:0x1effbc)
```
</details>

~~I guess this API should throw PNSE in WASM?~~

Will disable the tests against this issue in the meantime. 

cc: @steveisok @lewing @marek-safar @akoeplinger

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/38164.

### CODE REVIEW

**Review by alexischr — APPROVED** [review]

File: src/mono/mono/mini/mini-wasm.c [hunk 1]
```diff
@@ -722,24 +722,24 @@ ssize_t sendfile(int out_fd, int in_fd, off_t *offset, size_t count);
 
 ssize_t sendfile(int out_fd, int in_fd, off_t *offset, size_t count)
```
Comment (marek-safar) [inline src/mono/mono/mini/mini-wasm.c:723]: Why is it done here and not at a higher level with better exception type and less code?

Comment (vargaz) [reply src/mono/mono/mini/mini-wasm.c:723]: These are libc stubs they should error out instead of asserting.

Comment (akoeplinger) [reply src/mono/mono/mini/mini-wasm.c:723]: Yeah I agree.

**Review by akoeplinger — APPROVED** [review]
