### PR TITLE
Define equals manually for Swift JitInterface InlineArray types.

### LINKED ISSUE #104765: ILCompiler.Compiler.Tests.SwiftLoweringTests.VerifyLowering failing with preivew 6
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=737461
Build error leg or test failing: ILCompiler.Compiler.Tests.SwiftLoweringTests.VerifyLowering
Pull request: https://github.com/dotnet/runtime/pull/104696

## Error Message

```
    Assert.Equal() Failure: Exception thrown during comparison
Expected: {CORINFO_TYPE_LONG: 0, CORINFO_TYPE_DOUBLE: 8, CORINFO_TYPE_LONG: 16, CORINFO_TYPE_SHORT: 24}
Actual:   {CORINFO_TYPE_LONG: 0, CORINFO_TYPE_DOUBLE: 8, CORINFO_TYPE_LONG: 16, CORINFO_TYPE_SHORT: 24}
---- System.NotSupportedException : Calling built-in Equals() or GetHashCode() on type marked as InlineArray is invalid.

   at ILCompiler.Compiler.Tests.SwiftLoweringTests.VerifyLowering(String typeName, EcmaType type, CORINFO_SWIFT_LOWERING expectedLowering) in /_/src/coreclr/tools/aot/ILCompiler.Compiler.Tests/SwiftLoweringTests.cs:line 106
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

----- Inner Stack Trace -----
at System.ValueType.CanCompareBitsOrUseFastGetHashCode(MethodTable* pMT)
at System.ValueType.Equals(Object obj)
at System.ValueType.Equals(Object obj)
```

```json
{
  "ErrorMessage": "Calling built-in Equals() or GetHashCode() on type marked as InlineArray is invalid",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=737461
**Error message validated:** `[Calling built-in Equals() or GetHashCode() on type marked as InlineArray is invalid`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 7/11/2024 10:27:03 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes https://github.com/dotnet/runtime/issues/104765

### CODE REVIEW

File: src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs [hunk 1]
```diff
@@ -1509,12 +1509,52 @@ public struct CORINFO_SWIFT_LOWERING
         private struct SwiftLoweredTypes
```
Comment (jkotas) [inline src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs:1509]: Should this be only comparing `numLoweredElements` worth of items?

It would require the Equals and GetHashCode to be on the `CORINFO_SWIFT_LOWERING` that I think makes more sense in general.

File: src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs [hunk 2]
```diff
@@ -1529,6 +1529,47 @@ private struct LoweredOffsets
...
+                return false;
+            }
+
+            // If both are by-ref, the rest of the bits mean nothing.
+            if (byReference)
+            {
+                return true;
+            }
+
+            return LoweredElements.Slice(0, (int)numLoweredElements).SequenceEqual(other.LoweredElements).Slice(0, (int)other.numLoweredElements)
```
Comment (jkotas) [inline src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs:1550]:
```suggestion
            return LoweredElements.Slice(0, (int)numLoweredElements).SequenceEqual(other.LoweredElements.Slice(0, (int)other.numLoweredElements);
```

**Review by jkotas — APPROVED** [review]
