### PR TITLE
handle SECURITY_STATUS 0x80090016

### LINKED ISSUE #69828: Unhandled SECURITY_STATUS (0x80090016) in SecurityStatusAdapterPal results in InternalException
### Description

SecurityStatusAdapterPal does not seem to have an error code mapping for 0x80090016 (-2146893802). This can result in the following exception from HttpClient when .NET runtime cannot validate the CA certificate:

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. -2146893802
at System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(SECURITY_STATUS win32SecurityStatus, Boolean attachException)
at System.Net.Security.SslStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteContext& context, String targetName, ArraySegment`1 input, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
<>
at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
<>
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Bo--TRUNCATED--
```

### Reproduction Steps

I'm honestly not sure how to reproduce this. It happens once every few million requests for our service.

### Expected behavior

SecurityStatusAdapterPal should be able to translate this into a proper error code/exception that the consumer can catch.

### Actual behavior

SecurityStatusAdapterPal throws an System.Net.InternalException which cannot be caught since that class is internal to .NET runtime.

### Regression?

I am unsure if this is regression. From what I can tell looking at the SecurityStatusAdapterPal source code, it does not appear this code was ever supported.

### Known Workarounds

_No response_

### Configuration

- .NET Version: .NET Core SDK 3.1.417
- OS version: Unsure, this is running on an Azure VM. Likely Windows Server 2019 or 2022.
- Architecture: x64

### Other information

The exception indicates there's no mapping found in this dictionary: https://github.com/dotnet/runtime/blob/032a7dcbe1056493e8bab51e6b5b9503de727273/src/libraries/Common/src/System/Net/SecurityStatusAdapterPal.Windows.cs#L21-L66

### PR DESCRIPTION
**Pull request by pedrobsaila**
Fixes #69828

### CODE REVIEW

**Review by rzikm — APPROVED** [review]
LGTM!

File: src/libraries/Common/src/Interop/Windows/SChannel/Interop.SECURITY_STATUS.cs [hunk 1]
```diff
@@ -51,5 +51,6 @@ internal enum SECURITY_STATUS
         DowngradeDetected = unchecked((int)0x80090350),
         ApplicationProtocolMismatch = unchecked((int)0x80090367),
         NoRenegotiation = unchecked((int)0x00090360),
+        KeysetDoesNotExist = unchecked((int)0x80090016)
```
Comment (wfurt) [inline src/libraries/Common/src/Interop/Windows/SChannel/Interop.SECURITY_STATUS.cs:54]: It feels like this should be `KeySetDesNotExist` to follow https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509keystorageflags?view=net-6.0 capitalization. 

I'm not 100% this matches the other usage. cc: @bartonjs for second voice.

**Review by wfurt — COMMENTED** [review]
generally looks good to me.

**Review by wfurt — APPROVED** [review]
