### PR TITLE
Fix XUnitWrapperGenerator handling of SkipOnCoreClrAttribute with no runtime test modes

### LINKED ISSUE #105964: Issue with DecorateWithSkipOnCoreClrConfiguration
Hit the following error, when removing `<MergedWrapperProjectReference Remove="classloader/SequentialLayout/ManagedSequential/LargeStructSize_Mono.csproj" />` from `src/tests/Loader/Loader.csproj`

```
##[error]artifacts/tests/coreclr/obj/AnyOS.x64.Checked/Managed/Loader/Loader/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs(1042,17): error CS1525: Invalid expression term ')' [/__w/1/s/src/tests/Loader/Loader.csproj]
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Add check to skip tests if all RuntimeTestModes are skipped

Fixes https://github.com/dotnet/runtime/issues/105964

### CODE REVIEW

File: src/tests/Common/XUnitWrapperGenerator/XUnitWrapperGenerator.cs [hunk 1]
```diff
@@ -875,12 +875,13 @@ void ReadSkippedInformationFromSkipOnCoreClrAttributeArgument(TypedConstant argu
                         }
                     }
 
-                    if (skippedTestModes == Xunit.RuntimeTestModes.Any)
+                    if (skippedTestModes == Xunit.RuntimeTestModes.Any
+                        && skippedConfigurations == Xunit.RuntimeConfigurations.Any
```
Comment (jkoritzinsky) [inline src/tests/Common/XUnitWrapperGenerator/XUnitWrapperGenerator.cs]:
```suggestion
                        && skippedConfigurations == Xunit.RuntimeConfiguration.Any
```

File: src/tests/Common/XUnitWrapperGenerator/ITestInfo.cs [hunk 2]
```diff
@@ -207,6 +212,16 @@ private static string GetPlatformConditionFromTestPlatform(Xunit.TestPlatforms p
...
+        if (platform == Xunit.TestPlatforms.Any)
+        {
+            return "false";
+        }
+
+        if (platform == 0)
+        {
+            return "true";
+        }
+
```
Comment (jkoritzinsky) [inline src/tests/Common/XUnitWrapperGenerator/ITestInfo.cs:224]:
```suggestion
        if (platform == Xunit.TestPlatforms.Any)
        {
            return "true";
        }

        if (platform == 0)
        {
            return "false";
        }

```

**Review by akoeplinger — APPROVED** [review]
