### PR TITLE
[NativeAOT] Fixes for two rare stress issues.

### LINKED ISSUE #83898: [NativeAot] Rare deadlock when two threads try to suspend runtime
This is rare. The common case for EE suspension is GC and those suspensions happen one at a time.

However if there is another request for suspension or more generally another thread tries to lock the threadstore, we may get into a deadlock because we allow threads to lock on threadstore while in coop mode.

An example of a real scenario hitting this is tests that use `RhGetTotalAllocatedBytesPrecise`.
- `RhGetTotalAllocatedBytesPrecise` initiates EE suspension and acquires threadstore lock
- GC happens and tries to suspend EE on a thread in coop mode
- the thread blocks on threadstore lock
- EE suspension cannot complete, since there is a coop thread in native code blocked on threadstore lock that will only be released when this same suspension is over.

The root cause is that the thread that tries to acquire threadstore lock must not be in coop mode as EE may be already suspending for other reasons.

This is a tracking bug. I am testing a fix for this.

### LINKED ISSUE #83900: [NativeAOT] Rare stress crash due to unwalkable transition frame capturing a hijacked return address.
`RhpGcAlloc` is called from the fast-path asm helpers such as `RhpNewObject` or `RhpNewArrayRare`. 
The asm helpers can be tail-called. That is desirable for perf.
The caller of the asm helper could be hijacked. That is by itself ok too.

If the allocation cannot be satisfied in the asm helper, the helper will push a transition frame (so that stack is walkable if GC happens) and then call into `RhpGcAlloc`. 
In the rare case when allocation was tail-called from a hijacked method, the transition frame captures hijacked return address and thus unwalkable. If GC happens as a result of this allocation, it will see an unwalkable stack.

This is a tracking bug. I am testing a fix.

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: https://github.com/dotnet/runtime/issues/83900
Fixes: https://github.com/dotnet/runtime/issues/83898

Fixes for two rare stress issues. 
When running tests in a loop I see these maybe once in 100+ runs, so they are mostly stress nuisance.

### CODE REVIEW

**Comment by VSadov** [comment]
Strange failures about 'SQLitePCLRaw.core' . Is there a new AOT-incompatible test?

```
  Internal.TypeSystem.TypeSystemException+FileNotFoundException: Failed to load assembly 'SQLitePCLRaw.core'
     at Internal.TypeSystem.ThrowHelper.ThrowFileNotFoundException(ExceptionStringID id, String fileName) in /_/src/coreclr/tools/Common/TypeSystem/Common/ThrowHelper.cs:line 35
     at Internal.TypeSystem.ResolutionFailure.Throw() in /_/src/coreclr/tools/Common/TypeSystem/Common/ResolutionFailure.cs:line 105
     at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 412
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ResolveHandle(EntityHandle handle) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 61
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl(SignatureTypeCode typeCode) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 143
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode typeCode) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 98
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType() in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 309
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseFieldSignature() in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 449
     at Internal.TypeSystem.Ecma.EcmaField.InitializeFieldType() in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaField.cs:line 102
     at Internal.TypeSystem.MetadataFieldLayoutAlgorithm.ComputeInstanceLayout(DefType defType, InstanceLayoutKind layoutKind) in /_/src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:line 37
     at Internal.TypeSystem.DefType.ComputeInstanceLayout(InstanceLayoutKind layoutKind) in /_/src/coreclr/tools/Common/TypeSystem/Common/DefType.FieldLayout.cs:line 436
     at ILCompiler.CompilerTypeSystemContext.EnsureLoadableTypeUncached(TypeDesc type) in /_/src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.Validation.cs:line 137
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key) in /_/src/coreclr/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 562
     at ILCompiler.DependencyAnalysis.EETypeNode..ctor(NodeFactory factory, TypeDesc type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/EETypeNode.cs:line 103
     at ILCompiler.DependencyAnalysis.NodeFactory.CreateNecessaryTypeNode(TypeDesc type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs:line 518
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key) in /_/src/coreclr/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 562
     at ILCompiler.DependencyAnalysis.NodeFactory.NecessaryTypeSymbol(TypeDesc type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs:line 593
     at ILCompiler.DependencyAnalysis.GenericCompositionNode.GetDehydratableData(NodeFactory factory, Boolean relocsOnly) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/GenericCompositionNode.cs:line 95
     at ILCompiler.DependencyAnalysis.DehydratableObjectNode.GetData(NodeFactory factory, Boolean relocsOnly) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/DehydratableObjectNode.cs:line 19
     at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory factory) in /_/src/coreclr/tools/Common/Compiler/DependencyAnalysis/ObjectNode.cs:line 59
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 182
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 222
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 257
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 308
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 140
     at ILCompiler.Program.<Run>g__RunScanner|3_0(<>c__DisplayClass3_0&) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 443
     at ILCompiler.Program.Run() in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 423
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass206_0.<.ctor>b__0(InvocationContext context) in /_/src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs:line 275

```

**Comment by jkotas** [comment]
> Strange failures about 'SQLitePCLRaw.core' . Is there a new AOT-incompatible test?

https://github.com/dotnet/runtime/pull/83881 has the fix

**Comment by VSadov** [comment]
I do not think the failures in mono tests could be related to this.

**Comment by VSadov** [comment]
rebased onto main to keep recent

File: src/coreclr/nativeaot/Runtime/gcrhenv.cpp [hunk 1]
```diff
@@ -292,13 +293,32 @@ Object* GcAllocInternal(MethodTable *pEEType, uint32_t uFlags, uintptr_t numElem
...
+    // The helper can also be tail-called. That is desirable for the fast path.
+    //
+    // Here we are on the slow(er) path when we need to call into GC. The fast path pushes a frame and calls here.
+    // In extremely rare cases the caller of the asm helper is hijacked and the helper is tail-called.
+    // As a result the asm helper may capture a hijacked return address into the transition frame.
+    // We do not want to put the burden of preventing such scenario on the fast path. Instead we will
+    // check for "hijacked frame" here and un-hijack m_RIP.
+    // We do not need to re-hijack when we are done, since m_RIP is discarded in POP_COOP_PINVOKE_FRAME
+    //
+    // NOTE: this is not a problem for ARM since tail-calling methods are not hijackable for other reasons.
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/gcrhenv.cpp:313]: Is there any harm in enabling this for all platforms? This is a very cheap check.

**Review by jkotas — APPROVED** [review]
Thanks!

File: src/coreclr/nativeaot/Runtime/gcrhenv.cpp (hunk 1 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/gcrhenv.cpp:313]: It is hard to reason how we would deal with this issue on ARM64. 

m_RIP is not discarded in POP_COOP_PINVOKE_FRAME` on architectures that have LR-style calls. POP_COOP_PINVOKE_FRAME would use m_RIP to restore LR.  
The contract with hijacking is that we can never pop out of a hijacked frame. Otherwise unhijack would be modifying stack that could be reused in subsequent calls for something else. So, if LR somehow contained a hijacked return, we'd need to restore it.

I figured it is easier to not do the check at all and explain why it is not needed, than do the check and explain why the fixup might not work correctly on ARM64 but also would never be applied.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/gcrhenv.cpp:313]: Another question here is - why do we not unhijack the thread as well? 

We could do that. It is allowed for a thread in coop mode to unhijack itself at any time. But it is more work and while this is a slower path, we are not necessarily heading for a GC. Most likely GC will just refill/reset the allocation buffer minus the object that still needs to be allocated.

It can happen relatively fast and hijack would still be valid. So I figured to do the minimum fixup that is needed.

Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/gcrhenv.cpp:313]: It was not clear to me that this logic would be broken on Arm64. 

The norm on newer architectures is to have the return address in a register. Amd64 and x86 are the exception. 

I think we should:

- Put this logic under `#if defined(TARGET_X86) || defined(TARGET_AMD64)`
- Add `ASSERT(!Thread::IsHijackTarget(pTransitionFrame->m_RIP));` into the `#else` part of the ifdef, with a comment explaining the problem.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/gcrhenv.cpp:313]: > The norm on newer architectures is to have the return address in a register. Amd64 and x86 are the exception.

Yes, I think new architectures will use something like LR. Another reason I did not want this to be a default. 

> Put this logic under #if defined(TARGET_X86) || defined(TARGET_AMD64)

Right. It would be better.

> Add ASSERT(!Thread::IsHijackTarget(pTransitionFrame->m_RIP)); into the #else part of the ifdef, with a comment explaining the problem.

Can add that.

I've added such assert to the `SetDeferredTransitionFrame` - to catch all the cases - where this condition cannot happen or where it needs a fixup.

In theory we could introduce more cases that would call `SetDeferredTransitionFrame` and have a similar concern. For now I think RhpGcAlloc is the only such case.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/gcrhenv.cpp:313]: There is one another user of PUSH_COOP_PINVOKE_FRAME - RhpGcPoll which is used for polling in loops. I do not think it can be tail-called, since it is called from loops.

I think, I will add an assert in RhpGcPoll2, just in case.

**Comment by VSadov** [comment]
Thanks!!
