### PR TITLE
Fix NamedMutex PAL test

### LINKED ISSUE #82052: NamedMutex outerloop test failures
Link: https://dev.azure.com/dnceng-public/public/_build/results?buildId=169947&view=results

```scala
paltests <PrintPalTests|TestName>
Either print list of all paltests by passing PrintPalTests, or run a single PAL test.
'paltest_namedmutex_test1' failed at line 298. Expression: WaitForMutexToBeCreated(testName, childEvents[0], ChildEventNamePrefix0)
'paltest_namedmutex_test1' failed at line 495. Expression: InitializeParent(testName, parentEvents, childEvents)
'paltest_namedmutex_test1' failed at line 598. Expression: MutualExclusionTests_Parent()
paltests <PrintPalTests|TestName>
Either print list of all paltests by passing PrintPalTests, or run a single PAL test.
'paltest_namedmutex_test1' failed at line 298. Expression: WaitForMutexToBeCreated(testName, childEvents[0], ChildEventNamePrefix0)
'paltest_namedmutex_test1' failed at line 608. Expression: InitializeParent(testName, parentEvents, childEvents)
'paltest_namedmutex_test1' failed at line 686. Expression: LifetimeTests_Parent()
paltests <PrintPalTests|TestName>
Either print list of all paltests by passing PrintPalTests, or run a single PAL test.
'paltest_namedmutex_test1' failed at line 298. Expression: WaitForMutexToBeCreated(testName, childEvents[0], ChildEventNamePrefix0)
'paltest_namedmutex_test1' failed at line 729. Expression: InitializeParent(testName, parentEvents, childEvents)
'paltest_namedmutex_test1' failed at line 934. Expression: AbandonTests_Parent()
paltests <PrintPalTests|TestName>
Either print list of all paltests by passing PrintPalTests, or run a single PAL test.
'paltest_namedmutex_test1' failed at line 298. Expression: WaitForMutexToBeCreated(testName, childEvents[0], ChildEventNamePrefix0)
'paltest_namedmutex_test1' failed at line 957. Expression: InitializeParent(testName, parentEvents, childEvents)
'paltest_namedmutex_test1' failed at line 1089. Expression: LockAndCloseWithoutThreadExitTests_Parent_CloseOnSameThread()
```

Maybe related to #81604? cc @am11 @AaronRobinsonMSFT

### PR DESCRIPTION
**Pull request by am11**
Fix https://github.com/dotnet/runtime/issues/82052.

### CODE REVIEW

File: src/coreclr/pal/tests/palsuite/threading/NamedMutex/test1/namedmutex.cpp [hunk 1]
```diff
@@ -193,9 +195,10 @@ bool StartProcess(const char *funcName)
     processCommandLinePathLength += test_strlen(g_processPath);
     g_processCommandLinePath[processCommandLinePathLength++] = '\"';
     g_processCommandLinePath[processCommandLinePathLength++] = ' ';
-    processCommandLinePathLength += test_snprintf(&g_processCommandLinePath[processCommandLinePathLength], processCommandLinePathLength, "%s ", "threading/NamedMutex/test1/paltest_namedmutex_test1");
-
-    processCommandLinePathLength += test_snprintf(&g_processCommandLinePath[processCommandLinePathLength], processCommandLinePathLength, "%u", g_parentPid);
+    const char* testname = "threading/NamedMutex/test1/paltest_namedmutex_test1";
+    processCommandLinePathLength += test_snprintf(&g_processCommandLinePath[processCommandLinePathLength], strlen(testname) + 2, "%s ", testname);
```
Comment (am11) [inline src/coreclr/pal/tests/palsuite/threading/NamedMutex/test1/namedmutex.cpp:199]: +2 is for the space after `%s`. In rest of the places, it's +1 (room for trailing `NUL`).

File: src/coreclr/pal/tests/palsuite/threading/NamedMutex/test1/namedmutex.cpp [hunk 2]
```diff
@@ -84,11 +84,12 @@ char *BuildName(const char *testName, char *buffer, const char *prefix0, const c
     if (g_isStress)
     {
         // Append the test name so that tests can run in parallel
-        nameLength += test_snprintf(&buffer[nameLength], nameLength, "%s", testName);
+        nameLength += test_snprintf(&buffer[nameLength], strlen(testName) + 1, "%s", testName);
```
Comment (janvorli) [inline src/coreclr/pal/tests/palsuite/threading/NamedMutex/test1/namedmutex.cpp:87]: I wonder what's the benefit of computing the size instead of using the remainder of the buffer. To me, that's how the snprintf is supposed to be used - you pass it the space left in the buffer and it will ensure it won't write out of the buffer.

Comment (am11) [reply src/coreclr/pal/tests/palsuite/threading/NamedMutex/test1/namedmutex.cpp:87]: Currently the callers doesn't pass the _size_, so I computed it in-place. I agree that difference approach is more suitable. I will pass the sizes from the call-sites.

Comment (am11) [reply src/coreclr/pal/tests/palsuite/threading/NamedMutex/test1/namedmutex.cpp]: Turned out we are using the same constant in this function. The different sized array was `char name[257];`, which we don't pass to BuildName.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by am11** [comment]
@janvorli, can you please start the outerloop pipeline against this PR?

**Comment by am11** [comment]
Failure is unrelated (`docker pull` failed).

cc @AaronRobinsonMSFT
