### PR TITLE
Copy the SSA name when cloning locals

### LINKED ISSUE #68479: Assertion failed 'ssaNum != SsaConfig::RESERVED_SSA_NUM'  during 'VN based copy prop'
```c#
// Found by Antigen
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
        public struct S1_D1_F1
        {
        }
        public ulong ulong_1;
    }
    public struct S2
    {
        public ulong ulong_3;
    }
    static char s_char_6 = 'R';
    static long s_long_11 = 2;
    static S1.S1_D1_F1 s_s1_s1_d1_f1_18 = new S1.S1_D1_F1();
    static S1 s_s1_19 = new S1();
    static S2 s_s2_20 = new S2();
    char char_23 = 'H';
    S2 s2_37 = new S2();
    public char LeafMethod2()
    {
        unchecked
        {
            return s_char_6 = char_23 = 'Q';
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public decimal LeafMethod3()
    {
        unchecked
        {
            return 15+4;
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public long LeafMethod7()
    {
        unchecked
        {
            return 15%4;
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public ulong LeafMethod13()
    {
        unchecked
        {
            return 15+4;
        }
    }
    public decimal Method1(S1.S1_D1_F1 p_s1_s1_d1_f1_38, long p_long_39, out ulong p_ulong_40, ref S2 p_s2_41, S2 p_s2_42, S1.S1_D1_F1 p_s1_s1_d1_f1_43)
    {
        unchecked
        {
            p_ulong_40 = s_s2_20.ulong_3 &= s_s1_19.ulong_1% 15+4+ LeafMethod13();
            return LeafMethod3();
        }
    }
    public void Method0()
    {
        unchecked
        {
            char char_81 = 'D';
            int int_85 = -5;
            long long_86 = 2;
            S1.S1_D1_F1 s1_s1_d1_f1_93 = new S1.S1_D1_F1();
            S1 s1_94 = new S1();
            try
            {
            }
            catch (System.AggregateException)
            {
            }
            finally
            {
                switch (char_81 = char_81 = LeafMethod2())
                {
                    case '6':
                    {
                        break;
                    }
                    case 'T':
                    {
                        break;
                    }
                    case 'J':
                    {
                        if (15*4>= 15+4+ 51|| 15==4)
                        {
                        }
                        else
                        {
                            switch (int_85 += 15-4)
                            {
                                case -1:
                                {
                                    break;
                                }
                                case -5:
                                {
                                    break;
                                }
                                case 2:
                                {
                                    switch (LeafMethod7())
                                    {
                                        case -2:
                                        {
                                            break;
                                        }
                                        case 0:
                                        {
                                            break;
                                        }
                                        case 34:
                                        {
                                            Method1(s1_s1_d1_f1_93, 15*4^ long_86 % (s_long_11 = 2147483646)+ 69, out s1_94.ulong_1, ref s2_37, s2_37, s_s1_s1_d1_f1_18);
                                            break;
                                        }
                                        default:
                                        {
                                            break;
                                        }
                                    }
                                    break;
                                }
                                case 0:
                                {
                                    break;
                                }
                                case 1:
                                {
                                    break;
                                }
                                case -2:
                                {
                                    break;
                                }
                                case 5:
                                {
                                    break;
                                }
                                default:
                                {
                                    break;
                                }
                            }
                        }
                        break;
                    }
                    case 'R':
                    {
                        break;
                    }
                    case '0':
                    {
                        break;
                    }
                    case 'Q':
                    {
                        break;
                    }
                    case '7':
                    {
                        ;
                        break;
                    }
                    case 'Y':
                    {
                        break;
                    }
                    default:
                    {
                        break;
                    }
                }
            }
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}
/*
Environment:

set COMPlus_AltJitName=clrjit_unix_x64_x64.dll
set COMPlus_AltJit=Method0

Assert failure(PID 13696 [0x00003580], Thread: 82844 [0x1439c]): Assertion failed 'ssaNum != SsaConfig::RESERVED_SSA_NUM' in 'TestClass:Method0():this' during 'VN based copy prop' (IL size 265; hash 0x46e9aa75; FullOpts)
    File: D:\git\runtime\src\coreclr\jit\compiler.h Line: 353
    Image: D:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
*/

```

### PR DESCRIPTION
**Pull request by SingleAccretion**
The issue was that during early propagation we can call morph, and that can introduce new uses of in-SSA locals. It is safe and desirable to annotate these with the appropriate SSA numbers.

[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1736241&view=ms.vss-build-web.run-extensions-tab) as expected.

Fixes #68479.

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -7983,22 +7983,24 @@ GenTree* Compiler::gtClone(GenTree* tree, bool complexOK)
             break;
 
         case GT_LCL_VAR:
-            // Remember that the LclVar node has been cloned. The flag will be set
-            // on 'copy' as well.
-            tree->gtFlags |= GTF_VAR_CLONED;
+        case GT_LCL_VAR_ADDR:
```
Comment (SingleAccretion) [inline src/coreclr/jit/gentree.cpp:7986]: Adding `GT_LCL_VAR_ADDR` is not part of the fix, but I just could not unsee how we clone `LCL_FLD_ADDR` but not its offset-less equivalent.

**Review by AndyAyersMS — APPROVED** [review]
