### PR TITLE
[EventPipe] Remove thread lock and cleanup ThreadSessionState lifecycle

### LINKED ISSUE #111368: CoreCLR EventPipe CPU+memory leak
### Description

EventPipe sessions that aren't file or IPC sessions never garbage collect their "thread state session list" for exited threads. This results in a memory leak proportional to the number of threads that have ever started since the EventPipe session began, and for each EventPipe event, a single-threaded CPU leak caused by iterating over the ever-growing thread session state linked list when looking for the next event.

This behavior has been present since at least .NET 6.0 when EventPipe was rewritten into CoreCLR in C, and is still present in the latest `main` branch as of writing this.

### Reproduction Steps

Create an `EventListener` subclass that enables CLR events, something like this:
```csharp
class ClrEventListener : EventListener
{
    protected override void OnEventSourceCreated(EventSource eventSource)
    {
        if (eventSource.Name.Equals("Microsoft-Windows-DotNETRuntime"))
        {
            EnableEvents(eventSource, EventLevel.Informational, (EventKeywords) 0x8000); // 0x8000 enables exception events in this case
        }
    }
}
```

Instantiate the event listener subclass, spawn thousands of short-lived threads, and then do something that creates CLR events (e.g. throw and catch exceptions).

As the number of threads ever spawned increases, the `.NET Long Runni` thread that processes these CLR events will get slower and slower and tend towards 100% CPU time, even if the number of currently running threads stays constant.

I made a [GitHub repo to fully demonstrate and reproduce this issue](https://github.com/dqsully/coreclr-eventpipe-thread-gc-bug).

### Expected behavior

EventPipe session performance should be at least proportional to number currently running threads, not threads that have ever existed during the session.

EventPipe "thread session states" should be garbage collected in all EventPipe session types, so that the length of the thread session state linked-list approximates the number of currently running threads.

### Actual behavior

After a non-file, non-IPC EventPipe session is created, any new threads created will cause the `.NET Long Runni` thread to consume more and more CPU for each event it collects.

### Regression?

I haven't tried this on .NET 5.0, so I'm not sure, but it's been around since at least .NET 6.0 when EventPipe was rewritten in C.

### Known Workarounds

If the EventPipe session is closed and reopened, the new session will start with an empty "thread state session list" and the old one will have cleaned everything up. This also happens if an active EventPipe session is reconfigured, which ends up closing and opening a new session anyways.

Another workaround would be to only use file or IPC-type EventPipe sessions if possible, as these session types do run garbage collection on the "thread session state list".

### Configuration

Tested locally on .NET 8.0.404 and .NET 9.0.101, on a Linux laptop running Ubuntu 24.04 (kernel 6.8.0) with an Intel i7-13800H processor.

Have seen this in production in containers on both Intel and AMD processors, all x86, on various Linux kernels. I don't believe this issue is specific to any particular system or architecture.

### Other information

When I test creating 5,000 synchronous, short-lived threads, and then throwing 5,000,000 exceptions on .NET 9.0.101 on my Linux laptop, `perf` reports the following "Self" times with `libcoreclr.so` offsets:
```
26.23%  .NET Long Runni  libcoreclr.so  [.] 0x00000000004f9eda
13.61%  .NET Long Runni  libcoreclr.so  [.] 0x00000000004f9ed6
 7.88%  .NET Long Runni  libcoreclr.so  [.] 0x00000000004f9ed2
```

For some reason, on my laptop, the `perf` addresses are off by exactly 0x1000. I couldn't tell you why, but I have validated this behavior with .NET 8.0.404 on my laptop, and I've seen this exact same issue in at least 5 different production systems all on different .NET versions with correct `perf` addresses.

Unfortunately, `libcoreclr.so` isn't built with debug symbols, and no debuginfo is published for it, so I've had to reverse-engineer `libcoreclr.so` to match the disassembly with the source code to figure out what is going on here. Below are the .NET 9.0 slow instructions in question:

```asm
004faec5  4d8b6d08           mov     r13, qword [r13+0x8]
004faec9  4d85ed             test    r13, r13
004faecc  0f848f000000       je      0x4faf61

004faed2  498b4500           mov     rax, qword [r13]
004faed6  488b5818           mov     rbx, qword [rax+0x18]
004faeda  4c8b7b10           mov     r15, qword [rbx+0x10]
004faede  4d85ff             test    r15, r15
004faee1  74e2               je      0x4faec5
```

This is the section from `buffer_manager_move_next_event_any_thread` that [iterates each thread session state to find a single event](https://github.com/dotnet/runtime/blob/v9.0.0/src/native/eventpipe/ep-buffer-manager.c#L607), which will then be sent back through to the EventListener.

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes https://github.com/dotnet/runtime/issues/111368

This PR removes EventPipe's complex dual-lock synchronization scheme and integrates ThreadSessionState cleanup as part of event reading logic.

### Thread Lock Removal
- Eliminated the EventPipe thread lock, replacing the complex dual-lock scheme (thread lock + buffer_manager lock) with a single buffer_manager lock
- Unified synchronization: Thread list and session_state slot updates now occur atomically under one lock, eliminating race conditions between buffer operations and session state management
- Simplified lock-free reads: Removed complex cross-lock coordination requirements

### ThreadSessionState Lifecycle Cleanup
- Fixed memory leaks: Proper cleanup of ThreadSessionState objects prevents unbounded growth in long-running sessions
- Unified resource management: ThreadSessionState and buffer_list now have matching lifetimes, eliminating buffer_list leaks from the previous cleanup logic
- Eliminated TSS leak scenarios when threads exit before session disable
- Atomic cleanup operations: Single-lock model enables proper cleanup without cross-lock race conditions
- SequencePoints are updated when a ThreadSessionState is being removed

### Slight Event Reading Optimization
- Added snapshotting of known EventPipeThreadSessionStates to prevent iterating over Threads whose buffers are guaranteed to not have the earliest events

## Testing

Using the original repro
```
Throwing and catching 1000 exceptions (warm up JIT)

Throwing and catching 5000000 exceptions
RSS: 51.7MiB, user CPU: 100.4%
20000000 EventPipe events received, 5000000 exceptions thrown

Spawning 5000 short-lived threads
RSS: 60.3MiB, user CPU: 119.0%
20000 EventPipe events received, 5000 exceptions thrown

Throwing and catching 5000000 exceptions
RSS: 54.3MiB, user CPU: 101.5%
20000000 EventPipe events received, 5000000 exceptions thrown
```

## Performance

Adapted https://github.com/dotnet/diagnostics/tree/main/src/tests/EventPipeStress to also stress the native in-proc event listener EventPipeSession.
Testing a matrix of Session Type X Thread Count X Exceptions/Thread
Session Type: IPC Streaming, Native In-Proc
Thread Count: 1, 8, 16, 50, 100, 1000
Exceptions/Thread: 1, 2, 100, 1000

Note: The local stress test that I put together primarily tests an immediate burst in events being written to EventPipe, which doesn't reflect the behavior of any steady state behavior.

### Native InProc
Baseline vs PR
Screenshot 2026-01-14 221654

This PR overall performs better in fewer events dropped, especially considering the high thread x high exceptions/thread scenarios.

### IPC Streaming
Baseline VS PR
Screenshot 2026-01-14 222304

This PR performs similarly, with slight drop (0.8%) in events read for high threads x high exceptions/thread.

### CODE REVIEW

File: src/native/eventpipe/ep-buffer-manager.c [hunk 1]
```diff
@@ -1456,6 +1324,73 @@ ep_buffer_manager_ensure_consistency (EventPipeBufferManager *buffer_manager)
...
+	EP_ASSERT (thread_session_state != NULL);
+
+	ep_buffer_manager_requires_lock_held (buffer_manager);
+
+	DN_LIST_FOREACH_BEGIN (EventPipeSequencePoint *, current_sequence_point, buffer_manager->sequence_points) {
+		dn_umap_it_t found = dn_umap_ptr_uint32_find (ep_sequence_point_get_thread_sequence_numbers (current_sequence_point), thread_session_state);
+		if (!dn_umap_it_end (found)) {
+			dn_umap_erase (found);
+			// buffer_manager_init_sequence_point_thread_list - every entry of this map was holding an extra ref to the thread
+			ep_thread_release (ep_thread_session_state_get_thread (thread_session_state));
```
[the remark this answers is not in the document]
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Forgot to remove this method, its no longer needed

[the remark this answers is not in the document]
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Forgot to remove this method, its no longer needed

File: src/native/eventpipe/ep-buffer-manager.c [hunk 2]
```diff
@@ -1456,6 +1324,73 @@ ep_buffer_manager_ensure_consistency (EventPipeBufferManager *buffer_manager)
...
+	EventPipeBufferManager *buffer_manager,
+	EventPipeThreadSessionState *thread_session_state)
+{
+	EP_ASSERT (buffer_manager != NULL);
+	EP_ASSERT (thread_session_state != NULL);
+
+	ep_buffer_manager_requires_lock_held (buffer_manager);
+
+	DN_LIST_FOREACH_BEGIN (EventPipeSequencePoint *, current_sequence_point, buffer_manager->sequence_points) {
+		dn_umap_it_t found = dn_umap_ptr_uint32_find (ep_sequence_point_get_thread_sequence_numbers (current_sequence_point), thread_session_state);
```
[the remark this answers is not in the document]
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Forgot to remove this method, its no longer needed

File: src/native/eventpipe/ep-buffer-manager.c [hunk 3]
```diff
@@ -684,64 +685,66 @@ buffer_manager_move_next_event_same_thread (
...
 				// delete the empty buffer
 				EventPipeBuffer *removed_buffer = ep_buffer_list_get_and_remove_head (buffer_list);
 				EP_ASSERT (current_buffer == removed_buffer);
 				buffer_manager_deallocate_buffer (buffer_manager, removed_buffer);
 
 				// get the next buffer
 				current_buffer = buffer_list->head_buffer;
+
+				if (!current_buffer && (ep_rt_volatile_load_uint32_t_without_barrier (ep_thread_get_unregistered_ref (ep_thread_session_state_get_thread (thread_session_state))) > 0))
+					buffer_manager_remove_and_delete_thread_session_state (buffer_manager, thread_session_state);
```
[the remark this answers is not in the document]
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: The first commit removes the thread lock. this line is under the buffer manger lock

**Comment by lateralusX** [comment]
By moving from two locks to one, did you analyze any potential additional lock contention and its effect on EventPipe performance? Buffer manager lock is a central lock for a session, meaning that a lot of parallel activities will queue up on this lock more frequently due to increase need to lock buffer manager. Just looking at the buffer_manager_advance_to_non_empty_buffer  we reach for the buffer manager lock multiple times where the old code only took buffer manager lock when a buffer needed to be deleted after been fully consumed. I know there has been a lot of optimizations that taken place over the years to reduce the contention on buffer manager lock to improve performance in EventPipe. Just wanted to make sure we don't introduce any major performance regression by increasing the use of buffer manager lock in some critical code paths.

File: src/native/eventpipe/ep-thread.c [hunk 4]
```diff
@@ -418,46 +412,23 @@ ep_thread_session_state_get_buffer_list (const EventPipeThreadSessionState *thre
 {
 	EP_ASSERT (thread_session_state != NULL);
 
-	ep_buffer_manager_requires_lock_held (thread_session_state->buffer_manager);
+	ep_buffer_manager_requires_lock_held (ep_session_get_buffer_manager (thread_session_state->session));
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.c]: The lock should no longer be needed to call this accessor. Previously buffer_list was allocated and freed independently of ThreadStateState which meant the pointer could mutate. Now the buffer list is allocated in ep_thread_session_state_alloc and freed in ep_thread_session_state_free. Since the pointer stays constant for the lifetime of the thread_session_state no lock is required to read an immutable value. 

(Technically it transitions from NULL to non-NULL inside alloc, but accessing it indirectly via the this pointer ensures all threads will see the non-NULL value. We don't support super weak memory models like Alpha that could reorder dependent loads)

File: src/native/eventpipe/ep-buffer-manager.c [hunk 5]
```diff
@@ -684,64 +685,67 @@ buffer_manager_move_next_event_same_thread (
...
-	EP_ASSERT (buffer_list->head_buffer == buffer);
+	EP_ASSERT (thread_session_state != NULL);
 
 	ep_buffer_manager_requires_lock_not_held (buffer_manager);
 
-	EventPipeBuffer *current_buffer = buffer;
+	EventPipeBufferList *buffer_list = NULL;
+	EventPipeBuffer *current_buffer = NULL;
 	bool done = false;
+	EP_SPIN_LOCK_ENTER (&buffer_manager->rt_lock, section1)
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c]: This lock can be removed. ep_thread_session_state_get_buffer_list() returns an immutable value and is safe to call lock-free.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 6]
```diff
@@ -684,64 +685,67 @@ buffer_manager_move_next_event_same_thread (
...
 				// delete the empty buffer
 				EventPipeBuffer *removed_buffer = ep_buffer_list_get_and_remove_head (buffer_list);
 				EP_ASSERT (current_buffer == removed_buffer);
 				buffer_manager_deallocate_buffer (buffer_manager, removed_buffer);
 
 				// get the next buffer
 				current_buffer = buffer_list->head_buffer;
+
+				if (!current_buffer && (ep_rt_volatile_load_uint32_t_without_barrier (ep_thread_get_unregistered_ref (ep_thread_session_state_get_thread (thread_session_state))) > 0))
+					buffer_manager_remove_and_delete_thread_session_state (buffer_manager, thread_session_state);
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c]: Deleting one of the function input arguments as a side-effect is unusual behavior when the method isn't clearly named to make callers expect that (free(), delete(), etc). I'd suggest rather than delete it here just let the caller know we've exhausted all the buffers and let them deal with deletion. You could add a parameter such as `bool & is_enum_complete` that gets set to true here.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 7]
```diff
@@ -942,52 +951,54 @@ ep_buffer_manager_write_event (
...
+	// Check to see an event thread was specified. If not, then use the current thread.
+	if (event_thread == NULL)
+		event_thread = thread;
+
+	EventPipeThread *current_thread;
+	current_thread = ep_thread_get ();
+	ep_raise_error_if_nok (current_thread != NULL);
+
+	// session_state won't be freed if write_in_progress is set.
+	EP_ASSERT (ep_thread_is_rundown_thread (current_thread) || ep_thread_get_session_write_in_progress (current_thread) == ep_session_get_index (session));
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c]: Is there anything that prevents the rundown thread from setting the write_in_progress flag? Assuming there isn't I think its simpler to set the flag rather than complicate the conditionals.

File: src/native/eventpipe/ep-thread.h [hunk 8]
```diff
@@ -254,23 +260,19 @@ struct _EventPipeThreadSessionState_Internal {
...
-	// buffers a given thread has used (see: ep_thread_session_state_get_buffer_count_estimate and its uses).
+	// The list of buffers that were written to by this thread.
+	// immutable
 	EventPipeBufferList *buffer_list;
-#ifdef EP_CHECKED_BUILD
-	// protected by the buffer manager lock.
-	EventPipeBufferManager *buffer_manager;
-#endif
+	// The sequence number of the last event that was read, only
+	// updated/read by the reader thread.
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.h:273]: Currently in this PR the last_read_sequence_number is read in buffer_manager_init_sequence_point_thread_list which occurs when threads allocate new buffers while writing events. Elsewhere I suggested a change that would remove that and make the comment accurate again. In case we don't wind up doing that this comment needs to describe whatever thread memory access behavior we do end up with.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 9]
```diff
@@ -1244,7 +1201,26 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
+			if (sequence_point != NULL) {
+				dn_umap_it_t found_thread_id = dn_umap_threadid_uint32_find (ep_sequence_point_get_thread_sequence_numbers (sequence_point), os_thread_id);
+				EP_ASSERT (!dn_umap_it_end (found_thread_id));
+				uint32_t thread_sequence_number = !dn_umap_it_end (found_thread_id) ? dn_umap_it_value_uint32_t (found_thread_id) : 0;
+				// Sequence numbers can overflow so we can't use a direct last_read > sequence_number comparison
+				// If a thread is able to drop more than 0x80000000 events in between sequence points then we will
+				// miscategorize it, but that seems unlikely.
+				uint32_t last_read_delta = sequence_number - thread_sequence_number;
+				if (0 < last_read_delta && last_read_delta < 0x80000000)
+					dn_umap_threadid_uint32_insert_or_assign (ep_sequence_point_get_thread_sequence_numbers (sequence_point), os_thread_id, sequence_number);
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c]: Updating the current sequence point won't guarantee that future sequence points are correct. When a SP is initialized the sequence point value is populated using an unsynchronized read so the initial value is only a stale lower bound on the correct value. Imagine this sequence:

Thread A creates sequence point 1 and records (A,0) in the map
Thread A writes 100 events
Thread B creates sequence point 2 and records (A, 95), (B,0) in the map.
Thread B writes 100 events
Reader thread reads 100 events from A's queue and updates SP1 to (A,100)
Reader thread sends SP1
Reader thread reads 100 events from B's queue and updates SP2 to (A,95), (B,100)
Reader thread sends SP2 which has bad data... it claims that A went backwards from 100 to 95.

I think one scheme that would compute it correctly is:
1. Capture every thread in thread_session_state_list when creating sequence points, including the dead ones. The tracking state wouldn't be needed any longer.
2. Prior to sending a sequence point, enumerate the thread_session_state_list and update any sequence numbers if they are less than last_read_sequence_number (accounting for integer overflow).
3. Let move_next_event() functions update TSS->last_read_sequence_number as a side-effect.
4. Let move_next_event() functions delete TSS instances when they no longer have any remaining events. Before the delete we should update the current sequence point (if any), delete the thread id from any other sequence points queued up, and remove the TSS from the session list.

File: src/native/eventpipe/ep-thread.c [hunk 10]
```diff
@@ -123,6 +119,18 @@ ep_thread_unregister (EventPipeThread *thread)
...
+	for (uint32_t i = 0; i < EP_MAX_NUMBER_OF_SESSIONS; ++i) {
+		EventPipeThreadSessionState *thread_session_state = (EventPipeThreadSessionState *)ep_rt_volatile_load_ptr ((volatile void **)(&thread->session_state [i]));
+		if (thread_session_state == NULL)
+			continue;
+
+		EventPipeBufferManager *buffer_manager = ep_session_get_buffer_manager (thread_session_state->session);
+		EP_ASSERT (buffer_manager != NULL);
+
+		if (ep_buffer_list_is_empty (thread_session_state->buffer_list))
+			ep_buffer_manager_remove_and_delete_thread_session_state (buffer_manager, thread_session_state);
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.c]: I think its possible to do the cross-thread deletion safely, but it would probably be simpler if we [wake up the reader thread](https://github.com/dotnet/runtime/pull/118415/files?diff=split&w=1#diff-4965904f7532c0cc7cb23dc328dd7e4a167b49c850fc1cdfed3805a46ab92ce5R1031-R1033) and let it delete the TSS as a side-effect of its normal event processing loop. Doing it that way means we don't have to reason about potential races with the reader thread. For example we don't have to worry that the reader might access a cached TSS pointer to set last_read_sequence_number after this thread had already deleted it.

File: src/native/eventpipe/ep-thread.h [hunk 11]
```diff
@@ -21,22 +21,40 @@ struct _EventPipeThread {
...
+	// session is enabled. ep_disable() won't exit the global EP lock until all the slots for that session are NULL and
+	// threads have exited code regions where they may have been using locally cached pointers retrieved through
+	// the slots. This ensures threads neither retain stale pointers to a disabled session, nor will they be able to acquire a
+	// stale pointer from the slot later. It also means no thread will be trying to synchronize using a stale session lock across
+	// the transition when a new session takes over ownership of the slot.
+	//
+	// Writing a non-NULL pointer into the slot only occurs on the OS thread associated with this EventPipeThread object when
+	// trying to write the first event into a session.
+	// Writing a NULL pointer into the slot could occur on either:
+	// 1. The thread owning this EventPipeThread when it unregisters (currently this doesn't happen, but it should in the future).
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.h]: My proposal above to signal the reader rather than doing the cross thread delete gets rid of this first option and leaves only (2) and (3). Assuming we do it then we should update the comment to match.

File: src/native/eventpipe/ep-thread.h [hunk 12]
```diff
@@ -254,23 +260,19 @@ struct _EventPipeThreadSessionState_Internal {
 	EventPipeThreadHolder thread_holder;
 	// immutable.
 	EventPipeSession *session;
-	// The buffer this thread is allowed to write to if non-null, it must
-	// match the tail of buffer_list
-	// protected by thread_holder->thread.rt_lock
+	// The buffer this thread is allowed to write to. If non-null, it must
+	// match the tail of buffer_list.
+	// Modifications always occur under the buffer manager lock.
+	// Non-null writes only occur on the thread this state belong to.
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.h]:
```suggestion
	// Non-null writes only occur on the thread this state belongs to.
```

File: src/native/eventpipe/ep-thread.h [hunk 13]
```diff
@@ -254,23 +260,19 @@ struct _EventPipeThreadSessionState_Internal {
...
+	// Null writes may occur on the buffer manager event flushing thread.
+	// Lock-free reads may occur only on the thread this state belong to.
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.h]:
```suggestion
	// Lock-free reads may occur only on the thread this state belongs to.
```

File: src/native/eventpipe/ep-thread.c (hunk 4 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-thread.c]: Thanks. I was wondering if we still needed to use a lock to synchronize mutations to the buffer_list internals, like ep_buffer_list_insert_tail and ep_buffer_list_get_and_remove_head, which all callsites are under a lock, but there weren't any "requires_lock_held" in either. I'm also wondering if theres a particular reason those are exposed as public apis instead of static

File: src/native/eventpipe/ep-buffer-manager.c (hunk 5 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Thanks!

File: src/native/eventpipe/ep-buffer-manager.c (hunk 6 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Good point, added a thread_session_state_exhausted bool to buffer_manager_advance_to_non_empty_buffer, and leaving the callers `buffer_manager_move_next_event_any|same_thread` to cleanup the ThreadSessionStates.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 7 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Thanks! Set the writing_event_in_progress flag during rundown as well.

File: src/native/eventpipe/ep-thread.h (hunk 8 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-thread.h:273]: Implemented, so this comment is accurate now! Thanks

File: src/native/eventpipe/ep-buffer-manager.c (hunk 9 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Thank you! I completely missed this scenario. I extended buffer_manager_remove_and_delete_thread_session_state to also handle updating SequencePoints if any, to call from both buffer_manager_move_next_event_any|same_thread.

File: src/native/eventpipe/ep-thread.c (hunk 10 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-thread.c]: Done, thanks!

File: src/native/eventpipe/ep-thread.h (hunk 11 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-thread.h]: Implemented and Removed 1)

File: src/native/eventpipe/ep-thread.c [hunk 14]
```diff
@@ -123,6 +119,17 @@ ep_thread_unregister (EventPipeThread *thread)
 
 	ep_return_false_if_nok (thread != NULL);
 
+	for (uint32_t i = 0; i < EP_MAX_NUMBER_OF_SESSIONS; ++i) {
+		EventPipeThreadSessionState *thread_session_state = (EventPipeThreadSessionState *)ep_rt_volatile_load_ptr ((volatile void **)(&thread->session_state [i]));
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.c]: This access to thread->session_state doesn't appear to be following thread safety rules outlined in the header comments:

```
	// Reading from this slot can either be done by taking the buffer manager lock, or by doing a volatile read of the pointer. The volatile
	// read should only occur when running on the OS thread associated with this EventPipeThread object. When reading under the lock the
	// pointer should not be retained past the scope of the lock. When using the volatile read, the pointer should not be retained
	// outside the period where writing_event_in_process == slot_number.
	volatile EventPipeThreadSessionState *session_state [EP_MAX_NUMBER_OF_SESSIONS];
```

The underlying issue is figuring out what would prevent some other thread from deleting the memory pointed to by thread_session_state sometime after executing line 123 and prior to the thread_session_state->session dereference that occurs at line 127. You would either need to use one of the two synchronization mechanisms already in place, add a new mechanism, or avoid accessing the field.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 15]
```diff
@@ -583,69 +569,72 @@ buffer_manager_move_next_event_any_thread (
 
 	buffer_manager->current_event = NULL;
 	buffer_manager->current_buffer = NULL;
-	buffer_manager->current_buffer_list = NULL;
+	buffer_manager->current_thread_session_state = NULL;
 
 	// We need to do this in two steps because we can't hold m_lock and EventPipeThread::m_lock
 	// at the same time.
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c]: This comment appears outdated - EventPipeThread::m_lock no longer exists.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 16]
```diff
@@ -113,20 +113,24 @@ static
 EventPipeBuffer *
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c:119]: The comment above is out of sync, there is no pBuffer argument to this method

File: src/native/eventpipe/ep-buffer-manager.c [hunk 17]
```diff
@@ -942,52 +947,54 @@ ep_buffer_manager_write_event (
 	// Before we pick a buffer, make sure the event is enabled.
 	ep_return_false_if_nok (ep_event_is_enabled (ep_event));
 
+	// Check to see an event thread was specified. If not, then use the current thread.
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c]:
```suggestion
	// Check to see if an event thread was specified. If not, then use the current thread.
```

File: src/native/eventpipe/ep-buffer-manager.c [hunk 18]
```diff
@@ -1253,101 +1203,41 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
...
-							dn_vector_ptr_push_back (&session_states_to_delete, session_state);
-							dn_list_remove (buffer_manager->thread_session_state_list, session_state);
-						}
-					}
+		// stopped at sequence point case
+
+		// the sequence point captured a lower bound for sequence number on each thread, but iterating
+		// through the events we may have observed that a higher numbered event was recorded. If so we
+		// should adjust the sequence numbers upwards to ensure the data in the stream is consistent.
+		EP_SPIN_LOCK_ENTER (&buffer_manager->rt_lock, section2)
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c:1267]: For clarity it may help to add a comment here mentioning that if a thread was exhausted during the event enumeration above it won't be in the session_state_list any longer but its sequence point info has already been updated in the dictionary as part of removing it.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 19]
```diff
@@ -1381,61 +1271,34 @@ ep_buffer_manager_deallocate_buffers (EventPipeBufferManager *buffer_manager)
...
 				buffer = ep_buffer_list_get_and_remove_head (buffer_list);
 			}
 
-			// Now that all the buffer list elements have been freed, free the list itself.
-			ep_buffer_list_free (buffer_list);
-			buffer_list = NULL;
+			// clear the thread session state slot
+			ep_thread_set_session_state (ep_thread_session_state_get_thread (thread_session_state), ep_thread_session_state_get_session (thread_session_state), NULL);
+			// delete the thread session state and transitively the buffer list
+			ep_thread_session_state_free (thread_session_state);
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c:1366]: At the moment deallocate_buffers is called from ep_buffer_manager_free() which is called from ep_session_dec_ref() if the ref count is zero. disable_holding_lock() calls ep_session_dec_ref() and I think given the state of code right now it happens that ref is the last one, but nothing in comments or code I saw suggests that has to remain true in the future. We probably want to update this so that even if disable_holding_lock() isn't releasing the last session reference we still get proper cleanup. The bad case that we wouldn't want to happen is that disable_holding_lock() would complete, the ep_lock would be released, the session index would get reassigned to a new session and then some thread intending to write to the new session winds up writing to the old session instead because we haven't cleared the thread_session_state slot.

I suspect a simple fix would be to add some method like ep_session_close() which is called in disable_holding_lock() prior to the ep_session_dec_ref(). close() would call this function to ensure that we've freed all the buffers and detached all the threads prior to ep_lock being released. For consistency maybe rename this method buffer_manager_close(). ep_buffer_manager_free() would no longer call this method but it could assert that the thread_session_state_list is empty validating that the close() already happened.

**Review by noahfalk — COMMENTED** [review]
This looks pretty nice overall. I did notice a couple potential use-after-free race conditions that we should certainly shore up and we might need to make some perf adjustments but I think this is close.

File: src/native/eventpipe/ep-thread.c (hunk 14 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-thread.c]: Thanks for the catch, I switched from using the ThreadSessionState's session field to just loading the EventPipeSession via `ep_volatile_load_session` and signaling its buffer_manager (if any).

File: src/native/eventpipe/ep-buffer-manager.c (hunk 15 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Updated

File: src/native/eventpipe/ep-buffer-manager.c (hunk 16 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:119]: Updated this and the descriptions in above functions as well.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 18 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:1267]: Added, thanks!

File: src/native/eventpipe/ep-buffer-manager.c (hunk 19 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:1366]: Added ep_session_close() and `buffer_manager_deallocate_buffers` -> `buffer_manager_close`, and added the assert that the list is empty when freeing the buffer_manager.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 20]
```diff
@@ -823,6 +831,13 @@ ep_buffer_manager_alloc (
 	ep_rt_wait_event_alloc (&instance->rt_wait_event, false, true);
 	ep_raise_error_if_nok (ep_rt_wait_event_is_valid (&instance->rt_wait_event));
 
+	instance->thread_session_state_list_snapshot = NULL;
+	if (ep_session_get_session_type (session) == EP_SESSION_TYPE_LISTENER) {
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c]: is there some benefit to special casing the snapshoting to only occur for listener sessions? Conceptually it seems simpler if we treat all buffer manager sessions the same way or we should add some comments about what benefits we get that justifies treating them differently.

File: src/native/eventpipe/ep-thread.c [hunk 21]
```diff
@@ -123,6 +119,20 @@ ep_thread_unregister (EventPipeThread *thread)
...
+		if (thread_session_state == NULL)
+			continue;
+
+		EventPipeSession *session = ep_volatile_load_session (i);
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.c]: Unforetunately this is basically the same free-vs-use-race as before, now with the Session object instead of the ThreadSession object. The session slots have very similar thread-safety requirements as the thread_session slots, just the code comments to warn you of that are missing :(

Imagine that in parallel with this function some other thread is executing disable_holding_lock(). This thread needs to prevent disable_holding_lock() from deleting the session object prior to the call to ep_session_get_buffer_manager() below. The easiest option is probably to be holding the ep lock the entire time so that disable_holding_lock() can't run concurrently.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 20 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: For just allocating the list, I think I mainly wanted to avoid the failure to allocate the list to affect non-listener session_types. But if a session fails here that would indicate bigger problems with memory, right? Will remove the special case here.

As for using the snapshot in the other session types, don't they mainly use `ep_buffer_manager_write_all_buffer_to_file_v4`? I hadn't yet thought about integrating the snapshot logic into the sequence point ordering logic. Thinking about it now

Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: For snapshot timestamp + sequence point timestamp + v4 caller's stop_timestamp coordination, I'm thinking of the following sequence.

`buffer_manager_move_next_event_any_thread` -> `buffer_manager_move_next_event_any_snapshot_thread`
`buffer_manager_move_next_event_same_thread` remains the same.

buffer_manager_get_next_event builds its snapshot as part of the call and sets the snapshot_timestamp to "now"

v4 builds its snapshot in the outermost while loop, where snapshot_timestamp replaces current_timstamp_boundary, so after the nested loop over threads and their events, the expectation is once that loop breaks, the snapshot_list is empty.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 22]
```diff
@@ -573,60 +572,48 @@ buffer_manager_move_next_event_any_thread (
...
+					buffer_manager->current_thread_session_state = thread_session_state;
+					oldest_timestamp = next_event_timestamp;
+				}
 			}
 		}
-		if (thread_session_state_exhausted) {
-			EP_SPIN_LOCK_ENTER (&buffer_manager->rt_lock, section2)
+
+		if (snapshot_thread_session_state_exhausted)
+			dn_list_erase (it);
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c:638]: does the snapshot support having items deleted from the list while in the middle of iterating it? Many enumerable iterators don't support this kind of concurrent modification. Previously the code didn't do concurrent modification because we were iterating a cached copy at the time of deleting from the session thread_state list.

File: src/native/eventpipe/ep-buffer-manager.c [hunk 23]
```diff
@@ -1085,19 +1072,39 @@ ep_buffer_manager_write_all_buffers_to_file_v3 (
...
+	buffer_manager->snapshot_timestamp = stop_timestamp;
+	EP_SPIN_LOCK_ENTER (&buffer_manager->rt_lock, section1)
+		EP_ASSERT (dn_list_empty (buffer_manager->thread_session_state_list_snapshot));
+		DN_LIST_FOREACH_BEGIN (EventPipeThreadSessionState *, thread_session_state, buffer_manager->thread_session_state_list) {
+			EventPipeBufferList *buffer_list = ep_thread_session_state_get_buffer_list (thread_session_state);
+			EventPipeBuffer *buffer = buffer_list->head_buffer;
+			if (buffer && ep_buffer_get_creation_timestamp (buffer) < buffer_manager->snapshot_timestamp)
+				dn_list_push_back (buffer_manager->thread_session_state_list_snapshot, thread_session_state);
+		} DN_LIST_FOREACH_END;
+	EP_SPIN_LOCK_EXIT (&buffer_manager->rt_lock, section1);
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c:1120]: This same block of code appears in each of each of write_all_buffers_v3, write_all_buffers_v4, and get_next_event. How about a helper method `snapshot_threads(timestamp)`?

File: src/native/eventpipe/ep-thread.c [hunk 24]
```diff
@@ -115,25 +115,28 @@ ep_thread_register (EventPipeThread *thread)
...
-		if (session == NULL)
-			continue;
-
-		EventPipeBufferManager *buffer_manager = ep_session_get_buffer_manager (session);
-		EP_ASSERT (buffer_manager != NULL);
-		ep_rt_wait_event_set (ep_buffer_manager_get_rt_wait_event_ref (buffer_manager));
-	}
-
 	bool found = false;
+	EP_LOCK_ENTER (section1)
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.c]: A comment would be handy to tell the reader why we take this lock.

File: src/native/eventpipe/ep-thread.c [hunk 25]
```diff
@@ -115,25 +115,28 @@ ep_thread_register (EventPipeThread *thread)
...
+		for (uint32_t i = 0; i < EP_MAX_NUMBER_OF_SESSIONS; ++i) {
+			EventPipeThreadSessionState *thread_session_state = (EventPipeThreadSessionState *)ep_rt_volatile_load_ptr ((volatile void **)(&thread->session_state [i]));
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.c]: Its probably easier to remove this check than keep it and describe why it is safe. Currently the comments for thread->session_state do not mention accessing the slot using the EP lock. Conservatively signaling every active session probably isn't noticeably different perf-wise.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 22 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:638]: I believe it does if we are manually iterating the nodes in the doubly linked list instead of using the `DN_LIST_FOREACH_BEGIN` macro. The macro [updates the iterator by dereference it to grab the next node](https://github.com/dotnet/runtime/blob/0f30f5dbfd51bf25c1e4660db50de13e25e29f45/src/native/containers/dn-list.h#L142), but this manual loop doesn't have a updater in the loop line, it grabs the next item early on and sets it at the end.

Moreover, the [logic before this PR removed thread_session_states from the list while iterating over the list in the same manner](https://github.com/dotnet/runtime/blob/0f30f5dbfd51bf25c1e4660db50de13e25e29f45/src/native/eventpipe/ep-buffer-manager.c#L1266-L1297), and the native eventpipe tests, although not actively ran and need updating, also suggest removing items in a similar manner
https://github.com/dotnet/runtime/blob/0f30f5dbfd51bf25c1e4660db50de13e25e29f45/src/mono/mono/eventpipe/test/dn-list-tests.c#L1046-L1050

As for using dn_list_erase vs dn_list_remove, I think erase is fine here as it deletes a specific node, remove would iterate and remove all matching nodes, which we shouldn't have in this case.

File: src/native/eventpipe/ep-buffer-manager.c (hunk 23 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:1120]: Added, thanks for the catch, was too hasty when extending the snapshot to all reader paths

File: src/native/eventpipe/ep-thread.c (hunk 24 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-thread.c]: Added the context for signaling the reader thread + grabbing the config lock

File: src/native/eventpipe/ep-thread.c (hunk 25 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-thread.c]: Good point, removed the thread_session_state check

File: src/native/eventpipe/ep-thread.c (hunk 21 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-thread.c]: Added the lock, thanks!

File: src/native/eventpipe/ep-buffer-manager.c (hunk 20 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Extended the snapshot to all reading paths

File: src/native/eventpipe/ep-buffer-manager.c [hunk 26]
```diff
@@ -1171,6 +1193,7 @@ ep_buffer_manager_write_all_buffers_to_file_v4 (
 	*events_written = false;
 
 	EventPipeSequencePoint *sequence_point = NULL;
+	ep_timestamp_t current_timestamp_boundary = stop_timestamp;
```
Comment (noahfalk) [inline src/native/eventpipe/ep-buffer-manager.c]: Nit: defining the variable here appears unnecessary, line 1209 could define it.

File: src/native/eventpipe/ep-thread.c [hunk 27]
```diff
@@ -121,12 +121,15 @@ ep_thread_unregister (EventPipeThread *thread)
 	ep_return_false_if_nok (thread != NULL);
 
 	bool found = false;
+
+	// Thread unregistration is one condition for EventPipeThreadSessionStates to be cleaned up.
+	// Rather than coordinating cross-thread cleanup, restrict the work to each reader thread by
+	// signaling events available for reading.
+	//
+	// Sessions are freed under the config lock, so hold the config lock to ensure
+	// that the buffer_manager pointer is valid for signaling.
```
Comment (noahfalk) [inline src/native/eventpipe/ep-thread.c]:
```suggestion
	// that the session pointer isn't freed while we use it.
```

**Review by noahfalk — APPROVED** [review]
LGTM

File: src/native/eventpipe/ep-buffer-manager.c (hunk 26 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c]: Done, thanks!

File: src/native/eventpipe/ep-thread.c (hunk 27 above)
Comment (mdh1418) [reply src/native/eventpipe/ep-thread.c]: Altered logic to signal the buffer_manager's wait event

File: src/native/eventpipe/ep-buffer-manager.c
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer-manager.c:819]: The correctness of this is that both these fields are accessed using atomic ops on all access. We flip the write buffer to NULL on this thread while holding buffer manager lock and code using the write buffer reads it using atomic ops after they flipped the session in progress using atomic ops. Maybe we should document this in some way since it needs to be enforced through the codebase.

File: src/native/eventpipe/ep-buffer-manager.h
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer-manager.h:107]: We should be more clear exactly what fields are not protected by rt_lock and expected to only be used from the reader thread.

File: src/native/eventpipe/ep-buffer-manager.c
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer-manager.c:582]: Maybe we should have a comment that ownership of thread_session_state is still in thread_session_state_list.

Comment (lateralusX) [inline src/native/eventpipe/ep-buffer-manager.c:909]: Should we do the same assert as on thread_session_state_list that its empty before freeing?

File: src/native/eventpipe/ep-session.c
Comment (lateralusX) [inline src/native/eventpipe/ep-session.c:561]: Curious why we needed did this in the past, converting buffers to read only happens when we flush buffers in ep_session_write_all_buffers_to_file and that is called after ep_session_suspend_write_event. I believe it has been like this for a very long time (maybe from the original implementation), so might be something that was originally needed, but then got carried along without specific reasons.

File: src/native/eventpipe/ep-buffer.c
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer.c:59]: Isn't this still true, that we shouldn't free any buffers that is not in read-only mode or why did we remove this assert?

File: src/native/eventpipe/ep.c
Comment (lateralusX) [inline src/native/eventpipe/ep.c:698]: Why do we need a separate close instead of doing it when session ref_count reach 0? ep_session_dec_ref is called elsewhere, so if we only want to do the close part here and not when we potentially could decrease the ref to 0 elsewhere, then it make sense, but still a little confusing.

File: src/native/eventpipe/ep-session.c
Comment (lateralusX) [inline src/native/eventpipe/ep-session.c:522]: Similar scenario as in buffer manager but this case we rely on a different combined with of flags to sync with write. We first switch the session in the session array to NULL before calling this function and then wait for the session in progress to be cleared from our session. The writer on the other hand first sets the in progress and then loads the session from the array, all using atomic ops.

There is a small very theoretical race but it's not new and existed before these changes as well. If exploited it shouldn't lead to any side effects either, just that the reload of the session after setting the in progress flag, might point to a different session if thread gets suspended long enough before setting the in progress flag and a new session gets created in the same slot.

Maybe we should make this decency on session->index being NULL in the array before calling the yield, like having an assert making sure that the session index in the array is NULL + a comment on why that is critical.

**Review by lateralusX — APPROVED** [review]
I mainly looked at the threading scenarios around the use of the new locking patterns + dependencies around waiting on writer threads to finish up work before terminating sessions, or cleaning up thread state. Made some comments around that, but nothing popped up as a real issue after code reviewing it. It needs a lot of milage over time to build full confidence, but what we have at least appears to be correct. 

I didn't look into any depth around the changes around sequence point handling and ordering, but I assume we have test coverage that would at least trigger errors in-case sequence point handling regressed as part of this change.

I made some smaller comments. Great work!

File: src/native/eventpipe/ep-buffer.c
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer.c:59]: This was a part of the assertion fixes (3rd commit) that I was hitting when testing the Thread lock removal (1st commit). When sessions are disabled or abruptly disconnected, not all buffers may have been converted to read-only. For example the `log_process_info_event` may never be read by the in-proc listener session and ep_buffer_alloc failure. So now that converting buffers to read-only yields for in-progress event writing to complete, we wouldn't be deleting a buffer that a writer thread is writing into.

File: src/native/eventpipe/ep.c
Comment (mdh1418) [reply src/native/eventpipe/ep.c:698]: It was to guarantee that the session being disabled would clear out all buffer_manager resources (including EventPipeThreadSessionStates) before a newly allocated session acquires this session's index. https://github.com/dotnet/runtime/pull/118415#discussion_r2671698456

File: src/native/eventpipe/ep-buffer-manager.c
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:909]: We could, that would just mean we would also need to empty `thread_session_state_list_snapshot` as part of `ep_buffer_manager_close` since we don't guarantee that all events have been read for Listener EventPipe Sessions by the time the session is disabled. Originally, I was thinking that since the `thread_session_state_list` owns data, it's important for those to be cleared to ensure nothing was leaked, whereas the snapshot references the data.

File: src/native/eventpipe/ep-session.c
Comment (mdh1418) [reply src/native/eventpipe/ep-session.c:522]: The `EP_ASSERT (!ep_is_session_enabled` above asserts that the session index in the array is NULL. I'll extend the comment.

File: src/native/eventpipe/ep.c
Comment (mdh1418) [reply src/native/eventpipe/ep.c:698]: Added a clarifying comment on the call to ep_session_close

File: src/native/eventpipe/ep-buffer.c
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer.c:59]: Added a comment in ep_buffer_free that the state is not guaranteed to be read_only

File: src/native/eventpipe/ep-buffer-manager.c
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:909]: Added the clear in ep_buffer_manager_close and asserted that the list is empty.

Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:582]: Added a comment

File: src/native/eventpipe/ep-buffer-manager.h
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.h:107]: Added a border around the reader thread specific fields, and the section begins with stating no rt_lock protections

File: src/native/eventpipe/ep-buffer-manager.c
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:819]: Thanks, added a comment!

File: src/native/eventpipe/ep-session.c
Comment (mdh1418) [reply src/native/eventpipe/ep-session.c:561]: In the past, it used to be responsible for waiting for all threads to finish writing to the session's buffer_manager https://github.com/dotnet/runtime/commit/289d2cf2851f4430a2081a1e66b325f86dbdbbeb#diff-23d22a915fe109f2546833cdf6e695b5f1d2d0def61e5ec4dc389614a3f7ff32

Today, the method no longer suspends, and we no longer need to eagerly convert buffers to read-only since that's done as part of the event processing loop

File: src/native/eventpipe/ep-buffer-manager.c
Comment (lateralusX) [reply src/native/eventpipe/ep-buffer-manager.c:909]: Part of closing down a session, we make sure no more data gets written into the session, waits for pending writers, we then make sure all data gets flushed, shouldn't that make sure we always empty the thread_session_state_list_snapshot, so when we close down the session it should be empty? If that is not the case, would mean we didn't flush all data written into the session when disable the session? Under what scenarios could that happen?

File: src/native/eventpipe/ep-session.c
Comment (lateralusX) [reply src/native/eventpipe/ep-session.c:522]: Since we will loop and yield I think you should have an assert as part of the loop as well, making sure session stays NULL or validate that this method is only called holding the config lock on call, since we shouldn't allocate/free sessions without holding the config lock. I would probably add both asserts, since they are assert, they will only be in debug/checked builds so no perf impact and they will run more frequent make sure the assumption around this locking pattern is enforced over time.

File: src/native/eventpipe/ep-buffer.c
Comment (lateralusX) [inline src/native/eventpipe/ep-buffer.c]: I don't think we should pass in buffer manager here and keep buffer as a standalone entity (it currently have no relationship with buffer manager). The reason why buffer manager lock is needed is because it's how the buffers are used by buffer manager, so no need to assert the lock is held inside ep-buffer.c, just enforce that the lock is taken at callsite.

File: src/native/eventpipe/ep-buffer-manager.c
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer-manager.c:909]: I think the data flushing only happens for File, File Stream, and IPC Streaming sessions https://github.com/dotnet/runtime/blob/2075e8ffaa8cf598dac9c09f5f690778ef1a6c8e/src/native/eventpipe/ep-session.c#L642C1-L648C15

So just the Listener session would not have its events flushed when a session is being disabled, which only occurs when the listener session is reset with a repeat `EnableEvents` invocation and is disabled at https://github.com/dotnet/runtime/blob/2075e8ffaa8cf598dac9c09f5f690778ef1a6c8e/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventPipeEventDispatcher.Threads.cs#L53
On another note I'm also finding out that runtime shutdown doesn't disable a Listener session https://github.com/dotnet/runtime/blob/2075e8ffaa8cf598dac9c09f5f690778ef1a6c8e/src/native/eventpipe/ep.c#L1574-L1577

File: src/native/eventpipe/ep-session.c
Comment (mdh1418) [reply src/native/eventpipe/ep-session.c:522]: Added the assert and moved the comments, thanks!

File: src/native/eventpipe/ep-buffer.c
Comment (mdh1418) [reply src/native/eventpipe/ep-buffer.c]: Removed the arg and added a comment around the current callsite to note why the lock should be held when calling convert_to_read_only. Kept the comments around the lock guarantees in `ep-buffer.h` as they hint how the state should be changed/read.

File: src/native/eventpipe/ep-session.c [hunk 28]
```diff
@@ -543,9 +506,13 @@ ep_session_suspend_write_event (EventPipeSession *session)
 	if (dn_vector_ptr_custom_init (&threads, &params)) {
 		ep_thread_get_threads (&threads);
 		DN_VECTOR_PTR_FOREACH_BEGIN (EventPipeThread *, thread, &threads) {
+			// Frequently ensure the session remains disabled and removed from the session array.
+			// The yield below opens a window for a newly allocated session to inherit this session's index,
```
Comment (noahfalk) [inline src/native/eventpipe/ep-session.c]: the config lock ensures that there is no such window. We only allow new sessions to be created under that lock and right now this thread holds the lock.

Maybe that is what you meant but to me the comment suggests the code has a bug in it.

Comment (mdh1418) [reply src/native/eventpipe/ep-session.c]: Yeah, the comment wasn't as clear as I had hoped when adding it. I added more comments to clarify that this method depends on the config lock being held and the session pointer slot being and remaining NULL throughout its scope for its logic to be correct.
