### PR TITLE
[Arm64] ASIMD Miscellaneous

### LINKED ISSUE #35806: ARM Round to Integer intrinsics
```csharp
namespace System.Runtime.Intrinsics.Arm
{
    public abstract class AdvSimd
    {
        // Alias for RoundToPositiveInfinity, same as for x86
        public static Vector64<float>   Ceiling(Vector64<float> value);
        public static Vector128<double> Ceiling(Vector128<double> value);
        public static Vector128<float>  Ceiling(Vector128<float> value);

        public static Vector64<double>  CeilingScalar(Vector64<double> value);
        public static Vector64<float>   CeilingScalar(Vector64<float> value);

        // Alias for RoundToNegativeInfinity, same as for x86
        public static Vector64<float>   Floor(Vector64<float> value);
        public static Vector128<double> Floor(Vector128<double> value);
        public static Vector128<float>  Floor(Vector128<float> value);

        public static Vector64<double>  FloorScalar(Vector64<double> value);
        public static Vector64<float>   FloorScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Round to Integral, to nearest with ties to Away
        /// For each element result[elem] = Round(value[elem], MidpointRounding.AwayFromZero)
        /// Corresponds to vector forms of FRINTA
        /// </summary>
        public static Vector64<float>   RoundAwayFromZero(Vector64<float> value);
        public static Vector128<double> RoundAwayFromZero(Vector128<double> value);
        public static Vector128<float>  RoundAwayFromZero(Vector128<float> value);

        public static Vector64<double>  RoundAwayFromZeroScalar(Vector64<double> value);
        public static Vector64<float>   RoundAwayFromZeroScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point fused Multiply-Add to accumulator
        /// For each element result[elem] = addend[elem] + left[elem] * right[rightIndex]
        /// Corresponds to vector forms of FRINTI
        /// </summary>
        public static Vector64<float>   RoundCurrentDirection(Vector64<float> value);
        public static Vector128<double> RoundCurrentDirection(Vector128<double> value);
        public static Vector128<float>  RoundCurrentDirection(Vector128<float> value);

        public static Vector64<double>  RoundCurrentDirectionScalar(Vector64<double> value);
        public static Vector64<float>   RoundCurrentDirectionScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Round to Integral, to nearest with ties to Away
        /// For each element result[elem] = Round(value[elem], MidpointRounding.ToEven)
        /// Corresponds to vector forms of FRINTN
        /// </summary>
        public static Vector64<float>   RoundToNearest(Vector64<float> value);
        public static Vector128<double> RoundToNearest(Vector128<double> value);
        public static Vector128<float>  RoundToNearest(Vector128<float> value);

        public static Vector64<double>  RoundToNearestScalar(Vector64<double> value);
        public static Vector64<float>   RoundToNearestScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Round to Integral, to nearest with ties to Away
        /// For each element result[elem] = Round(value[elem], MidpointRounding.ToNegativeInfinity)
        /// Corresponds to vector forms of FRINTM
        /// </summary>
        public static Vector64<float>   RoundToNegativeInfinity(Vector64<float> value);
        public static Vector128<double> RoundToNegativeInfinity(Vector128<double> value);
        public static Vector128<float>  RoundToNegativeInfinity(Vector128<float> value);

        public static Vector64<double>  RoundToNegativeInfinityScalar(Vector64<double> value);
        public static Vector64<float>   RoundToNegativeInfinityScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Round to Integral, to nearest with ties to Away
        /// For each element result[elem] = Round(value[elem], MidpointRounding.ToPositiveInfinity)
        /// Corresponds to vector forms of FRINTP
        /// </summary>
        public static Vector64<float>   RoundToPositiveInfinity(Vector64<float> value);
        public static Vector128<double> RoundToPositiveInfinity(Vector128<double> value);
        public static Vector128<float>  RoundToPositiveInfinity(Vector128<float> value);

        public static Vector64<double>  RoundToPositiveInfinityScalar(Vector64<double> value);
        public static Vector64<float>   RoundToPositiveInfinityScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Round to Integral, to nearest with ties to Away
        /// For each element result[elem] = Round(value[elem], MidpointRounding.ToZero)
        /// Corresponds to vector forms of FRINTZ
        /// </summary>
        public static Vector64<float>   RoundToZero(Vector64<float> value);
        public static Vector128<double> RoundToZero(Vector128<double> value);
        public static Vector128<float>  RoundToZero(Vector128<float> value);

        public static Vector64<double>  RoundToZeroScalar(Vector64<double> value);
        public static Vector64<float>   RoundToZeroScalar(Vector64<float> value);

        // FRINTX - Floating-point Round to Integral exact, using current rounding mode
        // - Not proposed for exposure, .NET doesn't support floating-point exceptions today
    }
}
```

### LINKED ISSUE #36693: ARM Convert Floating-point to/from Integer intrinsics
```csharp
namespace System.Runtime.Intrinsics.Arm
{
    public abstract class AdvSimd
    {
        /// <summary>
        /// Floating-point Convert to Signed integer, rounding to nearest with ties to Away
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.AwayFromZero)
        /// Corresponds to vector forms of FCVTAS
        /// </summary>
        public static Vector64<int> ConvertToInt32RoundAwayFromZero(Vector64<float> value);
        public static Vector128<long> ConvertToInt64RoundAwayFromZero(Vector128<double> value);
        public static Vector128<int> ConvertToInt32RoundAwayFromZero(Vector128<float> value);

        public static Vector64<long> ConvertToInt64RoundAwayFromZeroScalar(Vector64<double> value);
        public static Vector64<int> ConvertToInt32RoundAwayFromZeroScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Convert to Unsigned integer, rounding to nearest with ties to Away
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.AwayFromZero)
        /// Corresponds to vector forms of FCVTAU
        /// </summary>
        public static Vector64<uint> ConvertToUInt32RoundAwayFromZero(Vector64<float> value);
        public static Vector128<ulong> ConvertToUInt64RoundAwayFromZero(Vector128<double> value);
        public static Vector128<uint> ConvertToUInt32RoundAwayFromZero(Vector128<float> value);

        public static Vector64<ulong> ConvertToUInt64RoundAwayFromZeroScalar(Vector64<double> value);
        public static Vector64<uint> ConvertToUInt32RoundAwayFromZeroScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Convert to Signed integer, rounding toward minus infinity
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.ToNegativeInfinity)
        /// Corresponds to vector forms of FCVTMS
        /// </summary>
        public static Vector64<int> ConvertToInt32RoundToNegativeInfinity(Vector64<float> value);
        public static Vector128<long> ConvertToInt64RoundToNegativeInfinity(Vector128<double> value);
        public static Vector128<int> ConvertToInt32RoundToNegativeInfinity(Vector128<float> value);

        public static Vector64<long> ConvertToInt64RoundToNegativeInfinityScalar(Vector64<double> value);
        public static Vector64<int> ConvertToInt32RoundToNegativeInfinityScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Convert to Unsigned integer, rounding toward minus infinity
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.ToNegativeInfinity)
        /// Corresponds to vector forms of FCVTMU
        /// </summary>
        public static Vector64<uint> ConvertToUInt32RoundToNegativeInfinity(Vector64<float> value);
        public static Vector128<ulong> ConvertToUInt64RoundToNegativeInfinity(Vector128<double> value);
        public static Vector128<uint> ConvertToUInt32RoundToNegativeInfinity(Vector128<float> value);

        public static Vector64<ulong> ConvertToUInt64RoundToNegativeInfinityScalar(Vector64<double> value);
        public static Vector64<uint> ConvertToUInt32RoundToNegativeInfinityScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Convert to Signed integer, rounding to nearest with ties to even
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.ToEven)
        /// Corresponds to vector forms of FCVTNS
        /// </summary>
        public static Vector64<int> ConvertToInt32RoundToEven(Vector64<float> value);
        public static Vector128<long> ConvertToInt64RoundToEven(Vector128<double> value);
        public static Vector128<int> ConvertToInt32RoundToEven(Vector128<float> value);

        public static Vector64<long> ConvertToInt64RoundToEvenScalar(Vector64<double> value);
        public static Vector64<int> ConvertToInt32RoundToEvenScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Convert to Unsigned integer, rounding to nearest with ties to even
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.ToEven)
        /// Corresponds to vector forms of FCVTNU
        /// </summary>
        public static Vector64<uint> ConvertToUInt32RoundToEven(Vector64<float> value);
        public static Vector128<ulong> ConvertToUInt64RoundToEven(Vector128<double> value);
        public static Vector128<uint> ConvertToUInt32RoundToEven(Vector128<float> value);

        public static Vector64<ulong> ConvertToUInt64RoundToEvenScalar(Vector64<double> value);
        public static Vector64<uint> ConvertToUInt32RoundToEvenScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Convert to Signed integer, toward positive infinity
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.ToPositiveInfinity)
        /// Corresponds to vector forms of FCVTNS
        /// </summary>
        public static Vector64<int> ConvertToInt32RoundToPositiveInfinity(Vector64<float> value);
        public static Vector128<long> ConvertToInt64RoundToPositiveInfinity(Vector128<double> value);
        public static Vector128<int> ConvertToInt32RoundToPositiveInfinity(Vector128<float> value);

        public static Vector64<long> ConvertToInt64RoundToPositiveInfinityScalar(Vector64<double> value);
        public static Vector64<int> ConvertToInt32RoundToPositiveInfinityScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Convert to Unsigned integer, toward positive infinity
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.ToPositiveInfinity)
        /// Corresponds to vector forms of FCVTNU
        /// </summary>
        public static Vector64<uint> ConvertToUInt32RoundToPositiveInfinity(Vector64<float> value);
        public static Vector128<ulong> ConvertToUInt64RoundToPositiveInfinity(Vector128<double> value);
        public static Vector128<uint> ConvertToUInt32RoundToPositiveInfinity(Vector128<float> value);

        public static Vector64<ulong> ConvertToUInt64RoundToPositiveInfinityScalar(Vector64<double> value);
        public static Vector64<uint> ConvertToUInt32RoundToPositiveInfinityScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Convert to Signed integer, toward zero
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.ToZero)
        /// Corresponds to vector forms of FCVTNS
        /// </summary>
        public static Vector64<int> ConvertToInt32RoundToZero(Vector64<float> value);
        public static Vector128<long> ConvertToInt64RoundToZero(Vector128<double> value);
        public static Vector128<int> ConvertToInt32RoundToZero(Vector128<float> value);

        public static Vector64<long> ConvertToInt64RoundToZeroScalar(Vector64<double> value);
        public static Vector64<int> ConvertToInt32RoundToZeroScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Convert to Unsigned integer, toward zero
        /// For each element result[elem] = ConvertToInteger(value[elem], MidpointRounding.ToZero)
        /// Corresponds to vector forms of FCVTNU
        /// </summary>
        public static Vector64<uint> ConvertToUInt32RoundToZero(Vector64<float> value);
        public static Vector128<ulong> ConvertToUInt64RoundToZero(Vector128<double> value);
        public static Vector128<uint> ConvertToUInt32RoundToZero(Vector128<float> value);

        public static Vector64<ulong> ConvertToUInt64RoundToZeroScalar(Vector64<double> value);
        public static Vector64<uint> ConvertToUInt32RoundToZeroScalar(Vector64<float> value);

        /// <summary>
        /// Floating-point Signed/Unsigned convert to floating-point
        /// For each element result[elem] = ConvertToFloat(value[elem])
        /// Corresponds to vector forms of SCVTF and UCVTF
        /// </summary>
        public static Vector128<double> ConvertToDouble(Vector128<long> value);
        public static Vector128<double> ConvertToDouble(Vector128<ulong> value);

        public static Vector64<double> ConvertToDoubleScalar(Vector64<long> value);
        public static Vector64<double> ConvertToDoubleScalar(Vector64<ulong> value);

        public static Vector64<float> ConvertToSingle(Vector64<int> value);
        public static Vector64<float> ConvertToSingle(Vector64<uint> value);
        public static Vector128<float> ConvertToSingle(Vector128<int> value);
        public static Vector128<float> ConvertToSingle(Vector128<uint> value);

        public static Vector64<float> ConvertToSingleScalar(Vector64<int> value);
        public static Vector64<float> ConvertToSingleScalar(Vector64<uint> value);

        // FCVTZS, FCVTZU, SCVTF, and UCVTF which deal with "fixed-point" are not currently proposed
    }
}
```

### LINKED ISSUE #36701: ARM Misc Intrinsics
```csharp
namespace System.Runtime.Intrinsics.Arm
{
    public abstract class AdvSimd
    {
        /// <summary>
        /// Signed saturating Absolute value
        /// Corresponds to vector forms of SQABS and VQABS
        /// </summary>
        public static Vector64<short> AbsSaturate(Vector64<short> value);
        public static Vector64<int> AbsSaturate(Vector64<int> value);
        public static Vector64<sbyte> AbsSaturate(Vector64<sbyte> value);
        public static Vector128<short> AbsSaturate(Vector128<short> value);
        public static Vector128<int> AbsSaturate(Vector128<int> value);
        public static Vector128<sbyte> AbsSaturate(Vector128<sbyte> value);

        /// <summary>
        /// Floating-point Convert to higher precision Long
        /// Corresponds to vector forms of FCVTL/FCVTL2 and VCVT
        /// </summary>
        public static Vector128<double> ConvertToDoubleLower(Vector128<float> value);
        public static Vector128<double> ConvertToDoubleUpper(Vector128<float> value);

        /// <summary>
        /// Floating-point Convert to lower precision Narrow
        /// Corresponds to vector forms of FCVTN/FCVTN2 and VCVT
        /// </summary>
        public static Vector64<float> ConvertToSingleLower(Vector128<double> value);
        public static Vector128<float> ConvertToSingleUpper(Vector64<float> lower, Vector128<double> value);

        /// <summary>
        /// Signed saturating extract Narrow
        /// Corresponds to vector forms of SQXTN/SQXTUN and VQMOVN
        /// </summary>
        public static Vector64<sbyte> ExtractNarrowingLowerSaturateSigned(Vector128<short> value);
        public static Vector64<short> ExtractNarrowingLowerSaturateSigned(Vector128<int> value);
        public static Vector64<int> ExtractNarrowingLowerSaturateSigned(Vector128<long> value);
		public static Vector64<sbyte> ExtractNarrowingLowerSaturateSigned(Vector128<ushort> value);
        public static Vector64<short> ExtractNarrowingLowerSaturateSigned(Vector128<uint> value);
        public static Vector64<int> ExtractNarrowingLowerSaturateSigned(Vector128<ulong> value);

        /// <summary>
        /// Signed saturating extract Narrow
        /// Corresponds to vector forms of SQXTN2/SQXTUN2 and VQMOVN
        /// </summary>
        public static Vector128<sbyte> ExtractNarrowingUpperSaturateSigned(Vector64<short> lower, Vector128<short> value);
        public static Vector128<short> ExtractNarrowingUpperSaturateSigned(Vector64<int> lower, Vector128<int> value);
        public static Vector128<int> ExtractNarrowingUpperSaturateSigned(Vector64<long> lower, Vector128<long> value);
        public static Vector128<sbyte> ExtractNarrowingUpperSaturateSigned(Vector64<ushort> lower, Vector128<ushort> value);
        public static Vector128<short> ExtractNarrowingUpperSaturateSigned(Vector64<uint> lower, Vector128<uint> value);
        public static Vector128<int> ExtractNarrowingUpperSaturateSigned(Vector64<ulong> lower, Vector128<ulong> value);

        /// <summary>
        /// Unsigned saturating extract Narrow
        /// Corresponds to vector forms of UQXTN and VQMOVN
        /// </summary>
		public static Vector64<byte> ExtractNarrowingLowerSaturateUnsigned(Vector128<ushort> value);
        public static Vector64<ushort> ExtractNarrowingLowerSaturateUnsigned(Vector128<uint> value);
        public static Vector64<uint> ExtractNarrowingLowerSaturateUnsigned(Vector128<ulong> value);

        /// <summary>
        /// Unsigned saturating extract Narrow
        /// Corresponds to vector forms of UQXTN2 and VQMOVN
        /// </summary>
        public static Vector128<byte> ExtractNarrowingUpperSaturateUnsigned(Vector64<ushort> lower, Vector128<ushort> value);
        public static Vector128<ushort> ExtractNarrowingUpperSaturateUnsigned(Vector64<uint> lower, Vector128<uint> value);
        public static Vector128<uint> ExtractNarrowingUpperSaturateUnsigned(Vector64<ulong> lower, Vector128<ulong> value);

        /// <summary>
        /// Signed saturating Negate
        /// Corresponds to vector forms of SQNEG and VQNEG
        /// </summary>
        public static Vector64<short> NegateSaturate(Vector64<short> value);
        public static Vector64<int> NegateSaturate(Vector64<int> value);
        public static Vector64<sbyte> NegateSaturate(Vector64<sbyte> value);
        public static Vector128<short> NegateSaturate(Vector128<short> value);
        public static Vector128<int> NegateSaturate(Vector128<int> value);
        public static Vector128<sbyte> NegateSaturate(Vector128<sbyte> value);

        public abstract class Arm64
        {
            /// <summary>
            /// Signed saturating Absolute value
            /// Corresponds to vector forms of SQABS
            /// </summary>
            public static Vector128<long> AbsSaturate(Vector128<long> value);
            public static Vector64<long> AbsSaturateScalar(Vector64<long> value);

            /// <summary>
            /// Signed saturating Negate
            /// Corresponds to vector forms of SQNEG
            /// </summary>
            public static Vector128<long> NegateSaturate(Vector128<long> value);
            public static Vector64<long> NegateSaturateScalar(Vector64<long> value);

            /// <summary>
            /// Signed/Unsigned Add Long across Vector
            /// Corresponds to vector forms of SADDLV and UADDLV
            /// </summary>
            public static Vector64<byte> AddAcrossWidening(Vector64<byte> value);
            public static Vector64<short> AddAcrossWidening(Vector64<short> value);
            public static Vector64<int> AddAcrossWidening(Vector64<int> value);
            public static Vector64<sbyte> AddAcrossWidening(Vector64<sbyte> value);
            public static Vector64<ushort> AddAcrossWidening(Vector64<ushort> value);
            public static Vector64<uint> AddAcrossWidening(Vector64<uint> value);
            public static Vector128<byte> AddAcrossWidening(Vector128<byte> value);
            public static Vector128<short> AddAcrossWidening(Vector128<short> value);
            public static Vector128<int> AddAcrossWidening(Vector128<int> value);
            public static Vector128<long> AddAcrossWidening(Vector128<long> value);
            public static Vector128<sbyte> AddAcrossWidening(Vector128<sbyte> value);
            public static Vector128<ushort> AddAcrossWidening(Vector128<ushort> value);
            public static Vector128<uint> AddAcrossWidening(Vector128<uint> value);
            public static Vector128<ulong> AddAcrossWidening(Vector128<ulong> value);

            /// <summary>
            /// Signed saturating accumulate of unsigned value
            /// Corresponds to vector forms of SUQADD
            /// </summary>
            public static Vector64<short> AddSaturate(Vector64<short> left, Vector64<ushort> right);
            public static Vector64<int> AddSaturate(Vector64<int> left, Vector64<uint> right);
            public static Vector64<sbyte> AddSaturate(Vector64<sbyte> left, Vector64<byte> right);
            public static Vector128<short> AddSaturate(Vector128<short> left, Vector128<ushort> right);
            public static Vector128<int> AddSaturate(Vector128<int> left, Vector128<uint> right);
            public static Vector128<long> AddSaturate(Vector128<long> left, Vector128<ulong> right);
            public static Vector128<sbyte> AddSaturate(Vector128<sbyte> left, Vector128<byte> right);

            public static Vector64<short> AddSaturateScalar(Vector64<short> left, Vector64<ushort> right);
            public static Vector64<int> AddSaturateScalar(Vector64<int> left, Vector64<uint> right);
            public static Vector64<sbyte> AddSaturateScalar(Vector64<sbyte> left, Vector64<byte> right);
            public static Vector64<long> AddSaturateScalar(Vector64<long> left, Vector64<ulong> right);
            public static Vector128<short> AddSaturateScalar(Vector128<short> left, Vector128<ushort> right);
            public static Vector128<int> AddSaturateScalar(Vector128<int> left, Vector128<uint> right);
            public static Vector128<long> AddSaturateScalar(Vector128<long> left, Vector128<ulong> right);
            public static Vector128<sbyte> AddSaturateScalar(Vector128<sbyte> left, Vector128<byte> right);

            /// <summary>
            /// Signed saturating accumulate of unsigned value
            /// Corresponds to vector forms of USQADD
            /// </summary>
            public static Vector64<byte> AddSaturate(Vector64<byte> left, Vector64<sbyte> right);
            public static Vector64<ushort> AddSaturate(Vector64<ushort> left, Vector64<short> right);
            public static Vector64<uint> AddSaturate(Vector64<uint> left, Vector64<int> right);
            public static Vector128<byte> AddSaturate(Vector128<byte> left, Vector128<sbyte> right);
            public static Vector128<ushort> AddSaturate(Vector128<ushort> left, Vector128<short> right);
            public static Vector128<uint> AddSaturate(Vector128<uint> left, Vector128<int> right);
            public static Vector128<ulong> AddSaturate(Vector128<ulong> left, Vector128<long> right);

            public static Vector64<byte> AddSaturateScalar(Vector64<byte> left, Vector64<sbyte> right);
            public static Vector64<ushort> AddSaturateScalar(Vector64<ushort> left, Vector64<short> right);
            public static Vector64<uint> AddSaturateScalar(Vector64<uint> left, Vector64<int> right);
            public static Vector64<ulong> AddSaturateScalar(Vector64<ulong> left, Vector64<long> right);
            public static Vector128<byte> AddSaturateScalar(Vector128<byte> left, Vector128<sbyte> right);
            public static Vector128<ushort> AddSaturateScalar(Vector128<ushort> left, Vector128<short> right);
            public static Vector128<uint> AddSaturateScalar(Vector128<uint> left, Vector128<int> right);
            public static Vector128<ulong> AddSaturateScalar(Vector128<ulong> left, Vector128<long> right);

            /// <summary>
            /// Floating-point Convert to lower precision Narrow, rounding to odd
            /// Corresponds to vector forms of FCVTXN/FCVTXN2
            /// </summary>
            public static Vector64<float> ConvertToSingleRoundToOddLower(Vector128<double> value);
            public static Vector128<float> ConvertToSingleRoundToOddUpper(Vector64<float> lower, Vector128<double> value);
        }
    }
}
```

### PR DESCRIPTION
**Pull request by echesakov**
Implements the remaining *approved* Arm64 hardware intrinsics:

* AbsSaturate and AbsSaturateScalar
* AddAcrossWidening
* AddSaturate and AddSaturateScalar *(the ones corresponding to suqadd and usqadd instructions)*
* Ceiling and CeilingScalar
* ConvertToDoubleScalar
* ConvertToDoubleUpper
* ConvertToInt32RoundAwayFromZero and ConvertToInt32RoundAwayFromZeroScalar
* ConvertToInt32RoundToEven and ConvertToInt32RoundToEvenScalar
* ConvertToInt32RoundToNegativeInfinity and ConvertToInt32RoundToNegativeInfinityScalar
* ConvertToInt32RoundToPositiveInfinity and ConvertToInt32RoundToPositiveInfinityScalar
* ConvertToInt32RoundToZero and ConvertToInt32RoundToZeroScalar
* ConvertToInt64RoundAwayFromZero and ConvertToInt64RoundAwayFromZeroScalar
* ConvertToInt64RoundToEven and ConvertToInt64RoundToEvenScalar
* ConvertToInt64RoundToNegativeInfinity and ConvertToInt64RoundToNegativeInfinityScalar
* ConvertToInt64RoundToPositiveInfinity and ConvertToInt64RoundToPositiveInfinityScalar
* ConvertToInt64RoundToZero and ConvertToInt64RoundToZeroScalar
* ConvertToSingle and ConvertToSingleScalar
* ConvertToUInt32RoundAwayFromZero and ConvertToUInt32RoundAwayFromZeroScalar
* ConvertToUInt32RoundToEven and ConvertToUInt32RoundToEvenScalar
* ConvertToUInt32RoundToNegativeInfinity and ConvertToUInt32RoundToNegativeInfinityScalar
* ConvertToUInt32RoundToPositiveInfinity and ConvertToUInt32RoundToPositiveInfinityScalar
* ConvertToUInt32RoundToZero and ConvertToUInt32RoundToZeroScalar
* ConvertToUInt64RoundAwayFromZero and ConvertToUInt64RoundAwayFromZeroScalar
* ConvertToUInt64RoundToEven and ConvertToUInt64RoundToEvenScalar
* ConvertToUInt64RoundToNegativeInfinity and ConvertToUInt64RoundToNegativeInfinityScalar
* ConvertToUInt64RoundToPositiveInfinity and ConvertToUInt64RoundToPositiveInfinityScalar
* ConvertToUInt64RoundToZero and ConvertToUInt64RoundToZeroScalar
* Floor and FloorScalar
* NegateSaturate and NegateSaturateScalar
* RoundAwayFromZero and RoundAwayFromZeroScalar
* RoundToNearest and RoundToNearestScalar
* RoundToNegativeInfinity and RoundToNegativeInfinityScalar
* RoundToPositiveInfinity and RoundToPositiveInfinityScalar
* RoundToZero and RoundToZeroScalar

<s>Depends on #38010</s>

Fixes #35806 
Fixes #36693 
Fixes #36701 

@CarolEidt @tannergooding @TamarChristinaArm PTAL

### CODE REVIEW

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/src/jit/hwintrinsiccodegenarm64.cpp [hunk 1]
```diff
@@ -735,6 +735,24 @@ void CodeGen::genHWIntrinsic(GenTreeHWIntrinsic* node)
                 GetEmitter()->emitIns_R_R_R(ins, emitSize, targetReg, op1Reg, op2Reg, opt);
                 break;
 
+            case NI_AdvSimd_Arm64_AddSaturateScalar:
+                if (varTypeIsUnsigned(node->GetAuxiliaryType()) != varTypeIsUnsigned(intrin.baseType))
```
Comment (CarolEidt) [inline src/coreclr/src/jit/hwintrinsiccodegenarm64.cpp:739]: It might be nice to have a getter for `baseType` as well (though perhaps that also needs a better name).
Nothing that needs addressing now, though.

**Review by CarolEidt — APPROVED** [review]
