### PR TITLE
Change Assembly.GetFile(s) to throw when in-memory

### LINKED ISSUE #40154: Assembly.GetFile should throw an explicit exception for memory-loaded assemblies
`Assembly.GetFile` and `Assembly.GetFiles` currently calls `Module.FullyQualifiedName` and then returns a `FileStream` over that path. For assemblies loaded from memory (or any other assembly not loaded directly from a file) this will try to load a file like `"C:\currentdirectory\<Unknown>"` because `Module.FullyQualifiedName` returns constant `<Unknown>` for memory-loaded assemblies. Opening such file will typically fail with `IOException`.

It would be much cleaner to explicitly handle this case in `Assembly.GetFile`/`Assembly.GetFiles` and throw some more specific exception. In theory it's possible that the file `<Unknown>` will actually exist in which case the API would return basically a random stream of data.

### PR DESCRIPTION
**Pull request by agocke**
This code path already threw an exception in most cases, but mostly accidentally.
This changes the code to deliberately throw an exception when the assembly is
in-memory.

Fixes #40154

### CODE REVIEW

File: src/libraries/System.Reflection/tests/AssemblyTests.cs [hunk 1]
```diff
@@ -160,6 +160,35 @@ public void GetFile()
             Assert.Equal(typeof(AssemblyTests).Assembly.GetFile("System.Reflection.Tests.dll").Name, typeof(AssemblyTests).Assembly.Location);
         }
 
+        [Fact]
+        public void GetFile_InMemory()
+        {
+            var inMemBlob = File.ReadAllBytes(SourceTestAssemblyPath);
+            var asm = Assembly.Load(inMemBlob);
+            var methods = asm.GetType("GetFileMethods");
+            var getFile = methods.GetMethod("GetFile");
```
Comment (vitek-karas) [inline src/libraries/System.Reflection/tests/AssemblyTests.cs:169]: I don't understand why we have to call the `GetFile` from within the assembly in question. Much simpler repro/test is to just call `asm.GetFile(...)` directly. There's no difference in doing so either way.

File: src/coreclr/src/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs [hunk 2]
```diff
@@ -356,6 +356,12 @@ internal static RuntimeAssembly InternalLoad(AssemblyName assemblyName, ref Stac
         // given name.  (Name should not include path.)
         public override FileStream? GetFile(string name)
         {
+            if (Location == "")
+            {
+                // Throw if the assembly was loaded from memory, indicated by Location returning an empty string
+                throw new InvalidOperationException(SR.InvalidOperation_NoFileTableInInMemoryAssemblies);
```
Comment (vitek-karas) [inline src/coreclr/src/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs:362]: Alternatively we could throw `FileNotFoundException` - it's not as good as `InvalidOperationException` but it's "close enough" and it is much less likely to be a breaking change (since `FileNotFoundException` derives from `IOException`, so only direct type equality checks would be broken). The specific exception message should be enough really.

I think the higher order reason for this fix is to make the behavior stable/predictable and not "by accident". Having a nice exception is just a bonus.

File: src/libraries/System.Reflection/tests/AssemblyTests.cs (hunk 1 above)
Comment (agocke) [reply src/libraries/System.Reflection/tests/AssemblyTests.cs:169]: Ah yeah, that's a good point. Not sure what I was thinking.

**Comment by agocke** [comment]
This is a little strange -- I seem to have somehow changed the order that interface implementations here are returned. Not sure how that could have happened. Ideas?

**Comment by vitek-karas** [comment]
That is really weird - does it repro locally?

File: src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs [hunk 3]
```diff
@@ -425,6 +431,12 @@ public override Assembly GetSatelliteAssembly(CultureInfo culture, Version? vers
 
         public override FileStream[] GetFiles(bool getResourceModules)
         {
+            if (Location == "")
```
Comment (vitek-karas) [inline src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs:433]: Nit: Maybe file an issue that this code should move to the shared corelib - for example the GetFiles is basically identical (just different coding style a bit).

**Review by vitek-karas — APPROVED** [review]

File: src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs (hunk 3 above)
Comment (steveisok) [reply src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs:433]: /cc @CoffeeFlux

**Comment by agocke** [comment]
Huh, it still seems like interfaces have been re-ordered somehow, but I can't seem to get the mono tests to run locally

File: src/libraries/System.Reflection/tests/TestAssembly/TestAssembly.cs [hunk 4]
```diff
@@ -16,4 +16,4 @@ public static int Foo(string[] args)
          }
          return sum;
     }
-}
+}
```
Comment (CoffeeFlux) [inline src/libraries/System.Reflection/tests/TestAssembly/TestAssembly.cs:19]: Accidental I assume.

File: src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs (hunk 3 above)
Comment (CoffeeFlux) [reply src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs:433]: Some of this should be able to move, just have to keep in mind that changing the layout is hard because we want to match the legacy mono BCL in some cases (or at least, having them differ would result in a bunch of netcore-specific runtime code).

File: src/coreclr/src/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs [hunk 5]
```diff
@@ -360,6 +360,12 @@ internal static RuntimeAssembly InternalLoad(AssemblyName assemblyName, ref Stac
         // given name.  (Name should not include path.)
         public override FileStream? GetFile(string name)
         {
+            if (Location == "")
```
Comment (danmosemsft) [inline src/coreclr/src/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs:363]: Nit, Location declares it's not nullable, so I guess you can use `Location.Length  == 0` which avoids the call to Equals.

File: src/libraries/System.Private.CoreLib/src/Resources/Strings.resx [hunk 6]
```diff
@@ -2674,6 +2674,9 @@
   <data name="InvariantFailed_Cnd" xml:space="preserve">
     <value>Invariant failed: {0}</value>
   </data>
+  <data name="IO_NoFileTableInInMemoryAssemblies" xml:space="preserve">
+    <value>This assembly was loaded from memory and does not have a file table.</value>
```
Comment (danmosemsft) [inline src/libraries/System.Private.CoreLib/src/Resources/Strings.resx:2678]:
```suggestion
    <value>This assembly does not have a file table because it was loaded from memory.</value>
```
?

**Comment by agocke** [comment]
@danmosemsft I'm stuck on this Mono issue. Can you recommend someone to help out?

**Comment by steveisok** [comment]
@CoffeeFlux the mono test failures look weird.  Any thoughts?

**Comment by CoffeeFlux** [comment]
Definitely strange. I'll take a look tomorrow.

**Comment by agocke** [comment]
@CoffeeFlux Any luck?

**Comment by CoffeeFlux** [comment]
Interestingly, these pass locally for me even with the debug configuration.

```
./build.sh mono+libs -c debug
./dotnet.sh build src/libraries/System.Reflection/tests/ /t:Test /p:Configuration=Debug
```
gives me
```
  ----- start Fri Aug 14 17:22:09 EDT 2020 =============== To repro directly: =====================================================
  pushd /Users/ryan/git/runtime/artifacts/bin/System.Reflection.Tests/net5.0-Debug
  /Users/ryan/git/runtime/artifacts/bin/testhost/net5.0-OSX-Debug-x64/dotnet exec --runtimeconfig System.Reflection.Tests.runtimeconfig.json  xunit.console.dll System.Reflection.Tests.dll -xml testResults.xml -nologo -notrait category=OuterLoop -notrait category=failing 
  popd
  ===========================================================================================================
  ~/git/runtime/artifacts/bin/System.Reflection.Tests/net5.0-Debug ~/git/runtime/src/libraries/System.Reflection/tests
    Discovering: System.Reflection.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Reflection.Tests (found 390 of 407 test cases)
    Starting:    System.Reflection.Tests (parallel test collections = on, max threads = 12)
    Finished:    System.Reflection.Tests
  === TEST EXECUTION SUMMARY ===
     System.Reflection.Tests  Total: 1278, Errors: 0, Failed: 0, Skipped: 0, Time: 1.369s
  ~/git/runtime/src/libraries/System.Reflection/tests
  ----- end Fri Aug 14 17:22:12 EDT 2020 ----- exit code 0 ----------------------------------------------------------
```

**Comment by agocke** [comment]
@CoffeeFlux The same is true for me. Should I temporarily disable this test?

**Comment by CoffeeFlux** [comment]
Yeah, let's disable it for now. I'm trying to get the artifacts off CI so I can figure out what's actually going on here, and maybe I'll get somewhere this weekend—think I'm done for today though. If I can't get it sorted out this weekend and it ends up being a serious issue, I'll figure out the backport.

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs [hunk 7]
```diff
@@ -490,6 +490,12 @@ public void IsEnumDefined_Invalid()
         [InlineData(typeof(CompoundClass4<string>), new Type[] { typeof(GenericInterface1<string>), typeof(TI_NonGenericInterface1) })]
         public void ImplementedInterfaces(Type type, Type[] expected)
         {
+            if (PlatformDetection.IsMonoRuntime)
```
Comment (CoffeeFlux) [inline src/libraries/System.Reflection/tests/TypeInfoTests.cs:493]: I believe the proper way to exclude this is to open an issue on Github with the specifics and then apply the ActiveIssue attribute to the method? That file has another example.

Comment (agocke) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:493]: Sounds good

**Review by CoffeeFlux — APPROVED** [review]

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs (hunk 7 above)
Comment (am11) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:494]: We can remove this condition since ActiveIssue is added?

Comment (wzchua) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:494]: I think this has been fixed in #40632

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs [hunk 8]
```diff
@@ -490,6 +491,12 @@ public void IsEnumDefined_Invalid()
...
+            {
+                // Mono re-orders interfaces due to #40593 and it's not clear why
+                return;
+            }
+
```
Comment (jkotas) [inline src/libraries/System.Reflection/tests/TypeInfoTests.cs:499]:
```suggestion
```

Comment (agocke) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs]: Oh, does the attribute suppress running on Mono?

Comment (am11) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs]: Yup, with ActiveIssueAttribute in place using TestRuntimes.Mono, this condition was redundant.

**Comment by jkotas** [comment]
Tests failing on wasm:
```
System.IO.FileNotFoundException : This assembly does not have a file table because it was loaded from memory.

Stack trace
   at System.Reflection.RuntimeAssembly.GetFiles(Boolean getResourceModules)
   at System.Reflection.Assembly.GetFiles()
   at System.Reflection.Tests.AssemblyTests.GetFiles()
```

**Comment by agocke** [comment]
Hmm, I'll claim that this is the right behavior -- wasm is basically load from memory. But how do I exclude these tests from running on wasm?

**Comment by jkotas** [comment]
You can either mark them with `PlatformDetection.IsNotBrowser`.

Or you can make the test robust against assemblies loaded from memory in general case and suppress the failing checks when Location is empty string. It would be nice to be able to run all tests in single file mode eventually, even outside Browser.

**Comment by jkotas** [comment]
Opened #40885 on the test failure
