### PR TITLE
[mono] Fix Vector<T>.IsSupported intrinsic

### LINKED ISSUE #88983: [mono] Tests failing `System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.*` due to Specified type is not supported
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=341298

Affected pipelines:
- runtime-extra-platforms

Build error legs:
- net8.0-windows-Release-x64-Mono_Release-Windows.11.Amd64.Client.Open
- net8.0-windows-Release-x64-Mono_Release-Windows.Amd64.Server2022.Open
- net8.0-windows-Release-x64-Mono_Release-Windows.81.Amd64.Open

Tests failing: 
- `System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.*`

Pull request: https://github.com/dotnet/runtime/pull/88723

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorPattern": "System\\.Runtime\\.Intrinsics\\.Tests\\.Vectors\\.Vector128Tests\\.\\w+\\s\\[FAIL\\]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=341298
**Error message validated:** `System\.Runtime\.Intrinsics\.Tests\.Vectors\.Vector128Tests\.\w+\s\[FAIL\]`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/17/2023 8:15:44 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[372550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550&view=ms.vss-test-web.build-test-results-tab&runId=7912582&resultId=164114)||
|[372445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445&view=ms.vss-test-web.build-test-results-tab&runId=7908646&resultId=168080)|dotnet/runtime#90270|
|[372307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307&view=ms.vss-test-web.build-test-results-tab&runId=7903972&resultId=163616)||
|[372186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372186)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntShiftLeftTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372186&view=ms.vss-test-web.build-test-results-tab&runId=7899988&resultId=161747)||
|[372071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372071)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372071&view=ms.vss-test-web.build-test-results-tab&runId=7896140&resultId=163637)||
|[371811](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371811)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371811&view=ms.vss-test-web.build-test-results-tab&runId=7889786&resultId=163799)||
|[371518](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371518)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntShiftRightLogicalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371518&view=ms.vss-test-web.build-test-results-tab&runId=7883682&resultId=147300)||
|[371313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371313)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371313&view=ms.vss-test-web.build-test-results-tab&runId=7879790&resultId=163210)|dotnet/runtime#90413|
|[370857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370857)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370857&view=ms.vss-test-web.build-test-results-tab&runId=7868352&resultId=147621)||
|[370244](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370244)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370244&view=ms.vss-test-web.build-test-results-tab&runId=7856508&resultId=157020)||
|[369565](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369565)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369565&view=ms.vss-test-web.build-test-results-tab&runId=7850642&resultId=158956)|dotnet/runtime#90304|
|[369870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369870)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369870&view=ms.vss-test-web.build-test-results-tab&runId=7849258&resultId=163179)|dotnet/runtime#89712|
|[369604](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369604)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369604&view=ms.vss-test-web.build-test-results-tab&runId=7840440&resultId=168563)|dotnet/runtime#90150|
|[369496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496&view=ms.vss-test-web.build-test-results-tab&runId=7836780&resultId=169565)||
|[369482](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369482)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369482&view=ms.vss-test-web.build-test-results-tab&runId=7836402&resultId=157800)|dotnet/runtime#90298|
|[369160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369160)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369160&view=ms.vss-test-web.build-test-results-tab&runId=7829094&resultId=154902)|dotnet/runtime#90199|
|[368974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368974)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntShiftLeftTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368974&view=ms.vss-test-web.build-test-results-tab&runId=7826116&resultId=156064)|dotnet/runtime#90119|
|[368875](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368875)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368875&view=ms.vss-test-web.build-test-results-tab&runId=7819702&resultId=164017)||
|[368230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368230)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntShiftRightLogicalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368230&view=ms.vss-test-web.build-test-results-tab&runId=7801898&resultId=163214)|dotnet/runtime#90184|
|[368204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368204)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368204&view=ms.vss-test-web.build-test-results-tab&runId=7800764&resultId=148321)|dotnet/runtime#90225|
|[367894](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367894)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367894&view=ms.vss-test-web.build-test-results-tab&runId=7791350&resultId=162777)|dotnet/runtime#90150|
|[367870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367870)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367870&view=ms.vss-test-web.build-test-results-tab&runId=7790480&resultId=162493)||
|[367380](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367380)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367380&view=ms.vss-test-web.build-test-results-tab&runId=7777202&resultId=155722)||
|[367235](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367235)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367235&view=ms.vss-test-web.build-test-results-tab&runId=7775588&resultId=146996)|dotnet/runtime#90119|
|[366678](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366678)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366678&view=ms.vss-test-web.build-test-results-tab&runId=7767114&resultId=163472)|dotnet/runtime#89997|
|[366629](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366629)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366629&view=ms.vss-test-web.build-test-results-tab&runId=7757626&resultId=157463)|dotnet/runtime#87108|
|[366404](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366404)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntShiftLeftTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366404&view=ms.vss-test-web.build-test-results-tab&runId=7750168&resultId=163496)||
|[365849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365849)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365849&view=ms.vss-test-web.build-test-results-tab&runId=7739850&resultId=157495)||
|[365172](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365172)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntShiftRightLogicalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365172&view=ms.vss-test-web.build-test-results-tab&runId=7723050&resultId=163539)||
|[364942](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364942)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364942&view=ms.vss-test-web.build-test-results-tab&runId=7717340&resultId=163927)||
|[364831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364831)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364831&view=ms.vss-test-web.build-test-results-tab&runId=7713930&resultId=147971)||
|[364732](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364732)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntShiftRightLogicalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364732&view=ms.vss-test-web.build-test-results-tab&runId=7711042&resultId=147569)||
|[364492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364492)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364492&view=ms.vss-test-web.build-test-results-tab&runId=7705272&resultId=163263)||
|[364028](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364028)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364028&view=ms.vss-test-web.build-test-results-tab&runId=7695380&resultId=155377)||
|[363818](https://dev.azure.com/dnceng-public/public/_build/results?buildId=363818)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=363818&view=ms.vss-test-web.build-test-results-tab&runId=7690100&resultId=157917)|dotnet/runtime#87108|
|[363584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=363584)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=363584&view=ms.vss-test-web.build-test-results-tab&runId=7684718&resultId=155400)|dotnet/runtime#89997|
|[363283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=363283)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=363283&view=ms.vss-test-web.build-test-results-tab&runId=7677048&resultId=148191)||
|[362691](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362691)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362691&view=ms.vss-test-web.build-test-results-tab&runId=7662990&resultId=147869)||
|[362632](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362632)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362632&view=ms.vss-test-web.build-test-results-tab&runId=7661960&resultId=147772)|dotnet/runtime#89966|
|[362128](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362128)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntStoreUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362128&view=ms.vss-test-web.build-test-results-tab&runId=7649640&resultId=147396)|dotnet/runtime#89813|
|[361950](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361950)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361950&view=ms.vss-test-web.build-test-results-tab&runId=7646166&resultId=150861)|dotnet/runtime#89421|
|[361849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361849)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361849&view=ms.vss-test-web.build-test-results-tab&runId=7643108&resultId=153383)||
|[361682](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361682)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361682&view=ms.vss-test-web.build-test-results-tab&runId=7638452&resultId=163760)|dotnet/runtime#89421|
|[361365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361365)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361365&view=ms.vss-test-web.build-test-results-tab&runId=7628820&resultId=159488)|dotnet/runtime#89809|
|[361283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361283)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntShiftLeftTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361283&view=ms.vss-test-web.build-test-results-tab&runId=7627454&resultId=155748)||
|[360331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360331)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntStoreAlignedTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360331&view=ms.vss-test-web.build-test-results-tab&runId=7603212&resultId=163158)||
|[360323](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360323)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360323&view=ms.vss-test-web.build-test-results-tab&runId=7602862&resultId=164257)|dotnet/runtime#89726|
|[359818](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359818)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359818&view=ms.vss-test-web.build-test-results-tab&runId=7590110&resultId=163750)|dotnet/runtime#89809|
|[359789](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359789)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359789&view=ms.vss-test-web.build-test-results-tab&runId=7589116&resultId=156563)|dotnet/runtime#89813|
|[359654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359654)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359654&view=ms.vss-test-web.build-test-results-tab&runId=7582958&resultId=146846)||
|[359427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359427)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359427&view=ms.vss-test-web.build-test-results-tab&runId=7577290&resultId=145898)|dotnet/runtime#89260|
|[358612](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358612)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358612&view=ms.vss-test-web.build-test-results-tab&runId=7554084&resultId=164407)||
|[358004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358004)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358004&view=ms.vss-test-web.build-test-results-tab&runId=7537454&resultId=161150)||
|[357256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357256)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntShiftRightArithmeticTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357256&view=ms.vss-test-web.build-test-results-tab&runId=7520074&resultId=157524)|dotnet/runtime#89421|
|[357141](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357141)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.IsSupportedUInt64](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357141&view=ms.vss-test-web.build-test-results-tab&runId=7517118&resultId=163416)||
|[357013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357013)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=357013&view=ms.vss-test-web.build-test-results-tab&runId=7513006&resultId=162877)|dotnet/runtime#89421|
|[356877](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356877)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356877&view=ms.vss-test-web.build-test-results-tab&runId=7509420&resultId=163082)||
|[356640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356640)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntShiftLeftTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356640&view=ms.vss-test-web.build-test-results-tab&runId=7504956&resultId=167858)||
|[356525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356525)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356525&view=ms.vss-test-web.build-test-results-tab&runId=7501196&resultId=163382)||
|[356351](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356351)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356351&view=ms.vss-test-web.build-test-results-tab&runId=7496924&resultId=163366)|dotnet/runtime#89638|
|[356170](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356170)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356170&view=ms.vss-test-web.build-test-results-tab&runId=7491690&resultId=163121)||
|[355784](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355784)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355784&view=ms.vss-test-web.build-test-results-tab&runId=7481904&resultId=133064)||
|[355019](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355019)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355019&view=ms.vss-test-web.build-test-results-tab&runId=7465132&resultId=127750)||
|[354414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354414)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354414&view=ms.vss-test-web.build-test-results-tab&runId=7448710&resultId=163858)||
|[353999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353999)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353999&view=ms.vss-test-web.build-test-results-tab&runId=7440756&resultId=162845)|dotnet/runtime#89569|
|[353633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353633)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353633&view=ms.vss-test-web.build-test-results-tab&runId=7432364&resultId=149815)||
|[353096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353096)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353096&view=ms.vss-test-web.build-test-results-tab&runId=7418970&resultId=155792)||
|[353048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353048)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353048&view=ms.vss-test-web.build-test-results-tab&runId=7417368&resultId=134065)|dotnet/runtime#89467|
|[352690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352690)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadUnsafeTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352690&view=ms.vss-test-web.build-test-results-tab&runId=7416840&resultId=154624)|dotnet/runtime#89431|
|[352553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352553)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352553&view=ms.vss-test-web.build-test-results-tab&runId=7406364&resultId=163226)|dotnet/runtime#89498|
|[352326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352326)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352326&view=ms.vss-test-web.build-test-results-tab&runId=7399796&resultId=162679)||
|[351937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351937)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351937&view=ms.vss-test-web.build-test-results-tab&runId=7389948&resultId=163068)||
|[351866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351866)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351866&view=ms.vss-test-web.build-test-results-tab&runId=7388262&resultId=152621)||
|[351758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351758)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351758&view=ms.vss-test-web.build-test-results-tab&runId=7385702&resultId=163182)|dotnet/runtime#89223|
|[351723](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351723)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351723&view=ms.vss-test-web.build-test-results-tab&runId=7384706&resultId=152616)||
|[351065](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351065)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351065&view=ms.vss-test-web.build-test-results-tab&runId=7369756&resultId=163681)||
|[351063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351063)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.IsSupportedSByte](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351063&view=ms.vss-test-web.build-test-results-tab&runId=7369680&resultId=163166)|dotnet/runtime#89421|
|[350917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350917)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350917&view=ms.vss-test-web.build-test-results-tab&runId=7366660&resultId=168599)|dotnet/runtime#89308|
|[350495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350495)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350495&view=ms.vss-test-web.build-test-results-tab&runId=7356516&resultId=162673)||
|[350271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350271)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350271&view=ms.vss-test-web.build-test-results-tab&runId=7352226&resultId=154500)||
|[349510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349510)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349510&view=ms.vss-test-web.build-test-results-tab&runId=7333960&resultId=163716)||
|[349328](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349328)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.IsSupportedUIntPtr](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349328&view=ms.vss-test-web.build-test-results-tab&runId=7327288&resultId=163046)||
|[349156](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349156)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349156&view=ms.vss-test-web.build-test-results-tab&runId=7322152&resultId=163816)||
|[349045](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349045)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349045&view=ms.vss-test-web.build-test-results-tab&runId=7319152&resultId=163830)||
|[348654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348654)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntShiftRightLogicalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348654&view=ms.vss-test-web.build-test-results-tab&runId=7308928&resultId=163458)||
|[348291](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348291)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348291&view=ms.vss-test-web.build-test-results-tab&runId=7299350&resultId=155265)||
|[347426](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347426)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347426&view=ms.vss-test-web.build-test-results-tab&runId=7279794&resultId=167946)||
|[346915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346915)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346915&view=ms.vss-test-web.build-test-results-tab&runId=7260872&resultId=163069)||
|[346860](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346860)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346860&view=ms.vss-test-web.build-test-results-tab&runId=7258484&resultId=163870)||
|[346590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346590)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346590&view=ms.vss-test-web.build-test-results-tab&runId=7250952&resultId=154176)|dotnet/runtime#89260|
|[346479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346479)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346479&view=ms.vss-test-web.build-test-results-tab&runId=7248240&resultId=144224)||
|[346114](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346114)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntLoadUnsafeIndexTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=346114&view=ms.vss-test-web.build-test-results-tab&runId=7239958&resultId=163593)||
|[345752](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345752)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345752&view=ms.vss-test-web.build-test-results-tab&runId=7230684&resultId=162366)||
|[345634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345634)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NUIntShiftRightLogicalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345634&view=ms.vss-test-web.build-test-results-tab&runId=7227954&resultId=122530)||
|[345419](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345419)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345419&view=ms.vss-test-web.build-test-results-tab&runId=7222922&resultId=124514)||
|[345080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345080)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=345080&view=ms.vss-test-web.build-test-results-tab&runId=7214620&resultId=147546)|dotnet/runtime#89187|
|[344997](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344997)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntStoreAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344997&view=ms.vss-test-web.build-test-results-tab&runId=7212754&resultId=149583)||
|[344698](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344698)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntShiftRightArithmeticTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344698&view=ms.vss-test-web.build-test-results-tab&runId=7205982&resultId=161771)||
|[344129](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344129)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344129&view=ms.vss-test-web.build-test-results-tab&runId=7190334&resultId=160669)||
|[343954](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954)|dotnet/runtime|[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128NIntLoadAlignedNonTemporalTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954&view=ms.vss-test-web.build-test-results-tab&runId=7186616&resultId=162904)|dotnet/runtime#88723|
Displaying 100 of 107 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|28|107|

### PR DESCRIPTION
**Pull request by ivanpovazan**
This PR fixes a regression introduced in: https://github.com/dotnet/runtime/pull/86546 where `Vector<T>.IsSupported` tests started failing on `win-x64` platform.

The `Vector<T>.IsSupported` is now intrinsified properly when the type parameter T is a primitive type on all supported 
platforms.

---
Fixes https://github.com/dotnet/runtime/issues/88983

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Review by SamMonoRT — APPROVED** [review]

**Comment by lewing** [comment]
This appears to fail for MONO_TYPE_CHAR?  which is causing problems in the tests

**Comment by vargaz** [comment]
Vector128.IsSupported returns false for char.

**Comment by lewing** [comment]
Ah yeah, here is one of the wasm failures
```
        [wasm test-browser] fail: MONO_WASM:    at System.Text.Json.JsonReaderHelper.GetUtf8ByteCount(ReadOnlySpan`1 )
        [wasm test-browser]          at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 , JsonDocumentOptions )
        [wasm test-browser]          at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object , BindingFlags )
        [wasm test-browser]       Error: Specified type is not supported
        [wasm test-browser]           at sr (http://127.0.0.1:44753/_framework/dotnet.runtime.js:3:33283)
        [wasm test-browser]           at Br (http://127.0.0.1:44753/_framework/dotnet.runtime.js:3:42678)
        [wasm test-browser]           at p.javaScriptExports.call_entry_point (http://127.0.0.1:44753/_framework/dotnet.runtime.js:3:199925)
        [wasm test-browser]           at Object.Il [as runMain] (http://127.0.0.1:44753/_framework/dotnet.runtime.js:3:166662)
        [wasm test-browser]           at run (http://127.0.0.1:44753/test-main.js:390:50)
        [wasm test-browser]           at async http://127.0.0.1:44753/test-main.js:406:1
```
i

**Comment by lewing** [comment]
I fixed the throwhelpers to share the same logic.

**Comment by matouskozak** [comment]
LGTM. 

I see that the runtime-extra-platforms test that was failing before `windows-x64 Release AllSubsets_Mono` in https://github.com/dotnet/runtime/issues/88983 started failing in a different way (I already saw it fail on main before so not caused by this PR).

File: src/mono/mono/mini/simd-intrinsics.c [hunk 1]
```diff
@@ -2346,11 +2346,19 @@ emit_vector64_vector128_t (MonoCompile *cfg, MonoMethod *cmethod, MonoMethodSign
...
+	if (id == SN_get_IsSupported) {
+		MonoInst *ins = NULL;
+		EMIT_NEW_ICONST (cfg, ins, is_primitive_element_type ? 1 : 0);
+		return ins;
+	}
+
+	if (!is_primitive_element_type)
 		return NULL;
 
+	gboolean supported = TRUE;
```
Comment (matouskozak) [inline src/mono/mono/mini/simd-intrinsics.c:2361]: I would maybe remove the `gboolean supported` variable and replace the `supported = False;` with `return NULL;`  as we now deal with `SN_get_IsSupported` earlier. However, it is just my feeling and feel free to merge.)

**Review by matouskozak — APPROVED** [review]

File: src/mono/mono/mini/simd-intrinsics.c (hunk 1 above)
Comment (ivanpovazan) [reply src/mono/mono/mini/simd-intrinsics.c]: I agree, thanks!

**Comment by premun** [comment]
Just an FYI, we've seen a spike of failed jobs on OSX 13 AppleTV queue originating from this PR:

```kql
WorkItems
| where QueueName == "osx.13.amd64.appletv.open" and Finished > now() - 3d and Finished < now() - 1d
| where ExitCode != 0
| join kind=inner Jobs on JobId
| summarize count() by Source
```

This happened about 2 days ago and was enough to trigger an alert for our infra.
I am not sure if there wasn't a unrelated infra issue but I suggest re-running this PR on an appletv queue.

**Comment by ivanpovazan** [comment]
@SamMonoRT If I don't manage to resolve the failures introduced by this PR, we can disable the failing Vector128<T> tests on `win-x64` to unblock clean `runtime-extra-platforms` pipeline for RC1, and fix the issue immediately after it.

File: src/mono/mono/mini/simd-intrinsics.c [hunk 2]
```diff
@@ -2346,9 +2346,16 @@ emit_vector64_vector128_t (MonoCompile *cfg, MonoMethod *cmethod, MonoMethodSign
 
 	MonoClass *klass = cmethod->klass;
 	MonoType *etype = mono_class_get_context (klass)->class_inst->type_argv [0];
-	gboolean supported = TRUE;
+	gboolean is_primitive_element_type = MONO_TYPE_IS_VECTOR_PRIMITIVE (etype);
 
-	if (!MONO_TYPE_IS_VECTOR_PRIMITIVE (etype))
```
Comment (fanyang-mono) [inline src/mono/mono/mini/simd-intrinsics.c:2351]: Same change should be done to `emit_sys_numerics_vector_t` as well.

Comment (ivanpovazan) [reply src/mono/mono/mini/simd-intrinsics.c:2351]: I have reverted the initial change and made another attempt to properly fix this.

Regarding `emit_sys_numerics_vector_t` and `emit_vector256_t` those functions are actually doing the right thing:
1. Firstly, filtering out non-primitive types with `MONO_TYPE_IS_VECTOR_PRIMITIVE`
2. Second, returning `TRUE` for `SN_get_IsSupported` intrinsic


- `emit_sys_numerics_vector_t`: 
https://github.com/dotnet/runtime/blob/6c38f2ceafa32fae0d775f862fb0fe43af5c200d/src/mono/mono/mini/simd-intrinsics.c#L3103-L3121

- `emit_vector256_t`:
https://github.com/dotnet/runtime/blob/6c38f2ceafa32fae0d775f862fb0fe43af5c200d/src/mono/mono/mini/simd-intrinsics.c#L5284-L5301

**Comment by ivanpovazan** [comment]
I have opened several tracking issues for failures on `runtime-extra-platforms` none of which are related to these changes.

This PR now seems to be a proper fix - originally reported regressions on `win-x64` are gone.

@vargaz @lewing @SamMonoRT do you want to take another look before I merge this?

**Review by fanyang-mono — APPROVED** [review]
LGTM!

**Review by jandupej — APPROVED** [review]

**Review by vargaz — APPROVED** [review]
