### PR TITLE
Fix passing too small args for PUTARG_STK on macOS arm64 ABI

### LINKED ISSUE #66720: Error in Int16 variables when running in M1 macs
**Version Used**: 
.NET 6.0.1  - **Apple M1 Pro**
.NET SDK 6.0.201

**Steps to Reproduce**:

1. Open the attached project uint-bug.zip in an "Apple Silicon" machine. I've used a 16" Macbook pro, M1 pro chip.
2. dotnet run --configuration Debug

**Expected Behavior**:
It should not have any errors. We are just assigning an Int16 to an Int16, so there is no possibility to overflow.

**Actual Behavior**:
Unhandled exception. System.AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.) (Arithmetic operation resulted in an overflow.)....

**Description**
This bug happens in Apple M1 chips, not in intel machines. I am not sure about iphone chips or other arm targets.
It is happening in a big application without threads, but it was difficult to reduce to a simple program that could be analyzed. To be able to reproduce it always, I had to add a parallel loop to make the effect evident. But it also happens in the big app wihtout threads at all. Also in this example, if you disable the parallel loop and change it to a single loop, I can still reproduce while debugging but not from the command line.

It looks like the compiler passes the full int32 value of an int16 variable (filling the upper bits with garbage, which causes the overflow).

If you change the "checked" line to "unchecked, then you get lines like this:0x2672 = 0x80F62672

0x37 = 0x80F60037
0x396 = 0x80F60396

Which seem to indicate the int16 number is just the original number with garbage in the upper bits)

When you debug the code, you see:

image

So the value it is trying to set is 0x81080EEB  
If you move up in the stack trace, in the clone method we pass 0xEEB:

image

But in the class constructor, aVar4 changed from 0xEEB to 0x8180EEB:
image

I can reproduce it 100% in this machine, but I don't know if it will happen in others, even other arm macs. I hope this information is sufficient to figure out what is going on, but any extra information please ask.

[uint-bug.zip](https://github.com/dotnet/roslyn/files/8258045/uint-bug.zip)

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #66720

I got far enough that I figured I would submit what I think is a good fix.

cc @dotnet/jit-contrib PTAL @AndyAyersMS

### CODE REVIEW

**Review by AndyAyersMS — APPROVED** [review]
Thanks.

We should port this one back to 6.0.

File: src/coreclr/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -815,32 +806,35 @@ void CodeGen::genPutArgStk(GenTreePutArgStk* treeNode)
...
+                emitAttr storeAttr = emitTypeSize(source->TypeGet());
                 emit->emitIns_S_R(INS_str, storeAttr, srcReg, varNumOut, argOffsetOut);
                 argOffsetOut += EA_SIZE_IN_BYTES(storeAttr);
             }
             assert(argOffsetOut <= argOffsetMax); // We can't write beyond the outgoing arg area
             return;
         }
 
+        var_types slotType = genActualType(source);
         if (compMacOsArm64Abi())
```
Comment (am11) [inline src/coreclr/jit/codegenarmarch.cpp:818]: @jakobbotsch, just for my own education; is it specific to mac ABI? i.e. if we apply the same classification to linux and windows arm64, it will break putarg on those targets?

This TODO is probably related: https://github.com/dotnet/runtime/blob/d682d680684773530cfcf1c5fc7650dd640ddda9/src/coreclr/jit/morph.cpp#L736-L738

Comment (jakobbotsch) [reply src/coreclr/jit/codegenarmarch.cpp:818]: macOS arm64 ABI is different in that multiple small arguments can be packed into the same stack slot. It means we have different behavior in some places in the JIT, and that different behavior was wrong here.
The behavior for the other ABIs did not have this bug.

File: src/coreclr/jit/codegenarmarch.cpp [hunk 2]
```diff
@@ -815,32 +806,35 @@ void CodeGen::genPutArgStk(GenTreePutArgStk* treeNode)
...
-                emitAttr storeAttr = emitTypeSize(targetType);
+                emitAttr storeAttr = emitTypeSize(source->TypeGet());
                 emit->emitIns_S_R(INS_str, storeAttr, srcReg, varNumOut, argOffsetOut);
                 argOffsetOut += EA_SIZE_IN_BYTES(storeAttr);
             }
             assert(argOffsetOut <= argOffsetMax); // We can't write beyond the outgoing arg area
             return;
         }
 
+        var_types slotType = genActualType(source);
```
Comment (sandreenko) [inline src/coreclr/jit/codegenarmarch.cpp:817]: do I understand this change correctly that now we have such slot types:
1byte -  TYP_BYTE
2bytes - TYP_SHORT
4bytes - TYP_LONG (was TYP_INT before the change).
8bytes - TYP_LONG
?
so if we pass two `TYP_INT ` on the stack, in one 8byte stack slot, don't we override anything?

Comment (jakobbotsch) [reply src/coreclr/jit/codegenarmarch.cpp:817]: Not totally sure I understand. `genActualType(TYP_INT)` returns `TYP_INT`, not `TYP_LONG`.

The difference before was that we used the real type of the operand to decide on how much to store on the stack. That's not right, a small-typed operand still produces a value of type `genActualType(operand)` and it is the `PUTARG_STK` node that decides how much should be put on the stack. So we had a problem for e.g. a `TYP_SHORT` indirection feeding into a `TYP_INT` parameter.

A `TYP_INT` indirection feeding into a 4 byte parameter will still only store 4 bytes on the stack.

Comment (sandreenko) [reply src/coreclr/jit/codegenarmarch.cpp:817]: I see, thanks!
