### PR TITLE
Don't test ANSI any mapping on non en-US locales.

### LINKED ISSUE #33925: Local failure of Interop.PInvoke / AsAnyTests.RunBestFitMappingTests
Environment: Windows 10 Pro Insider Preview, Build 19587 / ko-KR
Test output:
```

C:\Users\gotos\source\repos\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Interop\PInvoke\AsAny\AsAnyTest\AsAny
Test.cmd (2 seconds)

#################################################################
Output of failing tests:

[C:\Users\gotos\source\repos\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Interop\PInvoke\AsAny\AsAnyTest\AsAn
yTest.cmd]:


Return code:      1
Raw output file:      C:\Users\gotos\source\repos\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Reports\Interop
.PInvoke\AsAny\AsAnyTest\AsAnyTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\Users\gotos\source\repos\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" AsAnyT
est.dll
Scenario : Checking Marshal AsAny for sbyte array
Scenario : Checking Marshal AsAny for byte array
Scenario : Checking Marshal AsAny for short array
Scenario : Checking Marshal AsAny for ushort array
Scenario : Checking Marshal AsAny for Int array
Scenario : Checking Marshal AsAny for uint array
Scenario : Checking Marshal AsAny for long array
Scenario : Checking Marshal AsAny for ulong array
Scenario : Checking Marshal AsAny for float array
Scenario : Checking Marshal AsAny for double array
Scenario : Checking Marshal AsAny for char array
Scenario : Checking Marshal AsAny for bool array
Scenario : Checking Marshal AsAny for IntPtr array
Scenario : Checking Marshal AsAny for UIntPtr array
Scenario: Running Layout Tests:
------------------------
------------------------
System.ArgumentException: Cannot marshal: Encountered unmappable character.
   at System.Runtime.InteropServices.Marshal.StringToAnsiString(String s, Byte* buffer, Int32 bufferLength, Boolean best
Fit, Boolean throwOnUnmappableChar)
   at System.StubHelpers.AnsiCharMarshaler.DoAnsiConversion(String str, Boolean fBestFit, Boolean fThrowOnUnmappableChar
, Int32& cbLength)
   at System.StubHelpers.CSTRMarshaler.ConvertToNative(Int32 flags, String strManaged, IntPtr pNativeBuffer)
   at System.StubHelpers.AsAnyMarshaler.ConvertStringToNative(String pManagedHome, Int32 dwFlags)
   at System.StubHelpers.AsAnyMarshaler.ConvertToNative(Object pManagedHome, Int32 dwFlags)
   at AsAnyTests.PassAnsiStrTT(Object i, Boolean isIncludeUnMappableChar)
   at AsAnyTests.TestAnsiStringBestFitMapping() in C:\Users\gotos\source\repos\runtime\src\coreclr\tests\src\Interop\PIn
voke\AsAny\AsAnyTest.cs:line 437
   at AsAnyTests.RunBestFitMappingTests() in C:\Users\gotos\source\repos\runtime\src\coreclr\tests\src\Interop\PInvoke\A
sAny\AsAnyTest.cs:line 342
   at AsAnyTests.Main() in C:\Users\gotos\source\repos\runtime\src\coreclr\tests\src\Interop\PInvoke\AsAny\AsAnyTest.cs:
line 324
PassLayout: i->a  = 12
PassLayout: i->b = 3
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\Users\gotos\source\repos\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root
> C:\Users\gotos\source\repos\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Interop\PInvoke\AsAny\AsAnyTest\AsA
nyTest.cmd
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #33925 
/cc @jkoritzinsky @elinor-fung

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

File: src/coreclr/tests/src/Interop/PInvoke/AsAny/AsAnyTest.cs [hunk 1]
```diff
@@ -339,6 +339,13 @@ private static void RunAsAnyFieldTests()
 
     private static void RunBestFitMappingTests()
     {
+        if (System.Globalization.CultureInfo.CurrentCulture.Name != "en-US")
+        {
+            Console.WriteLine("Non english platforms are not supported");
+            Console.WriteLine("passing without running tests");
```
Comment (elinor-fung) [inline src/coreclr/tests/src/Interop/PInvoke/AsAny/AsAnyTest.cs:345]: Maybe also specify exactly what is not supported / being run? Otherwise, it seems this test will run a bunch of other tests, then print out that it is passing without running tests.

**Review by elinor-fung — APPROVED** [review]

File: src/coreclr/tests/src/Interop/PInvoke/AsAny/AsAnyTest.cs [hunk 2]
```diff
@@ -339,6 +339,13 @@ private static void RunAsAnyFieldTests()
 
     private static void RunBestFitMappingTests()
     {
+        if (System.Globalization.CultureInfo.CurrentCulture.Name != "en-US")
+        {
+            Console.WriteLine("Non english platforms are not supported");
```
Comment (lpereira) [inline src/coreclr/tests/src/Interop/PInvoke/AsAny/AsAnyTest.cs:344]:
```suggestion
            Console.WriteLine("Non-US English platforms are not supported");
```
