### PR TITLE
[wasm][debugger] Remove non-deterministic signals from debugger tests.

### LINKED ISSUE #75392: [release/7.0][wasm] Debugger test `ExceptionTestUncaughtWithReload` failing
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=11459), and
[log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-86cf3625b0f44c3a9a/chrome-DebuggerTests/1/console.a62cc7da.log?helixlogtype=result):
```
[xUnit.net 00:39:47.90]     DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload [FAIL]
  Failed DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload [1 s]
  Error Message:
   [pause1]

Expected: DebuggerTests.ExceptionTestsClass.TestUncaughtException.run
Actual:   invoke_static_method
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.AssertEqual(Object expected, Object actual, String label) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1184
   at DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload() in /_/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs:line 251
--- End of stack trace from previous location ---
[Result: IsOk: True, IsErr: False, Value: {
  "breakpointId": "1:539:8:dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs",
  "locations": [
    {
      "scriptId": "dotnet://27014_1",
      "lineNumber": 542,
      "columnNumber": 8
    }
  ]
}, Error:  ]
[Result: IsOk: True, IsErr: False, Value: {
  "breakpointId": "1:1272:8:dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs",
  "locations": []
}, Error:  ]
```

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/75392.
Removes `Task.Delay` and `Thread.Sleep` from debugger tests.

- `ExceptionTestUncaughtWithReload` - using `App_Ready` is enough.
- `CreateGoodBreakpointAndHitGoToNonWasmPageComeBackAndHitAgain`: we are going to non-wasm page, so there's no runtime from which we could get info about being ready. Also, we cannot rely on any message passed from browser to notify the inspector in all cases because it would send notification for wasm as well. That's why we introduce a new mechanism of informing Inspector that tests are waiting for non-wasm loading and only then we can notify about runtime context being created.
- `ExceptionTestAllWithReload` had a Sleep that was in fact useless as `SendCommandAndCheck` waits for `Inspector.PAUSE` evant by default anyway.

### CODE REVIEW

File: src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs [hunk 1]
```diff
@@ -505,7 +505,8 @@ public async Task CreateGoodBreakpointAndHitGoToNonWasmPageComeBackAndHitAgain(s
                 expression = "window.setTimeout(function() { " + func_name + "(); }, 1);"
             });
             await cli.SendCommand("Runtime.evaluate", run_method, token);
-            await Task.Delay(1000, token);
+            insp.NotifyOfNonWasmIsLoading(true);
+            await insp.WaitFor(Inspector.NON_WASM_PAGE_READY);
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs:509]: You can use `insp.WaitForEvent(..)` for this. We do this for waiting for breakpoint resolved events too. I would suggest:

```diff
diff --git a/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs b/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs
index bb228900f4a..69a99a3fb72 100644
--- a/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs
+++ b/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs
@@ -505,8 +505,7 @@ public async Task CreateGoodBreakpointAndHitGoToNonWasmPageComeBackAndHitAgain(s
                 expression = "window.setTimeout(function() { " + func_name + "(); }, 1);"
             });
             await cli.SendCommand("Runtime.evaluate", run_method, token);
-            insp.NotifyOfNonWasmIsLoading(true);
-            await insp.WaitFor(Inspector.NON_WASM_PAGE_READY);
+            await WaitForEventAsync("Runtime.executionContextCreated");

             run_method = JObject.FromObject(new
             {
diff --git a/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs b/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs
index b533d39910a..6d40816626c 100644
--- a/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs
+++ b/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs
@@ -1451,17 +1451,17 @@ internal async Task<JObject> LoadAssemblyAndTestHotReload(string asm_file, strin
             return await WaitFor(Inspector.PAUSE);
         }

-        public async Task<JObject> WaitForBreakpointResolvedEvent()
+        public Task<JObject> WaitForBreakpointResolvedEvent() => WaitForEventAsync("Debugger.breakpointResolved");
+
+        public async Task<JObject> WaitForEventAsync(string eventName)
         {
             try
             {
-                var res = await insp.WaitForEvent("Debugger.breakpointResolved");
-                _testOutput.WriteLine ($"breakpoint resolved to {res}");
-                return res;
+                return await insp.WaitForEvent(eventName);
             }
             catch (TaskCanceledException)
             {
-                throw new XunitException($"Timed out waiting for Debugger.breakpointResolved event");
+                throw new XunitException($"Timed out waiting for {eventName} event");
             }
         }
```

**Review by radical — APPROVED** [review]
