### PR TITLE
Fix an incorrect CSE case with struct retyping.

### LINKED ISSUE #33884: System.CodeAnalysis.dll crashes building with Crossgen2
Command-line:

<pre>
"D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\corerun" "D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\crossgen2\crossgen2.dll" -r:"D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\System.*.dll" -r:"D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\Microsoft.*.dll" -r:"D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\mscorlib.dll" -r:"D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\netstandard.dll" -O --inputbubble --out:"D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\temp.ni._dll" "D:\git\runtime2\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\Microsoft.CodeAnalysis.dll"
</pre>

Error message:
<pre>
D:\git\runtime2\src\coreclr\src\jit\optcse.cpp:2768
Assertion failed 'IsCompatibleType(cseLclVarTyp, expTyp)' in 'Microsoft.CodeAnalysis.CommonReferenceManager`2:PropagateRecursiveAliases([Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.CommonReferenceManager`2+BoundInputAssembly<System.__Canon,System.__Canon>[],[System.Collections.Immutable]System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CommonReferenceManager`2+ResolvedReference<System.__Canon,System.__Canon>>,[Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.ArrayBuilder`1<System.Collections.Immutable.ImmutableArray`1<string>>)' during 'Optimize Valnum CSEs' (IL size 311)
</pre>

category:correctness
theme:ngen
skill-level:expert
cost:medium

### PR DESCRIPTION
**Pull request by sandreenko**
The failing assert was:
```
Assertion failed 'IsCompatibleType(cseLclVarTyp, expTyp)'  
F:\git\runtime\src\coreclr\src\jit\optcse.cpp Line: 2768
```

That was a combination of two issues:
1.  There was an `IND struct` under `ADDR` not marked with `DONT_CSE`, it came from `INDEX` morphing;
2. There was another `IND` for the same `LCL_VAR`, but as `ref` from call return retyping, `VNApplySelectorsTypeCheck` saw this `IND ref` and returned `struct` type for it without checking sizes/structHandles (we don't have handles in this case, because we don't have a mechanism to keep them on pointers and we access array through a ref (pointer) local var);
-> CSE saw `IND struct` and `IND ref` with the same VN and without `DONT_CSE` and failed.

The first issue was fixed the third commit https://github.com/dotnet/runtime/pull/34676/commits/86a9f22f9aa284404e32e7699c8042a9a78c5be1, 
it introduced a few diffs (20 methods in frameworks, then a few in BING/pri1 SPMI), all textual, not size diffs. I have fixed them in https://github.com/dotnet/runtime/pull/34676/commits/cd24383210b9ed22f7ea3640005217021f9fbd63 commit.

The solution adds this flag on each node under `ADDR` and checks it in `debugCheckFlags`. It is questionable because we will for sure forget to clear `DONT_CSE` flag from time to time and we don't have a checker to assert when it is set without a reason, as we do for `CALL, ASG, EXCEPT` flags. 
We could add a checker (in another PR) but it won't be cheap because:
1. `DONT_CSE` is used not only for correctness but for profitability as well. I had a change that cleaned it from `NULLCHECK` nodes, but diffs were negative: CSE started to create CSE copies for them, but the null checks were later deleted by assertion propagation, so changing CSE logic to have zero diffs would be non-trivial;
2. we don't have a clear contract where `DONT_CSE` is required for the correctness and there are comments with TODO to delete some that reference failing tests if you do.

Maybe it would be better to drop the commit for SPMI diffs and accept textual diffs instead of adding these non-obvious conditions. I am sure there are some other places where we forgot to clean that, they just don't produce any diffs.

Commits:
61286138a07: Fix old printing issues.
df5266c8285: add a repro test that doesn't require crossgen2.
86a9f22f9aa: Check that all `ADDR` sources are marked as DONT_CSE.
cd24383210b: Fix text(no size) diffs found by SPMI (could be dropped).
c0300c46777: Add a question/comment (will be dropped/fixed before merge).

Fixes #33884.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @erozenfeld @briansull, cc @dotnet/jit-contrib 
I would like to hear your opinion about adding a checker for `DONT_CSE` or move its setting to another place/phase.

File: src/coreclr/src/jit/morph.cpp [hunk 1]
```diff
@@ -16831,8 +16833,15 @@ void Compiler::fgMorphStructField(GenTree* tree, GenTree* parent)
                 tree->SetOper(GT_LCL_VAR);
                 tree->AsLclVarCommon()->SetLclNum(fieldLclIndex);
                 tree->gtType = fieldType;
+                bool canCSE  = tree->CanCSE();
+                // That doesn't make any sense, was it supposed to clean all flags except GTF_NODE_MASK here? 2012<
                 tree->gtFlags &= GTF_NODE_MASK;
+                // If yes then why a year after (2013) was this cleaning added, that obviously does nothing.
```
Comment (briansull) [inline src/coreclr/src/jit/morph.cpp:16839]: I don't think that you want to checkin these two comments.

File: src/coreclr/src/jit/importer.cpp [hunk 2]
```diff
@@ -9121,7 +9123,12 @@ GenTree* Compiler::impFixupStructReturnType(GenTree* op, CORINFO_CLASS_HANDLE re
         if ((op1->gtOper == GT_ADDR) && (op1->AsOp()->gtOp1->gtOper != GT_INDEX))
         {
             // Change '*(&X)' to 'X' and see if we can do better
-            op = op1->AsOp()->gtOp1;
+            bool canCSE = op->CanCSE();
+            op          = op1->AsOp()->gtOp1;
+            if (canCSE)
+            {
+                op->ClearDoNotCSE();
```
Comment (briansull) [inline src/coreclr/src/jit/importer.cpp:9130]: It isn't necessary to guard this call to ClearDoNotCSE()

File: src/coreclr/src/jit/importer.cpp [hunk 3]
```diff
@@ -3863,11 +3863,13 @@ GenTree* Compiler::impIntrinsic(GenTree*                newobjThis,
...
             op1                                    = impPopStack().val;
             GenTree*             thisptr           = newobjThis;
+            GenTreeLclVar*       lclVar            = thisptr->gtGetOp1()->AsLclVar();
             CORINFO_FIELD_HANDLE fldHnd            = info.compCompHnd->getFieldInClass(clsHnd, 0);
             GenTree*             field             = gtNewFieldRef(TYP_BYREF, fldHnd, thisptr, 0);
             GenTree*             assign            = gtNewAssignNode(field, op1);
-            GenTree*             byReferenceStruct = gtCloneExpr(thisptr->gtGetOp1());
-            assert(byReferenceStruct != nullptr);
+            GenTreeLclVar*       byReferenceStruct = gtCloneExpr(lclVar)->AsLclVar();
+            assert(!byReferenceStruct->CanCSE());
```
Comment (briansull) [inline src/coreclr/src/jit/importer.cpp:3871]: Did you want to remove the assert?  I believe that gtCloneExpr can return nullptr for some complex trees.
`assert(byReferenceStruct != nullptr);`

**Comment by briansull** [comment]
> I would like to hear your opinion about adding a checker for DONT_CSE or move its setting to another place/phase.

Checker phases are typically used to enforce correctness issues.
The DONT_CSE is a flag that prevents an optimization, presumably because it is unsafe.
When code sets it is could be unsafe for all cases or if is is difficult to determine it could be unsafe just for some cases.

Failing to perform a CSE isn't a correctness issue and often won't even significantly change the performance of the generated code.   It will show up in code diffs, which looks like what your bug fix is trying to correct here.

> Maybe it would be better to drop the commit for SPMI diffs and accept textual diffs instead of adding these non-obvious conditions. 

I am fine with accepting a small amount of textual diffs and we often get them when code changes the behavior of the CSE heuristics .

File: src/coreclr/src/jit/importer.cpp (hunk 2 above)
Comment (sandreenko) [reply src/coreclr/src/jit/importer.cpp:9130]: Why is not it? It could be a volatile LCL_VAR that needs that flag.

File: src/coreclr/src/jit/importer.cpp (hunk 3 above)
Comment (sandreenko) [reply src/coreclr/src/jit/importer.cpp:3871]: `CanCSE` does `this` dereferencing, so it is not necessary to check it separately, but I will return it if it reads better.

File: src/coreclr/src/jit/morph.cpp (hunk 1 above)
Comment (sandreenko) [reply src/coreclr/src/jit/morph.cpp:16839]: Yes, I will drop that commit before merge, want to see if somebody knows more about these changes.

**Comment by sandreenko** [comment]
> Checker phases are typically used to enforce correctness issues.
> The DONT_CSE is a flag that prevents an optimization, presumably because it is unsafe.
> When code sets it is could be unsafe for all cases or if is is difficult to determine it could be unsafe just for some cases.

How is it different from, for example, `GTF_EXCEPT`? When we don't set `GTF_EXCEPT` where we need it - it is a correctness issue. When we set it if we don't need it - it forbids some optimizations.

File: src/coreclr/src/jit/importer.cpp (hunk 3 above)
Comment (briansull) [reply src/coreclr/src/jit/importer.cpp:3871]: An A/V in a Checked build is worse than an assert firing, in terms of debuggablity.

File: src/coreclr/src/jit/importer.cpp (hunk 2 above)
Comment (briansull) [reply src/coreclr/src/jit/importer.cpp:9130]: The implementation of CanCSE is 
` return ((gtFlags & GTF_DONT_CSE) == 0);`
So this is basically saying if the flag is set then clear it using the AND NOT operation.
Not sure how a volatile LCL_VAR would behave any differently here

**Comment by briansull** [comment]
GTF_EXCEPT flags are a bit different IMO,  these are flags that get push up the tree to all of the parent nodes.
Thus it summarizes the state below, so that we don't have to walk the entire tree to look for operations that have exceptional side effects.   Since when inserting new node it is easy to forget to set the GTF_EXCDEPT flags , a checker is great to insure that the summery is always correct.  I am sure that correctness of our optimization depend upon having correct GTF_EXCEPT flags, although having an extra flag would only disable an optimization (similar to having an extra DONT_CSE flag)

The DONT_CSE flag is a local flag that only applies to the current node, and typically the parent node is responsible for setting it on one or both of its child nodes.

That said I am not strongly opposed to adding some kind of checker if it provides good value.

**Comment by erozenfeld** [comment]
We currently have 56 places in the code where we set `GTF_DONT_CSE` and an additional 11 places where we propagate it. I think it would be beneficial to audit these places and do three things:
1. For places where there are comments that indicate that it's not clear why the flag is set, try not to set it and figure out the right solution.
2. For places that where there is a good reason to set the flag for correctness, see if it's possible to add a check to the checker to make sure we don't lose the flag.
3. For places where we set the flag for performance reasons we probably don't want to add a check to the checker but we should make sure there is a good comment explaining why the flag is set.
That will also make it impossible to add a check in the checker that we shouldn't see an unexpected `GTF_DONT_CSE`.

File: src/coreclr/src/jit/importer.cpp (hunk 2 above)
Comment (sandreenko) [reply src/coreclr/src/jit/importer.cpp:9130]: > So this is basically saying if the flag is set then clear it using the AND NOT operation.

Maybe I am missing something, but I don't understand.
We are checking the flag on `IND(ADDR(X))` tree and clear it on `X`. `X` was marked as `DONT_CSE` because it was `ADDR` source, `IND(ADDR(X))` could be marked as `DONT_CSE` for other reasons that we don't change here, so if `IND(ADDR(X))` was marked with that flag then after the transformation `X` should have this flag as well.

For example, `IND1(ADDR2(IND3(ADDR4(X))` in the beginning `X` and `IND3` have `DONT_CSE` because they are `ADDR` sources, when we optimize `IND3(ADDR4(X))` we have to keep `DONT_CSE` on `X` .

File: src/coreclr/src/jit/valuenum.cpp [hunk 4]
```diff
@@ -3614,6 +3614,13 @@ ValueNum ValueNumStore::VNApplySelectorsTypeCheck(ValueNum elem, var_types indTy
 
         if ((indType == TYP_REF) && (varTypeIsStruct(elemTyp)))
         {
+            // This whole block is over-optimistic, we don't have any information
```
Comment (sandreenko) [inline src/coreclr/src/jit/valuenum.cpp:3617]: I checked that if we delete that unsafe condition we will get 8 bytes regression in framework assemblies (1 method) and 2 in SPMI (pri1 and BING).
That regression will be fixed with #33225, so I think I will just delete this block before the merge.

File: src/coreclr/src/jit/morph.cpp [hunk 5]
```diff
@@ -5376,7 +5376,12 @@ GenTree* Compiler::fgMorphArrayIndex(GenTree* tree)
         tree->ChangeOper(GT_IND);
         GenTreeIndir* const indir = tree->AsIndir();
         indir->Addr()             = indexAddr;
+        bool canCSE               = indir->CanCSE();
         indir->gtFlags            = GTF_IND_ARR_INDEX | (indexAddr->gtFlags & GTF_ALL_EFFECT);
+        if (!canCSE)
+        {
+            indir->SetDoNotCSE();
+        }
```
Comment (erozenfeld) [inline src/coreclr/src/jit/morph.cpp:5384]: Why do you need to check whether`DONT_CSE` is set on `indir` here before setting it? Why not just set it?

File: src/coreclr/src/jit/morph.cpp [hunk 6]
```diff
@@ -16831,8 +16833,15 @@ void Compiler::fgMorphStructField(GenTree* tree, GenTree* parent)
...
                 tree->gtType = fieldType;
+                bool canCSE  = tree->CanCSE();
+                // That doesn't make any sense, was it supposed to clean all flags except GTF_NODE_MASK here? 2012<
                 tree->gtFlags &= GTF_NODE_MASK;
+                // If yes then why a year after (2013) was this cleaning added, that obviously does nothing.
                 tree->gtFlags &= ~GTF_GLOB_REF;
+                if (!canCSE)
+                {
+                    tree->SetDoNotCSE();
+                }
```
Comment (erozenfeld) [inline src/coreclr/src/jit/morph.cpp:16844]: Same comment: why not set `DONT_CSE` without checking it first?

File: src/coreclr/src/jit/morph.cpp [hunk 7]
```diff
@@ -16831,8 +16833,15 @@ void Compiler::fgMorphStructField(GenTree* tree, GenTree* parent)
                 tree->SetOper(GT_LCL_VAR);
                 tree->AsLclVarCommon()->SetLclNum(fieldLclIndex);
                 tree->gtType = fieldType;
+                bool canCSE  = tree->CanCSE();
+                // That doesn't make any sense, was it supposed to clean all flags except GTF_NODE_MASK here? 2012<
```
Comment (erozenfeld) [inline src/coreclr/src/jit/morph.cpp:16837]: I can help you find the change that introduced this.

**Review by erozenfeld — COMMENTED** [review]
Left a few comments.

File: src/coreclr/src/jit/morph.cpp (hunk 5 above)
Comment (erozenfeld) [reply src/coreclr/src/jit/morph.cpp:5384]: Never mind, I misread the change.

File: src/coreclr/src/jit/morph.cpp (hunk 6 above)
Comment (erozenfeld) [reply src/coreclr/src/jit/morph.cpp:16844]: Never mind, I misread the change.

File: src/coreclr/src/jit/importer.cpp (hunk 2 above)
Comment (briansull) [reply src/coreclr/src/jit/importer.cpp:9130]: Yes, I see.
I missed that we were overwriting `op` after setting `canCSE`.
This sequence is confusing and could use a comment, saying we are preserving any DONT_CSE that was set on the original version of `op`

```
 bool canCSE = op->CanCSE();
          op        = op1->AsOp()->gtOp1;
```

File: src/coreclr/src/jit/valuenum.cpp [hunk 8]
```diff
@@ -3612,15 +3612,7 @@ ValueNum ValueNumStore::VNApplySelectorsTypeCheck(ValueNum elem, var_types indTy
         size_t elemTypSize = (elemTyp == TYP_STRUCT) ? elemStructSize : genTypeSize(elemTyp);
         size_t indTypeSize = genTypeSize(indType);
 
-        if ((indType == TYP_REF) && (varTypeIsStruct(elemTyp)))
```
Comment (sandreenko) [inline src/coreclr/src/jit/valuenum.cpp:3615]: That change gives as one regression in framework crossgening:
```
8 (12.70% of base) : Newtonsoft.Json.dasm -  Newtonsoft.Json.Serialization.JsonTypeReflector:get_DynamicCodeGeneration():bool
```

**Comment by sandreenko** [comment]
I have updated the PR, deleted the suspicious optimization from `VNApplySelectorsTypeCheck` and allowed textual diffs where we forget to clean DONT_CSE.
Please take another look.

**Review by briansull — APPROVED** [review]
LGTM now

**Review by erozenfeld — APPROVED** [review]
LGTM
