### PR TITLE
Don't propagate const TYP_REF as TYP_I_IMPL

### LINKED ISSUE #75644: JIT: libraries jitstress failures Assertion failed 'addr->TypeIs(TYP_BYREF)'
https://dev.azure.com/dnceng-public/public/_build/results?buildId=15973&view=ms.vss-test-web.build-test-results-tab

A number of different legs hit this assert. Did not see it in runs from the day before (which had other issues)
```
Assert failure(PID 27 [0x0000001b], Thread: 37 [0x0025]): Assertion failed 'addr->TypeIs(TYP_BYREF)' in 'Microsoft.VisualBasic.CompilerServices.Operators:GetNoValidOperatorException(byte,System.Object,System.Object):System.Exception' during 'Morph - Global' (IL size 143; hash 0xd19b006e; Tier1)

    File: /__w/1/s/src/coreclr/jit/gentree.h Line: 6465
    Image: /root/helix/work/correlation/dotnet
```

### LINKED ISSUE #75657: Test failure JIT/Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.sh
Run: [runtime-coreclr jitstress 20220913.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=15973&view=ms.vss-test-web.build-test-results-tab&runId=312636&paneView=debug&resultId=108578)

Failed test:
```
coreclr Linux x64 Checked jitstress1 @ Ubuntu.1804.Amd64.Open
- JIT/Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.sh

coreclr Linux x64 Checked jitstress1_tiered @ Ubuntu.1804.Amd64.Open
- JIT/Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.sh

coreclr Linux x64 Checked zapdisable @ Ubuntu.1804.Amd64.Open
- JIT/Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.sh

coreclr windows x64 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Regression\\JitBlue\\Runtime_70790\\Runtime_70790\\Runtime_70790.cmd

coreclr windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- JIT\\Regression\\JitBlue\\Runtime_70790\\Runtime_70790\\Runtime_70790.cmd

coreclr windows x64 Checked zapdisable @ Windows.10.Amd64.Open
- JIT\\Regression\\JitBlue\\Runtime_70790\\Runtime_70790\\Runtime_70790.cmd

coreclr OSX x64 Checked zapdisable @ OSX.1200.Amd64.Open
- JIT/Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.sh

coreclr OSX x64 Checked jitstress1 @ OSX.1200.Amd64.Open
- JIT/Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.sh

coreclr OSX x64 Checked jitstress1_tiered @ OSX.1200.Amd64.Open
- JIT/Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.sh
```
**Error message:**
```
Assert failure(PID 23033 [0x000059f9], Thread: 23033 [0x59f9]): Assertion failed 'id->idGCref() == GCT_BYREF' in 'System.SpanHelpers:IndexOfValueType[short,DontNegate`1[short]](https://dev.azure.com/dnceng-public/public/_build/byref,short,int):int' during 'Emit code' (IL size 1084; hash 0x1375cf9a; FullOpts)

File: /__w/1/s/src/coreclr/jit/emitxarch.cpp Line: 13083
Image: /datadisks/disk1/work/B41509AE/p/corerun
[createdump] waitpid() returned successfully (wstatus 00000000)
/datadisks/disk1/work/B41509AE/w/A77509BE/e/JIT/Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.sh: line 409: 23033 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/B41509AE/w/A77509BE/uploads/Reports/JIT.Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/B41509AE/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Runtime_70790.dll ''
[createdump] Gathering state for process 23033 corerun
[createdump] Crashing thread 000059f9 signal 00000006
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.23033.dmp
[createdump] Written 132714496 bytes (32401 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 991ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/datadisks/disk1/work/B41509AE/p
/datadisks/disk1/work/B41509AE/w/A77509BE/e/JIT/Regression/JitBlue/Runtime_70790/Runtime_70790/Runtime_70790.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_Runtime_70790_Runtime_70790_Runtime_70790_._JitBlue_Runtime_70790_Runtime_70790_Runtime_70790_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### LINKED ISSUE #75659: Test failure JIT\\Directed\\StrAccess\\straccess1_cs_ro\\straccess1_cs_ro.cmd
Run: [runtime-coreclr jitstress 20220913.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=15973&view=ms.vss-test-web.build-test-results-tab&runId=312696&paneView=debug&resultId=108230)

Failed test:
```
coreclr windows arm64 Checked jitstress1 @ Windows.10.Arm64v8.Open
- JIT\\Directed\\StrAccess\\straccess1_cs_ro\\straccess1_cs_ro.cmd
- JIT\\Directed\\StrAccess\\straccess1_cs_do\\straccess1_cs_do.cmd

coreclr Linux x64 Checked jitstress1 @ Ubuntu.1804.Amd64.Open
- JIT/Directed/StrAccess/straccess1_cs_do/straccess1_cs_do.sh
- JIT/Directed/StrAccess/straccess1_cs_ro/straccess1_cs_ro.sh

coreclr Linux arm64 Checked jitstress1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/Directed/StrAccess/straccess1_cs_do/straccess1_cs_do.sh
- JIT/Directed/StrAccess/straccess1_cs_ro/straccess1_cs_ro.sh

coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
- JIT\\Directed\\StrAccess\\straccess1_cs_do\\straccess1_cs_do.cmd
- JIT\\Directed\\StrAccess\\straccess1_cs_ro\\straccess1_cs_ro.cmd

coreclr Linux arm64 Checked jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/Directed/StrAccess/straccess1_cs_do/straccess1_cs_do.sh
- JIT/Directed/StrAccess/straccess1_cs_ro/straccess1_cs_ro.sh

coreclr Linux x64 Checked jitstress2 @ Ubuntu.1804.Amd64.Open
- JIT/Directed/StrAccess/straccess1_cs_do/straccess1_cs_do.sh
- JIT/Directed/StrAccess/straccess1_cs_ro/straccess1_cs_ro.sh

coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Directed\\StrAccess\\straccess1_cs_ro\\straccess1_cs_ro.cmd
- JIT\\Directed\\StrAccess\\straccess1_cs_do\\straccess1_cs_do.cmd

coreclr windows arm64 Checked jitstress2 @ Windows.10.Arm64v8.Open
- JIT\\Directed\\StrAccess\\straccess1_cs_do\\straccess1_cs_do.cmd
- JIT\\Directed\\StrAccess\\straccess1_cs_ro\\straccess1_cs_ro.cmd

coreclr windows x64 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Directed\\StrAccess\\straccess1_cs_ro\\straccess1_cs_ro.cmd
- JIT\\Directed\\StrAccess\\straccess1_cs_do\\straccess1_cs_do.cmd

coreclr windows x64 Checked jitstress2 @ Windows.10.Amd64.Open
- JIT\\Directed\\StrAccess\\straccess1_cs_ro\\straccess1_cs_ro.cmd
- JIT\\Directed\\StrAccess\\straccess1_cs_do\\straccess1_cs_do.cmd

coreclr OSX x64 Checked jitstress1 @ OSX.1200.Amd64.Open
- JIT/Directed/StrAccess/straccess1_cs_ro/straccess1_cs_ro.sh
- JIT/Directed/StrAccess/straccess1_cs_do/straccess1_cs_do.sh

coreclr OSX x64 Checked jitstress2 @ OSX.1200.Amd64.Open
- JIT/Directed/StrAccess/straccess1_cs_do/straccess1_cs_do.sh
- JIT/Directed/StrAccess/straccess1_cs_ro/straccess1_cs_ro.sh

coreclr OSX arm64 Checked jitstress1 @ OSX.1200.ARM64.Open
- JIT/Directed/StrAccess/straccess1_cs_ro/straccess1_cs_ro.sh
- JIT/Directed/StrAccess/straccess1_cs_do/straccess1_cs_do.sh

coreclr OSX arm64 Checked jitstress2 @ OSX.1200.ARM64.Open
- JIT/Directed/StrAccess/straccess1_cs_ro/straccess1_cs_ro.sh
- JIT/Directed/StrAccess/straccess1_cs_do/straccess1_cs_do.sh
```
**Error message:**
```
Assert failure(PID 13552 [0x000034f0], Thread: 7320 [0x1c98]): Assertion failed 'addr->TypeIs(TYP_BYREF)' in 'StrAccess1:Main():int' during 'Morph - Global' (IL size 4157; hash 0xd563053c; FullOpts)

File: D:\a\_work\1\s\src\coreclr\jit\gentree.h Line: 6465
Image: D:\h\w\AD600960\p\corerun.exe
Return code:      1
Raw output file:      D:\h\w\AD600960\w\A70E098F\uploads\Reports\JIT.Directed\StrAccess\straccess1_cs_ro\straccess1_cs_ro.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\AD600960\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  straccess1_cs_ro.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AD600960\p
D:\h\w\AD600960\w\A70E098F\e\JIT\Directed\StrAccess\straccess1_cs_ro\straccess1_cs_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._StrAccess_straccess1_cs_ro_straccess1_cs_ro_._StrAccess_straccess1_cs_ro_straccess1_cs_ro_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/75657
Fixes https://github.com/dotnet/runtime/issues/75659
Fixes https://github.com/dotnet/runtime/issues/75644

Those jitstress tests found more cases in JIT where it does not expect non-zero gc const handles - still wonder how it worked for NativeAOT.
Jit was propagating CNS_INT TYP_REF gc handle as TYP_I_IMPL, e.g.:

```
               [002991] -----------                         \--*  ARR_ADDR  byref ushort[]
               [002990] -----------                            \--*  ADD       byref 
               [002982] -----------                               +--*  LCL_VAR   ref    V01 loc1         
               [002989] -----------                               \--*  ADD       long  
                                                                        ...

Assertion prop1 in BB01:
Constant Assertion: V01 == [000001FC25C68DE0], index = #02
               [002993] H----------                         *  CNS_INT(h) long   0x25C68DE0 [ICON_STR_HDL]


Folding long operator with constant nodes into a constant:
               [002990] -----------                         *  ADD       long  
               [002994] H----+-----                         +--*  CNS_INT(h) long   0x25C68DE0 [ICON_STR_HDL]
               [002989] -----+-----                         \--*  CNS_INT   long   12
Bashed to long constant:
               [002990] -----------                         *  CNS_INT   long   0x1fc25c68dec
```
Even folded gc-handle + 12 then

### CODE REVIEW

File: src/coreclr/jit/emitxarch.cpp [hunk 1]
```diff
@@ -13080,7 +13080,7 @@ BYTE* emitter::emitOutputRI(BYTE* dst, instrDesc* id)
                 break;
 
             case IF_RRW_CNS:
-                assert(id->idGCref() == GCT_BYREF);
+                assert((id->idGCref() == GCT_BYREF) || (id->idGCref() == GCT_GCREF));
```
Comment (jakobbotsch) [inline src/coreclr/jit/emitxarch.cpp:13083]: Looks like the `emitGCregLiveUpd(GCT_BYREF, id->idReg1(), dst);` call below also needs to be fixed.

But it seems strange to me. How are we producing a gcref after a `r/w reg, const` operation? Seems like we are either misreporting this or the const has to be 0 and the instruction is useless.

Comment (EgorBo) [reply src/coreclr/jit/emitxarch.cpp:13083]: I've not investigated this one yet (where it come from, I assume it's jitstressregs mode) but it looks like this:
```
IN0006: 000030 B901000000           mov      ecx, 1
IN0007: 000035 48BA0800FDD748020000 mov      rdx, 0x248D7FD0008
                            ; gcrRegs +[rdx]
IN0008: 00003F 4881C2F8090000       add      rdx, 0x9F8
                            ; gcrRegs -[rdx]
                            ; byrRegs +[rdx]
```
so from my understanding it should not be fixed to GCREF, should it?

Comment (jakobbotsch) [reply src/coreclr/jit/emitxarch.cpp:13083]: > so from my understanding it should not be fixed to GCREF, should it?

I agree, but I think we are creating an incorrect instruction then. `id->idGCref() == GCT_BYREF` should be true here. Consider
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
static void Foo(C c)
{
    Bar(ref c.F);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void Bar(ref int i)
{
}

private class C
{
    public int F;
}
```
that produces
```asm
add rcx, 8
```
without hitting the assert today.

Comment (EgorBo) [reply src/coreclr/jit/emitxarch.cpp]: @jakobbotsch thanks, I've found the reason - it turns out the test sets `DOTNET_JitConstCSE=3` so then it picks up gc const handle as a "shared constant" (it's where it may use it as a base for other constants) - that's how that `add` appeared
```

We have shared Const CSE's and selected $1c1 with a value of 0x0000024CB7AC0008 as the base.

CSE #01 def at [000897] replaced in BB02 with def of V61
ReMorphing args for 533.CALL:
Args for [000533].CALL after fgMorphArgs:
CallArg[[001079].COMMA ref (By value), 1 reg: rcx, byteAlignment=8, isLate, processed]
CallArg[[000898].CNS_INT ref (By value), 1 reg: rdx, byteAlignment=8, isLate, processed]
OutgoingArgsStackSize is 32

optValnumCSE morphed tree:
N009 ( 22, 33)              [000533] -ACXG------                         *  CALL      void   System.Diagnostics.Debug.Fail $VN.Void
N007 (  5, 16)              [001079] -A--------- arg0 in rcx             +--*  COMMA     ref    $1c0
N003 (  2, 10) CSE #01 (def)[001075] -A------R--                         |  +--*  ASG       ref    $VN.Void
N002 (  1,  1)              [001074] D------N---                         |  |  +--*  LCL_VAR   ref    V61 cse1          $VN.Void
N001 (  2, 10)              [001073] -----------                         |  |  \--*  CNS_INT   ref    0x24cb7ac0008 $1c1
N006 (  3,  6)              [001078] -------N---                         |  \--*  ADD       ref    $1c0
N004 (  1,  1)              [001076] -----------                         |     +--*  LCL_VAR   ref    V61 cse1          $1c1
N005 (  1,  4)              [001077] -----------                         |     \--*  CNS_INT   ref    0x9a8
N008 (  3, 10) CSE #01 (use)[000898] H---------- arg1 in rdx             \--*  CNS_INT(h) ref    0xB7AC0008 [ICON_STR_HDL] $1c1
```

File: src/coreclr/jit/optcse.cpp [hunk 2]
```diff
@@ -478,8 +478,9 @@ unsigned Compiler::optValnumCSE_Index(GenTree* tree, Statement* stmt)
         assert(vnStore->IsVNConstant(vnLibNorm));
 
         // We don't share small offset constants when they require a reloc
+        // Also, we don't share non-null const gc handles
         //
-        if (!tree->AsIntConCommon()->ImmedValNeedsReloc(this))
+        if (!tree->AsIntConCommon()->ImmedValNeedsReloc(this) && ((tree->IsIntegralConst(0)) || !tree->TypeIs(TYP_REF)))
```
Comment (jakobbotsch) [inline src/coreclr/jit/optcse.cpp:483]: Should we use `varTypeIsGC` instead? I imagine we can have the same problem with `TYP_BYREF`. Or is producing `TYP_BYREF` via pointer arithmetic of a `TYP_BYREF` that may be pointing into another object ok in this particular case?

Comment (EgorBo) [reply src/coreclr/jit/optcse.cpp]: Yeah, let's use `varTypeIsGC`

**Review by jakobbotsch — APPROVED** [review]

**Comment by JulieLeeMSFT** [comment]
@EgorBo, thanks for the quick fix. Do we need to backport this to 7.0?

**Comment by EgorBo** [comment]
> @EgorBo, thanks for the quick fix. Do we need to backport this to 7.0?

No, it's Main-only. Frozen strings exposed many cases where JIT was not ready for constant gc handles 😞 but it's mostly my fault that I didn't run all the outerloop/stress tests as part of that PR

**Comment by EgorBo** [comment]
CI failures so far:
1) Unrelated https://github.com/dotnet/runtime/issues/75782
2) `TieredVtableMethodTests` that is also reproduceable outside of this PR but look frozen segment related, but codegen looks fine to me, will file an issue with a repro, it needs help from gc side since it crashes with GCStress=0xC during `WKS::GCHeap::Promote`
