### PR TITLE
Fix AreFlagsSetToZeroCmp to not consider unsupported formats

### LINKED ISSUE #85637: Failures in System.Net.Mail.Tests.SmtpClientTest tests
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=258828
Build error leg or test failing: System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded
Pull request: https://github.com/dotnet/runtime/pull/85620

Failing in several recent PR runs of runtime.

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[260745](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260745)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260745&view=ms.vss-test-web.build-test-results-tab&runId=5116984&resultId=164016)|dotnet/runtime#85702|
|[261029](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261029)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=261029&view=ms.vss-test-web.build-test-results-tab&runId=5116968&resultId=156534)|dotnet/runtime#85619|
|[260984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260984)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260984&view=ms.vss-test-web.build-test-results-tab&runId=5116274&resultId=159438)|dotnet/runtime#85388|
|[260976](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260976)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260976&view=ms.vss-test-web.build-test-results-tab&runId=5116264&resultId=159097)|dotnet/runtime#85501|
|[260946](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260946)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260946&view=ms.vss-test-web.build-test-results-tab&runId=5115372&resultId=156406)|dotnet/runtime#85701|
|[260931](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260931)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260931&view=ms.vss-test-web.build-test-results-tab&runId=5115196&resultId=159468)|dotnet/runtime#85568|
|[260915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260915)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260915&view=ms.vss-test-web.build-test-results-tab&runId=5114838&resultId=158346)|dotnet/runtime#85254|
|[260883](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260883)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260883&view=ms.vss-test-web.build-test-results-tab&runId=5114382&resultId=152451)|dotnet/runtime#85601|
|[260871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260871)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260871&view=ms.vss-test-web.build-test-results-tab&runId=5113706&resultId=201000)|dotnet/runtime#85542|
|[260560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260560)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260560&view=ms.vss-test-web.build-test-results-tab&runId=5112702&resultId=155879)|dotnet/runtime#85689|
|[260853](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260853)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260853&view=ms.vss-test-web.build-test-results-tab&runId=5112516&resultId=204350)|dotnet/runtime#85709|
|[260843](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260843)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260843&view=ms.vss-test-web.build-test-results-tab&runId=5112522&resultId=155909)|dotnet/runtime#85704|
|[260827](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260827)|dotnet/runtime|[System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260827&view=ms.vss-test-web.build-test-results-tab&runId=5112230&resultId=197329)|dotnet/runtime#85565|
|[260720](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260720)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260720&view=ms.vss-test-web.build-test-results-tab&runId=5109966&resultId=200987)|dotnet/runtime#85705|
|[260693](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260693)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260693&view=ms.vss-test-web.build-test-results-tab&runId=5109880&resultId=162116)|dotnet/runtime#85703|
|[260617](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260617)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260617&view=ms.vss-test-web.build-test-results-tab&runId=5106256&resultId=159934)|dotnet/runtime#85542|
|[260534](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260534)|dotnet/runtime|[System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260534&view=ms.vss-test-web.build-test-results-tab&runId=5105344&resultId=141090)||
|[260583](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260583)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260583&view=ms.vss-test-web.build-test-results-tab&runId=5105254&resultId=165536)|dotnet/runtime#85701|
|[260571](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260571)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260571&view=ms.vss-test-web.build-test-results-tab&runId=5105066&resultId=163823)|dotnet/runtime#85654|
|[260549](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260549)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260549&view=ms.vss-test-web.build-test-results-tab&runId=5103588&resultId=199580)|dotnet/runtime#85516|
|[260323](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260323)|dotnet/runtime|[System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260323&view=ms.vss-test-web.build-test-results-tab&runId=5102544&resultId=157267)|dotnet/runtime#85694|
|[260501](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260501)|dotnet/runtime|[System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260501&view=ms.vss-test-web.build-test-results-tab&runId=5101848&resultId=204535)||
|[260461](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260461)|dotnet/runtime|[System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260461&view=ms.vss-test-web.build-test-results-tab&runId=5100584&resultId=197161)||
|[260479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260479)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260479&view=ms.vss-test-web.build-test-results-tab&runId=5100712&resultId=167601)|dotnet/runtime#85698|
|[260472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260472)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260472&view=ms.vss-test-web.build-test-results-tab&runId=5100702&resultId=167601)|dotnet/runtime#85671|
|[260466](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260466)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260466&view=ms.vss-test-web.build-test-results-tab&runId=5100676&resultId=167568)|dotnet/runtime#85619|
|[260445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260445)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260445&view=ms.vss-test-web.build-test-results-tab&runId=5100068&resultId=193077)|dotnet/runtime#85516|
|[260408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260408)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260408&view=ms.vss-test-web.build-test-results-tab&runId=5099594&resultId=168381)|dotnet/runtime#85689|
|[260380](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260380)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260380&view=ms.vss-test-web.build-test-results-tab&runId=5098884&resultId=147254)|dotnet/runtime#85671|
|[260354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260354)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260354&view=ms.vss-test-web.build-test-results-tab&runId=5098370&resultId=179418)|dotnet/runtime#85692|
|[260345](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260345)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260345&view=ms.vss-test-web.build-test-results-tab&runId=5098400&resultId=164010)|dotnet/runtime#85689|
|[260322](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260322)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260322&view=ms.vss-test-web.build-test-results-tab&runId=5097792&resultId=163861)|dotnet/runtime#85694|
|[260310](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260310)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260310&view=ms.vss-test-web.build-test-results-tab&runId=5097494&resultId=161154)|dotnet/runtime#85284|
|[260327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260327)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260327&view=ms.vss-test-web.build-test-results-tab&runId=5097734&resultId=199551)|dotnet/runtime#85695|
|[260271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260271)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260271&view=ms.vss-test-web.build-test-results-tab&runId=5096666&resultId=159889)|dotnet/runtime#84384|
|[260247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260247)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260247&view=ms.vss-test-web.build-test-results-tab&runId=5096474&resultId=159217)|dotnet/runtime#85667|
|[260260](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260260)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260260&view=ms.vss-test-web.build-test-results-tab&runId=5096346&resultId=153749)|dotnet/runtime#85373|
|[260187](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260187)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260187&view=ms.vss-test-web.build-test-results-tab&runId=5095506&resultId=168274)|dotnet/runtime#85689|
|[260176](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260176)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260176&view=ms.vss-test-web.build-test-results-tab&runId=5094610&resultId=173196)|dotnet/runtime#85681|
|[260121](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260121)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260121&view=ms.vss-test-web.build-test-results-tab&runId=5093248&resultId=164516)|dotnet/runtime#85657|
|[260092](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260092)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260092&view=ms.vss-test-web.build-test-results-tab&runId=5092718&resultId=163750)|dotnet/runtime#85671|
|[260078](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260078)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260078&view=ms.vss-test-web.build-test-results-tab&runId=5092190&resultId=162613)|dotnet/runtime#85664|
|[260070](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260070)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260070&view=ms.vss-test-web.build-test-results-tab&runId=5092038&resultId=162219)|dotnet/runtime#85658|
|[260046](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260046)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260046&view=ms.vss-test-web.build-test-results-tab&runId=5091732&resultId=162141)|dotnet/runtime#84821|
|[260053](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260053)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260053&view=ms.vss-test-web.build-test-results-tab&runId=5091730&resultId=151282)|dotnet/runtime#85686|
|[260034](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260034)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260034&view=ms.vss-test-web.build-test-results-tab&runId=5091386&resultId=204338)|dotnet/runtime#85668|
|[260009](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260009)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260009&view=ms.vss-test-web.build-test-results-tab&runId=5090820&resultId=153364)|dotnet/runtime#85683|
|[259786](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259786)|dotnet/runtime|[System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259786&view=ms.vss-test-web.build-test-results-tab&runId=5085866&resultId=198174)|dotnet/runtime#85323|
|[259982](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259982)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259982&view=ms.vss-test-web.build-test-results-tab&runId=5090136&resultId=167837)|dotnet/runtime#85494|
|[259956](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259956)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259956&view=ms.vss-test-web.build-test-results-tab&runId=5089234&resultId=160359)||
|[259938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259938)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259938&view=ms.vss-test-web.build-test-results-tab&runId=5089424&resultId=167513)|dotnet/runtime#85667|
|[259922](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259922)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259922&view=ms.vss-test-web.build-test-results-tab&runId=5089422&resultId=167533)|dotnet/runtime#85634|
|[259878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259878)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259878&view=ms.vss-test-web.build-test-results-tab&runId=5088742&resultId=165483)|dotnet/runtime#85647|
|[259912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259912)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259912&view=ms.vss-test-web.build-test-results-tab&runId=5088966&resultId=157280)|dotnet/runtime#85678|
|[259865](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259865)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259865&view=ms.vss-test-web.build-test-results-tab&runId=5088260&resultId=163994)|dotnet/runtime#85642|
|[259813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259813)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259813&view=ms.vss-test-web.build-test-results-tab&runId=5086948&resultId=204565)||
|[259819](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259819)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259819&view=ms.vss-test-web.build-test-results-tab&runId=5087746&resultId=164024)|dotnet/runtime#85501|
|[259778](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259778)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259778&view=ms.vss-test-web.build-test-results-tab&runId=5087274&resultId=165161)|dotnet/runtime#85323|
|[259773](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259773)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259773&view=ms.vss-test-web.build-test-results-tab&runId=5086954&resultId=163757)|dotnet/runtime#85618|
|[259746](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259746)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259746&view=ms.vss-test-web.build-test-results-tab&runId=5085792&resultId=167034)|dotnet/runtime#85651|
|[259712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259712)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259712&view=ms.vss-test-web.build-test-results-tab&runId=5085412&resultId=167252)|dotnet/runtime#85284|
|[259694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259694)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259694&view=ms.vss-test-web.build-test-results-tab&runId=5085286&resultId=168049)|dotnet/runtime#85373|
|[259687](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259687)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259687&view=ms.vss-test-web.build-test-results-tab&runId=5084844&resultId=163023)|dotnet/runtime#85673|
|[259416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259416)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259416&view=ms.vss-test-web.build-test-results-tab&runId=5084548&resultId=162931)|dotnet/runtime#85655|
|[259654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259654)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259654&view=ms.vss-test-web.build-test-results-tab&runId=5084000&resultId=160818)|dotnet/runtime#85671|
|[259564](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259564)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259564&view=ms.vss-test-web.build-test-results-tab&runId=5081476&resultId=204330)|dotnet/runtime#85667|
|[259549](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259549)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259549&view=ms.vss-test-web.build-test-results-tab&runId=5080888&resultId=163439)|dotnet/runtime#85518|
|[259541](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259541)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259541&view=ms.vss-test-web.build-test-results-tab&runId=5080890&resultId=165576)|dotnet/runtime#85664|
|[259263](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259263)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259263&view=ms.vss-test-web.build-test-results-tab&runId=5078580&resultId=153244)|dotnet/runtime#85538|
|[259483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259483)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259483&view=ms.vss-test-web.build-test-results-tab&runId=5078590&resultId=160203)|dotnet/runtime#85658|
|[259458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259458)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259458&view=ms.vss-test-web.build-test-results-tab&runId=5077976&resultId=159552)|dotnet/runtime#85657|
|[259285](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259285)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259285&view=ms.vss-test-web.build-test-results-tab&runId=5077758&resultId=158359)|dotnet/runtime#85559|
|[259441](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259441)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259441&view=ms.vss-test-web.build-test-results-tab&runId=5077472&resultId=201004)|dotnet/runtime#85516|
|[259277](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259277)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259277&view=ms.vss-test-web.build-test-results-tab&runId=5076678&resultId=159623)|dotnet/runtime#85434|
|[259390](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259390)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259390&view=ms.vss-test-web.build-test-results-tab&runId=5075378&resultId=157921)|dotnet/runtime#85654|
|[259363](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259363)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259363&view=ms.vss-test-web.build-test-results-tab&runId=5074930&resultId=159654)|dotnet/runtime#85642|
|[259343](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259343)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259343&view=ms.vss-test-web.build-test-results-tab&runId=5074368&resultId=160009)|dotnet/runtime#84122|
|[259334](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259334)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259334&view=ms.vss-test-web.build-test-results-tab&runId=5074022&resultId=157417)|dotnet/runtime#85651|
|[259306](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259306)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259306&view=ms.vss-test-web.build-test-results-tab&runId=5073250&resultId=196631)|dotnet/runtime#85569|
|[259229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259229)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259229&view=ms.vss-test-web.build-test-results-tab&runId=5071578&resultId=161242)|dotnet/runtime#85648|
|[259238](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259238)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259238&view=ms.vss-test-web.build-test-results-tab&runId=5071634&resultId=155728)|dotnet/runtime#85649|
|[259208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259208)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259208&view=ms.vss-test-web.build-test-results-tab&runId=5070944&resultId=161197)|dotnet/runtime#85647|
|[259189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259189)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259189&view=ms.vss-test-web.build-test-results-tab&runId=5070346&resultId=156725)|dotnet/runtime#85646|
|[259156](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259156)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259156&view=ms.vss-test-web.build-test-results-tab&runId=5069340&resultId=149042)|dotnet/runtime#85518|
|[259082](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259082)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259082&view=ms.vss-test-web.build-test-results-tab&runId=5065946&resultId=150311)|dotnet/runtime#85254|
|[259074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259074)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259074&view=ms.vss-test-web.build-test-results-tab&runId=5065470&resultId=189364)|dotnet/runtime#85642|
|[259039](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259039)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259039&view=ms.vss-test-web.build-test-results-tab&runId=5064738&resultId=204369)|dotnet/runtime#85640|
|[259026](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259026)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259026&view=ms.vss-test-web.build-test-results-tab&runId=5064564&resultId=200971)|dotnet/runtime#85266|
|[259022](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259022)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259022&view=ms.vss-test-web.build-test-results-tab&runId=5064362&resultId=160038)|dotnet/runtime#85639|
|[259007](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259007)|dotnet/runtime|[System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259007&view=ms.vss-test-web.build-test-results-tab&runId=5063480&resultId=197160)|dotnet/runtime#85585|
|[259001](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259001)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259001&view=ms.vss-test-web.build-test-results-tab&runId=5063456&resultId=167597)|dotnet/runtime#85284|
|[258976](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258976)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258976&view=ms.vss-test-web.build-test-results-tab&runId=5062680&resultId=204352)|dotnet/runtime#85156|
|[258971](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258971)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258971&view=ms.vss-test-web.build-test-results-tab&runId=5062612&resultId=204467)||
|[258912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258912)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258912&view=ms.vss-test-web.build-test-results-tab&runId=5062308&resultId=153246)|dotnet/runtime#85518|
|[258946](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258946)|dotnet/runtime|[System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258946&view=ms.vss-test-web.build-test-results-tab&runId=5060184&resultId=204840)||
|[258828](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258828)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258828&view=ms.vss-test-web.build-test-results-tab&runId=5060060&resultId=147446)|dotnet/runtime#85620|
|[258936](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258936)|dotnet/runtime|[System.Net.Mail.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258936&view=ms.vss-test-web.build-test-results-tab&runId=5059840&resultId=197327)||
|[258937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258937)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258937&view=ms.vss-test-web.build-test-results-tab&runId=5059888&resultId=168522)|dotnet/runtime#85634|
|[258918](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258918)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258918&view=ms.vss-test-web.build-test-results-tab&runId=5059066&resultId=152455)|dotnet/runtime#85633|
|[258905](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258905)|dotnet/runtime|[System.Net.Mail.Tests.SmtpClientTest.SendMail_DeliveryFormat_SubjectEncoded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258905&view=ms.vss-test-web.build-test-results-tab&runId=5058680&resultId=168037)|dotnet/runtime#85626|
Displaying 100 of 106 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|66|106|106|

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/85637

### CODE REVIEW

File: src/coreclr/jit/emitxarch.cpp [hunk 1]
```diff
@@ -887,21 +887,30 @@ bool emitter::AreFlagsSetToZeroCmp(regNumber reg, emitAttr opSize, GenCondition
...
+    {
+        // Don't consider instructions which didn't write a register
+        return false;
+    }
+
+    if (id->idHasMemWrite() || id->idIsReg2Write())
     {
+        // Don't consider instructions which also wrote a mem location or second register
         return false;
     }
```
Comment (tannergooding) [inline src/coreclr/jit/emitxarch.cpp:909]: This is more conservative than it needs to be but brings it back inline with what was previously being checked:
```csharp
    switch (fmt)
    {
        case IF_RWR_CNS:
        case IF_RRW_CNS:
        case IF_RRW_SHF:
        case IF_RWR_RRD:
        case IF_RRW_RRD:
        case IF_RWR_MRD:
        case IF_RWR_SRD:
        case IF_RRW_SRD:
        case IF_RWR_ARD:
        case IF_RRW_ARD:
        case IF_RWR:
        case IF_RRD:
        case IF_RRW:
        case IF_RWR_RRD_RRD:
        case IF_RWR_RRD_MRD:
        case IF_RWR_RRD_ARD:
        case IF_RWR_RRD_SRD:
            break;
        default:
            return false;
    }
```

The general issue was that the check missed cases like `xadd` which wrote two registers or a mem location + a register and while that isn't "incorrect" to do, handling it would require more checks to ensure the correct register write impacted the flags.

I opted for the faster/more conservative fix and will log an issue tracking adding the correctly handling for cases like `xadd`

**Comment by jakobbotsch** [comment]
There's also `AreFlagsSetForSignJumpOpt` right below. Is there any way to audit the changes made in #85536 to make sure there are no other cases?

**Comment by tannergooding** [comment]
> Is there any way to audit the changes made in https://github.com/dotnet/runtime/pull/85536 to make sure there are no other cases?

There were only a handful of places that had big switch table removals; the other places just had additions to the existing switches to cover the "missing" formats.

Of the places that removed switch tables, `getMemoryOperation`, `emitIsInstrWritingToReg`, `emitGetVexPrefixSize`, and `emitMapFmtAtoM` were already "exhaustive" and were just collapsed to use the new metadata.

That leaves `AreFlagsSetForSignJumpOpt` and `AreFlagsSetToZeroCmp` as the ones that were changed in a different way

File: src/coreclr/jit/emitxarch.cpp [hunk 2]
```diff
@@ -956,8 +965,15 @@ bool emitter::AreFlagsSetForSignJumpOpt(regNumber reg, emitAttr opSize, GenCondi
...
```
Comment (tannergooding) [inline src/coreclr/jit/emitxarch.cpp:978]: Similarly, the previous switch was:
```cpp
    switch (fmt)
    {
        case IF_RWR_CNS:
        case IF_RRW_CNS:
        case IF_RRW_SHF:
        case IF_RWR_RRD:
        case IF_RRW_RRD:
        case IF_RWR_MRD:
        case IF_RWR_SRD:
        case IF_RRW_SRD:
        case IF_RWR_ARD:
        case IF_RRW_ARD:
        case IF_RWR:
        case IF_RRD:
        case IF_RRW:
            break;
        default:
            return false;
    }
```

**Review by jakobbotsch — APPROVED** [review]
