### PR TITLE
Events for IL methods without IL headers

### LINKED ISSUE #90485: CLR crashing when running RemoteExecutor tests locally on Debug builds
Using the latest commit (007cbcff31127d0829ef674ee140ccdbf11b2645) on windows-x64, running:
```
.\build.cmd clr+libs -rc release
dotnet test src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Tests/System.Text.Json.SourceGeneration.Roslyn4.4.Tests.csproj -f net8.0
```
Will fail with the following stacktrace:
```
The active test run was aborted. Reason: Test host process crashed : Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.Serialization.SerializationGuard.<ThrowIfDeserializationInProgress>g__ThrowIfDeserializationInProgress|0_0(System.Runtime.Serialization.SerializationInfo, System.String, Int32 ByRef)
   at System.Runtime.Serialization.SerializationGuard.ThrowIfDeserializationInProgress(System.String, Int32 ByRef)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(System.Reflection.MethodInfo, System.String[], Microsoft.DotNet.RemoteExecutor.RemoteInvokeOptions, Boolean)
   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(System.Action, Microsoft.DotNet.RemoteExecutor.RemoteInvokeOptions)
   at System.Text.Json.SourceGeneration.Tests.JsonSerializerContextTests.JsonSerializerContext_GeneratedDefault_IsSingleton()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(System.Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CallTestMethod(System.Object)
```
Which seems to be originating from this call in `Process.Start`:

https://github.com/dotnet/runtime/blob/af651f48d07c87c94e1225859e63e919719b687b/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L1280

This test has started failing on my local machine in the last few days, but strangely I don't see it impacting CI. Thought I'd file an issue in case others are having the same problem.

### LINKED ISSUE #90580: Test failure Loader\\binding\\tracing\\BinderTracingTest.ResolutionFlow\\BinderTracingTest.ResolutionFlow.cmd
**Failed in:** [runtime-coreclr outerloop 20230814.10](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373837&view=ms.vss-test-web.build-test-results-tab&runId=7945912&resultId=120204&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows arm64 Checked @ Windows.11.Arm64.Open
    - Loader\\binding\\tracing\\BinderTracingTest.ResolutionFlow\\BinderTracingTest.ResolutionFlow.cmd
coreclr osx x64 Checked @ OSX.1200.Amd64.Open
    - Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh
coreclr osx arm64 Checked @ OSX.1200.ARM64.Open
    - Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh
R2R-CG2 osx x64 Checked no_tiered_compilation @ OSX.1200.Amd64.Open
    - Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh
```

**Error message:**
```
 
Assert failure(PID 5600 [0x000015e0], Thread: 4760 [0x1298]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! DecoderInit + 0x20 (0x00007ffa`9d352188)
CORECLR! COR_ILMETHOD_DECODER::COR_ILMETHOD_DECODER + 0x34 (0x00007ffa`9d35e194)
CORECLR! ETW::MethodLog::SendMethodJitStartEvent + 0x1E8 (0x00007ffa`9d245160)
CORECLR! ETW::MethodLog::MethodJitting + 0x12C (0x00007ffa`9d2404ec)
CORECLR! MethodDesc::JitCompileCodeLockedEventWrapper + 0x328 (0x00007ffa`9d0aa090)
CORECLR! MethodDesc::JitCompileCode + 0x3BC (0x00007ffa`9d0a9834)
CORECLR! MethodDesc::PrepareILBasedCode + 0x37C (0x00007ffa`9d0aadec)
CORECLR! MethodDesc::PrepareCode + 0x54 (0x00007ffa`9d0aaa64)
CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x34C (0x00007ffa`9cff240c)
CORECLR! MethodDesc::DoPrestub + 0x3AC (0x00007ffa`9d0a631c)
CORECLR! PreStubWorker + 0x424 (0x00007ffa`9d0adf64)
CORECLR! ThePreStub + 0x50 (0x00007ffa`9cfa11f8)
SYSTEM.DIAGNOSTICS.PROCESS! <no symbol> + 0x0 (0x00007ffa`ec62e310)
SYSTEM.DIAGNOSTICS.PROCESS! <no symbol> + 0x0 (0x00007ffa`ec62e7c4)
BINDERTRACINGTEST.RESOLUTIONFLO! <no symbol> + 0x0 (0x00007ffa`faaaadc4)
BINDERTRACINGTEST.RESOLUTIONFLO! <no symbol> + 0x0 (0x00007ffa`faaa8300)
BINDERTRACINGTEST.RESOLUTIONFLO! <no symbol> + 0x0 (0x00007ffa`faaafb74)
CORECLR! CallDescrWorkerInternal + 0x84 (0x00007ffa`9cfa1fbc)
CORECLR! MethodDescCallSite::CallTargetWorker + 0x6CC (0x00007ffa`9d116c64)
-----
.AV on tid=0x1298 (4760), cxr=0000002A39F7D670, exr=0000002A39F7DA00
FAILED: false

CORECLR! CHECK::Trigger + 0x1BC (0x00007ffa`9d358ce4)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x218 (0x00007ffa`9d011dd0)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x64 (0x00007ffa`9d0119b4)
CORECLR! CLRVectoredExceptionHandler + 0x1B8 (0x00007ffa`9d011930)
CORECLR! CLRVectoredExceptionHandlerShim + 0x24C (0x00007ffa`9d0120ec)
NTDLL! RtlTimeToSecondsSince1970 + 0x1A8 (0x00007ffb`07236fc8)
NTDLL! RtlRaiseException + 0x198 (0x00007ffb`0721f938)
NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007ffb`071b2764)
CORECLR! DecoderInit + 0x20 (0x00007ffa`9d352188)
CORECLR! COR_ILMETHOD_DECODER::COR_ILMETHOD_DECODER + 0x34 (0x00007ffa`9d35e194)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp Line: 7119
    Image: C:\h\w\A8E50951\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A8E50951\w\A4AB090D\uploads\Reports\Loader.binding\tracing\BinderTracingTest.ResolutionFlow\BinderTracingTest.ResolutionFlow.output.txt
Raw output:
BEGIN EXECUTION
AssemblyToLoad.dll
BinderTracingTest.ResolutionFlow.dll
TestLibrary.dll
        3 file(s) copied.
 3:30:28.81
Response file: C:\h\w\A8E50951\w\A4AB090D\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\AssemblyToLoad.dll.rsp
C:\h\w\A8E50951\w\A4AB090D\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\IL-CG2\AssemblyToLoad.dll
-o:C:\h\w\A8E50951\w\A4AB090D\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\AssemblyToLoad.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A8E50951\p\System.*.dll
-r:C:\h\w\A8E50951\p\Microsoft.*.dll
-r:C:\h\w\A8E50951\p\xunit.*.dll
-r:C:\h\w\A8E50951\p\mscorlib.dll
-r:C:\h\w\A8E50951\p\netstandard.dll
" "dotnet" "C:\h\w\A8E50951\p\crossgen2\crossgen2.dll" @"C:\h\w\A8E50951\w\A4AB090D\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\AssemblyToLoad.dll.rsp"   -r:C:\h\w\A8E50951\w\A4AB090D\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\A8E50951\w\A4AB090D\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\AssemblyToLoad.dll
" "dotnet" "C:\h\w\A8E50951\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\A8E50951\w\A4AB090D\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\AssemblyToLoad.dll --out C:\h\w\A8E50951\w\A4AB090D\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\AssemblyToLoad.dll.r2rdump --val"
 3:30:30.42
 3:30:30.42
Respons
```

**Stack trace:**
```
   at Loader_binding._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-08-15T20:10:01.829Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"BuildNumber":"20230815.3","architecture":"x64","AzurePipelinesTestRunId":"7968564","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","Project":"public","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","BuildId":"374709","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked","configuration":"Checked-no_tiered_compilation","DefinitionName":"runtime-coreclr outerloop","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"108","System.JobAttempt":"1","System.StageName":"Build","System.StageAttempt":"1"} | Schedule
2023-08-15T20:10:01.829Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"BuildNumber":"20230815.3","architecture":"x64","AzurePipelinesTestRunId":"7968564","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","Project":"public","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","BuildId":"374709","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked","configuration":"Checked-no_tiered_compilation","DefinitionName":"runtime-coreclr outerloop","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"108","System.JobAttempt":"1","System.StageName":"Build","System.StageAttempt":"1"} | Schedule
2023-08-15T20:09:45.631Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230815.3","AzurePipelinesTestRunId":"7968554","System.StageAttempt":"1","DefinitionName":"runtime-coreclr outerloop","operatingSystem":"OSX.1200.Amd64.Open","System.JobName":"__default","System.PhaseAttempt":"1","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked","DefinitionId":"108","BuildId":"374709","architecture":"x64","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_x64_checked","Reason":"Schedule","System.StageName":"Build"} | Schedule
2023-08-15T20:09:45.631Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230815.3","AzurePipelinesTestRunId":"7968554","System.StageAttempt":"1","DefinitionName":"runtime-coreclr outerloop","operatingSystem":"OSX.1200.Amd64.Open","System.JobName":"__default","System.PhaseAttempt":"1","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked","DefinitionId":"108","BuildId":"374709","architecture":"x64","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_x64_checked","Reason":"Schedule","System.StageName":"Build"} | Schedule
2023-08-15T20:08:25.469Z | runtime-coreclr outerloop | Checked | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"Project":"public","System.PhaseAttempt":"1","BuildId":"374709","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"OSX.1200.ARM64.Open","BuildNumber":"20230815.3","System.StageAttempt":"1","architecture":"arm64","DefinitionName":"runtime-coreclr outerloop","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","AzurePipelinesTestRunId":"7968420","System.JobName":"__default","System.StageName":"Build","System.PhaseName":"run_test_p1__osx_arm64_checked","DefinitionId":"108","System.JobAttempt":"1","configuration":"Checked"} | Schedule
<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-08-15T20:08:25.469Z | runtime-coreclr outerloop | Checked | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"Project":"public","System.PhaseAttempt":"1","BuildId":"374709","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"OSX.1200.ARM64.Open","BuildNumber":"20230815.3","System.StageAttempt":"1","architecture":"arm64","DefinitionName":"runtime-coreclr outerloop","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","AzurePipelinesTestRunId":"7968420","System.JobName":"__default","System.StageName":"Build","System.PhaseName":"run_test_p1__osx_arm64_checked","DefinitionId":"108","System.JobAttempt":"1","configuration":"Checked"} | Schedule
2023-08-15T11:06:40.789Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.StageName":"Build","System.JobName":"__default","configuration":"Checked","System.StageAttempt":"1","Project":"public","System.JobAttempt":"1","AzurePipelinesTestRunId":"7953356","operatingSystem":"OSX.1200.Amd64.Open","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","BuildId":"374118","Reason":"Schedule","BuildNumber":"20230815.1","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","DefinitionId":"108","DefinitionName":"runtime-coreclr outerloop","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked"} | Schedule
2023-08-15T11:06:40.789Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.StageName":"Build","System.JobName":"__default","configuration":"Checked","System.StageAttempt":"1","Project":"public","System.JobAttempt":"1","AzurePipelinesTestRunId":"7953356","operatingSystem":"OSX.1200.Amd64.Open","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","BuildId":"374118","Reason":"Schedule","BuildNumber":"20230815.1","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","DefinitionId":"108","DefinitionName":"runtime-coreclr outerloop","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked"} | Schedule
2023-08-15T11:06:40.789Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.StageName":"Build","System.JobName":"__default","configuration":"Checked","System.StageAttempt":"1","Project":"public","System.JobAttempt":"1","AzurePipelinesTestRunId":"7953356","operatingSystem":"OSX.1200.Amd64.Open","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","BuildId":"374118","Reason":"Schedule","BuildNumber":"20230815.1","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","DefinitionId":"108","DefinitionName":"runtime-coreclr outerloop","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked"} | Schedule
2023-08-15T11:00:56.183Z | runtime-coreclr outerloop | Checked | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"arm64","AzurePipelinesTestRunId":"7953244","configuration":"Checked","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildId":"374118","operatingSystem":"OSX.1200.ARM64.Open","Reason":"Schedule","BuildNumber":"20230815.1","System.PhaseAttempt":"1","System.JobAttempt":"1","Project":"public","System.StageAttempt":"1","DefinitionId":"108","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.StageName":"Build","DefinitionName":"runtime-coreclr outerloop"} | Schedule
2023-08-15T11:00:56.183Z | runtime-coreclr outerloop | Checked | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"arm64","AzurePipelinesTestRunId":"7953244","configuration":"Checked","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildId":"374118","operatingSystem":"OSX.1200.ARM64.Open","Reason":"Schedule","BuildNumber":"20230815.1","System.PhaseAttempt":"1","System.JobAttempt":"1","Project":"public","System.StageAttempt":"1","DefinitionId":"108","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.StageName":"Build","DefinitionName":"runtime-coreclr outerloop"} | Schedule
2023-08-15T11:00:56.183Z | runtime-coreclr outerloop | Checked | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"arm64","AzurePipelinesTestRunId":"7953244","configuration":"Checked","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildId":"374118","operatingSystem":"OSX.1200.ARM64.Open","Reason":"Schedule","BuildNumber":"20230815.1","System.PhaseAttempt":"1","System.JobAttempt":"1","Project":"public","System.StageAttempt":"1","DefinitionId":"108","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.StageName":"Build","DefinitionName":"runtime-coreclr outerloop"} | Schedule
2023-08-15T10:00:15.144Z | runtime-coreclr pgo | Checked-defaultpgo | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"7952554","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.JobAttempt":"1","BuildId":"374094","architecture":"arm64","System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobName":"__default","Project":"public","Reason":"Schedule","operatingSystem":"OSX.1200.ARM64.Open","DefinitionName":"runtime-coreclr pgo","System.StageName":"Build","configuration":"Checked-defaultpgo","DefinitionId":"144","BuildNumber":"20230815.1","System.StageAttempt":"1","System.PhaseAttempt":"1"} | Schedule
2023-08-15T10:00:15.144Z | runtime-coreclr pgo | Checked-defaultpgo | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"7952554","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.JobAttempt":"1","BuildId":"374094","architecture":"arm64","System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobName":"__default","Project":"public","Reason":"Schedule","operatingSystem":"OSX.1200.ARM64.Open","DefinitionName":"runtime-coreclr pgo","System.StageName":"Build","configuration":"Checked-defaultpgo","DefinitionId":"144","BuildNumber":"20230815.1","System.StageAttempt":"1","System.PhaseAttempt":"1"} | Schedule
2023-08-15T10:00:15.144Z | runtime-coreclr pgo | Checked-defaultpgo | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"7952554","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.JobAttempt":"1","BuildId":"374094","architecture":"arm64","System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobName":"__default","Project":"public","Reason":"Schedule","operatingSystem":"OSX.1200.ARM64.Open","DefinitionName":"runtime-coreclr pgo","System.StageName":"Build","configuration":"Checked-defaultpgo","DefinitionId":"144","BuildNumber":"20230815.1","System.StageAttempt":"1","System.PhaseAttempt":"1"} | Schedule
2023-08-15T10:00:15.144Z | runtime-coreclr pgo | Checked-defaultpgo | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"7952554","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.JobAttempt":"1","BuildId":"374094","architecture":"arm64","System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobName":"__default","Project":"public","Reason":"Schedule","operatingSystem":"OSX.1200.ARM64.Open","DefinitionName":"runtime-coreclr pgo","System.StageName":"Build","configuration":"Checked-defaultpgo","DefinitionId":"144","BuildNumber":"20230815.1","System.StageAttempt":"1","System.PhaseAttempt":"1"} | Schedule
2023-08-15T10:00:15.144Z | runtime-coreclr pgo | Checked-defaultpgo | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"7952554","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.JobAttempt":"1","BuildId":"374094","architecture":"arm64","System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobName":"__default","Project":"public","Reason":"Schedule","operatingSystem":"OSX.1200.ARM64.Open","DefinitionName":"runtime-coreclr pgo","System.StageName":"Build","configuration":"Checked-defaultpgo","DefinitionId":"144","BuildNumber":"20230815.1","System.StageAttempt":"1","System.PhaseAttempt":"1"} | Schedule
2023-08-15T10:00:15.144Z | runtime-coreclr pgo | Checked-defaultpgo | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"7952554","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.JobAttempt":"1","BuildId":"374094","architecture":"arm64","System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobName":"__default","Project":"public","Reason":"Schedule","operatingSystem":"OSX.1200.ARM64.Open","DefinitionName":"runtime-coreclr pgo","System.StageName":"Build","configuration":"Checked-defaultpgo","DefinitionId":"144","BuildNumber":"20230815.1","System.StageAttempt":"1","System.PhaseAttempt":"1"} | Schedule
2023-08-15T08:01:44.424Z | coreclr-release-outerloop-nightly | Release | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.PhaseAttempt":"1","AzurePipelinesTestRunId":"7950970","Project":"public","System.PhaseName":"run_test_p1__osx_x64_release","System.JobId":"35f33b9f-4ed4-566d-bf76-b9e04bf55ca5","architecture":"x64","System.StageAttempt":"1","Reason":"Schedule","DefinitionName":"coreclr-release-outerloop-nightly","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20230814.1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","BuildId":"374053","System.JobAttempt":"1","DefinitionId":"135","configuration":"Release","System.JobName":"__default"} | Schedule
2023-08-15T08:01:44.424Z | coreclr-release-outerloop-nightly | Release | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.PhaseAttempt":"1","AzurePipelinesTestRunId":"7950970","Project":"public","System.PhaseName":"run_test_p1__osx_x64_release","System.JobId":"35f33b9f-4ed4-566d-bf76-b9e04bf55ca5","architecture":"x64","System.StageAttempt":"1","Reason":"Schedule","DefinitionName":"coreclr-release-outerloop-nightly","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20230814.1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","BuildId":"374053","System.JobAttempt":"1","DefinitionId":"135","configuration":"Release","System.JobName":"__default"} | Schedule
2023-08-15T08:01:44.424Z | coreclr-release-outerloop-nightly | Release | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.PhaseAttempt":"1","AzurePipelinesTestRunId":"7950970","Project":"public","System.PhaseName":"run_test_p1__osx_x64_release","System.JobId":"35f33b9f-4ed4-566d-bf76-b9e04bf55ca5","architecture":"x64","System.StageAttempt":"1","Reason":"Schedule","DefinitionName":"coreclr-release-outerloop-nightly","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20230814.1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","BuildId":"374053","System.JobAttempt":"1","DefinitionId":"135","configuration":"Release","System.JobName":"__default"} | Schedule
2023-08-15T07:59:28.66Z | coreclr-release-outerloop-nightly | Release | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"DefinitionId":"135","System.PhaseName":"run_test_p1_R2R_osx_x64_release","BuildId":"374053","System.StageAttempt":"1","architecture":"x64","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","System.JobName":"__default","DefinitionName":"coreclr-release-outerloop-nightly","System.JobAttempt":"1","BuildNumber":"20230814.1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","AzurePipelinesTestRunId":"7950950","Reason":"Schedule","System.StageName":"Build","configuration":"Release"} | Schedule
2023-08-15T07:59:28.66Z | coreclr-release-outerloop-nightly | Release | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"DefinitionId":"135","System.PhaseName":"run_test_p1_R2R_osx_x64_release","BuildId":"374053","System.StageAttempt":"1","architecture":"x64","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","System.JobName":"__default","DefinitionName":"coreclr-release-outerloop-nightly","System.JobAttempt":"1","BuildNumber":"20230814.1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","AzurePipelinesTestRunId":"7950950","Reason":"Schedule","System.StageName":"Build","configuration":"Release"} | Schedule
2023-08-15T07:59:28.66Z | coreclr-release-outerloop-nightly | Release | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"DefinitionId":"135","System.PhaseName":"run_test_p1_R2R_osx_x64_release","BuildId":"374053","System.StageAttempt":"1","architecture":"x64","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","System.JobName":"__default","DefinitionName":"coreclr-release-outerloop-nightly","System.JobAttempt":"1","BuildNumber":"20230814.1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","AzurePipelinesTestRunId":"7950950","Reason":"Schedule","System.StageName":"Build","configuration":"Release"} | Schedule
2023-08-15T07:59:27.485Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"Project":"public","configuration":"Release-no_tiered_compilation","System.JobName":"__default","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20230814.1","DefinitionName":"coreclr-release-outerloop-nightly","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"135","System.JobAttempt":"1","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","System.StageAttempt":"1","AzurePipelinesTestRunId":"7950952","System.PhaseAttempt":"1","BuildId":"374053","Reason":"Schedule","System.StageName":"Build","System.PhaseName":"run_test_p1_R2R_osx_x64_release"} | Schedule
2023-08-15T07:59:27.485Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"Project":"public","configuration":"Release-no_tiered_compilation","System.JobName":"__default","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20230814.1","DefinitionName":"coreclr-release-outerloop-nightly","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"135","System.JobAttempt":"1","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","System.StageAttempt":"1","AzurePipelinesTestRunId":"7950952","System.PhaseAttempt":"1","BuildId":"374053","Reason":"Schedule","System.StageName":"Build","System.PhaseName":"run_test_p1_R2R_osx_x64_release"} | Schedule
2023-08-15T07:59:27.485Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | osx.1200.amd64.open | x64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"Project":"public","configuration":"Release-no_tiered_compilation","System.JobName":"__default","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20230814.1","DefinitionName":"coreclr-release-outerloop-nightly","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"135","System.JobAttempt":"1","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","System.StageAttempt":"1","AzurePipelinesTestRunId":"7950952","System.PhaseAttempt":"1","BuildId":"374053","Reason":"Schedule","System.StageName":"Build","System.PhaseName":"run_test_p1_R2R_osx_x64_release"} | Schedule
2023-08-15T07:59:25.313Z | coreclr-release-outerloop-nightly | Release | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.PhaseAttempt":"1","System.StageAttempt":"1","DefinitionId":"135","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"7950946","System.JobName":"__default","System.JobId":"e67f486c-1397-564e-9443-0513ec888494","Project":"public","Reason":"Schedule","BuildId":"374053","configuration":"Release","BuildNumber":"20230814.1","DefinitionName":"coreclr-release-outerloop-nightly","System.JobAttempt":"1","operatingSystem":"OSX.1200.ARM64.Open","System.PhaseName":"run_test_p1__osx_arm64_release","System.StageName":"Build"} | Schedule
2023-08-15T07:59:25.313Z | coreclr-release-outerloop-nightly | Release | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.PhaseAttempt":"1","System.StageAttempt":"1","DefinitionId":"135","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"7950946","System.JobName":"__default","System.JobId":"e67f486c-1397-564e-9443-0513ec888494","Project":"public","Reason":"Schedule","BuildId":"374053","configuration":"Release","BuildNumber":"20230814.1","DefinitionName":"coreclr-release-outerloop-nightly","System.JobAttempt":"1","operatingSystem":"OSX.1200.ARM64.Open","System.PhaseName":"run_test_p1__osx_arm64_release","System.StageName":"Build"} | Schedule
2023-08-15T07:59:25.313Z | coreclr-release-outerloop-nightly | Release | osx.1200.arm64.open | arm64 | Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh | Failed | {"System.PhaseAttempt":"1","System.StageAttempt":"1","DefinitionId":"135","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"7950946","System.JobName":"__default","System.JobId":"e67f486c-1397-564e-9443-0513ec888494","Project":"public","Reason":"Schedule","BuildId":"374053","configuration":"Release","BuildNumber":"20230814.1","DefinitionName":"coreclr-release-outerloop-nightly","System.JobAttempt":"1","operatingSystem":"OSX.1200.ARM64.Open","System.PhaseName":"run_test_p1__osx_arm64_release","System.StageName":"Build"} | Schedule
</details>

### LINKED ISSUE #90593: BinderTracingTest_ResolutionFlow test fails
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=373766
Build error leg or test failing: Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh
Pull request: https://github.com/dotnet/runtime/pull/90536

## Error Message
From the log:
```
Starting:    Loader.binding.XUnitWrapper (parallel test collections = on, max threads = 12)
    Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh [FAIL]
      [createdump] Invalid process id: task_for_pid(49565) FAILED (os/kern) failure (5)
      [createdump] This failure may be because createdump or the application is not properly signed and entitled.
      [createdump] Failure took 1ms
      waitpid() returned successfully (wstatus 0000ff00) WEXITSTATUS ff WTERMSIG 0
      /private/tmp/helix/working/C3180A61/w/9FDF083E/e/Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh: line 454: 49565 Segmentation fault: 11  (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /tmp/helix/working/C3180A61/w/9FDF083E/uploads/Reports/Loader.binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.output.txt
      Raw output:
      BEGIN EXECUTION
      /tmp/helix/working/C3180A61/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true BinderTracingTest.ResolutionFlow.dll ''
      [10:18:00 PM] Running AssemblyLoadContextResolving_ReturnNull...
      [10:18:01 PM] Running AssemblyLoadContextResolving_LoadAssembly...
      [10:18:01 PM] Running AssemblyLoadContextResolving_NameMismatch...
      [10:18:01 PM] Running AssemblyLoadContextResolving_MultipleHandlers...
      [10:18:02 PM] Running AppDomainAssemblyResolve_ReturnNull...
      [10:18:02 PM] Running AppDomainAssemblyResolve_LoadAssembly...
      [10:18:02 PM] Running AppDomainAssemblyResolve_NameMismatch...
      [10:18:02 PM] Running AppDomainAssemblyResolve_MultipleHandlers...
      [10:18:02 PM] Launching process for AssemblyLoadFromResolveHandler_LoadDependency...
      [createdump] Target process is alive
      Expected: 100
      Actual: 139
      END EXECUTION - FAILED
      Test failed. Trying to see if dump file was created in /cores since 8/14/2023 10:18:00 PM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/tmp/helix/working/C3180A61/p
      > /private/tmp/helix/working/C3180A61/w/9FDF083E/e/Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at Loader_binding._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
      Output:
        [createdump] Invalid process id: task_for_pid(49565) FAILED (os/kern) failure (5)
        [createdump] This failure may be because createdump or the application is not properly signed and entitled.
        [createdump] Failure took 1ms
        waitpid() returned successfully (wstatus 0000ff00) WEXITSTATUS ff WTERMSIG 0
        /private/tmp/helix/working/C3180A61/w/9FDF083E/e/Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh: line 454: 49565 Segmentation fault: 11  (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /tmp/helix/working/C3180A61/w/9FDF083E/uploads/Reports/Loader.binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.output.txt
        Raw output:
        BEGIN EXECUTION
        /tmp/helix/working/C3180A61/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true BinderTracingTest.ResolutionFlow.dll ''
        [10:18:00 PM] Running AssemblyLoadContextResolving_ReturnNull...
        [10:18:01 PM] Running AssemblyLoadContextResolving_LoadAssembly...
        [10:18:01 PM] Running AssemblyLoadContextResolving_NameMismatch...
        [10:18:01 PM] Running AssemblyLoadContextResolving_MultipleHandlers...
        [10:18:02 PM] Running AppDomainAssemblyResolve_ReturnNull...
        [10:18:02 PM] Running AppDomainAssemblyResolve_LoadAssembly...
        [10:18:02 PM] Running AppDomainAssemblyResolve_NameMismatch...
        [10:18:02 PM] Running AppDomainAssemblyResolve_MultipleHandlers...
        [10:18:02 PM] Launching process for AssemblyLoadFromResolveHandler_LoadDependency...
        [createdump] Target process is alive
        Expected: 100
        Actual: 139
        END EXECUTION - FAILED
        Test failed. Trying to see if dump file was created in /cores since 8/14/2023 10:18:00 PM
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/tmp/helix/working/C3180A61/p
        > /private/tmp/helix/working/C3180A61/w/9FDF083E/e/Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh
```

```json
{
  "ErrorMessage": "at Loader_binding._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_sh()",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=373766
**Error message validated:** `at Loader_binding._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_sh()`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/15/2023 1:25:39 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[379711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379711)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379711&view=ms.vss-test-web.build-test-results-tab&runId=8087970&resultId=110958)|dotnet/runtime#90841|
|[379525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379525)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379525&view=ms.vss-test-web.build-test-results-tab&runId=8084306&resultId=110958)|dotnet/runtime#90816|
|[379068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379068)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379068&view=ms.vss-test-web.build-test-results-tab&runId=8084020&resultId=110747)|dotnet/runtime#90766|
|[379491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379491)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379491&view=ms.vss-test-web.build-test-results-tab&runId=8083476&resultId=110747)||
|[378960](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378960)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378960&view=ms.vss-test-web.build-test-results-tab&runId=8074744&resultId=118944)||
|[378953](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378953)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378953&view=ms.vss-test-web.build-test-results-tab&runId=8074802&resultId=110956)|dotnet/runtime#90817|
|[378961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378961)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378961&view=ms.vss-test-web.build-test-results-tab&runId=8072644&resultId=112831)||
|[378889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378889)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378889&view=ms.vss-test-web.build-test-results-tab&runId=8072176&resultId=110747)|dotnet/runtime#90814|
|[378706](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378706)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378706&view=ms.vss-test-web.build-test-results-tab&runId=8072262&resultId=112835)|dotnet/runtime#90799|
|[378806](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378806)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378806&view=ms.vss-test-web.build-test-results-tab&runId=8069370&resultId=110960)|dotnet/runtime#90255|
|[378741](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378741)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378741&view=ms.vss-test-web.build-test-results-tab&runId=8067052&resultId=110917)|dotnet/runtime#90792|
|[378683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378683)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378683&view=ms.vss-test-web.build-test-results-tab&runId=8066350&resultId=120824)||
|[378751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378751)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378751&view=ms.vss-test-web.build-test-results-tab&runId=8066934&resultId=110960)|dotnet/runtime#90778|
|[378684](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378684)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378684&view=ms.vss-test-web.build-test-results-tab&runId=8065780&resultId=112833)||
|[378712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378712)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378712&view=ms.vss-test-web.build-test-results-tab&runId=8066170&resultId=110959)|dotnet/runtime#90802|
|[378671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378671)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378671&view=ms.vss-test-web.build-test-results-tab&runId=8065600&resultId=110960)|dotnet/runtime#90796|
|[378641](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378641)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378641&view=ms.vss-test-web.build-test-results-tab&runId=8064530&resultId=110749)|dotnet/runtime#88572|
|[378548](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378548)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378548&view=ms.vss-test-web.build-test-results-tab&runId=8064416&resultId=117779)|dotnet/runtime#90790|
|[378544](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378544)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378544&view=ms.vss-test-web.build-test-results-tab&runId=8063824&resultId=110749)|dotnet/runtime#90790|
|[378502](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378502)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378502&view=ms.vss-test-web.build-test-results-tab&runId=8063104&resultId=110960)|dotnet/runtime#90789|
|[378437](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378437)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378437&view=ms.vss-test-web.build-test-results-tab&runId=8060186&resultId=118947)||
|[378417](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378417)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378417&view=ms.vss-test-web.build-test-results-tab&runId=8059638&resultId=120825)||
|[378419](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378419)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378419&view=ms.vss-test-web.build-test-results-tab&runId=8059306&resultId=112834)||
|[378393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378393)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378393&view=ms.vss-test-web.build-test-results-tab&runId=8059066&resultId=110959)|dotnet/runtime#89636|
|[378365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378365)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378365&view=ms.vss-test-web.build-test-results-tab&runId=8058896&resultId=118040)||
|[378374](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378374)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378374&view=ms.vss-test-web.build-test-results-tab&runId=8058856&resultId=110959)|dotnet/runtime#90734|
|[378343](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378343)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378343&view=ms.vss-test-web.build-test-results-tab&runId=8058018&resultId=118152)||
|[378363](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378363)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378363&view=ms.vss-test-web.build-test-results-tab&runId=8058498&resultId=110958)||
|[378364](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378364)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378364&view=ms.vss-test-web.build-test-results-tab&runId=8058268&resultId=112832)||
|[378344](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378344)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378344&view=ms.vss-test-web.build-test-results-tab&runId=8058022&resultId=120823)||
|[378339](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378339)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378339&view=ms.vss-test-web.build-test-results-tab&runId=8057236&resultId=120825)||
|[378291](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378291)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378291&view=ms.vss-test-web.build-test-results-tab&runId=8056430&resultId=118944)||
|[378312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378312)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378312&view=ms.vss-test-web.build-test-results-tab&runId=8056330&resultId=110956)||
|[378266](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378266)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378266&view=ms.vss-test-web.build-test-results-tab&runId=8056046&resultId=118947)||
|[378292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378292)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378292&view=ms.vss-test-web.build-test-results-tab&runId=8056164&resultId=110958)||
|[378195](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378195)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378195&view=ms.vss-test-web.build-test-results-tab&runId=8055716&resultId=118946)||
|[378272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378272)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378272&view=ms.vss-test-web.build-test-results-tab&runId=8055908&resultId=110748)|dotnet/runtime#90778|
|[378186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378186)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378186&view=ms.vss-test-web.build-test-results-tab&runId=8055284&resultId=110749)|dotnet/runtime#90681|
|[378152](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378152)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378152&view=ms.vss-test-web.build-test-results-tab&runId=8055230&resultId=110748)|dotnet/runtime#90558|
|[378175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378175)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378175&view=ms.vss-test-web.build-test-results-tab&runId=8055292&resultId=110959)|dotnet/runtime#90777|
|[378140](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378140)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378140&view=ms.vss-test-web.build-test-results-tab&runId=8055240&resultId=110959)|dotnet/runtime#90773|
|[377853](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377853)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377853&view=ms.vss-test-web.build-test-results-tab&runId=8054940&resultId=118944)||
|[378155](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378155)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378155&view=ms.vss-test-web.build-test-results-tab&runId=8055092&resultId=110956)||
|[378106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378106)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378106&view=ms.vss-test-web.build-test-results-tab&runId=8054534&resultId=112833)||
|[377988](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377988)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377988&view=ms.vss-test-web.build-test-results-tab&runId=8053722&resultId=110959)|dotnet/runtime#90708|
|[377994](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377994)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377994&view=ms.vss-test-web.build-test-results-tab&runId=8053518&resultId=110959)|dotnet/runtime#90772|
|[377965](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377965)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377965&view=ms.vss-test-web.build-test-results-tab&runId=8052992&resultId=112835)|dotnet/runtime#90468|
|[377927](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377927)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377927&view=ms.vss-test-web.build-test-results-tab&runId=8051722&resultId=112834)||
|[377811](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377811)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377811&view=ms.vss-test-web.build-test-results-tab&runId=8050386&resultId=118944)||
|[377783](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377783)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377783&view=ms.vss-test-web.build-test-results-tab&runId=8050390&resultId=110959)|dotnet/runtime#90765|
|[377681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377681)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377681&view=ms.vss-test-web.build-test-results-tab&runId=8048620&resultId=118152)||
|[377697](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377697)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377697&view=ms.vss-test-web.build-test-results-tab&runId=8049698&resultId=110959)|dotnet/runtime#90418|
|[377711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377711)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377711&view=ms.vss-test-web.build-test-results-tab&runId=8048716&resultId=110749)|dotnet/runtime#90681|
|[373307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373307)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373307&view=ms.vss-test-web.build-test-results-tab&runId=8048560&resultId=112831)|dotnet/runtime#81993|
|[377685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377685)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377685&view=ms.vss-test-web.build-test-results-tab&runId=8047538&resultId=110956)|dotnet/runtime#90749|
|[377743](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377743)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377743&view=ms.vss-test-web.build-test-results-tab&runId=8046302&resultId=110956)||
|[377736](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377736)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377736&view=ms.vss-test-web.build-test-results-tab&runId=8046150&resultId=110956)||
|[377631](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377631)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377631&view=ms.vss-test-web.build-test-results-tab&runId=8045956&resultId=112831)|dotnet/runtime#90761|
|[377628](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377628)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377628&view=ms.vss-test-web.build-test-results-tab&runId=8045198&resultId=112831)|dotnet/runtime#90623|
|[377625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377625)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377625&view=ms.vss-test-web.build-test-results-tab&runId=8044366&resultId=110956)|dotnet/runtime#90623|
|[374618](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374618)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374618&view=ms.vss-test-web.build-test-results-tab&runId=8043260&resultId=112832)|dotnet/runtime#90556|
|[377337](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377337)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377337&view=ms.vss-test-web.build-test-results-tab&runId=8041794&resultId=120823)|dotnet/runtime#90735|
|[377335](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377335)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377335&view=ms.vss-test-web.build-test-results-tab&runId=8041510&resultId=120823)|dotnet/runtime#90735|
|[377587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377587)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377587&view=ms.vss-test-web.build-test-results-tab&runId=8041406&resultId=110958)|dotnet/runtime#90758|
|[377462](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377462)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377462&view=ms.vss-test-web.build-test-results-tab&runId=8037432&resultId=119743)||
|[377459](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377459)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377459&view=ms.vss-test-web.build-test-results-tab&runId=8037172&resultId=119258)||
|[377507](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377507)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377507&view=ms.vss-test-web.build-test-results-tab&runId=8037976&resultId=112832)|dotnet/runtime#90752|
|[377466](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377466)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377466&view=ms.vss-test-web.build-test-results-tab&runId=8036380&resultId=112623)||
|[377460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377460)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377460&view=ms.vss-test-web.build-test-results-tab&runId=8036048&resultId=112447)||
|[377449](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377449)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377449&view=ms.vss-test-web.build-test-results-tab&runId=8035084&resultId=110957)|dotnet/runtime#90747|
|[377427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377427)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377427&view=ms.vss-test-web.build-test-results-tab&runId=8034580&resultId=112833)|dotnet/runtime#90468|
|[377393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377393)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377393&view=ms.vss-test-web.build-test-results-tab&runId=8032468&resultId=110956)|dotnet/runtime#90739|
|[377315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377315)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377315&view=ms.vss-test-web.build-test-results-tab&runId=8030860&resultId=110957)|dotnet/runtime#90734|
|[377195](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377195)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377195&view=ms.vss-test-web.build-test-results-tab&runId=8027448&resultId=110957)|dotnet/runtime#90727|
|[377137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377137)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377137&view=ms.vss-test-web.build-test-results-tab&runId=8027438&resultId=112832)|dotnet/runtime#90724|
|[377143](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377143)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377143&view=ms.vss-test-web.build-test-results-tab&runId=8026912&resultId=118945)||
|[377189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377189)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377189&view=ms.vss-test-web.build-test-results-tab&runId=8027028&resultId=110957)|dotnet/runtime#90729|
|[377156](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377156)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377156&view=ms.vss-test-web.build-test-results-tab&runId=8026486&resultId=112832)|dotnet/runtime#90726|
|[377123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377123)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377123&view=ms.vss-test-web.build-test-results-tab&runId=8025146&resultId=112624)||
|[377101](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377101)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377101&view=ms.vss-test-web.build-test-results-tab&runId=8024624&resultId=112832)|dotnet/runtime#90719|
|[377064](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377064)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377064&view=ms.vss-test-web.build-test-results-tab&runId=8024160&resultId=117509)||
|[377080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377080)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377080&view=ms.vss-test-web.build-test-results-tab&runId=8024184&resultId=110746)|dotnet/runtime#90255|
|[377045](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377045)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377045&view=ms.vss-test-web.build-test-results-tab&runId=8023414&resultId=118150)||
|[377063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377063)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377063&view=ms.vss-test-web.build-test-results-tab&runId=8023556&resultId=110745)||
|[377061](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377061)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377061&view=ms.vss-test-web.build-test-results-tab&runId=8023580&resultId=110956)||
|[376942](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376942)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376942&view=ms.vss-test-web.build-test-results-tab&runId=8023134&resultId=120823)||
|[377027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377027)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377027&view=ms.vss-test-web.build-test-results-tab&runId=8022884&resultId=118152)||
|[376926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376926)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376926&view=ms.vss-test-web.build-test-results-tab&runId=8022448&resultId=110959)|dotnet/runtime#90700|
|[376952](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376952)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376952&view=ms.vss-test-web.build-test-results-tab&runId=8021962&resultId=118944)||
|[376985](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376985)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376985&view=ms.vss-test-web.build-test-results-tab&runId=8021998&resultId=110957)|dotnet/runtime#90058|
|[376960](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376960)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376960&view=ms.vss-test-web.build-test-results-tab&runId=8022008&resultId=112832)|dotnet/runtime#90712|
|[376839](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376839)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376839&view=ms.vss-test-web.build-test-results-tab&runId=8021568&resultId=120822)||
|[376894](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376894)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376894&view=ms.vss-test-web.build-test-results-tab&runId=8021558&resultId=110957)|dotnet/runtime#90708|
|[376937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376937)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376937&view=ms.vss-test-web.build-test-results-tab&runId=8021448&resultId=110745)||
|[376832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376832)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376832&view=ms.vss-test-web.build-test-results-tab&runId=8021342&resultId=110746)|dotnet/runtime#90695|
|[376888](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376888)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376888&view=ms.vss-test-web.build-test-results-tab&runId=8021434&resultId=110745)|dotnet/runtime#90668|
|[376803](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376803)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376803&view=ms.vss-test-web.build-test-results-tab&runId=8021274&resultId=110956)|dotnet/runtime#90704|
|[376824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376824)|dotnet/runtime|[Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376824&view=ms.vss-test-web.build-test-results-tab&runId=8021184&resultId=110746)|dotnet/runtime#90707|
|[376807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376807)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376807&view=ms.vss-test-web.build-test-results-tab&runId=8021030&resultId=110957)|dotnet/runtime#90705|
|[376790](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376790)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376790&view=ms.vss-test-web.build-test-results-tab&runId=8020910&resultId=110956)|dotnet/runtime#90703|
Displaying 100 of 193 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|17|193|193|

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Dynamically generated methods like [`UnsafeAccessorAttribute`](https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.unsafeaccessorattribute)
functions are marked as IL, but don't contain an IL header.
The lack of header is an indication the IL must be generated
at runtime.

Fixes #90485
Fixes #90580
Fixes #90593

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
This also reverts https://github.com/dotnet/runtime/pull/90801.

**Comment by AaronRobinsonMSFT** [comment]
There are also two places in the dac that should probably be updated.

File: src/coreclr/debug/daccess/stack.cpp [hunk 1]
```diff
@@ -1253,7 +1253,10 @@ ClrDataFrame::GetLocalSig(MetaSig** sig,
     {
         // It turns out we cannot really get rid of this check.  Dynamic methods
         // (including IL stubs) do not have their local sig's available after JIT time.
-        if (!m_methodDesc->IsIL())
+        // IL Methods with dynamically generated IL (for example, UnsafeAccessors) can
+        // may have not have an IL header.
```
Comment (tlakollo) [inline src/coreclr/debug/daccess/stack.cpp:1257]:
```suggestion
        // IL Methods with dynamically generated IL (for example, UnsafeAccessors) may
        // not have an IL header.
```

File: src/coreclr/vm/eventtrace.cpp [hunk 2]
```diff
@@ -4566,9 +4566,13 @@ VOID ETW::MethodLog::SendMethodJitStartEvent(MethodDesc *pMethodDesc, SString *n
...
         }
         else
+        {
             ulMethodToken = (ULONG)pMethodDesc->GetMemberDef();
+        }
 
-        if(pMethodDesc->IsIL())
+        // An IL method that has no IL header can occur for dynamically
+        // generated code during JIT (for example, UnsafeAccessor).
+        if(pMethodDesc->IsIL() && pMethodDesc->GetILHeader() != NULL)
```
Comment (jkotas) [inline src/coreclr/vm/eventtrace.cpp:4575]: `GetILHeader` is not trivial operation. We should avoid calling it twice.

(It would be even better to let caller pass it in so that it matches what was actually JITed. `GetILHeader` does not provide stable results in the presence of rejit.)

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/eventtrace.cpp:4575]: > It would be even better to let caller pass it in so that it matches what was actually JITed. GetILHeader does not provide stable results in the presence of rejit.

That is going to make this PR a bit larger. Is that what you want?

Comment (jkotas) [reply src/coreclr/vm/eventtrace.cpp:4575]: I do not have a problem with making the PR a bit larger. I do not see a significant risk with doing the right thing here.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/eventtrace.cpp:4575]: I don't even think we should consider this. It is far too much change right now. I will add this to my backlog and handle it later.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/eventtrace.cpp:4575]: Didn't see your reply. Okay. I will give it a shot.

Comment (jkotas) [reply src/coreclr/vm/eventtrace.cpp:4575]: (It is fine with me to do the cleanup later.)

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/eventtrace.cpp]: It was simple, I just wasn't sure how much churn we wanted. Let me know if you'd like me to revert it.

File: src/coreclr/debug/daccess/stack.cpp [hunk 3]
```diff
@@ -1253,7 +1253,10 @@ ClrDataFrame::GetLocalSig(MetaSig** sig,
     {
         // It turns out we cannot really get rid of this check.  Dynamic methods
         // (including IL stubs) do not have their local sig's available after JIT time.
-        if (!m_methodDesc->IsIL())
+        // IL Methods with dynamically generated IL (for example, UnsafeAccessors) may
+        // not have an IL header.
+        if (!m_methodDesc->IsIL()
```
Comment (jkotas) [inline src/coreclr/debug/daccess/stack.cpp:1258]: Avoid the duplicate `GetILHeader` call here as well?

**Review by jkotas — APPROVED** [review]
LGTM. Thank you!

**Comment by AaronRobinsonMSFT** [comment]
Failure is https://github.com/dotnet/runtime/issues/90605
