### PR TITLE
No-op ConcurrentStack.PushRange(T[]) if empty

### LINKED ISSUE #62121: ConcurrentStack.PushRange(T[]) throws an ArgumentOutOfRangeException on empty T[]
### Description

`ConcurrentStack<T>.PushRange(T[])` throws an ArgumentOutOfRangeException when `T[]` is an empty array. The exception message is 'The startIndex argument must be greater than or equal to zero.'.

- This behavior is not documented
- It should do nothing instead of throwing an exception, like `List<T>.AddRange(IEnumerable<T>)` does

### Reproduction Steps

`new ConcurrentStack<int>().PushRange(Array.Empty<int>());`

### Expected behavior

It should not throw an exception.

### Actual behavior

It throws an ArgumentOutOfRangeException: 'The startIndex argument must be greater than or equal to zero.'

### Regression?

_No response_

### Known Workarounds

Check the array for `Length > 0` before calling `ConcurrentStack<T>.PushRange(T[])`.

### Configuration

.NET 6.0.100

### Other information

_No response_

### PR DESCRIPTION
**Pull request by martincostello**
Resolves #62121.

### CODE REVIEW

File: src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs [hunk 1]
```diff
@@ -349,7 +354,6 @@ public void PushRange(T[] items, int startIndex, int count)
             if (count == 0)
                 return;
```
Comment (martincostello) [inline src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs:355]: In retrospect, I guess this condition should be removed because it's redundant?

**Comment by stephentoub** [comment]
Thanks.

This would address the case of `PushRange(empty)`, but not of `PushRange(empty, 0, 0)`, which should be functionally identical.

I suggest the right fix is simply to change this condition:
https://github.com/dotnet/runtime/blob/a4cab7d3206027566dc14672669caeac56ef8400/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs#L413
from
```C#
if (startIndex >= length || startIndex < 0)
```
to
```C#
if (startIndex > length || startIndex < 0)
```
or even:
```C#
if ((uint)startIndex >= length)
```
i.e. it should be fine to have the start index be at the end of the array, as long as the count is 0, which the subsequent check validates.

File: src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs [hunk 2]
```diff
@@ -316,6 +316,11 @@ public void PushRange(T[] items)
             {
                 throw new ArgumentNullException(nameof(items));
             }
+
+            // No op if the length is zero
+            if (items.Length == 0)
```
Comment (eiriktsarpalis) [inline src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs:321]: If we're making this change I'd argue we should also do the same for `PushRange(array, 0, 0)` calls. That would also avoid the need for making this check twice.

**Comment by martincostello** [comment]
Thanks both - I did think about that, but then asking to start from index 0 (which doesn't exist) seemed to be an equally valid mistake to me at first sight on an empty array when the range is specified, so went with this initially to gauge thoughts.

I'll update the PR as suggested 👍

**Review by eiriktsarpalis — APPROVED** [review]

**Comment by stephentoub** [comment]
> asking to start from index 0 (which doesn't exist) seemed to be an equally valid mistake to me

This is how things generally work in .NET, e.g. you can insert at the end of a collection with the index == length,  you can take a 0-length substring at the end of a string,  etc.

File: src/libraries/System.Collections.Concurrent/tests/ConcurrentStackTests.cs [hunk 3]
```diff
@@ -63,6 +63,26 @@ public void PushRange_NoItems_NothingAdded()
...
+
+        [Fact]
+        public void PushRange_NoItems_NothingAdded_EmptyArrayNoRangeSpecified()
+        {
+            var s = new ConcurrentStack<int>();
+            Assert.True(s.IsEmpty);
+
+            s.PushRange(new int[0]);
+            Assert.True(s.IsEmpty);
+        }
```
Comment (stephentoub) [inline src/libraries/System.Collections.Concurrent/tests/ConcurrentStackTests.cs:84]: We should also validate with a zero count at the end of a non-empty array,  e.g.
```C#
int[] arr = new int[2];
s.PushRange(arr, arr.Length, 0);
```

File: src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs [hunk 4]
```diff
@@ -410,7 +410,7 @@ private static void ValidatePushPopRangeInput(T[] items, int startIndex, int cou
                 throw new ArgumentOutOfRangeException(nameof(count), SR.ConcurrentStack_PushPopRange_CountOutOfRange);
             }
             int length = items.Length;
-            if (startIndex >= length || startIndex < 0)
```
Comment (Clockwork-Muse) [inline src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs:413]: Doesn't this change the exception observed when `startIndex == length`, with a non-zero `count`?  You've added a test that catches `ArgumentException` for this case - is that the exception that occurs before this change?  (Also, it may be good to add a similar case for a non-empty array regardless)

Not that anybody should be catching `ArgumentException`, so as breaking changes go this is relatively minor...
