### PR TITLE
Annotate TypeConverterAttribute so that the ILLinker preserves the ctor on the converter

### LINKED ISSUE #39125: TypeConverterAttribute needs to be annotated so the ILLinker preserves the ctor on the converter
If you link the following app:

```C#
using System;
using System.ComponentModel;
using System.Globalization;

/// <summary>
/// Tests that System.ComponentModel.TypeConverter.ConvertFromInvariantString
/// is not trimmed out when needed by DefaultValueAttribute in a trimmed application.
/// </summary>
class Program
{
    static int Main(string[] args)
    {
        TypeDescriptor.AddAttributes(typeof(string), new TypeConverterAttribute(typeof(MyStringConverter)));

        var attribute = new DefaultValueAttribute(typeof(string), "Hello, world!");
        return (string)attribute.Value == "Hello, world!trivia" ? 100 : -1;
    }

    private class MyStringConverter : StringConverter
    {
        /// <summary>
        /// Converts the specified value object to a string object.
        /// </summary>
        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            if (value is string)
            {
                return (string)value + "trivia";
            }

            throw new NotSupportedException();
        }
    }
}
```

It fails because `MyStringConverter` is not getting its ctor preserved. This is because `TypeConverterAttribute` needs to have a `[DynamicallyAccessedMembers(PublicParameterlessConstructor)]` annotations on it:

https://github.com/dotnet/runtime/blob/a9944fa8a721af673999d074caf1dd74617f6ba6/src/libraries/System.ObjectModel/src/System/ComponentModel/TypeConverterAttribute.cs#L33-L41

`ConverterTypeName` is used elsewhere to create the object:

https://github.com/dotnet/runtime/blob/a9944fa8a721af673999d074caf1dd74617f6ba6/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.ReflectedTypeData.cs#L192-L196

@joperezr @layomia

### PR DESCRIPTION
**Pull request by layomia**
Fixes https://github.com/dotnet/runtime/issues/39125

### CODE REVIEW

File: src/libraries/System.ObjectModel/src/System/ComponentModel/TypeConverterAttribute.cs [hunk 1]
```diff
@@ -30,7 +32,7 @@ public TypeConverterAttribute()
         /// class, using the specified type as the data converter for the object this attribute
         /// is bound to.
         /// </summary>
-        public TypeConverterAttribute(Type type)
+        public TypeConverterAttribute([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] Type type)
```
Comment (eerhardt) [inline src/libraries/System.ObjectModel/src/System/ComponentModel/TypeConverterAttribute.cs:35]: See [my comment here](https://github.com/dotnet/runtime/issues/39125#issuecomment-657816918), this should be `PublicConstructors` instead since the converter can have a ctor that takes the underlying `Type` as well.

Comment (eerhardt) [reply src/libraries/System.ObjectModel/src/System/ComponentModel/TypeConverterAttribute.cs:35]: It might be nice to also test a type that uses a ctor that takes an underlying `Type`, e.g. [NullableConverter](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/NullableConverter.cs) or [EnumConverter](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/EnumConverter.cs).

File: src/libraries/System.ObjectModel/tests/TrimmingTests/TypeConverterAttributeCtorTest.cs [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+            // Type-based TypeConverterAttribute ctor overload, ensure public parameterized ctor of TypeConverter type is preserved.
+            TypeDescriptor.AddAttributes(typeof(DayOfWeek), new TypeConverterAttribute(typeof(EnumConverter)));
+            var attribute = new DefaultValueAttribute(typeof(DayOfWeek), "Friday");
+            if ((DayOfWeek)attribute.Value != DayOfWeek.Friday)
+            {
+                return -1;
+            }
+
+            // String-based TypeConverterAttribute ctor overload, ensure public parameterless ctor of TypeConverter type is preserved.
+            TypeDescriptor.AddAttributes(typeof(string), new TypeConverterAttribute("TypeConverterAttributeTest.MyStringConverter, project, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"));
```
Comment (eerhardt) [inline src/libraries/System.ObjectModel/tests/TrimmingTests/TypeConverterAttributeCtorTest.cs:27]: You need to use a different type here to get the test coverage. The Type overload test above would preserve the constructor of this type. And even if we messed up the string overload this test would pass.

File: src/libraries/System.ObjectModel/tests/TrimmingTests/TypeConverterAttributeCtorTest.cs [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    /// <summary>
+    /// Tests that the public constructors of types passed into System.ComponentModel.TypeConverterAttribute
+    /// are not trimmed out when needed in a trimmed application.
+    /// </summary>
+    class Program
+    {
+        static int Main(string[] args)
+        {
+            // Type-based TypeConverterAttribute ctor overload, ensure public parameterized ctor of TypeConverter type is preserved.
+            TypeDescriptor.AddAttributes(typeof(DayOfWeek), new TypeConverterAttribute(typeof(EnumConverter)));
```
Comment (eerhardt) [inline src/libraries/System.ObjectModel/tests/TrimmingTests/TypeConverterAttributeCtorTest.cs:19]: I'd be careful using a built-in type `EnumConverter` here. There will be other reasons this type gets preserved correctly - see https://github.com/dotnet/runtime/issues/38582.

We should probably be using a custom type to ensure this test is testing the overload correctly.

File: src/libraries/System.ObjectModel/tests/TrimmingTests/TypeConverterAttributeCtorTest.cs [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+    class Program
+    {
+        static int Main(string[] args)
+        {
+            // Type-based TypeConverterAttribute ctor overload, ensure public parameterized ctor of TypeConverter type is preserved.
+            TypeDescriptor.AddAttributes(typeof(DayOfWeek), new TypeConverterAttribute(typeof(MyDayOfWeekConverter)));
+            var attribute = new DefaultValueAttribute(typeof(DayOfWeek), "Friday");
+            if ((DayOfWeek)attribute.Value != DayOfWeek.Monday)
+            {
+                return -1;
```
Comment (joperezr) [inline src/libraries/System.ObjectModel/tests/TrimmingTests/TypeConverterAttributeCtorTest.cs:23]: Would it make sense to separate these into two different tests in order to isolate the use of each one?

**Review by joperezr — APPROVED** [review]
Left a small question but otherwise this looks good!

**Comment by layomia** [comment]
CI run appears to be complete https://dev.azure.com/dnceng/public/_build/results?buildId=743476&view=logs&j=a9d0dd01-e81d-52b7-e673-948d9174db20.

**Review by eerhardt — COMMENTED** [review]
We should have also removed this workaround which was linked to this bug:

https://github.com/dotnet/runtime/blob/142021c172e2e3b60d6c7e58a4e514002f1679c5/src/libraries/System.Runtime/tests/TrimmingTests/DefaultValueAttributeCtorTest.cs#L16-L18
