### PR TITLE
Handle empty string parameter value in MetadataLoadContext

### LINKED ISSUE #57238: ParameterInfo.RawDefaultValue throws when default value is string.empty
### Description

When using a metaDataLoadContext to find static methods in an assembly, invoking `ParameterInfo.RawDefaultValue` throws a badformat exception - I've tracked down the line of code to here:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaDefaultValueProcessing.cs#L18

this appears to throw when the parameter in question is an optional string with a default value of empty string `""`
It looks like `constantValue.Value` is nil in this case. I'm not sure if it's simply an issue with empty strings in all cases or its an environment issue.

### Configuration

* Which version of .NET is the code running on? `.net 4.8`
* What OS and version, and what distro if applicable? `windows 10 2004`
* What is the architecture (x64, x86, ARM, ARM64)? `x64`
* Do you know whether it is specific to that configuration? `do not know`
* If you're using Blazor, which web browser(s) do you see this issue in? `NA`
  

### Regression?

Don't know at this time.

### PR DESCRIPTION
**Pull request by svick**
Fixes https://github.com/dotnet/runtime/issues/57238.

Also add test for `null` parameter default value, since that is another special case.

### CODE REVIEW

File: src/libraries/System.Reflection.MetadataLoadContext/tests/src/SampleMetadata/SampleMetadata.cs [hunk 1]
```diff
@@ -198,6 +198,8 @@ public class ParametersWithDefaultValues
         public void Foo4(short s = -34) { }
         public void Foo5(decimal d = 1234m) { }
         public void Foo6([DateTimeConstant(ticks: 8736726782)] DateTime dt) { }
+        public void Foo7(string s1 = "foo", string s2 = "") { }
```
Comment (buyaa-n) [inline src/libraries/System.Reflection.MetadataLoadContext/tests/src/SampleMetadata/SampleMetadata.cs:201]: NIT: maybe add a test case for null default?
```suggestion
        public void Foo7(string s1 = "foo", string s2 = "", string s3 = null) { }
```

**Review by buyaa-n — APPROVED** [review]
Left and NIT, overall LGTM, thanks!

File: src/libraries/System.Reflection.MetadataLoadContext/tests/src/SampleMetadata/SampleMetadata.cs (hunk 1 above)
Comment (svick) [reply src/libraries/System.Reflection.MetadataLoadContext/tests/src/SampleMetadata/SampleMetadata.cs]: Sure, done.

**Review by steveharter — APPROVED** [review]
