### PR TITLE
Fix concurrency issue in TypeDescriptor GetProperties() and GetConverter()

### LINKED ISSUE #30024: Concurrency issue in TypeDescriptor.GetConverter(type)
`TypeDescriptor.GetConverter(type)` returns different results when calling on multiple threads with the same type and this `type` has a custom `TypeDescriptionProvider`.

This issue is reproducible with target frameworks `netcoreapp2.2` and `net472` on window 10 x64.

## Repro
I'm calling the method on 10 threads and print the fetched type converter at the end.

### Expected output
All 10 calls return `MyTypeConverter`

### Actual output
The method return both `TypeConverter` and `MyTypeConverter` in random order like the following:

```
TypeConverter
TypeConverter
TypeConverter
MyTypeConverter
TypeConverter
TypeConverter
TypeConverter
TypeConverter
TypeConverter
TypeConverter
```

The good thing is that the method is returning `MyTypeConverter` after the concurrent calls are finished. The bad thing is that there are libs (like newtonsoft.json) that are caching the type descriptors. If the cache of 3rd party lib is initialized with wrong descriptor then the application is broken until restart.

### Program.cs
```
public class Program
{
   public static async Task Main()
   {
      var tasks = new Task<TypeConverter>[10];

      for (var i = 0; i < tasks.Length; i++)
      {
         tasks[i] = new Task<TypeConverter>(() => TypeDescriptor.GetConverter(typeof(MyClass)));
      }

      foreach (var t in tasks)
      {
         t.Start();
      }

      foreach (var conv in await Task.WhenAll(tasks))
      {
         Console.WriteLine(conv.GetType().Name);
      }
   }
}

[TypeDescriptionProvider(typeof(MyClassTypeDescriptionProvider))]
public class MyClass
{
}

public class MyClassTypeDescriptionProvider : TypeDescriptionProvider
{
   public override ICustomTypeDescriptor GetTypeDescriptor(Type objectType, object instance)
   {
      return new MyClassTypeDescriptor();
   }
}

public class MyClassTypeDescriptor : CustomTypeDescriptor
{
   public override TypeConverter GetConverter()
   {
      return new MyTypeConverter();
   }
}

public class MyTypeConverter : TypeConverter
{
}
```

### .csproj-file
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <OutputType>EXE</OutputType>
    </PropertyGroup>
</Project>
```

### LINKED ISSUE #92394: TypeDescriptor.GetProperties(object instance) is not thread-safe
### Description

If multiple threads call TypeDescriptor.GetProperties(object instance) at the same time, they can get different results if the instance has a TypeDescriptorProvider attribute.  I believe this is because of missing locks around reading the WeakHashTables.

### Reproduction Steps

```using System;
using System.ComponentModel;
using System.Threading;

namespace TypeDescriptionProvider_GetProperties_repro
{
	public class SomeTypeProvider : TypeDescriptionProvider
	{
		public static ThreadLocal<bool> Constructed = new ThreadLocal<bool>();
		public static ThreadLocal<bool> GetPropertiesCalled = new ThreadLocal<bool>();
		private class CTD : ICustomTypeDescriptor
		{
			public AttributeCollection GetAttributes() => AttributeCollection.Empty;
			public string? GetClassName() => null;
			public string? GetComponentName() => null;
			public TypeConverter GetConverter() => new TypeConverter();
			public EventDescriptor? GetDefaultEvent() => null;
			public PropertyDescriptor? GetDefaultProperty() => null;
			public object? GetEditor(Type editorBaseType) => null;
			public EventDescriptorCollection GetEvents() => EventDescriptorCollection.Empty;
			public EventDescriptorCollection GetEvents(Attribute[]? attributes) => EventDescriptorCollection.Empty;

			public PropertyDescriptorCollection GetProperties()
			{
				GetPropertiesCalled.Value = true;
				return PropertyDescriptorCollection.Empty;
			}

			public PropertyDescriptorCollection GetProperties(Attribute[]? attributes)
			{
				throw new NotImplementedException();
			}

			public object? GetPropertyOwner(PropertyDescriptor? pd) => null;
		}
		public override ICustomTypeDescriptor GetTypeDescriptor(Type objectType, object? instance)
		{
			Constructed.Value = true;
			return new CTD();
		}
	}

	[TypeDescriptionProvider(typeof(SomeTypeProvider))]
	public sealed class SomeType
	{
		public int SomeProperty { get; set; }
	}

	public static class Program
	{
		public static void ConcurrentTest(SomeType instance)
		{
			var properties = TypeDescriptor.GetProperties(instance);
			Console.WriteLine($"Constructed = {SomeTypeProvider.Constructed.Value} GetPropertiesCalled={SomeTypeProvider.GetPropertiesCalled.Value} properties.Count = {properties.Count} (should be 0)");
		}

		public static void Main()
		{
			const int threadCount = 10;
			// Uncomment and it will get the correct properties for all threads
			// TypeDescriptor.GetProperties(new SomeType());
			using (var finished = new CountdownEvent(threadCount))
			{
				SomeType[] instances = new SomeType[threadCount];
				for (var i = 0; i < threadCount; i++)
				{
					instances[i] = new SomeType();
				}
				for (var i = 0; i < threadCount; i++)
				{
					int _i = i;
					new Thread(() =>
					{
						ConcurrentTest(instances[_i]);
						finished.Signal();
					}).Start();
				}

				finished.Wait();
			}
		}
	}
}

### Expected behavior

Every thread should call the provider and get an empty list of properties.

### Actual behavior

Some threads will not call the provider and get the default properties based on reflection

### Regression?

Not that I know.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by steveharter**
Fixes #92394
Fixes #30024

Replaces (and is derived from the same branch as) PR https://github.com/dotnet/runtime/pull/92521 in order to apply the "sentinel" pattern so that we don't need a new Hashtable instance. Thanks [karakasa](https://github.com/karakasa) and [Maximys](https://github.com/Maximys) for your work on this.

### CODE REVIEW

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs [hunk 1]
```diff
@@ -271,33 +274,35 @@ private static void CheckDefaultProvider(Type type)
...
+                    Type? providerType = Type.GetType(pa.TypeName);
+                    if (providerType != null && typeof(TypeDescriptionProvider).IsAssignableFrom(providerType))
+                    {
+                        TypeDescriptionProvider prov = (TypeDescriptionProvider)Activator.CreateInstance(providerType)!;
+                        AddProvider(prov, type);
+                        providerAdded = true;
+                    }
                 }
+
+                s_defaultProviders[type] = s_initializedProvider;
```
Comment (ericstj) [inline src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:305]: I _think_ this needs to happen after the call to `CheckDefaultProvider(baseType);` and that needs to remain under the lock.  Otherwise another thread might exit out of this method before the default provider is added for the base type.

To test that you could try testing this with a race where the converter is not set on the target type, but it's base type.

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs [hunk 2]
```diff
@@ -271,33 +274,35 @@ private static void CheckDefaultProvider(Type type)
...
                 if (s_defaultProviders.ContainsKey(type))
                 {
+                    // Either another thread finished initializing for this type, or we are recursing on the same thread.
                     return;
                 }
 
-                // Immediately clear this. If we find a default provider
-                // and it starts messing around with type information,
+                // Immediately set this so we can short circuit in the ContainsKey check above.
+                // If we find a default provider and it starts messing around with type information,
```
Comment (ericstj) [inline src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:282]: I still don't understand this comment.  This is how I would word it.
```suggestion
                // Immediately set this to null to indicate we are in progress setting the default provider for a type.
                // This prevents re-entrance in this method.
```

**Review by ericstj — COMMENTED** [review]
This looks good, just one functional suggestion.

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs (hunk 2 above)
Comment (steveharter) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:282]: Thanks - added

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs [hunk 3]
```diff
@@ -28,7 +28,8 @@ public sealed class TypeDescriptor
         // class load anyway.
         private static readonly WeakHashtable s_providerTable = new WeakHashtable();     // mapping of type or object hash to a provider list
         private static readonly Hashtable s_providerTypeTable = new Hashtable();         // A direct mapping from type to provider.
-        private static readonly Hashtable s_defaultProviders = new Hashtable(); // A table of type -> default provider to track DefaultTypeDescriptionProviderAttributes.
+        private static readonly Hashtable s_defaultProviders = new Hashtable();          // A table of type -> default provider to track DefaultTypeDescriptionProviderAttributes.
```
[the remark this answers is not in the document]
Comment (steveharter) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:31]: Thanks - done

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs (hunk 1 above)
Comment (steveharter) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:305]: Agree - expanded the lock. Also for the base type check, split the method into 2 to prevent an unnecessary dictionary check and a recursive lock.

Comment (ericstj) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs]: Makes sense - that definitely makes this clearer

**Review by ericstj — APPROVED** [review]
This looks good to me.   For those tests - assume you saw them failing before the fix and confirmed the fix fixes them?

**Comment by steveharter** [comment]
> This looks good to me. For those tests - assume you saw them failing before the fix and confirmed the fix fixes them?

Yes, I reverted the changes from the previous PR and the 3 new tests failed. Then I added back the changes and the tests passed.

**Comment by cincuranet** [comment]
Regressions:
- https://github.com/dotnet/perf-autofiling-issues/issues/27477
