### PR TITLE
[NativeAOT] Fix resetting apartment state

### LINKED ISSUE #119925: NET10:  AOT => Failed to set the specified COM apartment state. Current apartment state 'MTA'.
### Description

Fail with simple GTK4 Test app compiled with AOT in NET10. 

In NET9 or via dotnet run with NET10 work fine.

Error creando Gtk.Application: System.InvalidOperationException: Failed to set the specified COM apartment state. Current apartment state 'MTA'.
   at System.Threading.Thread.SetApartmentStateUnchecked(ApartmentState, Boolean) + 0x15f
   at myProgram.Program.<Main>d__1.MoveNext() + 0xb9

### Reproduction Steps

Project.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>gtk4Test</AssemblyName>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GirCore.Gtk-4.0" Version="0.7.0-preview.2" />
    <PackageReference Include="GirCore.Gio-2.0" Version="0.7.0-preview.2" />
    <PackageReference Include="GirCore.GtkSource-5" Version="0.7.0-preview.2" />
    <PackageReference Include="GirCore.GObject-2.0.Integration" Version="0.7.0-preview.2" />
  </ItemGroup>
  
</Project>  
```

Program.cs
```
	[System.STAThread]
        public static void Main(string[] args)
        {
            var application = Gtk.Application.New("org.GirCore.GTK4TestApp", Gio.ApplicationFlags.FlagsNone);
	}
```

### Expected behavior

In NET9 work fine.

### Actual behavior

Error creando Gtk.Application: System.InvalidOperationException: Failed to set the specified COM apartment state. Current apartment state 'MTA'.
   at System.Threading.Thread.SetApartmentStateUnchecked(ApartmentState, Boolean) + 0x15f
   at myProgram.Program.<Main>d__1.MoveNext() + 0xb9

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #119925

This was latent bug in NativeAOT that got exposed by initializing COM eagerly on finalizer thread (https://github.com/dotnet/runtime/pull/113194).

### CODE REVIEW

File: src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs [hunk 1]
```diff
@@ -121,6 +127,26 @@ public static int Run()
...
 }
 
+internal static class ApartmentTests
+{
+    [Fact]
+    public static void ResetApartmentStatus()
+    {
+        Assert.Equal(ApartmentState.MTA, Thread.CurrentThread.GetApartmentState());
+
+        Thread.CurrentThread.SetApartmentState(ApartmentState.Unknown);
```
Comment (MichalPetryka) [inline src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs]: Isn't this supposed to always throw according to the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.setapartmentstate?view=net-9.0)?

image

Comment (jkotas) [reply src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs]: The docs are misleading.

Resetting Apartment state like this works in both .NET Framework and .NET Core. It is not the best practice - the best practice is to set the apartment state before the thread is started, but that's not a good enough reason to break it. 

NativeAOT had a latent bug here that got exposed by unrelated change.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs [hunk 2]
```diff
@@ -15,7 +15,7 @@ namespace System.Threading
     public sealed partial class Thread
     {
         [ThreadStatic]
-        private static ApartmentType t_apartmentType;
+        private static sbyte t_apartmentState; // ApartmentState shifted by ApartmentState.Unknonw to represent Unknown as the default value
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs]: Alternative is to keep ApartmentType and keeping mapping between ApartmentType and ApartmentState via switch expression.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs [hunk 3]
```diff
@@ -581,21 +587,13 @@ internal static ApartmentType GetCurrentApartmentType()
                     break;
 
                 default:
-                    Debug.Fail("bad return from CoGetApartmentType");
+                    Debug.Fail("bad return from CoGetApartmentState");
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs]:
```suggestion
                    Debug.Fail("bad return from CoGetApartmentType");
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs [hunk 4]
```diff
@@ -527,49 +529,53 @@ internal static void CheckForPendingInterrupt()
...
                         case Interop.APTTYPE.APTTYPE_NA:
                             switch (aptTypeQualifier)
                             {
                                 case Interop.APTTYPEQUALIFIER.APTTYPEQUALIFIER_NA_ON_MTA:
+                                    state = ApartmentState.MTA;
+                                    break;
+
                                 case Interop.APTTYPEQUALIFIER.APTTYPEQUALIFIER_NA_ON_IMPLICIT_MTA:
-                                    type = ApartmentType.MTA;
+                                    state = ApartmentState.Unknown;
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs:584]: This is the first part of the bug fix: Return Unknonwn from this method for implicit MTA

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs [hunk 5]
```diff
@@ -334,14 +334,15 @@ public ApartmentState GetApartmentState()
...
-                case ApartmentType.STA:
+                case ApartmentState.STA:
                     return ApartmentState.STA;
-                case ApartmentType.MTA:
+                case ApartmentState.MTA:
                     return ApartmentState.MTA;
                 default:
-                    return ApartmentState.Unknown;
+                    // If COM is uninitialized on the current thread, it is assumed to be implicit MTA.
+                    return ApartmentState.MTA;
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs:342]: This is the second part of the bug fix: Map `Unknown` to `MTA` in the public API to match regular CoreCLR behavior.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs [hunk 6]
```diff
@@ -527,49 +529,53 @@ internal static void CheckForPendingInterrupt()
         }
 
         internal static bool ReentrantWaitsEnabled =>
-            GetCurrentApartmentType() == ApartmentType.STA;
+            GetCurrentApartmentState() == ApartmentState.STA;
 
-        internal static ApartmentType GetCurrentApartmentType()
+        internal static ApartmentState GetCurrentApartmentState()
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs:546]:
```suggestion
        // Unlike the public API, this returns ApartmentState.Unknown when the COM is uninitialized on current thread
        internal static ApartmentState GetCurrentApartmentState()
```

File: src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs (hunk 1 above)
Comment (MichalPetryka) [reply src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs]: Should the docs be adjusted here then?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs [hunk 7]
```diff
@@ -15,7 +15,7 @@ namespace System.Threading
     public sealed partial class Thread
     {
         [ThreadStatic]
-        private static ApartmentType t_apartmentType;
+        private static sbyte t_apartmentState; // ApartmentState shifted by ApartmentState.Unknown to represent Unknown as the default value
```
Comment (MichalPetryka) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs]: Would it make sense to add an enum for this?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs [hunk 8]
```diff
@@ -527,49 +529,54 @@ internal static void CheckForPendingInterrupt()
         }
 
         internal static bool ReentrantWaitsEnabled =>
-            GetCurrentApartmentType() == ApartmentType.STA;
+            GetCurrentApartmentState() == ApartmentState.STA;
 
-        internal static ApartmentType GetCurrentApartmentType()
+        // Unlike the public API, this returns ApartmentState.Unknown when the COM is uninitialized on current thread
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs]:
```suggestion
        // Unlike the public API, this returns ApartmentState.Unknown when COM is uninitialized on the current thread
```

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs (hunk 7 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs]: The enum was removed in this PR. I agree it was momentarily confusing. I'm personally fine without it. The "shifting" statement helped to confirm the intent. It is also only every shifted in a simple method so not a big deal in my opinion.

File: src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs]: > Should the docs be adjusted here then?

Yes.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs (hunk 7 above)
Comment (jkotas) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs]: I have folded it into the existing ComState enum

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs (hunk 1 above)
Comment (jkotas) [reply src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs]: I do not think we want to be explaining the COM re-initialization compat quirk in the .NET official docs. It would need to be accompanied by an explanation of the narrow scenario where it may be ok to use. We would need to invent this explanation. It is hard to do well since Windows official docs do not mention the COM re-initialization compat quirk either: https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex .

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs [hunk 9]
```diff
@@ -374,14 +372,29 @@ private bool SetApartmentStateUnchecked(ApartmentState state, bool throwOnError)
...
+                    Debug.Assert((t_comState & ComState.MTA) != 0);
+                    retState = ApartmentState.MTA;
+                }
+            }
+
+            // Special case where we pass in Unknown and get back MTA.
+            //  Once we CoUninitialize the thread, the OS will still
+            //  report the thread as implicitly in the MTA if any
+            //  other thread in the process is CoInitialized.
+            if ((state == ApartmentState.Unknown) && (retState == ApartmentState.MTA))
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.Windows.cs:395]: Copy&paste from regular CoreCLR variant for better compat. (Ideally, we would de-dup the code eventually.)

File: src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs (hunk 1 above)
Comment (MichalPetryka) [reply src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs]: > It is hard to do well since Windows official docs do not mention the COM re-initialization compat quirk either: https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex .

Does this not mention it?

>Once COM has been uninitialized on a thread, you can reinitialize it in any mode, subject to the constraints above.

Comment (jkotas) [reply src/tests/nativeaot/SmokeTests/UnitTests/Threading.cs]: I do not think it is that simple. It does not mention what one needs to be careful when re-initializing the apartment of a thread. There is a lot of code out there that assumes that the thread apartment is immutable and caches the state. If the cached state gets out of sync, it leads to hard to diagnose bugs.
