### PR TITLE
JIT: fix OSR reporting for special stack slots

### LINKED ISSUE #43534: OSR Test Failures
Two different types of failures have cropped up in the experimental OSR test runs

See [test results](https://dev.azure.com/dnceng/public/_build/results?buildId=848538&view=ms.vss-test-web.build-test-results-tab).

1. Assertion failed `ppInfo->HasKeptAliveThis()`  in roslyn based tests
2. Assertion failed `pData->profiledRsp == (void*)ctx.Rsp` in profiler tests

category:correctness
theme:osr
skill-level:expert
cost:medium

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Revise the reporting of the special stack slots for OSR to be more uniform.
* Always record the original method FP-relative offset.
* Always apply the same adjustment for original method slosts i the OSR frame
* Handle caller-SP relative adjustment in `lvaToCallerSPRelativeOffset`

In particular, this fixes #43534 where we were reporting the wrong caller SP
for the profiler exit hook.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

OSR stress mode over pri1 passes locally.

File: src/coreclr/jit/gcencode.cpp [hunk 1]
```diff
@@ -3907,19 +3907,22 @@ void GCInfo::gcInfoBlockHdrSave(GcInfoEncoder* gcInfoEncoder, unsigned methodSiz
...
         {
-            PatchpointInfo* ppInfo = compiler->info.compPatchpointInfo;
-            offset                 = ppInfo->GenericContextArgOffset();
-            assert(offset != -1);
-        }
-        else
-        {
-            offset = compiler->lvaToCallerSPRelativeOffset(compiler->lvaCachedGenericContextArgOffset(),
-                                                           compiler->isFramePointerUsed());
+            // Sanity the offset vs saved patchpoint info.
```
Comment (BruceForstall) [inline src/coreclr/jit/gcencode.cpp:3916]: nit: Sanity the => Sanity check the

**Review by BruceForstall — APPROVED** [review]
