### PR TITLE
JIT: Fix GC info for fast tailcalls with contained targets

### LINKED ISSUE #122544: Test failure: CoreMangLib/system/delegate/VSD/OpenDelegate/OpenDelegate.cmd
**Failed in:** [runtime-coreclr gcstress-extra 20251214.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1231161)

**Failed tests:**
```
coreclr windows x64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.10.Amd64.Open
    - CoreMangLib/system/delegate/VSD/OpenDelegate/OpenDelegate.cmd
```

**Error message:**
```
Fatal error.
0xC0000005
   at System.RuntimeMethodHandle.InvokeMethod(System.Runtime.CompilerServices.ObjectHandleOnStack, Void**, System.Runtime.CompilerServices.ObjectHandleOnStack, BOOL, System.Runtime.CompilerServices.ObjectHandleOnStack)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(System.Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(System.Object, System.Span`1<System.Object>, System.Reflection.BindingFlags)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at Program.TestEntryPoint()
   at __GeneratedMainWrapper.Main()

Return code:      1
Raw output file:      C:hwA3B90973wA7B7097BuploadssystemdelegateVSDOpenDelegateoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwA3B90973pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  OpenDelegate.dll 
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 12/14/2025 10:43:54 PM
Processing C:corescorerun.exe.3780.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggersdcdb.exe -c "$<C:hwA3B90973		mpunjqon.tmp" -z "C:corescorerun.exe.3780.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.3780.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwA3B90973pPDB
Symbol search path is: C:hwA3B90973pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sun Dec 14 22:44:00.000 2025 (UTC + 0:00)
System Uptime: 0 days 0:04:54.360
Process Uptime: 0 days 0:00:06.000
.............................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(ec4.a3c): Access violation - code c0000005 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
KERNELBASE!RaiseFailFastException+0xae:
00007ffa`ed90a0be 803d7d6e120000  cmp     byte ptr [KERNELBASE!local_unwind+0x7452 (00007ffa`eda30f42)],0 ds:00007ffa`eda30f42=00
0:000> cdb: Reading initial command '$<C:hwA3B90973		mpunjqon.tmp'
0:000> .cordll -lp "C:hwA3B90973p"
The call to LoadLibrary(sos) failed, Win32 error 0n2
    "The system cannot find the file specified."
Please check your debugger configuration and/or network access.
CLR DLL status: Loaded DLL C:hwA3B90973pmscordaccore.dll
0:000> .load C:Users
unner.dotnetsossos.dll
0:000> ~*k

.  0  Id: ec4.a3c Suspend: 0 Teb: 000000b7`49feb000 Unfrozen
Child-SP          RetAddr           Call Site
000000b7`4a17a370 00007ffa`cafabcd9 KERNELBASE!RaiseFailFastException+0xae
000000b7`4a17a940 00007ffa`cb24972e coreclr!WatsonLastChance+0x3e9
000000b7`4a17aae0 00007ffa`cb2483de coreclr!EEPolicy::LogFatalError+0x9be
00
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/arcade/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor31|0_32(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
For fast tailcalls we consume the operands as part of generating the `GT_CALL` node, yet we do not actually use values in the registers until after generating the epilog.

This is incompatible with assumptions made by the code that implements the consumption side of operands. That code assumes that the registers will be used immediately and kills any GC information/local information immediately.

Normally this is not a problem. We end up with a wrong GC information view in codegen, but since the emitter uses a lazy approach to register GC information, we don't end up actually reporting the wrong GC information. However, we can see a problem because of various constructs where the emitter ends up synchronizing its GC information view with the view that codegen had -- for example if a label with GC information was created. That started happening recently with #107283 when we started allowing tailcalls out of methods with GS cookie checks.

Fix the situation by remarking the base/index of contained indirections as containing GC pointers if necessary. There is already corresponding logic for arguments that does the same remarking.

The fix is only needed on x64/x86 since other platforms do not support contained indirections in calls and hence the target will not usually contain any GC pointers.

Fix #122544

### CODE REVIEW

File: src/coreclr/jit/codegenxarch.cpp [hunk 1]
```diff
@@ -6052,6 +6052,21 @@ void CodeGen::genCall(GenTreeCall* call)
...
+                GenTreeIndir* indir = target->AsIndir();
+                if (indir->HasBase() && indir->Base()->TypeIs(TYP_BYREF, TYP_REF))
+                {
+                    gcInfo.gcMarkRegPtrVal(indir->Base()->GetRegNum(), indir->Base()->TypeGet());
+                }
+
+                if (indir->HasIndex() && indir->Index()->TypeIs(TYP_BYREF, TYP_REF))
+                {
+                    gcInfo.gcMarkRegPtrVal(indir->Index()->GetRegNum(), indir->Index()->TypeGet());
+                }
```
Comment (EgorBo) [inline src/coreclr/jit/codegenxarch.cpp:6069]: can Base or Index be contained, hence no GetRegNum here?

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/codegenxarch.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/codegenxarch.cpp:6069]: I don't _think_ so. At least the codegen for the target address of the `GT_CALL` does not have any special handling for contained base/index:
https://github.com/dotnet/runtime/blob/dd0661f087803f895f8bdab47bd804386ba5cfd1/src/coreclr/jit/codegenxarch.cpp#L6243-L6257
