### PR TITLE
Ensure that we aren't accidentally generating instructions for unsupported ISAs

### LINKED ISSUE #60154: Test failure: JIT/HardwareIntrinsics/General/Vector256/Vector256_ro/Vector256_ro.sh Timed Out
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20211003.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1400353&view=ms.vss-test-web.build-test-results-tab&runId=40669192&paneView=debug&resultId=111142)
Failed test;
```
CoreCLR Linux arm64 Checked gcstress0x3 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/HardwareIntrinsics/General/Vector256/Vector256_ro/Vector256_ro.sh

CoreCLR Linux x64 Checked gcstress0x3 @ Ubuntu.1804.Amd64.Open

- readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh
- JIT/HardwareIntrinsics/General/Vector128/Vector128_ro/Vector128_ro.sh
- JIT/HardwareIntrinsics/*

CoreCLR OSX arm64 Checked gcstress0x3 @ OSX.1100.ARM64.Open

- JIT/HardwareIntrinsics/General/Vector256/Vector256_ro/Vector256_ro.sh
- JIT/HardwareIntrinsics/General/Vector128/Vector128_ro/Vector128_ro.sh

CoreCLR Linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/HardwareIntrinsics/General/Vector64/Vector64_ro/Vector64_ro.sh
- JIT/HardwareIntrinsics/General/Vector256/Vector256_ro/Vector256_ro.sh
- JIT/HardwareIntrinsics/General/Vector128/Vector128_ro/Vector128_ro.sh

CoreCLR windows arm64 Checked gcstress0x3 @ Windows.10.Arm64v8.Open

- JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd

CoreCLR Linux arm Checked gcstress0xc @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/HardwareIntrinsics/General/Vector128/Vector128_r/Vector128_r.sh
- JIT/HardwareIntrinsics/General/Vector256/Vector256_r/Vector256_r.sh
```
**One of error message:**
```
cmdLine:/root/helix/work/workitem/e/JIT/HardwareIntrinsics/General/Vector256/Vector256_ro/Vector256_ro.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 10/3/2021 2:59:49 PM, end: 10/3/2021 3:59:49 PM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/General/Vector256/Vector256_ro/Vector256_ro.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Vector256_ro.dll ''
Beginning test case Abs.Byte at 10/3/2021 2:59:53 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 10/3/2021 3:00:15 PM
Beginning test case Abs.Double at 10/3/2021 3:00:15 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 10/3/2021 3:00:23 PM
Beginning test case Abs.Int16 at 10/3/2021 3:00:23 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 10/3/2021 3:00:27 PM
Beginning test case Abs.Int32 at 10/3/2021 3:00:27 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 10/3/2021 3:00:33 PM
Beginning test case Abs.Int64 at 10/3/2021 3:00:33 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 10/3/2021 3:00:39 PM
Beginning test case Abs.SByte at 10/3/2021 3:00:39 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 10/3/2021 3:00:44 PM
Beginning test case Abs.Single at 10/3/2021 3:00:44 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenar


Stack trace
   at JIT_HardwareIntrinsics._General_Vector256_Vector256_ro_Vector256_ro_._General_Vector256_Vector256_ro_Vector256_ro_sh()
```

|Build|Kind|Start Time|
|---|---|---|
[1582767](https://dev.azure.com/dnceng/public/_build/results?buildId=1582767)|Rolling|2022-31-01|
[1583845](https://dev.azure.com/dnceng/public/_build/results?buildId=1583845)|Rolling|2022-01-02|
[1585006](https://dev.azure.com/dnceng/public/_build/results?buildId=1585006)|Rolling|2022-01-02|
[1589146](https://dev.azure.com/dnceng/public/_build/results?buildId=1589146)|Rolling|2022-03-02|

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/60154

-- NOTE: The first commit here is intentionally just adding an assert to ensure that it surfaces the area on the failing CI machines

### CODE REVIEW

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 1]
```diff
@@ -86,6 +86,9 @@ void CodeGen::genHWIntrinsic(GenTreeHWIntrinsic* node)
     HWIntrinsicCategory    category    = HWIntrinsicInfo::lookupCategory(intrinsicId);
     size_t                 numArgs     = node->GetOperandCount();
 
+    // We need to validate that other phases of the compiler haven't introduced unsupported intrinsics
+    assert(compiler->compIsaSupportedDebugOnly(isa));
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:90]: This shows the assert triggering on the original bug: https://dev.azure.com/dnceng/public/_build/results?buildId=1566647&view=ms.vss-test-web.build-test-results-tab&runId=44059054&resultId=102987&paneView=debug

It's not "perfect" and its still possible for something else in the JIT to incorrectly generate an AVX2 instruction; but this should catch the bulk of them, particularly since most intrinsic usages are now driven through the HWIntrinsic nodes so that optimizations and other transforms are consistently applied.

File: src/coreclr/jit/hwintrinsicxarch.cpp [hunk 2]
```diff
@@ -1024,7 +1024,7 @@ GenTree* Compiler::impBaseIntrinsic(NamedIntrinsic        intrinsic,
         {
             assert(sig->numArgs == 2);
 
-            if ((simdSize != 32) || varTypeIsFloating(simdBaseType) || compExactlyDependsOn(InstructionSet_AVX2))
+            if ((simdSize != 32) || compExactlyDependsOn(InstructionSet_AVX2))
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsicxarch.cpp:1027]: I was originally going to handle this differently but this likely needs to be backported to .NET 7 P1 and so I kept it "minimal".

File: src/coreclr/jit/lowerxarch.cpp [hunk 3]
```diff
@@ -3429,7 +3429,7 @@ void Lowering::LowerHWIntrinsicDot(GenTreeHWIntrinsic* node)
                     //   e6, e7, e4, e5 | e2, e3, e0, e1
                     //   e7, e6, e5, e4 | e3, e2, e1, e0
 
-                    shuffleConst = 0x4D;
+                    shuffleConst = 0x4E;
```
Comment (Wraith2) [inline src/coreclr/jit/lowerxarch.cpp:3432]: Was this just wrong before?

File: src/coreclr/jit/gentree.cpp [hunk 4]
```diff
@@ -19323,6 +19325,12 @@ GenTree* Compiler::gtNewSimdCmpOpAllNode(genTreeOps  op,
 
             if (simdSize == 32)
             {
+                // TODO-XArch-CQ: It's a non-trivial amount of work to support these
+                // for floating-point while only utilizing AVX. It would require, among
+                // other things, inverting the comparison and potentially support for a
+                // new Avx.TestNotZ intrinsic to ensure the codegen remains efficient.
+                assert(compIsaSupportedDebugOnly(InstructionSet_AVX2));
+
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:19333]: Just noting that this is worth doing even if we decided to only accelerate on AVX2+. Using `CompareNotGreaterThan` allows us to use `PTEST`, which in turn is more efficient and allows the code to directly branch rather than requiring a `MoveMask` instruction.

File: src/coreclr/jit/lowerxarch.cpp (hunk 3 above)
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:3432]: I ran tests on all ISAs from SSE2-AVX2 to ensure no other "disabled" instructions were being generated and it flagged this as a failing test (`4D` meant it was selecting `1, 3, 0, 1`. `4E` means it will pick `2, 3, 0, 1`)

Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp:3432]: Yes, see https://github.com/dotnet/runtime/pull/64140#discussion_r790132513

Comment (Wraith2) [reply src/coreclr/jit/lowerxarch.cpp:3432]: I was too fast then, should have checked the timestamps on the comments.

**Comment by tannergooding** [comment]
CC. @jkotas; @jeffhandley

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp [hunk 5]
```diff
@@ -206,6 +206,10 @@ void CodeGen::genHWIntrinsic(GenTreeHWIntrinsic* node)
 {
     const HWIntrinsic intrin(node);
 
+    // We need to validate that other phases of the compiler haven't introduced unsupported intrinsics
+    CORINFO_InstructionSet isa = HWIntrinsicInfo::lookupIsa(intrin.id);
+    assert(compiler->compIsaSupportedDebugOnly(isa));
```
Comment (jkotas) [inline src/coreclr/jit/hwintrinsiccodegenarm64.cpp:211]:
```suggestion
    assert(compiler->compIsaSupportedDebugOnly(HWIntrinsicInfo::lookupIsa(intrin.id)));
```
to avoid unusual code in release. (C++ compiler may optimize it out, but one never knows.)

**Comment by tannergooding** [comment]
x86 failure looks unrelated. Appears to be an issue with extracting a zip file for the Libraries x86 Debug tests

**Comment by tannergooding** [comment]
> x86 failure looks unrelated.

Given its the weekend and this likely won't get reviewed until Monday, going to requeue all jobs and see if that resolves the artifacts issue (just requeuing the single job tries to pull down the same problematic artifact)

**Comment by tannergooding** [comment]
CC. @echesakovMSFT, @dotnet/jit-contrib 

A quick-review would be appreciated; this fixing a sporadic CI failure showing up on the small pool of OSX machines that have AVX but not AVX2

File: src/coreclr/jit/hwintrinsicxarch.cpp [hunk 6]
```diff
@@ -1287,7 +1287,7 @@ GenTree* Compiler::impBaseIntrinsic(NamedIntrinsic        intrinsic,
...
```
Comment (echesakovMSFT) [inline src/coreclr/jit/hwintrinsicxarch.cpp:1290]: I wonder if it's worth having such ISA requirements done in a declarative way and checking that before the `switch`? (Obviously, as a follow-up exercise).

**Review by echesakov — APPROVED** [review]
LGTM

File: src/coreclr/jit/hwintrinsicxarch.cpp (hunk 6 above)
Comment (tannergooding) [reply src/coreclr/jit/hwintrinsicxarch.cpp:1290]: I've considered the same. Part of the issue is the number of variations/considerations that might come into play here and things being missed in refactorings or changes.

It'd be great if we had a way to easily unit test these and validate when something is treated as intrinsic vs not. There was a functioning (but hacky) solution done for Vector<T> that was never done for the hardware intrinsics; but we're also already hitting various timing issues.

It might work better if many of the HWIntrinsic tests were ported to be library tests instead and we limited the runtime side to super simple validation of things like "was it jitted or treated as an intrinsic"...

Comment (jkotas) [reply src/coreclr/jit/hwintrinsicxarch.cpp:1290]: > It might work better if many of the HWIntrinsic tests were ported to be library tests 

What are the library tests doing differently that would make it work better?

Comment (tannergooding) [reply src/coreclr/jit/hwintrinsicxarch.cpp:1290]: > What are the library tests doing differently that would make it work better?

For starters, they don't run under GCStress today. But on top of that, the managed testing frameworks already handle things like parallelizing the test runs; tracking each scenario individually when considering timeouts, etc.

xUnit (as do others like MSTest and NUnit) already handles a large number of these scenarios/considerations and so we'd be able to still provide the desired coverage while limiting what gets stress tested for the runtime to just the scenarios we believe are "most impactful".

Comment (tannergooding) [reply src/coreclr/jit/hwintrinsicxarch.cpp:1290]: So, I imagine moving most of the logic to the libraries side may actually speed up the inner loop test time, make it easier to debug/validate certain changes, and fix the GCStress timeouts.

We'd still have to keep some scenarios to ensure that we do get stress test coverage; but we may be able to limit that to a single scenario per intrinsic rather than 10-12 scenarios per intrinsic.

Comment (jkotas) [reply src/coreclr/jit/hwintrinsicxarch.cpp:1290]: > For starters, they don't run under GCStress today

That is a bug, not a feature. I would love to have a capability to run GCStress on anything. One the problems with GCStress and libraries tests is reflection-based xunit runner that is too heavy for GCStress.

> managed testing frameworks already handle things like parallelizing the test runs; tracking each scenario individually when considering timeouts, etc.

We are moving the runtime tests to the same xunit authoring as libraries tests (except that the runner is going to be source generated). I hope we are going to have similar flexibility in the runtime tests once that is all done.

Comment (BruceForstall) [reply src/coreclr/jit/hwintrinsicxarch.cpp:1290]: > That is a bug, not a feature. I would love to have a capability to run GCStress on anything. One of the problems with GCStress and libraries tests is reflection-based xunit runner that is too heavy for GCStress.

fwiw, I created (a long time ago) GCStress pipelines for libraries tests: https://dev.azure.com/dnceng/public/_build?definitionId=839, https://dev.azure.com/dnceng/public/_build?definitionId=840, but never enabled them because there are too many timeouts and other GCStress-related issues that need to be cleaned up before they wouldn't be too noisy.
