### PR TITLE
JIT: optimize redundant branches by looking through phis

### LINKED ISSUE #75987: JIT does not eliminate null check for "o ??= new()"
### Description

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunHjykTFAwCy5ABQRgAKxhgMDCAEoOXHuoCWAMwbjJDAPwGAvAwB2MAO6KZcjOKUqNucwFcANu5UYAFlAjWFtYAoghgMAAOGBoQZg4A3GrcAL5JDGn0TAJCoqSStvKKKpzU6po6ehAMpkE2svIOTi5mHl4Mvv6BVgyh4VExcUqJpTypI9wZfNnEwiJ04hpmChrFaeW6GgwAPAwADE7Ve8NlPNob23vefgHm3b2R0bEJaWPqk1mCM6Io+fUKyqpxgwxskgA=
```C#
static void M1(object o) {
    if ((o ??= new object()) is null) throw new Exception();
}
    
static void M2(object o) {
    if ((o = new object()) is null) throw new Exception();
}

static void M3(int i) {
    if (i < 0) i = 0;
    if (i < 0) throw new Exception();
}
    
static void M4(object o) {
}
```

While the JIT can optimize `M2`(almost, but still curiously worse than `M4`) and `M3` to a nop, it cannot optimize `M1` similarly.

Found while discussing #75936.

### Configuration

sharplab says "Core CLR 6.0.822.36306 on amd64".

I also tried 7.0.100-rc.1.22431.12 on amd64. The codegen for `M1` was not really better.

### Regression?

Probably not.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
In some cases the value of a block's branch predicate is correlated with the predecessor of the block. Often this correlation is hinted at by the presence of phis in the predicate's tree and/or phi VNs in in the predicate's VN graph.

For each predecessor of a block, we evaluate the predicate value number using the values brought to the block by that predecessor. If we find correlations, we use them to drive the existing jump threading optimization.

Also, if we end up partially disambiguating such that there is just one remaining predecessor, update the value number of the predicate to reflect the values that flow in from that predecessor.

Fixes #75987.
Contributes to #48115.

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=34219&view=ms.vss-build-web.run-extensions-tab)

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib 

Expecting a fairly large number of diffs. Looked at some of the bigger regressions and they seem to be changes in LSRA.

**Comment by EgorBo** [comment]
Are failures related?

**Comment by AndyAyersMS** [comment]
> Are failures related? Diffs are nice indeed 🚀

I think so. Debugging now.

**Comment by AndyAyersMS** [comment]
> > Are failures related? Diffs are nice indeed 🚀
> 
> I think so. Debugging now.

Fix that but looks like it has uncovered other problems.

**Comment by AndyAyersMS** [comment]
> > > Are failures related? Diffs are nice indeed 🚀
> > 
> > 
> > I think so. Debugging now.
> 
> Fixed that but looks like it has uncovered other problems.

Oops, the fix was wrong, `PhiDef` VNs have some unusual argument encodings.

**Comment by AndyAyersMS** [comment]
> > > > Are failures related? Diffs are nice indeed 🚀
> > > 
> > > 
> > > I think so. Debugging now.
> > 
> > 
> > Fixed that but looks like it has uncovered other problems.
> 
> Oops, the fix was wrong, `PhiDef` VNs have some unusual argument encodings.

The issue was that both relop operands had PhiDef VNs for V04, but only one of them matched the local PHI; the other came from a "nonlocal" PHI (via a copy to another local). So when scanning for the right local PHI we need to match both the local num and the SSA def num we get from the PhiDef VN.

**Comment by AndyAyersMS** [comment]
The condition for the bug is (seemingly) pretty rare, so I don't expect it to perturb the diffs much.

Code for `M1` in #75987 is now identical to `M2`...  in both cases we needlessly build frames as we don't realize we have eliminated all the calls.

```asm
; Assembly listing for method X:M1(System.Object)
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; No PGO data
; 0 inlinees with PGO data; 1 single block inlinees; 0 inlinees without PGO data
; Final local variable assignments
;
;* V00 arg0         [V00,T00] (  0,  0   )     ref  ->  zero-ref    class-hnd
;  V01 OutArgs      [V01    ] (  1,  1   )  lclBlk (32) [rsp+00H]   "OutgoingArgSpace"
;* V02 tmp1         [V02,T01] (  0,  0   )     ref  ->  zero-ref   
;* V03 tmp2         [V03    ] (  0,  0   )     ref  ->  zero-ref    class-hnd exact single-def "NewObj constructor temp"
;* V04 tmp3         [V04,T02] (  0,  0   )     ref  ->  zero-ref    class-hnd exact single-def "NewObj constructor temp"
;
; Lcl frame size = 40

G_M9243_IG01:              ;; offset=0000H
       4883EC28             sub      rsp, 40
						;; size=4 bbWeight=1    PerfScore 0.25
G_M9243_IG02:              ;; offset=0004H
       4883C428             add      rsp, 40
       C3                   ret      
						;; size=5 bbWeight=1    PerfScore 1.25
```
Getting to this point required all of the tricks here and in #76207, in particular the fall through pred conversion / VN update / retry if block is still BBJ_COND. As seen below....
```
--- Trying RBO in BB03 ---
Relop [000011] BB03 value unknown, trying inference
... JT-PHI [interestingVN] in BB03 relop first operand VN is PhiDef for V02
N003 (  5,  4) [000011] J------N---                         *  NE        int    $101
N001 (  3,  2) [000009] -----------                         +--*  LCL_VAR   ref    V02 tmp1         u:2 (last use) $1c0
N002 (  1,  1) [000010] -----------                         \--*  CNS_INT   ref    null $VN.Null
... substituting ($80,$0) for ($1c0,$0) in $101 gives $100
BB01 is an ambiguous pred
... substituting ($180,$0) for ($1c0,$0) in $101 gives $42
... substituted VN implies relop is 1 when coming from pred BB02
BB02 is a true pred
BB02 is the fall-through pred
BB03 has ambiguous preds and a (true) fall through pred and no (false) preds.
Converting fall through pred BB02 to BBJ_ALWAYS
Optimizing via jump threading
Jump flow from pred BB02 -> BB03 implies predicate true; we can safely redirect flow to be BB02 -> BB05
Setting edge weights for BB02 -> BB05 to [0 .. 3.402823e+38]
BB03 has just one remaining predecessor BB01
Updating [000011] liberal VN from $101 to $100
Will retry RBO in BB03 after partial optimization

--- Trying RBO in BB03 ---
Relop [000011] BB03 value unknown, trying inference

Dominator BB01 of BB03 has relop with same liberal VN
N003 (  3,  3) [000003] J------N---                         *  NE        int    $100
N001 (  1,  1) [000001] -----------                         +--*  LCL_VAR   ref    V02 tmp1         u:1 (last use) $80
N002 (  1,  1) [000002] -----------                         \--*  CNS_INT   ref    null $VN.Null
 Redundant compare; current relop:
N003 (  5,  4) [000011] J------N---                         *  NE        int    <l:$100, c:$101>
N001 (  3,  2) [000009] -----------                         +--*  LCL_VAR   ref    V02 tmp1         u:2 (last use) $1c0
N002 (  1,  1) [000010] -----------                         \--*  CNS_INT   ref    null $VN.Null
Jump successor BB03 of BB01 reaches, relop [000011] must be true

Redundant branch opt in BB03:

removing useless STMT00002 ( ??? ... 0x00D )
N004 (  7,  6) [000012] -----------                         *  JTRUE     void   $VN.Void
N003 (  5,  4) [000011] -----------                         \--*  CNS_INT   int    1
 from BB03

Conditional folded at BB03
BB03 becomes a BBJ_ALWAYS to BB05
Compiler::optRedundantBranch removed tree:
N004 (  7,  6) [000012] -----------                         *  JTRUE     void   $VN.Void
N003 (  5,  4) [000011] -----------                         \--*  CNS_INT   int    1
```

**Comment by EgorBo** [comment]
@AndyAyersMS btw, does it improve codegen for this:
```csharp
static bool Test(object obj) => obj is int;
```
In current Main seems to be emitting:
```asm
; Method Proga:Test(System.Object):bool
G_M55190_IG01:        ; gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref, nogc <-- Prolog IG
						;; size=0 bbWeight=1    PerfScore 0.00

G_M55190_IG02:        ; gcrefRegs=00000002 {rcx}, byrefRegs=00000000 {}, byref, isz
                            ; gcrRegs +[rcx]
       4885C9               test     rcx, rcx
       7411                 je       SHORT G_M55190_IG05
						;; size=5 bbWeight=1    PerfScore 1.25

G_M55190_IG03:        ; gcrefRegs=00000002 {rcx}, byrefRegs=00000000 {}, byref, isz
       48B8E0B89E64FE7F0000 mov      rax, 0x7FFE649EB8E0      ; System.Int32
       483901               cmp      qword ptr [rcx], rax
       7402                 je       SHORT G_M55190_IG05
						;; size=15 bbWeight=0.25 PerfScore 1.06

G_M55190_IG04:        ; gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref
                            ; gcrRegs -[rcx]
       33C9                 xor      rcx, rcx
                            ; gcrRegs +[rcx]
						;; size=2 bbWeight=0.12 PerfScore 0.03

G_M55190_IG05:        ; gcrefRegs=00000002 {rcx}, byrefRegs=00000000 {}, byref
       33C0                 xor      eax, eax
       4885C9               test     rcx, rcx
       0F95C0               setne    al
						;; size=8 bbWeight=1    PerfScore 1.50

G_M55190_IG06:        ; , epilog, nogc, extend
       C3                   ret      
						;; size=1 bbWeight=1    PerfScore 1.00
; Total bytes of code: 31


```

**Comment by EgorBo** [comment]
If it does it might fix some of these:
https://github.com/dotnet/runtime/issues/36649
https://github.com/dotnet/runtime/issues/47920
https://github.com/dotnet/runtime/issues/55841

**Comment by AndyAyersMS** [comment]
> @AndyAyersMS btw, does it improve codegen for this:

No, that is the "side effect" case which we still can't handle.

**Comment by AndyAyersMS** [comment]
> > @AndyAyersMS btw, does it improve codegen for this:
> 
> No, that is the "side effect" case which we still can't handle.

You might recall handling this requires some code duplication and probably an SSA update. Likely the next thing to try and fix.

**Comment by EgorBo** [comment]
@AndyAyersMS Ah I see. By the way, when we have a PHI node and one of the preds is another PHI - does this PR handle that or give up?

**Comment by AndyAyersMS** [comment]
> @AndyAyersMS Ah I see. By the way, when we have a PHI node and one of the preds is another PHI - does this PR handle that or give up?

We give up since both those values arrive via the same pred edge. That is, given something like `(GT (PHI (PHI(a, b), c)), 0)` the chances that both `a` and `b` lead to the same overall VN when substituted seems small. Also, you have to start worrying about cycles in the SSA graph.

**Comment by AndyAyersMS** [comment]
@egorbo the bug is fixed.

**Review by EgorBo — APPROVED** [review]
Glad that the diffs remain 🙂

File: src/coreclr/jit/redundantbranchopts.cpp [hunk 1]
```diff
@@ -1079,6 +1088,259 @@ bool Compiler::optJumpThread(BasicBlock* const block, BasicBlock* const domBlock
...
+            {
+                GenTreePhiArg* const phiArgNode = use.GetNode()->AsPhiArg();
+                assert(phiArgNode->GetLclNum() == funcArgToPhiLocalMap[i]);
+
+                if (phiArgNode->gtPredBB == predBlock)
+                {
+                    ValueNum phiArgVN = phiArgNode->GetVN(VNK_Liberal);
+
+                    // We sometimes see cases where phi args do not have VNs.
+                    // (I recall seeing this before... track down why)
```
Comment (SingleAccretion) [inline src/coreclr/jit/redundantbranchopts.cpp:1229]: > `track down why`

It's because we don't number `PHI_ARG`s which depend on a cycle (i. e. represent defs from blocks we haven't numbered yet).
