### PR TITLE
Fix GC heap dump

### LINKED ISSUE #38639: dotnet-gcdump and perfview's gcdump do not work on 5.0 runtimes
If you collect a gc dump with either dotnet-gcump or perfview's gcdump command from a live process you will see output like this:

```
Name
UNKNOWN 0x7ffabf7e46a0
UNKNOWN 0x7ffabf811688 (Bytes > 10K)
UNKNOWN 0x7ffabf7a7a48 (Bytes > 10K)
UNKNOWN 0x7ffabf7ecb50
UNKNOWN 0x7ffabf6e6768 (Bytes > 1K)
[static vars]
UNKNOWN 0x7ffabf7ecbe0 (Bytes > 1K)
UNKNOWN 0x7ffabf7e46a0 (Bytes > 1K)
[strong Handles]
UNKNOWN 0x7ffabf7a2990 (Bytes > 1K)
UNKNOWN 0x7ffabf7a7a48
UNKNOWN 0x7ffabf806c20
UNKNOWN 0x7ffabf6e6768
UNKNOWN 0x7ffabf814298
UNKNOWN 0x7ffabf7b1c80
UNKNOWN 0x7ffabf7a2990
UNKNOWN 0x7ffabf7aeb78
UNKNOWN 0x7ffabf812218
[local vars]
UNKNOWN 0x7ffabf814cb0
UNKNOWN 0x7ffabf7c0d28
[pinning Handles]
[static var Type(0x7ffabf814cb0).s_in]
[static var Type(0x7ffabf812218).s_out]
[static var Type(0x7ffabf7a2990).s_table]
[other roots]
[.NET Roots]
[static var Type(0x7ffabf7aeb78).s_dataStore]
ROOT
```

It works on 3.1 but fails on 5.0 runtimes. Since both tools are failing I suspect it is a runtime issue where we're not emitting the right events.

### PR DESCRIPTION
**Pull request by davmason**
#36932 had a typo that caused types to never be logged

Fixes #38639

### CODE REVIEW

**Review by sdmaclea — APPROVED** [review]

**Review by sywhang — APPROVED** [review]

**Comment by davmason** [comment]
@noahfalk @sywhang If I wanted to add a test to make sure we get at least some types from the bulk type event, is the right place for it the runtime or diagnostics repo?

**Review by josalem — APPROVED** [review]

**Review by mikem8361 — APPROVED** [review]

**Comment by sywhang** [comment]
@davmason Thanks for fixing this.. I think the right place would be the runtime repo.

**Review by noahfalk — APPROVED** [review]

File: src/coreclr/tests/src/tracing/eventpipe/gcdump/gcdump.cs [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+            };
+
+            source.Clr.GCBulkRootStaticVar += (GCBulkRootStaticVarTraceData data) =>
+            {
+                _bulkRootStaticVarCount += data.Count;
+            };
+
+            return () => 
+            {
+                // 50 is a safe number, comfortably less than the events we expect.
```
Comment (josalem) [inline src/coreclr/tests/src/tracing/eventpipe/gcdump/gcdump.cs:84]: Could you put in the comment how many we "expect"?  It will make diagnosing test failures easier later on.

Comment (davmason) [reply src/coreclr/tests/src/tracing/eventpipe/gcdump/gcdump.cs:84]: I was thinking when I chose 50 that I basically want to verify that there is more than 1, but I don't really want to be in the business of tracking how many there should be. I expect that number to change over time since most of the types will be in framework code. As people add and remove types the numbers could change a lot over time.

How are you envisioning knowing the amount of types would help with debugging?

Comment (josalem) [reply src/coreclr/tests/src/tracing/eventpipe/gcdump/gcdump.cs:84]: I was envisioning situations where we get "some" events but less than 50.  If we really only care that we get _any_ I was thinking we should have the test just check for `>1`, but I think this is probably fine as is.

Comment (davmason) [reply src/coreclr/tests/src/tracing/eventpipe/gcdump/gcdump.cs:84]: I would like to be as close to accurate as possible but also not have to deal with what happens when it changes a little bit. Maybe 50 is too low. I was originally thinking I wanted to avoid the scenario where there is some small number of hardcoded types and we miss the dynamic ones.

I was already waffling about whether to just go with 1 or try to make it close to the real values before your feedback.

These are the current values
```
_bulkTypeCount =          153
_bulkNodeCount =          724
_bulkEdgeCount =          1066
_bulkRootEdgeCount =      321
_bulkRootStaticVarCount = 92
```

Instead I'll change it to be ~80% of those numbers and add a comment that if it becomes and sort of maintenance burden just change the values to 1

Comment (davmason) [reply src/coreclr/tests/src/tracing/eventpipe/gcdump/gcdump.cs:85]: Nevermind, it already was causing failures so I switched it back

**Comment by echesakovMSFT** [comment]
@davmason I noticed that test in this PR was merged under src/coreclr/tests/src while after #38058 all the tests should be under src/tests. Can you move it to right location?

**Comment by davmason** [comment]
@echesakovMSFT there's already a PR open #39057
