### PR TITLE
Disable Int128 use in by value ABI scenarios, and fix field layout behavior

### LINKED ISSUE #72206: `[U]Int128` alignment handling is in the wrong place
There is code here:

https://github.com/dotnet/runtime/blob/cb57fbb00a8ca39df359c0e7bdf600b72abea09f/src/coreclr/vm/methodtablebuilder.cpp#L9909-L9923

Which is intended to handle the special alignment requirement of the type on Unix x64/ARM64.

However, this code is currently dead because it is in an `if` block under `bmtGenerics->HasInstantiation()` (i. e. the `if` only handles generic types).

@tannergooding

### PR DESCRIPTION
**Pull request by davidwrighton**
Unfortunately, attempting to actually fix all the ABI issues is probably too complex for this time in the release cycle.

- Mark `Int128` as being ABI unstable in Crossgen2. This will prevent it from appearing in function signatures
- Adjust layout so that crossgen2 and the runtime agree about layout
  - Arm32 - Alignment of 8 bytes
  - Everywhere else - Alignment of 16 bytes
- Disable use of `Int128` in pinvokes as a by value parameter or return value. (Match behavior of `Vector128<T>`) (Unlike Vector128<T> handle scenarios such as having fields of `Int128` types.)
- Disable tests that will fail now that pinvokes are disabled
- Build a test that will succeed now that pinvokes are disabled
- Add test that alignment matches OS behavior
- Add unit tests for alignment behavior
- Update R2R version

Fixes #72206

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
If you explicitly mark `Int128` as non-blittable, you can then block it in the struct marshalling stubs (and as a result block usage of any struct containing an `Int128` in a P/Invoke scenario)

File: src/tests/Interop/PInvoke/Int128/Int128Test.cs [hunk 1]
```diff
@@ -25,6 +32,47 @@ unsafe partial class Int128Native
     [DllImport(nameof(Int128Native))]
     public static extern Int128 AddInt128(Int128 lhs, Int128 rhs);
 
+
+    [DllImport(nameof(Int128Native))]
+    public static extern void AddStructWithInt128_ByRef(ref StructWithInt128 lhs, ref StructWithInt128 rhs);
```
Comment (MichalPetryka) [inline src/tests/Interop/PInvoke/Int128/Int128Test.cs:37]: Should pointers also be checked to make sure the marshaler doesn't change the by-ref marshalling?

Comment (davidwrighton) [reply src/tests/Interop/PInvoke/Int128/Int128Test.cs:53]: I've done some mild testing of pointers. It should work acceptably well.

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 2]
```diff
@@ -10005,6 +9990,30 @@ void MethodTableBuilder::CheckForSystemTypes()
...
+#elif defined(TARGET_64BIT) || defined(TARGET_X86)
+
+            // These types correspond to fundamental data types in the underlying ABIs:
+            // * Int128:  __int128
+            // * UInt128: unsigned __int128
+            //
+            // This behavior matches the ABI standard on various Unix platforms
+            // On Windows, no standard for Int128 has been established yet, 
+            // although applying 16 byte alignment is consistent with treatment of 128 bit SSE types
+            // even on X86
```
Comment (tannergooding) [inline src/coreclr/vm/methodtablebuilder.cpp:10011]: Worth noting that the MSVC STL does have a private `__int128` that is 16-byte aligned. Clang also uses 16-byte alignment for its own `Int128` when targeting the Windows ABI.

Nothing official/documented of course, but it does help justify using `16` on Windows here for managed.

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/vm/classlayoutinfo.cpp [hunk 3]
```diff
@@ -328,6 +328,20 @@ namespace
         return FALSE;
     }
 
+    BOOL TypeHasInt128Field(CorElementType corElemType, TypeHandle pNestedType)
+    {
+        if (CorTypeInfo::IsPrimitiveType(corElemType) || corElemType == ELEMENT_TYPE_PTR || corElemType == ELEMENT_TYPE_FNPTR)
+        {
+            return FALSE;
+        }
```
Comment (jkoritzinsky) [inline src/coreclr/vm/classlayoutinfo.cpp:336]: This block is unneeded since we only return true in the `ELEMENT_TYPE_VALUETYPE` branch.

```suggestion
```

File: src/tests/Interop/PInvoke/Int128/Int128TestFieldLayout.csproj [hunk 4]
```diff
@@ -0,0 +1,15 @@
+<?xml version="1.0" encoding="utf-8"?>
+<Project Sdk="Microsoft.NET.Sdk">
+  <PropertyGroup>
+    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
+    <DebugType>embedded</DebugType>
```
Comment (jkoritzinsky) [inline src/tests/Interop/PInvoke/Int128/Int128TestFieldLayout.csproj:5]: Is this necessary?

**Review by jkoritzinsky — APPROVED** [review]
LGTM with a few nits

File: src/tests/Interop/PInvoke/Int128/Int128TestFieldLayout.csproj (hunk 4 above)
Comment (davidwrighton) [reply src/tests/Interop/PInvoke/Int128/Int128TestFieldLayout.csproj:5]: The separate test? Yes, as the other test fails, and I'd like to not get rid of it. The DebugType flag, no, but it was just a copy/paste from the other project.

File: src/coreclr/tools/aot/ILCompiler.TypeSystem.Tests/CoreTestAssembly/Platform.cs [hunk 5]
```diff
@@ -73,6 +73,24 @@ public class Exception { }
...
+    }
+
+    [Intrinsic]
+    [StructLayout(LayoutKind.Sequential)]
+    public readonly struct UInt128
+    {
+
+        private readonly ulong _lower;
+        private readonly ulong _upper;
+    }
```
Comment (MichalPetryka) [inline src/coreclr/tools/aot/ILCompiler.TypeSystem.Tests/CoreTestAssembly/Platform.cs:93]:
```suggestion
    [Intrinsic]
    [StructLayout(LayoutKind.Sequential)]
    public readonly struct Int128
    {
        private readonly ulong _lower;
        private readonly ulong _upper;
    }

    [Intrinsic]
    [StructLayout(LayoutKind.Sequential)]
    public readonly struct UInt128
    {
        private readonly ulong _lower;
        private readonly ulong _upper;
    }
```

File: src/tests/Interop/PInvoke/Int128/Int128TestFieldLayout.csproj (hunk 4 above)
Comment (jkoritzinsky) [reply src/tests/Interop/PInvoke/Int128/Int128TestFieldLayout.csproj:5]: The question was around the DebugType in particular.

**Comment by davidwrighton** [comment]
The failures here are all arm64 issues hit by the arm helix queues falling over today.
