### PR TITLE
JIT: fix issues in field-wise escape analysis

### LINKED ISSUE #111922: System.Collections.Test: Assert failure '!CREATE_CHECK_STRING(bSmallObjectHeapPtr || bLargeObjectHeapPtr)'
Hit in `libraries-pgo`. [Example run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954772&view=results) ([console log](https://helixr18s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-112639-merge-58eaeb97d9d449aba4/System.Collections.Concurrent.Tests/1/console.0d43f6bb.log?skoid=8eda00af-b5ec-4be9-b69b-0919a2338892&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2025-02-18T08%3A36%3A48Z&ske=2025-02-18T09%3A36%3A48Z&sks=b&skv=2024-11-04&sv=2024-11-04&st=2025-02-18T08%3A36%3A48Z&se=2025-02-18T09%3A36%3A48Z&sr=c&sp=r&sig=n29%2BIh5iGerTmxoFVgiT6La5LQMbs7PLwtI2IR3%2FOhs%3D)). cc @dotnet/jit-contrib 

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.Collections.Test","!CREATE_CHECK_STRING(bSmallObjectHeapPtr || bLargeObjectHeapPtr)"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=954772
**Error message validated:** `[!CREATE_CHECK_STRING(bSmallObjectHeapPtr || bLargeObjectHeapPtr)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/18/2025 8:42:54 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 7/29/2025 1:27:05 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1108628](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108628)|dotnet/runtime|[System.Collections.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1108628&view=ms.vss-test-web.build-test-results-tab&runId=30405718&resultId=211227)|dotnet/runtime#116539|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Two fixes:
* we can't retype implicit byref gc struct params, as their GC info is reported by the caller. Instead we must mark them as escaping.
* when retyping GT_STOREIND we should always use the stored data's new type

Fixes #111922.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

(revised version of #114968)

Modest number of good diffs from the retyping fix.

**Comment by AndyAyersMS** [comment]
I believe the failures are unrelated.

File: src/coreclr/jit/objectalloc.cpp [hunk 1]
```diff
@@ -698,11 +698,24 @@ void ObjectAllocator::MarkEscapingVarsAndBuildConnGraph()
...
+
+        // We have to mark all struct params as escaping, because
+        // their GC reporting is controlled by the caller
+        //
+        if (lclDsc->lvIsParam && (lclDsc->lvType == TYP_STRUCT))
+        {
+            JITDUMP("   V%02u is a struct param\n", lclNum);
+            MarkLclVarAsEscaping(lclNum);
+            continue;
         }
```
Comment (jakobbotsch) [inline src/coreclr/jit/objectalloc.cpp:719]: Is this only necessary for implicit byrefs, or truly all struct parameters?

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/objectalloc.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/objectalloc.cpp:719]: Can similar issues happen for primitives parameters too then?

Comment (jakobbotsch) [reply src/coreclr/jit/objectalloc.cpp:719]: Indeed, seems it would be better to create new locals instead of doing this retyping. Probably even for all locals, not just parameter ones.

Comment (AndyAyersMS) [reply src/coreclr/jit/objectalloc.cpp:719]: Seems like the caller is responsible for implicit byrefs, otherwise callee. See `GCInfo::gcMakeRegPtrTable`.

If had some way of forcing promotion we could probably lift this limitation too. But for now will just go with blocking implicit byrefs.

**Comment by AndyAyersMS** [comment]
@jakobbotsch I revised this to just exclude implicit byrefs; the callee reports gc fields for all the other param cases.

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/objectalloc.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/objectalloc.cpp:720]: Implicit byrefs are retyped to pointers later by `fgRetypeImplicitByRefArgs` -- retyping their local here is not going to have any effect on that, so I guess in that sense it makes sense that there would be issues around this.
I wonder if there are any similar issues around OSR locals... I suppose not because this retyping does not happen.
