### PR TITLE
Fix zero-extending displacement on win_x86_x64 JIT

### LINKED ISSUE #115661: crossgen2-comparison windows x86 Release to x86 windows failing for System.Private.CoreLib
Example build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1043288&view=results

```
Comparing crossgen results in "C:\h\w\9D490889\w\AAA3099F\u\prebuiltWork\log" and "C:\h\w\9D490889\w\AAA3099F\uploads" directories for files of type "NativeOrReadyToRunImage":
File hash sum mismatch for "System.Private.CoreLib" assembly for files of type "NativeOrReadyToRunImage":
 - "C:\h\w\9D490889\w\AAA3099F\u\prebuiltWork\log" has "eb257a2ff5dc02fb96f92a781432bb5ef7c52b2bfa1ff42c5bbba04f960bb79c"
 - "C:\h\w\9D490889\w\AAA3099F\uploads" has "a6a96aba010df04e946fad72fef8e4e90f4fbbdcf3afff9f37be2c621df61344"
Number of omitted results: 0
Number of mismatched results: 1
Total number of files compared: 236
```

### PR DESCRIPTION
**Pull request by max-charlamb**
Resolves #115661 

crossgen2-comparison test comparing crossgen targeting x86 from a x86 and x64 JIT has been failing due to the x64 host JIT using different encodings. 

I traced this back to a 32-bit displacement value not being sign extended to a 64-bit value. This caused the JIT to think the displacement was a large positive number and used a larger encoding.

Fixed by treating the displacement as a signed value.

### CODE REVIEW

**Comment by jkotas** [comment]
cc @dotnet/jit-contrib

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 1]
```diff
@@ -1977,7 +1977,7 @@ void CodeGen::genBaseIntrinsic(GenTreeHWIntrinsic* node, insOpts instOptions)
             noway_assert(simdInitTempVarNum != BAD_VAR_NUM);
 
             bool     isEBPbased;
-            unsigned offs = compiler->lvaFrameAddress(simdInitTempVarNum, &isEBPbased);
+            int offs = compiler->lvaFrameAddress(simdInitTempVarNum, &isEBPbased);
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp]: I expect there is another one of these that needs to be fixed under the `_GetElement:` path

**Comment by jkotas** [comment]
@max-charlamb The JIT codebase is auto-formatted. Could you please apply the auto-formatter patch from one of the failing formatter legs?

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp (hunk 1 above)
Comment (max-charlamb) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp]: Modified the other usage as well.

**Review by tannergooding — APPROVED** [review]
