### PR TITLE
Fix NULL conversion warnings found in Alpine x64 Source-Build

### LINKED ISSUE #4298: Alpine Legs failing to build CoreCLR
The Alpine legs are failing due to issues building runtime's CoreCLR component. There are many errors for this component, but most of them are related to null values and null pointers. Below are two examples of errors that appeared in the build:

- `error: value of type 'std::nullptr_t' is not implicitly convertible to 'UINT_PTR' (aka 'unsigned long')`
- `error: cannot initialize a member subobject of type 'COUNT_T' (aka 'unsigned int') with an rvalue of type 'std::nullptr_t'`

I believe that https://github.com/dotnet/runtime/pull/98336 may have introduced these errors.

[Link to failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2423233&view=logs&j=7830363c-9761-5497-b6c6-e8d55da0c426&t=8113443e-6df1-5d6a-2d5b-ae8e3898266f) (internal Microsoft link)

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes https://github.com/dotnet/source-build/issues/4298

### CODE REVIEW

File: src/coreclr/binder/customassemblybinder.cpp [hunk 1]
```diff
@@ -242,21 +242,21 @@ void CustomAssemblyBinder::PrepareForLoadContextRelease(INT_PTR ptrManagedStrong
 CustomAssemblyBinder::CustomAssemblyBinder()
 {
     m_pDefaultBinder = NULL;
-    m_ptrManagedStrongAssemblyLoadContext = NULL;
+    m_ptrManagedStrongAssemblyLoadContext = 0;
```
Comment (mangod9) [inline src/coreclr/binder/customassemblybinder.cpp:245]: I worry that this kind of change reduces code readability? Are these new warnings related to a tooling update?

Comment (jkoritzinsky) [reply src/coreclr/binder/customassemblybinder.cpp:245]: With a more recent musl libc (the version in Alpine 3.19), NULL is defined as nullptr directly, making what was suppressable warnings with our current toolsets into unsupressable compiler errors. This PR includes fixes for all the locations that were now procuding errors for an x64 build on Alpine 3.19 (what the source-build pipeline tests).

In the future, I plan to follow up with re-enabling the warnings and fixing the remaining cases

**Comment by jkoritzinsky** [comment]
Okay this PR has now included all of the various different changes to handle the three different definitions of `NULL` that the standard libraries we build against use (and how they interact with our DAC-ized pointer types).

- `#define NULL nullptr` as used by newer versions of musl libc (Alpine 3.19)
- `#define NULL __null` as used by glibc (GCC/Clang)
- `#define NULL 0` as used by MSVC

This generally involved changing code like `TADDR foo = NULL` to `TADDR foo = (TADDR)NULL` or `TADDR foo = 0` and changing `PTR_Bar foo = NULL` to `PTR_Bar foo = nullptr`.

File: src/coreclr/binder/customassemblybinder.cpp (hunk 1 above)
Comment (mangod9) [reply src/coreclr/binder/customassemblybinder.cpp:245]: so is there no way to #ifdef NULL to 0 somehow for this platform? 

cc: @AaronRobinsonMSFT @janvorli

Comment (janvorli) [reply src/coreclr/binder/customassemblybinder.cpp:245]: This PR uses `(UINT_PTR)NULL` instead of 0 in a similar case, it seems like it would be better here too.

Comment (janvorli) [reply src/coreclr/binder/customassemblybinder.cpp:245]: Here it would be actually `(INT_PTR)NULL`

**Comment by jkoritzinsky** [comment]
I've taken a different approach here that should still work and cut the diff in half (and removed the majority of the changes required for non Alpine).

**Review by mangod9 — APPROVED** [review]

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

File: src/coreclr/debug/daccess/daccess.cpp [hunk 2]
```diff
@@ -4324,7 +4324,7 @@ ClrDataAccess::TranslateExceptionRecordToNotification(
     GcEvtArgs pubGcEvtArgs = {};
     ULONG32 notifyType = 0;
     DWORD catcherNativeOffset = 0;
-    TADDR nativeCodeLocation = NULL;
+    TADDR nativeCodeLocation = (TADDR)NULL;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/debug/daccess/daccess.cpp:4327]: Since you have found all of these... thoughts on doing a `TADDR::Null` static? I am making this suggestion based on the assumption that we going to stuck with this `NULL` casting for `TADDR` for a long time.

File: src/coreclr/vm/clrex.h [hunk 3]
```diff
@@ -934,7 +934,7 @@ LONG CLRNoCatchHandler(EXCEPTION_POINTERS* pExceptionInfo, PVOID pv);
 // ---------------------------------------------------------------------------
 
 inline CLRException::CLRException()
-  : m_throwableHandle(NULL)
+  : m_throwableHandle((OBJECTHANDLE)NULL)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/clrex.h:937]:
```suggestion
  : m_throwableHandle{}
```

File: src/coreclr/vm/codeversion.cpp [hunk 4]
```diff
@@ -60,7 +60,7 @@ NativeCodeVersionNode::NativeCodeVersionNode(
     PatchpointInfo* patchpointInfo,
     unsigned ilOffset)
     :
-    m_pNativeCode(NULL),
+    m_pNativeCode((PCODE)NULL),
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/codeversion.cpp:63]:
```suggestion
    m_pNativeCode{},
```

File: src/coreclr/vm/custommarshalerinfo.cpp [hunk 5]
```diff
@@ -25,7 +25,7 @@ CustomMarshalerInfo::CustomMarshalerInfo(LoaderAllocator *pLoaderAllocator, Type
 : m_NativeSize(0)
 , m_hndManagedType(hndManagedType)
 , m_pLoaderAllocator(pLoaderAllocator)
-, m_hndCustomMarshaler(NULL)
+, m_hndCustomMarshaler(0)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/custommarshalerinfo.cpp:28]:
```suggestion
, m_hndCustomMarshaler{}
```

File: src/coreclr/vm/domainassembly.cpp [hunk 6]
```diff
@@ -37,8 +37,8 @@ DomainAssembly::DomainAssembly(PEAssembly* pPEAssembly, LoaderAllocator* pLoader
     m_pLoaderAllocator(pLoaderAllocator),
     m_level(FILE_LOAD_CREATE),
     m_loading(TRUE),
-    m_hExposedModuleObject(NULL),
-    m_hExposedAssemblyObject(NULL),
+    m_hExposedModuleObject((LOADERHANDLE)NULL),
+    m_hExposedAssemblyObject((LOADERHANDLE)NULL),
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/domainassembly.cpp:41]:
```suggestion
    m_hExposedModuleObject{},
    m_hExposedAssemblyObject{},
```

File: src/coreclr/vm/exceptionhandling.h [hunk 7]
```diff
@@ -132,7 +132,7 @@ struct ExceptionTrackerBase
 
     ExceptionTrackerBase(PTR_EXCEPTION_RECORD pExceptionRecord, PTR_CONTEXT pExceptionContext, PTR_ExceptionTrackerBase pPrevNestedInfo) :
         m_pPrevNestedInfo(pPrevNestedInfo),
-        m_hThrowable(NULL),
+        m_hThrowable(0),
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/exceptionhandling.h:135]:
```suggestion
        m_hThrowable{},
```

File: src/coreclr/vm/exceptionhandling.h [hunk 8]
```diff
@@ -265,7 +265,7 @@ class ExceptionTracker : public ExceptionTrackerBase
                      PTR_CONTEXT           pContextRecord) :
         ExceptionTrackerBase(pExceptionRecord, pContextRecord, PTR_NULL),
         m_pThread(GetThread()),
-        m_uCatchToCallPC(NULL),
+        m_uCatchToCallPC(0),
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/exceptionhandling.h:268]:
```suggestion
        m_uCatchToCallPC{},
```

File: src/coreclr/vm/exinfo.cpp [hunk 9]
```diff
@@ -317,7 +317,7 @@ ExInfo::ExInfo(Thread *pThread, EXCEPTION_RECORD *pExceptionRecord, CONTEXT *pEx
     m_kind(exceptionKind),
     m_passNumber(1),
     m_idxCurClause(0xffffffff),
-    m_notifyDebuggerSP(NULL),
+    m_notifyDebuggerSP(0),
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/exinfo.cpp:320]:
```suggestion
    m_notifyDebuggerSP{},
```

File: src/coreclr/vm/listlock.h [hunk 10]
```diff
@@ -65,7 +65,7 @@ class ListLockEntryBase
         m_pNext(NULL),
         m_dwRefCount(1),
         m_hrResultCode(S_FALSE),
-        m_hInitException(NULL),
+        m_hInitException((LOADERHANDLE)0),
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/listlock.h:68]:
```suggestion
        m_hInitException{},
```

File: src/coreclr/vm/multicorejit.h [hunk 11]
```diff
@@ -92,7 +92,7 @@ class MulticoreJitCodeInfo
     TADDR m_entryPointAndTierInfo;
 
 public:
-    MulticoreJitCodeInfo() : m_entryPointAndTierInfo(NULL)
+    MulticoreJitCodeInfo() : m_entryPointAndTierInfo(0)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/multicorejit.h:95]:
```suggestion
    MulticoreJitCodeInfo() : m_entryPointAndTierInfo{}
```

**Review by AaronRobinsonMSFT — APPROVED** [review]
One suggestion and a few nits to consider. Thanks!

File: src/coreclr/debug/daccess/daccess.cpp (hunk 2 above)
Comment (jkoritzinsky) [reply src/coreclr/debug/daccess/daccess.cpp:4327]: `TADDR` is a typedef from `uintptr_t` so we can't do anything like that today.

In the future, I'd like to move in that direction (by making `TADDR` an enum-class or something like that to get us more explicit typing without regressions on Windows) but that's going to be a lot more work than I want to do in this PR.

Comment (AaronRobinsonMSFT) [reply src/coreclr/debug/daccess/daccess.cpp:4327]: Oh, right. I was thinking it was a `struct`. All good.
