### PR TITLE
Fix poisoning for very large structs

### LINKED ISSUE #60852: .NET 6 C++/CLI runtime generates InvalidProgramException when large stack-allocated variables are used
### Description

I am porting some code to .NET 6 and encountered some issues running C++/CLI code. After narrowing it down, it seems that using large stack-allocated arrays (larger than 65536 bytes) will generate a System.InvalidProgramException when the method with the offending variable is called for the first time.

### Reproduction Steps

A minimal repro is to put the following code into a CLR Class Library and call it from a C# program:

```
namespace ClassLibrary1
{
	public ref class Class1
        {
        public:
	        static System::String^ BrokenFunction()
	        {
		        unsigned char block[16 * 1024 * 4 + 1] = { 0 };
		        return gcnew String("unused");
	        }
	        static System::String^ WorkingFunction()
	        {
		        unsigned char block[16 * 1024 * 4 + 0] = { 0 };
		        return gcnew String("unused");
	        }
	        static System::String^ WorkingFunction2()
	        {
		        unsigned char block[16 * 1024 * 4 + 0] = { 0 };
		        unsigned char block2[16 * 1024 * 4 + 0] = { 0 };
		        return gcnew String("unused");
	        }
	        static System::String^ AlsoWorkingFunction()
	        {
		        unsigned char* block = (unsigned char*)alloca(16 * 1024 * 4 + 1);
		        memset(block, 0, 16 * 1024 * 4 + 1);
		        return gcnew String("unused");
	        }
        };
}
```

As can be seen, it looks like there's a fundamental limit in the compiler-generated types which back the arrays. Note that prior to .NET 6, this appeared to work without issue.

### Expected behavior

The program should not crash as long as we don't exceed the thread stack size.

### Actual behavior

The program throws an exception as soon as a method with a large local array is called.

### Regression?

Yes, this appears to be a .NET 6 specific issue.

### Known Workarounds

In my case, as this is a scratch buffer, I could use `alloca` instead.

### Configuration

.NET 6 RC2
Windows 10, x64
VS2022

Haven't tried any other configurations.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jakobbotsch**
For very large structs poisoning could end up generating instructions
requiring larger local var offsets than we can handle which would hit an
IMPL_LIMIT that throws InvalidProgramException. Switch to using rep
stosd (x86/x64)/memset helper (other platforms) when a local needs more
than a certain number of mov instructions to poison.

Fix #60852

### CODE REVIEW

File: src/coreclr/jit/lsrabuild.cpp [hunk 1]
```diff
@@ -3291,7 +3299,7 @@ void LinearScan::BuildStoreLocDef(GenTreeLclVarCommon* storeLoc,
         defCandidates = allRegs(type);
     }
 #else
-    defCandidates = allRegs(type);
+    defCandidates  = allRegs(type);
```
Comment (jakobbotsch) [inline src/coreclr/jit/lsrabuild.cpp:3302]: No idea why clang-tidy wants this changed all of a sudden.

File: src/coreclr/jit/lsrabuild.cpp [hunk 2]
```diff
@@ -2356,7 +2356,15 @@ void LinearScan::buildIntervals()
         // into the scratch register, so it will be killed here.
         if (compiler->compShouldPoisonFrame() && compiler->fgFirstBBisScratch() && block == compiler->fgFirstBB)
         {
-            addRefsForPhysRegMask(genRegMask(REG_SCRATCH), currentLoc + 1, RefTypeKill, true);
+            regMaskTP killed;
+#if defined(TARGET_XARCH)
+            // Poisoning uses EAX for small vars and rep stosd that kills edi, ecx and eax for large vars.
+            killed = RBM_EDI | RBM_ECX | RBM_EAX;
+#else
+            // Poisonining uses REG_SCRATCH for small vars and memset helper for big vars.
```
Comment (AndyAyersMS) [inline src/coreclr/jit/lsrabuild.cpp:2364]:
```suggestion
            // Poisoning uses REG_SCRATCH for small vars and memset helper for big vars.
```

**Review by AndyAyersMS — APPROVED** [review]
LGTM.

We should consider backporting this one.

**Comment by jakobbotsch** [comment]
> We should consider backporting this one.

Agree. Luckily it only affects code compiled in debug without .zeroinit, but the impact may still be quite large.

File: src/coreclr/jit/codegencommon.cpp [hunk 3]
```diff
@@ -12461,49 +12473,63 @@ void CodeGen::genPoisonFrame(regMaskTP regLiveIn)
 
         assert(varDsc->lvOnFrame);
 
-        int size = (int)compiler->lvaLclSize(varNum);
-
+        unsigned int size = compiler->lvaLclSize(varNum);
         if (size / TARGET_POINTER_SIZE > 16)
```
Comment (jakobbotsch) [inline src/coreclr/jit/codegencommon.cpp:12477]:
```suggestion
        if ((size / TARGET_POINTER_SIZE) > 16)
```
