### PR TITLE
Make getTypeForPrimitiveValueClass treat different signs as different types

### LINKED ISSUE #71632: Box-unbox optimization swallows InvalidCastException on different signs
### Description

Values with different signs are casted with no exception while roundtripping through object.

### Reproduction Steps

```C#
[MethodImpl(MethodImplOptions.NoInlining)]
private static sbyte Problem(byte a)
{
    object box = a;
    Use(ref box);
    return (sbyte)box;
}

[MethodImpl(MethodImplOptions.NoInlining)]
private static sbyte Problem2(byte a)
{
    object box = a;
    return (sbyte)box;
}

public static void Use<T>(ref T arg) { }
```

### Expected behavior

Both methods throw InvalidCastException.

### Actual behavior

Problem2 doesn't throw it.

### Regression?

Yes, introduced probably in Box-unbox enum optimization introduced in #70167.

### Known Workarounds

_No response_

### Configuration

.Net 7 builds off main branch, Preview 5 doesn't reproduce it.

### Other information

It's probably caused by `getTypeForPrimitiveValueClass` treating types of the same size as the same here:
https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/jitinterface.cpp#L3974

### PR DESCRIPTION
**Pull request by MichalPetryka**
Fixes #71632.

### CODE REVIEW

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -3969,54 +3969,10 @@ CorInfoType CEEInfo::getTypeForPrimitiveValueClass(
     }
     else
     {
-        switch (th.GetInternalCorElementType())
+        CorElementType elementType = th.GetInternalCorElementType();
+        if (elementType >= ELEMENT_TYPE_BOOLEAN && elementType <= ELEMENT_TYPE_R8)
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:3973]: This does not handle `ELEMENT_TYPE_I` and `ELEMENT_TYPE_U`

Comment (MichalPetryka) [reply src/coreclr/vm/jitinterface.cpp:3973]: Missed those, thanks.

File: src/coreclr/vm/jitinterface.cpp [hunk 2]
```diff
@@ -3969,54 +3969,13 @@ CorInfoType CEEInfo::getTypeForPrimitiveValueClass(
     }
     else
     {
-        switch (th.GetInternalCorElementType())
+        CorElementType elementType = th.GetInternalCorElementType();
+        if (elementType >= ELEMENT_TYPE_BOOLEAN && elementType <= ELEMENT_TYPE_R8
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:3973]: We have a helper method for this. I think it should be possible to simplify the whole thing into:
```
```
TypeHandle th(clsHnd);
_ASSERTE (!th.IsGenericVariable());

CorElementType elementType = th.GetVerifierCorElementType();
if (CorIsPrimitiveType(elementtype) || elementType == ELEMENT_TYPE_PTR || ELEMENT_TYPE_FNPTR)
{
    result = asCorInfoType(elementType);
}
```

It looks odd that this method is handling `ELEMENT_TYPE_PTR` and `ELEMENT_TYPE_FNPTR`. It does not match the name `getTypeForPrimitiveValueClass`. 

Is the JIT really expecting this method to handle `ELEMENT_TYPE_PTR` and `ELEMENT_TYPE_FNPTR`?

Comment (MichalPetryka) [reply src/coreclr/vm/jitinterface.cpp:3973]: > Is the JIT really expecting this method to handle `ELEMENT_TYPE_PTR` and `ELEMENT_TYPE_FNPTR`?
Yes, for example in https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/importer.cpp#L4203

Comment (MichalPetryka) [reply src/coreclr/vm/jitinterface.cpp:3973]: `CorIsPrimitiveType` would also include `ELEMENT_TYPE_END`, would that be okay?

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp:3973]: > Yes, for example in https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/importer.cpp#L4203

I do not see the connection between this line and the method being changed in this PR. Could you please shed some light on it?

> CorIsPrimitiveType would also include ELEMENT_TYPE_END, would that be okay?

Yes, that' ok. `ELEMENT_TYPE_END` is never returned by as CorElementType of a type.

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp]: `CORINFO_FLG_VALUECLASS` is not set for pointers and function pointers. This is unreachable code that can be deleted.

Any other places?

Comment (MichalPetryka) [reply src/coreclr/vm/jitinterface.cpp]: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/importer.cpp#L3596 relies on it not being undef
https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/importer.cpp#L13647 same here
https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/importer.cpp#L15730 and here

I also see some usages in interpreter.cpp.

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp]: None of these places will be affected if `elementType == ELEMENT_TYPE_PTR || elementType == ELEMENT_TYPE_FNPTR` check is deleted here. Could you please change the condition to just `if (CorIsPrimitiveType(elementType))` so that it matches the method name, and see whether it is going to cause any issues?

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib PTAL for this community PR.

**Review by EgorBo — APPROVED** [review]

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/vm/jitinterface.cpp (hunk 2 above)
Comment (jakobbotsch) [reply src/coreclr/vm/jitinterface.cpp]: The failure looks like the same as https://github.com/dotnet/runtime/pull/66413#issuecomment-1175489442 which might be related to https://github.com/dotnet/runtime/pull/71439. Does not look related to your change.

Comment (EgorBo) [reply src/coreclr/vm/jitinterface.cpp]: The failure is unrelated and failed in other PRs - https://github.com/dotnet/runtime/pull/66413#issuecomment-1175509710

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp]: I have opened blocking-clean-in issue https://github.com/dotnet/runtime/issues/71684 on this.

When merging on red, failures should be always tracked by active blocking-clean-in issue.
