### PR TITLE
Fix mdarrays

### LINKED ISSUE #38260: CG2: Test failure JIT\Generics\Arrays\TypeParameters\MultiDim\class01 and struct01
Example run:
https://dev.azure.com/dnceng/public/_build/results?buildId=698082&view=ms.vss-test-web.build-test-results-tab&runId=21633748&resultId=100954&paneView=debug

Tests failing:
JIT\Generics\Arrays\TypeParameters\MultiDim\class01
JIT\Generics\Arrays\TypeParameters\MultiDim\struct01
Loader\\classloader\\regressions\\Dev12_518401\\dev12_518401\\dev12_518401

Platform:
Win10 x64

Item log:
<pre>
Could Not Find C:\h\w\A62C0917\w\A62C0924\e\JIT\Generics\Arrays\TypeParameters\MultiDim\struct01\struct01.dll.rsp
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B (COR_E_BADIMAGEFORMAT))
   at Gen`1.StoreTArray(T[] arr)
   at Test.Main()

Return code:      1
Raw output file:      C:\h\w\A62C0917\w\A62C0924\e\JIT\Generics\Reports\JIT.Generics\Arrays\TypeParameters\MultiDim\struct01\struct01.output.txt
Raw output:
BEGIN EXECUTION
        1 file(s) copied.
Response file: C:\h\w\A62C0917\w\A62C0924\e\JIT\Generics\Arrays\TypeParameters\MultiDim\struct01\\struct01.dll.rsp
--inputbubble
C:\h\w\A62C0917\w\A62C0924\e\JIT\Generics\Arrays\TypeParameters\MultiDim\struct01\IL\struct01.dll
-r:C:\h\w\A62C0917\w\A62C0924\e\JIT\Generics\Arrays\TypeParameters\MultiDim\struct01\IL\*.dll
-o:C:\h\w\A62C0917\w\A62C0924\e\JIT\Generics\Arrays\TypeParameters\MultiDim\struct01\\struct01.dll
--targetarch:x64
-O
-r:C:\h\w\A62C0917\p\System.*.dll
-r:C:\h\w\A62C0917\p\Microsoft.*.dll
-r:C:\h\w\A62C0917\p\mscorlib.dll
-r:C:\h\w\A62C0917\p\netstandard.dll
" "dotnet" "C:\h\w\A62C0917\p\crossgen2\crossgen2.dll" @"C:\h\w\A62C0917\w\A62C0924\e\JIT\Generics\Arrays\TypeParameters\MultiDim\struct01\\struct01.dll.rsp" "
Info: Method `[struct01]Test.Eval(bool)` was not compiled because `https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS` requires runtime JIT
Emitting R2R PE file: C:\h\w\A62C0917\w\A62C0924\e\JIT\Generics\Arrays\TypeParameters\MultiDim\struct01\struct01.dll
 "C:\h\w\A62C0917\p\corerun.exe" struct01.dll 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A62C0917\p
> C:\h\w\A62C0917\w\A62C0924\e\JIT\Generics\Arrays\TypeParameters\MultiDim\struct01\struct01.cmd
</pre>

### PR DESCRIPTION
**Pull request by davidwrighton**
- MDArrays are special and method references to the methods needs to be encoded with their type in more cases than normal methods
- Only generate the owner type if the memberref does not encode the same owner type
- Add tests for various multidimensional array scenarios to crossgen2smoke

Fix issue #38260

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/crossgen-contrib

File: src/tests/readytorun/crossgen2/Program.cs [hunk 1]
```diff
@@ -1626,6 +1626,141 @@ private static bool GenericLdtokenTest()
...
+        }
+        public override bool Equals(object other)
+        {
+            return Equals((SomeLargeStruct)other);
+        }
+
+        public override int GetHashCode() { return x; }
+    }
+
+    struct SomeClass : IEquatable<SomeClass>
```
Comment (AntonLapounov) [inline src/tests/readytorun/crossgen2/Program.cs:1661]: Should it be `class`?

File: src/tests/readytorun/crossgen2/Program.cs [hunk 2]
```diff
@@ -1626,6 +1626,141 @@ private static bool GenericLdtokenTest()
...
+            return false;
+        }
+
+        return true;
+    }
+
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    private static bool ArrayLdtokenTests()
+    {
+        RuntimeMethodHandle rmhCtor1 = default(RuntimeMethodHandle);
```
Comment (AntonLapounov) [inline src/tests/readytorun/crossgen2/Program.cs:1751]: It might be worth adding a comment explaining what we are testing here.

**Review by AntonLapounov — APPROVED** [review]
