### PR TITLE
[wasm][debugger] Added support for getting members of static structures.

### LINKED ISSUE #68539: [wasm][debugger] Fix member type in static structures
When we get static structure members from the runtime, type information `etype` in the buffer is always "17" (valueType), no matter what the real type of the member is. 
https://github.com/dotnet/runtime/blob/6387a2dc3de16e2f22c8e49678bee33506260c46/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L2003
Because of this, we are not able to correctly create objects on the debugger side and one of its consequences is erroneous value in ["value"]["className"] and  ["value"]["description"]. For non-static structures and non-static/static classes the problem does not exist, types are granted correctly.

How to reproduce in tests:
take `EvaluateBrowsableNone` and add two scenarios for `EvaluateBrowsableStaticStruct` that is the same as existing `EvaluateBrowsableStaticClass` but a structure. One scenario should be for fields, the other for auto-properties. 

Result:
all `testNoneProps` elements are valueType objects with incorrect description and classNames.

Expected behavior:
`testNoneProps` elements should be the same as for `isCustomGetter = false` scenarios.

After it's fixed, add these two cases to all the other `EvaluateBrowsable*` tests and additionally `EvaluateBrowsableCustomPropertiesStruct` scenario can be added, that is nearly the same as `EvaluateBrowsableCustomPropertiesClass` but a structure.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/68539.

Changes in this PR:
- Members of static valueTypes are now being returned on `getProperties`, before they were skipped. To do it, flag `includeStatic=true` was added to the data flow.
- For static properties, to get values we need to invoke them. Because they are static, we cannot invoke getter using `objectId`, we have to use `typeId` instead. This change was made in `GetNotAutoExpandableObject` where we put different values in `containerId`, conditioned by property being static. We have to save the information if getter is static in `JObject` to skip writing `ElementType` to the buffer in `InvokeMethod` - for statics runtime does not expect such information. 
- Changed the expected result in `CallFunctionOnTests.PropertyGettersTest`. Previously properties of static classes were skipped in the reply to `getProperties`. It was not the planned behavior so in this PR they are added to the reply as well.
- Changed the expected number of fields for `MiscTest.InspectTaskAtLocals` - now we expect 4 statics to be there as well:
image

- Smaller changes: removed whitespaces in Browsable tests classes to match automatic formatting, renamed Browsable test classes to be more descriptive, added missing test cases for static non-autoproperties in classes and structures.

### CODE REVIEW

**Comment by lewing** [comment]
@ilonatommy  is this waiting on review now?

**Comment by lewing** [comment]
cc @radical @thaystg

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 1]
```diff
@@ -53,48 +53,74 @@ public ValueTypeClass(byte[] buffer, string className, JArray fields, int typeId
...
             var typePropertiesBrowsableInfo = typeInfo?.Info?.DebuggerBrowsableProperties;
 
             IReadOnlyList<FieldTypeClass> fieldTypes = await sdbAgent.GetTypeFields(typeId, token);
-            // statics should not be in valueType fields: CallFunctionOnTests.PropertyGettersTest
+
+            JArray fields = new();
+            if (includeStatic)
+            {
+                IEnumerable<FieldTypeClass> staticFields = fieldTypes
+                .Where(f => f.Attributes.HasFlag(FieldAttributes.Static));
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:69]:
```suggestion
                IEnumerable<FieldTypeClass> staticFields =
                	fieldTypes.Where(f => f.Attributes.HasFlag(FieldAttributes.Static));
```

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 2]
```diff
@@ -53,48 +53,74 @@ public ValueTypeClass(byte[] buffer, string className, JArray fields, int typeId
...
+                        FieldAttributes.Private | FieldAttributes.Static => "private",
+                        FieldAttributes.Public | FieldAttributes.Static => "result",
+                        _ => "internal"
+                    }
+                    : field.Attributes switch
                 {
                     FieldAttributes.Private => "private",
                     FieldAttributes.Public => "result",
                     _ => "internal"
                 };
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:113]:
```suggestion
                    {
                        FieldAttributes.Private => "private",
                        FieldAttributes.Public => "result",
                        _ => "internal"
                    };
```

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 3]
```diff
@@ -53,48 +53,74 @@ public ValueTypeClass(byte[] buffer, string className, JArray fields, int typeId
...
+            JObject GetFieldWithMetadata(FieldTypeClass field, JObject fieldValue, bool isStatic)
+            {
+                // GetFieldValue returns JObject without name and we need this information
+                if (isStatic)
+                    fieldValue["name"] = field.Name;
+
+                fieldValue["__section"] = isStatic
+                    ? field.Attributes switch
+                    {
+                        FieldAttributes.Private | FieldAttributes.Static => "private",
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:104]: Check with `HasFlag` instead of this, because this would be doing an exact match of the value. But the field attributes could have other flags too.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 4]
```diff
@@ -53,48 +53,74 @@ public ValueTypeClass(byte[] buffer, string className, JArray fields, int typeId
...
+                        FieldAttributes.Public | FieldAttributes.Static => "result",
+                        _ => "internal"
+                    }
+                    : field.Attributes switch
                 {
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:109]: .. and same thing here

File: src/mono/wasm/debugger/DebuggerTestSuite/CallFunctionOnTests.cs [hunk 5]
```diff
@@ -625,7 +625,11 @@ public async Task CFOWithSilentReturnsErrors(string eval_fn, string bp_loc, int
 
                    // Auto properties show w/o getters, because they have
                    // a backing field
-                   DTAutoProperty = TDateTime(dt)
+                   DTAutoProperty = TDateTime(dt),
+
+                   // Static properties
+                   PublicStaticDTProp = TGetter("PublicStaticDTProp"),
+                   PrivateStaticDTProp = TGetter("PrivateStaticDTProp"),
                }, local_name);
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/CallFunctionOnTests.cs:633]: test: internal static

File: src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs [hunk 6]
```diff
@@ -872,7 +872,7 @@ public async Task GetSourceEmbeddedSource()
                 await CheckProps(t_props, new
                     {
                         Status = TGetter("Status")
-                    }, "t_props", num_fields: 54);
+                    }, "t_props", num_fields: 58);
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:875]: You can replace `num_fields` by `skip_num_fields_check: true`.

**Review by radical — CHANGES_REQUESTED** [review]
Other than the feedback, it looks good.
In a future PR - static members in base/derived classes .

File: src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs (hunk 6 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:875]: On the one hand, yes but on the other: when we break something so that we won't be displaying all the fields correctly (e.g. I would roll back this PR) then this test will help us because it will fail. I would prefer to leave it, if someone will find it problematic at some point - it can be replaced then.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 7]
```diff
@@ -98,19 +98,10 @@ JObject GetFieldWithMetadata(FieldTypeClass field, JObject fieldValue, bool isSt
...
-                    : field.Attributes switch
-                {
-                    FieldAttributes.Private => "private",
-                    FieldAttributes.Public => "result",
-                    _ => "internal"
-                };
+                fieldValue["__section"] = field.Attributes.HasFlag(FieldAttributes.Private)
+                    ? "private" :
+                    field.Attributes.HasFlag(FieldAttributes.Public) ?
+                    "public" : "internal";
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:104]: nit:
```csharp
                fieldValue["__section"] = field.Attributes.HasFlag(FieldAttributes.Private)
                      ? "private"
					  : (field.Attributes.HasFlag(FieldAttributes.Public) ? "public" : "internal");
```

**Comment by radical** [comment]
There is a test failure:

```
DebuggerTests.GetPropertiesTests.PropertiesSortedByProtectionLevel
...

  Error Message:
   missing or unexpected members found
  Stack Trace:
     at DebuggerTests.GetPropertiesTests.AssertHasOnlyExpectedProperties(String[] expected_names, IEnumerable`1 actual) in /_/src/mono/wasm/debugger/DebuggerTestSuite/GetPropertiesTests.cs:line 445
   at DebuggerTests.GetPropertiesTests.<>c__DisplayClass12_0.<<PropertiesSortedByProtectionLevel>b__0>d.MoveNext() in /_/src/mono/wasm/debugger/DebuggerTestSuite/GetPropertiesTests.cs:line 545
--- End of stack trace from previous location ---
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 256
   at DebuggerTests.GetPropertiesTests.PropertiesSortedByProtectionLevel(Dictionary`2 expectedPublic, Dictionary`2 expectedProtInter, Dictionary`2 expectedPriv, String entryMethod) in /_/src/mono/wasm/debugger/DebuggerTestSuite/GetPropertiesTests.cs:line 535
--- End of stack trace from previous location ---
  Standard Output Messages:
 Missing: b
```

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs (hunk 3 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs]: When `attrs = Assembly`  and does not include Private, `attr.HasFlag(FieldAttributes.Private) == true`. To fix it I changed the order of arguments to check for Assembly instead of Private and leave Private as the 3rd option and it works but it's kind of strange.

**Comment by radical** [comment]
Looking at the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.fieldattributes?view=net-6.0):
```
Private: 1
Assembly: 3
...
FieldAccessMask: 7
```

So, if it's assembly then `HasFlag` would return true for `Private` also, because it will do something like `(Attributes & FieldAttributes.Private) == FieldAttributes.Private`.

Instead, we should do it like:
 https://github.com/dotnet/runtime/blob/c21ae04d923a1e5d2964fed61cc919571cce2efe/src/libraries/System.Private.CoreLib/src/System/Reflection/FieldInfo.cs#L30

This checks the exact value instead.

**Review by radical — APPROVED** [review]
Only one needed change remaining - https://github.com/dotnet/runtime/pull/69542#issuecomment-1197168627 .

Other than that, LGTM 👍
