### PR TITLE
JIT: Skip more covariance checks

### LINKED ISSUE #96787: JIT doesn't see real type of field in a shared generic type with exact context
Filed for https://github.com/dotnet/runtime/pull/96773

JIT doesn't see real type of the `arr` field and doesn't fold the condition.

```cs
public class MyList<T>
{
    public T[] arr;
}

bool Test(MyList<string> list) => list.arr.GetType() == typeof(string[]);
```
Current codegen for `Test`:
```asm
; Method Program:Foo(MyList`1[System.String]):ubyte:this (FullOpts)
G_M55733_IG01:
G_M55733_IG02:
       mov      rax, gword ptr [rdx+0x08]
       mov      rcx, 0xD1FFAB1E      ; System.String[]
       cmp      qword ptr [rax], rcx
       sete     al
       movzx    rax, al
G_M55733_IG03:
       ret      
; Total bytes of code: 24
```
Expected codegen:
```
nullchecks
return true;
```

### LINKED ISSUE #107080: JIT: We should be able to avoid covariance checks when inlining with exact types
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public static void Foo(List<string> l)
{
    l[0] = "abc";
}
```

Current codegen:
```asm
; Assembly listing for method Program:Foo(System.Collections.Generic.List`1[System.String]) (Tier1)
; Emitting BLENDED_CODE for X64 with AVX - Windows
; Tier1 code
; optimized code
; optimized using Synthesized PGO
; rsp based frame
; partially interruptible
; with Synthesized PGO: fgCalledCount is 100
; No PGO data
; 1 inlinees with PGO data; 0 single block inlinees; 0 inlinees without PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  6,  6   )     ref  ->  rbx         class-hnd single-def <System.Collections.Generic.List`1[System.String]>
;  V01 OutArgs      [V01    ] (  1,  1   )  struct (32) [rsp+0x00]  do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;
; Lcl frame size = 32

G_M31751_IG01:  ;; offset=0x0000
       push     rbx
       sub      rsp, 32
       mov      rbx, rcx
                                                ;; size=8 bbWeight=1 PerfScore 1.50
G_M31751_IG02:  ;; offset=0x0008
       cmp      dword ptr [rbx+0x10], 0
       je       SHORT G_M31751_IG04
       mov      rcx, gword ptr [rbx+0x08]
       xor      edx, edx
       mov      r8, 0x27C2F262D78      ; 'abc'
       call     CORINFO_HELP_ARRADDR_ST
       inc      dword ptr [rbx+0x14]
                                                ;; size=30 bbWeight=1 PerfScore 10.50
G_M31751_IG03:  ;; offset=0x0026
       add      rsp, 32
       pop      rbx
       ret
                                                ;; size=6 bbWeight=1 PerfScore 1.75
G_M31751_IG04:  ;; offset=0x002C
       call     [System.ThrowHelper:ThrowArgumentOutOfRange_IndexMustBeLessException()]
       int3
                                                ;; size=7 bbWeight=0 PerfScore 0.00

; Total bytes of code 51, prolog size 5, PerfScore 13.75, instruction count 15, allocated bytes for code 51 (MethodHash=efae83f8) for method Program:Foo(System.Collections.Generic.List`1[System.String]) (Tier1)
; ============================================================
```

Expected: no call to `CORINFO_HELP_ARRADDR_ST`. It seems like we should be able to statically determine here that no covariance check is necessary.

cc @dotnet/jit-contrib, @EgorBo this might be up your alley...

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/107080
Closes https://github.com/dotnet/runtime/issues/96787

```cs
void Test(List<string> l)
{
    l[0] = "abc";
}
```
Was:
```asm
; Assembly listing for method Test
       push     rbx
       sub      rsp, 32
       mov      rbx, rdx
       cmp      dword ptr [rbx+0x10], 0
       je       SHORT G_M54492_IG04
       mov      rcx, gword ptr [rbx+0x08]
       xor      edx, edx
       mov      r8, 0x1FE6C3654A0      ; 'abc'
       call     CORINFO_HELP_ARRADDR_ST
       inc      dword ptr [rbx+0x14]
       add      rsp, 32
       pop      rbx
       ret      
G_M54492_IG04:
       call     [System.ThrowHelper:ThrowArgumentOutOfRange_IndexMustBeLessException()]
       int3     
; Total bytes of code 51
```
Now:
```asm
; Assembly listing for method Test
       sub      rsp, 40
       cmp      dword ptr [rdx+0x10], 0
       je       SHORT G_M54492_IG04
       mov      rax, gword ptr [rdx+0x08]
       mov      ecx, dword ptr [rax+0x08]
       test     rcx, rcx
       je       SHORT G_M54492_IG05
       mov      rcx, 0x137EF1554A0      ; 'abc'
       mov      gword ptr [rax+0x10], rcx
       inc      dword ptr [rdx+0x14]
       add      rsp, 40
       ret      
G_M54492_IG04:
       call     [System.ThrowHelper:ThrowArgumentOutOfRange_IndexMustBeLessException()]
       int3     
G_M54492_IG05:
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
; Total bytes of code 57
```
So we can either use a faster write barrier helper, or, like in this case, omit it at all.

[Diffs](https://github.com/MihuBot/runtime-utils/issues/574) - I was expecting more **size** regressions since we replace a call with a call + explicit bound checks, but, apparently, some opts kick in.

### CODE REVIEW

**Comment by EgorBo** [comment]
@MihuBot

**Comment by EgorBo** [comment]
@EgorBot -arm64 -intel
```cs
using BenchmarkDotNet.Attributes;
using System.Collections.Generic;

public class Bench
{
    List<string> _list = new();

    [Benchmark]
    public void Test() => _list[0] = "abc";
}
```

**Comment by EgorBo** [comment]
@EgorBot -arm64 -intel
```cs
using BenchmarkDotNet.Attributes;
using System.Collections.Generic;

public class Bench
{
    List<string> _list = new() { null };

    [Benchmark]
    public void Test() => _list[0] = "abc";
}
```

**Comment by EgorBo** [comment]
@MihuBot

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -7088,18 +7088,15 @@ GenTree* Compiler::fgMorphCall(GenTreeCall* call)
...
+        GenTree* index = call->gtArgs.GetArgByIndex(1)->GetNode();
         GenTree* value = call->gtArgs.GetArgByIndex(2)->GetNode();
-        if (value->IsIntegralConst(0))
-        {
-            assert(value->OperGet() == GT_CNS_INT);
-
-            GenTree* arr   = call->gtArgs.GetArgByIndex(0)->GetNode();
-            GenTree* index = call->gtArgs.GetArgByIndex(1)->GetNode();
 
+        if (impCanSkipCovariantStoreCheck(value, arr))
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:7098]: Can we rename it to remove the `imp` prefix given that it is being used outside import now?

Comment (EgorBo) [reply src/coreclr/jit/morph.cpp]: Done

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -31840,3 +31847,116 @@ GenTree* Compiler::gtFoldExprHWIntrinsic(GenTreeHWIntrinsic* tree)
...
+//    can skip the array store covariance check.
+//
+// Arguments:
+//    value -- tree producing the value to store
+//    array -- tree representing the array to store to
+//
+// Returns:
+//    true if the store does not require a covariance check.
+//
+bool Compiler::gtCanSkipCovariantStoreCheck(GenTree* value, GenTree* array)
```
Comment (EgorBo) [inline src/coreclr/jit/gentree.cpp:31862]: No changes here, it's just moved from importer.cpp and renamed.

**Review by jakobbotsch — APPROVED** [review]

**Comment by EgorBo** [comment]
@MihuBot

**Comment by EgorBo** [comment]
Ugh, `isMoreSpecific` is not working as I expected (e.g. it says that `IFoo` is more specific then `FooImpl<_Canon>`). While `getFieldType` requires exact owner (for validation purposes mainly). Looks like I need to modify JIT-EE 🙁

**Comment by AndyAyersMS** [comment]
> Ugh, `isMoreSpecific` is not working as I expected (e.g. it says that `IFoo` is more specific then `FooImpl<_Canon>`). While `getFieldType` requires exact owner (for validation purposes mainly). Looks like I need to modify JIT-EE 🙁

I think you could update `isMoreSpecific` to say that a class type is more specific than an interface type, as long as the class is not `_Canon` or `Object`.

**Comment by EgorBo** [comment]
> I think you could update `isMoreSpecific` to say that a class type is more specific than an interface type, as long as the class is not `_Canon` or `Object`.

I think it's still not enough sadly, say we have:
```
class BaseClass
class SubClass<T>
```
It is still going to return `BaseClass` as more specific than `SubClass<_Canon>` (although, it passes your `as long as the class is not _Canon or Object.` suggestion). `isMoreSpecific` needs to also check class hierarchy I guess.

I was afraid of touch it, so I ended up just validating that the hint class actually has the field or not.

**Comment by EgorBo** [comment]
@MihuBot

**Comment by EgorBo** [comment]
@MihuBot

**Comment by EgorBo** [comment]
@jkotas could you please review VM changes?

I suspect that there is still some room for improvements in that function, but I don't think that will bring any diffs.

E.g. `IsMoreSpecific(Foo<ClassA>, Foo<ClassB>)`

**Comment by AndyAyersMS** [comment]
> @jkotas could you please review VM changes?
> 
> I suspect that there is still some room for improvements in that function, but I don't think that will bring any diffs.
> 
> E.g. `IsMoreSpecific(Foo<ClassA>, Foo<ClassB>)`

The contract for `IsMoreSpecific` is vague: it is trying to inform the JIT about which type might lead to more specific answers to other queries. In general, we expect the types passed to it to be assignment compatible since they are different views of the same underlying type (which may not be known).

File: src/coreclr/vm/jitinterface.cpp [hunk 3]
```diff
@@ -4363,15 +4363,15 @@ static BOOL isMoreSpecificTypeHelper(TypeHandle hnd1, TypeHandle hnd2)
...
+    if (!hnd1.IsTypeDesc() && !hnd2.IsTypeDesc() &&
+        hnd1.AsMethodTable()->HasSameTypeDefAs(hnd2.AsMethodTable()))
     {
-        // Only one of hnd1 and hnd2 is shared.
-        // hdn2 is more specific if hnd1 is the shared type.
-        return isHnd1CanonSubtype;
+        return isHnd1CanonSubtype && !isHnd2CanonSubtype;
     }
 
     // Otherwise both types are either shared or not shared.
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:4377]: This comment is no longer accurate.

File: src/coreclr/vm/jitinterface.cpp [hunk 4]
```diff
@@ -4363,15 +4363,15 @@ static BOOL isMoreSpecificTypeHelper(TypeHandle hnd1, TypeHandle hnd2)
         return FALSE;
     }
 
-    // If we have a mixture of shared and unshared types,
-    // consider the unshared type as more specific.
     BOOL isHnd1CanonSubtype = hnd1.IsCanonicalSubtype();
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:4366]: This can be moved inside the if check. You only need to compute these values if they are used.

**Comment by jkotas** [comment]
Do you see any negative diffs from this change? 

I would expect it to improve code quality of some cases and regress some other cases.

**Comment by AndyAyersMS** [comment]
Size-increasing diffs from PMI [here](https://gist.github.com/MihuBot/e1e79f82b91b77c906e250d951850711).

The no covariance check path is a bit bigger, the jit has to materialize the address, bounds check and then call the write barrier helper.

File: src/coreclr/vm/jitinterface.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/vm/jitinterface.cpp]: Addressed

File: src/coreclr/vm/jitinterface.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/vm/jitinterface.cpp]: Addressed

**Comment by EgorBo** [comment]
Right, full report is https://github.com/MihuBot/runtime-utils/issues/584
Presumably, improvements are when bound checks are removed by rangecheck and we end up not needing a write-barrier (mostly for string literals).

**Comment by jkotas** [comment]
Are there any cases where the change in `IsMoreSpecific` results in slower code?

**Comment by EgorBo** [comment]
> Are there any cases where the change in `IsMoreSpecific` results in slower code?

@jkotas just checked locally - only 10 diffs across all `--frameworks` libs and it seems that all are size improvements since the previous change could incorrectly say that a baseclass (or abstract/interface) is more specific than its shared-generic subclass.

**Comment by jakobbotsch** [comment]
@EgorBot -arm64 -intel
```
using BenchmarkDotNet.Attributes;

public sealed class Bench
{
    Bench _bench = new Bench();
    List<Bench> _list = new() { null };

    [Benchmark]
    public void Test() => _list[0] = _bench;
}
```

**Comment by EgorBo** [comment]
@jakobbotsch BDN doesn't support `sealed` classes (and my bot still has a room for improvements for error reporting)

**Comment by jakobbotsch** [comment]
@EgorBo Ah.. just wanted to see how big the benefit is when we retain the write barrier. Let me just change the string benchmark slightly

**Comment by EgorBo** [comment]
@EgorBot -intel -arm64
```cs
using BenchmarkDotNet.Attributes;
using System.Collections.Generic;

public sealed class SealedClass {}

public class Bench
{
    SealedClass _bench = new();
    List<SealedClass> _list = new() { null };

    [Benchmark]
    public void Test() => _list[0] = _bench;
}
```

**Comment by jkotas** [comment]
> The contract for IsMoreSpecific is vague: it is trying to inform the JIT about which type might lead to more specific answers to other queries. 

Right. A better name for this method would be `isLikelyMoreSpecificType`. It is not always possible to decide which one of two types is more specific. The JIT should produce correct code even if this method returns a random number.

> @jkotas just checked that change only - only 10 diffs across all --frameworks libs and it seems that all are size improvements

Thanks for checking. In case there are any cases that end up producing worse code, they must be very rare.

The VM change LGTM.

File: src/coreclr/jit/ee_il_dll.hpp [hunk 5]
```diff
@@ -78,9 +78,18 @@ bool Compiler::eeIsFieldStatic(CORINFO_FIELD_HANDLE fldHnd)
...
 FORCEINLINE
-var_types Compiler::eeGetFieldType(CORINFO_FIELD_HANDLE fldHnd, CORINFO_CLASS_HANDLE* pStructHnd)
+var_types Compiler::eeGetFieldType(CORINFO_FIELD_HANDLE  fldHnd,
+                                   CORINFO_CLASS_HANDLE* pStructHnd,
+                                   CORINFO_CLASS_HANDLE  memberParent)
 {
-    return JITtype2varType(info.compCompHnd->getFieldType(fldHnd, pStructHnd));
+    // memberParent is an opportunistic hint to get a more exact field type
+    if ((memberParent != NO_CLASS_HANDLE) &&
+        !info.compCompHnd->isMoreSpecificType(info.compCompHnd->getFieldClass(fldHnd), memberParent))
```
Comment (jkotas) [inline src/coreclr/jit/ee_il_dll.hpp:87]: This looks suspect. What's the problem with passing the hint to `getFieldType` unconditionally?

Comment (EgorBo) [reply src/coreclr/jit/ee_il_dll.hpp]: > This looks suspect. What's the problem with passing the hint to `getFieldType` unconditionally?

`getFieldType` uses that argument for validation purposes and requires it to be actual owner or its subclass. I've added a validation loop in my latest commits - I presume we can also modify JIT-EE interface and duplicate the same loop in both runtimes so the jit side change looks better?

Comment (jkotas) [reply src/coreclr/jit/ee_il_dll.hpp]: What are the cases when we reject the hint? Can the hint be completely bogus type; or is the worse-case scenario that the hint is `Canon` instantiation instead of actual generic instantiation?

Comment (EgorBo) [reply src/coreclr/jit/ee_il_dll.hpp]: > What are the cases when we reject the hint? Can the hint be completely bogus type; or is the worse-case scenario that the hint is `Canon` instantiation instead of actual generic instantiation?

For the hint we call our main work-horse `gtGetClassHandle(GenTree*)` for an object representing an instance of the class with the field, so it can report something generic like `System.Object` or even an interface so without any validation `getFieldType` will fail.

So the loop I pushed will make sure the hinted type actually contains the field and `isMoreSpecific` is used just to ignore cases where `gtGetClassHandle(GenTree*)` fails to determine the exact class of the field owner.

**Comment by EgorBo** [comment]
@EgorBot -ampere -graviton4 -perf --envvars DOTNET_JitDisasm:Test
```cs
using BenchmarkDotNet.Attributes;
using System.Collections.Generic;

public class Bench
{
    List<string> _list = new() { null };

    [Benchmark]
    public void Test() => _list[0] = "hi";
}
```

File: src/coreclr/jit/ee_il_dll.hpp (hunk 5 above)
Comment (jkotas) [reply src/coreclr/jit/ee_il_dll.hpp]: Field handles are shared between Canon and specific instantiations in the CoreCLR runtime type system and only for instance fields. I do not think that the validation will work as expected in AOT compilers. 

The validation is very expensive compared to what it does. The same check can be 100x cheaper if done on the VM side directly.

Also, is the current implementation leaving some cases on the table? Consider this:
```
class A<T> { T _aField; }
class B : A<string> { }
```
Is it possible to end up with `B` as the hint type for `_aField`?

**Comment by EgorBo** [comment]
@EgorBot -ampere -graviton4 -profiler --envvars DOTNET_JitDisasm:Test
```cs
using BenchmarkDotNet.Attributes;
using System.Collections.Generic;

public class Bench
{
    List<string> list = [""];

    [Benchmark]
    public void Test() => list[0] = "hi";
}
```

File: src/coreclr/jit/ee_il_dll.hpp (hunk 5 above)
Comment (EgorBo) [reply src/coreclr/jit/ee_il_dll.hpp]: @jkotas I ended up moving logic to `getTypeFIeld` VM API. It looks like the 3rd argument was only used in 2 places (I think both were written by me) so it looks like it's fine to relax the argument to a potentially an invalid hint

File: src/coreclr/vm/jitinterface.cpp [hunk 6]
```diff
@@ -9183,10 +9179,52 @@ CorInfoType CEEInfo::getFieldTypeInternal (CORINFO_FIELD_HANDLE fieldHnd,
...
+            bool isValidParent = false;
+            if (!hintedFieldOwner.IsTypeDesc())
+            {
+                // Now we need to check whether hinted ownerTh is an actual
+                // subclass of fieldsOwner.
+
+                MethodTable* hintedFieldOwnerParent = hintedFieldOwner.AsMethodTable();
+                while (hintedFieldOwnerParent != nullptr)
+                {
+                    if (hintedFieldOwnerParent->HasSameTypeDefAs(actualFieldsOwner))
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:9200]: You can call `MethodTable::GetMethodTableMatchingParentClass` instead (it does the same loop).

File: src/coreclr/vm/jitinterface.cpp [hunk 7]
```diff
@@ -9183,10 +9179,52 @@ CorInfoType CEEInfo::getFieldTypeInternal (CORINFO_FIELD_HANDLE fieldHnd,
 
         SigPointer ptr(sig, sigCount);
 
+        // Actual field's owner
+        MethodTable* actualFieldsOwner = field->GetApproxEnclosingMethodTable();
+
+        // Potentially, a more specific field's owner (hint)
+        TypeHandle hintedFieldOwner = TypeHandle(owner);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:9186]: We should rename the method argument

File: src/coreclr/jit/ee_il_dll.hpp (hunk 5 above)
Comment (jkotas) [reply src/coreclr/jit/ee_il_dll.hpp]: Looks good to me.

File: src/coreclr/vm/jitinterface.cpp (hunk 7 above)
Comment (EgorBo) [reply src/coreclr/vm/jitinterface.cpp]: Renamed

File: src/coreclr/vm/jitinterface.cpp (hunk 6 above)
Comment (EgorBo) [reply src/coreclr/vm/jitinterface.cpp]: Thanks! Switched to it

**Comment by EgorBo** [comment]
@jkotas does it look better now? It seems that R2R/NAOT don't use "fieldOwner" arg at all and manage to successfully generate expected code for my code example as is 😐

File: src/coreclr/vm/jitinterface.cpp [hunk 8]
```diff
@@ -9183,10 +9179,37 @@ CorInfoType CEEInfo::getFieldTypeInternal (CORINFO_FIELD_HANDLE fieldHnd,
...
+                isHintValid = TypeHandle(actualFieldsOwner).IsCanonicalSubtype() &&
+                    !hintedFieldOwner.IsCanonicalSubtype();
+            }
+            else if (hintedFieldOwnerParent->GetMethodTableMatchingParentClass(actualFieldsOwner) != nullptr)
+            {
+                // Otherwise, use hintedFieldOwner only if it's a subclass of actualFieldsOwner
+                isHintValid = true;
+            }
+        }
+        hintedFieldOwner = isHintValid ? hintedFieldOwner : TypeHandle();
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:9207]:
```suggestion
        TypeHandle moreExactFieldOwner = TypeHandle();
        if (!hintedFieldOwner.IsNull() && !hintedFieldOwner.IsTypeDesc())
        {
            MethodTable* matchingHintedFieldOwner = hintedFieldOwner.AsMethodTable()->GetMethodTableMatchingParentClass(actualFieldsOwner);
            if (matchingHintedFieldOwner != NULL)
            {
                // we take matchingHintedFieldOwner only if actualFieldsOwner is shared and matchingHintedFieldOwner
                // is not, hence, it's definitely more exact.
                if (actualFieldsOwner->IsSharedByGenericInstantiations() &&
                    !matchingHintedFieldOwner->IsSharedByGenericInstantiations())
                {
                    moreExactFieldOwner  = matchingHintedFieldOwner;
                }
            }
        }
```
Should this be more like this? I do not think it makes sense to make a distinction between matching type and matching parent type. We should take either of those cases only if the hint is more exact.

File: src/coreclr/vm/jitinterface.cpp [hunk 9]
```diff
@@ -9183,10 +9179,37 @@ CorInfoType CEEInfo::getFieldTypeInternal (CORINFO_FIELD_HANDLE fieldHnd,
...
+
         // For verifying code involving generics, use the class instantiation
         // of the optional owner (to provide exact, not representative,
         // type information)
-        SigTypeContext typeContext(field, (TypeHandle)owner);
+        SigTypeContext typeContext(field, hintedFieldOwner);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:9212]:
```suggestion
        SigTypeContext typeContext(field, moreExactFieldOwner);
```

**Comment by jkotas** [comment]
> It seems that R2R/NAOT don't use "fieldOwner" arg at all and manage to successfully generate expected code for my code example as is 

Are you able to construct a test case for the situation where we need to find a matching parent of the hint? Does this case work in AOT compilers too?

File: src/coreclr/vm/jitinterface.cpp [hunk 10]
```diff
@@ -9183,10 +9179,33 @@ CorInfoType CEEInfo::getFieldTypeInternal (CORINFO_FIELD_HANDLE fieldHnd,
...
+        {
+            MethodTable* matchingHintedFieldOwner = hintedFieldOwner.AsMethodTable()->GetMethodTableMatchingParentClass(actualFieldsOwner);
+            if (matchingHintedFieldOwner != NULL)
+            {
+                // we take matchingHintedFieldOwner only if actualFieldsOwner is shared and matchingHintedFieldOwner
+                // is not, hence, it's definitely more exact.
+                if (actualFieldsOwner->IsSharedByGenericInstantiations() &&
+                    !matchingHintedFieldOwner->IsSharedByGenericInstantiations())
+                {
+                    moreExactFieldOwner  = matchingHintedFieldOwner;
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:9200]:
```suggestion
                    moreExactFieldOwner = matchingHintedFieldOwner;
```

**Review by jkotas — APPROVED** [review]
LGTM. Thanks!
