### PR TITLE
[RuntimeAsync] Respect IsFlowSuppressed when capturing execution context for suspension.

### LINKED ISSUE #122052: [RuntimeAsync] Runtime Async may not honor ExecutionContext.SuppressFlow().
Flowing execution context when it is suppressed is observable. One purpose for suppressing could be hiding secrets, although most commonly the flow is suppressed for performance reasons.

Not reacting to suppression may result in failures like:

```
    System.Net.Sockets.Tests.ExecutionContextFlowTest.SocketAsyncEventArgs_ExecutionContextFlowsAcrossSendAsyncOperation(suppressContext: True, sendMode: 2) [FAIL]
      Assert.Equal() Failure: Values differ
      Expected: 0
      Actual:   42
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/ExecutionContextFlowTest.cs(345,0): at System.Net.Sockets.Tests.ExecutionContextFlowTest.SocketAsyncEventArgs_ExecutionContextFlowsAcrossSendAsyncOperation(Boolean suppressContext, Int32 sendMode)
        /_/src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.CoreCLR.cs(478,0): at System.Runtime.CompilerServices.AsyncHelpers.RuntimeAsyncTaskCore.DispatchContinuations[T,TOps](T task)
        --- End of stack trace from previous location ---
        --- End of stack trace from previous location ---
  Finished:    System.Net.Sockets.Tests
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #122052

=== async1 counterpart:

Regular/synchronous Capture/Restore of execution context should work unconditionally.

https://github.com/dotnet/runtime/blob/aa500a46758c21af99cb8970bf16a5e34b7fb9d2/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs#L30-L33

But captures on the suspension code path use `ExecutionContext.Capture`, that does not capture if the current context suppresses the flow.

https://github.com/dotnet/runtime/blob/aa500a46758c21af99cb8970bf16a5e34b7fb9d2/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs#L158-L167

### CODE REVIEW

File: src/coreclr/inc/clrconfigvalues.h [hunk 1]
```diff
@@ -710,7 +710,7 @@ RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableRiscV64Zbb,             W("EnableRiscV64
 #endif
 
 // Runtime-async
-RETAIL_CONFIG_DWORD_INFO(UNSUPPORTED_RuntimeAsync, W("RuntimeAsync"), 0, "Enables runtime async method support")
+RETAIL_CONFIG_DWORD_INFO(UNSUPPORTED_RuntimeAsync, W("RuntimeAsync"), 1, "Enables runtime async method support")
```
Comment (VSadov) [inline src/coreclr/inc/clrconfigvalues.h]: TODO: undo enabling of async/tests before merging

File: src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.CoreCLR.cs [hunk 2]
```diff
@@ -775,10 +781,19 @@ private static ValueTask ValueTaskFromException(Exception ex)
...
         private static ExecutionContext? CaptureExecutionContext()
         {
-            return Thread.CurrentThreadAssumedInitialized._executionContext;
+            ExecutionContext? executionContext = Thread.CurrentThreadAssumedInitialized._executionContext;
+            if (executionContext?.m_isFlowSuppressed == true)
+            {
+                // 'null' is the internal representation of default execution
+                // context that contains no variables.
+                executionContext = null;
+            }
```
Comment (jakobbotsch) [inline src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.CoreCLR.cs]: `ExecutionContext.Capture` does something else, returning `ExecutionContext.Default` when the current execution context is null. Do we need to respect that?

File: src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs [hunk 3]
```diff
@@ -24,7 +24,7 @@ public sealed class ExecutionContext : IDisposable, ISerializable
 
         private readonly IAsyncLocalValueMap? m_localValues;
         private readonly IAsyncLocal[]? m_localChangeNotifications;
-        private readonly bool m_isFlowSuppressed;
+        internal readonly bool m_isFlowSuppressed;
```
Comment (jakobbotsch) [inline src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs]: This would not be necessary if we used `ExecutionContext.Capture`.

**Review by jakobbotsch — APPROVED** [review]
Do we have a targeted test for this?

File: src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.CoreCLR.cs (hunk 2 above)
Comment (VSadov) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.CoreCLR.cs]: `ExecutionContext.Capture` has many callers with different purposes. For our purpose we only need to match what the AsyncStateMachineBox does. It looks like it stores whatever comes from `ExecutionContext.Capture` as-is, but when it comes to restoring it to a thread, all the paths check for `Default` and replace with `null`.

```cs
            private void MoveNext(Thread? threadPoolThread)
            {
                Debug.Assert(!IsCompleted);

                bool loggingOn = TplEventSource.Log.IsEnabled();
                if (loggingOn)
                {
                    TplEventSource.Log.TraceSynchronousWorkBegin(this.Id, CausalitySynchronousWork.Execution);
                }

                ExecutionContext? context = Context;
                if (context == null)
                {
                    Debug.Assert(StateMachine != null);
                    StateMachine.MoveNext();
                }
                else
                {
                    if (threadPoolThread is null)
                    {
                        ExecutionContext.RunInternal(context, s_callback, this);
                    }
                    else
                    {
                        ExecutionContext.RunFromThreadPoolDispatchLoop(threadPoolThread, context, s_callback, this);
                    }
                }
```

Both `ExecutionContext.RunInternal` and `RunFromThreadPoolDispatchLoop` have code that is:

```cs
            if (executionContext != null && executionContext.m_isDefault)
            {
                // Default is a null ExecutionContext internally
                executionContext = null;
            }
```

or

```cs
            // ThreadPool starts on Default Context so we don't need to save the "previous" state as we know it is Default (null)

            // Default is a null ExecutionContext internally
            if (executionContext != null && !executionContext.m_isDefault)
            {
                // Non-Default context to restore
                RestoreChangedContextToThread(threadPoolThread, contextToRestore: executionContext, currentContext: null);
            }
```

I think `AsyncStateMachineBox` could also store `null` for Default.

In fact, if we stored the result of `ExecutionContext.Capture`, we would need compensating code when restoring. Otherwise we hit asserts/crashes in a few places that expect an invariant "if context is not `null`, there must be variables in it".

Comment (VSadov) [reply src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncHelpers.CoreCLR.cs]: I’ll add an internal helper for async capture and use in AsyncStateMachineBox as well.

**Comment by VSadov** [comment]
added some test scenarios. @jakobbotsch @davidwrighton - PTAL. Thanks!

File: src/tests/async/execution-context/execution-context.cs [hunk 4]
```diff
@@ -13,6 +13,7 @@ public class Async2ExecutionContext
     public static void TestEntryPoint()
     {
         Test().GetAwaiter().GetResult();
+        TestNoFlowOuter().GetAwaiter().GetResult();
```
Comment (jakobbotsch) [inline src/tests/async/execution-context/execution-context.cs:21]: Add a new `[Fact]` for this test?

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs [hunk 5]
```diff
@@ -155,7 +155,7 @@ private static IAsyncStateMachineBox GetStateMachineBox<TStateMachine>(
             [NotNull] ref Task<TResult>? taskField)
             where TStateMachine : IAsyncStateMachine
         {
-            ExecutionContext? currentContext = ExecutionContext.Capture();
+            ExecutionContext? currentContext = ExecutionContext.CaptureForSuspension(Thread.CurrentThread);
```
Comment (jakobbotsch) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:158]: What about the non-T version of this?

Also cc @stephentoub

**Comment by VSadov** [comment]
Hold on. There are testcase failures in Libraries now.  
I think I missed the subtle part that when the flow is suppressed, it does not mean "if capturing, capture default", which would make sense to me, it actually means "if restoring, do not restore". 

The result is different if running a callback with an already dirty context. 

That is why the `Capture` does its weird thing. 

When context is applied to a thread, `null` means default state with no variables, but in the captured state `null` becomes `Default` (and when applied to a thread will clear its context), but suppressed context is captured as `null` and cause the callback to run without restoring at all.

**Comment by VSadov** [comment]
Basically, suppressing context flow will result in callback executing in a nondeterministic context that may depend on implementation details. (i.e. did we switch threads or ran "inline",...)

Indeed, the following produces randomly different output:

```cs
    internal class Program
    {
        static void Main(string[] args)
        {
            TestNoFlowOuter().GetAwaiter().GetResult();
        }

        public static AsyncLocal<long?> s_local = new AsyncLocal<long?>();

        private static async Task TestNoFlowOuter()
        {
            s_local.Value = 7;
            await TestNoFlowInner();
            System.Console.WriteLine(s_local.Value);
        }

        private static async Task TestNoFlowInner()
        {
            ExecutionContext.SuppressFlow();

            s_local.Value = 42;
            // returns synchronously, context stays the same.
            await ChangeThenReturn();
            System.Console.WriteLine(s_local.Value);

            // returns asynchronously, context should not flow.
            await ChangeYieldThenReturn();

// The following may print either False or True;
// I see mostly True in Debug, but sometimes False.
// In Release I see False, but would not be surprised if sometimes it prints True

            System.Console.WriteLine(s_local.Value == null); 
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static async Task ChangeThenReturn()
        {
            s_local.Value = 123;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static async Task ChangeYieldThenReturn()
        {
            s_local.Value = 123;
            // restore flow so that state is not cleared by Yield
            ExecutionContext.RestoreFlow();
            await Task.Yield();
            System.Console.WriteLine(s_local.Value);
        }
    }
```

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs (hunk 5 above)
Comment (VSadov) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:158]: non-T versions internally delegate to `Task<VoidTaskResult>`, same for `ValueTask` and `ValueTask<T>`

**Comment by VSadov** [comment]
Using `null` as a sentinel for flow-suppressed contexts would force us to map `null` to `Default` and then map back the `Default` to `null` and that is a per-frame expense that can add up. 

I'll try using some other sentinel, so that the most common case, when the context is `null`, could be captured/restored as-is.

**Comment by VSadov** [comment]
The failures seem to be: https://github.com/dotnet/runtime/issues/122228

**Comment by VSadov** [comment]
failures in Cryptography.Tests.MLKemImplementationTests are #122228

File: src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs [hunk 6]
```diff
@@ -403,7 +403,7 @@ public void MoveNext()
             {
                 ExecutionContext? context = Context;
 
-                if (context is null)
+                if (context == ExecutionContext.DefaultFlowSuppressed)
```
Comment (stephentoub) [inline src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:406]: Are there still cases where context is null? If so, those will now end up taking the more expensive ExecutionContext.RunInternal path?

Comment (VSadov) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:406]: The `null` context on this code path used to represent "no flow", while "default" was represented as `Default` context. Thus `no flow`/`null` was resulting in direct execution of MoveNext, while `Default` was sent to `ExecutionContext.RunInternal` where the `Default` would be remapped back to `null` as outside of suspend/resume the "default" context is represented as `null`.

Now, if we see `null` here it is the actual `null` that represents the default state. It will go into `ExecutionContext.RunInternal` where it will be treated as "default" with fewer checks.

Comment (VSadov) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:406]: Basically - between   the "default" and "no flow" cases we should take the same codepaths as before - "no flow" results in calling MoveNext directly and "default" calls  `ExecutionContext.RunInternal`.

The differences are:
- while in the captured state the representation has changed. 
"no flow" was `null` and now `DefaultFlowSuppressed`
"default" was `Default` and now `null`

- when calling `ExecutionContext.RunInternal` on the resume path
"default" was represented by `Default` and was remapped back to `null` inside `ExecutionContext.RunInternal`,  
now "default" simply goes in as already `null` and needs fewer branches inside `ExecutionContext.RunInternal`

Comment (VSadov) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:406]: For async1 this removes couple branches on suspend/resume path, which is likely a microimprovement which will not matter, but also makes things less confusing. 
 
For runtime async the "microimprovement" is more noticeable as using `null` to mean "default" regardless of suspend/resume or save/restore scenario allows to not specialcase `Default` at all. 

In runtime async these codepaths are completely internal and always pick up contexts from a thread and apply to a thread, thus we can only specialcase `DefaultFlowSuppressed` and only on suspend/resume codepath as it has special `noop` meaning for resume. Otherwise, we always apply to a thread whatever we've picked up from a thread, so we do not need to be in the business of normalizing the default state into `null`. 
Runtime async does not have a codepath where the exec context comes directly from the user via calling some API.

Comment (VSadov) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:406]: > Are there still cases where context is null? If so, those will now end up taking the more expensive ExecutionContext.RunInternal path?

Basically - Yes there are scenarios where the context is `null`, but they match scenarios where we previously had `Default`, and should not be more expensive than before. Perhaps slightly cheaper.

Comment (stephentoub) [reply src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:406]: Ok

**Comment by VSadov** [comment]
@stephentoub - Thanks!
