### PR TITLE
Fix race condition between GCInfo and Rundown

### LINKED ISSUE #69375: tracing/eventpipe/eventsvalidation tests failing with AF:  codeLength > 0
Hit in https://github.com/dotnet/runtime/pull/69360#issuecomment-1126828635:
```
     Assert failure(PID 5146 [0x0000141a], Thread: 5148 [0x141c]): codeLength > 0
          File: /__w/1/s/src/coreclr/vm/eetwain.cpp Line: 5880
          Image: /root/helix/work/correlation/corerun
      
      /root/helix/work/workitem/e/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1/ExceptionThrown_V1.sh: line 408:  5146 Aborted                 (core dumped)
```
Based on the investigation below, this assert is just one of the possible failure modes of this test due this bug. Any crash or AF with `ETW::MethodLog::SendEventsForJitMethods` on stack is potentially caused by this bug.

### PR DESCRIPTION
**Pull request by davmason**
Fixes #69375

* Adds a check to see if the GCInfo is published yet before trying to emit a rundown event
* Published GCInfo under the code heap crst so we can only see an uninitialized GCInfo or a complete one
* Moved the freeing of the temporary code heaps in LCG methods to after we call FreeCodeMemory so we don't race on deletion

### CODE REVIEW

**Comment by davmason** [comment]
@jkotas Looking at the prior art, it seems like `EEJitManager` is a good place to put this sort of logic. Is that right? 

Then `CEEJitInfo::WriteCode` can call `EEJitManager::PublishGCInfo` and it can take the code heap lock, and everything is all good - in rundown we can check and either get fully published GCInfo or uninitialized and skip it.

**Comment by jkotas** [comment]
> @jkotas Looking at the prior art, it seems like EEJitManager is a good place to put this sort of logic. Is that right?

Yep.

**Comment by davmason** [comment]
With the test app below it would hit asserts on a checked build within a minute before, and I have run it for an hour or so with no issue now on windows x64. On x86 it runs out of memory after ~25k dynamic methods, but works fine up until then.

I am going to run it against linux arm32 to make sure, but I have no reason to suspect it will be any different there

```

using Microsoft.Diagnostics.NETCore.Client;
using Microsoft.Diagnostics.Tracing;
using System.Diagnostics;
using System.Diagnostics.Tracing;
using System.Reflection;
using System.Reflection.Emit;

Console.WriteLine("Hello, World!");

long numDynamicMethods = 0;
List<Thread> threads = new List<Thread>();
int numThreads = 100;
for (int i = 0; i < numThreads; i++)
{
    Thread t = new Thread(MakeDynamicMethods);
    t.Start();
    threads.Add(t);
}

Thread gcTriggerThread = new Thread(() =>
    {
        while (true)
        {
            Thread.Sleep(100);
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }
    });

gcTriggerThread.Start();
threads.Add(gcTriggerThread);

while (true)
{
    Console.WriteLine($"New EventPipe session, dynamic methods={numDynamicMethods}");

    int processId = Process.GetCurrentProcess().Id;
    DiagnosticsClient client = new DiagnosticsClient(processId);

    int numEvents = 0;
    List<EventPipeProvider> providers = new List<EventPipeProvider>()
    {
        new EventPipeProvider("Microsoft-Windows-DotNETRuntime", EventLevel.Verbose),
        new EventPipeProvider("Microsoft-Windows-DotNETRuntimeRundown", EventLevel.Verbose),
        new EventPipeProvider("Microsoft-DotNETCore-SampleProfiler", EventLevel.Verbose),
    };
    using (EventPipeSession session = client.StartEventPipeSession(providers, /* requestRunDown */ true))
    { 
        EventPipeEventSource source = new EventPipeEventSource(session.EventStream);
        source.Dynamic.All += (TraceEvent traceEvent) =>
        {
            ++numEvents;
        };

        Thread processingThread = new Thread(new ThreadStart(() =>
        {
            source.Process();
            Console.WriteLine($"Saw {numEvents} events.");
        }));
        processingThread.Start();

        Thread.Sleep(100);

        // The events are fired in the JITCompilationStarted callback for TriggerMethod,
        // so by the time we are here, all events should be fired.
        session.Stop();

        processingThread.Join();
    }
}

void MakeDynamicMethods(object? obj)
{
    Random random = new Random();
    while (true)
    {
        AssemblyName name = new AssemblyName(GetRandomName());
        AssemblyBuilder dynamicAssembly = AssemblyBuilder.DefineDynamicAssembly(name, AssemblyBuilderAccess.RunAndCollect);
        ModuleBuilder dynamicModule = dynamicAssembly.DefineDynamicModule(GetRandomName());

        Type[] methodArgs = { typeof(int) };

        DynamicMethod squareIt = new DynamicMethod(
            "SquareIt",
            typeof(long),
            methodArgs,
            dynamicModule);

        ILGenerator il = squareIt.GetILGenerator();
        il.Emit(OpCodes.Ldarg_0);
        il.Emit(OpCodes.Conv_I8);
        il.Emit(OpCodes.Dup);
        il.Emit(OpCodes.Mul);
        il.Emit(OpCodes.Ret);

        OneParameter<long, int> invokeSquareIt =
            (OneParameter<long, int>)
            squareIt.CreateDelegate(typeof(OneParameter<long, int>));

        invokeSquareIt(random.Next());

        Interlocked.Increment(ref numDynamicMethods);
    }
}

static string GetRandomName()
{
    return Guid.NewGuid().ToString();
}

delegate long SquareItInvoker(int input);

delegate TReturn OneParameter<TReturn, TParameter0>
    (TParameter0 p0);

```

File: src/coreclr/vm/eventtrace.cpp [hunk 1]
```diff
@@ -6655,6 +6655,29 @@ VOID ETW::MethodLog::SendMethodEvent(MethodDesc *pMethodDesc, DWORD dwEventOptio
     // by a TADDR (i.e., w/out thumb bit set on ARM)
     EECodeInfo codeInfo(start);
 
+    // We can race with the JIT publishing GCInfo, if it is not published we can skip this method since
+    // it is not in use yet.
+#ifdef TARGET_X86
+    hdrInfo  gcInfo;
+    DecodeGCHdrInfo(codeInfo.GetGCInfoToken(),
```
Comment (jkotas) [inline src/coreclr/vm/eventtrace.cpp:6662]: Should this rather check for NULL GetGCInfoToken? I do not think we should be attempting to decode the GC info that has not been published.

Comment (jkotas) [reply src/coreclr/vm/eventtrace.cpp:6662]: Or maybe this change is not needed with the new approach?

File: src/coreclr/vm/jitinterface.cpp [hunk 2]
```diff
@@ -10970,6 +10970,12 @@ void CEEJitInfo::WriteCode(EEJitManager * jitMgr)
     UnwindInfoTable::PublishUnwindInfoForMethod(m_moduleBase, m_CodeHeader->GetUnwindInfo(0), m_totalUnwindInfos);
 #endif // defined(TARGET_AMD64)
 
+    {
+        ExecutableWriterHolder<BYTE *> gcInfoWriterHolder(m_CodeHeader->GetGCInfoAddr(), sizeof(void *));
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:10974]: `ExecutableWriterHolder` is not a cheap operation. `WriteCodeBytes` has one already. Can we refactor such that we have just one ExecutableWriterHolder for both operations?

File: src/coreclr/vm/codeman.cpp [hunk 3]
```diff
@@ -3215,21 +3215,22 @@ BYTE* EEJitManager::allocGCInfo(CodeHeader* pCodeHeader, DWORD blockSize, size_t
     } CONTRACTL_END;
 
     MethodDesc* pMD = pCodeHeader->GetMethodDesc();
```
Comment (jkotas) [inline src/coreclr/vm/codeman.cpp:3217]: You can just pass in the `MethodDesc` instead of the whole `CodeHeader`. This method does not need the `CodeHeader` anymore.

File: src/coreclr/vm/jitinterface.cpp [hunk 4]
```diff
@@ -12131,17 +12135,15 @@ void * CEEJitInfo::allocGCInfo (size_t size)
     }
 #endif // HOST_64BIT
 
-    block = m_jitManager->allocGCInfo(m_CodeHeaderRW,(DWORD)size, &m_GCinfo_len);
-    if (!block)
+    m_pGCInfo = m_jitManager->allocGCInfo(m_CodeHeaderRW,(DWORD)size, &m_GCinfo_len);
+    if (!m_pGCInfo)
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:12139]: This should not be needed. `allocGCInfo` throws on OOM.

**Comment by tommcdon** [comment]
@davmason is this PR still active or should we move to draft mode?

**Comment by davmason** [comment]
> @davmason is this PR still active or should we move to draft mode?

Still active, just didn't finish it before I took vacation

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by jkotas** [comment]
The test failure is https://github.com/dotnet/runtime/issues/70450
