### PR TITLE
JIT: Handle async calls implemented via `ldvirtftn` properly

### LINKED ISSUE #118714: [RuntimeAsync] Possible issue with async GVMs
It may be similar to #117266, but I think it is a separate issue.

The repro (need to run with RT async enabled):

```cs
    interface I2
    {
        Task<string> M0<T>();
        Task<string> M1<T>(object a0, object a1, object a2, object a3, object a4, object a5, object a6, object a7, object a8);
    }

    class Class2 : I2
    {
        public async Task<string> M0<T>()
        {
            await Task.Yield();
            return typeof(T).ToString();
        }

        public async Task<string> M1<T>(object a0, object a1, object a2, object a3, object a4, object a5, object a6, object a7, object a8)
        {
            await Task.Yield();
            return typeof(T).ToString();
        }
    }

    static I2 o2;
    static async Task<string> CallClass2M0()
    {
        o2 = new Class2();
        return await o2.M0<string>();
    }

    static async Task<string> CallClass2M1()
    {
        o2 = new Class2();
        return await o2.M1<string>(default, default, default, default, default, default, default, default, default);
    }

    [Fact]
    public static void NoArgGVM()
    {
        Assert.Equal("System.String", CallClass2M0().Result);
    }

    [Fact]
    public static void ManyArgGVM()
    {
        Assert.Equal("System.String", CallClass2M1().Result);
    }

```

The repro results in AVs/NullRef exceptions. Even though there is an instantiating stub involved, I think the continuation is trashed earlier - by the managed GVM cache lookup helper.

Although there is a possibility that it is indirectly a problem with the stub.

### PR DESCRIPTION
**Pull request by jakobbotsch**
Handling was missing to mark these as async and to insert async continuations.

Fix #118714

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Opened #118735 to fix the failing test (flakey).

**Comment by jakobbotsch** [comment]
All other failures are known, cc @dotnet/jit-contrib @VSadov PTAL @AndyAyersMS

File: src/coreclr/inc/clrconfigvalues.h [hunk 1]
```diff
@@ -709,7 +709,7 @@ RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableRiscV64Zbb,             W("EnableRiscV64
 #endif
 
 // Runtime-async
-RETAIL_CONFIG_DWORD_INFO(UNSUPPORTED_RuntimeAsync, W("RuntimeAsync"), 0, "Enables runtime async method support")
+RETAIL_CONFIG_DWORD_INFO(UNSUPPORTED_RuntimeAsync, W("RuntimeAsync"), 1, "Enables runtime async method support")
```
Comment (jakobbotsch) [inline src/coreclr/inc/clrconfigvalues.h]: Will make sure to remove this and the Directory.Build.targets change before merging

**Review by AndyAyersMS — APPROVED** [review]

File: src/coreclr/jit/importercalls.cpp [hunk 2]
```diff
@@ -384,8 +384,18 @@ var_types Compiler::impImportCall(OPCODE                  opcode,
...
+                    impSetupAndSpillForAsyncCall(call->AsCall(), opcode, prefixFlags);
+                }
+
                 impPopCallArgs(sig, call->AsCall());
 
+                if (call->AsCall()->IsAsync())
+                {
+                    impInsertAsyncContinuationForLdvirtftnCall(call->AsCall());
+                }
+
```
Comment (VSadov) [inline src/coreclr/jit/importercalls.cpp:398]: So the culprit was the `goto DONE;` below, thus `CORINFO_VIRTUALCALL_LDVIRTFTN` was not going through the codepath that eventually inserts continuation arg for other kinds of calls. Thus this was overlooked.

**Review by VSadov — APPROVED** [review]
LGTM. Thanks!

File: src/coreclr/jit/importercalls.cpp (hunk 2 above)
Comment (jakobbotsch) [reply src/coreclr/jit/importercalls.cpp:398]: Yes, this entire path skips over the rest of the function. Sadly `impImportCall` is quite badly factored.
