### PR TITLE
JIT: fix bug where a gc struct is not zero initialized

### LINKED ISSUE #65694: Memory dump of AccessViolationException on gc_heap::mark_object_simple and  heap corruption
When running our test suite we got a crash: `The process was terminated due to an internal error in the .NET Runtime at IP 00007FFDC50AB5FC (00007FFDC5010000) with exit code 80131506.`:

```
Faulting application name: dotnet.exe, version: 6.0.222.6406, time stamp: 0x61e1d8df
Faulting module name: coreclr.dll, version: 6.0.222.6406, time stamp: 0x61e1d09e
Exception code: 0xc0000005
Fault offset: 0x000000000009b5fc
Faulting process id: 0x22b4
Faulting application start time: 0x01d823e188848226
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.2\coreclr.dll
```

We have configured automatic memory dumps creation which resulted in creating the following memory dump:

https://drive.google.com/file/d/19S1k74Foe9V6A03hRwIuebE42GVQUirI/view?usp=sharing

In our project ([github.com/ravendb/ravendb](https://github.com/ravendb/ravendb)) we use unmanaged memory directly, so it might be that it's because of our code.

The following analysis was made so far in WinDBG.

1. Based on `!analyze -v` I the crashing stacktrace is:

```
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffdc50ab5fc (coreclr!WKS::gc_heap::mark_object_simple+0x000000000000011c)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000001
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000022da7b73000
Attempt to read from address 0000022da7b73000
```

```
coreclr!WKS::gc_heap::mark_object_simple+0x11c
coreclr!WKS::GCHeap::Promote+0x74
coreclr!GcEnumObject+0x76
coreclr!GcInfoDecoder::EnumerateLiveSlots+0x792
coreclr!EECodeManager::EnumGcRefs+0xe9
coreclr!GcStackCrawlCallBack+0x12f
coreclr!Thread::StackWalkFramesEx+0xee
coreclr!Thread::StackWalkFrames+0xae
coreclr!ScanStackRoots+0x7a
coreclr!GCToEEInterface::GcScanRoots+0x9f
coreclr!WKS::gc_heap::mark_phase+0x291
coreclr!WKS::gc_heap::gc1+0x98
coreclr!WKS::gc_heap::garbage_collect+0x1ad
coreclr!WKS::GCHeap::GarbageCollectGeneration+0x14f
coreclr!WKS::gc_heap::trigger_gc_for_alloc+0x2b
coreclr!WKS::gc_heap::try_allocate_more_space+0x5c141
coreclr!WKS::gc_heap::allocate_more_space+0x31
coreclr!WKS::GCHeap::Alloc+0x84
coreclr!JIT_NewArr1+0x4bd
0x00007ffd`778e62c6
0x00007ffd`6f3e3770
0x00007ffd`741c1efb
...
0x00007ffd`67d765da
0x00007ffd`67deeff2
coreclr!CallDescrWorkerInternal+0x83
coreclr!DispatchCallSimple+0x80
coreclr!ThreadNative::KickOffThread_Worker+0x63
coreclr!ManagedThreadBase_DispatchMiddle+0x85
coreclr!ManagedThreadBase_DispatchOuter+0xae
coreclr!ThreadNative::KickOffThread+0x79
kernel32!BaseThreadInitThunk+0x14
ntdll!RtlUserThreadStart+0x21
```

2. The heap is corrupted:

```
0:340> !verifyheap
object 0000022da400fff8: bad member 0000022D04C05821 at 0000022DA4010000
Last good object: 0000022DA400FFE0.
```

3. The last good object is:

```
0:340> !do 0000022DA400FFE0
Name:        Sparrow.Utils.TimeoutManager+<>c__DisplayClass6_0
MethodTable: 00007ffd67a1a6e0
EEClass:     00007ffd67a24988
Tracked Type: false
Size:        24(0x18) bytes
File:        c:\Jenkins\workspace\PR_Tests\s\test\SlowTests\bin\Release\net6.0\Sparrow.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ffd679b44a0  40002eb        8 ...Private.CoreLib]]  0 instance 0000022da4010160 onCancel
```

I see `onCancel` member so it's likely the following from `TimeoutManager.cs`:

```
var onCancel = new TaskCompletionSource<object>(TaskCreationOptions.RunContinuationsAsynchronously);
using (token.Register(tcs => onCancel.TrySetCanceled(), onCancel))
{
}
```

https://github.com/ravendb/ravendb/blob/193624d559fe2e6525cc383de362c83d19aacffd/src/Sparrow/Utils/TimeoutManager.cs#L139

4. Bad object is:

```
0:340> !do 0000022da400fff8
Name:        System.Action`1[[System.Object, System.Private.CoreLib]]
MethodTable: 00007ffd66a69428
EEClass:     00007ffd658f6788
Tracked Type: false
Size:        64(0x40) bytes
File:        C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.2\System.Private.CoreLib.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ffd655a5678  40001ec        8        System.Object  0 instance 0000022d04c05821 _target
00007ffd655a5678  40001ed       10        System.Object  0 instance 0000000000000000 _methodBase
00007ffd65654228  40001ee       18        System.IntPtr  1 instance 00007FFD67569160 _methodPtr
00007ffd65654228  40001ef       20        System.IntPtr  1 instance 0000000000000000 _methodPtrAux
00007ffd655a5678  4000273       28        System.Object  0 instance 0000000000000000 _invocationList
00007ffd65654228  4000274       30        System.IntPtr  1 instance 0000000000000000 _invocationCount
```

It is `System.Action1[[System.Object, System.Private.CoreLib]]` so my suspicion is that it's this action `tcs => onCancel.TrySetCanceled()`.

The attempt to get its `_target` results in:

```
!DumpObj /d 0000022d04c05821
<Note: this object has an invalid CLASS field>
Invalid object
```

The address matches the output of `verifyheap`  - `bad member 0000022D04C05821 at 0000022DA4010000` so we know that the corrupted member is `_target`.

5. I see that in our code we use directly `onCancel` variable in  `tcs => onCancel.TrySetCanceled()` instead of using the callback action: `tcs => ((TaskCompletionSource<object>)tcs).TrySetCanceled()` but effectively it's the same thing. Could it cause any GC problems and result in something like that?

### PR DESCRIPTION
**Pull request by AndyAyersMS**
This fixes an unexpected interaction between the zero-init optimization and
dead stores.

We have a local gc struct that is tracked but not promoted (and so on the
frame) with an explicit zero init.

The zero-init opt determines that in-prolog init is not needed because the
local is tracked and has a live explicit initializer. So it marks the local
as `lvHasExplicitInit`. But subsequent control flow optimizations end up
making the explicit zero init dead, and it is removed by dead stores.

Later on when we report GC info for the struct we report it as untracked. This
leads to the GC seeing an uninitialized stack slot as a GC ref.

The fix is to inhibit dead stores of zero initializers for `lvHasExplicitInit`
(restricted to GC locals with multiple references).

[some alternative fixes were considered, see notes in the PR].

Addresses #65694 (needs backporting for a full fix).

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
we will want to back port this to .net 6.

@BruceForstall PTAL
cc @dotnet/jit-contrib (fyi @erozenfeld)

There are a few problematic aspects. First is that we can do untracked GC reporting for a tracked local. Second is that because of optimizations we can change liveness and so deductions/expectations based in earlier phases might end up getting broken.

In this case the problematic control flow comes from
```c#
            if (_d?.TryGetValue(k, out p) == true && (p.x == 33))
```
Initially the jit sees a path where `p` can be referenced without invoking `TryGetValue`. So the upstream zero init of `p` is live.

The control flow snippet below is from the original repro case. The call to `TryGetValue` is in BB97, and there's a path from the null check of `d` in BB94 down through BB95 and BB96 to the access of the struct field in BB101. This is the state of the flow graph when the zero-init opt runs.

But it turns out that taking the BB94->BB95 path will then result in always taking the BB95->BB102 path; the jit proves this during subsequent optimization phases and removes the path. As a result the upstream zero initializer becomes dead.

image

Some alternative fixes I considered:
* Recognize that despite being tracked this local is going to be reported as untracked, and so treat as case (a) in zero init
* Fix jit so it can report tracked structs on the frame as tracked in the GC info
* (possibly) do dependent promotion for all tracked structs?
* (possibly) don’t track unpromoted structs

Diffs with this change are minimal -- just one method has diffs in SPMI, and the case with diffs does not have the bug (instead it has a local struct with multiple dead references).

Likely the odd control flow setup here is somewhat rare.

File: src/coreclr/jit/liveness.cpp [hunk 1]
```diff
@@ -1988,25 +1988,45 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
...
                             (addrUse.User()->OperIs(GT_STOREIND, GT_STORE_BLK, GT_STORE_OBJ)))
                         {
-                            // Remove the store. DCE will iteratively clean up any ununsed operands.
                             GenTreeIndir* const store = addrUse.User()->AsIndir();
 
-                            JITDUMP("Removing dead indirect store:\n");
-                            DISPNODE(store);
+                            // If this is a zero init of an explicit zero init gc local
+                            // that has at least one other reference, we will keep the zero init.
+                            //
```
Comment (jakobbotsch) [inline src/coreclr/jit/liveness.cpp:1995]: Maybe expand a bit on why? This just seems to be a restatement of the code below.

**Comment by AndyAyersMS** [comment]
Arm64 failures: https://github.com/dotnet/runtime/issues/67821 and one run that failed with no progress on DDARM64-046.

**Comment by erozenfeld** [comment]
Have you considered a solution where you mark an explicit zero initialization with some sort of side effect to prevent its removal if zero-init optimization makes a decision based on the presence of the explicit zero int?

**Comment by erozenfeld** [comment]
Or will that still lead to a problem if we report as untracked?

**Review by erozenfeld — APPROVED** [review]
I think what you have is a good solution.

**Comment by AndyAyersMS** [comment]
> Have you considered a solution where you mark an explicit zero initialization with some sort of side effect to prevent its removal if zero-init optimization makes a decision based on the presence of the explicit zero int?

Yeah, that would be more surgical, but I'm not confident I can find a suitable flag -- we seem to widely assume stores to locals can't have operator/lhs side effects. 

I suppose I could also insert a fake use ala keep alive.

**Comment by BruceForstall** [comment]
> The fix is to inhibit dead stores of zero initializers for lvHasExplicitInit
(restricted to GC locals with multiple references).

Since the JIT decided to report the struct as untracked (it would useful to understand under what conditions this happens), doesn't that invalidate the zeroing optimization assumptions that allowed it to use the in-body zeroing in the first place? I.e., even if you leave the dead in-body zeroing, isn't there a range between the end of the prolog and the in-body zeroing where the struct local is uninitialized and GC could occur? I guess `optRemoveRedundantZeroInits` checks for GC safe points, but I thought offset zero (immediately after the prolog) was always a GC safe point?

**Comment by AndyAyersMS** [comment]
> Since the JIT decided to report the struct as untracked (it would useful to understand under what conditions this happens),

https://github.com/dotnet/runtime/blob/aff3c1867b50d8a021c0a7b1df94f54a40cb44a5/src/coreclr/jit/gcencode.cpp#L4122-L4260

Here we have TYP_STRUCT, which is not a gc type, so we end up at line 4217 and report the GC fields of the struct as untracked.

> I thought offset zero (immediately after the prolog) was always a GC safe point?

Not sure. Empirically that doesn't seem to be the case for partially interruptible methods (if so, the repro above should fail under GCStress=3, but it passes).

The zero init opt "remove prolog" flavor won't kick in for fully interruptible methods.

**Comment by AndyAyersMS** [comment]
> I thought offset zero (immediately after the prolog) was always a GC safe point?

I asked both Jans about this and neither of them thought offset 0 was special either.

File: src/coreclr/jit/liveness.cpp [hunk 2]
```diff
@@ -1988,25 +1988,45 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
...
+                            const LclVarDsc& varDsc              = lvaTable[node->AsLclVarCommon()->GetLclNum()];
+                            const bool       isExplicitInitLocal = varDsc.lvHasExplicitInit;
+                            const bool       isReferencedLocal   = varDsc.lvRefCnt() > 1;
+                            const bool       isZeroInit          = store->OperIsInitBlkOp();
```
Comment (BruceForstall) [inline src/coreclr/jit/liveness.cpp:1999]: Don't you also need to check the init value is actually zero if you only want to avoid deleting only zero inits? E.g., check IsConstInitVal and then the constant init value?

File: src/coreclr/jit/liveness.cpp [hunk 3]
```diff
@@ -1988,25 +1988,45 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
...
 
-                            assert(store->Addr() == node);
-                            blockRange.Delete(this, block, node);
-
-                            GenTree* data =
-                                store->OperIs(GT_STOREIND) ? store->AsStoreInd()->Data() : store->AsBlk()->Data();
-                            data->SetUnusedValue();
-
-                            if (data->isIndir())
+                            if (isExplicitInitLocal && isReferencedLocal && isZeroInit && isGCInit)
```
Comment (BruceForstall) [inline src/coreclr/jit/liveness.cpp:2002]: We don't know if this is the _first_ dead store. E.g., what if the lclVar has multiple zeroing that are dead stores? All of them will be kept even though (probably) only the first was the "explicit init" one as determined by `optRemoveRedundantZeroInits`.

File: src/coreclr/jit/liveness.cpp (hunk 2 above)
Comment (BruceForstall) [reply src/coreclr/jit/liveness.cpp:1999]: Couldn't this problem occur for normal untracked ref/byref lclVar and not just for struct field gc refs reported as untracked to the gc?

i.e., should we stop marking all gc vars or structs with gc fields as explicit init in `optRemoveRedundantZeroInits`?

Comment (AndyAyersMS) [reply src/coreclr/jit/liveness.cpp:1999]: >Don't you also need to check the init value is actually zero 

I suppose so, but this kicks in so rarely it won't matter in practice.

> Couldn't this problem occur for normal untracked ref/byref lclVa

We won't have liveness info for these so won't dead store.

File: src/coreclr/jit/liveness.cpp (hunk 3 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/liveness.cpp:2002]: Right, if there are multiple dead stores we will keep them all.

**Review by BruceForstall — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
@erozenfeld were you going to take another look?

**Comment by erozenfeld** [comment]
> @erozenfeld were you going to take another look?

Yeah, I'll take another look tomorrow.

**Review by erozenfeld — APPROVED** [review]
I reviewed this again and I think this is the right fix.

**Comment by AndyAyersMS** [comment]
Thanks @erozenfeld.
