### PR TITLE
[Android] InvariantGlobalization support for CoreCLR Android builds

### LINKED ISSUE #117270: [Android] `Invariant.Tests.csproj` is failing on CoreCLR Android
### Description

The `System.Globalization.Tests/Invariant/Invariant.Tests.csproj` fails on CoreCLR Android because the invariant-globalization flag isn't propagated to the runtime at startup. The project file contains
```
<InvariantGlobalization>true</InvariantGlobalization>
```
but the CoreCLR initialization code in `monodroid-coreclr.c` does not forward this setting as an appcontext variable, so the runtime never runs in invariant-globalization mode.

### Reproduction Steps

Build the runtime:
```
build.sh -arch arm64 -os android  -s clr.runtime+clr.alljits+clr.corelib+clr.nativecorelib+clr.tools+clr.packages+libs+libs.tests+host+packs -c Release /p:ArchiveTests=true /p:RunSmokeTestsOnly=True
```

Run the apk using Android Studio.

### Expected behavior

The tests pass on the CI: https://dev.azure.com/dnceng-public/public/_build?definitionId=223

### Actual behavior

The tests fail on the CI.

### PR DESCRIPTION
**Pull request by davidnguyen-tech**
## Description

Forward the `InvariantGlobalization` MSBuild property to the CoreCLR runtime for Android applications by connecting the existing infrastructure.

## Related issues

Fixes #117270

### CODE REVIEW

**Comment by davidnguyen-tech** [comment]
@dotnet-policy-service agree company="Microsoft"

File: src/tasks/AndroidAppBuilder/AndroidAppBuilder.cs [hunk 1]
```diff
@@ -108,6 +108,11 @@ public class AndroidAppBuilderTask : Task
 
     public bool ForceInterpreter { get; set; }
 
+    /// <summary>
+    /// Indicates whether we want to use invariant globalization mode.
+    /// </summary>
+    public bool InvariantGlobalization { get; set; }
```
Comment (vitek-karas) [inline src/tasks/AndroidAppBuilder/AndroidAppBuilder.cs:114]: Just curious - why not pass this through `EnvironmentVariables`?
Personally, I probably like this solution a little better, but I don't have many arguments either way.

**Review by kotlarmilos — COMMENTED** [review]
Let's check if the other globalization failures are resolved with this PR. Otherwise, LGTM!

File: src/tasks/AndroidAppBuilder/AndroidAppBuilder.cs (hunk 1 above)
Comment (davidnguyen-tech) [reply src/tasks/AndroidAppBuilder/AndroidAppBuilder.cs:114]: I did consider passing it through `EnvironmentVariables`, as it reuses the existing logic of setting environment variables in `ApkBuilder`. On the other hand, `ApkBuilder` already has a public `InvariantGlobalization` property that some users might rely on, which is why I chose the proposed approach.

Comment (vitek-karas) [reply src/tasks/AndroidAppBuilder/AndroidAppBuilder.cs:114]: Makes sense, thanks.

**Review by kotlarmilos — APPROVED** [review]
LGTM!

**Comment by akoeplinger** [comment]
@davidnguyen-tech @kotlarmilos does this mean coreclr doesn't read the runtimeconfig.json yet? cause it should be set there afaik.

**Comment by akoeplinger** [comment]
I just saw the discussion with @vitek-karas in https://github.com/dotnet/runtime/pull/117542#discussion_r2201137004, I agree that passing this through EnvironmentVariables is better and we can get rid of the workaround once coreclr android supports reading runtimeconfig.json.

The InvariantGlobalization property on ApkBuilder looks like a leftover

**Comment by davidnguyen-tech** [comment]
@akoeplinger I agree - since it seems like nobody's using the property, I will refactor it to be passed through EnvironmentVariables and get rid of the property. Thanks for pointing it out!

**Comment by vitek-karas** [comment]
>we can get rid of the workaround once coreclr android supports reading runtimeconfig.json

Just to clarify - the proper Android hosting from dotnet/android does support this already. The problem is with the simple test host we use in dotnet/runtime. We've discussed this with @davidnguyen-tech and it's probably not worth the effort yet to implement something in the simple test host.

**Comment by akoeplinger** [comment]
@vitek-karas hmm not sure I agree with that, there are likely other important settings you'll miss and all other hosts are implementing it.

I see that this is implemented in https://github.com/dotnet/android/blob/868acb2ceab4f97a5c261e8288500f2e3e2f8901/src/native/clr/host/host.cc#L33, can we not provide a simple implementation of get_runtime_property in dotnet/runtime? We already have the runtimeconfig.bin conversion code so you don't need to parse json.

**Comment by vitek-karas** [comment]
@akoeplinger - we were discussing exactly that. For this specific problem we don't need it, because the knob has an env. variable. I just wanted to "Wait" until we find a case where we do need a knob which doesn't have env. variable - and implement it then.
But if David wants to pick it up right now, it's likely not a throw away work.

**Comment by akoeplinger** [comment]
ok, makes sense

**Comment by davidnguyen-tech** [comment]
The `runtimeconfig.json` support for our test host is tracked in #117919.
