### PR TITLE
Fix lookup for current Thread in async signal handler

### LINKED ISSUE #121581: Address sanitizer: Crash/deadlock in inject signal handler on Linux with glibc >= 2.40
### Description

CoreCLR crashes in signal handler due to not async-safe code called from `inject_activation_handler` signal handler.

This starts to happen with glibc at least >= 2.40, which changed logic in thread locals and now `GetThread`/`GetThreadNULLOk` called from signal handler can lead to realloc and crash. Sometimes this can lead to deadlock, https://github.com/dotnet/runtime/issues/121345 is related. This issue happens both with and without asan. 

Example of crash backtrace (also from https://github.com/dotnet/runtime/issues/121345):
```
0xf51a9340 is located 0 bytes inside of 320-byte region [0xf51a9340,0xf51a9480)
freed by thread T11 here:
    #0 0xf75fa26e in realloc.part.0 (/usr/lib/libasan.so+0x9e26e) (BuildId: 9bba7c7c1d333d26085dc332318addcdddefc51d)
    #1 0xf7b11ae4 in _dl_resize_dtv (/lib/ld-linux.so.3+0x41010ae4) (BuildId: 09e97ca6a7629ff5a7bcdd346a4f7a5508203c59)
    #2 0xf7b12500 in _dl_update_slotinfo (/lib/ld-linux.so.3+0x41011500) (BuildId: 09e97ca6a7629ff5a7bcdd346a4f7a5508203c59)
    #3 0xf7b1265c in update_get_addr (/lib/ld-linux.so.3+0x4101165c) (BuildId: 09e97ca6a7629ff5a7bcdd346a4f7a5508203c59)
    #4 0xf75dd5ea in __tls_get_addr (/usr/lib/libasan.so+0x815ea) (BuildId: 9bba7c7c1d333d26085dc332318addcdddefc51d)
    #5 0xf24062da in CheckActivationSafePoint(unsigned int) (/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcoreclr.so+0x1792da) (BuildId: 78a8db7ede0a62b8ff150e5a58e4c5dad06019e3)
    #6 0xf2571cc8 in inject_activation_handler(int, siginfo_t*, void*) (/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcoreclr.so+0x2e4cc8) (BuildId: 78a8db7ede0a62b8ff150e5a58e4c5dad06019e3)
    #7 0xf71ace0c  (/lib/libc.so.6+0x41242e0c) (BuildId: 4d66a597c3674cb64087a6587522a00c688b8037)
    #8 0xf7605700 in __sanitizer::BufferedStackTrace::UnwindImpl(unsigned int, unsigned int, void*, bool, unsigned int) (/usr/lib/libasan.so+0xa9700) (BuildId: 9bba7c7c1d333d26085dc332318addcdddefc51d)
    #9 0xf75fa298 in realloc.part.0 (/usr/lib/libasan.so+0x9e298) (BuildId: 9bba7c7c1d333d26085dc332318addcdddefc51d)
    #10 0xf7b11ae4 in _dl_resize_dtv (/lib/ld-linux.so.3+0x41010ae4) (BuildId: 09e97ca6a7629ff5a7bcdd346a4f7a5508203c59)
    #11 0xf7b12500 in _dl_update_slotinfo (/lib/ld-linux.so.3+0x41011500) (BuildId: 09e97ca6a7629ff5a7bcdd346a4f7a5508203c59)
    #12 0xf7b1265c in update_get_addr (/lib/ld-linux.so.3+0x4101165c) (BuildId: 09e97ca6a7629ff5a7bcdd346a4f7a5508203c59)
    #13 0xf75dd5ea in __tls_get_addr (/usr/lib/libasan.so+0x815ea) (BuildId: 9bba7c7c1d333d26085dc332318addcdddefc51d)
    #14 0xf235d62a in ManagedThreadBase_DispatchMiddle(ManagedThreadCallState*)::Cleanup::~Cleanup() (/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcoreclr.so+0xd062a) (BuildId: 78a8db7ede0a62b8ff150e5a58e4c5dad06019e3)
    #15 0xf235c926 in ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) (/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcoreclr.so+0xcf926) (BuildId: 78a8db7ede0a62b8ff150e5a58e4c5dad06019e3)
    #16 0xf235cb60 in ManagedThreadBase::KickOff(void (*)(void*), void*) (/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcoreclr.so+0xcfb60) (BuildId: 78a8db7ede0a62b8ff150e5a58e4c5dad06019e3)
    #17 0xf238a274 in ThreadNative::KickOffThread(void*) (/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcoreclr.so+0xfd274) (BuildId: 78a8db7ede0a62b8ff150e5a58e4c5dad06019e3)
    #18 0xf25912d8 in CorUnix::CPalThread::ThreadEntry(void*) (/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcoreclr.so+0x3042d8) (BuildId: 78a8db7ede0a62b8ff150e5a58e4c5dad06019e3)
    #19 0xf75a1eda in asan_thread_start(void*) (/usr/lib/libasan.so+0x45eda) (BuildId: 9bba7c7c1d333d26085dc332318addcdddefc51d)
    #20 0xf71f0cb0 in start_thread (/lib/libc.so.6+0x41286cb0) (BuildId: 4d66a597c3674cb64087a6587522a00c688b8037)
```

Should hijack be disabled for Linux for now as a quick fix (e.g. disabling `FEATURE_THREAD_ACTIVATION`) until https://github.com/dotnet/runtime/issues/121345#issuecomment-3500116260 is not completed? This seems to affect all Linux platforms with glibc >= 2.40 (e.g. Ubuntu 25.04 and higher).

cc @dotnet/samsung 

### Reproduction Steps

Some reproduction cases are mentioned in https://github.com/dotnet/runtime/issues/121345

### Expected behavior

No crash/deadlock

### Actual behavior

Crash/deadlock

### Regression?

Seems to be present in all .net versions (at least starting from .net core 3.1)

### Known Workarounds

Disabling `FEATURE_THREAD_ACTIVATION`?

### Configuration

Crash backtrace above for .net 8.0.11 arm32 Tizen, but bug is independent of arch and dotnet version

### Other information

_No response_

### PR DESCRIPTION
**Pull request by janvorli**
The current `CheckActivationSafePoint` uses thread local storage to
get the current Thread instance. But this function is called from
async signal handler (the activation signal handler) and it is not
allowed to access TLS variables there because the access can allocate
and if the interrupted code was running in an allocation code, it
could crash.
There was no problem with this since .NET 1.0, but a change in the
recent glibc version has broken this. We've got reports of crashes
in this code due to the reason mentioned above.

This change introduces an async safe mechanism for accessing the
current Thread instance from async signal handlers. It uses a
segmented array that can grow, but never shrink. Entries for
threads are added when runtime creates a thread / attaches to an
external thread and removed when the thread dies.

The check for safety of the activation injection was further enhanced
to make sure that the ScanReaderLock is not taken. In cases it would 
need to be taken, we just reject the location.

Since NativeAOT is subject to the same issue, the code to maintain the
thread id to thread instance map is placed to the minipal and shared
between coreclr and NativeAOT.

Closes #121581

### CODE REVIEW

File: src/native/minipal/thread.c [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+
+#define MAX_THREADS_IN_SEGMENT 256
+
+struct ThreadSegment
+{
+    struct ThreadEntry entries[MAX_THREADS_IN_SEGMENT];
+    struct ThreadSegment* pNext;
+};
+
+static struct ThreadSegment *s_pAsyncSafeThreadMapHead = NULL;
```
Comment (jkotas) [inline src/native/minipal/thread.c]: I am not sure whether the implementation of this data structure belongs to minipal. 

If you have put it into minipal just to facilitate sharing between NAOT and regular CoreCLR, we have better place for that: `src\coreclr\runtime .

**Comment by jkotas** [comment]
> There was no problem with this since .NET 1.0, but a change in the recent glibc version has broken this

Have you been able to trace down the change? I think we just got lucky that it has not showed up on the radar earlier.

File: src/native/minipal/thread.c (hunk 1 above)
Comment (am11) [reply src/native/minipal/thread.c]: Initially, native/minipal was created to share code between src/coreclr and something outside of coreclr (libs, corehost or mono). Then we added cpuid/cpufeatures and bunch of other stuff which is not used by anything outside coreclr. Today, src/native/minipal is just being used to share C code regardless of whether it’s used outside of src/coreclr.

> to facilitate sharing between NAOT and regular CoreCLR, we have better place for that: `src\coreclr\runtime .

I thought src\coreclr\minipal is the place for that facility and coreclr\runtime is to unify asm code between them.

Comment (jkotas) [reply src/native/minipal/thread.c]: I think about src\minipal as general-purpose stuff that should be abstracting the platform. I know we have a few exceptions that are not really a platform abstraction - but they are still very general-purpose utilities.

This data structure looks very specific to how the thread suspension is implemented in JIT (regular CoreCLR) and NAOT runtimes. I think about it as an implementation detail of the thread suspension. Ideally, the whole implementation of thread suspension would be shared between JIT and NAOT - we are not there yet.

> cpuid/cpufeatures

BTW: cpuid/cpufeatures is also used in crossgen2/ilc that is distinct from the runtimes.

> src\coreclr\minipal is the place for that facility

coreclr\minipal has the messier and less general-purpose PAL abstractions that are specific to the JIT runtime. It is not used by anything else. We tend to be moving bits of src\coreclr\pal that are too difficult to cleanup completely, https://github.com/dotnet/runtime/blob/main/src/coreclr/minipal/dn-stdio.h#L15 is a great example.

> coreclr\runtime is to unify asm code between them.

It is meant to be used for more than just the .asm files. It has CachedInterfaceDispatch.cpp/CachedInterfaceDispatch.h today. It would be nice to move the other .h/cpp files that are shared between JIT and NAOT runtime too. These files are cherry-picked from VM directory in a hacky way currently that does not look great, e.g.: https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/Runtime/gcinfodecoder.cpp.

File: src/coreclr/vm/threadsuspend.cpp [hunk 2]
```diff
@@ -5731,16 +5731,18 @@ void ThreadSuspend::SuspendEE(SUSPEND_REASON reason)
 //          It is unsafe to use blocking APIs or allocate in this method.
 BOOL CheckActivationSafePoint(SIZE_T ip)
 {
-    Thread *pThread = GetThreadNULLOk();
+    Thread *pThread = GetThreadAsyncSafe();
+    _ASSERTE(pThread != NULL);
```
[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/vm/threadsuspend.cpp]: This looks like valid feedback. We can be seeing a signal sent by some other component (e.g. second NAOT runtime). We should forward the signal to the next component in that case.

Could you please do some ad-hoc stress testing to make sure that it works well? We should not be crashing, and we should not be eating signals that other components may expect.

File: src/native/minipal/thread.c (hunk 1 above)
Comment (janvorli) [reply src/native/minipal/thread.c]: > If you have put it into minipal just to facilitate sharing between NAOT and regular CoreCLR, we have better place for that: `src\coreclr\runtime .

Yes, the reason was just to share that between coreclr and nativeaot. I'll move it to the src\coreclr\runtime.

File: src/coreclr/vm/threadsuspend.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (janvorli) [reply src/coreclr/vm/threadsuspend.cpp]: This assert is a forgotten leftover from my local testing, it should not be there. 



> Could you please do some ad-hoc stress testing to make sure that it works well? We should not be crashing, and we should not be eating signals that other components may expect.

Yes, I'll do that.

File: src/coreclr/vm/threads.cpp [hunk 3]
```diff
@@ -371,6 +379,21 @@ void SetThread(Thread* t)
 
     // Clear or set the app domain to the one domain based on if the thread is being nulled out or set
     t_CurrentThreadInfo.m_pAppDomain = t == NULL ? NULL : AppDomain::GetCurrentDomain();
+
+#ifdef TARGET_UNIX
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/threads.cpp]: Can we fold this logic into the branch above? It is odd to see the same checks in a different location in the same function.

File: src/native/minipal/thread.h
Comment (AaronRobinsonMSFT) [inline src/native/minipal/thread.h]:
```suggestion
    return minipal_get_current_thread_id_no_cache(); // See impl for details.
```

File: src/native/minipal/thread.c [hunk 4]
```diff
@@ -0,0 +1,130 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+#define _GNU_SOURCE
+
+#include <stdbool.h>
+#include "utils.h"
+#include "thread.h"
+
+#ifdef TARGET_UNIX
```
Comment (AaronRobinsonMSFT) [inline src/native/minipal/thread.c]: Why not use this everywhere? Instead of relying on Windows platform semantics, we can simply make this the way to do it?

File: src/coreclr/runtime/asyncsafethreadmap.cpp [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+                ppSegment,
+                &pExpected,
+                pNewSegment,
+                false /* weak */,
+                __ATOMIC_RELEASE  /* success_memorder */,
+                __ATOMIC_RELAXED /* failure_memorder */))
+            {
+                // Another thread added the segment first
+                free(pNewSegment);
+                pNewSegment = *ppSegment;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/runtime/asyncsafethreadmap.cpp]: Instead of reaching back up and accessing a potentially changing value, this API writes the non-equal failure value back into `pExpected`. I think the more correct operation would be `pNewSegment = *pExpected;`

File: src/coreclr/runtime/asyncsafethreadmap.cpp [hunk 6]
```diff
@@ -0,0 +1,130 @@
...
+            pSegment = pNewSegment;
+        }
+        for (size_t i = 0; i < MAX_THREADS_IN_SEGMENT; i++)
+        {
+            size_t index = (startIndex + i) % MAX_THREADS_IN_SEGMENT;
+
+            size_t expected = 0;
+            if (__atomic_compare_exchange_n(
+                    &pSegment->entries[index].osThread,
+                    &expected, osThread,
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/runtime/asyncsafethreadmap.cpp]:
```suggestion
                    &expected,
                    osThread,
```

File: src/coreclr/nativeaot/Runtime/threadstore.cpp [hunk 7]
```diff
@@ -352,6 +365,13 @@ EXTERN_C RuntimeThreadLocals* RhpGetThread()
     return &tls_CurrentThread;
 }
 
+#ifdef TARGET_UNIX
+Thread * ThreadStore::GetCurrentThreadIfAvailableAsyncSafe()
+{
+    return (Thread*)FindThreadInAsyncSafeMap(minipal_get_current_thread_id_no_cache());
```
Comment (am11) [inline src/coreclr/nativeaot/Runtime/threadstore.cpp:371]: @janvorli, was there a reliability issue with the cached variant? If so, does it affect existing callers?

Comment (janvorli) [reply src/coreclr/nativeaot/Runtime/threadstore.cpp:371]: The cached variant uses TLS. We cannot use TLS, as preventing access to TLS is what's this PR is all about.

Comment (am11) [reply src/coreclr/nativeaot/Runtime/threadstore.cpp:371]: Ah, I missed that it's stored in thread local.

File: src/native/minipal/thread.h
Comment (janvorli) [reply src/native/minipal/thread.h]: done

File: src/coreclr/runtime/asyncsafethreadmap.cpp (hunk 5 above)
Comment (janvorli) [reply src/coreclr/runtime/asyncsafethreadmap.cpp]: done

File: src/coreclr/runtime/asyncsafethreadmap.cpp (hunk 6 above)
Comment (janvorli) [reply src/coreclr/runtime/asyncsafethreadmap.cpp]: done

File: src/native/minipal/thread.c (hunk 4 above)
Comment (janvorli) [reply src/native/minipal/thread.c]: We could possibly do that, but it would be adding unnecessary overhead for Windows. I would prefer to keep it for Unix only, at least for now. @jkotas, what do you think?

Comment (jkotas) [reply src/native/minipal/thread.c]: I agree. I do not think we want to pay this overhead on Windows.

File: src/native/minipal/thread.h [hunk 8]
```diff
@@ -4,6 +4,8 @@
 #ifndef HAVE_MINIPAL_THREAD_H
 #define HAVE_MINIPAL_THREAD_H
 
+#ifndef TARGET_WINDOWS
```
Comment (jkotas) [inline src/native/minipal/thread.h]:
```suggestion
#ifndef HOST_WINDOWS
```

File: src/native/minipal/thread.h [hunk 9]
```diff
@@ -118,8 +138,11 @@ static inline int minipal_set_thread_name(pthread_t thread, const char* name)
 #endif
 }
 
+
 #ifdef __cplusplus
 }
 #endif // extern "C"
 
+#endif // !TARGET_WINDOWS
```
Comment (jkotas) [inline src/native/minipal/thread.h]:
```suggestion
#endif // !HOST_WINDOWS
```

Comment (janvorli) [reply src/native/minipal/thread.h]: Done

File: src/coreclr/runtime/asyncsafethreadmap.cpp [hunk 10]
```diff
@@ -0,0 +1,130 @@
...
+void *minipal_find_thread_in_async_safe_map(size_t osThread)
+{
+    size_t startIndex = osThread % MAX_THREADS_IN_SEGMENT;
+    struct ThreadSegment* pSegment = s_pAsyncSafeThreadMapHead;
+    while (pSegment)
+    {
+        for (size_t i = 0; i < MAX_THREADS_IN_SEGMENT; i++)
+        {
+            size_t index = (startIndex + i) % MAX_THREADS_IN_SEGMENT;
+            // Use acquire to synchronize with release in insert_thread_to_async_safe_map
```
[the remark this answers is not in the document]
Comment (janvorli) [reply src/coreclr/runtime/asyncsafethreadmap.cpp]: Fixed

File: src/coreclr/vm/threads.cpp (hunk 3 above)
Comment (janvorli) [reply src/coreclr/vm/threads.cpp]: Done

File: src/native/minipal/thread.h (hunk 8 above)
Comment (janvorli) [reply src/native/minipal/thread.h]: Done

**Comment by janvorli** [comment]
Looking at the NativeAOT handler, there is actually also a call to the GetCurrentThreadIfAvailable in the Thread::HijackCallback that , so the NativeAOT fix is not complete yet.

**Comment by janvorli** [comment]
@jkotas I've tested this change with added testing activation signal handler to corerun and verified that this handler is called after the real coreclr one returns. I did it by writing a message to stderr in that handler and then running all coreclr tests with it and scanning the test logs afterwards for that message. I've also ran all pri 1 tests with gcstress 3 locally to stress it. All seemed good.

File: src/coreclr/nativeaot/Runtime/threadstore.cpp [hunk 11]
```diff
@@ -143,6 +145,14 @@ void ThreadStore::AttachCurrentThread(bool fAcquireThreadStoreLock)
     pAttachingThread->m_ThreadStateFlags = Thread::TSF_Attached;
 
     pTS->m_ThreadList.PushHead(pAttachingThread);
+
+#if defined(TARGET_UNIX) && !defined(TARGET_WASM)
+    if (!InsertThreadIntoAsyncSafeMap(pAttachingThread->m_threadId, pAttachingThread))
+    {
+        ASSERT_UNCONDITIONALLY("Failed to insert thread into async-safe map due to OOM.");
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/threadstore.cpp]:
```suggestion
        PalPrintFatalError("\nFailed to insert thread into async-safe map due to out of memory.\n");
```

File: src/coreclr/vm/threadsuspend.cpp [hunk 12]
```diff
@@ -5731,16 +5731,17 @@ void ThreadSuspend::SuspendEE(SUSPEND_REASON reason)
...
     // Also we are not interested in handling interruption if we are already in preemptive mode nor if we are single stepping
     BOOL isActivationSafePoint = pThread != NULL &&
         (pThread->m_StateNC & Thread::TSNC_DebuggerIsStepping) == 0 &&
         pThread->PreemptiveGCDisabled() &&
-        ExecutionManager::IsManagedCode(ip);
+        (ExecutionManager::GetScanFlags(pThread) != ExecutionManager::ScanReaderLock) &&
+        ExecutionManager::IsManagedCodeNoLock(ip);
 
-    if (!isActivationSafePoint)
+    if (!isActivationSafePoint && pThread != NULL)
```
Comment (jkotas) [inline src/coreclr/vm/threadsuspend.cpp:5744]:
```suggestion
    if (pThread != NULL)
```
Should we clear it unconditionally like on NAOT?

File: src/coreclr/vm/threads.cpp [hunk 13]
```diff
@@ -370,7 +383,27 @@ void SetThread(Thread* t)
...
     // Clear or set the app domain to the one domain based on if the thread is being nulled out or set
-    t_CurrentThreadInfo.m_pAppDomain = t == NULL ? NULL : AppDomain::GetCurrentDomain();
+    if (t != NULL)
+    {
+        t_CurrentThreadInfo.m_pAppDomain = AppDomain::GetCurrentDomain();
+#if defined(TARGET_UNIX) && !defined(TARGET_WASM)
+        if (!InsertThreadIntoAsyncSafeMap(t->GetOSThreadId64(), t))
+        {
+            // TODO: can we handle this OOM more gracefully?
+            EEPOLICY_HANDLE_FATAL_ERROR_WITH_MESSAGE(COR_E_EXECUTIONENGINE, W("Failed to insert thread into async-safe map due to OOM."));
```
Comment (jkotas) [inline src/coreclr/vm/threads.cpp]:
```suggestion
            EEPOLICY_HANDLE_FATAL_ERROR_WITH_MESSAGE(COR_E_EXECUTIONENGINE, W("Failed to insert thread into async-safe map due to out of memory."));
```

File: src/coreclr/vm/threads.cpp [hunk 14]
```diff
@@ -370,7 +383,27 @@ void SetThread(Thread* t)
...
 
     // Clear or set the app domain to the one domain based on if the thread is being nulled out or set
-    t_CurrentThreadInfo.m_pAppDomain = t == NULL ? NULL : AppDomain::GetCurrentDomain();
+    if (t != NULL)
+    {
+        t_CurrentThreadInfo.m_pAppDomain = AppDomain::GetCurrentDomain();
+#if defined(TARGET_UNIX) && !defined(TARGET_WASM)
+        if (!InsertThreadIntoAsyncSafeMap(t->GetOSThreadId64(), t))
+        {
+            // TODO: can we handle this OOM more gracefully?
```
Comment (jkotas) [inline src/coreclr/vm/threads.cpp]: We can - if it is one of our threads. However, I do not think it is worth it. The allocation of the thread statics above can crash due to OOM too and I do not think there is a good way to recover from it either. Recovering from corner-case OOMs is just not a thing on Unix.

File: src/coreclr/vm/threadsuspend.cpp (hunk 12 above)
Comment (jkotas) [reply src/coreclr/vm/threadsuspend.cpp:5744]: Ah, it will be cleared later in HandleSuspensionForInterruptedThread - that's better.

**Review by jkotas — APPROVED** [review]
Thank you!

File: src/coreclr/vm/threads.cpp (hunk 14 above)
Comment (janvorli) [inline src/coreclr/vm/threads.cpp]:
```suggestion
```

**Comment by gbalykov** [comment]
Thanks! Do you plan to backport this to .net 8?
