### PR TITLE
Custom attribute properties were not always applied correctly

### LINKED ISSUE #31195: CustomAttribute with Array Properties sets nulls incorrectly
An attribute with two array properties does not behave as expected if the first array property is set to a value and the second array property is set to null. If the two arrays are of the same type, the second property is set to the same value as the first property. If the two types are incompatible, an exception is thrown when the attribute is constructed, stating that the second property cannot be found.

Attached are two variations on a simple program that replicates each issue.

[Same Type](https://github.com/dotnet/corefx/files/3737962/Program.txt)
[Incompatible Types](https://github.com/dotnet/corefx/files/3737971/Program.2.txt)

### PR DESCRIPTION
**Pull request by steveharter**
Fixes https://github.com/dotnet/runtime/issues/31195

Note the two new tests were failing before this change with:
```
    System.Reflection.Tests.CustomAttributeTests.AttributeWithDifferentPropertyTypes [FAIL]
      System.Reflection.CustomAttributeFormatException : 'StringArray' property specified was not found.
    System.Reflection.Tests.CustomAttributeTests.AttributeWithSamePropertyTypes [FAIL]
      Assert.Null() Failure
      Expected: (null)
      Actual:   Object[] [""]
```

### CODE REVIEW

File: src/coreclr/src/vm/customattribute.cpp [hunk 1]
```diff
@@ -937,6 +936,7 @@ FCIMPL7(void, COMCustomAttribute::GetPropertyOrFieldData, ReflectModuleBaseObjec
                 break;
             case SERIALIZATION_TYPE_SZARRAY:
             {
+                *value = NULL;
```
Comment (GrabYourPitchforks) [inline src/coreclr/src/vm/customattribute.cpp:939]: Nit: Should this be moved above the _switch_ statement to make this code more future-proof should new case statements be added in the future?

**Review by GrabYourPitchforks — APPROVED** [review]

File: src/coreclr/src/vm/customattribute.cpp (hunk 1 above)
Comment (steveharter) [reply src/coreclr/src/vm/customattribute.cpp:939]: Was considered, but there's the tiny cost of double assignment.
