### PR TITLE
Reduce leaked test files

### LINKED ISSUE #62756: Some outer loop tests on Linux fail unless run as root
We have 8 tests, all for Unix, that are marked thus
```c#
        [Trait(XunitConstants.Category, XunitConstants.RequiresElevation)]
```
if these tests are run as a non root user, they either fail or attempt to block to request sudo password. This is because we have never filtered on this annotation.

On Windows, tests conditionalize on `PlatformDetection.IsWindowsAndElevated` either dynamically or indirectly through a `[ConditionalXXX]` attribute on the test.

Most likely we should do the same thing for Unix, write code that determines whether we are running as root, remove the Trait attribute and use the Windows approach.

### LINKED ISSUE #68454: Test failure System.IO.Tests.DirectoryInfo_SymbolicLinks.ResolveLinkTarget_ReturnFinalTarget_ChainOfLinks_ExceedsLimit_Throws
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20220423.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1734215&view=ms.vss-test-web.build-test-results-tab&runId=46958122&paneView=debug&resultId=147769)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_checked-jitstress2_jitstressregs0x1000-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- System.IO.Tests.DirectoryInfo_SymbolicLinks.ResolveLinkTarget_ReturnFinalTarget_ChainOfLinks_ExceedsLimit_Throws(length: 100, relative: False)

```
**Error message:**
```
System.IO.IOException : The file '/tmp/DirectoryInfo_SymbolicLinks_jcexpizd.5gs/GetRandomLinkName_84_f7f92673.link' already exists.


Stack trace
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) in /_/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs:line 21
   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter) in /_/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs:line 48
   at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Unix.cs:line 621
   at System.IO.FileSystemInfo.CreateAsSymbolicLink(String pathToTarget) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystemInfo.cs:line 149
   at System.IO.Tests.BaseSymbolicLinks_FileSystemInfo.CreateSymbolicLink(String path, String pathToTarget) in /_/src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystemInfo.cs:line 17
   at System.IO.Tests.BaseSymbolicLinks_FileSystem.CreateChainOfLinks(String target, Int32 length, Boolean relative) in /_/src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs:line 304
   at System.IO.Tests.BaseSymbolicLinks_FileSystem.ResolveLinkTarget_ReturnFinalTarget_ChainOfLinks_ExceedsLimit_Throws(Int32 length, Boolean relative) in /_/src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs:line 293
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs:line 383
```

### PR DESCRIPTION
**Pull request by danmoseley**
Replaces https://github.com/dotnet/runtime/pull/68456
Fix https://github.com/dotnet/runtime/issues/68454 (?)
Fix https://github.com/dotnet/runtime/issues/62756

Increase entropy in randomly generated file names
Pass through caller method name and line number in more cases to improve test file name forensics
Add # prefix to test folders to make it easier to find leaks in today's crowded temp folders
Remove any read-only attributes on files within the test folder to ensure it can be deleted
Fix several test issues causing leaked files
Improve file-matching test to ensure it doesn't accidentally match a randomly generated name
Fixup sudo conditions
In some cases, a test was leaking its temp directory when it remote-exec'd code that changed the current directory to the temp directory. The fix was to set the current directory back at the end of the remote-exec'd code. This is a puzzle as the test directory gets deleted when the test method completes, which happens after the remote-exec process has already quit, and the current-directory of the remote-exec process ought to be irrelevant. It's as if Windows holds on to it a little longer.

This fixes almost all leaked files when running the FileSystem test cases.

### CODE REVIEW

**Comment by danmoseley** [comment]
Included https://github.com/dotnet/runtime/pull/64619 by @Tarun047

**Comment by danmoseley** [comment]
The only remaining temp file leaks (on Windows outerloop)
```
#File_OpenHandle_mbf4thvj.vp0\NegativeBufferSizeThrows_27_15m40hrp
#File_OpenHandle_u4sk3vcy.r4j\NegativeBufferSizeThrows_27_u7ldv46y
#File_OpenHandle_xqxtvgkl.pdn\NegativeBufferSizeThrows_27_xkaed0k4
#PhysicalFileProviderTests_2iwnhs1x.chf\GetDirectoryContentsDoesNotReturnFileInfoForHiddenFile_698_w3scpmbq
#PhysicalFileProviderTests_2iwnhs1x.chf\GetDirectoryContentsDoesNotReturnFileInfoForHiddenFile_698_w3scpmbq\78e32c35-9a63-4664-b9fa-ccf3d7df76cb
#PhysicalFileProviderTests_2kzd21ai.0vv\GetDirectoryContentsReturnsFilesWhenExclusionDisabled_769_nu1s4h0d
#PhysicalFileProviderTests_2kzd21ai.0vv\GetDirectoryContentsReturnsFilesWhenExclusionDisabled_769_nu1s4h0d\bb45ddf2-9cb0-489d-aeab-baeb4d7c9d78
#PhysicalFileProviderTests_2kzd21ai.0vv\GetDirectoryContentsReturnsFilesWhenExclusionDisabled_769_nu1s4h0d\bb45ddf2-9cb0-489d-aeab-baeb4d7c9d78\.af3c89e7-27d0-4a43-93a4-126e0461d732
#PhysicalFileProviderTests_5xgxmqxg.iyq\GetFileInfoReturnsNotFoundFileInfoForRelativePathWithEmptySegmentsThatNavigates_216_zu0ehdt0
#PhysicalFileProviderTests_5xgxmqxg.iyq\GetFileInfoReturnsNotFoundFileInfoForRelativePathWithEmptySegmentsThatNavigates_216_zu0ehdt0\b
#PhysicalFileProviderTests_bbfm10d4.0yw\GetDirectoryContentsReturnsRootDirectoryContentsForEmptyPath_663_cf6pw9ju
#PhysicalFileProviderTests_bbfm10d4.0yw\GetDirectoryContentsReturnsRootDirectoryContentsForEmptyPath_663_cf6pw9ju\Fileb792923d-2e73-435e-9d97-8c1675783746
#PhysicalFileProviderTests_dz3xqd2f.oag\GetFileInfoReturnsNotFoundFileInfoForHiddenFile_252_97gaod5t
#PhysicalFileProviderTests_hjrbdee3.egf\TokensNotFiredForHiddenAndSystemFiles_1333_3ymzo581
#PhysicalFileProviderTests_igsq2m4c.wxg\TokensFiredForNewDirectoryContentsOnRename_1240_licz3ckf
#PhysicalFileProviderTests_igsq2m4c.wxg\TokensFiredForNewDirectoryContentsOnRename_1240_licz3ckf\5a26b9e4-a2de-48a4-a984-e7b1e24480a9
#PhysicalFileProviderTests_igsq2m4c.wxg\TokensFiredForNewDirectoryContentsOnRename_1240_licz3ckf\5a26b9e4-a2de-48a4-a984-e7b1e24480a9\e173ffcc-fdc2-47bd-b70a-d4ed24956845
#PhysicalFileProviderTests_igsq2m4c.wxg\TokensFiredForNewDirectoryContentsOnRename_1240_licz3ckf\5a26b9e4-a2de-48a4-a984-e7b1e24480a9\e173ffcc-fdc2-47bd-b70a-d4ed24956845\3f259218-b872-4cd1-8998-b191253a0db0
#PhysicalFileProviderTests_kilcwnnx.312\GetDirectoryContentsDoesNotReturnFileInfoForSystemFile_723_85ifuxce
#PhysicalFileProviderTests_kilcwnnx.312\GetDirectoryContentsDoesNotReturnFileInfoForSystemFile_723_85ifuxce\d838ace2-55c6-4891-892f-1ac10e971bab
#PhysicalFileProviderTests_pr3cf3ft.cpm\GetFileInfoReturnsNotFoundFileInfoForSystemFile_274_liv199bi
#PhysicalFileProviderTests_t3mtw2d3.wdb\GetFileInfoReturnsNotFoundFileInfoForRelativePathThatNavigatesAboveRoot_201_9os11pww
#PhysicalFileProviderTests_t3mtw2d3.wdb\GetFileInfoReturnsNotFoundFileInfoForRelativePathThatNavigatesAboveRoot_201_9os11pww\b
#PhysicalFileProviderTests_zexq03sy.f0h\GetDirectoryContentsDoesNotReturnFileInfoForFileNameStartingWithPeriodByDefault_746_p1pzflds
#PhysicalFileProviderTests_zexq03sy.f0h\GetDirectoryContentsDoesNotReturnFileInfoForFileNameStartingWithPeriodByDefault_746_p1pzflds\7e46e490-5b9a-460d-9194-63cc11d0fe60
#PhysicalFileProviderTests_zexq03sy.f0h\GetDirectoryContentsDoesNotReturnFileInfoForFileNameStartingWithPeriodByDefault_746_p1pzflds\7e46e490-5b9a-460d-9194-63cc11d0fe60\.5ccf1ad5-1044-4a56-b4ad-687ab6aa126d
```

File: src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs [hunk 1]
```diff
@@ -69,9 +70,24 @@ public void Dispose()
...
+                    {
+                        file.IsReadOnly = false;
+                    }
 
-            try { Directory.Delete(TestDirectory, recursive: true); }
-            catch { } // avoid exceptions escaping Dispose
+                    Directory.Delete(TestDirectory, recursive: true);
+                }
+            }
+            catch {  } // avoid exceptions escaping Dispose
```
Comment (Jozkee) [inline src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs:90]: You can do this instead, unless you want to also catch exceptions occurring in the `catch (UnauthorizedAccessException)` block.
```cs
try 
{ 
    Directory.Delete(TestDirectory, recursive: true); 
}
catch (UnauthorizedAccessException)
{
    DirectoryInfo di = new DirectoryInfo(TestDirectory);
    foreach (FileInfo file in di.GetFiles("*", SearchOption.AllDirectories))
    {
        file.IsReadOnly = false;
    }
}
catch { } // avoid exceptions escaping Dispose

```

File: src/libraries/Common/tests/TestUtilities/System/IO/PathGenerator.cs [hunk 2]
```diff
@@ -17,6 +19,27 @@ public static string GenerateTestFileName([CallerMemberName] string memberName =
                 memberName ?? "TestBase",
                 lineNumber,
                 index.GetValueOrDefault(),
-                Guid.NewGuid().ToString("N").Substring(0, 8)); // randomness to avoid collisions between derived test classes using same base method concurrently
+                GenerateRandomFileSafeString(8)); // randomness to avoid collisions between derived test classes using same base method concurrently
+
+        private static string GenerateRandomFileSafeString(int length)
+        {
+            // A little more entropy than Guid.NewGuid().ToString("N").Substring(0, length))
+            const string alphanum = "abcdefghijklmnopqrstuvwxyz0123456789";
```
Comment (Jozkee) [inline src/libraries/Common/tests/TestUtilities/System/IO/PathGenerator.cs:27]: IIRC `const`s are written in Pascal.
```suggestion
            const string Alphanumeric = "abcdefghijklmnopqrstuvwxyz0123456789";
```

File: src/libraries/Common/tests/TestUtilities/System/IO/PathGenerator.cs [hunk 3]
```diff
@@ -17,6 +19,27 @@ public static string GenerateTestFileName([CallerMemberName] string memberName =
...
+
+            byte[] bytes = new byte[length];
+            lock (_rand)
```
Comment (Jozkee) [inline src/libraries/Common/tests/TestUtilities/System/IO/PathGenerator.cs:30]: Just curious, what might happen if you don't `lock` it?

File: src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs [hunk 4]
```diff
@@ -453,8 +455,7 @@ public void ProcessStart_UseShellExecuteTrue_OpenUrl_SuccessfullyReadsArgumentAr
             }
         }
 
-        [ConditionalFact(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported))]
-        [Trait(XunitConstants.Category, XunitConstants.RequiresElevation)]
+        [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsUnixAndSuperUser))]
```
Comment (Jozkee) [inline src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:458]: It no longer checks `RemoteExecutor.IsSupported`, is that ok?
Also, you already know is Unix because `ProcessTests.Unix.cs` only compiles for it.

File: src/libraries/System.IO.FileSystem/tests/Base/FileGetSetAttributes.cs [hunk 5]
```diff
@@ -99,7 +99,7 @@ public void GettingAndSettingAttributes_AlternateDataStream_Windows(string strea
         {
             string path = CreateItem();
             streamName = path + streamName;
-            File.Create(streamName);
+            File.Create(streamName).Dispose();
```
Comment (Jozkee) [inline src/libraries/System.IO.FileSystem/tests/Base/FileGetSetAttributes.cs:102]: I think an analyzer-codefix for a standalone call to `File.Create(path)` would be very helpful to avoid these mistakes.

File: src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs [hunk 6]
```diff
@@ -468,6 +468,8 @@ protected void CreateSymbolicLink_PathToTarget_RelativeToLinkPath_Internal(bool
             // Verify that Target is resolved and is relative to Link's directory and not to the cwd.
             Assert.False(targetInfo.Exists);
             Assert.Equal(Path.GetDirectoryName(linkInfo.FullName), Path.GetDirectoryName(targetInfo.FullName));
+
+            Directory.SetCurrentDirectory(Path.GetTempPath());
```
Comment (Jozkee) [inline src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs:472]: > The fix was to set the current directory back at the end of the remote-exec'd code.

you mean set it back to the path we previously set in `ChangeCurrentDirectory()`? If so, I think this should be `Directory.SetCurrentDirectory(tempCwd)`

File: src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs [hunk 7]
```diff
@@ -94,7 +94,7 @@ public void PathAlreadyExistsAsDirectory(FileAttributes attributes)
             }
             finally
             {
-                testDir.Attributes = original;
+                testDir.Attributes = FileAttributes.Normal;
```
Comment (Jozkee) [inline src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs:97]: Can you please elaborate on why this is needed?

File: src/libraries/Common/tests/TestUtilities/System/IO/PathGenerator.cs (hunk 3 above)
Comment (danmoseley) [reply src/libraries/Common/tests/TestUtilities/System/IO/PathGenerator.cs:30]: The Random class is not thread safe - and this is a static method accessed from any thread running a test. (We do have Random.Shared which is thread safe, but it's not available when targeting .NET Framework)

File: src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs (hunk 1 above)
Comment (danmoseley) [reply src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs:90]: can you clarify? that looks the same as what I have, except that it doesn't delete the directory.

yes, I think we do want to catch exceptions from this block. we have decided that failing to cleanup should not fail the test.

File: src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs (hunk 7 above)
Comment (danmoseley) [reply src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs:97]: the new directory has FileAttributes.Normal, there's no need to read them.

if you mean - why bother setting them back - it's because a r/o directory can't be deleted. this was before I went in an added code in the cleanup to handle this, but it seems reasonable cleanup here.

File: src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs [hunk 8]
```diff
@@ -69,9 +70,24 @@ public void Dispose()
...
+            try
+            {
+                try
+                {
+                    Directory.Delete(TestDirectory, recursive: true);
+                }
+                catch (UnauthorizedAccessException)
+                {
+                    DirectoryInfo di = new DirectoryInfo(TestDirectory);
+                    foreach (FileInfo file in di.GetFiles("*", SearchOption.AllDirectories))
```
Comment (danmoseley) [inline src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs:82]: Just noticed this should be FileSystemInfo -- it needs to handle directories also

File: src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs [hunk 9]
```diff
@@ -69,9 +70,24 @@ public void Dispose()
         protected virtual void Dispose(bool disposing)
         {
             // No managed resources to clean up, so disposing is ignored.
```
Comment (danmoseley) [inline src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs:72]:
```suggestion
```

File: src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs (hunk 1 above)
Comment (Jozkee) [reply src/libraries/Common/tests/TestUtilities/System/IO/FileCleanupTestBase.cs:90]: > can you clarify? that looks the same as what I have, except that it doesn't delete the directory.

I was pointing out that you could avoid nested `try`s. But since you want to try-catch the UnauthorizedAccessException case, you still need the nested try. You can ignore.

File: src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs (hunk 7 above)
Comment (Jozkee) [reply src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs:97]: I mean, before we were restoring `Attributes` to its `original` value, I don't see how `original` could contain the `ReadOnly` flag if the directory was just created one line above.

File: src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs [hunk 10]
```diff
@@ -703,19 +703,19 @@ public void SearchPatternCaseSensitive()
         {
             DirectoryInfo testDir = Directory.CreateDirectory(GetTestFilePath());
             string testBase = GetTestFileName();
-            testDir.CreateSubdirectory(testBase + "aBBb");
-            testDir.CreateSubdirectory(testBase + "aBBB");
+            testDir.CreateSubdirectory(testBase + "aBBBBBBBBBBb");
```
Comment (Jozkee) [inline src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs:706]: Why do you need larger names?

File: src/libraries/System.IO.FileSystem/tests/Enumeration/AttributeTests.cs [hunk 11]
```diff
@@ -263,6 +263,8 @@ public void IsReadOnlyAttribute()
             };
 
             Assert.Equal(new string[] { fileTwo.FullName }, enumerable);
+
+            fileTwo.Attributes &= ~FileAttributes.ReadOnly;
```
Comment (Jozkee) [inline src/libraries/System.IO.FileSystem/tests/Enumeration/AttributeTests.cs:267]:
```suggestion
            // Cleanup
            fileTwo.Attributes &= ~FileAttributes.ReadOnly;
```

File: src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs (hunk 7 above)
Comment (danmoseley) [reply src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs:97]: It couldn't, but it was an extra line of code.

Comment (danmoseley) [reply src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs:97]: Oh, I see your point. In this case I guess I did it only for cleanup - remove the extra line.

File: src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs (hunk 6 above)
Comment (danmoseley) [reply src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs:472]: We don't want that -- tempCwd is within the test's folder, which we want cleaned up.

(As I mentioned in the description, I don't understand why the current directory of the child process is relevant since by the time the test exits, the remoteexec process has quit and presumably the OS closed any handles it had open. But nevertheless that is what I saw.)

File: src/libraries/System.IO.FileSystem/tests/Base/FileGetSetAttributes.cs (hunk 5 above)
Comment (danmoseley) [reply src/libraries/System.IO.FileSystem/tests/Base/FileGetSetAttributes.cs:102]: It should be found if you change CS2000 to "warn"
https://github.com/danmoseley/runtime/blob/4225cb0fff263e9fbc7ad007ab18e774a1b73d1e/eng/CodeAnalysis.test.globalconfig#L409
CA2213 is also relevant.

@stephentoub did you try these -- was there a lot of noise?

File: src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs (hunk 10 above)
Comment (danmoseley) [reply src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs:706]: this will fail whenever the test file name contains two capital B's in a row. previously that didn't happen as GUID letters formatted as lower case. Initially I was using capital letters in the generated names so it failed approx every 200 runs. I changed to lower case for some reason but seemed reasonable to make it longer in case we change again.

File: src/libraries/System.Formats.Tar/tests/TarWriter/TarWriter.WriteEntry.File.Tests.Unix.cs [hunk 12]
```diff
@@ -9,7 +9,9 @@ namespace System.Formats.Tar.Tests
 {
     public partial class TarWriter_WriteEntry_File_Tests : TarTestsBase
     {
-        [ConditionalTheory(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported))]
+        private static bool IsRemoteExecutorSupportedAndOnUnixAndSuperUser => RemoteExecutor.IsSupported && PlatformDetection.IsUnixAndSuperUser;
```
[the remark this answers is not in the document]
Comment (danmoseley) [reply src/libraries/System.Formats.Tar/tests/TarWriter/TarWriter.WriteEntry.File.Tests.Unix.cs:12]: It can't go in PlatformDetection as not all projects that include PlatformDetection also reference the remote executor.

**Comment by danmoseley** [comment]
@Jozkee feedback addressed.

File: src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs (hunk 6 above)
Comment (Jozkee) [reply src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs:472]: Ah I see what you mean, sounds like the folder is still locked by the RemoteExecutor process. 
I don't know if it may be possible to change the CWD of the RemoteExecutor Process in, say, `RemoteInvokeHandle.Dispose()` in order to avoid doing this each time its cwd gets changed.

File: src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs (hunk 10 above)
Comment (Jozkee) [reply src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs:706]: Sounds quite hard to figure out when an issue reporting the failing test gets filed. Consider adding a comment.

File: src/libraries/System.Configuration.ConfigurationManager/tests/System/Configuration/ConfigurationPathTests.cs [hunk 13]
```diff
@@ -44,6 +44,7 @@ public void CustomAppConfigIsUsedWhenSpecifiedAsAbsolutePath()
         }
 
         [ConditionalFact(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported))]
+        [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "Fails when path contains #")]
```
Comment (Jozkee) [inline src/libraries/System.Configuration.ConfigurationManager/tests/System/Configuration/ConfigurationPathTests.cs:47]: Should we use other prefix instead (TMP_)?

**Review by jozkee — APPROVED** [review]
Otherwise; LGTM. Thanks, Dan.

File: src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs (hunk 6 above)
Comment (danmoseley) [reply src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs:472]: That may be cleaner.

@jkotas do you have any idea why resetting the current directory seems necessary, given the remote exec process exits before we clean up the test folder?

File: src/libraries/System.Configuration.ConfigurationManager/tests/System/Configuration/ConfigurationPathTests.cs (hunk 13 above)
Comment (danmoseley) [reply src/libraries/System.Configuration.ConfigurationManager/tests/System/Configuration/ConfigurationPathTests.cs:47]: I chose # as it only makes the paths 1 chat longer. We have had length problems in the past - hence the code in FileCleanupTestBase that shortens paths. Plus, nobody else seems to use #..

File: src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs (hunk 6 above)
Comment (danmoseley) [reply src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs:472]: created https://github.com/dotnet/arcade/pull/9200

Comment (jkotas) [reply src/libraries/System.IO.FileSystem/tests/Base/SymbolicLinks/BaseSymbolicLinks.FileSystem.cs:472]: > @jkotas do you have any idea why resetting the current directory seems necessary, given the remote exec process exits before we clean up the test folder?

My guess is that it is likely anti-virus, watson or some other kind of Windows background task holding the directory. I think that it is unlikely for the process itself to be holding onto the directory once it exists.
