### PR TITLE
[wasm] Testing with NodeJs on CI

### LINKED ISSUE #41861: dotnet.wasm in node.js looks for module called 'a' and fails
`dotnet.wasm` module does not load cleanly in the node.js environment. It complains about a missing `package 'a'`.

Repro:
```sh
$ node -v
v14.9.0

$ cat > test.mjs << EOF
import * as dotnet from '/Users/am11/.nuget/packages//microsoft.netcore.app.runtime.browser-wasm/5.0.0-rc.1.20425.18/runtimes/browser-wasm/native/dotnet.wasm';

const listMethods = subject => Object.getOwnPropertyNames(subject).filter(item => typeof subject[item] === 'function');

console.log(listMethods(dotnet));
EOF

$ node --experimental-modules --experimental-wasm-modules test.mjs
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'a' imported from /Users/am11/.nuget/packages/microsoft.netcore.app.runtime.browser-wasm/5.0.0-rc.1.20425.18/runtimes/browser-wasm/native/dotnet.wasm
    at packageResolve (internal/modules/esm/resolve.js:623:9)
    at moduleResolve (internal/modules/esm/resolve.js:664:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:778:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Similar error about `module 'a'` occurs if we try [`WebAssembly.instantiate`](https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API) API:

```sh
$ cat > test2.mjs << EOF
import * as fs from 'fs';

const name = '/Users/am11/.nuget/packages//microsoft.netcore.app.runtime.browser-wasm/5.0.0-rc.1.20425.18/runtimes/browser-wasm/native/dotnet.wasm'
const bytes = fs.readFileSync(name);
const result =  WebAssembly.instantiate(bytes, {
  imports: { imported_func: arg => console.log(arg) }
}).catch(err => console.error(err));
EOF

$ node --experimental-modules --experimental-wasm-modules test2.mjs
[TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function]
```

### LINKED ISSUE #47336: Developers can run .NET libraries inside Node.js
Node.js sports V8 engine which means it can run WebAssembly code. In the recent Node.js v15.6.0 version initial WASI support was added to further support WASM.

Developers which would like to run .NET code inside Node.js would use publish for wasm target. This will probably mean adding a new RID in form of `node-wasm` or `wasi-wasm`.

Related issues
- [x] #41861

### LINKED ISSUE #62901: [wasm] MarshalTests.MarshalFailedSynchronousTask fail on NodeJs
### Description

System.Runtime.InteropServices.JavaScript.Tests.MarshalTests.MarshalFailedSynchronousTask
System.Runtime.InteropServices.JavaScript.Tests.MarshalTests.MarshalFailedAsynchronousTask

```
ABORT: System.AggregateException: One or more errors occurred. (Exception of type 'System.Exception' was thrown.)
```

### Reproduction Steps

`dotnet build /bl:test.binlog /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Debug /t:Test src/libraries/System.Private.Runtime.InteropServices.JavaScript/tests /p:Scenario=WasmTestOnNodeJs`

### Expected behavior

Tests pass

### Actual behavior

Unit test should pass

### Regression?

No

### Known Workarounds

No

### Configuration

NodeJs v14.16.1 on Windows

### Other information

_No response_

### PR DESCRIPTION
**Pull request by pavelsavara**
### Add WASM test on NodeJS on CI
- new job for scenario `wasmtestonnodejs` in `runtime-manual` pipeline
- wasm CI image bumped to `webassembly-20210707133424-12f133e` with NodeJs upgrade

### RunScript improvements
- unified unix and cmd WasmRunnerTemplate
- added `SetScriptCommands` early in the script templates
- so that the XHarness defaulting logic could happen on Helix based on current `SCENARIO` and `JS_ENGINE` env variables

### SendToHelixHelp
- `WasmTestOnNodeJs` scenario triggers `NeedsEMSDKNode`
- `NeedsEMSDKNode` would take emscripten NodeJs binaries and push it as HelixCorrelationPayload
- because NodeJs version on Helix agent is obsolete

Fixes https://github.com/dotnet/runtime/issues/47336
Fixes https://github.com/dotnet/runtime/issues/41861
Fixes https://github.com/dotnet/runtime/issues/62901

### CODE REVIEW

File: eng/testing/WasmRunnerAOTTemplate.sh [hunk 1]
```diff
@@ -1,11 +1,15 @@
...
+[[SetCommandsEcho]]
 
-cd $EXECUTION_DIR
+EXECUTION_DIR=$(dirname $0)
+if [[ -n "$3" ]]; then
+	SCENARIO=$3
+fi
 
-if [ -z "$HELIX_WORKITEM_UPLOAD_ROOT" ]; then
+if [[ -z "$HELIX_WORKITEM_UPLOAD_ROOT" ]]; then
```
Comment (radekdoulik) [inline eng/testing/WasmRunnerAOTTemplate.sh:12]: What is the reason to use `[[ ... ]]` here instead of `[ ... ]` and in the other places?

File: eng/testing/tests.wasm.targets [hunk 2]
```diff
@@ -22,14 +23,27 @@
...
+  <ItemGroup Condition="'$(OS)' == 'Windows_NT'">
+    <SetScriptCommands Condition="'$(Scenario)' != ''" Include="set &quot;SCENARIO=$(Scenario)&quot;" />
+    <SetScriptCommands Condition="'$(JSEngine)' != ''" Include="set &quot;JS_ENGINE=--engine=$(JSEngine)&quot;" />
+    <SetScriptCommands Condition="'$(JSEngineArgs)' != ''" Include="set &quot;JS_ENGINE_ARGS=$(JSEngineArgs)&quot;" />
+    <SetScriptCommands Condition="'$(_WasmMainJSFileName)' != ''" Include="set &quot;MAIN_JS=--js-file=$(_WasmMainJSFileName)&quot;" />
+  </ItemGroup>
   <PropertyGroup Condition="'$(RunScriptCommand)' == ''">
-    <JSEngine Condition="'$(JSEngine)' == ''">V8</JSEngine>
-    <JSEngineArgs Condition="'$(JSEngine)' == 'V8'">$(JSEngineArgs) --engine-arg=--stack-trace-limit=1000</JSEngineArgs>
-
```
Comment (radekdoulik) [inline eng/testing/tests.wasm.targets:28]: Where are these set now?

File: eng/testing/WasmRunnerAOTTemplate.sh (hunk 1 above)
Comment (pavelsavara) [reply eng/testing/WasmRunnerAOTTemplate.sh:12]: As far as I could tell `[[` is build-in command of bash, and `[` is alias for `test` binary. It should behave same way in this case.

File: eng/testing/tests.wasm.targets (hunk 2 above)
Comment (pavelsavara) [reply eng/testing/tests.wasm.targets:28]: They could be set explicitly by individual .csproj, if they are not, the default value would be calculated in the RunScript on the Helix. See https://github.com/dotnet/runtime/pull/62779/files#diff-5cb02ee3bbdcb7cb7e772808b494689a7c5a83e1539645bfef2003ac78fc7702R37

File: eng/testing/WasmRunnerAOTTemplate.sh (hunk 1 above)
Comment (radekdoulik) [reply eng/testing/WasmRunnerAOTTemplate.sh:12]: It is less portable, so I was curious if there's reason to use it. I guess we can change it again when needed.

File: eng/testing/WasmRunnerTemplate.cmd [hunk 3]
```diff
@@ -35,17 +35,17 @@ if [%XHARNESS_COMMAND%] == [] (
...
         )
 
         if [%MAIN_JS%] == [] (
-            set "MAIN_JS=--js-file=test-main.js"
+            set "MAIN_JS=--js-file^=test-main.js"
         )
 
         if [%JS_ENGINE_ARGS%] == [] (
-            set "JS_ENGINE_ARGS=--engine-arg=--stack-trace-limit=1000"
+            set "JS_ENGINE_ARGS=--engine-arg^=--stack-trace-limit=1000"
```
Comment (radekdoulik) [inline eng/testing/WasmRunnerTemplate.cmd]: I guess you want to escape the other `=` char as well?

File: src/tests/BuildWasmApps/Wasm.Build.Tests/data/RunScriptTemplate.cmd [hunk 4]
```diff
@@ -35,17 +35,17 @@ if [%XHARNESS_COMMAND%] == [] (
...
         )
 
         if [%MAIN_JS%] == [] (
-            set "MAIN_JS=--js-file=test-main.js"
+            set "MAIN_JS=--js-file^=test-main.js"
         )
 
         if [%JS_ENGINE_ARGS%] == [] (
-            set "JS_ENGINE_ARGS=--engine-arg=--stack-trace-limit=1000"
+            set "JS_ENGINE_ARGS=--engine-arg^=--stack-trace-limit=1000"
```
Comment (radekdoulik) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/data/RunScriptTemplate.cmd]: As above.

**Comment by pavelsavara** [comment]
- There are unrelated failing Debugger tests https://github.com/dotnet/runtime/issues/62964
- There is new NodeJs failing test https://github.com/dotnet/runtime/issues/62965 on runtime-manual pipeline
- There are lot of unrelated failures on other platforms on runtime-manual and runtime-staging pipelines

**Review by radekdoulik — APPROVED** [review]
LGTM. It would be nice to have activeissue set on the nodejs failing tests.
