### PR TITLE
arm64: Fix negs compare to minus int.MinValue

### LINKED ISSUE #121294: JIT: Wrong result of comparison against 0 on arm64
```csharp
// Generated by Fuzzlyn v3.3 on 2025-11-02 17:19:53
// Run on Arm64 Linux
// Seed: 3881835425328722402-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256,armsve,armsve2
// Reduced from 15.0 KiB to 0.4 KiB in 00:00:16
// Debug: Prints 1 line(s)
// Release: Prints 2 line(s)
public class Program
{
    public static void Main()
    {
        if ((-M3()) >= 0)
        {
            ulong vr3 = default(ulong);
            System.Console.WriteLine(vr3);
        }
    }

    public static long M3()
    {
        ulong var0 = default(ulong);
        System.Console.WriteLine(var0);
        return -9223372036854775808L;
    }
}
```

Likely caused by #119758, @jonathandavies-arm can you PTAL?

### PR DESCRIPTION
**Pull request by jonathandavies-arm**
* Fixes #121294

### CODE REVIEW

**Comment by jonathandavies-arm** [comment]
@dotnet/arm64-contrib @jakobbotsch Please can I have a review?

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -4435,10 +4435,10 @@ GenTree* Lowering::OptimizeConstCompare(GenTree* cmp)
     }
 
     // Optimize EQ/NE/GT/GE/LT/LE(op_that_sets_zf, 0) into op_that_sets_zf with GTF_SET_FLAGS + SETCC.
-    // For GT/GE/LT/LE don't allow ADD/SUB, runtime has to check for overflow.
+    // For GT/GE/LT/LE don't allow ADD/SUB/NEG, runtime has to check for overflow.
     LIR::Use use;
     if (((cmp->OperIs(GT_EQ, GT_NE) && op2->IsIntegralConst(0) && op1->SupportsSettingZeroFlag()) ||
-         (cmp->OperIs(GT_GT, GT_GE, GT_LT, GT_LE) && op2->IsIntegralConst(0) && !op1->OperIs(GT_ADD, GT_SUB) &&
+         (cmp->OperIs(GT_GT, GT_GE, GT_LT, GT_LE) && op2->IsIntegralConst(0) && !op1->OperIs(GT_ADD, GT_SUB, GT_NEG) &&
           op1->SupportsSettingResultFlags())) &&
```
Comment (jakobbotsch) [inline src/coreclr/jit/lower.cpp]: What is the problem with add, sub and neg? Should `SupportsSettingResultFlags` rather return false for it? It seems that the contract of `SupportsSettingResultFlags` is not clear if the caller has to special case multiple other operators.

Comment (jonathandavies-arm) [reply src/coreclr/jit/lower.cpp]: Those 3 do support setting the results flags including the overflow flag. If that is set and we do a comparison that checks that flag (gt, ge, lt, le) then it will produce a result different from what dotnet expects.

e.g.
```
bool add_gt_zero(int a, int b) => return (a + b) > 0;

add_gt_zero(1, int.MaxValue) // expected result false in dotnet

// Current assembly
add w0, w0, w1
cmp w0, #0
cset w0, gt

// Assembly using adds
adds w0, w0, w1
cset w0, gt
```
In this example the expected result is false in dotnet because ints overflow to negative and we are just testing if the result is > 0. 
If we change to using adds then the overflow flag will be set by adds which doesn't happen with the cmp. Setting the overflow flag will change the result of the gt in this case to true.

I could add a function `SupportsSettingOverflowFlag()` and use that to decide if we do this optimisation. I think we shouldn't remove them from `SupportsSettingResultFlags()` because they do do that.

Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp]: I do not think `SupportsSettingResultFlags` is a useful function since the caller has to make multiple more checks when it returns true.
Can we rename it to `SupportsSettingFlagsAsCompareToZero` and remove `ADD, SUB, NEG` from it?

Comment (SwapnilGaikwad) [reply src/coreclr/jit/lower.cpp]: would it be worth removing the `SupportsSettingResultFlags` altogether as it will be effectively left with only `OperIs(GT_AND, GT_AND_NOT)` check that can be inlined instead?

Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp]: That would be ok with me as well.

Comment (tannergooding) [reply src/coreclr/jit/lower.cpp]: > If we change to using adds then the overflow flag will be set by adds which doesn't happen with the cmp. Setting the overflow flag will change the result of the gt in this case to true.

It sounds like the actual problem here is that we decide to use `adds` but then don't correspondingly update the flag that is getting checked.

That is, `add w0, w0, w1; cmp w0, #0; cset w0, gt` is valid because it does an addition, comparison against 0, and then gt comparison which functionally checks "was this negative". Noting that:
* `cmp w0, #0` is notably equivalent to `subs wzr, w0, #0`
* `cset w0, gt` is equivalent to `csinc w0, wzr, wzr, le`
* we could have instead used `cset w0, mi` as that is logically equivalent given the comparison against 0

So, we're logically doing:
```csharp
// given: `int w0` and `int w1`
w0 += w1

PSTATE.N = (w0 < 0) ? 1 : 0;
PSTATE.Z = (w0 == 0) ? 1 : 0;
PSTATE.C = unsigned_overflow(w0 + w1) ? 1 : 0;
PSTATE.V = signed_overflow(w0 + w1) ? 1 : 0;

return ((PSTATE.N == PSTATE.V) && (PSTATE.Z == 0)) ? 0 : 1;
```

The transform to `adds w0, w0, w1; cset w0, gt` is then invalid because we're no longer doing the equivalent of "was this result negative". What should be happening is that when we drop the `cmp w0, #0` we also change the `cset w0, gt` into `cset w0, mi` which ensures that we're then logically doing the same operation as the comparison

We could notably, in this particular case, also update the `adds` to not use the result since it's not used outside the flags check. That is, the "optimal" sequence here is `adds wzr, w0, w1; cset w0, mi`

Similar optimizations are possible for `subs`, `negs`, and other flags checks.

Comment (tannergooding) [reply src/coreclr/jit/lower.cpp]: The same is notably true for xarch and this looks like the current runtime checks are pessimizing that.

That is, we shouldn't be skipping the optimization. We should be updating the flag checked to ensure the logical operation is equivalent.

`if (x < 0)` for `unsigned` is always `false` and so should've been optimized out as dead code. While for `signed` it's simply doing a "is the sign bit set" check and so on xarch should be checking `SF` instead of `ZF` to keep it valid.

Comment (jonathandavies-arm) [reply src/coreclr/jit/lower.cpp]: >     * `cmp w0, #0` is notably equivalent to `subs wzr, w0, #0`
>     * `cset w0, gt` is equivalent to `csinc w0, wzr, wzr, le`
>     * we could have instead used `cset w0, mi` as that is logically equivalent given the comparison against 0

In this case I don't think we can use `cset w0, mi`. In order to use `adds` I think it would require multiple cset and a `and`. 
There might be a way to only have a single cset or csinc but I need to think about it more.

I've got a commit that removes `SupportsSettingResultFlags` that I'll push shortly. I think we should merge that to fix the issue. I'm also writing up a new issue to look into using `adds` and changing the comparison suffix to make sure we have the correct behaviour. I'll link it when it is created.

Comment (tannergooding) [reply src/coreclr/jit/lower.cpp]: Could you elaborate on why would it require multiple flags?

The check behind performed would be logically the same given the comparison against 0.

Comment (jonathandavies-arm) [reply src/coreclr/jit/lower.cpp]: If we have this code
```
int add_gt_zero(int a, int b) => a + b > 0;
```
and we change the assembly from
```
add w0, w0, w1
cmp w0, #0
cset w0, gt
```
to
```
adds w0, w0, w1
cset w0, mi
```
I think it will produce an incorrect result. 

After the adds we need to check that the result is positive (`pl`) but that is also true when the result is zero. So we would have to also check it isn't zero (`ne'). I think there should be a way to do it in a single instruction but I need to think about what it should be.

Comment (jonathandavies-arm) [reply src/coreclr/jit/lower.cpp]: https://github.com/dotnet/runtime/issues/121445

Comment (tannergooding) [reply src/coreclr/jit/lower.cpp]: Ah, I see. Because it's `> 0` you logically need `(N == 0) && (Z == 0)`. While there is only `(N == V) && (Z == 0)` or `(C == 1) && (Z == 0)` (and their inverses) available.

`>= 0` (ge) or `> -1` (gt) would be fine as would `< 0` (lt) or `<= -1` (le), but `> 0` (gt) and `<= 0` (le) are problematic. 

Likewise since `csinc`, `csinv`, and `csneg` only take registers, you can't do anything "clever" with them either unless you already have a register with `1` available in it.

That's unfortunate, but it is what it is.

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -19922,42 +19917,18 @@ bool GenTree::SupportsSettingZeroFlag()
...
-{
-#if defined(TARGET_ARM64)
+#elif defined(TARGET_ARM64)
     if (OperIs(GT_AND, GT_AND_NOT))
     {
         return true;
     }
 
-    // We do not support setting result flags if neg has a contained mul
+    // We do not support setting zero flag for madd/msub.
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:19926]: I don't expect many readers will know that `mneg` is just an alias of `msub`. We should probably keep it explicitly called out, especially since its the preferred name/disassembly.

**Review by tannergooding — APPROVED** [review]
This resolves the issue and any potential regressions are tracked by https://github.com/dotnet/runtime/issues/121445

File: src/coreclr/jit/lower.cpp [hunk 3]
```diff
@@ -4435,11 +4435,9 @@ GenTree* Lowering::OptimizeConstCompare(GenTree* cmp)
     }
 
     // Optimize EQ/NE/GT/GE/LT/LE(op_that_sets_zf, 0) into op_that_sets_zf with GTF_SET_FLAGS + SETCC.
-    // For GT/GE/LT/LE don't allow ADD/SUB, runtime has to check for overflow.
     LIR::Use use;
     if (((cmp->OperIs(GT_EQ, GT_NE) && op2->IsIntegralConst(0) && op1->SupportsSettingZeroFlag()) ||
-         (cmp->OperIs(GT_GT, GT_GE, GT_LT, GT_LE) && op2->IsIntegralConst(0) && !op1->OperIs(GT_ADD, GT_SUB) &&
-          op1->SupportsSettingResultFlags())) &&
+         (cmp->OperIs(GT_GT, GT_GE, GT_LT, GT_LE) && op2->IsIntegralConst(0) && op1->OperIs(GT_AND, GT_AND_NOT))) &&
```
Comment (jakobbotsch) [inline src/coreclr/jit/lower.cpp]: I do not expect that all backends with support for `GT_AND` and `GT_AND_NOT` will support this transformation.
So we need `SupportsSettingFlagsAsCompareToZero` that's properly conditioned on the backend's support after all. (And also, looks like this is a slight pessimization on xarch over its current codegen.)
arm64 and arm32 both look like they benefit from this, though.

File: src/coreclr/jit/gentree.cpp [hunk 4]
```diff
@@ -19938,6 +19938,19 @@ bool GenTree::SupportsSettingZeroFlag()
...
 }
 
+//------------------------------------------------------------------------
+// SupportsSettingFlagsAsCompareToZero: Returns true if we support setting
+// flags for compare to zero operations.
+//
+bool GenTree::SupportsSettingFlagsAsCompareToZero()
+{
+#if defined(TARGET_ARM64)
+    return true;
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.cpp]:
```suggestion
#if defined(TARGET_ARMARCH)
    return OperIs(GT_AND, GT_AND_NOT);
```

File: src/coreclr/jit/lower.cpp [hunk 5]
```diff
@@ -4437,7 +4437,7 @@ GenTree* Lowering::OptimizeConstCompare(GenTree* cmp)
     // Optimize EQ/NE/GT/GE/LT/LE(op_that_sets_zf, 0) into op_that_sets_zf with GTF_SET_FLAGS + SETCC.
     LIR::Use use;
     if (((cmp->OperIs(GT_EQ, GT_NE) && op2->IsIntegralConst(0) && op1->SupportsSettingZeroFlag()) ||
-         (cmp->OperIs(GT_GT, GT_GE, GT_LT, GT_LE) && op2->IsIntegralConst(0) && op1->OperIs(GT_AND, GT_AND_NOT))) &&
+         (cmp->OperIs(GT_GT, GT_GE, GT_LT, GT_LE) && op2->IsIntegralConst(0) && op1->OperIs(GT_AND, GT_AND_NOT) && op1->SupportsSettingFlagsAsCompareToZero())) &&
```
Comment (jakobbotsch) [inline src/coreclr/jit/lower.cpp]:
```suggestion
         (cmp->OperIs(GT_GT, GT_GE, GT_LT, GT_LE) && op2->IsIntegralConst(0) && op1->SupportsSettingFlagsAsCompareToZero())) &&
```

**Comment by a74nh** [comment]
@jakobbotsch thanks for fixing this up. This looks good to me now? The failures are just CI issues

**Review by jakobbotsch — APPROVED** [review]
Thanks
