### PR TITLE
Handle blittable byref returns in built-in marshalling

### LINKED ISSUE #72316: [NativeAOT] Can't call a function pointer with a ref return value
### Description

In some cases with the System V ABI, when a "complex" type is returned, the caller is expected to allocate memory for the return value, and pass a pointer to that memory as a hidden first argument.

I'm trying to call a function that uses that convention, so I looked at how to instruct the runtime to do so. It looks like that may be the case when returning by ref: https://github.com/dotnet/runtime/blob/05473449c1db9edbbbc565b39d73a59bf517de96/src/coreclr/vm/callingconvention.h#L1784
(note: I may be misinterpreting this code, since I haven't been able to try)

However, when trying to call an unmanaged pointer with a `ref` return value, the NativeAOT compilation fails.

### Reproduction Steps

Create a new project, declare a function pointer with a `ref` return value, and try calling it:

```csharp
public struct TestStruct
{
}

public static unsafe void CreateFunctionPointer(IntPtr address)
{
    var functionPointer = (delegate* unmanaged[Cdecl, MemberFunction]<IntPtr, ref TestStruct>)address;
    functionPointer(IntPtr.Zero);
}
```

Then try compiling it with NativeAOT:

```
dotnet publish /p:SelfContained=true -r win-x64 -c Release
```

### Expected behavior

The call should work.

### Actual behavior

An error is thrown during compilation:

```
  Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeNativeAOT
EXEC : error : VTable of type 'System.Runtime.InteropServices.MarshalDirectiveException' not computed by the IL scanner. You c
an work around by running the compilation with scanner disabled. [C:\Users\kevin\source\repos\TestNativeAot\TestNativeAot\Test
NativeAot.csproj]
  ILCompiler.ScannerFailedException: VTable of type 'System.Runtime.InteropServices.MarshalDirectiveException' not computed by
   the IL scanner. You can work around by running the compilation with scanner disabled.
     at ILCompiler.ILScanResults.ScannedVTableProvider.GetSlice(TypeDesc type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler
  /Compiler/ILScanner.cs:line 282
     at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
     at ILCompiler.DependencyAnalysis.ConstructedEETypeNode.ComputeNonRelocationBasedDependencies(NodeFactory factory) in /_/s
  rc/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ConstructedEETypeNode.cs:line 64
     at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory factory) in /_/src/coreclr/tools/Common/Com
  piler/DependencyAnalysis/ObjectNode.cs:line 59
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node) in /_
  /src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 181
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node) in /_/src
  /coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 221
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() in /_/src/coreclr/tools/aot/ILCompiler.
  DependencyAnalysisFramework/DependencyAnalyzer.cs:line 256
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /_/src/coreclr/tools/aot/ILCompile
  r.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 307
     at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper) in /_/src/coreclr/tools/aot/ILCom
  piler.RyuJit/Compiler/RyuJitCompilation.cs:line 88
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper) in /_/src/coreclr/tools
  /aot/ILCompiler.Compiler/Compiler/Compilation.cs:line 526
     at ILCompiler.Program.Run(String[] args) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 898
     at ILCompiler.Program.Main(String[] args) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 1090
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #72316

### CODE REVIEW

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs [hunk 1]
```diff
@@ -515,16 +510,16 @@ public static partial class MarshalHelpers
...
             else if (type.IsPointer)
             {
-                if (nativeType == NativeTypeKind.Default)
+                type = type.GetParameterType();
+
+                if (type.IsValueType && !type.IsPrimitive && !type.IsEnum && !isField
+                    && HasCopyConstructorCustomModifier(parameterIndex, customModifierData))
                 {
-                    var pointedAtType = type.GetParameterType();
-                    if (!pointedAtType.IsPrimitive && !type.IsEnum && marshallerType != MarshallerType.Field
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:521]: `!type.IsEnum` was always false here since `type` was a byref.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs [hunk 2]
```diff
@@ -228,29 +225,35 @@ public static partial class MarshalHelpers
...
+                nativeType = marshalAs.Type;
+
             if (type.IsByRef)
             {
-                isByRef = true;
-
                 type = type.GetParameterType();
 
-                if (!type.IsPrimitive && type.IsValueType && marshallerType != MarshallerType.Field
+                if (type.IsValueType && !type.IsPrimitive && !type.IsEnum && !isField
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:239]: Trying to make these conditions consistent and more in sync with CoreCLR logic. This path should be only ever used by managed C++ so it does not matter a while lot anyway.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.Aot.cs [hunk 3]
```diff
@@ -1279,4 +1282,15 @@ protected void EmitCleanUpNativeData(ILCodeStream codeStream)
...
         }
     }
+
+    class BlittableValueClassByRefReturn : Marshaller
+    {
+        protected override void SetupArgumentsForReturnValueMarshalling()
+        {
+            ILEmitter emitter = _ilCodeStreams.Emitter;
+
+            _managedHome = new Home(emitter.NewLocal(ManagedParameterType), ManagedParameterType, isByRef: false);
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.Aot.cs:1292]: We just need to create locals of the right type. The default implementation works fine otherwise.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs [hunk 4]
```diff
@@ -452,14 +455,6 @@ public static partial class MarshalHelpers
             }
             else if (type.IsSzArray)
             {
-#if READYTORUN
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:455]: Is it okay to delete these before #69758 is done?

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs (hunk 4 above)
Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:455]: Yes, it is okay to delete this. We are only generating no-op blittable marshallers for R2R now. Arrays are never blittable.
