### PR TITLE
[Experiment] Clone blocks with bounds checks

### LINKED ISSUE #109983: Neighboring bounds checks aren't collapsed
### Description

Given the following code:

```csharp
public static uint Test(ReadOnlySpan<uint> span) =>
    span[0] + span[1] + span[2] + span[3];
```

The only way for this method to fail a bounds/range check is if `span.Length < 4`. As such, I'd expect the runtime to optimize to something like this:
```csharp
public static uint Test(ReadOnlySpan<uint> span)
{
    if (span.Length <= 3)
        CORINFO_HELP_RNGCHKFAIL();
    return span[0] + span[1] + span[2] + span[3];
}
```

Instead, [the runtime generates this](https://godbolt.org/z/drT7edGfz):

```assembly
// coreclr trunk-20241119+e33be4d53ab951272c9161c50b549e5e7db60262

Klass:Test(System.ReadOnlySpan`1[uint]):uint (FullOpts):
       push     rax
       test     esi, esi
       je       SHORT G_M30269_IG04
       mov      eax, dword ptr [rdi]
       cmp      esi, 1
       jbe      SHORT G_M30269_IG04
       add      eax, dword ptr [rdi+0x04]
       cmp      esi, 2
       jbe      SHORT G_M30269_IG04
       add      eax, dword ptr [rdi+0x08]
       cmp      esi, 3
       jbe      SHORT G_M30269_IG04
       add      eax, dword ptr [rdi+0x0C]
       add      rsp, 8
       ret      
G_M30269_IG04:  ;; offset=0x0024
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
```

Note the four range checks against `esi`. Failures all call into `CORIFNO_HELP_RNGCHKFAIL` with no indication of which failed. As such, I'd expect the four compare+branch blocks to collapse into a singular one like this:

```assembly
       cmp esi, 3
       jbe SHORT_G_M30269_IG04
       mov eax, dword ptr [rdi]
       add eax, dword ptr [rdi+0x04]
       add eax, dword ptr [rdi+0x08]
       add eax, dword ptr [rdi+0x0C]
       ret      
G_M30269_IG04:  ;; offset=0x00__
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
```

### Configuration

Godbolt Compiler Explorer against "trunk" (e33be4d53ab951272c9161c50b549e5e7db60262)

### Regression?

No. Present in [net7.0.19](https://godbolt.org/z/8GYc7KKMj) and [net8.0.5](https://godbolt.org/z/fdr6zPPY8).

### Notes

Interestingly, [a naive loop generates nearly the same assembly](https://godbolt.org/z/WMvWen8zr), but sets up and tears down a frame:

```csharp
public static uint Test(ReadOnlySpan<uint> span)
{
    uint sum = 0;
    for (int i = 0; i < 4; i++)
        sum += span[i];
    return sum;
}
```

```assembly
// coreclr trunk-20241119+e33be4d53ab951272c9161c50b549e5e7db60262

Klass:Test(System.ReadOnlySpan`1[uint]):uint (FullOpts):
       push     rbp
       mov      rbp, rsp
       test     esi, esi
       je       SHORT G_M30269_IG04
       mov      eax, dword ptr [rdi]
       cmp      esi, 1
       jbe      SHORT G_M30269_IG04
       add      eax, dword ptr [rdi+0x04]
       cmp      esi, 2
       jbe      SHORT G_M30269_IG04
       add      eax, dword ptr [rdi+0x08]
       cmp      esi, 3
       jbe      SHORT G_M30269_IG04
       add      eax, dword ptr [rdi+0x0C]
       pop      rbp
       ret      
G_M30269_IG04:  ;; offset=0x0024
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
```

### LINKED ISSUE #112524: JIT: Block clonning for subsequent bounds checks
If we have:
```cs
void Test(int[] arr, int i)
{
    arr[i + 0] = 0;
    arr[i + 1] = 0;
    arr[i + 2] = 0;
    arr[i + 3] = 0;
}
```
Which generates a single BasicBlock with either multiple statements or a single statement with multiple COMMAs containing STOREIND node, we should be able to just clone it and remove all bound checks in the fast path:
```cs
public void Test(int[] arr, int i)
{
    if (i >= 0 && i < arr.Length - 3)
    {
        // Fast path: no bounds checks
        arr[i + 0] = 0;
        arr[i + 1] = 0;
        arr[i + 2] = 0;
        arr[i + 3] = 0;
    }
    else
    {
        // Slow fallback
        arr[i + 0] = 0;
        arr[i + 1] = 0;
        arr[i + 2] = 0;
        arr[i + 3] = 0;
    }
}
```
So, essentially, a loop clonning but for non-loop stuff.

cc @dotnet/jit-contrib opinions? such patterns aren't uncommon in BCL

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/112524
Closes https://github.com/dotnet/runtime/issues/109983

For an arbitrary block
```cs
arr[i + 1] = x;
arr[i + 3] = y;
arr[i + 5] = z;
arr[i + 6] = w;
```
In order to remove bounds checks, JIT can clone the whole thing to have fast and slow paths under "block clonning conditions":
```cs
if (i >= 0 && i < arr.Length - 6)
{
    // fast path
    arr[i + 1] = x; // no bounds check
    arr[i + 3] = y; // no bounds check
    arr[i + 5] = z; // no bounds check
    arr[i + 6] = w; // no bounds check
}
else
{
    // slow path
    arr[i + 1] = x;
    arr[i + 3] = y;
    arr[i + 5] = w;
    arr[i + 6] = w;
}
```

It works not only for stores, but for any expressions with bounds checks, e.g. `arr[1] + arr[2] + arr[3]`

### Codegen example:
```cs
void Test(int[] arr)
{
    arr[0] = 10;
    arr[1] = 11;
    arr[2] = 12;
    arr[3] = 13;
}
```
Current codegen (4 bounds checks):
```asm
; Assembly listing for method Proga:Test(int[]):this (FullOpts)
    stp     fp, lr, [sp, #-0x10]!
    mov     fp, sp
    ldr     w0, [x1, #0x08]

    ;; arr[0] = 10
    cbz     w0, G_M65333_IG04
    mov     w2, #10
    str     w2, [x1, #0x10]

    ;; arr[1] = 11
    cmp     w0, #1
    bls     G_M65333_IG04
    mov     w2, #11
    str     w2, [x1, #0x14]

    ;; arr[2] = 12
    cmp     w0, #2
    bls     G_M65333_IG04
    mov     w2, #12
    str     w2, [x1, #0x18]

    ;; arr[3] = 13
    cmp     w0, #3
    bls     G_M65333_IG04
    mov     w0, #13
    str     w0, [x1, #0x1C]

    ldp     fp, lr, [sp], #0x10
    ret     lr
G_M65333_IG04:
    bl      CORINFO_HELP_RNGCHKFAIL
    brk     #0
; Total bytes of code 88
```

New codegen (single SIMD store in the fast path!):
```asm
; Assembly listing for method Proga:Test(int[]) (FullOpts)
    stp     fp, lr, [sp, #-0x10]!
    mov     fp, sp
    ldr     w1, [x0, #0x08]
    sxtw    w2, w1
    cmp     w1, #3
    ble     G_M50025_IG05
    ldr     q16, [@RWD00]
    str     q16, [x0, #0x10] ;; <-- single Vector128 store!
G_M50025_IG04:
    ldp     fp, lr, [sp], #0x10
    ret     lr

    ;; Slow path (cold block):
G_M50025_IG05:
    cbz     w2, G_M50025_IG06
    mov     w2, #10
    str     w2, [x0, #0x10]
    cmp     w1, #1
    bls     G_M50025_IG06
    mov     w2, #11
    str     w2, [x0, #0x14]
    cmp     w1, #2
    bls     G_M50025_IG06
    mov     w2, #12
    str     w2, [x0, #0x18]
    cmp     w1, #3
    bls     G_M50025_IG06
    mov     w1, #13
    str     w1, [x0, #0x1C]
    b       G_M50025_IG04
G_M50025_IG06:
    bl      CORINFO_HELP_RNGCHKFAIL
    brk     #0
RWD00  	dq	0000000B0000000Ah, 0000000D0000000Ch
; Total bytes of code 112
```

### CODE REVIEW

**Comment by EgorBo** [comment]
image

Seems like PerfScore improvement as expected. TP cost can be improved to be around +0.2%
Although, looks like it is better to do this after general range check phase. But that would require us to actually drop the bounds checks,.

**Comment by EgorBo** [comment]
This PR also sort of closes https://github.com/dotnet/runtime/issues/109983

image

For this case we don't have to clone the blocks actually, but it's better than nothing 🙂

**Comment by EgorBo** [comment]
@EgorBot -amd -arm --filter *benchmarkLU*

**Comment by EgorBo** [comment]
@EgorBot -amd -arm
```cs
using BenchmarkDotNet.Attributes;

public class Bench
{
    static int[] _arr = new int[2000];

    [Benchmark]
    [Arguments(42, 1000)]
    public void Loop(int offset, int len)
    {
        for (int i = offset; i < len; i++)
        {
            _arr[i + 0] = 0;
            _arr[i + 1] = 0;
            _arr[i + 2] = 0;
            _arr[i + 3] = 0;
        }
    }

    [Benchmark]
    public void Scalar()
    {
        _arr[0] = 10;
        _arr[1] = 11;
        _arr[2] = 12;
        _arr[3] = 13;
    }
}
```

**Comment by EgorBo** [comment]
Actually, this should be good as is (as a start). [Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=954040&view=ms.vss-build-web.run-extensions-tab) - obviously, a size regression, but mostly a clean PerfScore improvement:

image

The PR basically just scans all GT_BOUNDS_CHECK node in a block, then groups them by "base indexVN + lengthVN" in a dictionary (sort of `Dictionary<(baseVN, lenVN), BoundsCheck>`), takes the one group with the most bounds checks, calculate their Statement range, split the block at the very first bounds check in the group (so the length and the index of the first bounds check are spilled if they have side effects) and clone the rest. Then repeats the same in case if we have more groups.

I decided to perform this optimization after the range check phase - it allows me to handle only those bounds checks nobody was able to handle before me. A bit unfortunate phase ordering issue is that CSE sometimes decides to perform CSE for the index tree (because it's used in the bounds check and the actual array access) and when my algorithm drops the bounds check node, we're left with a redundant local:

image

This is main source of the regressions - it'd be nice to have some late forward sub to clean these up. Also, this issue is solved with JitOptRepeat, perhaps, my phase could request an extra iteration of that in the future (not today as JitOptRepeat has issues).

PTAL @jakobbotsch @AndyAyersMS @dotnet/jit-contrib

File: src/coreclr/jit/compiler.h [hunk 1]
```diff
@@ -3809,7 +3810,8 @@ class Compiler
     bool gtStoreDefinesField(
         LclVarDsc* fieldVarDsc, ssize_t offset, unsigned size, ssize_t* pFieldStoreOffset, unsigned* pFieldStoreSize);
 
-    void gtPeelOffsets(GenTree** addr, target_ssize_t* offset, FieldSeq** fldSeq = nullptr);
+    void gtPeelOffsets(GenTree** addr, target_ssize_t* offset, FieldSeq** fldSeq = nullptr) const;
+    static void gtPeelOffsetsI32(GenTree** addr, int* offset);
```
Comment (jakobbotsch) [inline src/coreclr/jit/compiler.h:3814]: Looks unused?

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 2]
```diff
@@ -0,0 +1,520 @@
...
+        assert(bndChkParent->OperIs(GT_COMMA));
+        if (bndChkParent->gtGetOp2() == bndChkNode)
+        {
+            // GT_BOUNDS_CHECK is mostly LHS of COMMAs.
+            // In rare cases, it can be either a root node or RHS of COMMAs
+            // Unfortunately, optRemoveRangeCheck doesn't know how to handle it
+            // being RHS of COMMAs. TODO-RangeCheckCloning: fix that
+            return false;
+        }
+    }
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:84]: Is this phase using range check still? Seems like this can be removed?

Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:84]: hm.. not sure I understand the question. This phase is ran in the main opt loop, bounds checks are removed in codegen.
If you asking whether we can see such an IR then the answer is yes (a few hits accross all collections) - I just didn't want to touch the existing optRemoveRangeCheck as part of this PR, could be done separately (to inspect the diffs)

File: src/coreclr/jit/compiler.h (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/compiler.h:3814]: Yep, an artifact from the previous impl when the phase was after Loop Clonning.

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 3]
```diff
@@ -0,0 +1,520 @@
...
+        JITDUMP("Current method has no bounds checks\n");
+        return PhaseStatus::MODIFIED_NOTHING;
+    }
+
+    if (lvaHaveManyLocals(0.75))
+    {
+        // If we're close to running out of locals, we should be conservative
+        JITDUMP("Too many locals - bail out.\n");
+        return PhaseStatus::MODIFIED_NOTHING;
+    }
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:399]: Why? Did you see any cases here?

I think it would be preferable to avoid checks like these if we can since it does not take anything about references or hotness/coldness into account. All that stuff is taken into account by the code that picks which locals to track.

Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:399]: I've seen impact from this in my initial version I think, for this one - no diffs, will remove

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 4]
```diff
@@ -0,0 +1,520 @@
...
+        // Now choose the largest group of bounds checks (the one with the most checks)
+        BoundsCheckInfoStack* largestGroup = nullptr;
+        for (BoundsCheckInfoMap::Node* keyValuePair : BoundsCheckInfoMap::KeyValueIteration(&bndChkMap))
+        {
+            ArrayStack<BoundsCheckInfo>* value = keyValuePair->GetValue();
+            if ((largestGroup == nullptr) || (value->Height() > largestGroup->Height()))
+            {
+                largestGroup = value;
+            }
+        }
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:500]: Why not do it for all groups? It seems arbitrary that if I split a block then the optimization might kick in more.

Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:500]: I'd like to try that in a separate PR to estimate an impact if you don't mind - one of my intermediate commit supported it

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 5]
```diff
@@ -0,0 +1,520 @@
...
+
+    JITDUMP("\nUpper bound check:\n");
+    DISPTREE(jtrue);
+
+    // 3) fallbackBb:
+    //
+    // For the fallback (slow path), we just entirely clone the fast path.
+    //
+    BasicBlock* fallbackBb = comp->fgNewBBafter(BBJ_ALWAYS, upperBndBb, false);
+    BasicBlock::CloneBlockState(comp, fallbackBb, fastpathBb);
```
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:256]: Good point!

File: src/coreclr/jit/rangecheckcloning.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:500]: One problem is how to propagate side effects from the first bounds checks of secondary groups. Today, I just do `gtSplitTree` on the first bounds check and it handles side effect ordering issue for me naturally

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 6]
```diff
@@ -0,0 +1,520 @@
...
+    fgWalkResult PostOrderVisit(GenTree** use, GenTree* user)
+    {
+        GenTree* node = *use;
+        if (node->OperIs(GT_BOUNDS_CHECK))
+        {
+            m_boundsChks->Push(BoundCheckLocation(m_stmt, node->AsBoundsChk(), user));
+        }
+        return fgWalkResult::WALK_CONTINUE;
+    }
+};
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:372]: If you do this in preorder you can use `GTF_EXCEPT` to quickly locate the bounds checks in each statement.

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 7]
```diff
@@ -0,0 +1,520 @@
...
+        if (block->isRunRarely())
+        {
+            continue;
+        }
+
+        if (!block->KindIs(BBJ_ALWAYS, BBJ_RETURN, BBJ_COND))
+        {
+            // For now, we support only simple blocks
+            continue;
+        }
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:437]: What support is missing for this?

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 8]
```diff
@@ -0,0 +1,520 @@
...
+
+        bndChkLocations.Reset();
+        bndChkMap.RemoveAll();
+
+        for (Statement* const stmt : block->Statements())
+        {
+            if (block->KindIs(BBJ_COND, BBJ_RETURN) && (stmt == block->lastStmt()))
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:444]:
```suggestion
            if (block->HasTerminator()&& (stmt == block->lastStmt()))
```

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 9]
```diff
@@ -0,0 +1,520 @@
...
+        }
+
+        if (!block->KindIs(BBJ_ALWAYS, BBJ_RETURN, BBJ_COND))
+        {
+            // For now, we support only simple blocks
+            continue;
+        }
+
+        bndChkLocations.Reset();
+        bndChkMap.RemoveAll();
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:440]:
```suggestion
```
? Weren't these just allocated?

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 10]
```diff
@@ -0,0 +1,520 @@
...
+            {
+                IdxLenPair            key(bci.idxVN, bci.lenVN);
+                BoundsCheckInfoStack* value;
+                if (!bndChkMap.Lookup(key, &value))
+                {
+                    CompAllocator allocator = getAllocator(CMK_RangeCheckCloning);
+                    value                   = new (allocator) BoundsCheckInfoStack(allocator);
+                    bndChkMap.Set(key, value);
+                }
+                value->Push(bci);
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:481]:
```suggestion
                BoundsCheckInfoStack** value = bndCheckMap.LookupPointerOrAdd(key, nullptr);
                if (*value == nullptr)
                {
                    CompAllocator allocator = getAllocator(CMK_RangeCheckCloning);
                    *value                  = new (allocator) BoundsCheckInfoStack(allocator);
                }
                (*value)->Push(bci);
```

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 11]
```diff
@@ -0,0 +1,520 @@
...
+// Return Value:
+//    true if the initialization was successful, false otherwise.
+//
+bool BoundsCheckInfo::Initialize(const Compiler*   comp,
+                                 Statement*        statement,
+                                 GenTreeBoundsChk* bndChkNode,
+                                 GenTree*          bndChkParentNode)
+{
+    idxVN = comp->vnStore->VNConservativeNormalValue(bndChkNode->GetIndex()->gtVNPair);
+    lenVN = comp->vnStore->VNConservativeNormalValue(bndChkNode->GetArrayLength()->gtVNPair);
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:63]: I think since the length is removed we would want to include the exception set here, for the length only.

File: src/coreclr/jit/rangecheckcloning.cpp (hunk 7 above)
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:437]: I think nothing, your suggestion with `HasTerminator` should handle it

File: src/coreclr/jit/rangecheckcloning.cpp (hunk 9 above)
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:440]: I reset them when I switch to a new block (to avoid allocating them for each block)

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 12]
```diff
@@ -388,6 +388,56 @@ class BoundsChecksVisitor final : public GenTreeVisitor<BoundsChecksVisitor>
...
+
+    // Some arbitrary limit just in case
+    if (bndChks->Height() > 64)
+    {
+        JITDUMP("\tExceeded the maximum number of bounds checks: %d\n", bndChks->Height());
+        return true;
+    }
+
+    // We're relying on GetCostSz to avoid walking the trees again.
+    // We assume the costs are initialized and relatively accurate.
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:418]: It seems ok to me to use `GetCostSz`, but @AndyAyersMS may have some feedback since he ended up not using it for loop cloning (why?). Also I wouldn't expect it to be that expensive to use `gtComplexityExceeds` since this code runs only  in the case where we are actually optimizing.

File: src/coreclr/jit/rangecheckcloning.cpp (hunk 11 above)
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:63]: Ended up introducing my own optRemoveRangeCheck without relaxations for side-effects like we've discussed offline.

File: src/coreclr/jit/rangecheckcloning.cpp (hunk 12 above)
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:471]: Yeah it was not about saving TP (this PR has a minor impact on it), but the fact that CostSz takes into account the complexity of trees, not just their amount? Of course, if it's accurate/maintained

File: src/coreclr/jit/rangecheckcloning.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply src/coreclr/jit/rangecheckcloning.cpp:315]: Yeah I would vote for using `gtComplexityExceeds` or `block->ComplexityExceeds` so we are closer to doing things in a common way in the places we decide to duplicate blocks.

There's a lot of logic in loop cloning that you could potentially reuse here. Any thoughts on trying to leverage that?

[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:315]: @AndyAyersMS 

> Yeah I would vote for using gtComplexityExceeds

Ok, switched to `gtComplexityExceeds`

> There's a lot of logic in loop cloning that you could potentially reuse here. Any thoughts on trying to leverage that?

To be fair, I don't see much. If you don't mind, I'd like to experiment/land more improvements to this impl. Then, perhaps, come up with some generic way to split a block (or a sub-graph of blocks) at an arbitrary tree with a condition. And use that for loop cloning as well

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 13]
```diff
@@ -0,0 +1,644 @@
...
+//    This function is a copy of optRemoveRangeCheck, but without questionable
+//    relaxations around side effect extractions.
+//
+// Arguments:
+//    comp  - compiler instance
+//    check - bounds check node to remove
+//    comma - check's parent node (either null or COMMA)
+//    stmt  - statement containing the bounds check
+//
+static void RemoveBoundsChk(Compiler* comp, GenTreeBoundsChk* check, GenTree* comma, Statement* stmt)
```
Comment (jakobbotsch) [inline src/coreclr/jit/rangecheckcloning.cpp:113]: If you are copying this out anyway then why not change it to support any bounds check, by just taking the `GenTree**` for the bounds check?

Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:113]: @jakobbotsch can you elaborate? what kind of benchmarks it does not support now?

File: src/coreclr/jit/rangecheckcloning.cpp [hunk 14]
```diff
@@ -0,0 +1,644 @@
...
+    {
+        // No side effects, just bash the bounds check to NOP.
+        check->gtBashToNOP();
+    }
+
+    if (tree->OperIs(GT_COMMA))
+    {
+        // We can no longer CSE the GT_COMMA.
+        tree->gtFlags |= GTF_DONT_CSE;
+    }
```
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:158]: what about jitoptrepeat? also, this is copied from rangecheck

File: src/coreclr/jit/rangecheckcloning.cpp (hunk 13 above)
Comment (jakobbotsch) [reply src/coreclr/jit/rangecheckcloning.cpp:113]: Any embedded statement that isn't `GT_COMMA` (e.g. `GT_CALL` setup nodes).
I think it would be an overall simplification of the code to stop caring about the parent of the bounds check.

Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:113]: > Any embedded statement that isn't GT_COMMA (e.g. GT_CALL setup nodes).

sorry, still don't understand. We have a bounds check that can be either root (then its user is Statement, not some other node) or COMMA (in which case we can re-use the comma to propagate side effects from the bounds check) - how can `GenTree**` argument help here?

Comment (jakobbotsch) [reply src/coreclr/jit/rangecheckcloning.cpp:113]: If a `BOUNDS_CHECK` ever ends up as the setup node in `GT_CALL` then your pass will hit this assertion:
https://github.com/dotnet/runtime/blob/8f867f64556bf267d68376230134642a84a8e4c6/src/coreclr/jit/rangecheckcloning.cpp#L73
It should be legal IR to have any embedded statement as a setup node in calls. If we ever end up with other forms of embedded statements, then it should also be legal to have bounds checks inside those.

To fix this, I think you can just remove `BoundCheckLocation::bndChkParent` and change `BoundCheckLocation::bndChk` to a `GenTree**` that points to the use (which you save in `BoundsCheckVisitor::PostOrderVisit`). Then you have the edge already on hand when you need to remove the bounds checks in this function.

Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp:113]: Ah, thanks! I thought about it too, but I assumed that I would need the actual parent anyway to use it as a split point for the last check, but I presume I can just find it by hands if I ever need it

File: src/coreclr/jit/rangecheckcloning.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp]: I see, thanks! Removed

File: src/coreclr/jit/rangecheckcloning.cpp (hunk 13 above)
Comment (EgorBo) [reply src/coreclr/jit/rangecheckcloning.cpp]: Thanks for the suggestion - addressed!

**Review by jakobbotsch — APPROVED** [review]
This LGTM now. Cool opt 🙂
