### PR TITLE
fix Alpine build break

### LINKED ISSUE #4345: All Alpine319 legs are failed to build CoreCLR component
`main` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2434119

Working build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2433339&view=logs&s=9b073b6c-199e-5782-2adb-83c30ea48e21&j=b9abe003-a5da-5729-0444-865506f15e35

Error:

      /vmr/src/runtime/src/coreclr/debug/daccess/cdac.cpp:51:25: error: assigning to 'intptr_t' (aka 'long') from incompatible type 'std::nullptr_t'
         51 |         m_cdac_handle = NULL;
            |                         ^~~~
      /usr/include/time.h:11:14: note: expanded from macro 'NULL'
         11 | #define NULL nullptr
            |              ^~~~~~~
      /vmr/src/runtime/src/coreclr/debug/daccess/cdac.cpp:65:23: error: invalid operands to binary expression ('intptr_t' (aka 'long') and 'std::nullptr_t')
         65 |     if (m_cdac_handle != NULL)
            |         ~~~~~~~~~~~~~ ^  ~~~~
      2 errors generated.

### PR DESCRIPTION
**Pull request by lambdageek**
Apline defines NULL as std::nullptr which is not comparable/assignable with intptr_t

Fixes https://github.com/dotnet/source-build/issues/4345

### CODE REVIEW

**Review by elinor-fung — APPROVED** [review]

File: src/coreclr/debug/daccess/cdac.cpp [hunk 1]
```diff
@@ -48,7 +48,7 @@ CDAC::CDAC(HMODULE module, uint64_t descriptorAddr, ICorDebugDataTarget* target)
 {
     if (m_module == NULL)
     {
-        m_cdac_handle = NULL;
+        m_cdac_handle = 0;
```
Comment (akoeplinger) [inline src/coreclr/debug/daccess/cdac.cpp:51]: looks like the approach in https://github.com/dotnet/runtime/pull/100796 was to cast NULL to INT_PTR instead

Comment (lambdageek) [reply src/coreclr/debug/daccess/cdac.cpp:51]: I think it's a style preference.  in this case m_cdac_handle isn't a pointer (it happens to be a NativeAOT GCHandle), so `(INT_PTR)NULL` isn't really apropriate, either.
