### PR TITLE
[JIT] ARM64 Fix - Use `SetOper` instead of `ChangeOper` to preserve flags

### LINKED ISSUE #84966: [JitStress] JIT/IL_Conformance/Old/Conformance_Base/bge_un* failures
Various tests are failing under JIT/IL_Conformance/Old/Conformance_Base/bge_un in JitStress pipeline for minopts legs.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=242476&view=ms.vss-test-web.build-test-results-tab

This is just for linux/windows/osx arm64.

image

### PR DESCRIPTION
**Pull request by TIHan**
## Description

Resolves https://github.com/dotnet/runtime/issues/84966

The changes from https://github.com/dotnet/runtime/pull/84605 resulted in the failing test.

I narrowed down the IL to this:
```IL
	ldc.r4		ZERO
	ldc.r4		NAN
	bge.un PASS
	br FAIL
```

This is an `unordered` comparison against a float ZERO and float NAN. In the importer, when we see this, the `GTF_RELOP_NAN_UN` flag gets set on the relop. However, if we decide to later swap the relop, calling `ChangeOper` will clear this bit which is what resulted in the test failing.

The fix is to use `SetOper` as it will not clear this flag.

### CODE REVIEW

File: src/coreclr/jit/compiler.h [hunk 1]
```diff
@@ -2928,6 +2928,7 @@ class Compiler
     bool gtComplexityExceeds(GenTree* tree, unsigned limit);
 
     GenTree* gtReverseCond(GenTree* tree);
+    GenTree* gtSwapRelop(GenTree* tree);
```
Comment (tannergooding) [inline src/coreclr/jit/compiler.h:2931]: We have a number of functions that call `GenTree::SwapRelop` and/or `gtReverseCond` today. Can we either update those as well or log an issue tracking updating them to be consistent?

Comment (TIHan) [reply src/coreclr/jit/compiler.h:2931]: Seems fair to update all cases.

Comment (TIHan) [reply src/coreclr/jit/compiler.h]: Turns out there was only one other use of `GenTree::SwapRelop` that gets used to change an oper.

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -3545,6 +3545,34 @@ GenTree* Compiler::gtReverseCond(GenTree* tree)
...
+
+    if (varTypeIsFloating(tree->gtGetOp1()))
+    {
+        isUnordered = (tree->gtFlags & GTF_RELOP_NAN_UN);
+    }
+
+    tree->SetOper(GenTree::SwapRelop(tree->OperGet()), vnUpdate);
+
+    // SetOper will clear the GTF_RELOP_NAN_UN bit.
+    // Therefore, we need to set it again if it was set before.
```
Comment (SingleAccretion) [inline src/coreclr/jit/gentree.cpp:3567]: That does not sound true, `SetOper` does not clear oper-specific flags (it is inteded to be used when switching between opers of the same "class").

Comment (TIHan) [reply src/coreclr/jit/gentree.cpp:3567]: You are right. I was thinking of `ChangeOper`. Now that I'm thinking about this, I should revert this change. In the place where I used `ChangeOper`, I should use `SetOper`.

Having `SetOper` and `ChangeOper` is a little confusing to me.

**Comment by TIHan** [comment]
@dotnet/jit-contrib This is ready. // cc @jakobbotsch

**Review by jakobbotsch — APPROVED** [review]
