### PR TITLE
JIT: fix flags lossage in morph comma/ind interchange

### LINKED ISSUE #68049: JIT: Wrong result computed with forward sub enabled on x64 Windows/Linux
### Description

The following program computes a wrong result when forward sub is enabled.

### Reproduction Steps

```csharp
// Generated by Fuzzlyn v1.5 on 2022-04-13 11:38:00
// Run on X64 Linux
// Seed: 1784259920377383051
// Reduced from 110.5 KiB to 0.9 KiB in 00:00:57
// Debug: Outputs 1
// Release: Outputs 0
public struct S0
{
    public uint F0;
    public long F1;
    public S0(uint f0): this()
    {
        F0 = f0;
    }

    public ulong M5()
    {
        var vr1 = new ushort[]{0};
        M6(vr1);
        return 1;
    }

    public void M6(ushort[] arg0)
    {
        this = new S0(0);
    }
}

public class Program
{
    public static IRuntime s_rt;
    public static void Main()
    {
        s_rt = new Runtime();
        var vr4 = new S0[]{new S0(1)};
        var vr5 = new short[]{0};
        bool vr6 = M1(vr4, vr5) <= 1;
    }

    public static short M1(S0[] arg0, short[] arg1)
    {
        long var3 = arg0[0].F1;
        var3 = (arg0[0].F0 & (byte)arg0[0].M5());
        s_rt.WriteLine(var3);
        return arg1[0];
    }
}

public interface IRuntime
{
    void WriteLine<T>(T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(T value) => System.Console.WriteLine(value);
}
```

### Expected behavior

Same result.

### Actual behavior

Different result.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

Reproduces on both x64 Windows and Linux.

### Other information

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Morph may transform `IND(COMMA(..., z))` into `COMMA(... , IND(z))`
and when doing so it was not computing appropriately conservative
flags for the new `IND`. In particular it was losing `GTF_GLOB_REF`.

This allowed subsequent opts to reorder operands in an unsafe manner.

Fixes #68049.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

Leads to a few diffs in SPMI.

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -12991,9 +12991,12 @@ GenTree* Compiler::fgMorphSmpOp(GenTree* tree, MorphAddrContext* mac)
...
                 // TODO-1stClassStructs: we often create a struct IND without a handle, fix it.
                 op1 = gtNewIndir(typ, addr);
-                // This is very conservative
-                op1->gtFlags |= treeFlags & ~GTF_ALL_EFFECT & ~GTF_IND_NONFAULTING;
+
+                // Determine flags on the indir
+                //
+                op1->gtFlags |= treeFlags & ~GTF_ALL_EFFECT;
                 op1->gtFlags |= (addr->gtFlags & GTF_ALL_EFFECT);
+                op1->gtFlags |= treeFlags & (GTF_GLOB_REF | GTF_IND_FLAGS);
```
Comment (SingleAccretion) [inline src/coreclr/jit/morph.cpp:12999]: Is the `GTF_IND_FLAGS` portion needed? Seems like it'd be set by the `|= treeFlags & ~GTF_ALL_EFFECT;` above.

Comment (AndyAyersMS) [reply src/coreclr/jit/morph.cpp:12999]: > Is the `GTF_IND_FLAGS` portion needed?

No, it's not needed.

**Review by SingleAccretion — APPROVED** [review]

File: src/tests/JIT/Regression/JitBlue/Runtime_68049/Runtime_68049_1.cs [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+    public static sbyte[][] s_8 = new sbyte[][]{new sbyte[]{1}};
+    public static byte s_9 = 28;
+    public static int Main()
+    {
+        CollectibleALC alc = new CollectibleALC();
+        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
+        System.Reflection.MethodInfo mi = asm.GetType(typeof(Runtime_68049_1).FullName).GetMethod(nameof(MainInner));
+        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
+        mi.Invoke(null, new object[]{System.Activator.CreateInstance(runtimeTy)});
+        return (int) s_result;
```
Comment (jakobbotsch) [inline src/tests/JIT/Regression/JitBlue/Runtime_68049/Runtime_68049_1.cs:41]: I would remove this test. It requires loading the assembly from file which means it has to be disabled in various configurations in issues.targets. Also I think the `s_result` is being set in the other instance of the type (the one loaded in the other ALC), not in this one, so it will always fail. Probably easier to just rely on the other test.

Comment (AndyAyersMS) [reply src/tests/JIT/Regression/JitBlue/Runtime_68049/Runtime_68049_1.cs:41]: Ok.

**Comment by AndyAyersMS** [comment]
Evidently we can't just copy the flags over:
```
Assert failure(PID 6704 [0x00001a30], Thread: 6592 [0x19c0]): Assertion failed '!"Extra flags on tree"' in 'ILGEN_0x1c02a9a5:Main():int' during 'Morph - Global' (IL size 58; hash 0xd149b15e; FullOpts)

Extra flags on tree [000122]: -----XG-------
[000122] n--XG+-N----                        *  IND       long
[000117] ------------                        --*  CNS_INT   byref  0
```

**Comment by AndyAyersMS** [comment]
The extra flag is the `GTF_IND_NONFAULTING`.  We get here because we have
```
fgMorphArrayIndex (before remorph):
               [011944] ---XG-------              *  COMMA     long  
               [011936] ---X--------              +--*  BOUNDS_CHECK_Rng void  
               [004058] ---X-----U--              |  +--*  CAST_ovfl int <- ubyte <- uint
               [004057] ------------              |  |  \--*  CNS_INT   int    -1
               [011935] ---X--------              |  \--*  ARR_LENGTH int   
               [004056] ------------              |     \--*  LCL_VAR   ref    V11 loc3         
               [004059] n--XG-------              \--*  IND       long  
               [011943] ---X---N----                 \--*  ARR_ADDR  byref long[]
               [011942] ---X--------                    \--*  ADD       byref 
               [011932] ------------                       +--*  LCL_VAR   ref    V11 loc3         
               [011941] ---X--------                       \--*  ADD       long  
               [011939] ---X--------                          +--*  MUL       long  
               [011937] ---X-----U--                          |  +--*  CAST      long <- uint
               [011933] ---X-----U--                          |  |  \--*  CAST_ovfl int <- ubyte <- uint
               [011934] ------------                          |  |     \--*  CNS_INT   int    -1
               [011938] -------N----                          |  \--*  CNS_INT   long   8
               [011940] ------------                          \--*  CNS_INT   long   16

Folding binary operator with constant nodes into a comma throw:
               [004058] ---X-----U--              *  CAST_ovfl int <- ubyte <
```
and `gtFoldExprConst` basically turns this into
```
IND(COMMA(THROW(), 0))
```
so after the IND/COMMA interchange we end up with a non-faulting indir off off zero which is also unreachable.
```
COMMA(THROW(), IND(0))
```
This eventually makes the flag checker uneasy.

This may be why the old code cleared `GTF_IND_NONFAULTING` but there's something unsavory about the whole business as most of the time we ought to be able to preserve that flag.

We perhaps should check for comma throw here and just nuke the indir entirely.

**Comment by jakobbotsch** [comment]
> ```
>               [004059] n--XG-------              \--*  IND       long  
>               [011943] ---X---N----                 \--*  ARR_ADDR  byref long[]
>               [011942] ---X--------                    \--*  ADD       byref 
>               [011932] ------------                       +--*  LCL_VAR   ref    V11 loc3         
>               [011941] ---X--------                       \--*  ADD       long  
>               [011939] ---X--------                          +--*  MUL       long  
>               [011937] ---X-----U--                          |  +--*  CAST      long <- uint
>               [011933] ---X-----U--                          |  |  \--*  CAST_ovfl int <- ubyte <- uint
> ```

It already looks strange to me here. How can an indirection have both `GTF_IND_NONFAULTING` and `GTF_EXCEPT`? Aren't those mutually exclusive?

**Comment by AndyAyersMS** [comment]
> It already looks strange to me here. How can an indirection have both `GTF_IND_NONFAULTING` and `GTF_EXCEPT`? Aren't those mutually exclusive?

That's okay -- an array access is guaranteed to either throw an exception or give you and address you can safely dereference. Recall `GTF_EXCEPT` is a whole-tree property.

(What I wrote above may be a little off, I'm not yet sure how we get into the IND/COMMA, since it looks like the IND is already under the comma. Need to do a bit more debugging).

**Comment by jakobbotsch** [comment]
> That's okay -- an array access is guaranteed to either throw an exception or give you and address you can safely dereference. Recall `GTF_EXCEPT` is a whole-tree property.

Ah ok, but they are mutually exclusive if the child of the indirection does not have `GTF_EXCEPT`, which I suppose is what the checker complains about?

**Comment by AndyAyersMS** [comment]
> Ah ok, but they are mutually exclusive if the child of the indirection does not have `GTF_EXCEPT`, which I suppose is what the checker complains about?

The checker makes assumptions about indirs with constant bases:

https://github.com/dotnet/runtime/blob/736883624a7ef175729cf082e12ce18f236d8524/src/coreclr/jit/fgdiagnostic.cpp#L3003-L3036

I need to debug through this part too as I don't quite see how it ends up complaining about what it complains about.

**Comment by AndyAyersMS** [comment]
Debugged and the actual checker flag complaint is indeed about `GTF_EXCEPT`, and as you note it makes no sense to have this set on a `GTF_IND_NONFAULTING` indir if the base address doesn't also have it set.

**Review by jakobbotsch — APPROVED** [review]
