### PR TITLE
[tests] Fix recently added mono test

### LINKED ISSUE #110149: [mono] Runtime tests `LargeStructSize_Mono` and `xprecise1_cs_do` failing on Apple mobile
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=876794&view=logs&j=07effcfd-c63d-5008-e811-03b29530f5cb&t=506b47fe-4551-54d6-41af-334dd2c09566
Build error leg or test failing: `JIT_Methodical` and `Loader_classloader`

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Test failed",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Error log:
```
[11:12:00] dbug: Running /private/tmp/helix/working/A12A087E/p/microsoft.dotnet.xharness.cli/10.0.0-prerelease.24564.1/tools/net8.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode_14.3.app -setenv=MONO_APPLE_APP_ENTRY_POINT_LIB_NAME=testdir-LargeStructSize_Mono/LargeStructSize_Mono.dll -setenv=MONO_APPLE_APP_ASSEMBLY_LOAD_PREFIX=testdir-LargeStructSize_Mono --disable-memory-limits --devname 00008020-001439AE1A03002E --launchdevbundleid net.dot.Loader_classloader --wait-for-exit -v -v -v -v -v
                 With env vars: 
                     MONO_APPLE_APP_ENTRY_POINT_LIB_NAME = 'testdir-LargeStructSize_Mono/LargeStructSize_Mono.dll'
                     MONO_APPLE_APP_ASSEMBLY_LOAD_PREFIX = 'testdir-LargeStructSize_Mono'
[11:12:02] dbug: Process mlaunch exited with 0
[11:12:07] dbug: Killing process tree of 41899...
[11:12:08] dbug: Pids to kill: 41899
[11:12:08] dbug: Detected exit code 101 from /tmp/helix/working/A12A087E/w/AD2B0920/uploads/net.dot.Loader_classloader.log
[11:12:08] info: App run ended with 101
[11:12:08] fail: Application has finished with exit code 101 but 100 was expected
[11:12:08] info: Uninstalling the application 'net.dot.Loader_classloader' from 'DNCENGOSX-009'
[11:12:08] dbug: 
[11:12:08] dbug: Running /private/tmp/helix/working/A12A087E/p/microsoft.dotnet.xharness.cli/10.0.0-prerelease.24564.1/tools/net8.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode_14.3.app --uninstalldevbundleid net.dot.Loader_classloader --devname 00008020-001439AE1A03002E -v -v -v -v -v
[11:12:08] dbug: Using Xcode 14.3 found in /Applications/Xcode_14.3.app
[11:12:08] dbug: Xamarin.Hosting: Device discovery started
[11:12:08] dbug: Xamarin.Hosting: Device discovery event: Connected (00008020-001439AE1A03002E)
[11:12:08] dbug: Xamarin.Hosting: Connected to DNCENGOSX-009 (00008020-001439AE1A03002E) in 00:00:00.0031760
[11:12:09] dbug: Uninstalling application 'net.dot.Loader_classloader' from 'DNCENGOSX-009'
[11:12:09] dbug: RemovingApplication: 75%
[11:12:09] dbug: PercentComplete: 50
[11:12:09] dbug: Status: RemovingApplication
[11:12:09] dbug: GeneratingApplicationMap: 95%
[11:12:09] dbug: PercentComplete: 90
[11:12:09] dbug: Status: GeneratingApplicationMap
[11:12:09] dbug: Application 'net.dot.Loader_classloader' uninstalled from 'DNCENGOSX-009'
[11:12:09] dbug: Process mlaunch exited with 0
[11:12:09] info: Application 'net.dot.Loader_classloader' was uninstalled successfully
[11:12:09] dbug: Saving diagnostics data to '/tmp/helix/working/A12A087E/w/AD2B0920/e/diagnostics.json'
XHarness exit code: 71 (GENERAL_FAILURE)
Test failed
```

Error log:
```
[11:04:47] dbug: Running /private/tmp/helix/working/A12A087E/p/microsoft.dotnet.xharness.cli/10.0.0-prerelease.24564.1/tools/net8.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode_14.3.app -setenv=MONO_APPLE_APP_ENTRY_POINT_LIB_NAME=testdir-xprecise1_cs_do/xprecise1_cs_do.dll -setenv=MONO_APPLE_APP_ASSEMBLY_LOAD_PREFIX=testdir-xprecise1_cs_do --disable-memory-limits --devname 00008030-000174882E23402E --launchdevbundleid net.dot.JIT_Methodical --wait-for-exit -v -v -v -v -v
                 With env vars: 
                     MONO_APPLE_APP_ENTRY_POINT_LIB_NAME = 'testdir-xprecise1_cs_do/xprecise1_cs_do.dll'
                     MONO_APPLE_APP_ASSEMBLY_LOAD_PREFIX = 'testdir-xprecise1_cs_do'
[11:05:20] dbug: Process mlaunch exited with 1
[11:05:25] dbug: Killing process tree of 5986...
[11:05:25] dbug: Pids to kill: 5986
[11:05:25] fail: App run has failed. mlaunch exited with 1
[11:05:25] info: Uninstalling the application 'net.dot.JIT_Methodical' from 'DNCENGOSX125'
[11:05:25] dbug: 
[11:05:25] dbug: Running /private/tmp/helix/working/A12A087E/p/microsoft.dotnet.xharness.cli/10.0.0-prerelease.24564.1/tools/net8.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode_14.3.app --uninstalldevbundleid net.dot.JIT_Methodical --devname 00008030-000174882E23402E -v -v -v -v -v
[11:05:26] dbug: Using Xcode 14.3 found in /Applications/Xcode_14.3.app
[11:05:26] dbug: Xamarin.Hosting: Device discovery started
[11:05:26] dbug: Xamarin.Hosting: Device discovery event: Connected (00008030-000174882E23402E)
[11:05:26] dbug: Xamarin.Hosting: Connected to DNCENGOSX125 (00008030-000174882E23402E) in 00:00:00.0030490
[11:05:26] dbug: Uninstalling application 'net.dot.JIT_Methodical' from 'DNCENGOSX125'
[11:05:26] dbug: RemovingApplication: 75%
[11:05:26] dbug: PercentComplete: 50
[11:05:26] dbug: Status: RemovingApplication
[11:05:26] dbug: GeneratingApplicationMap: 95%
[11:05:26] dbug: PercentComplete: 90
[11:05:26] dbug: Status: GeneratingApplicationMap
[11:05:26] dbug: Application 'net.dot.JIT_Methodical' uninstalled from 'DNCENGOSX125'
[11:05:26] dbug: Process mlaunch exited with 0
[11:05:26] info: Application 'net.dot.JIT_Methodical' was uninstalled successfully
[11:05:26] dbug: Saving diagnostics data to '/tmp/helix/working/A12A087E/w/A4A80888/e/diagnostics.json'
XHarness exit code: 83 (APP_LAUNCH_FAILURE)
Test failed
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=876794
**Error message validated:** `[Test failed`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 11/25/2024 12:19:49 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[895348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=895348)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=895348&view=ms.vss-test-web.build-test-results-tab&runId=23474914&resultId=100156)||
|[895101](https://dev.azure.com/dnceng-public/public/_build/results?buildId=895101)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=895101&view=ms.vss-test-web.build-test-results-tab&runId=23471364&resultId=110349)|dotnet/runtime#110622|
|[895068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=895068)|dotnet/runtime|[Interop\ICustomMarshaler\Primitives\ICustomMarshaler_TargetWindows\ICustomMarshaler_TargetWindows.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=895068&view=ms.vss-test-web.build-test-results-tab&runId=23469968&resultId=107556)|dotnet/runtime#110701|
|[894379](https://dev.azure.com/dnceng-public/public/_build/results?buildId=894379)|dotnet/runtime|[baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=894379&view=ms.vss-test-web.build-test-results-tab&runId=23445790&resultId=117019)|dotnet/runtime#110471|
|[894279](https://dev.azure.com/dnceng-public/public/_build/results?buildId=894279)|dotnet/runtime|[tracing\runtimeeventsource\nativeruntimeeventsource\nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=894279&view=ms.vss-test-web.build-test-results-tab&runId=23443878&resultId=115291)|dotnet/runtime#110622|
|[893759](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893759)|dotnet/runtime|[nativeaot\SmokeTests\TrimmingBehaviors\TrimmingBehaviors\TrimmingBehaviors.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893759&view=ms.vss-test-web.build-test-results-tab&runId=23432256&resultId=112445)|dotnet/runtime#110655|
|[893188](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893188)|dotnet/runtime|[GC/LargeMemory/Regressions/largearraytest/largearraytest.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893188&view=ms.vss-test-web.build-test-results-tab&runId=23415036&resultId=112992)|dotnet/runtime#110617|
|[893212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893212)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893212&view=ms.vss-test-web.build-test-results-tab&runId=23411300&resultId=100156)||
|[893208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893208)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893208&view=ms.vss-test-web.build-test-results-tab&runId=23411922&resultId=119378)||
|[893159](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893159)|dotnet/runtime|[tracing\runtimeeventsource\nativeruntimeeventsource\nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893159&view=ms.vss-test-web.build-test-results-tab&runId=23410190&resultId=115291)|dotnet/runtime#110622|
|[892926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892926)|dotnet/runtime|[tracing/eventlistener/EventListenerThreadPool/EventListenerThreadPool.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892926&view=ms.vss-test-web.build-test-results-tab&runId=23404452&resultId=115727)|dotnet/runtime#110627|
|[892907](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892907)|dotnet/runtime|[tracing\runtimeeventsource\nativeruntimeeventsource\nativeruntimeeventsource.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892907&view=ms.vss-test-web.build-test-results-tab&runId=23403372&resultId=115291)|dotnet/runtime#110622|
|[892587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892587)|dotnet/runtime|[baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892587&view=ms.vss-test-web.build-test-results-tab&runId=23393290&resultId=100418)||
|[892590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892590)|dotnet/runtime|[GC/LargeMemory/Regressions/largearraytest/largearraytest.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892590&view=ms.vss-test-web.build-test-results-tab&runId=23393360&resultId=110306)|dotnet/runtime#110617|
|[891555](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891555)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891555&view=ms.vss-test-web.build-test-results-tab&runId=23360272&resultId=120838)||
|[891559](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891559)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891559&view=ms.vss-test-web.build-test-results-tab&runId=23359644&resultId=100291)||
|[891249](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891249)|dotnet/runtime|[readytorun/crossgen2/crossgen2smoke/crossgen2smoke.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891249&view=ms.vss-test-web.build-test-results-tab&runId=23351448&resultId=114300)|dotnet/runtime#110477|
|[891053](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891053)|dotnet/runtime|[nativeaot\SmokeTests\HardwareIntrinsics\X64Avx\X64Avx.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=891053&view=ms.vss-test-web.build-test-results-tab&runId=23341228&resultId=112431)|dotnet/runtime#103950|
|[890103](https://dev.azure.com/dnceng-public/public/_build/results?buildId=890103)|dotnet/runtime|[readytorun/crossgen2/crossgen2smoke/crossgen2smoke.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=890103&view=ms.vss-test-web.build-test-results-tab&runId=23318406&resultId=111473)|dotnet/runtime#110477|
|[889844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889844)|dotnet/runtime|[readytorun/crossgen2/crossgen2smoke/crossgen2smoke.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889844&view=ms.vss-test-web.build-test-results-tab&runId=23309804&resultId=110279)|dotnet/runtime#110477|
|[889002](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889002)|dotnet/runtime|[JIT/opt/OSR/synchronized/synchronized.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889002&view=ms.vss-test-web.build-test-results-tab&runId=23272428&resultId=114248)|dotnet/runtime#110501|
|[888242](https://dev.azure.com/dnceng-public/public/_build/results?buildId=888242)|dotnet/runtime|[nativeaot.SmokeTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=888242&view=ms.vss-test-web.build-test-results-tab&runId=23252128&resultId=100459)|dotnet/runtime#110475|
|[888153](https://dev.azure.com/dnceng-public/public/_build/results?buildId=888153)|dotnet/runtime|[nativeaot\SmokeTests\DynamicGenerics\DynamicGenerics\DynamicGenerics.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=888153&view=ms.vss-test-web.build-test-results-tab&runId=23249792&resultId=100006)|dotnet/runtime#110472|
|[887997](https://dev.azure.com/dnceng-public/public/_build/results?buildId=887997)|dotnet/runtime|[Regression_3.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=887997&view=ms.vss-test-web.build-test-results-tab&runId=23245006&resultId=120839)||
|[888001](https://dev.azure.com/dnceng-public/public/_build/results?buildId=888001)|dotnet/runtime|[tracing_eventpipe.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=888001&view=ms.vss-test-web.build-test-results-tab&runId=23244346&resultId=100030)||
|[887976](https://dev.azure.com/dnceng-public/public/_build/results?buildId=887976)|dotnet/runtime|[System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=887976&view=ms.vss-test-web.build-test-results-tab&runId=23242628&resultId=148285)|dotnet/runtime#110467|
|[885924](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885924)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885924&view=ms.vss-test-web.build-test-results-tab&runId=23182502&resultId=110431)|dotnet/runtime#110105|
|[885674](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885674)|dotnet/runtime|[JIT_opt.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885674&view=ms.vss-test-web.build-test-results-tab&runId=23170714&resultId=100018)||
|[885610](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885610)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885610&view=ms.vss-test-web.build-test-results-tab&runId=23169990&resultId=109916)||
|[885300](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885300)|dotnet/runtime|[CoreMangLib_system.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885300&view=ms.vss-test-web.build-test-results-tab&runId=23159352&resultId=100022)||
|[885296](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885296)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885296&view=ms.vss-test-web.build-test-results-tab&runId=23162810&resultId=105235)||
|[885058](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885058)|dotnet/runtime|[JIT/opt/Cloning/loops_with_eh/loops_with_eh.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=885058&view=ms.vss-test-web.build-test-results-tab&runId=23152088&resultId=112336)|dotnet/runtime#110020|
|[884516](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884516)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884516&view=ms.vss-test-web.build-test-results-tab&runId=23134290&resultId=100158)||
|[884596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884596)|dotnet/runtime|[Loader/classloader/RefFields/Validate/Validate.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884596&view=ms.vss-test-web.build-test-results-tab&runId=23134292&resultId=110093)|dotnet/runtime#110344|
|[884511](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884511)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884511&view=ms.vss-test-web.build-test-results-tab&runId=23132610&resultId=119268)||
|[884449](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884449)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884449&view=ms.vss-test-web.build-test-results-tab&runId=23131432&resultId=108174)||
|[884416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884416)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884416&view=ms.vss-test-web.build-test-results-tab&runId=23130636&resultId=100158)||
|[884403](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884403)|dotnet/runtime|[JIT/opt/Cloning/loops_with_eh/loops_with_eh.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884403&view=ms.vss-test-web.build-test-results-tab&runId=23130748&resultId=112924)|dotnet/runtime#110020|
|[884253](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884253)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884253&view=ms.vss-test-web.build-test-results-tab&runId=23125824&resultId=100156)||
|[884249](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884249)|dotnet/runtime|[Regression_3.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884249&view=ms.vss-test-web.build-test-results-tab&runId=23127216&resultId=120491)||
|[884123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884123)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884123&view=ms.vss-test-web.build-test-results-tab&runId=23124158&resultId=109035)||
|[884127](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884127)|dotnet/runtime|[nativeaot.SmokeTests.StackTraceMetadata.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=884127&view=ms.vss-test-web.build-test-results-tab&runId=23121432&resultId=100012)||
|[883346](https://dev.azure.com/dnceng-public/public/_build/results?buildId=883346)|dotnet/runtime|[JIT/opt/OSR/largefuncletframe/largefuncletframe.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=883346&view=ms.vss-test-web.build-test-results-tab&runId=23096856&resultId=114805)|dotnet/runtime#107283|
|[882460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=882460)|dotnet/runtime|[JIT/opt/OSR/mainlooptry3/mainlooptry3.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=882460&view=ms.vss-test-web.build-test-results-tab&runId=23070140&resultId=112963)|dotnet/runtime#110273|
|[881999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881999)|dotnet/runtime|[JIT/superpmi/superpmicollect/superpmicollect.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881999&view=ms.vss-test-web.build-test-results-tab&runId=23057244&resultId=112743)|dotnet/runtime#107168|
|[881982](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881982)|dotnet/runtime|[Loader_classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881982&view=ms.vss-test-web.build-test-results-tab&runId=23056868&resultId=100019)||
|[881663](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881663)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881663&view=ms.vss-test-web.build-test-results-tab&runId=23044982&resultId=100158)||
|[881659](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881659)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881659&view=ms.vss-test-web.build-test-results-tab&runId=23045892&resultId=118001)||
|[881350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881350)|dotnet/runtime|[profiler/assembly/ALCTest/ALCTest.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881350&view=ms.vss-test-web.build-test-results-tab&runId=23035640&resultId=102367)|dotnet/runtime#109901|
|[881227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881227)|dotnet/runtime|[Interop/Swift/SwiftSelfContext/SwiftSelfContext/SwiftSelfContext.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881227&view=ms.vss-test-web.build-test-results-tab&runId=23033304&resultId=111135)|dotnet/runtime#110232|
|[881204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881204)|dotnet/runtime|[profiler/assembly/ALCTest/ALCTest.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881204&view=ms.vss-test-web.build-test-results-tab&runId=23031646&resultId=115923)|dotnet/runtime#109901|
|[881066](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881066)|dotnet/runtime|[profiler/assembly/ALCTest/ALCTest.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881066&view=ms.vss-test-web.build-test-results-tab&runId=23026932&resultId=109404)|dotnet/runtime#109901|
|[880817](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880817)|dotnet/runtime|[nativeaot/SmokeTests/TrimmingBehaviors/TrimmingBehaviors/TrimmingBehaviors.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880817&view=ms.vss-test-web.build-test-results-tab&runId=23016234&resultId=100016)|dotnet/runtime#103950|
|[880450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880450)|dotnet/runtime|[tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880450&view=ms.vss-test-web.build-test-results-tab&runId=23000380&resultId=110300)|dotnet/runtime#110208|
|[880213](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880213)|dotnet/runtime|[JIT_Directed.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880213&view=ms.vss-test-web.build-test-results-tab&runId=22993744&resultId=100057)||
|[880208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880208)|dotnet/runtime|[JIT/Regression/JitBlue/DevDiv_255294/DevDiv_255294/DevDiv_255294.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880208&view=ms.vss-test-web.build-test-results-tab&runId=22995902&resultId=118965)||
|[879242](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879242)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879242&view=ms.vss-test-web.build-test-results-tab&runId=22963656&resultId=100158)||
|[879107](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879107)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879107&view=ms.vss-test-web.build-test-results-tab&runId=22963730&resultId=100156)||
|[2589571](https://dev.azure.com/dnceng/internal/_build/results?buildId=2589571)|dotnet-runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2589571&view=ms.vss-test-web.build-test-results-tab&runId=54547371&resultId=100005)|[#45278](https://dev.azure.com/dnceng/internal/_git/dotnet-runtime/pullrequest/45278)|
|[879212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879212)|dotnet/runtime|[Regression_3.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879212&view=ms.vss-test-web.build-test-results-tab&runId=22963362&resultId=120839)||
|[878786](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878786)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878786&view=ms.vss-test-web.build-test-results-tab&runId=22948170&resultId=118344)||
|[878527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878527)|dotnet/runtime|[baseservices\invalid_operations\InvalidOperations\InvalidOperations.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878527&view=ms.vss-test-web.build-test-results-tab&runId=22939354&resultId=113793)|dotnet/runtime#109901|
|[878306](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878306)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878306&view=ms.vss-test-web.build-test-results-tab&runId=22932184&resultId=100158)||
|[878000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878000)|dotnet/runtime|[Loader_classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878000&view=ms.vss-test-web.build-test-results-tab&runId=22919224&resultId=100019)||
|[876794](https://dev.azure.com/dnceng-public/public/_build/results?buildId=876794)|dotnet/runtime|[Loader_classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=876794&view=ms.vss-test-web.build-test-results-tab&runId=22882104&resultId=100019)|dotnet/runtime#104097|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|18|65|

### PR DESCRIPTION
**Pull request by BrzVlad**
There are two issues with the test. Firstly, the `BigArray_x_2` structs were expected to throw type load exception in the test, due to size limit, but their size was decremented by one instead of incremented. Secondly, inlining of `Environment.Is64BitProcess` fails due to class initialization not yet being performed. This means that we would end up initializing both 32bit and 64bit types in the test.

This test has been failing on mono ever since it was added in https://github.com/dotnet/runtime/pull/104393. It seems to have gone undercover because it is not being run as apart of normal desktop runtime tests due to incorrect configuration where it is removed in `Loader.csproj`. This hack was apparently done because disabling the test on coreclr hits a separate issue https://github.com/dotnet/runtime/issues/105964.

Test was consistently failing on mobile where we use a different mechanism for running runtime tests.

### CODE REVIEW

**Comment by BrzVlad** [comment]
https://github.com/dotnet/runtime/issues/110149. CC @matouskozak @kotlarmilos

File: src/tests/Loader/classloader/SequentialLayout/ManagedSequential/LargeStructSize_Mono.cs [hunk 1]
```diff
@@ -65,29 +65,39 @@ struct BigArray_32_1
...
             Assert.Throws<TypeLoadException>(() => sizeof(X_explicit_32));
             Assert.Throws<TypeLoadException>(() => sizeof(Y_32));
+    }
+
+    [Fact]
+    public static void TestLargeStructSize()
+    {
+        if (Environment.Is64BitProcess)
+        {
+            Test64Bit ();
```
Comment (matouskozak) [inline src/tests/Loader/classloader/SequentialLayout/ManagedSequential/LargeStructSize_Mono.cs:96]: Why does moving the code to separate subroutine helps with:

> Secondly, inlining of Environment.Is64BitProcess fails due to class initialization not yet being performed.

?

**Review by matouskozak — APPROVED** [review]
Thanks for fixing this, I started `extra-platforms` to make sure it fixes the issue on CI as well.

For refence, here is the original issue https://github.com/dotnet/runtime/issues/106797 after https://github.com/dotnet/runtime/pull/104393 got merged. I think it got superseded later by https://github.com/dotnet/runtime/issues/110149.

File: src/tests/Loader/classloader/SequentialLayout/ManagedSequential/LargeStructSize_Mono.cs (hunk 1 above)
Comment (BrzVlad) [reply src/tests/Loader/classloader/SequentialLayout/ManagedSequential/LargeStructSize_Mono.cs:96]: Consider code like:
```
if (true)
    print sizeof (T1)
else
    print sizeof (T2)
```
`sizeof (T1)` needs to run some class initialization before being computed. Also the size gets included in the emitted code. In this scenario, during method compilation, `sizeof (T1)` will be computed and we won't emit any code in the else branch. However if the `if` condition is not obviously known at method compile time, then both branches will be compiled and we would end up running initialization for `T1` as well as for `T2`. This is not about resolving the condition better, but rather preventing the initialization of both types.

Comment (matouskozak) [reply src/tests/Loader/classloader/SequentialLayout/ManagedSequential/LargeStructSize_Mono.cs:96]: Ah I see, thanks. Everything can be solved by another layer of indirection :) 

However, thinking about it more, why would `if (Environment.Is64BitProcess)` (which is just `IntPtr.Size == 8`) be unknown, especially during AOT. Maybe we are not optimizing the compilation and always emitting code for both branches and discarding the else branch later?

Comment (BrzVlad) [reply src/tests/Loader/classloader/SequentialLayout/ManagedSequential/LargeStructSize_Mono.cs:96]: That is not the case. We don't inline any methods from classes that have a cctor that hasn't been run yet. In this particular case, the cctor wouldn't have any consequence on the result.

How does CoreCLR handle `Environment.Is64BitProcess` for example ? Does it rely on the tiered method to have the optimized code generated while the untiered method doesn't hardcode the value ? @AndyAyersMS

Comment (AndyAyersMS) [reply src/tests/Loader/classloader/SequentialLayout/ManagedSequential/LargeStructSize_Mono.cs:96]: > How does CoreCLR handle `Environment.Is64BitProcess` for example ? Does it rely on the tiered method to have the optimized code generated while the untiered method doesn't hardcode the value ? @AndyAyersMS

I don't see any special treatment (eg intrisic attribute) in CoreCLR for `Is64BitProcess`, so it will be a call in Tier0 and inlined / folded to a constant in Tier1.
