### PR TITLE
[Mono] enable tests that seem to pass

### LINKED ISSUE #14956: [netcore] Make System.Linq.Parallel.Tests.PlinqModesTests.WithExecutionMode_Multiple Pass
The test currently fails with:

```
System.Linq.Parallel.Tests.PlinqModesTests.WithExecutionMode_Multiple(first: Default, second: Default) [FAIL]
      System.ArgumentException : Arg_ObjObjEx
      Stack Trace:
           at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
           at System.Reflection.RuntimeMethodInfo.ConvertValues(Binder binder, Object[] args, ParameterInfo[] pinfo, CultureInfo culture, BindingFlags invokeAttr)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
        --- End of stack trace from previous location where exception was thrown ---
    System.Linq.Parallel.Tests.PlinqModesTests.WithExecutionMode_Multiple(first: Default, second: NotBuffered) [FAIL]
      System.ArgumentException : Arg_ObjObjEx
      Stack Trace:
           at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
           at System.Reflection.RuntimeMethodInfo.ConvertValues(Binder binder, Object[] args, ParameterInfo[] pinfo, CultureInfo culture, BindingFlags invokeAttr)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
        --- End of stack trace from previous location where exception was thrown ---
    System.Linq.Parallel.Tests.PlinqModesTests.WithExecutionMode_Multiple(first: NotBuffered, second: Default) [FAIL]
      System.ArgumentException : Arg_ObjObjEx
      Stack Trace:
           at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
           at System.Reflection.RuntimeMethodInfo.ConvertValues(Binder binder, Object[] args, ParameterInfo[] pinfo, CultureInfo culture, BindingFlags invokeAttr)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
        --- End of stack trace from previous location where exception was thrown ---
    System.Linq.Parallel.Tests.PlinqModesTests.WithExecutionMode_Multiple(first: NotBuffered, second: NotBuffered) [FAIL]
      System.ArgumentException : Arg_ObjObjEx
      Stack Trace:
           at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
           at System.Reflection.RuntimeMethodInfo.ConvertValues(Binder binder, Object[] args, ParameterInfo[] pinfo, CultureInfo culture, BindingFlags invokeAttr)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
        --- End of stack trace from previous location where exception was thrown ---
```

Determine why and make the test pass.

### LINKED ISSUE #15190: [netcore] Make System.Numerics.Tests.GenericVectorTests.ConstructorWithUnsupportedTypes_DateTime Pass
The test currently fails with:

```
 System.Numerics.Tests.GenericVectorTests.ConstructorWithUnsupportedTypes_DateTime [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.NotSupportedException)
      Actual:   typeof(System.TypeInitializationException): The type initializer for 'System.Numerics.Vector`1' threw an exception.
      ---- System.TypeInitializationException : The type initializer for 'System.Numerics.Vector`1' threw an exception.
      -------- System.NotSupportedException : Specified type is not supported
      Stack Trace:
           at System.Numerics.Tests.GenericVectorTests.<>c__734`1[[System.DateTime, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<TestConstructorWithUnsupportedTypes>b__734_0()
        ----- Inner Stack Trace -----
           at System.Numerics.Tests.GenericVectorTests.<>c__734`1[[System.DateTime, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<TestConstructorWithUnsupportedTypes>b__734_0()
        ----- Inner Stack Trace -----
           at System.Numerics.Vector`1[[System.DateTime, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..cctor()
```

Determine why and make the test pass.

### LINKED ISSUE #15353: [netcore] Make System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform Pass
The test currently fails with:

```
System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform(inputType: Reader, readerType: XmlValidatingReader, transformType: Reader, docType: XPathDocument) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Xml.Tests.XsltApiTestCaseBase.VerifyResult(String expectedValue)
           at System.Xml.Tests.CXmlResolverTest.<>c__DisplayClass5_0.<TC_AbsolutePath_Transform>b__0()
           at System.Xml.Tests.XsltApiTestCaseBase.TestUsingTemporaryCopyOfResolverDocument(Action testAction)
           at System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform(InputType inputType, ReaderType readerType, TransformType transformType, DocType docType)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      Output:
        Loading style sheet as XmlValidatingReader TestFiles/TestData/XsltApi/xmlResolver_document_function_absolute_uri.xsl
        Loading XML TestFiles/TestData/XsltApi/fruits.xml
        Executing transform
        Expected : <?xml version="1.0" encoding="utf-8"?><result>123</result>
        Actual : <?xml version="1.0" encoding="utf-8"?><result></result>
```

Determine why and make the test pass.

### PR DESCRIPTION
**Pull request by lambdageek**
These tests have`ActiveIssue` attributes that link to https://github.com/mono/mono issues.  They appear to pass now.

| Test project | Issue |
|----------------|-----------|
| `System.Numerics.Vectors` | Fixes https://github.com/mono/mono/issues/15190 |
| `System.ComponentModel.Composition` | Possibly addresses https://github.com/mono/mono/issues/16417 |
| `System.Private.Xml` | Fixes https://github.com/mono/mono/issues/15353 |
| `System.Linq.Parallel` | Fixes https://github.com/mono/mono/issues/14956 |

Note there are a number of remaining `ActiveIssue` attributes that link to issues in `mono/mono`  see gist https://gist.github.com/lambdageek/dd9b7872d446a16589529f0c562c4123

### CODE REVIEW

**Comment by lambdageek** [comment]
The ComponentModel tests with https://github.com/mono/mono/issues/16417 are reportedly flaky.  So perhaps those are still active.

**Comment by lambdageek** [comment]
The `Build Browser wasm Release AllSubsets_Mono)` failure is interesting
https://helix.dot.net/api/2019-06-17/jobs/e88282f0-b8c9-45e2-89de-e95b11b28f8f/workitems/System.ComponentModel.Composition.Tests/console :

```
[19:37:41] info: Discovering: System.ComponentModel.Composition.Tests.dll (method display = ClassAndMethod, method display options = None)
[19:37:44] info: Discovered:  System.ComponentModel.Composition.Tests.dll (found 1424 of 1588 test cases)
[19:37:44] info: Starting:    System.ComponentModel.Composition.Tests.dll
[19:37:47] fail: [FAIL] System.ComponentModel.Composition.DirectoryCatalogTests.LoadedFiles_ContainsMultipleDllsAndSomeNonDll_ShouldOnlyContainDlls
[19:37:47] info: System.ArgumentException : Empty file name is not legal. (Parameter 'sourceFileName')
[19:37:47] info:    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
[19:37:47] info:    at System.IO.File.Copy(String sourceFileName, String destFileName)
[19:37:47] info:    at System.ComponentModel.Composition.DirectoryCatalogTests.LoadedFiles_ContainsMultipleDllsAndSomeNonDll_ShouldOnlyContainDlls()
[19:37:47] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[19:37:48] fail: [FAIL] System.ComponentModel.Composition.Primitives.DirectoryCatalogDebuggerProxyTests.LoadedFiles_ContainsMultipleDllsAndSomeNonDll_ShouldOnlyContainDlls
[19:37:48] info: System.ArgumentException : Empty file name is not legal. (Parameter 'sourceFileName')
[19:37:48] info:    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
[19:37:48] info:    at System.IO.File.Copy(String sourceFileName, String destFileName)
[19:37:48] info:    at System.ComponentModel.Composition.Primitives.DirectoryCatalogDebuggerProxyTests.LoadedFiles_ContainsMultipleDllsAndSomeNonDll_ShouldOnlyContainDlls()
[19:37:48] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[19:37:49] fail: [FAIL] Tests.Integration.DiscoveryTests.InheritedExport_TwoInterfaces
[19:37:49] info: Assert.Equal() Failure
[19:37:49] info: Expected: String[] ["IFoo1", "IFoo2"]
[19:37:49] info: Actual:   SelectArrayIterator<Lazy<Object, IDictionary<String, Object>>, String> ["IFoo2", "IFoo1"]
[19:37:49] info:    at Tests.Integration.DiscoveryTests.InheritedExport_TwoInterfaces()
[19:37:49] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[19:37:50] info: Finished:    System.ComponentModel.Composition.Tests.dll
[19:37:50] info: 
[19:37:50] info: === TEST EXECUTION SUMMARY ===
[19:37:50] info: Total: 1424, Errors: 0, Failed: 3, Skipped: 1, Time: 5.776298s
[19:37:50] info: 
```

The two test doing copying should probably be disabled on wasm.   Not sure about `InheritedExport_TwoInterfaces`

**Comment by steveisok** [comment]
@lambdageek Can you push again to restart the build?

**Comment by lambdageek** [comment]
rebased on master

**Review by steveisok — APPROVED** [review]

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs [hunk 1]
```diff
@@ -733,6 +733,7 @@ public void GetConstructor(Type[] types, int? expected)
         }
 
         [Fact]
+        [ActiveIssue("https://github.com/mono/mono/issues/15029", TestRuntimes.Mono)]
```
Comment (am11) [inline src/libraries/System.Reflection/tests/TypeInfoTests.cs:736]: https://github.com/mono/mono/pull/20535 seems to be closed when #44081 was merged. Should it be reopened if the bug has regressed since?

Comment (lambdageek) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:736]: Good catch! I think this PR (43407) is older than 44081 - i'll verify that the ActiveIssue is resolved and open a new PR to remove it

Comment (lambdageek) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:736]: Fix is in https://github.com/dotnet/runtime/pull/46680
