### PR TITLE
Properly check ISAs for static readonly simd fields

### LINKED ISSUE #87390: Test failure JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd
**Failed in:** [runtime-coreclr jitstress-isas-x86 20230610.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=302664&view=ms.vss-test-web.build-test-results-tab&runId=6138314&resultId=112887&paneView=debug)

**Failed tests:**
```
coreclr osx x64 Checked jitstress_isas_nohwintrinsic @ OSX.1200.Amd64.Open
    - JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.cmd
coreclr osx x64 Checked jitstress_isas_1_x86_nosse @ OSX.1200.Amd64.Open
    - JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.cmd
coreclr osx x64 Checked jitstress_isas_x86_nosse @ OSX.1200.Amd64.Open
    - JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.cmd
coreclr osx x64 Checked jitstress_isas_2_x86_nosse @ OSX.1200.Amd64.Open
    - JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.cmd
coreclr osx x64 Checked jitstress_isas_2_x86_nohwintrinsic @ OSX.1200.Amd64.Open
    - JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.cmd
coreclr osx x64 Checked jitstress_isas_x86_nohwintrinsic @ OSX.1200.Amd64.Open
    - JIT/HardwareIntrinsics/General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.cmd
```

**Error message:**
```
 
Assert failure(PID 77208 [0x00012d98], Thread: 650877 [0x9ee7d]): Assertion failed 'm_store->TypeGet() == m_src->TypeGet()' in 'StaticReadonlySimd:Test()' during 'Morph - Global' (IL size 320; hash 0x34c1e7a5; Tier1)

    File: /Users/runner/work/1/s/src/coreclr/jit/morphblock.cpp Line: 672
    Image: /private/tmp/helix/working/A5B6093F/p/corerun

[createdump] Invalid process id: task_for_pid(77208) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
waitpid() returned successfully (wstatus 0000ff00) WEXITSTATUS ff WTERMSIG 0
/private/tmp/helix/working/A5B6093F/w/9F040956/e/JIT/HardwareIntrinsics/HardwareIntrinsics_General_r/../General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.sh: line 448: 77208 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/A5B6093F/w/9F040956/uploads/General/ConstantFolding/StaticReadonlySimd/output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A5B6093F/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true StaticReadonlySimd.dll ''
[createdump] Target process is alive
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 6/10/2023 3:32:39 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/A5B6093F/w/9F040956/e/JIT/HardwareIntrinsics/HardwareIntrinsics_General_r/../General/ConstantFolding/StaticReadonlySimd/StaticReadonlySimd.sh
Expected: True
Actual:   False
```

**Stack trace:**
```
    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor2396|0_2397(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/87390

### CODE REVIEW

**Comment by EgorBo** [comment]
@dotnet/jit-contrib PTAL, simple change, fixes jitstress assert

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -3530,18 +3530,29 @@ GenTree* Compiler::impImportStaticReadOnlyField(CORINFO_FIELD_HANDLE field, CORI
...
+                        hwAccelerated = compOpportunisticallyDependsOn(InstructionSet_AVX);
+                    }
+                    else
 #endif
+                        if ((simdType != TYP_SIMD8) && (simdType != TYP_SIMD12) && (simdType != TYP_SIMD16))
+                    {
+                        // SIMD8, SIMD12, SIMD16 are covered by IsBaselineSimdIsaSupported check
+                        assert(!"unknown simd type size");
+                        hwAccelerated = false;
+                    }
```
Comment (tannergooding) [inline src/coreclr/jit/importer.cpp:3555]: Should this whole bit just be an assert so we don't incur the 3 comparisons (we're unlikely to add more TYP_SIMD anytime in the future and the asserts should catch it if we do)

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/importer.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/importer.cpp]: Makes sense, changed to an assert
