### PR TITLE
Don't block specific generic types in field marshalling scenarios.

### LINKED ISSUE #31640: Marshal.SizeOf throws exceptions for struct with Nullable<T> fields
The following program throws an exception in the 5.0 alpha builds. But not in 3.1

```CSharp
namespace ThrowsExceptionIn50
{
    using System;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    internal struct Test
    {
        public float? J { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Marshal.SizeOf(typeof(Test)));
        }
    }
}
```

cc @mjsabby

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Bing is using `Marshal.SizeOf` to calculate the size of structs that contain a `Nullable<T>` field. In the old system, this would unexpectedly work since we apparently allowed using generic structs as fields in interop types (but not generic classes). See the `&& ELEMENT_TYPE_CLASS` at the end of the condition on line 208: https://github.com/dotnet/coreclr/blob/release/3.1/src/vm/fieldmarshaler.cpp#L208-L211

Semantically, the correct function for users to call here would be `Unsafe.SizeOf<T>`, but there's a large number of users who use `Marshal.SizeOf` instead of `Unsafe.SizeOf` for various reasons.

Fixes #31640

### CODE REVIEW

**Comment by jkotas** [comment]
Test?

**Comment by jkoritzinsky** [comment]
Added

**Review by jkotas — APPROVED** [review]
Thanks!

File: src/coreclr/src/vm/mlinfo.cpp [hunk 1]
```diff
@@ -2784,22 +2784,36 @@ MarshalInfo::MarshalInfo(Module* pModule,
...
-                    || m_pMT->HasSameTypeDefAs(MscorlibBinder::GetClass(CLASS__VECTOR128T))
-                    || m_pMT->HasSameTypeDefAs(MscorlibBinder::GetClass(CLASS__VECTOR256T))
+                // * Vector<T>: Has a variable size (either __m128 or __m256) and isn't readily usable for interop scenarios
+
+                if (m_pMT->HasInstantiation() && !IsFieldScenario())
+                {
+                    if (!m_pMT->IsBlittable()
+                        || (m_pMT->HasSameTypeDefAs(g_pByReferenceClass)
+                            || m_pMT->HasSameTypeDefAs(g_pNullableClass)
+                            || m_pMT->HasSameTypeDefAs(MscorlibBinder::GetClass(CLASS__VECTOR64T))
```
Comment (tannergooding) [inline src/coreclr/src/vm/mlinfo.cpp]: `Vector64/128/256<T>` need to be blocked even in the field scenario. It has special ABI handling for some architectures, even when it is a field in a struct (where it might qualify as a HVA).

**Comment by jkotas** [comment]
> Vector64/128/256<T> need to be blocked even in the field scenario.

.NET Core 3.x shipped without this block. E.g. the following works fine in .NET Core 3.x:
```
using System;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;

struct Foo
{
    Vector64<int> f;
}

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(Marshal.SizeOf<Foo>());
    }
}
```

Is adding the block for these a breaking change?

**Comment by tannergooding** [comment]
> .NET Core 3.x shipped without this block.

Was it allowed to cross the P/Invoke boundary or just allowed in functions like `Marshal.SizeOf<T>()`?

**Comment by jkotas** [comment]
It was allowed to cross P/Invoke boundary too.

**Comment by tannergooding** [comment]
That's unfortunate. The intent was that it shouldn't be allowed as `struct Mat4x4 { Vector128<float> x, y, z, w; }` has special ABI requirements on some platforms (it can be passed in 4 registers; rather than by reference).

**Comment by jkoritzinsky** [comment]
I take it based on this feedback that we want to switch this back to only explicitly blocking `ByReference<T>` in field scenarios?

**Comment by jkotas** [comment]
For this PR, we should make it do what it did in .NET Core 3.0. 

If you would like to propose breaking changes against the .NET Core 3.0 behavior, it should be separate issue / PR.

**Comment by jkoritzinsky** [comment]
Sounds good to me.

File: src/coreclr/src/vm/mlinfo.cpp [hunk 2]
```diff
@@ -2784,22 +2784,35 @@ MarshalInfo::MarshalInfo(Module* pModule,
...
-                    || m_pMT->HasSameTypeDefAs(MscorlibBinder::GetClass(CLASS__VECTOR256T))
+                // * Vector<T>: Has a variable size (either __m128 or __m256) and isn't readily usable for interop scenarios
+
+                if (IsFieldScenario())
+                {
+                    if (m_pMT->HasSameTypeDefAs(g_pByReferenceClass))
+                    {
+                        // We need to allow Nullable<T> and VectorX<T> fields for people who are using Marshal.SizeOf instead of Unsafe.SizeOf
+                        // for back-compat reasons, but we still don't want to allow ByReference<T>.
+                        m_resID = IDS_EE_BADMARSHAL_GENERICS_RESTRICTION;
```
Comment (jkotas) [inline src/coreclr/src/vm/mlinfo.cpp]: Was this disallowed in .NET Core 3.0?

**Comment by jkotas** [comment]
Could you please add tests for the different cases we have discussed above?

**Comment by jkoritzinsky** [comment]
Will do!

File: src/coreclr/src/vm/mlinfo.cpp (hunk 2 above)
Comment (jkoritzinsky) [reply src/coreclr/src/vm/mlinfo.cpp]: I will go check again to validate.

**Comment by MichalStrehovsky** [comment]
Could you also match this with MarshalHelpers.cs in Crossgen2?

https://github.com/dotnet/runtime/blob/a716fa2f13f22fdf6602130c07d9fd14c0c26f33/src/coreclr/src/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs#L337-L355

If you need to narrow down to field marshalling only, the `marshallerType` parameter has it.

File: src/coreclr/src/vm/mlinfo.cpp (hunk 2 above)
Comment (jkoritzinsky) [reply src/coreclr/src/vm/mlinfo.cpp]: Due to C# language restrictions around ref structs as generic type parameters, this was only possible by using the deprecated `Marshal.SizeOf(Type t)` signature (which is also marked `EditorBrowsableState.Never`), which has been deprecated since before the introduction of `ByReference<T>` and family. It is disallowed with the not-deprecated `Marshal.SizeOf<T>` signature.

I can still change this back if we feel that we should, but that would allow users to marshal a `Span<T>` as a structure, which I don't know if we want to allow (this block was explicitly put in place as a way to block marshalling `Span<T>`).

Comment (jkotas) [reply src/coreclr/src/vm/mlinfo.cpp]: I would keep all .NET Core 3.x -> 5.x potentially breaking changes for a separate issue / PR. When we mix bug fixes and breaking changes together, nobody can figure our what actually happened after the fact.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Linux job failure is an intermittent issue tracked with AzDO.
MacOS failure is #2176 

I'm going to merge this in so we can unblock Bing.
