### PR TITLE
[RateLimiting] Dequeue items when queuing with NewestFirst

### LINKED ISSUE #62817: QueueProcessingOrder.NewestFirst WaitAsync should drop the oldest item when the queue is full
### Description

QueueProcessingOrder.NewestFirst is used for a stack pattern (FILO), so the newest entry in line always gets processed next. However, when the queue fills up it starts refusing to add new entries, keeping older entries in the queue.

Instead, it should add the new entry to the front and drop the oldest entry from the back.

### Reproduction Steps

```
        var limiter = new System.Threading.RateLimiting.ConcurrencyLimiter(
            new System.Threading.RateLimiting.ConcurrencyLimiterOptions(
                permitLimit: 1, queueProcessingOrder: QueueProcessingOrder.NewestFirst, queueLimit: 2));

        var lease1 = limiter.Acquire(); // Succeeds, exhausts permitLimit.
        var lease2Task = limiter.WaitAsync(); // Incomplete, queued
        var lease3Task = limiter.WaitAsync(); // Incomplete, queued, exhausts queueLimit.

        var lease4Task = limiter.WaitAsync();
        // Expected: Incomplete, lease2Task completes without acquiring.
        // Actual: Completes immediately without acquiring. lease2Task remains queued.
```

### Expected behavior

WaitAsync should queue a new item and drop the oldest item when the queue is full

### Actual behavior

WaitAsync does not queue a new item and maintains the oldest item when the queue is full

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

.NET 7

### Other information

_No response_

### PR DESCRIPTION
**Pull request by BrennanConroy**
When using `QueueProcessingOrder.NewestFirst` and the rate limiters' queue is full, valid calls to `WaitAsync()` should de-queue the oldest items until the new acquisition request can be queued.

Fixes #62817

### CODE REVIEW

**Review by halter73 — APPROVED** [review]

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/TokenBucketRateLimiter.cs [hunk 1]
```diff
@@ -104,7 +104,22 @@ protected override ValueTask<RateLimitLease> WaitAsyncCore(int tokenCount, Cance
...
+                    {
+                        // remove oldest items from queue until there is space for the newest acquisition request
+                        do
+                        {
+                            RequestRegistration oldestRequest = _queue.DequeueHead();
+                            _queueCount -= oldestRequest.Count;
+                            Debug.Assert(_queueCount >= 0);
+                            oldestRequest.Tcs.TrySetResult(FailedLease);
+                        }
+                        while (_queueCount + tokenCount > _options.QueueLimit);
```
Comment (halter73) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/TokenBucketRateLimiter.cs:117]: Do you think it would be worthwhile to share more logic between the rate limiter implementations?

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/ConcurrencyLimiter.cs [hunk 2]
```diff
@@ -98,7 +98,22 @@ protected override ValueTask<RateLimitLease> WaitAsyncCore(int permitCount, Canc
                 // Don't queue if queue limit reached
```
Comment (Tratcher) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/ConcurrencyLimiter.cs:98]: Outdated comment

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/ConcurrencyLimiter.cs [hunk 3]
```diff
@@ -98,7 +98,22 @@ protected override ValueTask<RateLimitLease> WaitAsyncCore(int permitCount, Canc
...
+                    {
+                        // remove oldest items from queue until there is space for the newest request
+                        do
+                        {
+                            RequestRegistration oldestRequest = _queue.DequeueHead();
+                            _queueCount -= oldestRequest.Count;
+                            Debug.Assert(_queueCount >= 0);
+                            oldestRequest.Tcs.TrySetResult(FailedLease);
+                        }
+                        while (_queueCount + permitCount > _options.QueueLimit);
```
Comment (Tratcher) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/ConcurrencyLimiter.cs:111]: Infinite loop if permitCount > QueueLimit?

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/ConcurrencyLimiter.cs [hunk 4]
```diff
@@ -98,7 +98,22 @@ protected override ValueTask<RateLimitLease> WaitAsyncCore(int permitCount, Canc
                 // Don't queue if queue limit reached
                 if (_queueCount + permitCount > _options.QueueLimit)
```
Comment (stephentoub) [inline src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/ConcurrencyLimiter.cs:99]: Is it possible _queueCount + permitCount could wrap to be < 0?

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/TokenBucketRateLimiter.cs (hunk 1 above)
Comment (BrennanConroy) [reply src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/TokenBucketRateLimiter.cs]: 👍 
Yeah it seems like a lot of the logic is common

File: src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/ConcurrencyLimiter.cs (hunk 4 above)
Comment (BrennanConroy) [reply src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/ConcurrencyLimiter.cs]: Yep, fixed by using subtraction instead and added a test to cover that case.

**Review by Tratcher — APPROVED** [review]
