### PR TITLE
JIT: Fix overzealous assert in `CodeGen::genSSE42Intrinsic`

### LINKED ISSUE #105821: JIT: Assertion failed '(op2->GetRegNum() != targetReg) || (op1Reg == targetReg)' during 'Generate code'
```csharp
// Generated by Fuzzlyn v2.2 on 2024-08-01 15:50:23
// Run on X64 Linux
// Seed: 16776152078868034128-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86avx512fx64,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 17.3 KiB to 0.4 KiB in 00:00:34
// Hits JIT assert in Debug:
// Assertion failed '(op2->GetRegNum() != targetReg) || (op1Reg == targetReg)' in 'Program:M1(short)' during 'Generate code' (IL size 18; hash 0xb20f93e4; MinOpts)
// 
//     File: /__w/1/s/src/coreclr/jit/hwintrinsiccodegenxarch.cpp Line: 2242
// 
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static void Main()
    {
        M1(0);
    }

    public static void M1(short arg0)
    {
        Sse42.Crc32(Bmi2.ParallelBitDeposit(0, 0) % 0, (uint)arg0);
    }
}
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #105821.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib

**Review by EgorBo — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Isn't the assert fine? If it triggers it should mean problems. We would override the "index" (in `op2`) with the current CRC value (in `op1Reg`), since `targetReg` and `op2Reg` coincide.

What are the registers in this case?

**Comment by jakobbotsch** [comment]
I think the assert should instead be:
```
assert(!op2->isUsedFromReg() || (op2->GetRegNum() != targetReg) || (op1Reg == targetReg));
```

**Comment by tannergooding** [comment]
> !op2->isUsedFromReg()

Are we getting register assignments when we aren't used from reg?

**Comment by jakobbotsch** [comment]
Evidently so. In this case `op2` is used from a spill temp, so it needs a register to compute the def into. However, it would probably be possible for codegen to unset the register assignment spilling as part of the def.

**Comment by tannergooding** [comment]
That definitely seems like a safer and more robust long term solution; but probably not something we want for .NET 9

I think your proposed assert handles it well enough for the short term fix. We do indeed need to ensure that the `mov tgt, op1` isn't overwriting `op2`, as that would produce incorrect results (and likely mean we forgot a `delayFree` somewhere).

**Comment by amanasifkhalid** [comment]
> What are the registers in this case?
`targetReg` and `op2->GetRegNum()` are `rax`, `op1Reg` is `rdx`.

Thanks for the proposed assert, and for opening an issue. I think you're right that we didn't unset the register assignment for `op2` somewhere -- the updated assert works.

**Review by tannergooding — APPROVED** [review]

File: src/tests/JIT/Regression/JitBlue/Runtime_105821/Runtime_105821.cs [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+// 
+using System;
+using System.Runtime.CompilerServices;
+using System.Numerics;
+using System.Runtime.Intrinsics;
+using System.Runtime.Intrinsics.X86;
+
+public class Program
+{
+    public static void Main()
```
Comment (tannergooding) [inline src/tests/JIT/Regression/JitBlue/Runtime_105821/Runtime_105821.cs:21]: Doesn't this need to use xunit, `[Fact]`, and be named something like `TestEntryPoint` to match the convention for tests in this folder?

Presumably `class Program` should then also be named `Runtime_105821` so that we can correctly filter and run it individually?

Comment (amanasifkhalid) [reply src/tests/JIT/Regression/JitBlue/Runtime_105821/Runtime_105821.cs]: Right, fixed.

**Review by tannergooding — APPROVED** [review]
