### PR TITLE
Capture Reverse P/Invoke frame offset in x86 GC info and disallow return hijacking of reverse P/Invokes on x86.

### LINKED ISSUE #45326: Test failure: readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=901492&view=ms.vss-test-web.build-test-results-tab&runId=28795396&resultId=106816&paneView=debug

CoreCLR Linux x64 Checked jitstress1_tiered @ Ubuntu.1804.Amd64.Open


Error message
~~~
1 / 1 (100%, 1 failed): failed in 15981 msecs, exit code 134, expected 0: corerun /home/helixbot/work/A64D08B1/p/crossgen2/crossgen2.dll @/home/helixbot/work/A64D08B1/w/A68C0979/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp\n\nReturn code:      1
Raw output file:      /home/helixbot/work/A64D08B1/w/A68C0979/e/readytorun/coreroot_determinism/Reports/readytorun.coreroot_determinism/coreroot_determinism/coreroot_determinism.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/A64D08B1/p/corerun coreroot_determinism.dll ''
================================== Compiling with seed 1 ==================================
Locating output folder /home/helixbot/work/A64D08B1/w/A68C0979/e/readytorun/coreroot_determinism/coreroot_determinism/seed1
Deleting 0 output folders
Successfully deleted 0 output folders in 60 msecs
Using dotnet: /home/helixbot/work/A64D08B1/p/corerun
1 / 1 (0%, 0 failed): launching: /home/helixbot/work/A64D08B1/p/corerun /home/helixbot/work/A64D08B1/p/crossgen2/crossgen2.dll @/home/helixbot/work/A64D08B1/w/A68C0979/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
Compilation failed. /home/helixbot/work/A64D08B1/p/corerun /home/helixbot/work/A64D08B1/p/R2RTest/R2RTest.dll compile-directory -cr /home/helixbot/work/A64D08B1/p -in TestAssemblies --nojit --noexe --large-bubble --release --nocleanup -out seed1 failed with exit code 1
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/A64D08B1/p
> /home/helixbot/work/A64D08B1/w/A68C0979/e/readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh
Expected: True
Actual:   False

Stack trace
   at readytorun_coreroot_determinism._coreroot_determinism_coreroot_determinism_._coreroot_determinism_coreroot_determinism_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.x64.Checked/TestWrappers/readytorun.coreroot_determinism/readytorun.coreroot_determinism.XUnitWrapper.cs:line 153
~~~
<!-- runfo report start -->
Runfo Tracking Issue: [coreroot_determinism.cmd](https://runfo.azurewebsites.net/tracking/issue/136)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x86 Checked @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-45673e8a608245cda9/PayloadGroup0/console.0bb29f21.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A26%2525253A23Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D9ULHSTjt0ihFC9gf7YDxG7majUUoOZji7HAZsTkT0W4%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-45673e8a608245cda9/PayloadGroup0/6ce84f4f-e176-4e47-b3ca-39bdf55aad91.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A26%2525253A23Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D9ULHSTjt0ihFC9gf7YDxG7majUUoOZji7HAZsTkT0W4%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-82de7a76fa45460d99/PayloadGroup0/console.83c9f799.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A26%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DNuFcH0sVNHok3BkCMe9IqPEeprT%2525252BajlKUh4dn%2525252FxnMtQ%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-82de7a76fa45460d99/PayloadGroup0/4ed6d96c-ae67-41f2-ab2d-d88749a7a52d.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A26%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DNuFcH0sVNHok3BkCMe9IqPEeprT%2525252BajlKUh4dn%2525252FxnMtQ%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows arm64 Checked @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-178cab6870134fb396/PayloadGroup0/console.86d66aca.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A27%2525253A33Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Ds2VHm%2525252B1dX3QUhFDtt5fWP45qaaNOevMqb7mMloy5bAw%2525253D)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-178cab6870134fb396/PayloadGroup0/e9d9ffa9-7490-4d2b-99f3-2181e0c9bd23.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A27%2525253A33Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Ds2VHm%2525252B1dX3QUhFDtt5fWP45qaaNOevMqb7mMloy5bAw%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-a6bd1e0519f241aa99/PayloadGroup0/console.2667fcb0.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A27%2525253A33Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DRdIRZkLia4cMCr59IGHTiaUtIPxidmRPZNSMAKxUok0%2525253D)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-a6bd1e0519f241aa99/PayloadGroup0/867c92d9-5616-4d2f-b5f5-ef24f0dfc4f0.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A27%2525253A33Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DRdIRZkLia4cMCr59IGHTiaUtIPxidmRPZNSMAKxUok0%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x64 Checked @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-d7d4dedcc8af4f95a0/PayloadGroup0/console.d8dba8d2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A32%2525253A56Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dn1XBbZ2h9zWJrigtOy7aeerbzpEqtIOECUxyp3ao9gI%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-d7d4dedcc8af4f95a0/PayloadGroup0/0d9eb083-abca-43a4-bcdf-f3c38752f504.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A32%2525253A56Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dn1XBbZ2h9zWJrigtOy7aeerbzpEqtIOECUxyp3ao9gI%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-e4add070328f477395/PayloadGroup0/console.48ad777e.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A32%2525253A56Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DBprzL1NV0HOFXIS6pgPCsNFxIBFowICS%2525252BJSXRHa1RP8%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-e4add070328f477395/PayloadGroup0/d565fbf9-eb2a-4972-9532-bcf71a1d0311.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T04%2525253A32%2525253A56Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DBprzL1NV0HOFXIS6pgPCsNFxIBFowICS%2525252BJSXRHa1RP8%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x86 Checked @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-94958da30bac4a2cb1/PayloadGroup0/console.18440a90.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A42%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DYBRhwmVYEmTCQfT4fu1ntN8YfGg242DK7eQ1dJsEbzo%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-94958da30bac4a2cb1/PayloadGroup0/770e27e8-b34b-4c28-9a3b-db8cb0c847ca.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A42%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DYBRhwmVYEmTCQfT4fu1ntN8YfGg242DK7eQ1dJsEbzo%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-c57ae94ba81d4f848e/PayloadGroup0/console.51130d69.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A42%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DBEMd392jw6ODLE2%2525252FHs3FnU6IiV2tdiPzv%2525252FkvZ3pOYQU%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-c57ae94ba81d4f848e/PayloadGroup0/1e1d185a-16c4-4c23-be3e-df05a4d5290e.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A42%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DBEMd392jw6ODLE2%2525252FHs3FnU6IiV2tdiPzv%2525252FkvZ3pOYQU%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows arm64 Checked @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-8bad1c9e03244f1ebc/PayloadGroup0/console.2464df8e.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A55Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DteYrgV%2525252FU3hMX38GszmMLQ18w5DpJnIv7gckkRlyv1FE%2525253D)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-8bad1c9e03244f1ebc/PayloadGroup0/e0f1f5cb-505a-4377-ae87-02cd39e2f96b.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A55Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DteYrgV%2525252FU3hMX38GszmMLQ18w5DpJnIv7gckkRlyv1FE%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-35ba2eb5c7384283b4/PayloadGroup0/console.0718d3db.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A55Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DCZckEzhVNy73r9tbj5NYW5ungJ3oNy1n9pHXh%2525252F%2525252BZeYg%2525253D)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-35ba2eb5c7384283b4/PayloadGroup0/5ed09993-6b54-48f4-ad38-6a34a7122883.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A55Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DCZckEzhVNy73r9tbj5NYW5ungJ3oNy1n9pHXh%2525252F%2525252BZeYg%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-35ba2eb5c7384283b4/PayloadGroup0/console.0718d3db.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A55Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DCZckEzhVNy73r9tbj5NYW5ungJ3oNy1n9pHXh%2525252F%2525252BZeYg%2525253D)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-35ba2eb5c7384283b4/PayloadGroup0/5ed09993-6b54-48f4-ad38-6a34a7122883.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A55Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DCZckEzhVNy73r9tbj5NYW5ungJ3oNy1n9pHXh%2525252F%2525252BZeYg%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x64 Checked @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-307107490da542958c/PayloadGroup0/console.2787e582.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DKB3zCO%2525252FWgeQ0ckqJtKu%2525252BMEo6%2525252FRv8J8j0oJqu7zmPD24%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-307107490da542958c/PayloadGroup0/3cbab434-28eb-499e-be3e-20252c1e5cfc.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DKB3zCO%2525252FWgeQ0ckqJtKu%2525252BMEo6%2525252FRv8J8j0oJqu7zmPD24%2525253D)|
|[1079379](https://dev.azure.com/dnceng/public/_build/results?buildId=1079379)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-2e7194c77dbe4d1e99/PayloadGroup0/console.d75e935c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DklRc5J6Sw9BmCL6f%2525252BCH11Em1JJtSz7DCrpSMGVWjg3w%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-2e7194c77dbe4d1e99/PayloadGroup0/ee9172cd-aa72-419b-9604-c000172c2ae4.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-29T12%2525253A46%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DklRc5J6Sw9BmCL6f%2525252BCH11Em1JJtSz7DCrpSMGVWjg3w%2525253D)|
|[1078291](https://dev.azure.com/dnceng/public/_build/results?buildId=1078291)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x64 Checked @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-cea67f2415e44f65a7/PayloadGroup0/console.f6df4aa7.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-28T23%2525253A04%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5AO1iXEO4mdVKh%2525252FqAP%2525252Bovdc8BYvoqfh%2525252FnbUCOyQNPGw%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-cea67f2415e44f65a7/PayloadGroup0/eaefbeb9-9bc5-4002-8e6d-a63ba11c034f.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-28T23%2525253A04%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5AO1iXEO4mdVKh%2525252FqAP%2525252Bovdc8BYvoqfh%2525252FnbUCOyQNPGw%2525253D)|
|[1078291](https://dev.azure.com/dnceng/public/_build/results?buildId=1078291)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-cc2faef6a8d1428787/PayloadGroup0/console.63c2df03.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-28T23%2525253A04%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D%2525252FsRJRrQF3veUF0tnZRhDY9RbouLqQfFPANwo4BolR5I%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-cc2faef6a8d1428787/PayloadGroup0/0e35ee3b-eb46-4973-87de-cfa310d51059.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-28T23%2525253A04%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D%2525252FsRJRrQF3veUF0tnZRhDY9RbouLqQfFPANwo4BolR5I%2525253D)|
|[1078291](https://dev.azure.com/dnceng/public/_build/results?buildId=1078291)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows arm64 Checked @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-493d4a1d15c74df08b/PayloadGroup0/console.4d1ecac5.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-28T23%2525253A05%2525253A22Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DQjy5lE6D9Ul2recqzzxQp3iUEiMGpdiyr1j%2525252FrjAjaF0%2525253D)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-493d4a1d15c74df08b/PayloadGroup0/2468c49e-b083-4024-ba16-4703489d798f.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-28T23%2525253A05%2525253A22Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DQjy5lE6D9Ul2recqzzxQp3iUEiMGpdiyr1j%2525252FrjAjaF0%2525253D)|
|[1078291](https://dev.azure.com/dnceng/public/_build/results?buildId=1078291)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50922](https://github.com/dotnet/runtime/pull/50922)|CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-c1ceeeec769e4c67ba/PayloadGroup0/console.fd118707.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-28T23%2525253A05%2525253A22Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D2gMY15rLxsYeD4TQewjZka3outGxdhPxLHUgNW1rUCo%2525253D)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50922-merge-c1ceeeec769e4c67ba/PayloadGroup0/fd7e8b1e-585d-4119-a0fd-2aa31b4a60ae.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-28T23%2525253A05%2525253A22Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D2gMY15rLxsYeD4TQewjZka3outGxdhPxLHUgNW1rUCo%2525253D)|
|[1059736](https://dev.azure.com/dnceng/public/_build/results?buildId=1059736)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50232](https://github.com/dotnet/runtime/pull/50232)|CoreCLR windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50232-merge-85483e7227444d7584/PayloadGroup0/console.1c196db9.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-16T16%2525253A03%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DKVA2eBEwiP5ixY%2525252BDZOR%2525252FUMR2xo%2525252F5fKPhjgEwkpeOi%2525252Bk%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50232-merge-85483e7227444d7584/PayloadGroup0/15847962-cf1b-48f0-9d8f-4f7d307f3e16.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-16T16%2525253A03%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DKVA2eBEwiP5ixY%2525252BDZOR%2525252FUMR2xo%2525252F5fKPhjgEwkpeOi%2525252Bk%2525253D)|
|[1059736](https://dev.azure.com/dnceng/public/_build/results?buildId=1059736)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50232](https://github.com/dotnet/runtime/pull/50232)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50232-merge-2ee9d2ffd04c4362ad/PayloadGroup0/console.eb61b776.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-16T16%2525253A03%2525253A31Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DghEKxFpuuUYicZXO6YCRxMHfdLQ0iaZxMpBdIhMPjq8%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50232-merge-2ee9d2ffd04c4362ad/PayloadGroup0/58dd224b-d985-4e6f-839f-0bb3fa2e7000.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-16T16%2525253A03%2525253A31Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DghEKxFpuuUYicZXO6YCRxMHfdLQ0iaZxMpBdIhMPjq8%2525253D)|
|[1059736](https://dev.azure.com/dnceng/public/_build/results?buildId=1059736)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50232](https://github.com/dotnet/runtime/pull/50232)|CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50232-merge-115d44b55ede4bb7b8/PayloadGroup0/console.df628fff.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-16T16%2525253A07%2525253A17Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DblGJWD2Jvp46F5dJaZ%2525252FT5ggjcSLBEOPUwzKNEuWvh1A%2525253D)||||
|[1057171](https://dev.azure.com/dnceng/public/_build/results?buildId=1057171)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50082](https://github.com/dotnet/runtime/pull/50082)|CoreCLR windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50082-merge-09ea0871d0464159bf/PayloadGroup0/console.ca7470ce.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-15T02%2525253A48%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DfEwyfT6PXa3Q4Exs53H2ynxTGGiGLzghQVReghXMOik%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50082-merge-09ea0871d0464159bf/PayloadGroup0/b0a06be8-481b-4950-8244-606e51d8ce71.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-15T02%2525253A48%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DfEwyfT6PXa3Q4Exs53H2ynxTGGiGLzghQVReghXMOik%2525253D)|
|[1057171](https://dev.azure.com/dnceng/public/_build/results?buildId=1057171)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50082](https://github.com/dotnet/runtime/pull/50082)|CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50082-merge-70bfb8df6d7e4b50b0/PayloadGroup0/console.fce8013c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-15T02%2525253A49%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DXNxLNGBnTBryn15rvaGxCXAasw1S3O6Ilv0vjRcWjkM%2525253D)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50082-merge-70bfb8df6d7e4b50b0/PayloadGroup0/e006b163-b3e0-4e20-b8a0-eb7e183fa5c1.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-15T02%2525253A49%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DXNxLNGBnTBryn15rvaGxCXAasw1S3O6Ilv0vjRcWjkM%2525253D)|
|[1057171](https://dev.azure.com/dnceng/public/_build/results?buildId=1057171)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 50082](https://github.com/dotnet/runtime/pull/50082)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50082-merge-ff7883d91b6d468eae/PayloadGroup0/console.21038690.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-15T02%2525253A49%2525253A48Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dv6%2525252Bvwv52ReQokNYF9eHqOAMuLxsTbRB%2525252Ba6AxHbMBSOg%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50082-merge-ff7883d91b6d468eae/PayloadGroup0/5b96d28f-19c6-4229-9bf1-b346f0063671.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-15T02%2525253A49%2525253A48Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dv6%2525252Bvwv52ReQokNYF9eHqOAMuLxsTbRB%2525252Ba6AxHbMBSOg%2525253D)|
|[1037848](https://dev.azure.com/dnceng/public/_build/results?buildId=1037848)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49576](https://github.com/dotnet/runtime/pull/49576)|CoreCLR windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49576-merge-0d432a2a07704f209e/PayloadGroup0/console.d8ec9516.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-02T15%2525253A46%2525253A52Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D3JxZ3SkrdbVWD4hwlSF34XXy7NrLBn7YQcnDrdspeLE%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49576-merge-0d432a2a07704f209e/PayloadGroup0/71b96d7b-0b3b-43c0-9ea9-6d77f5a63516.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-04-02T15%2525253A46%2525253A52Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D3JxZ3SkrdbVWD4hwlSF34XXy7NrLBn7YQcnDrdspeLE%2525253D)|
|[1028832](https://dev.azure.com/dnceng/public/_build/results?buildId=1028832)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49295](https://github.com/dotnet/runtime/pull/49295)|CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49295-merge-0787f112703b4b09a3/PayloadGroup0/console.864dfa30.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-29T13%2525253A44%2525253A55Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DqGkeUL%2525252BoOoUgapupvCMkudVvlJ2Xv4Q5pinN6yjXTXU%2525253D)||||
|[1028832](https://dev.azure.com/dnceng/public/_build/results?buildId=1028832)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49295](https://github.com/dotnet/runtime/pull/49295)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49295-merge-d9f7a314eaf2405c8e/PayloadGroup0/console.78db2d57.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-29T13%2525253A48%2525253A37Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DjvMfB8d7QB8zfkWxgJrCONUjKLnV7km2du%2525252Fhdn9kjmY%2525253D)||||
|[1028832](https://dev.azure.com/dnceng/public/_build/results?buildId=1028832)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49295](https://github.com/dotnet/runtime/pull/49295)|CoreCLR windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49295-merge-c7fa2984ef76412486/PayloadGroup0/console.5cfa2788.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-29T13%2525253A49%2525253A10Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dudkn4jA3of4u3dkBgzApa6CMeKvKpv5XeA8kWvz2H8g%2525253D)||||
|[1027318](https://dev.azure.com/dnceng/public/_build/results?buildId=1027318)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47901](https://github.com/dotnet/runtime/pull/47901)|CoreCLR windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47901-merge-ce08df37f6604415b3/PayloadGroup0/console.fd42c56c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-28T19%2525253A21%2525253A47Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Ds0AZrq%2525252FOpGGFglPgBTkCh%2525252B2fG3PDE0kjw91zbMGq6kM%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47901-merge-ce08df37f6604415b3/PayloadGroup0/a9136645-a985-4c04-ab66-57606c70c256.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-28T19%2525253A21%2525253A47Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Ds0AZrq%2525252FOpGGFglPgBTkCh%2525252B2fG3PDE0kjw91zbMGq6kM%2525253D)|
|[1025677](https://dev.azure.com/dnceng/public/_build/results?buildId=1025677)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49257](https://github.com/dotnet/runtime/pull/49257)|CoreCLR windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49257-merge-aebf0543d0b6495ab4/PayloadGroup0/console.586af3ef.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-26T06%2525253A51%2525253A10Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DZwM2huJhAl1qQ%2525252B5fAD5aQjriRtuU1nIe6jOSSw7SLbY%2525253D)||||
|[1025113](https://dev.azure.com/dnceng/public/_build/results?buildId=1025113)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49183](https://github.com/dotnet/runtime/pull/49183)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49183-merge-b8503c7dc79944e5a9/PayloadGroup0/console.c48831a6.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-25T23%2525253A06%2525253A51Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DP%2525252FesjL8cW3l%2525252Bd2M8r9EwIaZIUznbuW1%2525252F9Llsea32Xvk%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49183-merge-b8503c7dc79944e5a9/PayloadGroup0/6fa705bb-dd02-47ad-91e9-5a131be77393.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-25T23%2525253A06%2525253A51Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DP%2525252FesjL8cW3l%2525252Bd2M8r9EwIaZIUznbuW1%2525252F9Llsea32Xvk%2525253D)|
|[1023780](https://dev.azure.com/dnceng/public/_build/results?buildId=1023780)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48936](https://github.com/dotnet/runtime/pull/48936)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48936-merge-e42d281dc14046859e/PayloadGroup0/console.93526a7e.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-25T02%2525253A11%2525253A42Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DlY6PM9xSWeJPeM49P5pVTFWr571T%2525252BcrOHoeCpjlgOFM%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48936-merge-e42d281dc14046859e/PayloadGroup0/c9fa45ee-1a42-423e-afc0-be3a4106c048.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-25T02%2525253A11%2525253A42Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DlY6PM9xSWeJPeM49P5pVTFWr571T%2525252BcrOHoeCpjlgOFM%2525253D)|
|[1023759](https://dev.azure.com/dnceng/public/_build/results?buildId=1023759)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49178](https://github.com/dotnet/runtime/pull/49178)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49178-merge-738bebff97d94f578f/PayloadGroup0/console.dc73746b.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-25T01%2525253A54%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DdhqQjKlmC8FuZXv4ukF9fGYCvTqTHfPBeoLSkmkVhqY%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49178-merge-738bebff97d94f578f/PayloadGroup0/4d3aa5fd-06f1-4721-a24f-da5ec8d63211.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-25T01%2525253A54%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DdhqQjKlmC8FuZXv4ukF9fGYCvTqTHfPBeoLSkmkVhqY%2525253D)|
|[1023260](https://dev.azure.com/dnceng/public/_build/results?buildId=1023260)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49066](https://github.com/dotnet/runtime/pull/49066)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49066-merge-fb3cd99ee1e7452599/PayloadGroup0/console.dd994958.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-24T22%2525253A02%2525253A40Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DlliYN9XgRVTqtncoB9hoc53b9rn%2525252F0L6AthnT22%2525252FmUHw%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49066-merge-fb3cd99ee1e7452599/PayloadGroup0/293af25f-0a9f-4152-8a3a-736da7c03717.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-24T22%2525253A02%2525253A40Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DlliYN9XgRVTqtncoB9hoc53b9rn%2525252F0L6AthnT22%2525252FmUHw%2525253D)|
|[1022125](https://dev.azure.com/dnceng/public/_build/results?buildId=1022125)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48936](https://github.com/dotnet/runtime/pull/48936)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48936-merge-3044852deef74710a9/PayloadGroup0/console.560b53ba.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-24T03%2525253A34%2525253A20Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DkAwFofo9zlddnJ9hdqFcNkkuUEmqdxLKpu4854o5lmk%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48936-merge-3044852deef74710a9/PayloadGroup0/1f2455f4-cf02-490e-b704-3e8dee44df0c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-24T03%2525253A34%2525253A20Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DkAwFofo9zlddnJ9hdqFcNkkuUEmqdxLKpu4854o5lmk%2525253D)|
|[1021719](https://dev.azure.com/dnceng/public/_build/results?buildId=1021719)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49093](https://github.com/dotnet/runtime/pull/49093)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49093-merge-fa25ce38721446b6ba/PayloadGroup0/console.3bbfd262.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-24T00%2525253A13%2525253A23Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DJGj6kZi%2525252FDjfbwLFbygDoJ1LPyD%2525252F3x85FTs9pY3u6vzU%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49093-merge-fa25ce38721446b6ba/PayloadGroup0/e851a180-22b1-4ac0-90a3-113bd261a1dd.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-24T00%2525253A13%2525253A23Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DJGj6kZi%2525252FDjfbwLFbygDoJ1LPyD%2525252F3x85FTs9pY3u6vzU%2525253D)|
|[1021643](https://dev.azure.com/dnceng/public/_build/results?buildId=1021643)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48589](https://github.com/dotnet/runtime/pull/48589)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48589-merge-bfb15898b4664456b3/PayloadGroup0/console.29fa231d.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-23T23%2525253A52%2525253A48Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D8u2QpBf2JSECZjCPEJ7i2z805KJm5vaFgTOe%2525252BMWiAH8%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48589-merge-bfb15898b4664456b3/PayloadGroup0/95dc4021-83dd-4c7f-a3ec-d62fe488e140.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-23T23%2525253A52%2525253A48Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D8u2QpBf2JSECZjCPEJ7i2z805KJm5vaFgTOe%2525252BMWiAH8%2525253D)|
|[1021240](https://dev.azure.com/dnceng/public/_build/results?buildId=1021240)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49074](https://github.com/dotnet/runtime/pull/49074)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49074-merge-8730f57bdaad46c99b/PayloadGroup0/console.431fa605.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-23T21%2525253A19%2525253A19Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DFDvpLGqUveES4sIxbZGNNA5s7gcqdaLwtOz6s%2525252BbjV40%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49074-merge-8730f57bdaad46c99b/PayloadGroup0/ed1cdf2c-4b11-40e8-9c57-2341390d9ac2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-23T21%2525253A19%2525253A19Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DFDvpLGqUveES4sIxbZGNNA5s7gcqdaLwtOz6s%2525252BbjV40%2525253D)|
|[1020340](https://dev.azure.com/dnceng/public/_build/results?buildId=1020340)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48589](https://github.com/dotnet/runtime/pull/48589)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48589-merge-77d6bfffe32e4bd48b/PayloadGroup0/console.47dff990.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-23T09%2525253A52%2525253A26Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DlM9Mo2%2525252ByANlXSs%2525252BDQzGM%2525252F6tzbjE%2525252FIckPoEQ6s7JLFiw%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48589-merge-77d6bfffe32e4bd48b/PayloadGroup0/16a5dc28-6d81-4292-955b-2886252d5945.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-23T09%2525253A52%2525253A26Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DlM9Mo2%2525252ByANlXSs%2525252BDQzGM%2525252F6tzbjE%2525252FIckPoEQ6s7JLFiw%2525253D)|
|[1019099](https://dev.azure.com/dnceng/public/_build/results?buildId=1019099)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 49021](https://github.com/dotnet/runtime/pull/49021)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49021-merge-6238ad0c13bd4d1da8/PayloadGroup0/console.cbed545b.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-22T19%2525253A50%2525253A28Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DJ35Hx8IKQLA0ru%2525252BW8QBfdbTA9cp26sRTOZRr4GIakqs%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49021-merge-6238ad0c13bd4d1da8/PayloadGroup0/21173861-b2da-46ea-aed7-f6be7c2e5671.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-22T19%2525253A50%2525253A28Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DJ35Hx8IKQLA0ru%2525252BW8QBfdbTA9cp26sRTOZRr4GIakqs%2525253D)|
|[1017879](https://dev.azure.com/dnceng/public/_build/results?buildId=1017879)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48923](https://github.com/dotnet/runtime/pull/48923)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48923-merge-4b1302324b2842369b/PayloadGroup0/console.1c203ceb.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-22T00%2525253A41%2525253A02Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DW1dx1LbxRcLVRDCy0t2Iw%2525252FWh7Ecli3o2LlVhtbCMI2c%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48923-merge-4b1302324b2842369b/PayloadGroup0/71b14f28-2abb-4726-904d-b695e89dfdb2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-22T00%2525253A41%2525253A02Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DW1dx1LbxRcLVRDCy0t2Iw%2525252FWh7Ecli3o2LlVhtbCMI2c%2525253D)|
|[1017716](https://dev.azure.com/dnceng/public/_build/results?buildId=1017716)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45058](https://github.com/dotnet/runtime/pull/45058)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45058-merge-3770451e4b38461095/PayloadGroup0/console.d9b9651c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-21T23%2525253A47%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DmSdU4fmeMfJxQz1WXDmNKcSInkLhEqhT%2525252FGubPJMh9Po%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45058-merge-3770451e4b38461095/PayloadGroup0/518fcda6-c4ec-4d58-8bd9-5aa25a9ecb96.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-21T23%2525253A47%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DmSdU4fmeMfJxQz1WXDmNKcSInkLhEqhT%2525252FGubPJMh9Po%2525253D)|
|[1017614](https://dev.azure.com/dnceng/public/_build/results?buildId=1017614)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48923](https://github.com/dotnet/runtime/pull/48923)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48923-merge-e49bc1f37db54239b3/PayloadGroup0/console.9e0b5706.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-21T22%2525253A29%2525253A47Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DItP0g6MRdQjG0gKNWOSJIUcnnvLHB5A870dYJV9F2Hg%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48923-merge-e49bc1f37db54239b3/PayloadGroup0/baae0dec-bd69-4b61-9b96-22365e3539e7.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-21T22%2525253A29%2525253A47Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DItP0g6MRdQjG0gKNWOSJIUcnnvLHB5A870dYJV9F2Hg%2525253D)|
|[1013297](https://dev.azure.com/dnceng/public/_build/results?buildId=1013297)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-093795a9f38e4bc2bb/PayloadGroup0/console.b794c532.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-18T10%2525253A34%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DFBs3gNmy6uWZXXlQWESiBdigr71dvTJveLZB7AyfMJE%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-093795a9f38e4bc2bb/PayloadGroup0/f3fd765c-6292-4464-ad04-34bde40414a9.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-18T10%2525253A34%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DFBs3gNmy6uWZXXlQWESiBdigr71dvTJveLZB7AyfMJE%2525253D)|
|[1013095](https://dev.azure.com/dnceng/public/_build/results?buildId=1013095)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48677](https://github.com/dotnet/runtime/pull/48677)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48677-merge-52099ebdfbf24bb5a0/PayloadGroup0/console.ae8ca7ed.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-18T05%2525253A39%2525253A45Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DHTkanj1%2525252F8lnMeUobpzyKqSIMR9LhV561cpjTpKQw1Ug%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48677-merge-52099ebdfbf24bb5a0/PayloadGroup0/cdd7a018-8341-4e33-b774-af67c7fbfda5.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-18T05%2525253A39%2525253A45Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DHTkanj1%2525252F8lnMeUobpzyKqSIMR9LhV561cpjTpKQw1Ug%2525253D)|
|[1012960](https://dev.azure.com/dnceng/public/_build/results?buildId=1012960)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48171](https://github.com/dotnet/runtime/pull/48171)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48171-merge-c2579a538f2d467da9/PayloadGroup0/console.794d8b2d.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-18T03%2525253A43%2525253A53Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DboDqngxBvI1nRzkP2qMVBW%2525252BiC80JbSlBDMcd0sES6VQ%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48171-merge-c2579a538f2d467da9/PayloadGroup0/2cb7af83-88ea-4088-8725-a47c5b0fc95d.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-18T03%2525253A43%2525253A53Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DboDqngxBvI1nRzkP2qMVBW%2525252BiC80JbSlBDMcd0sES6VQ%2525253D)|
|[1012535](https://dev.azure.com/dnceng/public/_build/results?buildId=1012535)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48536](https://github.com/dotnet/runtime/pull/48536)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48536-merge-57da9bdf6ba8489da0/PayloadGroup0/console.19554963.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-18T00%2525253A58%2525253A31Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DCfMQ49%2525252FpDct3Kyk3MIbOIMZc8u0JWIcuwbFA%2525252FzA%2525252B9Cw%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48536-merge-57da9bdf6ba8489da0/PayloadGroup0/e547a4ce-3173-4162-b389-55959a34cf99.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-18T00%2525253A58%2525253A31Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DCfMQ49%2525252FpDct3Kyk3MIbOIMZc8u0JWIcuwbFA%2525252FzA%2525252B9Cw%2525253D)|
|[1011419](https://dev.azure.com/dnceng/public/_build/results?buildId=1011419)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48746](https://github.com/dotnet/runtime/pull/48746)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48746-merge-a6b476fbb5154a7696/PayloadGroup0/console.45e4d836.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-17T13%2525253A26%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DB89phg247T20b%2525252BF04dfzPDIxN4zV018f5ME8B%2525252BwwsyI%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48746-merge-a6b476fbb5154a7696/PayloadGroup0/e491cfd1-e8b2-48e9-99a3-54fce49117d0.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-17T13%2525253A26%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DB89phg247T20b%2525252BF04dfzPDIxN4zV018f5ME8B%2525252BwwsyI%2525253D)|
|[1011339](https://dev.azure.com/dnceng/public/_build/results?buildId=1011339)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48601](https://github.com/dotnet/runtime/pull/48601)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48601-merge-b033fbd4779146af87/PayloadGroup0/console.fe3d87e3.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-17T12%2525253A14%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVOxMwDO4YtWiXpi6rDwApWdOZ3lsryOvFCknux38avg%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48601-merge-b033fbd4779146af87/PayloadGroup0/9b94c28c-b18c-4cca-9a69-2349ef9726fc.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-17T12%2525253A14%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVOxMwDO4YtWiXpi6rDwApWdOZ3lsryOvFCknux38avg%2525253D)|
|[1010968](https://dev.azure.com/dnceng/public/_build/results?buildId=1010968)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48731](https://github.com/dotnet/runtime/pull/48731)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48731-merge-4b07e28425054424a6/PayloadGroup0/console.b75724d5.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-17T04%2525253A17%2525253A16Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DvoGSV9Lh0jLeR93Rtt2XwoUARhF%2525252BbAeehhLC%2525252BwtK3X4%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48731-merge-4b07e28425054424a6/PayloadGroup0/05749358-788d-41dd-a373-f1811298d819.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-17T04%2525253A17%2525253A16Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DvoGSV9Lh0jLeR93Rtt2XwoUARhF%2525252BbAeehhLC%2525252BwtK3X4%2525253D)|
|[1010324](https://dev.azure.com/dnceng/public/_build/results?buildId=1010324)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48435](https://github.com/dotnet/runtime/pull/48435)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48435-merge-2d4daf93e6004d2eb8/PayloadGroup0/console.97799911.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-16T22%2525253A04%2525253A12Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DB7PiJW5Fl140P4h2w20Kql2vcRypjyXv%2525252FUTpPBQMCik%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48435-merge-2d4daf93e6004d2eb8/PayloadGroup0/520a2bc1-d326-49a4-b9ce-cc61dc1ce6bc.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-16T22%2525253A04%2525253A12Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DB7PiJW5Fl140P4h2w20Kql2vcRypjyXv%2525252FUTpPBQMCik%2525253D)|
|[1009843](https://dev.azure.com/dnceng/public/_build/results?buildId=1009843)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47639](https://github.com/dotnet/runtime/pull/47639)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47639-merge-78a526b351b04168b0/PayloadGroup0/console.4225793c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-16T16%2525253A02%2525253A28Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DEs%2525252FG1bzwcz9%2525252FvVmmMjU7OcP%2525252BiUVXOWi5n08LkmMf28Q%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47639-merge-78a526b351b04168b0/PayloadGroup0/a33829f1-4736-4152-8382-138f36496ed2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-16T16%2525253A02%2525253A28Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DEs%2525252FG1bzwcz9%2525252FvVmmMjU7OcP%2525252BiUVXOWi5n08LkmMf28Q%2525253D)|
|[1009838](https://dev.azure.com/dnceng/public/_build/results?buildId=1009838)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48698](https://github.com/dotnet/runtime/pull/48698)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48698-merge-5d12109a0a714ce1bf/PayloadGroup0/console.8473a7c5.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-16T15%2525253A42%2525253A44Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DLo7ZY29n3I9cxdUb8u7MyQoZw6HHQNM9ESQVE0DM4s4%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48698-merge-5d12109a0a714ce1bf/PayloadGroup0/a2eecc34-9cdd-48e8-94d9-be1b083cb6d6.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-16T15%2525253A42%2525253A44Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DLo7ZY29n3I9cxdUb8u7MyQoZw6HHQNM9ESQVE0DM4s4%2525253D)|
|[1009500](https://dev.azure.com/dnceng/public/_build/results?buildId=1009500)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48691](https://github.com/dotnet/runtime/pull/48691)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48691-merge-51b703e772b04c7eb4/PayloadGroup0/console.78ad4d4f.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-16T09%2525253A40%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D7CQNyGGn0wz4O4M6LgkQODWdTVvfbNNlrufJNoWEAlQ%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48691-merge-51b703e772b04c7eb4/PayloadGroup0/05cf5059-548d-42e6-927e-4741f9415c26.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-16T09%2525253A40%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D7CQNyGGn0wz4O4M6LgkQODWdTVvfbNNlrufJNoWEAlQ%2525253D)|
|[1007749](https://dev.azure.com/dnceng/public/_build/results?buildId=1007749)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44905](https://github.com/dotnet/runtime/pull/44905)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44905-merge-c055e7b30e1b48d5bb/PayloadGroup0/console.19ae8d15.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-15T15%2525253A33%2525253A01Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DPgb4EaHfpFHDoPJZqOhYpO4rzcRcjOwOYmjwG0v6abc%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44905-merge-c055e7b30e1b48d5bb/PayloadGroup0/dc0c78b8-072c-41a3-92e5-ea5e20f80358.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-15T15%2525253A33%2525253A01Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DPgb4EaHfpFHDoPJZqOhYpO4rzcRcjOwOYmjwG0v6abc%2525253D)|
|[1007653](https://dev.azure.com/dnceng/public/_build/results?buildId=1007653)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48642](https://github.com/dotnet/runtime/pull/48642)|CoreCLR windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48642-merge-d9da56445007493fa4/PayloadGroup0/console.489a5032.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-15T13%2525253A28%2525253A14Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DEQ5g8B%2525252BGrI7CfjZjFUJB2f3QXEQ6vQgRg0d5m1a%2525252FrVY%2525253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48642-merge-d9da56445007493fa4/PayloadGroup0/fef6f2f4-2c95-4f8f-a60a-b9edbee2ec68.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-03-15T13%2525253A28%2525253A14Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DEQ5g8B%2525252BGrI7CfjZjFUJB2f3QXEQ6vQgRg0d5m1a%2525252FrVY%2525253D)|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|2|4|

<!-- runfo report end -->

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #45326 

cc: @dotnet/jit-contrib

### CODE REVIEW

File: src/coreclr/vm/eetwain.cpp [hunk 1]
```diff
@@ -5892,6 +5892,12 @@ bool EECodeManager::GetReturnAddressHijackInfo(GCInfoToken gcInfoToken, ReturnKi
 
     DecodeGCHdrInfo(gcInfoToken, 0, &info);
 
+    if (info.revPInvokeOffset != INVALID_REV_PINVOKE_OFFSET)
```
Comment (jkotas) [inline src/coreclr/vm/eetwain.cpp:5895]: Do we also need to check this in EH, like GetReversePInvokeFrameStackSlot
is checked on non-x86? It is possible that it is not needed, just mentioning it.

**Review by jkotas — APPROVED** [review]
Thank you!

File: src/coreclr/vm/eetwain.cpp (hunk 1 above)
Comment (jkoritzinsky) [reply src/coreclr/vm/eetwain.cpp:5895]: It's not needed in x86 Windows EH since we fully integrate with SEH already. However, it looks like Unix x86 needs it, so I'll update the relevant locations to use it.

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
Many tests on x86 failing with:
```
Assert failure(PID 1332 [0x00000534], Thread: 864 [0x0360]): Assertion failed 'header->revPInvokeOffset != INVALID_REV_PINVOKE_OFFSET' in 'System.Net.NameResolutionPal:GetAddressInfoExCallback(int,int,int)' during 'Emit GC+EH tables' (IL size 10)

    File: D:\workspace\_work\1\s\src\coreclr\jit\gcencode.cpp Line: 1631
```

**Comment by jkoritzinsky** [comment]
I think the sentinel we have for the "invalid offset" value can possibly be a valid value. I'll run through one of the CoreCLR tests that's failing tomorrow.

**Comment by trylek** [comment]
Beautiful, thank you!
