### PR TITLE
Check field's real type before we call getArrayOrStringLength

### LINKED ISSUE #77968: [libraries-pgo] Assert failure: Reached the "unreachable" in getArrayOrStringLength
Work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=74655&view=ms.vss-test-web.build-test-results-tab&runId=1537616&resultId=194524&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-482d4a39acdd47cea7/System.Text.RegularExpressions.Tests/1/console.e2964816.log?helixlogtype=result

```scala
Assert failure(PID 16183 [0x00003f37], Thread: 16712 [0x4148]): Reached the "unreachable": FAILED: <unreachable>
    File: /__w/1/s/src/coreclr/vm/jitinterface.cpp Line: 1747
    Image: /datadisks/disk1/work/B76F0A0C/p/dotnet
```

This is inside `getArrayOrStringLength`, cc @EgorBo

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/77968

I assumed that anything under `GT_ARR_LENGTH` is an array (or string). It turns out it may not be.

### CODE REVIEW

File: src/coreclr/jit/valuenum.cpp [hunk 1]
```diff
@@ -2106,14 +2106,18 @@ ValueNum ValueNumStore::VNForFunc(var_types typ, VNFunc func, ValueNum arg0VN)
...
+                        uint8_t              buffer[TARGET_POINTER_SIZE] = {0};
+                        if (m_pComp->info.compCompHnd->getReadonlyStaticFieldValue(field, buffer, TARGET_POINTER_SIZE,
+                                                                                   false))
                         {
-                            uint8_t buffer[TARGET_POINTER_SIZE] = {0};
-                            if (m_pComp->info.compCompHnd->getReadonlyStaticFieldValue(field, buffer,
-                                                                                       TARGET_POINTER_SIZE, false))
+                            // Now we need to make sure it's a real array or string under GT_ARR_LEN
+                            // it can be "((int[])obj).Length;" where "obj" is neither String nor Array.
+                            CORINFO_CLASS_HANDLE fldCls = m_pComp->info.compCompHnd->getStaticFieldCurrentClass(field);
```
Comment (jkotas) [inline src/coreclr/jit/valuenum.cpp:2118]: I think it would ok to leave this check for `getArrayOrStringLength`. It has to check for array vs. string anyway, and we are assuming that it can fail (return negative number) below.

Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp]: agreed, changed

File: src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.RyuJit.cs [hunk 2]
```diff
@@ -2303,7 +2303,7 @@ private int getArrayOrStringLength(CORINFO_OBJECT_STRUCT_* objHnd)
             {
                 FrozenStringNode frozenStr => frozenStr.Data.Length,
                 FrozenObjectNode frozenObj => frozenObj.GetArrayLength(),
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.RyuJit.cs:2305]:
```suggestion
                FrozenObjectNode frozenObj when frozenObj.ObjectType.IsArray => frozenObj.GetArrayLength(),
```

File: src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.RyuJit.cs [hunk 3]
```diff
@@ -2303,7 +2303,7 @@ private int getArrayOrStringLength(CORINFO_OBJECT_STRUCT_* objHnd)
...
-                _ => throw new NotImplementedException($"Unexpected object in getArrayOrStringLength: {obj}")
+                _ => -1;
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.RyuJit.cs:2306]:
```suggestion
                _ => -1
```

**Review by jakobbotsch — APPROVED** [review]

**Review by jkotas — APPROVED** [review]
