### PR TITLE
[mono][interpreter] Make nint and nuint work for interpreter simd intrinsics

### LINKED ISSUE #114088: PackedSimd fails to find interpreter intrinsic
```csharp
if (PackedSimd.IsSupported)
{
    Console.WriteLine("Packed SIMD is supported.");
    Vector128<nint> vector1 = Vector128<nint>.One;
    Vector128<nint> vector2 = Vector128<nint>.Zero;
    var vector3 = PackedSimd.Add(vector1, vector2);
    Console.WriteLine($"Vector3: {vector3}");
}
```

The lookup validation fails for MONO_TYPE_U and MONO_TYPE_I

Image

### PR DESCRIPTION
**Pull request by lewing**
PackedSimd is currently broken in the interpreter with nint and nuint types because of this, and Vector128 fails to find the intrinsics.  Additionally `Vector128<nuint>` is used in a potential hot path. https://github.com/dotnet/runtime/blob/4b16dce6097aa70e09bb82e27c5055421cf74ded/src/libraries/System.Private.CoreLib/src/System/Text/Unicode/Utf16Utility.Validation.cs#L293

fixes https://github.com/dotnet/runtime/issues/114088
Also fixes PackedSimd.Store*, and ConvertToDoubleLower interpreter intrinsics identified by the tests

### CODE REVIEW

**Comment by lewing** [comment]
More fixes on the way

**Comment by lewing** [comment]
Need to add a test case

**Comment by lewing** [comment]
I will backport the runtime abort fixes to net 9 manually.

**Review by steveisok — APPROVED** [review]

File: src/mono/mono/mini/interp/transform-simd.c [hunk 1]
```diff
@@ -563,6 +582,7 @@ emit_sri_vector128 (TransformData *td, MonoMethod *cmethod, MonoMethodSignature
 			else if (arg_size == 8) simd_intrins = INTERP_SIMD_INTRINSIC_V128_I8_CREATE_SCALAR;
 			break;
 		case SN_Equals:
+			atype = resolve_native_size (atype);
```
Comment (kg) [inline src/mono/mono/mini/interp/transform-simd.c:585]: why in these individual cases instead of up top?

Comment (lewing) [reply src/mono/mono/mini/interp/transform-simd.c:585]: If you look farther up in the function there are cases where the type is checked against the parameter type.  I just made a choice to be explicit about doing where it was uses rather than introducing a new variable there.
