### PR TITLE
JIT: fix pred list maintenance during fgUpdateFlowGraph

### LINKED ISSUE #56495: JIT: flow opts does an incorrect pred list update
Repro case is:
```C#
// Generated by Fuzzlyn v1.2 on 2021-07-07 08:13:57
// Seed: 11738605779775786426
// Reduced from 155.0 KiB to 0.5 KiB in 00:30:58
// Crashes the runtime
public class Program
{
    static bool s_1;
    public static void Main()
    {
        ulong vr1 = 0;
        for (int vr2 = 0; vr2 < 0; vr2++)
        {
            if (s_1)
            {
                try
                {
                }
                finally
                {
                    vr1 = vr1;
                }
            }
            else
            {
                if (s_1)
                {
                    bool vr3 = s_1;
                }
            }
        }
    }
}
```
and it leads to a jit assert
```
Assert failure(PID 20200 [0x00004ee8], Thread: 24136 [0x5e48]): Assertion failed 'i < BitSetTraits::GetSize(env)' 
   in 'Program:Main()' during 'Compute blocks reachability' (IL size 41)
```
See https://github.com/dotnet/runtime/pull/56184#issuecomment-888596878 and following comments for more details.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Handle case where a BBJ_COND block both falls through and branches to
another block, and we want to introduce a block to re-route the fall through.

Closes #56495.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

no spmi asm diffs.

**Review by BruceForstall — APPROVED** [review]

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/fgopt.cpp [hunk 1]
```diff
@@ -5624,8 +5624,10 @@ bool Compiler::fgUpdateFlowGraph(bool doTailDuplication)
                                 BasicBlock* const bFixup = fgNewBBafter(BBJ_ALWAYS, bDest, true);
                                 bFixup->inheritWeight(bDestNext);
                                 bFixup->bbJumpDest = bDestNext;
-                                fgReplacePred(bDestNext, bDest, bFixup);
+
+                                fgRemoveRefPred(bDestNext, bDest);
                                 fgAddRefPred(bFixup, bDest);
+                                fgAddRefPred(bDestNext, bFixup);
                             }
```
Comment (EgorBo) [inline src/coreclr/jit/fgopt.cpp:5631]: So ReplacePred should always be avoided and be replaced with a pair of RemoveRefPred + AddRefPred ?

Comment (AndyAyersMS) [reply src/coreclr/jit/fgopt.cpp:5631]: Not necessarily, sometimes you want to replace all the references.

I find editing flow in the jit to be fairly complex in general, especially dealing with the fall through behavior. I have ideas on how to simplify this but not sure when/if we'll get to them.
