### PR TITLE
Fix deadlock in TestEventListener and re-enable ArrayPool DiagnosticEvent tests

### LINKED ISSUE #42899: System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentBufferFiresRentedDiagnosticEvent failure
The test failed in CI on my PR (with change unrelated to the issue):
```
    System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentBufferFiresRentedDiagnosticEvent [FAIL]
      Half-way through waiting for remote process.
      Timed out at 9/30/2020 1:52:32 AM after 60000ms waiting for remote process.
      	Process ID: 23479
      	Handle: 904
      	Name: dotnet
      	MainModule: /home/helixbot/work/A64809A4/p/dotnet
      	StartTime: 9/30/2020 1:51:32 AM
      	TotalProcessorTime: 00:00:00.0100000
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(224,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(57,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs(44,0): at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Action action, Boolean trim)
        /_/src/libraries/System.Buffers/tests/ArrayPool/UnitTests.cs(404,0): at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentBufferFiresRentedDiagnosticEvent()
```
https://dev.azure.com/dnceng/public/_build/results?buildId=836124&view=ms.vss-test-web.build-test-results-tab&runId=26640246&resultId=172262&paneView=history
<!-- runfo report start -->
Runfo Tracking Issue: [system.buffers.arraypool.tests.arraypoolunittests.rentbufferfiresrenteddiagnosticevent](https://runfo.azurewebsites.net/tracking/issue/90)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[903664](https://dev.azure.com/dnceng/public/_build/results?buildId=903664)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-ericstj-removeperfc9ac1195257484277a8/System.Buffers.Tests/console.8ff274a4.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-21T00%2525253A16%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DYzzxtRmSQsnWutSW5rIDidGLT%2525252FfOF8Bts8AzXPWdvp0%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-ericstj-removeperfc9ac1195257484277a8/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-21T00%2525253A16%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DYzzxtRmSQsnWutSW5rIDidGLT%2525252FfOF8Bts8AzXPWdvp0%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-ericstj-removeperfc9ac1195257484277a8/System.Buffers.Tests/35856f78-ee3a-4e01-91d4-e62992e01eaf.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-21T00%2525253A16%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DYzzxtRmSQsnWutSW5rIDidGLT%2525252FfOF8Bts8AzXPWdvp0%2525253D)|
|[901897](https://dev.azure.com/dnceng/public/_build/results?buildId=901897)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45288](https://github.com/dotnet/runtime/pull/45288)|net6.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open|||||
|[901284](https://dev.azure.com/dnceng/public/_build/results?buildId=901284)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|||||
|[901142](https://dev.azure.com/dnceng/public/_build/results?buildId=901142)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59|||||
|[899972](https://dev.azure.com/dnceng/public/_build/results?buildId=899972)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59|||||
|[899820](https://dev.azure.com/dnceng/public/_build/results?buildId=899820)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|||||
|[899354](https://dev.azure.com/dnceng/public/_build/results?buildId=899354)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59|||||
|[898522](https://dev.azure.com/dnceng/public/_build/results?buildId=898522)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-5e519d792b9c481baf/System.Buffers.Tests/console.ba31e9d2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-14T20%2525253A27%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DbCQLTqOC9fLuCTU2E909XHLj81iR%2525252BEDDcbL7CJ4fvNQ%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-5e519d792b9c481baf/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-14T20%2525253A27%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DbCQLTqOC9fLuCTU2E909XHLj81iR%2525252BEDDcbL7CJ4fvNQ%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-5e519d792b9c481baf/System.Buffers.Tests/ac2735d7-85d9-4266-9b65-fb15c4a81dd9.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-14T20%2525253A27%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DbCQLTqOC9fLuCTU2E909XHLj81iR%2525252BEDDcbL7CJ4fvNQ%2525253D)|
|[898011](https://dev.azure.com/dnceng/public/_build/results?buildId=898011)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45127](https://github.com/dotnet/runtime/pull/45127)|net6.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45127-merge-db8c1f3e3adc45e380/System.Buffers.Tests/console.a23ebb8a.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-14T13%2525253A13%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DRiZlCBm7fKybYlgEB1Jo3UvHulZKuSuOXkxoaN7Y2Lk%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45127-merge-db8c1f3e3adc45e380/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-14T13%2525253A13%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DRiZlCBm7fKybYlgEB1Jo3UvHulZKuSuOXkxoaN7Y2Lk%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45127-merge-db8c1f3e3adc45e380/System.Buffers.Tests/55f514a8-783f-4443-a6a0-92179f140b64.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-14T13%2525253A13%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DRiZlCBm7fKybYlgEB1Jo3UvHulZKuSuOXkxoaN7Y2Lk%2525253D)|
|[896701](https://dev.azure.com/dnceng/public/_build/results?buildId=896701)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-de82662d8fd545e8b5/System.Buffers.Tests/console.239c1e4a.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-13T18%2525253A10%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D9Rx4BQdKc6I6n3Hj2VbbkpTC2qt4SE%2525252BMZVDTX1c0rgI%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-de82662d8fd545e8b5/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-13T18%2525253A10%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D9Rx4BQdKc6I6n3Hj2VbbkpTC2qt4SE%2525252BMZVDTX1c0rgI%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-de82662d8fd545e8b5/System.Buffers.Tests/3d60c25d-54a5-4695-813d-597cc372cd60.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-13T18%2525253A10%2525253A00Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D9Rx4BQdKc6I6n3Hj2VbbkpTC2qt4SE%2525252BMZVDTX1c0rgI%2525253D)|
|[896155](https://dev.azure.com/dnceng/public/_build/results?buildId=896155)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45105](https://github.com/dotnet/runtime/pull/45105)|net6.0-OSX-Debug-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45105-merge-2e594ade13f546119d/System.Buffers.Tests/console.e844cedc.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-13T07%2525253A02%2525253A52Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5K3Rx5OGOiRLMtU6XOx%2525252Bb70DgFhIVDn%2525252F0dxea01KoaQ%2525253D)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45105-merge-2e594ade13f546119d/System.Buffers.Tests/core.2094?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-13T07%2525253A02%2525253A52Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5K3Rx5OGOiRLMtU6XOx%2525252Bb70DgFhIVDn%2525252F0dxea01KoaQ%2525253D)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45105-merge-2e594ade13f546119d/System.Buffers.Tests/8e944a79-1d35-4524-b186-c6f0b434dffa.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-13T07%2525253A02%2525253A52Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5K3Rx5OGOiRLMtU6XOx%2525252Bb70DgFhIVDn%2525252F0dxea01KoaQ%2525253D)|
|[895893](https://dev.azure.com/dnceng/public/_build/results?buildId=895893)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-14377ea4e8e6475988/System.Buffers.Tests/console.9dba6e5c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-12T15%2525253A57%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DAX8gby0bxuk5JgEM2w1uxaGPzLW%2525252BOURAAXQJUTKalxQ%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-14377ea4e8e6475988/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-12T15%2525253A57%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DAX8gby0bxuk5JgEM2w1uxaGPzLW%2525252BOURAAXQJUTKalxQ%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-14377ea4e8e6475988/System.Buffers.Tests/9edd0273-bab5-47f8-b888-c4fd8bec5ca7.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-12T15%2525253A57%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DAX8gby0bxuk5JgEM2w1uxaGPzLW%2525252BOURAAXQJUTKalxQ%2525253D)|
|[895732](https://dev.azure.com/dnceng/public/_build/results?buildId=895732)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-1c5241abdc864dd0aa/System.Buffers.Tests/console.4e911f90.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-12T03%2525253A25%2525253A34Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DE52EpICz%2525252BlwPHB%2525252BMk93al4iYrCYTxq9KelXs%2525252BMtIXBY%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-1c5241abdc864dd0aa/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-12T03%2525253A25%2525253A34Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DE52EpICz%2525252BlwPHB%2525252BMk93al4iYrCYTxq9KelXs%2525252BMtIXBY%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-1c5241abdc864dd0aa/System.Buffers.Tests/8871cf5e-009b-4633-a1e1-0a4be6f1324c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-12T03%2525253A25%2525253A34Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DE52EpICz%2525252BlwPHB%2525252BMk93al4iYrCYTxq9KelXs%2525252BMtIXBY%2525253D)|
|[895551](https://dev.azure.com/dnceng/public/_build/results?buildId=895551)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45052](https://github.com/dotnet/runtime/pull/45052)|net6.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45052-merge-9a03d37d0202425795/System.Buffers.Tests/console.7446c6ea.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-11T18%2525253A09%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D2AwAuW%2525252FwC96N1SInMhlDsMVJ6vkUP%2525252BpRClysA%2525252By9JGk%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45052-merge-9a03d37d0202425795/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-11T18%2525253A09%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D2AwAuW%2525252FwC96N1SInMhlDsMVJ6vkUP%2525252BpRClysA%2525252By9JGk%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45052-merge-9a03d37d0202425795/System.Buffers.Tests/fac08ba9-a07f-4d78-bd74-9fe06e1657b2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-11T18%2525253A09%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D2AwAuW%2525252FwC96N1SInMhlDsMVJ6vkUP%2525252BpRClysA%2525252By9JGk%2525253D)|
|[895413](https://dev.azure.com/dnceng/public/_build/results?buildId=895413)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-3ef9b02dcd5449caab/System.Buffers.Tests/console.ee24abbc.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-11T09%2525253A18%2525253A28Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DFihMwzHo9HXPRq1V3NF5WHzPZqasCZzVdPazAL6aMck%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-3ef9b02dcd5449caab/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-11T09%2525253A18%2525253A28Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DFihMwzHo9HXPRq1V3NF5WHzPZqasCZzVdPazAL6aMck%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-3ef9b02dcd5449caab/System.Buffers.Tests/84d2b36d-4872-41ce-a0e5-a56d1224d36d.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-11T09%2525253A18%2525253A28Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DFihMwzHo9HXPRq1V3NF5WHzPZqasCZzVdPazAL6aMck%2525253D)|
|[895135](https://dev.azure.com/dnceng/public/_build/results?buildId=895135)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-729250c0b6714a3f88/System.Buffers.Tests/console.57c7a0ec.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-11T01%2525253A45%2525253A49Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DAj9oWoLtqLM3OfY1hyPD1W2AYJYL8894Hb%2525252B2VCI7p2k%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-729250c0b6714a3f88/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-11T01%2525253A45%2525253A49Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DAj9oWoLtqLM3OfY1hyPD1W2AYJYL8894Hb%2525252B2VCI7p2k%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-729250c0b6714a3f88/System.Buffers.Tests/e4dabc05-ef7e-443a-af5a-f456e1435287.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-11T01%2525253A45%2525253A49Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DAj9oWoLtqLM3OfY1hyPD1W2AYJYL8894Hb%2525252B2VCI7p2k%2525253D)|
|[892085](https://dev.azure.com/dnceng/public/_build/results?buildId=892085)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-25c69e4ac10d487399/System.Buffers.Tests/console.c0c0f900.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-09T08%2525253A13%2525253A19Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DtXClVv%2525252FDTu4F1bmA%2525252BwehgeWr%2525252BrQFd99PJbM6xn6ecKA%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-25c69e4ac10d487399/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-09T08%2525253A13%2525253A19Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DtXClVv%2525252FDTu4F1bmA%2525252BwehgeWr%2525252BrQFd99PJbM6xn6ecKA%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-25c69e4ac10d487399/System.Buffers.Tests/a33beeae-9c25-4244-8980-c2e62d0e380a.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-09T08%2525253A13%2525253A19Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DtXClVv%2525252FDTu4F1bmA%2525252BwehgeWr%2525252BrQFd99PJbM6xn6ecKA%2525253D)|
|[891305](https://dev.azure.com/dnceng/public/_build/results?buildId=891305)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-0d44c8d06a8c4c54bf/System.Buffers.Tests/console.0c83efc3.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-08T21%2525253A29%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DpZ%2525252FEAxCBNbvVlhqGL43x5d%2525252B91JBP6AlvxszSaEnABlE%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-0d44c8d06a8c4c54bf/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-08T21%2525253A29%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DpZ%2525252FEAxCBNbvVlhqGL43x5d%2525252B91JBP6AlvxszSaEnABlE%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-0d44c8d06a8c4c54bf/System.Buffers.Tests/fc61742a-a922-4606-b43f-bfe1e0cc41cd.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-08T21%2525253A29%2525253A24Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DpZ%2525252FEAxCBNbvVlhqGL43x5d%2525252B91JBP6AlvxszSaEnABlE%2525253D)|
|[890330](https://dev.azure.com/dnceng/public/_build/results?buildId=890330)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44843](https://github.com/dotnet/runtime/pull/44843)|net6.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44843-merge-57e0c4db60dd4bc196/System.Buffers.Tests/console.29098c59.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-08T05%2525253A02%2525253A32Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DEP3F7Tmbpm29Y6Vy%2525252BIrXZDVrk4TZCYWttEnYmiGHkrs%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44843-merge-57e0c4db60dd4bc196/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-08T05%2525253A02%2525253A32Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DEP3F7Tmbpm29Y6Vy%2525252BIrXZDVrk4TZCYWttEnYmiGHkrs%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44843-merge-57e0c4db60dd4bc196/System.Buffers.Tests/4a51c981-ffcf-45f8-ae96-65b69689b223.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-08T05%2525253A02%2525253A32Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DEP3F7Tmbpm29Y6Vy%2525252BIrXZDVrk4TZCYWttEnYmiGHkrs%2525253D)|
|[889777](https://dev.azure.com/dnceng/public/_build/results?buildId=889777)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44836](https://github.com/dotnet/runtime/pull/44836)|net6.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44836-merge-db31da3d00784e80b9/System.Buffers.Tests/console.792072a6.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-07T23%2525253A08%2525253A36Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DWYnaZ1SRDxtKe8OcFyuqBNaZdcKSrmHs2T5EDrAZa98%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44836-merge-db31da3d00784e80b9/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-07T23%2525253A08%2525253A36Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DWYnaZ1SRDxtKe8OcFyuqBNaZdcKSrmHs2T5EDrAZa98%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44836-merge-db31da3d00784e80b9/System.Buffers.Tests/0c07d0a7-8cd4-4140-be86-eaff6673ba16.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-07T23%2525253A08%2525253A36Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DWYnaZ1SRDxtKe8OcFyuqBNaZdcKSrmHs2T5EDrAZa98%2525253D)|
|[887869](https://dev.azure.com/dnceng/public/_build/results?buildId=887869)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44750](https://github.com/dotnet/runtime/pull/44750)|net6.0-OSX-Debug-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44750-merge-1341a2d0b6134d5bae/System.Buffers.Tests/console.05f7dd98.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-06T19%2525253A51%2525253A40Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DBGyUFPsuRk0UlNk4mT9xjTa1hr%2525252BQ7jvEK9OGqvr%2525252FXVg%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44750-merge-1341a2d0b6134d5bae/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-06T19%2525253A51%2525253A40Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DBGyUFPsuRk0UlNk4mT9xjTa1hr%2525252BQ7jvEK9OGqvr%2525252FXVg%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44750-merge-1341a2d0b6134d5bae/System.Buffers.Tests/413f04be-67b2-49a0-86fe-d5962267a66d.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-06T19%2525253A51%2525253A40Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DBGyUFPsuRk0UlNk4mT9xjTa1hr%2525252BQ7jvEK9OGqvr%2525252FXVg%2525253D)|
|[886432](https://dev.azure.com/dnceng/public/_build/results?buildId=886432)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a7fcc6613fe24661a6/System.Buffers.Tests/console.ce3e866d.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-04T02%2525253A37%2525253A27Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D%2525252BJOt8GcwgOL91G1UIr7oenXJBydbon4zVdOlgV7ZBA4%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a7fcc6613fe24661a6/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-04T02%2525253A37%2525253A27Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D%2525252BJOt8GcwgOL91G1UIr7oenXJBydbon4zVdOlgV7ZBA4%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a7fcc6613fe24661a6/System.Buffers.Tests/50f6961c-a249-4411-8581-467f6c9e8f25.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-04T02%2525253A37%2525253A27Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D%2525252BJOt8GcwgOL91G1UIr7oenXJBydbon4zVdOlgV7ZBA4%2525253D)|
|[886432](https://dev.azure.com/dnceng/public/_build/results?buildId=886432)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a642d86822cf4b0697/System.Buffers.Tests/console.b72e6c8b.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-04T02%2525253A59%2525253A25Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DhIo%2525252Bkb5427yBhgc1Pw4Wf7JM%2525252FklE%2525252B%2525252B%2525252BeMbHT%2525252F8tPdxI%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a642d86822cf4b0697/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-04T02%2525253A59%2525253A25Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DhIo%2525252Bkb5427yBhgc1Pw4Wf7JM%2525252FklE%2525252B%2525252B%2525252BeMbHT%2525252F8tPdxI%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a642d86822cf4b0697/System.Buffers.Tests/b92664ab-6236-4a00-aabf-146b65d962a7.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-04T02%2525253A59%2525253A25Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DhIo%2525252Bkb5427yBhgc1Pw4Wf7JM%2525252FklE%2525252B%2525252B%2525252BeMbHT%2525252F8tPdxI%2525253D)|
|[885670](https://dev.azure.com/dnceng/public/_build/results?buildId=885670)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-7512c145acae458097/System.Buffers.Tests/console.baade9d2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-03T18%2525253A24%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DbiDySOpZ5Lhen%2525252B0o4WCP4UWLKeC4ileOtWD801EApVY%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-7512c145acae458097/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-03T18%2525253A24%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DbiDySOpZ5Lhen%2525252B0o4WCP4UWLKeC4ileOtWD801EApVY%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-7512c145acae458097/System.Buffers.Tests/e36a34e3-9f34-4d2c-9693-363f126bdcfb.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-03T18%2525253A24%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DbiDySOpZ5Lhen%2525252B0o4WCP4UWLKeC4ileOtWD801EApVY%2525253D)|
|[885104](https://dev.azure.com/dnceng/public/_build/results?buildId=885104)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44629](https://github.com/dotnet/runtime/pull/44629)|net6.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44629-merge-56753e0514f6428986/System.Buffers.Tests/console.866791ef.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-03T03%2525253A43%2525253A43Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dfc23dT68%2525252FDaAWGq1U0GRIhtuNViAQSccfgmkqWxp1WQ%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44629-merge-56753e0514f6428986/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-03T03%2525253A43%2525253A43Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dfc23dT68%2525252FDaAWGq1U0GRIhtuNViAQSccfgmkqWxp1WQ%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44629-merge-56753e0514f6428986/System.Buffers.Tests/6aabe247-848b-476b-8f32-34bfffad5d24.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-03T03%2525253A43%2525253A43Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dfc23dT68%2525252FDaAWGq1U0GRIhtuNViAQSccfgmkqWxp1WQ%2525253D)|
|[883833](https://dev.azure.com/dnceng/public/_build/results?buildId=883833)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-012ea0cbcc104bd684/System.Buffers.Tests/console.3a7e05a4.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-02T07%2525253A44%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5xOvBLIp4reu%2525252Fk%2525252F42OiTjMnfKoJtxzgV6UBjOGhpnxc%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-012ea0cbcc104bd684/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-02T07%2525253A44%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5xOvBLIp4reu%2525252Fk%2525252F42OiTjMnfKoJtxzgV6UBjOGhpnxc%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-012ea0cbcc104bd684/System.Buffers.Tests/6f62a9dd-416f-4201-8eb0-fdc8990dd79f.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-02T07%2525253A44%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5xOvBLIp4reu%2525252Fk%2525252F42OiTjMnfKoJtxzgV6UBjOGhpnxc%2525253D)|
|[883101](https://dev.azure.com/dnceng/public/_build/results?buildId=883101)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-135b6b3d9bff466ca5/System.Buffers.Tests/console.bb310f72.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T21%2525253A18%2525253A31Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Db4Mr2THWumuv7iB90Y4UujK3Q4teCDW1CNHPM4vjakI%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-135b6b3d9bff466ca5/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T21%2525253A18%2525253A31Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Db4Mr2THWumuv7iB90Y4UujK3Q4teCDW1CNHPM4vjakI%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-135b6b3d9bff466ca5/System.Buffers.Tests/24c95103-066b-4771-b419-bfbdf5603d9c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T21%2525253A18%2525253A31Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Db4Mr2THWumuv7iB90Y4UujK3Q4teCDW1CNHPM4vjakI%2525253D)|
|[882752](https://dev.azure.com/dnceng/public/_build/results?buildId=882752)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-26500baef9bc47809a/System.Buffers.Tests/console.dc902f6d.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T18%2525253A45%2525253A44Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DJ5PwjHpQWXechu5UqE5mEGvefYuLQ1zwR0vGeXXI7%2525252FY%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-26500baef9bc47809a/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T18%2525253A45%2525253A44Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DJ5PwjHpQWXechu5UqE5mEGvefYuLQ1zwR0vGeXXI7%2525252FY%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-26500baef9bc47809a/System.Buffers.Tests/b0c9e0da-3636-4e55-af1d-c99d1a59e2a2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T18%2525253A45%2525253A44Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DJ5PwjHpQWXechu5UqE5mEGvefYuLQ1zwR0vGeXXI7%2525252FY%2525253D)|
|[882733](https://dev.azure.com/dnceng/public/_build/results?buildId=882733)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44532](https://github.com/dotnet/runtime/pull/44532)|net6.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44532-merge-5d7b0011bcda4b3487/System.Buffers.Tests/console.ae6b5a15.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T18%2525253A01%2525253A46Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DydaUqafrAjZ5UcFh3gHfcn%2525252FOYr4czwOxNcAWZAyjbw0%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44532-merge-5d7b0011bcda4b3487/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T18%2525253A01%2525253A46Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DydaUqafrAjZ5UcFh3gHfcn%2525252FOYr4czwOxNcAWZAyjbw0%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44532-merge-5d7b0011bcda4b3487/System.Buffers.Tests/9878985f-8c54-47d2-a164-40877286dc44.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T18%2525253A01%2525253A46Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DydaUqafrAjZ5UcFh3gHfcn%2525252FOYr4czwOxNcAWZAyjbw0%2525253D)|
|[882477](https://dev.azure.com/dnceng/public/_build/results?buildId=882477)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-7ccdbaf519eb48fe9b/System.Buffers.Tests/console.e515b34a.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T12%2525253A41%2525253A20Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Drrf%2525252BD8wacSTyWT0RttRchujmf1OJJIgawInHYQH%2525252B%2525252BmQ%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-7ccdbaf519eb48fe9b/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T12%2525253A41%2525253A20Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Drrf%2525252BD8wacSTyWT0RttRchujmf1OJJIgawInHYQH%2525252B%2525252BmQ%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-7ccdbaf519eb48fe9b/System.Buffers.Tests/e53d7544-6720-4664-b625-d68671cc2605.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-12-01T12%2525253A41%2525253A20Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Drrf%2525252BD8wacSTyWT0RttRchujmf1OJJIgawInHYQH%2525252B%2525252BmQ%2525253D)|
|[880481](https://dev.azure.com/dnceng/public/_build/results?buildId=880481)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-b4dc54639e254f7d85/System.Buffers.Tests/console.5a1d61b1.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-30T03%2525253A40%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dn%2525252FvNleuyCs3o%2525252BKIDXLxlQvjNv95X3rzvPDXFOwp6S6Q%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-b4dc54639e254f7d85/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-30T03%2525253A40%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dn%2525252FvNleuyCs3o%2525252BKIDXLxlQvjNv95X3rzvPDXFOwp6S6Q%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-b4dc54639e254f7d85/System.Buffers.Tests/aad9fc8d-2c61-45f8-bb78-81742e711014.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-30T03%2525253A40%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dn%2525252FvNleuyCs3o%2525252BKIDXLxlQvjNv95X3rzvPDXFOwp6S6Q%2525253D)|
|[877610](https://dev.azure.com/dnceng/public/_build/results?buildId=877610)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-bfcd90a-20200127194925|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-1678e752e5954f3684/System.Buffers.Tests/console.27fde665.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T05%2525253A23%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DRlAmT71y7xzFYEy7AfIdLgxREDL93Gh5WRuonOXkEBk%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-1678e752e5954f3684/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T05%2525253A23%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DRlAmT71y7xzFYEy7AfIdLgxREDL93Gh5WRuonOXkEBk%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-1678e752e5954f3684/System.Buffers.Tests/06c280f0-782a-4646-87b5-99f6e4e975d2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T05%2525253A23%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DRlAmT71y7xzFYEy7AfIdLgxREDL93Gh5WRuonOXkEBk%2525253D)|
|[877106](https://dev.azure.com/dnceng/public/_build/results?buildId=877106)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-80d58caf4b6b4ed5a3/System.Buffers.Tests/console.43dc643a.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-25T21%2525253A55%2525253A14Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DDJAaGzQFrtk%2525252FEaHTM3Lzp88rLih5EMzeL9Y7rX7CKCU%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-80d58caf4b6b4ed5a3/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-25T21%2525253A55%2525253A14Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DDJAaGzQFrtk%2525252FEaHTM3Lzp88rLih5EMzeL9Y7rX7CKCU%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-80d58caf4b6b4ed5a3/System.Buffers.Tests/89528661-e60e-40d7-a86d-0c220d1c31ec.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-25T21%2525253A55%2525253A14Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DDJAaGzQFrtk%2525252FEaHTM3Lzp88rLih5EMzeL9Y7rX7CKCU%2525253D)|
|[875555](https://dev.azure.com/dnceng/public/_build/results?buildId=875555)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-565f13b7dcea417484/System.Buffers.Tests/console.836d24c9.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T16%2525253A47%2525253A37Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D6II3PdGZqVeQ31BxbXtkKMA8tL8MBh%2525252FfOQPtxJQYdJw%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-565f13b7dcea417484/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T16%2525253A47%2525253A37Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D6II3PdGZqVeQ31BxbXtkKMA8tL8MBh%2525252FfOQPtxJQYdJw%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-565f13b7dcea417484/System.Buffers.Tests/13bcf019-e150-4c9b-8976-6d5245ce9151.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T16%2525253A47%2525253A37Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D6II3PdGZqVeQ31BxbXtkKMA8tL8MBh%2525252FfOQPtxJQYdJw%2525253D)|
|[874089](https://dev.azure.com/dnceng/public/_build/results?buildId=874089)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-351e4891265d4c8f97/System.Buffers.Tests/console.2a6052c6.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T13%2525253A37%2525253A37Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DZ1Bsvae5Ovmgw3HQc1EjolTuxdyC1V7HbhC6JuM%2525252BV8I%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-351e4891265d4c8f97/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T13%2525253A37%2525253A37Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DZ1Bsvae5Ovmgw3HQc1EjolTuxdyC1V7HbhC6JuM%2525252BV8I%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-351e4891265d4c8f97/System.Buffers.Tests/09b5aa68-3374-4d44-a33f-b52c9d55dd1f.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T13%2525253A37%2525253A37Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DZ1Bsvae5Ovmgw3HQc1EjolTuxdyC1V7HbhC6JuM%2525252BV8I%2525253D)|
|[873691](https://dev.azure.com/dnceng/public/_build/results?buildId=873691)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-f8fb3f511f6d4a4194/System.Buffers.Tests/console.b112f8eb.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T22%2525253A49%2525253A53Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DrvLpo7VHvk4eJg%2525252FfzjmKUzC%2525252BUS5pnaStnt2ESrJJyTk%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-f8fb3f511f6d4a4194/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T22%2525253A49%2525253A53Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DrvLpo7VHvk4eJg%2525252FfzjmKUzC%2525252BUS5pnaStnt2ESrJJyTk%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-f8fb3f511f6d4a4194/System.Buffers.Tests/cb8ce9b7-ef4d-4e22-8210-3f233ea3caeb.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T22%2525253A49%2525253A53Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DrvLpo7VHvk4eJg%2525252FfzjmKUzC%2525252BUS5pnaStnt2ESrJJyTk%2525253D)|
|[872718](https://dev.azure.com/dnceng/public/_build/results?buildId=872718)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a882f750c0be45429d/System.Buffers.Tests/console.67c49171.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-21T23%2525253A47%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D9M8pSbL%2525252BUUkp5yclmrRFXj7LVRA4DWhhtHRJuDFO0BE%2525253D)||[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a882f750c0be45429d/System.Buffers.Tests/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-21T23%2525253A47%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D9M8pSbL%2525252BUUkp5yclmrRFXj7LVRA4DWhhtHRJuDFO0BE%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a882f750c0be45429d/System.Buffers.Tests/543e59e3-7a82-41cf-80b7-295c1d5cd68c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-21T23%2525253A47%2525253A21Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D9M8pSbL%2525252BUUkp5yclmrRFXj7LVRA4DWhhtHRJuDFO0BE%2525253D)|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|6|35|

<!-- runfo report end -->

### PR DESCRIPTION
**Pull request by sywhang**
Fix #42899. 

TestEventListener has a deadlock in its implementation where it tries to lock the `_eventSourceList` and call `EnableEventSource` which can try to take the EventListener lock, while the overriden OnEventSourceCreated method tries to grab that same lock (`_eventSourceList`) while holding the EventListener lock. 

The fix is simple - calling `EnableEventSource` doesn't need to be inside the `_eventSourceList` lock.

### CODE REVIEW

File: src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs [hunk 1]
```diff
@@ -61,26 +62,32 @@ private void AddSource(string name, Guid? guid, EventLevel level, EventKeywords
                 {
                     if (name == source.Name || guid == source.Guid)
                     {
-                        EnableEventSource(source, level, keywords);
+                        sourceToEnable = source;
+                        break;
                     }
                 }
             }
+            if (sourceToEnable != null)
```
Comment (stephentoub) [inline src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:70]: Nit:
```suggestion

            if (sourceToEnable != null)
```

File: src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs [hunk 2]
```diff
@@ -61,26 +62,32 @@ private void AddSource(string name, Guid? guid, EventLevel level, EventKeywords
...
+                EnableEventSource(sourceToEnable, level, keywords);
+            }
         }
 
         public void AddActivityTracking() =>
             AddSource("System.Threading.Tasks.TplEventSource", EventLevel.Informational, (EventKeywords)0x80 /* TasksFlowActivityIds */);
 
         protected override void OnEventSourceCreated(EventSource eventSource)
         {
+            var shouldEnable = false;
```
Comment (stephentoub) [inline src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:81]:
```suggestion
            bool shouldEnable = false;
```

File: src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs [hunk 3]
```diff
@@ -61,26 +62,32 @@ private void AddSource(string name, Guid? guid, EventLevel level, EventKeywords
...
                 _eventSourceList.Add(eventSource);
-
-                if (_names.TryGetValue(eventSource.Name, out Settings settings) ||
-                    _guids.TryGetValue(eventSource.Guid, out settings))
-                {
-                    EnableEventSource(eventSource, settings.Level, settings.Keywords);
-                }
+                shouldEnable = _names.TryGetValue(eventSource.Name, out settings) || _guids.TryGetValue(eventSource.Guid, out settings);
+            }
+            if (shouldEnable)
```
Comment (stephentoub) [inline src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:88]:
```suggestion

            if (shouldEnable)
```

**Review by stephentoub — APPROVED** [review]
Thanks for fixing!

**Comment by sywhang** [comment]
CI failures are from #43249 and #44173.
