### PR TITLE
Fix RuntimeTypeHandle.IsComObject check for __ComObject type

### LINKED ISSUE #57107: Create COM objects on PowerShell gives an error `Constructor on type 'System.__ComObject' not found.`
### Description

On a PowerShell build with .NET 6 Preview 7, when a new instance of a COM object is done, we get an error: `Constructor on type 'System.__ComObject' not found.` which is `System.MissingMethodException`

Gist for sample code to repro the error:

https://gist.github.com/adityapatwardhan/954af5c2d894d889e1465c614ecf7e1a

### Configuration

.NET 6 Preview 7 SDK on Windows 10 x64.

### Regression?

Yes, from .NET 6 Preview 6

### Other information

Repro for the issue is on PowerShell built against .NET 6 Preview 7 SDK.

PS C:\> $fileSystem = New-Object -ComObject scripting.filesystemobject
New-Object: Constructor on type 'System.__ComObject' not found.
PS C:\> Get-Error

Exception             :
    Type       : System.MissingMethodException
    Message    : Constructor on type 'System.__ComObject' not found.
    TargetSite :
        Name          : CreateInstanceImpl
        DeclaringType : System.RuntimeType, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Source     : System.Private.CoreLib
    HResult    : -2146233069
    StackTrace :
   **at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) in System.Private.CoreLib.dll:token 0x60006c6+0x173
   at System.Activator.CreateInstance(Type type, Object[] args) in System.Private.CoreLib.dll:token 0x60009e0+0x0
   at Microsoft.PowerShell.Commands.NewObjectCommand.SafeCreateInstance(Type t, Object[] args) in D:\PSGit\PowerShell\src\Microsoft.PowerShell.Commands.Utility\commands\utility\New-Object.cs:line 359
CategoryInfo          : InvalidOperation: (:) [New-Object], MissingMethodException
FullyQualifiedErrorId : NoPublicCtorMatch,Microsoft.PowerShell.Commands.NewObjectCommand**
InvocationInfo        :
    MyCommand        : New-Object
    ScriptLineNumber : 1
    OffsetInLine     : 15
    HistoryId        : 9
    Line             : $fileSystem = New-Object -ComObject scripting.filesystemobject
    PositionMessage  : At line:1 char:15
                       + $fileSystem = New-Object -ComObject scripting.filesystemobject
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-Object
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

### PR DESCRIPTION
**Pull request by elinor-fung**
Fixes #57107

cc @AaronRobinsonMSFT @jkoritzinsky

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

File: src/tests/Interop/COM/NETClients/ConsumeNETServer/Program.cs [hunk 1]
```diff
@@ -29,6 +29,23 @@ static void Validate_Activation()
...
+        static void Validate_Activation_CreateInstance()
+        {
+            Console.WriteLine($"{nameof(Validate_Activation_CreateInstance)}...");
+
+            Type t = Type.GetTypeFromCLSID(Guid.Parse(Guids.ConsumeNETServerTesting));
+            Assert.IsTrue(t.IsCOMObject);
+
+            // Use the overload that takes constructor arguments. This tests the path where the runtime searches for the
+            // constructor to use (which has some special-casing for COM) instead of just always using the default.
+            object obj = Activator.CreateInstance(t, Array.Empty<object>());
```
Comment (AaronRobinsonMSFT) [inline src/tests/Interop/COM/NETClients/ConsumeNETServer/Program.cs:41]: Should we also use the `CreateInstance` without the args overload?

Comment (elinor-fung) [reply src/tests/Interop/COM/NETClients/ConsumeNETServer/Program.cs:41]: I just did this overload since all the COM + dynamic tests go through `Activator.CreateInstance(Type type)`. I can add it explicitly here too.

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs [hunk 2]
```diff
@@ -463,8 +463,9 @@ internal RuntimeMethodHandleInternal GetInterfaceMethodImplementation(RuntimeTyp
         internal static bool IsComObject(RuntimeType type, bool isGenericCOM)
         {
 #if FEATURE_COMINTEROP
+            // We need to check the type handle values - not the instances - to determine if the runtime type is a ComOjbect.
```
[the remark this answers is not in the document]
Comment (elinor-fung) [reply src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs]: New instances are created for different COM classes (so that COM objects of different CLSIDs have different types. For example, if you have:
```c#
Type t1 = Type.GetTypeFromCLSID(<clsid>);
Type t2 = Type.GetTypeFromCLSID(<clsid>);
Type t3 = Type.GetTypeFromCLSID(<different_clsid>);
```
They would be `__ComObject`, but `t1` and `t3` would be different instances such that `t1 == t2` but `t1 != t3`.
