### PR TITLE
Use FLS detach callback as a thread termination notification. Another try.

### LINKED ISSUE #110350: Process not responsive dump indicates garbage collection
### Description

After upgrading to .net 9, we have random processes, which just freeze, becoming completely unresponsive
Process are run as windows services on windows VM

I have a dump file, which I could send to you
I would just rather not make that public as it probably has passwords within

Analyzing the dump indicates a possible problem in the garbage collector

0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 1484

    Key  : Analysis.Elapsed.mSec
    Value: 5300

    Key  : Analysis.IO.Other.Mb
    Value: 0

    Key  : Analysis.IO.Read.Mb
    Value: 1

    Key  : Analysis.IO.Write.Mb
    Value: 1

    Key  : Analysis.Init.CPU.mSec
    Value: 781

    Key  : Analysis.Init.Elapsed.mSec
    Value: 120611

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 223

    Key  : Analysis.Version.DbgEng
    Value: 10.0.27725.1000

    Key  : Analysis.Version.Description
    Value: 10.2408.27.01 amd64fre

    Key  : Analysis.Version.Ext
    Value: 1.2408.27.1

    Key  : CLR.Engine
    Value: CORECLR

    Key  : CLR.Version
    Value: 9.0.24.52809

    Key  : Failure.Bucket
    Value: BREAKPOINT_80000003_coreclr.dll!WKS::GCHeap::WaitUntilGCComplete

    Key  : Failure.Hash
    Value: {54e9a6da-d4d0-d004-574b-4219b46bdb8d}

    Key  : Failure.Source.FileLine
    Value: 265

    Key  : Failure.Source.FilePath
    Value: D:\a\_work\1\s\src\coreclr\gc\gcee.cpp

    Key  : Failure.Source.SourceServerCommand
    Value: raw.githubusercontent.com/dotnet/runtime/9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3/src/coreclr/gc/gcee.cpp

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 896327

    Key  : Timeline.Process.Start.DeltaSec
    Value: 17922

    Key  : WER.OS.Branch
    Value: rs5_release

    Key  : WER.OS.Version
    Value: 10.0.17763.1

    Key  : WER.Process.Version
    Value: 1.0.0.0

FILE_IN_CAB:  SmfHaircuts.Service-2024-12-03-YB6213.DMP

NTGLOBALFLAG:  0

APPLICATION_VERIFIER_FLAGS:  0

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 0000000000000000
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 0

FAULTING_THREAD:  00000f6c

PROCESS_NAME:  SmfHaircuts.Service.dll

ERROR_CODE: (NTSTATUS) 0x80000003 - {EXCEPTION}  Breakpoint  A breakpoint has been reached.

EXCEPTION_CODE_STR:  80000003

STACK_TEXT:  
0000008c`61d7e028 00007ffc`bdba0f33     : 00000000`00000000 000002be`90a8dab0 000002be`90a8d9f0 0000008c`61d7e170 : ntdll!NtWaitForSingleObject+0x14
0000008c`61d7e030 00007ffb`364f1c30     : 00000000`00000000 00004612`d1730f35 00000000`00000000 00000000`00000284 : KERNELBASE!WaitForSingleObjectEx+0x93
0000008c`61d7e0d0 00007ffb`36416915     : 00000000`00000000 0000008c`61d7e2d0 00000000`00000804 0000008c`61d7e1b0 : coreclr!WKS::GCHeap::WaitUntilGCComplete+0x30
0000008c`61d7e100 00007ffb`364e8328     : 00007ffa`d68130c0 00000000`00000000 00000000`00000000 0000027d`f97fc570 : coreclr!Thread::RareDisablePreemptiveGC+0x9d
0000008c`61d7e190 00007ffb`3659ea2d     : 00007ffa`d68130c0 00000000`00000000 000002be`906cedf0 00000001`00000000 : coreclr!JIT_ReversePInvokeEnterRare2+0x18
0000008c`61d7e1c0 00007ffa`d7e5b718     : 00000000`00000004 0000008c`61d7e260 00000000`00000000 00007ffc`c166598d : coreclr!JIT_ReversePInvokeEnterTrackTransitions+0x9d13d
0000008c`61d7e1f0 00000000`00000004     : 0000008c`61d7e260 00000000`00000000 00007ffc`c166598d 00000000`00000000 : 0x00007ffa`d7e5b718
0000008c`61d7e1f8 0000008c`61d7e260     : 00000000`00000000 00007ffc`c166598d 00000000`00000000 0000008c`61d7e1f0 : 0x4
0000008c`61d7e200 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x0000008c`61d7e260

STACK_COMMAND:  ~0s; .ecxr ; kb

FAULTING_SOURCE_LINE:  D:\a\_work\1\s\src\coreclr\gc\gcee.cpp

FAULTING_SOURCE_FILE:  D:\a\_work\1\s\src\coreclr\gc\gcee.cpp

FAULTING_SOURCE_LINE_NUMBER:  265

FAULTING_SOURCE_SRV_COMMAND:  https://raw.githubusercontent.com/dotnet/runtime/9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3/src/coreclr/gc/gcee.cpp

FAULTING_SOURCE_CODE:  
No source found for 'D:\a\_work\1\s\src\coreclr\gc\windows\gcenv.windows.cpp'

SYMBOL_NAME:  coreclr!WKS::GCHeap::WaitUntilGCComplete+30

MODULE_NAME: coreclr

IMAGE_NAME:  coreclr.dll

FAILURE_BUCKET_ID:  BREAKPOINT_80000003_coreclr.dll!WKS::GCHeap::WaitUntilGCComplete

OS_VERSION:  10.0.17763.1

BUILDLAB_STR:  rs5_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  9.0.24.52809

FAILURE_ID_HASH:  {54e9a6da-d4d0-d004-574b-4219b46bdb8d}

Followup:     MachineOwner

### Reproduction Steps

Not possilbe. Happens randomly

### Expected behavior

Not freezing

### Actual behavior

Process completely unresponsive

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #110350

Switches the mechanism for OS notification about thread termination to use FLS (Fiber Local Storage) - the same mechanism as used on NativeAOT.

The advantage of FLS notification is that it does not run while holding the Loader Lock, thus it does not require that the termination callback never calls or waits for an OS call that may need to acquire that same Loader Lock. (It is hard for us to guarantee the latter)

This PR is similar to #110589 with additional mitigation for scenario where COM thread cleanups reinitialize the Thread object after we had our last chance to clean it up. 
The mitigation is basically ensuring that COM is initialized and sets up its FLS slot before we set up ours.

### CODE REVIEW

**Comment by VSadov** [comment]
@jkotas @mangod9 This is basically the same PR as before + mitigation for the COM reinitializing/attaching Thread objects and possibly running managed code after we had our last chance to detach Threads. 

The idea is basically to make sure we call CoInitialize before setting up our FLS slot, which would make COM to set up its FLS slot, if not already initialized. 

We call CoInitialize in most cases anyways, and fairly early, for example once the first method starts JIT-ing we launch the tiering helper, for example, which is explicitly an MTA thread. Most user-launched threads are MTA as well. Alas, all that would be after we have our FLS slot set already.

Why on the finalizer thread and not on the thread that initializes EE? 
My concern is that we do not know the context of the thread that initializes EE. In theory CoInitialize may be not allowed on some threads and initialize nothing. We control the state of Finalizer thread though.

**Comment by VSadov** [comment]
I have run quite a bit of winform tests with this + there is now a failfast in case we see an orphaned Thread in `DLL_THREAD_DETACH`, which is more deterministic than crashing on GC holes.

**Comment by jkotas** [comment]
`System.Threading.Tests.EtwTests.WaitHandleWaitEventTest` failure looks related to this change.

File: src/coreclr/vm/ceemain.cpp [hunk 1]
```diff
@@ -1671,6 +1677,24 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+                // The callback runs only once. There will be no further clean up and we will likely crash in GC
+                // once OS clears the native TLS.
+                //
+                // NB: It is ok for the Thread to be reinitialized before the premortem OS callback runs.
+                //     That historically may happen in rare cases when a thread cleans upon returning, but then FlsDataCleanup for COM
+                //     ends up releasing objects and calling APIs in the runtime that require Thread, or sends messages to the thread's
+                //     managed message loop. That is ok, as long as reinitialization happens prior to our thread termination
+                //     callback from OS. We guarantee that by ensuring our FlsSlot is initializad after COM has already been
+                //     initialized.
+                _ASSERTE_ALL_BUILDS(!GetThreadNULLOk() && "Thread reinitialized after final clean up?");
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:1696]: It would be better to fail-fast right when this re-initialization happens, so that we can see the callstack triggering the reinitialization. It would address https://github.com/dotnet/runtime/issues/112131.

File: src/coreclr/vm/interoputil.cpp [hunk 2]
```diff
@@ -1400,23 +1400,25 @@ VOID EnsureComStarted(BOOL fCoInitCurrentThread)
...
             GetThread()->SetApartment(Thread::AS_InMTA);
 
-        // set the finalizer event
-        FinalizerThread::EnableFinalization();
+        if (!IsFinalizerThread())
+        {
+            FinalizerThread::GetFinalizerThread()->SetRequiresCoInitialize();
+            // set the finalizer event
+            FinalizerThread::EnableFinalization();
+        }
```
Comment (jkotas) [inline src/coreclr/vm/interoputil.cpp:1421]: What is this trying to do? Is it still needed now that we wait for the finalizer thread to CoInitialize COM during startup?

File: src/coreclr/vm/ceemain.cpp (hunk 1 above)
Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:1696]: I would prefer that too, but it fairly hard to arrange. The reinitialization by itself is actually ok and happens often. It is the initialization after we had our _chance_ to clean it up, that is problematic. That is - initialization after OS has looked at our FLS slot.

The original failure would go like:

0. Clear state.
1. managed thread starts, initializes Thread. Arms FLS.
2. managed thread exits, clears Thread, disarms FLS.    (we are effectively at state 0 again)
3. OS looks at our slot, sees it is clear, does nothing.
4. COM does its clean up, calls managed code or something else that initializes Thread. This arms FLS, but it is too late, OS will not look at it again.

In theory steps `#1` and `#2` are optional. Just `#3` and `#4` are enough for a failure. 
`#3` is hard to detect if nothing runs in the callback.

File: src/coreclr/vm/interoputil.cpp (hunk 2 above)
Comment (VSadov) [reply src/coreclr/vm/interoputil.cpp:1421]: I think all the stuff that tries to CoInitialize the current and Finalizer thread lazily can be removed if this change goes in. 
I think quite a bit of cleanup might be possible even without this change. 

I did not want to go too far beyond what is needed for the fix - jut to minimize the diff, in case we backport this.

**Comment by VSadov** [comment]
> System.Threading.Tests.EtwTests.WaitHandleWaitEventTest failure looks related to this change.

That is on alpine-3.21-helix-arm32v7. I did not realize we run `ceemain`/`DLL_THREAD_DETACH` on linux as well, nor I am certain if the same invariant applies in such case. 

It may be worth to investigate and add similar guards on other platforms (unix, NativeAOT), if possible and appropriate, but it should not be in this PR.

I will scope the failfast to Windows only.

File: src/coreclr/vm/ceemain.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp]: Can we set a regular thread static bool in our callback to clear Thread (step 2) and trigger this fail-fast in Thread initialization when this bool is set (step 1)?

File: src/coreclr/vm/interoputil.cpp (hunk 2 above)
Comment (jkotas) [reply src/coreclr/vm/interoputil.cpp:1421]: I agree that there is a lot of cruft that can be cleaned up that is better left for a different PR.

I am not able to reason about whether this `if (!IsFinalizerThread()) { ... }` block is just a useless code or whether it can be actively harmful in some corner cases.

For this PR, can we delete the `if (!IsFinalizerThread())` block, `fCoInitCurrentThread` argument for `EnsureComStarted` and the one call to `EnsureComStarted(FALSE)`?

File: src/coreclr/vm/ceemain.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp]: (If you do this, it should be fine to keep this enabled on Unix too since it is not going to be sensitive to ordering of `DLL_THREAD_DETACH` notification and thread static destructors.

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp]: The thing is that currently the callback runs very rarely. When thread exits, KickOffThread calls DestroyThread and that does complete deinitialization and unregisters the callback. In the original repro the callback would typically not run, since COM would arm the callback after OS looked at our slot.

As aside - we do not need to do anything in KickOff. We could always rely on the callback - it is kind of the same thing, just the call comes from the OS equivalent of KickOff (at least that is the case on Windows). Always relying on callback would make it easier to do what you suggest.  
I actually tried to not call DestroyThread from our KickOff and thus relying entirely on the callback and it mostly worked fine, except for occasional crash in winforms tests when cleaning up syncblock/RCW stuff. Perhaps there is some subtle dependency on doing things the current way. When doing an overhaul, the reason may need to be understood, but for a fix I think we should keep deinitialization order is it is.

I think we can keep the order as it is and yet detect initialization after callback has run. We could do the following:
- do not disarm the callback when deinitializing a thread.
(i.e. do not do `FlsSetValue(g_flsIndex, NULL);` as that makes the callback to not run)
- track a threadstatic state: 
0 not armed
1 armed
2 callback has run

transition between 0 and 1 are legal either way and transition to 1 sets the new Thread into the slot value.
Callback always transitions to 2, but in state 0 does not run detach (the Thread in the slot is dead already). 
Attempt to transition from 2 to any other state is a failfast.

- There is still a way to get in trouble that this scheme will not detect. 
That is when a thread did not run anything managed and someone has a callback registered to run after ours and that enters managed code. 
I think for this reason we should keep the failfast in `DLL_THREAD_DETACH` as well. 

This "backstop" failfast would not be normally reachable as the state-based validation should trip on most problems earlier, unless the scenario above happens (or if our logic is wrong and there are other ways to see orphaned Thread).

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp]: I think what can be mildly confusing is an assumption that callback always runs for every exiting thread. It only runs if data slot is set to something not `NULL`. 

We do a check like `if (lpFlsData != NULL)` - I do not know exactly why. That was in the original NativeAOT implementation. Maybe it can happen in some older OSes or in some fiber-specific scenarios...

File: src/coreclr/vm/interoputil.cpp (hunk 2 above)
Comment (VSadov) [reply src/coreclr/vm/interoputil.cpp:1421]: I have added `g_pFinalizerThread->SetApartmentOfUnstartedThread(Thread::AS_InMTA)` to match manual call into CoInitialize, but that results in "lazy coinitialize" pattern forcing finalizer to set itself to MTA in response to setting finalizer thread to MTA.  

I think I can remove both this change and `g_pFinalizerThread->SetApartmentOfUnstartedThread(Thread::AS_InMTA)` to raise fewer questions. 
It is ok to use native API to set apartment state before Thread is attached. The rest is unnecessary and perhaps confusing.

File: src/coreclr/vm/ceemain.cpp [hunk 3]
```diff
@@ -1671,6 +1677,26 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+                // NB: It is ok for the Thread to be reinitialized before the premortem OS callback runs.
+                //     That historically may happen in rare cases when a thread cleans upon returning, but then FlsDataCleanup for COM
+                //     ends up releasing objects and calling APIs in the runtime that require Thread, or sends messages to the thread's
+                //     managed message loop. That is ok, as long as initialization happens prior to our thread termination
+                //     callback from OS. We guarantee that by ensuring our FlsSlot is initializad after COM has already been
+                //     initialized.
+                _ASSERTE_ALL_BUILDS(!GetThreadNULLOk() && "Thread initialized after final clean up could have run.");
+#endif
+                break;
+            }
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:1699]:
```suggestion
```
This should not be needed with the other change. It would be best to get rid of this DllMain in a follow up change.

File: src/coreclr/vm/ceemain.cpp [hunk 4]
```diff
@@ -1684,6 +1710,122 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+#ifdef TARGET_WINDOWS
+
+// Index for the fiber local storage of the attached thread pointer
+static uint32_t g_flsIndex = FLS_OUT_OF_INDEXES;
+
+#define FLS_STATE_CLEAR 0
+#define FLS_STATE_ARMED 1
+#define FLS_STATE_INVOKED 2
+
+static __declspec(thread) int flsState;
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:1758]:
```suggestion
static __declspec(thread) byte flsState;
```

File: src/coreclr/vm/ceemain.cpp [hunk 5]
```diff
@@ -1684,6 +1710,122 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+{
+    ASSERT(g_flsIndex != FLS_OUT_OF_INDEXES);
+    void* threadFromCurrentFiber = FlsGetValue(g_flsIndex);
+
+    if (threadFromCurrentFiber != thread)
+    {
+        _ASSERTE_ALL_BUILDS(!"Detaching a thread from the wrong fiber");
+    }
+
+    flsState = FLS_STATE_CLEAR;
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:1820]: Is this right? I do not think that we can handle re-initialization of the Thread after this point gracefully.

File: src/coreclr/vm/ceemain.cpp [hunk 6]
```diff
@@ -1684,6 +1710,122 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+    }
+}
+
+// Register the thread with OS to be notified when thread is about to be destroyed
+// It fails fast if a different thread was already registered with the current fiber.
+// Parameters:
+//  thread        - thread to attach
+static void OsAttachThread(void* thread)
+{
+    _ASSERTE_ALL_BUILDS((flsState != FLS_STATE_INVOKED) && "Initializing thread after termination callback has run.");
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:1794]:
```suggestion
    if (flsState != FLS_STATE_INVOKED)
    {
        _ASSERTE_ALL_BUILDS(!"Attempt to execute managed code after the .NET runtime thread state has been destroyed.");
    }
```
I would make the message more user facing, so that users are able to self-diagnose the problem.

File: src/coreclr/vm/ceemain.cpp (hunk 3 above)
Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:1699]: This can be hit if a thread did not run any managed code at all, and then someone enters managed code in an FLS callback that runs after our FLS callback would have run. 

We do not know any cases like this right now. It is theoretically possible.

File: src/coreclr/vm/ceemain.cpp (hunk 5 above)
Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:1823]: This happens in winforms. We currently rely on re-initialization in COM cleanup scenarios -

A thread returns from its entry point and we call DestroyThread, which comes here and detaches/destroys the Thread. 

Then OS goes through FLS callbacks and COM callback may need to run something that needs Thread, so we attach a new instance of Thread (because the former is gone by then), and the new Thread get later deinitialized in our FLS callback.  
As long as our deinitialization happens last, things work ok. Seems like it has been like this for a long time.

Ideally, we should not call DestroyThread explicitly when thread exits, just rely on callback - so we never need to reinitialize. Naively, making such change breaks other things, so probably not in this PR.

File: src/coreclr/vm/ceemain.cpp (hunk 3 above)
Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:1699]: I guess we could drop this check, considering we do not like to have this DllMain

Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp]: You made a good point that this check can catch one of the corner cases that I have not considered. I think that it is very unlikely for user code to hit this corner case, without tripping over the other check most of the time.

I am fine with either keeping it or leaving it out.

File: src/coreclr/vm/ceemain.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp]: > We do a check like if (lpFlsData != NULL)

My guess is that it is just a defensive programming or misunderstanding of the contract.

File: src/coreclr/vm/ceemain.cpp (hunk 5 above)
Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp:1815]: Ok, I agree that we want to fix this one in separate PR. The reinitialization sounds like a great source of mysterious corner-case bugs.

**Comment by VSadov** [comment]
I think the new failures in `SslStream_ServerUntrustedCaWithCustomTrust_OK ` are unrelated.
(`The remote certificate is invalid because of errors in the certificate chain: PartialChain`)

File: src/coreclr/vm/ceemain.cpp [hunk 7]
```diff
@@ -1684,6 +1690,137 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+    _ASSERTE(thread != NULL);
+    FlsSetValue(g_flsIndex, thread);
+}
+
+// Detach thread from OS notifications.
+// It fails fast if some other thread value was attached to the current fiber.
+// Parameters:
+//  thread        - thread to detach
+// Return:
+//  true if the thread was detached, false if there was no attached thread
```
Comment (VSadov) [inline src/coreclr/vm/ceemain.cpp:1793]:
```suggestion
```

I think we've removed this comment once already.

File: src/coreclr/vm/interoputil.cpp (hunk 2 above)
Comment (jkotas) [reply src/coreclr/vm/interoputil.cpp]: I am thinking about performance overhead of this change. We are going to do extra thread switch during startup critical path. It is unavoidable.

However, `EnsureComStarted` that is going to be executed a bit later is going to spin the finalizer thread again by setting `FinalizerThread::EnableFinalization`. 

Can we reduce the startup overhead by setting `g_fComStarted` on finalizer thread once we call CoInitialize and reduce EnsureComStarted to just:
```
    _ASSERTE(g_fComStarted); // COM is expected to be started on finalizer thread during startup
```
?

File: src/coreclr/vm/ceemain.cpp (hunk 7 above)
Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:1793]: In https://github.com/dotnet/runtime/pull/110631 , which was abandoned

File: src/coreclr/vm/interoputil.cpp (hunk 2 above)
Comment (VSadov) [reply src/coreclr/vm/interoputil.cpp]: > I am thinking about performance overhead of this change. We are going to do extra thread switch during startup critical path. It is unavoidable.

I've moved launching of finalizer thread a bit earlier. Initializing thread will do some other work before it needs to check if FLS/COM initialization is finished. Hopefully it will be at least partially done, so we'd not need to wait much, if at all.

> Can we reduce the startup overhead by setting `g_fComStarted` on finalizer thread

Good point. Since we will be initializing anyways, why not get some benefit from it.

File: src/coreclr/vm/ceemain.cpp [hunk 8]
```diff
@@ -1684,6 +1690,135 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+#ifdef TARGET_WINDOWS
+
+// Index for the fiber local storage of the attached thread pointer
+static uint32_t g_flsIndex = FLS_OUT_OF_INDEXES;
+
+#define FLS_STATE_CLEAR 0
+#define FLS_STATE_ARMED 1
+#define FLS_STATE_INVOKED 2
+
+static __declspec(thread) byte flsState;
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:1738]:
```suggestion
static __declspec(thread) byte t_flsState;
```
Naming nit

**Review by jkotas — COMMENTED** [review]
LGTM otherwise. Thank you!

**Review by jkotas — APPROVED** [review]

**Comment by VSadov** [comment]
/ba-g  remaining 2 osx arm64 test legs just take very long time and seems to eventually time out in most runs.

**Comment by u-less** [comment]
@VSadov Does this fix work for Linux platform ? We also encountered the same problem on the Linux platform after upgrading to. net9.

**Comment by jkotas** [comment]
This is fixing Windows-specific problem. If you are seeing issues on Linux, it is going to be something else. You may want to open a new issue about it.
