### PR TITLE
Optimize KnownColor value lookup via a combined color table

### LINKED ISSUE #49161: [Perf] Regression in GetHue and GetSaturation
### Run Information

Architecture | arm64
-- | --
OS | ubuntu 18.04
Baseline | [c7fa2955e3f860f8070adea115f7277281228a2e](https://github.com/dotnet/runtime/commit/c7fa2955e3f860f8070adea115f7277281228a2e)
Compare | [ee3f7daed083477689a4c6240025afa45ffa3352](https://github.com/dotnet/runtime/commit/ee3f7daed083477689a4c6240025afa45ffa3352)

### Regressions in System.Drawing.Tests.Perf_Color

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[GetHue](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_arm64_ubuntu 18.04/System.Drawing.Tests.Perf_Color.GetHue.html>) | 2.85 μs | 3.83 μs | 1.34 | | |
[GetSaturation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_arm64_ubuntu 18.04/System.Drawing.Tests.Perf_Color.GetSaturation.html>) | 2.66 μs | 3.34 μs | 1.25 | | |

graph
graph
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_arm64_ubuntu%2018.04_Regression/System.Drawing.Tests.Perf_Color.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Drawing.Tests.Perf_Color*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-cd971600-1737-40a7-be84-2ebb936772f86558daf22b04f3d88/aa8f66c8-6963-4a80-83f0-98e8fe629ee7.zip?sv=2019-07-07&se=2021-03-28T15%3A16%3A22Z&sr=c&sp=rl&sig=U2AdKOt3jFEvhh%2BvWHiZK4zWm5eKtteqzVwpPImLVLA%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-e0a356e9-d918-4a60-975f-affa5bf20d67d3392e7d658495f9b/9b725bfb-7ef2-4af8-8788-c263dfb5eced.zip?sv=2019-07-07&se=2021-03-29T00%3A33%3A50Z&sr=c&sp=rl&sig=1O8uAtN8dC8Afyavf7CrCfkd9D7sinr8P2HOgq3XUH4%3D>)

#### System.Drawing.Tests.Perf_Color.GetHue

```log
[2250.445 ; 2319.859) | @@@@@
[2319.859 ; 2389.273) | 
[2389.273 ; 2458.687) | 
[2458.687 ; 2528.101) | 
[2528.101 ; 2597.515) | 
[2597.515 ; 2666.929) | 
[2666.929 ; 2776.940) | @@
[2776.940 ; 2844.675) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[2844.675 ; 2914.089) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[2914.089 ; 2984.335) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[2984.335 ; 3094.568) | @@@@@@
[3094.568 ; 3163.982) | 
[3163.982 ; 3233.396) | 
[3233.396 ; 3302.810) | 
[3302.810 ; 3418.114) | @
[3418.114 ; 3487.528) | 
[3487.528 ; 3556.942) | 
[3556.942 ; 3626.356) | 
[3626.356 ; 3695.770) | 
[3695.770 ; 3870.175) | @@@@@@@@@@@@@
```
#### System.Drawing.Tests.Perf_Color.GetSaturation

```log
[1996.174 ; 2051.575) | @@@@
[2051.575 ; 2104.848) | @
[2104.848 ; 2160.249) | 
[2160.249 ; 2215.650) | 
[2215.650 ; 2271.051) | 
[2271.051 ; 2326.452) | 
[2326.452 ; 2381.853) | 
[2381.853 ; 2437.254) | 
[2437.254 ; 2492.655) | 
[2492.655 ; 2564.862) | @@@@@@@@@@@@@@@@@
[2564.862 ; 2620.263) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[2620.263 ; 2682.709) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[2682.709 ; 2739.098) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[2739.098 ; 2806.151) | @@
[2806.151 ; 2862.841) | @
[2862.841 ; 2973.643) | 
[2973.643 ; 3039.207) | 
[3039.207 ; 3156.006) | @
[3156.006 ; 3266.807) | 
[3266.807 ; 3365.991) | @@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by L2**
* Fixes: #49161 related to commit d21fe17023e2a03f9b
* Brings the following dotnet/performance microbenchmarks back on par
  with .NET5
  * System.Drawing.Tests.Perf_Color.GetBrightness
  * System.Drawing.Tests.Perf_Color.GetSaturation
  * System.Drawing.Tests.Perf_Color.GetHue
* Use one known color table for both system and non-system
  colors (indexed by the corresponding KnownColor enum value).
* This table is split into 2 arrays: color value and color kind (category).
* Add color category constants for Unknown, System, and Web.
* Combined table removes the need to handle mismatches corresponding
  with the KnownColor enum value.
* Obtaining the value of and verifying if a known color is a system
  color is simplified to a single lookup instead of multiple base
  bounds comparisons inside the fragmented KnownColor enum table.
* These base bounds comparisons would grow linearly as the KnownColor
  enum table had more colors added to it, mixed between system and
  non-system. Now no comparisons are needed.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=50489) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=50489) before we can accept your contribution.<br/><br/>:x: L2 [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=50489)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=50489) it.</sub>

**Comment by L2** [comment]
dotnet/performance microbenchmarks filtered with System.Drawing.Tests.Perf_Color*:

Base = Before this changeset
Diff = After this changeset

No Slower results for the provided threshold = 2% and noise filter = 25ns.

| Faster                                        | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| --------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| System.Drawing.Tests.Perf_Color.GetBrightness |      1.48 |          1540.92 |          1038.91 |         |
| System.Drawing.Tests.Perf_Color.GetSaturation |      1.47 |          1622.30 |          1104.48 |         |
| System.Drawing.Tests.Perf_Color.GetHue        |      1.35 |          1755.29 |          1303.64 |         |

**Comment by L2** [comment]
What my profiling showed was that Color.IsKnownColorSystem(color) called here was not being inlined anymore due to the extra comparison that was added to the KnownColorToArgb(KnownColor color) method:

https://github.com/dotnet/runtime/blob/5078dd61a81c88dbdd131a77b8148b4dee3803fa/src/libraries/Common/src/System/Drawing/KnownColorTable.cs#L187-L199

I also saw that there was a lot of time being spent in IsKnownColorSystem(KnownColor knownColor) due to the extra comparisons that were added:
https://github.com/dotnet/runtime/blob/5078dd61a81c88dbdd131a77b8148b4dee3803fa/src/libraries/System.Drawing.Primitives/src/System/Drawing/Color.cs#L375-L376

To mitigate both causes, I combined the color lookup tables inside KnownColorTable.cs, indexed by their enum value in KnownColor.cs. I also augmented this table to include the color category which leads to no base bounds comparisons necessary to check if a color is categorized as system or non-system (web).

Regarding the base bounds comparisons: the existing implementation categorized the color based on its location inside the KnownColor enum table. As this table became more fragmented, more comparisons would be needed to categorize a color. 

For example:
Enum {
SystemColor1
SystemColor2
SystemColor3
Web1
Web2
SystemColor4
SystemColor5
SystemColor6
Web3
SystemColor7
Web4}

Since modifications to the KnownColor enum table are breaking changes, new colors are added to the end and the existing implementation checks if a given known color is a system color by checking if its inside the enum value bounds of (SystemColor1 to SystemColor3 | SystemColor4 to SystemColor6| SystemColor7) in this example. As this becomes more fragmented, the comparisons grow linearly.

As we already have a unique lookup value for each color (their enum value) we can use a secondary table as it already exists in two parts (one for web and another for system) in KnownColorTable, combine it, and also include the category labels.

File: src/libraries/Common/src/System/Drawing/KnownColorTable.cs [hunk 1]
```diff
@@ -7,176 +7,252 @@ namespace System.Drawing
...
-            0xFFD8BFD8,     // Thistle
-            0xFFFF6347,     // Tomato
-            0xFF40E0D0,     // Turquoise
-            0xFFEE82EE,     // Violet
-            0xFFF5DEB3,     // Wheat
-            0xFFFFFFFF,     // White
-            0xFFF5F5F5,     // WhiteSmoke
-            0xFFFFFF00,     // Yellow
-            0xFF9ACD32,     // YellowGreen
+            Unknown,
```
Comment (safern) [inline src/libraries/Common/src/System/Drawing/KnownColorTable.cs:12]: should we instead introduce 3 constants?

Comment (L2) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs:12]: Thanks @safern , yes I did consider that initially but chose the enum route in favor of constants due to easier readability and maybe simpler when using the library? I believe enum compiles to a constant so I went with that currently. Also by using enums we can expand the categories in the future to hold more values other than unknown, system, and web. But you're right, if we use constants directly there will be less casting involved. I will follow your recommendation.

Comment (safern) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs:12]: I doubt having more categories. If we end up in the need to using more categories we can go back to an enum. 

Yeah, enums are handy cause they compile to a constant, but we are doing a lot of castings for this scenario, so it might just be better to store them as uint constants, or even byte constants given that we don't need 32 bits for the current categories?

Comment (L2) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs:12]: Sure, sounds good. I will change the enum categories to byte constants. Just a quick question, I had originally made them uint so I could put them in the same uint array:

`public static readonly uint[,] s_colorTable = new uint[knownColorCount, 2]`

but it turned out I still needed to cast the enums. By using byte constants, I will still need to cast to place them inside this table right? Or do you recommend something like an array of structs to hold the category byte constant and color value so we don't need to cast?

Comment (safern) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs:12]: We could have an array of byte, uint tiple. But let's leave it as you have it now using uint for both values. I'm not sure what would be better. 

@tannergooding insight might help.

Comment (L2) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs]: Thanks, I've updated it with the requested changes, keeping constant uint categories as suggested for now.

Comment (L2) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs]: Hi @safern , anything else I can do to enhance this PR? Thanks for the help.

Comment (tannergooding) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs]: Sorry, I missed the ping and Santi just pinged me offline.

My recommendation is to split this into a `byte[]` (for the kind) and `uint[]` (for the value). The JIT and C# compiler can optimize this scenario and it will save us some space.
The `byte[]` for the kind could even be further compressed if space was a concern, since its basically a bitmap (0 or 1, per entry)

Comment (safern) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs]: Hi @L2, I just spoke with @tannergooding and we think the best approach for this would be to have 2 separate arrays.

One `byte[]` for the color kind and one `uint[]` for the color itself. Having a multidimensional array might affect startup perf and memory perf vs two separate arrays, plus since these are primitives, the JIT will optimize these 2 arrays.

Comment (L2) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs]: Thank you, @tannergooding and @safern . I've updated it with the recommended changes. Looks to have a nice bump in speed with the casting removed and split array.

----------------
dotnet/performance microbenchmarks filtered with System.Drawing.Tests.Perf_Color*:

summary:
better: 3, geomean: 1.480
total diff: 3

No Slower results for the provided threshold = 2% and noise filter = 25ns.

| Faster                                        | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| --------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| System.Drawing.Tests.Perf_Color.GetBrightness |      1.55 |          1542.74 |           996.36 |         |
| System.Drawing.Tests.Perf_Color.GetSaturation |      1.50 |          1597.70 |          1064.63 |         |
| System.Drawing.Tests.Perf_Color.GetHue        |      1.40 |          1757.32 |          1258.50 |         |

File: src/libraries/Common/src/System/Drawing/KnownColorTable.cs [hunk 2]
```diff
@@ -153,30 +216,263 @@ internal static class KnownColorTable
...
+#endif
+            // "Web" colors, Part 2
+            KnownColorKindWeb,      // RebeccaPurple
+        };
+
         internal static Color ArgbToKnownColor(uint argb)
         {
-            // Should be fully opaque (and as such we can skip the first entry
-            // which is transparent).
             Debug.Assert((argb & Color.ARGBAlphaMask) == Color.ARGBAlphaMask);
```
[the remark this answers is not in the document]
Comment (L2) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs:468]: Thanks, updated.

File: src/libraries/Common/src/System/Drawing/KnownColorTable.cs [hunk 3]
```diff
@@ -153,30 +216,263 @@ internal static class KnownColorTable
...
 
-            for (int index = 1; index < s_colorTable.Length; ++index)
+            for (int index = 1; index < KnownColorCount; ++index)
```
[the remark this answers is not in the document]
Comment (L2) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs]: Sounds good, thanks! Updated.

[the remark this answers is not in the document]
Comment (safern) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs]: Also, is there a test that gives us enough test coverage that the color kind is the expected kind? Should we add one if not that makes sure the tables are constructed correctly?

[the remark this answers is not in the document]
Comment (L2) [reply src/libraries/Common/src/System/Drawing/KnownColorTable.cs]: Thanks @safern , I've added an additional test that goes over the ordering of the color kind table. Please let me know if you think any more tests are needed.

**Review by safern — APPROVED** [review]
Thank you very much!

**Comment by DrewScoggins** [comment]
### Improvemnts in System.Drawing.Tests.Perf_Color

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[GetHue](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Drawing.Tests.Perf_Color.GetHue.html>) | 1.65 μs | 1.36 μs | 0.83 | | |
[GetSaturation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Drawing.Tests.Perf_Color.GetSaturation.html>) | 1.39 μs | 1.15 μs | 0.82 | | |

graph
graph
![graph]
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_13_2021/refs/heads/main_x64_ubuntu%2018.04_Improvement/System.Drawing.Tests.Perf_Color.html>)

We are seeing these results in the lab, thanks for tracking down and fixing this issue.
