### PR TITLE
[mono][aot] Handle out of range indexes in the generated get_method () functions, they can happen since mini-llvm.c and aot-compiler.c can compute different table sizes.

### LINKED ISSUE #50202: [Wasm][AOT] register_methods_in_jinfo memory access out of bounds
### Description

Repro: https://github.com/jeromelaban/Wasm.Samples/tree/master/Bug50202/Bug50202
Faulty `dotnet.wasm` file: [dotnet.wasm.zip](https://github.com/dotnet/runtime/files/6200157/dotnet.wasm.zip)

For an unknown reason, the following error happens:

```
dotnet.js:6766 Unhandled exception in _finalize_startup RuntimeError: memory access out of bounds
    at register_methods_in_jinfo (<anonymous>:wasm-function[7879]:0x14f441)
    at load_aot_module (<anonymous>:wasm-function[5004]:0xbf7de)
    at mono_assembly_invoke_load_hook_internal (<anonymous>:wasm-function[3116]:0x750e0)
    at mono_assembly_request_load_from (<anonymous>:wasm-function[3108]:0x748ad)
    at search_bundle_for_assembly (<anonymous>:wasm-function[4234]:0xa3ec5)
    at netcore_load_reference (<anonymous>:wasm-function[8007]:0x1545f1)
    at mono_assembly_request_byname (<anonymous>:wasm-function[1372]:0x29900)
    at load_image (<anonymous>:wasm-function[1113]:0x237a5)
    at load_aot_module (<anonymous>:wasm-function[5004]:0xbf86d)
    at mono_assembly_invoke_load_hook_internal (<anonymous>:wasm-function[3116]:0x750e0)
```

This is the location of the error:
https://github.com/dotnet/runtime/blob/dc5c9099b2c4ebcc74f8f40a5de5c4733ac79bfa/src/mono/mono/mini/aot-runtime.c#L1856

Which is caused by invalid addresses provided by this:
https://github.com/dotnet/runtime/blob/dc5c9099b2c4ebcc74f8f40a5de5c4733ac79bfa/src/mono/mono/mini/aot-runtime.c#L2175

Like so: 

```
load_aot_module: System.Net.Http addr=6271 i=944
dotnet.js:1498 load_aot_module: System.Net.Http addr=6272 i=945
dotnet.js:1498 load_aot_module: System.Net.Http addr=6273 i=946
dotnet.js:1498 load_aot_module: System.Net.Http addr=6274 i=947
dotnet.js:1498 load_aot_module: System.Net.Http addr=6275 i=948
dotnet.js:1498 load_aot_module: System.Net.Http addr=6276 i=953
dotnet.js:1498 load_aot_module: System.Net.Http addr=948 i=954
dotnet.js:1498 load_aot_module: System.Net.Http addr=-2130634233 i=955
dotnet.js:1498 load_aot_module: System.Net.Http addr=84 i=956
dotnet.js:1498 load_aot_module: System.Net.Http addr=654377216 i=958
dotnet.js:1498 load_aot_module: System.Net.Http addr=37290241 i=959
```

### Configuration

2f6c5d6845e2964b6f96ba246c55c0e9d57d8b3d

### Regression?

Maybe?

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/50202.

### CODE REVIEW

File: src/mono/mono/mini/mini-llvm.c [hunk 1]
```diff
@@ -2874,12 +2874,14 @@ emit_get_method (MonoLLVMModule *module)
...
 
+	int table_len = module->max_method_idx + 1;
+
 	if (emit_table) {
 		LLVMTypeRef table_type;
 		LLVMValueRef *table_elems;
 		char *table_name;
 
-		int table_len = module->max_method_idx + 1;
+		printf ("MTABLE: %s %d\n", module->global_prefix, table_len);
```
Comment (jeromelaban) [inline src/mono/mono/mini/mini-llvm.c:2884]: Should this stay ?

**Comment by jeromelaban** [comment]
Confirmed fixes the original issue.

**Review by CoffeeFlux — APPROVED** [review]
Hopefully @imhameed can take a look when he's back, but otherwise LGTM.
