### PR TITLE
Avoid reporting incorrect thread context to Watson

### LINKED ISSUE #111182: EEPolicy::HandleFatalError calls RaiseFailFastException with invalid context
CONTEXT is captured here: https://github.com/dotnet/runtime/blob/31b5ae20fc558b0c8bfb18223c4c653de9b79567/src/coreclr/vm/eepolicy.cpp#L786

And then passed to RaiseFailFastException here: https://github.com/dotnet/runtime/blob/31b5ae20fc558b0c8bfb18223c4c653de9b79567/src/coreclr/vm/excep.cpp#L3574

Stacktrace:
```
KERNELBASE!RaiseFailFastException
coreclr!WatsonLastChance+0x1b3 [D:\a\_work\1\s\src\coreclr\vm\excep.cpp @ 3590] 
coreclr!EEPolicy::LogFatalError+0x6b4 [D:\a\_work\1\s\src\coreclr\vm\eepolicy.cpp @ 589] 
coreclr!EEPolicy::HandleFatalError+0x133 [D:\a\_work\1\s\src\coreclr\vm\eepolicy.cpp @ 828]
```

The problem is that RaiseFailFastException validates that the context matches a valid return address on the stack as part of CET. If the context is not valid, it rejects it, flags it as a potential attack and asserts in checked builds of Windows OS.

We should stop passing invalid CONTEXT to RaiseFailFastException and verify that the Watson bucketing of the crashes originating in EEPolicy::HandleFatalError works as expected.

### PR DESCRIPTION
**Pull request by tommcdon**
Fixes #111182
This change avoids reporting contexts generated from EEPolicy::HandleFatalError to Watson

### CODE REVIEW

File: src/coreclr/vm/excep.cpp [hunk 1]
```diff
@@ -3567,8 +3567,9 @@ LONG WatsonLastChance(                  // EXCEPTION_CONTINUE_SEARCH, _CONTINUE_
 #ifdef HOST_WINDOWS
                 CreateCrashDumpIfEnabled(fSOException);
 #endif
-                RaiseFailFastException(pExceptionInfo == NULL ? NULL : pExceptionInfo->ExceptionRecord,
-                                       pExceptionInfo == NULL ? NULL : pExceptionInfo->ContextRecord,
+                bool fAvoidReportContextToRaiseFailFast = tore.IsFatalError(); // avoid reporting incorrect thread context to Watson
```
Comment (jkotas) [inline src/coreclr/vm/excep.cpp]:
```suggestion
                // RaiseFailFastException validates that the context matches a valid return address on the stack as part of CET.
                // If the return address is not valid, it rejects the context, flags it as a potential attack and asserts in 
                // checked builds of Windows OS. 
                // Avoid reporting thread context captured by EEPolicy::HandleFatalError since it has IP that does not 
                // match a valid return address on the stack.
                bool fAvoidReportContextToRaiseFailFast = tore.IsFatalError();
```

**Comment by jkotas** [comment]
We had to play games with context passed to Watson on win x86 - see https://github.com/dotnet/coreclr/pull/23289 . You may want to double check that Watson and dump debugging on win x86 works well with this change.

**Review by jkotas — APPROVED** [review]

**Comment by tommcdon** [comment]
> We had to play games with context passed to Watson on win x86 - see [dotnet/coreclr#23289](https://github.com/dotnet/coreclr/pull/23289) . You may want to double check that Watson and dump debugging on win x86 works well with this change.

Verified `!analyze` works as expected on a Windows Error Reported collect dump of an x86 test app calling `Environment.FailFast`, which invokes the `FatalError` code path:

```
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 083b2f3c (ConsoleApp1!Program.<<Main>$>g__Function5|0_4+0x00000054)
   ExceptionCode: 80131623
  ExceptionFlags: 00000001
NumberParameters: 0

PROCESS_NAME:  ConsoleApp1.dll
.
.
.
STACK_TEXT:  
0257f27c 6a0574ec System_Private_CoreLib!System.Environment.FailFast+0x3c
0257f2dc 6a05749f System_Private_CoreLib!System.Environment.FailFast+0xf
0257f2e8 6a057448 System_Private_CoreLib!System.Environment.FailFast+0x18
0257f2f0 083b2f3c ConsoleApp1!Program.<<Main>$>g__Function5|0_4+0x54
0257f308 083b2eca ConsoleApp1!Program.<<Main>$>g__Function4|0_3+0x3a
0257f320 083b2e72 ConsoleApp1!Program.<<Main>$>g__Function3|0_2+0x3a
0257f338 083b2e1a ConsoleApp1!Program.<<Main>$>g__Function2|0_1+0x3a
0257f350 083b2dc2 ConsoleApp1!Program.<<Main>$>g__Function1|0_0+0x3a
0257f368 083b2d2b ConsoleApp1!Program.<Main>$+0x3b
```
