### PR TITLE
JIT: don't inline methods with small stackallocs if the call site is …

### LINKED ISSUE #43391: How to forcefully zeroing memory allocated by stackalloc?
The program I wrote uses stackalloc to allocate small memory (8byte~64byte), but unexpectedly found that some methods will read non-zero memory under the Release. by reading such related [questions](https://github.com/dotnet/runtime/issues/4384#issuecomment-124003439) , I know stackalloc It is not always possible to allocate zero-initialized data.

localsinit has always been the default behavior of c#, and [SkipLocalsInit ](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#performance-and-interop) can be used in c#9.0, but at present, what can I do to ensure that my stackalloc is forced to zero initialization?

### PR DESCRIPTION
**Pull request by AndyAyersMS**
…in a loop

The logic in `fgInlinePrependStatements` that zero-initializes locals doesn't
kick in for jit temps introduced when small stackallocs are optimized. So if we
inline a method with a small stackalloc into a loop, the memory for the
stackalloc doesn't get properly re-zeroed on each iteration.

Fix by disallowing such inlines by adding an extra check: the call site must
not be in a loop.

Closes #43391.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@briansull PTAL
cc @dotnet/jit-contrib

File: src/coreclr/src/jit/importer.cpp [hunk 1]
```diff
@@ -15146,14 +15146,18 @@ void Compiler::impImportBlockCode(BasicBlock* block)
                     {
                         const ssize_t allocSize = op2->AsIntCon()->IconValue();
 
+                        bool bbInALoop =
+                            (compIsForInlining() && ((impInlineInfo->iciBlock->bbFlags & BBF_BACKWARD_JUMP) != 0)) ||
```
Comment (briansull) [inline src/coreclr/src/jit/importer.cpp:15150]: Should we use a helper method to check this property here, as this could be needed in more places in the future?

**Review by briansull — APPROVED** [review]
Approved with a suggestion to use a helper method instead

File: src/coreclr/src/jit/importer.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/src/jit/importer.cpp:15150]: Good suggestion. It is already used elsewhere.

**Comment by AndyAyersMS** [comment]
Failure is unrelated; seems to be some flaky infrastructure.
```
##[error]We stopped hearing from agent Azure Pipelines 6. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
```

**Comment by AndyAyersMS** [comment]
@GrabYourPitchforks fix is in master.

About backports: given this has been in the code for ~4 years and is just reported now it does not seem urgent? Thoughts?

The change is pretty simple so backporting should not be risky/difficult.

**Comment by GrabYourPitchforks** [comment]
I'd vote for backporting it to all affected JIT versions. Otherwise we could end up in a situation where somebody creates a netstandard library they believe to be type-safe (no use of uninitialized memory), they test it on net48 and net60 and observe correct behavior, but the consuming app exhibits undefined behavior on other runtimes. And it might be very difficult to root cause the behavior back to this.

@jkotas for other opinions.

**Comment by AndyAyersMS** [comment]
Also should note the only diff I found running locally (SPMI vs fx, tests) was in the test case I added when I first implemented this optimization. So we don't currently appear to be affected by this issue in our own code.

**Comment by jkotas** [comment]
> they test it on net48 and net60 and observe correct behavior, but the consuming app exhibits undefined behavior on other runtimes

The same can be said for many other bugs. I think that the probability of this bug being hit by the actual code is pretty low. It would be hard to make a case about it for servicing shiproom.

**Comment by GrabYourPitchforks** [comment]
If the smart money says no real need to backport, so be it. :)
