### PR TITLE
Install native dependencies on all Apple OS in CI

### LINKED ISSUE #82240: OSX infra issue - prereq check for 'pkg-config' missing
Library + OSX tests failing with this:
```
  __DistroRid: osx-x64
  Setting up directories for build
  Checking prerequisites...
  Please install pkg-config before running this script, see https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/macos-requirements.md
```

See errors on https://github.com/dotnet/runtime/pull/81006

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Please install pkg-config before running this script",
  "BuildRetry": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[175172](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175172)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175172/logs/2332)|dotnet/runtime#81867|
|[179215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=179215)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/179215/logs/1244)|dotnet/runtime#82432|
|[179276](https://dev.azure.com/dnceng-public/public/_build/results?buildId=179276)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/179276/logs/56)|dotnet/runtime#82433|
|[179273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=179273)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/179273/logs/342)|dotnet/runtime#82433|
|[175441](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175441)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175441/logs/1535)|dotnet/runtime#82268|
|[175444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175444)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175444/logs/102)|dotnet/runtime#82268|
|[168759](https://dev.azure.com/dnceng-public/public/_build/results?buildId=168759)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/168759/logs/812)|dotnet/runtime#82005|
|[176245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176245)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/176245/logs/1771)|dotnet/runtime#82192|
|[176254](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176254)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/176254/logs/60)|dotnet/runtime#82192|
|[174792](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174792)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174792/logs/1377)|dotnet/runtime#82254|
|[175734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175734)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175734/logs/1677)|dotnet/runtime#82292|
|[175724](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175724)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175724/logs/1066)|dotnet/runtime#81319|
|[175707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175707)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175707/logs/1527)|dotnet/runtime#82249|
|[175737](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175737)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175737/logs/27)|dotnet/runtime#82292|
|[175733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175733)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175733/logs/27)|dotnet/runtime#81164|
|[175727](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175727)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175727/logs/27)|dotnet/runtime#81319|
|[175710](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175710)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175710/logs/27)|dotnet/runtime#82249|
|[175646](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175646)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175646/logs/1062)|dotnet/runtime#82086|
|[175665](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175665)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175665/logs/27)|dotnet/runtime#81319|
|[175661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175661)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175661/logs/27)|dotnet/runtime#82287|
|[175600](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175600)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175600/logs/1076)|dotnet/runtime#82253|
|[175588](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175588)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175588/logs/991)|dotnet/runtime#82285|
|[175582](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175582)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175582/logs/738)||
|[175621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175621)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175621/logs/27)|dotnet/runtime#81319|
|[175607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175607)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175607/logs/27)|dotnet/runtime#81969|
|[175603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175603)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175603/logs/27)|dotnet/runtime#82253|
|[175567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175567)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175567/logs/1713)||
|[174946](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174946)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174946/logs/1618)|dotnet/runtime#82235|
|[175539](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175539)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175539/logs/955)|dotnet/runtime#82284|
|[175543](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175543)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175543/logs/7)||
|[175520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175520)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175520/logs/221)|dotnet/runtime#82222|
|[175490](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175490)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175490/logs/1571)|dotnet/runtime#82181|
|[175483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175483)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175483/logs/1218)|dotnet/runtime#80960|
|[175479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175479)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175479/logs/1028)|dotnet/runtime#82282|
|[175493](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175493)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175493/logs/27)|dotnet/runtime#82181|
|[175460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175460)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175460/logs/1045)|dotnet/runtime#82281|
|[175482](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175482)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175482/logs/27)|dotnet/runtime#82282|
|[175420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175420)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175420/logs/1249)|dotnet/runtime#82222|
|[175463](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175463)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175463/logs/27)|dotnet/runtime#82281|
|[175045](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175045)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175045/logs/1415)|dotnet/runtime#82264|
|[175318](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175318)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175318/logs/1211)|dotnet/runtime#82276|
|[175325](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175325)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175325/logs/1051)|dotnet/runtime#82277|
|[175251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175251)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175251/logs/971)|dotnet/runtime#82255|
|[175228](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175228)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175228/logs/1397)|dotnet/runtime#80297|
|[175193](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175193)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175193/logs/1891)|dotnet/runtime#81518|
|[175165](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175165)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175165/logs/1774)|dotnet/runtime#82270|
|[175231](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175231)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175231/logs/27)|dotnet/runtime#80297|
|[175139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175139)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175139/logs/1241)|dotnet/runtime#82268|
|[175196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175196)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175196/logs/27)|dotnet/runtime#81518|
|[175175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175175)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175175/logs/27)|dotnet/runtime#81867|
|[175168](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175168)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175168/logs/27)|dotnet/runtime#82270|
|[175085](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175085)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175085/logs/1054)|dotnet/runtime#82265|
|[175060](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175060)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175060/logs/1148)|dotnet/runtime#80539|
|[175142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175142)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175142/logs/48)|dotnet/runtime#82268|
|[175037](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175037)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175037/logs/1670)|dotnet/runtime#82206|
|[175027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175027)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175027/logs/1095)|dotnet/runtime#82121|
|[174980](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174980)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174980/logs/1118)|dotnet/runtime#80960|
|[174972](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174972)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174972/logs/723)||
|[175040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175040)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175040/logs/27)|dotnet/runtime#82206|
|[174962](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174962)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174962/logs/1041)|dotnet/runtime#82261|
|[175030](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175030)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175030/logs/27)|dotnet/runtime#82121|
|[174934](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174934)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174934/logs/1045)|dotnet/runtime#82259|
|[174906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174906)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174906/logs/1846)||
|[174879](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174879)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174879/logs/1881)|dotnet/runtime#81518|
|[174826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174826)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174826/logs/1419)|dotnet/runtime#80635|
|[174928](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174928)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174928/logs/293)|dotnet/runtime#82179|
|[174788](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174788)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174788/logs/1153)|dotnet/runtime#82253|
|[174882](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174882)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174882/logs/27)|dotnet/runtime#81518|
|[174771](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174771)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174771/logs/2091)|dotnet/runtime#82246|
|[174767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174767)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174767/logs/2034)|dotnet/runtime#82245|
|[174535](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174535)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174535/logs/2385)|dotnet/runtime#81006|
|[174538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174538)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174538/logs/43)|dotnet/runtime#81006|
|[174742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174742)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174742/logs/2204)|dotnet/runtime#82250|
|[174732](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174732)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174732/logs/1415)|dotnet/runtime#80960|
|[174706](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174706)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174706/logs/2039)|dotnet/runtime#82221|
|[174813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174813)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174813/logs/7)||
|[174711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174711)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174711/logs/2071)|dotnet/runtime#82249|
|[174791](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174791)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174791/logs/27)|dotnet/runtime#82253|
|[174670](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174670)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174670/logs/1146)|dotnet/runtime#82238|
|[174779](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174779)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174779/logs/91)|dotnet/runtime#82248|
|[174775](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174775)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174775/logs/59)|dotnet/runtime#82246|
|[174776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174776)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174776/logs/598)|dotnet/runtime#82248|
|[174770](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174770)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174770/logs/27)|dotnet/runtime#82245|
|[174745](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174745)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174745/logs/27)|dotnet/runtime#82250|
|[174652](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174652)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174652/logs/2029)|dotnet/runtime#79790|
|[174666](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174666)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174666/logs/1287)|dotnet/runtime#82183|
|[174656](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174656)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174656/logs/1140)|dotnet/runtime#81063|
|[174661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174661)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174661/logs/1085)|dotnet/runtime#82244|
|[174517](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174517)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174517/logs/1388)|dotnet/runtime#82184|
|[174714](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174714)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174714/logs/27)|dotnet/runtime#82249|
|[174709](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174709)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174709/logs/27)|dotnet/runtime#82221|
|[174503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174503)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174503/logs/1525)|dotnet/runtime#82086|
|[174673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174673)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174673/logs/27)|dotnet/runtime#82238|
|[174646](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174646)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174646/logs/598)|dotnet/runtime#82242|
|[174655](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174655)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174655/logs/27)|dotnet/runtime#79790|
|[174649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174649)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174649/logs/27)|dotnet/runtime#82242|
|[174584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174584)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174584/logs/923)|dotnet/runtime#82148|
|[174576](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174576)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174576/logs/1077)|dotnet/runtime#81319|
|[174550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174550)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174550/logs/1032)|dotnet/runtime#82223|
|[174555](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174555)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/174555/logs/956)|dotnet/runtime#82190|
Displaying 100 of 104 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|104|

### PR DESCRIPTION
**Pull request by am11**
Fix https://github.com/dotnet/runtime/issues/82240
(hopefully 🤞)

### CODE REVIEW

File: eng/install-native-dependencies.sh [hunk 1]
```diff
@@ -14,22 +14,33 @@ if [ -e /etc/os-release ]; then
...
+
+        apt update
+
+        apt install -y build-essential gettext locales cmake llvm clang lldb liblldb-dev libunwind8-dev libicu-dev liblttng-ust-dev \
+            libssl-dev libkrb5-dev libnuma-dev zlib1g-dev
+
+        localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
+        ;;
+
+    mac*|osx|ios*|tvos*)
```
Comment (am11) [inline eng/install-native-dependencies.sh:32]:
```suggestion
    osx|mac*|ios*|tvos*)
```

File: eng/pipelines/coreclr/templates/build-job.yml [hunk 2]
```diff
@@ -167,7 +167,7 @@ jobs:
     # Linux builds use docker images with dependencies preinstalled,
     # and FreeBSD builds use a build agent with dependencies
     # preinstalled, so we only need this step for OSX and Windows.
-    - ${{ if eq(parameters.osGroup, 'osx') }}:
+    - ${{ if in(parameters.osGroup, 'osx', 'maccatalyst', 'ios', 'iossimulator', 'tvos', 'tvossimulator') }}:
```
Comment (hoyosjs) [inline eng/pipelines/coreclr/templates/build-job.yml:170]: No harm, although not sure this will impact any leg.

**Review by hoyosjs — APPROVED** [review]

File: eng/pipelines/coreclr/templates/build-job.yml (hunk 2 above)
Comment (am11) [reply eng/pipelines/coreclr/templates/build-job.yml:170]: Yes. It's easy to miss these, so I kept them in sync; since we need to run this script if it is any Apple OS && there is any native build step. We just don't have something like https://github.com/dotnet/runtime/blob/b01311bd8dc591ce26b88a86b592c63a26798ceb/eng/native/configureplatform.cmake#L102 in pipelines.

Comment (am11) [reply eng/pipelines/coreclr/templates/build-job.yml:170]: Yes, harmless. It's easy to miss these and hard to figure out which condition is the culprit, so I kept them in sync. We need to run install-native-dependencies script in the CI, if we are on any Apple OS && there is any native build step. We just don't have something more generic like https://github.com/dotnet/runtime/blob/b01311bd8dc591ce26b88a86b592c63a26798ceb/eng/native/configureplatform.cmake#L102 in pipelines.

**Comment by am11** [comment]
Quic test failure is unrelated.

Lets merge this to unblock various pipelines.

File: eng/install-native-dependencies.sh [hunk 3]
```diff
@@ -10,26 +10,41 @@ set -e
...
-    echo "Must pass 'linux', 'macos', 'maccatalyst', 'ios' or 'tvos' as first argument."
-    exit 1
-fi
+        apt install -y build-essential gettext locales cmake llvm clang lldb liblldb-dev libunwind8-dev libicu-dev liblttng-ust-dev \
+            libssl-dev libkrb5-dev libnuma-dev zlib1g-dev
+
+        localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
+        ;;
+
+    osx|mac*|ios*|tvos*)
```
Comment (akoeplinger) [inline eng/install-native-dependencies.sh:36]: nit for a future PR: I prefer listing the OSes explicitly (`maccatalyst`, `ios`, `iossimulator`) as it makes it easier to find matches if you're grepping the codebase

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
Thank you!

File: eng/install-native-dependencies.sh (hunk 3 above)
Comment (am11) [reply eng/install-native-dependencies.sh:36]: I opted for this approach because there was `macos` option in old revision and the rest are no different than `StartsWith('ios/tvos')` per-existing pattern. I agree that we should update such conditions together and bring them to the same plan to keep things plain and grep'able. Will follow-up after https://github.com/dotnet/runtime/pull/82086.

Comment (am11) [reply eng/install-native-dependencies.sh:36]: I opted for this approach because there was `macos` option in old revision and the rest are no different than `StartsWith('ios/tvos')` per-existing pattern. I agree that we should update such conditions together and bring them to the same plan to keep things plain and grep'able. Will follow-up after https://github.com/dotnet/runtime/pull/82086 is merged.

**Comment by am11** [comment]
> backporting to release/7.0 failed

@hoysjs, manually backported https://github.com/dotnet/runtime/pull/82322 and https://github.com/dotnet/runtime/pull/82323.
