### PR TITLE
Fix MarshalArrayAsParam/AsLPArray/AsLPArrayTest test

### LINKED ISSUE #81674: PInvoke/Array/MarshalArrayAsParam/AsLPArray/AsLPArrayTest failing
```
BEGIN EXECUTION

C:\git\runtime\artifacts\tests\coreclr\windows.x64.Release\interop\PInvoke\Array\MarshalArrayAsParam\AsLPArray\AsLPArrayTest>set DOTNETCLI=C:\git\runtime\dotnet.cmd 
call C:\git\runtime\src\tests\Common\scripts\nativeaottest.cmd C:\git\runtime\artifacts\tests\coreclr\windows.x64.Release\interop\PInvoke\Array\MarshalArrayAsParam\AsLPArray\AsLPArrayTest\ AsLPArrayTest.dll 
ByVal marshaling CLR array as c-style-array no attributes
ByVal marshaling  CLR array as c-style-array with InAttribute applied
By value marshaling CLR array as c-style-array with InAttribute and OutAttribute applied

TEST FAIL: Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1, String) + 0x4b
   at ArrayMarshal.TestMarshalByVal_InOut() + 0xa0
   at ArrayMarshal.Main() + 0x2c
============ [CStyle_Array_Int] ============
============ [CStyle_Array_Uint] ============
============ [CStyle_Array_Short] ============
============ [CStyle_Array_Word] ============
============ [CStyle_Array_Long64] ============
============ [CStyle_Array_ULong64] ============
============ [CStyle_Array_Double] ============
============ [CStyle_Array_Float] ============
============ [CStyle_Array_Byte] ============
============ [CStyle_Array_Char] ============
============ [CStyle_Array_LPCSTR] ============
============ [CStyle_Array_LPSTR] ============
============ [CStyle_Array_LPCSTR] ============
============ [CStyle_Array_Struct] ============
============ [CStyle_Array_Bool] ============
============ [CStyle_Array_Int] ============
============ [CStyle_Array_Uint] ============
============ [CStyle_Array_Short] ============
============ [CStyle_Array_Word] ============
============ [CStyle_Array_Long64] ============
============ [CStyle_Array_ULong64] ============
============ [CStyle_Array_Double] ============
============ [CStyle_Array_Float] ============
============ [CStyle_Array_Byte] ============
============ [CStyle_Array_Char] ============
============ [CStyle_Array_LPCSTR] ============
============ [CStyle_Array_LPSTR] ============
============ [CStyle_Array_LPCSTR] ============
============ [CStyle_Array_Struct] ============
============ [CStyle_Array_Bool] ============
============ [CStyle_Array_Int_InOut] ============
============ [CStyle_Array_Int] ============
============ [CStyle_Array_Int_InOut_Null] ============
============ [CStyle_Array_Int_InOut_ZeroLength] ============
[CStyle_Array_Int_InOut_ZeroLength] Error: parameter actual is NULL
Expected: 100
Actual: 101
END EXECUTION - FAILED
```

### PR DESCRIPTION
**Pull request by eduardo-vp**
When marshalling an `[Out, MarshalAs(UnmanagedType.LPArray)] string[]` parameter, the marshaller allocates a native buffer but skips initialization (`TransformManagedToNative` is skipped for out-only parameters). Native callees can attempt to free those uninitialized pointers and cause heap corruption.

Fixes #81674.

### CODE REVIEW

**Review by MichalStrehovsky — APPROVED** [review]
LGTM!

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs [hunk 1]
```diff
@@ -1114,9 +1114,30 @@ protected override void AllocManagedToNative(ILCodeStream codeStream)
...
+                codeStream.EmitStLoc(vAllocSize);
+
+                codeStream.Emit(ILOpcode.call, emitter.NewToken(
+                    InteropTypes.GetMarshal(Context).GetKnownMethod("AllocCoTaskMem"u8, null)));
+                codeStream.Emit(ILOpcode.dup);
+                StoreNativeValue(codeStream);
+                // Zero initialize: initblk(nativeBuffer, 0, allocSize)
+                codeStream.EmitLdc(0);
+                codeStream.EmitLdLoc(vAllocSize);
+                codeStream.Emit(ILOpcode.initblk);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1133]: @jkoritzinsky @jtschuster Do we handle this in the source generator side? The `ArrayMarshaller<T, TUnmanagedElement>.AllocateContainerForUnmanagedElements` doesn't initialize to zero in that case, but I don't recall if we do that in the actual body for `out` params.

Comment (jtschuster) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1133]: I asked copilot investigate: https://github.com/dotnet/runtime/tasks/700dfe52-b67a-4ecf-b82d-fa901f520346?session_id=901fca07-1235-4437-b7f7-eb0a23452feb

We do call `Clear()` on the container for `[Out]` parameters before calling the PInvoke, and we also call `Clear()` before calling the managed method for UnmanagedToManaged in the COM generator.
