### PR TITLE
Fix macOS floating point corruption

### LINKED ISSUE #66568: Test failure Regressions/coreclr/GitHub_16833/Test16833/Test16833.sh
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20220313.1
](https://dev.azure.com/dnceng/public/_build/results?buildId=1661068&view=ms.vss-test-web.build-test-results-tab&runId=45721876&resultId=110795&paneView=debug)

Failed test:
```
CoreCLR OSX arm64 Checked gcstress0xc @ OSX.1200.ARM64.Open

- Regressions/coreclr/GitHub_16833/Test16833/Test16833.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /tmp/helix/working/A59A092C/w/A38E0941/uploads/Reports/Regressions.coreclr/GitHub_16833/Test16833/Test16833.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A59A092C/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Test16833.dll ''
Test Test2 failed. Expected "Test2:  1, 2, 3, 4, [5, 6], 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17", got "Test2:  1, 2, 3, 4, [5, 6], -9.255963134931783E+61, 0, 0, 0, 11, 12, 13, 14, 15, 16, 17"
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A59A092C/p
/private/tmp/helix/working/A59A092C/w/A38E0941/e/Regressions/coreclr/GitHub_16833/Test16833/Test16833.sh
Expected: True
Actual:   False


Stack trace
   at Regressions_coreclr._GitHub_16833_Test16833_Test16833_._GitHub_16833_Test16833_Test16833_sh()
```

### PR DESCRIPTION
**Pull request by janvorli**
There is a race condition between activation signal handling and returning from a hardware exception handler on macOS. It shows up intermittently in the Regression/coreclr/GitHub_16833 test in the CI and I am able to repro it on my local mac once in several thousands of iterations of the test when running with GC stress C.

It turned out the issue is caused by the order in which we set parts of the context in the thread when returning from the hardware exception handler. MacOS can only set the floating point and control / integer portions separately. We were setting the control / integer portion first and the floating point portion after that. In the race condition, the signal handling code in the macOS extracts the context that contains the new control registers, but the old floating point ones (which is the state of those in the `PAL_DispatchException`). The signal handler for the activation injection then gets executed and when it returns later to our managed code, the floating point registers get restored to the wrong values.
I have figured this out by adding some instrumentation to the PAL / runtime, logging state of the `PC` and `D0` registers to the stresslog in activation handler / hardware exception handler. I could see that the hardware exception handler was getting correct `D0` at a `PC` and right away the activation handler was getting a corrupted `D0`at the same `PC` and the `D0` matched what the formatted string contained in the failing test instead of the correct value (0xcccccccccccccccc or rarely 0).

The fix is to change the context setting to first set the floating point registers and then the control / integer portion of the context.

With the fix, the test was running over the whole weekend without any crashes.

Close #66568

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @mangod9

**Comment by janvorli** [comment]
cc: @AntonLapounov

**Comment by AntonLapounov** [comment]
> In the race condition, the signal handling code in the macOS extracts the context that contains the new control registers, but the old floating point ones

> The fix is to change the context setting to first set the floating point registers and then the control / integer portion of the context.

What prevents the opposite case, i.e. using the old control registers with the new floating point ones?  Thanks for catching this!

File: src/coreclr/pal/src/thread/context.cpp [hunk 1]
```diff
@@ -1569,6 +1487,65 @@ CONTEXT_SetThreadContextOnPort(
         }
     }
 
+    if (lpContext->ContextFlags & (CONTEXT_CONTROL|CONTEXT_INTEGER) & CONTEXT_AREA_MASK)
```
Comment (jkotas) [inline src/coreclr/pal/src/thread/context.cpp:1490]: It may be useful to add a note that the integer/control registers have to be set last.

**Review by jkotas — APPROVED** [review]
LGTM
