### PR TITLE
[mbr] Fix encmap boundary and method RVA lookup.

### LINKED ISSUE #50190: WebAssembly hot reload reverts to old version of a type
### Description

It's possible this is a known limitation and that @lambdageek has it on a backlog, but @pranavkm said I should report things to ensure they are tracked.

The WebAssembly hot reload support is amazingly fast (*really* amazingly - I've never seen hot reload so fast on any other tech) but currently it appears to be limited to making changes in a single type. If you have type `A` referencing `B`, and you edit `B` then the change appears, but if you then edit `A`, your change to `A` appears but it reverts to referencing the old unedited version of `B`.

More precise steps:

 * Use latest preview 3 SDK
 * `dotnet new blazorwasm -o MyApp`
 * `cd MyApp`

Issue 1:

 * Edit `Pages/Index.html`, adding `<Counter />`
 * `dotnet watch`. See your counter on the home screen.
 * Edit `Pages/Counter.razor`, e.g., changing the `<h1>` element to `<h1>Counter2</h1>`. See this show up on the home screen where you added it.
 * Edit `Pages/Index.razor` to add a second `<Counter />`.
    * Expected: New counter appears also with title `Counter2`
    * Actual: New counter appears, but the title is `Counter`, and the other counter component also reverts its title to `Counter`. 

Issue 2:

 * `dotnet watch`
 * Edit `Shared/SurveyPrompt.razor`, changing some text (e.g., `tell us what you think` -> `HELLO`). See your change appear correctly in the browser window.
 * Go to `Index.razor` and try to edit the `<h1>` text.
   * Expected: change shows up
   * Actual: Nothing happens

### Configuration

This is with SDK `6.0.100-preview.3.21173.6`, with `Microsoft.NETCoreSdk.BundledVersions.props` patched to use the runtime version `6.0.0-preview.4.21174.4`.

### PR DESCRIPTION
**Pull request by lambdageek**
Two separate issues:

1. When we process the EnC map, any tables after the last one that has an update gets an "enc_recs" pointer that's one past the last row of the table.  (the enc_recs pointer is used to speed up relative address lookup).  So at lookup time if enc_recs says to look past the end of the EnC map table, we know there won't be any updates - return -1.

2. When looking for the updated RVA of a method, we need to go through every delta and find the latest one that has an update for the given method.  The problem is that if a later generation doesn't have an update, we would take the NULL return value at face value and it would look like the method had no updates to its body - we would go back to using the original version from before any updates were applied.  Instead now ignore lookup table misses and remember the last successful lookup.  Fixes https://github.com/dotnet/runtime/issues/50190

### CODE REVIEW

File: src/mono/mono/metadata/metadata-update.c [hunk 1]
```diff
@@ -635,11 +635,17 @@ mono_image_relative_delta_index (MonoImage *image_dmeta, int token)
 	g_assert (delta_info);
 
 	int index_map = delta_info->enc_recs [table];
+	int encmap_rows = table_info_get_rows (encmap);
+
+	/* if the table didn't have any updates in this generation and the
+	 * table index is bigger than the last table that got updates,
+	 * enc_recs will point past the last row */
+	if (index_map - 1 == encmap_rows)
```
Comment (CoffeeFlux) [inline src/mono/mono/metadata/metadata-update.c:643]: And here you promised me no off by one math ;(

**Review by thaystg — APPROVED** [review]
LGTM

**Review by CoffeeFlux — APPROVED** [review]

**Comment by lambdageek** [comment]
Manually backported to Preview 3 https://github.com/dotnet/runtime/pull/50254
