### PR TITLE
Remove _isBlocked constraint from StreamReader.Peek()

### LINKED ISSUE #68983: StreamReader.Peek() on a DeflateStream returns -1 early
### Description

I have code that has a DeflateStream and uses a StreamReader on it - this code works fine in .NET Framework, .NET Core 3.1, and .NET 5 - but it breaks in .NET 6.

When trying to Peek() on the stream, internally StreamReader reads a block out that ends up being smaller than it requested, I'm pretty sure this is due to [this breaking change](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams).  After that happens, it sets a flag called "_isBlocked" and starts returning -1 from Peek() which is not expected.

This seems like a bug in StreamReader?

### Reproduction Steps

Construct a StreamReader over a DeflateStream
Read for a while, peeking as you go

### Expected behavior

Peek() returns -1 only at the end of the stream, as it did before

### Actual behavior

Peek() returns -1 early in the middle of the file.

### Regression?

Yes, regressed in .NET 6

### Known Workarounds

Can use StreamReader.EndOfStream instead of looking for -1 from Peek(), but this was still a difficult to hunt down bug on upgrading the .NET version of this library.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jozkee**
Fixes https://github.com/dotnet/runtime/issues/68983

The bug was uncovered by the [partial and zero-byte reads in DeflateStream](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams) breaking change i.e: the bug is not a regression.

### CODE REVIEW

File: src/libraries/Common/tests/System/IO/ReadOneAtATimeStream.cs [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+            _memoryStream.ReadExactly(buffer, offset, 1);
+            return 1;
+        }
+
+        public override void Flush() { }
+        public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();
+        public override void SetLength(long value) => throw new NotSupportedException();
+        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();
+    }
```
Comment (stephentoub) [inline src/libraries/Common/tests/System/IO/ReadOneAtATimeStream.cs:44]: Could you simplify this by just deriving from MemoryStream instead of Stream?

Comment (stephentoub) [reply src/libraries/Common/tests/System/IO/ReadOneAtATimeStream.cs:44]: We also have a DelegateStream type in tests; it lets you just construct an instance, supplying the ctor with a delegate to use for various operations, so you might not even have to declare your own type.  And if you do continue to have your own, assuming you derive from MemoryStream such that it can be really short, you could just make it a private nested class right next to the test that's using it.

**Review by stephentoub — APPROVED** [review]
