### PR TITLE
Include condition inside assert for forward jump loops

### LINKED ISSUE #51084: Assertion failed 'igInLoop->igLoopBackEdge == igLoopHeader'
https://dev.azure.com/dnceng/public/_build/results?buildId=1082263&view=ms.vss-test-web.build-test-results-tab&runId=33189076&resultId=176802&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

System.IO.Packaging.Tests 

net6.0-Linux-Release-x64-CoreCLR_checked-jitstress1-Ubuntu.1804.Amd64.Open

```
+ grep COMPlus
COMPlus_TieredCompilation=0
COMPlus_JitStress=1
COMPlus_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
COMPlus_DbgEnableMiniDump=1
+ ./RunTests.sh --runtime-path /home/helixbot/work/A9AD091A/p
----- start Sun Apr 11 08:46:01 UTC 2021 =============== To repro directly: =====================================================
pushd .
/home/helixbot/work/A9AD091A/p/dotnet exec --runtimeconfig System.IO.Packaging.Tests.runtimeconfig.json --depsfile System.IO.Packaging.Tests.deps.json xunit.console.dll System.IO.Packaging.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
~/work/A9AD091A/w/B50009D1/e ~/work/A9AD091A/w/B50009D1/e
  Discovering: System.IO.Packaging.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.Packaging.Tests (found 146 of 147 test cases)
  Starting:    System.IO.Packaging.Tests (parallel test collections = on, max threads = 2)

Assert failure(PID 9947 [0x000026db], Thread: 9959 [0x26e7]): Assertion failed 'igInLoop->igLoopBackEdge == igLoopHeader' in 'System.IO.Packaging.Tests.Tests:T035_ModifyAllPackageProperties():this' during 'Generate code' (IL size 1137)

    File: /__w/1/s/src/coreclr/jit/emit.cpp Line: 4694
    Image: /home/helixbot/work/A9AD091A/p/dotnet

Gathering state for process 9947 dotnet
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.9947.dmp
Written 132050944 bytes (32239 pages) to core file
Dump successfully written
./RunTests.sh: line 162:  9947 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.IO.Packaging.Tests.runtimeconfig.json --depsfile System.IO.Packaging.Tests.deps.json xunit.console.dll System.IO.Packaging.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
~/work/A9AD091A/w/B50009D1/e
----- end Sun Apr 11 08:46:11 UTC 2021 ----- exit code 134 ----------------------------------------------------------

```

### PR DESCRIPTION
**Pull request by kunalspathak**
Loop alignment is done for loops that are formed when we see a backward jump to the loop top. Sometimes, register allocation's resolution can insert a block in middle which might change the loop to the following form:

```
IG05:
    ...
    jmp IG18
...
...
IG18:
   ...
   jne IG05
```

For such cases, through basic block analysis, we think that we need to add `align` instruction inside `IG17` to align the loop that starts at `IG18`, but when we try to set the backedge of the loop (to calculate loop size), we cannot do that because we haven't generated those IGs. In above example, since `IG05->IG18` is a forward jump and hence we cannot set the backedge because `IG18` is not yet generated.

When we calculate loop size, if we encounter an IG that needs alignment, we had an `assert` that made sure that IG is the last one and points to a valid loop header. However, like above example, we can also have an IG inside a loop that was marked as "need alignment", but we never set its backedge and hence it won't match with any loop header. The fix was to include that condition inside the assert. To calculate `loopSize` of such loops, we would just iterate over all the IGs until we meet `loopSize` threshold, after which we will break out from loop size calculation and decide not to align the loop.

I have added little description around the assert to make sure that we remember all the scenarios.

Fixes: https://github.com/dotnet/runtime/issues/51084

### CODE REVIEW

**Comment by kunalspathak** [comment]
jitstress failures are unrelated.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/codegenlinear.cpp [hunk 1]
```diff
@@ -366,6 +366,8 @@ void CodeGen::genCodeForBBlist()
 
             block->bbEmitCookie = GetEmitter()->emitAddLabel(gcInfo.gcVarPtrSetCur, gcInfo.gcRegGCrefSetCur,
                                                              gcInfo.gcRegByrefSetCur, FALSE);
+            JITDUMP("Mapped " FMT_BB " to G_M%03u_IG%02u\n", block->bbNum, compiler->compMethodID,
```
Comment (BruceForstall) [inline src/coreclr/jit/codegenlinear.cpp:369]: Do we need this dump? We already dumped the block we're generating, and emitAddLabel dumps the IG#.

In particular, I don't want anyone outside of the emitter to access `emitCurIG`

**Review by BruceForstall — CHANGES_REQUESTED** [review]

File: src/coreclr/jit/codegenlinear.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/codegenlinear.cpp:369]: Yes, the mapping is spread out in the dump. 

```
=============== Generating BB01 [000..013), preds={} succs={BB02} flags=0x00000002.204b0020: i label target hascall gcsafe newobj LIR 
BB01 IN (1)={V99        } + ByrefExposed + GcHeap
     OUT(3)={V99 V03 V02} + ByrefExposed + GcHeap

Recording Var Locations at start of BB01
  <none>

Change life 000000000000000000000000000000000000000000000000 {} -> 000000000000000000000000000000000000800000000000 {V99}
							Live regs: (unchanged) 00000000 {}
							GC regs: (unchanged) 00000000 {}
							Byref regs: (unchanged) 00000000 {}

      L_M46582_BB01:
Label: IG02,
```

During diagnosis, it is easier to get all the mappings so we can relate the IGs to BBs. With my change, we can just search for "Mapped BB" in entire jit dump and get all the mappings. If we do not want to expose `emitCurIG`, I can probably pass `bbNum` as `DEBUG_ARG()` to `emitAddLabel()`?

Comment (BruceForstall) [reply src/coreclr/jit/codegenlinear.cpp:369]: debug arg would be ok. Maybe you can change `BOOL isFinallyTarget` to `bool isFinallyTarget` at the same time.

But hopefully we don't have to pass `isFinallyTarget` at all call sites. Maybe add overloads:

```
 void* emitter::emitAddLabel(VARSET_VALARG_TP GCvars, regMaskTP gcrefRegs, bool isFinallyTarget = false, regMaskTP byrefRegs DEBUG_ARG(unsigned bbNum = 0))
{
...
}
 void* emitter::emitAddLabel(VARSET_VALARG_TP GCvars, regMaskTP gcrefRegs, regMaskTP byrefRegs DEBUG_ARG(unsigned bbNum))
{
  return emitAddLabel(GCvars, gcrefRegs, byrefRegs, false DEBUG_ARG(bbNum));
}
```

?

Comment (kunalspathak) [reply src/coreclr/jit/codegenlinear.cpp:369]: Looks like `isFinallyTarget` is never `true` for Arm and thus will never set `IGF_FINALLY_TARGET`. Is that an oversight or did we stop using it at one point but didn't delete the code? @AndyAyersMS

Comment (kunalspathak) [reply src/coreclr/jit/codegenlinear.cpp:369]: Alright, I deleted `IGF_FINALLY_TARGET` and code around it.

Comment (AndyAyersMS) [reply src/coreclr/jit/codegenlinear.cpp]: I'm not familiar with `IGF_FINALLY_TARGET` -- Bruce probably knows.

Comment (BruceForstall) [reply src/coreclr/jit/codegenlinear.cpp]: No, please don't delete the `IGF_FINALLY_TARGET` code.

Unfortunately, you have accidentally found a small GC hole in our arm32 codegen that has existed since the beginning of RyuJIT/arm32 (I presume the reason we added that code still exists). We need to call emitAddLabel in genCodeForBBlist() as:
```
block->bbEmitCookie = GetEmitter()->emitAddLabel(gcInfo.gcVarPtrSetCur, gcInfo.gcRegGCrefSetCur,
                                                 gcInfo.gcRegByrefSetCur,
#if FEATURE_EH_FUNCLETS && defined(TARGET_ARM)
                                           /*isFinally*/ block->bbFlags & BBF_FINALLY_TARGET
#else
                                           FALSE
#endif
                                            );
```

This code never got ported over from the legacy codegen. I wonder what the GC info diffs for arm32 will show...

Of course, this is a separate issue; you shouldn't do it as part of this change.

Comment (BruceForstall) [reply src/coreclr/jit/codegenlinear.cpp]: I created https://github.com/dotnet/runtime/issues/51289 to track this.

Comment (kunalspathak) [reply src/coreclr/jit/codegenlinear.cpp]: Thanks! I went ahead and reverted that commit. For now, I have just added `DEBUG_ARG(bbNum)` without creating an overloaded method. Hopefully when we address #51289 , we will do it properly.

**Comment by kunalspathak** [comment]
The failure seems intermittent. @BruceForstall , let me know if there is anything more to add.

**Review by BruceForstall — APPROVED** [review]
