### PR TITLE
Normalize TYP_STRUCT to TYP_SIMD in impInlineUnboxNullable

### LINKED ISSUE #116369: JIT: Assertion failed 'layout->GetType() == TYP_STRUCT' during 'Morph - Inlining'
```csharp
// Generated by Fuzzlyn v3.3 on 2025-06-06 10:21:46
// Run on X64 Windows
// Seed: 1256851873714619775-async,vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86pclmulqdqv256,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 14.5 KiB to 0.3 KiB in 00:00:21
// Hits JIT assert for Release:
// Assertion failed 'layout->GetType() == TYP_STRUCT' in 'System.Threading.AsyncLocal`1[System.Nullable`1[System.Runtime.Intrinsics.Vector128`1[int]]]:get_Value():System.Nullable`1[System.Runtime.Intrinsics.Vector128`1[int]]:this' during 'Importation' (IL size 44; hash 0x78887c0d; FullOpts)
//
//     File: C:\dev\dotnet\runtime3\src\coreclr\jit\gentree.cpp Line: 8641
//
using System.Threading;
using System.Runtime.Intrinsics;

public class Program
{
    public static AsyncLocal<Vector128<int>?> s_asyncLocal7 = new AsyncLocal<Vector128<int>?>();
    public static void Main()
    {
        Vector128<int> vr0 = s_asyncLocal7.Value ??= Vector128.Create<int>(0);
    }
}
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/116369

### CODE REVIEW

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -2934,18 +2934,20 @@ GenTree* Compiler::impInlineUnboxNullable(CORINFO_CLASS_HANDLE nullableCls, GenT
...
     //  result._value = MethodTableLookup(obj);
     //
-    CORINFO_FIELD_HANDLE valueFldHnd = info.compCompHnd->getFieldInClass(nullableCls, 1);
-    CORINFO_CLASS_HANDLE valueStructCls;
-    var_types            valueType = JITtype2varType(info.compCompHnd->getFieldType(valueFldHnd, &valueStructCls));
+    CORINFO_FIELD_HANDLE valueFldHnd    = info.compCompHnd->getFieldInClass(nullableCls, 1);
+    CORINFO_CLASS_HANDLE valueStructCls = NO_CLASS_HANDLE;
+    ClassLayout*         layout         = nullptr;
+    var_types            valueType =
+        TypeHandleToVarType(info.compCompHnd->getFieldType(valueFldHnd, &valueStructCls), valueStructCls, &layout);
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp]: The evaluation order of args is implementation defined in C++. That might be the reason for the failures, since the `getFieldType` call needs to happen before the `valueStructCls` arg.

Comment (EgorBo) [reply src/coreclr/jit/importer.cpp]: I haven't checked the failures yet, but it does look to be the problem 

image

Comment (EgorBo) [reply src/coreclr/jit/importer.cpp]: Yeah, that was it, thanks!

**Comment by EgorBo** [comment]
@dotnet/jit-contrib PTAL simple change, the previous code was attempting to create a `STORE_BLK<TYP_STRUCT>` for a layout being SIMD,

[Zero diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1061239&view=ms.vss-build-web.run-extensions-tab)

**Review by jakobbotsch — APPROVED** [review]
