### PR TITLE
ARM64-SVE: Allow SVE ops to re-use the same registers

### LINKED ISSUE #106866: JIT SVE: Assertion failed '(targetReg == op1Reg) || (targetReg != op3Reg)' during 'Generate code'
```csharp
// Generated by Fuzzlyn v2.3 on 2024-08-23 10:04:52
// Run on Arm64 Windows
// Seed: 12028719405363964033-vectort,vector64,vector128,armsve
// Reduced from 60.4 KiB to 0.7 KiB in 00:00:33
// Hits JIT assert in Release:
// Assertion failed '(targetReg == op1Reg) || (targetReg != op3Reg)' in 'S0:M3():this' during 'Generate code' (IL size 57; hash 0x4541fc9f; FullOpts)
//
//     File: C:\dev\dotnet\runtime2\src\coreclr\jit\hwintrinsiccodegenarm64.cpp Line: 1128
//
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public struct S0
{
    public bool F0;
    public Vector<sbyte> F2;
    public void M3()
    {
        var vr0 = this.F2;
        var vr1 = this.F2;
        var vr2 = this.F2;
        this.F2 = Sve.Splice(vr0, vr1, vr2);
        Program.s_rt.WriteLine(this.F0);
    }
}

public class Program
{
    public static IRuntime s_rt;
    public static void Main()
    {
        new S0().M3();
    }
}

public interface IRuntime
{
    void WriteLine<T>(T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(T value) => System.Console.WriteLine(value);
}
```

cc @dotnet/arm64-contrib @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by a74nh**
Fixes #106866

RMW intrinsics can use the RMW register in other inputs. The only restriction is that those inputs will be overwritten.

Added extra intrinsic testing to cover this. Requires #107036 for all the tests to pass.

### CODE REVIEW

**Comment by a74nh** [comment]
@dotnet/arm64-contrib @kunalspathak

**Comment by a74nh** [comment]
Given the discussions over in #107036, I think this PR is correct.

For this case we have:

```
Generating: N017 (  1,  1) [000033] -----+-----                   t33 =    LCL_VAR   simd16 V07 tmp6         u:2 d0 REG d0 $80
Generating: N019 (  1,  1) [000034] -----+-----                   t34 =    LCL_VAR   simd16 V07 tmp6         u:2 d0 (last use) REG d0 $80
                                                                        /--*  t37    mask
                                                                        +--*  t33    simd16
                                                                        +--*  t34    simd16
Generating: N021 (  6,  6) [000035] -----+-----                   t35 = *  HWINTRINSIC simd16 byte Splice REG d0 $240
							V07 in reg d0 is becoming dead  [000034]
							Live regs: 0000000100000000 {d0} - {d0} => 0000000000000000 {}
							Live vars after [000034]: {V07} -{V07} => {}
IN0004:             splice  z0.b, p0, z0.b, z0.b
```

Like in the previous PR, we have the same value used twice. But here we are not going to use a `MOVPRFX` (due to it not being wrapped with conditional select). Therefore we have no requirement to delay free the operands, and can simply allow the same one to be used.

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp [hunk 1]
```diff
@@ -1106,7 +1106,6 @@ void CodeGen::genHWIntrinsic(GenTreeHWIntrinsic* node)
                     }
                     else if (isRMW)
                     {
-                        assert((targetReg == op1Reg) || (targetReg != op2Reg));
```
Comment (kunalspathak) [inline src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1109]: as we spoke offline, did you verify if we put this assert back, do we hit them. These asserts were added conservatively with the idea that we understand the scenario under which this cannot be true. I am wondering if we should remove these as we see scenarios that trigger them.

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp [hunk 2]
```diff
@@ -1124,18 +1123,12 @@ void CodeGen::genHWIntrinsic(GenTreeHWIntrinsic* node)
...
-                            assert((targetReg == op1Reg) || (targetReg != op1Reg));
-                            assert((targetReg == op1Reg) || (targetReg != op3Reg));
-
                             GetEmitter()->emitIns_Mov(INS_mov, emitTypeSize(node), targetReg, op2Reg,
                                                       /* canSkip */ true);
                             GetEmitter()->emitIns_R_R_R(ins, emitSize, targetReg, op1Reg, op3Reg, opt);
                         }
                         else
                         {
-                            assert((targetReg == op1Reg) || (targetReg != op2Reg));
```
Comment (kunalspathak) [inline src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1136]: same with these two.

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp [hunk 3]
```diff
@@ -1124,18 +1123,12 @@ void CodeGen::genHWIntrinsic(GenTreeHWIntrinsic* node)
                     {
                         if (HWIntrinsicInfo::IsExplicitMaskedOperation(intrin.id))
                         {
-                            assert((targetReg == op1Reg) || (targetReg != op1Reg));
```
Comment (kunalspathak) [inline src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1127]: these are OK to have.

**Review by kunalspathak — CHANGES_REQUESTED** [review]
I am not totally convinced that we should be removing all the asserts without seeing a case that hits it. Its ok to put some of them back for now and relax them as we see cases.

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp (hunk 3 above)
Comment (a74nh) [reply src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1127]: These ones are hit by the new hwintrinsic tests:

```
------------------- {'JitStressRegs': '1'} -------------------
Errors:

Assert failure(PID 366410 [0x0005974a], Thread: 366410 [0x5974a]): Assertion failed '(targetReg == op1Reg) || (targetReg != op3Reg)' in 'JIT.HardwareIntrinsics.Arm._Sve.SimpleTernaryOpTest__Sve_ConditionalExtractAfterLastActiveElementAndReplicate_float:RunSameClassFldScenario():this' during 'Generate code' (IL size 92; hash 0xa42df59e; FullOpts)

    File: /home/alahay01/dotnet/runtime_sve_api/src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1118
    Image: /home/alahay01/dotnet/runtime_sve_api/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun
```

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp (hunk 1 above)
Comment (a74nh) [reply src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1109]: Restored this one

**Comment by a74nh** [comment]
Stress tests working with the latest version

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp (hunk 3 above)
Comment (tannergooding) [reply src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1117]: We need some kind of assert validating the `mov` is valid.

Since we're doing `mov targetReg, op2Reg`, then when `targetReg == op1Reg` and `op1Reg != op2Reg`, then the we would overwrite `op1` and produce in incorrect results.

So, therefore, we expect that `targetReg == op2Reg` so no `mov` is emitted.

The assert therefore needs to be something like `assert((targetReg == op2Reg) || ((targetReg != op1Reg) && (targetReg != op3Reg))`. Which validates `no move` or `no overwrite`

Comment (tannergooding) [reply src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1117]: All paths need some kind of similar assert validating `no move` or `no overwrite, if a move is emitted`

Comment (kunalspathak) [reply src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1117]: > All paths need some kind of similar assert validating `no move` or `no overwrite, if a move is emitted`

Agree.

Comment (a74nh) [reply src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1117]: Done replaced this assert as suggested, and the next one with a similar assert

Comment (a74nh) [reply src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1117]: confirmed stress tests passing.

**Review by kunalspathak — APPROVED** [review]
LGTM
