### PR TITLE
Annotate `System.ComponentModel.SyntaxCheck` as null-tolerant

### LINKED ISSUE #119582: [API Proposal]: `System.ComponentModel.SyntaxCheck.CheckMachineName` should accept a null argument
### Background and motivation

`SyntaxCheck.CheckMachineName` currently returns `false` for a `null` argument. It would be useful to see this reflected in the nullability annotations.

### API Proposal

```diff
namespace System.ComponentModel;

public class SyntaxCheck
{
-   public bool CheckMachineName(string value);
+   public bool CheckMachineName([NotNullWhen(true)] string? value);
}
```

### API Usage

```C#
void Validate([NotNull] string? machineName)
{
    if (!SyntaxCheck.CheckMachineName(machineName))
    {
        throw new InvalidOperationException("Value must be a machine name");
    }
}
```

### Alternative Designs

_No response_

### Risks

_No response_

### PR DESCRIPTION
**Pull request by RenderMichael**
Fixes https://github.com/dotnet/runtime/issues/119582

### CODE REVIEW

File: src/libraries/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs [hunk 1]
```diff
@@ -285,6 +285,7 @@ public abstract partial class CustomTypeDescriptor : System.ComponentModel.ICust
     {
         protected CustomTypeDescriptor() { }
         protected CustomTypeDescriptor(System.ComponentModel.ICustomTypeDescriptor? parent) { }
+        public virtual bool? RequireRegisteredTypes { get { throw null; } }
```
Comment (RenderMichael) [inline src/libraries/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs]: A few reordering changes got pulled in when I ran `dotnet msbuild /t:GenerateReferenceAssemblySource`. I can revert if that's preferred.

Comment (stephentoub) [reply src/libraries/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs]: > I can revert if that's preferred.

Please, thanks.

We should separately clean up the refs to be up-to-date with the tool's output. Feel free to open an issue for that.

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
Thanks
