### PR TITLE
Fix reporting of foreign native exception not handled by runtime

### LINKED ISSUE #115654: UnhandledException fires when unmanaged exception thrown from managed catch block C++/CLI .NET 9
### Description

C++/CLI code. If I throw an unmanaged exception from the `catch` block that handles a managed exception, an uncatchable SEHException is thrown and triggers the UnhandledException event handler of AppDomain. It is impossible (AFAIK) to detect whether this exception will terminate the application, because UnhandledExceptionEventArgs::IsTerminating is always true.

This is probably due to the new exception handling introduced in .NET 9, but setting DOTNET_LegacyExceptionHandling does not change this behavior.

### Reproduction Steps

```
#pragma once

using namespace System;

#include "pch.h"
#include <stdexcept>
#include <iostream>

using namespace System;

#pragma managed
void Handler(Object^ sender, UnhandledExceptionEventArgs^ e) {
    if (e->IsTerminating) {
        Console::WriteLine("Terminating");
    }
    Console::WriteLine("Printing exception object:");
    Console::WriteLine(e->ExceptionObject);
}

#pragma managed
void ManagedCodeCatchesManagedAndThrowsUnmanaged() {
    AppDomain::CurrentDomain->UnhandledException += gcnew UnhandledExceptionEventHandler(&Handler);
    try {
        Console::WriteLine(Environment::Version);
        throw gcnew System::Exception("managed exception!");
    }
    catch (System::Exception^ e) {
        Console::WriteLine("Caught managed exception");
        Console::WriteLine(e->Message);
        throw std::runtime_error("unmanaged error!");
    }
}

#pragma unmanaged
extern "C" __declspec(dllexport) int main()
{
    try {
        ManagedCodeCatchesManagedAndThrowsUnmanaged();
    }
    catch (const std::runtime_error& e) {
        std::cout << "caught unmanaged exception:" << std::endl;
        std::cout << e.what() << std::endl;
    }
    return 0;
}
```

I couldn't manage to run this directly from Visual Studio, but I did create a C++ application that dynamically loads this library and invokes its main method. Here's the output with .NET 8:

```
8.0.15
Caught managed exception
managed exception!
caught unmanaged exception:
unmanaged error!
```

Here's the output from the .NET 10 preview (but it also happens with .NET 9):

```
10.0.0
Caught managed exception
managed exception!
Terminating
Printing exception object:
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at UnmanagedCodeThrows()
   at ManagedCodeCatchesManagedAndThrowsUnmanaged() in C:\Users\samcook\source\repos\CppCliLib\CppCliLib\CppCliLib.h:line 35
Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at UnmanagedCodeThrows()
   at ManagedCodeCatchesManagedAndThrowsUnmanaged() in C:\Users\samcook\source\repos\CppCliLib\CppCliLib\CppCliLib.h:line 35
caught unmanaged exception:
unmanaged error!
```

### Expected behavior

No SEHException should be thrown.

### Actual behavior

An uncatchable SEHException is thrown and triggers the UnhandledException event handler.

### Regression?

Yes. This workflow is fine in .NET Framework and up to/including .NET 8.

### Known Workarounds

There are no workarounds. This prevents all MATLAB users from using .NET 9 and higher versions.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by janvorli**
When a native exception occurs on a foreign thread, it is propagated through managed frames and then flows into the foreign native frames and is handled there, the runtime still reports the exception as unhandled via `AppDomain.CurrentDomain.UnhandledException` event and also prints out the unhandled exception message. Even though the process then continues running just fine.

This change fixes the behavior so that only managed exceptions thrown by the .NET runtime are reported as unhandled in such case. Foreign exceptions, like e.g. C++ exceptions, are not reported as unhandled and they are just propagated into the foreign native frames. If that exception is not handled by the native frames, then C++ reports them as unhandled.

I have also added a test that fails without this fix.

Close #115654

### CODE REVIEW

File: src/tests/baseservices/exceptions/exceptioninterop/ExceptionInteropNative.cpp [hunk 1]
```diff
@@ -33,3 +39,22 @@ extern "C" DLL_EXPORT void InvokeCallbackCatchCallbackAndRethrow(PFNACTION1 call
     }
 }
 
+#ifdef _WIN32
+extern "C" DLL_EXPORT void InvokeCallbackAndCatchNative(PFNACTION1 callback)
```
Comment (jkoritzinsky) [inline src/tests/baseservices/exceptions/exceptioninterop/ExceptionInteropNative.cpp:43]:
```suggestion
extern "C" DLL_EXPORT void STDMETHODCALLTYPE InvokeCallbackAndCatchNative(PFNACTION1 callback)
```

File: src/tests/baseservices/exceptions/exceptioninterop/ExceptionInteropNative.cpp [hunk 2]
```diff
@@ -33,3 +39,22 @@ extern "C" DLL_EXPORT void InvokeCallbackCatchCallbackAndRethrow(PFNACTION1 call
...
+    {
+        callback();
+    }
+    catch (std::exception& ex)
+    {
+        printf("Caught exception %s in native code\n", ex.what());
+    }
+}
+
+extern "C" DLL_EXPORT void InvokeCallbackOnNewThread(PFNACTION1 callback)
```
Comment (jkoritzinsky) [inline src/tests/baseservices/exceptions/exceptioninterop/ExceptionInteropNative.cpp:55]:
```suggestion
extern "C" DLL_EXPORT void STDMETHODCALLTYPE InvokeCallbackOnNewThread(PFNACTION1 callback)
```

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by janvorli** [comment]
There are some failures in the outerloop tests, I need to investigate if they are possibly related or not.

**Comment by janvorli** [comment]
The outerloop failure is #106675
