### PR TITLE
Fix TraceSwitch to synchronize the Value and Level properties

### LINKED ISSUE #83153: TraceSwitch can have inconsistent internal state
### Description

`TraceSwitch` class is inherited from `Switch` class. `Switch` class has a property called `Value` which used to be a protected property in .NET 6.0 and became a public property in .NET 7.0. If the user creates `TraceSwitch` object and then call `Value` property. This operation will reflect also on the property `Level`. In other meaning, `Value` and `Level` must be in-sync. 
The problem is when the user set the `Level` property, this operation will not affect the `Value` property and the internal state of the object will have inconsistency. 

This problem is affecting users who use TraceSwitch with the configuration. You may look at the issue https://github.com/dotnet/runtime/issues/82998 for the details how this problem is affecting the configuration. 

### Reproduction Steps

```C#
            TraceSwitch ts = new TraceSwitch("Name", "Description");
            Console.WriteLine($"Level: {ts.Level}, Value: {ts.Value}"); // Level: Off, Value: 0

            ts.Value = "1"; // Error value
            Console.WriteLine($"Level: {ts.Level}, Value: {ts.Value}"); // Level: Error, Value: 1. Level is changed according to the Value

            ts.Level = TraceLevel.Info;
            Console.WriteLine($"Level: {ts.Level}, Value: {ts.Value}"); // Level: Info, Value: 1. Value didn't change :-(
```

### Expected behavior

When changing the `Level` it should get reflected on the `Value` and vice versa. 

### Actual behavior

When changing the `Level` it is not affecting the `Value` property.

### Regression?

After Exposing `Value` property in .NET 7.0 and not synchronizing the `Level` and `Value` values, this had a side effect on the configuration and causing a regression. The issue https://github.com/dotnet/runtime/issues/82998 has more details about this regression.

### Known Workarounds

For configuration regression, can set the `Value` and `Level` in the configuration. Look at the comment https://github.com/dotnet/runtime/issues/82998#issuecomment-1455341742 for more details.

### Configuration

.NET 7.0 on any OS with any architecture. 

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/83153

### CODE REVIEW

File: src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs [hunk 1]
```diff
@@ -165,6 +165,12 @@ protected int SwitchSetting
 
         protected internal virtual string[]? GetSupportedAttributes() => null;
 
+        internal void SetSwitchValueString(string switchValueString)
+        {
+            Debug.Assert(switchValueString is not null, "switchValueString != null");
```
Comment (stephentoub) [inline src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs:170]: Nit: If the assert fires, switchValueString == null rather than != null

File: src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs [hunk 2]
```diff
@@ -94,6 +95,13 @@ protected override void OnSwitchSettingChanged()
         protected override void OnValueChanged()
         {
             SwitchSetting = (int)Enum.Parse<TraceLevel>(Value, true);
+
+            Debug.Assert(Value.Length > 0, "Value.Length > 0");
+            if (char.IsDigit(Value[0]))
+            {
+                // Convert digit value representation to TraceLevel representation
+                SetSwitchValueString(((TraceLevel)SwitchSetting).ToString());
```
Comment (stephentoub) [inline src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs:103]: I'm not following the logic here... why do we only do this if Value begins with a number?

**Comment by tarekgh** [comment]
@ViktorHofer @stephentoub any other feedback here?

**Comment by tarekgh** [comment]
@carlossanlop do you want to look at this change as @ViktorHofer is not available?

File: src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs (hunk 2 above)
Comment (carlossanlop) [reply src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs:103]: Yes, but `SetSwitchValueString` should also be also called if the user sets `Value` to "Off", "Error", "Warning", "Info" or "Verbose". With the code as it is right now, `SetSwitchValueString` will only be called if the user sets `Value` to "0", "1", "2", "3" or "4".

Related question: Why would we allow this?:
```cs
mySwitch.Value = "1";
```

if the user can set the number via the `Level`?
```cs
mySwitch.Level = 1;
```

Shouldn't we only allow `Value` to be set to "Off", "Error", "Warning", "Info" and "Verbose", and not the integer representation of their enum value?

Comment (tarekgh) [reply src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs:103]: @carlossanlop `TraceSwitch` is wrapping the `TraceLevel` enum. If we restrict the `Value` to enume field names, this will be a breaking change and wouldn't be logical too as the runtime allows parsing numeric values.

Comment (carlossanlop) [reply src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs:103]: Okay, no need to restrict. But still, this needs fixing:

> Yes, but SetSwitchValueString should also be also called if the user sets Value to "Off", "Error", "Warning", "Info" or "Verbose". With the code as it is right now, SetSwitchValueString will only be called if the user sets Value to "0", "1", "2", "3" or "4".

Comment (tarekgh) [reply src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs:103]: > SetSwitchValueString should also be also called if the user sets Value to "Off", "Error", "Warning", "Info" or "Verbose". With the code as it is right now, SetSwitchValueString will only be called if the user sets Value to "0", "1", "2", "3" or "4".

Users call `Value` property to set these values. 

https://github.com/dotnet/runtime/blob/587b0ad50e805e3467533e84e2bb3383f6b72824/src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs#L183

For example, if you set the value to `Error`, this value will be stored in `_switchValueString` which same value returned from the property getter. So, there is no need to call `SetSwitchValueString` at that time because the right value is already there. If the user instead set the value to `1`, at that time `_switchValueString` will store this value. We'll need to change this value to `Error` and this is why I am calling `SetSwitchValueString` to reset `_switchValueString`.

Comment (carlossanlop) [reply src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs:103]: Ah okay, I see it now. Thanks for clarifying it.

**Review by carlossanlop — APPROVED** [review]

File: src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs (hunk 2 above)
Comment (stephentoub) [reply src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs:103]: What happens if the user sets the value to a number that's not mapped to a named value?

What `char.IsDigit(Value[0])` is false because the text was padded with whitespace?

Comment (tarekgh) [reply src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSwitch.cs]: I have addressed these fantastic questions with the latest commit [`985943c` (#89278)](https://github.com/dotnet/runtime/pull/89278/commits/985943c06b1e08b3938fa9da71e2a548d5703417). 

> What happens if the user sets the value to a number that's not mapped to a named value?

Now I am calling ` OnSwitchSettingChanged()` to let it normalize the value. This will make it match the behavior of the `Level` property. It is a good catch you raised it. 

> What if char.IsDigit(Value[0]) is false because the number was padded with whitespace?

I didn't know that `Enum.Parse` trim the white spaces when parsing. With the new change, I am calling `SetSwitchValueString` anyway to ensure always updating the string value. Thanks for the catch too.

File: src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs [hunk 3]
```diff
@@ -165,6 +165,12 @@ protected int SwitchSetting
 
         protected internal virtual string[]? GetSupportedAttributes() => null;
 
+        internal void SetSwitchValueString(string switchValueString)
+        {
+            Debug.Assert(switchValueString is not null, "Unexpected 'switchValueString' null value");
+            _switchValueString = switchValueString;
```
Comment (stephentoub) [inline src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs:171]: There's a lock inside of SwitchSetting, and this write is not a part of it.  What are the guarantees around multithreaded access to these settings?  Is it possible _switchSetting and _switchValueString could become inconsistent with each other, and what would happen in that case?

Comment (tarekgh) [reply src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs:171]: I am not seeing these classes are documented as thread safe. Even looking at the `Value` property setterhttps://github.com/dotnet/runtime/blob/2427b67722a40fed059241de920b17d9fe8c82b3/src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs#L183 it is not protected with the lock which set the possibility of inconsistency regardless of which is extending this Switch class.

I can see the same issue with the `BooleanSwitch` here 
https://github.com/dotnet/runtime/blob/2427b67722a40fed059241de920b17d9fe8c82b3/src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/BooleanSwitch.cs#L48 which is possible the Value and the Enabled property can get inconsistent in the multi-threading scenarios. 

I am not sure if we need to fix all the multi-threading issues with this PR.

Comment (tarekgh) [reply src/libraries/System.Diagnostics.TraceSource/src/System/Diagnostics/Switch.cs]: @stephentoub 
I have addressed the multip-threading issue with the comment [`6effd1d` (#89278)](https://github.com/dotnet/runtime/pull/89278/commits/6effd1dde196ee8f28565cf513240e7e3ad67174). Please have a look and let me know if you have any more comments. Thanks!
