### PR TITLE
Jitstress fixes for tailcall tests

### LINKED ISSUE #1752: JIT\Directed\tailcall fails at runtime with jitstress=2
```
Stack overflow.
Return code: 1
BEGIN EXECUTION
 "C:\h\w\A59B0955\p\corerun.exe" tailcall.dll 
Test Start
Expected: 100
Actual: -1073741571
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Make STRESS_GENERIC_VARN more compatible with methods that make explicit tail
calls. Don't add gc checks for explicit tail calls, and remove the code in
morph that blocks tail calls if gc checks are active.

Update the tailcall test to to disable STRESS_UNSAFE_BUFFER_CHECKS. This can
be reverted when ~~#314~~ #341 is merged.

Fixes #1752.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Also fixes dotnet/coreclr#27658.

**Review by jashook — APPROVED** [review]

File: src/coreclr/src/jit/importer.cpp [hunk 1]
```diff
@@ -16246,11 +16246,21 @@ GenTree* Compiler::impAssignMultiRegTypeToVar(GenTree* op, CORINFO_CLASS_HANDLE
...
 #endif // FEATURE_MULTIREG_RET
 
-// do import for a return
-// returns false if inlining was aborted
-// opcode can be ret or call in the case of a tail.call
+//------------------------------------------------------------------------
+// impReturnInstruction: import a return or an explicit tail call
+//
+// Arguments:
+//     block -- call returning a struct in a registers
```
Comment (BruceForstall) [inline src/coreclr/src/jit/importer.cpp]: "in a registers"? grammar seems weird.

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/src/jit/importer.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/src/jit/importer.cpp]: Yikes, copy paste artifact from the method above.

Looks like `block` is unused so I'll just remove it entirely and fix up the caller.
