### PR TITLE
JIT: fix morph tail call copy opt alias analysis

### LINKED ISSUE #56734: Unable to run x86 tests
I'm currently running into issues when trying to run library tests locally for x86.

Steps to reproduce:

```shell
$ git checkout origin/main
$ git clean -xdf
$ git pull origin main
$ .\build.cmd clr+libs+libs.tests -c Release -test -a x86
```

Which results in the following error:

```
...
  NoSpecialEntryPointPatternThrows -> C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\NoSpecialEntryPointPatternThrows\net6.0-Release\NoSpecialEntryPointPatternThrows.dll
  CreateWebHostBuilderPatternTestSite -> C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\CreateWebHostBuilderPatternTestSite\net6.0-Release\CreateWebHostBuilderPatternTestSite.dll
  NoSpecialEntryPointPatternHangs -> C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\NoSpecialEntryPointPatternHangs\net6.0-Release\NoSpecialEntryPointPatternHangs.dll
  NoSpecialEntryPointPatternExits -> C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\NoSpecialEntryPointPatternExits\net6.0-Release\NoSpecialEntryPointPatternExits.dll
  CreateWebHostBuilderInvalidSignature -> C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\CreateWebHostBuilderInvalidSignature\net6.0-Release\CreateWebHostBuilderInvalidSignature.dll
  CreateHostBuilderPatternTestSite -> C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\CreateHostBuilderPatternTestSite\net6.0-Release\CreateHostBuilderPatternTestSite.dll
  NoSpecialEntryPointPattern -> C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\NoSpecialEntryPointPattern\net6.0-Release\NoSpecialEntryPointPattern.dll
  Microsoft.Extensions.Hosting.Functional.Tests -> C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\Microsoft.Extensions.Hosting.Functional.Tests\net6.0-Release\Microsoft.Extensions.Hosting.Functional.Tests.dll
  Microsoft.Extensions.HostFactoryResolver.Tests -> C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\Microsoft.Extensions.HostFactoryResolver.Tests\net6.0-Release\Microsoft.Extensions.HostFactoryResolver.Tests.dll
  Running tests: C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\ILCompiler.TypeSystem.ReadyToRun.Tests\x86\Release\ILCompiler.TypeSystem.ReadyToRun.Tests.dll [net6.0|x86]
XUnit : error : Tests failed: C:\Users\acovingt\source\repos\runtime-master\artifacts\TestResults\Release\ILCompiler.TypeSystem.ReadyToRun.Tests_net6.0_x86.html [net6.0|x86] [C:\Users\acovingt\source\repos\runtime-master\src\coreclr\tools\aot\ILCompiler.TypeSystem.ReadyToRun.Tests\ILCompiler.TypeSystem.ReadyToRun.Tests.csproj]

Build FAILED.

XUnit : error : Tests failed: C:\Users\acovingt\source\repos\runtime-master\artifacts\TestResults\Release\ILCompiler.TypeSystem.ReadyToRun.Tests_net6.0_x86.html [net6.0|x86] [C:\Users\acovingt\source\repos\runtime-master\src\coreclr\tools\aot\ILCompiler.TypeSystem.ReadyToRun.Tests\ILCompiler.TypeSystem.ReadyToRun.Tests.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:14:34.08
Build failed with exit code 1. Check errors above.
Some builds failed:
        Configuration: Release, Architecture: x86
```

`dotnet --info` output for more troubleshooting information:

```shell
$ dotnet --info
Host (useful for support):
  Version: 6.0.0-preview.4.21253.7
  Commit:  bfd6048a60

.NET SDKs installed:
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21328.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21253.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21253.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.4.21254.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Please let me know if I can provide any other information. Thanks!

### LINKED ISSUE #56743: JIT omits copy of aliased struct passed as implicit byref
```csharp
static void Foo(S h)
{
    h.H = &h;
    Bar(h);
}
 
struct S
{
    public long A, B;
    public S* H;
}
 
[MethodImpl(MethodImplOptions.NoInlining)]
static void Bar(S h)
{
}
```

Generates:
```
; Assembly listing for method Program:Foo(S)
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; fully interruptible
; No PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  5, 10   )   byref  ->  rcx         ld-addr-op single-def
;# V01 OutArgs      [V01    ] (  1,  1   )  lclBlk ( 0) [rsp+00H]   "OutgoingArgSpace"
;* V02 tmp1         [V02    ] (  0,  0   )    long  ->  zero-ref    do-not-enreg[] V05.A(offs=0x00) P-DEP "field V00.A (fldOffset=0x0)"
;* V03 tmp2         [V03    ] (  0,  0   )    long  ->  zero-ref    do-not-enreg[] V05.B(offs=0x08) P-DEP "field V00.B (fldOffset=0x8)"
;* V04 tmp3         [V04    ] (  0,  0   )    long  ->  zero-ref    do-not-enreg[] V05.H(offs=0x10) P-DEP "field V00.H (fldOffset=0x10)"
;* V05 tmp4         [V05    ] (  0,  0   )  struct (24) zero-ref    do-not-enreg[S] "Promoted implicit byref"
;
; Lcl frame size = 0
G_M25920_IG01:              ;; offset=0000H
                                                ;; bbWeight=1    PerfScore 0.00
G_M25920_IG02:              ;; offset=0000H
       48894910             mov      qword ptr [rcx+16], rcx
                                                ;; bbWeight=1    PerfScore 1.00
G_M25920_IG03:              ;; offset=0004H
       E94F3DFFFF           jmp      Program:Bar(S)
                                                ;; bbWeight=1    PerfScore 2.00
; Total bytes of code 9, prolog size 0, PerfScore 3.90, instruction count 2, allocated bytes for code 9 (MethodHash=ccee9abf) for method Program:Foo(S)
```

It does not seem right that `h.H == &h` inside of `Bar`.

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
If there are non-call references to an implicit byref local, disqualify
that local from morph tail call copy optimization.

The fix is conservative in that "harmless" non-call references like field
accesses will also disqualify the opt. This can be improved on with extra
analysis in local morph.

Closes #56743.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

There were 66 methods with diffs (almost all regressions), didn't look at them all, but suspect all are cases where we're now overly conservative.

## benchmarks.run.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 1157
Total bytes of diff: 1678
Total bytes of delta: 521 (45.03% of base)
Total relative delta: 7.31
    diff is a regression.
    relative diff is a regression.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         188 : 14755.dasm (391.67% of base)
         153 : 18364.dasm (50.83% of base)
          73 : 12645.dasm (243.33% of base)
          50 : 17879.dasm (11.34% of base)
          30 : 17903.dasm (15.71% of base)
          27 : 15374.dasm (18.49% of base)

6 total files with Code Size differences (0 improved, 6 regressed), 0 unchanged.

Top method regressions (bytes):
         188 (391.67% of base) : 14755.dasm - System.IO.Path:Join(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Char]):System.String
         153 (50.83% of base) : 18364.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData:CreateMetadataExpression(Microsoft.CodeAnalysis.TypedConstant,Microsoft.CodeAnalysis.Emit.EmitContext):Microsoft.Cci.IMetadataExpression:this
          73 (243.33% of base) : 12645.dasm - System.IO.Path:Join(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Char]):System.String
          50 (11.34% of base) : 17879.dasm - Microsoft.CodeAnalysis.CodeGen.ReferenceDependencyWalker:VisitReference(Microsoft.Cci.IReference,Microsoft.CodeAnalysis.Emit.EmitContext)
          30 (15.71% of base) : 17903.dasm - Microsoft.CodeAnalysis.SmallDictionary`2[__Canon,LabelInfo][System.__Canon,Microsoft.CodeAnalysis.CodeGen.ILBuilder+LabelInfo]:HandleInsert(AvlNode[__Canon,LabelInfo],AvlNode[__Canon,LabelInfo],System.__Canon,LabelInfo,bool):this
          27 (18.49% of base) : 15374.dasm - System.Convert:ToHexString(System.ReadOnlySpan`1[Byte]):System.String

Top method regressions (percentages):
         188 (391.67% of base) : 14755.dasm - System.IO.Path:Join(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Char]):System.String
          73 (243.33% of base) : 12645.dasm - System.IO.Path:Join(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Char]):System.String
         153 (50.83% of base) : 18364.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData:CreateMetadataExpression(Microsoft.CodeAnalysis.TypedConstant,Microsoft.CodeAnalysis.Emit.EmitContext):Microsoft.Cci.IMetadataExpression:this
          27 (18.49% of base) : 15374.dasm - System.Convert:ToHexString(System.ReadOnlySpan`1[Byte]):System.String
          30 (15.71% of base) : 17903.dasm - Microsoft.CodeAnalysis.SmallDictionary`2[__Canon,LabelInfo][System.__Canon,Microsoft.CodeAnalysis.CodeGen.ILBuilder+LabelInfo]:HandleInsert(AvlNode[__Canon,LabelInfo],AvlNode[__Canon,LabelInfo],System.__Canon,LabelInfo,bool):this
          50 (11.34% of base) : 17879.dasm - Microsoft.CodeAnalysis.CodeGen.ReferenceDependencyWalker:VisitReference(Microsoft.Cci.IReference,Microsoft.CodeAnalysis.Emit.EmitContext)

6 total methods with Code Size differences (0 improved, 6 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## coreclr_tests.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 30
Total bytes of diff: 107
Total bytes of delta: 77 (256.67% of base)
Total relative delta: 5.24
    diff is a regression.
    relative diff is a regression.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
          39 : 249559.dasm (300.00% of base)
          38 : 85326.dasm (223.53% of base)

2 total files with Code Size differences (0 improved, 2 regressed), 0 unchanged.

Top method regressions (bytes):
          39 (300.00% of base) : 249559.dasm - ImplicitByrefTailCalls:G(System.Span`1[Int32],bool):int
          38 (223.53% of base) : 85326.dasm - MS.VT:sub(MS.VT):MS.VT:this

Top method regressions (percentages):
          39 (300.00% of base) : 249559.dasm - ImplicitByrefTailCalls:G(System.Span`1[Int32],bool):int
          38 (223.53% of base) : 85326.dasm - MS.VT:sub(MS.VT):MS.VT:this

2 total methods with Code Size differences (0 improved, 2 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 8219
Total bytes of diff: 9929
Total bytes of delta: 1710 (20.81% of base)
Total relative delta: 33.63
    diff is a regression.
    relative diff is a regression.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         140 : 41163.dasm (46.51% of base)
          73 : 125201.dasm (304.17% of base)
          64 : 154830.dasm (266.67% of base)
          64 : 154829.dasm (266.67% of base)
          64 : 154831.dasm (266.67% of base)
          64 : 154828.dasm (266.67% of base)
          64 : 154832.dasm (266.67% of base)
          64 : 154833.dasm (266.67% of base)
          49 : 81251.dasm (13.39% of base)
          41 : 155095.dasm (95.35% of base)
          41 : 155094.dasm (95.35% of base)
          40 : 106749.dasm (24.39% of base)
          39 : 41218.dasm (13.45% of base)
          39 : 222921.dasm (60.94% of base)
          38 : 214403.dasm (30.16% of base)
          38 : 225607.dasm (90.48% of base)
          37 : 214405.dasm (19.68% of base)
          37 : 179631.dasm (23.27% of base)
          30 : 80971.dasm (96.77% of base)
          30 : 80142.dasm (96.77% of base)

Top file improvements (bytes):
         -40 : 7831.dasm (-4.95% of base)

58 total files with Code Size differences (1 improved, 57 regressed), 0 unchanged.

Top method regressions (bytes):
         140 (46.51% of base) : 41163.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData:CreateMetadataExpression(Microsoft.CodeAnalysis.TypedConstant,Microsoft.CodeAnalysis.Emit.EmitContext):Microsoft.Cci.IMetadataExpression:this
          73 (304.17% of base) : 125201.dasm - System.Net.Http.HttpConnection:ReadBufferedAsync(System.Memory`1[Byte]):System.Threading.Tasks.ValueTask`1[Int32]:this
          64 (266.67% of base) : 154833.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndBytes(System.ReadOnlySpan`1[Byte],System.ReadOnlySpan`1[Byte])
          64 (266.67% of base) : 154832.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndBytes(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Byte])
          64 (266.67% of base) : 154830.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndValue(System.ReadOnlySpan`1[Byte],System.ReadOnlySpan`1[Byte])
          64 (266.67% of base) : 154829.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndValue(System.ReadOnlySpan`1[Byte],System.ReadOnlySpan`1[Char])
          64 (266.67% of base) : 154828.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndValue(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Byte])
          64 (266.67% of base) : 154831.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndValue(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Char])
          49 (13.39% of base) : 81251.dasm - Microsoft.CodeAnalysis.CodeGen.ReferenceDependencyWalker:VisitReference(Microsoft.Cci.IReference,Microsoft.CodeAnalysis.Emit.EmitContext)
          41 (95.35% of base) : 155095.dasm - System.Text.Json.Utf8JsonWriter:ValidatePropertyNameAndDepth(System.ReadOnlySpan`1[Byte]):this
          41 (95.35% of base) : 155094.dasm - System.Text.Json.Utf8JsonWriter:ValidatePropertyNameAndDepth(System.ReadOnlySpan`1[Char]):this
          40 (24.39% of base) : 106749.dasm - Newtonsoft.Json.Utilities.DictionaryWrapper`2[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:Contains(System.Collections.Generic.KeyValuePair`2[__Canon,Nullable`1]):bool:this
          39 (13.45% of base) : 41218.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.DynamicTypeSymbol:Microsoft.Cci.INamespaceTypeReference.GetUnit(Microsoft.CodeAnalysis.Emit.EmitContext):Microsoft.Cci.IUnitReference:this
          39 (60.94% of base) : 222921.dasm - System.Text.SegmentStringBuilder:Add(System.ReadOnlyMemory`1[Char]):this
          38 (30.16% of base) : 214403.dasm - System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo:Init(System.Type,System.Runtime.Serialization.ISurrogateSelector,System.Runtime.Serialization.StreamingContext,System.Runtime.Serialization.ObjectManager,System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit,System.Runtime.Serialization.IFormatterConverter,bool):this
          38 (90.48% of base) : 225607.dasm - System.Threading.Tasks.Dataflow.WriteOnceBlock`1[Vector`1][System.Numerics.Vector`1[System.Single]]:CloneItem(System.Numerics.Vector`1[Single]):System.Numerics.Vector`1[Single]:this
          37 (23.27% of base) : 179631.dasm - System.ComponentModel.Design.Serialization.MemberRelationshipService:get_Item(System.ComponentModel.Design.Serialization.MemberRelationship):System.ComponentModel.Design.Serialization.MemberRelationship:this
          37 (19.68% of base) : 214405.dasm - System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo:Init(System.Type,System.String[],System.Type[],System.Runtime.Serialization.ISurrogateSelector,System.Runtime.Serialization.StreamingContext,System.Runtime.Serialization.ObjectManager,System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit,System.Runtime.Serialization.IFormatterConverter,bool):this
          30 (96.77% of base) : 80971.dasm - Microsoft.CodeAnalysis.CodeGen.ArrayMethodParameterInfo:GetType(Microsoft.CodeAnalysis.Emit.EmitContext):Microsoft.Cci.ITypeReference:this
          30 (96.77% of base) : 80142.dasm - Microsoft.CodeAnalysis.Emit.NoPia.VtblGap:Microsoft.Cci.ISignature.GetType(Microsoft.CodeAnalysis.Emit.EmitContext):Microsoft.Cci.ITypeReference:this

Top method improvements (bytes):
         -40 (-4.95% of base) : 7831.dasm - Microsoft.FSharp.Collections.SetTreeModule:balance(System.Collections.Generic.IComparer`1[Vector`1],Microsoft.FSharp.Collections.SetTree`1[Vector`1],System.Numerics.Vector`1[Single],Microsoft.FSharp.Collections.SetTree`1[Vector`1]):Microsoft.FSharp.Collections.SetTree`1[Vector`1]

Top method regressions (percentages):
          73 (304.17% of base) : 125201.dasm - System.Net.Http.HttpConnection:ReadBufferedAsync(System.Memory`1[Byte]):System.Threading.Tasks.ValueTask`1[Int32]:this
          64 (266.67% of base) : 154833.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndBytes(System.ReadOnlySpan`1[Byte],System.ReadOnlySpan`1[Byte])
          64 (266.67% of base) : 154832.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndBytes(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Byte])
          64 (266.67% of base) : 154830.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndValue(System.ReadOnlySpan`1[Byte],System.ReadOnlySpan`1[Byte])
          64 (266.67% of base) : 154829.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndValue(System.ReadOnlySpan`1[Byte],System.ReadOnlySpan`1[Char])
          64 (266.67% of base) : 154828.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndValue(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Byte])
          64 (266.67% of base) : 154831.dasm - System.Text.Json.JsonWriterHelper:ValidatePropertyAndValue(System.ReadOnlySpan`1[Char],System.ReadOnlySpan`1[Char])
          30 (96.77% of base) : 80971.dasm - Microsoft.CodeAnalysis.CodeGen.ArrayMethodParameterInfo:GetType(Microsoft.CodeAnalysis.Emit.EmitContext):Microsoft.Cci.ITypeReference:this
          30 (96.77% of base) : 80142.dasm - Microsoft.CodeAnalysis.Emit.NoPia.VtblGap:Microsoft.Cci.ISignature.GetType(Microsoft.CodeAnalysis.Emit.EmitContext):Microsoft.Cci.ITypeReference:this
          41 (95.35% of base) : 155095.dasm - System.Text.Json.Utf8JsonWriter:ValidatePropertyNameAndDepth(System.ReadOnlySpan`1[Byte]):this
          41 (95.35% of base) : 155094.dasm - System.Text.Json.Utf8JsonWriter:ValidatePropertyNameAndDepth(System.ReadOnlySpan`1[Char]):this
          38 (90.48% of base) : 225607.dasm - System.Threading.Tasks.Dataflow.WriteOnceBlock`1[Vector`1][System.Numerics.Vector`1[System.Single]]:CloneItem(System.Numerics.Vector`1[Single]):System.Numerics.Vector`1[Single]:this
          24 (66.67% of base) : 191955.dasm - System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper:Write(System.ReadOnlySpan`1[Byte]):this
          39 (60.94% of base) : 222921.dasm - System.Text.SegmentStringBuilder:Add(System.ReadOnlyMemory`1[Char]):this
          27 (55.10% of base) : 125290.dasm - ContentLengthWriteStream:Write(System.ReadOnlySpan`1[Byte]):this
          22 (55.00% of base) : 15542.dasm - System.MemoryExtensions:Sort(System.Span`1[Byte],System.Comparison`1[Byte])
          29 (50.88% of base) : 175620.dasm - System.Collections.Generic.Stack`1[Vector`1][System.Numerics.Vector`1[System.Single]]:Push(System.Numerics.Vector`1[Single]):this
          23 (48.94% of base) : 173035.dasm - Node[Vector`1,Nullable`1][System.Numerics.Vector`1[System.Single],System.Nullable`1[System.Int32]]:Remove(System.Numerics.Vector`1[Single],System.Collections.Generic.IComparer`1[Vector`1],byref):Node[Vector`1,Nullable`1]:this
          29 (48.33% of base) : 20897.dasm - System.Collections.Generic.List`1[Vector`1][System.Numerics.Vector`1[System.Single]]:Add(System.Numerics.Vector`1[Single]):this
         140 (46.51% of base) : 41163.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData:CreateMetadataExpression(Microsoft.CodeAnalysis.TypedConstant,Microsoft.CodeAnalysis.Emit.EmitContext):Microsoft.Cci.IMetadataExpression:this

Top method improvements (percentages):
         -40 (-4.95% of base) : 7831.dasm - Microsoft.FSharp.Collections.SetTreeModule:balance(System.Collections.Generic.IComparer`1[Vector`1],Microsoft.FSharp.Collections.SetTree`1[Vector`1],System.Numerics.Vector`1[Single],Microsoft.FSharp.Collections.SetTree`1[Vector`1]):Microsoft.FSharp.Collections.SetTree`1[Vector`1]

58 total methods with Code Size differences (1 improved, 57 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

For example in benchmarks method 12645 we see a field reference...

```
LocalAddressVisitor visiting statement:
STMT00001 (IL   ???...  ???)
               [000006] --C---------              *  JTRUE     void  
               [000005] --C---------              \--*  NE        int   
               [000033] ----G-------                 +--*  FIELD     int    _length
               [000031] ------------                 |  \--*  ADDR      byref 
               [000032] -------N----                 |     \--*  LCL_VAR   struct<System.ReadOnlySpan`1[Char], 16>(P) V00 arg0         
                                                     |     \--*    byref  V00._pointer (offs=0x00) -> V03 tmp1         
                                                     |     \--*    int    V00._length (offs=0x08) -> V04 tmp2         
               [000004] ------------                 \--*  CNS_INT   int    0
Replacing the field in promoted struct with local var V04
LocalAddressVisitor incrementing ref count from 0 to 1 for implicit by-ref V00

Arg [000020] is unpromoted implicit byref V00, seeing if we can still tail call
... no, arg has 2 non-call appearance(s)
[Fast tailcall decision]: Will not fast tailcall (Callee has a byref parameter)
```

**Comment by AndyAyersMS** [comment]
New assert is firing...
```
Assert failure(PID 4380 [0x0000111c], Thread: 5928 [0x1728]): Assertion failed 'totalAppearances >= callAppearances' in 'System.Buffers.Text.Utf8Parser:TryParse(System.ReadOnlySpan`1[Byte],byref,byref,ushort):bool' during 'Morph - Global' (IL size 78)
```
Suspect it's because morph monkeys with the RCS_EARLY counts.... I suspect for no good reason anymore, as we redo the regular ref counts from scratch later on.

I may need to change that first (hopefully zero diff).

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -7119,13 +7119,29 @@ bool Compiler::fgCallHasMustCopyByrefParameter(GenTreeCall* callee)
...
                             }
+                            else if (totalAppearances > callAppearances)
+                            {
+                                // lvRefCntWtd tracks the number of appearances of the arg at call sites.
+                                // If this number doesn't match the regular ref count, there is
+                                // a non-call appearance, and we must be conservative.
+                                //
+                                JITDUMP("... no, arg has %u non-call appearance(s)\n",
+                                        totalAppearances - callAppearances);
+                            }
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:7139]: Is it possible to see two arguments like:
```
GT_LCL_VAR a

GT_COMMA
  GT_ASG
    GT_LCL_VAR b
    GT_ADDR
      GT_LCL_VAR a
  GT_LCL_VAR b
```

and what do the ref counts look like in this case?

Comment (AndyAyersMS) [reply src/coreclr/jit/morph.cpp:7139]: The counts should be 1 call, 1 non-call for both `a` and `b`. The counting logic is in `UpdateEarlyRefCountForImplicitByRef`.

**Review by jakobbotsch — APPROVED** [review]
LGTM with the ref count fix.

**Comment by AndyAyersMS** [comment]
Rebased to pick up #57037.

**Comment by AndyAyersMS** [comment]
Odd, I can't see the initial commit test history anymore.

**Comment by AndyAyersMS** [comment]
Linker tests got a nuget failure:
```
##[error].dotnet/sdk/6.0.100-preview.6.21355.2/NuGet.RestoreEx.targets(19,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) Failed to retrieve information about 'Microsoft.AspNetCore.App.Ref' from remote source 'https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/58ca65bb-e6c1-4210-88ac-fa55c1cd7877/nuget/v3/flat2/microsoft.aspnetcore.app.ref/index.json'.
```

**Comment by AndyAyersMS** [comment]
Same diffs as above, with #57037 in place.
