### PR TITLE
Fix various LastIndexOf bugs when dealing with zero-length target substrings

### LINKED ISSUE #13382: ROS<T>.LastIndexOf(ROS<T> value) returns wrong index when 'value' is empty
```cs
Console.WriteLine("Hello".LastIndexOf(""));
Console.WriteLine("Hello".LastIndexOf("", StringComparison.Ordinal));
Console.WriteLine("Hello".AsSpan().LastIndexOf(""));
Console.WriteLine("Hello".AsSpan().LastIndexOf("", StringComparison.Ordinal));

// PRINTS:
// 4
// 4
// 0
// 4
```

The behavior of `ROS<T>.LastIndexOf` differs based on whether the `char`-specific overload is called or whether the generic `T` overload is called, as shown above. We should make the behavior consistent.

(To be fair, all of these APIs should be returning "5", not "4". I'll file a separate bug for that.)

### LINKED ISSUE #13383: string.LastIndexOf(string.Empty, ...) returns wrong index
(Related to https://github.com/dotnet/coreclr/issues/26608.)

The definition of `string.IndexOf(string value, StringComparison comparisonType)` is such that it returns the minimum integer _index_ for which the following expression is true:

```cs
originalString.Substring(index).StartsWith(value, comparisonType) == true
```

Similarly, the definition of `string.LastIndexOf(string value, StringComparison comparisonType)` is such that it returns the maximum integer _index_ for which the following expression is true:

```cs
originalString.Substring(index).StartsWith(value, comparisonType) == true
```

(If there is no value _index_ which makes this expression true, `IndexOf` and `LastIndexOf` return -1.)

Given this definition, the result of `someInputString.LastIndexOf("", StringComparison.Ordinal)` should be `someInputString.Length` for all possible input strings. This is because calling `someInputString.Substring(someInputString.Length)` will result in the empty string, and any string (including the empty string) trivially starts with itself. Furthermore, there is no larger value _index_ which can be passed into the `Substring` routine, as any such value would result in an exception.

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Fixes https://github.com/dotnet/runtime/issues/13382.
Fixes https://github.com/dotnet/runtime/issues/13383.

`string.LastIndexOf` and `MemoryExtensions.LastIndexOf` are inconsistent with how they handle zero-length target strings with various `StringComparison` arguments. In some cases they return `string.Length - 1`. In some cases they return `span.Length`. And in some cases they return `0`.

This PR normalizes the behavior of all of these APIs so that a zero-length target substring is always found at the end of the search space. Since `LastIndexOf`'s parameters vary significantly from `IndexOf`'s parameters, I also included a code comment right in front of `string.IndexOf(string)` that explains the concept of "search space" vis-à-vis this particular API.

There's also some small comment cleanup throughout the code paths which deal with these checks.

This PR was extracted from https://github.com/dotnet/runtime/pull/1514 into its own standalone review. This PR addresses only `LastIndexOf` and doesn't address the zero-weight code point issue tracked by that PR.

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
Note to @tarekgh: This PR doesn't have the "avoid validating `CompareOptions` if you can early-exit" concerns that you raised in https://github.com/dotnet/runtime/pull/1514#discussion_r364882861. But that's because this PR doesn't attempt to solve the zero-weight code point problem. 😉 Once I spin https://github.com/dotnet/runtime/pull/1514 back up we'll have to deal with the issue at that time since it'll necessarily involve contorting control flow.

**Comment by tarekgh** [comment]
CC @safern just in case he is touching some of the changed files here.

**Review by tarekgh — APPROVED** [review]
I like the change and now our behavior is more understandable. only one thing, we need to document this as a breaking change. right? if so, can we ensure this is written so we can point users to the doc when anyone complains? Thanks for clearing this area.

**Comment by GrabYourPitchforks** [comment]
This issue is marked with a breaking change tag. In theory it should be caught in any pre-release sweep we do to account for such changes in the docs.

**Comment by safern** [comment]
>CC @safern just in case he is touching some of the changed files here.

Thanks @tarekgh for the heads up. It seems only the file renames will conflict, I'll have to deal with it 😄

File: src/libraries/Common/tests/Tests/System/StringTests.cs [hunk 1]
```diff
@@ -4068,8 +4070,8 @@ public static void LastIndexOf_TurkishI_EnglishUSCulture()
         }
```
Comment (adamsitnik) [inline src/libraries/Common/tests/Tests/System/StringTests.cs:4070]: not related to your changes: IMHO this test (`IndexOf_AllSubstrings`) is very complex and is trying to test too many test cases at the same time. It would be better to split it into few smaller tests with self-describing names

**Review by adamsitnik — APPROVED** [review]
LGTM 👍 :shipit:

File: src/libraries/Common/tests/Tests/System/StringTests.cs (hunk 1 above)
Comment (GrabYourPitchforks) [reply src/libraries/Common/tests/Tests/System/StringTests.cs:4070]: Agreed, it's a bit of a bear. Do you have recommendations for how it might naturally be split?

Comment (adamsitnik) [reply src/libraries/Common/tests/Tests/System/StringTests.cs:4070]: I think that the two `if` blocks could become separate tests: `value.Length == 0`, `s.Length == 0`
