### PR TITLE
JIT: Account for mixed-enregistered locals when zeroing without block-init

### LINKED ISSUE #104570: superpmi-replay failing with `Assertion failed 'emitCurIG != emitPrologIG'`
superpmi-replay jobs are failing with this assert
```
[04:30:25] ISSUE: <ASSERT> #186407 D:\a\_work\1\s\src\coreclr\jit\emit.cpp (9672) - Assertion failed 'emitCurIG != emitPrologIG' in 'System.Numerics.Tensors.TensorPrimitives:<Aggregate>g__Vectorized512|67_3[ulong,System.Numerics.Tensors.TensorPrimitives+SquaredOperator`1[ulong],System.Numerics.Tensors.TensorPrimitives+AddOperator`1[ulong]](byref,ulong):ulong' during 'Generate code' (IL size 1149; hash 0x6bc820e5; FullOpts)
```

Example pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=733104&view=results
Example console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-104554-merge-492afeb818194082b4/windows-x64-3/1/console.c2da1a33.log?helixlogtype=result

### PR DESCRIPTION
**Pull request by jakobbotsch**
Locals that are in registers at the beginning of a function do not need to have their stack home zeroed. `genFnProlog` already skips these locals when computing the range of bytes to zero; however, `genZeroInitFrame` was not doing the same in the non-block init case (which ignores the range computed by `genFnProlog`). This could cause an unbounded amount of (unnecessary) codegen during zero-initing, which is not legal to have in the prolog.

Fix #104570

### CODE REVIEW

File: src/coreclr/jit/codegencommon.cpp [hunk 1]
```diff
@@ -4024,9 +4024,15 @@ void CodeGen::genZeroInitFrame(int untrLclHi, int untrLclLo, regNumber initReg,
...
-            noway_assert(varDsc->lvIsInReg() || varDsc->lvOnFrame);
+            // Locals that are (only) in registers to begin with do not need
+            // their stack home zeroed. Their register will be zeroed later in
+            // the prolog.
+            if (varDsc->lvIsInReg() && !varDsc->lvLiveInOutOfHndlr)
+            {
+                continue;
+            }
+
+            noway_assert(varDsc->lvOnFrame);
```
Comment (tannergooding) [inline src/coreclr/jit/codegencommon.cpp:4035]: In `genCheckUseBlockInit` it looks like the main loop only increases `initStkLclCnt` when `varDsc->lvIsOnFrame`.

So couldn't we use that as an early out detection mechanism? Basically:
```cpp
if (!varDsc->lvMustInit || !varDsc->lvOnFrame)
{
    continue;
}
```

There's then a secondary handler that increments for spill temps containing pointers, but that looks to be independent of this main loop in `genZeroInitFrame` and is handled in its own subsequent loop.

**Review by tannergooding — APPROVED** [review]
LGTM. It's somewhat hard to correlate the logic done in `genCheckUseBlockInit` in contrast to the logic done in `genZeroInitFrame`, I think long term it'd be ideal if these could be more explicit between the two to make it very clear that we're handling the right things.

File: src/coreclr/jit/codegencommon.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/codegencommon.cpp:4035]: `genCheckUseBlockInit` will set `lvMustInit`, so I don't think we need more checks here... the logic is that if `genCheckUseBlockInit` left `lvMustInit` as 1 and it isn't a register argument, then it must be on frame as otherwise we wouldn't need to init it.

**Comment by jakobbotsch** [comment]
> LGTM. It's somewhat hard to correlate the logic done in `genCheckUseBlockInit` in contrast to the logic done in `genZeroInitFrame`, I think long term it'd be ideal if these could be more explicit between the two to make it very clear that we're handling the right things.

Yeah... @AndyAyersMS has had musings about creating an actual model of the stack frame, which would also make this stuff harder to get wrong.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib 

libraries-jitstress failures look like #104613, #104605, #102706, #104269/#103940/#103630/#103549, #104366
Other failures look like infra issues.
