### PR TITLE
JIT: Don't compact away block in cond-to-return folding

### LINKED ISSUE #113923: JIT: Assertion failed 'bbTrueEdge->getSourceBlock() == this' during Optimize Bools
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=993643&view=results
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Assertion failed 'bbTrueEdge->getSourceBlock() == this'",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

cc @dotnet/jit-contrib 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=993643
**Error message validated:** `[Assertion failed 'bbTrueEdge->getSourceBlock() == this'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/26/2025 3:17:28 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[994520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=994520)|dotnet/runtime|[System.Collections.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=994520&view=ms.vss-test-web.build-test-results-tab&runId=26545466&resultId=201308)|dotnet/runtime#111072|
|[993750](https://dev.azure.com/dnceng-public/public/_build/results?buildId=993750)|dotnet/runtime|[System.Collections.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=993750&view=ms.vss-test-web.build-test-results-tab&runId=26544424&resultId=201292)|dotnet/runtime#113905|
|[994406](https://dev.azure.com/dnceng-public/public/_build/results?buildId=994406)|dotnet/runtime|[System.Collections.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=994406&view=ms.vss-test-web.build-test-results-tab&runId=26541634&resultId=208003)|dotnet/runtime#107369|
|[994387](https://dev.azure.com/dnceng-public/public/_build/results?buildId=994387)|dotnet/runtime|[System.Collections.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=994387&view=ms.vss-test-web.build-test-results-tab&runId=26540506&resultId=208003)|dotnet/runtime#110818|
|[993643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=993643)|dotnet/runtime|[System.Collections.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=993643&view=ms.vss-test-web.build-test-results-tab&runId=26519300&resultId=208142)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|5|5|5|

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #113923. If we are considering folding a conditional block with successors that loop back to it, don't try to compact the successors, as that will quietly remove the conditional block from the flowgraph. Instead, skip compaction, and let the cond-to-return shape check fail.

### CODE REVIEW

File: src/coreclr/jit/optimizebools.cpp [hunk 1]
```diff
@@ -1720,8 +1721,8 @@ bool Compiler::fgFoldCondToReturnBlock(BasicBlock* block)
         return modified;
     }
 
-    retTrueBb  = block->GetTrueTarget();
-    retFalseBb = block->GetFalseTarget();
+    assert(block->TrueTargetIs(retTrueBb));
```
Comment (EgorBo) [inline src/coreclr/jit/optimizebools.cpp:1724]: there is `Same here - bail out if the block is no longer BBJ_COND after compacting.` comment with a condition that you can remove I presume

**Review by EgorBo — APPROVED** [review]
Good catch, totally forgot that BBJ_COND can point to itself

File: src/coreclr/jit/optimizebools.cpp [hunk 2]
```diff
@@ -1698,18 +1698,19 @@ bool Compiler::fgFoldCondToReturnBlock(BasicBlock* block)
...
+    // but don't compact the conditional block away in the process
+    if (fgCanCompactBlock(retTrueBb) && !retTrueBb->TargetIs(block))
     {
         fgCompactBlock(retTrueBb);
         modified = true;
     }
     // By the time we get to the retFalseBb, it might be removed by fgCompactBlock()
     // so we need to check if it is still valid.
-    if (!retFalseBb->HasFlag(BBF_REMOVED) && fgCanCompactBlock(retFalseBb))
+    if (!retFalseBb->HasFlag(BBF_REMOVED) && fgCanCompactBlock(retFalseBb) && !retFalseBb->TargetIs(block))
```
Comment (EgorBo) [inline src/coreclr/jit/optimizebools.cpp:1713]: presumably you also don't need `!retFalseBb->HasFlag(BBF_REMOVED)` check

File: src/coreclr/jit/optimizebools.cpp (hunk 1 above)
Comment (amanasifkhalid) [reply src/coreclr/jit/optimizebools.cpp:1724]: I don't think we can remove this: Suppose the true target jumps to the false target, and we compact the false target into the true target. This will make the conditional block degenerate, since it now branches to the same target in either case. `fgReplaceJumpTarget` will detect this, and convert the block into a `BBJ_ALWAYS`, so I think we need to check for this case in the caller.

File: src/coreclr/jit/optimizebools.cpp (hunk 2 above)
Comment (amanasifkhalid) [reply src/coreclr/jit/optimizebools.cpp:1713]: I think we still need this too in the case of the diamond shape: If the true target jumps to the false target and we compact them, `retFalseBb` will be removed from the flowgraph. This check currently defends against this case.

**Comment by amanasifkhalid** [comment]
[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=994746&view=ms.vss-build-web.run-extensions-tab)

**Comment by amanasifkhalid** [comment]
/ba-g timeouts on Azure Linux 3 queues
