### PR TITLE
[release/10.0][Android] Avoid calling membarrier on older Android versions

### LINKED ISSUE #115480: [Android][CoreCLR] Android.Device_Emulator.JIT.Test crashes with SIGSYS
#115330 showed that Android.Device_Emulator.JIT.Test work item crashes with the following output on several Android API levels:

```
05-06 11:27:48.155  2909  2925 D DOTNET  : Java_net_dot_MonoRunner_setEnv:
05-06 11:27:48.155  2909  2925 D DOTNET  : Setting env: HOME=/data/user/0/net.dot.Android.Device_Emulator.JIT.Test/files
05-06 11:27:48.155  2909  2925 D DOTNET  : Java_net_dot_MonoRunner_setEnv:
05-06 11:27:48.155  2909  2925 D DOTNET  : Setting env: TMPDIR=/data/user/0/net.dot.Android.Device_Emulator.JIT.Test/cache
05-06 11:27:48.155  2909  2925 D DOTNET  : Java_net_dot_MonoRunner_setEnv:
05-06 11:27:48.155  2909  2925 D DOTNET  : Setting env: TEST_RESULTS_DIR=/storage/emulated/0/Android/data/net.dot.Android.Device_Emulator.JIT.Test/files/Documents
05-06 11:27:48.155  2909  2925 I DOTNET  : MonoRunner initializeRuntime, entryPointLibName=Android.Device_Emulator.JIT.Test.dll
05-06 11:27:48.421  2909  2925 D DOTNET  : Java_net_dot_MonoRunner_initRuntime (CoreCLR):
05-06 11:27:48.421  2909  2925 D DOTNET  : mono_droid_runtime_init (CoreCLR) called with executable: Android.Device_Emulator.JIT.Test.dll
05-06 11:27:48.421  2909  2925 D DOTNET  : Calling coreclr_initialize
--------- beginning of crash
05-06 11:27:48.517  2909  2925 F libc    : Fatal signal 31 (SIGSYS), code 1 in tid 2925 (.dot.MonoRunner)
05-06 11:27:48.712  2931  2931 W crash_dump64: type=1400 audit(0.0:34): avc: denied { search } for name="files" dev="dm-0" ino=98989 scontext=u:r:crash_dump:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-06 11:27:48.732  2931  2931 I chatty  : uid=10065(u0_a65) crash_dump64 identical 1 line
05-06 11:27:48.775  2931  2931 I crash_dump64: obtaining output fd from tombstoned
05-06 11:27:48.792  1510  1510 I /system/bin/tombstoned: received crash request for pid 2909
05-06 11:27:48.793  2931  2931 I crash_dump64: performing dump of process 2909 (target tid = 2925)
05-06 11:27:48.793  2931  2931 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-06 11:27:48.793  2931  2931 F DEBUG   : Build fingerprint: 'Android/sdk_phone_x86_64/generic_x86_64:8.0.0/OSR1.180418.004/4931640:userdebug/test-keys'
05-06 11:27:48.793  2931  2931 F DEBUG   : Revision: '0'
05-06 11:27:48.793  2931  2931 F DEBUG   : ABI: 'x86_64'
05-06 11:27:48.793  2931  2931 F DEBUG   : pid: 2909, tid: 2925, name: .dot.MonoRunner  >>> net.dot.Android.Device_Emulator.JIT.Test <<<
05-06 11:27:48.793  2931  2931 F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
05-06 11:27:48.793  2931  2931 F DEBUG   : Cause: seccomp prevented call to disallowed x86_64 system call 0
05-06 11:27:48.793  2931  2931 F DEBUG   :     rax 0000000000000144  rbx 0000000000000000  rcx ffffffffffffffff  rdx 0000000000000000
05-06 11:27:48.793  2931  2931 F DEBUG   :     rsi 0000000000000000  rdi 0000000000000000
05-06 11:27:48.793  2931  2931 F DEBUG   :     r8  0000000000000000  r9  0000744a0e658860  r10 00000000ffffffff  r11 0000000000000246
05-06 11:27:48.793  2931  2931 F DEBUG   :     r12 0000744a1ab1b580  r13 00000000000001ff  r14 0000744a0e658b00  r15 000000000000001a
05-06 11:27:48.793  2931  2931 F DEBUG   :     cs  0000000000000033  ss  000000000000002b
05-06 11:27:48.793  2931  2931 F DEBUG   :     rip 0000744a1d52a6f8  rbp 0000744a059d2130  rsp 0000744a059d2118  eflags 0000000000000246
05-06 11:27:48.795  2931  2931 F DEBUG   : 
05-06 11:27:48.795  2931  2931 F DEBUG   : backtrace:
05-06 11:27:48.795  2931  2931 F DEBUG   :     #00 pc 00000000000276f8  /system/lib64/libc.so (syscall+24)
05-06 11:27:48.795  2931  2931 F DEBUG   :     #01 pc 00000000005acb5a  /data/app/net.dot.Android.Device_Emulator.JIT.Test-I0FZtG-4sfwHbLVXurirLg==/lib/x86_64/libcoreclr.so
05-06 11:27:48.795  2931  2931 F DEBUG   :     #02 pc 000000000058d9c5  /data/app/net.dot.Android.Device_Emulator.JIT.Test-I0FZtG-4sfwHbLVXurirLg==/lib/x86_64/libcoreclr.so
05-06 11:27:48.795  2931  2931 F DEBUG   :     #03 pc 000000000058dcad  /data/app/net.dot.Android.Device_Emulator.JIT.Test-I0FZtG-4sfwHbLVXurirLg==/lib/x86_64/libcoreclr.so
05-06 11:27:48.795  2931  2931 F DEBUG   :     #04 pc 00000000001c111f  /data/app/net.dot.Android.Device_Emulator.JIT.Test-I0FZtG-4sfwHbLVXurirLg==/lib/x86_64/libcoreclr.so (coreclr_initialize+479)
05-06 11:27:48.795  2931  2931 F DEBUG   :     #05 pc 00000000000017f6  /data/app/net.dot.Android.Device_Emulator.JIT.Test-I0FZtG-4sfwHbLVXurirLg==/lib/x86_64/libmonodroid.so (mono_droid_runtime_init+326)
05-06 11:27:48.795  2931  2931 F DEBUG   :     #06 pc 000000000000153b  /data/app/net.dot.Android.Device_Emulator.JIT.Test-I0FZtG-4sfwHbLVXurirLg==/lib/x86_64/libmonodroid.so (Java_net_dot_MonoRunner_initRuntime+507)
05-06 11:27:48.795  2931  2931 F DEBUG   :     #07 pc 00000000000023ff  /data/app/net.dot.Android.Device_Emulator.JIT.Test-I0FZtG-4sfwHbLVXurirLg==/oat/x86_64/base.odex (offset 0x2000)
05-06 11:27:48.795  2931  2931 F DEBUG   :     #08 pc 000000000000000b  <unknown>
05-06 11:27:49.072  2931  2931 W crash_dump64: type=1400 audit(0.0:36): avc: denied { search } for name="files" dev="dm-0" ino=98989 scontext=u:r:crash_dump:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-06 11:27:49.164  1510  1510 E /system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_00
05-06 11:27:49.165  1626  1645 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
05-06 11:27:49.205  1626  1640 E memtrack: Couldn't load memtrack module
05-06 11:27:49.205  1626  1640 W android.os.Debug: failed to get memory consumption info: -1
05-06 11:27:49.212  1626  1886 I ActivityManager: Process net.dot.Android.Device_Emulator.JIT.Test (pid 2909) has died: fore FGS 
05-06 11:27:49.212  1626  1886 W ActivityManager: Crash of app net.dot.Android.Device_Emulator.JIT.Test running instrumentation ComponentInfo{net.dot.Android.Device_Emulator.JIT.Test/net.dot.MonoRunner}
05-06 11:27:49.213  1626  1886 I ActivityManager: Force stopping net.dot.Android.Device_Emulator.JIT.Test appid=10065 user=0: finished inst
05-06 11:27:49.215  1471  1471 I Zygote  : Process 2909 exited due to signal (31)
```

Full logs: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1034591&view=ms.vss-test-web.build-test-results-tab

This crash was observed on the following helix queues:
- ubuntu.2204.amd64.android.21.open
- ubuntu.2204.amd64.android.22.open
- ubuntu.2204.amd64.android.26.open
- ubuntu.2204.amd64.android.27.open
- ubuntu.2204.amd64.android.28.open

The test passed on the following helix queues:
- ubuntu.2204.amd64.android.23.open
- ubuntu.2204.amd64.android.24.open
- ubuntu.2204.amd64.android.25.open
- ubuntu.2204.amd64.android.29.open
- ubuntu.2204.amd64.android.30.open
- ubuntu.2204.amd64.android.31.open
- ubuntu.2204.amd64.android.32.open
- ubuntu.2204.amd64.android.33.open
- ubuntu.2204.amd64.android.34.open

It's not apparent why this test passes on some API levels and fails on others. There isn't a clear divide which would show that it only fails before a certain API level, so the failures might be somewhat random.

/cc @kotlarmilos @ivanpovazan @vitek-karas

### PR DESCRIPTION
**Pull request by simonrozsival**
Fixes #115480 in .NET 10 RC2, supersedes #118984.

This fix was part of #118161 but it wasn't ready before the RC snap. This PR includes only the necessary changes to fix the Android startup crash.

/cc @jkotas 

## Customer Impact

- [ ] Customer reported
- [X] Found internally

In .NET 10, we are shipping experimental support for CoreCLR on Android. On older Android versions, the `membarrier` syscall is disallowed. Without this change, customers will not be able to test Android CoreCLR on devices running API 28 and earlier which are still supported by .NET.

## Regression

- [ ] Yes
- [X] No

## Testing

Manual testing on Android emulators running a wide range of API levels.

## Risk

Low. The fix is scoped to the Android target. It is based on the existing code in [`gcenv.unix.cpp`](https://github.com/dotnet/runtime/blob/release/10.0/src/coreclr/gc/unix/gcenv.unix.cpp#L143-L155).

### CODE REVIEW

File: src/coreclr/pal/src/thread/process.cpp [hunk 1]
```diff
@@ -2826,6 +2826,17 @@ InitializeFlushProcessWriteBuffers()
     _ASSERTE(s_flushUsingMemBarrier == 0);
 
 #if defined(__linux__) || HAVE_SYS_MEMBARRIER_H
+
+#ifdef TARGET_ANDROID
+    // Avoid calling membarrier on older Android versions where membarrier
+    // may be barred by seccomp causing the process to be killed.
+    int apiLevel = android_get_device_api_level();
```
Comment (jkotas) [inline src/coreclr/pal/src/thread/process.cpp:2833]: This needs to mirror the logic from https://github.com/dotnet/runtime/blob/2b6bc445bf9bdb2c6d33addd969a80a106d476ad/src/coreclr/gc/unix/gcenv.unix.cpp#L147-L155

When we are on old Android, we need to execute the fallback path below that creates ` s_helperPage`, etc.

**Review by jkotas — CHANGES_REQUESTED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
approved. please get a code review. merge when ready

File: src/coreclr/pal/src/thread/process.cpp (hunk 1 above)
Comment (simonrozsival) [reply src/coreclr/pal/src/thread/process.cpp:2833]: I see. I updated the code accordingly.

**Review by jkotas — APPROVED** [review]

**Comment by jeffschwMSFT** [comment]
@simonrozsival please take a look at the ci failures.  I can assist with merging

**Comment by simonrozsival** [comment]
@jeffschwMSFT the failing tests on android-arm64 are unrelated to this change (#118366, #118950)
