### PR TITLE
Use holding thread id in AwareLock to avoid orphaned lock crash

### LINKED ISSUE #44071: Crash caused by orphaned locks
I just run into an issue on .NET Framework, but it impacts .NET Core as well. In both cases, it causes the app to crash with an access violation.

Repro code:

```csharp
static void Main(string[] args)
{
    var locks = new object[4];

    for (int i = 0; i < locks.Length; i++)
    {
        locks[i] = new object();
    }

    for (int i = 0; i < 4; i++)
    {
        var thread = new Thread(state =>
        {
            Monitor.Enter(locks[(int)state]);
        });

        thread.Start(i);
        thread.Join();
    }

    // Force the thread to be collected, orphaning the lock
    GC.Collect(2, GCCollectionMode.Forced, true, true);
    GC.WaitForPendingFinalizers();
    GC.Collect(2, GCCollectionMode.Forced, true, true);

    // Promote to a syncblock
    for (int i = 0; i < locks.Length; i++)
    {
        _ = locks[i].GetHashCode();
    }

    // Trigger the crash
    for (int i = 0; i < 4; i++)
    {
        var thread = new Thread(state =>
        {
            _ = Monitor.IsEntered(locks[(int)state]);
        });

        thread.Start(i);
        thread.Join();
    }
}
```

First, a thread locks an object. A thin-lock is used. The thread dies without releasing the lock.
Later, the thin-lock is promoted to a syncblock (either because of a call to `GetHashCode`, or because another thread tries to acquire the lock). When it does, the runtime tries to map the thin-lock id to the address of the thread: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/syncblk.cpp#L2214
If the cleaned up thread was the last in the map, it causes the `IdToThreadWithValidation` method to return NULL (that's the `if ((size_t)result <= m_idToThreadCapacity)` check) :
https://github.com/dotnet/runtime/blob/4d09ba6b7e458b491d0ba3d8b8d2a0ac0a289a09/src/coreclr/src/vm/threads.h#L5160-L5174

If it does, then `GetSyncBlock` sets the thread address in the syncblock to -1:
https://github.com/dotnet/runtime/blob/4d09ba6b7e458b491d0ba3d8b8d2a0ac0a289a09/src/coreclr/src/vm/syncblk.cpp#L2216-L2220

Later, another thread tries to acquire the lock. `ObjectNative::IsLockHeld` is called, which in turn calls `GetThreadOwningMonitorLock` (https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/syncblk.cpp#L1804). The method fetches the thread address from the syncblock, checks if it's null, but omits to check if it's equal to -1. This causes the access violation when trying to dereference it to fetch the thread id:
https://github.com/dotnet/runtime/blob/4d09ba6b7e458b491d0ba3d8b8d2a0ac0a289a09/src/coreclr/src/vm/syncblk.cpp#L1840-L1852

### PR DESCRIPTION
**Pull request by eduardo-vp**
In GetThreadOwningMonitorLock, in case there's a sync block, the method only checks for pThread to be equal to NULL to return false, otherwise it assumes pThread actually points to a thread. However, it can be the case that pThread is -1 for orphaned locks and should return false as well (the calling thread doesn't own the lock).

Fixes https://github.com/dotnet/runtime/issues/44071.

### CODE REVIEW

File: src/coreclr/vm/syncblk.cpp [hunk 1]
```diff
@@ -1816,7 +1816,7 @@ BOOL ObjHeader::GetThreadOwningMonitorLock(DWORD *pThreadId, DWORD *pAcquisition
 
             _ASSERTE(psb->GetMonitor() != NULL);
             Thread* pThread = psb->GetMonitor()->GetHoldingThread();
-            if(pThread == NULL)
+            if(pThread == NULL || pThread == (Thread*) -1) // -1 means the lock is orphaned
```
Comment (jkotas) [inline src/coreclr/vm/syncblk.cpp:1819]: This only handled the case of the lock being orphaned when the sync block is created.

It does not handle the case where the lock becomes orphaned after the sync got created.

File: src/coreclr/vm/syncblk.cpp [hunk 2]
```diff
@@ -2200,10 +2208,11 @@ SyncBlock *ObjHeader::GetSyncBlock()
                             }
                             else
                             {
+                                threadId = pThread->GetThreadId();
```
Comment (kouvel) [inline src/coreclr/vm/syncblk.cpp:2211]: In the above block maybe this should also be set to -1 similarly to others, to differentiate between not held and orphaned

File: src/coreclr/vm/syncblk.h [hunk 3]
```diff
@@ -436,6 +436,7 @@ class AwareLock
 
     ULONG           m_Recursion;
     PTR_Thread      m_HoldingThread;
+    DWORD           m_HoldingThreadId;
```
Comment (kouvel) [inline src/coreclr/vm/syncblk.h:439]: It would be nice to remove `m_HoldingThread` altogether. It would probably need a change to get the Thread pointer from the thread ID in the DAC. Maybe this could be cleaned up in a separate PR, for now at least the field shouldn't be dereferenced.

File: src/coreclr/vm/syncblk.cpp [hunk 4]
```diff
@@ -2367,6 +2376,7 @@ void AwareLock::Enter()
         {
             // We get here if we successfully acquired the mutex.
             m_HoldingThread = pCurThread;
+            m_HoldingThreadId = pCurThread->GetThreadId();
```
Comment (kouvel) [inline src/coreclr/vm/syncblk.cpp:2379]: Looks like some similar updates are missing in `syncblk.inl`

File: src/coreclr/vm/syncblk.inl [hunk 5]
```diff
@@ -683,6 +687,7 @@ FORCEINLINE AwareLock::LeaveHelperAction AwareLock::LeaveHelper(Thread* pCurThre
         MODE_ANY;
     } CONTRACTL_END;
 
+    // if (m_HoldingThreadId != pCurThread->GetThreadId()) some tests failed when using this line instead
```
Comment (jkotas) [inline src/coreclr/vm/syncblk.inl:690]: Why did the test fail?

Comment (eduardo-vp) [reply src/coreclr/vm/syncblk.inl:690]: Not sure yet, will look into that

Comment (eduardo-vp) [reply src/coreclr/vm/syncblk.inl]: Actually there was some line missing in AwareLock::LeaveHelper which caused the failure

File: src/coreclr/vm/syncblk.inl [hunk 6]
```diff
@@ -683,7 +687,7 @@ FORCEINLINE AwareLock::LeaveHelperAction AwareLock::LeaveHelper(Thread* pCurThre
         MODE_ANY;
     } CONTRACTL_END;
 
-    if (m_HoldingThread != pCurThread)
+    if (m_HoldingThreadId != pCurThread->GetThreadId())
```
Comment (kouvel) [inline src/coreclr/vm/syncblk.inl:690]: Since the enter path is still using the thread pointer, maybe the exit path here could also use the thread pointer for now just for minor consistency. I assume the thread pointer will be removed separately, at which point all of the checks would switch to using the thread ID anyway.

**Review by kouvel — APPROVED** [review]
Just a minor comment, otherwise LGTM, thanks!
