### PR TITLE
Fix a few places where we did not use Register type for struct locals.

### LINKED ISSUE #57913: [JitStressWithRandomNumbers] Assertion failed 'emitTypeSizes[TypeGet(type)] > 0 Generate code'
Example:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57900-merge-21f87f2b5e05428ba2/JIT.jit64.mcc/1/console.f39418f0.log?sv=2019-07-07&se=2021-09-11T23%3A47%3A24Z&sr=c&sp=rl&sig=WMzzGLr72%2FoymRcD0zHwkJJ6erBnJZcZfH9E9bhsBUY%3D

Repro steps (x86 windows):
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=8
JIT\jit64\mcc\interop\mcc_i87\mcc_i87.cmd
```

Failure log:
```
      Assert failure(PID 1656 [0x00000678], Thread: 1816 [0x0718]): Assertion failed 'emitTypeSizes[TypeGet(type)] > 0' in 'MCCTest.MyClass:GetSum2(long,MCCTest.VType8,double,MCCTest.VType8,float,MCCTest.VType8,int,MCCTest.VType8,ushort,MCCTest.VType8,int,MCCTest.VType8,float,MCCTest.VType8,long,MCCTest.VType8,float,MCCTest.VType8,double,MCCTest.VType8,float,MCCTest.VType8,short,MCCTest.VType8):MCCTest.VType8' during 'Generate code' (IL size 5)
```

the issue from a quality week JitStress experiment.

### LINKED ISSUE #57917: [JitStressWithRandomNumbers] Assertion failed 'varDsc->TypeGet() != TYP_STRUCT Generate code'
Example:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57900-merge-d8a44708bc6c4950a7/JIT.jit64.mcc/1/console.dd6cff81.log?sv=2019-07-07&se=2021-09-11T23%3A58%3A43Z&sr=c&sp=rl&sig=5YN3fi0dXJ31sqG7T1y2Nivumqk5qCNWNgGDGFzM1nE%3D

Repro steps (windows arm64):
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=8
JIT\jit64\mcc\interop\mcc_i87\mcc_i87.cmd
```

Failure log:
```
      Assert failure(PID 15160 [0x00003b38], Thread: 17020 [0x427c]): Assertion failed 'varDsc->TypeGet() != TYP_STRUCT' in 'MCCTest.MyClass:GetSum2(long,MCCTest.VType8,double,MCCTest.VType8,float,MCCTest.VType8,int,MCCTest.VType8,ushort,MCCTest.VType8,int,MCCTest.VType8,float,MCCTest.VType8,long,MCCTest.VType8,float,MCCTest.VType8,double,MCCTest.VType8,float,MCCTest.VType8,short,MCCTest.VType8):MCCTest.VType8' during 'Generate code' (IL size 5)
      
          File: D:\workspace\_work\1\s\src\coreclr\jit\codegenarmarch.cpp Line: 2689
          Image: D:\h\w\AACB0917\p\corerun.exe
```

the issue from a quality week JitStress experiment.

### PR DESCRIPTION
**Pull request by sandreenko**
There were a few places around IL JMP opcode where we did not use `GetRegisterType` for enregistarable struct locals and it was causing stress failures.

Closes https://github.com/dotnet/runtime/issues/57917, closes  https://github.com/dotnet/runtime/issues/57913.

I have spent a few hours trying to create a non-stress repro but did not succeed, I was really close with https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Regression/JitBlue/GitHub_20799/GitHub_20799.il template (thanks @echesakovMSFT), but to mark a local as "vulnerable" we need to take its address and we don't enregister address-exposed structs.
I think it can be reproduced with `genProfilingEnterCallback` for a method with struct arguments that are passed in registers, will try to do if I have more time today.

### CODE REVIEW

File: src/coreclr/jit/codegenxarch.cpp [hunk 1]
```diff
@@ -8625,7 +8625,7 @@ void CodeGen::genProfilingEnterCallback(regNumber initReg, bool* pInitRegZeroed)
                 continue;
             }
 
-            var_types storeType = varDsc->lvaArgType();
+            var_types storeType = varDsc->GetRegisterType();
```
Comment (sandreenko) [inline src/coreclr/jit/codegenxarch.cpp:8628]: I assume we can do like we do in genJmpMethod:
```
        var_types storeType = varDsc->GetActualRegisterType(); // We own the memory and can use the full move.
```
could somebody confirm?
but if it goes to RC2 it is better to keep it conservative.

File: src/coreclr/jit/lclvars.cpp [hunk 2]
```diff
@@ -1761,7 +1761,7 @@ bool Compiler::StructPromotionHelper::CanPromoteStructType(CORINFO_CLASS_HANDLE
     // or 8 Vector<T>/Vector128<T> fields on SSE2.
     const int MaxOffset = MAX_NumOfFieldsInPromotableStruct * YMM_REGSIZE_BYTES;
 #elif defined(TARGET_ARM64)
-    const int MaxOffset = MAX_NumOfFieldsInPromotableStruct * FP_REGSIZE_BYTES;
+    const int MaxOffset      = MAX_NumOfFieldsInPromotableStruct * FP_REGSIZE_BYTES;
```
Comment (sandreenko) [inline src/coreclr/jit/lclvars.cpp:1764]: a strange change from jit-format.

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]
