### PR TITLE
JIT: Validate loop invariant base case as part of IV analysis

### LINKED ISSUE #95315: JIT: Loop cloning when the method has GDV skips necessary validity checks
The following program either hits AV or prints memory from a random heap location. We get rid of the bounds check in the loop in `Bar`.

```csharp
using System;
using System.Runtime.CompilerServices;
using System.Threading;

public class Program
{
    public static void Main()
    {
        for (int i = 0; i < 4; i++)
        {
            for (int j = 0; j < 200; j++)
            {
                try
                {
                    Bar(new int[10], new C());
                }
                catch (IndexOutOfRangeException)
                {
                }
            }

            Thread.Sleep(500);
        }

        Bar(new int[1], new C());
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Bar(int[] arr, I iface)
    {
        if (arr == null)
        {
            return;
        }

        iface.Foo();

        int i = 10000000;
        do
        {
            Console.WriteLine(arr[i]);
            i++;
        } while (i < arr.Length);
    }
}

internal interface I
{
    void Foo();
}

internal class C : I
{
    public void Foo()
    {
    }
}
```

The problem is that we skip the following check when we have GDVs in the method, but then still end up optimizing bounds checks. That's only legal when this check passes. 
https://github.com/dotnet/runtime/blob/9ca95805a64f8b381efa4b5a1887ccfef1c3728e/src/coreclr/jit/loopcloning.cpp#L1893

### LINKED ISSUE #96591: JIT: Loop unrolling does not validate predecessor BBJ_COND condition properly
The following program prints `0 1 2 3`. It should not print anything.
```csharp
using System;
using System.Runtime.CompilerServices;

public class Program
{
    public static void Main()
    {
        Foo(0);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Foo(int y)
    {
        int x = 0;
        if (y != 0)
        {
            do
            {
                Console.WriteLine(x);
                x++;
            }
            while (x < 4);
        }
    }
}
```

The problem is this code in loop unrolling, which unconditionally removes the init block condition, for reasons unclear to me:
https://github.com/dotnet/runtime/blob/c33557d2bb1c1d3a8a4ef6be1ace9624a1e2dab9/src/coreclr/jit/optimizer.cpp#L4481-L4508

### LINKED ISSUE #96623: JIT: Improper zero-trip checking in loop cloning/unrolling
The following program hits an AV at runtime. It should throw `IndexOutOfRangeException`.
```csharp
public static void Main()
{
    Foo(new int[15]);
}

private static int Foo(int[] arr)
{
    int limit = GetLimit();
    int sum = 0;
    int i = 0;
    int j = 0;

    int x;

    if (Environment.TickCount < 0)
        x = 42;
    else
        x = 42;

    if (x == 42)
    {
        i = int.MaxValue;
        goto TestInner;
    }

    Console.WriteLine("Unreachable");
    goto TestOuter;

OuterStart:;
    Console.WriteLine("Outer");
    goto TestInner;

InnerStart:;
    sum += arr[i];

TestInner:;
    j++;
    if (j < 30)
        goto InnerStart;

TestOuter:;
    i++;
    if (i < limit)
        goto OuterStart;

    return sum;
}

[MethodImpl(MethodImplOptions.NoInlining)]
private static int GetLimit() => 10;
```

The problem is the JIT assumes that the entry is protected by a zero-trip test whenever we have performed loop inversion. However, the zero-trip test created by loop inversion can be unreachable, like in this case. The flow graph looks like [this](https://edotor.net/?engine=dot?engine=dot#digraph%20FlowGraph%20%7B%0A%0A%20%20%20%20graph%20%5Blabel%20%3D%20%22Foo%5Cnafter%5CnInvert%20loops%22%5D%3B%0A%20%20%20%20node%20%5Bshape%20%3D%20%22Box%22%5D%3B%0A%20%20%20%20BB01%20%5Blabel%20%3D%20%22BB01%22%2C%20shape%20%3D%20%22house%22%5D%3B%0A%20%20%20%20BB02%20%5Blabel%20%3D%20%22BB02%22%5D%3B%0A%20%20%20%20BB03%20%5Blabel%20%3D%20%22BB03%22%5D%3B%0A%20%20%20%20BB09%20%5Blabel%20%3D%20%22BB09%5CnV03%20%3E%3D%20V01%22%2C%20shape%20%3D%20%22note%22%5D%3B%0A%20%20%20%20BB04%20%5Blabel%20%3D%20%22BB04%22%5D%3B%0A%20%20%20%20BB10%20%5Blabel%20%3D%20%22BB10%5CnV04%20%3E%3D%2030%22%2C%20shape%20%3D%20%22note%22%5D%3B%0A%20%20%20%20BB05%20%5Blabel%20%3D%20%22BB05%22%5D%3B%0A%20%20%20%20BB06%20%5Blabel%20%3D%20%22BB06%5CnV04%20%3C%2030%22%5D%3B%0A%20%20%20%20BB07%20%5Blabel%20%3D%20%22BB07%5CnV03%20%3C%20V01%22%5D%3B%0A%20%20%20%20BB08%20%5Blabel%20%3D%20%22BB08%22%2C%20shape%20%3D%20%22invhouse%22%5D%3B%0A%20%20%20%20BB01%20-%3E%20BB02%20%5Bcolor%3Dblue%2C%20weight%3D20%5D%3B%0A%20%20%20%20BB03%20-%3E%20BB09%20%5Bcolor%3Dblue%2C%20weight%3D20%5D%3B%0A%20%20%20%20BB07%20-%3E%20BB04%20%5Bcolor%3Dgreen%5D%3B%0A%20%20%20%20BB09%20-%3E%20BB04%20%5Bcolor%3Dblue%2C%20weight%3D20%5D%3B%0A%20%20%20%20BB02%20-%3E%20BB10%20%5B%5D%3B%0A%20%20%20%20BB04%20-%3E%20BB10%20%5Bcolor%3Dblue%2C%20weight%3D20%5D%3B%0A%20%20%20%20BB06%20-%3E%20BB05%20%5Bcolor%3Dgreen%5D%3B%0A%20%20%20%20BB10%20-%3E%20BB05%20%5Bcolor%3Dblue%2C%20weight%3D20%5D%3B%0A%20%20%20%20BB05%20-%3E%20BB06%20%5Bcolor%3Dblue%2C%20weight%3D20%5D%3B%0A%20%20%20%20BB06%20-%3E%20BB07%20%5Bcolor%3Dblue%2C%20weight%3D20%5D%3B%0A%20%20%20%20BB10%20-%3E%20BB07%20%5B%5D%3B%0A%20%20%20%20BB07%20-%3E%20BB08%20%5Bcolor%3Dblue%2C%20weight%3D20%5D%3B%0A%20%20%20%20BB09%20-%3E%20BB08%20%5B%5D%3B%0A%20%20%20%20BB01%20-%3E%20BB02%20%5Bstyle%3D%22invis%22%2C%20weight%3D25%5D%3B%0A%20%20%20%20BB02%20-%3E%20BB03%20%5Bstyle%3D%22invis%22%2C%20weight%3D25%5D%3B%0A%20%20%20%20BB03%20-%3E%20BB09%20%5Bstyle%3D%22invis%22%2C%20weight%3D25%5D%3B%0A%20%20%20%20BB09%20-%3E%20BB04%20%5Bstyle%3D%22invis%22%2C%20weight%3D25%5D%3B%0A%20%20%20%20BB04%20-%3E%20BB10%20%5Bstyle%3D%22invis%22%2C%20weight%3D25%5D%3B%0A%20%20%20%20BB10%20-%3E%20BB05%20%5Bstyle%3D%22invis%22%2C%20weight%3D25%5D%3B%0A%20%20%20%20BB05%20-%3E%20BB06%20%5Bstyle%3D%22invis%22%2C%20weight%3D25%5D%3B%0A%20%20%20%20BB06%20-%3E%20BB07%20%5Bstyle%3D%22invis%22%2C%20weight%3D25%5D%3B%0A%20%20%20%20BB07%20-%3E%20BB08%20%5Bstyle%3D%22invis%22%2C%20weight%3D25%5D%3B%0A%7D%0A) after loop inversion, where the zero-trip test in `BB09` is unreachable. This in turn makes the checking done by loop cloning insufficient to prove that the bounds check for `arr[i]` can be removed.

Sadly OSR compilations seem to make good use of this unsoundness, so fixing this bug will mean we stop loop cloning in a bunch of OSR cases.

### LINKED ISSUE #97040: Assertion failed 'loop->EntryEdge(0)->getSourceBlock()->KindIs(BBJ_ALWAYS)'
System.Linq.Tests Work Item
net9.0-linux-Release-x64-CoreCLR_checked-fullpgo_random_gdv_edge-Ubuntu.2204.Amd64.Open

https://dev.azure.com/dnceng-public/public/_build/results?buildId=526820&view=ms.vss-test-web.build-test-results-tab&runId=12404218&paneView=debug

Also, net9.0-windows-Release-x64-CoreCLR_checked-jitosr_stress_random-Windows.10.Amd64.Open

```
DOTNET_TC_QuickJitForLoops=1
DOTNET_JitRandomGuardedDevirtualization=1
DOTNET_EnableCrashReport=1
DOTNET_TieredCompilation=1
DOTNET_JitRandomEdgeCounts=1
DOTNET_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
DOTNET_TieredPGO=1
DOTNET_DbgEnableMiniDump=1
DOTNET_JitRandomlyCollect64BitCounts=1
DOTNET_ReadyToRun=0
+ ./RunTests.sh --runtime-path /datadisks/disk1/work/9AB7088D/p
========================= Begin custom configuration settings ==============================
export __IsXUnitLogCheckerSupported=1
========================== End custom configuration settings ===============================
----- start Sun Jan 14 04:53:15 PM UTC 2024 =============== To repro directly: =====================================================
pushd .
/datadisks/disk1/work/9AB7088D/p/dotnet exec --runtimeconfig System.Linq.Tests.runtimeconfig.json --depsfile System.Linq.Tests.deps.json xunit.console.dll System.Linq.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/datadisks/disk1/work/9AB7088D/w/A7A808BC/e /datadisks/disk1/work/9AB7088D/w/A7A808BC/e
  Discovering: System.Linq.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Linq.Tests (found 1750 of 1754 test cases)
  Starting:    System.Linq.Tests (parallel test collections = on, max threads = 2)
    System.Linq.Tests.TakeWhileTests.IndexTakeWhileOverflowBeyondIntMaxValueElements [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Linq.Tests.ToArrayTests.ToArray_FailOnExtremelyLargeCollection [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Linq.Tests.SkipWhileTests.IndexSkipWhileOverflowBeyondIntMaxValueElements [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Linq.Tests.WhereTests.IndexOverflows [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Linq.Tests.SelectTests.Overflow [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Linq.Tests.IndexTests.LargeEnumerable [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Linq.Tests.IndexTests.LargeEnumerable_ThrowsOverflowException [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Linq.Tests.SelectManyTests.IndexOverflow [SKIP]
      Condition(s) not met: "IsStressModeEnabled"

Assert failure(PID 4147 [0x00001033], Thread: 4558 [0x11ce]): Assertion failed 'loop->EntryEdge(0)->getSourceBlock()->KindIs(BBJ_ALWAYS)' in 'System.Linq.Enumerable:SumSignedIntegersVectorized[long](System.ReadOnlySpan`1[long]):long' during 'Unroll loops' (IL size 547; hash 0x004dc3a8; Tier1)

    File: /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp Line: 4772
    Image: /datadisks/disk1/work/9AB7088D/p/dotnet

[createdump] Gathering state for process 4147 dotnet
[createdump] Crashing thread 11ce signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.4147.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.4147.dmp
[createdump] Written 382439424 bytes (93369 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 763ms
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
./RunTests.sh: line 180:  4147 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Linq.Tests.runtimeconfig.json --depsfile System.Linq.Tests.deps.json xunit.console.dll System.Linq.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/datadisks/disk1/work/9AB7088D/w/A7A808BC/e
----- end Sun Jan 14 04:54:28 PM UTC 2024 ----- exit code 134 ----------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
Move the validation of the base case of the IV analysis into `FlowGraphNaturalLoop::AnalyzeIteration`. Previously the validation for the base case was left up to the users:

- Loop cloning tried to accomplish this by checking whether loop inversion had run, but this is not sufficient (#96623) as nothing guarantees the loop is dominated by the inverted test. Loop cloning also skipped the check entirely for GDV, leading to #95315.

- Unrolling completely neglected to check the condition leading to #96591. Furthermore, unrolling made implicit assumptions that any `BBJ_COND` init block was an inverted test and downright removed the condition without any checks. This also led to another issue #97040 where unrolling could uncover new natural loops that had not been canonicalized.

This change makes `FlowGraphNaturalLoop::AnalyzeIteration` try to prove that the loop invariant it returns is true in the base case as well as being maintained by the loop. If it cannot prove this then it fails. This fixes all the issues, but sadly uncovers that we were doing a lot of cloning in OSR methods without actually proving legality, and where it is actually illegal. We no longer clone in these cases, but we can look into what to do about them separately.

In addition, loop unrolling no longer removes the init block condition. We leave that up to RBO which is able to remove the trivial checks that loop inversion sometimes creates in generality. This does lead to a few diffs from removing the check later in the JIT pipeline.

Diffs expected from less cloning in OSR and from leaving the trivial inverted tests around until RBO.

Fix #95315
Fix #96591
Fix #96623
Fix #97040

### CODE REVIEW

File: src/coreclr/jit/flowgraph.cpp [hunk 1]
```diff
@@ -5212,6 +5239,105 @@ bool FlowGraphNaturalLoop::MatchLimit(NaturalLoopIterInfo* info, GenTree* test)
...
+            return true;
+        }
+    }
+
+    // Do we have a zero-trip test?
+    if (initBlock->KindIs(BBJ_COND))
+    {
+        GenTree* enteringJTrue = initBlock->lastStmt()->GetRootNode();
+        assert(enteringJTrue->OperIs(GT_JTRUE));
+        if (enteringJTrue->gtGetOp1()->OperIsCompare() && ((enteringJTrue->gtGetOp1()->gtFlags & GTF_RELOP_ZTT) != 0))
```
Comment (jakobbotsch) [inline src/coreclr/jit/flowgraph.cpp:5330]: Note that loop cloning checks `GTF_RELOP_ZTT` that is set on the test tree within the loop, while this is checking for `GTF_RELOP_ZTT` set on the actual zero-trip test that we find through the init block. Loop inversion sets both, but checking the one inside the loop doesn't make sense because nothing validates that the test outside the loop actually dominates the loop.

I want to switch this to an IR based check and remove `GTF_RELOP_ZTT` so that we do not have this cross phase dependency on loop inversion. We'll be able to remove `GTF_RELOP_ZTT` when we do that. However, I'll do that separately.

File: src/coreclr/jit/flowgraph.cpp [hunk 2]
```diff
@@ -5340,7 +5466,7 @@ var_types NaturalLoopIterInfo::IterOperType()
 //
 bool NaturalLoopIterInfo::IsReversed()
 {
-    return TestTree->gtGetOp2()->OperIs(GT_LCL_VAR) && ((TestTree->gtGetOp2()->gtFlags & GTF_VAR_ITERATOR) != 0);
+    return TestTree->gtGetOp2()->OperIsScalarLocal() && (TestTree->gtGetOp2()->AsLclVar()->GetLclNum() == IterVar);
```
Comment (jakobbotsch) [inline src/coreclr/jit/flowgraph.cpp:5469]: We'll also be able to delete `GTF_VAR_ITERATOR` soon. Currently there is a use left in old loop finding.

File: src/coreclr/jit/compiler.h [hunk 3]
```diff
@@ -2023,6 +2025,9 @@ struct NaturalLoopIterInfo
     // Tree that mutates the induction variable.
     GenTree* IterTree = nullptr;
 
+    // Is the loop exited when TestTree is true?
+    bool ExitedOnTrue : 1;
```
Comment (jakobbotsch) [inline src/coreclr/jit/compiler.h:2029]: Since I spent time understanding the logic I added this now, even though it is always expected to be false currently. I expect to make a future change that removes the use of `GetLexicallyBottomMostBlock` in `AnalyzeIteration`, at which point this will be able to be true.

File: src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+using System.Runtime.CompilerServices;
+using System.Threading;
+using Xunit;
+
+public class Runtime_95315
+{
+    [Fact]
+    public static void TestEntryPoint()
+    {
+        for (int i = 0; i < 4; i++)
```
Comment (BruceForstall) [inline src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs:14]: Why are the constants in this test chosen to be the values they are?

e.g., is "4" because the constant 4-count loop gets unrolled? 200 because it doesn't get unrolled?

File: src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+    private static void Bar(int[] arr, I iface)
+    {
+        if (arr == null)
+        {
+            return;
+        }
+
+        iface.Foo();
+
+        int i = 10000000;
```
Comment (BruceForstall) [inline src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs:37]: why 10M? presumably it will fail after 10 iterations? (if it doesn't fail, we don't want the test writing 10MB of data)

File: src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+    public static void TestEntryPoint()
+    {
+        for (int i = 0; i < 4; i++)
+        {
+            for (int j = 0; j < 200; j++)
+            {
+                Assert.Throws<IndexOutOfRangeException>(() => Bar(new int[10], new C()));
+            }
+
+            Thread.Sleep(100);
```
Comment (BruceForstall) [inline src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs:21]: This is to allow tiering up?

File: src/coreclr/jit/compiler.h [hunk 7]
```diff
@@ -2006,14 +2006,16 @@ struct NaturalLoopIterInfo
     // The local that is the induction variable.
     unsigned IterVar = BAD_VAR_NUM;
 
+#ifdef DEBUG
+    // Tree that initializes induction varaible outside the loop.
```
Comment (BruceForstall) [inline src/coreclr/jit/compiler.h:2010]:
```suggestion
    // Tree that initializes induction variable outside the loop.
```

**Review by BruceForstall — APPROVED** [review]

File: src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs (hunk 6 above)
Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs:21]: Yeah, this loop is just to tier up `Bar`. The problem is inside `Bar`

File: src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs (hunk 5 above)
Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs:37]: I picked a large constant that has high probability to hit AV if we wrongly elide the check. But you're right, we shouldn't be doing `Console.WriteLine` with it, will fix that

Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs:37]: Note that `arr.Length` is only 1

File: src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs (hunk 4 above)
Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs:14]: It's to make sure we tier up completely (handling up to 4 potential tiers...)

File: src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs (hunk 5 above)
Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs:37]: On second thought, if we hit valid data at + 10000000 then we only print one time anyway, since `i < arr.Length` will immediately be false.

File: src/coreclr/jit/compiler.h (hunk 7 above)
Comment (jakobbotsch) [reply src/coreclr/jit/compiler.h:2010]: Going to address this as part of a follow-up.

File: src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs (hunk 5 above)
Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_95315/Runtime_95315.cs:37]: Going to leave it like this since it'll at most print one time.
