### PR TITLE
P/Invoke transient IL regression fixes

### LINKED ISSUE #127209: Test failure: global::GenericsTest.TestVector128C()
**Failed in:** [runtime-coreclr outerloop 20260420.4](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1388332)

**Failed tests:**
```
R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open
- global::GenericsTest.TestVector128C()
- global::GenericsTest.TestVector256C()
- global::GenericsTest.TestVector64C()
- global::GenericsTest.TestVectorC()
R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- global::GenericsTest.TestVector128C()
- global::GenericsTest.TestVector256C()
- global::GenericsTest.TestVector64C()
- global::GenericsTest.TestVectorC()

```

**Error message:**
```
Unable to find an entry point named 'GetVector128COut' in DLL 'GenericsNative'.
```

**Stack trace:**
```
   at GenericsTest.TestVector128C()
   at Program.<<Main>$>g__TestExecutor116|0_117(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### LINKED ISSUE #127231: CONTRACT VIOLATION by PInvokeImportWorker
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1389215
Build error leg or test failing: System.DirectoryServices.AccountManagement.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/127205

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "CONTRACT VIOLATION by PInvokeImportWorker",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1389215
**Error message validated:** `[CONTRACT VIOLATION by PInvokeImportWorker`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/21/2026 5:26:16 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1389215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1389215)|dotnet/runtime|[System.DirectoryServices.AccountManagement.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1389215&view=ms.vss-test-web.build-test-results-tab&runId=38798914&resultId=223715)|dotnet/runtime#127205|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes https://github.com/dotnet/runtime/issues/127231
Fixes https://github.com/dotnet/runtime/issues/127209

### CODE REVIEW

File: src/coreclr/vm/dllimport.cpp [hunk 1]
```diff
@@ -6019,22 +6022,40 @@ EXTERN_C void* PInvokeImportWorker(PInvokeMethodDesc* pMD)
...
 
-    UNINSTALL_UNWIND_AND_CONTINUE_HANDLER;
-    UNINSTALL_MANAGED_EXCEPTION_DISPATCHER;
+        ret = pMD->GetPInvokeTarget();
+
+        UNINSTALL_UNWIND_AND_CONTINUE_HANDLER;
+        UNINSTALL_MANAGED_EXCEPTION_DISPATCHER;
+    }
 
     return ret;
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]:
```suggestion
    return pMD->GetPInvokeTarget();
```

File: src/coreclr/vm/dllimport.cpp [hunk 2]
```diff
@@ -6019,22 +6022,40 @@ EXTERN_C void* PInvokeImportWorker(PInvokeMethodDesc* pMD)
...
+        // any of our internal exceptions into managed exceptions.
+        INSTALL_UNWIND_AND_CONTINUE_HANDLER;
 
-    ret = pMD->GetPInvokeTarget();
+        PInvoke::ResolvePInvokeTarget(pMD);
 
-    UNINSTALL_UNWIND_AND_CONTINUE_HANDLER;
-    UNINSTALL_MANAGED_EXCEPTION_DISPATCHER;
+        ret = pMD->GetPInvokeTarget();
+
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]:
```suggestion
```

File: src/coreclr/vm/dllimport.cpp [hunk 3]
```diff
@@ -6019,22 +6022,40 @@ EXTERN_C void* PInvokeImportWorker(PInvokeMethodDesc* pMD)
...
-    // this function is called by CLR to native assembly stubs which are called by
-    // managed code as a result, we need an unwind and continue handler to translate
-    // any of our internal exceptions into managed exceptions.
-    INSTALL_UNWIND_AND_CONTINUE_HANDLER;
+    if (!pMD->PInvokeTargetIsImportThunk())
+    {
+        ret = pMD->GetPInvokeTarget();
+    }
+    else
+    {
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]:
```suggestion
    if (pMD->PInvokeTargetIsImportThunk())
    {
```

File: src/coreclr/vm/dllimport.cpp [hunk 4]
```diff
@@ -6008,6 +6009,8 @@ VOID PInvokeMethodDesc::SetPInvokeTarget(LPVOID pTarget)
 // - Inlined non-SuppressGCTransition P/Invokes in jitted code at invoke time
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp:6022]:
```suggestion
// - Inlined non-SuppressGCTransition P/Invokes at invoke time
```
As far as I can tell, we are going to take this path for R2R precompiled code too. Is that right?

File: src/coreclr/vm/dllimport.cpp [hunk 5]
```diff
@@ -6008,6 +6009,8 @@ VOID PInvokeMethodDesc::SetPInvokeTarget(LPVOID pTarget)
...
 //   after we have already transitioned to unmanaged code.
 //   As far as the jitted code is concerned, we are in the unmanaged call right now.
+// - Non-inlined P/Invokes in jitted code at invoke time.
+//   In these cases the target is guaranteed to be resolved in the prestub.
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]: > In these cases the target is guaranteed to be resolved in the prestub.

Right, so why do we end up going into this method in this case? Is there some subtle race condition or memory model issue? And if there is an issue like that, what avoids it for the suppress GC transition case?

Comment (jkoritzinsky) [reply src/coreclr/vm/dllimport.cpp]: I think it's some sort of memory model issue, but I'm trying to figure out why this would have never hit previously.

Maybe with the ILStub implementation there were enough barriers with the locks to ensure a consistent view across threads?

I'll swap this commit with one that does a volatile store when we set the P/Invoke target to ensure that the target set is observed before we return from the prestub.

File: src/coreclr/vm/dllimport.cpp (hunk 4 above)
Comment (jkoritzinsky) [reply src/coreclr/vm/dllimport.cpp:6022]: Now we call into `PInvoke::ResolvePInvokeTarget` instead of coming through the import thunk worker.

File: src/coreclr/vm/dllimport.cpp [hunk 6]
```diff
@@ -5997,7 +5998,7 @@ VOID PInvokeMethodDesc::SetPInvokeTarget(LPVOID pTarget)
     }
     CONTRACTL_END;
 
-    m_pPInvokeTarget = pTarget;
+    VolatileStore(&m_pPInvokeTarget, pTarget);
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]: I do not think this is fixing the problem.

The failure happened on windows x86 chk. VolatileStore on x86 just prevents compiler reordering that is very unlikely.

Comment (jkotas) [reply src/coreclr/vm/dllimport.cpp]: The problem is that we call `PInvoke::ResolvePInvokeTarget` too late in PreStub . When we call `PInvoke::ResolvePInvokeTarget`, other threads can see the code for the PInvoke stub already and start executing it before `PInvoke::ResolvePInvokeTarget` finished running.

You can reproduce the problem 100% reliably by running this (compiled it as debug):
```
using System.Runtime.InteropServices;
using System.Threading;

new Thread(() => { }).Start();

Console.ReadLine();
new Thread(Second).Start();
GetCurrentThreadId();

static void Second()
{
    Console.ReadLine();
    GetCurrentThreadId();
}


[DllImport("kernel32.dll")]
[SuppressGCTransition]
extern static int GetCurrentThreadId();
```
1. Start under windbg and wait a bit for the program to stop on the first readline
2. `bp coreclr!PInvoke::ResolvePInvokeTarget` & `g`
3. Press enter in the app
4. `c` as needed until you hit `PInvoke::ResolvePInvokeTarget` for `GetCurrentThreadId`
5. `~n` (suspend the current thread) & `g`
6. Press enter in the app

You should see the AF on the second thread.

The fix needs to be to call `ResolvePInvokeTarget` earlier, for the `SuppressGCTransition` case at least. One option is to call `PInvokeMethodDesc::TryGetResolvedPInvokeTarget` when generating the transient IL for the stub.

Comment (jkoritzinsky) [reply src/coreclr/vm/dllimport.cpp]: I misunderstood where in the logic in prestub.cpp that we set the the native code. I thought it was after these blocks. (I think the logit in JitCompileCode is now setting it earlier that it would have been set previously with the IL stub approach). I'll move where we resolve the P/Invoke target to be earlier.

File: src/coreclr/vm/dllimport.cpp [hunk 7]
```diff
@@ -4759,6 +4760,18 @@ COR_ILMETHOD_DECODER* PInvoke::CreatePInvokeMethodIL(PInvokeMethodDesc* pMD, Dyn
...
+
+    // By now, we've generated the marshaling IL and we will have thrown any exception for invalid marshaling.
+    // We can now safely resolve the P/Invoke target.
+    // We need to resolve the P/Invoke target here in the following cases:
+    // - SuppressGCTransition
+    //  - The logic to resolve the P/Invoke target does not meet the requirements for SuppressGCTransition usage.
+    // - No P/Invoke import thunk
+    //  - If there's no P/Invoke import thunk, then there's no later time to resolve the P/Invoke target.
+    //
+    // For simplicity, we will resolve all P/Invoke targets here for non-inlined P/Invokes.
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]: Can this happen too early in some case? For example, does this work well with multicore JIT?

This would not be correct if we ever change our mind and enable inlining of PInvoke stubs, so this assumes that PInvoke stub inlining is unconditionally disabled.

I think it may be better to call `PInvokeMethodDesc::TryGetResolvedPInvokeTarget` in `PInvokeStubLinker::DoPInvoke`. It would make the inlined PInvokes and non-inlined PInvokes work exactly the same during JIT, and avoid bugs that show up in one case but not the other.

**Review by jkotas — APPROVED** [review]
