### PR TITLE
Fix issue #114504 by not emitting empty gcrefmaps in R2R

### LINKED ISSUE #114504: Crossgen2 composite with JitOptimization causes R2R dump failures on linux
If we enable optimization in crossgen2-composite tests, we get invalid RVA failures in R2R dump on Linux.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=1012253&view=ms.vss-test-web.build-test-results-tab

(part of #114464)

For example
```
Running CrossGen2:  /tmp/helix/working/A242093B/p/crossgen2/crossgen2 @/private/tmp/helix/working/A242093B/w/B7F50969/e/JIT/Intrinsics/CreateSpan_il/composite-r2r.dll.rsp  --composite 
Emitting R2R PE file: /private/tmp/helix/working/A242093B/w/B7F50969/e/JIT/Intrinsics/CreateSpan_il/composite-r2r.dll
Emitting R2R PE file: /private/tmp/helix/working/A242093B/w/B7F50969/e/JIT/Intrinsics/CreateSpan_il/CreateSpan_il.dll
Running R2RDump:  dotnet /tmp/helix/working/A242093B/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/A242093B/w/B7F50969/e/JIT/Intrinsics/CreateSpan_il/composite-r2r.dll --out /private/tmp/helix/working/A242093B/w/B7F50969/e/JIT/Intrinsics/CreateSpan_il/composite-r2r.dll.r2rdump --val
Error: System.BadImageFormatException: Failed to convert invalid RVA to offset: 66830
   at ILCompiler.Reflection.ReadyToRun.PEReaderExtensions.GetOffset(PEReader reader, Int32 rva) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/PEReaderExtensions.cs:line 113
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.EnsureImportSections() in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 1497
   at R2RDump.TextDumper.DumpSectionContents(ReadyToRunSection section) in /_/src/coreclr/tools/r2rdump/TextDumper.cs:line 435
   at R2RDump.TextDumper.DumpSection(ReadyToRunSection section) in /_/src/coreclr/tools/r2rdump/TextDumper.cs:line 120
   at R2RDump.TextDumper.DumpHeader(Boolean dumpSections) in /_/src/coreclr/tools/r2rdump/TextDumper.cs:line 81
   at R2RDump.Program.Dump(ReadyToRunReader r2r) in /_/src/coreclr/tools/r2rdump/Program.cs:line 166
   at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 460
```

### PR DESCRIPTION
**Pull request by kg**
Should fix #114504

cc @davidwrighton

### CODE REVIEW

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs [hunk 1]
```diff
@@ -50,20 +50,19 @@ public void AppendMangledName(NameMangler nameMangler, Utf8StringBuilder sb)
...
-
             _methods.MergeSort(CompilerComparer.Instance);
             GCRefMapBuilder builder = new GCRefMapBuilder(factory.Target, relocsOnly);
+
             builder.Builder.RequireInitialAlignment(4);
             builder.Builder.AddSymbol(this);
 
+            if (_methods.Count == 0 || relocsOnly)
+            {
+                // Size header (R2RDump needs this)
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: Should we fix R2RDump instead?

R2RDump should be able to dump older existing R2R images too. This fix won't apply to existing R2R images.

Comment (kg) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: The older images are corrupt, technically. The RVA in them is invalid.

For Windows R2R images, the RVA for it points to random garbage currently that r2rdump manages to not choke on. For linux images, it points to the end of the section, so there's nothing to read and R2Rdump rightly throws.

I can make R2Rdump recover from the linux scenario and that seems to be harmless, but recovering from the windows scenario is harder.

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: Ok, I can see that R2R dump fix is not straightforward. It would require a different strategy: dump the GCRefMap while dumping imports - for the imports that require GCRefMap.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs [hunk 2]
```diff
@@ -50,20 +50,19 @@ public void AppendMangledName(NameMangler nameMangler, Utf8StringBuilder sb)
...
+                builder.Builder.EmitInt(0);
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: Instead of writing out dummy padding, can we write AuxiliaryData RVA as zero when the GCRefMap is empty?

Comment (kg) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: That should work. I'll try it, thanks!

Comment (kg) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: There are other cases where we attempt to serialize an empty gcrefmap, not just in the header. I added a Debug.Assert to check whether there were any methods and it's being hit during compilation of the BCL. I need to figure out whether it's correct to omit the 0 size header in that case or not.

Comment (kg) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: I tested this and with a `Debug.Assert(_methods.Count > 0);` in the GetObjectData, the assert still triggers when building the test suite even if I do the 'auxiliarydata RVA is zero' thing. So I think we need this path for the zero method count to write the size header.

Thank you for calling my attention to this code though because I think the size header is incorrect in relocsOnly mode. I've fixed that.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionNode.cs [hunk 3]
```diff
@@ -135,7 +135,7 @@ public override void EncodeData(ref ObjectDataBuilder dataBuilder, NodeFactory f
                 dataBuilder.EmitUInt(0);
             }
 
-            if (_emitGCRefMap)
+            if (_emitGCRefMap && !_gcRefMap.IsEmpty)
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionNode.cs]:
```suggestion
            if (!_gcRefMap?.IsEmpty)
```
Nit: We do not really need `_emitGCRefMap`. The few places where it is used can be replaced with _gcRefMap null check.

Comment (kg) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionNode.cs]: I will remove the field, thank you.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs (hunk 2 above)
Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: Yes, GetData on gcRefMap will be called since GCRefMap is added as unconditional dependency in GetStaticDependencies. It means that we will try to include its content in the final image.

It should be fine for GetData to contribute no content like it was before this change. Can all changes in GetData be reverted (keep the changes to emit zero AuxiliaryData RVA)? Is there something that does not work when you do that?

BTW: There is also inefficiency one level up. We emit empty `READYTORUN_IMPORT_SECTION` entries that is unnecessary. If we stopped emitting empty `READYTORUN_IMPORT_SECTION` entries, the bug with bogus AuxiliaryData RVA would be fixed as well. If I am reading the code correctly, the bogus RVA can happen for empty `READYTORUN_IMPORT_SECTION` only.

Comment (kg) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: It seems wholly wrong to ever emit content for a refmap that is missing the size header. If the size header isn't mandatory, why is it there? How can a consumer reading the refmap know that the data following the refmap isn't a refmap size header at runtime? Is there an implicit size header somewhere else that protects us, and R2RDump isn't reading it?

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs]: The only way to get to the refmap at runtime is via `READYTORUN_IMPORT_SECTION,AuxiliaryData`. If you set `AuxiliaryData` to zero when the refmap is empty, there is no way to get to whatever content refmap contributed to the image, so it is fine for it to contribute no content.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionNode.cs [hunk 4]
```diff
@@ -135,8 +130,10 @@ public override void EncodeData(ref ObjectDataBuilder dataBuilder, NodeFactory f
                 dataBuilder.EmitUInt(0);
             }
 
-            if (_emitGCRefMap)
+            // If we emit an Rva for an empty gcrefmap, it will have no size header and be impossible for r2rdump to read correctly
+            if (_gcRefMap?.IsEmpty == false)
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionNode.cs:134]:
```suggestion
            if (_gcRefMap != null && !_gcRefMap.IsEmpty)
```
Actually, I do not think the shortcut is going to work correctly here.

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionNode.cs:134]: Ok, I think it does work correctly. Ignore this comment.

**Review by jkotas — APPROVED** [review]
