### PR TITLE
Explicit zeroing for stackalloc if inlined into a caller without LocalsInit

### LINKED ISSUE #95056: JIT: Missing zero initialization of stackallocs converted to locals for "init mem" mismatches during inlining
```csharp
using System;
using System.Runtime.CompilerServices;

public class Program
{
    public static void Main()
    {
        Foo();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Foo()
    {
        Span<byte> bytes = stackalloc byte[8];
        Console.WriteLine(bytes[0]);
    }
}
```

This program frequently prints a non-zero value. It should always print 0. The example is adapted from a customer reported example on the community Discord, where it was exposed by new inlining due to PGO in .NET 8.

When the caller does not have .locals init, but the callee does, we insert zero initialization here:
https://github.com/dotnet/runtime/blob/3b61ad9e3acb6302fd2fcef4947373475a0dcc29/src/coreclr/jit/fginline.cpp#L1952-L1994

This code does not handle the locals created by the stackalloc-to-local transformation, and the transformation itself also does not insert any zero initialization (which would likely be the easiest fix).

### LINKED ISSUE #96174: NativeAOT stackalloc returning garbage in AggressiveInlining method
### Description

`stackalloc` is returning a span containing garbage bytes in NativeAOT. The bytes in the span changes on each run. This issue occurs in a method with `AggressiveInlining` in **Release** builds. If the attribute is removed, or the project is built under Debug configuration, the issue does not reproduce.

### Reproduction Steps

```c#
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

ref struct BitBuffer
{
    private static readonly byte[] Empty4Bytes = new byte[4];

    private int _bitsAvail = 0;
    private uint _buf = 0;
    private ReadOnlySpan<byte> _pointer;

    public BitBuffer(ReadOnlySpan<byte> pointer)
    {
        _pointer = pointer;
        FetchNext();
    }

    private void FetchNext()
    {
        _bitsAvail = _pointer.Length >= 4 ? 32 : _pointer.Length * 8;
        UpdateBuffer();
    }

    public uint ReadUBits(int numBits)
    {
        var ret = (uint) (_buf & ((1 << numBits) - 1));
        _bitsAvail -= numBits;
        if (_bitsAvail != 0)
        {
            _buf >>= numBits;
        }
        else
        {
            FetchNext();
        }

        return ret;
    }

    public byte ReadByte() => (byte) ReadUBits(8);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void UpdateBuffer()
    {
        if (_pointer.Length < 4)
        {
            Span<byte> buf = stackalloc byte[4];
            if (!buf.SequenceEqual(Empty4Bytes))
            {
                throw new Exception("stackalloc non zero!");
            }
            _pointer.CopyTo(buf);
            _buf = MemoryMarshal.Read<uint>(buf);
            _pointer = default;
        }
        else
        {
            _buf = MemoryMarshal.Read<uint>(_pointer[..4]);
            _pointer = _pointer[4..];
        }
    }

    public uint ReadUVarInt32()
    {
        uint result = 0;
        var shift = 0;
        byte byteRead;

        do
        {
            byteRead = ReadByte();
            result |= (uint) (byteRead & 0x7F) << shift;
            shift += 7;
        } while ((byteRead & 0x80) != 0);

        return result;
    }
}

public class Program
{
    public static void Main(string[] args)
    {
        var bytes = new byte[] {36, 0, 0, 0};
        var bitBuffer = new BitBuffer(bytes);
        bitBuffer.ReadUBits(18);
        bitBuffer.ReadUBits(6);
        var result = bitBuffer.ReadUVarInt32();
        Console.WriteLine($"Result = {result}");
    }
}
```

### Expected behavior

Result = 0

### Actual behavior

```
Unhandled Exception: System.Exception: stackalloc non zero!
   at BitBuffer.FetchNext() + 0x168
   at BitBuffer.ReadUBits(Int32) + 0xac
   at BitBuffer.ReadUVarInt32() + 0x28
   at Program.Main(String[] args) + 0x150
   at StackallocNonZeroBug!<BaseAddress>+0xeab38
```

### Regression?

_No response_

### Known Workarounds

Remove `[MethodImpl(MethodImplOptions.AggressiveInlining)]` from `UpdateBuffer`

### Configuration

- Which version of .NET is the code running on? .NET 8
- What OS and version, and what distro if applicable? macOS 13.4.1 (22F82)
- What is the architecture (x64, x86, ARM, ARM64)? ARM64
- Do you know whether it is specific to that configuration? Not sure, can only test Mac Arm64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/96174
Fixes https://github.com/dotnet/runtime/issues/95056

### CODE REVIEW

File: src/coreclr/jit/fginline.cpp [hunk 1]
```diff
@@ -1584,6 +1584,9 @@ void Compiler::fgInsertInlineeBlocks(InlineInfo* pInlineInfo)
 
     lvaGenericsContextInUse |= InlineeCompiler->lvaGenericsContextInUse;
 
+    // Caller has no "init locals" flag, but callee does? Propagate the flag up.
+    info.compInitMem |= InlineeCompiler->info.compInitMem;
+
```
Comment (jakobbotsch) [inline src/coreclr/jit/fginline.cpp:1589]: I don't think this is the right fix. We should instead zero this in when we do the transformation during import or when we detect the mismatch during inlining. Note that we already detect and handle the case during inlining for all other locals than the one introduced by this transformation.

The issue is the same as #95056.

Comment (EgorBo) [reply src/coreclr/jit/fginline.cpp:1589]: > I don't think this is the right fix. We should instead zero this in when we do the transformation during import or when we detect the mismatch during inlining. Note that we already detect and handle the case during inlining for all other locals than the one introduced by this transformation.
> 
> The issue is the same as #95056.

That was my first fix too, but I just wanted to see the diffs from this

Comment (EgorBo) [reply src/coreclr/jit/fginline.cpp:1589]: Also, I guess it's a correct fix, just likely too conservative.

Comment (jakobbotsch) [reply src/coreclr/jit/fginline.cpp:1589]: Maybe it's correct due to limitations around where we currently allow inlining the converted stackallocs, but in general initializing inlinee locals only in the prolog of the caller is not sufficient since the inlined callee can run multiple times... So it seems like a bit of a fragile fix.

**Comment by EgorBo** [comment]
@jakobbotsch [No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=504557&view=ms.vss-build-web.run-extensions-tab) (but fixes the issue) - does it look good now? I'll file a separate PR to experiment with enabling small stackallocs in loops, and this is one is kept simple to backport it to 8.0

File: src/coreclr/jit/importer.cpp [hunk 2]
```diff
@@ -9540,15 +9540,28 @@ void Compiler::impImportBlockCode(BasicBlock* block)
...
                                         stackallocAsLocal);
-                                lvaSetStruct(stackallocAsLocal, typGetBlkLayout((unsigned)allocSize), false);
+                                lvaSetStruct(stackallocAsLocal, layout, false);
                                 lvaTable[stackallocAsLocal].lvHasLdAddrOp    = true;
                                 lvaTable[stackallocAsLocal].lvIsUnsafeBuffer = true;
                                 op1                                          = gtNewLclVarAddrNode(stackallocAsLocal);
                                 convertedToLocal                             = true;
 
+                                if (compIsForInlining() && info.compInitMem &&
+                                    !impInlineInfo->InlinerCompiler->info.compInitMem)
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp:9555]: Does it need to be `impInlineRoot()`?

File: src/coreclr/jit/importer.cpp [hunk 3]
```diff
@@ -9540,15 +9540,28 @@ void Compiler::impImportBlockCode(BasicBlock* block)
...
+                                {
+                                    // Explicitly zero out the local if we're inlining a method with InitLocals into a
+                                    // method
+                                    // without InitLocals.
+                                    op1 = gtNewOperNode(GT_COMMA, TYP_I_IMPL,
+                                                        gtNewStoreValueNode(layout, op1, gtNewIconNode(0)),
+                                                        gtCloneExpr(op1));
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp:9562]: Ideally we should prefer spilling over commas in the importer, I think.

File: src/coreclr/jit/importer.cpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/jit/importer.cpp]: addressed.

**Review by jakobbotsch — APPROVED** [review]
