### PR TITLE
[Android] Allow using installed certificates for client authentication in SslStream

### LINKED ISSUE #99874: Android: Installed X509 certificates can't be used with SSL authentication
### Description

On Android when using the SocketsHttpHandler with X509 Client certificates to PKI authenticate with a server, you can only use certificates with a private key coming from a file. When using the more correct and secure way of only using certificates installed in the keychain authentication fails, because the SocketsHttpHandler wants direct access to the private key instead of using the Java APIs to authenticate.

### Reproduction Steps

Reproduction steps are a little tricky since they require a server that requires PKI authentication, and a certificate installed on the users device. I'm going to assume you have this here.
```cs
           Uri uri = new Uri("https://mypkiserver/index.html");
            var handler = new SocketsHttpHandler();
            var tcs = new TaskCompletionSource<X509Certificate2>();
            Android.Security.KeyChain.ChoosePrivateKeyAlias(Platform.CurrentActivity!, response: new KeyChainAliasCallback(tcs),
                new String[] { Android.Security.Keystore.KeyProperties.KeyAlgorithmRsa, "DSA" }, // List of acceptable key types. null for any
                null,                        // issuer, null for any
                null,                        // host name of server requesting the cert, null if unavailable
                -1,                          // port of server requesting the cert, -1 if unavailable
                "");
            certificate = await tcs.Task;
            if (certificate != null)
                handler.SslOptions.ClientCertificates = new X509Certificate2Collection(certificate); 

            using var client = new HttpClient(handler);
            var response = await client.GetAsync(infoUri); //will usually throw if certificate can't be used
            response = response.EnsureSuccessStatusCode();
```

`KeyChainAliasCallback.cs` responsible for letting the user pick an installed certificate:
```cs
    public class KeyChainAliasCallback : Java.Lang.Object, Android.Security.IKeyChainAliasCallback
    {
        private readonly TaskCompletionSource<X509Certificate2?> _tcs;
        public KeyChainAliasCallback(TaskCompletionSource<X509Certificate2?> tcs)
        {
            _tcs = tcs;
        }

        void Android.Security.IKeyChainAliasCallback.Alias(string? alias)
        {
            if (alias != null)
            {
                var certificateChain = Android.Security.KeyChain.GetCertificateChain(Platform.CurrentActivity!, alias!);
                if (certificateChain != null && certificateChain.Length > 0)
                {
                    X509Certificate2 certificate = new(certificateChain[0].Handle);
                    _tcs.TrySetResult(certificate);
                }
            }
            _tcs.TrySetResult(null);
        }
    }
```

### Expected behavior

Certificates used from the keychain where the private key isn't directly accessible will work. 

### Actual behavior

Fails to authenticate.

### Regression?

_No response_

### Known Workarounds

None

### Configuration

_No response_

### Other information

Related issue: https://github.com/dotnet/runtime/issues/45741#issuecomment-1823987611

This is a blocker for larger enterprises since they can't use their secured services with the level of security they require. Using file-based certificates in-app with the full exportable private key just isn't acceptable to them.

### PR DESCRIPTION
**Pull request by simonrozsival**
Closes #99874

This PR adds the possibility to use certificates with non-exportable private keys installed on an Android device for client authentication in SslStream/SocketsHttpHandler.

The inspiration for these changes comes from `AppleCertificatePal` where we allow passing in either `SecCertificate` or `SecIdentity` via the `IntPtr` constructor. The Android IntPtr constructor will now accept not only handles of `java.security.cert.X509Certificate`, but also of `java.security.KeyStore.PrivateKeyEntry`. This will allow the developer to pass in certificates with non-exportable private keys and use them for client authentication (see the linked issue for an example usage with `KeyChain.ChoosePrivateKeyAlias`).

To implement this feature, it is necessary to introduce new Java class `net.dot.android.crypto.DotnetX509KeyManager`. This will require follow-up work in the .NET for Android SDK code to adjust the ProGuard configuration (https://github.com/xamarin/xamarin-android/blob/7e67d2c241e561b05065f2a57ddf59093f74de58/src/Xamarin.Android.Build.Tasks/Resources/proguard_xamarin.cfg#L29).

As a follow-up to this PR, we should introduce new APIs to the `Android.Security.KeyChain` class in the `dotnet/android` repository. This will allow the developers to avoid using this low level `IntPtr` constructor.

/cc @karelz @vitek-karas @grendello @filipnavara @dotMorten

### CODE REVIEW

**Comment by dotMorten** [comment]
@simonrozsival Thank you for working on this! Very exciting. What's the easiest way for me to test this with our various PKI tests on Android?

**Comment by simonrozsival** [comment]
@dotMorten I'm not sure if there's an easy way to do it, you'll need to jump through a few hoops:
1. build the code in this branch, you can follow https://github.com/dotnet/runtime/blob/main/docs/workflow/building/mono/README.md (alternatively I could send you the prebuilt nupkgs directly if you're OK with that, you can reach out to me via email or discord)
2. add the local nupkg source to your MAUI app via NuGet.config
3. follow this guide to use your locally built dev version of the runtimepack: https://github.com/xamarin/xamarin-android/blob/main/Documentation/workflow/DevelopmentTips.md?plain=1#L432
4. use the new ctor as it's shown in the issue or in the new unit test in this PR

File: src/libraries/Common/tests/TestUtilities/System/AndroidKeyStoreHelper.cs [hunk 1]
```diff
@@ -0,0 +1,30 @@
+
```
Comment (akoeplinger) [inline src/libraries/Common/tests/TestUtilities/System/AndroidKeyStoreHelper.cs:1]: license header:
```suggestion
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

```

**Comment by dotMorten** [comment]
I tried this change, and it indeed addresses the issue for us. Nice work @simonrozsival (and thanks for helping getting it running)

**Comment by simonrozsival** [comment]
The failing tests in `runtime-extra-platforms` are known and unrelated (https://github.com/dotnet/runtime/issues/103472)

File: src/native/libs/System.Security.Cryptography.Native.Android/pal_x509store.h [hunk 2]
```diff
@@ -70,3 +70,13 @@ Returns 1 on success, 0 otherwise.
 PALEXPORT int32_t AndroidCryptoNative_X509StoreRemoveCertificate(jobject /*KeyStore*/ store,
                                                                  jobject /*X509Certificate*/ cert,
                                                                  const char* hashString);
+
+/*
+Looks up priate key and certificate chain based on the alias in the provided keystore
```
Comment (akoeplinger) [inline src/native/libs/System.Security.Cryptography.Native.Android/pal_x509store.h:75]:
```suggestion
Looks up private key and certificate chain based on the alias in the provided keystore
```

File: src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs [hunk 3]
```diff
@@ -32,6 +32,18 @@ internal static byte[] X509Encode(SafeX509Handle x)
...
         }
+        [LibraryImport(Libraries.AndroidCryptoNative, EntryPoint = "AndroidCryptoNative_X509IsKeyStorePrivateKeyEntry")]
+        [return: MarshalAs(UnmanagedType.U1)]
+        internal static partial bool IsKeyStorePrivateKeyEntry(IntPtr handle);
+        [LibraryImport(Libraries.AndroidCryptoNative, EntryPoint = "AndroidCryptoNative_X509GetCertificateForPrivateKeyEntry")]
+        private static partial IntPtr GetPrivateKeyEntryCertificate(IntPtr privatKeyEntryHandle);
+        internal static SafeX509Handle GetPrivateKeyEntryCertificate(SafeHandle privatKeyEntryHandle)
+        {
+            var certificateHandle = new SafeX509Handle();
+            var certificatePtr = GetPrivateKeyEntryCertificate(privatKeyEntryHandle.DangerousGetHandle());
```
Comment (vcsjones) [inline src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs:43]: This should use an explicit type, not `var` here.

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs [hunk 4]
```diff
@@ -208,5 +208,49 @@ public async Task AutomaticOrManual_DoesntFailRegardlessOfWhetherClientCertsAreA
                 }, new LoopbackServer.Options { UseSsl = true });
             }
         }
+
+        [ConditionalFact]
```
Comment (akoeplinger) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:212]: this can be a normal `[Fact]`

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs [hunk 5]
```diff
@@ -208,5 +208,49 @@ public async Task AutomaticOrManual_DoesntFailRegardlessOfWhetherClientCertsAreA
...
+        [PlatformSpecific(TestPlatforms.Android)]
+        public async Task Android_GetCertificateFromKeyStoreViaAlias()
+        {
+#if TARGETS_ANDROID
```
Comment (akoeplinger) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:216]: I'd wrap the whole test in the #if then you also don't need the #else

**Review by akoeplinger — APPROVED** [review]
LGTM, a couple comments but I'm fine if we address them in a follow-up PR

File: src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs (hunk 3 above)
Comment (vcsjones) [reply src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs:43]: What is ensuring the liveliness of the handle here? Do we need to do a `DangerousAddRef` and `DangerousRelease` around getting the handle? This is of particular concern if multiple threads are involved.

To ask another way, can `privatKeyEntryHandle` be disposed between the calls of `DangerousGetHandle` and `GetPrivateKeyEntryCertificate`?

File: src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509Store.cs [hunk 6]
```diff
@@ -57,6 +57,12 @@ internal static partial class AndroidCrypto
             SafeX509StoreHandle store,
             SafeX509Handle cert,
             string hashString);
+
+        [LibraryImport(Libraries.AndroidCryptoNative, EntryPoint = "AndroidCryptoNative_X509StoreGetPrivateKeyEntry", StringMarshalling = StringMarshalling.Utf8)]
+        internal static partial IntPtr X509StoreGetPrivateKeyEntry(IntPtr store, string hashString);
+        [LibraryImport(Libraries.AndroidCryptoNative, EntryPoint = "AndroidCryptoNative_X509StoreDeleteEntry", StringMarshalling = StringMarshalling.Utf8)]
+        [return: MarshalAs(UnmanagedType.Bool)]
```
Comment (vcsjones) [inline src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509Store.cs:64]: Is this `MarshalAs(...Bool)` right? Up above we have it as `UnmanagedType.U1`. Looking at the native definition, this seems "off" to me because a C bool is usually 1 byte whereas `UnmanagedType.Bool` is a 4 byte value.

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs (hunk 5 above)
Comment (vcsjones) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:216]: Why do we need this compiler condition if the test is already marked as `PlatformSpecific`?

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs [hunk 7]
```diff
@@ -208,5 +208,49 @@ public async Task AutomaticOrManual_DoesntFailRegardlessOfWhetherClientCertsAreA
...
+            var options = new LoopbackServer.Options { UseSsl = true };
+
+            var (store, alias) = AndroidKeyStoreHelper.AddCertificate(Configuration.Certificates.GetClientCertificate());
+            try
+            {
+                var clientCertificate = AndroidKeyStoreHelper.GetCertificateViaAlias(store, alias);
```
Comment (vcsjones) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:222]: Nit: `var`

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs [hunk 8]
```diff
@@ -208,5 +208,49 @@ public async Task AutomaticOrManual_DoesntFailRegardlessOfWhetherClientCertsAreA
...
         }
+
+        [ConditionalFact]
+        [PlatformSpecific(TestPlatforms.Android)]
+        public async Task Android_GetCertificateFromKeyStoreViaAlias()
+        {
+#if TARGETS_ANDROID
+            var options = new LoopbackServer.Options { UseSsl = true };
+
+            var (store, alias) = AndroidKeyStoreHelper.AddCertificate(Configuration.Certificates.GetClientCertificate());
```
Comment (vcsjones) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:219]: Nit: `var`

Comment (vcsjones) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:219]: The `store` should be disposed.

File: src/libraries/System.Net.Http/tests/FunctionalTests/AndroidKeyStoreHelper.cs [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+            X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
+            store.Open(OpenFlags.ReadWrite);
+            store.Add(cert);
+            string alias = cert.GetCertHashString(System.Security.Cryptography.HashAlgorithmName.SHA256);
+            return (store, alias);
+        }
+
+        public static X509Certificate2 GetCertificateViaAlias(X509Store store, string alias)
+        {
+            var privateKeyEntry = Interop.AndroidCrypto.X509StoreGetPrivateKeyEntry(store.StoreHandle, alias);
```
Comment (vcsjones) [inline src/libraries/System.Net.Http/tests/FunctionalTests/AndroidKeyStoreHelper.cs:23]: Nit: `var`

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AndroidCertificatePal.cs [hunk 10]
```diff
@@ -25,6 +26,13 @@ public static ICertificatePal FromHandle(IntPtr handle)
             if (handle == IntPtr.Zero)
                 throw new ArgumentException(SR.Arg_InvalidHandle, nameof(handle));
 
+            if (Interop.AndroidCrypto.IsKeyStorePrivateKeyEntry(handle))
+            {
+                var newPrivateKeyEntryHandle = new Interop.JObjectLifetime.SafeJObjectHandle();
+                Marshal.InitHandle(newPrivateKeyEntryHandle, Interop.JObjectLifetime.NewGlobalReference(handle));
```
Comment (vcsjones) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AndroidCertificatePal.cs:32]: I've seen these lines paired together a couple of times. A nonblocking suggestion would be to add a new static method to `SafeJObjectHandle` that creates a global reference from an `IntPtr`

```C#
internal partial class SafeJObjectHandle
{
    internal static SafeJObjectHandle CreateGlobalReferenceFromHandle(IntPtr handle)
    {
        var jObjectHandle = new SafeJObjectHandle();
        Marshal.InitHandle(jObjectHandle, Interop.JObjectLifetime.NewGlobalReference(handle));
        return jObjectHandle;
    }    
}
```

File: src/native/libs/System.Security.Cryptography.Native.Android/pal_x509.c [hunk 11]
```diff
@@ -346,3 +346,28 @@ static void FindCertStart(const uint8_t** buffer, int32_t* len)
...
+
+bool AndroidCryptoNative_X509IsKeyStorePrivateKeyEntry(jobject entry)
+{
+    if (!entry)
+        return false;
+
+    JNIEnv* env = GetJNIEnv();
+
+    return (*env)->IsInstanceOf(env, entry, g_PrivateKeyEntryClass);
+}
```
Comment (vcsjones) [inline src/native/libs/System.Security.Cryptography.Native.Android/pal_x509.c:373]: A C `bool` is not typically used across .NET marshaling boundaries. Consider returning it as an `int32_t` and changing the LibraryImport definition to `[return: MarshalAs(UnmanagedType.Bool)]`

_Wait, Kevin, change it to an int here and a bool there?_

Yeah. UnmanagedType.Bool is always 32-bits. So it would look something like:
```suggestion
int32_t AndroidCryptoNative_X509IsKeyStorePrivateKeyEntry(jobject entry)
{
    if (!entry)
        return false;

    JNIEnv* env = GetJNIEnv();

    return (*env)->IsInstanceOf(env, entry, g_PrivateKeyEntryClass) ? 1 : 0;
}
```

Of course you would need to make sure the p/invoke matches, and change the header.

File: src/native/libs/System.Security.Cryptography.Native.Android/pal_x509store.c [hunk 12]
```diff
@@ -458,3 +458,58 @@ int32_t AndroidCryptoNative_X509StoreRemoveCertificate(jobject /*KeyStore*/ stor
...
+    }
+
+    privateKeyEntry = ToGRef(env, privateKeyEntry);
+
+cleanup:
+    RELEASE_LOCALS(loc, env);
+    return privateKeyEntry;
+}
+
+bool AndroidCryptoNative_X509StoreDeleteEntry(jobject /*KeyStore*/ store, const char* hashString)
```
Comment (vcsjones) [inline src/native/libs/System.Security.Cryptography.Native.Android/pal_x509store.c:495]: Same concern / feedback about bool.

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AndroidCertificatePal.cs [hunk 13]
```diff
@@ -36,6 +44,13 @@ public static ICertificatePal FromOtherCert(X509Certificate cert)
 
             AndroidCertificatePal certPal = (AndroidCertificatePal)cert.Pal;
 
+            if (certPal._keyStorePrivateKeyEntry is not null)
+            {
+                var jobjectHandle = new Interop.JObjectLifetime.SafeJObjectHandle();
+                Marshal.InitHandle(jobjectHandle, Interop.JObjectLifetime.NewGlobalReference(certPal.Handle));
```
Comment (vcsjones) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AndroidCertificatePal.cs:50]: What happens if the certificate gets disposed between line 47 and 50 by another thread?

Since `certPal.Handle` basically the dangerous handle of `_keyStorePrivateKeyEntry` should we do a an add ref / release on that first and use that instead of the `certPal.Handle`?

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs (hunk 5 above)
Comment (simonrozsival) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:216]: The `AndroidKeyStoreHelper` is only available on android builds. I will change this test to be all wrapped in `#if` and remove the `PlatformSpecific`.

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs (hunk 8 above)
Comment (simonrozsival) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:219]: it is disposed in the `finally` block

Comment (vcsjones) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:219]: Ah whoops, I overlooked that.

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AndroidCertificatePal.cs (hunk 13 above)
Comment (simonrozsival) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AndroidCertificatePal.cs:50]: You're right, this isn't threadsafe. I'll add add+release ref.

File: src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs (hunk 3 above)
Comment (simonrozsival) [reply src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs]: I added `DangerousAddRef`+`DangerousRelease` to make sure the handle isn't disposed by another thread.

**Comment by simonrozsival** [comment]
Failing `runtime-extra-platforms` tests are unrelated

**Review by wfurt — APPROVED** [review]
LGTM. Would X509Certificate2.HasPrivateKey return right value?

**Comment by vcsjones** [comment]
>  Would X509Certificate2.HasPrivateKey return right value?

That is asserted here:

https://github.com/dotnet/runtime/blob/49663a68186010f0e52db3f031431b63db4866e6/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs#L222

And the Android X.509 PAL changes look sensible.

https://github.com/dotnet/runtime/blob/49663a68186010f0e52db3f031431b63db4866e6/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/AndroidCertificatePal.cs#L181

**Comment by simonrozsival** [comment]
@wfurt yes, the AndroidCertificatePal class will return the right value whether it's created the previously existing way or the new way with KeyStore.PrivateKeyEntry.

**Review by vcsjones — APPROVED** [review]

File: src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs [hunk 14]
```diff
@@ -32,6 +32,31 @@ internal static byte[] X509Encode(SafeX509Handle x)
 
             return encoded;
         }
+        [LibraryImport(Libraries.AndroidCryptoNative, EntryPoint = "AndroidCryptoNative_X509IsKeyStorePrivateKeyEntry")]
+        [return: MarshalAs(UnmanagedType.U1)]
```
Comment (akoeplinger) [inline src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs:36]: @simonrozsival the native code returns int32_t here so we should change this to UnmanagedType.Bool (4 bytes), or change the native code to use a C `bool` which is 1 byte. We seem to be using both variants in the Android crypto imports...

Comment (vcsjones) [reply src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs:36]: At least in the Linux and MacOS Desktop PALs, we try to use `int32_t` and not a C `bool` since there is no guarantee by the C standard that it is exactly one byte.

Comment (simonrozsival) [reply src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs:36]: oh, thanks for pointing that out!

Comment (simonrozsival) [reply src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs:36]: https://github.com/dotnet/runtime/pull/103825

Comment (akoeplinger) [reply src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.X509.cs:36]: @vcsjones there are plenty of examples of `UnmanagedType.Bool` even in the Unix PAL :smile: 

https://github.com/search?q=repo%3Adotnet%2Fruntime+UnmanagedType.Bool+path%3Asrc%2Flibraries%2FCommon%2Fsrc%2FInterop%2F+-path%3Asrc%2Flibraries%2FCommon%2Fsrc%2FInterop%2FWindows&type=code
