### PR TITLE
JIT: Fix x86 VectorT_ToScalar(long) when SSE41 not available

### LINKED ISSUE #106143: JIT: Assertion failed 'compIsaSupportedDebugOnly(InstructionSet_SSE41)'
On Windows x86:
```csharp

// Found by Antigen
// Reduced from 62.4 KB to 2.24 KB.
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;
using System.Numerics;
public class TestClass
{
    static byte s_byte_4 = 1;
    static ulong s_ulong_16 = 5;
    static SveMaskPattern s_SveMaskPattern_17 = SveMaskPattern.VectorCount1;
    byte byte_54 = 1;
    int int_59 = 56;
    string string_63 = "V";
    Vector<ulong> v_ulong_95 = Vector<ulong>.Zero;
    public void Method0()
    {
        unchecked
        {
            byte byte_191 = 0;
            string string_200 = "Q5ZXJ81";
            try
            {
                try
                {
                    int __loopvar2 = 15-4;
                }
                catch (System.OverflowException)
                {
                    for (; int_59 < Sve.SaturatingIncrementBy16BitElementCount(15*4, byte_54 >>= 15<<4, s_SveMaskPattern_17); string_63 = string_63 += string_200)
                    {
                        if (15*4== byte_191 - s_byte_4)
                        {
                            switch (15<<4)
                            {
                                case -1:
                                {
                                    break;
                                }
                                case 3:
                                {
                                    break;
                                }
                                case 1:
                                {
                                    break;
                                }
                                default:
                                {
                                    s_ulong_16 |= Sve.SaturatingIncrementBy32BitElementCount(Vector.ToScalar(v_ulong_95), 15|4, s_SveMaskPattern_17);
                                    break;
                                }
                            }
                        }
                        else
                        {
                        }
                    }
                }
            }
            finally
            {
            }
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}
/*
Got output diff:
--------- Baseline ---------  
Environment:
--------- Test ---------  
Environment:
set DOTNET_EnableSSSE3=0
set DOTNET_AltJit=Method0
Assert failure(PID 17808 [0x00004590], Thread: 33592 [0x8338]): Assertion failed 'compIsaSupportedDebugOnly(InstructionSet_SSE41)' in 'TestClass:Method0():this' during 'Importation' (IL size 127; hash 0x46e9aa75; Tier0-FullOpts)
    File: C:\wk\runtime\src\coreclr\jit\gentree.cpp:23234
    Image: C:\wk\runtime\artifacts\tests\coreclr\windows.x86.Checked\Tests\Core_Root\corerun.exe
*/
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
When handling VectorT_ToScalar(long) on x86, ensure SSE41 is available; if not, resort to the software fallback.

Fixes #106143.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@tannergooding PTAL
cc @dotnet/jit-contrib 

The antigen test case isn't too bad here. I could probably adapt it into a test case. Let me know if you think adding it is useful.

File: src/coreclr/jit/simdashwintrinsic.cpp [hunk 1]
```diff
@@ -890,6 +890,14 @@ GenTree* Compiler::impSimdAsHWIntrinsicSpecial(NamedIntrinsic       intrinsic,
                 return op1;
             }
 
+#if defined(TARGET_X86)
+            if ((intrinsic == NI_VectorT_ToScalar) && varTypeIsLong(simdBaseType) &&
+                !compOpportunisticallyDependsOn(InstructionSet_SSE41))
+            {
+                return nullptr;
+            }
```
Comment (tannergooding) [inline src/coreclr/jit/simdashwintrinsic.cpp:898]: nit: Most similar checks are higher up in a switch case before we ever get to this point

It's not necessarily important that we move that up there however, especially since the rest of this file should be getting removed in early .NET 10 and so there isn't any long term risk of breakage from other code or refactorings. I'll leave it up to you on if you want to just keep it "as is" or move it up with the rest of the handling.


-- For context, this file is the last of the `SimdAsHWIntrinsic` logic which now that Vector2/3/4 are in managed only exists to support `Vector<T>`. The plan for .NET 10 is to remove it and just forward by name to the Vector128/256/512 paths instead so we can reduce the cost and risk of bugs like the one this is fixing.

**Review by tannergooding — APPROVED** [review]
LGTM.

Don't have a strong preference on the antigen test. It'd be nice to have a regression test for this scenario, but the antigen one is also testing exclusively SVE but exposing an x86 issue from the AltJit.

I think rather it'd be better to find a smaller repro (might just be something like `[NoInline] public static long M(Vector<T> x) => (x + x).ToScalar()` would work), but wouldn't spend too many cycles on it

File: src/coreclr/jit/simdashwintrinsic.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/simdashwintrinsic.cpp:898]: Ok I will move it up.
