### PR TITLE
Fix use of uninitialized `bool` value

### LINKED ISSUE #100559: Uninitialized memory usage in MethodTableBuilder
PR #85743 introduced the following code: 
 https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/methodtablebuilder.cpp#L2786-L2788

``` C++
        bool hasGenericMethodArgsComputed;
        bool hasGenericMethodArgs = this->GetModule()->m_pMethodIsGenericMap->IsGeneric(tok, &hasGenericMethodArgsComputed);
        if (!hasGenericMethodArgsComputed)
        {
```

On the other side of ReadyToRun_MethodIsGenericMap::IsGeneric:  https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/readytoruninfo.cpp#L1930-L1947

This method does not assign `foundResult`/`hasGenericMethodArgsComputed` in most cases, leading to us branching off of an uninitialized value.  I wasn't fully confident in what the intent of the `foundResult` variable should be (compared to what is being returned) to make a fix myself.  Thanks!

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes https://github.com/dotnet/runtime/issues/100559

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

File: src/coreclr/vm/readytoruninfo.cpp [hunk 1]
```diff
@@ -1929,20 +1929,17 @@ bool ReadyToRun_TypeGenericInfoMap::HasConstraints(mdTypeDef input, bool *foundR
...
 bool ReadyToRun_MethodIsGenericMap::IsGeneric(mdMethodDef input, bool *foundResult) const
 {
-#ifdef DACCESS_COMPILE
-    *foundResult = false;
-    return false;
-#else
+#ifndef DACCESS_COMPILE
     uint32_t rid = RidFromToken(input);
-    if ((rid > MethodCount) || (rid == 0))
+    if ((rid <= MethodCount) && (rid != 0))
```
Comment (fanyang-mono) [inline src/coreclr/vm/readytoruninfo.cpp:1934]: Missing return and assigning value to `foundResult` when this condition is not met.

Comment (lambdageek) [reply src/coreclr/vm/readytoruninfo.cpp:1934]: @fanyang-mono the return and assginment are after the `#endif`.  This PR unifies the false case and the `defined(DACCESS_COMPILE)` cases
