### PR TITLE
[mono][interp] Update mono struct lowering to use MonoMemoryManager

### LINKED ISSUE #102478: Abort on mono in SwiftErrorHandling
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=683209
Build error leg or test failing: Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd
Pull request: https://github.com/dotnet/runtime/pull/102472

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Got a SIGSEGV while executing native code",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=682138
**Error message validated:** `[Got a SIGSEGV while executing native code`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/21/2024 5:19:59 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[685054](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685054)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685054&view=ms.vss-test-web.build-test-results-tab&runId=17004972&resultId=104467)|dotnet/runtime#102591|
|[685021](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685021)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685021&view=ms.vss-test-web.build-test-results-tab&runId=17004384&resultId=110114)|dotnet/runtime#102180|
|[684969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684969)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684969&view=ms.vss-test-web.build-test-results-tab&runId=17003062&resultId=105858)|dotnet/runtime#102589|
|[684888](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684888)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684888&view=ms.vss-test-web.build-test-results-tab&runId=16999982&resultId=109977)|dotnet/runtime#102295|
|[684830](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684830)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684830&view=ms.vss-test-web.build-test-results-tab&runId=16998992&resultId=110114)|dotnet/runtime#102489|
|[684779](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684779)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684779&view=ms.vss-test-web.build-test-results-tab&runId=16997996&resultId=110114)|dotnet/runtime#102364|
|[684784](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684784)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684784&view=ms.vss-test-web.build-test-results-tab&runId=16997892&resultId=109977)|dotnet/runtime#102548|
|[684676](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684676)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684676&view=ms.vss-test-web.build-test-results-tab&runId=16995684&resultId=109401)||
|[684639](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684639)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684639&view=ms.vss-test-web.build-test-results-tab&runId=16994650&resultId=104858)|dotnet/runtime#101938|
|[684588](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684588)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684588&view=ms.vss-test-web.build-test-results-tab&runId=16993862&resultId=110114)|dotnet/runtime#102410|
|[684520](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684520)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684520&view=ms.vss-test-web.build-test-results-tab&runId=16992594&resultId=109977)|dotnet/runtime#102295|
|[684523](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684523)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684523&view=ms.vss-test-web.build-test-results-tab&runId=16992552&resultId=107401)|dotnet/runtime#102364|
|[682089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682089)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682089&view=ms.vss-test-web.build-test-results-tab&runId=16991732&resultId=110114)|dotnet/runtime#99818|
|[684475](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684475)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684475&view=ms.vss-test-web.build-test-results-tab&runId=16991566&resultId=109977)|dotnet/runtime#102548|
|[684108](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684108)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684108&view=ms.vss-test-web.build-test-results-tab&runId=16990596&resultId=110114)|dotnet/runtime#102490|
|[684091](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684091)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684091&view=ms.vss-test-web.build-test-results-tab&runId=16990606&resultId=104690)|dotnet/runtime#102488|
|[684439](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684439)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684439&view=ms.vss-test-web.build-test-results-tab&runId=16990242&resultId=110114)|dotnet/runtime#102499|
|[684400](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684400)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684400&view=ms.vss-test-web.build-test-results-tab&runId=16989636&resultId=108401)|dotnet/runtime#102570|
|[684391](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684391)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684391&view=ms.vss-test-web.build-test-results-tab&runId=16989492&resultId=110114)|dotnet/runtime#102547|
|[684369](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684369)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684369&view=ms.vss-test-web.build-test-results-tab&runId=16989134&resultId=109977)|dotnet/runtime#102262|
|[684352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684352)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684352&view=ms.vss-test-web.build-test-results-tab&runId=16988822&resultId=104674)|dotnet/runtime#102410|
|[684312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684312)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684312&view=ms.vss-test-web.build-test-results-tab&runId=16988044&resultId=110807)|dotnet/runtime#101796|
|[2458102](https://dev.azure.com/dnceng/internal/_build/results?buildId=2458102)|dotnet-runtime|[x64.micro_mono.net9.0.Partition8.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2458102&view=ms.vss-test-web.build-test-results-tab&runId=53640973&resultId=100050)||
|[684293](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684293)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684293&view=ms.vss-test-web.build-test-results-tab&runId=16987340&resultId=104836)|dotnet/runtime#100056|
|[684265](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684265)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684265&view=ms.vss-test-web.build-test-results-tab&runId=16987138&resultId=104264)|dotnet/runtime#102547|
|[684229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684229)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684229&view=ms.vss-test-web.build-test-results-tab&runId=16986328&resultId=110114)|dotnet/runtime#101801|
|[684250](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684250)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684250&view=ms.vss-test-web.build-test-results-tab&runId=16986362&resultId=104687)|dotnet/runtime#102489|
|[684145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684145)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684145&view=ms.vss-test-web.build-test-results-tab&runId=16984902&resultId=106847)|dotnet/runtime#102493|
|[684020](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684020)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=684020&view=ms.vss-test-web.build-test-results-tab&runId=16978556&resultId=103401)|dotnet/runtime#102548|
|[683993](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683993)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683993&view=ms.vss-test-web.build-test-results-tab&runId=16977660&resultId=110114)|dotnet/runtime#102551|
|[683982](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683982)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683982&view=ms.vss-test-web.build-test-results-tab&runId=16977398&resultId=107178)|dotnet/runtime#101938|
|[683960](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683960)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683960&view=ms.vss-test-web.build-test-results-tab&runId=16977100&resultId=107401)|dotnet/runtime#102499|
|[683908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683908)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683908&view=ms.vss-test-web.build-test-results-tab&runId=16975774&resultId=110114)|dotnet/runtime#102547|
|[683890](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683890)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683890&view=ms.vss-test-web.build-test-results-tab&runId=16974932&resultId=212674)||
|[2457902](https://dev.azure.com/dnceng/internal/_build/results?buildId=2457902)|dotnet-runtime|[release.Partition8.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2457902&view=ms.vss-test-web.build-test-results-tab&runId=53640035&resultId=100050)||
|[682617](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682617)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682617&view=ms.vss-test-web.build-test-results-tab&runId=16974332&resultId=109538)|dotnet/runtime#102487|
|[683755](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683755)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683755&view=ms.vss-test-web.build-test-results-tab&runId=16972434&resultId=110114)|dotnet/runtime#102539|
|[683730](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683730)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683730&view=ms.vss-test-web.build-test-results-tab&runId=16971750&resultId=110114)|dotnet/runtime#102410|
|[683720](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683720)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683720&view=ms.vss-test-web.build-test-results-tab&runId=16971490&resultId=104294)|dotnet/runtime#102536|
|[683715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683715)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683715&view=ms.vss-test-web.build-test-results-tab&runId=16971292&resultId=104467)|dotnet/runtime#102364|
|[682742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682742)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682742&view=ms.vss-test-web.build-test-results-tab&runId=16970840&resultId=107571)|dotnet/runtime#102493|
|[682643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682643)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682643&view=ms.vss-test-web.build-test-results-tab&runId=16970478&resultId=108401)|dotnet/runtime#102488|
|[682680](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682680)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682680&view=ms.vss-test-web.build-test-results-tab&runId=16970290&resultId=107401)|dotnet/runtime#102490|
|[2457660](https://dev.azure.com/dnceng/internal/_build/results?buildId=2457660)|dotnet-runtime|[release.Partition8.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2457660&view=ms.vss-test-web.build-test-results-tab&runId=53638353&resultId=100050)||
|[683209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683209)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683209&view=ms.vss-test-web.build-test-results-tab&runId=16968074&resultId=110114)|dotnet/runtime#102520|
|[683553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683553)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683553&view=ms.vss-test-web.build-test-results-tab&runId=16967320&resultId=110797)|dotnet/runtime#102364|
|[683262](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683262)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683262&view=ms.vss-test-web.build-test-results-tab&runId=16959440&resultId=212674)||
|[683433](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683433)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683433&view=ms.vss-test-web.build-test-results-tab&runId=16965168&resultId=107434)|dotnet/runtime#102499|
|[683428](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683428)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683428&view=ms.vss-test-web.build-test-results-tab&runId=16965056&resultId=107434)|dotnet/runtime#102499|
|[2457311](https://dev.azure.com/dnceng/internal/_build/results?buildId=2457311)|dotnet-runtime|[release.Partition8.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2457311&view=ms.vss-test-web.build-test-results-tab&runId=53636603&resultId=100050)||
|[683154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683154)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683154&view=ms.vss-test-web.build-test-results-tab&runId=16957402&resultId=104858)|dotnet/runtime#102180|
|[683141](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683141)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683141&view=ms.vss-test-web.build-test-results-tab&runId=16957312&resultId=110114)|dotnet/runtime#102516|
|[683123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683123)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683123&view=ms.vss-test-web.build-test-results-tab&runId=16957092&resultId=110114)|dotnet/runtime#102475|
|[683105](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683105)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683105&view=ms.vss-test-web.build-test-results-tab&runId=16956972&resultId=110612)|dotnet/runtime#102508|
|[683085](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683085)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683085&view=ms.vss-test-web.build-test-results-tab&runId=16956204&resultId=102525)|dotnet/runtime#102424|
|[683043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683043)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683043&view=ms.vss-test-web.build-test-results-tab&runId=16955934&resultId=110797)|dotnet/runtime#102498|
|[682938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682938)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682938&view=ms.vss-test-web.build-test-results-tab&runId=16951030&resultId=110797)|dotnet/runtime#102248|
|[682872](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682872)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682872&view=ms.vss-test-web.build-test-results-tab&runId=16949558&resultId=101377)|dotnet/runtime#102262|
|[682671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682671)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682671&view=ms.vss-test-web.build-test-results-tab&runId=16945732&resultId=104033)|dotnet/runtime#101801|
|[2457064](https://dev.azure.com/dnceng/internal/_build/results?buildId=2457064)|dotnet-runtime|[release.Partition8.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2457064&view=ms.vss-test-web.build-test-results-tab&runId=53635417&resultId=100050)||
|[682649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682649)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682649&view=ms.vss-test-web.build-test-results-tab&runId=16944316&resultId=110114)|dotnet/runtime#102489|
|[682524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682524)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682524&view=ms.vss-test-web.build-test-results-tab&runId=16938318&resultId=104326)|dotnet/runtime#102392|
|[682414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682414)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682414&view=ms.vss-test-web.build-test-results-tab&runId=16935004&resultId=212673)||
|[2456883](https://dev.azure.com/dnceng/internal/_build/results?buildId=2456883)|dotnet-runtime|[release.Partition8.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2456883&view=ms.vss-test-web.build-test-results-tab&runId=53634617&resultId=100050)||
|[682357](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682357)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682357&view=ms.vss-test-web.build-test-results-tab&runId=16933430&resultId=110114)|dotnet/runtime#102475|
|[682341](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682341)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682341&view=ms.vss-test-web.build-test-results-tab&runId=16933270&resultId=110114)|dotnet/runtime#102424|
|[682269](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682269)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682269&view=ms.vss-test-web.build-test-results-tab&runId=16931496&resultId=104467)|dotnet/runtime#102424|
|[682229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682229)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682229&view=ms.vss-test-web.build-test-results-tab&runId=16930778&resultId=110114)|dotnet/runtime#102476|
|[681910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681910)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681910&view=ms.vss-test-web.build-test-results-tab&runId=16930028&resultId=107401)|dotnet/runtime#102180|
|[682154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682154)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682154&view=ms.vss-test-web.build-test-results-tab&runId=16929386&resultId=110797)|dotnet/runtime#102364|
|[682138](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682138)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682138&view=ms.vss-test-web.build-test-results-tab&runId=16928972&resultId=108401)|dotnet/runtime#102472|
|[681878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681878)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681878&view=ms.vss-test-web.build-test-results-tab&runId=16927120&resultId=101393)|dotnet/runtime#102271|
|[681751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681751)|dotnet/runtime|[Microsoft.Extensions.Primitives.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681751&view=ms.vss-test-web.build-test-results-tab&runId=16926420&resultId=163881)||
|[681854](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681854)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681854&view=ms.vss-test-web.build-test-results-tab&runId=16920226&resultId=110797)||
|[681837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681837)|dotnet/runtime|[System.Composition.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681837&view=ms.vss-test-web.build-test-results-tab&runId=16919170&resultId=155636)||
|[681841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681841)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681841&view=ms.vss-test-web.build-test-results-tab&runId=16919740&resultId=109977)|dotnet/runtime#102364|
|[681713](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681713)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681713&view=ms.vss-test-web.build-test-results-tab&runId=16916774&resultId=104690)|dotnet/runtime#102295|
|[681514](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681514)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681514&view=ms.vss-test-web.build-test-results-tab&runId=16913308&resultId=109977)|dotnet/runtime#102366|
|[681495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681495)|dotnet/runtime|[Interop/Swift/SwiftErrorHandling/SwiftErrorHandling/SwiftErrorHandling.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681495&view=ms.vss-test-web.build-test-results-tab&runId=16912852&resultId=109890)|dotnet/runtime#102363|
|[681132](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681132)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681132&view=ms.vss-test-web.build-test-results-tab&runId=16902468&resultId=212672)||
|[680976](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680976)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680976&view=ms.vss-test-web.build-test-results-tab&runId=16899598&resultId=200081)|dotnet/runtime#102440|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|36|81|81|

### PR DESCRIPTION
**Pull request by kotlarmilos**
## Description

This PR updates `mono_metadata_signature_dup_new_params` to use `MonoMemoryManager` instead of `MonoMemPool`. The mempool can be detroyed after method is compiled.

Fixes https://github.com/dotnet/runtime/issues/102478

### CODE REVIEW

**Review by matouskozak — APPROVED** [review]
Thanks a lot for the quick fix. The failing test was caused by my PR https://github.com/dotnet/runtime/pull/102143 and the fact that at the moment when the CI ran on my PR the `SwiftErrorHandling` tests were disabled so it didn't get caught before merging.

File: src/mono/mono/mini/method-to-ir.c [hunk 1]
```diff
@@ -7585,7 +7585,7 @@ mono_method_to_ir (MonoCompile *cfg, MonoMethod *method, MonoBasicBlock *start_b
 				}
 
 				// Create a new dummy signature with the lowered arguments				
-				fsig = mono_metadata_signature_dup_new_params (cfg->mempool, fsig, new_param_count, (MonoType**)new_params->data);
+				fsig = mono_metadata_signature_dup_new_params (cfg->mem_manager, fsig, new_param_count, (MonoType**)new_params->data);
```
Comment (BrzVlad) [inline src/mono/mono/mini/method-to-ir.c:7588]: Is this really needed though ? While interpreter requires the signature to be alive after the code is compiled, I don't think jit code has this constraint. This change prevents the signature from being freed as it was done before.

Comment (matouskozak) [reply src/mono/mono/mini/method-to-ir.c]: We could use similar approach as with `mono_metadata_signature_dup_internal` https://github.com/dotnet/runtime/blob/b1b3e85dbf2d52b70d8c44c663e83b5c320c6abd/src/mono/mono/metadata/metadata.c#L2429 and use `mempool` for JIT and `mem_manager` for interpreter.

Comment (kotlarmilos) [reply src/mono/mono/mini/method-to-ir.c]: Thanks, updated.

File: src/mono/mono/metadata/metadata.c [hunk 2]
```diff
@@ -2559,13 +2576,13 @@ mono_metadata_signature_dup_delegate_invoke_to_target (MonoMethodSignature *sig)
  * @return the new \c MonoMethodSignature structure.
  */
 MonoMethodSignature*
-mono_metadata_signature_dup_new_params (MonoMemPool *mp, MonoMethodSignature *sig, uint32_t num_params, MonoType **new_params)
+mono_metadata_signature_dup_new_params (MonoImage *image, MonoMemPool *mp, MonoMemoryManager *mem_manager, MonoMethodSignature *sig, uint32_t num_params, MonoType **new_params)
```
Comment (BrzVlad) [inline src/mono/mono/metadata/metadata.c:2579]: Looks like we can drop the image arg here.

Comment (kotlarmilos) [reply src/mono/mono/metadata/metadata.c]: Yes, I added it for future extensibility, but not needed at this point.
