### PR TITLE
[MonoAOTCompiler] more properties & custom WorkingDirectory

### LINKED ISSUE #56163: .NET 6 Android AOT fails on certain folder names
### Description

Create a `dotnet new android` project in a folder named such as `BuildAotApplicationAndBundle AndÜmläüts_arm64-v8a_False_True`.

Build with `-c Release -p:RunAOTCompilation=true`, and you get the error:

```
Precompiling failed for C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplicationAndBundle AndÜmläüts_arm64-v8a_False_True\obj\Release\android-arm64\linked\System.Private.CoreLib.dll: Error: Loaded assembly 'C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplicationAndBundle And├£ml├ñ├╝ts_arm64-v8a_False_True\obj\Release\android-arm64\linked\System.Private.CoreLib.dll' doesn't match original file name 'C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplicationAndBundle And▄mlΣⁿts_arm64-v8a_False_True\obj\Release\android-arm64\linked\System.Private.CoreLib.dll'. Set MONO_PATH to the assembly's location. [C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplicationAndBundle AndÜmläüts_arm64-v8a_False_True\UnnamedProject.csproj]
```

A screenshot of the `.binlog` viewer shows odd characters as well:

image

Logs: [msbuild.zip](https://github.com/dotnet/runtime/files/6863886/msbuild.zip)

### Configuration

```
> dotnet --version
6.0.100-rc.1.21369.3
```

I believe this would also happen in Preview 7.

### Regression?

No, Android AOT is a new feature.

/cc @akoeplinger @steveisok

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://github.com/dotnet/runtime/issues/56163

PR #58523 fixed something on Windows, but it didn't actually address
our issues on Android.

A directory name like `foo Ümläüts` fails:

* `mkdir 'foo Ümläüts' ; cd 'foo Ümläüts'`
* `dotnet new android`
* `dotnet build -c Release -p:RunAOTCompilation=true` (adding
  `-p:EnableLLVM=true` complicates further)

The error:

    Precompiling failed for C:\src\foo Ümläüts\obj\Release\android-arm64\linked\System.Private.CoreLib.dll: Error: Loaded assembly 'C:\src\foo ├£ml├ñ├╝ts\obj\Release\android-arm64\linked\System.Private.CoreLib.dll' doesn't match original file name 'C:\foo ▄mlΣⁿts\obj\Release\android-arm64\linked\System.Private.CoreLib.dll'. Set MONO_PATH to the assembly's location.

Reviewing the existing AOT implementation in Xamarin.Android, I found
out *why* Xamarin.Android works:

    [AOT] response file obj\Release\120\aot\arm64-v8a\App36.dll\response.txt: --llvm "--aot=temp-path=obj\Release\120\aot\arm64-v8a\App36.dll,llvm-path=C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Xamarin\Android,outfile=obj\Release\120\aot\arm64-v8a\libaot-App36.dll.so,msym-dir=obj\Release\120\aot\arm64-v8a,asmwriter,mtriple=aarch64-linux-android,tool-prefix=C:\Program Files (x86)\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-,ld-name=ld.EXE,ld-flags=\"-LC:\Program Files (x86)\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\lib\gcc\aarch64-linux-android\4.9.x\";\"-LC:\Program Files (x86)\Android\android-sdk\ndk-bundle\platforms\android-21\arch-arm64\usr\lib\";\"C:\Program Files (x86)\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\lib\gcc\aarch64-linux-android\4.9.x\libgcc.a\";\"C:\Program Files (x86)\Android\android-sdk\ndk-bundle\platforms\android-21\arch-arm64\usr\lib\libc.so\";\"C:\Program Files (x86)\Android\android-sdk\ndk-bundle\platforms\android-21\arch-arm64\usr\lib\libm.so\"" C:\Users\jopepper\source\repos\App36\App36\obj\Release\120\android\assets\shrunk\App36.dll

1. Xamarin.Android passes *relative* paths. The `foo Ümläüts`
   directory name doesn't even come into play for some arguments.

2. With LLVM, `ld-flags` contains a `;`.

The existing code splits on `;` and joins on `,`:

https://github.com/dotnet/runtime/blob/25c207351c4f57cf2daa98caaf327a8b8d83edb8/src/tasks/AotCompilerTask/MonoAOTCompiler.cs#L505-L509

So we lose any `;` delimiters for the `ld-flags` value, they get
replaced by `,`.

I think the solution here is:

1. Add several missing properties to `<MonoAOTCompiler/>` so we don't
   have to rely on the `%(AotArguments)` item metadata. No splitting
   on `;` would be required, `ld-flags` can be passed in and used as-is.

2. Add a new `WorkingDirectory` property. When this is set, assume
   paths passed in might be relative -- and don't transform paths by
   calling `Path.GetFullPath()`.

Lastly, I fixed a place where the UTF8 encoding wasn't passed when
MSBuild logging the response file.

These changes I tried to make in a way where this shouldn't break
other .NET workloads like wasm. If existing MSBuild targets call this
task (not using the new properties), the behavior should remain
unchanged.

I tested these changes by commiting a modified `MonoAOTCompiler.dll`:

https://github.com/xamarin/xamarin-android/pull/6562

I'm able to enable several AOT tests related to dotnet/runtime#56163.

### CODE REVIEW

**Comment by steveisok** [comment]
The runtime-manual failures are unrelated.  The AOT legs for wasm and iOS were successful.

@radical and @akoeplinger please review.

**Review by steveisok — APPROVED** [review]

File: src/tasks/AotCompilerTask/MonoAOTCompiler.cs [hunk 1]
```diff
@@ -191,12 +191,39 @@ public class MonoAOTCompiler : Microsoft.Build.Utilities.Task
...
+
+    /// <summary>
+    /// Passes ld-name to the AOT compiler, for use with UseLLVM=true
+    /// </summary>
+    public string? LdName { get; set; }
+
+    /// <summary>
+    /// Passes ld-flags to the AOT compiler, for use with UseLLVM=true
+    /// </summary>
+    public string? LdFlags { get; set; }
```
Comment (radical) [inline src/tasks/AotCompilerTask/MonoAOTCompiler.cs:212]: I wonder if it might be better to have a `ITaskItem? CommonAotArguments` with metadata which act as the key-value pairs to pass to `--aot`.

Comment (jonathanpeppers) [reply src/tasks/AotCompilerTask/MonoAOTCompiler.cs:212]: `LdFlags` will contain a `;` on Android. So it seems like using item metadata would always have an issue?

Our usage is now:
```xml
<MonoAOTCompiler
    Triple="$(_Triple)"
    ToolPrefix="$(_ToolPrefix)"
    MsymPath="$(_MsymPath)"
    Assemblies="@(_MonoAOTAssemblies)"
    CompilerBinaryPath="$(_MonoAOTCompilerPath)"
    DisableParallelAot="$(_DisableParallelAot)"
    IntermediateOutputPath="$(IntermediateOutputPath)"
    LibraryFormat="So"
    Mode="$(AndroidAotMode)"
    OutputDir="$(IntermediateOutputPath)aot\"
    OutputType="Library"
    UseAotDataFile="false"
    UseLLVM="$(EnableLLVM)"
    LLVMPath="$(_LLVMPath)"
    LdName="$(_LdName)"
    LdFlags="$(_LdFlags)"
    WorkingDirectory="$(MSBuildProjectDirectory)"
    AotArguments="$(AndroidAotAdditionalArguments)">
  <Output TaskParameter="CompiledAssemblies" ItemName="_AotCompiledAssemblies" />
  <Output TaskParameter="FileWrites"         ItemName="FileWrites" />
</MonoAOTCompiler>
```

But maybe `$(AndroidAotAdditionalArguments)` could be passed in a different way? What would the XML look like for `ITaskItem? CommonAotArguments`?

Comment (radical) [reply src/tasks/AotCompilerTask/MonoAOTCompiler.cs:212]: > `LdFlags will contain a ; on Android. So it seems like using item metadata would always have an issue?`

We won't split the metadata on `CommonAotArguments`.
As for the metadata names, we could either use the real argument name, like` <ld-flags>foo; bar</ld-flags>`, or we could have `<LdFlags>foo; bar</LdFlags>` and convert to the real name in the task.

```xml
  <CommonAotArguments Include="common">
    <ld-flags>foo;bar</ld-flags>
    <ld-name>xyz</ld-name>
  </CommonAotArguments>
```
or
```xml
  <CommonAotArguments Include="common">
    <LdFlags>foo;bar</LdFlags>
    <LdName>xyz</LdName>
  </CommonAotArguments>
```

And you could have a `<PassVerbatim>..</PassVerbatim>` metadata (or better name) for just any additional string to be passed to `--aot`.

Feel free to push back, I'm just thinking aloud.

Comment (jonathanpeppers) [reply src/tasks/AotCompilerTask/MonoAOTCompiler.cs:212]: The weird part about using `@(CommonAotArguments)`, is that you put `Include=""` with any random word inside. You can't leave out `Include`, or that would be an empty item group. I also like the idea of having C# properties, as it checks for typos -- you'll get an MSBuild error if you put `LdlFlags` instead of `LdFlags`.

Adding something like `@(CommonAotArguments)` might be ok if there is some unknown set. At least for Android, these changes now include every parameter we use. Are there many more not represented here?

**Review by radical — APPROVED** [review]

**Comment by jonathanpeppers** [comment]
@steveisok how would we get this on the `mauipre` branch? Is there a magic comment to backport it?
