### PR TITLE
JIT: Switch GetElement and WithElement to native sized indices

### LINKED ISSUE #118974: [interp] Calling convention disagreement when calling R2R'd Vector2.get_Item from interpreted code
The R2R'd code for Vector2.get_Item believes the high bits of rdx will be zeroes - it contains an int32, the index. The r2r'd code first range checks edx and then happily does a load using rdx (instead of edx) to compute an address. Disassembly:

```asm
00007FFC978AB610 48 83 EC 38          sub         rsp,38h  
00007FFC978AB614 F2 0F 10 01          movsd       xmm0,mmword ptr [rcx]  ; rcx is the vector, containing {1,2}
00007FFC978AB618 83 FA 02             cmp         edx,2  ; edx is 0 here
00007FFC978AB61B 73 10                jae         00007FFC978AB62D  
00007FFC978AB61D 0F 29 44 24 20       movaps      xmmword ptr [rsp+20h],xmm0  
00007FFC978AB622 F3 0F 10 44 94 20    movss       xmm0,dword ptr [rsp+rdx*4+20h]  ; we crash here
00007FFC978AB628 48 83 C4 38          add         rsp,38h  
00007FFC978AB62C C3                   ret  
00007FFC978AB62D B9 15 00 00 00       mov         ecx,15h  
00007FFC978AB632 FF 15 B0 CB CD 00    call        qword ptr [7FFC985881E8h]  
```

Looking at the arguments on the interpreter stack before the call, we can see the high bits of index on the interpreter stack are garbage, so it's natural that rdx has the same garbage in its high bits. I think the interpreter is probably behaving correctly here, but if jitcode expects us to zero the high bits then we probably need to zero them somewhere, maybe in the call stub routines or something.

Image

Call stack:
```
System_Private_CoreLib!System.Numerics.Vector2.get_Item+0x12
coreclr!CallJittedMethodRetDouble+0x17
coreclr!InvokeCompiledMethod+0x4ed
coreclr!InterpExecMethod+0x8914
coreclr!ExecuteInterpretedMethod+0x209
coreclr!InterpreterStubRetI8+0x12
coreclr!InterpreterStub+0xcc
coreclr!CallDescrWorkerInternal+0x83
coreclr!CallDescrWorkerWithHandler+0x137
coreclr!MethodDescCallSite::CallTargetWorker+0xbd8
coreclr!MethodDescCallSite::Call_RetArgSlot+0x11f
coreclr!RunMainInternal+0x2a9
```

This appears to be inside TestCallingConvention3Rev in Interpreter.cs

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #118974

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -23270,6 +23273,7 @@ GenTree* Compiler::gtNewSimdGetElementNode(
     var_types      simdBaseType = JitType2PreciseVarType(simdBaseJitType);
 
     assert(varTypeIsArithmetic(simdBaseType));
+    assert(op2->TypeIs(TYP_I_IMPL));
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp]: Just noting here, for explanation....

The reason that `gtNewSimdGetElementNode` took `TYP_INT` is because the underlying instruction takes `TYP_BYTE`.

The only time we actually consume it as `TYP_I_IMPL` is if it is non-constant and we must fallback to spilling the vector to memory and using the index dynamically.

File: src/coreclr/jit/hwintrinsic.cpp [hunk 2]
```diff
@@ -1590,7 +1590,7 @@ GenTree* Compiler::addRangeCheckForHWIntrinsic(GenTree* immOp, int immLowerBound
     // The value of (immUpperBound - immLowerBound + 1) is denoted as adjustedUpperBound.
 
     const ssize_t adjustedUpperBound     = (ssize_t)immUpperBound - immLowerBound + 1;
-    GenTree*      adjustedUpperBoundNode = gtNewIconNode(adjustedUpperBound, TYP_INT);
+    GenTree*      adjustedUpperBoundNode = gtNewIconNode(adjustedUpperBound, TYP_I_IMPL);
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsic.cpp]: This ends up working because `int32 - nativeint` is defined, correct?

We have a lot of APIs that take `TYP_UBYTE` from the managed signature and which will only ever be `[0, 255]`.

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/hwintrinsic.cpp (hunk 2 above)
Comment (jakobbotsch) [reply src/coreclr/jit/hwintrinsic.cpp]: Hmm no, this needs a few more changes. I had missed `addRangeCheckForHWIntrinsic` isn't only used from `GetElement`/`WithElement`.

File: src/coreclr/jit/lowerxarch.cpp [hunk 3]
```diff
@@ -2184,17 +2184,30 @@ GenTree* Lowering::LowerHWIntrinsic(GenTreeHWIntrinsic* node)
                 if (!op2->OperIsConst())
                 {
                     // Extract allows the full range while GetElement only allows
-                    // 0-3, so we need to mask the index here so codegen works.
+                    // 0-3, so we need to mask the index here so codegen works. We also may need
+                    // an extension since GetElement takes a native sized index.
 
-                    GenTree* msk = comp->gtNewIconNode(3, TYP_INT);
+                    if (!op2->TypeIs(TYP_I_IMPL))
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp]: This change is getting pretty complex for something that only impacts a very particular path and is potentially going to cause problems since instructions like `X86Base_Extract` do not take `I_IMPL`, they explicitly take `TYP_INT` and encode it as a contained 8-bit immediate.

Would it be better to just insert `TYP_INT -> TYP_I_IMPL` cast here in lowering for `GetElement`/`WithElement` in the case they are preserved as-is?

This only occurs if the vector has to be accessed from memory, which means it was either already spilled or had to be spilled because the index was not a constant.

Comment (jakobbotsch) [reply src/coreclr/jit/lowerxarch.cpp]: > Would it be better to just insert TYP_INT -> TYP_I_IMPL cast here in lowering for GetElement/WithElement in the case they are preserved as-is?

Yeah, I think that's better to do it like that.

Will that only be necessary for xarch?

Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp]: It's likely needed for both.

Most platforms only allow constant extract/insert for the instructions and so have to spill and dynamically read/write from memory otherwise: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lowerarmarch.cpp#L1682

It's the dynamic read/write where we need it to be a "full register" since the specialized addressing modes typically only allow full registers.

File: src/coreclr/jit/lower.cpp [hunk 4]
```diff
@@ -11682,6 +11682,39 @@ GenTree* Lowering::InsertNewSimdCreateScalarUnsafeNode(var_types   simdType,
...
+//   Prepare to use an index for address calculations by ensuring it is native sized.
+//
+//  Arguments:
+//    index - The index that may be an int32
+//
+// Returns:
+//    The node itself, or a cast added on top of the node to perform normalization.
+//
+// Remarks:
+//    May insert a cast or may bash the node type in place for constants.
```
Comment (tannergooding) [inline src/coreclr/jit/lower.cpp]: nit: Explicitly call out this doesn't replace the use?

File: src/coreclr/jit/lowerxarch.cpp [hunk 5]
```diff
@@ -4890,6 +4890,9 @@ GenTree* Lowering::LowerHWIntrinsicGetElement(GenTreeHWIntrinsic* node)
         return LowerNode(node);
     }
 
+    op2         = NormalizeIndexToNativeSized(op2);
+    node->Op(2) = op2;
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:4894]: Is this "too early"? There's paths further down that are expecting it to be kept as a constant and will consume/contain it directly.

I'd expect we need it under the `OperIs(GT_IND)` path and the `!op2->IsConst` path, but we want to keep it as `TYP_INT` otherwise since the containment is expecting 8-bits

Comment (jakobbotsch) [reply src/coreclr/jit/lowerxarch.cpp:4894]: I think the contained native sized constant should work fine (after all once contained, we should just use the node to extract the integer constant, so the actual type on it shouldn't matter). It would be confusing to me if the expected type of an operand depends on factors like these. I think it is much better for understandability of the IR if we can say something like "the index operand of `GetElement/WithElement` is native sized after lowering".

Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp:4894]: > "the index operand of GetElement/WithElement is native sized after lowering

I agree. The consideration here, however, was that the logic further down will rewrite this from `GetElement`/`WithElement` to something like `Sse41.Extract(vector, cns)` or `Sse41.Extract(Avx.ExtractVector128(vector, cns1), cns2)` instead.

If it's all working, that's great and fine; just want to ensure that the nuance is being considered since the other nodes are really setup to expect something explicitly constrained to `[0, 255]`.

Comment (jakobbotsch) [reply src/coreclr/jit/lowerxarch.cpp:4894]: > The consideration here, however, was that the logic further down will rewrite this from GetElement/WithElement to something like Sse41.Extract(vector, cns) or Sse41.Extract(Avx.ExtractVector128(vector, cns1), cns2) instead.
> 
> If it's all working, that's great and fine; just want to ensure that the nuance is being considered since the other nodes are really setup to expect something explicitly constrained to [0, 255].

Ah, I see. I _think_ that still works fine; the logic there removes the constant and reinserts a new (int32-typed) constant when it makes that change.

Actually I see that it sometimes changes back to `NI_Vector128_GetElement` with that int32-typed constant, so that will likely hit the new assert I added. Let me make sure that particular case ends up with a native sized index too.

**Review by tannergooding — APPROVED** [review]
