### PR TITLE
Remove built-in WinRT support from the runtime

### LINKED ISSUE #33330: Remove some WinRT code that was replaced by the new ComWrappers API.
The [ComWrappers API](https://github.com/dotnet/runtime/issues/1845) provides a different approach for WinRT support and therefore some code within the runtime can be removed.

See https://github.com/dotnet/runtime/pull/32091

/cc @jkoritzinsky

### LINKED ISSUE #34396: [Mono] Test failed on windows: System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignatureWinRT
`System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignatureWinRT` is disabled in Mono's CoreFX.issues_windows.rsp file. After enabling it still fails locally with the following output:
```
System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignatureWinRT(assemblyName: "Windows, Version=255.255.255.255, Culture=neutral,"..., type: "Windows.Foundation.Collections.StringMap", ignoreCase: False, bindingAttr: Instance | Public | NonPublic, binder: DefaultBinder { }, args: [], culture: , activationAttributes: null, returnedFullNameType: "Windows.Foundation.Collections.StringMap") [FAIL]
System.IO.FileLoadException : The assembly name is invalid.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\AssemblyName.Mono.cs(28,0): at System.Reflection.AssemblyName..ctor(String assemblyName)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(118,0): at System.Activator.CreateInstanceInternal(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(60,0): at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
    _\src\libraries\System.Runtime\tests\System\ActivatorTests.cs(784,0): at System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignatureWinRT(String assemblyName, String type, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, String returnedFullNameType)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
The test will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

### LINKED ISSUE #34749: [mono] Tests failed on windows: System.Runtime.InteropServices.WindowsRuntime.Tests
`System.Runtime.InteropServices.WindowsRuntime.Tests` tests fail on windows mostly with `System.PlatformNotSupportedException : Operation is not supported on this platform.`

The following tests classes/methods will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592:
- System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests
- System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTests
- System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeMarshalTests
- System.Runtime.InteropServices.WindowsRuntime.Tests.InterfaceImplementedInVersionAttributeTests.Ctor_DefaultInterface

The example of the output with the stack traces:
```
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.Ctor_NonDelegateType_ThrowsInvalidOperationException [FAIL]
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(System.PlatformNotSupportedException): Operation is not supported on this platform.
---- System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(22,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.<>c.<Ctor_NonDelegateType_ThrowsInvalidOperationException>b__1_0()
    ----- Inner Stack Trace -----
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(22,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.<>c.<Ctor_NonDelegateType_ThrowsInvalidOperationException>b__1_0()
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.InvocationList_SetDelegate_GetReturnsExpected [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(171,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.InvocationList_SetDelegate_GetReturnsExpected()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_Null_ReturnsZeroToken [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(68,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_Null_ReturnsZeroToken()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_SingleInvocationList_AddsSingleDelegateToInvocationList [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(29,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_SingleInvocationList_AddsSingleDelegateToInvocationList()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Assert.Throws() Failure
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NonDelegateType_ThrowsInvalidOperationException [FAIL]
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(System.PlatformNotSupportedException): Operation is not supported on this platform.
---- System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(154,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.<>c__DisplayClass12_0.<GetOrCreateEventRegistrationTokenTable_NonDelegateType_ThrowsInvalidOperationException>b__0()
    ----- Inner Stack Trace -----
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(154,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.<>c__DisplayClass12_0.<GetOrCreateEventRegistrationTokenTable_NonDelegateType_ThrowsInvalidOperationException>b__0()
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_NullDelegate_Nop [FAIL]
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(130,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_NullDelegate_Nop()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_Token_RemovesFromTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(80,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_Token_RemovesFromTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_MultipleTimes_RemovesSingleDelegateFromTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(115,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_MultipleTimes_RemovesSingleDelegateFromTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_Delegate_RemovesFromTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(97,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_Delegate_RemovesFromTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NullTable_ReturnsNewTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(138,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NullTable_ReturnsNewTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_MultipleTimes_AddsEachDelegateToInvocationList [FAIL]
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(54,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_MultipleTimes_AddsEachDelegateToInvocationList()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_MultipleInvocationList_AddsAllDelegateToInvocationLists [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(43,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_MultipleInvocationList_AddsAllDelegateToInvocationLists()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NonNullTable_ReturnsEventTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(145,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NonNullTable_ReturnsEventTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.InvocationList_SetNull_GetReturnsNull [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(160,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.InvocationList_SetNull_GetReturnsNull()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.Ctor_Default [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(15,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.Ctor_Default()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

### LINKED ISSUE #34768: [mono] Tests failed on windows: System.Runtime.WindowsRuntime.Tests
There are test failures in `System.Runtime.WindowsRuntime.Tests` on windows.

```
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [], offset: 0, length: 0, capacity: 0) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 2, length: 0, capacity: 0) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 2, length: 0, capacity: 1) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 0, length: 3, capacity: 3) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 1, length: 2, capacity: 2) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_NegativeLength_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_NegativeOffset_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_NegativeCapacity_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [], offset: 0, length: 1, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [], offset: 1, length: 0, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 1, length: 2, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 2147483647, length: 0, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 0, capacity: 3) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 0, capacity: 2147483647) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 2, capacity: 1) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_NullBuffer_ThrowsArgumentNullException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentNullException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_NegativeCapacity_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_NegativeLength_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Buffer_ReturnsExpected(source: [], offset: 0, length: 0, capacity: 0) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 0, length: 3, capacity: 3) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Buffer_ReturnsExpected(source: [1, 2, 3, 4, 5, ...], offset: 2, length: 1, capacity: 4) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 1, length: 2, capacity: 2) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [], offset: 0, length: 1, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [], offset: 1, length: 0, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 1, length: 2, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 2147483647, length: 0, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 0, capacity: 3) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 0, capacity: 2147483647) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 2, capacity: 1) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Length_SetGreaterThanCapacity_ThrowsArgumentException [FAIL]
    System.TypeLoadException : Could not load type of field 'System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests+<>c__DisplayClass8_0:buffer' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Capacity_ReturnsExpected(capacity: 0) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Capacity_ReturnsExpected(capacity: 1) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_NegativeOffset_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_NullData_ThrowsArgumentNullException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentNullException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
```
The following test classes will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592:
- System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests
- System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests

### LINKED ISSUE #37672: [Breaking change] Removal of built-in WinRT support in .NET 5.0
# [Breaking change] Removal of built-in WinRT support in .NET 5.0

With the work to provide sustainable and long term [support for WinRT consumption in .NET](https://github.com/dotnet/runtime/issues/35318), the built-in support has been removed. This is a high impact change to all existing libraries and application that rely on the built-in WinRT support.

The replacement for built-in WinRT support is the [C#/WinRT](https://aka.ms/cswinrt) tool chain.

For complete details see the official doc issue at https://github.com/dotnet/docs/issues/18875.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Now that [C#/WinRT](https://github.com/microsoft/CsWinRT) is public and is the new supported way forward for WinRT support in .NET, we can remove WinRT support from the runtime (or at least attempt to).

This is currently blocked on #36889

Fixes #33330
Fixes https://github.com/dotnet/runtime/issues/37672

### CODE REVIEW

**Comment by stephentoub** [comment]
This is deleting a bunch of APIs, such as the AsTask methods that support creating Tasks from IAsyncActions.  What is the replacement for that?

**Comment by jkoritzinsky** [comment]
The public APIs deleted here have all been ported to C#/WinRT.

The implementations here rely on the ability to load WinMDs since they reference Windows.winmd directly for the type definitions, so after the WinRT removal, they can't be loaded by the type loader.

File: src/coreclr/src/inc/cor.h [hunk 1]
```diff
@@ -1825,27 +1825,6 @@ DECLARE_INTERFACE_(IMetaDataInfo, IUnknown)
         DWORD *       pdwMappingType) PURE; // [out] Type of file mapping (code:CorFileMapping).
 };  // class IMetaDataInfo
 
-
-//-------------------------------------
-//--- IMetaDataWinMDImport
-//-------------------------------------
-// {969EA0C5-964E-411B-A807-B0F3C2DFCBD4}
-EXTERN_GUID(IID_IMetaDataWinMDImport, 0x969ea0c5, 0x964e, 0x411b, 0xa8, 0x7, 0xb0, 0xf3, 0xc2, 0xdf, 0xcb, 0xd4);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/inc/cor.h:1833]: Let's be careful of all these interface changes and updates. If all of them are internal then updates are fine, but we need to make sure that they can't be implemented by external people without a GUID change or else vtables will be in a bad state.

File: src/coreclr/src/debug/daccess/daccess.cpp [hunk 2]
```diff
@@ -6604,7 +6604,7 @@ bool ClrDataAccess::GetILImageInfoFromNgenPEFile(PEFile *peFile,
 
 #if defined(FEATURE_CORESYSTEM)
 /* static */
-// We extract "ni.dll or .ni.winmd" from the NGEM image name to obtain the IL image name.
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/debug/daccess/daccess.cpp:6607]: >NGEM [](start = 45, length = 4)

NGEN

File: src/coreclr/src/dlls/mscorrc/mscorrc.rc [hunk 3]
```diff
@@ -500,6 +475,7 @@ BEGIN
     IDS_EE_MISSING_METHOD                   "Method not found: '%1'."
 
     IDS_EE_NO_IDISPATCH                     "This object cannot be marshaled as an IDispatch."
+    IDS_EE_NO_IINSPECTABLE                  "Marshalling as IInspectable is not supported in the .NET runtime."
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/dlls/mscorrc/mscorrc.rc:478]: >IDS_EE_NO_IINSPECTABLE [](start = 4, length = 22)

Haven't gotten this far yet, but note we should write a test for this.

File: src/coreclr/src/hosts/corerun/corerun.cpp [hunk 4]
```diff
@@ -562,7 +558,6 @@ HRESULT InitializeHost(
         "APP_PATHS",
         "APP_NI_PATHS",
         "NATIVE_DLL_SEARCH_DIRECTORIES",
-        "APP_LOCAL_WINMETADATA",
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/hosts/corerun/corerun.cpp:565]: >APP_LOCAL_WINMETADATA [](start = 9, length = 21)

We might want to add a log or something that when this is found we provide a warning. Is that feasible?

File: src/coreclr/src/inc/dacvars.h [hunk 5]
```diff
@@ -222,7 +221,6 @@ DEFINE_DACVAR(ULONG, SIZE_T, dac__gFCallMethods, ::gFCallMethods)
 DEFINE_DACVAR(ULONG, PTR_SyncTableEntry, dac__g_pSyncTable, ::g_pSyncTable)
 #ifdef FEATURE_COMINTEROP
 DEFINE_DACVAR(ULONG, UNKNOWN_POINTER_TYPE, dac__g_pRCWCleanupList, ::g_pRCWCleanupList)
-DEFINE_DACVAR(ULONG, BOOL, RCWWalker__s_bIsGlobalPeggingOn, RCWWalker::s_bIsGlobalPeggingOn)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/inc/dacvars.h:225]: >DEFINE_DACVAR [](start = 0, length = 13)

This is actually still desired since we handle the global pegging logic in interoplib.

Comment (jkoritzinsky) [reply src/coreclr/src/inc/dacvars.h:225]: To my understanding, the pegging logic only applies to WinRT. In which case, the built in RCW/CCW system doesn't need to understand pegging any more. As a result, the DAC doesn't need to know about pegging since it only uses this variable to handle telling the debugger if a given built-in RCW/CCW is pegged.

If my assumption is incorrect, I'll add pegging back to the built-in RCW/CCW system and re-expose this variable to the DAC from interoplib.

Comment (AaronRobinsonMSFT) [reply src/coreclr/src/inc/dacvars.h:225]: No worries. I wasn't sure why the DAC needed it so I kept it. If that is why, then you are correct it can be removed. Thanks!

**Comment by AaronRobinsonMSFT** [comment]
>     if (m_pGuidToTypeHash != NULL)

How do we know this is WinRT only?

---
Refers to: src/coreclr/src/vm/ceeload.cpp:8625 in 848062a. [](commit_id = 848062a916c6b1ed56f13649ab4a5bce3a43d446, deletion_comment = True)

**Comment by AaronRobinsonMSFT** [comment]
>     // This maintains both COM ref in 64-bit

Let's update this comment to reference it is only 64-bit since we previously stored information in the upper 32 bits and there is no longer a need for it to be this wide.

---
Refers to: src/coreclr/src/vm/comcallablewrapper.h:1756 in 848062a. [](commit_id = 848062a916c6b1ed56f13649ab4a5bce3a43d446, deletion_comment = False)

**Comment by AaronRobinsonMSFT** [comment]
> inline bool IsIAgileObject(REFIID riid)

I am not entirely sure we should get rid of this yet. This was introduced in Win8, but is used in COM in general nowadays.

---
Refers to: src/coreclr/src/vm/comcallablewrapper.cpp:1741 in 848062a. [](commit_id = 848062a916c6b1ed56f13649ab4a5bce3a43d446, deletion_comment = True)

**Comment by AaronRobinsonMSFT** [comment]
>         if (wcscmp(pPropertyNames[i], W("APP_LOCAL_WINMETADATA")) == 0)

I see where this is being used now. No need to log anything. Thanks.

---
Refers to: src/coreclr/src/vm/corhost.cpp:684 in 848062a. [](commit_id = 848062a916c6b1ed56f13649ab4a5bce3a43d446, deletion_comment = True)

**Comment by AaronRobinsonMSFT** [comment]
>     static FCDECL3(IUnknown*,       GetCOMIPFromRCW_WinRT,              Object* pSrcUNSAFE, MethodDesc* pMD, void **ppTarget);

Where were these FCalls removed from on the managed side?

---
Refers to: src/coreclr/src/vm/stubhelpers.h:51 in 848062a. [](commit_id = 848062a916c6b1ed56f13649ab4a5bce3a43d446, deletion_comment = True)

**Comment by AaronRobinsonMSFT** [comment]
>     MARSHAL_FLAG_HIDDENLENPARAM     = 0x040,

I thought this was used in COM for array length passing. Was this only for WinRT?

---
Refers to: src/coreclr/src/vm/mlinfo.h:58 in 848062a. [](commit_id = 848062a916c6b1ed56f13649ab4a5bce3a43d446, deletion_comment = True)

**Comment by AaronRobinsonMSFT** [comment]
>     // unused                       = 0x10000

Can we remove these?

---
Refers to: src/coreclr/src/vm/comtoclrcall.h:39 in 848062a. [](commit_id = 848062a916c6b1ed56f13649ab4a5bce3a43d446, deletion_comment = False)

**Comment by jkoritzinsky** [comment]
> > ```
> > if (m_pGuidToTypeHash != NULL)
> > ```
> 
> How do we know this is WinRT only?
> 
> Refers to: src/coreclr/src/vm/ceeload.cpp:8625 in [848062a](https://github.com/dotnet/runtime/commit/848062a916c6b1ed56f13649ab4a5bce3a43d446). [](commit_id = [848062a](https://github.com/dotnet/runtime/commit/848062a916c6b1ed56f13649ab4a5bce3a43d446), deletion_comment = True)

This hash was only used for mapping a Guid to a generic WinRT type. The CLSID->Type hash map used for classic COM is a different hash map.


> > ```
> > static FCDECL3(IUnknown*,       GetCOMIPFromRCW_WinRT,              Object* pSrcUNSAFE, MethodDesc* pMD, void **ppTarget);
> > ```
> 
> Where were these FCalls removed from on the managed side?
> 
> Refers to: src/coreclr/src/vm/stubhelpers.h:51 in [848062a](https://github.com/dotnet/runtime/commit/848062a916c6b1ed56f13649ab4a5bce3a43d446). [](commit_id = [848062a](https://github.com/dotnet/runtime/commit/848062a916c6b1ed56f13649ab4a5bce3a43d446), deletion_comment = True)

These FCalls were exposed via StubHelpers.cs. They've been removed in this PR.



> > ```
> > MARSHAL_FLAG_HIDDENLENPARAM     = 0x040,
> > ```
> 
> I thought this was used in COM for array length passing. Was this only for WinRT?
> 
> Refers to: src/coreclr/src/vm/mlinfo.h:58 in [848062a](https://github.com/dotnet/runtime/commit/848062a916c6b1ed56f13649ab4a5bce3a43d446). [](commit_id = [848062a](https://github.com/dotnet/runtime/commit/848062a916c6b1ed56f13649ab4a5bce3a43d446), deletion_comment = True)

Yes, this was only used for WinRT array marshalling.

**Comment by jkoritzinsky** [comment]
> > ```
> > // unused                       = 0x10000
> > ```
> 
> Can we remove these?
> 
> Refers to: src/coreclr/src/vm/comtoclrcall.h:39 in [848062a](https://github.com/dotnet/runtime/commit/848062a916c6b1ed56f13649ab4a5bce3a43d446). [](commit_id = [848062a](https://github.com/dotnet/runtime/commit/848062a916c6b1ed56f13649ab4a5bce3a43d446), deletion_comment = False)

Probably? I don't think anything outside of the vm uses these, so I just followed the pattern in the code base of just changing them to be "unused".

File: src/coreclr/src/dlls/mscorrc/mscorrc.rc (hunk 3 above)
Comment (jkoritzinsky) [reply src/coreclr/src/dlls/mscorrc/mscorrc.rc:478]: I've added a few tests.

**Comment by jkoritzinsky** [comment]
> IsIAgileObject(REFIID riid)

This function is actually unused in master.

File: src/coreclr/src/vm/comtoclrcall.h [hunk 6]
```diff
@@ -36,7 +36,7 @@ enum ComCallFlags
     enum_IsWinRTCall                = 0x2000,   // The method is declared on a WinRT interface/delegate
     enum_IsWinRTCtor                = 0x4000,   // The method is a WinRT constructor
     enum_IsWinRTStatic              = 0x8000,   // The method is a WinRT static
```
Comment (janvorli) [inline src/coreclr/src/vm/comtoclrcall.h:38]: Are the remaining WinRT related enums still needed?

File: src/coreclr/src/vm/method.hpp [hunk 7]
```diff
@@ -2746,7 +2745,7 @@ class DynamicMethodDesc : public StoredSigMethodDesc
     bool HasMDContextArg()
     {
         LIMITED_METHOD_CONTRACT;
-        return ((IsCLRToCOMStub() && !IsDelegateCOMStub()) || IsPInvokeStub());
+        return IsCLRToCOMStub()|| IsPInvokeStub();
```
Comment (janvorli) [inline src/coreclr/src/vm/method.hpp:2748]: A nit - missing space before ||

**Review by janvorli — COMMENTED** [review]
The EH changes look good.

File: src/coreclr/src/vm/comtoclrcall.h (hunk 6 above)
Comment (jkoritzinsky) [reply src/coreclr/src/vm/comtoclrcall.h:38]: Nope. I must have missed these on my most recent passes. I'll remove them/mark them as unused.

**Comment by AaronRobinsonMSFT** [comment]
> IsIAgileObject

Look for `IID_IAgileObject`. It is used in `IsComponentFreeThreaded()`. Unsure if we ever go down the same path with a CCW though. However, I would imagine COM would query for that.

**Comment by jkoritzinsky** [comment]
> > > IsIAgileObject
> 
> > This function is actually unused in master.
> 
> Look for `IID_IAgileObject`. It is used in `IsComponentFreeThreaded()`. Unsure if we ever go down the same path with a CCW though. However, I would imagine COM would query for that.
.
If you'd prefer, I can add back the ability to QI a CCW for `IAgileObject`. That way we preserve considering the built-in COM objects as free-threaded when possible.

**Comment by AaronRobinsonMSFT** [comment]
I think we should continue to support `IAgileObject` since COM will call for it in non-WinRT scenarios.

**Comment by jkoritzinsky** [comment]
Installer and live-build failures are blocked on the uptake of #36889

**Comment by jkoritzinsky** [comment]
This PR is green with both our usual PR test runs and also Pri1 CoreCLR test runs. It's ready for review.

**Comment by AaronRobinsonMSFT** [comment]
@ericstj Is there any additional mop up you can think of with this work?

**Comment by AaronRobinsonMSFT** [comment]
>         private const string IID_IINSPECTABLE = "AF86E2E0-B12D-4c6a-9C5A-D7AA65101E90";

You can remove this now.

---
Refers to: src/coreclr/tests/src/Interop/COM/ComWrappers/GlobalInstance/GlobalInstance.cs:53 in 45ad790. [](commit_id = 45ad79009070f704becff863f057d62190ff6eef, deletion_comment = False)

**Comment by AaronRobinsonMSFT** [comment]
>                 int i,

Should we also add the obsolete attribute to `UnmanagedType.IInspectable`?

---
Refers to: src/coreclr/tests/src/Interop/COM/ComWrappers/GlobalInstance/GlobalInstance.cs:46 in 45ad790. [](commit_id = 45ad79009070f704becff863f057d62190ff6eef, deletion_comment = True)

**Comment by jkoritzinsky** [comment]
> > ```
> >             int i,
> > ```
> 
> Should we also add the obsolete attribute to `UnmanagedType.IInspectable`?
> 
> Refers to: src/coreclr/tests/src/Interop/COM/ComWrappers/GlobalInstance/GlobalInstance.cs:46 in [45ad790](https://github.com/dotnet/runtime/commit/45ad79009070f704becff863f057d62190ff6eef). [](commit_id = [45ad790](https://github.com/dotnet/runtime/commit/45ad79009070f704becff863f057d62190ff6eef), deletion_comment = True)

That's probably a good idea. Do we want to use the old style obsolete or is this a good place to use the new obsoletion mechanism where we can specify a specific code/link for information about the obsoletion?

**Comment by AaronRobinsonMSFT** [comment]
>         GCPressureSize_WinRT_High   = 7,

These can be removed as well.

---
Refers to: src/coreclr/src/vm/runtimecallablewrapper.h:409 in 45ad790. [](commit_id = 45ad79009070f704becff863f057d62190ff6eef, deletion_comment = True)

**Comment by AaronRobinsonMSFT** [comment]
>     bool fAllowOutOfContextCache = false;

I would remove this entirely.

---
Refers to: src/coreclr/src/vm/runtimecallablewrapper.cpp:2668 in 45ad790. [](commit_id = 45ad79009070f704becff863f057d62190ff6eef, deletion_comment = False)

**Comment by AaronRobinsonMSFT** [comment]
> class WeakReferenceImpl : public IUnknownCommon<IWeakReference, IID_IWeakReference>

Since we are removing this can we update weakerferencenative.cpp to remove some of the branches?

---
Refers to: src/coreclr/src/vm/comcallablewrapper.h:1328 in 45ad790. [](commit_id = 45ad79009070f704becff863f057d62190ff6eef, deletion_comment = True)

**Comment by AaronRobinsonMSFT** [comment]
>Do we want to use the old style obsolete or is this a good place to use the new obsoletion mechanism where we can specify a specific code/link for information about the obsoletion?

We should use the latest methodology. We also have that aka.ms we can use in the message.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky This is great work. I am signed off.

I would like to see @jkotas, @ericstj, and/or @stephentoub to provide some thoughts on their respective ownership areas. This change impacts the entire .NET stack in vNext.

We should also reach out to the existing VS designers for WinRT and ensure they haven't started using .NET 5 in an isolated scenario.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Review by jkotas — APPROVED** [review]
LGTM

**Comment by ericstj** [comment]
What will happen when someone builds a 5.0 app using packages from 3.1?
What happens when you build a 3.1 app and have it roll forward to 5.0?
You will want to test both of these scenarios to see if the behavior is acceptable or if you want to do something to improve it.

**Comment by jkoritzinsky** [comment]
Here's the possible scenarios:

- If someone runs code that loads `System.Runtime.InteropServices.WindowsRuntime.dll`, they'll get a FileNotFound exception when loading the assembly. This can happen from using packages or from rollforward. This assembly is rarely used and it would be unlikely that it would be loaded before a WinMD in a typical application. 
- If someone runs code that attempts to load a WinMD at runtime, they will get a `PlatformNotSupportedException`. https://github.com/dotnet/sdk/pull/11805 blocks directly or transitively referencing a WinMD at build time, so the only time you can build a project that targets .NET 5 and uses WinMDs is if a package uses ref assemblies and the ref assemblies don't reference WinMDs but the runtime assemblies do.

I believe both of these behaviors are acceptable.

**Comment by jkoritzinsky** [comment]
Those two assemblies ship out of band in packages anyway, so they will continue to work until someone touches a WinRT type. The entire surface area of System.Runtime.WindowsRuntime uses WinRT types so it will fail with the PNSE failure. The System.Runtime.WindowsRuntime.UI.Xaml assembly has some non WinRT types, so those types will continue to work as expected, and the others will fail with PNSE.

**Comment by jkoritzinsky** [comment]
I believe all feedback here has been addressed. There's some follow-up cleanup around the edges that Aaron has pointed out that we can do in a later PR.

To make sure that we get this in before the Preview 6 cut, I'm going to merge this in now.

**Comment by ViktorHofer** [comment]
Any reason why we haven't removed https://github.com/dotnet/runtime/tree/master/src/libraries/mscorlib.WinRT-Facade which was only referenced by the WindowsRuntime projects?

**Comment by ericstj** [comment]
Nope, if no-one is referencing it, delete it.  It's only used for consuming winmds in src build before we've built the mscorlib shim.
