### PR TITLE
Switch to PREEMPT mode when calling CoTaskMem* APIs

### LINKED ISSUE #70973: cli xUnit tests fail since https://github.com/dotnet/runtime build 20220616.9
### Description

The [update from the runtime](https://github.com/dotnet/winforms/pull/7322) fails at the test leg, see https://dev.azure.com/dnceng/public/_build/results?buildId=1833158&view=results.

It looks like the test runner (or the process?) reports a non-zero exit code despite no failed tests, e.g.:
image
image

### Reproduction Steps

1. `git clone https://github.com/dotnet/winforms`
2. switch to `darc-main-240f38e5-32c6-4ca8-8d1a-35df12541c87` branch
3. `build.cmd -test`

### Expected behavior

All tests pass. The current main is green: https://dev.azure.com/dnceng/public/_build/results?buildId=1830484&view=results

### Actual behavior

The test runner reports incorrect value and fails.

### Regression?

By the looks of it.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #70973

This enables WinForms to pass.

Still need to consider other COM entry points (for example, `ComPreStubWorker`).

### CODE REVIEW

File: src/coreclr/vm/comtoclrcall.cpp [hunk 1]
```diff
@@ -505,6 +505,13 @@ extern "C" UINT64 __stdcall COMToCLRWorker(Thread *pThread, ComMethodFrame* pFra
         }
     }
 
+    if (pThread->PreemptiveGCDisabled())
+    {
+        EEPOLICY_HANDLE_FATAL_ERROR_WITH_MESSAGE(
+            COR_E_FAILFAST,
+            W("Thread invoking a COM method from non-preemptive GC state. The transition to preemptive mode was missed."));
```
Comment (jkotas) [inline src/coreclr/vm/comtoclrcall.cpp:512]:
```suggestion
            W("Invalid Program: attempted to call a COM method from managed code."));
```
I would use the same wording as `ReversePInvokeBadTransition`

**Comment by jkotas** [comment]
> Still need to consider other COM entry points (for example, ComPreStubWorker).

I think ComPreStubWorker is the only one that needs it. There may be other entrypoints for various corner cases, but I do not think we need to boil the ocean to add this check everywhere.

File: src/coreclr/vm/comtoclrcall.cpp [hunk 2]
```diff
@@ -489,7 +489,7 @@ extern "C" UINT64 __stdcall COMToCLRWorker(Thread *pThread, ComMethodFrame* pFra
     // idea is that we needn't really do this work either in static assembly code nor in dynamically
     // generated code since the benefit/cost ratio is low.  There are some minor differences in the below
     // code, compared to x86.  First, the reentrancy and loader lock checks are optionally compiled into the
```
Comment (jkotas) [inline src/coreclr/vm/comtoclrcall.cpp:491]:
```suggestion
    // code, compared to x86.
```
These checks do not exist in CoreCLR

File: src/coreclr/vm/comtoclrcall.cpp [hunk 3]
```diff
@@ -489,7 +489,7 @@ extern "C" UINT64 __stdcall COMToCLRWorker(Thread *pThread, ComMethodFrame* pFra
...
-    // stub on x86, depending on whether or not the corresponding MDAs are active at stub-generation time.
+    // stub on x86 at stub-generation time.
```
Comment (jkotas) [inline src/coreclr/vm/comtoclrcall.cpp:492]:
```suggestion
```

File: src/coreclr/vm/comtoclrcall.cpp [hunk 4]
```diff
@@ -505,8 +505,15 @@ extern "C" UINT64 __stdcall COMToCLRWorker(Thread *pThread, ComMethodFrame* pFra
...
+    if (pThread->PreemptiveGCDisabled())
+    {
+        EEPOLICY_HANDLE_FATAL_ERROR_WITH_MESSAGE(
+            COR_E_EXECUTIONENGINE,
+            W("Invalid Program: attempted to call a COM method from managed code."));
+    }
+
     // Attempt to switch GC modes.  Note that this is performed manually just like in the x86 stub because
-    // we have additional checks for shutdown races, MDAs, and thread abort that are performed only when
+    // we have additional checks for shutdown races and thread abort that are performed only when
```
Comment (jkotas) [inline src/coreclr/vm/comtoclrcall.cpp:516]:
```suggestion
    // we have additional checks for thread abort that are performed only when
```
Checks for shutdown that this is talking about do not exist in CoreCLR.

**Review by jkotas — APPROVED** [review]
Thank you!
