### PR TITLE
Disable IEnumerator test on Mono

### LINKED ISSUE #95792: Interop tests crash on Mono
```
"C:\h\w\B52309CB\p\watchdog.exe" 29 "C:\h\w\B52309CB\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Interop.dll 
08:44:38.933 Running test: global::PInvokeTests.IEnumeratorTests.TestNativeToManaged()
App Exit Code: -1073741819
Expected: 100
Actual: -1073741819
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=492896
Build error leg or test failing: Interop.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/95710

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Running test: global::PInvokeTests.IEnumeratorTests.TestNativeToManaged()",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=492896
**Error message validated:** `Running test: global::PInvokeTests.IEnumeratorTests.TestNativeToManaged()`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 12/8/2023 4:09:25 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[493836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493836)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493836&view=ms.vss-test-web.build-test-results-tab&runId=11453226&resultId=113329)|dotnet/runtime#95798|
|[493152](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493152)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493152&view=ms.vss-test-web.build-test-results-tab&runId=11451058&resultId=113329)|dotnet/runtime#95554|
|[493715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493715)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493715&view=ms.vss-test-web.build-test-results-tab&runId=11450362&resultId=113329)||
|[493610](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493610)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493610&view=ms.vss-test-web.build-test-results-tab&runId=11448622&resultId=113329)|dotnet/runtime#95801|
|[493393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493393)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493393&view=ms.vss-test-web.build-test-results-tab&runId=11442666&resultId=113329)|dotnet/runtime#94764|
|[492796](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492796)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492796&view=ms.vss-test-web.build-test-results-tab&runId=11439680&resultId=113329)|dotnet/runtime#94446|
|[493316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493316)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493316&view=ms.vss-test-web.build-test-results-tab&runId=11439170&resultId=113329)|dotnet/runtime#95738|
|[493264](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493264)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493264&view=ms.vss-test-web.build-test-results-tab&runId=11438086&resultId=113329)|dotnet/runtime#95787|
|[493249](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493249)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493249&view=ms.vss-test-web.build-test-results-tab&runId=11437894&resultId=113329)|dotnet/runtime#95786|
|[493212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493212)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493212&view=ms.vss-test-web.build-test-results-tab&runId=11437436&resultId=113329)|dotnet/runtime#95742|
|[493155](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493155)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493155&view=ms.vss-test-web.build-test-results-tab&runId=11435656&resultId=113329)|dotnet/runtime#95785|
|[492904](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492904)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492904&view=ms.vss-test-web.build-test-results-tab&runId=11425864&resultId=113329)||
|[492896](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492896)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492896&view=ms.vss-test-web.build-test-results-tab&runId=11425268&resultId=113329)|dotnet/runtime#95710|
|[492874](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492874)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492874&view=ms.vss-test-web.build-test-results-tab&runId=11424662&resultId=113329)|dotnet/runtime#95779|
|[492819](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492819)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492819&view=ms.vss-test-web.build-test-results-tab&runId=11422176&resultId=113329)|dotnet/runtime#93043|
|[492680](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492680)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492680&view=ms.vss-test-web.build-test-results-tab&runId=11418630&resultId=113329)|dotnet/runtime#95775|
|[492590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492590)|dotnet/runtime|[Interop.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=492590&view=ms.vss-test-web.build-test-results-tab&runId=11416030&resultId=113329)|dotnet/runtime#95670|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|17|17|17|

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes https://github.com/dotnet/runtime/issues/95792

With the recent interop test refactoring, the disabling of this test was lost.

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

File: src/tests/Interop/PInvoke/IEnumerator/IEnumeratorTest.cs [hunk 1]
```diff
@@ -40,6 +40,7 @@ static class IEnumeratorNative
     }
 
     [ConditionalClass(typeof(PlatformDetection), nameof(PlatformDetection.IsBuiltInComEnabled))]
+    [SkipOnMono("PInvoke IEnumerator/IEnumarable marshalling not supported on Mono")]
```
Comment (jkotas) [inline src/tests/Interop/PInvoke/IEnumerator/IEnumeratorTest.cs:43]:
```suggestion
    [SkipOnMono("PInvoke IEnumerator/IEnumerable marshalling not supported on Mono")]
```

**Review by jkotas — APPROVED** [review]
