### PR TITLE
[wasm][debugger] Fix debugger behavior when the type has ToString method overridden

### LINKED ISSUE #76748: An overwritten ToString method does not show the content of an item in Blazor WASM (while DebuggerDisplay works now)
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DebuggerDisplay-and-ToString-do-not-wo/10163727)._

---
An overwritten ToString method does not show the content of an item in Blazor WASM (while DebuggerDisplay works now)

Visual Studio Professional 17.3.5

---
#### Feedback Bot on 10/4/2022, 02:56 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by thaystg**
The description of an object that has ToString implemented should bethe result of the ToString and not the type name.

Fixes #76748 

Using this PR:
image

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs [hunk 1]
```diff
@@ -293,6 +293,21 @@ private async Task<JObject> ReadAsObjectValue(MonoBinaryReader retDebuggerCmdRea
                 return Create(value: className, type: "symbol", description: className);
             }
         }
+        var typeInfo = await _sdbAgent.GetTypeInfo(type_id[0], token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs:296]: If a type has `ToString` overridden, and has a Debugger* attribute, then which one would be used?

Also, this won't work for ValueTypes, right?

File: src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs [hunk 2]
```diff
@@ -1371,4 +1371,17 @@ public static void CheckArguments(ReadOnlySpan<object> parameters)
...
     }
+}
+
+public class ToStringOverwritten
+{
+    public override string ToString()
+    {
+        return "hello";
+    }
+    public static void Run()
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:1382]: Can we also add a tests for:

```csharp
class A { public override string ToString() { ... } }
class B: A { .. }

var b = new B();
```
and
```csharp
class A { .. }
class B: A { public override string ToString() { .. } }

A a = new B();
```

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 3]
```diff
@@ -110,17 +111,39 @@ JObject GetFieldWithMetadata(FieldTypeClass field, JObject fieldValue, bool isSt
...
         }
+        public async Task<string> ToString(MonoSDBHelper sdbAgent, CancellationToken token)
+        {
+            var typeInfo = await sdbAgent.GetTypeInfo(TypeId, token);
+            if (typeInfo == null)
+                return null;
+            if (typeInfo.Name == "object")
+                return null;
+            Microsoft.WebAssembly.Diagnostics.MethodInfo methodInfo = typeInfo.Info.Methods.FirstOrDefault(m => m.Name == "ToString");
+            if (!IsEnum && methodInfo == null)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:122]: Should this be `||`?

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:122]: Can this method exit early in case of `IsEnum==true`?

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 4]
```diff
@@ -110,17 +111,39 @@ JObject GetFieldWithMetadata(FieldTypeClass field, JObject fieldValue, bool isSt
...
+                return null;
+            int[] methodIds = await sdbAgent.GetMethodIdsByName(TypeId, "ToString", token);
+            if (methodIds == null)
+                return null;
+            try {
+                var retMethod = await sdbAgent.InvokeMethod(Buffer, methodIds[0], token, "methodRet");
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:128]: There could be other `ToString` methods like too `public string ToString(int x) => $"{x+2}";`, so we need to find the one that has no parameters.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 5]
```diff
@@ -110,17 +111,39 @@ JObject GetFieldWithMetadata(FieldTypeClass field, JObject fieldValue, bool isSt
                 return fieldValue;
             }
         }
+        public async Task<string> ToString(MonoSDBHelper sdbAgent, CancellationToken token)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:114]: nit: rename to `InvokeToStringAsync`, or just `ToStringAsync`.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 6]
```diff
@@ -110,17 +111,39 @@ JObject GetFieldWithMetadata(FieldTypeClass field, JObject fieldValue, bool isSt
...
         public async Task<JObject> ToJObject(MonoSDBHelper sdbAgent, bool forDebuggerDisplayAttribute, CancellationToken token)
         {
             string description = className;
             if (ShouldAutoInvokeToString(className) || IsEnum)
             {
-                int[] methodIds = await sdbAgent.GetMethodIdsByName(TypeId, "ToString", token);
-                if (methodIds == null)
+                var toString = await ToString(sdbAgent, token);
+                if (toString == null)
                     throw new InternalErrorException($"Cannot find method 'ToString' on typeId = {TypeId}");
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:145]: Should we log this, and fallback to some default value?

Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:145]: Also, the error isn't correct because `toString` could be null because we couldn't find it, or it wasn't applicable, or invoking the method failed with an exception.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs (hunk 5 above)
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:114]:
```suggestion

        public async Task<string> ToString(MonoSDBHelper sdbAgent, CancellationToken token)
```

File: src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs [hunk 7]
```diff
@@ -265,22 +265,51 @@ async Task<string> GetNullObjectClassName()
...
     }
-
+    private async Task<string> ToString(List<int> typeIds, int objectId, CancellationToken token)
+    {
+        string description = "";
+        try {
+            foreach (var typeId in typeIds)
+            {
+                var typeInfo = await _sdbAgent.GetTypeInfo(typeId, token);
+                if (typeInfo != null && typeInfo.Name != "object")
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs:275]: nit:
```suggestion
                if (typeInfo == null || typeInfo.Name == "object")
                    continue;
```

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs:275]: When could `typeInfo` be `null`? If it is null for a valid type, and that has a `ToString` override, then we will be skipping that, and using a parent's `ToString`.

And that would be a useful test to add - derived, and parent class both having `ToString` overridden, just to confirm that we are picking the correct one.

File: src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs [hunk 8]
```diff
@@ -265,22 +265,51 @@ async Task<string> GetNullObjectClassName()
             return className;
         }
     }
-
+    private async Task<string> ToString(List<int> typeIds, int objectId, CancellationToken token)
+    {
+        string description = "";
+        try {
+            foreach (var typeId in typeIds)
+            {
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs:273]: Can we extract the body of the loop to `MonoSDBHelper`, and use that here, and in `ValueTypeClass`?

File: src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs [hunk 9]
```diff
@@ -1371,4 +1371,45 @@ public static void CheckArguments(ReadOnlySpan<object> parameters)
...
+    class ToStringOverridenC {}
+    class ToStringOverridenD: ToStringOverridenC
+    {
+        public override string ToString()
+        {
+            return "helloToStringOverridenD";
+        }
+    }
+
+    struct ToStringOverridenE
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:1395]:
```suggestion
    struct ToStringOverridenE
```

File: src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs (hunk 2 above)
Comment (radical) [reply src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:1407]: Along with `A a = new B();`, `object o = new B();` would be useful too.

File: src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs [hunk 10]
```diff
@@ -265,22 +265,51 @@ async Task<string> GetNullObjectClassName()
...
+            _logger.LogDebug($"Error while evaluating ToString method: {e}");
+        }
+        return description;
+    }
     private async Task<JObject> ReadAsObjectValue(MonoBinaryReader retDebuggerCmdReader, int typeIdFromAttribute, bool forDebuggerDisplayAttribute, CancellationToken token)
     {
         var objectId = retDebuggerCmdReader.ReadInt32();
-        var type_id = await _sdbAgent.GetTypeIdsForObject(objectId, false, token);
-        string className = await _sdbAgent.GetTypeName(type_id[0], token);
+        var typeIds = await _sdbAgent.GetTypeIdsForObject(objectId, true, token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs:301]: use parameter name for the bool. And 👍 on the local rename!

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs (hunk 3 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:122]: No should be `&&`, if it's a enum we want to call ToString even if we cannot find the method.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs (hunk 6 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:146]: changed.

File: src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs (hunk 2 above)
Comment (thaystg) [reply src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:1407]: done

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs (hunk 6 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:146]: I just kept the old behavior that was throwing the exception, but I think we can, if you think it's better

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs (hunk 4 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:129]: Done

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs (hunk 5 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:115]: Done

File: src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs (hunk 10 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs:302]: done.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs (hunk 3 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:123]: We don't get the method in case of an enum? Is that the case for other valuetypes? `record struct`?

Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:123]: Only for enum, I added tests for record also.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 11]
```diff
@@ -111,16 +112,46 @@ JObject GetFieldWithMetadata(FieldTypeClass field, JObject fieldValue, bool isSt
...
+            {
+                sdbAgent.logger.LogDebug($"Error while evaluating ToString method: {e}");
+            }
+            return null;
+        }
+
         public async Task<JObject> ToJObject(MonoSDBHelper sdbAgent, bool forDebuggerDisplayAttribute, CancellationToken token)
         {
             string description = className;
             if (ShouldAutoInvokeToString(className) || IsEnum)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:148]: If a type has a DebuggerDisplayAttribute, and has ToString overridden, then what takes precedence?

Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:148]: If it's not a ShouldAutoInvode or a Enum, then DebuggerDisplayAttribute is more important.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs (hunk 3 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:123]: Are no methods returned for enums at all? Is that a debugger-agent thing?

Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs]: No methods returned for enums at all, not sure if it's a debugger-agent thing or if they are really not implemented in the enum, they are somewhere like a "base class".

File: src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs (hunk 8 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/JObjectValueCreator.cs]: done

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 12]
```diff
@@ -116,11 +117,11 @@ public async Task<JObject> ToJObject(MonoSDBHelper sdbAgent, bool forDebuggerDis
...
             {
-                int[] methodIds = await sdbAgent.GetMethodIdsByName(TypeId, "ToString", token);
-                if (methodIds == null)
-                    throw new InternalErrorException($"Cannot find method 'ToString' on typeId = {TypeId}");
-                var retMethod = await sdbAgent.InvokeMethod(Buffer, methodIds[0], token, "methodRet");
-                description = retMethod["value"]?["value"].Value<string>();
+                var toString = await sdbAgent.InvokeToStringAsync(new List<int>(){TypeId}, true, IsEnum, Id.Value, IsEnum ? BindingFlags.Default : BindingFlags.DeclaredOnly, token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:120]:
```suggestion
                var toString = await sdbAgent.InvokeToStringAsync(new int[]{ TypeId }, true, IsEnum, Id.Value, IsEnum ? BindingFlags.Default : BindingFlags.DeclaredOnly, token);
```

.. and named arguments, because of the two bools.

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 13]
```diff
@@ -129,6 +130,12 @@ public async Task<JObject> ToJObject(MonoSDBHelper sdbAgent, bool forDebuggerDis
                 string displayString = await sdbAgent.GetValueFromDebuggerDisplayAttribute(Id, TypeId, token);
                 if (displayString != null)
                     description = displayString;
+                else
+                {
+                    var toString = await sdbAgent.InvokeToStringAsync(new List<int>(){TypeId}, true, IsEnum, Id.Value, IsEnum ? BindingFlags.Default : BindingFlags.DeclaredOnly, token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:135]:
```suggestion
                    var toString = await sdbAgent.InvokeToStringAsync(new int[]{ TypeId }, true, IsEnum, Id.Value, IsEnum ? BindingFlags.Default : BindingFlags.DeclaredOnly, token);
```

.. and named arguments.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 14]
```diff
@@ -1839,6 +1839,43 @@ public Task<JObject> InvokeMethod(DotnetObjectId dotnetObjectId, CancellationTok
...
+        {
+            try
+            {
+                foreach (var typeId in typeIds)
+                {
+                    var typeInfo = await GetTypeInfo(typeId, token);
+                    if (typeInfo == null)
+                        continue;
+                    if (typeInfo.Name == "object")
+                        continue;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1852]: nit:
```suggestion
                    if (typeInfo == null || typeInfo.Name == "object")
                        continue;
```

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs [hunk 15]
```diff
@@ -129,6 +130,12 @@ public async Task<JObject> ToJObject(MonoSDBHelper sdbAgent, bool forDebuggerDis
                 string displayString = await sdbAgent.GetValueFromDebuggerDisplayAttribute(Id, TypeId, token);
                 if (displayString != null)
                     description = displayString;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueTypeClass.cs:132]:
```suggestion
                if (displayString != null)
                {
                    description = displayString;
                }
```

**Review by radical — APPROVED** [review]
Other than the minor comments, LGTM 👍

**Review by ilonatommy — APPROVED** [review]
lgtm, good job👍
