### PR TITLE
Address flakey behavior testing COM lifetime cleanup.

### LINKED ISSUE #40965: Test failure: Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
failed in job: [runtime-coreclr gcstress-extra 20200816.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=773405&view=ms.vss-test-web.build-test-results-tab&runId=24164304&resultId=104610&paneView=debug)

Error message
~~~
Return code:      1
Raw output file:      D:\h\w\9DCA08A2\w\A5670925\e\Interop\COM\Reports\Interop.COM\NETClients\Primitives\NETClientPrimitives\NETClientPrimitives.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\9DCA08A2\p\corerun.exe" NETClientPrimitives.dll 
Numeric RNG seed: 37
Byte test invariant: 101 + 70 = 171
Int16 test invariant: 22885 + -29882 = -6997
UInt16 test invariant: 22885 + 35654 = 58539
Int32 test invariant: 120215909 + 1447004998 = 1567220907
UInt32 test invariant: 120215909 + 1447004998 = 1567220907
Int64 test invariant: 120215909 + 1447004998 = 1567220907
UInt64 test invariant: 120215909 + 1447004998 = 1567220907
Single test invariant: 1202159.1 + 14470051 = 15672210
Double test invariant: 1202159.09 + 14470049.98 = 15672209.07
Int32 11 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 = 66
Int32 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = 78
Byte[] marshalling
Int16[] marshalling
UInt16[] marshalling
Int32[] marshalling
UInt32[] marshalling
Int64[] marshalling
UInt64[] marshalling
Single[] marshalling
Double[] marshalling
Marshal strings as LPStr
Marshal strings as LPWStr
Marshal strings as BStr
Marshal LCID
Verify expected exception from HRESULT
Verify preserved function signature
Testing COM object lifetime control methods.
Numeric RNG seed: 37
Byte test invariant: 101 + 70 = 171
Int16 test invariant: 22885 + -29882 = -6997
UInt16 test invariant: 22885 + 35654 = 58539
Int32 test invariant: 120215909 + 1447004998 = 1567220907
UInt32 test invariant: 120215909 + 1447004998 = 1567220907
Int64 test invariant: 120215909 + 1447004998 = 1567220907
UInt64 test invariant: 120215909 + 1447004998 = 1567220907
Single test invariant: 1202159.1 + 14470051 = 15672210
Double test invariant: 1202159.09 + 14470049.98 = 15672209.07
Int32 11 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 = 66
Int32 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = 78
Byte[] marshalling
Int16[] marshalling
UInt16[] marshalling
Int32[] marshalling
UInt32[] marshalling
Int64[] marshalling
UInt64[] marshalling
Single[] marshalling
Double[] marshalling
Marshal strings as LPStr
Marshal strings as LPWStr
Marshal strings as BStr
Marshal LCID
Verify expected exception from HRESULT
Verify preserved function signature
Test Failure: TestLibrary.AssertTestException: Assert.IsFalse: 
   at TestLibrary.Assert.HandleFail(String assertionName, String message) in /Users/runner/work/1/s/src/tests/Common/CoreCLRTestLibrary/Assertion.cs:line 734
   at NetClient.Program.Main(String[] doNotUse) in /Users/runner/work/1/s/src/tests/Interop/COM/NETClients/Primitives/Program.cs:line 28
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\9DCA08A2\p
> D:\h\w\9DCA08A2\w\A5670925\e\Interop\COM\NETClients\Primitives\NETClientPrimitives\NETClientPrimitives.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_COM._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 1789
~~~

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #40965 

/cc @elinor-fung @jkoritzinsky

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
Failure for jitstress is due to https://github.com/dotnet/runtime/issues/49184.

File: src/tests/Interop/COM/NETClients/Primitives/Program.cs [hunk 1]
```diff
@@ -20,22 +20,52 @@ static int Main(string[] doNotUse)
...
                 return 101;
             }
 
             return 100;
         }
 
+        private static void ForceGC()
+        {
+            GC.Collect();
+            GC.Collect();
```
Comment (jkotas) [inline src/tests/Interop/COM/NETClients/Primitives/Program.cs:62]: What are the redundant `GC.Collect` calls meant to collect?

If the redundant `GC.Collect` calls are meant to collect stuff released by the finalizers, it may be better to do it like this:
```
for (int i = 0; i < 3; i++)
{
    GC.Collect();
    GC.WaitForPendingFinalizers();
}
```

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/COM/NETClients/Primitives/Program.cs:62]: This is how I was instructed to called `GC.Collect()` long ago. Is the correct way what you have written?

Comment (jkotas) [reply src/tests/Interop/COM/NETClients/Primitives/Program.cs:62]: It depends on what you are trying to achieve.

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/COM/NETClients/Primitives/Program.cs:62]: Sure. The multiple calls are to ensure the GC has considered as much as possible. I think your proposal is clearer as to my intent though.

File: src/tests/Interop/COM/NETClients/Primitives/Program.cs [hunk 2]
```diff
@@ -20,22 +20,51 @@ static int Main(string[] doNotUse)
...
+                Console.WriteLine($"Test object interop failure: {e}");
+                return 101;
+            }
+
+            try
+            {
+                Console.WriteLine(
+@"
+=========================
+Testing COM object lifetime control methods.
```
Comment (elinor-fung) [inline src/tests/Interop/COM/NETClients/Primitives/Program.cs:40]: Testing lifetime control seems weirdly tacked on to NETClientPrimitives? Are we just trying to avoid running the lifetime control tests if the first pass of just the object interop tests fails?

**Review by elinor-fung — APPROVED** [review]

File: src/tests/Interop/COM/NETClients/Primitives/Program.cs (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/tests/Interop/COM/NETClients/Primitives/Program.cs:40]: I agree. Ideally we would move these to a newer more narrower test. For right now I just wanted to make sure it was no longer failing. Would you prefer to I simply rewrite the test now?

Comment (elinor-fung) [reply src/tests/Interop/COM/NETClients/Primitives/Program.cs:40]: I'd prefer to just split it now.
