### PR TITLE
Fix DacHeapWalker for USE_REGIONS

### LINKED ISSUE #56653: ICorDebugProcess5::EnumerateHeapRegions returned a COR_SEGMENT that grow backwards under USE_REGIONS
I attempted to enumerate the POH regions using the API, but the API gave me a `COR_SEGMENT` structure with `start >= end`, which does not make sense.

### PR DESCRIPTION
**Pull request by cshung**
Fixes #56653

This change fixes two issues: 

The first issue is that we `generation_allocation_start` is no longer defined in the `generation` class.

```c++
class generation
{
public:
    // Don't move these first two fields without adjusting the references
    // from the __asm in jitinterface.cpp.
    alloc_context   allocation_context;
    PTR_heap_segment start_segment;
#ifndef USE_REGIONS
    uint8_t*        allocation_start;
#endif //!USE_REGIONS
...
```
The fix here is completely analogus to https://github.com/dotnet/runtime/pull/56056. It is a lot of code, but it is all boilerplate.

The second issue is that unlike in the segment case, gen1 and gen0 have their own linked list of regions. 

The removal of the `allocation_start` pointer means we no longer have a pointer for the beginning of a generation, and it is easily remedied because the start of the generation is the beginning of the first region in that linked list.

This fix is sufficient to get heap enumeration working, but it is probably not addressing all uses of the `generation_allocation_start` field (and potentially also fields whose values are derived from it). That would be out of the scope of the current PR, the remaining work are tracked as issues and they can wait because they are shipped out of band.

The work to fix SOS is tracked [here](https://github.com/dotnet/diagnostics/issues/2483) and the work to fix clrmd is tracked [here](https://github.com/microsoft/clrmd/issues/936).

### CODE REVIEW

**Comment by Maoni0** [comment]
why are we not doing the same thing as we did for the `gc_heap`/`dac_gc_heap`? seems like the same type of problem.

I would also not use something like `saved_sweep_ephemeral_start` to identify if it's using regions or not.. we may not even have this field at all anymore in the future. would be a shame to keep it just for this purpose. we do have these fields -

```cplusplus
    gcDacVars->major_version_number = 1;
    gcDacVars->minor_version_number = 0;
```
can these actually be put to use?

**Comment by Maoni0** [comment]
is there any reason why each dac type is defined in its own header instead of them being in gcinterface.dac.h since they are part of the interface...?

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -45589,6 +45589,18 @@ void PopulateDacVars(GcDacVars *gcDacVars)
...
+
+#define DEFINE_FIELD(field_name, field_type) offsetof(generation, field_name),
+#define DEFINE_DPTR_FIELD(field_name, field_type) offsetof(generation, field_name),
+#define DEFINE_MISSING_FIELD -1,
+
+#include "generation_fields.h"
+
+#undef DEFINE_MISSING_FIELD
+#undef DEFINE_DPTR_FIELD
+#undef DEFINE_FIELD
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:45602]: do you really need to define and undefine all these macros for each type? could you define a macro for the class name so you don't need to repeat this? eg

```cplusplus
#define DEFINE_FIELD(field_name, field_type) offsetof(CLASS_NAME, field_name),
#define DEFINE_MISSING_FIELD -1,

static int gc_heap_field_offsets[] = {
#define CLASS_NAME gc_heap
#include "gcheap_fields.h"
};
```

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -45589,6 +45589,18 @@ void PopulateDacVars(GcDacVars *gcDacVars)
     };
     static_assert(sizeof(gc_heap_field_offsets) == (GENERATION_TABLE_FIELD_INDEX + 1) * sizeof(int), "GENERATION_TABLE_INDEX mismatch");
 #endif //MULTIPLE_HEAPS
+    static int generation_field_offsets[] = {
+
+#define DEFINE_FIELD(field_name, field_type) offsetof(generation, field_name),
+#define DEFINE_DPTR_FIELD(field_name, field_type) offsetof(generation, field_name),
+#define DEFINE_MISSING_FIELD -1,
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:45596]: instead of defining a missing field to just -1, I would define it like this so it's very easy to see which missing field you are defining -

`#define DEFINE_MISSING_FIELD(field_name) -1,`

Comment (Maoni0) [reply src/coreclr/gc/gc.cpp:45596]: (sorry this is from the last PR but I didn't get a chance to review before you merged)

File: src/coreclr/gc/generation_fields.h [hunk 3]
```diff
@@ -0,0 +1,7 @@
+DEFINE_FIELD      (allocation_context, gc_alloc_context)
```
Comment (Maoni0) [inline src/coreclr/gc/generation_fields.h:1]: nit - instead of naming these headers generation_fields.h/gcheap_fields.h, I would name them dac_generation_fields.h/dac_gcheap_fields.h, just to make it very clear that these are different from other headers in the sense that they are only used for dac (I'd be fine if you want to make a new dir for them too as we might have others in the future but I don't have a strong opinion as long as it's clear they are for dac).

File: src/coreclr/debug/daccess/dacdbiimpl.cpp [hunk 4]
```diff
@@ -6557,7 +6559,9 @@ HRESULT DacHeapWalker::NextSegment()
 
         mCurrObj = mHeaps[mCurrHeap].Segments[mCurrSeg].Start;
 
-        if (mHeaps[mCurrHeap].Gen0Start <= mCurrObj && mHeaps[mCurrHeap].Gen0End > mCurrObj)
+        bool isGen0 = IsRegion() ? (mHeaps[mCurrHeap].Segments[mCurrSeg].Generation == 0) : (mHeaps[mCurrHeap].Gen0Start <= mCurrObj && mHeaps[mCurrHeap].Gen0End > mCurrObj);
```
Comment (Maoni0) [inline src/coreclr/debug/daccess/dacdbiimpl.cpp:6562]: nit - this line is so long...

File: src/coreclr/gc/gcinterface.dac.h [hunk 5]
```diff
@@ -169,6 +175,11 @@ struct opaque_gc_heap
     uint8_t unused;
 };
 
+struct opaque_generation
+{
+    uint8_t unused;
+};
```
Comment (Maoni0) [inline src/coreclr/gc/gcinterface.dac.h:181]: nit - instead of naming these `opaque`, is it better to name them `unused`? and can you please add a comment to explain why they are here?

**Review by Maoni0 — CHANGES_REQUESTED** [review]
the rest LGTM

File: src/coreclr/gc/gcinterface.dac.h [hunk 6]
```diff
@@ -46,9 +46,15 @@ class dac_heap_segment {
 // of a generation and its allocation context.
 class dac_generation {
 public:
-    gc_alloc_context allocation_context;
-    DPTR(dac_heap_segment) start_segment;
-    uint8_t* allocation_start;
+#define ALL_FIELDS
+#define DEFINE_FIELD(field_name, field_type) field_type field_name;
```
Comment (Maoni0) [inline src/coreclr/gc/gcinterface.dac.h:50]: is there a case where `ALL_FIELDS` would not be defined?

Comment (Maoni0) [inline src/coreclr/gc/gcinterface.dac.h:50]: >DEFINE_FIELD [](http://example.com/codeflow?start=8&length=12)

I see you are defining these macros again here....duplicated from gc.cpp. can you define them all in this header so you don't have to duplicate the definition in gc.cpp?

**Comment by Maoni0** [comment]
other than those comments above the rest LGTM

File: src/coreclr/gc/gcinterface.dac.h (hunk 6 above)
Comment (cshung) [reply src/coreclr/gc/gcinterface.dac.h:50]: The only case where `ALL_FIELDS` is not defined is `gc.cpp` where we generate the offset array. There, we need to make sure we do not attempt to use the `offsetof` operator and emit a -1 directly.

Comment (cshung) [reply src/coreclr/gc/gcinterface.dac.h:50]: The definition here and the definition in `gc.cpp` are different, they have the same name but different content. Here we are using the macro to define the fields, but there we are using them to generate array values.

Comment (Maoni0) [reply src/coreclr/gc/gcinterface.dac.h:50]: > they have the same name but different content

doesn't that cause unnecessary confusion? if they are different we could give them different names...

Comment (Maoni0) [reply src/coreclr/gc/gcinterface.dac.h:50]: I see; makes sense

Comment (cshung) [reply src/coreclr/gc/gcinterface.dac.h:50]: That is the only way I can think of to have a single copy of that list to fields to generate three different sets of things. The field declaration, the array index offset, as well as the loading code in the DAC. 

This is based on what @noahfalk suggested in https://github.com/dotnet/runtime/pull/56056#issuecomment-889682100

Comment (Maoni0) [reply src/coreclr/gc/gcinterface.dac.h:50]: ahh got it. that's fine then.

**Review by Maoni0 — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

File: src/coreclr/debug/daccess/request_common.h [hunk 7]
```diff
@@ -29,35 +29,27 @@ DPTR(T) Dereference(DPTR(T*) ptr)
...
-    DPTR(opaque_gc_heap*) heap_table = Dereference(heaps);
-    DPTR(opaque_gc_heap*) ptr = TableIndex(heap_table, index, sizeof(void*));
+    DPTR(unused_gc_heap*) heap_table = Dereference(heaps);
+    DPTR(unused_gc_heap*) ptr = TableIndex(heap_table, index, sizeof(void*));
     return Dereference(ptr).GetAddr();
 }
 
-// Indexes into a given generation table, returning a DPTR to the
-// requested element (the element at the given index) of the table.
-inline DPTR(dac_generation)
```
[the remark this answers is not in the document]
Comment (cshung) [reply src/coreclr/debug/daccess/request_common.h:41]: This is meant to reduce complexity at a small cost of performance. If I were to do that lazily, I have to either introduce a class that performs the loading lazily on access (one could imagine how complex it would be to make the macros to generate such a class) or to requires all the downstream usages to use the `LOAD` macro (one could imagine how messy that would look). 

The cost of not lazily loading them was just reading a few more bytes here, which is very probably cached anyway. IMO, this is a very reasonable trade-off to make.

File: src/coreclr/debug/daccess/dacdbiimpl.cpp [hunk 8]
```diff
@@ -6739,54 +6745,107 @@ HRESULT DacHeapWalker::ListNearObjects(CORDB_ADDRESS obj, CORDB_ADDRESS *pPrev,
 
 HRESULT DacHeapWalker::InitHeapDataWks(HeapData *&pHeaps, size_t &pCount)
 {
+    bool regions = IsRegion();
```
[the remark this answers is not in the document]
Comment (cshung) [reply src/coreclr/debug/daccess/dacdbiimpl.cpp:6748]: I can take care of these in a follow-up.

File: src/coreclr/debug/daccess/dacdbiimpl.cpp [hunk 9]
```diff
@@ -6739,54 +6745,107 @@ HRESULT DacHeapWalker::ListNearObjects(CORDB_ADDRESS obj, CORDB_ADDRESS *pPrev,
...
     int i = 0;
-    for (; seg && (i < count); ++i)
+
+    // Small object heap segments
+    if (regions)
     {
-        pHeaps[0].Segments[i].Start = (CORDB_ADDRESS)seg->mem;
-        if (seg.GetAddr() == (TADDR)*g_gcDacGlobals->ephemeral_heap_segment)
+        seg = gen2.start_segment;
+        for (; seg && (i < count); ++i)
```
[the remark this answers is not in the document]
Comment (cshung) [reply src/coreclr/debug/daccess/dacdbiimpl.cpp:6794]: I can take care of these in a follow-up.

File: src/coreclr/debug/daccess/request_common.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (hoyosjs) [reply src/coreclr/debug/daccess/request_common.h:41]: Just wanted to make sure dragons did not live here. Makes sense given the offset approach.
