### PR TITLE
Change all "unmanaged" (no GC fields) sequential types to have sequential layout.

### LINKED ISSUE #12977: Why Nullable<byte> is aligned to 8 bytes instead of 2 bytes as short does?
Use `System.Runtime.CompilerServices.Unsafe.SizeOf<T>()` and `ValueTuple` to do the test, seems it's always the same on different version of .net.(x86 aligned to 4 bytes)
Don't know why it need such a big padding, and use 3 more times(1 more time for x86) memory than it actually needed.

 Type  | Length  
---|---
 byte?  | 2  
 short  | 2  
 ValueTuple<byte?> |  2 
 ValueTuple<short> |  2 
 ValueTuple<short, short> |  4 
 ValueTuple<byte?, byte?> |  16
 ValueTuple<short, short, short> |  8 
ValueTuple<byte?, byte?, byte?>| 24

### LINKED ISSUE #44579: Struct promoted to auto-layout if it contains a non-blittable field type + explicit layout field type
### Description

We have discovered an unexpected behavior of the runtime regarding layout of a struct in memory with .NET CLR.
In the following example, the struct `BoolAndExplicitStruct` layout will be promoted to an auto-layout because of the presence of the field `public bool Bool` and `public ExplicitLayoutStruct ExplicitLayout` _together_:

```csharp
   [StructLayout(LayoutKind.Explicit)]
    struct ExplicitLayoutStruct {
        [FieldOffset(0)] public byte B00;
    }

    struct RegularStruct
    {
        public int Field;
    }

    struct BoolAndExplicitStruct
    {
        // bool AND a field with an explicit layout struct
        // change the layout of this struct to Auto instead of sequential
        public bool Bool;
        public ExplicitLayoutStruct ExplicitLayout;
        public int Int32;
        public RegularStruct RegularStruct;
        public long Int64;
    }

    // Field Int64: starts at offset 0
    // Field Int32: starts at offset 8
    // Field Bool: starts at offset 12
    // Field ExplicitLayout: starts at offset 16
    // Field RegularStruct: starts at offset 24
```

This is causing lots of trouble on the Burst compiler on our side, because as we are using these structs in native code, we expect the same sequential+explicit layout than .NET, but we were not expecting an implicit auto-layout promotion in this case (We haven't implemented today the auto-layout because we fear its implementation dependent behavior)

It seems to be related around this function [CheckIfDisqualifiedFromManagedSequential](https://github.com/dotnet/runtime/blob/29e9b5b7fd95231d9cd9d3ae351404e63cbb6d5a/src/coreclr/src/vm/classlayoutinfo.cpp#L237-L299) or the caller of this function, but haven't identified exactly in the code when this flip occurs.

Do you know the reason of this auto-layout promotion? Could we revert that behavior? (We will be happy to make a PR)

### Configuration

Happens on all OS, all CPU and all .NET version (including .NET framework) but not on Mono (because Mono doesn't have auto-layout promotion afaik)

### Regression?

Nope.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This is a prereq for #60639 

This enables us to use the managed layout as the native layout for all LayoutKind.Sequential "C# unmanaged" structs, which is required for reconciling the "unmanaged" and "blittable" concepts.

Fixes https://github.com/dotnet/runtime/issues/44579
Fixes https://github.com/dotnet/runtime/issues/12977

### CODE REVIEW

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs [hunk 1]
```diff
@@ -196,9 +196,9 @@ protected override ModuleFieldLayout CreateValueFromKey(EcmaModule module)
                         }
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs:196]: I would expect that the call to `MarshalUtils.IsBlittableType` is going disappear from this file as part of this change. Is it possible?

Comment (jkoritzinsky) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs:196]: We'd need to get rid of the explicit layout size compat quirk in both CoreCLR and here, which I'm okay doing if we don't have concerns about removing it.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs [hunk 2]
```diff
@@ -803,7 +803,7 @@ protected override ComputedInstanceFieldLayout ComputeInstanceFieldLayout(Metada
                 return ComputeExplicitFieldLayout(type, numInstanceFields);
             }
             else
-            if (type.IsEnum || MarshalUtils.IsBlittableType(type) || IsManagedSequentialType(type))
+            if (type.IsEnum || (type.IsSequentialLayout && !type.ContainsGCPointers))
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs:806]:
```suggestion
            if (type.IsSequentialLayout && !type.ContainsGCPointers)
```
Can it be simplified to this? Or is the `IsEnum` check important?

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs (hunk 1 above)
Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs:196]: I would love to get rid of this quirk if possible.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs (hunk 2 above)
Comment (jkoritzinsky) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs:806]: C# enums are auto-layout, so I wanted to keep this check.
https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgCmA7ArgWwAQCieA3ngGJ4C+QA===

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs (hunk 1 above)
Comment (jkoritzinsky) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs:196]: I'll try to remove it then.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs (hunk 2 above)
Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs:806]: Enums are single field, so both sequential and auto layout algorithms should produce exact same output. I would be curious if there are situations where this makes a difference for valid enums.

Comment (jkoritzinsky) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs:806]: Although, enum layout should be the same if sequential or auto, so removing this would probably be okay.

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 3]
```diff
@@ -369,7 +367,7 @@ protected ComputedInstanceFieldLayout ComputeExplicitFieldLayout(MetadataType ty
                 instanceSize,
                 largestAlignmentRequired,
                 layoutMetadata.Size,
-                alignUpInstanceByteSize: AlignUpInstanceByteSizeForExplicitFieldLayoutCompatQuirk(type),
+                alignUpInstanceByteSize: false,
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:370]: Should this rather be `true`? `true` would maintain the existing behavior for blittable and managed sequential types, but allow it to differ for auto layout and similar types.

Comment (jkoritzinsky) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:370]:
```suggestion
                alignUpInstanceByteSize: true,
```

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 4]
```diff
@@ -369,7 +367,7 @@ protected ComputedInstanceFieldLayout ComputeExplicitFieldLayout(MetadataType ty
                 instanceSize,
                 largestAlignmentRequired,
                 layoutMetadata.Size,
-                alignUpInstanceByteSize: AlignUpInstanceByteSizeForExplicitFieldLayoutCompatQuirk(type),
+                alignUpInstanceByteSize: true,
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:370]: The `alignUpInstanceByteSize` is always true now. It can be deleted.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs (hunk 2 above)
Comment (jkoritzinsky) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs]: Using sequential layout turned out to be the easiest way to enforce that enum types get the right alignment (with auto layout, 8-byte enums were getting the wrong alignment on x86)

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs]: I am wondering whether it is a bug or a feature of the auto layout algorithm.

Comment (jkoritzinsky) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs]: I'll give it a shot to change this behavior and see what breaks.

Comment (jkoritzinsky) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs]: Looking at the code, it seems to be an explicit behavior choice to never require stricter alignment than `TARGET_POINTER_SIZE` except where we have a type that "requires 8-byte alignment" on arm32.
https://github.com/dotnet/runtime/blob/7a62468ffbb90008e08b30471bfa94b2d4c58726/src/coreclr/vm/methodtablebuilder.cpp#L8217-L8234

The reason that enums fields don't fall into this case is that our signature walking for layout (at least in the sequential case) normalizes enums to their underlying type.

Comment (jkoritzinsky) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs]: I've updated the managed type system to normalize enums to their underlying type for sequential and explicit layout and removed this case again. Let me know what you think!

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs]: Nice! LGTM.

**Comment by jkotas** [comment]
Is the current change also fixing https://github.com/dotnet/runtime/issues/12977?

The changes in the managed type system looks good to me. The changes in the runtime type systems are harder to reason about - if the behavior matches the managed type system, then it looks good as well.

We have a special stress mode to check that the field layout algorithm matches between crossgen2 and runtime. Do you know how to run it? If not, @trylek is the person to ask.

**Comment by trylek** [comment]
> We have a special stress mode to check that the field layout algorithm matches between crossgen2 and runtime. Do you know how to run it? If not, @trylek is the person to ask.

I believe that both local test execution in Crossgen2 mode and all CG2 pipelines use the field layout validation logic (CG2 command-line argument <code>-verify-type-and-field-layout</code). It is definitely useful to validate these changes both in the composite and per-assembly CG2 pipelines as the notion of 'local' vs. 'external compilation unit' differs between them with subtle effects on layouts (e.g. cross-bubble alignment at the parent - derived type boundary).

**Comment by jkoritzinsky** [comment]
I believe I've been using the special field layout algorithm validation throughout working on this PR. I'll run some of the outer pipelines to make sure that things are working across more assemblies.

/azp run runtime-coreclr outerloop
/azp run runtime-coreclr crossgen2-composite

**Comment by jkoritzinsky** [comment]
The PALTests failure in `runtime-coreclr outerloop` is also occuring in `main` and the Multi-Core JIT test failure in `runtime-coreclr crossgen2-composite` is also occurring in `main`.

So looks like we're all good for matching the layout algorithms.

I don't believe this is fixing #12977, but I'll go check.

**Comment by trylek** [comment]
I'll send out a PR to disable the BasicTestWithMcj, with CG2 I saw that one a couple of times, I guess it must be a new tests as I don't recall seeing it before.

**Comment by jkoritzinsky** [comment]
This fixes the `Nullable<byte>` case in https://github.com/dotnet/runtime/issues/12977, but doesn't fix the `ValueTuple` cases as I didn't modify the auto-layout algorithm. I'll try to add a fix for the other case and see how easy it is to do.

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 5]
```diff
@@ -8169,35 +8169,63 @@ VOID    MethodTableBuilder::PlaceInstanceFields(MethodTable ** pByValueClassCach
...
+                else if (pByValueMT->HasLayout())
+                {
+                    int fieldAlignmentRequirement = pByValueMT->GetLayoutInfo()->m_ManagedLargestAlignmentRequirementOfAllMembers;
+                    largestAlignmentRequirement = max(largestAlignmentRequirement, fieldAlignmentRequirement);
+                    dwCumulativeInstanceFieldPos = (DWORD)ALIGN_UP(dwCumulativeInstanceFieldPos, fieldAlignmentRequirement);
+                }
+                else
+                {
+                    // We are in the case of an auto-layout struct that has no GC pointers and no other alignment requirements.
+                    // We don't have a good place to track alignment, so we're going to do a best-effort sort of option and use
```
Comment (jkotas) [inline src/coreclr/vm/methodtablebuilder.cpp:8217]: I think it would be fine to add a field to `EEClassOptionalFields` for this, so that we can track it precisely. We really only need to track it when it is different than the best-effort default that should not be common.

Comment (jkoritzinsky) [reply src/coreclr/vm/methodtablebuilder.cpp:8217]: I'll take a look at doing that.

**Comment by jkoritzinsky** [comment]
@jkotas I've updated this PR to now fix #12977. This is ready for another round of review.

File: src/coreclr/vm/classlayoutinfo.cpp [hunk 6]
```diff
@@ -282,16 +281,32 @@ namespace
...
+                    // this field type has GC pointers in it, which need to be pointer-size aligned
+                    // so do this if it has not been done already
+                    pManagedPlacementInfo->m_alignment = TARGET_POINTER_SIZE;
+                    // Types that have GC Pointer fields (objects or byrefs) are disqualified from ManagedSequential layout.
+                    return TRUE;
+                }
+                else
+                {
+                    pManagedPlacementInfo->m_alignment = pByValueMT->GetFieldAlignmentRequirement();
+                }
```
Comment (jkotas) [inline src/coreclr/vm/classlayoutinfo.cpp:308]: Nit: The formatting looks off. Unindent the whole block?

File: src/coreclr/vm/class.h [hunk 7]
```diff
@@ -1672,7 +1692,7 @@ class EEClass // DO NOT CREATE A NEW EEClass USING NEW!
         // unused                              = 0x00010000,
         VMFLAG_NO_GUID                         = 0x00020000,
         VMFLAG_HASNONPUBLICFIELDS              = 0x00040000,
-        // unused                              = 0x00080000,
+        VMFLAG_HAS_CUSTOM_FIELD_ALIGNMENT            = 0x00080000,
```
Comment (jkotas) [inline src/coreclr/vm/class.h:1695]:
```suggestion
        VMFLAG_HAS_CUSTOM_FIELD_ALIGNMENT      = 0x00080000,
```

**Comment by jkotas** [comment]
It looks good to me (once it builds on all platforms).

Are you happy with the test coverage we have for this, or do you plan to add more tests?

It would be useful to also get a review from @trylek or @davidwrighton .

File: src/coreclr/vm/classlayoutinfo.cpp [hunk 8]
```diff
@@ -282,16 +281,32 @@ namespace
...
             {
+                pManagedPlacementInfo->m_alignment = 8;
+            }
+            else
+#endif // FEATURE_64BIT_ALIGNMENT
+            if (pNestedType.GetMethodTable()->ContainsPointers())
+            {
+                // this field type has GC pointers in it, which need to be pointer-size aligned
+                // so do this if it has not been done already
                 pManagedPlacementInfo->m_alignment = TARGET_POINTER_SIZE;
```
Comment (trylek) [inline src/coreclr/vm/classlayoutinfo.cpp:301]: What about types that contain both GC pointers and 64-bit fields in <code>RequiresAlign8</code> mode (on arm32), won't this override the previously set 8-alignment?

**Review by trylek — APPROVED** [review]
I love this change, thanks so much Jeremy for finally putting some order to all this mess!

File: src/coreclr/vm/classlayoutinfo.cpp (hunk 8 above)
Comment (jkoritzinsky) [reply src/coreclr/vm/classlayoutinfo.cpp:301]: There’s an `else` above in the Align8 case so this won’t be hit then.

Comment (trylek) [reply src/coreclr/vm/classlayoutinfo.cpp:301]: Right you are, sorry for overlooking, this looks good to me now.

**Comment by jkoritzinsky** [comment]
It looks like the macOS ARM64 test failures are https://github.com/dotnet/runtime/issues/62747 due to the following multidimensional array:

https://github.com/dotnet/runtime/blob/fbabdb663cb7895e5e6002960be2fe560b957b2e/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L885

**Comment by jkoritzinsky** [comment]
I've confirmed these failures are also in main now that #61938 has been merged long enough to have outerloop runs triggered against it.

I think the test coverage already have makes me comfortable enough to merge this PR. I'll add more test coverage when I implement #60639.
