### PR TITLE
Fixing impMathIntrinsic to not insert unnecessary casts

### LINKED ISSUE #47856: Failing assert in ILogB benchmark
I've merged one big PR of mine to the performance repo and some CI legs went red after that. I thought it was my fault, but according to the [logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-performance-refs-heads-master-b0e291e414a14b52b3/Partition0/console.94d3d474.log?sv=2019-07-07&se=2021-02-24T12%3A04%3A47Z&sr=c&sp=rl&sig=IWpBGVp7VJ0YkF6VTB3etbJSGxm7l5EWkCWhKYaJowk%3D) the windows CI leg for .NET 6 failed because of the following condition:

https://github.com/dotnet/performance/blob/4e14ecc54759224121b807c70e46fb1d9ee0e7d6/src/benchmarks/micro/runtime/Math/Functions/Double/ILogB.cs#L31

```log
[2021/02/04 12:35:55][INFO] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2021/02/04 12:35:55][INFO]  ---> System.Exception: Expected Result                 2499; Actual Result                    0
[2021/02/04 12:35:55][INFO]    at System.MathBenchmarks.Double.ILogBTest() in C:\h\w\A401087B\p\src\benchmarks\micro\runtime\Math\Functions\Double\ILogB.cs:line 33
[2021/02/04 12:35:55][INFO]    at System.MathBenchmarks.Double.ILogB() in C:\h\w\A401087B\p\src\benchmarks\micro\runtime\Math\Functions\Double\ILogB.cs:line 18
[2021/02/04 12:35:55][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_354.WorkloadActionUnroll(Int64 invokeCount) in C:\h\w\A401087B\p\artifacts\bin\MicroBenchmarks\Release\net6.0\aba3fe28-ae33-452f-9d08-31981993ac55\aba3fe28-ae33-452f-9d08-31981993ac55.notcs:line 210808
```

I was able to reproduce it on my PC:

```cmd
git clone https://github.com/dotnet/performance.git repro
py .\repro\scripts\benchmarks_ci.py -f net6.0 --filter System.MathBenchmarks.Double.ILogB
```

@tannergooding is this expected?

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #47856

### CODE REVIEW

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -4615,15 +4615,22 @@ GenTree* Compiler::impMathIntrinsic(CORINFO_METHOD_HANDLE method,
...
         {
             case 1:
                 op1 = impPopStack().val;
 
-                assert(varTypeIsFloating(op1));
+                arg     = sig->args;
+                op1Type = JITtype2varType(strip(info.compCompHnd->getArgType(sig, arg, &tmpClass)));
 
-                if (op1->TypeGet() != callType)
+                if (op1->TypeGet() != genActualType(op1Type))
```
Comment (tannergooding) [inline src/coreclr/jit/importer.cpp:4631]: I really would have preferred to just delete these checks altogether. However, it looks  like there are other places in the importer that are doing similar and that imply the JIT supports implicitly passing `float` args where `double` is expected and that it is supposed to do the right thing.

For example: 
* https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/importer.cpp#L955-L963
* https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/importer.cpp#L11834-L11841
* https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/importer.cpp#L12757-L12771
* https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/importer.cpp#L13204-L13227
* https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/importer.cpp#L17944-L17956

I'm not sure how consistently we are actually doing this. For example, I don't think any of the HWIntrinsic code is attempting to handle this scenario and I'm not sure what else in the JIT might generate such nodes.

Comment (tannergooding) [reply src/coreclr/jit/importer.cpp:4631]: I can somewhat understand implicitly allowing `float->double` since it is lossless; but the implicit from `double->float` at least seems like it would have been undesirable since that means there is loss of data.

I'm guessing that is has something to do with only having a single spec'd stack type for floats (even though we internally track `TYP_FLOAT` and `TYP_DOUBLE`)

**Comment by kunalspathak** [comment]
@tannergooding - are you looking into the CI test failure? Also, did you get chance to do asm diff before/after your changes?

**Comment by tannergooding** [comment]
I haven't looked yet. I should be able to get to it tomorrow.

**Comment by tannergooding** [comment]
CI test failure was an unrelated flaky test. Building the repo to get diffs, although I only expect to find them in the `ILogB` tests.

**Comment by tannergooding** [comment]
No diffs, except when comparing the new tests (checked for `--frameworks`, `--benchmarks`, and `--tests` both with and without `--pmi`):
```
Total bytes of delta: -2 (-0.01% of base)
    diff is an improvement.


Top file improvements (bytes):
          -2 : Functions_ro.dasm (-0.01% of base)

1 total files with Code Size differences (1 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
          -1 (-0.63% of base) : Functions_ro.dasm - Double:ILogBTest()
          -1 (-0.63% of base) : Functions_ro.dasm - Single:ILogBTest()

Top method improvements (percentages):
          -1 (-0.63% of base) : Functions_ro.dasm - Double:ILogBTest()
          -1 (-0.63% of base) : Functions_ro.dasm - Single:ILogBTest()

2 total methods with Code Size differences (2 improved, 0 regressed), 123 unchanged.
```

**Review by kunalspathak — APPROVED** [review]
LGTM. Thanks!
