### PR TITLE
JIT: Handle enums in box-unbox optimization

### LINKED ISSUE #55355: Inefficient codegen for enum -> object -> int casts
### Description

The JIT usually optimizes box + unbox cases, this isn't the case for enum -> object -> int though. Filled per request from @EgorBo 

### Configuration

Sharplab Core CLR v5.0.721.25508

### Regression?

No idea.

### Data

[Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgy5UQAtsUPgBlsweszYdFS5cQBMlKgHZlAb2Xln5ANoApVhgDiMJiOkACgwATz4YCAAzQIBRJgZ8KgBKJIBdZwB6DPImCAwnF1cAWRgMdQgAEwBJfkFAkrLKmr5BAHk+NggmXBoAQQBzfthcXFYJGCqmQVYmGf60gudiAGZrJHJgCAhBcgAJPAAxQWx+gB4AFQA+QPPyCWxBBhg0clvI4/nF8kclFz/KGzkQKBGYYJKBCDAABWMDAYPujxg5AAZEDQeDITC4Ul3ickuQALwEoEMdEQ6GwsG4/qmP4AX2UDLMKlWfgS5DiCSo33IvReACFyHSgA)

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/55355

When we box a enum and unbox it as integer (and vice versa) JIT should be able to optimize it as no-op. E.g. https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgy5UQAtsUPgBlsweszYdFS5cQBMlKgHZlAb2Xln5ANoApVhgDiMJiOkACgwATz4YCAAzQIBRJgZ8KgBKJIBdZwB6DPImCAwnF1cAWRgMdQgAEwBJfkFAkrLKmr5BAHk+NggmXBoAQQBzfthcXFYJGCqmQVYmGf60gudiAGZrJHJgCAhBcgAJPAAxQWx+gB4AFQA+QPPyCWxBBhg0clvI4/nF8kclFz/KGzkQKBGYYJKBCDAABWMDAYPujxg5AAZEDQeDITC4Ul3ickuQALwEtEsDHQ2Fg3H9Ux/AC+ynpZhUqz8CXIcQSVG+5F6LwAQuRaUA==

New codegen:
```asm
; Program.HasFlag
       and      ecx, edx
       xor      eax, eax
       cmp      ecx, edx
       sete     al
       ret      
; Total bytes of code: 10
```
The change is small, the verbosity is due to JIT-EE update, I had to add a flag to `compareTypesForEquality` because in some places it's still expected to be more conservative around enums vs integers.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Can you please take care of #69900 too since you are changing JIT-EE GUID?

**Comment by EgorBo** [comment]
> Can you please take care of #69900 too since you are changing JIT-EE GUID?

Done

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -7455,7 +7455,7 @@ int Compiler::impBoxPatternMatch(CORINFO_RESOLVED_TOKEN* pResolvedToken,
 
                 // See if the resolved tokens describe types that are equal.
                 const TypeCompareState compare =
-                    info.compCompHnd->compareTypesForEquality(unboxResolvedToken.hClass, pResolvedToken->hClass);
+                    info.compCompHnd->compareTypesForEquality(unboxResolvedToken.hClass, pResolvedToken->hClass, false);
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp:7458]: I wonder if we could just call `getTypeForPrimitiveValueClass` on the classes here. I guess it's not the exact same logic but maybe it is ok?

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 2]
```diff
@@ -2637,6 +2637,12 @@ private TypeCompareState compareTypesForEquality(CORINFO_CLASS_STRUCT_* cls1, CO
             // If neither type is a canonical subtype, type handle comparison suffices
             if (!type1.IsCanonicalSubtype(CanonicalFormKind.Any) && !type2.IsCanonicalSubtype(CanonicalFormKind.Any))
             {
+                if (!exact)
+                {
+                    // Compare with Enum's underlying primitive type
+                    type1 = type1.IsEnum ? type1.UnderlyingType : type1;
+                    type2 = type2.IsEnum ? type2.UnderlyingType : type2;
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:2644]: `UnderlyingType` returns `this` if the type is not an enum.

```suggestion
                    type1 = type1.UnderlyingType;
                    type2 = type2.UnderlyingType;
```

File: src/coreclr/jit/importer.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/importer.cpp]: Great idea! addressed 🙂

**Review by jakobbotsch — APPROVED** [review]
