### PR TITLE
Drop generic type constraints from Unsafe.BitCast

### LINKED ISSUE #99006: [Perf] Windows/x64: 3 Regressions on 2/19/2024 10:53:50 AM
### Run Information

Name | Value
-- | --
Architecture | x64
OS | Windows 10.0.18362
Queue | TigerWindows
Baseline | [d972a19c077e899d0b3fff97d955968e50906396](https://github.com/dotnet/runtime/commit/d972a19c077e899d0b3fff97d955968e50906396)
Compare | [5e1caf14fd94b4ed85357002303c8935fedacb8b](https://github.com/dotnet/runtime/commit/5e1caf14fd94b4ed85357002303c8935fedacb8b)
Diff | [Diff](https://github.com/dotnet/runtime/compare/d972a19c077e899d0b3fff97d955968e50906396...5e1caf14fd94b4ed85357002303c8935fedacb8b)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Tests.Perf_String

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[IndexOfAny - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_String.IndexOfAny.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime/Perf.String.cs#L181-#L184>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3NvZ4CZumhI1khFpKCVAICR5Q6i62Bv70H1Ye+fWrhC/nTsnCk0qIb9YvvHM7Nxq13NgpkKQoKx58Zs8FIBArisusiWUmiQJoZm2CmwfK2W5BHrMukam0qLlIWxNvwCWmb5kXJ0QJ5gW3EJqXTXCFQlo/WZII0IZSvcSHthrMPYrk+A939FVYyzIngdNbwG4vVtZ5CrvzVQG9bftRDX/Ci0rNdVqy/MKmeVamR90qmXJRXua6wzoT5L8IdRyR8/oy/8pHfSZq2yvkDxF/UTADcjSNsEz4UTbsANtps0XcS/b1nThfzI3KucKunC9cRfeXCvdMa6nzpQFLBHcs4tkket1U3YKvCgaw1MmFqil9khX4cdmgzy7FXrDBH9ssS6y5WDZtcJNXQK6sVftTB5P6VS7lQBc63L/djzxaydbWSZL8pZkzILfnmAQDy7Ozs/PBqN1fDW+HI6Ho955fDWKLwev43gcx76EqaRkyB+BMMzvJKuD1tAniMirkGyakwrRYWsiP8rfK6jA+ZSof7mNe0ZegqmETdClzoInN9nhk3tAljunizAirZU3Tj4gB5WJ5oD4ZrUHHxndN0Di75gWDC154LYggXHNA5McNBGpUy0qqZLTTM0ON8kuhCNabgUk9L1rnftPNPujl5BAmdBjphTcJqwGE/4FEq/z3MkEAAA=>)</li></ul> | 7.88 ns | 11.71 ns | 1.49 | 0.31 | False | | |
|<ul><li>[Trim - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_String.Trim(s%3a%20%22%20Te%20st%20%20%22).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime/Perf.String.cs#L116-#L122>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/rPpiG9x8NU2VSEakoYUCQSHxG0LVxd7Yh3x31t65jSvEb+fOiUKTSsgvlm88Mzu32vUcma4IBUqjX/2GxxwJ4briRbrEUkEUgZcqI9F0qZKGC/SOWdfEZJI3PMKN7ubIUt0VjMsT4pSSnBtMjK0GXILvbUdDLwSPkbAvwYEdozbfmEDn+d5b1dqg6DhQdxZIm/uVIS6zTkxc+HoCZ1YA2gCcBf8qLis5U3LDs4qY4UrqH95MiZIXzWmuUvR+QvQHPMMtPfVe/09poS9cpnuF4AmpZwKuUZSm9l8Ip8oELWh3Sn8tHkTTozb8z/pGZlxiG64zbsObK6laxnXUO2mQSkL7bCNZZCquy1aBF3mtecKKBSmhHNJW+KleE08/FmrNCv7UYG1ky8GybYWbbYl25OyeuOE8HteZsruBFKty/3Y8+rGVrQwTJbyDlBl0a+QPeoOL837/fHAV98aTy+FkeNUZjEf98eXoba836fVcCV0JwYg/ITDK7gXb+o2hSxDCmwDW9UmF8LA+oRvl7xVWaH1KUr/s6r0gL1FXhYnIpk79ZzfZ4dMHJJZZp4sghMbKGUe3xFGmRX1AXLOag4tM9hsSuDsmOSMDj9zk4GvbPNTRQRPCNlFFJWR0mqne4TrahbBEw02BkffBts7+MOr90UnAlzpwmC4LbiK2RR38BfGU5RvSBAAA>)</li></ul> | 14.48 ns | 15.74 ns | 1.09 | 0.09 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_27_2024/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_String.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Tests.Perf_String*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c6083aa8-6b7a-42f1-bc3d-2bc2ac9e829239385436392436488/93bdd173-1d48-423e-9dcd-ebc52f42050e.zip?sv=2021-08-06&se=2024-03-17T11%3A52%3A59Z&sr=c&sp=rl&sig=5LU4a14LVBDgbBBufZkDDeNyawdVEEXHod09vm7uGOM%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9d3a4d4c-380b-4cd8-939b-2896bce2b042218ade9fb10466ab2/7711ad57-6399-4773-81fe-adef4ef259e7.zip?sv=2021-08-06&se=2024-03-20T17%3A43%3A57Z&sr=c&sp=rl&sig=CNKuZejruWoJUhOoMQEMoU0tfut9Rj04i8IZx%2FNtDMw%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | Windows 10.0.18362
Queue | TigerWindows
Baseline | [d972a19c077e899d0b3fff97d955968e50906396](https://github.com/dotnet/runtime/commit/d972a19c077e899d0b3fff97d955968e50906396)
Compare | [5e1caf14fd94b4ed85357002303c8935fedacb8b](https://github.com/dotnet/runtime/commit/5e1caf14fd94b4ed85357002303c8935fedacb8b)
Diff | [Diff](https://github.com/dotnet/runtime/compare/d972a19c077e899d0b3fff97d955968e50906396...5e1caf14fd94b4ed85357002303c8935fedacb8b)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in Microsoft.Extensions.Primitives.StringSegmentBenchmark

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[IndexOfAny - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/Microsoft.Extensions.Primitives.StringSegmentBenchmark.IndexOfAny.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/Microsoft.Extensions.Primitives/StringSegmentBenchmark.cs#L75-#L76>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UYY/SQBD9buJ/2G8t2oMCngpJjYCnoqIIfDPGLO3QjnZ3m9kt116Mv93dQvDgEtMvTff1vTdvJzNdANclgQBp9KPf7DYDAjYtMU9WUCgWRcxLlJFgelRKgwK8c9aUuIyzhkew070MeKJ7gqO8IE4oztBAbGw1hpL5XvX8mRcwj5OwL50TewPafOYCnOdrb4ExKa12pntTGZAaldTdJaFAg3vQ3bUhlOkaUneDKdgsgtOv7lwmUH3ZTWT9L8aqlDMld5iWxI3z+ebNlCgwb04LlYD3nUV/mGfQ0hPv8f+UFvqIMjkqhEt5T4AaRGFq/4FwokynBW2u9Kd8L5rGteF/0DcyRQltuM64DW+hpGoZ11Hn0gAVBPbZRrJM1aYuWgVeZrXGmOdLUkI5pK3wfb0lTN7lastzvGuwNrLVYNW2wk1VgJ1FO3puYs9neKbswgBtVHF8O9+HjZWtDRcFe8USbsDtlj8IB8Orfv9q8GITjsbX1+Nh2H0Zjkb94ehpGI7D0JXQpbAzjnfAOKU/BK/8xtAlCNiTDtvWFxWC004FbpS/llCC9SlI/bT7+IC8Al3mJiKbOvHv3eSAT/ZAPLVOw07AGitnHL0lBJnk9QlxzWoOLjLZb0DM3THOOBl2iyZjvrbNAx2dNAGrYpWXQkaXmeoDrqNDCEs0aHKIvDe2dfYvUh+PTsJ8qTsO00WOJuIV6M5fchkkfecEAAA=>)</li></ul> | 6.26 ns | 7.91 ns | 1.26 | 0.17 | False | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_27_2024/refs/heads/main_x64_Windows%2010.0.18362_Regression/Microsoft.Extensions.Primitives.StringSegmentBenchmark.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'Microsoft.Extensions.Primitives.StringSegmentBenchmark*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c6083aa8-6b7a-42f1-bc3d-2bc2ac9e829239385436392436488/93bdd173-1d48-423e-9dcd-ebc52f42050e.zip?sv=2021-08-06&se=2024-03-17T11%3A52%3A59Z&sr=c&sp=rl&sig=5LU4a14LVBDgbBBufZkDDeNyawdVEEXHod09vm7uGOM%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9d3a4d4c-380b-4cd8-939b-2896bce2b042218ade9fb10466ab2/7711ad57-6399-4773-81fe-adef4ef259e7.zip?sv=2021-08-06&se=2024-03-20T17%3A43%3A57Z&sr=c&sp=rl&sig=CNKuZejruWoJUhOoMQEMoU0tfut9Rj04i8IZx%2FNtDMw%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### LINKED ISSUE #99205: [API Proposal]: Replace `TFrom : struct` constraint on `Unsafe.BitCast` with a dynamic check
### Background and motivation

In .NET 8 we've added the `Unsafe.BitCast` API as a less-unsafe alternative to `Unsafe.As` when casting between compatible structs.

One justification was that this would let us avoid codegen pessimization for values marked as address-taken in some cases. Example from the original API proposal: https://github.com/dotnet/runtime/issues/81334#issuecomment-1407730061

Due to the `TFrom : struct` constraint, we can't use this API in places like the `span.IndexOf*` helpers.
I propose we drop the generic constraint while keeping the runtime behavior the same.

With the constraint removed, I was able to confirm that we're able to flow the constness of values through for [this case](https://github.com/dotnet/runtime/blob/37445d4964a50eeff87ca7ed8cbdf251b547b779/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.T.cs#L1675-L1682): https://github.com/MihaZupan/runtime/commit/65c80545d66d960f0d6854296a021ba8ab47435d.

Quoting the conclusion from the initial API review:
> ... we should try having it constrained, and if we run into problems then get rid of them. They're easier to remove than add.

### API Proposal

```diff
namespace System.Runtime.CompilerServices;

public static class Unsafe
{
    public static TTo BitCast<TFrom, TTo>(TFrom value)
-       where TFrom : struct
        where TTo : struct;
}
```

### API Usage

```csharp
public static unsafe int IndexOf<T>(this Span<T> span, T value)
    where T : IEquatable<T>?
{
    if (RuntimeHelpers.IsBitwiseEquatable<T>() && sizeof(T) == sizeof(short))
    {
        return IndexOfValueType(
            ref Unsafe.As<T, short>(ref MemoryMarshal.GetReference(span)),
            Unsafe.BitCast<T, short>(value0), // <--- This is now legal
            span.Length);
    }

    // ...
}

private static unsafe int IndexOfValueType<T>(ref T searchSpace, T value, int length)
    where T : struct, INumber<T> => 42;
```

### Alternative Designs

We could drop the constraint on `TTo` as well while we're at it?

### Risks

Some erroneous usages move from being compile-time errors to run-time exceptions.
But this is an `Unsafe` API for a reason :)

### PR DESCRIPTION
**Pull request by MihaZupan**
Fixes #99205
Fixes #99006

https://github.com/MihuBot/runtime-utils/issues/354

Most diffs appear to be more inlining / removing unreachable branches. For example seeing that these `IndexOf*` calls are passing in 0 and therefore deleting the checks and unreachable calls to `PackedSpanHelpers`
https://github.com/dotnet/runtime/blob/34629761799d71a7c30c51fe2e2b78bf39611eb2/src/libraries/System.Net.Http/src/System/Net/Http/Headers/UriHeaderParser.cs#L65-L67

<details>
<summary>Part of the diff</summary>

```diff
 G_M22867_IG04:
-       xor      edx, edx
-       mov      dword ptr [rbp-0x2C], edx
-       mov      dword ptr [rbp-0x30], 127
-       movzx    rsi, word  ptr [rbp-0x2C]
-       movzx    rdx, word  ptr [rbp-0x30]
-       lea      r8d, [rsi-0x01]
-       cmp      r8d, 254
-       jae      SHORT G_M22867_IG05
-       lea      r8d, [rdx-0x01]
-       cmp      r8d, 254
-       jae      SHORT G_M22867_IG05
-       cmp      edx, esi
-       jl       SHORT G_M22867_IG05
-       sub      edx, esi
-       movsx    rdx, dx
-       movsx    rsi, si
-       mov      rdi, rax
-       mov      rax, 0xD1FFAB1E      ; code for System.PackedSpanHelpers:IndexOfAnyInRange[System.SpanHelpers+Negate`1[short]](byref,short,short,int):int
-       call     [rax]System.PackedSpanHelpers:IndexOfAnyInRange[System.SpanHelpers+Negate`1[short]](byref,short,short,int):int
-       jmp      SHORT G_M22867_IG06
-						;; size=77 bbWeight=1 PerfScore 15.25
-G_M22867_IG05:
-       mov      rdi, rax
+       mov      rdi, rcx
+       mov      ecx, esi
+       xor      esi, esi
+       mov      edx, 127
        mov      rax, 0xD1FFAB1E      ; code for System.SpanHelpers:NonPackedIndexOfAnyInRangeUnsignedNumber[ushort,System.SpanHelpers+Negate`1[ushort]](byref,ushort,ushort,int):int
        call     [rax]System.SpanHelpers:NonPackedIndexOfAnyInRangeUnsignedNumber[ushort,System.SpanHelpers+Negate`1[ushort]](byref,ushort,ushort,int):int
```

</details>

### CODE REVIEW

File: src/coreclr/jit/importercalls.cpp [hunk 1]
```diff
@@ -4717,6 +4717,13 @@ GenTree* Compiler::impSRCSUnsafeIntrinsic(NamedIntrinsic          intrinsic,
             ClassLayout*         toLayout  = nullptr;
             var_types            toType    = TypeHandleToVarType(toTypeHnd, &toLayout);
 
+            if (fromType == TYP_REF || info.compCompHnd->getBoxHelper(fromTypeHnd) == CORINFO_HELP_BOX_NULLABLE ||
+                toType == TYP_REF || info.compCompHnd->getBoxHelper(toTypeHnd) == CORINFO_HELP_BOX_NULLABLE)
```
Comment (jkotas) [inline src/coreclr/jit/importercalls.cpp:4721]: It is less than ideal to check for Nullable<T> by asking for box helper. This should be a new JIT/EE interface method.

Comment (jkotas) [reply src/coreclr/jit/importercalls.cpp:4721]: (The method should return `TypeCompareState`, e.g. similar to https://github.com/dotnet/runtime/pull/99555/files#diff-9219a33640f657e0bbc2f00f2aa40f6a5630999d8edd7e6d4f9bb79ff2ea8e03R2743 .)

Comment (MichalPetryka) [reply src/coreclr/jit/importercalls.cpp:4721]: Do we even really need to block nullable here?

Comment (tannergooding) [reply src/coreclr/jit/importercalls.cpp:4721]: Yes. We are exactly preserving the previous semantics. `where T : struct` requires the type be a non-nullable value type and thus excludes `Nullable<T>` which is considered special.

Comment (MihaZupan) [reply src/coreclr/jit/importercalls.cpp:4721]: @tannergooding does the change look correct otherwise (would it be fine assuming we "just" add the new helper for Nullable)?

Comment (tannergooding) [reply src/coreclr/jit/importercalls.cpp:4721]: As far as I'm aware it looks correct...

However, if we're going to be adding a JIT/EE interface to handle nullable anyways, it might be nice to just have some helper to see if a given `T` meets the `where T : struct` constraint to ensure this can be more simply handled overall and would ensure we don't miss anything in the future if what generics support is expanded (if generics start supporting things like `ref T` or `T*` for example).

File: src/coreclr/jit/importercalls.cpp [hunk 2]
```diff
@@ -4717,6 +4717,13 @@ GenTree* Compiler::impSRCSUnsafeIntrinsic(NamedIntrinsic          intrinsic,
...
+            {
+                // Fallback to the software implementation to throw when the types don't fit "where T : struct"
```
Comment (jkotas) [inline src/coreclr/jit/importercalls.cpp:4723]:
```suggestion
                // Fallback to the software implementation to throw when the types fail "default(T) == null" check.
```

File: src/coreclr/jit/importercalls.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/jit/importercalls.cpp:4721]: Nit: The implementation rejects `default(T) is null`. It happens to match `where T : struct` today, but it is not clear whether it would continue to match `where T : struct` if generics start supporting things like `ref T` or `T*`.

Comment (MihaZupan) [reply src/coreclr/jit/importercalls.cpp]: Added a `TypeCompareState isNullableType(CORINFO_CLASS_HANDLE cls)` helper now.

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 3]
```diff
@@ -2941,6 +2941,18 @@ private bool isExactType(CORINFO_CLASS_STRUCT_* cls)
             return _compilation.IsEffectivelySealed(type);
         }
 
+        private TypeCompareState isNullableType(CORINFO_CLASS_STRUCT_* cls)
+        {
+            TypeDesc type = HandleToObject(cls);
+
+            if (type.IsCanonicalDefinitionType(CanonicalFormKind.Any))
```
Comment (jkotas) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:2948]:
```suggestion
            if (type.IsGenericParameter)
```
`CanonicalFormKind.Any` is too conservative. `CanonicalFormKind.Specific` cannot ever be Nullable. On the other hand, it would be nice if this logic was same as isEnum logic below. The isEnum logic below does not handle UniversalCanon (it is ok - we have number of places that do not handle universal generics, universal generics are not used currently).

Comment (MihaZupan) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs]: Updated to `IsGenericParameter`, thanks.

Going by https://github.com/dotnet/runtime/pull/99555#discussion_r1520479299, would this be hit for something like this?
```c#
class C<TFrom>
{
    [NoInlining]
    public TTo BitCast<TTo>(TFrom t) => Unsafe.BitCast<TFrom, TTo>(t);
}

_ = new C<int?>().BitCast<long>(42);
```

Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs]: > Updated to IsGenericParameter, thanks.

The IsGenericParameter in the isEnum case is bogus and will never hit. I'm going to delete it in #101040 once all the legs finish, but it's already clear it never hits. Jit should never be asking about things that report true to `IsGenericParameter` (not in this API and not anywhere else).

It will never hit here either.

Comment (MihaZupan) [reply src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs]: Changed it to an assert now

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 4]
```diff
@@ -2941,6 +2941,14 @@ private bool isExactType(CORINFO_CLASS_STRUCT_* cls)
             return _compilation.IsEffectivelySealed(type);
         }
 
+        private TypeCompareState isNullableType(CORINFO_CLASS_STRUCT_* cls)
+        {
+            TypeDesc type = HandleToObject(cls);
+            Debug.Assert(!type.IsGenericParameter);
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:2947]: I don't think we need the assert. I'm only running the leg with an assert to double check. It's a nonsensical value, but I could come up with dozen(s) of other non-sensical values we could assert here. It feels like asserting it's not a generic parameter is just confusing (this should never be a generic parameter in any of the APIs we have here and then why we only assert here?).

**Review by jkotas — APPROVED** [review]
LGTM!

**Review by tannergooding — APPROVED** [review]

**Comment by jakobbotsch** [comment]
FYI @dotnet/jit-contrib ( IT-EE GUID changed)

**Comment by tannergooding** [comment]
Sorry, I had thought jit-contrib had already been tagged above but now I see the area tag ended up being `CompilerServices` instead.

**Comment by LoopedBard3** [comment]
Another potentially related regression issue @MihaZupan 
Windows x64: https://github.com/dotnet/perf-autofiling-issues/issues/33044 (Only the IndexOfAny test)
