### PR TITLE
JIT: Model JIT helper exceptions correctly in VN

### LINKED ISSUE #101028: JIT: CSE removes throwing modulo computation on x86
```csharp
// Generated by Fuzzlyn v1.6 on 2024-04-14 16:27:20
// Run on X86 Windows
// Seed: 10804341095091511908
// Reduced from 201.8 KiB to 1.0 KiB in 00:03:25
// Debug: Throws 'System.OverflowException'
// Release: Runs successfully
using System.Runtime.CompilerServices;

public class Program
{
    public static int s_1;
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[]{System.Activator.CreateInstance(runtimeTy)});
    }

    public static void MainInner(IRuntime rt)
    {
        s_1 ^= (0 >> (short)(-9223372036854775808L % (-1 | s_1)));
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC(): base(true)
    {
    }
}
```

Relevant snippet from jitdump:
```scala
N028 ( 76, 59)              [000028] nACXG------                         ▌  STOREIND  int    $101
N005 ( 17, 13)              [000027] --CXG--N---                         ├──▌  ADD       byref  $143
N003 ( 16, 12) CSE #01 (def)[000025] H-CXG------                         │  ├──▌  CALL help byref  CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE_DYNAMICCLASS $141
N001 (  1,  4)              [000023] ----------- arg0 in ecx             │  │  ├──▌  CNS_INT   int    0x8AFC8A0 $41
N002 (  1,  1)              [000024] ----------- arg1 in edx             │  │  └──▌  CNS_INT   int    0 $42
N004 (  1,  1)              [000026] -----------                         │  └──▌  CNS_INT   int    4 Fseq[s_1] $43
N027 ( 56, 43) CSE #02 (use)[000022] -ACXG------                         └──▌  XOR       int    <l:$1c2, c:$1c1>
N014 ( 20, 16)              [000033] -ACXG------                            ├──▌  COMMA     int    <l:$1c2, c:$1c1>
N012 ( 19, 15) CSE #02 (def)[000031] DACXG------                            │  ├──▌  STORE_LCL_VAR int    V01 cse0         d:1 $VN.Void
N011 ( 19, 15)              [000005] n-CXG------                            │  │  └──▌  IND       int    <l:$1c2, c:$1c1>
N010 ( 17, 13)              [000004] --CXG--N---                            │  │     └──▌  ADD       byref  $143
N008 ( 16, 12) CSE #01 (use)[000002] H-CXG------                            │  │        ├──▌  CALL help byref  CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE_DYNAMICCLASS $141
N006 (  1,  4)              [000000] ----------- arg0 in ecx                │  │        │  ├──▌  CNS_INT   int    0x8AFC8A0 $41
N007 (  1,  1)              [000001] ----------- arg1 in edx                │  │        │  └──▌  CNS_INT   int    0 $42
N009 (  1,  1)              [000003] -----------                            │  │        └──▌  CNS_INT   int    4 Fseq[s_1] $43
N013 (  1,  1)              [000032] -----------                            │  └──▌  LCL_VAR   int    V01 cse0         u:1 <l:$1c2, c:$1c1>
N026 ( 35, 26)              [000021] --CXG---R--                            └──▌  RSH       int    $1cb
N025 (  1,  1)              [000006] -----------                               ├──▌  CNS_INT   int    0 $42
N024 ( 30, 24)              [000020] --CXG------                               └──▌  AND       int    $1ca
N022 ( 28, 22)              [000018] --CXG------                                  ├──▌  CAST      int <- short <- int $1c8
N021 ( 27, 20)              [000030] --CXG------                                  │  └──▌  CAST      int <- long $1c6
N020 ( 26, 18)              [000017] --CXG------                                  │     └──▌  CALL help long   CORINFO_HELP_LMOD $282
N015 (  2,  8)              [000007] ----------- arg0 on STK                      │        ├──▌  CNS_LNG   long   0x8000000000000000 $240
N019 (  4,  5)              [000016] ----G------ arg1 on STK                      │        └──▌  CAST      long <- int $280
N018 (  3,  3)              [000015] ----G------                                  │           └──▌  OR        int    $1c4
N016 (  1,  1)              [000034] -----------                                  │              ├──▌  LCL_VAR   int    V01 cse0         u:1 <l:$1c0, c:$200>
N017 (  1,  1)              [000008] -----------                                  │              └──▌  CNS_INT   int    -1 $40
N023 (  1,  1)              [000019] -----------                                  └──▌  CNS_INT   int    31 $47


Working on the replacement of the CSE #02 use at [000022] in BB01

This CSE use has side effects and/or nested CSE defs. The sideEffectList:
N012 ( 19, 15) CSE #02 (def)[000031] DACXG------                         ▌  STORE_LCL_VAR int    V01 cse0         d:1 $VN.Void
N011 ( 19, 15)              [000005] n-CXG------                         └──▌  IND       int    <l:$1c2, c:$1c1>
N010 ( 17, 13)              [000004] --CXG--N---                            └──▌  ADD       byref  $143
N008 ( 16, 12) CSE #01 (use)[000002] H-CXG------                               ├──▌  CALL help byref  CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE_DYNAMICCLASS $141
N006 (  1,  4)              [000000] ----------- arg0 in ecx                   │  ├──▌  CNS_INT   int    0x8AFC8A0 $41
N007 (  1,  1)              [000001] ----------- arg1 in edx                   │  └──▌  CNS_INT   int    0 $42
N009 (  1,  1)              [000003] -----------                               └──▌  CNS_INT   int    4 Fseq[s_1] $43

ReMorphing args for 25.CALL:
Args for [000025].CALL after fgMorphArgs:
CallArg[[000023].CNS_INT int (By value), 1 reg: ecx, byteAlignment=4, isLate, processed]
CallArg[[000024].CNS_INT int (By value), 1 reg: edx, byteAlignment=4, isLate, processed]
OutgoingArgsStackSize is 0

ReMorphing args for 2.CALL:
Args for [000002].CALL after fgMorphArgs:
CallArg[[000000].CNS_INT int (By value), 1 reg: ecx, byteAlignment=4, isLate, processed]
CallArg[[000001].CNS_INT int (By value), 1 reg: edx, byteAlignment=4, isLate, processed]
OutgoingArgsStackSize is 0

optValnumCSE morphed tree:
N015 ( 40, 32)              [000028] nACXG------                         ▌  STOREIND  int    $101
N005 ( 17, 13)              [000027] --CXG--N---                         ├──▌  ADD       byref  $143
N003 ( 16, 12) CSE #01 (def)[000025] H-CXG------                         │  ├──▌  CALL help byref  CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE_DYNAMICCLASS $141
N001 (  1,  4)              [000023] ----------- arg0 in ecx             │  │  ├──▌  CNS_INT   int    0x8AFC8A0 $41
N002 (  1,  1)              [000024] ----------- arg1 in edx             │  │  └──▌  CNS_INT   int    0 $42
N004 (  1,  1)              [000026] -----------                         │  └──▌  CNS_INT   int    4 Fseq[s_1] $43
N014 ( 20, 16)              [000036] -ACXG------                         └──▌  COMMA     int    <l:$1c0, c:$200>
N012 ( 19, 15) CSE #02 (def)[000031] DACXG------                            ├──▌  STORE_LCL_VAR int    V01 cse0         d:1 $VN.Void
N011 ( 19, 15)              [000005] n-CXG------                            │  └──▌  IND       int    <l:$1c2, c:$1c1>
N010 ( 17, 13)              [000004] --CXG--N---                            │     └──▌  ADD       byref  $143
N008 ( 16, 12) CSE #01 (use)[000002] H-CXG------                            │        ├──▌  CALL help byref  CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE_DYNAMICCLASS $141
N006 (  1,  4)              [000000] ----------- arg0 in ecx                │        │  ├──▌  CNS_INT   int    0x8AFC8A0 $41
N007 (  1,  1)              [000001] ----------- arg1 in edx                │        │  └──▌  CNS_INT   int    0 $42
N009 (  1,  1)              [000003] -----------                            │        └──▌  CNS_INT   int    4 Fseq[s_1] $43
N013 (  1,  1)              [000035] -----------                            └──▌  LCL_VAR   int    V01 cse0         u:1 <l:$1c0, c:$200>
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
The JIT currently models all exceptions thrown by helpers with a
singleton VN. This can cause CSE to remove exception side effects
incorrectly.

This change starts modelling exceptions thrown by the following helpers
accurately:
- The R2R cast helper
- Division helpers
- Static constructor base helpers

Remaining JIT helpers are modelled conservatively, with an opaque VN in
the exception part.

Contributes to #63559
Fix #101028

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @SingleAccretion @EgorBo 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=643933&view=ms.vss-build-web.run-extensions-tab). Some improvements in Instrumented-Tier1 because we no longer try CSE'ing a common pattern around profiling helpers. Those CSE candidates typically look like the following:
```scala
N006 ( 18, 19) CSE #03 (def)[000041] --CXG------                            │     └──▌  COMMA     ref    $1c2
N004 ( 17, 18)              [000039] --CXG------                            │        ├──▌  CALL help void   CORINFO_HELP_CLASSPROFILE32 $1c1
N002 (  1,  1)              [000037] ----------- arg0 in rcx                │        │  ├──▌  LCL_VAR   ref    V01 arg1         u:1 $81
N003 (  2, 10)              [000038] ----------- arg1 in rdx                │        │  └──▌  CNS_INT   long   0x7ff8b74c8a58 $140
N005 (  1,  1)              [000040] -----------                            │        └──▌  LCL_VAR   ref    V01 arg1         u:1 $81
...
N014 ( 18, 19) CSE #03 (use)[000080] --CXG------                         │     │     └──▌  COMMA     ref    $1c2
N012 ( 17, 18)              [000078] --CXG------                         │     │        ├──▌  CALL help void   CORINFO_HELP_CLASSPROFILE32 $1c1
N010 (  1,  1)              [000076] ----------- arg0 in rcx             │     │        │  ├──▌  LCL_VAR   ref    V01 arg1         u:1 $81
N011 (  2, 10)              [000077] ----------- arg1 in rdx             │     │        │  └──▌  CNS_INT   long   0x7ff8b74c8f90 $142
N013 (  1,  1)              [000079] -----------                         │     │        └──▌  LCL_VAR   ref    V01 arg1         u:1 (last use) $81
```
and before this change we ended up CSE'ing them like this, creating another local:
```scala
N009 ( 25, 24)              [000122] -ACXG------                            │     └──▌  COMMA     ref    $1c2
N007 ( 22, 22) CSE #03 (def)[000120] DACXG------                            │        ├──▌  STORE_LCL_VAR ref    V20 cse0         d:1 $VN.Void
N006 ( 18, 19)              [000041] --CXG------                            │        │  └──▌  COMMA     ref    $1c2
N004 ( 17, 18)              [000039] --CXG------                            │        │     ├──▌  CALL help void   CORINFO_HELP_CLASSPROFILE32 $1c1
N002 (  1,  1)              [000037] ----------- arg0 in rcx                │        │     │  ├──▌  LCL_VAR   ref    V01 arg1         u:1 $81
N003 (  2, 10)              [000038] ----------- arg1 in rdx                │        │     │  └──▌  CNS_INT   long   0x7ff8b74c8a58 $140
N005 (  1,  1)              [000040] -----------                            │        │     └──▌  LCL_VAR   ref    V01 arg1         u:1 $81
N008 (  3,  2)              [000121] -----------                            │        └──▌  LCL_VAR   ref    V20 cse0         u:1 $1c2
...
N014 ( 20, 20)              [000124] --CXG------                         │     │     └──▌  COMMA     ref    $1c2
N012 ( 17, 18)              [000078] --CXG------                         │     │        ├──▌  CALL help void   CORINFO_HELP_CLASSPROFILE32 $1c1
N010 (  1,  1)              [000076] ----------- arg0 in rcx             │     │        │  ├──▌  LCL_VAR   ref    V01 arg1         u:1 $81
N011 (  2, 10)              [000077] ----------- arg1 in rdx             │     │        │  └──▌  CNS_INT   long   0x7ff8b74c8f90 $142
N013 (  3,  2)              [000123] -----------                         │     │        └──▌  LCL_VAR   ref    V20 cse0         u:1 $81
```

After this change they are blocked because they don't have the same exception sets. The profile helpers probably don't have the right properties modelled in the first place to even be considering exceptions.

File: src/coreclr/jit/valuenum.cpp [hunk 1]
```diff
@@ -13169,10 +13169,92 @@ bool Compiler::fgValueNumberHelperCall(GenTreeCall* call)
...
+            case CORINFO_HELP_GETSHARED_GCTHREADSTATIC_BASE_DYNAMICCLASS:
+            case CORINFO_HELP_GETSHARED_NONGCTHREADSTATIC_BASE_DYNAMICCLASS:
+                // These all take (Module*, class ID) as parameters.
+
+                vnpExc = vnStore->VNPExcSetSingleton(
+                    vnStore->VNPairForFunc(TYP_REF, VNF_ClassInitExc,
+                                           vnStore->VNPNormalPair(
+                                               call->gtArgs.GetUserArgByIndex(0)->GetNode()->gtVNPair),
+                                           vnStore->VNPNormalPair(
+                                               call->gtArgs.GetUserArgByIndex(1)->GetNode()->gtVNPair)));
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:13200]: Why is it correct to give each cctor helper for the same class the same exception set, when the set of exceptions that can be thrown by a cctor (or, more precisely, the set of circumstances under which `TypeInitializationException` can be thrown) is dependent on ambient memory state as well?

(I don't necessarily think it is incorrect, since cctors are only triggered once, but am looking for the format argument of why that is, which would ideally also be included as a code comment.)

File: src/coreclr/jit/valuenum.cpp [hunk 2]
```diff
@@ -13169,10 +13169,92 @@ bool Compiler::fgValueNumberHelperCall(GenTreeCall* call)
...
+                break;
+
             default:
                 // Setup vnpExc with the information that multiple different exceptions
-                // could be generated by this helper
-                vnpExc = vnStore->VNPExcSetSingleton(vnStore->VNPairForFunc(TYP_REF, VNF_HelperMultipleExc));
+                // could be generated by this helper, in an opaque way
+                vnpExc =
+                    vnStore->VNPExcSetSingleton(vnStore->VNPairForFunc(TYP_REF, VNF_HelperOpaqueExc,
+                                                                       vnStore->VNPairForExpr(compCurBB, TYP_I_IMPL)));
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:13256]: Can we use helper call properties to assert a specific set of helpers that are handled conservatively, s. t. adding new helpers which shouldn't be will be caught quickly, e. g.:

```
case CORINFO_HELP_XYZ:
case ...
case CORINFO_HELP_ZXY:
    // Handled conservatively.
    ...
    break;

default:
    assert(!call->OperMayThrow(this));
    break;
```
?

File: src/coreclr/jit/valuenumfuncs.h [hunk 3]
```diff
@@ -65,9 +65,14 @@ ValueNumFuncDef(ConvOverflowExc, 2, false, false, false, false)    // Cast conve
...
 ValueNumFuncDef(NewArrOverflowExc, 1, false, false, false, false)  // Raises Integer overflow when Arg 0 is negative
-ValueNumFuncDef(HelperMultipleExc, 0, false, false, false, false)  // Represents one or more different exceptions that could be thrown by a Jit Helper method
+ValueNumFuncDef(ClassInitExc, 2, false, false, false, false)       // Represents exceptions thrown by static constructor for class. Args: 0: VN of module, 1: VN of class ID
+ValueNumFuncDef(R2RClassInitExc, 1, false, false, false, false)    // Represents exceptions thrown by static constructor for class. Args: 0: VN of R2R entry point
+ValueNumFuncDef(ClassInitGenericExc, 2, false, false, false, false)// Represents exceptions thrown by static constructor for generic class. Args: 0: VN of class handle
+ValueNumFuncDef(HelperOpaqueExc, 1, false, false, false, false)    // Represents opaque exceptions could be thrown by a JIT helper.
+                                                                   // Args: 0: Input to helper that uniquely determines exceptions thrown.
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenumfuncs.h:75]: This is, strictly speaking, more expensive than it needs to be. One can devise a scheme where this would be close to zero-cost, by creating a new chunk kind (`CEA_Unique`) for this VN that would not need to be allocated physically - since there are no arguments (`VNForExpr` VNs that don't need to record loop args could be optimized to use the same chunk kind).

**Review by SingleAccretion — COMMENTED** [review]
What is the memory consumption impact of this change?

Nit: this shouldn't close #63559, since that is also about numbering user calls 'precisely', s. t. this checking can be enabled:

https://github.com/dotnet/runtime/blob/f8afaea32baa10207e6d4299b1b13b46b16af556/src/coreclr/jit/valuenum.cpp#L13778-L13782

File: src/coreclr/jit/valuenumfuncs.h (hunk 3 above)
Comment (jakobbotsch) [reply src/coreclr/jit/valuenumfuncs.h:75]: I did think about adding the ability to allocate multiple unique VNs with `HelperOpaqueExc` VNF, and making this nullary, but it seemed like a premature optimization to me. Let's see what the memory diff says.

File: src/coreclr/jit/valuenum.cpp (hunk 2 above)
Comment (SingleAccretion) [reply src/coreclr/jit/valuenum.cpp:13256]: I suppose it's still possible to do this by listing out the rest of the helpers explicitly:

```
case CORINFO_HELP_XYZ:
case ...
case CORINFO_HELP_ZXY:
    // Handled conservatively.
    break;

default:
    assert(!"Unhandled throwing helper in fgValueNumberHelperCall");
    break;
```
It is a bit suboptimal though, since unknown helpers wouldn't get conservative handling by default. Up to you.

File: src/coreclr/jit/valuenum.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/valuenum.cpp:13200]: I suppose from the perspective of VN it's hard to model something like this completely accurately. The exception set of a second call to one of these helpers is empty if it is dominated by the first call, but as you say, depends on the heap if the paths are otherwise disjoint.
So there is some aspect of "making CSE able to do something with this" here. I'll add some comments as you suggest.

**Comment by jakobbotsch** [comment]
> What is the memory consumption impact of this change?

Diff of memstats over win-x64 `libraries_tests.run`: https://www.diffchecker.com/ddMRxfAN/
Around 0.7% more VN memory allocated, 0.04% more memory overall.

File: src/coreclr/jit/valuenum.cpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp:13265]: E.g. `CORINFO_HELP_ARRADDR_ST` may throw IndexOutOfRange 🙂

**Review by EgorBo — APPROVED** [review]
