### PR TITLE
Fix lcl fld addr.

### LINKED ISSUE #39403: Optimizations introduce null reference exception on latest preview 8 daily build
With tiered compilation off, optimizations enabled, targeting net5.0 on win10 x64 under latest daily build (f37dd6fc8595e130909dcb3085a56342d04aa20c, 5.0.0-preview.8.20361.2), calling `TestRepro` throws a null reference exception:
```
        struct Container
        {
            public Vector<int> Vector;
            public int Integer;
        }

        static Vector<int> DoAThingByRef(ref Vector<int> s)
        {
            return s + Vector<int>.Zero;
        }
        [MethodImpl(MethodImplOptions.NoInlining)]
        static unsafe Vector<int> Test()
        {
            Container container = default;
            return DoAThingByRef(ref container.Vector);
        }

        public static void TestRepro()
        {
            Test();
        }
```
The resulting assembly for Test:
```
 sub         rsp,28h  
 vzeroupper  
 xor         eax,eax  
 vxorps      xmm0,xmm0,xmm0  
 vmovdqu     xmmword ptr [rsp],xmm0  
 vmovdqu     xmmword ptr [rsp+10h],xmm0  
 mov         qword ptr [rsp+20h],rax  
 vxorps      ymm0,ymm0,ymm0  
 vpaddd      ymm0,ymm0,ymmword ptr [0] 🐱‍👤
 vmovupd     ymmword ptr [rcx],ymm0  
 mov         rax,rcx  
 vzeroupper  
 add         rsp,28h  
 ret  
```
Preview 7 works as expected.

### PR DESCRIPTION
**Pull request by sandreenko**
This PR fixes https://github.com/dotnet/runtime/issues/39403 introduced by https://github.com/dotnet/runtime/pull/38316 (first two commits).

The safest solution would be to revert https://github.com/dotnet/runtime/commit/eefeb7e7b1485f48c2c3d65d119c7fa7693b0943 and https://github.com/dotnet/runtime/commit/ceec9c8fd43d5b938f5bc5ad610075aa44498b44 but it will lead to significant regressions, like 

  | Total size diff, bytes | Methods imrpoved | Methods regressed
-- | -- | -- | --
arm64 Windows crossgen | 18912 | 0 | 1156

so after advising with Carol I have decided to fix the optimization rather than disable it.

The two bad things about the issue were:
1. we did not catch it with our testing;
2. Jit was producing bad code instead of failing with an assert;

so the main goal in the fix was to add as many relevant asserts as possible. 

I recommend reviewing by commits.

Changes:
https://github.com/dotnet/runtime/pull/39424/commits/aaf2e99c566d8beff28851f330bb4dfe09f6e1a6: Add a repro test.

https://github.com/dotnet/runtime/pull/39424/commits/69d33fb52d427019cd89243f9dd0118839446b31: Small ref.

Combine long chains of `addr->OperGet() == GT_* ||` with `GT_LCL_VAR_ADDR` using `OperIs` to simplify future changes.

https://github.com/dotnet/runtime/pull/39424/commits/f8d8cacec293d41b63e9c2f9588fb6efd69fba2e: Add an assert that would fire in the repro test.

`emitter::emitHandleMemOp` has special logic for contained `memBase` but the last else does not
expect a contained node. A contained node doesn't produce a register so it is not correct to use the result
of `GetRegNum()` from a contained node as a valid register.
However, adding an assert to `GetRegNum()` that `!this->isContained` is a bigger task that is out of this PR.

https://github.com/dotnet/runtime/pull/39424/commits/578d0ed1194fbfa2732215c8f8d416f18071a2e5: Assert that `LCL_FLD_ADDR` is not contained in `genPutArgStk(Split)`

We have contained `LCL_VAR_ADDR` support there but make sure that contained `LCL_FLD_ADDR` can't reach it.

https://github.com/dotnet/runtime/pull/39424/commits/cd9d0b3eff500c97731291749f4304f472d31181: Contain `GT_LCL_FLD_ADDR` under HW_INTRINSIC.

This is an additional optimization that makes future changes simpler.

https://github.com/dotnet/runtime/pull/39424/commits/7d68d3f25289c3ad126f3b39ca82ba0119ba907f: Add contained checks.

In all these places we expect `LCL_VAR_ADDR` to be contained.
If we had gotten a `LCL_VAR_ADDR` that is not contained we would have instantiated `LCL_VAR_ADDR` twice:
in the register and the parent instruction.
The register value would have been unused.

https://github.com/dotnet/runtime/pull/39424/commits/1865d2943f15d3b00523597f519b546f4dea936f: Support `FLD_ADDR` where `LCL_ADDR` is supported.

However, fire an assert if we think that this path is unreachable for now.

https://github.com/dotnet/runtime/pull/39424/commits/69ecffc6a1c0d67b59f3c87fb914ef5cd48efa40: Delete asserts in the reachable blocks.

We have coverage for this asserts in the following tests:
hwintrinsic 478: Ssse3_ro
instr 11645: Runtime_39403
instr 1028 : Aes_ro
hwintrinsic 716: pmi of Microsoft.Diagnostics.Tracing.TraceEvent

From HWIntrinsic support we have some improvements (x64 Pmi):
```
Total bytes of diff: -2267 (-0.00% of base)
    diff is an improvement.
Top file improvements (bytes):
        -604 : JIT\HardwareIntrinsics\X86\Sse2\Sse2_r\Sse2_r.dasm (-0.02% of base)
        -500 : JIT\HardwareIntrinsics\X86\Avx2\Avx2_r\Avx2_r.dasm (-0.01% of base)
        -364 : JIT\HardwareIntrinsics\X86\Avx\Avx_r\Avx_r.dasm (-0.02% of base)
        -300 : JIT\HardwareIntrinsics\X86\Sse41\Sse41_r\Sse41_r.dasm (-0.02% of base)
        -208 : JIT\HardwareIntrinsics\X86\Sse\Sse_r\Sse_r.dasm (-0.02% of base)
         -80 : JIT\HardwareIntrinsics\X86\Fma_Vector128\Fma_r\Fma_r.dasm (-0.02% of base)
         -64 : JIT\HardwareIntrinsics\X86\Ssse3\Ssse3_r\Ssse3_r.dasm (-0.01% of base)
         -48 : JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_r\Fma_r.dasm (-0.02% of base)
         -32 : JIT\HardwareIntrinsics\X86\Sse41_Overloaded\Sse41_Overloaded_r\Sse41_Overloaded_r.dasm (-0.03% of base)
         -24 : JIT\HardwareIntrinsics\X86\Aes\Aes_r\Aes_r.dasm (-0.03% of base)
         -24 : JIT\HardwareIntrinsics\X86\Sse3\Sse3_r\Sse3_r.dasm (-0.02% of base)
          -8 : JIT\HardwareIntrinsics\X86\Avx_Vector128\Avx_r\Avx_r.dasm (-0.01% of base)
          -4 : JIT\HardwareIntrinsics\X86\Avx2_Vector128\Avx2_r\Avx2_r.dasm (-0.00% of base)
          -4 : JIT\HardwareIntrinsics\X86\Sse42\Sse42_r\Sse42_r.dasm (-0.02% of base)
          -3 : JIT\Regression\JitBlue\Runtime_39403\Runtime_39403\Runtime_39403.dasm (-1.03% of base)
15 total files with Code Size differences (15 improved, 0 regressed), 3365 unchanged.
```

crossgen linuxnonjit:
```
Top file improvements (bytes):
        -662 : System.Private.CoreLib.dasm (-0.01% of base)
1 total files with Code Size differences (1 improved, 0 regressed), 261 unchanged.
Top method improvements (bytes):
        -184 (-20.54% of base) : System.Private.CoreLib.dasm - Matrix4x4:op_Multiply(Matrix4x4,Matrix4x4):Matrix4x4 (2 methods)
         -70 (-15.84% of base) : System.Private.CoreLib.dasm - Matrix4x4:Lerp(Matrix4x4,Matrix4x4,float):Matrix4x4 (2 methods)
         -70 (-23.33% of base) : System.Private.CoreLib.dasm - Matrix4x4:op_Addition(Matrix4x4,Matrix4x4):Matrix4x4 (2 methods)
         -70 (-23.33% of base) : System.Private.CoreLib.dasm - Matrix4x4:op_Subtraction(Matrix4x4,Matrix4x4):Matrix4x4 (2 methods)
         -70 (-27.34% of base) : System.Private.CoreLib.dasm - Matrix4x4:op_Equality(Matrix4x4,Matrix4x4):bool (2 methods)
         -70 (-26.72% of base) : System.Private.CoreLib.dasm - Matrix4x4:op_Inequality(Matrix4x4,Matrix4x4):bool (2 methods)
         -32 (-11.76% of base) : System.Private.CoreLib.dasm - Matrix4x4:Transpose(Matrix4x4):Matrix4x4 (2 methods)
         -32 (-10.06% of base) : System.Private.CoreLib.dasm - Matrix4x4:op_UnaryNegation(Matrix4x4):Matrix4x4 (2 methods)
         -32 (-10.06% of base) : System.Private.CoreLib.dasm - Matrix4x4:op_Multiply(Matrix4x4,float):Matrix4x4 (2 methods)
         -32 (-1.24% of base) : System.Private.CoreLib.dasm - Matrix4x4:<Invert>g__SseImpl|59_0(Matrix4x4,byref):bool (2 methods)

```

I am planning to write repro cases for the rest of `assert(!"don't expect GT_LCL_FLD_ADDR")` before I finish this PR.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @CarolEidt @dotnet/jit-contrib

**Review by AndyAyersMS — COMMENTED** [review]
Seems like the same pattern of code added to quite a number of places. Should we make this into a new helper method?

**Comment by sandreenko** [comment]
> Seems like the same pattern of code added to quite a number of places. Should we make this into a new helper method?

I like the idea. I was thinking about adding `GetLclOffs` to `LclVarCommon` returning `0` for `LCL_VAR`, 
or
```
	assert(addr->isContained());
	varNum = addr->AsLclVarCommon()->GetLclNum();
	if (addr->OperIs(GT_LCL_FLD_ADDR))
	{
		offset = addr->AsLclFld()->GetLclOffs();
	}
	else
	{
		offset = 0;
	}
```
can be extracted (but will have to use out params to pass results).
What do you think is better? The first could be used in other places as well.

I can make a try and see how it looks.

File: src/coreclr/src/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -820,6 +820,7 @@ void CodeGen::genPutArgStk(GenTreePutArgStk* treeNode)
                 }
                 else // addrNode is used
                 {
+                    assert(!addrNode->isContained());
```
Comment (CarolEidt) [inline src/coreclr/src/jit/codegenarmarch.cpp:823]: We are asserting that `addrNode` is not contained, and yet calling `genConsumeAddress` which handles a contained `LEA`. Is that so that it will handle a contained address even if we don't expect it? If so, a comment would be good. If not, it should be calling `genConsumeReg()`.

File: src/coreclr/src/jit/codegenarmarch.cpp [hunk 2]
```diff
@@ -1270,6 +1271,7 @@ void CodeGen::genPutArgSplit(GenTreePutArgSplit* treeNode)
         else // addrNode is used
         {
             assert(addrNode != nullptr);
+            assert(!addrNode->isContained());
```
Comment (CarolEidt) [inline src/coreclr/src/jit/codegenarmarch.cpp:1274]: Same comment here.

File: src/coreclr/src/jit/codegenxarch.cpp [hunk 3]
```diff
@@ -6951,9 +6951,19 @@ void CodeGen::genSSE41RoundOp(GenTreeOp* treeNode)
             switch (memBase->OperGet())
             {
                 case GT_LCL_VAR_ADDR:
+                case GT_LCL_FLD_ADDR:
                 {
+                    assert(memBase->isContained());
                     varNum = memBase->AsLclVarCommon()->GetLclNum();
-                    offset = 0;
+                    if (memBase->OperIs(GT_LCL_FLD_ADDR))
```
Comment (CarolEidt) [inline src/coreclr/src/jit/codegenxarch.cpp:6958]: A comment here would be good - i.e. that this path is unexpected and untested, but should be correct in case it is encountered in a non-checked JIT.

File: src/coreclr/src/jit/emitxarch.cpp [hunk 4]
```diff
@@ -2956,24 +2956,27 @@ void emitter::emitHandleMemOp(GenTreeIndir* indir, instrDesc* id, insFormat fmt,
...
+            amIndxReg = index->GetRegNum();
+            assert(amIndxReg != REG_NA);
         }
-        else
-        {
-            id->idAddr()->iiaAddrMode.amIndxReg = REG_NA;
-        }
-        id->idAddr()->iiaAddrMode.amScale = emitEncodeScale(indir->Scale());
+
+        assert((amBaseReg != REG_NA) || (amIndxReg != REG_NA)); // At least one should be set.
```
Comment (CarolEidt) [inline src/coreclr/src/jit/emitxarch.cpp:2976]: I believe that it could potentially be the case that we have no base or index, but in that case we should have a handle for the offset.

**Review by CarolEidt — COMMENTED** [review]
Overall looks good, with a couple of questions & suggestions. I also like Andy's suggestion to extract the repeated code, if possible.

File: src/coreclr/src/jit/codegenxarch.cpp (hunk 3 above)
Comment (sandreenko) [reply src/coreclr/src/jit/codegenxarch.cpp:6958]: Thanks, I am planning to write a test that hits that path, if I won't be able to construct it I will add a comment.

File: src/coreclr/src/jit/emitxarch.cpp (hunk 4 above)
Comment (sandreenko) [reply src/coreclr/src/jit/emitxarch.cpp:2976]: I will add a check `|| (indir->Offset() != 0)`, I think it is unreachable (based on my analysis of `GenTreeIndir::Offset()`) but it is just safer for now.

File: src/coreclr/src/jit/codegenxarch.cpp (hunk 3 above)
Comment (sandreenko) [reply src/coreclr/src/jit/codegenxarch.cpp:6958]: Added the repro cases and deleted the asserts.

File: src/tests/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424.il [hunk 5]
```diff
@@ -0,0 +1,196 @@
...
+  {
+    // Code size       30 (0x1e)
+    .maxstack  2
+    .locals init (valuetype Runtime_39424/Container V_0)
+    IL_0000:  ldloca.s   V_0
+    IL_0002:  initobj    Runtime_39424/Container
+    IL_0008:  ldloca.s   V_0
+    IL_000a:  ldarg.0
+    IL_000b:  stfld      float64 Runtime_39424/Container::Double
+    IL_0010:  ldloca.s   V_0
```
Comment (sandreenko) [inline src/tests/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424.il:37]:
```
ldloca.s   V_0 
ldflda float64 Runtime_39424/Container::Double
volatile. ldind.r8
```
were generating what we needed.  I have disabled CSE, added more than 4 fields to avoid struct promotion and marked indir as volatile to avoid the optimizations that were hiding the issue.

File: src/coreclr/src/jit/codegenarmarch.cpp (hunk 1 above)
Comment (sandreenko) [reply src/coreclr/src/jit/codegenarmarch.cpp:826]: Added a comment about that.

**Comment by sandreenko** [comment]
The PR has been updated and is ready for the next round of review.

**Comment by sandreenko** [comment]
ping @dotnet/jit-contrib

**Review by AndyAyersMS — APPROVED** [review]
Changes look good, though I don't know how to be confident that all the places that needed to be changed have been changed.

**Comment by sandreenko** [comment]
> Changes look good, though I don't know how to be confident that all the places that needed to be changed have been changed.

I estimate the risk as low. We had had support for contained `GT_CLS_VAR_ADDR` on all platforms and for contained `GT_LCL_VAR_ADDR` on x64, so I have checked all places where we were referencing one of them and add support for the new nodes. Then I made sure that these new code paths are visited by adding a repro test for each of them.

I think the new asserts in `emitHandleMemOp` would help to catch similar issues in the future on x64/x86. Arm arch logic is simpler and because of that it needs less changes.
