### PR TITLE
Fix unhandled exception in tiered compilation thread

### LINKED ISSUE #116676: UnsafeAccessorType targeting non-existing type crashing on Linux
Repro:

`dotnet run -c release` on Linux:
```csharp
using System.Runtime.CompilerServices;

for (int i = 0; ; i++)
{
    Console.WriteLine(i);
    Work(false);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void Work(bool f)
{
    if (f)
        DoesNotExist(null);
}

[UnsafeAccessor(UnsafeAccessorKind.Method)]
extern static void DoesNotExist([UnsafeAccessorType("DoesNotExist")] object a);
```

Actual result: Crash with no error message after several thousands of iterations

Expected result: Runs indefinitely

### PR DESCRIPTION
**Pull request by janvorli**
The detection the unhandled exception is not working in the case of the tiered compilation thread, because there is no indication that the exception is going to be caught in the `CEEInfo::runWithErrorTrap`. So the EH assumes the exception is going to be unhandled and exits the process.
The unhandled exception message was not seen in the repro case of the issue likely because the tiered compilation thread console output didn't get flushed. When running under a debugger and stepping over the `InternalUnhandledExceptionFilter_Worker`, it was actually printed out.

The fix is to add `DebuggerU2MCatchHandlerFrame` to the `CEEInfo::runWithErrorTrap`. That allows the EH to see that the exception will be caught there and let it flow through the `CallDescrWorker` to reach that trap.

I have also taken this opportunity and renamed the confusing `invalidRevPInvoke` local variable.

Closes #116676

### CODE REVIEW

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -10585,6 +10585,8 @@ bool CEEInfo::runWithErrorTrap(void (*function)(void*), void* param)
 
     bool success = true;
 
+    DebuggerU2MCatchHandlerFrame catchFrame(true /* catchesAllExceptions */);
+
 #if !defined(TARGET_UNIX)
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]: Is this `TARGET_UNIX` ifdef still applicable?

File: src/coreclr/vm/jitinterface.cpp [hunk 2]
```diff
@@ -10585,6 +10585,8 @@ bool CEEInfo::runWithErrorTrap(void (*function)(void*), void* param)
...
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]: Do we need to Pop the frame manually before the method exits?

**Comment by jkotas** [comment]
Should we add a regression test for this?

File: src/coreclr/vm/jitinterface.cpp (hunk 2 above)
Comment (janvorli) [reply src/coreclr/vm/jitinterface.cpp]: Sigh, yes.

File: src/coreclr/vm/jitinterface.cpp (hunk 1 above)
Comment (janvorli) [reply src/coreclr/vm/jitinterface.cpp]: It seems the Windows way works on Unix too, so I'll keep just that. This split is pre-.NET 1.0.

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp]: Can it be the other way around - keep the simpler Unix version? The fewer `PAL_TRY`s we have, the better.

File: src/coreclr/vm/exceptionhandling.cpp [hunk 3]
```diff
@@ -3958,18 +3958,18 @@ extern "C" CLR_BOOL QCALLTYPE SfiNext(StackFrameIterator* pThis, uint* uExCollid
...
         codeInfo.DecodeGCHdrInfo(&hdrInfoBody);
-        invalidRevPInvoke = hdrInfoBody->revPInvokeOffset != INVALID_REV_PINVOKE_OFFSET;
+        isPropagatingToNativeCode = hdrInfoBody->revPInvokeOffset != INVALID_REV_PINVOKE_OFFSET;
 #endif // USE_GC_INFO_DECODER
         bool isPropagatingToExternalNativeCode = false;
 
-        EH_LOG((LL_INFO100, "SfiNext: reached native frame at IP=%p, SP=%p, invalidRevPInvoke=%d\n",
-            GetIP(pThis->m_crawl.GetRegisterSet()->pCurrentContext), GetSP(pThis->m_crawl.GetRegisterSet()->pCurrentContext), invalidRevPInvoke));
+        EH_LOG((LL_INFO100, "SfiNext: reached native frame at IP=%p, SP=%p, isPropagatingToNativeCode=%d\n",
+            GetIP(pThis->m_crawl.GetRegisterSet()->pCurrentContext), GetSP(pThis->m_crawl.GetRegisterSet()->pCurrentContext), isPropagatingToNativeCode));
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/exceptionhandling.cpp:3970]:
```suggestion
        EH_LOG((LL_INFO100, "SfiNext: reached native frame at IP=%p, SP=%p, isPropagatingToNativeCode=%s\n",
            GetIP(pThis->m_crawl.GetRegisterSet()->pCurrentContext), GetSP(pThis->m_crawl.GetRegisterSet()->pCurrentContext), (isPropagatingToNativeCode ? "true" : "false")));
```

File: src/coreclr/vm/jitinterface.cpp (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp]: Is there a reason the `DebuggerU2MCatchHandlerFrame`'s dtor doesn't do the `Pop()`?

Comment (janvorli) [reply src/coreclr/vm/jitinterface.cpp]: In general, the explicit frames don't pop themselves in the destructor. I have actually added that for Unix long time ago as it was needed for some Unix specific cases of unwinding exception through native frames (https://github.com/dotnet/coreclr/pull/3250), but on Windows, we've stayed on the plan of explicit popping. And it is possible that with the new EH, it is not needed anymore.
Here are some reasons I was able to figure out:
* Some frames are created in functions that use SEH and that's incompatible with instances of objects with destructors in those functions. The `DebuggerU2MCatchHandlerFrame` is actually such a frame.
* Some frames are created by asm helpers, so there is no destructor being called for those. Having the pops explicit makes all frames to handle pops in a consistent manner (explicitly).

File: src/tests/Regressions/coreclr/GitHub_116676/test116676.cs [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+        if (f)
+            DoesNotExist(null);
+    }
+
+    [Fact]
+    public static void TestEntryPoint()
+    {
+        for (int i = 0; i < 1_000_000; i++)
+        {
+            Console.WriteLine(i);
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_116676/test116676.cs]: This will produce megabytes of output that will get copied around, etc. Can we do something less visible, like `Thread.Sleep(10)` and change the for-loop to go till like 200? We should only need to hit the loop about `CallCountThreshold` times (30) to trigger the background tiered compilation.

Comment (janvorli) [reply src/tests/Regressions/coreclr/GitHub_116676/test116676.cs]: It usually triggers on hundreds of thousands of iterations for me, so even a Sleep(1) was too long. Let me try if a longer sleep and less iterations would give the tiered compilation enough time to crash.

Comment (janvorli) [reply src/tests/Regressions/coreclr/GitHub_116676/test116676.cs]: I've modified it to use the Sleep(10) and less loops. It reproduces the problem without the fix reliably.

File: src/coreclr/vm/jitinterface.cpp [hunk 5]
```diff
@@ -10533,26 +10533,6 @@ uint32_t CEEInfo::getJitFlags(CORJIT_FLAGS* jitFlags, uint32_t sizeInBytes)
...
-    EXCEPTION_POINTERS m_exceptionPointers;
-};
-
-static LONG RunWithErrorTrapFilter(struct _EXCEPTION_POINTERS* exceptionPointers, void* theParam)
-{
-    WRAPPER_NO_CONTRACT;
-
-    auto* param = reinterpret_cast<RunWithErrorTrapFilterParam*>(theParam);
-    param->m_exceptionPointers = *exceptionPointers;
-    return EEFilterException(exceptionPointers, nullptr);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:10552]: This is the only call of `EEFilterException`. Delete `EEFilterException` too?

File: src/coreclr/vm/jitinterface.cpp [hunk 6]
```diff
@@ -10585,31 +10565,12 @@ bool CEEInfo::runWithErrorTrap(void (*function)(void*), void* param)
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:10482]: The comment above is not applicable. `EEFilterException` is not really used anymore and this method does not use SEH anymore. Can this have a regular JIT/EE interface contract?

File: src/tests/Regressions/coreclr/GitHub_116676/test116676.cs (hunk 4 above)
Comment (MichalPetryka) [reply src/tests/Regressions/coreclr/GitHub_116676/test116676.cs]: Would it make sense to use the env var for aggressive tiering here?

Comment (janvorli) [reply src/tests/Regressions/coreclr/GitHub_116676/test116676.cs]: I don't think it is needed, the test now repros the problem reliably (with the fix from this PR removed)

File: src/coreclr/vm/jitinterface.cpp [hunk 7]
```diff
@@ -10573,43 +10469,25 @@ bool CEEInfo::runWithSPMIErrorTrap(void (*function)(void*), void* param)
 
 bool CEEInfo::runWithErrorTrap(void (*function)(void*), void* param)
 {
-    // No dynamic contract here because SEH is used
-    STATIC_CONTRACT_THROWS;
-    STATIC_CONTRACT_GC_TRIGGERS;
-    STATIC_CONTRACT_MODE_PREEMPTIVE;
+    CONTRACTL {
+        THROWS;
+        GC_NOTRIGGER;
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp]:
```suggestion
        GC_TRIGGERS;
```

**Review by jkotas — APPROVED** [review]
Thanks

**Review by AaronRobinsonMSFT — APPROVED** [review]
