### PR TITLE
[mono] Use SROA-friendly struct type declarations

### LINKED ISSUE #58062: Mono GC crash in CI
```
      =================================================================
      Managed Stacktrace:
      =================================================================
        at <unknown> <0xffffffff>
        at System.Object:__icall_wrapper_mono_gc_alloc_vector <0x0008a>
        at System.Object:AllocVector <0x000f2>
        at System.Collections.Generic.Dictionary`2:Initialize <0x0006e>
        at System.Collections.Generic.Dictionary`2:.ctor <0x0003f>
        at System.Collections.Generic.Dictionary`2:.ctor <0x00021>
        at Microsoft.Cci.MetadataHeapsBuilder:.ctor <0x000ed>
        at Microsoft.Cci.FullMetadataWriter:Create <0x00077>
        at Microsoft.Cci.PeWriter:WritePeToStream <0x00123>
        at Microsoft.CodeAnalysis.Compilation:SerializeToPeStream <0x0061b>
        at Microsoft.CodeAnalysis.Compilation:Emit <0x00716>
        at Microsoft.CodeAnalysis.Compilation:Emit <0x001a7>
        at Microsoft.CodeAnalysis.Compilation:Emit <0x000bf>
        at CscBench:CompileBench <0x0028b>
        at CscBench:Main <0x00025>
        at <Module>:runtime_invoke_int <0x0005f>
      =================================================================
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58028-merge-0f18162b6a714630a6/JIT/1/console.71179669.log?sv=2019-07-07&se=2021-09-13T17%3A30%3A21Z&sr=c&sp=rl&sig=pNe9viQHA2TTqAOjNwkXgMqxXDAXFiw0aGviMCTofe4%3D

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57928-merge-872ab46efd2b494988/JIT/1/console.607ded22.log?sv=2019-07-07&se=2021-09-12T13%3A23%3A40Z&sr=c&sp=rl&sig=t5BAIXU9yCaDHr2wqN84Z3t79kp2WWqPzP86f4JD2RA%3D

cc @marek-safar @lambdageek @vargaz

---

The native stack traces look like this:

```
  Thread 1 (Thread 0x7fd2c37bd740 (LWP 3830)):
      #0  0x00007fd2c319632a in __waitpid (pid=3938, stat_loc=0x7ffe506b3700, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
      #1  0x00007fd2c08738f7 in dump_native_stacktrace (signal=<optimized out>, mctx=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:842
      #2  mono_dump_native_crash_info (signal=<optimized out>, mctx=0x7ffe506b4270, info=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:869
      #3  0x00007fd2c081660e in mono_handle_native_crash (signal=0x7fd2c1d0fcb3 "SIGSEGV", mctx=0x7ffe506b4270, info=0x7ffe506b4530) at /__w/1/s/src/mono/mono/mini/mini-exceptions.c:2940
      #4  0x00007fd2c0777ee1 in mono_sigsegv_signal_handler_debug (_dummy=11, _info=0x7ffe506b4530, context=0x7ffe506b4400, debug_fault_addr=0x8) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:3658
      #5  <signal handler called>
      #6  copy_object_no_checks (obj=0x7fd2bf8f1680, queue=0x7ffe506b4c60) at /__w/1/s/src/mono/mono/mini/../sgen/sgen-copy-object.h:69
      #7  0x00007fd2c07570b0 in simple_nursery_serial_copy_object_from_obj (obj_slot=0x7fd2bfcff5e8, queue=0x7ffe506b4c60) at /__w/1/s/src/mono/mono/mini/../sgen/sgen-minor-copy-object.h:238
      #8  simple_nursery_serial_scan_object (full_object=<optimized out>, desc=<optimized out>, queue=0x7ffe506b4c60) at /__w/1/s/src/mono/mono/mini/../sgen/sgen-scan-object.h:64
      #9  0x00007fd2c0758157 in simple_nursery_serial_drain_gray_stack (queue=0x7ffe506b4c60) at /__w/1/s/src/mono/mono/mini/../sgen/sgen-minor-scan-object.h:142
      #10 0x00007fd2c072db4b in sgen_drain_gray_stack (ctx=...) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:578
      #11 finish_gray_stack (generation=0, ctx=...) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:1140
      #12 0x00007fd2c072ccb9 in collect_nursery (reason=0x7fd2c1d112cf "Nursery full", is_overflow=<optimized out>) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:1932
      #13 0x00007fd2c0729003 in sgen_perform_collection_inner (requested_size=<optimized out>, generation_to_collect=<optimized out>, reason=<optimized out>, forced_serial=<optimized out>, stw=<optimized out>) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:2656
      #14 sgen_perform_collection (requested_size=3176, generation_to_collect=0, reason=0x7fd2c1d112cf "Nursery full", forced_serial=0, stw=1) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:2768
      #15 0x00007fd2c0728e03 in sgen_ensure_free_space (size=3176, generation=<optimized out>) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:2622
      #16 0x00007fd2c071cf86 in sgen_alloc_obj_nolock (vtable=0x5579c627f110, size=3176) at /__w/1/s/src/mono/mono/sgen/sgen-alloc.c:258
      #17 0x00007fd2c06ecc97 in mono_gc_alloc_vector (vtable=0x5579c627f110, size=3176, max_length=131) at /__w/1/s/src/mono/mono/metadata/sgen-mono.c:1340
      #18 0x0000000040688d6b in ?? ()
      #19 0x00007fd2bfc00438 in ?? ()
      #20 0x0000000000000083 in ?? ()
      #21 0x00005579c643b610 in ?? ()
      #22 0x0000000000000083 in ?? ()
      #23 0x00005579c627f110 in ?? ()
      #24 0x00005579c07bbd10 in ?? ()
      #25 0x00005579c627f110 in ?? ()
      #26 0x00007ffe506b4e70 in ?? ()
      #27 0x0000000000000000 in ?? ()
```

### PR DESCRIPTION
**Pull request by imhameed**
LLVM's SROA can decompose loads and stores of aggregate type into a
sequence of aggregate-element-typed loads and stores. Before this
change, Mono translated .NET-level value types into LLVM IR-level
structs containing nothing but `i8` elements.

When a value type field has reference type, and a value of this value
type is copied using a `memcpy` intrinsic or an LLVM IR load followed by
a store, LLVM will emit code that loads managed references in multiple
byte-sized fragments before reconstructing the original pointer using a
sequence of ALU ops. This causes sgen to fail to pin the referent.

This change works around this by translating value types to LLVM IR
structs with pointer-sized fields. Packed value types with non-standard
alignment will be translated into LLVM IR structs containing
alignment-sized fields.

Note that this does not completely guarantee that the code we generate
will respect sgen's requirements. No specific guarantees are provided
about the translation of non-atomic LLVM IR loads and stores to machine
code. And we'll need some alternative means (perhaps a special
`gc_copy_unaligned` runtime call or similar) to copy packed or
misaligned value types that contain managed references. For stronger
LLVM IR-level guarantees, we'll want to make use of unordered atomic
loads and stores and unordered atomic memcpy, but that work is out of
scope for this change.

Fixes #58062, but see the previous paragraph for caveats.

See:
- https://github.com/dotnet/llvm-project/blob/release/11.x/llvm/lib/Transforms/Scalar/SROA.cpp#L3371-L3388
- https://github.com/dotnet/llvm-project/blob/release/11.x/llvm/lib/Transforms/Scalar/SROA.cpp#L3327-L3340

### CODE REVIEW

File: src/mono/mono/mini/mini-llvm.c [hunk 1]
```diff
@@ -681,11 +685,17 @@ create_llvm_type_for_type (MonoLLVMModule *module, MonoClass *klass)
...
-		for (i = 0; i < size; ++i)
-			eltypes [i] = LLVMInt8Type ();
+		MonoSizeAlign size_align = get_vtype_size_align (t);
+		eltypes = g_new (LLVMTypeRef, size_align.size);
+		size = 0;
+		int bytes = 0;
+		int chunk = size_align.align < TARGET_SIZEOF_VOID_P ? size_align.align : TARGET_SIZEOF_VOID_P;
+		for (; chunk > 0; chunk = chunk >> 1) {
+			for (; (bytes + chunk) <= size_align.size; bytes += chunk) {
+				eltypes [size] = LLVMIntType (chunk * 8);
```
Comment (lambdageek) [inline src/mono/mono/mini/mini-llvm.c:695]: @imhameed, I'm curious, why do we use these element types that don't have anything to do with the actual elements of the original Mono type (and presumably we bitcast at the use sites?).  Why not use the field layout of the Mono type to create the LLVM struct?  (ie: for a mono class `int x; double y; represent it as `int32 x; int32 padding; double y` instead of I think `int32 el0; int32 el1; int32 el2; int32 el3`)?

Is it to limit the number of unique llvm types that we have to create?

**Review by vargaz — APPROVED** [review]

File: src/mono/mono/mini/mini-llvm.c (hunk 1 above)
Comment (vargaz) [reply src/mono/mono/mini/mini-llvm.c:695]: We were only doing it for simplicity i think.

Comment (imhameed) [reply src/mono/mono/mini/mini-llvm.c:695]: > @imhameed, I'm curious, why do we use these element types that don't have anything to do with the actual elements of the original Mono type (and presumably we bitcast at the use sites?). Why not use the field layout of the Mono type to create the LLVM struct? (ie: for a mono class `int x; double y;` represent it as `int32 x; int32 padding; double y` instead of I think `int32 el0; int32 el1; int32 el2; int32 el3`)?

Simplicity, mostly. The diff is small. I'd like to more accurately represent IL types in our LLVM IR in the future.

Reads and writes of individual fields are done via normal loads/stores, pointer coercion, and getelementpointer.

**Comment by SamMonoRT** [comment]
@imhameed - once all validations are complete and we are confident of the change, please indicate so, and we can start backport to release\6.0   fyi @marek-safar

**Comment by imhameed** [comment]
A before/after comparison of the problematic generated code in CscBench: [before](https://gist.github.com/imhameed/100c25b8b801ee2549f0a96acc27cbc6), [after](https://gist.github.com/imhameed/a1c933c16c381cbeb079277c32b98acf).

**Comment by imhameed** [comment]
"runtime (Mono llvmfullaot Pri0 Runtime Tests Run Linux arm64 release)" is timing out right now because the backing Helix pool (ubuntu.1804.armarch.open) currently has over 15,000 jobs queued with a wait time of over 3 hours.
