### PR TITLE
Fix corerun for assemblies with mismatched filename

### LINKED ISSUE #68455: Test failure: all ilasm/ildasm round-trip tests failing
Run: [runtime-coreclr ilasm 20220423.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1734703&view=ms.vss-test-web.build-test-results-tab&runId=46966786&resultId=105794&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked ilasmroundtrip @ Windows.10.Arm64v8.Open

- JIT\\Regression\\CLR-x86-JIT\\V2.0-Beta2\\b399444\\b399444b\\b399444b.cmd
- JIT\\Regression\\CLR-x86-JIT\\V2.0-Beta2\\b399444\\b399444a\\b399444a.cmd
- JIT\\jit64\\opt\\cse\\hugeSimpleExpr1\\hugeSimpleExpr1.cmd
- JIT\\Regression\\CLR-x86-JIT\\V2.0-Beta2\\b268908\\b268908\\b268908.cmd
- JIT\\HardwareIntrinsics\\Arm\\AdvSimd\\AdvSimd_Part8_ro\\AdvSimd_Part8_ro.cmd
- readytorun\\determinism\\crossgen2determinism\\crossgen2determinism.cmd
- JIT\\HardwareIntrinsics\\Arm\\AdvSimd\\AdvSimd_Part5_r\\AdvSimd_Part5_r.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_r\\Vector128_r.cmd
- JIT\\HardwareIntrinsics\\Arm\\AdvSimd\\AdvSimd_Part7_r\\AdvSimd_Part7_r.cmd
- JIT\\HardwareIntrinsics\\Arm\\AdvSimd\\AdvSimd_Part15_r\\AdvSimd_Part15_r.cmd
- JIT\\HardwareIntrinsics\\*

coreclr OSX arm64 Checked ilasmroundtrip @ OSX.1200.ARM64.Open

- JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part4_r/AdvSimd_Part4_r.sh
- JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part16_r/AdvSimd_Part16_r.sh
- JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part10_r/AdvSimd_Part10_r.sh
- JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part1_r/AdvSimd_Part1_r.sh
- JIT/jit64/regress/vsw/266693/test/test.sh
- JIT/jit64/gc/misc/structret4_3/structret4_3.sh
- JIT/jit64/gc/misc/ret_struct_test1/ret_struct_test1.sh
- JIT/jit64/regress/ndpw/21015/interior_pointer/interior_pointer.sh
- JIT/HardwareIntrinsics/General/Vector128/Vector128_r/Vector128_r.sh
- ...

coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- JIT\\Regression\\CLR-x86-JIT\\V2.0-Beta2\\b399444\\b399444a\\b399444a.cmd
- JIT\\Regression\\CLR-x86-JIT\\V2.0-Beta2\\b399444\\b399444b\\b399444b.cmd
- readytorun\\tests\\mainv1\\mainv1.cmd
- readytorun\\tests\\mainv2\\mainv2.cmd
- JIT\\jit64\\opt\\cse\\HugeField1\\HugeField1.cmd
- readytorun\\determinism\\crossgen2determinism\\crossgen2determinism.cmd
- ...

coreclr Linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open

- JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444a/b399444a.sh
- JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444b/b399444b.sh
- JIT/HardwareIntrinsics/X86/Pclmulqdq/Pclmulqdq_r/Pclmulqdq_r.sh
- JIT/HardwareIntrinsics/X86/Pclmulqdq/Pclmulqdq_ro/Pclmulqdq_ro.sh
- JIT/HardwareIntrinsics/General/Vector128/Vector128_r/Vector128_r.sh
- Loader/classloader/StaticVirtualMethods/GenericContext/GenericContextTestDefaultImpCallDefaultImp/GenericContextTestDefaultImpCallDefaultImp/GenericContextTestDefaultImpCallDefaultImp.sh
- ...

coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- JIT\\Regression\\CLR-x86-JIT\\V2.0-Beta2\\b399444\\b399444a\\b399444a.cmd
- JIT\\Regression\\CLR-x86-JIT\\V2.0-Beta2\\b399444\\b399444b\\b399444b.cmd
- JIT\\jit64\\opt\\cse\\hugeSimpleExpr1\\hugeSimpleExpr1.cmd
- JIT\\jit64\\opt\\cse\\HugeField1\\HugeField1.cmd
- JIT\\jit64\\opt\\cse\\HugeArray1\\HugeArray1.cmd
- ...

coreclr Linux arm64 Checked ilasmroundtrip @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444a/b399444a.sh
- JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444b/b399444b.sh
- readytorun/determinism/crossgen2determinism/crossgen2determinism.sh
- JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b268908/b268908/b268908.sh
- JIT/jit64/opt/cse/hugeSimpleExpr1/hugeSimpleExpr1.sh
- ...

coreclr Linux arm Checked ilasmroundtrip @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/jit64/opt/cse/HugeField1/HugeField1.sh
- readytorun/determinism/crossgen2determinism/crossgen2determinism.sh
- Interop/PrimitiveMarshalling/EnumMarshalling/EnumTest/EnumTest.sh
- JIT/jit64/opt/cse/arrayexpr2_r_try/arrayexpr2_r_try.sh
- Interop/PrimitiveMarshalling/Bool/BoolTest/BoolTest.sh
- Interop/PrimitiveMarshalling/UIntPtr/PInvokeUIntPtrTest/PInvokeUIntPtrTest.sh
- baseservices/threading/generics/TimerCallback/thread22/thread22.sh
- ...

coreclr OSX x64 Checked ilasmroundtrip @ OSX.1200.Amd64.Open

- JIT/jit64/opt/regress/vswhidbey/193825/193825_uro/193825_uro.sh
- JIT/jit64/opt/cse/mixedexpr1_r_loop/mixedexpr1_r_loop.sh
- JIT/jit64/opt/cprop/Dev10_884217_IL/Dev10_884217_IL.sh
- JIT/jit64/opt/cse/staticFieldExpr1_r_try/staticFieldExpr1_r_try.sh
- JIT/jit64/opt/cg/CGRecurse/CGRecurseACA_do/CGRecurseACA_do.sh
- JIT/jit64/opt/cse/hugeSimpleExpr1/hugeSimpleExpr1.sh
- JIT/jit64/opt/cse/staticFieldExpr1_d_loop_try/staticFieldExpr1_d_loop_try.sh
- baseservices/threading/generics/threadstart/GThread26/GThread26.sh
- baseservices/threading/generics/TimerCallback/thread29/thread29.sh
- baseservices/threading/generics/syncdelegate/GThread08/GThread08.sh
- baseservices/threading/generics/syncdelegate/GThread22/GThread22.sh
- ...
```
**Error message:**
```
Unhandled exception. System.IO.FileLoadException: Assembly with same name is already loaded

Return code:      1
Raw output file:      D:\h\w\AD640915\w\A1F10939\uploads\Reports\JIT.Regression\CLR-x86-JIT\V2.0-Beta2\b399444\b399444b\b399444b.output.txt
Raw output:
BEGIN EXECUTION
D:\h\w\AD640915\p\ildasm.exe /raweh /out=b399444b.dasm.il b399444b.dll
D:\h\w\AD640915\p\ilasm.exe /output=b399444b.asm.dll  b399444b.dasm.il

Microsoft (R) .NET IL Assembler.  Version 7.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'b399444b.dasm.il'  to EXE --> 'b399444b.asm.dll'
Source file is UTF-8

Assembled method Tests.Test::Main
Assembled method Tests.Test::TestLd
Assembled method Tests.Test::.ctor
Assembled method Tests.ThousandMoreField::.ctor
Creating PE file

Emitting classes:
Class 1:Tests.Test
Class 2:Tests.ThousandMoreField

Emitting fields and methods:
Global
Class 1Methods: 3;
Class 2Fields: 65535;Methods: 1;
Resolving local member refs: 65536 -> 65536 defs, 0 refs, 0 unresolved

Emitting events and properties:
Global
Class 1
Class 2
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
"D:\h\w\AD640915\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  b399444b.asm.dll
END EXECUTION OF IL{D}ASM BINARY - FAILED -532462766 vs 100
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AD640915\p
D:\h\w\AD640915\w\A1F10939\e\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b399444\b399444b\b399444b.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._CLR_x86_JIT_V2_0_Beta2_b399444_b399444b_b399444b_._CLR_x86_JIT_V2_0_Beta2_b399444_b399444b_b399444b_cmd()
```

### LINKED ISSUE #70755: Crash in coreclr.dll!Debugger::SendException while processing stack overflow in x64 Windows
### Description

The in-process part of the .NET debugging services will exhaust the guard page while trying to send a stack overflow exception. This results in the target process exiting with an access violation and the debugger never breaking on the stack overflow. I don't know if this is the only way to cause this or just the easiest way, but I don't see this with a "hello world" sync method, but I do see it with an async method.

### Reproduction Steps

Run the following program under a debugger in x64 Windows. This repros with either 6.0.5 or with .NET 7 preview 4.

```csharp
class Program
{
    public static async Task Main(string[] args)
    {
        await Task.Delay(100);
        string result = StackOverflow(100000);
        Console.WriteLine(result);
    }

    private static string StackOverflow(int v)
    {
        if (v == 0)
        {
            return string.Empty;
        }
        else
        {
            return "*" + StackOverflow(v - 1);
        }
    }
}
```

### Expected behavior

Debugger should receive an unhandled exception event for the stack overflow.

### Actual behavior

Target process crashes with the following stack:

```
void StackFrameIterator::ProcessIp(PCODE Ip)
{
...
    // Re-initialize codeInfo with new IP
    m_crawl.codeInfo.Init(Ip, m_scanFlag);
   00007FFFF709840D  add         rcx,230h  
   00007FFFF7098414  mov         r8d,dword ptr [rbx+2E0h]  
=> 00007FFFF709841B  call        EECodeInfo::Init (07FFFF7098438h)  
```

The `call` instruction crashes because rsp already points at the end of stack, so the following page in unmapped.

```
coreclr.dll!StackFrameIterator::ProcessIp(unsigned __int64 Ip) Line 2729
	at D:\a\_work\1\s\src\coreclr\vm\stackwalk.cpp(2729)
coreclr.dll!StackFrameIterator::Init(Thread * pThread, Frame * pFrame, REGDISPLAY * pRegDisp, unsigned int flags) Line 1211
	at D:\a\_work\1\s\src\coreclr\vm\stackwalk.cpp(1211)
coreclr.dll!Thread::StackWalkFramesEx(REGDISPLAY * pRD, StackWalkAction(*)(CrawlFrame *, void *) pCallback, void * pData, unsigned int flags, Frame * pStartFrame) Line 907
	at D:\a\_work\1\s\src\coreclr\vm\stackwalk.cpp(907)
coreclr.dll!EEDbgInterfaceImpl::StackWalkFramesEx(Thread * pThread, REGDISPLAY * pRD, StackWalkAction(*)(CrawlFrame *, void *) pCallback, void * pData, unsigned int flags) Line 78
	at D:\a\_work\1\s\src\coreclr\vm\eedbginterfaceimpl.cpp(78)
coreclr.dll!Debugger::IsThreadAtSafePlaceWorker(Thread * thread) Line 12563
	at D:\a\_work\1\s\src\coreclr\debug\ee\debugger.cpp(12563)
coreclr.dll!AtSafePlaceHolder::AtSafePlaceHolder(Thread * pThread) Line 195
	at D:\a\_work\1\s\src\coreclr\debug\ee\debugger.cpp(195)
coreclr.dll!Debugger::SendException(Thread * pThread, bool fFirstChance, unsigned __int64 currentIP, unsigned __int64 currentSP, bool fContinuable, bool fAttaching, bool fForceNonInterceptable, _EXCEPTION_POINTERS * pExceptionInfo) Line 7690
	at D:\a\_work\1\s\src\coreclr\debug\ee\debugger.cpp(7690)
coreclr.dll!Debugger::LastChanceManagedException(_EXCEPTION_POINTERS * pExceptionInfo, Thread * pThread, int jitAttachRequested) Line 8656
	at D:\a\_work\1\s\src\coreclr\debug\ee\debugger.cpp(8656)
coreclr.dll!NotifyDebuggerLastChance(Thread * pThread, _EXCEPTION_POINTERS * pExceptionInfo, int jitAttachRequested) Line 3603
	at D:\a\_work\1\s\src\coreclr\vm\excep.cpp(3603)
coreclr.dll!WatsonLastChance(Thread * pThread, _EXCEPTION_POINTERS * pExceptionInfo, TypeOfReportedError tore) Line 3994
	at D:\a\_work\1\s\src\coreclr\vm\excep.cpp(3994)
coreclr.dll!EEPolicy::HandleFatalStackOverflow(_EXCEPTION_POINTERS * pExceptionInfo, int) Line 725
	at D:\a\_work\1\s\src\coreclr\vm\eepolicy.cpp(725)
coreclr.dll!EEPolicy::HandleStackOverflow() Line 147
	at D:\a\_work\1\s\src\coreclr\vm\eepolicy.cpp(147)
coreclr.dll!ProcessCLRException(_EXCEPTION_RECORD * pExceptionRecord, unsigned __int64 MemoryStackFp, _CONTEXT * pContextRecord, _DISPATCHER_CONTEXT * pDispatcherContext) Line 895
	at D:\a\_work\1\s\src\coreclr\vm\exceptionhandling.cpp(895)
ntdll.dll!RtlpExecuteHandlerForException() Line 132
	at minkernel\ntos\rtl\amd64\xcptmisc.asm(132)
ntdll.dll!RtlDispatchException(_EXCEPTION_RECORD * ExceptionRecord, _CONTEXT * ContextRecord) Line 595
	at minkernel\ntos\rtl\amd64\exdsptch.c(595)
ntdll.dll!KiUserExceptionDispatch() Line 751
	at minkernel\ntos\rtl\amd64\trampoln.asm(751)
00007fff9780041c()
        < Managed code >
```

### Regression?

This is a regression from .NET Framework.

### Known Workarounds

The only work around I have found is to run the code under the x86 runtime.

### Configuration

Version: .NET 6 and .NET 7
OS: Windows 10 (didn't try anything else)
Architecture: X64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkotas**
corerun gracefully handled filename not matching the assembly name. Handling of this case regressed in #68186. This change is fixing the regression.

Fixes #68455

### CODE REVIEW

**Comment by jkotas** [comment]
@BruceForstall Do you happen to know how to trigger the ilasm run?

**Comment by BruceForstall** [comment]
> @BruceForstall Do you happen to know how to trigger the ilasm run?

You did what I would have done. Let me see if I can find any obvious configuration issue with the pipeline.

**Comment by BruceForstall** [comment]
@jkotas Well I'm mystified about the trigger, but I manually kicked off an ilasm pipeline run:

https://dev.azure.com/dnceng/public/_build/results?buildId=1827721&view=results

**Comment by BruceForstall** [comment]
(fyi, it seems like the fact that the ilasm pipeline defines PR "paths" triggers (`src/coreclr/ilasm/*`, `src/coreclr/ildasm/*`) makes it unavailable for comment triggers. Seems like a bug/limitation, IMO.)

File: src/coreclr/binder/inc/defaultassemblybinder.h [hunk 1]
```diff
@@ -16,6 +16,7 @@ class DefaultAssemblyBinder final : public AssemblyBinder
 public:
 
     HRESULT BindUsingPEImage(PEImage* pPEImage,
+        bool fOverrideAppPath,
```
Comment (VSadov) [inline src/coreclr/binder/inc/defaultassemblybinder.h:19]: should this be `excludeAppPaths` ?

Comment (jkotas) [reply src/coreclr/binder/inc/defaultassemblybinder.h]: Yes, I have changed the name mid-flight.

**Review by VSadov — APPROVED** [review]
LGTM

**Review by elinor-fung — APPROVED** [review]

**Comment by jkotas** [comment]
ilasm failures are unrelated
