### PR TITLE
Fix the ARM's `double` register name displayed in JitDisasm/JitDump

### LINKED ISSUE #8121: [ARM32] Display wrong register number for double registers
For ARM32, double register number is not shown correctly in JitDump, JitDisasm and etc.

- An example from coreclr unit test.
  ```
  $ COMPlus_JitDisasm=DblAdd COMPlus_JitDump=DblAdd  ./corerun 
  tests/JIT/CodeGenBringUpTests/DblAdd/DblAdd.exe
  ...(omitted)...
  IN0001: 000006  EE30 0B01      vadd    d0, d0, d2
  ...(omitted)...
  IN0001: 000006      vadd    d0, d0, d2
  ```
  However above instruction encoding `EE30 0B01` means `vadd d0, d0, d1`.

- Another example from recent PR for ryujit/arm32.
  I was confused with below example (https://github.com/dotnet/coreclr/pull/11643#issuecomment-301755496) in the PR.
  ```
  IN0074: 000180  EEB8 4BC4      vcvt.i2d d8, s8  
  ```
  This encoding `EEB8 4BC4` means `vcvt.i2d d4, s8`, i.e. single-float register number is correct, but double register number is incorrectly displayed.

Both LegacyJIT and RyuJIT have same problem.

category:implementation
theme:debug-dumps
skill-level:intermediate
cost:medium

### PR DESCRIPTION
**Pull request by kunalspathak**
Fix the display of ARM double register name in JitDisasm and JitDump. We would just display the floating register name, but instead should be displaying the accurate double register name (that the encoding reflects).

Fixes: https://github.com/dotnet/runtime/issues/8121

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/emitarm.cpp [hunk 1]
```diff
@@ -6927,8 +6927,18 @@ void emitter::emitDispReg(regNumber reg, emitAttr attr, bool addComma)
...
+        {
+            char     regNum[2];
+            unsigned regIndex = reg - REG_F0;
+            regIndex >>= 1;
+
+            printf("d%s", _itoa(regIndex, regNum, 10));
+        }
+        else
+        {
+            printf("s%s", emitFloatRegName(reg, attr) + 1);
```
Comment (markples) [inline src/coreclr/jit/emitarm.cpp:6940]: Is this side also incorrect?  I could easily have misread the chain of calls, but it looked like emitFloatRegName is going to return "f<n>" so it would be "sf<n>", which doesn't seem right.

**Review by markples — APPROVED** [review]
Change looks good - there might be another change depending on whether my comment is correct or not, but this is an improvement either way.

File: src/coreclr/jit/emitarm.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/emitarm.cpp:6940]: Right, but since we do ` + 1`, we remove the extra `f` character that gets printed. This portion is unchanged actually.

Comment (kunalspathak) [reply src/coreclr/jit/emitarm.cpp:6940]: I will just use something manual version of `_itoa` to convert from int -> string.

**Review by BruceForstall — APPROVED** [review]
