### PR TITLE
Fixed ILVerify incorrectly flagging valid default interface implementations

### LINKED ISSUE #46236: ILVerify rejects classes which inherit default interface method implementations
### Description

ILVerify 5.0.0 does not verify a class which implements an interface which contains a method which is virtual but not abstract. In other words, it doesn't seem to support [default interface methods](https://github.com/dotnet/runtime/blob/9ddd39ed571f6ca82a5b7aee05ac327073b112a3/docs/design/features/default-interface-methods.md).

**Repro steps**:

1. Create a new C# console application (e.g. `dotnet new console`).
2. Ensure the new project has a TargetFramework of `net5.0`.
3. Declare an interface and a method within that interface that provides an implementation. E.g.:
    ```
    interface I
    {
        public string HasDefaultImplementation()
        {
            return "I::HasDefaultImplementation";
        }
    }
    ```
4. Declare a class which implements that interface but does *not* provide an implementation for that method. E.g:
    ```
    class C : I { }
    ```
5. Build and run the project to show that there are no errors building or at runtime. (Optionally, you can exercise the types declared, such as by calling `HasDefaultImplementation` on an instance of `C` which has been cast to `I`.)
6. Install ILVerify as a local tool (e.g. `dotnet new tool-manifest` then `dotnet tool install dotnet-ilverify`).
7. Run ILVerify on the built assembly (e.g. `dotnet ilverify bin\Debug\net5.0\ILVerifyRepro.dll -r "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\*.dll"`).

**Expected behavior**: the assembly verifies completely.

**Actual behavior**: the following error is reported:

```
[MD]: Error: Class implements interface but not method, Class: '[ILVerifyRepro]ILVerifyRepro.C' Interface: '[ILVerifyRepro]ILVerifyRepro.I' Missing method: '[ILVerifyRepro]ILVerifyRepro.I.HasDefaultImplementation()'.
```

**Reproduction (attachment)**: [ILVerifyRepro.zip](https://github.com/dotnet/runtime/files/5718276/ILVerifyRepro.zip)

**Rationale**:

It sounds like this issue might already be known, based on [this comment](https://github.com/dotnet/runtime/issues/43503#issuecomment-712790904), but I figured I should report it as its own issue both for better visibility and tracking, and also to indicate there's some desire outside of Microsoft / the .NET developers for an accurate ILVerify. Specifically, I represent the Dotfuscator team at PreEmptive, and an up-to-date ILVerify would be very helpful in ensuring we continue to obey the runtime's rules when modifying customers' assemblies, in light of the recent changes to interface methods.

### Configuration

* The example console app targets .NET 5.0. Based on the output of `--list-runtimes`, the only 5.0 runtime I have installed is Microsoft.NETCore.App 5.0.0.
* Running on Windows 10, Version 1903 (10.0.18362.592).
* The machine is x64.
* I would think it unlikely that this issue is configuration-specific.

### Regression?

The oldest version of [dotnet-ilverify listed on NuGet.org](https://www.nuget.org/packages/dotnet-ilverify/) is `5.0.0-preview.7.20364.11`. It errors with a different message:

```
Error: System.Resources.MissingManifestResourceException: Could not find the resource "ILVerification.Strings.resources" among the resources "" 
embedded in the assembly "ILVerify", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at ILVerify.Verifier.<>c__DisplayClass13_0.<VerifyType>b__1(VerifierError code, Object[] args)
   at Internal.TypeVerifier.TypeVerifier.VerificationError(VerifierError error, Object[] args)
   at Internal.TypeVerifier.TypeVerifier.VerifyInterfaces()
   at Internal.TypeVerifier.TypeVerifier.Verify()
   at ILVerify.Verifier.VerifyType(EcmaModule module, TypeDefinitionHandle typeHandle)
   at ILVerify.Verifier.Verify(PEReader peReader, TypeDefinitionHandle typeHandle, Boolean verifyMethods)+MoveNext()
   at ILVerify.Program.VerifyTypes(PEReader peReader, EcmaModule module, String path, Int32& numErrors, Int32& verifiedTypeCounter, Int32& typeCounter)
   at ILVerify.Program.VerifyAssembly(PEReader peReader, EcmaModule module, String path)
   at ILVerify.Program.Run()
   at ILVerify.Program.Run(Options options)
```

The next newest version, `5.0.0-preview.8.20407.11`, produces the same error as in `5.0.0`.

### PR DESCRIPTION
**Pull request by bbartels**
This PR fixes #46236 

I moved tests regarding default implementation to a new file for visibility. If this is an undesired change, let me know and I'll revert it.

The following test still fails, even though the default interface method that is re-abstracted in `IReabstractDefaultImplementation` is implemented within the class. I will open another issue for this scenario.

```
.class public auto ansi beforefieldinit ChildClassThatInheritsFromInterfaceThatReabstractedDefaultInterfaceMethodImplementsContract_ValidType_Valid
	extends [System.Runtime]System.Object
	implements IReabstractDefaultImplementation, IExtendedDefaultImplInterface, IInterface
{
	.method public final hidebysig newslot virtual 
		instance void Method () cil managed 
	{
		.maxstack 8

		IL_0001: ret
	}

	.method public hidebysig specialname rtspecialname 
		instance void .ctor () cil managed 
	{
		.maxstack 8

		IL_0000: ldarg.0
		IL_0001: call instance void [System.Runtime]System.Object::.ctor()
		IL_0006: nop
		IL_0007: ret
	}
}
```

/cc @EgorBo 
/cc @jkotas

### CODE REVIEW

File: src/coreclr/tools/Common/TypeSystem/Common/TypeSystemHelpers.cs [hunk 1]
```diff
@@ -296,9 +296,16 @@ public static MethodDesc ResolveInterfaceMethodTarget(this TypeDesc thisType, Me
             }
             while (result == null && currentType != null);
 
+            // If no base type contains interface method, attempt to find default implementation
+            if (result == null)
+            {
+                _ = thisType.ResolveInterfaceMethodToDefaultImplementationOnType(interfaceMethodToResolve, out result);
+            }
+
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Common/TypeSystemHelpers.cs:304]: ILVerify needs to call `ResolveInterfaceMethodToDefaultImplementationOnType` manually after this resolution fails; it cannot be done in this method. There are nuances around default interface method resolution that will not work as expected if this is done here. The nuances might not affect ILVerify right now, but will affect it eventually.

E.g. if we want to do reporting of diamond cases in ILVerify (when multiple interfaces on the type provide a default implementation for a method), we'll have to call into ResolveInterfaceMethodToDefaultImplementationOnType manually anyway.

Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/TypeSystem/Common/TypeSystemHelpers.cs:304]: (This change breaks other consumers of TypeSystemHelper.cs)

Comment (bbartels) [reply src/coreclr/tools/Common/TypeSystem/Common/TypeSystemHelpers.cs:304]: Could you elaborate on what you mean with `ILVerify needs to call ResolveInterfaceMethodToDefaultImplementationOnType manually after this resolution fails`? Why is it a problem that ILVerify needs to call the method after the resolution fails? Does the method affect state in some way, meaning a second call won't succeed anymore?

Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/TypeSystem/Common/TypeSystemHelpers.cs:304]: `ResolveInterfaceMethodTarget` (which is in a source file shared with other components in this repo and not unique to ILVerify) should not call `ResolveInterfaceMethodToDefaultImplementationOnType`. Instead ILVerify should call `ResolveInterfaceMethodToDefaultImplementationOnType` when `ResolveInterfaceMethodTarget` returns null.

This is how other components do this as well. We don't want to hide failure modes that are unique to default interface methods here (I'm referring to the value returned from `ResolveInterfaceMethodToDefaultImplementationOnType` that is being swallowed here).

Comment (bbartels) [reply src/coreclr/tools/Common/TypeSystem/Common/TypeSystemHelpers.cs:304]: Right I think I understand correctly now. So would it be sufficient to move the call to `ResolveInterfaceMethodToDefaultImplementationOnType` into `VerifyInterfaces` if  `ResolveInterfaceMethodToDefaultImplementationOnType` returns `null`?

Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/TypeSystem/Common/TypeSystemHelpers.cs:304]: Yes, that sound good. It will also put ILVerify into a better position to report unique error messages for things like the diamond case.

Comment (bbartels) [reply src/coreclr/tools/Common/TypeSystem/Common/TypeSystemHelpers.cs]: Thank you! I adjusted the callsite of `ResolveInterfaceMethodToDefaultImplementationOnType`. Apologies for misunderstanding your original comment, thank you for elaborating :)
I'll create another issue for the bug mentioned in this PR's description.

**Comment by JulieLeeMSFT** [comment]
@MichalStrehovsky Is there anything else to be done for this PR? Are we good to merge this PR?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky Is there anything else to be done for this PR? Are we good to merge this PR?

The change no longer touches any of the files I own (which was the reason I looked at it in the first place). The change in ILVerify looks good. I didn't look at the tests.

File: src/tests/ilverify/ILTests/DefaultInterfaceMethod.il [hunk 2]
```diff
@@ -0,0 +1,125 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+.assembly DefaultImpl
```
Comment (jkotas) [inline src/tests/ilverify/ILTests/DefaultInterfaceMethod.il:4]:
```suggestion
.assembly DefaultInterfaceMethod
```
to match the filename

File: src/tests/ilverify/ILTests/DefaultInterfaceMethod.il [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+{
+}
+
+.class interface private auto ansi abstract IInterface
+{
+	.method public hidebysig newslot abstract virtual
+		instance void Method () cil managed
+	{
+	}
+
```
Comment (jkotas) [inline src/tests/ilverify/ILTests/DefaultInterfaceMethod.il:18]:
```suggestion
```
extra ws

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
@bbartels Thank you!
