### PR TITLE
Optimize VectorX<T>.ConditionalSelect for constant masks

### LINKED ISSUE #104001: VectorX<T>.ConditionalSelect doesn’t get optimized for const masks on non-AVX512 platforms
### Description

I was comparing `VectorT.ConditionalSelect` (128-bit in particular) and `Sse41.BlendVariable` disassembly output and found out that the first method gets only optimized into the second one only if the mask is the result of `Compare*` intrinsic. However we can actually optimize it if the mask is constant (e.g. `Vector.Create`) since we can check its contents in the JIT during compilation. [Here is the reproduction repo](https://github.com/ezhevita/ConditionalSelectReproduce). I’ve also implemented an optimization in JIT [here](https://github.com/ezhevita/runtime/tree/optimize-cndsel) (worth mentioning that I’ve currently haven’t optimized `VectorT.ConditionalSelect(Vector.Create(fieldOrVariable))` since I didn’t find a way to inspect the values of field/variable, `GT_LCL_VAR` and `GT_LCL_FLD` in the JIT tree).

### Configuration

```
BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3737/23H2/2023Update/SunValley3)
AMD Ryzen 7 5800X3D, 1 CPU, 16 logical and 8 physical cores
.NET SDK 9.0.100-preview.5.24307.3
  [Host]     : .NET 9.0.0 (9.0.24.30607), X64 RyuJIT AVX2
  DefaultJob : .NET 9.0.0 (9.0.24.30607), X64 RyuJIT AVX2
```

### Regression?

Not a regression.

### Data

Reproduction, benchmarks, and disassembly: https://github.com/ezhevita/ConditionalSelectReproduce

### Analysis

The current implementation only checks for `Compare*` intrinsics however we can actually check and prove that the mask is indeed per-element if the vector is constant.
Also another solution might be a new method in the API for the consumers which restricts the vector to be per-element mask.

### PR DESCRIPTION
**Pull request by ezhevita**
Resolves https://github.com/dotnet/runtime/issues/104001.
I’ve also realized that it is not possible to implement this for arrays as I’ve originally intended since we have no immutability guarantees, so instead I’ve made sure it gets optimized with `ReadOnlySpan<T>` property and static `VectorX<T>` field.

Example:
```csharp
[DisassemblyDiagnoser]
public class TestClass
{
    private ReadOnlySpan<byte> Mask => [255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0];

    [Benchmark]
    public byte Span()
    {
        return Vector128.ConditionalSelect(Vector128.Create(Mask), Vector128<byte>.Zero, Vector128<byte>.One)[0];
    }
}
```

Old codegen:
```asm
; Method TestNamespace.TestClass:Span():ubyte:this (FullOpts)
G_M000_IG01:

G_M000_IG02:
       vmovups  xmm0, xmmword ptr [reloc @RWD00]
       vxorps   xmm1, xmm1, xmm1
       vpand    xmm1, xmm1, xmm0
       vpandn   xmm0, xmm0, xmmword ptr [reloc @RWD16]
       vpor     xmm0, xmm0, xmm1
       vmovd    eax, xmm0
       movzx    rax, al

G_M000_IG03:
       ret      
RWD00  	dq	00FF00FF00FF00FFh, 00FF00FF00FF00FFh
RWD16  	dq	0101010101010101h, 0101010101010101h
; Total bytes of code: 36

```

New codegen:
```asm
; Method TestNamespace.TestClass:Span():ubyte:this (FullOpts)
G_M000_IG01:

G_M000_IG02:
       vmovups  xmm0, xmmword ptr [reloc @RWD00]
       vxorps   xmm1, xmm1, xmm1
       vmovups  xmm2, xmmword ptr [reloc @RWD16]
       vpblendvb xmm0, xmm2, xmm1, xmm0
       vmovd    eax, xmm0
       movzx    rax, al

G_M000_IG03:
       ret      
RWD00  	dq	00FF00FF00FF00FFh, 00FF00FF00FF00FFh
RWD16  	dq	0101010101010101h, 0101010101010101h
; Total bytes of code: 34

```

### CODE REVIEW

**Comment by ezhevita** [comment]
@dotnet-policy-service agree

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -29442,6 +29442,57 @@ bool GenTree::IsInvariant() const
...
+// Returns:
+//     True if this node is a vector constant per-element mask
+//
+bool GenTree::IsVectorPerElementMask(var_types simdBaseType, unsigned simdSize) const
+{
+#ifdef FEATURE_SIMD
+    if (IsCnsVec())
+    {
+        const GenTreeVecCon* vecCon = AsVecCon();
+        if (vecCon->IsAllBitsSet() || vecCon->IsZero())
```
Comment (EgorBo) [inline src/coreclr/jit/gentree.cpp:29458]: do we need these checks? I doubt they save any measurable TP

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -29442,6 +29442,57 @@ bool GenTree::IsInvariant() const
...
 }
 
+//-------------------------------------------------------------------
+// IsVectorPerElementMask: returns true if this node is a vector constant per-element mask
+// (every element has either all bits set or none of them).
+//
+// Returns:
+//     True if this node is a vector constant per-element mask
+//
+bool GenTree::IsVectorPerElementMask(var_types simdBaseType, unsigned simdSize) const
```
Comment (EgorBo) [inline src/coreclr/jit/gentree.cpp:29452]: Perhaps, we can name it as ElementsAreAllBitsSetOrZero as well?

File: src/coreclr/jit/gentree.cpp [hunk 3]
```diff
@@ -29442,6 +29442,57 @@ bool GenTree::IsInvariant() const
     return OperIsConst() || OperIs(GT_LCL_ADDR) || OperIs(GT_FTN_ADDR);
 }
 
+//-------------------------------------------------------------------
+// IsVectorPerElementMask: returns true if this node is a vector constant per-element mask
+// (every element has either all bits set or none of them).
```
Comment (EgorBo) [inline src/coreclr/jit/gentree.cpp:29447]: nit: comments for parameters are missing

File: src/coreclr/jit/gentree.cpp (hunk 2 above)
Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:29452]: We've explicitly used the term `PerElementMask` elsewhere throughout the JIT to encompass the general concept necessary here.

File: src/coreclr/jit/gentree.cpp (hunk 1 above)
Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:29458]: 👍, these functions just loop the memory checking if all elements are a given value

Comment (ezhevita) [reply src/coreclr/jit/gentree.cpp:29458]: @tannergooding suggested that these checks should be in place here: https://discord.com/channels/143867839282020352/312132327348240384/1255568916151930990
However ConditionalSelect with all bits set/all bits zero as a mask is pretty useless, so we can get rid of these

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:29458]: The consideration is rather just that main loop below already handles this and these checks aren't "cheap", they are just doing a loop and comparison themselves.

So by removing these explicit checks, we can loop once rather than 3 times and still handle all the scenarios.

File: src/coreclr/jit/gentree.cpp [hunk 4]
```diff
@@ -29442,6 +29442,57 @@ bool GenTree::IsInvariant() const
...
+            case TYP_DOUBLE:
+                return ElementsAreAllBitsSetOrZero(&vecCon->gtSimdVal.u64[0], elementCount);
+            default:
+                unreached();
+        }
+    }
+    else if (OperIsHWIntrinsic())
+    {
+        // TODO-XARCH-AVX512 Use VPBLENDM* and take input directly from K registers if cond is from
+        // MoveMaskToVectorSpecial.
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:29488]: This comment isn't applicable to the general query, it was specific to the CndSel lowering logic

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/gentree.cpp [hunk 5]
```diff
@@ -29442,6 +29442,57 @@ bool GenTree::IsInvariant() const
...
+        return HWIntrinsicInfo::ReturnsPerElementMask(AsHWIntrinsic()->GetHWIntrinsicId());
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:29489]: If you wanted to, you could also update this just a little bit more as there's some very simple cases that we could cover that would also allow us to optimize further.

In particular, you could have this do:
```cpp
GenTreeHWIntrinsic* intrinsic   = AsHWIntrinsic();
NamedIntrinsic      intrinsicId = intrinsic->GetHWIntrinsicId();

if (HWIntrinsicInfo::ReturnsPerElementMask(intrinsicId))
{
    // We directly return a per-element mask
    return true;
}

bool       isScalar = false;
genTreeOps oper     = intrinsic->HWOperGet(&isScalar);

switch (oper)
{
    case GT_AND:
    case GT_AND_NOT:
    case GT_OR:
    case GT_XOR:
    {
        // We are a binary bitwise operation where both inputs are per-element masks
        return intrinsic->Op(1)->IsVectorPerElementMask(simdBaseType, simdSize)
            && intrinsic->Op(2)->IsVectorPerElementMask(simdBaseType, simdSize);
    }

    case GT_NOT:
    {
        // We are an unary bitwise operation where the input is a per-element mask
        return intrinsic->Op(1)->IsVectorPerElementMask(simdBaseType, simdSize);
    }

    default:
    {
        assert(!GenTreeHWIntrinsic::OperIsBitwiseHWIntrinsic(oper));
        break;
    }
}

return false;
```

There's others that qualify as well, but I expect they're more rare and the bitwise operations are the most important to consider.

File: src/coreclr/jit/gentree.cpp [hunk 6]
```diff
@@ -29442,6 +29442,93 @@ bool GenTree::IsInvariant() const
...
+
+        if (HWIntrinsicInfo::ReturnsPerElementMask(intrinsicId))
+        {
+            // We directly return a per-element mask
+            return true;
+        }
+
+        bool       isScalar = false;
+        genTreeOps oper     = intrinsic->HWOperGet(&isScalar);
+        assert(!isScalar);
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:29498]: Don't think this `assert` is correct. There's lots of nodes that don't return a per-element mask but which can be scalar, like `GT_ADD`

It just shouldn't be scalar for the bitwise operators (AND, AND_NOT, OR_XOR, NOT)

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:29498]: Removing this should get everything in a state where we can get it merged
```suggestion
```

**Review by tannergooding — APPROVED** [review]

**Comment by tannergooding** [comment]
@EgorBo, this should be good for secondary sign-off and merging now

**Review by EgorBo — APPROVED** [review]
Thanks!
