### PR TITLE
[mono] Fix detecting [DisableRuntimeMarshalling] in MarshalingPInvokeScanner.

### LINKED ISSUE #112980: MarshalingPInvokeScanner doesn't see [DisableRuntimeMarshalling] attributes in any assembly except System.Runtime.dll
The MarshalingPInvokeScanner task doesn't see [DisableRuntimeMarshalling] attributes defined in any assembly except System.Runtime.dll (where the attribute is defined).

The problem is that this code:

https://github.com/dotnet/runtime/blob/035d2686771a79ee8b8f1b976f6ccc6dec427611/src/tasks/MonoTargetsTasks/MarshalingPInvokeScanner/MarshalingPInvokeScanner.cs#L116-L131

does not take into account that the attribute's constructor will be a MethodReference when referencing a constructor defined in another assembly.

Repro:

* Clone https://github.com/rolfbjarne/marshalling-scanner (including submodules)
* Run `make disable-runtime-marshalling-attribute`

This happens:

```
[...]
Assembly /Users/rolf/test/dotnet/marshalling-scanner/disable-runtime-marshalling-attribute/bin/Debug/net9.0/disable-runtime-marshalling-attribute.dll requires marshal-ilgen for method .Class1:DoSomething (first pass).
❌ Failed, because some assemblies are incompatible
make: *** [disable-runtime-marshalling-attribute] Error 1
```

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fix detecting the [DisableRuntimeMarshalling] attribute in
MarshalingPInvokeScanner for assemblies that reference the attribute from
another assembly (i.e. any assembly except System.Runtime.dll).

Fixes https://github.com/dotnet/runtime/issues/112980.

### CODE REVIEW

File: src/tasks/MonoTargetsTasks/MarshalingPInvokeScanner/MarshalingPInvokeScanner.cs [hunk 1]
```diff
@@ -104,6 +104,12 @@ private void ResolveInconclusiveTypes(HashSet<string> incompatible, string assyP
             }
         }
 
+        private bool IsDisableRuntimeMarshallingAttribute (MetadataReader mdtReader, StringHandle ns, StringHandle name)
+        {
+            return mdtReader.GetString(ns) == "System.Runtime.CompilerServices" &&
+                   mdtReader.GetString(name) == "DisableRuntimeMarshallingAttribute";
```
Comment (teo-tsirpanis) [inline src/tasks/MonoTargetsTasks/MarshalingPInvokeScanner/MarshalingPInvokeScanner.cs:110]: This will avoid allocating strings.

```suggestion
            return mdtReader.StringComparer.Equals(ns, "System.Runtime.CompilerServices") &&
                   mdtReader.StringComparer.Equals(name, "DisableRuntimeMarshallingAttribute");
```

**Comment by akoeplinger** [comment]
lgtm but there are a few code style errors

**Review by akoeplinger — APPROVED** [review]

**Comment by rolfbjarne** [comment]
@akoeplinger looks like the failure is unrelated? is there anything else I need to do to get this in?

**Comment by akoeplinger** [comment]
>  is there anything else I need to do to get this in?

no, I just forgot to merge, sorry :D
