### PR TITLE
[browser] tests and fixes for heap larger than 2GB

### LINKED ISSUE #104618: [browser] tests and fixes for heap larger than 2GB
## WBT
 - set `<EmccMaximumHeapSize>4294901760</EmccMaximumHeapSize>`
 - allocate large arrays in order to deplete memory below 2GB
 - after that
     - test marshaling array of string via `JSImport`
     - call some method many times to trigger interp tier-up and jiterp

## Potential fixes needed
 - convert all results of `Module._malloc` from `int` to `uint`
     - in jiterp
     - in JS interop

See also https://github.com/dotnet/runtime/discussions/99114

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/104618.

We're adding WBT that uses `EmccMaximumHeapSize`.
It surfaces an issue: relink is needed to pass `EmccMaximumHeapSize` further to emscripten https://github.com/dotnet/runtime/blob/61f08d36ac9d92a2c93a5478bf22f3fc82a0b7e8/src/mono/browser/build/BrowserWasmApp.targets#L299
otherwise we will get OOM failure.

Related issues: https://github.com/dotnet/runtime/issues/104790

### CODE REVIEW

File: src/mono/wasm/testassets/WasmBasicTestApp/App/MemoryTest.cs [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+        bool correct = AssertJoinCorrect(testArray, response);
+        if (!correct)
+            errors += $"expected response: {response}, testArray: {string.Join("", testArray)}";
+
+        // call a method many times to trigger tier-up optimization
+        for (int i = 0; i < 10000; i++)
+        {
+            AssertJoinCorrect(testArray, response);
+        }
+        if (!string.IsNullOrEmpty(error))
```
Comment (maraf) [inline src/mono/wasm/testassets/WasmBasicTestApp/App/MemoryTest.cs:46]: Is it a typo?

```suggestion
        if (!string.IsNullOrEmpty(errors))
```

**Review by maraf — APPROVED** [review]
The test looks good to me.

Do you plan to do more as part of https://github.com/dotnet/runtime/issues/104618 or is it fine to close it with this PR?

**Comment by ilonatommy** [comment]
I would close it already, the issue was meant to track down the reasons for this behavior. We have a new issue for fixing the reasons (https://github.com/dotnet/runtime/issues/104790).

File: src/mono/wasm/testassets/WasmBasicTestApp/App/MemoryTest.cs [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+                arrayHolder[i] = new int[1024 * 1024 * 25];
+            }
+            catch (Exception ex)
+            {
+                errors += $"Exception {ex} was thrown on i={i}";
+            }
+        }
+
+        // marshall string array to JS
+        string [] testArray = new [] { "M", "e", "m", "o", "r", "y", "T", "e", "s", "t" };
```
Comment (pavelsavara) [inline src/mono/wasm/testassets/WasmBasicTestApp/App/MemoryTest.cs:34]: Please make each string here random (constants are not allocated) and large enough, so that the JS side is forced to make allocations above 2GB mark. And overflow to negative numbers. Maybe run this in a loop.

Comment (ilonatommy) [reply src/mono/wasm/testassets/WasmBasicTestApp/App/MemoryTest.cs:34]: Then let's use the `arrayHolder` that is already prepared.

Comment (ilonatommy) [reply src/mono/wasm/testassets/WasmBasicTestApp/App/MemoryTest.cs]: 2GB string allocation with random data is taking too long, not only to run WBT but to even debug it.

Comment (ilonatommy) [reply src/mono/wasm/testassets/WasmBasicTestApp/App/MemoryTest.cs]: Also, we cannot just take `arrayHolder` and send it to JS to force JS to allocate 2GB because interop does not support array of arrays. Allocating flat array of 2GB requires more linear memory and can be problematic from other reasons than investigated in the issue. Allocating an array of strings theoretically should work but as I already mentioned, it takes tens of minutes to finish the allocation, even using `StringBuilder`.
@maraf, do you have a good idea how to fulfill the requirements?

Comment (ilonatommy) [reply src/mono/wasm/testassets/WasmBasicTestApp/App/MemoryTest.cs]: Never mind, I realized that the key point was "allocations above 2GB mark", not "allocations of 2GB".

Comment (ilonatommy) [reply src/mono/wasm/testassets/WasmBasicTestApp/App/MemoryTest.cs]: We're allocating `2 621 440 000 bytes` so more than max int. There are no traces of overflow. Let's merge this to take care of the relink fix PR that is built on top of this.
