### PR TITLE
[mono][interp] Don't assert when encountering invalid IL opcode

### LINKED ISSUE #54372: [MONO][Interp] transform.c: Unimplemented opcode: ee at 0x0
The following tests failed on Android x64 with Interpreter the the same error shown below:

- JIT/Directed/coverage/importer/ceeillegal/ceeillegal.sh
- JIT/Directed/coverage/importer/Desktop/ceeillegal_il_d/ceeillegal_il_d.sh
- JIT/Directed/coverage/importer/Desktop/ceeillegal_il_r/ceeillegal_il_r.sh

Here is the error message:

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.Directed/console.850ee7bc.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
06-17 16:50:05.652  7348  7366 I DOTNET  : MonoRunner initialize,, entryPointLibName=ceeillegal.dll
      06-17 16:50:05.652  7348  7366 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Directed/files/runtimeconfig.bin
      06-17 16:50:05.666  7348  7366 D DOTNET  : Interp Enabled
      06-17 16:50:05.691  7348  7366 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Directed/files
      06-17 16:50:05.754  7348  7366 D DOTNET  : assembly_preload_hook: ceeillegal.dll (null) /data/user/0/net.dot.JIT_Directed/files
      06-17 16:50:05.755  7348  7366 D DOTNET  : Executable: ceeillegal.dll
      06-17 16:50:05.755  7348  7366 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_Directed/files
      06-17 16:50:05.755  7348  7366 D DOTNET  : ((null) error) transform.c: Unimplemented opcode: ee at 0x0
      06-17 16:50:05.755  7348  7366 E DOTNET  : Exit code: 1.
      06-17 16:50:05.805  1792  6219 I ActivityManager: Process net.dot.JIT_Directed (pid 7348) has died: fore FGS 
      06-17 16:50:05.807  1792  6219 W ActivityManager: Crash of app net.dot.JIT_Directed running instrumentation ComponentInfo{net.dot.JIT_Directed/net.dot.MonoRunner}
      06-17 16:50:05.808  1536  1536 I Zygote  : Process 7348 exited cleanly (1)
      06-17 16:50:05.809  1792  6219 I ActivityManager: Force stopping net.dot.JIT_Directed appid=10110 user=0: finished inst
      06-17 16:50:05.816  1792  7369 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:50:05.816  1792  7369 W Binder  : java.lang.Throwable
      06-17 16:50:05.816  1792  7369 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:50:05.816  1792  7369 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:50:05.816  1792  7369 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:50:05.827  7338  7338 D AndroidRuntime: Shutting down VM
      06-17 16:50:05.847  1792  7369 I ActivityManager: Failure reporting to instrumentation watcher: comp=ComponentInfo{net.dot.JIT_Directed/net.dot.MonoRunner} results=Bundle[{shortMsg=Process crashed.}]
      06-17 16:50:05.852  1792  1819 I libprocessgroup: Successfully killed process cgroup uid 10110 pid 7348 in 45ms
```

### PR DESCRIPTION
**Pull request by BrzVlad**
Throw exception instead.

Fixes https://github.com/dotnet/runtime/issues/54372

### CODE REVIEW

File: src/mono/mono/mini/interp/transform.c [hunk 1]
```diff
@@ -7539,8 +7539,11 @@ generate_code (TransformData *td, MonoMethod *method, MonoMethodHeader *header,
 				g_error ("transform.c: Unimplemented opcode: 0xFE %02x (%s) at 0x%x\n", *td->ip, mono_opcode_name (256 + *td->ip), td->ip-header->code);
 			}
 			break;
-		default:
-			g_error ("transform.c: Unimplemented opcode: %02x at 0x%x\n", *td->ip, td->ip-header->code);
+		default: {
+			g_warning ("opcode 0x%02x not handled", *td->ip);
+			mono_error_set_generic_error (error, "System", "InvalidProgramException", "");
```
Comment (lambdageek) [inline src/mono/mono/mini/interp/transform.c:7544]: Can we include the opcode in the message in the exception?
```suggestion
			mono_error_set_generic_error (error, "System", "InvalidProgramException", "opcode 0x%02x not handled", *td->ip);
```

**Review by lambdageek — APPROVED** [review]
