### PR TITLE
Fix and simplify GCDescs for collectible types

### LINKED ISSUE #49684: Crash in GC
### Description
.NET Runtime crash in GC with stack:
```
[0x0]   coreclr!CGCDesc::GetNumPointers + 0x24   
[0x1]   coreclr!WKS::gc_heap::background_mark_simple1 + 0x10262a   
[0x2]   coreclr!WKS::gc_heap::background_mark_simple + 0x74   
[0x3]   coreclr!WKS::gc_heap::background_promote + 0x52   
[0x4]   coreclr!ScanConsecutiveHandlesWithoutUserData + 0x45   
[0x5]   coreclr!BlockScanBlocksWithoutUserData + 0x44   
[0x6]   coreclr!ProcessScanQNode + 0x44   
[0x7]   coreclr!ProcessScanQueue + 0x3f   
[0x8]   coreclr!xxxTableScanQueuedBlocksAsync + 0x5d   
[0x9]   coreclr!xxxAsyncSegmentIterator + 0x55   
[0xa]   coreclr!TableScanHandles + 0x7c   
[0xb]   coreclr!xxxTableScanHandlesAsync + 0x97   
[0xc]   coreclr!HndScanHandlesForGC + 0x10c   
[0xd]   coreclr!Ref_TracePinningRoots + 0x96   
[0xe]   coreclr!GCScan::GcScanHandles + 0xd4   
[0xf]   coreclr!WKS::gc_heap::background_mark_phase + 0x1244   
[0x10]   coreclr!WKS::gc_heap::gc1 + 0x1b5   
[0x11]   coreclr!WKS::gc_heap::bgc_thread_function + 0x90   
[0x12]   coreclr!<lambda_c5a49c859c7ba70587da980d74c056e1>::operator() + 0xa0   
[0x13]   kernel32!BaseThreadInitThunk + 0x14   
[0x14]   ntdll!RtlUserThreadStart + 0x21   
```
I tried to switch into Server GC but it crashed too:
```
[0x0]   coreclr!CGCDesc::GetNumPointers + 0x25   
[0x1]   coreclr!SVR::gc_heap::background_mark_simple1 + 0xf4   
[0x2]   coreclr!SVR::gc_heap::background_mark_simple + 0x96   
[0x3]   coreclr!SVR::gc_heap::background_promote + 0x11d   
[0x4]   coreclr!ScanConsecutiveHandlesWithoutUserData + 0x45   
[0x5]   coreclr!BlockScanBlocksWithoutUserData + 0x44   
[0x6]   coreclr!ProcessScanQNode + 0x44   
[0x7]   coreclr!ProcessScanQueue + 0x3f   
[0x8]   coreclr!xxxTableScanQueuedBlocksAsync + 0x5d   
[0x9]   coreclr!xxxAsyncSegmentIterator + 0x55   
[0xa]   coreclr!TableScanHandles + 0x7c   
[0xb]   coreclr!xxxTableScanHandlesAsync + 0x97   
[0xc]   coreclr!HndScanHandlesForGC + 0x10c   
[0xd]   coreclr!Ref_TraceNormalRoots + 0xb8   
[0xe]   coreclr!GCScan::GcScanHandles + 0x218   
[0xf]   coreclr!SVR::gc_heap::background_mark_phase + 0x13ba   
[0x10]   coreclr!SVR::gc_heap::gc1 + 0x136   
[0x11]   coreclr!SVR::gc_heap::bgc_thread_function + 0xe0   
[0x12]   coreclr!<lambda_c5a49c859c7ba70587da980d74c056e1>::operator() + 0xa0   
[0x13]   kernel32!BaseThreadInitThunk + 0x14   
[0x14]   ntdll!RtlUserThreadStart + 0x21   
```
It happened in our internal build system. When I run build with /m:16 and worked if I run build without /m.
### Configuration
Windows: 19042.867
.NET Core SDK: dotnet-sdk-5.0.103-win-x64
x64

### Other information
I create two full dumps in Server and Workstation GC mode.
https://drive.google.com/file/d/1RvDtBOVmexXFYRdJuaEIpZUXmWLsRTg7/view?usp=sharing
https://drive.google.com/file/d/1yzqwsb2WXwmYaxBQE7kp702L1YR9qodb/view?usp=sharing

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #49684

### CODE REVIEW

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 1]
```diff
@@ -8743,19 +8743,6 @@ MethodTableBuilder::HandleGCForExplicitLayout()
 
     MethodTable *pMT = GetHalfBakedMethodTable();
 
-#ifdef FEATURE_COLLECTIBLE_TYPES
```
Comment (jkotas) [inline src/coreclr/vm/methodtablebuilder.cpp:8746]: I want to see the places where these dummy GCDescs are actually needed. I am not able to find them via codereview.

Comment (jkotas) [reply src/coreclr/vm/methodtablebuilder.cpp:8746]: @davidwrighton Do you happen to remember what is the path that needed these dummy GCDescs for collectible types? As far as I can tell, they are not needed.

Comment (davidwrighton) [reply src/coreclr/vm/methodtablebuilder.cpp:8746]: The concern is the behavior of go_through_object. go_through_object with the dummy gcdesc works, but if the gc ever calls go_through_object or go_through_object_nostart without checking ContainsPointers is not safe. (go_through_object_cl is safe as it checks ContainsPointers internally).

At one point we did not reliably have a guarantee that go_through_object would not be hit for objects where Collectible was true, but ContainsPointers is false. Looking at the gc codebase, it appears that it may have been changed to make that  invariant true, but I'm not sufficiently familiar with the logic to be sure. For instance, in mark_object_simple1 there is a use of go_through_object not directly protected with a call to ContainsPointers and the logic isn't completely clear about avoiding use of the go_through_object in that case.

Comment (jkotas) [reply src/coreclr/vm/methodtablebuilder.cpp:8746]: > For instance, in mark_object_simple1 there is a use of go_through_object not directly protected with a call to ContainsPointers and the logic isn't completely clear about avoiding use of the go_through_object in that case.

Yeah, I agree that the logic is not straightforward for this one - but I believe that it still works fine.

I have changed the assert in `GCDesc::GetCGCDescFromMT` to catch the cases where Collectible was true, but ContainsPointers is false. I hope that we are going to hit intermittently it in the CI if there is any corner case that can sneak through.

If we find that the dummy GCDescs have to be there, we will need to generate them for non-canonical generic types.

**Comment by davidwrighton** [comment]
@Maoni0 I'd like you to review the change in particular to tell us if we can expect that go_through_object is never used when Collectible is true but ContainsPointers is false.

**Review by davidwrighton — APPROVED** [review]
This change looks good as long as the GC maintains the invariant around usage of go_through_object. Otherwise, we may need to fix the empty gc desc problem for generics

**Comment by Maoni0** [comment]
the case in `mark_object_simple1` (and `background_mark_simple1`) are covered because we only push the ref onto the stack if it's `ContainsPointersOrCollectible()` is true. and when we pop this off to mark we check if it's collectible and if it is, we check if it containers point and only call `go_through_object` if it does.

**Review by Maoni0 — APPROVED** [review]
