### PR TITLE
align GC memory load calculation on Linux with Docker and Kubernetes

### LINKED ISSUE #63840: Memory load calculation used by GC is not aligned with Docker and Kubernetes
### Description

Current logic in [GetCGroupMemoryUsage](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/gc/unix/cgroup.cpp#L404) to calculate container memory usage from a GC perspective may produce a significantly different value than popular container tools such as Docker and Kubernetes (for example, for the below test application it's about 30% lower than expected).

This can result in containers unnecessarily getting OOM-killed due to the GC not being able to detect high memory pressure.

Both [Docker](https://github.com/docker/cli/blob/6e2838e18645e06f3e4b6c5143898ccc44063e3b/cli/command/container/stats_helpers.go#L230) and [Kubernetes](https://github.com/google/cadvisor/blob/a3b5f4f6c501d5a4ac67530bc973a05c1ebd7d8c/container/libcontainer/handler.go#L836) use a different method: get total memory usage from `memory.usage_in_bytes` and subtract the `total_inactive_file` value of `memory.stat`.

Would it be possible to update .NET implementation to use the same method?

### Reproduction Steps

1. Run `dotnet new console -n MemoryLoadTest` using the latest .NET SDK (6.0.101 at the moment) and add the following code to `Program.cs`:

```C#
var lockObj = new object();

var rnd = new Random();

var cache = new Dictionary<int, int[]>();

Console.WriteLine("Seconds\tMemoryLoadBytes\t\tcache.Count");

var runTimeInSeconds = int.Parse(Environment.GetEnvironmentVariable("RUN_TIME_IN_SECONDS")!);

// Start 1000 threads. Each thread adds a cache item every 5-10s
for (int i = 0; i < 1000; i++)
{
    new Thread(() =>
    {
        while (true)
        {
            int sleepTime;

            lock (lockObj)
            {
                sleepTime = rnd.Next(5000, 10000);

                var cacheItem = new int[10 * 1024];

                cache[cacheItem.GetHashCode()] = cacheItem;
            }

            Thread.Sleep(sleepTime);
        }
    })
    { IsBackground = true }.Start();
}

// Remove random item from cache every 10ms
for (int i = 1; i <= runTimeInSeconds * 100; i++)
{
    lock (lockObj)
    {
        if (cache.Count > 0)
        {
            cache.Remove(cache.Keys.ElementAt(rnd.Next(cache.Count)));
        }

        if (i % 100 == 0)
        {
            Console.WriteLine($"{i / 100}\t{Format(GC.GetGCMemoryInfo().MemoryLoadBytes)}\t{cache.Count}");
        }
    }

    Thread.Sleep(10);
}

Console.WriteLine("Finished successfully!");

string Format(long bytes) => $"{bytes} ({Math.Round((double)bytes / 1024 / 1024, 2)}MiB)";
```
2. Create the following `Dockerfile` in the `MemoryLoadTest` folder:

```dockerfile
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["MemoryLoadTest.csproj", "MemoryLoadTest/"]
RUN dotnet restore "MemoryLoadTest/MemoryLoadTest.csproj"
COPY . "MemoryLoadTest/"
WORKDIR "/src/MemoryLoadTest"
RUN dotnet build "MemoryLoadTest.csproj" -c Release -o /app/build
RUN dotnet tool install --tool-path /tools dotnet-trace

FROM build AS publish
RUN dotnet publish "MemoryLoadTest.csproj" -c Release -o /app/publish --os linux --self-contained true

FROM base AS final
WORKDIR /tools
COPY --from=build /tools .
WORKDIR /app
COPY --from=publish /app/publish .
ENV PATH="${PATH}:/tools"

# copy coreclr build from CORECLR_BUILD_PATH and start dotnet-trace, which will create gc.nettrace in [runtime repository root]/artifacts
ENTRYPOINT ["/bin/sh", "-c" , "if [ \"$CORECLR_BUILD_PATH\" != \"\" ] ; then echo \"copying coreclr from $CORECLR_BUILD_PATH ...\" && cp -r \"$CORECLR_BUILD_PATH/.\" /app/ && echo 'finished copying!' ; fi  && dotnet-trace collect -o /runtime/artifacts/gc.nettrace --profile gc-collect --show-child-io -- dotnet MemoryLoadTest.dll"]
```
3. From `MemoryLoadTest` run `docker build -t memoryloadtest -f Dockerfile .`

4. (Optional) In a separate window run `docker stats` to start monitoring containers.

5. Checkout the latest main branch of the runtime repository.

6. Build the runtime repository (replace [runtime repository root] with local runtime repository path): 

`docker run --rm -v [runtime repository root]:/runtime -w /runtime mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-a50a721-20191120200116 ./build.sh -subset clr -configuration release -clang9`

7. Run the application (replace [runtime repository root] with local runtime repository path):

`docker run -m 165m --memory-swap 165m --name MemoryLoadTest --rm --env RUN_TIME_IN_SECONDS=20 -v [runtime repository root]:/runtime --env CORECLR_BUILD_PATH=/runtime/artifacts/bin/coreclr/Linux.x64.Release -it memoryloadtest`

Observe that the application reaches the memory limit after about 13 seconds and gets OOM-killed. Also `MemoryLoadBytes` is significantly lower than container memory usage reported by `docker stats`:
```
Seconds MemoryLoadBytes         cache.Count
1       81317068 (77.55MiB)     900
2       81317068 (77.55MiB)     800
3       81317068 (77.55MiB)     700
4       81317068 (77.55MiB)     600
5       81317068 (77.55MiB)     581
6       91697971 (87.45MiB)     685
7       102078873 (97.35MiB)    818
8       102078873 (97.35MiB)    912
9       112459776 (107.25MiB)   1000
10      112459776 (107.25MiB)   1001
11      122840678 (117.15MiB)   940
12      122840678 (117.15MiB)   933
13      122840678 (117.15MiB)   958

Trace completed.
Process exited with code '137'.
```
8. Finally, checkout the branch from PR https://github.com/dotnet/runtime/pull/64128 and repeat steps 6-7. The application finishes successfully and `MemoryLoadBytes` is accurate:

```
Seconds MemoryLoadBytes         cache.Count
1       115920076 (110.55MiB)   900
2       115920076 (110.55MiB)   800
3       115920076 (110.55MiB)   700
4       115920076 (110.55MiB)   600
5       115920076 (110.55MiB)   571
6       126300979 (120.45MiB)   680
7       126300979 (120.45MiB)   790
8       134951731 (128.7MiB)    905
9       145332633 (138.6MiB)    1003
10      145332633 (138.6MiB)    1008
11      164364288 (156.75MiB)   956
12      164364288 (156.75MiB)   950
13      155713536 (148.5MiB)    974
14      155713536 (148.5MiB)    1045
15      150523084 (143.55MiB)   1134
16      152253235 (145.2MiB)    1192
17      152253235 (145.2MiB)    1232
18      164364288 (156.75MiB)   1255
19      164364288 (156.75MiB)   1258
20      164364288 (156.75MiB)   1270
Finished successfully!

Trace completed.
Process exited with code '0'.
```
From the output and the generated `gc.nettrace` file in `[runtime repository root]/artifacts` for the second run we can confirm that there was a full blocking collection due to low memory, which allowed the application to keep executing without hitting the memory limit.

### Expected behavior

The application finishes successfully and doesn't get OOM-killed.

### Actual behavior

The application gets OOM-killed.

### Regression?

Not a regression.

### Known Workarounds

Playing with `GCHighMemPercent` or similar settings can provide a short-term workaround in some cases.

### Configuration

.NET 5/6 running in Linux container on Docker or Kubernetes.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by dennis-yemelyanov**
The goal of this PR is to fix an issue where memory load calculation used by .NET can produce significantly different values than popular container tools such as Docker and Kubernetes, causing containers to run out of memory and be killed.

Fix #63840

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=64128) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=64128) before we can accept your contribution.<br/><br/>:x: dennis-yemelyanov [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=64128)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=64128) it.</sub>

**Comment by mangod9** [comment]
Thanks for your contribution @dennis-yemelyanov. The approach looks reasonable, but we will need to evaluate if this works generically for non container scenarios, else we will need to special such logic.

**Comment by dennis-yemelyanov** [comment]
thank you @mangod9 . Yeah my initial understanding was that this code is only used by containers, but if not and the approach looks good otherwise, I'm happy to look more at other flows that might be affected by this change

**Comment by mangod9** [comment]
Perhaps @janvorli and @tmds can determine the best approach here. Perhaps we will need to add a config switch to toggle the behavior?

**Comment by dennis-yemelyanov** [comment]
I did some digging and confirmed (from the code and by testing the same program) that this change doesn't affect non-container execution.

Basically, the method being modified `GetCGroupMemoryUsage` is only called (through `GetPhysicalMemoryUsed`) from `GCToOSInterface::GetMemoryStatus` and only if `restricted_limit` is set: https://github.com/dotnet/runtime/blob/69b9000671f1b73b3fa17810a9f6cb31abb612a2/src/coreclr/gc/unix/gcenv.unix.cpp#L1326
`restricted_limit` is only set to a non-zero value if `is_restricted_physical_mem` is set to `true` in [gc.cpp](https://github.com/dotnet/runtime/blob/69b9000671f1b73b3fa17810a9f6cb31abb612a2/src/coreclr/gc/gc.cpp). And this seems possible in only 2 cases:
1. Running in containers - the scenario that this PR is trying to fix.
2. If GC config `GCTotalPhysicalMemory` is set. However I'm not sure if this is a valid scenario since this config is not documented [here](https://docs.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector) and when I run the test program with this config set to some limit, even with the latest .NET release it seems to be broken (reports `MemoryLoadBytes` significantly higher than this limit, and the program still finishes successfully).

**Comment by tmds** [comment]
@dennis-yemelyanov the sum we're making now was meant to be an estimate of _usage - inactive_.

I don't mind calculating it as a subtraction, though it requires opening two files instead of one.

I also wonder if there are fields from `memory.stat` we could add to the sum, that would make it more accurate. The reported issue mentions:

> (for example, for the below test application it's about 30% lower than expected).

Do you know what `memory.stat` fields may account for this 30%?

**Comment by dennis-yemelyanov** [comment]
thank you @tmds for looking into it. I think kernel memory might not be reported anywhere in `memory.stat`. I just tried getting it from `memory.kmem.usage_in_bytes`, and adding it to current values read in `memory.stat` does produce a value that is closer to `memory.usage_in_bytes` - `inactive_file`.

In the test program mentioned in the issue `memory.kmem.usage_in_bytes` reports about 33MiB. But this is just one of potential factors that can contribute to the difference (I haven't done a lot of research about other factors).

If performance is the main concern with reading 2 files, would it be helpful to profile it to measure if there is a significant overhead from reading the second file? (I believe technically these are not even real files, but just file-like abstractions that should have much lower overhead than opening real files)

**Comment by tmds** [comment]
The important thing is correctness. If there is no way to calculate the value from the `memory.stat` fields, we need to read the `usage` separate.

**Comment by dennis-yemelyanov** [comment]
yeah I don't know any way to get the same information from `memory.stat` only. I think that might also be why other container tools read `usage_in_bytes` as well

File: src/coreclr/gc/unix/cgroup.cpp [hunk 1]
```diff
@@ -68,18 +70,13 @@ class CGroup
 
         if (s_cgroup_version == 1)
         {
-            s_mem_stat_n_keys = 4;
-            s_mem_stat_key_names[0] = "total_inactive_anon ";
-            s_mem_stat_key_names[1] = "total_active_anon ";
-            s_mem_stat_key_names[2] = "total_dirty ";
-            s_mem_stat_key_names[3] = "total_unevictable ";
+            s_mem_stat_n_keys = 1;
```
Comment (tmds) [inline src/coreclr/gc/unix/cgroup.cpp:73]: Because we're only reading a single field, we no longer need this array. Can you refactor the code?

Comment (dennis-yemelyanov) [reply src/coreclr/gc/unix/cgroup.cpp]: thank you, removed the code that is no longer used

File: src/coreclr/gc/unix/cgroup.cpp [hunk 2]
```diff
@@ -59,30 +59,19 @@ class CGroup
 
     static char *s_memory_cgroup_path;
 
-    static const char *s_mem_stat_key_names[];
-    static size_t s_mem_stat_key_lengths[];
-    static size_t s_mem_stat_n_keys;
+    static char *s_mem_stat_inactive_file_key_name;
```
Comment (janvorli) [inline src/coreclr/gc/unix/cgroup.cpp:62]: Can you please keep this a `const char*`? Then you don't need the casts of string literals below to `char*`.

File: src/coreclr/gc/unix/cgroup.cpp [hunk 3]
```diff
@@ -444,43 +433,36 @@ class CGroup
...
     }
 };
 
 int CGroup::s_cgroup_version = 0;
 char *CGroup::s_memory_cgroup_path = nullptr;
 
-const char *CGroup::s_mem_stat_key_names[1] = {};
-size_t CGroup::s_mem_stat_key_lengths[1] = {};
-size_t CGroup::s_mem_stat_n_keys = 0;
+char *CGroup::s_mem_stat_inactive_file_key_name = nullptr;
```
Comment (janvorli) [inline src/coreclr/gc/unix/cgroup.cpp:464]: Can you please keep this as `const char*` too?

File: src/coreclr/pal/src/misc/cgroup.cpp [hunk 4]
```diff
@@ -651,9 +634,8 @@ int CGroup::s_cgroup_version = 0;
 char *CGroup::s_memory_cgroup_path = nullptr;
 char *CGroup::s_cpu_cgroup_path = nullptr;
 
-const char *CGroup::s_mem_stat_key_names[1] = {};
-size_t CGroup::s_mem_stat_key_lengths[1] = {};
-size_t CGroup::s_mem_stat_n_keys = 0;
+char *CGroup::s_mem_stat_inactive_file_key_name = nullptr;
```
Comment (janvorli) [inline src/coreclr/pal/src/misc/cgroup.cpp:637]: Can you please keep this as `const char*` too?

File: src/coreclr/gc/unix/cgroup.cpp [hunk 5]
```diff
@@ -417,43 +433,36 @@ class CGroup
 
         char *line = nullptr;
         size_t lineLen = 0;
-        size_t readValues = 0;
+        bool foundInactiveFileValue = false;
         char* endptr;
 
-        *val = 0;
-        while (getline(&line, &lineLen, stat_file) != -1 && readValues < s_mem_stat_n_keys)
+        *val = usage;
```
Comment (dennis-yemelyanov) [inline src/coreclr/gc/unix/cgroup.cpp:439]: I assume it's fine that `val` will be set to some value even if this method returns `false`? From the calling code looks like it shouldn't matter, and the currently version of this method follows the same pattern. If we want to return 0 in case of errors, I can add a temporary variable

Comment (janvorli) [reply src/coreclr/gc/unix/cgroup.cpp:439]: The preferable behavior would be to not to set the output variable at all (not even to 0) if the method is returning false.

Comment (dennis-yemelyanov) [reply src/coreclr/gc/unix/cgroup.cpp]: sounds good, updated to not set it in this case

**Comment by dennis-yemelyanov** [comment]
thank you everyone for helping to review this change and providing all the feedback so far! If there are any additional concerns or any other tests I can do, I'll be happy to look more into it.

So far I have run the test program with the following configurations on Ubuntu 20.04:
- cgroup v1 (default) - works as expected
- cgroup v2 (had to enable it explicitly) - works as expected
- no containers, just running directly on host - no change in behavior

**Comment by dennis-yemelyanov** [comment]
If there are no other concerns can this PR be merged?

We would really appreciate this since it would help us avoid OOM kills and make our services more stable

**Comment by dennis-yemelyanov** [comment]
> it would be better to tweak the memory config so the managed heap can take care of its own without relying on cgroup limit triggers

Yes, these are valid suggestions, it’s just that we are really tight on budget and system resources… So increasing container memory and/or reducing max heap size are not our first choices (also I should probably mention that in our real production  application we have a lot more memory than in the test application mentioned in the issue, and the difference between the current and new calculation methods can easily be a few GB sometimes)

File: src/coreclr/gc/unix/cgroup.cpp [hunk 6]
```diff
@@ -113,9 +99,9 @@ class CGroup
         if (s_cgroup_version == 0)
             return false;
         else if (s_cgroup_version == 1)
-            return GetCGroupMemoryUsage(val);
+            return GetCGroupMemoryUsage(val, CGROUP1_MEMORY_USAGE_FILENAME);
```
Comment (tmds) [inline src/coreclr/gc/unix/cgroup.cpp:102]: Can you remove `s_mem_stat_inactive_file_key_name`/`s_mem_stat_inactive_file_key_length` and pass it as `CGROUP1_MEMORY_STAT_INACTIVE_FIELD`/`CGROUP2_MEMORY_STAT_INACTIVE_FIELD` similar to the other defines?

To get the length you can use `strlen` inside `GetCGroupMemoryUsage`. It is cheap compared to all the other stuff that goes on.

Comment (tmds) [reply src/coreclr/gc/unix/cgroup.cpp:102]: @dennis-yemelyanov can you clean this up?

Comment (dennis-yemelyanov) [reply src/coreclr/gc/unix/cgroup.cpp:102]: yes, sorry, got distracted with another important project, hoping to return to this in a few days and complete this refactoring

**Comment by tmds** [comment]
> based on the recent comments assume there is some changes required for this?

Yes, only some small cleanup suggestions.

**Comment by mangod9** [comment]
Hi @dennis-yemelyanov, checking in if you plan to update the PR with required changes?

File: src/coreclr/gc/unix/cgroup.cpp (hunk 6 above)
Comment (dennis-yemelyanov) [reply src/coreclr/gc/unix/cgroup.cpp]: made a change to remove these fields

**Comment by dennis-yemelyanov** [comment]
PR has been updated to address the latest comments. Please let me know if any other changes are needed

**Comment by akoeplinger** [comment]
@tmds @mangod9 would you mind taking another look at this PR?

**Review by mangod9 — APPROVED** [review]

**Comment by mangod9** [comment]
this looks good to me, @janvorli @tmds could you please take a look too?

**Review by janvorli — APPROVED** [review]
LGTM, thank you!
