### PR TITLE
[libraries][iOS][tvOS] Skip RoundtripEmptyArray on older tvOS iOS ver…

### LINKED ISSUE #52199: [iOS][tvOS] System.Security.Cryptography RoundtripEmptyArray flakes on iOS/tvOS
These tests haven't failed locally based on `b491d634bb7`, but have failed on CI in the three lanes of the same run.
https://dev.azure.com/dnceng/public/_build/results?buildId=1118648&view=logs&j=e4e455c5-b032-5051-d2c5-a64982c9ac45&t=0263a457-10d3-5b56-3414-171b09292e09
https://dev.azure.com/dnceng/public/_build/results?buildId=1118648&view=logs&j=accacb66-0a14-52ef-4079-6344686d9d4c&t=34fbd35e-866b-51a1-9063-fb50703b1957
https://dev.azure.com/dnceng/public/_build/results?buildId=1118648&view=logs&j=60bb76d0-1552-55d1-167a-0040a91a2806&t=0bd88bfe-5770-5552-db3f-b8a830860b26

```
System.Security.Cryptography.Csp.Tests.dll   Failed: 2
Test collection for System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span.RoundtripEmptyArray
    Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - RSAdecrypt wrong input (err -1))
Test collection for System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array.RoundtripEmptyArray
    Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - RSAdecrypt wrong input (err -1))


System.Security.Cryptography.Algorithms.Tests.dll   Failed: 2
Test collection for System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span.RoundtripEmptyArray
    Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - RSAdecrypt wrong input (err -1))
Test collection for System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array.RoundtripEmptyArray
    Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - RSAdecrypt wrong input (err -1))
```

### PR DESCRIPTION
**Pull request by mdh1418**
…sions

Fixes https://github.com/dotnet/runtime/issues/52199

Locally checked the test passed on iOS 13.6 and tvOS 14.0
Locally did not have any simulator versions between tvOS 13.4 and 14.0 on my xcode.

### CODE REVIEW

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs [hunk 1]
```diff
@@ -336,11 +337,18 @@ private void RsaCryptRoundtrip(RSAEncryptionPadding paddingMode, bool expectSucc
             Assert.Equal(TestData.HelloBytes, output);
         }
 
-        [Fact]
+        [ConditionalFact]
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs:340]: Seems like this should stay as just Fact, as no conditions are applied.

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs [hunk 2]
```diff
@@ -336,11 +337,18 @@ private void RsaCryptRoundtrip(RSAEncryptionPadding paddingMode, bool expectSucc
...
         public void RoundtripEmptyArray()
         {
+            if (PlatformDetection.IsiOS && !OperatingSystem.IsIOSVersionAtLeast(13, 6))
+            {
+                throw new SkipTestException("This test is broken on <iOS 13.6");
+            }
+            if (PlatformDetection.IstvOS && !OperatingSystem.IsTvOSVersionAtLeast(14, 0))
+            {
+                throw new SkipTestException("This test is broken on <tvOS 14.0");
+            }
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs:351]:
```suggestion
            }
            
```

(blank line after, please)

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs [hunk 3]
```diff
@@ -336,11 +337,18 @@ private void RsaCryptRoundtrip(RSAEncryptionPadding paddingMode, bool expectSucc
...
 
-        [Fact]
+        [ConditionalFact]
         [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework)]
-        [ActiveIssue("https://github.com/dotnet/runtime/issues/52199", TestPlatforms.iOS | TestPlatforms.tvOS | TestPlatforms.MacCatalyst)]
         public void RoundtripEmptyArray()
         {
+            if (PlatformDetection.IsiOS && !OperatingSystem.IsIOSVersionAtLeast(13, 6))
+            {
+                throw new SkipTestException("This test is broken on <iOS 13.6");
```
Comment (vcsjones) [inline src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs:346]: Can we somehow make “broken” a bit more clear that this is expected rather than a limitation of the test?

```suggestion
                throw new SkipTestException("iOS prior to 13.6 does not reliably support RSA encryption of empty data.");
```

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs (hunk 1 above)
Comment (mdh1418) [reply src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs:340]: It needs to be a `ConditionalFact` to catch the `SkipTestException` and turn the test into an ignored test.

Fact
```
<test name="System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span.RoundtripEmptyArray" type="System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span" method="RoundtripEmptyArray" time="0.0002629" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : This test is broken on <iOS 13.6]]></message>
    <stack-trace><![CDATA[   at System.Security.Cryptography.Rsa.Tests.EncryptDecrypt.RoundtripEmptyArray() in System.Security.Cryptography.Algorithms.Tests.dll:token 0x600042e+0x26
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004fa1+0x96]]></stack-trace>
  </failure>
</test>
```
ConditionalFact
```
<test name="System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span.RoundtripEmptyArray" type="System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span" method="RoundtripEmptyArray" time="0" result="Skip">
  <reason><![CDATA[This test is broken on <iOS 13.6]]></reason>
</test>
```

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs (hunk 2 above)
Comment (mdh1418) [reply src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs:351]: Thanks!

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs (hunk 3 above)
Comment (mdh1418) [reply src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs]: Done!

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs [hunk 4]
```diff
@@ -336,11 +337,19 @@ private void RsaCryptRoundtrip(RSAEncryptionPadding paddingMode, bool expectSucc
             Assert.Equal(TestData.HelloBytes, output);
         }
 
-        [Fact]
+        [ConditionalFact]
         [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework)]
-        [ActiveIssue("https://github.com/dotnet/runtime/issues/52199", TestPlatforms.iOS | TestPlatforms.tvOS | TestPlatforms.MacCatalyst)]
         public void RoundtripEmptyArray()
         {
+            if (PlatformDetection.IsiOS && !OperatingSystem.IsIOSVersionAtLeast(13, 6))
```
Comment (akoeplinger) [inline src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs:344]: nit: use the `OperatingSystem` API directly rather than going through the `PlatformDetection` helper:

```suggestion
            if (OperatingSystem.IsIOS() && !OperatingSystem.IsIOSVersionAtLeast(13, 6))
```

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs [hunk 5]
```diff
@@ -336,11 +337,19 @@ private void RsaCryptRoundtrip(RSAEncryptionPadding paddingMode, bool expectSucc
...
+            {
+                throw new SkipTestException("iOS prior to 13.6 does not reliably support RSA encryption of empty data.");
+            }
+            if (PlatformDetection.IstvOS && !OperatingSystem.IsTvOSVersionAtLeast(14, 0))
```
Comment (akoeplinger) [inline src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs:348]:
```suggestion
            if (OperatingSystem.IsTvOS() && !OperatingSystem.IsTvOSVersionAtLeast(14, 0))
```

**Review by akoeplinger — APPROVED** [review]

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs (hunk 4 above)
Comment (mdh1418) [reply src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs]: Thanks, in other scenarios where we do use `PlatformDetection.Is*` why wouldn't we want to directly use `OperatingSystem` instead?

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs (hunk 5 above)
Comment (mdh1418) [reply src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs]: Done!

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs (hunk 4 above)
Comment (akoeplinger) [reply src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs]: If there's an equivalent API in `OperatingSystem` I'd always use that one, it's mostly historical reasons we're not doing it right now since `PlatformDetection` was added much earlier than `OperatingSystem`.

File: src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs (hunk 1 above)
Comment (bartonjs) [reply src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/EncryptDecrypt.cs:340]: Huh.  Alright then.

**Review by bartonjs — APPROVED** [review]
