### PR TITLE
[wasm][debugger] Debuger tests refactor 63667

### LINKED ISSUE #63667: [wasm][debugger] Refactor tests to use existing, complex test classes
Try to reduce the number of test classes used only in one test, e.g. 

- [x]  see if property checking in struct getters can be done the same way as for autoexpandable getters:
```
TGetter("foo", TString("value"))
```
- [x] remove [TestClass](https://github.com/dotnet/runtime/blob/35f85119045bbd4a8afc5647d3f123c1c6ebdc48/src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs#L823) and try to use something from  e.g. debugger-get-properties-test.cs
- [x] after replacing TestClass with DerivedClass, with more complex fields a bug in InvokeMethod was found. The bug was caused by deciding if method should be invoked as Class or Value type by checking if value of a given objectId exists in valueTypes collection. For overriden objects that should be resolved as Class, it resulted in resolving as ValueType and an exception was thrown. To fix it, ElementType field was re-added to DotnetObjectId class - it solved the problem.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes #63667, see the Issue for description.
The PR also adds logging the error thrown in RuntimeGetPropertiesInternal as it was the information I frequently lacked when debugging.

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs [hunk 1]
```diff
@@ -92,6 +93,9 @@ public static bool TryParse(string id, out DotnetObjectId objectId)
                         parts = id.Split(":");
                         if (parts.Length > 3)
                             objectId.SubValue = int.Parse(parts[3]);
+                        ElementType et;
+                        Enum.TryParse(parts[4], out et);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:97]: When using `Try*` methods, we should check for the return value to see if it actually succeeded. In this case, if it returns `false`, then return `false` from the method.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 2]
```diff
@@ -781,7 +781,9 @@ internal async Task<JToken> RuntimeGetPropertiesInternal(SessionId id, DotnetObj
 
                 }
             }
-            catch (Exception) {
+            catch (Exception ex)
+            {
+                logger.LogDebug($"Error on getting properties of object {objectId} with scheme {objectId.Scheme}. {ex.Message}.");
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:786]: For debugging, the full stack trace would be more useful.
```suggestion
                logger.LogDebug($"Error on getting properties of object {objectId} with scheme {objectId.Scheme}. {ex}.");
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 3]
```diff
@@ -1588,11 +1588,10 @@ public async Task<JObject> InvokeMethod(ArraySegment<byte> valueTypeBuffer, int
             return await CreateJObjectForVariableValue(retDebuggerCmdReader, varName, false, -1, false, token);
         }
 
-        public async Task<JObject> InvokeMethodInObject(int objectId, int methodId, string varName, CancellationToken token)
+        public async Task<JObject> InvokeMethodInObject(int objectId, int methodId, ElementType elementType, string varName, CancellationToken token)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1591]: What we need to know here really is whether the objectId is for a valuetype or not. Use a `bool isValueType` instead.

File: src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs [hunk 4]
```diff
@@ -66,6 +66,7 @@ internal class DotnetObjectId
         public string Scheme { get; }
         public int Value { get; }
         public int SubValue { get; set; }
+        public ElementType ElementType { get; set; }
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:69]: Is the `ElementType` in the `methodId` used for anything other than valuetype/class differentiation? We should just add a bool, or simple `0/1` instead of the elementType to the `methodId`. And then expose a `public bool IsValueType { get; }` property here.

Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/DevToolsHelper.cs:69]: It's used only for that, bool will do the job as well.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 5]
```diff
@@ -1588,11 +1588,10 @@ public async Task<JObject> InvokeMethod(ArraySegment<byte> valueTypeBuffer, int
             return await CreateJObjectForVariableValue(retDebuggerCmdReader, varName, false, -1, false, token);
         }
 
-        public async Task<JObject> InvokeMethodInObject(int objectId, int methodId, string varName, CancellationToken token)
+        public async Task<JObject> InvokeMethodInObject(int objectId, int methodId, bool isValueType, string varName, CancellationToken token)
```
Comment (lewing) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1591]: Is there a reason not to make the first argument a DotnetObjectId then check isValueType in the body rather than passing two arguments?

Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1591]: No, we can change.

**Review by lewing — APPROVED** [review]
