### PR TITLE
Always append the "dll" extension for native libraries loads on Windows

### LINKED ISSUE #66608: [DllImport] on Windows fails to load library on case sensitive filesystem
### Description

[DllImport] on Windows fails to load library on case sensitive filesystem
System:  Windows 10 (21H1)
.net version: 6.0
File system: NTFS with SetCaseSensitiveInfo enabled

### Reproduction Steps

1. have Windows with case sensitive filesystem: `fsutil.exe file SetCaseSensitiveInfo C:\folder\path enable`
2. have `somelibrary.dll` - note all letters are lower case
3. use `[DllImport("somelibrary")]` **without** specifying extension
4. run project

### Expected behavior

Project correctly loads `somelibrary.dll`.

### Actual behavior

Project fails with exception:
`DllNotFoundException: Unable to load DLL 'somelibrary' or one of its dependencies: The specified module could not be found. (0x8007007E)`

### Regression?

_No response_

### Known Workarounds

Rename library to `somelibrary.DLL`.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #66608 

Due to case-sensitive file systems on Windows the runtime will now always append the ".dll" extension unless the name contains a trailing "." or a known loadable extension. This is an attempt to mitigate the default Windows behavior that appends a ".DLL" which is rarely the casing used for Windows shared libraries.

Documentation PR to follow.

/cc @dotnet/interop-contrib

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
My cursory look in Mono indicates they do not suffer from this issue. @lambdageek can you confirm my understanding of the following code:

https://github.com/dotnet/runtime/blob/ba5a5820fd1803f96713530dc1701888f846a93a/src/mono/mono/metadata/native-library.c#L492-L510

**Comment by jkotas** [comment]
Does https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/LibraryNameVariation.Windows.cs need fixing to be in sync?

**Comment by AaronRobinsonMSFT** [comment]
> Does https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/LibraryNameVariation.Windows.cs need fixing to be in sync?

Yes. I don't think how this was done makes a lot of sense. Having this code duplication logic is a recipe for failure. Thanks for pointing it out.

**Comment by jkoritzinsky** [comment]
Based on commit history, the duplicate implementation in managed is used by NativeAOT.

**Comment by lambdageek** [comment]
> My cursory look in Mono indicates they do not suffer from this issue. @lambdageek can you confirm my understanding of the following code:

Mono will probe for several different variations on the name - first as given, then with the `mono_dl_get_so_suffixes` suffixes (`".dll"` on Windows - lowercase), and also with a prefix `mono_dl_get_so_prefix ()` (`""` on Windows)- until it finds a name that works.

So I agree - I don't think Mono is affected.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/nativelibrary.cpp [hunk 1]
```diff
@@ -574,21 +576,16 @@ namespace
...
         int varCount = 0;
 
-        // The purpose of following code is to workaround LoadLibrary limitation:
-        // LoadLibrary won't append extension if filename itself contains '.'. Thus it will break the following scenario:
-        // [DllImport("A.B")] // The full name for file is "A.B.dll". This is common code pattern for cross-platform PInvoke
-        // The workaround for above scenario is to call LoadLibrary with "A.B" first, if it fails, then call LoadLibrary with "A.B.dll"
+        // The runtime will always append the '.dll' extension unless the name ends with a "."
+        // or with an existing known extension. This is done due to issues with case-sensitive file systems
+        // on Windows that only search for ".DLL" as opposed to the more common ".dll".
         auto it = libName.Begin();
```
Comment (elinor-fung) [inline src/coreclr/vm/nativelibrary.cpp:582]: Not used anymore.

File: src/coreclr/vm/nativelibrary.cpp [hunk 2]
```diff
@@ -574,21 +576,16 @@ namespace
...
-        if (!libNameIsRelativePath ||
```
Comment (elinor-fung) [inline src/coreclr/vm/nativelibrary.cpp:582]: Why don't we care about relative versus absolute path anymore? It seems inconsistent with other platforms where we say if you give us an absolute path, we expect that is exactly what you want, so that is what we are using.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/nativelibrary.cpp:582]: I was trying to be as forgiving as possible, but your point is well-taken. I didn't see any of these guarantees in the `DllImport` doc so didn't really consider that point-of-view. The addition of extension seems to be a Windows loader feature that isn't part of `dlopen` so always adding it on Windows to handle the case-sensitive scenario and be consistent was prudent in my mind. Does that change your opinion or is keeping this consistent preferred?

Comment (elinor-fung) [reply src/coreclr/vm/nativelibrary.cpp:582]: Doesn't the Windows loader only add the extension if the name is specified without the path? At least that is what the doc says - I did not actually check the behaviour.

Comment (jkoritzinsky) [reply src/coreclr/vm/nativelibrary.cpp:582]: Related to this conversation, we should document the probing behavior we have on each platform for the next time we have to look at this: https://github.com/dotnet/runtime/issues/4596

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/nativelibrary.cpp:582]: > Doesn't the Windows loader only add the extension if the name is specified without the path? At least that is what the doc says - I did not actually check the behaviour.

You would think. That is one of those behaviors I've mentioned in the past. Using ProcMon, you can see that if one supplies `C:\Users\foo`, probing will be for `C:\Users\foo.DLL`.

Comment (elinor-fung) [reply src/coreclr/vm/nativelibrary.cpp:582]: Ech. I would still prefer the consistency though.

I think of the variation / extension probing as mainly helpful for cross-platform - otherwise you could just put in the full name. If you are using an absolute path, I would think it is unlikely you are doing it cross-plat. To me, adding the probing on Windows for absolute paths adds inconsistency in our cross-plat behaviour while not really unblocking users.

Comment (elinor-fung) [reply src/coreclr/vm/nativelibrary.cpp:582]: We also call out that we don't do anything to absolute paths in https://docs.microsoft.com/dotnet/standard/native-interop/cross-platform

File: src/coreclr/vm/nativelibrary.cpp [hunk 3]
```diff
@@ -574,26 +576,19 @@ namespace
...
-            !libName.Find(it, W('.')) ||
-            libName.EndsWith(W(".")) ||
-            libName.EndsWithCaseInsensitive(W(".dll")) ||
-            libName.EndsWithCaseInsensitive(W(".exe")))
+        // Follow LoadLibrary rules in MSDN doc: https://docs.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya
+        // To prevent the function from appending ".DLL" to the module name, include a trailing point character (.) in the module name string
+        // or provide an absolute path.
+        libNameVariations[varCount++] = NameFmt;
+
+        // The runtime will append the '.dll' extension if the path is relative and the name doesn't ends with a "."
```
Comment (jkotas) [inline src/coreclr/vm/nativelibrary.cpp:584]:
```suggestion
        // The runtime will append the '.dll' extension if the path is relative and the name doesn't end with a "."
```

File: src/tests/Loader/AssemblyDependencyResolver/AssemblyDependencyResolverTests/NativeDependencyTests.cs [hunk 4]
```diff
@@ -174,21 +174,22 @@ public void TestFullPathLookupWithMatchingFileName()
...
+            ValidateFullPathNativeLibraryResolutions("lib{0}.so", "{0}", OS.None);
+            ValidateFullPathNativeLibraryResolutions("lib{0}.dll", "{0}.dll", OS.None);
+            ValidateFullPathNativeLibraryResolutions("lib{0}.dylib", "{0}.dylib", OS.None);
+            ValidateFullPathNativeLibraryResolutions("lib{0}.so", "{0}.so", OS.None);
         }
 
         [Flags]
         private enum OS
         {
+            None = 0,
```
Comment (elinor-fung) [inline src/tests/Loader/AssemblyDependencyResolver/AssemblyDependencyResolverTests/NativeDependencyTests.cs:192]: ❤️

**Review by elinor-fung — APPROVED** [review]

**Comment by saul** [comment]
Not sure if you were planning on updating it anyway, but this page will definitely need changing: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/cross-platform
