### PR TITLE
[wasm] stop using mmap/munmap

### LINKED ISSUE #107215: [wasm] New failure condition introduced by anonymous mmap implementation
The new anonymous mmap implementation ( https://github.com/dotnet/runtime/pull/101871 ) which replaces emscripten's mmap (malloc wearing a fancy hat) introduces a new failure scenario that wouldn't have failed before:

1. Allocate ~2GB of managed objects
2. Release the objects
3. Force SGen to collect garbage enough so that it releases all the now-unnecessary pages it allocated. (It's possible it doesn't actually do this correctly right now...)
4. Try to malloc 1gb of memory

In the old emscripten mmap, all sgen mmap operations and native malloc calls are all serviced by malloc under the hood, so "pages" released by munmap become available to mmap.

In the new mmap, these pages remain controlled by mmap, so emscripten malloc can't use them since it doesn't overlay on top of a real mmap implementation.

At present the workaround for this would be to disable the new mmap implementation for your application (there is a runtime option). In the long run I think the fix is to stop using emscripten malloc, and ship our own dlmalloc or mimalloc that sits on top of our mmap.

### PR DESCRIPTION
**Pull request by pavelsavara**
Contributes to https://github.com/dotnet/runtime/issues/108510
Fixes https://github.com/dotnet/runtime/issues/107215

# Context

- `sgen` GC is using `mono_valloc` -> `mmap` on all other platforms.
- `mmap` emulator in emscripten and `wasi-libc` doens't implement partial `munmap` 
    - It's implemented on top of `malloc` rather than on top of `sbrk`. 
    - It has large alignment overhead and no added value.
- We have [our own implementation](https://github.com/dotnet/runtime/pull/101871) of custom `mmap` 
    - which can do partial `munmap`
    - but it [never releases](https://github.com/dotnet/runtime/issues/107215) pages back to `malloc` pool.
- wasm could only grow, we can't return pages to OS/browser
- wasm32 adress space is rather small and could get fragmented easily

# Changes
- set `MS_BLOCK_ALLOC_NUM` to `1` which prevents `sgen` from doing partial `mono_vfree`
- set `LOCK_FREE_ALLOC_SB_MAX_SIZE` to `16384 * 32` to compensate for above
- `sgen_los_memory_usage_total` is accounting for alignment
- implement `mono_vfree` using `dlfree`
- implement `mono_valloc_aligned` and `mono_valloc` using `posix_memalign`
    - emscripten `sys_alloc` implementation will stitch last segment to new memory allocated via `sbrk`
- avoids emscripten `mmap` which always calls `memset` to zero the memory
    - this PR brings optimization that new pages which are received from `sbrk` don't need that.
    - also some calls to `mono_valloc` pass `MONO_MMAP_NOZERO`
- removes `mono-wasm-pagemgr.c` and `wasm-mmap` option

# TODO 
- [x] measure startup performance

image

### CODE REVIEW

File: src/mono/mono/sgen/sgen-marksweep.c [hunk 1]
```diff
@@ -49,7 +49,13 @@ static int ms_block_size;
  * Don't allocate single blocks, but alloc a contingent of this many
  * blocks in one swoop.  This must be a power of two.
  */
+#ifndef TARGET_WASM
 #define MS_BLOCK_ALLOC_NUM	32
+#else
+// WASM doesn't support partial munmap, so we can't free individual blocks
+// we use posix_memalign and free the whole block at once
+#define MS_BLOCK_ALLOC_NUM	1
```
Comment (kg) [inline src/mono/mono/sgen/sgen-marksweep.c:57]: we should investigate whether this will meaningfully regress performance; mwpm caused a benchmark regression that was fairly sizable

File: src/mono/mono/utils/lock-free-alloc.h [hunk 2]
```diff
@@ -45,11 +45,7 @@ typedef struct {
 	MonoMemAccountType account_type;
 } MonoLockFreeAllocator;
 
-#ifdef HOST_WASM
-#define LOCK_FREE_ALLOC_SB_MAX_SIZE					(mono_opt_wasm_mmap ? 65536 : 16384)
-#else
 #define LOCK_FREE_ALLOC_SB_MAX_SIZE					16384
```
Comment (kg) [inline src/mono/mono/utils/lock-free-alloc.h:48]: we need a solution for the 16 vs 64k problem here since the system page size is still 64kb right now

File: src/mono/mono/utils/mono-mmap-wasm.c [hunk 3]
```diff
@@ -37,22 +35,7 @@
...
-
-	// Prefer sysconf () as it's signal safe.
-#if defined (HAVE_SYSCONF) && defined (_SC_PAGESIZE)
-	saved_pagesize = sysconf (_SC_PAGESIZE);
-#else
-	saved_pagesize = getpagesize ();
-#endif
-
-	return saved_pagesize;
+	return 16384;
```
Comment (kg) [inline src/mono/mono/utils/mono-mmap-wasm.c:38]: we should make sure it's actually okay to lie here

File: src/mono/mono/utils/mono-mmap-wasm.c [hunk 4]
```diff
@@ -96,125 +79,48 @@ mono_setmmapjit (int flag)
...
-		if (mono_opt_wasm_mmap)
-			mwpm_free_range (addr, length);
-		else
-			munmap (addr, length);
-		END_CRITICAL_SECTION;
-	}
-
-	mono_account_mem (type, -(ssize_t)length);
-
+	// NOTE: this doesn't implement partial freeing like munmap does
```
Comment (kg) [inline src/mono/mono/utils/mono-mmap-wasm.c:121]: it would be ideal if we could detect attempted partial free here. i don't know if sgen is the only caller that can try to do a partial unmap

File: src/mono/mono/utils/mono-mmap-wasm.c [hunk 5]
```diff
@@ -267,6 +173,9 @@ mono_file_unmap (void *addr, void *handle)
 int
 mono_mprotect (void *addr, size_t length, int flags)
 {
+	if (flags & MONO_MMAP_DISCARD) {
```
Comment (kg) [inline src/mono/mono/utils/mono-mmap-wasm.c:176]: good catch

File: src/mono/mono/utils/mono-mmap-wasm.c [hunk 6]
```diff
@@ -96,125 +79,48 @@ mono_setmmapjit (int flag)
...
-		else
-			munmap (addr, length);
-		END_CRITICAL_SECTION;
-	}
-
-	mono_account_mem (type, -(ssize_t)length);
-
+	// NOTE: this doesn't implement partial freeing like munmap does
+	// we set MS_BLOCK_ALLOC_NUM to 1 to avoid partial freeing
+	g_free (addr);
```
Comment (kg) [inline src/mono/mono/utils/mono-mmap-wasm.c:123]: this is definitely an improvement over the old state of things, since g_free is dlfree and that performs way better than emscripten munmap

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 3 above)
Comment (kg) [reply src/mono/mono/utils/mono-mmap-wasm.c:38]: this will improve the state of things by making pagesize not > the max block size, but the design of sgen is optimized for a base page size in the 4-8K range so that it can start with smaller blocks and then step up to larger blocks. i think with a page size of 16K it will always allocate only large blocks, and that might be bad? i'm not sure.

File: src/mono/mono/utils/lock-free-alloc.h (hunk 2 above)
Comment (pavelsavara) [reply src/mono/mono/utils/lock-free-alloc.h:48]: does `sbrk()` page size matter in any way ? Why ?

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 4 above)
Comment (pavelsavara) [reply src/mono/mono/utils/mono-mmap-wasm.c:121]: if unit tests pass we are golden :)

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 3 above)
Comment (pavelsavara) [reply src/mono/mono/utils/mono-mmap-wasm.c:38]: We can change it down to 4K, I think

File: src/mono/mono/utils/lock-free-alloc.h (hunk 2 above)
Comment (kg) [reply src/mono/mono/utils/lock-free-alloc.h:48]: i think it might be fine with the combination of all the changes you made, but mono_pagesize not agreeing with other sources of page size information feels like a hazard down the road

Comment (pavelsavara) [reply src/mono/mono/utils/lock-free-alloc.h:48]: what would be the other sources which could conflict ?

**Comment by pavelsavara** [comment]
@radekdoulik could you please run startup benchmark on this PR ? Many thanks

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 4 above)
Comment (pavelsavara) [reply src/mono/mono/utils/mono-mmap-wasm.c:121]: CI tests passed fine. I would not worry about this too much.

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 3 above)
Comment (pavelsavara) [reply src/mono/mono/utils/mono-mmap-wasm.c:38]: The natural wasm page size of 64k is spoiled by the fact there is `dlmalloc` header around it anyway.
So I think we could choose arbitrary bage size and 16K is max on other platforms for sgen.

Right @BrzVlad

Comment (BrzVlad) [reply src/mono/mono/utils/mono-mmap-wasm.c:38]: @kg not sure if you are talking about other blocks. GC major blocks (for small object allocation) are at least 16k. 

I think 16k page size is just fine.

File: src/mono/mono/utils/mono-mmap-wasm.c [hunk 7]
```diff
@@ -96,125 +79,48 @@ mono_setmmapjit (int flag)
...
+#ifdef DISABLE_THREADS
+	if ((flags & MONO_MMAP_NOZERO) == 0 && old_sbrk > res) {
+		// this means that we got an old block, not the new block from sbrk
+		memset (res, 0, size);
+	}
+#else
+	if ((flags & MONO_MMAP_NOZERO) == 0) {
+		memset (res, 0, size);
+	}
+#endif
```
Comment (BrzVlad) [inline src/mono/mono/utils/mono-mmap-wasm.c:113]: this no longer does `mono_account_mem` tracking of allocated memory

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 4 above)
Comment (BrzVlad) [inline src/mono/mono/utils/mono-mmap-wasm.c:121]: as above, missing tracking of allocated memory.

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 3 above)
Comment (kg) [reply src/mono/mono/utils/mono-mmap-wasm.c:38]: I'm referring to the comments in the lock free allocator, which is one of the places that was consuming the page size and interacting with mmap. I guess I was under the mistaken assumption that we used the lock free allocator in more places than we do.

**Comment by radekdoulik** [comment]
there are visible regressions in json on firefox. I will schedule the updated commit to have another measurement at hand

File: src/mono/mono/sgen/sgen-marksweep.c (hunk 1 above)
Comment (pavelsavara) [reply src/mono/mono/sgen/sgen-marksweep.c:57]: Do you remember what specifically was impacted ?

Comment (kg) [reply src/mono/mono/sgen/sgen-marksweep.c:57]: it was a stack walking benchmark in the performance suite i believe, and it was caused by the lock free allocator not properly utilizing all the space it allocated

**Comment by radekdoulik** [comment]
the commit 5070e999649131aad70c272cdb2b62e4930019e1 is measured and visible in the [perf tool](https://radekdoulik.github.io/WasmPerformanceMeasurements/?startDate=2024-10-07T10%3A13%3A30.000Z&endDate=2024-10-21T08%3A09%3A47.000Z&tasks=%2CString&flavors=0%2C1)
Screenshot 2024-10-21 at 15 16 32

File: src/mono/mono/sgen/sgen-marksweep.c (hunk 1 above)
Comment (pavelsavara) [reply src/mono/mono/sgen/sgen-marksweep.c:57]: I made `LOCK_FREE_ALLOC_SB_MAX_SIZE` to `16384 * 32` to compensate for `MS_BLOCK_ALLOC_NUM 1`

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 3 above)
Comment (kg) [inline src/mono/mono/utils/mono-mmap-wasm.c:38]: does the loop that's based on SB_MAX_SIZE handle this pagesize correctly?

File: src/mono/mono/utils/mono-mmap-wasm.c [hunk 8]
```diff
@@ -96,122 +79,50 @@ mono_setmmapjit (int flag)
...
-		//  hash lookup failed because addr isn't exactly the start of the mapping.
-		// Ideally if the custom page manager is enabled, we won't have done aligned alloc.
-		BEGIN_CRITICAL_SECTION;
-		if (mono_opt_wasm_mmap)
-			mwpm_free_range (addr, length);
-		else
-			munmap (addr, length);
-		END_CRITICAL_SECTION;
-	}
+	// NOTE: this doesn't implement partial freeing like munmap does
```
Comment (kg) [inline src/mono/mono/utils/mono-mmap-wasm.c:123]: I'm concerned about this slightly, spec says that munmap on pages you didn't map is safe, and mwpm maintains that invariant too. g_free on a bad pointer will definitely crash.

**Review by kg — APPROVED** [review]

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 8 above)
Comment (pavelsavara) [reply src/mono/mono/utils/mono-mmap-wasm.c:123]: We didn't see any crash on CI. Also we are early in the Net10 cycle. I don't plan to merge this to any older releases.

File: src/mono/mono/utils/mono-mmap-wasm.c (hunk 3 above)
Comment (pavelsavara) [reply src/mono/mono/utils/mono-mmap-wasm.c:38]: I removed the ifdef and we will see if those asserts still pass. They should as mono_pagesize is 16K and `LOCK_FREE_ALLOC_SB_MAX_SIZE` is 32*16K

Comment (pavelsavara) [reply src/mono/mono/utils/mono-mmap-wasm.c:38]: So that didn't work and I reverted that and keep the ifdef.

Comment (kg) [reply src/mono/mono/utils/mono-mmap-wasm.c:38]: OK. It might be nice to add a comment near the broken loop/asserts that explains the current state of the code, in case someone other than you and me encounters it later
