### PR TITLE
Fix crc32 issues found in #62692

### LINKED ISSUE #62692: Issues with the Crc32 intrinsic in the Jit
1\): The assert [here](https://github.com/dotnet/runtime/blob/cf75830ce2ecd5efafbf39c5de319b2841d8666c/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1724) is wrong because it does not account for small types. Reproduction:
```cs
static uint Problem(byte* pSrc, uint data)
{
    return Sse42.Crc32(*pSrc, data);
}
```
2\) The same assert is also wrong because [in lowering](https://github.com/dotnet/runtime/blob/cf75830ce2ecd5efafbf39c5de319b2841d8666c/src/coreclr/jit/lowerxarch.cpp#L1051-L1062) we purposefully remove narrowing `long` -> `int` casts to avoid generating redundant `mov`s. Reproduction:
```cs
static uint Problem(uint crc, ulong data)
{
    return Sse42.Crc32(crc, (uint)(data >> 16));
}
```
3\) The code in lowering is wrong because it can discard meaningful casts. Reproduction (`data` here will not be zero-extended):
```cs
static uint Problem(uint crc, uint data)
{
    return Sse42.Crc32(crc, (uint)(byte)data);
}
```
4\) The code in lowering is also wrong because it can discard `long` -> `int` casts on x86, and end up with a `GT_LONG` operand, which is not handled downstream. Reproduction, run on x86:
```cs
[MethodImpl(MethodImplOptions.NoOptimization)]
static uint Problem(uint crc, ulong data)
{
    return Sse42.Crc32(crc, (uint)(data >> 16));
}
```
5\) The code in lowering is also wrong because it can discard `double/float -> int` casts. Applies to all use sites of `TryRemoveCastIfPresent`. Reproduction:
```cs
static uint Problem(uint crc, double data)
{
    return Sse42.Crc32(crc, (uint)data);
}
```
Curiously enough, if we disable asserts, this will happily emit `crc32    eax, xmm1`.

6\) The code in lowering is also wrong because it can discard checked casts. Applies to all use sites of `TryRemoveCastIfPresent`. Reproduction (observe the generated code will have no check):
```cs
static uint Problem(uint crc, int data)
{
    return Sse42.Crc32(crc, checked((uint)data));
}
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/62692

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @SingleAccretion @jakobbotsch @dotnet/jit-contrib

File: src/coreclr/jit/lower.h [hunk 1]
```diff
@@ -377,17 +377,36 @@ class Lowering final : public Phase
...
+        if (cast->gtOverflow())
+        {
+            return op;
+        }
+
+        if (genTypeSize(cast->CastToType()) >= genTypeSize(expectedType))
+        {
+#ifndef TARGET_64BIT
+            // Don't expose TYP_LONG on 32bit
+            if (varTypeIsLong(cast->CastFromType()) && varTypeIsInt(expectedType))
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.h:403]: I think it would be better to make this condition just `varTypeIsLong` and not rely on the fact one decomposition optimization makes this unreachable for small `expectedType`s.

**Review by jakobbotsch — APPROVED** [review]

**Review by deeprobin — APPROVED** [review]
LGTM. After this is merged please reopen https://github.com/dotnet/runtime/pull/61558

**Comment by EgorBo** [comment]
`runtime (mono llvmfullaot Pri0 Runtime Tests Run Linux arm64 release)` is pending but the test is x86 only and the change in JIT doesn't affect mono
