### PR TITLE
Fix Type System Equivalence Checks

### LINKED ISSUE #96242: Reduced .NET8 R2R performance
### Description

On arm64, using PublishReadyToRun on the attached project; you will get reduced performance using .NET8 (not present in NET7, NET6). 

```
dotnet publish .\Arm64Net8JitError.csproj -f net6.0-windows -r win-arm64 -c Release --no-self-contained -p:PublishReadyToRun=true -o error_62_net6
 
dotnet publish .\Arm64Net8JitError.csproj -f net8.0-windows -r win-arm64 -c Release --no-self-contained -p:PublishReadyToRun=true -o error_63_net8

```

On my machine:
NET6: 10ms 
NET8: 650ms

To help you guys get started, we have extracted a minimal reproduce project that triggers the error from a real application if you wonder why the app has no apparent purpose. 

Changing from struct to class on Point2D will remove the problem. 
[Arm64Net8JitError.zip](https://github.com/dotnet/runtime/files/13743233/Arm64Net8JitError.zip)

### Reproduction Steps

Start program published with parameter PublishReadyToRun:true and press the one button and get a messagebox with the init time to spot the difference. 

### Expected behavior

Non regressed performance. 

### Actual behavior

Really bad performance -> real world applicaton starts 10 times slower.  Attached benchmark app is even slower than that. 

### Regression?

Yes, works in NET6.0, NET7.0

### Known Workarounds

Convert Point2D struct to class instead. 

### Configuration

See description. 

### Other information

We target imx8MPlus.

### PR DESCRIPTION
**Pull request by ivdiazsa**
Fixes issue #96242.

This is the initial draft of the solution to address the aforementioned issue. Debugging through Crossgen2 and the compiler for ReadyToRun, we found that on Windows, we were computing and using type identifiers from Guid's, whether there is interop or not. As far as we're concerned, outside of those scenarios we shouldn't need to be doing those checks.

So, initially I want to ask for your guidance more than direct review feedback. Are we approaching this the right way? Is this the right solution? Starting this as draft since this discussion is needed beforehand.

@davidwrighton @jkotas @MichalStrehovsky

### CODE REVIEW

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs [hunk 1]
```diff
@@ -80,12 +80,12 @@ private TypeIdentifierData ComputeTypeIdentifierData()
                     if (this.HasCustomAttribute("System.Runtime.InteropServices", "ImportedFromTypeLibAttribute") || this.HasCustomAttribute("System.Runtime.InteropServices", "PrimaryInteropAssemblyAttribute"))
                     {
```
Comment (lambdageek) [inline src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs:81]: These look wrong too:  it should be checking the assembly for those attributes, not the current type.

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs [hunk 2]
```diff
@@ -80,12 +80,12 @@ private TypeIdentifierData ComputeTypeIdentifierData()
...
-                    }
-
-                    if (!TypeHasCharacteristicsRequiredToBeTypeEquivalent)
-                        return null;
+                        if (!TypeHasCharacteristicsRequiredToBeTypeEquivalent)
+                            return null;
 
-                    _data = ComputeTypeIdentifierFromGuids();
+                        _data = ComputeTypeIdentifierFromGuids();
+                        return _data;
```
Comment (lambdageek) [inline src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs:87]: nit: I think this function (and `ComputeTypeIdentifierFromGuids`) should not be assigning to `_data` directly.  They should just return a `TypeIdentifierData` or null.  The caching getter should do the atomic assignment to `_data`

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs (hunk 1 above)
Comment (kg) [reply src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs:81]: yeah, ImportedFromTypeLibAttribute "Indicates that the types defined within an assembly were originally defined in a type library" and its only valid target is an assembly.

Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs:81]: Huh, sigh. Yeah, this needs to be fixed too. It will slightly reduce the scope of your perf fix, but is necessary to avoid marking stuff as type equivalent.

File: src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs (hunk 2 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.TypeEquivalence.cs:87]: This is what I get for working on a PR over 2-3 years. I forget stuff. I don't think it's really a functional problem, but only having 1 writer was the intention here.

**Comment by steveisok** [comment]
@davidwrighton do you see any harm in backporting this change to net8?

**Comment by ivdiazsa** [comment]
Failures are known and unrelated. Could we get a review now? @davidwrighton @MichalStrehovsky @lambdageek @kg @steveisok

**Review by steveisok — APPROVED** [review]
LGTM! Only outstanding question I have is if this is backport worthy?

**Review by davidwrighton — APPROVED** [review]

**Comment by davidwrighton** [comment]
I think this is eligible for backport. It looks reasonable to me.

**Comment by ivdiazsa** [comment]
> I think this is eligible for backport. It looks reasonable to me.

Perfect thanks! Will merge this and start working on the backport PR to .NET 8.
