### PR TITLE
Implement ZLibStream and fix SocketsHttpHandler deflate support

### LINKED ISSUE #2236: Add support for zlib data format (RFC 1950)
Currently .Net doesn't support the zlib data format despite the majority of the work having been done by DeflateStream. I propose a new class be added similar to GZipStream to support [RFC 1950](https://www.ietf.org/rfc/rfc1950.txt).

Personally I'm encountering the zlib format in two areas. Many games depend on zlib, and save files using this format.  We also use zlib in the firmware of one of our hardware products.  We save debug data and compress it with zlib.  For both of these scenarios, we use C# tooling, on the desktop, to operate on these files whether it is for the purpose of reading, modifying, or writing.

Due to the lack of support in .Net I either have to use lame hacky methods, or rely on a separate third party library for the functionality. This is such a shame when .Net already provides the majority of what's needed, and it should be trivial (as far I can tell) to include this as part of .Net.

While decompression is quite simple to do by skipping the 2-6 byte header, and 4 byte CRC at the end, I have trouble with compression.  I wouldn't know what the proper header should be when using DeflateStream to do the compression, not to mention having to include a computation for the Adler32 checksum.

Here's a quick untested example of what I currently have to do for decompression to give you an idea of the "lame hacky-ness": (Note: I'm not checking the checksum here. I'm assuming the data is good.)
```csharp
private byte[] ZlibDecompress(byte[] data)
{
    using (var ms = new MemoryStream())
    using (var ds = new DeflateStream(ms, CompressionMode.Decompress))
    using (var msOut = new MemoryStream())
    {
        int headerSize = (data[1] & 0b10000) == 0b10000 ? 6 : 2;
        ms.Write(data, headerSize, data.Length - 4 - headerSize);
        ms.Seek(0, SeekOrigin.Begin);
        ds.CopyTo(msOut);
        return msOut.ToArray();
     }
}
```

## Proposed API
```csharp
public class ZLibStream : Stream
{
    public ZLibStream(Stream stream, CompressionLevel compressionLevel);
    public ZLibStream(Stream stream, CompressionMode mode);
    public ZLibStream(Stream stream, CompressionLevel compressionLevel, bool leaveOpen);
    public ZLibStream(Stream stream, CompressionMode mode, bool leaveOpen);
    public override bool CanWrite { get; }
    public override bool CanSeek { get; }
    public override bool CanRead { get; }
    public Stream BaseStream { get; }
    public override long Length { get; }
    public override long Position { get; set; }
    public override void CopyTo(Stream destination, int bufferSize);
    public override Task CopyToAsync(Stream destination, int bufferSize, CancellationToken cancellationToken);
    public override ValueTask DisposeAsync();
    public override void Flush();
    public override Task FlushAsync(CancellationToken cancellationToken);
    public override int Read(Span<byte> buffer);
    public override int Read(byte[] array, int offset, int count);
    public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken = default);
    public override Task<int> ReadAsync(byte[] array, int offset, int count, CancellationToken cancellationToken);
    public override int ReadByte();
    public override long Seek(long offset, SeekOrigin origin);
    public override void SetLength(long value);
    public override void Write(byte[] array, int offset, int count);
    public override void Write(ReadOnlySpan<byte> buffer);
    public override Task WriteAsync(byte[] array, int offset, int count, CancellationToken cancellationToken);
    public override ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default);
    protected override void Dispose(bool disposing);
}
```

### LINKED ISSUE #38022: HttpClient doesn't decompress "deflate" correctly
### Description
I am using .NET Core v3.1 to fetch data from a REST API that uses *deflate* compression. I use the following code:
```
var httpClientHandler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.All };
using var httpClient = new HttpClient(httpClientHandler);
var request = new HttpRequestMessage(HttpMethod.Get, "https://api.example.com/api/v1/get");
var response = await httpClient.SendAsync(request);
```
This request sends out the following headers:
```
GET https://api.example.com/api/v1/get HTTP/1.1
Host: api.example.com
Accept-Encoding: gzip, deflate, br
```
The server responds with (parsed with Fiddler):
```
HTTP/1.1 200 OK
Server: openresty/1.15.8.1
Date: Wed, 17 Jun 2020 12:06:27 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
charset: utf-8
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With
Content-Encoding: deflate
Vary: Accept-Encoding
Strict-Transport-Security: max-age=15724800; includeSubDomains
```
My .NET Core client cannot decompress the data and fails with "**The archive entry was compressed using an unsupported compression method.**". When I invoke this command using Curl or Postman, then it works fine and the result is a valid JSON result.

The binary data looks like this:
```
00000000: 789c edd4 414b c330 1407 f0af 22ef 9c43  x...AK.0...."..C
00000010: 92a6 8deb 7517 3d74 8808 1ec6 0e61 895d  ....u.=t.....a.]
00000020: a14d 244b 6132 f6dd 4daa 42ab 87a5 13d7  .M$Ka2..M.B.....
00000030: 83cd a92f fcf3 dafc 0a6f 7d84 da08 b932  .../.....o}....2
00000040: 9013 042f 4ac9 4a97 9f95 15ae 32fa 5e42  .../J.J.....2.^B
00000050: ce09 43d0 5407 6543 45b2 0481 8f59 1f56  ..C.T.eCE....Y.V
00000060: daed 215f 1f7b 7588 30cc 1608 9cb0 a572  ..!_.{u.0......r
00000070: cfaa 2a77 0ef2 c49f 92f6 ad10 ce29 fba0  ..*w.........)..
00000080: ec16 728c 406c 5d2b ea22 f45e 9aa6 11da  ..r.@l]+.".^....
00000090: 9f86 9bb0 309c 504c df8c 47f7 2db0 5f14  ....0.PL..G.-._.
000000a0: 4e1b 04a5 35ed ebc7 a777 8fdd c528 c7df  N...5....w...(..
000000b0: bb13 ecb7 764a c8a5 6975 5787 d3ce 3851  ....vJ..iuW...8Q
000000c0: 3ffd 0c76 fb77 fdb4 7713 87c7 4eb2 970c  ?..v.w..w...N...
000000d0: 37fb 72a7 b3fb 24ee c9ec 3e89 3b9b dd29  7.r...$...>.;..)
000000e0: 27e7 dcd3 31ec e979 f5f4 8fd5 e371 46a1  '...1..y.....qF.
000000f0: 93f8 9f79 013a 8d33 a797 9167 0372 3a20  ...y.:.3...g.r:
00000100: 67f8 f7e4 fe75 78b4 fab8 5110 3f0b e287  g....ux...Q.?...
00000110: 413a 40e2 0324 f63f a7c1 0453 f876 769f  A:@..$.?...S.vv.
00000120: c47d 31bb 5fcf 7df3 0ea6 e930 f2         .}1._.}....0.
```
After some digging, I found that the first two bytes `78 9C` are the ZLIB header and the final four bytes `A6 E9 30 F2` are the Adler32 checksum that is part of ZLIB compressed data. It seems that .NET uses the standard [DeflateStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.deflatestream) when it encounters **deflated** content and this stream cannot deal with deflated data that has this ZLIB header.

[RFC2616 section 3.5](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.5) specifies:

> **deflate** The "zlib" format defined in [RFC 1950](https://tools.ietf.org/html/rfc1950) in combination with the "deflate" compression mechanism described in [RFC 1951](https://tools.ietf.org/html/rfc1951).

.NET Core and .NET Framework don't implement the RFC 1950 part of this specification, so if the HTTP server uses the ZLIB envelope the data cannot be decompressed and the call fails.

### Expected behaviour
The .NET Core implementation should detect that a ZLIB envelop is being used and decompress the data according to this header.

### Workaround
Only specify the `DecompressionMethods.GZip` for the HttpClientHandler's `AutomaticDecompression` property. If the server behaves properly, then it should use GZip compression instead (or not use compression after all). If you have a bad behaving HTTP server it may still send deflated data instead.

### PR DESCRIPTION
**Pull request by stephentoub**
- Implements ZLibStream, exposes it in the ref, and add tests
- Fixes SocketsHttpHandler to use ZLibStream instead of DeflateStream to make HttpClient correctly support "deflate"

Fixes https://github.com/dotnet/runtime/issues/2236
Fixes https://github.com/dotnet/runtime/issues/38022
(This completes the commit from https://github.com/dotnet/runtime/issues/2236#issuecomment-653212590.)

The tests require the updated runtime-assets test data from https://github.com/dotnet/runtime-assets/pull/87.

cc: @ericstj @carlossanlop @geoffkizer

### CODE REVIEW

File: src/libraries/Common/tests/System/IO/Compression/CompressionStreamUnitTestBase.cs [hunk 1]
```diff
@@ -1254,6 +1254,59 @@ public async Task Parallel_CompressDecompressMultipleStreamsConcurrently()
...
+        [InlineData(false)]
+        [InlineData(true)]
+        public async Task DisposeAsync_MultipleCallsAllowed(bool leaveOpen)
+        {
+            using (var cs = CreateStream(new MemoryStream(), CompressionMode.Compress, leaveOpen))
+            {
+                await cs.DisposeAsync();
+                await cs.DisposeAsync();
+            }
+        }
```
Comment (stephentoub) [inline src/libraries/Common/tests/System/IO/Compression/CompressionStreamUnitTestBase.cs:1309]: These tests moved from the derived types down to the base type to avoid the duplication.

File: src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs [hunk 2]
```diff
@@ -0,0 +1,293 @@
+// Licensed to the .NET Foundation under one or more agreements.
```
Comment (stephentoub) [inline src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:1]: For the most part, this file is just a copy of GZipStream with minor tweaks.

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Decompression.cs [hunk 3]
```diff
@@ -186,6 +188,26 @@ public async Task GetAsync_SetAutomaticDecompression_ContentDecompressed(Configu
             }
         }
 
+        // The remote server endpoint was written to use DeflateStream, which isn't actually a correct
+        // implementation of the deflate protocol (the deflate protocol requires the zlib wrapper around
+        // deflate).  Until we can get that updated (and deal with previous releases still testing it
+        // via a DeflateStream-based implementation), we utilize httpbin.org to help validate behavior.
```
Comment (geoffkizer) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Decompression.cs:194]: Thumbs up for httpbin.org :)

File: src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs [hunk 4]
```diff
@@ -0,0 +1,293 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Diagnostics.CodeAnalysis;
+using System.Threading;
+using System.Threading.Tasks;
+
+namespace System.IO.Compression
+{
+    /// <summary>Provides methods and properties used to compress and decompress streams by using the ZLib data format specification.</summary>
+    public sealed class ZLibStream : Stream
```
Comment (geoffkizer) [inline src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:11]: It almost seems like having a DelegatingStream class would be useful.

Comment (stephentoub) [reply src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:11]: Now you know why it was top of mind for me ;-)

That said, it wouldn't help much here, as this type would still need to override most of the methods.

And on top of that, it would expose what's effectively an implementation detail into the public API surface area.

File: src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs [hunk 5]
```diff
@@ -211,7 +211,7 @@ public DeflateDecompressedContent(HttpContent originalContent)
             { }
 
             protected override Stream GetDecompressedStream(Stream originalStream) =>
-                new DeflateStream(originalStream, CompressionMode.Decompress);
+                new ZLibStream(originalStream, CompressionMode.Decompress);
```
Comment (geoffkizer) [inline src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:214]: Can we add a comment here about how, even though the HTTP compression scheme is called "deflate", what it really means is "zlib"? Or something like that. Otherwise it's kind of confusing why we aren't using DeflateStream here.

Comment (stephentoub) [reply src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:214]: Yup

File: src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs (hunk 4 above)
Comment (geoffkizer) [reply src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:11]: > That said, it wouldn't help much here, as this type would still need to override most of the methods.

why?

Comment (stephentoub) [reply src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:11]: > why?

Because it's maintaining the same semantics as GZipStream and has a ThrowIfClosed call at the beginning of most of the overrides before it calls to the delegated stream.

Comment (geoffkizer) [reply src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:11]: Why wouldn't a DelegatingStream class do the same thing?

Comment (ericstj) [reply src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:11]: There is a set of common stream modifiers that are useful that we should consider adding.  DelegatingStream, SubsettingStream, Readonly, WriteOnly, NoDispose.  I think I've written / seen most of these multiple times.  Do we have an issue?  cc @carlossanlop

Comment (stephentoub) [reply src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:11]: > Why wouldn't a DelegatingStream class do the same thing?

Seems to me like policy we wouldn't want there.  I could be wrong.

Comment (stephentoub) [reply src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:11]: But again, I think that's the lesser issue; making ZLibStream derive from DelegatingStream bakes that implementation detail into the public API surface area.  That seems to me very undesirable.  I'm very much in favor of adding a DelegatingStream for use in implementation, but I'm not sure how much of a place it has in public API surface area.

Comment (geoffkizer) [reply src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:11]: > making ZLibStream derive from DelegatingStream bakes that implementation detail into the public API surface area. That seems to me very undesirable. 

I get the point, but it seems unfortunate. The broader implication here is that derivation to support code reuse is not a viable approach in our public API. That kinda sucks.

**Review by geoffkizer — APPROVED** [review]

**Review by geoffkizer — APPROVED** [review]

File: src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs [hunk 6]
```diff
@@ -211,7 +211,12 @@ public DeflateDecompressedContent(HttpContent originalContent)
             { }
 
             protected override Stream GetDecompressedStream(Stream originalStream) =>
-                new DeflateStream(originalStream, CompressionMode.Decompress);
+                // As described in RFC 2616, the deflate content-coding is actually
+                // the "zlib" format (RFC 1950) in combination with the "deflate"
+                // compression algrithm (RFC 1951).  So while potentially
+                // counterintuitive based on naming, this needs to use ZLibStream
+                // rather than DeflateStream.
+                new ZLibStream(originalStream, CompressionMode.Decompress);
```
Comment (ericstj) [inline src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:219]: Do you think there is any reverse compatibility issue here?  Anyone who might desire the old behavior?

**Review by ericstj — APPROVED** [review]

File: src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs (hunk 6 above)
Comment (stephentoub) [reply src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:219]: It's possible. The standard has always been for the deflate-compressed content to be wrapped in a zlib wrapper, but some of the early web servers got it wrong:
https://stackoverflow.com/questions/9170338/why-are-major-web-sites-using-gzip/9186091#9186091
We could make it try both, though that gets complicated.

Comment (stephentoub) [reply src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:219]: > What is the mode of failure when the server provides deflate stream instead of zlib?

Exception saying the data is in the wrong format / can't be decompressed

> Presumably there are enough servers out there providing only deflate that this bug went unfixed for some time.

From what I've seen, it's more that very few clients actually request deflate because there historically was such confusion about what it meant.  But, yes, it's possible someone somewhere would break.

> I'd hate for us to break clients talking to those servers.

@geoffkizer, opinions on what you'd like to see done here?

Comment (geoffkizer) [reply src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:219]: I think we should make this change. We have time in this release to see if it breaks anyone. If it does, we could add a setting or an app config switch or something. But I think that's pretty unlikely.

Comment (geoffkizer) [reply src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:219]: > From what I've seen, it's more that very few clients actually request deflate

I think it's also that you'd need to request deflate as a higher priority than gzip. I've seen clients request "gzip, deflate" or just "gzip", but almost never "deflate" or "deflate, gzip". So in practice, if you are using compression, you're almost always using gzip.

File: src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs [hunk 7]
```diff
@@ -0,0 +1,293 @@
...
+        /// <param name="stream">The stream to which compressed data is written or from which decompressed data is read.</param>
+        /// <param name="mode">One of the enumeration values that indicates whether to compress or decompress the stream.</param>
+        public ZLibStream(Stream stream, CompressionMode mode) : this(stream, mode, leaveOpen: false)
+        {
+        }
+
+        /// <summary>Initializes a new instance of the <see cref="ZLibStream"/> class by using the specified stream, compression mode, and whether to leave the <paramref name="stream"/> open.</summary>
+        /// <param name="stream">The stream to which compressed data is written or from which decompressed data is read.</param>
+        /// <param name="mode">One of the enumeration values that indicates whether to compress or decompress the stream.</param>
+        /// <param name="leaveOpen"><c>true</c> to leave the stream object open after disposing the <see cref="ZLibStream"/> object; otherwise, <c>false</c>.</param>
```
Comment (carlossanlop) [inline src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:26]: It could also be fixed in the porting PR, but since we are here:
```suggestion
        /// <param name="leaveOpen"><see langword="true" /> to leave the stream object open after disposing the <see cref="ZLibStream"/> object; otherwise, <see langword="false" />.</param>
```

File: src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs [hunk 8]
```diff
@@ -0,0 +1,293 @@
...
+        /// <param name="stream">The stream to which compressed data is written.</param>
+        /// <param name="compressionLevel">One of the enumeration values that indicates whether to emphasize speed or compression efficiency when compressing the stream.</param>
+        public ZLibStream(Stream stream, CompressionLevel compressionLevel) : this(stream, compressionLevel, leaveOpen: false)
+        {
+        }
+
+        /// <summary>Initializes a new instance of the <see cref="ZLibStream"/> class by using the specified stream, compression level, and whether to leave the <paramref name="stream"/> open.</summary>
+        /// <param name="stream">The stream to which compressed data is written.</param>
+        /// <param name="compressionLevel">One of the enumeration values that indicates whether to emphasize speed or compression efficiency when compressing the stream.</param>
+        /// <param name="leaveOpen"><c>true</c> to leave the stream object open after disposing the <see cref="ZLibStream"/> object; otherwise, <c>false</c>.</param>
```
Comment (carlossanlop) [inline src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:42]:
```suggestion
        /// <param name="leaveOpen"><see langword="true" /> to leave the stream object open after disposing the <see cref="ZLibStream"/> object; otherwise, <see langword="false" />.</param>
```

File: src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs [hunk 9]
```diff
@@ -0,0 +1,293 @@
...
+        }
+
+        /// <summary>This method is not supported and always throws a <see cref="NotSupportedException"/>.</summary>
+        public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();
+
+        /// <summary>This method is not supported and always throws a <see cref="NotSupportedException"/>.</summary>
+        public override void SetLength(long value) => throw new NotSupportedException();
+
+        /// <summary>Reads a byte from the stream and advances the position within the stream by one byte, or returns -1 if at the end of the stream.</summary>
+        /// <returns></returns>
```
Comment (carlossanlop) [inline src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:90]: Since this returns what `_deflateStream.ReadByte()` returns, we can copy the original returns string:
```suggestion
        /// <returns>The unsigned byte cast to an <see cref="int" />, or -1 if at the end of the stream.</returns>
```
Original: https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.deflatestream.readbyte?view=netcore-3.1

File: src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs [hunk 10]
```diff
@@ -0,0 +1,293 @@
...
+
+        /// <summary>This property is not supported and always throws a <see cref="NotSupportedException"/>.</summary>
+        public override long Length => throw new NotSupportedException();
+
+        /// <summary>This property is not supported and always throws a <see cref="NotSupportedException"/>.</summary>
+        public override long Position
+        {
+            get => throw new NotSupportedException();
+            set => throw new NotSupportedException();
+        }
```
Comment (carlossanlop) [inline src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:65]: I can see that these are not supported because `DeflateStream` also does not support them. I was going to ask why they were throwing, but I assume we would've also tried to call the underlying `_deflateStream` properties if they didn't throw.
https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.deflatestream.length?view=netcore-3.1
https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.deflatestream.position?view=netcore-3.1

**Review by carlossanlop — APPROVED** [review]
LGTM. Left some minor documentation suggestions to consider.

**Comment by carlossanlop** [comment]
One of the CI failures is:

```
F:\workspace\_work\1\s\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.Decompression.cs(49,55): error CS0246:
The type or namespace name 'ZLibStream' could not be found (are you missing a using directive or an assembly reference?) 
[F:\workspace\_work\1\s\src\libraries\System.Net.Http.WinHttpHandler\tests\FunctionalTests\System.Net.Http.WinHttpHandler.Functional.Tests.csproj]


```

File: src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs (hunk 6 above)
Comment (stephentoub) [reply src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:219]: Ok, thanks for the discussion.  I'll stick with just using ZLibStream, and I've marked the PR as a breaking change just to ensure we doc this.

Comment (ericstj) [reply src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:219]: Got it, so folks do have a workaround by changing their requested `Transfer-Encoding` to a different spec compliant encoding.  That's better than supporting a non-compliant deflate format.  Thanks for the discussion.

**Comment by karelz** [comment]
@stephentoub you removed the breaking change labels ... is that because you implemented the detection that accepts both?
And there is no impact on server it seems ...

**Comment by stephentoub** [comment]
> is that because you implemented the detection that accepts both?

Correct.
