### PR TITLE
JIT: Fix block morphing/physical promotion self-interference

### LINKED ISSUE #85874: JIT: Block morphing does not handle that decomposed writes can affect the destination
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
static int Test()
{
    S s;
    s.Me = &s;
    S s2;
    s2.Me = null;
    s2.F = 1234;
    *(S*)s.Me = s2;
    return s.F;
}

public unsafe struct S
{
    public void* Me;
    public int F;
}
```

`Test` returns 1234 in tier-0 but throws `NullReferenceException` in tier-1. Block morphing produces
```scala
MorphCopyBlock:
PrepareDst for [000021] have not found a local var.
block assignment to morph:
               [000022] -A-XG------                         ▌  ASG       struct (copy)
               [000021] ---XG+-N---                         ├──▌  BLK       struct<Program+S, 16>
               [000019] ----G+-----                         │  └──▌  LCL_VAR   long  (AX) V03 tmp1         
               [000020] -----+-----                         └──▌  LCL_VAR   struct<Program+S, 16>(P) V01 loc1         
                                                            └──▌    long   V01.Program+S:Me (offs=0x00) -> V05 tmp3          (last use)
                                                            └──▌    int    V01.Program+S:F (offs=0x08) -> V06 tmp4          (last use)
 (m_srcDoFldAsg=true) using field by field assignments.
dstAddr - Multiple Fields Clone created:
               [000033] ----G------                         ▌  LCL_VAR   long  (AX) V03 tmp1         
MorphCopyBlock (after):
               [000038] -A-XG+-----                         ▌  COMMA     void  
               [000031] -A-XG------                         ├──▌  ASG       long  
               [000030] ---XG--N---                         │  ├──▌  IND       long  
               [000019] ----G+-----                         │  │  └──▌  LCL_VAR   long  (AX) V03 tmp1         
               [000029] -----------                         │  └──▌  LCL_VAR   long   V05 tmp3         
               [000037] -A-XG------                         └──▌  ASG       int   
               [000036] ---XG--N---                            ├──▌  IND       int   
               [000035] ----G------                            │  └──▌  ADD       byref 
               [000033] ----G+-----                            │     ├──▌  LCL_VAR   long  (AX) V03 tmp1         
               [000034] -----------                            │     └──▌  CNS_INT   long   8
               [000032] -----------                            └──▌  LCL_VAR   int    V06 tmp4         
```
The first store overrides `V03` that is also used in the second store.

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix a couple of cases where it's possible that the decomposed stores
will modify the address being used as part of the operation too early.
In those cases we must spill the address to a new local ahead of time.

Fix #85874

### CODE REVIEW

File: src/tests/JIT/Regression/JitBlue/Runtime_85874/Runtime_85874.cs [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+    [Fact]
+    public static int DestinationIsAddress()
+    {
+        ListElement e1;
+        ListElement e2 = default;
+        e2.Value = 100;
+        e1.Next = &e2;
+        e1.Value = 1234;
+        Consume(e1);
+        e1 = *e1.Next;
```
Comment (jakobbotsch) [inline src/tests/JIT/Regression/JitBlue/Runtime_85874/Runtime_85874.cs:31]: I'm surprised we haven't stumbled on this one before.

File: src/coreclr/jit/morphblock.cpp [hunk 2]
```diff
@@ -1512,6 +1515,66 @@ GenTree* MorphCopyBlockHelper::CopyFieldByField()
...
+        //  │     └──▌  LCL_VAR   long   V03 tmp1          (last use)
+        //  └──▌  ASG       int
+        //     ├──▌  LCL_VAR   int    V04 tmp2
+        //     └──▌  IND       int
+        //        └──▌  ADD       byref
+        //           ├──▌  LCL_VAR   long   V03 tmp1          (last use)
+        //           └──▌  CNS_INT   long   8
+        //
+        // which is also obviously incorrect.
+        //
```
Comment (SingleAccretion) [inline src/coreclr/jit/morphblock.cpp:1565]:
```suggestion
        // The store can also directly write to the address. For example:
        //
        //  ▌  STORE_LCL_VAR struct<Program+ListElement, 16>(P) V00 loc0
        //  ├──▌  long   V00.Program+ListElement:Next (offs=0x00) -> V03 tmp1
        //  ├──▌  int    V00.Program+ListElement:Value (offs=0x08) -> V04 tmp2
        //  └──▌  BLK       struct<Program+ListElement, 16>
        //     └──▌  LCL_VAR   long   V03 tmp1          (last use)
        //
        // If we reused the address we would produce
        //
        //  ▌  COMMA     void
        //  ├──▌  STORE_LCL_VAR long   V03 tmp1
        //  │  └──▌  IND       long
        //  │     └──▌  LCL_VAR   long   V03 tmp1          (last use)
        //  └──▌  STORE_LCL_VAR int    V04 tmp2
        //     └──▌  IND       int
        //        └──▌  ADD       byref
        //           ├──▌  LCL_VAR   long   V03 tmp1          (last use)
        //           └──▌  CNS_INT   long   8
        //
        // which is also obviously incorrect.
        //
```
Since the `ASG` picture will become outdated quite soon (and the non-`ASG` one is already correct).

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS

File: src/coreclr/jit/promotion.h [hunk 3]
```diff
@@ -104,6 +104,8 @@ class Promotion
     }
 
     PhaseStatus Run();
+
+    static bool CanReuseAddressForDecomposedStore(Compiler* comp, GenTree* storeDst, GenTree* addr);
```
Comment (SingleAccretion) [inline src/coreclr/jit/promotion.h:108]: Dead declaration?

Comment (jakobbotsch) [reply src/coreclr/jit/promotion.h:108]: Whoops, yes.

```suggestion
```

**Review by AndyAyersMS — APPROVED** [review]
