### PR TITLE
Fix thread static cleanup paths

### LINKED ISSUE #104449: Assertion failed `(pThread->m_StateNC & Thread::TSNC_OwnsSpinLock) == 0`
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=730601
Build error leg or test failing: System.Reflection.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/104429

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "(pThread->m_StateNC & Thread::TSNC_OwnsSpinLock) == 0",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=730601
**Error message validated:** `[(pThread->m_StateNC & Thread::TSNC_OwnsSpinLock) == 0`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/4/2024 7:50:45 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[801531](https://dev.azure.com/dnceng-public/public/_build/results?buildId=801531)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=801531&view=ms.vss-test-web.build-test-results-tab&runId=20683198&resultId=211440)|dotnet/runtime#107531|
|[799241](https://dev.azure.com/dnceng-public/public/_build/results?buildId=799241)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=799241&view=ms.vss-test-web.build-test-results-tab&runId=20605124&resultId=211582)|dotnet/runtime#107403|
|[797869](https://dev.azure.com/dnceng-public/public/_build/results?buildId=797869)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=797869&view=ms.vss-test-web.build-test-results-tab&runId=20557862&resultId=214723)|dotnet/runtime#107371|
|[797585](https://dev.azure.com/dnceng-public/public/_build/results?buildId=797585)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=797585&view=ms.vss-test-web.build-test-results-tab&runId=20549744&resultId=214723)|dotnet/runtime#107358|
|[795103](https://dev.azure.com/dnceng-public/public/_build/results?buildId=795103)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=795103&view=ms.vss-test-web.build-test-results-tab&runId=20467672&resultId=211402)|dotnet/runtime#104503|
|[794876](https://dev.azure.com/dnceng-public/public/_build/results?buildId=794876)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=794876&view=ms.vss-test-web.build-test-results-tab&runId=20460008&resultId=211418)|dotnet/runtime#107201|
|[794247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=794247)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=794247&view=ms.vss-test-web.build-test-results-tab&runId=20441042&resultId=211430)|dotnet/runtime#107147|
|[791535](https://dev.azure.com/dnceng-public/public/_build/results?buildId=791535)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=791535&view=ms.vss-test-web.build-test-results-tab&runId=20359672&resultId=211365)|dotnet/runtime#107089|
|[786597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786597)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786597&view=ms.vss-test-web.build-test-results-tab&runId=20208290&resultId=211373)|dotnet/runtime#105771|
|[785657](https://dev.azure.com/dnceng-public/public/_build/results?buildId=785657)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=785657&view=ms.vss-test-web.build-test-results-tab&runId=20203854&resultId=211516)|dotnet/runtime#106830|
|[783356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=783356)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=783356&view=ms.vss-test-web.build-test-results-tab&runId=20107026&resultId=211356)|dotnet/runtime#106683|
|[780692](https://dev.azure.com/dnceng-public/public/_build/results?buildId=780692)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=780692&view=ms.vss-test-web.build-test-results-tab&runId=20018892&resultId=211347)|dotnet/runtime#106599|
|[776253](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776253)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776253&view=ms.vss-test-web.build-test-results-tab&runId=19868194&resultId=214641)|dotnet/runtime#100294|
|[776248](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776248)|dotnet/runtime|[System.Reflection.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776248&view=ms.vss-test-web.build-test-results-tab&runId=19867838&resultId=211341)|dotnet/runtime#106314|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|4|14|

### PR DESCRIPTION
**Pull request by davidwrighton**
- Do not destroy GC handles while holding the spin lock
- Free the pLoaderHandle array when the thread is terminated

Fixes #104449

### CODE REVIEW

File: src/coreclr/vm/threadstatics.cpp [hunk 1]
```diff
@@ -405,6 +405,13 @@ void FreeLoaderAllocatorHandlesForTLSData(Thread *pThread)
                 }
             }
         }
+
+        pThread->cLoaderHandles = -1; // Sentinel value indicating that there are no LoaderHandles and the thread is permanently dead.
+        if (pThread->pLoaderHandles != NULL)
```
Comment (jkotas) [inline src/coreclr/vm/threadstatics.cpp:410]: Nit: This should be always true since `cLoaderHandles > 0` here. Also, the `delete` can be called outside the lock.

File: src/coreclr/vm/threadstatics.cpp [hunk 2]
```diff
@@ -405,6 +405,13 @@ void FreeLoaderAllocatorHandlesForTLSData(Thread *pThread)
                 }
             }
         }
+
+        pThread->cLoaderHandles = -1; // Sentinel value indicating that there are no LoaderHandles and the thread is permanently dead.
```
Comment (jkotas) [inline src/coreclr/vm/threadstatics.cpp:409]: Set the sentinel before we start cleaning the entries?

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/threadstatics.cpp [hunk 3]
```diff
@@ -431,34 +438,49 @@ void FreeThreadStaticData(Thread* pThread)
...
+
+        ThreadLocalData *pThreadLocalData = &t_ThreadStatics;
+
+        pOldCollectibleTlsArrayData = pThreadLocalData->pCollectibleTlsArrayData;
+        oldCollectibleTlsDataCount = pThreadLocalData->cCollectibleTlsData;
+
+        pThreadLocalData->pCollectibleTlsArrayData = 0;
+        pThreadLocalData->cCollectibleTlsData = 0;
+        pThreadLocalData->pNonCollectibleTlsArrayData = 0;
+        pThreadLocalData->cNonCollectibleTlsData = 0;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/threadstatics.cpp:457]:
```suggestion
        pThreadLocalData->pCollectibleTlsArrayData = NULL;
        pThreadLocalData->cCollectibleTlsData = 0;
        pThreadLocalData->pNonCollectibleTlsArrayData = NULL;
        pThreadLocalData->cNonCollectibleTlsData = 0;
```

File: src/coreclr/vm/threadstatics.cpp [hunk 4]
```diff
@@ -431,34 +438,49 @@ void FreeThreadStaticData(Thread* pThread)
...
-    delete[] (uint8_t*)pThreadLocalData->pCollectibleTlsArrayData;
-
-    pThreadLocalData->pCollectibleTlsArrayData = 0;
-    pThreadLocalData->cCollectibleTlsData = 0;
-    pThreadLocalData->pNonCollectibleTlsArrayData = 0;
-    pThreadLocalData->cNonCollectibleTlsData = 0;
+    if (pOldCollectibleTlsArrayData != NULL)
+    {
+        delete[] (uint8_t*)pOldCollectibleTlsArrayData;
+    }
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/threadstatics.cpp:476]:
```suggestion
    delete[] (uint8_t*)pOldCollectibleTlsArrayData;
```

**Review by AaronRobinsonMSFT — APPROVED** [review]
