### PR TITLE
[mono] Fix a few corner case overflow operations

### LINKED ISSUE #51323: Some tests for overflow checking operations are disabled on Mono
1\) `JIT/Directed/Convert/value_numbering_checked_casts_of_constants.csproj` - #51440 introduced a [new test](https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Directed/Convert/value_numbering_checked_casts_of_constants.csproj) which [has been disabled](https://github.com/dotnet/runtime/blob/044de838588006cf40b5656016b6ed26492c410f/src/tests/issues.targets#L1031) on Mono. This issue will track re-enabling it once the root cause has been investigated and fixed. See https://github.com/dotnet/runtime/pull/50450#issuecomment-813073036 for the context on the failure modes.

2\) `JIT/Directed/Convert/signed_overflow_conversions_are_not_treated_as_unsigned.ilproj` - failed in CI when it was introduced, also on many configurations (Browser (interpreter) & LLVM AOT). I assume it has the same underlying cause as the above failure.

~~Note: at least part of this failure on interpreter is because of the fundamental disagreement on the interpretation of some IL sequences between RyuJit & Mono interpreter. See #53189, https://github.com/dotnet/runtime/issues/53189#issuecomment-856391687.~~ <- this has been fixed, but it is unknown if the test above still fails.

3\) `JIT/Methodical/int64/misc/longmul.ilproj` - failed on llvmaot Linux arm64/x64, minijit Linux arm64/OSX x64, monointerpreter Linux arm64 / OSX x64.

4\) `JIT/Methodical/Overflow/FloatOvfToInt2` family of tests - failed on llvmaot Linux x64 and arm64.

### PR DESCRIPTION
**Pull request by BrzVlad**
Fixes #51323

### CODE REVIEW

File: src/mono/mono/mini/interp/interp.c [hunk 1]
```diff
@@ -5472,33 +5472,45 @@ MINT_IN_CASE(MINT_BRTRUE_I8_SP) ZEROP_SP(gint64, !=); MINT_IN_BREAK;
...
-			LOCAL_VAR (ip [1], guint64) = (guint64)val;
 			ip += 3;
 			MINT_IN_BREAK;
 		}
 		MINT_IN_CASE(MINT_CONV_OVF_U8_R8) {
 			double val = LOCAL_VAR (ip [2], double);
-			if (mono_isnan (val) || mono_trunc (val) != (guint64)val)
+			const double two64  = 4294967296.0 * 4294967296.0;
+			if (val > -1.0 && val < two64)
+				LOCAL_VAR (ip [1], guint64) = (guint64)val;
```
Comment (lambdageek) [inline src/mono/mono/mini/interp/interp.c:5488]: Can we make this into a function in mono-math.h?

```c
static inline gboolean
mono_try_trunc_u64 (double val, uint64_t *out)
{
	const double two64  = 4294967296.0 * 4294967296.0;
	if (val > -1.0 && val < two64) {
		*out = (uint64_t)val;
		return TRUE;
	}
	return FALSE;
}
```

And similar for the other cases?

**Review by lambdageek — APPROVED** [review]
Looks ok.  I'd prefer to move the math to mono-math.h
