### PR TITLE
Prevent emitting Avx2 instructions with Vector256<T>.AllBitsSet when not supported

### LINKED ISSUE #48283: Vector256<Integer>.AllBitsSet emits illegal instructions on a machine without AVX2
### Description

On a machine without AVX2 but with AVX (Sandy Bridge / Ivy Bridge), `Vector256<IntegralType>.AllBitsSet` will emit illegal instructions and cause the program to crash.

In particular, this method:
```C#
public static Vector256<byte> Problem() => Vector256<byte>.AllBitsSet;
```
Will emit the following:
```asm
       vzeroupper 
G_M65241_IG02:
       vpcmpeqd ymm0, ymm0, ymm0
       vmovupd  ymmword ptr[rcx], ymm0
       mov      rax, rcx
G_M65241_IG03:
       vzeroupper 
       ret
```
According to https://www.felixcloutier.com/x86/pcmpeqb:pcmpeqw:pcmpeqd, `vpcmpeqd` with `ymm` operands is only available when AVX2 is.

This is also a problem for `Vector256.Create(-1)`.

### Configuration

This applies to .NET 5 and .NET 6, tested on an Ivy Bridge machine running Windows 10 x64.

### Regression?

This is not a regression in case of `AllBitsSet` (the API was introduced in .NET 5), but it is a regression from .NET Core 3.1 for the `Create(-1)` call (lowering now folds it to the same `get_AllBitsSet` node, see also #47385).

### Other information

During importation, `Vector256<byte>.AllBitsSet` depends on the `Vector256` ISA, presumably because it is declared like so:
```
HARDWARE_INTRINSIC(Vector256, get_AllBitsSet, 32, 0, {INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_cmpps, INS_cmppd}, HW_Category_Helper, HW_Flag_SpecialImport|HW_Flag_NoContainment|HW_Flag_NoRMWSemantics)
```
This ISA is available when AVX is available, and the intrinsic is recognized:
```
Named Intrinsic System.Runtime.Intrinsics.Vector256`1.get_AllBitsSet: Notify VM instruction set (Vector256) must be supported.
```
And the node is later emitted as `vpcmpeqd`:
https://github.com/dotnet/runtime/blob/7e681c1a02a4051d3d7b09bada6f9e323c975433/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1254-L1269

cc @tannergooding

### PR DESCRIPTION
**Pull request by echesakov**
**If Avx2.IsSupported**

`Vector128<T>.AllBits`
```asm
 vpcmpeqd xmmReg, xmmReg, xmmReg
```

`Vector256<T>.AllBits`
```asm
 vpcmpeqd ymmReg, ymmReg, ymmReg
```

**If Avx.IsSupported** (but not Avx2)

`Vector128<T>.AllBits`
```asm
 vpcmpeqd xmmReg, xmmReg, xmmReg
```

`Vector256<T>.AllBits`
```asm
 vxorps xmmReg, xmmReg, xmmReg
 vcmptruesd ymmReg, ymmReg, ymmReg
```

**Otherwise**

`Vector128<T>.AllBits`
```asm
 pcmpeqd xmm0, xmm0
```

`Vector256<T>.AllBits`

 *Software fallback*

 Clang generates similar instruction sequence for 256-bits vectors - https://godbolt.org/z/erd5sf 

**References:**

* https://stackoverflow.com/questions/45105164/set-all-bits-in-cpu-register-to-1-efficiently/
* https://stackoverflow.com/questions/37469930/fastest-way-to-set-m256-value-to-all-one-bits/

Fixes #48283

@dotnet/jit-contrib @tannergooding PTAL

### CODE REVIEW

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 1]
```diff
@@ -1252,22 +1252,31 @@ void CodeGen::genBaseIntrinsic(GenTreeHWIntrinsic* node)
         }
 
         case NI_Vector128_get_AllBitsSet:
-        case NI_Vector256_get_AllBitsSet:
-        {
             assert(op1 == nullptr);
-            if (varTypeIsFloating(baseType) && compiler->compOpportunisticallyDependsOn(InstructionSet_AVX))
+            if (compiler->compOpportunisticallyDependsOn(InstructionSet_AVX))
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1256]: This `if` shouldn't be needed. `emitIns_SIMD_R_R_R` should already be handling VEX vs non VEX

Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1256]: Likewise, while the behavior is the same, this is changing the instruction used for floating-point. `ins` was not `pcmpeqd` here but instead was `cmpps` or `cmppd`.

Both the Intel and AMD optimization manuals have notes similar to:
> Previous microarchitectures (before Intel Core microarchitecture) do not have explicit restrictions on
mixing integer and floating-point (FP) operations on XMM registers. For Intel Core microarchitecture,
mixing integer and floating-point operations on the content of an XMM register can degrade performance. Software should avoid mixed-use of integer/FP operation on XMM registers. Specifically:
• Use SIMD integer operations to feed SIMD integer operations. Use PXOR for idiom.
• Use SIMD floating-point operations to feed SIMD floating-point operations. Use XORPS for idiom.
• When floating-point operations are bitwise equivalent, use PS data type instead of PD data type.
  MOVAPS and MOVAPD do the same thing, but MOVAPS takes one less byte to encode the instruction.

and

>  Avoid mixing packed integer operations with packed floating point operations

Which implies that we should try to use the matching floating-point comparisons over the integer comparisons when the target type is floating-point.

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 2]
```diff
@@ -1252,22 +1252,31 @@ void CodeGen::genBaseIntrinsic(GenTreeHWIntrinsic* node)
...
+        case NI_Vector256_get_AllBitsSet:
+            assert(op1 == nullptr);
+            if (compiler->compOpportunisticallyDependsOn(InstructionSet_AVX2))
+            {
                 emit->emitIns_SIMD_R_R_R(INS_pcmpeqd, attr, targetReg, targetReg, targetReg);
             }
+            else
+            {
+                assert(compiler->compIsaSupportedDebugOnly(InstructionSet_AVX));
+                emit->emitIns_SIMD_R_R_R(INS_xorps, EA_16BYTE, targetReg, targetReg, targetReg);
```
Comment (tannergooding) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1275]: We shouldn't need to zero the target register when using `8` as the immediate.

`8` is `VCMPEQ_UQSS` which is "compare equal, unordered, non-signalling" which effectively means that if `left` and `right` are the same or either is NaN, return `true` and do not throw for signalling NaN if floating-point exceptions are enabled".

Since `left` and `right` are both `target`, it means it will always return `true` (the same is technically true for `15`).

You can confirm this with a program such as:
```csharp
using System;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

class Program
{
    static void Main(string[] args)
    {
        var nan = Vector128.Create(float.NaN);
        var one = Vector128.Create(1.0f);
        var inf = Vector128.Create(float.PositiveInfinity);

        Test(nan, FloatComparisonMode.UnorderedEqualNonSignaling);
        Test(nan, FloatComparisonMode.UnorderedTrueNonSignaling);

        Test(one, FloatComparisonMode.UnorderedEqualNonSignaling);
        Test(one, FloatComparisonMode.UnorderedTrueNonSignaling);

        Test(inf, FloatComparisonMode.UnorderedEqualNonSignaling);
        Test(inf, FloatComparisonMode.UnorderedTrueNonSignaling);
    }

    static void Test(Vector128<float> value, FloatComparisonMode mode)
    {
        Console.WriteLine($"{value,-41}, {mode,-28}: {Avx.Compare(value, value, mode)}");
    }
}
```

which prints:
```
<NaN, NaN, NaN, NaN>                     , UnorderedEqualNonSignaling  : <NaN, NaN, NaN, NaN>
<NaN, NaN, NaN, NaN>                     , UnorderedTrueNonSignaling   : <NaN, NaN, NaN, NaN>
<1, 1, 1, 1>                             , UnorderedEqualNonSignaling  : <NaN, NaN, NaN, NaN>
<1, 1, 1, 1>                             , UnorderedTrueNonSignaling   : <NaN, NaN, NaN, NaN>
<Infinity, Infinity, Infinity, Infinity> , UnorderedEqualNonSignaling  : <NaN, NaN, NaN, NaN>
<Infinity, Infinity, Infinity, Infinity> , UnorderedTrueNonSignaling   : <NaN, NaN, NaN, NaN>
```

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp (hunk 1 above)
Comment (echesakovMSFT) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1256]: > Which implies that we should try to use the matching floating-point comparisons over the integer comparisons when the target type is floating-point.

@tannergooding But do we expect the value of `Vector128/256<double>.AllBitsSet` to be used by a floating-point operation in some user scenarios? Do you have some examples in mind?

BTW, have you had a chance to read the SO posts I mentioned?

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp (hunk 2 above)
Comment (echesakovMSFT) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1275]: But why choosing `VCMPEQ_UQSS` over `VCMPTRUESS` when the latter does exactly (setting all the bits to ones) what we need?

Comment (echesakovMSFT) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1275]: The idea of emitting `xorps` before `vcmptruess` was also explained in one of the links I mentioned earlier - it is there to break dependency on the prior value in the register. 

Also see https://www.agner.org/optimize/optimizing_assembly.pdf page 65

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp (hunk 1 above)
Comment (tannergooding) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1256]: > But do we expect the value of Vector128/256<double>.AllBitsSet

Yes. `AllBitsSet` is a fairly central value for masking, comparing, and blending because it is the value returned when any element is `true`.

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp (hunk 2 above)
Comment (tannergooding) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1275]: > But why choosing VCMPEQ_UQSS over VCMPTRUESS when the latter does exactly (setting all the bits to ones) what we need?

For the scenario being considered; they both look to operate identically. I don't recall why `VCMPEQ_UQSS` was chosen originally over `VCMPTRUESS` but it was and is what we are emitting today.
I don't have a strong preference on which of these two are emitted provided they are always identical for `tgt, tgt, tgt`.

> The idea behind emitting xorps before vcmptruess was also explained in one of the links I mentioned earlier - it is there to break dependency on the prior value in the register.

We aren't doing this for any of the other comparisons or for intrinsics in general (outside LZCNT or POPCNT IIRC, because older Intel CPUs had a bug where it always treated it as having a dependency). Likewise, I don't think we should be unconditionally inserting a dependency breaking idiom here and instead this would be better handled by some general purpose check that identifies possible dependencies and therefore where inserting this would be beneficial.

Hardware intrinsics are used in performance oriented code paths and even if `xorps` is elided in the decoding step, it still takes up space in the decoder and is going to change the overall throughput of small-medium sized loops.
Additionally, Clang itself isn't emitting this idiom on haswell or newer (essentially any machine with AVX2+) and is not emitting it on skylake (which is what most of our benchmarks and even estimated cycle counts are based on).

Comment (echesakovMSFT) [reply src/coreclr/jit/hwintrinsiccodegenxarch.cpp:1275]: > Additionally, Clang itself isn't emitting this idiom on haswell or newer (essentially any machine with AVX2+) and is not emitting it on skylake (which is what most of our benchmarks and even estimated cycle counts are based on).

Right, for AVX2+ Clang emits `vpcmpeqd ymmReg, ymmReg, ymmReg` as I poined out in the first post and implemented for `NI_Vector256_get_AllBitsSet`.

**Comment by echesakovMSFT** [comment]
@tannergooding Updated PR - would you take another look?

**Review by tannergooding — APPROVED** [review]
LGTM. Thanks!
