### PR TITLE
Scope events to the execution of the entry point

### LINKED ISSUE #33494: SimpleWithWebApplicationBuilderTests.HelloWorld
## Error Message

```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'IServiceProvider'.
```

## Stacktrace

```
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException() in Microsoft.Extensions.DependencyInjection.dll:token 0x600011e+0xa
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000067+0x8
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000062+0x0
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) in Microsoft.Extensions.DependencyInjection.Abstractions.dll:token 0x6000094+0x34
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider) in Microsoft.Extensions.DependencyInjection.Abstractions.dll:token 0x6000095+0xe
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 202
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer() in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 172
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 462
   at Microsoft.AspNetCore.Mvc.FunctionalTests.SimpleWithWebApplicationBuilderTests..ctor(MvcTestFixture`1 fixture) in /_/src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs:line 16
```

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1183988&view=ms.vss-test-web.build-test-results-tab&runId=35603264&resultId=118571&paneView=debug

@davidfowl I'm concerned this happened on the first official build with your changes to WebApplicationFactory https://github.com/dotnet/aspnetcore/pull/33462/.

### PR DESCRIPTION
**Pull request by davidfowl**
- Today we're using the global event source and events that fire in the app domain get captured and this can result in capturing the wrong instances. This fix uses an async local to scope the events for the HostingEventListener to the execution of the application's entry point.
- Removed the RemoteExecutor as a result of this change.

Fixes https://github.com/dotnet/aspnetcore/issues/33494

PS: This doesn't try to handle multiple instances being created on the same execution context.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.HostFactoryResolver/tests/HostFactoryResolverTests.cs [hunk 1]
```diff
@@ -6,14 +6,13 @@
...
 using System.Threading;
-using Microsoft.DotNet.RemoteExecutor;
 using Xunit;
 
 namespace Microsoft.Extensions.Hosting.Tests
 {
     public class HostFactoryResolverTests
     {
-        public static bool RequirementsMet => RemoteExecutor.IsSupported && PlatformDetection.IsThreadingSupported;
+        public static bool RequirementsMet => PlatformDetection.IsThreadingSupported;
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.HostFactoryResolver/tests/HostFactoryResolverTests.cs:15]: would it make sense to now just use `PlatformDetection.IsThreadingSupported` since `RequirementsMet` became simplified?

**Review by maryamariyan — APPROVED** [review]

File: src/libraries/Microsoft.Extensions.HostFactoryResolver/tests/HostFactoryResolverTests.cs (hunk 1 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.HostFactoryResolver/tests/HostFactoryResolverTests.cs]: Done
