### PR TITLE
FileSystemGlobbing: Allow rootDir paths ending with separator to match files correctly

### LINKED ISSUE #36415: InMemoryDirectoryInfo does not work as expected
Microsoft.Extensions.FileSystemGlobbing

Steps to reproduce (file C:\pagefile.sys exists):

```c#
            var d = new InMemoryDirectoryInfo(@"C:\", new[] { @"pagefile.sys" });
            var l = d.EnumerateFileSystemInfos().ToList(); //returns empty list
```

Thus using 

```c#
public static PatternMatchingResult Match(this Matcher matcher, string rootDir, IEnumerable<string> files)
```

does not work as well - the result is always empty.

### PR DESCRIPTION
**Pull request by jozkee**
`InMemoryDirectoryInfo.IsRootDirectory` method was failing to evaluate correctly when the rootDir argument was ending with a separator e.g: `C:\` or `/`. This PR changes the condition to correctly support the aforementioned cases. 

Fixes https://github.com/dotnet/runtime/issues/36415, https://github.com/dotnet/runtime/issues/44767

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs [hunk 1]
```diff
@@ -119,13 +119,11 @@ public override IEnumerable<FileSystemInfoBase> EnumerateFileSystemInfos()
...
-                filePath.IndexOf(Path.DirectorySeparatorChar, rootDir.Length) != rootDir.Length)
-            {
-                return false;
-            }
+            int rootDirLength = rootDir.Length;
 
-            return true;
+            return filePath.StartsWith(rootDir, StringComparison.Ordinal) &&
+                (rootDir[rootDirLength - 1] == Path.DirectorySeparatorChar ||
+                filePath.IndexOf(Path.DirectorySeparatorChar, rootDirLength) == rootDirLength);
```
Comment (Jozkee) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs:126]: Existing condition on line 126 was meant to avoid false positives when the path started with `rootDir` but it wasn't the complete name of the directory e.g:

```
var matcher = new Matcher();
matcher.AddInclude(@"**\*");

Console.WriteLine(matcher.Match(rootDir: @"C:\foo", file: @"C:\foo2\bar.cs").HasMatches); 
// prints false, which is correct.
```

However that same condition was interfering when `rootDir = @"C:\foo\"` since `filePath.IndexOf(Path.DirectorySeparatorChar, rootDirLength)` was always going to return the index of the separator of the next directory.

Therefore I added condition on line 125 in order to skip the length check when rootDir ends with a separator.

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs [hunk 2]
```diff
@@ -119,13 +119,11 @@ public override IEnumerable<FileSystemInfoBase> EnumerateFileSystemInfos()
...
-            if (!filePath.StartsWith(rootDir, StringComparison.Ordinal) ||
-                filePath.IndexOf(Path.DirectorySeparatorChar, rootDir.Length) != rootDir.Length)
-            {
-                return false;
-            }
+            int rootDirLength = rootDir.Length;
 
-            return true;
+            return filePath.StartsWith(rootDir, StringComparison.Ordinal) &&
+                (rootDir[rootDirLength - 1] == Path.DirectorySeparatorChar ||
```
Comment (carlossanlop) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs:125]: Minor nit - Apply [IDE0056](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0056):
```suggestion
                (rootDir[^1] == Path.DirectorySeparatorChar ||
```

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs [hunk 3]
```diff
@@ -520,5 +607,36 @@ private void ExecuteAndVerify(Matcher matcher, string directoryPath, params stri
...
+        // https://github.com/dotnet/runtime/issues/36415
+        [Fact]
+        public void VerifyInMemoryDirectoryInfo_IsNotEmpty()
+        {
+            IEnumerable<string> files = new[] { @"pagefile.sys" };
+
+            var directoryInfo = new InMemoryDirectoryInfo(@"C:\", files);
+            IEnumerable<FileSystemInfoBase> fileSystemInfos = directoryInfo.EnumerateFileSystemInfos();
+
+            Assert.NotEmpty(fileSystemInfos);
```
Comment (carlossanlop) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs:634]: Shouldn't we instead assert for an exact number of files?

**Review by carlossanlop — APPROVED** [review]
LGTM. Left some minor comments.

**Comment by carlossanlop** [comment]
Actually, I noticed all the unit test failures are happening in `Microsoft.Extensions.FileSystemGlobbing.Tests`. Can you please take a look?

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs (hunk 2 above)
Comment (Jozkee) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs:125]: Can't use this language feature here since we target `netstandard2.0` and `net461` which doesn't support System.Index.

**Comment by Jozkee** [comment]
@carlossanlop I excluded scenarios using Windows-like absolute paths from running on non-Windows OSes since FileSystemGlobbing is OS-dependent when dealing with paths. That should fix the issues on CI.

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs [hunk 4]
```diff
@@ -801,30 +825,38 @@ private void ExecuteAndVerify(Matcher matcher, string directoryPath, params stri
...
 
-            string fakeWindowsPath = "C:\\This\\is\\a\\nested\\windows-like\\path\\somefile.cs";
-            Assert.True(fileMatcher.Match(Path.GetPathRoot(fakeWindowsPath), fakeWindowsPath).HasMatches);
-
+            if (PlatformDetection.IsWindows)
+            {
+                // Windows-like absolute paths are not supported on Unix.
+                string fakeWindowsPath = "C:\\This\\is\\a\\nested\\windows-like\\path\\somefile.cs";
+                Assert.True(fileMatcher.Match(Path.GetPathRoot(fakeWindowsPath), fakeWindowsPath).HasMatches);
+            }
```
Comment (carlossanlop) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs:839]: Optional: put this in a separate, Windows-specific unit test.

**Review by carlossanlop — APPROVED** [review]

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs (hunk 4 above)
Comment (Jozkee) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs:839]: I think one test is fine since I am linking the issue reporting the scenario on the top of the method.

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs (hunk 1 above)
Comment (iSazonov) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs:126]: It seems line 126 checks one char in position rootDirLength - why do we use whole IndexOf() method instead of simple index - filePath[rootDirLength] == Path.DirectorySeparatorChar - like in line 125?
