### PR TITLE
Fix Vector256.IsHardwareAccelerated in R2R binaries

### LINKED ISSUE #63818: JIT/Regression/JitBlue/Runtime_34587 crashes Crossgen2 compilation with an assertion failure
OS: all (observed on Windows and Linux)
Architecture: all (observed on x86 and x64, arm runs are somewhat flaky these days)
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1552238&view=ms.vss-test-web.build-test-results-tab

Diagnostics:

<pre>
  Starting:    JIT.Regression.XUnitWrapper (parallel test collections = on, max threads = 4)
    JIT\Regression\JitBlue\Runtime_34587\Runtime_34587\Runtime_34587.cmd [FAIL]
      Could Not Find C:\h\w\A2A20899\w\C2860A5B\e\JIT\Regression\JitBlue\Runtime_34587\Runtime_34587\IL-CG2\composite-r2r.dll
      Could Not Find C:\h\w\A2A20899\w\C2860A5B\e\JIT\Regression\JitBlue\Runtime_34587\Runtime_34587\Runtime_34587.dll.rsp
      Process terminated. Assertion failed.
         at ILCompiler.DependencyAnalysis.SortableDependencyNode.ObjectNodeComparer.Compare(DependencyNodeCore`1 x1, DependencyNodeCore`1 y1)
         at ILCompiler.Sorting.Implementation.MergeSortCore`5.Merge(T[] localCopyOfHalfOfArray, TDataStructure arrayToSort, Int32 index, Int32 halfLen, Int32 length, TComparer comparer)
         at ILCompiler.Sorting.Implementation.MergeSortCore`5.MergeSortHelper(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer, T[] scratchSpace)
         at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSortApi(TDataStructure arrayToSort, TComparer comparer)
         at ILCompiler.MergeSortApi.MergeSortAllowDuplicates[T](List`1 listToSort, IComparer`1 comparer)
         at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
         at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)
         at ILCompiler.Program.RunSingleCompilation(Dictionary`2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary`2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
         at ILCompiler.Program.Run(String[] args)
         at ILCompiler.Program.Main(String[] args)
      
      Return code:      1
</pre>

This got broken after @tannergooding's change

https://github.com/dotnet/runtime/commit/4f89b79d842ece91d04a47d5483c7b34abd2e954

but the change itself isn't to blame, it just uncovered a pre-existing bug in Crossgen2 regarding unstable ordering - we create two instances of ReadyToRunInstructionSetSupportSignature, one of which is the "baseline instruction set support" and the other is a PerMethodInstructionSetSupportFixup (for the method [Runtime_34587]Runtime_34587.<ValidateArm>g__ValidateVector256|1_11()) - both of which have the same key, "X86Base+Sse+Sse2,". The reason we need the instruction set fixup is the second loop (over _actualInstructionSetUnsupported) where the conditional block in the loop body is entered for the instruction set "ARM64_Rdm_Arm64" (while building for Windows x64 release):

https://github.com/dotnet/runtime/blob/2692407f03ce8b648c54daa4d3a3eb534132edc9/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L450

I have consulted @davidwrighton w.r.t. triage of this issue and we are in agreement that the proximate bug is in Crossgen2 that shouldn't generate a per-method instruction set fixup considering the instruction set is the same as the baseline. It's however unclear whether the root cause is truly in Crossgen2 or whether it might be caused by erroneous, imprecise or misinterpreted JIT reporting by means of the <code>notifyInstructionSetUsage</code> JitInterface API.

Thanks

Tomas

/cc @dotnet/crossgen-contrib @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by davidwrighton**
- If a function had a dependency on Vector256<T> but not on any Avx2 functionality then we would fail to produce an R2R image using a debug version of the compiler, and would generate an incorrect function where the result of calling Vector256.IsHardwareAccelerated would produce the wrong result.
- To fix this we now annotate the VectorXXX instruction sets so that if there is a negative depenedency on them during R2R generation, that the function is not available for use if the underlying actual instruction set is available to use at runtime.
- Adjust test Runtime_34587 to test instruction set manner in a way that allows testing crossgen2 instruction set variation
  - Move instruction set issupported checks into standalone functions to isolate the tests in the JIT/Crossgen2 compiler to better see exactly what is happening

Fix #63818

### CODE REVIEW

**Review by trylek — APPROVED** [review]
Looks good, thanks for fixing!

File: src/coreclr/tools/Common/JitInterface/CorInfoInstructionSet.cs [hunk 1]
```diff
@@ -294,6 +294,35 @@ public void ExpandInstructionSetByImplication(TargetArchitecture architecture)
...
+                {
+                case InstructionSet.X64_Vector128: return InstructionSet.X64_SSE;
+                case InstructionSet.X64_Vector256: return InstructionSet.X64_AVX;
+                }
+                break;
+            case TargetArchitecture.X86:
+                switch(input)
+                {
+                case InstructionSet.X86_Vector128: return InstructionSet.X86_SSE;
+                case InstructionSet.X86_Vector256: return InstructionSet.X86_AVX;
```
Comment (tannergooding) [inline src/coreclr/tools/Common/JitInterface/CorInfoInstructionSet.cs:319]: should `Vector<T>` be normalized on the same handling?

Should there be a comment covering that:
1. The ABI handling for Vector128/256 requires Sse/Avx, this is what's required for them to be passed around as `__m128` and `__m256`, respectively
2. The `Vector128/256.IsHardwareAccelerated` property only returns `true` under Sse2/Avx2 (this is when users can depend on most functions exposed to be SIMD accelerated)

File: src/tests/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587.cs [hunk 2]
```diff
@@ -80,7 +81,9 @@ public static int Main()
         bool succeeded = true;
 
         succeeded &= ValidateArm();
+        Console.WriteLine($"ValidateArm:{succeeded}");
```
Comment (tannergooding) [inline src/tests/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587.cs:84]: nit: This will only correctly report the first failure. If say, `Arm` fails it will also report all subsequent validations as failing.

Comment (tannergooding) [reply src/tests/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587.cs:84]: nit: If you fix this, might be nice to also add a space between `:` and `{succeeded}` to help with readability

**Review by tannergooding — APPROVED** [review]
LGTM. Left a nit on the tests and a question around `Vector<T>` and potentially adding a clarifying comment.

File: src/coreclr/tools/Common/JitInterface/CorInfoInstructionSet.cs (hunk 1 above)
Comment (davidwrighton) [reply src/coreclr/tools/Common/JitInterface/CorInfoInstructionSet.cs:319]: Abi handling is actually separate from this entirely and is handled by an abi stability protection construct which works independently of all of this. (Mostly as the ABI for both Vector128 and Vector256 doesn't match the native vector ABI on Windows, and there was a desire at one point to unify on the actual official ABI. This has not yet happened.

Comment (tannergooding) [reply src/coreclr/tools/Common/JitInterface/CorInfoInstructionSet.cs:319]: So is this check only for `IsHardwareAccelerated` then?

Comment (tannergooding) [reply src/coreclr/tools/Common/JitInterface/CorInfoInstructionSet.cs:319]: Just trying to understand what these particular checks line up with.

We support efficiently passing and some acceleration for `Vector128<T>` under `SSE` and `Vector256<T>` under `AVX`.
However, `IsHardwareAccelerated` will only return `true` under `SSE2` and `AVX2`, respectively.

Comment (davidwrighton) [reply src/coreclr/tools/Common/JitInterface/CorInfoInstructionSet.cs:319]: This lines up with the Vector128/Vector256 api usage in the JIT. Effectively, when the jit determines that it cannot use a  VectorXXX api it will call up, and notify crossgen that It has determined that if VectorXXX is useable at runtime via any intrinsics the generated code cannot be used. At that stage crossgen needs to encode that one of the instruction sets is not permitted, as it cannot encode that the VectorXXX intrinsics are not available. So, what it does it encode that the minimum required instruction set for the VectorXXX intrinsics is not available. Handling of IsHardwareAccelerated is actually a side-effect of this. In the encoding there are actually more states for how this works than is pleasant to contemplate. For instance, the options available to crossgen for encoding a method which calls `Vector256<T>.IsHardwareAccelerated` are:

1. Generate a method where IsHardwareAccelerated returns false, and mark that if Avx is supported, then the method cannot be used. (In this case the JIT will specify that support for the Vector256 instruction set is required to be disabled)
2. Generate a method where IsHardwareAccelerated returns false, and mark that if Avx2 is supported, then the method cannot be used, and also mark that Avx must be supported to use the method. (In this case the JIT will specify that support for the Vector256 instruction set is required to be enabled, but Avx2 support is required to be disabled.)
3. Generate a method where IsHardwareAccelerated returns true, and mark that if Avx2 is not supported then the method cannot be used. (In this case the JIT will specify that support for the Vector256 instruction set is required to be enabled, and Avx2 support is required to be enabled.)

The problem that this bug solves is that while the previous logic correctly handled cases 2 and 3, it did not handle case 1. (What would happen is that the JIT would notify crossgen that Vector256 could not be used, and be we would fail to record that there was an instruction set restriction on the generated code.)
