### PR TITLE
JIT: Switch GS cookie check temp reg to use r10 for tailcalls

### LINKED ISSUE #120780: Test failure: JIT/Directed/perffix/primitivevt/mixed1_cs_do/mixed1_cs_do.dll
**Failed in:** [runtime-coreclr outerloop 20251015.2](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1175446)

**Failed tests:**
```
R2R-CG2 linux x64 Checked @ (Alpine.322.Amd64.Open)Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.22-helix-amd64
    - global::Test_10w5d.testout1.TestEntryPoint()
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_r/test_3b_r.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_d/test_3b_d.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72699/b72699/b72699.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72932/b72932/b72932.dll
    - JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b89797/b89797/b89797.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_do/mixed1_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_ro/mixed1_cs_ro.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_do/mixed2_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_ro/mixed2_cs_ro.dll
R2R-CG2 linux x64 Checked no_tiered_compilation @ (Alpine.322.Amd64.Open)Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.22-helix-amd64
    - global::Test_10w5d.testout1.TestEntryPoint()
    - global::Test_10w5d.testout1.TestEntryPoint()
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_r/test_3b_r.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_d/test_3b_d.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72699/b72699/b72699.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72932/b72932/b72932.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_do/mixed1_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_ro/mixed1_cs_ro.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_do/mixed2_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_ro/mixed2_cs_ro.dll
    - JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b89797/b89797/b89797.dll
R2R-CG2 linux x64 Checked @ AzureLinux.3.Amd64.Open
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_r/test_3b_r.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_do/mixed1_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_ro/mixed1_cs_ro.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_do/mixed2_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_ro/mixed2_cs_ro.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72699/b72699/b72699.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72932/b72932/b72932.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_d/test_3b_d.dll
    - JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b89797/b89797/b89797.dll
R2R-CG2 linux x64 Checked no_tiered_compilation @ AzureLinux.3.Amd64.Open
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_r/test_3b_r.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_do/mixed1_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_ro/mixed1_cs_ro.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_do/mixed2_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_ro/mixed2_cs_ro.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72699/b72699/b72699.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72932/b72932/b72932.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_d/test_3b_d.dll
    - JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b89797/b89797/b89797.dll
R2R-CG2 osx x64 Checked @ OSX.13.Amd64.Open
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_d/test_3b_d.dll
    - JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b89797/b89797/b89797.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72699/b72699/b72699.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72932/b72932/b72932.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_r/test_3b_r.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_do/mixed1_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_ro/mixed1_cs_ro.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_do/mixed2_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_ro/mixed2_cs_ro.dll
R2R-CG2 osx x64 Checked no_tiered_compilation @ OSX.13.Amd64.Open
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_d/test_3b_d.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Methodical/tailcall/test_3b_r/test_3b_r.dll
    - global::Test_10w5d.testout1.TestEntryPoint()
    - JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b89797/b89797/b89797.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72699/b72699/b72699.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b72932/b72932/b72932.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_do/mixed1_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed1_cs_ro/mixed1_cs_ro.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_do/mixed2_cs_do.dll
    - JIT/Directed/perffix/primitivevt/mixed2_cs_ro/mixed2_cs_ro.dll
```

**Error message:**
```
Object reference not set to an instance of an object.
```

**Stack trace:**
```
   at Test_10w5d.testout1.Func_0_6_6_6_3()
   at Test_10w5d.testout1.Func_0_6_6_6()
   at Test_10w5d.testout1.Func_0_6_6()
   at Test_10w5d.testout1.Func_0_6()
   at Test_10w5d.testout1.Func_0()
   at Test_10w5d.testout1.TestEntryPoint()
   at Program.<<Main>$>g__TestExecutor51|0_52(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
rax was used before, but rax is used as an argument for the indirection cell for R2R tailcalls. r10 has a use for some pinvokes, but we do not tailcall for these.

Fix #120780

### CODE REVIEW

**Comment by jakobbotsch** [comment]
PTAL @dotnet/jit-contrib, another one of these, this time around the change that enabled tailcalls for functions with GS cookie checks on x64.

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -1773,6 +1773,11 @@ void CallArgs::AddFinalArgsAndDetermineABIInfo(Compiler* comp, GenTreeCall* call
         InsertAfterThisOrFirst(comp, NewCallArg::Primitive(arg).WellKnown(WellKnownArg::PInvokeCookie));
         // put destination into R10/EAX
         arg = comp->gtClone(call->gtCallAddr, true);
+        // On x64 the pinvoke target is passed in r11 which is the same
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:1776]: Ugh this should say r10. I will fix it as part of a follow up change to avoid rerunning CI.

**Review by AndyAyersMS — APPROVED** [review]
