### PR TITLE
Remove the `sealed` blittable layoutclass correctness fix because of backcompat.

### LINKED ISSUE #53542: Bug regarding inheritance in classes with explicit layout
Not fixing this for .NET 6 as we decided it's too risky to change runtime layouts now, it would also require bumping up the readytorun major version, but it's a bug nonetheless. For an explicit layout class with a base class, we place its fields as if the base class was twice its actual instance size. This is because we first take the base class instance size into account when calculating the layout itself in

https://github.com/dotnet/runtime/blob/ffb095ae87f3b4e88b03b21d0d945ed969054258/src/coreclr/vm/classlayoutinfo.cpp#L138

and we add the parent class size a second time in MethodTableBuilder::HandleExplicitLayout in

https://github.com/dotnet/runtime/blob/ffb095ae87f3b4e88b03b21d0d945ed969054258/src/coreclr/vm/methodtablebuilder.cpp#L8579

and

https://github.com/dotnet/runtime/blob/ffb095ae87f3b4e88b03b21d0d945ed969054258/src/coreclr/vm/methodtablebuilder.cpp#L8631

/cc @dotnet/crossgen-contrib, @dotnet/dotnet-coreclr

### LINKED ISSUE #54132: .Net 5.0 Application using NAudio libraries crashes without any error message
### Description
Hey Guys,

It seems something on .NET 5 made [NAudio (master-branch)](https://github.com/naudio/NAudio) crashing without any error message.

There is also an open [Issue](https://github.com/naudio/NAudio/issues/789) open on the NAudio´s GitHub.

After discussions i found out, that the runtime tries to access memory it does not own so Windows kills the process with Access Violation.

### Configuration
It happens on Windows 20H2 with **ANY** .NET 5.X.X version.

### Related information
Based on the [issue from NAudio](https://github.com/naudio/NAudio/issues/789), it was referred, that .NET Core 3.1 is working. I only could verify it for .NET 5.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
We can't do the correct thing and ensure we marshal blittable layout classes correctly in subclass situations due to backcompat issues, so remove that correctness check and add a massive comment block explaining why we can't so we don't accidentally regress this again.

Fixes https://github.com/dotnet/runtime/issues/54132

Fixes https://github.com/dotnet/runtime/issues/53542

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
@jkotas let me know if you want me to start a backport request for this for .NET 5.

File: src/coreclr/vm/ilmarshalers.cpp [hunk 1]
```diff
@@ -2496,10 +2496,14 @@ void ILBlittablePtrMarshaler::EmitConvertContentsNativeToCLR(ILCodeStream* pslIL
 
 bool ILBlittablePtrMarshaler::CanMarshalViaPinning()
 {
+    // [COMPAT] For correctness, we can't marshal via pinning if we might need to marshal differently at runtime.
+    // See calls to EmitExactTypeCheck where we check the runtime type of the object being marshalled.
```
Comment (jkotas) [inline src/coreclr/vm/ilmarshalers.cpp:2500]: Just to understand the history: Was the `EmitExactTypeCheck` check added for better compatibility with .NET Framework, or was it added as attempt to fix a bug?

Comment (jkoritzinsky) [reply src/coreclr/vm/ilmarshalers.cpp:2500]: It was added as an attempt to fix a compat issue from the StructMarshal IL stubs work. The old struct/class marshalling used the runtime type of a given type to determine how to marshal, not the metadata type. The Struct Marshalling IL Stubs initially used the metadata type. The type check was to bring back compat with the runtime type check because some customers were using it to map a native discriminated union to managed.

**Review by AaronRobinsonMSFT — APPROVED** [review]
Based on some of the discussion on the issue I think we should service 5.0 for this.

**Comment by jkotas** [comment]
> Based on some of the discussion on the issue I think we should service 5.0 for this.

Agree.

**Review by jkotas — APPROVED** [review]
