### PR TITLE
Fix explicit offset of ByRefLike fields.

### LINKED ISSUE #111260: TypeLoadException when a `ref struct` using explicit layout has fields of type `ref struct`
### Description

Context: Found in .NET 9 when experimenting with `ref struct` in P/Invoke scenarios. I want to make it clear that I'm not using "ref fields" but rather only "ref structs"; the fields of the struct are not `ref` (pointer) but the type is of `ref struct` (stack-only).

### Reproduction Steps

```cs
using System;
using System.Runtime.InteropServices;
					
public class Program
{
    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 8)]
    public ref struct Foo
    {
        [FieldOffset(0)]
        public Bar A;
        [FieldOffset(4)]
        public Bar B;
    }

    public ref struct Bar
    {
        public uint Value;
    }
	
    public static void Main()
    {
	var e = default(Foo);
	e.A.Value = 1;
	e.B.Value = 2;
	Console.WriteLine("1 + 2 = " + (e.A.Value + e.B.Value));
    }
}
```

### Expected behavior

A `ref struct` of explicit layout can have fields that are positioned using `FieldOffset` attribute where the type of the field is a `ref struct` without creating a runtime exception.

### Actual behavior

When a `ref struct` is using explicit struct layout, a `System.TypeLoadException` can occur regarding the field offset of the struct's field which the type is another `ref struct`.

```
Unhandled exception. System.TypeLoadException: Could not load type 'Foo' from assembly 'r2oeekw4.exe, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it contains an object field at offset 4 that is incorrectly aligned or overlapped by a non-object field.
   at Program.Main()
```

### Regression?

_No response_

### Known Workarounds

- Removing the `ref` from the nested struct.

### Configuration

- .NET 9
- macOS Ventura 13.6.5
- Apple M1 (`osx-arm64`)
- Not specific to any configuration.

### Other information

Hypothesis: The word `ref` in the context of a struct (stack-only) is confused to be in the context of a field (pointer); the field is mistaken for an object type with rules about field alignment when it's actually a struct.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
A ByRefLike type was previously forced to be pointer aligned so `ref` fields were implicitly aligned. Using Explicit layout one can create valid aligned ByRefLike types with no object pointers. This change propagates the base offset of the ByRefLike type and includes that for determining offsets of fields in the ByRefLike type.

Fixes dotnet/runtime#111260

### CODE REVIEW

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 1]
```diff
@@ -8677,30 +8677,28 @@ MethodTableBuilder::HandleExplicitLayout(
             else
             {
                 MethodTable *pByValueMT = pByValueClassCache[valueClassCacheIndex];
-                if (pByValueMT->IsByRefLike() || pByValueMT->ContainsGCPointers())
+                BOOL hasGcPointers = pByValueMT->ContainsGCPointers();
+                if (hasGcPointers || pByValueMT->IsByRefLike())
                 {
-                    if ((pFD->GetOffset() & ((ULONG)TARGET_POINTER_SIZE - 1)) != 0)
+                    if (hasGcPointers && ((pFD->GetOffset() & ((ULONG)TARGET_POINTER_SIZE - 1)) != 0))
```
Comment (jkotas) [inline src/coreclr/vm/methodtablebuilder.cpp:8683]: This whole if-statement should not be needed. The same error condition should be checked by `CheckValueClassLayout` too - just a bit slower - but it does not matter since we are going to fail anyway.

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 2]
```diff
@@ -8855,13 +8853,13 @@ MethodTableBuilder::HandleExplicitLayout(
 
 //*******************************************************************************
 // make sure that no object fields are overlapped incorrectly, returns the trust level
-/*static*/ ExplicitFieldTrust::TrustLevel MethodTableBuilder::CheckValueClassLayout(MethodTable * pMT, bmtFieldLayoutTag *pFieldLayout)
+/*static*/ ExplicitFieldTrust::TrustLevel MethodTableBuilder::CheckValueClassLayout(MethodTable * pMT, bmtFieldLayoutTag *pFieldLayout, UINT fieldBaseOffset)
```
Comment (jkotas) [inline src/coreclr/vm/methodtablebuilder.cpp:8856]: I do not think we need `fieldBaseOffset` arg. If there is a misaligned byref-like type inside the field type, loading of the field type is going to fail anyway, so we should not need to take the offset of the field into account when doing this check.

File: src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs [hunk 3]
```diff
@@ -81,7 +81,7 @@ protected override bool NeedsRecursiveLayout(int offset, TypeDesc fieldType)
                     return false;
                 }
 
-                if (offset % PointerSize != 0)
+                if (!fieldType.IsByRefLike && offset % PointerSize != 0)
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs:84]: Sure.

File: src/coreclr/vm/methodtablebuilder.cpp (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/methodtablebuilder.cpp:8856]: > If there is a misaligned byref-like type inside the field type, loading of the field type is going to fail anyway

Perhaps I'm not understanding this statement, but adding support for a ByRefLike type to not be aligned on a pointer is what is happening in this PR. In this case, I think I need to know the offset of the field so it can be computed in the explicit offset case. I think the base offset is used in native AOT, how is CoreCLR different?

Comment (jkotas) [reply src/coreclr/vm/methodtablebuilder.cpp:8856]: What is the test case that is going to fail if you delete the `fieldBaseOffset` argument and replace its uses with `0`?


If I am understanding this correctly, the `fieldBaseOffset` argument is trying to handle this situation:
```
[SequentialLayout(Pack=1)]
ref struct A
{
    [FieldOffset(3)]
    B b;
}

[SequentialLayout(Pack=1)]
ref struct B
{
    [FieldOffset(5)]
    ref byte p;
}
```
The type A is technically valid since `ref byte p` inside type A is aligned and the `fieldBaseOffset` argument is trying to make it work. My point is that we should have failed to load the type `B` earlier since it has mis-aligned byref, so we do not need to make the effort to make the type A technically valid.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/methodtablebuilder.cpp:8856]: > What is the test case that is going to fail if you delete the fieldBaseOffset argument and replace its uses with 0?

I need to propagate the field offset to the inner so `p` is computed to be at an offset of `4`. This would be fine on x86, but fail on x64. It is one of the tests I added.

```csharp
[SequentialLayout(Pack=1)]
ref struct A
{
    [FieldOffset(4)]
    B b;
}

ref struct B
{
    ref byte p;
}
```

File: src/coreclr/vm/methodtablebuilder.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/vm/methodtablebuilder.cpp:8683]: Sorry, I got confused between `CheckValueClassLayout` and `CheckByRefLikeValueClassLayout`. 

For byref-like types, I think this check is redundant with https://github.com/dotnet/runtime/pull/111584/files#diff-4b65f34bf68fdb80cc734cc2435c72ef7f86ef16b9f56af47c06b87761383d3aR8969-R8972 . I agree that this check is needed for types that are contain GC references, but that are not byref-like types.

It may be less confusing to move this alignment check to https://github.com/dotnet/runtime/pull/111584/files#diff-4b65f34bf68fdb80cc734cc2435c72ef7f86ef16b9f56af47c06b87761383d3aR8877 so that CheckValueClassLayout is responsible for the alignment check for both byref-like and non-byref-like types?

File: src/coreclr/vm/methodtablebuilder.cpp (hunk 2 above)
Comment (jkotas) [reply src/coreclr/vm/methodtablebuilder.cpp:8856]: Got it. I see why this arg is needed now.

File: src/coreclr/vm/methodtablebuilder.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/methodtablebuilder.cpp]: Excellent suggestions. Please take a look at latest. I hope I was able to capture this suggestion.

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 4]
```diff
@@ -8873,18 +8862,26 @@ MethodTableBuilder::HandleExplicitLayout(
     bmtFieldLayoutTag *vcLayout = (bmtFieldLayoutTag*) qb.AllocThrows(fieldSize * sizeof(bmtFieldLayoutTag));
     memset((void*)vcLayout, nonoref, fieldSize);
 
-    // If the type contains pointers fill it out from the GC data
+    // If the type contains pointers fill it out from the GC data and validate OREF alignment.
     if (pMT->ContainsGCPointers())
     {
-        // use pointer series to locate the orefs
+        // Use pointer series to locate the OREFs
```
Comment (jkotas) [inline src/coreclr/vm/methodtablebuilder.cpp:8868]:
```suggestion
        // If the type contains pointers, it has to start at aligned offset. The alignment of the pointer
        // series was checked earlier.
       if (fieldBaseOffset % TARGET_POINTER_SIZE != 0)
       {
           // If we got here, then an OREF is misaligned.
           return ExplicitFieldTrust::kNone;
       }

        // Use pointer series to locate the OREFs
```

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 5]
```diff
@@ -8873,18 +8862,26 @@ MethodTableBuilder::HandleExplicitLayout(
...
 
-            memset((void*)&vcLayout[pSeries->GetSeriesOffset() - OBJECT_SIZE], oref, pSeries->GetSeriesSize() + pMT->GetBaseSize());
+            // Get offset into the value class of the first pointer field (includes a +Object)
+            size_t offset = pSeries->GetSeriesOffset() - OBJECT_SIZE;
+            if ((fieldBaseOffset + offset) % TARGET_POINTER_SIZE != 0)
+            {
+                // If we got here, then an OREF is misaligned.
+                return ExplicitFieldTrust::kNone;
+            }
+
```
Comment (jkotas) [inline src/coreclr/vm/methodtablebuilder.cpp:8883]:
```suggestion
```
We can check this just once before the loop starts.

**Review by jkotas — APPROVED** [review]
LGTM. Thank you!

**Comment by AaronRobinsonMSFT** [comment]
@jkotas I'm missing something here. I missed a case for the layout engine and with byrefs and when trying to fix it, I now see failures for `Explicit` involving class are off by 8 bytes - I assume this is the MethodTable issue. I guess my fix for byrefs was wrong, but I'm not sure where to fix it now.

**Comment by AaronRobinsonMSFT** [comment]
> @jkotas or @MichalStrehovsky So it looks like I could either create a new property on `DefType` that is `ContainsByRefs` or update `ContainsGCPointers` to include byrefs in the computation. Is there a right way to do this?

I opted for adding a new `ContainsByRefs` property.

**Comment by jkotas** [comment]
> I opted for adding a new ContainsByRefs property.

Yes, I do not think that you want to overload the meaning of `ContainsGCPointers`

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 6]
```diff
@@ -269,6 +269,24 @@ public override bool ComputeContainsGCPointers(DefType type)
...
+            if (!type.IsByRefLike)
+                return false;
+
+            foreach (var field in type.GetFields())
+            {
+                if (field.IsStatic)
+                    continue;
+
+                TypeDesc fieldType = field.FieldType;
+                if (fieldType.IsByRef)
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:283]: `fieldType` is a `TypeDesc`, not a `DefType`. I can perform a cast and check and then fallback?

**Review by Karinza38 — COMMENTED** [review]
Karinza38

File: src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs [hunk 7]
```diff
@@ -74,20 +74,15 @@ protected override FieldLayoutTag GetIntervalDataForType(int offset, TypeDesc fi
...
 
-                if (offset % PointerSize != 0)
-                {
-                    // Misaligned struct with GC pointers or ByRef
-                    ThrowFieldLayoutError(offset);
-                }
-
-                return true;
+                // Valuetypes with GC references and byref-like types need to be checked for overlaps and alignment
+                return ((MetadataType)fieldType).ContainsGCPointers || fieldType.IsByRefLike;
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Common/ExplicitLayoutValidator.cs:85]: Would ContainsByRefs be more precise than IsByRefLike?

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 8]
```diff
@@ -269,6 +269,27 @@ public override bool ComputeContainsGCPointers(DefType type)
...
+                return false;
+
+            foreach (var field in type.GetFields())
+            {
+                if (field.IsStatic)
+                    continue;
+
+                TypeDesc fieldType = field.FieldType;
+                if (fieldType.IsByRef
+                    || ((fieldType is DefType df) && df.ContainsByRefs))
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:284]: Nit: we avoid `is` checks for DefType. These casts all involve deep walks of type hierarchy since it's an abstract type derived by another abstract type. ByRefLike type is guaranteed to be a `DefType`.

```suggestion
                    || (fieldType.IsByRefLike && ((DefType)fieldType).ContainsByRefs))
```

**Review by MichalStrehovsky — APPROVED** [review]
Do we need to add this to breaking-change-rules.md? Would we consider it a breaking change to add a `ref` field to a `ref struct` that didn't previously have a `ref` field?

(We do consider switching between `struct` and `ref struct` a breaking change in that doc.)

**Comment by AaronRobinsonMSFT** [comment]
> Do we need to add this to breaking-change-rules.md? 

+1. I wasn't aware of this document, but I've updated it accordingly.

File: docs/coding-guidelines/breaking-change-rules.md [hunk 9]
```diff
@@ -169,6 +169,8 @@ Breaking Change Rules
 
 * Changing a `struct` type to a `ref struct` type and vice versa
 
+* Adding a new `ref` field to a type
```
Comment (MichalStrehovsky) [inline docs/coding-guidelines/breaking-change-rules.md:172]: Would something along these lines be more precise?

```suggestion
* Adding a new `ref` field to a type that didn't have any `ref` field before (recursively)
```

Comment (AaronRobinsonMSFT) [reply docs/coding-guidelines/breaking-change-rules.md:172]: Yes, that is much clearer and actually the breaking change issue. Thanks.

File: docs/coding-guidelines/breaking-change-rules.md [hunk 10]
```diff
@@ -169,6 +169,8 @@ Breaking Change Rules
 
 * Changing a `struct` type to a `ref struct` type and vice versa
 
+* Adding a new `ref` field to a type that didn't have any `ref` field before (recursively)
```
Comment (jkotas) [inline docs/coding-guidelines/breaking-change-rules.md:172]: I am not following what's the rationale for this. How is this different from adding/removing any fields? We have no guarantees for internal type layout compatibility, unless the guarantee is explicitly documented. 

"Changing a `struct` type to a `ref struct` type and vice versa" is very different - it is very obvious compile time breaking change.

Comment (AaronRobinsonMSFT) [reply docs/coding-guidelines/breaking-change-rules.md:172]: I think the point of it is that now add a `ref` field could break someone if they were using the type in an `Explicit` offset scenario. For example, the BCL has some `ref struct` that just has an `int `field. A user consumes that type in a user defined type as an `Explicit` field and the containing library is published to NuGet. In the next major version a `ref int` field is added. When that NuGet package is consumed on a new BCL, the library fails to load because the `ref int` field forces a new alignment restriction.

By definition this would now break. We can argue if it matters, but it would cause a failure at type load time.

Comment (jkotas) [reply docs/coding-guidelines/breaking-change-rules.md:172]: > I think the point of it is that now adding a ref field could break someone if they were using the type in an Explicit offset scenario. 

It is the case for any field changes in public BCL value types. You can get the same break by adding/removing `int` or `object` fields too. There is nothing special about ref fields here.

Field layout of BCL value types is not a public contract that people can depend on, unless it is explicitly documented for specific types.

Comment (AaronRobinsonMSFT) [reply docs/coding-guidelines/breaking-change-rules.md:172]: > "Changing a struct type to a ref struct type and vice versa" is very different - it is very obvious compile time breaking change.

> It is the case for any field changes in public BCL value types. You can get the same break by adding/removing int or object fields too. There is nothing special about ref fields here.

Between the two statements above, it looks like the distinction in this case is compile time vs run time failure. Is that the conversation we are having? In the sense that compile time failure is not acceptable, but run time failure is?

Comment (jkotas) [reply docs/coding-guidelines/breaking-change-rules.md]: There happens to be a compile time vs. runtime time difference between these two case, but that's just accidental. Runtime breaking changes are not acceptable either in general.

I think that the discussion that we are having here is about distinction between what we define as a breaking change vs. change that can break apps that depend on undocumented behaviors.

Comment (AaronRobinsonMSFT) [reply docs/coding-guidelines/breaking-change-rules.md]: > I think that the discussion that we are having here is about distinction between what we define as a breaking change vs. change that can break apps that depend on undocumented behaviors.

Okay, Thanks.

> Field layout of BCL value types is not a public contract that people can depend on, unless it is explicitly documented for specific types.

Is this explicitly documented somewhere?

Comment (jkotas) [reply docs/coding-guidelines/breaking-change-rules.md]: > Is this explicitly documented somewhere?

I am not sure whether it is mentioned in the official docs. Should we mention it in https://learn.microsoft.com/en-us/dotnet/standard/native-interop/best-practices ?

This falls into the same category as dangers of private reflection that are not particularly well documented either.

Comment (AaronRobinsonMSFT) [reply docs/coding-guidelines/breaking-change-rules.md]: > Should we mention it in https://learn.microsoft.com/en-us/dotnet/standard/native-interop/best-practices ?

Seems like a reasonable place to mention it. As you mentioned this is also a refelction story. Is there a general place for reflection or type system details that you'd recommend?

Comment (MichalStrehovsky) [reply docs/coding-guidelines/breaking-change-rules.md]: > It is the case for any field changes in public BCL value types. You can get the same break by adding/removing `int` or `object` fields too. There is nothing special about ref fields here.

I thought we already consider such things breaking as well - for example adding an object typed field to a struct makes the struct no longer meet `unmanaged` constraint. I recall Roslyn team even did work to put a dummy object filed into such struct for `ref` assemblies because these non-contractual private implementation details actually matter.

Comment (jkotas) [reply docs/coding-guidelines/breaking-change-rules.md]: If the libraries folks agree, I think it would be fine to explicitly match the current Roslyn behavior and say that adding first field of a new kind to an existing value type is disallowed change. Kind can be any of objref, byref or generic type argument, and the rule applies recursively. 

Introducing new significant state in existing value types is close to impossible to do in compatible way for other reasons (e.g. it is why we have both DateTime and DateTimeOffset), so these situations do not come up in practice. I guess it is the reason why nobody bothered to mention it in the breaking changes doc up until now.

**Comment by AaronRobinsonMSFT** [comment]
native AOT legs failing due to https://github.com/dotnet/runtime/issues/112021

File: docs/coding-guidelines/breaking-change-rules.md (hunk 10 above)
Comment (AaronRobinsonMSFT) [reply docs/coding-guidelines/breaking-change-rules.md]: I will create a discussion issue for this topic and loop in libraries folks. Updating the markdown is a cheaper PR than continually running the build/test legs.

Comment (jkotas) [reply docs/coding-guidelines/breaking-change-rules.md]: > This falls into the same category as dangers of private reflection that are not particularly well documented either.

I have created https://github.com/dotnet/runtime/issues/112114

Comment (jkotas) [reply docs/coding-guidelines/breaking-change-rules.md]: > Should we mention it in https://learn.microsoft.com/en-us/dotnet/standard/native-interop/best-practices

Opened https://github.com/dotnet/docs/pull/44672
