### PR TITLE
Remove usage of `Precode::GetPrecodeFromEntryPoint` in WASM.

### LINKED ISSUE #120319: [wasm][coreclr] bc.GenericVirtualMethod<string> failing in the interpreter test
It fails with
```
...
bc.GenericVirtualMethod<string>
ASSERT FAILED
        Expression: !"Precode::GetPrecodeFromEntryPoint is not supported with Portable EntryPoints"
        Location:   line 170 in /Users/rodo/git/runtime-main/src/coreclr/vm/precode_portable.cpp
        Function:   GetPrecodeFromEntryPoint
        Process:    42
Frame (InterpreterFrame): 0x4fecac
   0) InterpreterTest::TestVirtual, IR_00e3
   1) InterpreterTest::RunInterpreterTests, IR_04ee
   2) InterpreterTest::Main, IR_0029
```
the failing part
```
        Console.WriteLine("bc.GenericVirtualMethod<string>");
        retType = bc.GenericVirtualMethod<string>(out isBase);
        if (retType != typeof(string) || isBase)
            return false;
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
This inserted ifdefs and reorganizes things to remove usage of `Precode::GetPrecodeFromEntryPoint` in WASM.

Fixes https://github.com/dotnet/runtime/issues/120319

### CODE REVIEW

File: src/coreclr/vm/ceeload.cpp [hunk 1]
```diff
@@ -1386,13 +1392,20 @@ void Module::AllocateMaps()
...
     m_ILCodeVersioningStateMap.pTable = &m_MethodDefToDescMap.pTable[m_MethodDefToDescMap.dwCount];
+#endif // FEATURE_CODE_VERSIONING
 
     m_FieldDefToDescMap.pNext  = NULL;
     m_FieldDefToDescMap.supportedFlags = FIELD_DEF_MAP_ALL_FLAGS;
+
+#ifdef FEATURE_CODE_VERSIONING
     m_FieldDefToDescMap.pTable = &m_ILCodeVersioningStateMap.pTable[m_ILCodeVersioningStateMap.dwCount];
+#else // !FEATURE_CODE_VERSIONING
+    m_FieldDefToDescMap.pTable = NULL;
```
[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/vm/ceeload.cpp]: This looks like valid feedback.

Alternatively, we can move `m_ILCodeVersioningStateMap` to be last to make the ifdef simpler.

File: src/coreclr/vm/dllimport.cpp [hunk 2]
```diff
@@ -5650,13 +5650,17 @@ PCODE PInvoke::GetStubForILStub(PInvokeMethodDesc* pNMD, MethodDesc** ppStubMD,
     {
         CONSISTENCY_CHECK(pNMD->IsVarArgs());
 
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+        _ASSERTE(false && "Vararg P/Invoke is not supported with portable entrypoints");
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]: We can throw `IDS_EE_VARARG_NOT_SUPPORTED` instead of asserting.

File: src/coreclr/vm/dllimportcallback.h [hunk 3]
```diff
@@ -247,7 +247,8 @@ class UMEntryThunkData
 
         PCODE entryPoint = m_pUMThunkMarshInfo->GetExecStubEntryPoint();
 
-#ifdef FEATURE_INTERPRETER
+        bool nullEntryPoint;
+#if defined(FEATURE_INTERPRETER) && !defined(FEATURE_PORTABLE_ENTRYPOINTS)
```
Comment (jkotas) [inline src/coreclr/vm/dllimportcallback.h]: The whole UMEntryThunk should be excluded for FEATURE_PORTABLE_ENTRYPOINTS. This can be larger ifdef.

File: src/coreclr/vm/jitinterface.cpp [hunk 4]
```diff
@@ -9124,17 +9124,22 @@ void CEEInfo::getFunctionEntryPoint(CORINFO_METHOD_HANDLE  ftnHnd,
     {
         // FCalls can be called directly
         ret = (void*)ECall::GetFCallImpl(ftn, false /* throwForInvalidFCall */);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:9131]: This returns native entrypoint, but the other paths through this method return portable entrypoint. 

The only why this mismatch is not causing problems at the moment is that the interpreter does not call `getFunctionEntryPoint` currently.

Maybe wrap this whole method in `#ifndef FEATURE_PORTABLE_ENTRYPOINTS` so that the problem is immediately obvious in case the interpreter starts calling it?

File: src/coreclr/vm/dllimportcallback.h (hunk 3 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimportcallback.h]: Ugh. That is going to be a bunch more changes. I'll see what this looks like.

Comment (jkotas) [reply src/coreclr/vm/dllimportcallback.h]: I would be ok with something like this in this PR to make it build:
```
#ifdef FEATURE_PORTABLE_ENTRYPOINTS
    // WASM TODO: Exclude UMEntryThunk for FEATURE_PORTABLE_ENTRYPOINTS
#else
...
```

File: src/coreclr/vm/comdelegate.cpp [hunk 5]
```diff
@@ -1344,6 +1344,10 @@ LPVOID COMDelegate::ConvertToCallback(OBJECTREF pDelegateObj)
     }
     else
     {
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+        COMPlusThrow(kNotSupportedException);
```
Comment (jkotas) [inline src/coreclr/vm/comdelegate.cpp]:
```suggestion
        COMPlusThrow(kPlatformNotSupportedException, W("PlatformNotSupported_DynamicEntrypoint"));
```
Match the error we use for this sort of situation in naot

File: src/coreclr/vm/corhost.cpp [hunk 6]
```diff
@@ -714,7 +711,13 @@ HRESULT CorHost2::CreateDelegate(
     if (appDomainID != DefaultADID)
         return HOST_E_INVALIDOPERATION;
 
+    HRESULT hr = S_OK;
     BEGIN_EXTERNAL_ENTRYPOINT(&hr);
+
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+    hr = E_NOTIMPL;
```
Comment (jkotas) [inline src/coreclr/vm/corhost.cpp:718]: `HasUnmanagedCallersOnlyAttribute` path below should work fine.

(I am ok the larger ifdef, and fixing only if we need to.)

File: src/coreclr/vm/dllimport.cpp [hunk 7]
```diff
@@ -2014,6 +2014,10 @@ void PInvokeStubLinker::Begin(DWORD dwStubFlags)
     {
         if (SF_IsDelegateStub(dwStubFlags))
         {
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+            COMPlusThrow(kNotSupportedException);
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]: Is this reachable? It may want to be an assert.

File: src/coreclr/vm/dllimport.cpp [hunk 8]
```diff
@@ -2186,6 +2191,10 @@ void PInvokeStubLinker::DoPInvoke(ILCodeStream *pcsEmit, DWORD dwStubFlags, Meth
     }
     else // native-to-managed
     {
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+        COMPlusThrow(kNotSupportedException);
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]: dtto

File: src/coreclr/vm/dllimportcallback.cpp [hunk 9]
```diff
@@ -449,3 +434,18 @@ VOID UMThunkMarshInfo::RunTimeInit()
     // Must be the last thing we set!
     InterlockedCompareExchangeT<PCODE>(&m_pILStub, pFinalILStub, (PCODE)1);
 }
+#endif // !FEATURE_PORTABLE_ENTRYPOINTS
+
+// FailFast if a method marked UnmanagedCallersOnlyAttribute is
+// invoked directly from managed code. UMThunkStub.asm check the
+// mode and call this function to failfast.
+VOID STDCALL ReversePInvokeBadTransition()
```
Comment (jkotas) [inline src/coreclr/vm/dllimportcallback.cpp]: Nit: It may look better for this to live in jithelpers.cpp next to `JIT_ReversePInvokeEnterRare`. It is the central place where this is enforced.

File: src/coreclr/vm/dllimportcallback.h [hunk 10]
```diff
@@ -247,7 +246,8 @@ class UMEntryThunkData
 
         PCODE entryPoint = m_pUMThunkMarshInfo->GetExecStubEntryPoint();
 
-#ifdef FEATURE_INTERPRETER
+        bool nullEntryPoint;
```
Comment (jkotas) [inline src/coreclr/vm/dllimportcallback.h]:
```suggestion
        bool setTarget = true;
```

File: src/coreclr/vm/dllimportcallback.h [hunk 11]
```diff
@@ -260,9 +260,13 @@ class UMEntryThunkData
                 entryPoint = (PCODE)0;
```
Comment (jkotas) [inline src/coreclr/vm/dllimportcallback.h]:
```suggestion
                setTarget = false;
```

File: src/coreclr/vm/dllimportcallback.h [hunk 12]
```diff
@@ -260,9 +260,13 @@ class UMEntryThunkData
...
             }
         }
-
-        if (entryPoint != (PCODE)0)
+        nullEntryPoint = entryPoint == (PCODE)0;
+#else // !FEATURE_INTERPRETER
+        _ASSERTE(entryPoint != (PCODE)0);
+        nullEntryPoint = false;
```
Comment (jkotas) [inline src/coreclr/vm/dllimportcallback.h]:
```suggestion
```

File: src/coreclr/vm/dllimportcallback.h [hunk 13]
```diff
@@ -260,9 +260,13 @@ class UMEntryThunkData
...
 #endif // FEATURE_INTERPRETER
+
+        if (!nullEntryPoint)
```
Comment (jkotas) [inline src/coreclr/vm/dllimportcallback.h]:
```suggestion
        if (setTarget)
```

File: src/coreclr/vm/interpexec.cpp [hunk 14]
```diff
@@ -796,10 +799,14 @@ void InterpExecMethod(InterpreterFrame *pInterpreterFrame, InterpMethodContextFr
                     break;
                 case INTOP_STORESTUBCONTEXT:
                 {
-                    void *thunkData = GetMostRecentUMEntryThunkData();
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+                    COMPlusThrow(kNotSupportedException);
```
Comment (jkotas) [inline src/coreclr/vm/interpexec.cpp]: This should be unreachable. Assert or move the ifdef before `INTOP_STORESTUBCONTEXT` so that we take the default path?

File: src/coreclr/vm/method.hpp [hunk 15]
```diff
@@ -1443,31 +1453,41 @@ class MethodDesc
...
-
-        if (!IsNativeCodeStableAfterInit())
-            return FALSE;
-
-        return IsPointingToNativeCode();
-    }
-
     // Note: We are skipping the prestub based on addition information from the JIT.
     // (e.g. that the call is on same this ptr or that the this ptr is not null).
     // Thus we can end up with a running NGENed method for which IsPointingToNativeCode is false!
```
Comment (jkotas) [inline src/coreclr/vm/method.hpp]:
```suggestion
```
Obsolete comment

File: src/coreclr/vm/method.hpp [hunk 16]
```diff
@@ -1443,31 +1453,41 @@ class MethodDesc
...
 
         if (!HasPrecode())
             return TRUE;
 
         return GetPrecode()->IsPointingToNativeCode(GetNativeCode());
+#endif // FEATURE_PORTABLE_ENTRYPOINTS
+    }
+
+    //Is this method currently pointing to native code that will never change?
+    BOOL IsPointingToStableNativeCode()
```
Comment (jkotas) [inline src/coreclr/vm/method.hpp:1475]: This is only called from !FEATURE_PORTABLE_ENTRYPOINTS so the whole method can be ifdefed out instead.

File: src/coreclr/vm/method.hpp [hunk 17]
```diff
@@ -1443,31 +1453,41 @@ class MethodDesc
...
-        if (!IsNativeCodeStableAfterInit())
-            return FALSE;
-
-        return IsPointingToNativeCode();
-    }
-
     // Note: We are skipping the prestub based on addition information from the JIT.
     // (e.g. that the call is on same this ptr or that the this ptr is not null).
     // Thus we can end up with a running NGENed method for which IsPointingToNativeCode is false!
     BOOL IsPointingToNativeCode()
```
Comment (jkotas) [inline src/coreclr/vm/method.hpp:1461]: This is only called from !FEATURE_PORTABLE_ENTRYPOINTS code, except one place in encee.cpp. The one place in encee.cpp is prestub skipping optimization that can use `IsPointingToPrestub` or whatever is the right way to do that.

File: src/coreclr/vm/interpexec.cpp [hunk 18]
```diff
@@ -679,10 +679,15 @@ static void CallPreStub(MethodDesc *pMD)
     STATIC_STANDARD_VM_CONTRACT;
     _ASSERTE(pMD != NULL);
 
-    if (!pMD->IsPointingToPrestub() &&
-        pMD->GetTemporaryEntryPoint() && // The prestub may not yet be ready to be used, so force temporary entry point creation, and check again.
-        !pMD->IsPointingToPrestub())
-        return;
+    // The prestub may not yet be ready to be used, so force temporary entry point creation, and check again.
```
Comment (jkotas) [inline src/coreclr/vm/interpexec.cpp]: We do a simple `IsPointingToPrestub` check in other places as DoPrestub skipping optimization, e.g. `ReflectionInvocation_CompileMethod`. If the correct way to do the prestub skipping is this, we have bugs in the other places.

File: src/coreclr/vm/prestub.cpp [hunk 19]
```diff
@@ -2467,7 +2479,12 @@ PCODE TheUMThunkPreStub()
 {
     LIMITED_METHOD_CONTRACT;
 
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+    PORTABILITY_ASSERT("TheUMThunkPreStub not supported with FEATURE_PORTABLE_ENTRYPOINTS");
+    return (PCODE)0;
```
Comment (jkotas) [inline src/coreclr/vm/prestub.cpp]:
```suggestion
    UNREACHABLE_MSG("TheUMThunkPreStub not supported with FEATURE_PORTABLE_ENTRYPOINTS");
```
There is nothing to port here.

File: src/coreclr/vm/stubmgr.cpp [hunk 20]
```diff
@@ -1737,6 +1739,10 @@ BOOL ILStubManager::TraceManager(Thread *thread,
     }
     else if (pStubMD->IsReverseStub())
     {
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+        PORTABILITY_ASSERT("NYI: Reverse P/Invoke stubs with FEATURE_PORTABLE_ENTRYPOINTS.");
```
Comment (jkotas) [inline src/coreclr/vm/stubmgr.cpp]: Nothing to port here. I think the whole `IsReverseStub` case can be ifdefed.

File: src/coreclr/vm/syncblk.h [hunk 21]
```diff
@@ -744,19 +747,24 @@ class InteropSyncBlockInfo
...
     UMEntryThunkData* GetUMEntryThunk()
     {
         LIMITED_METHOD_CONTRACT;
         return m_pUMEntryThunk;
     }
+#endif // !FEATURE_PORTABLE_ENTRYPOINTS
 
 private:
+#ifdef FEATURE_PORTABLE_ENTRYPOINTS
+    void*               m_pUMEntryThunk; // Dummy field
```
Comment (jkotas) [inline src/coreclr/vm/syncblk.h]: Do we have layout of this hardcoded somewhere to need a dummy field? It can use a comment why we need the dummy field.

File: src/coreclr/vm/corhost.cpp (hunk 6 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/corhost.cpp:718]: I'd prefer to keep this for now. The hosting entrypoint isn't something I'd expect to get a lot of use with on WASM.

File: src/coreclr/vm/dllimport.cpp (hunk 7 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp]: I would prefer the exception for now. It isn't obvious to me why this wouldn't be reachable. If we can determine that for sure, then an assert might be appropriate.

Comment (jkotas) [reply src/coreclr/vm/dllimport.cpp]: `COMDelegate::ConvertToCallback` should be the only way to create these stubs and we block it there.

File: src/coreclr/vm/interpexec.cpp (hunk 14 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp]: Sure. That works too.

File: src/coreclr/vm/stubmgr.cpp (hunk 20 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/stubmgr.cpp]: It is possible, but the issue I have is `IsReverseStub()` still exists. Which means we should handle/check the case properly and error out. If we ifdef it out entirely the if/else chain will fall the default which isn't correct. I would prefer, especially in the diagnotics space, to fail hard so people know what is wrong/missing.

File: src/coreclr/vm/syncblk.h (hunk 21 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/syncblk.h]: This is because of C++ syntax using the initializer list. The syntax forces us to start with `:`, but all fields have related ifdef clauses. Which means knowing which one is first is tricky. Having a simple default makes this "just work". I'll expand the comment.

Comment (jkotas) [reply src/coreclr/vm/syncblk.h]: yeah, C++ initializers do not work well with ifdefs. 

Also, this means that `InteropSyncBlockInfo` should be unreachable on wasm, the compiler is hopefully going to take care of removing most of what's left, so the extra field should not introduce any overhead.

File: src/coreclr/vm/stubmgr.cpp [hunk 22]
```diff
@@ -1751,6 +1756,7 @@ BOOL ILStubManager::TraceManager(Thread *thread,
             LOG((LF_CORDB, LL_INFO10000, "ILSM::TraceManager: COM-to-CLR case %p\n", target));
         }
         trace->InitForManaged(target);
+#endif // FEATURE_PORTABLE_ENTRYPOINTS
```
Comment (jkotas) [inline src/coreclr/vm/stubmgr.cpp]:
```suggestion
    else if (pStubMD->IsReversePInvokeStub())
    {
#ifdef FEATURE_PORTABLE_ENTRYPOINTS
        UNREACHABLE_MSG("Reverse P/Invoke stubs not supported with FEATURE_PORTABLE_ENTRYPOINTS.");
#else // !FEATURE_PORTABLE_ENTRYPOINTS
        // This is reverse P/Invoke stub, the argument is UMEntryThunkData
        UMEntryThunkData *pEntryThunk = (UMEntryThunkData*)arg;
        target = pEntryThunk->GetManagedTarget();
        LOG((LF_CORDB, LL_INFO10000, "ILSM::TraceManager: Reverse P/Invoke case %p\n", target));
        trace->InitForManaged(target);
#endif // FEATURE_PORTABLE_ENTRYPOINTS        
    }
    else if (pStubMD->IsCOMToCLRStub())
    {
        // This is COM-to-CLR stub, the argument is the target
        target = (PCODE)arg;
        LOG((LF_CORDB, LL_INFO10000, "ILSM::TraceManager: COM-to-CLR case %p\n", target));\
        trace->InitForManaged(target);
    }
```
So that it makes a bit more sense.

Also, rename IsReverseStub to IsReversePInvokeStub, and make it return true for PInvoke only.

File: src/coreclr/vm/stubmgr.cpp (hunk 20 above)
Comment (jkotas) [reply src/coreclr/vm/stubmgr.cpp]: UNREACHABLE_MSG looks good

File: src/coreclr/vm/dllimportcallback.cpp (hunk 9 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimportcallback.cpp]: We also call this from within `ExecuteInterpretedMethod` now. The forward declarations were merely a symptom it seems.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimportcallback.cpp]: Also called from within `TheUMEntryPrestubWorker`.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimportcallback.cpp]: If I'm declaring it in `dllimportcallback.h`, I'd prefer if it was in the `dllimportcallback.cpp` translation unit.

File: src/coreclr/vm/interpexec.cpp (hunk 18 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp]: I don't fully understand this multi-step process either. @davidwrighton wrote this check originally. I simply didn't care for the complex checks in a predicate so rewrote it.

File: src/coreclr/vm/dllimportcallback.cpp (hunk 9 above)
Comment (jkotas) [reply src/coreclr/vm/dllimportcallback.cpp]: It is the only function left in dllimportcallback.cpp when marshalled delegates are not supported. It suggests that dllimportcallback.cpp is not the best home for it.

ReversePInvokeBadTransition is part of the JIT helper implementation in the first place. A few other places call it directly for various reasons. A few other JIT helper impl details are on a similar plan e.g. `DoJITFailFast`.

> If I'm declaring it in dllimportcallback.h, 

It can be on the same plan as `DoJITFailFast`: declared in jitinterface.h and implemented in jithelpers.cpp

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimportcallback.cpp]: Done.

**Review by jkotas — APPROVED** [review]

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/interpexec.cpp (hunk 18 above)
Comment (jkotas) [reply src/coreclr/vm/interpexec.cpp]: Do you plan to follow up on this?

**Review by radekdoulik — APPROVED** [review]
Thanks a lot for resolving this. It is great that it also disables few more areas.

I will recheck it with the interpreter tests and let you know in https://github.com/dotnet/runtime/issues/120319

File: src/coreclr/vm/interpexec.cpp (hunk 18 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interpexec.cpp]: Fixed with latest commit.

**Review by jkotas — APPROVED** [review]
