### PR TITLE
[wasm] Add support for AOT profiling, and add a `browser-profile` sample

### LINKED ISSUE #44167: [Wasm] Profiling APIs are missing
### Description

To generate an execution profile, those APIs are needed:

* WebAssembly.Runtime:StopProfile
* WebAssembly.Runtime:DumpAotProfileData

These assemblies are part of WebAssembly.Bindings in mono/mono:
https://github.com/mono/mono/blob/4966fc22c4d67dc5432e0fa3bf365c371c01bb1f/sdks/wasm/framework/src/WebAssembly.Bindings/Runtime.cs#L603

### Configuration

c72678bac90f9692ccea2787e22d88a6ae449cda

### Regression?

No

### PR DESCRIPTION
**Pull request by tqiu8**
Fix #44167

- Added profiling APIs for WASM
- Created new browser-profile sample for WASM 
  To get data.aotprofile: 
  `make get-aot-profile`

  To run with profile data:
  `make use-aot-profile`

- Add AotInterp (mixed mode) in order to use profile data. 
- Add Wasm config option to enable profiler.

### CODE REVIEW

File: src/mono/wasm/runtime/library_mono.js [hunk 1]
```diff
@@ -1474,8 +1474,8 @@ var MonoSupportLib = {
 
 			if (args.runtime_options)
 				MONO.mono_wasm_set_runtime_options (args.runtime_options);
-
-			if (args.aot_profiler_options)
+				
+			if (args.aot_profiler_options) {
```
Comment (lewing) [inline src/mono/wasm/runtime/library_mono.js:1478]: This looks like it needs to be removed.

File: src/mono/netcore/sample/wasm/browser/runtime.js [hunk 2]
```diff
@@ -9,7 +9,8 @@ var Module = {
         config.fetch_file_cb = function (asset) {
             return fetch (asset, { credentials: 'same-origin' });
         }
-
+        MONO.mono_wasm_init_aot_profiler();
```
Comment (lewing) [inline src/mono/netcore/sample/wasm/browser/runtime.js:12]: This shouldn't be needed.

File: src/mono/netcore/sample/wasm/browser/runtime.js [hunk 3]
```diff
@@ -9,7 +9,8 @@ var Module = {
...
         MONO.mono_load_runtime_and_bcl_args (config);
     },
-};
+    runProfiler: true,
```
Comment (lewing) [inline src/mono/netcore/sample/wasm/browser/runtime.js:15]: Is this used anywhere? Ah, you're using it to call StopProfile.  Typically you'd call that from managed, in the case of the sample it could just be at the end of main.

File: src/mono/wasm/runtime/library_mono.js [hunk 4]
```diff
@@ -1445,9 +1445,9 @@ var MonoSupportLib = {
 			if (options == null)
 				options = {}
 			if (!('write_at' in options))
-				options.write_at = 'WebAssembly.Runtime::StopProfile';
+				options.write_at = 'Interop/Runtime::StopProfile';
```
Comment (lewing) [inline src/mono/wasm/runtime/library_mono.js:1448]: If you change change this value you shouldn't need to load all the interop stuff.  You can point it at a function in the sample

File: src/mono/wasm/runtime/library_mono.js (hunk 1 above)
Comment (lewing) [inline src/mono/wasm/runtime/library_mono.js:1478]: The trailing brace is wrong.

File: src/mono/netcore/sample/wasm/browser/WasmSample.csproj [hunk 5]
```diff
@@ -38,15 +108,38 @@
...
-      AssemblySearchPaths="@(AssemblySearchPaths)"/>
+      Assemblies="@(BundleAssemblies)"/>
     <Exec Command="chmod a+x $(AppDir)/run-v8.sh" />
-    <Copy SourceFiles="bin\index.html;bin\server.py" DestinationFolder="$(AppDir)" />
+    <Copy SourceFiles="$(PublishDir)\index.html;$(PublishDir)\server.py" DestinationFolder="$(AppDir)" />
   </Target>
 
   <ItemGroup>
     <Compile Include="Program.cs" />
+    <Compile Include="$(LibrariesProjectRoot)Common/src/Interop/Browser/Interop.Runtime.cs" Condition="'$(ProfileAOT)' == 'true'"/>
```
Comment (lewing) [inline src/mono/netcore/sample/wasm/browser/WasmSample.csproj:120]: You won't need to add all this if change the write_at value in the options.

File: src/mono/netcore/sample/wasm/browser/Program.cs [hunk 6]
```diff
@@ -4,6 +4,8 @@
 using System;
 using System.Runtime.CompilerServices;
 
+[assembly: CLSCompliant(false)]
```
Comment (lewing) [inline src/mono/netcore/sample/wasm/browser/Program.cs:7]: Remove this.

File: src/mono/netcore/sample/wasm/browser/index.html [hunk 7]
```diff
@@ -13,11 +13,32 @@ <h3 id="header">Wasm Browser Sample</h3>
     <script type='text/javascript'>
       var App = {
         init: function () {
+          Module.cwrap('mono_wasm_load_profiler_aot', 'void', ['string'])();
```
Comment (lewing) [inline src/mono/netcore/sample/wasm/browser/index.html:16]: This shouldn't be needed.

**Review by lewing — CHANGES_REQUESTED** [review]
Good start but needs some work. We should probably move this to a different sample separate it from the normal case.

File: src/mono/netcore/sample/wasm/browser/runtime.js (hunk 2 above)
Comment (tqiu8) [reply src/mono/netcore/sample/wasm/browser/runtime.js:12]: Ok, I just need to define `config.aot_profiler_options` to have initialize the profiler.

File: src/mono/wasm/runtime/library_mono.js (hunk 4 above)
Comment (tqiu8) [reply src/mono/wasm/runtime/library_mono.js:1448]: To call `DumpAOTProfile` we would still have to load the interop stuff.

Comment (lewing) [reply src/mono/wasm/runtime/library_mono.js:1448]: The code is there already if the System.Private.Runtime.InteropServices.JavaScript assembly is being loaded (and DumpProfile hasn't been linked out)

Comment (lewing) [reply src/mono/wasm/runtime/library_mono.js:1448]: and by change the value I mean set it when generating the options.  The situation is kind of a mess because that assembly isn't public right now but we can deal with it differently until that changes.

File: src/mono/netcore/sample/wasm/browser/runtime.js (hunk 2 above)
Comment (lewing) [reply src/mono/netcore/sample/wasm/browser/runtime.js:12]: Yes, the build task should set it in the config

File: src/mono/wasm/runtime/library_mono.js (hunk 4 above)
Comment (tqiu8) [reply src/mono/wasm/runtime/library_mono.js:1448]: Ah, got it.

File: src/mono/netcore/sample/wasm/browser-profile/Makefile [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+
+all: build
+
+build:
+	$(DOTNET) publish $(DOTNET_Q_ARGS) $(DOTNET_RUN_AOT_COMPILATION_ARGS) $(DOTNET_PROFILE_ARGS) /p:TargetArchitecture=wasm /p:TargetOS=Browser /p:Configuration=$(CONFIG) WasmSample.csproj
+
+clean:
+	rm -rf bin
+
+run:
```
Comment (radical) [inline src/mono/netcore/sample/wasm/browser-profile/Makefile:28]: You can use `dotnet-serve` instead, like https://github.com/dotnet/runtime/blob/master/src/mono/netcore/sample/wasm/browser/Makefile#L20-L26

File: tools-local/tasks/mobile.tasks/AotCompilerTask/MonoAOTCompiler.cs [hunk 9]
```diff
@@ -58,6 +58,10 @@ public class MonoAOTCompiler : Microsoft.Build.Utilities.Task
     /// </summary>
     public bool UseAotDataFile { get; set; } = true;
 
+    public string? AotProfilePath { get; set; }
+
+    public ITaskItem[]? Profilers { get; set; }
```
Comment (radical) [inline tools-local/tasks/mobile.tasks/AotCompilerTask/MonoAOTCompiler.cs:63]: You can change the type to `string[]`. `ITaskItem` is useful if you want to access the metadata on the items, which is not the case here.

File: src/mono/netcore/sample/wasm/browser-profile/Makefile (hunk 8 above)
Comment (mdh1418) [reply src/mono/netcore/sample/wasm/browser-profile/Makefile:28]: In doing so, you can remove `server.py` and all other instances of it.

File: src/mono/netcore/sample/wasm/browser-profile/WasmSample.csproj [hunk 10]
```diff
@@ -0,0 +1,127 @@
...
+             Properties="Configuration=Debug"
+             Targets="Build;Publish"/>
+  </Target>
+
+  <Import Project="$(RepoTasksDir)mobile.tasks\AotCompilerTask\MonoAOTCompiler.props" />
+  <UsingTask TaskName="WasmAppBuilder" 
+             AssemblyFile="$(ArtifactsBinDir)WasmAppBuilder\Debug\$(NetCoreAppCurrent)\publish\WasmAppBuilder.dll"/>
+
+  <UsingTask TaskName="MonoAOTCompiler"
+             AssemblyFile="$(ArtifactsBinDir)MonoAOTCompiler\Debug\$(NetCoreAppCurrent)\MonoAOTCompiler.dll" />
```
Comment (mdh1418) [inline src/mono/netcore/sample/wasm/browser-profile/WasmSample.csproj:52]: I think `$(MonoAOTCompilerTasksAssemblyPath)` can be used here.

File: src/mono/netcore/sample/wasm/browser-profile/runtime.js [hunk 11]
```diff
@@ -0,0 +1,15 @@
...
+var Module = { 
+    onRuntimeInitialized: function () {
+        config.loaded_cb = function () {
+            App.init ();
+        };
+        config.fetch_file_cb = function (asset) {
+            return fetch (asset, { credentials: 'same-origin' });
+        }
+        config.aot_profiler_options = {write_at:"Sample.Test::StopProfile", 
+                                        send_to: "System.Runtime.InteropServices.JavaScript.Runtime::DumpAotProfileData"}
```
Comment (radical) [inline src/mono/netcore/sample/wasm/browser-profile/runtime.js:12]: formatting

File: src/mono/netcore/sample/wasm/browser-profile/WasmSample.csproj [hunk 12]
```diff
@@ -0,0 +1,123 @@
...
+      </AotInputAssemblies>
+    </ItemGroup>
+
+    <ItemGroup Condition="'$(RunAOTCompilation)' == 'true'">
+      <AotProfilers Include="aot" />
+    </ItemGroup>
+
+    <Error Condition="'$(RunAOTCompilation)' == 'true' and '$(EMSDK_PATH)' == ''" Text="The EMSDK_PATH environment variable should be set pointing to the emscripten SDK root dir when using AOT."/>
+    
+    <MonoAOTCompiler
```
Comment (radical) [inline src/mono/netcore/sample/wasm/browser-profile/WasmSample.csproj:56]: The AOT stuff can be updated to shared targets in `WasmApp.targets`, like https://github.com/dotnet/runtime/blob/master/src/mono/netcore/sample/wasm/console/WasmSample.csproj .

**Comment by radical** [comment]
I tried `get-aot-profile`, but I get errors in the browser:
Screen Shot 2021-01-05 at 5 52 11 PM

This is with a clean build of the branch.

**Comment by tqiu8** [comment]
@radical Added a `/p:BuildNative=true` to the `build-aot-profile` target.

**Comment by radical** [comment]
I would suggest moving the shared bits to a separate file - https://github.com/radical/runtime/commit/01946286c8553192c19184fc45e7fbe485b42fc8 .

File: src/mono/netcore/sample/wasm/browser-profile/Makefile [hunk 13]
```diff
@@ -0,0 +1,33 @@
...
+DOTNET_MONO_LOG_LEVEL=--setenv=MONO_LOG_LEVEL=debug
+endif
+
+CONFIG?=Release
+
+build-aot-profile:
+	EMSDK_PATH=$(realpath $(TOP)/src/mono/wasm/emsdk) $(DOTNET) publish $(DOTNET_Q_ARGS) /p:EnableProfiler=true /p:WasmBuildNative=true /p:Configuration=$(CONFIG) /p:TargetArchitecture=wasm /p:TargetOS=Browser $(MSBUILD_ARGS) WasmSample.csproj
+
+run-aot-profiled:
+	cp $(HOME)/Downloads/data.aotprofile ./bin/$(CONFIG)/AppBundle
```
Comment (radical) [inline src/mono/netcore/sample/wasm/browser-profile/Makefile:17]: Instead of hardcoding the path, use a var here, and error out if that isn't given.

**Comment by tqiu8** [comment]
> I would suggest moving the shared bits to a separate file - [radical@0194628](https://github.com/radical/runtime/commit/01946286c8553192c19184fc45e7fbe485b42fc8) .

Could we open a separate PR for that after this one?

**Comment by radical** [comment]
> > I would suggest moving the shared bits to a separate file - [radical@0194628](https://github.com/radical/runtime/commit/01946286c8553192c19184fc45e7fbe485b42fc8) .
> 
> Could we open a separate PR for that after this one?

why not just include it in this one?

**Comment by radical** [comment]
> > > I would suggest moving the shared bits to a separate file - [radical@0194628](https://github.com/radical/runtime/commit/01946286c8553192c19184fc45e7fbe485b42fc8) .
> > 
> > 
> > Could we open a separate PR for that after this one?
> 
> why not just include it in this one?

Separate PR will be fine too.

File: src/mono/netcore/sample/wasm/browser-profile/Makefile [hunk 14]
```diff
@@ -0,0 +1,36 @@
...
+DOTNET_MONO_LOG_LEVEL=--setenv=MONO_LOG_LEVEL=debug
+endif
+
+CONFIG?=Release
+
+build-aot-profile:
+	EMSDK_PATH=$(realpath $(TOP)/src/mono/wasm/emsdk) $(DOTNET) publish $(DOTNET_Q_ARGS) /p:EnableProfiler=true /p:WasmBuildNative=true /p:Configuration=$(CONFIG) /p:TargetArchitecture=wasm /p:TargetOS=Browser $(MSBUILD_ARGS) WasmSample.csproj
+
+run-aot-profiled:	
+ifeq ($(DOWNLOAD_DIR),)
```
Comment (radical) [inline src/mono/netcore/sample/wasm/browser-profile/Makefile:9]: Get the path to the profile data as input.

File: src/mono/netcore/sample/wasm/browser-profile/Makefile [hunk 15]
```diff
@@ -0,0 +1,36 @@
...
+	$(error DOWNLOAD_DIR is not set)
+endif
+	cp $(DOWNLOAD_DIR)/data.aotprofile bin/$(CONFIG)/AppBundle
```
Comment (radical) [inline src/mono/netcore/sample/wasm/browser-profile/Makefile:12]: Is this required? Or can we pass the original path to `/p:AOTProfilePath`?

File: src/libraries/System.Private.Runtime.InteropServices.JavaScript/src/System/Runtime/InteropServices/JavaScript/Runtime.cs [hunk 16]
```diff
@@ -70,6 +70,11 @@ public static object GetGlobalObject(string? str = null)
             return Interop.Runtime.GetGlobalObject(str);
         }
 
+        public static void DumpAotProfileData (ref byte buf, int len, string s)
```
Comment (radical) [inline src/libraries/System.Private.Runtime.InteropServices.JavaScript/src/System/Runtime/InteropServices/JavaScript/Runtime.cs:73]: rename `s` to `extraArg`. That is what the profiler passes as the arg here. And same for the other `DumpAotProfileData` method.

File: src/mono/wasm/build/WasmApp.targets [hunk 17]
```diff
@@ -39,13 +39,19 @@
...
 
     <MonoAOTCompiler
       CompilerBinaryPath="$(MicrosoftNetCoreAppRuntimePackRidDir)native\cross\mono-aot-cross"
-      Mode="LLVMOnly"
+      Mode="$(AOTMode)"
       OutputType="AsmOnly"
       Assemblies="@(AotInputAssemblies)"
       UseAotDataFile="false"
+      AotProfilePath="$(AOTProfilePath)"
+      Profilers="aot;"
```
Comment (radical) [inline src/mono/wasm/build/WasmApp.targets:54]: Add a `@(AOTProfilers)` here, and you can add `aot` by default for that.

File: src/tasks/WasmAppBuilder/WasmAppBuilder.cs [hunk 18]
```diff
@@ -217,6 +221,11 @@ public override bool Execute ()
                 if (source != null && source.ItemSpec != null)
                     config.RemoteSources.Add(source.ItemSpec);
         }
+        Console.WriteLine($"PROFILE {Profile}");
```
Comment (radical) [inline src/tasks/WasmAppBuilder/WasmAppBuilder.cs:224]: this line can be dropped

File: src/tasks/WasmAppBuilder/WasmAppBuilder.cs [hunk 19]
```diff
@@ -25,6 +25,8 @@ public class WasmAppBuilder : Task
     [Required]
     public string[]? Assemblies { get; set; }
 
+    public bool Profile { get; set; }
```
Comment (radical) [inline src/tasks/WasmAppBuilder/WasmAppBuilder.cs:28]: Maybe `EnableProfiler` would be a better name?

File: src/tasks/AotCompilerTask/MonoAOTCompiler.cs [hunk 20]
```diff
@@ -58,6 +58,16 @@ public class MonoAOTCompiler : Microsoft.Build.Utilities.Task
     /// </summary>
     public bool UseAotDataFile { get; set; } = true;
 
+    /// <summary>
+    /// Path to AOT profile file.
```
Comment (radical) [inline src/tasks/AotCompilerTask/MonoAOTCompiler.cs:62]: `File to use for profile-guided optimization`

File: src/libraries/Common/src/Interop/Browser/Interop.Runtime.cs [hunk 21]
```diff
@@ -99,5 +100,26 @@ public static object GetGlobalObject(string? str = null)
...
+            if (len == 0)
+                throw new JSException("Profile data length is 0");
+
+            var arr = new byte[len];
+            fixed (void *p = &buf)
+            {
+                var span = new ReadOnlySpan<byte>(p, len);
+                // Send it to JS
+                var module = (JSObject)Runtime.GetGlobalObject("Module");
+                module.SetObjectProperty("aot_profile_data", Uint8Array.From (span));
```
Comment (radical) [inline src/libraries/Common/src/Interop/Browser/Interop.Runtime.cs:121]: remove space before open paren

**Review by radical — CHANGES_REQUESTED** [review]
Some more feedback! Thanks for addressing the earlier ones

File: src/mono/netcore/sample/wasm/browser-profile/Makefile (hunk 15 above)
Comment (tqiu8) [reply src/mono/netcore/sample/wasm/browser-profile/Makefile:12]: Yes, we can do that. Just doing that to keep everything in one place.

File: src/mono/wasm/build/WasmApp.targets [hunk 22]
```diff
@@ -39,13 +39,19 @@
 
       <_WasmAssemblies Remove="@(_WasmAssemblies)" />
     </ItemGroup>
+    <PropertyGroup>
+      <AOTMode>LLVMOnly</AOTMode>
+      <AOTMode Condition="'$(BuildAOTProfiled)' == 'true'">AotInterp</AOTMode>
```
Comment (radical) [inline src/mono/wasm/build/WasmApp.targets:44]: We should check to see if the property is already set. This would allow it to be overridden.

```suggestion
      <AOTMode Condition="'$(AOTMode)' == '' and '$(BuildAOTProfiled)' == 'true'">AotInterp</AOTMode>
      <AOTMode Condition="'$(AOTMode)' == ''">LLVMOnly</AOTMode>
```

File: src/mono/wasm/build/WasmApp.targets [hunk 23]
```diff
@@ -39,13 +39,19 @@
...
+    </PropertyGroup>
 
     <MonoAOTCompiler
       CompilerBinaryPath="$(MicrosoftNetCoreAppRuntimePackRidDir)native\cross\mono-aot-cross"
-      Mode="LLVMOnly"
+      Mode="$(AOTMode)"
       OutputType="AsmOnly"
       Assemblies="@(AotInputAssemblies)"
       UseAotDataFile="false"
+      AotProfilePath="$(AOTProfilePath)"
```
Comment (radical) [inline src/mono/wasm/build/WasmApp.targets:53]: Is it valid to have `AOTMode==AotInterp`(due to `BuildAOTProfiled==true`), and empty `AOTProfilePath`? If not, then we should check for that in the task.

File: src/tasks/WasmAppBuilder/WasmAppBuilder.cs [hunk 24]
```diff
@@ -25,6 +25,8 @@ public class WasmAppBuilder : Task
     [Required]
     public string[]? Assemblies { get; set; }
 
+    public bool EnableProfile { get; set; }
```
Comment (radical) [inline src/tasks/WasmAppBuilder/WasmAppBuilder.cs:28]:
```suggestion
    public bool EnableProfiler { get; set; }
```

File: src/mono/netcore/sample/wasm/browser-profile/Wasm.BrowserProfile.Sample.csproj [hunk 25]
```diff
@@ -0,0 +1,81 @@
...
+    <Message Text="Packaged ID: %(RuntimePack.PackageDirectory)" Importance="high" />
+  </Target>
+  
+  <Target Name="PrepareForWasmBuild" BeforeTargets="WasmBuildApp">
+    <PropertyGroup>
+        <WasmAppDir>$(AppDir)</WasmAppDir>
+        <WasmBuildDir>$(MSBuildProjectDirectory)\$(PublishDir)\</WasmBuildDir>
+        <WasmMainAssemblyPath>$(WasmBuildDir)$(AssemblyName).dll</WasmMainAssemblyPath>
+        <WasmMainJSPath>runtime.js</WasmMainJSPath>
+        <WasmMainAssemblyPath>$(WasmBuildDir)$(AssemblyName).dll</WasmMainAssemblyPath>
```
Comment (radical) [inline src/mono/netcore/sample/wasm/browser-profile/Wasm.BrowserProfile.Sample.csproj:45]: can be removed, as it is already set above

File: src/tasks/AotCompilerTask/MonoAOTCompiler.cs [hunk 26]
```diff
@@ -132,13 +142,19 @@ public override bool Execute()
...
         switch (Mode)
         {
             case "Normal": parsedAotMode = MonoAotMode.Normal; break;
             case "Full": parsedAotMode = MonoAotMode.Full; break;
             case "LLVMOnly": parsedAotMode = MonoAotMode.LLVMOnly; break;
+            case "AotInterp": parsedAotMode = MonoAotMode.AotInterp; break;
             default:
-                throw new ArgumentException($"'{nameof(Mode)}' must be one of: '{nameof(MonoAotMode.Normal)}', '{nameof(MonoAotMode.Full)}', '{nameof(MonoAotMode.LLVMOnly)}'. Received: '{Mode}'.", nameof(Mode));
+                throw new ArgumentException($"'{nameof(Mode)}' must be one of: '{nameof(MonoAotMode.Normal)}', '{nameof(MonoAotMode.Full)}', '{nameof(MonoAotMode.LLVMOnly)}', '{nameof(MonoAotMode.AotInterp)}'. Received: '{Mode}'.", nameof(Mode));
         }
```
Comment (radical) [inline src/tasks/AotCompilerTask/MonoAOTCompiler.cs:158]:
```csharp
        if (!Enum.TryParse(Mode, true, out parsedAotMode))
        {
            Log.LogError($"Unknown Mode value: {Mode}. '{nameof(Mode)}' must be one of: {string.Join(',', Enum.GetNames(typeof(MonoAotMode)))}");
            return false;
        }
```

File: src/mono/netcore/sample/wasm/browser-profile/Wasm.BrowserProfile.Sample.csproj (hunk 25 above)
Comment (tqiu8) [reply src/mono/netcore/sample/wasm/browser-profile/Wasm.BrowserProfile.Sample.csproj:45]: I'm going to remove the definition above. Since `WasmBuildDir` is still needed in defining `WasmMainAssemblyPath` etc which are required

File: src/mono/wasm/build/WasmApp.targets (hunk 23 above)
Comment (tqiu8) [reply src/mono/wasm/build/WasmApp.targets:53]: Is it not possible to build in mixed mode without  a profile?

Comment (radical) [reply src/mono/wasm/build/WasmApp.targets:53]: @vargaz can answer that question

**Comment by SamMonoRT** [comment]
@vargaz - please review.

**Review by radical — APPROVED** [review]
Looks good in general. I don't know much about the actual args being passed for aot, but other than that, LGTM! 👍

**Comment by mdh1418** [comment]
@tqiu8 If possible in this PR, it might be good to simplify the browser profile sample if @radical 's PR  https://github.com/dotnet/runtime/pull/46772 makes it in before this.

**Review by vargaz — APPROVED** [review]

**Review by lewing — APPROVED** [review]

**Comment by vargaz** [comment]
The failure is because:
/bin/sh: 2: /tmp/tmpd4b55cd2d88f44fcb76e949b81b21acf.exec.cmd: source: not found
/__w/1/s/src/mono/wasm/build/WasmApp.targets(135,5): error MSB3073: The command "source /usr/local/emscripten/emsdk_env.sh && emcc --version | head -1 > emcc-version.txt" exited with code 127. [/__w/1/s/src/tests/FunctionalTests/wasm/AOT/browser/Wasm.Aot.Browser.Test.csproj]

**Comment by radical** [comment]
Some makefile updates that can be added here, or in a separate PR: https://gist.github.com/radical/5fdb866f4c14795f67457d4e7634c1b1
