### PR TITLE
Revert "Revert "Dynamic generic dictionary expansion feature (#32270)

### LINKED ISSUE #32828: Assert failure HasPerInstInfo() methodtable.h Line: 2908
https://dnceng.visualstudio.com/public/_build/results?buildId=535480&view=ms.vss-test-web.build-test-results-tab&runId=16999826&paneView=debug

Configuration: `netcoreapp5.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open`

Dump:   https://helix.dot.net/api/2019-06-17/jobs/1d28c181-b612-4d7b-b57c-ad158d0a1b9e/workitems/System.Composition.Hosting.Tests/files/core.51410

```
  Discovering: System.Composition.Hosting.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Composition.Hosting.Tests (found 66 test cases)
  Starting:    System.Composition.Hosting.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 51410 [0x0000c8d2], Thread: 3649813 [0x37b115]): HasPerInstInfo()
    File: /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/vm/methodtable.h Line: 2908
    Image: /private/tmp/helix/working/AA450997/p/dotnet


Assert failure(PID 51410 [0x0000c8d2], Thread: 3649814 [0x37b116]): HasPerInstInfo()
    File: /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/vm/methodtable.h Line: 2908
    Image: /private/tmp/helix/working/AA450997/p/dotnet

./RunTests.sh: line 161: 51410 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Composition.Hosting.Tests.runtimeconfig.json --depsfile System.Composition.Hosting.Tests.deps.json xunit.console.dll System.Composition.Hosting.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonnetcoreapptests -notrait category=nonosxtests $RSP_FILE
/private/tmp/helix/working/AA450997/w/A59A091E/e
----- end Tue Feb 25 00:51:44 PST 2020 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

cc @jkotas

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #32828

### CODE REVIEW

File: src/coreclr/src/vm/genericdict.cpp [hunk 1]
```diff
@@ -809,10 +780,10 @@ Dictionary* Dictionary::GetMethodDictionaryWithSizeCheck(MethodDesc* pMD, ULONG
     }
     CONTRACT_END;
 
-    Dictionary* pDictionary = pMD->GetMethodDictionary();
```
Comment (jkotas) [inline src/coreclr/src/vm/genericdict.cpp]: This is where the race condition was. We have fetched the Dictionary, then some other thread expanded the dictionary, and then we fetched the number of slot from the new Dictionary; but still kept using the old Dictionary.

**Comment by jkotas** [comment]
@fadimounir I have spent done detailed review of the code, and I believe that I have found the race condition. See the comment above. I have also tightened up the implementation in a few places as I was doing it.

File: src/coreclr/src/vm/genericdict.cpp (hunk 1 above)
Comment (fadimounir) [reply src/coreclr/src/vm/genericdict.cpp]: Thanks Jan for tracking this down!

**Review by fadimounir — APPROVED** [review]
