### PR TITLE
[wasm][debugger]Adding stack info to the exception details when evaluating expressions

### LINKED ISSUE #81333: [wasm] [debugger] Compilation error in debugger on `Debugger.evaluateOnCallFrame` command contains `stacktrace` in format that is not compatible with CDP
### Description

In CDP, `stacktrace` field inside `exceptionDetails` object is an `object`, according to the specification:
```json
{
  "id": "StackTrace",
  "description": "Call frames for assertions or error messages.",
  "type": "object",
  "properties": [
    {
      "name": "description",
      "description": "String label of this stack trace. For async traces this may be a name of the function that\ninitiated the async call.",
      "optional": true,
      "type": "string"
    },
    {
      "name": "callFrames",
      "description": "JavaScript function name.",
      "type": "array",
      "items": {
        "$ref": "CallFrame"
      }
    },
    {
      "name": "parent",
      "description": "Asynchronous JavaScript stack trace that preceded this stack, if available.",
      "optional": true,
      "$ref": "StackTrace"
    },
    {
      "name": "parentId",
      "description": "Asynchronous JavaScript stack trace that preceded this stack, if available.",
      "experimental": true,
      "optional": true,
      "$ref": "StackTraceId"
    }
  ]
}
```

In case of compilation error, `Debugger.evaluateOnCallFrame` returns `exceptionDetails.stackTrace` as a string instead of `object` with `callFrames`.

It is possible to compute `callFrames` array because we have `callFrameId` in the request.

### Reproduction Steps

Send a request to evaluate `undefined` on the call frame. `undefined` is not available in such context, such a command should produce compilation error:

```json
{
  "id": 31,
  "method": "Debugger.evaluateOnCallFrame",
  "params": {
    "callFrameId": "dotnet:scope:1",
    "expression": "undefined",
    "objectGroup": "suspendContext",
    "generatePreview": true
  }
} 
```

### Expected behavior

I see 2 potential ways how to achieve correct behavior without breaking the protocol:

1. Parse .NET stack trace and provide valid call frames, while the initial .NET stack trace goes to the description (as JS debugger does):
```json
{
  "id": 31,
  "sessionId": null,
  "result": {
    "result": {
      "type": "object",
      "subtype": "error",
      "description": "The name undefined does not exist in the current context   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.ResolveIdentifier(IdentifierNameSyntax identifier, MemberReferenceResolver resolver, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.Resolve[T](IList`1 collectionToResolve, MemberReferenceResolver resolver, Func`4 resolutionFunc, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.CompileAndRunTheExpression(String expression, MemberReferenceResolver resolver, ILogger logger, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.MonoProxy.OnEvaluateOnCallFrame(MessageId msg_id, Int32 scopeId, String expression, CancellationToken token)",
      "className": "ReferenceError"
    },
    "exceptionDetails": {
      "exception": {
        "type": "object",
        "subtype": "error",
        "description": "The name undefined does not exist in the current context   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.ResolveIdentifier(IdentifierNameSyntax identifier, MemberReferenceResolver resolver, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.Resolve[T](IList`1 collectionToResolve, MemberReferenceResolver resolver, Func`4 resolutionFunc, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.CompileAndRunTheExpression(String expression, MemberReferenceResolver resolver, ILogger logger, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.MonoProxy.OnEvaluateOnCallFrame(MessageId msg_id, Int32 scopeId, String expression, CancellationToken token)",
        "className": "ReferenceError"
      },
      "stackTrace": {
        "callFrames": [
          {
            "functionName": "Increment",
            "scriptId": "dotnet://179_4",
            "url": "file:///Users/seclerp/Playground/SimpleBlazorAppNet7/SimpleBlazorAppNet7/Pages/Counter.razor",
            "lineNumber": 14,
            "columnNumber": 8
          }
        ]
      }
    }
  }
}
```

2. The same as the first one but instead of concatenating with the description extend the protocol with a new field called something like monoStacktrace:

```json
    // ...
    "exceptionDetails": {
      // ...
      "stackTrace": {
        "callFrames": [
          {
            "functionName": "Increment",
            "scriptId": "dotnet://179_4",
            "url": "file:///Users/seclerp/Playground/SimpleBlazorAppNet7/SimpleBlazorAppNet7/Pages/Counter.razor",
            "lineNumber": 14,
            "columnNumber": 8
          }
        ],
        "monoStacktrace": "   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.ResolveIdentifier(IdentifierNameSyntax identifier, MemberReferenceResolver resolver, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.Resolve[T](IList`1 collectionToResolve, MemberReferenceResolver resolver, Func`4 resolutionFunc, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.CompileAndRunTheExpression(String expression, MemberReferenceResolver resolver, ILogger logger, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.MonoProxy.OnEvaluateOnCallFrame(MessageId msg_id, Int32 scopeId, String expression, CancellationToken token)"
      }
    }
    // ...
```

### Actual behavior

```json
{
  "id": 31,
  "sessionId": null,
  "result": {
    "result": {
      "type": "object",
      "subtype": "error",
      "description": "The name undefined does not exist in the current context",
      "className": "ReferenceError"
    },
    "exceptionDetails": {
      "exception": {
        "type": "object",
        "subtype": "error",
        "description": "The name undefined does not exist in the current context",
        "className": "ReferenceError"
      },
      // Should be an object with `callFrames` property
      "stackTrace": "   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.ResolveIdentifier(IdentifierNameSyntax identifier, MemberReferenceResolver resolver, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.Resolve[T](IList`1 collectionToResolve, MemberReferenceResolver resolver, Func`4 resolutionFunc, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.CompileAndRunTheExpression(String expression, MemberReferenceResolver resolver, ILogger logger, CancellationToken token)\n   at Microsoft.WebAssembly.Diagnostics.MonoProxy.OnEvaluateOnCallFrame(MessageId msg_id, Int32 scopeId, String expression, CancellationToken token)"
    }
  }
}
```

### Regression?

_No response_

### Known Workarounds

Intercept the value of `Runtime.ExceptionDetails` and remove the breaking `stacktrace` property, adding its value to the `description` to adopt JS tooling interface.

### Configuration

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.1
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.404 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]
```

### Other information

VS Code reproduces the issue when trying to evaluate something that doesn't compiles:

image

### PR DESCRIPTION
**Pull request by thaystg**
Fixes #81333 
We weren't using that string callstack for nothing, I think we can remove and add the expected one.

Return Without the PR:
```
[Result: IsOk: False, IsErr: True, Value: , Error: {
  "result": {
    "type": "object",
    "subtype": "error",
    "description": "Failed to resolve member access for DebuggerTests.EvaluateStaticFieldsInStaticClass.StaticProperty2",
    "className": "ReferenceError"
  },
  "exceptionDetails": {
    "exception": {
      "type": "object",
      "subtype": "error",
      "description": "Failed to resolve member access for DebuggerTests.EvaluateStaticFieldsInStaticClass.StaticProperty2",
      "className": "ReferenceError"
    },
    "stackTrace": "   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.ResolveMemberAccessExpression(MemberAccessExpressionSyntax memberAccess, MemberReferenceResolver resolver, CancellationToken token) in T:\\thays\\runtime_wasm_5\\runtime\\src\\mono\\wasm\\debugger\\BrowserDebugProxy\\EvaluateExpression.cs:line 316\r\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.Resolve[T](IList`1 collectionToResolve, MemberReferenceResolver resolver, Func`4 resolutionFunc, CancellationToken token) in T:\\thays\\runtime_wasm_5\\runtime\\src\\mono\\wasm\\debugger\\BrowserDebugProxy\\EvaluateExpression.cs:line 307\r\n   at Microsoft.WebAssembly.Diagnostics.ExpressionEvaluator.CompileAndRunTheExpression(String expression, MemberReferenceResolver resolver, ILogger logger, CancellationToken token) in T:\\thays\\runtime_wasm_5\\runtime\\src\\mono\\wasm\\debugger\\BrowserDebugProxy\\EvaluateExpression.cs:line 416\r\n   at Microsoft.WebAssembly.Diagnostics.MonoProxy.OnEvaluateOnCallFrame(MessageId msg_id, Int32 scopeId, String expression, CancellationToken token) in T:\\thays\\runtime_wasm_5\\runtime\\src\\mono\\wasm\\debugger\\BrowserDebugProxy\\MonoProxy.cs:line 1379"
  }
} ]
```

Return With the PR:
```
: [Result: IsOk: False, IsErr: True, Value: , Error: {
  "result": {
    "type": "object",
    "subtype": "error",
    "description": "Failed to resolve member access for DebuggerTests.EvaluateStaticFieldsInStaticClass.StaticProperty2",
    "className": "ReferenceError"
  },
  "exceptionDetails": {
    "exception": {
      "type": "object",
      "subtype": "error",
      "description": "Failed to resolve member access for DebuggerTests.EvaluateStaticFieldsInStaticClass.StaticProperty2",
      "className": "ReferenceError"
    },
    "stackTrace": {
      "callFrames": [
        {
          "functionName": "DebuggerTests.EvaluateMethodTestsClass.TestEvaluate.run",
          "scriptId": "dotnet://8_0",
          "url": "file:///T:/thays/runtime_wasm_5/runtime/src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs",
          "lineNumber": 358,
          "columnNumber": 16
        },
        {
          "functionName": "DebuggerTests.EvaluateMethodTestsClass.EvaluateMethods",
          "scriptId": "dotnet://8_0",
          "url": "file:///T:/thays/runtime_wasm_5/runtime/src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs",
          "lineNumber": 422,
          "columnNumber": 12
        }
      ]
    }
  }
} ]
```

### CODE REVIEW

**Review by seclerp — COMMENTED** [review]
I think the structure is still incorrect - according to https://vanilla.aslushnikov.com/?Runtime.StackTrace `StackTrace` should be an object and have `callFrames` inside it.

The structure you suggest will break existing CDP code that relies on `stackTrace`.

**Comment by thaystg** [comment]
> `callFrames`

Thanks a lot :)
Fixed it.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 1]
```diff
@@ -270,7 +270,7 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
                     }
                     catch (Exception ex)
                     {
-                        throw new ExpressionEvaluationFailedException($"BUG: Unable to get properties for scope: {scopeId}. {ex}");
+                        throw new ReturnAsErrorException($"BUG: Unable to get properties for scope: {scopeId}. {ex}", ex.GetType().Name);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:273]: Will these now get surfaced in the IDE? How does it show up?

Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:273]: This is completely ignored on VS and on chrome, as far as I know we only see the description which was not changed.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 2]
```diff
@@ -270,7 +270,7 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
                     }
                     catch (Exception ex)
                     {
-                        throw new ExpressionEvaluationFailedException($"BUG: Unable to get properties for scope: {scopeId}. {ex}");
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:273]: I think we could keep the exception, and decide how to react to this exception type somewhere up the call stack. Having a specific type gives us more information to better react to it.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests2.cs [hunk 3]
```diff
@@ -197,10 +197,18 @@ public static IEnumerable<object[]> InstanceMethodForTypeMembersTestData(string
             wait_for_event_fn: async (pause_location) =>
             {
                 var id = pause_location["callFrames"][0]["callFrameId"].Value<string>();
+                var id_prev = pause_location["callFrames"][1]["callFrameId"].Value<string>();
 
                 var (_, res) = await EvaluateOnCallFrame(id, "DebuggerTests.EvaluateStaticFieldsInStaticClass.StaticProperty2", expect_ok: false);
                 AssertEqual("Failed to resolve member access for DebuggerTests.EvaluateStaticFieldsInStaticClass.StaticProperty2", res.Error["result"]?["description"]?.Value<string>(), "wrong error message");
-
+                Assert.Equal("DebuggerTests.EvaluateMethodTestsClass.TestEvaluate.run", res.Error["exceptionDetails"]?["stackTrace"]?["callFrames"]?[0]?["functionName"]?.Value<string>());
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests2.cs:204]: Extract `res.Error["exceptionDetails"]?["stackTrace"]?["callFrames"]?[0]` to a local. it would help the readability also.

**Review by ilonatommy — APPROVED** [review]

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 2 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:273]: I think I don't see any reason for it. I removed because I would need to duplicate code or to inherit one from the other maybe, but I think there isn't any extra information on having it.

**Review by radical — APPROVED** [review]
Looks good, except for the one comment. 👍

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 4]
```diff
@@ -1409,12 +1409,31 @@ private async Task OnSetEntrypointBreakpoint(SessionId sessionId, JObject args,
...
+                retStackTrace.Add(JObject.FromObject(new
+                {
+                    functionName = call.Method.Name,
+                    scriptId = call.Location.Id.ToString(),
+                    url = context.Store.ToUrl(call.Location),
+                    lineNumber = call.Location.Line,
+                    columnNumber = call.Location.Column
+                }));
+            }
+            _error.Value["exceptionDetails"]["stackTrace"] = JObject.FromObject(new {callFrames = retStackTrace});
```
[the remark this answers is not in the document]
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1428]: Also, if this throws then the proxy crashes. We are not catching any exceptions above this! Something to fix in a future PR.

[the remark this answers is not in the document]
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs]: fixed :)
