### PR TITLE
Tolerate pathological growth of optCSEHash

### LINKED ISSUE #32733: Test failure in JIT/jit64/opt/cse/HugeArray1/HugeArray1.sh
failed in job: [runtime-coreclr crossgen2 outerloop 20200222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=533489&view=ms.vss-test-web.build-test-results-tab&runId=16936328&paneView=debug&resultId=110111)

Error message
`
\ncmdLine:/home/helixbot/work/B79909FA/w/BBBE0A3C/e/JIT/jit64/opt/cse/HugeArray1/HugeArray1.sh Timed Out\n\nReturn code: -100\nRaw output file: /home/helixbot/work/B79909FA/w/BBBE0A3C/e/JIT/jit64/Reports/JIT.jit64/opt/cse/HugeArray1/HugeArray1.output.txt\nRaw output:\nBEGIN EXECUTION\nin takeLock\nWarning: No files matching /home/helixbot/work/B79909FA/w/BBBE0A3C/e/JIT/jit64/opt/cse/HugeArray1/*.dll\n\ncmdLine:/home/helixbot/work/B79909FA/w/BBBE0A3C/e/JIT/jit64/opt/cse/HugeArray1/HugeArray1.sh Timed Out\nTest Harness Exitcode is : -100\nTo run the test:\n> set CORE_ROOT=/home/helixbot/work/B79909FA/p\n> /home/helixbot/work/B79909FA/w/BBBE0A3C/e/JIT/jit64/opt/cse/HugeArray1/HugeArray1.sh\nExpected: True\nActual: False
`

### PR DESCRIPTION
**Pull request by davidwrighton**
The `optCSEhash` can grow an unbounded amount if the function has numerous trees which are put into the `optCSEhash` as possible CSE candidates, but fewer than `MAX_CSE_CNT` are found, then the compiler will spend excessive amounts of time looking up entries in the `optCSEhash`.

This fix addresses the issue by making the `optCSEhash` able to grow its count of buckets.

This fixes #32733, but I'm not certain its the right approach. Potentially avoiding the pathological growth of the hash table would be a better approach.

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/jit-contrib

File: src/coreclr/src/jit/compiler.h [hunk 1]
```diff
@@ -6364,6 +6364,11 @@ class Compiler
     };
 
     static const size_t s_optCSEhashSize;
+    static const size_t s_optCSEhashGrowthFactor;
```
Comment (briansull) [inline src/coreclr/src/jit/compiler.h:6367]: This could be renamed to indicate that it is the initial hash table size

s_optCSEhashSize  => s_optCSEhashSizeInitial

File: src/coreclr/src/jit/compiler.h [hunk 2]
```diff
@@ -6364,6 +6364,11 @@ class Compiler
...
+    static const size_t s_optCSEhashBucketSize;
+    size_t              optCSEhashSize;                 // Size of hashtable
```
Comment (briansull) [inline src/coreclr/src/jit/compiler.h:6369]: // The current size of the hashtable

**Review by briansull — APPROVED** [review]
Looks Good, 
Thanks
