### PR TITLE
[browser] runtimeConfig via boot config 

### LINKED ISSUE #97449: [browser] Support AppContext switches on runtime
AppContext switches defined in csproj are not available on runtime

```xml
<ItemGroup>
    ...
    <RuntimeHostConfigurationOption Include="System.Runtime.OptionalFeatureBehavior"
                                    Condition="'$(UnoptimizedUserFacingBehavior)' != ''"
                                    Value="$(UnoptimizedUserFacingBehavior)"
                                    Link="false" />
    ...
</ItemGroup>
```

On other platforms, they end up in `runtime.config.json`. We should put them into `blazor.boot.json` as that's the only config required (for both wasmbrowser and blazor experience)

### LINKED ISSUE #112442: Make modern http streaming apis easily consumable in WebAssembly
The discussion in the pull request [#111680](https://github.com/dotnet/runtime/pull/111680) revolves around enabling response streaming for WebAssembly, which introduces a breaking change by disallowing synchronous reads and throwing NotSupportedExceptions instead. The main points discussed include:

All supported browsers support response streaming.
To disable response streaming and allow synchronous reads, a new runtime feature flag WebAssemblyEnableStreamingResponse can be set to false.
Here are the options for handling this change:

* Take the breaking change: Accept the breaking change and update the documentation to reflect that synchronous reads are no longer supported.
* Add a runtime feature flag: Implement the WebAssemblyEnableStreamingResponse feature flag, allowing users to opt-out of response streaming if necessary.
* Set the feature flag directly on requests that require it: Modify the code to set the WebAssemblyEnableStreamingResponse feature flag directly on specific requests that need synchronous reads.

You can view the full discussion and details of the pull request [here](https://github.com/dotnet/runtime/pull/111680).

### PR DESCRIPTION
**Pull request by pavelsavara**
- extend `BootJsonData` with `runtimeConfig` which matches just the `runtimeOptions.configProperties` part of `*.runtimeconfig.json`
- load `RuntimeConfigJsonPath` in `GenerateWasmBootJson` and in `WasmAppBuilder`
- drop RuntimeConfigParserTask from browser and move it to WASI msbuild
- convert from json to `char**` in `startup.ts`
- library mode `initialize_runtime()` out of scope

```js
export const config = /*json-start*/{
  "mainAssemblyName": "Wasm.Browser.Sample.dll",
  "debugLevel": -1,
  "globalizationMode": "sharded",
  ...
  "runtimeConfig": {
    "runtimeOptions": {
      "configProperties": {
        "System.Net.Http.WasmEnableStreamingResponse": true,
        "Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability": true,
        ...
      }
    }
  }
}/*json-end*/;
```

Fixes https://github.com/dotnet/runtime/issues/97449
Fixes https://github.com/dotnet/runtime/issues/112442
Together with https://github.com/dotnet/sdk/pull/48916

### CODE REVIEW

**Comment by lewing** [comment]
test failures look relevant

File: src/mono/browser/runtime/startup.ts [hunk 1]
```diff
@@ -617,7 +617,41 @@ export function mono_wasm_load_runtime (): void {
...
+                runtimeConfigProperties.set(key, "" + value);
+            }
+        }
+        runtimeConfigProperties.set("APP_CONTEXT_BASE_DIRECTORY", "/");
+        runtimeConfigProperties.set("RUNTIME_IDENTIFIER", "browser-wasm");
+        const propertyCount = runtimeConfigProperties.size;
+
+        const buffers:VoidPtr[] = [];
+        const appctx_keys = malloc(4 * runtimeConfigProperties.size) as any as CharPtrPtr;
+        const appctx_values = malloc(4 * runtimeConfigProperties.size) as any as CharPtrPtr;
```
Comment (javiercn) [inline src/mono/browser/runtime/startup.ts:633]: It's the `4` here because of 32 bit addressing?

**Review by javiercn — APPROVED** [review]

File: src/mono/browser/runtime/startup.ts (hunk 1 above)
Comment (pavelsavara) [reply src/mono/browser/runtime/startup.ts:633]: yes
