### PR TITLE
Fix IL interpreter to run on Hello World

### LINKED ISSUE #13759: [Linux] mixed Interpreter and JIT compiler
Hi,

OpenJDK is able to just enable interpreter:

```
java -Xint
```

or just enable JIT compilers:

```
java -Xcomp
```

or mixed:

```
java -Xmixed
```

And what about CoreCLR?

1. enable Interpreter build  https://github.com/dotnet/coreclr/pull/11252

```
./build.sh debug cmakeargs "-DFEATURE_INTERPRETER=1" skipcrossgen ignorewarnings
```
2. HelloWorld testcase for mixing Interpreter and JIT compiler

* X86

```
export CORE_LIBRARIES=~/dotnet-sdk-3.0.100-linux-x64/shared/Microsoft.NETCore.App/3.0.0

# interpreter
export COMPlus_DumpInterpreterStubs=1
export COMPlus_Interpret=*
export COMPlus_InterpreterJITThreshold=999999
export COMPlus_InterpreterPrintPostMortem=1
export COMPlus_InterpreterDoLoopMethods=1
export COMPlus_TraceInterpreterEntries=1
export COMPlus_TieredCompilation=1
export COMPlus_JITMinOpts=1
export COMPlus_ZapDisable=1

# jit
export COMPlus_JitFunctionTrace=1

./bin/Product/Linux.x64.Debug/corerun ~/HelloWorld.dll
```

* ARM64 with similar environment variables

```
./bin/Product/Linux.arm64.Debug/corerun ~/HelloWorld.dll
```

* MIPS64 ditto

```
./bin/Product/Linux.mips64.Debug/corerun ~/HelloWorld.dll
```

But there are only `Start Jitting` and `Jitted Entry`, no `Generating interpretation stub` at all:

```
...
{ Start Jitting ILStubClass:IL_STUB_PInvoke(long) (MethodHash=3045e69f)
} Jitted Entry 22e at 000000ff`722b1650 method ILStubClass:IL_STUB_PInvoke(long) size 000001d0
Histogram of method executions:
   # of execs   |   # meths (%)    |   cum % | % cum execs
   -------------------------------------------------------
            0   |       0 (  nan%) |    nan% |    nan%
            1   |       0 (  nan%) |    nan% |    nan%
            2   |       0 (  nan%) |    nan% |    nan%
            3   |       0 (  nan%) |    nan% |    nan%
            4   |       0 (  nan%) |    nan% |    nan%
            5   |       0 (  nan%) |    nan% |    nan%
            6   |       0 (  nan%) |    nan% |    nan%
            7   |       0 (  nan%) |    nan% |    nan%
            8   |       0 (  nan%) |    nan% |    nan%
            9   |       0 (  nan%) |    nan% |    nan%
           10   |       0 (  nan%) |    nan% |    nan%

For methods sorted in ascending # of executions order, cumulative % of executions:

Total number of calls from interpreted code: 0.
    Also, 0 are intrinsics; 0 of these are not currently handled intrinsically.
    Of these, 0 to potential property getters (0 of these dead simple), 0 to setters.
    Of the dead simple getter calls, 0 have been short-circuited.

Token resolutions by category:
Category     |  opportunities  |   calls   |      %
---------------------------------------------------
   Undefined |               0 |         0 |   0.00%
 Constrained |               0 |         0 |   0.00%
      NewObj |               0 |         0 |   0.00%
      NewArr |               0 |         0 |   0.00%
     LdToken |               0 |         0 |   0.00%
       LdFtn |               0 |         0 |   0.00%
   LdVirtFtn |               0 |         0 |   0.00%
    SFldAddr |               0 |         0 |   0.00%
      LdElem |               0 |         0 |   0.00%
        Call |               0 |         0 |   0.00%
       LdObj |               0 |         0 |   0.00%
       StObj |               0 |         0 |   0.00%
       CpObj |               0 |         0 |   0.00%
     InitObj |               0 |         0 |   0.00%
      IsInst |               0 |         0 |   0.00%
   CastClass |               0 |         0 |   0.00%
    MkRefAny |               0 |         0 |   0.00%
   RefAnyVal |               0 |         0 |   0.00%
      Sizeof |               0 |         0 |   0.00%
      StElem |               0 |         0 |   0.00%
         Box |               0 |         0 |   0.00%
       Unbox |               0 |         0 |   0.00%
    UnboxAny |               0 |         0 |   0.00%
       LdFld |               0 |         0 |   0.00%
      LdFldA |               0 |         0 |   0.00%
       StFld |               0 |         0 |   0.00%
   FindClass |               0 |         0 |   0.00%
   Exception |               0 |         0 |   0.00%
```

Although it is able to hack tieredcompilation https://github.com/dotnet/coreclr/issues/24824#issuecomment-497048982  to force interpreter. 
 There is SEGFAULT issue:

* X86

```
Generating interpretation stub (# 6 = 0x6, hash = 0x9d983a13) for ILStubClass:IL_STUB_InstantiatingStub.
Generating interpretation stub (# 7 = 0x7, hash = 0x253d4d8d) for System.Collections.Generic.EqualityComparer`1[__Canon][System.__Canon]:.cctor.
Entering method dotnet/coreclr#5 (= 0x5): System.Collections.Generic.EqualityComparer`1[__Canon][System.__Canon]:.cctor().
 arguments:
         0:  nativeint: 140737318125363 (= 0x7ffff5da7f33)

Program received signal SIGSEGV, Segmentation fault.
MethodTable::GetTypeDefRid_NoLogging (this=0x758b48f0758948f8) at /home/zhaixiang/coreclr-mips64-dev/src/vm/methodtable.cpp:8161
8161        WORD token = m_wToken;

(gdb) bt
#0  MethodTable::GetTypeDefRid_NoLogging (this=0x758b48f0758948f8)
    at /home/zhaixiang/coreclr-mips64-dev/src/vm/methodtable.cpp:8161
dotnet/coreclr#1  0x00007ffff5e6473f in MethodTable::GetTypeDefRid (this=0x758b48f0758948f8)
    at /home/zhaixiang/coreclr-mips64-dev/src/vm/methodtable.cpp:8153
dotnet/coreclr#2  0x00007ffff5e64620 in MethodTable::HasSameTypeDefAs (this=0x758b48f0758948f8, pMT=0x7fff7c355c48)
    at /home/zhaixiang/coreclr-mips64-dev/src/vm/methodtable.cpp:644
dotnet/coreclr#3  0x00007ffff5e771f0 in MethodTable::GetMethodTableMatchingParentClass (this=
    0x7ffff5da7f33 <FrameWithCookie<GCFrame>::FrameWithCookie(OBJECTREF*, unsigned int, int)+67>, pWhichParent=0x7fff7c355c48)
    at /home/zhaixiang/coreclr-mips64-dev/src/vm/methodtable.cpp:8361
dotnet/coreclr#4  0x00007ffff6019bf5 in InterpreterMethodInfo::GetPreciseGenericsContext (this=0x6b9620, thisArg=0x0, 
    genericsCtxtArg=0x7ffff5da7f33 <FrameWithCookie<GCFrame>::FrameWithCookie(OBJECTREF*, unsigned int, int)+67>)
    at /home/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:8857
dotnet/coreclr#5  0x00007ffff6021d9c in Interpreter::GetPreciseGenericsContext (this=0x7ffffffec198)
    at /home/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.h:1781
dotnet/coreclr#6  0x00007ffff60216da in Interpreter::ResolveToken (this=0x7ffffffec198, resTok=0x7ffffffeb808, token=452984835, 
    tokenType=CORINFO_TOKENKIND_Ldtoken, rtk=Interpreter::RTK_LdToken)
    at /home/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.hpp:396
dotnet/coreclr#7  0x00007ffff601102f in Interpreter::LdToken (this=0x7ffffffec198)
    at /home/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:6337
dotnet/coreclr#8  0x00007ffff6006b35 in Interpreter::ExecuteMethod (this=0x7ffffffec198, retVal=0x7ffffffec180, pDoJmpCall=0x7ffffffed6ef, 
    pJmpCallToken=0x7ffffffec17c) at /home/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:2942
dotnet/coreclr#9  0x00007ffff600347c in Interpreter::ExecuteMethodWrapper (interpMethInfo=0x6b9620, directCall=false, 
    ilArgs=0x7ffffffed990 "3\177\332\365\377\177", stubContext=0x7ffffffeddf0, pDoJmpCall=0x7ffffffed6ef, 
    pResolvedToken=0x7ffffffed698) at /home/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:1589
dotnet/coreclr#10 0x00007ffff6021b02 in Interpreter::InterpretMethodBody (interpMethInfo=0x6b9620, directCall=false, 
    ilArgs=0x7ffffffed990 "3\177\332\365\377\177", stubContext=0x7ffffffeddf0)
    at /home/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:1624
dotnet/coreclr#11 0x00007ffff6002d07 in InterpretMethod (interpMethInfo=0x6b9620, ilArgs=0x7ffffffed990 "3\177\332\365\377\177", 
    stubContext=0x7ffffffeddf0) at /home/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:1745
dotnet/coreclr#12 0x00007fff7c0cd2e4 in ?? ()
dotnet/coreclr#13 0x00007fffffffe0a0 in ?? ()
dotnet/coreclr#14 0x0000000000000000 in ?? ()
```

* ARM64

```
Generating interpretation stub (# 1 = 0x1, hash = 0xd8570543) for System.AppContext:Setup.

Thread 1 "corerun" received signal SIGSEGV, Segmentation fault.
0x0000007fb70b5658 in Interpreter::Interpreter (this=0x7fffffe710, methInfo_=0x0, directCall_=127, ilArgs_=0x0, stubContext_=0x7f3d43ab60, frameMemory=0x7f3d43ab60 "0~D=\177") at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.h:812
812        {
(gdb) bt
#0  0x0000007fb70b5658 in Interpreter::Interpreter (this=0x7fffffe710, methInfo_=0x0, directCall_=127, ilArgs_=0x0, stubContext_=0x7f3d43ab60, frameMemory=0x7f3d43ab60 "0~D=\177") at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.h:812
dotnet/coreclr#1  0x0000007fb7098eb4 in Interpreter::ExecuteMethodWrapper (interpMethInfo=0x7fb6f8d4c4 <MetaSig::NextArg()+156>, directCall=false, ilArgs=0x7fffffe2f8 "\020vC", stubContext=0x0, pDoJmpCall=0x7fffffe01c, pResolvedToken=0x7fffffdfc8) at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:1577
dotnet/coreclr#2  0x0000007fb70b5f7c in Interpreter::InterpretMethodBody (interpMethInfo=0x7fb6f8d4c4 <MetaSig::NextArg()+156>, directCall=false, ilArgs=0x7fffffe2f8 "\020vC", stubContext=0x0) at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:1624
dotnet/coreclr#3  0x0000007fb709887c in InterpretMethod (interpMethInfo=0x7fb6f8d4c4 <MetaSig::NextArg()+156>, ilArgs=0x7fffffe2f8 "\020vC", stubContext=0x0) at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:1745
dotnet/coreclr#4  0x0000007f3d19d060 in ?? ()
dotnet/coreclr#5  0x0000000000437610 in ?? ()
```

* MIPS64

```
Generating interpretation stub (# 1 = 0x1, hash = 0xd8570543) for System.AppContext:Setup.

Program received signal SIGSEGV, Segmentation fault.
0x000000fff696b224 in Interpreter::Interpreter (this=<error reading variable: Cannot access memory at address 0xf33332ba70>, methInfo_=<error reading variable: Cannot access memory at address 0xf33332ba68>, directCall_=<error reading variable: Cannot access memory at address 0xf33332ba64>, ilArgs_=<error reading variable: Cannot access memory at address 0xf33332ba58>, stubContext_=<error reading variable: Cannot access memory at address 0xf33332ba50>, frameMemory=<error reading variable: Cannot access memory at address 0xf33332ba48>) at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.h:812
812        {
Missing separate debuginfos, use: debuginfo-install libgcc-4.9.3-11.fc21.loongson.11.mips64el libstdc++-4.9.3-11.fc21.loongson.11.mips64el lttng-ust-2.4.1-3.fc21.loongson.mips64el userspace-rcu-0.8.1-6.fc21.loongson.mips64el xz-libs-5.1.2-14alpha.fc21.loongson.mips64el
(gdb) bt
#0  0x000000fff696b224 in Interpreter::Interpreter (this=<error reading variable: Cannot access memory at address 0xf33332ba70>, methInfo_=<error reading variable: Cannot access memory at address 0xf33332ba68>, directCall_=<error reading variable: Cannot access memory at address 0xf33332ba64>, ilArgs_=<error reading variable: Cannot access memory at address 0xf33332ba58>, stubContext_=<error reading variable: Cannot access memory at address 0xf33332ba50>, frameMemory=<error reading variable: Cannot access memory at address 0xf33332ba48>) at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.h:812
dotnet/coreclr#1  0x000000fff693d75c in Interpreter::ExecuteMethodWrapper (interpMethInfo=<error reading variable: Cannot access memory at address 0xf33332bb38>, directCall=<error reading variable: Cannot access memory at address 0xf33332bb34>, ilArgs=<error reading variable: Cannot access memory at address 0xf33332bb28>, stubContext=<error reading variable: Cannot access memory at address 0xf33332bb20>, pDoJmpCall=<error reading variable: Cannot access memory at address 0xf33332bb18>, pResolvedToken=<error reading variable: Cannot access memory at address 0xf33332bb10>) at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:1627
dotnet/coreclr#2  0x000000fff696c1b4 in Interpreter::InterpretMethodBody (interpMethInfo=0x1200be190, directCall=false, ilArgs=0xffffffa0b8 "py\003 \001", stubContext=0x0) at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:1674
dotnet/coreclr#3  0x000000fff693cbec in InterpretMethod (interpMethInfo=0x1200be190, ilArgs=0xffffffa0b8 "py\003 \001", stubContext=0x0) at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/interpreter.cpp:1795
dotnet/coreclr#4  0x000000fff6c0b608 in CallDescrWorkerInternal () at /home/loongson/zhaixiang/coreclr-mips64-dev/src/vm/mips64/calldescrworkermips64.S:74
Backtrace stopped: frame did not save the PC
```

How to mix Interpreter and JIT compiler?  Please give me some hint.

Thanks,
Leslie Zhai

category:correctness
theme:interpreter
skill-level:intermediate
cost:small

### PR DESCRIPTION
**Pull request by yuchong-pan**
1. Bug fix: Fix type casts in `interpreter.cpp` to make the codebase compile on Windows when `FEATURE_INTERPRETER` is turned on.
2. Bug fix: Special case `get_IsSupported` in the interpreter to semantically correctly interpret hardware intrinsics.
3. Bug fix: Fix bugs for the asynchronous promotion to Tier 1 in Tiered Compilation.
4. Improvement: Add two `COMPlus_` environment variables `ForceInterpreterTier0` and `ForceInterpreterAlways` to force the interpreter to be used as Tier 0 and always, respectively. Note that these two environment variables respect others; for instance, if `InterpreterFallback` is set to `1`, then JIT is still the default option. (Hence please check if the descriptions of the two environment variables are accurate.)

Fixes dotnet#13759.

With the above changes to the codebase, the interpreter runs on the following Hello World sample program. The number of calls to `Not` is used to trigger the promotion to Tier 1 in Tiered Compilation.

```c#
using System;

namespace ConsoleApp
{
    class Program
    {
        static bool Not(bool p)
        {
            bool q = p;
            q = !q;
            return q;
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            bool b = true;
            bool bb = Not(b);

            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);
            bb = Not(bb);

            Console.WriteLine(bb);
        }
    }
}
```

The following steps reproduce the result on the Hello World sample program (on Windows):
* Replace line 20 with `set(FEATURE_INTERPRETER 0)` in `src\coreclr\clrfeatures.cmake`.
* Build the Runtime by `.\build.cmd -subset clr.runtime`.
* Built the C# program below in Release.
* Set the `COMPlus_` environment variables by the following (e.g. in Powershell):
```powershell
$env:COMPlus_Interpret='*'
$env:COMPlus_ZapDisable=1
$env:COMPlus_InterpreterJITThreshold=10
$env:COMPlus_TC_CallCountThreshold=10
$env:COMPlus_TieredCompilation=1
$env:COMPlus_InterpreterHWIntrinsicsIsSupportedFalse=1
$env:COMPlus_InterpreterDoLoopMethods=1

# tracing
$env:COMPlus_InterpreterPrintPostMortem=1
$env:COMPlus_TraceInterpreterVerbose=0
$env:COMPlus_TraceInterpreterIL=0
$env:COMPlus_TraceInterpreterEntries=0
$env:COMPlus_DumpInterpreterStubs=0
$env:COMPlus_JitFunctionTrace=0
$env:COMPlus_TraceInterpreterJITTransition=1
```
* Use the built Runtime to execute the C# program.

Current Priority 0 passing rate:
```
  === TEST EXECUTION SUMMARY ===
     baseservices.compilerservices.XUnitWrapper           Total:    2, Errors: 0, Failed:   0, Skipped: 0, Time:     2.552s
     baseservices.exceptions.XUnitWrapper.dll             Total:    0
     baseservices.mono.XUnitWrapper.dll                   Total:    0
     baseservices.threading.XUnitWrapper                  Total:    4, Errors: 0, Failed:   0, Skipped: 0, Time:     9.893s
     baseservices.TieredCompilation.XUnitWrapper          Total:   11, Errors: 0, Failed:   1, Skipped: 0, Time:     9.210s
     baseservices.typeequivalence.XUnitWrapper            Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     0.952s
     baseservices.varargs.XUnitWrapper.dll                Total:    0
     CoreMangLib.system.XUnitWrapper                      Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     0.837s
     Exceptions.ForeignThread.XUnitWrapper                Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:     1.669s
     GC.API.XUnitWrapper                                  Total:   33, Errors: 0, Failed:   2, Skipped: 0, Time:   916.993s
     GC.Coverage.XUnitWrapper                             Total:    2, Errors: 0, Failed:   1, Skipped: 0, Time:   900.149s
     GC.Features.XUnitWrapper                             Total:   21, Errors: 0, Failed:   8, Skipped: 0, Time:   984.539s
     GC.LargeMemory.XUnitWrapper                          Total:    3, Errors: 0, Failed:   0, Skipped: 0, Time:    21.050s
     GC.Regressions.XUnitWrapper                          Total:   10, Errors: 0, Failed:   1, Skipped: 0, Time:   901.862s
     GC.Scenarios.XUnitWrapper                            Total:   37, Errors: 0, Failed:   8, Skipped: 0, Time:  1035.292s
     GC.Stress.XUnitWrapper                               Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     0.256s
     ilasm.System.XUnitWrapper                            Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:    18.275s
     Interop.ArrayMarshalling.XUnitWrapper                Total:    2, Errors: 0, Failed:   2, Skipped: 0, Time:    15.158s
     Interop.COM.XUnitWrapper                             Total:   19, Errors: 0, Failed:  14, Skipped: 0, Time:    64.475s
     Interop.DllImportAttribute.XUnitWrapper              Total:    2, Errors: 0, Failed:   0, Skipped: 0, Time:    12.541s
     Interop.ExecInDefAppDom.XUnitWrapper                 Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:     5.589s
     Interop.ICastable.XUnitWrapper                       Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:     8.021s
     Interop.ICustomMarshaler.XUnitWrapper                Total:    4, Errors: 0, Failed:   2, Skipped: 0, Time:    75.785s
     Interop.IJW.XUnitWrapper                             Total:    6, Errors: 0, Failed:   4, Skipped: 0, Time:    24.053s
     Interop.LayoutClass.XUnitWrapper                     Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:   901.902s
     Interop.MarshalAPI.XUnitWrapper                      Total:    3, Errors: 0, Failed:   2, Skipped: 0, Time:    22.342s
     Interop.NativeLibrary.XUnitWrapper                   Total:    5, Errors: 0, Failed:   0, Skipped: 0, Time:    10.118s
     Interop.PInvoke.XUnitWrapper                         Total:   85, Errors: 0, Failed:  18, Skipped: 0, Time:   978.328s
     Interop.StringMarshalling.XUnitWrapper               Total:    4, Errors: 0, Failed:   3, Skipped: 0, Time:     5.075s
     Interop.StructMarshalling.XUnitWrapper               Total:    5, Errors: 0, Failed:   5, Skipped: 0, Time:     9.618s
     Interop.StructPacking.XUnitWrapper                   Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     3.478s
     Interop.WinRT.XUnitWrapper                           Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     2.959s
     JIT.CheckProjects.XUnitWrapper                       Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     2.264s
     JIT.CodeGenBringUpTests.XUnitWrapper                 Total:   32, Errors: 0, Failed:   0, Skipped: 0, Time:    48.442s
     JIT.Directed.XUnitWrapper                            Total:  138, Errors: 0, Failed:  25, Skipped: 0, Time:   947.426s
     JIT.Generics.XUnitWrapper                            Total:   41, Errors: 0, Failed:   4, Skipped: 0, Time:    29.733s
     JIT.HardwareIntrinsics.XUnitWrapper                  Total:  302, Errors: 0, Failed:  94, Skipped: 0, Time:   209.510s
     JIT.IL_Conformance.XUnitWrapper                      Total:  104, Errors: 0, Failed:   0, Skipped: 0, Time:    62.196s
     JIT.Intrinsics.XUnitWrapper                          Total:   23, Errors: 0, Failed:   2, Skipped: 0, Time:    24.198s
     JIT.jit64.XUnitWrapper                               Total:  105, Errors: 0, Failed:  36, Skipped: 0, Time:   970.743s
     JIT.Methodical.XUnitWrapper                          Total:  763, Errors: 0, Failed: 108, Skipped: 0, Time:  3857.773s
     JIT.opt.XUnitWrapper                                 Total:   68, Errors: 0, Failed:   4, Skipped: 0, Time:   146.098s
     JIT.Performance.XUnitWrapper                         Total:   85, Errors: 0, Failed:  16, Skipped: 0, Time:  2027.139s
     JIT.Regression.XUnitWrapper                          Total:  606, Errors: 0, Failed:  29, Skipped: 0, Time:  2371.085s
     JIT.RyuJIT.XUnitWrapper                              Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     2.940s
     JIT.SIMD.XUnitWrapper                                Total:   99, Errors: 0, Failed:  37, Skipped: 0, Time:  2262.503s
     JIT.Stress.XUnitWrapper                              Total:    5, Errors: 0, Failed:   0, Skipped: 0, Time:     3.411s
     JIT.superpmi.XUnitWrapper                            Total:    3, Errors: 0, Failed:   2, Skipped: 0, Time:   901.856s
     Loader.AssemblyDependencyResolver.XUnitWrapper       Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:    15.791s
     Loader.AssemblyLoadContext30Extensions.XUnitWrapper  Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:    10.845s
     Loader.binding.XUnitWrapper                          Total:    2, Errors: 0, Failed:   2, Skipped: 0, Time:    13.222s
     Loader.classloader.XUnitWrapper                      Total:  106, Errors: 0, Failed:  10, Skipped: 0, Time:   289.772s
     Loader.ContextualReflection.XUnitWrapper             Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:     5.957s
     Loader.regressions.XUnitWrapper                      Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     4.141s
     managed.Compilation.XUnitWrapper                     Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:    79.046s
     profiler.eventpipe.XUnitWrapper                      Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:    14.825s
     profiler.gc.XUnitWrapper                             Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     8.556s
     profiler.rejit.XUnitWrapper                          Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     0.177s
     profiler.unittest.XUnitWrapper                       Total:    2, Errors: 0, Failed:   1, Skipped: 0, Time:    13.039s
     readytorun.coreroot_determinism.XUnitWrapper         Total:    1, Errors: 0, Failed:   1, Skipped: 0, Time:    24.766s
     readytorun.crossgen2.XUnitWrapper                    Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:    21.276s
     readytorun.determinism.XUnitWrapper                  Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:    25.744s
     readytorun.DynamicMethodGCStress.XUnitWrapper.dll    Total:    0
     readytorun.r2rdump.XUnitWrapper.dll                  Total:    0
     readytorun.tests.XUnitWrapper                        Total:    3, Errors: 0, Failed:   0, Skipped: 0, Time:     7.662s
     reflection.DefaultInterfaceMethods.XUnitWrapper      Total:    3, Errors: 0, Failed:   1, Skipped: 0, Time:   901.236s
     reflection.Modifiers.XUnitWrapper                    Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     3.851s
     reflection.SetValue.XUnitWrapper                     Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     4.970s
     reflection.StaticInterfaceMembers.XUnitWrapper       Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     3.612s
     Regressions.coreclr.XUnitWrapper                     Total:   20, Errors: 0, Failed:   9, Skipped: 0, Time:    29.335s
     tracing.eventactivityidcontrol.XUnitWrapper          Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     3.301s
     tracing.eventcounter.XUnitWrapper                    Total:    5, Errors: 0, Failed:   0, Skipped: 0, Time:     0.495s
     tracing.eventlistener.XUnitWrapper                   Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     4.143s
     tracing.eventpipe.XUnitWrapper                       Total:    5, Errors: 0, Failed:   1, Skipped: 0, Time:     6.415s
     tracing.eventsource.XUnitWrapper                     Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     0.166s
     tracing.regress.XUnitWrapper                         Total:    1, Errors: 0, Failed:   0, Skipped: 0, Time:     3.275s
     tracing.tracecontrol.XUnitWrapper.dll                Total:    0
     tracing.tracevalidation.XUnitWrapper                 Total:    4, Errors: 0, Failed:   3, Skipped: 0, Time:    66.634s
                                                                 ----          -          ---           -        ----------
                                                    GRAND TOTAL: 2812          0          465           0        22372.537s (22411.881s)
```

### CODE REVIEW

File: src/coreclr/src/inc/corinfo.h [hunk 1]
```diff
@@ -955,6 +955,7 @@ enum CorInfoIntrinsics
     CORINFO_INTRINSIC_Span_GetItem,
     CORINFO_INTRINSIC_ReadOnlySpan_GetItem,
     CORINFO_INTRINSIC_GetRawHandle,
+    CORINFO_INTRINSIC_GetIsSupported,       // for interpreting hardware intrinsics
```
Comment (jkotas) [inline src/coreclr/src/inc/corinfo.h:958]: This is legacy method for identifying intrinsics. It would be best to avoid adding more to it.

The preferred method for itentifying intrinsics is by name (e.g. look for `CORINFO_FLG_JIT_INTRINSIC` and related code).

File: src/coreclr/src/vm/interpreter.cpp [hunk 2]
```diff
@@ -10615,6 +10649,20 @@ void Interpreter::DoSIMDHwAccelerated()
...
+void Interpreter::DoGetIsSupported()
+{
+    CONTRACTL{
+        THROWS;
+        GC_TRIGGERS;
+        MODE_COOPERATIVE;
+    } CONTRACTL_END;
+
+    OpStackSet<BOOL>(m_curStackHt, false);
+    OpStackTypeSet(m_curStackHt, InterpreterType(CORINFO_TYPE_INT));
```
Comment (jkotas) [inline src/coreclr/src/vm/interpreter.cpp:10662]: The interpreter should be in sync on which hardware intrinsics are supported. This should return the same value as if the method was JITed.

File: src/coreclr/src/vm/method.cpp [hunk 3]
```diff
@@ -4865,6 +4865,16 @@ bool MethodDesc::IsJitOptimizationDisabled()
 {
     WRAPPER_NO_CONTRACT;
 
+#ifdef FEATURE_INTERPRETER
+    static ConfigDWORD s_ForceInterpreterTier0;
+    static ConfigDWORD s_ForceInterpreterAlways;
+    if (s_ForceInterpreterAlways.val(CLRConfig::INTERNAL_ForceInterpreterAlways) == 0 &&
```
Comment (noahfalk) [inline src/coreclr/src/vm/method.cpp:4871]: The check for ForceInterpreterAlways appears unneeded here? If ForceInterpreter==1 then the method is going to be interpretted regardless of whether jit optimization is allowed.

File: src/coreclr/src/vm/interpreter.cpp [hunk 4]
```diff
@@ -1636,6 +1636,7 @@ void Interpreter::JitMethodIfAppropriate(InterpreterMethodInfo* interpMethInfo,
 
         if (InterpretationStubToMethodInfo(stub) == md)
         {
+            CodeVersionManager::LockHolder _lockHolder;
```
Comment (noahfalk) [inline src/coreclr/src/vm/interpreter.cpp:1639]: Its best to do as little work inside of locks as necessary. I'd recommend moving it down to after the ifdef at 1667.

**Review by noahfalk — CHANGES_REQUESTED** [review]
Is this the first runtime PR? Congrats :D

I made some suggestions inline and happy to chat anytime if you've got questions

**Comment by jkotas** [comment]
> @jkotas, I had been thinking of IsSupported as a property that could vary when different code generators run the same method.

If we want to allow arbitrary combinations of different code generators in the same process, the IsSupported values cannot vary between them. For example, somebody writes code like:

```
readonly static RenderingEngine s_engine = Avx.IsSupported ? new AvxRenderingEngine() : new GenericRenderingEngine();

class GenericRenderingEngine : RenderingEngine
{
...
    virtual void Render()
    {
        Debug.Assert(!Avx.IsSupported); 
        ...
    }
...
}
```

Consider what happens when the interpretation of the `Avx.IsSupported` returns false during startup and we later switch the Render method to be JITed.

A similar problem exists with crossgen. We had bugs where IsSupported returned different values in crossgened core and JITed code, and it showed up as a real problem.

I do not think we should be special casing the individual hardware intrinsics in the interpreter. As you have said, there is a lot of them. We should depend on fallback to JIT for the hardware intrinsics methods. The JIT does generate valid body for the hardware intrinsics methods that can be called e.g. via reflection.

> check in this current design under a config switch

I am fine with that - as long it is well documented that it is not a production quality solution.

File: src/coreclr/src/vm/interpreter.cpp (hunk 4 above)
Comment (yuchong-pan) [reply src/coreclr/src/vm/interpreter.cpp]: Done in commit https://github.com/dotnet/runtime/pull/37825/commits/748c7ade014aeb6dbe5246d437ac1eb95162b58b.

File: src/coreclr/src/vm/method.cpp (hunk 3 above)
Comment (yuchong-pan) [reply src/coreclr/src/vm/method.cpp:4871]: The check for `ForceInterpreterAlways` _is_ unneeded here. I just added this check to minimize the change from the original codebase. I can remove this check.

Comment (yuchong-pan) [reply src/coreclr/src/vm/method.cpp]: Done in commit https://github.com/dotnet/runtime/pull/37825/commits/3345ef30ec343156746d028112c34a78cd67851a.

File: src/coreclr/src/inc/clrconfigvalues.h [hunk 5]
```diff
@@ -395,6 +395,8 @@ RETAIL_CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterIL, W("TraceInterpreterIL"), 0
 RETAIL_CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterOstack, W("TraceInterpreterOstack"), 0, "Logs operand stack after each IL instruction of interpreted methods to the console")
 CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterVerbose, W("TraceInterpreterVerbose"), 0, "Logs interpreter progress with detailed messages to the console")
 CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterJITTransition, W("TraceInterpreterJITTransition"), 0, "Logs when the interpreter determines a method should be JITted")
+RETAIL_CONFIG_DWORD_INFO(INTERNAL_ForceInterpreterTier0, W("ForceInterpreterTier0"), 0, "If non-zero, force the interpreter to be used as Tier 0 in Tiered Compilation") // this has no effect in Release
```
[the remark this answers is not in the document]
Comment (yuchong-pan) [reply src/coreclr/src/inc/clrconfigvalues.h]: Done in commit https://github.com/dotnet/runtime/pull/37825/commits/e4dccdfe6ff3628e5f8eeac24ad772634f541f47. I also renamed `ForceInterpreterAlways` to `ForceInterpreter`.

File: src/coreclr/src/vm/interpreter.cpp [hunk 6]
```diff
@@ -1665,7 +1666,12 @@ void Interpreter::JitMethodIfAppropriate(InterpreterMethodInfo* interpMethInfo,
 #ifdef FEATURE_TIERED_COMPILATION
             bool scheduleTieringBackgroundWork = false;
             NativeCodeVersion activeCodeVersion = md->GetCodeVersionManager()->GetActiveILCodeVersion(md).GetActiveNativeCodeVersion(md);
-            GetAppDomain()->GetTieredCompilationManager()->AsyncPromoteToTier1(activeCodeVersion, &scheduleTieringBackgroundWork);
+            ILCodeVersion ilCodeVersion = activeCodeVersion.GetILCodeVersion();
+            if (activeCodeVersion.GetOptimizationTier() == NativeCodeVersion::OptimizationTier0 &&
+                !ilCodeVersion.HasAnyOptimizedNativeCodeVersion(activeCodeVersion))
+            {
+                GetAppDomain()->GetTieredCompilationManager()->AsyncPromoteToTier1(activeCodeVersion, &scheduleTieringBackgroundWork);
+            }
```
[the remark this answers is not in the document]
Comment (yuchong-pan) [reply src/coreclr/src/vm/interpreter.cpp:1680]: Hi @noahfalk! I fixed this bug in commit https://github.com/dotnet/runtime/pull/37825/commits/f01109b9c5e4402d991e391206ccd30d1efedcee. Could you check if this is what you intended?

File: src/coreclr/src/inc/clrconfigvalues.h [hunk 7]
```diff
@@ -383,7 +383,7 @@ RETAIL_CONFIG_DWORD_INFO(INTERNAL_InterpreterMethHashMin, W("InterpreterMethHash
 RETAIL_CONFIG_DWORD_INFO(INTERNAL_InterpreterMethHashMax, W("InterpreterMethHashMax"), UINT32_MAX, "If non-zero, only interpret methods selected by 'Interpret' whose hash is at most this value")
 RETAIL_CONFIG_DWORD_INFO(INTERNAL_InterpreterStubMin, W("InterpreterStubMin"), 0, "Only interpret methods selected by 'Interpret' whose stub num is at least this value.")
 RETAIL_CONFIG_DWORD_INFO(INTERNAL_InterpreterStubMax, W("InterpreterStubMax"), UINT32_MAX, "If non-zero, only interpret methods selected by 'Interpret' whose stub number is at most this value.")
-RETAIL_CONFIG_DWORD_INFO(INTERNAL_InterpreterJITThreshold, W("InterpreterJITThreshold"), 10, "The number of times a method should be interpreted before being JITted")
+RETAIL_CONFIG_DWORD_INFO(INTERNAL_InterpreterJITThreshold, W("InterpreterJITThreshold"), 10, "The number of times (in hexadecimal) a method should be interpreted before being JITted")
```
Comment (BruceForstall) [inline src/coreclr/src/inc/clrconfigvalues.h:386]: It's fine to add this clarification, but note that _every_ integer COMPlus value is parsed as hex, not just this one.

File: src/coreclr/src/inc/clrconfigvalues.h [hunk 8]
```diff
@@ -395,6 +395,8 @@ RETAIL_CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterIL, W("TraceInterpreterIL"), 0
 RETAIL_CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterOstack, W("TraceInterpreterOstack"), 0, "Logs operand stack after each IL instruction of interpreted methods to the console")
 CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterVerbose, W("TraceInterpreterVerbose"), 0, "Logs interpreter progress with detailed messages to the console")
 CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterJITTransition, W("TraceInterpreterJITTransition"), 0, "Logs when the interpreter determines a method should be JITted")
+RETAIL_CONFIG_DWORD_INFO(INTERNAL_ForceJitOptimization, W("ForceJitOptimization"), 0, "If non-zero, force JIT optimization to be enabled") // this has no effect in Release
```
Comment (BruceForstall) [inline src/coreclr/src/inc/clrconfigvalues.h:398]: I'll have to look farther in this PR, but this name (ForceJitOptimization) doesn't seem appropriate.

Also, would it be useful to have all interpreter-related COMPlus variable names use `Interpreter` as a prefix (as most or all currently do)?

File: src/coreclr/src/vm/interpreter.cpp [hunk 9]
```diff
@@ -279,7 +279,7 @@ void InterpreterMethodInfo::InitArgInfo(CEEInfo* comp, CORINFO_METHOD_INFO* meth
                 }
                 m_argDescs[k].m_typeStackNormal = m_argDescs[k].m_type;
                 m_argDescs[k].m_nativeOffset = argOffsets_[k];
-                m_argDescs[k].m_directOffset = reinterpret_cast<short>(ArgSlotEndianessFixup(directOffset, sizeof(void*)));
+                m_argDescs[k].m_directOffset = (short) reinterpret_cast<intptr_t>(ArgSlotEndianessFixup(directOffset, sizeof(void*)));
```
Comment (BruceForstall) [inline src/coreclr/src/vm/interpreter.cpp:282]: It seems very odd to have a new-style cast followed by an old-style cast. Was there a compiler error here (and below)?

Comment (yuchong-pan) [reply src/coreclr/src/vm/interpreter.cpp:282]: Yes, there were compiler errors (at least on Windows) concerning the original lines of type cast `reinterpret_cast<short>(...)`. The modifications fix these compiler errors.

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 8 above)
Comment (yuchong-pan) [reply src/coreclr/src/inc/clrconfigvalues.h:398]: Hi @BruceForstall, thanks for pointing that out! The name `ForceJitOptimization` seems to describe what the flag does in the following place:
https://github.com/dotnet/runtime/blob/f01109b9c5e4402d991e391206ccd30d1efedcee/src/coreclr/src/vm/method.cpp#L4868
I feel that it is similar to @noahfalk's suggestion `AllowOptimizationForDebugCode`.

I agree that it would be best if the interpreter-related names have `Interpreter` as a prefix. Do you have recommendations for these names?

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 7 above)
Comment (yuchong-pan) [reply src/coreclr/src/inc/clrconfigvalues.h]: Hi @BruceForstall, thanks for mentioning this! Maybe this is specified somewhere in the documentation but I missed it. Anyway, I remove this redundant annotation in commit https://github.com/dotnet/runtime/pull/37825/commits/2328ced54e384af01f53769998dd0ed957167996.

File: src/coreclr/src/inc/corinfo.h (hunk 1 above)
Comment (yuchong-pan) [reply src/coreclr/src/inc/corinfo.h]: Hi @jkotas, thanks for pointing this out! I removed my changes in commit https://github.com/dotnet/runtime/pull/37825/commits/46a004c71e0e8e7614b160e702e4f636cf203774. However, I feel that a possibly more appropriate location to identify intrinsics is the handling of "intrinsics-like" methods after the `switch` for intrinsics:

https://github.com/dotnet/runtime/blob/46a004c71e0e8e7614b160e702e4f636cf203774/src/coreclr/src/vm/interpreter.cpp#L9074

Could you please check if this aligns with the pattern in the codebase? Thanks very much!

Comment (jkotas) [reply src/coreclr/src/inc/corinfo.h]: This needs TODO comment that it is workaround that does not produce correct results. (more context in https://github.com/dotnet/runtime/pull/37825#issuecomment-643630137).

File: src/coreclr/src/vm/interpreter.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (yuchong-pan) [reply src/coreclr/src/vm/interpreter.cpp:1675]: This previous fix does not seem to work and has been reverted. I think the following commit should do: https://github.com/dotnet/runtime/pull/37825/commits/24c8de178bf0109999146e76f002dad6b0ad9168.

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 8 above)
Comment (noahfalk) [reply src/coreclr/src/inc/clrconfigvalues.h:398]: The current implementation isn't forcing that jit optimization must occur, rather it permits optimized compilation to possibly occur. If all the other criteria are met the method will be marked as being eligible for tiered compilation, and then if the method is executed frequently enough the tier1 version will be compiled that contains optimizations. I'd suggest breaking the discussion in two parts:
1. Is the implemented behavior useful or do we actually want something else?
2. If that is the behavior we want, what is a good name for it?

Thinking on it a bit I can't tell if this is useful behavior? If the goal is to test performance I assume we'd want to do that on a release build. If the goal is to test correctness of the interpreter I assume we'd want to use the interpreter as much as possible. So far the only scenario I've come up with where we'd want to tier up from interpreter code to jitted code in Debug is if we need to run lots of test code that is already Debug configuration but the performance is so bad that we have to tier up the frequently executed code paths to let the tests run in a reasonable timeframe. Of course there could be another use you had in mind that I am not thinking of?

Comment (BruceForstall) [reply src/coreclr/src/inc/clrconfigvalues.h:398]: Thanks for the comment, @noahfalk ! My problem with the name it is sounds like it is forcing the JIT to generate code with certain characteristics, which is not the point here at all (and doesn't affect what the JIT will do). But I agree that it makes sense to better understand the scenario here.

File: src/coreclr/src/vm/interpreter.cpp (hunk 9 above)
Comment (BruceForstall) [reply src/coreclr/src/vm/interpreter.cpp:282]: Would it be better, then, to have, for example:
```
m_argDescs[k].m_directOffset = reinterpret_cast<short>( reinterpret_cast<intptr_t>(ArgSlotEndianessFixup(directOffset, sizeof(void*))) );
```
to not mix the cast types?

File: src/coreclr/src/vm/interpreter.cpp (hunk 2 above)
Comment (noahfalk) [reply src/coreclr/src/vm/interpreter.cpp:10673]: I think I saw a reply from @jkotas in email but github isn't showing it to me now. We should surround the logic that makes IsSupported return FALSE with a config variable that developers would need to explicitly set + comment that it is only intended for internal testing purposes.

@jkotas suggestion that we invoke the JIT for all of these intrinsics seemed like a reasonable production solution when the time comes in the future. I have some concerns that the high overhead interpreter has to call methods may make the performance look pretty bad, but that is a concern for a later time.

File: src/coreclr/src/vm/interpreter.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (yuchong-pan) [reply src/coreclr/src/vm/interpreter.cpp:1675]: This commit should work according offline discussion.

File: src/coreclr/src/inc/corinfo.h (hunk 1 above)
Comment (yuchong-pan) [reply src/coreclr/src/inc/corinfo.h]: Done in commit https://github.com/dotnet/runtime/pull/37825/commits/2fd5c4b610c0b52374403acae872fd0a6a18099e.

File: src/coreclr/src/vm/interpreter.cpp (hunk 9 above)
Comment (yuchong-pan) [reply src/coreclr/src/vm/interpreter.cpp:282]: Hi @BruceForstall, I don't think your proposed solution compiles (on Windows). The C++ compiler returns the following error:
```
    16>C:\Users\t-yucpan\GitHub\runtime\src\coreclr\src\vm\interpreter.cpp(282,150): error C2440: 'reinterpret_cast': cannot convert from 'intptr_t' to 'short' [C:\Users\t-yucpan\GitHub\runtime\artifacts\obj\coreclr\Windows_NT.x64.Checked\src\vm\wks\cee_wks.vcxproj]
```

Comment (BruceForstall) [reply src/coreclr/src/vm/interpreter.cpp:282]: maybe `static_cast` is appropriate?

Comment (yuchong-pan) [reply src/coreclr/src/vm/interpreter.cpp]: Hi @BruceForstall. Thanks for pointing this out! Indeed `static_cast<short>` works. I have converted all C-style casts to `static_cast` in commit https://github.com/dotnet/runtime/pull/37825/commits/76425bd4e09b96ba3a4dafb2a212747f22860827.

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 8 above)
Comment (yuchong-pan) [reply src/coreclr/src/inc/clrconfigvalues.h:398]: Hi @noahfalk, thanks for your reply! I think it is a good point to think about the use scenarios of the added `COMPlus` variables. I agree that the two scenarios you came up with (i.e. testing performance in Release` and testing functionality with interpreter triggered as much as possible) are the two main scenarios in my mind. My initial thought to trigger the interpreter only in Tier 0 in Debug/checked is due to the following two scenarios:

1. To mimic the behavior of the Runtime in Release so we can also test the correctness of promotion from Tier 0 to Tier 1.
2. In the future when CI is set up for the interpreter, to check the assertions in CI for the interpreter in the Checked configuration.

Do you think that these two are good scenarios to consider?

Comment (yuchong-pan) [reply src/coreclr/src/inc/clrconfigvalues.h]: I renamed `ForceJitOptimization` to `AllowJitOptimization` in commit https://github.com/dotnet/runtime/pull/37825/commits/7cdd55f830ca869aeee386ee4945d41ed588f7b9.

File: src/coreclr/src/vm/interpreter.cpp (hunk 2 above)
Comment (yuchong-pan) [reply src/coreclr/src/vm/interpreter.cpp:10684]: I added a `COMPlus` variable `InterpreterHWIntrinsicsIsSupportedFalse` in commit https://github.com/dotnet/runtime/pull/37825/commits/ba907e0fe46657872e7a6e74ec5aa5341ace7224 to force `get_IsSupported` to return false.

**Review by BruceForstall — APPROVED** [review]
This LGTM. I'd prefer if @noahfalk and/or @josalem also chime in before merging, though.

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 8 above)
Comment (josalem) [reply src/coreclr/src/inc/clrconfigvalues.h]: I want to clarify something here: your comment in the code mentions that this only applies to Debug/Checked code and not Release; are you referring to the runtime or the C# application?  My understanding of this flag was that it was similar to enabling JIT optimizations when debugging a managed application in VS, i.e., that you are allowing the JIT to optimize *debug IL code*.  Does the runtime's configuration have any impact on this flag?

File: src/coreclr/src/vm/interpreter.cpp [hunk 10]
```diff
@@ -1627,6 +1627,8 @@ void Interpreter::JitMethodIfAppropriate(InterpreterMethodInfo* interpMethInfo,
     } CONTRACTL_END;
 
     unsigned int MaxInterpretCount = s_InterpreterJITThreshold.val(CLRConfig::INTERNAL_InterpreterJITThreshold);
+    bool scheduleTieringBackgroundWork = false;
+    TieredCompilationManager * tieredCompilationManager = GetAppDomain()->GetTieredCompilationManager();
```
Comment (josalem) [inline src/coreclr/src/vm/interpreter.cpp:1631]:
```suggestion
    TieredCompilationManager *tieredCompilationManager = GetAppDomain()->GetTieredCompilationManager();
```

**Review by josalem — APPROVED** [review]
Left some comments inline.  I think the name may need to be clarified a little for the `INTERNAL_EnableJitOptimization` flag, but other than that, this is a great first PR!

File: src/coreclr/src/vm/interpreter.h [hunk 11]
```diff
@@ -13,6 +13,13 @@
 #include "stack.h"
 #include "crst.h"
 #include "callhelpers.h"
+#include "codeversion.h"
+
+#ifdef PAL_STDCPP_COMPAT
```
Comment (jkotas) [inline src/coreclr/src/vm/interpreter.h:18]: You do not need this. `PAL_STDCPP_COMPAT` is never defined when building vm.

File: src/coreclr/src/vm/method.cpp [hunk 12]
```diff
@@ -4865,6 +4865,14 @@ bool MethodDesc::IsJitOptimizationDisabled()
 {
     WRAPPER_NO_CONTRACT;
 
+#ifdef FEATURE_INTERPRETER
+    static ConfigDWORD s_EnableJitOptimization;
+    if (s_EnableJitOptimization.val(CLRConfig::INTERNAL_EnableJitOptimization) != 0)
```
Comment (jkotas) [inline src/coreclr/src/vm/method.cpp:4870]: How is this different from the existing `JitMinOpts` flag (below)? Can you just use the existing `JitMinOpts` to do what you need?

File: src/coreclr/src/inc/clrconfigvalues.h [hunk 13]
```diff
@@ -395,6 +395,9 @@ RETAIL_CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterIL, W("TraceInterpreterIL"), 0
 RETAIL_CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterOstack, W("TraceInterpreterOstack"), 0, "Logs operand stack after each IL instruction of interpreted methods to the console")
 CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterVerbose, W("TraceInterpreterVerbose"), 0, "Logs interpreter progress with detailed messages to the console")
 CONFIG_DWORD_INFO(INTERNAL_TraceInterpreterJITTransition, W("TraceInterpreterJITTransition"), 0, "Logs when the interpreter determines a method should be JITted")
+RETAIL_CONFIG_DWORD_INFO(INTERNAL_EnableJitOptimization, W("EnableJitOptimization"), 0, "If non-zero, enable JIT optimization (in Debug/Checked)") // this has no effect in Release
```
Comment (jkotas) [inline src/coreclr/src/inc/clrconfigvalues.h:398]: This super confusing. I am not able figure out what this is supposed to do by looking at the code.

Comment (jkotas) [reply src/coreclr/src/inc/clrconfigvalues.h:398]: Should this be rather called `ForceJitOptimization`?

File: src/coreclr/src/vm/interpreter.h (hunk 11 above)
Comment (yuchong-pan) [reply src/coreclr/src/vm/interpreter.h]: Done in commit https://github.com/dotnet/runtime/pull/37825/commits/74d235a0db1d38ba6ca1345dba11b76be519798a.

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 13 above)
Comment (yuchong-pan) [reply src/coreclr/src/inc/clrconfigvalues.h:398]: Hi @jkotas! Indeed I am a bit confused here. By looking at the code here https://github.com/dotnet/runtime/blob/6d3a9779737f27c33effd5e46c7e2d819b3d7e56/src/coreclr/src/vm/method.cpp#L4868
What name and description do you think is appropriate for this variable?

I initially named this variable as `ForJitOptimization`, but @noahfalk mentioned [here](https://github.com/dotnet/runtime/pull/37825#discussion_r439725270) that it should be instead named to be `AllowJitOptimizationForDebugCode`. By looking at the code, the variable is used in the function `IsJitOptimizationDisabled`. Therefore upon some reflection I am feeling that returning `false` in this function means that we enable JIT optimization. What do you think?

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 8 above)
Comment (yuchong-pan) [reply src/coreclr/src/inc/clrconfigvalues.h]: Hi @josalem! I think the description is actually confusing here. What I mean by "(for Debug/Checked)" is that this variable is only effective for Debug/Checked, but it does not have an effect for Release (I'm referring to the C# application). The runtime's configuration does not have impact on this. This variable itself does not check the configuration of the application; I'm just talking about the effects it has.

However I agree that this is not a good name nor a good description. Do you have some recommendation for this?

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 13 above)
Comment (jkotas) [reply src/coreclr/src/inc/clrconfigvalues.h:398]: Here is how the desired optimization level of a method is determined by default:
- If the binary is compiled as Debug, the optimizations are on
- If the binary is compiled as Release (or Checked), the optimizations are on.

This per binary default can be further over-riden by debugger or by per method `[MethodImpl(MethodImplOptions.NoOptimization)]` attribute.

If I am reading the code correctly, the switch as you have it implemented says ignore all this and set the desired optimization level to be optimizations on, not matter what other parts of the system say.

It means that turning in on may even produce incorrect behavior in certain situations. Respecting `NoOptimization` is often required for functional correctness. I expect that you may see some test failures if you turn this on in its current form.

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 8 above)
Comment (jkotas) [reply src/coreclr/src/inc/clrconfigvalues.h]: > Debug/Checked

Checked means optimizations on + assertions on. Checked is like Release as far as managed optimizations are concerned: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/System.Private.CoreLib.csproj#L87 . 

Checked is special flavor for used for CoreCLR itself only. Libraries or applications are just Debug/Release.

**Comment by yuchong-pan** [comment]
Given discussions with @noahfalk, @BruceForstall and @jkotas, I think that removing the `COMPlus` variable that triggers the interpreter as Tier 0 only (i.e. `EnableJitOptimization`) is probably a good solution since there exhibit many complications and confusions by introducing this variable. Also, @noahfalk mentioned [here](https://github.com/dotnet/runtime/pull/37825#discussion_r441236113) that the two major use scenarios of the interpreter do not require this variable. Any thoughts on this?

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 8 above)
Comment (noahfalk) [reply src/coreclr/src/inc/clrconfigvalues.h]: > Do you think that these two are good scenarios to consider?
1. To mimic the behavior of the Runtime in Release so we can also test the correctness of promotion from Tier 0 to Tier 1.

Did you mean mimic the behavior of a _managed assembly_ in Release? Our CI builds already compile the runtime in Release. I think the most straightforward way right now to test that tier0->tier1 promotion occurs is to use a managed assembly that was compiled in Release configuration. 

> 2. In the future when CI is set up for the interpreter, to check the assertions in CI for the interpreter in the Checked configuration.

If you are refering to assertions in the runtime source code that solely depends on whether the runtime has been compiled in Checked configuration. The config var would be unneeded there. If you are refering to Debug.Assert() calls in the C# source code of test apps then the "UseInterpretterAlways" config appears to handle that case already.

If these suggestions work then it appears there would be no need for the config switch that modifies JitOptimization policies, and then no need to worry about what to name it ; )

File: src/coreclr/src/inc/clrconfigvalues.h (hunk 13 above)
Comment (noahfalk) [reply src/coreclr/src/inc/clrconfigvalues.h:398]: fyi I commented on another thread of discussion - I'm still not sure this config switch is needed at all. If it isn't needed then it will shortcut discussions about getting the policy and naming clear : ) If it is needed then hopefully a better understanding of the requirements will make it easier to get the right policy and right name.

**Comment by yuchong-pan** [comment]
Having discussed this with @noahfalk and @jkotas, I removed the `EnableJitOptimization` environment variable in commit https://github.com/dotnet/runtime/pull/37825/commits/e9a94f1e9dd04d6382e8b663569de2ab823444e6.

**Review by noahfalk — APPROVED** [review]
Looks good to me! Happy interpretting : )

(Make sure to squash before merging)

**Comment by xiangzhai** [comment]
Hi,

But how to prove the Interpreter whether or not work?

```
./build-runtime.sh cmakeargs "-DFEATURE_INTERPRETER=1"

export CORE_LIBRARIES=/home/zhaixiang/project/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-preview.6.20305.6

# interpreter
export COMPlus_DumpInterpreterStubs=1
export COMPlus_Interpret=*
export COMPlus_InterpreterJITThreshold=20 # or 999999
export COMPlus_InterpreterPrintPostMortem=1
export COMPlus_InterpreterDoLoopMethods=1
export COMPlus_TraceInterpreterEntries=1
export COMPlus_TieredCompilation=1
export COMPlus_JITMinOpts=1
export COMPlus_ZapDisable=1

# jit
export COMPlus_JitFunctionTrace=1

/home/zhaixiang/project/runtime/artifacts/bin/coreclr/Linux.x64.Debug/corerun /home/zhaixiang/project/HelloWorld/bin/Debug/netcoreapp3.1/HelloWorld.dll
```

Please have a look at [debug.log](https://github.com/dotnet/runtime/files/4809280/debug.log)

Thanks,
Leslie Zhai

**Comment by yuchong-pan** [comment]
Hello @xiangzhai,

Thanks for asking! Could you please share me with the Hello World sample program that you use for testing?

Best,
Yuchong

**Comment by xiangzhai** [comment]
Hi @yuchong-pan 

Thanks for your response! I just `dotnet new console -o HelloWorld` and then `dotnet run`, I didn't modify the `Program.cs`.

Thanks,
Leslie Zhai

**Comment by yuchong-pan** [comment]
Hi @xiangzhai,

Thanks for sharing me with this information! To see that the interpreter is actually used, one of the approaches would be to look at the information printed by `InterpreterPrintPostMortem` (specifically, the total number of calls from interpreted code).

I also tested this PR on your Hello World sample program, and it seems that the program is not interpreted because you set `COMPlus_JITMinOpts=1`. With `JITMinOpts`, Tiered Compilation is not eligible (see [here](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/method.cpp#L4847) and [here](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/method.cpp#L4847)). Since the interpreter is dependent upon Tiered Compilation, the interpreter is hence disabled as well.

With `COMPlus_JITMinOpts=0`, the interpreter is triggered for Hello World on my local (Windows) machine. I believe that it would be the same for other platforms.

Please let me know if you have further questions!

Best,
Yuchong

**Comment by BruceForstall** [comment]
It's a little unfortunate that setting JITMinOpts disables the interpreter. What if you wanted to use the interpreter to bring up a new platform, where the JIT compiler is very immature? In that case, you might want to force JITMinOpts so the JIT does not invoke any optimization phases, but you would also want the interpreter as the "phase 0" of tiering. Maybe we need to rethink this MinOpts disabling tiering, in the presence of the interpreter.

**Comment by yuchong-pan** [comment]
Hi @BruceForstall! I think the point you make is a very good scenario to think of. However, if we force `JITMinOpts`, we can also set the newly added `ForceInterpreter` to use the interpreter even in the case where Tiered Compilation is ineligible.

**Comment by xiangzhai** [comment]
> With `COMPlus_JITMinOpts=0`, the interpreter is triggered for Hello World on my local (Windows) machine. I believe that it would be the same for other platforms.

```
./build-runtime.sh cmakeargs "-DFEATURE_INTERPRETER=1"

export CORE_LIBRARIES=/home/zhaixiang/project/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-preview.6.20305.6

# interpreter
export COMPlus_DumpInterpreterStubs=1
export COMPlus_Interpret=*
export COMPlus_InterpreterJITThreshold=20
export COMPlus_InterpreterPrintPostMortem=1
export COMPlus_InterpreterDoLoopMethods=1
export COMPlus_TraceInterpreterEntries=1
export COMPlus_TieredCompilation=1
export COMPlus_JITMinOpts=0
export COMPlus_ZapDisable=1

# jit
export COMPlus_JitFunctionTrace=1

gdb -ex=r --args /home/zhaixiang/project/runtime/artifacts/bin/coreclr/Linux.x64.Debug/corerun /home/zhaixiang/project/HelloWorld/bin/Debug/netcoreapp3.1/HelloWorld.dll
```

It seems repro https://github.com/dotnet/runtime/issues/13759

```
{ Start Jitting Method  191 HelloWorld.Program:Main(System.String[]) (MethodHash=ab41dfb7) MinOpts
} Jitted Method  191 at 00007fff`7dd2aa60 method HelloWorld.Program:Main(System.String[]) size 0000003d
Generating interpretation stub (# 1 = 0x1, hash = 0xd758ab36) for System.Console:WriteLine.
[New Thread 0x7ffff41a5700 (LWP 2215)]
Generating interpretation stub (# 2 = 0x2, hash = 0xcd1b9c62) for System.Console:.cctor.
Entering method #1 (= 0x1): System.Console:.cctor().
 arguments:

Entering method #2 (= 0x2): System.Console:WriteLine(class).
 arguments:

Thread 1 "corerun" received signal SIGSEGV, Segmentation fault.
Object::GetMethodTable (this=0x6820f827d6bc0200) at /home/zhaixiang/project/runtime/src/coreclr/src/vm/object.h:175
175             _ASSERTE((dac_cast<TADDR>(m_pMethTab) & MARKED_BIT) == 0);

(gdb) bt
#0  Object::GetMethodTable (this=0x6820f827d6bc0200) at /home/zhaixiang/project/runtime/src/coreclr/src/vm/object.h:175
#1  0x00007ffff6cfb5e8 in Interpreter::PrintValue (this=0x7fffffffaf20, it=..., valAddr=0x7fffffffc740 "")
    at /home/zhaixiang/project/runtime/src/coreclr/src/vm/interpreter.cpp:11823
#2  0x00007ffff6cfba1b in Interpreter::PrintArgValue (this=0x7fffffffaf20, argNum=0)
    at /home/zhaixiang/project/runtime/src/coreclr/src/vm/interpreter.cpp:11753
#3  0x00007ffff6ce4e62 in Interpreter::PrintArgs (this=0x7fffffffaf20)
    at /home/zhaixiang/project/runtime/src/coreclr/src/vm/interpreter.cpp:11742
#4  0x00007ffff6ce003d in Interpreter::ExecuteMethod (this=0x7fffffffaf20, retVal=0x7fffffffaf08, pDoJmpCall=0x7fffffffc49f, 
    pJmpCallToken=0x7fffffffaf04) at /home/zhaixiang/project/runtime/src/coreclr/src/vm/interpreter.cpp:1928
#5  0x00007ffff6cdf8fc in Interpreter::ExecuteMethodWrapper (interpMethInfo=0x5555556a09b0, directCall=false, 
    ilArgs=0x7fffffffc740 "", stubContext=0x1dffffcc50, pDoJmpCall=0x7fffffffc49f, pResolvedToken=0x7fffffffc448)
    at /home/zhaixiang/project/runtime/src/coreclr/src/vm/interpreter.cpp:1556
#6  0x00007ffff6cfe032 in Interpreter::InterpretMethodBody (interpMethInfo=0x5555556a09b0, directCall=false, 
    ilArgs=0x7fffffffc740 "", stubContext=0x1dffffcc50) at /home/zhaixiang/project/runtime/src/coreclr/src/vm/interpreter.cpp:1591
#7  0x00007ffff6cdf197 in InterpretMethod (interpMethInfo=0x5555556a09b0, ilArgs=0x7fffffffc740 "", stubContext=0x1dffffcc50)
    at /home/zhaixiang/project/runtime/src/coreclr/src/vm/interpreter.cpp:1726
#8  0x00007fff7cdbd0c9 in ?? ()
#9  0x00007fffffffdb00 in ?? ()
#10 0x0000000000000000 in ?? ()
(gdb) x/22i 0x00007fff7cdbd0c9-44
   0x7fff7cdbd09d:      push   %rsp
   0x7fff7cdbd09e:      push   %rbp
   0x7fff7cdbd09f:      rex.X
   0x7fff7cdbd0a0:      mov    %rcx,0x8(%rsp)
   0x7fff7cdbd0a5:      lea    0x8(%rsp),%rsi
   0x7fff7cdbd0aa:      sub    $0x28,%rsp
   0x7fff7cdbd0ae:      xor    %edi,%edi
   0x7fff7cdbd0b0:      mov    %rdi,%r8
   0x7fff7cdbd0b3:      movabs $0x5555556a09b0,%rdi
   0x7fff7cdbd0bd:      movabs $0x7ffff6cdf040,%rax
=> 0x7fff7cdbd0c7:      callq  *%rax
   0x7fff7cdbd0c9:      nop
   0x7fff7cdbd0ca:      add    $0x28,%rsp
   0x7fff7cdbd0ce:      retq   
   0x7fff7cdbd0cf:      add    %cl,0x0(%rax)
   0x7fff7cdbd0d2:      add    %al,(%rax)
   0x7fff7cdbd0d4:      add    %al,(%rax)
   0x7fff7cdbd0d6:      add    %al,(%rax)
   0x7fff7cdbd0d8:      add    %eax,(%rax)
   0x7fff7cdbd0da:      add    %al,(%rax)
   0x7fff7cdbd0dc:      add    %al,(%rax)
   0x7fff7cdbd0de:      add    %al,(%rax)
```

**Comment by xiangzhai** [comment]
> What if you wanted to use the interpreter to bring up a new platform, where the JIT compiler is very immature?

It is just able to work for MIPS64  https://github.com/dotnet/runtime/issues/4234#issuecomment-638254024 by disabled optimization:

```
# CoreFX && AspNetCore ALLIN1
export CORE_LIBRARIES=/home/loongson/corefx-3.1-Linux.mips64.Debug
# Optimization Disabled
export COMPlus_JITMinOpts=1

./bin/Product/Linux.mips64.Release/corerun /home/loongson/aspnet-samples/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Server/bin/Debug/netcoreapp3.1/FlightFinder.Server.dll --urls http://10.2.5.91:5000
```

Yes, we [are still fixing bugs](https://github.com/gsvm/coreclr/commits/mips64-port) to make it mature.

> In that case, you might want to force JITMinOpts so the JIT does not invoke any optimization phases

There are some hardcode disabled some optimization for MIPS64:

* https://github.com/gsvm/coreclr/blob/mips64-port/src/jit/compiler.hpp#L3953

```
#if defined(_TARGET_AMD64_) || defined(_TARGET_ARM64_)// || defined(_TARGET_MIPS64_)
// should confirm how optimize on mips64.

    // The struct parameter is a register candidate
    return PROMOTION_TYPE_INDEPENDENT;
#else
    // The struct parameter is not enregistered
    return PROMOTION_TYPE_DEPENDENT;
#endif
```

* https://github.com/gsvm/coreclr/blob/mips64-port/src/jit/lower.cpp#L2565

```
GenTree* Lowering::OptimizeConstCompare(GenTree* cmp)
{
    assert(cmp->gtGetOp2()->IsIntegralConst());

#if defined(_TARGET_XARCH_) || defined(_TARGET_ARM64_)// || defined(_TARGET_MIPS64_)
// should confirm how optimize on mips64.
```

We are implementing it for MIPS64.

Thanks,
Leslie Zhai
