### PR TITLE
Dependency Injection support for ValueTypes as Services

### LINKED ISSUE #42160: DependencyInjection doesn't support value type services
### Description

We have this test, which is currently disabled and fails when enabled:

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs#L211-L225

We should enable this test and fix the product to make it pass.

### LINKED ISSUE #59624: Dependency Injection using ILEmit is generating additional MSIL nop operations in the DynamicMethod
### Description

When inspecting MSIL code generated by Dependency Injection dynamic compilation using ILEmit, everytime there is a `ldloca.s` instruction, 3 `nop` operations are also generated.

### Configuration

* Which version of .NET is the code running on? .NET Framework 4.62
* What OS and version, and what distro if applicable? Windows 11 (22000.194)
* What is the architecture (x64, x86, ARM, ARM64)? x64

### Other information

To reproduce the issue, compile `Microsoft.Extensions.DependencyInjection` using `SAVE_ASSEMBLIES` symbol. Then run `ServiceProviderILEmitContainerTests.ScopedServiceCanBeResolved` and inspect MSIL code in `artifacts\bin\Microsoft.Extensions.DependencyInjection.Tests\net462-*\Test*.dll`

```assembly
  [...]
  IL_0047: ldloc.2      // sync
  IL_0048: ldloca.s     lockTaken
  IL_004a: nop
  IL_004b: nop
  IL_004c: nop
  IL_004d: call         void [mscorlib]System.Threading.Monitor::Enter(object, bool&)

  IL_0052: ldloc.1      // resolvedServices
  IL_0053: ldloc.0      // key
  IL_0054: ldloca.s     service
  IL_0056: nop
  IL_0057: nop
  IL_0058: nop
  IL_0059: callvirt     instance bool class [mscorlib]System.Collections.Generic.IDictionary`2<valuetype [Microsoft.Extensions.DependencyInjection]Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey, object>::TryGetValue(!0/*valuetype [Microsoft.Extensions.DependencyInjection]Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey*/, !1/*object*/&)
  IL_005e: brtrue       IL_007c
  [...]
```

### PR DESCRIPTION
**Pull request by allantargino**
The only thing that was missing to support ValueTypes as Services was box the result when visiting constructors call sites.

I am also fixing several tests that were building the ServiceProvider using the default ServiceProviderEngine, instead of relying on each specific engine abstract creation method.

fix #42160

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 1]
```diff
@@ -354,7 +367,7 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
                 // Load syncLocal
                 Ldloc(context.Generator, syncLocal.LocalIndex);
                 // Load address of lockTaken
-                context.Generator.Emit(OpCodes.Ldloca_S, lockTakenLocal.LocalIndex);
+                Ldloca(context.Generator, lockTakenLocal.LocalIndex);
```
Comment (teo-tsirpanis) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:370]:
```suggestion
                context.Generator.Emit(OpCodes.Ldloca, lockTakenLocal);
```

[`ILGenerator.Emit(OpCode, LocalInfo)`](https://github.com/dotnet/runtime/blob/1546679145d22b07eb7825eb3e16e4c61bac1994/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/ILGenerator.cs#L821) already does the optimizations we do ([even on .NET Framework](https://referencesource.microsoft.com/#mscorlib/system/reflection/emit/ilgenerator.cs,861)).

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 2]
```diff
@@ -363,7 +376,7 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
                 // Load cache key
                 Ldloc(context.Generator, cacheKeyLocal.LocalIndex);
                 // Load address of result local
-                context.Generator.Emit(OpCodes.Ldloca_S, resultLocal.LocalIndex);
+                Ldloca(context.Generator, resultLocal.LocalIndex);
```
Comment (teo-tsirpanis) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:379]:
```suggestion
                context.Generator.Emit(OpCodes.Ldloca, resultLocal);
```

Same as before.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 3]
```diff
@@ -96,21 +96,22 @@ private GeneratedMethod BuildTypeNoCache(ServiceCallSite callSite)
             ILGenerator ilGenerator = dynamicMethod.GetILGenerator(512);
             ILEmitResolverBuilderRuntimeContext runtimeContext = GenerateMethodBody(callSite, ilGenerator);
 
-#if SAVE_ASSEMBLIES
+#if SAVE_ASSEMBLIES && NETFRAMEWORK
```
Comment (teo-tsirpanis) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:99]:
```suggestion
#if SAVE_ASSEMBLIES
```

The library's `.csproj` file already allows defining `SAVE_ASSEMBLIES` only on .NET Framework.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 4]
```diff
@@ -485,5 +497,17 @@ private void Stloc(ILGenerator generator, int index)
 
             generator.Emit(OpCodes.Stloc, index);
         }
+
```
Comment (teo-tsirpanis) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:500]: With my suggestions above, this function is not needed. It would be great if you accordingly remove the need for the `Ldloc` and `Stloc` helper methods above.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 5]
```diff
@@ -165,7 +171,7 @@ protected override object VisitScopeCache(ServiceCallSite scopedCallSite, ILEmit
             GeneratedMethod generatedMethod = BuildType(scopedCallSite);
 
             // Type builder doesn't support invoking dynamic methods, replace them with delegate.Invoke calls
-#if SAVE_ASSEMBLIES
+#if SAVE_ASSEMBLIES && NETFRAMEWORK
```
Comment (teo-tsirpanis) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:174]:
```suggestion
#if SAVE_ASSEMBLIES
```

Same as before.

**Review by teo-tsirpanis — CHANGES_REQUESTED** [review]
I have some suggestions, seems good otherwise.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs (hunk 1 above)
Comment (allantargino) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:370]: Nice catch!

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 6]
```diff
@@ -96,12 +96,12 @@ private GeneratedMethod BuildTypeNoCache(ServiceCallSite callSite)
             ILGenerator ilGenerator = dynamicMethod.GetILGenerator(512);
             ILEmitResolverBuilderRuntimeContext runtimeContext = GenerateMethodBody(callSite, ilGenerator);
 
-#if SAVE_ASSEMBLIES
+#if SAVE_ASSEMBLIES && NETFRAMEWORK
             var assemblyName = "Test" + DateTime.Now.Ticks;
+            var fileName = assemblyName + ".dll";
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:101]: Can you revert these unrelated changes? In general it is best to keep your proposed changes to a single concern. These kinds of changes are distracting from the main intent of the PR.

Comment (allantargino) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:101]: Sure thing 👍 
Should I also split this PR into two? One for each issue fix?

Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs]: Honestly, yes, it might be better to split them into 2 PRs. (3 if you count the SAVE_ASSEMBLIES clean up you were doing here.)

We've had a few regressions in this kinds of changes where we've had to investigate issues. It is easier to narrow down which change caused the problem when unrelated changes are merged separately.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 7]
```diff
@@ -808,9 +808,61 @@ public void WorksWithStructServices(ServiceLifetime lifetime)
 
             var provider = CreateServiceProvider(serviceCollection);
             var service = provider.GetService<IFakeMultipleService>();
+
+            Assert.NotNull(service);
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:812]: Maybe also assert it is the correct type.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs [hunk 8]
```diff
@@ -821,8 +873,11 @@ public void WorksWithWideScopedTrees()
                 serviceCollection.AddScoped<IFakeMultipleService, FakeMultipleServiceWithIEnumerableDependency>();
                 serviceCollection.AddScoped<IFakeService, FakeService>();
             }
+            var serviceProvider = CreateServiceProvider(serviceCollection);
 
-            var service = CreateServiceProvider(serviceCollection).GetService<IEnumerable<IFakeOuterService>>();
+            var service = serviceProvider.GetService<IEnumerable<IFakeOuterService>>();
+
+            Assert.NotEmpty(service);
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs:880]: Should we make this assert stronger and assert how many there are?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs (hunk 6 above)
Comment (allantargino) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs]: No problem, I definitely understand the problems it can cause. Sorry for it, I will separate the changes them. This PR will contain only fixes to #42160. I will try to keep next ones scoped to single a purpose :)

**Review by eerhardt — APPROVED** [review]
:shipit: Thanks for the great work here, @allantargino. And thanks for separating the changes. It makes it much easier to review.

**Comment by allantargino** [comment]
Thank you @eerhardt for the reviews and best practices recommendations, I am learning a ton 👍
