### PR TITLE
Fix JIT crash caused by GetType() == typeof(SealedClass) optimization

### LINKED ISSUE #33333: JIT crash caused by late GetType() optimizations
Repro:

Compile and JIT w/ optimizations

```
using System;
using System.Runtime.CompilerServices;

sealed class Program
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public object M()
    {
        return GetType2() == typeof(Program) ? base.ToString() : ToString();
    }

    Type GetType2() => GetType();

    static void Main(string[] args)
    {
        new Program().M();
    }
}
```

Result:

`Assert failure(PID 23416 [0x00005b78], Thread: 15036 [0x3abc]): Assertion failed 'OperIs(GT_NOP, GT_CALL, GT_COMMA) || OperIsCompare() || OperIsLong() || OperIsSIMD() || OperIsHWIntrinsic()' in 'Program:M():System.Object:this' during 'Lowering nodeinfo' (IL size 37)`

Release build hits AV later

More context: https://github.com/dotnet/corert/issues/6729#issuecomment-595956648

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/33333 (caused by https://github.com/dotnet/runtime/pull/32790) via patch by @AndyAyersMS 

Is it possible to put runtime handles into a GT_SWITCH (e.g. via raw IL)? And apply a similar fix [here](https://github.com/dotnet/runtime/blob/b41296a37f4bfead66db234e9d14b81fff302567/src/coreclr/src/jit/morph.cpp#L14967-L14984).

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Yes, it appears switch could have the same issue. Did you try exposing that via C#?

Changes LGTM, but perhaps someone else should approve.

@dotnet/jit-contrib PTAL

**Comment by EgorBo** [comment]
> Yes, it appears switch could have the same issue. Did you try exposing that via C#?
> 
> Changes LGTM, but perhaps someone else should approve.
> 
> @dotnet/jit-contrib PTAL

Well, C# doesn't allow it https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGADAAQY4B0AKgBawCGAJgJYB2A5gNyGEYDM5LKQDCpAN6FS00lJlzpC2QRnlBGFKQCyACgCUSyStUyAzgHcWAFzC0dAcRhXqATwAOMfQeMmJS39JgDKYwpFbuMBAAZjoieiD+AarAjADWPD4mAL5KOQRZQA but perhaps it's possible via IL? let me check

File: src/coreclr/src/jit/morph.cpp [hunk 1]
```diff
@@ -14767,10 +14769,18 @@ bool Compiler::fgFoldConditional(BasicBlock* block)
...
 
-            /* remove the statement from bbTreelist - No need to update
-             * the reference counts since there are no lcl vars */
-            fgRemoveStmt(block, lastStmt);
-
+            if (condTree != cond)
+            {
+                // Preserve the potentially side effecting part of the comma
+                assert(condTree->OperIs(GT_COMMA));
+                lastStmt->SetRootNode(condTree->AsOp()->gtOp1);
```
Comment (erozenfeld) [inline src/coreclr/src/jit/morph.cpp]: Can condTree->AsOp()->gtOp2 be a GT_COMMA tree too?

**Review by briansull — APPROVED** [review]
[Edit]

File: src/coreclr/src/jit/morph.cpp (hunk 1 above)
Comment (briansull) [reply src/coreclr/src/jit/morph.cpp]: Yes, You could have multiple GT_COMMA nodes and need to collect all of the side effects not just the first one.

**Review by briansull — CHANGES_REQUESTED** [review]
You will need to collect all of the side effects.

File: src/coreclr/src/jit/morph.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/src/jit/morph.cpp]: The tree is a JTRUE, so there is no op2.

Comment (AndyAyersMS) [reply src/coreclr/src/jit/morph.cpp]: So, we should set the root node to `condTree`, not `condTree->op1`.

Comment (erozenfeld) [reply src/coreclr/src/jit/morph.cpp]: `condTree` is a `GT_COMMA` so it has op1 and op2.

Comment (AndyAyersMS) [reply src/coreclr/src/jit/morph.cpp]: Yeah I wasn't clear, I meant the root tree is JTRUE, so we can just replace it with the COMMA.

Comment (erozenfeld) [reply src/coreclr/src/jit/morph.cpp]: I still don't understand. If `condTree` is `COMMA(x, COMMA(y, z))` won't we lose the size effects from `y`?

Comment (AndyAyersMS) [reply src/coreclr/src/jit/morph.cpp]: We'd turn `JTRUE(COMMA(x, COMMA(y, 1)))` into `COMMA(x, COMMA(y, 1))`

**Comment by briansull** [comment]
This also fixes #33091

**Comment by briansull** [comment]
Change Compiler::fgFoldConditional

```
+                fgRemoveStmt(block, lastStmt);
+                assert(condTree->OperIs(GT_COMMA));
+                // Preserve the potentially side effecting part of the comma
+                GenTree* sideEffList = optExtractSideEffListFromConst(condTree);
+                lastStmt->SetRootNode(sideEffList);

```

Modify Compiler::optExtractSideEffListFromConst

```
GenTree* Compiler::optExtractSideEffListFromConst(GenTree* tree)
-    assert(vnStore->IsVNConstant(vnStore->VNConservativeNormalValue(tree->gtVNPair)));
+    // vnStore is null before the ValueNumber phase has run
+    if (vnStore != nullptr)
+    {
+        assert(vnStore->IsVNConstant(vnStore->VNConservativeNormalValue(tree->gtVNPair)));
+    }
+    else
+    {
+        assert(tree->gtEffectiveVal(true)->OperKind() & GTK_CONST);
+    }
```

**Comment by briansull** [comment]
@erozenfeld  You might also want to look into Compiler::optVNConstantPropOnJTrue

File: src/coreclr/src/jit/morph.cpp (hunk 1 above)
Comment (AndyAyersMS) [inline src/coreclr/src/jit/morph.cpp]:
```suggestion
                // Preserve any side effects
                assert(condTree->OperIs(GT_COMMA));
                lastStmt->SetRootNode(condTree);
```

File: src/coreclr/src/jit/morph.cpp [hunk 2]
```diff
@@ -14767,10 +14769,18 @@ bool Compiler::fgFoldConditional(BasicBlock* block)
...
+            }
+            else
+            {
+                // remove the statement from bbTreelist - No need to update
+                // the reference counts since there are no lcl vars
```
Comment (AndyAyersMS) [inline src/coreclr/src/jit/morph.cpp]:
```suggestion
                // no side effects, remove the jump entirely
```

File: src/coreclr/src/jit/morph.cpp [hunk 3]
```diff
@@ -14979,9 +14991,18 @@ bool Compiler::fgFoldConditional(BasicBlock* block)
...
             noway_assert(cond->gtOper == GT_CNS_INT);
 
-            /* remove the statement from bbTreelist - No need to update
-             * the reference counts since there are no lcl vars */
-            fgRemoveStmt(block, lastStmt);
+            if (condTree != cond)
+            {
+                // Preserve the potentially side effecting part of the comma
+                assert(condTree->OperIs(GT_COMMA));
+                lastStmt->SetRootNode(condTree->AsOp()->gtOp1);
```
Comment (AndyAyersMS) [inline src/coreclr/src/jit/morph.cpp]:
```suggestion
                // Preserve any side effects
                assert(condTree->OperIs(GT_COMMA));
                lastStmt->SetRootNode(condTree);
```

File: src/coreclr/src/jit/morph.cpp [hunk 4]
```diff
@@ -14979,9 +14991,18 @@ bool Compiler::fgFoldConditional(BasicBlock* block)
...
+            }
+            else
+            {
+                // remove the statement from bbTreelist - No need to update
+                // the reference counts since there are no lcl vars
```
Comment (AndyAyersMS) [inline src/coreclr/src/jit/morph.cpp]:
```suggestion
                // no side effects, remove the switch entirely
```

**Comment by EgorBo** [comment]
@AndyAyersMS should I also add changes for `optExtractSideEffListFromConst` ?

**Comment by AndyAyersMS** [comment]
Brian's suggestion was made so you could call `optExtractSideEffListFromConst` from `fgFoldConditional`, so I don't think you need to do this.

File: src/coreclr/src/jit/morph.cpp (hunk 1 above)
Comment (erozenfeld) [reply src/coreclr/src/jit/morph.cpp]: @AndyAyersMS Sorry, I was confused yesterday because I saw this message

>> The tree is a JTRUE, so there is no op2.

but didn't notice this one

>> So, we should set the root node to condTree, not condTree->op1.

Your suggestion makes sense.

**Comment by briansull** [comment]
I think that we can go with @AndyAyersMS  suggested fix.
It is possible that we may see unnecessary codegen to load the constant into a register.
If we do we can check for the common case of a single GT_COMMA node and when we have that case use  your original fix.  A nested set of commas with multiple side effect are extremely rare.

**Review by briansull — APPROVED** [review]

**Review by briansull — APPROVED** [review]
Looks Good now

**Comment by AndyAyersMS** [comment]
OSX build failures are known issues (#33471), so am going to ignore.
