### PR TITLE
Fix value number of a partial definition via IND.

### LINKED ISSUE #52320: Incorrect/incomplete value numbering of partial stores of constants
Reproduction:
```cs
private static bool UseAsgOpt(int a)
{
    Unsafe.InitBlock(ref Unsafe.As<int, byte>(ref a), 0, 2);

    return a == 1 << 20;
}
```
Tree in question in VN:
```scala
***** BB01, STMT00000(before)
N005 (  9,  8) [000005] -A------R---              *  ASG       short
N004 (  7,  6) [000004] n------N----              +--*  IND       short
N003 (  3,  3) [000001] ------------              |  \--*  ADDR      byref
N002 (  3,  2) [000000] U------N----              |     \--*  LCL_VAR   int    V00 arg0         ud:1->2
N001 (  1,  1) [000002] ------------              \--*  CNS_INT   int    0

N001 [000002]   CNS_INT   0 => $40 {IntCns 0}
N002 [000000]   LCL_VAR   V00 arg0         ud:1->2 => $80 {InitVal($40)}
N003 [000001]   ADDR      => $100 {PtrToLoc($40, $0)}
    VNForCastOper(short) is $42
Tree [000005] assigned VN to local var V00/2: VN $40 {IntCns 0}
N005 [000005]   ASG       => $VN.Void

***** BB01, STMT00000(after)
N005 (  9,  8) [000005] -A------R---              *  ASG       short  $VN.Void
N004 (  7,  6) [000004] n------N----              +--*  IND       short  $40
N003 (  3,  3) [000001] ------------              |  \--*  ADDR      byref  $100
N002 (  3,  2) [000000] U------N----              |     \--*  LCL_VAR   int    V00 arg0         ud:1->2 $80
N001 (  1,  1) [000002] ------------              \--*  CNS_INT   int    0 $40
```
We end up assigning `$40` to `V00` despite the partial store of a constant. This eventually leads to incorrect codegen:
```asm
xor eax, eax
ret
```
(`UseAsgOpt(1 << 20)` will return `false` while it should return `true`)

This happens because `VNApplySelectorsAssignTypeCoerce` [doesn't do anything](https://github.com/dotnet/runtime/blob/d058930b2bf416635710b8b4022839a1ee1b8e6e/src/coreclr/jit/valuenum.cpp#L3652) for constant RHSs.

Naively blocking this with `elem = VNMakeNormalUnique(elem);` for the `isConstant` branch results in 6 regressions across the framework and a fairly huge diff in tests (`3391 total methods with Code Size differences (450 improved, 2941 regressed)`).

### PR DESCRIPTION
**Pull request by sandreenko**
The actual fix is 1de13e5. It is a simple fix without any new checks.

Fixes #52320.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib , @SingleAccretion . This is a simple fix for https://github.com/dotnet/runtime/issues/52320, the idea was to catch the first place that knows that we are doing a partial store and don't have field seq.

File: src/coreclr/jit/valuenum.cpp [hunk 1]
```diff
@@ -3816,14 +3832,18 @@ ValueNum ValueNumStore::VNApplySelectorsAssignTypeCoerce(ValueNum elem, var_type
                 // We are trying to write an 'elem' of type 'elemType' using 'indType' store
 
                 // insert a cast of elem to 'indType'
-                elem = VNForCast(elem, indType, elemTyp);
+                dstVN = VNForCast(srcVN, dstIndType, srcType);
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:3835]: Maybe assert we only have integral types here? I always wondered if it is possible to construct a case where VN will insert a cast, say `float -> double` (or `float` -> `int`, etc), on mismatched assignment, where it was actually meant to be a `BITCAST`. Looks like like morph is careful enough to not allow that to happen, but then maybe I am just not imaginative enough.

File: src/coreclr/jit/valuenum.cpp [hunk 2]
```diff
@@ -7888,11 +7916,19 @@ void Compiler::fgValueNumberTree(GenTree* tree)
...
                                     {
+                                        assert(!isEntire);
                                         // We don't know where we're storing, so give the local a new, unique VN.
                                         // Do this by considering it an "entire" assignment, with an unknown RHS.
                                         isEntire = true;
                                         rhsVNPair.SetBoth(vnStore->VNForExpr(compCurBB, lclVarTree->TypeGet()));
                                     }
+                                    else if ((fieldSeq == nullptr) && !isEntire)
+                                    {
+                                        // It is a particial store of a LCL_VAR without using LCL_FLD.
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:7927]:
```suggestion
                                        // It is a partial store of a LCL_VAR without using LCL_FLD.
```

Comment (sandreenko) [reply src/coreclr/jit/valuenum.cpp]: fixed, thanks

File: src/coreclr/jit/valuenum.cpp (hunk 1 above)
Comment (sandreenko) [reply src/coreclr/jit/valuenum.cpp:3835]: such assert won't stand nowadays, first because there are many cases where `dstIndType` is not integral, second because VN tries to handle GC heap and for it the type is always `TYP_REF`, so we could have `srcType = TYP_REF`, `dstIndType = TYP_DOUBLE`.

There are many cases where VN is potentially wrong and we uncover more of them by improving our optimizations but for now, the CQ benefits from it still outweigh potential undiscovered bugs from it.

Comment (SingleAccretion) [reply src/coreclr/jit/valuenum.cpp:3835]: I see, thank you for the explanation.

**Comment by sandreenko** [comment]
ping @dotnet/jit-contrib

File: src/coreclr/jit/valuenum.cpp [hunk 3]
```diff
@@ -3787,27 +3787,43 @@ ValueNum ValueNumStore::VNApplySelectorsTypeCheck(ValueNum elem, var_types indTy
     return elem;
 }
 
-ValueNum ValueNumStore::VNApplySelectorsAssignTypeCoerce(ValueNum elem, var_types indType, BasicBlock* block)
+//------------------------------------------------------------------------
+// VNApplySelectorsAssignTypeCoerce: Compute the value number corresponding to `srcVN`
+//    being writen using an indirection of 'dstIndType'.
```
Comment (AndyAyersMS) [inline src/coreclr/jit/valuenum.cpp:3792]:
```suggestion
//    being written using an indirection of 'dstIndType'.
```

File: src/coreclr/jit/valuenum.cpp [hunk 4]
```diff
@@ -3787,27 +3787,43 @@ ValueNum ValueNumStore::VNApplySelectorsTypeCheck(ValueNum elem, var_types indTy
...
+//
+// Arguments:
+//    srcVN - value number for the value being stored;
+//    dstIndType - type of the indirection storing the value to the memory;
+//    block - block where the assignment occurs/
```
Comment (AndyAyersMS) [inline src/coreclr/jit/valuenum.cpp:3797]:
```suggestion
//    block - block where the assignment occurs
```

**Review by AndyAyersMS — APPROVED** [review]
