### PR TITLE
Apply the TimeProvider design feedback

### LINKED ISSUE #36617: API to provide the current system time
**This proposal is edited by @tarekgh**

## Proposal

The aim of this proposal is to introduce time abstraction. This abstraction will include the ability to retrieve the system date and time, either in UTC or local time, as well as timestamps for use in performance or tagging scenarios. Additionally, this abstraction can be used in the Task operations like `WaitAsync` and `CancellationTokenSource CancelAfter`. 
By introducing this new abstraction, it will become possible to replace other existing abstractions that are currently being used in a nonuniform way across various interfaces such as ISystemClock and ITimer. The following are some examples of such interfaces:

- [src/Servers/Kestrel/Transport.Quic/src/Internal/ISystemClock.cs](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Servers/Kestrel/Transport.Quic/src/Internal/ISystemClock.cs#L9)
- [SignalR/common/Shared/ISystemClock.cs](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/SignalR/common/Shared/ISystemClock.cs#L6)
- [Middleware/OutputCaching/src/ISystemClock.cs](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Middleware/OutputCaching/src/ISystemClock.cs#L9)
- [Security/Authentication/Core/src/ISystemClock.cs](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Security/Authentication/Core/src/ISystemClock.cs#L9)
- [Middleware/ResponseCaching/src/Interfaces/ISystemClock.cs](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Middleware/ResponseCaching/src/Interfaces/ISystemClock.cs#L9)
- [Servers/Kestrel/Core/src/Internal/Infrastructure/ISystemClock.cs](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Servers/Kestrel/Core/src/Internal/Infrastructure/ISystemClock.cs#L9)
- [libraries/Microsoft.Extensions.Caching.Abstractions/src/Internal/ISystemClock.cs](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/Internal/ISystemClock.cs#L11)
- [ReverseProxy/Utilities/ITimer.cs](https://github.com/microsoft/reverse-proxy/blob/701781241c60eb796794dc24ecf110a5c222c2b6/src/ReverseProxy/Utilities/ITimer.cs#L8)

In addition, this new abstraction will enable the creation of tests that can mock time functionality, providing greater flexibility in testing through the ability to customize time operations. 

Below are some design notes to consider:

- The proposed abstraction should be compatible with both the .NET and .NET Framework for maximum flexibility.
- It should work on down-level supported versions of both .NET and .NET Core, as it will support netstandard2.0.
- For .NET 8.0, the abstraction will be implemented in the CoreLib.
- For downl-level, the abstraction will be implemented in Microsoft.Extensions.Primitives or any chosen other OOB library which supports ns2.0 and will type forward to core if the library used for .NET 8 or up.
- In .NET 8.0, will add WaitAsync methods to the Task class which work with the time abstraction. Additionally, will provide a new `CancellationTokenSource` constructor that works with abstraction. 
- In the down-level, we'll provide Task extension methods for WaitAsync operation and creating `CancellationTokenSource` support the abstraction. 

### APIs for .NET 8.0 and Down-levels

- Note, the introduced APIs in down-levels will be type forwarded when running on .NET 8.0 and up.

```C#
namespace System
{
    /// <summary>Provides an abstraction for time. </summary>
    public abstract class TimeProvider
    {
        /// <summary>Initializes the instance. </summary>
        protected TimeProvider();

        /// <summary>
        /// Gets a <see cref="TimeProvider"/> that provides a clock based on <see cref="DateTimeOffset.UtcNow"/>,
        /// a time zone based on <see cref="TimeZoneInfo.Local"/>, a high-performance time stamp based on <see cref="Stopwatch"/>,
        /// and a timer based on <see cref="Timer"/>.
        /// </summary>
        public static TimeProvider System { get; }

        /// <summary>
        /// Creates a <see cref="TimeProvider"/> that provides a clock based on <see cref="DateTimeOffset.UtcNow"/>,
        /// a time zone based on <paramref name="timeZone"/>, a high-performance time stamp based on <see cref="Stopwatch"/>,
        /// and a timer based on <see cref="Timer"/>.
        /// </summary>
        public static TimeProvider FromLocalTimeZone(TimeZoneInfo timeZone);

        /// <summary>
        /// Gets a <see cref="DateTimeOffset"/> value whose date and time are set to the current
        /// Coordinated Universal Time (UTC) date and time and whose offset is Zero,
        /// all according to this <see cref="TimeProvider"/>'s notion of time.
        /// </summary>
        public abstract DateTimeOffset UtcNow { get; }

        /// <summary>
        /// Gets a <see cref="DateTimeOffset"/> value that is set to the current date and time according to this <see cref="TimeProvider"/>'s
        /// notion of time based on <see cref="UtcNow"/>, with the offset set to the <see cref="LocalTimeZone"/>'s offset from Coordinated Universal Time (UTC).
        /// </summary>
        public DateTimeOffset LocalNow { get; }

        /// <summary>Gets a <see cref="TimeZoneInfo"/> object that represents the local time zone according to this <see cref="TimeProvider"/>'s notion of time. </summary>
        public abstract TimeZoneInfo LocalTimeZone { get; }

        /// <summary>Gets the current high-frequency value designed to measure small time intervals with high accuracy in the timer mechanism. </summary>
        /// <returns>A long integer representing the high-frequency counter value of the underlying timer mechanism. </returns>
        public abstract long GetTimestamp();

        /// <summary>Gets the frequency of <see cref="GetTimestamp"/> of high-frequency value per second. </summary>
        public abstract long TimestampFrequency { get; }

        /// <summary>Gets the elapsed time between two timestamps retrieved using <see cref="GetTimestamp"/>. </summary>
        /// <param name="startingTimestamp">The timestamp marking the beginning of the time period. </param>
        /// <param name="endingTimestamp">The timestamp marking the end of the time period. </param>
        /// <returns>A <see cref="TimeSpan"/> for the elapsed time between the starting and ending timestamps. </returns>
        public TimeSpan GetElapsedTime(long startingTimestamp, long endingTimestamp);

        /// <summary>Creates a new <see cref="ITimer"/> instance, using <see cref="TimeSpan"/> values to measure time intervals. </summary>
        /// <param name="callback">
        /// A delegate representing a method to be executed when the timer fires.  The method specified for callback should be reentrant,
        /// as it may be invoked simultaneously on two threads if the timer fires again before or while a previous callback is still being handled.
        /// </param>
        /// <param name="state">An object to be passed to the <paramref name="callback"/>. This may be null. </param>
        /// <param name="dueTime">The amount of time to delay before <paramref name="callback"/> is invoked. Specify <see cref="Timeout.InfiniteTimeSpan"/> to prevent the timer from starting. Specify <see cref="TimeSpan.Zero"/> to start the timer immediately. </param>
        /// <param name="period">The time interval between invocations of <paramref name="callback"/>. Specify <see cref="Timeout.InfiniteTimeSpan"/> to disable periodic signaling. </param>
        /// <returns>The newly created <see cref="ITimer"/> instance. </returns>
        /// <exception cref="ArgumentNullException"><paramref name="callback"/> is null. </exception>
        /// <exception cref="ArgumentOutOfRangeException">The number of milliseconds in the value of <paramref name="dueTime"/> or <paramref name="period"/> is negative and not equal to <see cref="Timeout.Infinite"/>, or is greater than <see cref="int.MaxValue"/>. </exception>
        /// <remarks>
        /// <para>
        /// The delegate specified by the callback parameter is invoked once after <paramref name="dueTime"/> elapses, and thereafter each time the <paramref name="period"/> time interval elapses.
        /// </para>
        /// <para>
        /// If <paramref name="dueTime"/> is zero, the callback is invoked immediately. If <paramref name="dueTime"/> is -1 milliseconds, <paramref name="callback"/> is not invoked; the timer is disabled,
        /// but can be re-enabled by calling the <see cref="ITimer.Change"/> method.
        /// </para>
        /// <para>
        /// If <paramref name="period"/> is 0 or -1 milliseconds and <paramref name="dueTime"/> is positive, <paramref name="callback"/> is invoked once; the periodic behavior of the timer is disabled,
        /// but can be re-enabled using the <see cref="ITimer.Change"/> method.
        /// </para>
        /// <para>
        /// The return <see cref="ITimer"/> instance will be implicitly rooted while the timer is still scheduled.
        /// </para>
        /// <para>
        /// <see cref="CreateTimer"/> captures the <see cref="ExecutionContext"/> and stores that with the <see cref="ITimer"/> for use in invoking <paramref name="callback"/>
        /// each time it's called.  That capture can be suppressed with <see cref="ExecutionContext.SuppressFlow"/>.
        /// </para>
        /// </remarks>
        public abstract ITimer CreateTimer(TimerCallback callback, object? state, TimeSpan dueTime, TimeSpan period);
    }
}
```

```C#
namespace System.Threading
{
    /// <summary>Represents a timer that can have its due time and period changed. </summary>
    /// <remarks>
    /// Implementations of <see cref="Change"/>, <see cref="IDisposable.Dispose"/>, and <see cref="IAsyncDisposable.DisposeAsync"/>
    /// must all be thread-safe such that the timer instance may be accessed concurrently from multiple threads.
    /// </remarks>
    public interface ITimer : IDisposable, IAsyncDisposable
    {
        /// <summary>Changes the start time and the interval between method invocations for a timer, using <see cref="TimeSpan"/> values to measure time intervals. </summary>
        /// <param name="dueTime">
        /// A <see cref="TimeSpan"/> representing the amount of time to delay before invoking the callback method specified when the <see cref="ITimer"/> was constructed.
        /// Specify <see cref="Timeout.InfiniteTimeSpan"/> to prevent the timer from restarting. Specify <see cref="TimeSpan.Zero"/> to restart the timer immediately.
        /// </param>
        /// <param name="period">
        /// The time interval between invocations of the callback method specified when the Timer was constructed.
        /// Specify <see cref="Timeout.InfiniteTimeSpan"/> to disable periodic signaling.
        /// </param>
        /// <returns><see langword="true"/> if the timer was successfully updated; otherwise, <see langword="false"/>. </returns>
        /// <exception cref="ObjectDisposedException">The timer has already been disposed. </exception>
        /// <exception cref="ArgumentOutOfRangeException">The <paramref name="dueTime"/> or <paramref name="period"/> parameter, in milliseconds, is less than -1 or greater than 4294967294. </exception>
        bool Change(TimeSpan dueTime, TimeSpan period);
    }
```

### APIs for .NET 8.0 Only 
```diff
namespace System.Threading
{
-   public sealed class Timer : MarshalByRefObject, IDisposable, IAsyncDisposable
+  public sealed class Timer : MarshalByRefObject, IDisposable, IAsyncDisposable, ITimer
    {
    }

    public class CancellationTokenSource : IDisposable
    {
+        /// <summary>Initializes a new instance of the <see cref="CancellationTokenSource"/> class that will be canceled after the specified <see cref="TimeSpan"/>. </summary>
+        /// <param name="delay">The time interval to wait before canceling this <see cref="CancellationTokenSource"/>. </param>
+        /// <param name="timeProvider">The <see cref="TimeProvider"/> with which to interpret the <paramref name="delay"/>. </param>
+        /// <exception cref="ArgumentOutOfRangeException"><paramref name="delay"/>'s <see cref="TimeSpan.TotalMilliseconds"/> is less than -1 or greater than <see cref="uint.MaxValue"/> - 1. </exception>
+        /// <exception cref="ArgumentNullException"><paramref name="timeProvider"/> is null. </exception>
+        /// <remarks>
+        /// The countdown for the delay starts during the call to the constructor.  When the delay expires,
+        /// the constructed <see cref="CancellationTokenSource"/> is canceled, if it has
+        /// not been canceled already. Subsequent calls to CancelAfter will reset the delay for the constructed
+        /// <see cref="CancellationTokenSource"/>, if it has not been canceled already.
+        /// </remarks>
+        public CancellationTokenSource(TimeSpan delay, TimeProvider timeProvider);
    }

    public sealed class PeriodicTimer : IDisposable
    {
+        /// <summary>Initializes the timer. </summary>
+        /// <param name="period">The time interval between returning the next enumerated value.</param>
+        /// <param name="timeProvider">The <see cref="TimeProvider"/> used to interpret <paramref name="period"/>. </param>
+        /// <exception cref="ArgumentOutOfRangeException"><paramref name="period"/> must be <see cref="Timeout.InfiniteTimeSpan"/> or represent a number of milliseconds equal to or larger than 1 and smaller than <see cref="uint.MaxValue"/>. </exception>
+        /// <exception cref="ArgumentNullException"><paramref name="timeProvider"/> is null</exception>
+        public PeriodicTimer(TimeSpan period, TimeProvider timeProvider);
    }
}

namespace System.Threading.Tasks
{
    public class Task<TResult> : Task
    {
+        /// <summary>Gets a <see cref="Task{TResult}"/> that will complete when this <see cref="Task{TResult}"/> completes or when the specified timeout expires. </summary>
+        /// <param name="timeout">The timeout after which the <see cref="Task"/> should be faulted with a <see cref="TimeoutException"/> if it hasn't otherwise completed. </param>
+        /// <param name="timeProvider">The <see cref="TimeProvider"/> with which to interpret <paramref name="timeout"/>. </param>
+        /// <returns>The <see cref="Task{TResult}"/> representing the asynchronous wait.  It may or may not be the same instance as the current instance. </returns>
+        public new Task<TResult> WaitAsync(TimeSpan timeout, TimeProvider timeProvider);

+        /// <summary>Gets a <see cref="Task{TResult}"/> that will complete when this <see cref="Task{TResult}"/> completes, when the specified timeout expires, or when the specified <see cref="CancellationToken"/> has cancellation requested. </summary>
+        /// <param name="timeout">The timeout after which the <see cref="Task"/> should be faulted with a <see cref="TimeoutException"/> if it hasn't otherwise completed. </param>
+        /// <param name="timeProvider">The <see cref="TimeProvider"/> with which to interpret <paramref name="timeout"/>. </param>
+        /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for a cancellation request. </param>
+        /// <returns>The <see cref="Task{TResult}"/> representing the asynchronous wait.  It may or may not be the same instance as the current instance. </returns>
+        public new Task<TResult> WaitAsync(TimeSpan timeout, TimeProvider timeProvider, CancellationToken cancellationToken);
    }

    public class Task : IAsyncResult, IDisposable
    {
+        /// <summary>Gets a <see cref="Task"/> that will complete when this <see cref="Task"/> completes or when the specified timeout expires. </summary>
+        /// <param name="timeout">The timeout after which the <see cref="Task"/> should be faulted with a <see cref="TimeoutException"/> if it hasn't otherwise completed. </param>
+        /// <param name="timeProvider">The <see cref="TimeProvider"/> with which to interpret <paramref name="timeout"/>. </param>
+        /// <returns>The <see cref="Task"/> representing the asynchronous wait.  It may or may not be the same instance as the current instance. </returns>
+        public Task WaitAsync(TimeSpan timeout, TimeProvider timeProvider);

+        /// <summary>Gets a <see cref="Task"/> that will complete when this <see cref="Task"/> completes, when the specified timeout expires, or when the specified <see cref="CancellationToken"/> has cancellation requested. </summary>
+        /// <param name="timeout">The timeout after which the <see cref="Task"/> should be faulted with a <see cref="TimeoutException"/> if it hasn't otherwise completed. </param>
+        /// <param name="timeProvider">The <see cref="TimeProvider"/> with which to interpret <paramref name="timeout"/>. </param>
+        /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for a cancellation request. </param>
+        /// <returns>The <see cref="Task"/> representing the asynchronous wait.  It may or may not be the same instance as the current instance. </returns>
+        public Task WaitAsync(TimeSpan timeout, TimeProvider timeProvider, CancellationToken cancellationToken);
    }
}
```

### APIs for down-level Only 
```C#
namespace System.Threading.Tasks
{
    public static class TimeProviderTaskExtensions
    {
        public static async Task<TResult> WaitAsync<TResult>(this Task<TResult> task, TimeSpan timeout, TimeProvider timeProvider);
        public static async Task<TResult> WaitAsync<TResult>(this Task<TResult> task, TimeSpan timeout, TimeProvider timeProvider, CancellationToken cancellationToken);
        public static async Task WaitAsync(this Task task, TimeSpan timeout, TimeProvider timeProvider);
        public static async Task WaitAsync(this Task task, TimeSpan timeout, TimeProvider timeProvider, CancellationToken cancellationToken);

    }
```

### Possible APIs addition for .NET 8.0 and down-level
```C#
namespace System.Threading.Tasks
{
    public static class TimeProviderTaskExtensions
    {

        /// <summary>Initializes a new instance of the <see cref="CancellationTokenSource"/> class that will be canceled after the specified <see cref="TimeSpan"/>. </summary>
        /// <param name="timeProvider">The <see cref="TimeProvider"/> with which to interpret the <paramref name="delay"/>. </param>
        /// <param name="delay">The time interval to wait before canceling this <see cref="CancellationTokenSource"/>. </param>
        /// <exception cref="ArgumentOutOfRangeException"><paramref name="delay"/>'s <see cref="TimeSpan.TotalMilliseconds"/> is less than -1 or greater than <see cref="uint.MaxValue"/> - 1. </exception>
        /// <remarks>
        /// The countdown for the delay starts during the call to the constructor.  When the delay expires,
        /// the constructed <see cref="CancellationTokenSource"/> is canceled, if it has
        /// not been canceled already. Subsequent calls to CancelAfter will reset the delay for the constructed
        /// <see cref="CancellationTokenSource"/>, if it has not been canceled already.
        /// </remarks>
        public static CancellationTokenSource CreateCancellationTokenSource(this TimeProvider timeProvider, TimeSpan delay) ;
    }
}
```

**End of the @tarekgh edit**
# The Original Proposal 

## Motivation 

The `ISystemClock` interface exists in:
* `Microsoft.AspNetCore.Authentication`
* `Microsoft.AspNetCore.ResponseCaching`
* `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure`
* `Microsoft.Extensions.Internal`

There is a small difference exists between implementations, but in most cases it can be moved out. In case of Kestrel's clock which has a specific logic inside, there could be made a new interface `IScopedSystemClock` which will provide the scope start time as `UtcNow` does now. Therefore, looks like all of them could be merged into a single class/interface and put into `Microsoft.Extensions.Primitives`.

The same interface often implemented by developers themselves to be used by microservices and applications utilizing dependency injection.

Having a common implementation of the data provider pattern will free users from repeating the same simple code many times and will allow to test apps in conjunction with ASP.NET internals without changing an environment.

## Proposed API

The `ISystemClock` defines a way to get the current time in UTC timezone, and it has a simple implementation:

```csharp
public interface ISystemClock
{
    DateTimeOffset UtcNow { get; }
}

public class SystemClock : ISystemClock
{
    public DateTimeOffset UtcNow => DateTimeOffset.UtcNow;
}
```

---

Originally proposed in dotnet/aspnetcore#16844.

### LINKED ISSUE #84274: Address the TimeProvider community feedback
https://github.com/dotnet/runtime/issues/36617

Original writing by @stephentoub 

- Base implementation. We make all the abstract members instead be virtual. We’d then make their base implementations be the system implementations. This makes it easier to customize the default behavior, only needing to override the things you care about (it shouldn’t impact mocking at all one way or the other). We can still keep the type abstract, in order to make it clear that there’s zero benefit to instantiating it directly, but we could remove the abstractness if there’s a good reason to. If we do make it non-abstract, the System singleton would just be an instance of the base type. If we leave it abstract, the internal SystemTimeProvider simply becomes private sealed class SystemTimeProvider : TimeProvider { }, as all of its implementation is the base implementation.
Delete FromLocalTimeZone. This is such a niche use case, it’s not worth cluttering up the surface area of the type for or breeding choice when someone does TimeProvider. in an IDE, e.g. I don’t want someone accidentally thinking they should be doing TimeProvider.FromLocalTimeZone(TimeZoneInfo.Local) or something like that. For someone who does have this scenario, once the system implementation is the base, they can achieve it with their own simple derived type:
sealed class LocalTimeProvider(TimeZoneInfo local) : TimeProvider
```C#
sealed class LocalTimeProvider(TimeZoneInfo local) : TimeProvider
{
    public override LocalTimeZone => local;
}
```
- Parameterless ctor. Delete the existing (int) constructor and just make it parameterless, and either a) make TimestampFrequency virtual or b) add a protected virtual TimestampFrequencyCore (where TimestampFrequency would then invoke TimestampFrequencyCore once and store the result). We ended up with the ctor design so as to help ensure that frequency is guaranteed to be a constant, since we don’t envision or want to support a system where frequency changes (it would make it impossible to understand timestamps if that’s possible). We can achieve the same thing with FrequencyCore, or we can just state that an override should return the same value every time and leave it at that. And with the base implementation being the system implementation, the need for someone to override this should be practically never other than if they want to test their system’s correct handling of manual use of frequency values. As we cited as a possible issue when we were discussing the ctor, having no parameterless ctor does make mocking a tad bit more complicated, and as that's a primary scenario, removing any road blocks there is a good thing.
- Methods. I could go either way on this one, whether keeping UtcNow and LocalNow properties or making them GetUtcNow() and GetLocalNow(). I lean towards methods, for consistency within the class itself with GetTimeStamp(), because if we were designing everything from scratch they would be methods, because we do expect their values to change automatically between some invocations, etc.
What’s currently checked in is:

## Change Proposal

```diff

namespace System
{
    public abstract class TimeProvider
    {
        public static TimeProvider System { get; }
        
+      protected TimeProvider();

-      public abstract DateTimeOffset UtcNow { get; }
+      public virtual DateTimeOffset GetUtcNow();

-      public DateTimeOffset LocalNow { get; }
+      public DateTimeOffset GetLocalNow();

-      public abstract TimeZoneInfo LocalTimeZone { get; }
+      public virtual TimeZoneInfo LocalTimeZone { get; }

-      public abstract long GetTimestamp();
+      public virtual long GetTimestamp();

-      protected TimeProvider(long timestampFrequency);
-      public static TimeProvider FromLocalTimeZone(TimeZoneInfo timeZone);

-      public long TimestampFrequency { get; }
+      public virtual long TimestampFrequency { get; } // or `public long TimestampFrequency { get; }` and `protected virtual long TimestampFrequencyCore { get; }`

-      public abstract ITimer CreateTimer(TimerCallback callback, object? state, TimeSpan dueTime, TimeSpan period);
+      public virtual ITimer CreateTimer(TimerCallback callback, object? state, TimeSpan dueTime, TimeSpan period);

       public TimeSpan GetElapsedTime(long startingTimestamp, long endingTimestamp);
    }
}
```

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/36617
Fixes https://github.com/dotnet/runtime/issues/84274

This is the third and last part of the changes to TimeProvider.

### CODE REVIEW

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/pull/84235
https://github.com/dotnet/runtime/pull/83604

File: src/libraries/Common/src/System/TimeProvider.cs [hunk 1]
```diff
@@ -10,115 +10,100 @@ namespace System
...
         /// <remarks>
-        /// If the <see cref="TimeZoneInfo.Local"/> changes after the object is returned, the change will be reflected in any subsequent operations that retrieve <see cref="TimeProvider.LocalNow"/>.
+        /// If the <see cref="TimeZoneInfo.Local"/> changes after the object is returned, the change will be reflected in any subsequent operations that retrieve <see cref="TimeProvider.GetLocalNow"/>.
         /// </remarks>
-        public static TimeProvider System { get; } = new SystemTimeProvider(null);
+        public static TimeProvider System { get; } = new SystemTimeProvider();
 
         /// <summary>
-        /// Initializes the instance with the timestamp frequency.
+        /// Initializes new instance of <see cref="TimeProvider"/>.
```
Comment (stephentoub) [inline src/libraries/Common/src/System/TimeProvider.cs:24]:
```suggestion
        /// Initializes the <see cref="TimeProvider"/>.
```

File: src/libraries/Common/src/System/TimeProvider.cs [hunk 2]
```diff
@@ -10,115 +10,100 @@ namespace System
...
-                DateTime utcDateTime = UtcNow.UtcDateTime;
-                TimeSpan offset = LocalTimeZone.GetUtcOffset(utcDateTime);
-
-                long localTicks = utcDateTime.Ticks + offset.Ticks;
-                if ((ulong)localTicks > (ulong)s_maxDateTicks)
-                {
-                    localTicks = localTicks < s_minDateTicks ? s_minDateTicks : s_maxDateTicks;
-                }
+            DateTimeOffset utcDateTime = GetUtcNow();
+            TimeSpan offset = (LocalTimeZone ?? TimeZoneInfo.Local).GetUtcOffset(utcDateTime);
```
Comment (stephentoub) [inline src/libraries/Common/src/System/TimeProvider.cs:50]: This trying to protect against a derived type erroneously returning null from LocalTimeZone?  If we want to protect against that, I think we should throw an exception instead... otherwise it suggests returning null is acceptable.

File: src/libraries/Common/src/System/TimeProvider.cs [hunk 3]
```diff
@@ -10,115 +10,100 @@ namespace System
...
+        public TimeSpan GetElapsedTime(long startingTimestamp, long endingTimestamp)
+        {
+            long timestampFrequency = TimestampFrequency;
+            if (timestampFrequency <= 0)
+            {
+#if SYSTEM_PRIVATE_CORELIB
+                ArgumentOutOfRangeException.ThrowIfNegativeOrZero(TimestampFrequency);
+#else
+                string propertyName = nameof(TimestampFrequency);
+                throw new ArgumentOutOfRangeException(propertyName, timestampFrequency, SR.Format(SR.ArgumentOutOfRange_Generic_MustBeNonNegativeNonZero, nameof(TimestampFrequency)));
```
Comment (stephentoub) [inline src/libraries/Common/src/System/TimeProvider.cs:101]:
```suggestion
                throw new ArgumentOutOfRangeException(nameof(TimestampFrequency), timestampFrequency, SR.Format(SR.ArgumentOutOfRange_Generic_MustBeNonNegativeNonZero, nameof(TimestampFrequency)));
```

File: src/libraries/Common/src/System/TimeProvider.cs [hunk 4]
```diff
@@ -10,115 +10,100 @@ namespace System
...
-            if (timeZone is null)
-            {
-                throw new ArgumentNullException(nameof(timeZone));
-            }
-#endif // SYSTEM_PRIVATE_CORELIB
-
-            return new SystemTimeProvider(timeZone);
-        }
+        /// <remarks>
+        /// The default implementation returns <see cref="Stopwatch.Frequency"/>.
```
Comment (stephentoub) [inline src/libraries/Common/src/System/TimeProvider.cs:73]: Maybe add a comment that the value should be idempotent and never change for a given TimeProvider instance.

**Review by stephentoub — APPROVED** [review]

File: src/libraries/Common/src/System/TimeProvider.cs (hunk 3 above)
Comment (tarekgh) [reply src/libraries/Common/src/System/TimeProvider.cs:101]: I had it as you suggested but it is producing the following error:

```diff 
- error CA2208: Method GetElapsedTime passes 'TimestampFrequency' as the paramName argument to a ArgumentOutOfRangeException constructor. Replace this argument with one of the method's parameter names. Note that the provided parameter name should have the exact casing as declared on the method. [C:\oss\runtime\src\libraries\Microsoft.Bcl.TimeProvider\src\Microsoft.Bcl.TimeProvider.csproj::TargetFramework=net462]
```

That is why I worked around it by using `string propertyName = nameof(TimestampFrequency);`

Comment (stephentoub) [reply src/libraries/Common/src/System/TimeProvider.cs:110]: I hadn't looked to see what this was for. I think ArgOutOfRangeException is the wrong type here.... it's not an argument that's wrong. The analyzer is right that something is amiss.

Comment (tarekgh) [reply src/libraries/Common/src/System/TimeProvider.cs:110]: InvalidOperationException will be more reasonable here?

Comment (stephentoub) [reply src/libraries/Common/src/System/TimeProvider.cs:110]: Yeah, I think that's better.

Comment (tarekgh) [reply src/libraries/Common/src/System/TimeProvider.cs]: Done!

File: src/libraries/System.Private.CoreLib/src/Resources/Strings.resx [hunk 5]
```diff
@@ -2984,6 +2984,12 @@
   <data name="InvalidOperation_SpanOverlappedOperation" xml:space="preserve">
     <value>This operation is invalid on overlapping buffers.</value>
   </data>
+  <data name="InvalidOperation_TimeProviderNullLocalTimeZone" xml:space="preserve">
+    <value>The operation cannot performed when having TimeProvider.LocalTimeZone is returning null.</value>
```
Comment (pinkfloydx33) [inline src/libraries/System.Private.CoreLib/src/Resources/Strings.resx:2988]: > The operation cannot performed when having TimeProvider.LocalTimeZone is returning null.

Shouldn't this be something closer to:
> The operation cannot be performed when TimeProvider.LocalTimeZone is  null.

Similarly, all the others feel slightly wrong.

**Comment by pinkfloydx33** [comment]
I know that #84274 decided to go with methods for the "now" properties.... but it feels Java-y and was quite weird to look at upon review.

Maybe it's because it's not consistent with a simple `DateTime.UtcNow` invocation. That's what it feels like it _should_ be matched to, especially since a "now" abstraction was the driving force behind the original request. Explaining why one is a method and the other isn't--especially to a newcomer--feels like it could crop up a bit. I understand the reasoning, it just feels too inconsistent with the current static properties. 

Leaving it as a `UtcNow` property may also help keep the diffs tidy for _many_ of the places migrating from their own `ISystemClock` implementations, for whatever that is worth. 

Just my 2cp

**Comment by davidfowl** [comment]
I agree with leaving the properties as properties and not changing it to methods on this new abstraction. Feels weird to try and “fix things” here.

**Comment by stephentoub** [comment]
> Feels weird to try and “fix things” here.

Why is it weird? This is a new abstraction. Why shouldn't we get it "right", especially when overrides can do even more than the erroneous-as-a-property UtcNow? I think the arguments made in the issue where this was discussed at length are pretty compelling. We shouldn't be relitigating it here.

**Comment by davidfowl** [comment]
I think I favor consistency over “technically correct”.

**Comment by stephentoub** [comment]
From a consistency perspective, I think consistency with itself is more important. There are similar explanation challenges as to why it's appropriate for UtcNow/LocalNow to be properties but GetTimestamp() to be a method.

**Comment by tarekgh** [comment]
There are convincing strong reasons mentioned in the following comments to have them as methods. 

https://github.com/dotnet/runtime/issues/36617#issuecomment-1489433173
https://github.com/dotnet/runtime/issues/36617#issuecomment-1489501068

Additionally, users keep complaining having `UtcNow` and `Now` as a property and even we got requests before to obsolete such `Now`.  I don't think we need to repeat the same mistake just to be consistent.

File: src/libraries/System.Private.CoreLib/src/Resources/Strings.resx (hunk 5 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/Resources/Strings.resx]: Thanks. I fixed the messages.

**Comment by davidfowl** [comment]
Sure, like I said, I wouldn’t die on this hill 😅

File: src/libraries/Microsoft.Bcl.TimeProvider/ref/Microsoft.Bcl.TimeProvider.cs [hunk 6]
```diff
@@ -8,15 +8,14 @@ namespace System
...
-        public abstract long GetTimestamp();
+        protected TimeProvider() { throw null; }
+        public virtual System.DateTimeOffset GetUtcNow() { throw null; }
+        public System.DateTimeOffset GetLocalNow() { throw null; }
+        public virtual System.TimeZoneInfo LocalTimeZone { get; }
+        public virtual long TimestampFrequency { get; }
+        public virtual long GetTimestamp() { throw null; }
         public TimeSpan GetElapsedTime(long startingTimestamp, long endingTimestamp) { throw null; }
-        public abstract System.Threading.ITimer CreateTimer(System.Threading.TimerCallback callback, object? state, System.TimeSpan dueTime, System.TimeSpan period);
+        public virtual System.Threading.ITimer CreateTimer(System.Threading.TimerCallback callback, object? state, System.TimeSpan dueTime, System.TimeSpan period) { throw null; }
```
Comment (niemyjski) [inline src/libraries/Microsoft.Bcl.TimeProvider/ref/Microsoft.Bcl.TimeProvider.cs:18]: Question: Why would you want to throw null here? I'd expect NotImplementedException.

Comment (stephentoub) [reply src/libraries/Microsoft.Bcl.TimeProvider/ref/Microsoft.Bcl.TimeProvider.cs:18]: This is the reference assembly. It should never be used at runtime, and the goal is to define just the signatures while keeping the size as small as possible. throw null is what we do in the ref assemblies everywhere.

Comment (niemyjski) [reply src/libraries/Microsoft.Bcl.TimeProvider/ref/Microsoft.Bcl.TimeProvider.cs:18]: Thanks, that makes sense!
