### PR TITLE
Clear contained flag from AND->NOT transformation

### LINKED ISSUE #116657: Assertion failed 'operand->isUsedFromReg()' in 'System.Uri:InternalIsWellFormedOriginalString():bool:this'
Failed in [runtime-coreclr libraries-jitstress-random](https://dev.azure.com/dnceng-public/public/_build?definitionId=160&_a=summary) / [20250607.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1061711)
Test leg: net10.0-windows-Release-x64-jitstress_random_2-Windows.10.Amd64.Open
Work Item: System.Net.HttpListener.Tests 

```
C:\h\w\91AE081F\w\AFA3096A\e>"C:\h\w\91AE081F\p\dotnet.exe" exec --runtimeconfig System.Net.HttpListener.Tests.runtimeconfig.json --depsfile System.Net.HttpListener.Tests.deps.json xunit.console.dll System.Net.HttpListener.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Net.HttpListener.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.HttpListener.Tests (found 219 of 299 test cases)
  Starting:    System.Net.HttpListener.Tests (parallel test collections = on [4 threads], stop on fail = off)

Assert failure(PID 2912 [0x00000b60], Thread: 6556 [0x199c]): Assertion failed 'operand->isUsedFromReg()' in 'System.Uri:InternalIsWellFormedOriginalString():bool:this' during 'Generate code' (IL size 813; hash 0x83c53887; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\codegenxarch.cpp:715
    Image: C:\h\w\91AE081F\p\dotnet.exe
```

### LINKED ISSUE #116674: Possible JIT (?) or code gen regression between .NET 10 preview 3 and 4 (10.0.100-preview.3.25201.16 vs. 10.0.100-preview.4.25258.110)
### Description

Hey, I am currently experimenting with a custom programming language with the Compiler and VM implementation written in .NET, and I am not quite sure what is wrong.

I have noticed after wanting to check if there is a performance difference between .NET 9 and the latest .NET 10 preview 5, that the VM had a weird runtime error when doing a binary MULTIPLY operation.

The weird thing is that the error place changes if I change the overloaded operator * from `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to `[MethodImpl(MethodImplOptions.NoInlining)]`. Then the exception occurs for example for an ADD operation etc.

I also couldn't hit the break point and the test log said both `IsNumber` props returned true:

```c#
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Value operator *(Value left, Value right)
    {
        if (left.IsNumber && right.IsNumber)
        {
            return new Value(left.AsNumber() * right.AsNumber());
        }

        Console.WriteLine($"Left: {left.IsNumber}, Right: {right.IsNumber}");

        throw new RuntimeException($"Unsupported operator type * for left '{left}' and right '{right}'");
    }
```

The problem only occurs in a release build, in a debug build it works.

I have got the following JIT disassembly (part of it) from 10.0.100-preview.3.25201.16 and 10.0.100-preview.4.25258.110 (there was no difference between 10.0.100-preview.4.25258.110 to 10.0.100-preview.5.25277.114).

The JIT disasm is from the main `Execute` method that contains the VM main loop switch in a release build.

Some noise like:

10.0.100-preview.3.25201.16:

```asm
G_M000_IG34:
       mov      rcx, gword ptr [r14+0x10]
       mov      rdx, 0xD1FFAB1E
       and      rdx, rsi
       mov      r8, 0xD1FFAB1E
       cmp      rdx, r8
       je       SHORT G_M000_IG36
```

```asm
       call     CORINFO_HELP_STRCNS
```

10.0.100-preview.4.25258.110:

```asm
G_M000_IG34:
       mov      rcx, gword ptr [r14+0x10]
       mov      rdx, rsi
       not      rdx
       mov      r8, 0xD1FFAB1E
       and      rdx, r8
       je       SHORT G_M000_IG36
```

```asm
       call     [CORINFO_HELP_STRCNS]
```

But the largest diff was this (middle part):

10.0.100-preview.3.25201.16:

```asm
G_M000_IG67:
       call     [VmTest.VmObjectList:get_Items():System.Collections.Generic.List`1[VmTest.Value]:this]
       mov      r14, rax
       lea      rcx, [rbp-0x88]
       call     [VmTest.Value:AsNumber():double:this]
       vmovddup xmm1, xmm0
       vmovddup xmm2, xmm0
       vmovddup xmm0, xmm0
       vcmppd   xmm1, xmm2, xmm1, 0
       vandpd   xmm0, xmm1, xmm0
       vcmppd   xmm1, xmm0, xmmword ptr [reloc @RWD00], 13
       vcvttsd2si ecx, xmm0
       vmovd    xmm0, ecx
       vpbroadcastd xmm0, xmm0
       vpblendvb xmm0, xmm0, xmmword ptr [reloc @RWD16], xmm1
       vmovd    edx, xmm0
       mov      rcx, r14
       cmp      dword ptr [rcx], ecx
       call     [System.Collections.Generic.List`1[VmTest.Value]:get_Item(int):VmTest.Value:this]
       mov      rdx, rax
       mov      rcx, rbx
       call     [VmTest.VirtualMachine:Push(VmTest.Value):this]
       jmp      G_M000_IG148
```

10.0.100-preview.4.25258.110:

```asm
G_M000_IG67:
       call     [VmTest.VmObjectList:get_Items():System.Collections.Generic.List`1[VmTest.Value]:this]
       mov      r14, rax
       lea      rcx, [rbp-0x88]
       call     [VmTest.Value:AsNumber():double:this]
       vcmpsd   xmm1, xmm0, xmm0, 7
       vandpd   xmm1, xmm1, xmm0
       mov      ecx, 0xD1FFAB1E
       vcvttsd2si edx, xmm1
       vucomisd xmm0, qword ptr [reloc @RWD00]
       cmovb    ecx, edx
       mov      edx, ecx
       mov      rcx, r14
       cmp      dword ptr [rcx], ecx
       call     [System.Collections.Generic.List`1[VmTest.Value]:get_Item(int):VmTest.Value:this]
       mov      rdx, rax
       mov      rcx, rbx
       call     [VmTest.VirtualMachine:Push(VmTest.Value):this]
       jmp      G_M000_IG148
```

These are a few times in the diff. The problem seems to occur with and without native AOT.

### Reproduction Steps

If desired I can send the project to an MS employee or maybe try to create a minimal project and create a public repository. I want to have it as an open-source project, but currently it's more of a testing ground.

### Expected behavior

The executed program should execute like before with 10.0.100-preview.3.25201.16 and .NET 9.

Source code of the custom language:

```
number counter = 0

for i in 0..1_500
	counter += 1

WriteLine("Counter: {counter}")
```

Output working program (with .NET 9 and .NET 10 preview 3):

```txt
FunctionRegistry:Load took 5 ms
ClassRegistry:Load took 1 ms
Counter: 1500
```

### Actual behavior

Source code of the custom language:

```
number counter = 0

for i in 0..1_500
	counter += 1

WriteLine("Counter: {counter}")
```

Output of not working program (with .NET 10 preview 4):

```txt
FunctionRegistry:Load took 5 ms
ClassRegistry:Load took 1 ms
Unhandled exception. VmTest.Exceptions.RuntimeException: RuntimeError: Unsupported operator type + for left '1427' and right '1'
   at VmTest.VirtualMachine.Execute() in C:\Users\{USER}\source\repos\VmTest\VmTest\VirtualMachine.cs:line 314
   at Program.<Main>$(String[] args) in C:\Users\{USER}\source\repos\VmTest\VmTest\Program.cs:line 40
```

As you can see, the left and right operand are both ints (numbers in my language).

Interesting enough is that it does not occur with a lower iteration count like for example 1000.

### Regression?

Maybe, it woks with `-c Release` with 10.0.100-preview.3.25201.16 and fails with 10.0.100-preview.4.25258.110

### Known Workarounds

Use .NET 10 preview 3 or run in debug mode.

### Configuration

OS: Windows 11 23H2
Architecture: x64

Working:
.NET 9 and 10.0.100-preview.3.25201.16

Not working in release mode (works in debug mode):
>= 10.0.100-preview.4.25258.110

### Other information

If you have any questions or things I can provide or test please let me know.

### LINKED ISSUE #117795: JIT assert in ILC in test runs: ILC: Assertion failed 'operand->isUsedFromReg()' during 'Generate code'
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098314&view=logs&jobId=a9eab304-9375-5df6-9f7c-f505bd759fef&j=ea7d6d51-d18d-5306-47bd-e3b7db04467e&t=6f613bc6-161e-53a2-c035-24718f3c6909
Build error leg or test failing: windows-x64 Checked NativeAOT

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "ILC: Assertion failed 'operand->isUsedFromReg\\(\\)' in '.+' during 'Generate code'",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098314
**Error message validated:** `[ILC: Assertion failed 'operand->isUsedFromReg\(\)' in '.+' during 'Generate code'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/17/2025 11:27:26 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[1098562](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098562)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098562/logs/347)|dotnet/runtime#117258|
|[1098544](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098544)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098544/logs/385)|dotnet/runtime#117799|
|[1098488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098488)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098488/logs/853)|dotnet/runtime#117797|
|[1098458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098458)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098458/logs/881)|dotnet/runtime#117796|
|[1098452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098452)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098452/logs/353)|dotnet/runtime#117684|
|[1098432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098432)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098432/logs/1133)|dotnet/runtime#117635|
|[1098425](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098425)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098425/logs/354)|dotnet/runtime#117793|
|[1098385](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098385)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098385/logs/787)|dotnet/runtime#117583|
|[1098379](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098379)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098379/logs/369)|dotnet/runtime#117784|
|[1098369](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098369)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098369/logs/765)|dotnet/runtime#117792|
|[1098365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098365)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098365/logs/357)|dotnet/runtime#117791|
|[1098359](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098359)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098359/logs/753)|dotnet/runtime#117790|
|[1098349](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098349)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098349/logs/326)|dotnet/runtime#117258|
|[1098342](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098342)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098342/logs/351)|dotnet/runtime#117700|
|[1098314](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098314)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098314/logs/1140)|dotnet/runtime#117635|
|[1098284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098284)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098284/logs/800)|dotnet/runtime#117686|
|[1098280](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098280)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098280/logs/788)|dotnet/runtime#117690|
|[1098270](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098270)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098270/logs/777)|dotnet/runtime#117738|
|[1098263](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098263)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098263/logs/201)||
|[1098209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098209)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098209/logs/1034)||
|[1098201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098201)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098201/logs/385)|dotnet/runtime#117725|
|[1098172](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098172)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1098172/logs/294)|dotnet/runtime#117779|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|22|22|22|

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/117795
Fixes https://github.com/dotnet/runtime/issues/117783
Fixes https://github.com/dotnet/runtime/issues/116657
Fixes https://github.com/dotnet/runtime/issues/116674

Introduced in https://github.com/dotnet/runtime/pull/111933

We had `AND(X, CNS)` where we marked X as contained. Then this transformation converted `AND(X, CNS)` into `NOT(X)` while `X` is still marked as contained when the emitter doesn't support containment for this node.

### CODE REVIEW

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -4308,6 +4308,7 @@ GenTree* Lowering::OptimizeConstCompare(GenTree* cmp)
             // Transform EQ|NE(AND(x, y), y) into EQ|NE(AND(NOT(x), y), 0) when y is a constant.
             //
 
+            andOp1->ClearContained();
```
Comment (tannergooding) [inline src/coreclr/jit/lower.cpp:4311]: Not really related to this PR, but this feels like the type of transform we could/should be doing in HIR, such as part of morph. This isn't something that is architecture or lowering specific and would likely mitigate some risk from the LIR/containment complexities.

It's also a transform that we could optimize more for constants that are powers of 2. In particular we can use `shr eax, n; and eax, 1` if setting the flag in a register and `bt eax, n` if consuming it as a flag.

Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:4311]: I've just remembered that initially that transformation was done by a community member in HIR (morph) but diffs were worse (that PR was then abandoned)

**Comment by EgorBo** [comment]
/ba-g "Segmentation fault in clang on osx-x64 Debug CoreCLR_Libraries"
