### PR TITLE
[tests] Fix PlatformDetection.IsMonoInterpreter for mobile

### LINKED ISSUE #52460: Tasks issues on Mac Catalyst
### Description

```
* thread #11, name = 'com.apple.NSEventThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2ee00)
    frame #0: 0x00007fff20243ed1 libsystem_malloc.dylib`tiny_malloc_from_free_list + 162
libsystem_malloc.dylib`tiny_malloc_from_free_list:
->  0x7fff20243ed1 <+162>: movq   %rax, (%r9)
    0x7fff20243ed4 <+165>: jmp    0x7fff20243f9d            ; <+366>
    0x7fff20243ed9 <+170>: movq   0x828(%r15), %rax
    0x7fff20243ee0 <+177>: shrq   %cl, %rax
Target 0: (System.Threading.Tasks.Tests) stopped.
```

Approx the same failure with System.Threading.Tasks.Dataflow.Tests

### Configuration

`./build.sh -ci -arch x64 -os MacCatalyst -s libs.tests -c Release /p:ArchiveTests=true /p:MonoForceInterpreter=true  /p:CrossBuild=false`

### Regression?

No

### Other information

Related PR: https://github.com/dotnet/runtime/pull/51139

### PR DESCRIPTION
**Pull request by lambdageek**
Checking for `MONO_ENV_OPTIONS` is not reliable for the mobile test runners because they use the embedding API to enable the interpreter, rather than setting an environment variable.

Instead detect the interpreter by checking the values of the `IsDynamicCodeSupported` and `IsDynamicCodeCompiled` runtime features.

Re-enable the `System.Threading.Tasks.Dataflow.Tests` testsuite on Apple platforms

Fixes https://github.com/dotnet/runtime/issues/52460

### CODE REVIEW

File: src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs [hunk 1]
```diff
@@ -464,17 +464,7 @@ private static bool GetTls13Support()
...
-        private static bool GetIsRunningOnMonoInterpreter()
-        {
-#if NETCOREAPP
-            if (IsBrowser)
-                return RuntimeFeature.IsDynamicCodeSupported;
-#endif
-            // This is a temporary solution because mono does not support interpreter detection
-            // within the runtime.
-            var val = Environment.GetEnvironmentVariable("MONO_ENV_OPTIONS");
-            return (val != null && val.Contains("--interpreter"));
```
Comment (am11) [inline src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs:476]: Can we also remove it from `eng/pipelines/coreclr/templates/run-performance-job.yml`?

Comment (lambdageek) [reply src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs:476]: I don't think so.  We still need to _set_ it when we're running on desktop platforms using Mono, since in that case we're just using the normal libraries test host.

The issue is just that it's not sufficient to check for the environment variable setting to detect whether we're using the interpreter.  The RuntimeFeature checks should be accurate on all configurations, AFAIK.

**Review by steveisok — APPROVED** [review]
