### PR TITLE
Fix OperIs(GT_CNS_INT, GT_CNS_LNG) assertion during import

### LINKED ISSUE #126060: Assertion 'OperIs(GT_CNS_INT, GT_CNS_LNG)' during intrinsic import
Antigen pipelines hitting this assert on windows x64, reduction:
```
using System.Runtime.Intrinsics;

Vector256.WithElement(Vector256<double>.AllBitsSet, 4, 0.0);
```

```
Assertion failed 'OperIs(GT_CNS_INT, GT_CNS_LNG)' in 'Program:<Main>$(System.String[])' during 'Importation' (IL size 22; hash 0x79b422bf; Tier0)
```

### PR DESCRIPTION
**Pull request by dhartglassMSFT**
Assertion in `gtFoldExprHWIntrinsic` on `Vector.WithElement`.  The index argument could be a COMMA (boundscheck+integral constant) rather than just an integral constant as expected.

The windows-x64 antigen runs hit this assert pretty frequently, so fixing here to reduce the noise.

fixes #126060

### CODE REVIEW

**Review by AndyAyersMS — APPROVED** [review]

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -33814,7 +33814,7 @@ GenTree* Compiler::gtFoldExprHWIntrinsic(GenTreeHWIntrinsic* tree)
             case NI_Vector512_WithElement:
 #endif
             {
-                if ((cnsNode != op1) || !op3->OperIsConst())
+                if ((cnsNode != op1) || !op2->IsCnsIntOrI() || !op3->OperIsConst())
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:33817]: This is definitely the simplest fix, but is it going to hinder folding in cases that could otherwise have been handled?

That is, if we have a `WithElement(simd_cns, Comma(node, int_cns))` can we not still optimize this to `comma(node, simd_cns)`?

Comment (dhartglassMSFT) [reply src/coreclr/jit/gentree.cpp:33817]: Is this necessarily better?

i checked, i found for a case like `WithElement(vec, someInlinee, 0.0)` we're still able to optimize away the range check later on a subsequent pass anyway

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:33817]: Its not about the range check being optimized out, its about constant folding which may allow for other optimizations to kick in.

Comment (dhartglassMSFT) [reply src/coreclr/jit/gentree.cpp:33817]: yeah i wrote that when i was in a hurry, i meant we get the optimized range check + the folding here kicks in in a later phase

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:33817]: It varies for that. We have some optimizations that depend on early folding and others that don't

It's not a blocker if we don't handle it here, but if its relatively trivial to handle here then it feels like something we should.

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/gentree.cpp (hunk 1 above)
Comment (dhartglassMSFT) [reply src/coreclr/jit/gentree.cpp:33817]: For sure; so I did spend a bit here trying to get a repro case that would hit this new code path (a foldable WithElement+COMMA with a constant operand) but I couldn't build that case.  I do see the value, but I wouldn't want to do that transform without having something to test it against
