### PR TITLE
[browser] Fix dev tools profiler

### LINKED ISSUE #116146: [wasm][profiler] dev tools profiler fails with unbalanced stack
```
* Assertion at C:/Dev/runtime/src/mono/mono/profiler/browser.c:192, condition `top_frame->method == method' not met, 
function:method_exc_leave, method_exc_leave: 214 method mismatch top_frame 
void System.Runtime.CompilerServices.TaskAwaiter:HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task,System.Threading.Tasks.ConfigureAwaitOptions) != leave 
void Grpc.Net.Client.Balancer.Internal.ConnectionManager/<PickAsync>d__46:MoveNext ()
```

### PR DESCRIPTION
**Pull request by pavelsavara**
Fixes https://github.com/dotnet/runtime/issues/116146

- use `interp_frame` as profiler stack anchor for interpreter
- fix profiling with jiterp
- make dev tools profiler unsupported with AOT
- optimize calls to `mono_wasm_profiler_now`
- fix logging with null domain

### CODE REVIEW

File: src/mono/mono/profiler/browser.c [hunk 1]
```diff
@@ -65,12 +66,39 @@ static int sample_skip_counter;
 double mono_wasm_profiler_now ();
 void mono_wasm_profiler_record (MonoMethod *method, double start);
 
+static gpointer get_last_sp (MonoProfilerCallContext *ctx)
+{
+	/* TODO AOT
+	if (ctx) {
+		if (ctx->interp_frame) {
```
Comment (ilonatommy) [inline src/mono/mono/profiler/browser.c]: "use interp_frame as profiler stack anchor"

`interp_frame` has only removals, not a new usage. Is the description out-of-date?

File: src/mono/browser/runtime/jiterpreter-trace-generator.ts [hunk 2]
```diff
@@ -1426,7 +1426,6 @@ export function generateWasmBody (
                 break;
             case MintOpcode.MINT_PROF_EXIT:
             case MintOpcode.MINT_PROF_EXIT_VOID:
-                append_profiler_event(builder, ip, opcode);
```
Comment (ilonatommy) [inline src/mono/browser/runtime/jiterpreter-trace-generator.ts:1429]: Why did it fix jiterp?

Comment (pavelsavara) [reply src/mono/browser/runtime/jiterpreter-trace-generator.ts:1429]: Because the same event is also executed by interp and this made the stack in the profiler unbalanced

File: src/mono/mono/profiler/browser.c (hunk 1 above)
Comment (pavelsavara) [reply src/mono/mono/profiler/browser.c]: `ext->interp_exit_data` is set to `interp_frame`. 

If we enabled context to be passed to profiler, we could also read `ctx->interp_frame` (at cost of extra allocation per event call). That is, for those of the existing profiler events, that have appropriate event signature.

But the AOT stack frames need some other monotonic "stack pointer", ideally one that could be mixed with `interp_frame`. I was not able to find one. So I put AOT out of scope for now.

**Review by ilonatommy — APPROVED** [review]

File: src/mono/mono/profiler/browser.c [hunk 3]
```diff
@@ -65,12 +66,39 @@ static int sample_skip_counter;
 double mono_wasm_profiler_now ();
 void mono_wasm_profiler_record (MonoMethod *method, double start);
 
+static gpointer get_last_sp (MonoProfilerCallContext *ctx)
+{
+	/* TODO AOT
```
Comment (maraf) [inline src/mono/mono/profiler/browser.c]: nit: "TODO add support for AOT" & drop the commented code

File: src/mono/wasm/build/WasmApp.Common.targets [hunk 4]
```diff
@@ -495,6 +495,7 @@
 
     <Error Condition="'$(WasmProfilers)' != '' and '$(EnableDiagnostics)' != 'false'" Text="%24(WasmProfilers)=$(WasmProfilers) is not supported together with %24(EnableDiagnostics)=$(EnableDiagnostics)"/>
     <Error Condition="'$(WasmProfilers)' != '' and '$(WasmPerformanceInstrumentation)' != ''" Text="%24(WasmProfilers)=$(WasmProfilers) is not supported together with %24(WasmPerformanceInstrumentation)=$(WasmPerformanceInstrumentation)"/>
+    <Error Condition="'$(WasmProfilers)' != '' and '$(RunAOTCompilation)' == 'true'" Text="%24(WasmProfilers)=$(WasmProfilers) is not supported together with %24(RunAOTCompilation)=$(RunAOTCompilation)"/>
```
Comment (maraf) [inline src/mono/wasm/build/WasmApp.Common.targets]: Does it mean that no profiles are supported in AOT mode or that this prop is used only for Dev tools profiler?

Comment (pavelsavara) [reply src/mono/wasm/build/WasmApp.Common.targets]: Good catch, I only wanted to disable dev tools profiler, not log profiler.

**Review by maraf — APPROVED** [review]
