### PR TITLE
Makes GetChildKeys more efficient

### LINKED ISSUE #62510: ChainedConfigurationProvider.GetChildKeys is inefficient
### Description

`ChainedConfigurationProvider.GetChildKeys` ends up [splitting strings](https://github.com/dotnet/runtime/blob/12a8819eee9865eb38bca6c05fdece1053102854/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs#L32-L33) which forces an array allocation even if there are no keys with segments. This has shown up on a couple of performance profiles internally and we should improve it.

### Regression?

No

### Data

Ask me

### Analysis

Ask me

### PR DESCRIPTION
**Pull request by maryamariyan**
### Details

Prevents [`ChainedConfigurationProvider.GetChildKeys`](https://github.com/dotnet/runtime/blob/12a8819eee9865eb38bca6c05fdece1053102854/src/libraries/Microsoft.Extensions.Configuration/src/ChainedConfigurationProvider.cs#L75) from [splitting strings](https://github.com/dotnet/runtime/blob/12a8819eee9865eb38bca6c05fdece1053102854/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs#L32-L33) or making unnecessary allocation when keys do not contain delimiter or when keys are empty.

Fixes #62510

### Benchmarks

Benchmark code: [link to gist](https://gist.github.com/maryamariyan/aae2baa69c054cc37ebb0940e0770abd)
Also dotnet/performance PR: https://github.com/dotnet/performance/pull/2336

Without diff:

```
|                                     Method |        Mean |     Error |      StdDev |    Gen 0 |  Gen 1 | Allocated |
|------------------------------------------- |------------:|----------:|------------:|---------:|-------:|----------:|
|         AddChainedConfigurationNoDelimiter |  1,255.4 us |  24.20 us |    50.52 us | 130.8594 | 5.8594 |  1,011 KB |
|               AddChainedConfigurationEmpty | 37,957.7 us | 718.05 us | 1,466.79 us |  76.9231 |      - |  1,010 KB |
|       AddChainedConfigurationWithSplitting |    563.1 us |  11.11 us |    27.88 us |  61.5234 | 5.8594 |    472 KB |
| AddChainedConfigurationWithSplittingLooped |    557.0 us |  11.01 us |    23.69 us |  61.5234 | 5.8594 |    472 KB |
```

UPDATED TO LATEST:
With latest PR diff (updated using [b128f63](https://github.com/dotnet/runtime/pull/67186/commits/b128f6325108f2e3dd22834d9fef76e37b53695f)):

```
|                                     Method |        Mean |     Error |    StdDev |   Gen 0 |  Gen 1 | Allocated |
|------------------------------------------- |------------:|----------:|----------:|--------:|-------:|----------:|
|         AddChainedConfigurationNoDelimiter |    838.2 us |  16.30 us |  21.19 us | 18.5547 | 2.9297 |    143 KB |
|               AddChainedConfigurationEmpty | 20,030.8 us | 398.32 us | 545.23 us |       - |      - |    143 KB |
|       AddChainedConfigurationWithSplitting |    445.4 us |   8.12 us |   7.20 us |  4.8828 | 0.4883 |     40 KB |
| AddChainedConfigurationWithSplittingLooped |    430.9 us |   8.54 us |  22.50 us |  4.8828 |      - |     40 KB |
```

### CODE REVIEW

**Comment by maryamariyan** [comment]
@adamsitnik not sure if I need to change a setting for the `MultimodalDistribution` warning showing up in the screenshot

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 1]
```diff
@@ -29,49 +29,77 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+            if (string.IsNullOrWhiteSpace(x))
+            {
+                if (string.IsNullOrWhiteSpace(y))
+                {
+                    return 0;
+                }
+
+                return -y!.Length;
+            }
+            else if (string.IsNullOrWhiteSpace(y))
```
Comment (SteveDunn) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:41]: Redundant `else`

**Comment by davidfowl** [comment]
Can you also add a performance test for keys that do need the split?

**Comment by maryamariyan** [comment]
> Can you also add a performance test for keys that do need the split?

As you suspected the commit was not optimized for the keys needing split. Now with the newest diff I changed it to be optimized for split case. Using:

```c#
        {
// in Setup:
            var splittingKeys = new Dictionary<string, string>() { };
            for (int i = 1000; i < 2000; i++)
            {
                splittingKeys.Add("a:" + i.ToString(), string.Empty);
            }

            _chainedConfigWithSplitting = new ChainedConfigurationProvider(new ChainedConfigurationSource
            {
                Configuration = new ConfigurationBuilder()
                    .Add(new MemoryConfigurationSource { InitialData = splittingKeys })
                    .Build(),
                ShouldDisposeConfiguration = false,
            });
        }

        [Benchmark]
        public void AddChainedConfigurationWithSplitting()
            => _chainedConfigWithSplitting.GetChildKeys(new string[0], null);
```


- Without changes

image

- After new commit: optimized for split case

Screen Shot 2022-03-26 at 1 17 28 AM

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 2]
```diff
@@ -29,49 +29,64 @@ public class ConfigurationKeyComparer : IComparer<string>
...
-            string[] xParts = x?.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries) ?? Array.Empty<string>();
-            string[] yParts = y?.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries) ?? Array.Empty<string>();
-
-            // Compare each part until we get two parts that are not equal
-            for (int i = 0; i < Math.Min(xParts.Length, yParts.Length); i++)
+            if (x is not null && y is not null)
             {
-                x = xParts[i];
-                y = yParts[i];
+                if (x!.Contains(ConfigurationPath.KeyDelimiter) && y!.Contains(ConfigurationPath.KeyDelimiter))
```
Comment (gfoidl) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:34]:
```suggestion
                if (x.Contains(ConfigurationPath.KeyDelimiter) && y!.Contains(ConfigurationPath.KeyDelimiter))
```
Shouldn't be needed here (and below), as above is the check for `x is not null`.

**Comment by danmoseley** [comment]
Should your perf tests get added to the perf repo?

BTW you can copy paste the results tables into an issue like this as they are valid markdown. That’s easier than pasting screenshots.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 3]
```diff
@@ -29,49 +29,64 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+                }
+                else
+                {
+                    return compare(x, y);
+                }
+            }
 
+            return x?.Length ?? 0 - y?.Length ?? 0;
+
+            static int compare(string? a, string? b)
```
Comment (gfoidl) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:62]:
```suggestion
            static int Compare(string? a, string? b)
```
Local functions should also be named _PascalCase_.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 4]
```diff
@@ -29,49 +29,64 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+            {
                 int value1 = 0;
                 int value2 = 0;
 
-                bool xIsInt = x != null && int.TryParse(x, out value1);
-                bool yIsInt = y != null && int.TryParse(y, out value2);
+                bool aIsInt = a != null && int.TryParse(a, out value1);
+                bool bIsInt = b != null && int.TryParse(b, out value2);
```
Comment (gfoidl) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:68]:
```suggestion
                bool aIsInt = int.TryParse(a, out value1);
                bool bIsInt = int.TryParse(b, out value2);
```
`int.TryParse` does a null-check itself (and returns `false` if `null`), so you can omit the extra check here.

**Review by gfoidl — COMMENTED** [review]
Some nits.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 5]
```diff
@@ -29,49 +29,64 @@ public class ConfigurationKeyComparer : IComparer<string>
...
-
-            // Compare each part until we get two parts that are not equal
-            for (int i = 0; i < Math.Min(xParts.Length, yParts.Length); i++)
+            if (x is not null && y is not null)
             {
-                x = xParts[i];
-                y = yParts[i];
+                if (x!.Contains(ConfigurationPath.KeyDelimiter) && y!.Contains(ConfigurationPath.KeyDelimiter))
+                {
+                    string[] xParts = x!.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries);
```
Comment (tarekgh) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:36]: >xParts [](http://example.com/codeflow?start=29&length=6)

Can we optimize this more but avoid the allocations occur because of string.split? I think this is possible and not hard to do it. Like use string.indexof(ordinal) then compare substrings after that.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs (hunk 3 above)
Comment (SteveDunn) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:62]: I was wondering about that. I really like _camelCase_ local functions, and indeed, [_camelCased_ private functions](https://dunnhq.com/posts/2018/06/26/247/).

Comment (gfoidl) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:62]: Here applies [C# Coding Style](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md) §13
> We use PascalCasing for all method names, including local functions.

😉

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs (hunk 5 above)
Comment (adamsitnik) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:36]: I agree with @tarekgh.

BTW it's a pity that the code which is consuming this type is using string to represent a complex type and uses indexof/split back and forth.

The index is known here:

https://github.com/dotnet/runtime/blob/6033ef2c56db79e68e13f2856f42d250399d927e/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationProvider.cs#L98

then a substring is performed:

https://github.com/dotnet/runtime/blob/6033ef2c56db79e68e13f2856f42d250399d927e/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationProvider.cs#L99

then all the logic is reversed to be able to sort the keys:

https://github.com/dotnet/runtime/blob/6033ef2c56db79e68e13f2856f42d250399d927e/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationProvider.cs#L91

It's just a digression, I don't expect @maryamariyan to fix it in this PR (these types are public)

**Review by adamsitnik — COMMENTED** [review]
> not sure if I need to change a setting for the MultimodalDistribution warning showing up in the screenshot

You don't need to change anything. This benchmark just seems to be multimodal.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 6]
```diff
@@ -29,49 +29,64 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+                    string[] yParts = y!.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries);
+
+                    // Compare each part until we get two parts that are not equal
+                    for (int i = 0; i < Math.Min(xParts.Length, yParts.Length); i++)
+                    {
+                        int result = compare(xParts[i], yParts[i]);
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:42]:
```suggestion
                        int result = Compare(xParts[i], yParts[i]);
```

**Comment by maryamariyan** [comment]
With new changes,

Without diff:
```
|                                     Method |        Mean |     Error |      StdDev |    Gen 0 |  Gen 1 | Allocated |
|------------------------------------------- |------------:|----------:|------------:|---------:|-------:|----------:|
|         AddChainedConfigurationNoDelimiter |  1,255.4 us |  24.20 us |    50.52 us | 130.8594 | 5.8594 |  1,011 KB |
|               AddChainedConfigurationEmpty | 37,957.7 us | 718.05 us | 1,466.79 us |  76.9231 |      - |  1,010 KB |
|       AddChainedConfigurationWithSplitting |    563.1 us |  11.11 us |    27.88 us |  61.5234 | 5.8594 |    472 KB |
| AddChainedConfigurationWithSplittingLooped |    557.0 us |  11.01 us |    23.69 us |  61.5234 | 5.8594 |    472 KB |

```

With changes:
```
|                                     Method |        Mean |     Error |    StdDev |   Gen 0 |  Gen 1 | Allocated |
|------------------------------------------- |------------:|----------:|----------:|--------:|-------:|----------:|
|         AddChainedConfigurationNoDelimiter |    832.3 us |  16.46 us |  28.39 us | 18.5547 | 2.9297 |    143 KB |
|               AddChainedConfigurationEmpty | 18,357.2 us | 365.24 us | 676.99 us |       - |      - |    143 KB |
|       AddChainedConfigurationWithSplitting |    391.5 us |   7.66 us |  14.01 us |  4.8828 |      - |     40 KB |
| AddChainedConfigurationWithSplittingLooped |    376.5 us |   6.71 us |   9.19 us |  4.8828 | 0.4883 |     40 KB |

```

**Comment by danmoseley** [comment]
Should your benchmarks above be added to dotnet/performance to protect your change from regressions?

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 7]
```diff
@@ -29,49 +29,94 @@ public class ConfigurationKeyComparer : IComparer<string>
...
-            string[] xParts = x?.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries) ?? Array.Empty<string>();
-            string[] yParts = y?.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries) ?? Array.Empty<string>();
-
-            // Compare each part until we get two parts that are not equal
-            for (int i = 0; i < Math.Min(xParts.Length, yParts.Length); i++)
+            if (x is not null && y is not null)
             {
-                x = xParts[i];
-                y = yParts[i];
+                if (x.Contains(ConfigurationPath.KeyDelimiter) && y.Contains(ConfigurationPath.KeyDelimiter))
```
Comment (tarekgh) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:34]: > if (x.Contains(ConfigurationPath.KeyDelimiter) && y.Contains(ConfigurationPath.KeyDelimiter)) [](http://example.com/codeflow?start=15&length=94)

do you need to keep this check? I think the logic inside the block should take care with that.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 8]
```diff
@@ -29,49 +29,94 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+
+                        int compareResult = Compare(xSpan, ySpan);
+                        if (compareResult != 0)
+                        {
+                            return compareResult;
+                        }
+                    }
+
+                    string[] xParts = x.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries);
+                    string[] yParts = y.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries);
```
Comment (tarekgh) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:77]: why keeping these lines?

**Comment by maryamariyan** [comment]
> Should your benchmarks above be added to dotnet/performance to protect your change from regressions?

I plan to add those. Are you recommending to add them before this PR goes in?

**Comment by danmoseley** [comment]
> I plan to add those. Are you recommending to add them before this PR goes in?

That's your call. Adding them before the main PR (at least say half a day before) has the nice effect of gathering numbers before the change, so you see a nice uptick in the graph when your change goes in, and if it regresses it might possibly be interesting what the original value was. I don't think it matters otherwise.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 9]
```diff
@@ -29,49 +29,94 @@ public class ConfigurationKeyComparer : IComparer<string>
...
-
-            // Compare each part until we get two parts that are not equal
-            for (int i = 0; i < Math.Min(xParts.Length, yParts.Length); i++)
+            if (x is not null && y is not null)
             {
-                x = xParts[i];
-                y = yParts[i];
+                if (x.Contains(ConfigurationPath.KeyDelimiter) && y.Contains(ConfigurationPath.KeyDelimiter))
+                {
+                    int xIndex = 0;
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:36]: I find it easier if instead I use the ReadOnlySpan to "remember" the position where I am parsing instead of using an index.

So instead, you can declare a `xSpan` up here being the whole string and the `while` loop condition can be `!xSpan.IsEmpty && !ySpan.IsEmpty`. The `IndexOf` line just becomes `xSpan.IndexOf(ConfigurationPath.KeyDelimiter)`, and then you don't need to subtract off the `xIndex` in your slices below. The slices become `xSpan.Slice(0, nextXIndex)`. And then at the end, move your spans forward by `xSpan = xSpan.Slice(nextXIndex + 1)`.

Here's an example of what I'm talking about:

[https://github.com/xamarin/xamarin-android/blob/1ff560542f1bac8c7a6d5f4437711917eb4d16d8/src/Mono.Android/Android.Runtime/AndroidRuntime.cs#L474-L485](https://github.com/xamarin/xamarin-android/blob/1ff560542f1bac8c7a6d5f4437711917eb4d16d8/src/Mono.Android/Android.Runtime/AndroidRuntime.cs#L474-L485)

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs (hunk 8 above)
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:77]: It seems like we could just keep a count of x parts and y parts above, and then compare them here instead of splitting again.

**Comment by maryamariyan** [comment]
Found certain use cases for which removing `Split` with `IndexOf` would regress for: e.g. for empty segments, the `Split` API also is taking `RemoveEmptyEntries` option and so a string like `:::` would get and empty parts array.

The replacement function needs to behave similar to `Split`, returning the same count, not place allocation while we traverse one segment at a time to compare against the other string's segment.

One way forward would be to make use of something like the `SpanSplitEnumerator` that was reverted back in this PR https://github.com/dotnet/runtime/pull/37757/files.

**Comment by tarekgh** [comment]
> Seems like StringTokenizer can do the logic I need, will be using that instead [bd43f55/src/libraries/Microsoft.Extensions.Primitives/src/StringTokenizer.cs](https://github.com/dotnet/runtime/blob/bd43f55230d533af326e727366f61cfd3ed0e050/src/libraries/Microsoft.Extensions.Primitives/src/StringTokenizer.cs)

This looks a good idea to use.

**Comment by maryamariyan** [comment]
I tried using `StringTokenizer` and that would give us the allocation improvement we wanted but not time perf benefits. So I ended up using an improved version of `IndexOf` for this fix, so we get perf benefits in both time and allocation.


Without diff:

```
|                                     Method |        Mean |     Error |      StdDev |    Gen 0 |  Gen 1 | Allocated |
|------------------------------------------- |------------:|----------:|------------:|---------:|-------:|----------:|
|         AddChainedConfigurationNoDelimiter |  1,255.4 us |  24.20 us |    50.52 us | 130.8594 | 5.8594 |  1,011 KB |
|               AddChainedConfigurationEmpty | 37,957.7 us | 718.05 us | 1,466.79 us |  76.9231 |      - |  1,010 KB |
|       AddChainedConfigurationWithSplitting |    563.1 us |  11.11 us |    27.88 us |  61.5234 | 5.8594 |    472 KB |
| AddChainedConfigurationWithSplittingLooped |    557.0 us |  11.01 us |    23.69 us |  61.5234 | 5.8594 |    472 KB |
```

With latest PR diff:
```
|                                     Method |        Mean |     Error |    StdDev |   Gen 0 |  Gen 1 | Allocated |
|------------------------------------------- |------------:|----------:|----------:|--------:|-------:|----------:|
|         AddChainedConfigurationNoDelimiter |    880.8 us |  17.44 us |  23.88 us | 18.5547 | 2.9297 |    143 KB |
|               AddChainedConfigurationEmpty | 19,589.8 us | 388.99 us | 878.01 us |       - |      - |    143 KB |
|       AddChainedConfigurationWithSplitting |    422.6 us |   7.76 us |  14.95 us |  4.8828 | 0.4883 |     40 KB |
| AddChainedConfigurationWithSplittingLooped |    425.8 us |   8.40 us |  11.49 us |  4.8828 | 0.4883 |     40 KB |
```

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 10]
```diff
@@ -29,49 +29,111 @@ public class ConfigurationKeyComparer : IComparer<string>
...
         {
-            string[] xParts = x?.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries) ?? Array.Empty<string>();
-            string[] yParts = y?.Split(_keyDelimiterArray, StringSplitOptions.RemoveEmptyEntries) ?? Array.Empty<string>();
+            ReadOnlySpan<char> xSpan = x.AsSpan();
+            ReadOnlySpan<char> ySpan = y.AsSpan();
+
+            if (x == null || y == null)
+            {
+                return (x is null ? 0 : CountPartsIn(xSpan)) - (y is null ? 0 : CountPartsIn(ySpan));
+            }
```
Comment (gfoidl) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:38]: When the string is `null`, then `AsSpan` returns an empty span. So the check for empty span (i.e. string is null) could be moved to `CountPartsIn` then this code becomes:
```suggestion
            ReadOnlySpan<char> xSpan = x.AsSpan();
            ReadOnlySpan<char> ySpan = y.AsSpan();

            if (xSpan.IsEmpty || ySpan.IsEmpty)
            {
                return CountPartsIn(xSpan) - CountPartsIn(ySpan);
            }
```
Saves some branches here.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 11]
```diff
@@ -29,49 +29,111 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+                    return compareResult;
+                }
+
+                xSpan = xSpan.Slice(xSegmentLength);
+                ySpan = ySpan.Slice(ySegmentLength);
+            }
 
+            if (xSpan.IsEmpty)
+            {
+                return ySpan.IsEmpty ? 0 : -CountPartsIn(ySpan);
```
Comment (gfoidl) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:79]: With the above suggestion:
```suggestion
                return -CountPartsIn(ySpan);
```
So when `ySpan.IsEmpty` `0` is returned, hence the `-` doesn't bother us.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 12]
```diff
@@ -29,49 +29,111 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+            }
+
+            return CountPartsIn(xSpan);
+
+            static int CountPartsIn(ReadOnlySpan<char> a)
```
Comment (gfoidl) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:84]: No need to change this local function for the suggestion. Code already works that way.

If you keep the check for `!= null` or `IsEmpty` above, then the `while`-loop could be re-written as `do-while`, because for the first iteration the span won't be empty.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 13]
```diff
@@ -11,7 +12,7 @@ namespace Microsoft.Extensions.Configuration
     /// </summary>
     public class ConfigurationKeyComparer : IComparer<string>
     {
-        private static readonly string[] _keyDelimiterArray = new[] { ConfigurationPath.KeyDelimiter };
+        private static readonly char s_keyDelimiter = ConfigurationPath.KeyDelimiter[0];
```
[the remark this answers is not in the document]
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:14]: I think I would just make this:

```suggestion
        private const char s_keyDelimiter = ':';
```

It's not like this is going to change ever.

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 14]
```diff
@@ -29,49 +29,80 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+                    ySegmentLength = ySpan.Length;
+                }
+
+                int compareResult = Compare(xSpan.Slice(0, xSegmentLength), ySpan.Slice(0, ySegmentLength));
+                if (compareResult != 0)
+                {
+                    return compareResult;
+                }
+
+                xSpan = xSpan.Slice(xSegmentLength);
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:59]: It's a little surprising that in the middle of the path, we know `xSpan.Slice(xSegmentLength)` will have a delimiter at the beginning, and then we slice it off in SkipAheadOnDelimiter.

I guess I would have expected this to check the result of IndexOf twice, once during the slice above, and once here when slicing for the next segment.

```C#
int xDelimiterIndex = xSpan.IndexOf(s_keyDelimiter);
int yDelimiterIndex = ySpan.IndexOf(s_keyDelimiter);

int compareResult = Compare(
    xDelimiterIndex == -1 ? xSpan : xSpan.Slice(0, xDelimiterIndex),
    yDelimiterIndex == -1 ? ySpan : ySpan.Slice(0, yDelimiterIndex));
if (compareResult != 0)
{
    return compareResult;
}

xSpan = xDelimiterIndex == -1 ? default :
    SkipAheadOnDelimiter(xSpan.Slice(xDelimiterIndex + 1));
ySpan = yDelimiterIndex == -1 ? default :
    SkipAheadOnDelimiter(ySpan.Slice(yDelimiterIndex + 1));
```

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 15]
```diff
@@ -29,49 +29,73 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+
+                if (compareResult != 0)
+                {
+                    return compareResult;
+                }
 
-                int value1 = 0;
-                int value2 = 0;
+                xSpan = xDelimiterIndex == -1 ? default :
+                    SkipAheadOnDelimiter(xSpan.Slice(xDelimiterIndex));
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:54]:
```suggestion
                    SkipAheadOnDelimiter(xSpan.Slice(xDelimiterIndex + 1));
```

File: src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs [hunk 16]
```diff
@@ -29,49 +29,73 @@ public class ConfigurationKeyComparer : IComparer<string>
...
+                ySpan = yDelimiterIndex == -1 ? default :
+                    SkipAheadOnDelimiter(ySpan.Slice(yDelimiterIndex));
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationKeyComparer.cs:56]:
```suggestion
                    SkipAheadOnDelimiter(ySpan.Slice(yDelimiterIndex + 1));
```

**Review by eerhardt — COMMENTED** [review]
We know that `xDelimiterIndex` is at a delimiter. There is no reason to slice to that location, you can skip past it.

**Review by eerhardt — APPROVED** [review]
This looks good to me. Thanks for the great work here, @maryamariyan.
