### PR TITLE
Have COND_JUMP handling check for gtEffectiveVal

### LINKED ISSUE #103600: JIT:  Assertion failed 'cond == test->AsOp()->gtOp1' during 'Update flow graph early pass'
```csharp
// Generated by Fuzzlyn v1.6 on 2024-06-16 15:10:23
// Run on X64 Windows
// Seed: 6886681321438315426
// Reduced from 30.1 KiB to 0.3 KiB in 00:01:11
// Hits JIT assert in Release:
// Assertion failed 'cond == test->AsOp()->gtOp1' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Update flow graph early pass' (IL size 27; hash 0xade6b36b; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\fgopt.cpp Line: 5447
// 
using System.Runtime.CompilerServices;

public class Program
{
    public static void Main()
    {
        ulong[] vr0 = default(ulong[]);
        if (0 > vr0[0])
        {
            vr0 = vr0;
        }
        else
        {
            vr0 = new ulong[]{0};
        }

        vr0[0] = vr0[0];
    }
}
```

cc @amanasifkhalid, looks like there's still some of these cases hanging around.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/103600

### CODE REVIEW

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -7299,15 +7299,17 @@ void Compiler::impImportBlockCode(BasicBlock* block)
...
                 op1 = gtFoldExpr(op1);
 
                 /* Try to fold the really simple cases like 'iconst *, ifne/ifeq'*/
                 /* Don't make any blocks unreachable in import only mode */
 
-                if (op1->gtOper == GT_CNS_INT)
+                GenTree* effectiveOp1 = op1->gtEffectiveVal();
+
+                if (effectiveOp1->OperIs(GT_CNS_INT))
                 {
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp:7313]: Doesn't this drop the side effects silently now?

Comment (tannergooding) [reply src/coreclr/jit/importer.cpp:7313]: or rather, just wrap the comma in an unused node so we don't need to worry about chains of commas and then append

**Review by jakobbotsch — APPROVED** [review]
