### PR TITLE
Delete code related to CompilationRelaxations.NoStringInterning

### LINKED ISSUE #53726: JIT: Throw statement triggers: "has ldstr VM restriction"
### Description

The JIT is not able to inline this method because of the ` throw new FormatException("Bad variable size int");` statement with the following error: 

```
generic !!0  (value class System.ReadOnlySpan`1<unsigned int8>,int32,int32&)
Fail Reason: has ldstr VM restriction
```

A cleanup version of the offending code:

```
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static T ReadVariableSizeInt<T>(ReadOnlySpan<byte> buffer, int pos, out int offset) where T : unmanaged
        {
            if (typeof(T) == typeof(int) || typeof(T) == typeof(uint))
            {
                int ui = 0;

                offset = 0;

                byte b = buffer[pos + 0];
                ui |= (b & 0x7F);
                offset++;
                if ((b & 0x80) == 0)
                    goto End;

                b = buffer[pos + 1];
                ui |= (b & 0x7F) << 7;
                offset++;
                if ((b & 0x80) == 0)
                    goto End;

                b = buffer[pos + 2];
                ui |= (b & 0x7F) << 14;
                offset++;
                if ((b & 0x80) == 0)
                    goto End;

                b = buffer[pos + 3];
                ui |= (b & 0x7F) << 21;
                offset++;
                if ((b & 0x80) == 0)
                    goto End;

                b = buffer[pos + 4];
                ui |= (b & 0x7F) << 28;
                offset++;
                if ((b & 0x80) != 0)
                    throw new FormatException("Bad variable size int");

                End: return (T)(object)ui;
            }

            throw new NotSupportedException($"The type {nameof(T)} is not supported to be written.");
        }
```

### Configuration
.Net 5.0 

### Analysis
It sounds to me that because the offending line is a throw statement and is to be marked as cold, that restriction should not apply.

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
The code that was dealing with this relaxation was deleted in https://github.com/dotnet/runtime/pull/57693 last year (ceeload.cpp, line 4006). We still had code that was telling RyuJIT not to inline string literals across modules if `NoStringInterning` is active because it might be observable, but since fragile NGen got deleted, I don't believe it's actually observable anymore and we could have deleted this together with fragile NGen support.

Closes #53726 - we no longer need to worry about loosening the restriction - we just drop it all.

### CODE REVIEW

File: src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs [hunk 1]
```diff
@@ -501,10 +501,6 @@ public enum CorInfoInlineTypeCheckSource
     public enum CorInfoInlineRestrictions
```
Comment (jkotas) [inline src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs:501]: None of these restrictions are used anymore. Delete the whole thing?

**Review by jkotas — APPROVED** [review]
LGTM otherwise

File: src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs (hunk 1 above)
Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs]: Done. I've not done an actual JitInterface change to drop the unused parameter. I can do that to if needed at this point or it can wait for the next round of cleanups in JitInterface (e.g. when IL verification in RyuJIT is wiped).

File: src/coreclr/jit/importer.cpp [hunk 2]
```diff
@@ -8645,9 +8645,6 @@ var_types Compiler::impImportCall(OPCODE                  opcode,
                    opcodeNames[opcode], callInfo->kind, varTypeName(callRetTyp), structSize);
         }
 #endif
-        // This should be checked in impImportBlockCode.
-        assert(!compIsForInlining() || !(impInlineInfo->inlineCandidateInfo->dwRestrictions & INLINE_RESPECT_BOUNDARY));
```
Comment (jkotas) [inline src/coreclr/jit/importer.cpp:8649]: I think you should be also able delete `dwRestrictions` field in `inlineCandidateInfo` and on JIT/EE interface.

File: src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs (hunk 1 above)
Comment (jkotas) [reply src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs]: I would do it now.

**Comment by EgorBo** [comment]
Wow, I somehow missed this one, does it mean we can now inline methods with string literals from different assemblies? 🎉 🎉

**Comment by danmoseley** [comment]
> Wow, I somehow missed this one, does it mean we can now inline methods with string literals from different assemblies? 🎉 🎉

Barely, in fact entirely, unrelated, it would be nice if we didn't have so many resource strings duplicated across the shared framework assemblies. Some strings are duplicated 20 times.

**Comment by MichalStrehovsky** [comment]
> Wow, I somehow missed this one, does it mean we can now inline methods with string literals from different assemblies? 🎉 🎉

I hope so!

**Comment by EgorBo** [comment]
Most likely all improvements in this one https://github.com/dotnet/perf-autofiling-issues/issues/3263 are related

**Comment by EgorBo** [comment]
> > Wow, I somehow missed this one, does it mean we can now inline methods with string literals from different assemblies? 🎉 🎉
> 
> I hope so!

I double checked, it does work :)

**Comment by EgorBo** [comment]
Arm64 improvements: https://github.com/dotnet/perf-autofiling-issues/issues/3289

**Comment by EgorBo** [comment]
Arm64 improvements https://github.com/dotnet/perf-autofiling-issues/issues/3436
