### PR TITLE
Fix validation on build

### LINKED ISSUE #87429: Service Provider cannot resolve transient service from the Root scope if the `ValidateOnBuild` option is enabled
### Description

Service Provider cannot resolve transient service from the Root scope if the `ValidateOnBuild` option is enabled.

### Reproduction Steps

```c#
interface IBar {}
class Bar1 : IBar {}
class Bar2 : IBar {}

services.AddScoped<IBar, Bar1>();
services.AddTransient<IBar, Bar2>();

var sp = services.BuildServiceProvider(new ServiceProviderOptions { ValidateScopes = true, ValidateOnBuild = true });
Debug.Assert(sp.GetService<IBar>() is Bar2)
```

### Expected behavior

Debug.Assert(sp.GetService<IBar>() is Bar2)

### Actual behavior

Thrown Exception

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mapogolions**
Fixes https://github.com/dotnet/runtime/issues/87429

Let's look at the following example

```c#
interface IBar {}
class Bar1 : IBar {}
class Bar2 : IBar {}

services.AddScoped<IBar, Bar1>();  // Slot: 1
services.AddTransient<IBar, Bar2>(); // Slot: 0

var sp = services.BuildServiceProvider(validateScopes: true);
Debug.Assert(sp.GetService<IBar>() is Bar2)
```
The last implementation will be resolved by convention. For more details see the `CallSiteFactory` class and the `DefaultSlot` property. The scope validation is fine with a service lifetime (GetService for Transient service on the Root scope).
But the behavior breaks when we set the `ValidateOnBuild` property to 'true'. Please see unit tests that reproduce the issue.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteValidator.cs [hunk 1]
```diff
@@ -97,6 +98,12 @@ public void ValidateResolution(Type serviceType, IServiceScope scope, IServiceSc
 
         protected override Type? VisitFactory(FactoryCallSite factoryCallSite, CallSiteValidatorState state) => null;
 
+        private static ServiceCacheKey GetCacheKey(ServiceCallSite callSite)
+        {
+            return callSite.Cache.Key.Equals(ServiceCacheKey.Empty)
```
Comment (steveharter) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteValidator.cs:103]: The call to `callSite.Cache.Key` should only ever occur once for perf.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceProvider.cs [hunk 2]
```diff
@@ -173,10 +171,20 @@ private void ValidateService(ServiceDescriptor descriptor)
...
+                    };
                 }
 
-                return _engine.RealizeService(callSite);
+                Func<ServiceProviderEngineScope, object?> realizedService = _engine.RealizeService(callSite);
+                return scope =>
+                {
+                    OnResolve(callSite, scope);
+                    DependencyInjectionEventSource.Log.ServiceResolved(this, serviceType);
+                    return realizedService.Invoke(scope);
```
Comment (steveharter) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceProvider.cs:186]: `.Invoke()` is unnecessary.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderValidationTests.cs [hunk 3]
```diff
@@ -97,6 +99,49 @@ public void GetService_Throws_WhenGetServiceForScopedServiceIsCalledOnRootViaTra
...
+
+            // Act
+            var actual = serviceProvider.GetService<IBar>();
+
+            // Assert
+            Assert.IsType<Bar3>(actual);
+        }
+
+        [Fact]
+        public void ScopeValidation_ShouldBeAbleToDistingushGenericCollections_WhenGetServiceIsCalledOnRoot()
```
Comment (steveharter) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderValidationTests.cs:125]: It appears this passes without the changes here. Is that intentional?

**Comment by steveharter** [comment]
> Let's look at the following example

Please add a corresponding issue and link to it from this PR. Thanks

**Comment by mapogolions** [comment]
Issue #87429

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderValidationTests.cs (hunk 3 above)
Comment (mapogolions) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderValidationTests.cs:125]: Yes, It is intentional. It tests the `GetCacheKey()` private method that replaces `ResultCache.None` for services. (For instance, `IEnumerable<Foo>` and `IEnumerable<Bar>` have the same `ResultCache` that is equal to `ResultCache.None` if at least one of the `Foo` and at least one `Bar` has transient lifetime)

**Comment by steveharter** [comment]
Failure on runtime known issue.

**Review by steveharter — APPROVED** [review]

**Comment by steveharter** [comment]
Thanks @mapogolions
