### PR TITLE
Limit doublemapper maximum size

### LINKED ISSUE #117819: doublemapping.cpp causes crash with SIGXFSZ if file size limits <2TB are in effect
### Description

src/coreclr/minipal/Unix/doublemapping.cpp does:

> if (ftruncate(fd, MaxDoubleMappedSize) == -1)

where

> #ifdef TARGET_64BIT
> static const off_t MaxDoubleMappedSize = 2048ULL*1024*1024*1024;
> #else
> static const off_t MaxDoubleMappedSize = UINT_MAX;
> #endif

This causes the process to fail with SIGXFSZ if a file size limit has been imposed via setrlimit()/prlimit().

### Reproduction Steps

Set a file size limit (e.g., "ulimit -S -f 25165824" from bash).
Run any program which invokes VMToOSInterface::CreateDoubleMemoryMapper().

### Expected behavior

Process continues normally.

### Actual behavior

Process dies with SIGXFSZ.

### Regression?

Issue was observed in the Visual Studio Code C/C++ extension; problem occurs in ms-vscode.cpptools-1.23.5-linux-x64 but was not present in ms-vscode.cpptools-1.22.11-linux-x64 (cf. https://github.com/microsoft/vscode-cpptools/issues/13768).
See also https://github.com/microsoft/vscode/issues/251037 , in VS Code's vsce-sign program.
I presume these projects are embedding their libmscordaccore.so libraries from dotnet/runtime.

### Known Workarounds

_No response_

### Configuration

AlmaLinux 8.10 x86_64.

### Other information

Issue could be addressed by calling getrlimit(RLIMIT_FSIZE) and capping the parameter to ftruncate() at the soft limit.

### PR DESCRIPTION
**Pull request by janvorli**
The double mapping currently sets the maximum size of the double mapped memory to 2TB. However, that causes the runtime to fail to start if there is a rlimit for max file size set to a smaller value.

This change fixed the problem by clipping the max double mapped memory size by that rlimit and also uses much more conservative size even without the file size limit set. It is now set to the total amount of physical memory by default and also clipped by the virtual memory rlimit.

Close #117819

### CODE REVIEW

File: src/coreclr/minipal/Unix/doublemapping.cpp [hunk 1]
```diff
@@ -81,14 +82,46 @@ bool VMToOSInterface::CreateDoubleMemoryMapper(void** pHandle, size_t *pMaxExecu
...
+    if (pages != -1)
+    {
+        long pageSize = sysconf(_SC_PAGE_SIZE);
+        if (pageSize != -1)
+        {
+            maxDoubleMappedMemorySize = (off_t)pages * pageSize;
+        }
+    }
+
+    // Clip the maximum double mapped memory size to the virtual address space limit
```
Comment (jkotas) [inline src/coreclr/minipal/Unix/doublemapping.cpp]: Should this be clipped to a fraction of the virtual address space limit? I would expect that the double mapper is still going to fail if it tries to allocate virtual address space limit worth of space.

Comment (janvorli) [reply src/coreclr/minipal/Unix/doublemapping.cpp]: Makes sense. GC actually clips its usage to 1/2 of the VA space, so I guess using 1/4 as a limit here would probably be a good heuristic.

**Review by jkotas — APPROVED** [review]

**Review by mangod9 — APPROVED** [review]
