### PR TITLE
Arm64: Pass the small size accurately to emitIns_valid_imm_for_ldst_offset

### LINKED ISSUE #68536: Assertion failed '!"Instruction cannot be encoded: IF_LS_2B"' during 'Generate code'
Antigen tried reducing it but at one point, it was too slow to reduce. Hopefully it won't be that bad to reduce the test to smaller repro.

```c#
// Found by Antigen
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
        public sbyte sbyte_0;
        public ulong ulong_1;
    }
    public struct S2
    {
        public struct S2_D1_F1
        {
            public uint uint_2;
            public float float_3;
            public uint uint_4;
        }
    }
    static bool s_bool_5 = false;
    static byte s_byte_6 = 1;
    static char s_char_7 = 'D';
    static decimal s_decimal_8 = 0.0833333333333333333333333333m;
    static double s_double_9 = 4;
    static short s_short_10 = 4;
    static int s_int_11 = 0;
    static long s_long_12 = 5;
    static sbyte s_sbyte_13 = 7;
    static float s_float_14 = 1.1f;
    static string s_string_15 = "5E049";
    static ushort s_ushort_16 = 2;
    static uint s_uint_17 = 69;
    static ulong s_ulong_18 = 69;
    static S1 s_s1_19 = new S1();
    static S2.S2_D1_F1 s_s2_s2_d1_f1_20 = new S2.S2_D1_F1();
    static S2 s_s2_21 = new S2();
    bool bool_22 = true;
    byte byte_23 = 5;
    char char_24 = 'E';
    decimal decimal_25 = 2.0449438202247191011235955056m;
    double double_26 = 1.1666666666666667;
    short short_27 = 5;
    int int_28 = 2;
    long long_29 = 2;
    sbyte sbyte_30 = 5;
    float float_31 = -1.882353f;
    string string_32 = "J0O3C";
    ushort ushort_33 = 2;
    uint uint_34 = 2;
    ulong ulong_35 = 1;
    S1 s1_36 = new S1();
    S2.S2_D1_F1 s2_s2_d1_f1_37 = new S2.S2_D1_F1();
    S2 s2_38 = new S2();
    static int s_loopInvariant = 9;
    private static List<string> toPrint = new List<string>();
    [MethodImpl(MethodImplOptions.NoInlining)]
    public bool LeafMethod0()
    {
        unchecked
        {
            return ((bool)(((bool)(bool_22 = ((bool)(s_bool_5 = ((bool)(s_s2_s2_d1_f1_20.float_3 == s_s2_s2_d1_f1_20.float_3)))))) || ((bool)(((ushort)(s_ushort_16 / ((ushort)((((ushort)(ushort_33 ^= s_ushort_16))) + 19)))) == ((ushort)(((ushort)(ushort_33 - ushort_33)) + ((ushort)(ushort_33 % ((ushort)((ushort_33) + 5))))))))));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public byte LeafMethod1()
    {
        unchecked
        {
            return ((byte)(((byte)(s_byte_6 &= ((byte)(byte_23 ^= ((byte)(s_byte_6 % ((byte)((byte_23) + 42)))))))) + ((byte)(((byte)(((byte)(s_byte_6 -= s_byte_6)) * byte_23)) + ((byte)(((byte)(byte_23 + s_byte_6)) - ((byte)(s_byte_6 + byte_23))))))));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public decimal LeafMethod3()
    {
        unchecked
        {
            return decimal_25;
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public double LeafMethod4()
    {
        unchecked
        {
            return ((double)(s_double_9 % ((double)((((double)(s_double_9 /= ((double)((s_double_9) + 84))))) + 3))));
        }
    }
    public short LeafMethod5()
    {
        unchecked
        {
            return ((short)(short_27 * ((short)(((short)(((short)(short_27 <<= s_int_11)) >> int_28)) >> ((int)(int_28 + ((int)(s_int_11 << 4))))))));
        }
    }
    public int LeafMethod6()
    {
        unchecked
        {
            return ((int)(int_28 -= int_28));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public long LeafMethod7()
    {
        unchecked
        {
            return ((long)(((long)(((long)(long_29 % ((long)((((long)(long_29 + s_long_12))) + 72)))) & ((long)(long_29 -= s_long_12)))) & ((long)(((long)(((long)(s_long_12 * long_29)) - ((long)(s_long_12 + s_long_12)))) & ((long)(((long)(long_29 + s_long_12)) & s_long_12))))));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public sbyte LeafMethod8()
    {
        unchecked
        {
            return ((sbyte)(sbyte_30 >>= ((int)(s_int_11 = ((int)(((int)(int_28 &= LeafMethod6())) | int_28))))));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public float LeafMethod9()
    {
        unchecked
        {
            return ((float)(((float)(((float)(((float)(s2_s2_d1_f1_37.float_3 % ((float)((float_31) + 94)))) - ((float)(s_float_14 + s_s2_s2_d1_f1_20.float_3)))) / ((float)((((float)(((float)(s_float_14 - s_s2_s2_d1_f1_20.float_3)) - ((float)(float_31 + 4.02439f))))) + 38)))) % ((float)((float_31) + 29))));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public ushort LeafMethod11()
    {
        unchecked
        {
            return ((ushort)(((ushort)(((ushort)(ushort_33 |= ((ushort)(2 - ushort_33)))) - ((ushort)(((ushort)(ushort_33 - ushort_33)) & ((ushort)(ushort_33 / ((ushort)((s_ushort_16) + 24)))))))) / ((ushort)((((ushort)(((ushort)(((ushort)(s_ushort_16 += s_ushort_16)) * ((ushort)(s_ushort_16 - ushort_33)))) / ((ushort)((((ushort)(s_ushort_16 + s_ushort_16))) + 37))))) + 45))));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public uint LeafMethod12()
    {
        unchecked
        {
            return ((uint)(((uint)(s2_s2_d1_f1_37.uint_4 = s_s2_s2_d1_f1_20.uint_2)) + ((uint)(((uint)(((uint)(s2_s2_d1_f1_37.uint_2 | s_s2_s2_d1_f1_20.uint_2)) ^ ((uint)(s_s2_s2_d1_f1_20.uint_4 * s2_s2_d1_f1_37.uint_4)))) + ((uint)(s_uint_17 - s_s2_s2_d1_f1_20.uint_2))))));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public ulong LeafMethod13()
    {
        unchecked
        {
            return ((ulong)(((ulong)(((ulong)(((ulong)(ulong_35 - s_ulong_18)) - ((ulong)(s1_36.ulong_1 % ((ulong)((s1_36.ulong_1) + 49)))))) - ((ulong)(((ulong)(s1_36.ulong_1 | s_ulong_18)) - ((ulong)(s1_36.ulong_1 & 5)))))) / ((ulong)((((ulong)(2 * ((ulong)(((ulong)(s1_36.ulong_1 + s_ulong_18)) + ((ulong)(s_ulong_18 /= ((ulong)((s_s1_19.ulong_1) + 40))))))))) + 45))));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public S1 LeafMethod14()
    {
        unchecked
        {
            return s1_36;
        }
    }
    public S2.S2_D1_F1 LeafMethod15()
    {
        unchecked
        {
            return s_s2_s2_d1_f1_20;
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public S2 LeafMethod16()
    {
        unchecked
        {
            return s_s2_21;
        }
    }
    public ulong Method1(long p_long_39, out byte p_byte_40, int p_int_41, S2.S2_D1_F1 p_s2_s2_d1_f1_42, long p_long_43)
    {
        unchecked
        {
            bool bool_44 = true;
            byte byte_45 = 1;
            char char_46 = '3';
            decimal decimal_47 = 1m;
            double double_48 = 0.020618556701030927;
            short short_49 = 2;
            int int_50 = -2;
            long long_51 = 2;
            sbyte sbyte_52 = 2;
            float float_53 = 2f;
            string string_54 = "5";
            ushort ushort_55 = 2;
            uint uint_56 = 5;
            ulong ulong_57 = 4;
            S1 s1_58 = new S1();
            S2.S2_D1_F1 s2_s2_d1_f1_59 = new S2.S2_D1_F1();
            S2.S2_D1_F1 s2_s2_d1_f1_60 = s2_s2_d1_f1_59;
            S2 s2_61 = new S2();
            p_byte_40 = ((byte)(((byte)(byte_45 %= ((byte)((((byte)(((byte)(LeafMethod1() - byte_23)) + ((byte)(byte_23 ^= s_byte_6))))) + 23)))) ^ ((byte)(byte_23 % ((byte)((((byte)(s_byte_6 += ((byte)(s_byte_6 & LeafMethod1()))))) + 18))))));
            return ((ulong)(((ulong)(((ulong)(s1_36.ulong_1 <<= s_int_11)) % ((ulong)((s1_36.ulong_1) + 16)))) - s1_36.ulong_1));
        }
    }
    public S2 Method4(out S1 p_s1_110, out double p_double_111, S1 p_s1_112)
    {
        unchecked
        {
            bool bool_113 = false;
            byte byte_114 = 5;
            char char_115 = '1';
            decimal decimal_116 = 2.0512820512820512820512820513m;
            double double_117 = -0.9487179487179487;
            short short_118 = 0;
            int int_119 = -2;
            long long_120 = 5;
            sbyte sbyte_121 = 0;
            float float_122 = 2.0555556f;
            string string_123 = "WVOC35BP";
            ushort ushort_124 = 1;
            uint uint_125 = 2;
            ulong ulong_126 = 69;
            S1 s1_127 = new S1();
            S2.S2_D1_F1 s2_s2_d1_f1_128 = new S2.S2_D1_F1();
            S2 s2_129 = new S2();
            S2 s2_130 = s2_129;
            p_s1_110 = s1_36;
            p_double_111 = ((double)(s_double_9 -= ((double)(double_26 = ((double)(((double)(LeafMethod4() % ((double)((s_double_9) + 95)))) / ((double)((LeafMethod4()) + 79))))))));
            if (s_bool_5)
            {
                int __loopvar4 = s_loopInvariant;
                for (; int_28 < (((int)(s_int_11 |= ((int)(s_int_11 -= ((int)(((int)(int_28 - 5)) << int_28))))))); int_28++)
                {
                    if (__loopvar4 > s_loopInvariant + 3)
                        break;
                    int __loopvar1 = s_loopInvariant;
                    int __loopvar2 = s_loopInvariant;
                    ulong_35 >>= ((int)(s_int_11 += ((int)(((int)(s_int_11 |= int_28)) | ((int)(((int)(int_119 % ((int)((int_119) + 16)))) << ((int)(s_int_11 * int_119))))))));
                    decimal_116 += ((decimal)(s_decimal_8 %= ((decimal)((s_decimal_8) + 87))));
                    LeafMethod14();
                    int __loopvar3 = s_loopInvariant - 6;
                    switch (((long)(((long)(long_29 <<= ((int)(int_28 -= ((int)(int_28 >>= LeafMethod6())))))) ^ ((long)(long_120 + long_120)))))
                    {
                        case 69:
                        {
                            s_uint_17 ^= ((uint)(uint_34 >>= ((int)(((int)(int_28 |= ((int)(int_28 % ((int)((s_int_11) + 72)))))) - ((int)(69 / ((int)((((int)(LeafMethod6() >> LeafMethod6()))) + 55))))))));
                            s_decimal_8 += ((decimal)(LeafMethod3() % ((decimal)((((decimal)(((decimal)(((decimal)(decimal_25 /= ((decimal)((LeafMethod3()) + 23)))) * ((decimal)(LeafMethod3() / ((decimal)((decimal_116) + 36)))))) * ((decimal)(decimal_25 = LeafMethod3()))))) + 64))));
                            Method1(-1, out byte_23, ((int)(((int)(((int)(LeafMethod6() * LeafMethod6())) % ((int)((((int)(int_119 & LeafMethod6()))) + 53)))) / ((int)((int_28) + 24)))), s2_s2_d1_f1_37, ((long)(((long)(((long)(long_120 - LeafMethod7())) ^ s_long_12)) + long_29)));
                            ulong_126 = ((ulong)(((ulong)(((ulong)(((ulong)(s_s1_19.ulong_1 -= s_ulong_18)) & ((ulong)(s1_36.ulong_1 | ulong_35)))) + ((ulong)(((ulong)(LeafMethod13() * 1)) % ((ulong)((s_ulong_18) + 6)))))) ^ ulong_35));
                            break;
                        }
                        default:
                        {
                            LeafMethod8();
                            break;
                        }
                    }
                }
                LeafMethod7();
                short short_132 = ((short)(((short)(short_27 -= ((short)(s_short_10 + -1)))) * ((short)(short_118 >> ((int)(((int)(-1 >> int_28)) % ((int)((s_int_11) + 37))))))));
                Log("short_132", short_132);
            }
            else
            {
                s1_36.ulong_1 |= ((ulong)(s1_127.ulong_1 *= 2));
                s_uint_17 |= ((uint)(s_s2_s2_d1_f1_20.uint_4 |= s2_s2_d1_f1_37.uint_2));
                long long_133 = LeafMethod7();
                int_28 <<= ((int)(((int)(((int)(((int)(int_119 + LeafMethod6())) * LeafMethod6())) >> int_119)) ^ ((int)(((int)(int_119 += ((int)(int_119 |= s_int_11)))) * ((int)(int_119 * ((int)(s_int_11 << int_119))))))));
                p_double_111 = ((double)(double_117 + ((double)(((double)(s_double_9 *= ((double)(s_double_9 + p_double_111)))) * ((double)(((double)(s_double_9 + double_26)) / ((double)((((double)(p_double_111 *= p_double_111))) + 75))))))));
                int __loopvar6 = s_loopInvariant;
                for (; (__loopvar6 != s_loopInvariant + 12);)
                {
                    if (((bool)(((int)(int_28 = ((int)(((int)(s_int_11 = 5)) & ((int)(int_28 * s_int_11)))))) > ((int)(((int)(int_119 %= ((int)((((int)(5 % ((int)((s_int_11) + 45))))) + 30)))) << int_28)))))
                    {
                        s_decimal_8 *= ((decimal)(LeafMethod3() + ((decimal)(((decimal)(LeafMethod3() % ((decimal)((((decimal)(LeafMethod3() % ((decimal)((decimal_25) + 6))))) + 55)))) / ((decimal)((((decimal)(((decimal)(69.010101010101010101010101010m + decimal_25)) - ((decimal)(s_decimal_8 + decimal_116))))) + 99))))));
                        bool bool_135 = bool_113;
                    }
                    else
                    {
                        s2_s2_d1_f1_37.uint_2 = ((uint)(s_uint_17 = LeafMethod12()));
                        s_byte_6 >>= ((int)(((int)(((int)(s_int_11 & ((int)(LeafMethod6() | s_int_11)))) * LeafMethod6())) << ((int)(((int)(s_int_11 = LeafMethod6())) % ((int)((((int)(((int)(LeafMethod6() % ((int)((s_int_11) + 13)))) % ((int)((LeafMethod6()) + 42))))) + 68))))));
                        LeafMethod15();
                    }
                    if (LeafMethod0())
                    {
                        s_s1_19.sbyte_0 /= ((sbyte)((((sbyte)(sbyte_121 = ((sbyte)(((sbyte)(((sbyte)(sbyte_121 >> int_28)) * ((sbyte)(s_s1_19.sbyte_0 % ((sbyte)((LeafMethod8()) + 6)))))) - ((sbyte)(sbyte_30 >>= ((int)(s_int_11 << s_int_11))))))))) + 25));
                        int_119 = ((int)(((int)(int_119 &= ((int)(s_int_11 = ((int)(int_28 >>= int_28)))))) >> ((int)(s_int_11 /= ((int)((((int)(((int)(5 ^ LeafMethod6())) * ((int)(LeafMethod6() ^ int_28))))) + 93))))));
                        Method1(((long)(long_29 + ((long)(((long)(LeafMethod7() ^ LeafMethod7())) >> ((int)(int_28 * s_int_11)))))), out byte_23, ((int)(((int)(((int)(int_28 / ((int)((int_119) + 78)))) | ((int)(int_119 ^ 69)))) << ((int)(((int)(int_28 |= s_int_11)) * int_119)))), s2_s2_d1_f1_37, ((long)(long_133 >> ((int)(((int)(int_119 >> s_int_11)) | s_int_11)))));
                    }
                    else
                    {
                        s_int_11 ^= ((int)(((int)(int_28 ^= ((int)(((int)(int_119 % ((int)((int_28) + 97)))) + -1)))) / ((int)((((int)(LeafMethod6() / ((int)((((int)(((int)(int_28 += LeafMethod6())) >> ((int)(s_int_11 % ((int)((LeafMethod6()) + 96))))))) + 87))))) + 1))));
                        long_29 /= ((long)((((long)(long_29 *= ((long)(LeafMethod7() % ((long)((((long)(s_long_12 ^= ((long)(long_133 /= ((long)((long_120) + 82))))))) + 89))))))) + 25));
                        p_double_111 -= ((double)(LeafMethod4() + ((double)(double_26 %= ((double)((((double)(s_double_9 %= ((double)((LeafMethod4()) + 42))))) + 61))))));
                        decimal_116 -= ((decimal)(((decimal)(((decimal)(decimal_116 += ((decimal)(s_decimal_8 + decimal_116)))) + ((decimal)(((decimal)(LeafMethod3() - LeafMethod3())) - ((decimal)(s_decimal_8 * decimal_116)))))) / ((decimal)((decimal_116) + 10))));
                        LeafMethod14();
                    }
                    s_long_12 <<= ((int)(int_119 /= ((int)((LeafMethod6()) + 22))));
                    s_ushort_16 -= ((ushort)(ushort_33 <<= ((int)(int_28 ^= ((int)(s_int_11 = int_119))))));
                    s_ushort_16 |= ((ushort)(((ushort)(((ushort)(((ushort)(LeafMethod11() + ushort_33)) + ((ushort)(s_ushort_16 / ((ushort)((LeafMethod11()) + 45)))))) | ((ushort)(((ushort)(s_ushort_16 + ushort_33)) % ((ushort)((((ushort)(ushort_33 - ushort_33))) + 79)))))) * LeafMethod11()));
                    LeafMethod14();
                    double_26 = ((double)(LeafMethod4() % ((double)((((double)(((double)(p_double_111 += ((double)(double_26 + LeafMethod4())))) - double_26))) + 36))));
                    int __loopvar5 = s_loopInvariant + 6, __loopSecondaryVar5_0 = s_loopInvariant;
                }
            }
            LeafMethod16();
            Method1(long_29, out byte_23, ((int)(((int)(((int)(s_int_11 << LeafMethod6())) << int_119)) ^ ((int)(((int)(LeafMethod6() + int_119)) ^ ((int)(s_int_11 % ((int)((s_int_11) + 32)))))))), s2_s2_d1_f1_37, ((long)(((long)(((long)(long_120 % ((long)((s_long_12) + 4)))) | long_120)) % ((long)((((long)(s_long_12 &= long_29))) + 34)))));
            Log("p_s1_112", p_s1_112);
            Log("bool_113", bool_113);
            Log("p_double_1", p_double_111);
            Log("string_123", string_123);
            Log("ushort_124", ushort_124);
            Log("ulong_126", ulong_126);
            Log("s2_s2_d1_f", s2_s2_d1_f1_128);
            Log("s2_130", s2_130);
            return s2_129;
        }
    }
    public void Method0()
    {
        unchecked
        {
            bool bool_136 = true;
            byte byte_137 = 126;
            char char_138 = 'H';
            decimal decimal_139 = -0.9545454545454545454545454545m;
            double double_140 = -1.9733333333333334;
            short short_141 = 0;
            int int_142 = 5;
            long long_143 = 5;
            sbyte sbyte_144 = -1;
            float float_145 = 4.0163937f;
            string string_146 = "CINM6";
            ushort ushort_147 = 69;
            uint uint_148 = 1;
            ulong ulong_149 = 4;
            S1 s1_150 = new S1();
            S1 s1_151 = s1_150;
            S2.S2_D1_F1 s2_s2_d1_f1_152 = new S2.S2_D1_F1();
            S2 s2_153 = new S2();
            if (((bool)(s_bool_5 = ((bool)(bool_22 = ((bool)(((bool)(LeafMethod1() <= byte_23)) || ((bool)(LeafMethod7() <= LeafMethod7())))))))))
{}            else
            {
                int __loopvar5 = s_loopInvariant;
            }
            int __loopvar7 = s_loopInvariant;
            s2_153 = Method4(out s1_150, out double_140, s1_36);
            Log("s1_151.ulo", s1_151.ulong_1);
            Log("s2_153", s2_153);
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
        PrintLog();
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void Log(string varName, object varValue)
    {
        toPrint.Add($"{varName}={varValue}");
    }
    public static void PrintLog()
    {
        foreach (var entry in toPrint)
        {
            Console.WriteLine(entry);
        }
    }
}
/*
Environment:

set COMPlus_TieredCompilation=1
set COMPlus_TC_OnStackReplacement_InitialCounter=1
set COMPlus_AltJitName=clrjit_universal_arm64_x64.dll
set COMPlus_AltJit=Method4

Assert failure(PID 31608 [0x00007b78], Thread: 30564 [0x7764]): Assertion failed '!"Instruction cannot be encoded: IF_LS_2B"' in 'TestClass:Method4(byref,byref,S1):S2:this' during 'Generate code' (IL size 2675; hash 0x97446e08; Tier1-OSR)
    File: D:\git\dotnet-runtime\src\coreclr\jit\emitarm64.cpp Line: 5645
    Image: d:\git\dotnet-runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
*/

```

### PR DESCRIPTION
**Pull request by kunalspathak**
Pass the correct size of instruction to determine if the immediate will fit in the instruction or not.

Fixes: https://github.com/dotnet/runtime/issues/68536

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/codegenarm64.cpp [hunk 1]
```diff
@@ -335,10 +335,14 @@ bool CodeGen::genInstrWithConstant(instruction ins,
             break;
 
         case INS_ldrsb:
-        case INS_ldrsh:
-        case INS_ldrsw:
         case INS_ldrb:
+            immFitsInIns = emitter::emitIns_valid_imm_for_ldst_offset(imm, EA_1BYTE);
```
Comment (BruceForstall) [inline src/coreclr/jit/codegenarm64.cpp:339]: Why is `size` not already EA_1BYTE in this case?

Comment (kunalspathak) [reply src/coreclr/jit/codegenarm64.cpp:339]: It is passed by the caller `genEnregisterOSRArgsAndLocals()` using `emitActualTypeSize(lclTyp)`, which for `TYP_BYTE` returns `EA_4BYTE`.

Comment (BruceForstall) [reply src/coreclr/jit/codegenarm64.cpp:339]: It seems like the bug is in `genEnregisterOSRArgsAndLocals()` -- it appears lclTyp is TYP_BYTE so it is asking for a ldrb but it passes the actual size (4) instead of size 1. It looks like lclTyp can only be small for OSR local struct fields. Maybe it should use `const emitAttr  size = emitTypeSize(lclTyp);` instead of using `emitActualTypeSize()`? @AndyAyersMS ?

Comment (AndyAyersMS) [reply src/coreclr/jit/codegenarm64.cpp:339]: Yes, I think we should be using `emitTypeSize` in `genEnregisterOSRArgsAndLocals`.

Comment (kunalspathak) [reply src/coreclr/jit/codegenarm64.cpp:339]: > It looks like lclTyp can only be small for OSR local struct fields.

Why is the reasoning behind it?

> `emitTypeSize`

I never understood the difference between `emitTypeSize` and `emitActualTypeSize()`. In which scenarios should we use one over other?

Comment (kunalspathak) [reply src/coreclr/jit/codegenarm64.cpp]: Turns out that for `emit_R_R_I()` format, if we are sign extending, we expect the size to be valid general size i.e. 4 bytes or 8 bytes, so changing to `emitTypeSize()` hits an assert. I will follow up offline with @BruceForstall .

**Review by BruceForstall — APPROVED** [review]
