### PR TITLE
Fix sync issue in profiler tests

### LINKED ISSUE #46608: profiler/elt/slowpatheltenter/slowpatheltenter.sh test failed
```
  Discovering: profiler.elt.XUnitWrapper
  Discovered:  profiler.elt.XUnitWrapper
  Starting:    profiler.elt.XUnitWrapper
    profiler/elt/slowpatheltenter/slowpatheltenter.sh [FAIL]
      Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
         at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
         at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions)
         at SlowPathELTTests.SlowPathELTEnter.Main(String[] args)
      /home/helixbot/work/A3EB092B/w/B7EA09AA/e/profiler/elt/slowpatheltenter/slowpatheltenter.sh: line 372: 10240 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /home/helixbot/work/A3EB092B/w/B7EA09AA/e/profiler/elt/Reports/profiler.elt/slowpatheltenter/slowpatheltenter.output.txt
      Raw output:
      BEGIN EXECUTION
      /home/helixbot/work/A3EB092B/p/corerun slowpatheltenter.dll ''
      Profiler path: /home/helixbot/work/A3EB092B/w/B7EA09AA/e/profiler/elt/slowpatheltenter/libProfiler.so
      Profiler.dll!DllGetClassObject
      Profiler.dll!Profiler::Initialize
      Testing enter hooks
      Gathering state for process 10271 corerun
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.10271.dmp
      Written 80461824 bytes (19644 pages) to core file
      Dump successfully written
      
      Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
      Gathering state for process 10240 corerun
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.10240.dmp
      Written 114524160 bytes (27960 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/home/helixbot/work/A3EB092B/p
      > /home/helixbot/work/A3EB092B/w/B7EA09AA/e/profiler/elt/slowpatheltenter/slowpatheltenter.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at profiler_elt._slowpatheltenter_slowpatheltenter_._slowpatheltenter_slowpatheltenter_sh()
      Output:
        Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
           at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
           at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions)
           at SlowPathELTTests.SlowPathELTEnter.Main(String[] args)
        /home/helixbot/work/A3EB092B/w/B7EA09AA/e/profiler/elt/slowpatheltenter/slowpatheltenter.sh: line 372: 10240 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /home/helixbot/work/A3EB092B/w/B7EA09AA/e/profiler/elt/Reports/profiler.elt/slowpatheltenter/slowpatheltenter.output.txt
        Raw output:
        BEGIN EXECUTION
        /home/helixbot/work/A3EB092B/p/corerun slowpatheltenter.dll ''
        Profiler path: /home/helixbot/work/A3EB092B/w/B7EA09AA/e/profiler/elt/slowpatheltenter/libProfiler.so
        Profiler.dll!DllGetClassObject
        Profiler.dll!Profiler::Initialize
        Testing enter hooks
        Gathering state for process 10271 corerun
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.10271.dmp
        Written 80461824 bytes (19644 pages) to core file
        Dump successfully written
        
        Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
        Gathering state for process 10240 corerun
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.10240.dmp
        Written 114524160 bytes (27960 pages) to core file
        Dump successfully written
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/home/helixbot/work/A3EB092B/p
        > /home/helixbot/work/A3EB092B/w/B7EA09AA/e/profiler/elt/slowpatheltenter/slowpatheltenter.sh
  Finished:    profiler.elt.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   profiler.elt.XUnitWrapper  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 38.632s
+ export _commandExitCode=1
```

Dump: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46051-merge-c6d495492c1549728b/profiler.elt/coredump.10271.dmp?sv=2019-07-07&se=2021-01-25T21%3A22%3A03Z&sr=c&sp=rl&sig=5YUXiu9zCwQV1rF24K6yOYt%2Fdv%2F%2Byfy09lzWezMof9I%3D

<!-- runfo report start -->
Runfo Tracking Issue: [profiler/elt/slowpatheltenter/slowpatheltenter.sh test failed](https://runfo.azurewebsites.net/tracking/issue/116)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[947907](https://dev.azure.com/dnceng/public/_build/results?buildId=947907)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46315](https://github.com/dotnet/runtime/pull/46315)|CoreCLR OSX x64 Checked @ OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46315-merge-e00f071ca35e480f9a/profiler.elt/console.0d45c6b2.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-02T10%2525253A58%2525253A59Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D6%2525252BpVGPsNfAzCPh1r4UJHBjvp7p%2525252FdNs8kXdjcBKPLUQs%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46315-merge-e00f071ca35e480f9a/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-02T10%2525253A58%2525253A59Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D6%2525252BpVGPsNfAzCPh1r4UJHBjvp7p%2525252FdNs8kXdjcBKPLUQs%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46315-merge-e00f071ca35e480f9a/profiler.elt/80e035c8-dbf7-465c-82df-22f318b13eb4.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-02T10%2525253A58%2525253A59Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D6%2525252BpVGPsNfAzCPh1r4UJHBjvp7p%2525252FdNs8kXdjcBKPLUQs%2525253D)|
|[946889](https://dev.azure.com/dnceng/public/_build/results?buildId=946889)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46765](https://github.com/dotnet/runtime/pull/46765)|CoreCLR Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46765-merge-2e757745061246c3ad/profiler.elt/console.56dd6329.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T22%2525253A38%2525253A33Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DTQ1fiHThAV6wmivrU56oKHRSGTZqzjMtrlGeO%2525252FvmtTU%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46765-merge-2e757745061246c3ad/profiler.elt/core.1001.147?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T22%2525253A38%2525253A33Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DTQ1fiHThAV6wmivrU56oKHRSGTZqzjMtrlGeO%2525252FvmtTU%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46765-merge-2e757745061246c3ad/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T22%2525253A38%2525253A33Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DTQ1fiHThAV6wmivrU56oKHRSGTZqzjMtrlGeO%2525252FvmtTU%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46765-merge-2e757745061246c3ad/profiler.elt/84f37c01-0d90-4602-9a8c-ade15043e3ad.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T22%2525253A38%2525253A33Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DTQ1fiHThAV6wmivrU56oKHRSGTZqzjMtrlGeO%2525252FvmtTU%2525253D)|
|[946698](https://dev.azure.com/dnceng/public/_build/results?buildId=946698)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46638](https://github.com/dotnet/runtime/pull/46638)|CoreCLR OSX x64 Checked @ OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46638-merge-59937bfd042e44ada9/profiler.elt/console.b98afd7c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T20%2525253A13%2525253A09Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DjBIB34BRZtr8Tj6rq6EcKPeXmNKaGvgPM8eLdwK5Of4%2525253D)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46638-merge-59937bfd042e44ada9/profiler.elt/core.46097?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T20%2525253A13%2525253A09Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DjBIB34BRZtr8Tj6rq6EcKPeXmNKaGvgPM8eLdwK5Of4%2525253D)|[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46638-merge-59937bfd042e44ada9/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T20%2525253A13%2525253A09Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DjBIB34BRZtr8Tj6rq6EcKPeXmNKaGvgPM8eLdwK5Of4%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46638-merge-59937bfd042e44ada9/profiler.elt/138fa69a-ceb4-4c29-917a-a6a75eb1b5c6.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T20%2525253A13%2525253A09Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DjBIB34BRZtr8Tj6rq6EcKPeXmNKaGvgPM8eLdwK5Of4%2525253D)|
|[946690](https://dev.azure.com/dnceng/public/_build/results?buildId=946690)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46868](https://github.com/dotnet/runtime/pull/46868)|CoreCLR OSX x64 Checked @ OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46868-merge-5d10fc5fb7d94a8983/profiler.elt/console.be4a9e9e.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T20%2525253A08%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVV0vjrSatQ8Pq1cUKerZIT3zKjukagECW88mRIwMdm0%2525253D)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46868-merge-5d10fc5fb7d94a8983/profiler.elt/core.39845?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T20%2525253A08%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVV0vjrSatQ8Pq1cUKerZIT3zKjukagECW88mRIwMdm0%2525253D)|[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46868-merge-5d10fc5fb7d94a8983/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T20%2525253A08%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVV0vjrSatQ8Pq1cUKerZIT3zKjukagECW88mRIwMdm0%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46868-merge-5d10fc5fb7d94a8983/profiler.elt/0ffd001f-d05c-4bbe-8e39-f9c02f477420.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T20%2525253A08%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVV0vjrSatQ8Pq1cUKerZIT3zKjukagECW88mRIwMdm0%2525253D)|
|[946318](https://dev.azure.com/dnceng/public/_build/results?buildId=946318)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|CoreCLR OSX x64 Checked @ OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-38124c2760434f72b3/profiler.elt/console.795abf5c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T14%2525253A36%2525253A51Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DKwkukPIbd1yORhr0rS0u0O5aoaL%2525252FGCMhbHBn8of84V4%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-38124c2760434f72b3/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T14%2525253A36%2525253A51Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DKwkukPIbd1yORhr0rS0u0O5aoaL%2525252FGCMhbHBn8of84V4%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-38124c2760434f72b3/profiler.elt/159c6a61-9352-4c88-9a22-3a04465b8c99.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-02-01T14%2525253A36%2525253A51Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DKwkukPIbd1yORhr0rS0u0O5aoaL%2525252FGCMhbHBn8of84V4%2525253D)|
|[938936](https://dev.azure.com/dnceng/public/_build/results?buildId=938936)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46051](https://github.com/dotnet/runtime/pull/46051)|CoreCLR Linux x64 Checked @ Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46051-merge-c6d495492c1549728b/profiler.elt/console.bda1c4d6.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-01-25T21%2525253A22%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5YUXiu9zCwQV1rF24K6yOYt%2525252Fdv%2525252F%2525252Byfy09lzWezMof9I%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46051-merge-c6d495492c1549728b/profiler.elt/core.1000.10240?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-01-25T21%2525253A22%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5YUXiu9zCwQV1rF24K6yOYt%2525252Fdv%2525252F%2525252Byfy09lzWezMof9I%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46051-merge-c6d495492c1549728b/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-01-25T21%2525253A22%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5YUXiu9zCwQV1rF24K6yOYt%2525252Fdv%2525252F%2525252Byfy09lzWezMof9I%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46051-merge-c6d495492c1549728b/profiler.elt/21ca2cae-c72e-4222-90a1-6bb0637c1b54.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-01-25T21%2525253A22%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D5YUXiu9zCwQV1rF24K6yOYt%2525252Fdv%2525252F%2525252Byfy09lzWezMof9I%2525253D)|
|[938737](https://dev.azure.com/dnceng/public/_build/results?buildId=938737)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|CoreCLR Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a4c08b79ae894ffa8a/profiler.elt/console.106c6216.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-01-25T20%2525253A06%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DZdMke12pXRl3%2525252B2AKFiw2865yEwhhzEH4VZ6S%2525252F0rI1Lk%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a4c08b79ae894ffa8a/profiler.elt/core.1001.172?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-01-25T20%2525253A06%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DZdMke12pXRl3%2525252B2AKFiw2865yEwhhzEH4VZ6S%2525252F0rI1Lk%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a4c08b79ae894ffa8a/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-01-25T20%2525253A06%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DZdMke12pXRl3%2525252B2AKFiw2865yEwhhzEH4VZ6S%2525252F0rI1Lk%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a4c08b79ae894ffa8a/profiler.elt/b5458094-5f57-428b-9072-337599264586.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2021-01-25T20%2525253A06%2525253A05Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DZdMke12pXRl3%2525252B2AKFiw2865yEwhhzEH4VZ6S%2525252F0rI1Lk%2525253D)|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|1|5|7|

<!-- runfo report end -->

### LINKED ISSUE #46844: Test failure :  profiler/elt/slowpatheltleave/slowpatheltleave.sh
Job : [runtime-coreclr outerloop 20210111.3](https://dev.azure.com/dnceng/public/_build/results?buildId=945278&view=ms.vss-test-web.build-test-results-tab&runId=29829386&resultId=100631&paneView=debug)

Failed test: `profiler/elt/slowpatheltleave/slowpatheltleave.sh`

CoreCLR OSX x64 Checked @ OSX.1013.Amd64.Open

**Error message:**
```
Unhandled exception. System.Exception: Profilee returned exit code 139 instead of expected exit code 100.
 at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
 at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions)
 at SlowPathELTTests.SlowPathELTLeave.Main(String[] args)
MachO coredumps are not supported. To enable ELF coredumps on MacOS, set the COMPlus_DbgEnableElfDumpOnMacOS environment variable to 1.
/private/tmp/helix/working/ABA9097F/w/A30908E3/e/profiler/elt/slowpatheltleave/slowpatheltleave.sh: line 371: 47483 Abort trap: 6 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /private/tmp/helix/working/ABA9097F/w/A30908E3/e/profiler/elt/Reports/profiler.elt/slowpatheltleave/slowpatheltleave.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/ABA9097F/p/corerun slowpatheltleave.dll ''
Profiler path: /private/tmp/helix/working/ABA9097F/w/A30908E3/e/profiler/elt/slowpatheltleave/libProfiler.dylib
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Testing leave hooks
x=-123 y=-4.3 str=Hello, test!
SimpleArgsFunc returned Hello from SimpleArgsFunc!
ss=x=1 d=1
MixedStructFunc returned x=4 d=1
ls=x0=0 d0=0 x1=1 d1=1 x2=2 d2=2 x3=3 d3=3
LargeStructFunc returned 3
IntegerStructFunc returned x=21 y=256
FloatingPointStructFunc returned d1=13 d2=256.8
DoubleRetFunc returned 13
Profiler.dll!Profiler::Shutdown
PROFILER TEST PASSES

Test failed: Profilee returned exit code 139 instead of expected exit code 100.
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/ABA9097F/p
> /private/tmp/helix/working/ABA9097F/w/A30908E3/e/profiler/elt/slowpatheltleave/slowpatheltleave.sh
Expected: True
Actual: False


Stack trace
   at profiler_elt._slowpatheltleave_slowpatheltleave_._slowpatheltleave_slowpatheltleave_sh()
```

### PR DESCRIPTION
**Pull request by davmason**
Fixes #46844

The macros introduced with #46739 had a bug. Because I was on autopilot and used `do{...} while(0)` in the macros, it introduced a new scope and the ShutdownGuard class would not be held for the duration of the call. I did test it, since it prevented new calls from entering the profiler code it drastically reduced the hit rate but there still was a race condition.

### CODE REVIEW

File: src/tests/profiler/native/eltprofiler/slowpatheltprofiler.cpp [hunk 1]
```diff
@@ -307,8 +307,6 @@ HRESULT STDMETHODCALLTYPE SlowPathELTProfiler::LeaveCallback(FunctionIDOrClientI
 
 HRESULT STDMETHODCALLTYPE SlowPathELTProfiler::TailcallCallback(FunctionIDOrClientID functionIdOrClientID, COR_PRF_ELT_INFO eltInfo)
 {
-    SHUTDOWNGUARD();
```
Comment (davmason) [inline src/tests/profiler/native/eltprofiler/slowpatheltprofiler.cpp:310]: This is superfluous since it's already protected in `TailcallStub` above.

**Review by sdmaclea — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]
