### PR TITLE
[browser][mt] Update memory views after growth, refactor string processing, fix SharedArrayBuffer detection

### LINKED ISSUE #86642: [browser][MT] Memory growth on worker could cause failure
When we compile the runtime with `/p:MonoWasmBuildVariant=multithread` and the web worker would cause memory growth, the linear memory buffer is disconnected from the original buffer on the main thread.

Example of allocation and resize on worker
image

Example of subsequent failure on main thread: the buffer is no longer `instanceof SharedArrayBuffer` but I think it's just disconnected.
image

Leads to 
```
MONO_WASM: TypeError: Failed to execute 'decode' on 'TextDecoder': The provided ArrayBufferView value must not be shared.
    at UTF8ArrayToString (http://localhost:8000/dotnet.native.js:379:22)
    at Object.UTF8ToString (http://localhost:8000/dotnet.native.js:412:15)
    at mono_wasm_trace_logger (http://localhost:8000/dotnet.runtime.js:211:32)
    at wasm_trace_logger (http://localhost:8000/dotnet.native.wasm:wasm-function[142]:0x11902)
    at callback_adapter (http://localhost:8000/dotnet.native.wasm:wasm-function[872]:0x58eec)
    at mono_tracev_inner (http://localhost:8000/dotnet.native.wasm:wasm-function[867]:0x58cfb)
    at mono_trace.13 (http://localhost:8000/dotnet.native.wasm:wasm-function[5213]:0x15b333)
    at mono_runtime_class_init_full (http://localhost:8000/dotnet.native.wasm:wasm-function[5206]:0x15ab4e)
    at do_init_vtable (http://localhost:8000/dotnet.native.wasm:wasm-function[294]:0x2793e)
    at mono_interp_exec_method (http://localhost:8000/dotnet.native.wasm:wasm-function[277]:0x1ec85)
```
on the main thread.

### LINKED ISSUE #86696: Issues using Blazor Multithreading within iframes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the wasm-buildtools for .NET 8.0 Preview 4, I have come across an unpredictable and frequent runtime bug when embedding a multithreaded Blazor application within an iframe on another page. I've double checked that all CSP and CORS policies are in order and not the root cause. 

In fact, I found someone else reporting this exact same issue, only in a completely different use case over by the emscripten repository: https://github.com/emscripten-core/emscripten/issues/18034

The workaround being tossed out there by several developers is to make sure that all calls to `emcc` use the flag `-s TEXTDECODER=0`

I've been able to greatly reduce the frequency of this error by adding this flag using these properties: 
`<EmccCompileOptimizationFlag>-O2 -s TEXTDECODER=0</EmccCompileOptimizationFlag>`
`<EmccLinkOptimizationFlag>-O2 -s TEXTDECODER=0</EmccLinkOptimizationFlag>`
to my csproj file.

I have also confirmed that these flags are being used to compile my assemblies and dependencies. However, I can't figure out a way to add this flag to the main dotnet.wasm emcc command to ensure that my dotnet-runtime.js file does not use `TextDecoder` to marshal WASM memory across threads. 

Interesting to note is that the frequency of this error greatly decreases when embedding the blazor application page with `object` tags instead of `iframe`. 

Regardless, the error I am receiving exhibits the same, inconsistent behavior. I'm guessing this is a Blazor toolchain issue that can be fixed by making sure that the `-s TEXTDECODER=0` flag is used when compiling dotnet-runtime.js at publish-time; to safeguard against any regressions of users this bug doesn't affect, this flag would only be added if `WasmEnableThreads` is also explicitly enabled. I'm willing to write a PR that implements this. 

### Expected Behavior

The expected behavior is that I can use my multithreaded Blazor WebAssembly application within an `iframe` without the previously described inconsistent crashing behavior. 

### Steps To Reproduce

_No response_

### Exceptions (if any)

`Uncaught TypeError: Failed to execute 'decode' on 'TextDecoder': The provided ArrayBufferView value must not be shared.`

### .NET Version

8.0.100-preview.4.23260.5

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by IsaMorphic**
"memory pooling or reclamation mechanism that they use internally that causes SharedArrayBuffer to cross the iframe boundary"

- test for `SharedArrayBuffer` via `buffer[Symbol.toStringTag] === "SharedArrayBuffer"`
    -  @IsaMorphic adapted a fix to this issue from this PR in the emscripten repository: https://github.com/emscripten-core/emscripten/pull/16994
- added `copyBufferIfNecessary` helper
   - the method is NOOP in non-threaded build
- added `receiveWorkerHeapViews` 
   - the method is NOOP in non-threaded build
- replaced `Module.HEAP`xx with new `localHeapViewXXX()`
   - which calls `receiveWorkerHeapViews` and produces updated short lived "local" view
- added `-s TEXTDECODER=0` emcc linker flag for MT build
- wrap `Module.UTF8ArrayToString` and `Module.UTF8ToString` with our own `utf8ToString` and `decodeUTF8`
   - this will copy the bytes and use `TextDecoder` for longer strings instead of emscripten byte-by-byte loop
- move code into `encodeUTF8` and `utf8ToStringRelaxed` of `strings.ts`
- prefer `HEAPU8` over `HEAP8` for code consistency
- `string.ts` refactoring

Fixes https://github.com/dotnet/runtime/issues/86696
Fixes https://github.com/dotnet/runtime/issues/86642

Related issues: 
https://github.com/emscripten-core/emscripten/issues/15217

### CODE REVIEW

**Comment by IsaMorphic** [comment]
@dotnet-policy-service agree

File: src/mono/wasm/runtime/strings.ts [hunk 1]
```diff
@@ -77,7 +77,10 @@ export class StringDecoder {
             // When threading is enabled, TextDecoder does not accept a view of a
             // SharedArrayBuffer, we must make a copy of the array first.
             // See https://github.com/whatwg/encoding/issues/172
-            const subArray = typeof SharedArrayBuffer !== "undefined" && Module.HEAPU8.buffer instanceof SharedArrayBuffer
+        
+            // BEWARE: In some cases, `instanceof SharedArrayBuffer` returns false even though buffer is an SAB.
+            // Patch adapted from https://github.com/emscripten-core/emscripten/pull/16994
+            const subArray = typeof SharedArrayBuffer !== "undefined" && Object.prototype.toString.call(Module.HEAPU8.buffer) === "[object SharedArrayBuffer]"
```
Comment (kg) [inline src/mono/wasm/runtime/strings.ts:83]: This toString operation and comparison will probably add measurable overhead to the cost of decoding strings, so I'd like to see a better solution

**Comment by kg** [comment]
Thanks for your contribution! If I understand correctly, this instanceof bug affects scenarios involving iframes because the iframe is a different realm and has its own builtins like Array and SharedArrayBuffer, right? So any case where we are using instanceof is potentially broken in that case, which is what motivates APIs like Array.isArray.

File: src/mono/wasm/runtime/strings.ts (hunk 1 above)
Comment (IsaMorphic) [reply src/mono/wasm/runtime/strings.ts]: Good catch! Using the object's `[Symbol.toStringTag]` property should do the trick, since that's what Object.toString uses under the hood.

File: src/mono/wasm/runtime/strings.ts [hunk 2]
```diff
@@ -77,7 +77,11 @@ export class StringDecoder {
             // When threading is enabled, TextDecoder does not accept a view of a
             // SharedArrayBuffer, we must make a copy of the array first.
             // See https://github.com/whatwg/encoding/issues/172
-            const subArray = typeof SharedArrayBuffer !== "undefined" && Module.HEAPU8.buffer instanceof SharedArrayBuffer
+        
+            // BEWARE: In some cases, `instanceof SharedArrayBuffer` returns false even though buffer is an SAB.
+            // Patch adapted from https://github.com/emscripten-core/emscripten/pull/16994
+            // See also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag
+            const subArray = typeof SharedArrayBuffer !== "undefined" && Module.HEAPU8.buffer[Symbol.toStringTag] === "SharedArrayBuffer"
```
Comment (kg) [inline src/mono/wasm/runtime/strings.ts:84]: toStringTag is the perfect solution for this I think 👍

Comment (IsaMorphic) [reply src/mono/wasm/runtime/strings.ts:84]: I think so too! Very clean and just as easy to write.

**Review by kg — APPROVED** [review]

**Comment by pavelsavara** [comment]
How could dotnet wasm linear memory come from iframe ? 
Are we talking about 2 runtimes sharing memory across the iframe boundary ?

I would appreciate small demo project which reproduces the issue before we merge this. 
Adapting one of the [samples](https://github.com/dotnet/runtime/tree/main/src/mono/sample/wasm) would be ideal.

Possibly related issue https://github.com/dotnet/runtime/issues/86642

**Comment by IsaMorphic** [comment]
@pavelsavara 
To answer your question, yes: in my implementation specific use case, I am using a Blazor app as an embeddable image renderer to demonstrate a future product. In my application I am using 2 or more runtimes per page (each in their own iframe). However, it seems (from the related emscripten bug) that all modern browsers might have some type of memory pooling or reclamation mechanism that they use internally that causes buffers to cross the iframe boundary. Though it still could be misuse on the part of the .net runtime, as well :P

Please see the latest commit on my fork's `broken-sample` branch. Use the typical launch commands for the `browser-threading-minimal` sample, but make sure to browse to `http://localhost:<port>/embeds.html` and read the text on the page. This updated sample replicates the issue extremely consistently. 

I have not tried to see if my patch helps, as I have not build the runtime with the `-sTEXTDECODER=0` flag and tested it in this way yet. 

Hope this is helpful.

**Comment by pavelsavara** [comment]
`UTF8ArrayToString` is emscripten method and the issue is the same https://github.com/emscripten-core/emscripten/issues/18034
`TEXTDECODER=0` should have fixed that for you.

"memory pooling or reclamation mechanism that they use internally that causes buffers to cross the iframe boundary" could you please point me to more details about it ?

**Comment by pavelsavara** [comment]
Also, if there is buffer reuse across iframes, it should also manifest without threads, right ?
We have iframe based [benchmark](https://github.com/dotnet/runtime/blob/main/src/mono/sample/wasm/browser-bench/AppStart.cs) which we run daily. I don't remember such issue to manifest there. 

@radekdoulik would we capture/notice the error if one of the AppStart measures failed to start the runtime in the iframe ?

**Comment by pavelsavara** [comment]
I get it now, in our benchmark it's not a `SharedArrayBuffer`. I guess we should create MT flavor of the benchmark soon anyway.

**Comment by pavelsavara** [comment]
> Please see the latest commit on my fork's `broken-sample` branch. 

https://github.com/dotnet/runtime/compare/main...IsaMorphic:runtime-wasmfix:broken-sample

I will have look soon, probably next week. Thanks a lot!

I would still love to read about how this is not a browser bug. :-D

**Comment by pavelsavara** [comment]
I used your sample and indeed I can reproduce it.
image

I will push more comprehensive fix into this PR

**Comment by pavelsavara** [comment]
I made bit of the monster from your PR @IsaMorphic 😁 I hope you don't mind

@kg please re-review. I updated the PR description.

File: src/mono/wasm/runtime/strings.ts [hunk 3]
```diff
@@ -272,3 +269,68 @@ export function js_string_to_mono_string_new(string: string): MonoString {
...
+// When threading is enabled, TextDecoder does not accept a view of a
+// SharedArrayBuffer, we must make a copy of the array first.
+// See https://github.com/whatwg/encoding/issues/172
+// BEWARE: In some cases, `instanceof SharedArrayBuffer` returns false even though buffer is an SAB.
+// Patch adapted from https://github.com/emscripten-core/emscripten/pull/16994
+// See also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag
+export function copy_string_buffer_as_necessary(view: Uint8Array, start: CharPtr, end: CharPtr): Uint8Array {
+    updateGrowableHeapViews();
+    // this condition should be eliminated by rollup on non-threading builds
+    const needsCopy = mayNeedCopy && view.buffer[Symbol.toStringTag] === "SharedArrayBuffer";
```
Comment (lambdageek) [inline src/mono/wasm/runtime/strings.ts:332]: Let's make a general purpose utility

```ts
function isSharedArrayBuffer(x: any): x is SharedArrayBuffer
{
  return mayNeedCopy && view.buffer[Symbol.toStringTag] === "SharedArrayBuffer"
}

**Review by lambdageek — APPROVED** [review]

**Comment by IsaMorphic** [comment]
This is really awesome guys!! I'm so happy that my simple one-line fix has prompted the implementation of a more robust solution. Great job especially to @pavelsavara 😄

I'm wondering how I could go about using these patches in a Blazor project build? Is there an MSBuild hack that I could use, or do I have to be more patient and wait for the next preview? 

I ask because I want to test this patch on my original project before entirely deciding that the issue is completely fixed.

Please let me know!

**Comment by maraf** [comment]
> I'm wondering how I could go about using these patches in a Blazor project build? Is there an MSBuild hack that I could use, or do I have to be more patient and wait for the next preview?

You can try this https://github.com/dotnet/runtime/blob/main/src/mono/wasm/build/README.md#blazor

File: src/mono/wasm/runtime/memory.ts [hunk 4]
```diff
@@ -83,25 +89,30 @@ export function setU32_unchecked(offset: MemOffset, value: NumberOrPointer): voi
...
 }
 
 export function setI16(offset: MemOffset, value: number): void {
     assert_int_in_range(value, -0x8000, 0x7FFF);
+    updateGrowableHeapViews();
     Module.HEAP16[<any>offset >>> 1] = value;
 }
 
 export function setI32_unchecked(offset: MemOffset, value: number): void {
+    updateGrowableHeapViews();
```
Comment (kg) [inline src/mono/wasm/runtime/memory.ts:109]: Have you been able to benchmark the impact of this change? I'm concerned it will be a measurable performance regression in single-threaded builds for no upside

Comment (pavelsavara) [reply src/mono/wasm/runtime/memory.ts:109]: `updateGrowableHeapViews` is NOOP in single threaded, because rollup. I will double check that .js file to make sure.

Comment (pavelsavara) [reply src/mono/wasm/runtime/memory.ts:109]: This is MT version
image

This is single threaded version
image

The string `"Module.wasmMemory not set"` is not even in the file.

I will remove the `mono_assert` for MT performance sake.

File: src/mono/wasm/runtime/strings.ts (hunk 3 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/strings.ts:332]: This is what `StringDecoder.decode` boiled down to in non-MT build

image

**Comment by pavelsavara** [comment]
@IsaMorphic to build runtime use 
`build.cmd -os browser -subset mono+libs -c Debug /p:MonoWasmBuildVariant=multithread` and then maraf's advice

**Comment by pavelsavara** [comment]
> `Reason: Error: Assert failed: Can't find asset for js-module-runtime`

I think this is because we made changes in the tooling for  preview5 which are not compatible with preview4. Right @maraf ?

**Comment by maraf** [comment]
> > `Reason: Error: Assert failed: Can't find asset for js-module-runtime`
> 
> I think this is because we made changes in the tooling for preview5 which are not compatible with preview4. Right @maraf ?

Yes, this is incompatibility between SDK and runtime pack. Installing newer (nightly) preview will fix it

**Comment by pavelsavara** [comment]
I processed further feedback from @kg about not calling `updateGrowableHeapViews()` from tight loops.

While doing that I noticed that we have too many loops where we convert strings with different encodings, so I moved all of it into `string.ts`. 
And while I worked on that I dropped `StringDecoder` class because it was not helping anything. 
I dropped few legacy methods and renamed the rest to camelCase.

@ilonatommy I touched some of the hybrid locale stuff, please have look.

There is bit of risk that this change will introduce perf regression, but it was that already yesterday.
@radekdoulik could you please run benchmark on this before I merge it ?

File: src/mono/wasm/runtime/debug.ts [hunk 5]
```diff
@@ -59,6 +61,7 @@ export function mono_wasm_add_dbg_command_received(res_ok: boolean, id: number,
 }
 
 function mono_wasm_malloc_and_set_debug_buffer(command_parameters: string) {
+    const heapU8 = localHeapViewU8();
```
Comment (kg) [inline src/mono/wasm/runtime/debug.ts:64]: this is incorrect because we're calling malloc after, we need to do this after the malloc call

File: src/mono/wasm/runtime/memory.ts [hunk 6]
```diff
@@ -65,43 +68,58 @@ export function setB32(offset: MemOffset, value: number | boolean): void {
...
 }
 
 export function setU16(offset: MemOffset, value: number): void {
+    assert_int_in_range(value, 0, 0xFFFF);
+    updateGrowableHeapViews();
+    Module.HEAPU16[<any>offset >>> 1] = value;
+}
+
+// does not check for growable heap
+export function setU16_local(offset: MemOffset, value: number): void {
```
Comment (kg) [inline src/mono/wasm/runtime/memory.ts:82]: it may make sense for the _local functions to actually accept the heap as an argument, so you can't use them without having previously grabbed it

File: src/mono/wasm/runtime/net6-legacy/js-to-cs.ts [hunk 7]
```diff
@@ -150,10 +150,13 @@ function _extract_mono_obj_root(should_add_in_flight: boolean, js_obj: any, resu
 
 // https://github.com/Planeshifter/emscripten-examples/blob/master/01_PassingArrays/sum_post.js
 function js_typedarray_to_heap(typedArray: TypedArray) {
+    assert_legacy_interop();
+    const heapU8 = localHeapViewU8();
```
Comment (kg) [inline src/mono/wasm/runtime/net6-legacy/js-to-cs.ts:154]: move below malloc

File: src/mono/wasm/runtime/roots.ts [hunk 8]
```diff
@@ -217,7 +217,7 @@ export class WasmRootBufferImpl implements WasmRootBuffer {
     get(index: number): ManagedPointer {
         this._check_in_range(index);
         const offset = this.get_address_32(index);
-        return <any>Module.HEAPU32[offset];
+        return <any>localHeapViewU32()[offset];
```
Comment (kg) [inline src/mono/wasm/runtime/roots.ts:220]: roots and root buffers don't need growth checks; we pre-allocated them so as long as we do a growth check after the initial allocation the addresses will always be visible.

File: src/mono/wasm/runtime/web-socket.ts [hunk 9]
```diff
@@ -336,16 +332,10 @@ function _mono_wasm_web_socket_send_buffering(ws: WebSocketExtension, buffer_vie
...
-                // we do not validate outgoing data https://github.com/dotnet/runtime/issues/59214
-                _text_decoder_utf8 = new TextDecoder("utf-8", { fatal: false });
-            }
 
-            // See https://github.com/whatwg/encoding/issues/172
-            const bytes = typeof SharedArrayBuffer !== "undefined" && buffer instanceof SharedArrayBuffer
-                ? (<any>buffer).slice(0, offset)
-                : buffer.subarray(0, offset);
-            return _text_decoder_utf8.decode(bytes);
+            const bytes = copyBufferIfNecessary(buffer, 0 as any, offset as any);
```
Comment (kg) [inline src/mono/wasm/runtime/web-socket.ts:336]: there is type confusion here and in the original code - subarray is a method of ArrayView, which implies buffer is a Uint8Array or other type, not an ArrayBuffer. Which means `buffer instanceof SharedArrayBuffer` would never be true.

I think the operation we actually want here is named something like `ensureViewHasNonSharedBuffer`.

File: src/mono/wasm/runtime/hybrid-globalization/change-case.ts [hunk 10]
```diff
@@ -31,20 +27,19 @@ export function mono_wasm_change_case_invariant(src: number, srcLength: number,
...
     const cultureRoot = mono_wasm_new_external_root<MonoString>(culture),
         exceptionRoot = mono_wasm_new_external_root<MonoObject>(ex_address);
-    try{
-        const cultureName = conv_string_root(cultureRoot);
+    try {
+        const cultureName = monoStringToString(cultureRoot);
         if (!cultureName)
             throw new Error("Cannot change case, the culture name is null.");
-        const input = get_utf16_string(src, srcLength);
+        const input = utf16ToString(src, src + 2 * srcLength);
```
Comment (ilonatommy) [inline src/mono/wasm/runtime/hybrid-globalization/change-case.ts:37]: This place used to use loop-only. When we change it to using the TextDecoder on browser, we might have some hybrid tests failing - encoders/decoders behave like NLS, not like ICU.

**Review by ilonatommy — APPROVED** [review]
Globalization pointer math checked.

File: src/mono/wasm/runtime/roots.ts (hunk 8 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/roots.ts:220]: I put back `Module.HEAPU32` to all root code, correct also for MT ?

File: src/mono/wasm/runtime/web-socket.ts (hunk 9 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/web-socket.ts:336]: the `buffer` in WS code is always instance of `Uint8Array` and the code is correct, I will rename `copyBufferIfNecessary` to `viewOrCopy`

Comment (pavelsavara) [reply src/mono/wasm/runtime/web-socket.ts:336]: name `buffer` in WS is bit misleading, but most of the time it's dedicated buffer, not view of linear memory.

File: src/mono/wasm/runtime/roots.ts (hunk 8 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/roots.ts]: I'm not sure. I think `grow` would disconnect the views and they will be returning `undefined`

Comment (kg) [reply src/mono/wasm/runtime/roots.ts]: Good point

**Comment by pavelsavara** [comment]
I guess this is that we eliminated bunch of checks in the non-MT string conversion.

image

https://radekdoulik.github.io/WasmPerformanceMeasurements/?startDate=2023-05-24T10%3A51%3A33.000Z&endDate=2023-05-29T21%3A06%3A42.000Z&tasks=%2CJSInterop
