### PR TITLE
Fix unicode tests for ios/tvOs

### LINKED ISSUE #72951: [iOS] ZipArchive and ZipFile unicode test failures
Both [ExtractToDirectoryUnicode](https://github.com/dotnet/runtime/blob/c21ae04d923a1e5d2964fed61cc919571cce2efe/src/libraries/System.IO.Compression.ZipFile/tests/ZipFile.Extract.cs#L37-L46) and [ExtractToDirectoryExtension_Unicode](https://github.com/dotnet/runtime/blob/c21ae04d923a1e5d2964fed61cc919571cce2efe/src/libraries/System.IO.Compression.ZipFile/tests/ZipFileExtensions.ZipArchive.Extract.cs#L25-L33) fail comparing the file names extracted from `unicode.zip`.

What's weird is that the expected and actual file names appear to be equal:

```
Expected: 한글.txt

Actual: 한글.txt
```
If you take the strings from actual and expected and put them in a small test, they will be equal.  It seems like the values returned from the file system in https://github.com/dotnet/runtime/blob/c21ae04d923a1e5d2964fed61cc919571cce2efe/src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs#L291-L292 are suspect.

Skipping the tests for now.

### PR DESCRIPTION
**Pull request by alinpahontu2912**
Fixes #72951

Normalize extra ascii characters to perform correct matching on apple platforms

### CODE REVIEW

**Comment by akoeplinger** [comment]
Note that we only run smoke tests for iOS/tvOS in PRs by default which doesn't include System.IO.Compression so you'd need to trigger the full pipeline.

**Comment by alinpahontu2912** [comment]
Test was failing because iOS/tvOS store filenames in decomposed form NFD and we were comparing against NFC words. They look the same but compare different, so we should normalize for them to match.

File: src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs [hunk 1]
```diff
@@ -333,6 +333,20 @@ public static async Task DirsEqual(string actual, string expected)
             await ItemEqual(actualList, expectedList, isFile: true);
             await ItemEqual(actualFolders, expectedList, isFile: false);
         }
+        public static void NormalizeFileNames(string folder)
```
Comment (rzikm) [inline src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs]: Instead o normalizing the names on the disk, I would fix the comparison in the function below, to take normalization into account, and do that only for the affected platform.

File: src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs [hunk 2]
```diff
@@ -336,9 +336,17 @@ public static async Task DirsEqual(string actual, string expected)
 
         public static void DirFileNamesEqual(string actual, string expected)
         {
-            IOrderedEnumerable<string> actualEntries = Directory.EnumerateFileSystemEntries(actual, "*", SearchOption.AllDirectories).Order();
-            IOrderedEnumerable<string> expectedEntries = Directory.EnumerateFileSystemEntries(expected, "*", SearchOption.AllDirectories).Order();
-            AssertExtensions.SequenceEqual(expectedEntries.Select(Path.GetFileName).ToArray(), actualEntries.Select(Path.GetFileName).ToArray());
+            IEnumerable<string> actualEntries = Directory.EnumerateFileSystemEntries(actual, "*", SearchOption.AllDirectories);
+            IEnumerable<string> expectedEntries = Directory.EnumerateFileSystemEntries(expected, "*", SearchOption.AllDirectories);
+
+#if OS_IOS || OS_TVOS
```
Comment (rzikm) [inline src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs]: I don't think these smybols are defined anywhere.

I suggest you use `PlatformDetection.IstvOS` and `IsiOS` instead

File: src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs [hunk 3]
```diff
@@ -336,9 +336,20 @@ public static async Task DirsEqual(string actual, string expected)
...
-            IOrderedEnumerable<string> actualEntries = Directory.EnumerateFileSystemEntries(actual, "*", SearchOption.AllDirectories).Order();
-            IOrderedEnumerable<string> expectedEntries = Directory.EnumerateFileSystemEntries(expected, "*", SearchOption.AllDirectories).Order();
-            AssertExtensions.SequenceEqual(expectedEntries.Select(Path.GetFileName).ToArray(), actualEntries.Select(Path.GetFileName).ToArray());
+            IEnumerable<string> actualEntries = Directory.EnumerateFileSystemEntries(actual, "*", SearchOption.AllDirectories);
+            IEnumerable<string> expectedEntries = Directory.EnumerateFileSystemEntries(expected, "*", SearchOption.AllDirectories);
+
+            if (PlatformDetection.IstvOS || PlatformDetection.IsiOS)
+            {
+                actualEntries = actualEntries.Select(Path.GetFileName).Select(name => name.Normalize(NormalizationForm.FormC)).Order();
+            }
```
Comment (rzikm) [inline src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs]: I think there should be a comment as to why we are treating these differently than the others.

File: src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs [hunk 4]
```diff
@@ -336,9 +336,14 @@ public static async Task DirsEqual(string actual, string expected)
...
         {
-            IOrderedEnumerable<string> actualEntries = Directory.EnumerateFileSystemEntries(actual, "*", SearchOption.AllDirectories).Order();
-            IOrderedEnumerable<string> expectedEntries = Directory.EnumerateFileSystemEntries(expected, "*", SearchOption.AllDirectories).Order();
-            AssertExtensions.SequenceEqual(expectedEntries.Select(Path.GetFileName).ToArray(), actualEntries.Select(Path.GetFileName).ToArray());
+            IEnumerable<string> actualEntries = Directory.EnumerateFileSystemEntries(actual, "*", SearchOption.AllDirectories).Select(Path.GetFileName);
+            IEnumerable<string> expectedEntries = Directory.EnumerateFileSystemEntries(expected, "*", SearchOption.AllDirectories).Select(Path.GetFileName);
+
+            // iOS/tvOS filesystems use NFD by default for non-ASCII characters, so we normalize to NFC for cross-platform comparison
+            actualEntries = actualEntries.Select(name => name.Normalize(NormalizationForm.FormC)).Order();
+            expectedEntries = expectedEntries.Select(name => name.Normalize(NormalizationForm.FormC)).Order();
```
Comment (rzikm) [inline src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs]: I think we should be doing this only on the affected platforms.

**Review by rzikm — APPROVED** [review]
LGTM
