### PR TITLE
Fix edge case of code heap initial request

### LINKED ISSUE #71200: Assert failure: heapSize >= initialRequestSize with collectible assemblies on linux-x64
We have been hitting this on and off in Fuzzlyn jobs for a while now.

To reproduce:
1. Checkout and build [Fuzzlyn](https://github.com/jakobbotsch/Fuzzlyn/) with `dotnet publish -c Release -r linux-x64 --self-contained`
2. Execute Fuzzlyn's execution server with a checked `corerun` and the input file attached to the issue by running the following command:
```bash
artifacts/tests/coreclr/Linux.x64.Checked/Tests/Core_Root/corerun <path to publish dir>/Fuzzlyn.ExecutionServer.dll <path to attached input.json>
```

The JSON document contains two assemblies that the execution server will try to load and run in a collectible ALC.

Result:
```scala
// Assert failure(PID 1365 [0x00000555], Thread: 1373 [0x055d]): heapSize >= initialRequestSize
//     File: /home/jakob/dev/dotnet/runtime/src/coreclr/vm/codeman.cpp Line: 2583
//     Image: /home/jakob/dev/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Checked/Tests/Core_Root/corerun
//
```

[input.zip](https://github.com/dotnet/runtime/files/8966845/input.zip)

cc @janvorli

### PR DESCRIPTION
**Pull request by janvorli**
When the requested size passed to the `LoaderCodeHeap::CreateCodeHeap` is less
than 16 bytes smaller than the `COLLECTIBLE_CODEHEAP_SIZE`, we incorrectly
try to use the initially preallocated block. The problem is that besides the
requested size, we also allocate `JUMP_ALLOCATE_SIZE` sized block. In the
edge case mentioned above, it doesn't fit and we assert in debug builds
of the runtime.
In release build, it would throw OOM in such case.

This issue was found by the Fuzzlyn tool.

Close #71200

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas most of the changes are just because I've made the `AllocMem_TotalSize` a member of the `UnlockedLoaderHeap`. It was kind of weird to not to be that way.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/codeman.cpp [hunk 1]
```diff
@@ -2517,7 +2517,11 @@ HeapList* LoaderCodeHeap::CreateCodeHeap(CodeHeapRequestInfo *pInfo, LoaderHeap
     DWORD dwSizeAcquiredFromInitialBlock = 0;
     bool fAllocatedFromEmergencyJumpStubReserve = false;
 
-    pBaseAddr = (BYTE *)pInfo->m_pAllocator->GetCodeHeapInitialBlock(loAddr, hiAddr, (DWORD)initialRequestSize, &dwSizeAcquiredFromInitialBlock);
+    size_t allocationSize = pCodeHeap->m_LoaderHeap.AllocMem_TotalSize(initialRequestSize);
+#if defined(TARGET_AMD64) || defined(TARGET_ARM64) || defined(TARGET_LOONGARCH64)
```
Comment (am11) [inline src/coreclr/vm/codeman.cpp:2521]: Can we use `#ifdef TARGET_64BIT` instead (as done below on line 2600)?

Comment (janvorli) [reply src/coreclr/vm/codeman.cpp:2521]: Sure, I can do that. I've just copied the same ifdef that we have below where we allocate the personality routine. But there are many more places in the code where we have this same compound `#if`. So maybe it would be worth a separate cleanup instead.

Comment (am11) [reply src/coreclr/vm/codeman.cpp:2521]: Sure. Some of the usage of `HOST_64BIT` in VM can also be reviewed as part of that work, because it looks like the correct macro for them (in most places) is `TARGET_64BIT` (but it will require a in-depth analysis: https://github.com/dotnet/runtime/pull/2256#issuecomment-579543182).

Comment (janvorli) [reply src/coreclr/vm/codeman.cpp:2521]: I've created issue #71220 for that.
