### PR TITLE
Fix x86 InlinedCallFrame popping during EH

### LINKED ISSUE #2240: [Windows x86] InlinedCallFrame popping during EH corrupts Frame chain
From https://github.com/dotnet/runtime/pull/1929#issuecomment-578290763

The problem is in the Windows x86 path here: https://github.com/dotnet/coreclr/pull/24199/files#diff-5eb922d9071dbbd2c84a9fa5f4468ea0R1880

We are missing a check like this: https://github.com/dotnet/coreclr/pull/24199/files#diff-d5e4cb27da3539140a16dc576906b925R1857

It results into unwinding too many Frames that sometime leads to asserts about corrupted Frame chain and crashes.

### PR DESCRIPTION
**Pull request by janvorli**
There is a bug in InlinedCallFrame popping on x86 during EH with R2R
compiled code. The code is popping this frame if it is at the top of
the explicit frames stack before executing catch handler. But it
is missing a check to see if the frame was actually in the unwound part
of the stack. So in some corner cases, it can end up popping a frame
that belongs to an active pinvoke somewhere up the call chain.

The fix is to do the popping only if the InlinedCallFrame is located at
an address smaller than the resume ESP.

Close #2240

### CODE REVIEW

**Comment by janvorli** [comment]
Fixes a problem blocking PR #1929. I've ran corefx tests on Windows x86 with this fix applied on top of the changes from that PR and they have passed.

cc: @clamp03.

File: src/coreclr/src/vm/i386/excepx86.cpp [hunk 1]
```diff
@@ -1868,8 +1868,10 @@ NOINLINE LPVOID COMPlusEndCatchWorker(Thread * pThread)
     // Sync managed exception state, for the managed thread, based upon any active exception tracker
     pThread->SyncManagedExceptionState(fIsDebuggerHelperThread);
 
-    if (InlinedCallFrame::FrameHasActiveCall(pThread->m_pFrame))
+    if ((pThread->m_pFrame < esp) && InlinedCallFrame::FrameHasActiveCall(pThread->m_pFrame))
     {
+        // The current explicit frame is below the resume esp and it is an inlined call frame with an active call.
+        //
```
Comment (jkotas) [inline src/coreclr/src/vm/i386/excepx86.cpp]: Nit: You can fix typos in the comment below while you are on it:

unlined 
pinovoke

File: src/coreclr/src/vm/i386/excepx86.cpp [hunk 2]
```diff
@@ -1868,8 +1868,10 @@ NOINLINE LPVOID COMPlusEndCatchWorker(Thread * pThread)
     // Sync managed exception state, for the managed thread, based upon any active exception tracker
     pThread->SyncManagedExceptionState(fIsDebuggerHelperThread);
 
-    if (InlinedCallFrame::FrameHasActiveCall(pThread->m_pFrame))
+    if ((pThread->m_pFrame < esp) && InlinedCallFrame::FrameHasActiveCall(pThread->m_pFrame))
```
Comment (jkotas) [inline src/coreclr/src/vm/i386/excepx86.cpp]: How does this work?

I believe that we need to check whether the frame is within the method that we are resuming into, ie we need to check whether `pFrame < callerESP`.

Comment (janvorli) [reply src/coreclr/src/vm/i386/excepx86.cpp]: Hmm, you are right that this would not work for the case when the location we resume to is in the same function as the pinvoke frame. It works when it is anywhere up the call chain.

Comment (jkotas) [reply src/coreclr/src/vm/i386/excepx86.cpp]: I would not expect the current version of the change to fix the problem.

Anyway, this is not a new problem. #1929 was just unlucky to hit it. I have opened #2240 to track it and added workaround to #1929 to make forward progress.

**Comment by jkotas** [comment]
Could you please also delete the workaround for this bug from AssemblyNative::InternalLoad ?

**Comment by janvorli** [comment]
@jkotas I've removed the workaround for the issue, can you please take a look again?

**Review by jkotas — APPROVED** [review]
Thanks!
