### PR TITLE
ILC: track concrete dependencies of open generic methods

### LINKED ISSUE #120847: IL scanner VTable error
### Description

 I tried experimental NativeAOT for Android with my framework and hit this problem.

When building I get:

```
EXEC : error VTable of type 'Impl`3<MugenMvvm.Views.Interfaces.IViewManager,
MugenMvvm.Api.Interfaces.IApiProviderComponent`1<MugenMvvm.Views.Interfaces.IViewManager>,
MugenMvvm.Bindings.Api.BindingBuilderRequest`1<MugenMvvm.Common.InlineObjectTuple>>'
not computed by the IL scanner. You can work around by running the compilation with scanner disabled.
```

This generic combination isn’t actually used at runtime. As a workaround I added an explicit reference so the type is kept:

```csharp
public static class LinkerInclude
{
    public static void Include()
    {
        // Workaround for AOT linking / IL scanner
        _ = ComponentDescriptor.Impl<
                IViewManager,
                IApiProviderComponent<IViewManager>,
                BindingBuilderRequest<InlineObjectTuple>
            >.EmptyInstance;
    }
}
```

I have attached zip files from `<IlcArg Include="--make-repro-path:` as suggested here https://github.com/dotnet/android/issues/10546

[935452972_NativeAOT.Android.zip](https://github.com/user-attachments/files/22973181/935452972_NativeAOT.Android.zip)

[2113164319_NativeAOT.Android.zip](https://github.com/user-attachments/files/22973183/2113164319_NativeAOT.Android.zip)

### Reproduction Steps

Build and run the android app from the link https://github.com/vyacheslav-volkov/NativeAot.Test

### Expected behavior

No errors

### Actual behavior

Build fails with the error

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sbomer**
When RyuJit inlines a generic callee into a callsite where some of the generic arguments are concrete, the code generation may require concrete dependencies of the inlinee. We need to ensure that the scanner tracks such dependencies statically so that they are available for codegen.

For example:
```csharp
using System;
using System.Runtime.CompilerServices;

class Program
{
    static void Main()  
    {
        var r = typeof(Program).GetMethod(nameof(Caller)).MakeGenericMethod(GetStringType()).Invoke(null, []);
    }

    static Type GetStringType() => typeof(string);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    static string Callee<T, U>() => new Container<T>().ToString();

    public static string Caller<T>() => Callee<object, T>();
}

class Container<T>;
```

Here the concrete instantiation `Caller<string>` is not discovered statically - but when `Callee<object, T>()` is inlined into the canonical code for `Caller<__Canon>`, this results in a concrete reference to `Container<object>` from `Caller<__Canon>`, so we need to keep any generic dictionary dependencies of `Callee<object, T>`.

This change adds additional tracking of open generic methods to ensure that any concrete dependencies are preserved during scanning. It adds tracking similar to what's done by `ShadowConcreteMethodNode`  - now there's a new `ShadowNonConcreteMethodNode` that tracks non-concrete (not fully instantiated) generics. There are three entry points where we needed additional tracking for open generics:
- When reflecting over a generic method
- When encountering a GVM (this was the case in the original issue)
- When we see a direct call to a generic method

Now when `ShadowNonConcreteMethodNode` is used to instantiate generic dependencies of runtime-determined nodes, the resulting instantiation may not be concrete. We handle this by attempting the instantiation, and if the result is concrete we track the dependency as normal. If the result is not concrete, then we either track it as another `ShadowNonConcreteMethodNode` (if the result is a generic method) or ignore it.

Fixes https://github.com/dotnet/runtime/issues/120847

### CODE REVIEW

File: src/coreclr/tools/Common/Compiler/DependencyAnalysis/ShadowGenericMethodNode.cs [hunk 1]
```diff
@@ -13,21 +13,21 @@
 namespace ILCompiler.DependencyAnalysis
 {
     /// <summary>
-    /// Represents a concrete method on a generic type (or a generic method) that doesn't
+    /// Represents a generic method on a generic type (or a generic method) that doesn't
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/Compiler/DependencyAnalysis/ShadowGenericMethodNode.cs]: "generic method on a generic type (or a generic method)".

The new name of this node is problematic for the reasons seen in the updated comment - when we say "generic method" in the compiler, we mean a method with `HasInstantiation==true`. This node models methods with some genericness, but not just generic methods.

File: src/coreclr/tools/Common/Compiler/DependencyAnalysis/ShadowConcreteMethodNode.cs [hunk 2]
```diff
@@ -42,12 +42,11 @@ public void AppendMangledName(NameMangler nameMangler, Utf8StringBuilder sb)
         public override bool StaticDependenciesAreComputed
             => CanonicalMethodNode.StaticDependenciesAreComputed;
 
-        public ShadowConcreteMethodNode(MethodDesc method, IMethodNode canonicalMethod)
+        public ShadowGenericMethodNode(MethodDesc method, IMethodNode canonicalMethod)
         {
-            Debug.Assert(!method.IsSharedByGenericInstantiations);
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/Compiler/DependencyAnalysis/ShadowConcreteMethodNode.cs:47]: I would want to keep these assert - they prevent nonsensical graphs.

I think we should split this class into multiple classes - one that tracks fully instantiated things (can keep calling it `ShadowConcreteMethod`) - this one can still assert all these things. And add one that is not fully specialized. There may be a common base type. I think separate node would also result in more readable dependency graphs.

File: src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs [hunk 3]
```diff
@@ -126,12 +127,117 @@ private bool TriggersLazyStaticConstructor(NodeFactory factory)
...
+            return false;
+        }
+
         public IEnumerable<DependencyListEntry> InstantiateDependencies(NodeFactory factory, Instantiation typeInstantiation, Instantiation methodInstantiation)
         {
             DependencyList result = new DependencyList();
 
             var lookupContext = new GenericLookupResultContext(_dictionaryOwner, typeInstantiation, methodInstantiation);
 
+            bool isNotConcreteInstantiation = ContainsCanonicalTypes(typeInstantiation) || ContainsCanonicalTypes(methodInstantiation);
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs]: I think if we split ShadowConcreteMethod to two classes, we could add a bool to this method that tells what kind of dependencies we want (and we don't need to recompute it from ContainsCanonicalTypes

File: src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs [hunk 4]
```diff
@@ -796,7 +796,7 @@ private void ImportCall(ILOpcode opcode, int token)
                             _dependencies.Add(instParam, reason);
                         }
 
-                        _dependencies.Add(_factory.CanonicalEntrypoint(targetMethod), reason);
+                        _dependencies.Add(_factory.ShadowGenericMethod(concreteMethod), reason);
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs]: I think we only need to create a shadow if AcquiresInstMethodTableFromThis is true. There is a cascade of ifs on lines 780-792. I think we can add `else if (targetMethod.AcquiresInstMethodTableFromThis())` and only add the shadow method there. This should somewhat limit the nodes in the graph this adds (it feels like this is still adding a lot).

File: src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs [hunk 5]
```diff
@@ -126,12 +127,117 @@ private bool TriggersLazyStaticConstructor(NodeFactory factory)
...
+
+            if (isNotConcreteInstantiation)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs]: I wonder if we could move the logic in this `if` block into the individual `GenericLookupResult.GetTarget` overrides - maybe add a `bool isNotConcreteInstantiation` parameter and have it return null if the result would be canonical?

File: src/coreclr/tools/Common/Compiler/DependencyAnalysis/ShadowConcreteMethodNode.cs (hunk 2 above)
Comment (sbomer) [reply src/coreclr/tools/Common/Compiler/DependencyAnalysis/ShadowConcreteMethodNode.cs:47]: Split into ShadowConcreteMethodNode and ShadowNonConcreteMethodNode (with shared base ShadowMethodNode)

File: src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs (hunk 4 above)
Comment (sbomer) [reply src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs]: Nice, I was wondering if there was a more specific condition to check.

File: src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs (hunk 5 above)
Comment (sbomer) [reply src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs]: I had that idea too, but hesitated because I was afraid the GetTarget change would be too viral. It doesn't look as bad as I thought.

File: src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/HandleCallAction.cs [hunk 6]
```diff
@@ -765,7 +765,7 @@ private sealed class MakeGenericTypeSite : INodeWithRuntimeDeterminedDependencie
 
             public MakeGenericTypeSite(TypeDesc type) => _type = type;
 
-            public IEnumerable<DependencyNodeCore<NodeFactory>.DependencyListEntry> InstantiateDependencies(NodeFactory factory, Instantiation typeInstantiation, Instantiation methodInstantiation)
+            public IEnumerable<DependencyNodeCore<NodeFactory>.DependencyListEntry> InstantiateDependencies(NodeFactory factory, Instantiation typeInstantiation, Instantiation methodInstantiation, bool isConcreteInstantiotion)
```
Comment (sbomer) [inline src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/HandleCallAction.cs]:
```suggestion
            public IEnumerable<DependencyNodeCore<NodeFactory>.DependencyListEntry> InstantiateDependencies(NodeFactory factory, Instantiation typeInstantiation, Instantiation methodInstantiation, bool isConcreteInstantiation)
```

File: src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs [hunk 7]
```diff
@@ -791,6 +791,10 @@ private void ImportCall(ILOpcode opcode, int token)
                         {
                             instParam = GetGenericLookupHelper(ReadyToRunHelperId.TypeHandle, runtimeDeterminedMethod.OwningType);
                         }
+                        else if (targetMethod.AcquiresInstMethodTableFromThis() && concreteMethod.IsSharedByGenericInstantiations)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs]: Is the `concreteMethod.IsSharedByGenericInstantiations` part needed? I don't immediately see how we could end up here if this is `false`.

File: src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs [hunk 8]
```diff
@@ -126,10 +127,19 @@ private bool TriggersLazyStaticConstructor(NodeFactory factory)
             return factory.PreinitializationManager.HasLazyStaticConstructor(type.ConvertToCanonForm(CanonicalFormKind.Specific));
         }
 
-        public IEnumerable<DependencyListEntry> InstantiateDependencies(NodeFactory factory, Instantiation typeInstantiation, Instantiation methodInstantiation)
+        private static bool ContainsCanonicalTypes(Instantiation instantiation)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs]: This looks unused.

File: src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs [hunk 9]
```diff
@@ -10,6 +10,7 @@
 using Internal.TypeSystem;
 
 using ILCompiler.DependencyAnalysisFramework;
+using Internal.ReadyToRunConstants;
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ReadyToRunGenericHelperNode.cs]: Is this used?

File: src/coreclr/tools/Common/Compiler/DependencyAnalysis/ShadowNonConcreteMethodNode.cs [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+using Internal.Text;
+using Internal.TypeSystem;
+
+using Debug = System.Diagnostics.Debug;
+
+namespace ILCompiler.DependencyAnalysis
+{
+    /// <summary>
+    /// Represents a non-concrete method (not fully instantiated) for the purpose of
+    /// tracking dependencies.
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/Compiler/DependencyAnalysis/ShadowNonConcreteMethodNode.cs:17]:
```suggestion
    /// tracking dependencies of inlinees.
```

**Review by MichalStrehovsky — COMMENTED** [review]
Looks good otherwise! I'll merge main into this so I can run size measurements over in rt-sz, just in case something unexpected pops up.

**Comment by MichalStrehovsky** [comment]
> I'll merge main into this so I can run size measurements over in rt-sz, just in case something unexpected pops up.

Ah, I misinterpreted what rt-sz was complaining about. You already merged main before, so we had #122227 in this brach, but the SDK produced from dotnet/dotnet still doesn't have this, so rt-sz is failing with `EXEC : error : Unknown stack trace data: --scanreflection`. Merging main now obviously didn't resolve this. We need flow from runtime into dotnet/dotnet to resume :(.

File: src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs (hunk 7 above)
Comment (sbomer) [reply src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs]: You're right, this looks redundant with an earlier check - thanks!

**Comment by MichalStrehovsky** [comment]
# Size statistics

Pull request dotnet/runtime#122012

| Project | Size before | Size after | Difference |
|---------|-------------|------------|------------|
| TodosApi-linux | [ 24362616 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136640882) | [ 24362616 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136641738) | 0 |
| TodosApi-windows | [ 25836032 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136661036) | [ 25836032 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136654475) | 0 |
| avalonia.app-linux | [ 18826864 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136640347) | [ 18826864 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136634654) | 0 |
| avalonia.app-windows | [ 19388928 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136645399) | [ 19388928 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136646422) | 0 |
| hello-linux | [ 1146368 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136633911) | [ 1146368 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136630654) | 0 |
| hello-minimal-linux | [ 1006856 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136630340) | [ 1006856 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136630064) | 0 |
| hello-minimal-windows | [ 772608 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136643109) | [ 772608 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136639812) | 0 |
| hello-windows | [ 930816 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136638347) | [ 930816 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136636447) | 0 |
| kestrel-minimal-linux | [ 5241464 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136631085) | [ 5241464 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136631287) | 0 |
| kestrel-minimal-windows | [ 4820992 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136643514) | [ 4820992 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136641058) | 0 |
| reflection-linux | [ 1822128 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136633839) | [ 1822128 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136629956) | 0 |
| reflection-windows | [ 1689088 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136642006) | [ 1689088 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136641962) | 0 |
| webapiaot-linux | [ 9567216 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136633097) | [ 9567216 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136631938) | 0 |
| webapiaot-windows | [ 10180608 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136639327) | [ 10180608 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136652101) | 0 |
| winrt-component-minimal-windows | [ 720896 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136640377) | [ 720896 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/21021318839/artifacts/5136639807) | 0 |

**Review by MichalStrehovsky — APPROVED** [review]
Nice!
