### PR TITLE
Fix JitDoSsa=0

### LINKED ISSUE #62251: Assertion failed 'lclVarType != TYP_UNDEF' during 'Lowering nodeinfo'
```c#
// Found by Antigen


using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
        public double double_0;
    }
    public struct S2
    {
    }
    static short s_short_8 = 92;
    static S1 s_s1_17 = new S1();
    double double_23 = 0.041666666666666664;
    S1 s1_33 = new S1();
    S2 s2_34 = new S2();
    public S1 Method11(S1 p_s1_293, out S1 p_s1_294, ref double p_double_295, S1 p_s1_296, ref short p_short_297, ref S1 p_s1_298, ref S2 p_s2_299, S2 p_s2_300, out sbyte p_sbyte_301)
    {
        unchecked
        {
            sbyte sbyte_310 = 92;
            p_s1_294 = s_s1_17;
            p_sbyte_301 = sbyte_310 -= 15+4;
            return p_s1_293;
        }
    }
    public void Method0()
    {
        unchecked
        {
            sbyte sbyte_2624 = 0;
            S1 s1_2630 = new S1();
            S1 s1_2631 = s1_2630;
            s_s1_17 = Method11(s_s1_17, out s_s1_17, ref double_23, s1_2631, ref s_short_8, ref s1_33, ref s2_34, s2_34, out sbyte_2624);
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}

/*
Got output diff:
--------- Baseline ---------  

Environment:



--------- Test ---------  

Environment:

set COMPlus_TieredCompilation=0
set COMPlus_JitDoSsa=0
set COMPlus_AltJitName=clrjit_universal_arm_x86.dll
set COMPlus_AltJit=Method11

Assert failure(PID 34572 [0x0000870c], Thread: 17180 [0x431c]): Assertion failed 'lclVarType != TYP_UNDEF' in 'TestClass:Method11(S1,byref,byref,S1,byref,byref,byref,S2,byref):S1:this' during 'Lowering nodeinfo' (IL size 26)
    File: D:\git\dotnet-runtime\src\coreclr\jit\lower.cpp Line: 3451
    Image: d:\git\dotnet-runtime\artifacts\tests\coreclr\windows.x86.Checked\tests\Core_Root\CoreRun.exe
*/

```

### PR DESCRIPTION
**Pull request by BruceForstall**
If we don't do SSA, we don't do liveness, but Lowering depends on
liveness-created lvDoNotEnregister, so if we're not doing SSA,
at least run local var liveness. Note that in the MinOpts case,
`lvSetMinOptsDoNotEnreg()` sets all locals to do-not-enregister.

Fixes #62251

### CODE REVIEW

File: src/coreclr/jit/compiler.cpp [hunk 1]
```diff
@@ -4940,9 +4947,12 @@ void Compiler::compCompile(void** methodCodePtr, uint32_t* methodCodeSize, JitFl
...
             }
 
-            // Remove common sub-expressions
-            //
-            DoPhase(this, PHASE_OPTIMIZE_VALNUM_CSES, &Compiler::optOptimizeCSEs);
+            if (doCse)
+            {
+                // Remove common sub-expressions
+                //
+                DoPhase(this, PHASE_OPTIMIZE_VALNUM_CSES, &Compiler::optOptimizeCSEs);
```
Comment (BruceForstall) [inline src/coreclr/jit/compiler.cpp:4954]: This is extra: there's no reason to run CSE if we haven't built value numbers.

**Comment by BruceForstall** [comment]
@kunalspathak @dotnet/jit-contrib PTAL

**Review by markples — APPROVED** [review]

**Review by kunalspathak — APPROVED** [review]
LGTM
