### PR TITLE
[browser][coreCLR] enable System.Runtime.Tests on CI as Release build

### LINKED ISSUE #123030: [browser][coreCLR] Fix IL trimming in publish
```
    <EnableAggressiveTrimming>true</EnableAggressiveTrimming>
    <PublishTrimmed>true</PublishTrimmed>
```

```
ThreadPool.BackgroundJobHandler failed
    at System.Environment.<FailFast>g____PInvoke|11_0(System.Runtime.CompilerServices.StackCrawlMarkHandle, UInt16*, System.Runtime.CompilerServices.ObjectHandleOnStack, UInt16*)
    at System.Environment.FailFast(System.Runtime.CompilerServices.StackCrawlMarkHandle, System.String, System.Runtime.CompilerServices.ObjectHandleOnStack, System.String)
    at System.Environment.FailFast(System.Threading.StackCrawlMark ByRef, System.String, System.Exception, System.String)
    at System.Environment.FailFast(System.String, System.Exception)
    at System.Threading.ThreadPool.BackgroundJobHandler()
 System.NotSupportedException: Linked away
    at System.Threading.Thread.ResetThreadPoolThread()
    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### PR DESCRIPTION
**Pull request by pavelsavara**
### CoreCLR
- few more signatures for `callhelpers-interp-to-managed.cpp`
- workaround for https://github.com/dotnet/runtime/issues/121955
- roots Thread .ctor from IL trimming

### WasmTestRunner
- workaround for https://github.com/dotnet/runtime/issues/122972

### Emscripten build
- fix JS minification problem with `AJSDCE`
- make `BrowserHost-Static` private linking too
- reduce `EmccExportedRuntimeMethod` and other exports

### CI & MSBuild
- switch `runtime` pipeline to `Release`
- add `wasm-coreclr-library-tests.yml`
- enable `WasmTestLogExitCode`, `WasmTestAppendElementOnExit`, `WasmTestExitOnUnhandledError` for library tests on CoreCLR
- install chrome for CoreCLR tests
- disabled IL trimming https://github.com/dotnet/runtime/issues/123030

### System.Runtime.Tests
- I disabled bunch of failing tests with [[ActiveIssue]](https://github.com/dotnet/runtime/issues/123011)

Fixes https://github.com/dotnet/runtime/issues/120707
Fixes https://github.com/dotnet/runtime/issues/123030

### CODE REVIEW

File: src/coreclr/vm/wasm/callhelpers-interp-to-managed.cpp [hunk 1]
```diff
@@ -569,15 +650,19 @@ const StringToWasmSigThunk g_wasmThunks[] = {
     { "dddd", (void*)&CallFunc_F64_F64_F64_RetF64 },
     { "ddi", (void*)&CallFunc_F64_I32_RetF64 },
     { "di", (void*)&CallFunc_I32_RetF64 },
+    { "dii", (void*)&CallFunc_I32_I32_RetF64 },
```
Comment (radekdoulik) [inline src/coreclr/vm/wasm/callhelpers-interp-to-managed.cpp:653]: Curious, are these new calls in BCL or the test lib? If the later, please add the signatures and comment to https://github.com/dotnet/runtime/blob/main/src/tasks/WasmAppBuilder/coreclr/ManagedToNativeGenerator.cs#L72-L90, so that we can regenerate the helpers just with BCL.

File: src/libraries/System.Runtime/tests/System.Runtime.Tests/System/DateTimeTests.cs [hunk 2]
```diff
@@ -2702,6 +2702,7 @@ public void ToType_DateTime_ReturnsExpected()
         }
 
         [Fact]
+         [ActiveIssue("https://github.com/dotnet/runtime/issues/123011", typeof(PlatformDetection), nameof(PlatformDetection.IsBrowser), nameof(PlatformDetection.IsCoreCLR))]
```
Comment (radekdoulik) [inline src/libraries/System.Runtime/tests/System.Runtime.Tests/System/DateTimeTests.cs]: nit, whitespace before the `ActiveIssue` attributes

File: src/coreclr/vm/wasm/callhelpers-interp-to-managed.cpp (hunk 1 above)
Comment (pavelsavara) [reply src/coreclr/vm/wasm/callhelpers-interp-to-managed.cpp:653]: Ok, will do. This is delegates from `System.Runtime.Tests` and also from `System.Runtime.InteropServices.JavaScript.Tests`

File: src/mono/wasm/testassets/WasmBrowserRunMainOnly/WasmBrowserRunMainOnly.csproj [hunk 3]
```diff
@@ -5,6 +5,15 @@
     <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
   </PropertyGroup>
 
+  <!-- TODO-WASM https://github.com/dotnet/runtime/issues/120248 (CoreCLR on wasm defaults) -->
```
Comment (maraf) [inline src/mono/wasm/testassets/WasmBrowserRunMainOnly/WasmBrowserRunMainOnly.csproj]: Is this because of testing locally?

File: src/libraries/Common/tests/WasmTestRunner/WasmTestRunner.cs [hunk 4]
```diff
@@ -31,6 +33,14 @@ public static Task<int> Main(string[] args)
     }
 #endif
 
+    // workaround for https://github.com/dotnet/runtime/issues/122972
```
Comment (maraf) [inline src/libraries/Common/tests/WasmTestRunner/WasmTestRunner.cs]:
```suggestion
    // WASM-TODO: workaround for https://github.com/dotnet/runtime/issues/122972
```

File: eng/pipelines/common/templates/browser-wasm-coreclr-build-tests.yml [hunk 5]
```diff
@@ -42,9 +42,9 @@ jobs:
       jobParameters:
         dependsOn:
           - ${{ if eq(platform, 'browser_wasm') }}:
-            - build_browser_wasm_linux_Debug_AllSubsets_CoreCLR
```
Comment (maraf) [inline eng/pipelines/common/templates/browser-wasm-coreclr-build-tests.yml:45]: If CoreCLR WASM VM has problem with trimming, this is the part that makes it break; whereas the build config for WBT (line 18) should be fine to switch to Release. Am I correct?

**Comment by pavelsavara** [comment]
Passing WBT [Log](https://helix.dot.net/api/jobs/27ffd07e-c8c0-4556-b27d-0fa926389e20/workitems/NoWorkload-ST-Wasm.Build.Tests/files/console.44a62e7f.log?api-version=2019-06-17)
Passing System.Runtime.Tests [Log](https://helix.dot.net/api/jobs/ffe2a8ec-d0ac-4b71-b346-b13c095651a2/workitems/WasmTestOnChrome-ST-System.Runtime.Tests/files/console.487fb9e0.log?api-version=2019-06-17)

File: src/mono/wasm/testassets/WasmBrowserRunMainOnly/WasmBrowserRunMainOnly.csproj (hunk 3 above)
Comment (pavelsavara) [reply src/mono/wasm/testassets/WasmBrowserRunMainOnly/WasmBrowserRunMainOnly.csproj]: removed

File: eng/pipelines/common/templates/browser-wasm-coreclr-build-tests.yml (hunk 5 above)
Comment (pavelsavara) [reply eng/pipelines/common/templates/browser-wasm-coreclr-build-tests.yml:45]: This was the reason for trimming problem https://github.com/dotnet/runtime/issues/123030#issuecomment-3738833358

**Review by maraf — APPROVED** [review]

**Review by radekdoulik — APPROVED** [review]
Thank you! LGTM
