### PR TITLE
Omit ErrorInformation from ManagementException binary serialization

### LINKED ISSUE #2116: System.Management.ManagementException fails to serialize
ManagementException is currently decorated with SerializableAttribute.  However, it contains a ManagementBaseObject field, and the ManagementBaseObject class is not currently decorated with SerializableAttribute.  As a consequence, attempts to serialize ManagementException fail:

```System.Runtime.Serialization.SerializationException: Type 'System.Management.ManagementBaseObject' in Assembly 'System.Management, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.```

### PR DESCRIPTION
**Pull request by fagnercarvalho**
Fixes #2116

Using the `NonSerialized` attribute wouldn't make sense since the `ManagementException` class is overriding the `GetObjectData` method.

### CODE REVIEW

File: src/libraries/System.Management/src/System/Management/ManagementException.cs [hunk 1]
```diff
@@ -721,7 +720,6 @@ public override void GetObjectData(SerializationInfo info, StreamingContext cont
         {
             base.GetObjectData(info, context);
             info.AddValue("errorCode", errorCode);
-            info.AddValue("errorObject", errorObject);
```
Comment (GrabYourPitchforks) [inline src/libraries/System.Management/src/System/Management/ManagementException.cs:724]: Consider serializing an explicit _null_ value for this field for compat. Otherwise the `ManagementException` deserialization ctor will throw in .NET Framework apps when given these payloads, as the ctor always expects an "errorObject" key to be present in the `SerializationInfo` dictionary.

Comment (fagnercarvalho) [reply src/libraries/System.Management/src/System/Management/ManagementException.cs:724]: Ah, sure, this makes sense, will do this change.

**Review by GrabYourPitchforks — APPROVED** [review]
LGTM, but awaiting sign off from area owners. Thanks!

**Comment by danmosemsft** [comment]
@fagnercarvalho could you please verify the test passes, on both .NET Framework and .NET 5, if you didn't already?

You need to include `/p:Outerloop=true` and in one case `/p:BuildTargetFramework=net472` as per https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md

**Review by danmoseley — APPROVED** [review]

**Review by Anipik — APPROVED** [review]

**Comment by fagnercarvalho** [comment]
Hello @danmosemsft!

I just executed the tests but the default was set to .NET 6 and I'm not able to run the tests for .NET Framework 4.7.2, only 4.8.

Here are the commands I executed:

```
.\build.cmd
dotnet build src\libraries\System.Management\tests\System.Management.Tests.csproj /p:BuildTargetFramework=net48
dotnet build src\libraries\System.Management\tests\System.Management.Tests.csproj /t:Test /p:Outerloop=true
```

The last command is running tests for both .NET 6 and .NET Framework 4.8.

All tests are passing successfully.

Let me know if I need to do anything else.

**Comment by danmosemsft** [comment]
Thanks for the contribution!
