### PR TITLE
JIT: Null out SSA def nodes upon removal in RBO

### LINKED ISSUE #108406: JIT: Assertion failed 'tree == stmt->GetRootNode()'
Failed in [Fuzzlyn](https://dev.azure.com/dnceng-public/public/_build?definitionId=149&_a=summary)/[20240929.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=821614)

```
- linux-arm64 checked
```

Repro:
```
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static int s_17;
    public static void Main()
    {
        var vr2 = (uint)ArmBase.ReverseElementBits(0);
        var vr3 = (ushort)s_17;
        bool vr4 = Crc32.ComputeCrc32(vr2, vr3) >= 1;
        bool vr5 = vr4;
        vr4 ^= true;
        if (vr4)
        {
            bool vr6 = default(bool);
            vr4 = vr6;
        }
        else
        {
            vr4 = !vr4;
        }

        System.Console.WriteLine(vr4);
        System.Console.WriteLine(vr5);
    }
}
```

Distinct assertion error:
```scala
JIT assert failed:
Assertion failed 'tree == stmt->GetRootNode()' in 'Program:M0()' during 'VN-based dead store removal' (IL size 776; hash 0xaf50ff37; FullOpts)

    File: /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp Line: 3597
```

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #108406. When removing redundant store nodes in RBO, we need to also update SSA definitions to no longer track the removed stores. Because call sites that use SSA definitions are responsible for null-checking the store node, the simplest method of removal is to null out the node pointer in the SSA def.

cc @dotnet/jit-contrib, @AndyAyersMS PTAL. I can include a regression test if you think it would be useful, but I think the new `DEBUG_DESTROY_NODE` gives us better coverage anyway.

### CODE REVIEW

File: src/coreclr/jit/redundantbranchopts.cpp [hunk 1]
```diff
@@ -2173,6 +2173,22 @@ bool Compiler::optRedundantRelop(BasicBlock* const block)
     if (!usedCopy)
     {
         fgRemoveStmt(block, candidateStmt);
+
+        // Make sure the removed store node isn't referenced in any SSA definitions
+        assert(candidateStmt->GetRootNode()->OperIs(GT_STORE_LCL_VAR));
+        GenTreeLclVarCommon* const rootNode = candidateStmt->GetRootNode()->AsLclVarCommon();
+
+        LclVarDsc* const varDsc = lvaGetDesc(rootNode);
```
Comment (AndyAyersMS) [inline src/coreclr/jit/redundantbranchopts.cpp:2181]: Since the local is in SSA you should be able to locate the `LclSsaVarDsc` directly. Something like:
```C++
unsigned const ssaNum = rootNode->GetSsaNum();
LclSsaVarDsc* const defDsc = varDsc->GetPerSsaData(ssaNum);
assert(defDsc->GetDefNode() == rootNode);
defDsc->SetDefNode(nullptr);
```

Comment (amanasifkhalid) [reply src/coreclr/jit/redundantbranchopts.cpp:2181]: Thanks, fixed

**Review by AndyAyersMS — APPROVED** [review]
