### PR TITLE
Fix store/load float LCL_FIELD with unaligned offsets on arm32.

### LINKED ISSUE #34170: Assertion failed 'offsetFitsInVectorMem(emitGetInsSC(id))'
Windows arm32 with:
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=1
```

From attempt to re-enable "runtime-coreclr jitstress" testing:
https://dev.azure.com/dnceng/public/_build/results?buildId=574937&view=results

```
    JIT\Methodical\explicit\coverage\expl_float_1_d\expl_float_1_d.cmd [FAIL]
      
      Assert failure(PID 7700 [0x00001e14], Thread: 10360 [0x2878]): Assertion failed 'offsetFitsInVectorMem(emitGetInsSC(id))' in 'TestApp:Main():int' during 'Generate code' (IL size 4230)
      
          File: F:\workspace\_work\1\s\src\coreclr\src\jit\emitarm.cpp Line: 465
          Image: D:\h\w\B77C09AB\p\CoreRun.exe
```

Tests:
```
JIT\Methodical\explicit\coverage\expl_float_1_d\expl_float_1_d.cmd
JIT\Methodical\explicit\coverage\expl_float_1_r\expl_float_1_r.cmd
```

category:correctness
theme:alignment
skill-level:intermediate
cost:medium

### PR DESCRIPTION
**Pull request by sandreenko**
Use lea to instantiate LCL_VAR address in a register.

Also, after the change we have better code size for the test, before lclmorph regression change:
```
IN0003: 000024  4B      addw    r3, sp, 0x828	// [V00 loc0]
IN0004: 000028  2B      adds    r3, r3, 1
```
now:
```
IN0003: 000024  4B      addw    r3, sp, 0x829
```

Commits:
feb321aafeb: Add an additional test for the issue.
cecd8e466bc: Reenable the test.
b91991bae2d: Fix arm32 access to unaligned float fields.

Fixes #34170.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

**Review by CarolEidt — APPROVED** [review]
LGTM. You might add a comment indicating that although Arm supports unaligned accesses, the offset must be aligned. Although, looking at the ARMv7-M Architecture Reference Manual it seems that the offset need only be a multiple of 4 for both the double and single case; I'm not sure that makes enough difference to optimize for the double case.

File: src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170.cs [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+{
+    // the field is aligned inside SimpleStruct.
+    public float field;
+}
+
+[StructLayout(LayoutKind.Explicit)]
+internal struct StructNonAlignedField
+{
+    // SimpleStruct is unaligned, so the result offset to its float field is unaligned.
+    [FieldOffset(1)]
```
Comment (sandreenko) [inline src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170.cs:68]: This access was failing before the PR that introduced #34990 because morph was generating `LCL_FLD` for it.

File: src/coreclr/src/jit/codegenarm.cpp [hunk 2]
```diff
@@ -998,13 +998,36 @@ void CodeGen::genCodeForStoreLclFld(GenTreeLclFld* tree)
...
-    emit->emitIns_S_R(ins, attr, data->GetRegNum(), varNum, offset);
+    regNumber dataReg = data->GetRegNum();
+    if (varTypeIsFloating(targetType) && ((offset % emitTypeSize(tree)) != 0))
+    {
+        regNumber addr = tree->ExtractTempReg();
+        emit->emitIns_R_S(INS_lea, attr, addr, varNum, offset);
+        if (targetType == TYP_FLOAT)
+        {
+            regNumber floatAsInt = tree->GetSingleTempReg();
+            emit->emitIns_R_R(INS_vmov_f2i, EA_4BYTE, floatAsInt, dataReg);
```
Comment (sandreenko) [inline src/coreclr/src/jit/codegenarm.cpp:1014]: It could be improved a little if we distinguish small and large offsets. In the small case that could be encoded into `INS_str` and for the large offset case that can use `rsGetRsvdReg` register. I decided not to do that in this bug fix PR.

**Comment by sandreenko** [comment]
> Although, looking at the ARMv7-M Architecture Reference Manual it seems that the offset need only be a multiple of 4 for both the double and single case; I'm not sure that makes enough difference to optimize for the double case.

Thanks, there are a few things that could be improved, but this one looks pretty safe to do in this PR. Added a commit that does that.

File: src/coreclr/src/jit/codegenarm.cpp [hunk 3]
```diff
@@ -998,13 +998,38 @@ void CodeGen::genCodeForStoreLclFld(GenTreeLclFld* tree)
...
+            emit->emitIns_R_R(INS_str, EA_4BYTE, floatAsInt, addr);
+        }
+        else
+        {
+            regNumber halfdoubleAsInt1 = tree->ExtractTempReg();
```
Comment (echesakovMSFT) [inline src/coreclr/src/jit/codegenarm.cpp:1021]: If you don't mind going one step further this could be optimized downto
```suggestion
            regNumber halfdoubleAsInt1 = tree->ExtractTempReg();
            regNumber halfdoubleAsInt2 = tree->GetSingleTempReg();
            assert (halfdoubleAsInt1 < halfdoubleAsInt2);
            emit->emitIns_R_R_R(INS_vmov_d2i, EA_8BYTE, halfdoubleAsInt1, halfdoubleAsInt2, dataReg);
            regMaskTP doubleAsIntMask = genRegMask(halfdoubleAsInt1) | genRegMask(halfdoubleAsInt2);
            emit->emitIns_R_I(INS_stm, EA_4BYTE, addr, doubleAsIntMask);
```

File: src/coreclr/src/jit/codegenarm.cpp [hunk 4]
```diff
@@ -998,13 +998,38 @@ void CodeGen::genCodeForStoreLclFld(GenTreeLclFld* tree)
...
+    emitAttr attr = emitTypeSize(targetType);
 
     assert(!data->isContained());
     genConsumeReg(data);
-    emit->emitIns_S_R(ins, attr, data->GetRegNum(), varNum, offset);
+    regNumber dataReg = data->GetRegNum();
+    if (varTypeIsFloating(targetType) && ((offset % emitTypeSize(TYP_FLOAT)) != 0))
+    {
+        // Arm supports unaligned access only for integer types,
+        // convert the storing floating data into 2 integer registers and write them as int.
```
Comment (echesakovMSFT) [inline src/coreclr/src/jit/codegenarm.cpp:1010]: This comment should be?
`// convert the storing floating data into 1 or 2 integer registers and write them as int.`

File: src/coreclr/src/jit/codegenarmarch.cpp [hunk 5]
```diff
@@ -1780,7 +1780,39 @@ void CodeGen::genCodeForLclFld(GenTreeLclFld* tree)
...
+
+        if (targetType == TYP_FLOAT)
+        {
+            regNumber floatAsInt = tree->GetSingleTempReg();
+            emit->emitIns_R_R(INS_ldr, EA_4BYTE, floatAsInt, addr);
+            emit->emitIns_R_R(INS_vmov_i2f, EA_4BYTE, targetReg, floatAsInt);
+        }
+        else
+        {
+            regNumber halfdoubleAsInt1 = tree->ExtractTempReg();
```
Comment (echesakovMSFT) [inline src/coreclr/src/jit/codegenarmarch.cpp:1802]: Same here - could potentially be one instruction less
```suggestion
            regNumber halfdoubleAsInt1 = tree->ExtractTempReg();
            regNumber halfdoubleAsInt2 = tree->GetSingleTempReg();
            assert (halfdoubleAsInt1 < halfdoubleAsInt2);
            regMaskTP doubleAsIntMask = genRegMask(halfdoubleAsInt1) | genRegMask(halfdoubleAsInt2);
            emit->emitIns_R_I(INS_ldm, EA_4BYTE, addr, doubleAsIntMask);
            emit->emitIns_R_R_R(INS_vmov_d2i, EA_8BYTE, halfdoubleAsInt1, halfdoubleAsInt2, dataReg);
```
However, I am not sure how well instruction ldm is supported by emitter - I looked briefly and couldn't find an implementation for this in emitarm.cpp.

File: src/coreclr/src/jit/lsrabuild.cpp [hunk 6]
```diff
@@ -3119,9 +3119,28 @@ int LinearScan::BuildStoreLoc(GenTreeLclVarCommon* storeLoc)
...
 // Third, use internal registers.
-#ifdef FEATURE_SIMD
+#ifdef TARGET_ARM
+
+    var_types fieldType = storeLoc->TypeGet();
+    if (storeLoc->OperIs(GT_STORE_LCL_FLD) && varTypeIsFloating(fieldType))
+    {
+        GenTreeLclFld* fld    = storeLoc->AsLclFld();
+        uint16_t       offset = fld->GetLclOffs();
+        if ((offset % emitTypeSize(TYP_FLOAT)) != 0)
```
Comment (echesakovMSFT) [inline src/coreclr/src/jit/lsrabuild.cpp:3129]: Perhaps do this for better readability?

```c++
const bool isOffsetMisaligned = (offset % emitTypeSize(TYP_FLOAT)) != 0;
if (isOffsetMisaligned)
{
```

**Review by echesakov — APPROVED** [review]
Looks Good

File: src/coreclr/src/jit/codegenarm.cpp (hunk 3 above)
Comment (echesakovMSFT) [reply src/coreclr/src/jit/codegenarm.cpp:1021]: Not worth doing this now

File: src/coreclr/src/jit/lsrabuild.cpp (hunk 6 above)
Comment (sandreenko) [reply src/coreclr/src/jit/lsrabuild.cpp]: Extracted `IsOffsetMisaligned`.

**Review by CarolEidt — APPROVED** [review]
Still LGTM

**Comment by sandreenko** [comment]
The newly added test failed on arm32 linux and it does not fail on my arm32 windows, will have to investigate it futher.

File: src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170.cs [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+
+[StructLayout(LayoutKind.Explicit)]
+internal struct FloatNonAlignedFieldWithSmallOffset
+{
+    [FieldOffset(1)]
+    public float field;
+
+    public FloatNonAlignedFieldWithSmallOffset(float a)
+    {
+        field = a;
```
Comment (sandreenko) [inline src/coreclr/tests/src/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170.cs:18]: that field store was represented as `IND float(ADD byref(LCL_VAR byref this, CNT_INT 1))` and we did not catch it in morph, so it was another issue, that was failing before `LCL_FLD` changes. I made a fix in morph to catch this pattern as well.

File: src/coreclr/src/jit/morph.cpp [hunk 8]
```diff
@@ -13076,19 +13092,6 @@ GenTree* Compiler::fgMorphSmpOp(GenTree* tree, MorphAddrContext* mac)
                             {
                                 break;
                             }
-
-#ifdef TARGET_ARM
```
Comment (sandreenko) [inline src/coreclr/src/jit/morph.cpp:13080]: that block was under `opts.OptimizationEnabled()`, but it was required for correctness, also it did not need to forbid the optimization, so I moved it up and relaxed the condition, so we mark more `IND` as `GTF_IND_UNALIGNED`, for example, `IND(ADD(LCL_VAR, CNT_INT offset))`.

We still can force jit to generate an instruction that requires floating alignment and get runtime error, for example, with Unsafe API, but it is defiantly not a part of this regression fix, it is another preexisting issue.

**Comment by sandreenko** [comment]
Merged, thanks @echesakovMSFT and @CarolEidt for the help with debugging and reviews.
