### PR TITLE
Fix all runtime IL generation paths from passing GC types to unmanaged function calls.

### LINKED ISSUE #34279: AV in WKS::gc_heap::relocate_address
Hit in `Common.Tests` on Windows x86 Checked in #34261:

```
ntdll!KiUserExceptionDispatcher+0xf [d:\rs1\minkernel\ntos\rtl\i386\userdisp.asm @ 597] 
coreclr!WKS::tree_search+0x6 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 24978] 
coreclr!WKS::gc_heap::relocate_address+0x5e [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 25068] 
coreclr!WKS::GCHeap::Relocate+0x45 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 36864] 
coreclr!PromoteCarefully+0x83 [F:\workspace\_work\1\s\src\coreclr\src\vm\siginfo.cpp @ 4875] 
coreclr!GcEnumObject+0x4b [F:\workspace\_work\1\s\src\coreclr\src\vm\gcenv.ee.common.cpp @ 167] 
coreclr!EECodeManager::EnumGcRefs+0xc48 [F:\workspace\_work\1\s\src\coreclr\src\vm\eetwain.cpp @ 4702] 
coreclr!GcStackCrawlCallBack+0x152 [F:\workspace\_work\1\s\src\coreclr\src\vm\gcenv.ee.common.cpp @ 290] 
coreclr!Thread::MakeStackwalkerCallback+0x48 [F:\workspace\_work\1\s\src\coreclr\src\vm\stackwalk.cpp @ 841] 
coreclr!Thread::StackWalkFramesEx+0x193 [F:\workspace\_work\1\s\src\coreclr\src\vm\stackwalk.cpp @ 917] 
coreclr!Thread::StackWalkFrames+0x159 [F:\workspace\_work\1\s\src\coreclr\src\vm\stackwalk.cpp @ 1001] 
coreclr!ScanStackRoots+0x1e9 [F:\workspace\_work\1\s\src\coreclr\src\vm\gcenv.ee.cpp @ 146] 
coreclr!GCToEEInterface::GcScanRoots+0xe4 [F:\workspace\_work\1\s\src\coreclr\src\vm\gcenv.ee.cpp @ 175] 
coreclr!WKS::gc_heap::relocate_phase+0x35 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 25922] 
coreclr!WKS::gc_heap::plan_phase+0x1aa8 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 24246] 
coreclr!WKS::gc_heap::gc1+0x173 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 16782] 
coreclr!WKS::gc_heap::garbage_collect+0x3bd [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 18414] 
coreclr!WKS::GCHeap::GarbageCollectGeneration+0x239 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 38169] 
coreclr!WKS::gc_heap::trigger_gc_for_alloc+0x40 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 14039] 
coreclr!WKS::gc_heap::try_allocate_more_space+0x1ba [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 14157] 
coreclr!WKS::gc_heap::allocate_more_space+0x14 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 14587] 
coreclr!WKS::gc_heap::allocate+0x31 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 14618] 
coreclr!WKS::GCHeap::Alloc+0x199 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 37242] 
coreclr!Alloc+0x13e [F:\workspace\_work\1\s\src\coreclr\src\vm\gchelpers.cpp @ 231] 
coreclr!AllocateSzArray+0x2ea [F:\workspace\_work\1\s\src\coreclr\src\vm\gchelpers.cpp @ 486] 
coreclr!JIT_NewArr1+0x185 [F:\workspace\_work\1\s\src\coreclr\src\vm\jithelpers.cpp @ 2718] 
System_Private_CoreLib!System.Span`1[[System.Byte, System.Private.CoreLib]].ToArray()+0x9a6b2fa1 [/_/src/libraries/System.Private.CoreLib/src/System/Span.cs @ 477] 
Common_Tests!System.Net.Test.Common.VirtualNetworkStream.Write(Byte[], Int32, Int32)+0x67
Common_Tests!System.Net.Test.Common.VirtualNetworkStreamTest.VirtualNetworkStream_SingleThreadIntegrityTest_Ok()+0x137
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #34279 

**Update:** The assert added in this PR impacts more than first thought. When a P/Invoke, call in IL, is inlined any native arguments must be converted (`conv.i`/`conv.u`) prior to the call since the IL marshaler fixes in this PR won't run. See https://github.com/dotnet/runtime/issues/35187 for an example.

/cc @jkoritzinsky @elinor-fung @jkotas @AndyAyersMS

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@davidwrighton and @MichalStrehovsky for crossgen2 changes.

File: src/coreclr/src/vm/ilmarshalers.cpp [hunk 1]
```diff
@@ -2907,7 +2907,7 @@ MarshalerOverrideStatus ILSafeHandleMarshaler::ArgumentOverride(NDirectStubLinke
             }
 
             // Leave the address of the native handle local as the argument to the native method.
-            pslILDispatch->EmitLDLOCA(dwNativeHandleLocal);
+            EmitLoadNativeLocalAddrForByRefDispatch(pslILDispatch, dwNativeHandleLocal);
```
Comment (jkotas) [inline src/coreclr/src/vm/ilmarshalers.cpp:2910]: Nit: I am not sure whether factoring this into a helper method helps with readability. `EmitLDLOCA` + `EmitCONV_I` inline may be better. (matter of preference)

**Review by jkotas — APPROVED** [review]

File: src/coreclr/src/vm/ilmarshalers.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/src/vm/ilmarshalers.cpp:2910]: Not sure that it does either. I started down that path because we missed this in so many places and I was frustrated with the same two lines being in 4 places. My attempt was to make the method name verbose. I am going to leave it as such for now. I am hoping we can avoid touching this again entirely with the source generator approach.

**Review by davidwrighton — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
Le sigh... Dynamic runtime `IDispatch::Invoke()` support 😞

**Comment by AaronRobinsonMSFT** [comment]
... and IJW ...

Also it looks like during the switch over to SDK test projects we inadvertently disabled all native COM client tests for consuming managed COM servers. I am re-enabling them in this PR but will rebase when I merge so the two commits exist.

**Comment by AaronRobinsonMSFT** [comment]
... and WinRT ...

File: src/coreclr/src/jit/importer.cpp [hunk 2]
```diff
@@ -6738,9 +6738,16 @@ void Compiler::impPopArgsForUnmanagedCall(GenTree* call, CORINFO_SIG_INFO* sig)
...
 
-    for (GenTreeCall::Use& use : GenTreeCall::UseList(args))
+    for (GenTreeCall::Use& argUse : GenTreeCall::UseList(args))
     {
-        call->gtFlags |= use.GetNode()->gtFlags & GTF_GLOB_EFFECT;
+        // We should not be passing gc typed args to an unmanaged call.
+        GenTree* arg = argUse.GetNode();
+        if (varTypeIsGC(arg->TypeGet()))
+        {
+            assert(!"*** invalid IL: gc type passed to unmanaged call");
```
Comment (BruceForstall) [inline src/coreclr/src/jit/importer.cpp:6747]: Is it ok for this to be ignored in Release builds? Or should this be a BADCODE?

Comment (AaronRobinsonMSFT) [reply src/coreclr/src/jit/importer.cpp:6747]: That is a good question. I took the guidance from https://github.com/dotnet/runtime/issues/34279#issuecomment-613695776.

Comment (jkotas) [reply src/coreclr/src/jit/importer.cpp:6747]: Given how many places we had to fix in our stuff, I would be very worried about breaking potential of turning this into BADCODE and the long tail of issues from that. It may be better to look into making JIT resilient to this.
