### PR TITLE
JIT: some jitstress fixes

### LINKED ISSUE #1684: JIT: complus_jitstressonly broken
We end up calling `compStressCompile` very early, before the method name is set up, and so the jit crashes.
```
00 clrjit!JitConfigValues::MethodSet::contains
01 clrjit!Compiler::compStressCompile
02 clrjit!Compiler::compGetJitDefaultFill
03 clrjit!UninitializedWord
04 clrjit!ArenaAllocator::allocateMemory
05 clrjit!ArenaAllocator::MemStatsAllocator::allocateMemory
06 clrjit!CompAllocator::allocate
07 clrjit!operator new
08 clrjit!Compiler::compInit
09 clrjit!jitNativeCode::__l8::__Body::Run::__l6::__Body::Run
0a clrjit!`jitNativeCode'::`8'::__Body::Run
0b clrjit!jitNativeCode
0c clrjit!CILJit::compileMethod
```

### LINKED ISSUE #1704: JIT: STRESS_LCL_FLD doesn't handle LCL_VAR_ADDR
This shows up as bad jitstress2 codegen and causes failures in some tests, one example is k-nucleotide-9.

Minimal setup for isolated repro (depends on #1684):
```
complus_jitstress=2
complus_jitstressonly=FindNewWork32
complus_jitstressmodenames=STRESS_LCL_FLDS
complus_jitstressmodenamesonly=1
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Jitstress' `STRESS_LCL_FLD` mode was not handling `LCL_VAR_ADDR` nodes, leading
to bad "stress only" codegen. Handle these node types properly.

Fixes #1704.

Also initialize `compMethodName` early, so we can check for nullptr later on
when considering the jit stress range and avoid an AV.

Fixes #1684.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib PTAL

Fixes a good number of the jitstress2 failures.

**Review by BruceForstall — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
These are stress mode only fixes, so will ignore the failures.

File: src/coreclr/src/jit/lclvars.cpp [hunk 1]
```diff
@@ -7390,6 +7392,11 @@ Compiler::fgWalkResult Compiler::lvaStressLclFldCB(GenTree** pTree, fgWalkData*
             tree->ChangeOper(GT_LCL_FLD);
             tree->AsLclFld()->SetLclOffs(padding);
         }
+        else if (oper == GT_LCL_VAR_ADDR)
+        {
+            tree->ChangeOper(GT_LCL_FLD_ADDR);
```
Comment (mikedn) [inline src/coreclr/src/jit/lclvars.cpp]: There's code above that sets `GTF_GLOB_REF` on `tree`, that should not be done on `GT_LCL_VAR|FLD_ADDR` nodes. I'm not sure if that matters for stress mode but then I'm not sure why this particular stress mode exist to begin with.
