### PR TITLE
Fix NativeAOT rethrow bug

### LINKED ISSUE #88128: NativeAOT fails to catch rethrown exception in edge cases
The following code results in unhandled exception when compiled with NativeAOT:
```c#
class Program
{
    static void Main(string[] args)
    {
        try
        {
            throw new Exception("boo");
        }
        catch (Exception ex2)
        {
            Console.WriteLine($"1: {ex2}");
            try
            {
                throw;
                //throw new ArgumentException("aE");
            }
            catch (Exception ex3)
            {
                Console.WriteLine($"2: {ex3}");
            }
        }
    }
}
```
When the `throw;` is commented out and the `throw new ArgumentException("aE");` is uncommented it works. So it is a rethrow only issue.

### PR DESCRIPTION
**Pull request by janvorli**
The rethrowing incorrectly starts searching for exception clause based on the previously searched clause for the exception being rethrown. It should always start from the beginning.

Close #88128

### CODE REVIEW

File: src/tests/Regressions/coreclr/GitHub_88128/test88128.cs [hunk 1]
```diff
@@ -0,0 +1,27 @@
+using System;
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_88128/test88128.cs:1]:
```suggestion
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
```

File: src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs [hunk 2]
```diff
@@ -619,6 +619,7 @@ private static void DispatchEx(scoped ref StackFrameIterator frameIter, ref ExIn
 
             OnFirstChanceExceptionViaClassLib(exceptionObj);
 
+            uint startIdx = MaxTryRegionIdx;
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs:622]: Could you please shed some light for me on how the fix works?

As far as I can tell, `puExCollideClauseIdx` argument of `StackIterator.Next` is `out` argument, so passing a different value into `StackIterator.Next` should make difference.

And `isFirstRethrowFrame` should only affect the stacktrace reported by the exception. It should not affect how the exception gets handled.

Comment (jkotas) [reply src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs:622]: Ah ok, this is for-loop. It means that this `startIdx` is going to be used for the first iteration.

**Review by jkotas — APPROVED** [review]
LGTM. Thank you!
