### PR TITLE
Fix debugger crash during unload of assemblies in ALC

### LINKED ISSUE #2317: ICorDebugManagedCallback::DebuggerError when unloading AssemblyLoadContext
Running the following code in VS d16.5 typically fails with an error dialog due to the CLR's debugging interfaces returning DebuggerError with the error set to E_INVALIDARG.

```
using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Loader;

namespace PlugInTest
{
    class Program
    {
        //TODO: insert absolute path to managed dll
        static string pluginPath = @"C:\MyPlugin.dll";
        static AssemblyLoadContext AssemblyLoadContext;
        static Assembly Assembly;

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void Load()
        {
            AssemblyLoadContext = new AssemblyLoadContext("PluginLoader", true);
            Assembly = AssemblyLoadContext.LoadFromAssemblyPath(pluginPath);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static WeakReference Unload()
        {
            Assembly = null;
            AssemblyLoadContext.Unload();
            WeakReference weakRef = new WeakReference(AssemblyLoadContext);
            AssemblyLoadContext = null;
            return weakRef;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void Test()
        {
            WeakReference weakRef;
            {
                Load();
                weakRef = Unload();
            }

            while (weakRef.IsAlive)
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
            }
            Console.WriteLine("Finished Test");
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void Main(string[] args)
        {
            Test();
            Test();
            Test(); //crashs here at GC.Collect
        }
    }
}
```

originally reported here: https://developercommunity.visualstudio.com/content/problem/698374/vs2019-and-fatal-error-has-occurred-and-debugging.html

### PR DESCRIPTION
**Pull request by hoyosjs**
Fixes #2317

### CODE REVIEW

File: src/coreclr/src/debug/ee/debuggermodule.cpp [hunk 1]
```diff
@@ -239,12 +239,34 @@ void DebuggerModuleTable::RemoveModule(Module* module, AppDomain *pAppDomain)
...
-    _ASSERTE( FALSE );
+    LOG((LF_CORDB, LL_INFO1000, "DMT::RM Attempting to remove Module:0x%x AD:0x%x\n", pModule, pAppDomain));
 
+    _ASSERTE(ThreadHoldsLock());
+    _ASSERTE(pModule != NULL);
+
+    HASHFIND hf;
+    DebuggerModuleEntry *pDME; pDME = (DebuggerModuleEntry *) FindFirstEntry(&hf);
+
+    for (pDME = (DebuggerModuleEntry *) FindFirstEntry(&hf);
```
Comment (sdmaclea) [inline src/coreclr/src/debug/ee/debuggermodule.cpp]: Line 248 and line 250 should be simplified.  

Delete line 248 and...
```suggestion
    for (DebuggerModuleEntry pDME = (DebuggerModuleEntry *) FindFirstEntry(&hf);
```
or
```suggestion
    DebuggerModuleEntry pDME = (DebuggerModuleEntry *) FindFirstEntry(&hf);
    for (;
```
or 
```suggestion
    for (auto pDME = (DebuggerModuleEntry *) FindFirstEntry(&hf);
```

```

File: src/coreclr/src/debug/ee/debuggermodule.cpp [hunk 2]
```diff
@@ -239,12 +239,34 @@ void DebuggerModuleTable::RemoveModule(Module* module, AppDomain *pAppDomain)
...
+         pDME != NULL;
+         pDME = (DebuggerModuleEntry*) FindNextEntry(&hf))
+    {
+        DebuggerModule *pDM = pDME->module;
+        Module* pRtModInDebugMod = pDM->GetRuntimeModule();
+
+        if (pRtModInDebugMod == pModule && pDM->GetAppDomain() == pAppDomain)
```
Comment (sdmaclea) [inline src/coreclr/src/debug/ee/debuggermodule.cpp]: Even though the operator precedence is right.  I generally choose to add parenthesis to make the precedence explicit.

File: src/coreclr/src/debug/ee/debuggermodule.cpp [hunk 3]
```diff
@@ -239,12 +239,34 @@ void DebuggerModuleTable::RemoveModule(Module* module, AppDomain *pAppDomain)
...
+        {
+            LOG((LF_CORDB, LL_INFO1000, "DMT::RM Removing DebuggerMod:0x%x - Module:0x%x DF:0x%x AD:0x%x\n",
+                pDM, pModule, pDM->GetDomainFile(), pAppDomain));
+            TRACE_FREE(pDME->module);
```
Comment (sdmaclea) [inline src/coreclr/src/debug/ee/debuggermodule.cpp]:
```suggestion
            TRACE_FREE(pDM);
```

File: src/coreclr/src/debug/ee/debuggermodule.cpp [hunk 4]
```diff
@@ -239,12 +239,34 @@ void DebuggerModuleTable::RemoveModule(Module* module, AppDomain *pAppDomain)
...
+            DeleteInteropSafe(pDM);
+            Delete(HASH(pRtModInDebugMod), (HASHENTRY *) pDME);
```
Comment (sdmaclea) [inline src/coreclr/src/debug/ee/debuggermodule.cpp]: I assume since a lock held the order of operations here doesn't matter.  

I assume these are roughly
+ Delete the module
+ Remove module entry from the dictionary

**Review by sdmaclea — APPROVED** [review]
LGTM w/ comments

File: src/coreclr/src/debug/ee/debuggermodule.cpp (hunk 1 above)
Comment (hoyosjs) [reply src/coreclr/src/debug/ee/debuggermodule.cpp]: Wow, I didn't even see this when I restructured the code. Thanks

File: src/coreclr/src/debug/ee/debuggermodule.cpp (hunk 4 above)
Comment (hoyosjs) [reply src/coreclr/src/debug/ee/debuggermodule.cpp]: Doesn't matter mostly because of the lock indeed. The remove from the hash never tries any cleanup, just deletes the entry in the linked list.

As long as no one holds a reference to the debug module the first operation is safe. So far what I've seen is we're good citizens and use LookupOrCreate variants except for FuncEvals, and within the debugger modules themselves. Most cases would run one one thread under a lock, so all is good. The one in the debugger module is the primary module, and that should probably be removed as I couldn't find any reference.

File: src/coreclr/src/debug/ee/debuggermodule.cpp [hunk 5]
```diff
@@ -230,7 +230,7 @@ void DebuggerModuleTable::AddModule(DebuggerModule *pModule)
 // This occurs in response to AppDomain unload.
```
Comment (jkotas) [inline src/coreclr/src/debug/ee/debuggermodule.cpp]: Update the comment as well? We do not have AppDomain unload in .NET Core.

**Comment by baehny** [comment]
Is there a chance this fix will be released for .net core 3.1 for example by an 3.1.3 update?
