### PR TITLE
UnixCommandLinePing.cs: improve searching for the system ping binary

### LINKED ISSUE #103736: 'System.PlatformNotSupportedException: The system's ping utility could not be found.' thrown unless running as root on EndeavourOS.
### Description

Ping.Send() is either failing to find the ping binary or cannot access the ping binary as a non-root user on EndeavourOS.

### Reproduction Steps

This vb.net code snippet triggers a System.PlatformNotSupportedException while executing as a non-root user reliably on EndeavourOS, and will not fail if the user is root.
```vb
Public Function PingAddress(Address As Net.IpAddress) As Boolean
    If (New Ping).Send(Address).Status = IPStatus.Success Then
        Return True
    End If
    Return False
End Function
```

### Expected behavior

Calls to Ping.Send() should function while running as a non-root user.

### Actual behavior

Ping.Send() throws a System.PlatformNotSupportedException with message 'The system's ping utility could not be found.' while running as a non-root user.

### Regression?

Unknown

### Known Workarounds

Run as root (this is a bad idea).

### Configuration

.Net Version: running on 8.0.6, with the library causing this error targeting netstandard2.0
OS: EndeavourOS Rolling (Archlinux Derivative) 
Arch: linux-x64
Configuration Specific: Not Tested, but presumed that this may also affect Archlinux users as well.

### Other information

it should be noted that archlinux package `iputils` no longer provides separate ping6 and ping4 binaries in favor of a unified ping binary. `src/libraries/Common/src/System/Net/NetworkInformation/UnixCommandLinePing.cs` appears to use the old names still.

### PR DESCRIPTION
**Pull request by Ninjastorm380**
On newer linux systems, binaries ping6 and ping4 are no longer shipped, replaced by a unified ping binary and *maybe* some symlinks that replace ping4 and ping6 for compatibility. dotnet should prefer using the unified ping binary wherever possible on linux for this reason.

This fixes [103736](https://github.com/dotnet/runtime/issues/103736#issue-2363215967)

### CODE REVIEW

**Comment by rzikm** [comment]
Test failures seem to be related

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-103838-merge-323855de4e6f480fb4/System.Net.Ping.Functional.Tests/3/console.9bc88532.log?helixlogtype=result

```
    System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 0) [FAIL]
      System.Exception : [/sbin/ping -c 1 -s 16 ::1] process exit code is 68.
      StdOut:[]
      StdErr:[ping: cannot resolve ::1: Unknown host
      ]
      Stack Trace:
        /_/src/libraries/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs(103,0): at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(Int32 payloadSize)
        --- End of stack trace from previous location ---
    System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1) [FAIL]
      System.Exception : [/sbin/ping -c 1 -s 16 ::1] process exit code is 68.
      StdOut:[]
      StdErr:[ping: cannot resolve ::1: Unknown host
      ]
      Stack Trace:
        /_/src/libraries/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs(103,0): at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(Int32 payloadSize)
        --- End of stack trace from previous location ---
    System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 50) [FAIL]
      System.Exception : [/sbin/ping -c 1 -s 50 ::1] process exit code is 68.
      StdOut:[]
      StdErr:[ping: cannot resolve ::1: Unknown host
      ]
      Stack Trace:
        /_/src/libraries/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs(103,0): at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(Int32 payloadSize)
        --- End of stack trace from previous location ---
    System.Net.NetworkInformation.Tests.UnixPingUtilityTests.PacketSizeIsRespected(payloadSize: 1000) [FAIL]
      System.Exception : [/sbin/ping -c 1 -s 1000 ::1] process exit code is 68.
      StdOut:[]
      StdErr:[ping: cannot resolve ::1: Unknown host
      ]
```

**Comment by am11** [comment]
@rzikm, can we replace SendIcmpEchoRequestOverRawSocket and PingUtility with non-raw-socket implementation (SOCK_DGRAM instead of SOCK_RAW)?

e.g. this works without sudo on mac and linux

```c
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <netinet/ip_icmp.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>

#define PACKET_SIZE 64
#define TIMEOUT 1

unsigned short checksum(void *b, int len) {    
    unsigned short *buf = b; 
    unsigned int sum = 0; 
    unsigned short result; 

    for ( sum = 0; len > 1; len -= 2 ) {
        sum += *buf++;
    }
    if ( len == 1 ) {
        sum += *(unsigned char*)buf;
    }
    sum = (sum >> 16) + (sum & 0xFFFF);
    sum += (sum >> 16);
    result = ~sum;
    return result;
}

void ping(const char *host) {
    struct sockaddr_in addr;
    struct hostent *h;
    int sockfd, n;
    char packet[PACKET_SIZE];
    struct icmp *icmp_hdr = (struct icmp*) packet;
    struct timeval start, end;
    struct timeval timeout = {TIMEOUT, 0};
    fd_set fds;

    if ((h = gethostbyname(host)) == NULL) {
        perror("gethostbyname");
        exit(1);
    }

    memset(&addr, 0, sizeof(addr));
    addr.sin_family = h->h_addrtype;
    addr.sin_addr.s_addr = *(long*)h->h_addr;

    // Use SOCK_DGRAM for ICMP operations, SOCK_RAW is typically not necessary
    if ((sockfd = socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP)) < 0) {
        perror("socket");
        exit(1);
    }

    setsockopt(sockfd, SOL_SOCKET, SO_RCVTIMEO, &timeout, sizeof(timeout));

    memset(packet, 0, PACKET_SIZE);
    icmp_hdr->icmp_type = ICMP_ECHO;
    icmp_hdr->icmp_code = 0;
    icmp_hdr->icmp_id = getpid();
    icmp_hdr->icmp_seq = 0;
    icmp_hdr->icmp_cksum = checksum(packet, PACKET_SIZE);

    gettimeofday(&start, NULL);
    if (sendto(sockfd, packet, PACKET_SIZE, 0, (struct sockaddr*)&addr, sizeof(addr)) <= 0) {
        perror("sendto");
        exit(1);
    }

    FD_ZERO(&fds);
    FD_SET(sockfd, &fds);
    n = select(sockfd+1, &fds, NULL, NULL, &timeout);

    if (n == 0) {
        printf("Timeout\n");
    } else if (n < 0) {
        perror("select");
    } else {
        n = recv(sockfd, packet, PACKET_SIZE, 0);
        if (n <= 0) {
            perror("recv");
        } else {
            gettimeofday(&end, NULL);
            double time_taken = (end.tv_sec - start.tv_sec) * 1000.0;
            time_taken += (end.tv_usec - start.tv_usec) / 1000.0;
            printf("Round-trip time: %.2f ms\n", time_taken);
        }
    }

    close(sockfd);
}

int main(int argc, char **argv) {
    if (argc != 2) {
        printf("Usage: %s <hostname>\n", argv[0]);
        return 1;
    }

    ping(argv[1]);
    return 0;
}
```
```sh
$ cc ping.c -o myping
$ ./myping github.com
```

**Comment by rzikm** [comment]
If it works as expected, I don't see a reason not to. Cc @wfurt who daily drives OSX.

**Comment by wfurt** [comment]
we already do that for macOS @am11

https://github.com/dotnet/runtime/blob/afe6fbd792da542424fa561f73f7accbb81874c1/src/libraries/System.Net.Ping/src/System/Net/NetworkInformation/Ping.RawSocket.cs#L65-L67

AFAIK on Linux it depends on kernel setting. As far as I remember it did not work out of box on Ubuntu but I did not try it recently. 
https://opennms.discourse.group/t/how-to-allow-unprivileged-users-to-use-icmp-ping/1573

File: src/libraries/Common/src/System/Net/NetworkInformation/UnixCommandLinePing.cs [hunk 1]
```diff
@@ -25,7 +27,12 @@ internal static class UnixCommandLinePing
             string fileName = ipv4 ? s_ipv4PingFile : s_ipv6PingFile;
             foreach (string folder in s_binFolders)
             {
+                string pathv4v6 = Path.Combine(folder, s_ipv4v6PingFile);
                 string path = Path.Combine(folder, fileName);
+                if (File.Exists(pathv4v6))
```
Comment (wfurt) [inline src/libraries/Common/src/System/Net/NetworkInformation/UnixCommandLinePing.cs:32]: It seems like this will prefer 'ping` over 'ping6'. I don't know if it is safe

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-103838-merge-5862a84e5eb54ce381/System.Net.Ping.Functional.Tests/3/console.6b3e6490.log?helixlogtype=result

**Comment by am11** [comment]
@wfurt, the docker containers on mac seem to be getting permissive range set:

```
$ sysctl net.ipv4.ping_group_range
net.ipv4.ping_group_range = 0	2147483647
```
perhaps we could have a runtime check like this for datagram sockets as well?
https://github.com/dotnet/runtime/blob/c5e8f83db1606a89e70a9f4a0ac2fc03dea2418c/src/libraries/Common/src/System/Net/RawSocketPermissions.cs#L21

**Comment by Ninjastorm380** [comment]
What's the status here? we planning on using a datagram based implementation?

File: src/libraries/Common/src/System/Net/NetworkInformation/UnixCommandLinePing.cs (hunk 1 above)
Comment (Ninjastorm380) [reply src/libraries/Common/src/System/Net/NetworkInformation/UnixCommandLinePing.cs:32]: that should be the case. names ping4 and ping6 do not exist in iputils anymore.

**Comment by wfurt** [comment]
> What's the status here? we planning on using a datagram based implementation?

I would not mix them e.g. if anything I would do follow-up PR. I feel we may still need to existing `ping`  wrapper. 
Out of curiosity could you check the setting above on your system @Ninjastorm380 ?

**Comment by Ninjastorm380** [comment]
@wfurt `sysctl net.ipv4.ping_group_range` -> `net.ipv4.ping_group_range = 0	2147483647`

**Comment by Ninjastorm380** [comment]
those OSX errors, they a problem?

**Comment by wfurt** [comment]
> those OSX errors, they a problem?

yes, but it is curious as I would expect that the socket will be used all the time.
On my system:
```
lenoch:System.Net.Http furt$ /sbin/ping -c 1 -s 16 ::1
ping: cannot resolve ::1: Unknown host
lenoch:System.Net.Http furt$ /sbin/ping6 -c 1 -s 16 ::1
PING6(64=40+8+16 bytes) ::1 --> ::1
24 bytes from ::1, icmp_seq=0 hlim=64 time=0.128 ms

--- ::1 ping6 statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 0.128/0.128/0.128/0.000 ms
```

so it seems like direct outcome of this change.

**Comment by Ninjastorm380** [comment]
as you mentioned earlier, isn't macos supposed to use a datagram socket????

**Comment by Ninjastorm380** [comment]
on another note, does your ping support the -4 and -6 options?

**Comment by wfurt** [comment]
Does not seems to. macOS 14.5:
```
$ /sbin/ping -6 -c 1 -s 16 ::1
ping: invalid option -- 6
usage: ping [-AaDdfnoQqRrv] [-c count] [-G sweepmaxsize]
            [-g sweepminsize] [-h sweepincrsize] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern]
            [-S src_addr] [-s packetsize] [-t timeout][-W waittime]
            [-z tos] host
       ping [-AaDdfLnoQqRrv] [-c count] [-I iface] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern] [-S src_addr]
            [-s packetsize] [-T ttl] [-t timeout] [-W waittime]
            [-z tos] mcast-group
Apple specific options (to be specified before mcast-group or host like all options)
            -b boundif           # bind the socket to the interface
            -k traffic_class     # set traffic class socket option
            -K net_service_type  # set traffic class socket options
            --apple-connect       # call connect(2) in the socket
            --apple-time          # display current time
```

there is already fork for the parameters for macOS and FreeBSD. Another tricky platform is Alpine where the `ping` comes from `busybox` and has limited syntax. 

I'll look at the CI separately. There may be something with CI machines that prevents the socket. But in either case I think we should keep the fallback functional.

**Comment by Ninjastorm380** [comment]
well, I already updated the commit to prefer ping4 over ping for v4 if they are found, so those macos builds shouldn't fail either way.

**Comment by Ninjastorm380** [comment]
any news on the broken CI?

**Comment by Ninjastorm380** [comment]
@wfurt hello?

**Comment by Ninjastorm380** [comment]
btw, here's the parameters on ubuntu's ping (tested latest LTS in a VM):
```
ping -help

Usage
  ping [options] <destination>

Options:
  <destination>      DNS name or IP address
  -a                 use audible ping
  -A                 use adaptive ping
  -B                 sticky source address
  -c <count>         stop after <count> replies
  -C                 call connect() syscall on socket creation
  -D                 print timestamps
  -d                 use SO_DEBUG socket option
  -e <identifier>    define identifier for ping session, default is random for
                     SOCK_RAW and kernel defined for SOCK_DGRAM
                     Imply using SOCK_RAW (for IPv4 only for identifier 0)
  -f                 flood ping
  -h                 print help and exit
  -H                 force reverse DNS name resolution (useful for numeric
                     destinations or for -f), override -n
  -I <interface>     either interface name or address
  -i <interval>      seconds between sending each packet
  -L                 suppress loopback of multicast packets
  -l <preload>       send <preload> number of packages while waiting replies
  -m <mark>          tag the packets going out
  -M <pmtud opt>     define path MTU discovery, can be one of <do|dont|want|probe>
  -n                 no reverse DNS name resolution, override -H
  -O                 report outstanding replies
  -p <pattern>       contents of padding byte
  -q                 quiet output
  -Q <tclass>        use quality of service <tclass> bits
  -s <size>          use <size> as number of data bytes to be sent
  -S <size>          use <size> as SO_SNDBUF socket option value
  -t <ttl>           define time to live
  -U                 print user-to-user latency
  -v                 verbose output
  -V                 print version and exit
  -w <deadline>      reply wait <deadline> in seconds
  -W <timeout>       time to wait for response

IPv4 options:
  -4                 use IPv4
  -b                 allow pinging broadcast
  -R                 record route
  -T <timestamp>     define timestamp, can be one of <tsonly|tsandaddr|tsprespec>

IPv6 options:
  -6                 use IPv6
  -F <flowlabel>     define flow label, default is random
  -N <nodeinfo opt>  use IPv6 node info query, try <help> as argument

For more details see ping(8).
```
the presence of -4 and -6 indicate that it's a unified ping binary (it handles ipv4 and ipv6 pings).

**Comment by Ninjastorm380** [comment]
fedora sports an identical set of flags, including -4 and -6, so another unified ping binary. RHEL is probably using unified ping as well because of this.
```
ping -help

Usage
  ping [options] <destination>

Options:
  <destination>      DNS name or IP address
  -a                 use audible ping
  -A                 use adaptive ping
  -B                 sticky source address
  -c <count>         stop after <count> replies
  -C                 call connect() syscall on socket creation
  -D                 print timestamps
  -d                 use SO_DEBUG socket option
  -e <identifier>    define identifier for ping session, default is random for
                     SOCK_RAW and kernel defined for SOCK_DGRAM
                     Imply using SOCK_RAW (for IPv4 only for identifier 0)
  -f                 flood ping
  -h                 print help and exit
  -H                 force reverse DNS name resolution (useful for numeric
                     destinations or for -f), override -n
  -I <interface>     either interface name or address
  -i <interval>      seconds between sending each packet
  -L                 suppress loopback of multicast packets
  -l <preload>       send <preload> number of packages while waiting replies
  -m <mark>          tag the packets going out
  -M <pmtud opt>     define path MTU discovery, can be one of <do|dont|want|probe>
  -n                 no reverse DNS name resolution, override -H
  -O                 report outstanding replies
  -p <pattern>       contents of padding byte
  -q                 quiet output
  -Q <tclass>        use quality of service <tclass> bits
  -s <size>          use <size> as number of data bytes to be sent
  -S <size>          use <size> as SO_SNDBUF socket option value
  -t <ttl>           define time to live
  -U                 print user-to-user latency
  -v                 verbose output
  -V                 print version and exit
  -w <deadline>      reply wait <deadline> in seconds
  -W <timeout>       time to wait for response

IPv4 options:
  -4                 use IPv4
  -b                 allow pinging broadcast
  -R                 record route
  -T <timestamp>     define timestamp, can be one of <tsonly|tsandaddr|tsprespec>

IPv6 options:
  -6                 use IPv6
  -F <flowlabel>     define flow label, default is random
  -N <nodeinfo opt>  use IPv6 node info query, try <help> as argument

For more details see ping(8).
```

**Comment by Ninjastorm380** [comment]
since the big three (Archlinux, Debian, Redhat) all have unified ping binaries @wfurt, what should we do?

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by wfurt** [comment]
> since the big three (Archlinux, Debian, Redhat) all seem to have unified ping binaries @wfurt, what should we do?

The main distributions are typically easy to handle. But we should strive to support all the odd one. Weather it is `busybox`  like Alpine, or different implementation and disjoined behavior like macOS or FreeBSD.

**Comment by Ninjastorm380** [comment]
@wfurt unfortunately, I can't merge until the CI is fixed

**Comment by wfurt** [comment]
> @wfurt unfortunately, I can't merge until the CI is fixed

you don't have write rights anyway. the remained is know issue e.g.  the [Build Analysis](https://github.com/dotnet/runtime/pull/103838/checks?check_run_id=26956050732)  task is green.

**Comment by wfurt** [comment]
and thanks for the contribution @Ninjastorm380

**Comment by Ninjastorm380** [comment]
also, on a separate note, I have a working prototype for a dgram based ping for linux. I just need to port it to c#. will look at adding it on a separate PR.

**Comment by Ninjastorm380** [comment]
> and thanks for the contribution @Ninjastorm380

no problem!
