### PR TITLE
Fix BitArray.CopyTo

### LINKED ISSUE #98813: BitArray.CopyTo(Array, int) throws an ArgumentException, if BitArray.Length has been reduced to a multiple of 32
### Description

BitArray.CopyTo(Array, int) throws an ArgumentException, if BitArray.Length has been reduced to a multiple of 32

### Reproduction Steps

The following code works as expected:
```
using System.Collections;

var bitArray = new BitArray(256);
bitArray.Length = 33;

var intArray = new int[2];
bitArray.CopyTo(intArray, 0);
```

But if the length is further reduced to 32 then an ArgumentException is thrown:
```
using System.Collections;

var bitArray = new BitArray(256);
bitArray.Length = 32;

var intArray = new int[2];
bitArray.CopyTo(intArray, 0);
```

### Expected behavior

The relevant values get copied.

### Actual behavior

ArgumentException if BitArray.Length is reduced to a multiple of 32. Reasons seems to be that the length that should be copied is not calculated using the BitArray.Length. Instead the length of the underlying int array is used: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections/src/System/Collections/BitArray.cs#L764

Problem is the underlying int array is not resized when the BitArray.Length is reduced by a small amount (< BitArray._ShrinkThreshold).

### Regression?

In .NET 4.8 the length that should be copied is calculated using the BitArray.Length: https://referencesource.microsoft.com/#mscorlib/system/collections/bitarray.cs,370

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by lilinus**
Fixes https://github.com/dotnet/runtime/issues/98813

### CODE REVIEW

File: src/libraries/System.Collections/src/System/Collections/BitArray.cs [hunk 1]
```diff
@@ -756,21 +756,14 @@ public unsafe void CopyTo(Array array, int index)
 
             if (array is int[] intArray)
             {
-                Div32Rem(m_length, out int extraBits);
+                int fullInts = Div32Rem(m_length, out int extraBits);
```
Comment (lilinus) [inline src/libraries/System.Collections/src/System/Collections/BitArray.cs:759]: There was missing a check here for destination array length. Should I add one?

File: src/libraries/System.Collections/src/System/Collections/BitArray.cs [hunk 2]
```diff
@@ -791,8 +784,8 @@ public unsafe void CopyTo(Array array, int index)
 
                 Span<byte> span = byteArray.AsSpan(index);
 
-                int quotient = Div4Rem(arrayLength, out int remainder);
-                for (int i = 0; i < quotient; i++)
+                int fullInts = Div4Rem(arrayLength, out int extraBytes);
```
Comment (lilinus) [inline src/libraries/System.Collections/src/System/Collections/BitArray.cs:787]: Renamed these variables so it's more readable

Comment (eiriktsarpalis) [reply src/libraries/System.Collections/src/System/Collections/BitArray.cs:787]: Please retain the original terminology -- `quotient` and `remainder` is standard terminology when it comes to integer division. Also, it's good if the change focused on the fix at hand rather than introducing unrelated refactoring.

File: src/libraries/System.Collections/src/System/Collections/BitArray.cs (hunk 1 above)
Comment (eiriktsarpalis) [reply src/libraries/System.Collections/src/System/Collections/BitArray.cs:759]: I would guess that bounds checking is delegated to `Array.Copy`. Is it causing undesirable behavior right now?

Comment (lilinus) [reply src/libraries/System.Collections/src/System/Collections/BitArray.cs:759]: Yeah, seems like it is throwing IndexOutOfRangeException (in 8.0.2) when doing:
```new bitArray(33).CopyTo(new int[1], 0)```
Documentation says it should throw `ArgumentException`

Comment (eiriktsarpalis) [reply src/libraries/System.Collections/src/System/Collections/BitArray.cs:759]: Could you file a separate issue about it? Even though documentation says otherwise changing the exception type would be somewhat of a breaking change so it needs to be considered separately. It is likely that we need to investigate the `CopyTo` implementation in other collection types for similar discrepancies.

File: src/libraries/System.Collections/tests/BitArray/BitArray_GetSetTests.cs [hunk 3]
```diff
@@ -396,6 +396,18 @@ public static void CopyToIntArray()
             }
         }
 
+        // https://github.com/dotnet/runtime/issues/98813
+        [Fact]
+        public static void CopyToIntArray_Regression98813()
+        {
+            BitArray bitArray = new BitArray(256);
+            bitArray.Length = 32;
```
Comment (eiriktsarpalis) [inline src/libraries/System.Collections/tests/BitArray/BitArray_GetSetTests.cs:404]: Could you convert to a theory where multiple values < 256 are being tested?

File: src/libraries/System.Collections/src/System/Collections/BitArray.cs [hunk 4]
```diff
@@ -756,21 +756,14 @@ public unsafe void CopyTo(Array array, int index)
 
             if (array is int[] intArray)
             {
-                Div32Rem(m_length, out int extraBits);
+                int quotient = Div32Rem(m_length, out int extraBits);
 
-                if (extraBits == 0)
-                {
-                    // we have perfect bit alignment, no need to sanitize, just copy
-                    Array.Copy(m_array, 0, intArray, index, m_array.Length);
```
Comment (eiriktsarpalis) [inline src/libraries/System.Collections/src/System/Collections/BitArray.cs:764]: I think the only change necessary was to replace `m_array.Length` with `m_length`. Am I missing something?

Comment (lilinus) [reply src/libraries/System.Collections/src/System/Collections/BitArray.cs:764]: Yes, m_length is the number of bits stored the `BitArray` represents, so that's why we need to divrem by 32 to get extraBits and quotient (number of full ints)

Comment (eiriktsarpalis) [reply src/libraries/System.Collections/src/System/Collections/BitArray.cs:764]: Got it, thanks.

**Review by eiriktsarpalis — APPROVED** [review]
