### PR TITLE
switch to using CSTRMarshaller instead of AnsiBSTR

### LINKED ISSUE #54820: "free(): invalid pointer" with AnsiStringMarshaller compiled with crossgen2
### Description

If marshalling ilstub compilation is allowed in crossgen2, ansi string marshalling for string allocated in native code leads to "free(): invalid pointer".

Problem is related to `out string` argument marshalling, which tries to free `native_pointer - sizeof(void*)`.

**However, it seems that this problem might arise in SPC.dll even without any changes in crossgen2 because currently all such ilstubs are compiled, see GeneratesPInvoke:**
```c#
            if (((EcmaMethod)method).Module.Equals(method.Context.SystemModule))
                return true;
```

### Simple example to reproduce:

c# part:
```c#
using System;
using System.Runtime.InteropServices;

namespace ndirect
{
    class Program
    {
        [DllImport("tmp.so", EntryPoint = "test_func")]
        internal static extern int testFunc(out string value);

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            string a;
            testFunc(out a);
            Console.WriteLine(a);
        }
    }
}
```

native part, compiled with `gcc -shared -fPIC 1.c -o tmp.so`
```c
#include <malloc.h>
#include <string.h>

int test_func(char ** str)
{
  char * s = (char*) malloc(100);
  *str = s;
  strcpy(s, "my test string!");
  return strlen(s);
}
```
Output:
```
Hello World!
free(): invalid pointer
Aborted (core dumped)
```

Native code of compiled ilstub, which crashes:
```
10a10: 55                       push    rbp
                                UWOP_PUSH_NONVOL RBP(5)                                0

10a11: 41 57                    push    r15
                                UWOP_PUSH_NONVOL R15(15)                                0

10a13: 41 56                    push    r14
                                UWOP_PUSH_NONVOL R14(14)                                0

10a15: 41 55                    push    r13
                                UWOP_PUSH_NONVOL R13(13)                                0

10a17: 41 54                    push    r12
                                UWOP_PUSH_NONVOL R12(12)                                0

10a19: 53                       push    rbx
                                UWOP_PUSH_NONVOL RBX(3)                                0

10a1a: 48 83 ec 78              sub     rsp, 120
                                UWOP_ALLOC_SMALL 120                                0

10a1e: 48 8d ac 24 a0 00 00 00  lea     rbp, [rsp + 160]
10a26: 33 c0                    xor     eax, eax
10a28: 48 89 45 d0              mov     qword ptr [rbp - 48], rax
10a2c: 48 89 a5 60 ff ff ff     mov     qword ptr [rbp - 160], rsp
10a33: 48 89 7d c8              mov     qword ptr [rbp - 56], rdi
10a37: 48 8d 7d d0              lea     rdi, [rbp - 48]
10a3b: 48 89 7d c0              mov     qword ptr [rbp - 64], rdi
10a3f: 48 8d bd 68 ff ff ff     lea     rdi, [rbp - 152]
10a46: ff 15 ec 08 01 00        call    qword ptr [0x21338]   // PINVOKE_BEGIN (HELPER)
10a4c: 48 8b 05 25 09 01 00     mov     rax, qword ptr [0x21378] // int ndirect.Program.testFunc(ref string) (INDIRECT_PINVOKE_TARGET)
10a53: 48 8b 7d c0              mov     rdi, qword ptr [rbp - 64]
10a57: ff 10                    call    qword ptr [rax]
10a59: 8b d8                    mov     ebx, eax
10a5b: 48 8d bd 68 ff ff ff     lea     rdi, [rbp - 152]
10a62: ff 15 d8 08 01 00        call    qword ptr [0x21340]   // PINVOKE_END (HELPER)
10a68: 48 8b 7d d0              mov     rdi, qword ptr [rbp - 48]
10a6c: ff 15 e6 08 01 00        call    qword ptr [0x21358]   // string System.StubHelpers.AnsiBSTRMarshaler.ConvertToManaged(IntPtr) (METHOD_ENTRY_DEF_TOKEN)
                                RAX is live
10a72: 48 8b 7d c8              mov     rdi, qword ptr [rbp - 56]
                                RDI is live
10a76: 48 8b f0                 mov     rsi, rax
                                RSI is live
                                sp-56 is dead
10a79: ff 15 b1 08 01 00        call    qword ptr [0x21330]   // CHECKED_WRITE_BARRIER (HELPER)
                                RDI is dead
                                RAX is dead
                                RSI is dead
10a7f: 90                       nop
10a80: 48 8b 7d d0              mov     rdi, qword ptr [rbp - 48]
10a84: ff 15 d6 08 01 00        call    qword ptr [0x21360]   // void System.StubHelpers.AnsiBSTRMarshaler.ClearNative(IntPtr) (METHOD_ENTRY_DEF_TOKEN)
10a8a: 8b c3                    mov     eax, ebx
10a8c: 48 83 c4 78              add     rsp, 120
10a90: 5b                       pop     rbx
10a91: 41 5c                    pop     r12
10a93: 41 5d                    pop     r13
10a95: 41 5e                    pop     r14
10a97: 41 5f                    pop     r15
10a99: 5d                       pop     rbp
10a9a: c3                       ret
```

### Patch to allow marshalling ilstub compilation:
```patch
commit 129e85a182b9ed8561b3428f647df8dcf93ae49d
Author: Gleb Balykov <g.balykov@samsung.com>
Date:   Mon Jun 28 12:53:58 2021 +0300

    Partially allow marshalling ILSTUB compilation for ndirect methods using crossgen2 if SPC.dll is in the same bubble
    
    AnsiStringMarshaller is disallowed because it incorrectly handles pointers returned from native code.

diff --git a/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCompilationModuleGroupBase.cs b/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCompilationModuleGroupBase.cs
index 92ef5346c77..eaa2821ac94 100644
--- a/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCompilationModuleGroupBase.cs
+++ b/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCompilationModuleGroupBase.cs
@@ -329,10 +329,8 @@ public sealed override bool GeneratesPInvoke(MethodDesc method)
         {
             // PInvokes depend on details of the core library, so for now only compile them if:
             //    1) We're compiling the core library module, or
-            //    2) We're compiling any module, and no marshalling is needed
-            //
-            // TODO Future: consider compiling PInvokes with complex marshalling in version bubble
-            // mode when the core library is included in the bubble.
+            //    2) We're compiling any module, and no marshalling is needed, or
+            //    3) We're compiling any module, and core library module is in the same bubble, and marhaller supports compilation
 
             Debug.Assert(method is EcmaMethod);
 
@@ -344,6 +342,9 @@ public sealed override bool GeneratesPInvoke(MethodDesc method)
             if (((EcmaMethod)method).Module.Equals(method.Context.SystemModule))
                 return true;
 
+            if (_versionBubbleModuleSet.Contains(method.Context.SystemModule))
+                return !Marshaller.IsMarshallingNotSupported(method);
+
             return !Marshaller.IsMarshallingRequired(method);
         }
 
diff --git a/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs b/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs
index 636c698e8d5..4bc3d1340e2 100644
--- a/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs
+++ b/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs
@@ -141,5 +141,37 @@ public static bool IsMarshallingRequired(MethodSignature methodSig, ParameterMet
 
             return false;
         }
+
+        public static bool IsMarshallingNotSupported(MethodDesc targetMethod)
+        {
+            Debug.Assert(targetMethod.IsPInvoke);
+
+            if (targetMethod.IsUnmanagedCallersOnly)
+                return true;
+
+            PInvokeMetadata metadata = targetMethod.GetPInvokeMethodMetadata();
+            PInvokeFlags flags = metadata.Flags;
+
+            if (flags.SetLastError)
+                return true;
+
+            if (!flags.PreserveSig)
+                return true;
+
+            if (MarshalHelpers.ShouldCheckForPendingException(targetMethod.Context.Target, metadata))
+                return true;
+
+            var marshallers = GetMarshallersForMethod(targetMethod);
+            for (int i = 0; i < marshallers.Length; i++)
+            {
+                if (marshallers[i].GetType() == typeof(NotSupportedMarshaller))
+                    return true;
+            }
+
+            return false;
+        }
     }
 }
```

### More detailed description

This problem happens inside `System.StubHelpers.AnsiBSTRMarshaler.ClearNative`, which tries to cleanup bstr buffer, and subtracts `sizeof(void*)` from ptr (`Marshal.FreeBSTR` in Marshal.Unix.cs actually performs subtraction). This itself happens because `System.StubHelpers.AnsiBSTRMarshaler.ConvertToManaged` for some reason ignores non-bstr buffers. However, pointer returned from native code is not bstr, but a simple buffer. So, incorrect pointer is passed to free.

cc @alpencolt @jkotas

### PR DESCRIPTION
**Pull request by mangod9**
Fixes https://github.com/dotnet/runtime/issues/54820. 

cc @dotnet/crossgen-contrib  @MichalStrehovsky

### CODE REVIEW

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs [hunk 1]
```diff
@@ -1581,13 +1581,7 @@ protected override void EmitCleanupManaged(ILCodeStream codeStream)
 
     class AnsiStringMarshaller : Marshaller
     {
-        internal override bool CleanupRequired
```
Comment (mangod9) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1584]: tried to mimic stub for `ILCSTRMarshaler` from ilmarshallers.cpp, where its marked with no CleanupRequired.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs [hunk 2]
```diff
@@ -1603,24 +1597,76 @@ protected override void TransformManagedToNative(ILCodeStream codeStream)
             // ANSI marshalling. Allocate a byte array, copy characters
             //
 
-#if READYTORUN
```
Comment (mangod9) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1606]: do we have a usecase for non `READYTORUN`, or should we cleanup the codebase?

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs [hunk 3]
```diff
@@ -1603,24 +1597,76 @@ protected override void TransformManagedToNative(ILCodeStream codeStream)
...
             var stringToAnsi =
-                Context.SystemModule.GetKnownType("System.StubHelpers", "AnsiBSTRMarshaler")
+                Context.SystemModule.GetKnownType("System.StubHelpers", "CSTRMarshaler")
                 .GetKnownMethod("ConvertToNative", null);
+
+            bool bPassByValueInOnly = In && !Out && !IsManagedByRef;
+            ILLocalVariable localBuffer = emitter.NewLocal(Context.GetWellKnownType(WellKnownType.IntPtr));
+            if (bPassByValueInOnly)
```
Comment (mangod9) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1606]: is there a reason why this logic cant move to `System.StubHelpers.CSTRMarshaler` ?

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs (hunk 2 above)
Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1606]: These READYTORUN ifdefs is allows easier sharing of the code with the NativeAOT branch.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs (hunk 3 above)
Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1606]: Yes, it would be nice to have majority of the logic in C#, and minimize amount of the hand-emitted IL.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs (hunk 1 above)
Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1584]: That does not sound right. This needs cleanup to free the buffer.

Comment (mangod9) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1584]: so looking further at `ILCSTRMarshaler` native cleanup is [required](https://github.com/dotnet/runtime/blob/317783916d5695d86b087b45220a28c5d8db9fc6/src/coreclr/vm/ilmarshalers.cpp#L477), but not for managed. Doesnt look like this cg2 implementation makes such a differentiation. Perhaps that is the root of the problem since the failure only occurs during native->Managed string marshalling?

**Comment by mangod9** [comment]
@AaronRobinsonMSFT as well.. perhaps we should just fix the `out string` case and refactor these helpers in 7.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs (hunk 1 above)
Comment (mangod9) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1584]: I have updated the `CleanupManaged` logic with the one from which seems to work https://github.com/dotnet/runtime/blob/317783916d5695d86b087b45220a28c5d8db9fc6/src/coreclr/vm/ilmarshalers.cpp#L483.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs (hunk 2 above)
Comment (mangod9) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1606]: ok, thanks. Have keep `!READYTORUN` as-is then.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs [hunk 4]
```diff
@@ -1581,6 +1581,10 @@ protected override void EmitCleanupManaged(ILCodeStream codeStream)
 
     class AnsiStringMarshaller : Marshaller
     {
+        const int MAX_LOCAL_BUFFER_LENGTH = 256; // TODO: Is this accurate on all platforms?
+
+        private ILLocalVariable m_localBuffer = default;
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1586]:
```suggestion
        private ILLocalVariable _localBuffer = default;
```
Our convention for C# is to use `_` prefix for instance fields.

Comment (mangod9) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1586]: yup will rename, once current CI job completes.

**Comment by mangod9** [comment]
crossgen2 outerloop failures are comparable to main runs.

**Comment by mangod9** [comment]
@VSadov since we saw this show up as part of this issue: https://github.com/dotnet/runtime/issues/54759. Any comments / concerns with this change? 

Wonder how we hadn't seen any previous issues here since libraries have been compiled using cg2 for a few previews now and a simple interop call with `out string` should hit this case.

**Comment by VSadov** [comment]
@mangod9 - the fix look reasonable and the issue is very likely the same as one observed in #54759. 

As for why we have not seen this sooner - maybe seeing a combination of "out" parameters in interop scenario, on Linux, with crossgen2 just took time to observe...

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs [hunk 5]
```diff
@@ -1581,6 +1581,10 @@ protected override void EmitCleanupManaged(ILCodeStream codeStream)
 
     class AnsiStringMarshaller : Marshaller
     {
+        const int MAX_LOCAL_BUFFER_LENGTH = 256; // TODO: Is this accurate on all platforms?
```
Comment (mangod9) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1584]: MAX_PATH on windows is `260` so will update this. assume same value is used on other platforms in the PAL.

**Comment by MichalStrehovsky** [comment]
Do we need a regression test?

**Comment by mangod9** [comment]
yeah I am hoping there are some interop tests already covering `out string` scenario which we could add to the r2r pipeline. @AaronRobinsonMSFT @jkoritzinsky @elinor-fung do you happen to know if any exist?

**Comment by jkotas** [comment]
We have a lot of tests for this. The problem is that the interop stub generation in crossgen is currently only enabled for CoreLib, so it is impossible to test.

We would need to enable it for everything in CoreLib version bubble to make it testable by changing [this](https://github.com/dotnet/runtime/blob/333c4e72b83a08288db929ac56c0e336c936b655/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCompilationModuleGroupBase.cs#L362) to `if (_versionBubbleModuleSet.Contains(method.Context.SystemModule))`.

**Comment by mangod9** [comment]
which is being done in this PR: https://github.com/dotnet/runtime/pull/54847? So a combination of the two PRs (without skipping `AnsiStringMarshaller`) would suffice?

**Comment by jkotas** [comment]
Yes, assuming we have appropriate large version bubble test leg.

**Comment by mangod9** [comment]
with the latest change I am hitting an issue similar to this: https://github.com/dotnet/runtime/issues/51189. so more of these marshallers would need updates to work with R2R

**Comment by jkotas** [comment]
I would recommend undoing the last change, and deal with the testing later.

We need a unified intentionally designed set of helpers for marshalling strings that are shared between runtime-generated, crossgen-generated and source-generated interop.

**Comment by mangod9** [comment]
> I would recommend undoing the last change, and deal with the testing later.

yeah that seems like the best approach to get this merged. Will revert that change.

**Comment by mangod9** [comment]
ok, CI is good now. crossgen2-composite failures are at par with main.

**Comment by MichalStrehovsky** [comment]
Btw, disabling the Utf8Marshaller would be as simple as deleting these two lines: https://github.com/dotnet/runtime/blob/d431d6a15726797965336176efe9ae15aba241fd/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs#L28-L29. I don't think Utf8Marshaller as it is right now works with crossgen2 at all.

Looks like all of this slipped through the cracks because nobody realized it's pretty much not exercised by anything.

**Comment by mangod9** [comment]
yeah will do that as a separate change. Believe there are other ones (like `UnicodeString`) which need to excluded for R2R.

**Comment by mangod9** [comment]
Any other concerns with this?

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs [hunk 6]
```diff
@@ -1581,6 +1581,10 @@ protected override void EmitCleanupManaged(ILCodeStream codeStream)
 
     class AnsiStringMarshaller : Marshaller
     {
+        const int MAX_LOCAL_BUFFER_LENGTH = 260 + 1; // MAX_PATH + 1 
+
+        private ILLocalVariable _localBuffer = default;
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1586]: I think unused locals would break the build.

```suggestion
#if READYTORUN
        const int MAX_LOCAL_BUFFER_LENGTH = 260 + 1; // MAX_PATH + 1 

        private ILLocalVariable _localBuffer;
#endif
```

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs [hunk 7]
```diff
@@ -1605,12 +1609,75 @@ protected override void TransformManagedToNative(ILCodeStream codeStream)
...
+                var noOptimize = emitter.NewCodeLabel();
+
+                // if == NULL, goto NoOptimize
+                LoadManagedValue(codeStream);
+                codeStream.Emit(ILOpcode.brfalse, noOptimize);
+
+                // String.Length + 2
+                LoadManagedValue(codeStream);
+                var stringLen =
+                            Context.SystemModule.GetKnownType("System", "String")
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1635]:
```suggestion
                            Context.GetWellKnownType(WellKnownType.String)
```

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs [hunk 8]
```diff
@@ -1605,12 +1609,75 @@ protected override void TransformManagedToNative(ILCodeStream codeStream)
...
+            }
+
             int flags = (PInvokeFlags.BestFitMapping ? 0x1 : 0)
                 | (PInvokeFlags.ThrowOnUnmappableChar ? 0x100 : 0);
+
+            // CSTRMarshaler.ConvertToNative pManaged, dwAnsiMarshalFlags, pLocalBuffer
             codeStream.EmitLdc(flags);
             LoadManagedValue(codeStream);
+
+            if (_localBuffer != default)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1672]: Might be better to use `ILLocalVariable?` as the type of _localBuffer. This condition will also be true if we created a local and it was the first local (index 0).

**Review by MichalStrehovsky — APPROVED** [review]
Looks good otherwise.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs (hunk 8 above)
Comment (mangod9) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs]: makes sense, changed in latest commit.
