### PR TITLE
Fixes overwrite of last captured managed stack frame address in EvenPipe stack trace.

### LINKED ISSUE #71640: .NET 7 dotnet-trace output has `???` in stacks on Android
### Description

If I follow the instructions here:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md

.NET 7 looks like this:

image

While .NET 6 looks like:

image

### Reproduction Steps

Use `dotnet-dsrouter` and `dotnet-trace` to get a `.speedscope` file, following instructions here:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md

### Expected behavior

There isn't a stack frame that says `???`

### Actual behavior

There is a stack frame that says `???`

### Regression?

Yes, worked in .NET 6

### Known Workarounds

_No response_

### Configuration

This was happening with the .NET versions listed here: https://github.com/xamarin/xamarin-android/commit/a4a1c58642c22af60231c81eb567da4f057d93c6

.NET SDK 7.0.100-preview.7.22327.1

### Other information

Example `.speedscope` and `.nettrace` files:

[dotnet-new-maui-7.zip](https://github.com/dotnet/runtime/files/9047380/dotnet-new-maui-7.zip)

### PR DESCRIPTION
**Pull request by lateralusX**
When collecting stack frames in EventPipe, buffer manager buffer layout depends on the struct layout of the compiler up until data gets serialized into blocks and put into output stream following nettrace format.

In the past, there was a 1:1 map between the data collected for a stack trace and what was copied into buffer manager memory. Due to inefficiency, wasting a lot of memory when having small stack traces, this was optimized by https://github.com/dotnet/runtime/pull/68134, greatly reducing overhead and improved EventPipe throughput.

That change started to use a different struct when capturing the callstack compared to the layout written into buffer manager.
Since buffer manager memory still relies on compiler struct layout, code must take that into account when copying stack data into buffer manager memory, but the new optimized implementation didn't, meaning that it fails in cases where compiler adds padding inside EventPipeStackContentsInstance (done on 64-bit bit systems). That in turn will write event payload, starting 4 bytes into last captured stack frame causing issues for tools to symbolicate address, but payload data will still be correct, since EventPipeEventInstance keeps pointer to payload data, meaning most of the event will still be correct, covering up the overwrite to only affect last managed stack frame and only on 64-bit release builds.

Fix adjust the size calculation and make sure it takes any padding added by compiler into the computation of EventPipeEventInstance size.

Fixes #71640

### CODE REVIEW

File: src/native/eventpipe/ep-stack-contents.h [hunk 1]
```diff
@@ -215,58 +214,57 @@ EventPipeStackContentsInstance *
...
-ep_stack_contents_instance_get_total_size (const EventPipeStackContentsInstance *stack_contents_instance)
+ep_stack_contents_instance_get_full_size (const EventPipeStackContentsInstance *stack_contents_instance)
 {
-	// The total size including the size
 #ifdef EP_CHECKED_BUILD
-	return stack_contents_instance ? (ep_stack_contents_instance_get_next_available_frame (stack_contents_instance) * sizeof (uintptr_t) * 2) + sizeof (uint32_t) : sizeof (uint32_t);
+	return stack_contents_instance ? (ep_stack_contents_instance_get_next_available_frame (stack_contents_instance) * sizeof (uintptr_t) * 2) : 0;
 #else /* EP_CHECKED_BUILD */
-	return stack_contents_instance ? (ep_stack_contents_instance_get_next_available_frame (stack_contents_instance) * sizeof (uintptr_t)) + sizeof (uint32_t) : sizeof (uint32_t);
+	return stack_contents_instance ? (ep_stack_contents_instance_get_next_available_frame (stack_contents_instance) * sizeof (uintptr_t)) : 0;
```
Comment (hoyosjs) [inline src/native/eventpipe/ep-stack-contents.h:258]: Any reason not to use sizeof on stack_contents_instance.stack_frames instead of assumind it's just always one?

Comment (lateralusX) [reply src/native/eventpipe/ep-stack-contents.h:258]: The size of stack_contents_instance.stack_frames is just a way to get a pointer to that field when you use the struct into memory (will make sure you get the correct offset into the struct, depending on additional fields, padding etc), but the actual size is always dynamically allocated, and that real size of stack_contents_instance.stack_frames is whats gets calculated by above expression. That way you get a struct with dynamic size of stack_frames field, only consuming the exact needed amount of memory in buffer manager.

**Review by noahfalk — APPROVED** [review]
LGTM

**Comment by noahfalk** [comment]
@davmason

**Comment by lateralusX** [comment]
If there are no more feedback on this PR, I will merge it during the day.
