### PR TITLE
Fix compilation errors if host does not support AVX2

### LINKED ISSUE #50175: AVX ABI errors when building vector tests
I am trying to build and run tests on commit 61889c8e8926aed2a22000c312baa0a7969cc927 (for https://github.com/dotnet/runtime/pull/50148) and running into `-Wpsabi` errors:

```
$ cat /etc/os-release
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
$ uname -m
x86_64
$ rpm -q clang lldb gcc glibc
clang-11.0.0-2.fc33.x86_64
lldb-11.0.0-1.fc33.x86_64
gcc-10.2.1-9.fc33.x86_64
glibc-2.32-4.fc33.x86_64
$ git rev-parse HEAD~
61889c8e8926aed2a22000c312baa0a7969cc927
$ ./build.sh -subset clr
...
$ ./src/tests/build.sh
...
...
runtime/src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256C.cpp:67:24: error: AVX vector return of type 'Vector256C' (aka '__m256i') without 'avx' enabled changes the ABI [-Werror,-Wpsabi]
    Vector256C value = GetVector256C(e00, e01, e02, e03, e04, e05, e06, e07, e08, e09, e10, e11, e12, e13, e14, e15);
                       ^                                                                                              1 error generated.                                                                                                    
gmake[2]: *** [Interop/PInvoke/Generics/CMakeFiles/GenericsNative.dir/build.make:810: Interop/PInvoke/Generics/CMakeFiles/GenericsNative.dir/GenericsNative.Vector256C.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
runtime/src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256L.cpp:43:24: error: AVX vector return of type 'Vector256L' (aka '__m256i') without 'avx' enabled changes the ABI [-Werror,-Wpsabi]
                 Vector256L value = GetVector256L(e00, e01, e02, e03);                                                             
                                    ^                                   
[ 56%] Built target UnmanagedCallersOnlyDll
1 error generated.                                         
gmake[2]: *** [Interop/PInvoke/Generics/CMakeFiles/GenericsNative.dir/build.make:849: Interop/PInvoke/Generics/CMakeFiles/GenericsNative.dir/GenericsNative.Vector256L.cpp.o] Error 1                                         
[ 57%] Built target BoolNative                                                                                        
[ 58%] Built target UIntPtrNative
runtime/src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256B.cpp:99:24: error: AVX vector return of type 'Vector256B' (aka '__m256i') without 'avx' enabled changes the ABI [-Werror,-Wpsabi]
    Vector256B value = GetVector256B(e00, e01, e02, e03, e04, e05, e06, e07, e08, e09, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31);                          
                       ^                                                                      
```

Is this a known issue? Is there a fix/workaround available for this?

### PR DESCRIPTION
**Pull request by kant2002**
Closes #50175

### CODE REVIEW

**Comment by kant2002** [comment]
Whom I can ping, so it can be looked into? I have old laptop at home, where I intend to play with NativeAOT. @hoyosjs can you take a look?
The build failures seems to be unrelated.

**Comment by danmoseley** [comment]
Pinvoke tests - @AaronRobinsonMSFT  maybe

File: src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256B.cpp [hunk 1]
```diff
@@ -8,9 +8,14 @@
 
 #if defined(TARGET_XARCH)
     #include <immintrin.h>
+#elif defined(TARGET_ARMARCH)
```
Comment (AaronRobinsonMSFT) [inline src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256B.cpp:11]: My only feedback would be to add a comment in all files in the else branch for `TARGET_ARMARCH`. The comment should state `// Intentionally empty`

**Review by AaronRobinsonMSFT — APPROVED** [review]
FYI @tannergooding

**Comment by kant2002** [comment]
@tannergooding can I ask you to take a look at this PR?

File: src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256U.cpp [hunk 2]
```diff
@@ -8,9 +8,15 @@
 
 #if defined(TARGET_XARCH)
     #include <immintrin.h>
+#elif defined(TARGET_ARMARCH)
+    // Intentionally empty
+#else
+    #error Unsupported target architecture
+#endif
 
+#if defined(__AVX2__)
```
Comment (tannergooding) [inline src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256U.cpp:17]: Which compilers define this and under what scenarios is it defined?

AFAIK, most compilers set things like `__AVX2__` based on what your compiler switches are, not based on what the underlying hardware supports. This would require us compiling these assemblies for `-march=native` on GCC/Clang and doing some CMake magic for `msvc`.

Comment (kant2002) [reply src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256U.cpp:17]: You are right. I do not account for that. 
I found only one way perform CMake magic for arch detection, and I do not like that. This is it https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/cmakeFindModules/OptimizeForArchitecture.cmake#L357
This appears to be overkill for this only case where AVX detection needed.
Being a bit selfish, what if just add to this tests CMakeLists.txt
```
if (MSVC)
    # MSVC require proper detection of the host architecture, for now assume that AVX2 always used.
    add_compile_options(/arch:AVX2)
else()
    add_compile_options(-march=native)
endif()
```
In my understanding this improve situation with GCC and Clang, at the same time, preserve status quo in MSVC.
I know that this is just kicking can down the road, but maybe that can be acceptable compromise, since this is seems to be affect only minority of users and all of them so far was on Linux.

Comment (tannergooding) [reply src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256U.cpp:17]: That seems fine to me. I believe it might not be an issue on MSVC due to how the compiler handles `__m256` vs how Clang/GCC handle it.

The actual logic executing should be entirely dependent on the managed side `if (Avx.IsSupported)` check and so shouldn't execute.

Comment (kant2002) [reply src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256U.cpp:17]: @tannergooding I enable `--march=native` only on Clang and GCC on non-ARM builds. Would this works in your opinion?

Comment (tannergooding) [reply src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256U.cpp:17]: Provided the code is actually compiled and works as expected on MSVC, then it looks good to me.

I'm not familiar enough with what each compiler does by default to know off the top of my head.

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256U.cpp:17]: @kant2002 Have you been able to verify the behavior here?

Comment (kant2002) [reply src/tests/Interop/PInvoke/Generics/GenericsNative.Vector256U.cpp:17]: @AaronRobinsonMSFT Now yes.
