### PR TITLE
Fix nested calls to Assembly Load Start tracing

### LINKED ISSUE #55786: When assembly load tracing is enabled on Linux startup fails if System.Private.CoreLib is part of a composite R2R image
### Description

name_with_pid test is failing in CI on Linux platforms. For instance, see https://dnceng.visualstudio.com/public/_build/results?buildId=1239435&view=results

This is caused by misbehavior when attempting to run an application compiled as a composite R2R image under our performance tracing tools.

### Regression?

No, composite R2R images are new to our customers in .NET 6.

### PR DESCRIPTION
**Pull request by davidwrighton**
The name_with_pid test ends up testing the behavior of event tracing in the presence of composite images.

In the presence of a composite image, it might happen attempting to send trace data may force an attempt to load System.Private.CoreLib thus causing an stackoverflow as attempting to report the load of System.Private.CoreLib will trigger a load of System.Private.CoreLib, etc. This fix steps around the issue by using a thread local variable to skip subsequent attempts to report the load of System.Private.CoreLib.

Fixes #55786

### CODE REVIEW

File: src/coreclr/binder/bindertracing.cpp [hunk 1]
```diff
@@ -246,7 +251,7 @@ namespace BinderTracing
 
         // ActivityTracker or EventSource may have triggered the system satellite load.
         // Don't track system satellite binding to avoid potential infinite recursion.
-        m_ignoreBind = m_bindRequest.AssemblySpec->IsCoreLibSatellite();
+        m_ignoreBind = m_bindRequest.AssemblySpec->IsCoreLibSatellite() || (t_AssemblyLoadStartInProgress && m_bindRequest.AssemblySpec->IsCoreLib());
```
Comment (elinor-fung) [inline src/coreclr/binder/bindertracing.cpp:254]: The corelib satellite was the same kind of thing (except it wasn't really interesting, so we just skipped it entirely). I think it makes sense for this to become:
```
m_ignoreBind = t_AssemblyLoadStartInProgress && (m_bindRequest.AssemblySpec->IsCoreLib() || m_bindRequest.AssemblySpec->IsCoreLibSatellite());
```

Comment (elinor-fung) [reply src/coreclr/binder/bindertracing.cpp:254]: Can you also update the comment above?

**Review by elinor-fung — APPROVED** [review]
