### PR TITLE
[wasm] First attempt at a wasm app host

### LINKED ISSUE #67236: WebAssembly Browser App project fails to run
### Description

When I try to `dotnet run` a WebAssembly Browser App I get:

A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\WDAGUtilityAccount\Desktop\WasmBrowserApp\bin\Debug\net7.0\browser-wasm\'.

Presumably this is because the app is intended to be published and run in a browser, but there should be some sort of dev experience for running the app locally.

### Reproduction Steps

- Install .NET 7 Preview 2
- `dotnet workload install wasm-tools`
- `dotnet new wasmbrowser`
- `dotnet run`

### Expected behavior

App successfully builds and runs

### Actual behavior

C:\Users\WDAGUtilityAccount\Desktop\WasmBrowserApp>dotnet run
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\WDAGUtilityAccount\Desktop\WasmBrowserApp\bin\Debug\net7.0\browser-wasm\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\Users\WDAGUtilityAccount\Desktop\WasmBrowserApp\bin\Debug\net7.0\browser-wasm\browser.runtimeconfig.json' did not specify a framework.
  - If this should be a framework-dependent app, specify the appropriate framework in 'C:\Users\WDAGUtilityAccount\Desktop\WasmBrowserApp\bin\Debug\net7.0\browser-wasm\browser.runtimeconfig.json'.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by radical**
First attempt at implementing a wasm app host

Regular dotnet apps can be run with `dotnet run`. But this is not the case for
wasm apps. We use `xharness` to run the test apps that we generate for library
tests.

Templates for browser, and console wasm projects were added recently, but they
have to be run manually by either invoking a v8 script, or running a
`http-server` in the bundle directory. Though to use a debugger with this
requires starting the debug proxy separately, and connecting few bits.

# WasmAppHost

This PR adds a new `WasmAppHost`, which can be used through `dotnet run`:

- it can run "wasm app" from it's `AppBundle` directory, using various hosts
  like `v8`, `node`, or a browser. An example use:

    ```
    $ dotnet new wasmconsole
    $ dotnet run
    WasmAppHost --runtime-config /tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle//c0.runtimeconfig.json
    [02:26:40] info: host[0] Running: node main.cjs
    [02:26:40] dbug: host[0] Using working directory: /tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle
    Incoming arguments:
    Application arguments:
    Debugger.Debug: DEBUGGING ENABLED

    mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
    Could not find symbols file dotnet.js.symbols. Ignoring.
    Initializing.....
    Hello, Console!
    ```

    The console template project is run with `node` by default.

- it supports a `--debug` parameter, which (for the browser case) would startup
  a webserver, and the debug proxy for Chrome, and firefox.

```
$ dotnet new wasmbrowser

$ dotnet run --debug
WasmAppHost --runtime-config /workspaces/test/br0/bin/Debug/net7.0/browser-wasm/AppBundle//br0.runtimeconfig.json --debug --forward-console
Debug proxy for chrome now listening on http://127.0.0.1:9300/. And expecting chrome at http://localhost:9222/
Hosting environment: Production
Content root path: /workspaces/test/br0/bin/Debug/net7.0/browser-wasm/AppBundle
Now listening on: http://127.0.0.1:9300
Debug proxy for firefox now listening on tcp://127.0.0.1:6300. And expecting firefox at port 6000 .

App url: http://127.0.0.1:9000/index.html
App url: https://127.0.0.1:38331/index.html
```

- This enables using `dotnet run` with wasm samples, and library tests too.

## How do I try this out?

You'll need a dotnet with the updated packs. For now, you can use:

```
$ ./dotnet.sh build -p:TargetOS=Browser -p:TargetArchitecture=wasm -p:Configuration=Release src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj /t:InstallWorkloadUsingArtifacts
```

.. which would install a sdk in `artifacts/bin/dotnet-workload` with all the packs installed.

- Use that dotnet to create console, or browser wasm apps from templates, for example `dotnet new wasmconsole`, or `dotnet new wasmbrowser`.

### Debugging library tests

```
runtime$ ./artifacts/bin/dotnet-workload/dotnet run -f net7.0 -r browser-wasm -c $YourRuntimeConfig --project src/libraries/System.Buffers/tests/System.Buffers.Tests.csproj -p:DebuggerSupport=true --debug --host browser
```

- If the runtime was built in `Release` config, then you need to add `-p:DebuggerSupport=true`, so the pdbs would get deployed
- And use `--debug` to start the debugger

- Opening the url will show a `Run tests` button, which you can click after connecting with the IDE, to start running the tests

## Notes, and TODO

- `WasmAppHost`, along with the debug proxy are bundled in the `WebAssembly.Sdk` pack right now.
  - This might be changed in the future to use the dotnet app host pack pattern, and with
    additional support adding in the Sdk.
  - This would also allow using `launchSettings.json`, similar to blazor

- `WasmAppHost` depends on host config in `runtimeconfig.json`, which can be
  controlled by a `runtimeconfig.template.json` in the project directory.

- Needs more tests, cleanup, `--help` for command line arguments
- `app-support.*js` in templates, and `test-main.js` need more work to share the code

Fixes https://github.com/dotnet/runtime/issues/67236

### CODE REVIEW

File: src/mono/wasm/templates/templates/browser/app-support.js [hunk 1]
```diff
@@ -0,0 +1,427 @@
...
+    } else if (typeof scriptArgs !== "undefined") {
+        processedArguments = processArguments(Array.from(scriptArgs));
+    } else if (typeof WScript !== "undefined" && WScript.Arguments) {
+        processedArguments = processArguments(Array.from(WScript.Arguments));
+    }
+} catch (e) {
+    console.error(e);
+}
+
+if (is_node) {
```
Comment (pavelsavara) [inline src/mono/wasm/templates/templates/browser/app-support.js:150]: I would prefer to prune code which we don't actually need (this is browser, not nodejs).
I would also like it more if all of it was in `main.js`

File: src/mono/wasm/templates/templates/browser/app-support.js [hunk 2]
```diff
@@ -0,0 +1,427 @@
...
+        tests_done_elem.id = "tests_done";
+        tests_done_elem.innerHTML = exit_code.toString();
+        document.body.appendChild(tests_done_elem);
+
+        if (forward_console)  {
+            const stop_when_ws_buffer_empty = () => {
+                if (consoleWebSocket.bufferedAmount == 0) {
+                    // tell xharness WasmTestMessagesProcessor we are done. 
+                    // note this sends last few bytes into the same WS
+                    console.log("WASM EXIT " + exit_code);
```
Comment (pavelsavara) [inline src/mono/wasm/templates/templates/browser/app-support.js:372]: Is exit code "in-scope" for browser host ?

Comment (radical) [reply src/mono/wasm/templates/templates/browser/app-support.js:372]: Some of this stuff can be pruned like you said. But a big portion of the code is shared, like the arguments processing etc. It will be used in 3 places - the two templates, and test-main.js .

Comment (radical) [reply src/mono/wasm/templates/templates/browser/app-support.js:372]: > Is exit code "in-scope" for browser host ?

This is actually useful in the case when you use `--forward-console`, which shows the messages in the terminal. In that case, the exit message is helpful, and I'm able to use it for tests too. So, I'm printing that only when forwarding the console.

File: src/mono/wasm/templates/templates/console/app-support.cjs [hunk 3]
```diff
@@ -0,0 +1,427 @@
...
+    error: console.error
+};
+
+let consoleWebSocket;
+let processedArguments = null;
+let is_debugging = false;
+// FIXME: process args before all this
+let forward_console = true;
+
+function processArguments(incomingArguments) {
```
Comment (pavelsavara) [inline src/mono/wasm/templates/templates/console/app-support.cjs:34]: perhaps we don't want to publish most of the options we have internally

File: src/mono/wasm/templates/templates/console/app-support.cjs [hunk 4]
```diff
@@ -0,0 +1,427 @@
...
+        profilers,
+        setenv,
+        runtime_args,
+        enable_gc,
+        diagnostic_tracing,
+        working_dir,
+    }
+}
+
+function proxyConsoleMethod(prefix, func, asJson) {
```
Comment (pavelsavara) [inline src/mono/wasm/templates/templates/console/app-support.cjs:90]: I prefer to not have this functionality in the host.

File: src/mono/wasm/templates/templates/console/app-support.cjs [hunk 5]
```diff
@@ -0,0 +1,427 @@
...
+        } else {
+            console.log("WASM EXIT " + exit_code);
+        }
+
+    } else if (App && App.INTERNAL) {
+        App.INTERNAL.mono_wasm_exit(exit_code);
+    }
+}
+
+async function loadDotnet(file) {
```
Comment (pavelsavara) [inline src/mono/wasm/templates/templates/console/app-support.cjs:388]: if the template is ES6, let's stick with `import createDotnetRuntime from './dotnet.js'`
this complex way is there to support all possible combinations.

File: src/mono/wasm/templates/templates/console/app-support.cjs [hunk 6]
```diff
@@ -0,0 +1,427 @@
...
+        const url = new URL(decodeURI(window.location));
+        let urlArguments = []
+        for (let param of url.searchParams) {
+            if (param[0] == "arg") {
+                urlArguments.push(param[1]);
+            }
+        }
+        processedArguments = processArguments(urlArguments);
+    } else if (typeof arguments !== "undefined") {
+        processedArguments = processArguments(Array.from(arguments));
```
Comment (pavelsavara) [inline src/mono/wasm/templates/templates/console/app-support.cjs:140]: this is for v8

Comment (pavelsavara) [reply src/mono/wasm/templates/templates/console/app-support.cjs:140]: `processArguments` could be lifted to `dotnet.js` and added to it's `DotnetModuleConfig`

**Comment by radical** [comment]
Runtime test failures https://github.com/dotnet/runtime/issues/69517, and https://github.com/dotnet/runtime/issues/69518 .

I will re-enable all the other jobs that I had disabled.

**Review by thaystg — APPROVED** [review]
It LGTM, and also I tested and it works :)

**Comment by radical** [comment]
The failures are known, and have issues filed.
