### PR TITLE
[wasm][debugger] Remove workaround to get pauseOnExceptions setting

### LINKED ISSUE #62146: Debugger - Blazor WASM: Uncaught pause_on_uncaught (anonymous) @ VM324:1
### Describe the bug
Loading a WASM site locally with debugging enabled gives the following output in the console:

image

### Further technical details
- ASP.NET Core version: 6.0.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Rider EAP 9
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

### PR DESCRIPTION
**Pull request by thaystg**
Remove workaround to get pauseOnExceptions, now we receive it from Browser.
Fixes #62146

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 1]
```diff
@@ -513,13 +492,7 @@ protected override async Task<bool> AcceptCommand(MessageId id, JObject parms, C
...
                     {
                         string state = args["state"].Value<string>();
-                        context.PauseOnExceptions = state switch
-                        {
-                            "all"      => PauseOnExceptionsKind.All,
-                            "uncaught" => PauseOnExceptionsKind.Uncaught,
-                            "none"     => PauseOnExceptionsKind.None,
-                            _          => PauseOnExceptionsKind.Unset
-                        };
+                        context.PauseOnExceptions = GetPauseOnExceptionsStatusFromString(state);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:495]: Should `context.PauseOnExceptions` be set if `GetPauseOnExceptionsStatusFromString` returns `.Unset`? It would override the existing value that it would have. Same for the other location.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 2]
```diff
@@ -21,14 +21,14 @@ internal class MonoProxy : DevToolsProxy
...
         protected Dictionary<SessionId, ExecutionContext> contexts = new Dictionary<SessionId, ExecutionContext>();
-        private const string sPauseOnUncaught = "pause_on_uncaught";
-        private const string sPauseOnCaught = "pause_on_caught";
 
         public static HttpClient HttpClient => new HttpClient();
 
         // index of the runtime in a same JS page/process
         public int RuntimeId { get; private init; }
         public bool JustMyCode { get; private set; }
+        public PauseOnExceptionsKind PauseOnExceptions { get; set; }
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:30]: I think this should be private, and maybe named something like `_defaultPauseOnExceptions`, and initialized to `Unset`.

**Review by radical — CHANGES_REQUESTED** [review]

**Comment by radical** [comment]
What changed that allows this to be used, instead of the workaround?

File: src/mono/wasm/debugger/BrowserDebugProxy/Firefox/FirefoxExecutionContext.cs [hunk 3]
```diff
@@ -14,7 +14,7 @@ internal sealed class FirefoxExecutionContext : ExecutionContext
     public string? GlobalName { get; set; }
     public Result LastDebuggerAgentBufferReceived { get; set; }
 
-    public FirefoxExecutionContext(MonoSDBHelper sdbAgent, int id, string actorName) : base(sdbAgent, id, actorName)
+    public FirefoxExecutionContext(MonoSDBHelper sdbAgent, int id, string actorName, PauseOnExceptionsKind pauseOnExceptions = PauseOnExceptionsKind.Unset) : base(sdbAgent, id, actorName, pauseOnExceptions)
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/BrowserDebugProxy/Firefox/FirefoxExecutionContext.cs:17]: We are not using `FirefoxExecutionContext` with non-default `pauseOnExceptions` anywhere, then maybe let's not change it yet and call instead:
```suggestion
    public FirefoxExecutionContext(MonoSDBHelper sdbAgent, int id, string actorName) : base(sdbAgent, id, actorName, PauseOnExceptionsKind.Unset)
```

**Review by ilonatommy — APPROVED** [review]
Looks good!

**Review by radical — APPROVED** [review]
LGTM! 👍

**Comment by radical** [comment]
> Now chrome/edge/vs/vscode send us the settings when we start debugging.

Does this need some minimum version of chrome/edge?

**Comment by radical** [comment]
The WBT failure is known, and h related to this pr.
