### PR TITLE
Fix conditions for implicit use of hardware intrinsics

### LINKED ISSUE #425: [NativeAOT] Illegal instruction (core dumped) - Ubuntu 20.04
A linux user reported me this issue when using my application launcher built with .NET 5 and latest NativeAOT.
Other linux users everything works fine.
image

You can find the application here: https://www.classicuo.eu/launcher/linux-x64/ClassicUOLauncher-linux-x64-release.zip

This is the cpuinfo:
```
rocessor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 635 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 1700.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 5825.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 635 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 5825.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 2
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 635 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 5825.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 3
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 635 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 1700.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 5825.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate
```

```
X@X-workstation:~/Desktop/CUOLAUNCHER$ gdb ./ClassicUOLauncher 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./ClassicUOLauncher...
ru(gdb) run
Starting program: /home/jhendric/Desktop/CUOLAUNCHER/ClassicUOLauncher 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd7370700 (LWP 50780)]

Thread 1 "ClassicUOLaunch" received signal SIGILL, Illegal instruction.
0x0000000000853af9 in S_P_CoreLib_System_SpanHelpers__IndexOf_0 (searchSpace=@0x7fffffffe2bf: 47 '/', value=0 '\000', length=2147483647)
    at /_/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs:348
348	/_/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs: No such file or directory.
(gdb) bt
#0  0x0000000000853af9 in S_P_CoreLib_System_SpanHelpers__IndexOf_0 (searchSpace=@0x7fffffffe2bf: 47 '/', value=0 '\000', length=2147483647)
    at /_/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs:348
#1  0x000000000081184d in String__Ctor_3 (value=0x7fffffffe2bf "/home/jhendric/Desktop/CUOLAUNCHER/ClassicUOLauncher") at /_/src/libraries/System.Private.CoreLib/src/System/String.cs:189
#2  0x00000000008fdafe in S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeCommandLineArgs (argc=1, argv=0x7fffffffdf98)
    at /_/src/coreclr/src/nativeaot/System.Private.CoreLib/src/Internal/Runtime/CompilerHelpers/StartupCode/StartupCodeHelpers.Extensions.cs:31
#3  0x0000000000c6cde1 in ClassicUOLauncher__Module___StartupCodeMain () at <stdin>:15732480
#4  0x000000000041b2e9 in main (argc=1, argv=0x7fffffffdf98) at /__w/1/s/src/coreclr/src/nativeaot/Bootstrap/main.cpp:186
(gdb) quit
A debugging session is active.

	Inferior 1 [process 50776] will be killed.

Quit anyway? (y or n) y
```

### PR DESCRIPTION
**Pull request by jkotas**
JIT uses hardware intrinsics implicitly in certain cases. Unlike regular hardware intrinsics, these
transformations are not guarded using explicit IsSupported checks. NativeAOT had fragile code that tried
to step around this limitation. This change makes this contract explicit by allowing notifyInstructionSetUsage
callback to return bool that the EE side can use to suppress implicit use of hardware intrinsics.

Fixes dotnet/runtimelab#425

### CODE REVIEW

**Comment by jkotas** [comment]
cc @dotnet/jit-contrib

**Comment by jkotas** [comment]
The full change is at https://github.com/dotnet/runtimelab/pull/435

File: src/coreclr/src/jit/compiler.h [hunk 1]
```diff
@@ -8815,6 +8828,8 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 
         uint64_t compSupportsISA;
```
Comment (tannergooding) [inline src/coreclr/src/jit/compiler.h:8829]: Can we add a brief comment explaining the difference between these 3?

Is it currently (IIRC, please correct anything needed):
* `compSupportsISA`: The compiler is configured to emit such instructions, the target hardware may or may not support it
* `compSupportsISAReported`: Indicates some method is utilizing the given ISA in some code path
*
* `compSupportsISAExactly`: Indicates the VM has said an ISA is supported by the target hardware?

The names aren't super clear and at least for me it gets hard to mentally track which bits do what:
* `compSupportsHWIntrinsic` reports `COMPlus_EnableHWIntrinsic != 0`, `COMPlus_FeatureSIMD != 0` (basically, the compiler reports `true` provided the ISA isn't partially implemented and `HWIntrinsics` aren't generally disabled)
* `compExactlyDependsOn` used to report usage and return `compSupportsISA`; not looks to report usage and return `compSupportsISAExactly` which is dependent on `notifyInstructionSetUsage` returning `true`
* `compOpportunisticallyDependsOn` returns `compExactlyDependsOn` but only if `compSupportsISA` is true, effectively allowing code paths to not report usage if they can codify an alternative instead
*
* `compHWIntrinsicDependsOn` effectively returns `compSupportsISA` but additionally calls `compExactlyDependsOn` if true

Comment (tannergooding) [reply src/coreclr/src/jit/compiler.h:8829]: It's not clear to me exactly why we need `compSupportsISAExactly` for AOT scenarios rather than just having the VM accurately report `compSupportsISA`?
Likewise, for JIT scenarios (at least for S.P.Corelib), I would expect all of our usages are either behind a user provided `IsSupported` call or behind a `compOpportunisticallyDependsOn` check

I had the understanding that in the case of the latter, the method would be marked as using `SSE4.1`, for example, and if at runtime the method did not actually support it, it would be rejitted and get told the actual ISAs supported

Comment (jkotas) [reply src/coreclr/src/jit/compiler.h:8829]: > It's not clear to me exactly why we need compSupportsISAExactly for AOT scenarios rather than just having the VM accurately report compSupportsISA?

For NativeAOT that does not have fallback to JIT, we want to produce code that both works on all platforms and also leverages hardware intrinsics as much as possible. We achieve that by substituting `ISA.IsSupported` with a dynamic check like `bool Popcnt.IsSupport => (g_flags & PopcntBit) != 0;` (this dynamic check is provided by the VM as IL).

This scheme only works for explicit hardware intrinsics that are protected by explicit checks. It does not work for cases where the JIT chooses to use hardware intrinsics implicitly.

Comment (jkotas) [reply src/coreclr/src/jit/compiler.h:8830]: I have updated the comments. Please take a look.

**Review by tannergooding — APPROVED** [review]
