### PR TITLE
[browser][coreCLR] native stack trace symbols

### LINKED ISSUE #76710: [wasm] mono_wasm_trace_logger doesn't display message in FireFox console
`mono_wasm_trace_logger` and `mono_wasm_stringify_as_error_with_stack`  don't work well together on FF

Expected (like in Chrome):
image

Actual (in FF)
image

cc @radical

### PR DESCRIPTION
**Pull request by pavelsavara**
Also more work on
- exit code propagation
- shutdown
- exception logging

Fixes https://github.com/dotnet/runtime/issues/122647
Fixes https://github.com/dotnet/runtime/issues/76710
Fixes https://github.com/dotnet/runtime/issues/122644

when `<EnableDiagnostics>true</EnableDiagnostics>` and `<WasmEmitSymbolMap>true</WasmEmitSymbolMap>` it would translate native stack traces from `wasm-function[1018]` form into a symbol name (even on Release build).

```
Error
    at C (https://localhost:8080/_framework/dotnet.js:271:31)
    at Object.S [as onAbort] (https://localhost:8080/_framework/dotnet.js:256:5)
    at abort (https://localhost:8080/_framework/dotnet.native.b0lnvxzshm.js:8:6505)
    at _abort (https://localhost:8080/_framework/dotnet.native.b0lnvxzshm.js:8:97882)
    at https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[1018]:0x54c75
    at https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[897]:0x46a87
    at https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[2881]:0x127834
    at https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[3100]:0x14cfe1
    at https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[1753]:0x9b746
    at https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[759]:0x3be97
```

Becomes

```
Error
    at C (https://localhost:8080/_framework/dotnet.js:271:31)
    at Object.S [as onAbort] (https://localhost:8080/_framework/dotnet.js:256:5)
    at abort (https://localhost:8080/_framework/dotnet.native.b0lnvxzshm.js:8:6505)
    at _abort (https://localhost:8080/_framework/dotnet.native.b0lnvxzshm.js:8:97882)
    at PROCAbort (https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[1018]:0x54c75)
    at TerminateProcess (https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[897]:0x46a87)
    at SfiNextWorker(StackFrameIterator*, unsigned int*, bool*, bool*) (https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[2881]:0x127834)
    at DispatchExSecondPass(ExInfo*) (https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[3100]:0x14cfe1)
    at DispatchManagedException(Object*, _CONTEXT*, _EXCEPTION_RECORD*, ExKind) (https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[1753]:0x9b746)
    at DispatchManagedException(Object*, ExKind) (https://localhost:8080/_framework/dotnet.native.vp8656wnw0.wasm:wasm-function[759]:0x3be97)
```

### CODE REVIEW

File: src/native/corehost/browserhost/loader/polyfills.ts [hunk 1]
```diff
@@ -153,6 +153,10 @@ export function responseLike(url: string, body: ArrayBuffer | string | null, opt
             return Promise.resolve(JSON.parse(body));
         },
         text: () => {
+            if (typeof body !== "string" && typeof globalThis.TextDecoder !== "undefined") {
+                const decoder = new globalThis.TextDecoder("utf-8");
+                return Promise.resolve(body).then(buffer => decoder.decode(buffer || new Uint8Array()));
```
Comment (campersau) [inline src/native/corehost/browserhost/loader/polyfills.ts]: `body` should not be a promise like object so this can be simplified:

```suggestion
                return decoder.decode(body || new Uint8Array());
```

File: src/native/libs/System.Native.Browser/diagnostics/symbolicate.ts [hunk 2]
```diff
@@ -1,8 +1,86 @@
...
+    //# at http://127.0.0.1:63817/dotnet.wasm:wasm-function[8963]:0x1e23f4
+    regexes.push(/(?<replaceSection>[a-z]+:\/\/[a-zA-Z0-9.:/_~-]*:wasm-function\[(?<funcNum>\d+)\]:0x[a-fA-F\d]+)/g);
+
+    //# <?>.wasm-function[8962]
+    regexes.push(/(?<replaceSection><[^ >]+>[.:]wasm-function\[(?<funcNum>[0-9]+)\])/g);
+
+    const text = symbolTable;
+    symbolTable = undefined;
+    try {
+        text.split(/[\r\n]/).forEach((line: string) => {
```
Comment (radekdoulik) [inline src/native/libs/System.Native.Browser/diagnostics/symbolicate.ts]:
```suggestion
        text.split(/\r?\n|\r/).forEach((line: string) => {
```

**Review by radekdoulik — APPROVED** [review]
Thank you, LGTM

**Review by maraf — APPROVED** [review]
Awesome!
