### PR TITLE
JIT: Handle `FIELD_LIST` for tailcall arg/parameter interference checks

### LINKED ISSUE #122138: JIT Bug: Code Generation Error under inlining (Release only)
### Description

The provided C# code throws an **unexpected** System.Exception inside $Method2$ when compiled in the Release configuration using **.NET 10.0.0**.
The issue is a **JIT code generation error** related to the optimization path activated by the method attributes and repeated execution. The error specifically manifests during the comparison of int? types.

The input values are consistently $999$ and $999$, meaning the comparison $value1 != value2$ should always be $false$. However, the highly optimized JIT-compiled code erroneously evaluates this comparison as $true$, causing the exception.

### Reproduction Steps

// 1. Compile the code below using .NET 10.0.0 in Release configuration.
// 2. Run the application.

```csharp
using System;
using System.Runtime.CompilerServices;

class Program
{
    [MethodImpl(MethodImplOptions.NoOptimization)]
    static void Main()
    {
        var test = new Test();
        while (true)
        {
            test.Method1(0, 0, 0, 999, 999);
        }
    }
}

class Test
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Method1(int a, int b, int c, int value1, int? value2)
    {
        Method2(1, 2, 3, value1, value2);
    }

    public void Method2(long a, int b, int c, int? value1, int? value2)
    {
        try
        {
            if (value1 != value2)
            {
                throw new Exception($"{value1} != {value2}");
            }
        }
        catch
        {
            throw;
        }
    }
}
```

### Expected behavior

The program should run indefinitely without throwing an exception.

### Actual behavior

The program throws $System.Exception$ shortly after startup, indicating the JIT incorrectly evaluated the comparison of two equal non-null $int?$ values in the optimized code.

### Regression?

net9.0 in not affected

### Known Workarounds

_No response_

### Configuration

 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\10.0.100\

Target framework: net10.0

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jakobbotsch**
Since tailcalls place the arguments in the incoming parameter area it corrupts the value of existing parameters to the function. To handle this there is logic in place to create defensive copies of the parameters if we detect that we will need those later in the tailcalling sequence. However, this logic was missing handling when the argument was a `FIELD_LIST`:

- When an argument was a `FIELD_LIST` we did not take into account that we needed to look for parameter uses starting from its operands, and not just from the `FIELD_LIST` itself. Fix this by introducing a `FirstOperand` function and use it here.

- When the value of a `PUTARG_STK` was a contained `FIELD_LIST` we did not take into account that its codegen may invalidate the values of its own operands. Detect this case and introduce temps for it.

Fix #122138

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @EgorBo 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1220231&view=ms.vss-build-web.run-extensions-tab). Some minor regressions where we now introduce some more defensive copying.

File: src/tests/JIT/Regression/JitBlue/Runtime_122138/Runtime_122138.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System;
+using System.Runtime.CompilerServices;
+using Xunit;
+
+public class Runtime_122138
```
Comment (am11) [inline src/tests/JIT/Regression/JitBlue/Runtime_122138/Runtime_122138.cs:8]: Does this test fail without the fix? I tried it in `dotnet new xunit` project on win-x64 with `dotnet test -c Release`, it passed; while `dotnet run -c Release` original repro failed with `Unhandled exception. System.Exception: 769 != 999`.

Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_122138/Runtime_122138.cs:8]: Yes, it fails with `DOTNET_TieredCompilation=0`.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS 

[Minor diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1220231&view=ms.vss-build-web.run-extensions-tab)

(Edit: oh, already tagged above)

**Review by EgorBo — APPROVED** [review]

**Review by AndyAyersMS — APPROVED** [review]
