### PR TITLE
Fix Activity.Baggage items Order

### LINKED ISSUE #42596: No way to update or remove item in Activity.Baggage
**Problem description:**

I need to update the value of an item in `Activity.Baggage`.
Initially, I've assumed that `Activity.AddBaggage` would replace the previous value, but it adds a second item with the same key and also does it in an inconsistent way, for example following code:
```CSharp
Console.WriteLine("Version={0}", Environment.Version);

var key = "Key1";
var activity = new Activity("Test").Start();
activity.AddBaggage(key, "1");
activity.AddBaggage(key, "2");
Console.WriteLine("Current value {0}={1}", key, activity.GetBaggageItem(key));

Console.WriteLine("All baggage values:");
var index = 0;
foreach (var pair in activity.Baggage)
{
    Console.WriteLine("[{0}] => {1}={2}", index++, pair.Key, pair.Value);
}
```
When you target `netcoreapp3.1` will output:
```
Version=3.1.7
Current value Key1=2
All baggage values:
[0] => Key1=2
[1] => Key1=1
```
And for `net5.0`:
```
Version=5.0.0
Current value Key1=1
All baggage values:
[0] => Key1=1
[1] => Key1=2
```
In additional to that when you are passing `Activity` baggage as a header in web request to Kestrel, `Activity` inside server would have order reverced so value for the same key on client and server would be diffirent.

**Suggested solution**
From my point of view having two items with the same key is an incorrect state of the `Activity`, it creates confusion, lead to strange errors (since users don't expect that order is important) and also increase size or the `Baggage`(that should be kept as small as posible).

Ideally `AddBaggage` method should remove or replace previous value. 
If you want to avoid adding performance overhead to `AddBaggage` method then it would be helpful to have some option of removing value from collection, for example `RemoveBaggage(string key)`. Then users could remove old value before adding to avoid mentioned problems.

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/42596

In pre 5.0 .NET versions, when calling `Activity.AddBaggage`, will add a new Baggage item to internal linked list. The list was LIFO, which means when calling `Activity.Baggage` it will return the list in the reverse order of the added items. Also,  `Activity.AddBaggage` allow adding 2 items with same key and when calling `Activity.GetBaggageItem` to get a Baggage item value for a key which has duplication in the list, the API will return the last added item with that key. 

In 5.0, we used the internal LinkedList for other new scenarios (e.g. AddEvent) which required to have the list maintained on the order of the input. This had a side effect on `Baggage` order. The Baggage order became FIFO. Also, affected `Activity.GetBaggageItem` which made it to return the first added item with the specified input key instead of last added items. 

This is important to fix because `Baggage` is intended to be serialized over the wire across the process/machine. Looks users assumed specific order of the list even we didn't document the behavior. The change here is to ensure the old behavior to avoid breaking anyone and allow services using different version of the `System.Diagnostics.DiagnosticSource` to communicate reliably through serializing/deserializing the Baggage list.

### CODE REVIEW

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs [hunk 1]
```diff
@@ -432,7 +432,7 @@ public Activity AddBaggage(string key, string? value)
         {
             KeyValuePair<string, string?> kvp = new KeyValuePair<string, string?>(key, value);
 
-            if (_baggage != null || Interlocked.CompareExchange(ref _baggage, new LinkedList<KeyValuePair<string, string?>>(kvp), null) != null)
+            if (_baggage != null || Interlocked.CompareExchange(ref _baggage, new LinkedList<KeyValuePair<string, string?>>(kvp, reversed: true), null) != null)
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs:435]: I do think this works as written, but what would you think of creating a LinkedList.AddLast() API and invoking that here rather than storing extra state in the LinkedList? To me that would be a little bit simpler and has some minor performance benefits: 4-8 bytes less memory used in the LinkedList object and avoids adding a new conditional branch in the code path for tags, events, and baggage.

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/ActivityTests.cs [hunk 2]
```diff
@@ -99,6 +99,27 @@ public void Baggage()
             }
         }
 
+        [Fact]
+        public void TestBaggageOrderAndDuplicateKeys()
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/tests/ActivityTests.cs:103]: We should probably add a test that confirms baggage enumeration ordering is consistent (across versions) when multiple Activities in a chain have all had baggage added. Looking at the code it appears we have always maintained the order that child activity baggage is enumerated before parent activity baggage.

**Review by noahfalk — COMMENTED** [review]
Thanks @tarekgh! I suggested a small change

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs (hunk 1 above)
Comment (AndreyTretyak) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs:435]: Thank youf again for working on this. 
I'm sorry for adding even more confusion, but I don't think we should fix it like this.
Please correct me if I'm wrong, but the most common scenario during the transfer of baggage is something like this:
```CSharp
foreach (var item in baggage)
{
    activity.AddBaggage(item.Name, item.Value);
}
``` 
Here a sample of how Kestrel doing this: https://github.com/dotnet/aspnetcore/blob/c97a0020d8bab6d895bf821f6e47ee8722aa17d5/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L276

This means that with this change if before the transfer we had baggage like this
```
Key1=NewValue;Key1=OldValue
```
After transfer that would be:
```
Key1=OldValue;Key1=NewValue
```
So the result of `GetBaggageItem` will be changing on each transfer and would be totally unpredictable (Or we would need to require reversal of the baggage collection before adding that is very unintuitive)

This is what actually happening now in net core 3.1 and at lease from my point of view it's better to have a change in behavior then changes in order between transfers.

Alternatively, you could change `GetBaggageItem` method itself to return the last item with that key in the list, but that would mean fully iterating over the list each time (or making list double-linked), so I'm not sure if it worth it.

I do know how complicated is the process of exposing new public method is for your team, but in terms of our use case having something like `SetBaggageItem()` or `RemoveBaggageItem()` would solved all of the problems and it would've allowed to avoid all of the problematic cases discassed here. I don't think somebody actually want's two items with the same key (or if they do they could work with `Baggage` enumeration), but it's quite posible and easy to call `Add` twice in diffirent places or have the need to update value. 

Having the ability to update the list, you could always suggest people use it instead of `Add` when they are facing simular problems and it will prevernt inceasing baggage size when it's not needed.

Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs:435]: @AndreyTretyak This change is keeping the compatibility with the previous versions. in other word, we'll be consistent across the board. now, the callers of the Baggage APIs will have a consistent way to depend on regardless of which version of `System.Diagnostics.DiagnosticSource` package they will use. Changing the order is going to break someone else for sure. Imagine someone already working around the 3.1 behavior by storing the Baggages in the Activity object in reversed order as receive it from the deserialization. If we we change the order now, will break such guy and also add more risk breaking the scenario of using different versions of `System.Diagnostics.DiagnosticSource`. 

It is up to the consumer to handle the Baggage list as long as the order is well defined and maintained across versions. Kestrel can consume the list in reverse way if they like, you may request them to fix that.

We are open to add more APIs e.g. `SetBaggage` in the next release but for sure this will not be in 5.0.

Comment (AndreyTretyak) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs:435]: Thank you for the detailed explanation, I totally understand the need for maintaining behavior. Sorry for questioning it too much it's definitely too late for changing order, I liked new behaivour too much :)

What's needed from me in order for you to consider adding `SetBaggage` in the future versions? Should I create a separate API suggestion?

Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs:435]: > What's needed from me in order for you to consider adding SetBaggage in the future versions? Should I create a separate API suggestion?

Please log a new issue for this request and add your proposal to the description. please link the new issue to #42596 to have more context. Please follow the instructions in https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md when filing the new issue. Thanks for all your feedback. it was really super helpful.

**Comment by tarekgh** [comment]
@noahfalk I have addressed your feedback. please let me know if you have any more feedback.

**Review by noahfalk — APPROVED** [review]
LGTM
