### PR TITLE
JIT: Avoid resolving def-use conflicts by changing use registers

### LINKED ISSUE #125432: JIT: Invalid codegen with byref return
```csharp
// Generated by Fuzzlyn v3.3 on 2026-03-09 17:21:47
// Run on X64 Windows
// Seed: 1163906270042266374-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86avx512fx64,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 209.6 KiB to 3.6 KiB in 00:11:12
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class C0
{
    public Vector256<int> F0;
}

public struct S0
{
    public short F0;
    public sbyte F2;
}

public struct S1
{
    public S0 F3;
    public byte F7;
    public S0 F8;
}

public class C2
{
    public S1 F0;
    public S1 F1;
    public ushort F3;
    public S1 F5;
}

public struct S3
{
    public C0 F1;
    public short F2;
    public S3(C0 f1) : this()
    {
        F1 = f1;
    }

    public S3 M4(byte arg0, byte arg1, Vector128<uint> arg2, ref Vector<long> arg3, S4 arg4)
    {
        var vr4 = this.F2;
        var vr3 = Vector256.Create<short>(vr4);
        var vr7 = (short)0;
        var vr6 = Vector128.CreateScalar(vr7);
        var vr11 = (short)-23116;
        var vr9 = Vector128.CreateScalar(vr11);
        var vr5 = Sse2.Xor(vr6, vr9);
        var vr1 = Avx2.ShiftRightArithmetic(vr3, vr5);
        Vector256.CreateScalar(-29675);
        Program.s_rt.WriteLine("c_19", arg0);
        Program.s_rt.WriteLine("c_20", arg1);
        Program.s_rt.WriteLine("c_21", arg2);
        Program.s_rt.WriteLine("c_22", arg3);
        return this;
    }
}

public struct S4
{
    public uint F1;
    public long F4;
    public short F5;
    public S4(uint f1, short f2, long f4, short f5, sbyte f7) : this()
    {
        F1 = f1;
        F4 = f4;
        F5 = f5;
    }
}

public class Program
{
    public static IRuntime s_rt;
    public static uint s_2;
    public static S1 s_6;
    public static Vector<long>[] s_9 = new Vector<long>[]
    {
        Vector128.CreateScalar(0L).AsVector()
    };
    public static S3 s_10;
    public static C2[] s_18 = new C2[]
    {
        new C2()
    };
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[] { System.Activator.CreateInstance(runtimeTy) });
    }

    public static void MainInner(IRuntime rt)
    {
        s_rt = rt;
        var vr16 = s_18[0];
        var vr17 = M16();
        M2(vr16, vr17);
        s_rt.WriteLine("c_799", s_10.F1.F0);
    }

    public static ref S3 M16()
    {
        try
        {
            return ref s_10;
        }
        catch (System.Exception)
        {
        }

        return ref s_10;
    }

    public static void M2(C2 argThis, S3 arg0)
    {
        arg0 = new S3(new C0());
        try
        {
            M16() = arg0;
        }
        finally
        {
            argThis.F1 = s_6;
            byte vr25 = default(byte);
            var vr10 = (byte)Sse42.X64.Crc32(0, 0);
            var vr13 = Vector128.Create<uint>(s_2);
            var vr15 = new S4(argThis.F3, s_6.F3.F0++, (argThis.F3 >> argThis.F5.F7), argThis.F0.F8.F0, argThis.F0.F8.F2++);
            arg0.M4(vr25, vr10, vr13, ref s_9[0], vr15);
            argThis.F5.F8 = argThis.F0.F8;
            argThis.F0.F7 = argThis.F5.F7;
        }
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC() : base(true)
    {
    }
}
```

Bisected to 703be0833b619fab3b970175f0d391c097d1e17b

### LINKED ISSUE #125685: Test Failure: ComInterfaceGenerator.Unit.Tests and other tests
**Summary:**
  Multiple test assemblies crash with AccessViolationException under jitstressregs modes.

**Failed in (3):**
- [runtime-coreclr libraries-jitstress2-jitstressregs 20260314.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1335338)
- [runtime-coreclr libraries-jitstressregs 20260315.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1336130)
- [runtime-coreclr libraries-pgo 20260315.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1336300)

**Console Log:** [Console Log](https://helix.dot.net/api/2019-06-17/jobs/95138ad9-0bd7-4dac-bf0a-b6c370c4f1d5/workitems/ComInterfaceGenerator.Unit.Tests/console)

**Failed tests:**
```
runtime-coreclr libraries-jitstress2-jitstressregs
- net11.0-windows-Release-x64-jitstress2_jitstressregs8-Windows.10.Amd64.Open
runtime-coreclr libraries-jitstressregs
- net11.0-windows-Release-x64-jitstressregs8-Windows.10.Amd64.Open
runtime-coreclr libraries-pgo
- net11.0-windows-Release-x64-instrument_if_optimizing-Windows.10.Amd64.Open
- net11.0-windows-Release-x86-instrument_if_optimizing-Windows.10.Amd64.Open
  - ComInterfaceGenerator.Unit.Tests
  - IntrinsicsInSystemPrivateCoreLib.Tests
  - JSImportGenerator.Unit.Tests
  - LibraryImportGenerator.Unit.Tests
  - Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests
  - Microsoft.Extensions.Options.SourceGeneration.Tests
  - Microsoft.Extensions.Options.SourceGeneration.Unit.Tests
  - System.IO.Hashing.Tests
  - System.Text.Json.Tests
  - System.Text.RegularExpressions.Tests
```

**Error Message:**
```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Stack Trace:**
```
   at System.IO.Hashing.XxHashShared.MergeAccumulators(UInt64*, Byte*, UInt64)
   at System.IO.Hashing.XxHash128.GetCurrentHashAsHash128()
   at System.IO.Hashing.XxHash128.GetCurrentHashCore(System.Span`1<Byte>)
   at System.IO.Hashing.NonCryptographicHashAlgorithm.GetHashAndResetCore(System.Span`1<Byte>)
   at System.IO.Hashing.NonCryptographicHashAlgorithm.GetHashAndReset()
   at Microsoft.CodeAnalysis.Text.SourceText.<GetContentHash>g__computeContentHash|52_0()
   at Microsoft.CodeAnalysis.Host.TemporaryStorageService.WriteToTemporaryStorage(Microsoft.CodeAnalysis.Text.SourceText, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageService+<WriteToTemporaryStorageAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.Host.TemporaryStorageService+<WriteToTemporaryStorageAsync>d__13, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<WriteToTemporaryStorageAsync>d__13 ByRef)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageService.WriteToTemporaryStorageAsync(Microsoft.CodeAnalysis.Text.SourceText, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageService+<Microsoft-CodeAnalysis-Host-ITemporaryStorageServiceInternal-WriteToTemporaryStorageAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.Host.TemporaryStorageService+<Microsoft-CodeAnalysis-Host-ITemporaryStorageServiceInternal-WriteToTemporaryStorageAsync>d__11, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<Microsoft-CodeAnalysis-Host-ITemporaryStorageServiceInternal-WriteToTemporaryStorageAsync>d__11 ByRef)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageService.Microsoft.CodeAnalysis.Host.ITemporaryStorageServiceInternal.WriteToTemporaryStorageAsync(Microsoft.CodeAnalysis.Text.SourceText, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAsync>d__12, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SaveAsync>d__12 ByRef)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText.SaveAsync(Microsoft.CodeAnalysis.Text.SourceText, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAllAsync>d__28.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAllAsync>d__28, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SaveAllAsync>d__28 ByRef)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText.SaveAllAsync(Microsoft.CodeAnalysis.Collections.ImmutableSegmentedList`1<System.ValueTuple`2<RecoverableText,Microsoft.CodeAnalysis.Text.SourceText>>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Threading.AsyncBatchingWorkQueue`1+<>c__DisplayClass2_0+<<Convert>b__0>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.Threading.AsyncBatchingWorkQueue`1+<>c__DisplayClass2_0+<<Convert>b__0>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<Convert>b__0>d<System.ValueTuple`2<System.__Canon,System.__Canon>> ByRef)
   at Microsoft.CodeAnalysis.Threading.AsyncBatchingWorkQueue`1+<>c__DisplayClass2_0[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<Convert>b__0(Microsoft.CodeAnalysis.Collections.ImmutableSegmentedList`1<System.ValueTuple`2<System.__Canon,System.__Canon>>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Threading.AsyncBatchingWorkQueue`2+<ProcessNextBatchAsync>d__18[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.Threading.AsyncBatchingWorkQueue`2+<ProcessNextBatchAsync>d__18[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProcessNextBatchAsync>d__18<System.ValueTuple`2<System.__Canon,System.__Canon>,Microsoft.CodeAnalysis.Threading.VoidResult> ByRef)
   at Microsoft.CodeAnalysis.Threading.AsyncBatchingWorkQueue`2[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ProcessNextBatchAsync()
   at Microsoft.CodeAnalysis.Threading.AsyncBatchingWorkQueue`2+<<AddWork>g__ContinueAfterDelayAsync|16_1>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.ValueTuple`2[[System.Boolean, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.AsyncBatchingWorkQueue`2+<<AddWork>g__ContinueAfterDelayAsync|16_1>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=11.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(System.Threading.PortableThreadPool)
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
----- end Sun 03/15/2026 10:30:01.70 ----- exit code -1073741819 ----------------------------------------------------------
```

**Analysis:**
Multiple source generator and library test assemblies crash with a fatal AccessViolationException (AV) under jitstressregs and jitstress2-jitstressregs stress modes on Windows x64. 
The jitstressregs mode causes non-standard register allocation patterns which can expose codegen bugs manifesting as memory corruption.
>>>

### PR DESCRIPTION
**Pull request by jakobbotsch**
The only benefit is that it saves insertion of some explicit copies, but the trade off is an implicit contract between LSRA and codegen that is not very faithful. When LSRA defines in a different register than the constrained register, it believes that codegen can insert a copy and simultaneously use it from the new location, which is not true. This difference in the model has to be handled by inserting additional kill constraints during LSRA build, for example for shifts on xarch.

This PR additionally fixes a few issues uncovered while making this change:
- `GT_CATCH_ARG` codegen was straight up wrong, not properly producing its register value
- Multireg definitions cannot have their register assignment changed since that could override another defined register.

Fix #125432
Fix #125685

### CODE REVIEW

File: src/coreclr/jit/lsrabuild.cpp [hunk 1]
```diff
@@ -211,164 +211,125 @@ RefPosition* LinearScan::newRefPositionRaw(LsraLocation nodeLocation, GenTree* t
...
-            if (!useRegConflict)
-            {
-                // The use-reg may be busy at this point due to being a
-                // delay-free use from the previous location.
-                if (isRegInUse(useReg, interval->registerType))
+                if (!useRegConflict)
                 {
-                    useRegConflict = true;
+                    INDEBUG(dumpLsraAllocationEvent(LSRA_EVENT_DEFUSE_DEF_IN_FIXED_USE, interval));
+                    defRefPosition->registerAssignment = useRegAssignment;
```
[the remark this answers is not in the document]
Comment (jakobbotsch) [reply src/coreclr/jit/lsrabuild.cpp:301]: In this case we know `useRefPosition->isFisxedRegRef`, so it does not need to be cleared.

**Comment by jakobbotsch** [comment]
jitstressregs failures looks like the same that are present in main.

Rest looks like infra failures, will rerun CI.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1377857&view=ms.vss-build-web.run-extensions-tab). Some minor regressions mostly. I analyzed the arm64 ones and they happen "by chance": EH write-thru variables that cross calls are not strongly preferred into callee saves (unlike non EH-write thru variables).
Before this change, however, we would often have `x0` taken by some interval that went through the def-use conflict resolution, and that would result in some unrelated EH write-thru variable being allocated into a callee save because `x0` was taken and the next best register was a callee save.
With this change we end up with `x0` being free and LSRA then allocates some EH write-thru variable to that register. That results in now needing additional reloads after some calls.
I tried a few heuristics to solve this but I was not able to come up with something that was a win in the majority of cases.

File: src/coreclr/jit/codegenxarch.cpp [hunk 2]
```diff
@@ -4384,9 +4376,6 @@ void CodeGen::genLockedInstructions(GenTreeOp* node)
             // When value is used (it's the original value of the memory location)
             // we fallback to cmpxchg-loop idiom.
 
-            // for cmpxchg we need to keep the original value in RAX
-            assert(node->GetRegNum() == REG_RAX);
```
Comment (jakobbotsch) [inline src/coreclr/jit/codegenxarch.cpp:4388]: Nothing was stopping LSRA from changing the definition register on this node before, it just never happened because LSRA was preferring to change the user instead.

File: src/coreclr/jit/hwintrinsiccodegenxarch.cpp [hunk 3]
```diff
@@ -2546,6 +2546,9 @@ void CodeGen::genX86BaseIntrinsic(GenTreeHWIntrinsic* node, insOpts instOptions)
             // emit the DIV/IDIV instruction
             emit->emitInsBinary(ins, attr, node, op3);
 
+            assert(node->GetRegNumByIdx(0) == REG_EAX);
+            assert(node->GetRegNumByIdx(1) == REG_EDX);
```
Comment (jakobbotsch) [inline src/coreclr/jit/hwintrinsiccodegenxarch.cpp:2550]: There is a "new" invariant that LSRA does not change definition registers on multireg nodes, since that would require a parallel store that is very hard to accomplish for codegen without a temporary. E.g. in this case we could need to do `(eax, edx) = (edx, eax)`.

**Review by AndyAyersMS — APPROVED** [review]
