### PR TITLE
Fix an over-constrained use of a byte reg

### LINKED ISSUE #40963: Assertion failed 'farthestRefPhysRegRecord != nullptr'
Windows x86

https://dev.azure.com/dnceng/public/_build/results?buildId=772525&view=ms.vss-test-web.build-test-results-tab&runId=24122826&resultId=177239&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
C:\h\w\A3F40911\w\B6EE09BE\e>set COMPlus 
COMPlus_JitStress=2
COMPlus_JitStressRegs=4
COMPlus_TieredCompilation=0

C:\h\w\A3F40911\w\B6EE09BE\e>call RunTests.cmd --runtime-path C:\h\w\A3F40911\p --runtime-path C:\h\w\A3F40911\p 
----- start Sat 08/15/2020 10:18:06.49 ===============  To repro directly: ===================================================== 
pushd C:\h\w\A3F40911\w\B6EE09BE\e\
"C:\h\w\A3F40911\p\dotnet.exe" exec --runtimeconfig System.Memory.Tests.runtimeconfig.json --depsfile System.Memory.Tests.deps.json xunit.console.dll System.Memory.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\A3F40911\w\B6EE09BE\e>"C:\h\w\A3F40911\p\dotnet.exe" exec --runtimeconfig System.Memory.Tests.runtimeconfig.json --depsfile System.Memory.Tests.deps.json xunit.console.dll System.Memory.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Memory.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Memory.Tests (found 2260 of 2278 test cases)
  Starting:    System.Memory.Tests (parallel test collections = on, max threads = 2)

Assert failure(PID 3352 [0x00000d18], Thread: 6524 [0x197c]): Assertion failed 'farthestRefPhysRegRecord != nullptr' in 'System.Collections.Generic.ArraySortHelper`2[NotImcomparable,Byte][System.SpanTests.SpanTests+NotImcomparable,System.Byte]:InsertionSort(System.Span`1[NotImcomparable],System.Span`1[Byte],System.Collections.Generic.IComparer`1[NotImcomparable])' during 'LSRA build intervals' (IL size 191)

    File: F:\workspace\_work\1\s\src\coreclr\src\jit\lsra.cpp Line: 3853
    Image: C:\h\w\A3F40911\p\dotnet.exe
```

Also:
```
COMPlus_JitStress=2
COMPlus_JitStressRegs=0x80
COMPlus_TieredCompilation=0
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #40963

### CODE REVIEW

File: src/coreclr/src/jit/lsraxarch.cpp [hunk 1]
```diff
@@ -1439,6 +1445,24 @@ int LinearScan::BuildBlockStore(GenTreeBlk* blkNode)
...
+    // This is because the byteable register requirement doesn't "reserve" a specific register,
+    // and it would be possible for the incoming sources to all be occupying the byteable
+    // registers, leaving none free for the internal register.
+    // In this scenario, we will require rax to ensure that it is reserved and available.
+    // We don't expect a useCount of more than 3 for the initBlk case.
+    assert((useCount < 4) || !blkNode->OperIsInitBlkOp());
+    if (internalIsByte && (useCount >= 4))
+    {
+        noway_assert(internalIntDef != nullptr);
+        internalIntDef->registerAssignment = RBM_RAX;
```
Comment (CarolEidt) [inline src/coreclr/src/jit/lsraxarch.cpp:1462]: This is the actual fix.

File: src/coreclr/src/jit/lsraxarch.cpp [hunk 2]
```diff
@@ -1594,6 +1618,15 @@ int LinearScan::BuildPutArgStk(GenTreePutArgStk* putArgStk)
 
     srcCount = BuildOperandUses(src);
     buildInternalRegisterUses();
+
+#ifdef TARGET_X86
+    // There are only 4 byteable registers on x86. If we require a byteable internal register,
+    // we must have less than 4 sources.
+    // If we have 4 or more sources, and require a byteable internal register, we need to reserve
+    // one explicitly (see BuildBlockStore()).
+    assert(srcCount < 4);
```
Comment (CarolEidt) [inline src/coreclr/src/jit/lsraxarch.cpp:1627]: This and the other assert below are added because these are the only other semi-complex cases where we have byteable restrictions. I've convinced myself that we will never have more than 3 uses in these cases, so a simple assert is useful and sufficient (we don't need to check that we *actually* have a byteable register source).

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL
The remaining jitstressregs failures are #40607

**Review by sandreenko — APPROVED** [review]
LGTM

question: could we replace `4` with a constant defined in target.h? Can it be calculated from:
```
  #define RBM_BYTE_REGS           (RBM_EAX|RBM_ECX|RBM_EDX|RBM_EBX)
  #define RBM_NON_BYTE_REGS       (RBM_ESI|RBM_EDI)
```
?

Also, side question, could you please clarify for me why  `RBM_NON_BYTE_REGS` does not include `ESP, EBP`? It has only one use but could it be wrong?

**Comment by CarolEidt** [comment]
> could you please clarify for me why RBM_NON_BYTE_REGS does not include ESP, EBP? It has only one use but could it be wrong

I believe it's because we don't use `ESP` in the register allocator, and perhaps because `EBP` is sometimes restricted. IMO we should probably just eliminate `RBM_NON_BYTE_REGS` but I don't think it's critical.
