### PR TITLE
Fix InMemoryDirectoryInfo path resolution for '..' and relative paths

### LINKED ISSUE #99691: Microsoft.Extensions.FileSystemGlobbing.Matcher.Match does not work with the ".." pattern.
### Description

Matcher.Execute works with the ".." pattern.  Matcher.Match, however, does not.

### Reproduction Steps

```
/*
 * - C:\
 *     - Folder1
 *         - File1.txt
 *     - Folder2
 *         - File2.txt
 */

// Initialize
var rootDir = "C:/Folder1";
var fileToMatch = "C:/Folder2/File2.txt";
var matcher = new Matcher();
matcher.AddInclude("../Folder2/**");

// Test #1 - GOOD
var result = matcher.Execute(new DirectoryInfoWrapper(new DirectoryInfo(rootDir)));
Debug.Assert(result.HasMatches); // <== Good

// Test #2 - BAD
result = matcher.Match(rootDir, fileToMatch);
Debug.Assert(result.HasMatches); // <== Bad
```

### Expected behavior

Test #2 should pass.

### Actual behavior

Test #2 fails.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by svick**
Fix #99691 — `InMemoryDirectoryInfo` does not work with the `..` pattern.

## Problem

`InMemoryDirectoryInfo.GetDirectory` had two bugs:
- For `..`, it combined with `FullName` but passed the result as already-normalized, leaving `FullName` as e.g. `/Folder1/..` instead of resolving to the parent directory.
- For other relative paths, it resolved against the process CWD, ignoring `FullName` entirely.

`GetFile` had the same issue as the second case — it resolved relative paths against CWD instead of combining with `FullName`.

## Fix

Both `GetDirectory` and `GetFile` now combine the input path with `FullName` via `Path.Combine` and normalize via `Path.GetFullPath`, which properly resolves `..` segments. An `isParentPath` flag preserves `Name` as `".."` (needed by the matcher's pattern traversal), matching `DirectoryInfoWrapper`'s existing approach.

`DirectoryInfoWrapper.GetDirectory` was also simplified: the old code used `GetDirectories(name)` to look up subdirectories (returning `null` when not found), but this is inconsistent with the base class contract (`GetDirectory` should return an instance even if the directory does not exist). It now always constructs a `DirectoryInfo` via `Path.Combine`, matching the `..` branch that was already doing this.

## Tests

- Converted `FileAbstractionsTests` (`FilesAreEnumerated`, `SubFoldersAreEnumerated`, `GetDirectoryCanTakeDotDot`) from `[Fact]` to `[Theory]` with `bool useInMemory`, so each test exercises both `DirectoryInfoWrapper` and `InMemoryDirectoryInfo`.
- Added `VerifyInMemoryDirectoryInfo_ParentPatternMatches` in `FunctionalTests` — an end-to-end test that uses `Matcher` with a `../Folder2/**` pattern against `InMemoryDirectoryInfo`.
- Enhanced `DisposableFileSystem` with `useInMemory` support: when true, no files or directories are created on disk, and `GetDirectoryInfoBase()` returns an `InMemoryDirectoryInfo` populated from the recorded `CreateFile`/`CreateFiles` calls.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Abstractions/DirectoryInfoWrapper.cs [hunk 1]
```diff
@@ -66,39 +66,21 @@ public override IEnumerable<FileSystemInfoBase> EnumerateFileSystemInfos()
...
-                {
-                    return null;
-                }
-                else
-                {
-                    // This shouldn't happen. The parameter name isn't supposed to contain wild card.
-                    throw new InvalidOperationException(
-                        $"More than one sub directories are found under {_directoryInfo.FullName} with name {name}.");
-                }
-            }
```
Comment (svick) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Abstractions/DirectoryInfoWrapper.cs:98]: I have changed it so that this doesn't return `null` when the directory doesn't exist because:
 
* The documentation of `DirectoryInfoBase.GetDirectory()` says that it shouldn't return `null`.
* It's consistent with `DirectoryInfoWrapper.GetFile()`.
* No code in this repo seems to depend on this behavior.

**Review by rosebyte — APPROVED** [review]
