### PR TITLE
[wasm][debugger] Fix step behavior 

### LINKED ISSUE #49141: Blazor WASM doesn't correctly step through code when debugging
### Describe the bug
Stepping through code acts unpredictably, sometimes skipping over expressions that should be hit.

### Workaround
You can guarantee that code will stop on a given line by adding a breakpoint. Because STEP OVER acts so unpredictably, adding a breakpoint is really the only way you can guarantee that your code is going to stop on a given line.

### To Reproduce
1. Create a new Blazor WASM project
2. Add a new .NET library project to the solution
3. Add the `Foo` class to the library with the code below
4. Add a reference to the .NET library project from the WASM project
5. Update the `FetchData.razor` page with the code below.
6. Add a breakpoint in the `Bar` method of the `Foo` class on the line with `ret = 0`
7. Start debugging
8. Click on the "Fetch Data" link in the window
9. The program should break in the `Foo` class. 
10. Press F10 (or invoke the STEP OVER VS debug command)

### Expected Results
The currently executing line will progress will progress to the line with `return ret;`

### Actual Results
The debugger steps out of the function

#### Foo.cs
```csharp
using System;
using System.Linq;
using System.Collections.Generic;

namespace BlazorBugsLib
{
  public class Foo
  {
    public string Lorem { get; set; } = "Safe";
    public int Bar()
    {
      int ret;
      if (Lorem.StartsWith('S'))
        ret = 0;
      else
        ret = 1;

      return ret;
    }
  }
}
```

#### FetchData.razor
```csharp
  protected override async Task OnInitializedAsync()
  {
    Console.WriteLine(new BlazorBugsLib.Foo().Bar());
    forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("Bad URI");
  }
```

### LINKED ISSUE #49143: Watch window does not execute ToString() on objects
### Describe the bug
The watch window doesn't execute the `ToString()` method in Blazor WASM, which is valuable in debugging to inspect identifying properties of an object without having to expand it, especially when the objects are members of a collection.

### To Reproduce
1. Create a new Blazor WASM project
2. Add a new .NET library project to the solution
3. Add the `Foo` and `Something` classes to the library with the code below
4. Add a reference to the .NET library project from the WASM project
5. Update the `FetchData.razor` page with the code below.
6. Add a breakpoint in the `Bar` property
7. Start debugging
8. Click on the "Fetch Data" link in the window
9. The program should break in the `Foo` class. Open the locals Window

### Expected Results
The `What` property shows the result of `ToString` (`Name of Something`)
image
(Image shown is the locals window when the same value is viewed from a console project)

### Actual Results
The `What` property shows the name of the type (`BlazorBugsLib.Something`)
image

#### Foo.cs
```csharp
using System;

namespace BlazorBugsLib
{
  public class Foo
  {
    public string Bar => "sample-data/weather.json";
    public string Lorem { get; set; } = "Safe";
    public string Ipsum { get; set; } = "Side";
    public Something What { get; } = new Something();
  }

  public class Something
  {
    public string Name { get; set; }
    public Something() => Name = "Name of something";
    public override string ToString() => Name;
  }
}
```

#### FetchData.razor
```csharp
  protected override async Task OnInitializedAsync()
  {
    forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>(new BlazorBugsLib.Foo().Bar);
  }
```

### LINKED ISSUE #49218: Blazor WASM debugger faults when stepping through code
### Describe the bug
Stepping through code causes fault (failed assertion) in mono.

### To Reproduce
1. Create a new Blazor WASM project
2. Add a new .NET library project to the solution
3. Add the `Foo` class to the library with the code below
4. Add a reference to the .NET library project from the WASM project
5. Update the `FetchData.razor` page with the code below.
6. Add breakpoints at `FetchData.razor:42` (`Console.WriteLine...`)
7. Add `this.Bar` to the watch window.
8. Start debugging. **Wait for the debugger to attach before doing anything.**
9. Click on the "Fetch Data" link in the window
10. The program should break in the `FetchData.razor` page. Press F5 to **continue**.
11. Click on the "Home" link and then the "Fetch Data" link again
12. The program should break in the `FetchData.razor` page. Press F11 **twice** to **Step Into**.

### Expected Results
The debugger will step over the current statement

### Actual Results
The debugger becomes unusable and must be restarted.

### Comments
The problem appears to be caused by the expression `this.Bar` in the watch window: I'm unable to reproduce the error when the expression is removed.

#### Foo.cs
```csharp
using System;
using System.Linq;
using System.Collections.Generic;

namespace BlazorBugsLib
{
  public class Foo
  {
    //public string Bar => "sample-data/weather.json";
    public string Bar => Stuffs.First(x => x.Name.StartsWith('S')).Name;
    public string Lorem { get; set; } = "Safe";
    public string Ipsum { get; set; } = "Side";
    public Something What { get; } = new Something();
    public List<Something> Stuffs { get; } = Enumerable.Range(0, 10).Select(x => new Something()).ToList();

    public int Bart()
    {
      int ret;
      if (Lorem.StartsWith('S'))
        ret = 0;
      else
        ret = 1;

      return ret;
    }
  }
}
```

#### FetchData.razor
```csharp
  protected override async Task OnInitializedAsync()
  {
    Console.WriteLine(new BlazorBugsLib.Foo().Bart());
    forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("Bad URI");
  }
```

#### Output Window
```
mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
0
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorBugs2.Pages.FetchData.WeatherForecast[], BlazorBugs2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorBugs2.Pages.FetchData.WeatherForecast[], BlazorBugs2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[WeatherForecast[]](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[WeatherForecast[]](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.<ReadAsync>d__20`1[[BlazorBugs2.Pages.FetchData.WeatherForecast[], BlazorBugs2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__3`1[[BlazorBugs2.Pages.FetchData.WeatherForecast[], BlazorBugs2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__9`1[[BlazorBugs2.Pages.FetchData.WeatherForecast[], BlazorBugs2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at BlazorBugs2.Pages.FetchData.OnInitializedAsync() in C:\Users\rober\source\repos\BlazorBugs2\BlazorBugs2\Pages\FetchData.razor:line 43
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
>> mono_wasm_start_single_stepping 0
>> mono_wasm_start_single_stepping 0
: * Assertion at /__w/1/s/src/mono/mono/mini/debugger-engine.c:769, condition `<disabled>' not met

: * Assertion at /__w/1/s/src/mono/mono/mini/debugger-engine.c:769, condition `<disabled>' not met

Uncaught ExitStatusThe thread 0x2c50 has exited with code 0 (0x0).

```

### PR DESCRIPTION
**Pull request by thaystg**
The case that we would get a different behavior is when we have more than one command being executed in the same line:
`var d = TimeSpan.TryParseExact(y, @"ss\.fff", null, out var ts) && x.Contains('S');`
When we step over we stop in the same line again, then we need to step over again to go to next line.

- Creating test to test https://github.com/dotnet/runtime/issues/49142
- Fix behavior of step to be the same of what we see when debugging using debugger-libs+mono or coreclr.
- Creating test to close https://github.com/dotnet/runtime/issues/49143
- Creating test to close https://github.com/dotnet/runtime/issues/49141
- Creating test to close https://github.com/dotnet/runtime/issues/49218.
- Fix error message of evaluate calling methods.

NOTE: If we want to backport it to preview7 we also need to backport https://github.com/dotnet/runtime/pull/55869, otherwise it will break step after hotreload for wasm.

### CODE REVIEW

File: src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs [hunk 1]
```diff
@@ -653,3 +653,46 @@ internal static void ApplyUpdate (System.Reflection.Assembly assm, int version)
...
+        Console.WriteLine(foo);
+    }
+    public void OtherBar()
+    {
+        var a = 1;
+        var b = 2;
+        var x = "Stew";
+        var y = "00.123";
+        var c = a + b == 3 || b + a == 2;
+        var d = TimeSpan.TryParseExact(y, @"ss\.fff", null, out var ts) && x.Contains('S');
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:694]: Should we also test async cases for this? like given `Task<bool> FooAsync() { ..}`:

`x.Contains('S') && await FooAsync()`, `await BarAsync() && await FooAsync()`?

And would it work fine with a new line before/after `&&`?

Comment (thaystg) [reply src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:694]: It works fine with a new line before/after `&&`.
I'll add a test with await.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 2]
```diff
@@ -897,7 +897,7 @@ public async Task<bool> Step(SessionId sessionId, int thread_id, StepKind kind,
             commandParamsWriter.Write((byte)1);
             commandParamsWriter.Write((byte)ModifierKind.Step);
             commandParamsWriter.Write(thread_id);
-            commandParamsWriter.Write((int)0);
+            commandParamsWriter.Write((int)1);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:900]: What does 0, and 1 here mean? named consts might be helpful.

File: src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs [hunk 3]
```diff
@@ -862,5 +862,54 @@ public async Task BreakpointOnHiddenLineOfMethodWithNoNextVisibleLineShouldNotPa
             Task t = await Task.WhenAny(pause_task, Task.Delay(2000));
             Assert.True(t != pause_task, "Debugger unexpectedly paused");
         }
+
+        [Fact]
+        public async Task SimpleStepTest()
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:867]: What is this test for?

Comment (thaystg) [reply src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:867]: Trying to make sure that this issue is already fixed:
https://github.com/dotnet/runtime/issues/49141

Comment (radical) [reply src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:867]: Rename it to something like `SimpleStep_RegressionTest_49141`.

File: src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs [hunk 4]
```diff
@@ -862,5 +862,54 @@ public async Task BreakpointOnHiddenLineOfMethodWithNoNextVisibleLineShouldNotPa
...
+            await EvaluateAndCheck(
+                expression,
+                "dotnet://debugger-test.dll/debugger-test.cs", 674, 12,
+                "Bart");
+            await StepAndCheck(StepKind.Over, "dotnet://debugger-test.dll/debugger-test.cs", 677, 8, "Bart");
+            await StepAndCheck(StepKind.Over, "dotnet://debugger-test.dll/debugger-test.cs", 678, 4, "Bart");
+        }
+
+        [Fact]
+        public async Task StepAndEvaluate()
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:881]: nit:
```suggestion
        public async Task StepAndEvaluateExpression()
```

File: src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs [hunk 5]
```diff
@@ -862,5 +862,54 @@ public async Task BreakpointOnHiddenLineOfMethodWithNoNextVisibleLineShouldNotPa
...
+        {
+            await SetBreakpoint("dotnet://debugger-test.dll/debugger-test.cs", 682, 0);
+
+            string expression = "window.setTimeout(function() { invoke_static_method ('[debugger-test] Foo:RunBart'); }, 1);";
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:885]: super nit: rename the variable to something else, or move the string to line 887. Just to avoid confusing it with the expression being evaluated in this test.

File: src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs [hunk 6]
```diff
@@ -862,5 +862,54 @@ public async Task BreakpointOnHiddenLineOfMethodWithNoNextVisibleLineShouldNotPa
...
+            var pause_location = await StepAndCheck(StepKind.Into, "dotnet://debugger-test.dll/debugger-test.cs", 671, 4, "Bart");
+            var id = pause_location["callFrames"][0]["callFrameId"].Value<string>();
+            await EvaluateOnCallFrameAndCheck(id, ("this.Bar", TString("Same of something")));
+            pause_location = await StepAndCheck(StepKind.Into, "dotnet://debugger-test.dll/debugger-test.cs", 673, 8, "Bart");
+            id = pause_location["callFrames"][0]["callFrameId"].Value<string>();
+            await EvaluateOnCallFrameAndCheck(id, ("this.Bar", TString("Same of something")));
+        }
+
+        [Fact]
+        public async Task StepOverWithMoreThanOneCommandInSameLine()
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:899]: Do we need a test for a stepping over the last line of a method like:
```csharp
bool foo()
{
  ...
  return a() && b == 123;
}
```

File: src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs (hunk 3 above)
Comment (thaystg) [reply src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs]: done.

File: src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs (hunk 4 above)
Comment (thaystg) [reply src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs]: changed.

File: src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs (hunk 5 above)
Comment (thaystg) [reply src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs]: done.

File: src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs (hunk 6 above)
Comment (thaystg) [reply src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:898]: added to the test.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 2 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: It's the size of the step, before we were using `minimal` and debugger-libs uses `line`

File: src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs (hunk 1 above)
Comment (thaystg) [reply src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:694]: Added a test with async.

**Review by radical — APPROVED** [review]
