### PR TITLE
Fix gc.cpp compilation with BACKGROUND_GC disabled

### LINKED ISSUE #56186: GC does not compile when BACKGROUND_GC is not defined.
It would be nice to at least make it compiles.

### PR DESCRIPTION
**Pull request by cshung**
Fixes https://github.com/dotnet/runtime/issues/56186.
Part of https://github.com/dotnet/runtime/issues/58120

### CODE REVIEW

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -24,6 +24,14 @@
 #define USE_INTROSORT
 #endif
 
+#ifdef DACCESS_COMPILE
+#error this source file should not be compiled with DACCESS_COMPILE!
+#endif //DACCESS_COMPILE
+
+#if defined(DOUBLY_LINKED_FL) && !defined(BACKGROUND_GC)
+#error DOUBLY_LINKED_FL should only be used with BACKGROUND_GC
+#endif //DACCESS_COMPILE
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:33]: I don't think we need this - you are already explicitly only defining DOUBLY_LINKED_FL when BACKGROUND_GC is defined in gcpriv.h. checks like this are only for things that may be defined by things outside the GC, eg, DACCESS_COMPILE.

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -8519,10 +8523,12 @@ void gc_heap::get_card_table_element_sizes (uint8_t* start, uint8_t* end, size_t
     }
 #endif //CARD_BUNDLE
 #ifdef FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP
+#ifdef BACKGROUND_GC
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:8526]: should be combined -

`#if defined(FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP) && defined (BACKGROUND_GC)`

File: src/coreclr/gc/gc.cpp [hunk 3]
```diff
@@ -9210,6 +9221,7 @@ void gc_heap::copy_brick_card_range (uint8_t* la, uint32_t* old_card_table,
             assert (old_brick_table == 0);
         }
     }
+#endif
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:9224]: nit -

`#endif //BACKGROUND_GC`

File: src/coreclr/gc/gc.cpp [hunk 4]
```diff
@@ -9349,7 +9361,10 @@ BOOL gc_heap::insert_ro_segment (heap_segment* seg)
     enter_spin_lock (&gc_heap::gc_lock);
 
     if (!gc_heap::seg_table->ensure_space_for_insert ()
-        || (is_bgc_in_progress() && !commit_mark_array_new_seg(__this, seg)))
+#ifdef BACKGROUND_GC
+        || (is_bgc_in_progress() && !commit_mark_array_new_seg(__this, seg))
+#endif
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:9366]: nit -

`#endif //BACKGROUND_GC`

Comment (Maoni0) [reply src/coreclr/gc/gc.cpp:9366]: same with below

File: src/coreclr/gc/gc.cpp [hunk 5]
```diff
@@ -12484,12 +12502,14 @@ void gc_heap::reset_write_watch (BOOL concurrent_p)
...
+#ifdef BACKGROUND_GC
             base_address = max (base_address, background_saved_lowest_address);
-
+#endif
             uint8_t* high_address = ((seg == ephemeral_heap_segment) ? 
                 alloc_allocated : heap_segment_allocated (seg));
+#ifdef BACKGROUND_GC
             high_address = min (high_address, background_saved_highest_address);
-
+#endif
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:12512]: the following methods should only be defined when BACKGROUND_GC is defined -

```cplusplus
    PER_HEAP_ISOLATED
    void reset_write_watch_for_gc_heap(void* base_address, size_t region_size);
    PER_HEAP_ISOLATED
    void get_write_watch_for_gc_heap(bool reset, void *base_address, size_t region_size, void** dirty_pages, uintptr_t* dirty_page_count_ref, bool is_runtime_suspended);

    PER_HEAP
    void switch_one_quantum();
    PER_HEAP
    void reset_ww_by_chunk (uint8_t* start_address, size_t total_reset_size);
    PER_HEAP
    void switch_on_reset (BOOL concurrent_p, size_t* current_total_reset_size, size_t last_reset_size);
    PER_HEAP
    void reset_write_watch (BOOL concurrent_p);
```

File: src/coreclr/gc/gc.cpp [hunk 6]
```diff
@@ -18001,6 +18023,7 @@ uint8_t* gc_heap::allocate_in_older_generation (generation* gen, size_t size,
                             dprintf (3333, ("SFA: %Ix->%Ix(%d)", free_list, (free_list + free_list_size),
                                 (generation_set_bgc_mark_bit_p (gen) ? 1 : 0)));
                         }
+
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:18026]: random empty line was added here...

File: src/coreclr/gc/gc.cpp [hunk 7]
```diff
@@ -18236,7 +18258,6 @@ uint8_t* gc_heap::allocate_in_older_generation (generation* gen, size_t size,
 
                 set_plug_bgc_mark_bit (old_loc);
             }
-
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:18239]: empty line was randomly removed here

**Review by Maoni0 — CHANGES_REQUESTED** [review]
the rest LGTM

**Review by Maoni0 — APPROVED** [review]
the rest LGTM
