### PR TITLE
For arm32, kill REG_PROFILER_RET_SCRATCH for LSRA but not for GC

### LINKED ISSUE #37223: Assertion failed 'nonVarPtrRegs == RBM_NONE'
Failure in libraries System.Threading.Tasks.Dataflow.Tests: release libraries, checked coreclr with:

```
COMPlus_TieredCompilation=0
COMPlus_JitStress=2
COMPlus_JitStressRegs=4
```

Windows arm32

E.g.,
```
build -s libs+libs.tests -runtimeConfiguration checked -c Release -arch arm /p:ArchiveTests=true
```

(the `/p:ArchiveTests=true` is required to build the RunTests.cmd wrapper scripts)

```
c:\bugs\System.Threading.Tasks.Dataflow.Tests\net5.0-Release>call .\RunTests.cmd -r C:\bugs\testhost\net5.0-Windows_NT-Release-arm
----- start Sun 05/31/2020 13:04:02.26 ===============  To repro directly: =====================================================
pushd c:\bugs\System.Threading.Tasks.Dataflow.Tests\net5.0-Release\
"C:\bugs\testhost\net5.0-Windows_NT-Release-arm\dotnet.exe" exec --runtimeconfig System.Threading.Tasks.Dataflow.Tests.runtimeconfig.json --depsfile System.Threading.Tasks.Dataflow.Tests.deps.json xunit.console.dll System.Threading.Tasks.Dataflow.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

c:\bugs\System.Threading.Tasks.Dataflow.Tests\net5.0-Release>"C:\bugs\testhost\net5.0-Windows_NT-Release-arm\dotnet.exe" exec --runtimeconfig System.Threading.Tasks.Dataflow.Tests.runtimeconfig.json --depsfile System.Threading.Tasks.Dataflow.Tests.deps.json xunit.console.dll System.Threading.Tasks.Dataflow.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
  Discovering: System.Threading.Tasks.Dataflow.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tasks.Dataflow.Tests (found 290 of 297 test cases)
  Starting:    System.Threading.Tasks.Dataflow.Tests (parallel test collections = on, max threads = 8)
Regset after BB27 gcr=0001 {r0}, byr=0000 {}, regVars=0004 {r2}

Assert failure(PID 12028 [0x00002efc], Thread: 6680 [0x1a18]): Assertion failed 'nonVarPtrRegs == RBM_NONE' in 'System.Collections.Generic.Dictionary`2[Int64,KeyValuePair`2][System.Int64,System.Collections.Generic.KeyValuePair`2[System.Boolean,System.__Canon]]:Remove(long):bool:this' during 'Generate code' (IL size 356)

    File: C:\gh\runtime\src\coreclr\src\jit\codegenlinear.cpp Line: 509
    Image: C:\bugs\testhost\net5.0-Windows_NT-Release-arm\dotnet.exe

----- end Sun 05/31/2020 13:04:13.92 ----- exit code -1073740286 ----------------------------------------------------------
```

category:correctness
theme:elt-hooks
skill-level:intermediate
cost:medium

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Reworking of #37969. Block LSRA from using R2 around the profiler leave
callback, but don't kill GC refs in R2, since late codegen will use
R2 to temporarily hold return values around the callback.

Fixes #37223.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@CarolEidt PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Added in the gcstress-extra tests.

File: src/coreclr/src/jit/emit.cpp [hunk 1]
```diff
@@ -7692,7 +7692,12 @@ regMaskTP emitter::emitGetGCRegsKilledByNoGCCall(CorInfoHelpFunc helper)
             break;
 
         case CORINFO_HELP_PROF_FCN_LEAVE:
+#if defined(TARGET_ARM)
+            // profiler scratch remains gc live
+            result = RBM_PROFILER_LEAVE_TRASH & ~RBM_PROFILER_RET_SCRATCH;
+#else
```
Comment (echesakovMSFT) [inline src/coreclr/src/jit/emit.cpp:7698]: Can you please explain why this is only needed for `TARGET_ARM` and not other architectures?

Comment (AndyAyersMS) [reply src/coreclr/src/jit/emit.cpp:7698]: Arm is the only target that does this sort of return value sheltering in jitted code around the profiler leave hook.

No other architecture defines `RBM_PROFILER_RET_SCRATCH`.

**Comment by AndyAyersMS** [comment]
Added libraries jitstress test.

**Comment by AndyAyersMS** [comment]
Failure rates in gcstress-extra and libraries-jitstress seem similar to recent numbers.  All are gc stress crashes or (in one case) an incorrect result. No recurrence of #37223.

File: src/coreclr/src/jit/lsraarm.cpp [hunk 2]
```diff
@@ -491,6 +491,8 @@ int LinearScan::BuildNode(GenTree* tree)
 
         case GT_RETURN:
             srcCount = BuildReturn(tree);
+            killMask = getKillSetForReturn();
+            BuildDefsWithKills(tree, 0, RBM_NONE, killMask);
```
Comment (CarolEidt) [inline src/coreclr/src/jit/lsraarm.cpp:495]: I am OK with this fix as-is, but I think another option that might be slightly cleaner would be to replace the above 3 lines with:
```
            buildInternalIntRegisterDefForNode(tree, RBM_PROFILER_ENTER_TRASH);
            srcCount = BuildReturn(tree);
            buildInternalRegisterUses();
```
Then target.h and emit.cpp could, I believe, remain unchanged. This basically says to the register allocator: "I need an extra register and it must be r2", which will cause it to ensure that r2 is free at the return. However, I haven't tested this approach. Note that normally I wouldn't do this separately (outside of an existing `BuildXXX` method), but in this case `BuildReturn()` is shared across platforms and already complex.

Comment (AndyAyersMS) [reply src/coreclr/src/jit/lsraarm.cpp:495]: Yeah, I mentioned trying something like that [over in the issue](https://github.com/dotnet/runtime/issues/37223#issuecomment-666012530) but wasn't sure how to pull it off.

Seems like the cleanest solution would be to inject these calls early and handle them like any other call.

Not sure how to proceed -- if you're ok with this fix then approve? Else I can try the above.

Comment (CarolEidt) [reply src/coreclr/src/jit/lsraarm.cpp:495]: I'll approve; not sure it's worth iterating on.

**Review by CarolEidt — APPROVED** [review]
Thanks for all your work on this!
