### PR TITLE
Fix GC handle dac bug

### LINKED ISSUE #124872: GC handle enumeration bug
In the DAC we assume that there are as many handle tables per handle table bucket as heaps. However, during server GC the number of handle tables is equal to the number of processors, which may not match the number of heaps (for example with DATAS on). This leads to incomplete enumeration in the DAC (and cDAC). 

https://github.com/dotnet/runtime/blob/0fe50ea7068fecf3d9170a27d49a215a7fc2f4d4/src/coreclr/debug/daccess/daccess.cpp#L7542
https://github.com/dotnet/runtime/blob/0fe50ea7068fecf3d9170a27d49a215a7fc2f4d4/src/coreclr/gc/objecthandle.cpp#L789

Found in #124760

### PR DESCRIPTION
**Pull request by rcj1**
Ensure full enumeration of GC handles when multiple heaps are present. Fixes https://github.com/dotnet/runtime/issues/124872

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]

File: src/coreclr/debug/daccess/daccess.cpp [hunk 1]
```diff
@@ -7523,11 +7523,11 @@ void DacHandleWalker::WalkHandles()
     mEnumerated = true;
 
     // The table slots are based on the number of GC heaps in the process.
-    int max_slots = 1;
+    uint32_t max_slots = 1;
 
 #ifdef FEATURE_SVR_GC
     if (GCHeapUtilities::IsServerHeap())
-        max_slots = GCHeapCount();
+        max_slots = *g_gcDacGlobals->g_totalCpuCount;
```
Comment (hoyosjs) [inline src/coreclr/debug/daccess/daccess.cpp]: That being said - this feels brittle in the sense it's hardcoding policy again (the same thing that drifted here). There's not much to do here in the legacy dac I think - but adding a comment to getnumofslots pointing to the DAC use of the algorithm would be a good thing to do.

File: src/coreclr/debug/daccess/daccess.cpp [hunk 2]
```diff
@@ -7522,12 +7522,18 @@ void DacHandleWalker::WalkHandles()
 
     mEnumerated = true;
 
-    // The table slots are based on the number of GC heaps in the process.
-    int max_slots = 1;
+    // The table slots are based on the number of GC heaps in the process for GC interface version < 8.
+    // This is a bug, and the correct implementation is based on the number of processors starting at GC interface version 8.
```
Comment (noahfalk) [inline src/coreclr/debug/daccess/daccess.cpp]: Just reading the comment alone, its not clear what behavior it is refering to as "this is a bug". Perhaps:


```
    // The GC sets the number of slots based on the number of processors. Prior to
    // DATAS, num_processors == GCHeapCount() for ServerGC. Unfortunately the GC DAC
    // contract didn't record the number of processors independently until minor
    // version 8 and DATAS was enabled prior to that. When using a standalone GC version
    // < 8 the DAC approximates the processor count as GCHeapCount() because we don't
    // have more accurate data to work with. This may cause handle enumeration to be
    // incomplete.
```

File: src/coreclr/debug/daccess/daccess.cpp [hunk 3]
```diff
@@ -7522,12 +7522,18 @@ void DacHandleWalker::WalkHandles()
...
+    uint32_t max_slots = 1;
 
 #ifdef FEATURE_SVR_GC
     if (GCHeapUtilities::IsServerHeap())
-        max_slots = GCHeapCount();
+    {
+        if (g_gcDacGlobals->minor_version_number >= 8)
```
Comment (noahfalk) [inline src/coreclr/debug/daccess/daccess.cpp]: Is this ever true? It looks like we are only at 6 right now.

File: src/coreclr/gc/gcinterface.h [hunk 4]
```diff
@@ -11,7 +11,7 @@
 // The minor version of the IGCHeap interface. Non-breaking changes are required
 // to bump the minor version number. GCs and EEs with minor version number
 // mismatches can still interoperate correctly, with some care.
-#define GC_INTERFACE_MINOR_VERSION 6
+#define GC_INTERFACE_MINOR_VERSION 8
```
Comment (noahfalk) [inline src/coreclr/gc/gcinterface.h:14]: Is there a reason we are skipping 7?

**Review by noahfalk — APPROVED** [review]

File: src/coreclr/gc/gcinterface.h (hunk 4 above)
Comment (hoyosjs) [reply src/coreclr/gc/gcinterface.h:14]: Historically, see `IsRegionGCEnabled` and `IsBackgroundGCEnabled` (this probably should have a comment). If we someone loads a local GC versioned less than 2.4, then the minor gets interpreted as a bitfield... That being said, we reject anything lower than our major and we are already at 5, so this is not interesting anymore.

**Review by hoyosjs — APPROVED** [review]
