### PR TITLE
Fix watson buckets setting race condition

### LINKED ISSUE #45929: AccessViolationException 0xc0000005 in CopyWatsonBucketsBetweenThrowables / coreclr.dll
### Description

A Windows service running in production environment crashes periodically (once-twice a week) with AVs as seen below:

```
Faulting application name: XXXXX.exe, version: 0.0.0.0, time stamp: 0x5f6b3998
Faulting module name: coreclr.dll, version: 4.700.20.47201, time stamp: 0x5f6a7a28
Exception code: 0xc0000005
Fault offset: 0x0000000000232e2b
```
WinDbg:  the point of failure in FW 3.1 is this [line](https://github.com/dotnet/coreclr/blob/release/3.1/src/vm/excep.cpp#L10309):

> PTR_VOID pRawSourceWatsonBucketArray = dac_cast<PTR_VOID>(refSourceWatsonBucketArray->GetDataPtr());

### Configuration

- .NET Core 3.1 (coreclr 4.700.20.47201 and 4.700.20.36602)
- Windows 2016 DataCenter Server x64
- 64 vCPUs, 400 GB of RAM 

### Regression?

On a first sight this started **immediately** after the upgrade to v3.1.7 (dotnet-sdk-3.1.401-win-x64) (coreclr.dll 4.700.20.36602) on August 30 (fault offset 0x0000000000232e1b).

#### Update 1

We found 5 more crashes in our logs going back to beginning of 2020 (although not as frequent as it happens now):
- 3 crashes on coreclr 4.700.20.6602
- 2 crashes on coreclr 4.700.20.20201
 
#### Update 2

Jan 23 2019: a similar exception handing failure: 

```
Faulting application name: XXXXX.exe, version: 0.0.0.0, time stamp: 0x5c007e95
Faulting module name: coreclr.dll, version: 4.6.27129.4, time stamp: 0x5c00327e
Exception code: 0xc0000005
Fault offset: 0x00000000001a3b8d
```

WinDbg > [e:\a\_work\104\s\src\vm\exceptionhandling.cpp @ 1029] (00000001`800379e0)   coreclr!ProcessCLRException+0x16c1ad   |  (00000001`80037e00)   coreclr!ExceptionTracker::ProcessOSExceptionNotification

### Other information

The crash dump attached in Visual Studio:

image

There is  a normal .NET exception ends up in the crash at excep.cpp#L10309. 

Outer exception: 
- {"Exception has been thrown by the target of an invocation."} System.Reflection.TargetInvocationException
- SerializationWatsonBuckets: null

InnerException 
- {"InitializingException: Initializing"} System.Exception {InitializingException}
-  SerializationWatsonBuckets {byte[5616]}

Note that the application is in startup mode and there are quite a few of these `Initializing`(s) flying around, increasing the possibility of the bug to present itself (if there is one). Indeed, the crash is more likely to happen during the takeoff than during the cruising phase of the process lifetime.

Looking around a bit I noticed that the method that hits the null ref is not supposed to run unless `AreWatsonBucketsPresent` returns true. Could it be a race condition?

Please advice if upgrading to FW 5.0 or moving to another OS could help with the issue short term.

I will provide more details as necessary. 

Thank you.

FYI @karelz

### PR DESCRIPTION
**Pull request by janvorli**
The code that updates watson buckets in an exception from its inner
exception has a race that can cause runtime crashes when many threads
are rethrowing the same exception using ExceptionDispatchInfo.Throw.
At several places, we check if the inner exception contains watson
buckets and if that is true, we copy them to the outer exception.
However, the ExceptionDispatchInfo.Throw on another thread can reset
the buckets to the captured value, which might be null. So the
copying then crashes with access violation.

This change fixes the issue by reading the buckets reference once and
then performing the checks / copying using that extracted value.

It also adds a regression test that asserts quickly in debug / checked
builds.

Close #45929

### CODE REVIEW

File: src/tests/Regressions/coreclr/GitHub_45929/test45929.cs [hunk 1]
```diff
@@ -0,0 +1,124 @@
+using System;
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_45929/test45929.cs:1]: Nit: License header

File: src/coreclr/vm/object.h [hunk 2]
```diff
@@ -2481,7 +2481,8 @@ class ExceptionObject : public Object
     U1ARRAYREF GetWatsonBucketReference()
     {
         LIMITED_METHOD_CONTRACT;
-        return _watsonBuckets;
+        PTR_U1Array buckets = (PTR_U1Array)OBJECTREFToObject(_watsonBuckets);
```
Comment (jkotas) [inline src/coreclr/vm/object.h:2484]: Why is this change needed?

File: src/coreclr/vm/excep.cpp [hunk 3]
```diff
@@ -10550,17 +10560,24 @@ void SetStateForWatsonBucketing(BOOL fIsRethrownException, OBJECTHANDLE ohOrigin
...
+                }
+                else
+                {
+                    gotWatsonBucketDetails = false;
                 }
             }
 
+            if (gotWatsonBucketDetails)
+            {
             // Set the flag that we got bucketing details for the exception
```
Comment (jkotas) [inline src/coreclr/vm/excep.cpp:10576]: Indentation looks off

File: src/coreclr/vm/object.h (hunk 2 above)
Comment (janvorli) [reply src/coreclr/vm/object.h:2484]: The problem is that the underlying REF<U1Array> constructor that is called to create the return value calls validation on the _watsonBuckets this way:
```c++
do {if ((objref) != NULL) (objref).Validate();} while (0)
```
During the race, the condition is true, but another thread sets the buckets to NULL right after the check, so the (objref).Validate() crashes. This change prevents that by extracting the object and then constructing the returned value on that.

File: src/tests/Regressions/coreclr/GitHub_45929/test45929.cs (hunk 1 above)
Comment (janvorli) [reply src/tests/Regressions/coreclr/GitHub_45929/test45929.cs:1]: Oops, all of my recent regression tests are missing licence header. I'll fix them.

File: src/coreclr/vm/object.h (hunk 2 above)
Comment (jkotas) [reply src/coreclr/vm/object.h:2484]: It may be better to fix the validation to avoid this race condition. I suspect a bunch of places throughout the code have the same problem.

Comment (janvorli) [reply src/coreclr/vm/object.h:2484]: Sounds reasonable. I'll give it a try.

File: src/coreclr/vm/vars.hpp [hunk 4]
```diff
@@ -298,15 +298,15 @@ class REF : public OBJECTREF
...
-#define VALIDATEOBJECT(obj) do {if ((obj) != NULL) (obj)->Validate();} while (0)
-
 #define ObjectToOBJECTREF(obj)     (OBJECTREF(obj))
 #define OBJECTREFToObject(objref)  ((objref).operator-> ())
 #define ObjectToSTRINGREF(obj)     (STRINGREF(obj))
 #define STRINGREFToObject(objref)  (*( (StringObject**) &(objref) ))
 
+// the while (0) syntax below is to force a trailing semicolon on users of the macro
+#define VALIDATEOBJECT(obj) do {if ((obj) != NULL) (obj)->Validate();} while (0)
+#define VALIDATEOBJECTREF(objref) do { VALIDATEOBJECT(OBJECTREFToObject(objref)); } while (0)
```
Comment (jkotas) [inline src/coreclr/vm/vars.hpp:308]: How is this fixing the race condition? I would expect to see a temporary local variable or something like that as part of the fix.

Comment (janvorli) [reply src/coreclr/vm/vars.hpp:308]: Sigh, you are right, I have somehow forgotten that this is a macro and not a function call and so the OBJECTREFToObject(objref) will get propagated into the other macro as is.

**Review by jkotas — APPROVED** [review]
