### PR TITLE
[wasm] Improved error handling in debug proxy

### LINKED ISSUE #65744: [wasm][debugger] Assertion in `DebuggerTests.EvaluateOnCallFrameTests.EvaluateSimpleMethodCallsError`
Running this test on linux:

```
console.error: * Assertion at /workspaces/runtime/src/mono/mono/metadata/class-accessors.c:71, condition `<disabled>' not met
```

```c
mono_class_get_flags (MonoClass *klass)
{
        g_assert (klass);
```

### PR DESCRIPTION
**Pull request by radical**
- improved surfacing of errors from expression evaluation, which leads to more useful error messages
- `SendDebuggerAgentCommand` will now throw if the result is an error. Earlier, the returned reader was rarely checked. This should help to find issues more readily.
- All this should provide better error messages, and logging. And remove instances of cryptic `Unable to evaluate` errors.
- Also, tests will now fail on any error/warning raised by the runtime
  - this helped to catch a couple of new issues

Fixes https://github.com/dotnet/runtime/issues/65744

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/ValueOrError.cs [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+using System;
+
+namespace Microsoft.WebAssembly.Diagnostics;
+
+public struct ValueOrError<TValue>
+{
+    public TValue? Value { get; init; }
+    public Result? Error { get; init; }
+
+    public bool HasValue => Value != null;
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/BrowserDebugProxy/ValueOrError.cs:15]: If the name includes *or* then can we please change to IsError and IsValue so that it will be clear that it cannot have both? Without the need to check what is in the constructor ;)

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 2]
```diff
@@ -606,7 +604,7 @@ async Task EvaluateOnCallFrameFail(string call_frame_id, params (string expressi
                    ("f.textList[j]", TString("2")),
                    ("f.numArray[j]", TNumber(2)),
                    ("f.textArray[i]", TString("1")));
-                
+
```
Comment (ilonatommy) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:607]: There are some accidentally added blank lines here.

Comment (radical) [reply src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:607]: These are existing lines blank lines, that had trailing spaces. So, the diff makes them true blank lines :)

**Review by ilonatommy — APPROVED** [review]

**Comment by radical** [comment]
We should try to merge this. It has some useful fixes.

**Review by lewing — APPROVED** [review]
