### PR TITLE
corehost: derive fallback rid from output rid.

### LINKED ISSUE #81654: Fallback host rid is broken on non-portable builds
Microsoft's portable builds perform a fall-back to the portable rid when the `/etc/os-release/` rid is not known.

This doesn't work for non-portable builds because the information for the portable rid is missing in `Microsoft.NETCore.App.deps.json`.

For example, below is the full `runtimes` section of a Fedora 37 build. It does not include a section for `linux-x64` (which is the fallback host rid).

```json
  "runtimes": {
    "fedora.37-x64": [
      "fedora.37",
      "fedora-x64",
      "fedora",
      "linux-x64",
      "linux",
      "unix-x64",
      "unix",
      "any",
      "base"
    ]
```

For source-build, there _should_ be an exact match with the rid found here and the `/etc/os-release` rid.
That may not be the case:
- Because the `/etc/os-release` rid is unexpected (like in https://github.com/dotnet/runtime/issues/79196).
- It also happens when a distro gets upgraded, and the new version does not (yet) include packages for that .NET version. Then the existing .NET build will not know the new rid (`fedora.38-x64` is unknown).

In these two cases, the Microsoft build will continue to work, while the source-build builds start failing.

We should include this information in the non-portable builds so the fallback works.

cc @ViktorHofer @ericstj @am11 @omajid

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/runtime/issues/81654.

This is a start. It handles non-portable non-Windows.

I wonder if we need a separate path to handle portable, or if this should work as-is.

I need some help with updating the Windows scripts. I can figure some things out by copy-pasting, but I don't know how to strip the architecture from the `__OutputRid`.

@vitek-karas @elinor-fung @ViktorHofer @am11 ptal.

### CODE REVIEW

File: src/coreclr/build-runtime.sh [hunk 1]
```diff
@@ -145,8 +145,11 @@ export MSBUILDDEBUGPATH
 # Check prereqs.
 check_prereqs
 
+# When the host runs on an unknown rid, it falls back to the output rid
+__FallbackOS="${__OutputRid%-*}" # Strip architecture
```
Comment (am11) [inline src/coreclr/build-runtime.sh:149]: nit: move this assignment after https://github.com/dotnet/runtime/blob/3a3692029a2a038581fdc8c1c6496e0506a7e0c7/eng/native/build-commons.sh#L492 and then we won't need to repeat this logic in other scripts.

**Comment by am11** [comment]
> I need some help with updating the Windows scripts. I can figure some things out by copy-pasting, but I don't know how to strip the architecture from the `__OutputRid`.

```cmd
:: batch script - test.cmd

set __OutputRid=win10-arm64

for /f "delims=-" %%i in ("%__OutputRid%") do set __FallbackOS=%%i

echo %__FallbackOS%
```

outputs: `win10`

File: src/coreclr/build-runtime.cmd [hunk 2]
```diff
@@ -355,7 +357,12 @@ if %__BuildNative% EQU 1 (
         set __ExtraCmakeArgs="-DCMAKE_BUILD_TYPE=!__BuildType!"
     )
 
-    set __ExtraCmakeArgs=!__ExtraCmakeArgs! "-DCLR_CMAKE_TARGET_ARCH=%__TargetArch%" "-DCLR_CMAKE_TARGET_OS=%__TargetOS%" "-DCLR_CMAKE_PGO_INSTRUMENT=%__PgoInstrument%" "-DCLR_CMAKE_OPTDATA_PATH=%__PgoOptDataPath%" "-DCLR_CMAKE_PGO_OPTIMIZE=%__PgoOptimize%" %__CMakeArgs%
+    :: When the host runs on an unknown rid, it falls back to the output rid
+    :: Strip the architecture
+    for /f "delims=-" %%i in ("%__OutputRid%") do set __FallbackOS=%%i
+    if "%__FallbackOS%" == "" set __FallbackOS=win10
+
+    set __ExtraCmakeArgs=!__ExtraCmakeArgs! "-DCLR_CMAKE_TARGET_ARCH=%__TargetArch%" "-DCLR_CMAKE_TARGET_OS=%__TargetOS%" "-DCLI_CMAKE_FALLBACK_RID=%__FallbackOS%" "-DCLR_CMAKE_PGO_INSTRUMENT=%__PgoInstrument%" "-DCLR_CMAKE_OPTDATA_PATH=%__PgoOptDataPath%" "-DCLR_CMAKE_PGO_OPTIMIZE=%__PgoOptimize%" %__CMakeArgs%
```
Comment (tmds) [inline src/coreclr/build-runtime.cmd:365]: This what shows up in the Windows build log:

> Calling "D:\a\_work\1\s\eng\native\gen-buildsys.cmd" "D:\a\_work\1\s\src\coreclr" "D:\a\_work\1\s\artifacts\obj\coreclr\windows.x86.Checked" vs2022 x86 windows "-DCMAKE_BUILD_TYPE=Checked" "-DCLR_CMAKE_TARGET_ARCH=x86" "-DCLR_CMAKE_TARGET_OS=windows" "-DCLI_CMAKE_FALLBACK_RID=" "-DCLR_CMAKE_PGO_INSTRUMENT=0" "-DCLR_CMAKE_OPTDATA_PATH=" "-DCLR_CMAKE_PGO_OPTIMIZE=0" 

note: `-DCLI_CMAKE_FALLBACK_RID=` is empty.

I have no clue what I'm doing wrong.

Comment (am11) [reply src/coreclr/build-runtime.cmd:365]: And the previous line is `The system cannot find the drive specified.`

`for /f` has two meaning, it can treat the argument as file path (and reads its text) or string text, when argument is quoted. Somehow, it doesn't like `for` inside `if` although delayed expansion is enabled. But I'm not a batch expert either. 😅

If we move line 360-363 before the parent `if` block (which starts line 332), then it seems to work as expected.

Comment (tmds) [reply src/coreclr/build-runtime.cmd:365]: Thanks! Let's give that a run.

File: src/native/corehost/build.cmd [hunk 3]
```diff
@@ -100,8 +102,13 @@ if /i "%__PortableBuild%" == "1"   (set cm_BaseRid=win)
 set cm_BaseRid=%cm_BaseRid%-%__BuildArch%
 echo "Computed RID for native build is %cm_BaseRid%"
 
+:: When the host runs on an unknown rid, it falls back to the output rid
+:: Strip the architecture
+:: for /f "delims=-" %%i in ("%__OutputRid%") do set __FallbackOS=%%i
+__FallbackOS=win10
```
Comment (am11) [inline src/native/corehost/build.cmd:108]:
```suggestion
set __FallbackOS=win10
```

**Comment by tmds** [comment]
CI is looking good for these changes.

Portable and non-portable share the same logic.

Also, the Windows has the same logic as the Unix script.
The Windows script could be simplified to: `set __FallbackOS=win10` so it matches the `FALLBACK_HOST_RID` that was in the host for Windows.
I don't know what the preference is.

@vitek-karas @elinor-fung this is up for review.

File: src/native/corehost/setup.cmake [hunk 4]
```diff
@@ -50,3 +50,9 @@ else()
         add_definitions(-DREPO_COMMIT_HASH="${CLI_CMAKE_COMMIT_HASH}")
     endif()
 endif()
+
+if("${CLI_CMAKE_FALLBACK_RID}" STREQUAL "")
```
Comment (elinor-fung) [inline src/native/corehost/setup.cmake:54]: nit: Can we name it something like `CLI_CMAKE_FALLBACK_RID_OS` and `FALLBACK_HOST_RID_OS` instead? I know the existing define just had RID, but I think it would be helpful to have some indication that it needs to only be the OS portion, not any full RID.

File: src/native/corehost/build.cmd [hunk 5]
```diff
@@ -35,7 +36,8 @@ if /i [%1] == [amd64]       (set __BuildArch=x64&&shift&goto Arg_Loop)
 if /i [%1] == [arm64]       (set __BuildArch=arm64&&shift&goto Arg_Loop)
 
 if /i [%1] == [portable]    (set __PortableBuild=1&&shift&goto Arg_Loop)
-if /i [%1] == [rid]         (set __TargetRid=%2&&shift&&shift&goto Arg_Loop)
+if /i [%1] == [rid]         (set __OutputRid=%2&&shift&&shift&goto Arg_Loop)
+if /i [%1] == [outputrid]   (set __OutputRid=%2&&shift&&shift&goto Arg_Loop)
```
Comment (elinor-fung) [inline src/native/corehost/build.cmd:40]: Can you remove `rid` and  switch the build args passed on Windows to use `outputrid` instead?
https://github.com/dotnet/runtime/blob/14b844c06baabadcd0af7231015ee2321a51af59/src/native/corehost/corehost.proj#L136

Having both seems confusing and just keeping `outputrid` would match non-Windows better.

**Comment by tmds** [comment]
I've addressed the feedback, and CI looks happy.

**Review by elinor-fung — APPROVED** [review]
Thank you!

**Comment by tmds** [comment]
And thank you and @am11 for reviewing!
