### PR TITLE
Have mono handle ConvertToIntegerNative for Double and Single

### LINKED ISSUE #49586: [Perf] Linux/arm64: 5 Regressions on 2/1/2025 11:17:39 PM +00:00
### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 22.04
Queue | AmpereUbuntu
Baseline | [ad7b8299d8d80eb27cf22838c7017c5872056b56](https://github.com/dotnet/runtime/commit/ad7b8299d8d80eb27cf22838c7017c5872056b56)
Compare | [5a8f4055574f513a6e8a1d04ac20216ca041773a](https://github.com/dotnet/runtime/commit/5a8f4055574f513a6e8a1d04ac20216ca041773a)
Diff | [Diff](https://github.com/dotnet/runtime/compare/ad7b8299d8d80eb27cf22838c7017c5872056b56...5a8f4055574f513a6e8a1d04ac20216ca041773a)
Configs | CompilationMode:tiered, LLVM:true, MonoAOT:true, MonoInterpreter:false, RunKind:micro_mono

### Regressions in System.Tests.Perf_Random

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Next_int - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 22.04_LLVM=true_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono/System.Tests.Perf_Random.Next_int.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime.Extensions/Perf.Random.cs#L31-#L32>)</li><li>[ADX - Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACl1STW/bMAy9B8h/0HJRgrmxG6RAk0HAuq7YhjXbkATdMdAsOtagD0Oi1wTr/vso27n0QoEf75F8lAFkCBGZYO/57hwR7HxPfpz/gFAdttIpb+ff4IQH7ZC/G48MIWSFEAiiJAJqC9NFsVheXS+uiuW+WK0Xq/XN7fzmtlgtr5dvi2JdFLMBGaDxBOTKowPMQ+sS/sL7K0hX1ikfoIp5DVLF3ErtLgWld5U+ps5nJ60up3/5vbeNNhK1dxuvgK8ZRw0BFM8Yf3x82nSR0ELyN975u+/716EvjvZpApBNqUqa2OW2rfuqnUoxahb8wVIx/5eW+QT4WUf0QZfSfJQof2qs0ywy6OhdnCZVRTJZL5fobNYpIJLJhnVF/2TDcqJ/ZuPRC2uC/w0lsh0EDTFjH1pt1J4E26G0TcaepGlBpHvde1ISwhZia/DuDwR5hPEoz1/Yc01iDAzsDZEj6RnZZIL+4VSaVsFkwvKcPZyI0gDzFau0IS7tjsy3dGwWO3AaKIBTdPl0s7KWAdkzbc2mfYG4jHkqvWmtE6/HPffxKLq5qQ41GhCc5Etynwd3AzK2ASzQh5v9BzLv+mqhAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=>)</li></ul> | 15.44 ns | 27.99 ns | 1.81 | 0.27 | False | | |
|<ul><li>[Next_int_int - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 22.04_LLVM=true_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono/System.Tests.Perf_Random.Next_int_int.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime.Extensions/Perf.Random.cs#L37-#L38>)</li><li>[ADX - Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACl1STW8TMRC9R8p/MLk4EdvsNl1VEGSJUipANAUlUTlGZj2bGHntlT2miSj/vePdzaUHjzUf73nmjQ0gQwjIBPvIN6eA0My35If5T/D1bi2tcs38AY6407Y7/MN4ZAglawRPMCURUDcwXRSL8uJycVGU2+L98qpYFu/m1+VVeX1Zvi3IK2YD0kPrCMiVQwuY+2gT/sz720tbHVLeQx3yA0gV8kZqey6onK31Pr18srLR1fQfv3VNq41E7ezKKeBLxlGDB8Uzxu/vH1ddxEdI/spZd/Nj+zr0zdI8rQeyKVVLE7rcOtrv2qoUo8e82zVUzP+nYb4AftUBndeVNJ8lyl8aD6kX6XVwNkyTsiKZrJdLdDbrFBDJZMO4or+yYTjRX7Px6Jm13v2BCtkGvIaQsU9RG7UlwTYomzZjj9JEEGlnt46UBL+GEA3e/AUv9zAe5fkzezqQGAMDe0PkSHoGNpmguztWJiqYTFies7sjURpgrma1NsSl7Z65SMtmoQOnhjxYRZtPO6sO0iN7oqnZtC8Q5zaPlTOxseJ1u6c+HkTXN9WhRgOCk3xJ7tPgrkCG6KEB+nCzF5OA3QKlAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=>)</li></ul> | 8.98 ns | 20.28 ns | 2.26 | 0.50 | False | | |
|<ul><li>[Next_long_long - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 22.04_LLVM=true_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono/System.Tests.Perf_Random.Next_long_long.html>)</li><li>[ADX - Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACl1RTY/TMBC9V+p/ML24FdkmLasVLbLEsqwAsQXUVsuxMvGkMXLsyB6zrVj+O+MkvexlrPl44/feGECGEJAJ9p7vzgGhme8pD/Mf4KvDVlrlmvk3OOHBOHvsAn83HhnCyQrBE1BJBNQNTJfF8vpqsbwqrvfFav2mWC/ezm9Wi+XqpnhdFOuimA1ID60jIFcOLWDuo034y95fXtqyTn0PVchrkCrkjdT2MlA6W+lj+vlsZaPL6V9+55pWG4na2Y1TwNeMowYPimeMPzw8brqKj5DyjbPu9vv+ZemLJT2tB4qpVUkTut422q/aqlSjz7w7NDTM/yUxnwA/64DO61KajxLlT4114iK9Ds6GafJWpJD1dokuZp0DIoVskCv6JxvEif6ZjUfPrPXuN5TIduA1hIx9iNqoPRm2Q9m0GXuUJoJIV7tz5CT4LYRo8PYPeHmE8SjPn9lTTWYMG9grWo7kZ2CTCbr7U2migsmE5Tm7P9FKA8xVrNKGdml7ZC7SsVnowImQB6vo8ulmZS09sidSzab9gLjQPJXOxMaKl3TPfT2IjjfNoUYDgpN9ye7zkG5AhuihAYt89h8U+HSppwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=>)</li></ul> | 49.02 ns | 79.16 ns | 1.61 | 0.10 | False | | |
|<ul><li>[Next_long - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 22.04_LLVM=true_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono/System.Tests.Perf_Random.Next_long.html>)</li><li>[ADX - Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACl1RTW8TMRC9R8p/MLk4EdvsEipKgyxRSgWIBlASlWNk1rNZI39E9pgmovx3xrubSy9jzccbv/fGADKEiEyw93xzigh2vqU8zn9AaHZr6ZS3829wxJ3xbs/fjUeGILJBCIRREgG1hemiWlxevFpcVJfb6nr5ulou3s6vrqh4/eZlVS2rajYgAxw8Abny6ADLkFzGn/f+CtLVbe4HaGLZglSxtFK780DtXaP3+eeTk1bX07/81tuDNhK1dyuvgC8ZRw0BFC8Yv79/WHWVkCDnK+/8zfft89IXR3oOASjmViNN7Hrr5L5qp3KNPgt+Z2mY/8tiPgF+1hF90LU0HyXKnxrbzEUGHb2L02yryKHo7RJdLDoHRA7FIFf0TzGIE/0zG4+e2CH431Aj20DQEAv2IWmjtmTYBqU9FOxBmgQiH+zWk5MQ1hCTwZs/EOQexqOyfGKPLZkxbGAvaDmSn5FNJujvjrVJCiYTVpbs7kgrDTDfsEYb2qXdnvlEx2axA2dCAZyiy+eb1a0MyB5JNZv2A+JM81h7k6wTz+me+noUHW+aQ40GBCf7st2nIV2BjCmABYd89h8ezEExogIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=>)</li></ul> | 52.35 ns | 76.64 ns | 1.46 | 0.25 | False | | |

graph
graph
graph
graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/02_04_2025/refs/heads/main_arm64_ubuntu%2022.04_LLVM%3Dtrue_MonoAOT%3Dtrue_MonoInterpreter%3Dfalse_RunKind%3Dmicro_mono_Regression/System.Tests.Perf_Random.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

<details>
<summary>Repro Steps</summary>

#### Prerequisites (Files either built locally (with build.(sh/cmd) or downloaded from payload above (if same system setup) (in this order))
- Libraries build extracted to `runtime/artifacts` or build instructions: [Libraries README](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/libraries/README.md) args: `-subset libs+libs.tests -rc release -configuration Release -arch $RunArch -framework net8.0`
- CoreCLR product build extracted to `runtime/artifacts/bin/coreclr/$RunOS.$RunArch.Release`, build instructions: [CoreCLR README](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/README.md) args: `-subset clr+libs -rc release -configuration Release -arch $RunArch -framework net8.0`
- AOT MONO build extracted to `runtime/artifacts/bin/mono/$RunOS.$RunArch.Release`, build instructions: [MONO README](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/mono/README.md) args: `-arch $RunArch -os $RunOS -s mono+libs+host+packs -c Release /p:CrossBuild=false /p:MonoLLVMUseCxx11Abi=false`
- Dotnet SDK installed for dotnet commands
- Running commands from the runtime folder

Linux
```cmd
# Set $RunDir to the runtime directory
RunDir=`pwd`

# Set the OS, arch, and OSId
RunOS='linux'
RunOSId='linux'
RunArch='x64'

# Create aot directory
mkdir -p $RunDir/artifacts/bin/aot/sgen
mkdir -p $RunDir/artifacts/bin/aot/pack
cp -r $RunDir/artifacts/obj/mono/$RunOS.$RunArch.Release/mono/* $RunDir/artifacts/bin/aot/sgen
cp -r $RunDir/artifacts/bin/microsoft.netcore.app.runtime.$RunOS-$RunArch/Release/* $RunDir/artifacts/bin/aot/pack

# Create Core Root
$RunDir/src/tests/build.sh release $RunArch generatelayoutonly /p:LibrariesConfiguration=Release

# Clone performance
git clone --branch main --depth 1 --quiet https://github.com/dotnet/performance.git $RunDir/performance

# One line run:
python3 $RunDir/performance/scripts/benchmarks_ci.py --csproj $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --incremental no --architecture $RunArch -f net8.0 --filter 'System.Tests.Perf_Random*' --bdn-artifacts $RunDir/artifacts/BenchmarkDotNet.Artifacts --bdn-arguments="--anyCategories Libraries Runtime  --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir/artifacts/bin/aot/sgen/mini/mono-sgen --customruntimepack $RunDir/artifacts/bin/aot/pack --aotcompilermode llvm --logBuildOutput --generateBinLog"

# Individual Commands:
# Restore
dotnet restore $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --packages $RunDir/performance/artifacts/packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Build
dotnet build $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore /p:NuGetPackageRoot=$RunDir/performance/artifacts/packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Run
dotnet run --project $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore --no-build -- --filter System.Tests.Perf_Random* --anyCategories Libraries Runtime " --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir/artifacts/bin/aot/sgen/mini/mono-sgen --customruntimepack $RunDir/artifacts/bin/aot/pack --aotcompilermode llvm --logBuildOutput --generateBinLog " --artifacts $RunDir/artifacts/BenchmarkDotNet.Artifacts --packages $RunDir/performance/artifacts/packages --buildTimeout 1200
```

Windows
```cmd
# Set $RunDir to the runtime directory
$RunDir="FullPathHere"

# Set the OS, arch, and OSId
RunOS='windows'
RunOSId='win'
RunArch='x64'

# Create aot directory
mkdir $RunDir\artifacts\bin\aot\sgen
mkdir $RunDir\artifacts\bin\aot\pack
xcopy $RunDir\artifacts\obj\mono\$RunOS.$RunArch.Release\mono $RunDir\artifacts\bin\aot\sgen\ /e /y
xcopy $RunDir\artifacts\bin\microsoft.netcore.app.runtime.$RunOSId-$RunArch\Release $RunDir\artifacts\bin\aot\pack\ /e /y

# Create Core Root
$RunDir\src\tests\build.cmd release $RunArch generatelayoutonly /p:LibrariesConfiguration=Release

# Clone performance
git clone --branch main --depth 1 --quiet https://github.com/dotnet/performance.git $RunDir\performance

# One line run:
python3 $RunDir\performance\scripts\benchmarks_ci.py --csproj $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --incremental no --architecture $RunArch -f net8.0 --filter 'System.Tests.Perf_Random*' --bdn-artifacts $RunDir\artifacts\BenchmarkDotNet.Artifacts --bdn-arguments="--anyCategories Libraries Runtime  --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir\artifacts\bin\aot\sgen\mini\mono-sgen.exe --customruntimepack $RunDir\artifacts\bin\aot\pack --aotcompilermode llvm --logBuildOutput --generateBinLog"

# Individual Commands:
# Restore
dotnet restore $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --packages $RunDir\performance\artifacts\packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Build
dotnet build $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore /p:NuGetPackageRoot=$RunDir\performance\artifacts\packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Run
dotnet run --project $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore --no-build -- --filter System.Tests.Perf_Random* --anyCategories Libraries Runtime " --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir\artifacts\bin\aot\sgen\mini\mono-sgen.exe --customruntimepack $RunDir\artifacts\bin\aot\pack -aotcompilermode llvm --logBuildOutput --generateBinLog " --artifacts $RunDir\artifacts\BenchmarkDotNet.Artifacts --packages $RunDir\performance\artifacts\packages --buildTimeout 1200
```

</details>

<details>

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 22.04
Queue | AmpereUbuntu
Baseline | [ad7b8299d8d80eb27cf22838c7017c5872056b56](https://github.com/dotnet/runtime/commit/ad7b8299d8d80eb27cf22838c7017c5872056b56)
Compare | [5a8f4055574f513a6e8a1d04ac20216ca041773a](https://github.com/dotnet/runtime/commit/5a8f4055574f513a6e8a1d04ac20216ca041773a)
Diff | [Diff](https://github.com/dotnet/runtime/compare/ad7b8299d8d80eb27cf22838c7017c5872056b56...5a8f4055574f513a6e8a1d04ac20216ca041773a)
Configs | CompilationMode:tiered, LLVM:true, MonoAOT:true, MonoInterpreter:false, RunKind:micro_mono

### Regressions in System.Numerics.Tests.Perf_VectorOf&lt;Double&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[DivisionOperatorBenchmark - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 22.04_LLVM=true_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono/System.Numerics.Tests.Perf_VectorOf(Double).DivisionOperatorBenchmark.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Numerics.Vectors/Perf_VectorOfT.cs#L56-#L57>)</li><li>[ADX - Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACl1RTW8aMRC9I/EfXC4GdcNuSIQErasmIUqrhlIFRI+RszsLbv2xsscJqMl/73iBSy5jeT7evHlPAzKEgEywr3y5Dwhm+DMa8KoMwxUVwvAX+PpxDSU6v6g/z1x80vBlOFPPKihnFw14SaVrsOXWSP+Xf+p2NKHKGsETbCURUBnoj4rR5dn56Ky4XBWT6cV4OhoPJ5PzSTEZfyyKaVEMjpMeGkeDvHJoAXMfbZo/4T55SZtS3UMd8i3IKuRGKntqKJ2t1SZt3ltpVNn/x2+caZSWSHznrgI+ZRwVeKh4xvj9/XreZnyE9J87664Wq/ep75buaTxQTKVa6tDWHqL9oWyVcrTMu0dDzfwtHXMH+E0FEkeVUs8kyt8Kt4mL9Co4G/pJeZFCdpBLtDFrFRApZMdzxeHJjseJwzPodl5Z490fMoctyTMIGbuOSlcrEmyJ0jQZW0sdQSQrbxwpCf4BQtR49Uy+baDbyfNX9rIlMY4I7AOBI+kZWK+H7nZX6lhBr8fynN3uCFIDczWrlSYsZTfMRTKbhXY4EfJgK3I+eVZupUf2Qlez/qFBnGjuSqejseI93f0hH0TLm/pQoQbBSb4k9/74nYMM0YMBi3zwHzPUUrzFAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=>)</li></ul> | 3.10 ns | 4.17 ns | 1.34 | 0.44 | False | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/02_04_2025/refs/heads/main_arm64_ubuntu%2022.04_LLVM%3Dtrue_MonoAOT%3Dtrue_MonoInterpreter%3Dfalse_RunKind%3Dmicro_mono_Regression/System.Numerics.Tests.Perf_VectorOf%28Double%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

<details>
<summary>Repro Steps</summary>

#### Prerequisites (Files either built locally (with build.(sh/cmd) or downloaded from payload above (if same system setup) (in this order))
- Libraries build extracted to `runtime/artifacts` or build instructions: [Libraries README](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/libraries/README.md) args: `-subset libs+libs.tests -rc release -configuration Release -arch $RunArch -framework net8.0`
- CoreCLR product build extracted to `runtime/artifacts/bin/coreclr/$RunOS.$RunArch.Release`, build instructions: [CoreCLR README](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/README.md) args: `-subset clr+libs -rc release -configuration Release -arch $RunArch -framework net8.0`
- AOT MONO build extracted to `runtime/artifacts/bin/mono/$RunOS.$RunArch.Release`, build instructions: [MONO README](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/mono/README.md) args: `-arch $RunArch -os $RunOS -s mono+libs+host+packs -c Release /p:CrossBuild=false /p:MonoLLVMUseCxx11Abi=false`
- Dotnet SDK installed for dotnet commands
- Running commands from the runtime folder

Linux
```cmd
# Set $RunDir to the runtime directory
RunDir=`pwd`

# Set the OS, arch, and OSId
RunOS='linux'
RunOSId='linux'
RunArch='x64'

# Create aot directory
mkdir -p $RunDir/artifacts/bin/aot/sgen
mkdir -p $RunDir/artifacts/bin/aot/pack
cp -r $RunDir/artifacts/obj/mono/$RunOS.$RunArch.Release/mono/* $RunDir/artifacts/bin/aot/sgen
cp -r $RunDir/artifacts/bin/microsoft.netcore.app.runtime.$RunOS-$RunArch/Release/* $RunDir/artifacts/bin/aot/pack

# Create Core Root
$RunDir/src/tests/build.sh release $RunArch generatelayoutonly /p:LibrariesConfiguration=Release

# Clone performance
git clone --branch main --depth 1 --quiet https://github.com/dotnet/performance.git $RunDir/performance

# One line run:
python3 $RunDir/performance/scripts/benchmarks_ci.py --csproj $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --incremental no --architecture $RunArch -f net8.0 --filter 'System.Numerics.Tests.Perf_VectorOf&lt;Double&gt;*' --bdn-artifacts $RunDir/artifacts/BenchmarkDotNet.Artifacts --bdn-arguments="--anyCategories Libraries Runtime  --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir/artifacts/bin/aot/sgen/mini/mono-sgen --customruntimepack $RunDir/artifacts/bin/aot/pack --aotcompilermode llvm --logBuildOutput --generateBinLog"

# Individual Commands:
# Restore
dotnet restore $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --packages $RunDir/performance/artifacts/packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Build
dotnet build $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore /p:NuGetPackageRoot=$RunDir/performance/artifacts/packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Run
dotnet run --project $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore --no-build -- --filter System.Numerics.Tests.Perf_VectorOf&lt;Double&gt;* --anyCategories Libraries Runtime " --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir/artifacts/bin/aot/sgen/mini/mono-sgen --customruntimepack $RunDir/artifacts/bin/aot/pack --aotcompilermode llvm --logBuildOutput --generateBinLog " --artifacts $RunDir/artifacts/BenchmarkDotNet.Artifacts --packages $RunDir/performance/artifacts/packages --buildTimeout 1200
```

Windows
```cmd
# Set $RunDir to the runtime directory
$RunDir="FullPathHere"

# Set the OS, arch, and OSId
RunOS='windows'
RunOSId='win'
RunArch='x64'

# Create aot directory
mkdir $RunDir\artifacts\bin\aot\sgen
mkdir $RunDir\artifacts\bin\aot\pack
xcopy $RunDir\artifacts\obj\mono\$RunOS.$RunArch.Release\mono $RunDir\artifacts\bin\aot\sgen\ /e /y
xcopy $RunDir\artifacts\bin\microsoft.netcore.app.runtime.$RunOSId-$RunArch\Release $RunDir\artifacts\bin\aot\pack\ /e /y

# Create Core Root
$RunDir\src\tests\build.cmd release $RunArch generatelayoutonly /p:LibrariesConfiguration=Release

# Clone performance
git clone --branch main --depth 1 --quiet https://github.com/dotnet/performance.git $RunDir\performance

# One line run:
python3 $RunDir\performance\scripts\benchmarks_ci.py --csproj $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --incremental no --architecture $RunArch -f net8.0 --filter 'System.Numerics.Tests.Perf_VectorOf&lt;Double&gt;*' --bdn-artifacts $RunDir\artifacts\BenchmarkDotNet.Artifacts --bdn-arguments="--anyCategories Libraries Runtime  --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir\artifacts\bin\aot\sgen\mini\mono-sgen.exe --customruntimepack $RunDir\artifacts\bin\aot\pack --aotcompilermode llvm --logBuildOutput --generateBinLog"

# Individual Commands:
# Restore
dotnet restore $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --packages $RunDir\performance\artifacts\packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Build
dotnet build $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore /p:NuGetPackageRoot=$RunDir\performance\artifacts\packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Run
dotnet run --project $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore --no-build -- --filter System.Numerics.Tests.Perf_VectorOf&lt;Double&gt;* --anyCategories Libraries Runtime " --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir\artifacts\bin\aot\sgen\mini\mono-sgen.exe --customruntimepack $RunDir\artifacts\bin\aot\pack -aotcompilermode llvm --logBuildOutput --generateBinLog " --artifacts $RunDir\artifacts\BenchmarkDotNet.Artifacts --packages $RunDir\performance\artifacts\packages --buildTimeout 1200
```

</details>

<details>

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by tannergooding**
This should resolve https://github.com/dotnet/perf-autofiling-issues/issues/49586

### CODE REVIEW

File: src/mono/mono/mini/intrinsics.c [hunk 1]
```diff
@@ -2322,6 +2322,63 @@ mini_emit_inst_for_method (MonoCompile *cfg, MonoMethod *cmethod, MonoMethodSign
...
+			MonoTypeEnum tto_type = method_context->method_inst->type_argv [0]->type;
+			MonoStackType tto_stack = STACK_I4;
+			switch (tto_type) {
+				case MONO_TYPE_I1:
+					opcode = OP_FCONV_TO_I1;
+					break;
+				case MONO_TYPE_I2:
+					opcode = OP_FCONV_TO_I2;
+					break;
+#if TARGET_SIZEOF_VOID_P == 4
```
Comment (lateralusX) [inline src/mono/mono/mini/intrinsics.c:2340]: nit: in other places we use SIZEOF_REGISTER for these kinds of checks.

**Comment by lateralusX** [comment]
Little curious why this is excluded on Mono, [ConvertToIntegerNative ](https://github.com/dotnet/runtime/blob/f810340d7ee469abf4ccf937ab88f34dd64ef09c/src/libraries/System.Private.CoreLib/src/System/Single.cs#L663) ? For direct calls we would optimize calls using the new intrinsic implemented by this PR, but I would assume that indirect calls might end up in this implementation on Mono as well.

File: src/mono/mono/mini/intrinsics.c (hunk 1 above)
Comment (matouskozak) [reply src/mono/mono/mini/intrinsics.c:2340]: looks like it varies based on a file, in `simd-intrinsics.c`, the `TARGET_SIZEOF_VOID_P` looks to be the dominant way.

Comment (lateralusX) [reply src/mono/mono/mini/intrinsics.c:2340]: yeah its mixed, in this file SIZEOF_REGISTER seems to dominate. An interesting observation is that we have some code like this:

#if (SIZEOF_REGISTER > TARGET_SIZEOF_VOID_P) && (G_BYTE_ORDER == G_BIG_ENDIAN)

and we have this comment in [mono-machine.h](https://github.com/dotnet/runtime/blob/aeda1de6c20cb055e54c0527d595dfa919e2bfd6/src/mono/mono/utils/mono-machine.h#L64)

SIZEOF_REGISTER is usually the same as TARGET_SIZEOF_VOID_P, except when MONO_ARCH_ILP32 is defined

**Comment by tannergooding** [comment]
Looks like this needs to explicitly add support to Mono Interpreter as well.

**Review by kg — APPROVED** [review]
Interp parts LGTM, less certain about mini

**Comment by tannergooding** [comment]
Cc. @BrzVlad for the mono mini side

**Review by BrzVlad — APPROVED** [review]

**Comment by matouskozak** [comment]
Thank you @tannergooding for the fix. The regressions got resolved 
image
