### PR TITLE
[main] Fix LoaderAllocator computation for a generic type instance

### LINKED ISSUE #111611: LoaderAllocator selection logic for a generic type instance does not account for a LoaderAllocator of type itself
### Description

`ClassLoader::ComputeLoaderModuleWorker` uses a LoaderAllocator creation number to determine the latest LoaderAllocator to place a class in. However the method [does not account the number of the type definition itself](https://github.com/dotnet/runtime/blob/b03f83de362f7168c94daa2f4b192959abefe366/src/coreclr/vm/clsload.cpp#L165) when calculating the latest number and this can lead into a situation when the generic instance is put into an older LoaderAllocator.

E.g. if we have type `ClassA` from AssemblyLoadContext `A` with number 2 and type `ClassB` from AssemblyLoadContext `B` with number 5 the resulting loader allocator for the type `ClassB` would correspond to AssemblyLoadContext `A` with creation number 2. If `ClassB` contains a static, such static would be then placed under the LoaderAllocator `A`, preventing AssemblyLoadContext `B` from unloading unless `A` is unloaded.

### Reproduction Steps

1. Create 2 classes in 2 different assemblies

Assembly A
```
public class ClassA
{
}
```

Assembly B
```
public class ClassB<T>
{
    public static T instance = new T();
}
```

2. Load `A.dll` into a collectible AssemblyLoadContext `A`.
3. Load `B.dll` into a collectible AssemblyLoadContext `B`.
4. Instantiate type `ClassB<ClassA>`.
5. Ensure instance is not referenced and unload AssemblyLoadContext `B`.

### Expected behavior

AssemblyLoadContext `B` is unloaded successfully

### Actual behavior

AssemblyLoadContext `B` is not unloaded

### Regression?

No

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

The following change seem to fix the issue - https://github.com/Unity-Technologies/runtime/pull/279

### PR DESCRIPTION
**Pull request by alexey-zakharov**
## Purpose of this PR
Improve logic of computing LoaderAllocator for a generic type instance to avoid AssemblyLoadContext leaks.
Resolves https://github.com/dotnet/runtime/issues/111611

**Problem:**
`ClassLoader::ComputeLoaderModuleWorker` uses a LoaderAllocator creation number to determine the latest LoaderAllocator to place a class in. However the method does not account the number of the type definition itself when calculating the latest number and this can lead into a situation when the generic instance is put into the older LoaderAllocator.

E.g. if we have type `ClassA` from AssemblyLoadContext `A` with number 2 and type `ClassB` from AssemblyLoadContext `B` with number 5 the resulting loader allocator for the type ClassB<ClassA> would correspond to AssemblyLoadContext `A`. If `ClassB` contains a static, such static would be then placed under the LoaderAllocator `A`, preventing AssemblyLoadContext `B` from unloading.

**Proposed solution:**
The PR updates the `ComputeLoaderModuleWorker` logic to account for the LoaderAllocator of a defining type, so we use it if it has the latest creation number.

(cherry picked from commit b3a73f3b66589df3cd8d00c7333ad28e84d669d2)

### CODE REVIEW

File: src/coreclr/vm/clsload.cpp [hunk 1]
```diff
@@ -176,22 +179,17 @@ PTR_Module ClassLoader::ComputeLoaderModuleWorker(
...
+                pLoaderAllocatorCheck->GetCreationNumber() > latestFoundNumber)
             {
                 pOldestLoaderModule = pModuleCheck;
-                pOldestLoaderAllocator = pLoaderAllocatorCheck;
-                oldestFoundAge = pLoaderAllocatorCheck->GetCreationNumber();
+                latestFoundNumber = pLoaderAllocatorCheck->GetCreationNumber();
             }
         }
 
         // Only if we didn't find a different loader allocator than the defining loader allocator do we
```
Comment (alexey-zakharov) [inline src/coreclr/vm/clsload.cpp:190]: @joncham spotted, that perhaps this part of the comment is not needed anymore

File: src/coreclr/vm/clsload.cpp [hunk 2]
```diff
@@ -113,18 +113,15 @@ PTR_Module ClassLoader::ComputeLoaderModuleWorker(
...
-    Module *pLoaderModule = NULL;
-
-    if (pDefinitionModule)
-    {
-        if (pDefinitionModule->IsCollectible())
-            goto ComputeCollectibleLoaderModule;
-        pLoaderModule = pDefinitionModule;
-    }
+    // Use the definition module as the loader module by default
+    Module *pLoaderModule = pDefinitionModule;
```
Comment (alexey-zakharov) [inline src/coreclr/vm/clsload.cpp:121]: if pDefinitionModule != null we effectively fall through to it if it is collectible or not at the end, so I've decided to remove the if block

File: src/coreclr/vm/clsload.cpp [hunk 3]
```diff
@@ -155,14 +154,18 @@ PTR_Module ClassLoader::ComputeLoaderModuleWorker(
...
         DWORD classArgsCount = classInst.GetNumArgs();
         DWORD totalArgsCount = classArgsCount + methodInst.GetNumArgs();
 
-        if (pDefinitionModule != NULL) pLoaderAllocatorOfDefiningType = pDefinitionModule->GetLoaderAllocator();
+        // If possible use the loader allocator of the defining type
+        // and its creation number as the starting age.
+        if (pDefinitionModule != NULL)
+        {
+            pOldestLoaderModule = pDefinitionModule;
+            latestFoundNumber = pDefinitionModule->GetLoaderAllocator()->GetCreationNumber();
```
Comment (alexey-zakharov) [inline src/coreclr/vm/clsload.cpp:167]: assumption here is that if module in non-collectible ALC (or Default it still has a LoaderAllocator), but perhaps if it is not collectible we need to ignore it in favor of a first collectible number 🤔

File: src/coreclr/vm/clsload.cpp [hunk 4]
```diff
@@ -176,22 +179,18 @@ PTR_Module ClassLoader::ComputeLoaderModuleWorker(
             Module *pModuleCheck = arg.GetLoaderModule();
             LoaderAllocator *pLoaderAllocatorCheck = pModuleCheck->GetLoaderAllocator();
 
-            if (pLoaderAllocatorCheck != pLoaderAllocatorOfDefiningType &&
-                pLoaderAllocatorCheck->IsCollectible() &&
-                pLoaderAllocatorCheck->GetCreationNumber() > oldestFoundAge)
+            if (pLoaderAllocatorCheck->IsCollectible() &&
+                pLoaderAllocatorCheck->GetCreationNumber() > latestFoundNumber)
             {
                 pOldestLoaderModule = pModuleCheck;
```
Comment (davidwrighton) [inline src/coreclr/vm/clsload.cpp:185]: Please rename `pOldestLoaderModule` to something like `pLatestLoaderModule` The name is a legacy of very long ago when I was doing experiments to build this feature, and ... is rather inaccurate.

**Review by davidwrighton — CHANGES_REQUESTED** [review]
As you note, a test would be helpful. However, since the behavior of this sort of computation is not actually specified and may change in the future without warning, I'd rather not merge it in with existing tests, and would prefer this to be a separate test (and for the test to have some comments in it indicating that failure is reasonable when running on different runtimes). I'm pretty flexible on naming though, as I don't have a strong opinion. I'm notoriously terrible at naming stuff.

**Comment by alexey-zakharov** [comment]
> would prefer this to be a separate test (and for the test to have some comments in it indicating that failure is reasonable when running on different runtimes)

I've looked at the best location for the test and found that there is `src/libraries/System.Runtime.Loader/tests/CollectibleAssemblyLoadContextTest.cs` suite which tests ALC unloadability and seems like a perfect fit for the issue - would it be acceptable to have a test there?

- added `Unload_TwoCollectibleWithOneAssemblyAndOneInstanceReferencingAnotherThroughGenericStatic` test which tests the failing scenario
- updated issue links since the mentioned issue is closed now

File: src/coreclr/vm/clsload.cpp (hunk 4 above)
Comment (alexey-zakharov) [reply src/coreclr/vm/clsload.cpp]: done in 3a4e07cf8a8142c25f533eb28b53b908b84fa948

File: src/libraries/System.Runtime.Loader/tests/AssemblyLoadContextTest.cs [hunk 5]
```diff
@@ -189,7 +185,7 @@ public static void DefaultAssemblyLoadContext_Properties()
             Assert.Contains("\"Default\"", alc.ToString());
             Assert.Contains("System.Runtime.Loader.DefaultAssemblyLoadContext", alc.ToString());
             Assert.Contains(alc, AssemblyLoadContext.All);
-            Assert.Contains(Assembly.GetCallingAssembly(), alc.Assemblies);
+            Assert.Contains(typeof(int).Assembly, alc.Assemblies);
```
Comment (alexey-zakharov) [inline src/libraries/System.Runtime.Loader/tests/AssemblyLoadContextTest.cs:188]: I've updated the test because it was failing as the calling assembly for the test method is xunit assembly which is not in the Default ALC and I suppose is test runner implementation specific
CorLib assembly which is where type of int is is more stable check parameter imho

**Comment by alexey-zakharov** [comment]
@davidwrighton I don't see any suspicious test failures - do you think the changes are good to go?

**Review by davidwrighton — APPROVED** [review]
