### PR TITLE
Set DLL flag on R2R binaries

### LINKED ISSUE #54440: R2R causing crashes on Windows 7
Machine OS: win7 SP1
Repro steps:
1. Install .NET 6 prevew 6 SDK-6.0.100-preview.6.21315.23(runtime-6.0.0-preview.6.21306.1) from https://github.com/dotnet/installer--Main branch
2. Run "dotnet new console" in CLI .

Expected Result:
Create project successfully

Actual Result:
NET Host stop working.
image

Note:
Not repro on win10

dotnet --info:
C:\Users\v-danche>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21315.23
 Commit:    8f09936962

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21315.23\

Host (useful for support):
  Version: 6.0.0-preview.6.21306.1
  Commit:  5b8e1780ad

.NET SDKs installed:
  6.0.100-preview.6.21315.23 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21306.3 [C:\Program Files\dotnet\sh
ed\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21306.1 [C:\Program Files\dotnet\share
Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21305.3 [C:\Program Files\dotne
shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### PR DESCRIPTION
**Pull request by AntonLapounov**
Always set the IMAGE_FILE_DLL flag on output assemblies with ReadyToRun code even if the corresponding input IL assembly misses it. This is required for R2R relocations to be processed by the OS loader on Windows 7 and Windows 8.1. Fixes #54440. @dotnet/crossgen-contrib

The corresponding code in the old Crossgen: https://github.com/dotnet/runtime/blob/8a20ae03566e3aabb0c95d2bb206a9ee780db4fd/src/coreclr/zap/zapwriter.cpp#L479-L482
where `m_isDll` is unconditionally set to `true` in `ZapWriter::Initialize`: https://github.com/dotnet/runtime/blob/8a20ae03566e3aabb0c95d2bb206a9ee780db4fd/src/coreclr/zap/zapwriter.cpp#L51

### CODE REVIEW

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs [hunk 1]
```diff
@@ -721,13 +697,11 @@ public static PEHeaderBuilder Create(Characteristics imageCharacteristics, DllCh
                 sectionAlignment = fileAlignment;
             }
 
-            dllCharacteristics &= DllCharacteristics.AppContainer;
```
Comment (mangod9) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs:724]: is `AppContainer` not required?

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs [hunk 2]
```diff
@@ -664,52 +664,28 @@ protected override BlobBuilder SerializeSection(string name, SectionLocation loc
...
-            imageCharacteristics |= (is64BitTarget ? Characteristics.LargeAddressAware : Characteristics.Bit32Machine);
+            Characteristics imageCharacteristics = Characteristics.ExecutableImage | Characteristics.Dll;
+            imageCharacteristics |= is64BitTarget ? Characteristics.LargeAddressAware : Characteristics.Bit32Machine;
 
-            ulong imageBase = PE32HeaderConstants.ImageBase;
-            if (target.IsWindows && is64BitTarget && (imageBase <= uint.MaxValue))
-            {
-                // Base addresses below 4 GiB are reserved for WoW on x64 and disallowed on ARM64.
-                // If the input assembly was compiled for anycpu, its base address is 32-bit and we need to fix it.
-                imageBase = (imageCharacteristics & Characteristics.Dll) != 0 ? PE64HeaderConstants.DllImageBase : PE64HeaderConstants.ExeImageBase;
```
Comment (mangod9) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs:706]: so `ExeImageBase` is never used?

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs (hunk 1 above)
Comment (AntonLapounov) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs:724]: I think this flag does nothing on DLLs.  The C# compiler does not even have an option to set it on a DLL.

Comment (mangod9) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs:724]: but in this case it can also be an exe or since its marked with `IMAGE_FILE_DLL` it does not matter?

**Comment by mangod9** [comment]
might be good to run cg2 outerloop pipeline to ensure it doesn't cause any other regressions.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs (hunk 2 above)
Comment (AntonLapounov) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs:706]: Since we produce a DLL, it should not be used.  In the past we used to take the image base from the input file, later Tomas changed this code to use a constant, making the condition half-meaningless: https://github.com/dotnet/runtime/pull/31663/files#diff-a9a3ebc34e374980992ac65229a97d382e87ba63f7a937b747eca3b51ae6c4ebR582

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs (hunk 1 above)
Comment (AntonLapounov) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs:724]: We always use a host and never run a R2R binary directly.  In what scenario can it be an .exe?

Comment (mangod9) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs:724]: ah yes.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs [hunk 3]
```diff
@@ -664,52 +664,28 @@ protected override BlobBuilder SerializeSection(string name, SectionLocation loc
...
-
         /// <summary>
         /// Fill in PE header information into a PEHeaderBuilder used by PEBuilder.
         /// </summary>
-        /// <param name="relocsStripped">Relocs are not present in the PE executable</param>
-        /// <param name="dllCharacteristics">Extra DLL characteristics to apply</param>
         /// <param name="subsystem">Targeting subsystem</param>
         /// <param name="target">Target architecture to set in the header</param>
-        public static PEHeaderBuilder Create(Characteristics imageCharacteristics, DllCharacteristics dllCharacteristics, Subsystem subsystem, TargetDetails target)
+        public static PEHeaderBuilder Create(Subsystem subsystem, TargetDetails target)
```
Comment (AntonLapounov) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/ObjectWriter/R2RPEBuilder.cs:676]: The only bit of `dllCharacteristics` that we used was `AppContainer`, which seems to do nothing for DLLs.  No bits of `imageCharacteristics`, except the default ones, should be set either.

**Review by trylek — APPROVED** [review]
Looks awesome, thanks for fixing this! I also appreciate the time you took to fix typos in various code comments.

**Review by mangod9 — APPROVED** [review]

**Comment by mangod9** [comment]
we need to evaluate whether we backport this to preview6. My recommendation is to rel-note unless we feel it affects win8+ (which doesnt appear to be the case)

**Comment by AntonLapounov** [comment]
@mangod9 Has anyone actually tried that scenario on Windows 8.1?

**Comment by AntonLapounov** [comment]
All test failures are known and unrelated.
