### PR TITLE
Fix issue when logging stack overflow in WinForm apps.

### LINKED ISSUE #114412: StackOverFlowException no longer breaks into the debugger on F5, instead the app hangs
### .NET version

.NET 10.0 SDK build: 10.0.100-preview.4.25177.19

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro in previous .NET versions, regressed from .NET 10.0 Preview 4, cannot repro in .NET 10.0 Preview 3.

### Issue description
Simpler repro:
```
   public static void Main()
   {
       CauseStackOverflow();
   }
 
   private static void CauseStackOverflow()
   {
       CauseStackOverflow();
   } 
```
After the [update](https://github.com/dotnet/winforms/pull/13169) VS hangs

------
Old repro:

StackOverFlowException cannot be popped up when errorProvider with a large size icon: 256*256

**.NET 10**: when running app, cannot get StackOverFlowException and runtime form

https://github.com/user-attachments/assets/a2450276-149e-4e37-ad7a-5162b4115468

**.NET 9 and .NET framework 4.8.1**: get StackOverFlowException when running app

Image
_System.StackOverflowException
  HResult=0x800703E9
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>_

https://github.com/user-attachments/assets/58696f24-fb4c-4c1b-bcbe-fc4adc937ef9

### Steps to reproduce

Repro steps:
1. Create a Winforms .NET 10 app with TextBox and ErrorProvider added
2. Give a large icon with 256*256 size for errorProvider's Icon property
3. Double-click form designer, SetError for textBox in Form1_Load event
 ```
private void Form1_Load(object sender, EventArgs e)
{
  errorProvider1.SetError(textBox1, "testing");
}
```
4. Build and run application

or use this sample app: [WinFormsApp31.zip](https://github.com/user-attachments/files/19499748/WinFormsApp31.zip)

### PR DESCRIPTION
**Pull request by lateralusX**
WinForm apps doesn't have a console and apparently, Windows implementation of `fileno` doesn't have same behavior as POSIX implementation where a return of -1 means error. On Windows, `fileno` will return -2 when there is no console attached to the app. This bypass the check in `write_file` that should have return 0, instead it will call `_write` that will return an error that was not fully accounted for leading to an infinite loop.

Fix makes sure Windows implementation sees -1 and -2 as invalid file descriptors. Fix also account for errors returned by `_write` breaking out of the loop.

Fixes https://github.com/dotnet/runtime/issues/114412.

### CODE REVIEW

File: src/native/minipal/log.c [hunk 1]
```diff
@@ -239,9 +243,19 @@ static int sync_file(minipal_log_flags flags)
 
     return 0;
 }
+
+static ssize_t write_file(int fd, const char* msg, size_t bytes_to_write)
+{
+    if (fd == -1 || fd == -2)
```
Comment (am11) [inline src/native/minipal/log.c:249]: nit: better
```suggestion
    if (fd < 0)
```

based on the existing pattern:
```sh
$ git grep 'if.*fd <' ':!src/native/external'
src/coreclr/pal/src/configure.cmake:  if (fd < 0)
src/mono/mono/component/debugger-poll.c:        if (fd < 0)
src/mono/mono/component/debugger-poll.c:                if (fd < 0)
src/mono/mono/component/debugger-poll.c:                if (fd < 0)
src/mono/mono/eglib/test/file.c:         * if (fd < 0)
src/mono/mono/mini/cfgdump.c:   if (fd < 0) {
src/mono/mono/profiler/helper.c:        if (*max_fd < GUINT64_TO_INT(fd))
src/mono/mono/utils/mono-filemap.c:     if (fd < 0)
src/native/libs/Common/pal_utilities.h:#ifndef TARGET_WASI // the valid range of file descriptors is probably INT32_MIN <= fd && fd <= INT32_MAX, the negative handles are valid for console.
src/native/libs/System.IO.Ports.Native/pal_serial.c:    if (fd < 0)
src/native/libs/System.Native/pal_io.c:    if (fd < 0) return 0;
src/native/libs/System.Native/pal_io.c:    if (!isReadonly || fd < 0) return fd;
src/native/libs/System.Native/pal_io.c:    if (fd < 0)
src/native/libs/System.Native/pal_networkstatistics.c:                if (fd < 0) {
src/tasks/AndroidAppBuilder/Templates/monodroid.c:    if (fd < 0) {
src/tasks/AppleAppBuilder/Templates/runtime.m:    if (fd < 0) {
src/tasks/LibraryBuilder/Templates/autoinit.c:    if (fd < 0)
```

**Comment by tommcdon** [comment]
@jkotas @AaronRobinsonMSFT

File: src/native/minipal/log.c (hunk 1 above)
Comment (lateralusX) [reply src/native/minipal/log.c:249]: Wanted to be more specific based on the specific documented error codes returned on Windows for _fileno -1 and -2, on POSIX fileno should only return -1, so didn't want to rule out all negative fd's, but if we use similar pattern elsewhere, then maybe we should do the same here. Also, this is mainly tied to result of call to fileno, so maybe I should move the check to that location and don't do it as part of write_file since its an internal function only called from one place.

Comment (jkotas) [inline src/native/minipal/log.c:249]: This can use a comment explaining why we check for `-2`.

Comment (am11) [reply src/native/minipal/log.c:249]: The choice comes down to how much we care for the reason why underlying syscall has failed. In some cases, we want to take different measures based on the error mode. This seems like the other casem where we only care for the successful system call to continue.

Comment (lateralusX) [reply src/native/minipal/log.c:249]: Yes, but we are discussing if we should just look for negative values and be fine with it, the reason is documented here, https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fileno?view=msvc-170, under the Note section. So apparently, they changed the return value in case there is no console attached to -2...

Comment (lateralusX) [reply src/native/minipal/log.c:249]: Alternative is to don't explicit check the file descriptor returned by fileno and react to the errors in write/_write instead. That will be inline with how other code does it as well and according to the documentation of fileno, there is no real error, so as long as it gets called with a valid FILE stream, it should return something other API's should be capable of using or detect as an invalid fd.

Comment (lateralusX) [reply src/native/minipal/log.c]: Removed the explicit checks and left it to write/_write to return error when hitting the case where there is no stdout/stderr available. According to the POSIX/Win32 documentation fileno/_fileno doesn't have a real error return and if the used FILE streams represent a file (we only use stdout/stderr as arguments), it should return something that can be used with other API's. On Windows scenario where there is no console attached to an app, _write will return -1 when called with a file descriptor representing stdout/stderr in a process without a console.

**Review by jkotas — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by Tanya-Solyanik** [comment]
@lateralusX  - is this specific to StackOverflow? I see VS debugger hangs on Binder exceptions as well

**Comment by lateralusX** [comment]
> @lateralusX - is this specific to StackOverflow? I see VS debugger hangs on Binder exceptions as well

It will happen to anything that logs through this function, there are some low level errors and exception that could take that route, so likely related.

**Comment by lateralusX** [comment]
Failures are known errors.
