### PR TITLE
Modify the test case Runtime_40444.cs (release/5.0)

### LINKED ISSUE #44831: CI failure in JIT.Regression Runtime_40444.cmd
https://dev.azure.com/dnceng/public/_build/results?buildId=889393&view=logs&j=cc37abc9-5ced-5ca3-7db5-cfbd415ba586&t=6ce0ccaa-325b-5477-c8ab-ffa0b32a6fdc

```
C:\h\w\A75608B4\w\A9D3095D\e>dotnet C:\h\w\A75608B4\p\xunit.console.dll JIT\Regression\JIT.Regression.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.Regression 
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (32-bit .NET 5.0.0)
  Discovering: JIT.Regression.XUnitWrapper
  Discovered:  JIT.Regression.XUnitWrapper
  Starting:    JIT.Regression.XUnitWrapper
    JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\A75608B4\w\A9D3095D\e\JIT\Regression\Reports\JIT.Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\A75608B4\p\corerun.exe" Runtime_40444.dll 
      0: result = 1
      0: result = 2
      0: result = 3
      0: result = 4
      0: result = 5
      0: result = 6
      0: result = 7
      0: result = 8
      0: result = 9
      0: result = 10
      0: result = 11
      0: result = 12
      0: result = 13
      0: result = 14
      0: result = 15
      0: result = 16
      0: result = 17
      0: result = 18
      0: result = 19
      0: result = 20
      0: result = 21
      0: result = 22
      0: result = 23
      0: result = 24
      0: result = 25
      0: result = 26
      0: result = 27
      0: result = 28
      0: result = 29
      0: result = 30
      0: result = 31
      0: result = 32
      0: result = 33
      0: result = 34
      0: result = 35
      0: result = 36
      0: result = 37
      0: result = 38
      0: result = 39
      0: result = 40
      0: result = 41
      0: result = 42
      0: result = 43
      0: result = 44
      0: result = 45
      0: result = 46
      0: result = 47
      0: result = 48
      0: result = 49
      0: result = 50
      0: result = 51
      0: result = 52
      0: result = 53
      0: result = 54
      0: result = 55
      0: result = 56
      0: result = 57
      0: result = 58
      8732: result = 59
      0: result = 60
      0: result = 61
      0: result = 62
      0: result = 63
      0: result = 64
      0: result = 65
      0: result = 66
      0: result = 67
      0: result = 68
      0: result = 69
      0: result = 70
      0: result = 71
      0: result = 72
      0: result = 73
      0: result = 74
      0: result = 75
      9546: result = 76
      0: result = 77
      8440: result = 78
      0: result = 79
      8043: result = 80
      0: result = 81
      8156: result = 82
      0: result = 83
      14: result = 84
      0: result = 85
      0: result = 86
      0: result = 87
      0: result = 88
      FAILED
      Expected: 100
      Actual: -1
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\A75608B4\p
      > C:\h\w\A75608B4\w\A9D3095D\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs(56691,0): at JIT_Regression._JitBlue_Runtime_40444_Runtime_40444_Runtime_40444_._JitBlue_Runtime_40444_Runtime_40444_Runtime_40444_cmd()
      Output:
        
        Return code:      1
        Raw output file:      C:\h\w\A75608B4\w\A9D3095D\e\JIT\Regression\Reports\JIT.Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.output.txt
        Raw output:
        BEGIN EXECUTION
         "C:\h\w\A75608B4\p\corerun.exe" Runtime_40444.dll 
        0: result = 1
        0: result = 2
        0: result = 3
        0: result = 4
        0: result = 5
        0: result = 6
        0: result = 7
        0: result = 8
        0: result = 9
        0: result = 10
        0: result = 11
        0: result = 12
        0: result = 13
        0: result = 14
        0: result = 15
        0: result = 16
        0: result = 17
        0: result = 18
        0: result = 19
        0: result = 20
        0: result = 21
        0: result = 22
        0: result = 23
        0: result = 24
        0: result = 25
        0: result = 26
        0: result = 27
        0: result = 28
        0: result = 29
        0: result = 30
        0: result = 31
        0: result = 32
        0: result = 33
        0: result = 34
        0: result = 35
        0: result = 36
        0: result = 37
        0: result = 38
        0: result = 39
        0: result = 40
        0: result = 41
        0: result = 42
        0: result = 43
        0: result = 44
        0: result = 45
        0: result = 46
        0: result = 47
        0: result = 48
        0: result = 49
        0: result = 50
        0: result = 51
        0: result = 52
        0: result = 53
        0: result = 54
        0: result = 55
        0: result = 56
        0: result = 57
        0: result = 58
        8732: result = 59
        0: result = 60
        0: result = 61
        0: result = 62
        0: result = 63
        0: result = 64
        0: result = 65
        0: result = 66
        0: result = 67
        0: result = 68
        0: result = 69
        0: result = 70
        0: result = 71
        0: result = 72
        0: result = 73
        0: result = 74
        0: result = 75
        9546: result = 76
        0: result = 77
        8440: result = 78
        0: result = 79
        8043: result = 80
        0: result = 81
        8156: result = 82
        0: result = 83
        14: result = 84
        0: result = 85
        0: result = 86
        0: result = 87
        0: result = 88
        FAILED
        Expected: 100
        Actual: -1
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=C:\h\w\A75608B4\p
        > C:\h\w\A75608B4\w\A9D3095D\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.cmd
```

### PR DESCRIPTION
**Pull request by briansull**
* Modify the test case Runtime_40444.cs
1) Increase the maximum loop count for failure to 1000 million
2) Added additional computation inside of loop
3) Add addition message when the loop executes to the limit and the test case fails

Updated test case and insured that it fails on JITS without the fix
Test now checks it the other thread set t2_finished

* Re-enable the Runtime_40444 test

* Fix typos

### CODE REVIEW

File: src/tests/JIT/Regression/JitBlue/Runtime_40444/Runtime_40444.cs [hunk 1]
```diff
@@ -1,66 +1,154 @@
+
```
Comment (jkotas) [inline src/tests/JIT/Regression/JitBlue/Runtime_40444/Runtime_40444.cs:1]: Nit: Extra new line

Comment (briansull) [reply src/tests/JIT/Regression/JitBlue/Runtime_40444/Runtime_40444.cs:1]: I would like to just leave this matching the existing test in master.

**Comment by AndyAyersMS** [comment]
Port of #40951 to 5.0.

@danmosemsft since this just is a test fix, any extra scrutiny needed before a merge?

**Comment by briansull** [comment]
Manual run of jit-stress confirms that it is green:

https://dev.azure.com/dnceng/public/_build/results?buildId=906223&view=results

**Comment by briansull** [comment]
@jkotas @AndyAyersMS @danmosemsft @jeffschwMSFT 
The JitStress testing in release/5.0 is green with this fix.

So now I need the approval to check this into release/5.0

File: src/coreclr/tests/issues.targets [hunk 2]
```diff
@@ -76,9 +76,6 @@
         <ExcludeList Include="$(XunitTestBinBase)/GC/Scenarios/muldimjagary/muldimjagary/*">
             <Issue>https://github.com/dotnet/runtime/issues/5933</Issue>
         </ExcludeList>
-        <ExcludeList Include="$(XunitTestBinBase)/JIT/Regression/JitBlue/Runtime_40444/*">
```
Comment (jkotas) [inline src/coreclr/tests/issues.targets:79]: Why do we need to fix and re-enable this specific test in servicing?

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  Please work through cr feedback and then we can take this as part of tell mode.

File: src/coreclr/tests/issues.targets (hunk 2 above)
Comment (jkotas) [reply src/coreclr/tests/issues.targets:79]: Ok, I see that people are seeing the test failing in release/5.0: https://github.com/dotnet/runtime/issues/44831#issuecomment-729352185

The test should not be running in release/5.0 in the first place because it is disabled. Why is the test running in release/5.0?

I think we should rather fix the infrastructure problem that is causing this test to run.

**Comment by briansull** [comment]
Because Jit Stress testing was turned in release/5.0 on sometime after the fork.

Originally when I learned of this issue shortly after the fork, I verified that we were not running Jit stress testing jobs in the release/5.0 branch.   But since then these jobs have since been turned on and this occasionally test fails.

So an issue was opened to fix it and I ported this change over from master.

File: src/coreclr/tests/issues.targets (hunk 2 above)
Comment (briansull) [reply src/coreclr/tests/issues.targets:79]: This line is incorrect and didn't actually disable the test.

**Review by jkotas — APPROVED** [review]
