### PR TITLE
JIT: Fix implicit byref block expansion

### LINKED ISSUE #80616: JIT: Assertion failed 'GetLayout()->GetClassHandle() != NO_CLASS_HANDLE' during 'Morph - Global'
```csharp
using System.Numerics;
using System.Runtime.CompilerServices;

class Program
{
    static void Main(string[] args)
    {
        Vector<uint> foo = default;
        FooBar(ref foo, default);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static unsafe void FooBar(ref Vector<uint> foo, Vector<uint> bar)
    {
        foo = bar;
        Expose(ref bar);
        Unsafe.InitBlock(&bar, 0xcd, (uint)sizeof(Vector<uint>));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Expose(ref Vector<uint> f)
    {
    }
}
```

```scala
Assert failure(PID 24688 [0x00006070], Thread: 25500 [0x639c]): Assertion failed 'GetLayout()->GetClassHandle() != NO_CLASS_HANDLE' in 'Program:FooBar(byref,System.Numerics.Vector`1[uint])' during 'Morph - Global' (IL size 34; hash 0x81fff74e; FullOpts)

    File: C:\dev\dotnet\runtime3\src\coreclr\jit\gentree.h Line: 7109
    Image: C:\dev\dotnet\runtime3\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #80616

### CODE REVIEW

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -4810,7 +4810,7 @@ GenTree* Compiler::fgMorphExpandImplicitByRefArg(GenTreeLclVarCommon* lclNode)
     {
         if (argNodeType == TYP_STRUCT)
         {
-            newArgNode = gtNewObjNode(argNodeLayout, addrNode);
+            newArgNode = gtNewStructVal(argNodeLayout, addrNode);
```
Comment (SingleAccretion) [inline src/coreclr/jit/morph.cpp:4813]: I think `fgMorphExpandStackArgForVarArgs` will need the same fix.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @EgorBo @SingleAccretion

**Review by SingleAccretion — APPROVED** [review]

**Review by EgorBo — APPROVED** [review]
