### PR TITLE
[wasm][debugger] Support "on frame evaluation" of functions returning char

### LINKED ISSUE #65064: [wasm][debugger] Evaluation of functions returning char
Reproduction code, add in Counter.razor:
```
    private void IncrementCount()
    {
        var test = new TestClass();
        currentCount++;
    }

    public class TestClass
    {
        public char GetPassedChar(char param) => param;
        public char GetChar() => 'G';
        public bool GetTrueIfPassedA(char param) => param == 'A' ? true : false;
    }
```
Behavior:
Functions that return character (in debugger called *symbol*) are not supported yet, as on the screenshot below.
image

log:
[11:10:09] fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-:::110 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "message": "Evaluate of this datatype symbol not implemented yet" } ]

Where to fix: 
https://github.com/dotnet/runtime/blob/50cdcace8af7f72cf321bbdc9fa8e238ec230958/src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs#L215. There is no case "symbol" so function returning character land in default option that throws an error. Either add another case for symbols or somehow use string flow for chars.

After-fix-to-do:
uncomment GetChar() test case from EvaluateMethodWithDefaultParamCheckTypes test.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/65064. Merge after merging https://github.com/dotnet/runtime/pull/64970.

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 1]
```diff
@@ -231,6 +231,13 @@ private string ConvertJSToCSharpLocalVariableAssignment(string idName, JToken va
                         typeRet = "string";
                         break;
                     }
+                    case "symbol":
+                     {
+                         var str = value?.Value<string>()?.Replace("\'", "")?.LastOrDefault();
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:236]: This doesn't look right.

1. we use `symbol` for other types too, like delegates. (grep for `TSymbol` in the tests)
2. extracting the char value this way is brittle

Looking at the object here, it has a `value` that gets set here:

https://github.com/dotnet/runtime/blob/30f30a3e5b6be09eacf7ea4cf054576753ed99ca/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L1766-L1770

It is using `description` as the value too, like `"97 'a'"` (first arg for `CreateJObject<>`).

Instead, we can use the char as the value in `CreateJObjectForChar`, like:

```csharp
            char charValue = Convert.ToChar(value);
            var description = $"{value} '{charValue}'";
            return CreateJObject<char>(charValue, "symbol", description, true);
```

And here, you will have the character available as the value.

Do confirm that the visible values in chrome, and VS are still correct.

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 2]
```diff
@@ -231,6 +231,13 @@ private string ConvertJSToCSharpLocalVariableAssignment(string idName, JToken va
...
+                         valueRet = $"\"{str}\"";
+                         typeRet = "string";
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:238]: and these should be using char type

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs (hunk 1 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs]: It is correct, I left TSymbol only for delegates and made a separate one, dedicated for chars only.

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 3]
```diff
@@ -224,13 +224,19 @@ private string ConvertJSToCSharpLocalVariableAssignment(string idName, JToken va
                 switch (type)
                 {
                     case "string":
-                    {
+                        {
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:227]: indent

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs (hunk 1 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs]: We can't use `type=char` for the json object. The allowed types are dictated by https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-RemoteObject

So, on the proxy side you would have to do like I suggested. And on the tests side, you can have a `TChar` but one that checks for `symbol`.

The `T*` methods on the tests side are just to make it easier to match the json objects.

File: src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs [hunk 4]
```diff
@@ -323,10 +323,10 @@ internal async Task CheckString(JToken locals, string name, string value)
             await CheckValue(l["value"], TString(value), name);
         }
 
-        internal async Task<JToken> CheckSymbol(JToken locals, string name, string value)
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:326]: Keep `CheckSymbol`.

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 5]
```diff
@@ -231,6 +231,12 @@ private string ConvertJSToCSharpLocalVariableAssignment(string idName, JToken va
                         typeRet = "string";
                         break;
                     }
+                    case "symbol":
+                     {
+                         valueRet = $"\'{value?.Value<char>()}\'";
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:236]: Does `'` need to be escaped?

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 6]
```diff
@@ -424,6 +430,8 @@ private static object ConvertCSharpToJSType(object v, Type type)
                 return new { type = "object", subtype = "null", className = type?.ToString(), description = type?.ToString() };
             if (v is string s)
                 return new { type = "string", value = s, description = s };
+            if (v is char c)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:433]: This method should be using the same methods to create these jobjects, as monosdbhelper. But it can be cleaned up in a follow up PR.

**Review by radical — APPROVED** [review]
Looks good, other than the comments.

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs (hunk 6 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:433]: Saved for later: https://github.com/dotnet/runtime/issues/66068
