### PR TITLE
vm: Improve getStringLiteral for dynamic context

### LINKED ISSUE #67956: Improve vm's getStringLiteral for dynamic context
See https://github.com/dotnet/runtime/blob/316797be40867a49466e1486fa402a9931554f55/src/coreclr/vm/jitinterface.cpp#L681-L684

Currently, it only returns string literal's length and doesn't return actual content - it makes it impossible for dynamically emitted code to benefit from https://github.com/dotnet/runtime/pull/65288 optimization. It's very important for compiled regexes (old-style Compiled flag) and should fix this https://github.com/dotnet/runtime/pull/65222#issuecomment-1095269315 regression
Most likely we need to change the signature to accept a buffer rather than returning it.

### PR DESCRIPTION
**Pull request by EgorBo**
Improve `getStringLiteral` API to return string content for dynamic context.

Closes https://github.com/dotnet/runtime/issues/67956
Fixes perf regression - https://github.com/dotnet/runtime/pull/65222#issuecomment-1095234487

### CODE REVIEW

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 1]
```diff
@@ -1875,12 +1875,17 @@ private bool isValidToken(CORINFO_MODULE_STRUCT_* module, uint metaTOK)
...
 
-        private char* getStringLiteral(CORINFO_MODULE_STRUCT_* module, uint metaTOK, ref int length)
+        private int getStringLiteral(CORINFO_MODULE_STRUCT_* module, uint metaTOK, char* buffer, int size)
         {
             MethodILScope methodIL = HandleToObject(module);
             string s = (string)methodIL.GetObject((int)metaTOK);
-            length = (int)s.Length;
-            return (char*)GetPin(s);
+
+            char* ptr = (char*)GetPin(s);
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:1883]: We don't need to pin the string if we're not returning the pointer.

File: src/coreclr/vm/jitinterface.cpp [hunk 2]
```diff
@@ -674,29 +675,31 @@ const char16_t* CEEInfo::getStringLiteral (
...
-        LPCWSTR pString;
-        if (!FAILED((module)->GetMDImport()->GetUserString(metaTOK, &dwCharCount, NULL, &pString)))
-        {
-            // For string.Empty pString will be null
-            *length = dwCharCount;
-            result = (const char16_t *)pString;
-        }
-        else
+        GCX_COOP();
+        STRINGREF strRef = GetDynamicResolver(moduleHnd)->GetStringLiteral(metaTOK);
```
Comment (EgorBo) [inline src/coreclr/vm/jitinterface.cpp:689]: @jkotas could you please take a look if anything catches your eye, I'm observing a crash on Linux-x64 (Debug) because of this DynamicScope (even if I return `-1` then) the questions are:
1) do I need to GCPROTECT/pin strRef here or it's fine due to GCX_COOP?
2) can a module be unloaded while I copy string? (or e.g. already unloaded by the time I reach this code)

File: src/coreclr/vm/ilstubresolver.cpp [hunk 3]
```diff
@@ -111,6 +111,13 @@ int ILStubResolver::GetStringLiteralLength(mdToken metaTok)
     return -1;
 }
 
+STRINGREF ILStubResolver::GetStringLiteral(mdToken metaTok)
+{
+    STANDARD_VM_CONTRACT;
```
Comment (jkotas) [inline src/coreclr/vm/ilstubresolver.cpp:116]:
```suggestion
    LIMITED_METHOD_CONTRACT;
```
Nit

File: src/coreclr/vm/jitinterface.cpp (hunk 2 above)
Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp:689]: I do not see anything wrong in this code.

> do I need to GCPROTECT/pin strRef here or it's fine due to GCX_COOP?

You do not need to.

> can a module be unloaded while I copy string? (or e.g. already unloaded by the time I reach this code)

No. The JIT compilation keep the whole thing alive.

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 4]
```diff
@@ -1875,12 +1875,21 @@ private bool isValidToken(CORINFO_MODULE_STRUCT_* module, uint metaTOK)
...
+        private int getStringLiteral(CORINFO_MODULE_STRUCT_* module, uint metaTOK, char* buffer, int size)
         {
+            Debug.Assert(size >= 0);
+
             MethodILScope methodIL = HandleToObject(module);
             string s = (string)methodIL.GetObject((int)metaTOK);
-            length = (int)s.Length;
-            return (char*)GetPin(s);
+
+            fixed (char* ptr = s)
```
Comment (jkotas) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:1885]: This can be `s.AsSpan(0, Math.Min(size, s.Length)).CopyTo(new Span<char>(buffer, size)))`

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 5]
```diff
@@ -1875,12 +1875,21 @@ private bool isValidToken(CORINFO_MODULE_STRUCT_* module, uint metaTOK)
...
+            {
+                for (int i = 0; i < Math.Min(size, s.Length); i++)
+                {
+                    buffer[i] = ptr[i];
+                }
+            }
+            return (int)s.Length;
```
Comment (jkotas) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:1892]:
```suggestion
            return s.Length;
```

File: src/coreclr/vm/jitinterface.cpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/vm/jitinterface.cpp:689]: Thanks!
It turns out the crash is a buffer overflow (reported as `stack smashing detected`) because I was using `* sizeof(wchar_t)` (which is 4 on that platform) instead of `* sizeof(char16_t)` 🤦‍♂️

File: src/coreclr/jit/gentree.cpp [hunk 6]
```diff
@@ -6957,8 +6957,9 @@ GenTreeIntCon* Compiler::gtNewStringLiteralLength(GenTreeStrCon* node)
         return gtNewIconNode(0);
     }
 
-    int             length = -1;
-    const char16_t* str    = info.compCompHnd->getStringLiteral(node->gtScpHnd, node->gtSconCPX, &length);
+    constexpr int maxStrSize      = 1024;
```
Comment (am11) [inline src/coreclr/jit/gentree.cpp:6960]: nit: this (and https://github.com/dotnet/runtime/blob/b5381bf/src/coreclr/jit/importer_vectorization.cpp#L148) can be just `const int`

**Comment by EgorBo** [comment]
@jkotas @MichalStrehovsky does it look good now?

File: src/coreclr/jit/gentree.cpp (hunk 6 above)
Comment (EgorBo) [reply src/coreclr/jit/gentree.cpp:6960]: Thanks! will change if there will be more change requests to avoid re-running CI just for a code-style change 🙂

File: src/coreclr/jit/gentree.cpp [hunk 7]
```diff
@@ -6957,8 +6957,9 @@ GenTreeIntCon* Compiler::gtNewStringLiteralLength(GenTreeStrCon* node)
...
+    char16_t      str[maxStrSize] = {};
```
Comment (jkotas) [inline src/coreclr/jit/gentree.cpp:6961]: Does `= {}` cause the buffer to be zero initialized? That is writing 2kB of zeros...

Comment (jkotas) [inline src/coreclr/jit/gentree.cpp:6961]: Also, you do not really need the string at all, so the buffer can just be `null` in this case.

File: src/coreclr/jit/gentree.cpp [hunk 8]
```diff
@@ -6957,8 +6957,9 @@ GenTreeIntCon* Compiler::gtNewStringLiteralLength(GenTreeStrCon* node)
...
+    int           length = info.compCompHnd->getStringLiteral(node->gtScpHnd, node->gtSconCPX, str, maxStrSize);
     if (length >= 0)
```
Comment (jkotas) [inline src/coreclr/jit/gentree.cpp:6963]: Does `JITDUMP("Folded '\"%ws\".Length' to '%d'\n", str, length)` need the buffer to be zero-terminated? I do not see anything zero terminating the string when it does not fit into the buffer.

File: src/coreclr/jit/gentree.cpp (hunk 7 above)
Comment (EgorBo) [reply src/coreclr/jit/gentree.cpp]: Yes, it's not needed

Comment (EgorBo) [reply src/coreclr/jit/gentree.cpp]: Removed and made buffer nullptr, since it's doesn't add a lot of value to dump it

File: src/coreclr/jit/gentree.cpp (hunk 8 above)
Comment (EgorBo) [reply src/coreclr/jit/gentree.cpp:6961]: Decided to remove %ws

File: src/coreclr/vm/dynamicmethod.h [hunk 9]
```diff
@@ -78,6 +78,7 @@ class DynamicResolver
     virtual OBJECTHANDLE ConstructStringLiteral(mdToken metaTok) = 0;
     virtual BOOL IsValidStringRef(mdToken metaTok) = 0;
     virtual int GetStringLiteralLength(mdToken metaTok) = 0;
```
Comment (jkotas) [inline src/coreclr/vm/dynamicmethod.h:80]: You have removed the only use of `GetStringLiteralLength` so it be deleted now.

File: src/coreclr/vm/jitinterface.cpp [hunk 10]
```diff
@@ -674,27 +675,35 @@ const char16_t* CEEInfo::getStringLiteral (
...
+        if (strRef != NULL)
         {
-            // For string.Empty pString will be null
-            *length = dwCharCount;
-            result = (const char16_t *)pString;
+            StringObject* strObj = STRINGREFToObject(strRef);
+            result = (int)strObj->GetStringLength();
+            if (buffer != NULL && bufferSize > 0)
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:694]:
```suggestion
            if (buffer != NULL)
```
Nit: It is not necessary to check for `bufferSize > 0` here.

File: src/coreclr/vm/jitinterface.cpp [hunk 11]
```diff
@@ -674,27 +675,35 @@ const char16_t* CEEInfo::getStringLiteral (
...
     Module* module = GetModule(moduleHnd);
 
-    const char16_t* result = nullptr;
+    _ASSERTE(bufferSize >= 0);
+
+    int result = -1;
 
     JIT_TO_EE_TRANSITION();
 
+    ULONG dwCharCount;
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:684]: Nit: The old version where `dwCharCount` and `pString` were right next to the call to `GetUserString` looked better.

File: src/coreclr/jit/importer_vectorization.cpp [hunk 12]
```diff
@@ -678,8 +680,8 @@ GenTree* Compiler::impStringEqualsOrStartsWith(bool startsWith, CORINFO_SIG_INFO
         needsNullcheck = false;
     }
 
-    int             cnsLength = -1;
-    const char16_t* str       = nullptr;
+    int      cnsLength = -1;
```
Comment (jkotas) [inline src/coreclr/jit/importer_vectorization.cpp:683]:
```suggestion
    int      cnsLength;
```

**Comment by jkotas** [comment]
LGTM otherwise

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 13]
```diff
@@ -1875,12 +1875,19 @@ private bool isValidToken(CORINFO_MODULE_STRUCT_* module, uint metaTOK)
...
         {
+            Debug.Assert(size >= 0);
+
             MethodILScope methodIL = HandleToObject(module);
-            string s = (string)methodIL.GetObject((int)metaTOK);
-            length = (int)s.Length;
-            return (char*)GetPin(s);
+            string str = (string)methodIL.GetObject((int)metaTOK);
+
+            if (buffer != null && size > 0)
```
Comment (jkotas) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:1885]:
```suggestion
            if (buffer != null)
```

File: src/coreclr/tools/superpmi/superpmi-shared/methodcontext.cpp [hunk 14]
```diff
@@ -4788,39 +4788,39 @@ void MethodContext::recGetStringLiteral(CORINFO_MODULE_HANDLE module, unsigned m
...
+        return -1;
     }
     else
     {
         DD value = GetStringLiteral->Get(key);
         DEBUG_REP(dmpGetStringLiteral(key, value));
-
-        *length = (int)value.A;
-        return (const char16_t*)GetStringLiteral->GetBuffer(value.B);
+        if (buffer != nullptr && bufferSize > 0)
```
Comment (jkotas) [inline src/coreclr/tools/superpmi/superpmi-shared/methodcontext.cpp:4819]:
```suggestion
        if (buffer != nullptr)
```

File: src/coreclr/vm/jitinterface.cpp [hunk 15]
```diff
@@ -674,27 +675,38 @@ const char16_t* CEEInfo::getStringLiteral (
...
-            // For string.Empty pString will be null
-            *length = dwCharCount;
-            result = (const char16_t *)pString;
-        }
-        else
-        {
-            *length = -1;
+            _ASSERTE(dwCharCount >= 0 && dwCharCount <= INT_MAX);
+            result = (int)dwCharCount;
+            if (buffer != NULL && bufferSize > 0)
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:706]:
```suggestion
            if (buffer != NULL)
```

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/jitinterface.cpp (hunk 15 above)
Comment (EgorBo) [reply src/coreclr/vm/jitinterface.cpp]: Thanks for applying these!

**Comment by dakersnar** [comment]
Windows x86 improvements: https://github.com/dotnet/perf-autofiling-issues/issues/4712
