### PR TITLE
Prefix exported symbols via UnmanagedCallersOnly attribute

### LINKED ISSUE #79491: Mono AOT compiler does not prefix exported UnmanagedCallersOnly symbols with underscore when targeting iOS
## Description
If a method is marked with `UnmanagedCallersOnlyAttribute` and a named export is specified via `EntryPoint` e.g.,
``` csharp
[UnmanagedCallersOnly(EntryPoint="exposed_managed_method")]
    public static int ManagedMethod() => 42;
```
Mono AOT compiler exports the symbols as-is without prefixing it with an `_` which is required on iOS platforms.
This results in failures when trying to load the symbol dynamically from the native code via:
``` c
void *del = dlsym (RTLD_DEFAULT, "exposed_managed_method");
```

## Repro
To reproduce, apply the following patch:
``` diff
diff --git a/src/mono/sample/iOS/Program.cs b/src/mono/sample/iOS/Program.cs
index 603ff2e4ebc..fbdc8032daa 100644
--- a/src/mono/sample/iOS/Program.cs
+++ b/src/mono/sample/iOS/Program.cs
@@ -24,6 +24,9 @@ private static void OnButtonClick()
         ios_set_text("OnButtonClick! #" + counter++);
     }
 
+    [UnmanagedCallersOnly(EntryPoint="exposed_managed_method")]
+    public static int ManagedMethod() => 42;
+
 #if CI_TEST
     public static async Task<int> Main(string[] args)
 #else
diff --git a/src/mono/sample/iOS/Program.csproj b/src/mono/sample/iOS/Program.csproj
index 0e6aa8777fa..f0187ba8f81 100644
--- a/src/mono/sample/iOS/Program.csproj
+++ b/src/mono/sample/iOS/Program.csproj
@@ -16,6 +16,10 @@
     <TrimMode>Link</TrimMode>
   </PropertyGroup>
 
+  <ItemGroup>
+    <TrimmerRootDescriptor Include="$(MSBuildThisFileDirectory)ILLink.Descriptors.xml" />
+  </ItemGroup>
+
   <PropertyGroup Condition="'$(TargetOS)' == 'MacCatalyst'">
     <DevTeamProvisioning Condition="'$(TargetOS)' == 'MacCatalyst' and '$(DevTeamProvisioning)' == ''">adhoc</DevTeamProvisioning>
     <EnableAppSandbox Condition="'$(EnableAppSandbox)' == ''">false</EnableAppSandbox>
@@ -79,6 +83,7 @@
         TargetOS="$(TargetOS)"
         Arch="$(TargetArchitecture)"
         ProjectName="$(AppName)"
+        NativeMainSource="$(MSBuildThisFileDirectory)/main.m"
         MonoRuntimeHeaders="$(MicrosoftNetCoreAppRuntimePackDir)runtimes\$(TargetOS.ToLower())-$(TargetArchitecture)\native\include\mono-2.0"
         Assemblies="@(BundleAssemblies)"
         MainLibraryFileName="Program.dll"
diff --git a/src/mono/sample/iOS/main.m b/src/mono/sample/iOS/main.m
index 0ab407e8398..e6d8a3f31f4 100644
--- a/src/mono/sample/iOS/main.m
+++ b/src/mono/sample/iOS/main.m
@@ -2,6 +2,7 @@
 // The .NET Foundation licenses this file to you under the MIT license.
 
 #import <UIKit/UIKit.h>
+#import <dlfcn.h>
 #import "runtime.h"
 
 @interface ViewController : UIViewController
@@ -45,6 +46,8 @@ void (*clickHandlerPtr)(void);
     [self.view addSubview:button];
 
     dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
+        void *del = dlsym (RTLD_DEFAULT, "exposed_managed_method");
+        NSAssert(del != NULL, @"'exposed_managed_method' not found");
         mono_ios_runtime_init ();
     });
 }

```

And add the `ILLink.Descriptors.xml` file to the project directory with the following contents:
``` xml
<linker>
  <!-- this is here to show how to configure the trimming -->
  <assembly fullname="Program">
    <type fullname="Program">
        <method name="ManagedMethod" />
    </type>
  </assembly>
</linker>
```

Finally, build it with:
``` bash
cd src/mono/sample/iOS
make build-appbundle MONO_ARCH=arm64 AOT=true DEPLOY_AND_RUN=true
```

## Workaround
Possible workaround is to prefix the EntryPoint name with the underscore, but then such code is not platform independent. 

/cc @mdh1418 @steveisok

### PR DESCRIPTION
**Pull request by ivanpovazan**
This PR includes the following:
- All symbols exported via EntryPoint of `UnmanagedCallersOnlyAttribute` **will be** prefixed with a required `_` on Apple platforms (as it is expected by the linker and dlsym)
- All symbols exported via undocumented (and legacy) ExportSymbol of `MonoPInvokeCallbackAttribute` **will not** be prefixed (in order to prevent breaking existing code)
- The change has been tested with the added functional test for iOS platforms

Fixes: https://github.com/dotnet/runtime/issues/79491

/cc: @steveisok @mdh1418 @lateralusX

### CODE REVIEW

**Comment by ivanpovazan** [comment]
I have two questions regarding this change:
1. Should this PR also cover handling of: https://github.com/dotnet/runtime/blob/main/src/mono/mono/mini/aot-compiler.c#L5203-L5212 
2. Should we add a functional test for apple devices which is testing this fix and the https://github.com/dotnet/runtime/pull/79424

File: src/mono/mono/mini/aot-compiler.c [hunk 1]
```diff
@@ -5243,9 +5243,16 @@ MONO_RESTORE_WARNING
 					if (decoded_args->named_args_info [j].field && !strcmp (decoded_args->named_args_info [j].field->name, "EntryPoint")) {
 						named = (const char *)decoded_args->named_args[j]->value.primitive;
 						slen = mono_metadata_decode_value (named, &named);
+#ifdef TARGET_MACH
```
Comment (lateralusX) [inline src/mono/mono/mini/aot-compiler.c:5246]: use acfg->user_symbol_prefix instead it will have the right prefix for exported symbols and no need to use ifdefs here.

Comment (lateralusX) [reply src/mono/mono/mini/aot-compiler.c:5246]: If you change the export_name to include the prefix, then you need to adjust g_string_append_printf (export_symbols, "%s%s\n", acfg->user_symbol_prefix, export_name);

**Comment by steveisok** [comment]
> 2. Should we add a functional test for apple devices which is testing this fix and the [[mono] Export unmanagedcallersonly method symbols #79424](https://github.com/dotnet/runtime/pull/79424)

Since iOS/tvOS doesn't run on PR's, it would be better to add a test for osx.

File: src/mono/mono/mini/aot-compiler.c (hunk 1 above)
Comment (ivanpovazan) [reply src/mono/mono/mini/aot-compiler.c]: Thank you, I have corrected the code based on your suggestions. 
Should we also cover handling of `MonoPInvokeCallbackAttribute` (I am not familiar of how exported symbols should be mangled in that case) ?

Comment (lateralusX) [reply src/mono/mono/mini/aot-compiler.c]: That is pretty old logic and its not documented as part of MonoPInvokeCallbackAttribute and I have personally not used it to export out native->managed wrappers. Looking through aot-compiler.c all other exports added to acfg->export_names now uses acfg->user_symbol_prefix, so for consistency, I believe we should do the same for this attribute.

Comment (vargaz) [reply src/mono/mono/mini/aot-compiler.c]: This might break existing code. Are we going to use MonoPInvokeCallbackAttribute in the future ?

**Comment by ivanpovazan** [comment]
> > 2. Should we add a functional test for apple devices which is testing this fix and the [[mono] Export unmanagedcallersonly method symbols #79424](https://github.com/dotnet/runtime/pull/79424)
> 
> Since iOS/tvOS doesn't run on PR's, it would be better to add a test for osx.


@steveisok, regarding your comment:

Afaik calling exported symbols is supposed to work only in full AOT mode, which makes the testing of this feature really specific.
I was thinking of adding it to the `src/tests/Interop/UnmanagedCallersOnly` runtime tests, but excluding its execution on other platforms or including it only in full AOT mode seems a bit impractical. 
Instead I have added a functional test case for this purpose.

Does that make sense?

--- 
Additionally, with this change I also had to adapt: https://github.com/ivanpovazan/runtime/blob/unmanagedcallersonly-mangling/src/mono/msbuild/apple/build/AppleApp.targets#L143
to enable functional test to have a custom native main. 
I can create a separate PR if you agree with this change.

File: src/mono/mono/mini/aot-compiler.c (hunk 1 above)
Comment (ivanpovazan) [reply src/mono/mono/mini/aot-compiler.c]: I am not familiar with how the `MonoPInvokeCallbackAttribute` supposed to work, but I was wondering if the existing native code is using this feature, then how did it work so far (if we consider that `dlsym`, for example, requires the exported symbols to be prefixed with underscore on Apple platforms)?

**Comment by ivanpovazan** [comment]
Failures are unrelated

**Comment by steveisok** [comment]
> Does that make sense?
> 
> Additionally, with this change I also had to adapt: https://github.com/ivanpovazan/runtime/blob/unmanagedcallersonly-mangling/src/mono/msbuild/apple/build/AppleApp.targets#L143 to enable functional test to have a custom native main. I can create a separate PR if you agree with this change.

Yeah, you're right in that we don't run many full aot legs.  I'm fine with it.

It looks like the tvOS run timed out.

**Comment by ivanpovazan** [comment]
Created a separate PR to enable specifying custom native main for functional tests: https://github.com/dotnet/runtime/pull/80546

File: src/mono/mono/mini/aot-compiler.c (hunk 1 above)
Comment (ivanpovazan) [reply src/mono/mono/mini/aot-compiler.c]: @lateralusX what do you think?

Comment (lateralusX) [reply src/mono/mono/mini/aot-compiler.c]: Not sure, `MonoPInvokeCallbackAttribute` has been around for 11 years, https://github.com/mono/mono/commit/928bd3ee2bc77f2fbd3e4fc1a21bc1ac68df0cfe, so even if `ExportSymbol` is not documented there is a risk that it has been used with a prefix on Apple platforms. It would also work in the static linking scenario where you, so if there is code using that, it will be broken as well. We have the same risk with `UnmanagedCallersOnlyAttribute` as well, since it has been released and used in code and might break as well with this change. One alternative could be to export the symbols twice on platforms that uses a prefix, to maintain backward compatibility and since the number of functions using these attributes and export symbol names should be fairly small and it only applies to some platforms, I don't think that would have to big of an impact. @vargaz do you think it would be an issue if we exported them using both old name as well as name with prefix on platforms that uses it?

Comment (ivanpovazan) [reply src/mono/mono/mini/aot-compiler.c]: If we take the approach of emitting both symbols, should both be added to the `exports file`?

Comment (lateralusX) [reply src/mono/mono/mini/aot-compiler.c]: No just the correct one, exports file is a new feature, so no backward combability issues with that one.

Comment (vargaz) [reply src/mono/mono/mini/aot-compiler.c]: I think since MonoPInvokeCallbackAttribute is not going to be used too much in the future, we shouldn't change its behavior, nobody reported a problem with the current one.

Comment (ivanpovazan) [reply src/mono/mono/mini/aot-compiler.c]: I can revert the change regarding `MonoPInvokeCallbackAttribute` and add a warning to the compiler instead, noting that the exported symbol is not prefixed in its case?

---

>We have the same risk with UnmanagedCallersOnlyAttribute as well 

Should we mark the PR with breaking change label then?

Comment (lateralusX) [reply src/mono/mono/mini/aot-compiler.c]: If decide to leave `MonoPInvokeCallbackAttribute` as is I don't think we need to do anything with it at all, its old, people lived with it for 11+ years and figured out how to get it to work in the process. If we should do anything then it would be to document that its deprecated in favor of `UnmanagedCallersOnlyAttribute`.

For the `UnmanagedCallersOnlyAttribute`, if we take a step back and look at the use cases from and end user perspective:

The user uses `UnmanagedCallersOnlyAttribute` to get a wrapper that can be called from native code, so it can be passed over to native code using pinvoke. There is also a way to give it a symbol name, meaning native code could get hold of the symbol and call it without need to go through managed code.

Lets assume:

```
[UnmanagedCallersOnly(EntryPoint = "MyTest")]
public static void MyTest()
{
...
}
```

A user could consume this entry point in two ways:

1. User compile the assembly into and obj file using -static aot argument, the user would then assume that he can use the symbol in an extern declare from a C source that is then statically linked with the obj. I assume this case should use the symbols name as is since its not exported from a shared library, just linked as a regular symbol and use as is from a C source file. User has something like this in a C source:

```
extern void MyTest (void);
...
MyTest ();
```

2. User compile the assembly into shared library (or into an obj that user intend to include in a shared library). In this case consumer of symbol will use dlsym to load the symbol using the given name, meaning it needs to use any platform prefix needed. User has something like this in a C source:

```
typedef void(*MyTestFunc)(void);
MyTestFunc MyTest = (MyTestFunc)dlsym(handle, "MyTest");
...
MyTest ();
```

So in order for us to support both scenarios, I believe we need to emit symbols supporting both use cases, meaning that we would need to emit two symbols on platform that needs prefix for symbols exported out from a shared library.

Comment (ivanpovazan) [reply src/mono/mono/mini/aot-compiler.c]: @lateralusX regarding your comment `1.` 
- If I create a `native.c`, add the example code you suggested, and build it with:
`clang -c native.c -o native.o`
- and inspect symbols with:
`nm native.o > syms.list`
- it will show the extern symbol with the underscore:
```
                 U _MyTest
0000000000000000 T _main
0000000000000000 t ltmp0
0000000000000030 s ltmp1
```
Which means that in both cases it is expected to have the underscore prefix. Am I possibly missing something?

---
Info about the toolchain used:
```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
Thread model: posix
InstalledDir: /Applications/Xcode_14.1.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Comment (lateralusX) [reply src/mono/mono/mini/aot-compiler.c]: You need to have our aot compiler create the symbol and then try to link using that object file to see if you even can link the static scenario using extern declared C function. It might not even work if toolchain will always decorate with _ even for the static scenario not just when exporting out of a shared library.

Comment (ivanpovazan) [reply src/mono/mono/mini/aot-compiler.c]: > You need to have our aot compiler create the symbol (since it will emit it without prefix) and then try to link using that object file to see if you even can link the static scenario using extern declared C function. It might not even work if toolchain will always decorate with _ even for the static scenario not just when exporting out of a shared library.

I tried the following: 
If I revert my change of decorating exported symbols with a prefix, and adapt the `main.m`, of the added functional test, to reference `exposed_managed_method` through a extern declared C function (instead of dynamically looking up the symbol) the build of the test fails with: 
```
Undefined symbols for architecture arm64:
  "_exposed_managed_method", referenced from:
      ___29-[ViewController viewDidLoad]_block_invoke in main.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
as the linker seems to expect that in the static scenario it also expects the symbol to be prefixed with the underscore. With my change the error goes away, the app can be built, run and the exposed managed method is properly invoked.

Comment (lateralusX) [reply src/mono/mono/mini/aot-compiler.c]: Thanks for looking into it. So then the symbol needs to be prefixed for both scenario (static, shared), that also means if any existing code would have this work in any scenario, then the user needed to manually have prefixed the symbol on Apple platforms.

Looks like this, https://github.com/lambdageek/dnne_monovm_sample/tree/main, does use UnmanagedCallersOnly with EntryPoint on Mono, curious how that scenarios works, since it sounds like it should have hit issues with unresolved symbols and I know the author is on OSX :), possible to take a quick look to see if that scenario gets broken with this change?

**Comment by ivanpovazan** [comment]
Mentioning: https://github.com/xamarin/xamarin-macios/issues/10470 for a reference

File: src/mono/mono/mini/aot-compiler.c (hunk 1 above)
Comment (ivanpovazan) [reply src/mono/mono/mini/aot-compiler.c]: > I assume that linking a shared library directly against application also expects symbols being exported with prefixed entrypoints?

I have tested this by:
1. Creating a HelloWorld console application which exposes:
``` csharp
[UnmanagedCallersOnly(EntryPoint="exposed_managed_method")]
public static int ManagedMethod() => 42;
```
2. FullAOT compiled the application as a shared library
3. Create a simple `main.c`:
``` c
int exposed_managed_method();

int main()
{
    const char *managed_argv [128];
    managed_argv[0] = "/Users/ivan/repos/runtime-mono-AOT/artifacts/bin/HelloWorld/arm64/Debug/osx-arm64/publish/HelloWorld.dll";
    int res;
    printf("hello from native");
    mono_jit_set_aot_mode (MONO_AOT_MODE_FULL);
    setenv("MONO_PATH", "/Users/ivan/repos/runtime-mono-AOT/artifacts/bin/HelloWorld/arm64/Debug/osx-arm64/publish", 1);
    MonoDomain *domain = mono_jit_init ("HelloWorld");
    const char* executable = "HelloWorld.dll";
    MonoAssembly *assembly = mono_assembly_open (executable, NULL);
    res = mono_jit_exec (mono_domain_get (), assembly, 1, managed_argv);
    printf("Invoking exposed method: %d", exposed_managed_method());
    return 0;
}
```
4. Compiled the native code with:
```
clang -I /Users/ivan/repos/runtime-mono-AOT/artifacts/bin/microsoft.netcore.app.runtime.osx-arm64/Debug/runtimes/osx-arm64/native/include/mono-2.0 \
main.c \
-force_load /Users/ivan/repos/runtime-mono-AOT/artifacts/obj/mono/osx.arm64.Debug/cross/mono/mini/libmonosgen-2.0.a \
-force_load libSystem.Native.a \
-lz \
HelloWorld.dll.dylib \
-framework Foundation \
-g \
-o main
```
5. The code properly runs and prints the desired output: `./main`
---
Conclusion: It seems that in all cases the symbol is expected to be prefixed with underscore

Comment (lateralusX) [reply src/mono/mono/mini/aot-compiler.c]: Excellent! Thanks for investigating!

**Review by lateralusX — APPROVED** [review]
LGTM!
