### PR TITLE
[interp] Add IL seq points

### LINKED ISSUE #51096: Fail StackTraceTests.ToString_ShowILOffset on mono interpreter mode
Relates to: https://github.com/dotnet/runtime/pull/44013

In mono interpreter mode, the StackFrame's ilOffset value is set to -1.
Because of this, the functionality of showing ilOffset in StackTrace when pdb is not present does not work.

### PR DESCRIPTION
**Pull request by BrzVlad**
Fixes https://github.com/dotnet/runtime/issues/51096

### CODE REVIEW

**Comment by BrzVlad** [comment]
@thaystg @vargaz  It seems we have some duplicated IL offset computations mechanisms in the runtime. During codegen we store iloffset/nativeoffset pairs in a line_number array which then gets saved in the debug info for a method. We also have the IL seq points that serve the same purpose, being saved in the `MonoJitMemoryManager->seq_points` hashtable. During stack trace computation, we use the IL seq points if we don't have debug information for the method. Is this something we want to refactor ?

**Review by vargaz — APPROVED** [review]

File: src/mono/mono/metadata/seq-points-data.c [hunk 1]
```diff
@@ -131,8 +131,10 @@ mono_seq_point_info_new (int len, gboolean alloc_data, guint8 *data, gboolean ha
 void
 mono_seq_point_info_free (gpointer ptr)
 {
+	printf ("Freeing seq point %p\n", ptr);
 	MonoSeqPointInfo* info = (MonoSeqPointInfo*) ptr;
 	g_free (info);
+	printf ("Freed seq point %p\n", ptr);
```
Comment (lambdageek) [inline src/mono/mono/metadata/seq-points-data.c:137]: debug printfs
