### PR TITLE
Stop passing GC types to P/Invokes in IL tests.

### LINKED ISSUE #35187: Test failure: Assertion failed '!"*** invalid IL: gc type passed to unmanaged call"'
failed in job: [runtime-coreclr outerloop 20200419.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=607697&view=ms.vss-test-web.build-test-results-tab&runId=19093176&resultId=107921&paneView=debug)

failed tests: 
JIT\\Directed\\IL\\PInvokeTail\\PInvokeTail\\PInvokeTail.cmd
JIT\\Directed\\pinning\\object-pin\\object-pin\\object-pin.cmd

Error message
~~~
Assert failure(PID 8824 [0x00002278], Thread: 7548 [0x1d7c]): Assertion failed '!"*** invalid IL: gc type passed to unmanaged call"' in '<Module>:?callputs1@@YAHXZ():int' during 'Importation' (IL size 13)
File: F:\workspace\_work\1\s\src\coreclr\src\jit\importer.cpp Line: 6750
Image: C:\h\w\B18E09BC\p\CoreRun.exe
Return code: 1
Raw output file: C:\h\w\B18E09BC\w\A94A0981\e\JIT\Directed\Reports\JIT.Directed\IL\PInvokeTail\PInvokeTail\PInvokeTail.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B18E09BC\p\corerun.exe" PInvokeTail.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B18E09BC\p
> C:\h\w\B18E09BC\w\A94A0981\e\JIT\Directed\IL\PInvokeTail\PInvokeTail\PInvokeTail.cmd
Expected: True
Actual: False


Stack trace
   at JIT_Directed._IL_PInvokeTail_PInvokeTail_PInvokeTail_._IL_PInvokeTail_PInvokeTail_PInvokeTail_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.Directed\JIT.Directed.XUnitWrapper.cs:line 23323
~~~

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #35187

This issue was caused by the assert added in #35026.

/cc @dotnet/jit-contrib @jkotas

### CODE REVIEW

File: src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il [hunk 1]
```diff
@@ -32,18 +32,20 @@
 {
   .maxstack  1
 
-  IL_0000:  ldstr bytearray(48 65 6C 6C 6F 20 57 6F 72 6C 64 21 00 00 00 00) //ldptr      D_00003000
-  IL_0005:  tail. call       int32 puts(int8*)
-  IL_000a:  ret
+    ldstr bytearray(48 65 6C 6C 6F 20 57 6F 72 6C 64 21 00 00 00 00) //ldptr      D_00003000
```
Comment (jkotas) [inline src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il:35]: Converting unpinned `System.String` to unmanaged pointer, without pinning, does not sound right. What is this test trying to do?

Comment (AaronRobinsonMSFT) [reply src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il:35]: No idea. I believe validate eliding the dispatch to the P/Invoke though a managed function via a tail call. I can update the test.

Comment (AaronRobinsonMSFT) [reply src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il:35]: Actually isn't the correct solution here to reference the static array at `D_00003000`? Sigh. I will look into what these tests are actually doing.

File: src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il [hunk 2]
```diff
@@ -28,78 +27,66 @@
...
-} // end of global method '?callputs2@@YAHXZ'
+    .maxstack 1
+    .locals init (char&)
+
+    ldstr bytearray(48 65 6C 6C 6F 20 57 6F 72 6C 64 21 00 00 00 00) // "Hello World!"
+    call instance char& modreq([mscorlib]System.Runtime.InteropServices.InAttribute) [mscorlib]System.String::GetPinnableReference()
+    stloc.0
+    ldloc.0
+    conv.i
+    tail. call int32 puts(int8*)
```
Comment (jkotas) [inline src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il:42]: This is still passing unpinned pointer into a PInvoke. It will have unpredictable behavior e.g. with GC stress if the string gets moved while the PInvoke is executing.

Comment (AaronRobinsonMSFT) [reply src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il:42]: Oops. Forgot the `pinned`. I was doing a bit of experimentation here trying to learn some IL.

File: src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il [hunk 3]
```diff
@@ -28,78 +27,66 @@
...
-} // end of global method '?callputs2@@YAHXZ'
+    .maxstack 1
+    .locals init (char& pinned)
+
+    ldstr bytearray(48 65 6C 6C 6F 20 57 6F 72 6C 64 21 00 00 00 00) // "Hello World!"
+    call instance char& modreq([mscorlib]System.Runtime.InteropServices.InAttribute) [mscorlib]System.String::GetPinnableReference()
+    stloc.0
+    ldloc.0
+    conv.i
+    tail. call int32 puts(int8*)
```
Comment (jkotas) [inline src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il:42]: Assuming that the JIT respects the `tail.` prefix here, the pointer won't be pinned - the pinning local will be out of scope due to tailcall.

Comment (AaronRobinsonMSFT) [reply src/coreclr/tests/src/JIT/Directed/IL/PInvokeTail/PInvokeTail.il:38]: Pinned the string in `main()` and passed in.

**Review by jkotas — APPROVED** [review]
