### PR TITLE
[mono] Make mono_inst_name less misleading

### LINKED ISSUE #83545: [mono] Make mono_inst_name less misleading
Currently `mono_inst_name` is defined like this:
```c
const char*
mono_inst_name (int op) {
#ifndef DISABLE_LOGGING
	if (op >= OP_LOAD && op <= OP_LAST)
		return (const char*)&opstr + opidx [op - OP_LOAD];
	if (op < OP_LOAD)
		return mono_opcode_name (op);
	g_error ("unknown opcode name for %d", op);
	return NULL;
#else
	g_error ("unknown opcode name for %d", op);
	g_assert_not_reached ();
#endif
}
```

The problem is that when logging is disabled, this function is uncallable (the `#else` branch, above).  Any call to it will crash the runtime.

On Android, iOS and WASM we build the runtime with `DISABLE_LOGGING` defined.  Below is Android, but wasm and ios are similar:

```xml
      <_MonoCMakeArgs Include="-DENABLE_MINIMAL=ssa,logging" />
```

Why this is bad:

If someone incorrectly leaves in a call to `mono_inst_name` in a branch that isn't guarded by `#ifndef DISABLE_LOGGING`, the runtime will crash.  We tend to use `mono_inst_name` in code that is trying to provide additional diagnostics.  So something bad has already happened, we try to gather more info, and instead we crash the runtime.

What we should do instead:

Wrap both the *declaration* and *definition* of `mono_inst_name` in `#ifndef DISABLE_LOGGING`.  Turn any use of `mono_inst_name` that isn't protected by `#ifndef DISABLE_LOGGING` into a compile-time error that will fail to build the runtime.

That way, we don't get random crashes during unrelated investigations just because we called some diagnostic functionality

### PR DESCRIPTION
**Pull request by sayeedkhannabil**
Fixes #83545

### CODE REVIEW

**Comment by SamMonoRT** [comment]
LGTM - we'll have to wait for another review too.

File: src/mono/mono/mini/helpers.c [hunk 1]
```diff
@@ -76,6 +76,7 @@ static const gint16 opidx [] = {
 #endif
 //#define ARCH_PREFIX "powerpc64-linux-gnu-"
 
+#ifndef DISABLE_LOGGING
```
Comment (ivanpovazan) [inline src/mono/mono/mini/helpers.c:79]: @sayeedkhannabil thanks for looking into this!

This looks good. However if we surround the function definition with `#ifndef DISABLE_LOGGING` then we do not need the check for the same preprocessor directive inside of its body, and the `#else` is not needed anymore. 

So I believe something like:
```c
#ifndef DISABLE_LOGGING
const char*
mono_inst_name (int op) {
	if (op >= OP_LOAD && op <= OP_LAST)
		return (const char*)&opstr + opidx [op - OP_LOAD];
	if (op < OP_LOAD)
		return mono_opcode_name (op);
	g_error ("unknown opcode name for %d", op);
	return NULL;
}
#endif
```
would be cleaner.

Comment (sayeedkhannabil) [reply src/mono/mono/mini/helpers.c:79]: @ivanpovazan thanks for the suggestion. I have updated it.

**Comment by ivanpovazan** [comment]
@sayeedkhannabil I ran the `runtime-extra-platforms` pipeline on the CI for you, since it verifies builds for mobile platforms. 
The failures seem related. 
Could you please check and try to fix the failures?
Let me know if you need help with that.

**Comment by sayeedkhannabil** [comment]
@ivanpovazan I am looking into the build failures. Is it possible to have a 15 minute chat about the runtime-extra-platforms errors? I am new to automated testing. If you can give me some guideline about this, it would be really great for me.

**Comment by ivanpovazan** [comment]
> @ivanpovazan I am looking into the build failures. Is it possible to have a 15 minute chat about the runtime-extra-platforms errors? I am new to automated testing. If you can give me some guideline about this, it would be really great for me.

Sure, you can reach me out on Discord. My Discord ID is: `ivanpovazan`

**Comment by ivanpovazan** [comment]
After our offline discussion I reran the failing pipeline since it expired and logs were removed from AzDO.
Here is the link to the build error which has some more information about the cause:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=401505&view=logs&j=67ac41de-1978-5f8d-a67a-2482e49b9998&t=f8ab5ad6-03e7-54dc-430a-d032bae40ebf&l=1334

To reach the full log you can follow these steps:
1. Get more information about the failing job:
Screenshot 2023-09-11 at 13 21 33

2. Check more details Azure Pipelines via:
Screenshot 2023-09-11 at 13 22 01

3. The previous step opens up the failed job: 
Screenshot 2023-09-11 at 13 23 36

4. By clicking on the failed step - `Build product` shows the build log with the error message:
Screenshot 2023-09-11 at 13 21 16

The error indicates there is an issue around `src/mono/mono/mini/mini.c:605:49`
Let me know if you need any help or/and if you have any additional questions with resolving the CI/CD errors.

File: src/mono/mono/mini/alias-analysis.c [hunk 2]
```diff
@@ -53,10 +53,13 @@ lower_load (MonoCompile *cfg, MonoInst *load, MonoInst *ldaddr)
 	}
 
 	if (replaced_op != load->opcode) {
-		if (cfg->verbose_level > 2)
+		if (cfg->verbose_level > 2) {
+			#ifndef DISABLE_LOGGING
 			printf ("Incompatible load type: expected %s but got %s\n",
```
Comment (vargaz) [inline src/mono/mono/mini/alias-analysis.c:58]: What is the purpose of these changes ? These are in the JIT, and not many users would disable logging and not disable the JIT.

Comment (sayeedkhannabil) [reply src/mono/mono/mini/alias-analysis.c:58]: Since wrapping the `mono_inst_name` function declaration and functiond definition created behavior such as `mono_inst_name` that isn't protected by `#ifndef DISABLE_LOGGING` into a compile-time error that will fail to build the runtime, I have wrapped `mono_inst_name` function call with `#ifndef DISABLE_LOGGING` so that the android build test doesn't fail. Without changing this in all files, the code was failing in runtime, since On Android, iOS and WASM we build the runtime with DISABLE_LOGGING defined.
https://github.com/dotnet/runtime/issues/83545#issue-1628193099

Comment (vargaz) [reply src/mono/mono/mini/alias-analysis.c:58]: Wouldn't be simpler to change the declaration in mini.h in one place ?

**Comment by sayeedkhannabil** [comment]
> Screenshot 2023-09-11 at 13 21 16

I have tried that. my first commit was with only changing the declarating and definition. which resulted to the above CI/CD fail: implicit declaration of the function mono_inst_name. However, wrapping the function call with DISABLE_LOGGING everywhere seemed to fix that implicit declaration of function error.

File: src/mono/mono/mini/alias-analysis.c (hunk 2 above)
Comment (sayeedkhannabil) [reply src/mono/mono/mini/alias-analysis.c:58]: > Screenshot 2023-09-11 at 13 21 16

I have tried that. my first commit was with only changing the declarating and definition. which resulted to the above CI/CD fail: implicit declaration of the function mono_inst_name. However, wrapping the function call with DISABLE_LOGGING everywhere seemed to fix that implicit declaration of function error.

Comment (ivanpovazan) [reply src/mono/mono/mini/alias-analysis.c:58]: @vargaz do you have a suggestion how this should be fixed?

Comment (ivanpovazan) [reply src/mono/mono/mini/alias-analysis.c:58]: My suggestion would be to change all the call sites to include:
```
#ifndef DISABLE_LOGGING
        // some call site
#else
	g_error ("unknown opcode name for %d", op);
	g_assert_not_reached ();
#endif
```
as we still want to assert and display some error message - but without details for logging.

@lambdageek what do you think?

Comment (vargaz) [reply src/mono/mono/mini/alias-analysis.c:58]: I think the original problem itself is not serious enough to warrant this amount of changes.

Comment (SamMonoRT) [reply src/mono/mono/mini/alias-analysis.c:58]: We are just starting the .NET9 cycle. I think it is fine to proceed with extensive changes. We should be mindful of performance implications if any.

Comment (sayeedkhannabil) [reply src/mono/mono/mini/alias-analysis.c:58]: > My suggestion would be to change all the call sites to include:
> 
> ```
> #ifndef DISABLE_LOGGING
>         // some call site
> #else
> 	g_error ("unknown opcode name for %d", op);
> 	g_assert_not_reached ();
> #endif
> ```
> 
> as we still want to assert and display some error message - but without details for logging.

should I implement this to see the changes? @ivanpovazan

File: src/mono/mono/mini/mini-amd64.c [hunk 3]
```diff
@@ -7600,13 +7600,17 @@ mono_arch_output_basic_block (MonoCompile *cfg, MonoBasicBlock *bb)
...
+			#endif
 			g_assert_not_reached ();
 		}
-
+		
+		#ifndef DISABLE_LOGGING
 		g_assertf ((code - cfg->native_code - offset) <= max_len,
 			   "wrong maximal instruction length of instruction %s (expected %d, got %d)",
 			   mono_inst_name (ins->opcode), max_len, (int)(code - cfg->native_code - offset));
+		#endif
```
Comment (akoeplinger) [inline src/mono/mono/mini/mini-amd64.c:7613]: this is removing the `g_assertf` completely so we'd be missing the check, which is not what we want.

File: src/mono/mono/mini/mini-codegen.c [hunk 4]
```diff
@@ -1243,7 +1258,9 @@ mono_local_regalloc (MonoCompile *cfg, MonoBasicBlock *bb)
 		spec_dest = spec [MONO_INST_DEST];
 
 		if (G_UNLIKELY (spec == (gpointer)/*FIXME*/MONO_ARCH_CPU_SPEC)) {
+			#ifndef DISABLE_LOGGING
 			g_error ("Opcode '%s' missing from machine description file.", mono_inst_name (ins->opcode));
+			#endif
```
Comment (akoeplinger) [inline src/mono/mono/mini/mini-codegen.c:1263]: same here and above, the `g_error` is important in this case.

File: src/mono/mono/mini/mini.c [hunk 5]
```diff
@@ -602,7 +602,9 @@ mono_decompose_op_imm (MonoCompile *cfg, MonoBasicBlock *bb, MonoInst *ins)
 	mono_bblock_insert_before_ins (bb, ins, temp);
 
 	if (opcode2 == -1)
+		#ifndef DISABLE_LOGGING
 		g_error ("mono_op_imm_to_op failed for %s\n", mono_inst_name (ins->opcode));
```
Comment (akoeplinger) [inline src/mono/mono/mini/mini.c:606]: and here

**Review by akoeplinger — CHANGES_REQUESTED** [review]
There are a couple changes that need to be fixed, though I'm still wondering why we don't instead change `mono_inst_name` to return the opcode number as a string in the DISABLE_LOGGING case so we don't need to change any callers

**Comment by ivanpovazan** [comment]
> There are a couple changes that need to be fixed, though I'm still wondering why we don't instead change `mono_inst_name` to return the opcode number as a string in the DISABLE_LOGGING case so we don't need to change any callers

That is a good point, although it got me thinking could we do something like this instead:
1. Use the current approach to find all the callers that are misusing the function i.e., calling it when logging is disabled
2. Change the function to have a single responsibility and remove different behaviours controlled by `DISABLE_LOGGING` feature switch - so it only converts opcode number to string
3. Change the problematic callers found in 1) to assert if needed and handle unknown opcode values ie when function returns NULL

File: src/mono/mono/mini/alias-analysis.c (hunk 2 above)
Comment (ivanpovazan) [reply src/mono/mono/mini/alias-analysis.c:58]: @sayeedkhannabil sorry for the delay, I would suggest implementing the requested changes and get all the CI checks to pass.

**Comment by akoeplinger** [comment]
> Change the problematic callers found in 1) to assert if needed and handle unknown opcode values ie when function returns NULL

Not sure what that would buy us since then you'd need to duplicate the handling logic in every caller.

**Comment by sayeedkhannabil** [comment]
Sorry for the late reply. @akoeplinger what would you suggest for this problem? Or should I implement what @ivanpovazan mentioned before?

**Comment by lambdageek** [comment]
> > There are a couple changes that need to be fixed, though I'm still wondering why we don't instead change `mono_inst_name` to return the opcode number as a string in the DISABLE_LOGGING case so we don't need to change any callers
> 
> That is a good point, although it got me thinking could we do something like this instead:
> 
> 1. Use the current approach to find all the callers that are misusing the function i.e., calling it when logging is disabled
> 2. Change the function to have a single responsibility and remove different behaviours controlled by `DISABLE_LOGGING` feature switch - so it only converts opcode number to string
> 3. Change the problematic callers found in 1) to assert if needed and handle unknown opcode values ie when function returns NULL

So one problem with changing `mono_inst_name` to always convert the number to a string is that currently `mono_inst_name` is non-allocating - it returns a predefined constant string for each opcode.  if we changed it to be allocating, we'd have to adjust all the call sites to clean up.

I took a look, and `mono_inst_name` is used everywhere in print statements of various forms.

So what about doing something like this: make a new printf specifier macro that is `"%s"` if logging is enabled, and otherwise `"%d"` (or `"0x%04x"` or something) if logging is disabled.  Concretely:

```c
// in mini.h

#ifndef DISABLE_LOGGING
#define M_PRI_INST "%s"
const char * mono_inst_name(int opcode);
#else
#define M_PRI_INST "%d"
static inline int
mono_inst_name(int opcode)
{
        return opcode;
}
#endif
```

and then for call sites, change them like this:

```diff
- g_assertf (op >= 0 && op < OP_LAST, "unknown opcode %s in function %s", mono_inst_name (op), __FUNCTION__);
+ g_assertf (op >= 0 && op < OP_LAST, "unknown opcode " M_PRI_INST " in function %s", mono_inst_name (op), __FUNCTION__);
```

That way we still get useful assertions or warnings, but if we disabled logging we'll just get a number instead of the opcode mnemonic.

**Review by lambdageek — COMMENTED** [review]
LGTM

**Review by lambdageek — APPROVED** [review]

**Review by steveisok — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]
I like this approach!
