### PR TITLE
Fix bug in String.Equals unrolling for certain single-char strings

### LINKED ISSUE #78169: Inconsistent behavior in NET7 String.Equals
### Description
NET7 String.Equals shows inconsistent behavior in differences of target platform bitness, and Release or Debug.

```cs
const String v1 = "鉄";
var v2 = v1;
Console.WriteLine($"{v1 == v2}, {v1.Equals(v2, StringComparison.Ordinal)}, {v1.Equals(v2,StringComparison.OrdinalIgnoreCase)}");

foreach (var _ in Array.Empty<Object>())
{
    //Do nothing
}
```
```
dotnet run -r win-x86 --no-self-contained -c Release
False, False, True

dotnet run -r win-x64 --no-self-contained -c Release
True, True, True

dotnet run -r win-x86 --no-self-contained -c Debug
True, True, True

dotnet run -r win-x64 --no-self-contained -c Debug
True, True, True
```
In addition, if you just comment out foreach, output will change.
```cs
const String v1 = "鉄";
var v2 = v1;
Console.WriteLine($"{v1 == v2}, {v1.Equals(v2, StringComparison.Ordinal)}, {v1.Equals(v2,StringComparison.OrdinalIgnoreCase)}");

// foreach (var _ in Array.Empty<Object>())
{
    //Do nothing
}
```
```
dotnet run -r win-x86 --no-self-contained -c Release
True, True, True
```

### Configuration
SDK 7.0.100
x86
Same behavior in local windows machine, Azure App Service (Windows)

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/78169 bug

For single-char strings with "signed" bit (e.g. `((ushort)'鉄') >> 15`) we used to do sign-extension instead of zero-extension 😞 
From my understanding, only single-char strings (length == 1) of certain two-bytes languages/symbols are affected (looks like mostly around CJK languages). Still, definitely needs to be backported to 7.0

### CODE REVIEW

File: src/tests/JIT/opt/Vectorization/StringEquals.cs [hunk 1]
```diff
@@ -195,10 +195,22 @@ static void ValidateEquals(bool result, string left, string right)
...
+    [MethodImpl(MethodImplOptions.NoInlining)] public static void Equals_161(string s) => ValidateEquals(s == "鉄鉄", s, "鉄鉄");
+    [MethodImpl(MethodImplOptions.NoInlining)] public static void Equals_162(string s) => ValidateEquals(s == "鉄鉄鉄", s, "鉄鉄鉄");
+    [MethodImpl(MethodImplOptions.NoInlining)] public static void Equals_163(string s) => ValidateEquals(s == "\uFFFF", s, "\uFFFF");
+    [MethodImpl(MethodImplOptions.NoInlining)] public static void Equals_164(string s) => ValidateEquals(s == "\uFFFF\uFFFF", s, "\uFFFF\uFFFF");
+    [MethodImpl(MethodImplOptions.NoInlining)] public static void Equals_165(string s) => ValidateEquals(s == "\uFFFF\uFFFF\uFFFF", s, "\uFFFF\uFFFF\uFFFF");
 
     public static readonly string[] s_TestData =
     {
         null,
+        "鉄",
```
Comment (danmoseley) [inline src/tests/JIT/opt/Vectorization/StringEquals.cs:208]: Coding guidelines I think say to always use ASCII, ie use \uNNNN to avoid accidental garbling later. I don't know whether we are actually consistent. But in this case it would perhaps be clearer.

**Comment by EgorBo** [comment]
@dotnet/jit-contrib @jakobbotsch PTAL, I'm going to backport it once merged

File: src/coreclr/jit/importervectorization.cpp [hunk 2]
```diff
@@ -380,15 +380,15 @@ GenTree* Compiler::impExpandHalfConstEqualsSWAR(
...
+        return impCreateCompareInd(data, TYP_USHORT, dataOffset, cns[0], cmpMode);
     }
     if (len == 2)
     {
         //   [ ch1 ][ ch2 ]
         //   [   value    ]
         //
         const UINT32 value = MAKEINT32(cns[0], cns[1]);
-        return impCreateCompareInd(data, TYP_INT, dataOffset, value, cmpMode);
+        return impCreateCompareInd(data, TYP_UINT, dataOffset, value, cmpMode);
```
Comment (SingleAccretion) [inline src/coreclr/jit/importervectorization.cpp:391]: Doesn't this end up creating `TYP_UINT` indirs aka invalid IR?

(Applies to a few cases below as well)

Comment (EgorBo) [reply src/coreclr/jit/importervectorization.cpp]: @SingleAccretion changed to cast node

File: src/coreclr/jit/importervectorization.cpp [hunk 3]
```diff
@@ -324,6 +324,11 @@ GenTree* Compiler::impCreateCompareInd(GenTreeLclVar*        obj,
     GenTree*  addOffsetTree = gtNewOperNode(GT_ADD, TYP_BYREF, obj, offsetTree);
     GenTree*  indirTree     = gtNewIndir(type, addOffsetTree);
 
+    if (varTypeIsSmall(indirTree))
+    {
+        indirTree = gtNewCastNode(actualType, indirTree, true, varTypeToUnsigned(type));
```
Comment (SingleAccretion) [inline src/coreclr/jit/importervectorization.cpp:329]: This will work, but it's kind of unnecessary, morph retype the `IND` and drop the cast. The original fix with the `USHORT` indir looked good.

File: src/coreclr/jit/importervectorization.cpp [hunk 4]
```diff
@@ -447,7 +452,7 @@ GenTree* Compiler::impExpandHalfConstEqualsSWAR(
             return nullptr;
         }
 
-        secondIndir = gtNewCastNode(TYP_LONG, secondIndir, true, TYP_LONG);
+        secondIndir = gtNewCastNode(TYP_LONG, secondIndir, true, TYP_ULONG);
```
Comment (SingleAccretion) [inline src/coreclr/jit/importervectorization.cpp:455]:
```suggestion
        secondIndir = gtNewCastNode(TYP_LONG, secondIndir, true, TYP_LONG);
```
(These two are the same)

Comment (EgorBo) [reply src/coreclr/jit/importervectorization.cpp:455]: ULONG looks clearer to me in terms of intention, but I assume it's better to keep it canonized

Comment (SingleAccretion) [reply src/coreclr/jit/importervectorization.cpp]: Yeah, well, doesn't really matter. One minor benefit is keeping the diff small.

File: src/coreclr/jit/importervectorization.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/jit/importervectorization.cpp]: But presumably it emits the same IR as other stuff in the importer, right? Changed to USHORT, thanks!

Comment (SingleAccretion) [reply src/coreclr/jit/importervectorization.cpp]: > But presumably it emits the same IR as other stuff in the importer, right?

Well, any IR is just IR. `USHORT` indirs are perfectly fine, `CAST<ushort>(IND<short>)` are also fine, one's just smaller.

File: src/tests/JIT/opt/Vectorization/StringEquals.cs (hunk 1 above)
Comment (am11) [reply src/tests/JIT/opt/Vectorization/StringEquals.cs]: There are some existing non-ASCII chars in this file:
https://gist.github.com/am11/dddd538ad08af8c914ba1144adf74263#file-stringequals-cs

Comment (EgorBo) [reply src/tests/JIT/opt/Vectorization/StringEquals.cs]: Thanks! Let's keep this PR smaller for easier/cleaner backport. @am11 feel free to file a PR to clean that up after

**Review by jakobbotsch — APPROVED** [review]

**Comment by EgorBo** [comment]
> CONFLICT (content): Merge conflict in src/coreclr/jit/importer_vectorization.cpp
Please backport manually!

*stares at @jakobbotsch*

**Comment by EgorBo** [comment]
SPMI failures are due to today's JIT-EE guid update

File: src/tests/JIT/opt/Vectorization/StringEquals.cs (hunk 1 above)
Comment (am11) [reply src/tests/JIT/opt/Vectorization/StringEquals.cs]: > feel free to file a PR to clean that up after

https://github.com/dotnet/runtime/pull/78265
