### PR TITLE
JIT: Do not report duplicate EH clauses to VM

### LINKED ISSUE #114891: Eliminate duplicate EH clauses in JIT
The duplicate EH clauses are no longer used by any runtime. CoreCLR stopped using them with new exception handling, and the legacy EH has been removed. NativeAOT never used them. We should just stop emitting them altogether.

https://github.com/dotnet/runtime/blob/8c3a2e15a63d1a7b2b54312b79f8a725ccdc2d4d/src/coreclr/jit/codegencommon.cpp#L2355-L2369

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #114891

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
LGTM. Thank you!

File: src/coreclr/jit/codegencommon.cpp [hunk 1]
```diff
@@ -2519,288 +2440,10 @@ void CodeGen::genReportEH()
...
-                }
-                else
-                {
-                    hndTyp = encTab->ebdTyp;
-                }
-
-                CORINFO_EH_CLAUSE_FLAGS flags = ToCORINFO_EH_CLAUSE_FLAGS(encTab->ebdHandlerType);
-
-                // Tell the VM this is an extra clause caused by moving funclets out of line.
-                flags = (CORINFO_EH_CLAUSE_FLAGS)(flags | CORINFO_EH_CLAUSE_DUPLICATE);
```
Comment (jkotas) [inline src/coreclr/jit/codegencommon.cpp:2712]: Can we delete `CORINFO_EH_CLAUSE_DUPLICATE` as well?

Comment (filipnavara) [reply src/coreclr/jit/codegencommon.cpp:2712]: Probably yes. I will also mark the checks in VM for removal with next R2R version bump.

Comment (jkotas) [reply src/coreclr/jit/codegencommon.cpp:2712]: > I will also mark the checks in VM for removal with next R2R version bump.

I think you can just delete them. We have bumped R2R version enough times, so there is no risk of mix and match.

Comment (filipnavara) [reply src/coreclr/jit/codegencommon.cpp:2712]: Ok, done. (Hopefully it passes the build, I only checked on osx-arm64 this time.)

File: src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs [hunk 2]
```diff
@@ -620,7 +620,6 @@ public enum CORINFO_EH_CLAUSE_FLAGS
         CORINFO_EH_CLAUSE_FILTER = 0x0001, // If this bit is on, then this EH entry is for a filter
         CORINFO_EH_CLAUSE_FINALLY = 0x0002, // This clause is a finally clause
         CORINFO_EH_CLAUSE_FAULT = 0x0004, // This clause is a fault clause
-        CORINFO_EH_CLAUSE_DUPLICATED = 0x0008, // Duplicated clause. This clause was duplicated to a funclet which was pulled out of line
         CORINFO_EH_CLAUSE_SAMETRY = 0x0010, // This clause covers same try block as the previous one. (Used by NativeAOT ABI.)
```
Comment (filipnavara) [inline src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs:623]:
```suggestion
        CORINFO_EH_CLAUSE_SAMETRY = 0x0010, // This clause covers same try block as the previous one.
```

Not sure I want to restart the CI over this... it's used by CoreCLR too with new EH.

File: src/coreclr/inc/corinfo.h [hunk 3]
```diff
@@ -819,7 +819,6 @@ enum CORINFO_EH_CLAUSE_FLAGS
     CORINFO_EH_CLAUSE_FILTER    = 0x0001, // If this bit is on, then this EH entry is for a filter
     CORINFO_EH_CLAUSE_FINALLY   = 0x0002, // This clause is a finally clause
     CORINFO_EH_CLAUSE_FAULT     = 0x0004, // This clause is a fault clause
-    CORINFO_EH_CLAUSE_DUPLICATE = 0x0008, // Duplicated clause. This clause was duplicated to a funclet which was pulled out of line
     CORINFO_EH_CLAUSE_SAMETRY   = 0x0010, // This clause covers same try block as the previous one
```
Comment (BruceForstall) [inline src/coreclr/inc/corinfo.h:822]:
```suggestion
    CORINFO_EH_CLAUSE_SAMETRY   = 0x0008, // This clause covers same try block as the previous one
```
?

File: src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/EHInfo.cs [hunk 4]
```diff
@@ -25,7 +25,6 @@ public enum CorExceptionFlag
         COR_ILEXCEPTION_CLAUSE_FILTER = 0x0001,         // If this bit is on, then this EH entry is for a filter
         COR_ILEXCEPTION_CLAUSE_FINALLY = 0x0002,        // This clause is a finally clause
         COR_ILEXCEPTION_CLAUSE_FAULT = 0x0004,          // Fault clause (finally that is called on exception only)
-        COR_ILEXCEPTION_CLAUSE_DUPLICATED = 0x0008,     // duplicated clause. This clause was duplicated to a funclet which was pulled out of line
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/EHInfo.cs:28]: ILCompiler.Reflection.ReadyToRun is expected to be able to dump older versions. The changes in this file should be reverted.

**Review by BruceForstall — COMMENTED** [review]
I think you should update the JIT-EE GUID

**Comment by BruceForstall** [comment]
Also, update docs/design/coreclr/botr/clr-abi.md

File: src/coreclr/inc/corinfo.h (hunk 3 above)
Comment (filipnavara) [reply src/coreclr/inc/corinfo.h:822]: Not sure I want to renumber it. There's at least one place in VM which uses the numeric value... and at least two different enums covering the same set of values.

File: src/coreclr/inc/corinfo.h [hunk 5]
```diff
@@ -819,7 +819,6 @@ enum CORINFO_EH_CLAUSE_FLAGS
     CORINFO_EH_CLAUSE_FILTER    = 0x0001, // If this bit is on, then this EH entry is for a filter
     CORINFO_EH_CLAUSE_FINALLY   = 0x0002, // This clause is a finally clause
     CORINFO_EH_CLAUSE_FAULT     = 0x0004, // This clause is a fault clause
```
Comment (jkotas) [inline src/coreclr/inc/corinfo.h:821]:
```suggestion
    CORINFO_EH_CLAUSE_FAULT     = 0x0004, // This clause is a fault clause
    // UNUSED                                  = 0x0008,
```
Style nit: JIT/EE interface tends to keep unused bits explicit

File: src/coreclr/inc/corinfo.h (hunk 3 above)
Comment (jkotas) [reply src/coreclr/inc/corinfo.h:822]: `corinfo.h` is JIT/EE interface. It should be fine to renumber it here as long as you rev JIT/EE interface GUID.

**Comment by BruceForstall** [comment]
It looks like SOS in https://github.com/dotnet/diagnostics knows about dumping duplicated clauses. What is the compat story there? Does it need to run against older runtimes, or is it tightly bound to a runtime version? Does this limit changing corhdr.h/corinfo.h? @mikem8361

File: src/coreclr/inc/corinfo.h (hunk 3 above)
Comment (filipnavara) [reply src/coreclr/inc/corinfo.h:823]: I'd rather keep the enums in sync unless there's a specific need not to do so or performance benefit.

**Comment by filipnavara** [comment]
> I think you should update the JIT-EE GUID

Will do.

> Also, update docs/design/coreclr/botr/clr-abi.md

I removed the section for "duplicated clauses". There's another out-of-date section for "cloned finallys". Not sure how to reword it since it talks about JIT32, JIT64 and desktop CLR.

**Comment by filipnavara** [comment]
Keeping it as draft until we resolve the question about dotnet/diagnostics and updates to clr-abi.md.

File: src/coreclr/inc/corhdr.h [hunk 6]
```diff
@@ -1141,7 +1141,6 @@ typedef enum CorExceptionFlag                       // definitions for the Flags
     COR_ILEXCEPTION_CLAUSE_FILTER  = 0x0001,        // If this bit is on, then this EH entry is for a filter
     COR_ILEXCEPTION_CLAUSE_FINALLY = 0x0002,        // This clause is a finally clause
     COR_ILEXCEPTION_CLAUSE_FAULT = 0x0004,          // Fault clause (finally that is called on exception only)
-    COR_ILEXCEPTION_CLAUSE_DUPLICATED = 0x0008,     // duplicated clause. This clause was duplicated to a funclet which was pulled out of line
```
[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/inc/corhdr.h:1144]: The file is shared, but the value is not actually used. I think it is fine to delete it

**Comment by jkotas** [comment]
>  There's another out-of-date section for "cloned finallys". Not sure how to reword it since it talks about JIT32, JIT64 and desktop CLR.

Per the discussion in previous PR, it should be fine to delete everything that is not relevant to current main.

**Comment by filipnavara** [comment]
> It looks like SOS in https://github.com/dotnet/diagnostics knows about dumping duplicated clauses. What is the compat story there?

The code would continue to work but stop reporting the duplicate clauses and cloned finallys when running with newer runtime/DAC. I think that's fine since the runtime doesn't use the information so the value of reporting it is dubious at best. It's still useful for older runtimes.

I'd be happy to hear a second opinion though.

File: src/coreclr/inc/corhdr.h (hunk 6 above)
Comment (jkotas) [inline src/coreclr/inc/corhdr.h:1144]: Nit: You can delete `COR_ILEXCEPTION_CLAUSE_OFFSETLEN` and `COR_ILEXCEPTION_CLAUSE_DEPRECATED` above while you are on it.

File: src/coreclr/inc/corinfo.h (hunk 3 above)
Comment (jkotas) [reply src/coreclr/inc/corinfo.h:823]: Ok, it sounds like this is one of those places where JIT/EE interface definition leaks into the file formats and throughout the runtime. It is fine to keep it as is.

Comment (jkotas) [reply src/coreclr/inc/corinfo.h:823]: It would be nice to add a comment like "Keep values in sync with COR_ILEXCEPTION_CLAUSE flags" to point the coupling.

File: src/coreclr/inc/corhdr.h [hunk 7]
```diff
@@ -1136,12 +1136,9 @@ typedef struct IMAGE_COR_ILMETHOD_SECT_FAT
 typedef enum CorExceptionFlag                       // definitions for the Flags field below (for both big and small)
 {
     COR_ILEXCEPTION_CLAUSE_NONE,                    // This is a typed handler
-    COR_ILEXCEPTION_CLAUSE_OFFSETLEN = 0x0000,      // Deprecated
-    COR_ILEXCEPTION_CLAUSE_DEPRECATED = 0x0000,     // Deprecated
     COR_ILEXCEPTION_CLAUSE_FILTER  = 0x0001,        // If this bit is on, then this EH entry is for a filter
     COR_ILEXCEPTION_CLAUSE_FINALLY = 0x0002,        // This clause is a finally clause
     COR_ILEXCEPTION_CLAUSE_FAULT = 0x0004,          // Fault clause (finally that is called on exception only)
-    COR_ILEXCEPTION_CLAUSE_DUPLICATED = 0x0008,     // duplicated clause. This clause was duplicated to a funclet which was pulled out of line
 } CorExceptionFlag;
```
Comment (jkotas) [inline src/coreclr/inc/corhdr.h:1142]:
```suggestion
    COR_ILEXCEPTION_CLAUSE_DUPLICATED = 0x0008,     // Deprecated: Duplicated clause. This clause was duplicated to a funclet which was pulled out of line
    COR_ILEXCEPTION_CLAUSE_SAMETRY    = 0x0010,     // This clause covers same try block as the previous one
} CorExceptionFlag;
```

File: src/coreclr/inc/corinfo.h (hunk 3 above)
Comment (filipnavara) [reply src/coreclr/inc/corinfo.h:824]: Added the comment.

File: src/coreclr/inc/corhdr.h (hunk 7 above)
Comment (jkotas) [reply src/coreclr/inc/corhdr.h:1142]: And also change the one place in VM that uses hardcoded 0x10 to use `COR_ILEXCEPTION_CLAUSE_SAMETRY`

Comment (jkotas) [reply src/coreclr/inc/corhdr.h:1144]: I think we want to keep `COR_ILEXCEPTION_CLAUSE_DUPLICATED` here even through it is deprecated since it was part of the file format.

**Review by jkotas — APPROVED** [review]
Thank you!
