### PR TITLE
Update RegionInfo data and Fix RegionInfo.CurrentRegion on Windows

### LINKED ISSUE #32753: Region.TwoLetterISORegionName can return three numerical digits
On a Windows 10 system using a [customized locale](https://docs.microsoft.com/en-us/windows/win32/intl/custom-locales), `TwoLetterISORegionName` returns `"150"`. (RegionInfo also becomes unreliable for ascertaining accurate geographic region information, as needed for, say, GDPR purposes.)

# Environment
Windows 10 Version 1909 (18363.657) or Windows 10 Version 2004 (19569.1000) (pre-release)
.NET Framework 4.6.2 or .NET Core 3.1
Country: Netherlands
Regional format: English (Europe)
Short time: HH:mm tt
Long time: HH:mm:ss tt

# Samples
## .NET Framework BCL (sample1.cs)
```csharp
using System;
using System.IO;
using System.Globalization;

class A
{
  static void Main(string[] args)
  {
    Console.WriteLine(RegionInfo.CurrentRegion.TwoLetterISORegionName);
  }
}
```
1. `C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /out:sample1.exe sample1.cs`
2. Execute `sample1.exe`
3. Observe `150` output

## WinRT (sample2.cs)
```csharp
using System;
using System.IO;

class A
{
  static void Main(string[] args)
  {
    Console.WriteLine(new Windows.Globalization.GeographicRegion().CodeTwoLetter);
  }
}
```
1. `C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /out:sample2.exe /reference:"C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.16299.0\Windows.winmd" /reference:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Runtime.dll" sample2.cs`
2. Execute `sample2.exe`
3. Observe `NL` output

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #32753

Currently when running on Windows, the call of RegionInfo.CurrentRegion will return the region object matching CurrentCulture. Windows has different settings for the default region than the current culture. The good example is mentioned in the scenario in the attached issue which having current culture was set to `English (Europ)` and Country was set to `Netherland` and when getting CurrentRegion we return `159` because Europ doesn't have country code (because it is not a country). We suppose to return the region for `Netherland`. 
The change here is fixing this issue and updating the region data table too to reflect latest list of regions we have in the world.

### CODE REVIEW

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs [hunk 1]
```diff
@@ -133,6 +138,12 @@ internal static unsafe partial class Kernel32
         [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
         internal static extern int GetCalendarInfoEx(string? lpLocaleName, uint Calendar, IntPtr lpReserved, uint CalType, IntPtr lpCalData, int cchData, IntPtr lpValue);
 
+        [DllImport("kernel32.dll")]
+        internal static extern int GetUserGeoID(int geoClass);
+
+        [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
+        internal static unsafe extern int GetGeoInfoW(int location, int geoType, char *lpGeoData, int cchData, int LangId);
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: Nit: We do not have the  `W` suffix anywhere else in this file; and in most of the src/Interop.

I understand that `W` is a micro-optimization, but I think it is better to be consistent.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs [hunk 2]
```diff
@@ -714,5 +714,29 @@ internal bool IsReplacementCulture
                 return false;
             }
         }
+
+        internal static unsafe CultureData GetCurrentRegionData()
+        {
+            const int BUFF_LENGTH = 10;
+            char* geoIso2Letters = stackalloc char[BUFF_LENGTH];
```
Comment (jkotas) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs]: It would be better to use `Span<char>` and replace the uses of BUFF_LENGTH with .Length on the Span

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: I didn't have it in the first place but the pinvoke analyzer complained about till I added it.

File: src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs [hunk 3]
```diff
@@ -63,6 +66,19 @@ public void CurrentRegion()
             }
         }
 
+        [ConditionalFact(nameof(RegionInfoPropertyTests.IcuIsNotLoaded))]
+        public void TestCurrentRegion()
+        {
+            RegionInfo ri = RegionInfo.CurrentRegion;
+            CultureInfo.CurrentCulture.ClearCachedData(); // clear the current region cached data
```
Comment (stephentoub) [inline src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: Might this interact with other tests in any negative way? If memory serves, ClearCachedData mutates statics even though it's an instance method.

Comment (tarekgh) [reply src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: Yes, it mutates static values but if something else fails in other tests, that means we have a problem in the test or in the product.

Comment (stephentoub) [reply src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: Can you elaborate? What happens if, for example, this test runs concurrently with https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Globalization/tests/CultureInfo/CultureInfoAll.cs#L635? Might one of these fail because of the unexpected interaction? I'm wondering if this and any other tests might need to be isolated from each other.

Comment (tarekgh) [reply src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: It is possible the test you pointed at can fail. That test should run remotely as it is validating the cache itself. Any test code calling ClearCachedData should run fine except the test that validating the cache itself. I can change that test to execute remotely.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs (hunk 1 above)
Comment (jkotas) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: You can always tell PInvoke analyzer to shut up by adding the API to `PinvokeAnalyzerExceptionList.analyzerdata`

Can we just get rid of the pinvoke analyzer? I have not seen it helping at all ever. It is just something one has to fight with.

File: src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs (hunk 3 above)
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: I have changed the tests to execute remotely to avoid any possibility of failing.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: for now, I have added the API to the exception list and remove the 'W' from the name.

> Can we just get rid of the pinvoke analyzer? I have not seen it helping at all ever. It is just something one has to fight with.

The analyzer was useful to ensure we can use the Windows APIs that exist in all Windows SKU's and mainly the APIs allowed to use in .NET Native. I am not sure if this changed and we don't have to worry about that?

Comment (jkotas) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: We do not build .NET Native in master anymore, and Windows has relaxed the API restrictions for store quite a bit.

The one that we do support is Windows Nano. Windows Nano has number of APIs stubbed out, so the existence of the API tells you nothing whether the feature works. Testing is the only way to find out for sure.

File: src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs [hunk 4]
```diff
@@ -52,7 +52,10 @@ public void Ctor_InvalidName_ThrowsArgumentException(string name)
             AssertExtensions.Throws<ArgumentException>("name", () => new RegionInfo(name));
         }
 
-        [Fact]
+        private static bool IcuIsNotLoaded => PlatformDetection.ICUVersion.Equals(new Version(0, 0, 0, 0));
+        private static bool IcuIsLoaded =>  !IcuIsNotLoaded;
```
Comment (jkotas) [inline src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]:
```suggestion
        private static bool IcuIsLoaded => !IcuIsNotLoaded;
```

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: I have logged the issue https://github.com/dotnet/runtime/issues/33867 to track removing the analyzer.

**Comment by tarekgh** [comment]
I logged the issue https://github.com/dotnet/runtime/issues/33875 to track Mono's failures in the CI.

**Comment by tarekgh** [comment]
@jkotas @stephentoub please let me know if you have any more feedback or we ok to merge. the failures in the CI are unrelated and tracked with other linked issues.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs [hunk 5]
```diff
@@ -133,6 +138,12 @@ internal static unsafe partial class Kernel32
         [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
         internal static extern int GetCalendarInfoEx(string? lpLocaleName, uint Calendar, IntPtr lpReserved, uint CalType, IntPtr lpCalData, int cchData, IntPtr lpValue);
 
+        [DllImport("kernel32.dll")]
+        internal static extern int GetUserGeoID(int geoClass);
+
+        [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
+        internal static extern int GetGeoInfo(int location, int geoType, ref char lpGeoData, int cchData, int LangId);
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]:
```suggestion
        internal static extern int GetGeoInfo(int location, int geoType, char* lpGeoData, int cchData, int LangId);
```

File: src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs [hunk 6]
```diff
@@ -63,6 +66,21 @@ public void CurrentRegion()
             }
         }
 
+        [ConditionalFact(nameof(RegionInfoPropertyTests.IcuIsNotLoaded))]
```
Comment (jkotas) [inline src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: Is this really a ICU-specific test, or is more just a Windows-specific test?

Do you expect that the ICU option that @safern is working on is going to affect RegionInfo?

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs (hunk 5 above)
Comment (tarekgh) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: I had this in the first place and changed when you asked to use Span. otherwise the calling code will not be nice. I think either we keep using char* and not span in the calling code, or keeping the ref here. otherwise, I have to use other options like fixed or use Unsafe.AsPointer I think which I am not seeing it is worth doing that in this simple case.

File: src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs (hunk 6 above)
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: We have to do more changes for initializing CurrentCultures and Regions on Windows when using ICU. This need to be done in other PR's as part of @safern next steps.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs (hunk 5 above)
Comment (jkotas) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: What about something like this?
```
int geoIsoIdLength;

fixed (char* pGeoIso2Letters = geoIso2Letters)
{
    geoIsoIdLength = Interop.Kernel32.GetGeoInfo(geoId, Interop.Kernel32.GEO_ISO2, pGeoIsoIdLength, geoIso2Letters.Length, Interop.Kernel32.EN_LANG_ID);
}

if (geoIsoIdLength ...
```

Comment (jkotas) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: > I have to use other options like fixed

I do not see a problem with using fixed around an interop call. We do that in thousand other places libraries.

Comment (tarekgh) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: I don't like using fixed with stackalloc allocated buffer. if believe we should do it this way, I wouldn't mind.

Comment (stephentoub) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: What's the benefit here of stackalloc'ing into a span rather than into a ptr if we then turn around and immediately use fixed to get the pointer and do basically nothing else with the span?

File: src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs (hunk 6 above)
Comment (jkotas) [reply src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: Should the condition be just for Windows for now, and not talk about the ICU at all?

What you are saying, we will need to touch this code for ICU work anyway, so the future proofing does not help much.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs (hunk 5 above)
Comment (jkotas) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: Span gives you bounds checks for the string manipulations. I do not want do have another security even where one-time globalization initialization leads to buffer overrun.

Comment (stephentoub) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: > Span gives you bounds checks for the string manipulations.

The only string manipulation here is the subsequent Slice, and we're feeding into it the result of the GetGeoInfo call.  If GetGeoInfo was buggy and gave us a bad length, it could be buggy in other ways, such as having written all the way up to that bad length.

But if you think this adds meaningful safety, ok.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs [hunk 7]
```diff
@@ -714,5 +715,28 @@ internal bool IsReplacementCulture
...
+        {
+            Span<char> geoIso2Letters = stackalloc char[10];
+
+            int geoId = Interop.Kernel32.GetUserGeoID(Interop.Kernel32.GEOCLASS_NATION);
+            if (geoId != Interop.Kernel32.GEOID_NOT_AVAILABLE)
+            {
+                int geoIsoIdLength = Interop.Kernel32.GetGeoInfo(geoId, Interop.Kernel32.GEO_ISO2, ref MemoryMarshal.GetReference(geoIso2Letters), geoIso2Letters.Length, Interop.Kernel32.EN_LANG_ID);
+                if (geoIsoIdLength != 0)
+                {
+                    geoIsoIdLength -= geoIso2Letters[geoIsoIdLength - 1] == 0 ? 1 : 0; // handle null termination and exclude it.
```
Comment (danmosemsft) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs]: So sometimes it's null terminated and sometimes not? Why does it not return ERROR_INSUFFICIENT_BUFFER when it has no room to null terminate?

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs [hunk 8]
```diff
@@ -714,5 +715,28 @@ internal bool IsReplacementCulture
...
         }
+
+        internal static CultureData GetCurrentRegionData()
+        {
+            Span<char> geoIso2Letters = stackalloc char[10];
+
+            int geoId = Interop.Kernel32.GetUserGeoID(Interop.Kernel32.GEOCLASS_NATION);
+            if (geoId != Interop.Kernel32.GEOID_NOT_AVAILABLE)
+            {
+                int geoIsoIdLength = Interop.Kernel32.GetGeoInfo(geoId, Interop.Kernel32.GEO_ISO2, ref MemoryMarshal.GetReference(geoIso2Letters), geoIso2Letters.Length, Interop.Kernel32.EN_LANG_ID);
```
Comment (danmosemsft) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs]: for the last parameter docs say "Note   The application must set this parameter to 0 if GeoType has any value other than GEO_RFC1766 or GEO_LCID."
https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getgeoinfow

File: src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs (hunk 6 above)
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: I didn't use IsWindows because when Santi enables the first step we'll start failing as we'll be running on Windows and not doing the right initialization yet.

Comment (jkotas) [reply src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: Right, but I expect that we will have 100 other places with the same problem. All of them will need to be fixed, the "IsIcu" property will need to be moved into more central place, etc. So the code in this file will need to be redone anyway.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs (hunk 7 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs]: The doc is not ensuring we are returning null that is why I have to check to know if we got the null or not. 
We are requesting the 2-letters country code and I am providing a buffer of length 10 which is far enough to ensure not running into the ERROR_INSUFFICIENT_BUFFER case even with null.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs (hunk 8 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs]: we are using GEO_ISO2 and not GEO_RFC1766  nor GEO_LCID.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs (hunk 5 above)
Comment (tarekgh) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: I'll do what Jan suggested then and use `fixed` in the calling code.

File: src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs (hunk 6 above)
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/System/Globalization/RegionInfoTests.cs]: Ok, I'll change the condition to check Windows then as I am not feeling strongley about that either way.

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs [hunk 9]
```diff
@@ -40,6 +40,11 @@ internal static unsafe partial class Kernel32
 
         internal const uint TIME_NOSECONDS = 0x00000002;
 
+        internal const int GEOCLASS_NATION       = 16;
+        internal const int GEO_ISO2              =  4;
+        internal const int GEOID_NOT_AVAILABLE   = -1;
+        internal const int EN_LANG_ID            =  9;
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: Should this be `LANG_ENGLISH` ? I do not see `EN_LANG_ID` defined in the Windows SDK.

Comment (tarekgh) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.Globalization.cs]: I'll change this too.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs (hunk 8 above)
Comment (danmosemsft) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs]: Right, so LangId should be 0, but you're passing Interop.Kernel32.EN_LANG_ID ?

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs (hunk 7 above)
Comment (jkotas) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs]: From what I can tell, this is always returning zero terminated string.

Would it be best to create the string from the pointer and not bother with using the returned size? I would be fine with no using the Span in that case because of there is no buffer math that can go wrong.

```
char* pGeoIso2Letters = stackalloc char[10];

if (Interop.Kernel32.GetGeoInfo(..., pGeoIso2Letters, ...) != 0)
{
    CultureData? cd = GetCultureDataForRegion(new string(pGeoIso2Letters), ...
```

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs [hunk 10]
```diff
@@ -152,135 +152,262 @@ internal partial class CultureData
         /// </remarks>
         private static Dictionary<string, string> RegionNames =>
             s_regionNames ??=
-            new Dictionary<string, string>(211 /* prime */)
+            new Dictionary<string, string>(257 /* prime */)
```
Comment (danmosemsft) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs]: nit, I don't think there is any value in passing in a prime number - the dictionary internally rounds up to the next prime number from its list. it's harmless though of course.

Ideally the C# compiler would know that there's N entries coming in the initializer and pass in N to the constructor.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs (hunk 8 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs]: The doc kind confused me especially the second part of the following:

```
LangId

Identifier for the language, used with the value of Location. The application can set this parameter to 0, with GEO_RFC1766 or GEO_LCID specified for GeoType. This setting causes the function to retrieve the language identifier by calling GetUserDefaultLangID.
```

I'll change it to 0.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs (hunk 7 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs]: I would be more conservative checking null as the doc didn't ensure that and I am not sure what happen if we run on a different version of Windows.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs (hunk 10 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs]: I'll keep it as it is harmless and I am not sure what the C# initializer how it behaves there.

**Review by jkotas — APPROVED** [review]
Thanks

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs (hunk 10 above)
Comment (danmosemsft) [reply src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs]: fine, fyi the initializer always uses the parameterless constructor, so it is a valid microoptmization to pass a size here.
