### PR TITLE
Initial gcdump support

### LINKED ISSUE #88491: NativeAOT app crashes when run on a machine with an ETW session with GCHeapDump and Type keywords enabled
1. Start an ETW session, enabling the .NET runtime provider with GCHeapDump and Type keywords
    - For example, collect with PerfView and set additional providers to `Microsoft-Windows-DotNETRuntime:GCHeapDumpKeyword|TypeKeyword:Verbose`
2. Run a nativeaot app that has `<EventSourceSupport>true</EventSourceSupport>` and does a GC (explicit call or otherwise)
   - The ETW session is for the machine, so regardless of whether whoever started the session cares about the nativeaot app, the app is affected.

App crashes trying to get the type manager from a method table. The runtime is trying to use the `GCStaticEEType` method table, which is intentionally not fully populated.
```
> helloworld.exe!TypeManagerHandle::AsTypeManager() Line 105
  helloworld.exe!BulkTypeEventLogger::LogSingleType(MethodTable * pEEType) Line 252
  helloworld.exe!BulkTypeEventLogger::LogTypeAndParameters(unsigned __int64 thAsAddr, ETW::TypeSystemLog::TypeLogBehavior typeLogBehavior) Line 54
  helloworld.exe!ETW::TypeSystemLog::LogTypeAndParametersIfNecessary(BulkTypeEventLogger * pLogger, unsigned __int64 thAsAddr, ETW::TypeSystemLog::TypeLogBehavior typeLogBehavior) Line 357
  helloworld.exe!ETW::GCLog::ObjectReference(ProfilerWalkHeapContext * profilerWalkHeapContext, Object * pObjReferenceSource, unsigned __int64 typeID, unsigned __int64 cRefs, Object * * rgObjReferenceTargets) Line 1046
  helloworld.exe!HeapWalkHelper(Object * pBO, void * pvContext) Line 188
  helloworld.exe!WKS::gc_heap::walk_heap_per_heap(bool(*)(Object *, void *) fn, void * context, int gen_number, int walk_large_object_heap_p) Line 51537
  helloworld.exe!WKS::gc_heap::walk_heap(bool(*)(Object *, void *) fn, void * context, int gen_number, int walk_large_object_heap_p) Line 51563
  helloworld.exe!WKS::GCHeap::DiagWalkHeap(bool(*)(Object *, void *) fn, void * context, int gen_number, bool walk_large_object_heap_p) Line 51617
  helloworld.exe!GCProfileWalkHeapWorker(int fShouldWalkHeapRootsForEtw, int fShouldWalkHeapObjectsForEtw) Line 897
  helloworld.exe!GCProfileWalkHeap() Line 927
  helloworld.exe!GCToEEInterface::DiagGCEnd(unsigned __int64 index, int gen, int reason, bool fConcurrent) Line 955
  helloworld.exe!WKS::gc_heap::do_post_gc() Line 49754
```

cc @LakshanF

### PR DESCRIPTION
**Pull request by LakshanF**
Support for `gcdump `with `GCBulkNode`, `GCBulkEdge`, `GCBulkRootEdge`, `TypeBulkType `events
 - GCBulkRootStaticVar is not supported yet
 - Requires client time symbol lookup for Types since native AOT doesn't carry metadata.
 - Fixes #88491

### CODE REVIEW

File: src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp [hunk 1]
```diff
@@ -295,8 +282,13 @@ int BulkTypeEventLogger::LogSingleType(MethodTable * pEEType)
     // Determine this MethodTable's module.
     RuntimeInstance * pRuntimeInstance = GetRuntimeInstance();
 
-    ULONGLONG osModuleHandle = (ULONGLONG) pEEType->GetTypeManagerPtr()->AsTypeManager()->GetOsModuleHandle();
-
+    // There can be invalid pEETypes where EETypeElementType is ElementType_Unknown and accessing the TypeManager can cause problems
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp:285]: Where do these invalid EETypes come from?

Comment (LakshanF) [reply src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp:285]: I'm not sure.

The symbols for these are like: `__GCStaticEEType_NNN` (where NNN is like 010, 001). 

`ElementType_Unknown` is the only common trait I found to distinguish although `m_usNumVtableSlots`, `m_usNumInterfaces`, `GetHashCode`() tend to be very large (0xfff0, 0xffff, 0xffffffff) but not consistent. 

Using DIA's `findSymbolByRVAEx` gives the following information for these addresses,

```
Displacement = 0x0
                        SymIndex:        0x1
                          SymTag:        0x5
                            Name:        __GCStaticEEType_010
                   LexicalParent:        00000245432CA850
                            Type:        00000245432CA850
                    LocationType:        0x1
                  AddressSection:        0x3
                   AddressOffset:        0xC0D00
          RelativeVirtualAddress:        0x6FBD00
                  VirtualAddress:        0x6FBD00
                          Length:        0x28
                 LexicalParentId:        0x2
                          TypeId:        0x3
                 UndecoratedName:        __GCStaticEEType_010
                        NoReturn:        false
  uses custom calling convention:        false
                        NoInline:        false
   debug info for optimized code:        false
                     Unreachable:        false
           return from interrupt:        false
                      far return:        false
           frame pointer present:        false

Function       : static, [006FBD00][0003:000C0D00], len = 00000028, __GCStaticEEType_010
                 Function attribute:
                 Function info:
FuncDebugStart :   static, [006FBD00][0003:000C0D00]
FuncDebugEnd   :   static, [006FBD28][0003:000C0D28]

```

Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp:285]: These are EETypes for the GC statics.

Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp:285]:
```suggestion
    // EEType for GC statics are not fully populated and they do not have a valid TypeManager. We will identify them by checking for `ElementType_Unknown`.
```

File: src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp [hunk 2]
```diff
@@ -69,64 +68,53 @@ void BulkTypeEventLogger::FireBulkTypeEvent()
...
-            &(m_rgBulkTypeValues[iTypeData].cTypeParameters),
-            sizeof(m_rgBulkTypeValues[iTypeData].cTypeParameters));
+        DWORD cTypeParams = target.cTypeParameters;
+        ULONG *ptrInt = (ULONG*)(m_pBulkTypeEventBuffer + iSize);
+        *ptrInt = cTypeParams;
+        iSize += 4;
 
         // Type parameter array
-        if (m_rgBulkTypeValues[iTypeData].cTypeParameters > 0)
+        if (cTypeParams == 1)
```
Comment (elinor-fung) [inline src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp:105]: Are the comments in eventtracepriv.h about `cTypeParameters` still accurate?
https://github.com/dotnet/runtime/blob/2a9c80b799c55cba30c755d60042a6acb30aa37f/src/coreclr/nativeaot/Runtime/eventtracepriv.h#L118-L122

File: src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp [hunk 3]
```diff
@@ -69,64 +68,53 @@ void BulkTypeEventLogger::FireBulkTypeEvent()
...
+        else
         {
-            _ASSERTE(iDesc < _countof(EventData));
-            EventDataDescCreate(
-                &EventData[iDesc++],
-                ((m_rgBulkTypeValues[iTypeData].cTypeParameters == 1) ?
-                    &(m_rgBulkTypeValues[iTypeData].ullSingleTypeParameter) :
-                    (ULONGLONG*)(m_rgBulkTypeValues[iTypeData].rgTypeParameters)),
-                sizeof(ULONGLONG) * m_rgBulkTypeValues[iTypeData].cTypeParameters);
+            memcpy(m_pBulkTypeEventBuffer + iSize, target.rgTypeParameters.GetValue(), sizeof(ULONGLONG) * cTypeParams);
```
Comment (elinor-fung) [inline src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp:112]: Where does `rgTypeParameters` actually get updated? I'm missing where anything actually appends to it.

File: src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp [hunk 4]
```diff
@@ -69,64 +68,53 @@ void BulkTypeEventLogger::FireBulkTypeEvent()
...
+        iSize += 4;
 
         // Type parameter array
-        if (m_rgBulkTypeValues[iTypeData].cTypeParameters > 0)
+        if (cTypeParams == 1)
+        {
+            memcpy(m_pBulkTypeEventBuffer + iSize, &target.ullSingleTypeParameter, sizeof(ULONGLONG) * cTypeParams);
+            iSize += sizeof(ULONGLONG) * cTypeParams;
+        }
+        else
```
[the remark this answers is not in the document]
Comment (LakshanF) [reply src/coreclr/nativeaot/Runtime/eventtrace_bulktype.cpp]: Removed the case for `cTypeParams > 1`

File: src/coreclr/nativeaot/Runtime/eventtracepriv.h [hunk 5]
```diff
@@ -114,18 +114,9 @@ class BulkTypeValue
...
-    // have a reliable place to copy it from.  This is filled in at the last minute,
-    // when sending the event.
     ULONG cTypeParameters;
 
-    // If > 1 type parameter, this is an array of their MethodTable*'s
-    NewArrayHolder<ULONGLONG> rgTypeParameters;
-
-    // If exactly one type parameter, this is its MethodTable*.  (If != 1 type parameter,
-    // this is 0.)
+    // We only expect one type parameter
```
Comment (elinor-fung) [inline src/coreclr/nativeaot/Runtime/eventtracepriv.h:119]: Maybe point at the explanation in BulkTypeEventLogger::LogSingleType or include the gist of it here?

**Review by elinor-fung — APPROVED** [review]
