### PR TITLE
HTTP/3: Header encoding and decoding fixes

### LINKED ISSUE #46263: [HTTP/3] Error when reading trailing headers (unit tests)
If a HTTP/3 response has trailing headers then HttpClient throws an error in the QPACK decoder when decoding the trailers. I believe the cause is HttpClient is not resetting `QPackDecoder` state back to its initial value after parsing the response headers.

https://github.com/dotnet/runtime/blob/9277301b727bbf5d362656611a90bd36800d1935/src/libraries/Common/src/System/Net/Http/aspnetcore/Http3/QPack/QPackDecoder.cs#L111

When the decoder runs for the second time for a response, the state should be `RequiredInsertCount`. It is actually is `CompressedHeaders`.

@scalablecory

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/runtime/issues/46263

Also, encoding status code 500 was failing in Kestrel.

Tests that verify are part of https://github.com/dotnet/aspnetcore/pull/28763 and https://github.com/dotnet/aspnetcore/pull/28940

### CODE REVIEW

File: src/libraries/Common/src/System/Net/Http/aspnetcore/Http3/QPack/QPackEncoder.cs [hunk 1]
```diff
@@ -477,9 +477,8 @@ private int EncodeStatusCode(int statusCode, Span<byte> buffer)
                 case 400:
                 case 404:
                 case 500:
-                    // TODO this isn't safe, some index can be larger than 64. Encoded here!
-                    buffer[0] = (byte)(0xC0 | H3StaticTable.StatusIndex[statusCode]);
-                    return 1;
+                    EncodeStaticIndexedHeaderField(H3StaticTable.StatusIndex[statusCode], buffer, out var bytesWritten);
+                    return bytesWritten;
```
Comment (scalablecory) [inline src/libraries/Common/src/System/Net/Http/aspnetcore/Http3/QPack/QPackEncoder.cs:481]: Can we keep single byte write for those statuses that are still a single byte? Should be faster for those.

**Review by scalablecory — COMMENTED** [review]
Looks good, small optimization suggestion.

**Review by jkotalik — APPROVED** [review]

File: src/libraries/Common/src/System/Net/Http/aspnetcore/Http3/QPack/QPackEncoder.cs (hunk 1 above)
Comment (JamesNK) [reply src/libraries/Common/src/System/Net/Http/aspnetcore/Http3/QPack/QPackEncoder.cs:481]: This is only called once per request. I'll leave it as-is because I don't want to micro-optimize too much. Will revisit header encoding/decoding later when focusing on perf.
