### PR TITLE
Avoid exception when parsing AD path for port number

### LINKED ISSUE #109858: System.DirectoryServices.AccountManagement Version 9.0: UserPrincipal.GetAuthorizationGroups() throws  System.UriFormatException: Invalid URI: The hostname could not be parsed.
### Description

After updating from 8.0.1 to 9.0.0 the call above throws the following exception:
 System.UriFormatException: Invalid URI: The hostname could not be parsed.

### Reproduction Steps
```
var ctx = new PrincipalContext(ContextType.Domain);
var usersearcher = new PrincipalSearcher(new UserPrincipal(ctx));
var users = usersearcher.FindAll().Cast<UserPrincipal>();
var user = users.FirstOrDefault(e => e.SamAccountName == "valid user name");
var groupList = user?.GetAuthorizationGroups().ToList(); <== throws in 9.0.0
```

### Expected behavior

This call should return the groups as the older versions

### Actual behavior

Throws unexpected exception

### Regression?

Yes. worked in 8.0.1

### Known Workarounds

downgrade to 8.0.1

### Configuration

.NET 8.0 and .NET 9.0 on Windows 11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by steveharter**
Fixes https://github.com/dotnet/runtime/issues/109858

This will need to be ported to v9

We don't have automated tests for this; can @kumarravik78c or @jay98014 verify.

Regression in v9 from https://github.com/dotnet/runtime/pull/89787

### CODE REVIEW

**Comment by kumarravik78c** [comment]
@steveharter no we do not have any test around this code.

**Review by kumarravik78c — APPROVED** [review]

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs [hunk 1]
```diff
@@ -2418,12 +2421,22 @@ protected virtual void LoadDomainInfo()
...
+                else if (string.Equals(ldapUri.Scheme, "LDAPS", StringComparison.OrdinalIgnoreCase))
+                {
+                    port = LdapsDefaultPort;
+                }
+            }
 
             string dnsDomainName = "";
 
-            using (DirectoryEntry rootDse = new DirectoryEntry("LDAP://" + this.dnsHostName + ":" + port + "/rootDse", "", "", AuthenticationTypes.Anonymous))
+            using (DirectoryEntry rootDse = new DirectoryEntry($"LDAP://{this.dnsHostName}:{port}/rootDse", "", "", AuthenticationTypes.Anonymous))
```
Comment (ericstj) [inline src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs:2439]: I know it wasn't a reported problem, but double checking we are OK to add the default port values here when not specified by the user?  Was that an important part of the original fix?

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs [hunk 2]
```diff
@@ -2418,12 +2421,22 @@ protected virtual void LoadDomainInfo()
...
-            Uri ldapUri = new Uri(this.ctxBase.Path);
-            int port = ldapUri.Port != -1 ? ldapUri.Port : (ldapUri.Scheme.ToUpperInvariant() == "LDAPS" ? 636 : 389);
+            int port = LdapDefaultPort;
+            if (Uri.TryCreate(ctxBase.Path, UriKind.Absolute, out Uri ldapUri))
+            {
+                if (ldapUri.Port != -1)
+                {
+                    port = ldapUri.Port;
+                }
+                else if (string.Equals(ldapUri.Scheme, "LDAPS", StringComparison.OrdinalIgnoreCase))
```
Comment (ericstj) [inline src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs:2431]: Another issue from the original PR - it seems odd to me that we ignore this scheme and instead use LDAP below with a port.  Do you know if that's intentional?

**Review by ericstj — COMMENTED** [review]
Since the original PR regressed I wanted to give a bit more scrutiny. @kumarravik78c or @jay98014 Can you please have a look at my comments and let me know what you think?  We need you expertise here.  Thanks!

**Comment by steveharter** [comment]
PTAL @JasonDebug

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs (hunk 1 above)
Comment (kumarravik78c) [reply src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs:2439]: Since this code only interacts with a dc it is safe to use default ports, ie., 389 for regular LDAP and 636 for secure version of it.

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs (hunk 2 above)
Comment (steveharter) [reply src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs:2431]: i.e. should we use "LDAPS://" below when `ldapUri.Scheme == "LDAPS"`? Would the connection bel secure \ encrypted just because it's on the LDAPS port even though "LDAP://" is used?

Comment (kumarravik78c) [reply src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs:2431]: It has been like this from day one. After digging a little deeper and talking with my team, I found out that LDAPS is not valid provider name supported. Hence it uses LDAP as the supported provider name. This allows the user to call the api with LDAPS and the api in turn uses the ssl port(636) along with the supported provider name which LDAP. This is a less strict way to call the api and allow ssl port. Other way would not allow LDAPS at all which might break a lot of applications.

**Review by ericstj — APPROVED** [review]
Thank you for the additional information, @kumarravik78c
