### PR TITLE
[HTTP/3] Reenabled ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream

### LINKED ISSUE #53087: [HTTP/3] ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream test fails
## System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3_MsQuic.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream

For argument `chunked` with value `false` or `null` intermittently fails with:
```
Assert.Equal() Failure\nExpected: 104\nActual:   0
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass27_0.<<ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream>b__0>d.MoveNext() in /home/manicka/Repositories/runtime/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:line 959
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /home/manicka/Repositories/runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 63
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /home/manicka/Repositories/runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 82
   at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /home/manicka/Repositories/runtime/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs:line 36
--- End of stack trace from previous location ---
   at System.Net.Test.Common.Http3LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options) in /home/manicka/Repositories/runtime/src/libraries/Common/tests/System/Net/Http/Http3LoopbackServer.cs:line 97
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream(Nullable`1 chunked) in /home/manicka/Repositories/runtime/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:line 898
--- End of stack trace from previous location ---
```

Might be related to: https://github.com/dotnet/runtime/issues/52047

### PR DESCRIPTION
**Pull request by ManickaP**
Fixes #53087

I ran 10_000 tight loops locally without an issue.

### CODE REVIEW

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs [hunk 1]
```diff
@@ -1151,6 +1145,11 @@ public async Task ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream(boo
                             await connection.SendResponseBodyAsync("hello world");
                             break;
                     }
+
+                    if (connection is Http3LoopbackConnection http3Connection)
+                    {
+                        await http3Connection.WaitForClientDisconnectAsync();
```
Comment (CarnaViire) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1151]: Just wondering if it's the same kind of a workaround we would have to add for https://github.com/dotnet/runtime/issues/57779?

**Review by CarnaViire — APPROVED** [review]
LGTM

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs (hunk 1 above)
Comment (geoffkizer) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1151]: I wonder if we should just add this to the HTTP3 version of AcceptConnectionAsync.

Comment (ManickaP) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1151]: Yes, it's the same workaround. 

I tried to add it into `AcceptConnectionAsync` to make it more generic/future proof, but it caused timeouts in cancellation tests, so I scoped it to this particular test.

Side note: I think that the reason was that they dispose client one level higher then the server. Thus, the client connection is never closed before server needs to finish. Leading me to a conclusion that adding some generic solution might not be possible or at least won't be easy :cry:

Comment (ManickaP) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1151]: Ha @geoffkizer I didn't notice your comment before posting mine. I tried that, it cause timeouts elsewhere.

Comment (geoffkizer) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1151]: If it's only a handful of cancellation tests that failed, it might make more sense to update those tests to work with this than to update all the other tests to call WaitForClientDisconnectAsync.

Cancellation tests are tricky anyway; I'd rather be modifying them to be more robust than modifying a bunch of more straightforward tests...

Do you remember which cancellation tests failed?

Comment (ManickaP) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1151]: I'll have to retry. I think that the number of test instances was high but that it was just 2 or 3 test methods repeated for different inputs.
So do not merge on my behalf, I'll retry tomorrow and either try to fix those or report back how much of them it was.

Comment (geoffkizer) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1151]: Another option would be to actually initiate server shutdown here by sending a GOAWAY, then call WaitForClientDisconnectAsync. This is probably better behavior, but more involved.

Comment (geoffkizer) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:1151]: I posted a PR to do the graceful shutdown in AcceptConnectionAsync -- https://github.com/dotnet/runtime/pull/58088. Feedback welcome.

We should discuss if we want to take that PR or not.
