### PR TITLE
Check CancellationToken before TimeSpan in TimeProviderTaskExtensions

### LINKED ISSUE #106996: Down-level TimeProviderTaskExtensions CancellationToken behavior is inconsistent with Task
### Description

When using `TimeProviderTaskExtensions` from down-level runtimes, the Delay method which accepts a `CancellationToken` behaves inconsistently with the equivalent `Task.Delay` overload. `Task.Delay` checks `CancellationToken.IsCancellationRequested` first, whereas `TimeProviderTaskExtensions.Delay` checks the timeout for `TimeSpan.Zero` first. This means if the method is passed a zero timeout and an already canceled `CancellationToken`, `Task.Delay` returns `Task.FromCanceled` whereas `TimeProviderTaskExtensions.Delay` returns `Task.CompletedTask`.

https://github.com/dotnet/runtime/blob/fb8e078b5e24ea7ebffde7b62c6e2975f8765951/src/libraries/Microsoft.Bcl.TimeProvider/src/System/Threading/Tasks/TimeProviderTaskExtensions.cs#L69-L77

https://github.com/dotnet/runtime/blob/9a31a5b47aa7484bec71ba28aa59712c7898b902/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L5725-L5729

The same problem also affects `TimeProviderTaskExtensions.WaitAsync`.

https://github.com/dotnet/runtime/blob/9a31a5b47aa7484bec71ba28aa59712c7898b902/src/libraries/Microsoft.Bcl.TimeProvider/src/System/Threading/Tasks/TimeProviderTaskExtensions.cs#L164-L172

https://github.com/dotnet/runtime/blob/9a31a5b47aa7484bec71ba28aa59712c7898b902/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L2837-L2845

### Reproduction Steps

Target .NET < 8.0 (such as 4.6.2) and use a non-system time provider.

```cs
using var cts = new CancellationTokenSource();
cts.Cancel();

await new FakeTimeProvider().Delay(TimeSpan.Zero, cts.Token);
```

and

```cs
var tcs = new TaskCompletionSource<object>();

using var cts = new CancellationTokenSource();
cts.Cancel();

await tcs.WaitAsync(TimeSpan.Zero, new FakeTimeProvider(), cts.Token);
```

### Expected behavior

The examples above should throw `OperationCanceledException` o for consistency, otherwise library authors converting their code to use `TimeProvider` may encounter unexpected behaviors.

### Actual behavior

The `Delay` example above completes without an exception, the `WaitAsync` example throws `TimeoutException`.

### Regression?

This is not a regression

### Known Workarounds

Call `CancellationToken.ThrowIfCancellationRequested()` manually before calling `Delay` or `WaitAsync`. However, there is still a slim chance of a race condition in this case.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by brantburnett**
This makes the down-level behavior for Delay and WaitAsync match the behavior in .NET 8 and later, prefering to return a Canceled task over a Completed task or TimeoutException when the TimeSpan is Zero and the CancellationToken is already Canceled.

Fixes #106996

### CODE REVIEW

File: src/libraries/Common/tests/System/TimeProviderTests.cs [hunk 1]
```diff
@@ -316,12 +316,26 @@ public static void RunDelayTests(TimeProvider provider, ITestTaskFactory taskFac
...
+            // This should complete quickly with a CANCELED status.
+            Task task3 = taskFactory.Delay(provider, new TimeSpan(0), new CancellationToken(true));
+            try
+            {
+                var e = Assert.Throws<AggregateException>(task3.Wait);
+                Assert.IsAssignableFrom<OperationCanceledException>(e.InnerException);
+            }
+            catch (Exception e)
+            {
+                Assert.Fail(string.Format("RunDelayTests:    > FAILED.  Unexpected exception on canceled task Wait(): {0}", e));
```
Comment (tarekgh) [inline src/libraries/Common/tests/System/TimeProviderTests.cs:328]: nit: use interpolated string `$"..."` instead of string.Format

File: src/libraries/Common/tests/System/TimeProviderTests.cs [hunk 2]
```diff
@@ -316,12 +316,26 @@ public static void RunDelayTests(TimeProvider provider, ITestTaskFactory taskFac
...
             Assert.True(task2.Status == TaskStatus.RanToCompletion, "    > FAILED.  Expected Delay(TimeSpan(0), timeProvider, uncanceledToken) to run to completion");
 
+            // This should complete quickly with a CANCELED status.
+            Task task3 = taskFactory.Delay(provider, new TimeSpan(0), new CancellationToken(true));
+            try
+            {
+                var e = Assert.Throws<AggregateException>(task3.Wait);
+                Assert.IsAssignableFrom<OperationCanceledException>(e.InnerException);
+            }
+            catch (Exception e)
```
Comment (tarekgh) [inline src/libraries/Common/tests/System/TimeProviderTests.cs:326]: do we need the try-catch at all? shouldn't `var e = Assert.Throws<AggregateException>(task3.Wait);` will validate the thrown exception and will fail if got different exception? did you try that?

File: src/libraries/Common/tests/System/TimeProviderTests.cs (hunk 1 above)
Comment (brantburnett) [reply src/libraries/Common/tests/System/TimeProviderTests.cs:328]: I agree, I was just trying to be consistent with the rest of this test, I wasn't sure what the current guidelines are, I assumed "stay consistent on a per file basis". Would you prefer that I change all the `string.Format` cases in this test? Or the file?

File: src/libraries/Common/tests/System/TimeProviderTests.cs (hunk 2 above)
Comment (brantburnett) [reply src/libraries/Common/tests/System/TimeProviderTests.cs:326]: This was also just to remain consistent with the rest of the test, which is converting thrown exceptions into an `Assert.Fail` with a specific message. I presume this is because a single test method is testing multiple cases and it helps to identify which case failed in logs. However, you are correct, with the exception of more detailed logging, the Asserts alone are sufficient and the `try..catch` is not required. Happy to implement this whatever way you feel is best.

File: src/libraries/Common/tests/System/TimeProviderTests.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/Common/tests/System/TimeProviderTests.cs:328]: Changing it in the file will be ok.

File: src/libraries/Common/tests/System/TimeProviderTests.cs (hunk 2 above)
Comment (tarekgh) [reply src/libraries/Common/tests/System/TimeProviderTests.cs:326]: The other try-catch in the file is not using `Assert.Throws` inside the try block. If you prefer to assert with a good message, you may consider using `Record.Exception` instead. here is example of that https://github.com/dotnet/runtime/blob/959c10e41f1180482a7bc25e2bba16d27aca343a/src/libraries/System.Data.Odbc/tests/ReaderTests.cs#L28.

File: src/libraries/Common/tests/System/TimeProviderTests.cs (hunk 1 above)
Comment (brantburnett) [reply src/libraries/Common/tests/System/TimeProviderTests.cs]: Done, it was really only two spots so I feel a bit silly now. 😄

**Review by stephentoub — APPROVED** [review]

**Comment by tarekgh** [comment]
Thanks @brantburnett for your help with this change.
