### PR TITLE
Fix parsing of embedded .clsidmap in comhost

### LINKED ISSUE #39954: regsvr32 comhost.dll  in .NET5 doesn't work
when trying a simple .net5 COM server by following the tutorial [https://docs.microsoft.com/en-us/dotnet/core/native-interop/expose-components-to-com](url) ,Nothing happens after running"regsvr32 ComSample.comhost.dll".There isnt any item created in the Registry.
sdk version 5.0.100-preview.7.20366.6
code file
```
using System;
using System.Runtime.InteropServices;

namespace ComSample
{
    [ComVisible(true)]
    [Guid("54677FE2-061D-4F4D-9F41-E61163BF8D89")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IComServer
    {
        string Print();
    }

    [ComVisible(true)]
    [Guid("B94CB39C-7497-42CA-812C-8E34C23BB57F")]
    public class ComServer : IComServer
    {
        public string Print()
        {
            return "ComSample.ComServer in " + Environment.Version.ToString();
        }
    }
}
```
 project file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <EnableComHosting>true</EnableComHosting>
  </PropertyGroup>
</Project>
```
Build succeeded, no warning or error.
Regsvr32 doesnt display a dialog box which presents success message.
```
PS I:\Temp\comsample\comsample> dotnet build                                                                            
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored I:\Temp\comsample\comsample\ComSample.csproj (in 60 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  ComSample -> I:\Temp\comsample\comsample\bin\Debug\net5.0\ComSample.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.86
PS I:\Temp\comsample\comsample> cd .\bin\Debug\net5.0\                                                                  
PS I:\Temp\comsample\comsample\bin\Debug\net5.0> ls                                                                     

    目录: I:\Temp\comsample\comsample\bin\Debug\net5.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2020/7/27     16:25         183808 ComSample.comhost.dll
-a----        2020/7/27     16:25            419 ComSample.deps.json
-a----        2020/7/27     16:25           4608 ComSample.dll
-a----        2020/7/27     16:25           9452 ComSample.pdb
-a----        2020/7/27     16:25            210 ComSample.runtimeconfig.dev.json
-a----        2020/7/27     16:25            201 ComSample.runtimeconfig.json


PS I:\Temp\comsample\comsample\bin\Debug\net5.0> regsvr32 .\ComSample.comhost.dll                                       
PS I:\Temp\comsample\comsample\bin\Debug\net5.0>   
```
Besides, trying the sample [https://github.com/dotnet/samples/tree/master/core/extensions/COMServerDemo](url) in .NET5 ,I have run into the same problem.

### PR DESCRIPTION
**Pull request by elinor-fung**
`comhost` is crashing during registration. `json_parser_t::parse_stream` is using `seekg`/`tellg` to find the size of the stream. For the embedded .clsidmap, the stream buffer did not override / implement everything, so those functions would error out. We didn't check for error, so we would just use the invalid size and AV.

- Switch to operating on raw data and size for embedded .clsidmap instead of creating a stream
- Fold `json_parser_t::parse_stream` into `json_parser_t::parse_file` and check for error when getting the size of the stream
- Make tests use HostModel to create a comhost with an embedded .clsidmap instead of using a loose file

Fixes #39954

cc @AaronRobinsonMSFT @jkoritzinsky @vitek-karas

### CODE REVIEW

File: src/installer/corehost/cli/json_parser.cpp [hunk 1]
```diff
@@ -74,7 +74,7 @@ void json_parser_t::realloc_buffer(size_t size)
     m_json[size] = '\0';
 }
 
-bool json_parser_t::parse_json(char* data, int64_t size, const pal::string_t& context)
+bool json_parser_t::parse_raw_data(char* data, int64_t size, const pal::string_t& context)
 {
     constexpr auto flags = rapidjson::ParseFlag::kParseStopWhenDoneFlag | rapidjson::ParseFlag::kParseCommentsFlag;
```
Comment (AaronRobinsonMSFT) [inline src/installer/corehost/cli/json_parser.cpp:79]: Please assert that `data` isn't `nullptr` here. Unless `m_document` is our code.

File: src/installer/corehost/cli/json_parser.cpp [hunk 2]
```diff
@@ -145,13 +125,33 @@ bool json_parser_t::parse_file(const pal::string_t& path)
...
+        trace::error(_X("Cannot use file for resource [%s]: %s"), path.c_str(), pal::strerror(errno));
+        return false;
+    }
+
+    auto current_pos = ::get_utf8_bom_length(file);
+    file.seekg(0, file.end);
+    auto stream_size = file.tellg();
+    if (stream_size == -1)
+    {
+        trace::error(_X("Failed to get size of resource [%s]"), path.c_str());
```
Comment (AaronRobinsonMSFT) [inline src/installer/corehost/cli/json_parser.cpp:145]: ~~resource~~ -> file

?

**Review by AaronRobinsonMSFT — APPROVED** [review]
