### PR TITLE
Make case insensitive matches respect case insensitivity on the root.

### LINKED ISSUE #119117: Microsoft.Extensions.FileSystemGlobbing.Matcher does not respect case insensitivity in root when using an InMemoryDirectoryInfo;
### Description

When using a root and the `InMemoryDirectoryInfo` to match files, the root is always matched case sensitively instead of respecting the configuration of the `Matcher`.

### Reproduction Steps

This example program...
```csharp
using Microsoft.Extensions.FileSystemGlobbing;

Matcher matcher = new(StringComparison.OrdinalIgnoreCase);
matcher.AddInclude(@"this\casing\");

foreach (var stem in
         matcher.Match(
             @"C:\root\dir\casing\",
             [
                 @"C:\root\dir\casing\this\casing\MatchingCase",
                 @"C:\root\dir\casing\this\CASING\PathMismatchingCase",
                 @"C:\root\dir\CASING\this\casing\RootMismatchingCase",
                 @"C:\root\dir\CASING\this\CASING\BothMismatchingCase"
             ]
         ).Files.Select(filePatternMatch => filePatternMatch.Stem))
{
    Console.WriteLine(stem);
}
```
...outputs...
```
MatchingCase
PathMismatchingCase
```

because those are the only two options where the case of the root matches. This is unexpected because the `Matcher` is constructed with a `StringComparison.OrdinalIgnoreCase` comparison.

### Expected behavior

If a `Matcher` is configured with a specific case sensitivity, that case sensitivity should also apply to roots.

### Actual behavior

No matter the case sensitivity parameter, roots are always case sensitive.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

I think the offending line is [here](https://github.com/dotnet/runtime/blob/a139bfe6cf327b43b7c749179321a2fa83e105ea/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L124).

The most obvious solution would be for the comparison to be passed to the `InMemoryDirectoryInfo` created in the `Match` call by adding a constructor that takes it. Then using that to match roots in the `InMemoryDirectoryInfo`.

### PR DESCRIPTION
**Pull request by MitchBodmer**
This change addresses #119117 by making the `Matcher` match root directories case-insensitively when the Matcher is configured to be case-insensitive.

I'm not exactly sure this is the right way to go about this so I'm very open to feedback. The tack I took was to try to limit breaking changes while also fixing the bug.

One problem I hit was that the offending method on the `Matcher` is actually an extension method. That means it does not have access to the private `StringComparison` type on the matcher it is extending. I chose to make it a get-only internal property instead of moving the extension method into the matcher type in order to avoid changing the interface.

Another potential issue is that the `InMemoryDirectoryInfo` is still case-sensitive by default where the typical pattern in this repository has been to make things case-insensitive. Again this was just to avoid any breaking changes.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs [hunk 1]
```diff
@@ -17,24 +17,38 @@ public class InMemoryDirectoryInfo : DirectoryInfoBase
...
+        {
+        }
+
+        /// <summary>
+        /// Creates a new InMemoryDirectoryInfo with the root directory and files given.
+        /// </summary>
+        /// <param name="rootDir">The root directory that this FileSystem will use.</param>
+        /// <param name="files">Collection of file names. If relative paths <paramref name="rootDir"/> will be prepended to the paths.</param>
+        /// <param name="comparisonType">The comparison type for the root directory. When files are enumerated they will be compared with the root directory using this comparison type.</param>
+        public InMemoryDirectoryInfo(string rootDir, IEnumerable<string>? files, StringComparison comparisonType)
```
Comment (jozkee) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs]: This seems like a reasonable addition to public surface area but it needs to go through [API Review](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md) for it to be `public`.  Since this is in the same assembly as Matcher, you should use `internal` for now to address your issue.

Comment (MitchBodmer) [reply src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs]: Good catch. Done.

File: src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs [hunk 2]
```diff
@@ -901,5 +901,50 @@ public void VerifyFiles_ParentRedundantSegment_CurrentDirectory_HasMatches()
...
+                expectedSubPaths.Select(expectedSubPath => Path.Combine(filesRoot, expectedSubPath)));
+
+            Assert.True(patternMatchingResult.HasMatches);
+            Assert.Equal(expectedSubPaths.Length, patternMatchingResult.Files.Count());
+        }
+
+        [Theory]
+        [InlineData(@"C:\this\example\root", @"C:\this\EXAMPLE\root", "**/*", new[] { "some/test/file.txt" })]
+        [InlineData(@"C:\this\EXAMPLE\root", @"C:\this\example\root", "**/*", new[] { "some/test/file.txt" })]
+        public void VerifyFiles_InMemory_HasCaseSensitiveRootMisses(string matchRoot, string filesRoot, string pattern, string[] expectedSubPaths)
```
Comment (jozkee) [inline src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs:938]: This [failed in OSX](https://helixr1107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-120159-merge-b8683405190747e0aa/Microsoft.Extensions.FileSystemGlobbing.Tests/1/console.18a53fcf.log?helixlogtype=result&skoid=8eda00af-b5ec-4be9-b69b-0919a2338892&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2025-09-26T22%3A05%3A29Z&ske=2025-09-26T23%3A05%3A29Z&sks=b&skv=2024-11-04&sv=2024-11-04&se=2025-09-26T23%3A05%3A29Z&sr=b&sp=rl&sig=07UFno4CUjHSkd2vby9cDU7nHEPToTIuuCw5t8IAolE%3D), can you please take a look.

InMemoryDirectoryInfo normalizes path in an [os dependant way](https://github.com/dotnet/dotnet/blob/2db1f5ee2bdda2e8d873769325fabede32e420e0/src/runtime/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L49) so C:\somepath is actually treated as /your/cwd/C:\somepath in Unix, I don't think that's the intent of this test.  You could use `/` instead of `C:\` and that should work the same for both Windows and Unix.

**Review by jozkee — APPROVED** [review]
Thanks.
