### PR TITLE
Disable TestOnExecuteCustomCommand() for WSC

### LINKED ISSUE #43207: Test failure: System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand
failed in job:[runtime-libraries-coreclr outerloop 20201008.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26906848&paneView=debug&resultId=103443)

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
Assert.Equal() Failure
Expected: 129
Actual:   128

Stack trace
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnExecuteCustomCommand() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 156
~~~

### PR DESCRIPTION
**Pull request by danmoseley**
Fix https://github.com/dotnet/runtime/issues/43207

(By disabling on Windows Server Core: not a fix, but I don't believe we'll be investigating why it doesn't work there. It does work on Nano.)

### CODE REVIEW

File: src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs [hunk 1]
```diff
@@ -141,6 +142,11 @@ public void TestOnPauseAndContinueThenStop()
         [ConditionalFact(nameof(IsProcessElevated))]
         public void TestOnExecuteCustomCommand()
         {
+            if (PlatformDetection.IsWindowsServerCore)
+            {
+                throw new SkipTestException("Skip on Windows Server Core"); // https://github.com/dotnet/runtime/issues/43207
+            }
```
Comment (stephentoub) [inline src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:148]: We can't do this in the ConditionalFact?

**Review by stephentoub — APPROVED** [review]

**Review by Anipik — APPROVED** [review]

File: src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs (hunk 1 above)
Comment (danmoseley) [reply src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:148]: ConditionalXXX attribute a[ccepts `Type, Member*` or `Member](https://github.com/dotnet/arcade/blob/7e0f9bc02f83d0a561d9edb963d856334f048f0d/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalTestDiscoverer.cs#L158)` so I would have to create a property like IsElevatedAndWindowsServerCore which does not seem worth it.
