### PR TITLE
[Interp] Create an intrinsic for Interlocked.Exchange for int64

### LINKED ISSUE #41449: Microbenchmark System.Threading.Tests.Perf_Volatile.Read_double is  3,630 % slower on Wasm vs. desktop interpreter.
Microbenchmark System.Threading.Tests.Perf_Volatile.Read_double is  3,630 % slower on Wasm vs. desktop interpreter.

System.Threading.Tests.Perf_Volatile.Write_double is also slow (%866), the causes are probably related.

Repro Instructions for running benchmarks locally:
https://gist.github.com/naricc/efdc186951a912507550509b21fb992b

[Results page when reported.](https://pvscmdupload.blob.core.windows.net/reports/08_26_2020/report_Daily_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2020-08-26.html#Regressions  )

[Automated runs](https://pvscmdupload.blob.core.windows.net/index/index/index.html)

### PR DESCRIPTION
**Pull request by fanyang-mono**
Here are some measurements for wasm:
For microbenchmark System.Threading.Tests.Perf_Interlocked.Exchange_long, before and after this change: 141.6ns -> 11.0ns
For microbenchmark System.Threading.Tests.Perf_Volatile.Read_double, before and after this change: 183.9ns -> 158.5ns
For microbenchmark System.Threading.Tests.Perf_Volatile.Write_double, before and after this change: 151.0ns -> 18.04ns

Fixes #41449

### CODE REVIEW

File: src/mono/mono/metadata/threads-types.h [hunk 1]
```diff
@@ -580,4 +580,11 @@ mono_threads_summarize_execute (MonoContext *ctx, gchar **out, MonoStackHash *ha
 gboolean
 mono_threads_summarize_one (MonoThreadSummary *out, MonoContext *ctx);
 
+#if SIZEOF_VOID_P == 4
+/* Spin lock for unaligned InterlockedXXX 64 bit functions on 32bit platforms. */
+#define mono_interlocked_lock() mono_os_mutex_lock (&interlocked_mutex)
+#define mono_interlocked_unlock() mono_os_mutex_unlock (&interlocked_mutex)
+static mono_mutex_t interlocked_mutex;
+#endif
```
Comment (vargaz) [inline src/mono/mono/metadata/threads-types.h:588]: A static var shouldn't be in a header file, every file including it will get a copy.

File: src/mono/mono/mini/interp/mintops.def [hunk 2]
```diff
@@ -705,6 +705,7 @@ OPDEF(MINT_MONO_NEWOBJ, "mono_newobj", 2, Pop0, Push1, MintOpClassToken)
 OPDEF(MINT_MONO_RETOBJ, "mono_retobj", 1, Pop1, Push0, MintOpNoArgs)
 OPDEF(MINT_MONO_ATOMIC_STORE_I4, "mono_atomic.store.i4", 1, Pop2, Push0, MintOpNoArgs)
 OPDEF(MINT_MONO_MEMORY_BARRIER, "mono_memory_barrier", 1, Pop0, Push0, MintOpNoArgs)
+OPDEF(MINT_MONO_EXCHANGE_LONG, "mono_interlocked_exchange_long", 1, Pop2, Push1, MintOpNoArgs)
 OPDEF(MINT_MONO_LDDOMAIN, "mono_lddomain", 1, Pop0, Push1, MintOpNoArgs)
```
Comment (vargaz) [inline src/mono/mono/mini/interp/mintops.def:709]: Should have a different name like EXCHANGE_I8, 'long' is a bit ambiguous.

File: src/mono/mono/metadata/threads-types.h (hunk 1 above)
Comment (fanyang-mono) [reply src/mono/mono/metadata/threads-types.h:587]: Good catch! Made it to a global variable.

File: src/mono/mono/mini/interp/mintops.def (hunk 2 above)
Comment (fanyang-mono) [reply src/mono/mono/mini/interp/mintops.def:709]: Are you suggesting just `EXCHANGE_I8` or `mono_interlocked_exchange_I8`?

Comment (vargaz) [reply src/mono/mono/mini/interp/mintops.def:709]: MINT_MONO_EXCHANGE_I8.

Comment (fanyang-mono) [reply src/mono/mono/mini/interp/mintops.def:709]: Fixed.

File: src/mono/mono/metadata/threads-types.h [hunk 3]
```diff
@@ -580,4 +580,10 @@ mono_threads_summarize_execute (MonoContext *ctx, gchar **out, MonoStackHash *ha
 gboolean
 mono_threads_summarize_one (MonoThreadSummary *out, MonoContext *ctx);
 
+#if SIZEOF_VOID_P == 4
+/* Spin lock for unaligned InterlockedXXX 64 bit functions on 32bit platforms. */
+#define mono_interlocked_lock() mono_os_mutex_lock (&interlocked_mutex)
+#define mono_interlocked_unlock() mono_os_mutex_unlock (&interlocked_mutex)
```
Comment (lambdageek) [inline src/mono/mono/metadata/threads-types.h:586]:
```suggestion
extern mono_mutex_t mono_interlocked_mutex;
static inline void
mono_interlocked_lock(void) {
	mono_os_mutex_lock (&mono_interlocked_mutex);
}
static inline void mono_interlocked_unlock() {
	mono_os_mutex_unlock (&mono_interlocked_mutex);
}
```

1. You need a declaration for the global variable.  (just having a definition in threads.c is not enough).
2. Global variables should have a `mono_` prefix
3. No need to use `#define` when a `static inline` function will work since we're not doing any preprocessor stuff in the implementation.
4. You will need to go and change the places in `threads.c` that `init and `destory` the mutex to use the new name

File: src/mono/mono/mini/interp/interp.c [hunk 4]
```diff
@@ -6390,6 +6390,25 @@ interp_exec_method (InterpFrame *frame, ThreadContext *context, FrameClauseArgs
 			mono_memory_barrier ();
 			MINT_IN_BREAK;
 		}
+		MINT_IN_CASE(MINT_MONO_EXCHANGE_I8)
+			sp--;
+			gboolean flag = FALSE;
+#if SIZEOF_VOID_P == 4
+			extern mono_mutex_t interlocked_mutex;
```
Comment (lambdageek) [inline src/mono/mono/mini/interp/interp.c:6397]:
```suggestion
```

File: src/mono/mono/mini/interp/mintops.def [hunk 5]
```diff
@@ -705,6 +705,7 @@ OPDEF(MINT_MONO_NEWOBJ, "mono_newobj", 2, Pop0, Push1, MintOpClassToken)
 OPDEF(MINT_MONO_RETOBJ, "mono_retobj", 1, Pop1, Push0, MintOpNoArgs)
 OPDEF(MINT_MONO_ATOMIC_STORE_I4, "mono_atomic.store.i4", 1, Pop2, Push0, MintOpNoArgs)
 OPDEF(MINT_MONO_MEMORY_BARRIER, "mono_memory_barrier", 1, Pop0, Push0, MintOpNoArgs)
+OPDEF(MINT_MONO_EXCHANGE_I8, "mono_interlocked_exchange_long", 1, Pop2, Push1, MintOpNoArgs)
```
Comment (lambdageek) [inline src/mono/mono/mini/interp/mintops.def:708]: nit: `"mono_interlocked.exchange.i8"`  (really the only part of this bikeshedding that I feel is somewhat important is to use "i8" instead of "long")

File: src/mono/mono/metadata/threads-types.h (hunk 3 above)
Comment (fanyang-mono) [reply src/mono/mono/metadata/threads-types.h:586]: I declared the global variable with extern at the location where I used it again. And it did worked. I didn't add the declaration in the header file, because I wanted to limit its usage, since it was a static var before.

File: src/mono/mono/mini/interp/transform.c [hunk 6]
```diff
@@ -2012,9 +2012,8 @@ interp_handle_intrinsics (TransformData *td, MonoMethod *target_method, MonoClas
 	} else if (in_corlib && !strcmp (klass_name_space, "System.Threading") && !strcmp (klass_name, "Interlocked")) {
 		if (!strcmp (tm, "MemoryBarrier") && csignature->param_count == 0)
 			*op = MINT_MONO_MEMORY_BARRIER;
-		if (!strcmp (tm, "Exchange") && csignature->param_count == 2 && csignature->params [0]->type == MONO_TYPE_I8 && csignature->params [1]->type == MONO_TYPE_I8) {
-			*op = MINT_MONO_EXCHANGE_LONG;
-		}
+		if (!strcmp (tm, "Exchange") && csignature->param_count == 2 && csignature->params [0]->type == MONO_TYPE_I8 && csignature->params [1]->type == MONO_TYPE_I8)
```
Comment (vargaz) [inline src/mono/mono/mini/interp/transform.c:2015]: This should be else if.

Comment (fanyang-mono) [reply src/mono/mono/mini/interp/transform.c:2015]: Good catch!

File: src/mono/mono/mini/interp/mintops.def (hunk 5 above)
Comment (fanyang-mono) [reply src/mono/mono/mini/interp/mintops.def:708]: Fixed

**Comment by BrzVlad** [comment]
@fanyang-mono What perf gain would this produce on a 64bit platform, for the long xchg operation ? On wasm we were slow because long doesn't fit in a pointer size register, so we were taking the slow pinvoke path. I'm curious, on amd64, how fast icall compares to intrinsic.

File: src/mono/mono/mini/interp/interp.c [hunk 7]
```diff
@@ -6390,6 +6390,24 @@ interp_exec_method (InterpFrame *frame, ThreadContext *context, FrameClauseArgs
 			mono_memory_barrier ();
 			MINT_IN_BREAK;
 		}
+		MINT_IN_CASE(MINT_MONO_EXCHANGE_I8)
```
Comment (BrzVlad) [inline src/mono/mono/mini/interp/interp.c:6393]: I think you need braces when declaring variables inside switch case because c++

Comment (fanyang-mono) [reply src/mono/mono/mini/interp/interp.c:6393]: ah, that's could be why C++ is failing to build... Let me add a pair of braces.

**Review by lambdageek — APPROVED** [review]
lgtm.  Sounds like there's still ongoing discussion about perf impact, though.

**Comment by fanyang-mono** [comment]
I had been trying to get the numbers for desktop interpreter before and after this change, however, I am having difficulty running the microbenchmarks locally for desktop interpreter. With the current setup, it requires a patched dotnet. However, getting a patched dotnet is not something doable anymore. Now I am working with Nathan to get it work with a patched corerun. Will post the numbers here, as soon as I have them.

**Comment by fanyang-mono** [comment]
@BrzVlad For desktop interpreter on 64bit platform:
For microbenchmark System.Threading.Tests.Perf_Interlocked.Exchange_long, before and after this change: 37.80ns -> 5.499ns.

The other two microbenchmarks doesn't hit my change at all ob 64bit platform.

**Review by BrzVlad — APPROVED** [review]

**Comment by fanyang-mono** [comment]
Desktop interpreter runs for `System.Threading.Tests.Perf_Interlocked.Exchange_long`
Screen Shot 2020-11-10 at 5 29 53 PM

Before this PR, it took around 35 ns. After this PR, it took around 5 ns.

The WASM run hasn't been updated since Oct 29th. I will post the numbers when the run resumes.

**Comment by fanyang-mono** [comment]
WASM runs for `System.Threading.Tests.Perf_Interlocked.Exchange_long`
Screen Shot 2020-11-23 at 6 38 27 PM
Before this PR, it took around 139.08 ns. After this PR, it took around 9.50 ns.

WASM runs for `System.Threading.Tests.Perf_Volatile.Write_double`
Screen Shot 2020-11-23 at 6 43 10 PM
Before this PR, it took around 146.13 ns. After this PR, it took around 15.31 ns.

WASM runs for `System.Threading.Tests.Perf_Volatile.Read_double`
Screen Shot 2020-11-23 at 6 46 21 PM
Before this PR, it took around 184.25 ns. After this PR, it took around 162.18 ns.
