### PR TITLE
Copy ctor handling for crossgen2

### LINKED ISSUE #39423: Crossgen2 doesn't respect NeedsCopyConstructorModifier/IsCopyConstructed
IL marshallers generated by crossgen2 might assume things that have a copy constructors are simply blittable because crossgen2 is not aware of these modifiers. This could result in wrong p/invoke stubs getting generated (copy constructor not getting invoked).

### PR DESCRIPTION
**Pull request by davidwrighton**
- Add IL based test for copy ctor to allow testing in Crossgen2 which doesn't yet support IJW
- Add api to determine proper EmbeddedSignatureData index for these
  - And tests to ensure this remains functional
- Marshaller changes to recognize copy constructor cases
  - Note that there isn't actual marshaller support. Instead the compiler can now able to detect when copy ctors should be used, and falls back to the runtime interop layer

Fixes #39423

Note that with this change there is only one more case of custom modifier examination that is used to affect runtime codegen. (The use of the IsCXXReferenceModifier type when searching for destructors to implement this form of marshalling.) Also, as that syntax hasn't been generated from a C++/CLI compiler in many years, it is unlikely that it will ever need to be implemented.

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/crossgen-contrib

**Comment by davidwrighton** [comment]
@jkoritzinsky I've added this IL only copy ctor test in order to get coverage on this form of marshalling in crossgen2.

**Review by jkoritzinsky — APPROVED** [review]

File: src/coreclr/src/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs [hunk 1]
```diff
@@ -166,9 +166,40 @@ public static partial class MarshalHelpers
...
+                }
+            }
+
+            return false;
+        }
+
         internal static MarshallerKind GetMarshallerKind(
              TypeDesc type,
-             MarshalAsDescriptor marshalAs,
+            int? parameterIndex,
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:200]: Indentation looks off.

File: src/coreclr/src/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs [hunk 2]
```diff
@@ -183,6 +214,12 @@ public static partial class MarshalHelpers
 
                 type = type.GetParameterType();
 
+                if (!type.IsPrimitive && type.IsValueType && !(marshallerType == MarshallerType.Field)
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:217]:
```suggestion
                if (!type.IsPrimitive && type.IsValueType && marshallerType != MarshallerType.Field
```

File: src/coreclr/src/tools/Common/TypeSystem/Common/MethodDesc.cs [hunk 3]
```diff
@@ -51,6 +51,14 @@ public sealed partial class MethodSignature : TypeSystemEntity
         // Value of <see cref="EmbeddedSignatureData.index" /> for any custom modifiers on the return type
         public const string IndexOfCustomModifiersOnReturnType = "0.1.1.1";
 
+        // Value of <see cref="EmbeddedSignatureData.index" /> for any custom modifiers on
+        // SomeStruct when SomeStruct *, or SomeStruct & is the type of a parameter or return type
+        // Parameter index 0 represents the return type, and indices 1-n represent the parameters to the signature
+        public static string GetIndexOfCustomModifierOnPointedAtTypeByParameterIndex(int parameterIndex)
+        {
+            return $"0.1.1.2.{(parameterIndex + 1).ToStringInvariant()}.1";
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/Common/TypeSystem/Common/MethodDesc.cs:59]: Not reviewing this part. I don't want to spend time learning how this address is computed because that code upsets me.

File: src/coreclr/src/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs [hunk 4]
```diff
@@ -444,7 +481,15 @@ public static partial class MarshalHelpers
             else if (type.IsPointer)
             {
                 if (nativeType == NativeTypeKind.Default)
+                {
+                    var pointedAtType = type.GetParameterType();
+                    if (!pointedAtType.IsPrimitive && !type.IsEnum && !(marshallerType == MarshallerType.Field)
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:486]:
```suggestion
                    if (!pointedAtType.IsPrimitive && !type.IsEnum && marshallerType != MarshallerType.Field
```

**Review by MichalStrehovsky — APPROVED** [review]
