### PR TITLE
Skip reloc handling for IMAGE_REL_BASED_DIR64 if already handled

### LINKED ISSUE #104441: JIT: Spurious 0-sized diffs in smoke_tests.nativeaot.windows.arm64
We're seeing some spurious 0-sized diffs in smoke_tests.nativeaot.windows.arm64. Seems likely to be related to #104282, can you take a look @kunalspathak?

### LINKED ISSUE #104584: asmdiff failed for checked and release for smoke_tests.nativeaot.windows.arm64
Pipeline: [runtime-coreclr superpmi-asmdiffs-checked-release](https://dev.azure.com/dnceng-public/public/_build?definitionId=153&_a=summary): [20240708.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733731)
Failed job: [Link](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733726&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=2694d93b-a574-5310-1876-2e252085b877)
[Log](https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-8695c9bf0a31465ea2/windows-arm64/1/console.606a30e5.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-8695c9bf0a31465ea2/windows-arm64/1/console.606a30e5.log?helixlogtype=result))

Error Message:
```
[23:18:54] Asm diffs summary:

[23:18:54]   Replay failures in 1 MCH files:

[23:18:54]     C:\h\w\AE3409D3\p\artifacts\spmi\mch\e6c7a441-8d3c-4135-abc2-bc4dd7c6a4d7.windows.arm64\smoke_tests.nativeaot.windows.arm64.checked.mch

[23:18:54]   Asm diffs in 1 MCH files:

[23:18:54]     C:\h\w\AE3409D3\p\artifacts\spmi\mch\e6c7a441-8d3c-4135-abc2-bc4dd7c6a4d7.windows.arm64\smoke_tests.nativeaot.windows.arm64.checked.mch
```

### PR DESCRIPTION
**Pull request by kunalspathak**
Resolves https://github.com/dotnet/runtime/issues/104584 and resolves https://github.com/dotnet/runtime/issues/104441

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/tools/superpmi/superpmi-shared/compileresult.cpp [hunk 1]
```diff
@@ -918,7 +918,7 @@ void CompileResult::applyRelocs(RelocContext* rc, unsigned char* block1, ULONG b
 
         if (IsSpmiTarget64Bit())
         {
-            if (relocType == IMAGE_REL_BASED_DIR64)
+            if (!wasRelocHandled && (relocType == IMAGE_REL_BASED_DIR64))
```
Comment (amanasifkhalid) [inline src/coreclr/tools/superpmi/superpmi-shared/compileresult.cpp:921]: I might be missing something here, but if `relocType == IMAGE_REL_BASED_DIR64`, shouldn't `wasRelocHandled` always be false? I don't see this reloc type handled in any of the above switch statements, and those are the only places where `wasRelocHandled` can be set to true.

Comment (kunalspathak) [reply src/coreclr/tools/superpmi/superpmi-shared/compileresult.cpp:921]: yes, that's because `IMAGE_REL_BASED_DIR64` and `IMAGE_REL_ARM64_SECREL_HIGH12A` share the same enum value `0x9`. `IMAGE_REL_BASED_DIR64` is used in xarch, while `IMAGE_REL_ARM64_SECREL_HIGH12A` is for arm64. So yes, `wasRelocHandled` will mostly be `false`, except for arm64/`IMAGE_REL_ARM64_SECREL_HIGH12A` in which case we should not handle it here. If we do, it just overwrites the codestream leading to "decoding failures". Ideally, this handling should be just for `SPMI_TARGET_ARCHITECTURE_X86` and `SPMI_TARGET_ARCHITECTURE_AMD64`, but I was not sure if there was any historic reason to do so. Wanted to do minimal change to address the underlying issue for arm64.

 See the discussion in https://github.com/dotnet/runtime/pull/104282#discussion_r1661812059.

Comment (amanasifkhalid) [reply src/coreclr/tools/superpmi/superpmi-shared/compileresult.cpp:921]: Got it, thank you for explaining this!

**Review by amanasifkhalid — APPROVED** [review]
