### PR TITLE
Disable ctor calls on classes marked with `ComImport` when COM interop feature isn't enabled.

### LINKED ISSUE #114933: Assert failure: pMD->IsCtor()
Running 'PMI' on Dia2Lib.dll hits an assert. This causes the `runtime superpmi-collect` to fail the `SuperPMI collect libraries pmi linux x64 checked` collection job:

https://dev.azure.com/dnceng/internal/_build/results?buildId=2692581&view=logs&j=5562265b-363f-5c64-5cff-7b508c285721

To repro, build the https://github.com/dotnet/jitutils repo (clone, then run `./bootstrap.sh`). Then, from a dotnet/runtime `artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root` directory:
```
~/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root$ ./corerun ~/gh/jitutils/bin/pmi.dll DRIVEALL Dia2Lib.dll
DRIVEALL: Invoking /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun /home/brucefo/gh/jitutils/bin/pmi.dll PREPALL Dia2Lib.dll 0
PrepAll for Dia2Lib
Start type Dia2Lib.DiaSourceClass
PREPALL type# 0 method# 0 Dia2Lib.DiaSourceClass::get_lastError
Assert failure(PID 71552 [0x00011780], Thread: 71552 [0x11780]): pMD->IsCtor()    File: /home/brucefo/gh/runtime/src/coreclr/vm/ecall.cpp:350    Image: /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun
Current Method: 0 nextMethodToPrep: 1
DRIVEALL: Invoking /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun /home/brucefo/gh/jitutils/bin/pmi.dll PREPALL Dia2Lib.dll 2
PrepAll for Dia2Lib
Start type Dia2Lib.DiaSourceClass
PREPALL type# 0 method# 2 Dia2Lib.DiaSourceClass::loadAndValidateDataFromPdb
Assert failure(PID 71568 [0x00011790], Thread: 71568 [0x11790]): pMD->IsCtor()    File: /home/brucefo/gh/runtime/src/coreclr/vm/ecall.cpp:350    Image: /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun
Current Method: 2 nextMethodToPrep: 3
DRIVEALL: Invoking /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun /home/brucefo/gh/jitutils/bin/pmi.dll PREPALL Dia2Lib.dll 4
PrepAll for Dia2Lib
Start type Dia2Lib.DiaSourceClass
PREPALL type# 0 method# 4 Dia2Lib.DiaSourceClass::loadDataFromIStream
Assert failure(PID 71579 [0x0001179b], Thread: 71579 [0x1179b]): pMD->IsCtor()    File: /home/brucefo/gh/runtime/src/coreclr/vm/ecall.cpp:350    Image: /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun
Current Method: 4 nextMethodToPrep: 5
DRIVEALL: Invoking /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun /home/brucefo/gh/jitutils/bin/pmi.dll PREPALL Dia2Lib.dll 6
PrepAll for Dia2Lib
Start type Dia2Lib.DiaSourceClass
PREPALL type# 0 method# 6 Dia2Lib.DiaSourceClass::loadDataFromCodeViewInfo
Assert failure(PID 71590 [0x000117a6], Thread: 71590 [0x117a6]): pMD->IsCtor()    File: /home/brucefo/gh/runtime/src/coreclr/vm/ecall.cpp:350    Image: /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun
Current Method: 6 nextMethodToPrep: 7
DRIVEALL: Invoking /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun /home/brucefo/gh/jitutils/bin/pmi.dll PREPALL Dia2Lib.dll 8
PrepAll for Dia2Lib
Start type Dia2Lib.DiaSourceClass
PREPALL type# 0 method# 8 Dia2Lib.DiaSourceClass::IDiaDataSource3_get_lastError
Assert failure(PID 71602 [0x000117b2], Thread: 71602 [0x117b2]): pMD->IsCtor()    File: /home/brucefo/gh/runtime/src/coreclr/vm/ecall.cpp:350    Image: /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun
Current Method: 8 nextMethodToPrep: 9
DRIVEALL: Invoking /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun /home/brucefo/gh/jitutils/bin/pmi.dll PREPALL Dia2Lib.dll 10
PrepAll for Dia2Lib
Start type Dia2Lib.DiaSourceClass
PREPALL type# 0 method# 10 Dia2Lib.DiaSourceClass::IDiaDataSource3_loadAndValidateDataFromPdb
Assert failure(PID 71614 [0x000117be], Thread: 71614 [0x117be]): pMD->IsCtor()    File: /home/brucefo/gh/runtime/src/coreclr/vm/ecall.cpp:350    Image: /home/brucefo/gh/runtime/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun
Current Method: 10 nextMethodToPrep: 11
```

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes https://github.com/dotnet/runtime/issues/114933

### CODE REVIEW

File: src/coreclr/vm/ecall.cpp [hunk 1]
```diff
@@ -336,11 +336,10 @@ PCODE ECall::GetFCallImpl(MethodDesc * pMD, BOOL * pfSharedOrDynamicFCallImpl /*
         return CoreLibBinder::GetMethod(METHOD__DELEGATE__CONSTRUCT_DELEGATE)->GetMultiCallableAddrOfCode();
     }
 
+#ifdef FEATURE_COMINTEROP
     // COM imported classes have special constructors
     if (pMT->IsComObjectType()
```
Comment (jkotas) [inline src/coreclr/vm/ecall.cpp:341]: Related: Is there a reason for `IsComObjectType` to ever return true on non-Windows?

File: src/coreclr/vm/ecall.cpp [hunk 2]
```diff
@@ -352,6 +351,7 @@ PCODE ECall::GetFCallImpl(MethodDesc * pMD, BOOL * pfSharedOrDynamicFCallImpl /*
         // FCComCtor does not need to be in the fcall hashtable since it does not erect frame.
         return GetEEFuncEntryPoint(FCComCtor);
     }
+#endif // FEATURE_COMINTEROP
```
[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/vm/ecall.cpp:354]: For reference, https://github.com/dotnet/runtime/pull/54298 is yet another tweak in this logic.

**Comment by jkotas** [comment]
> SecurityException: ECall methods must be packaged into a system module.

This is confusing error to give when somebody tries to use built-in COM on non-Windows. Can we throw `IDS_EE_ERROR_COM` instead?

File: src/coreclr/vm/ecall.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/ecall.cpp:341]: Not really. That is only set for a `class` if it has been marked with `ComImport`. There is very little the class can do in this case other than exist and be used as metadata.

File: src/coreclr/vm/ecall.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/ecall.cpp:354]: This looks like making tests and disabled COM support work based on Windows. This JIT is hitting this because PMI is blinding reflecting over metadata and trying to use code that is marked with `ComImport`, which we don't test normally since it is failing case.

**Review by jkotas — APPROVED** [review]
Is it worth it to add a  regression test for PrepareMethod?

**Comment by AaronRobinsonMSFT** [comment]
> Is it worth it to add a regression test for PrepareMethod?

Yeah, I thought about it. I'm not sure how useful it is in practice, but I added one none the less.

File: src/libraries/System.Runtime/tests/System.Runtime.Tests/System/Runtime/CompilerServices/RuntimeHelpersTests.cs [hunk 3]
```diff
@@ -139,6 +148,11 @@ public static void PrepareMethod()
             {
                 Assert.ThrowsAny<ArgumentException>(() => RuntimeHelpers.PrepareMethod(typeof(IList).GetMethod("Add").MethodHandle));
             }
+
+            if (PlatformDetection.IsNotWindows)
+            {
+                Assert.Throws<PlatformNotSupportedException>(() => RuntimeHelpers.PrepareMethod(typeof(ComClass).GetMethod("Func").MethodHandle));
+            }
```
Comment (jkotas) [inline src/libraries/System.Runtime/tests/System.Runtime.Tests/System/Runtime/CompilerServices/RuntimeHelpersTests.cs:155]:
```suggestion
            try
            {
                // This is expected to either succeed or throw PlatformNotSupportedException depending on the platform
                // and runtime flavor
                RuntimeHelpers.PrepareMethod(typeof(ComClass).GetMethod("Func").MethodHandle);
            }
            catch (PlatformNotSupportedException)
            {
            }
```

Comment (AaronRobinsonMSFT) [reply src/libraries/System.Runtime/tests/System.Runtime.Tests/System/Runtime/CompilerServices/RuntimeHelpersTests.cs:155]: Seems like a reasonable compromise.
