### PR TITLE
Adjust stack level while calculating offset for Vector.getElement

### LINKED ISSUE #36614: Test failure: System.Numerics.Tests.GenericVectorTests.NarrowDouble
Failure in libraries System.Numerics.Vectors.Tests: release libraries, checked coreclr with:
```
set COMPlus_JitStress=1
```

fails with `set COMPlus_TieredCompilation` 0 or 1.

Windows x86

E.g.,
```
build -s libs+libs.tests -runtimeConfiguration checked -c Release -arch x86 /p:ArchiveTests=true
```

(the `/p:ArchiveTests=true` is required to build the RunTests.cmd wrapper scripts)

```
C:\gh\runtime\artifacts\bin\System.Numerics.Vectors.Tests\net5.0-Release>call .\RunTests.cmd -r C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x86
```

```
----- start Sun 05/17/2020 11:33:07.75 ===============  To repro directly: =====================================================
pushd C:\gh\runtime\artifacts\bin\System.Numerics.Vectors.Tests\net5.0-Release\
"C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x86\dotnet.exe" exec --runtimeconfig System.Numerics.Vectors.Tests.runtimeconfig.json --depsfile System.Numerics.Vectors.Tests.deps.json xunit.console.dll System.Numerics.Vectors.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

C:\gh\runtime\artifacts\bin\System.Numerics.Vectors.Tests\net5.0-Release>"C:\gh\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x86\dotnet.exe" exec --runtimeconfig System.Numerics.Vectors.Tests.runtimeconfig.json --depsfile System.Numerics.Vectors.Tests.deps.json xunit.console.dll System.Numerics.Vectors.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
  Discovering: System.Numerics.Vectors.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Numerics.Vectors.Tests (found 1191 of 1194 test cases)
  Starting:    System.Numerics.Vectors.Tests (parallel test collections = on, max threads = 8)
    System.Numerics.Tests.GenericVectorTests.NarrowDouble [FAIL]
      Assert.Equal() Failure
      Expected: 1.2382202E+09
      Actual:   -1.7497244E+09
      Stack Trace:
        C:\gh\runtime\src\libraries\System.Numerics.Vectors\tests\GenericVectorTests.cs(3048,0): at System.Numerics.Tests.GenericVectorTests.NarrowDouble()
  Finished:    System.Numerics.Vectors.Tests
=== TEST EXECUTION SUMMARY ===
   System.Numerics.Vectors.Tests  Total: 1191, Errors: 0, Failed: 1, Skipped: 0, Time: 25.167s
----- end Sun 05/17/2020 11:33:40.23 ----- exit code 1 ----------------------------------------------------------
```

The failure mode is different every run: the Expected/Actual values both change.

@tannergooding @CarolEidt

### PR DESCRIPTION
**Pull request by kunalspathak**
Include stack level while calculating the offset from stack pointer when emitting `vmovss`  for getting element of SIMD intrinsic.

```asm
       3B7704       cmp      esi, dword ptr [edi+4]
       7339         jae      SHORT G_M33220_IG10
       C5FB5A44F708 vcvtsd2ss xmm0, dword ptr [edi+8*esi+8]
       83EC04       sub      esp, 4                            ; <--- stack adjustment
       C5FA110424   vmovss   dword ptr [esp], xmm0
       8D4604       lea      eax, [esi+4]
       C5FD10442430 vmovupd  ymm0, ymmword ptr[esp+2CH+04H]
       C5FD11442408 vmovupd  ymmword ptr[esp+04H+04H], ymm0
       C5FA104C8404 vmovss   xmm1, dword ptr [esp+4*eax+04H]   ; <--- doesn't include +0x4 because of stack adjustment above
       83EC04       sub      esp, 4
       C5FA110C24   vmovss   dword ptr [esp], xmm1
       E86DFAFFFF   call     Xunit.Assert:Equal(float,float)
       46           inc      esi
       EBA5         jmp      SHORT G_M33220_IG05
```

This started showing up in stress run because `STRESS_DBL_ALN` was set for the method which was forcing the stack to be stack pointer based rather than frame pointer.

Fixes: https://github.com/dotnet/runtime/issues/36614

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/src/jit/simdcodegenxarch.cpp [hunk 1]
```diff
@@ -2192,8 +2192,12 @@ void CodeGen::genSIMDIntrinsicGetItem(GenTreeSIMD* simdNode)
     {
         unsigned simdInitTempVarNum = compiler->lvaSIMDInitTempVarNum;
         noway_assert(simdInitTempVarNum != BAD_VAR_NUM);
-        bool      isEBPbased;
-        unsigned  offs     = compiler->lvaFrameAddress(simdInitTempVarNum, &isEBPbased);
+        bool     isEBPbased;
+        unsigned offs = compiler->lvaFrameAddress(simdInitTempVarNum, &isEBPbased);
+
+        // Adjust the offset with stack level, if any.
```
Comment (CarolEidt) [inline src/coreclr/src/jit/simdcodegenxarch.cpp:2198]: This could use a comment. I generally find it confusing to reason about the stack level, but I believe it's the case that 1) it will always be zero if there's a frame pointer (I was wondering why you weren't checking `isEBPbased`), and 2) it will always be zero when `FEATURE_FIXED_OUT_ARGS` is true. Can you confirm or correct?
Also, I'm wondering why this isn't needed further down when a temp is used.

Comment (BruceForstall) [reply src/coreclr/src/jit/simdcodegenxarch.cpp:2198]: Normally, all local access is passed down to the emitter by storing the local number and offset within the local, and `emitOutputSV` does the appropriate offset translation using:
```
#if !FEATURE_FIXED_OUT_ARGS
        // Adjust the offset by the amount currently pushed on the CPU stack
        dsp += emitCurStackLvl;
#endif
```

It looks like the two cases that don't do this are the calls to `lvaFrameAddress` in this function, `genSIMDIntrinsicGetItem`.

So it seems like this is ok, but you need the `#if !FEATURE_FIXED_OUT_ARGS` case (for Linux x86 ABI) or prove Carol's #2. It would probably be better to only do the adjustment for the `!isEBPbased` case, for clarity.

Also, I think the op1 case above that calls `lvaFrameAddress` also needs this logic.

**Review by BruceForstall — CHANGES_REQUESTED** [review]
It would be nice to add a test case or two to the coreclr tests, to cover this.

**Comment by kunalspathak** [comment]
> It would be nice to add a test case or two to the coreclr tests, to cover this.

I spent some time thinking about how to add a test for this. From my understanding, this only happens if `isEBPBased == false` and it is set to `false` [here](https://github.com/dotnet/runtime/blob/4a21529178750aab4b194d54918d0676e0e5833a/src/coreclr/src/jit/lsra.cpp#L2497) or [here](https://github.com/dotnet/runtime/blob/4a21529178750aab4b194d54918d0676e0e5833a/src/coreclr/src/jit/lsra.cpp#L2505) inside `setFrameType()`. We need to have `doDoubleAlign == true` in order for that to happen (done at the top of `setFrameType()`). `doDoubleAlign` is set to `true` [here](https://github.com/dotnet/runtime/blob/4a21529178750aab4b194d54918d0676e0e5833a/src/coreclr/src/jit/lsra.cpp#L1658) and for that, `getCanDoubleAlign` [here](https://github.com/dotnet/runtime/blob/4a21529178750aab4b194d54918d0676e0e5833a/src/coreclr/src/jit/regalloc.cpp#L23) should return `MUST_DOUBLE_ALIGN`. This only happens if `JITStress` or `JitDoubleAlign` is set. I tried setting `JitDoubleAlign` to set (and reverting my fix). Unfortunately we don't repro the issue. One of the key thing of this issue is the `dest` array whose element is wrongly loaded is displaced by 4 bytes as well. So we add that as well while calculating the element address. (`esp+4*eax+04H` , the `04H` is the displacement). I don't see such displacement even if I set `JitDoubleAlign` but `JitStress` is not set. Additionally, there are other code diffs that might not make the bug easily reproducible. While debugging this issue, minor modification to source code was making it reproducible. Let me know if you have any thoughts on including a test. Also, the existing test for `NarrowDouble` with `JitStress` should exercise this code path, right?

File: src/coreclr/src/jit/simdcodegenxarch.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/src/jit/simdcodegenxarch.cpp]: Alright, so just verified that for `isEBPbased == true`, `genStackLevel` can be non-zero. I was hitting previously added assert when crossgening `System.Numerics.Plane:CreateFromVertices`. I have now updated the assert to only include when `FEATURE_FIXED_OUT_ARGS` is `true`.  Below is the code that was getting generated when I hit the assert:

```asm
       83EC0C       sub      esp, 12
       F20F110424   movsd    qword ptr [esp], xmm0
       660F70C802   pshufd   xmm1, xmm0, 2
       F30F114C2408 movss    dword ptr [esp+08H], xmm1
       F30F108568FFFFFF movss    xmm0, dword ptr [ebp-98H]  ; <-- This line
```
In above highlighted line, offset returned by `lvaFrameAddress` was 0x98 and genStackLevel was 0n12 inside `genSimdIntrinsicGetItem`. Since it was `isEBPBased`, the stack level didn't get added to the offset 0x98 and everything now works fine. So what I can conclude is for EBP based, the `varDsc->lvStkOff` holds accurate value but that doesn't happen when ESP based?

Comment (CarolEidt) [reply src/coreclr/src/jit/simdcodegenxarch.cpp]: > So what I can conclude is for EBP based, the varDsc->lvStkOff holds accurate value but that doesn't happen when ESP based?

Yes, that's right - because `genStackLevel` is relative to SP. EBP remains fixed, so the offset relative to that doesn't change.

**Review by BruceForstall — APPROVED** [review]

**Comment by kunalspathak** [comment]
I was able to come up with standalone case. Earlier I couldn't repro it because I was not using particular stress modes needed to repro it.

File: src/coreclr/tests/src/JIT/Regression/JitBlue/GitHub_36614/GitHub_36614.cs [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+            Vector<double> sourceVec2 = new Vector<double>(source2);
+            Vector<float> dest = Vector.Narrow(sourceVec1, sourceVec2);
+
+            for (int i = 0; i < Vector<double>.Count; i++)
+            {
+                Assert.Equal(unchecked((float)source1[i]), dest[i]);
+            }
+            for (int i = 0; i < Vector<double>.Count; i++)
+            {
+                // The test represents a problem where stack level is not adjusted in the offset while trying to
```
Comment (BruceForstall) [inline src/coreclr/tests/src/JIT/Regression/JitBlue/GitHub_36614/GitHub_36614.cs:39]: You might want a comment here that points out this only affects x86, when double-alignment causes access to a stack local.

**Review by BruceForstall — APPROVED** [review]
