### PR TITLE
Fix race condition in Microsoft.Extensions.Configuration test

### LINKED ISSUE #109904: Test failure: Microsoft.Extensions.Configuration.EnvironmentVariables.Test.EnvironmentVariablesTest.BindingDoesNotThrowIfReloadedDuringBinding
**Failed in:** [runtime-coreclr libraries-pgo 20241117.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871724&view=ms.vss-test-web.build-test-results-tab&runId=22726266&resultId=100420&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x64-fullpgo_random_gdv_methodprofiling_only-Windows.10.Amd64.Open
    - Microsoft.Extensions.Configuration.EnvironmentVariables.Test.EnvironmentVariablesTest.BindingDoesNotThrowIfReloadedDuringBinding
```

**Error message:**
```
 System.NullReferenceException : Object reference not set to an instance of an object.
```

**Stack trace:**
```
   at Microsoft.Extensions.Configuration.EnvironmentVariables.Test.EnvironmentVariablesTest.BindingDoesNotThrowIfReloadedDuringBinding() in /_/src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/tests/EnvironmentVariablesTest.cs:line 319
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #109904

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.Configuration/tests/FunctionalTests/ConfigurationTests.cs [hunk 1]
```diff
@@ -966,23 +966,19 @@ void ReloadLoop()
 
                 _ = Task.Run(ReloadLoop);
 
-                MyOptions options = null;
+                MyOptions options;
 
-                bool optionsInitialized = false;
-                while (!cts.IsCancellationRequested)
+                do
```
Comment (jkotas) [inline src/libraries/Microsoft.Extensions.Configuration/tests/FunctionalTests/ConfigurationTests.cs:971]: Fixing the other similar test to use same pattern

File: src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/tests/EnvironmentVariablesTest.cs [hunk 2]
```diff
@@ -331,14 +308,17 @@ void ReloadLoop()
 
                 _ = Task.Run(ReloadLoop);
 
-                while (!cts.IsCancellationRequested)
```
Comment (jkotas) [inline src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/tests/EnvironmentVariablesTest.cs:334]: The problem was that the token can be cancelled by the time we get here and options will stay null. We need to make sure to call `options = config.Get<MyOptions>()` at least once.

**Review by tarekgh — APPROVED** [review]
Thanks for fixing the issue and knowing the underlying reason causing the test failure!
