### PR TITLE
Disable matching constants for vectors that needs upper half to be save/restore

### LINKED ISSUE #70642: Test failure JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd
Run: [runtime-coreclr jitstress2-jitstressregs 20220612.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1820353&view=ms.vss-test-web.build-test-results-tab&runId=48298490&paneView=debug&resultId=100468)

Failed test:
```
coreclr windows x64 Checked jitstress2_jitstressregs1 @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd

coreclr windows x64 Checked jitstress2_jitstressregs8 @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd

```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\9DCC08D2\w\B0130977\uploads\Reports\JIT.HardwareIntrinsics\General\Vector256\Vector256_ro\Vector256_ro.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\9DCC08D2\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Vector256_ro.dll
Beginning test case Abs.Byte at 6/12/2022 7:21:43 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 6/12/2022 7:21:43 PM
Beginning test case Abs.Double at 6/12/2022 7:21:43 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 6/12/2022 7:21:43 PM
Beginning test case Abs.Int16 at 6/12/2022 7:21:43 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 6/12/2022 7:21:43 PM
Beginning test case Abs.Int32 at 6/12/2022 7:21:43 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 6/12/2022 7:21:44 PM
Beginning test case Abs.Int64 at 6/12/2022 7:21:44 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 6/12/2022 7:21:44 PM
Beginning test case Abs.SByte at 6/12/2022 7:21:44 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 6/12/2022 7:21:44 PM
Beginning test case Abs.Single at 6/12/2022 7:21:44 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Begin


Stack trace
   at JIT_HardwareIntrinsics._General_Vector256_Vector256_ro_Vector256_ro_._General_Vector256_Vector256_ro_Vector256_ro_cmd()
```

### PR DESCRIPTION
**Pull request by kunalspathak**
~This reverts commit 24f5de4bb10976dfb391e9b6affe5481f55a2d00.~

#70171 reuses `Vector constants` in register allocation but LSRA doesn't handle it very well. It doesn't have a semantics of looking into constant registers and save/restore the upper-half of them during the call. Because of this, the constant register that we want to reuse after the call gets garbage data in the upper-half and leads to silent functional differences. 

There were several alternatives tried:
- During `buildUpperVectorSave()` also check if there are any vector registers holding constants and add `RefPosition` to save/restore, but we don't have that information until the register allocation.
- Piggyback on one of the `RefTypeKill` refposition and clear the constant vector registers mask during allocation, but we don't have the `treeNode` information for `RefTypeKill` to accurately do this only for Calls and not for anything else.

~For now, I am reverting the change and handle it in better way as part of https://github.com/dotnet/runtime/issues/70182.~

For now, I am disabling the `IsMatchingConstant()` optimization for registers whose upper half need save/restore.

Fixes: https://github.com/dotnet/runtime/issues/70642

### CODE REVIEW

**Comment by kunalspathak** [comment]
@tannergooding @BruceForstall @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/jit/lsra.cpp [hunk 1]
```diff
@@ -2718,12 +2717,6 @@ bool LinearScan::isMatchingConstant(RegRecord* physRegRecord, RefPosition* refPo
             }
             break;
         }
-
-        case GT_CNS_VEC:
-        {
-            return GenTreeVecCon::Equals(refPosition->treeNode->AsVecCon(), otherTreeNode->AsVecCon());
-        }
```
Comment (tannergooding) [inline src/coreclr/jit/lsra.cpp:2725]: Instead of reverting, would it be feasible for this to be the following?
```cpp
return (otherTreeNode->gtType != TYP_SIMD32) && GenTreeVecCon::Equals(refPosition->treeNode->AsVecCon(), otherTreeNode->AsVecCon());
```

Asking as the original change had some measured perf wins and since it looks like the bug only impacts `TYP_SIMD32` due to the need to save/restore the upper halves (meaning I think it shouldn't impact `TYP_SIMD8/12/16`).

Comment (BruceForstall) [reply src/coreclr/jit/lsra.cpp:2725]: If we want to scope it, we only need to do it for platforms where `FEATURE_PARTIAL_SIMD_CALLEE_SAVE` is defined (win-amd64, arm64, LoongArch64). Presumably there is no issue on x86?

`varTypeNeedsPartialCalleeSave` would need to be used.

Comment (BruceForstall) [reply src/coreclr/jit/lsra.cpp:2725]: However, I still think it's probably "too late" to ensure correctness, on all platforms.

Comment (kunalspathak) [reply src/coreclr/jit/lsra.cpp:2725]: `varTypeNeedsPartialCalleeSave ` check seems reasonable to include, but I agree with @BruceForstall that the simplest thing would be to revert the change at this point.

Comment (tannergooding) [reply src/coreclr/jit/lsra.cpp:2725]: 👍, just thought I'd throw it out as a suggestion given this will have negative impact on Arm64.

I expect we'll see this one https://github.com/dotnet/perf-autofiling-issues/issues/5976 and a few of the other code paths that use vector constants regress a bit.

Comment (kunalspathak) [reply src/coreclr/jit/lsra.cpp]: I looked at the spmi-diffs and there are few in benchmarks. I tried the change to just use `varTypeNeedsPartialCalleeSave ` and didn't see as many spmi-diffs in benchmarks, asp locally. I will let CI run and check other diffs.

Comment (kunalspathak) [reply src/coreclr/jit/lsra.cpp]: There is no change in spmi diff on Arm64 if we just disable `isMatchingConstant` for `varTypeNeedsPartialCalleeSave`. On x64, there is slight difference (earlier in benchmark collection, 12 methods regressed and now 5). 

> it looks like the bug only impacts TYP_SIMD32 due to the need to save/restore the upper halves (meaning I think it shouldn't impact TYP_SIMD8/12/16).

@tannergooding , even Arm64 needs save/restore upper half as per this comment, so it could be problematic there too, right?

https://github.com/dotnet/runtime/blob/519d1e31184bcdbbb4cbf0a5688cc80366468bd3/src/coreclr/jit/compiler.h#L7439-L7445

Comment (kunalspathak) [reply src/coreclr/jit/lsra.cpp]: > What was the regression on Arm64 if we revert the entire PR?

There is no change between total revert and limiting it to just `varTypeNeedsPartialCalleeSave` on Arm64.

https://dev.azure.com/dnceng/public/_build/results?buildId=1951028&view=ms.vss-build-web.run-extensions-tab

Comment (kunalspathak) [reply src/coreclr/jit/lsra.cpp]: > (https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#simd-and-floating-point-registers):

Thanks for this incredible resource. I didn't know about it.

**Comment by JulieLeeMSFT** [comment]
CC @jeffschwMSFT, this is the bug fix for https://github.com/dotnet/runtime/issues/70642, and we are reverting it.

**Comment by jeffschwMSFT** [comment]
If wanted in 7, we need to backport to 7 RC1

**Review by BruceForstall — APPROVED** [review]
LGTM

Please make sure you change the title and text of this PR to reflect the current change (it's no longer "revert". Same for the commit message when you merge.

**Comment by kunalspathak** [comment]
Trigged a run https://dev.azure.com/dnceng/public/_build/results?buildId=1952719&view=results

**Comment by kunalspathak** [comment]
The test no longer fails in https://dev.azure.com/dnceng/public/_build/results?buildId=1952719&view=results .
