### PR TITLE
JIT: Fix uninitialized gtCallMethHnd for indirect calls causing false recursive tail call detection

### LINKED ISSUE #126930: Test failure: Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ScopeValidationtEnabledInDevelopmentWithServiceProviderChanges
**Failed in:** [runtime-coreclr crossgen2 20260413.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1377724)

**Failed tests:**
```
net11.0-osx-Release-x64-TestReadyToRun_Release-OSX.15.Amd64.Open
- Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ScopeValidationtEnabledInDevelopmentWithServiceProviderChanges
- Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ScopeValidationNotEnabledInDevelopmentWithServiceProviderChanges
- Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ValidateOnBuildNotEnabledInDevelopmentWithServiceProviderChanges
- Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ConfigureDefaultServiceProvider
net11.0-osx-Release-arm64-TestReadyToRun_RuntimeAsync_Release-OSX.26.Arm64.Open
- Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ScopeValidationtEnabledInDevelopmentWithServiceProviderChanges
- Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ScopeValidationNotEnabledInDevelopmentWithServiceProviderChanges
- Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ValidateOnBuildNotEnabledInDevelopmentWithServiceProviderChanges
- Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ConfigureDefaultServiceProvider

```

**Error message:**
```
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
```

**Stack trace:**
```
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.UseDefaultServiceProvider(IHostBuilder hostBuilder, Action`2 configure)
   at Microsoft.Extensions.Hosting.Tests.HostBuilderTests.ScopeValidationtEnabledInDevelopmentWithServiceProviderChanges() in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostBuilderTests.cs:line 583
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
> [!NOTE]
> This PR was generated with the assistance of GitHub Copilot.

Fixes #126930

## Problem

PR #125211 removed the union between `gtCallMethHnd` and `gtCallAddr` in `GenTreeCall`, making them separate fields. However, `gtNewCallNode` was not updated to initialize `gtCallMethHnd` for `CT_INDIRECT` calls. Since the JIT arena allocator doesn't zero memory in Release builds, `gtCallMethHnd` contains stale arena data.

When the stale data coincidentally matches the compiled method's handle, `gtIsRecursiveCall()` falsely returns true for indirect calls. Combined with `!call->IsVirtual()` being true for `CORINFO_VIRTUALCALL_LDVIRTFTN` calls (which lack `GTF_CALL_VIRT_*` flags), `fgMorphRecursiveFastTailCallIntoLoop` incorrectly transforms the call into a backward jump — creating an infinite allocating loop.

This only manifests non-deterministically depending on arena memory layout, which is why it appears on x64 CI but not on arm64 or in local builds.

## Fix

Three surgical changes:

1. **`gentree.cpp` (`gtNewCallNode`)**: Initialize `gtCallMethHnd = NO_METHOD_HANDLE` for `CT_INDIRECT` calls — the primary fix that prevents stale data.

2. **`compiler.h` (`gtIsRecursiveCall`)**: Defense-in-depth — return `false` for `CT_INDIRECT` calls since indirect calls can never be recursive by definition.

3. **`gentree.cpp` (`gtCloneExprCallHelper`)**: Same initialization for cloned indirect calls to prevent the same issue in clone paths.

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -9768,6 +9768,7 @@ GenTreeCall* Compiler::gtNewCallNode(gtCallTypes           callType,
     if (callType == CT_INDIRECT)
     {
         node->gtCallCookie  = nullptr;
+        node->gtCallMethHnd = NO_METHOD_HANDLE;
```
Comment (SingleAccretion) [inline src/coreclr/jit/gentree.cpp:9779]: It's not completely unintentional that this wasn't done in the gtCallAddr change, since the expectation is that the method handle is never accessed for indirect calls. `gtCallMethHnd` could certainly use an accessor.

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib PTAL

Suggest we take this to fix the ci-optional issue and then circle back to add better protection.

**Review by jakobbotsch — APPROVED** [review]
