### PR TITLE
Fix propagating of unhandled exception to native caller

### LINKED ISSUE #113751: [dotnet-sdk-10.0.100-preview.3.25168.9] Autodesk Revit 2025 close unexpectedly after closing File > Options window
### Description

When run the Autodesk Revit 2025 application with the latest .NET 10 build, it is closed unexpectedly after closing File > Options window.

### Reproduction Steps

**Please get the repro machine information from** [devdiv bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2422533)
**The machine only has the .NET 10 Preview3 runtime and set environment variables DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2:**
1. Launch Revit 2025.exe.
2. If the "Options - Hardware Acceleration" window pops up, click the “Close” button.  
3. Click the "Home" button on left top
4. Click "File" menu.
5. Click "Options".
6. Close the "Options" window and click anywhere in application.

### Expected behavior

The application can continue work after closing "Options" window.

### Actual behavior

Error Report window appear and then the application is closed unexpectedly.

Image

Image

### Regression?

Yes

Verify Scenarios:
1). Windows 10 22H2 AMD64 + dotnet-sdk-8.0.407: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.202: Pass 
3). Windows 10 21H2 AMD64 + 10.0.100-preview.2.25164.34: Pass 
4). Windows 10 22H2 AMD64 + dotnet-sdk-10.0.100-preview.3.25168.9: Fail

### Known Workarounds

_No response_

### Configuration

**Application Name:** Autodesk Revit 2025
**OS：** Windows 10 21H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-10.0.100-preview.3.25168.9

### Other information

**Findings:**
The application log journal.0003.txt and minidump.dmp file are all attached in ErrorDetails.zip file 

[ErrorDetails.zip](https://github.com/user-attachments/files/19382969/ErrorDetails.zip)

.
From the application log, it shows below exception with stack trace:
```
'C 21-Mar-2025 02:51:16.948;  DBG_INFO: Managed exception caught from external API application 'Autodesk.StructuralRibbon.Application' in method 'Void Execute(Autodesk.Revit.UI.UIApplication).' Exception type: '<System.NullReferenceException>,' Exception method: '<Object reference not set to an instance of an object.>,' Stack trace '   at Autodesk.Revit.UI.StructuralRibbon.VisibilityManager.Execute(UIApplication application)
'   at Autodesk.Revit.UI.IExternalEventHandlerBridge.execute_(IExternalEventHandlerBridge*, RevitApplication* pApp).': line 112 of F:\Ship25.4\2025_px64\Source\API\RevitAPIUI\Objects\APIExternalEvent.cpp.
' 0:< External event handler <Dialog option event handler for Structural Ribbon> failed with an exception {System exception}. The event was registered by an AddIn StructuralRibbon (844fae81-bbed-4b1e-aa6f-06ef261f6096)
```
And here is the stack from minidump:
```
STACK_TEXT:  
00000050`d0f29560 00007ffb`50e25f1b     : 00000000`00000000 00000000`00000000 00000050`d0f296b8 00000050`d0f296b0 : coreclr!__report_gsfailure+0x1d
00000050`d0f295a0 00007ffb`50e21578     : 00000000`00000000 00000000`00000000 00000000`00000000 00000050`d0f2ab20 : coreclr!JIT_FailFast+0xb
00000050`d0f295d0 00007ffb`50d1f653     : 00000050`d0f297b0 00000000`00000000 00007ffa`f9614f24 00007ffa`f9320000 : coreclr!Frame::GetFunction+0x98
00000050`d0f29600 00007ffb`50d1e9c7     : 00000050`00000000 00007ffa`f9320000 00000050`d0f2e750 00000000`00000000 : coreclr!StackFrameIterator::NextRaw+0x893
00000050`d0f296a0 00007ffb`50d1fa2a     : 00000050`d0f29701 000001ba`00000000 00000050`d0f29a58 00000050`d0f2a050 : coreclr!StackFrameIterator::Filter+0x223
00000050`d0f29740 00007ffb`50d1e659     : 00000000`00000002 00000050`d0f29870 000001ba`f6b6dbb0 00000000`000001a8 : coreclr!StackFrameIterator::Init+0x15e
00000050`d0f29770 00007ffb`50d1df95     : 000001ba`f7062590 00007ffb`50effa50 000001fb`ab1b1e38 00007ffb`e94db86b : coreclr!Thread::StackWalkFramesEx+0x89
00000050`d0f29b50 00007ffb`50effc21     : 00000050`d0f2c210 00000050`d0f2c210 000001ba`f2270000 00000000`00000002 : coreclr!Thread::StackWalkFrames+0xb9
00000050`d0f2ac70 00007ffb`50f00894     : 00000000`00000000 00000000`00000000 00000000`80131506 00000000`00000000 : coreclr!LogCallstackForLogWorker+0x121
00000050`d0f2ad50 00007ffb`50effd60     : 00000000`80131506 00000000`00000000 00007ffb`50e9d7d3 00000000`00000000 : coreclr!LogInfoForFatalError+0x218
00000050`d0f2adf0 00007ffb`50eff607     : 00000000`80131506 00007ffb`50e9d7d3 000001fb`9add0000 00007ffb`50daeea4 : coreclr!EEPolicy::LogFatalError+0x60
00000050`d0f2bab0 00007ffb`50e9d7f2     : 00000050`d0f2c210 00000050`d0f2c970 00000050`d0f2c210 00000050`d0f30000 : coreclr!EEPolicy::HandleFatalError+0x133
00000050`d0f2c0b0 00007ffb`50df9e53     : 000001ba`f7062590 00000050`d0f30000 00000050`d0f30000 000001bb`043f8290 : coreclr!CLRVectoredExceptionHandlerPhase2+0xa398e
00000050`d0f2c110 00007ffb`50df9d7d     : 00000000`00000000 00000050`d0f30000 00000000`00000000 00007ffa`f7ebdd37 : coreclr!CLRVectoredExceptionHandler+0x93
00000050`d0f2c180 00007ffb`e9529b4c     : 00007ffb`50df9ca0 00000000`00000000 000001ba`f6f6a600 00000000`00000000 : coreclr!CLRVectoredExceptionHandlerShim+0xdd
00000050`d0f2c1d0 00007ffb`e9502376     : 00000050`d0f2c970 00000050`d0f2c480 00000000`00000000 00007ffb`50cc0000 : ntdll!RtlpCallVectoredHandlers+0x108
00000050`d0f2c270 00007ffb`e95513ce     : 00000050`d0f2e600 000001bb`043f7f48 00000000`00000000 000001ba`fb844648 : ntdll!RtlDispatchException+0x66
00000050`d0f2c480 00007ffb`50d1d6fa     : 00000050`d0f2cd50 00007ffb`50d1f67d 00000000`00000000 00000000`00010082 : ntdll!KiUserExceptionDispatch+0x2e
00000050`d0f2cb90 00007ffb`50d1f75b     : 00000050`d0f2cc60 00007ffa`f302f082 00000000`00000000 00000000`00000000 : coreclr!ExceptionTracker::IsInStackRegionUnwoundBySpecifiedException+0x16
00000050`d0f2cbc0 00007ffb`50d1e98c     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : coreclr!ExceptionTracker::HasFrameBeenUnwoundByAnyActiveException+0xa7
00000050`d0f2cc40 00007ffb`50d1fa2a     : 00000050`d0f2cd01 000001ba`00000000 00000050`d0f2cff8 00000050`d0f2d5f0 : coreclr!StackFrameIterator::Filter+0x1e8
00000050`d0f2cce0 00007ffb`50d1e659     : 00000000`00000002 00000050`d0f2ce10 000001ba`f6b6dbb0 00000000`000001a8 : coreclr!StackFrameIterator::Init+0x15e
00000050`d0f2cd10 00007ffb`50d1df95     : 000001ba`f7062590 00007ffb`50d9eae0 00000000`00000000 00007ffa`00000000 : coreclr!Thread::StackWalkFramesEx+0x89
00000050`d0f2d0f0 00007ffb`50d1de50     : 00000000`00043466 00000050`d0f2e650 00000000`2f467000 00000000`00341150 : coreclr!Thread::StackWalkFrames+0xb9
00000050`d0f2e210 00007ffb`50d1dc68     : 000001ba`f7062590 00000000`00000002 00007ffb`50ce5540 00000000`00000000 : coreclr!ScanStackRoots+0xec
00000050`d0f2e280 00007ffb`50ce6e5f     : 00000000`000001c0 00000050`d0f2e330 000001fb`92d696c0 00000000`00000000 : coreclr!GCToEEInterface::GcScanRoots+0xac
00000050`d0f2e2c0 00007ffb`50cde76b     : 00000000`00000000 00000000`00000000 00000002`69d82000 00007ffb`50ccef69 : coreclr!WKS::gc_heap::mark_phase+0x1d7
00000050`d0f2e370 00007ffb`50cce76e     : 00000000`00022e86 00000000`00022e86 00000000`00000001 00000000`00000000 : coreclr!WKS::gc_heap::gc1+0x57
00000050`d0f2e3c0 00007ffb`50ce8462     : 00000000`00000001 00000000`00000000 00000000`00000000 00007ffb`51113fc8 : coreclr!WKS::gc_heap::garbage_collect+0x17a
00000050`d0f2e410 00007ffb`50deb97a     : 00000008`2ac660aa 00000000`00000000 00000000`00000000 00000000`00000000 : coreclr!WKS::GCHeap::GarbageCollectGeneration+0x13e
00000050`d0f2e470 00007ffb`50deb270     : 00000000`00000000 00007ffb`5110867c 00007ffb`5110867c 00000000`00000000 : coreclr!WKS::gc_heap::trigger_gc_for_alloc+0x26
00000050`d0f2e4a0 00007ffb`50deb105     : 00000000`00000000 000001ba`f6b6dd08 00000000`00000028 00000000`00000000 : coreclr!WKS::gc_heap::try_allocate_more_space+0x144
00000050`d0f2e500 00007ffb`50ce1de7     : 000001bb`06800178 00000000`00000028 000001ba`f6b6dd08 00007ffa`f8776781 : coreclr!WKS::gc_heap::allocate_more_space+0x31
00000050`d0f2e530 00007ffb`50d0070b     : 00000050`d0f2e5c0 00000000`00000028 00000000`00000100 000001bb`043ffa20 : coreclr!WKS::GCHeap::Alloc+0x97
00000050`d0f2e570 00007ffb`50d00545     : 00000000`00000007 000001ba`f6b6dd08 00000000`00000000 000001fb`8e1b085c : coreclr!AllocateString+0x143
00000050`d0f2e600 00007ffa`f93d1699     : 000001bb`0078ff50 000001bb`043fff90 000001bb`043fffa8 00000050`d0f2e7c0 : coreclr!FramedAllocateString+0x85
00000050`d0f2e750 000001bb`0078ff50     : 000001bb`043fff90 000001bb`043fffa8 00000050`d0f2e7c0 00000000`00000000 : 0x00007ffa`f93d1699
00000050`d0f2e758 000001bb`043fff90     : 000001bb`043fffa8 00000050`d0f2e7c0 00000000`00000000 00000050`0000000e : 0x000001bb`0078ff50
00000050`d0f2e760 000001bb`043fffa8     : 00000050`d0f2e7c0 00000000`00000000 00000050`0000000e 00007ffa`00000000 : 0x000001bb`043fff90
00000050`d0f2e768 00000050`d0f2e7c0     : 00000000`00000000 00000050`0000000e 00007ffa`00000000 00000050`d0f2e750 : 0x000001bb`043fffa8
00000050`d0f2e770 00000000`00000000     : 00000050`0000000e 00007ffa`00000000 00000050`d0f2e750 00007ffa`f21aca35 : 0x00000050`d0f2e7c0
```

**dotnet info:**
```
.NET SDK:
 Version:           10.0.100-preview.3.25168.8
 Commit:            f255b7461b
 Workload version:  10.0.100-manifests.93f92b2e
 MSBuild version:   17.15.0-preview-25167-10+bcc2dc6a6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\10.0.100-preview.3.25168.8\

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
Workloads are configured to install and update using workload versions, but none were found. Run "dotnet workload restore" to install a workload version.

Host:
  Version:      10.0.0-preview.3.25167.9
  Architecture: x64
  Commit:       4ff64a03e5

.NET SDKs installed:
  10.0.100-preview.3.25168.8 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 10.0.0-preview.3.25164.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 10.0.0-preview.3.25167.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 10.0.0-preview.3.25126.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

@dotnet-actwx-bot @dotnet/compat

### PR DESCRIPTION
**Pull request by janvorli**
The final propagation of unhandled exception into topmost native frames on foreign threads has a bug that hits when the native caller catches the exception and then calls into managed code again. The problem is that we weren't popping out the explicit frames and ExInfos. So when the managed code is entered again, the `Thread::m_pFrame` points to a garbage. The same is true for the `ExInfo` chain.

This is causing crashes in a 3rd party application where a foreign thread runs some MFC code that calls to some managed functions regularly and swallows exceptions stemming from it.

While investigating the issue, I have found that there is a secondary related problem. When we mark the thread by setting the TSNC_ProcessedUnhandledException flag, the ProcessCLRException intentionally starts ignoring managed frames, because we try to let the exception bubble out to the 3rd party code. But if it catches the exception and calls back to managed code, the
TSNC_ProcessedUnhandledException flag stays set and thus when the exception would need to propagate through native frames, all the managed frames would be ignored.

This change fixes both of the problems and adds a test that crashes without the fix in both of the cases.

Close #113751

### CODE REVIEW

File: src/coreclr/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -934,11 +937,30 @@ ProcessCLRExceptionNew(IN     PEXCEPTION_RECORD   pExceptionRecord,
...
+    if (!ExecutionManager::IsManagedCode((PCODE)pDispatcherContext->ControlPc))
+    {
+        return ExceptionContinueSearch;
+    }
+
+    if (pThread->HasThreadStateNC(Thread::TSNC_UnhandledException2ndPass) && !(pExceptionRecord->ExceptionFlags & EXCEPTION_UNWINDING))
+    {
+        // We are in the 1st pass of exception handling, but the thread mark says that it has already executed 2nd pass
+        // of unhandled exception handling. That means that some external native code on top of the stack has caught the
+        // exception that runtime considered to be unhandledand a new native exception was thrown on the current thread.
```
Comment (jkotas) [inline src/coreclr/vm/exceptionhandling.cpp:949]:
```suggestion
        // exception that runtime considered to be unhandled, and a new native exception was thrown on the current thread.
```

**Review by jkotas — APPROVED** [review]

**Comment by janvorli** [comment]
I can see the change has broken two diagnostic tests. I am looking into it

**Comment by janvorli** [comment]
@jkotas SOS tests ran in the CI were failing because the frames were popped too early. They need to stay until the RaiseException completes the first pass so that a crash dump on Windows contains them.

**Review by jkotas — APPROVED** [review]

**Comment by janvorli** [comment]
/ba-g the test failures are infra issues on azurelinux that occur on all recent CI runs.
