### PR TITLE
Correctly Save GC Mode on Suspension on Windows for SampleProfiler

### LINKED ISSUE #45179: SampleProfiler incorrectly marks all samples as external code on Windows
The SampleProfiler sends ThreadSample events that reference stacks.  The payload of these events is supposed to indicate what type of code was executing in the leaf frame _at the time of suspension_.

https://github.com/dotnet/runtime/blob/3f8966546a09ec104ca958eab20a22463907fed1/src/coreclr/src/vm/sampleprofiler.cpp#L238-L250

The SampleProfiler uses a cached value of `m_fPreemptiveGCDisabled` to determine whether to mark a sample as "managed" (GC was in COOP mode) or "external" (GC was in preemptive mode).

https://github.com/dotnet/runtime/blob/73a79932b9bfcf2078f21f173661f2d4afed9e90/src/coreclr/src/vm/threads.h#L4627-L4654

Currently, `SaveGCModeOnSuspension` is only called from `HandleGCSuspensionForInterruptedThread`.

https://github.com/dotnet/runtime/blob/c8c07900afdbf2103c1ccf9719005535edec851b/src/coreclr/src/vm/threadsuspend.cpp#L6071-L6096

Unfortunately, this code is only used for thread suspension on **_non_**-Windows platforms.  This means that all sample events on Windows are marked as "external" code since the underlying value is never changed from the uninitialized value of `0` (meaning preemptive mode).  On Linux/Mac systems, however, stacks are correctly labeled.

This value is used in tools like PerfView to do analysis on things like CPU blocking time.

We need to determine a location to call `SaveGCModeOnSuspension` that works for both platforms or add a call to the equivalent location on Windows.

One spot I'm vetting is here:
https://github.com/dotnet/runtime/blob/93cbc0974aa0475c586f40645e5b58a4b08ef017/src/coreclr/src/vm/threadsuspend.cpp#L3519-L3526

in `ThreadSuspend::SuspendRuntime` where it enumerates all the threads it is about to suspend.

I'm not sure how long this has been an issue, but I'm guessing it has been since this logic went in (~4 years ago circa .NET Core 2.2).

Is there another way we could transmit this information?  We could save the 4 bytes **_per_** sample event if we do away with this payload.  That can add up fast when you have ~1000 samples **_per_** thread **_per_** second.  That's roughly 4kb/s for a value that will _always_ be 1 or 2.  Could we intern this information directly into the stack events?  That would require a format change, though.

CC @sywhang @noahfalk @brianrob @tommcdon

### PR DESCRIPTION
**Pull request by josalem**
Fixes #45179

Move SaveGCModeOnSuspension to shared location rather than Unix only code path.

Before this change (as described in #45179), all events from the SampleProfiler on Windows would be marked as `UNMANAGED_CODE_TIME` samples. This was intended to only be the case for when a sample was collected while native code was on the stack.

This should make samples show up correctly in PerfView.

CC @tommcdon @noahfalk @brianrob

### CODE REVIEW

**Comment by josalem** [comment]
Sample of the fixed behavior (left is before, right is after):

image


The code traced:

```csharp
using System;
using System.Threading;
using System.Runtime.CompilerServices;

[MethodImpl(MethodImplOptions.NoInlining)]
int Foo(int bar) => bar + 1;

Console.WriteLine($"PID: {System.Diagnostics.Process.GetCurrentProcess().Id}");


while (true)
{
	// Should split unmanaged and managed suspensions about 50/50
    int i = 0;
    Thread.Sleep(TimeSpan.FromSeconds(1));
    DateTime then = DateTime.Now;
    while (DateTime.Now - then < TimeSpan.FromSeconds(1))
    {
        i = Foo(i);
    }
}
```

**Review by brianrob — APPROVED** [review]

**Review by davmason — APPROVED** [review]

File: src/coreclr/vm/threadsuspend.cpp [hunk 1]
```diff
@@ -3331,11 +3331,16 @@ void ThreadSuspend::SuspendRuntime(ThreadSuspend::SUSPEND_REASON reason)
...
 
+
                 // ::FlushProcessWriteBuffers above guarantees that the state that we see here
                 // is after the trap flag is visible to the other thread.
                 //
                 // In other words: any threads seen in preemptive mode are no longer interesting to us.
                 // if they try switch to cooperative, they would see the flag set. 
+#ifdef FEATURE_PERFTRACING
+                // Mark that the thread is currently in managed code.
+                thread->SaveGCModeOnSuspension();
```
Comment (hoyosjs) [inline src/coreclr/vm/threadsuspend.cpp:3342]: `HandleSuspensionForInterruptedThread` got called for every *safe* activation injection. This only happened on threads where: 1) a GC suspension was happening and 2) the top frame was managed. This will happen in other cases (debugger, profiler, rejit, etc) and will happen regardless of safepoints/sync state/frames.

Comment (hoyosjs) [reply src/coreclr/vm/threadsuspend.cpp:3342]: It's going to be consistent with the value before - it's just potentially going to be seen more often. One thing that I don't know for EP is mostly by this point there's threads that might have trapped already and switched to preemptive. If that's good enough for your calculations, then this looks good.
