### PR TITLE
Handle a null szPname field

### LINKED ISSUE #75667: System.NullReferenceException when using System.Speech 7.0.0-rc.1.22426.10 from Windows Forms
### .NET version

.NET 7.0.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET 6.0.0

### Issue description

When trying to use the latest version of [System.Speech](https://www.nuget.org/packages/System.Speech) from Windows Forms, it throws a System.NullReferenceException while trying to access the SpeechSynthesizer class.  

### Steps to reproduce

Run the attached project and click the button.

```csharp
        private void Button_Click(object sender, EventArgs e)
        {
            label.Text = string.Empty;
            using var speech = new SpeechSynthesizer();

            // System.Speech 7.0.0-rc.1.22426.10 throws System.NullReferenceException exception here.
            speech.SetOutputToDefaultAudioDevice();
            speech.SelectVoiceByHints(VoiceGender.Female);
            speech.SpeakProgress += (sender, e) => { label.Text += $"{e.Text} "; };

            speech.Speak("This is a test of the SpeechSynthesizer class.");

            label.Text += "\r\nFinished speaking...\r\n";
        }
```

Expected: The speech synthesizer should read out the contents of the string.

Actual: Accessing the newly created speech SpeechSynthesizer object throws a System.NullReferenceException exception.

Repro project:
[WinFormsSpeechRepro.zip](https://github.com/dotnet/winforms/files/9570983/WinFormsSpeechRepro.zip)

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes https://github.com/dotnet/runtime/issues/75667

### CODE REVIEW

File: src/libraries/Common/src/Interop/Windows/WinMm/Interop.waveOutGetDevCaps.cs [hunk 1]
```diff
@@ -50,7 +50,15 @@ public Native(WAVEOUTCAPS managed)
                         wMid = managed.wMid;
                         wPid = managed.wPid;
                         vDriverVersion = managed.vDriverVersion;
-                        managed.szPname.CopyTo(MemoryMarshal.CreateSpan(ref szPname[0], szPnameLength));
+                        Span<char> szPnameSpan = MemoryMarshal.CreateSpan(ref szPname[0], szPnameLength);
+                        if (managed.szPname is null)
+                        {
+                            szPnameSpan.Clear();
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/WinMm/Interop.waveOutGetDevCaps.cs:56]: Why is the Clear necessary?  If it's necessary here, I'm wondering if it's also necessary for the else path in case managed.szPname.Length < szPnameLength.

Comment (jkoritzinsky) [reply src/libraries/Common/src/Interop/Windows/WinMm/Interop.waveOutGetDevCaps.cs:56]: We probably should add it in the else path so we ensure the string is null-terminated if it's short. I'll make that change

**Comment by danmoseley** [comment]
If you add a call before this line
https://github.com/dotnet/runtime/blob/1d025196ae0d0f1e0b17e2e6033234e1937d997b/src/libraries/System.Speech/tests/SynthesizeRecognizeTests.cs#L41
to `SpeechSynthesizer.SetOutputToDefaultAudioDevice()` does it repro it? If so maybe throw that in this PR?

**Review by danmoseley — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
@danmoseley should I start a backport for this PR?

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
@jkoritzinsky, were you able to repro the exception before the fix and validate it doesn't repro after?

**Comment by jkoritzinsky** [comment]
I wasn't able to repro it initially, but based on the stack trace this was the only possible location for the exception.

I'll try reproing it without the fix again if that will help for servicing.

**Comment by stephentoub** [comment]
It'd both help with servicing and with confidence that we actually fixed the problem.

**Comment by jkoritzinsky** [comment]
I can't get it to repro locally on my machine. It's possible I didn't configure something right on the Windows side as there's some Windows configuration for System.Speech that I had to go through before any of the tests would run.

**Comment by danmoseley** [comment]
This code is pretty dependent on OS state, thinking back to bugs we've seen. I know that it can depend on eg what voices you have installed and other registry settings. Perhaps it would be OK if you can just set szPname to null in the debugger and then run.

**Comment by jkoritzinsky** [comment]
It looks like we won't even hit this code path if the following registry key isn't set: `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Speech\AudioOutput\DefaultTokenId`. I'm not sure how to manually set that registry key, so I can't repro this locally. @danmoseley any chance you have steps I can follow to set up the right key/value? (The call on line 48 below is what leads to the code that caused the exception).

https://github.com/dotnet/runtime/blob/b707fd62730fe2085f8157b238993b055ce12682/src/libraries/System.Speech/src/Internal/ObjectToken/SAPICategories.cs#L31-L57

**Comment by jkoritzinsky** [comment]
Figured out which control panel setting to set that key.

Repro'd locally without the fix and verified the fix locally.

**Comment by danmoseley** [comment]
Ha, yes there's an example of the [zillion registry settings](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee431801(v=vs.85))
