### PR TITLE
Fix Type.IsPublic for pointer and byref types

### LINKED ISSUE #12355: Type.IsPublic returns wrong answer for pointer and byref types
Even though `int` is public, `int*` and `int&` aren't. Sample code below.

```cs
Console.WriteLine(typeof(int).MakePointerType().IsPublic); // prints 'False', expected 'True'
Console.WriteLine(typeof(int).MakeByRefType().IsPublic); // prints 'False', expected 'True'
```

Perhaps an oversight when copying the elemental Type's visibility attributes into the pointer / byref Type we manfacture behind the scenes?

(Found by @stephentoub)

### PR DESCRIPTION
**Pull request by buyaa-n**
Fixes https://github.com/dotnet/runtime/issues/12355

Type.IsPublic returns false for pointer and byref types generated from a public type. Because `RuntimeTypeHandle::GetAttributes` returns 0 (NotPublic) for TypeDesc types (except generic type variables). Updated the code to return attributes from underlying element type (for pointer and byref types only)

### CODE REVIEW

File: src/coreclr/vm/typehandle.cpp [hunk 1]
```diff
@@ -244,6 +244,26 @@ TypeHandle TypeHandle::GetTypeParam() const
...
+// Obtain attributes of the element type from a byref or pointer type, returns tdPublic for generic type variables, 0 otherwise
+INT32 TypeHandle::GetElementTypeAttributes() const
+{
+    LIMITED_METHOD_DAC_CONTRACT;
+
+    if (IsGenericVariable())
+        return tdPublic;
+
+    if (IsPointer() || IsByRef()) {
+        TypeHandle elementType = GetTypeParam();
```
Comment (GrabYourPitchforks) [inline src/coreclr/vm/typehandle.cpp:256]: Suggestion: insert this assertion before the call to _GetTypeParam_.

```cpp
_ASSERTE(HasTypeParam());
```

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs [hunk 2]
```diff
@@ -1173,6 +1173,36 @@ public void MakePointerType(Type type)
...
+            yield return new object[] { typeof(int).MakeByRefType(), true };
+            yield return new object[] { typeof(int).MakePointerType(), true };
+            yield return new object[] { typeof(int).MakeArrayType(), true };
+            yield return new object[] { typeof(TI_BaseClass.InternalNestedClass).MakeByRefType(), false };
+            yield return new object[] { typeof(TI_BaseClass.InternalNestedClass).MakePointerType(), false };
+            yield return new object[] { typeof(TI_BaseClass.InternalNestedClass).MakeArrayType(), true };
+            yield return new object[] { typeof(TI_BaseClass.InternalNestedGenericClass<>).MakeGenericType(typeof(string)), false };
+            yield return new object[] { typeof(TI_BaseClass).MakeByRefType(), true };
+            yield return new object[] { typeof(TI_BaseClass).MakePointerType(), true };
+            yield return new object[] { typeof(TI_BaseClass).MakeArrayType(), true };
```
[the remark this answers is not in the document]
Comment (buyaa-n) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:1187]: i did not included that because i don't know how to create that type, i will try to find out, though the old behavior for that type not changed

**Review by lambdageek — COMMENTED** [review]
Mono changes LGTM

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (steveharter) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:1187]: Although function pointers are not really "supported" for introspection, they should return as `IntPtr` (there are some exceptions). So we could add some tests that use actual function pointers (delegate*)

[the remark this answers is not in the document]
Comment (buyaa-n) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:1187]: Added

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs [hunk 3]
```diff
@@ -1173,6 +1173,50 @@ public void MakePointerType(Type type)
...
+        {
+            Assert.Equal(expected, type.IsPublic);
+            Assert.Equal(!expected, type.IsNestedAssembly);
+        }
+
+        public delegate void PublicDelegate(string str);
+        internal delegate void InternalDelegate(string str);
+
+        [Fact]
+        public void DelegateTypesIsPublic()
```
Comment (steveharter) [inline src/libraries/System.Reflection/tests/TypeInfoTests.cs:1202]: Please split this into separate `Delegate` and `delegate*` (fcn pointer) tests for clarity since internally they are completely different.

Also adding ```Assert.False(typeof(InternalDelegate).IsPublic)``` would be good.

**Review by steveharter — APPROVED** [review]
LGTM; some minor test feedback

File: src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs [hunk 4]
```diff
@@ -672,7 +672,8 @@ public class IntPointerTests : TypePropertyTestBase
     {
         public override Type CreateType() => typeof(int).MakePointerType();
 
-        public override TypeAttributes Attributes => TypeAttributes.Class;
+        public override TypeAttributes Attributes => PlatformDetection.IsMonoRuntime ? TypeAttributes.Public :
```
Comment (jkotas) [inline src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs:675]: Can we fix Mono and/or CoreCLR to have identical behavior here?

**Comment by jkotas** [comment]
Does System.Reflection.MetadataLoadContext need this fix as well?

File: src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs (hunk 4 above)
Comment (buyaa-n) [reply src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs:675]: I saw several existing tests having conditional behavior so i thought difference is expected
https://github.com/dotnet/runtime/blob/11076ec2edbcd1e0972c4811299049cf7be19c83/src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs#L538-L540
https://github.com/dotnet/runtime/blob/11076ec2edbcd1e0972c4811299049cf7be19c83/src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs#L1096-L1098
Also mono and CLR implementations looks quite different, if we want same behavior i beleive that needs quite a lot code/test change needed.

**Comment by buyaa-n** [comment]
> @buyaa-n note some CI failures with the new tests

Looking, thanks

> Does System.Reflection.MetadataLoadContext need this fix as well?

Will check, thanks

File: src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs (hunk 4 above)
Comment (buyaa-n) [reply src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs:675]: For the `Type.IsPublic` API side both has identical behavior here, but CLR produce more attributes other than `TypeAttributes.Public`, please let me know if we want same behavior and what/which behavior is expected

**Comment by buyaa-n** [comment]
A question about the CI test failure: for `Assert.True(typeof(delegate*<string, int>).IsPublic);` the mono and CoreCLR behavior was different even before this change, for CLR:
https://github.com/dotnet/runtime/blob/f1337d9079e4a95e4c7f51f3bddf632bdfb905ce/src/coreclr/vm/runtimehandles.cpp#L811-L813
For mono:
https://github.com/dotnet/runtime/blob/f1337d9079e4a95e4c7f51f3bddf632bdfb905ce/src/mono/mono/metadata/icall.c#L1805-L1806
Now i am not sure which value is expected, I guess it should be public, but want to confirm, please let me know what you think @steveharter @jkotas @GrabYourPitchforks

**Comment by buyaa-n** [comment]
> Does System.Reflection.MetadataLoadContext need this fix as well?

MLC just returning `TypeAttributes.AnsiClass`, should we change it @steveharter?
https://github.com/dotnet/runtime/blob/ced5e7a2fddd9db9c89f9fc43b3ddceba6a99d3e/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoPointerType.cs#L28

https://github.com/dotnet/runtime/blob/ced5e7a2fddd9db9c89f9fc43b3ddceba6a99d3e/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoByRefType.cs#L28

**Comment by jkotas** [comment]
> MLC just returning TypeAttributes.AnsiClass

The value of `TypeAttributes.AnsiClass` is `0`. It is better to think about it as returning `default`. It would be actually better to write it as returning `default` instead `TypeAttributes.AnsiClass`.

**Comment by buyaa-n** [comment]
> The value of `TypeAttributes.AnsiClass` is `0`. It is better to think about it as returning `default`. It would be actually better to write it as returning `default` instead `TypeAttributes.AnsiClass`.

Right 0, so it was same as what `GetAttributes()` method was returning, so i need to update MLC, thanks !
https://github.com/dotnet/runtime/blob/4c2ea7e9010e9c71bfba332e430e92f00e19c04e/src/coreclr/vm/runtimehandles.cpp#L809-L815

File: src/mono/mono/metadata/icall.c [hunk 5]
```diff
@@ -1802,8 +1802,8 @@ ves_icall_RuntimeTypeHandle_GetAttributes (MonoQCallTypeHandle type_handle)
 {
 	MonoType *type = type_handle.type;
 
-	if (m_type_is_byref (type) || type->type == MONO_TYPE_PTR || type->type == MONO_TYPE_FNPTR)
-		return TYPE_ATTRIBUTE_NOT_PUBLIC;
+	if (type->type == MONO_TYPE_FNPTR)
+		return TYPE_ATTRIBUTE_PUBLIC;
```
Comment (jkotas) [inline src/mono/mono/metadata/icall.c:1806]: It looks odd that we are unconditionally returning public for function pointers, but not for regular pointers.

File: src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs (hunk 4 above)
Comment (jkotas) [reply src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs:675]: > I saw several existing tests having conditional behavior so i thought difference is expected

The TypeAttributes flags are mix of flags that describe public surface (e.g. TypeAttributes.Public/NonPublic) and flags that describe internal implementation details (e.g. TypeAttributes.SequentialLayout/AutoLayout). The existing Mono conditions in these tests are for flags that describe internal implementation details because the internal implementation is actually different. That's ok - we do not guarantee that the internal implementation details are same between all runtimes.

File: src/mono/mono/metadata/icall.c (hunk 5 above)
Comment (buyaa-n) [reply src/mono/mono/metadata/icall.c:1806]: Yes it is odd, i guess the visibility should be same as the function it is pointing to, but at least for the test case i have added `Assert.True(typeof(delegate*<string, int>).IsPublic);` that is undefined, so i assumed it could be constant, though we might want to return the default, not public, and might need to add condition for the function it is pointing

File: src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs (hunk 4 above)
Comment (jkotas) [reply src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs:675]: I am starting to think that we may want to unconditionally return TypeAttributes.Public for pointers and byrefs instead of inheriting it from element type, similar to what we are doing for generic variables.

The type visibility encoded in TypeAttribute flags is a local property of the given constituent. It does not says whether the composed type can be accessed publicly. For example, `typeof(List<MyPrivateType>).IsPublic` is going to be true since `List<T>` is a public type, even though this type is not actually publicly accessible.

Note that we also have `Type.IsVisible` property that checks local type visibility of all constituents and returns true only if all constituents are public.

Comment (buyaa-n) [reply src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs:675]: Returning true for `typeof(InternalStruct*).IsPublic` looks a bit odd to me 
```cs
    Console.WriteLine(typeof(PublicStruct).IsPublic); // true
    Console.WriteLine(typeof(PublicStruct*).IsPublic); // true
    Console.WriteLine(typeof(PublicStruct*).IsVisible); // true
    Console.WriteLine(typeof(InternalStruct).IsPublic); // false
    Console.WriteLine(typeof(InternalStruct*).IsPublic); // true
    Console.WriteLine(typeof(InternalStruct*).IsVisible); // false
```

Comment (jkotas) [reply src/libraries/System.Runtime/tests/System/Type/TypePropertyTests.cs:675]: I think we should be treating generic types and parametrized type the same way. They are very similar and partially redundant concepts. If we have had generics in the first .NET release (.NET Framework 1.0), parametrized types would not possibly exist at all, and pointers or arrays would just be special generic types.

So I think the output of this:
```
Console.WriteLine(typeof(List<InternalStruct>).IsPublic);
Console.WriteLine(typeof(List<InternalStruct>).IsVisible);
should be identical to the output of this:
```
Console.WriteLine(typeof(InternalStruct*).IsPublic);
Console.WriteLine(typeof(InternalStruct*).IsVisible);
```

File: src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs [hunk 6]
```diff
@@ -464,6 +464,37 @@ public static void TestIsValueType()
...
+        [MemberData(nameof(TypeDescTypesIsPublic_TestData))]
+        public static void TypeDescTypesIsPublic(Type type, bool isPublic, bool isVisible)
+        {
+            Assert.Equal(isPublic, type.IsPublic);
+            Assert.Equal(!isPublic, type.IsNestedAssembly);
+            Assert.Equal(isVisible, type.IsVisible);
+        }
+
+        [Fact]
+        [SkipOnMono("System.TypeLoadException : Could not find type 'System.MonoFNPtrFakeClass'")]
```
Comment (jkotas) [inline src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs:491]: What is the `MonoFNPtrFakeClass` type? Is this a known bug?

File: src/coreclr/vm/runtimehandles.cpp [hunk 7]
```diff
@@ -808,7 +808,7 @@ FCIMPL1(INT32, RuntimeTypeHandle::GetAttributes, ReflectClassBaseObject *pTypeUN
 
     if (typeHandle.IsTypeDesc()) {
 
-        if (typeHandle.IsGenericVariable()) {
+        if (typeHandle.IsGenericVariable() || typeHandle.IsByRef() || typeHandle.IsPointer() || typeHandle.IsFnPtrType()) {
```
[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/vm/runtimehandles.cpp:811]: This condition should not be necessary. I would delete it.

File: src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoByRefType.cs [hunk 8]
```diff
@@ -25,7 +25,7 @@ internal RoByRefType(RoType elementType)
 
         public sealed override int GetArrayRank() => throw new ArgumentException(SR.Argument_HasToBeArrayClass);
 
-        protected sealed override TypeAttributes ComputeAttributeFlags() => TypeAttributes.AnsiClass;
+        protected sealed override TypeAttributes ComputeAttributeFlags() => TypeAttributes.Public;
```
Comment (jkotas) [inline src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoByRefType.cs:28]: Could you please also change this: https://github.com/dotnet/runtime/blob/b2dc37ba181a7fa4427e717eab819ba3543d0ae4/src/coreclr/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/TypeInfos/RuntimeHasElementTypeInfo.cs#L162 to return `TypeAttributes.Public`

Comment (buyaa-n) [reply src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoByRefType.cs:28]: Sure

File: src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs (hunk 6 above)
Comment (buyaa-n) [reply src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs:491]: > What is the MonoFNPtrFakeClass type?

Not sure, only one hit found, seems function pointer name created in mono, 
https://github.com/dotnet/runtime/blob/053a472be0143bda0891c715d7b2ce7398538127/src/mono/mono/metadata/class-init.c#L1541

> Is this a known bug?

Guess not know, but seems [function pointer is not supported in MLC](https://github.com/dotnet/runtime/issues/43791), probably i should not have added this test in MLC

Comment (jkotas) [reply src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs:491]: > Not sure, only one hit found, seems function pointer name created in mono,

There should be no way for MLC to hit Mono runtime reflection implementation. Either this condition is bogus; or there is something really wrong.

Comment (buyaa-n) [reply src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs:491]: Here is [full log](https://helix.dot.net/api/2019-06-17/jobs/56c812f4-26b8-46ae-b108-e837c360f2fe/workitems/System.Reflection.MetadataLoadContext.Tests/console), it hit mono runtime
```log
System.Reflection.Tests.TypeTests.FunctionPointerTypeIsPublic [FAIL]
      System.TypeLoadException : Could not find type 'System.MonoFNPtrFakeClass' in assembly '/private/tmp/helix/working/A5E8094B/p/shared/Microsoft.NETCore.App/7.0.0/System.Private.CoreLib.dll'.
      Stack Trace:
        /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Helpers.cs(298,0): at System.Reflection.TypeLoading.Helpers.LoadTypeFromAssemblyQualifiedName(String name, RoAssembly defaultAssembly, Boolean ignoreCase, Boolean throwOnError)
        /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Assemblies/RoAssembly.cs(106,0): at System.Reflection.TypeLoading.RoAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
        /_/src/libraries/System.Reflection.MetadataLoadContext/tests/src/TestUtils/TestUtils.JittedRuntimes.cs(40,0): at System.Reflection.Tests.TestUtils.<>c__DisplayClass20_0.<Project>b__1(Type t)
        /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs(1146,0): at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory)
        /_/src/libraries/System.Reflection.MetadataLoadContext/tests/src/TestUtils/TestUtils.JittedRuntimes.cs(40,0): at System.Reflection.Tests.TestUtils.Project(Type type)
        /_/src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs(493,0): at System.Reflection.Tests.TypeTests.FunctionPointerTypeIsPublic()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs(386,0): at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
  Finished:    System.Reflection.MetadataLoadContext.Tests
```

File: src/libraries/System.Reflection.MetadataLoadContext/tests/src/SampleMetadata/SampleMetadata.cs [hunk 9]
```diff
@@ -553,4 +553,10 @@ public class ClassWithDefaultMember1<T> where T : ClassWithDefaultMember1<T>
     {
         public int Yes;
     }
+
+    public class PubilcClass
```
Comment (jkotas) [inline src/libraries/System.Reflection.MetadataLoadContext/tests/src/SampleMetadata/SampleMetadata.cs:557]: Typo: PubilcClass

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs [hunk 10]
```diff
@@ -1173,6 +1173,56 @@ public void MakePointerType(Type type)
             Assert.True(pointerType.IsPointer);
         }
 
+        public static IEnumerable<object[]> TypeDescTypesIsPublic_TestData()
```
Comment (jkotas) [inline src/libraries/System.Reflection/tests/TypeInfoTests.cs:1176]: `TypeDesc` is internal implementation detail of CoreCLR runtime. This test name does not make sense on Mono or NativeAOT. 

Also, this is testing more than `TypeDesc`s - for example, `TI_BaseClass.InternalNestedGenericClass<string>` is not represented by `TypeDesc`.

File: src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs (hunk 6 above)
Comment (jkotas) [reply src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs:491]: Ok, so this is actually a problem in the test helper method. The representation of function pointers is broken in reflection stack (https://github.com/dotnet/runtime/issues/11354), but it is broken in a different way on CoreCLR vs. Mono.

I think the test should be disabled against https://github.com/dotnet/runtime/issues/11354. It may be a good idea to disable it unconditionally. The test happens to pass outside Mono currently, but it is not testing what its name suggests there.

**Review by jkotas — APPROVED** [review]
LGTM. Thank you!

**Comment by buyaa-n** [comment]
Thank you all the your review and suggestions! Build [failure unrelated](https://github.com/dotnet/runtime/issues/65681), merging
