### PR TITLE
Imply NoInlining when only NoOptimization is set

### LINKED ISSUE #111298: `MethodImplOptions.NoOptimization` ignored for inlined function
### Description

`MethodImplOptions.NoOptimization` flag seems to be ignored when the method is inlined.

### Reproduction Steps

```cs
using System;
using System.Threading;
using System.Runtime.CompilerServices;

public class C
{
    private int _field;
    
    public void N()
    {
        _field++;   
    }
    
    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void Wrapper()
    {
        N();
    }
    
    public void Test(long count)
    {
        for (long i = 0; i < count; ++i)
        {
            Wrapper();
        }
    }
}
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgBUALWbAEwEsAdgHMA3DXpNWAJQCuAjH3wwWAYQj4ADnwA2MKAGU9ANz5gYuMdXEBmJqQYqaAbxoM3DDVD5HsGGA0EMBgB9ADM+GG0eS3cGV3diW2IUBgA5AAoASni3F2pY2LCIqIBqEpF3HIYAXyqqgG0AWRgMDggeAElNbXTm1vaujW0AeQ0FCAFcFlSIUYV8PgAvXz4JzIBdKsSmFIB1KGwNDT0sqryC9wzMmPda/Mr7t23khjZzDHTtCaEGSDkMbKPBjnC4MULQBifb4BBgAXgYdAqfAYAB5fhB/hUynxAaDgVU8ftDscoFkbhc7rE7tUgA==

### Expected behavior

The inlined method is not optimized. In this example, the wrapped call should not be inlined.

### Actual behavior

The inlined method is optimized. The wrapped call is also inlined.

### Regression?

Not sure.

### Known Workarounds

Add `MethodImplOptions.NoInlining` flag.

### Configuration

```
Windows 10 (10.0.19045.5247/22H2/2022Update)
AMD Ryzen 7 9800X3D 4.70GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 9.0.101
  [Host]     : .NET 8.0.11 (8.0.1124.51707), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  DefaultJob : .NET 8.0.11 (8.0.1124.51707), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
```

### Other information

Investigation of improving BenchmarkDotNet (https://github.com/dotnet/BenchmarkDotNet/pull/2334). The attempt is to call the benchmarked method directly without inlining the call. `NoInlining` flag on the wrapper method seems to work well for most CPUs (tested on AMD Phenom II, AMD Zen 3, Intel Core 9, Apple M3), but gets <s>bad</s> weird results specifically on AMD Zen 4+ architectures. Inlining the wrapper method seemed to get good timings with the test, but bad disassembly due to both calls getting inlined (and possibly incorrect results if such benchmark methods are actually inlined and optimized). Not sure what to do about it.

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/111298

Alternatively, we can only change `IsMiNoInlining`'s implementation to check either flag.

### CODE REVIEW

**Comment by jkotas** [comment]
Do we need the same change in AOT compilers?

**Comment by EgorBo** [comment]
> Do we need the same change in AOT compilers?

Oops, changed for AOT too.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs [hunk 1]
```diff
@@ -1299,9 +1299,9 @@ private bool canTailCall(CORINFO_METHOD_STRUCT_* callerHnd, CORINFO_METHOD_STRUC
                     return false;
                 }
 
-                // Do not tailcall from methods that are marked as noinline (people often use no-inline
+                // Do not tailcall from methods that are marked as NoInlining or NoOptimization (people often use no-inline
                 // to mean "I want to always see this method in stacktrace")
-                if (caller.IsNoInlining)
+                if (caller.IsNoInlining || caller.IsNoOptimization)
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:1304]: Is it necessary to check for NoOptimization here? I would expect that the JIT disables tailcall optimizations when the method is marked NoOptimization.

Comment (EgorBo) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:1304]: @jkotas um.. jit is not aware that a call has NoOptimization on it so it does emit tail calls for it, [example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4axAMxNSDITQDeNBqYYmzzJExQMAYhAgAKAJQXTx6me8MAQtihXNQYAehCGDGwpODBsSWkAE3cGAF8aZIBtAFkYDAALCASASXFJJxz8wpKxSQB5MT4ILlwWADkIer58XgAvbEauFwBdZKsbPwDXZM8fMzCGXFEYBmBeAHMGSATlsVgFGB5eLg3eDAYAMyhRFZgjk65JI5gkr1mmcgBOIOTvZi+XDSvWZ/b5AnwggE/SyfUFvd7/QFwiGIt7IqGmNFg34wyFY6EI9Hw2GonEo4GkwmY7xpagpIA===)

**Review by jkotas — APPROVED** [review]
