### PR TITLE
Fix allocation of empty array in the frozen heap for collectible types

### LINKED ISSUE #100437: Empty array allocated on the Frozen Heap for a Collectible type?
Hello folks,

Apologies, it's not a fully reproducible bug as we haven't tried yet to reproduce it with a simpler sample, but we have a suspicion.

We are investigating an error where we have the GC marking of frozen objects `gc_heap::mark_ro_segments()`that is crashing. 

One place that we are curious about is in `TryAllocateFrozenSzArray`:

https://github.com/dotnet/runtime/blob/7486be885b298aef622833bec509732e6b3f1667/src/coreclr/vm/gchelpers.cpp#L516-L520

Where it seems that we could allow to allocate an empty array for collectible MethodTable in the Frozen heap. Shouldn't it be something like this instead?

```cpp
    if (pArrayMT->Collectible() || (pArrayMT->ContainsPointers() && cElements > 0))
    {
        // For arrays with GC pointers we can only work with empty arrays
        return NULL;
    }
```

Before we investigate this further, any thoughts?

cc: @EgorBo

### PR DESCRIPTION
**Pull request by xoofx**
Fixes #100437

An empty array should not be allocated on a frozen heap if its type is coming from a collectible assembly.

Might be difficult to bring a proper test (e.g is there an API to check if an object is instantiated in a frozen heap?). If it is required, guidance appreciated.

This fix should be backported to `net8.0` as well.

### CODE REVIEW

File: src/coreclr/vm/gchelpers.cpp [hunk 1]
```diff
@@ -513,9 +513,11 @@ OBJECTREF TryAllocateFrozenSzArray(MethodTable* pArrayMT, INT32 cElements)
 
     // The initial validation is copied from AllocateSzArray impl
 
-    if (pArrayMT->ContainsPointers() && cElements > 0)
+    if (pArrayMT->Collectible() || (pArrayMT->ContainsPointers() && cElements > 0))
```
Comment (MichalPetryka) [inline src/coreclr/vm/gchelpers.cpp:516]: Maybe make it a separate if so that it's easier to read?

Comment (xoofx) [reply src/coreclr/vm/gchelpers.cpp:516]: There are several places in this file using similar condition checks, so I would think it is not necessary.

**Comment by xoofx** [comment]
My colleague that has been investigating this is also suggesting adding an assert in `FrozenObjectHeapManager::TryAllocateObject` to check that a type cannot be collectible.

https://github.com/dotnet/runtime/blob/34d13b27a4f0d62367145bcc1f67f7044ad2328a/src/coreclr/vm/frozenobjectheap.cpp#L48-L49

Thoughts?

I can add it as part of this PR.

**Comment by jkotas** [comment]
> adding an assert

Sounds good to me.

We should also add a test that hits it.

**Comment by jkotas** [comment]
> We should also add a test that hits it.

Let me know if you need help with the test.

**Comment by xoofx** [comment]
> Let me know if you need help with the test.

Yes, please, a starting place would be helpful! 😅

**Comment by cshung** [comment]
> is there an API to check if an object is instantiated in a frozen heap

Yes, `IGCHeap::IsInFrozenSegment` should do.

https://github.com/dotnet/runtime/blob/d1cc577eda302c25a29fdf12bf5ab23a5c419453/src/coreclr/gc/gcinterface.h#L974

**Comment by xoofx** [comment]
> Yes, `IGCHeap::IsInFrozenSegment` should do.

Thanks! I meant from C# as I'm not familiar how I will be able to make tests only from C++.

**Comment by jkotas** [comment]
> is there an API to check if an object is instantiated in a frozen heap

We prefer to test observable behavior like that the program does not crash. You do not need an API that checks if an object is instantiated in a frozen heap for that.

**Comment by jkotas** [comment]
> Yes, please, a starting place would be helpful!

This will crash with high probability due to this bug:
```
using System.Runtime.Loader;

public class Program
{
    static void Main()
    {
        WeakReference[] wrs = new WeakReference[10];
        for (int i = 0; i < wrs.Length; i++)
        {
            var alc = new MyAssemblyLoadContext();
            var a = alc.LoadFromAssemblyPath(typeof(Program).Assembly.Location);
            wrs[i] = (WeakReference)a.GetType("Program").GetMethod("Work").Invoke(null, null);
            GC.Collect();
        }

        foreach (var wr in wrs)
        {
            Console.WriteLine(wr.Target);
        }
    }

    public static WeakReference Work()
    {
        return new WeakReference(Array.Empty<Program>());
    }
}

class MyAssemblyLoadContext : AssemblyLoadContext
{
    public MyAssemblyLoadContext()
        : base(isCollectible: true)
    {
    }
}
```

**Comment by xoofx** [comment]
> We prefer to test observable behavior like that the program does not crash. You do not need an API that checks if an object is instantiated in a frozen heap for that.
> This will crash with high probability due to this bug:

Makes sense! Where should I add such a test? In `src\tests\GC\Scenarios` but I see also that there is a `src\tests\GC\API\Frozen`?

**Comment by jkotas** [comment]
As I was writing the test, I have realized that there is an opposite problem too: The frozen object allocated in shared generic static constructor may be end up leaking:
```
class MyG<T>
{
    static object s = new object(); // This will be allocate on frozen heap, but it is going to leak if T is collectible
}
```
I am not sure what's the best way to fix this leak. We can either detect and reject these problematic patterns as canidates for frozen heap allocation, or we need to pass the containing generic type to the MayBeFrozen allocation helper. cc @EgorBo

**Comment by jkotas** [comment]
> Where should I add such a test?

I would add it under src\tests\JIT\Regression\JitBlue. This is a codegen related problem, so the regression test for it belongs under JIT tests.

**Comment by xoofx** [comment]
Added the test with commit 1189eec94630a0ea3445fa2a24302fbc7acf6ad2 but I don't know how to run it. I tried `.\build.cmd clr+libs+libs.tests -rc checked -lc release -test` but doesn't look that it ran it.

**Comment by EgorBo** [comment]
> As I was writing the test, I have realized that there is an opposite problem too: The frozen object allocated in shared generic static constructor may end up leaking:
> 
> ```cs
> class MyG<T>
> {
>      // This will be allocated on frozen heap, but it is going to leak if T is collectible
>     static object s = new object();
> }
> ```
> 
> I am not sure what's the best way to fix this leak. We can either detect and reject these problematic patterns as canidates for frozen heap allocation, or we need to pass the containing generic type to the MayBeFrozen allocation helper. cc @EgorBo

Good point! I propse this patch [here](https://github.com/dotnet/runtime/blob/b7d91f230846587d959fdeb711a4c24eeeca9349/src/coreclr/jit/importer.cpp#L9284):
```diff
-    if ((fi.fieldFlags & flagsToCheck) == flagsToCheck)
+    if (((fi.fieldFlags & flagsToCheck) == flagsToCheck) &&
+       ((info.compCompHnd->getClassAttribs(info.compClassHnd) & CORINFO_FLG_SHAREDINST) == 0))
```

the logic to detect candidates for NonGC allocators is quite trivial here, I have a prototype for a more advanced version, but it's not ready yet.

**Comment by EgorBo** [comment]
> Good point! I propose this patch [here](https://github.com/dotnet/runtime/blob/b7d91f230846587d959fdeb711a4c24eeeca9349/src/coreclr/jit/importer.cpp#L9284):

Ah, it's a bit too conservative. Basically, with this patch we'll never optimize `Array.Empty<string>()` into a nongc handle. I presume a proper way is to pass type of current class as an argument in frozen allocator.. but that is not a trivial change so probably for now we should take the conservative patch?

**Comment by jkotas** [comment]
> Ah, it's a bit too conservative. Basically, with this patch we'll never optimize Array.Empty<string>() into a nongc handle. I presume a proper way is to pass type of current class as an argument in frozen allocator.. but that is not a trivial change so probably for now we should take the conservative patch?

Yes, the conservative fix can be backport candidate. The full fix would be hard to backport.

@xoofx Would you like to include it in this PR? (The test for this case can have similar structure - it should use weak handle to verify that the object is gone after the collectible assembly is unloaded.)

File: src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+public class Runtime_100437
+{
+    [Fact]
+    public static int TestCollectibleEmptyArrayNotInFrozenHeap()
+    {
+        WeakReference[] wrs = new WeakReference[10];
+        for (int i = 0; i < wrs.Length; i++)
+        {
+            var alc = new MyAssemblyLoadContext();
+            var a = alc.LoadFromAssemblyPath(typeof(Runtime_100437).Assembly.Location);
```
Comment (jkotas) [inline src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs:18]:
```suggestion
        string assemblyPath = Runtime_100437).Assembly.Location;
        
        // Skip this test for single file  
        if (string.IsNullOrEmpty(assemblyPath))
            return;

        WeakReference[] wrs = new WeakReference[10];
        for (int i = 0; i < wrs.Length; i++)
        {
            var alc = new MyAssemblyLoadContext();
            var a = alc.LoadFromAssemblyPath(assemblyPath);
```

File: src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+        }
+
+        int result = 0;
+        foreach (var wr in wrs)
+        {
+            // This is testing that the empty array from Work(), if collected, should not have been allocated on the Frozen heap
+            // otherwise it will result in a random crash.
+            result += wr.Target?.ToString()?.GetHashCode() ?? 0;
+        }
+        return result;
```
Comment (jkotas) [inline src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs:30]:
```suggestion
        foreach (var wr in wrs)
        {
            // This is testing that the empty array from Work(), if collected, should not have been allocated on the Frozen heap
            // otherwise it will result in a random crash.
            GC.KeepAlive(wr.Target?.ToString());
        }
```
The historic convention for int returning src\tests is that 100 indicates success and everything else is failure. So returning result like this would not work.

File: src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.csproj [hunk 4]
```diff
@@ -0,0 +1,8 @@
+<Project Sdk="Microsoft.NET.Sdk">
+  <PropertyGroup>
+    <Optimize>True</Optimize>
+  </PropertyGroup>
```
Comment (jkotas) [inline src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.csproj:4]:
```suggestion
```
This test should work both with optimizations on and off.

**Comment by xoofx** [comment]
> @xoofx Would you like to include it in this PR? (The test for this case can have similar structure - it should use weak handle to verify that the object is gone after the collectible assembly is unloaded.)

Sure, I will have a look.

File: src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.csproj (hunk 4 above)
Comment (xoofx) [reply src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.csproj]: Fixed by commit cd1ebe0

File: src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs (hunk 3 above)
Comment (xoofx) [reply src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs]: Trying a fix in latest commit.

File: src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs (hunk 2 above)
Comment (xoofx) [reply src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs]: Applied

**Comment by xoofx** [comment]
> @xoofx Would you like to include it in this PR? (The test for this case can have similar structure - it should use weak handle to verify that the object is gone after the collectible assembly is unloaded.)

I have added 97d9d76 with the fix from @EgorBo and a test for the collectible Generic + Static readonly.

File: src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+            GC.Collect();
+        }
+
+        int result = 0;
+        foreach (var wr in wrs)
+        {
+            result += wr.Target?.ToString()?.GetHashCode() ?? 0;
+        }
+        return (result & 100) | 100;
+    }
```
Comment (jkotas) [inline src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs:63]:
```suggestion
    public static int TestCollectibleNonGenericReadOnlyStaticInSharedGenericType()
    {
        string assemblyPath = typeof(Runtime_100437).Assembly.Location;

        // Skip this test for single file
        if (string.IsNullOrEmpty(assemblyPath))
            return 100;

        WeakReference wr = CreateReadOnlyStaticWeakReference();

        for (int i = 0; i < 10; i++)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
            if (wr.Target == null)
                return 100;
        }

        Console.WriteLine("Test Failed")
        return 1;
        
        [MethodImpl(MethodImplOptions.NoInlining)]
        WeakReference CreateReadOnlyStaticWeakReference()
        {
                AssemblyLoadContext alc = new MyAssemblyLoadContext();
                Assembly a = alc.LoadFromAssemblyPath(assemblyPath);
                return (WeakReference)a.GetType(nameof(Runtime_100437)).GetMethod(nameof(WorkForGenericCase)).Invoke(null, null);
            }
        }
    }
```
This variant needs to check the static disappears after the ALC is collected.

File: src/coreclr/vm/gchelpers.cpp (hunk 1 above)
Comment (jkotas) [inline src/coreclr/vm/gchelpers.cpp:516]:
```suggestion
    if (pArrayMT->ContainsPointers() && cElements > 0)
```
This change is unnecessary with the change in the JIT

File: src/coreclr/vm/gchelpers.cpp [hunk 6]
```diff
@@ -515,7 +515,9 @@ OBJECTREF TryAllocateFrozenSzArray(MethodTable* pArrayMT, INT32 cElements)
 
     if (pArrayMT->ContainsPointers() && cElements > 0)
     {
-        // For arrays with GC pointers we can only work with empty arrays
+        // We cannot allocate in the frozen heap if:
+        // - the array type is collectible
+        // - or for non empty arrays with GC pointers
```
Comment (jkotas) [inline src/coreclr/vm/gchelpers.cpp:520]:
```suggestion
        // For arrays with GC pointers we can only work with empty arrays
```

File: src/coreclr/vm/gchelpers.cpp [hunk 7]
```diff
@@ -1122,7 +1124,7 @@ OBJECTREF TryAllocateFrozenObject(MethodTable* pObjMT)
 
     SetTypeHandleOnThreadForAlloc(TypeHandle(pObjMT));
 
-    if (pObjMT->ContainsPointers() || pObjMT->IsComObjectType())
+    if (pObjMT->Collectible() || pObjMT->ContainsPointers() || pObjMT->IsComObjectType())
```
Comment (jkotas) [inline src/coreclr/vm/gchelpers.cpp:1127]:
```suggestion
    if pObjMT->ContainsPointers() || pObjMT->IsComObjectType())
```

File: src/coreclr/vm/gchelpers.cpp [hunk 8]
```diff
@@ -1122,7 +1122,7 @@ OBJECTREF TryAllocateFrozenObject(MethodTable* pObjMT)
 
     SetTypeHandleOnThreadForAlloc(TypeHandle(pObjMT));
 
-    if (pObjMT->ContainsPointers() || pObjMT->IsComObjectType())
+    if pObjMT->ContainsPointers() || pObjMT->IsComObjectType())
```
Comment (jkotas) [inline src/coreclr/vm/gchelpers.cpp:1125]:
```suggestion
    if (pObjMT->ContainsPointers() || pObjMT->IsComObjectType())
```

File: src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs (hunk 5 above)
Comment (jkotas) [reply src/tests/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437.cs:63]: Actually, this is not testing the interesting path.

**Review by EgorBo — APPROVED** [review]

**Comment by jkotas** [comment]
I have pushed test update that hits all interesting cases.

File: src/coreclr/vm/gchelpers.cpp (hunk 1 above)
Comment (MichalPetryka) [reply src/coreclr/vm/gchelpers.cpp]: What check blocks collectible value types without this? Isn't the JIT check only for shared generics so reference types?

Comment (jkotas) [reply src/coreclr/vm/gchelpers.cpp]: Existing `CORJIT_FLAG_FROZEN_ALLOC_ALLOWED` check handles that.

Comment (MichalPetryka) [reply src/coreclr/vm/gchelpers.cpp]: > Existing `CORJIT_FLAG_FROZEN_ALLOC_ALLOWED` check handles that.

I thought that'd only check if the type we're currently compiling is in a collectible assembly, not if its generic parameters are.

Comment (jkotas) [reply src/coreclr/vm/gchelpers.cpp]: `CORJIT_FLAG_FROZEN_ALLOC_ALLOWED` covers generic parameters as well.

File: src/tests/issues.targets [hunk 9]
```diff
@@ -1393,6 +1393,9 @@
         <ExcludeList Include="$(XunitTestBinBase)/GC/Scenarios/LeakGen/leakgen/**">
             <Issue>PlatformDetection.IsPreciseGcSupported false on mono</Issue>
         </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/JIT/Regression/JitBlue/Runtime_100437/**">
```
Comment (jkotas) [inline src/tests/issues.targets:1396]:
```suggestion
        <ExcludeList Include="$(XunitTestBinBase)/JIT/Regression/JitBlue/Runtime_100437/Runtime_100437/**">
```

**Comment by EgorBo** [comment]
I also usually struggle finding the right syntax for issues.props 😐

**Comment by jkotas** [comment]
I have opened https://github.com/dotnet/runtime/issues/100510 on re-enabling the optimization in shared generic with proper lifetime checks.

https://github.com/dotnet/runtime/pull/100509 is the backport to .NET 8.

@xoofx Thank you for your help with getting this bug found and fixed!

**Comment by xoofx** [comment]
> @xoofx Thank you for your help with getting this bug found and fixed!

Most of the hard work investigating the crash from our side came from @alexey-zakharov ☺️ 

We are super glad that a quick fix was found, as we are heavily relying on collectible ALC and that bug haunted several crashes on our CI. Thanks a lot for helping with it!
