### PR TITLE
Fix nullable annotations for ImmutableArray cast methods

### LINKED ISSUE #39799: ImmutableArray.CastUp and Cast should be annotated with `class?`
### Description

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L327
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L347

Both of these methods are annotated as `where TOther : class`. However, it's perfectly reasonable to substitute a nullable type for `TOther` there, and they should be annotated as `class?` because of it.

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Fixes #39799

### CODE REVIEW

File: src/libraries/System.Collections.Immutable/ref/System.Collections.Immutable.cs [hunk 1]
```diff
@@ -122,9 +122,9 @@ public partial struct ImmutableArray<T> : System.Collections.Generic.ICollection
         public System.ReadOnlyMemory<T> AsMemory() { throw null; }
         public System.ReadOnlySpan<T> AsSpan() { throw null; }
 #endif
-        public System.Collections.Immutable.ImmutableArray<TOther> As<TOther>() where TOther : class { throw null; }
-        public System.Collections.Immutable.ImmutableArray<TOther> CastArray<TOther>() where TOther : class { throw null; }
-        public static System.Collections.Immutable.ImmutableArray<T> CastUp<TDerived>(System.Collections.Immutable.ImmutableArray<TDerived> items) where TDerived : class, T { throw null; }
+        public System.Collections.Immutable.ImmutableArray<TOther> As<TOther>() where TOther : class? { throw null; }
```
Comment (buyaa-n) [inline src/libraries/System.Collections.Immutable/ref/System.Collections.Immutable.cs:125]: NIT: This one also needs to be `?` ?
CC @333fred

**Review by buyaa-n — APPROVED** [review]
Left NIT question, overall LGTM

File: src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs [hunk 2]
```diff
@@ -364,7 +364,7 @@ public static ImmutableArray<T> CastUp<TDerived>(ImmutableArray<TDerived> items)
         /// element types to their derived types. However, downcasting is only successful
         /// when it reverses a prior upcasting operation.
         /// </remarks>
-        public ImmutableArray<TOther> As<TOther>() where TOther : class
+        public ImmutableArray<TOther> As<TOther>() where TOther : class?
         {
             return new ImmutableArray<TOther>((this.array as TOther[])!);
```
Comment (buyaa-n) [inline src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs:369]: NIT: seems we can remove `!`

File: src/libraries/System.Collections.Immutable/ref/System.Collections.Immutable.cs (hunk 1 above)
Comment (333fred) [reply src/libraries/System.Collections.Immutable/ref/System.Collections.Immutable.cs:125]: It seems like it would be perfectly reasonable to pass a nullable type here.

Comment (333fred) [reply src/libraries/System.Collections.Immutable/ref/System.Collections.Immutable.cs:125]: In fact, it seems like this will be a place to use `T?` in the return type when that's available.

Comment (eiriktsarpalis) [reply src/libraries/System.Collections.Immutable/ref/System.Collections.Immutable.cs:125]: I'm not sure I follow, what is the proposed alteration here?

Comment (buyaa-n) [reply src/libraries/System.Collections.Immutable/ref/System.Collections.Immutable.cs:125]: That is related to https://github.com/dotnet/runtime/issues/39877, no action needed for this PR
