### PR TITLE
Fix liveness of FrameListRoot

### LINKED ISSUE #39221: LSRA assert when running PMI on xunit.performance.execution.dll
Repro steps:

1. Build release x64 core_root and set release_core_root to its location.
2. Copy checked clrjit.dll to %release_core_root%.
3. Build pmi.dll in http://github.com/dotnet/jitutils
4. set COMPlus_TieredCompilation=0
4. %release_core_root% pmi.dll PREPALL_QUIET %release_core_root%\xunit.performance.execution.dll

This will fail. The assert won't be printed to the console because this is using a release coreclr.dll. In the debugger the assert can be seen:

```
<GetIterations>d__17:MoveNext():bool:this - Assertion failed (F:\runtime1\src\coreclr\src\jit\lsra.cpp:2262 - !foundDiff) during Linear scan register alloc
```

This failure happens when running our standard jit-diffs --pmi --frameworks with release core_root and a checked clrjit.dll. Note that it's essential that release System.Private.CoreLib.dll is used. The assert doesn't repro with checked System.Private.CoreLib.dll. Because of that, checked coreclr.dll can't be used to repro either.

### PR DESCRIPTION
**Pull request by CarolEidt**
The FrameListRoot variable isn't used if `call->IsSuppressGCTransition()`, but liveness wasn't checking this.

Fix #39221

### CODE REVIEW

**Comment by CarolEidt** [comment]
This issue was introduced with https://github.com/dotnet/coreclr/pull/26458 but apparently went unnoticed for some time.

File: src/coreclr/src/jit/liveness.cpp [hunk 1]
```diff
@@ -1904,8 +1903,9 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
                     // Removing a call does not affect liveness unless it is a tail call in a nethod with P/Invokes or
```
Comment (jkotas) [inline src/coreclr/src/jit/liveness.cpp:1903]:
```suggestion
                    // Removing a call does not affect liveness unless it is a tail call in a method with P/Invokes or
```

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib @AaronRobinsonMSFT PTAL

File: src/coreclr/src/jit/liveness.cpp [hunk 2]
```diff
@@ -349,11 +349,10 @@ void Compiler::fgPerNodeLocalVarLiveness(GenTree* tree)
             // This ensures that the block->bbVarUse will contain
             // the FrameRoot local var if is it a tracked variable.
 
-            if ((tree->AsCall()->IsUnmanaged() || tree->AsCall()->IsTailCallViaJitHelper()) &&
-                compMethodRequiresPInvokeFrame())
+            if ((call->IsUnmanaged() || call->IsTailCallViaJitHelper()) && compMethodRequiresPInvokeFrame())
             {
                 assert((!opts.ShouldUsePInvokeHelpers()) || (info.compLvFrameListRoot == BAD_VAR_NUM));
-                if (!opts.ShouldUsePInvokeHelpers())
+                if (!opts.ShouldUsePInvokeHelpers() && !call->IsSuppressGCTransition())
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/jit/liveness.cpp:355]: Could this predicate be rewritten as:

```c++
if ((info.compLvFrameListRoot != BAD_VAR_NUM) && !call->IsSuppressGCTransition())
```

Since the member `compLvFrameListRoot` is directly used it seems clearer the relationship between the predicate and the branch logic.

Comment (AaronRobinsonMSFT) [reply src/coreclr/src/jit/liveness.cpp:355]: It looks like the assumption here is very much `info.compLvFrameListRoot != BAD_VAR_NUM` - in subsequent areas as well. If `ShouldUsePInvokeHelpers` is false does this mean that we should always have a FrameListRoot?

Comment (CarolEidt) [reply src/coreclr/src/jit/liveness.cpp:355]: > Since the member compLvFrameListRoot is directly used it seems clearer the relationship between the predicate and the branch logic.

Actually, I think the logic is clearer that `compLvFrameListRoot` should be marked as used if the logic indicates it is needed (i.e. that `ShouldUsePInvokeHelpers` is true). In any event, the relationship between the two should be quite clear from the assert above.

> If ShouldUsePInvokeHelpers is false does this mean that we should always have a FrameListRoot?

Only if there are unmanaged calls that require it. (See `compMethodRequiresPInvokeFrame()` which is defined as `return (info.compUnmanagedCallCountWithGCTransition > 0);`

**Comment by CarolEidt** [comment]
ping @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
@dotnet/dnceng - The `Build OSX x64 release Runtime_Debug` leg has not completed, but doesn't allow me to retry. What is the way to deal with this?

**Comment by MattGal** [comment]
> @dotnet/dnceng - The `Build OSX x64 release Runtime_Debug` leg has not completed, but doesn't allow me to retry. What is the way to deal with this?

new to me, checking it out.

**Comment by MattGal** [comment]
@CarolEidt looks like a new failure mode for Github / AzDO integration.  The reason you can't restart it is that it did finish, yesterday evening : https://dev.azure.com/dnceng/public/_build/results?buildId=734471&view=logs&j=9db4066d-6bf0-549a-7716-e181239d2ea7&s=d654deb9-056d-50a2-1717-90c08683d50a on attempt 2.

This is a repo that doesn't block on passing CI, and it did actually pass, so assuming you get signoff you can just merge.  I'll share this incident with the lead for this area to make sure it's on their radar.

**Comment by MattGal** [comment]
Feel free to upvote this issue if you'd like this GitHub / AzDO integration issue to get more priority: https://developercommunity.visualstudio.com/content/problem/1117817/github-reporting-in-progress-azure-devops-build-th.html

**Comment by CarolEidt** [comment]
ping again @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]
