### PR TITLE
Objective-C msgSend* support for pending exceptions in Release

### LINKED ISSUE #52737: Test failure System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendSuper)
Run: [runtime 20210513.81](https://dev.azure.com/dnceng/public/_build/results?buildId=1138119&view=ms.vss-test-web.build-test-results-tab&runId=34528676&resultId=151590&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open

- System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendSuper)
- System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendFpret)
- System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSend)

```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
Actual:   (No exception was thrown)
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 90
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 70

Child process:
  System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.PendingExceptionTests+<>c Void <ValidateSetMessageSendPendingException>b__8_0(System.String)

Child arguments:
  MsgSendSuper
```

### LINKED ISSUE #52962: Test failure on ARM64 macOS: Unable to find an entry point named 'objc_msgSend_fpret' in shared library '/usr/lib/libobjc.dylib'
Example runtime-staging build: https://dev.azure.com/dnceng/public/_build/results?buildId=1137913&view=results

```
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 145
   at Xunit.Assert.Throws[T](Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 41
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 90
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 70
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'objc_msgSend_fpret' in shared library '/usr/lib/libobjc.dylib'.
   at System.Runtime.InteropServices.Tests.LibObjC.objc_msgSend_fpret(IntPtr self, IntPtr selector)
   at System.Runtime.InteropServices.Tests.LibObjC.CallPInvoke(MessageSendFunction msgSend, IntPtr inst, IntPtr sel) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/LibObjC.cs:line 54
   at System.Runtime.InteropServices.Tests.MessageSendTests.SetMessageSendCallbackImpl(MessageSendFunction[] funcsToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/MessageSendTests.cs:line 137
   at System.Runtime.InteropServices.Tests.MessageSendTests.<>c.<SetMessageSendCallback>b__13_0(String funcsToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/MessageSendTests.cs:line 99
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Runtime.InteropServices.Tests.MessageSendTests.SetMessageSendCallback(funcsToOverride: [MsgSend, MsgSendStret]) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          System.EntryPointNotFoundException: Unable to find an entry point named 'objc_msgSend_fpret' in shared library '/usr/lib/libobjc.dylib'.
           at System.Runtime.InteropServices.Tests.LibObjC.objc_msgSend_fpret(IntPtr self, IntPtr selector)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/LibObjC.cs(54,0): at System.Runtime.InteropServices.Tests.LibObjC.CallPInvoke(MessageSendFunction msgSend, IntPtr inst, IntPtr sel)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/MessageSendTests.cs(137,0): at System.Runtime.InteropServices.Tests.MessageSendTests.SetMessageSendCallbackImpl(MessageSendFunction[] funcsToOverride)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/MessageSendTests.cs(99,0): at System.Runtime.InteropServices.Tests.MessageSendTests.<>c.<SetMessageSendCallback>b__13_0(String funcsToOverrideAsStr)
        
        Child process:
          System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.MessageSendTests+<>c Void <SetMessageSendCallback>b__13_0(System.String)
        
        Child arguments:
          MsgSend;MsgSendStret
        
    System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSend) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
        Actual:   (No exception was thrown)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(90,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(70,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr)
        
        Child process:
          System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.PendingExceptionTests+<>c Void <ValidateSetMessageSendPendingException>b__8_0(System.String)
        
        Child arguments:
          MsgSend
        
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 145
   at Xunit.Assert.Throws[T](Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 41
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 90
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 70
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendFpret) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
        Actual:   (No exception was thrown)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(90,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(70,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr)
        
        Child process:
          System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.PendingExceptionTests+<>c Void <ValidateSetMessageSendPendingException>b__8_0(System.String)
        
        Child arguments:
          MsgSendFpret
        
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 145
   at Xunit.Assert.Throws[T](Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 41
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 90
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 70
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendSuper) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
        Actual:   (No exception was thrown)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(90,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(70,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr)
        
        Child process:
          System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.PendingExceptionTests+<>c Void <ValidateSetMessageSendPendingException>b__8_0(System.String)
        
        Child arguments:
          MsgSendSuper
        
  Finished:    System.Runtime.InteropServices.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.InteropServices.Tests  Total: 928, Errors: 0, Failed: 4, Skipped: 4, Time: 26.320s
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #52737 
Fixes https://github.com/dotnet/runtime/issues/52962

The current logic was assuming the `NDirectMethodDesc` was always fully populated when the call to `MarshalingRequired` was performed &ndash; This is not the case, comment was added. The fix here is to attempt to populate the `NDirectMethodDesc` when we get to a point where it is needed.

It was also determined that a fundamental bug existed in the experience since the JIT does call `MarshalingRequired` prior to the method being run which means detecting if a method is overloaded could be detected in the scenario below. This means we are changing the logic so that no calls to overridable functions (i.e., `msgSend*`) in `/usr/lib/libobjc.dylib` will be inlinable and will always check for a pending exception.

```csharp
unsafe class Program
{
    private const string LibName = "/usr/lib/libobjc.dylib";
    [DllImport(LibName)]
    public static extern IntPtr objc_msgSend(IntPtr self, IntPtr selector);
    private sealed class PendingException : Exception
    {
        public PendingException(string message) : base(message) { }
    }
    [UnmanagedCallersOnly]
    private static IntPtr MsgSend(IntPtr inst, IntPtr sel) => SetPendingException();
    private static IntPtr SetPendingException([CallerMemberName] string callerName = "")
    {
        ObjectiveCMarshal.SetMessageSendPendingException(new PendingException(callerName));
        return IntPtr.Zero;
    }
    static void Main(string[] doNotUse)
    {
        var func = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&MsgSend;
        ObjectiveCMarshal.SetMessageSendCallback(MessageSendFunction.MsgSend, func);
        IntPtr inst = IntPtr.Zero;
        IntPtr sel = IntPtr.Zero;
        objc_msgSend(inst, sel); // Should throw PendingException but doesn’t.
    }
}
```

/cc @jkotas @jkoritzinsky @elinor-fung

### CODE REVIEW

File: src/coreclr/vm/dllimport.h [hunk 1]
```diff
@@ -404,7 +406,9 @@ struct PInvokeStaticSigInfo
 private:
     Module* m_pModule;
     Signature m_sig;
+    LPCUTF8 m_entryPointName;
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.h:409]: It does not feel right to add the unmanaged entrypoint name to `PInvokeStaticSigInfo`.

File: src/coreclr/vm/interoplibinterface_shared.cpp [hunk 2]
```diff
@@ -22,9 +25,32 @@ bool Interop::ShouldCheckForPendingException(_In_ NDirectMethodDesc* md)
...
-        return false;
+    {
+        // If no sig info was supplied we have no recourse.
+        if (sigInfo == NULL)
+            return false;
+
+        if (libraryName == NULL)
+        {
+            // If the library name is unknown, see if we can get the token
+            // from the sig info.
```
Comment (jkotas) [inline src/coreclr/vm/interoplibinterface_shared.cpp:36]: I think it would be better to require `NDirectMethodDesc` to be populated when this is called instead of trying to patch it up here.

When this gets called from the exception handler, I think it should be safe to assume that `NDirectMethodDesc` has been populated (in all cases that matter).

File: src/coreclr/vm/dllimport.h (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.h:409]: I agree that it does seem odd, but the spirit of this class is far more similar to the CrossGen2 data type - `PInvokeMetadata`. Let me see how I can refactor this PR though.

File: src/coreclr/vm/interoplibinterface_shared.cpp (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interoplibinterface_shared.cpp:36]: >When this gets called from the exception handler

This isn't the issue actually. The issue is during jit compilation when we are trying to determine if the P/Invoke call can be inlined. When the P/Invoke is eventually invoked, the PreStub path fills in the `NDirectMethodDesc` and since that has a conceptual lock around it the update is safe there but not at this point. I can try to audit the path but I do fear the potential for bug tail.

Comment (jkotas) [reply src/coreclr/vm/interoplibinterface_shared.cpp:36]: `PopulateNDirectMethodDesc` seems to be thread-safe already, it is just not very efficient when called multiple times.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/interoplibinterface_shared.cpp:36]: My concern is the following comment:

https://github.com/dotnet/runtime/blob/64f5f0b31d9af2df199229e6e4ef3f4a876a05a5/src/coreclr/vm/dllimport.cpp#L4266-L4268

Comment (jkotas) [reply src/coreclr/vm/interoplibinterface_shared.cpp:36]: I think that this comment was meant to say that the flags have to be set atomically.

It is pretty easy to see that `PopulateNDirectMethodDesc` can be called multiple threads at the same time today.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs [hunk 3]
```diff
@@ -797,5 +797,23 @@ public static partial class MarshalHelpers
                 return MarshallerKind.Invalid;
             }
         }
+
+        internal static bool ShouldCheckForPendingException(TargetDetails target, PInvokeMetadata metadata)
+        {
+            if (!target.IsOSX)
+                return false;
+
+            const string ObjectiveCLibrary = "/usr/lib/libobjc.dylib";
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:806]: I see number of examples using just `libobjc.dylib` without the full path, e.g. https://docs.microsoft.com/en-us/xamarin/ios/platform/exception-marshaling . Should this check be more relaxed?

Comment (AaronRobinsonMSFT) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:806]: We were following the documentation for selectors - https://docs.microsoft.com/xamarin/ios/internals/objective-c-selectors. This specifically uses a Xamarin constant in all examples - [`ObjectiveCLibrary`](https://github.com/xamarin/xamarin-macios/blob/63ad08ed4443b659d2c58cc49dec4c4dbe478bf7/src/ObjCRuntime/Constants.cs#L9).

Comment (AaronRobinsonMSFT) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:806]: Since Xamarin has a usable constant I am inclined to defer to that. Do you have a different opinion?

Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:806]: I do not have an opionion. I just see it all over the place in the real world code out there: https://github.com/search?l=&p=4&q=objc_msgSend+language%3AC%23&ref=advsearch&type=Code

What is the exact condition used in existing Xamarin for the `objc_msgSend` redirection?

Comment (filipnavara) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:806]: The original Xamarin code used this:
```
	mono_dllmap_insert (NULL, "/usr/lib/libobjc.dylib", "objc_msgSend",            lib, "xamarin_dyn_objc_msgSend");
	mono_dllmap_insert (NULL, "/usr/lib/libobjc.dylib", "objc_msgSendSuper",       lib, "xamarin_dyn_objc_msgSendSuper");
```
so it's more of a question whether Mono's dllmap first does resolution and then matching or just matching. @CoffeeFlux?

Comment (AaronRobinsonMSFT) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:806]: @jkotas I do see a few places where `objc` is just specified but the majority seem to be `LIBOBJC_DYLIB` which appears to be provided by the Xamarin code gen and points to the absolute path. I think what we have is the correct approach.

Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:806]: Sounds good.

Comment (AaronRobinsonMSFT) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:806]: Update documentation - https://github.com/MicrosoftDocs/xamarin-docs/pull/3305

File: src/coreclr/vm/dllimport.cpp [hunk 4]
```diff
@@ -662,6 +662,12 @@ class ILStubState : public StubState
         }
 #endif // PROFILING_SUPPORTED
 
+        if (SF_IsCheckPendingException(m_dwStubFlags)
+            && SF_IsForwardStub(m_dwStubFlags))
+        {
+            pcsDispatch->EmitCALL(METHOD__STUBHELPERS__CLEAR_PENDING_EXCEPTION_OBJECT, 0, 0);
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp:668]: Do we really need this? I am not sure how important it is to try to be robust against somebody setting the pending by accident without a matching for pending exception.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp:668]: I feel better with it because it provides us with a guarantee that nothing was missed. I assume your concern is the unnecessary performance impact?

Comment (jkotas) [reply src/coreclr/vm/dllimport.cpp:668]: I agree that it can cover up some a problem in simple cases. It does not provide the guarantee when the calls are nested. If there is a real problem that this is covering up, it will be hard to repro and debug.

I am not that concerned about performance. I have been more wondering about what made you to add this.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp:668]: > I have been more wondering about what made you to add this.

It was the potential stale thread state that bothered me. We have a clear/get/set for the last error so figured I would mimic the behavior. It was also when it was possible to get into a state where we didn't check, but that should be handled now. If you don't see value I am fine removing it.

Comment (jkotas) [reply src/coreclr/vm/dllimport.cpp:668]: I would remove it until we have a proof that it is really needed.

**Review by jkotas — APPROVED** [review]
LGTM. Thanks!

**Review by elinor-fung — COMMENTED** [review]
> This means we are changing the logic so that no calls to overridable functions (i.e., msgSend*) in /usr/lib/libobjc.dylib will be inlinable.

This is not just disabling inlining for `objc_msgSend*`, but also changing the emitted IL to always check for a pending exception object. Is that intentional? I'm not seeing why that would be necessary for this.

File: src/coreclr/vm/dllimport.cpp [hunk 5]
```diff
@@ -3098,6 +3102,11 @@ HRESULT NDirect::HasNAT_LAttribute(IMDInternalImport *pInternalImport, mdToken t
 
 
 // Either MD or signature & module must be given.
+//
+// N.B. This method can be called at a time when the associated NDirectMethodDesc
+// has not been fully populated. This means the optimized path for this call is to rely
+// on the most basic P/Invoke metadata. An example when this can happen is when the JIT
+// is compiling a method containing a P/Invoke that is being considered for inlining.
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp:3109]: Moved.

File: src/coreclr/vm/dllimport.cpp [hunk 6]
```diff
@@ -3098,6 +3102,11 @@ HRESULT NDirect::HasNAT_LAttribute(IMDInternalImport *pInternalImport, mdToken t
 
 
 // Either MD or signature & module must be given.
+//
+// N.B. This method can be called at a time when the associated NDirectMethodDesc
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp:3106]: Done.

**Comment by AaronRobinsonMSFT** [comment]
> This is not just disabling inlining for objc_msgSend*, but also changing the emitted IL to always check for a pending exception object. Is that intentional?

Yes. This aligns with the current Mono contract.

> I'm not seeing why that would be necessary for this.

Is your interpretation that only overriding a `msgSend*` function should require a check?

**Comment by elinor-fung** [comment]
Chatted offline.

If the intention is that all msgSend invokes (not just overridden ones) will actually check for a pending exceptions, we should update the API docs. Could we also add a test for this behaviour?

File: src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs [hunk 7]
```diff
@@ -71,27 +62,32 @@ public void ValidateSetMessageSendPendingException(MessageSendFunction func)
...
+                MessageSendFunction.MsgSendFpret => (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&MsgSendFpret,
+                MessageSendFunction.MsgSendStret => (IntPtr)(delegate* unmanaged<IntPtr*, IntPtr, IntPtr, void>)&MsgSendStret,
+                MessageSendFunction.MsgSendSuper => (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&MsgSendSuper,
+                MessageSendFunction.MsgSendSuperStret => (IntPtr)(delegate* unmanaged<IntPtr*, IntPtr, IntPtr, void>)&MsgSendSuperStret,
+                _ => throw new Exception($"Unknown {nameof(MessageSendFunction)}"),
+            };
+
+            // Override message send function
+            //
+            // We are using the overriding mechanism to enabling validating in the Libraries test suite.
```
Comment (elinor-fung) [inline src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:79]: to enabling!

File: src/coreclr/System.Private.CoreLib/src/System/Runtime/InteropServices/ObjectiveCMarshal.CoreCLR.cs [hunk 8]
```diff
@@ -10,7 +10,7 @@ namespace System.Runtime.InteropServices.ObjectiveC
     public static partial class ObjectiveCMarshal
     {
         /// <summary>
-        /// Sets a pending exception to be thrown the next time the runtime is entered from an overridden msgSend P/Invoke.
+        /// Sets a pending exception to be thrown the next time the runtime is entered from an Objective-C msgSend P/Invoke.
```
Comment (elinor-fung) [inline src/coreclr/System.Private.CoreLib/src/System/Runtime/InteropServices/ObjectiveCMarshal.CoreCLR.cs:13]: Doc is also in ObjectiveCMarshal.Mono.cs

**Review by elinor-fung — APPROVED** [review]
Thanks for the clarifications.

**Comment by AaronRobinsonMSFT** [comment]
I've one more commit to add but will wait to see if the current CI is green. This final commit only contains comment code so if the CI is green, I will push the commits and then merge.

**Comment by AaronRobinsonMSFT** [comment]
Issue is https://github.com/dotnet/runtime/pull/52799.

**Comment by AaronRobinsonMSFT** [comment]
The failure in crossgen2 is https://github.com/dotnet/runtime/issues/49365.

**Comment by AaronRobinsonMSFT** [comment]
Failures in x64 Debug are infrastructure failures.

**Comment by filipnavara** [comment]
Any plans to backport this to preview5?

**Comment by AaronRobinsonMSFT** [comment]
@filipnavara No. You can workaround this issue easily by making the P/Invoke signature non-blittable. An easy way to do this would be to set [`DllImportAttribute.SetLastError`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.dllimportattribute.setlasterror) to `true`. This would skip the inlining and be minimal overhead that could be removed once Preview 6 is released.

**Comment by filipnavara** [comment]
I was actually more concerned about consuming the API on the Xamarin side but I supposed it can wait one more preview or I can use custom builds.

File: src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs (hunk 3 above)
Comment (rolfbjarne) [reply src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs:806]: Just for the record: at one point we ran into problems when using just the filename. IIRC it was during a beta version of iOS, and Apple fixed their code so that using just the filename continued to work in the end, but since then we've always used the full path ourselves, and recommended it for everybody else. This is another result of this: https://github.com/xamarin/xamarin-macios/blob/e8fa7676b82ff3cd26535ec988a27cde1dc1a5d8/src/ObjCRuntime/Dlfcn.cs#L111-L118 (we expose `dlopen`, and if you don't pass a full path, we warn).
