### PR TITLE
JIT: simple forward substitution pass

### LINKED ISSUE #33002: JIT: Some SIMD intrinsics operations don't reliably fold memory addressing logic
Found while looking at codegen for https://github.com/dotnet/runtime/pull/32994. From SharpLab:

```cs
public unsafe static void WidenAndWrite_Foo(byte* pInput, char* pOutput, ulong offset)
{
    Vector128<byte> zero = Vector128<byte>.Zero;
    Vector128<byte> narrow = Sse2.LoadVector128(pInput + offset);

    Vector128<byte> wideLow = Sse2.UnpackLow(narrow, zero);
    Vector128<byte> wideHigh = Sse2.UnpackHigh(narrow, zero);

    Sse2.Store((byte*)(pOutput + offset), wideLow);
    Sse2.Store((byte*)(pOutput + offset + 0x08), wideHigh);
}

public unsafe static void WidenAndWrite_Bar(byte* pInput, char* pOutput, ulong offset)
{
    Vector128<byte> zero = Vector128<byte>.Zero;
    Vector128<byte> narrow = Sse2.LoadVector128(pInput + offset);

    Vector128<byte> wideLow = Sse2.UnpackLow(narrow, zero);
    Vector128<byte> wideHigh = Sse2.UnpackHigh(narrow, zero);

    Sse2.Store((byte*)(pOutput + offset), wideLow);
    Sse2.Store((byte*)pOutput + (offset << 1) + 0x10, wideHigh);
}
```

```asm
WidenAndWrite_Foo(Byte*, Char*, UInt64)
    L0000: vzeroupper
    L0003: vxorps xmm0, xmm0, xmm0
    L0007: vmovdqu xmm1, [rcx+r8]
    L000d: vpunpcklbw xmm2, xmm1, xmm0
    L0011: vpunpckhbw xmm0, xmm1, xmm0
    L0015: lea rax, [rdx+r8*2]
    L0019: vmovdqu [rax], xmm2
    L001d: vmovdqu [rax+0x10], xmm0
    L0022: ret

WidenAndWrite_Bar(Byte*, Char*, UInt64)
    L0000: vzeroupper
    L0003: vxorps xmm0, xmm0, xmm0
    L0007: vmovdqu xmm1, [rcx+r8]
    L000d: vpunpcklbw xmm2, xmm1, xmm0
    L0011: vpunpckhbw xmm0, xmm1, xmm0
    L0015: vmovdqu [rdx+r8*2], xmm2
    L001b: vmovdqu [rdx+r8*2+0x10], xmm0
    L0022: ret
```

Is there any reason why the first sample uses a `lea` to help with calculating the destination memory address, while the second sample foregoes `lea` and folds the memory addressing logic directly into the `vmovdqu` instruction? As far as I can tell they take around the same amount of time to execute, but the first sample burns a register unnecessarily.

Related: https://github.com/dotnet/runtime/issues/10923

category:cq
theme:addressing-modes
skill-level:expert
cost:medium

### LINKED ISSUE #48605: typeof(T).IsValueType not completely unimpactful in some cases
The JIT has an optimization to treat `typeof(T).IsValueType` as a const based on the T being specified, but in some cases the presence of the check is still having an impact on the generated asm.

Non-sensical repro (derived from much more complicated real-world scenario in dotnet/roslyn#51383):
```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[DisassemblyDiagnoser]
public class Program
{
    static void Main(string[] args) => BenchmarkSwitcher.FromAssemblies(new[] { typeof(Program).Assembly }).Run(args);
}

[DisassemblyDiagnoser]
public class Benchmarks
{
    private Wrapper<int> _array = new Wrapper<int>(new int[1]);
    private int _offset = 0;

    [Benchmark]
    public void Test1() => _array.Get1(_offset) = default;

    [Benchmark]
    public void Test2() => _array.Get2(_offset) = default;
}

public struct Wrapper<T>
{
    private T[] _items;

    public Wrapper(T[] item) => _items = item;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public ref T Get1(int index)
    {
        return ref _items[index];
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public ref T Get2(int index)
    {
        if (typeof(T).IsValueType)
        {
            return ref _items[index];
        }

        return ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(_items), index);
    }
}
```

The non-value type branch in Get2 should in theory be removed completely, but using a recent .NET 6 nightly, this results in:

## .NET 6.0.0 (6.0.21.11705), X64 RyuJIT
```assembly
; Benchmarks.Test1()
       sub       rsp,28
       lea       rax,[rcx+10]
       mov       edx,[rcx+8]
       mov       rax,[rax]
       cmp       edx,[rax+8]
       jae       short M00_L00
       movsxd    rdx,edx
       xor       ecx,ecx
       mov       [rax+rdx*4+10],ecx
       add       rsp,28
       ret
M00_L00:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 39
```

## .NET 6.0.0 (6.0.21.11705), X64 RyuJIT
```assembly
; Benchmarks.Test2()
       sub       rsp,28
       lea       rax,[rcx+10]
       mov       edx,[rcx+8]
       mov       rax,[rax]
       cmp       edx,[rax+8]
       jae       short M00_L00
       movsxd    rdx,edx
       lea       rax,[rax+rdx*4+10]
       xor       edx,edx
       mov       [rax],edx
       add       rsp,28
       ret
M00_L00:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 42
```

Note the difference between:
```
       xor       ecx,ecx
       mov       [rax+rdx*4+10],ecx
```
and
```
       lea       rax,[rax+rdx*4+10]
       xor       edx,edx
       mov       [rax],edx
```

category:cq
theme:optimization
skill-level:expert
cost:large
impact:medium

### LINKED ISSUE #51599: JIT doesn't always fold 'add' instructions into 'lea' which immediately follows it
__Repro code:__

```cs
{
class Program
{
    static int ReadInt32Field(object @this, nuint offset)
    {
        ref byte b = ref Unsafe.As<RawObjData>(@this).Data;
        b = ref Unsafe.Subtract(ref b, IntPtr.Size);
        b = ref Unsafe.AddByteOffset(ref b, (nint)offset);
        return Unsafe.ReadUnaligned<int>(ref b);
    }
}

sealed class RawObjData
{
    public byte Data;
}
```

```asm
; Method ConsoleApp62.Program:ReadInt32Field(System.Object,long):int
G_M62650_IG01:
						;; bbWeight=1    PerfScore 0.00

G_M62650_IG02:
       cmp      dword ptr [rcx], ecx
       add      rcx, 8
       mov      eax, dword ptr [rcx+rdx-8]
						;; bbWeight=1    PerfScore 4.25

G_M62650_IG03:
       ret      
						;; bbWeight=1    PerfScore 1.00
; Total bytes of code: 11
```

In this codegen, both the _add_ and the _mov_ instruction can be collapsed into a single `mov eax, dword ptr [rcx + rdx]` instruction, where the +8 and the -8 cancel each other out.

We see this sometimes with very low-level object manipulation in corelib. For example, the codegen listed at the top of https://github.com/dotnet/runtime/pull/51548 (working on an `Array.Clear` optimization) has this pattern. We even have [a specialized intrinsic](https://github.com/dotnet/runtime/blob/24966ab54e8ca795dac8e066e17fb4d8d04b9345/src/coreclr/vm/jitinterface.cpp#L7420) as a temporary workaround in _extremely_ hot code paths. (This intrinsic is used in `Memory<T>.get_Span`, for instance.)

It'd be great if JIT could somehow collapse these sequences where they occur. That would ideally result in better codegen and would allow us to remove this intrinsic from the code base.

### LINKED ISSUE #55472: Unsafe.SizeOf<T>() causes an additional mov over sizeof(T)
### Description

In some cases, `Unsafe.SizeOf<T>` produces an additional `mov` over `sizeof(T)` (both over not compile time known types). 

### Configuration

Sharplab Core CLR v5.0.721.25508

### Regression?

No idea.

### Data

[Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgy5UQAtsUPgBlsweszYdFS5cQDMlKknLNc2AGYxKAJnIAVWRmUBvZeSB5ADaAFKsGADiMEwi0gAUGACefDAQjvGsLACU2QC6AUGW1rbAEBCC5ACCADweAHzxwEkYMMF55M2tuNnkAO7qIi4e5CB2TPjYTNgA5jAAJoWB/kpBa5QA7J0tsjQ6MTMY6uQ15LisAF5pGR7ZpmsAvkvkz2ER0bFQCcmp6Zk5+WexWopXKlQAQnVGl02h0YT1+oNYJ5RuNJtM5otVkEVusilt4XsDkcTuQAKpMBzOGiiS4wADyjih8TuzyeSgeQA===)

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Extend ref counting done by local morph so that we can determine
single-def single-use locals.

Add a phase that runs just after local morph that will attempt to
forward single-def single-use local defs to uses when they are in
adjacent statements.

Fix or work around issues uncovered elsewhere:
* `gtFoldExprCompare` might fold "identical" volatile subtrees
* `fgGetStubAddrArg` cannot handle complex trees
* some simd/hw operations can lose struct handles
* some calls cannot handle struct local args

Addresses #6973 and related issues. Still sorting through exactly
which ones are fixed, so list below may need revising.

Fixes #48605.
Fixes #51599.
Fixes #55472.

Improves some but not all cases in #12880 and #62604.

Does not address #33002, #47082, or #63116; these require handling multiple
uses or bypassing statements.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Looks like various issues cropping up during crossgen for non-windows non-x64 builds. Hopefully minor.

**Comment by ShreyasJejurkar** [comment]
Just a note merging this PR will close these issues as well! Maybe put some dash or whitespace to avoid I guess! 
image

File: src/coreclr/jit/forwardsub.cpp [hunk 1]
```diff
@@ -0,0 +1,392 @@
...
+    // We can forward sub if
+    //
+    // the value of the fwdSubNode can't change and its evaluation won't cause side effects,
+    //
+    // or,
+    //
+    // if the next tree can't change the value of fwdSubNode or be adversly impacted by fwdSubNode effects
+    //
+    const bool fwdSubNodeInvariant   = ((fwdSubNode->gtFlags & GTF_ALL_EFFECT) == 0);
+    const bool nextTreeIsPureUpToUse = ((fsv.GetFlags() & (GTF_EXCEPT | GTF_GLOB_REF | GTF_CALL)) == 0);
```
Comment (SingleAccretion) [inline src/coreclr/jit/forwardsub.cpp:318]: It feels very risky to rely on `GTF_GLOB_REF` before (or, really, after, since we don't have the checker enabled for it) morph. For example:

```cs
static int* _lclAddr;

[MethodImpl(MethodImplOptions.NoInlining)]
static int Problem(int a, int b)
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static void CaptureLcl(int* lclAddr)
    {
        _lclAddr = lclAddr;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static int MutateLcl()
    {
        (*_lclAddr)++;
        return 0;
    }

    CaptureLcl(&a);

    b = a + a;

    return MutateLcl() + b; // We will forward-substitute 'a' because "a + a" won't have GTF_GLOB_REF on it.
}
```

Comment (AndyAyersMS) [reply src/coreclr/jit/forwardsub.cpp:324]: Thanks for the example. Seems like we'll need to walk over the tree to substitute and compute the actual set of effects flags.

**Comment by AndyAyersMS** [comment]
Going to set this aside for a while to focus on OSR. Looks like:
* there are possibly restrictions with forwarding unmanaged calls (messed up pinvoke transitions)
* something perhaps wrong with native AOT. Tried reproing this but was unable to build the tests properly.
* SPMI diffs may be too large to download? I can run them locally, but they take a long time...

@EgorBo feel free to look into any of the above.

**Comment by AndyAyersMS** [comment]
JIT/Directed/debugging/debuginfo/tester is failing everywhere as we're evidently removing statements with debug info. Wonder if we should be merging debug info somehow.

**Comment by AndyAyersMS** [comment]
Latest diff summary for windows x64 (since CI runs are still unable to provide data, likely because of the huge number of impacted methods):

## aspnet.run.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 20437148 (overridden on cmd)
Total bytes of diff: 20404319 (overridden on cmd)
Total bytes of delta: -32829 (-0.16 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         359 : 31193.dasm (67.99% of base)
         195 : 64130.dasm (1.13% of base)
          65 : 52047.dasm (7.78% of base)
          60 : 50166.dasm (7.21% of base)
          47 : 51516.dasm (5.08% of base)
          46 : 65775.dasm (0.44% of base)
          35 : 18861.dasm (5.20% of base)
          32 : 34557.dasm (1.30% of base)
          32 : 62779.dasm (0.63% of base)
          32 : 66812.dasm (1.30% of base)
          31 : 60170.dasm (1.22% of base)
          29 : 50431.dasm (3.08% of base)
          26 : 44637.dasm (1.50% of base)
          26 : 62781.dasm (0.26% of base)
          25 : 35794.dasm (1.03% of base)
          25 : 27528.dasm (1.28% of base)
          24 : 65641.dasm (0.45% of base)
          24 : 15218.dasm (2.63% of base)
          23 : 47807.dasm (3.43% of base)
          20 : 25977.dasm (1.56% of base)

Top file improvements (bytes):
        -159 : 29878.dasm (-4.16% of base)
        -156 : 66000.dasm (-2.75% of base)
        -155 : 60074.dasm (-2.73% of base)
        -126 : 45282.dasm (-1.79% of base)
        -119 : 11935.dasm (-4.35% of base)
        -119 : 21417.dasm (-3.42% of base)
        -111 : 49734.dasm (-1.57% of base)
        -110 : 13529.dasm (-1.57% of base)
        -110 : 19013.dasm (-1.57% of base)
        -106 : 62732.dasm (-1.61% of base)
        -102 : 27959.dasm (-3.88% of base)
        -100 : 29887.dasm (-4.56% of base)
        -100 : 59804.dasm (-3.23% of base)
         -95 : 14570.dasm (-3.87% of base)
         -94 : 62240.dasm (-2.86% of base)
         -91 : 67942.dasm (-2.99% of base)
         -90 : 28632.dasm (-3.55% of base)
         -90 : 29610.dasm (-4.65% of base)
         -88 : 25713.dasm (-4.42% of base)
         -88 : 25742.dasm (-1.48% of base)

5478 total files with Code Size differences (4779 improved, 699 regressed), 2627 unchanged.

Top method regressions (bytes):
         359 (67.99% of base) : 31193.dasm - MethodBase:CheckArguments(byref,ReadOnlySpan`1,Binder,int,CultureInfo,ref):Span`1:this
         195 ( 1.13% of base) : 64130.dasm - NpgsqlTypeMappingSource:.ctor(TypeMappingSourceDependencies,RelationalTypeMappingSourceDependencies,ISqlGenerationHelper,INpgsqlOptions):this
          65 ( 7.78% of base) : 52047.dasm - TextEncoder:EncodeToNewString(ReadOnlySpan`1,int):String:this
          60 ( 7.21% of base) : 50166.dasm - TextEncoder:EncodeToNewString(ReadOnlySpan`1,int):String:this
          47 ( 5.08% of base) : 51516.dasm - CancellationTokenSource:Register(Delegate,Object,SynchronizationContext,ExecutionContext):CancellationTokenRegistration:this
          46 ( 0.44% of base) : 65775.dasm - SelectExpression:ApplyProjection(Expression,int,int):Expression:this
          35 ( 5.20% of base) : 18861.dasm - ResourceManager:GetFirstResourceSet(CultureInfo):ResourceSet:this
          32 ( 1.30% of base) : 34557.dasm - HttpParser`1:ParseHeaders(Http1ParsingHandler,byref):bool:this
          32 ( 1.30% of base) : 66812.dasm - HttpParser`1:ParseHeaders(Http1ParsingHandler,byref):bool:this
          32 ( 0.63% of base) : 62779.dasm - NpgsqlMemberTranslatorProvider:.ctor(RelationalMemberTranslatorProviderDependencies,IModel,IRelationalTypeMappingSource,INpgsqlOptions):this
          31 ( 1.22% of base) : 60170.dasm - <OpenInternalAsync>d__70:MoveNext():this
          29 ( 3.08% of base) : 50431.dasm - ViewLocationCacheKey:GetHashCode():int:this
          26 ( 1.50% of base) : 44637.dasm - DbContextOptions:GetHashCode():int:this
          26 ( 0.26% of base) : 62781.dasm - NpgsqlMethodCallTranslatorProvider:.ctor(RelationalMethodCallTranslatorProviderDependencies,IModel,INpgsqlOptions):this
          25 ( 1.28% of base) : 27528.dasm - DfaMatcherBuilder:CreateCandidate(Endpoint,int):Candidate:this
          25 ( 1.03% of base) : 35794.dasm - JsonMiddleware:Invoke(HttpContext):Task:this
          24 ( 2.63% of base) : 15218.dasm - HttpProtocol:CreateResponseHeaders(bool):HttpResponseHeaders:this
          24 ( 0.45% of base) : 65641.dasm - IncludeExpandingExpressionVisitor:ExpandIncludesHelper(Expression,EntityReference,INavigationBase):Expression:this
          23 ( 3.43% of base) : 47807.dasm - ConnectorTypeMapper:Reset():this
          20 ( 5.12% of base) : 58929.dasm - DefaultViewCompiler:EnsureCompiledViews(ILogger):this

Top method improvements (bytes):
        -159 (-4.16% of base) : 29878.dasm - <ConnectAsync>d__96:MoveNext():this
        -156 (-2.75% of base) : 66000.dasm - <ExecuteReaderAsync>d__19:MoveNext():this
        -155 (-2.73% of base) : 60074.dasm - <ExecuteReaderAsync>d__19:MoveNext():this
        -126 (-1.79% of base) : 45282.dasm - <ExecuteReaderAsync>d__19:MoveNext():this
        -119 (-3.42% of base) : 21417.dasm - <ConnectAsync>d__96:MoveNext():this
        -119 (-4.35% of base) : 11935.dasm - ThreadPoolWorkQueue:Dispatch():bool
        -111 (-1.57% of base) : 49734.dasm - <ExecuteReaderAsync>d__19:MoveNext():this
        -110 (-1.57% of base) : 13529.dasm - HttpRequestHeaders:Append(ReadOnlySpan`1,ReadOnlySpan`1,bool):this
        -110 (-1.57% of base) : 19013.dasm - HttpRequestHeaders:Append(ReadOnlySpan`1,ReadOnlySpan`1,bool):this
        -106 (-1.61% of base) : 62732.dasm - <ExecuteReaderAsync>d__19:MoveNext():this
        -102 (-3.88% of base) : 27959.dasm - <GetHttp11ConnectionAsync>d__75:MoveNext():this
        -100 (-4.56% of base) : 29887.dasm - <CreateHttp11ConnectionAsync>d__98:MoveNext():this
        -100 (-3.23% of base) : 59804.dasm - <ReceiveBlobAsync>d__174`1:MoveNext():this
         -95 (-3.87% of base) : 14570.dasm - ThreadPoolWorkQueue:Dispatch():bool
         -94 (-2.86% of base) : 62240.dasm - <ReceiveBlobAsync>d__174`1:MoveNext():this
         -91 (-2.99% of base) : 67942.dasm - <QueryAsync>d__33`1:MoveNext():this
         -90 (-3.55% of base) : 28632.dasm - <GetHttp11ConnectionAsync>d__75:MoveNext():this
         -90 (-4.65% of base) : 29610.dasm - <GetHttp11ConnectionAsync>d__75:MoveNext():this
         -88 (-4.42% of base) : 25713.dasm - <GetHttp11ConnectionAsync>d__75:MoveNext():this
         -88 (-1.48% of base) : 25742.dasm - <WriteHeadersAsync>d__56:MoveNext():this

Top method regressions (percentages):
         359 (67.99% of base) : 31193.dasm - MethodBase:CheckArguments(byref,ReadOnlySpan`1,Binder,int,CultureInfo,ref):Span`1:this
           7 (24.14% of base) : 64420.dasm - OnEntityTypeAddedNode:Run(ConventionDispatcher):this
           7 (24.14% of base) : 64763.dasm - OnKeyAddedNode:Run(ConventionDispatcher):this
           7 (24.14% of base) : 64692.dasm - OnPropertyAddedNode:Run(ConventionDispatcher):this
           7 (24.14% of base) : 64831.dasm - OnPropertyNullableChangedNode:Run(ConventionDispatcher):this
           7 (24.14% of base) : 20658.dasm - String:GetHashCode():int:this
          11 (23.40% of base) : 34174.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 51784.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 43070.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 31283.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 48194.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 48486.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 61243.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
           7 (18.92% of base) : 62267.dasm - IdnMapping:get_NlsFlags():int:this
           7 (18.92% of base) : 49152.dasm - IdnMapping:get_NlsFlags():int:this
           7 (18.92% of base) : 44254.dasm - IdnMapping:get_NlsFlags():int:this
          10 (17.54% of base) : 14792.dasm - ILStubClass:IL_STUB_PInvoke(int,long):int
          14 (13.46% of base) : 15795.dasm - AwaitableSocketAsyncEventArgs:Release():this
          14 (13.46% of base) : 6199.dasm - AwaitableSocketAsyncEventArgs:Release():this
          15 (12.71% of base) : 54664.dasm - ControllerFactoryProvider:GetPropertiesToActivate(ControllerActionDescriptor):ref:this

Top method improvements (percentages):
          -3 (-37.50% of base) : 15829.dasm - HeartbeatManager:get_UtcNowTicks():long:this
         -32 (-31.37% of base) : 48870.dasm - IEnumerableCallSite:.ctor(ResultCache,Type,ref):this
         -51 (-31.10% of base) : 44776.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
         -51 (-31.10% of base) : 62677.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
         -51 (-31.10% of base) : 49523.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
          -3 (-30.00% of base) : 1028.dasm - Socket:get_SafeHandle():SafeSocketHandle:this
         -47 (-29.38% of base) : 60036.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
          -8 (-27.59% of base) : 48895.dasm - ResultCache:.ctor(int,ServiceCacheKey):this
          -3 (-27.27% of base) : 22339.dasm - ProxyConfigManager:GetChangeToken():IChangeToken:this
          -8 (-21.62% of base) : 6285.dasm - Complex:Abs():double:this
         -28 (-20.59% of base) : 29690.dasm - CancellationTokenSource:TryReset():bool:this
         -28 (-20.59% of base) : 25168.dasm - CancellationTokenSource:TryReset():bool:this
         -25 (-18.80% of base) : 18727.dasm - CancellationTokenSource:TryReset():bool:this
         -25 (-18.80% of base) : 16354.dasm - CancellationTokenSource:TryReset():bool:this
         -84 (-18.58% of base) : 16480.dasm - AdjustmentRule:get_HasDaylightSaving():bool:this
         -31 (-17.32% of base) : 65406.dasm - NpgsqlDecimalTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-17.32% of base) : 65358.dasm - NpgsqlDoubleTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-17.32% of base) : 65413.dasm - NpgsqlFloatTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40% of base) : 65409.dasm - NpgsqlCidrTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40% of base) : 65408.dasm - NpgsqlInetTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this

5478 total methods with Code Size differences (4779 improved, 699 regressed), 2627 unchanged.

```

</details>

--------------------------------------------------------------------------------

## benchmarks.run.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 12150977 (overridden on cmd)
Total bytes of diff: 12143455 (overridden on cmd)
Total bytes of delta: -7522 (-0.06 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         356 : 324.dasm (54.19% of base)
         116 : 22084.dasm (7.94% of base)
          81 : 7226.dasm (2.07% of base)
          70 : 12172.dasm (1.56% of base)
          51 : 1459.dasm (0.72% of base)
          39 : 6819.dasm (3.18% of base)
          39 : 15683.dasm (0.97% of base)
          39 : 17699.dasm (5.08% of base)
          39 : 2984.dasm (4.64% of base)
          39 : 17635.dasm (4.53% of base)
          36 : 20032.dasm (1.63% of base)
          36 : 8172.dasm (1.23% of base)
          33 : 5635.dasm (13.41% of base)
          32 : 17461.dasm (2.28% of base)
          31 : 17238.dasm (8.45% of base)
          31 : 22230.dasm (3.60% of base)
          30 : 18974.dasm (0.75% of base)
          29 : 8974.dasm (1.26% of base)
          29 : 6278.dasm (5.99% of base)
          27 : 9714.dasm (19.57% of base)

Top file improvements (bytes):
        -351 : 17979.dasm (-7.50% of base)
        -194 : 12466.dasm (-14.50% of base)
        -141 : 5943.dasm (-3.66% of base)
        -134 : 10075.dasm (-15.78% of base)
        -116 : 5941.dasm (-7.08% of base)
        -100 : 10080.dasm (-2.79% of base)
         -87 : 5916.dasm (-3.34% of base)
         -75 : 22440.dasm (-3.60% of base)
         -72 : 1287.dasm (-5.28% of base)
         -70 : 6054.dasm (-4.39% of base)
         -65 : 2901.dasm (-10.06% of base)
         -64 : 8010.dasm (-1.37% of base)
         -64 : 6071.dasm (-0.41% of base)
         -63 : 18262.dasm (-2.73% of base)
         -60 : 5932.dasm (-3.83% of base)
         -60 : 1586.dasm (-1.75% of base)
         -59 : 6049.dasm (-5.48% of base)
         -57 : 16172.dasm (-2.67% of base)
         -54 : 16142.dasm (-5.15% of base)
         -54 : 5945.dasm (-2.01% of base)

1888 total files with Code Size differences (1502 improved, 386 regressed), 9226 unchanged.

Top method regressions (bytes):
         356 (54.19% of base) : 324.dasm - System.Reflection.MethodBase:CheckArguments(byref,System.ReadOnlySpan`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],System.Reflection.Binder,int,System.Globalization.CultureInfo,System.RuntimeType[]):System.Span`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]:this
         116 ( 7.94% of base) : 22084.dasm - System.Net.Dns:GetHostEntryOrAddressesCore(System.Net.IPAddress,bool,int,Microsoft.Extensions.Internal.ValueStopwatch):System.Object
          81 ( 2.07% of base) : 7226.dasm - MessagePack.Internal.DynamicObjectTypeBuilder:BuildSerialize(System.Type,MessagePack.Internal.ObjectSerializationInfo,System.Reflection.Emit.ILGenerator,System.Action,System.Func`3[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MessagePack.Internal.ObjectSerializationInfo+EmittableMember, MessagePack, Version=1.9.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be],[System.Action, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],int)
          70 ( 1.56% of base) : 12172.dasm - System.Runtime.Serialization.Json.XmlJsonReader:Read():bool:this
          51 ( 0.72% of base) : 1459.dasm - ProtoBuf.Meta.MetaType:ApplyDefaultBehaviourImpl(int):this
          39 ( 5.08% of base) : 17699.dasm - Microsoft.CodeAnalysis.CSharp.ExecutableCodeBinder:ComputeBinderMap():this
          39 ( 4.53% of base) : 17635.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:AddSynthesizedConstructorsIfNecessary(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[[Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[ImmutableArray`1],Microsoft.CodeAnalysis.DiagnosticBag):this
          39 ( 0.97% of base) : 15683.dasm - System.Diagnostics.Process:StartWithCreateProcess(System.Diagnostics.ProcessStartInfo):bool:this
          39 ( 4.64% of base) : 2984.dasm - System.Resources.ResourceManager:GetFirstResourceSet(System.Globalization.CultureInfo):System.Resources.ResourceSet:this
          39 ( 3.18% of base) : 6819.dasm - System.Text.Json.Tests.Perf_Reader:Setup():this
          36 ( 1.63% of base) : 20032.dasm - CriticalHelper:ReadSimpleDictionary(System.Runtime.Serialization.CollectionDataContract,System.Type):this
          36 ( 1.23% of base) : 8172.dasm - System.Xml.Serialization.TempAssembly:GenerateRefEmitAssembly(System.Xml.Serialization.XmlMapping[],System.Type[],System.String):System.Reflection.Assembly
          33 (13.41% of base) : 5635.dasm - System.Net.IPAddress:.ctor(System.ReadOnlySpan`1[Byte]):this
          32 ( 2.28% of base) : 17461.dasm - Microsoft.CodeAnalysis.CommonReferenceManager`2[__Canon,__Canon][System.__Canon,System.__Canon]:ReuseAssemblySymbolsWithNoPiaLocalTypes(Microsoft.CodeAnalysis.CommonReferenceManager`2+BoundInputAssembly[System.__Canon,System.__Canon][],System.__Canon[],System.Collections.Immutable.ImmutableArray`1[__Canon],int):bool:this
          31 ( 3.60% of base) : 22230.dasm - Enumerator[Int32][System.Int32]:.ctor(Node[Int32],Builder[Int32],int,int,bool):this
          31 ( 8.45% of base) : 17238.dasm - Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode:ComputeSyntaxTree(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode):Microsoft.CodeAnalysis.SyntaxTree
          30 ( 0.75% of base) : 18974.dasm - CriticalHelper:ReadCollection(System.Runtime.Serialization.CollectionDataContract):this
          29 ( 1.26% of base) : 8974.dasm - System.Numerics.BigIntegerCalculator:PowCore(System.Span`1[UInt32],int,System.ReadOnlySpan`1[UInt32],System.ReadOnlySpan`1[UInt32],System.Span`1[UInt32],System.Span`1[UInt32])
          29 ( 5.99% of base) : 6278.dasm - System.Reflection.PortableExecutable.PEReader:ReadDebugDirectory():System.Collections.Immutable.ImmutableArray`1[DebugDirectoryEntry]:this
          27 ( 9.44% of base) : 6696.dasm - Newtonsoft.Json.Linq.JObject:Property(System.String,int):Newtonsoft.Json.Linq.JProperty:this

Top method improvements (bytes):
        -351 (-7.50% of base) : 17979.dasm - Microsoft.CodeAnalysis.CSharp.Binder:CheckValueKind(Microsoft.CodeAnalysis.SyntaxNode,Microsoft.CodeAnalysis.CSharp.BoundExpression,ushort,bool,Microsoft.CodeAnalysis.DiagnosticBag):bool:this
        -194 (-14.50% of base) : 12466.dasm - System.Diagnostics.Tracing.EventSource:WriteEventWithRelatedActivityIdCore(int,long,int,long):this
        -141 (-3.66% of base) : 5943.dasm - <ConnectAsync>d__96:MoveNext():this
        -134 (-15.78% of base) : 10075.dasm - System.Net.Security.SslSessionsCache:<CacheCredential>g__ShrinkCredentialCache|5_0()
        -116 (-7.08% of base) : 5941.dasm - <CreateHttp11ConnectionAsync>d__98:MoveNext():this
        -100 (-2.79% of base) : 10080.dasm - <ReceiveBlobAsync>d__174`1[AsyncReadWriteAdapter][System.Net.Security.AsyncReadWriteAdapter]:MoveNext():this
         -87 (-3.34% of base) : 5916.dasm - <GetHttp11ConnectionAsync>d__75:MoveNext():this
         -75 (-3.60% of base) : 22440.dasm - Utf8Json.Formatters.MicroBenchmarks_Serializers_ActiveOrUpcomingEventFormatter2:Deserialize(byref,Utf8Json.IJsonFormatterResolver):MicroBenchmarks.Serializers.ActiveOrUpcomingEvent:this
         -72 (-5.28% of base) : 1287.dasm - MicroBenchmarks.Serializers.DataGenerator:CreateMyEventsListerItem():MicroBenchmarks.Serializers.MyEventsListerItem
         -70 (-4.39% of base) : 6054.dasm - <ApplyPlaintextFilterAsync>d__100:MoveNext():this
         -65 (-10.06% of base) : 2901.dasm - Sigil.Impl.BufferedILGenerator`1[__Canon][System.__Canon]:Emit(System.Reflection.Emit.OpCode,Sigil.Label,byref):this
         -64 (-0.41% of base) : 6071.dasm - <SendAsyncCore>d__60:MoveNext():this
         -64 (-1.37% of base) : 8010.dasm - Newtonsoft.Json.JsonWriter:WriteValue(Newtonsoft.Json.JsonWriter,int,System.Object)
         -63 (-2.73% of base) : 18262.dasm - Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyEventsListerViewModel:Read4_MyEventsListerItem(bool,bool):MicroBenchmarks.Serializers.MyEventsListerItem:this
         -60 (-3.83% of base) : 5932.dasm - <AddHttp11ConnectionAsync>d__73:MoveNext():this
         -60 (-1.75% of base) : 1586.dasm - ProtoBuf.Meta.MetaType:BuildSerializer():ProtoBuf.Internal.Serializers.IProtoTypeSerializer:this
         -59 (-5.48% of base) : 6049.dasm - <ConstructHttp11ConnectionAsync>d__101:MoveNext():this
         -57 (-2.67% of base) : 16172.dasm - Utf8Json.Formatters.MicroBenchmarks_Serializers_MyEventsListerItemFormatter2:Deserialize(byref,Utf8Json.IJsonFormatterResolver):MicroBenchmarks.Serializers.MyEventsListerItem:this
         -54 (-2.01% of base) : 5945.dasm - <ConnectToTcpHostAsync>d__97:MoveNext():this
         -54 (-5.15% of base) : 16142.dasm - LUDecomp:build_problem(System.Double[][],int,System.Double[])

Top method regressions (percentages):
         356 (54.19% of base) : 324.dasm - System.Reflection.MethodBase:CheckArguments(byref,System.ReadOnlySpan`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],System.Reflection.Binder,int,System.Globalization.CultureInfo,System.RuntimeType[]):System.Span`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]:this
           7 (35.00% of base) : 21467.dasm - System.Tests.Perf_String:Concat_str_str_str(System.Tests.StringArguments):System.String:this
          11 (33.33% of base) : 19567.dasm - <>c__DisplayClass2_1:<RenderSingleThreadedWithADT>b__1(int,int):this
          11 (33.33% of base) : 19017.dasm - <>c__DisplayClass3_1:<RenderSingleThreadedNoADT>b__1(int,int):this
          11 (33.33% of base) : 20098.dasm - <>c__DisplayClass3_1:<RenderSingleThreadedNoADT>b__1(long,int):this
          11 (33.33% of base) : 20620.dasm - <>c__DisplayClass4_1:<RenderSingleThreadedWithADT>b__1(long,int):this
           6 (26.09% of base) : 8317.dasm - System.Text.RegularExpressions.Capture:get_Value():System.String:this
          25 (26.04% of base) : 17640.dasm - Microsoft.CodeAnalysis.ArrayBuilderExtensions:Any(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[ImmutableArray`1],System.Func`2[ImmutableArray`1,Boolean]):bool
           7 (24.14% of base) : 2598.dasm - System.String:GetHashCode():int:this
          24 (20.87% of base) : 9237.dasm - System.Text.RegularExpressions.Symbolic.RegexNodeToSymbolicConverter:<Convert>g__EnsureNewlinePredicateInitialized|9_0():this
          27 (19.57% of base) : 9714.dasm - System.Uri:ToString():System.String:this
          17 (17.89% of base) : 19399.dasm - System.Text.RegularExpressions.Symbolic.RegexNodeToSymbolicConverter:<Convert>g__EnsureWordLetterPredicateInitialized|9_1():this
          23 (17.69% of base) : 6736.dasm - Newtonsoft.Json.Linq.JObject:WriteTo(Newtonsoft.Json.JsonWriter,Newtonsoft.Json.JsonConverter[]):this
           7 (17.50% of base) : 1692.dasm - ProtoBuf.Serializers.RepeatedSerializerStub:EmitProvider(System.Reflection.Emit.ILGenerator):this
           4 (14.81% of base) : 21912.dasm - System.Tests.Perf_String:Concat_str_str_str_str(System.Tests.StringArguments):System.String:this
           7 (14.00% of base) : 19019.dasm - StoreBlock.AnyLocation:InitBlockAllZeros8():this
           7 (13.73% of base) : 19570.dasm - StoreBlock.AnyLocation:InitBlockAllOnes8():this
          33 (13.41% of base) : 5635.dasm - System.Net.IPAddress:.ctor(System.ReadOnlySpan`1[Byte]):this
          11 (12.94% of base) : 4072.dasm - System.Xml.XmlTextReaderImpl:ElementNamespaceLookup():this
          27 ( 9.44% of base) : 6696.dasm - Newtonsoft.Json.Linq.JObject:Property(System.String,int):Newtonsoft.Json.Linq.JProperty:this

Top method improvements (percentages):
         -24 (-42.11% of base) : 3757.dasm - EscaperImplementation:.ctor(bool):this
          -8 (-42.11% of base) : 14454.dasm - System.Span`1[__Canon][System.__Canon]:Clear():this
          -8 (-27.59% of base) : 4154.dasm - Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache:.ctor(int,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey):this
         -10 (-25.00% of base) : 9639.dasm - DataMemberComparer:Compare(System.Runtime.Serialization.DataMember,System.Runtime.Serialization.DataMember):int:this
          -3 (-25.00% of base) : 23079.dasm - System.Threading.Tests.Perf_Volatile:Read_double():double:this
         -22 (-20.00% of base) : 11532.dasm - System.Buffers.Tests.BufferSegment`1[Byte][System.Byte]:Append(System.ReadOnlyMemory`1[Byte]):System.Buffers.Tests.BufferSegment`1[Byte]:this
         -22 (-20.00% of base) : 5568.dasm - System.Memory.BufferSegment`1[Byte][System.Byte]:Append(System.ReadOnlyMemory`1[Byte]):System.Memory.BufferSegment`1[Byte]:this
         -52 (-19.55% of base) : 18264.dasm - Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyEventsListerViewModel:Read1_NullableOfDateTimeOffset(bool):System.Nullable`1[DateTimeOffset]:this
         -33 (-17.65% of base) : 17612.dasm - Microsoft.CodeAnalysis.CSharp.Binder:WithUnsafeRegionIfNecessary(Microsoft.CodeAnalysis.SyntaxTokenList):Microsoft.CodeAnalysis.CSharp.Binder:this
         -31 (-17.61% of base) : 12618.dasm - System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[__Canon][System.__Canon]:ReadAheadPropertyValue(byref,byref,System.Text.Json.Serialization.Metadata.JsonPropertyInfo):bool
         -31 (-17.61% of base) : 23561.dasm - System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[LargeStructWithProperties][MicroBenchmarks.Serializers.LargeStructWithProperties]:ReadAheadPropertyValue(byref,byref,System.Text.Json.Serialization.Metadata.JsonPropertyInfo):bool
         -28 (-15.91% of base) : 6755.dasm - Newtonsoft.Json.JsonWriter:Pop():int:this
         -16 (-15.84% of base) : 20200.dasm - System.Numerics.Matrix4x4:op_Equality(System.Numerics.Matrix4x4,System.Numerics.Matrix4x4):bool
        -134 (-15.78% of base) : 10075.dasm - System.Net.Security.SslSessionsCache:<CacheCredential>g__ShrinkCredentialCache|5_0()
         -10 (-15.38% of base) : 10920.dasm - System.Net.Http.HttpConnectionPool:GetSslOptionsForRequest(System.Net.Http.HttpRequestMessage):System.Net.Security.SslClientAuthenticationOptions:this
         -16 (-15.38% of base) : 16312.dasm - System.Numerics.Matrix4x4:op_Inequality(System.Numerics.Matrix4x4,System.Numerics.Matrix4x4):bool
         -12 (-15.19% of base) : 22559.dasm - DynamicClass:StartDateSetter(System.Object,System.DateTimeOffset)
         -15 (-14.85% of base) : 6132.dasm - System.Net.Http.HttpConnection:EqualsOrdinal(System.String,System.ReadOnlySpan`1[Byte]):bool
          -6 (-14.63% of base) : 11077.dasm - <>c:<set_MaxCacheSize>b__11_0(Node,Node):int:this
        -194 (-14.50% of base) : 12466.dasm - System.Diagnostics.Tracing.EventSource:WriteEventWithRelatedActivityIdCore(int,long,int,long):this

1888 total methods with Code Size differences (1502 improved, 386 regressed), 9226 unchanged.

```

</details>

--------------------------------------------------------------------------------

## coreclr_tests.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 125687386 (overridden on cmd)
Total bytes of diff: 125612814 (overridden on cmd)
Total bytes of delta: -74572 (-0.06 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
        4305 : 228767.dasm (3.56% of base)
        4203 : 228757.dasm (3.44% of base)
         636 : 219486.dasm (0.45% of base)
         624 : 219389.dasm (0.46% of base)
         581 : 219369.dasm (0.44% of base)
         565 : 219466.dasm (0.42% of base)
         415 : 219418.dasm (0.34% of base)
         415 : 219428.dasm (0.34% of base)
         415 : 219251.dasm (0.34% of base)
         415 : 219270.dasm (0.34% of base)
         295 : 234492.dasm (1.28% of base)
         280 : 234556.dasm (1.21% of base)
         277 : 234630.dasm (1.19% of base)
         268 : 234529.dasm (1.11% of base)
         268 : 234640.dasm (1.14% of base)
         265 : 234566.dasm (1.13% of base)
         264 : 228650.dasm (1.07% of base)
         264 : 228656.dasm (1.07% of base)
         259 : 219213.dasm (0.20% of base)
         254 : 219309.dasm (0.20% of base)

Top file improvements (bytes):
       -1526 : 161218.dasm (-16.72% of base)
       -1210 : 256458.dasm (-8.81% of base)
       -1105 : 226565.dasm (-7.16% of base)
       -1105 : 226568.dasm (-7.16% of base)
       -1059 : 93555.dasm (-21.56% of base)
       -1059 : 91021.dasm (-20.44% of base)
       -1059 : 90808.dasm (-20.43% of base)
       -1059 : 90810.dasm (-20.64% of base)
       -1057 : 93557.dasm (-20.95% of base)
       -1057 : 93559.dasm (-20.57% of base)
        -980 : 161488.dasm (-14.06% of base)
        -953 : 90805.dasm (-17.20% of base)
        -944 : 164092.dasm (-13.61% of base)
        -933 : 90813.dasm (-14.68% of base)
        -846 : 256459.dasm (-7.91% of base)
        -843 : 229545.dasm (-1.40% of base)
        -819 : 229550.dasm (-1.36% of base)
        -739 : 161442.dasm (-8.38% of base)
        -632 : 162140.dasm (-10.33% of base)
        -572 : 164550.dasm (-9.60% of base)

12030 total files with Code Size differences (10443 improved, 1587 regressed), 34702 unchanged.

Top method regressions (bytes):
        4305 ( 3.56% of base) : 228767.dasm - r8div:Main():int
        4203 ( 3.44% of base) : 228757.dasm - r4div:Main():int
         636 ( 0.45% of base) : 219486.dasm - u8rem:Main():int
         624 ( 0.46% of base) : 219389.dasm - i8rem:Main():int
         581 ( 0.44% of base) : 219369.dasm - i4rem:Main():int
         565 ( 0.42% of base) : 219466.dasm - u4rem:Main():int
         415 ( 0.34% of base) : 219251.dasm - overlddiv:Main():int
         415 ( 0.34% of base) : 219270.dasm - overlddiv:Main():int
         415 ( 0.34% of base) : 219418.dasm - overldrem:Main():int
         415 ( 0.34% of base) : 219428.dasm - overldrem:Main():int
         295 ( 1.28% of base) : 234492.dasm - lclfldadd:Main():int
         280 ( 1.21% of base) : 234556.dasm - lclfldmul:Main():int
         277 ( 1.19% of base) : 234630.dasm - lclfldsub:Main():int
         268 ( 1.11% of base) : 234529.dasm - lclflddiv:Main():int
         268 ( 1.14% of base) : 234640.dasm - lclfldsub:Main():int
         265 ( 1.13% of base) : 234566.dasm - lclfldmul:Main():int
         264 ( 1.07% of base) : 228650.dasm - r8NaNmul:Main():int
         264 ( 1.07% of base) : 228656.dasm - r8NaNmul:Main():int
         259 ( 0.20% of base) : 219213.dasm - i8div:Main():int
         254 ( 0.20% of base) : 219309.dasm - u4div:Main():int

Top method improvements (bytes):
       -1526 (-16.72% of base) : 161218.dasm - testout1:Func_0_4_5_4():System.Decimal
       -1210 (-8.81% of base) : 256458.dasm - bug178119:foo1():int
       -1105 (-7.16% of base) : 226565.dasm - IntelHardwareIntrinsicTest.Program:Main(System.String[]):int
       -1105 (-7.16% of base) : 226568.dasm - IntelHardwareIntrinsicTest.Program:Main(System.String[]):int
       -1059 (-21.56% of base) : 93555.dasm - JitTest.Test:Main():int
       -1059 (-20.44% of base) : 91021.dasm - JitTest.Test:Main():int
       -1059 (-20.43% of base) : 90808.dasm - JitTest.Test:Main():int
       -1059 (-20.64% of base) : 90810.dasm - JitTest.Test:Main():int
       -1057 (-20.95% of base) : 93557.dasm - JitTest.Test:Main():int
       -1057 (-20.57% of base) : 93559.dasm - JitTest.Test:Main():int
        -980 (-14.06% of base) : 161488.dasm - testout1:Func_0_2_3_1_5():System.Decimal
        -953 (-17.20% of base) : 90805.dasm - JitTest.Test:Main():int
        -944 (-13.61% of base) : 164092.dasm - testout1:Func_0_2_3_1_5():System.Decimal
        -933 (-14.68% of base) : 90813.dasm - JitTest.Test:Main():int
        -846 (-7.91% of base) : 256459.dasm - bug178119:foo2():int
        -843 (-1.40% of base) : 229545.dasm - testout1:Func_0():int
        -819 (-1.36% of base) : 229550.dasm - testout1:Func_0():int
        -739 (-8.38% of base) : 161442.dasm - testout1:Func_0_1_6_6_1():System.Decimal
        -632 (-10.33% of base) : 162140.dasm - testout1:Func_0_5_5_5_6():System.Decimal
        -572 (-9.60% of base) : 164550.dasm - testout1:Func_0_5_5_5_6():System.Decimal

Top method regressions (percentages):
          35 (3,500.00% of base) : 224259.dasm - TestUnsafeCasts:StructFromPrim()
         102 (728.57% of base) : 92552.dasm - Z:Main():int
          85 (607.14% of base) : 92517.dasm - Z:Main(System.String[]):int
          17 (188.89% of base) : 216950.dasm - TestClassVTableTracking:Run()
         246 (179.56% of base) : 241821.dasm - ServerSimulator.Parameters:.ctor():this
          18 (163.64% of base) : 246904.dasm - JitTest.Test:method_3_0(long):long
          18 (163.64% of base) : 246794.dasm - JitTest.Test:method_3_0(long):long
          18 (163.64% of base) : 247235.dasm - JitTest.Test:method_3_0(ushort):ushort
          18 (163.64% of base) : 256210.dasm - JitTest.Test:method_3_6(JitTest.ValueClass):JitTest.ValueClass
          18 (163.64% of base) : 256222.dasm - JitTest.Test:method_5_0(JitTest.ValueClass):JitTest.ValueClass
          18 (163.64% of base) : 246776.dasm - JitTest.Test:method_5_3(long):long
          18 (163.64% of base) : 246886.dasm - JitTest.Test:method_5_3(long):long
          18 (163.64% of base) : 247218.dasm - JitTest.Test:method_5_3(ushort):ushort
          18 (163.64% of base) : 246779.dasm - JitTest.Test:method_5_6(long):long
          18 (163.64% of base) : 246889.dasm - JitTest.Test:method_5_6(long):long
          18 (163.64% of base) : 247221.dasm - JitTest.Test:method_5_6(ushort):ushort
          51 (159.38% of base) : 97723.dasm - Test_TestCase0:Main():int
          51 (159.38% of base) : 97724.dasm - Test_TestCase0:Main():int
          51 (159.38% of base) : 97725.dasm - Test_TestCase1:Main():int
          17 (121.43% of base) : 96212.dasm - _callvirt:main(System.String[]):int

Top method improvements (percentages):
         -31 (-91.18% of base) : 241290.dasm - S:m(S):this
         -31 (-91.18% of base) : 241297.dasm - S1:m(S2):this
         -31 (-91.18% of base) : 241300.dasm - S1`1[Byte][System.Byte]:m(S2`1[Byte]):this
         -31 (-91.18% of base) : 241298.dasm - S2:m(S1):this
         -31 (-91.18% of base) : 241302.dasm - S2`1[Byte][System.Byte]:m(S1`1[Byte]):this
         -31 (-91.18% of base) : 241292.dasm - S2`1[Byte][System.Byte]:m(S2`1[Byte]):this
          -6 (-60.00% of base) : 229398.dasm - TestApp:test_0_1(ubyte,AA,AA):ubyte
          -8 (-57.14% of base) : 96217.dasm - _isinst:main(System.String[]):int
          -8 (-57.14% of base) : 96225.dasm - _newobj:main(System.String[]):int
          -8 (-57.14% of base) : 96133.dasm - ldind_ref:main(System.String[]):int
          -8 (-47.06% of base) : 246286.dasm - InlineBool.Program:Id02(bool):bool
          -8 (-47.06% of base) : 246288.dasm - InlineBool.Program:Id05(bool):bool
          -8 (-47.06% of base) : 246272.dasm - InlineBool.Program:Id43(bool):bool
          -8 (-47.06% of base) : 246251.dasm - InlineBool.Program:Id72(bool):bool
         -19 (-46.34% of base) : 207048.dasm - Tests:Test141_cns(int):ubyte
         -19 (-46.34% of base) : 206990.dasm - Tests:Test144_cns(int):ubyte
         -19 (-46.34% of base) : 206996.dasm - Tests:Test147_cns(int):ubyte
         -19 (-46.34% of base) : 207004.dasm - Tests:Test151_cns(int):ubyte
         -19 (-46.34% of base) : 207012.dasm - Tests:Test155_cns(int):ubyte
         -19 (-46.34% of base) : 206954.dasm - Tests:Test158_cns(int):ubyte

12030 total methods with Code Size differences (10443 improved, 1587 regressed), 34702 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.crossgen2.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 33840459 (overridden on cmd)
Total bytes of diff: 33806367 (overridden on cmd)
Total bytes of delta: -34092 (-0.10 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         339 : 101030.dasm (12.81% of base)
         313 : 5692.dasm (52.52% of base)
         175 : 87909.dasm (2.71% of base)
         141 : 55252.dasm (6.33% of base)
         140 : 85038.dasm (3.00% of base)
         117 : 63710.dasm (68.42% of base)
         109 : 135503.dasm (5.09% of base)
         105 : 63618.dasm (12.24% of base)
         103 : 99874.dasm (9.36% of base)
          98 : 96195.dasm (2.83% of base)
          92 : 96209.dasm (2.85% of base)
          89 : 77410.dasm (0.71% of base)
          86 : 96265.dasm (2.82% of base)
          81 : 72708.dasm (14.44% of base)
          77 : 122243.dasm (10.69% of base)
          72 : 11373.dasm (3.55% of base)
          71 : 196656.dasm (4.11% of base)
          70 : 48183.dasm (7.36% of base)
          66 : 94646.dasm (31.88% of base)
          61 : 101359.dasm (13.01% of base)

Top file improvements (bytes):
       -1199 : 48057.dasm (-2.77% of base)
        -553 : 150312.dasm (-3.75% of base)
        -138 : 196477.dasm (-4.05% of base)
        -132 : 96716.dasm (-3.02% of base)
        -128 : 125173.dasm (-7.01% of base)
        -120 : 187382.dasm (-1.77% of base)
        -112 : 121694.dasm (-2.52% of base)
        -103 : 91217.dasm (-2.86% of base)
        -101 : 85458.dasm (-4.32% of base)
         -98 : 203490.dasm (-6.39% of base)
         -96 : 77231.dasm (-2.27% of base)
         -95 : 22376.dasm (-6.18% of base)
         -92 : 13739.dasm (-12.71% of base)
         -92 : 163580.dasm (-10.37% of base)
         -91 : 136659.dasm (-8.45% of base)
         -91 : 203515.dasm (-6.95% of base)
         -82 : 150475.dasm (-0.71% of base)
         -80 : 70717.dasm (-3.49% of base)
         -75 : 13740.dasm (-10.81% of base)
         -75 : 196925.dasm (-7.04% of base)

8946 total files with Code Size differences (6917 improved, 2029 regressed), 20935 unchanged.

Top method regressions (bytes):
         339 (12.81% of base) : 101030.dasm - System.Data.XMLDiffLoader:ReadOldRowData(System.Data.DataSet,byref,byref,System.Xml.XmlReader):int:this
         313 (52.52% of base) : 5692.dasm - System.Reflection.MethodBase:CheckArguments(byref,System.ReadOnlySpan`1[System.Object],System.Reflection.Binder,int,System.Globalization.CultureInfo,System.RuntimeType[]):System.Span`1[System.Object]:this
         175 ( 2.71% of base) : 87909.dasm - System.Xml.Schema.SchemaCollectionPreprocessor:Preprocess(System.Xml.Schema.XmlSchema,System.String,int):this
         141 ( 6.33% of base) : 55252.dasm - ReferenceManager:CreateAndSetSourceAssemblyFullBind(Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation):bool:this
         140 ( 3.00% of base) : 85038.dasm - System.Xml.Xsl.XsltOld.HtmlElementProps:CreatePropsTable():System.Collections.Hashtable
         117 (68.42% of base) : 63710.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxListBuilder:AddRange(Microsoft.CodeAnalysis.SyntaxNode[],int,int):Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxListBuilder:this
         109 ( 5.09% of base) : 135503.dasm - Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter:GetDelta(Microsoft.CodeAnalysis.Emit.EmitBaseline,Microsoft.CodeAnalysis.Compilation,System.Guid,Microsoft.Cci.MetadataSizes):Microsoft.CodeAnalysis.Emit.EmitBaseline:this
         105 (12.24% of base) : 63618.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxTriviaListBuilder:ToList():Microsoft.CodeAnalysis.SyntaxTriviaList:this
         103 ( 9.36% of base) : 99874.dasm - System.Data.DataSet:SerializeDataSet(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext,int):this
          98 ( 2.83% of base) : 96195.dasm - System.Data.Common.SqlMoneyStorage:Aggregate(System.Int32[],int):System.Object:this
          92 ( 2.85% of base) : 96209.dasm - System.Data.Common.SqlInt64Storage:Aggregate(System.Int32[],int):System.Object:this
          89 ( 0.71% of base) : 77410.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:ReportOverloadResolutionFailureForASingleCandidate(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.Location,int,byref,System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.BoundExpression],System.Collections.Immutable.ImmutableArray`1[System.String],bool,bool,bool,bool,Microsoft.CodeAnalysis.DiagnosticBag,Microsoft.CodeAnalysis.VisualBasic.Symbol,bool,Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.Symbol):this
          86 ( 2.82% of base) : 96265.dasm - System.Data.Common.SqlDoubleStorage:Aggregate(System.Int32[],int):System.Object:this
          81 (14.44% of base) : 72708.dasm - Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbolExtensions:TransformToCanonicalFormFor(System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol],Microsoft.CodeAnalysis.VisualBasic.Symbol,System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeParameterSymbol]):System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol]
          77 (10.69% of base) : 122243.dasm - Microsoft.CodeAnalysis.CSharp.LocalRewriter:EvaluateSideEffectingArgumentsToTemps(System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.CSharp.BoundExpression],Microsoft.CodeAnalysis.ArrayBuilder`1[Microsoft.CodeAnalysis.CSharp.BoundExpression],byref):System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.CSharp.BoundExpression]:this
          72 ( 3.55% of base) : 11373.dasm - System.Globalization.TimeSpanFormat:FormatCustomized(System.TimeSpan,System.ReadOnlySpan`1[System.Char],System.Globalization.DateTimeFormatInfo,System.Text.StringBuilder):System.Text.StringBuilder
          71 ( 4.11% of base) : 196656.dasm - System.DirectoryServices.Protocols.DirectoryControl:TransformControls(System.DirectoryServices.Protocols.DirectoryControl[])
          70 ( 7.36% of base) : 48183.dasm - Microsoft.Diagnostics.Tracing.SampleProfilerThreadTimeComputer:<GenerateThreadTimeStacks>b__8_2(Microsoft.Diagnostics.Tracing.TraceEvent):this
          66 (31.88% of base) : 94646.dasm - MS.Internal.Xml.Cache.XPathNodeHelper:GetContentChild(byref,byref):bool
          61 (13.01% of base) : 101359.dasm - System.Xml.XmlDataDocument:GetRowInsertBeforeLocation(System.Data.DataRow,System.Xml.XmlElement,System.Xml.XmlNode):System.Xml.XmlNode:this

Top method improvements (bytes):
       -1199 (-2.77% of base) : 48057.dasm - Microsoft.Diagnostics.Tracing.CtfTraceEventSource:InitEventMap():System.Collections.Generic.Dictionary`2[System.String, Microsoft.Diagnostics.Tracing.ETWMapping]
        -553 (-3.75% of base) : 150312.dasm - <StartupCode$FSharp-Core>.$Query:.cctor()
        -138 (-4.05% of base) : 196477.dasm - System.DirectoryServices.Protocols.LdapConnection:SendRequestHelper(System.DirectoryServices.Protocols.DirectoryRequest,byref):int:this
        -132 (-3.02% of base) : 96716.dasm - System.Data.Common.DbDataAdapter:Update(System.Data.DataRow[],System.Data.Common.DataTableMapping):int:this
        -128 (-7.01% of base) : 125173.dasm - Microsoft.CodeAnalysis.CSharp.ClsComplianceChecker:TryGetCollisionErrorCode(Microsoft.CodeAnalysis.CSharp.Symbol,Microsoft.CodeAnalysis.CSharp.Symbol,byref):bool
        -120 (-1.77% of base) : 187382.dasm - R2RTest.BuildFolderSet:WriteBuildStatistics(System.IO.StreamWriter):this
        -112 (-2.52% of base) : 121694.dasm - Microsoft.CodeAnalysis.CSharp.TypeUnification:CanUnifyHelper(Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithModifiers,Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithModifiers,byref):bool
        -103 (-2.86% of base) : 91217.dasm - System.Xml.XmlTextReaderImpl:ParseAttributeValueSlow(int,ushort,System.Xml.XmlTextReaderImpl+NodeData):this
        -101 (-4.32% of base) : 85458.dasm - System.Xml.Xsl.Xslt.XsltInput:GetAttributes(System.Xml.Xsl.Xslt.XsltInput+XsltAttribute[]):System.Xml.Xsl.Xslt.XsltInput+ContextInfo:this
         -98 (-6.39% of base) : 203490.dasm - System.Threading.Tasks.Parallel:PartitionerForEachWorker(System.Collections.Concurrent.Partitioner`1[System.__Canon],System.Threading.Tasks.ParallelOptions,System.Action`1[System.__Canon],System.Action`2[System.__Canon, System.Threading.Tasks.ParallelLoopState],System.Action`3[System.__Canon, System.Threading.Tasks.ParallelLoopState, System.Int64],System.Func`4[System.__Canon, System.Threading.Tasks.ParallelLoopState, System.__Canon, System.__Canon],System.Func`5[System.__Canon, System.Threading.Tasks.ParallelLoopState, System.Int64, System.__Canon, System.__Canon],System.Func`1[System.__Canon],System.Action`1[System.__Canon]):System.Threading.Tasks.ParallelLoopResult
         -96 (-2.27% of base) : 77231.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:BindRaiseEventStatement(Microsoft.CodeAnalysis.VisualBasic.Syntax.RaiseEventStatementSyntax,Microsoft.CodeAnalysis.DiagnosticBag):Microsoft.CodeAnalysis.VisualBasic.BoundStatement:this
         -95 (-6.18% of base) : 22376.dasm - Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase:VisitChildren(Microsoft.CSharp.RuntimeBinder.Semantics.Expr):this
         -92 (-10.37% of base) : 163580.dasm - Microsoft.Extensions.DependencyModel.DependencyContextWriter:WriteCompilationOptions(Microsoft.Extensions.DependencyModel.CompilationOptions,System.Text.Json.Utf8JsonWriter):this
         -92 (-12.71% of base) : 13739.dasm - System.TupleExtensions:ToValueTuple(System.Tuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.Tuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.Tuple`7[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon]]]):System.ValueTuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.ValueTuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.ValueTuple`7[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon]]]
         -91 (-8.45% of base) : 136659.dasm - Microsoft.CodeAnalysis.AbstractSyntaxNavigator:GetPreviousToken(Microsoft.CodeAnalysis.SyntaxTrivia,Microsoft.CodeAnalysis.SyntaxTriviaList,System.Func`2[Microsoft.CodeAnalysis.SyntaxToken, System.Boolean],System.Func`2[Microsoft.CodeAnalysis.SyntaxTrivia, System.Boolean],byref):Microsoft.CodeAnalysis.SyntaxToken:this
         -91 (-6.95% of base) : 203515.dasm - System.Threading.Tasks.Parallel:ForWorker(int,int,System.Threading.Tasks.ParallelOptions,System.Action`1[System.Int32],System.Action`2[System.Int32, System.Threading.Tasks.ParallelLoopState],System.Func`4[System.Int32, System.Threading.Tasks.ParallelLoopState, System.__Canon, System.__Canon],System.Func`1[System.__Canon],System.Action`1[System.__Canon]):System.Threading.Tasks.ParallelLoopResult
         -82 (-0.71% of base) : 150475.dasm - Microsoft.FSharp.Linq.QueryModule:TransInner(int,bool,Microsoft.FSharp.Quotations.FSharpExpr):System.Tuple`2[Microsoft.FSharp.Linq.QueryModule+TransInnerResult, Microsoft.FSharp.Linq.RuntimeHelpers.Adapters+ConversionDescription]
         -80 (-3.49% of base) : 70717.dasm - Microsoft.CodeAnalysis.VisualBasic.LocalRewriter:RewriteIfStatement(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.BoundStatement,Microsoft.CodeAnalysis.VisualBasic.BoundStatement,bool,System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.BoundStatement]):Microsoft.CodeAnalysis.VisualBasic.BoundStatement:this
         -75 (-7.04% of base) : 196925.dasm - EncodeHelpers:EncodeKeyTransRecipientInfo(System.Security.Cryptography.Pkcs.CmsRecipient,Internal.Cryptography.Pal.Windows.HeapBlockRetainer):long
         -75 (-5.68% of base) : 39212.dasm - Microsoft.Diagnostics.Tracing.Parsers.MicrosoftWindowsTCPIP.TcpConnectionSummaryArgs:PayloadValue(int):System.Object:this

Top method regressions (percentages):
         117 (68.42% of base) : 63710.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxListBuilder:AddRange(Microsoft.CodeAnalysis.SyntaxNode[],int,int):Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxListBuilder:this
          25 (64.10% of base) : 95503.dasm - <>c__DisplayClass36_0:<ReadInternal>b__2():this
          10 (62.50% of base) : 189338.dasm - <>c__0`1:<Create>b__0_0(System.Diagnostics.Metrics.LabelInstruction,System.Diagnostics.Metrics.LabelInstruction):int:this
          10 (55.56% of base) : 178233.dasm - <>c:<GetUnreadOptionNames>b__13_1(Internal.CommandLine.ArgumentToken):System.String:this
          10 (55.56% of base) : 56060.dasm - Comparer:Equals(Microsoft.CodeAnalysis.VisualBasic.Symbols.SingleNamespaceDeclaration,Microsoft.CodeAnalysis.VisualBasic.Symbols.SingleNamespaceDeclaration):bool:this
          10 (55.56% of base) : 176045.dasm - PointerHashtable:CompareValueToValue(Internal.TypeSystem.PointerType,Internal.TypeSystem.PointerType):bool:this
          10 (55.56% of base) : 11336.dasm - TimeSpanTokenizer:.ctor(System.ReadOnlySpan`1[System.Char]):this
         313 (52.52% of base) : 5692.dasm - System.Reflection.MethodBase:CheckArguments(byref,System.ReadOnlySpan`1[System.Object],System.Reflection.Binder,int,System.Globalization.CultureInfo,System.RuntimeType[]):System.Span`1[System.Object]:this
          10 (47.62% of base) : 153511.dasm - ArgumentStorage:EmitAddress():this
          10 (47.62% of base) : 153513.dasm - ArgumentStorage:EmitLoad():this
          10 (47.62% of base) : 153512.dasm - ArgumentStorage:EmitStore():this
          10 (45.45% of base) : 189361.dasm - <>c__DisplayClass24_0:<Include>b__0(System.Diagnostics.Metrics.Instrument):bool:this
          10 (40.00% of base) : 186274.dasm - System.Net.HttpListenerRequest:GetChannelBinding():System.Security.Authentication.ExtendedProtection.ChannelBinding:this
           3 (37.50% of base) : 143109.dasm - System.Text.Json.JsonSerializerOptions:GetNodeOptions():System.Text.Json.Nodes.JsonNodeOptions:this
          10 (35.71% of base) : 29999.dasm - Microsoft.Diagnostics.Tracing.Ctf.CtfArray:ToString():System.String:this
          10 (35.71% of base) : 172210.dasm - System.CommandLine.Binding.BoundValue:ToString():System.String:this
          10 (34.48% of base) : 104536.dasm - <>c__DisplayClass5_0:<GetPropertyString>b__0():System.Object:this
          10 (33.33% of base) : 175843.dasm - FieldForInstantiatedTypeKeyHashtable:CompareKeyToValue(Internal.TypeSystem.TypeSystemContext+FieldForInstantiatedTypeKey,Internal.TypeSystem.FieldForInstantiatedType):bool:this
          10 (33.33% of base) : 175848.dasm - MethodForInstantiatedTypeKeyHashtable:CompareKeyToValue(Internal.TypeSystem.TypeSystemContext+MethodForInstantiatedTypeKey,Internal.TypeSystem.MethodForInstantiatedType):bool:this
          10 (33.33% of base) : 175831.dasm - MethodForRuntimeDeterminedTypeKeyHashtable:CompareKeyToValue(Internal.TypeSystem.TypeSystemContext+MethodForRuntimeDeterminedTypeKey,Internal.TypeSystem.MethodForRuntimeDeterminedType):bool:this

Top method improvements (percentages):
         -36 (-52.94% of base) : 160850.dasm - System.Linq.ParallelQuery`1:.ctor(System.Linq.Parallel.QuerySettings):this
         -39 (-46.43% of base) : 160115.dasm - System.Linq.Parallel.QueryOperator`1:.ctor(bool,System.Linq.Parallel.QuerySettings):this
         -39 (-46.43% of base) : 160982.dasm - System.Linq.Parallel.QueryOperator`1:.ctor(bool,System.Linq.Parallel.QuerySettings):this
         -18 (-46.15% of base) : 137257.dasm - Microsoft.CodeAnalysis.CompilationReference:.ctor(Microsoft.CodeAnalysis.MetadataReferenceProperties):this
         -34 (-45.33% of base) : 160116.dasm - System.Linq.Parallel.QueryOperator`1:.ctor(System.Linq.Parallel.QuerySettings):this
         -34 (-45.33% of base) : 160983.dasm - System.Linq.Parallel.QueryOperator`1:.ctor(System.Linq.Parallel.QuerySettings):this
         -24 (-42.11% of base) : 190383.dasm - EscaperImplementation:.ctor(bool):this
         -37 (-40.66% of base) : 171600.dasm - System.IO.Pipelines.PipeReader:Create(System.Buffers.ReadOnlySequence`1[System.Byte]):System.IO.Pipelines.PipeReader
          -3 (-37.50% of base) : 25499.dasm - System.Net.Http.Http3Connection:get_AbortException():System.Exception:this
          -3 (-37.50% of base) : 196209.dasm - System.Threading.Barrier:get_CurrentPhaseNumber():long:this
         -47 (-35.61% of base) : 135996.dasm - Microsoft.CodeAnalysis.SyntaxTriviaList:Equals(Microsoft.CodeAnalysis.SyntaxTriviaList):bool:this
         -37 (-34.26% of base) : 160061.dasm - System.Linq.Parallel.UnaryQueryOperator`2:.ctor(System.Linq.Parallel.QueryOperator`1[System.__Canon],bool,System.Linq.Parallel.QuerySettings):this
          -6 (-33.33% of base) : 6872.dasm - System.Runtime.InteropServices.MemoryMarshal:GetArrayDataReference(System.Array):byref
          -3 (-33.33% of base) : 9872.dasm - System.Threading.PortableThreadPool:GetMaxThreads():int:this
          -3 (-33.33% of base) : 9874.dasm - System.Threading.PortableThreadPool:GetMinThreads():int:this
         -42 (-33.07% of base) : 189804.dasm - System.Diagnostics.DiagLinkedList`1:.ctor(System.Diagnostics.ActivityEvent):this
         -19 (-30.16% of base) : 137178.dasm - Microsoft.CodeAnalysis.UnresolvedMetadataReference:.ctor(System.String,Microsoft.CodeAnalysis.MetadataReferenceProperties):this
          -9 (-30.00% of base) : 174651.dasm - Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache:.ctor(int,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey):this
          -3 (-30.00% of base) : 192535.dasm - System.Net.Sockets.Socket:get_SafeHandle():System.Net.Sockets.SafeSocketHandle:this
         -20 (-29.41% of base) : 206984.dasm - System.BinaryData:FromBytes(System.ReadOnlyMemory`1[System.Byte]):System.BinaryData

8946 total methods with Code Size differences (6917 improved, 2029 regressed), 20935 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 44427933 (overridden on cmd)
Total bytes of diff: 44358561 (overridden on cmd)
Total bytes of delta: -69372 (-0.16 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         369 : 172785.dasm (50.20% of base)
         238 : 141676.dasm (4.46% of base)
         203 : 172788.dasm (31.87% of base)
         194 : 18503.dasm (22.27% of base)
         188 : 30550.dasm (6.62% of base)
         164 : 18509.dasm (14.05% of base)
         164 : 18526.dasm (14.30% of base)
         154 : 137685.dasm (1.83% of base)
         140 : 140673.dasm (2.49% of base)
         122 : 16935.dasm (4.49% of base)
         112 : 26572.dasm (0.45% of base)
         112 : 18520.dasm (12.99% of base)
          99 : 29499.dasm (3.09% of base)
          98 : 114762.dasm (2.88% of base)
          94 : 114692.dasm (3.04% of base)
          93 : 114748.dasm (2.83% of base)
          90 : 116744.dasm (13.45% of base)
          90 : 43068.dasm (4.21% of base)
          84 : 75007.dasm (12.52% of base)
          82 : 188503.dasm (2.58% of base)

Top file improvements (bytes):
        -900 : 85717.dasm (-1.89% of base)
        -327 : 50965.dasm (-2.77% of base)
        -258 : 69447.dasm (-8.05% of base)
        -226 : 218776.dasm (-4.62% of base)
        -221 : 59165.dasm (-6.33% of base)
        -216 : 50985.dasm (-3.22% of base)
        -215 : 199132.dasm (-1.29% of base)
        -200 : 24935.dasm (-2.63% of base)
        -200 : 30414.dasm (-5.52% of base)
        -180 : 115652.dasm (-11.76% of base)
        -173 : 44186.dasm (-8.35% of base)
        -170 : 71144.dasm (-8.72% of base)
        -156 : 73449.dasm (-8.53% of base)
        -153 : 73655.dasm (-2.55% of base)
        -148 : 103908.dasm (-8.00% of base)
        -146 : 218815.dasm (-8.05% of base)
        -146 : 220637.dasm (-8.05% of base)
        -144 : 123683.dasm (-3.71% of base)
        -143 : 50658.dasm (-13.49% of base)
        -137 : 155948.dasm (-4.29% of base)

13905 total files with Code Size differences (11216 improved, 2689 regressed), 17020 unchanged.

Top method regressions (bytes):
         369 (50.20% of base) : 172785.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:UnionWith(System.Collections.Generic.IEnumerable`1[__Canon]):this
         238 ( 4.46% of base) : 141676.dasm - System.Xml.Xsl.Runtime.XmlCollation:Create(System.String,bool):System.Xml.Xsl.Runtime.XmlCollation
         203 (31.87% of base) : 172788.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:IntersectWith(System.Collections.Generic.IEnumerable`1[__Canon]):this
         194 (22.27% of base) : 18503.dasm - System.SpanHelpers:IndexOfAny(byref,System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],int):int
         188 ( 6.62% of base) : 30550.dasm - Microsoft.CodeAnalysis.CSharp.SymbolDisplayVisitor:AddTypeParameterConstraints(System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.ITypeSymbol, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]):this
         164 (14.05% of base) : 18509.dasm - System.SpanHelpers:IndexOfAny(byref,System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],int):int
         164 (14.30% of base) : 18526.dasm - System.SpanHelpers:LastIndexOfAny(byref,System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],int):int
         154 ( 1.83% of base) : 137685.dasm - System.Xml.Schema.SchemaCollectionPreprocessor:Preprocess(System.Xml.Schema.XmlSchema,System.String,int):this
         140 ( 2.49% of base) : 140673.dasm - System.Xml.Xsl.XsltOld.HtmlElementProps:CreatePropsTable():System.Collections.Hashtable
         122 ( 4.49% of base) : 16935.dasm - Internal.TypeSystem.Ecma.EcmaType:GetClassLayout():Internal.TypeSystem.ClassLayoutMetadata:this
         112 ( 0.45% of base) : 26572.dasm - Microsoft.CodeAnalysis.CSharp.CSharpCommandLineParser:Parse(System.Collections.Generic.IEnumerable`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],System.String,System.String,System.String):Microsoft.CodeAnalysis.CSharp.CSharpCommandLineArguments:this
         112 (12.99% of base) : 18520.dasm - System.SpanHelpers:LastIndexOfAny(byref,System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],int):int
          99 ( 3.09% of base) : 29499.dasm - Microsoft.CodeAnalysis.CSharp.AsyncExceptionHandlerRewriter:VisitTryStatement(Microsoft.CodeAnalysis.CSharp.BoundTryStatement):Microsoft.CodeAnalysis.CSharp.BoundNode:this
          98 ( 2.88% of base) : 114762.dasm - System.Data.Common.SqlMoneyStorage:Aggregate(System.Int32[],int):System.Object:this
          94 ( 3.04% of base) : 114692.dasm - System.Data.Common.SqlDoubleStorage:Aggregate(System.Int32[],int):System.Object:this
          93 ( 2.83% of base) : 114748.dasm - System.Data.Common.SqlInt64Storage:Aggregate(System.Int32[],int):System.Object:this
          90 ( 4.21% of base) : 43068.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.ConstraintsHelper:CheckConstraints(Microsoft.CodeAnalysis.CSharp.Symbol,Microsoft.CodeAnalysis.CSharp.ConversionsBase,Microsoft.CodeAnalysis.CSharp.Symbols.TypeMap,Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol,Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol,Microsoft.CodeAnalysis.Compilation,Microsoft.CodeAnalysis.ArrayBuilder`1[TypeParameterDiagnosticInfo],byref):bool
          90 (13.45% of base) : 116744.dasm - System.Drawing.Printing.PageSettings:get_PrintableArea():System.Drawing.RectangleF:this
          84 (12.52% of base) : 75007.dasm - DiagnosticRewriter:Rewrite(Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.CompilationUnitSyntax,Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.IfDirectiveTriviaSyntax, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.RegionDirectiveTriviaSyntax, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],bool,Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.ExternalSourceDirectiveTriviaSyntax,Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.Parser):Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.CompilationUnitSyntax
          82 ( 2.58% of base) : 188503.dasm - <ConstructResponseAsync>d__57:MoveNext():this

Top method improvements (bytes):
        -900 (-1.89% of base) : 85717.dasm - Microsoft.Diagnostics.Tracing.CtfTraceEventSource:InitEventMap():System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.Diagnostics.Tracing.ETWMapping, Microsoft.Diagnostics.Tracing.TraceEvent, Version=2.0.65.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]
        -327 (-2.77% of base) : 50965.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:BindFieldAndPropertyInitializers(Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol,System.Collections.Immutable.ImmutableArray`1[ImmutableArray`1],Microsoft.CodeAnalysis.VisualBasic.Symbols.SynthesizedInteractiveInitializerMethod,Microsoft.CodeAnalysis.DiagnosticBag):System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.VisualBasic.BoundInitializer, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]
        -258 (-8.05% of base) : 69447.dasm - Microsoft.CodeAnalysis.VisualBasic.OverloadResolution:OperatorInvocationOverloadResolution(Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.Binder,bool,bool,byref):OverloadResolutionResult
        -226 (-4.62% of base) : 218776.dasm - System.Security.Cryptography.Asn1.GeneralNameAsn:DecodeCore(byref,System.ReadOnlyMemory`1[Byte],byref)
        -221 (-6.33% of base) : 59165.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.Scanner:ScanDateLiteral(Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.SyntaxList`1[[Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.VisualBasicSyntaxNode, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]):Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.SyntaxToken:this
        -216 (-3.22% of base) : 50985.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:BindSymbolAccess(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.LookupResult,int,Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeArgumentListSyntax,int,Microsoft.CodeAnalysis.DiagnosticBag):Microsoft.CodeAnalysis.VisualBasic.BoundExpression:this
        -215 (-1.29% of base) : 199132.dasm - System.Management.ManagementClassGenerator:GenerateTypeConverterClass():System.CodeDom.CodeTypeDeclaration:this
        -200 (-2.63% of base) : 24935.dasm - Microsoft.CodeAnalysis.CSharp.Imports:FromSyntax(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode,Microsoft.CodeAnalysis.CSharp.InContainerBinder,Roslyn.Utilities.ConsList`1[[Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],bool):Microsoft.CodeAnalysis.CSharp.Imports
        -200 (-5.52% of base) : 30414.dasm - Microsoft.CodeAnalysis.CSharp.SyntaxFacts:GetContextualKeywordKind(System.String):ushort
        -180 (-11.76% of base) : 115652.dasm - System.Drawing.ImageFormatConverter:ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type):System.Object:this
        -173 (-8.35% of base) : 44186.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:HasInstanceData(Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax):bool
        -170 (-8.72% of base) : 71144.dasm - Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter:VisitToken(Microsoft.CodeAnalysis.SyntaxToken):Microsoft.CodeAnalysis.SyntaxToken:this
        -156 (-8.53% of base) : 73449.dasm - TypeBinder:BindTypeOrAliasSyntax(Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeSyntax,Microsoft.CodeAnalysis.VisualBasic.Binder,Microsoft.CodeAnalysis.DiagnosticBag,bool,bool,bool):Microsoft.CodeAnalysis.VisualBasic.Symbol
        -153 (-2.55% of base) : 73655.dasm - AnonymousDelegatePublicSymbol:.ctor(Microsoft.CodeAnalysis.VisualBasic.Symbols.AnonymousTypeManager,Microsoft.CodeAnalysis.VisualBasic.Symbols.AnonymousTypeDescriptor):this
        -148 (-8.00% of base) : 103908.dasm - <>c__DisplayClass0_0:<.ctor>b__1(Microsoft.Diagnostics.Tracing.TraceEvent):this
        -146 (-8.05% of base) : 218815.dasm - System.Security.Cryptography.Asn1.PssParamsAsn:Encode(System.Formats.Asn1.AsnWriter,System.Formats.Asn1.Asn1Tag):this
        -146 (-8.05% of base) : 220637.dasm - System.Security.Cryptography.Asn1.PssParamsAsn:Encode(System.Formats.Asn1.AsnWriter,System.Formats.Asn1.Asn1Tag):this
        -144 (-3.71% of base) : 123683.dasm - <ConnectAsync>d__96:MoveNext():this
        -143 (-13.49% of base) : 50658.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:BindRemoveNamespaceAttributesInvocation(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.BoundRValuePlaceholder,Microsoft.CodeAnalysis.VisualBasic.BoundRValuePlaceholder,byref,byref,Microsoft.CodeAnalysis.DiagnosticBag):Microsoft.CodeAnalysis.VisualBasic.BoundExpression:this
        -137 (-4.29% of base) : 155948.dasm - Microsoft.CSharp.RuntimeBinder.Errors.ErrorHandling:Error(int,Microsoft.CSharp.RuntimeBinder.Errors.ErrArg[]):Microsoft.CSharp.RuntimeBinder.RuntimeBinderException

Top method regressions (percentages):
          15 (187.50% of base) : 158144.dasm - Microsoft.Extensions.DependencyModel.EnvironmentWrapper:GetAppContextData(System.String):System.Object:this
           8 (66.67% of base) : 115301.dasm - System.Drawing.CharacterRange:GetHashCode():int:this
           8 (66.67% of base) : 188529.dasm - System.Drawing.Point:GetHashCode():int:this
           8 (66.67% of base) : 188661.dasm - System.Drawing.Size:GetHashCode():int:this
           8 (66.67% of base) : 225706.dasm - System.Text.RegularExpressions.Symbolic.SymbolicMatch:GetHashCode():int:this
           8 (61.54% of base) : 80879.dasm - Microsoft.CodeAnalysis.Text.TextLine:get_SpanIncludingLineBreak():Microsoft.CodeAnalysis.Text.TextSpan:this
         369 (50.20% of base) : 172785.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:UnionWith(System.Collections.Generic.IEnumerable`1[__Canon]):this
           7 (50.00% of base) : 217603.dasm - System.Security.Cryptography.CryptoPool:Return(System.ArraySegment`1[Byte])
           7 (50.00% of base) : 221720.dasm - System.Security.Cryptography.CryptoPool:Return(System.ArraySegment`1[Byte])
           7 (50.00% of base) : 218658.dasm - System.Security.Cryptography.CryptoPool:Return(System.ArraySegment`1[Byte])
           7 (50.00% of base) : 220175.dasm - System.Security.Cryptography.CryptoPool:Return(System.ArraySegment`1[Byte])
           7 (46.67% of base) : 115433.dasm - System.Drawing.Graphics:DrawImageUnscaled(System.Drawing.Image,System.Drawing.Rectangle):this
          10 (45.45% of base) : 209476.dasm - System.Reflection.Context.Projection.ProjectingManifestResourceInfo:get_ReferencedAssembly():System.Reflection.Assembly:this
           7 (43.75% of base) : 157440.dasm - Microsoft.Extensions.Configuration.ConfigurationSection:GetChildren():System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.Configuration.IConfigurationSection, Microsoft.Extensions.Configuration.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]:this
           7 (43.75% of base) : 3694.dasm - Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter:ConvVarToLinq(Microsoft.FSharp.Quotations.FSharpVar):System.Linq.Expressions.ParameterExpression
           7 (43.75% of base) : 117997.dasm - System.Linq.Expressions.ConstantCheck:AnalyzeTypeIs(System.Linq.Expressions.TypeBinaryExpression):int
           7 (43.75% of base) : 119708.dasm - System.Linq.Expressions.DynamicExpression:System.Linq.Expressions.IDynamicExpression.CreateCallSite():System.Object:this
           7 (43.75% of base) : 138654.dasm - System.Xml.Schema.XmlSchemaValidator:BuildElementName(System.Xml.XmlQualifiedName):System.String
          35 (43.21% of base) : 73369.dasm - MemberLookup:AnyShadows(Microsoft.CodeAnalysis.VisualBasic.LookupResult):bool
          38 (43.18% of base) : 53748.dasm - Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSignatureComparer:AreConstraintTypesSubset(Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]):bool

Top method improvements (percentages):
         -62 (-88.57% of base) : 209599.dasm - System.Reflection.Context.Projection.Projector:Project(long,System.Func`2[Int64,Int64]):long:this
         -58 (-87.88% of base) : 209596.dasm - System.Reflection.Context.Projection.Projector:Project(int,System.Func`2[Int32,Int32]):int:this
         -67 (-85.90% of base) : 209597.dasm - System.Reflection.Context.Projection.Projector:Project(double,System.Func`2[Double,Double]):double:this
         -60 (-84.51% of base) : 209594.dasm - System.Reflection.Context.Projection.Projector:Project(ubyte,System.Func`2[Byte,Byte]):ubyte:this
         -59 (-83.10% of base) : 209595.dasm - System.Reflection.Context.Projection.Projector:Project(short,System.Func`2[Int16,Int16]):short:this
         -20 (-80.00% of base) : 150141.dasm - System.Text.Json.Nodes.JsonArray:.ctor(System.Nullable`1[JsonNodeOptions]):this
         -22 (-70.97% of base) : 150365.dasm - System.Text.Json.Nodes.JsonValue`1[Byte][System.Byte]:.ctor(ubyte,System.Nullable`1[JsonNodeOptions]):this
         -22 (-70.97% of base) : 150369.dasm - System.Text.Json.Nodes.JsonValue`1[Int32][System.Int32]:.ctor(int,System.Nullable`1[JsonNodeOptions]):this
         -22 (-70.97% of base) : 150326.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Byte][System.Byte]:.ctor(ubyte,System.Nullable`1[JsonNodeOptions]):this
         -22 (-70.97% of base) : 150328.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Int32][System.Int32]:.ctor(int,System.Nullable`1[JsonNodeOptions]):this
         -22 (-68.75% of base) : 150367.dasm - System.Text.Json.Nodes.JsonValue`1[Int16][System.Int16]:.ctor(short,System.Nullable`1[JsonNodeOptions]):this
         -22 (-68.75% of base) : 150375.dasm - System.Text.Json.Nodes.JsonValue`1[Int64][System.Int64]:.ctor(long,System.Nullable`1[JsonNodeOptions]):this
         -22 (-68.75% of base) : 150327.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Int16][System.Int16]:.ctor(short,System.Nullable`1[JsonNodeOptions]):this
         -22 (-68.75% of base) : 150331.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Int64][System.Int64]:.ctor(long,System.Nullable`1[JsonNodeOptions]):this
          -9 (-64.29% of base) : 12863.dasm - Microsoft.FSharp.Core.Operators:Snd(System.Tuple`2[__Canon,Nullable`1]):System.Nullable`1[Int32]
          -9 (-64.29% of base) : 12864.dasm - Microsoft.FSharp.Core.Operators:Snd(System.Tuple`2[Byte,Nullable`1]):System.Nullable`1[Int32]
         -21 (-60.00% of base) : 150371.dasm - System.Text.Json.Nodes.JsonValue`1[Double][System.Double]:.ctor(double,System.Nullable`1[JsonNodeOptions]):this
         -21 (-60.00% of base) : 150329.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Double][System.Double]:.ctor(double,System.Nullable`1[JsonNodeOptions]):this
         -35 (-59.32% of base) : 9947.dasm - groupByRefType@438-3[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:Invoke(System.__Canon):StructBox`1[Nullable`1]:this
         -35 (-59.32% of base) : 9952.dasm - groupByRefType@438-3[Int32,Nullable`1][System.Int32,System.Nullable`1[System.Int32]]:Invoke(int):StructBox`1[Nullable`1]:this

13905 total methods with Code Size differences (11216 improved, 2689 regressed), 17020 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries_tests.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 114663564 (overridden on cmd)
Total bytes of diff: 114588769 (overridden on cmd)
Total bytes of delta: -74795 (-0.07 % of base)
    diff is an improvement.
    relative diff is a regression.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         547 : 154090.dasm (6.39% of base)
         535 : 154996.dasm (3.64% of base)
         464 : 126998.dasm (20.25% of base)
         426 : 205779.dasm (2.98% of base)
         297 : 190051.dasm (6.18% of base)
         297 : 67723.dasm (6.18% of base)
         286 : 190046.dasm (5.98% of base)
         286 : 67718.dasm (5.98% of base)
         284 : 154095.dasm (6.03% of base)
         275 : 154995.dasm (3.74% of base)
         268 : 70254.dasm (6.21% of base)
         246 : 205723.dasm (1.80% of base)
         245 : 159242.dasm (20.02% of base)
         240 : 51993.dasm (4.19% of base)
         240 : 51994.dasm (4.19% of base)
         230 : 188322.dasm (2.14% of base)
         229 : 153100.dasm (7.02% of base)
         223 : 204718.dasm (1.71% of base)
         219 : 282332.dasm (100.00% of base)
         219 : 204877.dasm (1.55% of base)

Top file improvements (bytes):
        -612 : 160187.dasm (-52.80% of base)
        -612 : 160188.dasm (-52.67% of base)
        -612 : 160189.dasm (-52.67% of base)
        -612 : 160190.dasm (-52.67% of base)
        -579 : 25023.dasm (-1.97% of base)
        -451 : 281941.dasm (-7.17% of base)
        -357 : 347313.dasm (-7.62% of base)
        -338 : 340325.dasm (-30.67% of base)
        -338 : 340327.dasm (-28.07% of base)
        -299 : 126348.dasm (-9.89% of base)
        -280 : 209068.dasm (-7.85% of base)
        -240 : 129253.dasm (-10.26% of base)
        -239 : 126272.dasm (-9.09% of base)
        -238 : 286019.dasm (-1.95% of base)
        -234 : 93118.dasm (-8.45% of base)
        -225 : 217620.dasm (-5.37% of base)
        -225 : 213467.dasm (-5.37% of base)
        -223 : 159202.dasm (-15.83% of base)
        -216 : 180363.dasm (-6.36% of base)
        -216 : 128350.dasm (-9.82% of base)

31384 total files with Code Size differences (18420 improved, 12964 regressed), 54114 unchanged.

Top method regressions (bytes):
         547 ( 6.39% of base) : 154090.dasm - System.Data.Tests.DataTableTest4:XmlTest10():this
         535 ( 3.64% of base) : 154996.dasm - System.Data.Tests.Common.DbConnectionStringBuilderTest:AppendKeyValuePair2_UseOdbcRules_True():this
         464 (20.25% of base) : 126998.dasm - Microsoft.CodeAnalysis.CSharp.Classification.Worker:ClassifyDirectiveTrivia(Microsoft.CodeAnalysis.CSharp.Syntax.DirectiveTriviaSyntax,bool):this
         426 ( 2.98% of base) : 205779.dasm - <>c__DisplayClass29_0:<Read_FullItem_ReturnsExpected>b__0(System.ServiceModel.Syndication.SyndicationFeed):this
         297 ( 6.18% of base) : 190051.dasm - System.Tests.StringTests:WhiteSpaceInMiddleTrim_Memory()
         297 ( 6.18% of base) : 67723.dasm - System.Tests.StringTests:WhiteSpaceInMiddleTrim_Memory()
         286 ( 5.98% of base) : 190046.dasm - System.Tests.StringTests:NoWhiteSpaceTrim_Memory()
         286 ( 5.98% of base) : 67718.dasm - System.Tests.StringTests:NoWhiteSpaceTrim_Memory()
         284 ( 6.03% of base) : 154095.dasm - System.Data.Tests.DataTableTest4:XmlTest15():this
         275 ( 3.74% of base) : 154995.dasm - System.Data.Tests.Common.DbConnectionStringBuilderTest:AppendKeyValuePair2_UseOdbcRules_False():this
         268 ( 6.21% of base) : 70254.dasm - System.Tests.TimeZoneInfoTests:GetAmbiguousTimeOffsets_Invalid()
         246 ( 1.80% of base) : 205723.dasm - <>c__DisplayClass20_0:<ReadFrom_FullItem_ReturnsExpected>b__0(System.ServiceModel.Syndication.SyndicationItem):this
         245 (20.02% of base) : 159242.dasm - System.Drawing.Drawing2D.Tests.MatrixTests:Ctor_Elements(float,float,float,float,float,float,bool,bool):this
         240 ( 4.19% of base) : 51993.dasm - System.Linq.Expressions.Tests.Expression_Tests:TestUserDefinedComparisonOperators()
         240 ( 4.19% of base) : 51994.dasm - System.Linq.Expressions.Tests.Expression_Tests:TestUserDefinedComparisonOperators()
         230 ( 2.14% of base) : 188322.dasm - System.Reflection.Tests.PropertyTests:TestProperties_GetterSetter()
         229 ( 7.02% of base) : 153100.dasm - System.Data.Tests.DataColumnCollectionTest2:Add():this
         223 ( 1.71% of base) : 204718.dasm - System.ServiceModel.Syndication.Tests.Rss20ItemFormatterTests:ReadFrom_TryParseReturnsTrue_ReturnsExpected(bool,bool):this
         219 (100.00% of base) : 282332.dasm - <>c:<TestAddingSamplerTagsFromMultipleListeners>b__21_3(byref):int:this
         219 ( 1.55% of base) : 204877.dasm - System.ServiceModel.Syndication.Tests.Atom10FeedFormatterTests:Read_TryParseTrue_ReturnsExpected(bool,bool):this

Top method improvements (bytes):
        -612 (-52.80% of base) : 160187.dasm - System.Drawing.Tests.TextureBrushTests:WrapMode_Tile_ReturnsExpected():this
        -612 (-52.67% of base) : 160188.dasm - System.Drawing.Tests.TextureBrushTests:WrapMode_TileFlipX_ReturnsExpected():this
        -612 (-52.67% of base) : 160190.dasm - System.Drawing.Tests.TextureBrushTests:WrapMode_TileFlipXY_ReturnsExpected():this
        -612 (-52.67% of base) : 160189.dasm - System.Drawing.Tests.TextureBrushTests:WrapMode_TileFlipY_ReturnsExpected():this
        -579 (-1.97% of base) : 25023.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.overloadResolution.Methods.Oneclass2methods.literals01.literals01.A:MainMethod():int
        -451 (-7.17% of base) : 281941.dasm - System.Diagnostics.Tests.ActivityTests:ActivityTraceFlagsTests():this
        -357 (-7.62% of base) : 347313.dasm - System.Xml.Tests.ToTypeTests:TestInvalid(System.String[],System.String,System.String[]):int:this
        -338 (-30.67% of base) : 340325.dasm - System.Threading.Tasks.Tests.ValueTaskTests:Generic_OperatorEquals():this
        -338 (-28.07% of base) : 340327.dasm - System.Threading.Tasks.Tests.ValueTaskTests:Generic_OperatorNotEquals():this
        -299 (-9.89% of base) : 126348.dasm - Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTokenExtensions:IsBeginningOfGlobalStatementContext(Microsoft.CodeAnalysis.SyntaxToken):bool
        -280 (-7.85% of base) : 209068.dasm - System.Threading.Tasks.Tests.TaskAwaiterTests:AwaiterAndAwaitableEquality()
        -240 (-10.26% of base) : 129253.dasm - Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery.SyntaxTreeExtensions:IsQueryIntoClauseContext(Microsoft.CodeAnalysis.SyntaxTree,int,Microsoft.CodeAnalysis.SyntaxToken,System.Threading.CancellationToken):bool
        -239 (-9.09% of base) : 126272.dasm - Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTreeExtensions:IsAtEndOfPattern(Microsoft.CodeAnalysis.SyntaxTree,Microsoft.CodeAnalysis.SyntaxToken,int):bool
        -238 (-1.95% of base) : 286019.dasm - System.Formats.Asn1.Tests.Writer.ComprehensiveWriteTest:WriteMicrosoftDotComCert()
        -234 (-8.45% of base) : 93118.dasm - System.Text.Json.Nodes.Tests.OperatorTests:ExplicitOperators_FromNullableValues()
        -225 (-5.37% of base) : 217620.dasm - Microsoft.SqlServer.Server.ValueUtilsSmi:GetSqlValue(Microsoft.SqlServer.Server.SmiEventSink_Default,Microsoft.SqlServer.Server.ITypedGettersV3,int,Microsoft.SqlServer.Server.SmiMetaData):System.Object
        -225 (-5.37% of base) : 213467.dasm - Microsoft.SqlServer.Server.ValueUtilsSmi:GetSqlValue(Microsoft.SqlServer.Server.SmiEventSink_Default,Microsoft.SqlServer.Server.ITypedGettersV3,int,Microsoft.SqlServer.Server.SmiMetaData):System.Object
        -223 (-15.83% of base) : 159202.dasm - System.Drawing.Drawing2D.Tests.LinearGradientBrushTests:InterpolationColors_SetWithExistingInterpolationColors_OverwritesInterpolationColors():this
        -216 (-9.82% of base) : 128350.dasm - Microsoft.CodeAnalysis.VisualBasic.Classification.ClassificationHelpers:ClassifyIdentifierSyntax(Microsoft.CodeAnalysis.SyntaxToken):System.String
        -216 (-6.36% of base) : 180363.dasm - System.Net.Http.Tests.HttpRequestHeadersTest:AddHeaders_SpecialHeaderValuesOnDestinationNotOnSource_NotCopied():this

Top method regressions (percentages):
          15 (1,500.00% of base) : 326577.dasm - <>c:<AppendPrivatePath>b__37_0():this
          15 (1,500.00% of base) : 326578.dasm - <>c:<ClearPrivatePath>b__38_0():this
          15 (1,500.00% of base) : 326529.dasm - <>c:<ClearShadowCopyPath>b__39_0():this
          15 (1,500.00% of base) : 326530.dasm - <>c:<SetCachePath>b__40_0():this
          15 (1,500.00% of base) : 326531.dasm - <>c:<SetShadowCopyFiles>b__41_0():this
          15 (1,500.00% of base) : 326532.dasm - <>c:<SetShadowCopyPath>b__42_0():this
          15 (1,500.00% of base) : 325555.dasm - System.Tests.AppDomainTests:DynamicDirectory_Null():this
          15 (1,500.00% of base) : 325548.dasm - System.Tests.AppDomainTests:RelativeSearchPath_Is_Null():this
          51 (463.64% of base) : 32195.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass001.genericbaseclass001.Test:MainMethod(System.String[]):int
          34 (309.09% of base) : 32267.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.backwardscompatible.dynamictypedeclared021.dynamictypedeclared021.App:MainMethod(System.String[]):int
          34 (309.09% of base) : 32171.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass003.genericbaseclass003.NS.Test:MainMethod(System.String[]):int
          34 (309.09% of base) : 32164.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass004.genericbaseclass004.NS.Test:MainMethod(System.String[]):int
          34 (309.09% of base) : 32157.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass005.genericbaseclass005.NS.Test:MainMethod(System.String[]):int
          17 (188.89% of base) : 151308.dasm - System.ComponentModel.Design.Serialization.Tests.DesignerLoaderTests:Flush_Invoke_Nop():this
          17 (188.89% of base) : 150598.dasm - System.ComponentModel.Tests.LicenseContextTests:GetSavedLicenseKey_Invoke_ReturnsNull():this
          17 (188.89% of base) : 150599.dasm - System.ComponentModel.Tests.LicenseContextTests:GetService_Invoke_ReturnsNull():this
          17 (188.89% of base) : 150600.dasm - System.ComponentModel.Tests.LicenseContextTests:SetSavedLicenseKey_Invoke_Nop():this
          17 (188.89% of base) : 50178.dasm - System.Linq.Expressions.Tests.ExpressionTests:DefaultReducesToSame():this
          17 (188.89% of base) : 53252.dasm - System.Linq.Expressions.Tests.VisitorTests:VisitNullDefaultsToReturnNull():this
          17 (188.89% of base) : 196221.dasm - System.Runtime.Serialization.Xml.Tests.XmlDictionaryReaderTests:Close_DerivedReader_Success()

Top method improvements (percentages):
        -129 (-91.49% of base) : 327199.dasm - System.Runtime.InteropServices.Tests.CULongTests:Ctor_NUInt_LargeValue():this
        -124 (-91.18% of base) : 327211.dasm - System.Runtime.InteropServices.Tests.CLongTests:Ctor_NInt_LargeValue():this
         -30 (-90.91% of base) : 23628.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.unaryOperators.is002.is002.Test:MainMethod(System.String[]):int
         -30 (-90.91% of base) : 23626.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.unaryOperators.is003.is003.Test:MainMethod(System.String[]):int
          -8 (-88.89% of base) : 19856.dasm - System.Collections.Tests.HashSet_Generic_Tests`1[Byte][System.Byte]:CanBeCastedToISet():this
          -8 (-88.89% of base) : 147669.dasm - System.ComponentModel.Composition.ImportingConstructorAttributeTests:Constructor_ShouldNotThrow():this
          -8 (-88.89% of base) : 147675.dasm - System.ComponentModel.Composition.MetadataAttributeAttributeTests:Constructor_ShouldNotThrow():this
          -8 (-88.89% of base) : 283907.dasm - System.Diagnostics.SymbolStore.Tests.SymDocumentTypeTests:Ctor_Default():this
          -8 (-88.89% of base) : 283909.dasm - System.Diagnostics.SymbolStore.Tests.SymLanguageTypeTests:Ctor_Default():this
          -8 (-88.89% of base) : 283912.dasm - System.Diagnostics.SymbolStore.Tests.SymLanguageVendorTests:Ctor_Default():this
          -8 (-88.89% of base) : 335116.dasm - System.Text.Tests.DecoderCtor:PosTest1():this
          -8 (-88.89% of base) : 335192.dasm - System.Text.Tests.EncoderCtor:PosTest1():this
          -8 (-88.89% of base) : 352770.dasm - XmlSerializerTests:XmlSerializationGeneratedCodeTest()
         -46 (-88.46% of base) : 111729.dasm - genDictionary@1026-1[Double][System.Double]:Invoke(double):bool:this
         -46 (-88.46% of base) : 111730.dasm - genDictionary@1026-1[Vector`1][System.Numerics.Vector`1[System.Single]]:Invoke(System.Numerics.Vector`1[Single]):bool:this
         -35 (-85.37% of base) : 111731.dasm - genDictionary@1026-1[Int64][System.Int64]:Invoke(long):bool:this
         -34 (-85.00% of base) : 111726.dasm - genDictionary@1026-1[Byte][System.Byte]:Invoke(ubyte):bool:this
         -34 (-85.00% of base) : 111727.dasm - genDictionary@1026-1[Int16][System.Int16]:Invoke(short):bool:this
         -33 (-84.62% of base) : 111728.dasm - genDictionary@1026-1[Int32][System.Int32]:Invoke(int):bool:this
         -20 (-80.00% of base) : 231336.dasm - FluentAssertions.Primitives.BooleanAssertions:.ctor(System.Nullable`1[Boolean]):this

31384 total methods with Code Size differences (18420 improved, 12964 regressed), 54114 unchanged.

```

</details>

--------------------------------------------------------------------------------

**Comment by AndyAyersMS** [comment]
As noted earlier, the big regressions (eg `System.Reflection.MethodBase:CheckArguments` in benchmarks) are cases where loop cloning now kicks in.

**Comment by EgorBo** [comment]
From my impressions some regressions are just missing oportunites for CSE which was supposed to "un-substitute" back where needed. Example:
```csharp
public class Strings
{
    public string s1 { get; }
    public string s2 { get; }
    public string s3 { get; }
}

public class Program
{
    public string Test(Strings size)
        => string.Concat(size.s1, size.s2, size.s3);
}
```
```diff
G_M19485_IG02:
        mov      rcx, gword ptr [rdx+8]
-       mov      rax, gword ptr [rdx+16]
-       mov      r8, gword ptr [rdx+24]
-       mov      rdx, rax
+       mov      gword ptr [rsp+10H], rdx
+       mov      rdx, gword ptr [rdx+16]
+       mov      r8, gword ptr [rsp+10H]
+       mov      r8, gword ptr [r8+24]
G_M19485_IG03:
        jmp      System.String:Concat(System.String,System.String,System.String):System.String
-; Total bytes of code: 20
+; Total bytes of code: 27
```

**Comment by AndyAyersMS** [comment]
> some regressions are just missing opportunities for CSE

Or (in this case) poor modelling of ABI constraints, LSRA preferencing, or poor choices for or arg evaluation order... @jakobbotsch was noting our current arg order sorting seems to be unhelpful.

**Comment by AndyAyersMS** [comment]
Might need to avoid forward sub of an implicit byref's promoted fields....

**Comment by jakobbotsch** [comment]
> JIT/Directed/debugging/debuginfo/tester is failing everywhere as we're evidently removing statements with debug info. Wonder if we should be merging debug info somehow.

The debug info tests assume that mappings will be placed on the statements containing calls. We should probably think about what the best way forward is -- perhaps prefer using the earliest offset? If we determine current behavior is ok the tests can be changed to have multiple uses to turn off the forward sub.

**Comment by EgorBo** [comment]
I am not sure the NativeAOT failure is related, well it is related but during reducing a repro I came up with one that fails even on Main jit (if I did everything correctly):
```csharp
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Text;

public class Test
{
    public static void Main()
    {
        try
        {
            throw new Exception();
        }
        catch when (FilterWithStackTrace())
        {
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static bool FilterWithStackTrace()
    {
        Consume(new StackTrace(0, true).ToString());
        return true;
    }
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Consume(string s)
    {
    }
}
```

**Comment by EgorBo** [comment]
Or actually I did something wrong, let me check...

File: src/coreclr/jit/forwardsub.cpp [hunk 2]
```diff
@@ -0,0 +1,549 @@
...
+
+#if defined(DEBUG)
+    enabled = JitConfig.JitNoForwardSub() == 0;
+#endif
+
+    if (enabled)
+    {
+        for (BasicBlock* const block : Blocks())
+        {
+            JITDUMP("\n\n===> " FMT_BB "\n", block->bbNum);
```
Comment (EgorBo) [inline src/coreclr/jit/forwardsub.cpp:31]: Is it worth skipping cold blocks here?

**Comment by EgorBo** [comment]
NativeAOT was a taught one since it only reproduced on app start and not during AOT compilation...
I managed to find the exact method ForwardSub for leads to a crash on NativeAOT test, here is the assembly diff for that file: https://www.diffchecker.com/JPgVi4N7 (forward sub result is on the right).

NgenDump diff: https://www.diffchecker.com/mbzS9LLk

Is this a correct substitution:
image

@AndyAyersMS

File: src/coreclr/jit/forwardsub.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/forwardsub.cpp:31]: Seems like this is the kind of thing that is not hot/cold sensitive?

**Comment by EgorBo** [comment]
@AndyAyersMS yeah, it helps

**Comment by AndyAyersMS** [comment]
Ok, looks like it kicks in in around 600 of the 73,000 or so diffs this causes. Doesn't seem too conservative.

I'll push it as a fix. Looks like I need to merge up too.

**Comment by AndyAyersMS** [comment]
> We should probably think about what the best way forward is 

For now, I've just updated the expected output of the test -- but yes we should think about what we really want here.

**Comment by AndyAyersMS** [comment]
Still have the arm32 failures in Vector128. Seem to happen even if fwd sub is disabled, so possibly one of the small number of other changes...?

**Comment by AndyAyersMS** [comment]
Bug was in prejitted code, we have a struct reinterpretation in an assignment that we can't fwd sub across:
```
===> BB01
    [000007]:  [000008] is only use of [000005] (V02)  [marking V00 as multi-reg-ret] -- fwd subbing [000004]; new next stmt is
STMT00002 ( ??? ... ??? )
               [000009] -------------             *  RETURN    struct
               [000004] m------N-----             \--*  LCL_VAR   struct<System.Runtime.Intrinsics.Vector128`1[Single], 16> V00 arg0         

removing useless STMT00001 ( 0x000[E-] ... ??? )
               [000007] -A--G--------             *  ASG       struct (copy)
               [000005] D------N-----             +--*  LCL_VAR   struct<System.Numerics.Vector4, 16> V02 tmp1         
               [000004] m------N-----             \--*  LCL_VAR   struct<System.Runtime.Intrinsics.Vector128`1[Single], 16> V00 arg0         
 from BB01
```

**Comment by AndyAyersMS** [comment]
Looks like 3 or more failures to work through from outerloop.

**Comment by AndyAyersMS** [comment]
Also seems like SPMI runs are timing out... took a bit of digging, but see
```
Console log: 'win-x64' from job e50a2941-1c2f-45a8-af71-4fb3e1530b32 workitem bb7a3031-9bf7-47b1-bb93-0aaea9521944 (windows.10.amd64.open.rt) executed on machine a009N8P

C:\h\w\AA490931\w\B1FC0968\e>C:\python3.9.1\python.exe C:\h\w\AA490931\p\superpmi_asmdiffs.py -base_jit_directory C:\h\w\AA490931\p\base -diff_jit_directory C:\h\w\AA490931\p\diff -log_directory C:\h\w\AA490931\w\B1FC0968\uploads -arch x64 -platform windows 
Adding C:\h\w\AA490931\p\jit-analyze to PATH
Adding C:\h\w\AA490931\p\git\cmd to PATH
Running superpmi.py download to get MCH files
Running: C:\python3.9.1\python.exe C:\h\w\AA490931\p\superpmi.py download --no_progress -core_root C:\h\w\AA490931\p -target_os windows -target_arch x64 -spmi_location C:\h\w\AA490931\p\artifacts\spmi -log_level debug -log_file C:\h\w\AA490931\w\B1FC0968\uploads\superpmi_download_windows_x64.log
================ Logging to C:\h\w\AA490931\w\B1FC0968\uploads\superpmi_download_windows_x64.log

Using mcs.exe from Core_Root: C:\h\w\AA490931\p\mcs.exe

Using JIT/EE Version from mcs: 323185e9-208a-4b35-a413-23f9aac2d5f7

SuperPMI download

------------------------------------------------------------

Start time: 18:47:35

Downloading:

  https://clrjit2.blob.core.windows.net/superpmi/collections/323185e9-208a-4b35-a413-23f9aac2d5f7/windows/x64/aspnet.run.windows.x64.checked.mch.mct.zip

  https://clrjit2.blob.core.windows.net/superpmi/collections/323185e9-208a-4b35-a413-23f9aac2d5f7/windows/x64/aspnet.run.windows.x64.checked.mch.zip
...
Finish time: 18:51:54

Elapsed time: 0:04:18.604483

['win-x64' END OF WORK ITEM LOG: Command timed out, and was killed]
```
Digging further there were ~8000 files with diffs from asp.net
```
Invoking: C:\h\w\AA490931\p\jit-analyze\jit-analyze.exe --md C:\h\w\AA490931\p\artifacts\spmi\asm.aspnet.run.windows.x64.checked\summary.md -r --base C:\h\w\AA490931\p\artifacts\spmi\asm.aspnet.run.windows.x64.checked\base --diff C:\h\w\AA490931\p\artifacts\spmi\asm.aspnet.run.windows.x64.checked\diff --retainOnlyTopFiles --override-total-base-metric 20165654 --override-total-diff-metric 20134922
Found 8182 files with textual diffs.
Deleted 16326 .dasm files.

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 20165654 (overridden on cmd)
Total bytes of diff: 20134922 (overridden on cmd)
Total bytes of delta: -30732 (-0.15 % of base)
    diff is an improvement.
    relative diff is an improvement.


Top file regressions (bytes):
         359 : 30410.dasm (67.99 % of base)
         195 : 65528.dasm (1.15 % of base)
          98 : 48855.dasm (1.25 % of base)
          65 : 63405.dasm (7.78 % of base)
          60 : 42792.dasm (7.21 % of base)
          53 : 26091.dasm (2.81 % of base)
          47 : 62883.dasm (5.08 % of base)
          44 : 12660.dasm (15.38 % of base)
          39 : 49296.dasm (4.67 % of base)
          35 : 16023.dasm (5.20 % of base)
          32 : 50013.dasm (1.30 % of base)
          32 : 59336.dasm (1.29 % of base)
          31 : 18225.dasm (4.53 % of base)
          30 : 47487.dasm (0.66 % of base)
          30 : 19367.dasm (4.42 % of base)
          29 : 43102.dasm (3.08 % of base)
          28 : 66316.dasm (2.74 % of base)
          28 : 46505.dasm (2.74 % of base)
          26 : 58530.dasm (0.52 % of base)
          26 : 58537.dasm (0.26 % of base)

Top file improvements (bytes):
        -110 : 13387.dasm (-1.57 % of base)
        -110 : 12545.dasm (-1.57 % of base)
         -91 : 67916.dasm (-2.99 % of base)
         -87 : 58039.dasm (-2.88 % of base)
         -87 : 59988.dasm (-2.90 % of base)
         -84 : 12998.dasm (-18.58 % of base)
         -81 : 61349.dasm (-4.39 % of base)
         -81 : 41974.dasm (-4.40 % of base)
         -81 : 58580.dasm (-4.39 % of base)
         -80 : 58292.dasm (-9.21 % of base)
         -79 : 40846.dasm (-2.90 % of base)
         -75 : 43214.dasm (-2.80 % of base)
         -75 : 52514.dasm (-12.21 % of base)
         -74 : 11923.dasm (-2.48 % of base)
         -73 : 19607.dasm (-1.41 % of base)
         -73 : 18680.dasm (-1.42 % of base)
         -72 : 67398.dasm (-1.27 % of base)
         -72 : 49071.dasm (-1.27 % of base)
         -71 : 25742.dasm (-1.49 % of base)
         -70 : 56074.dasm (-4.23 % of base)

5521 total files with Code Size differences (4829 improved, 692 regressed), 2682 unchanged.

Top method regressions (bytes):
         359 (67.99 % of base) : 30410.dasm - MethodBase:CheckArguments(byref,ReadOnlySpan`1,Binder,int,CultureInfo,ref):Span`1:this
         195 (1.15 % of base) : 65528.dasm - NpgsqlTypeMappingSource:.ctor(TypeMappingSourceDependencies,RelationalTypeMappingSourceDependencies,ISqlGenerationHelper,INpgsqlOptions):this
          98 (1.25 % of base) : 48855.dasm - RegexFindOptimizations:TryFindNextStartingPosition(ReadOnlySpan`1,byref,int,int,int):bool:this
          65 (7.78 % of base) : 63405.dasm - TextEncoder:EncodeToNewString(ReadOnlySpan`1,int):String:this
          60 (7.21 % of base) : 42792.dasm - TextEncoder:EncodeToNewString(ReadOnlySpan`1,int):String:this
          53 (2.81 % of base) : 26091.dasm - HttpTransformer:TransformRequestAsync(HttpContext,HttpRequestMessage,String):ValueTask:this
          47 (5.08 % of base) : 62883.dasm - CancellationTokenSource:Register(Delegate,Object,SynchronizationContext,ExecutionContext):CancellationTokenRegistration:this
          44 (15.38 % of base) : 12660.dasm - String:IndexOfAny(ref):int:this
          39 (4.67 % of base) : 49296.dasm - ViewLocationCacheKey:GetHashCode():int:this
          35 (5.20 % of base) : 16023.dasm - ResourceManager:GetFirstResourceSet(CultureInfo):ResourceSet:this
          32 (1.30 % of base) : 50013.dasm - HttpParser`1:ParseHeaders(Http1ParsingHandler,byref):bool:this
          32 (1.29 % of base) : 59336.dasm - HttpParser`1:ParseHeaders(Http1ParsingHandler,byref):bool:this
          31 (4.53 % of base) : 18225.dasm - String:IndexOfAny(ref):int:this
          30 (0.66 % of base) : 47487.dasm - IncludeExpandingExpressionVisitor:ExpandIncludesHelper(Expression,EntityReference,INavigationBase):Expression:this
          30 (4.42 % of base) : 19367.dasm - String:IndexOfAny(ref):int:this
          29 (3.08 % of base) : 43102.dasm - ViewLocationCacheKey:GetHashCode():int:this
          28 (2.74 % of base) : 66316.dasm - RelationalPropertyExtensions:GetColumnName(IReadOnlyProperty,byref):String
          28 (2.74 % of base) : 46505.dasm - RelationalPropertyExtensions:GetColumnName(IReadOnlyProperty,byref):String
          26 (0.52 % of base) : 58530.dasm - NpgsqlMemberTranslatorProvider:.ctor(RelationalMemberTranslatorProviderDependencies,IModel,IRelationalTypeMappingSource,INpgsqlOptions):this
          26 (0.26 % of base) : 58537.dasm - NpgsqlMethodCallTranslatorProvider:.ctor(RelationalMethodCallTranslatorProviderDependencies,IModel,INpgsqlOptions):this

Top method improvements (bytes):
        -110 (-1.57 % of base) : 13387.dasm - HttpRequestHeaders:Append(ReadOnlySpan`1,ReadOnlySpan`1,bool):this
        -110 (-1.57 % of base) : 12545.dasm - HttpRequestHeaders:Append(ReadOnlySpan`1,ReadOnlySpan`1,bool):this
         -91 (-2.99 % of base) : 67916.dasm - <QueryAsync>d__33`1:MoveNext():this
         -87 (-2.88 % of base) : 58039.dasm - <QueryAsync>d__33`1:MoveNext():this
         -87 (-2.90 % of base) : 59988.dasm - <QueryAsync>d__33`1:MoveNext():this
         -84 (-18.58 % of base) : 12998.dasm - AdjustmentRule:get_HasDaylightSaving():bool:this
         -81 (-4.39 % of base) : 61349.dasm - <InitializeReaderAsync>d__19:MoveNext():this
         -81 (-4.40 % of base) : 41974.dasm - <InitializeReaderAsync>d__19:MoveNext():this
         -81 (-4.39 % of base) : 58580.dasm - <InitializeReaderAsync>d__19:MoveNext():this
         -80 (-9.21 % of base) : 58292.dasm - ConcurrentDictionary`2:TryGetValue(SslCredKey,byref):bool:this
         -79 (-2.90 % of base) : 40846.dasm - SafeDeleteContext:AcceptSecurityContext(byref,byref,int,int,InputSecurityBuffers,byref,byref):int
         -75 (-2.80 % of base) : 43214.dasm - <RenderPageCoreAsync>d__20:MoveNext():this
         -75 (-12.21 % of base) : 52514.dasm - ConcurrentDictionary`2:TryGetValueInternal(ModelMetadataIdentity,int,byref):bool:this
         -74 (-2.48 % of base) : 11923.dasm - ThreadPoolWorkQueue:Dispatch():bool
         -73 (-1.41 % of base) : 19607.dasm - TimeZoneInfo:GetIsDaylightSavingsFromUtc(DateTime,int,TimeSpan,AdjustmentRule,Nullable`1,byref,TimeZoneInfo):bool
         -73 (-1.42 % of base) : 18680.dasm - TimeZoneInfo:GetIsDaylightSavingsFromUtc(DateTime,int,TimeSpan,AdjustmentRule,Nullable`1,byref,TimeZoneInfo):bool
         -72 (-1.27 % of base) : 67398.dasm - <ExecuteReaderAsync>d__19:MoveNext():this
         -72 (-1.27 % of base) : 49071.dasm - <ExecuteReaderAsync>d__19:MoveNext():this
         -71 (-1.49 % of base) : 25742.dasm - <WriteHeadersAsync>d__56:MoveNext():this
         -70 (-0.45 % of base) : 29489.dasm - <SendAsyncCore>d__60:MoveNext():this

Top method regressions (percentages):
         359 (67.99 % of base) : 30410.dasm - MethodBase:CheckArguments(byref,ReadOnlySpan`1,Binder,int,CultureInfo,ref):Span`1:this
           7 (24.14 % of base) : 65818.dasm - OnEntityTypeAddedNode:Run(ConventionDispatcher):this
           7 (24.14 % of base) : 66161.dasm - OnKeyAddedNode:Run(ConventionDispatcher):this
           7 (24.14 % of base) : 66090.dasm - OnPropertyAddedNode:Run(ConventionDispatcher):this
           7 (24.14 % of base) : 66229.dasm - OnPropertyNullableChangedNode:Run(ConventionDispatcher):this
           7 (24.14 % of base) : 22944.dasm - String:GetHashCode():int:this
          11 (23.40 % of base) : 56261.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40 % of base) : 60129.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40 % of base) : 63163.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40 % of base) : 39500.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40 % of base) : 49691.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40 % of base) : 64366.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40 % of base) : 30383.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
           7 (18.92 % of base) : 40816.dasm - IdnMapping:get_NlsFlags():int:this
           7 (18.92 % of base) : 49522.dasm - IdnMapping:get_NlsFlags():int:this
          10 (17.54 % of base) : 18254.dasm - ILStubClass:IL_STUB_PInvoke(int,long):int
          44 (15.38 % of base) : 12660.dasm - String:IndexOfAny(ref):int:this
          17 (14.41 % of base) : 54052.dasm - ControllerFactoryProvider:GetPropertiesToActivate(ControllerActionDescriptor):ref:this
          14 (13.46 % of base) : 18879.dasm - AwaitableSocketAsyncEventArgs:Release():this
          14 (13.46 % of base) : 5456.dasm - AwaitableSocketAsyncEventArgs:Release():this

Top method improvements (percentages):
          -3 (-37.50 % of base) : 13263.dasm - HeartbeatManager:get_UtcNowTicks():long:this
         -32 (-31.37 % of base) : 40333.dasm - IEnumerableCallSite:.ctor(ResultCache,Type,ref):this
         -51 (-31.10 % of base) : 41336.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
         -51 (-31.10 % of base) : 58436.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
         -51 (-31.10 % of base) : 61114.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
          -3 (-30.00 % of base) : 5308.dasm - Socket:get_SafeHandle():SafeSocketHandle:this
         -47 (-29.38 % of base) : 56752.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
          -8 (-27.59 % of base) : 40400.dasm - ResultCache:.ctor(int,ServiceCacheKey):this
          -3 (-27.27 % of base) : 24871.dasm - ProxyConfigManager:GetChangeToken():IChangeToken:this
          -8 (-21.62 % of base) : 5608.dasm - Complex:Abs():double:this
         -28 (-20.59 % of base) : 23415.dasm - CancellationTokenSource:TryReset():bool:this
         -28 (-20.59 % of base) : 29602.dasm - CancellationTokenSource:TryReset():bool:this
         -25 (-18.80 % of base) : 15914.dasm - CancellationTokenSource:TryReset():bool:this
         -25 (-18.80 % of base) : 13131.dasm - CancellationTokenSource:TryReset():bool:this
         -84 (-18.58 % of base) : 12998.dasm - AdjustmentRule:get_HasDaylightSaving():bool:this
         -31 (-17.32 % of base) : 66804.dasm - NpgsqlDecimalTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-17.32 % of base) : 66756.dasm - NpgsqlDoubleTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-17.32 % of base) : 66811.dasm - NpgsqlFloatTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40 % of base) : 66807.dasm - NpgsqlCidrTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40 % of base) : 66806.dasm - NpgsqlInetTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this

5521 total methods with Code Size differences (4829 improved, 692 regressed), 2682 unchanged.
```
anyways wondering if we can up the timeout here easily? @BruceForstall

**Comment by AndyAyersMS** [comment]
Working on c2g issues:
* need some kind of size limit on the tree we can substitute
* some patterns lower/morph can't handle
* maybe more

**Comment by AndyAyersMS** [comment]
Going to run outerloop again.

There are some known outerloop failures (https://github.com/dotnet/runtime/issues/64172) but other than that we should be good.

**Comment by BruceForstall** [comment]
So you're seeing failures / timeouts in the superpmi-asmdiffs job, e.g., https://dev.azure.com/dnceng/public/_build/results?buildId=1569227&view=results

> wondering if we can up the timeout here easily? @BruceForstall

The overall job is set to a 2 hour [timeout](https://github.com/dotnet/runtime/blob/070b7d80114354ba9ef5dfb8bd175ca832edb638/eng/pipelines/coreclr/templates/run-superpmi-asmdiffs-job.yml#L14) and each Helix work item to a 1 hour [timeout](https://github.com/dotnet/runtime/blob/070b7d80114354ba9ef5dfb8bd175ca832edb638/src/coreclr/scripts/superpmi-asmdiffs.proj#L34) (Is [this](https://github.com/dotnet/runtime/blob/070b7d80114354ba9ef5dfb8bd175ca832edb638/eng/pipelines/coreclr/templates/run-superpmi-asmdiffs-job.yml#L88) ignored?). We can certainly up these, but we do want some kind of timeout.

What is taking all the time? Presumably it's the generating of the .dasm files when there are a large number of asm diffs. Options:
1. increase the timeout, but keep it somewhat reasonable
2. use the superpmi.py option `-error_limit` to prevent "too many" asm diffs from overwhelming the system
3. figure out how to make the JIT faster generating .dasm files; can we turn off some (expensive) DEBUG checks for just this use?
4. Implement https://github.com/dotnet/runtime/issues/52877 to allow the JIT to generate jit-analyze metrics summary without actually generating .dasm files.

**Comment by AndyAyersMS** [comment]
> Presumably it's the generating of the .dasm files when there are a large number of asm diffs. 

I think so, yes. There are ~400,000 dasm files created when I do this locally.

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib think this is ready for some review.

I don't plan to remove any of the workarounds/limitations just yet --the idea is to get this first chunk in and then we can look at incrementally improving from there.

Still need to do some throughput measurements.

**Comment by AndyAyersMS** [comment]
x86 outerloop crossgen2 has one unexpected failure:
* `CoreMangLib\system\threading\interlocked\InterlockedAdd1`

**Comment by AndyAyersMS** [comment]
x86 issue is that morph is reordering args to a call:
```
;; after fwd sub ([000030] subbed in for local)

***** BB03
STMT00009 ( 0x02F[E-] ... ??? )
               [000043] -ACXG-------              *  ASG       int   
               [000042] D------N----              +--*  LCL_VAR   int    V01 loc0         
               [000041] --CXG-------              \--*  AND       int   
               [000039] --CXG-------                 +--*  CAST      int <- bool <- int
               [000037] --CXG-------                 |  \--*  CALL r2r_ind int    InterlockedAdd1.CheckValues
               [000033] ------------ this in ecx     |     +--*  LCL_VAR   ref    V00 this         
               [000024] ------------ arg1            |     +--*  ADD       int   
               [000022] ------------                 |     |  +--*  LCL_VAR   int   (AX) V02 loc1         
               [000023] ------------                 |     |  \--*  LCL_VAR   int    V03 loc2         
               [000030] --CXG------- arg2            |     +--*  CALL r2r_ind int    System.Threading.Interlocked.Add
               [000028] ------------ arg0            |     |  +--*  LCL_VAR_ADDR byref  V02 loc1         
               [000029] ------------ arg1            |     |  \--*  LCL_VAR   int    V03 loc2         
               [000036] ------------ arg3            |     \--*  LCL_VAR   int   (AX) V02 loc1         
               [000040] ------------                 \--*  LCL_VAR   int    V01 loc0         

;; after morph

***** BB03
STMT00009 ( 0x02F[E-] ... ??? )
               [000043] -ACXG+------              *  ASG       int   
               [000042] D----+-N----              +--*  LCL_VAR   int    V01 loc0         
               [000115] --CXG+------              \--*  CAST      int <- bool <- int
               [000041] --CXG+------                 \--*  AND       int   
               [000037] --CXG+------                    +--*  CALL r2r_ind int    InterlockedAdd1.CheckValues
               [000030] --CXG+------ arg2 on STK        |  +--*  CALL r2r_ind int    System.Threading.Interlocked.Add
               [000028] -----+------ arg0 in ecx        |  |  +--*  LCL_VAR_ADDR int    V02 loc1         
               [000029] -----+------ arg1 in edx        |  |  \--*  LCL_VAR   int    V03 loc2         
               [000036] ----G+------ arg3 on STK        |  +--*  LCL_VAR   int   (AX) V02 loc1         
               [000024] ----G+------ arg1 in edx        |  +--*  ADD       int   
               [000022] ----G+------                    |  |  +--*  LCL_VAR   int   (AX) V02 loc1         
               [000023] -----+------                    |  |  \--*  LCL_VAR   int    V03 loc2         
               [000033] -----+------ this in ecx        |  \--*  LCL_VAR   ref    V00 this         
               [000040] -----+------                    \--*  LCL_VAR   int    V01 loc0         
```
Note the missing `G` flags in the before picture. We either need to block fwd sub if args interfere from exposed locals, or else set the flags during fwd sub.

**Comment by AndyAyersMS** [comment]
Looks like actually adding the missing flags might not be simple. So, going to disable subbing a call as a call arg for now, which should prevent us from reordering a call and an aliased read. 

This may not be sufficient -- we might also need to watch for calls that have embedded assignment args so that we're not tempted to reorder an assign and an aliased read.

We could also run after morph where presumably GT_GLOB_REF is more trustworthy, but that kind of misses the point.

Ultimately, we may want to ensure that GT_GLOB_REF is set appropriately conservatively early on via `ld-addr-op` or similar as we may want to do other forms of code motion early.  It is ok if it is overstated as long as it's not too bad. The importer seems to get spilling right and so is breaking trees to help morph avoid getting into trouble.

**Comment by AndyAyersMS** [comment]
Outerloop failures are just the "expected ones" from #64172.

Going to try some stress legs too.

**Comment by AndyAyersMS** [comment]
Jitstress has two failures:
* JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b30125 (many legs) -- stack overflow: likely trees got too large. May need some kind of destination tree complexity check too....
* Interop/PInvoke/Vector2_3_4 (x86) -- mismatched live register assert in codegen

File: src/coreclr/jit/forwardsub.cpp [hunk 3]
```diff
@@ -0,0 +1,622 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+#include "jitpch.h"
+
+#ifdef _MSC_VER
+#pragma hdrstop
+#endif
+
+// Simple Forward Substitution
```
Comment (BruceForstall) [inline src/coreclr/jit/forwardsub.cpp:10]: Here would be a good place for a nice long comment:
1. Describing what "forward substitution" means
2. Explains why we need it (e.g., describe if we're "fixing" importer decisions or other phase choices)
3. Explains why it's in this place in the phase order
4. Gives examples
5. Says what cases are handled and not handled (and says whether they are fundamental or implementation limitations)
6. Gives a rough outline of the algorithm

Perhaps some of these could/should be elsewhere, closer to the code that does the work, but putting a reference / link here to that would also be useful.

File: src/coreclr/jit/forwardsub.cpp [hunk 4]
```diff
@@ -0,0 +1,622 @@
...
+// Returns:
+//   suitable phase status
+//
+PhaseStatus Compiler::fgForwardSub()
+{
+    bool changed = false;
+    bool enabled = true;
+
+#if defined(DEBUG)
+    enabled = JitConfig.JitNoForwardSub() == 0;
```
Comment (BruceForstall) [inline src/coreclr/jit/forwardsub.cpp:24]: Wouldn't this be simpler to allow early-exit, and get rid of `enabled` on the extra nesting it induces?
```suggestion
    if (JitConfig.JitNoForwardSub())
    {
        return PhaseStatus::MODIFIED_NOTHING;
    }
```

File: src/coreclr/jit/forwardsub.cpp [hunk 5]
```diff
@@ -0,0 +1,622 @@
...
+}
+
+//------------------------------------------------------------------------
+// fgForwardSub(BasicBlock) -- try forward substitution in this block
+//
+// Arguments:
+//    block -- block to process
+//
+// Returns:
+//    true if any forward substitution took place
```
Comment (BruceForstall) [inline src/coreclr/jit/forwardsub.cpp:46]: This better be stronger: return true if any IR change of any kind was made.

File: src/coreclr/jit/forwardsub.cpp [hunk 6]
```diff
@@ -0,0 +1,622 @@
...
+    }
+
+private:
+    GenTree** m_use;
+    GenTree*  m_node;
+    GenTree*  m_parentNode;
+    unsigned  m_lclNum;
+    int       m_count;
+    unsigned  m_useFlags;
+    unsigned  m_accumulatedFlags;
```
Comment (BruceForstall) [inline src/coreclr/jit/forwardsub.cpp:201]: Shouldn't these be `GenTreeFlags` type?

File: src/coreclr/jit/forwardsub.cpp [hunk 7]
```diff
@@ -0,0 +1,622 @@
...
+        return fgWalkResult::WALK_CONTINUE;
+    }
+
+    unsigned GetFlags()
+    {
+        return m_flags;
+    }
+
+private:
+    unsigned m_flags;
```
Comment (BruceForstall) [inline src/coreclr/jit/forwardsub.cpp:245]: `GenTreeFlags`?

File: src/coreclr/jit/forwardsub.cpp [hunk 8]
```diff
@@ -0,0 +1,622 @@
...
+    //
+    if (fwdSubNode->OperIs(GT_QMARK, GT_CATCH_ARG, GT_LCLHEAP))
+    {
+        JITDUMP(" tree to sub is qmark, catch arg, or lcl heap\n");
+        return false;
+    }
+
+    if (fwdSubNode->IsCall() && fwdSubNode->AsCall()->IsNoReturn())
+    {
+        JITDUMP(" tree to sub is no return call\n");
```
Comment (BruceForstall) [inline src/coreclr/jit/forwardsub.cpp:338]:
```suggestion
        JITDUMP(" tree to sub is 'no return' call\n");
```

**Review by BruceForstall — COMMENTED** [review]
Left some comments, mostly suggestions for comments, or naming.

File: src/coreclr/jit/compiler.cpp [hunk 9]
```diff
@@ -4658,6 +4658,13 @@ void Compiler::compCompile(void** methodCodePtr, uint32_t* methodCodeSize, JitFl
     //
     DoPhase(this, PHASE_STR_ADRLCL, &Compiler::fgMarkAddressExposedLocals);
 
+    // Run a simple forward sub pass.
+    //
+    if (opts.OptimizationEnabled())
```
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply src/coreclr/jit/compiler.cpp:4663]: Yeah, we should probably settle on one or the other. I'll move it into the phase.

**Comment by AndyAyersMS** [comment]
Merged up, and updated to address Bruce's feedback.

File: src/coreclr/jit/forwardsub.cpp [hunk 10]
```diff
@@ -0,0 +1,737 @@
...
+#include "jitpch.h"
+
+#ifdef _MSC_VER
+#pragma hdrstop
+#endif
+
+//------------------------------------------------------------------------
+// Simple Forward Substitution
+//
+// This phase tries to reconnect trees that were split early on by
```
Comment (BruceForstall) [inline src/coreclr/jit/forwardsub.cpp:13]: Awesome comment block! Thanks!

File: src/coreclr/jit/forwardsub.cpp [hunk 11]
```diff
@@ -0,0 +1,737 @@
...
+// If we're successful we will backtrack a bit, to try and catch cases like
+//
+// Statement(n):
+//    lcl1 = tree1
+// Statement(n+1):
+//    lcl2 = tree2
+// Statement(n+2):
+//    use ...  lcl1 ... use ... lcl2 ...
+//
+// If we can forward sub tree2, then the def aind use of lcl1 become
```
Comment (BruceForstall) [inline src/coreclr/jit/forwardsub.cpp:51]:
```suggestion
// If we can forward sub tree2, then the def and use of lcl1 become
```

File: src/coreclr/jit/forwardsub.cpp [hunk 12]
```diff
@@ -0,0 +1,737 @@
...
+// substituted where; these reflect various blemishes or implicit
+// contracts in our IR shapes that we should either remove or mandate.
+//
+// Possible enhancements:
+// * Allow fwd sub of "simple, cheap" trees when there's more than one use.
+// * Search more widely for the use.
+// * Use height/depth to avoid blowing morph's recursion, rather than tree size.
+// * Sub accross a block boundary if successor block is unique, join-free,
+//   and in the same EH region.
+// * Retrun this later, after we have built SSA, and handle single-def single-use
```
Comment (BruceForstall) [inline src/coreclr/jit/forwardsub.cpp:89]:
```suggestion
// * Rerun this later, after we have built SSA, and handle single-def single-use
```

**Review by BruceForstall — APPROVED** [review]
LGTM

File: src/coreclr/jit/forwardsub.cpp (hunk 3 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/forwardsub.cpp:11]: Assuming what I wrote suffices....

File: src/coreclr/jit/forwardsub.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/forwardsub.cpp:548]: Added some extra flags scanning.

**Comment by AndyAyersMS** [comment]
Total SPMI replay time on subset of ASP.NET that this change and baseline can handle:
```
DIFF
Total time: 16726.746400ms
Total time: 16529.541400ms
Total time: 16651.382400ms
Total time: 16478.285100ms
Total time: 16633.492000ms
BASE
Total time: 16518.550900ms
Total time: 16622.835000ms
Total time: 16628.837500ms
Total time: 16652.667300ms
Total time: 16593.576300ms
```

**Comment by AndyAyersMS** [comment]
Outerloop clean save for failures in `Loader\classloader\RefFields\Validate` (#64484).

File: src/coreclr/jit/forwardsub.cpp [hunk 13]
```diff
@@ -0,0 +1,737 @@
...
+    if (fwdSubNodeInvariant && ((fsv.GetFlags() & (GTF_CALL | GTF_ASG)) != 0))
+    {
+        EffectsVisitor ev(this);
+        ev.WalkTree(&fwdSubNode, nullptr);
+
+        if ((ev.GetFlags() & GTF_GLOB_REF) != 0)
+        {
+            JITDUMP(" potentially interacting effects (AX locals)\n");
+            return false;
+        }
```
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply src/coreclr/jit/forwardsub.cpp:569]: Sure. And it would be nice to get these flags set correctly (conservatively) right from the importer so no repairing is needed, just (optional) refinement.

File: src/coreclr/jit/forwardsub.cpp [hunk 14]
```diff
@@ -0,0 +1,737 @@
...
+    GenTree* const nextRootNode = nextStmt->GetRootNode();
+
+    // Bail if types disagree.
+    // Might be able to tolerate these by retyping.
+    //
+    if (fsv.GetNode()->TypeGet() != fwdSubNode->TypeGet())
+    {
+        JITDUMP(" mismatched types (substitution)\n");
+        return false;
+    }
```
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply src/coreclr/jit/forwardsub.cpp:537]: Thanks for the example. Would you recommend just bailing on these or trying to handle?

[the remark this answers is not in the document]
Comment (SingleAccretion) [reply src/coreclr/jit/forwardsub.cpp:537]: Small temps created by inlining/import will be normalize-on-store, so I would expect it is worth handling them. They should be straightforward to handle by adding a cast on top of `fwdSubNode` if `fgCastNeeded(fwdSubNode, varDsc->TypeGet())` is `true`.

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Latest diff summary. Going to take one more look at some of the bigger regressions.

## aspnet.run.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 20487680 (overridden on cmd)
Total bytes of diff: 20458024 (overridden on cmd)
Total bytes of delta: -29656 (-0.14 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         359 : 34337.dasm (67.99% of base)
          91 : 14607.dasm (4.78% of base)
          86 : 28947.dasm (3.39% of base)
          60 : 62157.dasm (7.19% of base)
          53 : 28733.dasm (2.81% of base)
          47 : 65753.dasm (5.08% of base)
          44 : 16374.dasm (15.38% of base)
          38 : 30100.dasm (1.46% of base)
          35 : 19898.dasm (5.20% of base)
          35 : 34193.dasm (0.44% of base)
          32 : 64697.dasm (1.30% of base)
          32 : 32649.dasm (1.30% of base)
          32 : 45257.dasm (0.65% of base)
          32 : 66983.dasm (0.64% of base)
          31 : 56544.dasm (1.22% of base)
          31 : 17028.dasm (4.53% of base)
          30 : 14847.dasm (4.42% of base)
          29 : 30104.dasm (3.82% of base)
          29 : 46283.dasm (3.08% of base)
          29 : 62350.dasm (3.08% of base)

Top file improvements (bytes):
        -113 : 13608.dasm (-1.62% of base)
        -113 : 20155.dasm (-1.62% of base)
        -110 : 21386.dasm (-2.32% of base)
         -98 : 28428.dasm (-2.18% of base)
         -92 : 61172.dasm (-3.39% of base)
         -91 : 57396.dasm (-2.99% of base)
         -87 : 65448.dasm (-2.90% of base)
         -84 : 16583.dasm (-18.58% of base)
         -81 : 44932.dasm (-4.39% of base)
         -81 : 67021.dasm (-4.39% of base)
         -81 : 61721.dasm (-4.40% of base)
         -80 : 66769.dasm (-9.21% of base)
         -79 : 44317.dasm (-2.90% of base)
         -75 : 46331.dasm (-2.82% of base)
         -75 : 48091.dasm (-12.21% of base)
         -73 : 17514.dasm (-1.45% of base)
         -73 : 15552.dasm (-1.49% of base)
         -72 : 56483.dasm (-1.27% of base)
         -72 : 60126.dasm (-1.27% of base)
         -72 : 64520.dasm (-2.16% of base)

5418 total files with Code Size differences (4709 improved, 709 regressed), 2249 unchanged.

Top method regressions (bytes):
         359 (67.99% of base) : 34337.dasm - MethodBase:CheckArguments(byref,ReadOnlySpan`1,Binder,int,CultureInfo,ref):Span`1:this
          91 ( 4.78% of base) : 14607.dasm - ThreadPoolWorkQueue:Dispatch():bool
          86 ( 3.39% of base) : 28947.dasm - ThreadPoolWorkQueue:Dispatch():bool
          60 ( 7.19% of base) : 62157.dasm - TextEncoder:EncodeToNewString(ReadOnlySpan`1,int):String:this
          53 ( 2.81% of base) : 28733.dasm - HttpTransformer:TransformRequestAsync(HttpContext,HttpRequestMessage,String):ValueTask:this
          47 ( 5.08% of base) : 65753.dasm - CancellationTokenSource:Register(Delegate,Object,SynchronizationContext,ExecutionContext):CancellationTokenRegistration:this
          44 (15.38% of base) : 16374.dasm - String:IndexOfAny(ref):int:this
          38 ( 1.46% of base) : 30100.dasm - AssemblyNameParser:Parse():AssemblyNameParts:this
          35 ( 0.44% of base) : 34193.dasm - RegexFindOptimizations:TryFindNextStartingPosition(ReadOnlySpan`1,byref,int,int,int):bool:this
          35 ( 5.20% of base) : 19898.dasm - ResourceManager:GetFirstResourceSet(CultureInfo):ResourceSet:this
          32 ( 1.30% of base) : 64697.dasm - HttpParser`1:ParseHeaders(Http1ParsingHandler,byref):bool:this
          32 ( 1.30% of base) : 32649.dasm - HttpParser`1:ParseHeaders(Http1ParsingHandler,byref):bool:this
          32 ( 0.65% of base) : 45257.dasm - NpgsqlMemberTranslatorProvider:.ctor(RelationalMemberTranslatorProviderDependencies,IModel,IRelationalTypeMappingSource,INpgsqlOptions):this
          32 ( 0.64% of base) : 66983.dasm - NpgsqlMemberTranslatorProvider:.ctor(RelationalMemberTranslatorProviderDependencies,IModel,IRelationalTypeMappingSource,INpgsqlOptions):this
          31 ( 1.22% of base) : 56544.dasm - <OpenInternalAsync>d__70:MoveNext():this
          31 ( 4.53% of base) : 17028.dasm - String:IndexOfAny(ref):int:this
          30 ( 4.42% of base) : 14847.dasm - String:IndexOfAny(ref):int:this
          29 ( 3.82% of base) : 30104.dasm - String:IndexOfAny(ref):int:this
          29 ( 3.08% of base) : 46283.dasm - ViewLocationCacheKey:GetHashCode():int:this
          29 ( 3.08% of base) : 62350.dasm - ViewLocationCacheKey:GetHashCode():int:this

Top method improvements (bytes):
        -113 (-1.62% of base) : 13608.dasm - HttpRequestHeaders:Append(ReadOnlySpan`1,ReadOnlySpan`1,bool):this
        -113 (-1.62% of base) : 20155.dasm - HttpRequestHeaders:Append(ReadOnlySpan`1,ReadOnlySpan`1,bool):this
        -110 (-2.32% of base) : 21386.dasm - <WriteHeadersAsync>d__56:MoveNext():this
         -98 (-2.18% of base) : 28428.dasm - <WriteHeadersAsync>d__56:MoveNext():this
         -92 (-3.39% of base) : 61172.dasm - SafeDeleteContext:AcceptSecurityContext(byref,byref,int,int,InputSecurityBuffers,byref,byref):int
         -91 (-2.99% of base) : 57396.dasm - <QueryAsync>d__33`1:MoveNext():this
         -87 (-2.90% of base) : 65448.dasm - <QueryAsync>d__33`1:MoveNext():this
         -84 (-18.58% of base) : 16583.dasm - AdjustmentRule:get_HasDaylightSaving():bool:this
         -81 (-4.39% of base) : 44932.dasm - <InitializeReaderAsync>d__19:MoveNext():this
         -81 (-4.39% of base) : 67021.dasm - <InitializeReaderAsync>d__19:MoveNext():this
         -81 (-4.40% of base) : 61721.dasm - <InitializeReaderAsync>d__19:MoveNext():this
         -80 (-9.21% of base) : 66769.dasm - ConcurrentDictionary`2:TryGetValue(SslCredKey,byref):bool:this
         -79 (-2.90% of base) : 44317.dasm - SafeDeleteContext:AcceptSecurityContext(byref,byref,int,int,InputSecurityBuffers,byref,byref):int
         -75 (-2.82% of base) : 46331.dasm - <RenderPageCoreAsync>d__20:MoveNext():this
         -75 (-12.21% of base) : 48091.dasm - ConcurrentDictionary`2:TryGetValueInternal(ModelMetadataIdentity,int,byref):bool:this
         -73 (-1.45% of base) : 17514.dasm - TimeZoneInfo:GetIsDaylightSavingsFromUtc(DateTime,int,TimeSpan,AdjustmentRule,Nullable`1,byref,TimeZoneInfo):bool
         -73 (-1.49% of base) : 15552.dasm - TimeZoneInfo:GetIsDaylightSavingsFromUtc(DateTime,int,TimeSpan,AdjustmentRule,Nullable`1,byref,TimeZoneInfo):bool
         -72 (-1.27% of base) : 56483.dasm - <ExecuteReaderAsync>d__19:MoveNext():this
         -72 (-1.27% of base) : 60126.dasm - <ExecuteReaderAsync>d__19:MoveNext():this
         -72 (-2.69% of base) : 62397.dasm - <RenderPageCoreAsync>d__20:MoveNext():this

Top method regressions (percentages):
         359 (67.99% of base) : 34337.dasm - MethodBase:CheckArguments(byref,ReadOnlySpan`1,Binder,int,CultureInfo,ref):Span`1:this
           7 (24.14% of base) : 58547.dasm - OnEntityTypeAddedNode:Run(ConventionDispatcher):this
           7 (24.14% of base) : 58890.dasm - OnKeyAddedNode:Run(ConventionDispatcher):this
           7 (24.14% of base) : 58819.dasm - OnPropertyAddedNode:Run(ConventionDispatcher):this
           7 (24.14% of base) : 58958.dasm - OnPropertyNullableChangedNode:Run(ConventionDispatcher):this
           7 (24.14% of base) : 21032.dasm - String:GetHashCode():int:this
          11 (23.40% of base) : 66018.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 32198.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 34433.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 60500.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 55695.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 36962.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
          11 (23.40% of base) : 43239.dasm - OrdinalCaseSensitiveComparer:GetHashCode(String):int:this
           7 (18.92% of base) : 44282.dasm - IdnMapping:get_NlsFlags():int:this
           7 (18.92% of base) : 64185.dasm - IdnMapping:get_NlsFlags():int:this
           7 (18.92% of base) : 61154.dasm - IdnMapping:get_NlsFlags():int:this
          10 (17.54% of base) : 14889.dasm - ILStubClass:IL_STUB_PInvoke(int,long):int
          44 (15.38% of base) : 16374.dasm - String:IndexOfAny(ref):int:this
          17 (14.41% of base) : 49812.dasm - ControllerFactoryProvider:GetPropertiesToActivate(ControllerActionDescriptor):ref:this
          14 (13.46% of base) : 15894.dasm - AwaitableSocketAsyncEventArgs:Release():this

Top method improvements (percentages):
          -3 (-37.50% of base) : 15929.dasm - HeartbeatManager:get_UtcNowTicks():long:this
         -32 (-31.37% of base) : 60891.dasm - IEnumerableCallSite:.ctor(ResultCache,Type,ref):this
         -51 (-31.10% of base) : 66904.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
         -51 (-31.10% of base) : 61523.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
         -51 (-31.10% of base) : 44787.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
          -3 (-30.00% of base) : 882.dasm - Socket:get_SafeHandle():SafeSocketHandle:this
         -47 (-29.38% of base) : 56197.dasm - TypeMappingInfo:.ctor(Type,bool,Nullable`1,Nullable`1,Nullable`1,Nullable`1,Nullable`1):this
          -8 (-27.59% of base) : 60916.dasm - ResultCache:.ctor(int,ServiceCacheKey):this
          -3 (-27.27% of base) : 20410.dasm - ProxyConfigManager:GetChangeToken():IChangeToken:this
          -8 (-21.62% of base) : 6412.dasm - Complex:Abs():double:this
         -84 (-18.58% of base) : 16583.dasm - AdjustmentRule:get_HasDaylightSaving():bool:this
         -31 (-17.32% of base) : 59533.dasm - NpgsqlDecimalTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-17.32% of base) : 59485.dasm - NpgsqlDoubleTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-17.32% of base) : 59540.dasm - NpgsqlFloatTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40% of base) : 59536.dasm - NpgsqlCidrTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40% of base) : 59535.dasm - NpgsqlInetTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40% of base) : 59525.dasm - NpgsqlIntervalTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40% of base) : 59497.dasm - NpgsqlLTreeTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40% of base) : 59537.dasm - NpgsqlMacaddr8TypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this
         -31 (-16.40% of base) : 59529.dasm - NpgsqlRegconfigTypeMapping:Clone(RelationalTypeMappingParameters):RelationalTypeMapping:this

5418 total methods with Code Size differences (4709 improved, 709 regressed), 2249 unchanged.

```

</details>

--------------------------------------------------------------------------------

## benchmarks.run.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 12646739 (overridden on cmd)
Total bytes of diff: 12639718 (overridden on cmd)
Total bytes of delta: -7021 (-0.06 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         356 : 324.dasm (54.19% of base)
         116 : 41379.dasm (7.94% of base)
          92 : 34791.dasm (6.13% of base)
          79 : 7771.dasm (2.03% of base)
          59 : 1470.dasm (0.83% of base)
          45 : 34750.dasm (19.07% of base)
          40 : 34663.dasm (3.19% of base)
          39 : 35098.dasm (2.20% of base)
          39 : 34300.dasm (5.22% of base)
          39 : 2991.dasm (4.64% of base)
          39 : 34056.dasm (4.53% of base)
          36 : 37783.dasm (1.63% of base)
          36 : 8705.dasm (1.23% of base)
          33 : 5546.dasm (13.41% of base)
          32 : 33453.dasm (2.28% of base)
          31 : 33324.dasm (8.45% of base)
          30 : 35579.dasm (0.75% of base)
          29 : 34173.dasm (4.07% of base)
          29 : 34601.dasm (3.60% of base)
          29 : 11226.dasm (1.26% of base)

Top file improvements (bytes):
        -351 : 34355.dasm (-7.50% of base)
        -194 : 11962.dasm (-14.47% of base)
        -138 : 6511.dasm (-16.31% of base)
        -101 : 11178.dasm (-2.20% of base)
         -75 : 29355.dasm (-3.60% of base)
         -72 : 1295.dasm (-5.28% of base)
         -65 : 5989.dasm (-0.41% of base)
         -65 : 2908.dasm (-10.06% of base)
         -64 : 8550.dasm (-1.37% of base)
         -63 : 36669.dasm (-2.73% of base)
         -58 : 33215.dasm (-3.77% of base)
         -57 : 31724.dasm (-2.67% of base)
         -54 : 31689.dasm (-5.15% of base)
         -52 : 33606.dasm (-5.21% of base)
         -52 : 33428.dasm (-1.52% of base)
         -52 : 36671.dasm (-19.55% of base)
         -51 : 40627.dasm (-7.10% of base)
         -50 : 31775.dasm (-3.19% of base)
         -48 : 1597.dasm (-1.40% of base)
         -48 : 3193.dasm (-5.11% of base)

1933 total files with Code Size differences (1544 improved, 389 regressed), 9122 unchanged.

Top method regressions (bytes):
         356 (54.19% of base) : 324.dasm - System.Reflection.MethodBase:CheckArguments(byref,System.ReadOnlySpan`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],System.Reflection.Binder,int,System.Globalization.CultureInfo,System.RuntimeType[]):System.Span`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]:this
         116 ( 7.94% of base) : 41379.dasm - System.Net.Dns:GetHostEntryOrAddressesCore(System.Net.IPAddress,bool,int,Microsoft.Extensions.Internal.ValueStopwatch):System.Object
          92 ( 6.13% of base) : 34791.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.AnonymousTypeManager:AssignTemplatesNamesAndCompile(Microsoft.CodeAnalysis.CSharp.MethodCompiler,Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder,Microsoft.CodeAnalysis.DiagnosticBag):this
          79 ( 2.03% of base) : 7771.dasm - MessagePack.Internal.DynamicObjectTypeBuilder:BuildSerialize(System.Type,MessagePack.Internal.ObjectSerializationInfo,System.Reflection.Emit.ILGenerator,System.Action,System.Func`3[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MessagePack.Internal.ObjectSerializationInfo+EmittableMember, MessagePack, Version=1.9.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be],[System.Action, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],int)
          59 ( 0.83% of base) : 1470.dasm - ProtoBuf.Meta.MetaType:ApplyDefaultBehaviourImpl(int):this
          45 (19.07% of base) : 34750.dasm - Microsoft.CodeAnalysis.CSharp.LocalRewriter:OptimizeTemporaries(Microsoft.CodeAnalysis.CSharp.BoundExpression[],Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[[Microsoft.CodeAnalysis.CSharp.BoundAssignmentOperator, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[[Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]])
          40 ( 3.19% of base) : 34663.dasm - Microsoft.CodeAnalysis.CodeGen.ILBuilder:RealizeBlocks():this
          39 ( 2.20% of base) : 35098.dasm - Microsoft.Cci.MetadataWriter:SerializeTypeReference(System.Reflection.Metadata.Ecma335.SignatureTypeEncoder,Microsoft.Cci.ITypeReference):this
          39 ( 5.22% of base) : 34300.dasm - Microsoft.CodeAnalysis.CSharp.ExecutableCodeBinder:ComputeBinderMap():this
          39 ( 4.53% of base) : 34056.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:AddSynthesizedConstructorsIfNecessary(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[[Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[ImmutableArray`1],Microsoft.CodeAnalysis.DiagnosticBag):this
          39 ( 4.64% of base) : 2991.dasm - System.Resources.ResourceManager:GetFirstResourceSet(System.Globalization.CultureInfo):System.Resources.ResourceSet:this
          36 ( 1.63% of base) : 37783.dasm - CriticalHelper:ReadSimpleDictionary(System.Runtime.Serialization.CollectionDataContract,System.Type):this
          36 ( 1.23% of base) : 8705.dasm - System.Xml.Serialization.TempAssembly:GenerateRefEmitAssembly(System.Xml.Serialization.XmlMapping[],System.Type[],System.String):System.Reflection.Assembly
          33 (13.41% of base) : 5546.dasm - System.Net.IPAddress:.ctor(System.ReadOnlySpan`1[Byte]):this
          32 ( 2.28% of base) : 33453.dasm - Microsoft.CodeAnalysis.CommonReferenceManager`2[__Canon,__Canon][System.__Canon,System.__Canon]:ReuseAssemblySymbolsWithNoPiaLocalTypes(Microsoft.CodeAnalysis.CommonReferenceManager`2+BoundInputAssembly[System.__Canon,System.__Canon][],System.__Canon[],System.Collections.Immutable.ImmutableArray`1[__Canon],int):bool:this
          31 ( 8.45% of base) : 33324.dasm - Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode:ComputeSyntaxTree(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode):Microsoft.CodeAnalysis.SyntaxTree
          30 ( 0.75% of base) : 35579.dasm - CriticalHelper:ReadCollection(System.Runtime.Serialization.CollectionDataContract):this
          29 ( 3.60% of base) : 34601.dasm - Microsoft.CodeAnalysis.CSharp.CodeGen.Optimizer:FilterValidStackLocals(System.Collections.Generic.Dictionary`2[[Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.CodeAnalysis.CSharp.CodeGen.LocalDefUseInfo, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]])
          29 ( 4.07% of base) : 34173.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.ConstraintsHelper:CheckConstraints(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol,Microsoft.CodeAnalysis.CSharp.CSharpCompilation,Microsoft.CodeAnalysis.CSharp.ConversionsBase,Microsoft.CodeAnalysis.Location,Microsoft.CodeAnalysis.DiagnosticBag):bool
          29 ( 1.26% of base) : 11226.dasm - System.Numerics.BigIntegerCalculator:PowCore(System.Span`1[UInt32],int,System.ReadOnlySpan`1[UInt32],System.ReadOnlySpan`1[UInt32],System.Span`1[UInt32],System.Span`1[UInt32])

Top method improvements (bytes):
        -351 (-7.50% of base) : 34355.dasm - Microsoft.CodeAnalysis.CSharp.Binder:CheckValueKind(Microsoft.CodeAnalysis.SyntaxNode,Microsoft.CodeAnalysis.CSharp.BoundExpression,ushort,bool,Microsoft.CodeAnalysis.DiagnosticBag):bool:this
        -194 (-14.47% of base) : 11962.dasm - System.Diagnostics.Tracing.EventSource:WriteEventWithRelatedActivityIdCore(int,long,int,long):this
        -138 (-16.31% of base) : 6511.dasm - System.Net.Security.SslSessionsCache:<CacheCredential>g__ShrinkCredentialCache|5_0()
        -101 (-2.20% of base) : 11178.dasm - <WriteHeadersAsync>d__56:MoveNext():this
         -75 (-3.60% of base) : 29355.dasm - Utf8Json.Formatters.MicroBenchmarks_Serializers_ActiveOrUpcomingEventFormatter2:Deserialize(byref,Utf8Json.IJsonFormatterResolver):MicroBenchmarks.Serializers.ActiveOrUpcomingEvent:this
         -72 (-5.28% of base) : 1295.dasm - MicroBenchmarks.Serializers.DataGenerator:CreateMyEventsListerItem():MicroBenchmarks.Serializers.MyEventsListerItem
         -65 (-0.41% of base) : 5989.dasm - <SendAsyncCore>d__60:MoveNext():this
         -65 (-10.06% of base) : 2908.dasm - Sigil.Impl.BufferedILGenerator`1[__Canon][System.__Canon]:Emit(System.Reflection.Emit.OpCode,Sigil.Label,byref):this
         -64 (-1.37% of base) : 8550.dasm - Newtonsoft.Json.JsonWriter:WriteValue(Newtonsoft.Json.JsonWriter,int,System.Object)
         -63 (-2.73% of base) : 36669.dasm - Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyEventsListerViewModel:Read4_MyEventsListerItem(bool,bool):MicroBenchmarks.Serializers.MyEventsListerItem:this
         -58 (-3.77% of base) : 33215.dasm - Microsoft.CodeAnalysis.Compilation:Emit(System.IO.Stream,System.IO.Stream,System.IO.Stream,System.IO.Stream,System.IO.Stream,System.Collections.Generic.IEnumerable`1[[Microsoft.CodeAnalysis.ResourceDescription, Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.Emit.EmitOptions,Microsoft.CodeAnalysis.IMethodSymbol,System.IO.Stream,System.Collections.Generic.IEnumerable`1[[Microsoft.CodeAnalysis.EmbeddedText, Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.CodeGen.CompilationTestData,System.Threading.CancellationToken):Microsoft.CodeAnalysis.Emit.EmitResult:this
         -57 (-2.67% of base) : 31724.dasm - Utf8Json.Formatters.MicroBenchmarks_Serializers_MyEventsListerItemFormatter2:Deserialize(byref,Utf8Json.IJsonFormatterResolver):MicroBenchmarks.Serializers.MyEventsListerItem:this
         -54 (-5.15% of base) : 31689.dasm - LUDecomp:build_problem(System.Double[][],int,System.Double[])
         -52 (-5.21% of base) : 33606.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol:GetTopLevelTypeByMetadataName(byref,Microsoft.CodeAnalysis.AssemblyIdentity,bool,bool,byref,Microsoft.CodeAnalysis.DiagnosticBag,bool):Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol:this
         -52 (-1.52% of base) : 33428.dasm - Microsoft.CodeAnalysis.PEModule:GetTargetAttributeSignatureIndex(System.Reflection.Metadata.MetadataReader,System.Reflection.Metadata.CustomAttributeHandle,Microsoft.CodeAnalysis.AttributeDescription):int
         -52 (-19.55% of base) : 36671.dasm - Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyEventsListerViewModel:Read1_NullableOfDateTimeOffset(bool):System.Nullable`1[DateTimeOffset]:this
         -51 (-7.10% of base) : 40627.dasm - System.Collections.Concurrent.ConcurrentQueue`1[Int32][System.Int32]:get_Count():int:this
         -50 (-3.19% of base) : 31775.dasm - Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderIndexViewModel:Read2_ActiveOrUpcomingEvent(bool,bool):MicroBenchmarks.Serializers.ActiveOrUpcomingEvent:this
         -48 (-1.40% of base) : 1597.dasm - ProtoBuf.Meta.MetaType:BuildSerializer():ProtoBuf.Internal.Serializers.IProtoTypeSerializer:this
         -48 (-5.11% of base) : 3193.dasm - System.Xml.XmlBaseWriter:WriteEndAttribute():this

Top method regressions (percentages):
         356 (54.19% of base) : 324.dasm - System.Reflection.MethodBase:CheckArguments(byref,System.ReadOnlySpan`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],System.Reflection.Binder,int,System.Globalization.CultureInfo,System.RuntimeType[]):System.Span`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]:this
           7 (35.00% of base) : 40796.dasm - System.Tests.Perf_String:Concat_str_str_str(System.Tests.StringArguments):System.String:this
          11 (33.33% of base) : 37204.dasm - <>c__DisplayClass2_1:<RenderSingleThreadedWithADT>b__1(int,int):this
          11 (33.33% of base) : 37847.dasm - <>c__DisplayClass3_1:<RenderSingleThreadedNoADT>b__1(long,int):this
          11 (33.33% of base) : 38324.dasm - <>c__DisplayClass4_1:<RenderSingleThreadedWithADT>b__1(long,int):this
          22 (28.95% of base) : 34752.dasm - Microsoft.CodeAnalysis.CSharp.LocalRewriter:GetRefKindsOrNull(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[RefKind]):System.Collections.Immutable.ImmutableArray`1[RefKind]
          25 (26.88% of base) : 34061.dasm - Microsoft.CodeAnalysis.ArrayBuilderExtensions:Any(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[ImmutableArray`1],System.Func`2[ImmutableArray`1,Boolean]):bool
           6 (26.09% of base) : 8851.dasm - System.Text.RegularExpressions.Capture:get_Value():System.String:this
           7 (24.14% of base) : 2610.dasm - System.String:GetHashCode():int:this
          24 (20.87% of base) : 7567.dasm - System.Text.RegularExpressions.Symbolic.RegexNodeToSymbolicConverter:<Convert>g__EnsureNewlinePredicateInitialized|9_0():this
          27 (19.57% of base) : 6391.dasm - System.Uri:ToString():System.String:this
          45 (19.07% of base) : 34750.dasm - Microsoft.CodeAnalysis.CSharp.LocalRewriter:OptimizeTemporaries(Microsoft.CodeAnalysis.CSharp.BoundExpression[],Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[[Microsoft.CodeAnalysis.CSharp.BoundAssignmentOperator, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[[Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]])
          17 (17.89% of base) : 7594.dasm - System.Text.RegularExpressions.Symbolic.RegexNodeToSymbolicConverter:<Convert>g__EnsureWordLetterPredicateInitialized|9_1():this
          23 (17.69% of base) : 7106.dasm - Newtonsoft.Json.Linq.JObject:WriteTo(Newtonsoft.Json.JsonWriter,Newtonsoft.Json.JsonConverter[]):this
           7 (17.50% of base) : 1703.dasm - ProtoBuf.Serializers.RepeatedSerializerStub:EmitProvider(System.Reflection.Emit.ILGenerator):this
           8 (14.81% of base) : 33966.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol:GetDeclaredInterfaces(Roslyn.Utilities.ConsList`1[[Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]):System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]:this
           8 (14.81% of base) : 33964.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol:InterfacesNoUseSiteDiagnostics(Roslyn.Utilities.ConsList`1[[Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]):System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol, Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]:this
           4 (14.81% of base) : 41237.dasm - System.Tests.Perf_String:Concat_str_str_str_str(System.Tests.StringArguments):System.String:this
           7 (13.73% of base) : 37207.dasm - StoreBlock.AnyLocation:InitBlockAllOnes8():this
          33 (13.41% of base) : 5546.dasm - System.Net.IPAddress:.ctor(System.ReadOnlySpan`1[Byte]):this

Top method improvements (percentages):
         -24 (-42.11% of base) : 3842.dasm - EscaperImplementation:.ctor(bool):this
          -8 (-42.11% of base) : 30238.dasm - System.Span`1[__Canon][System.__Canon]:Clear():this
          -8 (-27.59% of base) : 4084.dasm - Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache:.ctor(int,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey):this
         -10 (-25.00% of base) : 10101.dasm - DataMemberComparer:Compare(System.Runtime.Serialization.DataMember,System.Runtime.Serialization.DataMember):int:this
          -3 (-25.00% of base) : 12801.dasm - System.Threading.Tests.Perf_Volatile:Read_double():double:this
         -22 (-20.00% of base) : 11877.dasm - System.Buffers.Tests.BufferSegment`1[Byte][System.Byte]:Append(System.ReadOnlyMemory`1[Byte]):System.Buffers.Tests.BufferSegment`1[Byte]:this
         -22 (-20.00% of base) : 7229.dasm - System.Memory.BufferSegment`1[Byte][System.Byte]:Append(System.ReadOnlyMemory`1[Byte]):System.Memory.BufferSegment`1[Byte]:this
         -52 (-19.55% of base) : 36671.dasm - Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMyEventsListerViewModel:Read1_NullableOfDateTimeOffset(bool):System.Nullable`1[DateTimeOffset]:this
         -33 (-17.65% of base) : 34033.dasm - Microsoft.CodeAnalysis.CSharp.Binder:WithUnsafeRegionIfNecessary(Microsoft.CodeAnalysis.SyntaxTokenList):Microsoft.CodeAnalysis.CSharp.Binder:this
          -3 (-17.65% of base) : 34206.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:HasComplete(int):bool:this
          -3 (-17.65% of base) : 34207.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol:HasComplete(int):bool:this
        -138 (-16.31% of base) : 6511.dasm - System.Net.Security.SslSessionsCache:<CacheCredential>g__ShrinkCredentialCache|5_0()
         -28 (-15.91% of base) : 7130.dasm - Newtonsoft.Json.JsonWriter:Pop():int:this
         -16 (-15.84% of base) : 32382.dasm - System.Numerics.Matrix4x4:op_Equality(System.Numerics.Matrix4x4,System.Numerics.Matrix4x4):bool
         -10 (-15.38% of base) : 11170.dasm - System.Net.Http.HttpConnectionPool:GetSslOptionsForRequest(System.Net.Http.HttpRequestMessage):System.Net.Security.SslClientAuthenticationOptions:this
         -16 (-15.38% of base) : 39284.dasm - System.Numerics.Matrix4x4:op_Inequality(System.Numerics.Matrix4x4,System.Numerics.Matrix4x4):bool
         -12 (-15.19% of base) : 12078.dasm - DynamicClass:StartDateSetter(System.Object,System.DateTimeOffset)
         -15 (-14.85% of base) : 6046.dasm - System.Net.Http.HttpConnection:EqualsOrdinal(System.String,System.ReadOnlySpan`1[Byte]):bool
          -6 (-14.63% of base) : 12493.dasm - <>c:<set_MaxCacheSize>b__11_0(Node,Node):int:this
        -194 (-14.47% of base) : 11962.dasm - System.Diagnostics.Tracing.EventSource:WriteEventWithRelatedActivityIdCore(int,long,int,long):this

1933 total methods with Code Size differences (1544 improved, 389 regressed), 9122 unchanged.

```

</details>

--------------------------------------------------------------------------------

## coreclr_tests.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 127103442 (overridden on cmd)
Total bytes of diff: 127026916 (overridden on cmd)
Total bytes of delta: -76526 (-0.06 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
        3819 : 228811.dasm (3.16% of base)
        3663 : 228801.dasm (3.00% of base)
         441 : 219402.dasm (0.32% of base)
         425 : 219422.dasm (0.30% of base)
         413 : 219325.dasm (0.31% of base)
         329 : 219305.dasm (0.25% of base)
         295 : 234612.dasm (1.28% of base)
         280 : 234676.dasm (1.21% of base)
         277 : 234750.dasm (1.19% of base)
         268 : 234649.dasm (1.11% of base)
         268 : 234760.dasm (1.14% of base)
         265 : 234686.dasm (1.13% of base)
         264 : 228695.dasm (1.07% of base)
         264 : 228701.dasm (1.07% of base)
         250 : 234639.dasm (1.05% of base)
         248 : 228610.dasm (0.98% of base)
         246 : 241902.dasm (179.56% of base)
         238 : 216844.dasm (2.03% of base)
         233 : 228574.dasm (0.94% of base)
         220 : 234594.dasm (0.95% of base)

Top file improvements (bytes):
       -1526 : 160929.dasm (-16.72% of base)
       -1172 : 229589.dasm (-1.94% of base)
       -1148 : 229594.dasm (-1.91% of base)
       -1105 : 226610.dasm (-7.16% of base)
       -1105 : 226612.dasm (-7.16% of base)
        -980 : 161199.dasm (-14.06% of base)
        -944 : 163803.dasm (-13.61% of base)
        -739 : 161153.dasm (-8.38% of base)
        -632 : 161851.dasm (-10.33% of base)
        -578 : 219354.dasm (-0.47% of base)
        -578 : 219364.dasm (-0.47% of base)
        -578 : 219187.dasm (-0.47% of base)
        -578 : 219206.dasm (-0.47% of base)
        -572 : 164261.dasm (-9.60% of base)
        -521 : 230426.dasm (-13.67% of base)
        -393 : 234963.dasm (-11.89% of base)
        -393 : 234989.dasm (-11.89% of base)
        -288 : 235472.dasm (-0.86% of base)
        -276 : 234848.dasm (-6.31% of base)
        -274 : 234980.dasm (-9.31% of base)

12043 total files with Code Size differences (10524 improved, 1519 regressed), 34244 unchanged.

Top method regressions (bytes):
        3819 ( 3.16% of base) : 228811.dasm - r8div:Main():int
        3663 ( 3.00% of base) : 228801.dasm - r4div:Main():int
         441 ( 0.32% of base) : 219402.dasm - u4rem:Main():int
         425 ( 0.30% of base) : 219422.dasm - u8rem:Main():int
         413 ( 0.31% of base) : 219325.dasm - i8rem:Main():int
         329 ( 0.25% of base) : 219305.dasm - i4rem:Main():int
         295 ( 1.28% of base) : 234612.dasm - lclfldadd:Main():int
         280 ( 1.21% of base) : 234676.dasm - lclfldmul:Main():int
         277 ( 1.19% of base) : 234750.dasm - lclfldsub:Main():int
         268 ( 1.11% of base) : 234649.dasm - lclflddiv:Main():int
         268 ( 1.14% of base) : 234760.dasm - lclfldsub:Main():int
         265 ( 1.13% of base) : 234686.dasm - lclfldmul:Main():int
         264 ( 1.07% of base) : 228695.dasm - r8NaNmul:Main():int
         264 ( 1.07% of base) : 228701.dasm - r8NaNmul:Main():int
         250 ( 1.05% of base) : 234639.dasm - lclflddiv:Main():int
         248 ( 0.98% of base) : 228610.dasm - r4NaNmul:Main():int
         246 (179.56% of base) : 241902.dasm - ServerSimulator.Parameters:.ctor():this
         238 ( 2.03% of base) : 216844.dasm - TestReflectionInvoke:Run()
         233 ( 0.94% of base) : 228574.dasm - r4NaNadd:Main():int
         220 ( 0.95% of base) : 234594.dasm - lclfldadd:Main():int

Top method improvements (bytes):
       -1526 (-16.72% of base) : 160929.dasm - testout1:Func_0_4_5_4():System.Decimal
       -1172 (-1.94% of base) : 229589.dasm - testout1:Func_0():int
       -1148 (-1.91% of base) : 229594.dasm - testout1:Func_0():int
       -1105 (-7.16% of base) : 226610.dasm - IntelHardwareIntrinsicTest.Program:Main(System.String[]):int
       -1105 (-7.16% of base) : 226612.dasm - IntelHardwareIntrinsicTest.Program:Main(System.String[]):int
        -980 (-14.06% of base) : 161199.dasm - testout1:Func_0_2_3_1_5():System.Decimal
        -944 (-13.61% of base) : 163803.dasm - testout1:Func_0_2_3_1_5():System.Decimal
        -739 (-8.38% of base) : 161153.dasm - testout1:Func_0_1_6_6_1():System.Decimal
        -632 (-10.33% of base) : 161851.dasm - testout1:Func_0_5_5_5_6():System.Decimal
        -578 (-0.47% of base) : 219187.dasm - overlddiv:Main():int
        -578 (-0.47% of base) : 219206.dasm - overlddiv:Main():int
        -578 (-0.47% of base) : 219354.dasm - overldrem:Main():int
        -578 (-0.47% of base) : 219364.dasm - overldrem:Main():int
        -572 (-9.60% of base) : 164261.dasm - testout1:Func_0_5_5_5_6():System.Decimal
        -521 (-13.67% of base) : 230426.dasm - BenchmarkConsoleApplication.BenchmarkSystem:ProcessCommandLine(System.String[]):this
        -393 (-11.89% of base) : 234963.dasm - IntelHardwareIntrinsicTest.Program:Main(System.String[]):int
        -393 (-11.89% of base) : 234989.dasm - IntelHardwareIntrinsicTest.Program:Main(System.String[]):int
        -288 (-0.86% of base) : 235472.dasm - floatMDArrTest:Main():int
        -276 (-6.31% of base) : 234848.dasm - IntelHardwareIntrinsicTest.Program:Main(System.String[]):int
        -274 (-9.31% of base) : 234980.dasm - IntelHardwareIntrinsicTest.Program:Main(System.String[]):int

Top method regressions (percentages):
          35 (3,500.00% of base) : 224304.dasm - TestUnsafeCasts:StructFromPrim()
         102 (728.57% of base) : 92382.dasm - Z:Main():int
          85 (607.14% of base) : 92347.dasm - Z:Main(System.String[]):int
          17 (188.89% of base) : 216886.dasm - TestClassVTableTracking:Run()
         246 (179.56% of base) : 241902.dasm - ServerSimulator.Parameters:.ctor():this
          18 (163.64% of base) : 246939.dasm - JitTest.Test:method_3_0(long):long
          18 (163.64% of base) : 247049.dasm - JitTest.Test:method_3_0(long):long
          18 (163.64% of base) : 247380.dasm - JitTest.Test:method_3_0(ushort):ushort
          18 (163.64% of base) : 256487.dasm - JitTest.Test:method_3_6(JitTest.ValueClass):JitTest.ValueClass
          18 (163.64% of base) : 256499.dasm - JitTest.Test:method_5_0(JitTest.ValueClass):JitTest.ValueClass
          18 (163.64% of base) : 246921.dasm - JitTest.Test:method_5_3(long):long
          18 (163.64% of base) : 247031.dasm - JitTest.Test:method_5_3(long):long
          18 (163.64% of base) : 247363.dasm - JitTest.Test:method_5_3(ushort):ushort
          18 (163.64% of base) : 246924.dasm - JitTest.Test:method_5_6(long):long
          18 (163.64% of base) : 247034.dasm - JitTest.Test:method_5_6(long):long
          18 (163.64% of base) : 247366.dasm - JitTest.Test:method_5_6(ushort):ushort
          51 (159.38% of base) : 97512.dasm - Test_TestCase0:Main():int
          51 (159.38% of base) : 97513.dasm - Test_TestCase0:Main():int
          51 (159.38% of base) : 97514.dasm - Test_TestCase1:Main():int
          85 (149.12% of base) : 97711.dasm - <Module>:Main():int

Top method improvements (percentages):
         -31 (-91.18% of base) : 241388.dasm - S:m(S):this
         -31 (-91.18% of base) : 241395.dasm - S1:m(S2):this
         -31 (-91.18% of base) : 241398.dasm - S1`1[Byte][System.Byte]:m(S2`1[Byte]):this
         -31 (-91.18% of base) : 241396.dasm - S2:m(S1):this
         -31 (-91.18% of base) : 241400.dasm - S2`1[Byte][System.Byte]:m(S1`1[Byte]):this
         -31 (-91.18% of base) : 241390.dasm - S2`1[Byte][System.Byte]:m(S2`1[Byte]):this
          -6 (-60.00% of base) : 229442.dasm - TestApp:test_0_1(ubyte,AA,AA):ubyte
          -8 (-57.14% of base) : 96042.dasm - _isinst:main(System.String[]):int
          -8 (-57.14% of base) : 96050.dasm - _newobj:main(System.String[]):int
          -8 (-57.14% of base) : 95959.dasm - ldind_ref:main(System.String[]):int
         -19 (-46.34% of base) : 207084.dasm - Tests:Test141_cns(int):ubyte
         -19 (-46.34% of base) : 207026.dasm - Tests:Test144_cns(int):ubyte
         -19 (-46.34% of base) : 207032.dasm - Tests:Test147_cns(int):ubyte
         -19 (-46.34% of base) : 207040.dasm - Tests:Test151_cns(int):ubyte
         -19 (-46.34% of base) : 207048.dasm - Tests:Test155_cns(int):ubyte
         -19 (-46.34% of base) : 206990.dasm - Tests:Test158_cns(int):ubyte
         -19 (-46.34% of base) : 206996.dasm - Tests:Test161_cns(int):ubyte
         -19 (-46.34% of base) : 207004.dasm - Tests:Test165_cns(int):ubyte
         -19 (-46.34% of base) : 207012.dasm - Tests:Test169_cns(int):ubyte
         -19 (-46.34% of base) : 207018.dasm - Tests:Test172_cns(int):ubyte

12043 total methods with Code Size differences (10524 improved, 1519 regressed), 34244 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.crossgen2.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 33726910 (overridden on cmd)
Total bytes of diff: 33693615 (overridden on cmd)
Total bytes of delta: -33295 (-0.10 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         342 : 51979.dasm (12.93% of base)
         313 : 94337.dasm (52.52% of base)
         175 : 81291.dasm (2.71% of base)
         141 : 114355.dasm (6.33% of base)
         140 : 78341.dasm (3.00% of base)
         117 : 122797.dasm (68.42% of base)
         106 : 47074.dasm (3.06% of base)
         105 : 122705.dasm (12.24% of base)
         103 : 50814.dasm (9.33% of base)
         100 : 47088.dasm (3.10% of base)
          89 : 136346.dasm (0.71% of base)
          86 : 47144.dasm (2.82% of base)
          81 : 131717.dasm (14.44% of base)
          77 : 154124.dasm (10.69% of base)
          72 : 100025.dasm (3.55% of base)
          70 : 46989.dasm (2.46% of base)
          70 : 47060.dasm (2.30% of base)
          66 : 47102.dasm (2.33% of base)
          66 : 47116.dasm (2.33% of base)
          66 : 88014.dasm (31.88% of base)

Top file improvements (bytes):
       -1199 : 21075.dasm (-2.77% of base)
        -553 : 30962.dasm (-3.75% of base)
        -132 : 47599.dasm (-3.02% of base)
        -128 : 157054.dasm (-7.01% of base)
        -128 : 191230.dasm (-3.76% of base)
        -108 : 115304.dasm (-4.54% of base)
        -103 : 84598.dasm (-2.86% of base)
        -102 : 102353.dasm (-14.76% of base)
        -101 : 78763.dasm (-4.32% of base)
         -98 : 178870.dasm (-6.39% of base)
         -96 : 136167.dasm (-2.27% of base)
         -95 : 164290.dasm (-6.18% of base)
         -91 : 178895.dasm (-6.95% of base)
         -85 : 102354.dasm (-12.86% of base)
         -82 : 31130.dasm (-0.71% of base)
         -80 : 129731.dasm (-3.49% of base)
         -80 : 71277.dasm (-2.61% of base)
         -75 : 160323.dasm (-7.04% of base)
         -75 : 12185.dasm (-5.68% of base)
         -74 : 176656.dasm (-1.09% of base)

8184 total files with Code Size differences (6559 improved, 1625 regressed), 14179 unchanged.

Top method regressions (bytes):
         342 (12.93% of base) : 51979.dasm - System.Data.XMLDiffLoader:ReadOldRowData(System.Data.DataSet,byref,byref,System.Xml.XmlReader):int:this
         313 (52.52% of base) : 94337.dasm - System.Reflection.MethodBase:CheckArguments(byref,System.ReadOnlySpan`1[System.Object],System.Reflection.Binder,int,System.Globalization.CultureInfo,System.RuntimeType[]):System.Span`1[System.Object]:this
         175 ( 2.71% of base) : 81291.dasm - System.Xml.Schema.SchemaCollectionPreprocessor:Preprocess(System.Xml.Schema.XmlSchema,System.String,int):this
         141 ( 6.33% of base) : 114355.dasm - ReferenceManager:CreateAndSetSourceAssemblyFullBind(Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation):bool:this
         140 ( 3.00% of base) : 78341.dasm - System.Xml.Xsl.XsltOld.HtmlElementProps:CreatePropsTable():System.Collections.Hashtable
         117 (68.42% of base) : 122797.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxListBuilder:AddRange(Microsoft.CodeAnalysis.SyntaxNode[],int,int):Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxListBuilder:this
         106 ( 3.06% of base) : 47074.dasm - System.Data.Common.SqlMoneyStorage:Aggregate(System.Int32[],int):System.Object:this
         105 (12.24% of base) : 122705.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxTriviaListBuilder:ToList():Microsoft.CodeAnalysis.SyntaxTriviaList:this
         103 ( 9.33% of base) : 50814.dasm - System.Data.DataSet:SerializeDataSet(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext,int):this
         100 ( 3.10% of base) : 47088.dasm - System.Data.Common.SqlInt64Storage:Aggregate(System.Int32[],int):System.Object:this
          89 ( 0.71% of base) : 136346.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:ReportOverloadResolutionFailureForASingleCandidate(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.Location,int,byref,System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.BoundExpression],System.Collections.Immutable.ImmutableArray`1[System.String],bool,bool,bool,bool,Microsoft.CodeAnalysis.DiagnosticBag,Microsoft.CodeAnalysis.VisualBasic.Symbol,bool,Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.Symbol):this
          86 ( 2.82% of base) : 47144.dasm - System.Data.Common.SqlDoubleStorage:Aggregate(System.Int32[],int):System.Object:this
          81 (14.44% of base) : 131717.dasm - Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbolExtensions:TransformToCanonicalFormFor(System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol],Microsoft.CodeAnalysis.VisualBasic.Symbol,System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeParameterSymbol]):System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol]
          77 (10.69% of base) : 154124.dasm - Microsoft.CodeAnalysis.CSharp.LocalRewriter:EvaluateSideEffectingArgumentsToTemps(System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.CSharp.BoundExpression],Microsoft.CodeAnalysis.ArrayBuilder`1[Microsoft.CodeAnalysis.CSharp.BoundExpression],byref):System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.CSharp.BoundExpression]:this
          72 ( 3.55% of base) : 100025.dasm - System.Globalization.TimeSpanFormat:FormatCustomized(System.TimeSpan,System.ReadOnlySpan`1[System.Char],System.Globalization.DateTimeFormatInfo,System.Text.StringBuilder):System.Text.StringBuilder
          70 ( 2.46% of base) : 46989.dasm - System.Data.Common.SqlByteStorage:Aggregate(System.Int32[],int):System.Object:this
          70 ( 2.30% of base) : 47060.dasm - System.Data.Common.SqlSingleStorage:Aggregate(System.Int32[],int):System.Object:this
          66 (31.88% of base) : 88014.dasm - MS.Internal.Xml.Cache.XPathNodeHelper:GetContentChild(byref,byref):bool
          66 ( 2.33% of base) : 47116.dasm - System.Data.Common.SqlInt16Storage:Aggregate(System.Int32[],int):System.Object:this
          66 ( 2.33% of base) : 47102.dasm - System.Data.Common.SqlInt32Storage:Aggregate(System.Int32[],int):System.Object:this

Top method improvements (bytes):
       -1199 (-2.77% of base) : 21075.dasm - Microsoft.Diagnostics.Tracing.CtfTraceEventSource:InitEventMap():System.Collections.Generic.Dictionary`2[System.String, Microsoft.Diagnostics.Tracing.ETWMapping]
        -553 (-3.75% of base) : 30962.dasm - <StartupCode$FSharp-Core>.$Query:.cctor()
        -132 (-3.02% of base) : 47599.dasm - System.Data.Common.DbDataAdapter:Update(System.Data.DataRow[],System.Data.Common.DataTableMapping):int:this
        -128 (-7.01% of base) : 157054.dasm - Microsoft.CodeAnalysis.CSharp.ClsComplianceChecker:TryGetCollisionErrorCode(Microsoft.CodeAnalysis.CSharp.Symbol,Microsoft.CodeAnalysis.CSharp.Symbol,byref):bool
        -128 (-3.76% of base) : 191230.dasm - System.DirectoryServices.Protocols.LdapConnection:SendRequestHelper(System.DirectoryServices.Protocols.DirectoryRequest,byref):int:this
        -108 (-4.54% of base) : 115304.dasm - AnonymousTypeToStringMethodSymbol:GetBoundMethodBody(Microsoft.CodeAnalysis.DiagnosticBag,byref):Microsoft.CodeAnalysis.VisualBasic.BoundBlock:this
        -103 (-2.86% of base) : 84598.dasm - System.Xml.XmlTextReaderImpl:ParseAttributeValueSlow(int,ushort,System.Xml.XmlTextReaderImpl+NodeData):this
        -102 (-14.76% of base) : 102353.dasm - System.TupleExtensions:ToValueTuple(System.Tuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.Tuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.Tuple`7[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon]]]):System.ValueTuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.ValueTuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.ValueTuple`7[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon]]]
        -101 (-4.32% of base) : 78763.dasm - System.Xml.Xsl.Xslt.XsltInput:GetAttributes(System.Xml.Xsl.Xslt.XsltInput+XsltAttribute[]):System.Xml.Xsl.Xslt.XsltInput+ContextInfo:this
         -98 (-6.39% of base) : 178870.dasm - System.Threading.Tasks.Parallel:PartitionerForEachWorker(System.Collections.Concurrent.Partitioner`1[System.__Canon],System.Threading.Tasks.ParallelOptions,System.Action`1[System.__Canon],System.Action`2[System.__Canon, System.Threading.Tasks.ParallelLoopState],System.Action`3[System.__Canon, System.Threading.Tasks.ParallelLoopState, System.Int64],System.Func`4[System.__Canon, System.Threading.Tasks.ParallelLoopState, System.__Canon, System.__Canon],System.Func`5[System.__Canon, System.Threading.Tasks.ParallelLoopState, System.Int64, System.__Canon, System.__Canon],System.Func`1[System.__Canon],System.Action`1[System.__Canon]):System.Threading.Tasks.ParallelLoopResult
         -96 (-2.27% of base) : 136167.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:BindRaiseEventStatement(Microsoft.CodeAnalysis.VisualBasic.Syntax.RaiseEventStatementSyntax,Microsoft.CodeAnalysis.DiagnosticBag):Microsoft.CodeAnalysis.VisualBasic.BoundStatement:this
         -95 (-6.18% of base) : 164290.dasm - Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase:VisitChildren(Microsoft.CSharp.RuntimeBinder.Semantics.Expr):this
         -91 (-6.95% of base) : 178895.dasm - System.Threading.Tasks.Parallel:ForWorker(int,int,System.Threading.Tasks.ParallelOptions,System.Action`1[System.Int32],System.Action`2[System.Int32, System.Threading.Tasks.ParallelLoopState],System.Func`4[System.Int32, System.Threading.Tasks.ParallelLoopState, System.__Canon, System.__Canon],System.Func`1[System.__Canon],System.Action`1[System.__Canon]):System.Threading.Tasks.ParallelLoopResult
         -85 (-12.86% of base) : 102354.dasm - System.TupleExtensions:ToValueTuple(System.Tuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.Tuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.Tuple`6[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon]]]):System.ValueTuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.ValueTuple`8[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.ValueTuple`6[System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon]]]
         -82 (-0.71% of base) : 31130.dasm - Microsoft.FSharp.Linq.QueryModule:TransInner(int,bool,Microsoft.FSharp.Quotations.FSharpExpr):System.Tuple`2[Microsoft.FSharp.Linq.QueryModule+TransInnerResult, Microsoft.FSharp.Linq.RuntimeHelpers.Adapters+ConversionDescription]
         -80 (-2.61% of base) : 71277.dasm - <WriteHeadersAsync>d__56:MoveNext():this
         -80 (-3.49% of base) : 129731.dasm - Microsoft.CodeAnalysis.VisualBasic.LocalRewriter:RewriteIfStatement(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.BoundStatement,Microsoft.CodeAnalysis.VisualBasic.BoundStatement,bool,System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.VisualBasic.BoundStatement]):Microsoft.CodeAnalysis.VisualBasic.BoundStatement:this
         -75 (-7.04% of base) : 160323.dasm - EncodeHelpers:EncodeKeyTransRecipientInfo(System.Security.Cryptography.Pkcs.CmsRecipient,Internal.Cryptography.Pal.Windows.HeapBlockRetainer):long
         -75 (-5.68% of base) : 12185.dasm - Microsoft.Diagnostics.Tracing.Parsers.MicrosoftWindowsTCPIP.TcpConnectionSummaryArgs:PayloadValue(int):System.Object:this
         -74 (-1.09% of base) : 176656.dasm - R2RTest.BuildFolderSet:WriteBuildStatistics(System.IO.StreamWriter):this

Top method regressions (percentages):
         117 (68.42% of base) : 122797.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxListBuilder:AddRange(Microsoft.CodeAnalysis.SyntaxNode[],int,int):Microsoft.CodeAnalysis.VisualBasic.Syntax.SyntaxListBuilder:this
          25 (64.10% of base) : 72638.dasm - <>c__DisplayClass36_0:<ReadInternal>b__2():this
          10 (62.50% of base) : 190487.dasm - <>c__0`1:<Create>b__0_0(System.Diagnostics.Metrics.LabelInstruction,System.Diagnostics.Metrics.LabelInstruction):int:this
          10 (55.56% of base) : 170639.dasm - <>c:<GetUnreadOptionNames>b__13_1(Internal.CommandLine.ArgumentToken):System.String:this
          10 (55.56% of base) : 115156.dasm - Comparer:Equals(Microsoft.CodeAnalysis.VisualBasic.Symbols.SingleNamespaceDeclaration,Microsoft.CodeAnalysis.VisualBasic.Symbols.SingleNamespaceDeclaration):bool:this
          10 (55.56% of base) : 179149.dasm - PointerHashtable:CompareValueToValue(Internal.TypeSystem.PointerType,Internal.TypeSystem.PointerType):bool:this
          10 (55.56% of base) : 99988.dasm - TimeSpanTokenizer:.ctor(System.ReadOnlySpan`1[System.Char]):this
         313 (52.52% of base) : 94337.dasm - System.Reflection.MethodBase:CheckArguments(byref,System.ReadOnlySpan`1[System.Object],System.Reflection.Binder,int,System.Globalization.CultureInfo,System.RuntimeType[]):System.Span`1[System.Object]:this
          10 (47.62% of base) : 53788.dasm - ArgumentStorage:EmitAddress():this
          10 (47.62% of base) : 53790.dasm - ArgumentStorage:EmitLoad():this
          10 (47.62% of base) : 53789.dasm - ArgumentStorage:EmitStore():this
          10 (45.45% of base) : 190509.dasm - <>c__DisplayClass24_0:<Include>b__0(System.Diagnostics.Metrics.Instrument):bool:this
          10 (40.00% of base) : 166835.dasm - System.Net.HttpListenerRequest:GetChannelBinding():System.Security.Authentication.ExtendedProtection.ChannelBinding:this
          10 (35.71% of base) : 2941.dasm - Microsoft.Diagnostics.Tracing.Ctf.CtfArray:ToString():System.String:this
          10 (35.71% of base) : 168167.dasm - System.CommandLine.Binding.BoundValue:ToString():System.String:this
          10 (34.48% of base) : 61690.dasm - <>c__DisplayClass5_0:<GetPropertyString>b__0():System.Object:this
          10 (33.33% of base) : 178946.dasm - FieldForInstantiatedTypeKeyHashtable:CompareKeyToValue(Internal.TypeSystem.TypeSystemContext+FieldForInstantiatedTypeKey,Internal.TypeSystem.FieldForInstantiatedType):bool:this
          10 (33.33% of base) : 178951.dasm - MethodForInstantiatedTypeKeyHashtable:CompareKeyToValue(Internal.TypeSystem.TypeSystemContext+MethodForInstantiatedTypeKey,Internal.TypeSystem.MethodForInstantiatedType):bool:this
          10 (33.33% of base) : 178934.dasm - MethodForRuntimeDeterminedTypeKeyHashtable:CompareKeyToValue(Internal.TypeSystem.TypeSystemContext+MethodForRuntimeDeterminedTypeKey,Internal.TypeSystem.MethodForRuntimeDeterminedType):bool:this
          10 (32.26% of base) : 178945.dasm - FieldForInstantiatedTypeKeyHashtable:CompareValueToValue(Internal.TypeSystem.FieldForInstantiatedType,Internal.TypeSystem.FieldForInstantiatedType):bool:this

Top method improvements (percentages):
         -36 (-52.94% of base) : 193666.dasm - System.Linq.ParallelQuery`1:.ctor(System.Linq.Parallel.QuerySettings):this
         -39 (-46.43% of base) : 193789.dasm - System.Linq.Parallel.QueryOperator`1:.ctor(bool,System.Linq.Parallel.QuerySettings):this
         -39 (-46.43% of base) : 192933.dasm - System.Linq.Parallel.QueryOperator`1:.ctor(bool,System.Linq.Parallel.QuerySettings):this
         -18 (-46.15% of base) : 38786.dasm - Microsoft.CodeAnalysis.CompilationReference:.ctor(Microsoft.CodeAnalysis.MetadataReferenceProperties):this
         -34 (-45.33% of base) : 193790.dasm - System.Linq.Parallel.QueryOperator`1:.ctor(System.Linq.Parallel.QuerySettings):this
         -34 (-45.33% of base) : 192934.dasm - System.Linq.Parallel.QueryOperator`1:.ctor(System.Linq.Parallel.QuerySettings):this
         -24 (-42.11% of base) : 205345.dasm - EscaperImplementation:.ctor(bool):this
         -37 (-40.66% of base) : 200607.dasm - System.IO.Pipelines.PipeReader:Create(System.Buffers.ReadOnlySequence`1[System.Byte]):System.IO.Pipelines.PipeReader
          -3 (-37.50% of base) : 70963.dasm - System.Net.Http.Http3Connection:get_AbortException():System.Exception:this
          -3 (-37.50% of base) : 171241.dasm - System.Threading.Barrier:get_CurrentPhaseNumber():long:this
         -47 (-35.61% of base) : 37494.dasm - Microsoft.CodeAnalysis.SyntaxTriviaList:Equals(Microsoft.CodeAnalysis.SyntaxTriviaList):bool:this
         -37 (-34.26% of base) : 192880.dasm - System.Linq.Parallel.UnaryQueryOperator`2:.ctor(System.Linq.Parallel.QueryOperator`1[System.__Canon],bool,System.Linq.Parallel.QuerySettings):this
          -6 (-33.33% of base) : 95484.dasm - System.Runtime.InteropServices.MemoryMarshal:GetArrayDataReference(System.Array):byref
          -3 (-33.33% of base) : 98533.dasm - System.Threading.PortableThreadPool:GetMaxThreads():int:this
          -3 (-33.33% of base) : 98535.dasm - System.Threading.PortableThreadPool:GetMinThreads():int:this
         -42 (-33.07% of base) : 190950.dasm - System.Diagnostics.DiagLinkedList`1:.ctor(System.Diagnostics.ActivityEvent):this
         -19 (-30.16% of base) : 38702.dasm - Microsoft.CodeAnalysis.UnresolvedMetadataReference:.ctor(System.String,Microsoft.CodeAnalysis.MetadataReferenceProperties):this
          -9 (-30.00% of base) : 215439.dasm - Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache:.ctor(int,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey):this
          -3 (-30.00% of base) : 203474.dasm - System.Net.Sockets.Socket:get_SafeHandle():System.Net.Sockets.SafeSocketHandle:this
         -20 (-29.41% of base) : 213872.dasm - System.BinaryData:FromBytes(System.ReadOnlyMemory`1[System.Byte]):System.BinaryData

8184 total methods with Code Size differences (6559 improved, 1625 regressed), 14179 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 46088682 (overridden on cmd)
Total bytes of diff: 46025685 (overridden on cmd)
Total bytes of delta: -62997 (-0.14 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         369 : 179587.dasm (50.20% of base)
         203 : 179590.dasm (31.87% of base)
         194 : 16819.dasm (22.27% of base)
         188 : 28960.dasm (6.62% of base)
         169 : 230695.dasm (6.85% of base)
         164 : 16825.dasm (14.05% of base)
         164 : 16842.dasm (14.30% of base)
         151 : 142608.dasm (1.82% of base)
         140 : 145598.dasm (2.49% of base)
         112 : 16836.dasm (12.99% of base)
         107 : 160471.dasm (3.95% of base)
         106 : 119747.dasm (3.12% of base)
          96 : 27908.dasm (3.00% of base)
          94 : 119677.dasm (3.04% of base)
          90 : 41478.dasm (4.21% of base)
          90 : 121728.dasm (13.45% of base)
          89 : 77032.dasm (3.51% of base)
          84 : 73433.dasm (12.52% of base)
          82 : 195296.dasm (2.58% of base)
          82 : 42108.dasm (1.67% of base)

Top file improvements (bytes):
        -900 : 84153.dasm (-1.89% of base)
        -327 : 49384.dasm (-2.77% of base)
        -258 : 67873.dasm (-8.05% of base)
        -226 : 225486.dasm (-4.62% of base)
        -221 : 57591.dasm (-6.33% of base)
        -216 : 49404.dasm (-3.22% of base)
        -215 : 205942.dasm (-1.29% of base)
        -173 : 42597.dasm (-8.35% of base)
        -170 : 69570.dasm (-8.72% of base)
        -167 : 112596.dasm (-7.84% of base)
        -164 : 23341.dasm (-2.20% of base)
        -156 : 71875.dasm (-8.53% of base)
        -153 : 72081.dasm (-2.55% of base)
        -151 : 230767.dasm (-8.43% of base)
        -146 : 227340.dasm (-8.05% of base)
        -146 : 225525.dasm (-8.05% of base)
        -143 : 49077.dasm (-13.49% of base)
        -136 : 71876.dasm (-9.07% of base)
        -136 : 53053.dasm (-2.04% of base)
        -132 : 106931.dasm (-4.97% of base)

13571 total files with Code Size differences (10899 improved, 2672 regressed), 14165 unchanged.

Top method regressions (bytes):
         369 (50.20% of base) : 179587.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:UnionWith(System.Collections.Generic.IEnumerable`1[__Canon]):this
         203 (31.87% of base) : 179590.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:IntersectWith(System.Collections.Generic.IEnumerable`1[__Canon]):this
         194 (22.27% of base) : 16819.dasm - System.SpanHelpers:IndexOfAny(byref,System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],int):int
         188 ( 6.62% of base) : 28960.dasm - Microsoft.CodeAnalysis.CSharp.SymbolDisplayVisitor:AddTypeParameterConstraints(System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.ITypeSymbol, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]):this
         169 ( 6.85% of base) : 230695.dasm - System.ServiceModel.Syndication.AtomPub10ServiceDocumentFormatter:ReadCollection(System.Xml.XmlReader,System.ServiceModel.Syndication.Workspace):System.ServiceModel.Syndication.ResourceCollectionInfo:this
         164 (14.05% of base) : 16825.dasm - System.SpanHelpers:IndexOfAny(byref,System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],int):int
         164 (14.30% of base) : 16842.dasm - System.SpanHelpers:LastIndexOfAny(byref,System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],int):int
         151 ( 1.82% of base) : 142608.dasm - System.Xml.Schema.SchemaCollectionPreprocessor:Preprocess(System.Xml.Schema.XmlSchema,System.String,int):this
         140 ( 2.49% of base) : 145598.dasm - System.Xml.Xsl.XsltOld.HtmlElementProps:CreatePropsTable():System.Collections.Hashtable
         112 (12.99% of base) : 16836.dasm - System.SpanHelpers:LastIndexOfAny(byref,System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],int):int
         107 ( 3.95% of base) : 160471.dasm - Internal.TypeSystem.Ecma.EcmaType:GetClassLayout():Internal.TypeSystem.ClassLayoutMetadata:this
         106 ( 3.12% of base) : 119747.dasm - System.Data.Common.SqlMoneyStorage:Aggregate(System.Int32[],int):System.Object:this
          96 ( 3.00% of base) : 27908.dasm - Microsoft.CodeAnalysis.CSharp.AsyncExceptionHandlerRewriter:VisitTryStatement(Microsoft.CodeAnalysis.CSharp.BoundTryStatement):Microsoft.CodeAnalysis.CSharp.BoundNode:this
          94 ( 3.04% of base) : 119677.dasm - System.Data.Common.SqlDoubleStorage:Aggregate(System.Int32[],int):System.Object:this
          90 ( 4.21% of base) : 41478.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.ConstraintsHelper:CheckConstraints(Microsoft.CodeAnalysis.CSharp.Symbol,Microsoft.CodeAnalysis.CSharp.ConversionsBase,Microsoft.CodeAnalysis.CSharp.Symbols.TypeMap,Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol,Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol,Microsoft.CodeAnalysis.Compilation,Microsoft.CodeAnalysis.ArrayBuilder`1[TypeParameterDiagnosticInfo],byref):bool
          90 (13.45% of base) : 121728.dasm - System.Drawing.Printing.PageSettings:get_PrintableArea():System.Drawing.RectangleF:this
          89 ( 3.51% of base) : 77032.dasm - Microsoft.CodeAnalysis.COFFResourceReader:ReadWin32ResourcesFromCOFF(System.IO.Stream):Microsoft.Cci.ResourceSection
          84 (12.52% of base) : 73433.dasm - DiagnosticRewriter:Rewrite(Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.CompilationUnitSyntax,Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.IfDirectiveTriviaSyntax, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.RegionDirectiveTriviaSyntax, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],bool,Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.ExternalSourceDirectiveTriviaSyntax,Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.Parser):Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.CompilationUnitSyntax
          82 ( 2.58% of base) : 195296.dasm - <ConstructResponseAsync>d__57:MoveNext():this
          82 ( 1.67% of base) : 42108.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.ConstantEvaluationHelpers:OrderGraph(System.Collections.Generic.Dictionary`2[[Microsoft.CodeAnalysis.CSharp.Symbols.SourceFieldSymbolWithSyntaxReference, Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.CodeAnalysis.CSharp.Symbols.ConstantEvaluationHelpers+Node`1[[Microsoft.CodeAnalysis.CSharp.Symbols.SourceFieldSymbolWithSyntaxReference, Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.ArrayBuilder`1[FieldInfo])

Top method improvements (bytes):
        -900 (-1.89% of base) : 84153.dasm - Microsoft.Diagnostics.Tracing.CtfTraceEventSource:InitEventMap():System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.Diagnostics.Tracing.ETWMapping, Microsoft.Diagnostics.Tracing.TraceEvent, Version=2.0.65.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]
        -327 (-2.77% of base) : 49384.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:BindFieldAndPropertyInitializers(Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol,System.Collections.Immutable.ImmutableArray`1[ImmutableArray`1],Microsoft.CodeAnalysis.VisualBasic.Symbols.SynthesizedInteractiveInitializerMethod,Microsoft.CodeAnalysis.DiagnosticBag):System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.VisualBasic.BoundInitializer, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]
        -258 (-8.05% of base) : 67873.dasm - Microsoft.CodeAnalysis.VisualBasic.OverloadResolution:OperatorInvocationOverloadResolution(Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.Binder,bool,bool,byref):OverloadResolutionResult
        -226 (-4.62% of base) : 225486.dasm - System.Security.Cryptography.Asn1.GeneralNameAsn:DecodeCore(byref,System.ReadOnlyMemory`1[Byte],byref)
        -221 (-6.33% of base) : 57591.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.Scanner:ScanDateLiteral(Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.SyntaxList`1[[Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.VisualBasicSyntaxNode, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]):Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.SyntaxToken:this
        -216 (-3.22% of base) : 49404.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:BindSymbolAccess(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.LookupResult,int,Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeArgumentListSyntax,int,Microsoft.CodeAnalysis.DiagnosticBag):Microsoft.CodeAnalysis.VisualBasic.BoundExpression:this
        -215 (-1.29% of base) : 205942.dasm - System.Management.ManagementClassGenerator:GenerateTypeConverterClass():System.CodeDom.CodeTypeDeclaration:this
        -173 (-8.35% of base) : 42597.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:HasInstanceData(Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax):bool
        -170 (-8.72% of base) : 69570.dasm - Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter:VisitToken(Microsoft.CodeAnalysis.SyntaxToken):Microsoft.CodeAnalysis.SyntaxToken:this
        -167 (-7.84% of base) : 112596.dasm - Data:InitializeForEvaluation(Microsoft.Build.Evaluation.IToolsetProvider,Microsoft.Build.Shared.FileSystem.IFileSystem):this
        -164 (-2.20% of base) : 23341.dasm - Microsoft.CodeAnalysis.CSharp.Imports:FromSyntax(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode,Microsoft.CodeAnalysis.CSharp.InContainerBinder,Roslyn.Utilities.ConsList`1[[Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],bool):Microsoft.CodeAnalysis.CSharp.Imports
        -156 (-8.53% of base) : 71875.dasm - TypeBinder:BindTypeOrAliasSyntax(Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeSyntax,Microsoft.CodeAnalysis.VisualBasic.Binder,Microsoft.CodeAnalysis.DiagnosticBag,bool,bool,bool):Microsoft.CodeAnalysis.VisualBasic.Symbol
        -153 (-2.55% of base) : 72081.dasm - AnonymousDelegatePublicSymbol:.ctor(Microsoft.CodeAnalysis.VisualBasic.Symbols.AnonymousTypeManager,Microsoft.CodeAnalysis.VisualBasic.Symbols.AnonymousTypeDescriptor):this
        -151 (-8.43% of base) : 230767.dasm - System.ServiceModel.Syndication.Rss20FeedFormatter:ReadMediaEnclosure(System.Xml.XmlReader,System.Uri):System.ServiceModel.Syndication.SyndicationLink:this
        -146 (-8.05% of base) : 227340.dasm - System.Security.Cryptography.Asn1.PssParamsAsn:Encode(System.Formats.Asn1.AsnWriter,System.Formats.Asn1.Asn1Tag):this
        -146 (-8.05% of base) : 225525.dasm - System.Security.Cryptography.Asn1.PssParamsAsn:Encode(System.Formats.Asn1.AsnWriter,System.Formats.Asn1.Asn1Tag):this
        -143 (-13.49% of base) : 49077.dasm - Microsoft.CodeAnalysis.VisualBasic.Binder:BindRemoveNamespaceAttributesInvocation(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode,Microsoft.CodeAnalysis.VisualBasic.BoundExpression,Microsoft.CodeAnalysis.VisualBasic.BoundRValuePlaceholder,Microsoft.CodeAnalysis.VisualBasic.BoundRValuePlaceholder,byref,byref,Microsoft.CodeAnalysis.DiagnosticBag):Microsoft.CodeAnalysis.VisualBasic.BoundExpression:this
        -136 (-2.04% of base) : 53053.dasm - Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol:BindSingleHandlesClause(Microsoft.CodeAnalysis.VisualBasic.Syntax.HandlesClauseItemSyntax,Microsoft.CodeAnalysis.VisualBasic.Binder,Microsoft.CodeAnalysis.DiagnosticBag,Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Symbol, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Symbol, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.ArrayBuilder`1[[Microsoft.CodeAnalysis.VisualBasic.Symbol, Microsoft.CodeAnalysis.VisualBasic, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],byref):Microsoft.CodeAnalysis.VisualBasic.HandledEvent:this
        -136 (-9.07% of base) : 71876.dasm - TypeBinder:NotFound(Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeSyntax,System.String,Microsoft.CodeAnalysis.VisualBasic.Binder,Microsoft.CodeAnalysis.DiagnosticBag,bool):Microsoft.CodeAnalysis.DiagnosticInfo
        -132 (-4.97% of base) : 106931.dasm - <ReadFromAsync>d__3:MoveNext():this

Top method regressions (percentages):
          15 (187.50% of base) : 164982.dasm - Microsoft.Extensions.DependencyModel.EnvironmentWrapper:GetAppContextData(System.String):System.Object:this
          25 (67.57% of base) : 156309.dasm - <>c__DisplayClass36_0:<ReadInternal>b__2():this
           8 (66.67% of base) : 120287.dasm - System.Drawing.CharacterRange:GetHashCode():int:this
           8 (66.67% of base) : 195322.dasm - System.Drawing.Point:GetHashCode():int:this
           8 (66.67% of base) : 195453.dasm - System.Drawing.Size:GetHashCode():int:this
           8 (66.67% of base) : 235551.dasm - System.Text.RegularExpressions.Symbolic.SymbolicMatch:GetHashCode():int:this
           8 (61.54% of base) : 79314.dasm - Microsoft.CodeAnalysis.Text.TextLine:get_SpanIncludingLineBreak():Microsoft.CodeAnalysis.Text.TextSpan:this
         369 (50.20% of base) : 179587.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:UnionWith(System.Collections.Generic.IEnumerable`1[__Canon]):this
           7 (50.00% of base) : 224410.dasm - System.Security.Cryptography.CryptoPool:Return(System.ArraySegment`1[Byte])
           7 (50.00% of base) : 226880.dasm - System.Security.Cryptography.CryptoPool:Return(System.ArraySegment`1[Byte])
           7 (50.00% of base) : 228422.dasm - System.Security.Cryptography.CryptoPool:Return(System.ArraySegment`1[Byte])
           7 (50.00% of base) : 225368.dasm - System.Security.Cryptography.CryptoPool:Return(System.ArraySegment`1[Byte])
           7 (46.67% of base) : 120423.dasm - System.Drawing.Graphics:DrawImageUnscaled(System.Drawing.Image,System.Drawing.Rectangle):this
          10 (45.45% of base) : 216285.dasm - System.Reflection.Context.Projection.ProjectingManifestResourceInfo:get_ReferencedAssembly():System.Reflection.Assembly:this
           7 (43.75% of base) : 108874.dasm - Microsoft.Build.Experimental.Graph.ProjectGraph:<.ctor>b__26_0():System.Collections.Generic.IReadOnlyCollection`1[[Microsoft.Build.Experimental.Graph.ProjectGraphNode, Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]:this
           7 (43.75% of base) : 164253.dasm - Microsoft.Extensions.Configuration.ConfigurationSection:GetChildren():System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.Configuration.IConfigurationSection, Microsoft.Extensions.Configuration.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]:this
           7 (43.75% of base) : 3696.dasm - Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter:ConvVarToLinq(Microsoft.FSharp.Quotations.FSharpVar):System.Linq.Expressions.ParameterExpression
           7 (43.75% of base) : 122968.dasm - System.Linq.Expressions.ConstantCheck:AnalyzeTypeIs(System.Linq.Expressions.TypeBinaryExpression):int
           7 (43.75% of base) : 124681.dasm - System.Linq.Expressions.DynamicExpression:System.Linq.Expressions.IDynamicExpression.CreateCallSite():System.Object:this
           7 (43.75% of base) : 143576.dasm - System.Xml.Schema.XmlSchemaValidator:BuildElementName(System.Xml.XmlQualifiedName):System.String

Top method improvements (percentages):
         -63 (-88.73% of base) : 216408.dasm - System.Reflection.Context.Projection.Projector:Project(long,System.Func`2[Int64,Int64]):long:this
         -59 (-88.06% of base) : 216405.dasm - System.Reflection.Context.Projection.Projector:Project(int,System.Func`2[Int32,Int32]):int:this
         -68 (-86.08% of base) : 216406.dasm - System.Reflection.Context.Projection.Projector:Project(double,System.Func`2[Double,Double]):double:this
         -61 (-84.72% of base) : 216403.dasm - System.Reflection.Context.Projection.Projector:Project(ubyte,System.Func`2[Byte,Byte]):ubyte:this
         -60 (-83.33% of base) : 216404.dasm - System.Reflection.Context.Projection.Projector:Project(short,System.Func`2[Int16,Int16]):short:this
         -20 (-80.00% of base) : 233579.dasm - System.Text.Json.Nodes.JsonArray:.ctor(System.Nullable`1[JsonNodeOptions]):this
         -22 (-70.97% of base) : 233802.dasm - System.Text.Json.Nodes.JsonValue`1[Byte][System.Byte]:.ctor(ubyte,System.Nullable`1[JsonNodeOptions]):this
         -22 (-70.97% of base) : 233806.dasm - System.Text.Json.Nodes.JsonValue`1[Int32][System.Int32]:.ctor(int,System.Nullable`1[JsonNodeOptions]):this
         -22 (-70.97% of base) : 233763.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Byte][System.Byte]:.ctor(ubyte,System.Nullable`1[JsonNodeOptions]):this
         -22 (-70.97% of base) : 233765.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Int32][System.Int32]:.ctor(int,System.Nullable`1[JsonNodeOptions]):this
         -22 (-68.75% of base) : 233804.dasm - System.Text.Json.Nodes.JsonValue`1[Int16][System.Int16]:.ctor(short,System.Nullable`1[JsonNodeOptions]):this
         -22 (-68.75% of base) : 233812.dasm - System.Text.Json.Nodes.JsonValue`1[Int64][System.Int64]:.ctor(long,System.Nullable`1[JsonNodeOptions]):this
         -22 (-68.75% of base) : 233764.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Int16][System.Int16]:.ctor(short,System.Nullable`1[JsonNodeOptions]):this
         -22 (-68.75% of base) : 233768.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Int64][System.Int64]:.ctor(long,System.Nullable`1[JsonNodeOptions]):this
          -9 (-64.29% of base) : 12865.dasm - Microsoft.FSharp.Core.Operators:Snd(System.Tuple`2[__Canon,Nullable`1]):System.Nullable`1[Int32]
          -9 (-64.29% of base) : 12866.dasm - Microsoft.FSharp.Core.Operators:Snd(System.Tuple`2[Byte,Nullable`1]):System.Nullable`1[Int32]
         -21 (-60.00% of base) : 233808.dasm - System.Text.Json.Nodes.JsonValue`1[Double][System.Double]:.ctor(double,System.Nullable`1[JsonNodeOptions]):this
         -21 (-60.00% of base) : 233766.dasm - System.Text.Json.Nodes.JsonValueNotTrimmable`1[Double][System.Double]:.ctor(double,System.Nullable`1[JsonNodeOptions]):this
         -35 (-59.32% of base) : 9949.dasm - groupByRefType@438-3[__Canon,Nullable`1][System.__Canon,System.Nullable`1[System.Int32]]:Invoke(System.__Canon):StructBox`1[Nullable`1]:this
         -35 (-59.32% of base) : 9954.dasm - groupByRefType@438-3[Int32,Nullable`1][System.Int32,System.Nullable`1[System.Int32]]:Invoke(int):StructBox`1[Nullable`1]:this

13571 total methods with Code Size differences (10899 improved, 2672 regressed), 14165 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries_tests.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 112303696 (overridden on cmd)
Total bytes of diff: 112203489 (overridden on cmd)
Total bytes of delta: -100207 (-0.09 % of base)
    diff is an improvement.
    relative diff is a regression.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
         464 : 119499.dasm (20.25% of base)
         299 : 181727.dasm (6.29% of base)
         299 : 67727.dasm (6.29% of base)
         289 : 181722.dasm (6.11% of base)
         289 : 67722.dasm (6.11% of base)
         284 : 146790.dasm (6.03% of base)
         268 : 70257.dasm (6.21% of base)
         229 : 145795.dasm (7.02% of base)
         219 : 273915.dasm (100.00% of base)
         203 : 67587.dasm (8.48% of base)
         203 : 67588.dasm (8.48% of base)
         185 : 267065.dasm (18.19% of base)
         183 : 202332.dasm (13.65% of base)
         183 : 202340.dasm (13.65% of base)
         175 : 224350.dasm (19.49% of base)
         167 : 338316.dasm (2.74% of base)
         149 : 238270.dasm (5.01% of base)
         145 : 168517.dasm (11.15% of base)
         132 : 315766.dasm (5.47% of base)
         132 : 315767.dasm (5.47% of base)

Top file improvements (bytes):
        -612 : 152902.dasm (-52.80% of base)
        -612 : 152903.dasm (-52.67% of base)
        -612 : 152904.dasm (-52.67% of base)
        -612 : 152905.dasm (-52.67% of base)
        -597 : 25024.dasm (-2.11% of base)
        -469 : 273521.dasm (-7.51% of base)
        -357 : 340053.dasm (-7.64% of base)
        -338 : 332984.dasm (-32.22% of base)
        -338 : 332986.dasm (-29.37% of base)
        -299 : 118849.dasm (-9.89% of base)
        -280 : 201906.dasm (-7.85% of base)
        -240 : 121757.dasm (-10.26% of base)
        -239 : 118773.dasm (-9.09% of base)
        -238 : 277593.dasm (-1.95% of base)
        -234 : 93162.dasm (-8.45% of base)
        -223 : 151902.dasm (-15.83% of base)
        -216 : 120854.dasm (-9.82% of base)
        -216 : 173151.dasm (-6.54% of base)
        -210 : 173549.dasm (-3.20% of base)
        -204 : 118260.dasm (-9.47% of base)

24990 total files with Code Size differences (17819 improved, 7171 regressed), 47511 unchanged.

Top method regressions (bytes):
         464 (20.25% of base) : 119499.dasm - Microsoft.CodeAnalysis.CSharp.Classification.Worker:ClassifyDirectiveTrivia(Microsoft.CodeAnalysis.CSharp.Syntax.DirectiveTriviaSyntax,bool):this
         299 ( 6.29% of base) : 181727.dasm - System.Tests.StringTests:WhiteSpaceInMiddleTrim_Memory()
         299 ( 6.29% of base) : 67727.dasm - System.Tests.StringTests:WhiteSpaceInMiddleTrim_Memory()
         289 ( 6.11% of base) : 181722.dasm - System.Tests.StringTests:NoWhiteSpaceTrim_Memory()
         289 ( 6.11% of base) : 67722.dasm - System.Tests.StringTests:NoWhiteSpaceTrim_Memory()
         284 ( 6.03% of base) : 146790.dasm - System.Data.Tests.DataTableTest4:XmlTest15():this
         268 ( 6.21% of base) : 70257.dasm - System.Tests.TimeZoneInfoTests:GetAmbiguousTimeOffsets_Invalid()
         229 ( 7.02% of base) : 145795.dasm - System.Data.Tests.DataColumnCollectionTest2:Add():this
         219 (100.00% of base) : 273915.dasm - <>c:<TestAddingSamplerTagsFromMultipleListeners>b__21_3(byref):int:this
         203 ( 8.48% of base) : 67588.dasm - System.Runtime.CompilerServices.Tests.DefaultInterpolatedStringHandlerTests:<AppendFormatted_ValueTypes>g__Test|10_0(short)
         203 ( 8.48% of base) : 67587.dasm - System.Runtime.CompilerServices.Tests.DefaultInterpolatedStringHandlerTests:<AppendFormatted_ValueTypes>g__Test|10_0(ubyte)
         185 (18.19% of base) : 267065.dasm - System.Collections.Specialized.Tests.NameValueCollectionAddNameValueCollectionTests:Add_NameValueCollection_WithNullKeys():this
         183 (13.65% of base) : 202332.dasm - System.Threading.Tasks.Tests.Status.TaskCompletionSourceTests:Ctor_ArgumentsRoundtrip():this
         183 (13.65% of base) : 202340.dasm - System.Threading.Tasks.Tests.Status.TaskCompletionSourceTResultTests:Ctor_ArgumentsRoundtrip():this
         175 (19.49% of base) : 224350.dasm - FluentAssertions.Primitives.SimpleTimeSpanAssertions:BeCloseTo(System.TimeSpan,int,System.String,System.Object[]):FluentAssertions.AndConstraint`1[[FluentAssertions.Primitives.SimpleTimeSpanAssertions, FluentAssertions.Core, Version=4.19.4.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a]]:this
         167 ( 2.74% of base) : 338316.dasm - CoreXml.Test.XLinq.ReaderDiffNSAware:CompareNamespaceAware(System.Xml.XmlReader,System.Xml.XmlReader)
         149 ( 5.01% of base) : 238270.dasm - <DeletingFilesThatRedefineKeysWithReload>d__38:MoveNext():this
         145 (11.15% of base) : 168517.dasm - System.SpanTests.ReadOnlySpanTests:SequenceCompareToSingleMismatch()
         132 ( 5.47% of base) : 315766.dasm - System.Tests.UInt64Tests:TryFormat(long,System.String,System.IFormatProvider,System.String)
         132 ( 5.47% of base) : 70351.dasm - System.Tests.UInt64Tests:TryFormat(long,System.String,System.IFormatProvider,System.String)

Top method improvements (bytes):
        -612 (-52.80% of base) : 152902.dasm - System.Drawing.Tests.TextureBrushTests:WrapMode_Tile_ReturnsExpected():this
        -612 (-52.67% of base) : 152903.dasm - System.Drawing.Tests.TextureBrushTests:WrapMode_TileFlipX_ReturnsExpected():this
        -612 (-52.67% of base) : 152905.dasm - System.Drawing.Tests.TextureBrushTests:WrapMode_TileFlipXY_ReturnsExpected():this
        -612 (-52.67% of base) : 152904.dasm - System.Drawing.Tests.TextureBrushTests:WrapMode_TileFlipY_ReturnsExpected():this
        -597 (-2.11% of base) : 25024.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.overloadResolution.Methods.Oneclass2methods.literals01.literals01.A:MainMethod():int
        -469 (-7.51% of base) : 273521.dasm - System.Diagnostics.Tests.ActivityTests:ActivityTraceFlagsTests():this
        -357 (-7.64% of base) : 340053.dasm - System.Xml.Tests.ToTypeTests:TestInvalid(System.String[],System.String,System.String[]):int:this
        -338 (-32.22% of base) : 332984.dasm - System.Threading.Tasks.Tests.ValueTaskTests:Generic_OperatorEquals():this
        -338 (-29.37% of base) : 332986.dasm - System.Threading.Tasks.Tests.ValueTaskTests:Generic_OperatorNotEquals():this
        -299 (-9.89% of base) : 118849.dasm - Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTokenExtensions:IsBeginningOfGlobalStatementContext(Microsoft.CodeAnalysis.SyntaxToken):bool
        -280 (-7.85% of base) : 201906.dasm - System.Threading.Tasks.Tests.TaskAwaiterTests:AwaiterAndAwaitableEquality()
        -240 (-10.26% of base) : 121757.dasm - Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery.SyntaxTreeExtensions:IsQueryIntoClauseContext(Microsoft.CodeAnalysis.SyntaxTree,int,Microsoft.CodeAnalysis.SyntaxToken,System.Threading.CancellationToken):bool
        -239 (-9.09% of base) : 118773.dasm - Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTreeExtensions:IsAtEndOfPattern(Microsoft.CodeAnalysis.SyntaxTree,Microsoft.CodeAnalysis.SyntaxToken,int):bool
        -238 (-1.95% of base) : 277593.dasm - System.Formats.Asn1.Tests.Writer.ComprehensiveWriteTest:WriteMicrosoftDotComCert()
        -234 (-8.45% of base) : 93162.dasm - System.Text.Json.Nodes.Tests.OperatorTests:ExplicitOperators_FromNullableValues()
        -223 (-15.83% of base) : 151902.dasm - System.Drawing.Drawing2D.Tests.LinearGradientBrushTests:InterpolationColors_SetWithExistingInterpolationColors_OverwritesInterpolationColors():this
        -216 (-9.82% of base) : 120854.dasm - Microsoft.CodeAnalysis.VisualBasic.Classification.ClassificationHelpers:ClassifyIdentifierSyntax(Microsoft.CodeAnalysis.SyntaxToken):System.String
        -216 (-6.54% of base) : 173151.dasm - System.Net.Http.Tests.HttpRequestHeadersTest:AddHeaders_SpecialHeaderValuesOnDestinationNotOnSource_NotCopied():this
        -210 (-3.20% of base) : 173549.dasm - System.Net.Http.Tests.HttpRuleParserTest:GetCommentLength_SetOfValidComments_AllConsideredValid():this
        -204 (-9.47% of base) : 118260.dasm - Microsoft.CodeAnalysis.CSharp.Formatting.FormattingHelpers:IsParenInArgumentList(Microsoft.CodeAnalysis.SyntaxToken):bool

Top method regressions (percentages):
          15 (1,500.00% of base) : 319485.dasm - <>c:<AppendPrivatePath>b__37_0():this
          15 (1,500.00% of base) : 319486.dasm - <>c:<ClearPrivatePath>b__38_0():this
          15 (1,500.00% of base) : 319437.dasm - <>c:<ClearShadowCopyPath>b__39_0():this
          15 (1,500.00% of base) : 319438.dasm - <>c:<SetCachePath>b__40_0():this
          15 (1,500.00% of base) : 319439.dasm - <>c:<SetShadowCopyFiles>b__41_0():this
          15 (1,500.00% of base) : 319440.dasm - <>c:<SetShadowCopyPath>b__42_0():this
          15 (1,500.00% of base) : 318461.dasm - System.Tests.AppDomainTests:DynamicDirectory_Null():this
          15 (1,500.00% of base) : 318454.dasm - System.Tests.AppDomainTests:RelativeSearchPath_Is_Null():this
          51 (463.64% of base) : 32196.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass001.genericbaseclass001.Test:MainMethod(System.String[]):int
          34 (309.09% of base) : 32268.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.backwardscompatible.dynamictypedeclared021.dynamictypedeclared021.App:MainMethod(System.String[]):int
          34 (309.09% of base) : 32172.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass003.genericbaseclass003.NS.Test:MainMethod(System.String[]):int
          34 (309.09% of base) : 32165.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass004.genericbaseclass004.NS.Test:MainMethod(System.String[]):int
          34 (309.09% of base) : 32158.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass005.genericbaseclass005.NS.Test:MainMethod(System.String[]):int
          17 (188.89% of base) : 144001.dasm - System.ComponentModel.Design.Serialization.Tests.DesignerLoaderTests:Flush_Invoke_Nop():this
          17 (188.89% of base) : 143290.dasm - System.ComponentModel.Tests.LicenseContextTests:GetSavedLicenseKey_Invoke_ReturnsNull():this
          17 (188.89% of base) : 143291.dasm - System.ComponentModel.Tests.LicenseContextTests:GetService_Invoke_ReturnsNull():this
          17 (188.89% of base) : 143292.dasm - System.ComponentModel.Tests.LicenseContextTests:SetSavedLicenseKey_Invoke_Nop():this
          17 (188.89% of base) : 50179.dasm - System.Linq.Expressions.Tests.ExpressionTests:DefaultReducesToSame():this
          17 (188.89% of base) : 53253.dasm - System.Linq.Expressions.Tests.VisitorTests:VisitNullDefaultsToReturnNull():this
          17 (188.89% of base) : 187911.dasm - System.Runtime.Serialization.Xml.Tests.XmlDictionaryReaderTests:Close_DerivedReader_Success()

Top method improvements (percentages):
        -129 (-91.49% of base) : 320106.dasm - System.Runtime.InteropServices.Tests.CULongTests:Ctor_NUInt_LargeValue():this
        -124 (-91.18% of base) : 320117.dasm - System.Runtime.InteropServices.Tests.CLongTests:Ctor_NInt_LargeValue():this
         -30 (-90.91% of base) : 23629.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.unaryOperators.is002.is002.Test:MainMethod(System.String[]):int
         -30 (-90.91% of base) : 23627.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.statements.unaryOperators.is003.is003.Test:MainMethod(System.String[]):int
          -8 (-88.89% of base) : 19857.dasm - System.Collections.Tests.HashSet_Generic_Tests`1[Byte][System.Byte]:CanBeCastedToISet():this
          -8 (-88.89% of base) : 140355.dasm - System.ComponentModel.Composition.ImportingConstructorAttributeTests:Constructor_ShouldNotThrow():this
          -8 (-88.89% of base) : 140361.dasm - System.ComponentModel.Composition.MetadataAttributeAttributeTests:Constructor_ShouldNotThrow():this
          -8 (-88.89% of base) : 275489.dasm - System.Diagnostics.SymbolStore.Tests.SymDocumentTypeTests:Ctor_Default():this
          -8 (-88.89% of base) : 275491.dasm - System.Diagnostics.SymbolStore.Tests.SymLanguageTypeTests:Ctor_Default():this
          -8 (-88.89% of base) : 275494.dasm - System.Diagnostics.SymbolStore.Tests.SymLanguageVendorTests:Ctor_Default():this
          -8 (-88.89% of base) : 327731.dasm - System.Text.Tests.DecoderCtor:PosTest1():this
          -8 (-88.89% of base) : 327807.dasm - System.Text.Tests.EncoderCtor:PosTest1():this
          -8 (-88.89% of base) : 345521.dasm - XmlSerializerTests:XmlSerializationGeneratedCodeTest()
         -46 (-88.46% of base) : 111676.dasm - genDictionary@1026-1[Double][System.Double]:Invoke(double):bool:this
         -46 (-88.46% of base) : 111677.dasm - genDictionary@1026-1[Vector`1][System.Numerics.Vector`1[System.Single]]:Invoke(System.Numerics.Vector`1[Single]):bool:this
         -35 (-85.37% of base) : 111678.dasm - genDictionary@1026-1[Int64][System.Int64]:Invoke(long):bool:this
         -34 (-85.00% of base) : 111673.dasm - genDictionary@1026-1[Byte][System.Byte]:Invoke(ubyte):bool:this
         -34 (-85.00% of base) : 111674.dasm - genDictionary@1026-1[Int16][System.Int16]:Invoke(short):bool:this
         -33 (-84.62% of base) : 111675.dasm - genDictionary@1026-1[Int32][System.Int32]:Invoke(int):bool:this
         -20 (-80.00% of base) : 224205.dasm - FluentAssertions.Primitives.BooleanAssertions:.ctor(System.Nullable`1[Boolean]):this

24990 total methods with Code Size differences (17819 improved, 7171 regressed), 47511 unchanged.

```

</details>

--------------------------------------------------------------------------------

**Comment by AndyAyersMS** [comment]
### aspnet regressions

* 14607: extra CSE, which is not enregistered.
```
; ThreadPoolWorkQueue:Dispatch():bool
;; BEFORE
;  Total bytes of code 1902, prolog size 31, PerfScore 29027.23, instruction count 490

;; AFTER
;  V104 cse2        [V104,T32] (  3,   8.29)     int  ->  [rsp+3CH]   spill-single-def "CSE - moderate"
;  Total bytes of code 1993, prolog size 34, PerfScore 28843.80, instruction count 496
```

* 16374: no longer enregister tmp15 (T00 ==> this is the highest weight local var!)
```
;; String:IndexOfAny(ref):int:this

;; BEFORE
;  V17 tmp15        [V17,T00] ( 17,  9   )   byref  ->   r9         single-def "Inline stloc first use temp"
;  Total bytes of code 286, prolog size 4, PerfScore 76.48, instruction count 70

;; AFTER
;  V17 tmp15        [V17,T00] ( 17,  9   )   byref  ->  [rsp+38H]   single-def "Inline stloc first use temp"
;  Total bytes of code 330, prolog size 4, PerfScore 83.88, instruction count 84
```

* 28733: extra CSE; lsra makes different choices, 3 fewer temps enregistered
```
;; HttpTransformer:TransformRequestAsync(HttpContext,HttpRequestMessage,String):ValueTask:this

;; BEFORE
;  V50 tmp38        [V50,T48] (  2,  2.46)     ref  ->  r13         class-hnd single-def "Inlining Arg"
;  V67 tmp55        [V67,T50] (  2,  2.46)     ref  ->  r14         class-hnd single-def "Inlining Arg"
;  V85 tmp73        [V85,T52] (  2,  2.46)     ref  ->  r15         class-hnd single-def "Inlining Arg"
;  Total bytes of code 1888, prolog size 80, PerfScore 464.97, instruction count 433

;; AFTER
;  V50 tmp38        [V50,T48] (  2,  2.46)     ref  ->  [rbp-98H]   class-hnd spill-single-def "Inlining Arg"
;  V67 tmp55        [V67,T50] (  2,  2.46)     ref  ->  [rbp-A0H]   class-hnd spill-single-def "Inlining Arg"
;  V85 tmp73        [V85,T52] (  2,  2.46)     ref  ->  [rbp-A8H]   class-hnd spill-single-def "Inlining Arg"
;  V117 cse3        [V117,T26] ( 10,  4.00)    long  ->  r14         "CSE - moderate"
;  Total bytes of code 1941, prolog size 80, PerfScore 467.06, instruction count 437
```

* 34337: we clone a loop now where we didn't before; forward sub here enhances the ability of the cloner to prove loop invariance.
```
; MethodBase:CheckArguments(byref,ReadOnlySpan`1,Binder,int,CultureInfo,ref):Span`1:this

;; BEFORE
Considering loop L00 to clone for optimizations.
Checking loop L00 for optimization candidates
Found ArrIndex at BB09 STMT00012 tree [000347] which is equivalent to: V07[V10], bounds check nodes: [000347]
V07 is not loop invariant
Found ArrIndex at BB12 STMT00018 tree [000368] which is equivalent to: V09[V10], bounds check nodes: [000368]
V09 is not loop invariant
Found ArrIndex at BB13 STMT00019 tree [000411] which is equivalent to: V09[V10], bounds check nodes: [000411]
V09 is not loop invariant

; Total bytes of code 528, prolog size 16, PerfScore 312.80, instruction count 131

;; AFTER
Considering loop L00 to clone for optimizations.
Checking loop L00 for optimization candidates
Found ArrIndex at BB09 STMT00012 tree [000347] which is equivalent to: V07[V10], bounds check nodes: [000347]
Loop L00 can be cloned for ArrIndex V07[V10] on dim 0
Found ArrIndex at BB12 STMT00018 tree [000368] which is equivalent to: V09[V10], bounds check nodes: [000368]
V09 is not loop invariant
Found ArrIndex at BB13 STMT00019 tree [000411] which is equivalent to: V09[V10], bounds check nodes: [000411]
V09 is not loop invariant

; Total bytes of code 887, prolog size 23, PerfScore 354.12, instruction count 214
```

* 62157: unenregistered high-weight CSE, plus some LSRA temps
```
;; TextEncoder:EncodeToNewString(ReadOnlySpan`1,int):String:this

;; BEFORE
;  Total bytes of code 834, prolog size 95, PerfScore 220.51, instruction count 213

;; AFTER
;  V171 cse1        [V171,T15] (  5,  4   )    long  ->  [rbp+18H]   spill-single-def "CSE - moderate"
;  TEMP_02                                     ref  ->  [rbp+0x08]
;  TEMP_01                                    long  ->  [rbp+0x00]
;  Total bytes of code 894, prolog size 112, PerfScore 228.69, instruction count 224
```

* 65753: extra cse, highest-weight local not enregistered:
```
;; CancellationTokenSource:Register(Delegate,Object,SynchronizationContext,ExecutionContext):CancellationTokenRegistration:this

;; BEFORE
;  V07 loc1         [V07,T00] ( 28, 13.69)     ref  ->  r13         class-hnd
;  Total bytes of code 925, prolog size 45, PerfScore 203.40, instruction count 282

;; AFTER
;  V07 loc1         [V07,T00] ( 28, 13.69)     ref  ->  [rbp-50H]   class-hnd
;  V28 cse0         [V28,T08] ( 10,  3.00)   byref  ->  registers   "CSE - aggressive"
;  Total bytes of code 972, prolog size 48, PerfScore 214.26, instruction count 292
```

**Comment by AndyAyersMS** [comment]
### benchmarks regressions

* 324: extra loop cloning (same `MethodBase` as we saw in method 34337 in aspnet (above))

* 2610: same issue as 40796 (below)
```
;; System.String:GetHashCode():int:this

;; BEFORE
;  Total bytes of code 29, prolog size 0, PerfScore 8.40, instruction count 7

;; AFTER
;  Total bytes of code 36, prolog size 0, PerfScore 10.60, instruction count 8
```
* 8851: same issue as 40796 (below)

* 34791: forward sub lowers cost estimate for loop inversions, so we do more of them. After that it's not clear what happens -- would take some time to really understand.
Some redundant branch opts don't kick in in the after version, this seems to leave some throw code around.
```
;; Microsoft.CodeAnalysis.CSharp.Symbols.AnonymousTypeManager:AssignTemplatesNamesAndCompile(Microsoft.CodeAnalysis.CSharp.MethodCompiler,Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder,Microsoft.CodeAnalysis.DiagnosticBag):this

;; BEFORE
Duplication of loop condition [000283] is not done, because the cost of duplication (35) is greater than 34,
   loopIterations =   8.000, optInvertTotalInfo.sharedStaticHelperCount >= 0, validProfileWeights = false


STMT00149 ( INL23 @ 0x00E[E-] ... ??? ) <- INLRT @ 0x144[E-]
 [000619] -A---+------              *  ASG       int   
 [000618] D----+-N----              +--*  LCL_VAR   int    V49 tmp26        
 [000613] -----+------              \--*  LCL_VAR   int    V88 tmp65        

STMT00151 ( INL23 @ 0x00E[E-] ... ??? ) <- INLRT @ 0x144[E-]
 [000629] -A---+------              *  ASG       ref   
 [000628] D----+-N----              +--*  LCL_VAR   ref    V50 tmp27        
 [000616] -----+------              \--*  LCL_VAR   ref    V87 tmp64        

STMT00152 ( INL24 @ 0x000[E-] ... ??? ) <- INL23 @ 0x00E[E-] <- INLRT @ 0x144[E-]
 [000634] -A-XG+------              *  ASG       ref   
 [000633] D----+-N----              +--*  LCL_VAR   ref    V51 tmp28        
 [000625] ---XG+------              \--*  IND       ref   
 [001270] -----+------                 \--*  ADD       byref 
 [000624] -----+------                    +--*  LCL_VAR   ref    V87 tmp64        
 [001269] -----+------                    \--*  CNS_INT   long   8 field offset Fseq[_builder]

STMT00076 ( 0x144[E-] ... ??? )
 [000283] ---XG+------              *  JTRUE     void  
 [000622] J--XG+-N----              \--*  LT        int   
 [000620] -----+------                 +--*  LCL_VAR   int    V88 tmp65        
 [000632] ---XG+------                 \--*  IND       int   
 [001272] -----+------                    \--*  ADD       byref 
 [000631] -----+------                       +--*  LCL_VAR   ref    V51 tmp28        
 [001271] -----+------                       \--*  CNS_INT   long   16 field offset Fseq[hackishFieldName]

; Total bytes of code 1501, prolog size 37, PerfScore 1552.73, instruction count 338

;; AFTER
Duplication of loop condition [000283] is performed, because the cost of duplication (20) is less or equal than 34,
   loopIterations =   8.000, optInvertTotalInfo.sharedStaticHelperCount >= 0, validProfileWeights = false

STMT00076 ( 0x144[E-] ... ??? )
 [000283] ---XG+------              *  JTRUE     void  
 [000622] J--XG+-N----              \--*  LT        int   
 [000613] -----+------                 +--*  LCL_VAR   int    V88 tmp65        
 [000632] ---XG+------                 \--*  IND       int   
 [001270] ---XG+------                    \--*  ADD       byref 
 [000625] ---XG+------                       +--*  IND       ref   
 [001272] -----+------                       |  \--*  ADD       byref 
 [000616] -----+------                       |     +--*  LCL_VAR   ref    V87 tmp64        
 [001271] -----+------                       |     \--*  CNS_INT   long   8 field offset Fseq[_builder]
 [001269] -----+------                       \--*  CNS_INT   long   16 field offset Fseq[hackishFieldName]

; Total bytes of code 1593, prolog size 37, PerfScore 1744.55, instruction count 362
```

* 37204: same issue as 40796 (below)

* 40796: Very simple method that makes a tail call. Before version stages args through upstream 
temp assigns and likely gives LSRA an easier problem to solve.

```asm
;; System.Tests.Perf_String:Concat_str_str_str(System.Tests.StringArguments):System.String:this

;; BEFORE
       mov      rcx, gword ptr [rdx+8]
       mov      rax, gword ptr [rdx+16]
       mov      r8, gword ptr [rdx+24]
       mov      rdx, rax
       jmp      System.String:Concat(System.String,System.String,System.String):System.String

;  Total bytes of code 20, prolog size 0, PerfScore 10.25, instruction count 5

;; AFTER
       mov      rcx, gword ptr [rdx+8]
       mov      gword ptr [rsp+10H], rdx
       mov      rdx, gword ptr [rdx+16]
       mov      r8, gword ptr [rsp+10H]
       mov      r8, gword ptr [r8+24]
       jmp      System.String:Concat(System.String,System.String,System.String):System.String

;  Total bytes of code 27, prolog size 0, PerfScore 12.70, instruction count 6
```
* 41379: two new float CSEs in callee-saves. Method has EH, so this leads to extra saves/restores in prologs/epilogs.
```
;; System.Net.Dns:GetHostEntryOrAddressesCore(System.Net.IPAddress,bool,int,Microsoft.Extensions.Internal.ValueStopwatch):System.Object

;; BEFORE
;  Total bytes of code 1461, prolog size 62, PerfScore 348.62, instruction count 361

;; AFTER
;  V80 cse6         [V80,T52] (  6,  3   )  double  ->  mm6         "CSE - moderate"
;  V81 cse7         [V81,T53] (  6,  3   )  double  ->  mm7         "CSE - moderate"
;  Total bytes of code 1577, prolog size 83, PerfScore 369.27, instruction count 377
```

**Comment by AndyAyersMS** [comment]
### coreclr_tests regressions

* 92382: large number of dead news don't get cleaned up, as we forwad sub calls to
the new helper under a null check and nothing ever realizes all of this is now dead.
```
;; Z:Main():int

;; BEFORE

STMT00064 ( 0x0B1[E-] ... 0x0C6 )
 [000201] -AC---------              *  ASG       ref   
 [000200] D------N----              +--*  LCL_VAR   ref    V35 tmp28        
 [000199] --C---------              \--*  CALL help ref    HELPER.CORINFO_HELP_NEWSFAST
 [000198] H----------- arg0            \--*  CNS_INT(h) long   0x7ffe3dba9ea0 method

LocalAddressVisitor visiting statement:
STMT00123 ( INL66 @ 0x000[E-] ... ??? ) <- INLRT @ 0x0B6[--]
 [000381] ---X--------              *  NULLCHECK byte  
 [000204] ------------              \--*  LCL_VAR   ref    V35 tmp28  

; Total bytes of code 14, prolog size 4, PerfScore 3.15, instruction count 4

;; AFTER

;; should be trivial to dead code this in morph or later on

STMT00123 ( INL66 @ 0x000[E-] ... ??? ) <- INLRT @ 0x0B6[--]
 [000381] --CX--------              *  NULLCHECK byte  
 [000199] --C---------              \--*  CALL help ref    HELPER.CORINFO_HELP_NEWSFAST
 [000198] H----------- arg0            \--*  CNS_INT(h) long   0x7ffe3dba9ea0 method

; Total bytes of code 116, prolog size 4, PerfScore 38.85, instruction count 22
```
* 92347: same issue as in 92382
* 216886: same issue as in 92382
* 224304: morphing an overflow cast apparently doesn't try and simplify the cast operand.
So we miss a branch fold, which we never fix up later on.
```
;; TestUnsafeCasts:StructFromPrim()

;; BEFORE

 [000045] -AC---------              *  ASG       bool  
 [000044] D------N----              +--*  LCL_VAR   bool   V04 tmp2         
 [000036] --C---------              \--*  CAST      int <- bool <- int
 [000019] --C---------                 \--*  EQ        int   
 [000034] ---X--------                    +--*  CAST_ovfl int <- long
 [000033] ------------                    |  \--*  LCL_VAR   long   V03 tmp1         
 [000018] ------------                    \--*  CNS_INT   int    100

Copy     Assertion: V03 == V07, index = #03
Copy     Assertion: V07 == V00, index = #02
Constant Assertion: V00 == 100, index = #01
Folding operator with constant nodes into a constant: [000034]
Folding operator with constant nodes into a constant: [000019]
Folding operator with constant nodes into a constant: [000036]
New Local Constant Assertion: V04 == 1, index = #04

;  Total bytes of code 1, prolog size 0, PerfScore 1.10, instruction count 1

;; AFTER

In BB01 New Local Constant Assertion: V00 == 100, index = #01
In BB01 New Local Copy     Assertion: V07 == V00, index = #02

 [000045] -A-XG-------              *  ASG       bool  
 [000044] D------N----              +--*  LCL_VAR   bool   V04 tmp2         
 [000036] ---XG-------              \--*  CAST      int <- bool <- int
 [000019] ---XG-------                 \--*  EQ        int   
 [000034] ---XG-------                    +--*  CAST_ovfl int <- long
 [000030] ----G-------                    |  \--*  FIELD     long   hackishFieldName
 [000026] ------------                    |     \--*  ADDR      byref 
 [000027] ------------                    |        \--*  LCL_VAR   long   V07 tmp5         
 [000018] ------------                    \--*  CNS_INT   int    100

morph does not simplify [000030]

;  Total bytes of code 36, prolog size 4, PerfScore 7.85, instruction count 10
```
* 228811: two LSRA temps, spills/reloads from these seem to account for all the diffs. 
Would need to study this more deeply to really see what is happening.
```
;; r8div:Main():int

;; BEFORE
;  Total bytes of code 120867, prolog size 99, PerfScore 44353.99, instruction count 26651

;; AFTER
;  TEMP_05                                   double  ->  [rsp+0x72C]
;  TEMP_04                                   double  ->  [rsp+0x724]
;  Total bytes of code 124686, prolog size 99, PerfScore 45244.79, instruction count 27065
```

* 241902: same issue as in 92382
* 246939: same issue as in 92382

**Comment by AndyAyersMS** [comment]
### libraries crossgen2 regressions

* 51979: spilled high-weight CSE and local

```
;; System.Data.XMLDiffLoader:ReadOldRowData(System.Data.DataSet,byref,byref,System.Xml.XmlReader):int:this

;; BEFORE

;  Total bytes of code 2646, prolog size 53, PerfScore 1889.41, instruction count 679

;; AFTER

;  V13 loc8         [V13,T05] ( 20, 44   )     ref  ->  [rbp-80H]   class-hnd spill-single-def
;  V74 cse3         [V74,T01] ( 42, 75   )    long  ->  [rbp-58H]   "CSE - aggressive"

;  Total bytes of code 2988, prolog size 53, PerfScore 2068.36, instruction count 731
```

* 72638: call argument contention (similar to 40796 in benchmarks, above)
* 94337: spilled high-weight CSE

```
;; System.Reflection.MethodBase:CheckArguments(byref,System.ReadOnlySpan`1[System.Object],
;;    System.Reflection.Binder,int,System.Globalization.CultureInfo,System.RuntimeType[]):System.Span`1[System.Object]:this

;; BEFORE

;  Total bytes of code 596, prolog size 23, PerfScore 378.73, instruction count 149

;; AFTER

;  V49 cse2         [V49,T01] (  6, 19.80)    long  ->  [rsp+40H]   spill-single-def "CSE - aggressive"

;  Total bytes of code 909, prolog size 28, PerfScore 404.93, instruction count 223
```
* 122705: loop cloning
* 122797: loop cloning
* 131717: loop cloning
* 190487: call argument contention (similar to 40796 in benchmarks, above)

**Comment by AndyAyersMS** [comment]
Addressed one of the sources of regression noted above: nullchecks of new helper calls.  Diffs (from just this last commit) show ~270 improvements, no regressions. Interestingly, two cases not from test code.

## coreclr_tests.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 127026921 (overridden on cmd)
Total bytes of diff: 127022511 (overridden on cmd)
Total bytes of delta: -4410 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
        -238 : 216844.dasm (-1.99% of base)
        -235 : 241902.dasm (-61.36% of base)
        -119 : 244057.dasm (-25.00% of base)
        -102 : 234810.dasm (-15.64% of base)
        -102 : 92382.dasm (-87.93% of base)
        -102 : 234779.dasm (-15.64% of base)
        -102 : 234778.dasm (-15.64% of base)
        -102 : 234809.dasm (-15.64% of base)
         -85 : 97711.dasm (-59.86% of base)
         -85 : 243859.dasm (-9.18% of base)
         -85 : 243887.dasm (-9.18% of base)
         -85 : 259885.dasm (-27.96% of base)
         -85 : 92347.dasm (-85.86% of base)
         -68 : 243872.dasm (-7.40% of base)
         -68 : 243868.dasm (-7.40% of base)
         -68 : 92330.dasm (-25.56% of base)
         -56 : 260784.dasm (-51.38% of base)
         -51 : 97513.dasm (-61.45% of base)
         -51 : 97514.dasm (-61.45% of base)
         -51 : 251129.dasm (-31.68% of base)

128 total files with Code Size differences (128 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
        -238 (-1.99% of base) : 216844.dasm - TestReflectionInvoke:Run()
        -235 (-61.36% of base) : 241902.dasm - ServerSimulator.Parameters:.ctor():this
        -119 (-25.00% of base) : 244057.dasm - mainMethod:checkGetType(System.Object)
        -102 (-15.64% of base) : 234778.dasm - mainMethod:checkGetType(X`1[__Canon])
        -102 (-15.64% of base) : 234809.dasm - mainMethod:checkGetType(X`1[__Canon])
        -102 (-15.64% of base) : 234810.dasm - mainMethod:checkGetType(X`1[Byte])
        -102 (-15.64% of base) : 234779.dasm - mainMethod:checkGetType(X`1[Byte])
        -102 (-87.93% of base) : 92382.dasm - Z:Main():int
         -85 (-59.86% of base) : 97711.dasm - <Module>:Main():int
         -85 (-9.18% of base) : 243887.dasm - Chaos.A0:CreateAllTypesA0():this
         -85 (-9.18% of base) : 243859.dasm - Chaos.A0A0:CreateAllTypesA0A0():this
         -85 (-27.96% of base) : 259885.dasm - Test_instance02:Main():int
         -85 (-85.86% of base) : 92347.dasm - Z:Main(System.String[]):int
         -68 (-7.40% of base) : 243872.dasm - Chaos.A0A0A0`1[__Canon][System.__Canon]:CreateAllTypesA0A0A0():this
         -68 (-7.40% of base) : 243868.dasm - Chaos.A0A1`1[__Canon][System.__Canon]:CreateAllTypesA0A1():this
         -68 (-25.56% of base) : 92330.dasm - Test_exacttype:Main():int
         -56 (-51.38% of base) : 260784.dasm - HelloWorld:Main():int
         -51 (-31.68% of base) : 251129.dasm - CMain:ScenarioA_Test3():bool
         -51 (-33.77% of base) : 251133.dasm - CMain:ScenarioA_Test7():bool
         -51 (-31.68% of base) : 251136.dasm - CMain:ScenarioB_Test3():bool

Top method improvements (percentages):
        -102 (-87.93% of base) : 92382.dasm - Z:Main():int
         -85 (-85.86% of base) : 92347.dasm - Z:Main(System.String[]):int
         -17 (-65.38% of base) : 216886.dasm - TestClassVTableTracking:Run()
         -51 (-61.45% of base) : 97513.dasm - Test_TestCase0:Main():int
         -51 (-61.45% of base) : 97512.dasm - Test_TestCase0:Main():int
         -51 (-61.45% of base) : 97514.dasm - Test_TestCase1:Main():int
        -235 (-61.36% of base) : 241902.dasm - ServerSimulator.Parameters:.ctor():this
         -85 (-59.86% of base) : 97711.dasm - <Module>:Main():int
         -17 (-54.84% of base) : 96037.dasm - _callvirt:main(System.String[]):int
         -17 (-54.84% of base) : 96032.dasm - callintf:main(System.String[]):int
         -17 (-54.84% of base) : 96036.dasm - callsuper:main(System.String[]):int
         -17 (-54.84% of base) : 92317.dasm - Program:Main():int
         -17 (-54.84% of base) : 92270.dasm - Program:Test():int
         -17 (-54.84% of base) : 216885.dasm - TestClassVTableTracking:Call():int
         -34 (-51.52% of base) : 97501.dasm - Test_Ambiguous:Main():int
         -34 (-51.52% of base) : 261013.dasm - Test_dev10_794943:Main():int
         -56 (-51.38% of base) : 260784.dasm - HelloWorld:Main():int
         -12 (-46.15% of base) : 92269.dasm - Program:Test():int
         -12 (-46.15% of base) : 216884.dasm - TestClassVTableTracking:Call():int
         -17 (-41.46% of base) : 91556.dasm - cs1:Main(System.String[]):int

128 total methods with Code Size differences (128 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 46025685 (overridden on cmd)
Total bytes of diff: 46025617 (overridden on cmd)
Total bytes of delta: -68 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -34 : 138095.dasm (-6.17% of base)
         -34 : 138096.dasm (-5.14% of base)

2 total files with Code Size differences (2 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -34 (-6.17% of base) : 138095.dasm - CharEntityEncoderFallbackBuffer:Fallback(ushort,int):bool:this
         -34 (-5.14% of base) : 138096.dasm - CharEntityEncoderFallbackBuffer:Fallback(ushort,ushort,int):bool:this

Top method improvements (percentages):
         -34 (-6.17% of base) : 138095.dasm - CharEntityEncoderFallbackBuffer:Fallback(ushort,int):bool:this
         -34 (-5.14% of base) : 138096.dasm - CharEntityEncoderFallbackBuffer:Fallback(ushort,ushort,int):bool:this

2 total methods with Code Size differences (2 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries_tests.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 112203489 (overridden on cmd)
Total bytes of diff: 112200908 (overridden on cmd)
Total bytes of delta: -2581 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -51 : 32196.dasm (-82.26% of base)
         -34 : 32287.dasm (-10.33% of base)
         -34 : 319456.dasm (-25.56% of base)
         -34 : 32172.dasm (-75.56% of base)
         -34 : 32268.dasm (-75.56% of base)
         -34 : 32158.dasm (-75.56% of base)
         -34 : 32165.dasm (-75.56% of base)
         -27 : 136276.dasm (-35.53% of base)
         -22 : 326966.dasm (-21.15% of base)
         -17 : 144029.dasm (-13.93% of base)
         -17 : 198117.dasm (-3.88% of base)
         -17 : 199780.dasm (-3.69% of base)
         -17 : 30550.dasm (-29.82% of base)
         -17 : 31974.dasm (-3.41% of base)
         -17 : 32303.dasm (-9.09% of base)
         -17 : 326986.dasm (-65.38% of base)
         -17 : 327008.dasm (-65.38% of base)
         -17 : 43411.dasm (-34.00% of base)
         -17 : 43412.dasm (-35.42% of base)
         -17 : 143010.dasm (-26.15% of base)

143 total files with Code Size differences (143 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -51 (-82.26% of base) : 32196.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass001.genericbaseclass001.Test:MainMethod(System.String[]):int
         -34 (-25.56% of base) : 319456.dasm - <>c:<GetSetupInformation>b__55_0():this
         -34 (-10.33% of base) : 32287.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.backwardscompatible.dynamictypedeclared012.dynamictypedeclared012.Test:MainMethod():int
         -34 (-75.56% of base) : 32268.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.backwardscompatible.dynamictypedeclared021.dynamictypedeclared021.App:MainMethod(System.String[]):int
         -34 (-75.56% of base) : 32172.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass003.genericbaseclass003.NS.Test:MainMethod(System.String[]):int
         -34 (-75.56% of base) : 32165.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass004.genericbaseclass004.NS.Test:MainMethod(System.String[]):int
         -34 (-75.56% of base) : 32158.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass005.genericbaseclass005.NS.Test:MainMethod(System.String[]):int
         -27 (-35.53% of base) : 136276.dasm - System.CodeDom.Compiler.Tests.CodeCompilerTests:JoinStringArray_Invoke_ReturnsExpected(System.String[],System.String,System.String):this
         -22 (-21.15% of base) : 326966.dasm - System.Security.Permissions.Tests.EvidenceBaseTests:PermissionRequestEvidenceCallMethods()
         -17 (-1.71% of base) : 32376.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.context.property.regproperty.regclass.regclass020.regclass020.Test:MainMethod():int
         -17 (-9.09% of base) : 32303.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.backwardscompatible.dynamictypedeclared007.dynamictypedeclared007.Test:MainMethod():int
         -17 (-9.14% of base) : 32284.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.backwardscompatible.dynamictypedeclared013.dynamictypedeclared013.Test:MainMethod():int
         -17 (-60.71% of base) : 32270.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.backwardscompatible.dynamictypedeclared019.dynamictypedeclared019.Test:MainMethod(System.String[]):int
         -17 (-60.71% of base) : 32266.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.backwardscompatible.dynamictypedeclared023.dynamictypedeclared023.Test:MainMethod(System.String[]):int
         -17 (-4.94% of base) : 32240.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.method002.method002.Test:MainMethod(System.String[]):int
         -17 (-2.27% of base) : 31980.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.returnType.properties.property001.property001.Test:MainMethod(System.String[]):int
         -17 (-3.41% of base) : 31974.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.returnType.properties.property004.property004.Test:MainMethod(System.String[]):int
         -17 (-29.82% of base) : 30597.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.dynamicType.generics.cnstraintegeregers.complex001.complex001.Test:MainMethod(System.String[]):int
         -17 (-29.82% of base) : 30595.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.dynamicType.generics.cnstraintegeregers.complex002.complex002.Test:MainMethod(System.String[]):int
         -17 (-29.82% of base) : 30567.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.dynamicType.generics.cnstraintegeregers.simple001.simple001.Test:MainMethod(System.String[]):int

Top method improvements (percentages):
         -51 (-82.26% of base) : 32196.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass001.genericbaseclass001.Test:MainMethod(System.String[]):int
         -34 (-75.56% of base) : 32268.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.backwardscompatible.dynamictypedeclared021.dynamictypedeclared021.App:MainMethod(System.String[]):int
         -34 (-75.56% of base) : 32172.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass003.genericbaseclass003.NS.Test:MainMethod(System.String[]):int
         -34 (-75.56% of base) : 32165.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass004.genericbaseclass004.NS.Test:MainMethod(System.String[]):int
         -34 (-75.56% of base) : 32158.dasm - ManagedTests.DynamicCSharp.Conformance.dynamic.declarations.formalParameter.Methods.genericbaseclass005.genericbaseclass005.NS.Test:MainMethod(System.String[]):int
         -17 (-65.38% of base) : 144001.dasm - System.ComponentModel.Design.Serialization.Tests.DesignerLoaderTests:Flush_Invoke_Nop():this
         -17 (-65.38% of base) : 143290.dasm - System.ComponentModel.Tests.LicenseContextTests:GetSavedLicenseKey_Invoke_ReturnsNull():this
         -17 (-65.38% of base) : 143291.dasm - System.ComponentModel.Tests.LicenseContextTests:GetService_Invoke_ReturnsNull():this
         -17 (-65.38% of base) : 143292.dasm - System.ComponentModel.Tests.LicenseContextTests:SetSavedLicenseKey_Invoke_Nop():this
         -17 (-65.38% of base) : 50179.dasm - System.Linq.Expressions.Tests.ExpressionTests:DefaultReducesToSame():this
         -17 (-65.38% of base) : 53253.dasm - System.Linq.Expressions.Tests.VisitorTests:VisitNullDefaultsToReturnNull():this
         -17 (-65.38% of base) : 187911.dasm - System.Runtime.Serialization.Xml.Tests.XmlDictionaryReaderTests:Close_DerivedReader_Success()
         -17 (-65.38% of base) : 185658.dasm - System.Runtime.Serialization.Xml.Tests.XmlDictionaryReaderTests:Close_DerivedReader_Success()
         -17 (-65.38% of base) : 326969.dasm - System.Security.Permissions.Tests.HostProtectionTests:HostProtectionAttributeCallMethods()
         -17 (-65.38% of base) : 326990.dasm - System.Security.Permissions.Tests.PermissionTests:ConfigurationPermissionAttributeCallMethods()
         -17 (-65.38% of base) : 326994.dasm - System.Security.Permissions.Tests.PermissionTests:EnvironmentPermissionsAttributeCallMethods()
         -17 (-65.38% of base) : 326996.dasm - System.Security.Permissions.Tests.PermissionTests:FileDialogPermissionAttributeCallMethods()
         -17 (-65.38% of base) : 326999.dasm - System.Security.Permissions.Tests.PermissionTests:GacIdentityPermissionAttributeCallMethods()
         -17 (-65.38% of base) : 327001.dasm - System.Security.Permissions.Tests.PermissionTests:MediaPermissionAttributeCallMethods()
         -17 (-65.38% of base) : 327004.dasm - System.Security.Permissions.Tests.PermissionTests:PublisherIdentityPermissionAttributeCallMethods()

143 total methods with Code Size differences (143 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

**Comment by AndyAyersMS** [comment]
Assertion prop can set `GTF_ORDER_SIDEEFF` on non-volatile indirs, so look more deeply during in `gtFoldExprCompare` to find volatiles.

Diffs from latest commit:
## coreclr_tests.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 127022506 (overridden on cmd)
Total bytes of diff: 127018348 (overridden on cmd)
Total bytes of delta: -4158 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
        -539 : 257247.dasm (-39.66% of base)
        -536 : 257252.dasm (-40.88% of base)
        -533 : 257250.dasm (-38.82% of base)
        -529 : 257251.dasm (-38.75% of base)
        -529 : 257253.dasm (-38.93% of base)
        -529 : 257254.dasm (-38.93% of base)
        -529 : 257242.dasm (-38.75% of base)
         -73 : 219128.dasm (-0.06% of base)
         -73 : 219245.dasm (-0.06% of base)
         -72 : 219402.dasm (-0.05% of base)
         -71 : 219422.dasm (-0.05% of base)
         -63 : 219149.dasm (-0.05% of base)
         -59 : 219325.dasm (-0.04% of base)
         -23 : 219265.dasm (-0.02% of base)

14 total files with Code Size differences (14 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
        -539 (-39.66% of base) : 257247.dasm - TestCSE:TestOp():bool:this
        -536 (-40.88% of base) : 257252.dasm - TestCSE:TestOp():bool:this
        -533 (-38.82% of base) : 257250.dasm - TestCSE:TestOp():bool:this
        -529 (-38.75% of base) : 257251.dasm - TestCSE:TestOp():bool:this
        -529 (-38.93% of base) : 257253.dasm - TestCSE:TestOp():bool:this
        -529 (-38.93% of base) : 257254.dasm - TestCSE:TestOp():bool:this
        -529 (-38.75% of base) : 257242.dasm - TestCSE:TestOp():bool:this
         -73 (-0.06% of base) : 219128.dasm - i4div:Main():int
         -73 (-0.06% of base) : 219245.dasm - u4div:Main():int
         -72 (-0.05% of base) : 219402.dasm - u4rem:Main():int
         -71 (-0.05% of base) : 219422.dasm - u8rem:Main():int
         -63 (-0.05% of base) : 219149.dasm - i8div:Main():int
         -59 (-0.04% of base) : 219325.dasm - i8rem:Main():int
         -23 (-0.02% of base) : 219265.dasm - u8div:Main():int

Top method improvements (percentages):
        -536 (-40.88% of base) : 257252.dasm - TestCSE:TestOp():bool:this
        -539 (-39.66% of base) : 257247.dasm - TestCSE:TestOp():bool:this
        -529 (-38.93% of base) : 257253.dasm - TestCSE:TestOp():bool:this
        -529 (-38.93% of base) : 257254.dasm - TestCSE:TestOp():bool:this
        -533 (-38.82% of base) : 257250.dasm - TestCSE:TestOp():bool:this
        -529 (-38.75% of base) : 257251.dasm - TestCSE:TestOp():bool:this
        -529 (-38.75% of base) : 257242.dasm - TestCSE:TestOp():bool:this
         -73 (-0.06% of base) : 219128.dasm - i4div:Main():int
         -73 (-0.06% of base) : 219245.dasm - u4div:Main():int
         -72 (-0.05% of base) : 219402.dasm - u4rem:Main():int
         -71 (-0.05% of base) : 219422.dasm - u8rem:Main():int
         -63 (-0.05% of base) : 219149.dasm - i8div:Main():int
         -59 (-0.04% of base) : 219325.dasm - i8rem:Main():int
         -23 (-0.02% of base) : 219265.dasm - u8div:Main():int

14 total methods with Code Size differences (14 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 46025617 (overridden on cmd)
Total bytes of diff: 46025045 (overridden on cmd)
Total bytes of delta: -572 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
        -369 : 179587.dasm (-33.42% of base)
        -203 : 179590.dasm (-24.17% of base)

2 total files with Code Size differences (2 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
        -369 (-33.42% of base) : 179587.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:UnionWith(System.Collections.Generic.IEnumerable`1[__Canon]):this
        -203 (-24.17% of base) : 179590.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:IntersectWith(System.Collections.Generic.IEnumerable`1[__Canon]):this

Top method improvements (percentages):
        -369 (-33.42% of base) : 179587.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:UnionWith(System.Collections.Generic.IEnumerable`1[__Canon]):this
        -203 (-24.17% of base) : 179590.dasm - System.Collections.Generic.SortedSet`1[__Canon][System.__Canon]:IntersectWith(System.Collections.Generic.IEnumerable`1[__Canon]):this

2 total methods with Code Size differences (2 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

**Comment by AndyAyersMS** [comment]
### libraries regressions

* 16819: optimize bools creates
```
Folded non-leaf boolean conditions of BB04 and BB05 to :
STMT00007 ( 0x049[E-] ... ??? )
               [000041] -----+------              *  JTRUE     void  
               [000040] J----+-N----              \--*  NE        int   
               [000895] ------------                 +--*  OR        bool  
               [000499] -----+------                 |  +--*  HWINTRINSIC bool   float op_Equality
               [000498] n----+------                 |  |  +--*  OBJ       simd32<System.Numerics.Vector`1[Single]>
               [000494] -----+-N----                 |  |  |  \--*  LCL_VAR   byref  V01 arg1         
               [000034] -----+------                 |  |  \--*  LCL_VAR   simd32<System.Numerics.Vector`1[Single]> V04 loc0         
     (  9,  7) [000510] ------------                 |  \--*  HWINTRINSIC bool   float op_Equality
     (  7,  5) [000509] n-----------                 |     +--*  OBJ       simd32<System.Numerics.Vector`1[Single]>
     (  1,  1) [000505] -------N----                 |     |  \--*  LCL_VAR   byref  V02 arg2         
     (  1,  1) [000046] ------------                 |     \--*  LCL_VAR   simd32<System.Numerics.Vector`1[Single]> V04 loc0         
               [000039] -----+------                 \--*  CNS_INT   bool   0
```
which does not get optimized well:
```asm
;; System.SpanHelpers:IndexOfAny(byref,System.Numerics.Vector`1[Single],System.Numerics.Vector`1[Single],int):int

;; BEFORE

IN0091: 000289 vmovupd  ymm0, ymmword ptr[rsi+rax]
IN0092: 00028E vcmpps   ymm3, ymm1, ymm0, 0
IN0093: 000293 vmovmskps yrax, ymm3
IN0094: 000297 cmp      eax, 255
IN0095: 00029C je       G_M54126_IG14
IN0096: 0002A2 vcmpps   ymm0, ymm2, ymm0, 0
IN0097: 0002A7 vmovmskps yrax, ymm0
IN0098: 0002AB cmp      eax, 255
IN0099: 0002B0 je       G_M54126_IG14

;; AFTER
IN00a9: 0002D5 vmovupd  ymm0, ymmword ptr[rsi+rax]
IN00aa: 0002DB vcmpps   ymm3, ymm1, ymm0, 0
IN00ab: 0002E1 vmovmskps yrax, ymm3
IN00ac: 0002E6 cmp      eax, 255
IN00ad: 0002EB sete     al
IN00ae: 0002EE movzx    rax, al
IN00af: 0002F1 vcmpps   ymm0, ymm2, ymm0, 0
IN00b0: 0002F7 vmovmskps yrcx, ymm0
IN00b1: 0002FC cmp      ecx, 255
IN00b2: 000302 sete     cl
IN00b3: 000305 movzx    rcx, cl
IN00b4: 000308 or       al, cl
IN00b5: 00030A jne      G_M54126_IG14
```

* 16825: similar to 16819 above
* 16842: similar to 16819 above
* 16836: similar to 16819 above
* 120287: call argument contention (similar to 40796 in benchmarks, above)
* 121728: LSRA used 4 more XMM callee-saves, multiple epilogs. Likely because
forward sub broke up beneficial "splitting" via temps, similar to what we see in 40796 in benchmarks, above.
* 156309: call argument contention (similar to 40796 in benchmarks, above)
* 164982: call argument contention (similar to 40796 in benchmarks, above)
* 179587: optAssertionProp_Ind is setting GTF_ORDER_SIDEEFF on an indir,
this leads to us being unable to fold away a compare. Fixed.

**Comment by AndyAyersMS** [comment]
None of these recent failures seem related. Will retry, I guess.

Tried various things to avoid creating interference when forward subbing into calls, nothing satisfactory so far. 

Think this is the version we should merge.

**Comment by AndyAyersMS** [comment]
Linker test build failure:
```
emcc : error : Unexpected hash: 9ec7c573fac2cd4d6ba64dd4dfd7330f317be75367575013da4004d7da7ff51b70b85783dc8533df081e70527135cdbf2ffc12b40f2d011fd7fbe6cb52d2f47d [/__w/1/s/src/native/libs/build-native.proj]
##[error]emcc(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Unexpected hash: 9ec7c573fac2cd4d6ba64dd4dfd7330f317be75367575013da4004d7da7ff51b70b85783dc8533df081e70527135cdbf2ffc12b40f2d011fd7fbe6cb52d2f47d
  If you are updating the port, please update the hash in the port module.
  System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/build.make:80: recipe for target 'System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/pal_zlib.c.o' failed
  make[2]: *** [System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/pal_zlib.c.o] Error 1
```

**Comment by AndyAyersMS** [comment]
Arm test failure is a timeout, it happened again on rerun....
```
        cmdLine:/root/helix/work/workitem/e/JIT/HardwareIntrinsics/General/Vector256/Vector256_ro/Vector256_ro.sh 
          Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 2/1/2022 7:03:47 PM, end: 2/1/2022 7:13:47 PM)
```
Don't think it is related -- there is nothing manifestly arch specific in this change -- but will look into it further.

**Comment by AndyAyersMS** [comment]
Outerloop test tab shows as 3 failures. The status above shows 5 failing legs.

* JIT/HardwareIntrinsics/General/Vector256/Vector256_ro timeout (x2) (#64653)
* JIT\Generics\Instantiation\Interfaces\struct03 -- crossgen 2 dies, possibly related?
```
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
```
* CoreCLR Pri1 Runtime Tests Run R2R_CG2 Linux arm64 checked -- reported as failed but no test failure noted
* CoreCLR Pri1 Runtime Tests Run R2R_CG2 Linux_musl arm64 checked -- ditto

**Comment by AndyAyersMS** [comment]
SPMI still unable to show any info on diffs (because there are so many).

**Comment by AndyAyersMS** [comment]
@kunalspathak a bunch of fuzzlyn/antigen legs were cancelled. Seems like they're asking for a non-existent pool?
```
##[error]Failed to request agent. Exception Image Build.Ubuntu.1804.Amd64.Open doesn't exist in pool NetCore1ESPool-Public
```

**Comment by kunalspathak** [comment]
> Seems like they're asking for a non-existent pool?

@MattGal earlier confirmed that there is some issue with the Ubuntu.1804.Amd64.Open. Windows jobs are still running.

**Comment by AndyAyersMS** [comment]
From what I can tell the Antigen failures are there in main, as are most of the Fuzzlyn failures.

This Fuzzlyn failure may be unique:
```
Assertion failed '(emitThisGCrefRegs & regMask) == 0' in 'Program:M25(bool,long,int,int,byref):System.Int64[]' during 'Emit code' (IL size 3133)

    File: D:\a\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 12184
```

**Comment by kunalspathak** [comment]
There are few others in Antigen that I don't remember seeing on weekend. Not sure if they are related to your PR though.

```
Assert failure(PID 1688 [0x00000698], Thread: 5996 [0x176c]): Assertion failed 'a != b' in 'TestClass:Method5(S1):S2:this' during 'Do value numbering' (IL size 1352)
    File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp Line: 17408
    Image: C:\h\w\AE300971\p\CoreRoot\corerun.exe
```

```
Assert failure(PID 5540 [0x000015a4], Thread: 824 [0x0338]): Assertion failed 'fgReachable(begBlk, endBlk)' in 'TestClass:Method1(byref,byref,S1,byref,S1,byref):int:this' during 'Update flow graph opt pass' (IL size 23369)
    File: D:\a\_work\1\s\src\coreclr\jit\optimizer.cpp Line: 167
    Image: C:\h\w\B04E09AF\p\CoreRoot\corerun.exe
```

**Comment by jakobbotsch** [comment]
> From what I can tell the Antigen failures are there in main, as are most of the Fuzzlyn failures.
> 
> This Fuzzlyn failure may be unique:
> 
> ```
> Assertion failed '(emitThisGCrefRegs & regMask) == 0' in 'Program:M25(bool,long,int,int,byref):System.Int64[]' during 'Emit code' (IL size 3133)
> 
>     File: D:\a\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 12184
> ```

This Fuzzlyn example also looks interesting:
```csharp
// Generated by Fuzzlyn v1.5 on 2022-02-02 18:45:57
// Run on X86 Windows
// Seed: 2552302029114048182
// Reduced from 26.6 KiB to 0.5 KiB in 00:00:36
// Debug: Outputs -1
// Release: Outputs -2
public interface I1
{
}

public struct S0 : I1
{
    public short F5;
    public S0(short f5): this()
    {
        F5 = f5;
    }

    public void M4(short arg0, I1 arg1)
    {
        System.Console.WriteLine(arg0);
    }

    public I1 M7()
    {
        ref S0 var0 = ref this;
        var0 = new S0(1);
        return this;
    }
}

public class Program
{
    public static void Main()
    {
        S0 vr0 = default(S0);
        new S0(0).M4((short)~vr0.F5, vr0.M7());
    }
}
```

**Comment by AndyAyersMS** [comment]
@kunalspathak @jakobbotsch how do you dig out the repros...? It wasn't obvious to me.

**Comment by jakobbotsch** [comment]
> @kunalspathak @jakobbotsch how do you dig out the repros...? It wasn't obvious to me.

The one from Fuzzlyn is the first one under the "Summary of Fuzzlyn run on windows x86 checked -> 5 reduced examples are available" heading at
https://dev.azure.com/dnceng/public/_build/results?buildId=1587203&view=ms.vss-build-web.run-extensions-tab

**Comment by kunalspathak** [comment]
> @kunalspathak @jakobbotsch how do you dig out the repros...? It wasn't obvious to me.

You need to go to Artifacts of AzDo and location the Partition that failed (in first example it was `Partition2`) so you download the respective zip file.

image

For Antigen, each partition might have several unique issues and they are present in `UniqueIssue0`, `UniqueIssue1`, etc. Just open the summary file (which is present in the zip you downloaded) and it will tell you which unique issue folder is the repro present.

**Comment by AndyAyersMS** [comment]
> > @kunalspathak @jakobbotsch how do you dig out the repros...? It wasn't obvious to me.
> 
> The one from Fuzzlyn is the first one under the "Summary of Fuzzlyn run on windows x86 checked -> 5 reduced examples are available" heading at https://dev.azure.com/dnceng/public/_build/results?buildId=1587203&view=ms.vss-build-web.run-extensions-tab

The x64 failure doesn't have a repro, I guess that's what confused me.

**Comment by jakobbotsch** [comment]
> This Fuzzlyn failure may be unique:
> 
> ```
> Assertion failed '(emitThisGCrefRegs & regMask) == 0' in 'Program:M25(bool,long,int,int,byref):System.Int64[]' during 'Emit code' (IL size 3133)
> 
>     File: D:\a\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 12184
> ```

This one repros even on main so not related to this change. Unfortunate it looks like creating a small repro is not simple, so I will need to dig into this a bit further another time.

**Comment by AndyAyersMS** [comment]
What config settings do you run with for debug/release?

**Comment by jakobbotsch** [comment]
> What config settings do you run with for debug/release?

For Fuzzlyn it is just `COMPlus_TieredCompilation=0`.

**Comment by AndyAyersMS** [comment]
> > What config settings do you run with for debug/release?
> 
> For Fuzzlyn it is just `COMPlus_TieredCompilation=0`.

Ok. I can't repro, but maybe I need to merge up my local changes, they're a bit behind main.

**Comment by jakobbotsch** [comment]
> > > What config settings do you run with for debug/release?
> > 
> > 
> > For Fuzzlyn it is just `COMPlus_TieredCompilation=0`.
> 
> Ok. I can't repro, but maybe I need to merge up my local changes, they're a bit behind main.

I'll see if I can dig out what's going on.

**Comment by jakobbotsch** [comment]
This one repros on your branch:
```csharp
// Generated by Fuzzlyn v1.5 on 2022-02-02 18:45:57
// Run on X86 Windows
// Seed: 2552302029114048182
// Reduced from 26.6 KiB to 0.5 KiB in 00:00:36
// Debug: Outputs -1
// Release: Outputs -2
using System;

public interface I1
{
}

public struct S0 : I1
{
    public short F5;
    public S0(short f5): this()
    {
        F5 = f5;
    }

    public void M4(short arg0, I1 arg1)
    {
        Program.s_rt.WriteLine(arg0);
    }

    public I1 M7()
    {
        ref S0 var0 = ref this;
        var0 = new S0(1);
        return this;
    }
}

public class Program
{
    public static IRT s_rt;
    public static void Main()
    {
        s_rt = new C();
        S0 vr0 = default(S0);
        new S0(0).M4((short)~vr0.F5, vr0.M7());
    }
}

public interface IRT
{
    void WriteLine<T>(T val);
}

public class C : IRT
{
    public void WriteLine<T>(T val)
    {
        Console.WriteLine(val);
    }
}
```

**Comment by AndyAyersMS** [comment]
Ok, thanks. On the earlier one (still no repro with merged up build) fwd sub kicks in for `Main` and creates:
```
               [000049] -A----------              *  ASG       short 
               [000048] D------N----              +--*  LCL_VAR   short  V04 tmp2         
               [000045] ------------              \--*  CAST      int <- short <- int
               [000022] ------------                 \--*  CAST      int <- short <- int
               [000021] ------------                    \--*  NOT       int   
               [000020] ------------                       \--*  LCL_VAR   short (AX) V05 tmp3         
```
Morph turns this into the following. Seems odd, it pushes the outer cast down but doesn't clean up the double cast.
```
               [000049] -A--G+------              *  ASG       short 
               [000048] D----+-N----              +--*  LCL_VAR   int    V04 tmp2         
               [000022] ----G+------              \--*  CAST      int <- short <- int
               [000021] ----G+------                 \--*  NOT       int   
               [000062] ----G+------                    \--*  CAST      int <- short <- int
               [000020] ----G+------                       \--*  LCL_VAR   int   (AX) V05 tmp3         
```
and we generate:
```
IN0001: 00000A 8B4DF8       mov      ecx, dword ptr [ebp-08H]
IN0002: 00000D 0FBFC9       movsx    ecx, cx
IN0003: 000010 F7D1         not      ecx
IN0004: 000012 0FBFF1       movsx    esi, cx
```

**Comment by AndyAyersMS** [comment]
For the second Fuzzlyn case we're moving an address-exposed use into a call arg list and another call arg is going to modify the local
```
    [000036]:  [000037] is only use of [000035] (V04)  -- fwd subbing [000031]; new next stmt is
STMT00009 ( ??? ... ??? )
               [000039] --CXG-------              *  CALL      void   S0.M4
               [000026] ------------ this in ecx  +--*  ADDR      byref 
               [000025] -------N----              |  \--*  LCL_VAR   struct<S0, 2>(AX)(P) V01 loc1         
                                                  |  \--*    short  V01.F5 (offs=0x00) -> V06 tmp4         
               [000040] ------------ arg1         +--*  PUTARG_TYPE short 
               [000057] ------------              |  \--*  CAST      int <- short <- int
               [000031] ------------              |     \--*  CAST      int <- short <- int
               [000030] ------------              |        \--*  NOT       int   
               [000029] ------------              |           \--*  LCL_VAR   short (AX) V05 tmp3         
               [000034] --CXG------- arg2         \--*  CALL      ref    S0.M7
               [000033] ------------ this in ecx     \--*  ADDR      byref 
               [000032] -------N----                    \--*  LCL_VAR   struct<S0, 2>(AX)(P) V00 loc0         
                                                        \--*    short  V00.F5 (offs=0x00) -> V05 tmp3         
```
Thought I had sufficient checks for this. Evidently not.

**Comment by AndyAyersMS** [comment]
Seems like another case where morph may reorder call args and blindly assumes that they won't interfere, so forward sub needs to take pains to make sure we don't introduce interference. Or else Morph runs the interference checks but we haven't yet properly set GTF_GLOB_REF and so it misses things. After morph we've reordered -- and `[000031]` has proper flags:
```
               [000039] --CXG+------              *  CALL      void   S0.M4
               [000034] --CXG+------ arg2 on STK  +--*  CALL      ref    S0.M7
               [000033] -----+------ this in ecx  |  \--*  ADDR      byref 
               [000032] ----G+-N----              |     \--*  LCL_VAR   struct<S0, 2>(AX)(P) V00 loc0         
                                                  |     \--*    short  V00.F5 (offs=0x00) -> V05 tmp3         
     (  6,  7) [000031] ----G------- arg1 in edx  +--*  CAST      int <- short <- int
     (  5,  5) [000030] ----G-------              |  \--*  NOT       int   
     (  4,  4) [000070] ----G-------              |     \--*  CAST      int <- short <- int
     (  3,  2) [000029] ----G-------              |        \--*  LCL_VAR   int   (AX) V05 tmp3         
     (  3,  3) [000026] ------------ this in ecx  \--*  ADDR      byref 
     (  3,  2) [000025] ----G--N----                 \--*  LCL_VAR   struct<S0, 2>(AX)(P) V01 loc1         
                                                     \--*    short  V01.F5 (offs=0x00) -> V06 tmp4         
```
I am only checking for side effects of other call args "up to" the use so here we don't see the call effect from `[000034]` as we think it happens after the use of `[000031]`. Perhaps instead I need to look at the effects of all the args.

**Comment by jakobbotsch** [comment]
Can we not fix morph instead? Sounds like it is always incorrect to do that reordering and not really the fault of forward sub.

**Comment by AndyAyersMS** [comment]
> Can we not fix morph instead? Sounds like it is always incorrect to do that reordering and not really the fault of forward sub.

Yeah, that's one of the thing's I'll look into here.

**Comment by AndyAyersMS** [comment]
`fgArgInfo::SortArgs` keeps call args in order, but is willing to re-order call args wrt other call operands.

So it really does presume all the other arg values cannot be impacted by the calls. I am a bit leery of trying to fix this as part of this PR as it seems like something that in itself could end up fairly involved.

But maybe it's as simple as handling any GTF_GLOB_REF arg like it was a call; presumably we will only see that case arise from forward sub (otherwise we'd have spotted this bug already), so making that change to morph on its own shouldn't cause diffs.

I'll see if that's the case.

**Comment by AndyAyersMS** [comment]
> There are few others in Antigen that I don't remember seeing on weekend. Not sure if they are related to your PR though.
> 
> ```
> Assert failure(PID 1688 [0x00000698], Thread: 5996 [0x176c]): Assertion failed 'a != b' in 'TestClass:Method5(S1):S2:this' during 'Do value numbering' (IL size 1352)
>     File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp Line: 17408
>     Image: C:\h\w\AE300971\p\CoreRoot\corerun.exe
> ```
> 
> ```
> Assert failure(PID 5540 [0x000015a4], Thread: 824 [0x0338]): Assertion failed 'fgReachable(begBlk, endBlk)' in 'TestClass:Method1(byref,byref,S1,byref,S1,byref):int:this' during 'Update flow graph opt pass' (IL size 23369)
>     File: D:\a\_work\1\s\src\coreclr\jit\optimizer.cpp Line: 167
>     Image: C:\h\w\B04E09AF\p\CoreRoot\corerun.exe
> ```

These both repro with latest main...

**Comment by AndyAyersMS** [comment]
> But maybe it's as simple as handling any GTF_GLOB_REF arg like it was a call; presumably we will only see that case arise from forward sub (otherwise we'd have spotted this bug already), so making that change to morph on its own shouldn't cause diffs

It seems tricky to get this right without causing diffs. And I'm not sure what I am doing is correct. On the other hand, the diffs (while small) are mostly positive. Feels to me like we should look at this along with the recent things you have about arg exception reordering and poor evaluation order.

Preliminary changes here if you're curious: https://github.com/dotnet/runtime/compare/main...AndyAyersMS:FixMorphArgSorting

Diff synopsis (x64 windows):
```
25 total methods with Code Size differences (12 improved, 13 regressed), 326 unchanged.
0 total methods with Code Size differences (0 improved, 0 regressed), 46 unchanged.
115 total methods with Code Size differences (105 improved, 10 regressed), 107 unchanged.
2244 total methods with Code Size differences (2207 improved, 37 regressed), 816 unchanged.
2226 total methods with Code Size differences (2214 improved, 12 regressed), 700 unchanged.
497 total methods with Code Size differences (488 improved, 9 regressed), 3577 unchanged.

Total bytes of delta: -17 (-0.00 % of base)
Total bytes of delta: 0 (0.00 % of base)
Total bytes of delta: -732 (-0.00 % of base)
Total bytes of delta: -2153 (-0.01 % of base)
Total bytes of delta: -2222 (-0.00 % of base)
Total bytes of delta: -488 (-0.00 % of base)
```

I am going to push a generalization of the avoidance logic in forward sub instead.

**Comment by AndyAyersMS** [comment]
A number of odd CI failures to sort through
```
2022-02-03T16:05:43.2086940Z   Sending Job to OSX.1014.Amd64.Open...
2022-02-03T16:05:43.8388490Z /Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22075.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error : Helix API does not contain an entry for OSX.1014.Amd64.Open [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
2022-02-03T16:05:43.8558460Z ##[error].packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22075.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Helix API does not contain an entry for OSX.1014.Amd64.Open
2022-02-03T16:05:43.8782230Z 
2022-02-03T16:05:43.8884420Z Build FAILED.
```

**Comment by AndyAyersMS** [comment]
I think the Fuzzlyn and Antigen issues are known issues. And the runtime CI failures likewise. So, I'm going to merge.

**Comment by jakobbotsch** [comment]
@AndyAyersMS I do see 2 Fuzzlyn examples in the latest run that look related.

```csharp
// Generated by Fuzzlyn v1.5 on 2022-02-03 20:06:22
// Run on X86 Windows
// Seed: 4993495812901676847
// Reduced from 57.3 KiB to 0.6 KiB in 00:00:48
// Debug: Outputs 1
// Release: Outputs 4294967295
public struct S1
{
    public uint F4;
    public long F7;
    public S1(uint f4): this()
    {
        F4 = f4;
    }

    public ref bool M1(uint arg0, bool arg1)
    {
        this.F4 = (uint)-this.F4;
        System.Console.WriteLine(arg0);
        return ref Program.s_4;
    }
}

public struct S2
{
    public S1 F3;
    public S2(S1 f3): this()
    {
        F3 = f3;
    }
}

public class Program
{
    public static S1[] s_2 = new S1[]{new S1(0)};
    public static bool s_4;
    public static void Main()
    {
        S2 vr0 = new S2(new S1(1));
        s_2[0].M1(vr0.F3.F4, vr0.F3.M1(0, false));
    }
}
```

```csharp
// Generated by Fuzzlyn v1.5 on 2022-02-03 20:11:11
// Run on X86 Windows
// Seed: 3146441340761756415
// Reduced from 127.7 KiB to 0.7 KiB in 00:03:37
// Debug: Throws 'System.NullReferenceException'
// Release: Runs successfully
public struct S0
{
    public int F3;
    public uint F6;
}

public class C1
{
    public S1 M31(C1 arg0)
    {
        return new S1(new C1(), new S0());
    }
}

public struct S1
{
    public C1 F4;
    public S0 F7;
    public S1(C1 f4, S0 f7): this()
    {
    }

    public C1 M26(int arg0)
    {
        if (Program.s_4)
        {
            this.F4 = new C1();
        }

        return new C1();
    }
}

public class Program
{
    public static bool s_4 = true;
    public static long s_20;
    public static void Main()
    {
        S1 vr8 = default(S1);
        var vr9 = vr8.F7.F3;
        S1 vr10 = vr8.F4.M31(vr8.M26(vr9));
        System.Console.WriteLine(s_20);
    }
}
```

**Comment by jakobbotsch** [comment]
The first one needs a little massaging to repro as a console app:
```csharp
// Generated by Fuzzlyn v1.5 on 2022-02-03 20:06:22
// Run on X86 Windows
// Seed: 4993495812901676847
// Reduced from 57.3 KiB to 0.6 KiB in 00:00:48
// Debug: Outputs 1
// Release: Outputs 4294967295
using System;

public struct S1
{
    public uint F4;
    public long F7;
    public S1(uint f4): this()
    {
        F4 = f4;
    }

    public ref bool M1(uint arg0, bool arg1)
    {
        this.F4 = (uint)-this.F4;
        Program.s_rt.WriteLine(arg0);
        return ref Program.s_4;
    }
}

public struct S2
{
    public S1 F3;
    public S2(S1 f3): this()
    {
        F3 = f3;
    }
}

public class Program
{
    public static IRT s_rt;
    public static S1[] s_2 = new S1[]{new S1(0)};
    public static bool s_4;
    public static void Main()
    {
        s_rt = new C();
        S2 vr0 = new S2(new S1(1));
        s_2[0].M1(vr0.F3.F4, vr0.F3.M1(0, false));
    }
}

public interface IRT
{
    void WriteLine<T>(T value);
}

public class C : IRT
{
    public void WriteLine<T>(T value)
    {
        Console.WriteLine(value);
    }
}
```

The second repros out of the box.

**Comment by jakobbotsch** [comment]
Some failures from this weekend's Fuzzlyn run. All of these repro in main (179ffff7967f3136d8f8d0d17510a5460dd01adb) in win-x86 and not on win-x64.
```csharp
// Generated by Fuzzlyn v1.5 on 2022-02-06 17:06:01
// Run on X86 Windows
// Seed: 7854701479455767355
// Reduced from 192.2 KiB to 0.6 KiB in 00:03:51
// Debug: Outputs 0
// Release: Outputs 1
public struct S0
{
    public uint F0;
    public ulong F2;
    public int F3;
    public ushort F6;
    public int F8;
    public int[] M35(int arg0, int[] arg1)
    {
        this.F3 = arg1[0];
        Program.s_rt.WriteLine(arg0);
        return arg1;
    }
}

public class Program
{
    public static IRT s_rt;
    public static int[][] s_28 = new int[][]{new int[]{1}};
    public static void Main()
    {
        s_rt = new C();
        var vr3 = new S0();
        var vr6 = vr3.F3;
        var vr13 = s_28[0];
        var vr12 = vr3.M35(0, vr13);
        vr3.M35(vr6, vr12);
    }
}

public interface IRT
{
    void WriteLine<T>(T value);
}

public class C : IRT
{
    public void WriteLine<T>(T value)
    {
        System.Console.WriteLine(value);
    }
}
```

```csharp
// Generated by Fuzzlyn v1.5 on 2022-02-06 18:06:07
// Run on X86 Windows
// Seed: 525178552114891112
// Reduced from 142.0 KiB to 0.9 KiB in 00:06:35
// Debug: Throws 'System.NullReferenceException'
// Release: Runs successfully
public interface I0
{
}

public class C0
{
    public ushort F0;
}

public struct S0 : I0
{
    public byte F0;
    public bool F1;
    public long F3;
    public byte F4;
    public C0 F5;
    public S0(long f3, C0 f5): this()
    {
        F5 = f5;
    }

    public C1 M24(ref bool arg0)
    {
        this = new S0(0, new C0());
        return Program.s_18;
    }
}

public class C1
{
}

public class Program
{
    public static IRT s_rt;
    public static C1 s_18;
    public static void Main()
    {
        s_rt = new C();
        var vr4 = new S0(0, new C0());
        I0 vr7 = vr4;
        bool vr8 = default(bool);
        S0 vr9 = default(S0);
        var vr10 = vr9.F5;
        var vr11 = vr9.M24(ref vr8);
        M8(vr10, ref vr7, vr11);
    }

    public static void M8(C0 argThis, ref I0 arg0, C1 arg1)
    {
        s_rt.WriteLine(argThis.F0);
    }
}

public interface IRT
{
    void WriteLine<T>(T value);
}

public class C : IRT
{
    public void WriteLine<T>(T value)
    {
        System.Console.WriteLine(value);
    }
}
```

```csharp
// Generated by Fuzzlyn v1.5 on 2022-02-06 16:34:36
// Run on X86 Windows
// Seed: 15345211054104247945
// Reduced from 56.7 KiB to 1.1 KiB in 00:00:55
// Debug: Outputs 0
// Release: Outputs -1
public struct S0
{
    public ulong F1;
    public int F2;
    public byte F3;
    public short F5;
    public long F6;
    public void M4(int arg0, sbyte[] arg1)
    {
        Program.s_rt.WriteLine(arg0);
    }

    public sbyte[] M6(ref int arg0, bool arg1, ref S0 arg2, ref byte arg3)
    {
        var vr0 = Program.s_5;
        Program.M7(arg2, vr0, ref Program.s_6, ref Program.s_10, arg0);
        var vr1 = arg2.F6;
        Program.M8(arg2, vr1);
        arg0 = this.F2--;
        return new sbyte[]{1};
    }
}

public class Program
{
    public static IRT s_rt;
    public static bool s_2;
    public static S0 s_4;
    public static uint[] s_5;
    public static byte s_6;
    public static S0[] s_10;
    public static S0[, ] s_20 = new S0[, ]{{new S0()}};
    public static void Main()
    {
        s_rt = new C();
        S0 vr2 = default(S0);
        new S0().M4(vr2.F2, vr2.M6(ref s_4.F2, s_2, ref s_20[0, 0], ref s_4.F3));
    }

    public static void M8(S0 arg0, long arg1)
    {
    }

    public static void M7(S0 argThis, uint[] arg0, ref byte arg1, ref S0[] arg2, int arg3)
    {
    }
}

public interface IRT
{
    void WriteLine<T>(T value);
}

public class C : IRT
{
    public void WriteLine<T>(T value)
    {
        System.Console.WriteLine(value);
    }
}
```

**Comment by kunalspathak** [comment]
@jakobbotsch - do you think they are related to the forward substitution? Could you open GH issues instead for better tracking?

**Comment by jakobbotsch** [comment]
@kunalspathak Yes I expect so. Opened #64904. I don't really want to open two more yet since it seems very likely they may have the same cause.

**Comment by EgorBo** [comment]
arm64 improvements: https://github.com/dotnet/perf-autofiling-issues/issues/3438
