### PR TITLE
JIT: Unify preheader/exit weight calculation logic

### LINKED ISSUE #98370: [Perf] Linux/x64: 16 Regressions on 2/5/2024 1:05:09 PM
### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.CtorFromCollection&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Dictionary - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.CtorFromCollection(Int32).Dictionary(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Create/CtorFromCollection.cs#L47-#L48>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3NvZ4CaO3bQiwhVp2kKBoJDkDSF0sbfxofuw9s5tXCF+O3dOlDaphPxi3Y5nZvfWu54CMzWCBGXNqz/koQQEcllzUcyh0iTLCC20VWD7WCvLJdBD1iUylZctD+HO9EtghelLxtURcYx5yS3k1mUjXJGAbs5OaUQoQ+kO4Z69BGO/MQne8wNdNMaC7E20EE7LtTK9idV4g1o+Ye9vlU2Ti94Vb0OGTbDgjzAiw0ESPtUxr9VEqzu+rpG1Vj/oRMuKizaa6gLoT5L9JdRyRy/o6/8pHfSFq2KnkDxH/UzADcjKNsEL4VjbsAPtVpuv4l62nevC/2yu1Zor6ML1xl14U610x3I91X0DwArBPbtIZmu9bKpOBc/KxvCciZn76NojXYWfmhXy4qPQKyb4Y4t1kc2TedcM15sK0G2Fakf2cIgn2m0M4FJXu9PhQiydbGGZrMgFKZgFv1xBEifpyWBwMkiX8flo+G6UJL1hepoOzs7fxvEojn0KU0vJ0A04Ybj+JdkmaA19BRF5E5JVc5Qh2i9V5Ef5ew01OJ8K9W+3QC/IczC1sBm6qovg2U22+PgekK2dUxpGpLXyxtkNclCFaPaIb1Yb+JLRvQMk/o55ydCSB25LEhjXPDDZXhORTa5FLVV2XFOzxU22LcIRLbcCMnrlWud+I80u9BISKBN6zFSC24xtwIT/ALqJOTHoBAAA>)</li></ul> | 1.34 μs | 1.59 μs | 1.19 | 0.01 | False | | |
|<ul><li>[SortedList - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.CtorFromCollection(Int32).SortedList(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Create/CtorFromCollection.cs#L56-#L57>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/aMBR9n7T/4LckWwohlLGipRplbdetTAx4m6bJxLfEkz+ia6cl1bTfPjsgWqg05SWyT8459/jGN1OgpkKQoKx59Yc8FIBALiou2BxKTbKMBExbBbaLlbJcQnDIukCq8qLhIdyZbgGUma6kXB0Rx5gX3EJuXTXCFQmDzbvTICYBRekW0Z69BGO/UQne82OwqI0F2ZloIZyWa2U6E6vxCrV8wj7cKNtPzzsLjRbYLTc2XPBHGJFBL42ecswrNdHqjq8rpI3Vj2CiZclFs5tqBsFPkv0lgeWOzoLX/1M66CtXbKeQPEf9TMANyNLW4QvhWNuoBe1Gm1txL5vOteF/MZdqzRW04XrjNrypVrplXE913wCwRHDPNpLZWi/rslXgWVEbnlMxcx9de6St8HO9Qs6uhV5RwR8brI1sns7bVrjclIBuKlRzZQ8v8US7iQFc6nK3OhyIpZMtLJUlOSeMWvDDFaZJ2j/p9U56/WUyHA3ORmnaGSanw/eDs7dJMkoSX8JUUlJ0F5xQXP+SdBM2hj5BTN5EZFUfVYj3QxX7q/y9ggqcT4n6txugF+Q5mErYDF1qFj47yRYf3wPStXPqRzFprLxxdoUcFBP1HvHNajY+Mrp3gMSfMS8oWvLAbUFC45oHJttrYrLJtaikyo4z1VvcZNsQjmi5FZAFn1zr3G+k3m29hITKRB4zpeA2oxsw0T9P1E8C6AQAAA==>)</li></ul> | 6.01 μs | 7.29 μs | 1.21 | 0.21 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.CtorFromCollection%28Int32%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.CtorFromCollection&lt;Int32&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.Sort&lt;BigStruct&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Array_ComparerClass - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Sort(BigStruct).Array_ComparerClass(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Sort.cs#L47-#L48>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBM7aYsa4YokFCgQVJK8IVRd7G186D6svXUbV4jfzp0ThSaVkF8s33hmdm616xlwWyMo0GRf/GYPJSCwSS1kMYfKsCxjQWFIA/Wx1iQUBIesCXKdly0P4c72S+CF7Ssu9BFxjHkpCHJy1ZjQLAw256dBzAKOyr1Ee/YSLH3jCrznu2DRWALVmxopnVYYbXsLg/R2ItYLwjqny94YkTe3U6MqjoBTya0NF+IRRuwsHUT/YsxrPTX6Tqxr5K3Tj8CLhGxPM1NA8JNlf1hAwtGL4OX/lA76InSxUyiRo3kiEBZURU34TDg2FHWgXRv7Vd6rtnFd+J/tlV4LDV243rgLb2a06RjXU681AVYI7tlFcrM2y6bqFPimbKzIubxBo4xHugo/NSsUxUdpVlyKxxbrIpsP5l0rXG0qQLcUup3YwxmeGrcwgEtT7d4O92HpZAviqmKXrOAEfrfCQTIYnqTpSTpcJm9GZxejYdo7Ty/S5DR5nSSjJPElbK0URzfgjOP6VvFN2Br6BDF7FbFVc1Qh3u9U7Ef5ew01OJ8KzS+3U8/Ic7C1pAxd6iJ8cpMtPr4H5GvnNIxi1lp54+wDCtCFbPaIb1Z78JHRfQNk/o55yZHYg6CShdY1D2y218RskxtZK50dZ2q2uM22IRyRBEnIgveude4v0uyOXsJCbSOP2UoKyvgGbPQXJz6AuucEAAA=>)</li></ul> | 12.50 μs | 15.82 μs | 1.27 | 0.27 | False | | |
|<ul><li>[Array_Comparison - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Sort(BigStruct).Array_Comparison(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Sort.cs#L53-#L54>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBMnaZMS4Yo0FCgQFJK8IVRd7K196D6svbs2jhC/nTsnCk0qIb9YvvHM7Nxq1zOg2iIIkEa/+E0eS0Ag15bxfAGVImlKglwZCaaLVhomIDhmXSOVWdnwEO51twSa666gTJ4QJ5iVzEBmXDXCJAmDzfA8iElAUbiX6MBegTbfqADv+S5Y1tqA6EwV507LlNSdpULz9poVS4M2M1edCSKt76ZKVBSZVjJcsi2MyUWvH/3LsLByquQ9KyzSxuZH4BWMN6eZyiH4SdI/JDDM0fPg5f+UDvrCZL5XCJaheiJgGkRl6vCZcKJM1IJ2q/RX/iCarrXhf9Y3smAS2nC9cRveTEnVMq6n3koDWCG4ZxvJvFCrumoVeF7WmmWUz1EJ5ZG2wk/1Gln+kas15WzbYG1ki/6ibYWbTQXoNkI243o8wFPltgVwpar92/EyrJxsaaioyBXJqQG/WGE/6Q/Oer2z3mCVjMYXb8aDXmd0eTk6Hw5fJ8k4SXwJbYVwY74FQrG4E3QTNoY+QUxeRWRdn1SIDwsV+1H+bsGC86lQ/XIL9Yy8AG25SdGlzsMnN9nhkwdAWjinQRSTxsobpx+Qgcx5fUB8s5qDj4zuGyDxd8xKioY8MlOSULvmgU4PmphsMsWtkOlppnqH63QXwhENMxzS4L1rnfuF1Pujl5BQ6shjuuLMpHQDOvoL76S0aeQEAAA=>)</li></ul> | 11.48 μs | 15.15 μs | 1.32 | 0.23 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.Sort%28BigStruct%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.Sort&lt;BigStruct&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Tests.Perf_Enum

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[TryParseGeneric_Flags - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Tests.Perf_Enum.TryParseGeneric_Flags(text%3a%20%22Red%2c%20Orange%2c%20Yellow%2c%20Green%2c%20Blue%22).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime/Perf.Enum.cs#L80-#L83>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U227TQBB9R+IfRn2xDW6aC4I2khFtSEOBQEjzghCKNvY0XrQXa3bd2BXi29l1otCkEvKLtXP2nJmzoxlPkZmSUKKy5tlv2ORICFclF9kcCw1JAkGmrUJ7RqWyXGJwyLoiptK84RHembMcWWbOJOPqiHhJac4tptZVA64gDKrXr4IYAkbSHaI9e4HGfmESfc53wW1tLMqOB01nhnS3HKvSxVTPGBmcoELi6fJasLUJLVZ2CCdzzGL46oytMYbvKITexDAhRBXDlSjxJPrnbV6qkVZ3fF0Ss1wr8yMYaVlw0URTnWHwE5I/EFju6Fnw/H9KB33iKtspJE9JPxJwg7KwdfhEeKlt1IJ2o81ncS+bbrbhfzRjteYK23B94ja8qVa6pV1PvVEWqSB03zaS2Vov6qKV4VleG54yMSMttUfaCj/UK+LZROgVE/yhwdrI5v152wrjqnAz6TfKj/HhYI+02yKkhS52p8MlWTjZrWWygLeQMYt+4cJ+tz847fVOe4NF93zY7Q57g07/fHDRv3jz0kXdri9hSikZ8QcERuulZFXYJPQOYngRwao+qhDvFy32o/ytxBJdnoL0L7ekT8hzNKWwCTnXWfjoJVv88h6J+W0bRDE0qXzi5Jo4qkzUe8Q3qwm8ZXJ3SODfmOaMLGy4zSE0rnlokr0mhirVopQqOfZUb3GTbE04ouVWYBK8d61zv5Z6F3oJhMpEHjOF4DZhFZroL4tR+PX8BAAA>)</li></ul> | 82.35 ns | 91.92 ns | 1.12 | 0.09 | False | | |
|<ul><li>[Parse_Flags - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Tests.Perf_Enum.Parse_Flags(text%3a%20%22Red%2c%20Orange%2c%20Yellow%2c%20Green%2c%20Blue%22).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime/Perf.Enum.cs#L75-#L78>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/rPpiG9x8FlQiGZGEtBQIhDQvCKHoYm/iQ/dh7Z3buEL8du6cKDSphPxiecczu3OrG0+RmZJQorLm2W+4z5EQRiUX2RwLDUkCQaatQtumUlkuMThmjYipNK95hGvTzpFlpi0ZVyfEIaU5t5haNw24gjDYvr4IYggYSfcSHdgLNPYLk+h7vgtuK2NRtjxoWjOk9XKiStmaMTK4vBJsY0KLWzuAszlmMXx1djYYw3cUQt/HcE2IKoaRKPEs+udoXqqxVmu+KYlZrpX5EYy1LLioq6nOMPgJyR8ILHf0LHj+P6WDPnGV7RWSp6QfCbhBWdgqfCIcahs1oN1o81ncyXqHTfgfzURtuMImXN+4CW+qlW5o11NvlEUqCN2ziWS20YuqaGR4lleGp0zMSEvtkabCD9WKeHYt9IoJ/lBjTWTz3rzphMm2QHL5UPXlPb7OY+2yg7TQxf7tOBoLJ7u1TBbwFjJm0ccs7HV6/fNu97zbX3QuB53OoNtvXby66L7pXb50VafjR5hSSkb8AYHRZinZNqwbegcxvIhgVZ1MiA/xiv1V/lZiia5PQfqXi+YT8hxNKWxCznUWPjrJDh/eITGftn4UQ93KN06uiKPKRHVA/LLqwlsm9w0J/BnTnJGFe25zCI1bHprkoIlhm2pRSpWceqp2uEl2JhzRciswCd671bkfSrUvvQRCZSKPmUJwm7AtmugvZ3fVQvIEAAA=>)</li></ul> | 139.37 ns | 149.67 ns | 1.07 | 0.04 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Tests.Perf_Enum.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Tests.Perf_Enum*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.Sort&lt;IntStruct&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[List - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Sort(IntStruct).List(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Sort.cs#L59-#L60>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U227TQBB9R+If9s02uImTcGkjXJGGFgoNCkneEEIbexov2os1O27tCvHt7DpRaFIJ+cXaOT7nzOx4xjPgtkJQoMk++83uC0BgF5WQ+QJKw9KUBbkhDdTHSpNQEByyLpDrrGh5CLe2XwDPbV9xoY+IE8wKQZCRy8aEZmFQv3kVxCzgqNwh2rNXYOkrV+A93wfLxhKo3tRI6bTCaNtbGqR315qWhFVG570bYSlcigcYs9eDYfQv76LSU6NvxaZC3kq/B1OjSiHbaGZyCH6w9A8LSDh6Hjz/n9JBX4TOdwolMjSPBMKCKqkJnwgnhqIOtGtjb+SdajvVhf/ZXuqN0NCF64278GZGm47leqr7AoAlgnt2kcw3ZtWUnQqeF40VGZdzNMp4pKvwU7NGkX+UZs2leGixLrLFcNE1w2VdArot0O2IHg7t1LgNAVyZcnc6XICVky2Jq5Kds5wT+GUKh8lwdDIYnAxGq+R0nCTj4Wnv7OxtkgySly5KEp/CVkpxdAPOOG5+Kl6HraGvIGYvIrZujjLE+yWK/Sh/q6AC51Oi+eWW6Al5AbaSlKKrOg8f3WSLT+4A+cY5jaKYtVbeOL1CATqXzR7xzWoDXzK6d4DM3zErOBK7F1Sw0LrmgU33mpjVmZGV0ulxTc0Wt+m2CEckQRLS4INrnfttNLvQS1iobeQxW0pBKa/BRn8BLnS0ZtgEAAA=>)</li></ul> | 7.14 μs | 8.05 μs | 1.13 | 0.50 | False | | |
|<ul><li>[Array - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Sort(IntStruct).Array(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Sort.cs#L44-#L45>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBM7IRAiXJGGAgWCQpI3hNDF3saH7sPaW7dxhfjt3DlRaFoJ+cW6Hc/M7q13PQduawQFmuyT3+y2BAR2UQtZLKEyLMtYUBjSQH2sNQkFwSnrArnOy5aHcG37JfDC9hUX+gFxinkpCHJy2ZjQLAx2L18EMQs4KneIjuw1WPrKFXjPt8GqsQSqNzNSOq0w2vZWBunNlaYVYZ3TeW+KyJtwJe5gwkbpIPqXeFnrmdHXYlsjb7Xfg5lRlZBtNDcFBD9Y9ocFJBy9CJ7+T+mgz0IXB4USOZp7AmFBVdSEj4RTQ1EH2pWxX+SNalvVhf/JXuqt0NCF64278OZGm47leqr7BIAVgnt2kSy2Zt1UnQpelI0VOZcLNMp4pKvwY7NBUXyQZsOluGuxLrLlYNk1w+WuAnRroNsZPZ3amXErArg21eF0ugFrJ1sRVxU7ZwUn8NsUDpLB8CxNz9LhOhlPkmQyeN1LX6Xj0Wj83EVJ4lPYWimObsAZx+1PxXdha+griNmziG2aBxni4xbFfpS/1VCD86nQ/HJb9Ii8BFtLytBVXYT3brLHpzeAfOuchlHMWitvnL1HAbqQzRHxzWoDXzK6d4DM3zEvORK7FVSy0Lrmgc2OmpjtciNrpbOHNTV73Gb7IhyRBEnIgneude6/0RxCL2GhtpHHbCUFZXwHNvoL5x2lDtkEAAA=>)</li></ul> | 5.01 μs | 7.62 μs | 1.52 | 0.49 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.Sort%28IntStruct%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.Sort&lt;IntStruct&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Buffers.Text.Tests.Utf8ParserTests

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[TryParseInt64 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt64(value%3a%209223372036854775807).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Buffers/Utf8ParserTests.cs#L20-#L22>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UwY7TMBC9I/EPviWBbpsm3TZUCqItCyxQVLrhhBByk2ljFNvR2OkmK8S3Y6dV2XYllIvleXlv5tmZ8RKoqhA4CK2e/Sb3OSCQecWKbA2lJHFMnExqAXqAldCMg3POmiMVad7yELZqkAPN1IBTJi6IM0xzpiHVphphgrhOPR45PeJQ5GbjndgJKP2FcrA53zh3jdLA+/NquwVU/QRqbRalVf+b3kYrigrwECfYtOGt0OORu6dFBVPyKgjCcBL44Ti6Hk0m15E/8f4ZW1diIcWW7SqkmkmhvjsLyUtWtNFSZuD8IPEf4mhm6Jnz/H9KA31iIjsqOEtRPhIwBbzUjftEOJPa60C7lepzseftVXbhf1Q3YscEdOHaxF14SylkR7uWan4EYIlg1i6S1U4mTdnJ8CpvFEtpsULJpUW6Cj80G2TZ+0JuaMEeWqyLbB2su1a4qUtAMyai7eHzrl5IM0KmXWV53J1PSGJkd5rykrwmGdVgp80N/CC8Gg6vhmHiR1Pfn4ZRfxiMwmgcvDSR79sSquKcInsAQnH3k9PabRNaBz3ywiOb5qJC7zRlPdvKXyuowOQpUf4yE/qEvAZVFTpG4zpzH53kgM/2gHRnMoVej7SpbOL4HTIQWdGcEHtZbWAto/kGSOwZ05yiJvdM58Q108xAxSdNj9SpLCou4ktPzQFX8cGEIWqmC4idt+bqzLvSHEMrIa5QnsVUWTAd0xqU9xePHXyM+QQAAA==>)</li></ul> | 14.40 ns | 17.99 ns | 1.25 | 0.10 | True | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Buffers.Text.Tests.Utf8ParserTests.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Buffers.Text.Tests.Utf8ParserTests*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.Perf_Frozen&lt;Int16&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[TryGetValue_True - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Perf_Frozen(Int16).TryGetValue_True(Count%3a%2064).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Frozen/Perf_Frozen.cs#L82-#L91>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U247TMBB9R+If/JYEsm16UYGKrNgtewOKSjfiBaHKTaaNkS/R2N5tKsS3Y6dV2XYllJfIMznnzPFkJlOg2iIIkEa/+E0eS0Agl5bxYg6VImlKgkIZCaaLVhomIDhGXSKVedngEFa6WwItdFdQJk+AF5iXzEBuXDXCJAmDzWgYxCSgKNwhOqAz0OYrFeA1PwT3tTYgOhPFueMyJXVnBrhaXKPagnx/J01vdN7JsL4B851yC4sMLYQT5dyOyWgY/bMxt3Ki5IqtLdJG6UcwUaJivImmqoDgJ0n/kMAwBy+Cl/9jutRnJos9Q7Ac1RMC0yAqU4fPiBfKRC1gd0p/4Q+iaVwb/Cd9JddMQhusF26DmyqpWtr1UPclACsE92xDma1VVletDM/KWrOc8hkqoXymLfG2XiIrbrhaUs62Ta4Nbd6ft61wtakA3VLIZmKPZ7gZQcBMVfvT8T5kjnZvqKjIOSmoAb9bYT/pD856vbPeIEvejpNkPOx3kl6SvHszfO2iJPEltBWCItsCobheCLoJG0HvICavIrKsTyrEh52K/Sh/s2DB6VSofrmdegaeg7bcpOhcF+GTm+zyFw+AdO2UBlFMGikvnF4jA1nw+pDxzWoCbxndO0Di75iXFA15ZKYkoXbNA50eODHZ5IpbIdNTT/Uur9OdCQc0zHBIg4+ude4vUu9DTyGh1JHP6Yozk9IN6Ogv1AAvGecEAAA=>)</li></ul> | 184.83 ns | 271.49 ns | 1.47 | 0.28 | False | | |
|<ul><li>[TryGetValue_True - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Perf_Frozen(Int16).TryGetValue_True(Count%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Frozen/Perf_Frozen.cs#L82-#L91>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U227aQBB9r9R/2DfbrQM2JBShOiqhubWlosTqS1WhxR7wVnuxZtcJRlW/vbsG0UCkyi/WzvicM2fHM54C1RWCAGn0q9/kqQAEclUxns+hVCRJiJcrI8F0sZKGCfCOUVdIZVY0OISV7hZAc90VlMkT4BizghnIjK1GmCS+txmceyHxKAp7CA7oFLT5SgU4zQ/eQ60NiM5EcW65TEndmQGuFjeotiDf30sTDy47Kda3YL5TXsEixQr8ibJuR+Qi7gX/fMwrOVFyxdYV0kbqhzdRomS8iaYqB+8nSf4QzzALz73X/2Pa1Gcm8z1DsAzVMwLTIEpT+y+IY2WCFrB7pb/wR9F0rg3+k76WayahDdYJt8FNlVQt7Tqo/RSAJYJ9tqHM1iqty1aGZ0WtWUb5DJVQLtOWeFcvkeW3XC0pZ9sm14Y2783bVrjelIB2K2QzssdD3MwgYKrK/el4IVJLezBUlOSS5NSAWy6/F/X6Z3F8FvfTaDiKotF5rxMP48HF8N1bG0WRK6ErISiyLRCK64WgG78RdA5C8iYgy/qkQnhYqtCN8rcKKrA6JapfdqlegOegK24StK5z/9lNdvnxIyBdW6V+EJJGygknN8hA5rw+ZFyzmsBZRvsOkLg7ZgVFQ56YKYivbfNAJwdOSDaZ4pWQyamnepfXyc6EBRpmOCTeR9s6+xup96GjEF/qwOV0yZlJ6AZ08BekhH2y6AQAAA==>)</li></ul> | 1.84 μs | 2.17 μs | 1.18 | 0.16 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.Perf_Frozen%28Int16%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.Perf_Frozen&lt;Int16&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.Perf_DefaultFrozenDictionary

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[TryGetValue_True_FrozenDictionary - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Perf_DefaultFrozenDictionary.TryGetValue_True_FrozenDictionary(Count%3a%20100).html>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U247TMBB9R+If/JYEsm16YVlVCqLbvQJFpRvxglDlJtPGyJdobO82FeLbsdOqbLsSykvkGZ9z5ng0kylQbREESKNf/SZPJSCQS8t4MYdKkTQlQaGMBNNFKw0TEByjLpHKvGxwCCvdLYEWuisokyfAMeYlM5AbV40wScJgcz4MYhJQFO4QHdAZaPOVCvCaH4OHWhsQnYni3HGZkrozA1wtrmBFLTc3qLYgr1hzRbHuZFjfgvlOuYVFhu5ziggnyj1kRHpJEv2zOLdyouSKrS3SpsqPYKJExXgTTVUBwU+S/iGBYQ5eBK//x3Spz0wWe4ZgOapnBKZBVKYOXxDHykQtYPdKf+GPomlqG/wnfS3XTEIbrBdug5sqqVra9dB7aQArBPdtQ5mtVVZXrQzPylqznPIZKqF8pi3xrl4iK265WlLOtk2uDW3en7etcL2pAN3CyGaaj+e7mUHATFX70/GuZI72YKioyAdSUAN+78J+0h+c9XpnvUGWXIySZDQcdobv3g8v+udvXeTG2YloKwRFtgVCcb0QdBM2gt5BTN5EZFmfVIgP+xb7Uf5mwYLTqVD9cvv2AjwH7bYuRee6CJ+9ZJcfPwLStVMaRDFppLxweoMMZMHrQ8Y3qwm8ZXR3gMS/MS8pGvLETElC7ZoHOj1wYrLJFbdCpqee6l1epzsTDmiY4ZAGV6517g9T70NPIaHUkc/pijOT0g3o6C9gMufcAwUAAA==>)</li></ul> | 937.72 ns | 1.02 μs | 1.09 | 0.01 | False | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.Perf_DefaultFrozenDictionary.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.Perf_DefaultFrozenDictionary*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Numerics.Tests.Perf_BigInteger

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Divide - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Numerics.Tests.Perf_BigInteger.Divide(arguments%3a%201024%2c512%20bits).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime.Numerics/Perf.BigInteger.cs#L87-#L90>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UUW/aMBB+n7T/4LckWwoJMFRVyjSg3dZtVIzyNk2VSY7kptiOzg4l1bTfPjsgVqg05SXyffm+u8+Xu8yB65pAgDT61W/2WAABm9ZYZkuoFEsS5mXKSDB9qqVBAd4pa0pcpkXLI9jofgE8033BUZ4RJ5QWaCA1thpDyXxvNx55IfM4CXsIjuwVaHPHBbicH7z7RhsQvbtaAGGqe+6t7i2ANg9TzG+lgRyod41bzMDnlNftTa5YHA1G4bt4wNZodPDPy7KWMyU3mNfEDSqpf3gzJSos22iuMvB+suQP8wxaeua9/p/SQl9RZgeFwJTUMwFqEJVp/BfCiTJBB9qt0t/KrWi714X/Rd/IHCV04brEXXhzJVVHu47qvgdVBPbZRbLI1aqpOhleFI3GlJcLUkI5pKvwc7MmzD6Vas1LfGqxLrLlYNm1ws2usrPp5s6N7ekgz5TdGqCVqg6n06VYWdm94aJi71nGDbgF8wfRYHgRxxfxcBVdXkXxVRT1RqPLaDyO3kaRjVwJXQvBCZ+A2aF/EHzntwmdg5C9Cdi6OasQHhcrdKP8vYYabJ6K1C+7lC/IS9B1aRKyrjP/2U32+GQLxHObaRiErE3lEicfCUFmZXNEXLPawFkm+w6IuTumBSfDHtEUzNe2eaCToyZku1SVtZDJuadmj+tkb8ISDZoSEu/ats7+SppD6CTMl3btLaarEk3Cd6CDv+EIkGPsBAAA>)</li></ul> | 428.25 ns | 586.51 ns | 1.37 | 0.07 | False | | |
|<ul><li>[ToStringD - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Numerics.Tests.Perf_BigInteger.ToStringD(numberString%3a%20123).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime.Numerics/Perf.BigInteger.cs#L42-#L45>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBPnQwVFMiJJCy2QKiR+Q6i62Bt7ke/O2ju3cYX47dw5UWhSCfnFuh3P7M6td70ArmsCAdLoV7/ZYwEEbFZjma2gUiyOmZcpI8H0qZYGBXinrBlxmRYtj2Cr+wXwTPcFR3lGnFJaoIHU2GoMJfO93eXYC5nHSdhDcGQnoM0dF+ByfvTWjTYgene1AMJU99xb3VsCbe9nmN9KAzlQL1FrQyjzK1/WYgO0jyZsMBwF/3ysajlXcot5TdygkvqHN1eiwrKNFioD7yeL/zDPoKVn3uv/KS30FWV2UAhMST0ToAZRmcZ/IZwqE3Sg3Sr9rXwQbee68L/oa5mjhC5cl7gLb6Gk6mjXUd23oIrAPrtIlrlKmqqT4WXRaEx5uSQllEO6Cm+aDWH2uVQbXuJTi3WRrYarrhWud5WdS7c9bmRPh3iu7MYAJao6nE4XIrGyteGiYh9Yxg245fKH0XB0MRhcDEZJ9H4SDSZR1LuM3o0H49HbKLKRK6FrITjhEzBO+b3gO79N6ByE7E3ANs1ZhfC4VKEb5e811GDzVKR+2YV8QV6BrksTk3Wd+c9ussenD0A8t5lGQcjaVC5x/IkQZFY2R8Q1qw2cZbLvgJi7Y1pwMuwRTcF8bZsHOj5qQrZLVVkLGZ97ava4jvcmLNGgKSH2rmzr7G+kOYROwnypA4fpqkQT8x3o4C8UCEDA6AQAAA==>)</li></ul> | 16.14 ns | 18.14 ns | 1.12 | 0.07 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Numerics.Tests.Perf_BigInteger.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Numerics.Tests.Perf_BigInteger*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.ContainsKeyFalse&lt;Int32, Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[ConcurrentDictionary - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.ContainsKeyFalse(Int32%2c%20Int32).ConcurrentDictionary(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Contains/ContainsKeyFalse.cs#L99-#L108>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBs7ARpFuCJNWyglKCR5Qwhd7G186D6svXMbV4jfzp4ThSaVkF/su/XM7Nx696bAbY2gQDv74jd7KAGBXdRCFnOoDMsyFhTGaXA9rLUTCoJD1AVynZctDuHO9krghe0pLvQRcIx5KRzkjrIxoVkYbN69CWIWcFS0iPboJVj3lSvwmh+CRWMdqNOJkZK4wmhLa+1I395Cc82lhfc32g36MWtf5/5zXiPSgS5Fy+DYhAvxCCP2Nu1H/2zNa03YO7GukbfK34OJUZWQ7W5qCgh+sOwPC5wgeBG8/B+TQrdCFzuGEjmaJwRhQVWuCZ8Rx8ZFHWA3xn6R96otZBf8Z3ul10JDF6wX7oKbGm062vVQ+huAFQI9u1Bma7Nsqk6GZ2VjRc7lDI0yPtKV+KlZoSg+SrPiUjy2sS60eX/eNcPVpgKkIdFtBx/29MTQAAEuTbVbHc7HkmgLx1XFzlnBHfhZC/tJf3CSpifpYJkMR0k6Ss5Oh2dpMhymr5NklCQ+ha2V4kgNzjiufyq+CVtB7yBmryK2ao4yxPsZi30rf6uhBtKp0PyiGXsGnoOtpcuQXBfhk5Ns4+N7QL4mpUEUs1bKC2fXKEAXstlHfLHajbdM01kAMn/GvOTo2INwJQstFQ9stufEbJMbWSudHXtqtnGbbU0Q0AknIQsuqXR0qzS7raewUNvIx2wlhcv4Bmz0FyYqkWL3BAAA>)</li></ul> | 1.83 μs | 2.02 μs | 1.11 | 0.06 | False | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.ContainsKeyFalse%28Int32%2C%20Int32%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.ContainsKeyFalse&lt;Int32, Int32&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [c3940f603a42e5c78f888ba2cbab76fbfda29d83](https://github.com/dotnet/runtime/commit/c3940f603a42e5c78f888ba2cbab76fbfda29d83)
Compare | [7c90c578310f0071374878d002871418533ec005](https://github.com/dotnet/runtime/commit/7c90c578310f0071374878d002871418533ec005)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3940f603a42e5c78f888ba2cbab76fbfda29d83...7c90c578310f0071374878d002871418533ec005)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.CreateAddAndClear&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Array - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.CreateAddAndClear(Int32).Array(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/CreateAddAndClear.cs#L28-#L39>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBM7KRAiXOGaAgWCQpI3hNDFt40P3Ye1d27jCvHbuXOi0KQS8ovlG8/Mzq12PQNqGgQJyponv8ldBQjksuGCLaDWJMtIwLRVYIfYKMslBMesS6SqrDoewo0ZVkCZGUrK1Qkxx7LiFkrrqhGuSBhsX54HMQkoSvcSHdgrMPYrleA93wbL1liQg0IL4bRcKzMoEKiFnLFcsUIAxTfXyo5HF4Mckbbhkt/DlLxIR9G/BItGFVrd8E2DtDP5HhRa1lx0p5lmEPwg2R8SWO7oLHj6P6WDPnPF9grJS9QPBNyArG0bPhLm2kY9aNfafBG3sutZH/4nc6U2XEEfrjfuw5tppXvG9VTXfsAawT37SOYbvWrrXoHnVWt4ScUctdQe6Sv82K6Rsw9Cr6ng9x3WR7YYLfpWuNrWgG4fVDesx+NbaLcrgCtd79+OV2HlZEtLZU0uCHOj7NcqHCWj8VmanqXjVTKZJuk0fT14lUwm55P0eZJMk8SXMI2UFN2AE4qbn5Juw87QJ4jJs4is25MK8WGdYj/K3xpowPnUqH+5dXpEXoBphM3QpWbhg5vs8PwWkG6c0ziKSWfljbP3yEEx0R4Q36zu4COj+wZI/B3LiqIld9xWJDSueWCygyYm21KLRqrsNFO7w022C+GIllsBWfDOtc79QNr90UtIqEzkMVMLbjO6BRP9BZTEcBLiBAAA>)</li></ul> | 392.75 ns | 551.57 ns | 1.40 | 0.02 | True | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_13_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.CreateAddAndClear%28Int32%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.CreateAddAndClear&lt;Int32&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d55701b1-92f9-4597-ae83-225f337335c6e7ef0872a4c4719af/06e5756c-c119-4cc9-97bb-786fda328373.zip?sv=2021-08-06&se=2024-03-06T04%3A46%3A06Z&sr=c&sp=rl&sig=FNX1%2Bi3QaZz1leldjkW594i%2Fn6kU6GgfUTSTO8JNuGo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-25d51f60-c7f5-40c1-ad45-a7918c72b2f2fe1e16bd4814ea999/9d65ea19-9cf4-46c6-a6b9-1e68fb531c4c.zip?sv=2021-08-06&se=2024-03-06T15%3A57%3A06Z&sr=c&sp=rl&sig=lG%2FPDMtywKeG%2FMBFc%2FiIt8KyF8rHoAjBxCOF5h5wgww%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by jakobbotsch**
The preheader/exit weight calculation is essentially the same logic, so unify it to use the logic from the exit weight calculation. This also fixes a bug in the preheader weight calculation introduced by my recent change where we sometimes mistakenly used the weight of the newly inserted preheader instead of the header block to compute a likelihood.

The bug was here:
https://github.com/dotnet/runtime/blob/d4643138e8b9f23482618a32535cc40552da0bb7/src/coreclr/jit/optimizer.cpp#L3075-L3087

The `succ == preheader` case should have computed the `loopEnterCount` as `loop->GetHeader()->bbWeight` which is what the logic used to do before #96843. Of course this estimate is itself questionable, but better than using the newly inserted preheader's weight, which is always `100`.

Fix #98370

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=565813&view=ms.vss-build-web.run-extensions-tab)

File: src/coreclr/jit/optimizer.cpp [hunk 1]
```diff
@@ -3336,60 +3208,61 @@ weight_t Compiler::optEstimateEdgeLikelihood(BasicBlock* from, BasicBlock* to, b
...
+//   block - The new preheader or exit block
 //
-void Compiler::optSetExitWeight(FlowGraphNaturalLoop* loop, BasicBlock* exit)
+void Compiler::optSetWeightForPreheaderOrExit(FlowGraphNaturalLoop* loop, BasicBlock* block)
 {
     bool hasProfWeight = true;
 
-    // Inherit first estimate from the exit target; optEstimateEdgeLikelihood
+    assert(block->GetUniqueSucc() != nullptr);
+    // Inherit first estimate from the target target; optEstimateEdgeLikelihood
```
Comment (AndyAyersMS) [inline src/coreclr/jit/optimizer.cpp:3223]:
```suggestion
    // Inherit first estimate from the target; optEstimateEdgeLikelihood
```

**Review by AndyAyersMS — APPROVED** [review]

File: src/coreclr/jit/optimizer.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/optimizer.cpp:3223]: Will include this as part of a future PR.
