### PR TITLE
Intrinsic support for transient codegen.

### LINKED ISSUE #115429: R2R + Jit issue when inlining intrinsic methods
Based on a [discussion in the open PR](https://github.com/dotnet/runtime/pull/115345#discussion_r2078278919), when an intrinsic is JIT'd an AV occurs later in [CEEInfo::getArgType](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/jitinterface.cpp#L9554) when it calls `GetModule(sig->scope)` which calls [GetDynamicResolver(scope)->GetDynamicMethod()](https://github.com/dotnet/runtime/blob/3bacc83b4f3d21df591cc25b667b5198d8cebcff/src/coreclr/vm/dynamicmethod.h#L410).

This is a random exception, and only occurs in a release (or checked) build of the runtime when R2R is used on S.P.Corelib. Setting "dotnet_readytorun" to `0` prevents the exception. So when the JIT compiler decides to JIT the intrinsic method that was compiled for R2R, it causes the AV.

Repro:
1) Clone the PR referenced above
2) Change the class `InstanceCalliHelper` in file `src\coreclr\System.Private.CoreLib\src\System\Reflection\InstanceCalliHelper.cs` so that every `[MethodImpl(MethodImplOptions.NoInlining)]` is replaced with `[MethodImpl(MethodImplOptions.AggressiveInlining)]`
3) Build runtime in release or checked.
4) Run the test System.Reflection.Tests.MethodInfoTests.TestProperties
5) You may want to put a breakpoint in `MethodDesc::GenerateFunctionPointerCall(DynamicResolver** resolver, COR_ILMETHOD_DECODER** methodILDecoder)` (file `instancecaii.cpp`) to encourage the timing necessary to repro.
6) Run this a few times until the failure occurs. If the breakpoint is hit in the step above, the exception should occur afterwards.

Sample repro:
```
cd C:\git\YOURREPO\artifacts\bin\System.Reflection.Tests\Release\net10.0

C:\git\YOURREPO\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe exec --runtimeconfig System.Reflection.Tests.runtimeconfig.json c:\Users\YOURALIAS\.nuget\packages\microsoft.dotnet.xunitconsolerunner\2.9.0-beta.24475.5\tools\net9.0\xunit.console.dll System.Reflection.Tests.dll -method System.Reflection.Tests.MethodInfoTests.TestProperties
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
The previous transient codegen paths only handled lifetime management when the method had no metadata back IL (that is, RVA == 0). The InstanceCalli scenario creates intrinsic methods which have metadata, but that metadata is copied and then modified falling into a middle ground that the existing logic didn't handle properly. The tricky scenario is when these new instrinsic types were inlined (lifetimes were being ignored). This change fixes that up but did require a bit of clean-up in the `UnsafeJitFunction` as it relates to the JIT and interpreter interaction.

Fixes #115429

### CODE REVIEW

**Comment by jkotas** [comment]
The failure looks related
```
Beginning scenario: RunBasicScenario_UnsafeRead
ASSERT FAILED
	Expression: GetRVA() == 0
	Location:   line 21 in /Users/runner/work/1/s/src/coreclr/vm/asyncthunks.cpp
	Function:   TryGenerateAsyncThunk
	Process:    31332
App Exit Code: 22
```

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -7494,19 +7494,24 @@ static bool getILIntrinsicImplementationForActivator(MethodDesc* ftn,
 
 //---------------------------------------------------------------------------------------
 //
-
-static void getMethodInfoHelper(
-    MethodInfoHelperContext& cxt,
+void CEEInfo::getMethodInfoWorker(
+    MethodInfoWorkerContext& cxt,
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:7498]: Does the caller really need to pass `MethodInfoWorkerContext` into this method from the outside? As far as I can tell, the only reason why it is needed is because of the IL is partially computed in `JitCompileCodeLockedEventWrapper` so that we can include the IL size of the method being JITed in the trace and we do want to repeat the partial computation of the IL header.

I think it would be simpler to avoid passing the partially computed IL through the layers and instead let `getMethodInfoWorker` to compute it from scratch (ie get rid of the `MethodInfoWorkerContext` argument). To make the tracing of IL size work, I think it is fine to re-fetch the IL header on the tracing-specific path. This partial computation of IL is cheap compared to the total cost of the tracing path. The IL size used by tracing is kind of broken for intrinsics and other dynamically generated IL.

Alternatively, if you would like to fix the tracing so that it logs the actual JITed IL size (without computing the IL redundantly), the IL computation would need to be refactored into a separate type from `CEEInfo` and that type would need to be passed all the way from JitCompileCodeLockedEventWrapper. I am not sure whether it is worth it.

Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp:7498]: BTW: While looking at this. I have noticed that `GetAndVerifyMetadataILHeader` has a bunch of useless/redundant code. We do not really care about protecting against malformed binaries. `AVInRuntimeImplOkayHolder` in that method does not look useful.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp:7498]: > Does the caller really need to pass MethodInfoWorkerContext into this method from the outside?

Oh, wow. I think you're onto something. Now that we have a reorganized `UnsafeJitFunction`, there is no need for the extra state since we always have a `CEEInfo` to store the details. I think I can remove `MethodInfoWorkerContext` entirely.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas and @ericstj I added an overly aggressive assert that tripped on x86 with C++/CLI so that was the last failure. The assert would have needed to be removed for https://github.com/dotnet/runtime/pull/115345 anyways. This should be ready for review now.

File: src/coreclr/vm/jitinterface.cpp [hunk 2]
```diff
@@ -13250,7 +13354,7 @@ PCODE UnsafeJitFunctionWorker(EECodeGenManager *pJitMgr, CEECodeGenInfo *pJitInf
 PCODE UnsafeJitFunction(PrepareCodeConfig* config,
                         _In_opt_ COR_ILMETHOD_DECODER* ILHeader,
                         _In_ CORJIT_FLAGS* pJitFlags,
-                        _In_opt_ ULONG* pSizeOfCode)
+                        _In_ ULONG* pSizeOfCode)
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp:13357]: Oops.

File: src/coreclr/vm/jitinterface.cpp [hunk 3]
```diff
@@ -7708,31 +7701,24 @@ CEEInfo::getMethodInfo(
...
     JIT_TO_EE_TRANSITION();
 
-    MethodDesc * ftn = GetMethod(ftnHnd);
-
-    // Get the IL header
-    MethodInfoHelperContext cxt{ ftn };
-    if (ftn->IsDynamicMethod())
+    MethodDesc* ftn = GetMethod(ftnHnd);
+    if (ftn->IsDynamicMethod()
+        || (ftn->IsIL() && ftn->GetRVA() == 0)) // IL methods with no RVA indicate there is no implementation defined in metadata.
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp:7706]: How about we compromise here. I will move the second predicate `(ftn->IsIL() && ftn->GetRVA() == 0)` back to the third branch to avoid the duplicate. I'm planning on leaving the existing `HasILHeader()` and `GetILHeader()` calls though. The `MethodDesc` APIs aren't helpful and do so much magic. I'd prefer to avoid altering them much in this PR. Unless there is an obvious combination that makes this both clearer and doesn't require changing `MethodDesc`, I'm inclined to revert the order here.

File: src/coreclr/vm/jitinterface.h [hunk 4]
```diff
@@ -397,12 +397,6 @@ class CEEInfo : public ICorJitInfo
 
     void setJitFlags(const CORJIT_FLAGS& jitFlags);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.h:399]:
```suggestion
```
No longer used

File: src/coreclr/vm/jitinterface.cpp [hunk 5]
```diff
@@ -10731,8 +10713,146 @@ bool CEEInfo::logMsg(unsigned level, const char* fmt, va_list args)
...
+
+    // The header maybe replaced during the call to getMethodInfoWorker. This is most probable
+    // when the input is null (that is, no metadata), but we can also examine the method and generate
+    // an entirely new IL body (for example, intrinsic methods).
+    m_ILHeader = ilHeader;
+
+    m_jitFlags = GetCompileFlags(config, m_pMethodBeingCompiled, &m_MethodInfo);
+
+    // Negate the check for no inlining so the logic is easier to follow
+    m_allowInlining = !m_jitFlags.IsSet(CORJIT_FLAGS::CORJIT_FLAG_NO_INLINING);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:10854]:
```suggestion
```
Instead, change the one place that checks `m_allowInlining` to check `m_jitFlags.IsSet(CORJIT_FLAGS::CORJIT_FLAG_NO_INLINING)` instead.

File: src/coreclr/vm/jitinterface.h [hunk 6]
```diff
@@ -366,7 +366,7 @@ class CEEInfo : public ICorJitInfo
 #if defined(FEATURE_GDBJIT)
         m_pCalledMethods(NULL),
 #endif
-        m_allowInlining(fAllowInlining)
+        m_allowInlining(true)
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.h:369]:
```suggestion
```

Comment (jkotas) [reply src/coreclr/vm/jitinterface.h:369]: And delete `m_allowInlining` field

File: src/coreclr/vm/jitinterface.cpp [hunk 7]
```diff
@@ -12805,12 +12936,10 @@ CorJitResult invokeCompileMethodHelper(EECodeGenManager *jitMgr,
     return ret;
 }
 
-
 /*********************************************************************/
-CorJitResult invokeCompileMethod(EECodeGenManager *jitMgr,
+static CorJitResult invokeCompileMethod(EECodeGenManager *jitMgr,
                                  CEECodeGenInfo *comp,
                                  struct CORINFO_METHOD_INFO *info,
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:12942]:
```suggestion
```

File: src/coreclr/vm/jitinterface.cpp [hunk 8]
```diff
@@ -12825,7 +12954,7 @@ CorJitResult invokeCompileMethod(EECodeGenManager *jitMgr,
 
     GCX_PREEMP();
 
-    CorJitResult ret = invokeCompileMethodHelper(jitMgr, comp, info, jitFlags, nativeEntry, nativeSizeOfCode);
+    CorJitResult ret = invokeCompileMethodHelper(jitMgr, comp, info, nativeEntry, nativeSizeOfCode);
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:12957]:
```suggestion
    CorJitResult ret = invokeCompileMethodHelper(jitMgr, comp, nativeEntry, nativeSizeOfCode);
```

File: src/coreclr/vm/jitinterface.cpp [hunk 9]
```diff
@@ -12734,10 +12866,9 @@ void CEECodeGenInfo::getEHinfo(
     EE_TO_JIT_TRANSITION();
 }
 
-CorJitResult invokeCompileMethodHelper(EECodeGenManager *jitMgr,
+static CorJitResult invokeCompileMethodHelper(EECodeGenManager *jitMgr,
                                        CEECodeGenInfo *comp,
                                        struct CORINFO_METHOD_INFO *info,
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:12871]:
```suggestion
```

File: src/coreclr/vm/jitinterface.cpp [hunk 10]
```diff
@@ -12747,12 +12878,11 @@ CorJitResult invokeCompileMethodHelper(EECodeGenManager *jitMgr,
 
     CorJitResult ret = CORJIT_SKIPPED;   // Note that CORJIT_SKIPPED is an error exit status code
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:12880]:
```suggestion

    CORINFO_METHOD_INFO *info = comp->getMethodInfoInternal();
```

File: src/coreclr/vm/jitinterface.cpp [hunk 11]
```diff
@@ -12312,6 +12432,18 @@ void* CEECodeGenInfo::getMethodSync(CORINFO_METHOD_HANDLE ftnHnd,
     return result;
 }
 
+CORINFO_METHOD_INFO* CEECodeGenInfo::getMethodInfoInternal()
+{
+    STANDARD_VM_CONTRACT;
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:12437]:
```suggestion
    LIMITED_METHOD_CONTRACT;
```
More precise

File: src/coreclr/vm/jitinterface.cpp [hunk 12]
```diff
@@ -12312,6 +12432,18 @@ void* CEECodeGenInfo::getMethodSync(CORINFO_METHOD_HANDLE ftnHnd,
...
+    return &m_MethodInfo;
+}
+
+CORJIT_FLAGS* CEECodeGenInfo::getJitFlagsInternal()
+{
+    STANDARD_VM_CONTRACT;
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:12443]:
```suggestion
    LIMITED_METHOD_CONTRACT;
```

File: src/coreclr/vm/jitinterface.cpp [hunk 13]
```diff
@@ -13149,8 +13169,7 @@ PCODE UnsafeJitFunctionWorker(EECodeGenManager *pJitMgr, CEECodeGenInfo *pJitInf
 
         res = invokeCompileMethod(pJitMgr,
                                   pJitInfo,
-                                  &methodInfo,
-                                  *pJitFlags,
+                                  methodInfo,
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:13172]:
```suggestion
```

File: src/coreclr/vm/jitinterface.cpp [hunk 14]
```diff
@@ -13234,207 +13253,245 @@ PCODE UnsafeJitFunctionWorker(EECodeGenManager *pJitMgr, CEECodeGenInfo *pJitInf
...
+    if (interpreterMgr->IsInterpreterLoaded())
     {
-        CInterpreterJitInfo interpreterJitInfo(ftn, ILHeader, interpreterMgr, !pJitFlags->IsSet(CORJIT_FLAGS::CORJIT_FLAG_NO_INLINING));
-        ret = UnsafeJitFunctionWorker(interpreterMgr, &interpreterJitInfo, pJitFlags, methodInfo, &cxt, nativeCodeVersion, pSizeOfCode);
+        CInterpreterJitInfo interpreterJitInfo{ config, ftn, ILHeader, interpreterMgr };
+        ret = UnsafeJitFunctionWorker(interpreterMgr, &interpreterJitInfo, nativeCodeVersion, pSizeOfCode, &sizeOfILCode);
+
+        // Collect the JIT flags for the interpreter
+        if (ret)
+            *pJitFlags = *interpreterJitInfo.getJitFlagsInternal();
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:13440]:
```suggestion
        ret = UnsafeJitFunctionWorker(interpreterMgr, &interpreterJitInfo, nativeCodeVersion, pSizeOfCode);

        // Collect the JIT flags for the interpreter
        if (ret)
        {
            sizeOfILCode = interpreterJitInfo.getMethodInfoInternal()->ILCodeSize;
            *pJitFlags = *interpreterJitInfo.getJitFlagsInternal();
        }
```
We can read the ILCodeSize out the same way as JIT flags.

File: src/coreclr/vm/jitinterface.cpp [hunk 15]
```diff
@@ -13234,207 +13253,245 @@ PCODE UnsafeJitFunctionWorker(EECodeGenManager *pJitMgr, CEECodeGenInfo *pJitInf
...
+// the same pMD, ALL of them MUST return the SAME value.
+// To ensure that this happens you must call MakeJitWorker.
+// It creates a DeadlockAware list of methods being jitted and prevents us
+// from trying to jit the same method more that once.
+//
+// Calls to this method that occur to check if inlining can occur on x86,
+// are OK since they discard the return value of this method.
+PCODE UnsafeJitFunction(PrepareCodeConfig* config,
+                        _In_opt_ COR_ILMETHOD_DECODER* ILHeader,
+                        _Out_ CORJIT_FLAGS* pJitFlags,
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:13395]:
```suggestion
                        _Out_ bool* pfTier0,
```
The caller is only interested in `CORJIT_FLAG_TIER0` flag, so we may just pass that one single flag as a bool out (better encapsulation, the caller has no business in knowing all JIT flags).

File: src/coreclr/vm/jitinterface.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp]: Sounds good.

**Review by jkotas — APPROVED** [review]
Thank you!

File: src/coreclr/vm/jitinterface.cpp [hunk 16]
```diff
@@ -13182,11 +13149,8 @@ PCODE UnsafeJitFunctionWorker(EECodeGenManager *pJitMgr, CEECodeGenInfo *pJitInf
             OutputDebugStringUtf8(codeBase.GetUTF8());
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:13149]: `methodInfo.ILCodeSize` -> `methodInfo->ILCodeSize` a few lines above
