### PR TITLE
Fix failure to generate ngen pdb in crossgen

### LINKED ISSUE #89337: Cross-gen failed to produce PDB for C# Dev Kit binaries
### Description

Cross-gen works for our binaries but stops working if we want to produce PDB files for cross-gen binaries.

This might happen due to our package has code referencing msbuild, but msbuild binaries are not included in the package. (We expect to load them from the SDK folder based on global.json of the user project, instead of using one from the developing time. It doesn't seem to be a problem in our another package.

Here are the call stacks in the build log:

If we skip building PDB, the problem will disappear.

D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5): Error: Failed to load assembly 'Microsoft.Build' [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5): Internal.TypeSystem.TypeSystemException+FileNotFoundException: Failed to load assembly 'Microsoft.Build' [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.TypeSystem.ThrowHelper.ThrowFileNotFoundException(ExceptionStringID, String) + 0x30 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.TypeSystem.ResolutionFailure.Throw() + 0x117 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle, NotFoundBehavior) + 0x9a [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle) + 0x11 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType() + 0x75 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags) + 0x44 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags) + 0x17 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.TypeSystem.TypeNameFormatter.AppendName(StringBuilder, TypeDesc) + 0x27 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.JitInterface.TypeString.AppendNameForInstantiatedType(StringBuilder, DefType) + 0x88 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.JitInterface.TypeString.AppendNameForInstantiatedType(StringBuilder, DefType) + 0x88 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at Internal.TypeSystem.TypeNameFormatter.FormatName(TypeDesc) + 0x4e [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at ILCompiler.PEWriter.OutputInfoBuilder.FormatMethodName(MethodDesc, TypeNameFormatter) + 0x83 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at ILCompiler.PEWriter.OutputInfoBuilder.<EnumerateMethods>d__16.MoveNext() + 0x162 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at ILCompiler.Diagnostics.PdbWriter.WritePDBDataHelper(String, IEnumerable`1) + 0x6f1 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at ILCompiler.Diagnostics.PdbWriter.WritePDBData(String, IEnumerable`1) + 0x1b [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable() + 0x9ce [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at ILCompiler.ReadyToRunCodegenCompilation.Compile(String) + 0x18d [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at ILCompiler.Program.RunSingleCompilation(Dictionary`2, InstructionSetSupport, String, Dictionary`2, HashSet`1, CompilerTypeSystemContext) + 0x17b0 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at ILCompiler.Program.Run(String[]) + 0xd6b [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]
D:\a\_work\_tool\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(465,5):    at ILCompiler.Program.Main(String[]) + 0x32 [D:\a\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Server.Package\Microsoft.VisualStudio.ProjectSystem.Server.Package.csproj]

### Reproduction Steps

It failed in the project system build pipeline.

### Expected behavior

be able to produce PDB.

### Actual behavior

should be able to produce PDB.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by davidwrighton**
Fix issue in R2R compilation where we would compile a method we could not generate a name for

- This is caused by the the type of a parameter having a generic parameter which derived from a type not found in the compilation information
- There are 2 fixes here
  1. Change the logic for computing the set of compilable methods to require that all parameters are loadable
  2. Change the implementation of loadable types to check generic instantiations for loadability
    - This required implementing a stack system to check types for loadability, as loading can require circular references to be resolved.
    - Add a check that the instantiation types of an instantiated generic are loadable. - Generic interfaces on arrays work now, so enable the the constraint checking logic.

Fixes #89337

### CODE REVIEW

File: src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.Validation.cs [hunk 1]
```diff
@@ -11,13 +13,181 @@ namespace ILCompiler
...
+                }
+                else if (t_typeLoadCheckInProgressStack[typeCheckDepth].OtherTypesToMarkAsSuccessfullyLoaded.Contains(type))
+                {
+                    // We've found where the type will be marked as successfully loaded.
+                    typeLoadCheckInProgressStackOffset = typeCheckDepth;
+                    break;
+                }
+            }
+
+            if (checkingMode)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.Validation.cs:130]: I don't see a codepath that would lead to this `if` being taken.

File: src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.Validation.cs [hunk 2]
```diff
@@ -161,16 +334,14 @@ private static TypeDesc EnsureLoadableTypeUncached(TypeDesc type)
                     {
                         ThrowHelper.ThrowTypeLoadException(ExceptionStringID.ClassLoadGeneral, type);
                     }
+
+                    ((CompilerTypeSystemContext)type.Context).EnsureLoadableType(type.BaseType);
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.Validation.cs:338]:
```suggestion
                    ((CompilerTypeSystemContext)type.Context).EnsureLoadableType(typeArg);
```

**Review by MichalStrehovsky — APPROVED** [review]
Looks good otherwise!
