### PR TITLE
Pool the underlying list and dictionary in scopes.

### LINKED ISSUE #47607: DI allocations improvements
In Orchard CMS which is quite allocaty, the second culprit is DI. This code path does a database request and renders the html. During that process several services are resolved, increasing the size of the scoped service dictionary.

Stack trace of allocations:

```
Name                                                                                                                                                                                                                                  	Inc %
 Type Entry[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey,System.Object][]                                                                                                                                   	  7.8
+ coreclr!?                                                                                                                                                                                                                           	  7.8
|+ System.Private.CoreLib.il!System.Collections.Generic.Dictionary`2[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey,System.__Canon].Resize(int32,bool)                                                        	  7.8
||+ System.Private.CoreLib.il!System.Collections.Generic.Dictionary`2[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey,System.__Canon].TryInsert(!0,!1,value class System.Collections.Generic.InsertionBehavior)	  7.8
|| + System.Private.CoreLib.il!System.Collections.Generic.Dictionary`2[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCacheKey,System.__Canon].Add(!0,!1)                                                              	  7.8
||  + microsoft.extensions.dependencyinjection.il!dynamicClass.ResolveService(pMT: 00007FF84C1DFF08,pMT: 00007FF84C1D9B20)                                                                                                            	  7.8
||   + microsoft.extensions.dependencyinjection.il!dynamicClass.ResolveService(pMT: 00007FF84C1DFF08,pMT: 00007FF84C1D9B20)                                                                                                           	  7.8
||    + microsoft.extensions.dependencyinjection.abstractions.il!ServiceProviderServiceExtensions.GetRequiredService                                                                                                                  	  4.8
||    |+ microsoft.extensions.dependencyinjection.abstractions.il!ServiceProviderServiceExtensions.GetRequiredService                                                                                                                 	  4.8
||    | + orchardcore.displaymanagement.liquid!OrchardCore.DisplayManagement.Liquid.LiquidTemplateContextExtensions+<EnterScopeAsync>d__0.MoveNext()                                                                                  	  4.5

```

And overall memory consumption:

```
Name                                                                                                                                         Exc %  ExcInc %     Inc Fold                            When
?!?                                                                                                                                           8.66,57215.5  11,8571,7788389CDDoDCDFED9ECFFFDGGHFFE89DY*
e_sqlite3!?                                                                                                                                   4.03,088 6.1   4,7011,36762526767655664565557556565569535
microsoft.extensions.dependencyinjection.il!dynamicClass.ResolveService(pMT: 00007FF84C1DFF08,pMT: 00007FF84C1D9B20)                          2.92,217 5.4   4,1341,907105o556655665546566567566564630o
orchardcore.displaymanagement!OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay+<ExecuteAsync>d__7.MoveNext()                   2.72,09728.1  21,4691,95400N5WWXVWVVVWSOXUWWXXVWXWWXRWN9.
orchardcore.contentmanagement.display!OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator+<BuildDisplayAsync>d__9.MoveNext() 2.31,74910.0   7,6481,6760_81BCABBBABB99CBBACBABBBCCBD92_
System.Private.CoreLib.il!AsyncMethodBuilderCore.Start                                                                                        2.21,69071.9  54,9611,42801****************************3_
orchardcore.displaymanagement!OrchardCore.DisplayManagement.Views.ShapeResult+<ApplyImplementationAsync>d__17.MoveNext()                      2.01,540 5.2   4,0081,4130o40665656555446655655656666741_
orchardcore.displaymanagement.liquid!OrchardCore.DisplayManagement.Liquid.Tags.HelperStatement+<WriteToAsync>d__4.MoveNext()                  1.91,47413.0   9,9651,38200A3FGFFEEEEEDBGEEEFEEEFFGGCDA51
ntoskrnl!RtlpLookupFunctionEntryForStackWalks                                                                                                 1.91,437 1.9   1,437  242__o012222223221122222o222220____
orchardcore.displaymanagement.liquid!LiquidTagHelperActivator.Create                                                                          1.91,428 2.3   1,7831,3710o202222222222132232222233222110
```

This issue is just to raise some concern, and maybe there is nothing better to be done.

### PR DESCRIPTION
**Pull request by davidfowl**
- Today DI scopes allocate a dictionary and an optional list of disposables per request. That dictionary starts off with the default capacity and resizes as scoped services are resolved.  Depending on how many scoped services are resolved, this can end up with many resizes per request which result in new array allocations. This change pools those 2 lists assuming that short lived scopes look mostly the same (same number of services resolved and disposed per scope instance).
- This change pools a set of scopes assuming they are short lived.
- One breaking change is that after disposal, pooled scopes will throw if services are accessed afterwards on the scope.
- We *could* make this an opt in flag but, I'm not sure if it it makes sense. Accessing a scope after it's disposed is broken anyways.

~PS: Needs testing, getting early feedback.~
~TODO: Performance tests~

cc @sebastienros 

Fixes https://github.com/dotnet/runtime/issues/47607

Update: @sebastienros confirmed it fixes the issue.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 1]
```diff
@@ -155,30 +163,48 @@ static async ValueTask Await(int i, ValueTask vt, List<object> toDispose)
...
+        {
+            ThrowHelper.ThrowObjectDisposedException();
+            return null;
+        }
+
+        private void ClearState()
+        {
+            // Dispose the state, which will end up attempting to return the state pool.
+            // This will return false if the pool is full or if this state object is the root scope
+            if (_state.Return())
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:181]: There's a race here I need to fix between getting resolved services and returning state to the pool.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs [hunk 2]
```diff
@@ -9,13 +11,28 @@ namespace Microsoft.Extensions.DependencyInjection.ServiceLookup
     public class ServiceProviderEngineScopeTests
     {
         [Fact]
-        public void Dispose_DoesntClearResolvedServices()
+        public void ResolvedServicesAfterDispose_ThrowsObjectDispose()
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs:14]: This is the biggest change. Accessing services after disposing will throw.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+
+            public State(ScopePool pool = null)
+            {
+                _pool = pool;
+                ResolvedServices = pool == null ? new ConcurrentDictionary<ServiceCacheKey, object>() : new Dictionary<ServiceCacheKey, object>();
+            }
+
+            internal void Clear()
+            {
+                // REVIEW: Should we trim excess here as well?
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:58]: I would expect scopes to have a similar amount of resolved services during the app lifetime.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 4]
```diff
@@ -134,9 +139,11 @@ public ValueTask DisposeAsync()
                 }
             }
 
+            ClearState();
+
             return default;
 
-            static async ValueTask Await(int i, ValueTask vt, List<object> toDispose)
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:139]: why remove the static?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+
+using System;
+using System.Collections.Concurrent;
+using System.Collections.Generic;
+using System.Threading;
+using Microsoft.Extensions.DependencyInjection.ServiceLookup;
+
+namespace Microsoft.Extensions.DependencyInjection
+{
+    internal class ScopePool
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:12]: How many similar pool implementations do we have across the codebase? Worth having something reusable?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 6]
```diff
@@ -15,20 +13,24 @@ internal sealed class ServiceProviderEngineScope : IServiceScope, IServiceProvid
...
-
-            // To reduce lock contention for singletons upon resolve we use a concurrent dictionary.
-            ResolvedServices = isRoot ? new ConcurrentDictionary<ServiceCacheKey, object>() : new Dictionary<ServiceCacheKey, object>();
+            _state = isRoot ? new ScopePool.State() : engine.ScopePool.Rent();
         }
 
-        internal IDictionary<ServiceCacheKey, object> ResolvedServices { get; }
+        internal IDictionary<ServiceCacheKey, object> ResolvedServices => _state?.ResolvedServices ?? ScopeDisposed();
+
+        internal object Sync => _scopeLock;
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:33]: Can we reuse the dispose lock?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 7]
```diff
@@ -339,8 +343,15 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
...
                 Stloc(context.Generator, resolvedServicesLocal.LocalIndex);
 
-                // Load resolvedServices
-                Ldloc(context.Generator, resolvedServicesLocal.LocalIndex);
+                // scope
+                context.Generator.Emit(OpCodes.Ldarg_1);
+                // .Sync
+                context.Generator.Emit(OpCodes.Callvirt, ScopeLockGetter);
+                // Store syncLocal
+                Stloc(context.Generator, syncLocal.LocalIndex);
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:351]: You store and then immediately load the syncLocal. Can we just keep it on the stack and avoid the local?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs [hunk 8]
```diff
@@ -0,0 +1,69 @@
...
+        {
+            private readonly ScopePool _pool;
+
+            public IDictionary<ServiceCacheKey, object> ResolvedServices { get; }
+            public List<object> Disposables { get; set; }
+
+            public State(ScopePool pool = null)
+            {
+                _pool = pool;
+                ResolvedServices = pool == null ? new ConcurrentDictionary<ServiceCacheKey, object>() : new Dictionary<ServiceCacheKey, object>();
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:53]: Can you add a comment saying that if pool == null it's the root scope and 
```
            // To reduce lock contention for singletons upon resolve we use a concurrent dictionary.
```

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs (hunk 7 above)
Comment (pakrym) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:351]: Ah, you use it later.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs [hunk 9]
```diff
@@ -389,7 +400,7 @@ private ILEmitResolverBuilderRuntimeContext GenerateMethodBody(ServiceCallSite c
                 // return if not
                 context.Generator.Emit(OpCodes.Brfalse, returnLabel);
                 // Load resolvedServices
```
Comment (pakrym) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:402]: nit: fix comment

**Comment by pakrym** [comment]
Did you consider pooling entire ServiceProviderEngineScope objects? Or is that too scary?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 4 above)
Comment (pakrym) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:139]: Pass `this` as a parameter?

**Comment by pakrym** [comment]
LGTM, nice and clean.

**Comment by davidfowl** [comment]
> Did you consider pooling entire ServiceProviderEngineScope objects? Or is that too scary?

I started that way, but it did seem a little scary and might need to be opt-in if we went that far. I'd like to reduce the object size event more (if possible) so scopes are basically a super lightweight wrapper around this possibly reusable state.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 4 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:139]: Yea, I could,

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs (hunk 3 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:58]: That's my current theory as well but scope types vary (long lived vs short lived) and we don't have any signal for that.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 6 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:33]: Yea I think we can do this now that singletons don't use this lock anymore.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 10]
```diff
@@ -155,30 +161,53 @@ static async ValueTask Await(int i, ValueTask vt, List<object> toDispose)
...
                 _disposed = true;
-                toDispose = _disposables;
-                _disposables = null;
+
+                return _state.Disposables;
 
                 // Not clearing ResolvedServices here because there might be a compilation running in background
                 // trying to get a cached singleton service instance and if it won't find
                 // it it will try to create a new one tripping the Debug.Assert in CaptureDisposable
                 // and leaking a Disposable object in Release mode
```
Comment (halter73) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:209]: Should we move this comment above the call to `_state.Return()` in `ClearState()`? At first I was going to point out we are clearing `ResolvedServices` now, but then I realized that we're not for the root scope.

Comment (halter73) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:209]: Or maybe `ScopePool.Return()` would now be a better place for this comment.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs (hunk 5 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:12]: Getting something that we can actually share internally is probably a good first test for any proposed `ObjectPool<T>` API.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs [hunk 11]
```diff
@@ -0,0 +1,71 @@
...
+using System.Collections.Generic;
+using System.Threading;
+using Microsoft.Extensions.DependencyInjection.ServiceLookup;
+
+namespace Microsoft.Extensions.DependencyInjection
+{
+    internal class ScopePool
+    {
+        // Modest number to re-use. We only really care about reuse for short lived scopes
+        private const int s_maxQueueSize = 128;
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:15]: (nit) Use PascalCasing for consts. #12 in [https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md)

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 12]
```diff
@@ -15,20 +13,23 @@ internal sealed class ServiceProviderEngineScope : IServiceScope, IServiceProvid
...
         internal Action<object> _captureDisposableCallback;
 
-        private List<object> _disposables;
-
         private bool _disposed;
-        private readonly object _disposelock = new object();
+        private ScopePool.State _state;
+
+        // This lock protects state on the scope, in particular, for the root scope, it protects
+        // the list of disposable entries only as ResolvedServices is a concurrent dictionary
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:20]:
```suggestion
        // the list of disposable entries only, since ResolvedServices is a concurrent dictionary.
```

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 13]
```diff
@@ -66,16 +67,17 @@ internal object CaptureDisposable(object service)
...
                         Task.Run(() => ((IAsyncDisposable)service).DisposeAsync().AsTask()).GetAwaiter().GetResult();
                     }
+
                     ThrowHelper.ThrowObjectDisposedException();
-                }
 
-                if (_disposables == null)
-                {
-                    _disposables = new List<object>();
+                    return service;
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:73]: ?? Huh?

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs [hunk 14]
```diff
@@ -9,13 +11,28 @@ namespace Microsoft.Extensions.DependencyInjection.ServiceLookup
...
         {
-            var serviceProviderEngineScope = new ServiceProviderEngineScope(null);
+            var engine = new FakeEngine();
+            var serviceProviderEngineScope = new ServiceProviderEngineScope(engine);
             serviceProviderEngineScope.ResolvedServices.Add(new ServiceCacheKey(typeof(IFakeService), 0), null);
             serviceProviderEngineScope.Dispose();
 
-            Assert.Single(serviceProviderEngineScope.ResolvedServices);
+            Assert.Throws<ObjectDisposedException>(() => serviceProviderEngineScope.ResolvedServices);
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs:21]: Reading what introduced this test:

[https://github.com/dotnet/extensions/pull/1049](https://github.com/dotnet/extensions/pull/1049)

Are we going to hit the same race condition now?

Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs:21]: Singletons are never cleared

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 15]
```diff
@@ -155,30 +161,53 @@ static async ValueTask Await(int i, ValueTask vt, List<object> toDispose)
...
+        {
+            ThrowHelper.ThrowObjectDisposedException();
+            return null;
+        }
+
+        private void ClearState()
+        {
+            // We lock here since ResolvedServices is always accessed in the scope lock, this means we'll never
+            // try to return to the pool while somebody is trying to access ResolvedServices.
+            lock (_scopeLock)
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:179]: this method seems to be a noop for root scope, would it make sense to skip for it before taking the lock?

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs (hunk 14 above)
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs:21]: Aren't you going to get an `ObjectDisposedException` in the background now?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 16]
```diff
@@ -15,20 +13,23 @@ internal sealed class ServiceProviderEngineScope : IServiceScope, IServiceProvid
...
         {
             Engine = engine;
-
-            // To reduce lock contention for singletons upon resolve we use a concurrent dictionary.
-            ResolvedServices = isRoot ? new ConcurrentDictionary<ServiceCacheKey, object>() : new Dictionary<ServiceCacheKey, object>();
+            _state = isRoot ? new ScopePool.State() : engine.ScopePool.Rent();
         }
 
-        internal IDictionary<ServiceCacheKey, object> ResolvedServices { get; }
+        internal IDictionary<ServiceCacheKey, object> ResolvedServices => _state?.ResolvedServices ?? ScopeDisposed();
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:30]: would it be easy to add tests for some of these cases? like when `ScopeDisposed` would happen

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 17]
```diff
@@ -134,9 +138,11 @@ public ValueTask DisposeAsync()
                 }
             }
 
+            ClearState();
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:141]: Would it make sense to add this ClearState() call on a finally block to the try-catch block above it?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 16 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:30]: There's one test that was modified to show this actually the only modified test

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 17 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:141]: Yes it would.

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs (hunk 14 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs:21]: Yes which we swallow.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 13 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:73]: Yea, this is kinda not required. It got added due to some refactoring and un-refactoring

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 17 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:141]: Actually, it's probably better not to try and return this scope to the pool if dispose throws.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 13 above)
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:73]: Can we remove it?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs [hunk 18]
```diff
@@ -0,0 +1,71 @@
...
+            {
+                _pool = pool;
+                // When pool is null, we're in the global scope which doesn't need pooling.
+                // To reduce lock contention for singletons upon resolve we use a concurrent dictionary.
+                ResolvedServices = pool == null ? new ConcurrentDictionary<ServiceCacheKey, object>() : new Dictionary<ServiceCacheKey, object>();
+            }
+
+            internal void Clear()
+            {
+                // REVIEW: Should we trim excess here as well?
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:60]: Both `Clear()` and `Return()` should never be called if `_pool == null`, right? Should we add an assert in both?

Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:60]: Oh, I guess `Return()` gets called by the root in its Dispose...

Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:60]: We call Return even if _pool is null and we noop. So I'll add the assert to Clear but not return.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 13 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:73]: Yep.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs [hunk 19]
```diff
@@ -0,0 +1,74 @@
...
+
+        public bool Return(State state)
+        {
+            if (Interlocked.Increment(ref _count) > MaxQueueSize)
+            {
+                Interlocked.Decrement(ref _count);
+                return false;
+            }
+
+            state.Clear();
```
Comment (BrennanConroy) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:39]: Should we always call Clear?

Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ScopePool.cs:39]: Why?

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs [hunk 20]
```diff
@@ -155,30 +159,52 @@ static async ValueTask Await(int i, ValueTask vt, List<object> toDispose)
...
+            {
+                // ResolvedServices is never cleared for singletons because there might be a compilation running in background
+                // trying to get a cached singleton service. If it doesn't find it
+                // it will try to create a new one which will result in an ObjectDisposedException.
+
+                // Dispose the state, which will end up attempting to return the state pool.
+                // This will return false if the pool is full or if this state object is the root scope
+                if (_state.Return())
+                {
+                    _state = null;
```
Comment (BrennanConroy) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:187]: What's the reason for not setting this to null in all cases?

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs (hunk 14 above)
Comment (eerhardt) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs:21]: OK, that sounds fine for this. Thanks for the explanation.

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs (hunk 20 above)
Comment (davidfowl) [reply src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs:187]: Singletons, and the background compilation thread that uses them. Also it isn't pooled.

**Review by eerhardt — APPROVED** [review]
I think this looks good. Nice work here!

File: src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs (hunk 2 above)
Comment (halter73) [reply src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderEngineScopeTests.cs:14]: I guess this [still is a regression test](https://github.com/dotnet/runtime/pull/50463/files#r605731182).

**Review by halter73 — APPROVED** [review]

**Comment by jkotas** [comment]
> TODO: Performance tests

Any performance numbers?

**Comment by sebastienros** [comment]
@jkotas on the same application as in the issue I filed, the allocations disappeared from the list. They represented 13% of the total allocations of the app (150MB /sec), and with this branch there were less than 1% AFAIR.

**Comment by davidfowl** [comment]
We (@sebastienros and I) ran a couple of the TE benchmarks to make sure nothing regressed. We saw a very minor RPS improvement and a reduction in allocation rate. In orchard, the allocations basically disappeared from the trace from being the top one but RPS didn't improve much.

Here's a microbenchmark with 10 scoped services:

```
|         Method |     Mean |   Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------- |---------:|--------:|--------:|-------:|------:|------:|----------:|
| ScopedServices | 667.8 ns | 9.00 ns | 8.42 ns | 0.3662 |     - |     - |    1.5 KB |
```

```
|         Method |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
| ScopedServices | 599.1 ns | 10.60 ns | 12.20 ns | 0.0763 |     - |     - |     320 B |
```

This benchmark needs more concurrency to represent what ends up happening per request in ASP.NET Core though (where we've mostly removed scoped services).

**Comment by jkotas** [comment]
Thanks.

> one but RPS didn't improve much.

This is fairly common for pools like this - they replace GC allocations with cache trashing.

**Comment by davidfowl** [comment]
@jkotas do we have an easy way to measure that? Or do we need a tool like vtune?

**Comment by jkotas** [comment]
Yep, vtune would be a tool to investigate this.
