### PR TITLE
Fix Restoring the Original Activity Parent

### LINKED ISSUE #46721: Ending an activity will not restore the previously active one for explicit parents
Copied from https://github.com/open-telemetry/opentelemetry-dotnet/issues/1677

## Symptom

Activity.Current becomes `null` whenever any Activity with explicit parent is ended. I would instead have expected that the previously active activity would be restored, independent of whether it was the parent or not.

Following shows how to repro this with OpenTelemetry, but this can be reproed by setting up any Activitylistener.

## Reproduce

```c#
using System;
using System.Diagnostics;
using OpenTelemetry;
using OpenTelemetry.Trace;

public class Program
{
    private static readonly ActivitySource MyActivitySource = new ActivitySource(
        "MyCompany.MyProduct.MyLibrary");

    public static void Main()
    {
        using var tracerProvider = Sdk.CreateTracerProviderBuilder()
            .SetSampler(new AlwaysOnSampler())
            .AddSource("MyCompany.MyProduct.MyLibrary")
            .Build();

        using (var activity = MyActivitySource.StartActivity("SayHello"))
        {
            Console.WriteLine("Current before: {0}", Activity.Current?.DisplayName);
            using (var child = MyActivitySource.StartActivity("SayWorld", ActivityKind.Internal, activity.Context))
            {
                Console.WriteLine("Current child: {0}", Activity.Current?.DisplayName);
            }

            Console.WriteLine("Current after: {0}", Activity.Current?.DisplayName ?? "(null)");
        }
    }
}
```

Actual Output:

```
Current before: SayHello
Current child: SayWorld
Current after: (null)
```

Expected output would be that the last line is `Current after: SayHello`.

## Additional context

Responsible line in `Activity.Stop`:

https://github.com/dotnet/runtime/blob/v5.0.1/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L629

I think the Activity should capture a "previous" Activity independently of the Parent Activity and then always set that as active when stopping it.

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #46721

When creating and starting an Activity object with a parent context the stopping this activity, we used not caring about the Activity.Current at that time. When stopping such Activity, we don't restore any parent to Activity.Current and instead we store `null`.
The change here is to restore the original value of Activity.Current before we started the Activity.

### CODE REVIEW

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs [hunk 1]
```diff
@@ -686,8 +687,7 @@ public void Stop()
                 }
 
                 Source.NotifyActivityStop(this);
-
-                SetCurrent(Parent);
+                SetCurrent(Parent ?? ((_originalParent != null && !_originalParent.IsFinished) ? _originalParent : null));
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs:690]: Parent is either _originalParent or null. Combining the previous comment + this one should reduce the implementation to:
````C#
SetCurrent(_originalParent);
````

**Review by noahfalk — APPROVED** [review]
I suggested a few simplifications inline (primarily because I was wrong earlier when we talked, sorry about that). Other than that, looks good!
