### PR TITLE
Fix TimeProvider Timer with Infinity Timeout

### LINKED ISSUE #88000: Cannot create a CancellationTokenSource with an infinite delay with TimeProvider that is not TimeProvider.System
### Description

If code creates a `CancellationTokenSource` with an infinite delay, when that code is invoked with any `TimeProvider` instead of `TimeProvider.System`, an `ArgumentOutOfRangeException` is thrown.

I'm guessing this is caused by the code here that casts the `long` to a `uint` wrapping around, which takes the value 1 beyond the maximum value in the validation code for `Timer`.

https://github.com/dotnet/runtime/blob/cfe30c057debbdd9ad21b36ae61062dbe72a1f83/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L155-L165

https://github.com/dotnet/runtime/blob/cfe30c057debbdd9ad21b36ae61062dbe72a1f83/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs#L824

### Reproduction Steps

Execute the following xunit test targeting `net8.0`:

```csharp
using Microsoft.Extensions.Time.Testing;

namespace CancellationTokenSourceWithTimeProviderRepro;

public static class CancellationTokenSourceTests
{
    public static IEnumerable<object[]> TimeProviders => new[]
    {
        new[] { TimeProvider.System },
        new[] { new DerivedTimeProvider() },
        new[] { new FakeTimeProvider() },
    };

    [Theory]
    [MemberData(nameof(TimeProviders))]
    public static void Can_Create_Infinite_CancellationTokenSource_With_TimeProvider(TimeProvider timeProvider)
    {
        using var cts = new CancellationTokenSource(Timeout.InfiniteTimeSpan, timeProvider);
        Assert.False(cts.IsCancellationRequested);
    }

    private sealed class DerivedTimeProvider : TimeProvider
    {
        // Changes no behaviour, but is not the same underlying type/object as TimeProvider.System
    }
}
```

### Expected behavior

All three tests pass.

### Actual behavior

The tests that do not use `TimeProvider.System` both fail with similar exceptions:

```
Can Create Infinite CancellationTokenSource With TimeProvider(timeProvider: DerivedTimeProvider { LocalTimeZone = (UTC+00:00) Dublin, Edinburgh, Lisbon, London, TimestampFrequency = 10000000 }) 
Duration: 1 ms

Message: 
  System.ArgumentOutOfRangeException : dueTime ('4294967295') must be less than or equal to '4294967294'. (Parameter 'dueTime')
  Actual value was 4294967295.

Stack Trace: 
  ArgumentOutOfRangeException.ThrowGreater[T](String paramName, T value, T other)
  SystemTimeProviderTimer.CheckAndGetValues(TimeSpan dueTime, TimeSpan periodTime)
  SystemTimeProviderTimer.ctor(TimeSpan dueTime, TimeSpan period, TimerCallback callback, Object state)
  TimeProvider.CreateTimer(TimerCallback callback, Object state, TimeSpan dueTime, TimeSpan period)
  CancellationTokenSource.InitializeWithTimer(UInt32 millisecondsDelay, TimeProvider timeProvider)
  CancellationTokenSource.ctor(TimeSpan delay, TimeProvider timeProvider)
  CancellationTokenSourceTests.Can_Create_Infinite_CancellationTokenSource_With_TimeProvider(TimeProvider timeProvider) line 21
  InvokeStub_CancellationTokenSourceTests.Can_Create_Infinite_CancellationTokenSource_With_TimeProvider(Object, Object, IntPtr*)
  MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

```
Can Create Infinite CancellationTokenSource With TimeProvider(timeProvider: 2000-01-01T00:00:00.000) 
Duration: 1 ms

Message: 
  System.ArgumentOutOfRangeException : Argument not in the range [-1..4294967294] (Parameter 'dueTime')
  Actual value was 4294967295.

Stack Trace: 
  Throw.ArgumentOutOfRangeException(String paramName, Object actualValue, String message)
  Waiter.ChangeAndValidateDurations(TimeSpan dueTime, TimeSpan period)
  Waiter.ctor(FakeTimeProvider fakeTimeProvider, TimeSpan dueTime, TimeSpan period, TimerCallback callback, Object state)
  FakeTimeProviderTimer.ctor(FakeTimeProvider fakeTimeProvider, TimeSpan dueTime, TimeSpan period, TimerCallback callback, Object state)
  FakeTimeProvider.CreateTimer(TimerCallback callback, Object state, TimeSpan dueTime, TimeSpan period)
  CancellationTokenSource.InitializeWithTimer(UInt32 millisecondsDelay, TimeProvider timeProvider)
  CancellationTokenSource.ctor(TimeSpan delay, TimeProvider timeProvider)
  CancellationTokenSourceTests.Can_Create_Infinite_CancellationTokenSource_With_TimeProvider(TimeProvider timeProvider) line 21
  InvokeStub_CancellationTokenSourceTests.Can_Create_Infinite_CancellationTokenSource_With_TimeProvider(Object, Object, IntPtr*)
  MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Regression?

Unknown.

### Known Workarounds

None.

### Configuration

- .NET SDK `8.0.100-preview.5.23303.2`
- Microsoft.Extensions.TimeProvider.Testing `8.0.0-preview.5.23308.3`

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/88000

For the time provider timer using the default implementation, we verify that the specified duration and periods are within the maximum allowed timeout milliseconds of 0xfffffffe. However, when dealing with an infinite timeout, represented by the value 0xffffffff, we incorrectly throw an out-of-range exception. To address this issue, we need to modify the code so that it does not throw an exception in such cases.

It's worth noting that this problem does not arise with the system time provider, as it directly creates a TimerQueueTimer and handles the infinity value as a special case.

### CODE REVIEW

File: src/libraries/Common/tests/System/TimeProviderTests.cs [hunk 1]
```diff
@@ -174,10 +174,15 @@ public void FastClockTest()
             Assert.Equal(stamp2 - stamp1, fastClock.GetElapsedTime(stamp1, stamp2).Ticks);
         }
 
+        public class DerivedTimeProvider : TimeProvider
```
Comment (danmoseley) [inline src/libraries/Common/tests/System/TimeProviderTests.cs:177]: is this sufficient to protect the fix?

File: src/libraries/Common/src/System/TimeProvider.cs [hunk 2]
```diff
@@ -239,33 +239,36 @@ private static (uint duration, uint periodTime) CheckAndGetValues(TimeSpan dueTi
...
-                if (dueTm > MaxSupportedTimeout)
+                if (dueTm > MaxAllowedTimeout)
                 {
-                    throw new ArgumentOutOfRangeException(nameof(dueTime), dueTm, SR.Format(SR.ArgumentOutOfRange_Generic_MustBeLessOrEqual, nameof(dueTime), MaxSupportedTimeout));
+                    throw new ArgumentOutOfRangeException(nameof(dueTime), dueTm, SR.Format(SR.ArgumentOutOfRange_Generic_MustBeLessOrEqual, nameof(dueTime), MaxAllowedTimeout));
                 }
 
                 if (periodTm < -1)
                 {
                     throw new ArgumentOutOfRangeException(nameof(periodTm), periodTm, SR.Format(SR.ArgumentOutOfRange_Generic_MustBeGreaterOrEqual, nameof(periodTm), -1));
```
Comment (danmoseley) [inline src/libraries/Common/src/System/TimeProvider.cs:266]: all `nameof(periodTm)` here should be `nameof(periodTime)` like above

File: src/libraries/Common/tests/System/TimeProviderTests.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/Common/tests/System/TimeProviderTests.cs:177]: Indeed, this approach will allow us to test the code path where `timePovider != TimeProvider.System` and cover the test cases that reproduce the existing issue, such as creating a CancellationTokenSource with an infinite duration.

File: src/libraries/Common/src/System/TimeProvider.cs (hunk 2 above)
Comment (tarekgh) [reply src/libraries/Common/src/System/TimeProvider.cs]: done.

File: src/libraries/Common/src/System/TimeProvider.cs [hunk 3]
```diff
@@ -239,33 +239,36 @@ private static (uint duration, uint periodTime) CheckAndGetValues(TimeSpan dueTi
...
+                const long MaxAllowedTimeout = (long)(unchecked((uint)Timeout.Infinite));
+
 #if SYSTEM_PRIVATE_CORELIB
                 ArgumentOutOfRangeException.ThrowIfLessThan(dueTm, -1, nameof(dueTime));
-                ArgumentOutOfRangeException.ThrowIfGreaterThan(dueTm, Timer.MaxSupportedTimeout, nameof(dueTime));
+                ArgumentOutOfRangeException.ThrowIfGreaterThan(dueTm, MaxAllowedTimeout, nameof(dueTime));
 
                 ArgumentOutOfRangeException.ThrowIfLessThan(periodTm, -1, nameof(periodTime));
-                ArgumentOutOfRangeException.ThrowIfGreaterThan(periodTm, Timer.MaxSupportedTimeout, nameof(periodTime));
+                ArgumentOutOfRangeException.ThrowIfGreaterThan(periodTm, MaxAllowedTimeout, nameof(periodTime));
```
Comment (stephentoub) [inline src/libraries/Common/src/System/TimeProvider.cs:252]: I don't understand these changes. dueTm and periodTm are signed. -1 will be -1, not 0xffffffff.

Comment (stephentoub) [reply src/libraries/Common/src/System/TimeProvider.cs:252]: I think this is a case of two wrongs making a right.  The problem isn't in CheckAndGetValues.  It's in the call chain of CheckAndGetValues passing in values that haven't been handled appropriately.  You can see in CTS for example that in the CancelAfter method it's special-casing:
https://github.com/dotnet/runtime/blob/a0964f9e3793cb36cc01d66c14a61e89ada5e7da/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L450
but in the ctor it's not:
https://github.com/dotnet/runtime/blob/a0964f9e3793cb36cc01d66c14a61e89ada5e7da/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L216

I think instead the right fix is to stop dealing with uints in the call sites, e.g.
https://github.com/dotnet/runtime/blob/a0964f9e3793cb36cc01d66c14a61e89ada5e7da/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L164
and instead pass down either ints or the original TimeSpan instances.

Comment (tarekgh) [reply src/libraries/Common/src/System/TimeProvider.cs]: It is a good idea. I applied the suggestion. Also, I have removed all duration/period validation inside the TimeProvider timer. This is because we use the system timers which already validate the duration and the period.

**Review by stephentoub — APPROVED** [review]
Thanks.

**Comment by tarekgh** [comment]
Thanks @martincostello for reporting this issue.
