### PR TITLE
Fix AMD64 epilog ABI

### LINKED ISSUE #54320: JIT emits non-compliant epilogs on Windows x64
For Windows x64 JIT generates a `LEA RSP` instruction in epilogs without emitting the `UWOP_SET_FPREG` unwind code, which is not allowed according to the [documentation](https://docs.microsoft.com/en-us/cpp/build/prolog-and-epilog?view=msvc-160#epilog-code):
> When a frame pointer is not used, the epilog must use `add RSP,constant` to deallocate the fixed part of the stack. It may not use `lea RSP,constant[RSP]` instead. This restriction exists so the unwind code has fewer patterns to recognize when searching for epilogs.

The issue can be demonstrated by running `R2RDump -d` on one of framework assemblies containing R2R code and searching for `LEA RSP`.  For instance, `IntPtr Interop+Kernel32.GetStdHandle(int)` method in `System.Console.dll` has the following R2R code:
```asm
push    rbp
UWOP_PUSH_NONVOL RBP
push    rsi
UWOP_PUSH_NONVOL RSI
sub     rsp, 40
UWOP_ALLOC_SMALL 40
lea     rbp, [rsp + 48]
...
lea     rsp, [rbp - 8]
pop     rsi
pop     rbp
ret
```

### PR DESCRIPTION
**Pull request by BruceForstall**
The Windows AMD64 epilog ABI states that an `lea rsp,[rbp+constant]` instruction
may only be used if a frame pointer has been reported to the OS in the prolog
unwind info, otherwise an `add rsp, constant` instruction must be used.
There were a number of cases where the JIT used the `lea` form simply because
a frame pointer had been established and was available, even though it had not
been reported to the OS (and, thus, the frame was effectively an `rsp` frame).

Fix this by using the same condition in the epilog for determining which form
to use, `lea` or `add`, that was used in the prolog to determine whether or not
to report the frame pointer in the unwind info.

Fixes #54320

### CODE REVIEW

**Comment by BruceForstall** [comment]
Code size diffs are either break-even or a slight loss due to sometimes larger encodings of `add` versus `lea`. E.g., benchmarks, below.

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 2249335
Total bytes of diff: 2251932
Total bytes of delta: 2597 (0.12% of base)
Total relative delta: 4.00
    diff is a regression.
    relative diff is a regression.
```
<details>

<summary>Detail diffs</summary>

```


Top file regressions (bytes):
          18 : 24245.dasm (0.96% of base)
          13 : 18451.dasm (1.75% of base)
          12 : 19246.dasm (1.41% of base)
          12 : 2225.dasm (1.87% of base)
          12 : 21541.dasm (0.24% of base)
          12 : 4595.dasm (1.68% of base)
          12 : 6770.dasm (1.91% of base)
          12 : 11335.dasm (0.61% of base)
          12 : 10723.dasm (1.72% of base)
          12 : 11219.dasm (1.73% of base)
          12 : 11609.dasm (2.27% of base)
          12 : 5125.dasm (1.04% of base)
          12 : 3941.dasm (2.56% of base)
          12 : 395.dasm (1.72% of base)
          10 : 21624.dasm (0.80% of base)
          10 : 2719.dasm (0.87% of base)
           9 : 12012.dasm (0.41% of base)
           9 : 17725.dasm (0.52% of base)
           9 : 3263.dasm (0.19% of base)
           9 : 11107.dasm (0.76% of base)

686 total files with Code Size differences (0 improved, 686 regressed), 6241 unchanged.

Top method regressions (bytes):
          18 ( 0.96% of base) : 24245.dasm - V8.Crypto.BigInteger:divRemTo(V8.Crypto.BigInteger,V8.Crypto.BigInteger,V8.Crypto.BigInteger):this
          13 ( 1.75% of base) : 18451.dasm - Microsoft.CodeAnalysis.ImmutableArrayExtensions:ToDictionary(System.Collections.Immutable.ImmutableArray`1[__Canon],System.Func`2[__Canon,__Canon],System.Collections.Generic.IEqualityComparer`1[__Canon]):System.Collections.Generic.Dictionary`2[__Canon,ImmutableArray`1]
          12 ( 1.41% of base) : 19246.dasm - Microsoft.CodeAnalysis.CSharp.MethodCompiler:GetEntryPoint(Microsoft.CodeAnalysis.CSharp.CSharpCompilation,Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder,bool,Microsoft.CodeAnalysis.DiagnosticBag,System.Threading.CancellationToken):Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol
          12 ( 1.87% of base) : 2225.dasm - FormatterCache`1[__Canon][System.__Canon]:.cctor()
          12 ( 0.24% of base) : 21541.dasm - System.Diagnostics.Tracing.EventSource:CreateManifestAndDescriptors(System.Type,System.String,System.Diagnostics.Tracing.EventSource,int):System.Byte[]
          12 ( 1.68% of base) : 4595.dasm - System.Linq.Enumerable:ToDictionary(System.Collections.Generic.IEnumerable`1[Int32],System.Func`2[Int32,Int32],System.Func`2[Int32,ValueTuple`4],System.Collections.Generic.IEqualityComparer`1[Int32]):System.Collections.Generic.Dictionary`2[Int32,ValueTuple`4]
          12 ( 1.91% of base) : 6770.dasm - FormatterCache`1[__Canon][System.__Canon]:.cctor()
          12 ( 0.61% of base) : 11335.dasm - Jil.Serialize.InlineSerializer`1[__Canon][System.__Canon]:WriteKeyValue(System.Reflection.MemberInfo,System.Type,System.Type):this
          12 ( 1.72% of base) : 10723.dasm - System.TimeZoneInfo:GetLocalTimeZone(CachedData):System.TimeZoneInfo
          12 ( 1.73% of base) : 11219.dasm - Newtonsoft.Json.Serialization.JsonSerializerInternalReader:SetPropertyValue(Newtonsoft.Json.Serialization.JsonProperty,Newtonsoft.Json.JsonConverter,Newtonsoft.Json.Serialization.JsonContainerContract,Newtonsoft.Json.Serialization.JsonProperty,Newtonsoft.Json.JsonReader,System.Object):bool:this
          12 ( 2.27% of base) : 11609.dasm - System.IO.Compression.BrotliDecoder:Decompress(System.ReadOnlySpan`1[Byte],System.Span`1[Byte],byref,byref):int:this
          12 ( 1.04% of base) : 5125.dasm - System.IO.Strategies.BufferedFileStreamStrategy:ReadAsync(System.Memory`1[Byte],System.Threading.CancellationToken):System.Threading.Tasks.ValueTask`1[Int32]:this
          12 ( 2.56% of base) : 3941.dasm - Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory:TryCreateOpenGeneric(Microsoft.Extensions.DependencyInjection.ServiceDescriptor,System.Type,Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain,int,bool):Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite:this
          12 ( 1.72% of base) : 395.dasm - System.Reflection.CustomAttribute:IsCustomAttributeDefined(System.Reflection.RuntimeModule,int,System.RuntimeType,int,bool):bool
          10 ( 0.80% of base) : 21624.dasm - Microsoft.Extensions.Logging.EventSource.EventSourceLogger:Log(int,Microsoft.Extensions.Logging.EventId,LogValues`2[Int32,__Canon],System.Exception,System.Func`3[LogValues`2,__Canon,__Canon]):this
          10 ( 0.87% of base) : 2719.dasm - System.Collections.Concurrent.ConcurrentDictionary`2[StructMultiKey`2,__Canon][Newtonsoft.Json.Utilities.StructMultiKey`2[System.__Canon,System.__Canon],System.__Canon]:TryAddInternal(Newtonsoft.Json.Utilities.StructMultiKey`2[__Canon,__Canon],System.Nullable`1[Int32],System.__Canon,bool,bool,byref):bool:this
           9 ( 0.41% of base) : 12012.dasm - System.Xml.Serialization.ReflectionAwareILGen:ILGenForCreateInstance(System.Xml.Serialization.CodeGenerator,System.Type,System.Type,bool):this
           9 ( 0.52% of base) : 17725.dasm - Microsoft.CodeAnalysis.PEModule:GetTargetAttributeSignatureIndex(System.Reflection.Metadata.MetadataReader,System.Reflection.Metadata.CustomAttributeHandle,Microsoft.CodeAnalysis.AttributeDescription):int
           9 ( 0.19% of base) : 3263.dasm - System.Xml.Serialization.XmlReflectionImporter:InitializeStructMembers(System.Xml.Serialization.StructMapping,System.Xml.Serialization.StructModel,bool,System.String,System.Xml.Serialization.RecursionLimiter):bool:this
           9 ( 0.76% of base) : 11107.dasm - System.Runtime.Serialization.Formatters.Binary.ObjectWriter:Write(System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo,System.Runtime.Serialization.Formatters.Binary.NameInfo,System.Runtime.Serialization.Formatters.Binary.NameInfo):this

Top method regressions (percentages):
          12 ( 2.56% of base) : 3941.dasm - Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory:TryCreateOpenGeneric(Microsoft.Extensions.DependencyInjection.ServiceDescriptor,System.Type,Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain,int,bool):Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite:this
           6 ( 2.37% of base) : 10705.dasm - CachedData:GetCurrentOneYearLocal():System.TimeZoneInfo
          12 ( 2.27% of base) : 11609.dasm - System.IO.Compression.BrotliDecoder:Decompress(System.ReadOnlySpan`1[Byte],System.Span`1[Byte],byref,byref):int:this
           6 ( 2.14% of base) : 16272.dasm - System.Net.NetworkInformation.SystemIPInterfaceStatistics:GetIfEntry2(long):MibIfRow2
          12 ( 1.91% of base) : 6770.dasm - FormatterCache`1[__Canon][System.__Canon]:.cctor()
          12 ( 1.87% of base) : 2225.dasm - FormatterCache`1[__Canon][System.__Canon]:.cctor()
           9 ( 1.79% of base) : 4927.dasm - System.IO.Compression.BrotliEncoder:Compress(System.ReadOnlySpan`1[Byte],System.Span`1[Byte],byref,byref,int):int:this
          13 ( 1.75% of base) : 18451.dasm - Microsoft.CodeAnalysis.ImmutableArrayExtensions:ToDictionary(System.Collections.Immutable.ImmutableArray`1[__Canon],System.Func`2[__Canon,__Canon],System.Collections.Generic.IEqualityComparer`1[__Canon]):System.Collections.Generic.Dictionary`2[__Canon,ImmutableArray`1]
          12 ( 1.73% of base) : 11219.dasm - Newtonsoft.Json.Serialization.JsonSerializerInternalReader:SetPropertyValue(Newtonsoft.Json.Serialization.JsonProperty,Newtonsoft.Json.JsonConverter,Newtonsoft.Json.Serialization.JsonContainerContract,Newtonsoft.Json.Serialization.JsonProperty,Newtonsoft.Json.JsonReader,System.Object):bool:this
          12 ( 1.72% of base) : 395.dasm - System.Reflection.CustomAttribute:IsCustomAttributeDefined(System.Reflection.RuntimeModule,int,System.RuntimeType,int,bool):bool
          12 ( 1.72% of base) : 10723.dasm - System.TimeZoneInfo:GetLocalTimeZone(CachedData):System.TimeZoneInfo
          12 ( 1.68% of base) : 4595.dasm - System.Linq.Enumerable:ToDictionary(System.Collections.Generic.IEnumerable`1[Int32],System.Func`2[Int32,Int32],System.Func`2[Int32,ValueTuple`4],System.Collections.Generic.IEqualityComparer`1[Int32]):System.Collections.Generic.Dictionary`2[Int32,ValueTuple`4]
           3 ( 1.60% of base) : 3217.dasm - ILStubClass:IL_STUB_PInvoke(System.Runtime.CompilerServices.QCallTypeHandle):bool
           3 ( 1.60% of base) : 9765.dasm - ILStubClass:IL_STUB_PInvoke(byref,byref):int
           6 ( 1.60% of base) : 973.dasm - System.Runtime.Loader.AssemblyLoadContext:OnProcessExit()
           3 ( 1.55% of base) : 3168.dasm - ILStubClass:IL_STUB_PInvoke(System.Runtime.CompilerServices.QCallAssembly,System.Runtime.CompilerServices.StringHandleOnStack):bool
           9 ( 1.53% of base) : 19289.dasm - Microsoft.CodeAnalysis.Compilation:SerializePeToStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder,Microsoft.CodeAnalysis.DiagnosticBag,Microsoft.CodeAnalysis.CommonMessageProvider,System.Func`1[[System.IO.Stream, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],System.Func`1[[System.IO.Stream, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],System.Func`1[[System.IO.Stream, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],Microsoft.Cci.PdbWriter,System.String,bool,bool,bool,bool,System.Nullable`1[RSAParameters],System.Threading.CancellationToken):bool
           3 ( 1.52% of base) : 289.dasm - System.ModuleHandle:GetModuleType(System.Reflection.RuntimeModule):System.RuntimeType
           9 ( 1.51% of base) : 10430.dasm - System.Reflection.PortableExecutable.PEReader:TryOpenCodeViewPortablePdb(System.Reflection.PortableExecutable.DebugDirectoryEntry,System.String,System.Func`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.Stream, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],byref,byref,byref):bool:this
           3 ( 1.50% of base) : 15736.dasm - ILStubClass:IL_STUB_PInvoke(int,int,long,long,byref):int

686 total methods with Code Size differences (0 improved, 686 regressed), 6241 unchanged.

```

</details>

--------------------------------------------------------------------------------

**Comment by BruceForstall** [comment]
@AntonLapounov @kunalspathak @dotnet/jit-contrib PTAL

cc @janvorli

**Review by AntonLapounov — APPROVED** [review]
Thank you!

File: src/coreclr/jit/codegencommon.cpp [hunk 1]
```diff
@@ -8177,6 +8201,15 @@ void CodeGen::genFnEpilog(BasicBlock* block)
 
         genPopCalleeSavedRegisters();
 
+#ifdef TARGET_AMD64
+        // In the case where we have an RSP frame, and no frame pointer reported in the OS unwind info,
+        // but we do have a pushed frame pointer and established frame chain, we do need to pop RBP.
+        if (doubleAlignOrFramePointerUsed())
+        {
+            inst_RV(INS_pop, REG_EBP, TYP_I_IMPL);
```
Comment (pmsjt) [inline src/coreclr/jit/codegencommon.cpp:8209]: I am not very familiar with the domain specific language in this compiler, but this is not the fix I was expecting. In the cases I analyzed, the POP RBP instruction was already there. What was missing was the UWOP_SET_FPREG unwind opcode in the prolog, when `lea rbp, [rsp + x]` is done.

Comment (BruceForstall) [reply src/coreclr/jit/codegencommon.cpp:8209]: The fix requires us to go down this code path, where we didn't previously need to pop EBP, but now we do. Basically, we don't need to add cases of setting UWOP_SET_FPREG; that was already correct. We need to remove cases where we were using `lea` to pop off the frame.

Comment (pmsjt) [reply src/coreclr/jit/codegencommon.cpp:8209]: Ok, so you are following the route of not setting a frame pointer at all. And this change will cause the compiler to emit an ADD RSP instead?

Comment (BruceForstall) [reply src/coreclr/jit/codegencommon.cpp:8209]: There are two frame types: RSP and RBP. For the RSP frame types, we don't emit UWOP_SET_FPREG, and restore the frame using `add rsp, constant`. However, there are still cases with RSP frames where we will save and restore the RBP register and establish a frame chain; we just don't report RBP as a frame pointer to the OS, since it isn't required for unwinding. For RBP frame types, we set UWOP_SET_FPREG and use `lea rsp, [rbp+constant]` to restore the stack. RBP frame types are typically required for alloca/stackalloc (dynamic frame size).

This change fixes the RSP frame case where we also happen to save/restore the RBP register, to not restore the stack using that RBP register.

Comment (pmsjt) [reply src/coreclr/jit/codegencommon.cpp:8209]: Yup, I understand the problem. After all it was me who reported it. I am just not seeing how this change will address the problem: making sure non-fp functions use add rsp to de-allocate the stack frame. Instead it seems as it is add a pop rbp. Am I reading it wrong?

**Comment by jakobbotsch** [comment]
Are we sure that #54320 is actually an issue? The documentation states that `lea RSP,constant[RSP]` is invalid, but that's not the form we're generating. And the documentation is stating that this is so the unwind code has to recognize fewer patterns -- presumably, that's because addressing off of `rsp` requires a SIB byte. The form we are generating in the example does not.

**Comment by BruceForstall** [comment]
Failures all look like infra, or other existing failures.

File: src/coreclr/jit/codegencommon.cpp (hunk 1 above)
Comment (jaykrell) [reply src/coreclr/jit/codegencommon.cpp:8209]: My read is..there was kinda a third case, where the code resembled or matched an RBP frame, but had no `UWOP_SET_FPREG` (and was correct).

Now they are following a very strict interpretation, where `lea rsp, [rbp+constant]` is only used if there is `UWOP_SET_FPREG`.

I am not sure this strictness is required but it is of course ok.
