### PR TITLE
Ensure that we are correctly typing simd comparison nodes

### LINKED ISSUE #105623: JIT: Assertion failed '!varTypeIsMask(tree)' during 'Linear scan register alloc'
```csharp
// Generated by Fuzzlyn v2.1 on 2024-07-28 20:13:41
// Run on X64 Linux
// Seed: 1985194660224925106-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86avx512fx64,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 33.0 KiB to 0.5 KiB in 00:00:30
// Hits JIT assert in Release:
// Assertion failed '!varTypeIsMask(tree)' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Linear scan register alloc' (IL size 55; hash 0xade6b36b; FullOpts)
// 
//     File: /__w/1/s/src/coreclr/jit/lsraxarch.cpp Line: 3113
// 
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static void Main()
    {
        uint[, ][] vr4 = default(uint[, ][]);
        var vr5 = Vector256.Create<sbyte>(0);
        var vr6 = vr4[0, 0][0];
        var vr7 = (sbyte)Sse42.Crc32(vr6, 0);
        var vr8 = Vector256.Create<sbyte>(vr7);
        Vector256<sbyte> vr9 = Avx512BW.VL.CompareLessThan(vr5, vr8);
        System.Console.WriteLine(vr9);
    }
}
```

SPMI collection captured on 0912e94a attached.
[6890D5D7.zip](https://github.com/user-attachments/files/16414023/6890D5D7.zip)

### PR DESCRIPTION
**Pull request by tannergooding**
This fixes #105623

### CODE REVIEW

**Comment by tannergooding** [comment]
cc @dotnet/jit-contrib this is ready for review and resolves #105623

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -11553,45 +11558,62 @@ GenTree* Compiler::fgMorphHWIntrinsic(GenTreeHWIntrinsic* tree)
...
-                                                                                          simdBaseType, simdSize, false);
+                    if (newId != NI_Illegal)
+                    {
+                        tree->ResetHWIntrinsicId(newId, op2, op1);
 
-                    tree->ResetHWIntrinsicId(newId, op2, op1);
+                        if (lookupType != retType)
+                        {
+                            assert(varTypeIsMask(lookupType));
+                            tree->gtType = lookupType;
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:11575]: Why is it ok to retype `tree` to a mask type here if it didn't start out as a mask type? Won't the parent node be expecting a non-mask type?

Comment (tannergooding) [reply src/coreclr/jit/morph.cpp:11575]: Because we're inserting and returning the `CvtMaskToVector` below if the final tree produced by morph ends up mismatching.

We don't insert it here because we still want to try and fold and finish morphing the new comparison node in case other optimizations are available.

There's many morph paths that return new nodes, so this should be no different.

Comment (tannergooding) [reply src/coreclr/jit/morph.cpp:11575]: -- It's inserted here: https://github.com/dotnet/runtime/pull/105883/files/92b5f01f4d490f84949f1afc3c9eb02678394b57#diff-5b83397bbbdd17bb9457998b520fdaaa474d165390985b66f32371561b6d0bacR11610-R11616

We make this transform, we try to fold, we try to optimize, and then we insert the `CvtMaskToVector` in the case the expected and actual return types mismatch.

**Review by jakobbotsch — APPROVED** [review]
