### PR TITLE
[wasm][debugger] Pass-through all `scriptParsed` events, including those with empty URLs

### LINKED ISSUE #42340: MonoProxy send stack traces with reference to script that wasn't notified
1. Create a new Blazor WebAssembly project in VS
2. Set breakpoint at line14(currentCount++) of "Pages\Counter.razor".
3. Debug Project with Chrome
4. Navigate the web page to the counter page
5. Click the click me button
6. After hitting the breakpoint press step into two times

We get this stack frame:
          {
            "callFrameId": "{\"ordinal\":0,\"injectedScriptId\":2}",
            "functionName": "monoeg_g_free",
            "location": {
              "scriptId": "16",
              "lineNumber": 0,
              "columnNumber": 22343
            },

But we never got a scriptParsed event with id 16. We got these:
image

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/42340. 
We introduced the empty `url` check here: https://github.com/mono/mono/commit/dce53cc9f31aab3883ca85303ba42ec9b22caea7. After removing it I do not see any side effects when debugging, both native and user code.

Number of additional traffic caused by removing `return true`:
- startup: ~200 messages with empty URL
- hitting a breakpoint: ~30
- resume: 1
- remove breakpoint: 1
- set breakpoint: 3
- step over/ step into: ~20,
- onEval: ~40,
- getProperties: ~80.

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 1]
```diff
@@ -214,16 +214,9 @@ protected override async Task<bool> AcceptEvent(SessionId sessionId, JObject par
...
-                        switch (url)
-                        {
-                            case var _ when url == "":
-                            {
-                                logger.LogTrace($"ignoring empty: Debugger.scriptParsed {url}");
-                                return true;
-                            }
-                        }
                         logger.LogTrace($"proxying Debugger.scriptParsed ({sessionId.sessionId}) {url} {args}");
+                        if (url == "")
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:218]: Isn't this same as the existing code? Logs a message, and return true if `url == ""`?

Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:218]: yes, it is. I need to think about it a bit more

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 2]
```diff
@@ -214,15 +214,6 @@ protected override async Task<bool> AcceptEvent(SessionId sessionId, JObject par
                 case "Debugger.scriptParsed":
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:214]: If we are not doing anything for this, and simply passing it on, then do we need this at all? If we don't have this block then it would be the same behavior, minus the ` logger.LogTrace($"proxying Debugger.scriptParsed ({sessionId.sessionId}) {url} {args}");`.
@thaystg does having the log message sound useful for debugging?

**Comment by ilonatommy** [comment]
@lewing That's my first video, if it's too chaotic or I should re-record with a focus on any particular issue, let me know. 

https://user-images.githubusercontent.com/32700855/193264244-649e3ba2-1ba6-44b9-9fe2-d8d71dba7334.mp4

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs (hunk 2 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:214]: I don't think we need the log message.

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:214]: And it would be getting logged already as a protocol message.

Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:214]: Checked what @radical suggested offline and indeed, we had log duplicates because of this line.

**Comment by ilonatommy** [comment]
> Are these getting generated for the small snippets of js we use, like `"getDotnetRuntime({runtimeId}).INTERNAL.mono_wasm_get_loaded_files()`?

"getDotnetRuntime(0).INTERNAL.mono_wasm_runtime_is_ready"
generates one `Debugger.scriptParsed` per source with URL:

http://localhost:9400/debugger-driver.html
http://localhost:9400/other.js
http://localhost:9400/debugger-main.js
http://localhost:9400/dotnet.js
http://localhost:9400/dotnet.wasm
etc

each command command:
"getDotnetRuntime(0).INTERNAL.mono_wasm_send_dbg_command (1, 15, 3,'')"
"getDotnetRuntime(0).INTERNAL.mono_wasm_debugger_attached()"
"getDotnetRuntime(0).INTERNAL.mono_wasm_get_dbg_command_info()"
"getDotnetRuntime(0).INTERNAL.mono_wasm_get_loaded_files()"

generate one `Debugger.scriptParsed` with empty URL
other `to-browser` commands (e.g. "Debugger.resume", "Runtime.evaluate") do not generate `Debugger.scriptParsed` events.

**Review by radical — APPROVED** [review]
