### PR TITLE
JIT: Fix generating unrepresentable nullchecks on ARM64

### LINKED ISSUE #71684: Assertion failed '(shiftAmount == scale) || (shiftAmount == 0)'
```
 Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 21 [0x00000015], Thread: 37 [0x0025]): Assertion failed '(shiftAmount == scale) || (shiftAmount == 0)' in 'Microsoft.CodeAnalysis.DotnetRuntime.Extensions.SyntaxValueProviderExtensions:<GetMatchingNodes>g__matchesAttributeName|4_2(byref,byref,System.String,bool,byref):bool' during 'Generate code' (IL size 286; hash 0x72e8996c; Tier1)

    File: /__w/1/s/src/coreclr/jit/emitarm64.cpp Line: 7028
```

```json
{ "ErrorMessage" : "Assertion failed '(shiftAmount == scale) || (shiftAmount == 0)'" }
```<!--Known issue error report start -->
### Report
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|
<!--Known issue error report end -->

### PR DESCRIPTION
**Pull request by jakobbotsch**
The logic in lowering could in some struct and primitive type cases
generate an unrepresentable NULLCHECK node for ARM64/LA64 when there
was a contained address mode. We now transform unused indirections and
create address modes in the opposite order on non-xarch to avoid these unrepresentable
nullchecks.

Fix #71684

### CODE REVIEW

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/compiler.cpp [hunk 1]
```diff
@@ -9972,16 +9972,21 @@ bool Compiler::lvaIsOSRLocal(unsigned varNum)
 //
 var_types Compiler::gtTypeForNullCheck(GenTree* tree)
 {
-    if (varTypeIsArithmetic(tree))
+    static const var_types s_typesBySize[] = {TYP_UNDEF, TYP_BYTE,  TYP_SHORT, TYP_UNDEF, TYP_INT,
+                                              TYP_UNDEF, TYP_UNDEF, TYP_UNDEF, TYP_LONG};
+
+    if (!varTypeIsStruct(tree))
```
Comment (EgorBo) [inline src/coreclr/jit/compiler.cpp:9978]: Btw, is TYP_SIMD is reported as struct?

Comment (jakobbotsch) [reply src/coreclr/jit/compiler.cpp:9978]: Yep, `varTypeIsStruct` is true for the SIMD types.
