### PR TITLE
low memory fixes

### LINKED ISSUE #55684: [Regions] Avoid declaring an object cannot fit in a segment if we already have committed space for it
In https://github.com/dotnet/runtime/pull/55585, I fixed the segment case. We need the same fix for regions.

The problem is that our code easily run into OutOfMemory in small containers.

**Repro:**

1. Build a Windows X64 Release CoreRoot out of this commit [85cadd9650b3a2311278d2734d22007c8f297405](https://github.com/dotnet/runtime/commit/85cadd9650b3a2311278d2734d22007c8f297405)
2. Run GCPerfSim using the CoreRoot using these parameters

```
GCPerfSim.dll -tc 6 -tagb 100.0 -tlgb 0.07 -lohar 0 -pohar 0 -sohsi 10 -lohsi 0 -pohsi 0 -sohsr 100-4000 -lohsr 102400-204800 -pohsr 100-4000 -sohpi 10 -lohpi 0 -sohfi 0 -lohfi 0 -pohfi 0 -allocType reference -testKind time
```

under these configuration:

```
COMPlus_GCHeapCount=6
COMPlus_GCHeapHardLimit=1C200000
COMPlus_GCServer=1
```

This repro is not particularly easy to work with. With high probability, the process fails with https://github.com/dotnet/runtime/issues/74401 instead.

### PR DESCRIPTION
**Pull request by cshung**
This PR is a combination of the individual fixes that I did for the low memory condition.

This is the accumulation of #76217, #76216, #76214, #75572, #75208, #75038, #74626. The issues are well described in the individual PRs. It is also much easier to review them in pieces there.

Together with #74625 (which was merged earlier accidentally), this change is intended for .NET 7. 

Fixes #55684

### CODE REVIEW

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -2855,12 +2861,18 @@ size_t     gc_heap::interesting_mechanism_bits_per_heap[max_gc_mechanism_bits_co
...
 bool gc_heap::special_sweep_p = false;
+#endif //USE_REGIONS
+
+int gc_heap::loh_pinned_queue_decay = LOH_PIN_DECAY;
 
 #endif // MULTIPLE_HEAPS
 
 /* end of per heap static initialization */
 
+const size_t uninitialized_end_gen0_region_space = (size_t)(-1);
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:2874]: this is only used for regions, you could move it to the #ifdef USE_REGIONS right above.

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -6915,21 +6935,41 @@ bool gc_heap::virtual_commit (void* address, size_t size, int bucket, int h_numb
...
+#else
+            base = current_total_committed;
+            limit = heap_hard_limit;
+#endif
+            if ((base + size) > limit)
+            {
+                dprintf (1, ("%Id + %Id = %Id > limit %Id ",
+                    base, size,
+                    (base + size),
+                    limit));
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:6969]:
```suggestion
                dprintf (1, ("%Id + %Id = %Id > limit %Id ", base, size, (base + size), limit));
```
nit - now this is pretty short so we can put it all on one line...

File: src/coreclr/gc/gc.cpp [hunk 3]
```diff
@@ -12632,7 +12707,6 @@ void gc_heap::distribute_free_regions()
                 }
             }
         }
-
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:12635]: would be nice to not do these "deleting random empty lines" kind of changes.

File: src/coreclr/gc/gc.cpp [hunk 4]
```diff
@@ -6915,21 +6935,41 @@ bool gc_heap::virtual_commit (void* address, size_t size, int bucket, int h_numb
         check_commit_cs.Enter();
         bool exceeded_p = false;
 
-        if (heap_hard_limit_oh[bucket] != 0)
+        if ((heap_hard_limit_oh[soh] != 0) && (bucket < total_oh_count) && (heap_hard_limit_oh[bucket] != 0))
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:6938]: do we really need to check `heap_hard_limit_oh[soh]`, then check `heap_hard_limit_oh[bucket]` again?

File: src/coreclr/gc/gc.cpp [hunk 5]
```diff
@@ -12674,7 +12748,11 @@ void gc_heap::distribute_free_regions()
             {
                 next_region = heap_segment_next (region);
                 int age_in_free_to_decommit = min (max (AGE_IN_FREE_TO_DECOMMIT, n_heaps), MAX_AGE_IN_FREE);
-                if (heap_segment_age_in_free (region) >= age_in_free_to_decommit)
+                if (
+                     (heap_segment_age_in_free (region) >= age_in_free_to_decommit)
+                     ||
+                     ((get_region_committed_size (region) == GC_PAGE_SIZE) && joined_last_gc_before_oom)
+                   )
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:12755]: nit - styling. no need to put these on separate lines unless you have to check for #ifdef's...

```suggestion
                // when we are about to get OOM, we'd like to discount the free regions that just have the initial page commit as they are not useful
                if ((heap_segment_age_in_free (region) >= age_in_free_to_decommit) ||
                    ((get_region_committed_size (region) == GC_PAGE_SIZE) && joined_last_gc_before_oom))
```

File: src/coreclr/gc/gc.cpp [hunk 6]
```diff
@@ -41356,20 +41524,49 @@ bool gc_heap::check_against_hard_limit (size_t space_required)
...
+    else
+    {
+        return false;
+    }
+}
+
 bool gc_heap::sufficient_space_regions (size_t end_space, size_t end_space_required)
 {
     // REGIONS PERF TODO: we can repurpose large regions here too, if needed.
+    // REGIONS PERF TODO: for callsites other than allocation, we should take commit into account
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:41556]:
```suggestion
    // REGIONS PERF TODO: for callsites other than allocation, we should also take commit into account
```

**Review by Maoni0 — APPROVED** [review]

File: src/coreclr/gc/gc.cpp [hunk 7]
```diff
@@ -13517,6 +13590,26 @@ HRESULT gc_heap::initialize_gc (size_t soh_segment_size,
...
+        size_t bookkeeping_size_per_region = 0;
+        uint8_t* temp_lowest_address = (uint8_t*)gc_region_size;
+        gc_heap::get_card_table_element_sizes(temp_lowest_address, temp_lowest_address + gc_region_size, sizes);
+        for (int i = 0; i < total_bookkeeping_elements; i++)
+        {
+            bookkeeping_size_per_region += sizes[i];
+        }
+        size_t total_size_per_region = gc_region_size + bookkeeping_size_per_region;
+        size_t max_region_count = gc_heap::heap_hard_limit / total_size_per_region; // implictly rounded down
+        gc_heap::heap_hard_limit_for_heap = max_region_count * gc_region_size;
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:13607]: >:heap_hard_limit_for_heap [](http://example.com/codeflow?start=16&length=25)

since these are not used when per OH limit is specified, it'd be better to just set them to some special value that we can assert in virtual_commit

**Comment by cshung** [comment]
Rebasing to latest to test CI again

**Review by Maoni0 — APPROVED** [review]
