### PR TITLE
Fix String.IsInterned regression

### LINKED ISSUE #99386: String.IsInterned always interns the string passed in to it
### Description

Through .NET 8.0, `System.String.IsInterned(System.String)` returned either the same string passed in to it (if that string was interned) or `null` (if the string was not interned). This matches the [documentation for this method](https://learn.microsoft.com/en-us/dotnet/api/system.string.isinterned?view=net-8.0). The implementation for .NET 8.0 is:

```
public static string? IsInterned(string str)
{
    ArgumentNullException.ThrowIfNull(str, "str");
    return str.IsInterned();
}
```

As of .NET 9.0 Preview 1, `IsInterned` now always interns the string passed in to it. Its implementation is:

```
public static string? IsInterned(string str)
{
    ArgumentNullException.ThrowIfNull(str, "str");
    Intern(new StringHandleOnStack(ref str));
    return str;
}
```

This appears to be an unintentional change in behavior while converting FCalls to QCalls in #95670.

### Reproduction Steps

When run under .NET Framework or versions of .NET [Core] up to 8.0, this snippet indicates that the string is not interned (as expected). When run under .NET 9.0 Preview 1, this snippet indicates that the string _is_ interned (because it just interned it).

```
string value = Guid.NewGuid().ToString();

Console.WriteLine($"Interned == {ReferenceEquals(value, string.IsInterned(value))}");
```

[StringInterningRepro.zip](https://github.com/dotnet/runtime/files/14517340/StringInterningRepro.zip)

### Expected behavior

I do not expect `System.String.IsInterned` to intern the string passed in to it.

### Actual behavior

`System.String.IsInterned` interns the string passed in to it.

### Regression?

This behavior is new with .NET 9.0 Preview 1. It was not seen with .NET Framework or any prior .NET [Core] versions.

### Known Workarounds

_No response_

### Configuration

- .NET 9.0 Preview 1
- Windows 11
- x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkotas**
Introduced by FCall to QCall conversion

Fixes #99386

### CODE REVIEW

File: src/libraries/Common/tests/Tests/System/StringTests.cs [hunk 1]
```diff
@@ -7629,6 +7629,17 @@ public static void InternalTestAotSubset()
 #pragma warning restore 0618 // restore warning when accessing obsolete members
         }
 
+        [Fact]
+        public static void InternTestCanReturnNull()
+        {
+            for (int i = 0; i < 20; i++)
```
Comment (stephentoub) [inline src/libraries/Common/tests/Tests/System/StringTests.cs:7635]: 2 would be sufficient to validate what we're trying to validate, right? The 20 here is just for good measure? Just checking :)

Comment (stephentoub) [reply src/libraries/Common/tests/Tests/System/StringTests.cs:7635]: (Or, I guess you're just testing 20 different strings because you're calling NewGuid().ToString() each time. Nevermind.)

**Review by stephentoub — APPROVED** [review]
