### PR TITLE
Explicitly check for arrays in Marshal.SizeOf impl.

### LINKED ISSUE #44508: .NET 5.0 Segmentation Fault - Marshal.SizeOf
When updating to .NET 5.0 today and running on Linux (Ubuntu 20.04), we're getting a Segmentation fault (core dumped) error. Everything continues to work well using .netcoreapp3.1.

Are there any recommended tools that can help isolate the call before the SIGSEGV? I've tried running the app with gdb which provides the thread list.

I'll work on isolating this further and reproducing a minimal repo.

Here's how we're building and running the app.

```
publish ./src/App -f net5.0 -c release -r linux-x64 -o 
```

```
./App -> Segmentation fault (core dumped)
```

---

GDB output.

```
gdb ./App
(gdb)  run -d -L debug
Starting program: /var/apps/135/0.6.203/App -d -L debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6b30700 (LWP 12374)]
[New Thread 0x7ffff632f700 (LWP 12375)]
[New Thread 0x7ffff5b2e700 (LWP 12376)]
[New Thread 0x7ffff5324700 (LWP 12377)]
[New Thread 0x7ffff4adf700 (LWP 12378)]
[New Thread 0x7fffe7fff700 (LWP 12379)]
[New Thread 0x7ffff4095700 (LWP 12380)]
[New Thread 0x7fffe74dc700 (LWP 12381)]
[New Thread 0x7fff7d2ab700 (LWP 12382)]
[New Thread 0x7fffe711e700 (LWP 12383)]
[New Thread 0x7ffd291fa700 (LWP 12384)]
[New Thread 0x7fff7c598700 (LWP 12385)]
[New Thread 0x7ffd289f9700 (LWP 12386)]
[New Thread 0x7ffd0bfff700 (LWP 12387)]
[New Thread 0x7ffd0b7fe700 (LWP 12388)]
[New Thread 0x7ffd0affd700 (LWP 12389)]

Thread 1 "App" received signal SIGSEGV, Segmentation fault.
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
With the refactoring to lazily generate type interop data, we missed a corner case where we could sometimes end up trying to get the native size of an array. A debug runtime asserts, but a release runtime just ran through and crashed.

Explicitly check for arrays in `MarshalNative::SizeOfClass` since arrays of blittable types return true from `IsBlittable`.

Fixes #44508

### CODE REVIEW

File: src/coreclr/src/vm/marshalnative.cpp [hunk 1]
```diff
@@ -277,7 +277,7 @@ FCIMPL2(UINT32, MarshalNative::SizeOfClass, ReflectClassBaseObject* refClassUNSA
     // refClass is validated to be non-NULL RuntimeType by callers
     TypeHandle th = refClass->GetType();
 
-    if (throwIfNotMarshalable && !th.IsBlittable())
+    if (throwIfNotMarshalable && (!th.IsBlittable() || th.IsArray()))
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/src/vm/marshalnative.cpp:280]: Aside based on previous conversation.

Does the `char` type return true for `IsBlittable`? I am trying to understand what happens here for

```CSharp
struct A
{
   char c;
}
```

Comment (AaronRobinsonMSFT) [inline src/coreclr/src/vm/marshalnative.cpp:280]: There is similar logic in `IsStructMarshalable`. Are these two related?

https://github.com/dotnet/runtime/blob/5a6c21cb6285a3c110f0048d9bf657042ea4ca10/src/coreclr/src/vm/fieldmarshaler.cpp#L311-L320

Comment (AaronRobinsonMSFT) [reply src/coreclr/src/vm/marshalnative.cpp:280]: Based on the surrounding code am I to assume that the struct marshallers handle the above type and treat `char` as a blittable type?

**Review by jkotas — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky We should also consider this for .NET 5 servicing.

File: src/coreclr/src/vm/marshalnative.cpp (hunk 1 above)
Comment (jkoritzinsky) [reply src/coreclr/src/vm/marshalnative.cpp:280]: Yes, the above structure is handled by the struct marshalling infra (the `GetNativeSize` call below).

Comment (jkoritzinsky) [reply src/coreclr/src/vm/marshalnative.cpp:280]: Yes they are related. The `if` condition is basically a quick check for some possible failure cases so we can avoid doing a GC transition for blittable types.

Comment (AaronRobinsonMSFT) [reply src/coreclr/src/vm/marshalnative.cpp:280]: That should be noted here. Having these duplicate if checks is convoluted and breeds confusion about what is checking state and what isn't. I would like to see these two concept reconciled given the above has a nice comment but the one just introduced doesn't. This causes further confusion if one debugs through this a observes seemingly identical checks without a clear indicate as to why. Can the inner here be reused to fix this? If this is just an optimization to avoid the GC transition why was it still failing.
