### PR TITLE
Low level API support for Objective-C interop.

### LINKED ISSUE #44659: Low level API support for Objective-C scenarios
The [Blazor Desktop scenario](https://github.com/dotnet/aspnetcore/issues/27217) will require interop support for enabling the [usage of native UI components](https://github.com/dotnet/aspnetcore/issues/27239). A new API should be provided to facilitate this scenario.

## Goals:

- Support macOS version of [Xamarin-macios](https://github.com/xamarin/xamarin-macios) running on CoreCLR.
- Limit code changes to Xamarin bridge.

## Non-Goals:

- Support non-macOS scenarios (e.g. watchOS, tvOS, etc).
- Provide a flexible API for another Objective-C interop implementation approach.

# Proposed API

```CSharp
namespace System.Runtime.InteropServices.ObjectiveC
{
    /// <summary>
    /// Attribute used to indicate a class is tracked from the native environment.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class)]
    public class TrackedNativeReferenceAttribute : Attribute
    {
        /// <summary>
        /// Instantiate a <see cref="TrackedNativeReferenceAttribute"/> instance.
        /// </summary>
        public TrackedNativeReferenceAttribute() { }
    }

    /// <summary>
    /// API to enable an Objective-C bridge.
    /// </summary>
    public static class Bridge
    {
        /// <summary>
        /// Initialize reference tracking for the Objective-C bridge API.
        /// </summary>
        /// <param name="beginEndCallback">Called when tracking begins and ends.</param>
        /// <param name="isReferencedCallback">Called to determine if a managed object instance is referenced elsewhere, and must not be collected by the GC.</param>
        /// <param name="trackedObjectEnteredFinalization">Called when a tracked object enters the finalization queue.</param>
        /// <exception cref="InvalidOperationException">Thrown if this API has already been called.</exception>
        /// <remarks>
        /// All callbacks must be written in native code since they will be called by the GC and
        /// managed code is not able to run at that time.
        ///
        /// The <paramref name="beginEndCallback"/> will be called when reference tracking begins and ends.
        /// The associated begin/end pair will never be nested.
        ///
        /// The <paramref name="isReferencedCallback"/> should return 0 for not reference or 1 for
        /// referenced. Any other value has undefined behavior.
        /// </remarks>
        public static unsafe void InitializeReferenceTracking(
            delegate* unmanaged<void> beginEndCallback,
            delegate* unmanaged<IntPtr, int> isReferencedCallback,
            delegate* unmanaged<IntPtr, void> trackedObjectEnteredFinalization);

        /// <summary>
        /// Request native reference tracking for the supplied object.
        /// </summary>
        /// <param name="obj">The object to track.</param>
        /// <param name="scratchMemory">A pointer to scratch memory.</param>
        /// <returns>Reference tracking GC handle.</returns>
        /// <exception cref="InvalidOperationException">Thrown if the Bridge API has not been initialized.</exception>
        /// <remarks>
        /// Reference tracking in the <see cref="Bridge"/> must be initialized prior to calling
        /// this function.
        ///
        /// The <paramref name="obj"/> must have a type in its hierarchy marked with
        /// <see cref="TrackedNativeReferenceAttribute"/>.
        ///
        /// The "Is Referenced" callback passed to InitializeReferenceTracking
        /// will be passed the <paramref name="scratchMemory"/> returned from this function.
        /// The memory it points at is 2 pointer's worth (for example, 16 bytes on a 64-bit platform) and
        /// will be zeroed out and available until <paramref name="obj"/> is collected by the GC.
        /// The memory pointed to by <paramref name="scratchMemory"/> can be used for any purpose by the
        /// caller of this function and usable during the "Is Referenced" callback.
        ///
        /// Calling this function multiple times with the same <paramref name="obj"/> will
        /// return a new handle each time but the same scratch memory will be returned. The
        /// scratch memory is only guaranteed to be zero initialized on the first call.
        ///
        /// The caller is responsible for freeing the returned <see cref="GCHandle"/>.
        /// </remarks>
        public static GCHandle CreateReferenceTrackingHandle(
            object obj,
            out IntPtr scratchMemory);

        /// <summary>
        /// Objective-C msgSend function override options.
        /// </summary>
        /// <see href="https://developer.apple.com/documentation/objectivec/1456712-objc_msgsend"/>
        public enum MsgSendFunction
        {
            ObjCMsgSend,
            ObjCMsgSendFpret,
            ObjCMsgSendStret,
            ObjCMsgSendSuper,
            ObjCMsgSendSuperStret,
        }

        /// <summary>
        /// Set function pointer override for an Objective-C runtime message passing export.
        /// </summary>
        /// <param name="msgSendFunction">The export to override.</param>
        /// <param name="func">The function override.</param>
        /// <exception cref="InvalidOperationException">Thrown if the msgSend function has already been overridden.</exception>
        /// <remarks>
        /// Providing an override can enable support for Objective-C
        /// exception propagation and variadic argument support.
        /// </remarks>
        public static void SetMessageSendCallback(MsgSendFunction msgSendFunction, IntPtr func);

        /// <summary>
        /// Sets a pending exception for this thread to be thrown
        /// the next time the runtime is entered from an overridden
        /// msgSend P/Invoke.
        /// </summary>
        /// <param name="exception">The exception.</param>
        /// <remarks>
        /// If <c>null</c> is supplied any pending exception is discarded.
        /// </remarks>
        public static void SetMessageSendPendingExceptionForThread(Exception? exception);

        /// <summary>
        /// Handler for unhandled Exceptions crossing the managed -> native boundary (that is, Reverse P/Invoke).
        /// </summary>
        /// <param name="exception">Unhandled exception.</param>
        /// <param name="lastMethod">Last managed method.</param>
        /// <param name="context">Context provided to the returned function pointer.</param>
        /// <returns>Exception propagation callback.</returns>
        /// <remarks>
        /// If the handler is able to propagate the managed Exception properly to the native environment an
        /// unmanaged callback can be returned, otherwise <c>null</c>. The RuntimeMethodHandle is to the
        /// last managed method that was executed prior to leaving the runtime. Along with the returned callback
        /// the handler can return a context that will be passed to the callback during dispatch.
        ///
        /// The returned handler will be passed the context when called and is the responsibility of the callback
        /// to managed. The handler must not return and is expected to propagate the exception into the native
        /// environment or fail fast.
        /// </remarks>
        public unsafe delegate delegate* unmanaged<IntPtr, void> UnhandledExceptionPropagationHandler(
            Exception exception,
            RuntimeMethodHandle lastMethod,
            out IntPtr context);

        /// <summary>
        /// Event for handling the propagation of unhandled Exceptions across a managed -> native boundary (that is, Reverse P/Invoke).
        /// </summary>
        /// <remarks>
        /// The first handler to return a non-null callback will be used to handle the Exception and no other
        /// handlers will be asked if they can propagate the exception.
        /// </remarks>
        public static event UnhandledExceptionPropagationHandler? UnhandledExceptionPropagation;
    }
}
```

# Example usage

Simple usage example is not available. A prototype consumption can be found in https://github.com/rolfbjarne/xamarin-macios/tree/dotnet-coreclr

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Implements approved API in https://github.com/dotnet/runtime/issues/44659#issuecomment-829495419.
Add support for `HNDTYPE_REFCOUNTED` GC handle type under specific `FEATURE_` defines.

Fixes https://github.com/dotnet/runtime/issues/44659

/cc @VSadov @Maoni0 @jkotas @jkoritzinsky @elinor-fung @rolfbjarne @lambdageek @davidwrighton @janvorli

### CODE REVIEW

File: src/coreclr/gc/objecthandle.cpp [hunk 1]
```diff
@@ -1065,7 +1065,9 @@ void Ref_TraceNormalRoots(uint32_t condemned, uint32_t maxgen, ScanContext* sc,
     // promote objects pointed to by variable handles whose dynamic type is VHT_STRONG
     TraceVariableHandles(PromoteObject, uintptr_t(sc), uintptr_t(fn), VHT_STRONG, condemned, maxgen, flags);
 
-#if defined(FEATURE_COMINTEROP) || defined(FEATURE_REDHAWK)
+    GCToEEInterface::RefCountedHandleCallbacksBefore();
```
Comment (VSadov) [inline src/coreclr/gc/objecthandle.cpp:1068]: This does not need to be called when `sc->concurrent == true`. Same applies to the "After" part.
When handles are scanned in the background (concurrently with managed threads), ref-counted handles are not scanned, so callbacks will be redundant.
See the condition at the line 1072.

Comment (VSadov) [reply src/coreclr/gc/objecthandle.cpp:1068]: What kind of code is runs in this Begin/After callback? Do we have an example?

Comment (AaronRobinsonMSFT) [reply src/coreclr/gc/objecthandle.cpp]: @VSadov Thanks for the clarity. I may have misunderstood @Maoni0 when this location was suggested, will let her clarify but I applied your suggestion and updated the naming on the interop side.

>What kind of code runs in this Begin/After callback? Do we have an example?

Sure. An example is in the test which isn't how the product will do this but the idea is to let the other system know when those handles are being examined and tracking that state.

```cpp
    std::atomic_bool state = { false };

     void STDMETHODCALLTYPE BeginEndCb()
    {
#ifdef REF_TRACKER_DEBUG_CALLBACKS
        ::printf("BeginEndCb: %s -> %s\n",
            state ? "true" : "false",
            !state ? "true" : "false");
#endif // REF_TRACKER_DEBUG_CALLBACKS

        state = !state;
    }
```

Comment (VSadov) [reply src/coreclr/gc/objecthandle.cpp]: My concern is that on server GC this will end up being called N times in parallel where N is the number of heaps, which is typically #proc. So the `BeginEnd` callback will see N begin calls and N end calls in some random order. It looks like your callback is not expecting such scenario.

It could get worse if the real callback takes locks as that would have serializing effect on GC - it will force the handle marking to happen serially, one heap after another.

I think these Begin/End calls should happen only once per GC (background or regular) -
-  one call before marking handles and one after in a regular (nonconcurrent) mark, and 
-  one call before marking handles and one after in a nonconcurrent mark phase of a background GC. 

In the second case the callbacks should happen when worker threads are joined, so that only one worker thread makes calls, not all of them. 
I think we have convenient locations in GC to put these callbacks, but you should check with @Maoni0 if that makes sense and where exactly the callbacks should be placed.

**Review by rolfbjarne — APPROVED** [review]

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -23683,6 +23683,7 @@ void gc_heap::mark_phase (int condemned_gen_number, BOOL mark_only_p)
         grow_mark_list_piece();
 #endif //USE_REGIONS
 
+        GCToEEInterface::BeforeGcScanRoots(max_generation, /* is_bgc */ false, /* is_concurrent */ false);
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:23686]: this should be `condemned_gen_number` instead of max_generation as we are not necessarily collecting max_generation

File: src/coreclr/vm/gcenv.ee.cpp [hunk 3]
```diff
@@ -49,6 +49,24 @@ VOID GCToEEInterface::SyncBlockCacheWeakPtrScan(HANDLESCANPROC scanProc, uintptr
...
+    CONTRACTL
+    {
+        NOTHROW;
+        GC_NOTRIGGER;
+    }
+    CONTRACTL_END;
+
+#ifdef VERIFY_HEAP
+    // Validate byrefs pinned by IL stubs since the last GC.
+    StubHelpers::ProcessByrefValidationList();
```
Comment (Maoni0) [inline src/coreclr/vm/gcenv.ee.cpp:63]: do you want to only call this when is_bgc is true? this is already called in GcStartWork which means for blocking GCs it would have just been called at the beginning of this GC.

**Review by Maoni0 — APPROVED** [review]
the rest LGTM!

File: src/coreclr/vm/gcenv.ee.cpp (hunk 3 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/gcenv.ee.cpp:63]: Doh. Good call. I will update this to be what it was.

File: src/coreclr/gc/gc.cpp (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/gc/gc.cpp:23686]: Boo. Thanks. I completely missed this.

**Review by janvorli — COMMENTED** [review]
The exception handling stuff looks good modulo the comment.

**Review by VSadov — APPROVED** [review]
PInvoke overriders and GC callbacks LGTM.

File: src/coreclr/vm/exceptionhandling.cpp [hunk 4]
```diff
@@ -4438,13 +4488,25 @@ VOID UnwindManagedExceptionPass2(PAL_SEHException& ex, CONTEXT* unwindStartConte
                 // We also need to reset the scanned stack range since the scanned frames will be
                 // obsolete after the unwind of the native frames completes.
                 ExceptionTracker* pTracker = GetThread()->GetExceptionState()->GetCurrentExceptionTracker();
-                pTracker->CleanupBeforeNativeFramesUnwind();
+                if (pTracker != NULL)
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/exceptionhandling.cpp:4491]: Still investigating this. So far, I've been able to confirm the `ExceptionTracker` instance is being NULL'd out during the last call to `ProcessCLRException` in `UnwindManagedExceptionPass2`.

**Review by dalexsoto — APPROVED** [review]

File: src/coreclr/vm/exceptionhandling.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/exceptionhandling.cpp:4491]: @janvorli I think this is actually okay. The `ExceptionTracker` instance is being cleaned up in `ProcessCLRException` because of the "invalid Reverse P/Invoke" logic at 

https://github.com/dotnet/runtime/blob/82c917aa6119c553c4fa093265c52f34476e7e13/src/coreclr/vm/exceptionhandling.cpp#L1229-L1235

I believe this is the cleanup we want. Should I assert something in this area?

[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/exceptionhandling.cpp:4494]: Added comment as to why this is okay.

**Comment by filipnavara** [comment]
Thanks! Happy to see this done! 🎉
