### PR TITLE
Don't fold relops with side effects that are used in jumps

### LINKED ISSUE #103888: JIT: Assertion failed 'block->bbPreorderNum == preorderNum' during 'Early Value Propagation'
```csharp
// Generated by Fuzzlyn v1.6 on 2024-06-23 16:50:17
// Run on X64 Windows
// Seed: 14337630088129483600
// Reduced from 13.5 KiB to 0.3 KiB in 00:01:04
// Hits JIT assert in Release:
// Assertion failed 'block->bbPreorderNum == preorderNum' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Early Value Propagation' (IL size 47; hash 0xade6b36b; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\fgdiagnostic.cpp Line: 4750
// 
using System.Runtime.CompilerServices;

public class C0
{
    public uint F0;
    public int F1;
}

public class Program
{
    public static void Main()
    {
        C0 vr0 = new C0();
        if (!((ulong)(0 << vr0.F1) <= vr0.F0))
        {
            vr0.F1 ^= vr0.F1;
        }
    }
}
```

Bisected to daf6cdcca892737ac4194605879295bb8cb46ce7, PTAL @tannergooding 

The problem most likely is that early prop invokes morph which ends up making flow graph changes at a point where that is disallowed.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #103888

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -14299,6 +14299,14 @@ GenTree* Compiler::gtFoldExprSpecial(GenTree* tree)
     // Here `op` is the non-constant operand, `cons` is the constant operand
     // and `val` is the constant value.
 
+    if (((op->gtFlags & GTF_SIDE_EFFECT) != 0) && ((tree->gtFlags & GTF_RELOP_JMP_USED) != 0) && tree->OperIsCompare())
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.cpp:14302]: Super nit, just to avoid checking for a flag while it may overlap a flag for some other node type...
```suggestion
    if (((op->gtFlags & GTF_SIDE_EFFECT) != 0) && tree->OperIsCompare() && ((tree->gtFlags & GTF_RELOP_JMP_USED) != 0))
```

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:14302]: I actually intentionally ordered it with `tree->OperIsCompare` last because the flag check is cheaper than the switch to check the oper kind, so it results in less code in the common case while still remaining correct.

Comment (jakobbotsch) [reply src/coreclr/jit/gentree.cpp:14302]: `OperIsCompare` is not a switch, it is a simple range check on the opers. I don't think we should be checking for oper-specific flags until we've verified those flags are valid for the oper we're dealing with. It introduces potential for mistakes during refactoring.

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp]: Fixed.

**Review by jakobbotsch — APPROVED** [review]
