### PR TITLE
Don't do an invalid mask conversion optimization for conditional select nodes

### LINKED ISSUE #118143: Data Corruption in System.Buffers.Text.Base64.EncodeToUtf8
We started observing intermittent CI failures on tests involving Base64 encoding in late June. This is recognized as a high-risk potential regression lurking in the .NET 10 release, and we need to find the root cause of this in time to resolve it before the .NET 10 RC1 release.

Here are the CI failures associated with this root cause:
1. #117163
2. #117169
3. #117614
4. #117665

Both #117163 and #117169 were reported on June 30, which is the earliest recognized signal of this issue. As was noted in [#117665](https://github.com/dotnet/runtime/issues/117665#issuecomment-3075130798):

> That seems... bad?
> 
> -f6 ba 82 83 26 0c 39 91 1b 8b 5d b1 8a 0f f3 6a 78 d5 59 a8 0d 64 29 3d d0 0c 35 87 56 00 ...
> +f4 0a 80 80 06 00 38 01 00 88 0d 80 88 0f c0 68 08 c0 58 08 00 64 09 00 d0 0c 00 84 06 00 ...
> It's like something is clearing every other 6 bits?
> 
> * F4BA XOR F40A is 02B0: 0b0000_0010_1011_0000
> * 8B5D XOR 880D is 0350: 0b0000_0011_0101_0000

> Since base64 is a 6-bit map... I wonder if this is a base64 encoding problem.

This is happening across multiple architectures and operating systems, as well as across different physical machines.
* [Machine a00DH2L running Windows-2016Server-10.0.14393-SP0](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-117716-merge-fee8dcbe800045c38e/Microsoft.Bcl.Memory.Tests/1/console.5f784235.log?helixlogtype=result)
* [Machine a009LPH running Linux-6.8.0-1030-azure-x86_64-with-glibc2.35](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-117937-merge-9fc25dcc6e8f472fb5/System.Security.Cryptography.OpenSsl.Tests/1/console.98216e88.log?helixlogtype=result)
* [Machine a009QWZ using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-helix-webassembly](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-117585-merge-2d36a55b1b944699b0/WasmTestOnChrome-ST-System.Memory.Tests/1/console.f55281a0.log?helixlogtype=result&skoid=8eda00af-b5ec-4be9-b69b-0919a2338892&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2025-07-28T21%3A19%3A21Z&ske=2025-07-28T22%3A19%3A21Z&sks=b&skv=2024-11-04&sv=2024-11-04&se=2025-07-28T22%3A19%3A21Z&sr=b&sp=rl&sig=1lIqz5i%2F8%2FwIojE%2BMzIpdP82gSLkmIUV9epL0PJ0xUM%3D)

@eiriktsarpalis conducted a preliminary investigation, reporting:

* The failing tests seem to all share a call to `System.Buffers.Text.Base64.EncodeToUtf8`, with that method producing corrupted data
* Some of the tests exercise the API through the `System.Convert` APIs, which only use the `Base64` class implementation if vectorization is available and applicable
   https://github.com/dotnet/runtime/blob/9df2042d2b2c7f68fa87c3ef1007e9a02cfab8a8/src/libraries/System.Private.CoreLib/src/System/Convert.cs#L2451-L2454
* The relevant implementation in [System/Buffers/Text/Base64Helper/Base64EncoderHelper.cs](https://github.com/dotnet/runtime/commits/main/src/libraries/System.Private.CoreLib/src/System/Buffers/Text/Base64Helper/Base64EncoderHelper.cs) hasn't been updated since October 2024

/cc @artl93 @jeffschwMSFT @marek-safar @lewing for visibility/awareness

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #118143 

This was exposed in, but not actually introduced by, #116983. The actual bug was introduced a bit over 10 months ago (still unique to .NET 10), as part of enabling the `mask conversion` optimization pass for xarch.

The general issue was that the transform was introducing invalid IR as it was creating a `ConditionalSelect(mask, simd, simd)` node when in actuality IR requires this to be: `ConditionalSelect(simd, simd, simd)`. Cases like `Sve.ConditionalSelect(mask, simd, simd)` and `BlendVariableMask(simd, simd, mask)` do exist. But they will already be in the right shape as the mask operand will either directly be taking a mask (no conversion necessary) or they  will have something like `CvtSimdToMask(simd)` for that argument position (which is handled by a different logical path in the mask conversion optimization phase).

The side effect of this invalid IR is that we would end up with an incorrect mask, which was logically being treated as `zero` when it should have been treated as a bitwise operation instead. This resulted in one path being dropped as dead code and us always returning `op2` of `ConditionalSelect(mask, op1, op2)`.

The intent of the handling was rather to look for cases that were logically `ConditionalSelect(MaskToSimd(mask), simd, simd)` and say "this could instead be `BlendVariableMask(simd, simd, mask)`, but that is a bit more involved and is largely irrelevant with #116983 as we're preferring importing things to be handled as masks natively where possible already, which would allow the normal `CvtSimdToMask(lcl)` and `CvtMaskToSimd(lcl)` handling to kick-in.

### CODE REVIEW

File: src/coreclr/jit/optimizemaskconversions.cpp [hunk 1]
```diff
@@ -175,37 +175,11 @@ class MaskConversionsCheckVisitor final : public GenTreeVisitor<MaskConversionsC
...
-                    {
-                        convertOp     = user->AsHWIntrinsic();
-                        hasConversion = true;
-                    }
-                    else if (hwintrin->OperIsVectorConditionalSelect())
-                    {
-                        // We don't actually have a convert here, but we do have a case where
-                        // the mask is being used in a ConditionalSelect and therefore can be
-                        // consumed directly as a mask. While the IR shows TYP_SIMD, it gets
-                        // handled in lowering as part of the general embedded-mask support.
```
Comment (tannergooding) [inline src/coreclr/jit/optimizemaskconversions.cpp:196]: This is what was "faulty" as `ConditionalSelect` is always a bitwise operation. The consideration is that we have a lowering optimization where if we know the selector (first operand) is a mask, we can sometimes optimize this to be a different instruction that is a little more efficient (such as `Sve.ConditionalSelect` or `Avx512.BlendVariableMask`)

What this *should* have been looking for was `VectorConditionalSelect(ConvertMaskToVector(op1), op2, op3)` and then rewritten it to `BlendVariableMask(op3, op2, op1)` (since we wanted to consume the mask directly and for other phases to be aware of this).

**Review by EgorBo — APPROVED** [review]
LGTM, do we need to backport this to any 10.0 preview branch?

**Comment by EgorBo** [comment]
Also, worth adding the original repro as a test case maybe?
