### PR TITLE
[QUIC] Fix test for debug/release version of a library

### LINKED ISSUE #93404: System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled fails
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=436041
Build error leg or test failing: System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled
Pull request: https://github.com/dotnet/runtime/pull/93384

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=436041
**Error message validated:** `System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled [FAIL]`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/12/2023 5:10:32 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[437401](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437401)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437401&view=ms.vss-test-web.build-test-results-tab&runId=9724782&resultId=194929)||
|[437368](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437368)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437368&view=ms.vss-test-web.build-test-results-tab&runId=9723818&resultId=204113)||
|[437377](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437377)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437377&view=ms.vss-test-web.build-test-results-tab&runId=9723756&resultId=194929)|dotnet/runtime#93407|
|[437331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437331)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437331&view=ms.vss-test-web.build-test-results-tab&runId=9722144&resultId=201674)|dotnet/runtime#93446|
|[437314](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437314)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437314&view=ms.vss-test-web.build-test-results-tab&runId=9721952&resultId=194929)|dotnet/runtime#93445|
|[437294](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437294)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437294&view=ms.vss-test-web.build-test-results-tab&runId=9721110&resultId=194929)|dotnet/runtime#93440|
|[437268](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437268)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437268&view=ms.vss-test-web.build-test-results-tab&runId=9720540&resultId=200755)|dotnet/runtime#93374|
|[437234](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437234)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437234&view=ms.vss-test-web.build-test-results-tab&runId=9719328&resultId=194929)|dotnet/runtime#93371|
|[437220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437220)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437220&view=ms.vss-test-web.build-test-results-tab&runId=9719014&resultId=194929)|dotnet/runtime#93437|
|[436887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436887)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436887&view=ms.vss-test-web.build-test-results-tab&runId=9719022&resultId=194929)|dotnet/runtime#93346|
|[437090](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437090)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437090&view=ms.vss-test-web.build-test-results-tab&runId=9717414&resultId=194929)|dotnet/runtime#93371|
|[437032](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437032)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437032&view=ms.vss-test-web.build-test-results-tab&runId=9716934&resultId=194929)|dotnet/runtime#93428|
|[436808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436808)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436808&view=ms.vss-test-web.build-test-results-tab&runId=9715524&resultId=200755)|dotnet/runtime#93417|
|[436694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436694)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436694&view=ms.vss-test-web.build-test-results-tab&runId=9714658&resultId=200755)|dotnet/runtime#93407|
|[436915](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436915)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436915&view=ms.vss-test-web.build-test-results-tab&runId=9713972&resultId=200757)|dotnet/runtime#93244|
|[436895](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436895)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436895&view=ms.vss-test-web.build-test-results-tab&runId=9713384&resultId=200755)|dotnet/runtime#93367|
|[436787](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436787)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436787&view=ms.vss-test-web.build-test-results-tab&runId=9710970&resultId=194929)|dotnet/runtime#90436|
|[436749](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436749)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436749&view=ms.vss-test-web.build-test-results-tab&runId=9709768&resultId=193847)|dotnet/runtime#93415|
|[436695](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436695)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436695&view=ms.vss-test-web.build-test-results-tab&runId=9708924&resultId=194929)|dotnet/runtime#93407|
|[436667](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436667)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436667&view=ms.vss-test-web.build-test-results-tab&runId=9707522&resultId=194929)|dotnet/runtime#93377|
|[436684](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436684)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436684&view=ms.vss-test-web.build-test-results-tab&runId=9708194&resultId=200755)|dotnet/runtime#93066|
|[436679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436679)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436679&view=ms.vss-test-web.build-test-results-tab&runId=9707508&resultId=194929)||
|[436089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436089)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436089&view=ms.vss-test-web.build-test-results-tab&runId=9707296&resultId=194929)|dotnet/runtime#93346|
|[436327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436327)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436327&view=ms.vss-test-web.build-test-results-tab&runId=9697674&resultId=200755)|dotnet/runtime#93367|
|[436041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436041)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436041&view=ms.vss-test-web.build-test-results-tab&runId=9692110&resultId=157194)|dotnet/runtime#93384|
|[435972](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435972)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435972&view=ms.vss-test-web.build-test-results-tab&runId=9690938&resultId=194929)|dotnet/runtime#93367|
|[436072](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436072)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436072&view=ms.vss-test-web.build-test-results-tab&runId=9690510&resultId=194929)|dotnet/runtime#90436|
|[436068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436068)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436068&view=ms.vss-test-web.build-test-results-tab&runId=9690308&resultId=194929)|dotnet/runtime#93345|
|[435859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435859)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicRemoteExecutorTests.SslKeyLogFile_IsCreatedAndFilled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=435859&view=ms.vss-test-web.build-test-results-tab&runId=9686040&resultId=200755)|dotnet/runtime#93280|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|29|29|29|

### PR DESCRIPTION
**Pull request by ManickaP**
The originally used preexisting platform detection is for runtime not libraries.

Fixes #93404

### CODE REVIEW

File: src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs [hunk 1]
```diff
@@ -103,6 +103,12 @@ public static bool IsPrivilegedProcess
         public static bool IsReleaseRuntime => s_isReleaseRuntime.Value;
         public static bool IsDebugRuntime => s_isDebugRuntime.Value;
 
+        private static readonly Lazy<bool> s_isReleaseLibraries = new Lazy<bool>(() => AssemblyConfigurationEquals("Release"));
+        private static readonly Lazy<bool> s_isDebugLibraries = new Lazy<bool>(() => AssemblyConfigurationEquals("Debug"));
```
Comment (akoeplinger) [inline src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs:107]: isn't this the same as s_isReleaseRuntime and s_isDebugRuntime ?

AssemblyConfigurationEquals checks typeof(string).Assembly so I think an easier solution would be to add an overload that takes the assembly.

Comment (ManickaP) [reply src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs:107]: Oh no, those are remnants, they shouldn't be here. The two bellow are important.

Comment (ManickaP) [reply src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs]: Removed.

Comment (akoeplinger) [reply src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs]: ok but why do you need to check DebuggableAttribute instead of adding an overload to the existing AssemblyConfigurationEquals?

Comment (ManickaP) [reply src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs]: As far as I can see in my tests, it returns the configuration of runtime, not the library and the attribute is not present for System.Net.Quic.dll:
```
Console.WriteLine(typeof(QuicConnection).Assembly.GetCustomAttribute<AssemblyConfigurationAttribute>() is null); // True
```

Comment (akoeplinger) [reply src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs]: ah I see, looks like we disable generating `AssemblyConfiguration` attributes for all libraries:
https://github.com/dotnet/runtime/blob/b9acf733a9cc77b02056a2a6d408b6197fb2fe18/eng/versioning.targets#L3-L4

**Review by akoeplinger — APPROVED** [review]

**Comment by ManickaP** [comment]
Failures are #92423

File: src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicRemoteExecutorTests.cs [hunk 2]
```diff
@@ -22,7 +22,7 @@ public MsQuicRemoteExecutorTests()
         [ConditionalFact(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported))]
         public void SslKeyLogFile_IsCreatedAndFilled()
         {
-            if (PlatformDetection.IsReleaseRuntime)
+            if (PlatformDetection.IsReleaseLibrary(typeof(QuicConnection).Assembly))
             {
                 throw new SkipTestException("Retrieving SSL secrets is not supported in Release mode.");
```
Comment (CarnaViire) [inline src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicRemoteExecutorTests.cs:27]: This is nitpicking, but since there's also 'checked' build possibility, I feel it might be better to check `!IsDebugLibrary` instead of `IsReleaseLibrary` (I see that implementation-wise this is the same, but it would make a bit more sense to me)


```suggestion
            if (!PlatformDetection.IsDebugLibrary(typeof(QuicConnection).Assembly))
            {
                throw new SkipTestException("Retrieving SSL secrets is supported only in Debug mode.");
```

Comment (CarnaViire) [reply src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicRemoteExecutorTests.cs:27]: Baah, I spent to much time looking at that 😂 you can disregard since this is merged already

Comment (ManickaP) [reply src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicRemoteExecutorTests.cs:27]: There's no "checked" version of library, that applies only to CLR.
