### PR TITLE
JIT: refine handle blocking logic

### LINKED ISSUE #1777: Checked / debug Crossgen2 fails building 8 framework assemblies due to a JIT assert
FYI @AndyAyersMS - I suspect this is related to

https://github.com/dotnet/runtime/pull/1593

that added the assert in question at

https://github.com/dotnet/runtime/blob/5182dadd4a5ea7e1d769322e845349088f06e9a2/src/coreclr/src/jit/codegencommon.cpp#L1379

We can see in the runtime-coreclr crossgen2 pipeline result history,

https://dev.azure.com/dnceng/public/_build?definitionId=674&_a=summary

that in the run before @GrabYourPitchforks' commit of the  GetArrayDataReference mop-up change (that broke System.Private.Corelib crossgenning) just a handful of tests failed:

https://dev.azure.com/dnceng/public/_build/results?buildId=475696&view=results

After Levi's commit, we started failing the SPC build in

https://dev.azure.com/dnceng/public/_build/results?buildId=478729&view=logs&j=6fdf90ec-154e-5293-972c-dfc4f172f2aa&t=871c2e7e-c1a2-56bc-b778-cc1c296911b3

In the latest runs, we're failing 7 assemblies:

  System.Net.WebHeaderCollection.dll
  System.Net.HttpListener.dll
  System.Text.Encodings.Web.dll
  System.Private.Uri.dll
  System.Text.RegularExpressions.dll
  System.Text.Json.dll
  System.Private.CoreLib.dll

[I have a fix for the SPC crossgen failure related to Levi's change but it seems to be also hitting the assert.]

/cc: @dotnet/crossgen-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Assertion prop uses `O2K_CONST_INT` for handles, even on 64 bit targets. Make
suitable adjustments to the handle propagation blocking logic.

Problem was introduced in #1593 and exposed by #1309.

Fixes #1777

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Review by trylek — APPROVED** [review]
LGTM, thanks for the lightning-fast turnaround!

**Review by janvorli — APPROVED** [review]

File: src/coreclr/src/jit/assertionprop.cpp [hunk 1]
```diff
@@ -2624,13 +2624,6 @@ GenTree* Compiler::optConstantAssertionProp(AssertionDsc*        curAssertion,
 
         case O2K_CONST_LONG:
 
-#ifdef _TARGET_64BIT_
-            // Don't propagate handles if we need to report relocs.
-            if (opts.compReloc && ((curAssertion->op2.u1.iconFlags & GTF_ICON_HDL_MASK) != 0))
-            {
-                return nullptr;
-            }
-#endif
```
Comment (briansull) [inline src/coreclr/src/jit/assertionprop.cpp]: You could add an assert here to insure that no change introduces a TYP_LONG witha reloc:

`assert((curAssertion->op2.u1.iconFlags & GTF_ICON_HDL_MASK) == 0);`

**Review by briansull — APPROVED** [review]
Looks Good, with one comment

File: src/coreclr/src/jit/assertionprop.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/src/jit/assertionprop.cpp]: How about adding this kind of check to `optDebugCheckAssertion`?

Comment (AndyAyersMS) [reply src/coreclr/src/jit/assertionprop.cpp]: Might make sense to merge this to unblock crossgen2 and add the assert in another PR.

Comment (briansull) [reply src/coreclr/src/jit/assertionprop.cpp]: I am fine with that
