### PR TITLE
Fix LoaderAllocator of DynamicMethodTable

### LINKED ISSUE #110987: Assert failure in SetLoaderAllocator() when calling a DynamicMethod with collectible AssemblyLoadContext
Using a checked runtime, the sample below fails with Assert in "_ASSERTE(pAllocator == GetLoaderAllocator())" in [MethodTable::SetLoaderAllocator](https://github.com/dotnet/runtime/blob/1da6bd7b5066a3768600b486245a6b48785a1bf8/src/coreclr/vm/methodtable.inl#L112).

```csharp
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Loader;

namespace ConsoleApp1
{
    public class Program
    {
        static void Main()
        {
            string tempFilePath = Path.GetTempFileName() + ".dll";

            // Create a simple type; this doesn't need to be run in the same process for the Assert to fail.
            {
                PersistedAssemblyBuilder ab = new PersistedAssemblyBuilder(new AssemblyName("MyAssembly"), typeof(object).Assembly);
                TypeBuilder typeBuilder = ab.DefineDynamicModule("MyModule").DefineType("MyType", TypeAttributes.Public | TypeAttributes.Class);
                MethodBuilder myMethod = typeBuilder.DefineMethod("MyMethod", MethodAttributes.Public | MethodAttributes.Static, CallingConventions.Standard);
                ILGenerator ilGenerator = myMethod.GetILGenerator();
                ilGenerator.Emit(OpCodes.Ret);
                typeBuilder.CreateType();
                ab.Save(tempFilePath);
            }

            {
                TestAssemblyLoadContext tlc = new TestAssemblyLoadContext();

                Type typeFromDisk = tlc.LoadFromAssemblyPath(tempFilePath).GetType("MyType")!;
                // This also fails with the Assert (instead of above):
                //Type typeFromDisk = Assembly.LoadFrom(tempFilePath).GetType("MyType")!;

                MethodInfo methodFromDisk = typeFromDisk.GetMethod("MyMethod")!;

                DynamicMethod callIt = new DynamicMethod(
                    "CallIt",
                    MethodAttributes.Public | MethodAttributes.Static,
                    CallingConventions.Standard,
                    returnType: typeof(void),
                    parameterTypes: null,
                    m: typeFromDisk.Module, // Using typeof(object).Module works
                    skipVisibility: true);

                ILGenerator il = callIt.GetILGenerator();
                il.Emit(OpCodes.Call, methodFromDisk);
                il.Emit(OpCodes.Ret);

                Action invoker = (Action)callIt.CreateDelegate(typeof(Action));
 
                // This fails Assert in checked runtime "_ASSERTE(pAllocator == GetLoaderAllocator())" in MethodTable::SetLoaderAllocator:
                invoker();

                Console.WriteLine("Success");
                Console.ReadLine();
            }
        }
    }

    class TestAssemblyLoadContext : AssemblyLoadContext
    {
        public TestAssemblyLoadContext() : base(isCollectible: true) // Using "isCollectible : false" works
        {
        }
    }
}

### PR DESCRIPTION
**Pull request by janvorli**
There is one `DynamicMethodTable` allocated per `Module` if needed. When its instance is being created, an incorrect `LoaderAllocator` is passed to the `CreateMinimalMethodTable` function. Instead of the `Module`'s `LoaderAllocator`, it passes in the default one.
That fires an assert in non-release builds of the runtime and it results in incorrect marking of the `MethodTable` as not collectible in case the `Module`'s LoaderAllocator is collectible.

This change fixes it by passing in the `LoaderAllocator` of the module instead.

Close #110987

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Do we need a regression test?

File: src/tests/Regressions/coreclr/GitHub_110987/test110987.cs [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+    public static void TestDynamicMethodALC()
+    {
+        string tempFilePath = Path.GetTempFileName() + ".dll";
+
+        // Create a simple type
+        PersistedAssemblyBuilder ab = new PersistedAssemblyBuilder(new AssemblyName("MyAssembly"), typeof(object).Assembly);
+        TypeBuilder typeBuilder = ab.DefineDynamicModule("MyModule").DefineType("MyType", TypeAttributes.Public | TypeAttributes.Class);
+        MethodBuilder myMethod = typeBuilder.DefineMethod("MyMethod", MethodAttributes.Public | MethodAttributes.Static, CallingConventions.Standard);
+        ILGenerator ilGenerator = myMethod.GetILGenerator();
+        ilGenerator.Emit(OpCodes.Ret);
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_110987/test110987.cs:29]:
```suggestion
```
Unnecessary

File: src/tests/Regressions/coreclr/GitHub_110987/test110987.cs [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    {
+    }
+}
+
+public class Test110987
+{
+    [Fact]
+    public static void TestDynamicMethodALC()
+    {
+        string tempFilePath = Path.GetTempFileName() + ".dll";
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_110987/test110987.cs:22]: If we need to save files to disk, we should make sure to clean up after the test.

Instead of saving the assembly to disk, you can save it to MemoryStream and load it from MemoryStream. It would avoid the problems with left-over temporary files and make the test more reliable (avoid interactions with antiviruses, etc.).

File: src/tests/Regressions/coreclr/GitHub_110987/test110987.cs [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+
+        // Create a simple type
+        PersistedAssemblyBuilder ab = new PersistedAssemblyBuilder(new AssemblyName("MyAssembly"), typeof(object).Assembly);
+        TypeBuilder typeBuilder = ab.DefineDynamicModule("MyModule").DefineType("MyType", TypeAttributes.Public | TypeAttributes.Class);
+        MethodBuilder myMethod = typeBuilder.DefineMethod("MyMethod", MethodAttributes.Public | MethodAttributes.Static, CallingConventions.Standard);
+        ILGenerator ilGenerator = myMethod.GetILGenerator();
+        ilGenerator.Emit(OpCodes.Ret);
+        typeBuilder.CreateType();
+        ab.Save(tempFilePath);
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_110987/test110987.cs:31]:
```suggestion

        MemoryStream ms = new MemoryStream()
        ab.Save(ms);
        
        ms.Position = 0;
```

File: src/tests/Regressions/coreclr/GitHub_110987/test110987.cs [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+
+        TestAssemblyLoadContext tlc = new TestAssemblyLoadContext();
+
+        Type typeFromDisk = tlc.LoadFromAssemblyPath(tempFilePath).GetType("MyType")!;
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_110987/test110987.cs:35]:
```suggestion
        Type typeFromDisk = tlc.LoadFromStream(ms).GetType("MyType")!;
```

**Comment by BruceForstall** [comment]
@janvorli Looks like the regression test is breaking test builds with

```
/__w/1/s/src/tests/Regressions/coreclr/GitHub_110987/test110987.cs(29,45): error CS1002: ; expected [/__w/1/s/src/tests/Regressions/coreclr/GitHub_110987/test110987.csproj] [/__w/1/s/src/tests/build.proj]
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=906353&view=logs&j=3725811e-4a8b-5f6a-b03b-a353ee894148&t=d59fccfb-2b13-5841-75bf-bfec705ee16a
