### PR TITLE
Fix handling of vector instruction sets in NativeAOT compiler

### LINKED ISSUE #68222: [NativeAOT] Benchmarks using Vector<T> seems to be slow
While working on the .NET 7 vs .NET 7 NativeAOT micro benchmarks perf study, I've stumbled upon multiple micro benchmarks being 10x slower with NativeAOT on x64, despite having all available Instruction Sets enabled (it applies to arm64 as well, but I had no chance to verify it with Instruction Sets enabled yet).

Most of them are using `Vector<T>`. `Vector.IsHardwareAccelerated` returns `true`.

Sample app that exhibits the problem:

```cs
using System;
using System.Linq;
using System.Numerics;
using System.Runtime.Intrinsics.X86;

namespace aotVector
{
    internal class Program
    {
        static char[] _array = Enumerable.Repeat('a', 512).ToArray();
        static char[] _same = Enumerable.Repeat('a', 512).ToArray();

        static void Main()
        {
            Console.WriteLine(Avx2.IsSupported); // True
            Console.WriteLine(Vector.IsHardwareAccelerated); // True
            Console.WriteLine(Vector<ushort>.Count); // 16

            var left = new System.Span<char>(_array);
            var right = new System.Span<char>(_same);
            int result = 0;

            for (long i = 0; i < 10_000_000; i++)
                result ^= left.SequenceCompareTo(right);
            
            Console.WriteLine(result);
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
     <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
    <IlcArg Include="--instructionset:base,sse,sse2,sse3,sse4.1,sse4.2,avx,avx2,aes,bmi,bmi2,fma,lzcnt,pclmul,popcnt" />
  </ItemGroup>
</Project>
```

Disassembly of [SpanHelpers.SequenceCompareTo](https://github.com/dotnet/runtime/blob/8883acfe2cb84f672b5ec18826410b83189943f5/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Char.cs#L359) for .NET 7:

image

Disassembly of the same method for .NET 7 NativeAOT:

image

cc @jkotas @MichalStrehovsky @EgorBo

### PR DESCRIPTION
**Pull request by jkotas**
The virtual vector instruction used internally by the JIT were leaking out and reported as unsupported

Fixes #68222

### CODE REVIEW

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -8830,7 +8830,7 @@ var_types Compiler::impImportCall(OPCODE                  opcode,
 
         // <NICE> Factor this into getCallInfo </NICE>
         bool isSpecialIntrinsic = false;
-        if ((mflags & (CORINFO_FLG_INTRINSIC | CORINFO_FLG_INTRINSIC)) != 0)
+        if ((mflags & CORINFO_FLG_INTRINSIC) != 0)
```
Comment (jkotas) [inline src/coreclr/jit/importer.cpp:8833]: Unrelated cleanup

File: src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets [hunk 2]
```diff
@@ -234,7 +234,7 @@ The .NET Foundation licenses this file to you under the MIT license.
       <IlcArg Condition="$(IlcInstructionSet) != ''" Include="--instructionset:$(IlcInstructionSet)" />
       <IlcArg Condition="$(IlcDisableReflection) == 'true'" Include="--disablereflection" />
       <IlcArg Condition="$(IlcDisableReflection) == 'true'" Include="--feature:System.Collections.Generic.DefaultComparers=false" />
-      <IlcArg Condition="$(IlcSingleThreaded) == 'true'" Include="--singlethreaded" />
+      <IlcArg Condition="$(IlcSingleThreaded) == 'true'" Include="--parallelism:1" />
```
Comment (jkotas) [inline src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets:237]: Unrelated cleanup - the argument name was changed in #63282

**Comment by jkotas** [comment]
cc @adamsitnik

File: src/coreclr/tools/aot/crossgen2/Program.cs [hunk 3]
```diff
@@ -229,13 +229,11 @@ private InstructionSetSupport ConfigureInstructionSetSupport()
             // Ready to run images are built with certain instruction set baselines
             if ((_targetArchitecture == TargetArchitecture.X86) || (_targetArchitecture == TargetArchitecture.X64))
             {
-                instructionSetSupportBuilder.AddSupportedInstructionSet("sse");
-                instructionSetSupportBuilder.AddSupportedInstructionSet("sse2");
+                instructionSetSupportBuilder.AddSupportedInstructionSet("sse2"); // Lower baselines included by implication
```
Comment (hez2010) [inline src/coreclr/tools/aot/crossgen2/Program.cs:232]: Can't we use AVX2 by default?

Comment (jkotas) [reply src/coreclr/tools/aot/crossgen2/Program.cs:232]: That is https://github.com/dotnet/designs/pull/173

**Comment by MichalStrehovsky** [comment]
Would it be possible to add a regression test for this to tests\nativeaot\SmokeTests\HardwareIntrinsics? The ISA handling is all quite confusing and that test is the only thing that gives me reasonable assurance it's all working in the end result.

**Comment by jkotas** [comment]
The test would have to have multiple versions of hardcoded asm code for a method that does `Vector<T>` operation, like comparing two vectors. Is it what you had in mind?

**Comment by MichalStrehovsky** [comment]
> The test would have to have multiple versions of hardcoded asm code for a method that does `Vector<T>` operation, like comparing two vectors. Is it what you had in mind?

Hm, maybe not worth it if that's the case. I was hoping there would be something else that is observable. Maybe perf testing will be a good enough regression test.

**Comment by jkotas** [comment]
Superpmi replay errors are known issue: https://github.com/dotnet/runtime/pull/68196#issuecomment-1103263507

**Comment by jkotas** [comment]
> I was hoping there would be something else that is observable

I do not see anything easily observable. 

In theory, the problem would be observable by `Vector128/256.IsHardwareAccelerated`. Unfortunately, the mapping of the vector ISA to physical ISA is done on the JIT side for these APIs: https://github.com/dotnet/runtime/blob/c49904522e3410350a7f27cbee18707b6171ed1d/src/coreclr/jit/hwintrinsic.cpp#L290-L304 .

**Review by adamsitnik — APPROVED** [review]
LGTM, big thanks for the fix @jkotas ! I can't wait to re-run the benchmarks and see fewer "regressions"!
