### PR TITLE
Fix a race condition in GCStress

### LINKED ISSUE #36681: Test failure: JIT\\Regression\\JitBlue\\GitHub_27924\\GitHub_27924\\GitHub_27924.cmd
failed in job: [runtime-coreclr jitstress 20200517.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=649313&view=ms.vss-test-web.build-test-results-tab&runId=20146270&resultId=108409&paneView=debug)

Error message
~~~
Assert failure(PID 5488 [0x00001570], Thread: 11524 [0x2d04]): _safePointDecoder.IsSafePoint(curOffs)

<no module>! <no symbol> + 0x0 (0x00000000)
 File: F:\workspace\_work\1\s\src\coreclr\src\vm\eetwain.cpp Line: 5044
 Image: D:\h\w\AAF5093E\p\CoreRun.exe


Return code: 1
Raw output file: D:\h\w\AAF5093E\w\B29D099C\e\JIT\Regression\Reports\JIT.Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\AAF5093E\p\corerun.exe" GitHub_27924.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\AAF5093E\p
> D:\h\w\AAF5093E\w\B29D099C\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.cmd
Expected: True
Actual: False


Stack trace
   at JIT_Regression._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm.Checked\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs:line 122360
~~~

category:correctness
theme:gc-stress
skill-level:expert
cost:large

### PR DESCRIPTION
**Pull request by BruceForstall**
Consider the case of a partially interruptible function where we've replaced
each call site with INTERRUPT_INSTR_CALL or INTERRUPT_INSTR_CALL_32. Even
though the call site itself isn't a safe point, we put a GCStress instruction
there so we can capture the call target at GC stress time, then set a specific
GCStress instruction for the next instruction that will indicate how to GC
protect any GC refs that are returned from the call.

Multiple threads can enter `DoGcStress` at the same time. They all get just
past the race check `if (!IsGcCoverageInterruptInstruction(instrPtr)) return;`.
One goes ahead, and reads the instruction code for the address at which we're
doing a GCStress. We set `atCall` to `true` if this matches one of our known
GCStress instructions for partially-interruptible call sites. Later, if
`atCall` is `true`, we write the original call instruction back to the code
stream, write the distinguished next instruction GCStress instruction, and
continue. If the other threads then read at the instruction address, they
might read the actual call opcode, not the distinguished GCStress breakpoint
instruction code. Then, they will set `atCall` to `false`. This will indicate
that we are in a fully-interruptible location, or that no special call-site
behavior is required. We go on, force a GC, and eventually get to the assert
in `EECodeManager::EnumGcRefs` that we are at a GC safe point.

The solution is to simply move the `if (!IsGcCoverageInterruptInstruction(instrPtr))`
check below the read of `*instrPtr` to set `atCall`.

Re-enable the GitHub_27924 test.

Fixes #36681

### CODE REVIEW

File: src/coreclr/src/vm/gccover.cpp [hunk 1]
```diff
@@ -744,23 +744,37 @@ void replaceSafePointInstructionWithGcStressInstr(UINT32 safePointOffset, LPVOID
...
     WORD instr = *((WORD*)savedInstrPtr - 1);
-
     instr = instr & 0xff87;
-    if((instr ^ 0x4780) == 0)
+    if ((instr ^ 0x4780) == 0)
+    {
         // It is call by register
         instructionIsACallThroughRegister = TRUE;
+    }
+    else
```
Comment (BruceForstall) [inline src/coreclr/src/vm/gccover.cpp:763]: The only code change here is putting the `instructionIsACallThroughImmediate` case as an `else` clause, if we didn't first see a `blx reg` instruction. The rest is just whitespace and semicolons.

File: src/coreclr/src/vm/gccover.cpp [hunk 2]
```diff
@@ -1446,6 +1463,17 @@ void DoGcStress (PCONTEXT regs, NativeCodeVersion nativeCodeVersion)
 
 #endif // _TARGET_*
 
+    if (!IsGcCoverageInterruptInstruction(instrPtr))
```
Comment (BruceForstall) [inline src/coreclr/src/vm/gccover.cpp:1466]: This is the real fix: moving this code here from above the `atCall` setting code.

**Review by AndyAyersMS — APPROVED** [review]
