### PR TITLE
[NativeAOT] Fix stack trace iteration over exceptions

### LINKED ISSUE #101364: [NativeAOT, win-x86] Bad EH info generated for nested trys
Hit with JIT\Regression\CLR-x86-JIT\V1-M10\b08944\b08944b test.

JitDump of the method with bad EH info:
[jitdump.zip](https://github.com/dotnet/runtime/files/15057772/jitdump.zip)

Notice:

```
2 EH table entries, 0 duplicate clauses, 0 cloned finallys, 2 total EH entries reported to VM
setEHcount(cEH=2)
EH#0: try [0029..0032) handled by [008D..00B2) (class: 1000014)
EH#1: try [0028..0034) handled by [00B2..016D) (class: 1000014)
```

The 29..32 try block looks okay, but the 28..34 is too short and doesn't cover the handler that got moved out-of-line.

Wondered if it's related to a `// TODO: Is this really UNIX_X86_ABI specific? Should we guard with compiler->UsesFunclets() instead?` comment but that didn't seem to fix it.

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #101364

The test `b08944b` on x86 in Release causes the `bomb()` method to be inlined. The stack trace iterator then incorrectly adjusts the pointer to the faulting instruction by `-1` which causes the `try` block not to be matched.

On x64 the inlined generated code for the `bomb()` method ended up being
```
00007ff7`3ecda705 33c9           xor     ecx, ecx
00007ff7`3ecda707 833900         cmp     dword ptr [rcx], 0
```

On x86 it is
```
004478ef 833d0000000000     cmp     dword ptr ds:[0], 0
```

Hence, for x64 the previous instruction to the faulting instruction was still in the `try` region. On x86 that's not the case.

### CODE REVIEW

**Comment by filipnavara** [comment]
Alternatively I can change to code to remove the `ApplyReturnAddressAdjustment` flag in the code path that sets `ExCollide`. Let's wait for the CI to see what breaks...

**Comment by filipnavara** [comment]
Hmm, the test failures do look suspicious. I'll check it in detail when all the pipelines finish running.

**Comment by filipnavara** [comment]
There are 6 test failures:
- 3x `JIT\Regression\JitBlue\Runtime_105821\Runtime_105821\Runtime_105821` which was meanwhile fixed by #105889
- AV in `System.Formats.Asn1.Tests` on linux-arm
- `SIGKILL` in `System.IO.Tests` on linux-x64
- Timeout in `System.Threading.Channels.Tests` on linux-arm64

The AV in `System.Formats.Asn1.Tests` has interesting stack trace:
```
Running assembly:System.Formats.Asn1.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Process terminated. Access Violation: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. The application will be terminated since this platform does not support throwing an AccessViolationException.
   at System.RuntimeExceptionHelpers.FailFast(String, Exception, String, RhFailFastReason, IntPtr, IntPtr) + 0x1fd
   at System.RuntimeExceptionHelpers.GetRuntimeException(ExceptionIDs) + 0x167
   at System.Runtime.EH.GetClasslibException(ExceptionIDs, IntPtr) + 0x3d
   at System.Runtime.EH.RhThrowHwEx(UInt32, EH.ExInfo&) + 0x69
   at Test.Cryptography.ByteUtils.ByteArrayToHex(ReadOnlySpan`1 bytes) + 0x5d
   at System.Formats.Asn1.Tests.Writer.WriteNamedBitList.VerifyWriteNamedBitList_KeyUsage_OneByte(AsnEncodingRules ruleSet) + 0x10d
   at System.Formats.Asn1!<BaseAddress>+0x96a10a
```

There's nothing in `ByteArrayToHex` that would obviously cause an AV exception, so it looks like something was collected by GC that shouldn't have been. That could possibly be triggered by a change in the stack walking logic but there's no exception on the given code path so I don't see how the change in this PR could have effect in this specific instance.

File: src/coreclr/nativeaot/Runtime/StackFrameIterator.cpp [hunk 1]
```diff
@@ -1830,7 +1825,10 @@ void StackFrameIterator::PrepareToYieldFrame()
     ASSERT(m_pInstance->IsManaged(m_ControlPC) ||
          ((m_dwFlags & SkipNativeFrames) == 0 && (m_dwFlags & UnwoundReversePInvoke) != 0));
 
-    if (m_dwFlags & ApplyReturnAddressAdjustment)
+    // Do not adjust the PC if ExCollide is set since in that case it's set to the
+    // beginning of the instruction from ExInfo and adjusting it would cause to move
+    // to the previous instruction.
```
Comment (filipnavara) [inline src/coreclr/nativeaot/Runtime/StackFrameIterator.cpp:1830]:
```suggestion
    // Do not adjust the PC if ExCollide is set. In that case it was either copied from
    // existing stack frame iterator that was already adjusted, or it's set to the
    // beginning of the faulting instruction from ExInfo and adjusting it would cause
    // us to move to the previous instruction which may no longer be in the same try
    // block.
```

**Review by jkotas — APPROVED** [review]
LGTM. @janvorli @VSadov Could you please review this one as well?

**Comment by JulieLeeMSFT** [comment]
> LGTM. @janvorli @VSadov Could you please review this one as well?

Ping @janvorli @VSadov for code review.
cc @dotnet/jit-contrib

File: src/coreclr/nativeaot/Runtime/StackFrameIterator.cpp [hunk 2]
```diff
@@ -1830,7 +1825,12 @@ void StackFrameIterator::PrepareToYieldFrame()
     ASSERT(m_pInstance->IsManaged(m_ControlPC) ||
          ((m_dwFlags & SkipNativeFrames) == 0 && (m_dwFlags & UnwoundReversePInvoke) != 0));
 
-    if (m_dwFlags & ApplyReturnAddressAdjustment)
+    // Do not adjust the PC if ExCollide is set. In that case it was either copied from
```
Comment (janvorli) [inline src/coreclr/nativeaot/Runtime/StackFrameIterator.cpp:1828]: I would suggest slight simplification of the comment here:

```C++
// Do not adjust the PC if ExCollide is set. In that case the m_ControlPC was copied from
// another stack frame iterator and it already has a correct value.
```

**Review by janvorli — APPROVED** [review]
LGTM modulo a nit regarding the comment.
