### PR TITLE
[browser] app start benchmark fix, loadBootResource fix

### LINKED ISSUE #89883: [browser] loadBootResource should not ask for `dotnetwasm` location before cache lookup
Because 

https://github.com/dotnet/aspnetcore/blob/22b8ebb68bf74371b038841ea461d74da03182b9/src/Components/WebAssembly/testassets/HostedInAspNet.Client/wwwroot/index.html#L21

will force real fetch.

That breaks  caching tests in BootResourceCachingTest
https://github.com/dotnet/aspnetcore/blob/22b8ebb68bf74371b038841ea461d74da03182b9/src/Components/test/E2ETest/Tests/BootResourceCachingTest.cs#L18

### PR DESCRIPTION
**Pull request by pavelsavara**
As we introduced cache also for non-blazor template, we also adopted it's resources cache and `no-cache` hint for `fetch`.
Because our SimpleServer which we use for benchmark doesn't use ETag header, it leads to full download.

- stop using `loadBootResource` too early
   - Fixes https://github.com/dotnet/runtime/issues/89883
- implement `ETag` HTTP header for `SimpleServer` and benchmark
- introduce `disableNoCacheFetch` and `disableIntegrityCheck` config flags
- use `noCache` and `useCredentials` flags on asset just for appsettings configuration, not all VFS
- delay cache cleanup 10 seconds later
- delay adding new cache items to timer loop
- replace `ResourceRequest` usage with `AssetEntryInternal`
- remove `ResourceRequest` type
- fixes prefetch on samples and bench
- apply unique query also to `js-module-library-initializer` and `manifest`
- start downloading non-script assets earlier
- minor `importLibraryInitializers` refactoring

### CODE REVIEW

File: src/mono/sample/wasm/simple-server/Program.cs [hunk 1]
```diff
@@ -16,11 +17,22 @@ public sealed class Session
...
+    public sealed class FileContent
+    {
+        public FileContent(byte[] buffer, string hash)
+        {
+            this.buffer = buffer;
+            this.hash = hash;
+        }        
+        public byte[] buffer;
+        public string hash;
+    }
```
Comment (radical) [inline src/mono/sample/wasm/simple-server/Program.cs:29]:
```suggestion
public sealed record FileContent(byte[] buffer, string hash);
```

File: src/mono/sample/wasm/simple-server/Program.cs [hunk 2]
```diff
@@ -16,11 +17,22 @@ public sealed class Session
...
+
     public sealed class Program
     {
         private bool Verbose = false;
         private ConcurrentDictionary<string, Session> Sessions = new ConcurrentDictionary<string, Session>();
-        private Dictionary<string, byte[]> cache = new Dictionary<string, byte[]>(StringComparer.OrdinalIgnoreCase);
+        private Dictionary<string, FileContent> cache = new Dictionary<string, FileContent>(StringComparer.OrdinalIgnoreCase);
```
Comment (radical) [inline src/mono/sample/wasm/simple-server/Program.cs:35]:
```suggestion
        private Dictionary<string, FileContent> cache = new(StringComparer.OrdinalIgnoreCase);
```

File: src/mono/sample/wasm/simple-server/Program.cs [hunk 3]
```diff
@@ -16,11 +17,13 @@ public sealed class Session
         public int Finished { get; set; } = 0;
     }
 
+public sealed record FileContent(byte[] buffer, string hash);
```
Comment (kg) [inline src/mono/sample/wasm/simple-server/Program.cs:20]: Is the indentation right? It looks wrong

File: src/mono/sample/wasm/simple-server/Program.cs [hunk 4]
```diff
@@ -279,25 +286,36 @@ private async void ServeAsync(HttpListenerContext context)
                 if (contentType != null)
                     context.Response.ContentType = contentType;
 
-                context.Response.ContentLength64 = buffer.Length;
-                context.Response.AppendHeader("cache-control", "public, max-age=31536000");
+                // context.Response.AppendHeader("cache-control", "public, max-age=31536000");
                 context.Response.AppendHeader("Cross-Origin-Embedder-Policy", "require-corp");
                 context.Response.AppendHeader("Cross-Origin-Opener-Policy", "same-origin");
+                context.Response.AppendHeader("Etag", fc.hash);
```
Comment (kg) [inline src/mono/sample/wasm/simple-server/Program.cs:292]: It's `ETag` and some http implementations are case sensitive, though not all

File: src/mono/wasm/runtime/dotnet.d.ts [hunk 5]
```diff
@@ -129,6 +129,14 @@ type MonoConfig = {
      * Gets a value that determines whether to enable caching of the 'resources' inside a CacheStorage instance within the browser.
      */
     cacheBootResources?: boolean;
+    /**
+     * Configures use of the hash for integrity checks while fetching assets
+     */
+    disableIntegrityCheck?: boolean;
+    /**
+     * Configures use of the hash for integrity checks while fetching assets
```
Comment (kg) [inline src/mono/wasm/runtime/dotnet.d.ts:137]: This comment seems wrong

File: src/mono/wasm/runtime/loader/assets.ts [hunk 6]
```diff
@@ -67,58 +89,70 @@ export function shouldLoadIcuAsset(asset: AssetEntryInternal): boolean {
     return !(asset.behavior == "icu" && asset.name != loaderHelpers.preferredIcuAsset);
 }
 
-function getSingleAssetWithResolvedUrl(resources: ResourceList | undefined, behavior: SingleAssetBehaviors): AssetEntry {
-    const keys = Object.keys(resources || {});
+function convertSingleAsset(modulesAssets: AssetEntryInternal[], resource: ResourceList | undefined, behavior: SingleAssetBehaviors): AssetEntryInternal {
```
Comment (kg) [inline src/mono/wasm/runtime/loader/assets.ts:92]: Is it right that 'resources: ResourceList' (plural, a list) is now 'resource' (singular, still a list?)

File: src/mono/wasm/runtime/loader/assets.ts [hunk 7]
```diff
@@ -314,21 +374,44 @@ function prepareAssets(containedInSnapshotAssets: AssetEntryInternal[], alwaysLo
...
-    config.assets = [...containedInSnapshotAssets, ...alwaysLoadedAssets];
+    config.assets = [...containedInSnapshotAssets, ...alwaysLoadedAssets, ...modulesAssets];
+}
+
+export function prepareAssetsWorker() {
+    const config = loaderHelpers.config;
+    mono_assert(config.assets, "config.assets must be defined");
+
+    for (const asset of config.assets) {
+        switch (asset.behavior) {
```
Comment (kg) [inline src/mono/wasm/runtime/loader/assets.ts:403]: Could you unify this with the switch from prepareAssets, in a single helper function they both use?

File: src/mono/wasm/runtime/loader/assetsCache.ts [hunk 8]
```diff
@@ -90,43 +90,45 @@ export async function findCachedResponse(request: ResourceRequest): Promise<Resp
...
     const cache = cacheIfUsed;
-    if (!cache || cacheSkipAssetBehaviors.includes(request.behavior) || !request.hash || request.hash.length === 0) {
+    if (!cache || asset.noCache || !asset.hash || asset.hash.length === 0) {
         return;
     }
-
-    const cacheKey = getCacheKey(request);
-    addToCacheAsync(cache, request.name, cacheKey, networkResponse); // Don't await - add to cache in background
+    const clonedResponse = networkResponse.clone();
+    setTimeout(() => {
```
Comment (kg) [inline src/mono/wasm/runtime/loader/assetsCache.ts:103]: Can we add a comment explaining why this needs to be in a setTimeout?

File: src/mono/wasm/runtime/loader/libraryInitializers.ts [hunk 9]
```diff
@@ -30,6 +18,7 @@ async function fetchLibraryInitializers(config: MonoConfig, type: LibraryInitial
     async function importInitializer(path: string): Promise<void> {
         try {
             const adjustedPath = appendUniqueQuery(loaderHelpers.locateFile(path), "js-module-library-initializer");
+            mono_log_debug(`Attempting to import '${adjustedPath}' for ${path}`);
```
Comment (kg) [inline src/mono/wasm/runtime/loader/libraryInitializers.ts:21]: Intended to keep this log message?

**Review by kg — APPROVED** [review]

File: src/mono/wasm/runtime/loader/assets.ts (hunk 6 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/loader/assets.ts:92]: The `ResourceList` name is not great. It's actually json dictionary, string key, string value. The key is file name and value is optional hash. And it's used as list of files, so the name makes some sense. 

Some asset types/behaviors have just one possible file. So this is a special case of `ResourceList` which has just one key/file in it.

File: src/mono/wasm/runtime/loader/assetsCache.ts (hunk 8 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/loader/assetsCache.ts:103]: It doesn't "need to" I'm just postponing the CPU/caching/allocation hit till later time, so that we could load it into the wasm memory as soon as possible. Will add comment.

File: src/mono/wasm/runtime/loader/libraryInitializers.ts (hunk 9 above)
Comment (pavelsavara) [reply src/mono/wasm/runtime/loader/libraryInitializers.ts:21]: yes, this is debug level and it will write only when `diagnosticTracing` is set.
