### PR TITLE
JIT: handle commas during inline return value substitution

### LINKED ISSUE #119058: JIT: Assertion failed 'cond == test->AsOp()->gtOp1' during 'Update flow graph early pass'
```csharp
// Generated by Fuzzlyn v3.3 on 2025-08-23 16:26:13
// Run on Arm64 MacOS
// Seed: 17015990397549431234-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256
// Reduced from 36.5 KiB to 0.5 KiB in 00:00:13
// Hits JIT assert for Release:
// Assertion failed 'cond == test->AsOp()->gtOp1' in 'Program:M0()' during 'Update flow graph early pass' (IL size 32; hash 0xaf50ff37; FullOpts)
// 
//     File: /Users/runner/work/1/s/src/coreclr/jit/fgopt.cpp Line: 4535
// 
public class Program
{
    public static uint s_3;
    public static ulong s_7;
    public static void Main()
    {
        M0();
    }

    public static void M0()
    {
        long[] var3 = default(long[]);
        sbyte var24 = default(sbyte);
        if ((ulong)M1() > (ulong)var3[0])
        {
            var24 = var24;
        }
        else
        {
            uint var25 = s_3;
        }

        ulong var39 = s_7;
    }

    public static int M1()
    {
        return default(int);
    }
}
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Fixes #119058.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib PTAL

File: src/tests/JIT/Regression/JitBlue/Runtime_119508/Runtime_119508.cs [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+// Generated by Fuzzlyn v3.3 on 2025-08-23 16:26:13
+// Run on Arm64 MacOS
+// Seed: 17015990397549431234-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256
+// Reduced from 36.5 KiB to 0.5 KiB in 00:00:13
+// Hits JIT assert for Release:
+// Assertion failed 'cond == test->AsOp()->gtOp1' in 'Program:M0()' during 'Update flow graph early pass' (IL size 32; hash 0xaf50ff37; FullOpts)
+// 
+//     File: /Users/runner/work/1/s/src/coreclr/jit/fgopt.cpp Line: 4535
+// 
+public class Runtime_119508
```
Comment (tannergooding) [inline src/tests/JIT/Regression/JitBlue/Runtime_119508/Runtime_119508.cs]: nit: Looks like this should be `119058`

File: src/coreclr/jit/fginline.cpp [hunk 2]
```diff
@@ -735,6 +735,27 @@ class SubstitutePlaceholdersAndDevirtualizeWalker : public GenTreeVisitor<Substi
             GenTree*    condTree = tree->AsOp()->gtOp1;
             assert(tree == block->lastStmt()->GetRootNode());
 
+            if (condTree->OperIs(GT_COMMA))
```
Comment (tannergooding) [inline src/coreclr/jit/fginline.cpp]: Is there any chance we need to handle `COMMA(COMMA(..., op2))` or the like? I know a few places we have comma handling, we end up having to loop through until the last comma.

File: src/tests/JIT/Regression/JitBlue/Runtime_119508/Runtime_119508.cs (hunk 1 above)
Comment (AndyAyersMS) [reply src/tests/JIT/Regression/JitBlue/Runtime_119508/Runtime_119508.cs]: Yep, let me fix.

File: src/coreclr/jit/fginline.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/fginline.cpp]: I suppose it's possible. We generally use `gtEffectiveVal` to descend through them all.

**Comment by AndyAyersMS** [comment]
Also we don't really need to extra all side effects, just tunnel down through until we find a compare or constant. Maybe I should rework this as a split.

File: src/coreclr/jit/fginline.cpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/jit/fginline.cpp]: I presume you can simply change your `if` into `while` if you want to handle nested COMMAs (well, and update condTree variable inside the loop)

**Review by EgorBo — APPROVED** [review]

File: src/tests/JIT/Regression/JitBlue/Runtime_119508/Runtime_119508.cs (hunk 1 above)
Comment (AndyAyersMS) [reply src/tests/JIT/Regression/JitBlue/Runtime_119508/Runtime_119508.cs]: Fixed.

File: src/coreclr/jit/fginline.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/fginline.cpp]: Yep, fixed.

**Comment by AndyAyersMS** [comment]
@egorbo updated; can you take one more look?

**Comment by AndyAyersMS** [comment]
@egorbo ping

**Review by EgorBo — APPROVED** [review]
