### PR TITLE
Fix x86 EH for UnmanagedCallersOnly methods

### LINKED ISSUE #57915: [JitStressWithRandomNumbers] UnmanagedCallersOnlyTest fails.
Example:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57900-merge-a85ae37fa53e48b5ba/Interop/1/console.dc3b4346.log?sv=2019-07-07&se=2021-09-12T00%3A17%3A58Z&sr=c&sp=rl&sig=Fmv2Y4%2BRpAP8bSulCAB8K9aOy29%2BoxOtgzZYwPLR%2FnA%3D

Repro steps (x86 windows):
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=71
Interop\UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.cmd
```

Failure log:
```
      Assert failure(PID 3060 [0x00000bf4], Thread: 10212 [0x27e4]): GetThreadNULLOk() == NULL || GetThread()->GetFrame() == (Frame*)-1 || GetThread()->GetFrame() <= pFrame
```
the issue from a quality week JitStress experiment.

### PR DESCRIPTION
**Pull request by janvorli**
There is a bug in the exception handling on x86 when exception is
propagated from a method marked with UnmanagedCallersOnly attribute to
an immediate caller that's also managed (and calls the method via a
native delegate). In this case, there is no native frame in between and
the stack walker accidentally skips the InlinedCallFrame processing
during first pass of exception handling. The InlinedCallFrame is expected
to be processed before the related PInvoke IL stub and it doesn't happen
in this case, as a native frame is required to make the stack frame iterator
move to the explicit InlinedCallFrame. The fact that it is not processed
results in ignoring the upper limit on the stack walk and walking the stack
further than expected.

This change fixes it by detecting the direct transition from
UnmanagedCallersOnly to managed caller and forces the stack frame
iterator to process the InlinedCallFrame.

Fixes #57915

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @AaronRobinsonMSFT

File: src/coreclr/vm/methodtablebuilder.cpp [hunk 1]
```diff
@@ -6156,6 +6156,27 @@ MethodTableBuilder::InitMethodDesc(
 #endif // !_DEBUG
         pNewMD->SetSynchronized();
 
+    HRESULT hr = pNewMD->GetCustomAttribute(
```
Comment (jkotas) [inline src/coreclr/vm/methodtablebuilder.cpp:6159]: This is non-pay for play. We have intentionally avoided the eager lookup of the attribute in the type loader and burning a bit on MethodDesc for it.

File: src/coreclr/vm/ilstubcache.cpp [hunk 2]
```diff
@@ -273,6 +273,7 @@ MethodDesc* ILStubCache::CreateNewMethodDesc(LoaderHeap* pCreationHeap, MethodTa
         if (SF_IsReverseStub(dwStubFlags))
         {
             pMD->m_dwExtendedFlags |= DynamicMethodDesc::nomdReverseStub | DynamicMethodDesc::nomdUnmanagedCallersOnlyStub;
+            pMD->SetUnmanagedCallersOnly();
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/ilstubcache.cpp:276]: We already have this marked above:

```cpp
| DynamicMethodDesc::nomdUnmanagedCallersOnlyStub;
```

File: src/coreclr/vm/methodtablebuilder.cpp (hunk 1 above)
Comment (janvorli) [reply src/coreclr/vm/methodtablebuilder.cpp:6159]: Makes sense, I am testing a new version done that way.

File: src/coreclr/vm/stackwalk.cpp [hunk 3]
```diff
@@ -3135,6 +3137,12 @@ void StackFrameIterator::PostProcessingForManagedFrames(void)
     m_exInfoWalk.WalkToPosition(GetRegdisplaySP(m_crawl.pRD), (m_flags & POPFRAMES));
 #endif // ELIMINATE_FEF
 
+#ifdef TARGET_X86
+    hdrInfo gcHdrInfo;
+    DecodeGCHdrInfo(m_crawl.codeInfo.GetGCInfoToken(), 0, &gcHdrInfo);
```
Comment (jkotas) [inline src/coreclr/vm/stackwalk.cpp:3142]: All other places that decode GCInfo in this file go through `m_crawl.GetCodeManager()`. Is it worth following the pattern?

**Review by jkotas — APPROVED** [review]
LGTM

File: src/coreclr/vm/stackwalk.cpp (hunk 3 above)
Comment (janvorli) [reply src/coreclr/vm/stackwalk.cpp:3142]: Good idea, but let me do that as a separate cleanup so that this change is just a fix for the bug. I will need to add a new method to the EECodeManager and then I'd use it in the exceptionhandling.cpp too where we currently also have this raw decoding.

**Review by AaronRobinsonMSFT — APPROVED** [review]
