### PR TITLE
Fix a Race in Installer Test Infrastructure

### LINKED ISSUE #33675: Bundle_extraction_is_reused failed in CI
See https://github.com/dotnet/runtime/pull/33563#issuecomment-599901920

Build failure https://dev.azure.com/dnceng/public/_build/results?buildId=561783&view=ms.vss-test-web.build-test-results-tab&runId=17679122&resultId=100000&paneView=debug

Platform: linux-x64

Error:
```
System.ComponentModel.Win32Exception : Text file busy


Stack trace
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Build.Framework.Command.Start() in /_/src/installer/test/TestUtils/Command.cs:line 200
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute(Boolean fExpectedToFail) in /_/src/installer/test/TestUtils/Command.cs:line 240
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute() in /_/src/installer/test/TestUtils/Command.cs:line 172
   at AppHost.Bundle.Tests.BundleExtractToSpecificPath.Bundle_extraction_is_reused() in /_/src/installer/test/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleExtractToSpecificPath.cs:line 87
```

/cc @swaroop-sridhar

### LINKED ISSUE #38013: Enable Apphost.Bundle.Test Bundle_can_be_renamed()
This test is failing non-deterministically in the lab, and is therefore disabled temporarily.
The likely problem is that the TestFixture is shared across runs in a `[Theory]`.
This issue tracks re-enabling the test.

### PR DESCRIPTION
**Pull request by swaroop-sridhar**
This PR contains the following changes: 

* Add locking around GetNewTestArtifactPath() so that multiple threads attempting to create new copies of a TextFixture don't collide and work on the same path (fixes failures such as #35068).
* Re-enable Apphost.Bundle.Tests.BundleRename test (fixes #38013)
* StaticHostTest used the StaticHostApp (which is effectively a copy of StandaloneApp) as a work-around for synchronization problems. Remove this work-around.

Fixes #33675
Fixes #38013

### CODE REVIEW

**Comment by swaroop-sridhar** [comment]
CC: @safern  @ViktorHofer  @VSadov

File: src/installer/tests/TestUtils/TestArtifact.cs [hunk 1]
```diff
@@ -67,25 +69,26 @@ public virtual void Dispose()
             _copies.Clear();
         }
 
+        private static readonly object pathCountLock = new object();
```
Comment (vitek-karas) [inline src/installer/tests/TestUtils/TestArtifact.cs:72]:
```suggestion
        private static readonly object _pathCountLock = new object();
```

**Review by vitek-karas — APPROVED** [review]
