### PR TITLE
[wasi] Combine `main` function for the default and single file bundle

### LINKED ISSUE #85616: [wasi] Invariant.Tests failing to run - regression
```
[20:18:51] info: Using wasm engine WasmTime from path /root/helix/work/correlation/wasmtime/wasmtime
[20:18:51] info: wasmtime-cli 5.0.0
[20:18:51] info: 
[20:18:51] info: Running /root/helix/work/correlation/wasmtime/wasmtime --dir=. --env=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true dotnet.wasm WasmTestRunner managed/Invariant.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[20:18:52] info: Process wasmtime exited with 1
[20:18:52] info: Waiting to flush log messages with a timeout of 120 secs ..
[20:18:52] info: 
[20:18:52] info: Unhandled Exception:
[20:18:52] info: System.ArgumentException: Invalid argument 'managed/Invariant.Tests.dll'.
[20:18:52] info:    at SimpleWasmTestRunner.Main(String[] args)
[20:18:52] info:    at SimpleWasmTestRunner.<Main>(String[] args)
[20:18:52] fail: Application has finished with exit code 1 but 0 was expected
```

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by radical**
.. case.

This was prompted by https://github.com/dotnet/runtime/issues/85616 where running `Invariant.Tests` breaks with:

```
Running /root/helix/work/correlation/wasmtime/wasmtime --dir=. --env=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true dotnet.wasm WasmTestRunner managed/Invariant.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing

Unhandled Exception:
System.ArgumentException: Invalid argument 'managed/Invariant.Tests.dll'.
   at SimpleWasmTestRunner.Main(String[] args)
   at SimpleWasmTestRunner.<Main>(String[] args)
```

- This broke because of a recent change due to which setting `InvariantGlobalization=true` meant `WasmBuildNative=true`
- But this did not trigger single file bundle
- And the build ended up relinking a dotnet.wasm but using the single-file bundle `main` function.
- The default, and single-file bundle `main` functions expect different set of command line arguments, and the mismatch causes the failure

Instead, we combine the two main functions and switch between the behavior depending on compile time defines.

Fixes https://github.com/dotnet/runtime/issues/85616

### CODE REVIEW

File: src/mono/wasi/runtime/main.c [hunk 1]
```diff
@@ -21,8 +21,38 @@ int main(int argc, char * argv[]) {
...
+	 * arg0: MainAssembly
+	 * arg1-..: args
+	 */
 	const char* assembly_name = dotnet_wasi_getentrypointassemblyname();
 	MonoAssembly* assembly = mono_assembly_open(assembly_name, NULL);
+#else
+	/*
+	 * For default case which uses dotnet.wasm, running with wasmtime:
+	 *
+	 *  $ wasmtime run --dir . dotnet.wasm MainAssembly [args]
```
Comment (maraf) [inline src/mono/wasi/runtime/main.c:40]: Shouldn't we have a unified way to run the application? For example, could we rename the `dotnet.wasm` to `MainAssembly.wasm` even for non-single file bundle?

Comment (pavelsavara) [reply src/mono/wasi/runtime/main.c:40]: I think that for non-single application, the interesting feature is that dotnet.wasm is always the same content. Full set of features, with which you could run any managed assembly.

File: src/mono/wasi/runtime/main.c [hunk 2]
```diff
@@ -21,8 +21,38 @@ int main(int argc, char * argv[]) {
 #endif
 	mono_wasm_load_runtime("", 0);
 
+	int arg_ofs = 0;
+#ifdef WASM_SINGLE_FILE
```
Comment (pavelsavara) [inline src/mono/wasi/runtime/main.c:25]: this is the same problem we have with shell on emscripten. 
I would prefer to separate the "runtime options" from "application arguments" by ` -- `. 
In this case there are no "runtime options" because we know which assembly to load. 

it would be `wasmtime run --dir . -- --run MainAssembly.wasm -- [args]`

In the non-single file the syntax would be 
it would be `wasmtime run --dir . -- -- [args]`

Note, that wasmtime also has ` -- ` it's own, to solve the same problem.

This would allow us in the future to add other runtime options, without counting positions of the arguments.
For example single-file
`wasmtime run --dir . -- --soft-breakpoints -- [args]`

where `--soft-breakpoints` is example of Mono option

Comment (radical) [reply src/mono/wasi/runtime/main.c:25]: Cleanly delineating arguments sounds like a good idea. I can explore that in a follow up PR. This PR fixes a regression and gets it passing on CI.

**Review by pavelsavara — APPROVED** [review]
