### PR TITLE
Emit More EventSource Data For Metrics Measurements

### LINKED ISSUE #93097: MetricEventSource value published events don't resolve which scope they are refering to
### Description

It is supported to have multiple scopes (DI containers effectively) that each have Meters with the same names and same instruments. When the instruments are initially published the scope hash distinguishes those multiple scopes, however later when values are published the scope hash isn't available. This means if two different scopes both have a Meter named Foo and instrument named Bar, the tool listening to the events can't distinguish which one produced the data.

### Reproduction Steps

Create two DI containers, then create a Meter and an instrument with identical naming in each. Produce some measurements for both. Enable MetricEventSource and listen to the measurement events.

### Expected behavior

The tool should be able to distinguish one set of measurements coming from DI container 1, and a second set of measurements coming from DI container 2.

### Actual behavior

There is no distinguishable information that allows correlating the measurements that came from the same DI container together across time.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/93097 and https://github.com/dotnet/runtime/issues/93767

- https://github.com/dotnet/runtime/issues/93097 
- https://github.com/dotnet/runtime/issues/93767

This change enables the emission of additional metrics data during measurement publishing. Specifically, it will emit the instrument's formatted tags and hash, as well as the meter's formatted tags, scope hash, and meter hash. With this extra data, aggregators can easily differentiate between instruments created with identical parameters such as name, tags, and units. Similarly, it allows for distinguishing between meters created with the same parameters, such as meter name, version, tags, and scope.

### CODE REVIEW

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+                if (i != labels.Length - 1)
+                {
+                    sb.Append(',');
+                }
+            }
+            return sb.ToString();
+        }
+
+        internal static string FormatObjectHash(object? obj) =>
+            obj is null ? string.Empty : RuntimeHelpers.GetHashCode(obj).ToString(CultureInfo.InvariantCulture);
```
Comment (stephentoub) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs:58]: Are you explicitly trying to avoid any object.GetHashCode override the object might provide?

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs [hunk 2]
```diff
@@ -115,40 +115,43 @@ public void CollectionStop(string sessionId, DateTime intervalStartTime, DateTim
...
 #if !NET8_0_OR_GREATER
         [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode",
                                       Justification = "This calls WriteEvent with all primitive arguments which is safe. Primitives are always serialized properly.")]
 #endif
-        public void CounterRateValuePublished(string sessionId, string meterName, string? meterVersion, string instrumentName, string? unit, string tags, string rate, string value)
+        public void CounterRateValuePublished(string sessionId, string meterName, string? meterVersion, string instrumentName, string? unit, string tags, string rate, string value,
+                                    string instrumentFormattedTags, string instrumentHash, string meterFormattedTags, string meterHash, string formattedScopeHash)
         {
-            WriteEvent(4, sessionId, meterName, meterVersion ?? "", instrumentName, unit ?? "", tags, rate, value);
+            WriteEvent(4, sessionId, meterName, meterVersion ?? "", instrumentName, unit ?? "", tags, rate, value, instrumentFormattedTags, instrumentHash, meterFormattedTags, meterHash, formattedScopeHash);
```
Comment (stephentoub) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:126]: We're sending this extra information now on every published value, even though (it looks like) the values don't change for a given instrument? Is that adding a lot of overhead?

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+                {
+                    sb.Append(',');
+                }
+
+                sb.Append(tag.Key).Append('=');
+
+                if (tag.Value is not null)
+                {
+                    sb.Append(tag.Value.ToString());
+                }
```
Comment (stephentoub) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs:38]:
```suggestion
                sb.Append(tag.Key).Append('=').Append(tag.Value);
```

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs (hunk 2 above)
Comment (noahfalk) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:126]: While it is more data than before, I'm not anticipating it to be problematic. The MetricsEventSource has a default limit at 1000 time series being sent at most once per second. Adding these tags and hashes may mean an extra ~100KB/sec is flowing but that is still a couple orders of magnitude what we expect to be stressful amount of data. Consumers can also control the number of time series or the frequency of updates to further reduce the volume. If it did prove to be an issue we could work on some feature in the future to more carefully curate the data provided.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/Meter.cs [hunk 4]
```diff
@@ -17,10 +17,19 @@ public class Meter : IDisposable
         private static readonly List<Meter> s_allMeters = new List<Meter>();
         private List<Instrument> _instruments = new List<Instrument>();
         private Dictionary<string, List<Instrument>> _nonObservableInstrumentsCache = new();
+
+        private string? _formattedTags;
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/Meter.cs:21]: Rather than add this state as internal properties on Meters and Instruments, organizationally I think InstrumentState is the more appropriate abstraction https://source.dot.net/#System.Diagnostics.DiagnosticSource/System/Diagnostics/Metrics/AggregationManager.cs,282.

InstrumentState represents the MetricsEventSource's private stash of data for the instruments it is actively recording whereas putting this on Instrument/Meter means we are paying several pointers per-instrument as soon as the instrument is defined, regardless whether MetricsEventSource ever listens to it. There isn't currently any MeterState object that corresponds to Meter, but I think it would be fine if you added InstrumentState.MeterTags and the string wound up being duplicated if there are multiple instruments on a Meter that has tags. Its probably almost always null given the rarity of Meter tag usage. For the hashes I suggested below you could emit them directly as ints so I think it would be fast enough to invoke GetHashCode() with no cached data at all for those.

If you are short for time I don't see anything functionally problematic leaving the fields where they are. My primary motivation is preserving the abstraction boundary and then memory overhead is a very distant 2nd.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs (hunk 2 above)
Comment (noahfalk) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:126]: @CodeBlanch - I just noticed your comment https://github.com/dotnet/runtime/issues/93767#issuecomment-2137869987 which also refers to this. I'd be fine having these metric data events include an instrument ID and not repeat the other data but two concerns:
1. Tarek has a limited amount of time with the deadline coming very soon. You guys would either need to agree on this fast, or we convince Tarek's managers that its worth making the change after the deadline.
2. You need to add a unique ID per instrument. The Instrument hashcode is close to that, but probably not a strong enough uniqueness guarantee that you'd want to rely on it as a join key. It doesn't take a ridiculous number of Instruments to get an occasional collision in 32 bit numbers. You could get a stronger ID by assigning a unique integer to each InstrumentState when it is first built.

**Review by noahfalk — APPROVED** [review]
A few suggestions inline

**Comment by noahfalk** [comment]
@wiktork @jander-msft - heads up since dotnet-monitor probably wants to consume this data too. Unless we get some extension the checkin deadline is the end of the week so this is likely to go fast.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs:58]: I want to generate instance hash code. we can pass any object (like string or any other type objects) and we want to differentiate between two instances that can generate same hash code  using `object.GetHashCode`.

Comment (stephentoub) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs:53]: > and we want to differentiate between two instances that can generate same hash code using object.GetHashCode

RuntimeHelpers.GetHashCode(obj) does not guarantee that two distinct objects will produce different hash codes.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs [hunk 5]
```diff
@@ -219,10 +226,12 @@ public void InitialInstrumentEnumerationComplete(string sessionId)
...
                         string instrumentTags,
                         string meterTags,
-                        string meterScopeHash)
+                        string meterScopeHash,
+                        string instrumentHash,
+                        string meterHash)
         {
             WriteEvent(11, sessionId, meterName, meterVersion ?? "", instrumentName, instrumentType, unit ?? "", description ?? "",
-                    instrumentTags, meterTags, meterScopeHash);
+                    instrumentTags, meterTags, meterScopeHash, instrumentHash, meterHash);
```
Comment (CodeBlanch) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:234]: @tarekgh 

We have this `InstrumentPublished` event which gives you the meter + instrument tags and the hashes. When we publish the values we also give the hashes. Listeners could build a meter/instrument cache which has the tags and then when values are published used the hashes to go and retrieve the top-level data? What I'm essentially saying is it seems silly\wasteful to keep republishing the same static data over and over 😄

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs [hunk 6]
```diff
@@ -115,40 +115,43 @@ public void CollectionStop(string sessionId, DateTime intervalStartTime, DateTim
...
 
-        [Event(5, Keywords = Keywords.TimeSeriesValues)]
+        [Event(5, Keywords = Keywords.TimeSeriesValues, Version = 2)]
 #if !NET8_0_OR_GREATER
         [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode",
                                       Justification = "This calls WriteEvent with all primitive arguments which is safe. Primitives are always serialized properly.")]
 #endif
-        public void GaugeValuePublished(string sessionId, string meterName, string? meterVersion, string instrumentName, string? unit, string tags, string lastValue)
+        public void GaugeValuePublished(string sessionId, string meterName, string? meterVersion, string instrumentName, string? unit, string tags, string lastValue,
+                                    string instrumentFormattedTags, string instrumentHash, string meterFormattedTags, string meterHash, string formattedScopeHash)
```
Comment (CodeBlanch) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:135]: `InstrumentPublished` event has "meterTags" & "instrumentTags" here we have "meterFormattedTags" & "instrumentFormattedTags" are they the same things? If so can we be consistent with the names?

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs:53]: Yes, but it is good enough for the cases we are using with Meter and Instruments for instance. The only case is the scope if someone created instances of types generating same hash. So `RuntimeHelpers.GetHashCode` is still better to use than `object.GetHashCode`. Note, we are trying to help in every corner case here which is someone create instrument/Meter with exact same parameters as names, tags...etc. If you have a better suggestion, please let me know and I can consider it.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs (hunk 6 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs]: done!

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs (hunk 5 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:234]: @noahfalk already addressed the concern of publishing the extra data in the comment https://github.com/dotnet/runtime/pull/104993#discussion_r1680498380. I'll let him weigh on if would be enough using the instrument and meter hashes to address distinguishing different instruments and avoid sending the tags and scope. Or it really doesn't matter sending these extra data.

Comment (noahfalk) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:234]: I lost internet and I'm doing what I can from the phone. I think I already captured my opinions about this in the previous comment already.

Comment (noahfalk) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:234]: I do not think hash is a go enough ID to use in a join, you need a stronger guarantee of uniqueness.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs [hunk 7]
```diff
@@ -115,40 +115,43 @@ public void CollectionStop(string sessionId, DateTime intervalStartTime, DateTim
...
 
-        [Event(4, Keywords = Keywords.TimeSeriesValues, Version = 1)]
+        [Event(4, Keywords = Keywords.TimeSeriesValues, Version = 2)]
 #if !NET8_0_OR_GREATER
         [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode",
                                       Justification = "This calls WriteEvent with all primitive arguments which is safe. Primitives are always serialized properly.")]
 #endif
-        public void CounterRateValuePublished(string sessionId, string meterName, string? meterVersion, string instrumentName, string? unit, string tags, string rate, string value)
+        public void CounterRateValuePublished(string sessionId, string meterName, string? meterVersion, string instrumentName, string? unit, string tags, string rate, string value,
+                                    string instrumentFormattedTags, string instrumentHash, string meterFormattedTags, string meterHash, string formattedScopeHash)
```
[the remark this answers is not in the document]
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs]: We are not emitting hashes any more.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/Meter.cs (hunk 4 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/Meter.cs]: Now I extended the InstrumentState to carry the Unique instrument Id and publishing the Id in all instrument's events.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs (hunk 5 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs]: I have updated the code to avoid sending the static data with the metrics value published events. Instead, I am sending only unique instrument Id which can be used to identify the instrument.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Helpers.cs:58]: I updated the code and avoided sending the hash codes of the instrument and meter, instead I am sending a unique generated instrument id which help in teh scenarios we are trying fix.

**Comment by tarekgh** [comment]
@noahfalk I have updated the code according to our offline discussion with introducing the instrument Id in our emitted events. If you are interested in looking at the update, please look at the last commit. Thanks!

**Comment by noahfalk** [comment]
LGTM!
