### PR TITLE
Move ComWrappers AddRef to C/C++

### LINKED ISSUE #110747: Hang during AddRef/Release calls from GC callbacks for IReferenceTracker support
### Description

> [!NOTE]
> Somewhat related to #109538. I got this hang from a .NET 10 build with the fix for that issue already there.

### Description

I hit another hang on Native AOT when testing the Microsoft Store:

<details>
  <summary><b>Stack trace (click to expand):</b></summary>
<br/>

```
ntdll.dll!ZwWaitForAlertByThreadId() Line 4059 Unknown
ntdll.dll!RtlAcquireSRWLockExclusive(_RTL_SRWLOCK * SRWLock) Line 1296  C
Windows.UI.Xaml.dll!DirectUI::ReferenceTrackerManager::ReferenceTrackingStarted() Line 512   C++
<MICROSOFT_STORE>.exe!S_P_CoreLib_System_Runtime_InteropServices_TrackerObjectManager__BeginReferenceTracking() Line 107   Unknown
<MICROSOFT_STORE>.exe!S_P_CoreLib_System_Runtime_InteropServices_TrackerObjectManager__GCStartCollection() Line 165   Unknown
<MICROSOFT_STORE>.exe!RestrictedCallouts::InvokeGcCallouts(GcRestrictedCalloutKind eKind, unsigned int uiCondemnedGeneration) Line 195      C++
<MICROSOFT_STORE>.exe!WKS::gc_heap::garbage_collect(int n) Line 24362   C++
> <MICROSOFT_STORE>.exe!WKS::GCHeap::GarbageCollectGeneration(unsigned int gen, gc_reason reason) Line 51305 C++
[Inline Frame] <MICROSOFT_STORE>.exe!VolatileStore(int *) Line 261      C++
[Inline Frame] <MICROSOFT_STORE>.exe!Volatile<int>::Store(const int &) Line 349   C++
[Inline Frame] <MICROSOFT_STORE>.exe!Volatile<int>::operator=(int) Line 388  C++
[Inline Frame] <MICROSOFT_STORE>.exe!WKS::leave_spin_lock(WKS::GCDebugSpinLock *) Line 1704    C++
<MICROSOFT_STORE>.exe!WKS::gc_heap::trigger_gc_for_alloc(int gen_number, gc_reason gr, WKS::GCDebugSpinLock * msl, bool loh_p, WKS::msl_take_state take_state) Line 19008 C++
[Inline Frame] <MICROSOFT_STORE>.exe!WKS::gc_heap::try_allocate_more_space(alloc_context *) Line 19133   C++
<MICROSOFT_STORE>.exe!WKS::gc_heap::allocate_more_space(alloc_context * acontext, unsigned __int64 size, unsigned int flags, int alloc_generation_number) Line 19633      C++
[Inline Frame] <MICROSOFT_STORE>.exe!WKS::gc_heap::allocate_uoh_object(unsigned __int64) Line 45648   C++
<MICROSOFT_STORE>.exe!WKS::GCHeap::Alloc(gc_alloc_context * context, unsigned __int64 size, unsigned int flags) Line 50185     C++
<MICROSOFT_STORE>.exe!GcAllocInternal(MethodTable * pEEType, unsigned int uFlags, unsigned __int64 numElements, Thread * pThread) Line 606     C++
<MICROSOFT_STORE>.exe!RhAllocateNewArray(MethodTable * pArrayEEType, unsigned int numElements, unsigned int flags, Array * * pResult) Line 694 C++
<MICROSOFT_STORE>.exe!S_P_CoreLib_System_GC___AllocateUninitializedArray_g__AllocateNewUninitializedArray_52_0<UInt8>() Line 827   Unknown
<MICROSOFT_STORE>.exe!S_P_CoreLib_System_Buffers_SharedArrayPool_1<UInt8>__Rent() Line 110   Unknown
<MICROSOFT_STORE>.exe!CommunityToolkit_HighPerformance_CommunityToolkit_HighPerformance_ArrayPoolExtensions__Resize<UInt8>() Line 47    Unknown
```
</details>

Dump shared internally, opening this just for tracking.

From @jkotas:

> It turns out that the [AddRef/Release implementations](https://github.com/dotnet/runtime/blob/efb8a8fe6263cb66c154576c859523e885dc5a24/src/coreclr/interop/comwrappers.cpp#L769-L783) in regular CoreCLR are in C/C++ and do not have GC transition in them. ProjectN has AddRef implemented in C/C++ as well with a long comment explaining the reason [...]. I think the fix should be to move the NAOT AddRef implementations (and potentially other methods nearby) to C/C++ to match regular CoreCLR and ProjectN to avoid the GC transitions that lead to deadlock."

cc. @AaronRobinsonMSFT @jkoritzinsky @manodasanW @VSadov @tommcdon @MichalStrehovsky

### PR DESCRIPTION
**Pull request by jkotas**
Xaml invokes AddRef while holding a lock that it *also* holds while a GC is in progress. Managed AddRef had to synchronize with the GC that caused intermittent deadlocks with the other thread holding Xaml's lock.

This change reverts the managed AddRef implementation to match .NET Native and CoreCLR.

Fixes #110747

### CODE REVIEW

File: src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp [hunk 1]
```diff
@@ -70,3 +70,57 @@ FCIMPL2(void, RhUnregisterRefCountedHandleCallback, void * pCallout, MethodTable
     RestrictedCallouts::UnregisterRefCountedHandleCallback(pCallout, pTypeFilter);
 }
 FCIMPLEND
+
+// This structure mirrors the managed type System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch!
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp:74]:
```suggestion
// This structure mirrors the managed type System.Runtime.InteropServices.ComWrappers.ManagedObjectWrapper.
```

File: src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp [hunk 2]
```diff
@@ -70,3 +70,57 @@ FCIMPL2(void, RhUnregisterRefCountedHandleCallback, void * pCallout, MethodTable
...
+
+    static const uint64_t ComRefCountMask = 0x000000007fffffffUL;
+
+    static uint32_t GetComCount(uint64_t c)
+    {
+        return (uint32_t)(c & ComRefCountMask);
+    }
+};
+
+// This structure mirrors the managed type System.Runtime.InteropServices.ComWrappers.InternalComInterfaceDispatch!
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp:99]:
```suggestion
// This structure mirrors the managed type System.Runtime.InteropServices.ComWrappers.InternalComInterfaceDispatch.
```

File: src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp [hunk 3]
```diff
@@ -70,3 +70,57 @@ FCIMPL2(void, RhUnregisterRefCountedHandleCallback, void * pCallout, MethodTable
...
+
+static ManagedObjectWrapper* ToManagedObjectWrapper(void* dispatchPtr)
+{
+    return ((InternalComInterfaceDispatch*)dispatchPtr)->_thisPtr;
+}
+
+//
+// AddRef is implemented in native code so that it can be invoked during a GC.  This is important because Xaml invokes AddRef
+// while holding a lock that it *also* holds while a GC is in progress.  If AddRef was managed, we would have to synchronize
+// with the GC before entering AddRef, which would deadlocks with the other thread holding Xaml's lock.
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp:114]:
```suggestion
// with the GC before entering AddRef, which would deadlock with the other thread holding Xaml's lock.
```

File: src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp [hunk 4]
```diff
@@ -70,3 +70,57 @@ FCIMPL2(void, RhUnregisterRefCountedHandleCallback, void * pCallout, MethodTable
...
+//
+static uint32_t __stdcall IUnknown_AddRef(void* pComThis)
+{
+    ManagedObjectWrapper* wrapper = ToManagedObjectWrapper(pComThis);
+    return wrapper->AddRef();
+}
+
+FCIMPL0(void*, RhGetIUnknownAddRef)
+{
+    return &IUnknown_AddRef;
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp:124]:
```suggestion
    return (void*)&IUnknown_AddRef;
```

**Review by Sergio0694 — APPROVED** [review]
Thank you!! 😄

Tested with the Microsoft Store and could not repro any hangs:
- Checked out `release/9.0-staging` (51fd1e2a44e5167170b4aaba823474c2d2e33743)
- Cherry-pick commits from #110558
- Cherry-pick commits from this PR
- Build with `.\build.cmd clr.aot -c Release`
- Set `IlcSdkPath` in the Store .csproj to `runtime\artifacts\bin\coreclr\windows.x64.Release\aotsdk\`
- Set `GenerateAppxPackageOnBuild`
- Switch to Release
- Deploy

I then tried to use the Store for a while, and also did the same thing that triggered the hang last time (opening and closing it in quick succession a couple dozen times). I could not repro the issue and everything seemed to be working great 🎉

File: src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp [hunk 5]
```diff
@@ -70,3 +70,57 @@ FCIMPL2(void, RhUnregisterRefCountedHandleCallback, void * pCallout, MethodTable
...
+    ManagedObjectWrapper* _thisPtr;
+};
+
+static ManagedObjectWrapper* ToManagedObjectWrapper(void* dispatchPtr)
+{
+    return ((InternalComInterfaceDispatch*)dispatchPtr)->_thisPtr;
+}
+
+//
+// AddRef is implemented in native code so that it can be invoked during a GC.  This is important because Xaml invokes AddRef
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp:112]:
```suggestion
// AddRef is implemented in native code so that it does not need to synchronize with the GC. This is important because Xaml invokes AddRef
```

File: src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp [hunk 6]
```diff
@@ -70,3 +70,57 @@ FCIMPL2(void, RhUnregisterRefCountedHandleCallback, void * pCallout, MethodTable
...
+// while holding a lock that it *also* holds while a GC is in progress.  If AddRef was managed, we would have to synchronize
+// with the GC before entering AddRef, which would deadlock with the other thread holding Xaml's lock.
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/HandleTableHelpers.cpp:114]:
```suggestion
// AddRef is implemented in native code so that it does not need to synchronize with the GC. This is important because Xaml
// invokes AddRef while holding a lock that it *also* holds while a GC is in progress.  If AddRef was managed, we would have
// to synchronize with the GC before entering AddRef, which would deadlock with the other thread holding Xaml's lock.
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 7]
```diff
@@ -1302,12 +1302,14 @@ internal static unsafe int IUnknown_QueryInterface(IntPtr pThis, Guid* guid, Int
...
         }
 
+#if false // Implemented in C/C++ to avoid GC transitions
         [UnmanagedCallersOnly]
         internal static unsafe uint IUnknown_AddRef(IntPtr pThis)
         {
             ManagedObjectWrapper* wrapper = ComInterfaceDispatch.ToManagedObjectWrapper((ComInterfaceDispatch*)pThis);
             return wrapper->AddRef();
         }
+#endif
```
Comment (jkoritzinsky) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:1312]: I don't really like the `#if false` pattern. I'd rather we just include a comment on line 1160 explaining that we have it implemented in C/C++ to avoid GC transitions.

**Review by AaronRobinsonMSFT — APPROVED** [review]
I agree with @jkoritzinsky's comment about the `#if false` style. Other than that, LGTM.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 8]
```diff
@@ -1157,7 +1157,7 @@ public static void RegisterForMarshalling(ComWrappers instance)
         public static unsafe void GetIUnknownImpl(out IntPtr fpQueryInterface, out IntPtr fpAddRef, out IntPtr fpRelease)
         {
             fpQueryInterface = (IntPtr)(delegate* unmanaged<IntPtr, Guid*, IntPtr*, int>)&ComWrappers.IUnknown_QueryInterface;
-            fpAddRef = (IntPtr)(delegate* unmanaged<IntPtr, uint>)&ComWrappers.IUnknown_AddRef;
+            fpAddRef = RuntimeImports.RhGetIUnknownAddRef();
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:1160]:
```suggestion
            fpAddRef = RuntimeImports.RhGetIUnknownAddRef(); // Implemented in C/C++ to avoid GC transitions
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs (hunk 7 above)
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:1312]:
```suggestion
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 9]
```diff
@@ -1302,12 +1302,6 @@ internal static unsafe int IUnknown_QueryInterface(IntPtr pThis, Guid* guid, Int
             return wrapper->QueryInterface(in *guid, out *ppObject);
         }
 
-        [UnmanagedCallersOnly]
-        internal static unsafe uint IUnknown_AddRef(IntPtr pThis)
-        {
-            ManagedObjectWrapper* wrapper = ComInterfaceDispatch.ToManagedObjectWrapper((ComInterfaceDispatch*)pThis);
-            return wrapper->AddRef();
-        }
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:1305]:
```suggestion
```

**Review by jkoritzinsky — APPROVED** [review]
