### PR TITLE
[NativeAOT] Fix a stress crash in thread detach at process shutdown.

### LINKED ISSUE #73116: [NativeAOT] Stress crash in ThreadStore::DetachCurrentThread
This is relatively rare, but it does not look linux-arm64 specific. It happens on linux-x64 as well. 
(not sure about windows)

The following crash is with the current main (i.e. linux-arm64 prior to runtime suspension changes). 
It may need many iterations to show up.

```
* thread #1, name = 'System.Net.Secu', stop reason = signal SIGSEGV
  * frame #0: 0x0000aaaaba8d1d94 System.Net.Security.Unit.Tests`unsigned long rh::std::count<SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, Thread*>(SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, Thread* const&) [inlined] SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator::_Value(this=0x0000ffff3fffe7d8) const at slist.inl:273:53
    frame #1: 0x0000aaaaba8d1d84 System.Net.Security.Unit.Tests`unsigned long rh::std::count<SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, Thread*>(SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, Thread* const&) [inlined] SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator::operator==(this=0x0000ffff3fffe7d8, rhs=0x0000ffff3fffe7c8) at slist.inl:207
    frame #2: 0x0000aaaaba8d1d74 System.Net.Security.Unit.Tests`unsigned long rh::std::count<SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, Thread*>(SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, Thread* const&) [inlined] SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator::operator!=(this=0x0000ffff3fffe7d8, rhs=0x0000ffff3fffe7c8) at slist.inl:226
    frame #3: 0x0000aaaaba8d1d74 System.Net.Security.Unit.Tests`unsigned long rh::std::count<SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy> >::Iterator, Thread*>(_First=Iterator @ 0x0000ffff3fffe7d8, _Last=Iterator @ 0x0000ffff3fffe7c8, _Val=0x0000ffff3fffe7b8) at type_traits.hpp:232
    frame #4: 0x0000aaaaba8d1514 System.Net.Security.Unit.Tests`ThreadStore::DetachCurrentThread() at threadstore.cpp:170:9

```

### PR DESCRIPTION
**Pull request by VSadov**
fixes: https://github.com/dotnet/runtime/issues/73116

At shutdown we allow some threads to terminate without removing themselves from the thread list. Once a TLS of such thread is released, the thread list becomes corrupted, so whoever iterates the list now or later crashes.

Since we cannot be sure that every thread is promptly aware that we are shutting down, we cannot let threads to exit without removing themselves from the thread list first.

### CODE REVIEW

**Comment by VSadov** [comment]
This crash/assert is such a nuisance when running libs tests as a stress test.

File: src/coreclr/nativeaot/Runtime/threadstore.cpp [hunk 1]
```diff
@@ -165,10 +165,21 @@ void ThreadStore::DetachCurrentThread()
...
         ASSERT(rh::std::count(pTS->m_ThreadList.Begin(), pTS->m_ThreadList.End(), pDetachingThread) == 1);
         pTS->m_ThreadList.RemoveFirst(pDetachingThread);
+
+        // the rest of cleanup is not necessary if we are shutting down.
+        if (shutdownStarted)
+        {
+            return;
+        }
+
         pDetachingThread->Detach();
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/threadstore.cpp:183]: We are going to skip `FixAllocContext` here. Is it going to cause problems/asserts with GC accounting if the GC manages to sneak in before the process actually exits?

Would it be better to only skip `Thread::Destroy`, but keep `Thread::Detach`?

**Review by jkotas — APPROVED** [review]

File: src/coreclr/nativeaot/Runtime/threadstore.cpp (hunk 1 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/threadstore.cpp:176]: It would probably only affect statistics like total alloc bytes if someone manages to query for that before the exit. 
We may as well call `FixAllocContext`. It is not a lot of savings if we don't.

**Comment by VSadov** [comment]
the failure on arm64 is https://github.com/dotnet/runtime/issues/13757

**Comment by VSadov** [comment]
Thanks!
