### PR TITLE
Remove some uses of dynamic from HardwareIntrinsic test code

### LINKED ISSUE #118234: AdvSimd tests don't run on native AOT
Had to disable them because a newly added test uses dynamic keyword. Dynamic keyword is not compatible with trimming or AOT. I'm surprised to see it in a JIT test.

```
03:06:58.023 Running test: _AdvSimd_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Program.AddRoundedHighNarrowingLower_Vector64_Int16()
Beginning scenario: RunBasicScenario_UnsafeRead
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) + 0x3c8
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value) + 0x10
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.VisitSAVE(ExprBinOp) + 0x5c
   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Dispatch(Expr) + 0x408
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.Rewrite(ExprBinOp, Expression[]) + 0x6c
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder, Expression[], DynamicMetaObject[], DynamicMetaObject&) + 0x1d4
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(ICSharpBinder, Expression[], DynamicMetaObject[], DynamicMetaObject&) + 0x58
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(ICSharpBinder, RuntimeBinder, DynamicMetaObject[], IEnumerable`1, DynamicMetaObject) + 0x490
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[], ReadOnlyCollection`1, LabelTarget) + 0x148
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1, Object[]) + 0x94
   at HardwareIntrinsics_Arm_ro!<BaseAddress>+0x3e90fec
   at System.Reflection.DynamicInvokeInfo.InvokeWithFewArguments(IntPtr, Byte&, Byte&, Object[], BinderBundle, Boolean) + 0xd0
--- End of stack trace from previous location ---
   at System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow(TargetInvocationException) + 0x18
   at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame) + 0x1cc
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame) + 0x48
   at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] arguments) + 0x8c
   at HardwareIntrinsics_Arm_ro!<BaseAddress>+0x3ce7d60
   at JIT.HardwareIntrinsics.Arm.Helpers.AddRoundedHighNarrowing[W,N](W op1, W op2) + 0xa4
   at JIT.HardwareIntrinsics.Arm._AdvSimd.SimpleBinaryOpTest__AddRoundedHighNarrowingLower_Vector64_Int16.ValidateResult(Int32[] left, Int32[] right, Int16[] result, String method) + 0x90
   at JIT.HardwareIntrinsics.Arm._AdvSimd.Program.AddRoundedHighNarrowingLower_Vector64_Int16() + 0x3c
   at Program.<<Main>$>g__TestExecutor988|0_989(StreamWriter tempLogSw, StreamWriter statsCsvSw, Program.<>c__DisplayClass0_0&) + 0x114
03:06:58.025 Failed test: _AdvSimd_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Program.AddRoundedHighNarrowingLower_Vector64_Int16()
```

### PR DESCRIPTION
**Pull request by snickolls-arm**
This is preventing the AdvSimd tests from running in NativeAOT contexts.

Fixes #118234

@dotnet/arm64-contrib

### CODE REVIEW

**Comment by a74nh** [comment]
Do the AOT tests get automatically run in the CI ?

**Comment by EgorBo** [comment]
> Do the AOT tests get automatically run in the CI ?

cc @MichalStrehovsky 


@MichalStrehovsky please run any outerloop pipelines here if necessary

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky please run any outerloop pipelines here if necessary

You found the right one.

**Review by amanasifkhalid — COMMENTED** [review]
I still see some usages of `dynamic` in `Helpers.cs`, like in `SignExtend<T>()`. We may not be using these helpers in any of the AdvSimd tests, so NativeAOT isn't blocked (yet), but could you please remove these as well while you're here?

If the remaining uses look tedious to fix, we can save them for a follow-up.

**Comment by snickolls-arm** [comment]
> I still see some usages of `dynamic` in `Helpers.cs`, like in `SignExtend<T>()`. We may not be using these helpers in any of the AdvSimd tests, so NativeAOT isn't blocked (yet), but could you please remove these as well while you're here?
> 
> If the remaining uses look tedious to fix, we can save them for a follow-up.

I'm working on the follow-up at the moment and I discovered another problem while doing so: https://github.com/dotnet/runtime/issues/94015#issuecomment-3144494717

I'm thinking the best way to keep a correct state is to fix that intrinsic that uses the helper, and then remove `dynamic` from the helper. As the other way around might involve committing some temporarily incorrect code.

**Comment by amanasifkhalid** [comment]
> I'm working on the follow-up at the moment and I discovered another problem while doing so: https://github.com/dotnet/runtime/issues/94015#issuecomment-3144494717

Ah, I didn't see that. In that case, let's take this as-is. Thanks for the fix!

**Review by amanasifkhalid — APPROVED** [review]

**Comment by amanasifkhalid** [comment]
There are some nativeaot-outerloop failures on non-arm64 platforms. A bunch of tests are flagged as failing on linux-arm, despite the console logs showing they exited successfully. Some `baseservices/threading` tests are failing with OOMs, ex:

```
17:55:50.857 Running test: baseservices/threading/generics/threadstart/GThread01_threadstart/GThread01_threadstart.dll
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Threading.Thread.StartCore() + 0xd5
   at Gen`1.ThreadPoolTest() + 0xdd
   at Test_thread01.TestEntryPoint() + 0xc3
   at Program.<<Main>$>g__TestExecutor4|0_5(StreamWriter tempLogSw, StreamWriter statsCsvSw, Program.<>c__DisplayClass0_0&) + 0x16f
```

And on osx-x64, `System.Runtime.Numerics.Tests` build is failing with the following errors from ILC:

```
2025-08-01T15:27:58.5531970Z EXEC : error : unexpected line op length at offset 0x00078652 expected 0x2c02 found 0x03 [/Users/runner/work/1/s/src/libraries/System.Runtime.Numerics/tests/System.Runtime.Numerics.Tests.csproj]
2025-08-01T15:27:58.5540700Z EXEC : error : last sequence in debug line table at offset 0x00000000 is not terminated [/Users/runner/work/1/s/src/libraries/System.Runtime.Numerics/tests/System.Runtime.Numerics.Tests.csproj]
2025-08-01T15:27:58.5548600Z EXEC : error : unexpected line op length at offset 0x00078652 expected 0x2c02 found 0x03 [/Users/runner/work/1/s/src/libraries/System.Runtime.Numerics/tests/System.Runtime.Numerics.Tests.csproj]
2025-08-01T15:27:58.5553220Z EXEC : error : last sequence in debug line table at offset 0x00000000 is not terminated [/Users/runner/work/1/s/src/libraries/System.Runtime.Numerics/tests/System.Runtime.Numerics.Tests.csproj]
```

@MichalStrehovsky do any of these failures look familiar to you?

**Comment by MichalStrehovsky** [comment]
> And on osx-x64, System.Runtime.Numerics.Tests build is failing with the following errors from ILC:

This one is known and Build Analysis correctly paired it.

> Some baseservices/threading tests are failing with OOMs, ex:

I've not seen this but Helix machines running into OOM is not unusual. Definitely not related to this PR, I'd not block on it.

File: src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs [hunk 1]
```diff
@@ -7789,35 +7789,33 @@ public static W MultiplyAddWidening<W, N>(W op1, N op2, N op3)
...
         public static N AddRoundedHighNarrowing<W, N>(W op1, W op2)
             where W : IBinaryInteger<W>
             where N : IBinaryInteger<N>
         {
             int halfsize = default(N).GetByteCount() * 8;
-            dynamic a = op1;
-            dynamic b = op2;
-            ulong sum = (ulong)a + (ulong)b;
+            ulong a = Convert.ToUInt64(op1);
+            ulong b = Convert.ToUInt64(op2);
```
Comment (tannergooding) [inline src/tests/JIT/HardwareIntrinsics/Arm/Shared/Helpers.cs]: These should be `ulong.CreateTruncating(op1)` or similar instead.

`Convert.*` is largely an expensive legacy API that isn't recommended for use when the `INumber<T>.Create` APIs are available.

**Review by tannergooding — APPROVED** [review]
