### PR TITLE
Fix the operands of NI_AVX512F_TernaryLogic during lowering

### LINKED ISSUE #107324: Assertion failed 'unreached' during 'Lowering nodeinfo'
```c#
// Found by Antigen
// Reduced from 60.5 KB to 2 KB.


using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;
using System.Numerics;
public class TestClass
{
    public struct S1
    {
    }
    static Vector512<short> s_v512_short_40 = Vector512<short>.AllBitsSet;
    static Vector<short> s_v_short_50 = Vector.Create((short)0);
    static S1 s_s1_61 = new S1();
    bool bool_63 = false;
    Vector512<short> v512_short_100 = Vector512.Create(1, 38, 5, -1, 1, 38, -2, 5, -2, 38, 38, -1, 0, 38, -2, 38, -2, 38, -2, 2, 5, 2, 3, -2, -1, -1, -2, 3, 1, 3, 38, 38);
    Vector<short> v_short_110 = Vector.Create((short)3);
    private static List<string> toPrint = new List<string>();
    public S1 Method1(S1 p_s1_123, out Vector<short> p_v_short_124)
    {
        unchecked
        {
            byte byte_126 = 3;
            p_v_short_124 = v_short_110 | Vector.AsVectorInt16(v_short_110) + s_v_short_50^ v_short_110;
            switch (15%4)
            {
                case 5:
                {
                    break;
                }
                default:
                {
                    int __loopvar8 = 15-4;
                    for (;;)
                    {
                        __loopvar8 += 2;
                        if (__loopvar8 >= 15+4)
                            break;
                        bool_63 = Vector512.EqualsAll((15-4)* Avx512F.TernaryLogic(v512_short_100, Vector512<short>.AllBitsSet, s_v512_short_40, byte_126), v512_short_100);
                    }
                    break;
                }
            }
            return s_s1_61;
        }
    }
    public void Method0()
    {
        unchecked
        {
            s_s1_61 = Method1(s_s1_61, out s_v_short_50);
            return;
        }
    }
    public static void Main(string[] args)
    {
    }
    public static int Antigen()
    {
        new TestClass().Method0();
        return string.Join(Environment.NewLine, toPrint).GetHashCode();
    }
}
/*
Environment:

set DOTNET_JitEdgeProfiling=0
set DOTNET_JitStressEvexEncoding=1
set DOTNET_TieredCompilation=0
set DOTNET_PreferredVectorBitWidth=512
set DOTNET_JitStressRegs=2
set DOTNET_JitThrowOnAssertionFailure=1
set DOTNET_LegacyExceptionHandling=1

Debug: 28101970

Release: 0
JIT assert failed:
Assertion failed 'unreached' in 'TestClass:Method1(TestClass+S1,byref):TestClass+S1:this' during 'Lowering nodeinfo' (IL size 117; hash 0xcd0a9be8; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\lowerxarch.cpp Line: 11752


*/

```

### LINKED ISSUE #107587: windows/x86: Assertion failed 'unreached' during 'Lowering nodeinfo'
```c#
// Found by Antigen
// Reduced from 20.86 KB to 1.7 KB.


using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;
using System.Numerics;
public class TestClass
{
    public struct S2
    {
    }
    static Vector256<ushort> s_v256_ushort_34 = Vector256.Create((ushort)2);
    static Vector512<sbyte> s_v512_sbyte_42 = Vector512.Create((sbyte)92);
    static Vector512<short> s_v512_short_43 = Vector512.Create(1, -2, -2, 0, 92, 2, 0, 1, 0, 0, 5, 1, 1, 5, 0, 1, -2, -1, 1, 5, 92, 92, -1, 5, -1, 3, 5, 0, -1, 92, 2, 5);
    static S2 s_s2_65 = new S2();
    Vector512<sbyte> v512_sbyte_102 = Vector512.CreateScalar((sbyte)-2);
    Vector3 v3_122 = Vector3.UnitX;
    private static List<string> toPrint = new List<string>();
    public Vector512<short> Method1(Vector3 p_v3_126, S2 p_s2_127, int p_int_128, S2 p_s2_129, Vector512<sbyte> p_v512_sbyte_130, ref Vector256<ushort> p_v256_ushort_131, byte p_byte_132)
    {
        unchecked
        {
            return s_v512_short_43 -= s_v512_short_43;
        }
    }
    public void Method0()
    {
        unchecked
        {
            byte byte_152 = 3;
            int int_157 = 0;
            S2 s2_167 = new S2();
            s_v512_short_43 = Method1(15*4* (v3_122 += Vector3.Round(v3_122)), s_s2_65, int_157, s2_167, s_v512_sbyte_42 *= s_v512_sbyte_42 *= Avx512F.TernaryLogic(v512_sbyte_102, s_v512_sbyte_42, s_v512_sbyte_42, byte_152), ref s_v256_ushort_34, 15+4);
            return;
        }
    }
    public static void Main(string[] args)
{}
    public static int Antigen()
    {
        new TestClass().Method0();
        return string.Join(Environment.NewLine, toPrint).GetHashCode();
    }
}
/*
Environment:

set DOTNET_JitDoReversePostOrderLayout=1
set DOTNET_JitRandomOnStackReplacement=5
set DOTNET_JitEdgeProfiling=0
set DOTNET_JitStressEvexEncoding=1
set DOTNET_JitELTHookEnabled=1
set DOTNET_JitStressProcedureSplitting=1
set DOTNET_TieredCompilation=0
set DOTNET_PreferredVectorBitWidth=512
set DOTNET_JitStressRegs=1
set DOTNET_JitThrowOnAssertionFailure=1
set DOTNET_LegacyExceptionHandling=1

Debug: -283778863

Release: 0
JIT assert failed:
Assertion failed 'unreached' in 'TestClass:Method0():this' during 'Lowering nodeinfo' (IL size 133; hash 0x46e9aa75; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\lowerxarch.cpp Line: 11752


*/

```

### PR DESCRIPTION
**Pull request by kunalspathak**
We were not correctly translating the logical operation into control word leading to assert getting hit during containment.

Fixes: https://github.com/dotnet/runtime/issues/107587
Fixes: https://github.com/dotnet/runtime/issues/107324

### CODE REVIEW

File: src/coreclr/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -3897,11 +3897,10 @@ GenTree* Lowering::LowerHWIntrinsicTernaryLogic(GenTreeHWIntrinsic* node)
                     case TernaryLogicUseFlags::AB:
                     {
                         // Swap the operands here to make the containment checks in codegen significantly simpler
-                        std::swap(node->Op(2), node->Op(3));
-                        std::swap(node->Op(1), node->Op(2));
+                        std::swap(node->Op(1), node->Op(3));
 
                         // Make sure we also fixup the control byte
-                        control = TernaryLogicInfo::GetTernaryControlByte(info, C, A, B);
+                        control = TernaryLogicInfo::GetTernaryControlByte(info, C, B, A);
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:3903]: Not understanding why this fixes the problem; I think it might instead introduce a different one...

We start with `ABC` where we're using `AB` and `C` is unused. (A == op1, B == op2, C == op3)

We then swap `op2/op3` giving us `ACB` (A == op1, C == op2, B == op3)
We then swap `op1/op2` giving us `CAB` (C == op1, A == op2, B == op3)

This should change the use to `BC` leaving `A`  (op1) as unused.

-----------------

All you've done here is effectively change it from `ABC` to `CBA` (C == op1, B == op2, A == op3)

This will mean that the operand order has changed for used operands, which can negatively impact certain operations.

I think rather the issue is that `GetTernaryControlByte` should've been `(info, B, C, A)` instead. Because it was `AB` with C unused and we want `BC` with `A` unused

Comment (kunalspathak) [reply src/coreclr/jit/lowerxarch.cpp:3903]: Got it. Yes, I didn't understand these semantics, so that was my best (and wrong) guess. Fixed it as per your suggestion.

**Comment by JulieLeeMSFT** [comment]
@tannergooding @BruceForstall PTAL. We want to merge before 4pm today.

**Review by tannergooding — APPROVED** [review]

File: src/tests/JIT/Regression/JitBlue/Runtime_107587/Runtime_107587.cs [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+    public Vector512<sbyte> Method0()
+    {
+        byte byte_152 = 3;
+        return Avx512F.TernaryLogic(s_v512_sbyte_42, s_v512_sbyte_42, s_v512_sbyte_42, byte_152);
+    }
+    
+    [Fact]   
+    public static void TestEntryPoint()
+    {
+        try
```
Comment (tannergooding) [inline src/tests/JIT/Regression/JitBlue/Runtime_107587/Runtime_107587.cs:32]: This should rather be checking `if (Avx512F.IsSupported)`, rather than doing try/catch, no?

Comment (kunalspathak) [reply src/tests/JIT/Regression/JitBlue/Runtime_107587/Runtime_107587.cs:32]: ah, I misread the error of a different issue about "NullReferenceException". Will fix it.
