### PR TITLE
Fix fast tail calls on Windows ARM64.

### LINKED ISSUE #31729: tailcalls_do / tailcalls_d fail on Windows ARM64
*Example repro:*

https://dev.azure.com/dnceng/public/_build/results?buildId=494779&view=ms.vss-test-web.build-test-results-tab&runId=15897688&resultId=100793&paneView=debug

*Diagnostic info:*

<pre>
Return code: 1
Raw output file: C:\dotnetbuild\work\98AC07F7\w\9293083E\e\JIT\Stress\Reports\JIT.Stress\ABI\tailcalls_do\tailcalls_do.output.txt
Raw output:
BEGIN EXECUTION
 "C:\dotnetbuild\work\98AC07F7\p\corerun.exe" tailcalls_do.dll --tailcalls --num-calls 1000 --no-ctrlc-summary 
Stressing tailcalls
OSVersion: Microsoft Windows NT 6.2.9200.0
OSArchitecture: Arm64
ProcessArchitecture: Arm64
Selecting win64 ABI
Mismatch in tailcall: expected -1792697222, got -241256253
Int32 ABIStress_TailCaller4(S2U, Double, Int16, Int32, Int16, S1P, S8P, S2U, S8P, S4U, S8P, Int32, S2U, Byte, S2U, S4U, Single, S2U, Byte, S8P, Int16, S1P, S4P, S4U)
Int32 ABIStress_TailCallee5178(Int64, S4P, S4U, S8P, Double, S2P, S4P, S2U, Single, Double, S8U, S8P)
Mismatch in tailcall: expected 329656105, got -1461745871
Int32 ABIStress_TailCaller9(S8U, Byte, S2U, Single, S1P, Int32, Int32, S2U, Int16, Int16, Double, Byte, S4P, S4U, S2U)
Int32 ABIStress_TailCallee8146(Int32, S1P, Int64, S8P, Int64, Int16, S4U, S4U, Single, S4P, S4P, S1P, S4P, Single)
Mismatch in tailcall: expected 1872306653, got -280200393
Int32 ABIStress_TailCaller10(Int32, S8U, S4U, Int64, S8U, S4P, Double, S2U, S4U, S4U, Double, S2U, Int64, S4U, S8U, S8P, S2P, S4U, Byte, S2P, Double, S8P)
Int32 ABIStress_TailCallee6312(Double, Double, S4P, S8U, S1P, S2P, Single, S4U, Byte, Int64, Byte, Double, S4U, S4P, Int64, S8U, S2P, S8P, Single)
Mismatch in tailcall: expected -958760121, got 1383693481
Int32 ABIStress_TailCaller31(Int16, S8P, Single, Int16, Int16, S4U, S2P, S4P, Byte, S8P, S8U, Single, S1P, Int32, Int16, S4U)
Int32 ABIStress_TailCallee9934(Int64, Int16, Double, S2U, Int64, Byte, S4P, S8P, S4U, S8U, Single, S1P, Int16, S2P, Byte)
50 callers done (45 successful tailcalls tested)
Mismatch in tailcall: expected -1032050283, got -1862624250
Int32 ABIStress_TailCaller50(S4U, S2P, S4P, S2P, Int32, S8P, S2P, Int64, S1P, Byte, S8U, S2U, S8U, S1P, Int16, S8P, Byte, Double)
Int32 ABIStress_TailCallee9994(Int64, Single, S8P, Int16, Int32, Int64, Int64, S8U, Int32, Int64, Single, Int16, S8U, S2P, Double)
Mismatch in tailcall: expected 1332452070, got 285299523
Int32 ABIStress_TailCaller52(Int64, Int32, Double, Int16, Single, S4P, Byte, S8U, S2U, S4U, S8U, S4U, S2P, S8P, S4U, Int32, Byte, Int32, Byte, S8P, Int64, S2U, Single, Int64)
Int32 ABIStress_TailCallee1312(S8P, S2P, Int16, Byte, Double, Int16, Int32, Int16, S2U, S4P, Byte, Int32, Byte, Double, Double, S8P, Byte, S1P, S4U, Single, Byte, S8U)
Mismatch in tailcall: expected -454712802, got 1026721613
Int32 ABIStress_TailCaller58(S8U, Byte, Int16, Single, S4U, Single, S4P, S2P, S8P, S8P, Byte, Int64, S1P, S2U, Single, Double, S8P, Double)
Int32 ABIStress_TailCallee9374(Int64, S8U, S4U, S4U, Int64, Single, S4U, S4P, S4P, Int64, S8U, Byte, S4U, S8U)
Mismatch in tailcall: expected 1977502728, got -1485647357
Int32 ABIStress_TailCaller63(S2P, Int16, Int64, Int32, Byte, Byte, Byte, S2U, S8U, Double, S2U, S8U, S4P, S8P, Double, Int16, S2P, S4U, S1P, S8U, Byte, S2U, S4U)
Int32 ABIStress_TailCallee2379(S4U, S8P, S2P, S4P, Single, S4U, Int16, Single, Byte, Int64, S2U, Int16, S8U)
Mismatch in tailcall: expected 1587307949, got 202074404
Int32 ABIStress_TailCaller64(Int32, S4U, S8U, S2P, S8P, S1P, S2U, Byte, S4U, Byte, S2P, S2P, S4P, S4P, S4U, Double, Int64, S4U, Double)
Int32 ABIStress_TailCallee2937(S2U, Int16, Int16, S4P, Single, S4P, S2U, S8P, S8U, S8P, Int64, Int32, S2P, S4U, S4P, Int64, Double)
Mismatch in tailcall: expected 1855809914, got -1738803405
Int32 ABIStress_TailCaller73(Double, S2P, Int16, Int16, S2P, S8U, Int16, S8P, Int16, Single, S4U, Int16, S4P, S1P, S8U, S4P, S8U, Byte, S2P, S8P, Byte, S2P, Single, Int16)
Int32 ABIStress_TailCallee1009(S2U, S4U, Int32, S2P, S1P, S4P, S8P, Int32, Double, Int16, Int64, S2P, Single, Int16)
Mismatch in tailcall: expected -1351429783, got -1492495110
</pre>

The <code>issues.targets</code> already disables some JIT tests with the issue set to "Requires helper-based tailcalls"; not sure whether this is related. CC @janvorli who was involved in the tailcall design and parts of its implementation AFAIK.

category:correctness
theme:testing
skill-level:expert
cost:small

### LINKED ISSUE #36911: [Arm64] tailcall bad codegen
Failure in libraries test System.Private.Uri.Tests:
```
       public void Ctor_String_String_Int_String_String(string schemeName, string hostName, int port, string pathValue, string extraValue, string expectedScheme, string expectedHost, string expectedPath, string expecte
Query, string expectedFragment)
       {
           var uriBuilder = new UriBuilder(schemeName, hostName, port, pathValue, extraValue);
           VerifyUriBuilder(uriBuilder, expectedScheme, "", "", expectedHost, port, expectedPath, expectedQuery, expectedFragment);
       }
```

e.g.:
```
c:\bugs\System.Private.Uri.Functional.Tests\net5.0-Release>"C:\bugs\testhost\dotnet.exe" exec --runtimeconfig System.Private.Uri.Functional.Tests.runtimeconfig.json --depsfile System.Private.Uri.Functional.Tests.deps.json xunit.console.dll System.Private.Uri.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -parallel none -maxthreads 1 -method "*.Ctor_String_String_Int_String_String"
Discovering: System.Private.Uri.Functional.Tests (method display = ClassAndMethod, method display options = None)
Discovered:  System.Private.Uri.Functional.Tests (found 1 of 382 test case)
Starting:    System.Private.Uri.Functional.Tests (parallel test collections = off, max threads = 1)
System.PrivateUri.Tests.UriBuilderTests.Ctor_String_String_Int_String_String(schemeName: "http", hostName: "host", port: 0, pathValue: "/path", extraValue: "?query#fragment", expectedScheme: "http", expectedHost: "host", expectedPath: "/path", expectedQuery: "?query", expectedFragment: "#fragment") [FAIL]
Assert.Equal() Failure
 (pos 0)
Expected: #fragment
Actual:   /path
 (pos 0)
Stack Trace:
C:\gh\runtime\src\libraries\System.Private.Uri\tests\FunctionalTests\UriBuilderTests.cs(391,0): at System.PrivateUri.Tests.UriBuilderTests.VerifyUriBuilder(UriBuilder uriBuilder, String scheme, String userName, String password, String host, Int32 port, String path, String query, String fragment)
System.PrivateUri.Tests.UriBuilderTests.Ctor_String_String_Int_String_String(schemeName: "HTTP", hostName: "host", port: 20, pathValue: "/path1/path2", extraValue: "?query&query2=value#fragment", expectedScheme: "http", expectedHost: "host", expectedPath: "/path1/path2", expectedQuery: "?query&query2=value", expectedFragment: "#fragment") [FAIL]
```

JIT generates a tailcall to VerifyUriBuilder. It needs to copy 3rd stack argument arg10 to be the 1st stack argument of the tailcall. It moves the argument on the stack, trashing the stack argument arg8 before it is loaded into a register for the tailcall.
```
G_M8925_IG03:        ; offs=000064H, size=0034H, bbWeight=1    PerfScore 14.00, nogc, extend

IN000d: 000064                    ldr     x20, [fp,#96] // [V10 arg10]
IN000e: 000068                    str     x20, [fp,#80] // [V08 arg8]
IN000f: 00006C                    movz    x2, #0x3060
IN0010: 000070                    movk    x2, #0xd0a0 LSL #16
IN0011: 000074                    movk    x2, #487 LSL #32
IN0012: 000078                    ldr     x3, [x2]
IN0013: 00007C                    mov     x2, x3
IN0014: 000080                    mov     x0, x26
IN0015: 000084                    mov     x1, x24
IN0016: 000088                    mov     x4, x25
IN0017: 00008C                    mov     w5, w19
IN0018: 000090                    ldr     x6, [fp,#80]  // [V08 arg8]
*************** reading the already trashed expectedPath!
IN0019: 000094                    ldr     x7, [fp,#88]  // [V09 arg9]

G_M8925_IG04:        ; offs=000098H, size=0018H, bbWeight=1    PerfScore 6.00, epilog, nogc, extend

IN0027: 000098                    ldp     x25, x26, [sp,#64]
IN0028: 00009C                    ldp     x23, x24, [sp,#48]
IN0029: 0000A0                    ldp     x21, x22, [sp,#32]
IN002a: 0000A4                    ldp     x19, x20, [sp,#16]
IN002b: 0000A8                    ldp     fp, lr, [sp],#80
IN002c: 0000AC                    b       System.PrivateUri.Tests.UriBuilderTests:VerifyUriBuilder(System.UriBuilder,System.String,System.String,System.String,System.String,int,System.String,System.String,System.String)
```

### PR DESCRIPTION
**Pull request by erozenfeld**
LowerFastTailCall has code that looks for incoming stack arguments
that may be overwritten by outgoing stack arguments and copies
them to a temp. The logic was incorrect for Windows Arm64 because it was
assuming shadow space, which only exists in Windows x64 abi.

Fixes #31729.
Fixes #36911.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@BruceForstall @dotnet/jit-contrib PTAL

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/src/jit/lower.cpp [hunk 1]
```diff
@@ -1883,7 +1883,7 @@ void Lowering::LowerFastTailCall(GenTreeCall* call)
                     continue;
                 }
 
-#if defined(TARGET_WINDOWS) && defined(TARGET_64BIT)
+#if defined(TARGET_WINDOWS) && defined(TARGET_AMD64)
                 // On Win64, the argument position determines the stack slot uniquely, and even the
```
Comment (jkotas) [inline src/coreclr/src/jit/lower.cpp:1887]: Nit: Fix the comment?

**Review by jashook — APPROVED** [review]

File: src/coreclr/src/jit/lower.cpp (hunk 1 above)
Comment (erozenfeld) [reply src/coreclr/src/jit/lower.cpp]: Fixed.

**Comment by jkotas** [comment]
Test failures are tracked by https://github.com/dotnet/runtime/issues/35068 and https://github.com/dotnet/runtime/issues/37132
