### PR TITLE
[mono] Implement IgnoresAccessChecksToAttribute support

### LINKED ISSUE #47989: [mono] Add support for IgnoresAccessChecksToAttribute
The issue is specific to mono.

Most likely same issue exists for InternalsVisibleTo but this was not tested.

See System.Reflection.DispatchProxy tests disabled with this issue number. All tests are using TestType_PrivateProxy. Tests look similar to this:

```csharp
public class TestType_PrivateProxy
{
    public static T Proxy<T>() => DispatchProxy.Create<T, InvokeProxy<T>>();

    private class InvokeProxy<T> : DispatchProxy
    {
        protected override object Invoke(MethodInfo targetMethod, object[] args) => null;
    }
}

// Testcase (pass any interface as generic argument):
TestType_PrivateProxy.Proxy<TestType_InternalInterfaceService>()
```

the dispatch proxy adds IgnoresAccessChecksToAttribute to the assembly so that it can use that private type but gets:

```
[22:32:12] fail: [FAIL] DispatchProxyTests.DispatchProxyTests.Create_Using_PrivateProxy
[22:32:12] info: System.MethodAccessException : Method `TestType_PrivateProxy+InvokeProxy`1[TestType_IHelloService]..ctor()' is inaccessible from method `generatedProxy_2..ctor(System.Reflection.MethodInfo[])'
[22:32:12] info:    at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
[22:32:12] info:    at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[22:32:12] info:    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[22:32:12] info:    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
[22:32:12] info:    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
[22:32:12] info:    at System.Activator.CreateInstance(Type type, Object[] args)
[22:32:12] info:    at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(Type baseType, Type interfaceType)
[22:32:12] info:    at System.Reflection.DispatchProxy.Create[TestType_IHelloService,InvokeProxy`1]()
[22:32:12] info:    at TestType_PrivateProxy.Proxy[TestType_IHelloService]()
[22:32:12] info:    at DispatchProxyTests.DispatchProxyTests.Create_Using_PrivateProxy()
[22:32:12] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

note: [Tests are currently in PR](https://github.com/dotnet/runtime/pull/47903)

### PR DESCRIPTION
**Pull request by lambdageek**
System.Runtime.CompilerServices.IgnoresAccessChecksToAttribute is like the reverse of
InternalsVisibleTo - it's added to an assembly to indicate that that
assembly can call non-public methods from the specified assembly.

The interesting thing is that the DynamicProxy dynamically generates
the attribute, so it is not explicitly declared in CoreLib.

Fixes https://github.com/dotnet/runtime/issues/47989

### CODE REVIEW

File: src/mono/mono/metadata/class.c [hunk 1]
```diff
@@ -5855,6 +5855,26 @@ is_valid_family_access (MonoClass *access_klass, MonoClass *member_klass, MonoCl
...
+		return TRUE;
+	if (!accessing || !accessed)
+		return FALSE;
+
+	mono_assembly_load_friends (accessing);
+	for (GSList *tmp = accessing->ignores_checks_assembly_names; tmp; tmp = tmp->next) {
+		MonoAssemblyName *victim = (MonoAssemblyName *)tmp->data;
+		if (!victim->name)
+			continue;
+		if (g_ascii_strcasecmp (accessed->aname.name, victim->name))
```
Comment (CoffeeFlux) [inline src/mono/mono/metadata/class.c:5871]: Purely a nit, but isn't this cleaner by just writing `if (!condition) return`? The continue seems odd.

File: src/mono/mono/metadata/assembly.c [hunk 2]
```diff
@@ -2126,7 +2126,11 @@ mono_assembly_load_friends (MonoAssembly* ass)
 	}
 	mono_assemblies_unlock ();
 
-	list = NULL;
+	GSList *visible_list;
```
Comment (CoffeeFlux) [inline src/mono/mono/metadata/assembly.c:2129]: Another nit, but you can just initialize these to NULL on the same line.

**Review by CoffeeFlux — APPROVED** [review]

File: src/mono/mono/metadata/class.c [hunk 3]
```diff
@@ -5855,6 +5855,26 @@ is_valid_family_access (MonoClass *access_klass, MonoClass *member_klass, MonoCl
 	return TRUE;
 }
 
+static gboolean
+ignores_access_checks_to (MonoAssembly *accessing, MonoAssembly *accessed)
+{
+	if (accessing == accessed)
+		return TRUE;
```
Comment (lambdageek) [inline src/mono/mono/metadata/class.c:5862]: Hmm.  I dont' think this is right.  I think this will make all `private` members accessible.

Comment (CoffeeFlux) [reply src/mono/mono/metadata/class.c:5862]: Wouldn't `can_access_internals` be broken too then?

Comment (lambdageek) [reply src/mono/mono/metadata/class.c:5862]: No because `can_access_internals` is only called for `internal` or `protected` or `private protected`.  IgnoresAccessChecks is actually more powerful (c.f. the re-enabled tests) it will let you reach in to get `private` methods too.

Comment (CoffeeFlux) [reply src/mono/mono/metadata/class.c:5862]: I would be somewhat surprised if that did not trigger a test failure, but maybe it's disabled for other reasons. If a test like that does not exist, it also might be worth explicitly adding one.

Comment (lambdageek) [reply src/mono/mono/metadata/class.c]: Working on adding one.  I coudln't find aything like it.  There's not a lot of mentions of MethodAccessException in the codebase!

Comment (lambdageek) [reply src/mono/mono/metadata/class.c]: Added 2 more tests.  Now we check that calling `internal`/`private` methods across assemblies throws a `MethodAccessException` and that calling a `private` method in the same assembly also throws.

**Comment by krwq** [comment]
Thank you @lambdageek!
