### PR TITLE
Fix typing of BlendVariableMask condition when optimizing TernaryLogic

### LINKED ISSUE #114572: JIT: Debug/Release generate different results
```
// Generated by Fuzzlyn v2.5 on 2025-04-11 19:29:41
// Run on X64 Windows
// Seed: 557319528607462789-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86avx512fx64,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 41.1 KiB to 0.7 KiB in 00:01:23
// Debug: Outputs <0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1>
// Release: Outputs <0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1>
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static Vector256<ushort> s_2;
    public static ushort s_4;
    public static void Main()
    {
        var vr11 = Vector256.Create<ushort>(0);
        var vr12 = Vector256.Create<ushort>(1);
        var vr13 = (ushort)0;
        var vr14 = Vector256.CreateScalar(vr13);
        var vr15 = (ushort)1;
        var vr16 = Vector256.CreateScalar(vr15);
        var vr17 = Vector256.Create<ushort>(s_4);
        var vr18 = Avx2.Max(vr16, vr17);
        s_2 = Avx512F.VL.TernaryLogic(vr11, vr12, Avx512BW.VL.CompareGreaterThanOrEqual(vr14, vr18), 216);
        System.Console.WriteLine(s_2);
    }
}
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=1013771&view=ms.vss-build-web.run-extensions-tab

@dotnet/jit-contrib @dotnet/intel

### PR DESCRIPTION
**Pull request by BruceForstall**
TernaryLogic nodes normalize small types to large types. When optimizing a TernaryLogic node to a BlendVariableMask, if we leave the normalized type, then the Blend uses the wrong instruction.

To fix this, change the Blend node to use the mask simd base type. We only do this for mask base types that are small, which is unsatisfying: there exists codegen today for double->int casts, for example, that uses a 'double' type mask but an 'int' sized TernaryLogic node. This works because we end up only using lane '0', as the vector is converted to scalar. I didn't find any other case like this, so hopefully if the mask type is small we can safely use it.

Fixes #114572

### CODE REVIEW

**Comment by BruceForstall** [comment]
Looks like this optimization logic originated in https://github.com/dotnet/runtime/pull/97468

**Comment by BruceForstall** [comment]
@tannergooding PTAL
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
cc @dotnet/intel

File: src/coreclr/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -3875,6 +3875,28 @@ GenTree* Lowering::LowerHWIntrinsicTernaryLogic(GenTreeHWIntrinsic* node)
...
+                // The condition mask element size is expected to be the same size as the TernaryLogic
+                // node element size, unless the condition element size is short, in which case the
+                // TernaryLogic node element size would have been normalized.
+                // However, there is code, such as for double->int conversions, that generates a 'double'
+                // base type mask for a TernaryLogic node with base type 'int'. That works because it only
+                // cares about the '0' elem, as the result will be cast to scalar.
+                var_types conditionBaseType = condition->AsHWIntrinsic()->GetSimdBaseType();
+                uint32_t  conditionElemSize = genTypeSize(conditionBaseType);
+                uint32_t  elemSize          = genTypeSize(simdBaseType);
+                if (varTypeIsShort(conditionBaseType) && (conditionElemSize < elemSize))
```
Comment (saucecontrol) [inline src/coreclr/jit/lowerxarch.cpp:3894]: Shouldn't this be checking `varTypeIsSmall`?  Same problem can happen with a byte compare.

Simplified repro:

```cs
public class Runtime_114572
{
    public static byte s_ub;
    public static ushort s_us;

    public static void Problem1()
    {
        var v0 = Vector128<ushort>.Zero;
        var v1 = Vector128<ushort>.One;
        var vs = Vector128.Create(s_us);

        var vr = Avx512F.VL.TernaryLogic(v0, v1, Avx512BW.VL.CompareGreaterThanOrEqual(v0, vs), 216);
        Console.WriteLine(vr);
    }

    public static void Problem2()
    {
        var v0 = Vector128<byte>.Zero;
        var v1 = Vector128<byte>.One;
        var vs = Vector128.Create(s_ub);

        var vr = Avx512F.VL.TernaryLogic(v0, v1, Avx512BW.VL.CompareGreaterThanOrEqual(v0, vs), 216);
        Console.WriteLine(vr);
    }
}
```

Though I'm not sure it's not always wrong to allow a larger blend when the condition element size was smaller.

Notably, the TernaryLogic nodes mentioned in the comment (from cast normalization lowering) are gone in the rewrite I did in #114410.  If anything, they should have been ConditionalSelect nodes so that they wouldn't have required transformation back to mask blend, but `GT_SELECT` ended up being more efficient since the result is a scalar anyway.

Comment (BruceForstall) [reply src/coreclr/jit/lowerxarch.cpp]: > Shouldn't this be checking `varTypeIsSmall`? Same problem can happen with a byte compare.

Indeed. Fixed.

I added your byte test case (and simplified ushort case as well).

**Comment by BruceForstall** [comment]
[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1021438&view=ms.vss-build-web.run-extensions-tab)

File: src/coreclr/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -3875,6 +3875,28 @@ GenTree* Lowering::LowerHWIntrinsicTernaryLogic(GenTreeHWIntrinsic* node)
...
+                NamedIntrinsic intrinsicId = node->GetHWIntrinsicId();
+                assert(HWIntrinsicInfo::NeedsNormalizeSmallTypeToInt(intrinsicId));
+
+                // The condition mask element size is expected to be the same size as the TernaryLogic
+                // node element size, unless the condition element size is short, in which case the
+                // TernaryLogic node element size would have been normalized.
+                // However, there is code, such as for double->int conversions, that generates a 'double'
+                // base type mask for a TernaryLogic node with base type 'int'. That works because it only
+                // cares about the '0' elem, as the result will be cast to scalar.
+                var_types conditionBaseType = condition->AsHWIntrinsic()->GetSimdBaseType();
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:3891]: Don't think this is quite correct. We only require that `condition` produce `TYP_MASK` which could include things like `LCL_VAR` (such as from some CSE'd node).

In general we should also likely be doing this for all scenarios and only making the swap if `condition is TYP_MASK` and if we know the base type that the mask produced.

Consider for example the following where the `mask` will be `TYP_UINT` but the `TernaryLogic` node is `TYP_ULONG`, so we'd end up ignoring half the mask bits.
```csharp
var v0 = Vector128.Create<ulong>(x);
var v1 = Vector128.Create<ulong>(y);
var v2 = Vector128.Create<uint>(z);
var v3 = Vector128.Create<uint>(w);

var vr = Avx512F.VL.TernaryLogic(v0, v1, Avx512F.VL.CompareGreaterThanOrEqual(v2, v3).AsUInt64(), 0xE4);
```

This means that any scenario where the type of the mask is smaller than the size of the ternary logic node, we need to retype to the smaller type (as more mask bits are present). You also need to consider the other scenario, where if the mask is larger than the size of the ternary logic node we'd also need to retype (as fewer mask bits are present).

This is why normally we strictly require that `maskSize == operSize`. The case of a `TernaryLogic representing ConditionalSelect` is then special because it is bitwise and so equates to `BlendVariableMask` based on the base type of the mask.

Comment (BruceForstall) [reply src/coreclr/jit/lowerxarch.cpp:3891]: I don't think I understand the implications of your comment. Should we simply give up on this optimization converting TernaryLogic to BlendVariableMask if the TernaryLogic and mask sizes are not equal?

In your example above, are you saying that we need to retype to the minimum of the mask and TernaryLogic node operation size, since no matter which is larger, the upper bits are garbage?

This code I added is trying to choose the correct BlendVariableMask operation size. Maybe after #114410 it can do this unconditionally by using the operand mask size. But maybe you're suggesting it should be unconditional based on the minimum of the sizes?

Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp:3891]: I'm saying that for `TernaryLogic (CndSel in particular) -> BlendVariableMask` you need to always take the base type of the condition, regardless of what the type of the `TernaryLogic` was

If the base type of the condition isn't known (i.e. it's a CSE'd TYP_MASK local), then we need to give up.

Comment (BruceForstall) [reply src/coreclr/jit/lowerxarch.cpp]: Ok, I changed this code to unconditionally use the 'condition' base element type, and bail if the condition is not a HW intrinsic. This leads to some asm diffs due to the cast typing issue in the comment, previously, but the functionality should be identical, since in the casting case, no matter the opmask size, we only use the lower dword in the end.

e.g., diffs:
```
<        vpblendmd xmm0 {k1}, xmm0, dword ptr [reloc @RWD64] {1to4}
>        vblendmps xmm0 {k1}, xmm0, dword ptr [reloc @RWD64] {1to4}
...
<       vpblendmd xmm0 {k1}, xmm0, dword ptr [reloc @RWD64] {1to4}
>       vblendmpd xmm0 {k1}, xmm0, qword ptr [reloc @RWD96] {1to2}
```

**Review by tannergooding — APPROVED** [review]
