### PR TITLE
Perform reachability analysis before codegen 

### LINKED ISSUE #66578: Assertion failed 'interval->isSpilled' during 'LSRA allocate'
### Description

The following program hits a JIT assert on arm32 when optimizing.

### Reproduction Steps

```csharp
// Generated by Fuzzlyn v1.5 on 2022-03-13 15:19:20
// Run on Arm Linux
// Seed: 13161118502102171269
// Reduced from 313.8 KiB to 1.2 KiB in 00:16:29
// Hits JIT assert in Release:
// Assertion failed 'interval->isSpilled' in 'Program:M52(C0)' during 'LSRA allocate' (IL size 103; hash 0xb4fc4553; FullOpts)
// 
//     File: /__w/1/s/src/coreclr/jit/lsra.cpp Line: 5924
// 
public interface I0
{
}

public interface I1
{
}

public class C0 : I0, I1
{
    public sbyte F0;
    public bool F1;
    public uint F2;
    public ushort F5;
    public C0(sbyte f0, bool f1, uint f2, ushort f5)
    {
        F0 = f0;
        F1 = f1;
        F2 = f2;
        F5 = f5;
    }
}

public class Program
{
    public static I1[][] s_18;
    public static ushort[][] s_43;
    public static I1 s_64;
    public static I0 s_88;
    public static void Main()
    {
        var vr6 = new C0(0, false, 0, 0);
        M52(vr6);
    }

    public static void M52(C0 argThis)
    {
        I1 vr9 = s_18[0][0];
        if (argThis.F1)
        {
            return;
        }

        if (argThis.F1)
        {
            try
            {
                s_43 = new ushort[][]{new ushort[]{0}};
            }
            finally
            {
                for (int var8 = 0; var8 < 2; var8++)
                {
                    s_64 = argThis;
                }

                C0 vr10 = new C0(0, true, 0, 0);
                s_88 = new C0(-1, true, 0, 0);
            }

            I1 vr12 = s_18[0][0];
        }
    }
}
```

### Expected behavior

No assert hit.

### Actual behavior

Assert hit.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

category:correctness
theme:register-allocator

### PR DESCRIPTION
**Pull request by kunalspathak**
Perform reachability analysis one last time before doing code gen to eliminate unreachable blocks. 

While investigating, #66578, I noticed that there was lot of dead blocks that were kept around and that keeps variables alive longer and creating unnecessary refpositions. Having extra refpositions is not problematic, but the liveness of variables was not tracked correctly because of unreachable blocks. The liveness of variables decides if an interval should be spilled or not. As seen in my analysis in https://github.com/dotnet/runtime/issues/66578#issuecomment-1069769609, there were 3 refpositions (def, use, use) created for the problematic variable, but because of missing liveness, both the uses were marked as `lastUse` leading to making the interval as inactive instead of spilled.

In this PR, I have added the `computeReachability()` phase after all the optimizations are done so it can remove any unreachable blocks. It performs the block renumbering, but since LSRA is sensitive to block renumbering (see https://github.com/dotnet/runtime/issues/66994), I didn't want to see its impact as part of this change. Hence, I have added an option to skip the block renumbering in the final phase.

PIN numbers on windows/x64 SPMI

| Collection | Base          | Diff          | % diff |
|------------|---------------|---------------|--------|
| libraries  | 1392303237458 | 1393889260100 | 0.11%  |
| benchmarks | 328547820836  | 328920196300  | 0.11%  |

Also emit the block size after every block in order to spot the code size diff at block level.

Fixes: https://github.com/dotnet/runtime/issues/66578

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/compiler.cpp [hunk 1]
```diff
@@ -4944,6 +4945,16 @@ void Compiler::compCompile(void** methodCodePtr, uint32_t* methodCodeSize, JitFl
...
 
+    //
+    // Compute reachability and remove unreachable blocks, if any.
+    //
+    auto computeReachability = [this]() {
+
+        EnsureBasicBlockEpoch();
+        fgComputeReachability(/* computeDoms */ false, /* doRenumbering */ false);
+    };
+    DoPhase(this, PHASE_COMPUTE_REACHABILITY, computeReachability);
```
Comment (AndyAyersMS) [inline src/coreclr/jit/compiler.cpp:4956]: I would use a different local name and a different phase name (reusing a phase name likely messes up some stats computations).

**Review by AndyAyersMS — COMMENTED** [review]
Are you actually removing the blocks anywhere?

`fgComputeReachability` is not particularly efficient (it blindly unions all preds instead of just the ones with updates).

It is overkill for what I think you are looking for here -- you only want to know if a block A is reachable from method entry, not whether block A is reachable from block B.

`fgComputeReachability` also updates the gc safe block flags, which, while likely harmless is probably not something we want to be doing.

So I think you can get this information more cheaply and with less collateral impact.

File: src/coreclr/jit/compiler.cpp [hunk 2]
```diff
@@ -4769,7 +4769,8 @@ void Compiler::compCompile(void** methodCodePtr, uint32_t* methodCodeSize, JitFl
 
         // Compute reachability sets and dominators.
         //
-        DoPhase(this, PHASE_COMPUTE_REACHABILITY, &Compiler::fgComputeReachability);
```
Comment (BruceForstall) [inline src/coreclr/jit/compiler.cpp:4772]: Why does this need to change?

File: src/coreclr/jit/emit.cpp [hunk 3]
```diff
@@ -6556,7 +6556,8 @@ unsigned emitter::emitEndCodeGen(Compiler* comp,
 #ifdef DEBUG
         if (emitComp->opts.disAsm || emitComp->verbose)
         {
-            printf("\t\t\t\t\t\t;; bbWeight=%s PerfScore %.2f", refCntWtd2str(ig->igWeight), ig->igPerfScore);
+            printf("\t\t\t\t\t\t;;  size=%d   bbWeight=%s PerfScore %.2f", ig->igSize, refCntWtd2str(ig->igWeight),
```
Comment (BruceForstall) [inline src/coreclr/jit/emit.cpp:6559]: nit: why so much whitespace?

File: src/coreclr/jit/fgopt.cpp [hunk 4]
```diff
@@ -351,7 +351,10 @@ void Compiler::fgComputeReturnBlocks()
 // to avoid creating "retless" calls, since we need the BBJ_ALWAYS for the purpose
 // of unwinding, even if the call doesn't return (due to an explicit throw, for example).
 //
-void Compiler::fgComputeEnterBlocksSet()
+// Arguments:
+//    renumberingDone -- `true` if block renumbering was done.
+//
+void Compiler::fgComputeEnterBlocksSet(DEBUG_ARG1(const bool renumberingDone))
```
Comment (BruceForstall) [inline src/coreclr/jit/fgopt.cpp:357]: This is kind of annoying (adding an arg just for this). Why not just remove the offending assert instead? Doesn't seem like it has much value anyway.

File: src/coreclr/jit/fgopt.cpp [hunk 5]
```diff
@@ -543,10 +546,14 @@ bool Compiler::fgRemoveUnreachableBlocks()
 // Also, compute the list of return blocks `fgReturnBlocks` and set of enter blocks `fgEnterBlks`.
 // Delete unreachable blocks.
 //
+//  Arguments:
+//       computeDoms - Whether to compute doms or not.
```
Comment (BruceForstall) [inline src/coreclr/jit/fgopt.cpp:550]: It would be useful to understand (and add to this comment block) when renumbering is required, and why. And when it is not. Same for creating doms.

**Review by BruceForstall — CHANGES_REQUESTED** [review]

**Comment by kunalspathak** [comment]
> Are you actually removing the blocks anywhere?

Yes, after it tracks the `bbReach` it uses it to determine (by referring the `fgEnterBlks`) whether to remove it or not, but I agree with you. I can do `bbReach` or equivalent calculation cheaper. Let me work on it.

https://github.com/dotnet/runtime/blob/8b42dffa5f37762caddbe949ebc2fc348cca5121/src/coreclr/jit/fgopt.cpp#L455-L464

**Comment by kunalspathak** [comment]
@AndyAyersMS - Just to answer your original question, yes it does remove block in that method as seen [in asmdiffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1675329&view=ms.vss-build-web.run-extensions-tab).

**Comment by kunalspathak** [comment]
I have verified the diffs between the new implementation and previous (exhaustive) implementation and there is no diff.

**Review by AndyAyersMS — COMMENTED** [review]
I think the approach is good.

I have one question and also wondered if you had new TP measurements.

File: src/coreclr/jit/fgopt.cpp [hunk 6]
```diff
@@ -624,6 +641,97 @@ void Compiler::fgComputeReachability()
...
+
+    // A block is unreachable if no path was found from
+    // any of the fgFirstBB, handler, filter or BBJ_ALWAYS (Arm) blocks.
+    auto isBlockRemovable = [&](BasicBlock* block) -> bool {
+        return !BlockSetOps::IsMember(this, visitedBlocks, block->bbNum);
+    };
+
+    unsigned passNum = 1;
+    bool     changed;
+    do
```
[the remark this answers is not in the document]
Comment (kunalspathak) [reply src/coreclr/jit/fgopt.cpp:711]: I need to double check. I was trying to be conservative and reuse the same logic we have in reachability, but may be the way I am calling reachability here, another iteration might not be needed.

**Comment by kunalspathak** [comment]
I guess there are superpmi replay for linux-arm failures that I need to look into.

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66967-merge-88ab271474c44ff7ab/unix-arm-1/1/console.33965e13.log?sv=2019-07-07&se=2022-04-12T07%3A25%3A15Z&sr=c&sp=rl&sig=K9oClcSFxxSXGc4cuE6aKs4EUpOU9DzkcMyRZ6OKLWM%3D

File: src/coreclr/jit/fgopt.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (BruceForstall) [reply src/coreclr/jit/fgopt.cpp:711]: Since you aren't recomputing reachability each loop, it seems that iterating won't have an effect anyway.

**Comment by kunalspathak** [comment]
Latest pin numbers on superpmi libraries_pmi collection:

```
Before: 327744184719
After: 328136546105
Diff: 0.12%
```

File: src/coreclr/jit/fgopt.cpp [hunk 7]
```diff
@@ -624,6 +643,95 @@ void Compiler::fgComputeReachability()
...
+#if defined(FEATURE_EH_FUNCLETS) && defined(TARGET_ARM)
+    // For ARM code, prevent creating retless calls by adding the BBJ_ALWAYS to the "fgAlwaysBlks" list.
+    for (BasicBlock* const block : Blocks())
+    {
+        if (block->bbJumpKind == BBJ_CALLFINALLY)
+        {
+            assert(block->isBBCallAlwaysPair());
+
+            // Don't remove the BBJ_ALWAYS block that is only here for the unwinder.
+            worklist.insert(worklist.end(), block->bbNext);
```
Comment (BruceForstall) [inline src/coreclr/jit/fgopt.cpp:676]: this could also be:
```suggestion
            worklist.push_back(block->bbNext);
```
?

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/jit/fgopt.cpp (hunk 7 above)
Comment (kunalspathak) [reply src/coreclr/jit/fgopt.cpp:676]: ah missed this one.

**Comment by kunalspathak** [comment]
failure related to https://github.com/dotnet/runtime/issues/59542

**Comment by EgorBo** [comment]
Improvements in System.Text.Json.Tests.Perf_Booleans https://github.com/dotnet/perf-autofiling-issues/issues/4364 on x64
