### PR TITLE
JIT: Fix constrained call dereferences happening too early

### LINKED ISSUE #73615: JIT incorrectly reorders constrained call 'this' indirections with other arguments
Small example:
```csharp
using InlineIL;
using System;
using System.Runtime.CompilerServices;

public class Program
{
    public static void Main()
    {
        Foo(new C("A"));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Foo(C arg)
    {
        IL.Emit.Ldarga(nameof(arg));
        IL.Emit.Ldarga(nameof(arg));
        IL.Emit.Call(new MethodRef(typeof(Program), nameof(Bar)));
        IL.Emit.Constrained<C>();
        IL.Emit.Callvirt(new MethodRef(typeof(C), nameof(arg.Baz)));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static int Bar(ref C o)
    {
        o = new C("B");
        return 0;
    }
}

public record class C(string Name)
{
    public void Baz(int arg)
    {
        Console.WriteLine(Name);
    }
}
```
Expected: B
Actual: A

Seen in https://github.com/dotnet/runtime/issues/73606#issuecomment-1209210990

category:correctness
theme:importer
skill-level:intermediate
cost:small
impact:small

### PR DESCRIPTION
**Pull request by jakobbotsch**
Constrained calls in IL include an implicit dereference that occurs as part of the call. The JIT was adding this dereference on top of the 'this' argument tree, which makes it happen too early (before other arguments are evaluated). This changes the importer to spill when necessary to preserve ordering.

For:
```cil
  .method private hidebysig static void  Foo(class Runtime_73615/C arg) cil managed noinlining
  {
    // Code size       21 (0x15)
    .maxstack  2
    IL_0000:  ldarga.s   arg
    IL_0002:  ldarga.s   arg
    IL_0004:  call       int32 Runtime_73615::Bar(class Runtime_73615/C&)
    IL_0009:  constrained. Runtime_73615/C
    IL_000f:  callvirt   instance void Runtime_73615/C::Baz(int32)
    IL_0014:  ret
  }
```

Before:
```scala
***** BB01
STMT00000 ( 0x000[E-] ... 0x014 )
               [000003] --C-G------                         ▌  CALL nullcheck void   Runtime_73615+C:Baz(int):this
               [000004] n---G------ this                    ├──▌  IND       ref
               [000000] -----------                         │  └──▌  LCL_ADDR  long   V00 arg0         [+0]
               [000002] --C-G------ arg1                    └──▌  CALL      int    Runtime_73615:Bar(byref):int
               [000001] ----------- arg0                       └──▌  LCL_ADDR  byref  V00 arg0         [+0]
```

After:
```scala
***** BB01
STMT00000 ( 0x000[E-] ... 0x014 )
               [000005] -AC-G------                         ▌  ASG       int
               [000004] D------N---                         ├──▌  LCL_VAR   int    V02 tmp1
               [000002] --C-G------                         └──▌  CALL      int    Runtime_73615:Bar(byref):int
               [000001] ----------- arg0                       └──▌  LCL_ADDR  byref  V00 arg0         [+0]

***** BB01
STMT00001 ( ??? ... ??? )
               [000003] --C-G------                         ▌  CALL nullcheck void   Runtime_73615+C:Baz(int):this
               [000007] n---G------ this                    ├──▌  IND       ref
               [000000] -----------                         │  └──▌  LCL_ADDR  long   V00 arg0         [+0]
               [000006] ----------- arg1                    └──▌  LCL_VAR   int    V02 tmp1
```

Fix #73615

Some regressions/improvements are expected due to more spilling in these cases.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283284&view=ms.vss-build-web.run-extensions-tab).

cc @dotnet/jit-contrib PTAL @markples

**Comment by jakobbotsch** [comment]
Checked offline with @AlekseyTs and this needs to wait for a corresponding VB.NET compiler fix (C# compiler was already fixed). Will close this for now.

**Comment by BruceForstall** [comment]
> Checked offline with @AlekseyTs and this needs to wait for a corresponding VB.NET compiler fix (C# compiler was already fixed). Will close this for now.

Don't we need to support IL generated by older (unfixed) compilers?

**Comment by jakobbotsch** [comment]
> Don't we need to support IL generated by older (unfixed) compilers?

It's not that we do not support the IL, but currently we have a JIT bug that nondeterministically (depending on numbers of args, debug vs release) can sometimes evaluate things in the wrong order, and it just so happens that there is a VB.NET unit test that relies on one of these cases.
When we met about this we were ok with taking the JIT fix once the C# and VN compilers are fixed to emit correct IL for these patterns.

File: src/coreclr/jit/importercalls.cpp [hunk 1]
```diff
@@ -884,7 +884,21 @@ var_types Compiler::impImportCall(OPCODE                  opcode,
...
+    // constrained call 'this' is a byref that may need to be dereferenced.
+    // That dereference should happen _after_ all args, so we need to spill
+    // them if they can interfere.
+    bool hasThis;
+    hasThis = ((mflags & CORINFO_FLG_STATIC) == 0) && ((sig->callConv & CORINFO_CALLCONV_EXPLICITTHIS) == 0) &&
+              ((opcode != CEE_NEWOBJ) || (newobjThis != nullptr));
+
+    if (hasThis && (constraintCallThisTransform == CORINFO_DEREF_THIS))
+    {
+        impSpillSideEffects(false, CHECK_SPILL_ALL DEBUGARG(
```
Comment (markples) [inline src/coreclr/jit/importercalls.cpp:899]: I don't recall exactly what a "global effect" is in this context.  Could the same issue happen if the this pointer was from a loaded field rather than a local?

File: src/tests/JIT/Regression/JitBlue/Runtime_73615/Runtime_73615.cs [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+        Foo(new C(101));
+
+        if (Result == 100)
+        {
+            Console.WriteLine("PASS");
+        }
+        else
+        {
+            Console.WriteLine("FAIL: Got result {0}", Result);
+        }
```
Comment (markples) [inline src/tests/JIT/Regression/JitBlue/Runtime_73615/Runtime_73615.cs:25]: I think the autogenerated harness will already display failure information.

**Review by markples — APPROVED** [review]

File: src/coreclr/jit/importercalls.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/importercalls.cpp:899]: A global effect here means something that reads heap memory. We don't need to spill those because inserting an indirection doesn't modify global state.

The same issue can happen if the pointer is from a loaded field, but the spill here is still sufficient (anything that can modify global memory will be spilled even without `spillGlobEffects`).

Comment (markples) [reply src/coreclr/jit/importercalls.cpp:899]: 👍
