### PR TITLE
Fix empty ParamName in ArgumentException

### LINKED ISSUE #15028: [netcore] Make System.Reflection.Tests.TypeInfoTests.IsEnumDefined_Invalid Pass
The test currently fails with:

```
System.Reflection.Tests.TypeInfoTests.IsEnumDefined_Invalid [FAIL]
      Assert.Equal() Failure
                ↓ (pos 0)
      Expected: 
      Actual:   enumType
                ↑ (pos 0)
      Stack Trace:
           at System.AssertExtensions.Throws[ArgumentException](String paramName, Func`1 testCode)
           at System.Reflection.Tests.TypeInfoTests.IsEnumDefined_Invalid()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

### LINKED ISSUE #27491: IsEnumDefined throws an exception with empty ParamName
Hello,
could you please clarify why do we expect an exception with an empty `ParamName` according this TypeInfo test https://github.com/dotnet/corefx/blob/master/src/System.Reflection/tests/TypeInfoTests.cs#L462 ?

### PR DESCRIPTION
**Pull request by Youssef1313**
Not too much sure if this is correct to be honest.

Fixes #27491
Fixes https://github.com/mono/mono/issues/15028

### CODE REVIEW

**Comment by jkotas** [comment]
The `IsEnumDefined_Invalid` test needs a matching fix.

File: src/coreclr/src/vm/reflectioninvocation.cpp [hunk 1]
```diff
@@ -2397,7 +2397,7 @@ FCIMPL1(Object *, ReflectionEnum::InternalGetEnumUnderlyingType, ReflectClassBas
     VALIDATEOBJECT(target);
     TypeHandle th = target->GetType();
     if (!th.IsEnum())
-        FCThrowArgument(NULL, NULL);
+        FCThrowArgument(W("enumType"), NULL);
```
Comment (jkotas) [inline src/coreclr/src/vm/reflectioninvocation.cpp:2400]: The exception is still going to have misleading message with this change. You can move this check after `HELPER_METHOD_FRAME_BEGIN_RET_0` and use `COMPlusThrow` that lets you specify the message, like this:

```
    if (!th.IsEnum())
        COMPlusThrow(kArgumentException, W("Arg_MustBeEnum"));
```

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs [hunk 2]
```diff
@@ -471,10 +471,9 @@ public static void IsEnumDefined(object value, bool expected)
         }
 
         [Fact]
-        [ActiveIssue("https://github.com/mono/mono/issues/15028", TestRuntimes.Mono)]
         public void IsEnumDefined_Invalid()
         {
-            AssertExtensions.Throws<ArgumentException>("", () => typeof(NonGenericClassWithNoInterfaces).GetTypeInfo().IsEnumDefined(10));
+            AssertExtensions.Throws<ArgumentException>("enumType", () => typeof(NonGenericClassWithNoInterfaces).GetTypeInfo().IsEnumDefined(10));
```
Comment (jkotas) [inline src/libraries/System.Reflection/tests/TypeInfoTests.cs:476]: The implementation has another path for string. It would be nice to add a test for:
`typeof(NonGenericClassWithNoInterfaces).GetTypeInfo().IsEnumDefined("10")`

and make sure that the exception is same for it.

File: src/coreclr/src/vm/reflectioninvocation.cpp (hunk 1 above)
Comment (Youssef1313) [reply src/coreclr/src/vm/reflectioninvocation.cpp:2400]: Sorry if it looks a very basic question, I'm not very expert. But, where the ParamName ("enumType") will be specified with the use of `COMPlusThrow`?

Comment (jkotas) [reply src/coreclr/src/vm/reflectioninvocation.cpp:2400]: I have edited the suggestion

File: src/libraries/System.Reflection/tests/TypeInfoTests.cs [hunk 3]
```diff
@@ -471,10 +471,10 @@ public static void IsEnumDefined(object value, bool expected)
...
+            AssertExtensions.Throws<ArgumentException>("enumType", () => typeof(NonGenericClassWithNoInterfaces).GetTypeInfo().IsEnumDefined("10"));
```
Comment (jkotas) [inline src/libraries/System.Reflection/tests/TypeInfoTests.cs:477]: If I am reading the code correctly, this is going to fail (the argument name is not going to be `enumType`).

It may be best to do the check on the managed side in C#, for both cases. And change the `FCThrowArgument` in the unmanaged implementation to just `_ASSERTE(th.IsEnum())`. More code in C# is good, one line at a time :-)

```
            if (!IsEnum)
                throw new ArgumentException(SR.Arg_MustBeEnum, "enumType");
```

Comment (Youssef1313) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:477]: @jkotas, Looking at [Type.Enum.cs](https://github.com/dotnet/runtime/blob/0a2f0e6da98a784601b37d19417b930a33b2c478/src/libraries/System.Private.CoreLib/src/System/Type.Enum.cs#L26), the check is there. Not sure how it didn't throw in that line and the code flow went to the cpp implementation. I'm not very familiar with the code base, so excuse me if the question is looking trivial.

Comment (Youssef1313) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:477]: Oh, got it. The check exists in Type.Enum.cs but is missing in RuntimeType.cs, will fix that.

Comment (Youssef1313) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:477]: @jkotas, A side question, should **all** argument exceptions through the code base have ParamName specified? or there are cases where it shouldn't be specified?

Comment (jkotas) [reply src/libraries/System.Reflection/tests/TypeInfoTests.cs:477]: There are cases where it does not make sense. For example, if there are multiple arguments and it is not clear which one to blame for having wrong value.

**Comment by jkotas** [comment]
`src/libraries/System.Private.CoreLib/src/System/RuntimeType.cs(239,1): error SA1028: Code should not contain trailing whitespace`

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by jkotas** [comment]
More tests nee updating:
```
 Starting:    System.ComponentModel.TypeConverter.Tests (parallel test collections = on, max threads = 2)
    System.ComponentModel.Tests.EnumConverterTests.ConvertTo_WithContext_Negative [FAIL]
      Assert.Equal() Failure
      Expected: (null)
      Actual:   enumType
      Stack Trace:
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(63,0): at System.AssertExtensions.Throws[T](String netCoreParamName, String netFxParamName, Func`1 testCode)
        /_/src/libraries/System.ComponentModel.TypeConverter/tests/EnumConverterTest.cs(112,0): at System.ComponentModel.Tests.EnumConverterTests.ConvertTo_WithContext_Negative()
  Finished:    System.ComponentModel.TypeConverter.Tests
```

**Comment by jkotas** [comment]
Infrastructure network errors:
```
[Users/runner/runners/2.168.2/work/1/s/.dotnet/sdk/5.0.100-preview.5.20251.2/NuGet.targets(128,5): error : Failed to retrieve information about 'Microsoft.Private.Corefx.NETCoreApp' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1a5f89f6-d8da-4080-b15f-242650c914a8/nuget/v3/flat2/microsoft.private.corefx.netcoreapp/index.json'. [/Users/runner/runners/2.168.2/work/1/s/src/libraries/restore/runtime/runtime.depproj]
/Users/runner/runners/2.168.2/work/1/s/.dotnet/sdk/5.0.100-preview.5.20251.2/NuGet.targets(128,5): error :   nodename nor servname provided, or not known [/Users/runner/runners/2.168.2/work/1/s/src/libraries/restore/runtime/runtime.depproj]
```

**Comment by jkotas** [comment]
Thank you!
