### PR TITLE
Fix ISA check in Runtime_107146 test

### LINKED ISSUE #107519: Test failure in Runtime_107146 with `DOTNET_EnablePOPCNT=0`
Pipeline: runtime-coreclr jitstress-isas-x86
Job: Many (all?) the "nopopcnt" jobs
Test: JIT/Regression/JitBlue/Runtime_107146/Runtime_107146/Runtime_107146.dll

E.g.,
```
set DOTNET_TieredCompilation=0
set DOTNET_EnablePOPCNT=0
set DOTNET_JitStress=1
```

```
22:35:58.700 Running test: JIT/Regression/JitBlue/Runtime_107146/Runtime_107146/Runtime_107146.dll
<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>
0
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Runtime_107146.TestEntryPoint()
   at Program.<<Main>$>g__TestExecutor109|0_110(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
22:35:59.214 Failed test: JIT/Regression/JitBlue/Runtime_107146/Runtime_107146/Runtime_107146.dll
```

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/107519

### CODE REVIEW

File: src/tests/JIT/Regression/JitBlue/Runtime_107146/Runtime_107146.cs [hunk 1]
```diff
@@ -28,7 +28,7 @@ public class Runtime_107146
     [Fact]
     public static void TestEntryPoint()
     {
-        if (!Avx512BW.VL.IsSupported)
+        if (!Avx512BW.VL.IsSupported || !Popcnt.IsSupported)
```
Comment (tannergooding) [inline src/tests/JIT/Regression/JitBlue/Runtime_107146/Runtime_107146.cs:31]: nit: Most of the other regression tests don't try to early exit; specifically because this is somewhat of an anti-pattern and trivially breaks across refactorings or misses cases like this.

Instead, we should be doing
```csharp
if (Avx512BW.VL.IsSupported)
{
    // Avx512BW usage, which also implies everything that is in the ISA hierarchy, such as popcnt
}
```

**Review by tannergooding — APPROVED** [review]

File: src/tests/JIT/Regression/JitBlue/Runtime_107146/Runtime_107146.cs [hunk 2]
```diff
@@ -28,21 +28,19 @@ public class Runtime_107146
     [Fact]
     public static void TestEntryPoint()
     {
-        if (!Avx512BW.VL.IsSupported)
+        if (Avx512BW.VL.IsSupported) // Avx512BW implies Popcnt
```
Comment (jkotas) [inline src/tests/JIT/Regression/JitBlue/Runtime_107146/Runtime_107146.cs:31]: Where do we depend on the exact polarity of the branch?

Comment (EgorBo) [reply src/tests/JIT/Regression/JitBlue/Runtime_107146/Runtime_107146.cs]: @tannergooding actually it seems that `DOTNET_EnablePOPCNT=0` doesn't turn `AVX512BW` so we do need to check `Popcnt.IsSupported` explicitly here

Comment (tannergooding) [reply src/tests/JIT/Regression/JitBlue/Runtime_107146/Runtime_107146.cs]: > actually it seems that DOTNET_EnablePOPCNT=0 doesn't turn AVX512BW so we do need to check Popcnt.IsSupported explicitly here

👍. That's probably a missing implication we should fix in .NET 10 then.

`popcnt` is a bit different because for Intel it's formally part of `SSE4.2`, while AMD includes it as part of `SSE4a` (which is an AMD specific precursor to `SSE4.1` we don't expose).

It's identified by its own unique bit, but in effect you cannot have AVX or higher without it.

Comment (tannergooding) [reply src/tests/JIT/Regression/JitBlue/Runtime_107146/Runtime_107146.cs]: (No need to fix it in this PR, I'll log an issue and track getting it resolved separately)

**Review by tannergooding — APPROVED** [review]
