### PR TITLE
Use a separate thread for tiered compilation background work

### LINKED ISSUE #44211: [Perf] Widespread regressions after threadpool change
After https://github.com/dotnet/runtime/pull/43841, we are seeing widespread (about 40 tests) regress. Some of these are threading tests, but some seem to have little to do with threading, like https://github.com/DrewScoggins/performance-2/issues/3177. Below I have a link to a query that is all of the regressions and a few improvements that are linked to this change. We are seeing this across Windows x64, x86 and Ubuntu x64, and I will be updating this issue as we get the Windows x86, and Ubuntu x64 regressions categorized.

[Regression Query - Windows x64](https://github.com/DrewScoggins/performance-2/issues?q=is%3Aopen+is%3Aissue+label%3A%22Windows+10.0.18362%22+label%3Arefs%2Fheads%2Fmaster+label%3ARegression+sort%3Aupdated-desc+label%3Ax64+label%3A%22Needs+Transfer%22+label%3A%22ThreadPool+Change%22)

[Improvement Query - Windows x64](https://github.com/DrewScoggins/performance-2/issues?q=is%3Aopen+is%3Aissue+label%3A%22Windows+10.0.18362%22+label%3Arefs%2Fheads%2Fmaster+label%3AImprovement+sort%3Aupdated-desc+label%3Ax64+label%3A%22Needs+Transfer%22+label%3A%22ThreadPool+Change%22+)

### PR DESCRIPTION
**Pull request by kouvel**
- Makes it easier to manage how much time is spent for performing background work like rejitting and allows yielding more frequently with just Sleep without incurring thread pool overhead, which is useful in CPU-limited cases
- A min/max range is determined for how long background work will be done before yielding the thread. The max is the same as before, 50 ms. For now the min is `processor count` ms (capped to the max), such that in CPU-limited cases the thread would yield more frequently in order to not monopolize too much of the limited CPU resources for background work, and in cases with a larger number of processors where the background work is typically less intrusive to foreground work it would yield less frequently.
- At the same time, progress should be made on background work such that steady-state perf would be reached in reasonable time. Yielding too frequently can slow down the background work too much. The sleep duration is measured to identify oversubscribed situations to yield less frequently and make faster progress on the background work.
- Due to less time spent rejitting in some CPU-limited cases, steady-state performance may be reached a bit later in favor of smaller spikes along the way
- When the portable thread pool is enabled, a side effect of using a managed worker thread for tiering background work was that several GC-heavy microbenchmarks regressed. Tiering was the only thing using the thread pool in those tests and stack-walking the managed thread was slower due to the presence of GC refs. It's not too concerning, the benchmarks are just measuring something different from before, but in any case this change also resolves that issue. Fixes https://github.com/dotnet/runtime/issues/44211.

### CODE REVIEW

**Comment by kouvel** [comment]
#### MusicStore Windows affinity: 1 proc

Before
```
============= Startup Performance ============

Server start (ms):   457
1st Request (ms):    378
Total (ms):          835

========== Steady State Performance ==========

  Requests    Aggregate Time(ms)    Req/s   Req Min(ms)   Req Mean(ms)   Req Median(ms)   Req Max(ms)   SEM(%)
-----------   ------------------   ------   -----------   ------------   --------------   -----------   ------
    2-  100                 1047   465.57          1.73           2.15             1.80         17.26     8.46
  101-  250                 1366   470.16          1.76           2.13             1.82         39.01    11.67
  251-  500                 1919   452.32          1.43           2.21             1.70        126.60    22.62
  501-  750                 2651   341.64          1.23           2.93             1.37        126.52    26.84
  751- 1000                 3104   551.91          1.21           1.81             1.27        126.01    27.54
 1001- 1500                 3950   590.90          1.13           1.69             1.19        203.36    24.06
 1501- 2000                 4562   816.66          1.13           1.22             1.19          4.78     0.77
 2001- 3000                 5772   826.59          1.14           1.21             1.19          2.25     0.36
 3001- 5000                 8189   827.25          1.11           1.21             1.19          2.52     0.26
 5001-10000                14281   820.76          1.11           1.22             1.19          7.73     0.20
```

After
```
============= Startup Performance ============

Server start (ms):   466
1st Request (ms):    374
Total (ms):          840

========== Steady State Performance ==========

  Requests    Aggregate Time(ms)    Req/s   Req Min(ms)   Req Mean(ms)   Req Median(ms)   Req Max(ms)   SEM(%)
-----------   ------------------   ------   -----------   ------------   --------------   -----------   ------
    2-  100                 1054   460.95          1.74           2.17             1.80         19.82     9.28
  101-  250                 1354   501.21          1.73           2.00             1.78          9.51     3.58
  251-  500                 1872   482.59          1.51           2.07             1.68          7.27     3.55
  501-  750                 2300   584.15          1.47           1.71             1.52          6.67     2.69
  751- 1000                 2856   448.89          1.38           2.23             1.50          7.18     4.24
 1001- 1500                 3743   563.79          1.30           1.77             1.38         16.48     3.28
 1501- 2000                 4765   489.63          1.16           2.04             1.27         11.07     3.47
 2001- 3000                 6008   804.51          1.14           1.24             1.19          5.11     0.84
 3001- 5000                 8447   819.91          1.03           1.22             1.19          2.84     0.30
 5001-10000                14519   823.37          1.08           1.21             1.19          2.33     0.17
```

#### MusicStore Linux --cpuset-cpus=1

Before
```
============= Startup Performance ============

Server start (ms):  1019
1st Request (ms):    293
Total (ms):         1312

========== Steady State Performance ==========

  Requests    Aggregate Time(ms)     Req/s   Req Min(ms)   Req Mean(ms)   Req Median(ms)   Req Max(ms)   SEM(%)
-----------   ------------------   -------   -----------   ------------   --------------   -----------   ------
    2-  100                 1478    595.83          1.27           1.68             1.34         15.55    10.37
  101-  250                 1743    564.91          1.27           1.77             1.31         58.03    21.51
  251-  500                 2193    556.11          1.07           1.80             1.11         54.65    20.05
  501-  750                 2528    745.39          1.03           1.34             1.10         53.40    15.60
  751- 1000                 3002    527.89          0.82           1.89             1.04         53.85    21.84
 1001- 1500                 3537    933.26          0.77           1.07             0.83         55.08    14.04
 1501- 2000                 4054    967.10          0.73           1.03             0.79         52.34    14.08
 2001- 3000                 5067    988.04          0.68           1.01             0.72         56.17    10.85
 3001- 5000                 6557   1341.62          0.67           0.75             0.72          2.00     0.30
 5001-10000                10239   1358.02          0.67           0.74             0.72          2.22     0.18
```

After
```
============= Startup Performance ============

Server start (ms):  1025
1st Request (ms):    304
Total (ms):         1329

========== Steady State Performance ==========

  Requests    Aggregate Time(ms)     Req/s   Req Min(ms)   Req Mean(ms)   Req Median(ms)   Req Max(ms)   SEM(%)
-----------   ------------------   -------   -----------   ------------   --------------   -----------   ------
    2-  100                 1495    596.10          1.26           1.68             1.33         15.62    10.48
  101-  250                 1765    555.33          1.26           1.80             1.32          9.63     4.94
  251-  500                 2178    604.41          1.05           1.65             1.16          3.68     2.67
  501-  750                 2542    688.24          1.05           1.45             1.12         11.79     5.19
  751- 1000                 2987    560.69          0.90           1.78             2.08          9.78     2.93
 1001- 1500                 3572    854.85          0.79           1.17             0.85         14.11     4.00
 1501- 2000                 4102    944.62          0.75           1.06             0.83         10.81     3.28
 2001- 3000                 5194    915.07          0.68           1.09             0.78         10.63     2.58
 3001- 5000                 6659   1365.22          0.67           0.73             0.71          1.96     0.30
 5001-10000                10359   1351.50          0.68           0.74             0.72          2.41     0.21
```

#### MusicStore Linux --cpus=1

Before
```
============= Startup Performance ============

Server start (ms):  1009
1st Request (ms):    306
Total (ms):         1315

========== Steady State Performance ==========

  Requests    Aggregate Time(ms)    Req/s   Req Min(ms)   Req Mean(ms)   Req Median(ms)   Req Max(ms)   SEM(%)
-----------   ------------------   ------   -----------   ------------   --------------   -----------   ------
    2-  100                 1834   190.48          1.46           5.25             1.66        103.80    31.16
  101-  250                 2101   561.62          1.34           1.78             1.43         15.38     8.29
  251-  500                 2800   357.80          0.99           2.79             1.16        107.74    24.82
  501-  750                 3260   543.99          1.04           1.84             1.14        104.71    23.62
  751- 1000                 3768   492.22          0.88           2.03             1.05        109.44    25.01
 1001- 1500                 4420   765.76          0.89           1.31             1.08         20.41     6.90
 1501- 2000                 5078   760.81          0.84           1.31             1.05         21.16     7.49
 2001- 3000                 6318   806.30          0.92           1.24             0.97         21.58     5.36
 3001- 5000                 8918   769.09          0.92           1.30             1.05         23.24     3.70
 5001-10000                15282   785.76          0.86           1.27             0.99         23.13     2.44
```

After
```
============= Startup Performance ============

Server start (ms):   991
1st Request (ms):    302
Total (ms):         1293

========== Steady State Performance ==========

  Requests    Aggregate Time(ms)    Req/s   Req Min(ms)   Req Mean(ms)   Req Median(ms)   Req Max(ms)   SEM(%)
-----------   ------------------   ------   -----------   ------------   --------------   -----------   ------
    2-  100                 1502   471.88          1.51           2.12             1.65         18.35    10.84
  101-  250                 1790   521.18          1.43           1.92             1.51         23.63     9.68
  251-  500                 2420   397.07          1.30           2.52             1.48         57.73    17.26
  501-  750                 3045   399.72          1.31           2.50             1.43         58.17    17.55
  751- 1000                 3564   481.83          1.06           2.08             1.22         56.80    18.52
 1001- 1500                 4523   521.37          1.03           1.92             1.15         59.15    12.78
 1501- 2000                 5450   539.66          0.96           1.85             1.10         57.93    13.85
 2001- 3000                 6684   809.82          0.90           1.23             0.97         22.16     5.41
 3001- 5000                 9178   802.16          0.93           1.25             0.97         22.73     3.90
 5001-10000                15481   793.19          0.79           1.26             0.98         24.00     2.45
```

#### Other testing

- Ran CscRoslyn in CPU-limited cases, as it has a lot of methods to rejit, to verify that steady-state perf is reached in reasonable time. No change in startup or steady-state perf.
- Ran ASP.NET JsonPlatform in CPU-limited cases to look for regressions. Didn't see any unexpected differences, just the expected slight differences in rejit timing. No change in startup or steady-state perf.

**Comment by kouvel** [comment]
The diff of `tieredcompilation.cpp` is not well aligned, I have shared a [better-aligned diff](https://1drv.ms/u/s!AvtRwG9CobRTgvlvNuVpfJlL5VVLqw?e=MEW7dL), download and open in a browser.

File: src/coreclr/vm/tieredcompilation.cpp [hunk 1]
```diff
@@ -355,88 +392,190 @@ void WINAPI TieredCompilationManager::TieringDelayTimerCallback(PVOID parameter,
...
-        // Reschedule the timer if there has been recent tier 0 activity (when a new eligible method is called the first
-        // time) to further delay call counting
-        bool success = false;
-        EX_TRY
         {
-            if (ThreadpoolMgr::ChangeTimerQueueTimer(
-                    tieringDelayTimerHandle,
-                    g_pConfig->TieredCompilation_CallCountingDelayMs(),
-                    (DWORD)-1 /* Period, non-repeating */))
+            LockHolder tieredCompilationLockHolder;
```
Comment (noahfalk) [inline src/coreclr/vm/tieredcompilation.cpp:500]: I think there is a little race window between exiting the lock inside of DoBackgroundWork() and re-taking the lock here but maybe I've misunderstood:

1. [Background thread] Inside DoBackgroundWork() within lock - determine all methods have been jitted
2. [Background thread] Return true from DoBackgroundWork() and then switch out before reaching this lock
3. [Managed code thread] Run AsyncPromoteToTier1 which calls TryScheduleBackgroundWorkerWithoutGCTrigger_Locked(). This call will observe that s_isBackgroundWorkerProcessingWork = true so s_backgroundWorkAvailableEvent is not set
4. [Background thread] Enter lock here, set s_isBackgroundWorkerProcessingWork = false, wait on event which may not be signaled again.

File: src/coreclr/vm/tieredcompilation.cpp [hunk 2]
```diff
@@ -355,88 +392,190 @@ void WINAPI TieredCompilationManager::TieringDelayTimerCallback(PVOID parameter,
...
+        // The wait timed out, see if the worker can exit
+
+        LockHolder tieredCompilationLockHolder;
+
+        if (s_isBackgroundWorkerProcessingWork)
         {
-            return;
+            // The background worker got scheduled again just as the wait timed out. The event would have been signaled just
+            // after the wait had timed out, so reset it and continue processing work.
+            s_backgroundWorkAvailableEvent.Reset();
```
Comment (noahfalk) [inline src/coreclr/vm/tieredcompilation.cpp:526]: If we are going to manually reset the event in some cases is there a reason not to use a ManualResetEvent and Reset() it inside this lock always?

**Review by noahfalk — COMMENTED** [review]
There might be a little fishiness in the cross-thread signaling but other than that all looked good to me.

File: src/coreclr/vm/tieredcompilation.cpp (hunk 1 above)
Comment (kouvel) [reply src/coreclr/vm/tieredcompilation.cpp:500]: The conditions for doing background work are rechecked inside the lock below, so if something happens in-between it would observe that inside the lock below and continue processing work.

> 4. [Background thread] Enter lock here, set s_isBackgroundWorkerProcessingWork = false

This part shouldn't happen because at step 3 `m_countOfMethodsToOptimize` would become nonzero and that would be seen below.

File: src/coreclr/vm/tieredcompilation.cpp (hunk 2 above)
Comment (kouvel) [reply src/coreclr/vm/tieredcompilation.cpp:526]: Resetting manually would be more expensive than having it auto-reset. This reset is optional, it's a rare case where we know that the event is signaled unnecessarily and not doing the reset would cause the thread to loop an extra time, which would be more expensive unnecessarily. Auto-reset also feels more natural to me here, as in most cases, as it seems rare to me though valid, that one would want to unblock multiple waits on an event all at once.

**Comment by kouvel** [comment]
Rebased to fix conflicts

File: src/coreclr/vm/tieredcompilation.cpp (hunk 1 above)
Comment (noahfalk) [reply src/coreclr/vm/tieredcompilation.cpp:500]: Ah I think I follow now, this is a double checked lock pattern. the conditions evaluated above were just oportunistic and the precise checks are in the lock. Yep my mistake. I wouldn't have expected the performance needs of this code path to make that level of complexity worthwhile but if it matters no qualms from me.

File: src/coreclr/vm/tieredcompilation.cpp (hunk 2 above)
Comment (noahfalk) [reply src/coreclr/vm/tieredcompilation.cpp:526]: It is surprising to me to see AutoReset used as a perf-optimization to save the cost of the Reset() call in the common case. Given the asserts you needed to change in the event code I assume its a pattern not used anywhere else in the coreclr codebase. If the perf really matters then I don't mind going along but I would add more explanation in the comments about why it is written this way. I was quite puzzled by it : )

**Review by noahfalk — APPROVED** [review]
Looks good, thanks Kount!

File: src/coreclr/vm/tieredcompilation.cpp (hunk 1 above)
Comment (kouvel) [reply src/coreclr/vm/tieredcompilation.cpp:500]: It wasn't particularly optimized, the only reason for the unlocked checks above was to avoid the unnecessary `BackgroundJitStart/Stop` events that would be fired by `DoBackgroundWork` when there is no background work to do.

File: src/coreclr/vm/tieredcompilation.cpp (hunk 2 above)
Comment (kouvel) [reply src/coreclr/vm/tieredcompilation.cpp:526]: > It is surprising to me to see AutoReset used as a perf-optimization to save the cost of the Reset() call in the common case.

I didn't use it as an optimization, I used it naturally because to me AutoReset is the natural thing to use here by default and there would need to be a good reason to use ManualReset instead (not only because it is less optimal).

Comment (kouvel) [reply src/coreclr/vm/tieredcompilation.cpp:526]: Also the assertion that AutoReset events shouldn't be manually Reset is completely arbitrary and unnecessary restriction, as shown here there are sometimes good reasons to manually reset an AutoReset event.

Comment (noahfalk) [reply src/coreclr/vm/tieredcompilation.cpp:526]: I agree that it is unnecessary restriction, but the combination of my confusion, someone deliberately writing asserts to ensure it doesn't happen, and nobody else diverging from that pattern in the entire coreclr codebase is decent evidence that it is an established convention in place. Fwiw I would have found ManualResetEvent rather than AutoResetEvent to be the more natural primitive to use here but I only mention it to say I think its a matter of opinion. I view you as the owner of this code so I am fine to give your opinion the greater weight. My only request is to comment it because there is a decent chance others could find this confusing too.

Comment (kouvel) [reply src/coreclr/vm/tieredcompilation.cpp:526]: Sure I'll add a comment, but I don't think it should be necessary to add a comment every time one type of event is used over the other. If the type of event that is used works reasonably in the case where it is used and there is no particular logical reason to use the other type of event, then any established convention is maybe not very relevant for this type of thing. Conventions may be important for other things, I'm not aware of any strong convention regarding the type of event that is used, typically as far as I'm aware the type of event that makes sense to the author would be used, and unless there is a good reason to use one over the other that's totally fine.

Comment (noahfalk) [reply src/coreclr/vm/tieredcompilation.cpp:526]: > I don't think it should be necessary to add a comment every time one type of event is used over the other

That isn't what I am proposing, perhaps I explained badly. I am suggesting:
- If the person doing the code review found something confusing, there is an increased chance that other developers would react similarly. I'm saying I found this specific instance of using an AutoResetEvent confusing.
- Asserts in the codebase are a good indication of what some other developer thought was a useful invariant. Code changes that delete those asserts so they can change the invariant have increased risk of creating some confusion. The assert in this case was that AutoResetEvent will never be used in a scenario where it needs to be manually reset.

Hopefully that sounds more sensible now : )

Comment (kouvel) [reply src/coreclr/vm/tieredcompilation.cpp:526]: The existence of the assert and because of it, the call to Reset, may have caused extra confusion. For the comment maybe for now just a minimal comment indicating that any type of event could be logically used here without going into too much detail, hopefully that would suffice to alleviate some confusion. Hopefully it shouldn't be necessary to indicate that in the future where either type of event could be used.
