### PR TITLE
JIT: Kill assertions about struct local when skipping field stores in block morph

### LINKED ISSUE #113658: Faulty codegen SkipLocalsInit Nullable<T> default value arm64
### Description

A user of Npgsql ran into garbled nullable values on his M2.

The full context can be found here https://github.com/npgsql/npgsql/issues/6058#issuecomment-2734049925

### Reproduction Steps

```cs
using System;
using System.Runtime.CompilerServices;

// Necessary
[module: SkipLocalsInit]

static class Program
{
    public static void Main()
    {
        var i = 0;
        // Let the JIT tier up.
        while (true)
        {
            var data = FaultyDefaultNullable<long?>();
            var d = data.GetValueOrDefault();
            // We need to dirty the stack and make sure this won't be optimized out by doing GC.Keepalive.
            var iObject = (object)i;
            var dataObject = (object?)data;
            var dObject = (object?)d;
            var hasValueObject = (object?)data.HasValue;
            // Alternatively
            // Console.WriteLine("{0}: `{1}` / {2}, `{3}`", i, data, d, data.HasValue);

            if (d != 0)
            {
                Console.WriteLine($"Unexpected value: {d} / {d:X} / {d:b8}");
                throw new Exception("We are here");
            }

            GC.KeepAlive(iObject);
            GC.KeepAlive(dataObject);
            GC.KeepAlive(dObject);
            GC.KeepAlive(hasValueObject);

            i++;
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static T FaultyDefaultNullable<T>()
    {
        // When T is a Nullable<T> (and only in that case), we support returning null
        if (default(T) is null && typeof(T).IsValueType)
            return default!;

        throw new InvalidOperationException("Not nullable");
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static T OkDefaultNullable<T>() => default!;
}
```

### Expected behavior

**OkDefaultNullable**
```
; Assembly listing for method Program:OkDefaultNullable[System.Nullable`1[long]]():System.Nullable`1[long] (Tier1)
; Emitting BLENDED_CODE for generic ARM64 - Apple
; Tier1 code
; optimized code
; optimized using Synthesized PGO
; fp based frame
; partially interruptible
; with Synthesized PGO: fgCalledCount is 100
; No PGO data

G_M000_IG01:                ;; offset=0x0000
            stp     fp, lr, [sp, #-0x10]!
            mov     fp, sp
 
G_M000_IG02:                ;; offset=0x0008
            mov     w0, wzr
            mov     x1, xzr
 
G_M000_IG03:                ;; offset=0x0010
            ldp     fp, lr, [sp], #0x10
            ret     lr
 
; Total bytes of code 24
```

### Actual behavior

**FaultyDefaultNullable**
```
; Assembly listing for method Program:FaultyDefaultNullable[System.Nullable`1[long]]():System.Nullable`1[long] (Tier1)
; Emitting BLENDED_CODE for generic ARM64 - Apple
; Tier1 code
; optimized code
; optimized using Synthesized PGO
; fp based frame
; partially interruptible
; with Synthesized PGO: fgCalledCount is 100
; No PGO data

G_M000_IG01:                ;; offset=0x0000
            stp     fp, lr, [sp, #-0x20]!
            mov     fp, sp
 
G_M000_IG02:                ;; offset=0x0008
            mov     w0, wzr
            ldr     x1, [fp, #0x18]
 
G_M000_IG03:                ;; offset=0x0010
            ldp     fp, lr, [sp], #0x20
            ret     lr
 
; Total bytes of code 24
```

### Regression?

This code works in .NET 8.0, starts failing in 9.0 and onwards (also tested 10.0 preview 1)

### Known Workarounds

Remove SkipLocalsInit from Npgsql

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jakobbotsch**
If we skip storing a field local because we know it is dead, then assertions about the struct local are no longer valid, so invalidate them in that case.

Without this change we could end up using the assertion about the struct local to remove a future store to the particular field, which would leave no zeroing of that field, and would be observable.

Fix #113658

### CODE REVIEW

File: src/coreclr/jit/morphblock.cpp [hunk 1]
```diff
@@ -242,8 +242,6 @@ void MorphInitBlockHelper::PropagateBlockAssertions()
 //
 void MorphInitBlockHelper::PropagateExpansionAssertions()
 {
-    // Consider doing this for FieldByField as well
-    //
```
Comment (jakobbotsch) [inline src/coreclr/jit/morphblock.cpp:246]: We already do this for the individual fields in that case. And doing it for the base local is unlikely to help anything since the local should be morphed to its fields.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS @EgorBo 

[Very minor diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1041291&view=ms.vss-build-web.run-extensions-tab)

**Review by EgorBo — APPROVED** [review]

**Review by AndyAyersMS — APPROVED** [review]
