### PR TITLE
Reconcile handling of EH vars

### LINKED ISSUE #1786: Assertion failed 'varDsc->lvLiveInOutOfHndlr'
Test: JIT\Regression\CLR-x86-JIT\v1-m08\b12668\b12668

Windows x86 with:
```
COMPlus_JitStress=2
COMPlus_TieredCompilation=0
```

```
F:\gh\runtime2\artifacts\tests\coreclr\Windows_NT.x86.Checked\JIT\Regression\CLR-x86-JIT\v1-m08\b12668\b12668>F:\gh\runtime2\artifacts\tests\coreclr\Windows_NT.x86.Debug\Tests\Core_Root\CoreRun.exe F:\gh\runtime2\artifacts\tests\coreclr\Windows_NT.x86.Checked\JIT\Regression\CLR-x86-JIT\v1-m08\b12668\b12668\b12668.dll

Assert failure(PID 2116 [0x00000844], Thread: 10416 [0x28b0]): Assertion failed 'varDsc->lvLiveInOutOfHndlr' in 'DefaultNamespace.EAObject:Main(System.String[]):int' (IL size 617)

    File: F:\gh\runtime2\src\coreclr\src\jit\lsra.cpp Line: 1401
    Image: F:\gh\runtime2\artifacts\tests\coreclr\Windows_NT.x86.Debug\Tests\Core_Root\CoreRun.exe
```

E.g.,
https://dev.azure.com/dnceng/public/_build/results?buildId=483756&view=ms.vss-test-web.build-test-results-tab&runId=15357200&resultId=108519&paneView=debug

### PR DESCRIPTION
**Pull request by CarolEidt**
Modify `BasicBlock::hasEHBoundaryIn()` and `BasicBlock::hasEHBoundaryOut()` to reflect what liveness is doing, and change liveness to call those methods, and adjust the register allocator code appropriately.

It might make sense to extract the code that's basically the same, except that the register allocator doesn't need the `finallyVars` except as validation in the `DEBUG` case.

Fix #1786

### CODE REVIEW

**Comment by CarolEidt** [comment]
Also, fix `STRESS_RANDOM_INLINE` to work when set with `COMPlus_JitStressModeNames` not just with `COMPlus_JitStress`.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL - will still want to run stress testing on this if all the innerloop passes.

File: src/coreclr/src/jit/block.cpp [hunk 1]
```diff
@@ -1374,6 +1374,68 @@ BasicBlock* Compiler::bbNewBasicBlock(BBjumpKinds jumpKind)
...
+// isBBCallAlwaysPairLast: Determine if this is the last block of a BBJ_CALLFINALLY/BBJ_ALWAYS pari
+//
+// Return Value:
+//    True iff "this" is the last block of a BBJ_CALLFINALLY/BBJ_ALWAYS pair
+//    -- a block corresponding to an exit from the try of a try/finally.
+//
+// Notes:
+//    See notes on isBBCallAlwaysPair(), above.
+//
+bool BasicBlock::isBBCallAlwaysPairLast()
```
Comment (BruceForstall) [inline src/coreclr/src/jit/block.cpp]: I'm not too fond of "Last" in the name -- it seems ambiguous what it is last with respect to: last in the function?

How about "Tail" instead?

File: src/coreclr/src/jit/block.cpp [hunk 2]
```diff
@@ -1374,6 +1374,68 @@ BasicBlock* Compiler::bbNewBasicBlock(BBjumpKinds jumpKind)
...
+{
+    return (((bbFlags & BBF_KEEP_BBJ_ALWAYS) != 0) && (bbPreds != nullptr) && (bbPreds->flNext == nullptr) &&
```
Comment (BruceForstall) [inline src/coreclr/src/jit/block.cpp]: I think this would be better as:
```
return (bbPrev != nullptr) && bbPrev->isBBCallAlwaysPair();
```

There are other places that could use this, e.g. in optAddCopies:
```
#if defined(FEATURE_EH_FUNCLETS)
                    // With funclets, this is only used for BBJ_CALLFINALLY/BBJ_ALWAYS pairs. For x86, it is also used
                    // as the "final step" block for leaving finallys.
                    assert((block->bbPrev != nullptr) && block->bbPrev->isBBCallAlwaysPair());
#endif // FEATURE_EH_FUNCLETS
```

and EHSuccessorIterPosition:
```
        BasicBlock* beforeBlock = block->bbPrev;
        if (beforeBlock != nullptr && beforeBlock->isBBCallAlwaysPair())
        {
            m_curTry = nullptr;
        }
 ```

there are more.

File: src/coreclr/src/jit/liveness.cpp [hunk 3]
```diff
@@ -2411,37 +2411,23 @@ void Compiler::fgInterBlockLocalVarLiveness()
...
-        if (block->bbFlags & BBF_FUNCLET_BEG)
-        {
-            VarSetOps::UnionD(this, exceptVars, block->bbLiveIn);
-        }
-        if ((block->bbJumpKind == BBJ_EHFINALLYRET) || (block->bbJumpKind == BBJ_EHFILTERRET) ||
-            (block->bbJumpKind == BBJ_EHCATCHRET))
+        if (block->hasEHBoundaryOut())
         {
             VarSetOps::UnionD(this, exceptVars, block->bbLiveOut);
+            if (block->bbJumpKind == BBJ_EHFINALLYRET)
```
Comment (BruceForstall) [inline src/coreclr/src/jit/liveness.cpp]: You're no longer adding to `filterVars` for `BBJ_EHFILTERRET`.

File: src/coreclr/src/jit/liveness.cpp [hunk 4]
```diff
@@ -2411,37 +2411,23 @@ void Compiler::fgInterBlockLocalVarLiveness()
...
-
-            VarSetOps::UnionD(this, finallyVars, block->bbLiveOut);
-        }
-#if defined(FEATURE_EH_FUNCLETS)
-        // Funclets are called and returned from, as such we can only count on the frame
-        // pointer being restored, and thus everything live in or live out must be on the
-        // stack
-        if (block->bbFlags & BBF_FUNCLET_BEG)
-        {
-            VarSetOps::UnionD(this, exceptVars, block->bbLiveIn);
```
Comment (BruceForstall) [inline src/coreclr/src/jit/liveness.cpp]: You removed this, but the `hasEHBoundaryIn()` case above doesn't replace it for filter/finally/fault funclets.

**Review by BruceForstall — CHANGES_REQUESTED** [review]

**Comment by BruceForstall** [comment]
The liveness changes are nice (if complete), but not necessary to fix the bug that's making the CI pipelines fail. Could they be moved to a separate PR?

File: src/coreclr/src/jit/block.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/block.cpp]: Makes sense.

File: src/coreclr/src/jit/block.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/block.cpp]: I'll modify the condition - I think that using this in other places might be better left as a "clean up" PR that also includes the liveness changes.

File: src/coreclr/src/jit/liveness.cpp (hunk 3 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/liveness.cpp]: `filterVars` is not separately used, and can be combined with `exceptVars` since they are tested with an `||` condition.

File: src/coreclr/src/jit/liveness.cpp (hunk 4 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/liveness.cpp]: I believe that you had indicated to me that a block with `BBF_FUNCLET_BEG` set would always have `bbCatchTyp != BBCT_NONE`, so this was changed to an assert for the `hasEHBoundaryIn()` case - is there something else I've missed?

Comment (BruceForstall) [reply src/coreclr/src/jit/liveness.cpp]: Ah, right, I forgot about the special BBCT values for fault/finally/filter/filter-handler.

**Review by BruceForstall — APPROVED** [review]
