### PR TITLE
[hot_reload] Check for added fields earlier in compute_class_bitmap

### LINKED ISSUE #86172: [mono][hotreload] Adding a new field didn't work
Program.cs:
```
public class EntryPoint
{
	public static void Main(string[] args)
	{
		try
		{
			AddProperty1.Main2(); // line 7
			Console.Write("\f");
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
			throw;
		}
	}
}
```
OtherClass.cs
```
public class AddProperty1
{
	public static void Main2()
	{
	}
}
```
Add a breakpoint on line 7 of Program.cs.
Run the program, once it's paused, go to OtherClass.cs and replace the content to:

```
public class AddProperty1
{
	private static int A { get; set; }
	public static void Main2()
	{
		A = 11;
		System.Console.WriteLine(A);
	}
}
```

Mono runtime crashes:
image

`field->type is NULL`

### PR DESCRIPTION
**Pull request by lambdageek**
Added fields don't contribute to the class bitmap, and they also might not have their type resolved yet - move the "is from update" check before we need to access the field's type

Fixes https://github.com/dotnet/runtime/issues/86172

### CODE REVIEW

File: src/mono/mono/metadata/object.c [hunk 1]
```diff
@@ -834,6 +834,11 @@ compute_class_bitmap (MonoClass *klass, gsize *bitmap, int size, int offset, int
 		while ((field = mono_class_get_fields_internal (p, &iter))) {
 			MonoType *type;
 
+			/* metadadta-update: added fields aren't stored in the object, don't
```
Comment (vargaz) [inline src/mono/mono/metadata/object.c:837]: Typo.

**Review by vargaz — APPROVED** [review]

**Review by fanyang-mono — APPROVED** [review]
