### PR TITLE
JIT: Use 'compOpportunisticallyDependsOn' to determine if we can use ArmBase_Arm64_MultiplyLongAdd/MultiplyLongSub/MultiplyLongNeg intrinsics in lowering

### LINKED ISSUE #95081: Checked/Release asm diffs failure: Assertion failed 'compiler->compIsaSupportedDebugOnly(HWIntrinsicInfo::lookupIsa(intrin.id))'
SPMI checked/release asm diffs is failing with 4 asserts on linux-arm64, coreclr_tests.run.linux.arm64.checked.mch, e.g.:

```
ISSUE: <ASSERT> #329065 D:\a\_work\1\s\src\coreclr\jit\hwintrinsiccodegenarm64.cpp (210) - Assertion failed 'compiler->compIsaSupportedDebugOnly(HWIntrinsicInfo::lookupIsa(intrin.id))' in 'System.Collections.Generic.Dictionary`2[System.__Canon,System.__Canon]:TryInsert(System.__Canon,System.__Canon,ubyte):ubyte:this' during 'Generate code' (IL size 668; hash 0x26ab038f; FullOpts)
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=476416&view=results

We don't see this in normal replay runs because for checked/release diffs, we pass `-ignoreStoredConfig` to superpmi to avoid the case where Checked builds are affected by config values but Release builds aren't.

A simple repro:
```
superpmi.exe -c 329087 -target arm64 -ignoreStoredConfig C:\gh\runtime4\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\clrjit_universal_arm64_x64.dll c:\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.linux.arm64\coreclr_tests.run.linux.arm64.checked.mch -jitoption EnableHWIntrinsic=1
```

Stack trace:
```
 	clrjit_universal_arm64_x64.dll!assertAbort(const char * why, const char * file, unsigned int line) Line 284	C++
>	clrjit_universal_arm64_x64.dll!CodeGen::genHWIntrinsic(GenTreeHWIntrinsic * node) Line 210	C++
 	clrjit_universal_arm64_x64.dll!CodeGen::genCodeForTreeNode(GenTree * treeNode) Line 335	C++
 	clrjit_universal_arm64_x64.dll!CodeGen::genCodeForBBlist() Line 468	C++
 	clrjit_universal_arm64_x64.dll!CodeGen::genGenerateMachineCode() Line 1895	C++
```
with `intrin.id == NI_ArmBase_Arm64_MultiplyLongAdd (779)`

Setting `EnableHWIntrinsic=0` (which is in the MC stored config) allows it to pass.

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by TIHan**
Fixes https://github.com/dotnet/runtime/issues/95081

Do not use `JitConfig.EnableHWIntrinsic` to determine whether or not we can use a HW intrinsic. Instead, we should use `compOpportunisticallyDependsOn` on the specific instruction set, in this case `ArmBase_Arm64`.

When SuperPMI records a JITted method, it also records the JITFlags as it came from the VM - the JIT itself does not determine those flags. The JITFlags contains information of whether an ISA is supported or not.

The original issue occurred because when we set EnableHWIntrinsic=1 and re-JIT using SuperPMI, the original JITFlags did not support the `ArmBase_Arm64` ISA. There were two optimizations that used an `ArmBase_Arm64` intrinsic but only checked it with `JitConfig.EnableHWIntrinsic() != 0` - which isn't sufficient because it doesn't take into account what the VM said was supported. Instead, use `compOpportunisticallyDependsOn` to perform the check - this fixes the issue.

### CODE REVIEW

**Comment by TIHan** [comment]
@dotnet/jit-contrib @BruceForstall This is ready

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/jit/lowerarmarch.cpp [hunk 1]
```diff
@@ -2774,7 +2774,7 @@ GenTree* Lowering::TryLowerAddSubToMulLongOp(GenTreeOp* op)
     if (!comp->opts.OptimizationEnabled())
         return nullptr;
 
-    if (!JitConfig.EnableHWIntrinsic())
+    if (!comp->compOpportunisticallyDependsOn(InstructionSet_ArmBase_Arm64))
```
Comment (kunalspathak) [inline src/coreclr/jit/lowerarmarch.cpp:2777]: are there other places where we use `EnableHWIntrinsics` and should use `compOpportunisticallyDependsOn` instead?

Comment (TIHan) [reply src/coreclr/jit/lowerarmarch.cpp:2777]: Nope, just these two places.

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by TIHan** [comment]
Merging, ci failure is unrelated.
