### PR TITLE
CreateSymbolicLink PInvoke retval must be marshalled as U1

### LINKED ISSUE #62975: Creating symbolic links without developer mode or elevation fails silently
Tested on Windows 10 21H1 19043 without Developer Mode with .NET 6 RTM; it does not throw.

_Originally posted by @wegylexy in https://github.com/dotnet/runtime/issues/57205#issuecomment-992636452_

cc @iSazonov @adamsitnik.

### PR DESCRIPTION
**Pull request by jozkee**
Fixes https://github.com/dotnet/runtime/issues/62975. Silent failures were caused by incorrect marshalling, [CreateSymbolicLinkW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw) returns BOOLEAN, which is 1 byte, as opposed to BOOL, which is 4 bytes.

### CODE REVIEW

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CreateSymbolicLink.cs [hunk 1]
```diff
@@ -55,17 +55,10 @@ internal static void CreateSymbolicLink(string symlinkFileName, string targetFil
```
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CreateSymbolicLink.cs:55]: While you are on it, could you please also fix redundant invocations of `Environment.OSVersion.Version` above?
```
Version osVersion = Environment.OSVersion.Version;
bool isAtLeastWin10Build14972 = osVersion.Major >= 11 || osVersion.Major == 10 && osVersion.Build >= 14972;
```

**Review by jkoritzinsky — APPROVED** [review]

File: src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CreateSymbolicLink.cs (hunk 1 above)
Comment (Jozkee) [reply src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CreateSymbolicLink.cs:54]: Done.

**Review by jkotas — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]
Should this be ported back to .NET 6?

**Comment by Jozkee** [comment]
@stephentoub there's a reasonable workaround, that is, checking if the link does exists after calling the create symlink method.
