### PR TITLE
Fix FOH for SOS

### LINKED ISSUE #76232: VerifyHeap fails on frozen heap
Repro: Run `!VerifyHeap` in SOS once the runtime starts up (e.g. when entering `Main`)

Result (on Windows x86):
```
0:000> !VerifyHeap
Object 08592968 is too large.  End of segment at 085929E4.
Last good object: 085928E4.
```

The object that VerifyHeap complains about is at the end of the newly introduced frozen heap.

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/76232

The issue that FOH reported `sizeof(ObjHeader)`-bytes less than needed in `UpdateFrozenSegment`. It used to report the actual end of the last object while it's expected to be actual end + `sizeof(ObjHeader)` (for next object)

Tested locally with LLDB + SOS that it no longer printing errors.

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @jkotas

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 1]
```diff
@@ -137,15 +137,15 @@ Object* FrozenObjectSegment::TryAllocateObject(PTR_MethodTable type, size_t obje
     _ASSERT(m_pStart != nullptr && FOH_SEGMENT_SIZE > 0 && m_SegmentHandle != nullptr); // Expected to be inited
     _ASSERT(IS_ALIGNED(m_pCurrent, DATA_ALIGNMENT));
 
-    uint8_t* obj = m_pCurrent;
-    if (reinterpret_cast<size_t>(m_pStart + FOH_SEGMENT_SIZE) < reinterpret_cast<size_t>(obj + objectSize))
+    const size_t nextObject = reinterpret_cast<size_t>(m_pCurrent + objectSize);
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:140]: Can this overflow?

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 2]
```diff
@@ -137,15 +137,15 @@ Object* FrozenObjectSegment::TryAllocateObject(PTR_MethodTable type, size_t obje
...
+    if (reinterpret_cast<size_t>(m_pStart + FOH_SEGMENT_SIZE) < nextObject)
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:141]: Nit: These casts to `size_t` do not look necessary. Comparing the `uint8_t*` pointers should work just fine.

File: src/coreclr/vm/frozenobjectheap.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/vm/frozenobjectheap.cpp]: Slightly reshaped code, added asserts

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 3]
```diff
@@ -136,18 +136,27 @@ Object* FrozenObjectSegment::TryAllocateObject(PTR_MethodTable type, size_t obje
...
+    // Test if we have a room for the given object (including extra sizeof(ObjHeader) for next object)
+    if (spaceLeft - sizeof(ObjHeader) < objectSize)
     {
-        // Segment is full
         return nullptr;
     }
 
     // Check if we need to commit a new chunk
-    if (reinterpret_cast<size_t>(m_pStart + m_SizeCommitted) < reinterpret_cast<size_t>(obj + objectSize))
+    if (spaceUsed + objectSize + sizeof(ObjHeader) > m_SizeCommitted)
```
Comment (EgorBo) [inline src/coreclr/vm/frozenobjectheap.cpp:155]: this can not overflow because it's already proven to this point that there is a room for new object

File: src/coreclr/vm/frozenobjectheap.cpp [hunk 4]
```diff
@@ -136,18 +136,27 @@ Object* FrozenObjectSegment::TryAllocateObject(PTR_MethodTable type, size_t obje
 {
     _ASSERT(m_pStart != nullptr && FOH_SEGMENT_SIZE > 0 && m_SegmentHandle != nullptr); // Expected to be inited
     _ASSERT(IS_ALIGNED(m_pCurrent, DATA_ALIGNMENT));
+    _ASSERT(objectSize <= FOH_COMMIT_SIZE);
```
Comment (jkotas) [inline src/coreclr/vm/frozenobjectheap.cpp:139]: Where is this guaranteed? `AllocateString` calls this without any upfront check on `objectSize`.

Comment (jkotas) [reply src/coreclr/vm/frozenobjectheap.cpp:139]: Ah ok, it is guaranteed in FrozenObjectHeapManager

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by EgorBo** [comment]
Pri0 failure is https://github.com/dotnet/runtime/issues/76280
