### PR TITLE
Disallow resetting initial thread apartment state

### LINKED ISSUE #72232: ApartmentStateTest_ChangeBeforeThreadStarted failing
```
[FAIL] System.Threading.Threads.Tests.ThreadTests.ApartmentStateTest_ChangeBeforeThreadStarted_Windows(getApartmentState: Func`2 { Method = System.Threading.ApartmentState <ApartmentStateTest_MemberData>b__3_0(System.Threading.Thread), Target = <>c { } }, setApartmentState: Func`3 { Method = Int32 <ApartmentStateTest_MemberData>b__3_1(System.Threading.Thread, System.Threading.ApartmentState), Target = <>c { } }, setType: 0)
Assert.Equal() Failure
Expected: STA
Actual:   MTA
   at System.Threading.Threads.Tests.ThreadTests.ApartmentStateTest_ChangeBeforeThreadStarted_Windows(Func`2, Func`3, Int32) + 0x1a4
   at System.Threading.Thread.Tests!<BaseAddress>+0x877f04
   at System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0xec
[FAIL] System.Threading.Threads.Tests.ThreadTests.ApartmentStateTest_ChangeBeforeThreadStarted_Windows(getApartmentState: Func`2 { Method = System.Threading.ApartmentState <ApartmentStateTest_MemberData>b__3_2(System.Threading.Thread), Target = <>c { } }, setApartmentState: Func`3 { Method = Int32 <ApartmentStateTest_MemberData>b__3_3(System.Threading.Thread, System.Threading.ApartmentState), Target = <>c { } }, setType: 1)
Assert.Equal() Failure
Expected: 2
Actual:   0
   at System.Threading.Threads.Tests.ThreadTests.ApartmentStateTest_ChangeBeforeThreadStarted_Windows(Func`2, Func`3, Int32) + 0x164
   at System.Threading.Thread.Tests!<BaseAddress>+0x877f04
   at System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0xec
[FAIL] System.Threading.Threads.Tests.ThreadTests.ApartmentStateTest_ChangeBeforeThreadStarted_Windows(getApartmentState: Func`2 { Method = System.Threading.ApartmentState <ApartmentStateTest_MemberData>b__3_4(System.Threading.Thread), Target = <>c { } }, setApartmentState: Func`3 { Method = Int32 <ApartmentStateTest_MemberData>b__3_5(System.Threading.Thread, System.Threading.ApartmentState), Target = <>c { } }, setType: 2)
Assert.Equal() Failure
Expected: 2
Actual:   0
   at System.Threading.Threads.Tests.ThreadTests.ApartmentStateTest_ChangeBeforeThreadStarted_Windows(Func`2, Func`3, Int32) + 0x164
   at System.Threading.Thread.Tests!<BaseAddress>+0x877f04
   at System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0xec
```

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #72232

### CODE REVIEW

File: src/coreclr/vm/comsynchronizable.h [hunk 1]
```diff
@@ -52,13 +52,6 @@ friend class ThreadBaseObject;
         ThreadAbortRequested = 128,
     };
 
-    enum
```
Comment (jkotas) [inline src/coreclr/vm/comsynchronizable.h:55]: This enum was redundant. I have deleted it and the remapping code for enum values.

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!
