### PR TITLE
Fix handling of array constructors in Crossgen2

### LINKED ISSUE #48204: Runtimelab_578/arr fails in crossgen2.
The test added in https://github.com/dotnet/runtime/pull/47400 is failing in crossgen2 outerloop with:
```
  Regressions/coreclr/Runtimelab_578/arr/arr.sh [FAIL]
      cp: target '/home/helixbot/work/AE900994/p/lib*.dylib' is not a directory
      rm: cannot remove '/home/helixbot/work/AE900994/w/B29009C8/e/Regressions/coreclr/Runtimelab_578/arr/composite-r2r.dll.rsp': No such file or directory
      Unhandled exception. System.AggregateException: One or more errors occurred. (Code generation failed for method '[arr]<Module>.main()')
       ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[arr]<Module>.main()'
       ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at Internal.TypeSystem.ArrayMethod.GetCanonMethodTarget(CanonicalFormKind kind)

```
full log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48152-merge-304a3fe532ab482ca7/PayloadGroup0/console.88cdfe54.log?sv=2019-07-07&se=2021-03-03T22%3A44%3A29Z&sr=c&sp=rl&sig=oyTi3cN3NEeo8ng0oocOqdvb8kdokAjUMLrxnXZrzk8%3D

added in https://github.com/dotnet/runtime/pull/47400, @MichalStrehovsky could you please take a look if it is a test issue?

### PR DESCRIPTION
**Pull request by trylek**
Fixes: https://github.com/dotnet/runtime/issues/48204

I have attempted to adapt Michal's fix https://github.com/dotnet/runtimelab/pull/586 to Crossgen2.

Thanks

Tomas

/cc @dotnet/crossgen-contrib

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
I think we'll need to very carefully only do this for array constructors - arrays have IL-based methods on them that I think still need to canonicalize as usual. Only the constructor is special magic because it doesn't actually have code associated with it.

If you're set up for it, it might be worth checking how CoreCLR/crossgen1 does the canonical forms of these constructors (I know we try to mirror how crossgen1 is structured and crossgen1 apparently can get away without this special casing).

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRunCodegenNodeFactory.cs [hunk 1]
```diff
@@ -358,7 +358,11 @@ private IMethodNode CreateMethodEntrypoint(TypeAndMethod key)
             MethodWithToken method = key.Method;
             bool isInstantiatingStub = key.IsInstantiatingStub;
             bool isPrecodeImportRequired = key.IsPrecodeImportRequired;
-            MethodDesc compilableMethod = method.Method.GetCanonMethodTarget(CanonicalFormKind.Specific);
+            MethodDesc compilableMethod = method.Method;
+            if (!compilableMethod.OwningType.IsArray)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRunCodegenNodeFactory.cs:362]: I wouldn't expect special casing outside corinfoimpl to be needed - RyuJIT should realize this is an array constructor and ask for a helper - I wouldn't expect there would be an entrypoint for the actual method.

Comment (trylek) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRunCodegenNodeFactory.cs]: Thanks Michal for your insightful feedback. I have tracked this down to the fact that we need to set the <code>codePointerOrStubLookup.constLookup</code> in the "zapinfo" version of getCallInfo, otherwise it unconditionally requested the entrypoint. As of the 2nd commit I've been able to roll this back.

**Comment by trylek** [comment]
@MichalStrehovsky - this is what I see when I run the test with CG1:

<pre>
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Method not found: 'Void System.Int32[]..ctor(Int32, Int32)'. while compiling method <Module>.alloc
Native image D:\git\runtime7\artifacts\tests\coreclr\windows.x64.Checked\Regressions\coreclr\Runtimelab_578\arr\\arr.dll generated successfully.
</pre>

Does that answer your question?

**Comment by MichalStrehovsky** [comment]
The warning is for these lines:

https://github.com/dotnet/runtime/blob/49cfb3507c586b539d0652814defbbc9e3073f16/src/tests/Regressions/coreclr/Runtimelab_578/arr.il#L17-L22

That's expected since since single-dimensional arrays or non-arrays don't have a jagged constructor.

My question is more about what crossgen does on the same line that was crashing in crossgen2 - why does the canonicalization succeed. But no need to spend time on it if you're not set up for it (don't have things built). More just curiosity on my side.

**Comment by mangod9** [comment]
@trylek is this PR ready to merge or still needs work?

**Comment by trylek** [comment]
Apart from the PR question I'm not aware of any outstanding blocking feedback; it may also need rebasing. I'll look into finishing that today or tomorrow.

**Review by MichalStrehovsky — APPROVED** [review]

**Comment by trylek** [comment]
Taking a look now, will roll this back if I don't manage to nail this down and fix quickly.
