### PR TITLE
Fix fgCanTailCallViaJitHelper

### LINKED ISSUE #70013: What was the reason to inject DispatchTailCalls method after profiler instrumentation in .NET 7.0?
Hi, could you please tell us what was the reason to inject `DispatchTailCalls` method after profiler instrumentation in .NET 7.0? Some our .NET 7.0 tests became 🔴. The fast investigation shown that all our injections was surrounded Enter/Leave for `DispatchTailCalls` callbacks. It broken our profiler down, because we didn't expect that in code. Hotfix was disable the ELT injection for all `DispatchTailCalls` methods. Thanks in advance...
```
000047BC 1 03077968 PTIProf::FunctionIdMapper fid=0B728E00 res=ok fuid=00200001 fname='Main' cname='JetBrains.Profiler.Tests.RealApplications.Program'
000047BC 1 03077968 PTIProf::RdtscFastEnter fuid=00200001
000047BC 1 03077968 PTIProf::FunctionIdMapper fid=0B776EE0 res=instrumentation_helper
000047BC 1 03077968 PTIProf::FunctionIdMapper fid=0AF7CF40 res=ok fuid=001053A1 fname='DispatchTailCalls' cname='System.Runtime.CompilerServices.RuntimeHelpers'
000047BC 1 03077968 PTIProf::RdtscFastEnter fuid=001053A1 ; <=== !!!
000047BC 1 03077968 PTIProf::RdtscFastBegin var=0AD04CEC c=18
000047BC 1 03077968 PTIProf::RdtscFastLeave fuid=001053A1 ; <=== !!!
000047BC 1 03077968 PTIProf::FunctionIdMapper fid=0B776F10 res=instrumentation_helper
000047BC 1 03077968 PTIProf::RdtscFastEnter fuid=001053A1 ; <=== !!!
000047BC 1 03077968 PTIProf::RdtscFastMeasure var=0AD04CEC c=18 st=0
000047BC 1 03077968 PTIProf::RdtscFastLeave fuid=001053A1 ; <=== !!!
000047BC 1 03077968 ERROR: No end IL inject was called
	'[location] = C:\Work\dotnet-products\Profiler\Kernel\Windows\Native\Solution\core\src\profilers\performance\TemplatePerformanceThread.Header.h(66)'
	'[function] = unsigned __int64 *__thiscall jbprof::PerformanceInjectThread::Leave(const unsigned __int64 &,const unsigned int)'
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
FEATURE_READYTORUN is always defined except for single-file JIT. The
right check here is `Compiler::Options::IsReadyToRun()`.

Fix #70013

### CODE REVIEW

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -17526,10 +17526,15 @@ bool Compiler::fgCheckStmtAfterTailCall()
 //
 bool Compiler::fgCanTailCallViaJitHelper()
 {
-#if !defined(TARGET_X86) || defined(UNIX_X86_ABI) || defined(FEATURE_READYTORUN)
```
Comment (EgorBo) [inline src/coreclr/jit/morph.cpp:17529]: did it basically turn helper-based tailcalls off for jit?

Comment (EgorBo) [reply src/coreclr/jit/morph.cpp:17529]: If so I guess we need more (if we have any) microbenchmarks written in F#

Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp:17529]: (I thought I responded but can't see my comment..?)

> did it basically turn helper-based tailcalls off for jit?

No, it just made x86 use the same mechanism we use on all other platforms.

> If so I guess we need more (if we have any) microbenchmarks written in F#

That would be great, and yes, this would probably have shown up as a noticeable perf regression.

**Review by EgorBo — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Looks like this bit rotted slightly, probably because of #67238.
