### PR TITLE
Fix the slot calculation for multiple services

### LINKED ISSUE #54407: Bad result for 5 or more service implementations of interface
### Description

See [simple repro repo](https://github.com/billybraga/DotnetEnumerableServiceBug/blob/main/DotnetEnumerableServiceBug/Program.cs).

Basically, in dotnet 6 preview5, getting IEnumerable<> service (to get all implementations) is broken if service provider validates on build because slots are not always determined the same way and the validate step builds call site cache differently.

This snippet will throw:

```csharp
var services = new ServiceCollection();
services.AddSingleton<ICustomService, CustomService1>();
services.AddSingleton<ICustomService, CustomService2>();
services.AddSingleton<ICustomService, CustomService3>();
services.AddSingleton<ICustomService, CustomService4>();
services.AddSingleton<ICustomService, CustomService5>();
var serviceProvider = services.BuildServiceProvider(
    new ServiceProviderOptions
    {
        ValidateOnBuild = true
    }
);
var customServices = serviceProvider
    .GetService<IEnumerable<ICustomService>>()
    .ToArray()
// Index 1 should be CustomService2 but instead we get 5
if (customServices[1] is CustomService5 && customServices[4] is CustomService5)
{
    throw new Exception(
        "This is not right"
    );
}
```

### Configuration

dotnet 6 preview 5.21301.5

### Regression?

Yes

### Other information

I think this is the code that caused the bug : https://github.com/dotnet/runtime/commit/bb2d2c45410b9407a9657df7f5ca113bced53a43#diff-12fe7d127bc25efffaedd4b50d0b12792aa7c236e855d782c127424fa2f9dbb0

The problem is maybe that `descriptors.GetSlot()` should be used here : https://github.com/dotnet/runtime/blob/v6.0.0-preview.5.21301.5/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteFactory.cs#L176

### PR DESCRIPTION
**Pull request by davidfowl**
- The slot calculation was not correct for more than 5 services.
- Added tests to verify the slot calculation and service resolution.

Fixes https://github.com/dotnet/runtime/issues/54407

PS: We should put this in preview6

Details:

When register multiple instances of the same service type (e.g. IFoo, Foo1 : IFoo, Foo2 : IFoo), that service type can be resolved as an `IEnumerable<T>` or `T`. When resolved as `T` we take the last registration, when resolved as `IEnumerable<T>` we take all in registration order. Slots are per service type and represent 2 things:
- The 0th slot is the service service descriptor that will be resolved when asking for specific service type (Foo2 in the above example)
- It's a way to disambiguate the cache key for the same service type for IEnumerable (Foo1 = (IFoo, slot = 1), Foo2 = (IFoo, slot = 0))

Looking at the examples above, the last service registered is slot 0 and the first service registered is slot N - 1, where N is the number of service descriptors with the same service type.

The bug:

These calculations show why things were broken for only >= 5 services when ValidateOnBuild was set. Most of the time, even though the slot calculation was incorrect, it was incorrect and outside of the valid range of slot values for the IEnumerable. So for example, the valid range for 5 items is 0-4 (think array indexes). At 5 or more services, the incorrect slot calculation began to overlap in the valid list of slot values.

1
GetSlot(CS1) = Slot 0

2
GetSlot(CS1) = Slot 1 
GetSlot(CS2) = Slot 3 -> invalid slot

3
GetSlot(CS1) = Slot 2
GetSlot(CS2) = Slot 4 -> invalid slot
GetSlot(CS3) = Slot 3 -> invalid slot

4
GetSlot(CS1) = Slot 3
GetSlot(CS2) = Slot 5 -> invalid slot
GetSlot(CS3) = Slot 4 -> invalid slot
GetSlot(CS4) = Slot 3 -> already correctly cached so it gets ignored

5
GetSlot(CS1) = Slot 4
GetSlot(CS2) = Slot 6 -> invalid slot
GetSlot(CS3) = Slot 5 -> invalid slot
GetSlot(CS4) = Slot 4 -> already correctly cached so it gets ignored
GetSlot(CS5) = Slot 3 -> This crosses into a valid slot

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteFactory.cs [hunk 1]
```diff
@@ -537,7 +548,7 @@ public int GetSlot(ServiceDescriptor descriptor)
                     int index = _items.IndexOf(descriptor);
                     if (index != -1)
                     {
-                        return Count - index + 1;
+                        return _items.Count - (index + 1);
```
Comment (davidfowl) [inline src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteFactory.cs:551]: This is the fix.

**Review by eerhardt — APPROVED** [review]
LGTM

**Review by pakrym — APPROVED** [review]
Nice bug.
