### PR TITLE
Fix linux-x86 build

### LINKED ISSUE #11539: [x86/unix] HW instrinsics support
On x86/unix hardware intrinsics are disabled in the JIT, but enabled in System.Private.CoreLib, which leads to runtime errors. dotnet/coreclr#21164 temporarily solves these errors by disabling intrinsics in S.P.CoreLib, but they should be enabled back when we're certain there are no regressions with intrinsics on that platform.
CC @tannergooding @alpencolt 

category:correctness
theme:hardware-intrinsics
skill-level:intermediate
cost:small

### PR DESCRIPTION
**Pull request by filipnavara**
The linux-x86 builds have been broken for quite a while. At some point in the .NET 5 timeframe `genZeroInitFrameUsingBlockInit` was rewritten and it dropped support for non-SIMD platforms. linux-x86 had `FEATURE_SIMD` disabled since 2016 but the original intention was to disable AVX only.

- Enable FEATURE_SIMD and HW intrinsics on linux-x86. Fixes #11539
- Disable AVX support due to missing context saving.
- Fix general bit rot around stubs and W^X support.
- Enable CrossGen runs on linux-x86 CI for S.P.CoreLib to reduce further bit rot.

This is good enough to run Hello World again.

### CODE REVIEW

**Comment by filipnavara** [comment]
It still fails to run a simple Hello World (which is likely not related to this specific change):

```
./artifacts/bin/testhost/net10.0-linux-Debug-x86/dotnet --roll-forward major ~/helloworld/bin/Debug/net7.0/helloworld.dll

Assert failure(PID 5684 [0x00001634], Thread: 5684 [0x1634]): !stackSize.IsOverflow()
    File: /home/navara/runtime/src/coreclr/vm/stublink.inl:40
    Image: /home/navara/runtime/artifacts/bin/testhost/net10.0-linux-Debug-x86/dotnet

Aborted (core dumped)
```

File: src/coreclr/jit/compiler.cpp [hunk 1]
```diff
@@ -2222,6 +2222,13 @@ void Compiler::compSetProcessor()
         instructionSetFlags.AddInstructionSet(InstructionSet_Vector128);
     }
 
+#if defined(UNIX_X86_ABI)
+    // We don't support saving XState context on linux-x86 platforms yet, so we
+    // need to disable any AVX support that uses the extended registers.ß
```
Comment (jkotas) [inline src/coreclr/jit/compiler.cpp:2227]:
```suggestion
    // need to disable any AVX support that uses the extended registers.
```

**Comment by filipnavara** [comment]
The Hello World crash is caused by incorrect size passed at
https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/i386/stublinkerx86.cpp#L2160

If it's the only startup problem I'll just fold the fix into this PR.

File: src/coreclr/jit/compiler.cpp [hunk 2]
```diff
@@ -2222,6 +2222,13 @@ void Compiler::compSetProcessor()
         instructionSetFlags.AddInstructionSet(InstructionSet_Vector128);
     }
 
+#if defined(UNIX_X86_ABI)
+    // We don't support saving XState context on linux-x86 platforms yet, so we
```
[the remark this answers is not in the document]
Comment (filipnavara) [reply src/coreclr/jit/compiler.cpp:2226]: We could do that. I asked @tannergooding what would be a good place and went with his first suggestion. Presumably updating `xmmYmmStateSupport` would work as well.

[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/jit/compiler.cpp:2226]: > Presumably updating xmmYmmStateSupport would work as well.

Yep

File: eng/pipelines/runtime.yml [hunk 3]
```diff
@@ -448,8 +448,8 @@ extends:
           - linux_x86
           jobParameters:
             testScope: innerloop
-            nameSuffix: CoreCLR_NoR2R
-            buildArgs: -s clr.runtime+clr.jit+clr.iltools+clr.spmi+clr.corelib -c $(_BuildConfig)
+            nameSuffix: CoreCLR
+            buildArgs: -s clr.runtime+clr.jit+clr.iltools+clr.spmi+clr.corelib+clr.nativecorelib -c $(_BuildConfig)
```
Comment (jakobbotsch) [inline eng/pipelines/runtime.yml:452]: There is a comment above that looks like it should be updated if we are starting to run linux-x86 crossgen2 with this PR

**Comment by filipnavara** [comment]
I'll continue debugging this tomorrow...

```
Process 2400 launched: '/home/navara/runtime/artifacts/bin/testhost/net10.0-linux-Debug-x86/dotnet' (i386)

Assert failure(PID 2400 [0x00000960], Thread: 2400 [0x0960]): ((reinterpret_cast<DWORD>(pLocation) & 0x3) == 0)
    File: /home/navara/runtime/src/coreclr/vm/i386/jitinterfacex86.cpp:951
    Image: /home/navara/runtime/artifacts/bin/testhost/net10.0-linux-Debug-x86/dotnet

This version of LLDB has no plugin for the language "assembler". Inspection of frame variables will be limited.
Process 2400 stopped
* thread #1, name = 'dotnet', stop reason = signal SIGTRAP
    frame #0: 0xf77db46d libcoreclr.so`DBG_DebugBreak at debugbreak.S:9
   6
   7    LEAF_ENTRY DBG_DebugBreak, _TEXT
   8            int3
-> 9            ret
   10   LEAF_END_MARKED DBG_DebugBreak, _TEXT
   11
(lldb) bt
* thread #1, name = 'dotnet', stop reason = signal SIGTRAP
  * frame #0: 0xf77db46d libcoreclr.so`DBG_DebugBreak at debugbreak.S:9
    frame #1: 0xf77418a6 libcoreclr.so`::DebugBreak() at debug.cpp:408:9
    frame #2: 0xf74fbc66 libcoreclr.so`::DbgAssertDialog(szFile="/home/navara/runtime/src/coreclr/vm/i386/jitinterfacex86.cpp", iLine=951, szExpr="((reinterpret_cast<DWORD>(pLocation) & 0x3) == 0)") at debug.cpp:431:13
    frame #3: 0xf72b2375 libcoreclr.so`ValidateWriteBarrierHelpers() at jitinterfacex86.cpp:951:5
    frame #4: 0xf72b228b libcoreclr.so`InitJITHelpers1() at jitinterfacex86.cpp:907:5
    frame #5: 0xf7718322 libcoreclr.so`EEStartupHelper() at ceemain.cpp:890:9
    frame #6: 0xf771a3f7 libcoreclr.so`EEStartup(this=0xffffc20b, p=0x00000000)::$_1::operator()(void*) const at ceemain.cpp:1078:9
    frame #7: 0xf7716dfb libcoreclr.so`EEStartup() at ceemain.cpp:1080:5
    frame #8: 0xf7716b8d libcoreclr.so`EnsureEEStarted() at ceemain.cpp:298:17
```

File: src/native/minipal/cpufeatures.c [hunk 4]
```diff
@@ -66,6 +71,7 @@ static uint32_t xmmYmmStateSupport()
       );
     // check OS has enabled both XMM and YMM state support
     return ((eax & 0x06) == 0x06) ? 1 : 0;
+#endif // UNIX_X86_ABI
```
Comment (am11) [inline src/native/minipal/cpufeatures.c:74]: Nit: match HOST_X86 and UNIX_X86_ABI.

File: src/coreclr/vm/i386/stublinkerx86.cpp [hunk 5]
```diff
@@ -1143,9 +1144,12 @@ VOID StubLinkerCPU::X86EmitPopRegs(unsigned regSet)
 {
     STANDARD_VM_CONTRACT;
 
-    for (X86Reg r = NumX86Regs; r >= kEAX; r = (X86Reg)(r-1))
+    for (X86Reg r = NumX86Regs; regSet > 0; r = (X86Reg)(r-1))
```
Comment (filipnavara) [inline src/coreclr/vm/i386/stublinkerx86.cpp:1147]: This would always underflow, `X86Reg` is unsigned and `kEAX` is 0.

**Comment by filipnavara** [comment]
The last crash looks like issue with stack alignment related to the enabled SIMD support.

**Comment by filipnavara** [comment]
Here's a JIT dump of the crashing method: https://gist.github.com/filipnavara/cdf7cd19acaf04ed61160cb0e4f97866

ESP is 16-byte aligned, the prolog makes EBP 8 bytes away from ESP, so the instruction `movaps   xmmword ptr [V69 ebp-0x140], xmm0` ends up with misaligned access.

**Comment by filipnavara** [comment]
Okay, with the last few commits the "Hello World" works again. Still need to fix W^X code paths.

File: src/coreclr/jit/compiler.h [hunk 6]
```diff
@@ -9756,7 +9756,7 @@ class Compiler
     //
     bool isSIMDTypeLocalAligned(unsigned varNum)
     {
-#if defined(FEATURE_SIMD) && ALIGN_SIMD_TYPES
+#if defined(FEATURE_SIMD) && ALIGN_SIMD_TYPES && !UNIX_X86_ABI
```
Comment (filipnavara) [inline src/coreclr/jit/compiler.h:9759]: We can do better here, but this is no worse than win-x86 today.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/jit/compiler.h (hunk 6 above)
Comment (jkotas) [reply src/coreclr/jit/compiler.h:9759]: Would it be better to not define `ALIGN_SIMD_TYPES` for `UNIX_X86_ABI`? Makes the workaround more local.

Comment (filipnavara) [reply src/coreclr/jit/compiler.h:9759]: Either way would work and I am happy to change it if there's a preference. I chose this because it's closer to the code path that win-x86 takes today (by the virtue of having `STACK_ALIGN == 4`) but this is really only x86 usage of `ALIGN_SIMD_TYPES` so it wouldn't really matter. 

Ideally we want to do a similar thing as what x64 does in this branch and depend on the 16-byte stack alignment. We would just need to modify it to account for the pointer size being 4 bytes and not 8.

Comment (jkotas) [inline src/coreclr/jit/compiler.h:9759]:
```suggestion
#if defined(FEATURE_SIMD) && ALIGN_SIMD_TYPES && !defined(UNIX_X86_ABI)
```

Comment (jkotas) [reply src/coreclr/jit/compiler.h]: ok
