### PR TITLE
Fold "cns"[cns] for ROS<char>

### LINKED ISSUE #78359: Inlined ReadOnlySpan<char> parameter lacks string-like optimizations
Repro:
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8BiAOwFcAbS7YSmAAgBMBLXW+gWACgABAJgCMPXgAYGvQQDoASuVIYW+GFIDCEfAAcW9KAGUYUAG4swMXAG4eIgMwT+DVQwDePBu4ZuPkpAxYKGAFlBAAoASgYAXgA+BgARCAB1aABrUIAibHSwq24PCUFffwwg/nCo2ITkqBSyzOzc/K93AG1AmAwACwgmAEktShD2rp7+zUoAeU1FCFJcKQBBAHMl2FxcFiMYXtJKf38lsIBdZoKigKrU0JkYbCYJ3YBPPU1sUgAeME7sKFijbEo5BgYVOrjy+Q8LAAZgwQv9ASoADIwUhLLpRSIMQQg8EQlynPHuXAAdxYGC+sPhQJaoiODEIDFECH4ohxhIhYPZ7LAeEYAHJsHyQBIAOxYxpcvE83D84BC0UMfgSyX5aX8sDy3hilDKlXuNUMPlMTVigAcur1Br5MBNWKQFpVVqhtpsSoJhIAvu73F7uN6GF0oBBiQxSDAQwBRBBmaYsWbhXW+pq4hhtDrdPoDIbp0YDKYzOaLFZrDZbHZ7UgHY6nHx+C5JVJlSTiKnA0H+6GUgFAqTI1HoyKY7H+zkqklkilw7swGl0hlMllslWjvX63mGwXCrXi/3c9d8uVbsVulOW/cao8MHW7wlW42X803qX7m2XwoOyVOl0nvVJz3WU8PEDYNQ3DBgoxjAsE1OX0PSAA==)
```C#
#nullable disable
using System;
using System.Runtime.CompilerServices;

public class C {
    
    static int M1() => DoWork1("a");
    static int M2() => DoWork2("a");
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    static int DoWork1(ReadOnlySpan<char> value)
    {
        if (value.Length == 1)
        {
            switch (value[0] | 0x20)
            {
                case 'a': return 1;
                case 'b': return 2;
                case 'c': return 4;
                case 'd': return 8;
                case 'e': return 16;
                case 'f': return 32;
            }
        }

        throw new Exception();
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    static int DoWork2(string value)
    {
        if (value.Length == 1)
        {
            switch (value[0] | 0x20)
            {
                case 'a': return 1;
                case 'b': return 2;
                case 'c': return 4;
                case 'd': return 8;
                case 'e': return 16;
                case 'f': return 32;
            }
        }

        throw new Exception();
    }
}
```

M1 produces:
```asm
C.M1()
    L0000: push rsi
    L0001: sub rsp, 0x20
    L0005: mov rax, 0x23aa049dbd8
    L000f: mov rax, [rax]
    L0012: add rax, 0xc
    L0016: movzx eax, word ptr [rax]
    L0019: or eax, 0x20
    L001c: add eax, 0xffffff9f
    L001f: cmp eax, 5
    L0022: ja short L006a
    L0024: mov eax, eax
    L0026: lea rcx, [0x7ffcc3d200d8]
    L002d: mov ecx, [rcx+rax*4]
    L0030: lea rdx, [L0005]
    L0037: add rcx, rdx
    L003a: jmp rcx
    L003c: mov eax, 1
    L0041: jmp short L0064
    L0043: mov eax, 2
    L0048: jmp short L0064
    L004a: mov eax, 4
    L004f: jmp short L0064
    L0051: mov eax, 8
    L0056: jmp short L0064
    L0058: mov eax, 0x10
    L005d: jmp short L0064
    L005f: mov eax, 0x20
    L0064: add rsp, 0x20
    L0068: pop rsi
    L0069: ret
    L006a: mov rcx, 0x7ffce3cf2e38
    L0074: call 0x00007ffd4376f130
    L0079: mov rsi, rax
    L007c: mov rcx, rsi
    L007f: mov rax, 0x7ffce3d05c00
    L0089: call qword ptr [rax]
    L008b: mov rcx, rsi
    L008e: call 0x00007ffd4369fb10
    L0093: int3
```
whereas M2 produces:
```asm
C.M2()
    L0000: mov eax, 1
    L0005: ret
```

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/78359
e.g.:
```csharp
int Test() => DoWork("D");

[MethodImpl(MethodImplOptions.AggressiveInlining)]
int DoWork(ReadOnlySpan<char> format)
{
    if (format.Length == 1)
    {
        switch (format[0] | 0x20)
        {
            case 'a': return 1;
            case 'b': return 2;
            case 'c': return 4;
            case 'd': return 8;
            case 'e': return 16;
            case 'f': return 32;
        }
    }
    throw new Exception();
}
```

Current codegen for `Test`:
```asm
; Method ConsoleApp8.C:Test():int:this
G_M000_IG01:                ;; offset=0000H
       56                   push     rsi
       4883EC20             sub      rsp, 32
G_M000_IG02:                ;; offset=0005H
       48B84023807D78020000 mov      rax, 0x2787D802340
       488B00               mov      rax, gword ptr [rax]
       4883C00C             add      rax, 12
       0FB700               movzx    rax, word  ptr [rax]
       83C820               or       eax, 32
       83C09F               add      eax, -97
       83F805               cmp      eax, 5
       7746                 ja       SHORT G_M000_IG10
       8BC0                 mov      eax, eax
       488D0D63000000       lea      rcx, [reloc @RWD00]
       8B0C81               mov      ecx, dword ptr [rcx+4*rax]
       488D15CEFFFFFF       lea      rdx, G_M000_IG02
       4803CA               add      rcx, rdx
       FFE1                 jmp      rcx
G_M000_IG03:                ;; offset=003CH
       B801000000           mov      eax, 1
       EB21                 jmp      SHORT G_M000_IG09
G_M000_IG04:                ;; offset=0043H
       B802000000           mov      eax, 2
       EB1A                 jmp      SHORT G_M000_IG09
G_M000_IG05:                ;; offset=004AH
       B804000000           mov      eax, 4
       EB13                 jmp      SHORT G_M000_IG09
G_M000_IG06:                ;; offset=0051H
       B808000000           mov      eax, 8
       EB0C                 jmp      SHORT G_M000_IG09
G_M000_IG07:                ;; offset=0058H
       B810000000           mov      eax, 16
       EB05                 jmp      SHORT G_M000_IG09
G_M000_IG08:                ;; offset=005FH
       B820000000           mov      eax, 32
G_M000_IG09:                ;; offset=0064H
       4883C420             add      rsp, 32
       5E                   pop      rsi
       C3                   ret      
G_M000_IG10:                ;; offset=006AH
       48B9582E82E0FA7F0000 mov      rcx, 0x7FFAE0822E58
       E84744AC5F           call     CORINFO_HELP_NEWSFAST
       488BF0               mov      rsi, rax
       488BCE               mov      rcx, rsi
       FF153BB10800         call     [System.Exception:.ctor():this]
       488BCE               mov      rcx, rsi
       E843509F5F           call     CORINFO_HELP_THROW
       CC                   int3     
RWD00  	dd	00000037h ; case G_M000_IG03
       	dd	0000003Eh ; case G_M000_IG04
       	dd	00000045h ; case G_M000_IG05
       	dd	0000004Ch ; case G_M000_IG06
       	dd	00000053h ; case G_M000_IG07
       	dd	0000005Ah ; case G_M000_IG08
; Total bytes of code: 142
```
New codegen for `Test`:
```asm
; Method ConsoleApp8.C:Test():int:this
       B808000000           mov      eax, 8
       C3                   ret      
; Total bytes of code: 6
```

### CODE REVIEW

**Comment by EgorBo** [comment]
@SingleAccretion can you please take a look at the VN side, we discussed this one yesterday. For the issue with the side-effects I decide to just call `gtUpdateStmtSideEffects` for current statement.

File: src/coreclr/jit/valuenum.cpp [hunk 1]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+//    tree - the GT_IND node
+//
+// Return Value:
+//    true if the pattern was recognized and a new VN is assigned
+//
+bool Compiler::fgValueNumberConstStringElemLoad(GenTreeIndir* tree)
+{
+    ValueNum  addrVN = tree->gtGetOp1()->gtVNPair.GetLiberal();
+    VNFuncApp funcApp;
+    if (!varTypeIsShort(tree) || !vnStore->GetVNFunc(addrVN, &funcApp))
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8509]: Why are we interested in `TYP_SHORT` (signed) trees, since I assume this is a TP heuristic?

This shouldn't have to recompute `addrVN` + `GetVNFunc`, since the caller already did that.

File: src/coreclr/jit/valuenum.cpp [hunk 2]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+        if (vnStore->IsVNHandle(vn) && (vnStore->GetHandleFlags(vn) == GTF_ICON_OBJ_HDL))
+        {
+            const size_t obj = vnStore->CoercedConstantValue<size_t>(vn);
+            *handle          = reinterpret_cast<CORINFO_OBJECT_HANDLE>(obj);
+            return true;
+        }
+        return false;
+    };
+
+    CORINFO_OBJECT_HANDLE objHandle = nullptr;
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8525]: Nit: can we add `NO_OBJECT_HANDLE` similar to `NO_CLASS_HANDLE`, etc?

File: src/coreclr/jit/valuenum.cpp [hunk 3]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+        ValueNum arrVN  = funcApp.m_args[1];
+        ValueNum inxVN  = funcApp.m_args[2];
+        ssize_t  offset = vnStore->ConstantValue<ssize_t>(funcApp.m_args[3]);
+
+        if (isCnsObjHandle(vnStore, arrVN, &objHandle) && offset == 0 && vnStore->IsVNConstant(inxVN))
+        {
+            index = (int)vnStore->CoercedConstantValue<size_t>(inxVN);
+        }
+    }
+    else if (((genTreeOps)funcApp.m_func == GT_ADD) && vnStore->IsVNConstant(funcApp.m_args[0]))
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8541]: Nit (here and below): `(genTreeOps)funcApp.m_func == GT_ADD` -> `funcApp.m_func == VNFunc(GT_ADD)`.

File: src/coreclr/jit/valuenum.cpp [hunk 4]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+            const size_t byteDataIndex = vnStore->CoercedConstantValue<size_t>(funcApp.m_args[0]);
+            if (vnStore->GetVNFunc(funcApp.m_args[1], &funcApp) && ((genTreeOps)funcApp.m_func == GT_ADD) &&
+                vnStore->IsVNConstant(funcApp.m_args[1]) && isCnsObjHandle(vnStore, funcApp.m_args[0], &objHandle))
+            {
+                dataOffset = vnStore->CoercedConstantValue<size_t>(funcApp.m_args[1]) + byteDataIndex;
+            }
+        }
+
+        // Convert dataOffset (that also includes offset to firstChar field) into char index
+        if ((dataOffset >= OFFSETOF__CORINFO_String__chars) && ((dataOffset % 2) == 0))
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8565]: This implicitly assumes `OFFSETOF__CORINFO_String__chars`, so it should `static_assert_no_msg` that.

File: src/coreclr/jit/valuenum.cpp [hunk 5]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+        {
+            index = (int)(dataOffset - OFFSETOF__CORINFO_String__chars) / 2;
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8567]: This assumes the offset fits into an `int`, which could be not true.

File: src/coreclr/jit/valuenum.cpp [hunk 6]
```diff
@@ -8743,6 +8834,13 @@ void Compiler::fgValueNumberTree(GenTree* tree)
                     // Note VNF_PtrToStatic statics are currently always "simple".
                     fgValueNumberFieldLoad(tree, /* baseAddr */ nullptr, fldSeq, offset);
                 }
+                else if (tree->OperIs(GT_IND) && fgValueNumberConstStringElemLoad(tree->AsIndir()))
+                {
+                    tree->gtFlags |= GTF_IND_NONFAULTING | GTF_IND_INVARIANT;
+                    tree->gtFlags &= ~GTF_EXCEPT;
+                    // Update side-effect flags of parent trees if needed
+                    gtUpdateStmtSideEffects(stmt);
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8842]: It is not right to update side effects in VN like that. The problem this solves should be solved in some other way.

File: src/coreclr/jit/valuenum.cpp [hunk 7]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+
+    // First, let see if we have PtrToArrElem
+    ValueNum addr = funcApp.m_args[0];
+    if (funcApp.m_func == VNF_PtrToArrElem)
+    {
+        ValueNum arrVN  = funcApp.m_args[1];
+        ValueNum inxVN  = funcApp.m_args[2];
+        ssize_t  offset = vnStore->ConstantValue<ssize_t>(funcApp.m_args[3]);
+
+        if (isCnsObjHandle(vnStore, arrVN, &objHandle) && offset == 0 && vnStore->IsVNConstant(inxVN))
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8536]:
```suggestion
        if (isCnsObjHandle(vnStore, arrVN, &objHandle) && (offset == 0) && vnStore->IsVNConstant(inxVN))
```

File: src/coreclr/jit/valuenum.cpp [hunk 8]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+
+    if ((objHandle != nullptr) && (index >= 0))
+    {
+        assert(objHandle != nullptr);
+        USHORT charValue;
+        if (info.compCompHnd->getStringChar(objHandle, index, &charValue))
+        {
+            JITDUMP("Folding \"cns_str\"[%d] into %u\n", index, (unsigned)charValue);
+            // NOTE: we need to sign-extend it here in case if it's a negative Int16
+            tree->gtVNPair.SetBoth(vnStore->VNForIntCon((SHORT)charValue));
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8579]: This assumes the load doesn't have a significant difference in the conservative component, which does not like an assumption we can make.

E. g.:
```cs
obj.StringField = "my constant";
/* here thread B mutates this to be "not my constant" */
Use(obj.StringField[2]);
```
So this optimization should either be done for `Liberal == Conservative` or (which is what all of the other similar optimizations do) for both liberal and conservative components, with some `VNForConstLoad` or similar function.

File: src/coreclr/jit/valuenum.cpp [hunk 9]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+// fgValueNumberConstStringElemLoad: Try to match "cns_str"[cns_index] tree
+//    and apply a constant VN representing given char at cns_index in that string.
+//
+// Arguments:
+//    tree - the GT_IND node
+//
+// Return Value:
+//    true if the pattern was recognized and a new VN is assigned
+//
+bool Compiler::fgValueNumberConstStringElemLoad(GenTreeIndir* tree)
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8505]: Nit: I think it is likely we will be looking at other types of know constant data before long, so I'd name this function `fgValueNumberConstLoad` (or its VN version, see comments below) today.

File: src/coreclr/jit/valuenum.cpp [hunk 10]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+        if (vnStore->IsVNConstant(funcApp.m_args[1]) && isCnsObjHandle(vnStore, funcApp.m_args[0], &objHandle))
+        {
+            dataOffset = vnStore->CoercedConstantValue<size_t>(funcApp.m_args[1]);
+        }
+        else
+        {
+            assert(vnStore->IsVNConstant(funcApp.m_args[0]));
+            const size_t byteDataIndex = vnStore->CoercedConstantValue<size_t>(funcApp.m_args[0]);
+            if (vnStore->GetVNFunc(funcApp.m_args[1], &funcApp) && ((genTreeOps)funcApp.m_func == GT_ADD) &&
+                vnStore->IsVNConstant(funcApp.m_args[1]) && isCnsObjHandle(vnStore, funcApp.m_args[0], &objHandle))
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8558]: VN canonicalization means we usually have to check for both `m_args[0]` and `m_args[1]` to be constant.

File: src/coreclr/jit/valuenum.cpp [hunk 11]
```diff
@@ -8492,7 +8492,98 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+    }
+    else if (((genTreeOps)funcApp.m_func == GT_ADD) && vnStore->IsVNConstant(funcApp.m_args[0]))
+    {
+        // Here we try to match these two patterns:
+        //
+        //  1) (objHandle + firstCharOffset)
+        //  2) ((objHandle + firstCharOffset) + byteIndex)
+        //
+        size_t dataOffset = 0;
+        if (vnStore->IsVNConstant(funcApp.m_args[1]) && isCnsObjHandle(vnStore, funcApp.m_args[0], &objHandle))
```
Comment (SingleAccretion) [inline src/coreclr/jit/valuenum.cpp:8549]: Nit: the more convention way to structure this search is with a `while` loop over `GT_ADD` funcs (see e. g. `fgValueNumberAddExceptionSetForIndirection`).

File: src/coreclr/jit/valuenum.cpp (hunk 6 above)
Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp:8842]: @SingleAccretion Any recommendation and what's wrong with it? Unfortunately, I don't see a better option and this is required for this PR.
Alternative option I see is to define a new VN with "known-non-null" property and then fold it later e.g. at assertprop.

File: src/coreclr/jit/valuenum.cpp (hunk 8 above)
Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp:8579]: Yes, it had `Liberal == Conservative` I probably removed it before push

File: src/coreclr/jit/valuenum.cpp (hunk 10 above)
Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp:8558]: um.. isn't m_args[0] is checked via `isCnsObjHandle` here?

File: src/coreclr/jit/valuenum.cpp (hunk 6 above)
Comment (SingleAccretion) [reply src/coreclr/jit/valuenum.cpp:8842]: > Any recommendation

From the discussion yesterday - did making VN-based constant propagation run in post-order not work?

> what's wrong with it

It's not in VN's contract to modify IR like this. Certainly, if you allow this, all sorts of things become possible (for example, here we would just bash the node to a `CNS_INT` directly).

File: src/coreclr/jit/valuenum.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp:8565]: um, not sure I follow, can you please elaborate?

File: src/coreclr/jit/valuenum.cpp (hunk 10 above)
Comment (SingleAccretion) [reply src/coreclr/jit/valuenum.cpp:8558]: What I mean is that this is looking for `ADD(handle, offset)`, but VN's canonicalization means we can also see `ADD(offset, handle)` (it depends on prior numbering which one will it be).

File: src/coreclr/jit/valuenum.cpp (hunk 4 above)
Comment (SingleAccretion) [reply src/coreclr/jit/valuenum.cpp:8565]: Sorry, I did not actually write the full thing out: "...implicitly assumes OFFSETOF__CORINFO_String__chars _is divisible by 2_".

File: src/coreclr/jit/valuenum.cpp (hunk 10 above)
Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp:8558]: I can add it but initially I just didn't want to make code more complicated for the case that didn't raise any diffs

Comment (SingleAccretion) [reply src/coreclr/jit/valuenum.cpp:8558]: > didn't raise any diffs

Is that the case? Then I think it is fine as-is. It is kind of accidental though.

**Comment by am11** [comment]
> ```cs
>         switch (format[0] | 0x20)
> ```

Looks like with `char.ToLowerInvariant()` it emits an extra `mov` and a `jmp`.

```diff
+            switch (char.ToLowerInvariant(value[0]))
-            switch (value[0] | 0x20)
```

```diff
C.M2()
+    L0000: mov rcx, 0x207d38020d8
+    L000a: mov rcx, [rcx]
+    L000d: jmp 0x00007ff863530090
-    L0000: mov eax, 8
-    L0005: ret
```

and gets worse with `value.ToLowerInvariant()[0]`. Maybe importer can normalize them to `| 0x20` equivalent for ASCII / A-Za-z values (since `ToLowerInvariant()` is more common than `| 0x20`).

**Comment by EgorBo** [comment]
@am11 good point! That jump is a tail call to `TextInfo:ToLowerInvariant` which is not inlined, I've pushed a change that fixes that - https://github.com/dotnet/runtime/pull/78593/commits/369179d2b3a424285c308d0a9570f74c7ca03670, e.g.:
```csharp
char foo() => char.ToLowerInvariant('B');
```
Was:
```asm
; Method Prog:foo():ushort:this
       B942000000           mov      ecx, 66 ; 'B'
       FF25556B1500         tail.jmp [System.Globalization.TextInfo:ToLowerInvariant(ushort):ushort]
; Total bytes of code: 11
```
Now:
```asm
; Method Prog:foo():ushort:this
       B862000000           mov      eax, 98 ; 'b'
       C3                   ret      
; Total bytes of code: 6
```

I think it's fine to mark as AggressiveInlining, `Invariant` is folded always (but inliner currently has no chance to know it) and `IsAsciiCodePoint` and `ToUpperAsciiInvariant` are single instructions basically.

File: src/coreclr/jit/valuenum.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp]: @SingleAccretion can you point me where exactly caller already did it? it seems like other paths also compute it https://github.com/dotnet/runtime/blob/b406c1782d15a676b3e70cf71c53393cbc99481e/src/coreclr/jit/valuenum.cpp#L8838-L8853.

Changed to TYP_SHORT (yes, it was a TP fast-out path)

File: src/coreclr/jit/valuenum.cpp (hunk 6 above)
Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp]: Thanks! Reverted the change, the suggestion about post-order works but I decided to postpone it to a separate PR so I can see if it worth the effort around TP and diffs (and planned a few experiments around that)

**Comment by EgorBo** [comment]
@jkotas does VM side looks good to you?

File: src/coreclr/jit/valuenum.cpp (hunk 1 above)
Comment (SingleAccretion) [reply src/coreclr/jit/valuenum.cpp]: > can you point me where exactly caller already did it? it seems like other paths also compute it

`else if (vnStore->GetVNFunc(addrNvnp.GetLiberal(), &funcApp)` computes it. It would be good to change this to compute the thing once like `ASG` numbering does.

**Comment by jkotas** [comment]
The VM side looks good.

File: src/coreclr/jit/valuenum.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp]: do you mind if I leave it as is, I've just pushed a change to extract vnfunc only after TP-oriented checks. I tried to re-organize code to save these two existing lookups and didn't like the outcome, feel free to file a PR to clean it up

**Comment by EgorBo** [comment]
@SingleAccretion can you take a look again? 🙂 

As I said in some of the comment, I decided to avoid assertprop changes in this PR so it still folds everything but might leave nullchecks in some cases, I'll work separately (once this lands and collections are updated) to see if it's worth the effort and JIT-TP to clean them up (local runs of jit-diff state that there are not many hits)

File: src/coreclr/jit/valuenum.cpp (hunk 1 above)
Comment (SingleAccretion) [reply src/coreclr/jit/valuenum.cpp]: Sure.

**Review by SingleAccretion — APPROVED** [review]
Jit side changes LGTM.

**Comment by EgorBo** [comment]
@jakobbotsch Can you please sign off the jit side (if it looks good to you)

File: src/coreclr/jit/valuenum.cpp [hunk 12]
```diff
@@ -8494,6 +8494,104 @@ void Compiler::fgValueNumberSsaVarDef(GenTreeLclVarCommon* lcl)
...
+    }
+
+    USHORT charValue;
+    if (((size_t)index < INT_MAX) && (objHandle != NO_OBJECT_HANDLE) &&
+        info.compCompHnd->getStringChar(objHandle, (int)index, &charValue))
+    {
+        JITDUMP("Folding \"cns_str\"[%d] into %u", (int)index, (unsigned)charValue);
+
+        // NOTE: we need to sign-extend it here in case if it's a negative Int16
+        tree->gtVNPair.SetBoth(vnStore->VNForIntCon((SHORT)charValue));
```
Comment (jakobbotsch) [inline src/coreclr/jit/valuenum.cpp:8589]: Why are we sign extending here? It doesn't seem right to me given that the tree is a `TYP_USHORT` indirection.

Comment (EgorBo) [reply src/coreclr/jit/valuenum.cpp]: It most likely was not correct actually, let's see if CI agrees. The current version asserted on this example in the assertprop:
```csharp
int Foo()
{
    char x = GetChar()[1];
    if (x > 100)
    {
        Console.WriteLine(x);
    }
    return x;
}

private ReadOnlySpan<char> GetChar()
{
    return "鉄鉄鉄";
}
```
```
 Assertion failed 'FitsIn(tree->TypeGet(), value)' in 'Prog:Foo():int:this' during 'Assertion prop'
```

Comment (jakobbotsch) [reply src/coreclr/jit/valuenum.cpp]: Consider adding some targeted tests for it.

**Review by jakobbotsch — APPROVED** [review]

**Comment by EgorBo** [comment]
Merging to have a new collection by Monday.
Two CI failures are unrelated because they're Mono only, e.g. iOS seems to be struggling connecting to a test device in that test (infra issue)

**Comment by jkotas** [comment]
> Two CI failures are unrelated because they're Mono only

We still want to keep track of the unrelated intermittent failures to ensure that they are getting fixed: https://github.com/dotnet/runtime/blob/main/docs/pr-builds.md#what-to-do-if-you-determine-the-failure-is-unrelated

Both of the failures are known - I have added comments to the tracking issues for you.

**Comment by EgorBo** [comment]
Improvements on x64: https://github.com/dotnet/perf-autofiling-issues/issues/9914
