### PR TITLE
JIT: SpanHelpers.Fill may escape its last argument

### LINKED ISSUE #122879: Unexpected NullReferenceException (potentially escaped stack allocation)
### Description

During the migration of a codebase from .NET 9 to .NET 10 unexpected AccessViolationException(s) started showing up.

Further investigation showed that the problem seems to be related to a stack-allocated value that escapes to a caller. I've reduced the problem into the repro below. It crashes with a NullReferenceException when calling "StackTrasher", otherwise it works as expected. This only happens in Release mode with the highest optimization level.

### Reproduction Steps

Create a Program.cs with:
```cs
var result = Creator();
StackTrasher(); // Removing this line makes it work as expected
Console.WriteLine(result[0].Value);

static void StackTrasher()
{
    Guid heavy = Guid.NewGuid();
    heavy.ToString();
}

static Poco[] Creator() => CreateArray(new Poco("Greetings"), 2);

static T[] CreateArray<T>(T value, int count)
{
    var output = new T[count];
    output.AsSpan().Fill(value);
    return output;
}

public class Poco(string value)
{
    public string Value { get; } = value;
}
```

and a csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
</Project>
```

(Note that TieredCompilation *must* be disabled)

Full Repro:
[net10escape.zip](https://github.com/user-attachments/files/24437752/net10escape.zip)

Build with `dotnet build -c Release`

### Expected behavior

The application prints "Greetings".

### Actual behavior

The application terminates with:
```plain
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at Program.<Main>$(String[] args)
```

### Regression?

Yes, downgrading to .NET 9.0 fixes the issue.

### Known Workarounds

None

### Configuration

.NET 10.0 / SDK 10.0.101
Windows 11 (10.0.26200.7462 / AMD64)

### Other information

Looking at the disassembly of the "Creator" method in WinDbg:

Image

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Fixes #122879.

### CODE REVIEW

**Review by kg — APPROVED** [review]

File: src/coreclr/jit/objectalloc.cpp [hunk 1]
```diff
@@ -2203,12 +2203,20 @@ void ObjectAllocator::AnalyzeParentStack(ArrayStack<GenTree*>* parentStack, unsi
...
                     {
                         case NI_System_SpanHelpers_ClearWithoutReferences:
-                        case NI_System_SpanHelpers_Fill:
                         case NI_System_SpanHelpers_Memmove:
                         case NI_System_SpanHelpers_SequenceEqual:
                             canLclVarEscapeViaParentStack = false;
                             break;
 
+                        case NI_System_SpanHelpers_Fill:
+                            // For Fill only the first (byref span) arg does not escape
```
Comment (EgorBo) [inline src/coreclr/jit/objectalloc.cpp:2212]: technically, only the last (value) may escape? not sure if it's useful to know that the length arg does or doesn't

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/objectalloc.cpp (hunk 1 above)
Comment (adamperlin) [reply src/coreclr/jit/objectalloc.cpp:2212]: Would it be possible to track the type/origin of the last value to determine if it's a ref that could escape here, or is that simply too complicated to do or wouldn't work? Thinking of i.e.,
```
int n = 5;
Span<int> s = new[10];
s.Fill(n); // n's value should be copied here so no escape?
return s;
```

Comment (AndyAyersMS) [reply src/coreclr/jit/objectalloc.cpp:2212]: For escape analysis we only care about GC types.

Comment (adamperlin) [reply src/coreclr/jit/objectalloc.cpp:2212]: Ah got it, thanks for clarifying
