### PR TITLE
Move a morph opt to post-order

### LINKED ISSUE #61074: Assertion failed '!parentStruct->lvUndoneStructPromotion' during 'Mark local vars'
### Description

The following program hits a JIT assert in checked builds when optimizations are on:

### Reproduction Steps

```csharp
// Generated by Fuzzlyn v1.5 on 2021-10-31 16:57:02
// Run on X64 Windows
// Seed: 701457804295464207
// Reduced from 37.8 KiB to 0.3 KiB in 00:00:50
// Hits JIT assert in Release:
// Assertion failed '!parentStruct->lvUndoneStructPromotion' in 'Program:M2(S0)' during 'Mark local vars' (IL size 33)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\lclvars.cpp Line: 4039
// 
public struct S0
{
    public long F0;
    public long F1;
}

public class Program
{
    public static void Main()
    {
        S0 vr4 = default(S0);
        M2(vr4);
    }

    public static void M2(S0 arg4)
    {
        bool vr0 = ((-arg4.F0 * -1) & arg4.F1--) == 0;
        bool vr1 = vr0;
    }
}
```

### Expected behavior

No JIT assert hit

### Actual behavior

JIT assert is hit

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

Assert was added as part of #58582.
cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by jakobbotsch**
When changing the shape of child nodes in pre-order we must ensure we properly morph
potential promoted/demoted child nodes. Normally this happens inside
fgMorphTree which does it for child nodes, but this specific transform was not
calling `fgMorphTree` on the parent tree after changing the shape of child nodes.

The simplest fix is just to move the optimization to post-order which catches more cases and does not need to bother dealing with this.

Fix #61074

### CODE REVIEW

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -10242,13 +10242,18 @@ GenTree* Compiler::fgMorphSmpOp(GenTree* tree, MorphAddrContext* mac)
...
+                    // do promotion-specific morphing of op1); however, morphing
+                    // the top-level node twice is not ok. Reuse op1 as the new
+                    // top-level node instead.
+                    op2->AsIntCon()->gtIconVal = -op2->AsIntCon()->gtIconVal;
+                    op1->ChangeOper(GT_MUL);
+                    op1->SetVNsFromNode(tree);
+                    op1->AsOp()->gtOp2 = op2;
+                    DEBUG_DESTROY_NODE(tree);
+
+                    return fgMorphTree(op1);
```
Comment (SingleAccretion) [inline src/coreclr/jit/morph.cpp:10256]: Another option here would be to not return early and carry on morphing instead (would require updating `op1` and `op2` local variables).

Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp:10256]: I don't think that would fix the problem. As I tried to explain in the comment we morph promoted/demoted locals only when morphing their user.

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:10256]: You are right, sorry for the distraction.

Coincidentally, after #69819 and the equivalent change for implicit byrefs, that will no longer be a problem.

Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp:10256]: > Coincidentally, after https://github.com/dotnet/runtime/pull/69819 and the equivalent change for implicit byrefs, that will no longer be a problem.

Regardless, it feels iffy to leave the call to `fgMorphSmpOp` which somehow implies that it is fully sufficient as a replacement of `fgMorphTree`. I guess there are other cases where `fgMorphTree` will make additional decisions depending on child nodes, e.g. local assertion prop.

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:10256]: Yes, I agree with that.

(The usage of `fgMorphSmpOp` instead of `fgMorphTree` in these code paths is a workaround for the double-morphing assert)

File: src/coreclr/jit/morph.cpp [hunk 2]
```diff
@@ -10242,13 +10242,18 @@ GenTree* Compiler::fgMorphSmpOp(GenTree* tree, MorphAddrContext* mac)
                 if (op1->OperIs(GT_NEG) && !op1->gtGetOp1()->IsCnsIntOrI() && op2->IsCnsIntOrI() &&
                     !op2->IsIconHandle())
```
[the remark this answers is not in the document]
Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp:10243]: If we morph to helpers on 32-bit then presumably reusing the `GT_NEG` node is not going to be ok here...

File: src/coreclr/jit/morph.cpp [hunk 3]
```diff
@@ -12910,6 +12894,19 @@ GenTree* Compiler::fgOptimizeMultiply(GenTreeOp* mul)
...
     if (op2->IsIntegralConst())
     {
+        // We should not get here for 64-bit multiplications on 32-bit.
+        assert(op2->IsCnsIntOrI());
+
+        // MUL(NEG(a), C) => MUL(a, NEG(C))
+        if (opts.OptimizationEnabled() && op1->OperIs(GT_NEG) && !op2->IsIconHandle())
+        {
+            mul->gtOp1                 = op1->AsUnOp()->gtGetOp1();
+            op2->AsIntCon()->gtIconVal = -op2->AsIntCon()->gtIconVal;
```
[the remark this answers is not in the document]
Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp:12904]: Whoops yes, thanks for spotting that! Fixed.

**Review by SingleAccretion — APPROVED** [review]

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Review by EgorBo — APPROVED** [review]
