### PR TITLE
Fix Windows Arm64 unwinding

### LINKED ISSUE #101921: Infinite loop in Frame::UpdateFloatingPointRegisters on ARM64
We have observed that some tests started to time out on Windows ARM64 outerloop runs, first run on commit https://github.com/dotnet/runtime/commit/d92ac1f892a7f9c00561db6541671f25f3972eed. I assume something committed in the preceeding 24h will be the cause.

Example failure https://[helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b0ba224c9aa14ac7aa/System.Net.WebHeaderCollection.Tests/1/console.ebb7fdfd.log?helixlogtype=result](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b0ba224c9aa14ac7aa/System.Net.WebHeaderCollection.Tests/1/console.ebb7fdfd.log?helixlogtype=result)

```
========================== End custom configuration settings ===============================
----- start Mon 05/06/2024 10:10:02.06 ===============  To repro directly: =====================================================
pushd C:\h\w\BB260A1D\w\AB250977\e\
"C:\h\w\BB260A1D\p\dotnet.exe" exec --runtimeconfig System.Net.WebHeaderCollection.Tests.runtimeconfig.json --depsfile System.Net.WebHeaderCollection.Tests.deps.json xunit.console.dll System.Net.WebHeaderCollection.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\BB260A1D\w\AB250977\e>"C:\h\w\BB260A1D\p\dotnet.exe" exec --runtimeconfig System.Net.WebHeaderCollection.Tests.runtimeconfig.json --depsfile System.Net.WebHeaderCollection.Tests.deps.json xunit.console.dll System.Net.WebHeaderCollection.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Net.WebHeaderCollection.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.WebHeaderCollection.Tests (found 61 test cases)
  Starting:    System.Net.WebHeaderCollection.Tests (parallel test collections = on [2 threads], stop on fail = off)
   System.Net.WebHeaderCollection.Tests: [Long Running Test] 'System.Net.Tests.WebHeaderCollectionTest.HttpResponseHeader_AddInvalid_Throws', Elapsed: 00:02:11
   System.Net.WebHeaderCollection.Tests: [Long Running Test] 'System.Net.Tests.WebHeaderCollectionTest.HttpResponseHeader_AddInvalid_Throws', Elapsed: 00:04:12
   System.Net.WebHeaderCollection.Tests: [Long Running Test] 'System.Net.Tests.WebHeaderCollectionTest.HttpResponseHeader_AddInvalid_Throws', Elapsed: 00:06:12
```

The test itself just calling a ctor and checks for exception type, there is nothing that can be expected to hang. 

https://github.com/dotnet/runtime/blob/fa5dcda23c681031b5d2bd68482702baef80b836/src/libraries/System.Net.WebHeaderCollection/tests/WebHeaderCollectionTest.cs#L51-L59

There are more examples like this, the common thread is that the test involves throwing an exception. Compiling locally on ARM64 machine and attaching a debugger shows infinite loop in 

https://github.com/dotnet/runtime/blob/93f886f5f64c738fd8122d5b85e2c032da23dd0e/src/coreclr/vm/frames.cpp#L469-L480

With stacktrace

```
0:011> !dumpstack
OS Thread Id: 0x6544 (11)
Current frame: coreclr!RangeSectionMap::LookupRangeSection + 0x94 [C:\source\runtime\src\coreclr\vm\codeman.h:1251]
ChildFP          RetAddr          Caller, Callee
0000008EF25F98D0 00007ff9af0b7e48 coreclr!ExecutionManager::IsManagedCodeWorker + 0x28 [C:\source\runtime\src\coreclr\vm\codeman.cpp:4561], calling coreclr!RangeSectionMap::LookupRangeSection [C:\source\runtime\src\coreclr\vm\codeman.h:1239]
0000008EF25F98E0 00007ff9af0b7dfc coreclr!ExecutionManager::IsManagedCodeWithLock + 0x24 [C:\source\runtime\src\coreclr\vm\codeman.cpp:4537], calling coreclr!ExecutionManager::IsManagedCodeWorker [C:\source\runtime\src\coreclr\vm\codeman.cpp:4551]
0000008EF25F98F0 00007ff9af0fba2c coreclr!UnwindAndContinueRethrowHelperAfterCatch + 0x7c, calling coreclr!DispatchManagedException [C:\source\runtime\src\coreclr\vm\exceptionhandling.cpp:5704]
0000008EF25F9910 00007ff9af0b7db8 coreclr!ExecutionManager::IsManagedCode + 0x20 [C:\source\runtime\src\coreclr\vm\codeman.cpp:4518], calling coreclr!ExecutionManager::IsManagedCodeWithLock [C:\source\runtime\src\coreclr\vm\codeman.cpp:4528]
0000008EF25F9940 00007ff9af0b7d74 coreclr!Frame::UpdateFloatingPointRegisters + 0x1c [C:\source\runtime\src\coreclr\vm\frames.cpp:472], calling coreclr!ExecutionManager::IsManagedCode [C:\source\runtime\src\coreclr\vm\codeman.cpp:4508]
0000008EF25F9960 00007ff9af057a68 coreclr!HelperMethodFrame::UpdateRegDisplay + 0x1d8 [C:\source\runtime\src\coreclr\vm\arm64\stubs.cpp:429], calling coreclr!Frame::UpdateFloatingPointRegisters [C:\source\runtime\src\coreclr\vm\frames.cpp:470]
0000008EF25F9970 00007ff9af0598bc coreclr!StackFrameIterator::ProcessIp + 0x1c [C:\source\runtime\src\coreclr\vm\stackwalk.cpp:2872], calling coreclr!EECodeInfo::Init [C:\source\runtime\src\coreclr\vm\jitinterface.cpp:14541]
0000008EF25F9980 00007ff9af05c350 coreclr!StackFrameIterator::NextRaw + 0x4d8 [C:\source\runtime\src\coreclr\vm\stackwalk.cpp:2731], calling coreclr!HelperMethodFrame::UpdateRegDisplay [C:\source\runtime\src\coreclr\vm\arm64\stubs.cpp:416]
0000008EF25F99A0 00007ff9af0b7d20 coreclr!StackFrameIterator::Next + 0x20 [C:\source\runtime\src\coreclr\vm\stackwalk.cpp:1636], calling coreclr!StackFrameIterator::NextRaw [C:\source\runtime\src\coreclr\vm\stackwalk.cpp:2462]
0000008EF25F99F0 00007ff9af0b7280 coreclr!SfiInit + 0x1c0 [C:\source\runtime\src\coreclr\vm\exceptionhandling.cpp:8327], calling coreclr!StackFrameIterator::Next [C:\source\runtime\src\coreclr\vm\stackwalk.cpp:1624]
0000008EF25F9A10 00007ff950830184 (MethodDesc 00007ff94f683ce8 + 0xcc System.Runtime.ExceptionServices.InternalCalls.RhpSfiInit(System.Runtime.StackFrameIterator ByRef, Void*, Boolean, Boolean*))
0000008EF25F9A80 00007ffa95f6a804 ntdll!RtlpFreeHeapInternal + 0x36c, calling ntdll!RtlpHpLfhSubsegmentFreeBlock
0000008EF25F9AF0 00007ffa95f6a45c ntdll!RtlpHpFreeWithExceptionProtection + 0x6c, calling ntdll!RtlpFreeHeapInternal
0000008EF25F9B50 00007ff950830098 (MethodDesc 00007ff94f684080 + 0x40 System.Runtime.StackFrameIterator.Init(PAL_LIMITED_CONTEXT*, Boolean, Boolean*))
0000008EF25F9B90 00007ff950830184 (MethodDesc 00007ff94f683ce8 + 0xcc System.Runtime.ExceptionServices.InternalCalls.RhpSfiInit(System.Runtime.StackFrameIterator ByRef, Void*, Boolean, Boolean*))
0000008EF25F9BA0 00007ffa95f6a34c ntdll!RtlFreeHeap + 0x4c, calling ntdll!RtlpHpFreeWithExceptionProtection
0000008EF25F9BC0 00007ff9af03a81c coreclr!CrstBase::Leave + 0x1c [C:\source\runtime\src\coreclr\vm\crst.cpp:356]
0000008EF25F9C60 00007ff95082f9c4 (MethodDesc 00007ff94f683bc0 + 0x104 System.Runtime.EH.DispatchEx(System.Runtime.StackFrameIterator ByRef, ExInfo ByRef))
0000008EF25F9C90 00007ff95082f810 (MethodDesc 00007ff94f683b78 + 0x90 System.Runtime.EH.RhThrowEx(System.Object, ExInfo ByRef))
0000008EF25F9E20 00007ff9aefe1e04 coreclr!CallDescrWorkerInternal + 0x84 [C:\source\runtime\artifacts\obj\coreclr\windows.arm64.Release\vm\wks\CallDescrWorkerARM64.asm:4989]
0000008EF25F9E50 00007ff9af091e8c coreclr!DispatchCallSimple + 0x8c [C:\source\runtime\src\coreclr\vm\callhelpers.cpp:221], calling coreclr!CallDescrWorkerInternal [C:\source\runtime\artifacts\obj\coreclr\windows.arm64.Release\vm\wks\CallDescrWorkerARM64.asm:4929]
0000008EF25F9E70 00007ff9af151430 coreclr!operator new[] + 0x60 [C:\source\runtime\src\coreclr\utilcode\clrhost_nodependencies.cpp:348]
0000008EF25F9EB0 00007ff9af04cbb8 coreclr!CodeVersionManager::PublishVersionableCodeIfNecessary + 0x238 [C:\source\runtime\src\coreclr\vm\codeversion.cpp:1734], calling coreclr!MethodDesc::JitCompileCode [C:\source\runtime\src\coreclr\vm\prestub.cpp:593]
0000008EF25F9ED0 00007ff9af0fd58c coreclr!ExInfo::ExInfo + 0xbc [C:\source\runtime\src\coreclr\vm\exinfo.cpp:334], calling coreclr!StackTraceInfo::AllocateStackTrace [C:\source\runtime\src\coreclr\vm\excep.cpp:3289]
0000008EF25F9EF0 00007ff9af0fd40c coreclr!DispatchManagedException + 0xcc [C:\source\runtime\src\coreclr\vm\exceptionhandling.cpp:5673], calling coreclr!ExInfo::ExInfo [C:\source\runtime\src\coreclr\vm\exinfo.cpp:331]
0000008EF25F9F10 00007ff9af0fd480 coreclr!DispatchManagedException + 0x140 [C:\source\runtime\src\coreclr\vm\exceptionhandling.cpp:5695], calling coreclr!DispatchCallSimple [C:\source\runtime\src\coreclr\vm\callhelpers.cpp:171]
0000008EF25F9F40 00007ff9af0fd3bc coreclr!DispatchManagedException + 0x7c [C:\source\runtime\src\coreclr\vm\exceptionhandling.cpp:5665], calling coreclr!GetHRFromThrowable [C:\source\runtime\src\coreclr\vm\excep.cpp:2633]
0000008EF25FA180 00007ff9af04e644 coreclr!MethodDesc::JitCompileCodeLocked + 0xac [C:\source\runtime\src\coreclr\vm\prestub.cpp:939], calling coreclr!UnsafeJitFunction [C:\source\runtime\src\coreclr\vm\jitinterface.cpp:12877]
0000008EF25FA1D0 00007ff9af04e6d8 coreclr!MethodDesc::JitCompileCodeLocked + 0x140 [C:\source\runtime\src\coreclr\vm\prestub.cpp:1006], calling coreclr!PrepareCodeConfig::SetNativeCode [C:\source\runtime\src\coreclr\vm\prestub.cpp:1862]
0000008EF25FA1E0 00007ff9af04e504 coreclr!MethodDesc::JitCompileCodeLockedEventWrapper + 0x174 [C:\source\runtime\src\coreclr\vm\prestub.cpp:820], calling coreclr!MethodDesc::JitCompileCodeLocked [C:\source\runtime\src\coreclr\vm\prestub.cpp:928]
0000008EF25FA200 00007ff94feac0fc (MethodDesc 00007ff94f758bb0 + 0x3c System.Runtime.Intrinsics.Vector128.Widen(System.Runtime.Intrinsics.Vector128`1<Byte>))
0000008EF25FA240 00007ff94feac088 (MethodDesc 00007ff94f90ea80 + 0x478 System.Text.Ascii.Widen[[System.Runtime.Intrinsics.Vector128`1[[System.Byte, System.Private.CoreLib]], System.Private.CoreLib],[System.Runtime.Intrinsics.Vector128`1[[System.UInt16, System.Private.CoreLib]], System.Private.CoreLib]](System.Runtime.Intrinsics.Vector128`1<Byte>))
0000008EF25FA280 00007ff94f6df1e8 (MethodDesc 00007ff94f903918 + 0x270 System.Text.Ascii.WidenAsciiToUtf1_Vector[[System.Runtime.Intrinsics.Vector128`1[[System.Byte, System.Private.CoreLib]], System.Private.CoreLib],[System.Runtime.Intrinsics.Vector128`1[[System.UInt16, System.Private.CoreLib]], System.Private.CoreLib]](Byte*, Char*, UIntPtr ByRef, UIntPtr))
0000008EF25FA290 00007ffa95f6a804 ntdll!RtlpFreeHeapInternal + 0x36c, calling ntdll!RtlpHpLfhSubsegmentFreeBlock
0000008EF25FA340 00007ff95085b904 (MethodDesc 00007ff95091de10 + 0x64 System.Net.HttpResponseHeaderExtensions.GetName(System.Net.HttpResponseHeader)), calling 00007ff94f6a0270
```

### PR DESCRIPTION
**Pull request by janvorli**
There was an issue with unwinding native code functions in case of calls to no-return function placed at an end of a function code block. The return address was not in range of the function code, so RtlLookupFunctionEntry was not finding anything, we were thinking that it was a leaf function due to that and tried to unwind using LR only, which was wrong and resulted in staying on the same instruction. Thus the unwinding ended up in an infinite loop for those cases. The fix, that matches what RtlUnwind does, is to adjust the instruction pointer at call sites back. This is arm64 specific.

Close #101921

### CODE REVIEW

File: src/coreclr/vm/stackwalk.cpp [hunk 1]
```diff
@@ -553,6 +553,13 @@ PCODE Thread::VirtualUnwindCallFrame(T_CONTEXT* pContext,
     UINT_PTR            uImageBase;
     PT_RUNTIME_FUNCTION pFunctionEntry;
 
+#if !defined(TARGET_UNIX) && defined(CONTEXT_UNWOUND_TO_CALL)
```
Comment (jkotas) [inline src/coreclr/vm/stackwalk.cpp:556]: When is `CONTEXT_UNWOUND_TO_CALL` not defined on Windows here?

I see `CONTEXT_UNWOUND_TO_CALL` defined for both x64 and arm64 in Windows SDK.

Comment (janvorli) [reply src/coreclr/vm/stackwalk.cpp:556]: Hmm, that's strange. In pal.h we don't define it for x64 and Windows also doesn't set it for non-arm.

Comment (janvorli) [reply src/coreclr/vm/stackwalk.cpp]: I've added a commit to change that ifdef to TARGET_ARM64

**Review by jkotas — APPROVED** [review]
Thanks

**Review by mangod9 — APPROVED** [review]
