### PR TITLE
Re-work fix for flow graph update.

### LINKED ISSUE #40094: [Perf -10%] System.Text.RegularExpressions.Tests.Perf_Regex_Common (2)
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/f3f23b4bde8b0a449d57ef600d99560ac97a784e...5ff4db1a5d22efb02300457d9a7a3154a7a5b0cb)

### Regressions in System.Text.RegularExpressions.Tests.Perf_Regex_Common

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
Email_IsNotMatch | 354.11 ns | 380.00 ns | 1.07 |  | True
Email_IsMatch | 257.82 ns | 289.67 ns | 1.12 |  | True

graph
graph
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_28_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Text.RegularExpressions.Tests.Perf_Regex_Common.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.RegularExpressions.Tests.Perf_Regex_Common*';
```
<details>

#### System.Text.RegularExpressions.Tests.Perf_Regex_Common.Email_IsNotMatch(Options: IgnoreCase, Compiled)

```log
[351.514 ; 362.555) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[362.555 ; 375.809) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[375.809 ; 394.434) | @@@@@@@@@@@@@@@@@@@@@@@@
```
#### System.Text.RegularExpressions.Tests.Perf_Regex_Common.Email_IsMatch(Options: IgnoreCase, Compiled)

```log
[255.611 ; 262.054) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[262.054 ; 267.995) | @@@@@@@@@@@@@@@@@@@@@@
[267.995 ; 274.438) | 
[274.438 ; 279.884) | 
[279.884 ; 286.328) | @@
[286.328 ; 295.294) | @@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by erozenfeld**
In #39878 I switched fgUpdateChangedFlowGraph to call fgComputeReachability,
which both removes unreachable blocks and calls fgComputeDoms. As mentioned
in that PR, in addition to removing unreachable blocks fgRemoveUnreachableBlocks
updates `BBF_LOOP_HEAD` flags even if no unreachable blocks were found. That resulted
in some diffs, both positive and negative, from downstream effects: e.g., in some cases
we now recognize more loops, which changes weights, etc.

Some of the negative diffs affected benchmarks we are tracking, e.g., in #40094
`System.Text.RegularExpressions.Tests.Perf_Regex_Common` had a 10% regression
because of codegen diffs in the large dynamic method created when compiling regular expressions.

Because of these regressions, I decided to go with a more surgical fix for the original issue (assert when
computing dominators after inlining GC polls). The downstream phases don't really need the dominator
info so I changed fgUpdateChangedFlowGraph to not re-compute dominators after GC poll inlining.

This reverses all diffs from #39878 and fixes #40094.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@AndyAyersMS @dotnet/jit-contrib PTAL

File: src/coreclr/src/jit/flowgraph.cpp [hunk 1]
```diff
@@ -3722,7 +3726,8 @@ PhaseStatus Compiler::fgInsertGCPolls()
     {
         noway_assert(opts.OptimizationEnabled());
         fgReorderBlocks();
-        fgUpdateChangedFlowGraph();
+        constexpr bool computeDoms = false;
```
Comment (AndyAyersMS) [inline src/coreclr/src/jit/flowgraph.cpp:3729]: `const` isn't sufficient...?

**Review by AndyAyersMS — APPROVED** [review]
LGTM

File: src/coreclr/src/jit/flowgraph.cpp (hunk 1 above)
Comment (erozenfeld) [reply src/coreclr/src/jit/flowgraph.cpp:3729]: `const` would've worked too.

**Comment by erozenfeld** [comment]
CopyCtorTest fails in other PRs as well, e.g., #40160. 
@davidwrighton

**Comment by davidwrighton** [comment]
@erozenfeld Yes I've noticed that. I've just disabled the test on Mono, and have a PR out to fix it on X86. Sorry about that.
