### PR TITLE
Remove CreateFalse node during lowering, if MaskToVector is getting removed

### LINKED ISSUE #113338: JIT: Assertion failed 'node->IsUnusedValue() && "found an unmarked unused value"' during 'Lowering nodeinfo'
```csharp
// Generated by Fuzzlyn v2.4 on 2025-03-09 17:40:34
// Run on Arm64 Windows
// Seed: 2919831583372544736-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256,armsve
// Reduced from 184.8 KiB to 1.0 KiB in 00:02:55
// Hits JIT assert in Release:
// Assertion failed 'node->IsUnusedValue() && "found an unmarked unused value"' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Lowering nodeinfo' (IL size 134; hash 0xade6b36b; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\lir.cpp Line: 1706
// 
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class C1
{
    public double F0;
}

public class Program
{
    public static void Main()
    {
        C1 vr27 = default(C1);
        var vr28 = Vector128.CreateScalar(-1).AsVector();
        var vr29 = Vector128.CreateScalar(0).AsVector();
        var vr30 = Sve.CreateTrueMaskUInt32();
        var vr31 = Vector128.CreateScalar(1757780578U).AsVector();
        var vr32 = Sve.CreateFalseMaskUInt32();
        var vr33 = Sve.ConditionalSelect(vr30, vr31, vr32);
        var vr34 = Vector.Create<uint>(0);
        var vr35 = Vector128.CreateScalar(687899908U).AsVector();
        var vr36 = Sve.ConditionalSelect(vr33, vr34, vr35);
        var vr37 = Sve.ShiftRightArithmetic(vr29, vr36);
        if (Sve.TestFirstTrue(vr28, vr37))
        {
            System.Console.WriteLine(System.BitConverter.DoubleToUInt64Bits(vr27.F0));
        }
    }
}
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by kunalspathak**
During lowering, if we see `CndSel(AllTrue, op2, op3)`, we replace it with `op2` and delete `AllTrue` and `op3`. If `op3` is `AllFalse`, we remove it too. However, it can be wrapped in `MaskToVector(AllFalse)` and in such case, we would just delete `MaskToVector` node and not `AllFalse` node. Fixed by removing that node as well.

Fixes: #113338

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @dotnet/arm64-contrib

**Comment by kunalspathak** [comment]
most of the failures seems to be https://github.com/dotnet/runtime/issues/113534 which is fixed in https://github.com/dotnet/runtime/pull/114228. I will merge `main`, just to be sure.

File: src/coreclr/jit/lowerarmarch.cpp [hunk 1]
```diff
@@ -4160,6 +4160,14 @@ GenTree* Lowering::LowerHWIntrinsicCndSel(GenTreeHWIntrinsic* cndSelNode)
...
                 {
+                    if (nestedOp3->OperIsConvertMaskToVector())
+                    {
+                        GenTree*       zeroMask   = nestedOp3->AsHWIntrinsic()->Op(1);
+                        NamedIntrinsic zeroMaskId = zeroMask->AsHWIntrinsic()->GetHWIntrinsicId();
+                        assert((zeroMaskId >= NI_Sve_CreateFalseMaskByte) &&
+                               (zeroMaskId <= NI_Sve_CreateFalseMaskUInt64));
+                        BlockRange().Remove(zeroMask);
+                    }
                     BlockRange().Remove(nestedOp3);
```
Comment (jakobbotsch) [inline src/coreclr/jit/lowerarmarch.cpp:4171]: Given that we already have the `nestedOp3->SetUnusedValue()` fallback, can we just remove this code entirely and just unconditionally mark it as unused?

Comment (kunalspathak) [reply src/coreclr/jit/lowerarmarch.cpp:4171]: Probably. I am not sure if `CheckLIR` will complain about anything. Let me try it.

**Review by jakobbotsch — APPROVED** [review]

**Comment by kunalspathak** [comment]
osx/arm64 fuzzlyn failure is https://github.com/dotnet/runtime/issues/113940
