### PR TITLE
Mono: support CallConvSuppressGCTransition

### LINKED ISSUE #46451: [Mono] Implement support for CallConvSuppressGCTransition
See #38134.  The CoreCLR implementation is in #46343

This gives the ability to declare a function pointer that can be called without a GC transition.

For example:
```csharp
delegate* unmanaged[Cdecl, SuppressGCTransition]<int*, int> fptr
        = (delegate* unmanaged[Cdecl, SuppressGCTransition]<int*, int>)GetNextUIntFunctionPointer();
```

The call to `GetNextUintFunctionPointer` returns a pointer to some unmanaged function.  By declaring its calling convention as `[Cdecl, SuppressGCTransition]` (as opposed to `[Cdecl]`) the caller code does not need to do a managed-to-native transition when calling through `fptr`.  All the rules of [`SuppressGCTransitionAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.suppressgctransitionattribute?view=net-5.0) still apply: the native function can't block, throw exceptions, call back into the runtime, manipulate locks or other concurrency primitives, etc.

---

Re-enable `Interop/PInvoke/Attributes/SuppressGCTransition/SuppressGCTransitionTest/` in `src/tests/issues.targets` once this is fixed.

### PR DESCRIPTION
**Pull request by lambdageek**
* Parse modopt encoded calling conventions
   Add `suppress_gc_transition` bit to `MonoMethodSignature` to add support for the `SuppressGCTransition` unmanaged calling convention modifier.

* Don't emit a wrapper on `calli` if `suppress_gc_transition` is set 

   This adds support for `delegate* unmanaged[Cdecl, SuppressGCTransition] <TRet, TArgs...>` function pointers. (And other base calling conventions other than Cdecl).

* Allow blittable types in `mono_marshal_get_native_func_wrapper_indirect`

   This was already used by C++/CLI, so the C# function pointers spec allows blittable types in unmanaged function pointer types.

* Remove SuppressGCTransitionTest from exclude list

Fixes #46451, Contributes to https://github.com/dotnet/runtime/issues/38480

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
Don't forget to re-enable the SuppressGCTransition runtime test test. It's disabled in issues.targets.

**Comment by lambdageek** [comment]
> Don't forget to re-enable the SuppressGCTransition runtime test test. It's disabled in issues.targets.

Done. It's the last commit in the PR 😁

File: src/mono/mono/metadata/marshal.c [hunk 1]
```diff
@@ -3688,13 +3688,19 @@ mono_marshal_get_native_func_wrapper_indirect (MonoClass *caller_class, MonoMeth
 	g_assert (!sig->hasthis && ! sig->explicit_this);
 	g_assert (!sig->is_inflated && !sig->has_type_parameters);
 
+#if 0
+	/*
```
Comment (vargaz) [inline src/mono/mono/metadata/marshal.c:3692]: How can non-blittable types be passed to unmanaged code, how are they marshalled ?

**Review by vargaz — APPROVED** [review]

File: src/mono/mono/metadata/marshal.c (hunk 1 above)
Comment (lambdageek) [reply src/mono/mono/metadata/marshal.c:3692]: (I'm going by what I see in https://github.com/dotnet/runtime/issues/46402#issuecomment-756486124)

It works the same way as a normal pinvoke: the wrapper does marshalling based on the managed signature.  we don't know the exact callee, but we know the types.
