### PR TITLE
Include key in FrozenDictionary.this[] KeyNotFoundException

### LINKED ISSUE #98588: `FrozenDictionary<,>` doesn't include the key in `KeyNotFoundException`
We fixed `Dictionary<,>` to include the key in the exception message. We should do the same for `FrozenDictionary<,>`.

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/98588

### CODE REVIEW

File: src/libraries/System.Collections.Immutable/src/System/Collections/ThrowHelper.cs [hunk 1]
```diff
@@ -26,8 +26,8 @@ public static void ThrowIfNull(object arg, [CallerArgumentExpression(nameof(arg)
             throw new ArgumentNullException(paramName);
 
         [DoesNotReturn]
-        public static void ThrowKeyNotFoundException() =>
-            throw new KeyNotFoundException();
+        public static void ThrowKeyNotFoundException<TKey>(TKey key) =>
+            throw new KeyNotFoundException(SR.Format(SR.Arg_KeyNotFoundWithKey, key));
```
Comment (danmoseley) [inline src/libraries/System.Collections.Immutable/src/System/Collections/ThrowHelper.cs:30]: This will not be a useful message for some types of key e.g. object - is that ok?

**Review by danmoseley — APPROVED** [review]

File: src/libraries/System.Collections.Immutable/src/System/Collections/ThrowHelper.cs (hunk 1 above)
Comment (stephentoub) [reply src/libraries/System.Collections.Immutable/src/System/Collections/ThrowHelper.cs:30]: It's what Dictionary does

**Review by eiriktsarpalis — APPROVED** [review]
