### PR TITLE
JIT: Build and consume FMA and Permute node operands in standard order

### LINKED ISSUE #102773: SPMI Replay failing sporadically
There looks to be a non-deterministic failure occuring in some SPMI replay runs across a range of PRs:
```
[11:07:25] ISSUE: <ASSERT> #288834 D:\a\_work\1\s\src\coreclr\jit\scopeinfo.cpp (864) - Assertion failed '!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' in 'System.Numerics.Tensors.TensorPrimitives+TanOperatorDouble:Invoke(System.Runtime.Intrinsics.Vector128`1[double]):System.Runtime.Intrinsics.Vector128`1[double]' during 'Generate code' (IL size 686; hash 0x5f971363; FullOpts)
```

It looks to trigger more reliably on x86 but also fails sometimes on x64, neither platform reproduces it everytime: https://dev.azure.com/dnceng-public/public/_build?definitionId=150&_a=summary

The `Invoke` method in question isn't really doing anything particularly special, it's mostly just doing some basic arithmetic operations overall: https://source.dot.net/#System.Numerics.Tensors/System/Numerics/Tensors/netcore/TensorPrimitives.Tan.cs,b0e53fd55e442a32,references

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=689641
Build error leg or test failing: runtime-coreclr superpmi-replay (Build SuperPMI replay windows x86 checked)
Pull request: https://github.com/dotnet/runtime/pull/102702

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "'!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' in 'System.Numerics.Tensors.TensorPrimitives+TanOperatorDouble",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=689641
**Error message validated:** `['!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' in 'System.Numerics.Tensors.TensorPrimitives+TanOperatorDouble`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 5/28/2024 5:44:27 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by jakobbotsch**
The building and consumption of these operands can happen in op1, op2, op3 order regardless of whether the codegen uses the registers in a different order.

Fix #102773

### CODE REVIEW

File: src/coreclr/jit/lsraxarch.cpp [hunk 1]
```diff
@@ -2544,11 +2544,24 @@ int LinearScan::BuildHWIntrinsic(GenTreeHWIntrinsic* intrinsicTree, int* pDstCou
...
+                    }
+                    else if (op == emitOp2)
+                    {
+                        srcCount += BuildDelayFreeUses(op, emitOp1);
+                    }
+                    else if (op == emitOp3)
+                    {
+                        srcCount += op->isContained() ? BuildOperandUses(op) : BuildDelayFreeUses(op, emitOp1);
+                    }
+                }
```
Comment (jakobbotsch) [inline src/coreclr/jit/lsraxarch.cpp:2564]: This could probably be cleaned up to just build the uses directly without first figuring out `emitOp1, emitOp2, emitOp3`, but I didn't really understand all the constraints around `copiesUpperBits`, the preferred target and the contained operand, so I gave up on trying to do it.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @kunalspathak @tannergooding 

This should hopefully fix the failures for good this time.

**Review by tannergooding — APPROVED** [review]

**Comment by tannergooding** [comment]
@jakobbotsch there's another case that is doing something similar with operand switching for `PermuteVar*x2`, I'm guessing it needs an identical fix?

**Comment by tannergooding** [comment]
We also, more generally have various commutative nodes that also dynamically pick the `tgtPrefUse` and `containable` node via logic in `BuildRMWUses`. These ones look fine because they look to always build `op1` then `op2` and codegen (such as `genCodeForBinary`) then consumes them in the same order via `genConsumeOperands` even if codegen is going to swap them about

**Comment by jakobbotsch** [comment]
> @jakobbotsch there's another case that is doing something similar with operand switching for `PermuteVar*x2`, I'm guessing it needs an identical fix?

Ah, good catch, same thing should be applied there. Pushed it to this PR.

> We also, more generally have various commutative nodes that also dynamically pick the `tgtPrefUse` and `containable` node via logic in `BuildRMWUses`. These ones look fine because they look to always build `op1` then `op2` and codegen (such as `genCodeForBinary`) then consumes them in the same order via `genConsumeOperands` even if codegen is going to swap them about

Yeah, that looks fine. Seems likely we could try to clean up/unify some of these cases.

**Review by tannergooding — APPROVED** [review]

**Comment by jakobbotsch** [comment]
[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699590&view=ms.vss-build-web.run-extensions-tab)
