### PR TITLE
Fix handling of corrupting state exceptions

### LINKED ISSUE #103018: Corrupting exceptions are not turned into fail fasts
## Repro:

It should not be possible to catch corrupting exceptions like AccessViolationExceptions.

```csharp
using System;

class Test
{
    static unsafe void Main()
    {
        try {
            *(int*)0x1235678 = 0x12345;
        }
        catch (Exception e) {
            Console.WriteLine("Here");
        }
    }
}
```

## Actual behavior

`Here`

## Expected behavior

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Test.Main()
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by janvorli**
The new EH is not correctly handling corrupting state exceptions. Instead of failing fast, the exceptions are actually handled like other exceptions and can be caught by the user code.

This change fixes it. Besides fixing the issue, I had to introduce a way to trim exception handling code frames from the stack trace reported by the failfast, otherwise the output would be confusing.

As an additional change, I've noticed that hardware exceptions under WinDbg don't trigger the WinDbg first chance exception mechanism. I've recently fixed the same for software exceptions, this adds the same for hardware ones.

Close #103018

### CODE REVIEW

File: src/coreclr/vm/excep.cpp [hunk 1]
```diff
@@ -6557,6 +6559,8 @@ void HandleManagedFaultNew(EXCEPTION_RECORD* pExceptionRecord, CONTEXT* pContext
     args[ARGNUM_0] = DWORD_TO_ARGHOLDER(exceptionCode);
     args[ARGNUM_1] = PTR_TO_ARGHOLDER(&exInfo);
 
+    FirstChanceExceptionNotification();
```
Comment (jkotas) [inline src/coreclr/vm/excep.cpp:6562]: The legacy EH rethrows the exception as the original exception code. This will rethrow it as `EXCEPTION_COMPLUS`. 

I look at the EH rethrowing in the legacy EH as a shortcoming, not as a feature. I am not sure whether it makes sense to replicate it here.

File: src/coreclr/vm/exceptionhandling.cpp [hunk 2]
```diff
@@ -8295,6 +8322,8 @@ extern "C" bool QCALLTYPE SfiInit(StackFrameIterator* pThis, CONTEXT* pStackwalk
     {
         GCX_COOP();
         UpdatePerformanceMetrics(&pThis->m_crawl, false, ((uint8_t)pExInfo->m_kind & (uint8_t)ExKind::RethrowFlag) == 0);
+
+        FailFastIfCorruptingStateException(pExInfo);
```
Comment (jkotas) [inline src/coreclr/vm/exceptionhandling.cpp:8326]: I am wondering whether it would be possible to do this earlier. The earlier we failfast for corrupting exceptions, the better.

**Review by jkotas — APPROVED** [review]
Thanks!

File: src/coreclr/vm/excep.cpp (hunk 1 above)
Comment (janvorli) [reply src/coreclr/vm/excep.cpp:6562]: Let me remove it for this PR as it is unrelated to the actual fix and reason about this later.

File: src/coreclr/vm/exceptionhandling.cpp (hunk 2 above)
Comment (janvorli) [reply src/coreclr/vm/exceptionhandling.cpp:8326]: We may be able move it to the beginning of the SfiInit, but other than that, this method is the first native code that gets called when we have the throwable so that I can get a proper message out of it.
