### PR TITLE
Fix type generator test failures

### LINKED ISSUE #43466: CG2 Outerloop Test Failure: TypeGeneratorTests throwing System.BadImageFormatException
Example run:
https://dev.azure.com/dnceng/public/_build/results?buildId=853947&view=ms.vss-test-web.build-test-results-tab&runId=27279090&resultId=102633&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Tests failing:
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest612\\Generated612\\Generated612.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest613\\Generated613\\Generated613.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest614\\Generated614\\Generated614.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest681\\Generated681\\Generated681.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest682\\Generated682\\Generated682.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest683\\Generated683\\Generated683.cmd

Platform:
Win10 (x64, arm64)

Item log:
<pre>
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B (COR_E_BADIMAGEFORMAT))
         at Framework.M.G2_C221.T.T[T0,T1,W](W inst, String exp)
         at Framework.ConstrainedCallsTest()
         at Framework.Main()
      
      Return code:      1
      Raw output file:      C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\Reports\Loader.classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\Generated682.output.txt
      Raw output:
      BEGIN EXECUTION
      Generated682.dll
      TestFramework.dll
              2 file(s) copied.
      Response file: C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\\composite-r2r.dll.rsp
      C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\IL\*.dll
      -o:C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\\composite-r2r.dll
      --targetarch:x64
      --verify-type-and-field-layout
      -O
      -r:C:\h\w\B90C0986\p\System.*.dll
      -r:C:\h\w\B90C0986\p\Microsoft.*.dll
      -r:C:\h\w\B90C0986\p\mscorlib.dll
      -r:C:\h\w\B90C0986\p\netstandard.dll
      " "dotnet" "C:\h\w\B90C0986\p\crossgen2\crossgen2.dll" @"C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\\composite-r2r.dll.rsp"   --composite"
      Emitting R2R PE file: C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\composite-r2r.dll
      Emitting R2R PE file: C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\Generated682.dll
      Emitting R2R PE file: C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\TestFramework.dll
       "C:\h\w\B90C0986\p\corerun.exe" Generated682.dll 
      ========================== Method Calling Test ==========================
[Snip...]
</pre>

### LINKED ISSUE #43467: CG2 Outerloop Test Failure: TypeGeneratorTests asserting in MethodDesc::FindOrCreateAssociatedMethodDesc
Example run:
https://dev.azure.com/dnceng/public/_build/results?buildId=853947&view=ms.vss-test-web.build-test-results-tab&runId=27279090&resultId=105033&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Platform:
Win10 (x64, arm64)

Item log:
[Full log example](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-80f8b66adcfd4ff6b7/Loader.classloader.TypeGeneratorTests.TypeGeneratorTest0-299/console.197fae69.log?sv=2019-07-07&se=2020-11-04T09%3A49%3A55Z&sr=c&sp=rl&sig=FDkBqhAgPX1CStSZ3aXnpTsM%2F6aR7vSueSixezXBBI0%3D) since it's a verbose test, just the failure stack is below.

<pre>
Could Not Find C:\h\w\B90C0986\w\A45F08B7\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest295\Generated295\composite-r2r.dll.rsp
      
      Assert failure(PID 3544 [0x00000dd8], Thread: 3848 [0x0f08]): false
      
      CORECLR! MethodDesc::FindOrCreateAssociatedMethodDesc + 0x1F9E (0x00007ff9`b4efc3b6)
      CORECLR! ZapSig::DecodeMethod + 0x5A1 (0x00007ff9`b4e2e021)
      CORECLR! ZapSig::DecodeMethod + 0xF0 (0x00007ff9`b4e2e2bc)
      CORECLR! LoadDynamicInfoEntry + 0xB8A (0x00007ff9`b4ceeb92)
      CORECLR! Module::FixupNativeEntry + 0x28B (0x00007ff9`b4bc239b)
      CORECLR! Module::FixupDelayListAux<Module *,int (__cdecl Module::*)(CORCOMPILE_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *)> + 0x485 (0x00007ff9`b4e2ed6d)
      CORECLR! ReadyToRunInfo::GetEntryPoint + 0x390 (0x00007ff9`b4e30840)
      CORECLR! MethodDesc::GetPrecompiledR2RCode + 0xD8 (0x00007ff9`b4d98de4)
      CORECLR! MethodDesc::GetPrecompiledCode + 0xBE (0x00007ff9`b4d98b4a)
      CORECLR! MethodDesc::PrepareILBasedCode + 0x20D (0x00007ff9`b4d9ba79)
          File: F:\workspace\_work\1\s\src\coreclr\src\vm\genmeth.cpp Line: 811
          Image: C:\h\w\B90C0986\p\CoreRun.exe
</pre>

Tests failing:
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest1\Generated1\Generated1.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest14\Generated14\Generated14.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest15\Generated15\Generated15.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest16\Generated16\Generated16.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest17\Generated17\Generated17.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest18\Generated18\Generated18.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest19\Generated19\Generated19.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest20\Generated20\Generated20.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest21\Generated21\Generated21.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest22\Generated22\Generated22.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest23\Generated23\Generated23.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest24\Generated24\Generated24.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest25\Generated25\Generated25.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest26\Generated26\Generated26.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest27\Generated27\Generated27.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest28\Generated28\Generated28.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest62\Generated62\Generated62.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest63\Generated63\Generated63.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest64\Generated64\Generated64.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest65\Generated65\Generated65.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest66\Generated66\Generated66.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest67\Generated67\Generated67.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest68\Generated68\Generated68.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest69\Generated69\Generated69.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest70\Generated70\Generated70.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest171\Generated171\Generated171.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest192\Generated192\Generated192.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest193\Generated193\Generated193.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest194\Generated194\Generated194.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest195\Generated195\Generated195.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest196\Generated196\Generated196.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest197\Generated197\Generated197.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest198\Generated198\Generated198.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest199\Generated199\Generated199.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest200\Generated200\Generated200.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest201\Generated201\Generated201.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest202\Generated202\Generated202.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest203\Generated203\Generated203.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest204\Generated204\Generated204.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest205\Generated205\Generated205.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest206\Generated206\Generated206.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest207\Generated207\Generated207.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest208\Generated208\Generated208.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest209\Generated209\Generated209.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest210\Generated210\Generated210.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest211\Generated211\Generated211.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest212\Generated212\Generated212.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest213\Generated213\Generated213.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest214\Generated214\Generated214.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest215\Generated215\Generated215.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest292\Generated292\Generated292.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest293\Generated293\Generated293.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest294\Generated294\Generated294.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest295\Generated295\Generated295.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest296\Generated296\Generated296.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest297\Generated297\Generated297.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest298\Generated298\Generated298.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest299\Generated299\Generated299.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest300\Generated300\Generated300.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest301\Generated301\Generated301.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest302\Generated302\Generated302.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest303\Generated303\Generated303.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest304\Generated304\Generated304.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest305\Generated305\Generated305.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest306\Generated306\Generated306.cmd
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest307\Generated307\Generated307.cmd

### PR DESCRIPTION
**Pull request by davidwrighton**
- Fix issue where method token referred to derived type but method was actually defined on base type
  - Previously the methods did not carry enough state to determine when to emit the owner type of the method, and which exact type was the owning type. The new logic computes it from the token in the presence of a proper instantiation context, which allows for correct operation.

- Fix issue where constrained dispatch on a method of a valuetype would not put in the correct owner type
  - Issue fixed by determining if the token resolves to a method on the same type as the eventual target method, or if it needs to have a specific owning type specified

In general these issues where both caused by confusion around exactly the correct owning type, and it turned out that computation could not be computed within the signature emitter code, but instead needed to be computed in the JIT at point of use. Fortunately, we had a structure `MethodWithToken` that is used in these (and only these situations). Finally, I also made a pass through the emitter and related logic to remove various band-aids that had built up over the last few years to make all the tests and applications pass. I believe that the new logic should be correct in the general case.

Bonus tweak...  Use parallelism when compiling the framework composite images with crossgen2, and fix bug in composite image generation where mangled symbol names might conflict.

Fixes #43466 and fixes #43467

### CODE REVIEW

File: src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DelegateCtorSignature.cs [hunk 1]
```diff
@@ -88,7 +88,7 @@ public override int CompareToImpl(ISortableNode other, CompilerComparer comparer
             if (result != 0)
                 return result;
 
-            return _methodToken.CompareTo(otherNode._methodToken);
+            return _methodToken.Token.CompareTo(otherNode._methodToken.Token);
```
Comment (trylek) [inline src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DelegateCtorSignature.cs:91]: Is there a guarantee that the same token here will always be accompanied by the same method? To put it yet another way, why can't we use the comparison of the complete MethodAndToken instances?

**Review by trylek — APPROVED** [review]
Looks great to me, I'm amazed by the cleanness and simplicity of your fixes, thank you!

File: src/tests/build.cmd [hunk 2]
```diff
@@ -637,7 +637,7 @@ set __CrossgenCmd="%__RepoRootDir%\dotnet.cmd" "%CORE_ROOT%\R2RTest\R2RTest.dll"
 if defined __CompositeBuildMode (
     set __CrossgenCmd=%__CrossgenCmd% --composite
 ) else (
-    set __CrossgenCmd=%__CrossgenCmd% --large-bubble
+    set __CrossgenCmd=%__CrossgenCmd% --large-bubble --crossgen2-parallelism 1
```
[the remark this answers is not in the document]
Comment (davidwrighton) [reply src/tests/build.cmd:640]: Ah, sorry, yes it was intentional. CG2 parallelism is a very significant performance win in composite build mode, especially when working with a debug coreclr. On my machine, this reduces the time to run crossgen by about a factor of 8.

File: src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DelegateCtorSignature.cs (hunk 1 above)
Comment (davidwrighton) [reply src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DelegateCtorSignature.cs:91]: Well, we don't have a comparison for MethodAndToken instances. And as a slight detail, my analysis of pathways into this code indicate that it will always be unique as long as the target method is also unique. I agree though, its not very obvious.

File: src/tests/build.cmd (hunk 2 above)
[the remark this answers is not in the document]
Comment (trylek) [reply src/tests/build.cmd:640]: I see, thanks for clarifying, that sounds good to me.

File: src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DelegateCtorSignature.cs (hunk 1 above)
Comment (trylek) [reply src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DelegateCtorSignature.cs:91]: Ah, OK, makes sense.

Comment (davidwrighton) [reply src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DelegateCtorSignature.cs:91]: Um, now that I think about it, that's a fair bit of hubris on my part that my analysis is certain to be correct now, and will remain correct in the future. I'll add the appropriate comparisons such that this is more reliable.
