### PR TITLE
Fix race condition in LoaderAllocator::CompareExchangeValueInHandle

### LINKED ISSUE #70742: Race condition results in Assembly reference equality being false
### Description

I was investigating a random instability running our NUnit tests.  The issue traced back to two assembly instances not being equal when I'm pretty sure they should be.

There is a race condition that results in the following randomly being false when multiple threads trigger the loading of an assembly for the first time

```
static void Worker()
{
    var asm1 = typeof(Class1).Assembly;
    var asm2 = typeof(Class1).Assembly;

    if (asm1 != asm2)
        Console.WriteLine("Assemblies were not equal!!!");
```

When this happens, one of the assembly instances will not appear in `AssemblyLoadContext.Default.Assemblies`

I was able to reproduce this on both Windows & Mac using .NET 6.0.100.  

I was able to reproduce using .NET 5.0.301 on windows.  I didn't test Mac.  The issue appears to be much more common on net5.  Every time I've ran on net5 the issue has happened in less than 10 iterations.

### Reproduction Steps

1) Check out the repro project here https://github.com/mrvoorhe/AssemblyRaceBugRepro

2) Run `dotnet build`

2) `dotnet run --project Runner/Runner.csproj`

3) Wait for the program to end.

If the issue doesn't happen, there are some parameters you can tweak at the top of `Runner/Program.cs` that may make it easier to reproduce

### Expected behavior

```
Quiting.  The issue never happened
```

### Actual behavior

```
Assemblies were not equal!!!
asm1.GetHashCode() = 4032828
asm2.GetHashCode() = 37489757
Default ALC contains asm1 = False
Default ALC contains asm2 = True
Run 76 complete
Quiting because behavior was reproduced
```

### Regression?

The issue does not seem to happen on .NET Framework.  I've completed a few thousand iterations without hitting the problem.   

I was able to reproduce the issue using .NET 5.0.301 on windows.  I didn't test net5 on mac.  The issue appears to be much more common on net5.  Every time I've ran on net5 the issue has happened in less than 10 iterations.

The repro project has targets setup for net5.0 and net48

### Known Workarounds

_No response_

### Configuration

I reproduced on 6.0.100 and 5.0.301

I reproduced on Windows 11 and macOS Monterey

x64 Windows.  M1 Mac Pro.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkotas**
The method was not actually using interlocked operation. It made it possible for multiple different values to win.

Fixes #70742

### CODE REVIEW

**Comment by jkotas** [comment]
The repro attached to the bug did not work for me. I was only able to reproduce the problem by suspending threads under debugger in specific locations.

File: src/coreclr/vm/loaderallocator.cpp [hunk 1]
```diff
@@ -919,10 +919,11 @@ OBJECTREF LoaderAllocator::CompareExchangeValueInHandle(LOADERHANDLE handle, OBJ
...
     {
         OBJECTREF *ptr = (OBJECTREF *)(((UINT_PTR)handle) - 1);
-        gc.previous = *ptr;
-        if ((*ptr) == gc.compare)
+
+        gc.previous = InterlockedCompareExchangeT(ptr, gc.value, gc.compare);
+        if (gc.previous == gc.compare)
         {
-            SetObjectReference(ptr, gc.value);
+            ErectWriteBarrier(ptr, gc.value);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/loaderallocator.cpp:926]: I'd like to confirm my understanding here. The handle above was properly updated using `InterlockedCompareExchangeT`, but we need to also update the GC's card tables so need to also call `ErectWriteBarrier`, right?

Comment (jkotas) [reply src/coreclr/vm/loaderallocator.cpp:926]: Right

Comment (VSadov) [reply src/coreclr/vm/loaderallocator.cpp:926]: does this also need
```
#ifdef _DEBUG
        Thread::ObjectRefAssign(ptr);
#endif
```

Perhaps it is easier to just call `COMInterlocked::CompareExchangeObject(ptr, gc.value, gc.compare)` ?

Comment (jkotas) [reply src/coreclr/vm/loaderallocator.cpp:926]: `Thread::ObjectRefAssign(ptr);` is not necessary here. It is only necessary when the assigned OBJECTREF is OBJECTREF on stack. It is not the case here.

`COMInterlocked::CompareExchangeObject` is FCall. It is difficult to call FCalls from guts of the runtime. It requires to suppressing number of contract violations.

**Review by VSadov — APPROVED** [review]
Thanks!

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/vm/loaderallocator.cpp (hunk 1 above)
Comment (VSadov) [reply src/coreclr/vm/loaderallocator.cpp:926]: I guess the need to InterlockExchange references does not come too often, so we do not have a regular, not an FCall helper. 
It is indeed easy to forget about the barrier, which is needed, since this can be a cross-generational assignment.

**Comment by jkotas** [comment]
ARM queues are backed up: https://github.com/dotnet/arcade/issues/9692
