### PR TITLE
[MONO][MARSHAL] Initialize ilgen with a flag

### LINKED ISSUE #74603: Race condition on marshal-ilgen init
### Description

Because of this change: https://github.com/dotnet/runtime/pull/71203, `mono_marshal_ilgen_init` gets called later, after comnponents are initilized. This allows for potential races in initilizing the callback table.

I propose to fix this by making a pointer to `ilgen_marshal_cb`, and initing that pointer atomically (with a CAS) after the table has been constructed.

See comment here: https://github.com/dotnet/runtime/pull/71203#issuecomment-1227590206

### Reproduction Steps

Race condition; not easily reproducible.

### Expected behavior

Runs

### Actual behavior

```
Assertion at /home/uweigand/runtime/src/mono/mono/component/marshal-ilgen.c:63, condition `!ilgen_cb_inited' not met
```
with this call stack:
```
  #14 0x000003ffb327d0ac in mono_assertion_message (file=0x3ffb33865a0 "/home/uweigand/runtime/src/mono/mono/component/marshal-ilgen.c", line=63, condition=0x3ffb33865e0 "!ilgen_cb_inited") at /home/uweigand/runtime/src/mono/mono/eglib/goutput.c:226
  #15 0x000003ffb3321a30 in mono_install_marshal_callbacks_ilgen (cb=0x3ff9a3f16d0) at /home/uweigand/runtime/src/mono/mono/component/marshal-ilgen.c:63
  #16 0x000003ffb33221ce in mono_marshal_ilgen_init () at /home/uweigand/runtime/src/mono/mono/component/marshal-ilgen.c:2858
  #17 0x000003ffb3322106 in get_marshal_cb () at /home/uweigand/runtime/src/mono/mono/component/marshal-ilgen.c:2753
  #18 0x000003ffb3321f24 in mono_emit_marshal_ilgen (m=0x3ff9a3f1bc8, argnum=0, t=0x3ff8ad98b68, spec=0x0, conv_arg=0, conv_arg_type=0x3ff8ad99ed8, action=MARSHAL_ACTION_CONV_IN, lightweigth_cb=0x3ffb33910e8 <marshal_lightweight_cb>) at /home/uweigand/runtime/src/mono/mono/component/marshal-ilgen.c:2810
  #19 0x000003ffb2e54c52 in mono_emit_marshal (m=0x3ff9a3f1bc8, argnum=0, t=0x3ff8ad98b68, spec=0x0, conv_arg=0, conv_arg_type=0x3ff8ad99ed8, action=MARSHAL_ACTION_CONV_IN) at /home/uweigand/runtime/src/mono/mono/metadata/marshal.c:3226
  #20 0x000003ffb2f219aa in emit_native_wrapper_ilgen (image=0x2aa18a8b950, mb=0x3ff7c90eb50, sig=0x3ff8ad99cc8, piinfo=0x3ff8ad98af0, mspecs=0x3ff7c8f47e0, func=0x3ff82d81750 <CompressionNative_DeflateInit2_>, flags=(EMIT_NATIVE_WRAPPER_CHECK_EXCEPTIONS | EMIT_NATIVE_WRAPPER_RUNTIME_MARSHALLING_ENABLED)) at /home/uweigand/runtime/src/mono/mono/metadata/marshal-lightweight.c:937
  #21 0x000003ffb2e5755a in mono_marshal_emit_native_wrapper (image=0x2aa18a8b950, mb=0x3ff7c90eb50, sig=0x3ff8ad99cc8, piinfo=0x3ff8ad98af0, mspecs=0x3ff7c8f47e0, func=0x3ff82d81750 <CompressionNative_DeflateInit2_>, flags=(EMIT_NATIVE_WRAPPER_CHECK_EXCEPTIONS | EMIT_NATIVE_WRAPPER_RUNTIME_MARSHALLING_ENABLED)) at /home/uweigand/runtime/src/mono/mono/metadata/marshal.c:6300
  #22 0x000003ffb2e56b6c in mono_marshal_get_native_wrapper (method=0x3ff8ad98af0, check_exceptions=1, aot=0) at /home/uweigand/runtime/src/mono/mono/metadata/marshal.c:3672
  #23 0x000003ffb30328e8 in compile_special (method=0x3ff8ad98af0, error=0x3ff9a3f2c38) at /home/uweigand/runtime/src/mono/mono/mini/mini-runtime.c:2469
  #24 0x000003ffb30322b0 in mono_jit_compile_method_with_opt (method=0x3ff8ad98af0, opt=374417919, jit_only=0, error=0x3ff9a3f2c38) at /home/uweigand/runtime/src/mono/mono/mini/mini-runtime.c:2672
  #25 0x000003ffb3031c04 in jit_compile_method_with_opt_cb (arg=0x3ff9a3f28e8) at /home/uweigand/runtime/src/mono/mono/mini/mini-runtime.c:2762
  #26 0x000003ffb3029ea8 in jit_compile_method_with_opt (params=0x3ff9a3f28e8) at /home/uweigand/runtime/src/mono/mono/mini/mini-runtime.c:2778
  #27 0x000003ffb3029c7e in mono_jit_compile_method (method=0x3ff8ad98af0, error=0x3ff9a3f2c38) at /home/uweigand/runtime/src/mono/mono/mini/mini-runtime.c:2797
  #28 0x000003ffb31677ba in common_call_trampoline (regs=0x3ff9a3f2db8, code=0x3ffa806234c "\a\340\300\001", m=0x3ff8ad98af0, vt=0x0, vtable_slot=0x0, error=0x3ff9a3f2c38) at /home/uweigand/runtime/src/mono/mono/mini/mini-trampolines.c:618
  #29 0x000003ffb3166b8e in mono_magic_trampoline (regs=0x3ff9a3f2db8, code=0x3ffa806234c "\a\340\300\001", arg=0x3ff8ad98af0, tramp=0x3ffb3de02c8 "\300X") at /home/uweigand/runtime/src/mono/mono/mini/mini-trampolines.c:759
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

ppc, but probably possible on other architectures

### Other information

_No response_

### LINKED ISSUE #77090: [Mono] System.Text.RegularExpressions.Tests source generator tests crash in DeflateInit2_
```
=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at <unknown> <0xffffffff>
	  at ZLibStreamHandle:DeflateInit2_ <0x00073>
	  at System.IO.Compression.ZLibNative:CreateZLibStreamForDeflate <0x000a3>
	  at System.IO.Compression.Deflater:.ctor <0x00133>
	  at System.IO.Compression.DeflateStream:InitializeDeflater <0x00087>
	  at System.IO.Compression.DeflateStream:.ctor <0x0006b>
	  at System.IO.Compression.DeflateStream:.ctor <0x0004b>
	  at System.Reflection.PortableExecutable.DebugDirectoryBuilder:WriteEmbeddedPortablePdbData <0x00107>
	  at System.Reflection.PortableExecutable.DebugDirectoryBuilder:AddEmbeddedPortablePdbEntry <0x00087>
	  at Microsoft.Cci.PeWriter:WritePeToStream <0x00cdb>
	  at Microsoft.CodeAnalysis.Compilation:SerializePeToStream <0x001b7>
	  at Microsoft.CodeAnalysis.Compilation:SerializeToPeStream <0x006f7>
	  at Microsoft.CodeAnalysis.Compilation:Emit <0x00587>
```

## Build Information
Log: https://dev.azure.com/dnceng-public/public/_build/results?buildId=53859&view=ms.vss-test-web.build-test-results-tab&runId=1102432&paneView=debug&resultId=196512
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=53859
Build error leg or test failing: System.Text.RegularExpressions.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/77088

```json
{
  "ErrorMessage": "at ZLibStreamHandle:DeflateInit2_",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[56035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56035)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56035&view=ms.vss-test-web.build-test-results-tab&runId=1149346&resultId=196550)|dotnet/runtime#77170|
|[53859](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53859)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=53859&view=ms.vss-test-web.build-test-results-tab&runId=1102432&resultId=196512)|dotnet/runtime#77088|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|2|

### PR DESCRIPTION
**Pull request by naricc**
Currently, marshal ilgen callbacks are initialized lazily *or* by having embedders call `mono_marshal_ilgen_init`, and the code for doing this has a race condition. This change modifies `mono_marshal_ilgen_init` so that it sets a flag, and if the flag is set either ilgen callbacks are installed later during startup (intead  of lazily).  If the flag is not set, and ENABLE_ILGEN is false, the noilgen callbacks are installed instead.

Installation of callbacks occurs only once before any user code is executing, so there is no longer a race condition. See discussion here: https://github.com/dotnet/runtime/pull/77383#discussion_r1003451363

Fixes: https://github.com/dotnet/runtime/issues/74603
Fixes: https://github.com/dotnet/runtime/issues/77090

### CODE REVIEW

File: src/mono/mono/metadata/marshal-lightweight.h [hunk 1]
```diff
@@ -9,4 +9,7 @@
 MONO_API void
 mono_marshal_lightweight_init (void);
 
+gboolean
+mono_marshal_did_embedder_request_ilgen_callbacks (void);
```
Comment (lambdageek) [inline src/mono/mono/metadata/marshal-lightweight.h:13]: nit: I don't like the name

maybe: `mono_marshal_is_ilgen_requested` ?

**Review by lambdageek — APPROVED** [review]
Thanks!

**Comment by naricc** [comment]
The remaining test failure appears to be this issue: https://github.com/dotnet/runtime/issues/77630

However, I am reluctant to merge this until that is resolved. That issue prevents the whole test suite from running, since it stops the product build step, and errors in this change definitely have the possibility of breaking wasm.

**Comment by naricc** [comment]
Well, it passed several other wasm lanes and the marshaling stuff doesn't vary on them. So I think this is good to merge.

**Comment by SamMonoRT** [comment]
@naricc @lambdageek - we should give this fix a few days on main and then consider backporting to servicing release
