### PR TITLE
instrumentation changes

### LINKED ISSUE #45375: GCAllocationTick_V2 ETW events are reporting wrong allocation sizes in multithreaded application
Assume we have a program which is allocating fixed amount of memory(~200MB) in a tight loop with portions of 200KB in multiple threads:
```
using System.Linq;
using System.Threading;
class Program
{
  public static void Main(string[] args)
  {
    var threadsCount = args.Any() ? int.Parse(args[0]) : 4;
    var waitHandles = new WaitHandle[threadsCount];
    int counter = 1024;
    for (int i = 0; i != threadsCount; ++i)
    {
      var waitHandle = new AutoResetEvent(false);
      var thread = new Thread(() =>
      {
        while (Interlocked.Decrement(ref counter) > 0)
        {
          var _ = new byte[200 * 1024];
        }
        waitHandle.Set();
      });
      thread.Start();
      waitHandles[i] = waitHandle;
    }
    WaitHandle.WaitAll(waitHandles);
  }
}
```

If I run this program on .NET Core 5 (Windows 10) with one thread I'll get 1023 events with 204 848 bytes allocated each which is expected. Sum of allocation sizes column: ~210MB (see PerfView status bar in the bottom). If I ran multiple times - I get same numbers:

image

However If I run this program with 4 or 8 threads, allocation sizes will start to differ and total sum will not be equal to 200MB. It fluctuates between 70(Release configuration) to 360MB. Which can't be right:

image

Should there be thread synchronization on this allocation size counter or synchronization is not viable option because of low overhead requirement?

### PR DESCRIPTION
**Pull request by Maoni0**
We've never had ETW events that had fields about time - we rely on the the timestamps of the ETW events themselves to calculate time. This checkin introduces some new events/event fields that will include time info instead of firing individual events that otherwise don't carry much info, ie, they'd just be there so we could use their timestamps, which would be a nuisance when we have many heaps.

The rationale behind firing events with time already calculated is 

1) it does reduce overhead since we don't fire as many events so we can fire these in fewer events for informational level
2) firing individual vents and having the tools interpret them isn't very useful unlike events such as `GCStart`/`GCEnd` which can be correlated with other events (eg, you get `GCStart`, and then get a bunch of other events so you know those happened after a GC started) wheras things like very GC internal things don't have this property, ie, we are not gonna care that "these other events happened during a GC and specifically during the relocation phase". 

---

Added MarkWithType events for marking due to dependent handles, newly promoted due to dead finalizable objects and `mark_steal`. Perfview needs to be updated to work with this otherwise you can't see the GCStats view (I'm submitting a PR for that).

Recorded time for marking roots (but sizedref is separate), short weak, ScanForFinalization, long weak, relocate, compact and sweep.

Added a new version that includes the size of the object that triggered the event. This is for a request from [this issue](https://github.com/dotnet/runtime/issues/49424#issuecomment-810457867). I'm unclear if the config for the threshold was requested as a runtime config or something configurable via profiling API so asked for clarification there.

Provided a new rundown `GCSettings` event that has info on settings hard to get from traces. 

Added a `GCLOHCompact` event which is fired for all heaps (heaps that didn't actually do LOH compact would have values of all 0s). I'm trying to add events that don't require a lot of correlation with other events to interpret. This is to help get an idea how long it takes to compact LOH and how reference rich it is.

Added a verbose level `GCFitBucketInfo` event which helps us with FL fitting investigation. I'm firing this for 2 things in a gen1 GC:

1) for plugs that allocated with `allocate_in_condemned_generations` the event will capture all of them with the same bucketing as we do for gen2 FL;

2) for gen2 FL we look at the largest free items that take up 25% of the FL space, or if there are too many of them we stop after walking a certain number of free items as we have to limit the amount of time we are spending here. 

---

Fixed issues -

For BGC we were reporting the pinned object count the same as the last FGC..and that causes confusion so fixed that.

Fixed https://github.com/dotnet/runtime/issues/45375

While fixing https://github.com/dotnet/runtime/issues/45375, I noticed we have another bug related to alloc tick which is we are not firing the alloc tick events correctly for LOH and POH since the ETW alloc tracking didn't seperate them... fixed this too.

Added the POH type for `GCSegmentTypeMap` which was missing in the manifest.

---

Did some cleanup in eventtrace.h - we don't need the info that's not used which means we just ended up duplicating things like `_GC_ROOT_KIND` in more places than needed. 

---

Note, I realize that I do have some inconsistency with the `FEAETURE_EVENT_TRACE` here, as in, some code should be under an `#ifdef` check but is not. I will look into a remedy for that with a separate PR.

### CODE REVIEW

**Comment by Maoni0** [comment]
@dotnet/gc please review.

@PeterSolMS please let me know if you are ok with how I structured the new `GCFitBucketInfo` event based on what we talked about.

@noahfalk PTAL at the changes in clretwall.man and the related interface changes.

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -2201,8 +2214,34 @@ size_t      gc_heap::committed_by_oh[total_oh_count] = {0, 0, 0, 0};
 
 size_t      gc_heap::current_total_committed_bookkeeping = 0;
 
+#ifdef FEATURE_EVENT_TRACE
```
Comment (mangod9) [inline src/coreclr/gc/gc.cpp:2217]: is `FEATURE_EVENT_TRACE` not enabled by default?

**Review by mangod9 — APPROVED** [review]

File: src/coreclr/gc/gc.cpp (hunk 1 above)
Comment (Maoni0) [reply src/coreclr/gc/gc.cpp:2217]: it's enabled by default but it is a "feature", as in, it may not be defined.

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -14114,6 +14220,46 @@ void allocator::thread_sip_fl (heap_segment* region)
...
+            assert (((CObjectHeader*)free_item)->IsFree());
+
+            size_t free_item_size = Align (size (free_item));
+            size_counted_total += free_item_size;
+            items_counted_total++;
+            items_counted++;
+
+            if ((size_counted_total > max_size) || (items_counted > max_item_count))
+            {
+                bucket_info[i] = items_counted;
```
Comment (PeterSolMS) [inline src/coreclr/gc/gc.cpp:14248]: So you record the *number* of items per bucket - would it be more useful to record the *cumulative size* instead? Of course then uint32_t for the bucket_info may no longer be large enough...

Comment (Maoni0) [reply src/coreclr/gc/gc.cpp:14248]: I could record the cumulative size per bucket in addition to the # of items in that bucket? the # is useful too, especially for larger buckets...

File: src/coreclr/gc/gc.cpp [hunk 3]
```diff
@@ -2943,7 +2986,22 @@ void gc_heap::fire_pevents()
...
+    uint32_t count_time_info = (settings.concurrent ? max_bgc_time_type : 
+                                (settings.compaction ? max_compact_time_type : max_sweep_time_type));
+
+    uint64_t* time_info = (settings.concurrent ? bgc_time_info : gc_time_info);
+    // We don't want to have to fire the time info as 64-bit integers as there's no need to
+    // so compress them down to 32-bit ones.
+    uint32_t* time_info_32 = (uint32_t*)time_info;
+    for (uint32_t i = 0; i < count_time_info; i++)
+    {
+        time_info_32[i] = ((time_info[i] > UINT32_MAX) ? UINT32_MAX : (uint32_t)time_info[i]);
```
Comment (PeterSolMS) [inline src/coreclr/gc/gc.cpp:3001]: Nit: this pattern of a saturating conversion to 32 bits is repeated 5 times or so - perhaps it would be good to encapsulate in an inline method like "limit_time_to_uint32"?

Comment (Maoni0) [reply src/coreclr/gc/gc.cpp:3001]: will do!

File: src/coreclr/gc/gc.cpp [hunk 4]
```diff
@@ -24119,19 +24325,28 @@ void gc_heap::mark_phase (int condemned_gen_number, BOOL mark_only_p)
...
         //decide on promotion
         if (!settings.promotion)
         {
             size_t m = 0;
             for (int n = 0; n <= condemned_gen_number;n++)
             {
+#ifdef MULTIPLE_HEAPS
                 m +=  (size_t)(dd_min_size (dynamic_data_of (n))*(n+1)*0.1);
+#else
+                m +=  (size_t)(dd_min_size (dynamic_data_of (n))*(n+1)*0.06);
```
Comment (PeterSolMS) [inline src/coreclr/gc/gc.cpp:24342]: What is the reason the constant is different between SVR and WKS?

Nit: As the rest of the formula is identical, perhaps it would be best to define a constant with a meaningful name that is different between SVR and WKS, and have the computation itself not #ifdef'd.

Comment (PeterSolMS) [reply src/coreclr/gc/gc.cpp:24342]: Oh, I see, we already had this different constant below, it's just that you folded the WKS copy of the code.

**Review by PeterSolMS — APPROVED** [review]

File: src/coreclr/vm/ClrEtwAll.man [hunk 5]
```diff
@@ -3850,6 +3971,16 @@
                            task="GarbageCollection"
                            symbol="GenAwareEnd" message="$(string.RuntimePublisher.GenAwareEndEventMessage)"/>
 
+                    <event value="208" version="0" level="win:Informational"  template="GCLOHCompact"
+                           keywords ="GCKeyword"  opcode="GCLOHCompact"
+                           task="GarbageCollection"
+                           symbol="GCLOHCompact" message="$(string.RuntimePublisher.GCLOHCompactEventMessage)"/>
+
+                    <event value="209" version="0" level="win:Verbose"  template="GCFitBucketInfo"
```
Comment (noahfalk) [inline src/coreclr/vm/ClrEtwAll.man:3979]: How verbose are these events relative to allocation_tick? I'm imagining we've got users that want to use Allocation_Tick for low overhead sampling, but because it is marked as a verbose event we are forcing them to receive all other GC verbose events even if they have no use for them.

**Review by noahfalk — COMMENTED** [review]
Mostly looked fine to me. A few thoughts overall:
1. I wasn't sure if the config mechanism for AllocTick events will be readily usable by profiler vendors. They might prefer a profiler API.
2. Emitting the rundown settings at startup too is an option if it is useful now or in the future
3. Given that these events are mostly intended for GC team's own analysis I didn't push for docs.

File: src/coreclr/gc/gc.cpp (hunk 1 above)
Comment (brianrob) [reply src/coreclr/gc/gc.cpp:2217]: Yes, and there are definitely folks that undef `FEATURE_EVENT_TRACE`.

File: src/coreclr/vm/ClrEtwAll.man [hunk 6]
```diff
@@ -1316,6 +1354,79 @@
...
+                                <Count> %12 </Count>
+                            </GCGlobalHeap_V4>
+                        </UserData>
+                    </template>
+
+                    <template tid="GCLOHCompact">
+                        <data name="ClrInstanceID" inType="win:UInt16" />
+                        <data name="Count" inType="win:UInt16"  />
+                        <struct name="Values"   count="Count"  >
+							<data name="TimePlan" inType="win:UInt32" />
```
[the remark this answers is not in the document]
Comment (Maoni0) [reply src/coreclr/vm/ClrEtwAll.man:1396]: I didn't have my IDE insert spaces for tabs for this file type... will fix.

File: src/coreclr/vm/ClrEtwAll.man [hunk 7]
```diff
@@ -1316,6 +1354,79 @@
...
+                        <data name="Reason" inType="win:UInt32" />
+                        <data name="GlobalMechanisms" inType="win:UInt32" />
+                        <data name="ClrInstanceID" inType="win:UInt16" />
+                        <data name="PauseMode" inType="win:UInt32" />
+                        <data name="MemoryPressure" inType="win:UInt32" />
+                        <data name="CondemnReasons0" inType="win:UInt32" />
+                        <data name="CondemnReasons1" inType="win:UInt32" />
+                        <data name="Count" inType="win:UInt32"  />
+                        <struct name="Values"   count="Count"  >
+							<data name="Time" inType="win:UInt32" />
```
[the remark this answers is not in the document]
Comment (Maoni0) [reply src/coreclr/vm/ClrEtwAll.man:1371]: will fix

File: src/coreclr/vm/ClrEtwAll.man (hunk 5 above)
Comment (Maoni0) [reply src/coreclr/vm/ClrEtwAll.man:3979]: we already have other verbose level event in GC fired during a GC like the join events that are a lot more verbose than this. in fact we have informational level GC events that are fired more frequent than this one (eg, the GCMarkWithType is fired multiple times per heap and this event is fired once per heap during only gen1 GCs). and the users are already receiving them regardless whether they use them or not (often they don't since most tools don't interpret most of the GC events). 

overhead is relative - alloc tick is low overhead compared to other mechanisms (eg, it's very low ahead via the alloc monitoring with profiling API). for tracing I view it as medium overhead compared to events we _usually_ collect. certainly they are a lot more verbose than events fired during GCs.

File: src/coreclr/vm/ClrEtwAll.man [hunk 8]
```diff
@@ -8335,6 +8510,7 @@
                 <string id="RuntimePublisher.ExecutionCheckpointTaskMessage" value="ExecutionCheckpoint" />
                 <string id="RuntimePublisher.ProfilerTaskMessage" value="Profiler" />
 
+				<string id="RundownPublisher.GCTaskMessage" value="GC" />
```
[the remark this answers is not in the document]
Comment (Maoni0) [reply src/coreclr/vm/ClrEtwAll.man:8513]: will fix

File: src/coreclr/vm/ClrEtwAll.man (hunk 5 above)
Comment (noahfalk) [reply src/coreclr/vm/ClrEtwAll.man:3979]: As long as the relative increase in event volume isn't large (comparing verbose before this PR to verbose afterwards) it should be fine : )

File: src/coreclr/gc/gc.cpp (hunk 2 above)
Comment (PeterSolMS) [reply src/coreclr/gc/gc.cpp:14248]: Looks good, thanks!
