### PR TITLE
Exit with quick_exit when using debug UCRT

### LINKED ISSUE #108640: Test failure: JIT/jit64/mcc/interop/mcc_i03/mcc_i03.cmd
**Failed in:** [runtime-coreclr r2r 20241006.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=828920&view=ms.vss-test-web.build-test-results-tab&runId=21561748&resultId=118488&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open
    - JIT/jit64/mcc/interop/mcc_i03/mcc_i03.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hwA7CB08E3wB59C09C8uploadsmccinteropmcc_i03output.txt
Raw output:
BEGIN EXECUTION
mcc_i03.dll
native_i0c.dll
native_i0s.dll
native_i1c.dll
native_i1s.dll
native_i3c.dll
native_i3s.dll
native_i5c.dll
native_i5s.dll
native_i6c.dll
native_i6s.dll
native_i7c.dll
native_i7s.dll
native_i8c.dll
native_i8s.dll
       15 file(s) copied.
 6:57:42.77
Response file: C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03mcc_i03.dll.rsp
C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03IL-CG2mcc_i03.dll
-o:C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03mcc_i03.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwA7CB08E3pSystem.*.dll
-r:C:hwA7CB08E3pMicrosoft.*.dll
-r:C:hwA7CB08E3p\xunit.*.dll
-r:C:hwA7CB08E3pmscorlib.dll
-r:C:hwA7CB08E3p
etstandard.dll
"Running CrossGen2:  "C:hwA7CB08E3pcrossgen2crossgen2.exe" @"C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03mcc_i03.dll.rsp"   -r:C:hwA7CB08E3wB59C09C8eJITjit64jit64_2IL-CG2*.dll  -r:C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03IL-CG2*.dll"
Emitting R2R PE file: C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03mcc_i03.dll
"Running R2RDump:  "dotnet" "C:hwA7CB08E3p
2rdump
2rdump.dll" --header --sc --in C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03mcc_i03.dll --out C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03mcc_i03.dll.r2rdump --val"
 6:57:43.60
 6:57:43.60
Response file: C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i0c.dll.rsp
C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03IL-CG2
ative_i0c.dll
-o:C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i0c.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwA7CB08E3pSystem.*.dll
-r:C:hwA7CB08E3pMicrosoft.*.dll
-r:C:hwA7CB08E3p\xunit.*.dll
-r:C:hwA7CB08E3pmscorlib.dll
-r:C:hwA7CB08E3p
etstandard.dll
"Running CrossGen2:  "C:hwA7CB08E3pcrossgen2crossgen2.exe" @"C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i0c.dll.rsp"   -r:C:hwA7CB08E3wB59C09C8eJITjit64jit64_2IL-CG2*.dll  -r:C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03IL-CG2*.dll"
No input files are loadable
 6:57:43.66
 6:57:43.66
Response file: C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i0s.dll.rsp
C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03IL-CG2
ative_i0s.dll
-o:C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i0s.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwA7CB08E3pSystem.*.dll
-r:C:hwA7CB08E3pMicrosoft.*.dll
-r:C:hwA7CB08E3p\xunit.*.dll
-r:C:hwA7CB08E3pmscorlib.dll
-r:C:hwA7CB08E3p
etstandard.dll
"Running CrossGen2:  "C:hwA7CB08E3pcrossgen2crossgen2.exe" @"C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i0s.dll.rsp"   -r:C:hwA7CB08E3wB59C09C8eJITjit64jit64_2IL-CG2*.dll  -r:C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03IL-CG2*.dll"
No input files are loadable
 6:57:43.71
 6:57:43.72
Response file: C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i1c.dll.rsp
C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03IL-CG2
ative_i1c.dll
-o:C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i1c.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwA7CB08E3pSystem.*.dll
-r:C:hwA7CB08E3pMicrosoft.*.dll
-r:C:hwA7CB08E3p\xunit.*.dll
-r:C:hwA7CB08E3pmscorlib.dll
-r:C:hwA7CB08E3p
etstandard.dll
"Running CrossGen2:  "C:hwA7CB08E3pcrossgen2crossgen2.exe" @"C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i1c.dll.rsp"   -r:C:hwA7CB08E3wB59C09C8eJITjit64jit64_2IL-CG2*.dll  -r:C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03IL-CG2*.dll"
No input files are loadable
 6:57:43.77
 6:57:43.77
Response file: C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i1s.dll.rsp
C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03IL-CG2
ative_i1s.dll
-o:C:hwA7CB08E3wB59C09C8eJITjit64mccinteropmcc_i03
ative_i1s.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwA7CB08E3pSystem.*.dll
-r:C:hw
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor4|0_5(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Resolves #108640.

Cc @dotnet/ilc-contrib @janvorli

### CODE REVIEW

**Comment by jkotas** [comment]
I expect that this will break tracing tests. Tracing depends on C runtime shutdown notification to close the session: https://github.com/dotnet/runtime/blob/be013ed306ea178907baca6763601f9b2e69a400/src/coreclr/nativeaot/Runtime/startup.cpp#L375

Also, the same fundamental problem exists in regular coreclr as well.

**Comment by janvorli** [comment]
It seems that the only way to fix the problem and keep the cleanup at exit untouched would be to link to ucrt dynamically. The cleanup then occurs in DllMain of the library on DLL_PROCESS_DETACH.

**Comment by janvorli** [comment]
I meant the low level CRT cleanup, not the atexit stuff.

**Comment by filipnavara** [comment]
> Tracing depends on C runtime shutdown notification to close the session

Playing the devil's advocate, you can always make that a `at_quick_exit`.

**Comment by jkotas** [comment]
> Ah, damn, that's C++ and not in ucrt, so that would not help.

There is no C++ in the mix. Neither `atexit` or `at_quick_exit` are directly exposed by the ucrt.dll. They are statically linked stubs that use CRT global state for .exes and module-local state for .dlls. For example:
- Exiting via `quick_exit` from `main` still runs `atexit` handlers registered in other .dlls in the process, but it does not run `at_quick_exit` handlers registered in other .dlls in the process
- Exiting via `quick_exit` from .dll with statically linked CRT (the "global" state is module-local with static linking) runs `at_quick_exit` handlers registered in the given .dll, but it does not run `atexit` nor `at_quick_exit` handlers registered by the .exe

**Comment by jkotas** [comment]
It looks like we do not have any diagnostics tests that would be sensitive for improperly closed eventpipe sessions.

I think we should also update https://github.com/dotnet/runtime/pull/109006#issuecomment-2421826781 to register the callbacks using `at_quick_exit `. 

Looks good to me otherwise.

**Comment by teo-tsirpanis** [comment]
> link to ucrt dynamically

Why don't we do it currently?

**Comment by jkotas** [comment]
> Why don't we do it currently?

We do not dynamically link to debug CRT to save us from troubles with deploying it to CI machines.

We do dynamically link to release CRT (ie the shipping bits link to release CRT).

**Comment by teo-tsirpanis** [comment]
Thanks, I remember trying to link some static libraries with dynamic CRT linkage and getting errors related to static/dynamic CRT mismatch. But that was years ago and I will try it again.

File: src/coreclr/nativeaot/Runtime/startup.cpp [hunk 1]
```diff
@@ -372,7 +372,12 @@ extern "C" bool RhInitialize(bool isDll)
 #endif
 
 #if defined(HOST_WINDOWS) || defined(FEATURE_PERFTRACING)
-    atexit(&OnProcessExit);
+#if defined(HOST_WINDOWS)
+    at_quick_exit
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/startup.cpp:376]: This is changing the behavior of shipping release bits. `at_quick_exit` handlers are not called on normal program termination. 

`OnProcessExit` is no longer called on normal program termination -> the tracing shutdown is no longer during shutdown -> we should see tracing tests fail -> we have a test hole since no tracing tests are failing.

I am leaving a suggestion with a fix.

File: src/coreclr/nativeaot/Bootstrap/main.cpp [hunk 2]
```diff
@@ -222,7 +223,12 @@ int main(int argc, char* argv[])
     if (initval != 0)
         return initval;
 
+#if !defined(DEBUG) || !defined(_WIN32)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Bootstrap/main.cpp:226]:
```suggestion
#if defined(DEBUG) && defined(_WIN32)
    // quick_exit works around Debug UCRT shutdown issues: https://github.com/dotnet/runtime/issues/108640
    quick_exit(__managed__Main(argc, argv));
#else
```
Nit: Positive conditions are easier to understand. Also, matches the polarity of ifdef in the other place we are applying the workaround.

File: src/coreclr/nativeaot/Bootstrap/main.cpp [hunk 3]
```diff
@@ -222,7 +223,12 @@ int main(int argc, char* argv[])
...
     return __managed__Main(argc, argv);
+#else
+    // quick_exit works around Debug UCRT shutdown issues: https://github.com/dotnet/runtime/issues/108640
+    quick_exit(__managed__Main(argc, argv));
```
Comment (jkotas) [inline src/coreclr/nativeaot/Bootstrap/main.cpp:230]:
```suggestion
```

File: src/coreclr/nativeaot/Runtime/startup.cpp (hunk 1 above)
Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/Runtime/startup.cpp]: Filed #114461 for the test hole.

**Review by jkotas — APPROVED** [review]
