### PR TITLE
[wasm][debugger] Implement support for null-conditional operators in simple expressions

### LINKED ISSUE #69133: [wasm][debugger] Evaluate list?.Count
1) Copied from: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1459677
2) Create a new Blazor WebAssembly app using VS2022 (17.0.4)
3) Replace Index.razor with

```
@page "/"

@code {
    protected override void OnInitialized()
    {
        List<int>? listNull = null; 
        List<int> list = new List<int>() {1};  // or this, doesn't matter
    } // Set breakpoint here
}
```

4) Set breakpoint at the end of the method (as denoted in the code)
5) Run in debug mode
6) When breakpoint is hit, open Watch window and enter `list?.Count`

EXPECTED: null is returned or Count is returned

ACTUAL: Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.ProtocolException is thrown

Also, if you try to evaluate the statement in “Immediate Window”, it will just return an empty line.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/69133.
- this PR enables support for expressions like `?.`, and `!.` in debugger watch in simple cases of member access.
- TODO: the same for array access, and method calls.

Changes:
- Added passing "forDebuggerDisplayAttribute" when calling `RuntimeGetObjectMembers` internally in `ResolveAsInstanceMember` because we need to get all the values from "forDebuggerProxyAttribute". Without it, the members we were extracting were shadowed by proxy and we were skipping some, e.g. `Count` when extracting members of a Collections.Generic.List. Now we can evaluate `list.Count` without throwing.
- Removed the mechanism at the end of `ResolveAsInstanceMember` that checked if `resolvedObject` is null and prevented from evaluation of its members when it was true. This caused throwing an exception even when user used null safety operator. Now, evaluation of `objectNull?.member` results in returning null instead of throwing while `objectNull.member` throws as expected.

### CODE REVIEW

**Review by radical — COMMENTED** [review]
partial comments

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 1]
```diff
@@ -185,17 +188,25 @@ public async Task<JObject> Resolve(string varName, CancellationToken token)
             if (scopeCache.ObjectFields.TryGetValue(varName, out JObject valueRet))
                 return await GetValueFromObject(valueRet, token);
 
-            string[] parts = varName.Split(".");
+            string[] parts = varName.Split(".", StringSplitOptions.TrimEntries);
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:191]: E.g. `DebuggerTests.EvaluateOnCallFrameTests.EvaluateMethodLocals` or `DebuggerTests.EvaluateOnCallFrameTests.AsyncLocalsInContinueWithBlock` are testing whitespaces. But in this very place it was not necessary because we were Trimming each `part` separately when processing it. I decided that instead, I will remove Trimming from `ResolveAsLocalOrThisMember` and `ResolveAsInstanceMember` and do it only once here, where you added this comment.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 2]
```diff
@@ -185,17 +188,25 @@ public async Task<JObject> Resolve(string varName, CancellationToken token)
...
             if (parts.Length == 0)
                 return null;
 
             JObject retObject = await ResolveAsLocalOrThisMember(parts[0]);
+            bool isRootNullSafe = parts[0].LastOrDefault() == '?';
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs]: After changing it turns out we have some failing tests. When parts[0] is empty and it can happen when we are testing with `expression = ".a."` then we end with parts = { "", "a", "" }. So indexing 0th element is not safe. When we use FirstOrDefault we are sure not to index wrong. The expressions cannot be too long as they are manually provided by users so iterating through one part to get the last element does not seem painful here because we would have to check for nullOrEmpty in the indexing scenario additionally. What do you think?

[the remark this answers is not in the document]
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:196]: Shouldn't we fail in that case? `.a.` isn't a valid expression by itself.

[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs]: Actually yes, it's a good idea to finish the processing early with throwing "RefError". I decided to do the same for `parts.Count == 0` because it's a similar situation and the expected result does not change.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 3]
```diff
@@ -1148,6 +1148,54 @@ public async Task EvaluateLocalObjectFromAssemblyNotRelatedButLoaded()
...
+                // we have no way of returning int? for null values, 
+                // so we return the last non-null class name
+                await EvaluateOnCallFrameAndCheck(id,
+                   ("list.Count", TNumber(1)),
+                   ("list?.Count", TNumber(1)),
+                   ("listNull", TObject("System.Collections.Generic.List<int>", is_null: true)),
+                   ("listNull?.Count", TObject("System.Collections.Generic.List<int>", is_null: true)),
+                   ("tc?.memberList?.Count", TNumber(2)),
+                   ("tc?.memberListNull?.Count", TObject("System.Collections.Generic.List<int>", is_null: true)),
+                   ("tc.memberListNull?.Count", TObject("System.Collections.Generic.List<int>", is_null: true)),
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1168]: https://github.com/dotnet/runtime/issues/69543

**Comment by radical** [comment]
I think for this, if the expression is not a simple `a`, or `a.b.c`, then we should compile it with roslyn, so that we don't have to explicitly handle `?., ?[], !., ![], .. ` etc.

**Comment by ilonatommy** [comment]
> I think for this, if the expression is not a simple `a`, or `a.b.c`, then we should compile it with roslyn, so that we don't have to explicitly handle `?., ?[], !., ![], .. ` etc.

You are right, resolving e.g. `tc?.memberList[0]` will fail with this PR. However, evaluation of expressions in our `CompileAndRunTheExpression` function where we use Roslyn is tricky because SyntaxNode does not work as expected every time. In the quoted expression it recognizes correctly `tc?.memberList[0]` as `ConditionalAccessExpressionSyntax` but treats `memberList` as identifier instead of `MemberAccessExpressionSyntax`. Support of null-condition operator in complex expressions requires a lot of changes to the logic, if not a complex refactor of the existing mechanism (I mean: removing the separation between `Resolve` and `CompileAndRunTheExpression` and merging them into one process). 
Good news is that `!` operator can be handled in this PR, it does not change anything in the evaluation process, so we can remove it from the expression and evaluate as if it was not there.

**Comment by ilonatommy** [comment]
Test failure in staging is not connected with the changes.

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs [hunk 4]
```diff
@@ -382,6 +382,13 @@ private static async Task<IList<JObject>> ResolveElementAccess(IEnumerable<Eleme
             return values;
         }
 
+        internal static string RemoveNullSuppression(string expression)
+        {
+            expression = expression.Trim();
+            expression = expression.Replace("!.", ".").Replace("![", "[").Replace("!(", "(");
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:388]: don't remove these here because these can be in a quoted string in the expression, like `foo.Bar("x ?.qwe")`, which shouldn't be removed.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 5]
```diff
@@ -187,18 +190,27 @@ public async Task<JObject> Resolve(string varName, CancellationToken token)
...
-            if (parts.Length == 0)
-                return null;
+            ArraySegment<string> parts = new ArraySegment<string>(varName.Split(".", StringSplitOptions.TrimEntries));
+            if (parts.Count == 0 || string.IsNullOrEmpty(parts[0]))
+                throw new ReturnAsErrorException($"Failed to resolve expression: {varName}", "ReferenceError");
 
             JObject retObject = await ResolveAsLocalOrThisMember(parts[0]);
-            if (retObject != null && parts.Length > 1)
-                retObject = await ResolveAsInstanceMember(string.Join('.', parts[1..]), retObject);
+            bool hasNullCondition = parts[0][^1] == '?';
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:198]: I would suggest `bool throwOnNullReference = parts[0][^1] != '?';`, because `throw on null reference` is the behavior that is relevant to us.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 6]
```diff
@@ -226,7 +237,11 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
                     localsFetched = true;
                 }
 
-                if (scopeCache.Locals.TryGetValue(nameTrimmed, out JObject obj))
+                // remove null-condition, otherwise TryGet by name fails
+                if (name[^1] == '?')
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:241]: .. remove if `== '!'` also.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 7]
```diff
@@ -242,33 +257,61 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
...
 
                 return null;
             }
 
-            async Task<JObject> ResolveAsInstanceMember(string expr, JObject baseObject)
+            async Task<JObject> ResolveAsInstanceMember(ArraySegment<string> parts, JObject baseObject, bool hasNullCondition)
             {
+                // if the prevPart has "?" at the end: true
+                bool hasResolvedObjNullCondition = hasNullCondition;
+                bool isPrevPartNull = false;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:271]: This is not needed, AFAIU.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 8]
```diff
@@ -242,33 +257,61 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
...
-                JToken objRet = valueOrError.Value.FirstOrDefault(objPropAttr => objPropAttr["name"].Value<string>() == nameTrimmed);
+                JToken objRet = valueOrError.Value.FirstOrDefault(objPropAttr => objPropAttr["name"].Value<string>() == name);
                 if (objRet != null)
                     return await GetValueFromObject(objRet, token);
 
                 return null;
             }
 
-            async Task<JObject> ResolveAsInstanceMember(string expr, JObject baseObject)
+            async Task<JObject> ResolveAsInstanceMember(ArraySegment<string> parts, JObject baseObject, bool hasNullCondition)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:267]: `hasNullCondition` -> `throwOnNullReference`

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 9]
```diff
@@ -242,33 +257,61 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
...
             {
+                // if the prevPart has "?" at the end: true
+                bool hasResolvedObjNullCondition = hasNullCondition;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:270]: new local is not needed, the arg can be used instead.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 10]
```diff
@@ -242,33 +257,61 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
...
+                    string partTrimmed = parts[i];
                     if (partTrimmed.Length == 0)
                         return null;
 
+                    // current value of resolvedObject is on parts[i - 1]
+                    if (isPrevPartNull || resolvedObject.IsNullValuedObject())
+                    {
+                        // trying null.$member
+                        if (!hasResolvedObjNullCondition)
+                            throw new ReturnAsErrorException($"Cannot access member \"{partTrimmed}\" of a null-valued object.", "ReferenceError");
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:284]: Error can be more explicit about what happened - `"Expression threw NullReferenceException trying to access \"{partTrimmed}\" on a null-valued object.`.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 11]
```diff
@@ -242,33 +257,61 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
...
+                // if the prevPart has "?" at the end: true
+                bool hasResolvedObjNullCondition = hasNullCondition;
+                bool isPrevPartNull = false;
                 JObject resolvedObject = baseObject;
-                string[] parts = expr.Split('.');
-                for (int i = 0; i < parts.Length; i++)
+                for (int i = 0; i < parts.Count; i++)
                 {
-                    string partTrimmed = parts[i].Trim();
+                    string partTrimmed = parts[i];
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:275]: Since this is not trimmed anymore, rename the variable.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 12]
```diff
@@ -242,33 +257,61 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
...
+                    }
+
+                    bool hasCurrentPartNullCondition = partTrimmed.Last() == '?';
+                    hasResolvedObjNullCondition = hasCurrentPartNullCondition;
+
+                    // cannot resolve the members but can check if null condition is
+                    // correctly applied and if we should throw or return null-object
                     if (!DotnetObjectId.TryParse(resolvedObject?["objectId"]?.Value<string>(), out DotnetObjectId objectId))
-                        return null;
+                        continue;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:303]: You can check here if `resolvedObject` was a primitive type (except `string`), so maybe check `type == 'number'`, and throw if that's the case.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 13]
```diff
@@ -242,33 +257,61 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
...
 
-                    ValueOrError<GetMembersResult> valueOrError = await proxy.RuntimeGetObjectMembers(sessionId, objectId, null, token);
+                    var args = JObject.FromObject(new { forDebuggerDisplayAttribute = true });
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:305]: Is there a test covering this?

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 14]
```diff
@@ -1147,8 +1147,61 @@ public async Task EvaluateLocalObjectFromAssemblyNotRelatedButLoaded()
...
+            });
+
+        [ConditionalFact(nameof(RunningOnChrome))]
+        public async Task EvaluateNullObjectPropertiesNegative() => await CheckInspectLocalsAtBreakpointSite(
+            $"DebuggerTests.EvaluateNullableProperties", "Evaluate", 6, "Evaluate",
+            $"window.setTimeout(function() {{ invoke_static_method ('[debugger-test] DebuggerTests.EvaluateNullableProperties:Evaluate'); 1 }})",
+            wait_for_event_fn: async (pause_location) =>
+            {
+                var id = pause_location["callFrames"][0]["callFrameId"].Value<string>();
+                var (_, res) = await EvaluateOnCallFrame(id, "listNull.Count", expect_ok: false);
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1180]: It's difficult to quickly glance at the cases being tested. Instead use:

```csharp
                async Task CheckEvaluateFail(string expr, string message)
                {
                    (_, Result _res) = await EvaluateOnCallFrame(id, expr, expect_ok: false);
                    AssertEqual(message, _res.Error["result"]?["description"]?.Value<string>(), $"Expression '{expr}' - wrong error message");
                }
```

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 15]
```diff
@@ -1147,8 +1147,61 @@ public async Task EvaluateLocalObjectFromAssemblyNotRelatedButLoaded()
...
+                AssertEqual("Cannot access member \"Count\" of a null-valued object.",
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1181]: And the updated tests, with some new ones:
```csharp
                var id = pause_location["callFrames"][0]["callFrameId"].Value<string>();
                await CheckEvaluateFail("list.Count.x", "Cannot find member 'x' on primitive type");

                await CheckEvaluateFail("listNull.Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("listNull!.Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("tcNull.memberListNull.Count", "Expression threw NullReferenceException trying to access \"memberListNull\" on a null-valued object.");
                await CheckEvaluateFail("tc.memberListNull.Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("tcNull?.memberListNull.Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("listNull?.Count.NonExistingProperty", "Expression threw NullReferenceException trying to access \"NonExistingProperty\" on a null-valued object.");

                await CheckEvaluateFail("tc?.memberListNull!  .Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("tc?. memberListNull!.Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("tc?.memberListNull.Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("tc!  .memberListNull!.Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("tc!.memberListNull.  Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("tcNull?.Sibling.memberListNull?.Count", "Expression threw NullReferenceException trying to access \"memberListNull?\" on a null-valued object.");

                await CheckEvaluateFail("listNull?", "Expected expression.");
                await CheckEvaluateFail("listNull!.Count", "Expression threw NullReferenceException trying to access \"Count\" on a null-valued object.");
                await CheckEvaluateFail("x?.p", "Operation '?' not allowed on primitive type - 'x?'");
```

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 16]
```diff
@@ -1147,8 +1147,61 @@ public async Task EvaluateLocalObjectFromAssemblyNotRelatedButLoaded()
...
+                    res.Error["result"]?["description"]?.Value<string>(), "wrong error message");
+                (_, res) = await EvaluateOnCallFrame(id, "listNull!.Count", expect_ok: false);
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1183]: And `// await CheckEvaluateFail("x?.ToString()", "Operation '?' not allowed on type 'int'");` can be a case for a future PR.

File: src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs [hunk 17]
```diff
@@ -1401,6 +1401,24 @@ public static void Evaluate()
             string localString = "S*T*R";
         }
     }
+
+    public static class EvaluateNullableProperties
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs:1405]: The tests need these changes though in `debugger-evaluate-test.cs`:
```diff
@@ -1371,7 +1371,7 @@ public static void Evaluate()
             var test = new TestClass();
         }
     }
-
+
     public static class PrimitiveTypeMethods
     {
         public class TestClass
@@ -1408,6 +1408,7 @@ class TestClass
         {
             public List<int> memberListNull = null;
             List<int> memberList = new List<int>() {1, 2};
+            public TestClass Sibling { get; set; }
         }
         static void Evaluate()
         {
@@ -1417,6 +1418,11 @@ static void Evaluate()
             List<int> list = new List<int>() {1};
             TestClass tc = new TestClass();
             TestClass tcNull = null;
+            string str = "str#value";
+            string str_null = null;
+            int x = 5;
+            int? x_null = null;
+            int? x_val = x;
         }
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 18]
```diff
@@ -187,18 +190,27 @@ public async Task<JObject> Resolve(string varName, CancellationToken token)
...
-                retObject = await ResolveAsInstanceMember(string.Join('.', parts[1..]), retObject);
+            bool hasNullCondition = parts[0][^1] == '?';
+            if (retObject != null && parts.Count > 1)
+            {
+                // cannot resolve instance member on a primitive type,
+                // try compiling to check if it's not a method on primitive
+                var typeName = retObject["className"]?.Value<string>();
+                if (MonoSDBHelper.IsPrimitiveType(typeName))
+                    return null;
+
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:206]: For returning null so that we can exit `Resolve()` and enter `CompileAndRunTheExpression()` where such things are handled. There's no point in continuing in `Resolve`, so we want to quit early. It won't return anything sensible when primitive is not the last thing in the expression.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 13 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:305]: Yes, it was done to fix existing tests. It's the 1st dot from the PR description: https://github.com/dotnet/runtime/pull/69307#issue-1235045964.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 12 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:303]: By throwing here this way we will block executing methods on primitives. I will check out if there's any other solution.

File: src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs (hunk 4 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/EvaluateExpression.cs:388]: Good point. Moving the removal it to `ResolveAsInstanceMember`.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 7 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:271]: You're right. I replaced it with earlier update of `throwOnNullReference` and continuing.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs (hunk 16 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1183]: https://github.com/dotnet/runtime/issues/70337

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 12 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs]: What's more I decided to leave the `objectId` check, so not exchanging it to `type` value comparison. We want strings to behave the same was as other primitives at this stage because we don't support evaluation of their properties yet (it is planned to be solved in https://github.com/dotnet/runtime/issues/66823). Till this PR is fixed I will throw "not supported" error for strings so that users won't get confused.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 19]
```diff
@@ -264,24 +256,27 @@ async Task<JObject> ResolveAsLocalOrThisMember(string name)
...
-                    string partTrimmed = parts[i];
-                    if (partTrimmed.Length == 0)
+                    string part = parts[i];
+                    if (part.Length == 0)
                         return null;
 
+                    if (part[^1] == '!')
+                        part = part.Remove(part.Length - 1);
+
+                    bool hasCurrentPartNullCondition = part[^1] == '?';
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:272]: You can get rid of this local too. And update `throwOnNullReference = partTrimmed[^1] != '?';` after the `if (resolvedObject.IsNullValuedObject())` block.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 20]
```diff
@@ -311,15 +307,15 @@ async Task<JObject> ResolveAsInstanceMember(ArraySegment<string> parts, JObject
                     }
 
                     if (hasCurrentPartNullCondition)
-                        partTrimmed = partTrimmed.Remove(partTrimmed.Length - 1);
-                    JToken objRet = valueOrError.Value.FirstOrDefault(objPropAttr => objPropAttr["name"]?.Value<string>() == partTrimmed);
+                        part = part.Remove(part.Length - 1);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:312]: Shouldn't this be done for both `?`, and `!`?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 21]
```diff
@@ -311,15 +307,15 @@ async Task<JObject> ResolveAsInstanceMember(ArraySegment<string> parts, JObject
                     }
 
                     if (hasCurrentPartNullCondition)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:311]: And use an explicit condition here like `if (part[^1] is '?' or '!')`, so we don't mistakenly have `bool throwOnNullReference = parts[0][^1] != '?'; if (!throwOnNullReference)` - which would match any character other than `?`

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 20 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:312]: It's done a bit earlier (https://github.com/dotnet/runtime/blob/25e907cf5ecfdec23d37d2d3047ceaf2c14c9a3e/src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs#L269)

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 19 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:272]: um this is fine too. I was doing it a little differently, but this if fine.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs (hunk 20 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:312]: But we can merge them both (in the place where we currently remove only '?'). I won't change anything

**Review by radical — APPROVED** [review]
LGTM! 👍
