### PR TITLE
[wasm][debugger] Indexing with expression 

### LINKED ISSUE #67029: [wasm][debugger] Indexing with expression does not work
Indexing arrays with mathematical expressions e.g.
```
int [] arr = new int[]{ 1, 2, 3 };
arr[1 + 1]; //error
```
error:
`Cannot evaluate '(arr[1 + 1]\n)`

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/67029.
Introduces indexing with mathematical expressions.

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs [hunk 1]
```diff
@@ -406,7 +408,16 @@ public async Task<JObject> Resolve(ElementAccessExpressionSyntax elementAccess,
                                     indexObject ??= await Resolve(argParm.Identifier.Text, token);
                                     elementIdxStr += indexObject["value"].ToString();
                                 }
-                                // FixMe: indexing with expressions, e.g. x[a + 1]
+                                // indexing with expressions, e.g. x[a + 1]
+                                else
+                                {
+                                    SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(arg + @";", cancellationToken: token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:414]: IIUC, we can use the `$"{arg};"` directly instead of creating a `SyntaxTree`. Creating that would be useful if we wanted to make changes to the expression.

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs:414]: Oh, sorry, `arg` is not a string. It think you should use `arg.ToString()` for both the arguments passed to `EvaluateSimpleExpression`.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 2]
```diff
@@ -627,6 +627,50 @@ async Task EvaluateOnCallFrameFail(string call_frame_id, params (string expressi
...
+           {
+               var id = pause_location["callFrames"][0]["callFrameId"].Value<string>();
+
+               await EvaluateOnCallFrameAndCheck(id,
+                   ("f.numArray2D[0, j - 1]", TNumber(1)), // 0, 0
+                   ("f.numArray2D[f.idx1, i + j]", TNumber(4)), // 1, 1
+                   ("f.numArray2D[(f.idx1 - j) * 5, i + j]", TNumber(2)), // 0, 1
+                   ("f.numArray2D[i + j, f.idx1 - 1]", TNumber(3)) // 1, 0
+                );
+           });
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:660]: nit: indents are a little off, and inconsistent

**Review by radical — APPROVED** [review]

**Review by lewing — APPROVED** [review]
