### PR TITLE
JIT: emit vzeroupper before calls to the bulk write barrier helper

### LINKED ISSUE #106679: 3x perf regression on 13th Gen Intel Core (i7-13800H) maybe in readonly struct passed by ref
### Description

One of the benchmarks in our [`Corvus.JsonSchema`](https://github.com/corvus-dotnet/Corvus.JsonSchema) library has wildly different performance characteristics on .NET 9.0 on certain hardware:

| CPU | .NET 8.0 | .NET 9.0 (9.0.24.40507) |
|--|--|--|
| Intel Core i9-9900K CPU 3.60GHz (Coffee Lake) | 22ms | 19ms |
| Intel Core i7-13800H | 15ms | **42ms** |

On the (rather old) Coffee Lake CPU, we see what you'd hope: .NET 9.0 is significantly faster than .NET 8.0.

On the much newer CPU (in a Surface Laptop Studio 2), in .NET 8.0 the benchmark runs a lot faster than on the old CPU, as is typical with a CPU that much newer. But running the same code on .NET 9.0 on that newer CPU is almost 3 times slower than with .NET 8.0 on the same CPU. (It's significantly slower even than .NET 8.0 on the much older CPU.)

To reproduce this,  clone the repo from [commit 2621745](https://github.com/corvus-dotnet/Corvus.JsonSchema/tree/26217453404eb41a44ed712eb25d9f639242ae4f), run the `Corvus.Json.Benchmark` project, and select the `ValidateLargeDocument` benchmark.

The figures in the table above are for the `ValidateLargeArrayCorvusV3` benchmark, but we see similar regressions (again, only on the newer CPU) for the `ValidateLargeArrayCorvusV4` and `ValidateLargeArrayCorvusValidator` benchmarks.

We haven't yet succeeded in isolating whatever it is about this benchmark that produces these effects. So far our attempts to profile the code outside of BenchmarkDotNet haven't reproduced the issue. The code in question makes heavy use of `System.Text.Json`, so that's where we suspect the issue lies, but we can't prove that.

### Configuration

> Which version of .NET is the code running on?

NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX2 and .NET 9.0.0 (9.0.24.40507), X64 RyuJIT AVX2

> What OS version, and what distro if applicable?

On the Coffee Lake machine (which doesn't have this problem) we're running Windows 11 (10.0.22631.4037/23H2/2023Update/SunValley3).

The newer machine (which exhibits the problem) is running Windows 11 (10.0.22621.4037/22H2/2022Update/SunValley2).

> What is the architecture (x64, x86, ARM, ARM64)?

x64, Intel Core.

> If relevant, what are the specs of the machine?

On the machine that does not reproduce the problem, the CPU is as already described. The machine has 64GB of memory. (I can provide more details if required.)

The machine on which we see the problem is a Surface Laptop Studio 2 with 64GB of RAM.

### Regression

We're seeing the regression from .NET 8.0.7 to .NET 9.0.0-preview.7.24405.7 (BenchmarkDotNet reports this as 9.0.24.40506.)

We first observed this with .NET 9.0.0-preview.6.

### Data

The `Throughput` benchmark results on the older (Coffee Lake) CPU (on which we **don't** see the regression) are:

```
| Method                            | Runtime  | RunStrategy | UnrollFactor | Mean      | Error     | StdDev    | Median    | Ratio | RatioSD | Gen0       | Gen1       | Gen2      | Allocated   | Alloc Ratio  |
|---------------------------------- |--------- |------------ |------------- |----------:|----------:|----------:|----------:|------:|--------:|-----------:|-----------:|----------:|------------:|-------------:|
| ValidateLargeArrayCorvusV3        | .NET 8.0 | Throughput  | 16           |  21.94 ms |  0.324 ms |  0.303 ms |  21.97 ms |  1.00 |    0.00 |          - |          - |         - |        23 B |         1.00 |
| ValidateLargeArrayCorvusV4        | .NET 8.0 | Throughput  | 16           |  21.39 ms |  0.246 ms |  0.218 ms |  21.36 ms |  0.97 |    0.01 |          - |          - |         - |        23 B |         1.00 |
| ValidateLargeArrayCorvusValidator | .NET 8.0 | Throughput  | 16           |  37.38 ms |  0.710 ms |  0.697 ms |  37.20 ms |  1.70 |    0.03 |          - |          - |         - |       961 B |        41.78 |
| ValidateLargeArrayJsonEverything  | .NET 8.0 | Throughput  | 16           | 674.64 ms | 12.023 ms | 11.246 ms | 677.29 ms | 30.76 |    0.70 | 26000.0000 | 21000.0000 | 3000.0000 | 193961040 B | 8,433,088.70 |
| ValidateLargeArrayCorvusV3        | .NET 9.0 | Throughput  | 16           |  18.58 ms |  0.271 ms |  0.241 ms |  18.50 ms |  0.85 |    0.01 |          - |          - |         - |        34 B |         1.48 |
| ValidateLargeArrayCorvusV4        | .NET 9.0 | Throughput  | 16           |  17.97 ms |  0.232 ms |  0.193 ms |  17.96 ms |  0.82 |    0.01 |          - |          - |         - |        34 B |         1.48 |
| ValidateLargeArrayCorvusValidator | .NET 9.0 | Throughput  | 16           |  38.59 ms |  2.037 ms |  5.975 ms |  37.90 ms |  1.63 |    0.24 |          - |          - |         - |      4936 B |       214.61 |
| ValidateLargeArrayJsonEverything  | .NET 9.0 | Throughput  | 16           | 677.66 ms | 10.140 ms |  8.468 ms | 677.89 ms | 30.89 |    0.56 | 25000.0000 | 20000.0000 | 2000.0000 | 192861320 B | 8,385,274.78 |
```

As you can see, on that CPU .NET 9.0 does better than .NET 8.0.

Here are the same results for the 13th gen CPU in the Surface Laptop Studio 2:

```
| Method                            | Runtime  | RunStrategy | UnrollFactor | Mean      | Error    | StdDev    | Ratio | RatioSD | Gen0       | Gen1       | Gen2      | Allocated   | Alloc Ratio   |
|---------------------------------- |--------- |------------ |------------- |----------:|---------:|----------:|------:|--------:|-----------:|-----------:|----------:|------------:|--------------:|
| ValidateLargeArrayCorvusV3        | .NET 8.0 | Throughput  | 16           |  14.63 ms | 0.263 ms |  0.205 ms |  1.00 |    0.00 |          - |          - |         - |        12 B |          1.00 |
| ValidateLargeArrayCorvusV4        | .NET 8.0 | Throughput  | 16           |  13.39 ms | 0.075 ms |  0.070 ms |  0.92 |    0.01 |          - |          - |         - |        12 B |          1.00 |
| ValidateLargeArrayCorvusValidator | .NET 8.0 | Throughput  | 16           |  22.67 ms | 0.060 ms |  0.054 ms |  1.55 |    0.02 |          - |          - |         - |       902 B |         75.17 |
| ValidateLargeArrayJsonEverything  | .NET 8.0 | Throughput  | 16           | 390.16 ms | 7.662 ms | 15.651 ms | 27.00 |    1.44 | 17000.0000 | 14000.0000 | 2000.0000 | 193948488 B | 16,162,374.00 |
| ValidateLargeArrayCorvusV3        | .NET 9.0 | Throughput  | 16           |  42.31 ms | 0.151 ms |  0.141 ms |  2.90 |    0.04 |          - |          - |         - |        61 B |          5.08 |
| ValidateLargeArrayCorvusV4        | .NET 9.0 | Throughput  | 16           |  38.11 ms | 0.158 ms |  0.148 ms |  2.61 |    0.04 |          - |          - |         - |        56 B |          4.67 |
| ValidateLargeArrayCorvusValidator | .NET 9.0 | Throughput  | 16           |  59.78 ms | 0.105 ms |  0.098 ms |  4.09 |    0.06 |          - |          - |         - |      1306 B |        108.83 |
| ValidateLargeArrayJsonEverything  | .NET 9.0 | Throughput  | 16           | 397.82 ms | 7.837 ms | 13.931 ms | 27.55 |    0.93 | 17000.0000 | 14000.0000 | 2000.0000 | 192858296 B | 16,071,524.67 |
```

As you can see, the .NET 9.0 numbers here (same preview build of .NET 9.0 - preview.7) for the first 3 benchmarks are significantly slower than for .NET 8.0. (And they are significantly slower than the same benchmarks on the much older CPU for either .NET 8.0 or 9.0 preview 7.)

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The helper uses SSE2, so we need to take care to avoid AVX-SSE transition penalties.

Fixes #106679.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@tannergooding @EgorBo PTAL
cc @dotnet/jit-contrib 

Will backport to .Net 9.

Will also look for other helpers that need similar treatement.

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -2050,6 +2050,13 @@ bool GenTreeCall::NeedsVzeroupper(Compiler* comp)
         }
     }
 
+    // Other special cases
+    //
+    if (!needsVzeroupper && IsHelperCall(comp, CORINFO_HELP_BULK_WRITEBARRIER))
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:2055]: Can't this be moved under `CT_HELPER` since `IsHelperCall(...)` requires `gtCallType == CT_HELPER`?

-- Not necessary, just makes it slightly more "pay for play"?

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/gentree.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/gentree.cpp:2055]: That switch is guarded with `IsPInvoke` but this helper call is not a pinvoke -- it has no managed counterpart.

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:2055]: Ah right, that makes sense.

I think we may need to ensure this is guarded under `if (comp->canUseVexEncoding())` then; otherwise `lsraxarch` will mark us as having a call needing `vzeroupper` (see `SetContainsCallNeedingVzeroupper`) and that will cause a `vzeroupper` to be emitted when preserving callee saved float registers.

Comment (AndyAyersMS) [reply src/coreclr/jit/gentree.cpp:2055]: `this` meaning this new bit, or the whole method...? 

If we can't use vex then it seems like we can just immediately return false?

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:2055]: > If we can't use vex then it seems like we can just immediately return false?

Right.

> this meaning this new bit, or the whole method...?

The new bit in particular, but we already have the existing `if (IsPInvoke() && comp->canUseVexEncoding())`, so we can probably just do something like this:
```cpp
if (!comp->canUseVexEncoding())
{
    return false;
}

if (IsPInvoke())
{
   // ...
}

if (!needsVzeroupper && IsHelperCall(comp, CORINFO_HELP_BULK_WRITEBARRIER))
{
   // ...
}
```

Comment (AndyAyersMS) [reply src/coreclr/jit/gentree.cpp:2055]: CI [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=787081&view=ms.vss-build-web.run-extensions-tab) show a lot more additions than I'd expect, will need to generate them locally and review.

Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:2055]: These all look expected at a glance. `vzeroupper` is 3 bytes for any method that uses such a `CORINFO_HELP_BULK_WRITEBARRIER`

In the case that the method contains a call needing `vzeroupper` (i.e. contains a `CORINFO_HELP_BULK_WRITEBARRIER` call) then we have two scenarios:
A) The method uses 256-bit or greater AVX instructions
B) The method uses 128-bit AVX or no AVX instructions

For scenario A, we need to emit a `vzeroupper` prior to each `CORINFO_HELP_BULK_WRITEBARRIER` call
For scenario B, we optimize to only emitting a single `vzeroupper` call in the function prologue

Looking at the diffs, the vast majority of cases are those with just 1 new `vzeroupper`. There's a few larger functions that have multiple bulk write barriers and use floating-point/simd, and so have many new `vzeroupper`. -- 17 write barriers is the most for a non-test scenario, 67 is then an outlier for a `ComInterfaceGenerator.Unit.Tests.CompileFails` iterator method

For .NET 9, this is probably the "right" fix and while it increases size, `vzeroupper` is supposed to be "zero-cost" and handled by the register renamer. So it shouldn't negatively impact things.

In .NET 10, we could look at adding an explicit AVX path to `CORINFO_HELP_BULK_WRITEBARRIER` in order to avoid the need to emit `vzeroupper`, which may be desirable.
