### PR TITLE
[wasm] Use lightweight marshal for enums

### LINKED ISSUE #115780: Blazor WebAssembly - `ZipArchiveEntry.Open` causes unexpected termination at runtime in published app on .NET 10 Preview 3 and 4
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When using the `ZipArchiveEntry.Open()` method to read the stream of a zipped file in a Blazor WebAssembly application, the application will be forced to terminate at runtime. This issue only occurs when publishing the application in Release mode with runtime relinking enabled, and only with .NET 10 Preview 3 or 4. The issue does not occur with .NET 9 or earlier versions, nor with .NET 10 Preview 1 or 2. Additionally, the issue does not reproduce during development-time execution (i.e., `dotnet run` or `dotnet watch`).

The error appears in the browser's developer console as follows:

```
[MONO] * Assertion at /__w/1/s/src/runtime/src/mono/mono/metadata/method-builder-ilgen.c:631, condition `<disabled>' not met
```

This appears to be a regression introduced in .NET 10 Preview 3.

### Expected Behavior

`ZipArchiveEntry.Open()` should correctly return a readable stream for the contents of a zip entry, even in Release mode with runtime relinking enabled, without crashing the application.

### Steps To Reproduce

1. Install the .NET SDK version 10 Preview 4 and the `wasm-tools` workload with the `dotnet workload install wasm-tools` command. _[2025-08-01 Updated]_ 
2. Download the sample project: [BlazorWasmApp1.zip](https://github.com/user-attachments/files/20347418/BlazorWasmApp1.zip)
3. Extract the contents to a working directory.
4. Publish the project using the following command: `dotnet publish -f net10.0`
5. Install the dotnet-serve tool (if not already installed): `dotnet tool install -g dotnet-serve`
6. Serve the published application using: `dotnet serve -p 5000 -d .\bin\Release\net10.0\publish\wwwroot\`
7. Open the browser and navigate to: `http://localhost:5000/`
8. Click the "Extract the sample.zip file" button on the page.
9. Observe that a yellow bar appears saying "An unhandled error has occurred".
10. Open the browser's developer console, and you will see the following error:
```
[MONO] * Assertion at /__w/1/s/src/runtime/src/mono/mono/metadata/method-builder-ilgen.c:631, condition `<disabled>' not met
```

Image

### Exceptions (if any)

```
[MONO] * Assertion at /__w/1/s/src/runtime/src/mono/mono/metadata/method-builder-ilgen.c:631, condition `<disabled>' not met
```

### .NET Version

10.0.100-preview.4.25258.110 and `wasm-tools` workload. _[2025-08-01 Updated]_

### Anything else?

This issue does not occur under the following conditions:

- When publishing with .NET 9:

```
dotnet publish -f net9.0
dotnet serve -p 5000 -d .\bin\Release\net9.0\publish\wwwroot\
```

- When publishing with .NET 10 Preview 4, but with runtime relinking disabled via the `UsingBrowserRuntimeWorkload` MSBuild property:

```
dotnet publish -f net10.0 -p:UsingBrowserRuntimeWorkload=false
dotnet serve -p 5000 -d .\bin\Release\net10.0\publish\wwwroot\
```

Image

The `UsingBrowserRuntimeWorkload=false` workaround is not viable for real-world applications because runtime relinking is essential for reducing the download size of Blazor WebAssembly apps and for enabling interop with WebAssembly-native modules written in C/C++ or Rust.

This issue seems to be a regression introduced in .NET 10 Preview 3 and needs to be addressed to maintain the functionality and performance of Blazor WebAssembly applications that depend on `System.IO.Compression`.

### PR DESCRIPTION
**Pull request by maraf**
Based on `MinimalMarshalingTypeCompatibilityProvider.cs` we mark enums as marshallable by lightweight marshaller on build.
We were missing enums when checking for supported types in `marshal-ilgen-stub.c` on runtime.

Fixes https://github.com/dotnet/runtime/issues/115780
Contributes to https://github.com/dotnet/runtime/issues/94187

### CODE REVIEW

File: src/mono/mono/component/marshal-ilgen-stub.c [hunk 1]
```diff
@@ -43,11 +43,16 @@ stub_emit_marshal_ilgen (EmitMarshalContext* m, int argnum, MonoType* t,
 	case MONO_TYPE_U8:
 	case MONO_TYPE_FNPTR:
 		return lightweight_cb->emit_marshal_scalar (m, argnum, t, spec, conv_arg, conv_arg_type, action);
-	default:
+	default: {
+		MonoClass *klass = m_type_data_get_klass_unchecked (t); // aka MONO_TYPE_ 17
+		if (m_class_is_enumtype (klass) == 1)
```
Comment (lewing) [inline src/mono/mono/component/marshal-ilgen-stub.c]:
```suggestion
		if (m_class_is_enumtype (m_type_data_get_klass_unchecked (t)))
```

**Review by pavelsavara — APPROVED** [review]

**Review by lewing — APPROVED** [review]

File: src/mono/mono/component/marshal-ilgen-stub.c [hunk 2]
```diff
@@ -43,11 +43,15 @@ stub_emit_marshal_ilgen (EmitMarshalContext* m, int argnum, MonoType* t,
 	case MONO_TYPE_U8:
 	case MONO_TYPE_FNPTR:
 		return lightweight_cb->emit_marshal_scalar (m, argnum, t, spec, conv_arg, conv_arg_type, action);
-	default:
+	default: {
+		if (m_class_is_enumtype (m_type_data_get_klass_unchecked (t)))
```
Comment (lewing) [inline src/mono/mono/component/marshal-ilgen-stub.c:47]: I think you could make this stricter by only checking when the type is MONO_TYPE_VALUETYPE but I think this works too

Comment (maraf) [reply src/mono/mono/component/marshal-ilgen-stub.c:47]: I see, in other places there is a check for MONO_TYPE_VALUETYPE + the check "is enum"
