### PR TITLE
Work around for UriFormatException caused by \\?\ prefix in the path

### LINKED ISSUE #70318: Reading application settings in NET WinForms OOP designer fails with exception 'Invalid URI: The hostname could not be parsed"
### Environment

Version 17.2.2

### .NET version

net6.0-windows

### Did this work in a previous version of Visual Studio and/or previous .NET release?

No, this is new in VS2022 and the NET WinForms OOP designer.

### Issue description

This is an issue in the new NET WinForms designer when using the microsoft.winforms.designer.sdk to add design-time support to a custom NET6 WinForms control. Reading application settings at design-time fails with exception “Invalid URI: this hostname could not be parsed”.

I also reported this as feedback from VS2022:
https://developercommunity.visualstudio.com/t/Reading-application-settings-fails-in-th/10055004

### Steps to reproduce

My github sample to reproduce:
https://github.com/tracktownsoftware/MicrosoftWinFormsDesignerSDK_AppSettingsBug

The above repository includes a Nuget package you can use to test and reproduce. The nuget package contains a custom NET6 WinForms "MyButton" control with WinForms Designer Extensibility SDK design-time support.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by buyaa-n**
When the path populated by `AppDomain.CurrentDomain.BaseDirectory` starts with `\\?\` (long path prefix) Uri constructor throws UriFormatException: `Invalid URI: The hostname could not be parsed` which causing WinForms designer failure:
image

Moving the Uri creation code to where it is used and using `Uri.TryCreate` instead of the ctor

Please see the details from the issue: https://github.com/dotnet/runtime/issues/70318

Fixes https://github.com/dotnet/runtime/issues/70318

### CODE REVIEW

File: src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs [hunk 1]
```diff
@@ -265,9 +264,12 @@ private static string GetTypeAndHashSuffix(string exePath, bool isSingleFile)
                 {
                     try
                     {
-                        // Certain platforms may not have support for crypto
-                        hash = IdentityHelper.GetNormalizedUriHash(codeBase);
-                        typeName = UrlDesc;
+                        if (Uri.TryCreate(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, assembly.ManifestModule.Name), UriKind.RelativeOrAbsolute, out Uri codeBase))
```
Comment (jkotas) [inline src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:267]: Do we have any test coverage for this? For example, you delete this code completely - are any tests going to fail?

Comment (jkotas) [inline src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:267]: The constructor that was used here before used `UriKind.Absolute` kind: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.Uri/src/System/Uri.cs#L365-L371

Is there a reason to switch to `UriKind.RelativeOrAbsolute` here?

Comment (buyaa-n) [reply src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:267]: Doesn't seem there is a test, no test failure if delete it completely

Comment (buyaa-n) [reply src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:267]: Good catch, was just trying to cover everything possible, did not checked the Uri implementation

Comment (buyaa-n) [reply src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs]: Are you suggesting to remove this part or add a test (not sure if it is testable though)?

File: src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs [hunk 2]
```diff
@@ -265,9 +264,12 @@ private static string GetTypeAndHashSuffix(string exePath, bool isSingleFile)
...
-                        hash = IdentityHelper.GetNormalizedUriHash(codeBase);
-                        typeName = UrlDesc;
+                        if (Uri.TryCreate(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, assembly.ManifestModule.Name), UriKind.Absolute, out Uri codeBase))
+                        {
+                            // Certain platforms may not have support for crypto
+                            hash = IdentityHelper.GetNormalizedUriHash(codeBase);
+                            typeName = UrlDesc;
+                        }
                     }
                     catch (PlatformNotSupportedException) { }
```
Comment (stephentoub) [inline src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:274]: Should the try/catch be inside the if (Uri...) block rather than outside of it?  It seems like the intention is it's targeted at the GetNormalizedUriHash call.

Comment (buyaa-n) [reply src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:274]: Right

**Review by jkotas — APPROVED** [review]
