### PR TITLE
[wasm] Wasm.Build.Tests - fixes for tests failing on CI

### LINKED ISSUE #70675: [wasm] nodejs on windows doesn't flush `stdout/stderr` streams on exit - with the `consolewasm` template
This happens in Debug, And Release, though now always in both. It is being hit on PRs, and rolling builds. [Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a3b0cc5cb0d4469982/Workloads-.WasmTemplateTests/1/console.acd328b1.log?helixlogtype=result):

```
 Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Debug", aot: True) [FAIL]
      Assert.Contains() Failure
      Not found: args[0] = x
      In value:  [Debug_0ptsa3o0.ug5] WasmAppHost --runtime-config C:\helix\work\workitem\e\Debug_0ptsa3o0.ug5\bin\Debug\net7.0\browser-wasm\AppBundle\/Debug_0ptsa3o0.ug5.runtimeconfig.json --setenv=MONO_LOG_MASK=aot --setenv=MONO_LOG_LEVEL=debug x y z
                 [Debug_0ptsa3o0.ug5] [21:10:13] info: host[0] Running: C:\helix\work\correlation\build\emsdk-node/14.18.2_64bit/bin\node.exe main.cjs --setenv=MONO_LOG_MASK=aot --setenv=MONO_LOG_LEVEL=debug x y z
                 [Debug_0ptsa3o0.ug5] [21:10:13] dbug: host[0] Using working directory: C:\helix\work\workitem\e\Debug_0ptsa3o0.ug5\bin\Debug\net7.0\browser-wasm\AppBundle
                 [Debug_0ptsa3o0.ug5] [21:10:13] info: host[0] Incoming arguments: --setenv=MONO_LOG_MASK=aot --setenv=MONO_LOG_LEVEL=debug x y z
                 [Debug_0ptsa3o0.ug5] [21:10:13] info: host[0] Application arguments: x y z
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] Found statically linked AOT module 'System.Private.CoreLib'.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Private.CoreLib wants to load image 0: System.Private.CoreLib
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: image 'System.Private.CoreLib' found.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper managed-to-native) object:__icall_wrapper_mono_threads_state_poll () [0x2a62 - 0x2a63 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper managed-to-native) object:__icall_wrapper_mini_llvmonly_init_vtable_slot (intptr,int) [0x6d - 0x6e 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper managed-to-native) object:__icall_wrapper_mono_helper_ldstr_mscorlib (int) [0x246 - 0x247 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper managed-to-native) object:__icall_wrapper_mono_fill_method_rgctx (intptr,int) [0x2a11 - 0x2a12 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper managed-to-native) object:__icall_wrapper_mono_fill_class_rgctx (intptr,int) [0x1d6 - 0x1d7 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.OutOfMemoryException:.ctor (string) [0xb68 - 0xb69 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.NullReferenceException:.ctor (string) [0xa8b - 0xa8c 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.StackOverflowException:.ctor (string) [0xe4e - 0xe4f 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.AppContext:Setup (char**,char**,int) [0x63b - 0x63c 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper other) object:gsharedvt_out_sig (object&,object&,int&,intptr) [0x2b34 - 0x2b35 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Collections.Generic.EqualityComparer`1:CreateComparer () [0x20d8 - 0x20d9 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Collections.HashHelpers:.cctor () [0x2066 - 0x2067 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper other) object:gsharedvt_out_sig (intptr) [0x2b36 - 0x2b37 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Collections.Generic.NonRandomizedStringEqualityComparer:.cctor () [0x2182 - 0x2183 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.OrdinalIgnoreCaseComparer:.cctor () [0xe65 - 0xe66 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.OrdinalCaseSensitiveComparer:.cctor () [0xe5f - 0xe60 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Type:.cctor () [0x607 - 0x608 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Type/<>c:.cctor () [0x608 - 0x609 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Reflection.Missing:.cctor () [0x1bca - 0x1bcb 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Array/EmptyArray`1:.cctor () [0x326 - 0x327 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Type:FilterAttributeImpl (System.Reflection.MemberInfo,object) [0x605 - 0x606 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper delegate-invoke) <Module>:invoke_bool_MemberInfo_object (System.Reflection.MemberInfo,object) [0x2a8b - 0x2a8c 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Type/<>c:<.cctor>b__287_0 (System.Reflection.MemberInfo,object) [0x60a - 0x60b 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Type/<>c:<.cctor>b__287_1 (System.Reflection.MemberInfo,object) [0x60b - 0x60c 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.RuntimeType:IsAssignableFrom (System.Type) [0x4d7 - 0x4d8 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.RuntimeType:.cctor () [0x4db - 0x4dc 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.RuntimeType:get_UnderlyingSystemType () [0x4be - 0x4bf 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper stelemref) object:virt_stelemref_class_small_idepth (intptr,object) [0x29d5 - 0x29d6 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Reflection.ConstructorInfo:.cctor () [0x1b7f - 0x1b80 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper stelemref) object:virt_stelemref_sealed_class (intptr,object) [0x29d3 - 0x29d4 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Reflection.MethodBase:GetParametersNoCopy () [0x1a40 - 0x1a41 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Reflection.RuntimeConstructorInfo:GetParametersInternal () [0x1afc - 0x1afd 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Array:Resize<T> (T[]&,int) [0x314 - 0x315 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Reflection.RuntimeConstructorInfo:get_Attributes () [0x1b00 - 0x1b01 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Collections.Generic.GenericEqualityComparer`1:.ctor () [0x212d - 0x212e 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Collections.Generic.Dictionary`2:Add (TKey,TValue) [0x20f9 - 0x20fa 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.ThrowHelper:ThrowAddingDuplicateWithKeyArgumentException<T> (T) [0xe81 - 0xe82 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Collections.Generic.NonRandomizedStringEqualityComparer/OrdinalComparer:GetHashCode (string) [0x2185 - 0x2186 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] Found statically linked AOT module 'System.Private.Runtime.InteropServices.JavaScript'.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Private.Runtime.InteropServices.JavaScript wants to load image 0: System.Private.Runtime.InteropServices.JavaScript
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Private.Runtime.InteropServices.JavaScript wants to load image 1: System.Private.CoreLib
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Private.Runtime.InteropServices.JavaScript wants to load image 2: System.Private.Uri
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] Found statically linked AOT module 'System.Private.Uri'.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Private.Uri wants to load image 0: System.Private.Uri
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Private.Uri wants to load image 1: System.Private.CoreLib
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: image 'System.Private.Uri' found.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: image 'System.Private.Runtime.InteropServices.JavaScript' found.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] Could not find symbols file dotnet.js.symbols. Ignoring.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] Initializing.....
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] Found statically linked AOT module 'Debug_0ptsa3o0.ug5'.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module Debug_0ptsa3o0.ug5 wants to load image 1: Debug_0ptsa3o0.ug5
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module Debug_0ptsa3o0.ug5 wants to load image 0: System.Private.CoreLib
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module Debug_0ptsa3o0.ug5 wants to load image 2: System.Console
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] Found statically linked AOT module 'System.Console'.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Console wants to load image 0: System.Console
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Console wants to load image 1: System.Private.CoreLib
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: image 'System.Console' found.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: image 'Debug_0ptsa3o0.ug5' found.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] Found statically linked AOT module 'System.Runtime'.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Runtime wants to load image 1: System.Runtime
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: module System.Runtime wants to load image 0: System.Private.CoreLib
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: image 'System.Runtime' found.
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method Program:<Main>$ (string[]) [0x5 - 0x6 0x1348]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method (wrapper other) object:gsharedvt_out_sig (object&,intptr) [0x2b0a - 0x2b0b 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Console:WriteLine (string) [0x85 - 0x86 0x41e0]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Runtime.CompilerServices.DefaultInterpolatedStringHandler:ToStringAndClear () [0x1e0 - 0x1e1 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Runtime.CompilerServices.DefaultInterpolatedStringHandler:AppendFormatted (string) [0x1df - 0x1e0 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Runtime.CompilerServices.DefaultInterpolatedStringHandler:AppendLiteral (string) [0x1de - 0x1df 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Runtime.CompilerServices.DefaultInterpolatedStringHandler:AppendFormatted<T_INT> (T_INT) [0x21c4 - 0x21c5 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Runtime.CompilerServices.DefaultInterpolatedStringHandler:.ctor (int,int) [0x1dd - 0x1de 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Buffers.ArrayPool`1<T_CHAR>:.cctor () [0x2391 - 0x2392 0x54188]
                 [Debug_0ptsa3o0.ug5] [21:10:22] info: host[0] [MONO] AOT: FOUND method System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1<T_CHAR>:.ctor () [0x2398 - 0x2399 0x54188]
```

### PR DESCRIPTION
**Pull request by radical**
- Fix an issue with stdout/stderr streams not being flushed correctly on nodejs.
- Fix an issue with completely reading stdout/stderr for `xharness`
- And remove dependence on xharness' std* streams, and instead use the emitted `wasm-console.log`, for non-browser cases
  - note: this is still correctly testing the *app* output, as xharness reads that, and writes to `wasm-console.log`
- And copy sdk for workload testing only when running on CI.

Fixes https://github.com/dotnet/runtime/issues/70675

### CODE REVIEW

**Comment by pavelsavara** [comment]
We will need to update this PR after https://github.com/dotnet/runtime/pull/70746

**Comment by radical** [comment]
this has a timeout right now for flushing the streams, but maybe that should be removed?

File: src/mono/wasm/templates/templates/console/app-support.mjs [hunk 1]
```diff
@@ -47,11 +47,26 @@ function set_exit_code(exit_code, reason) {
     }
 
     if (App && App.INTERNAL) {
-        App.INTERNAL.mono_wasm_exit(exit_code);
+        let _flush = function(_stream) {
+             return new Promise((resolve, reject) => {
+                 setTimeout(reject, 30000);
```
Comment (kg) [inline src/mono/wasm/templates/templates/console/app-support.mjs:52]: maybe pass a 'timed out' message to the rejection handler here

File: src/mono/wasm/templates/templates/console/app-support.mjs [hunk 2]
```diff
@@ -47,11 +47,26 @@ function set_exit_code(exit_code, reason) {
...
+                 _stream.write('', function() { resolve () });
+                 _stream.on('error', (error) => reject(error));
```
Comment (kg) [inline src/mono/wasm/templates/templates/console/app-support.mjs:54]: shouldn't you do this before the write instead of after, since .write could cause an error?

File: src/mono/wasm/test-main.js [hunk 3]
```diff
@@ -105,26 +105,23 @@ function set_exit_code(exit_code, reason) {
...
-                    if (!_stream.write('')) {
-                        _stream.on('drain', () => resolve());
-                        setTimeout(reject, 3000);
-                    } else {
-                        resolve();
-                    }
-                });
+            let _flush = function(_stream) {
+                 return new Promise((resolve, reject) => {
+                     setTimeout(reject, 30000);
```
Comment (kg) [inline src/mono/wasm/test-main.js:110]: same feedback as for app-support.mjs applies here

File: src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs [hunk 4]
```diff
@@ -230,6 +234,12 @@ public BuildTestBase(ITestOutputHelper output, SharedBuildPerTestClassFixture bu
                                         timeoutMs: s_defaultPerTestTimeoutMs);
 
             File.WriteAllText(Path.Combine(testLogPath, $"xharness.log"), output);
+            if (useWasmConsoleOutput)
+            {
+                string wasmConsolePath = Path.Combine(testLogPath, "wasm-console.log");
+                if (File.Exists(wasmConsolePath))
+                    output = File.ReadAllText(wasmConsolePath);
```
Comment (kg) [inline src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs:241]: if it doesn't exist, maybe emit a warning to specify that we looked for the log and it wasn't there?

Comment (kg) [reply src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs:241]: this read could also hit a sharing violation if the test process has it locked too, i think? i'm not sure. might be worth having a try-catch around it

**Review by kg — CHANGES_REQUESTED** [review]
This looks fine to me other than the bits of feedback I provided, changes not mandatory

File: src/mono/wasm/templates/templates/console/app-support.mjs (hunk 2 above)
Comment (radical) [reply src/mono/wasm/templates/templates/console/app-support.mjs:53]: Should we remove the timeout completely for console template, IOW, user apps?

the other usage of the timeout is in tests, which should be useful.

Comment (kg) [reply src/mono/wasm/templates/templates/console/app-support.mjs:53]: I think removing it for apps is probably reasonable

**Review by kg — APPROVED** [review]

**Comment by radical** [comment]
Chrome debugger test failure is intermittent, and unrelated.
