### PR TITLE
Fix critical finalization test

### LINKED ISSUE #75782: critical_finalization tests fails with GCStress=0x3
This test fails in outerloop pipelines with `DOTNET_GCStress=0x3`, reproduces even on release/7.0 so not related to any of recent changes.

E.g. https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75661-merge-30d9d20cfaba4818b9/baseservices.critical_finalization/1/console.2f6963c2.log?helixlogtype=result

### PR DESCRIPTION
**Pull request by AntonLapounov**
The test assumed that all allocated `P` and `Q` objects are collected during the same GC pass (`Q.first_p_count == P.count`), which may not be the case under GC stress. The fix is to unroot all allocated objects at the same time. I also fixed indentation, improved naming, and moved the test to the existing `finalization` directory.

Fixes #75782.

### CODE REVIEW

**Review by EgorBo — APPROVED** [review]

File: src/tests/baseservices/finalization/CriticalFinalizer.cs [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+static class CriticalFinalizerTest
+{
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    static void AllocateObjects(int count)
+    {
+        List<object> list = new();
+
+        for (int i = 0; i < count; i++)
+        {
+            list.Add(new Normal());
```
Comment (VSadov) [inline src/tests/baseservices/finalization/CriticalFinalizer.cs:40]: For completeness of the test, perhaps allocate on multiple threads?
It may be easier to guarantee the order if all objects end up in the same heap.

Comment (VSadov) [reply src/tests/baseservices/finalization/CriticalFinalizer.cs:40]: This could be as simple as switching to Parallel.For

**Review by VSadov — APPROVED** [review]
Thanks!!

**Comment by EgorBo** [comment]
@AntonLapounov looks like it's still failing? e.g. in https://github.com/dotnet/runtime/pull/75573 and other PRs ^

**Comment by fanyang-mono** [comment]
@radical This PR changed runtime tests; but the mono runtime tests CI lanes weren't triggered in this PR. Could you please check?

**Comment by AndyAyersMS** [comment]
Still failing for me too... #75992 (x86 windows).

**Comment by AntonLapounov** [comment]
I opened #76041 for the new intermittent failure.
