### PR TITLE
[mono][metadata] Replace use of mem manager lock with loader lock

### LINKED ISSUE #90834: [8.0] [mono] Test process gets killed
### Error Blob

```json
{
  "ErrorMessage": "Tests' END OF WORK ITEM LOG: Command timed out, and was killed]",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

This failure happens often in System.Runtime.Tests specifically.

- PR: https://github.com/dotnet/runtime/pull/90809
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=378797&view=logs&j=1f44e919-17d8-5098-631c-31ef11f9e57b&t=d617d884-da52-5b82-bd49-f7613b408af4&l=87
- Queue: `Libraries Test Run release mono linux x64 Debug`
- Log: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-90809-merge-956e379e01714658b2/System.Runtime.Tests/1/console.73e1394a.log?helixlogtype=result
- Output:

```
Console log: 'System.Runtime.Tests' from job 956e379e-0171-4658-b2cd-b234086ec9af workitem 50980a74-2595-4c8f-b4a1-bbcc0991bb7b (ubuntu.1804.amd64.open.svc) executed on machine a005SZ1 running Linux-5.4.0-1109-azure-x86_64-with-Ubuntu-18.04-bionic
+ ./RunTests.sh --runtime-path /datadisks/disk1/work/9F780922/p
----- start Fri Aug 18 17:28:49 UTC 2023 =============== To repro directly: =====================================================
pushd .
/datadisks/disk1/work/9F780922/p/dotnet exec --runtimeconfig System.Runtime.Tests.runtimeconfig.json --depsfile System.Runtime.Tests.deps.json xunit.console.dll System.Runtime.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=AdditionalTimezoneChecks -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/datadisks/disk1/work/9F780922/w/A2490973/e /datadisks/disk1/work/9F780922/w/A2490973/e
  Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Tests (found 9160 of 9278 test cases)
  Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 2)
    System.Tests.ArrayEnumeratorTests_int.ICollection_Generic_Remove_ReferenceRemovedFromCollection [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
['System.Runtime.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 8/29/2023 9:18:10 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[390358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390358)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390358&view=ms.vss-test-web.build-test-results-tab&runId=8374390&resultId=195975)|dotnet/runtime#91314|
|[390315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390315)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390315&view=ms.vss-test-web.build-test-results-tab&runId=8372588&resultId=195952)|dotnet/runtime#91239|
|[390327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390327)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390327&view=ms.vss-test-web.build-test-results-tab&runId=8373528&resultId=195589)||
|[390312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390312)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390312&view=ms.vss-test-web.build-test-results-tab&runId=8373130&resultId=195595)|dotnet/runtime#91240|
|[390304](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390304)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390304&view=ms.vss-test-web.build-test-results-tab&runId=8373092&resultId=195691)|dotnet/runtime#91311|
|[390232](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390232)|dotnet/runtime|[System.Globalization.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390232&view=ms.vss-test-web.build-test-results-tab&runId=8370694&resultId=200024)|dotnet/runtime#90970|
|[390131](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390131)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390131&view=ms.vss-test-web.build-test-results-tab&runId=8366246&resultId=195939)|dotnet/runtime#91303|
|[389716](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389716)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389716&view=ms.vss-test-web.build-test-results-tab&runId=8355760&resultId=195691)|dotnet/runtime#91293|
|[389636](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389636)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389636&view=ms.vss-test-web.build-test-results-tab&runId=8353138&resultId=196068)|dotnet/runtime#91290|
|[389641](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389641)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389641&view=ms.vss-test-web.build-test-results-tab&runId=8353936&resultId=195595)|dotnet/runtime#91291|
|[389595](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389595)|dotnet/runtime|[System.Net.NetworkInformation.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389595&view=ms.vss-test-web.build-test-results-tab&runId=8352040&resultId=200278)||
|[389529](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389529)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389529&view=ms.vss-test-web.build-test-results-tab&runId=8350968&resultId=196806)|dotnet/runtime#91283|
|[389491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389491)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389491&view=ms.vss-test-web.build-test-results-tab&runId=8350354&resultId=195565)||
|[389478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389478)|dotnet/runtime|[Microsoft.Extensions.Configuration.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389478&view=ms.vss-test-web.build-test-results-tab&runId=8349842&resultId=205355)|dotnet/runtime#91239|
|[389287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389287)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389287&view=ms.vss-test-web.build-test-results-tab&runId=8346670&resultId=195593)|dotnet/runtime#91267|
|[389320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389320)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389320&view=ms.vss-test-web.build-test-results-tab&runId=8345508&resultId=182018)|dotnet/runtime#91216|
|[389280](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389280)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389280&view=ms.vss-test-web.build-test-results-tab&runId=8344864&resultId=196009)|dotnet/runtime#91264|
|[389142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389142)|dotnet/runtime|[System.Security.Cryptography.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=389142&view=ms.vss-test-web.build-test-results-tab&runId=8342628&resultId=196804)|dotnet/runtime#91262|
|[388978](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388978)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388978&view=ms.vss-test-web.build-test-results-tab&runId=8337234&resultId=197678)||
|[388942](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388942)|dotnet/runtime|[normal-System.Threading.Tasks.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388942&view=ms.vss-test-web.build-test-results-tab&runId=8336490&resultId=173687)||
|[388902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388902)|dotnet/runtime|[Microsoft.Extensions.HostFactoryResolver.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388902&view=ms.vss-test-web.build-test-results-tab&runId=8334882&resultId=205242)|dotnet/runtime#91176|
|[388878](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388878)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388878&view=ms.vss-test-web.build-test-results-tab&runId=8334362&resultId=196066)|dotnet/runtime#91240|
|[388706](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388706)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388706&view=ms.vss-test-web.build-test-results-tab&runId=8334326&resultId=195593)|dotnet/runtime#91245|
|[388797](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388797)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388797&view=ms.vss-test-web.build-test-results-tab&runId=8333016&resultId=195594)|dotnet/runtime#91237|
|[388672](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388672)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388672&view=ms.vss-test-web.build-test-results-tab&runId=8329196&resultId=211026)|dotnet/runtime#91247|
|[388667](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388667)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388667&view=ms.vss-test-web.build-test-results-tab&runId=8330128&resultId=192118)|dotnet/runtime#91246|
|[388556](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388556)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388556&view=ms.vss-test-web.build-test-results-tab&runId=8327704&resultId=195615)|dotnet/runtime#89952|
|[388379](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388379)|dotnet/runtime|[System.IO.Pipes.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388379&view=ms.vss-test-web.build-test-results-tab&runId=8321204&resultId=204850)|dotnet/runtime#91231|
|[388449](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388449)|dotnet/runtime|[System.Net.Http.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388449&view=ms.vss-test-web.build-test-results-tab&runId=8322070&resultId=181405)||
|[388406](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388406)|dotnet/runtime|[System.Security.Cryptography.OpenSsl.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388406&view=ms.vss-test-web.build-test-results-tab&runId=8321262&resultId=181181)|dotnet/runtime#91190|
|[388166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388166)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388166&view=ms.vss-test-web.build-test-results-tab&runId=8315866&resultId=195692)|dotnet/runtime#91218|
|[388145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388145)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=388145&view=ms.vss-test-web.build-test-results-tab&runId=8315166&resultId=195691)|dotnet/runtime#91154|
|[387880](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387880)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387880&view=ms.vss-test-web.build-test-results-tab&runId=8310336&resultId=194586)|dotnet/runtime#91172|
|[387528](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387528)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387528&view=ms.vss-test-web.build-test-results-tab&runId=8299264&resultId=195583)|dotnet/runtime#91189|
|[387355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387355)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387355&view=ms.vss-test-web.build-test-results-tab&runId=8294002&resultId=195605)|dotnet/runtime#89952|
|[387323](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387323)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387323&view=ms.vss-test-web.build-test-results-tab&runId=8293014&resultId=196056)|dotnet/runtime#90982|
|[387294](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387294)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387294&view=ms.vss-test-web.build-test-results-tab&runId=8292782&resultId=196020)|dotnet/runtime#91171|
|[387117](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387117)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387117&view=ms.vss-test-web.build-test-results-tab&runId=8286502&resultId=195584)|dotnet/runtime#91160|
|[387116](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387116)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387116&view=ms.vss-test-web.build-test-results-tab&runId=8286068&resultId=173008)||
|[387106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387106)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387106&view=ms.vss-test-web.build-test-results-tab&runId=8285514&resultId=195577)||
|[386969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386969)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386969&view=ms.vss-test-web.build-test-results-tab&runId=8279886&resultId=195953)|dotnet/runtime#91154|
|[386929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386929)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386929&view=ms.vss-test-web.build-test-results-tab&runId=8279566&resultId=195583)|dotnet/runtime#90982|
|[386516](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386516)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386516&view=ms.vss-test-web.build-test-results-tab&runId=8266656&resultId=195566)||
|[386357](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386357)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386357&view=ms.vss-test-web.build-test-results-tab&runId=8262326&resultId=195576)||
|[386352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386352)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386352&view=ms.vss-test-web.build-test-results-tab&runId=8261766&resultId=196055)|dotnet/runtime#91133|
|[386233](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386233)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386233&view=ms.vss-test-web.build-test-results-tab&runId=8259474&resultId=195582)|dotnet/runtime#91074|
|[386241](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386241)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386241&view=ms.vss-test-web.build-test-results-tab&runId=8258672&resultId=196056)|dotnet/runtime#91107|
|[386139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386139)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386139&view=ms.vss-test-web.build-test-results-tab&runId=8256076&resultId=195582)|dotnet/runtime#91123|
|[386115](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386115)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386115&view=ms.vss-test-web.build-test-results-tab&runId=8254310&resultId=195582)|dotnet/runtime#91122|
|[386015](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386015)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386015&view=ms.vss-test-web.build-test-results-tab&runId=8251650&resultId=195582)|dotnet/runtime#91116|
|[385733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385733)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385733&view=ms.vss-test-web.build-test-results-tab&runId=8241216&resultId=195582)|dotnet/runtime#90518|
|[385671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385671)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385671&view=ms.vss-test-web.build-test-results-tab&runId=8239130&resultId=195582)|dotnet/runtime#91102|
|[385446](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385446)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385446&view=ms.vss-test-web.build-test-results-tab&runId=8236334&resultId=195582)|dotnet/runtime#89405|
|[385484](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385484)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385484&view=ms.vss-test-web.build-test-results-tab&runId=8236224&resultId=195394)||
|[385364](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385364)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385364&view=ms.vss-test-web.build-test-results-tab&runId=8228874&resultId=197859)||
|[385005](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385005)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385005&view=ms.vss-test-web.build-test-results-tab&runId=8225244&resultId=195582)|dotnet/runtime#89102|
|[384990](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384990)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384990&view=ms.vss-test-web.build-test-results-tab&runId=8223646&resultId=195582)|dotnet/runtime#91077|
|[384688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384688)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384688&view=ms.vss-test-web.build-test-results-tab&runId=8214886&resultId=195520)|dotnet/runtime#91057|
|[384597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384597)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384597&view=ms.vss-test-web.build-test-results-tab&runId=8212038&resultId=195581)|dotnet/runtime#91050|
|[384450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384450)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384450&view=ms.vss-test-web.build-test-results-tab&runId=8205280&resultId=195520)|dotnet/runtime#91033|
|[384447](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384447)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384447&view=ms.vss-test-web.build-test-results-tab&runId=8205056&resultId=195581)|dotnet/runtime#91032|
|[384038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384038)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384038&view=ms.vss-test-web.build-test-results-tab&runId=8201510&resultId=199703)|dotnet/runtime#90790|
|[383772](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383772)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383772&view=ms.vss-test-web.build-test-results-tab&runId=8190128&resultId=195581)|dotnet/runtime#88034|
|[382759](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382759)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382759&view=ms.vss-test-web.build-test-results-tab&runId=8188516&resultId=195581)|dotnet/runtime#90954|
|[378797](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378797)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378797&view=ms.vss-test-web.build-test-results-tab&runId=8066972&resultId=195836)|dotnet/runtime#90809|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|18|64|65|

### PR DESCRIPTION
**Pull request by BrzVlad**
Hash table operations under the mem manager lock could end up taking the loader lock when performing type comparison, in the case where custom modifiers needed to be loaded. Use the loader lock instead to prevent deadlocks.

Fixes https://github.com/dotnet/runtime/issues/90834

### CODE REVIEW

File: src/mono/mono/metadata/metadata.c [hunk 1]
```diff
@@ -3434,7 +3434,8 @@ mono_metadata_get_canonical_generic_inst (MonoGenericInst *candidate)
 	MonoMemoryManager *mm = mono_mem_manager_get_generic (data.images, data.nimages);
 	collect_data_free (&data);
 
-	mono_mem_manager_lock (mm);
+	// Hashtable key equal func can take loader lock
```
Comment (lambdageek) [inline src/mono/mono/metadata/metadata.c:3437]: In `loader-internals.h` the following other caches do a deep comparison that might also have a problem:

* `gmethod_cache`
* `gsignature_cache`
* `gclass_cache`

There's also a ton of hashtables in `MonoWrapperCaches`, but I didn't check them - from my recollection they mostly do pointer comparison.

Comment (lambdageek) [reply src/mono/mono/metadata/metadata.c:3437]: I checked for other uses of `g_hash_table_new_full` with a comparison func that looks like it's doing deep type equality.  The only other places (besides the ones in the previous comment) are the 3 caches in `mini-generic-sharing.c` that call `mono_metadata_signature_equal` under the `gshared_lock()`.  I don't understand generic sharing well enough to tell if this needs to change to the loader lock, too. /cc @vargaz

Comment (BrzVlad) [reply src/mono/mono/metadata/metadata.c:3437]: Thanks for taking a look. Not sure why you mention `gmethod_cache` and `gsignature_cache`, the equality function only does ref compares. Added a new commit to handle `gclass_cache`.  I don't think any of those wrapper creation methods are called while holding the loader lock. If that's the case we can't deadlock there.

Comment (lambdageek) [reply src/mono/mono/metadata/metadata.c:3437]: You're right. For some reason I thought `mono_metadata_generic_context_equal` does a deep equality - I think I probably wasn't careful when looking around the code.

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
We should backport to net8.0 /cc @SamMonoRT

**Comment by carlossanlop** [comment]
@BrzVlad @SamMonoRT @lambdageek is this ready to get backported? I think this is the most impactful failure in 8.0.

**Comment by vargaz** [comment]
Wouldn't be better to modify the hashtable equality functions so they wouldn't lock ?

**Comment by lambdageek** [comment]
That might be difficult - I think the issue is that they indirectly trigger assembly loading. Although maybe there's some way to avoid it

**Comment by vargaz** [comment]
Is there a stacktrace which shows this happening ?

**Comment by BrzVlad** [comment]
```
frame #0: 0x00007ff803797892 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x00007ff8037d1b14 libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_wait + 76
    frame #2: 0x00007ff8037cf921 libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_slow + 214
    frame #3: 0x000000010b1ff905 libcoreclr.dylib`mono_os_mutex_lock(mutex=0x000000010b3d8ec0) at mono-os-mutex.h:105:8
    frame #4: 0x000000010b1ffae1 libcoreclr.dylib`mono_coop_mutex_lock(mutex=0x000000010b3d8ec0) at mono-coop-mutex.h:57:2
    frame #5: 0x000000010b1ffa39 libcoreclr.dylib`mono_loader_lock at loader.c:136:2
    frame #6: 0x000000010b1ab4e8 libcoreclr.dylib`mono_class_create_from_typedef(image=0x00007f7b2f815200, type_token=33555983, error=0x0000700011720a80) at class-init.c:486:2
    frame #7: 0x000000010b19e7f1 libcoreclr.dylib`mono_class_get_checked(image=0x00007f7b2f815200, type_token=33555983, error=0x0000700011720a80) at class.c:2925:11
    frame #8: 0x000000010b19fc83 libcoreclr.dylib`mono_class_from_name_checked_aux(image=0x00007f7b2f815200, name_space="System.Runtime.CompilerServices", name="IsConst", visited_images=0x0000600000ffe5c0, case_sensitive=1, error=0x0000700011720a80) at class.c:3444:10
    frame #9: 0x000000010b19fbc7 libcoreclr.dylib`mono_class_from_name_checked_aux(image=0x00007f7b2e816200, name_space="System.Runtime.CompilerServices", name="IsConst", visited_images=0x0000600000ffe5c0, case_sensitive=1, error=0x0000700011720a80) at class.c:3433:12
    frame #10: 0x000000010b19758e libcoreclr.dylib`mono_class_from_name_checked(image=0x00007f7b2e816200, name_space="System.Runtime.CompilerServices", name="IsConst", error=0x0000700011720a80) at class.c:3470:10
    frame #11: 0x000000010b197456 libcoreclr.dylib`mono_class_from_typeref_checked(image=0x00007f7b2f902c00, type_token=16777219, error=0x0000700011720a80) at class.c:214:8
    frame #12: 0x000000010b19e80a libcoreclr.dylib`mono_class_get_checked(image=0x00007f7b2f902c00, type_token=16777219, error=0x0000700011720a80) at class.c:2928:11
    frame #13: 0x000000010b19eae1 libcoreclr.dylib`mono_type_get_checked(image=0x00007f7b2f902c00, type_token=16777219, context=0x0000000000000000, error=0x0000700011720a80) at class.c:2976:22
    frame #14: 0x000000010b226dd8 libcoreclr.dylib`mono_type_get_custom_modifier(ty=0x00006000014fdb90, idx='\0', required=0x0000700011720a74, error=0x0000700011720a80) at metadata.c:6043:10
    frame #15: 0x000000010b22dd5e libcoreclr.dylib`mono_metadata_custom_modifiers_equal(t1=0x00006000014fdb90, t2=0x00006000014e1110, signature_only=0) at metadata.c:5781:24
    frame #16: 0x000000010b2265b6 libcoreclr.dylib`do_mono_metadata_type_equal(t1=0x00006000014fdb90, t2=0x00006000014e1110, equiv_flags=0) at metadata.c:5816:19
    frame #17: 0x000000010b21f7b1 libcoreclr.dylib`mono_generic_inst_equal_full(a=0x00007f7b32030410, b=0x0000700011720e90, signature_only=0) at metadata.c:1909:8
    frame #18: 0x000000010b21f69f libcoreclr.dylib`mono_metadata_generic_inst_equal(ka=0x00007f7b32030410, kb=0x0000700011720e90) at metadata.c:1921:9
    frame #19: 0x000000010b14f53d libcoreclr.dylib`monoeg_g_hash_table_lookup_extended(hash=0x0000600000fcc740, key=0x0000700011720e90, orig_key=0x0000700011720c10, value=0x0000700011720c08) at ghashtable.c:341:7
    frame #20: 0x000000010b14f5d5 libcoreclr.dylib`monoeg_g_hash_table_lookup(hash=0x0000600000fcc740, key=0x0000700011720e90) at ghashtable.c:321:6
    frame #21: 0x000000010b221e46 libcoreclr.dylib`mono_metadata_get_canonical_generic_inst(candidate=0x0000700011720e90) at metadata.c:3442:46
    frame #22: 0x000000010b221ce8 libcoreclr.dylib`mono_metadata_get_generic_inst(type_argc=2, type_argv=0x00006000018bd260) at metadata.c:3409:9
    frame #23: 0x000000010b222c9f libcoreclr.dylib`mono_metadata_parse_generic_inst(m=0x00007f7b2f902c00, container=0x0000000000000000, count=2, ptr="\b0\U00000001\U00000001\U00000001 \r\U0000001e", rptr=0x0000700011720fa8, error=0x0000700011721360) at metadata.c:3635:10
    frame #24: 0x000000010b22cef3 libcoreclr.dylib`do_mono_metadata_parse_generic_class(type=0x00007000117210f8, m=0x00007f7b2f902c00, container=0x0000000000000000, ptr="\b0\U00000001\U00000001\U00000001 \r\U0000001e", rptr=0x0000700011721020, error=0x0000700011721360) at metadata.c:3668:9
    frame #25: 0x000000010b22c988 libcoreclr.dylib`do_mono_metadata_parse_type(type=0x00007000117210f8, m=0x00007f7b2f902c00, container=0x0000000000000000, transient=0, ptr="\U00000012\t\U00000002\b \r\U00000002\b0\U00000001\U00000001\U00000001 \r\U0000001e", rptr=0x00007000117210c0, error=0x0000700011721360) at metadata.c:4093:8
    frame #26: 0x000000010b22c2e9 libcoreclr.dylib`do_mono_metadata_parse_type_with_cmods(type=0x00007000117210f8, cmod_count=0, m=0x00007f7b2f902c00, container=0x0000000000000000, opt_attrs=0, transient=0, ptr="\U00000015\U00000012\t\U00000002\b \r\U00000002\b0\U00000001\U00000001\U00000001 \r\U0000001e", rptr=0x0000700011721208, error=0x0000700011721360) at metadata.c:2151:7
    frame #27: 0x000000010b21fb38 libcoreclr.dylib`mono_metadata_parse_type_internal(m=0x00007f7b2f902c00, container=0x0000000000000000, opt_attrs=0, transient=0, ptr="\U00000015\U00000012\t\U00000002\b \r\U00000002\b0\U00000001\U00000001\U00000001 \r\U0000001e", rptr=0x0000700011721208, error=0x0000700011721360) at metadata.c:2233:7
    frame #28: 0x000000010b21fa35 libcoreclr.dylib`mono_metadata_parse_type_checked(m=0x00007f7b2f902c00, container=0x0000000000000000, opt_attrs=0, transient=0, ptr="\U00000015\U00000012\t\U00000002\b \r\U00000002\b0\U00000001\U00000001\U00000001 \r\U0000001e", rptr=0x0000700011721208, error=0x0000700011721360) at metadata.c:2265:9
    frame #29: 0x000000010b2205e6 libcoreclr.dylib`mono_metadata_parse_method_signature_full(m=0x00007f7b2f902c00, container=0x0000000000000000, def=2, ptr="\U00000015\U00000012\t\U00000002\b \r\U00000002\b0\U00000001\U00000001\U00000001 \r\U0000001e", rptr=0x0000000000000000, error=0x0000700011721360) at metadata.c:2717:24
    frame #30: 0x000000010b2033ce libcoreclr.dylib`mono_method_signature_checked_slow(m=0x00007f7b3030ddf8, error=0x0000700011721360) at loader.c:1850:15
    frame #31: 0x000000010b200c4b libcoreclr.dylib`mono_method_signature_checked(m=0x00007f7b3030ddf8, error=0x0000700011721360) at class-internals.h:775:21
    frame #32: 0x000000010b20383b libcoreclr.dylib`mono_method_signature_internal_slow(m=0x00007f7b3030ddf8) at loader.c:1940:29
    frame #33: 0x000000010b1d0f09 libcoreclr.dylib`mono_method_signature_internal(m=0x00007f7b3030ddf8) at class-internals.h:786:21
    frame #34: 0x000000010b1d7cb1 libcoreclr.dylib`ves_icall_RuntimeMethodInfo_get_IsGenericMethod(ref_method=MonoReflectionMethodHandle @ 0x0000700011721418, erro=0x0000700011721460) at icall.c:3466:9
    frame #35: 0x000000010b1eb58b libcoreclr.dylib`ves_icall_RuntimeMethodInfo_get_IsGenericMethod_raw(a0=0x0000700011721520) at icall-def.h:402:1
    frame #36: 0x0000000110030708
    frame #37: 0x000000010ae3c273 libcoreclr.dylib`mono_jit_runtime_invoke(method=0x00007f7b2ebee728, obj=0x0000000000000000, params=0x0000000000000000, exc=0x00007000117216c0, error=0x0000700011721a50) at mini-runtime.c:3681:12
    frame #38: 0x000000010b23d3b6 libcoreclr.dylib`do_runtime_invoke(method=0x00007f7b2ebee728, obj=0x0000000000000000, params=0x0000000000000000, exc=0x0000000000000000, error=0x0000700011721a50) at object.c:2542:11
    frame #39: 0x000000010b237761 libcoreclr.dylib`mono_runtime_invoke_checked(method=0x00007f7b2ebee728, obj=0x0000000000000000, params=0x0000000000000000, error=0x0000700011721a50) at object.c:2758:9
    frame #40: 0x000000010b243bdf libcoreclr.dylib`mono_runtime_try_invoke_byrefs(method=0x00007f7b2ebee728, obj=0x0000000000000000, params_byref=0x0000000000000000, exc=0x0000000000000000, error=0x0000700011721a50) at object.c:5142:16
    frame #41: 0x000000010b1d8c14 libcoreclr.dylib`ves_icall_InternalInvoke(method_handle=MonoReflectionMethodHandle @ 0x0000700011721968, this_arg_handle=MonoObjectHandle @ 0x0000700011721960, params_byref=0x0000000000000000, exception_out=MonoExceptionHandleOut @ 0x0000700011721958, error=0x0000700011721a50) at icall.c:3622:11
    frame #42: 0x000000010b1ea48f libcoreclr.dylib`ves_icall_InternalInvoke_raw(a0=0x0000700011721b48, a1=0x0000700011721b50, a2=0x0000000000000000, a3=0x0000700011721b40) at icall-def.h:371:1
```
