### PR TITLE
Define a DllMain for native AOT shared libraries

### LINKED ISSUE #109543: [NativeAOT] Creating a new thread from DllMain makes the program get stuck.
### Description

NativeAOT dlls get stuck when creating a new thread from DllMain using `new Thread()`.
`Task.Run` does similar behavior, instead when I try to sleep inside the Task, it gets stuck.

### Reproduction Steps

- Make NativeAOT dynamic library project for Windows with DllMain.
```cs
using System.Runtime.InteropServices;
using Windows.Win32;

namespace ThreadTesting;

public static class ThreadTest {
    [UnmanagedCallersOnly(EntryPoint = "DllMain")]
    public unsafe static int DllMain(nint hModule, uint ul_reason_for_call, nint lpReserved) {
        // DLL_PROCESS_ATTACH = 1
        if (ul_reason_for_call == 1) {
            Console.WriteLine("Creating new thread");

            var thread = new Thread(SomeFunction);
            // It gets stuck here
            thread.Start();

            Console.WriteLine("Thread created");
        }

        return 1;
    }

    public static void SomeFunction() {
        Console.WriteLine("Hello inside new thread");
        Thread.Sleep(1000);
        Console.WriteLine("Slept successfully");
    }
}
```

- Make a simple C++ console app that loads the library with LoadLibrary.
```cpp
int main()
{
    LoadLibrary(L"ThreadTesting.dll");
}
```

### Expected behavior

The new thread runs correctly.

### Actual behavior

The program gets stuck.

### Regression?

_No response_

### Known Workarounds

Using Native Windows function CreateThread (PInvoke) works.

### Configuration

- .NET 9.0.0-rc.2.24473.5
- Windows 11 Build 22631
- x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
In theory a breaking change since any other `DllMain` would cause a symbol conflict during linking.

Closes #109543

### CODE REVIEW

File: src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+// No-op DllMain. The purpose is to reserve DllMain for our purposes.
+//
+// Some users also try to define a DllMain in managed code using an UnmanagedCallersOnly
+// attribute. This will not work correctly because the entire runtime initialization would run
+// as part of such DllMain, before the first line of users DllMain executes. We don't support
+// initializing the runtime under loader lock.
+//
+BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
+{
```
Comment (jkotas) [inline src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: Call `DisableThreadLibraryCalls`?

The weakly-linked default DllMain that we use today does that.

Comment (MichalPetryka) [reply src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: Does NativeAOT not static link the CRT in some cases? Static CRT forbids calling `DisableThreadLibraryCalls`.

Comment (jkotas) [reply src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: > Does NativeAOT not static link the CRT in some cases?

It does for debug builds only. I guess we can call `DisableThreadLibraryCalls` only when building release bits that link CRT dynamically. Is there a define that can be used to detect whether the compilation targets dynamic or static CRT?

Comment (MichalPetryka) [reply src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: > Is there a define that can be used to detect whether the compilation targets dynamic or static CRT?

Seems `#ifndef _DLL` is the documented way for it.

Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: Would `DisableThreadLibraryCalls` do anything? The API is documented as "This function does not perform any optimizations if static [Thread Local Storage (TLS)](https://learn.microsoft.com/en-us/windows/win32/procthread/thread-local-storage) is enabled. Static TLS is enabled when using thread_local variables, __declspec( thread ) variables, or function-local static."

Comment (MichalPetryka) [reply src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: > Would `DisableThreadLibraryCalls` do anything? The API is documented as "This function does not perform any optimizations if static [Thread Local Storage (TLS)](https://learn.microsoft.com/en-us/windows/win32/procthread/thread-local-storage) is enabled. Static TLS is enabled when using thread_local variables, __declspec( thread ) variables, or function-local static."

`Do not call this function from a DLL that is linked to the static C run-time library (CRT). The static CRT requires DLL_THREAD_ATTACH and DLL_THREAD_DETATCH notifications to function properly.`

Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: > > Would `DisableThreadLibraryCalls` do anything? The API is documented as "This function does not perform any optimizations if static [Thread Local Storage (TLS)](https://learn.microsoft.com/en-us/windows/win32/procthread/thread-local-storage) is enabled. Static TLS is enabled when using thread_local variables, __declspec( thread ) variables, or function-local static."
> 
> `Do not call this function from a DLL that is linked to the static C run-time library (CRT). The static CRT requires DLL_THREAD_ATTACH and DLL_THREAD_DETATCH notifications to function properly.`

Is that related?

Comment (jkotas) [reply src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: > This function does not perform any optimizations if static [Thread Local Storage (TLS)](https://learn.microsoft.com/en-us/windows/win32/procthread/thread-local-storage) is enabled. Static TLS is enabled when using thread_local variables, __declspec( thread ) variables, or function-local static.

Interesting. I did not know that `DisableThreadLibraryCalls` is no-op if the target .dll has thread statics.

Comment (MichalPetryka) [reply src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: > > > Would `DisableThreadLibraryCalls` do anything? The API is documented as "This function does not perform any optimizations if static [Thread Local Storage (TLS)](https://learn.microsoft.com/en-us/windows/win32/procthread/thread-local-storage) is enabled. Static TLS is enabled when using thread_local variables, __declspec( thread ) variables, or function-local static."
> > 
> > 
> > `Do not call this function from a DLL that is linked to the static C run-time library (CRT). The static CRT requires DLL_THREAD_ATTACH and DLL_THREAD_DETATCH notifications to function properly.`
> 
> Is that related?

That's from the docs of `DisableThreadLibraryCalls`.

**Review by jkotas — APPROVED** [review]
LGTM!

File: src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/nativeaot/Bootstrap/dllmain/dllmain.cpp:14]: > Interesting. I did not know that DisableThreadLibraryCalls is no-op if the target .dll has thread statics.

It means that this change is a tiny perf optimization. It will skip the unnecessary `DisableThreadLibraryCalls` call that the boilerplate DllMain does now.

**Comment by huoyaoyuan** [comment]
This looks like a better fix to me. The hacky usages replacing the nativeaot runtime won't be blocked.

I think we should highlight this in documentation, both breaking change and DllExport.

**Comment by MichalPetryka** [comment]
> This looks like a better fix to me.

My only issue with this is that it'll break legitimate uses of `DllMain` from native static libs without managed code.

**Comment by jkotas** [comment]
> My only issue with this is that it'll break legitimate uses of DllMain from native static libs without managed code.

I do not think so. These cases have to have their own build targets to call the linker. They cannot use the default targets that this change is modifying. The default build targets initialize GC and related subsystems unconditionally.

**Comment by MichalStrehovsky** [comment]
> > This looks like a better fix to me.
> 
> My only issue with this is that it'll break legitimate uses of `DllMain` from native static libs without managed code.

One cannot just `<NativeLibrary Include="somelib.lib" />` and expect link.exe to pick up a DllMain in it (it will not pick it up because there already is a weak definition in the CRT itself, even before this change). It requires more messing with linker arguments. These are all scenarios that are likely to quickly run into unsupported territories. We provide a linker argument passthrough, but cannot support all possible values people could pass.

**Comment by slxdy** [comment]
So the better idea is to just completely block it... even for unmanaged parts of the library. 👏

**Comment by HerpDerpinstine** [comment]
This just broke existing projects that were using this successfully without issue.....

**Comment by nitrog0d** [comment]
Can't believe out of all ways to do this, this is the way you do it... Really will make us start compiling .NET just for own use.

**Comment by hez2010** [comment]
> So the better idea is to just completely block it... even for unmanaged parts of the library. 👏

You can always opt-out the behavior by calling the linker on your own, or writing your own MSBuild target to manipulate the arguments passed to the linker. 
The default MSBuild target never supports linking against a library containing a `DllMain` symbol.

**Comment by slxdy** [comment]
Because who cares about community feedback, am I right?

**Comment by hez2010** [comment]
This is done to resolve the long-standing issue that being asked again and again why their `DllMain` doesn't work. This can never be supported by default.
If you are an advanced user who has a runtime implementation that can get it to work, you are already not using the built-in targets directly. So this won't block any existing users.

**Comment by huoyaoyuan** [comment]
`DllMain` never worked consistently, and can't work consistently with current GC model. The real impacted users are luck-driven usages that fails randomly or consistently.
There's really no commitment for luck-driven usages.

**Comment by HerpDerpinstine** [comment]
> `DllMain` never worked consistently, and can't work consistently with current GC model. The real impacted users are luck-driven usages that fails randomly or consistently. There's really no commitment for luck-driven usages.

There were projects that were able to use it without failing randomly or consistently.
The issue was more-so the end developer wasn't more informed about how unsafe and unstable it could possibly get when used in some ways.

**Comment by slxdy** [comment]
For anyone still needing DllMain in C#, I'm thinking of creating a nuget package for a reliable™ 'OnLoad' callback.
If you think this is a good idea or would like to help, please let me know :)

The idea is to write a C++ static lib which will be linked to your NativeAOT library. The lib will get a callback by calling a constructor on a global object (the CRT will do this before calling the user-defined DllMain). After this, we can use a technique shown in https://github.com/ElliotKillick/LdrLockLiberator to escape the loader lock. It would then simply call one of our exported functions in NativeAOT. I'm not exactly sure how to turn that into a nuget package, but I'm sure it can be done.

**Comment by jkotas** [comment]
> a technique shown in https://github.com/ElliotKillick/LdrLockLiberator 

Note that these techniques depend on undocumented Windows APIs and undocumented internal Windows implementation details discovered via reverse engineering. I doubt that they are fully reliable, and they are prone to get broken by Windows updates.

**Comment by slxdy** [comment]
I mean, if anything, Microsoft finally cleaning up the kernel would be a blessing, but I doubt that's ever gonna happen at this point 😅

**Comment by huoyaoyuan** [comment]
A major usage of `DllMain` is hooking as of my knowledge, which is already in gray area. It's often broken by security/reliability features, for example `DllImportSearchPath.System32`.

As a personal developer I'm glad to see the gray areas being open, but it's not the case for more serious usages.
