### PR TITLE
Return null instead of throwing in ServiceDescriptor.ImplementationInstance\Type\Factory if a keyed service

### LINKED ISSUE #95789: ServiceDescriptor.ImplementationType throws exception for Keyed descriptor: System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.
### Description

It looks like an intentional behavior is breaking a lot of existing code. There are a lot of places that inspect/iterate over ServiceCollection and look for a specific ImplementationType as a way of custom TryAdd. This works fine with `Microsoft.Extensions.DependencyInjection.Abstractions` v8.0.0, until a Keyed descriptor is added before the offending inspection.

This is happening on all frameworks supported by `Microsoft.Extensions.DependencyInjection.Abstractions` (v8) - it's not framework-dependent.

Now, I understand that this is not a good practice (iterating and inspecting ImplementationType). Sadly, it seems to be a common practice, even including multiple Microsoft products:
- https://github.com/microsoft/ApplicationInsights-dotnet/issues/2828
- https://github.com/AzureAD/microsoft-identity-web/issues/2604

Problematic source code:

https://github.com/dotnet/runtime/blob/611934fcd58a6d0ab8ff7000d48f491b56931c08/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs#L158-L168

### Reproduction Steps

- `dotnet new console`
- `dotnet add package Microsoft.Extensions.DependencyInjection`

`Program.cs`

```csharp
using Microsoft.Extensions.DependencyInjection;

var services = new ServiceCollection();
services.AddKeyedSingleton<FooService>("key");
services.FirstOrDefault(x => x.ImplementationType == typeof(BarService));

class FooService {}
class BarService {}
```

`dotnet run` throws:

```
Unhandled exception. System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType()
   at Program.<>c.<<Main>$>b__0_0(ServiceDescriptor x) in C:\Users\amadeusz.sadowski\dev\test-keyed\KeyedExceptionRepro\Program.cs:line 5
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Program.<Main>$(String[] args) in C:\Users\amadeusz.sadowski\dev\test-keyed\KeyedExceptionRepro\Program.cs:line 5
```

### Expected behavior

Existing libraries keep working - exception is not thrown. Maybe just return null.

### Actual behavior

`InvalidOperationException` is thrown when iterating over registered descriptors' `ImplementationType`.

### Regression?

Definitely a regression. This works with all versions of DependencyInjection up until v8.

### Known Workarounds

Attempt to register keyed service after registrations that inspect ServiceCollection.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by steveharter**
Fixes https://github.com/dotnet/runtime/issues/95789

This fixes a regression for cases where `ServiceDescriptor.ImplementationInstance\Type\Factory` is called for code that is not servicekey-aware. Instead of throwing, `null` is returned.

This will be backported to 8.0.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs [hunk 1]
```diff
@@ -1058,8 +1048,6 @@ private string DebuggerToString()
             return debugText;
         }
 
-        private static void ThrowKeyedDescriptor() => throw new InvalidOperationException(SR.KeyedDescriptorMisuse);
-
         private static void ThrowNonKeyedDescriptor() => throw new InvalidOperationException(SR.NonKeyedDescriptorMisuse);
```
Comment (benjaminpetit) [inline src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs:1051]: If we don't throw when accessing on non-leyed property when the descriptor is kedyed, shoud we also remove this, to be consistent?

Comment (steveharter) [reply src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs:1051]: I was wondering about that as well. The original issue was a backwards compat issue with existing APIs so not throwing there makes sense. Throwing for the new APIs I think is OK and desired to help catch issues (as originally intended).

Other than consistency, can you think of a scenario where we would want to return null for the new APIs?

File: src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs [hunk 2]
```diff
@@ -152,24 +152,20 @@ private ServiceDescriptor(Type serviceType, object? serviceKey, ServiceLifetime
...
+        public Type? ImplementationType => IsKeyedService ? null : _implementationType;
 
         /// <summary>
-        /// Gets the <see cref="Type"/> that implements the service.
+        /// Gets the <see cref="Type"/> that implements the service,
+        /// or throws <see cref="InvalidOperationException"/> if <see cref="IsKeyedService"/> is <see langword="false"/>.
         /// </summary>
+        /// <remarks>
+        /// If <see cref="IsKeyedService"/> is <see langword="false"/>, <see cref="ImplementationType"/> should be called instead.
+        /// </remarks>>
```
Comment (buyaa-n) [inline src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs:168]: NIT: extra `>` here and all similar `</remarks>>` below
```suggestion
        /// </remarks>
```

File: src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs [hunk 3]
```diff
@@ -152,24 +152,20 @@ private ServiceDescriptor(Type serviceType, object? serviceKey, ServiceLifetime
         private Type? _implementationType;
 
         /// <summary>
-        /// Gets the <see cref="Type"/> that implements the service.
+        /// Gets the <see cref="Type"/> that implements the service,
+        /// or returns <see langword="null"/> if <see cref="IsKeyedService"/> is <see langword="true"/>.
         /// </summary>
+        /// If <see cref="IsKeyedService"/> is <see langword="true"/>, <see cref="KeyedImplementationType"/> should be called instead.
```
Comment (buyaa-n) [inline src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs:158]: NIT: Might wanted to put inside `<remarks>` tag? Here and all similar cases below
```suggestion
        /// <remarks>
        /// If <see cref="IsKeyedService"/> is <see langword="true"/>, <see cref="KeyedImplementationType"/> should be called instead.
        /// <remarks/>
```

**Review by buyaa-n — APPROVED** [review]
Nits on docs, otherwise LGTM

File: src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs (hunk 1 above)
Comment (benjaminpetit) [reply src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs:1051]: Nope it's only for consistency's sake. It's fine to me to throw here otherwise

**Review by benjaminpetit — APPROVED** [review]

File: src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs (hunk 2 above)
Comment (steveharter) [reply src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs]: Nice catch

File: src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs (hunk 3 above)
Comment (steveharter) [reply src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs:159]: Thanks. Done

**Comment by steveharter** [comment]
`/backport to release/8.0-staging`
