### PR TITLE
Fix Idna Test

### LINKED ISSUE #72749: system.globalization.tests.idnmappingidnaconformancetests.getascii_invalid
Runfo Tracking Issue: [system.globalization.tests.idnmappingidnaconformancetests.getascii_invalid](https://runfo.azurewebsites.net/tracking/issue/390)
|Build|Definition|Kind|Run Name|
|---|---|---|---|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/72749

### CODE REVIEW

**Comment by tarekgh** [comment]
@eerhardt could you please have a look?

**Comment by danmoseley** [comment]
Is this something we should report to Windows?

File: src/libraries/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_9_0/Unicode_9_0_IdnaTest.cs [hunk 1]
```diff
@@ -26,7 +26,14 @@ public Unicode_9_0_IdnaTest(string line, int lineNumber)
 
             Type = ConvertStringToType(split[0].Trim());
             Source = EscapedToLiteralString(split[1], lineNumber);
-            bool validDomainName = (split.Length != 5 || split[4].Trim() != "NV8");
+            bool validDomainName = (split.Length != 5 || split[4].Trim() != "NV8"); 
+            
+            // On Server 2019, uses ICU 61.0 which IDNA not supporting the following cases. Ignore these entries there.
+            if (PlatformDetection.IsWindowsServer2019 && Source.EndsWith("\ud802\udf8b\u3002\udb40\udd0a", StringComparison.Ordinal))
+            {
+                Source = "";
```
Comment (filipnavara) [inline src/libraries/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_9_0/Unicode_9_0_IdnaTest.cs:34]: Why not use `Assert.Skip`?

Comment (stephentoub) [reply src/libraries/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_9_0/Unicode_9_0_IdnaTest.cs:34]: Because it doesn't exist? :smile:

File: src/libraries/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_9_0/Unicode_9_0_IdnaTest.cs [hunk 2]
```diff
@@ -26,7 +26,14 @@ public Unicode_9_0_IdnaTest(string line, int lineNumber)
 
             Type = ConvertStringToType(split[0].Trim());
             Source = EscapedToLiteralString(split[1], lineNumber);
-            bool validDomainName = (split.Length != 5 || split[4].Trim() != "NV8");
+            bool validDomainName = (split.Length != 5 || split[4].Trim() != "NV8"); 
+            
+            // On Server 2019, uses ICU 61.0 which IDNA not supporting the following cases. Ignore these entries there.
```
Comment (stephentoub) [inline src/libraries/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_9_0/Unicode_9_0_IdnaTest.cs:31]:
```suggestion
            // Server 2019 uses ICU 61.0 whose IDNA does not support the following cases. Ignore these entries there.
```

**Review by stephentoub — APPROVED** [review]

File: src/libraries/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_9_0/Unicode_9_0_IdnaTest.cs (hunk 1 above)
Comment (filipnavara) [reply src/libraries/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_9_0/Unicode_9_0_IdnaTest.cs:34]: I was [convinced it does](https://github.com/xunit/xunit/issues/2073#issuecomment-786846718). Then again I regularly have to switch between xUnit and NUnit and I could have just assumed it must exist...

Comment (stephentoub) [reply src/libraries/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_9_0/Unicode_9_0_IdnaTest.cs:34]: It very well might in xunit v3.  We use v2 (v3 isn't released yet to my knowledge).

Comment (filipnavara) [reply src/libraries/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_9_0/Unicode_9_0_IdnaTest.cs:34]: Oh well, I will check back in a year or so, it would be perfect fit here.

**Review by eerhardt — APPROVED** [review]
LGTM - once the comment is cleaned up as suggested by @stephentoub

**Comment by tarekgh** [comment]
@danmoseley 

> Is this something we should report to Windows?

No, it happens on Windows Server 2019 carrying ICU v61.1 which has this behavior. I don't think Windows can risk upgrading ICU there.
