### PR TITLE
Fix layout and GCInfo for ByRef fields.

### LINKED ISSUE #64465: R2R-CrossGen2 failure - loader\\classloader\\reffields\\validate\\validate.cmd
Runfo Tracking Issue: [R2R-CrossGen2 failure - loader\\classloader\\reffields\\validate\\validate.cmd](https://runfo.azurewebsites.net/tracking/issue/260)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1b639b101e9e4c78ac/Loader.classloader/1/console.8d0518e0.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A06%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DSZAHuikWQWSZtZ93EMtoCG2AzbWfVdEIf7wF5sz8qyo%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1b639b101e9e4c78ac/Loader.classloader/106cda19-7650-4fa9-af20-d92ab4aa06f8.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A06%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DSZAHuikWQWSZtZ93EMtoCG2AzbWfVdEIf7wF5sz8qyo%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0d5326de3b3a4a879f/Loader.classloader/1/console.14f360ad.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A06%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DUICr%25252FBjfCzI%25252BW0hZGz3%25252Bi6IgqvaC4R1IWltlFVqaxF0%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0d5326de3b3a4a879f/Loader.classloader/fe819a87-231b-4bac-9990-31146c88b5c4.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A06%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DUICr%25252FBjfCzI%25252BW0hZGz3%25252Bi6IgqvaC4R1IWltlFVqaxF0%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-dc35a40ec29c42e0ad/Loader.classloader/1/console.409258c4.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A49Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DgFg7CMXkAqkJGWP3pw4%25252FuHQR6nq9xeRq2I5ycOfSF8M%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-dc35a40ec29c42e0ad/Loader.classloader/1/corerun.exe.5752.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A49Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DgFg7CMXkAqkJGWP3pw4%25252FuHQR6nq9xeRq2I5ycOfSF8M%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-dc35a40ec29c42e0ad/Loader.classloader/562e5fd3-6917-4ef1-86ca-e620c21e0089.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A49Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DgFg7CMXkAqkJGWP3pw4%25252FuHQR6nq9xeRq2I5ycOfSF8M%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-6e1f4fba517443f095/Loader.classloader/1/console.cb3f225d.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A49Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DUyIr%25252BQCxquaY5KkWblfDWfpp4GoRu0rzGHu0aUGjmU0%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-6e1f4fba517443f095/Loader.classloader/1/corerun.exe.5312.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A49Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DUyIr%25252BQCxquaY5KkWblfDWfpp4GoRu0rzGHu0aUGjmU0%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-6e1f4fba517443f095/Loader.classloader/62074c4b-6347-492a-a075-2324dd6b9b8c.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A49Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DUyIr%25252BQCxquaY5KkWblfDWfpp4GoRu0rzGHu0aUGjmU0%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-aa42e05d7eb047faa9/Loader.classloader/1/console.d5ec7264.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A13%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DpFEwdysk1KffRxmWZf%25252FnEj2x8e1vlNKwvy0ZGe5lQJg%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-aa42e05d7eb047faa9/Loader.classloader/1/corerun.exe.3184.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A13%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DpFEwdysk1KffRxmWZf%25252FnEj2x8e1vlNKwvy0ZGe5lQJg%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-aa42e05d7eb047faa9/Loader.classloader/261c51ab-626d-4512-871a-9ab535191205.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A13%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DpFEwdysk1KffRxmWZf%25252FnEj2x8e1vlNKwvy0ZGe5lQJg%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d5e62b7c0e164ebf81/Loader.classloader/1/console.9a2281c8.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A13%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DddTXmMAml65IsqfJ%25252F1ASH5K7AlfI7iYyXNojLM3nG78%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d5e62b7c0e164ebf81/Loader.classloader/1/corerun.exe.5892.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A13%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DddTXmMAml65IsqfJ%25252F1ASH5K7AlfI7iYyXNojLM3nG78%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d5e62b7c0e164ebf81/Loader.classloader/f7cfe552-0bbb-4482-bfd9-28f99e878b13.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A13%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DddTXmMAml65IsqfJ%25252F1ASH5K7AlfI7iYyXNojLM3nG78%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c67832fdcfa34ed9aa/Loader.classloader/1/console.3b2c6523.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A16%25253A27Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DOVldTW1b3tL9Vtp3u1Ntg8ikTZXvabX%25252FmUfMzzLuZwI%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c67832fdcfa34ed9aa/Loader.classloader/10bc089a-c84c-4e96-9ec9-cb3b727fe69a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A16%25253A27Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DOVldTW1b3tL9Vtp3u1Ntg8ikTZXvabX%25252FmUfMzzLuZwI%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7cbbe93e02a34fd89a/Loader.classloader/1/console.4edad071.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A16%25253A27Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D4KRLSxy17cvNrmQM9XzCHfUykQIHS4lbfK0ZgWkS%25252F9Q%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7cbbe93e02a34fd89a/Loader.classloader/6f641bef-0378-4041-8573-aff21995ff92.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A16%25253A27Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D4KRLSxy17cvNrmQM9XzCHfUykQIHS4lbfK0ZgWkS%25252F9Q%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1c81883f1a46427091/Loader.classloader/1/console.2cdb3bec.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A25Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DNMTf5t5aBjM5HT7F8Fnrrl1i2XiVzsBu3WKK8y7kQVk%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1c81883f1a46427091/Loader.classloader/1/corerun.exe.2328.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A25Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DNMTf5t5aBjM5HT7F8Fnrrl1i2XiVzsBu3WKK8y7kQVk%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1c81883f1a46427091/Loader.classloader/c4d9b213-70de-4695-b8f0-d64a502dd9f5.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A25Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DNMTf5t5aBjM5HT7F8Fnrrl1i2XiVzsBu3WKK8y7kQVk%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2393637300224724be/Loader.classloader/1/console.a3d2e03c.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A25Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D%25252BCpZL%25252BblzeL%25252BjpmDsiWgUwjEHhz2gVe6YH%25252Fdil5kXFI%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2393637300224724be/Loader.classloader/1/corerun.exe.4912.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A25Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D%25252BCpZL%25252BblzeL%25252BjpmDsiWgUwjEHhz2gVe6YH%25252Fdil5kXFI%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2393637300224724be/Loader.classloader/74cf75f2-4af8-4312-b601-927cea82741f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A25Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D%25252BCpZL%25252BblzeL%25252BjpmDsiWgUwjEHhz2gVe6YH%25252Fdil5kXFI%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-db48f1556b3f458aaa/Loader.classloader/1/console.9ddff3e3.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D2X4YfKOCRRFNNc2GJLJhnYH7RR7GncBMPRlUhAsEq9I%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-db48f1556b3f458aaa/Loader.classloader/bf5e915a-6084-44c7-bb37-ea64792d2f98.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D2X4YfKOCRRFNNc2GJLJhnYH7RR7GncBMPRlUhAsEq9I%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9e4000cadac0485b98/Loader.classloader/1/console.2343d756.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DX6SomND2Fywqe%25252Fxty4sCSm7eEAY9WokgGTP5HpkXQlg%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9e4000cadac0485b98/Loader.classloader/fc6aab58-3dea-49a5-bbdb-694cc3f8e323.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DX6SomND2Fywqe%25252Fxty4sCSm7eEAY9WokgGTP5HpkXQlg%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b79555f546024e37a9/Loader.classloader/1/console.1804eb2a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A16%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DcdbtdfjCFOa9ssY2eELoNjICSQ%25252Fq3g652TkRW5Z75EE%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b79555f546024e37a9/Loader.classloader/1/corerun.exe.2012.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A16%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DcdbtdfjCFOa9ssY2eELoNjICSQ%25252Fq3g652TkRW5Z75EE%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b79555f546024e37a9/Loader.classloader/14ef16b0-4b92-46fe-a726-6f7767f037a2.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A16%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DcdbtdfjCFOa9ssY2eELoNjICSQ%25252Fq3g652TkRW5Z75EE%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cf3231c2fd90462cac/Loader.classloader/1/console.f6e12ab7.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A16%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DQk9TC%25252FJHB8%25252FGIB00au%25252BPU%25252FU80U4XxNWFM6pdOvvyUow%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cf3231c2fd90462cac/Loader.classloader/1/corerun.exe.9184.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A16%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DQk9TC%25252FJHB8%25252FGIB00au%25252BPU%25252FU80U4XxNWFM6pdOvvyUow%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cf3231c2fd90462cac/Loader.classloader/80b306a1-76ff-4769-a7b7-eb46a0c21a1a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A16%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DQk9TC%25252FJHB8%25252FGIB00au%25252BPU%25252FU80U4XxNWFM6pdOvvyUow%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b318fae1565e47a09b/Loader.classloader/1/console.5a783a32.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A17%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dh42L1IiNEM7jd8qJzP6cSxcyrGjs0ISBdfQGfTEKFZ8%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b318fae1565e47a09b/Loader.classloader/825dca5f-6355-4c0a-8db7-2e2787073f15.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A17%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dh42L1IiNEM7jd8qJzP6cSxcyrGjs0ISBdfQGfTEKFZ8%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b212019e646e42ab89/Loader.classloader/1/console.6e61030c.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A17%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D%25252FcKwEYMdjhaTDixdGEsiR1KwQaX2n5uyHXXcPX%25252FmNN0%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b212019e646e42ab89/Loader.classloader/b6046268-332a-43ef-a63f-8cc0239e183a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A17%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D%25252FcKwEYMdjhaTDixdGEsiR1KwQaX2n5uyHXXcPX%25252FmNN0%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|2|2|2|

### LINKED ISSUE #64466: R2R-CrossGen2 failure - loader/classloader/reffields/validate/validate.sh
Runfo Tracking Issue: [R2R-CrossGen2 failure - loader/classloader/reffields/validate/validate.sh](https://runfo.azurewebsites.net/tracking/issue/261)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux x64 Checked @ Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4b3c69c8ee91437fb1/Loader.classloader/1/console.d8245371.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A01%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DMmThVrha%25252F2AZaM2l6gX3YnhSGm6dSA0VlNCg7rqZSBQ%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4b3c69c8ee91437fb1/Loader.classloader/1/core.1000.20356?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A01%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DMmThVrha%25252F2AZaM2l6gX3YnhSGm6dSA0VlNCg7rqZSBQ%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4b3c69c8ee91437fb1/Loader.classloader/be5317c4-8dbe-46f9-99c9-ea61979f0d4a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A01%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DMmThVrha%25252F2AZaM2l6gX3YnhSGm6dSA0VlNCg7rqZSBQ%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-34b23df9c96b419fab/Loader.classloader/1/console.05a9f9f8.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A01%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D2%25252F2Hmx6n2dUbb69SEwDeocpLr2JsitIwXpXtn2uojCI%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-34b23df9c96b419fab/Loader.classloader/1/coredump.32600.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A01%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D2%25252F2Hmx6n2dUbb69SEwDeocpLr2JsitIwXpXtn2uojCI%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-34b23df9c96b419fab/Loader.classloader/41bca077-c809-46f6-b4c3-a406250d08fa.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A01%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D2%25252F2Hmx6n2dUbb69SEwDeocpLr2JsitIwXpXtn2uojCI%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a5f4128e88d84c4999/Loader.classloader/1/console.f083d00f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A02%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D0t6mfPtZCRbEfQDemRRHAoK2JMymY4jqUXTk8vu%25252BqsA%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a5f4128e88d84c4999/Loader.classloader/1/core.1000.8555?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A02%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D0t6mfPtZCRbEfQDemRRHAoK2JMymY4jqUXTk8vu%25252BqsA%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a5f4128e88d84c4999/Loader.classloader/d9aa8747-cebf-45c9-9f02-50f0fc2ccbc1.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A02%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D0t6mfPtZCRbEfQDemRRHAoK2JMymY4jqUXTk8vu%25252BqsA%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bb234d498d39405eb4/Loader.classloader/1/console.0d38932e.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A02%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DBVEt%25252F8Z28rJaWD8EpC2hH3iuhLqjze3AsHg8jk4lMCk%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bb234d498d39405eb4/Loader.classloader/1/core.1000.8424?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A02%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DBVEt%25252F8Z28rJaWD8EpC2hH3iuhLqjze3AsHg8jk4lMCk%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bb234d498d39405eb4/Loader.classloader/1c6286f3-f16c-4550-b1f8-5a6f3c3553a3.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A02%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DBVEt%25252F8Z28rJaWD8EpC2hH3iuhLqjze3AsHg8jk4lMCk%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux arm64 Checked @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f76334588538409686/Loader.classloader/1/console.e9f01452.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A03%25253A10Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DGGiW4lcwnSITloaCwaQkUFvzFDth3anQVlFmnZb4d1M%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f76334588538409686/Loader.classloader/1/coredump.2181.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A03%25253A10Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DGGiW4lcwnSITloaCwaQkUFvzFDth3anQVlFmnZb4d1M%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f76334588538409686/Loader.classloader/bab64c5f-43a2-48ec-8a4e-ca6c4d8a8910.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A03%25253A10Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DGGiW4lcwnSITloaCwaQkUFvzFDth3anQVlFmnZb4d1M%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4296c3b5c28b4d32ad/Loader.classloader/1/console.37055f80.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A03%25253A10Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DJDXN6Aw%25252FgUX9DIw6qkd7DxEP27zKmpApqrTOewAqS%25252Bc%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4296c3b5c28b4d32ad/Loader.classloader/1/coredump.13658.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A03%25253A10Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DJDXN6Aw%25252FgUX9DIw6qkd7DxEP27zKmpApqrTOewAqS%25252Bc%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4296c3b5c28b4d32ad/Loader.classloader/70014b08-ac96-4631-aba2-35933250b28f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A03%25253A10Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DJDXN6Aw%25252FgUX9DIw6qkd7DxEP27zKmpApqrTOewAqS%25252Bc%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 OSX x64 Checked @ OSX.1014.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-66b9b2fd3b3749f0a1/Loader.classloader/1/console.5555b766.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A08%25253A04Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DAx%25252BIRVNgFhrQV624N9BaXXP86J8AS5A0D3xIU8gPP4E%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-66b9b2fd3b3749f0a1/Loader.classloader/1/core.19414?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A08%25253A04Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DAx%25252BIRVNgFhrQV624N9BaXXP86J8AS5A0D3xIU8gPP4E%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-66b9b2fd3b3749f0a1/Loader.classloader/a8691763-fe5c-44d7-b43f-c67909307a1b.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A08%25253A04Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DAx%25252BIRVNgFhrQV624N9BaXXP86J8AS5A0D3xIU8gPP4E%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1014.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bb59831dbb58404090/Loader.classloader/1/console.45c25242.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A08%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DXuz52rWPV3muROzoXbOn4weBpxCuE%25252FezZRiH7quL1aY%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bb59831dbb58404090/Loader.classloader/1/core.18351?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A08%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DXuz52rWPV3muROzoXbOn4weBpxCuE%25252FezZRiH7quL1aY%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bb59831dbb58404090/Loader.classloader/f8b67462-3a5a-44a5-a164-d239bf1188d4.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A08%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DXuz52rWPV3muROzoXbOn4weBpxCuE%25252FezZRiH7quL1aY%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d98a181a1a034b75ad/Loader.classloader/1/console.604b9009.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DM09XHXT7XYUKGGIt8OfrhS%25252FMnPgvpSf15yqbOiJ1DwM%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d98a181a1a034b75ad/Loader.classloader/1/coredump.10481.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DM09XHXT7XYUKGGIt8OfrhS%25252FMnPgvpSf15yqbOiJ1DwM%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d98a181a1a034b75ad/Loader.classloader/1a0390f1-7a90-41be-92bd-ee87f9b4f85a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DM09XHXT7XYUKGGIt8OfrhS%25252FMnPgvpSf15yqbOiJ1DwM%25253D)|
|[1578514](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bad6034114a94da58d/Loader.classloader/1/console.544afddd.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DClTplKFpXK4nFP7w%25252B1JMqg2gunsM7INqkHS20c1ybus%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bad6034114a94da58d/Loader.classloader/1/core.1001.5772?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DClTplKFpXK4nFP7w%25252B1JMqg2gunsM7INqkHS20c1ybus%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bad6034114a94da58d/Loader.classloader/889ff210-94cd-41f3-8d79-de6dd1366cce.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T20%25253A12%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DClTplKFpXK4nFP7w%25252B1JMqg2gunsM7INqkHS20c1ybus%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cee9e64353d0445d8b/Loader.classloader/1/console.3efa1bac.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A56%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DHlgdCojKMpMOIuwP0SBwmG4T5WEN4ce%25252BIniFFiXG3%25252Fs%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cee9e64353d0445d8b/Loader.classloader/1/core.1001.8628?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A56%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DHlgdCojKMpMOIuwP0SBwmG4T5WEN4ce%25252BIniFFiXG3%25252Fs%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cee9e64353d0445d8b/Loader.classloader/6267b54e-7bf6-4ca9-9f5b-6b6078673079.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A56%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DHlgdCojKMpMOIuwP0SBwmG4T5WEN4ce%25252BIniFFiXG3%25252Fs%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-14bab4e2603e496da6/Loader.classloader/1/console.c95e49aa.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A56%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253De%25252F0uTNQEEB4trwI1ucjefoByWAZQzEspYDi2KYbrFtk%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-14bab4e2603e496da6/Loader.classloader/1/core.1001.5653?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A56%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253De%25252F0uTNQEEB4trwI1ucjefoByWAZQzEspYDi2KYbrFtk%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-14bab4e2603e496da6/Loader.classloader/3b87662c-bd7a-4634-a6cf-9afe88228c3a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A56%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253De%25252F0uTNQEEB4trwI1ucjefoByWAZQzEspYDi2KYbrFtk%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux arm64 Checked @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-eaa830e4e3f24b8382/Loader.classloader/1/console.1562ebc4.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A58%25253A42Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DT%25252Bhbw5C5wlcE9zU61cqXv%25252BR6i2mkgnDhUGEyDPzZjJQ%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-eaa830e4e3f24b8382/Loader.classloader/1/coredump.5942.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A58%25253A42Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DT%25252Bhbw5C5wlcE9zU61cqXv%25252BR6i2mkgnDhUGEyDPzZjJQ%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-eaa830e4e3f24b8382/Loader.classloader/d9c3150f-94e9-4775-ac83-76bf13a231be.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A58%25253A42Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DT%25252Bhbw5C5wlcE9zU61cqXv%25252BR6i2mkgnDhUGEyDPzZjJQ%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-18703f14b2c2469a95/Loader.classloader/1/console.9337cdf1.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A58%25253A42Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Da5CG1vWB1fetQLHtbP6Ta1uLHj5U6QjxkQAQWu%25252F4Ot0%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-18703f14b2c2469a95/Loader.classloader/1/coredump.11481.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A58%25253A42Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Da5CG1vWB1fetQLHtbP6Ta1uLHj5U6QjxkQAQWu%25252F4Ot0%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-18703f14b2c2469a95/Loader.classloader/3be2acb3-b046-45b1-a065-d6197fca4fb9.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A58%25253A42Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Da5CG1vWB1fetQLHtbP6Ta1uLHj5U6QjxkQAQWu%25252F4Ot0%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f217f080067749d4a3/Loader.classloader/1/console.30e793d9.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoeEaT%25252BxvTVCTkHz5Li9VoUJvIs3K1vftXiWApBbzuJA%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f217f080067749d4a3/Loader.classloader/1/core.1000.10027?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoeEaT%25252BxvTVCTkHz5Li9VoUJvIs3K1vftXiWApBbzuJA%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f217f080067749d4a3/Loader.classloader/8f159f38-3ba0-462c-8b2b-b0e8acd21dae.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoeEaT%25252BxvTVCTkHz5Li9VoUJvIs3K1vftXiWApBbzuJA%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1b2a621e0bfb43c391/Loader.classloader/1/console.8e4cdc41.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DY%25252FCzn552P5q%25252FsOs8M5tVuaXkjNp7YMBoMsTVkmrCP3s%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1b2a621e0bfb43c391/Loader.classloader/1/coredump.4696.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DY%25252FCzn552P5q%25252FsOs8M5tVuaXkjNp7YMBoMsTVkmrCP3s%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1b2a621e0bfb43c391/Loader.classloader/6edcfcf0-927e-494f-89e0-1ae320852c21.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DY%25252FCzn552P5q%25252FsOs8M5tVuaXkjNp7YMBoMsTVkmrCP3s%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux x64 Checked @ Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d7ccf87d3ee94e1885/Loader.classloader/1/console.958fc331.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D1RbPjj8CJClL8IOUVQCCrYcz6nSiS0UrtzrLFE%25252B2E7s%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d7ccf87d3ee94e1885/Loader.classloader/1/coredump.24334.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D1RbPjj8CJClL8IOUVQCCrYcz6nSiS0UrtzrLFE%25252B2E7s%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d7ccf87d3ee94e1885/Loader.classloader/72867e11-284b-4f33-9fdf-ba132291c01b.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D1RbPjj8CJClL8IOUVQCCrYcz6nSiS0UrtzrLFE%25252B2E7s%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-64ce2f124a82405680/Loader.classloader/1/console.bf620a8a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DlpLe%25252B%25252FQ5cPaRbeJ8FxzIYmAadrLv017IIxwaHLacBtU%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-64ce2f124a82405680/Loader.classloader/1/coredump.11419.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DlpLe%25252B%25252FQ5cPaRbeJ8FxzIYmAadrLv017IIxwaHLacBtU%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-64ce2f124a82405680/Loader.classloader/b07a54b6-4e92-4376-b30b-7a5dd6988468.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T10%25253A59%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DlpLe%25252B%25252FQ5cPaRbeJ8FxzIYmAadrLv017IIxwaHLacBtU%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 OSX x64 Checked @ OSX.1014.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0a17e474701441bab0/Loader.classloader/1/console.39464603.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoCP0rIfYMdKULvlNCmgYabXSIk8YGu61rWG%25252FfOeFHzw%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0a17e474701441bab0/Loader.classloader/1/core.89924?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoCP0rIfYMdKULvlNCmgYabXSIk8YGu61rWG%25252FfOeFHzw%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0a17e474701441bab0/Loader.classloader/a444670f-1705-4f1a-be75-7b2f3e75ace5.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoCP0rIfYMdKULvlNCmgYabXSIk8YGu61rWG%25252FfOeFHzw%25253D)|
|[1577796](https://dev.azure.com/dnceng/public/_build/results?buildId=1577796)|[runtime-coreclr outerloop](https://dnceng.visualstudio.com/public/_build?definitionId=655)|Rolling|R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1014.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0ea28158e7764794a2/Loader.classloader/1/console.63963859.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DeqlJk6Yw%25252FL5h38eggdhc8WKdUd%25252Bsjiork5zCLgrhhnY%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0ea28158e7764794a2/Loader.classloader/1/core.53505?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DeqlJk6Yw%25252FL5h38eggdhc8WKdUd%25252Bsjiork5zCLgrhhnY%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0ea28158e7764794a2/Loader.classloader/ab728b7c-7d45-4168-9252-2ec6520d5e4c.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-17T11%25253A09%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DeqlJk6Yw%25252FL5h38eggdhc8WKdUd%25252Bsjiork5zCLgrhhnY%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|2|2|2|

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Update tests to use recursion and validate GCStress scenarios.

Related NativeAOT/CrossGen2 change - https://github.com/dotnet/runtime/pull/64366

Fixes https://github.com/dotnet/runtime/issues/64465
Fixes https://github.com/dotnet/runtime/issues/64466

/cc @MichalStrehovsky @dotnet/interop-contrib

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Tangentially related to the topic of GC holes, is there a similar problem in `FindByRefPointerOffsetsInByRefLikeObject`? That one is used in stack walking. Not sure how to hit that one... might be something along the lines of an interface call that takes a struct with `ref` fields as a parameter? It might be a good strategy to search for all occurrences of `g_pByReferenceClass`.

Found that one by accident when I wanted to point you to https://github.com/dotnet/runtime/issues/12842 (that we should also do for byref fields due to GC tracking).

Sorry for dumping tangentially related stuff on this pull request - it should have probably gone to #63985.

**Comment by AaronRobinsonMSFT** [comment]
> Tangentially related to the topic of GC holes, is there a similar problem in FindByRefPointerOffsetsInByRefLikeObject?
> It might be a good strategy to search for all occurrences of g_pByReferenceClass.

@MichalStrehovsky That is exactly what I've been doing for the past 40 minutes. I agree there are some issues here. Based on my searching, I think `FindByRefPointerOffsetsInByRefLikeObject` is the only other thing that needs to be changed. I was going to defer until we remove `ByReference<T>` but since you brought it up, I will apply the fixes to the other places.

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -2029,54 +2029,54 @@ bool CEEInfo::checkMethodModifier(CORINFO_METHOD_HANDLE hMethod,
...
             MethodTable * pFieldMT = pFD->GetApproxFieldTypeHandleThrowing().AsMethodTable();
             result += ComputeGCLayout(pFieldMT, gcPtrs + fieldStartIndex);
         }
+        else if (pFD->IsObjRef())
+        {
+            result += MarkGCField(gcPtrs + fieldStartIndex, TYPE_GC_REF);
+        }
+        else if (pFD->IsByRef())
+        {
+            result += MarkGCField(gcPtrs + fieldStartIndex, TYPE_GC_BYREF);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/jitinterface.cpp:2078]: We could assert the field offset is `pFD->GetOffset() % TARGET_POINTER_SIZE == 0`? I could also update the type loader during field layout if that is of interest instead.

Related https://github.com/dotnet/runtime/issues/12842

/cc @jkotas

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/jitinterface.cpp:2078]: I reread issue #12842 and realized the unaligned field on a pointer offset issue was already handled by @MichalStrehovsky. This means the outstanding issue - pointer aligned field overlap of a byref-like with a non-byref-like field.  This is handled in the PR at with the `MarkGCField()` helper.

**Review by jkotas — APPROVED** [review]
LGTM

**Comment by AaronRobinsonMSFT** [comment]
@MichalStrehovsky I am checking this in now since it is impacting the outer loop tests. Please still give it a once over in case there is something else I'm not considering.

**Comment by MichalStrehovsky** [comment]
Looks good! I filed #64520 for one of the tangentially related issues.

File: src/coreclr/vm/jitinterface.cpp (hunk 1 above)
Comment (MichalStrehovsky) [reply src/coreclr/vm/jitinterface.cpp:2078]: Came back to this comment as I'm deleting github notifications.

#25200 made sure type load of `[FieldOffset(SomeNonPointerValue)] ByRefLikeType _field` won't load, but we need to make sure `[FieldOffset(SomeNonPointerValue)] ref SomeType _field` won't load either - #64520 will track we do that/have test coverage.
