### PR TITLE
Fix paltest_pal_sxs_test1 on illumos

### LINKED ISSUE #35362: paltest_pal_sxs_test1 failed on SmartOS x64
The following condition is failing on SmartOS x64: https://github.com/dotnet/runtime/blob/0fbd88e4bd00b5f5218a20468e617b3d79d10a1d/src/coreclr/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest2.cpp#L65-L67

Based on the discussion in https://github.com/dotnet/runtime/issues/5158, I have captured the backtraces and printed the value of `ex.GetExceptionRecord()->ExceptionInformation[1]`, which is different in every run, but never the expected `0x22`: https://gist.github.com/am11/0bef90cabb1185d41a93c456e9083b4d.

cc @janvorli, if i try to comment this FAIL line it throws SIGABRT after few lines.

### PR DESCRIPTION
**Pull request by AustinWise**
These changes taken together make `paltest_pal_sxs_test1` pass. Along the way it also fixes building the rootfs for illumos. Each commit description contains details about the changes; here is a summary:

* Disable alternate stacks for signal handlers. illumos has limitations on the use of alternate stacks in signal handlers that .NET is incompatible with.
* Define the RPATH for the `paltest_pal_sxs_test1` executable so that it can find the dynamic libraries used in the test.

### Tested on:

I did the testing using the updated cross rootfs from dotnet/arcade#14978.

* OpenIndiana Hipster 2024.04 - Global Zone
* OpenIndiana Hipster 2024.04 - ipkg zone
* SmartOS 20240701T205528Z - base-64-lts 23.4.0 zone

Fixes #35362

### CODE REVIEW

**Comment by gwr** [comment]
> I am not sure what is the best way to disable alternate stacks for signal handlers. Possibilities include:
[...]
> * detect whether sigaltstack works as expected on startup.
> 
> The last two might be handy for cases where other platforms or emulators have the same problem with alternate stacks as illumos. The specific case I'm thinking of is the Linux emulation support included in some distributions of illumos. It has the same problem last I checked.

Could you please open a bug at illumos.org/issues for the sigaltstack problem?
You're probably in a better position to describe what's wrong, what should happen,
and (hopefully) provide a simple test that demonstrates the problem.  Thanks!

File: eng/common/cross/build-rootfs.sh
Comment (am11) [inline eng/common/cross/build-rootfs.sh:1]: Changes in `eng/common` should be submitted upstream in dodnet/arcade (otherwise, next sync will overwrite this file losing your changes)

File: src/coreclr/pal/src/exception/signal.cpp [hunk 1]
```diff
@@ -190,13 +190,20 @@ BOOL SEHInitializeSignals(CorUnix::CPalThread *pthrCurrent, DWORD flags)
         handle_signal(SIGSEGV, sigsegv_handler, &g_previous_sigsegv);
 #else
         handle_signal(SIGTRAP, sigtrap_handler, &g_previous_sigtrap);
+        int additionalFlagsForSigSegv = 0;
+#ifndef __sun
```
Comment (am11) [inline src/coreclr/pal/src/exception/signal.cpp:194]: nit: `HOST_SUNOS` (here and other places) which is a prevalent pattern in this file.

**Comment by gwr** [comment]
Looks like this should fix #35362 -- right?  I didn't see a reference to that issue here.

File: eng/native/configurecompiler.cmake [hunk 2]
```diff
@@ -434,6 +434,7 @@ if (CLR_CMAKE_HOST_UNIX)
   elseif(CLR_CMAKE_HOST_NETBSD)
     message("Detected NetBSD amd64")
   elseif(CLR_CMAKE_HOST_SUNOS)
+    add_definitions(-DHOST_SUNOS)
```
Comment (am11) [inline eng/native/configurecompiler.cmake:437]: I think we should just use `TARGET_SUNOS` and not define this. When mapping `host,build,target` unix-y concepts on `host,target`, target is what we actually want 99% of the time, which is why Linux and FreeBSD are still not requiring its definition and those ports are completed since many releases.

Comment (am11) [reply eng/native/configurecompiler.cmake]: Yup, HOST_ is mostly used for DAC like stuff or previously in old crossgen1 type of components.
In mono, the logic is more unix-y, host+build is HOST, so it's a fusion between unix-y and windows style, this explains unix-y terminologies: https://stackoverflow.com/a/78396726/863980.

**Comment by am11** [comment]
> This fixes this test for FreeBSD as well.

Awesome! @Thefrank, another happy news for you. ;)

**Review by gwr — APPROVED** [review]
LGTM.  Thanks.

**Comment by Thefrank** [comment]
Confirming this resolves the test failure on FreeBSD as well! Thank you!
```
Finished running PAL tests.

PAL Test Results:
  Passed: 337
  Failed: 0

Copied PAL test output files to /root/runtime/artifacts/bin/coreclr/freebsd.x64.Debug/paltestsoutputs.
```

**Comment by gwr** [comment]
Got a helpful response on the illumos issue.  If I understand correctly, what dotnet is doing today with contexts and sigaltstack is highly system-dependent (non-portable).  I wonder if it might be possible to let dotnet have what it needs using only getcontext/setcontext etc? (basically adhere to the interface descriptions pointed to in the comments on that illumos bug.). I assume that would be a fair bit of work.

**Comment by janvorli** [comment]
@AustinWise thank you for looking into the alternate stack vs return from signal handler issue. I've hit the same thing in the past when I was considering moving macOS to handle hardware exceptions via signals to unify it with other Unix platforms. macOS also keeps track of the alt stack and when we don't return from the handler and redirect execution instead, next time we hit a hardware exception, it calls the handler on the original stack. 
I think it would make sense to try to move to the way you've tried in your proof of context. I've actually tried that with macOS in the past too, but I ended up not making the change. It was about 2-3 years ago, so I don't remember all the details. I have a feeling that I've hit some subtle problem that made me stop trying to finalize it at that time, but I don't remember the details anymore. So it seems to be worth revisiting to make it cleaner,
Based on what I've just said, I would prefer making this PR smaller - just by not passing the `SA_ONSTACK` to the `handle_signal` and returning `false` from `IsRunningOnAlternateStack` for illumos and keeping everything else unchanged (besides the PAL test, of course).

**Review by janvorli — APPROVED** [review]
LGTM thank you!

**Comment by gwr** [comment]
> > Got a helpful response on the illumos issue. If I understand correctly, what dotnet is doing today with contexts and sigaltstack is highly system-dependent (non-portable). I wonder if it might be possible to let dotnet have what it needs using only getcontext/setcontext etc? (basically adhere to the interface descriptions pointed to in the comments on that illumos bug.). I assume that would be a fair bit of work.
> 
> One of the options Joshua mentioned:
> [ modifying ... the existing ucontext_t in place, and then return from the signal handler. ]
> 
> As an existence proof that this is possible for .NET, NativeAOT takes this approach:
> 
> https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/Runtime/unix/HardwareExceptions.cpp#L508
> 
> CoreCLR currently is in a transition phase where it supports its original exception dispatch code and a new model based on NativeAOT's system (see references to `g_isNewExceptionHandlingEnabled`). I think if we want to change the CoreCLR exception dispatcher to always return from the signal handler, it would be easier to make this change once the old exception handling system has been removed.

If the runtime is "just trying to unwind" to some deeper frame on the stack, then it should be possible to use getcontext (at the deeper frame to which we might unwind) and then in the exception handler, call setcontext to restore that context. That too does the OS-specific stuff about altstacks that returning from a signal handler does.  Is "just trying to unwind" an accurate summary of what the runtime is doing?  That was not clear to me after a quick look at the code.

Should we have a separate issue for possibly improving the runtime exception handling?
I'd rather that not block this work-around, even if we plan to improve it later.

**Comment by janvorli** [comment]
> Should we have a separate issue for possibly improving the runtime exception handling?

Yes, we should. I've created it here: https://github.com/dotnet/runtime/issues/106645

> If the runtime is "just trying to unwind" to some deeper frame on the stack, then it should be possible to use getcontext (at the deeper frame to which we might unwind) and then in the exception handler, call setcontext to restore that context.

The SIGSEGV handler allows .NET runtime to handle NullReferenceException that can occur at any arbitrary location in the code that our JIT produces (and also in a few handwritten assembler helpers). The exception handling code walks the stack until it finds a frame that handles the exception (it has a catch handler for it). Then it calls that catch handler and after it returns, it restores context to the code location after the catch handler to continue normal execution. It is also possible that the catch handler never returns, because it ends up throwing some exception again (could be any software / hardware exception).

So we cannot reasonably use the getcontext as we would essentially have to call it before every call (as we don't know which method can end up throwing an exception). And even if we could, it would add unnecessary and non-trivial overhead to the non-exceptional code execution. I believe that returning from the signal handler with instruction pointer in the context modified to point to a helper function that then invokes the exception handling code is the right thing to do here. It will actually be a bit more involved so that the failing frame is still visible on the stack when running the exception handling code.
