### PR TITLE
fix failing revocation & ssl tests

### LINKED ISSUE #38744: Test failure: System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
failed in job: [runtime-libraries outerloop 20200702.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=714372&view=ms.vss-test-web.build-test-results-tab&runId=22141816&resultId=103132&paneView=debug)

Error message
~~~
Assert.Equal() Failure
Expected: X509ChainStatusFlags[] [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked | NotValidForUsage]
Actual: X509ChainStatusFlags[] [NoError, NoError, NotTimeValid | Revoked]


Stack trace
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1247
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass17_0.<RevokeEndEntity_PolicyErrors_NotTimeValid>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 602
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.SimpleTest(PkiOptions pkiOptions, RunSimpleTest callback, String callerName, Boolean pkiOptionsInTestName) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1218
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(Boolean policyErrors, Boolean notTimeValid) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 564
~~~

### LINKED ISSUE #38805: Test failure： System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UntrustedCaWithCustomCallback_OK
failed in job: [runtime 20200704.19 ](https://dev.azure.com/dnceng/public/_build/results?buildId=716691&view=ms.vss-test-web.build-test-results-tab&runId=22209938&resultId=135760&paneView=debug)

failed tests:
System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UntrustedCaWithCustomCallback_OK
System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UntrustedCaWithCustomCallback_Throws

Error message
~~~
System.AggregateException : One or more errors occurred. (One or more errors occurred. (Authentication failed, see inner exception.)) (One or more errors occurred. (Authentication failed, see inner exception.))
---- System.AggregateException : One or more errors occurred. (Authentication failed, see inner exception.)
-------- System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
------------ Interop+OpenSsl+SslException : SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
---------------- Interop+Crypto+OpenSslCryptographicException : error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
---- System.AggregateException : One or more errors occurred. (Authentication failed, see inner exception.)
-------- System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
------------ Interop+OpenSsl+SslException : Using SSL certificate failed with OpenSSL error - ee key too small.


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 109
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UntrustedCaWithCustomCallback_OK() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamNetworkStreamTest.cs:line 299
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__171`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext() in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 317
----- Inner Stack Trace -----
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount) in /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 291
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 115
----- Inner Stack Trace -----

----- Inner Stack Trace #2 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__171`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext() in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 317
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
----- Inner Stack Trace -----
   at Interop.OpenSsl.SetSslCertificate(SafeSslContextHandle contextPtr, SafeX509Handle certPtr, SafeEvpPKeyHandle keyPtr) in /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 583
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions) in /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 155
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions) in /_/src/libraries/Common/src/System/Net/Security/Unix/SafeDeleteSslContext.cs:line 48
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 112
~~~

### PR DESCRIPTION
**Pull request by wfurt**
fix tests broken by #38182. 
This adds fork for Ssl server leaving revocation tests as before.
It adds keySize parameter to avoid failures on Debian 10 (requiring stronger crypto)

fixes  #38805
fixes #38744

### CODE REVIEW

File: src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs [hunk 1]
```diff
@@ -929,10 +944,14 @@ private enum CertStatus
...
                 }
 
-                endEntityCert = intermediateAuthority.CreateEndEntity(
-                    BuildSubject(subjectName ?? "A Revocation Test Cert", testName, pkiOptions, pkiOptionsInSubject),
-                    eeKey,
-                    altName);
+                endEntityCert = endEntityIsServer ?
+                    intermediateAuthority.CreateServerEndEntity(
+                        BuildSubject(subjectName ?? "A Revocation Test Cert", testName, pkiOptions, pkiOptionsInSubject),
+                        eeKey, altName) :
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs:950]:
```suggestion
                        eeKey,
                        altName) :
```

File: src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs [hunk 2]
```diff
@@ -929,10 +944,14 @@ private enum CertStatus
...
+                    intermediateAuthority.CreateEndEntity(
+                        BuildSubject(subjectName ?? "A Revocation Test Cert", testName, pkiOptions, pkiOptionsInSubject),
+                        eeKey, altName);
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs:953]:
```suggestion
                        eeKey,
                        altName);
```

File: src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs [hunk 3]
```diff
@@ -929,10 +944,14 @@ private enum CertStatus
                     altName = builder.Build();
                 }
 
-                endEntityCert = intermediateAuthority.CreateEndEntity(
-                    BuildSubject(subjectName ?? "A Revocation Test Cert", testName, pkiOptions, pkiOptionsInSubject),
-                    eeKey,
-                    altName);
+                endEntityCert = endEntityIsServer ?
+                    intermediateAuthority.CreateServerEndEntity(
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs:948]: Really this feels like it should just take an OidCollection or Oid or string, rather than using a bit in the PkiOptions.

Comment (wfurt) [reply src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs:948]: I was thinking about adding bool to BuildPrivatePki() but OidCollection seems like better option. I think more variations are yet to come.

**Comment by wfurt** [comment]
I added collection and moved altName to SslStream helper. I think that will give us more flexibility to also add IPs if we need to.

**Review by bartonjs — APPROVED** [review]

**Comment by bartonjs** [comment]
Yay for code reuse.  Thanks, @wfurt.
