### PR TITLE
Arm64/Sve: Remove unwanted insScalableOpts and instructions

### LINKED ISSUE #103606: Arm64/Sve: AV in GatherLoad* APIs
`Sve_GatherVector_Bases_double_ulong` is failing for me with below call stack:

```
>	clrjit_universal_arm64_x64.dll!Compiler::fgValueNumberAddExceptionSetForIndirection(GenTree * tree, GenTree * baseAddr) Line 13618	C++
 	clrjit_universal_arm64_x64.dll!Compiler::fgValueNumberHWIntrinsic(GenTreeHWIntrinsic * tree) Line 12461	C++
 	clrjit_universal_arm64_x64.dll!Compiler::fgValueNumberTree(GenTree * tree) Line 12056	C++
 	clrjit_universal_arm64_x64.dll!Compiler::fgValueNumberBlock(BasicBlock * blk) Line 10554	C++
 	clrjit_universal_arm64_x64.dll!Compiler::fgValueNumber() Line 10340	C++
 	clrjit_universal_arm64_x64.dll!CompilerPhaseWithStatus::DoPhase() Line 132	C++
```

https://github.com/dotnet/runtime/blob/a0b8890f989d2d4b37507b99d94249506f161d6f/src/coreclr/jit/valuenum.cpp#L13618

### PR DESCRIPTION
**Pull request by kunalspathak**
Now that we have separate predicate and vector registers, remove all the unnecessary `insScalableOpts` entries and fix some unit tests.  Also included a fix for `GatherVector*` which currently AVs.

They are all passing: https://gist.github.com/kunalspathak/797640e95a3f3edfd67ef107c19389ae
Also ran the unit tests and they are all working.

Fixes: https://github.com/dotnet/runtime/issues/103606

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/arm64-contrib @TIHan @amanasifkhalid PTAL

File: src/coreclr/jit/emitarm64.cpp [hunk 1]
```diff
@@ -4252,9 +4252,15 @@ void emitter::emitIns_Mov(
         {
             if (isPredicateRegister(dstReg) && isPredicateRegister(srcReg))
             {
-                assert(insOptsNone(opt));
+                if (insOptsNone(opt))
```
Comment (a74nh) [inline src/coreclr/jit/emitarm64.cpp:4255]: This code is odd. This is because for predicates we always use INS_OPTS_SCALABLE_B for a mov, so the passed in `opt` value doesn't matter ?

File: src/coreclr/jit/emitarm64sve.cpp [hunk 2]
```diff
@@ -1926,22 +1926,17 @@ void emitter::emitInsSve_R_R(instruction     ins,
                 assert(insOptsScalableStandard(opt));
                 return emitInsSve_R_R_I(INS_sve_pmov, attr, reg1, reg2, 0, opt, sopt);
             }
-            if (sopt == INS_SCALABLE_OPTS_TO_PREDICATE)
```
Comment (a74nh) [inline src/coreclr/jit/emitarm64sve.cpp:1929]: Are there any functions we can remove `sopt` completely?

File: src/coreclr/jit/gentree.cpp [hunk 3]
```diff
@@ -27525,11 +27525,11 @@ bool GenTreeHWIntrinsic::OperIsMemoryLoad(GenTree** pAddr) const
...
                 addr = Op(2);
-                if (varTypeIsSIMD(addr->gtType))
+                if (!varTypeIsI(addr))
                 {
-                    // The address is a vector of addresses.
-                    // Return true, but do not set pAddr.
-                    return true;
+                    // For some variants, the address is in vector.
+                    // Return false for such cases.
+                    return false;
```
Comment (a74nh) [inline src/coreclr/jit/gentree.cpp:27532]: I was returning `true` here because I assumed we needed to track the fact there were addresses in `Op2`. Is it safe to not track that?

File: src/coreclr/jit/emitarm64.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/emitarm64.cpp:4255]: Yes, so basically, this code operates just on `INS_OPTS_SCALABLE_B` (and we added single test for that). For other places, if we have to pass `INS_OPTS_SCALABLE_B` if register types are predicate feels like an overhead, so instead this code expects it to be NONE, in which case it will set the options to `INS_OPTS_SCALABLE_B`.

File: src/coreclr/jit/gentree.cpp (hunk 3 above)
Comment (kunalspathak) [reply src/coreclr/jit/gentree.cpp]: Re-reading, the `OperIsMemoryLoad()` contract is to return true if this intrinsic may throw `NullReferenceException` of address is "null". Now, for certain non-faulting intrinsics, it should return `false`, but for `Gather*`, this should return `true`. 
Fixed it.

File: src/coreclr/jit/emitarm64.cpp (hunk 1 above)
Comment (amanasifkhalid) [reply src/coreclr/jit/emitarm64.cpp:4255]: Would something like this work?
```
if (!insOptsNone(opt))
{
    assert(opt == INS_OPTS_SCALABLE_B);
}

opt = INS_OPTS_SCALABLE_B;
```

I think that shape makes it clearer the if-statement is debug-only code, and ensures `opt` is always `INS_OPTS_SCALABLE_B` even if we don't have asserts on to catch improper handling.

File: src/coreclr/jit/gentree.cpp (hunk 3 above)
Comment (a74nh) [reply src/coreclr/jit/gentree.cpp]: > the OperIsMemoryLoad() contract is to return true if this intrinsic may throw NullReferenceException of address is "null".

That was the part I wasn't sure of.
Happy with the new version.

File: src/coreclr/jit/emitarm64.cpp (hunk 1 above)
Comment (a74nh) [reply src/coreclr/jit/emitarm64.cpp:4255]:
```
assert(opt == INS_OPTS_SCALABLE_B || insOptsNone(opt));
opt = INS_OPTS_SCALABLE_B;
```
?

File: src/coreclr/jit/emitarm64sve.cpp (hunk 2 above)
Comment (amanasifkhalid) [reply src/coreclr/jit/emitarm64sve.cpp:1929]: I think Alan means are there any `emitInsSve_*` methods that no longer need the `sopt` parameter, because it's only checking that `sopt` is `INS_SCALABLE_OPTS_NONE`? `emitInsSve_R_R` seems close to that, though we still check `sopt` with `insScalableOptsWithVectorLength` at the end of the method.

**Review by amanasifkhalid — APPROVED** [review]
LGTM, thanks!

File: src/coreclr/jit/emitarm64sve.cpp (hunk 2 above)
Comment (kunalspathak) [reply src/coreclr/jit/emitarm64sve.cpp:1929]: Ah ok. Thanks @amanasifkhalid for clarifying. I didn't check, but can do it as a follow-up work.
