### PR TITLE
JIT: Discard simple dominated CSEs that will never be defs

### LINKED ISSUE #98413: JIT: CSE for passthrough nodes CQ issue
Minimal repo (on Main):
```cs
class Program
{
    static void Main()
    {
        object o = new();
        Test(ref o);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]  
    static void Test(ref object o)
    {
        for (int i = 0; i < 1000; i++)
            _ = (Program)o;
    }
}
```
Codegen for `Test`:
```asm
; Method Program:Foo(byref) (FullOpts)
       push     rsi
       push     rbx
       sub      rsp, 40
       xor      ebx, ebx
       mov      rsi, gword ptr [rcx]
       mov      rdx, rsi
       mov      rcx, rdx
       test     rcx, rcx
       je       SHORT G_M7833_IG05
       mov      rax, 0x7FF9BEC50F48      ; Program
       cmp      qword ptr [rcx], rax
       je       SHORT G_M7833_IG05
       mov      rcx, rax
       call     CORINFO_HELP_CHKCASTCLASS_SPECIAL ;; hoisted copy

       ;; LOOP START
G_M7833_IG05:
       mov      rdx, rsi
       test     rdx, rdx
       je       SHORT G_M7833_IG08
       mov      rcx, 0x7FF9BEC50F48      ; Program
       cmp      qword ptr [rdx], rcx
       je       SHORT G_M7833_IG08
       mov      rdx, rsi
       call     CORINFO_HELP_CHKCASTCLASS_SPECIAL ;; CSE didn't pick this up
G_M7833_IG08:
       inc      ebx
       cmp      ebx, 0x3E8
       jl       SHORT G_M7833_IG05
       ;; LOOP END

       add      rsp, 40
       pop      rbx
       pop      rsi
       ret      
; Total bytes of code: 93
```
So, loop hoister hoisted the invariant cast, but then CSE struggled to pick it up. My understanding that the root cause here is that castclass has the same VN as its argument (+ exception set) and CSE doesn't work well in such cases.

### PR DESCRIPTION
**Pull request by jakobbotsch**
Be a bit smarter when indexing CSEs if we see the same value twice in the same basic block and the second one has more exceptions than the first one. In that case the first will never be a candidate def for the second, so it is always better to just consider the second one to be the def.

This is particularly relevant with passthrough nodes like `CASTCLASS(x, y)`, where `CASTCLASS` gets the same VN as its first operand, but with more exceptions on it. Previously we would consider `x` to be the def; this naturally considers the full `CASTCLASS(x, y)` to be the def, which promises more exceptions.

One thing to note is that `GT_COMMA` would benefit from this handling too, but it is already special cased such that we create a separate candidate for the `GT_COMMA` (that includes the exception set of `op1`) and its op2 (that doesn't). That would also be a potential way to improve the situation here, but it requires special casing all such cases.

The fix here is very simplistic and doesn't handle many cases. In particular we could have seen `x` previously in another basic block, in which case we run into the same issue again. I think switching CSE to be dominator tree based and generating multiple candidates instead would be a better general solution; hopefully we can work towards that. If not, this at least alleviates some of the problem.

Fix #98413

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS @EgorBo 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=566200&view=ms.vss-build-web.run-extensions-tab).

**Review by EgorBo — APPROVED** [review]
LGTM, I had a more ugly fix for this. I expect this to have bigger impact with the changes I plan for casts in future.

**Comment by BruceForstall** [comment]
I remember loop cloning having a similar issue where hot and cold loop CSEs had different exception sets so CSE bailed entirely.

Could there be completely separate CSEs for same VN but different exception sets?

**Comment by AndyAyersMS** [comment]
> I remember loop cloning having a similar issue where hot and cold loop CSEs had different exception sets so CSE bailed entirely.
> 
> Could there be completely separate CSEs for same VN but different exception sets?

Not so easy to do with the current setup, as it does not know which defs reach which uses, and/or can't decide to turn a use into a def and split up a candidate that way (roughly: it forms candidate sets first, then uses simple dataflow on candidate IDs to mark as defs/uses).

I have a prototype implementation of CSE location that can be much more flexible, but it needs some work. And I expect perhaps we'll need the ML stuff to figure out when splitting / merging pays off, as the combinatorics start to get crazy.

**Comment by AndyAyersMS** [comment]
> I have a prototype implementation of CSE location that can be much more flexible, but it needs some work.

Have put this up as a draft PR, in case you're curious: https://github.com/dotnet/runtime/pull/98467. It will likely have high TP impact and some interesting diffs.

File: src/coreclr/jit/optcse.cpp [hunk 1]
```diff
@@ -609,10 +609,42 @@ unsigned Compiler::optValnumCSE_Index(GenTree* tree, Statement* stmt)
...
+                {
+                    GenTree* prevTree  = hashDsc->csdTree;
+                    ValueNum prevVnLib = prevTree->GetVN(VNK_Liberal);
+                    if (prevVnLib != vnLib)
+                    {
+                        ValueNum prevExceptionSet = vnStore->VNExceptionSet(prevVnLib);
+                        ValueNum curExceptionSet  = vnStore->VNExceptionSet(vnLib);
+                        if ((prevExceptionSet != curExceptionSet) &&
+                            vnStore->VNExcIsSubset(curExceptionSet, prevExceptionSet))
+                        {
```
Comment (AndyAyersMS) [inline src/coreclr/jit/optcse.cpp:638]: It would be nice to JITDUMP here to call out that we're dropping a possible candidate out of CSEness.

I can add that at some point, since I'm also messing with CSE.

**Review by AndyAyersMS — APPROVED** [review]

File: src/coreclr/jit/optcse.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/optcse.cpp:638]: Added it.
