### PR TITLE
don't dispose client control stream before closing connection

### LINKED ISSUE #57021: [HTTP/3] Client closing control stream before closing connection
Justification for 6.0: Violation of HTTP/3 spec -- leading to error on the server side (which can be in theory ignored, but will be confusing for people adopting and experimenting with HTTP/3, lowering their confidence).

HttpClient is closing its outbound control stream before closing the connection. This is causing an `H3_CLOSED_CRITICAL_STREAM` error to be raised in Kestrel. There will be a race between that connection error, and `H3_NO_ERROR` error from the client closing the connection.

Spec says this stream must not be closed - https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-6.2.1-2. I believe the right behavior is to leave it open and allow it to be aborted with `H3_NO_ERROR` when the connection closes.

Kestrel logs:
```
    | [0.385s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Disposing client.
    | [0.386s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Waiting for server to receive connection close.
    | [0.396s] Microsoft.AspNetCore.Server.Kestrel.Http3 Debug: Connection id "0HMAPBN35QRHQ": HTTP/3 connection error.
    | Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3ConnectionErrorException: HTTP/3 connection error (H3_CLOSED_CRITICAL_STREAM): The client closed the connection control stream inbound to the server.
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3ControlStream.HandleControlStream() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http3\Http3ControlStream.cs:line 238
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3ControlStream.ProcessRequestAsync[TContext](IHttpApplication`1 application) in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http3\Http3ControlStream.cs:line 171
    | [0.398s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HMAPBN35QRHQ" aborted by peer with error code 256.
    | System.Net.Quic.QuicConnectionAbortedException: Connection aborted by peer (256).
    |    at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.AcceptStreamAsync(CancellationToken cancellationToken)
    |    at System.Net.Quic.QuicConnection.AcceptStreamAsync(CancellationToken cancellationToken)
    |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicConnectionContext.cs:line 96
```

### PR DESCRIPTION
**Pull request by geoffkizer**
Fixes #57021 

Don't dispose the client control stream until after the connection has been successfully closed, as per RFC.

Also, add some basic handling and validation in the loopback server for the client control stream.

Update mock provider to better handle connection errors so that the above validation works for the mock provider.

### CODE REVIEW

File: src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs [hunk 1]
```diff
@@ -44,21 +50,26 @@ public Http3LoopbackConnection(QuicConnection connection)
...
             }
 
-            if (!_closed)
-            {
-            //    CloseAsync(H3_INTERNAL_ERROR).GetAwaiter().GetResult();
-            }
+            // Dispose the connection
+            // If we already waited for graceful shutdown from the client, then the connection is already closed and this will simply release the handle.
+            // If not, then this will silently abort the connection.
+            _connection.Dispose();
```
Comment (ManickaP) [inline src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs:62]: Will this cause us to drop connections prematurely again? I know that the close/dispose were commented out, because the server task would sometimes finish before the client. It would close the connection from the server side and then the client response reading would throw due to a closed stream.

File: src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs [hunk 2]
```diff
@@ -44,21 +50,26 @@ public Http3LoopbackConnection(QuicConnection connection)
...
 
-            //_connection.Dispose();
+            // Dispose control streams so that we release their handles too.
+            _inboundControlStream?.Dispose();
```
[the remark this answers is not in the document]
Comment (geoffkizer) [reply src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs:65]: As long as we close the connection first, it shouldn't matter.

That said, in this path we may or may not have closed the connection (as per comment above). If we haven't, then it does matter because if we dispose the stream before the connection, this will abort the stream because the connection is still open. We don't want that.

File: src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs (hunk 1 above)
Comment (geoffkizer) [reply src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs:62]: I don't think so. 

The original problem was with code that would use CreateClientAndServer. The problem here was that we would spawn a task for the client and another for the server, then wait for them both. And the server task would dispose the server connection when it completed. This could result in losing data. The fix was to have the server wait for graceful shutdown in these cases.

Most code that doesn't use CreateClientAndServer should not have this problem.

Note though that if code does have this problem, then it already has it because even though we didn't dispose the connection here previously, it was still collectible at this point, meaning that we would likely see occasional failures here. So actively disposing the connection here is probably better since it will be more likely to fail consistently.

Comment (ManickaP) [reply src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs:62]: I think that we might revisit some of the H/3 tests and see if this might be a problem there. For example: 
https://github.com/dotnet/runtime/blob/c8dc49e6e7a654cc730a18c209513561f560c1ae/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs#L35

It's disabled now so we wouldn't see any problem, but I think it might suffer from this problem. I assume that adding `WaitForClientDisconnectAsync` add the end of the server task should mitigate this, am I right?

**Review by ManickaP — APPROVED** [review]
LGTM, thanks!

**Comment by ManickaP** [comment]
Test failures are relevant. I checked out this PR and I'm seeing the same problems locally.

**Comment by CarnaViire** [comment]
@geoffkizer were LoopbackServer changes necessary to test HttpClient changes? I am afraid of a possible spike in test failures which we might not be able to properly react to... Maybe if we do LoopbackServer changes in a separate PR it will be easier to revert if something blows up? I understand that we would not want to revert this change completely, because previous HttpClient behavior was breaking the spec.

File: src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs (hunk 1 above)
Comment (geoffkizer) [reply src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs:62]: I agree, there could be a problem here, unfortunately.

> I assume that adding WaitForClientDisconnectAsync at the end of the server task should mitigate this, am I right?

Yes, I believe that would handle it. That said, I think we should revisit how this works generally, as it is slightly different for every version of HTTP, which seems bad. That's not something to tackle for 6.0 though.

I think what we should do here is just revert the change here that disposes the connection, to minimize behavioral change in the loopback server. I'll update and post a new version of the PR.

**Comment by geoffkizer** [comment]
I reverted the loopback connection Dispose behavior to not dispose the connection, as it worked previously. I believe this will mitigate the test issues introduced here.

Note that there is one minor change to loopback Dispose, which is that we no longer Dispose the client control stream. I don't think this should cause any problems, and it's actually more correct per RFC -- we shouldn't ever close the client's control stream while the connection is still alive.

The rest of the loopback changes here are all about handling the client's control stream, and are necessary to test the change here -- that is, that we don't close the control stream before closing the connection. I believe these are relatively safe.

Please take a look.

**Comment by geoffkizer** [comment]
Note that this comment from me above still applies, I believe:

> Note though that if code does have this problem, then it already has it because even though we didn't dispose the connection here previously, it was still collectible at this point, meaning that we would likely see occasional failures here. So actively disposing the connection here is probably better since it will be more likely to fail consistently.

In other words, we still have a test issue where the loopback connection could, in theory, get collected and cause occasional failures here. I don't know whether this is actually happening in practice.

**Review by CarnaViire — APPROVED** [review]
LGTM

**Comment by geoffkizer** [comment]
The failure in InvalidCertificateServers_CertificateValidationDisabled_Succeeds looks unrelated -- looks like an external server issue.
