### PR TITLE
[browser] dev tools profiler - method name resolution

### LINKED ISSUE #115551: Uncaught (in promise) RuntimeError: memory access out of bounds
Repro steps:
- Install .NET 10 Preview 4 with wasm-tools workload
- Create new Blazor Web App with interactive WebAssembly rendering enabled
- Add MSBuild properties to the Client project to enable browser perf profiling:

```xml
    <WasmProfilers>browser</WasmProfilers>
    <WasmNativeStrip>false</WasmNativeStrip>
    <WasmNativeDebugSymbols>true</WasmNativeDebugSymbols>
```

- Run the app and browse to the counter page
- In the browser dev tools performance tab, start a recording
- Click the counter a bunch of times and stop the recording
- Check the browser dev console:

```
dotnet.native.p6c5fv8ns5.wasm:0x294bd1  Uncaught (in promise) RuntimeError: memory access out of bounds
    at dotnet.native.wasm.strlen (dotnet.native.p6c5fv8ns5.wasm:0x294bd1)
    at dotnet.native.wasm.mono_wasm_method_get_name_ex (dotnet.native.p6c5fv8ns5.wasm:0x2b71df)
    at Pc (profiler.ts:109:30)
    at dotnet.native.wasm.method_leave (dotnet.native.p6c5fv8ns5.wasm:0x90b0)
    at dotnet.native.wasm.mono_profiler_raise_method_leave (dotnet.native.p6c5fv8ns5.wasm:0xfbd2c)
    at dotnet.native.wasm.mono_interp_profiler_raise (dotnet.native.p6c5fv8ns5.wasm:0x1b5d9)
    at dotnet.native.wasm.mono_interp_exec_method (dotnet.native.p6c5fv8ns5.wasm:0x18290)
    at dotnet.native.wasm.interp_runtime_invoke (dotnet.native.p6c5fv8ns5.wasm:0x1c36f)
    at dotnet.native.wasm.mono_jit_runtime_invoke (dotnet.native.p6c5fv8ns5.wasm:0x1331a4)
    at dotnet.native.wasm.do_runtime_invoke (dotnet.native.p6c5fv8ns5.wasm:0xf2238)
```

### PR DESCRIPTION
**Pull request by pavelsavara**
- dereference of un-initialized buffer
- `snprintf` doesn't zero-terminate too long strings

Fixes https://github.com/dotnet/runtime/issues/115551

### CODE REVIEW

**Review by maraf — APPROVED** [review]

File: src/mono/browser/runtime/driver.c [hunk 1]
```diff
@@ -521,9 +521,12 @@ EMSCRIPTEN_KEEPALIVE char * mono_wasm_method_get_name_ex (MonoMethod *method) {
 	MONO_ENTER_GC_UNSAFE;
 	const char *method_name = mono_method_get_name (method);
 	// starts with .ctor or .cctor
-	if (mono_method_get_flags (method, NULL) & 0x0800 /* METHOD_ATTRIBUTE_SPECIAL_NAME */ && strlen (res) < 7) {
+	if (!method_name) {
+		res = strdup ("<unknown>");
+	} else if (method_name && mono_method_get_flags (method, NULL) & 0x0800 /* METHOD_ATTRIBUTE_SPECIAL_NAME */ && strlen (method_name) < 7) {
 		res = (char *) malloc (128);
 		snprintf (res, 128,"%s.%s", mono_class_get_name (mono_method_get_class (method)), method_name);
+		res[127] = '\0';
```
Comment (lewing) [inline src/mono/browser/runtime/driver.c:529]: this is harmless but snprintf should null terminate even at max length, is it really not?

Comment (pavelsavara) [reply src/mono/browser/runtime/driver.c:529]: [MS Doc](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l?view=msvc-170)
`The _snprintf family of functions only appends a terminating NULL character if the formatted string length is strictly less than count characters.`

Maybe emscripten libc is different, but I wanted to be sure.
