### PR TITLE
[mono] Add test for wasm loader regression, fix loading from bundle

### LINKED ISSUE #42207: Asp.Net 5.0 Blazor Assembly.Load does not create types that link to types in loaded assemblies
### Describe the bug
When using Blazor running in the browser with dotnet 5.0.0-preview.8.20407.11 an assembly loaded using Assembly.Load(byte[] rawAssembly, byte[]? rawSymbolStore) will create types that reference assemblies that appear to be duplicates of assemblies that have already been loaded preventing any use of shared types. This behavior is different to other non WASM runtimes and to the dotnet 3.2.0 WASM runtime.

The bug is not present in the release of WASM Blazor in dotnet core 3.2.0 and was found during an upgrade of existing code.

E.g.
* A Type A implements interface IA
* Interface IA is defined in an assembly that the a Blazor component is build against
* Type A is defined in an project that references the project interface IA is present in
* Interface IA will be resolved when the Blazor component loads.
* Type A is defined in an assembly loaded by Assembly.Load
* In the dotnet 5.0 WASM runtime the interface IA implemented by Type A is defined in an assembly that is different to the interface IA referenced by the Blazor component meaning that the component cannot cast Type A to Interface IA.
* The same code run in a stardard dotnet 5.0 runtime is correctly able to perform the cast.

### To Reproduce
A reproduction based on the Blazor starter project is available from: https://github.com/allderidge/BlazorBugReport_AssemblyLoad

There are two solutions:
* AssemblyLoadTest_5_0/AssemblyLoadTest.sln Reproduces the bug and illustrates that a test in a standard runtime passes.
* AssemblyLoadTest_3_2_0/AssemblyLoadTest.sln Illustrates the bug is not present in the dotnet core 3.2

### The web page shown running in dotnet 5.0:
image

### The web page shown running in dotnet core 3.2
image

### Illustrative code
``` c#
var assemblyData = await Client.GetFromJsonAsync<DynamicAssembly>("Assembly");
var assembly = Assembly.Load(assemblyData.AssemblyDllBytes, assemblyData.AssemblyPdbBytes);

var dynamicType = assembly.GetType("AssemblyLoadTest.Dynamic.SharedInterfaceImplementation", true) ?? throw new ApplicationException("Unable to load dynamic type");
var sharedInterface = dynamicType.GetInterfaces().First(e => e.Name == nameof(ISharedInterface));
SharedAssemblyMatches = sharedInterface.Assembly == typeof(ISharedInterface).Assembly;  // should be true, false in bug repo
SharedInterfaceMatches = sharedInterface == typeof(ISharedInterface); // should be true, false in bug repo

var instance = Activator.CreateInstance(dynamicType);
CanCast = instance is ISharedInterface;  // should be true, false in bug repo

Name = ((ISharedInterface)instance).HelloWorldName; // causes a invalid cast exception
```

### Further technical details
- ASP.NET Core version: `5.0.0-preview.8.20414.8`
- Include the output of `dotnet --info`

```.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]
  3.1.103 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
`Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 2.1`

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Fixes https://github.com/dotnet/runtime/issues/42207

The new test is based on the sample from that issue.

The naive fix (moving all bundle loading to after we check the default ALC) highlights that the satellite assembly tests were passing for the wrong reasons. The full fix here handles satellite loads correctly, putting them in the same ALC as the parent assembly. One non-satellite test that was previously passing also passed erroneously, but it makes no sense on wasm so disable it.

I don't know how likely we think customers are to use custom ALCs on wasm, but the current behavior seems fairly broken. For the repro I use `Assembly.Load(byte[])` to match the customer issue, but I think you can achieve the same effect by just loading an assembly into a custom ALC and trying to cast the same way.

If we do want to backport, the problem is these changes are all on top of @safern's previous bundle work, so I'd either need to backport the whole thing or manually implement some of this work on top of RC2. Maybe the latter option is the way to go here? Not sure how to proceed. cc: @marek-safar @SamMonoRT

### CODE REVIEW

**Comment by marek-safar** [comment]
Landing this to master only is fine

**Comment by CoffeeFlux** [comment]
Option 1: Get things completely correct. We'd need to backport this, https://github.com/dotnet/runtime/pull/41358, and a small PR I'm about to submit to aspnetcore (and by that I mean after I sleep).

Option 2: Manually backport this PR on top of RC2, fixing the ALC selection issues and ignoring the satellite assembly culture problems addressed by the previous PR. I lean towards this since it seems to minimize risk while fixing a clear issue with custom ALC usage, but it's significantly more work for me.

Option 3: Backport this PR and https://github.com/dotnet/runtime/pull/41358. This would produce a much larger diff than option 2, and with it significantly higher risk, but fixes a couple extra issues related to satellite assemblies and is also essentially zero extra work.

After giving it some thought, I lean towards option 2 here since I still don't think the satellite assembly issues are pressing enough to merit the associated risk and am less concerned about the risk associated with a manual backport than I was a few hours ago; the diff shouldn't be that large outside of the new test. Additionally, we have a direct customer bug report for this, whereas the satellite assembly bugs were just found via failing tests.

All that said, I'm heading to bed so I guess I'll see how I feel after getting some rest. If you also think option 2 is the way to go here, I'll start on that when I get up.

File: src/mono/mono/metadata/assembly.c [hunk 1]
```diff
@@ -1741,6 +1737,38 @@ netcore_load_reference (MonoAssemblyName *aname, MonoAssemblyLoadContext *alc, M
...
+		}
+	}
+
+	if (satellite_bundles != NULL && is_satellite) {
+		// Satellite assembly byname requests should be loaded in the same ALC as their parent assembly
+		size_t name_len = strlen (aname->name);
+		char *parent_name = NULL;
+		MonoAssemblyLoadContext *parent_alc = NULL;
+		if (g_str_has_suffix (aname->name, MONO_ASSEMBLY_RESOURCE_SUFFIX))
+			parent_name = g_strdup_printf ("%s.dll", g_strndup (aname->name, name_len - strlen (MONO_ASSEMBLY_RESOURCE_SUFFIX)));
```
Comment (lambdageek) [inline src/mono/mono/metadata/assembly.c:1754]: I'm confused why this should ever be true.   `aname` is an assembly name, not a file name.  So it's something like `"System.Private.CoreLib, PublicKeyToken=xyz, Version=a.b.c.d, Culture=jp"`.  So why isn't `MonoAssemblyName parent_aname` just a copy of `aname` with culture set to neutral?

File: src/mono/mono/metadata/assembly.c [hunk 2]
```diff
@@ -1741,6 +1737,38 @@ netcore_load_reference (MonoAssemblyName *aname, MonoAssemblyLoadContext *alc, M
...
+
+		if (parent_name) {
+			MonoAssemblyOpenRequest req;
+			mono_assembly_request_prepare_open (&req, MONO_ASMCTX_DEFAULT, alc);
+			MonoAssembly *parent_assembly = mono_assembly_request_open (parent_name, &req, NULL);
+			parent_alc = mono_assembly_get_alc (parent_assembly);
+		}
+
+		if (parent_alc)
+			reference = search_bundle_for_assembly (parent_alc, aname);
```
Comment (lambdageek) [inline src/mono/mono/metadata/assembly.c:1764]: Shouldn't `parent_alc == alc` always?  we're in netcore_load_reference - so we're resolving some reference.  can anyone other than the parent assembly reference the satellite assembly?

**Review by lambdageek — COMMENTED** [review]
i'm confused why we do a search by filename instead of by assembly name when looking for the parent assembly of a satellite assembly

File: src/mono/mono/metadata/assembly.c (hunk 2 above)
Comment (CoffeeFlux) [reply src/mono/mono/metadata/assembly.c:1764]: We get to `netcore_load_reference` with any byname load, so you can trigger this by initiating a byname load from a custom ALC for a satellite assembly whose parent does not live in that ALC. We actually test this functionality, and this bit of code mirrors what we do in managed for normal satellite assembly loads.

File: src/mono/mono/metadata/assembly.c (hunk 1 above)
Comment (CoffeeFlux) [reply src/mono/mono/metadata/assembly.c:1754]: The satellite assembly names all have `.resources` at the end. All this is purely copying some previous managed logic over to the native side. https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L714

**Comment by CoffeeFlux** [comment]
After sleep and some discussion with Aleksey, I think we should definitely not backport anything other than this. I'll do it manually once we reach a consensus and land this individual PR.

File: src/mono/mono/metadata/assembly.c [hunk 3]
```diff
@@ -1741,6 +1737,38 @@ netcore_load_reference (MonoAssemblyName *aname, MonoAssemblyLoadContext *alc, M
 		}
 	}
 
+	if (bundles != NULL && !is_satellite) {
+		reference = search_bundle_for_assembly (mono_domain_default_alc (mono_alc_domain (alc)), aname);
+		if (reference) {
+			mono_trace (G_LOG_LEVEL_DEBUG, MONO_TRACE_ASSEMBLY, "Assembly found in the bundle: '%s'.", aname->name);
+			goto leave;
+		}
+	}
```
Comment (lambdageek) [inline src/mono/mono/metadata/assembly.c:1746]: ok this part makes sense to me.

**Review by lambdageek — APPROVED** [review]
Had an offline discussion with @CoffeeFlux and this PR makes sense to me.

For the backport I like Option 2 (do a backport by hand that doesn't include the bundled satellite assembly changes from #41358).  The satellite assemblies change seems riskier and I don't entirely follow the consequences to `MonoLoadedImages` caches from the changes there.

**Review by safern — APPROVED** [review]
Makes sense to me, thanks for fixing the ALC miss match between satellite assemblies and parent assembly for bundled runtimes.
