### PR TITLE
Fix GetAppdomainStaticAddress for non-collectible assemblies

### LINKED ISSUE #40954: GetAppDomainStaticAddress only works for collectible modules
### Description

I have previously reported an issue with an AV in GetAppDomainStaticAddress (issue #33367), which was fixed in #34677. However, as far as I can see, this fix introduces a regression. It is no longer possible to retrieve AppDomain static addresses for non-collectible modules. The fix verifies that the LoadAllocator has an initialized "ExposedObject", but this object only seems to be initialized for collectible modules. Maybe "ExposedObject" should only be verified for collectible modules?

In ProfToEEInterfaceImpl::GetAppDomainStaticAddress:

```
    if (typeHandle.GetModule()->GetLoaderAllocator() == NULL ||
        typeHandle.GetModule()->GetLoaderAllocator()->GetExposedObject() == NULL)
    {
        return CORPROF_E_DATAINCOMPLETE;
    }
```

### Configuration

* .NET 5 Preview 7, Windows x86/x64

### Regression?

Works correctly under .NET Core 3.1.6, but this version may be susceptible to the AV mentioned in #33367. I have not been able to reproduce the original AV on .NET Core 3.1.6.

### PR DESCRIPTION
**Pull request by davmason**
Fixes #40954

#34677 had a bug in it that it would check if pModule->GetLoaderAllocator()->GetExposedObject was NULL, which is the right thing to check for collectible modules but non-collectible modules it will always be NULL.

### CODE REVIEW

File: src/coreclr/src/vm/proftoeeinterfaceimpl.cpp [hunk 1]
```diff
@@ -3146,8 +3146,10 @@ HRESULT ProfToEEInterfaceImpl::GetAppDomainStaticAddress(ClassID classId,
         return CORPROF_E_DATAINCOMPLETE;
     }
 
-    if (typeHandle.GetModule()->GetLoaderAllocator() == NULL ||
-        typeHandle.GetModule()->GetLoaderAllocator()->GetExposedObject() == NULL)
+    // We might have caught a collectible assembly in the middle of being collected
+    Module *pModule = typeHandle.GetModule();
+    if (pModule->IsCollectible() &&
+        (pModule->GetLoaderAllocator() == NULL || pModule->GetLoaderAllocator()->GetExposedObject() == NULL))
```
Comment (hoyosjs) [inline src/coreclr/src/vm/proftoeeinterfaceimpl.cpp:3152]: If this is the error we want to keep, can you update the doc comment atop saying "or if the type's assembly has been collected". Also, out of curiosity, is this the address for static fields in general?

**Review by sywhang — APPROVED** [review]

File: src/coreclr/src/vm/proftoeeinterfaceimpl.cpp (hunk 1 above)
Comment (davmason) [reply src/coreclr/src/vm/proftoeeinterfaceimpl.cpp:3152]: Sure, I can update the comment. The api exists because profilers don't have another way to inspect static fields. If a class has a static field it isn't part of the object on the heap, so you have to use this api to get a pointer to the field so you can inspect it.

**Review by noahfalk — APPROVED** [review]
👍

**Comment by sandreenko** [comment]
There was a test failure in a recent outerloop, is it a known issue?
https://dev.azure.com/dnceng/public/_build/results?buildId=794520&view=ms.vss-test-web.build-test-results-tab
```
  Starting:    profiler.unittest.XUnitWrapper
    profiler\unittest\getappdomainstaticaddress\getappdomainstaticaddress.cmd [FAIL]
      Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
         at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in /__w/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 138
         at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in /__w/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 92
         at Profiler.Tests.Program.Main(String[] args) in /__w/1/s/src/tests/profiler/unittest/getappdomainstaticaddress.cs:line 25
```

**Comment by davmason** [comment]
@sandreenko no that is not a known issue. Looking at the logs it's not a failure I would expect to see either. I'll try and dig a little deeper but I suspect that this is a one off thing I won't be able to investigate
