### PR TITLE
Check containment for op3 for ternary instruction

### LINKED ISSUE #111835: Assertion failed '(consume == 0) || (ComputeAvailableSrcCount(tree) == consume)'
Compile the following method with Checked JIT:
```cs
public bool EqualsTest(byte* a, byte* b, nuint len)
{
    for (nuint i = 0; i < len; i += 128)
    {
        var v11 = Vector512.LoadAligned(a + i);
        var v12 = Vector512.LoadAligned(a + i + 64);
        var v21 = Vector512.LoadAligned(b + i);
        var v22 = Vector512.LoadAligned(b + i + 64);
        if (((v11 ^ v21) | (v12 ^ v22)) != Vector512<byte>.Zero)
            return false;
    }
    return false;
}
```
Expected: compiles
Actual:
```
Assert failure(PID 374500 [0x0005b6e4], Thread: 444996 [0x6ca44]): Assertion failed '(consume == 0) || (ComputeAvailableSrcCount(tree) == consume)' in 'Benchmarks:EqualsTest(ulong,ulong,ulong):ubyte:this' during 'Linear scan register alloc' (IL size 105; hash 0x96711b35; FullOpts)

    File: C:\prj\runtime-main\src\coreclr\jit\lsrabuild.cpp:1775
    Image: C:\prj\runtime-main\artifacts\bin\coreclr\windows.x64.Checked\CoreRun.exe
```

### PR DESCRIPTION
**Pull request by kunalspathak**
Fixes: https://github.com/dotnet/runtime/issues/111835

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @saucecontrol

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib ping

File: src/coreclr/jit/lsraxarch.cpp [hunk 1]
```diff
@@ -2965,8 +2965,18 @@ int LinearScan::BuildHWIntrinsic(GenTreeHWIntrinsic* intrinsicTree, int* pDstCou
...
+                        srcCount += BuildAddrUses(op3->AsHWIntrinsic()->Op(1), op3RegCandidates);
+                    }
+                    else if (isRMW)
+                    {
+                        srcCount += BuildDelayFreeUses(op3, op1, op3RegCandidates);
+                    }
+                    else
+                    {
+                        srcCount += BuildOperandUses(op3, op3RegCandidates);
+                    }
```
Comment (tannergooding) [inline src/coreclr/jit/lsraxarch.cpp]: Is this correct? Shouldn't it be `if (isRMW && !op3->isContained())` since it being contained or producing a scalar means there is no need to delay free?

It would then match the handling done for the 1-operand and 2-operand paths.

Comment (kunalspathak) [reply src/coreclr/jit/lsraxarch.cpp]: true. fixed

**Review by tannergooding — APPROVED** [review]
