### PR TITLE
Fix ulong->double conversion on x64 (without avx512f)

### LINKED ISSUE #43895: UInt64 to Double conversions are incorrect
Conversions from `UInt64` to `Double` for values greater than `long.MaxValue` are currently incorrect. The same issue may exist for `UInt32` to `Double` for values greater than `int.MaxValue` but I have not confirmed.

The simple repro case is detailed here: https://github.com/dotnet/csharplang/discussions/4074
```csharp
using System;
namespace App
{
    internal static class Program
    {
        internal static void Main()
        {
            /// Displays 'True'.
           Console.WriteLine(10648738977740919977d != 10648738977740919977);
        }
    }
}
```

You can see approximately what the runtime generates by looking at: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWzQBMQBqAHwAEAmARgFgAoSgZgAIa2BhNgbybaCO7IhACuwADYw2AWQAUYyRAB2AczYIAlHwFD9lAOyaA3HsEBfJhaA===
```csharp
public double M(ulong x) {
    return x;
}
```

Which results in:
```asm
    L0000: vzeroupper
    L0003: vxorps xmm0, xmm0, xmm0
    L0007: vcvtsi2sd xmm0, xmm0, rdx
    L000c: test rdx, rdx
    L000f: jge short L0019
    L0011: vaddsd xmm0, xmm0, [C.M(UInt64)]
    L0019: ret
```

The constant used by `L0011` appears to be `1.8446744073709552E+19` (`0x43f0000000000000`)

category:correctness
theme:optimization
skill-level:beginner
cost:small
impact:small

### LINKED ISSUE #102149: Bizarre decimal-to-double behavior difference on same machine, same code
### Description

I made a dotnet class library with a single method:

    public static double ConvertForMe(decimal d)
    {
           return (double)d;
    }

I then wrote a small console program that calls this, like this:

    var dec = -4619.7403751459050600M;
    var doubleDll = DoubleConversion.DoubleConversion.ConvertForMe(dec);
    Console.WriteLine($"Decimal:   {dec}");
    Console.WriteLine($"Double dll: {doubleDll}");.

I get:

    Decimal:   -4619,7403751459050600
    Double dll: -4619,740375145904

That's fine, I guess, and this can be reproduced on various machines and online dotnet playgrounds. However, on the _same machine_ using the _same, previously compiled, class library_, but calling it from inside a larger .NET 8-based server we have running there in test, we instead get:

    Decimal:   -4619,7403751459050600
    Double dll: -4619,740375145905

Which amounts to a difference in the LSB in the Int64 representation of the double (using BitConverter). Since this is financial software, people are wondering about this, and I can't explain it. This only seems to happen on this particular machine (and only when invoked via our larger server, using Assembly.Load and IoC).

### Reproduction Steps

As described above. We haven't been able to reproduce the abnormal result in any other contexts so far.

### Expected behavior

The version ending in 4. Well, it's hard to say. I think the version ending in 5 seems more correct, but every other context, machine and online playground seems to give the one ending in 4. 

### Actual behavior

When we call the method in the dll from our (ultimately .NET 8 console program started as Windows service), we get the version ending in 5.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

The problem happens on the same machine, but the environment is slightly different. Common environment variables that might influence this (but that are present both in the 4 and 5 case):

    DOTNET_gcServer: 1

Environment variables unique to the case where we get the abnormal behavior:

    COMPlus_ReadyToRun: 0
    CORECLR_ENABLE_PROFILING: 1
    CORECLR_PROFILER: {some guid}
    CORECLR_PROFILER_PATH_64: some-path-to-dynatrace/.../oneagentloader.dll

I have tried to manually set the COMPlus variable but it doesn't reproduce the abnormal behavior. I haven't investigated if the tracing can be related.

Other configuration:
.NET 8.0.2
Microsoft Windows 10.0.14393

Both programs run as framework-dependent.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/102149
Fixes https://github.com/dotnet/runtime/issues/43895

### CODE REVIEW

File: src/coreclr/jit/utils.cpp [hunk 1]
```diff
@@ -2230,33 +2230,7 @@ unsigned CountDigits(double num, unsigned base /* = 10 */)
...
-#else
-        d = (double)uIntVal;
-#endif
-    }
-    else
-    {
-        d = (double)uIntVal;
-    }
-    return d;
+    return (double)uIntVal;
```
Comment (jkotas) [inline src/coreclr/jit/utils.cpp:2233]: There is similar cruft in `convertDoubleToUInt64` below. I think `convertDoubleToUInt64` can be just `return (UINT64)d;`. (It is fine to do in separate change if you prefer.)

Comment (EgorBo) [reply src/coreclr/jit/utils.cpp:2233]: Right, I'd prefer a separate change. My understanding that we need to be careful depending on the current compiler behaviour E.g. MSVC has changed its the behavior for `ulong -> double` not long ago: https://godbolt.org/z/rE8axqhra

**Comment by EgorBo** [comment]
@tannergooding PTAL

File: src/coreclr/inc/clrconfigvalues.h [hunk 2]
```diff
@@ -762,7 +762,7 @@ RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableAVX512CD,               W("EnableAVX512C
 RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableAVX512CD_VL,            W("EnableAVX512CD_VL"),         1, "Allows AVX512CD_VL+ hardware intrinsics to be disabled")
 RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableAVX512DQ,               W("EnableAVX512DQ"),            1, "Allows AVX512DQ+ hardware intrinsics to be disabled")
 RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableAVX512DQ_VL,            W("EnableAVX512DQ_VL"),         1, "Allows AVX512DQ_VL+ hardware intrinsics to be disabled")
-RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableAVX512F,                W("EnableAVX512F"),             1, "Allows AVX512F+ hardware intrinsics to be disabled")
+RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableAVX512F,                W("EnableAVX512F"),             0, "Allows AVX512F+ hardware intrinsics to be disabled")
```
Comment (tannergooding) [inline src/coreclr/inc/clrconfigvalues.h:765]: This looks like it was accidentally included. The `runtime-coreclr jitstress-isas-x86` jobs should be able to cover this for CI

File: src/coreclr/jit/codegen.h [hunk 3]
```diff
@@ -60,9 +60,6 @@ class CodeGen final : public CodeGenInterface
     // Bit mask used in zeroing the 3rd element of a SIMD12
     CORINFO_FIELD_HANDLE zroSimd12Elm3;
 
-    // Bit mask used in U8 -> double conversion to adjust the result.
-    CORINFO_FIELD_HANDLE u8ToDblBitmask;
```
Comment (tannergooding) [inline src/coreclr/jit/codegen.h:64]: Unrelated, but I don't think any of these handles are actually needed anymore.

The method local constant APIs already browse the constant table for matching bit patterns to avoid duplicating them.

Comment (EgorBo) [reply src/coreclr/jit/codegen.h:64]: Good point, will delete them once current CI run finishes

File: src/coreclr/inc/clrconfigvalues.h (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/inc/clrconfigvalues.h:765]: Yep, just wanted to have first results (potential failures) before `jitstress-isas-x86`

File: src/coreclr/jit/codegenxarch.cpp [hunk 4]
```diff
@@ -7532,47 +7532,53 @@ void CodeGen::genIntToFloatCast(GenTree* treeNode)
...
-        // and gcc generate. However, we keep the current sequence for backward compatibility.
-        // If we change the instructions below, FloatingPointUtils::convertUInt64ToDobule
-        // should be also updated for consistent conversion result.
         assert(dstType == TYP_DOUBLE);
         assert(op1->isUsedFromReg());
 
-        // Set the flags without modifying op1.
-        // test op1Reg, op1Reg
-        inst_RV_RV(INS_test, op1->GetRegNum(), op1->GetRegNum(), srcType);
+        // The following LONG->DOUBLE cast machinery is based on clang's implementation
```
Comment (tannergooding) [inline src/coreclr/jit/codegenxarch.cpp:7545]: I wonder if doing this in codegen is better than doing it in lowering or an inlinable managed implementation instead.

For example, this hinders LSRAs ability to optimize (such as if `argReg` was last use since temp registers are always delay free) and will also impact the ability to easily pick the right instructions for each node, which will be more relevant when APX comes online.

The logic here isn't really that complex and basically boils down to:
```csharp
static double ConvertToDouble(ulong value)
{
    long signedValue = (long)value;

    if (signedValue >= 0)
    {
        return signedValue;
    }
    signedValue = (signedValue >>> 1) | (signedValue & 1);

    double tmp = signedValue;
    return tmp + tmp;
}
```

The JIT generates pretty ideal code for this already (this is for SSE2 baseline):
```asm
; Method Program:ConvertToDouble(ulong):double (FullOpts)
G_M000_IG01:                ;; offset=0x0000

G_M000_IG02:                ;; offset=0x0000
       test     rcx, rcx
       jl       SHORT G_M000_IG05

G_M000_IG03:                ;; offset=0x0005
       xorps    xmm0, xmm0
       cvtsi2sd  xmm0, rcx

G_M000_IG04:                ;; offset=0x000D
       ret      

G_M000_IG05:                ;; offset=0x000E
       mov      rax, rcx
       shr      rax, 1
       and      rcx, 1
       or       rax, rcx
       xorps    xmm0, xmm0
       cvtsi2sd  xmm0, rax
       addsd    xmm0, xmm0

G_M000_IG06:                ;; offset=0x0027
       ret      
; Total bytes of code: 40
```

The only real pessimization is that `cvtsi2sd` can avoid the `xorps` and leave the upper bits undefined instead to save a few extra bytes of codegen. Given we already have a branch for `jns` its also not clear that using `cmov` is preferable over doing the early out instead and minimally duplicating the logic 

-------------

Notably we can get the JIT to generate `cmov` instead via:
```csharp
static double ConvertToDouble2(ulong value)
{
    long signedValue = (long)value;

    if (signedValue < 0)
    {
        signedValue = (signedValue >>> 1) | (signedValue & 1);
    }

    double result = signedValue;

    if (signedValue < 0)
    {
        result += result;
    }

    return result;
}
```

which generates
```asm
; Method Program:ConvertToDouble2(ulong):double (FullOpts)
G_M000_IG01:                ;; offset=0x0000

G_M000_IG02:                ;; offset=0x0000
       mov      rax, rcx
       mov      rdx, rcx
       shr      rdx, 1
       and      rcx, 1
       or       rcx, rdx
       test     rax, rax
       cmovl    rax, rcx
       xorps    xmm0, xmm0
       cvtsi2sd  xmm0, rax
       test     rax, rax
       jge      SHORT G_M000_IG04

G_M000_IG03:                ;; offset=0x0024
       addsd    xmm0, xmm0

G_M000_IG04:                ;; offset=0x0028
       ret      
; Total bytes of code: 41
```

The same `xorps` bit exists as does us missing we can reuse the flags from the previous test, since no intermediate operations overwrote them. But both are general purpose opts we can make to then get identical codegen to clang. -- We also pick the `l` and `ge` conditions, rather than the `ns` condition, but that's just because we don't model that `test` always clears `OF` and so we can just check `SF` rather than `SF != OF`

**Review by tannergooding — APPROVED** [review]
Looks good/correct to me.

Really just a question on if doing this all in lowering vs deferring to a managed implementation that can be inlined is better.

File: src/coreclr/jit/codegenxarch.cpp (hunk 4 above)
Comment (EgorBo) [reply src/coreclr/jit/codegenxarch.cpp:7545]: I agree that Lower sounds like a better place, the main problem that we can't introduce control flow (basic blocks) there so I don't know how to do that jump, perhaps can be made branchless with some efforts with SIMD, but I guess we talk about a relatively rare case of `ulong -> double/float` cast on X64 without AVX512, so not sure it's worth the efforts. Since this change is more about correctness I propose we think about a more performant (in case if the current approach is indeed slow) solution separately

Comment (EgorBo) [reply src/coreclr/jit/codegenxarch.cpp:7545]: > If we could just do the managed implementation and the JIT could inline that managed helper,

We currently have a single GT_CAST node that is easy to hoist/cse etc. An inlined control flow from a managed helper will be, sadly, hard to work with 🙁

File: src/coreclr/jit/utils.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/jit/utils.cpp:2233]: #102225
