### PR TITLE
exclude UTF8 string marshallers from cg2

### LINKED ISSUE #51189: Code generation failure when using `UnmanagedType.LPUTF8Str` in the interop definition inside System.Private.CoreLib.
Trying to define pinvoke like the following inside System.Private.CoreLib 

```
        [DllImport(Libraries.GlobalizationNative, CharSet = CharSet.Unicode, EntryPoint = "GlobalizationNative_WindowsIdToIanaId")]
        internal static extern unsafe int WindowsIdToIanaId(string windowsId, [MarshalAs(UnmanagedType.LPUTF8Str)] string? region, char* ianaId, int ianaIdLength);
```

I am getting the following error. Looks because the usage of `UnmanagedType.LPUTF8Str`. Changing to `UnmanagedType.LPStr` will make it work but could be wrong if we expect UTF8 string.

```
EXEC : error : One or more errors occurred. (Code generation failed for method '[S.P.CoreLib]System.TimeZoneInfo.TryConvertWindowsIdToIanaId(string,string,bool,string&)') [C:\oss\runtime\src\coreclr\crossgen-corelib.proj]
  System.AggregateException: One or more errors occurred. (Code generation failed for method '[S.P.CoreLib]System.TimeZoneInfo.TryConvertWindowsIdToIanaId(string,string,bool,string&)')
   ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[S.P.CoreLib]System.TimeZoneInfo.TryConvertWindowsIdToIanaId(string,string,bool,string&)'
   ---> System.InvalidOperationException: Expected type 'Internal.Runtime.CompilerHelpers.InteropHelpers' not found in module 'System.Private.CoreLib'
     at Internal.IL.HelperExtensions.GetKnownType(ModuleDesc module, String namespace, String name)
     at Internal.IL.HelperExtensions.GetHelperType(TypeSystemContext context, String name)
     at Internal.IL.HelperExtensions.GetHelperEntryPoint(TypeSystemContext context, String typeName, String methodName)
     at Internal.TypeSystem.Interop.UTF8StringMarshaller.TransformManagedToNative(ILCodeStream codeStream)
     at Internal.TypeSystem.Interop.Marshaller.AllocAndTransformManagedToNative(ILCodeStream codeStream)
     at Internal.TypeSystem.Interop.Marshaller.EmitMarshalArgumentManagedToNative()
     at Internal.TypeSystem.Interop.Marshaller.EmitForwardArgumentMarshallingIL()
     at Internal.TypeSystem.Interop.Marshaller.EmitArgumentMarshallingIL()
     at Internal.TypeSystem.Interop.Marshaller.EmitMarshallingIL(PInvokeILCodeStreams pInvokeILCodeStreams)
     at Internal.IL.Stubs.PInvokeILEmitter.EmitIL()
     at Internal.IL.Stubs.PInvokeILEmitter.EmitIL(MethodDesc method)
     at ILCompiler.Compilation.ILCache.CreateValueFromKey(MethodDesc key)
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
     at ILCompiler.Compilation.GetMethodIL(MethodDesc method)
     at Internal.JitInterface.CorInfoImpl.pInvokeMarshalingRequired(CORINFO_METHOD_STRUCT_* handle, CORINFO_SIG_INFO* callSiteSig)
     at Internal.JitInterface.CorInfoImpl._pInvokeMarshalingRequired(IntPtr thisHandle, IntPtr* ppException, CORINFO_METHOD_STRUCT_* method, CORINFO_SIG_INFO* callSiteSig)
     --- End of inner exception stack trace ---
     at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)
     at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger)
     at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__36_0(DependencyNodeCore`1 dependency)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica.Execute()
     --- End of inner exception stack trace ---
     at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
     at ILCompiler.ReadyToRunCodegenCompilation.ComputeDependencyNodeDependencies(List`1 obj)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
     at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```

### PR DESCRIPTION
**Pull request by mangod9**
Fixes https://github.com/dotnet/runtime/issues/51189

@dotnet/crossgen-contrib

### CODE REVIEW

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs [hunk 1]
```diff
@@ -25,12 +25,15 @@ protected static Marshaller CreateMarshaller(MarshallerKind kind)
                     return new BooleanMarshaller();
                 case MarshallerKind.AnsiString:
                     return new AnsiStringMarshaller();
+#if !READYTORUN
```
Comment (mangod9) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs:28]: just realized that this is specific to R2R so just need to remove these instead of `#ifdef`-ing

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs [hunk 2]
```diff
@@ -25,12 +25,15 @@ protected static Marshaller CreateMarshaller(MarshallerKind kind)
...
+                // UTF8 and Unicode Strings are not supported in R2R
                 case MarshallerKind.UTF8String:
                     return new UTF8StringMarshaller();
-                case MarshallerKind.SafeHandle:
-                    return new SafeHandleMarshaller();
                 case MarshallerKind.UnicodeString:
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs:32]: Is this one not used in CoreLib? Looks like the common path of this marshaller is usable in crossgen - it's only corner cases (the string is passed by reference) that would hit non-existent helpers. We could also make the marshaller throw when it's in the corner case. (Just want to make sure we don't pregenerate fewer p/invokes and regress startup time.)

**Review by MichalStrehovsky — COMMENTED** [review]
Looks good otherwise!

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs [hunk 3]
```diff
@@ -25,12 +25,15 @@ protected static Marshaller CreateMarshaller(MarshallerKind kind)
...
                     return new UnicodeStringMarshaller();
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs:33]: Unicode marshaller is very frequently used on Windows, so removing it here will likely cause more methods to be JITed during startup.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs (hunk 2 above)
Comment (mangod9) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs:32]: Correct, its the non-pinned case here which is not handled correctly: https://github.com/dotnet/runtime/blob/fa779e8cb2b5868a0ac2fd4215f39ffb91f0dab0/src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs#L1494

Will check if throwing in that case excludes the method from precompilation.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs (hunk 3 above)
Comment (mangod9) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs:33]: yeah Michal also pointed that out above, will need to handle the non-supported cases so as to precompile the most common cases.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs (hunk 2 above)
Comment (mangod9) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs]: fixed to bring back UnicodeStringMarshaller

**Comment by davidwrighton** [comment]
>                                 Context.GetHelperEntryPoint("InteropHelpers", "CoTaskMemFree")));

This block needs the #if READYTORUN and throw NotSupportedException change as well.

---
Refers to: src/coreclr/tools/Common/TypeSystem/Interop/IL/Marshaller.cs:1609 in 3d9cb77. [](commit_id = 3d9cb772f876231c5e8705d236deac18c04c525a, deletion_comment = False)

**Review by davidwrighton — CHANGES_REQUESTED** [review]
:clock1:

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs [hunk 4]
```diff
@@ -25,8 +25,6 @@ protected static Marshaller CreateMarshaller(MarshallerKind kind)
                     return new BooleanMarshaller();
                 case MarshallerKind.AnsiString:
                     return new AnsiStringMarshaller();
-                case MarshallerKind.UTF8String:
-                    return new UTF8StringMarshaller();
```
Comment (AntonLapounov) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs:29]: Should we put it under `#if !READYTORUN` instead of removing?  I assume this code is shared with NativeAOT.

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs:29]: This file is not shared

Comment (mangod9) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Interop/IL/Marshaller.ReadyToRun.cs:29]: this code is specific to R2R. Notice this comment: https://github.com/dotnet/runtime/pull/55624#discussion_r669346533

**Review by davidwrighton — APPROVED** [review]

**Comment by mangod9** [comment]
`windows x86 release Runtime_Debug` is actually green, but the checks doesnt seem to have the updated status.
