### PR TITLE
Fix UpperVector save asserts

### LINKED ISSUE #2181: Assertion failed 'localVarInterval->assignedReg->isCalleeSave'
On Linux/arm64, JitStress=1 or JitStress=2, JIT/HardwareIntrinsics/General/Vector128_1/Vector128_1_ro/Vector128_1_ro.sh fails with:

```
Assert failure(PID 14794 [0x000039ca], Thread: 14794 [0x39ca]): Assertion failed 'localVarInterval->assignedReg->isCalleeSave' in 'JIT.HardwareIntrinsics.General.VectorAs__AsDouble:RunGenericScenario():this' (IL size 345)

    File: /home/bruce/gh/runtime/src/coreclr/src/jit/lsra.cpp Line: 7109
    Image: /home/brucefo/build/runtime/artifacts/tests/coreclr/Linux.arm64.Checked/Tests/Core_Root/corerun
```

with:
```
export COMPlus_TieredCompilation=0
export COMPlus_JitStress=1
```

Example in CI:
https://dev.azure.com/dnceng/public/_build/results?buildId=496122&view=results

### PR DESCRIPTION
**Pull request by CarolEidt**
Not all helper calls have standard kill sets.
Fix #2181

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/dnceng - the "Libraries Test Run release coreclr Linux_musl arm64 Release" run fails even on retry with:
```
.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20071.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(17,5): error : (NETCORE_ENGINEERING_TELEMETRY=Helix) You must specify at least one target queue to send a job to helix. Use the HelixTargetQueues property or HelixTargetQueue items.
```
I don't think this could be related to my changes, but I didn't see a similar issue

**Comment by MattGal** [comment]
> @dotnet/dnceng - the "Libraries Test Run release coreclr Linux_musl arm64 Release" run fails even on retry with:
> 
> ```
> .packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20071.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(17,5): error : (NETCORE_ENGINEERING_TELEMETRY=Helix) You must specify at least one target queue to send a job to helix. Use the HelixTargetQueues property or HelixTargetQueue items.
> ```
> 
> I don't think this could be related to my changes, but I didn't see a similar issue

I've seen this in other runtime builds as well.  It's a source-related problem (and I'd definitely prefer that Helix error when trying to send to nothing than "succeed" sending nothing) but I am quite certain you aren't introducing it.  I'll take a quick stab at commit history to see if I can find who did it and tag them.

**Comment by MattGal** [comment]
@CarolEidt it's just because your fork still has this change: https://github.com/dotnet/runtime/commit/41dea28c85a5a95dea79961896158a5ec484c797#diff-620b4a0ab54dce90ec71e41d9753bb38 .  Merge master in to make it go away (especially if you think your change is relevant to alpine ARM64 linux) otherwise you can choose to strategically ignore it.

**Comment by CarolEidt** [comment]
@mattgal - since this does impact arm64 I'll merge just to be safe. Thanks!

File: src/coreclr/src/jit/lsra.cpp [hunk 1]
```diff
@@ -7104,9 +7103,9 @@ void LinearScan::resolveRegisters()
                     Interval* localVarInterval = interval->relatedInterval;
                     if ((localVarInterval->physReg != REG_NA) && !localVarInterval->isPartiallySpilled)
                     {
-                        // If the localVar is in a register, it must be a callee-save register (otherwise it would have
-                        // already been spilled).
-                        assert(localVarInterval->assignedReg->isCalleeSave);
+                        // If the localVar is in a register, it must be in a register that is not trashed by
+                        // the current node (otherwise it would have already been spilled).
+                        assert((genRegMask(localVarInterval->physReg) & getKillSetForNode(treeNode)) == RBM_NONE);
```
Comment (CarolEidt) [inline src/coreclr/src/jit/lsra.cpp]: `GT_PROF_HOOK` has a special calling convention that doesn't kill the argument registers, so they may still be live here, so instead of checking that its in a callee-save, we need to check that it's *not* in the kill set for the current node.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
The failing test from #2181 is not failing in the stress testing.
There are arm failures that cannot possibly be related to this, as the changes are all under `FEATURE_PARTIAL_SIMD_CALLEE_SAVE`.

**Review by BruceForstall — APPROVED** [review]
