### PR TITLE
imul instruction size misprediction

### LINKED ISSUE #12840: Test Failed: Assert failure: 'sz == _idCodeSize'
**Job:**
https://mc.dot.net/#/user/coreclr-outerloop-jitstress2-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190609.1/workItem/JIT.Regression.CLR-x86-JIT.V1-M09-M11/analysis/xunit/JIT_Regression._CLR_x86_JIT_V1_M09_5_PDC_b25463_b25463_b25463_~2F_CLR_x86_JIT_V1_M09_5_PDC_b25463_b25463_b25463_cmd

**Failed tests:**
JIT_Regression._CLR_x86_JIT_V1_M09_5_PDC_b25463_b25463_b25463_._CLR_x86_JIT_V1_M09_5_PDC_b25463_b25463_b25463_cmd

**Log:**
```
Assert failure(PID 3192 [0x00000c78], Thread: 408 [0x0198]): Assertion failed 'sz == _idCodeSize' in 'ILGEN_0x7122ba20:main():int' (IL size 171)

    File: f:\\workspace\\_work\\1\\s\\src\\jit\\emit.h Line: 888
    Image: C:\\dotnetbuild\\work\\6c91f97e-ceba-49f1-b03d-10156f43cafe\\Payload\\CoreRun.exe

Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\6c91f97e-ceba-49f1-b03d-10156f43cafe\\Work\\c71234d0-eff6-4156-98e3-78836636de0c\\Exec\\JIT\\Regression\\Reports\\JIT.Regression\\CLR-x86-JIT\\V1-M09.5-PDC\\b25463\\b25463\\b25463.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\6c91f97e-ceba-49f1-b03d-10156f43cafe\\Payload\\corerun.exe\" b25463.exe 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\6c91f97e-ceba-49f1-b03d-10156f43cafe\\Payload
> C:\\dotnetbuild\\work\\6c91f97e-ceba-49f1-b03d-10156f43cafe\\Work\\c71234d0-eff6-4156-98e3-78836636de0c\\Exec\\JIT\\Regression\\CLR-x86-JIT\\V1-M09.5-PDC\\b25463\\b25463\\b25463.cmd
Expected: True
Actual:   False
```

category:implementation
theme:ir
skill-level:intermediate
cost:large

### LINKED ISSUE #57041: Assertion failed 'emitOffsAdj == newOffsAdj' during 'Emit code'
```c#
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
//
// This file is auto-generated.
// Seed: -1
//
using System;
using System.Runtime.CompilerServices;
public class TestClass34
{
    public struct S1
    {
    }
    public struct S2
    {
        public bool boolean_1;
    }
    public struct S4
    {
        public ulong uint64_1;
        public decimal decimal_3;
        public byte byte_4;
    }
    public struct S5
    {
    }
    static bool s_boolean_0 = false;
    static int s_int32_6 = 1;
    static float s_single_9 = 1;
    static ulong s_uint64_13 = 1;
    static S1 s_s1_15 = new S1();
    static S2 s_s2_16 = new S2();
    static S4 s_s4_18 = new S4();
    static int s_loopInvariant = 4;
    public int LeafMethod6()
    {
        unchecked
        {
            return s_int32_6 ^= s_int32_6 |= 15 | 4;
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public ulong LeafMethod13()
    {
        unchecked
        {
            return s_s4_18.uint64_1;
        }
    }
    public decimal Method1(ref S2 p_s2_0, ref S5 p_s5_1, out S2 p_s2_2, float p_single_3, S2 p_s2_4, S1 p_s1_5, ref S1 p_s1_6)
    {
        unchecked
        {
            int int32_2 = 1;
            ulong uint64_3 = 1;
            p_s2_2 = p_s2_4;
            { }
            {
                for (int __loopvar0 = s_loopInvariant - 9; s_int32_6 < (int32_2 %= 15 + 4) - (s_int32_6 *= LeafMethod6() ^ LeafMethod6() >> (int32_2 <<= 1805207166));)
                {
                    __loopvar0 += 3;
                    {
                        int __loopvar1 = 15 + 4, __loopSecondaryVar1_0 = 15 + 4;
                        for (; ; )
                        {
                            __loopvar1--;
                            __loopSecondaryVar1_0--;
                            if (s_boolean_0)
                            {
                                ulong uint64_238 = s_uint64_13 /= s_s4_18.uint64_1 |= 15 - 4 ^ (s_s4_18.uint64_1 &= (s_uint64_13 *= 26607244UL) % LeafMethod13() + 23) % LeafMethod13() ^ (uint64_3 *= s_uint64_13) ^ 15 & 4;
                            }
                        }
                    }
                }
            }
            return s_s4_18.decimal_3 /= 15 + 4;
        }
    }

    public static void Main(string[] args)
    {
        TestClass34 objTestClass34 = new TestClass34();
        S5 s5_4 = new S5();
        objTestClass34.Method1(ref s_s2_16, ref s5_4, out s_s2_16, s_single_9, s_s2_16, s_s1_15, ref s_s1_15);
    }
}
/*
Got output diff:
--------- Baseline ---------  

Environment:

COMPlus_JITMinOpts=1
COMPlus_TieredCompilation=1


--------- Test ---------  

Environment:

COMPlus_JITMinOpts=0
COMPlus_TieredCompilation=0
COMPlus_JitDoLoopInversion=0
COMPlus_JitStressRegs=1



Assert failure(PID 37488 [0x00009270], Thread: 21896 [0x5588]): Assertion failed 'emitOffsAdj == newOffsAdj' in 'TestClass34:Method1(byref,byref,byref,float,S2,S1,byref):System.Decimal:this' during 'Emit code' (IL size 258)

    File: D:\git\runtime\src\coreclr\jit\emit.cpp Line: 6049
    Image: D:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe


*/
```

Note: The repro could be reduced further.

### PR DESCRIPTION
**Pull request by kunalspathak**
During emitting `imul`, we wrongly predict the size of instruction as `16 bytes` whereas it should be just `15 bytes` (which is debatable, see below) comprising of 1 byte `REX prefix` + 1 byte `opcode` + 1 byte `modR/M` + 4 bytes `RIP-relative displacement` + 4 bytes of `immediate`. Last row in https://www.felixcloutier.com/x86/imul table.

Now as per Intel docs:

```
RIP-relative addressing allows specific ModR/M modes to address memory relative to the 64-bit RIP using a signed
32-bit displacement. 
```
which means the RIP immediate above should be just 4-bytes and the instruction size should be just `11 bytes`. But in `emitInsSizeCV()` we have it calculated as `valSize == 8`.

When calculating the size, it seems that we double calculate the `REX prefix size`, once in https://github.com/dotnet/runtime/blob/53a1ddc4af2cb7592125aa80e4f812f2a3a3fde3/src/coreclr/jit/emitxarch.cpp#L2612

and then further in `emitInsSize() -> emitGetPrefixSize()` in https://github.com/dotnet/runtime/blob/53a1ddc4af2cb7592125aa80e4f812f2a3a3fde3/src/coreclr/jit/emitxarch.cpp#L1188-L1191

Because of above conditions, we end up with size of `16 bytes` but when we save the size in `instrDesc`, we cap it to `15 bytes` because of #12840.

https://github.com/dotnet/runtime/blob/d20606c23a985a5906324d9eef992c225afb29c8/src/coreclr/jit/emit.h#L887-L896

Further, we account the wrong size of instruction `16 bytes` instead of the one we have in `id->CodeSize()` of `15 bytes`. 

https://github.com/dotnet/runtime/blob/53a1ddc4af2cb7592125aa80e4f812f2a3a3fde3/src/coreclr/jit/emitxarch.cpp#L5596-L5601

Due to this, the `emitCurIGSize` and hence `ig->igOffs` becomes off by 1 byte and during emitting, we think that we just over-estimated the instruction by 4 bytes = 15 (`id->CodeSize()`) - 11 (`actual encoding size`) but the offsets were calculated assuming the instruction size of `16 bytes`. That difference of 1 byte leads to an assert in https://github.com/dotnet/runtime/issues/57041.

To summarize, there are 3 problems:
1. Double counting of REX prefix which happens at multiple places.

This is fixed by tracking if we have already counted REX prefix size and if yes, do not include it in `emitGetPrefixSize()`.

2. Why is `valSize > 4` for RIP-immediate . I have added an assert in this draft PR to see if there are any instructions other than `mov` for which we get `valSize > 4` other wise, we should just update [this code ](https://github.com/dotnet/runtime/blob/53a1ddc4af2cb7592125aa80e4f812f2a3a3fde3/src/coreclr/jit/emitxarch.cpp#L2624-L2628) to cap `valSize` to 4 bytes.

This is fixed by making sure we cap `valSize` to 4 bytes for all instructions except `mov`.

3. There are multiple places that has code like this:
```c++
sz = calculateSize();
id->idCodeSize(sz);
emitCurIGsize += sz; // This can be wrong for sz >= 15.
```

This problem should never arise because I have removed the code that caps `sz` to 15 bytes and added an assert for `sz <= 15`. With that, it will be safe to use `emitCurIGsize += sz`.

Thanks @tannergooding for pointing me to manuals.

Fixes: #12840, #57041

### CODE REVIEW

**Comment by kunalspathak** [comment]
Can someone take a look so we can get this in before next week? @echesakov or @tannergooding

**Review by tannergooding — APPROVED** [review]
Changes LGTM for a quick fix.

We should log an issue to track fixing this properly (likely by centralizing the size computation logic so we don't risk duplicating checks, etc).

**Comment by kunalspathak** [comment]
> We should log an issue to track fixing this properly (likely by centralizing the size computation logic so we don't risk duplicating checks, etc).

Sure, I have created https://github.com/dotnet/runtime/issues/57368 and included links to multiple issues that talks about it.

**Review by briansull — APPROVED** [review]
I reviewed it and it looks OK
(and better than before)

File: src/coreclr/jit/emit.h [hunk 1]
```diff
@@ -884,16 +884,6 @@ class emitter
         }
         void idCodeSize(unsigned sz)
         {
-            if (sz > 15)
```
Comment (echesakovMSFT) [inline src/coreclr/jit/emit.h:887]: Since you are removing the workaround - does it mean we don't overestimate instruction sizes anymore?

**Review by echesakov — APPROVED** [review]
LGTM

File: src/coreclr/jit/emit.h (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/emit.h:887]: Double counting the REX prefix was the only place AFAIK because of which we were overcalculating the instruction size. Other overestimation still exists and I have opened #57368 to track it.

**Comment by kunalspathak** [comment]
no asmdiff in benchmarks/libraries. Minor improvements in coreclr_tests:

```
Summary of Allocation Size diffs:
(Lower is better)

Total bytes of base: 5881
Total bytes of diff: 5852
Total bytes of delta: -29 (-0.49% of base)
Total relative delta: -0.07
    diff is an improvement.
    relative diff is an improvement.


Top file improvements (bytes):
          -8 : 82370.dasm (-0.95% of base)
          -4 : 245861.dasm (-0.82% of base)
          -4 : 247166.dasm (-0.32% of base)
          -4 : 245841.dasm (-0.82% of base)
          -4 : 81148.dasm (-3.96% of base)
          -4 : 247130.dasm (-0.33% of base)
          -1 : 240673.dasm (-0.07% of base)

7 total files with Allocation Size differences (7 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
          -8 (-0.95% of base) : 82370.dasm - ldfldstatic:Main():int
          -4 (-0.82% of base) : 245861.dasm - MyClass:TestStaticFields()
          -4 (-0.32% of base) : 247166.dasm - ShiftTest.ulong32Test:Main():int
          -4 (-0.82% of base) : 245841.dasm - MyClass:TestStaticFields()
          -4 (-3.96% of base) : 81148.dasm - Program:Main():int
          -4 (-0.33% of base) : 247130.dasm - ShiftTest.longTest:Main():int
          -1 (-0.07% of base) : 240673.dasm - AA:Static5(System.Double[],byref,byref,ushort,System.Boolean[][],byref,System.UInt32[][,,],long):System.SByte[,][]

Top method improvements (percentages):
          -4 (-3.96% of base) : 81148.dasm - Program:Main():int
          -8 (-0.95% of base) : 82370.dasm - ldfldstatic:Main():int
          -4 (-0.82% of base) : 245841.dasm - MyClass:TestStaticFields()
          -4 (-0.82% of base) : 245861.dasm - MyClass:TestStaticFields()
          -4 (-0.33% of base) : 247130.dasm - ShiftTest.longTest:Main():int
          -4 (-0.32% of base) : 247166.dasm - ShiftTest.ulong32Test:Main():int
          -1 (-0.07% of base) : 240673.dasm - AA:Static5(System.Double[],byref,byref,ushort,System.Boolean[][],byref,System.UInt32[][,,],long):System.SByte[,][]

7 total methods with Allocation Size differences (7 improved, 0 regressed), 0 unchanged.
```
