### PR TITLE
Fix ROR(x, 32) on arm64

### LINKED ISSUE #102285: Runtime_86027 test fails in jitstress-random
[runtime-coreclr jitstress-random](https://dev.azure.com/dnceng-public/public/_build?definitionId=159&_a=summary) fails in `Runtime_86027` test (arm64):

```
16:05:24.790 Running test: _Runtime_86207::Runtime_86027.TestRotateLeft32()
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   0
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 140
   at Program.<<Main>$>g__TestExecutor360|0_361(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
16:05:25.120 Failed test: _Runtime_86207::Runtime_86027.TestRotateLeft32()
```

## Build Information
Build: 
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Failed test: _Runtime_86207::Runtime_86027.TestRotateLeft32",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 5/15/2024 9:16:45 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/102285

Minimal repro:
```cs
static bool Test(long x) => 
    long.RotateLeft(x, 32) == 3886722753596608508;
```
the previous logic folded `GT_ROR(x, 32)` to `GT_ROR(x, 0)` because it took `parentNode` (which is `(int)GT_EQ`) into account to calculate max rotation width.

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @dotnet/jit-contrib trivial fix

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/lowerarmarch.cpp [hunk 1]
```diff
@@ -313,7 +314,7 @@ bool Lowering::IsContainableUnaryOrBinaryOp(GenTree* parentNode, GenTree* childN
             return false;
         }
 
-        const ssize_t wrapAmount = (static_cast<ssize_t>(genTypeSize(parentNode)) * BITS_PER_BYTE);
+        const ssize_t wrapAmount = (static_cast<ssize_t>(genTypeSize(rotateOpNode)) * BITS_PER_BYTE);
```
Comment (jakobbotsch) [inline src/coreclr/jit/lowerarmarch.cpp:317]: Actually shouldn't this be `childNode`? Can `rotateOpNode` be a small typed local?

Comment (EgorBo) [reply src/coreclr/jit/lowerarmarch.cpp:317]: Correct! x64 also uses `childNode` for it

**Review by tannergooding — APPROVED** [review]
