### PR TITLE
JIT: rely on DFS for cycle entry detection in optRemoveRedundantZeroInits

### LINKED ISSUE #103477: Optimization removes necessary code
### Description

A NativeAOT version of our project fails at runtime while the related managed version works. There are not publishing warnings and static analysis warnings.

The root cause is that the publishing removes some required code. The code is simple without reflection or any similar dynamic techniques.

### Reproduction Steps

Program.cs
```csharp
namespace AotIssue
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string s = "12151";
            int i = 0;

            char? a = null;
            while (true)
            {
                string? res = get(s, ref i, ref a);
                if (res != null)
                {
                    Console.Write(res);
                    a = null; // !!! this line is removed from the published version

                    // Console.Write(a); // uncomment the line for the workaround
                    continue;
                }

                if (i >= s.Length)
                    break;

                a = '.';
            }
        }

        static string? get(string s, ref int index, ref char? a)
        {
            if (index >= s.Length)
                return null;

            if (a == '.')
                return ".";

            a ??= s[index++];
            return (a == '1') ? "1" : null;
        }
    }
}
```

AotIssue.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
</Project>
```

To publish the project, you can use the `dotnet publish -r win-x64 -c Release` command. Or similar publish profile:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net8.0\publish\win-x64\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
</Project>
```

### Expected behavior

The AOT version prints "1.1.1" like regular .NET version.

### Actual behavior

The AOT version prints an infinite sequence of "1111111111111...". The loop never ends.

### Regression?

_No response_

### Known Workarounds

Uncomment the line `Console.Write(a);`. In this case, the code works as expected after publishing.

### Configuration

I reproduced the issue in the .NET 8 project with win-x64 target platform on Windows 10.

### Other information

The line `a = null;` is removed from the published version.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
If a block is DFS ancestor of one of its preds, the block is a cycle entry. Use this instead of `BBF_BACKWARD_JUMP` to stop the scan of blocks when looking for redundant zero inits.

Fixes #103477 (in main).

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

Small number of diffs expected.

**Comment by EgorBo** [comment]
should we leave a comment on `BBF_BACKWARD_JUMP` flag that it's not precise? also, do we want to add the original issue as a test?

**Comment by AndyAyersMS** [comment]
> should we leave a comment on `BBF_BACKWARD_JUMP` flag that it's not precise outside of importer? also, do we want to add the original issue as a test?

It's still used in some other places, we'll need to dig into those. Early enough is ok.

I am trying to adapt the test case above into something that I can add.

File: src/coreclr/jit/optimizer.cpp [hunk 1]
```diff
@@ -5918,10 +5918,33 @@ void Compiler::optRemoveRedundantZeroInits()
...
-         block             = block->GetUniqueSucc())
+    for (BasicBlock* block = fgFirstBB; block != nullptr; block = block->GetUniqueSucc())
     {
-        block->SetFlags(BBF_MARKED);
+        if (m_dfsTree->HasCycle())
+        {
+            // See if this block is a cycle entry
+            //
+            bool stop = false;
+            for (BasicBlock* const pred : block->PredBlocks())
```
Comment (jakobbotsch) [inline src/coreclr/jit/optimizer.cpp:5928]: This could use `BlockPredsWithEH`... It probably doesn't actually matter since we walk forwards with `block->GetUniqueSucc()`, so won't ever end up at a handler, but it would be more consistent with the graph that the DFS tree is constructed over.

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/optimizer.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/optimizer.cpp]: Done... no change in SPMI diffs.

**Comment by AndyAyersMS** [comment]
Some thoughts for follow up:
* do we need to run this opt this early? It should would work better later when we've had a chance to optimize branches
* could this be subsumed by VN dead stores?

**Comment by AndyAyersMS** [comment]
CI errors are known.
