### PR TITLE
[mono][wasm] Pin corlib exceptions after creation.

### LINKED ISSUE #63749: [wasm][aot] Assertion failure - `unexpected GC filler class` in `Microsoft.VisualBasic.Core.Tests`
Hit on [rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1550401&view=logs&j=c24b3bf0-34d4-58dc-62fd-621ef62beaf8&t=57689805-9064-5d56-984a-6ae89a8efb73), [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b9e7b279caf2452788/normal-System.Runtime.Numerics.Tests/1/console.4c14c6af.log?sv=2019-07-07&se=2022-02-02T08%3A16%3A13Z&sr=c&sp=rl&sig=%2BeeaSe0%2B4XKfJWaXrbFz4VCHglkX2uoTYEK7uTjdfEk%3D)

```
 ==== JS stack trace =========================================
 
 Security context: 0x03f3081d0a8d <JSObject>#0#
     0: builtin exit frame: trace(this=0x03f3081c5d29 <console map = 000003F308202911>#1#,0x03f3081c5d29 <console map = 000003F308202911>#1#,0x03f3080b96a9 <String[106]: c"* Assertion at D:/a/_work/1/s/src/mono/mono/metadata/class-accessors.c:86, condition `<disabled>' not met\n">)
 
     1: mono_wasm_trace_logger [000003F308313345] [./dotnet.js:3] [bytecode=000003F308CF0831 offset=135](this=0x03f308305dd1 <Object map = 000003F308209559>#2#,0,3507126,113046584,4,0)
     2: _mono_wasm_trace_logger [000003F30830320D] [./dotnet.js:6191] [bytecode=000003F3082D1585 offset=25](this=0x03f3081c33f9 <JSGlobal Object>#3#)
     3: WasmToJsFrame [pc: 000001B19E2311B4]
     4: WASM [wasm://wasm/0826337e], function #71031 ('wasm_trace_logger'), pc=000001B19E435BBA (+0x3a), pos=15107908 (+11)
     5: WASM [wasm://wasm/0826337e], function #59270 ('eglib_log_adapter'), pc=000001B19E81D8B2 (+0x92), pos=13687910 (+34)
     6: WASM [wasm://wasm/0826337e], function #70246 ('monoeg_g_logstr'), pc=000001B19E479860 (+0x80), pos=15000330 (+47)
     7: WASM [wasm://wasm/0826337e], function #70244 ('monoeg_g_logv_nofree'), pc=000001B19E47999F (+0x7f), pos=15000249 (+64)
     8: WASM [wasm://wasm/0826337e], function #70249 ('monoeg_assertion_message'), pc=000001B19E479607 (+0x47), pos=15000457 (+32)
     9: WASM [wasm://wasm/0826337e], function #70251 ('mono_assertion_message'), pc=000001B19E4794E5 (+0x45), pos=15000528 (+40)
    10: WASM [wasm://wasm/0826337e], function #70250 ('mono_assertion_message_disabled'), pc=000001B19E479562 (+0x22), pos=15000481 (+10)
    11: WASM [wasm://wasm/0826337e], function #53935 ('mono_class_get_flags'), pc=000001B19E99F40E (+0xee), pos=13146033 (+169)
    12: WASM [wasm://wasm/0826337e], function #53838 ('mono_class_init_internal'), pc=000001B19E9AE1FB (+0x4db), pos=13122097 (+688)
    13: WASM [wasm://wasm/0826337e], function #53746 ('mono_class_is_assignable_from_general'), pc=000001B19E9B707F (+0x9f), pos=13108852 (+59)
    14: WASM [wasm://wasm/0826337e], function #53745 ('mono_class_is_assignable_from_checked'), pc=000001B19E9B7B88 (+0x28), pos=13108786 (+11)
    15: WASM [wasm://wasm/0826337e], function #53742 ('mono_class_is_assignable_from_internal'), pc=000001B19E9B8009 (+0x49), pos=13108367 (+37)
    16: WASM [wasm://wasm/0826337e], function #57878 ('mono_object_handle_isinst'), pc=000001B19E8825BA (+0xba), pos=13544773 (+89)
    17: WASM [wasm://wasm/0826337e], function #57880 ('mono_object_isinst_checked'), pc=000001B19E882367 (+0xa7), pos=13544946 (+73)
    18: WASM [wasm://wasm/0826337e], function #69473 ('handle_exception_first_pass'), pc=000001B19E4B4BE0 (+0xd20), pos=14918263 (+1270)
    19: WASM [wasm://wasm/0826337e], function #69467 ('mono_handle_exception_internal'), pc=000001B19E4B615C (+0xabc), pos=14914680 (+1355)
    20: WASM [wasm://wasm/0826337e], function #69429 ('mono_handle_exception'), pc=000001B19E4BB558 (+0x38), pos=14907946 (+11)
    21: WASM [wasm://wasm/0826337e], function #69427 ('mono_llvm_throw_exception'), pc=000001B19E4BB646 (+0x66), pos=14907906 (+68)
    22: WASM [wasm://wasm/0826337e], function #69493 ('mono_llvm_throw_corlib_exception'), pc=000001B19E4B2CCA (+0x4a), pos=14920466 (+25)
    23: WASM [wasm://wasm/0826337e], function #38204 ('System_Runtime_Numerics_System_Numerics_BigIntegerCalculator_Div'), pc=000001B19C6DD08B (+0x1ab), pos=9227728 (+173)
    24: WASM [wasm://wasm/0826337e], function #38326 ('System_Runtime_Numerics_System_Numerics_BigInteger_DivRem_System'), pc=000001B19C6B84BE (+0x1b5e), pos=9276464 (+2895)
    25: WASM [wasm://wasm/0826337e], function #39983 ('System_Runtime_Numerics_Tests_System_Numerics_Tests_StackCalc_Do'), pc=000001B19C5165BF (+0x13bf), pos=9994772 (+1975)
    26: WASM [wasm://wasm/0826337e], function #39361 ('System_Runtime_Numerics_Tests_System_Numerics_Tests_StackCalc_Do'), pc=000001B19C613F97 (+0xb37), pos=9473218 (+1008)
    27: WASM [wasm://wasm/0826337e], function #31059 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_u1_this_'), pc=000001B19CA41352 (+0x92), pos=8220240 (+15)
    28: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C3B (+0x13b), pos=12936523 (+94)
    29: JsToWasmFrame [pc: 000003F3002066BB]
    30: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9974960)
    31: WasmToJsFrame [pc: 000001B19E22D87D]
    32: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
    33: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
    34: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25FBCD (+0x1050d), pos=12877891 (+5244)
    35: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
    36: WASM [wasm://wasm/0826337e], function #52990 ('interp_entry_static_ret_1'), pc=000001B19EA0E2BA (+0x5a), pos=12940024 (+50)
    37: WASM [wasm://wasm/0826337e], function #31460 ('corlib_aot_wrapper_gsharedvt_in_sig_obj_obj'), pc=000001B19CA24536 (+0xb6), pos=8246805 (+60)
    38: WASM [wasm://wasm/0826337e], function #44957 ('xunit_assert_Xunit_Assert_RecordException_System_Action'), pc=000001B19C1FD41B (+0xfb), pos=11216808 (+74)
    39: WASM [wasm://wasm/0826337e], function #44956 ('xunit_assert_Xunit_Assert_Throws_T_REF_System_Action'), pc=000001B19C1FD578 (+0xd8), pos=11216624 (+83)
    40: WASM [wasm://wasm/0826337e], function #39582 ('System_Runtime_Numerics_Tests_System_Numerics_Tests_divremTest_R'), pc=000001B19C596A72 (+0x912), pos=9699842 (+1124)
    41: WASM [wasm://wasm/0826337e], function #31125 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_void_'), pc=000001B19CA3C564 (+0x84), pos=8223853 (+11)
    42: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10BA2 (+0xa2), pos=12936765 (+336)
    43: JsToWasmFrame [pc: 000003F3002066BB]
    44: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9975888)
    45: WasmToJsFrame [pc: 000001B19E22D87D]
    46: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
    47: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
    48: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25FBCD (+0x1050d), pos=12877891 (+5244)
    49: WASM [wasm://wasm/0826337e], function #52832 ('interp_runtime_invoke'), pc=000001B19EA1B58A (+0x1ca), pos=12872581 (+247)
    50: WASM [wasm://wasm/0826337e], function #69040 ('mono_jit_runtime_invoke'), pc=000001B19E4E5AAC (+0x52c), pos=14840609 (+627)
    51: WASM [wasm://wasm/0826337e], function #57670 ('do_runtime_invoke'), pc=000001B19E89303B (+0xdb), pos=13520841 (+53)
    52: WASM [wasm://wasm/0826337e], function #57668 ('mono_runtime_invoke_checked'), pc=000001B19E8931D5 (+0x55), pos=13520753 (+40)
    53: WASM [wasm://wasm/0826337e], function #57828 ('mono_runtime_try_invoke_span'), pc=000001B19E88656A (+0x54a), pos=13539100 (+604)
    54: WASM [wasm://wasm/0826337e], function #57829 ('mono_runtime_invoke_span_checked'), pc=000001B19E885FD4 (+0x34), pos=13539593 (+18)
    55: WASM [wasm://wasm/0826337e], function #56499 ('ves_icall_InternalInvoke'), pc=000001B19E8F385F (+0x6bf), pos=13382583 (+813)
    56: WASM [wasm://wasm/0826337e], function #56648 ('ves_icall_InternalInvoke_raw'), pc=000001B19E8E5D49 (+0xa9), pos=13402743 (+71)
    57: WASM [wasm://wasm/0826337e], function #52944 ('do_icall'), pc=000001B19EA1242A (+0x4ca), pos=12934848 (+254)
    58: WASM [wasm://wasm/0826337e], function #52901 ('do_icall_wrapper'), pc=000001B19EA152BD (+0xfd), pos=12931336 (+276)
    59: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25F4F2 (+0xfe32), pos=12876986 (+4339)
    60: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
    61: WASM [wasm://wasm/0826337e], function #52974 ('interp_entry_instance_ret_3'), pc=000001B19EA0F244 (+0x64), pos=12938706 (+64)
    62: WASM [wasm://wasm/0826337e], function #32817 ('corlib_aot_wrapper_gsharedvt_in_sig_obj_this_obji4cl26_Mono_dVal'), pc=000001B19C9A8539 (+0xf9), pos=8354632 (+76)
    63: WASM [wasm://wasm/0826337e], function #25898 ('corlib_System_Reflection_RuntimeMethodInfo_InvokeWorker_object_S'), pc=000001B19CD3A225 (+0x165), pos=7202318 (+109)
    64: WASM [wasm://wasm/0826337e], function #25923 ('corlib_System_Reflection_RuntimeMethodInfo_Invoke_object_System_'), pc=000001B19CD336F3 (+0x373), pos=7211901 (+374)
    65: WASM [wasm://wasm/0826337e], function #46507 ('xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_Cal'), pc=000001B19C0E78E4 (+0x1a4), pos=11561640 (+192)
    66: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
    67: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C90 (+0x190), pos=12936547 (+118)
    68: JsToWasmFrame [pc: 000003F3002066BB]
    69: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9976976)
    70: WasmToJsFrame [pc: 000001B19E22D87D]
    71: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
    72: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
    73: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
    74: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
    75: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
    76: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
    77: WASM [wasm://wasm/0826337e], function #46521 ('xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1__c__DisplayClass4'), pc=000001B19C0E5750 (+0x110), pos=11564532 (+83)
    78: WASM [wasm://wasm/0826337e], function #48772 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF70E01 (+0x5e1), pos=12016170 (+792)
    79: WASM [wasm://wasm/0826337e], function #31479 ('corlib_aot_wrapper_gsharedvt_out_sig_void_bii'), pc=000001B19CA22E00 (+0x80), pos=8247864 (+13)
    80: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10BEE (+0xee), pos=12936504 (+75)
    81: JsToWasmFrame [pc: 000003F3002066BB]
    82: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9977696)
    83: WasmToJsFrame [pc: 000001B19E22D87D]
    84: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
    85: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
    86: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25FBCD (+0x1050d), pos=12877891 (+5244)
    87: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
    88: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
    89: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
    90: WASM [wasm://wasm/0826337e], function #46351 ('xunit_execution_dotnet_Xunit_Sdk_ExecutionTimer__AggregateAsyncd'), pc=000001B19C0F9978 (+0xf8), pos=11537728 (+73)
    91: WASM [wasm://wasm/0826337e], function #48298 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BFB747E (+0x31e), pos=11931409 (+410)
    92: WASM [wasm://wasm/0826337e], function #46349 ('xunit_execution_dotnet_Xunit_Sdk_ExecutionTimer_AggregateAsync_S'), pc=000001B19C0F9BC6 (+0x186), pos=11537549 (+163)
    93: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
    94: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C90 (+0x190), pos=12936547 (+118)
    95: JsToWasmFrame [pc: 000003F3002066BB]
    96: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9978496)
    97: WasmToJsFrame [pc: 000001B19E22D87D]
    98: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
    99: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   100: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25FBCD (+0x1050d), pos=12877891 (+5244)
   101: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   102: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   103: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   104: WASM [wasm://wasm/0826337e], function #45680 ('xunit_core_Xunit_Sdk_ExceptionAggregator__RunAsyncd__9_MoveNext'), pc=000001B19C17B8F8 (+0xf8), pos=11375678 (+73)
   105: WASM [wasm://wasm/0826337e], function #45933 ('xunit_core_System_Runtime_CompilerServices_AsyncMethodBuilderCor'), pc=000001B19C14B0CF (+0x30f), pos=11433660 (+407)
   106: WASM [wasm://wasm/0826337e], function #45677 ('xunit_core_Xunit_Sdk_ExceptionAggregator_RunAsync_System_Func_1_'), pc=000001B19C17C366 (+0x186), pos=11374755 (+163)
   107: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
   108: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C90 (+0x190), pos=12936547 (+118)
   109: JsToWasmFrame [pc: 000003F3002066BB]
   110: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9979312)
   111: WasmToJsFrame [pc: 000001B19E22D87D]
   112: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   113: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   114: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25FBCD (+0x1050d), pos=12877891 (+5244)
   115: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   116: WASM [wasm://wasm/0826337e], function #52963 ('interp_entry_instance_1'), pc=000001B19EA0FD3A (+0x5a), pos=12937792 (+50)
   117: WASM [wasm://wasm/0826337e], function #32620 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_bii'), pc=000001B19C9BB312 (+0x92), pos=8336381 (+15)
   118: WASM [wasm://wasm/0826337e], function #46510 ('xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_Inv'), pc=000001B19C0E7096 (+0x236), pos=11562359 (+271)
   119: WASM [wasm://wasm/0826337e], function #46711 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestInvoker_InvokeTestMeth'), pc=000001B19C0CAB10 (+0xa30), pos=11597621 (+877)
   120: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
   121: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C90 (+0x190), pos=12936547 (+118)
   122: JsToWasmFrame [pc: 000003F3002066BB]
   123: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9980144)
   124: WasmToJsFrame [pc: 000001B19E22D87D]
   125: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   126: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   127: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   128: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   129: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   130: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   131: WASM [wasm://wasm/0826337e], function #48333 ('xunit_execution_dotnet_Xunit_Sdk_ExceptionAggregator__RunAsyncd_'), pc=000001B19BFB2DB8 (+0xf8), pos=11936467 (+73)
   132: WASM [wasm://wasm/0826337e], function #48771 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF7162F (+0x30f), pos=12015030 (+407)
   133: WASM [wasm://wasm/0826337e], function #48332 ('xunit_execution_dotnet_Xunit_Sdk_ExceptionAggregator_RunAsync_Sy'), pc=000001B19BFB2FA6 (+0x186), pos=11936292 (+163)
   134: WASM [wasm://wasm/0826337e], function #46509 ('xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_Run'), pc=000001B19C0E74C3 (+0x283), pos=11562061 (+281)
   135: WASM [wasm://wasm/0826337e], function #46726 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestMetho'), pc=000001B19C0C896D (+0x1cd), pos=11599556 (+219)
   136: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
   137: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C90 (+0x190), pos=12936547 (+118)
   138: JsToWasmFrame [pc: 000003F3002066BB]
   139: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9981104)
   140: WasmToJsFrame [pc: 000001B19E22D87D]
   141: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   142: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   143: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   144: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   145: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   146: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   147: WASM [wasm://wasm/0826337e], function #46727 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner__InvokeTestAsyn'), pc=000001B19C0C8738 (+0xf8), pos=11599656 (+73)
   148: WASM [wasm://wasm/0826337e], function #48376 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BFAB2AC (+0x32c), pos=11946906 (+420)
   149: WASM [wasm://wasm/0826337e], function #46725 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestAsync'), pc=000001B19C0C8BBE (+0x17e), pos=11599234 (+168)
   150: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
   151: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C90 (+0x190), pos=12936547 (+118)
   152: JsToWasmFrame [pc: 000003F3002066BB]
   153: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9981888)
   154: WasmToJsFrame [pc: 000001B19E22D87D]
   155: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   156: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   157: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   158: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   159: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   160: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   161: WASM [wasm://wasm/0826337e], function #45684 ('xunit_core_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_T_REF_'), pc=000001B19C17B55B (+0x11b), pos=11375902 (+95)
   162: WASM [wasm://wasm/0826337e], function #46063 ('xunit_core_System_Runtime_CompilerServices_AsyncMethodBuilderCor'), pc=000001B19C13E801 (+0x5e1), pos=11447231 (+792)
   163: WASM [wasm://wasm/0826337e], function #45936 ('xunit_core_System_Runtime_CompilerServices_AsyncTaskMethodBuilde'), pc=000001B19C14A9D4 (+0x1b4), pos=11434436 (+135)
   164: WASM [wasm://wasm/0826337e], function #45678 ('xunit_core_Xunit_Sdk_ExceptionAggregator_RunAsync_T_REF_System_F'), pc=000001B19C17BFA3 (+0x283), pos=11375116 (+258)
   165: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
   166: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C90 (+0x190), pos=12936547 (+118)
   167: JsToWasmFrame [pc: 000003F3002066BB]
   168: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9982704)
   169: WasmToJsFrame [pc: 000001B19E22D87D]
   170: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   171: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   172: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25FBCD (+0x1050d), pos=12877891 (+5244)
   173: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   174: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   175: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   176: WASM [wasm://wasm/0826337e], function #46582 ('xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__RunAsyncd__43_TTe'), pc=000001B19C0E0B70 (+0x110), pos=11570656 (+83)
   177: WASM [wasm://wasm/0826337e], function #48775 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF6EE03 (+0x563), pos=12019359 (+675)
   178: WASM [wasm://wasm/0826337e], function #48347 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB1BF4 (+0x1b4), pos=11937569 (+135)
   179: WASM [wasm://wasm/0826337e], function #46579 ('xunit_execution_dotnet_Xunit_Sdk_TestRunner_1_TTestCase_REF_RunA'), pc=000001B19C0E1125 (+0x2a5), pos=11570314 (+320)
   180: WASM [wasm://wasm/0826337e], function #46635 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestCaseRunner_RunTestAsyn'), pc=000001B19C0D9D2F (+0x4af), pos=11578922 (+450)
   181: WASM [wasm://wasm/0826337e], function #31071 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_'), pc=000001B19CA40481 (+0xa1), pos=8220881 (+26)
   182: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C3B (+0x13b), pos=12936523 (+94)
   183: JsToWasmFrame [pc: 000003F3002066BB]
   184: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9983696)
   185: WasmToJsFrame [pc: 000001B19E22D87D]
   186: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   187: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   188: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   189: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   190: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   191: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   192: WASM [wasm://wasm/0826337e], function #46415 ('xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1__RunAsyncd__19'), pc=000001B19C0F1610 (+0x110), pos=11548396 (+83)
   193: WASM [wasm://wasm/0826337e], function #48766 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF74814 (+0x534), pos=12010229 (+651)
   194: WASM [wasm://wasm/0826337e], function #48313 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB5854 (+0x1b4), pos=11933547 (+135)
   195: WASM [wasm://wasm/0826337e], function #46343 ('xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1_TTestCase_REF_'), pc=000001B19C0FB0B2 (+0x292), pos=11536138 (+309)
   196: WASM [wasm://wasm/0826337e], function #46959 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestCase_RunAsync_Xunit_Ab'), pc=000001B19C0A0A88 (+0x468), pos=11646437 (+401)
   197: WASM [wasm://wasm/0826337e], function #46723 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestMethodRunner_RunTestCa'), pc=000001B19C0C90D5 (+0x2d5), pos=11598993 (+236)
   198: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
   199: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C90 (+0x190), pos=12936547 (+118)
   200: JsToWasmFrame [pc: 000003F3002066BB]
   201: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9984640)
   202: WasmToJsFrame [pc: 000001B19E22D87D]
   203: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   204: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   205: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   206: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   207: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   208: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   209: WASM [wasm://wasm/0826337e], function #46554 ('xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunTestCase'), pc=000001B19C0E3050 (+0x110), pos=11567573 (+83)
   210: WASM [wasm://wasm/0826337e], function #48774 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF6F843 (+0x563), pos=12018335 (+675)
   211: WASM [wasm://wasm/0826337e], function #48344 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB2114 (+0x1b4), pos=11937249 (+135)
   212: WASM [wasm://wasm/0826337e], function #46549 ('xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_RE'), pc=000001B19C0E3725 (+0x2a5), pos=11567192 (+320)
   213: WASM [wasm://wasm/0826337e], function #31071 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_'), pc=000001B19CA40481 (+0xa1), pos=8220881 (+26)
   214: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C3B (+0x13b), pos=12936523 (+94)
   215: JsToWasmFrame [pc: 000003F3002066BB]
   216: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9985472)
   217: WasmToJsFrame [pc: 000001B19E22D87D]
   218: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   219: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   220: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   221: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   222: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   223: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   224: WASM [wasm://wasm/0826337e], function #46550 ('xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunAsyncd__'), pc=000001B19C0E3410 (+0x110), pos=11567359 (+83)
   225: WASM [wasm://wasm/0826337e], function #48773 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF70301 (+0x5e1), pos=12017311 (+792)
   226: WASM [wasm://wasm/0826337e], function #48342 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB2374 (+0x1b4), pos=11937092 (+135)
   227: WASM [wasm://wasm/0826337e], function #46548 ('xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_RE'), pc=000001B19C0E3B71 (+0x291), pos=11566788 (+309)
   228: WASM [wasm://wasm/0826337e], function #46644 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestClassRunner_RunTestMet'), pc=000001B19C0D691A (+0x29a), pos=11583137 (+246)
   229: WASM [wasm://wasm/0826337e], function #31720 ('corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobjobjobj'), pc=000001B19CA08FBB (+0x11b), pos=8272249 (+82)
   230: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10DAD (+0x2ad), pos=12936649 (+220)
   231: JsToWasmFrame [pc: 000003F3002066BB]
   232: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9986368)
   233: WasmToJsFrame [pc: 000001B19E22D87D]
   234: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   235: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   236: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   237: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   238: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   239: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   240: WASM [wasm://wasm/0826337e], function #46453 ('xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunTestMetho'), pc=000001B19C0EC6BB (+0x11b), pos=11555090 (+95)
   241: WASM [wasm://wasm/0826337e], function #48768 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF73423 (+0x563), pos=12012251 (+675)
   242: WASM [wasm://wasm/0826337e], function #48320 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB4DD4 (+0x1b4), pos=11934217 (+135)
   243: WASM [wasm://wasm/0826337e], function #46441 ('xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF'), pc=000001B19C0EEC26 (+0x2a6), pos=11552243 (+320)
   244: WASM [wasm://wasm/0826337e], function #31071 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_'), pc=000001B19CA40481 (+0xa1), pos=8220881 (+26)
   245: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C3B (+0x13b), pos=12936523 (+94)
   246: JsToWasmFrame [pc: 000003F3002066BB]
   247: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9987264)
   248: WasmToJsFrame [pc: 000001B19E22D87D]
   249: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   250: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   251: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   252: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   253: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   254: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   255: WASM [wasm://wasm/0826337e], function #46449 ('xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunAsyncd__3'), pc=000001B19C0ECA70 (+0x110), pos=11554864 (+83)
   256: WASM [wasm://wasm/0826337e], function #48767 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF73E34 (+0x534), pos=12011228 (+651)
   257: WASM [wasm://wasm/0826337e], function #48318 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB5034 (+0x1b4), pos=11934060 (+135)
   258: WASM [wasm://wasm/0826337e], function #46440 ('xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF'), pc=000001B19C0EF072 (+0x292), pos=11551839 (+309)
   259: WASM [wasm://wasm/0826337e], function #46683 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestCollectionRunner_RunTe'), pc=000001B19C0CECA5 (+0x265), pos=11592365 (+251)
   260: WASM [wasm://wasm/0826337e], function #31717 ('corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobjobj'), pc=000001B19CA0954A (+0xea), pos=8271851 (+68)
   261: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10D47 (+0x247), pos=12936610 (+181)
   262: JsToWasmFrame [pc: 000003F3002066BB]
   263: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9988144)
   264: WasmToJsFrame [pc: 000001B19E22D87D]
   265: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   266: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   267: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   268: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   269: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   270: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   271: WASM [wasm://wasm/0826337e], function #46481 ('xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunTest'), pc=000001B19C0EA070 (+0x110), pos=11558207 (+83)
   272: WASM [wasm://wasm/0826337e], function #48770 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF72003 (+0x563), pos=12014274 (+675)
   273: WASM [wasm://wasm/0826337e], function #48329 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB3554 (+0x1b4), pos=11935949 (+135)
   274: WASM [wasm://wasm/0826337e], function #46473 ('xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCas'), pc=000001B19C0EADC5 (+0x2a5), pos=11557361 (+320)
   275: WASM [wasm://wasm/0826337e], function #31071 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_'), pc=000001B19CA40481 (+0xa1), pos=8220881 (+26)
   276: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10C3B (+0x13b), pos=12936523 (+94)
   277: JsToWasmFrame [pc: 000003F3002066BB]
   278: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9988976)
   279: WasmToJsFrame [pc: 000001B19E22D87D]
   280: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   281: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   282: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19E25EDF6 (+0xf736), pos=12877560 (+4913)
   283: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19EA166DC (+0x39c), pos=12929523 (+471)
   284: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19EA0FDEE (+0x4e), pos=12937728 (+43)
   285: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   286: WASM [wasm://wasm/0826337e], function #46474 ('xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunAsyn'), pc=000001B19C0EAAB0 (+0x110), pos=11557528 (+83)
   287: WASM [wasm://wasm/0826337e], function #48769 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF72A14 (+0x534), pos=12013251 (+651)
   288: WASM [wasm://wasm/0826337e], function #48327 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB37B4 (+0x1b4), pos=11935792 (+135)
   289: WASM [wasm://wasm/0826337e], function #46472 ('xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCas'), pc=000001B19C0EB212 (+0x292), pos=11556957 (+309)
   290: WASM [wasm://wasm/0826337e], function #46598 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTest'), pc=000001B19C0DE7BD (+0x25d), pos=11573358 (+214)
   291: WASM [wasm://wasm/0826337e], function #31720 ('corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobjobjobj'), pc=000001B19CA08FBB (+0x11b), pos=8272249 (+82)
   292: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19EA10DAD (+0x2ad), pos=12936649 (+220)
   293: JsToWasmFrame [pc: 000003F3002066BB]
   294: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9989872)
   295: WasmToJsFrame [pc: 000001B19E22D87D]
   296: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19E485977 (+0x57), pos=14976321 (+22)
   297: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19EA146B9 (+0x2b9), pos=12932514 (+396)
   298: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B03A (+0x411a), pos=12877560 (+4913)
   299: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   300: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   301: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   302: WASM [wasm://wasm/0826337e], function #46401 ('xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunTestCo'), pc=000001B19C0F2290 (+0x110), pos=11547404 (+83)
   303: WASM [wasm://wasm/0826337e], function #48764 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF77121 (+0x5c1), pos=12006519 (+722)
   304: WASM [wasm://wasm/0826337e], function #48305 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB6814 (+0x1b4), pos=11932466 (+135)
   305: WASM [wasm://wasm/0826337e], function #46389 ('xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_'), pc=000001B19C0F3E22 (+0x342), pos=11545492 (+395)
   306: WASM [wasm://wasm/0826337e], function #46600 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__n__0_X'), pc=000001B19C0DE221 (+0x61), pos=11573660 (+36)
   307: WASM [wasm://wasm/0826337e], function #31556 ('corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobj'), pc=000001B19CA1B42F (+0xcf), pos=8254829 (+54)
   308: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB90B4 (+0x2d4), pos=12936576 (+147)
   309: JsToWasmFrame [pc: 000003F3002066BB]
   310: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9990832)
   311: WasmToJsFrame [pc: 000001B19E22D87D]
   312: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   313: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   314: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B2BA (+0x439a), pos=12877891 (+5244)
   315: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   316: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   317: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   318: WASM [wasm://wasm/0826337e], function #46612 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__RunTes'), pc=000001B19C0DD258 (+0xf8), pos=11574823 (+73)
   319: WASM [wasm://wasm/0826337e], function #48351 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BFB12BF (+0x33f), pos=11938159 (+413)
   320: WASM [wasm://wasm/0826337e], function #46597 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTest'), pc=000001B19C0DEA4C (+0x1ac), pos=11573040 (+188)
   321: WASM [wasm://wasm/0826337e], function #31556 ('corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobj'), pc=000001B19CA1B42F (+0xcf), pos=8254829 (+54)
   322: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB90B4 (+0x2d4), pos=12936576 (+147)
   323: JsToWasmFrame [pc: 000003F3002066BB]
   324: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9991712)
   325: WasmToJsFrame [pc: 000001B19E22D87D]
   326: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   327: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   328: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B03A (+0x411a), pos=12877560 (+4913)
   329: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   330: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   331: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   332: WASM [wasm://wasm/0826337e], function #46397 ('xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunAsyncd'), pc=000001B19C0F2650 (+0x110), pos=11547190 (+83)
   333: WASM [wasm://wasm/0826337e], function #48763 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BF77BCC (+0x58c), pos=12005443 (+697)
   334: WASM [wasm://wasm/0826337e], function #48303 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTask'), pc=000001B19BFB6A74 (+0x1b4), pos=11932309 (+135)
   335: WASM [wasm://wasm/0826337e], function #46388 ('xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_'), pc=000001B19C0F42AC (+0x2ac), pos=11545012 (+327)
   336: WASM [wasm://wasm/0826337e], function #31071 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_'), pc=000001B19CA40481 (+0xa1), pos=8220881 (+26)
   337: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB8FAC (+0x1cc), pos=12936523 (+94)
   338: JsToWasmFrame [pc: 000003F3002066BB]
   339: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9992592)
   340: WasmToJsFrame [pc: 000001B19E22D87D]
   341: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   342: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   343: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B2BA (+0x439a), pos=12877891 (+5244)
   344: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   345: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   346: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   347: WASM [wasm://wasm/0826337e], function #46987 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor__Run'), pc=000001B19C095A18 (+0xf8), pos=11658785 (+73)
   348: WASM [wasm://wasm/0826337e], function #48412 ('xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMeth'), pc=000001B19BFA64DB (+0x33b), pos=11952775 (+430)
   349: WASM [wasm://wasm/0826337e], function #46985 ('xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor_RunT'), pc=000001B19C095E9D (+0x27d), pos=11658548 (+279)
   350: WASM [wasm://wasm/0826337e], function #46859 ('xunit_execution_dotnet_Xunit_Sdk_TestFrameworkExecutor_1_TTestCa'), pc=000001B19C0B3E5D (+0x3fd), pos=11624389 (+399)
   351: WASM [wasm://wasm/0826337e], function #49351 ('xunit_runner_utility_netcoreapp10_Xunit_Xunit2_RunTests_System_C'), pc=000001B19BF1AB98 (+0x238), pos=12118902 (+157)
   352: WASM [wasm://wasm/0826337e], function #49088 ('xunit_runner_utility_netcoreapp10_TestFrameworkExtensions_RunTes'), pc=000001B19BF3AB18 (+0x338), pos=12081622 (+384)
   353: WASM [wasm://wasm/0826337e], function #32605 ('corlib_aot_wrapper_gsharedvt_out_sig_void_objobjobjobj'), pc=000001B19C9BC764 (+0xe4), pos=8335308 (+78)
   354: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB90B4 (+0x2d4), pos=12936576 (+147)
   355: JsToWasmFrame [pc: 000003F3002066BB]
   356: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9993584)
   357: WasmToJsFrame [pc: 000001B19E22D87D]
   358: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   359: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   360: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B2BA (+0x439a), pos=12877891 (+5244)
   361: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   362: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   363: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   364: WASM [wasm://wasm/0826337e], function #431 ('Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHa'), pc=000001B19E1FC0F8 (+0xf8), pos=294366 (+71)
   365: WASM [wasm://wasm/0826337e], function #628 ('Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_Compi'), pc=000001B19E1D3913 (+0x373), pos=343216 (+453)
   366: WASM [wasm://wasm/0826337e], function #413 ('Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHa'), pc=000001B19E2016B3 (+0x1b3), pos=288307 (+193)
   367: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
   368: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB902E (+0x24e), pos=12936547 (+118)
   369: JsToWasmFrame [pc: 000003F3000B4A95]
   370: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9994560)
   371: WasmToJsFrame [pc: 000001B19E22D87D]
   372: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   373: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   374: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B03A (+0x411a), pos=12877560 (+4913)
   375: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   376: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   377: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   378: WASM [wasm://wasm/0826337e], function #135 ('Microsoft_DotNet_XHarness_TestRunners_Common_Microsoft_DotNet_XH'), pc=000001B19E22ABB8 (+0xf8), pos=242620 (+69)
   379: WASM [wasm://wasm/0826337e], function #304 ('Microsoft_DotNet_XHarness_TestRunners_Common_System_Runtime_Comp'), pc=000001B19E2122B6 (+0x356), pos=268808 (+431)
   380: WASM [wasm://wasm/0826337e], function #128 ('Microsoft_DotNet_XHarness_TestRunners_Common_Microsoft_DotNet_XH'), pc=000001B19E22B592 (+0x192), pos=241903 (+173)
   381: WASM [wasm://wasm/0826337e], function #31145 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj'), pc=000001B19CA3AB1B (+0xbb), pos=8225074 (+40)
   382: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB902E (+0x24e), pos=12936547 (+118)
   383: JsToWasmFrame [pc: 000003F3000B4A95]
   384: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9995520)
   385: WasmToJsFrame [pc: 000001B19E22D87D]
   386: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   387: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   388: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B2BA (+0x439a), pos=12877891 (+5244)
   389: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   390: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   391: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   392: WASM [wasm://wasm/0826337e], function #139 ('Microsoft_DotNet_XHarness_TestRunners_Common_Microsoft_DotNet_XH'), pc=000001B19E22A818 (+0xf8), pos=242812 (+69)
   393: WASM [wasm://wasm/0826337e], function #306 ('Microsoft_DotNet_XHarness_TestRunners_Common_System_Runtime_Comp'), pc=000001B19E2119AD (+0x32d), pos=269646 (+416)
   394: WASM [wasm://wasm/0826337e], function #129 ('Microsoft_DotNet_XHarness_TestRunners_Common_Microsoft_DotNet_XH'), pc=000001B19E22B230 (+0x1f0), pos=242236 (+230)
   395: WASM [wasm://wasm/0826337e], function #31717 ('corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobjobj'), pc=000001B19CA0954A (+0xea), pos=8271851 (+68)
   396: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB9153 (+0x373), pos=12936610 (+181)
   397: JsToWasmFrame [pc: 000003F3000B4A95]
   398: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9996336)
   399: WasmToJsFrame [pc: 000001B19E22D87D]
   400: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   401: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   402: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B2BA (+0x439a), pos=12877891 (+5244)
   403: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   404: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   405: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   406: WASM [wasm://wasm/0826337e], function #238 ('Microsoft_DotNet_XHarness_TestRunners_Common_Microsoft_DotNet_XH'), pc=000001B19E220AB8 (+0xf8), pos=251164 (+69)
   407: WASM [wasm://wasm/0826337e], function #354 ('Microsoft_DotNet_XHarness_TestRunners_Common_System_Runtime_Comp'), pc=000001B19E20C661 (+0x301), pos=275486 (+393)
   408: WASM [wasm://wasm/0826337e], function #233 ('Microsoft_DotNet_XHarness_TestRunners_Common_Microsoft_DotNet_XH'), pc=000001B19E220EE6 (+0x126), pos=250877 (+116)
   409: WASM [wasm://wasm/0826337e], function #31071 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_'), pc=000001B19CA40481 (+0xa1), pos=8220881 (+26)
   410: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB8FAC (+0x1cc), pos=12936523 (+94)
   411: JsToWasmFrame [pc: 000003F3000B4A95]
   412: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9997088)
   413: WasmToJsFrame [pc: 000001B19E22D87D]
   414: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   415: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   416: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B03A (+0x411a), pos=12877560 (+4913)
   417: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   418: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   419: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   420: WASM [wasm://wasm/0826337e], function #456 ('Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHa'), pc=000001B19E1F63B8 (+0xf8), pos=301251 (+71)
   421: WASM [wasm://wasm/0826337e], function #727 ('Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_Compi'), pc=000001B19E1C9861 (+0x301), pos=353534 (+395)
   422: WASM [wasm://wasm/0826337e], function #454 ('Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHa'), pc=000001B19E1F69A6 (+0x126), pos=300590 (+118)
   423: WASM [wasm://wasm/0826337e], function #31071 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_'), pc=000001B19CA40481 (+0xa1), pos=8220881 (+26)
   424: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB8FAC (+0x1cc), pos=12936523 (+94)
   425: JsToWasmFrame [pc: 000003F3000B4A95]
   426: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9997840)
   427: WasmToJsFrame [pc: 000001B19E22D87D]
   428: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   429: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   430: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B2BA (+0x439a), pos=12877891 (+5244)
   431: WASM [wasm://wasm/0826337e], function #52885 ('interp_entry'), pc=000001B19BCBF3A2 (+0x3a2), pos=12929523 (+471)
   432: WASM [wasm://wasm/0826337e], function #52962 ('interp_entry_instance_0'), pc=000001B19BCB7EFC (+0x5c), pos=12937728 (+43)
   433: WASM [wasm://wasm/0826337e], function #31439 ('corlib_aot_wrapper_gsharedvt_in_sig_void_this_'), pc=000001B19CA26340 (+0x80), pos=8245220 (+13)
   434: WASM [wasm://wasm/0826337e], function #44779 ('WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext'), pc=000001B19C2163F8 (+0xf8), pos=11186931 (+73)
   435: WASM [wasm://wasm/0826337e], function #44832 ('WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilde'), pc=000001B19C20C981 (+0x301), pos=11199095 (+397)
   436: WASM [wasm://wasm/0826337e], function #44776 ('WasmTestRunner_SimpleWasmTestRunner_Main_string__'), pc=000001B19C2168ED (+0x12d), pos=11186544 (+127)
   437: WASM [wasm://wasm/0826337e], function #31069 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_obj'), pc=000001B19CA40784 (+0xa4), pos=8220715 (+38)
   438: WASM [wasm://wasm/0826337e], function #52947 ('jit_call_cb'), pc=000001B19BCB8FAC (+0x1cc), pos=12936523 (+94)
   439: JsToWasmFrame [pc: 000003F3000B4A95]
   440: invoke_vi [000003F30830374D] [./dotnet.js:7850] [bytecode=000003F3085C2B35 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#3#,52587,9998624)
   441: WasmToJsFrame [pc: 000001B19E22D87D]
   442: WASM [wasm://wasm/0826337e], function #70130 ('mono_llvm_cpp_catch_exception'), pc=000001B19B6AD6D8 (+0x58), pos=14976321 (+22)
   443: WASM [wasm://wasm/0826337e], function #52904 ('do_jit_call'), pc=000001B19BCBD071 (+0x351), pos=12932514 (+396)
   444: WASM [wasm://wasm/0826337e], function #52833 ('interp_exec_method'), pc=000001B19B41B2BA (+0x439a), pos=12877891 (+5244)
   445: WASM [wasm://wasm/0826337e], function #52832 ('interp_runtime_invoke'), pc=000001B19BCC4891 (+0x1f1), pos=12872581 (+247)
   446: WASM [wasm://wasm/0826337e], function #69040 ('mono_jit_runtime_invoke'), pc=000001B19B7192F3 (+0x633), pos=14840609 (+627)
   447: WASM [wasm://wasm/0826337e], function #57670 ('do_runtime_invoke'), pc=000001B19BB136AE (+0xee), pos=13520841 (+53)
   448: WASM [wasm://wasm/0826337e], function #57681 ('mono_runtime_try_invoke'), pc=000001B19BB12269 (+0x89), pos=13522653 (+38)
   449: WASM [wasm://wasm/0826337e], function #57760 ('mono_runtime_invoke'), pc=000001B19BB0AF8C (+0xac), pos=13531411 (+65)
   450: WASM [wasm://wasm/0826337e], function #71023 ('mono_wasm_invoke_method'), pc=000001B19B656F34 (+0x74), pos=15106423 (+42)
   451: JsToWasmFrame [pc: 000003F3000B4A95]
   452: /* anonymous */ [000003F3082CC22D] [./dotnet.js:7103] [bytecode=000003F3085D3BC9 offset=36](this=0x03f3081c33f9 <JSGlobal Object>#3#)
   453: /* anonymous */ [000003F3081FF485] [./dotnet.js:3] [bytecode=000003F3082DDC39 offset=100](this=0x03f308312fbd <Object map = 000003F308205729>#4#)
   454: _call_method_with_converted_args(aka _call_method_with_converted_args) [000003F308314095] [./dotnet.js:3] [bytecode=000003F3085D3939 offset=43](this=0x03f3080023b5 <undefined>,32882144,0,0x03f308842e35 <Object map = 000003F308219639>#5#,0x03f308002235 <null>,36946080,0x03f30800248d <true>,0x03f3080023b5 <undefined>)
   455: call_method(aka call_method) [000003F308314015] [./dotnet.js:3] [bytecode=000003F3085D147D offset=185](this=0x03f3080023b5 <undefined>,32882144,0,0x03f3081d2dd5 <String[1]: #m>,0x03f308842e5d <JSArray[1]>#6#)
   456: /* anonymous */(aka /* anonymous */) [000003F308842EB1] [./dotnet.js:3] [bytecode=000003F3085CFB39 offset=128](this=0x03f3080023b5 <undefined>)
   457: mono_call_assembly_entry_point(aka mono_call_assembly_entry_point) [000003F308314115] [./dotnet.js:3] [bytecode=000003F3085CF6D1 offset=24](this=0x03f3080023b5 <undefined>,0x03f308322cc1 <String[18]: "WasmTestRunner.dll">,0x03f308842edd <JSArray[1]>#7#,0x03f3081d2dd5 <String[1]: #m>)
   458: mono_run_main [000003F308314479] [./dotnet.js:3] [bytecode=000003F3085CEF81 offset=47](this=0x03f308312f11 <Object map = 000003F30820EDF1>#8#,0x03f308322cc1 <String[18]: "WasmTestRunner.dll">,0x03f308842ecd <JSArray[7]>#9#)
   459: init [000003F308322B39] [test-main.js:214] [bytecode=000003F3085CEB65 offset=635](this=0x03f308305d51 <Object map = 000003F308218FA9>#10#,0x03f308842f45 <Object map = 000003F308218F09>#11#)
   460: onDotnetReady [000003F308317495] [test-main.js:153] [bytecode=000003F3085CE4DD offset=176](this=0x03f308312f01 <Object map = 000003F3082151F1>#12#)
   461: finalize_startup(aka finalize_startup) [000003F3083145ED] [./dotnet.js:3] [bytecode=000003F3085C833D offset=450](this=0x03f3080023b5 <undefined>,0x03f308312f65 <Object map = 000003F308212BF9>#13#)
   462: mono_wasm_after_runtime_initialized(aka mono_wasm_after_runtime_initialized) [000003F30831454D] [./dotnet.js:3] [bytecode=000003F3082DCD6D offset=58](this=0x03f3080023b5 <undefined>)
   463: callRuntimeCallbacks [000003F308321D51] [./dotnet.js:1487] [bytecode=000003F3082D9DCD offset=28](this=0x03f3081c33f9 <JSGlobal Object>#3#,0x03f308321b65 <JSArray[0]>#14#)
   464: postRun [000003F308321BD5] [./dotnet.js:1193] [bytecode=000003F3082DCC09 offset=95](this=0x03f3081c33f9 <JSGlobal Object>#3#)
   465: doRun [000003F3082F9709] [./dotnet.js:8006] [bytecode=000003F3082D9F85 offset=91](this=0x03f3081c33f9 <JSGlobal Object>#3#)
   466: run [000003F3083176F1] [./dotnet.js:8019] [bytecode=000003F3082CE2C9 offset=106](this=0x03f3081c33f9 <JSGlobal Object>#3#,0x03f30831d889 <Arguments map = 000003F3082040A9>#15#)
   467: runCaller [000003F308321C55] [./dotnet.js:7973] [bytecode=000003F3082D9BB1 offset=14](this=0x03f3081c33f9 <JSGlobal Object>#3#)
   468: removeRunDependency [000003F308307021] [./dotnet.js:1266] [bytecode=000003F3082CEDB5 offset=68](this=0x03f3081c33f9 <JSGlobal Object>#3#,0x03f3082cb209 <String[16]: #wasm-instantiate>)
   469: receiveInstance [000003F308323905] [./dotnet.js:1402] [bytecode=000003F3082D98D9 offset=103](this=0x03f3081c33f9 <JSGlobal Object>#3#,0x03f3082d12e5 <Instance map = 000003F308207079>#16#,0x03f3080023b5 <undefined>)
   470: receiveInstantiationResult [000003F308323899] [./dotnet.js:1413] [bytecode=000003F3082D9845 offset=8](this=0x03f3081c33f9 <JSGlobal Object>#3#,0x03f3082f8875 <Object map = 000003F308214EF9>#17#)
   471: StubFrame [pc: 000003F300106018]
   472: StubFrame [pc: 000003F30006E950]
   473: EntryFrame [pc: 000003F30004993B]
 =====================
 ```

This was for https://github.com/dotnet/runtime/commit/46db4aa3c505ac36cf8d0d612d4161bb7239ed87 . And the previous passing rolling build was https://github.com/dotnet/runtime/commit/6de7147b9266d7730b0d73ba67632b0c198cb11e .

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/63749.

### CODE REVIEW

File: src/mono/mono/mini/mini-exceptions.c [hunk 1]
```diff
@@ -3500,9 +3500,14 @@ mini_llvmonly_throw_corlib_exception (guint32 ex_token_index)
...
 	MonoException *ex;
 
+	HANDLE_FUNCTION_ENTER ();
+
 	ex = mono_exception_from_token (m_class_get_image (mono_defaults.exception_class), ex_token);
+	MONO_HANDLE_PIN (ex);
 
 	mini_llvmonly_throw_exception ((MonoObject*)ex);
+
+	HANDLE_FUNCTION_RETURN ();
```
Comment (lambdageek) [inline src/mono/mono/mini/mini-exceptions.c:3510]: `mini_llvmonly_throw_exception` starts stack unwinding, so the cleanup in `HANDLE_FUNCTION_RETURN` won't happen and we'll leak a coop handle.

Can you pass `&ex` to `mini_llvmonly_throw_exception` wouldn't that be enough to pin `ex` on the stack until the stack unwinding starts?

**Review by lambdageek — CHANGES_REQUESTED** [review]

File: src/mono/mono/mini/mini-exceptions.c (hunk 1 above)
Comment (vargaz) [reply src/mono/mono/mini/mini-exceptions.c]: Stored it in jit_tls instead.

**Review by lambdageek — APPROVED** [review]
