### PR TITLE
Use the typical `MethodTable` not instantiated on the declaration for constraint validation

### LINKED ISSUE #107132: `UnsafeAccessorAttribute` doesn't work with generic classes that have any constraint on generic type argument
### Description

If you create an generic accessor, like described in the updated docs, that refers to a generic class that have any constraint on generic type argument it throws an `InvalidProgramException` with the message `Generic type constraint do not match`.

### Reproduction Steps

```cs
using System.Runtime.CompilerServices;

var t = new Class<Argument>();
Accessor<Argument>.UnsafeMethod(t, 10);

public interface IInterface 
{ }

public class Argument : IInterface
{ }

public class Class<T> where T : IInterface
{
    private void Method(int value) { }
}

public static class Accessor<T>
    where T : IInterface
{
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "Method")]
    public static extern void UnsafeMethod(Class<T> @this, int value);
}
```

### Expected behavior

The type constraint on `Accessor<T>` matches the type constraint of the referred class `Class<T>` so the code should run fine and invoke the method.

### Actual behavior

The runtime throws an `InvalidProgramException` with the message `Generic type constraint do not match`.

### Regression?

In .NET8 you can implements a non generic accessor with closed generic and it worked as expected.
This implementation doesn't work anymore in .NET9 because of the new generic signature requirement.

```cs
using System.Runtime.CompilerServices;

var t = new Class<Argument>();
Accessor.UnsafeMethod(t, 10);

public interface IInterface 
{ }

public class Argument : IInterface
{ }

public class Class<T> where T : IInterface
{
    private void Method(int value) { }
}

public static class Accessor
{
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "Method")]
    public static extern void UnsafeMethod(Class<Argument> @this, int value);
}
```

### Known Workarounds

_No response_

### Configuration

- .NET version: 9.0.0-preview.7.24405.7
- O.S.: Windows 10 22H2 (OS build 19045.4780)
- Architecture: x64 (11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #107132

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/prestub.cpp [hunk 1]
```diff
@@ -1294,7 +1294,7 @@ namespace
         Instantiation targetMethodInst;
         if (targetType->HasInstantiation())
         {
-            declClassInst = declaration->GetMethodTable()->GetInstantiation();
+            declClassInst = declaration->GetMethodTable()->GetTypicalMethodTable()->GetInstantiation();
```
Comment (jkotas) [inline src/coreclr/vm/prestub.cpp:1297]: I have been looking at the implementation of `MethodTable::GetTypicalMethodTable`. 

It uses `LookupTypeDef` that returns the MethodTable if the type was loaded, but it can return null if it was not loaded yet.

Do we guarantee somewhere that the typical method table is loaded before we can come here?

Comment (jkotas) [reply src/coreclr/vm/prestub.cpp:1297]: Ok, this should guarantee that: https://github.com/dotnet/runtime/blob/fbf46726097e766bb7b8a3eb94315d55185e9cf3/src/coreclr/vm/methodtable.cpp#L4358-L4362
