### PR TITLE
Convert invalid C# uses of UnmanagedCallersOnly to IL.

### LINKED ISSUE #42125: UnmanagedCallersOnly test failing in the outerloop during compilation
The issue seems to be due to some C# compiler update - the failures seem to be at places of negative testing that expects runtime failures, but we started to get compilation failures instead.

```
/__w/1/s/src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs(341,6): error CS8896: 'UnmanagedCallersOnly' can only be applied to ordinary static methods or static local functions. [/__w/1/s/src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.csproj]
##[error]src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs(341,6): error CS8896: 'UnmanagedCallersOnly' can only be applied to ordinary static methods or static local functions.
/__w/1/s/src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs(439,6): error CS8895: Methods attributed with 'UnmanagedCallersOnly' cannot have generic type parameters and cannot be declared in a generic type. [/__w/1/s/src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.csproj]
##[error]src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs(439,6): error CS8895: Methods attributed with 'UnmanagedCallersOnly' cannot have generic type parameters and cannot be declared in a generic type.
/__w/1/s/src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs(440,48): error CS8894: Cannot use 'T' as a parameter type on a method attributed with 'UnmanagedCallersOnly'. [/__w/1/s/src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.csproj]
##[error]src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs(440,48): error CS8894: Cannot use 'T' as a parameter type on a method attributed with 'UnmanagedCallersOnly'.
/__w/1/s/src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs(520,10): error CS8895: Methods attributed with 'UnmanagedCallersOnly' cannot have generic type parameters and cannot be declared in a generic type. [/__w/1/s/src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.csproj]
##[error]src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs(520,10): error CS8895: Methods attributed with 'UnmanagedCallersOnly' cannot have generic type parameters and cannot be declared in a generic type.
```

Log here:
https://dev.azure.com/dnceng/public/_build/results?buildId=811186&view=logs&j=db768a9e-3325-5ce3-2d52-896c40bee68a&t=59112ad9-fe58-56ee-6943-84df6f0e3f8e&l=13792

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #42125 

/cc @jkoritzinsky @elinor-fung

### CODE REVIEW

File: src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs [hunk 1]
```diff
@@ -35,6 +37,20 @@ public static class UnmanagedCallersOnlyDll
         public static extern int PInvokeMarkedWithUnmanagedCallersOnly(int n);
     }
 
+    private const string InvalidCSharpAssemblyName = "InvalidCSharp.dll";
+
+    public static Type GetCallbacksType()
+    {
+        var asm = AssemblyLoadContext.Default.LoadFromAssemblyPath(Path.Combine(Environment.CurrentDirectory, InvalidCSharpAssemblyName));
```
Comment (jkotas) [inline src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:44]: A simple `Assembly.Load("InvalidCSharp")` does not work?

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs]: It does. I have been falling back to ALC usage just because it seems like the clearest way now.

Fixed.

Comment (jkotas) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs]: `Assembly.Load` is the cleanest way when the assembly is part of your application that should be majority of cases.

**Comment by am11** [comment]
Thanks! maybe run the outerloop leg (to validate the fix in CI).

**Comment by AaronRobinsonMSFT** [comment]
@am11 That is no needed. I moved this to priority 0 so it now runs in the CI - which is where it should have been when we made the API public.

File: src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs [hunk 2]
```diff
@@ -371,7 +379,7 @@ .locals init ([0] native int ptr)
         il.Emit(OpCodes.Nop);
```
Comment (jkotas) [inline src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:379]: The dynamic IL generation can be moved to the IL project too. It would improve the test coverage for AOT.

It can be done as a separate PR.

**Review by jkotas — APPROVED** [review]

File: src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs [hunk 3]
```diff
@@ -35,6 +35,20 @@ public static class UnmanagedCallersOnlyDll
         public static extern int PInvokeMarkedWithUnmanagedCallersOnly(int n);
     }
 
+    private const string InvalidCSharpAssemblyName = "InvalidCSharp";
+
+    public static Type GetCallbacksType()
+    {
+        var asm = Assembly.Load(InvalidCSharpAssemblyName);
+        return asm.GetType("InvalidCSharp.Callbacks");
```
Comment (jkotas) [inline src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: The ProjectReferences seems to be working fine for test projects. For example: https://github.com/dotnet/runtime/blob/master/src/tests/baseservices/callconvs/TestCallingConventions.csproj#L11

Project reference would be even better than `Assembly.Load`.

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: Yes, `ProjectReference`s do work for build but not to refer to the assembly. The typical issue is the assembly that contains `System.Object` isn't the same when compiled with `ilasm` as the one for `csc` and during assembly reference an error occurs. The only way I have found to circumvent this is to load during runtime.

The reason the referenced test works is because of the following:

https://github.com/dotnet/runtime/blob/c86733753da5ec1b2e670cad229f38a5bc113f6e/src/tests/baseservices/callconvs/CallFunctionPointers.il#L4-L8

This is fine for now, but when we version to .NET 6, this will break. The current approach is the only way I have found that continue to work through time.

**Comment by jkotas** [comment]
Have you done anything about the test failures before merging?

```
 You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  AppDir: /home/helixbot/work/A8DD0933/w/9F1008D3/e/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/WasmApp/
  TestBinDir: /home/helixbot/work/A8DD0933/w/9F1008D3/e/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest
  ArtifactsBinDir: 
Arguments: --run,UnmanagedCallersOnlyTest.dll,UnmanagedCallersOnlyTest
console.debug: MONO_WASM: Initializing mono runtime
console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
Initializing.....
Running TestUnmanagedCallersOnlyValid...
Test Failure: System.PlatformNotSupportedException: No native to managed transitions on this platform.
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
   at Program.TestUnmanagedCallersOnlyValid()
   at Program.Main(String[] args)
```

File: src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs (hunk 3 above)
Comment (jkotas) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: I do not think this should be a problem. What is the csc error that you are seeing? I know that csc was picky about situations like these in the past, but these checks were removed a while ago. They did not make sense for .NET Core nor for .NET Framework with binding redirects. 

It is fairly normal to have multiple different System.Runtime references in .NET Core world. For example, it is fully supported for project targeting net6 (that has System.Runtime 6.0) to reference project targeting net6 (that has System.Runtime 5.0.).

If you do not like hardcoding versions, you can just omit them. For example: https://github.com/jkotas/runtime/blob/5095f1f75f86c2aedaedf9e35457cb6635a3c989/src/tests/Regressions/coreclr/16355/boring.il#L4

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: I was hitting the error about `System.Object` from assembly is not known. However, when I try it now I don't see that... this is unsettling because I did try that first. I'm not a fan of not understanding why I hit that error for 20 minutes changed to the runtime load but now it doesn't repro.

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: Yep, that works just fine throughout. Any idea how I could have made that error occur? That is frustrating beyond belief. I will push up a new PR with the IL updates as well.

Comment (jkotas) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: > error about System.Object from assembly is not known.

This error is typically caused by missing System.Runtime reference, not by having incompatible System.Runtime references.

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: Here is what I am seeing now.

Failure during build of C# test application:
```
error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Call site in C#:
```CSharp
InvalidCSharp.Test.Invoke(null, n);
```

Snippet of IL code being called in C#:
```
.assembly extern System.Runtime { }
.assembly extern System.Runtime.InteropServices { }

.assembly InvalidCSharp { }

.class public auto ansi beforefieldinit InvalidCSharp.Test
    extends System.Object
{
    .method public hidebysig static 
        void Invoke (
            void* fptr,
            int32 n
        ) cil managed 
    {
        .maxstack 2
        .locals init ([0] native int ptr)

        nop
        ldarg.0
        stloc.0

        ldloc.0
        ldarg.1
        calli int32 *(int32)
        
        ret
    }
}
```

Comment (jkotas) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: Maybe C# compiler needs the public key tokens to match? You can try adding ` .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )`.

Comment (jkotas) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: Does the C# compiler command line have `/r:....\System.Runtime.dll` ?

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:43]: >Maybe C# compiler needs the public key tokens to match? You can try adding .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A ).

That did it. This is a very confusing issue. But it works now so yay.

>Does the C# compiler command line have /r:....\System.Runtime.dll ?

It does.

```
 /reference:D:\runtime\artifacts\bin\ref\net5.0\System.Runtime.dll
```
