### PR TITLE
[clr-ios] Enable Release builds and dynamic linking on Apple mobile

### LINKED ISSUE #121023: [clr-interp] Interpreter doesn't build with Release
### Description

```
src\coreclr\vm\amd64\asmconstants.h(576): error C2607 static assertion failure
```

at

```
#ifdef TARGET_UNIX
#define OFFSETOF__Thread__m_pInterpThreadContext 0xb50
#else // TARGET_UNIX
#define OFFSETOF__Thread__m_pInterpThreadContext 0xba8
#endif // TARGET_UNIX
ASMCONSTANTS_C_ASSERT(OFFSETOF__Thread__m_pInterpThreadContext == offsetof(Thread, m_pInterpThreadContext))
```

### Reproduction Steps

Change `set(FEATURE_INTERPRETER $<IF:$<CONFIG:Debug,Checked>,1,0>)` to `set(FEATURE_INTERPRETER 1)` in clrfeatures.cmake and build the coreclr with Release config

### Expected behavior

coreclr builds

### Actual behavior

build failure with static assertiong failure

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by kotlarmilos**
## Description

This PR enables the interpreter by default on Apple mobile platforms and enables dynamic linking in AppleAppBuilder used in the testing pipeline.

Contributes to https://github.com/dotnet/runtime/issues/119006

Fixes https://github.com/dotnet/runtime/issues/121023

### CODE REVIEW

File: src/coreclr/vm/arm64/asmconstants.h [hunk 1]
```diff
@@ -305,7 +305,11 @@ ASMCONSTANTS_C_ASSERT(OFFSETOF__ThreadLocalInfo__m_pThread == offsetof(ThreadLoc
 ASMCONSTANTS_C_ASSERT(OFFSETOF__InterpMethod__pCallStub == offsetof(InterpMethod, pCallStub))
 
 #ifdef TARGET_UNIX
+#ifdef _DEBUG
 #define OFFSETOF__Thread__m_pInterpThreadContext 0xb78
+#else
+#define OFFSETOF__Thread__m_pInterpThreadContext 0x310
+#endif // _DEBUG
```
[the remark this answers is not in the document]
Comment (kotlarmilos) [reply src/coreclr/vm/arm64/asmconstants.h:312]: @janvorli How this isn’t hit on WASM yet, given that it is enabled in all configurations there?

File: src/tasks/AppleAppBuilder/Templates/CMakeLists.txt.template [hunk 2]
```diff
@@ -57,13 +57,32 @@ if("${HARDENED_RUNTIME}")
...
+  TARGET %ProjectName% POST_BUILD
+  COMMAND
+    if test \"$CODE_SIGN_IDENTITY\" && test \"$CODE_SIGN_IDENTITY\" != \"\"\; then
+      SIGN_IDENTITY=\"$EXPANDED_CODE_SIGN_IDENTITY\"\;
+      # This resolves the correct signing certificate by matching the identity name
+      # when multiple signing certificates are available
+      if test -z \"$SIGN_IDENTITY\" || test \"$SIGN_IDENTITY\" = \"$CODE_SIGN_IDENTITY\"\; then
+        CERT_HASH=`security find-identity -v -p codesigning | grep \"$CODE_SIGN_IDENTITY\" | head -1 | awk '{print $2}'`\;
+        SIGN_IDENTITY=\"$CERT_HASH\"\;
+      fi\;
```
[the remark this answers is not in the document]
Comment (kotlarmilos) [reply src/tasks/AppleAppBuilder/Templates/CMakeLists.txt.template:74]: This is used for testing only, so it assumes a certificate is available.

File: src/tasks/AppleAppBuilder/Xcode.cs [hunk 3]
```diff
@@ -295,6 +295,11 @@ public string GenerateCMake(
         {
             predefinedExcludes.Add("libcoreclr.dylib");
         }
+        else
+        {
```
[the remark this answers is not in the document]
Comment (kotlarmilos) [reply src/tasks/AppleAppBuilder/Xcode.cs:299]: Added a comment

File: src/coreclr/vm/arm64/asmconstants.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (janvorli) [reply src/coreclr/vm/arm64/asmconstants.h:312]: I guess no one tried to build wasm in Release configuration yet.

[the remark this answers is not in the document]
Comment (janvorli) [reply src/coreclr/vm/arm64/asmconstants.h:312]: Btw, there is an issue tracking this for all targets - #121023

File: src/coreclr/clrfeatures.cmake [hunk 4]
```diff
@@ -43,6 +43,8 @@ if(NOT DEFINED FEATURE_INTERPRETER)
     set(FEATURE_INTERPRETER 1)
     set(FEATURE_PORTABLE_ENTRYPOINTS 1)
     set(FEATURE_PORTABLE_HELPERS 1)
+  elseif(CLR_CMAKE_TARGET_IOS OR CLR_CMAKE_TARGET_TVOS OR CLR_CMAKE_TARGET_MACCATALYST)
```
Comment (janvorli) [inline src/coreclr/clrfeatures.cmake:46]: We also need to change src/coreclr/clr.featuredefines.props where the FeatureInterpreter is defined for managed code:
https://github.com/dotnet/runtime/blob/7201a39b318e4916f704e3a5c2fa96e3d58bc352/src/coreclr/clr.featuredefines.props#L39-L41

Comment (janvorli) [reply src/coreclr/clrfeatures.cmake:46]: Otherwise the offsets in the native and managed EH code won't match and EH would crash in funny ways.

File: src/mono/sample/iOS/Program.csproj [hunk 5]
```diff
@@ -31,7 +30,7 @@
     <RuntimeComponents Condition="'$(DiagnosticPorts)' != ''" Include="diagnostics_tracing" />
     <EnvironmentVariables Condition="'$(UseMonoRuntime)' != 'true'" Include="DOTNET_InterpMode=3" />
     <EnvironmentVariables Condition="'$(UseMonoRuntime)' != 'true'" Include="DOTNET_ReadyToRun=0" />
-    <EnvironmentVariables Condition="'$(UseMonoRuntime)' != 'true'" Include="DOTNET_InterpDump=*!*" />
+    <EnvironmentVariables Condition="'$(UseMonoRuntime)' != 'true'" Include="DOTNET_InterpDump=%2A%21%2A" />
```
Comment (janvorli) [inline src/mono/sample/iOS/Program.csproj]: Do we want to have the debug dumping enabled?

**Comment by kotlarmilos** [comment]
@vitek-karas @matouskozak Please take a look, this will enable iOS SDK integration

**Review by vitek-karas — APPROVED** [review]
The pipeline changes look good.. I didn't review the exact mechanics of handling dynamic libs in the app builder.

File: src/tasks/AppleAppBuilder/AppleAppBuilder.cs [hunk 6]
```diff
@@ -342,7 +342,7 @@ public override bool Execute()
             {
                 extraLinkerArgs.Add("-rpath @executable_path");
             }
-            shouldStaticLink = true;
+            shouldStaticLink = false;
```
Comment (BrzVlad) [inline src/tasks/AppleAppBuilder/AppleAppBuilder.cs:345]: Why exactly are we using dynamic linking on iOS ? I seem to remember that we planned to have static linking.

Comment (kotlarmilos) [reply src/tasks/AppleAppBuilder/AppleAppBuilder.cs:345]: We are using dynamic linking for simplicity. Crossgen2 produces object files that are dynamically linked into the framework and loaded on Apple mobile. Static R2R libraries might have versioning issues, and performance characteristics are still unknown. The plan is to use dynamic linking in debug and release builds and collect performance.

**Review by janvorli — APPROVED** [review]
The runtime changes look good to me.

File: src/mono/sample/iOS/Program.csproj (hunk 5 above)
Comment (kotlarmilos) [reply src/mono/sample/iOS/Program.csproj]: It was used only for validation. Since this sample is used for startup measurements, I will remove it.

**Comment by kotlarmilos** [comment]
/ba-g Android timeouts https://github.com/dotnet/dnceng/issues/6408
