### PR TITLE
Fix one more Crossgen2 field layout mismatch with runtime

### LINKED ISSUE #73728: crossgen2/VM layout mismatch in CI
<!-- runfo report start -->
Runfo Tracking Issue: [jit\\regression\\jitblue\\runtime_60035\\runtime_60035\\runtime_60035.cmd](https://runfo.azurewebsites.net/tracking/issue/426)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked heapverify1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-e83eb42e8665440b8c/JIT.Regression/1/console.404b3800.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-e83eb42e8665440b8c/JIT.Regression/1/corerun.exe.5576.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-e83eb42e8665440b8c/JIT.Regression/7e3ea6a8-eb69-4d0d-87ef-a37826e2a033.log?%3F%253Fhelixlogtype%253Dresult)|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked heapverify1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-dbb35b5b56f04a279d/JIT.Regression/1/console.7c718baa.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-dbb35b5b56f04a279d/JIT.Regression/e3f38ab9-49c6-48b5-bcd9-ca910996ddd8.log?%3F%253Fhelixlogtype%253Dresult)|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-70f779ec68f54d33a9/JIT.Regression/1/console.05b467ed.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-70f779ec68f54d33a9/JIT.Regression/1/corerun.exe.4144.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-70f779ec68f54d33a9/JIT.Regression/ba0d399b-bb6b-4f7d-ab97-1b8bd508c21c.log?%3F%253Fhelixlogtype%253Dresult)|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-3ffce4863e594a64bb/JIT.Regression/1/console.e63c991d.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-3ffce4863e594a64bb/JIT.Regression/1/corerun.exe.2932.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-3ffce4863e594a64bb/JIT.Regression/ada18114-fd6d-4203-a6d6-04b7fee1ea94.log?%3F%253Fhelixlogtype%253Dresult)|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_tailcallstress @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-e6f2e8fa64324ec184/JIT.Regression/1/console.6f90f8d4.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-e6f2e8fa64324ec184/JIT.Regression/1/corerun.exe.1708.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-e6f2e8fa64324ec184/JIT.Regression/23b12514-e05d-4861-a4e2-40e5439e2b7b.log?%3F%253Fhelixlogtype%253Dresult)|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5e146301f85c4b0390/JIT.Regression/1/console.9c536b38.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5e146301f85c4b0390/JIT.Regression/1/corerun.exe.3332.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5e146301f85c4b0390/JIT.Regression/f43b0ccd-5870-4f7f-93be-f10d54f868d4.log?%3F%253Fhelixlogtype%253Dresult)|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitstress1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4229669710744a59a7/JIT.Regression/1/console.fb96c936.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4229669710744a59a7/JIT.Regression/6bed5218-e633-4785-ba51-e44413b5b53b.log?%3F%253Fhelixlogtype%253Dresult)|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitstress2 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9b1e3f433d144f3abc/JIT.Regression/1/console.cbf3457b.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9b1e3f433d144f3abc/JIT.Regression/796d071f-ed72-4baf-b475-8d4bfae31a17.log?%3F%253Fhelixlogtype%253Dresult)|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_tailcallstress @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-01d81121136b482c89/JIT.Regression/1/console.17809879.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-01d81121136b482c89/JIT.Regression/ac57eb7a-b33f-414b-9796-3bbc6cf00f6d.log?%3F%253Fhelixlogtype%253Dresult)|
|[1943278](https://dev.azure.com/dnceng/public/_build/results?buildId=1943278)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-12f1d3e1b6ae428f96/JIT.Regression/1/console.88dcec9d.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-12f1d3e1b6ae428f96/JIT.Regression/c399461d-239c-4bb5-a5e4-e71a0f533a95.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked heapverify1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-62fa14cd1886458db5/JIT.Regression/1/console.c364c5bd.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-62fa14cd1886458db5/JIT.Regression/1/corerun.exe.1332.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-62fa14cd1886458db5/JIT.Regression/dc3a68fe-d2cc-406e-9a3f-15e2468d8864.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked heapverify1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-64e20eb90bbe4982b4/JIT.Regression/1/console.7b9b1e57.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-64e20eb90bbe4982b4/JIT.Regression/1/corerun.exe.13336.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-64e20eb90bbe4982b4/JIT.Regression/becc365e-0929-4b7d-b711-89d731252cd0.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bcf168b658db489ba0/JIT.Regression/1/console.badcef72.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bcf168b658db489ba0/JIT.Regression/1/corerun.exe.3432.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bcf168b658db489ba0/JIT.Regression/d3c618f2-8725-49fa-b6ea-56583842cfaf.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f18a40fa1f224ee696/JIT.Regression/1/console.25deed5c.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f18a40fa1f224ee696/JIT.Regression/1/corerun.exe.2588.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f18a40fa1f224ee696/JIT.Regression/a559766a-1b73-45d5-ba10-2ffee79eb943.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_tailcallstress @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9f8e17869ece4876bb/JIT.Regression/1/console.d2c01905.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9f8e17869ece4876bb/JIT.Regression/1/corerun.exe.6596.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9f8e17869ece4876bb/JIT.Regression/069610f5-fa0b-41be-b3f9-8e41464f2e05.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-69896ec51aae4d958f/JIT.Regression/1/console.9c1d1f0d.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-69896ec51aae4d958f/JIT.Regression/1/corerun.exe.3548.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-69896ec51aae4d958f/JIT.Regression/eb4e3b05-9819-4e6d-b92c-7a762c6fd751.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitstress1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5fe3e52586de4c7a9a/JIT.Regression/1/console.391c9ec4.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5fe3e52586de4c7a9a/JIT.Regression/74b5b0d7-35c2-4818-91ad-2420e8fd13d1.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitstress2 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c636674aa4cb40aa91/JIT.Regression/1/console.3b82e493.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c636674aa4cb40aa91/JIT.Regression/1bb3ffe0-9b2f-4b0f-b4be-f1be058adde0.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_tailcallstress @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0682d39ee4d1434484/JIT.Regression/1/console.3a605a02.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0682d39ee4d1434484/JIT.Regression/1/corerun.exe.9196.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0682d39ee4d1434484/JIT.Regression/3338a3d5-8366-4a49-aff5-df1235e13bfe.log?%3F%253Fhelixlogtype%253Dresult)|
|[1942465](https://dev.azure.com/dnceng/public/_build/results?buildId=1942465)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2dd630acc6514d8b9d/JIT.Regression/1/console.6c420f61.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2dd630acc6514d8b9d/JIT.Regression/1830cee2-26ac-4145-90f2-e77a81896000.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked heapverify1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-19e58e6293b5425198/JIT.Regression/1/console.949d29b7.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-19e58e6293b5425198/JIT.Regression/1/corerun.exe.5516.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-19e58e6293b5425198/JIT.Regression/5761df1c-ef47-4d3b-b991-e8b9e7f62cb4.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked heapverify1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b1dd0c33c9ad45b4bc/JIT.Regression/1/console.50e9bb0d.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b1dd0c33c9ad45b4bc/JIT.Regression/480a94ef-578f-4cbf-82b1-3dc65f5741ac.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d3083f8e89bd47939a/JIT.Regression/1/console.903bcaed.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d3083f8e89bd47939a/JIT.Regression/1/corerun.exe.5224.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d3083f8e89bd47939a/JIT.Regression/d6af9111-cb60-4d55-a2f2-95cb17a94b1f.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-61af9b49a37f4e7498/JIT.Regression/1/console.7a0186b7.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-61af9b49a37f4e7498/JIT.Regression/1/corerun.exe.9308.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-61af9b49a37f4e7498/JIT.Regression/8ab9a7a8-9049-48e3-b495-4c20482a1945.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_tailcallstress @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b6362ed26c1d434f9b/JIT.Regression/1/console.26cd9be3.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b6362ed26c1d434f9b/JIT.Regression/1/corerun.exe.2360.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b6362ed26c1d434f9b/JIT.Regression/066e60dc-ff3f-4d79-b00d-2dd71fe6a251.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a4bafe75c33d49f6aa/JIT.Regression/1/console.c678789e.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a4bafe75c33d49f6aa/JIT.Regression/1/corerun.exe.6944.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a4bafe75c33d49f6aa/JIT.Regression/6bfcc114-7015-4691-8776-2fed0860fe10.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitstress1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f4388ba9ca844045be/JIT.Regression/1/console.3ebcbed2.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f4388ba9ca844045be/JIT.Regression/38e7100e-0aaf-4442-9fd2-6cfbc3d79df5.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitstress2 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9214e31fecb8455f93/JIT.Regression/1/console.716562ca.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9214e31fecb8455f93/JIT.Regression/cd209c9f-9bd4-452c-b73f-378ab0828bb3.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_tailcallstress @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-344c44a7313444e4a1/JIT.Regression/1/console.d6dd354d.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-344c44a7313444e4a1/JIT.Regression/b047b8a7-8ab4-43d3-b41d-b7a2e3b37f37.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928978](https://dev.azure.com/dnceng/public/_build/results?buildId=1928978)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2bdce7dd38224b8b90/JIT.Regression/1/console.f4c89a6f.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2bdce7dd38224b8b90/JIT.Regression/13ff4d58-3a27-4479-840c-d902043fb35d.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked heapverify1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-59d32db3c00642f0a3/JIT.Regression/1/console.c7606e99.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-59d32db3c00642f0a3/JIT.Regression/1/corerun.exe.6060.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-59d32db3c00642f0a3/JIT.Regression/bd4a74f9-b763-44e3-961c-1efd31a0a5eb.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked heapverify1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-555927bf24b1493098/JIT.Regression/1/console.e7cf4a02.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-555927bf24b1493098/JIT.Regression/daffe78d-4a5e-48c2-93c8-3c1eee1f0bf5.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fb396aed454d4289b0/JIT.Regression/1/console.8c7ee13a.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fb396aed454d4289b0/JIT.Regression/1/corerun.exe.2988.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fb396aed454d4289b0/JIT.Regression/6cf3ec2b-cf67-4944-aaa8-68ecef2c9474.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c7f394516bfb4908a3/JIT.Regression/1/console.319c05f9.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c7f394516bfb4908a3/JIT.Regression/1/corerun.exe.2984.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c7f394516bfb4908a3/JIT.Regression/b147b17e-2abc-4331-acc9-9d3abc0e05ae.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_tailcallstress @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7210c8762cf940ab90/JIT.Regression/1/console.5c04461c.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7210c8762cf940ab90/JIT.Regression/1/corerun.exe.3932.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7210c8762cf940ab90/JIT.Regression/0666e15f-9b64-4fa8-a908-29f4efe3b90b.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows x64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-95314862e8c24aa8a3/JIT.Regression/1/console.bee05c5a.log?%3F%253Fhelixlogtype%253Dresult)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-95314862e8c24aa8a3/JIT.Regression/1/corerun.exe.1356.dmp?%3F%253Fhelixlogtype%253Dresult)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-95314862e8c24aa8a3/JIT.Regression/8e931c9a-f9c6-4834-9eb4-ca83948560e3.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitstress1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8385a2de727143b2ad/JIT.Regression/1/console.6940e0b8.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8385a2de727143b2ad/JIT.Regression/ce802721-d026-4b22-832c-a6d597875e13.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitstress2 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-954c899f87d44e65b9/JIT.Regression/1/console.cc4958f2.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-954c899f87d44e65b9/JIT.Regression/8b9f5387-fcff-4df9-a165-bb43854a812c.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_tailcallstress @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ddbb05ed9b6c497287/JIT.Regression/1/console.05c88f1b.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ddbb05ed9b6c497287/JIT.Regression/2c542be1-c77f-42b7-9c9a-7bc61db89f82.log?%3F%253Fhelixlogtype%253Dresult)|
|[1928205](https://dev.azure.com/dnceng/public/_build/results?buildId=1928205)|[runtime-coreclr crossgen2-composite gcstress](https://dnceng.visualstudio.com/public/_build?definitionId=886)|Rolling|R2R-CG2 windows arm64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Arm64v8.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-03e944074e39471ea0/JIT.Regression/1/console.74c2b19a.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-03e944074e39471ea0/JIT.Regression/002e2a74-6562-4a00-9e97-18e9bb1a81ae.log?%3F%253Fhelixlogtype%253Dresult)|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|2|4|

<!-- runfo report end -->

### PR DESCRIPTION
**Pull request by trylek**
The field offset mismatch in the test

JIT/Regression/JitBlue/Runtime_60035/Runtime_60035.csproj

specific to Crossgen2 composite mode is due to the recent
proliferation of 16-byte alignment specific to Vector across
the runtime repo. Previously, the largest supported alignment
was 8 and X86 was the only architecture not respecting it.

In general the problem is caused by the fact that the native
CoreCLR runtime method table builder calculates field offsets
without taking the method table pointer into account; in the
particular case of the Runtime_60035 test, the class
System.Text.Encodings.Web.OptimizedInboxTextEncoder
has a field named _allowedAsciiCodePoints that is 16-aligned
that exposes this inconsistency.

Thanks

Tomas

/cc @dotnet/crossgen-contrib 

Fixes #73728

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 1]
```diff
@@ -545,7 +545,7 @@ protected ComputedInstanceFieldLayout ComputeAutoFieldLayout(MetadataType type,
             // between base type and the current type.
             LayoutInt cumulativeInstanceFieldPos = CalculateFieldBaseOffset(type, requiresAlign8, requiresAlignedBase: false);
             LayoutInt offsetBias = LayoutInt.Zero;
-            if (!type.IsValueType && cumulativeInstanceFieldPos != LayoutInt.Zero && type.Context.Target.Architecture == TargetArchitecture.X86)
+            if (!type.IsValueType && cumulativeInstanceFieldPos != LayoutInt.Zero && type.Context.Target.Architecture != TargetArchitecture.ARM)
```
Comment (davidwrighton) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:548]: This function needs a comment describing what's happening here, and we need a test where we have Sequential field layout used for classes as well as just the standard auto layout.

**Comment by mangod9** [comment]
There is one test failing in the IL.ClassLayout tests. Given this error looks like the test is expecting a nondeterministic layout:

```Assert.Equal() Failure\nExpected: Indeterminate\nActual:   8```

**Comment by davidwrighton** [comment]
@mangod9, @trylek, the failing test is testing universal generic layout behavior, which I don't believe has been actually correct since we implemented auto layout. We can comment that test out.

**Comment by mangod9** [comment]
> @mangod9, @trylek, the failing test is testing universal generic layout behavior, which I don't believe has been actually correct since we implemented auto layout. We can comment that test out.

or perhaps just update it to expect 8. Or is that non-deterministic still?

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs (hunk 1 above)
Comment (trylek) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:580]: Thanks David for your feedback. I have improved the code comment and I added a pair of tests exercising the 16-layout with classes using both Auto and Sequential layout. Could you please take another look when you have a chance?

**Review by davidwrighton — APPROVED** [review]
