### PR TITLE
Fix for assert failure in distribute free regions

### LINKED ISSUE #66601: GC regions failure in System.Threading.Tests.dll
PR leg: https://dev.azure.com/dnceng/public/_build/results?buildId=1662354&view=logs&jobId=a68d6dca-d11c-59af-6c4a-cf852cb20e3a&j=a68d6dca-d11c-59af-6c4a-cf852cb20e3a&t=28d89dec-7e09-5293-5fd2-aeb03e603264

```
C:\h\w\A26608BD\w\B4F90A12\e>"C:\h\w\A26608BD\p\dotnet.exe" exec --runtimeconfig System.Threading.Tests.runtimeconfig.json --depsfile System.Threading.Tests.deps.json xunit.console.dll System.Threading.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Threading.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tests (found 258 of 270 test cases)
  Starting:    System.Threading.Tests (parallel test collections = on, max threads = 4)
    System.Threading.Tests.MutexTests.Ctor_TryCreateGlobalMutexTest_Uwp [SKIP]
      Condition(s) not met: "IsInAppContainer"

Assert failure(PID 2060 [0x0000080c], Thread: 468 [0x01d4]): global_regions_to_decommit[kind].get_num_free_regions() == num_regions_to_decommit_before + (size_t)num_regions_to_decommit[kind]

CORECLR! GetCLRRuntimeHost + 0x66D748 (0x00007ffe`8561d158)
CORECLR! GetCLRRuntimeHost + 0x67198B (0x00007ffe`8562139b)
CORECLR! GetCLRRuntimeHost + 0x670F34 (0x00007ffe`85620944)
CORECLR! GetCLRRuntimeHost + 0x659C6E (0x00007ffe`8560967e)
CORECLR! GetCLRRuntimeHost + 0x6597CE (0x00007ffe`856091de)
CORECLR! GetCLRRuntimeHost + 0x280792 (0x00007ffe`852301a2)
<no module>! <no symbol> + 0x0 (0x00007ffe`2769fa13)
<no module>! <no symbol> + 0x0 (0x00000086`e15f9c90)
<no module>! <no symbol> + 0x0 (0x00000086`e15f9948)
<no module>! <no symbol> + 0x0 (0x00000086`e15f9600)
    File: D:\a\_work\1\s\src\coreclr\gc\gc.cpp Line: 12432
    Image: C:\h\w\A26608BD\p\dotnet.exe
```

### PR DESCRIPTION
**Pull request by PeterSolMS**
I had failed to take into account the case where we move a free region to the decommit list due to age, but it is among the free regions with the highest address, and so is encountered by move_highest_free_regions as well.

What happens then is that move_highest_free_regions removes it from the decommit list, and puts it on the decommit list again. No harm done, except that we didn't move as many regions to the decommit list as planned.

Fix is to check in move_highest_free_regions whether a region is already on the decommit list, and skip it in this case. I preferred this to loosening the assert because it makes sure we actually decommit as much as planned.

Fixes: https://github.com/dotnet/runtime/issues/66601

### CODE REVIEW

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -12141,6 +12141,13 @@ void region_free_list::add_region_descending (heap_segment* region, region_free_
     to_free_list[kind].add_region_in_descending_order (region);
 }
 
+bool region_free_list::is_on_free_list (heap_segment* region, region_free_list free_list[count_free_region_kinds])
```
Comment (mangod9) [inline src/coreclr/gc/gc.cpp:12144]: assume the free list is usually not long so the search is fast?

**Review by mangod9 — APPROVED** [review]

File: src/coreclr/gc/gc.cpp (hunk 1 above)
Comment (PeterSolMS) [reply src/coreclr/gc/gc.cpp:12144]: There is no searching - if a region is on a free list, it contains a pointer to that free list. So the check is constant time.

Comment (mangod9) [reply src/coreclr/gc/gc.cpp:12144]: ah nice.

**Review by Maoni0 — APPROVED** [review]
