### PR TITLE
Permit unencrypted key exports from CNG

### LINKED ISSUE #109059: Cannot export RSAParameters from X509Certificate2 in .NET 9 RC2
### Description

I've noticed a discrepancy in behavior between .NET 8 and 9 (RC2) when it comes to the ability to export the RSAParameters (with private) between .NET 8 and .NET 9.

From a quick investigation it looks like ExportPolicy is different between those two frameworks despite passing same X509KeyStorageFlags parameters to the X509Certificate2 ctor (tried X509CertificateLoader as well).

I'm running this on Windows.

### Reproduction Steps

```csharp
        var certBytes = File.ReadAllBytes("<path_to_pfx>");
        var cert = new X509Certificate2(certBytes, (string)null, X509KeyStorageFlags.Exportable | X509KeyStorageFlags.UserKeySet);
        var privateKey = (RSACng)cert.GetRSAPrivateKey();
        Console.WriteLine(privateKey.Key.ExportPolicy);

        var parameters = privateKey.ExportParameters(true);
```

I can paste the PFX if needed. Got it from the staging Let's Encrypt.

### Expected behavior

On .NET 8 I'm getting following output from the console writeline

```
AllowExport, AllowPlaintextExport
```

### Actual behavior

On .NET 9 RC2 I'm getting following output:

```
AllowExport
Unhandled exception. System.Security.Cryptography.CryptographicException: The requested operation is not supported.
   at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format)
   at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters)
   at Tryouts.Program.Main(String[] args) in D:\workspaces\ravendb_4\test\Tryouts\Program.cs:line 42
   at Tryouts.Program.<Main>(String[] args)
```

I'm suspecting that the exception is caused because of the missing 'AllowPlaintextExport' flag.

### Regression?

Yes?

### Known Workarounds

_No response_

### Configuration

```
dotnet --info
.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.4872d5d5
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.11.35327.3, VS 17.12.35410.144
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0-rc.2.24473.5
  Architecture: x64
  Commit:       990ebf52fc

.NET SDKs installed:
  8.0.206 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.2.24474.11 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.2.24474.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24473.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.2.24474.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Other information

_No response_

### PR DESCRIPTION
**Pull request by vcsjones**
CNG, by default, loads PKCS#12 certificate private keys as "AllowExport", not "AllowsPlaintextExport". When users attempt to export the private key from a loaded PKCS#12, they will receive an error that the operation is not permitted because they are expected to perform an encrypted export.

This is counter-intuitive to some people, as the general expectation is that they can export private keys they just loaded. Starting in .NET 9, we are loading more PKCS#12 private keys in CNG instead of the legacy CSP, meaning users will hit this problem more. This is also a regression from .NET 8. The default provider changed, meaning keys that were once exportable no longer are.

This pull request makes a change similar to what we do for macOS. If a user asks for an unencrypted export of the private key, and the key does not permit that, we will ask CNG for an encrypted export of the private key and decrypt it for them. This makes the unencrypted exports "just work", as they do on other platforms.

Fixes #109059

### CODE REVIEW

File: src/libraries/Common/src/System/Security/Cryptography/ECDsaCng.ImportExport.cs [hunk 1]
```diff
@@ -105,18 +113,38 @@ public override ECParameters ExportParameters(bool includePrivateParameters)
         {
             ECParameters ecparams = default;
 
+            const string TemporaryExportPassword = "DotnetExportPhrase";
```
Comment (jkoritzinsky) [inline src/libraries/Common/src/System/Security/Cryptography/ECDsaCng.ImportExport.cs:116]: Are we going to have a problem with CredScan after we merge this? We should try pushing this change to the internal mirror and make sure it doesn't trip CredScan before we merge this.

Comment (vcsjones) [reply src/libraries/Common/src/System/Security/Cryptography/ECDsaCng.ImportExport.cs:116]: I was back-channeling with @GrabYourPitchforks on this - we (well, Levi) is going to run it - especially since this might be a thing we try to fix for 9.0.

File: src/libraries/Common/src/System/Security/Cryptography/ECDsaCng.ImportExport.cs [hunk 2]
```diff
@@ -264,5 +292,48 @@ public override bool TryExportEncryptedPkcs8PrivateKey(
                 destination,
                 out bytesWritten);
         }
+
+        private bool PlaintextOnlyExport
```
Comment (bartonjs) [inline src/libraries/Common/src/System/Security/Cryptography/ECDsaCng.ImportExport.cs:296]: It's actually EncryptedOnlyExport... Plaintext is what's not allowed :smile:

Comment (vcsjones) [reply src/libraries/Common/src/System/Security/Cryptography/ECDsaCng.ImportExport.cs:296]: The name makes a certain amount of sense to me, but probably only me. So, will fix it.

File: src/libraries/Common/src/System/Security/Cryptography/ECDsaCng.ImportExport.cs [hunk 3]
```diff
@@ -87,10 +88,17 @@ public override void ImportParameters(ECParameters parameters)
...
+            {
+                return ExportPrivateExplicitParameters();
+            }
+            else
+            {
+                byte[] blob = ExportFullKeyBlob(includePrivateParameters: false);
+                ECParameters ecparams = default;
+                ECCng.ExportPrimeCurveParameters(ref ecparams, blob, includePrivateParameters: false);
+                return ecparams;
+            }
```
Comment (bartonjs) [inline src/libraries/Common/src/System/Security/Cryptography/ECDsaCng.ImportExport.cs:101]: What about ECDH?  Can this easily be lifted into ECCng to avoid duplication?

And, sure, "what about DSA?"

File: src/libraries/System.Security.Cryptography/tests/X509Certificates/ExportTests.cs [hunk 4]
```diff
@@ -441,44 +442,168 @@ public static void ECDsa_Export_DefaultKeyStorePermitsUnencryptedExports_ExportP
...
+        {
+            using (ECDsa ca = ECDsa.Create(ECCurve.NamedCurves.nistP256))
+            {
+                CertificateRequest issuerRequest = new CertificateRequest(
+                    new X500DistinguishedName("CN=root"),
+                    ca,
+                    HashAlgorithmName.SHA256);
+
+                issuerRequest.CertificateExtensions.Add(
+                    new X509BasicConstraintsExtension(true, false, 0, true));
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/tests/X509Certificates/ExportTests.cs:543]: This could be

```suggestion
                    X509BasicConstraintsExtension.CreateForCertificateAuthority());
```

but that's just aesthetics.

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/ECDsaCng.cs [hunk 5]
```diff
@@ -151,6 +151,21 @@ private void AcceptImport(CngPkcs8.Pkcs8Response response)
 
         public override bool TryExportPkcs8PrivateKey(Span<byte> destination, out int bytesWritten)
         {
+            const CngExportPolicies Exportable = CngExportPolicies.AllowPlaintextExport | CngExportPolicies.AllowExport;
+            bool encryptedOnlyExport = (Key.ExportPolicy & Exportable) == CngExportPolicies.AllowExport;
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/ECDsaCng.cs:155]: It would be nice if this could be put in just one place.

The best I can come up with is the CngPkcs8 partial that's not in Common (though since we no longer have .Cng split out, either partial might be fine):

```C#
internal static bool AllowsOnlyEncryptedExport(CngKey key)
{
    const CngExportPolicies Exportable = CngExportPolicies.AllowPlaintextExport | CngExportPolicies.AllowExport;
    return (key.ExportPolicy & Exportable) == CngExportPolicies.AllowExport;
}
```

Just because having the same const and bitmask copied over and over makes me nervous.

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
@GrabYourPitchforks ran 3811dde through credscan and reported it came back "clean", so, merging.
