### PR TITLE
[RuntimeAsync] Remove reflection TODOs. Add tests.

### LINKED ISSUE #121762: [RuntimeAsync] TODO in ModuleBuilder_GetMemberRefOfMethodInfo
Looks like:

```c
    // TODO: (async) revisit and examine if this needs to be supported somehow
    if (pMeth->IsAsyncVariantMethod())
    {
        _ASSERTE(!"Async variants should be hidden from reflection.");
        COMPlusThrow(kNotSupportedException);
    }
```

We need to follow up on this and remove the TODOs as a result of either:
- confirming that what we have is correct. Perhaps add a comment why it is correct.
- fix the code and ideally add tests.

Most likely we should not see Async Thunks here and just an assert would be enough. 
We may see an async-callconv helper like `Await` though. If it is possible to get here with those, it should throw. Also will need a test.

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #121764
Fixes: #121762

Following up on TODOs. Contributes to: #115094

Added scenarios for other ways to get reflection info on methods. 
Checks that we only see the formal definitions, never thunks/stubs.

### CODE REVIEW

File: src/coreclr/inc/clrconfigvalues.h [hunk 1]
```diff
@@ -710,7 +710,7 @@ RETAIL_CONFIG_DWORD_INFO(EXTERNAL_EnableRiscV64Zbb,             W("EnableRiscV64
 #endif
 
 // Runtime-async
-RETAIL_CONFIG_DWORD_INFO(UNSUPPORTED_RuntimeAsync, W("RuntimeAsync"), 0, "Enables runtime async method support")
+RETAIL_CONFIG_DWORD_INFO(UNSUPPORTED_RuntimeAsync, W("RuntimeAsync"), 1, "Enables runtime async method support")
```
Comment (VSadov) [inline src/coreclr/inc/clrconfigvalues.h]: TODO: revert the change that enables runtime async before merging

**Comment by VSadov** [comment]
@MichalStrehovsky - are the new scenarios AOT-compatible?

**Comment by VSadov** [comment]
NativeAOT seems to have a bug here

```
How did reflection get a RuntimeMethodHandle for an async variant?
   at System.Diagnostics.DebugProvider.Fail(String, String) + 0x36
   at System.Diagnostics.Debug.Fail(String, String) + 0x32
   at Internal.Runtime.TypeLoader.TypeLoaderEnvironment.TryGetRuntimeMethodHandleComponents(RuntimeMethodHandle, RuntimeTypeHandle&, QMethodDefinition&, RuntimeTypeHandle[]&) + 0x6c
   at Internal.Reflection.Augments.ReflectionAugments.GetMethodFromHandle(RuntimeMethodHandle) + 0x65
   at async!<BaseAddress>+0x3055aa
   at async!<BaseAddress>+0x2fd22e
   at System.Runtime.CompilerServices.AsyncHelpers.RuntimeAsyncTask`1.DispatchContinuations() + 0x13e
   at System.Threading.ThreadPoolWorkQueue.Dispatch() + 0x196
   at System.Threading.WindowsThreadPool.DispatchCallback(IntPtr, IntPtr, IntPtr) + 0x7d
Expected: 100
```

**Comment by MichalStrehovsky** [comment]
> NativeAOT seems to have a bug here

Yep, `MethodBase.GetCurrentMethod` is annotated as RequiresUnreferencedCode, so it can be broken with native AOT (we generate a warning, and therefore the API might not work), but this is fixable. I filed #122546 on it, let's ActiveIssue this new test on that.

> @MichalStrehovsky - are the new scenarios AOT-compatible?

StackFrame.GetMethod is also annotated as RequiresUnreferencedCode so it may not work (and will not). However, we have `DiagnosticMethodInfo.Create(StackFrame)` API that is trim safe. On CoreCLR it simply builds on top of `StackFrame.GetMethod`. If you update the test to use that API, we can ActiveIssue it on #122547. If it stays as StackFrame.GetMethod, it's unsuspportable and the test should not run on native AOT.

File: src/tests/async/reflection/reflection.cs [hunk 2]
```diff
@@ -242,4 +245,126 @@ public static void UnsafeAccessors()
...
+    {
+        public static Task<int> M1() => Task.FromResult(1);
+
+        public async Task<int> M2() => 1;
+
+        public static Task<int> P1 => Task.FromResult(1);
+
+        public static string[] GetAll()
+        {
+            Type t = Type.GetType(typeof(EnumAll).FullName!)!;
```
Comment (MichalStrehovsky) [inline src/tests/async/reflection/reflection.cs]: What's the purpose of this roundtripping?

File: src/tests/async/reflection/reflection.cs [hunk 3]
```diff
@@ -242,4 +245,126 @@ public static void UnsafeAccessors()
...
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    private static async Task<string> FromStackAwait()
+    {
+        return await FromStackAsync();
+    }
+
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    private static Task<string> FromStackTask()
+    {
+        StackFrame stackFrame = new StackFrame(0);
```
Comment (MichalStrehovsky) [inline src/tests/async/reflection/reflection.cs]: Are the stack frames of thunks observable on CoreCLR? I.e. what would happen if this is called from an unawaited call and we construct `new StackFrame(1)`?

File: src/tests/async/reflection/reflection.cs (hunk 2 above)
Comment (VSadov) [reply src/tests/async/reflection/reflection.cs]: The test kind of "evolved" from initially using a hardcoded name of the class. There is no real reason. I will just use `typeof`.

File: src/tests/async/reflection/reflection.cs (hunk 3 above)
Comment (VSadov) [reply src/tests/async/reflection/reflection.cs]: > Are the stack frames of thunks observable on CoreCLR? I.e. what would happen if this is called from an unawaited call and we construct new StackFrame(1)?

I do not know if thunk frames are present in the stack trace. I will check. They used to be present long time ago.  
Just the presence of an extra infrastructure frame would not bother me hugely. async1 can have like 4 or 5 extra frames around await which are meaningless to the user. 

The main concern here is to not expose variants with async calling convention. For the purpose of reflection the runtime async methods have just one form - the Task-returning form that is in the metadata. How JIT emits them is implementation detail.

Either of the following would seem acceptable or at least not blocking for enabling of the feature:
- thunk frames are not in the trace.
- thunk frames are in the trace but report the MethodInfo for the "real" method.
- thunk frames are in the trace but report `null` for MethodInfo

It is worth adding a test for StackFrame(1) though, Thanks!

I also wonder what we get for the resume frame.

Comment (VSadov) [reply src/tests/async/reflection/reflection.cs]: It looks like CoreCLR does not report thunks and does not report resume stubs in these APIs. 
Only "real" (Task-returning) methods are visible via `StackFrame(int)`, even though we may actually be running a runtime async variant. 
I think this is the best/least-surprising from UX perspective.

Also it looks like `DiagnosticMethodInfo` does not report the method signature, only the name. I still need `StackFrame.GetMethod` flavor of the test to be able to check if the methodinfos are for async or Task variants. 

Thus I will have two flavors of the test:
- based on `StackFrame.GetMethod`, which will not be testing on NativeAOT
- based on `DiagnosticMethodInfo.Create(StackFrame)`, will run on both CoreCLR and NativeAOT.

File: src/tests/async/reflection/reflection.cs [hunk 4]
```diff
@@ -0,0 +1,452 @@
...
+        Accessors2.accessor<int>(null, 7).GetAwaiter().GetResult();
+        Assert.Equal(4, PrivateAsync1<int>.s);
+        Assert.Equal(4, PrivateAsync2.s);
+
+        Accessors1<int>.accessor(null, 7).GetAwaiter().GetResult();
+        Assert.Equal(8, PrivateAsync1<int>.s);
+        Assert.Equal(8, PrivateAsync2.s);
+    }
+
+    [Fact]
```
Comment (VSadov) [inline src/tests/async/reflection/reflection.cs:249]: New tests are from here downwards. 
(so it is easier to review, since the file has been renamed, it may not be clear what is new)

File: src/coreclr/vm/commodule.cpp [hunk 5]
```diff
@@ -302,7 +302,6 @@ extern "C" INT32 QCALLTYPE ModuleBuilder_GetMemberRefOfMethodInfo(QCall::ModuleH
         COMPlusThrow(kNotSupportedException);
     }
 
-    // TODO: (async) revisit and examine if this needs to be supported somehow
     if (pMeth->IsAsyncVariantMethod())
```
Comment (jkotas) [inline src/coreclr/vm/commodule.cpp]: I would change both this and the earlier IsArray case to just asserts. `_ASSERTE(!pMeth->IsArray())` and `_ASSERTE(!(pMeth->IsAsyncVariantMethod())`.

File: src/coreclr/vm/runtimehandles.cpp [hunk 6]
```diff
@@ -1863,8 +1863,7 @@ extern "C" void QCALLTYPE RuntimeMethodHandle_StripMethodInstantiation(MethodDes
 //          async variants for task-returning methods
 //
 // For {task-returning, async} variants Reflection hands out only the task-returning variant.
-//  the async varinat is an implementation detail that conceptually does not exist.
-//  TODO: (async) the filtering may not cover all scenarios. Review and add tests.
+//  the async variant is an implementation detail that conceptually does not exist.
```
Comment (jkotas) [inline src/coreclr/vm/runtimehandles.cpp:1866]: Does `MethodBase.GetCurrentMethod()` work correctly inside async methods?

Comment (jkotas) [reply src/coreclr/vm/runtimehandles.cpp:1866]: Ok, I see you have added test for that.

Comment (jkotas) [reply src/coreclr/vm/runtimehandles.cpp:1866]: What makes `MethodBase.GetCurrentMethod()` work inside async methods?

I would expect MethodBase_GetCurrentMethod to have a code somewhere that flips to Task returning method, but I do not see any.

Comment (VSadov) [reply src/coreclr/vm/runtimehandles.cpp:1866]: > Does `MethodBase.GetCurrentMethod()` work correctly inside async methods?

Yes. I have added tests in this PR. For all kind of stack situations like inside async, Task-returning, one stack level up...

There is a test for `MethodBase.GetCurrentMethod()` as well. For both async and ordinary Task-returning (just in case).

Comment (VSadov) [reply src/coreclr/vm/runtimehandles.cpp:1866]: Yes - on CoreCLR. On NativeAOT it may work, in theory, but not right now, tracking issue - https://github.com/dotnet/runtime/issues/122546

Comment (VSadov) [reply src/coreclr/vm/runtimehandles.cpp:1866]: > I would expect MethodBase_GetCurrentMethod to have a code somewhere that flips to Task returning method, but I do not see any.

Hmm. It works as expected. 

If it gets to the method via methoddef token at some point, it will get the definition in the metadata. Maybe because of that.

Comment (jkotas) [reply src/coreclr/vm/runtimehandles.cpp:1866]: It does not sound very robust to return the asynccall methoddesc to reflection, and then hope the reflection will fix it up before doing something with it. Could you please check how it actually works and whether we are happy with it?

Comment (VSadov) [reply src/coreclr/vm/runtimehandles.cpp:1866]: Actually there is a flip. It is in `RuntimeMethodHandle_GetStubIfNeededSlow`

https://github.com/dotnet/runtime/blob/20805161391d45095f4bcf27d0483f600e608b10/src/coreclr/vm/runtimehandles.cpp#L1930-L1934

The earlier fixes for reflection relied on that too. 

`GetStubIfNeededInternal` blocks async variants (intentionally, added in #118045). 
https://github.com/dotnet/runtime/blob/20805161391d45095f4bcf27d0483f600e608b10/src/coreclr/vm/runtimehandles.cpp#L1902-L1904

Then the resolution hits the slow path, which does the flip.
Then the result is cached by the caller.

Comment (VSadov) [reply src/coreclr/vm/runtimehandles.cpp:1866]: I just forgot we did that.
(it is actually in the method that was marked `//  TODO: (async) the filtering may not cover all scenarios. Review and add tests.`)

Comment (jkotas) [reply src/coreclr/vm/runtimehandles.cpp:1866]: ok

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/commodule.cpp [hunk 7]
```diff
@@ -295,20 +295,12 @@ extern "C" INT32 QCALLTYPE ModuleBuilder_GetMemberRefOfMethodInfo(QCall::ModuleH
...
-    {
-        _ASSERTE(!"Async variants should be hidden from reflection.");
-        COMPlusThrow(kNotSupportedException);
-    }
+    // Should not have come here.
+    _ASSERTE(!pMeth->IsArray());
+    // Async variants should be hidden from reflection.
+    _ASSERTE(!pMeth->IsAsyncVariantMethod());
 
+    // Otherwise, we want to return memberref token.
```
Comment (jkotas) [inline src/coreclr/vm/commodule.cpp]:
```suggestion
```

**Comment by VSadov** [comment]
Thanks!
