### PR TITLE
Use ReflectionOnly as serialization mode in case dynamic code runtime feature is not supported

### LINKED ISSUE #56533: iOS/AOT: XmlSerializer.Deserialize throws Attempting to JIT compile method 'void Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializerContract:.ctor ()' while running in aot-only mode.
### Description

Calling XmlSerializer.Deserialize ends up throwing a System.ExecutionEngineException: "Attempting to JIT compile method 'void Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializerContract:.ctor ()' while running in aot-only mode."

```
EXCEPTION: System.InvalidOperationException: XmlSerializeErrorDetails, 0, 0
 ---> System.ExecutionEngineException: Attempting to JIT compile method 'void Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializerContract:.ctor ()' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean ) in System.Private.CoreLib.dll:token 0x600269a+0x5
   Exception_EndOfInnerExceptionStack
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader , String , XmlDeserializationEvents ) in System.Private.Xml.dll:token 0x6001b05+0x10d
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader , String ) in System.Private.Xml.dll:token 0x6001b04+0x0
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader ) in System.Private.Xml.dll:token 0x6001b02+0x0
   at MySimpleApp.Program.XmlSerializationTest.Response.Deserialize(String xml) in /Users/rolf/work/maccore/main/xamarin-macios/tests/dotnet/MySimpleApp/AppDelegate.cs:line 67
   at MySimpleApp.Program.XmlSerializationTest.Bug1820_GenericList() in /Users/rolf/work/maccore/main/xamarin-macios/tests/dotnet/MySimpleApp/AppDelegate.cs:line 184
   at MySimpleApp.Program.Main(String[] args) in /Users/rolf/work/maccore/main/xamarin-macios/tests/dotnet/MySimpleApp/AppDelegate.cs:line 22
```

Test code: https://github.com/rolfbjarne/xamarin-macios/blob/c8014a6b6fd759159b409df19062f11b57ae8e2c/tests/dotnet/MySimpleApp/AppDelegate.cs#L21-L187

To reproduce:

1. Download & install Xcode 13 beta 3.
2. Clone my fork of xamarin-macios, and checkout the [`Bug1820_GenericList-testcase`](https://github.com/rolfbjarne/xamarin-macios/tree/Bug1820_GenericList-testcase) branch, and build it:

        git clone https://github.com/rolfbjarne/xamarin-macios
        git checkout Bug1820_GenericList-testcase
        cd xamarin-macios
        ./configure --enable-dotnet --enable-xamarin
        make reset
        make all -j8
        make install -j8

3. Connect an iOS device
4. Build & run the test project:

        make -C tests/dotnet/MySimpleApp/iOS run-dev

### Configuration

6.0.100-rc.1.21377.4

### Regression?

With regards to legacy Xamarin, yes.

### PR DESCRIPTION
**Pull request by MaximLipnin**
Fixes https://github.com/dotnet/runtime/issues/56533

### CODE REVIEW

File: src/tests/FunctionalTests/iOS/Simulator/XmlSerializer_Deserialize/Program.cs [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+using System.Xml.Serialization;
+
+public static class Program
+{
+    [DllImport("__Internal")]
+    public static extern void mono_ios_set_summary (string value);
+
+    public static async Task<int> Main(string[] args)
+    {
+        mono_ios_set_summary($"Starting functional test");
```
Comment (jkotas) [inline src/tests/FunctionalTests/iOS/Simulator/XmlSerializer_Deserialize/Program.cs:20]: Is it really necessary to use these internal calls in tests?

File: src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs [hunk 2]
```diff
@@ -109,7 +110,7 @@ internal enum SerializationMode
 
     public class XmlSerializer
     {
-        internal static SerializationMode Mode { get; set; } = SerializationMode.ReflectionAsBackup;
+        internal static SerializationMode Mode { get; set; } = RuntimeFeature.IsDynamicCodeSupported ? SerializationMode.ReflectionAsBackup : SerializationMode.ReflectionOnly;
```
Comment (jkotas) [inline src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:113]:
```suggestion
        internal static SerializationMode Mode => RuntimeFeature.IsDynamicCodeSupported ? SerializationMode.ReflectionAsBackup : SerializationMode.ReflectionOnly;
```
Is it possible to return the constant directly instead of caching it in a static variable, to enable linker to trim the unreachable code?

File: src/tests/FunctionalTests/iOS/Simulator/XmlSerializer_Deserialize/Program.cs (hunk 1 above)
Comment (jkotas) [reply src/tests/FunctionalTests/iOS/Simulator/XmlSerializer_Deserialize/Program.cs]: Hmmm, this internal call is actually in all existing tests under `src/tests/FunctionalTests`. Do we need it in all of them?

File: src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs (hunk 2 above)
Comment (MaximLipnin) [reply src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs]: There are some tests checking for the `Mode` setter, e.g. https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.Xml/tests/XmlSerializer/XmlSerializerTests.cs#L22-L27

Comment (stephentoub) [reply src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:113]: Are those even used?  Where are these compilation constants set?
https://github.com/dotnet/runtime/blob/81907137fc454e97a98eb5a7eae21b6c23bcb583/src/libraries/System.Private.Xml/tests/XmlSerializer/XmlSerializerTests.cs#L21
cc: @StephenMolloy

Comment (stephentoub) [reply src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:113]: Ah, nevermind, there's a separate project that sets at least one of them:
https://github.com/dotnet/runtime/blob/81907137fc454e97a98eb5a7eae21b6c23bcb583/src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj#L3

**Comment by jkotas** [comment]
> Revert Mode to usual property

You may be able to keep this optimization by using the same pattern as DataContractSerializer:
```
        private static SerializationMode s_mode = SerializationMode.ReflectionAsBackup;

        internal static SerializationMode Mode
        {
            get => RuntimeFeature.IsDynamicCodeSupported ? s_mode : SerializationMode.ReflectionOnly; }
            set => s_mode = value;
        }
```

File: src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs (hunk 2 above)
Comment (StephenMolloy) [reply src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:113]: Yeah, at this stage of the game, I'd stick with the original proposed change that caches the value at initialization so we maintain the ability to override when needed. (Which I believe is pretty much just testing right now.) We have a desire to potentially make the reflection-based serializer the primary option in the future, but we've got work to do to bring it up to par with the ILGen serializer before we can do that. Having a switch that is not stuck in one position is helpful.

**Review by steveisok — APPROVED** [review]

**Comment by MaximLipnin** [comment]
We can merge it if there are no any other comments.

**Review by jkotas — APPROVED** [review]
