### PR TITLE
[wasm] Consolidate interop tables generators

### LINKED ISSUE #67970: Error using double or float values with WebAssembly
### Description

Seeing a bug when using SQLitePCL.Raw preview and also see the same bug in Steve Sandersons Blaze Orbital sample when using double/float in entity classes. Works fine with decimals! Tried with EF Core and SQLite-net. 

### Reproduction Steps

https://github.com/mark-cb/BlazorSQLiteWasm

### Expected behavior

Double and floats should work the same as decimals. 

### Actual behavior

Error:
/__w/1/s/src/mono/mono/mini/aot-runtime-wasm.c:113 /__w/1/s/src/mono/mono/mini/aot-runtime-wasm.c:113
Uncaught ExitStatus

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

https://github.com/ericsink/SQLitePCL.raw/issues/480

### PR DESCRIPTION
**Pull request by maraf**
I have slightly deviated from the design in https://github.com/dotnet/runtime/issues/67970#issuecomment-1121364824
- `mono_wasm_install_interp_to_native_callback` installs callback that is invoked from `mono_wasm_get_interp_to_native_trampoline`. The callback is installed in `driver.c`.
- `mono_wasm_interp_method_args_get_*arg` returns concrete argument value instead of pointer to all args.
- The m2n generator is integrated both in `wasm.proj` and `WasmApp.Native.targets`. In runtime, the icall generator just looks for signatures and pass them to the m2n generator, because they are registered statically in the `icall-def.h`.
- PInvoke, icall and m2n generators are combined as `ManagedToNativeGenerator`.

Fixes https://github.com/dotnet/runtime/issues/67970.

### CODE REVIEW

File: src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs [hunk 1]
```diff
@@ -0,0 +1,197 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System;
```
Comment (radical) [inline src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs:4]: new class, we can use `#nullable enable` here :)

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs [hunk 2]
```diff
@@ -11,7 +11,7 @@
 using Microsoft.Build.Framework;
 using Microsoft.Build.Utilities;
 
-public class PInvokeTableGenerator : Task
+public class PInvokeTableGenerator
 {
     [Required, NotNull]
```
Comment (radical) [inline src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:16]: Since this is no longer a task, the `Required`, and `Output` attributes should be removed.
And remove the `NotNull` ones on the properties because these are not guaranteed to be null by msbuild any longer (as not a task). Instead, these can be accepted as constructor args, and thus can be non-nullable types.

File: src/tasks/WasmAppBuilder/IcallTableGenerator.cs [hunk 3]
```diff
@@ -253,18 +267,18 @@ private static string MapType (Type t)
     {
         switch (t.Name)
```
Comment (radical) [inline src/tasks/WasmAppBuilder/IcallTableGenerator.cs:268]: switch expression would work well here

**Comment by maraf** [comment]
@radical @lambdageek How to get rid of these errors?

```
/__w/1/s/src/mono/mono/mini/aot-runtime-wasm.c:89:1: error: no previous prototype for function 'mono_wasm_install_interp_to_native_callback' [-Werror,-Wmissing-prototypes]
  mono_wasm_install_interp_to_native_callback (MonoWasmNativeToInterpCallback cb)
  ^
```

I have found that other such APIs use `MONO_API_FUNCTION`, but mine (those for reading parameters) needs to have a parameter of type `InterpMethodArguments` which is not public.

File: src/mono/wasm/runtime/pinvoke.h [hunk 4]
```diff
@@ -23,4 +26,29 @@ wasm_dl_get_native_to_interp (const char *key, void *extra_arg);
...
 
+
+typedef void* (*MonoWasmNativeToInterpCallback) (char * cookie);
+
+void
+mono_wasm_install_interp_to_native_callback (MonoWasmNativeToInterpCallback cb);
+
+typedef struct {
+	
+} InterpMethodArguments;
```
Comment (lambdageek) [inline src/mono/wasm/runtime/pinvoke.h:37]: 1. The usual way to do this would be something like `typedef struct _InterpMethodArguments InterpMethodArguments` without providing a definition of `struct _InterpMethodArguments` in this header file.
2. Use a `Mono` prefix on the struct definition: `typedef struct _MonoInterpMethodArguments MonoInterpMethodArguments`

File: src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs [hunk 5]
```diff
@@ -0,0 +1,169 @@
...
+    private static void Emit(StreamWriter w, IEnumerable<string> cookies)
+    {
+        w.WriteLine("/*");
+        w.WriteLine("* GENERATED FILE, DON'T EDIT");
+        w.WriteLine("* Generated by InterpToNativeGenerator");
+        w.WriteLine("*/");
+        w.WriteLine("");
+        w.WriteLine(@"#include ""pinvoke.h""");
+        w.WriteLine(@"#include <stdlib.h>");
+        w.WriteLine("");
```
Comment (lambdageek) [inline src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs:66]: Use a [C# 11 raw string literal](https://devblogs.microsoft.com/dotnet/csharp-11-preview-updates/#raw-string-literals)

```

w.WriteLine ("""
/*
 * GENERATED FILE, DON'T EDIT
 * Generated by InterpToNativeGenerator
 *
 */
 
 #include "pinvoke.h"
 #include <stdlib.h>
""");
```

**Review by lambdageek — COMMENTED** [review]
overall seems ok; i'll look in more detail on Monday

File: src/mono/mono/mini/aot-runtime-wasm.c [hunk 6]
```diff
@@ -83,7 +83,43 @@ get_long_arg (InterpMethodArguments *margs, int idx)
 	return p.l;
 }
 
-#include "wasm_m2n_invoke.g.h"
+static MonoWasmNativeToInterpCallback mono_wasm_interp_to_native_callback;
+
+MONO_API void
+mono_wasm_install_interp_to_native_callback (MonoWasmNativeToInterpCallback cb)
```
Comment (lambdageek) [inline src/mono/mono/mini/aot-runtime-wasm.c:89]: don't use `MONO_API` in the .c file.


To make the warning about prototypes go away, add a declaration for this function (and the others) to some header that's included by `aot-runtime-wasm.c`

For example, `aot-runtime.h`:

```c

#ifdef HOST_WASM

MONO_API void
mono_wasm_install_interp_to_native_callback (MonoWasmNativeToInterpCallback cb);

MONO_API int
mono_wasm_interp_method_args_get_iarg (InterpMethodArguments *margs, int i);

/* ... etc ... */
#endif
```

File: src/mono/wasm/build/WasmApp.Native.targets [hunk 7]
```diff
@@ -1,16 +1,14 @@
...
-  <UsingTask TaskName="PInvokeTableGenerator" AssemblyFile="$(WasmAppBuilderTasksAssemblyPath)" />
-  <UsingTask TaskName="IcallTableGenerator" AssemblyFile="$(WasmAppBuilderTasksAssemblyPath)" />
+  <UsingTask TaskName="ManagedToNativeGenerator" AssemblyFile="$(WasmAppBuilderTasksAssemblyPath)" />
   <UsingTask TaskName="Microsoft.WebAssembly.Build.Tasks.EmccCompile" AssemblyFile="$(WasmAppBuilderTasksAssemblyPath)" />
 
   <PropertyGroup>
     <_WasmBuildNativeCoreDependsOn>
       _PrepareForWasmBuildNative;
       _GenerateDriverGenC;
-      _GeneratePInvokeTable;
```
Comment (radical) [inline src/mono/wasm/build/WasmApp.Native.targets:12]: The corresponding targets can be removed too.

File: src/mono/wasm/runtime/pinvoke.h [hunk 8]
```diff
@@ -11,6 +13,7 @@ typedef struct {
 	void *arg;
 } InterpFtnDesc;
 
+
```
Comment (radical) [inline src/mono/wasm/runtime/pinvoke.h:16]:
```suggestion
```

File: src/tasks/WasmAppBuilder/IcallTableGenerator.cs [hunk 9]
```diff
@@ -14,44 +14,32 @@
...
     //
-    public void GenIcallTable(string runtimeIcallTableFile, string[] assemblies)
+    public IEnumerable<string> GenIcallTable(string? runtimeIcallTableFile, string[] assemblies, string? outputPath)
     {
-        ReadTable (runtimeIcallTableFile);
+        _icalls.Clear();
+        signatures.Clear();
+
+        if (runtimeIcallTableFile != null)
+            ReadTable (runtimeIcallTableFile);
```
Comment (radical) [inline src/tasks/WasmAppBuilder/IcallTableGenerator.cs:41]:
```suggestion
            ReadTable(runtimeIcallTableFile);
```

File: src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs [hunk 10]
```diff
@@ -0,0 +1,167 @@
...
+            {
+                w.WriteLine($"\tvoid *retval = mono_wasm_interp_method_args_get_retval (margs);");
+                w.WriteLine($"\t*({TypeToSigType(c[0])}*)retval = res;");
+            }
+
+            w.WriteLine("}\n");
+        }
+
+        Array.Sort(signatures);
+
```
Comment (radical) [inline src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs:111]:
```suggestion
```

File: src/tasks/WasmAppBuilder/CookieHelper.cs [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+using System.Text;
+using System.Threading.Tasks;
+
+internal static class CookieHelper
+{
+    private static string TypeToChar(Type t)
+    {
+        string? c = t.Name switch
+        {
+            nameof(String) => "I",
```
Comment (radical) [inline src/tasks/WasmAppBuilder/CookieHelper.cs:17]: Maybe make `I, L, F, D` into an enum, so the various places in the code are in sync, and handle all the cases.

File: src/tasks/WasmAppBuilder/CookieHelper.cs [hunk 12]
```diff
@@ -0,0 +1,67 @@
...
+                c = "I";
+            else if (t.IsEnum)
+                c = TypeToChar(t.GetEnumUnderlyingType());
+            else if (t.IsValueType)
+                c = "I";
+        }
+
+        if (c == null)
+        {
+            throw new NotSupportedException($"Type '{t.Name}' is not supported.");
```
Comment (radical) [inline src/tasks/WasmAppBuilder/CookieHelper.cs:51]: If we return null from this method, then the caller can throw a `LogAsErrorException` with details about the method containing this unsupported type, which would be more useful, and actionable for the user.

File: src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs [hunk 13]
```diff
@@ -0,0 +1,167 @@
...
+    public InterpToNativeGenerator(TaskLoggingHelper log) => Log = log;
+
+    private static string TypeToSigType(char c) => c switch
+    {
+        'V' => "void",
+        'I' => "int",
+        'L' => "int64_t",
+        'F' => "float",
+        'D' => "double",
+        _ => throw new Exception("Can't handle " + c)
```
Comment (radical) [inline src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs:34]: This should indicate a bug in the task, correct? It should be eliminated though if we use an enum string.
In any case, if we want to throw an exception here, then use a more specific type which can be caught by the caller, and a useful error message with details of the method causing this be emitted.

File: src/tasks/WasmAppBuilder/IcallTableGenerator.cs [hunk 14]
```diff
@@ -14,44 +14,32 @@
 using Microsoft.Build.Framework;
 using Microsoft.Build.Utilities;
 
-public class IcallTableGenerator : Task
+public class IcallTableGenerator
```
Comment (radical) [inline src/tasks/WasmAppBuilder/IcallTableGenerator.cs:17]: internal

File: src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs (hunk 13 above)
Comment (maraf) [reply src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs:34]: Yes, it indicates bug inside of the task. Other generators produce signature that this one can't handle. Part of the working with this string signature is also in the c code and here it is used only internally. I think that converting it to a list of enums isn't necessary. Anyway I have refactored so most of the work is handled in `SignatureMapper`.

File: src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs [hunk 15]
```diff
@@ -0,0 +1,180 @@
...
+        w.WriteLine("};");
+
+        w.WriteLine("static const char* interp_to_native_signatures[] = {");
+
+        foreach (var signature in signatures)
+            w.WriteLine($"\t\"{signature}\",");
+
+        w.WriteLine("};");
+
+        w.WriteLine($"unsigned int interp_to_native_signatures_count = {signatures.Length};");
```
Comment (lambdageek) [inline src/tasks/WasmAppBuilder/InterpToNativeGenerator.cs:130]: nit: should be `static`, also.

Can be fixed in a follow-up

**Review by lambdageek — APPROVED** [review]
lgtm

**Review by radical — APPROVED** [review]
LGTM! 👍
