### PR TITLE
Fix DispatchProxy throwing TypeLoadException for static virtual members

### LINKED ISSUE #102716: DispatchProxy throws TypeLoadException for static virtual members
### Description

It seems `DispatchProxyGenerator` was never updated to support C#11 static virtual members, it throws a `TypeLoadException` when used with an interface that contains any.

### Reproduction Steps

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```

```C#
using System.Reflection;

DispatchProxy.Create<ITest, TestDispatchProxy>();

file interface ITest
{
    static virtual object? TestProperty { get; set; }

    static virtual void TestMethod() { }
}

file class TestDispatchProxy : DispatchProxy
{
    protected override object? Invoke(MethodInfo? targetMethod, object?[]? args)
    {
        throw new NotImplementedException();
    }
}
```

### Expected behavior

A valid instance is created.

### Actual behavior

```
System.TypeLoadException
  HResult=0x80131522
  Message=Signature of the body and declaration in a method implementation do not match.  Type: 'generatedProxy_1'.  Assembly: 'ProxyBuilder, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.Emit.RuntimeTypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.RuntimeTypeBuilder.CreateTypeInfoImpl()
   at System.Reflection.Emit.TypeBuilder.CreateType()
   at System.Reflection.DispatchProxyGenerator.ProxyBuilder.CreateType()
   at System.Reflection.DispatchProxyGenerator.ProxyAssembly.GenerateProxyType(Type baseType, Type interfaceType, String interfaceParameter, String proxyParameter)
   at System.Reflection.DispatchProxyGenerator.ProxyAssembly.GetProxyType(Type baseType, Type interfaceType, String interfaceParameter, String proxyParameter)
   at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(Type baseType, Type interfaceType, String interfaceParameter, String proxyParameter)
   at System.Reflection.DispatchProxy.Create[T,TProxy]()
   at Program.<Main>$(String[] args) in Program.cs:line 3
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Rans4ckeR**
Fixes: #102716

### CODE REVIEW

File: src/libraries/System.Reflection.DispatchProxy/tests/DispatchProxyTests.cs [hunk 1]
```diff
@@ -557,6 +557,28 @@ public static void Proxy_Declares_Interface_Properties(bool useGenericCreate)
...
+        [InlineData(false)]
+        [InlineData(true)]
+        public static void Proxy_Declares_Interface_Static_Virtual_Methods(bool useGenericCreate)
+        {
+            TestType_IStaticVirtualMethodService proxy = CreateHelper<TestType_IStaticVirtualMethodService, TestDispatchProxy>(useGenericCreate);
+            MethodInfo methodInfo = proxy.GetType().GetTypeInfo().GetDeclaredMethod(nameof(TestType_IStaticVirtualMethodService.TestMethod));
+            Assert.NotNull(methodInfo);
+            Assert.True((methodInfo.Attributes & MethodAttributes.Static) != 0);
+        }
+
```
Comment (jkotas) [inline src/libraries/System.Reflection.DispatchProxy/tests/DispatchProxyTests.cs:581]: We also need test that invoke the method and that the verify that the proxy received correct values of the method arguments.

Comment (Rans4ckeR) [reply src/libraries/System.Reflection.DispatchProxy/tests/DispatchProxyTests.cs:581]: > We also need tests that invoke the method and that verify that the proxy received correct values of the method arguments.

Do you mean to test the result of e.g. this?
```C#
private static string TestStaticMethodInvocation<T>(T proxy)
    where T : TestType_IStaticVirtualMethodService
    => T.TestMethod();
```
After all, the method cannot be invoked on the proxy instance itself since it's static.

Comment (jkotas) [reply src/libraries/System.Reflection.DispatchProxy/tests/DispatchProxyTests.cs:581]: Good point!

So what would be the behavior of calling `methodInfo.Invoke(...)` in this test case?

Comment (Rans4ckeR) [reply src/libraries/System.Reflection.DispatchProxy/tests/DispatchProxyTests.cs:581]: > Good point!
> 
> So what would be the behavior of calling `methodInfo.Invoke(...)` in this test case?

Unless I'm doing something wrong, this results in:
```
System.InvalidProgramException : Common Language Runtime detected an invalid program.
        Stack Trace:
             at generatedProxy_13.TestMethod(String)
             at InvokeStub_generatedProxy_13.TestMethod(Object, Span`1)
             at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Being able to call a static interface method on an instance of the interface should not be possible, so something like this seems expected.

The point is not to be able to call this method on the proxy instance but rather to be able to generate the proxy so one can call the non-static members of the interface, which is not possible atm since it fails to generate the proxy at all.

File: src/libraries/System.Reflection.DispatchProxy/tests/DispatchProxyTests.cs [hunk 2]
```diff
@@ -557,6 +557,52 @@ public static void Proxy_Declares_Interface_Properties(bool useGenericCreate)
...
+            {
+                methodInfo.Invoke(proxy, null);
+            }
+            catch (Exception e)
+            {
+                actualException = e;
+            }
+
+            Assert.NotNull(actualException);
+            Assert.IsType<NotSupportedException>(actualException.InnerException);
```
Comment (jkotas) [inline src/libraries/System.Reflection.DispatchProxy/tests/DispatchProxyTests.cs:603]:
```suggestion
            Assert.Throws<NotSupportedException>(() => methodInfo.Invoke(proxy, null));
```

**Review by jkotas — APPROVED** [review]
Thanks

**Review by buyaa-n — APPROVED** [review]
Thank you @Rans4ckeR!
