### PR TITLE
[mono][aot] Fix compilation crashes when type load exception is generated in code

### LINKED ISSUE #110003: Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 134
_From @mlancione on Wed, 20 Nov 2024 05:02:37 GMT_

### Apple platform

iOS

### Framework version

net9.0-*

### Affected platform version

.NET 9.0.100

### Description

Getting a failed to AOT compile error when building the below repro project.

It seems that adding Microsoft.Maui.Essentials and Microsoft.Extensions.DependencyInjection NuGet packages and referencing a Microsoft.Extensions.DependencyInjection type in code causes the build error.

Note: The build error only happens when UseInterpreter=false and TrimMode=partial.

### Steps to Reproduce

Build repro project:

[AOTBuildError.zip](https://github.com/user-attachments/files/17825188/AOTBuildError.zip)

### Did you find any workaround?

Setting either UseInterpreter=true or TrimMode=full will avoid the build error.

### Build logs

[msbuild.binlog.zip](https://github.com/user-attachments/files/17825181/msbuild.binlog.zip)

_Copied from original issue xamarin/xamarin-macios#21663_

### PR DESCRIPTION
**Pull request by BrzVlad**
Following https://github.com/dotnet/runtime/pull/91261, exception throwing during aot compilation for type load exceptions was replaced with throwing of exception at runtime, as part of the method code. This code insertion could hit some issues in various scenarios. Fixes https://github.com/dotnet/runtime/issues/110003 and https://github.com/dotnet/runtime/issues/109966

### CODE REVIEW

**Comment by vitek-karas** [comment]
Sorry - no idea about the code change... but a question about the regression:
I'm curious how it is that it was in 9.0 for a year and we didn't detect it? Are we missing some tests, should we add them as part of this change?

**Review by steveisok — APPROVED** [review]

File: src/mono/mono/mini/method-to-ir.c [hunk 1]
```diff
@@ -6262,6 +6262,9 @@ method_make_alwaysthrow_typeloadfailure (MonoCompile* cfg, MonoClass* klass)
 	mono_link_bblock (cfg, bb, cfg->bb_exit);
 
 	cfg->disable_inline = TRUE;
+
+	for (int i = 0; i < cfg->header->num_clauses; i++)
```
Comment (lewing) [inline src/mono/mono/mini/method-to-ir.c:6266]:
```suggestion
	for (guint i = 0; i < cfg->header->num_clauses; i++)
```
