### PR TITLE
PlatformNotSupportedException for UNIX domain sockets on iOS/tvOS

### LINKED ISSUE #51335: System.IO.Pipes.Tests Fails on iOS/tvOS
All are failing with some form of `System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/EB1382F4-1DF5-494C-AEAE-7D7E33B18B3B/data/Containers/Data/Application/E75E9C2B-CFE1-4984-9370- ...`

System.IO.Pipes.Tests
System.IO.Pipes.Tests.NamedPipeTest_CreateServer.Unix_GetHandleOfNewServerStream_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_CreateServer.Create_PipeName_Direction_MaxInstances
System.IO.Pipes.Tests.NamedPipeTest_CreateServer.Create_PipeName
System.IO.Pipes.Tests.NamedPipeTest_Specific.MultipleWaitingClients_ServerServesOneAtATime
System.IO.Pipes.Tests.NamedPipeTest_Specific.Unix_GetImpersonationUserName_Succeed
System.IO.Pipes.Tests.NamedPipeTest_Specific.PipeTransmissionMode_Returns_Byte
System.IO.Pipes.Tests.NamedPipeTest_Specific.InvalidReadMode_Throws_ArgumentOutOfRangeException
System.IO.Pipes.Tests.NamedPipeTest_Specific.Unix_BufferSizeRoundtripping
System.IO.Pipes.Tests.NamedPipeTest_Specific.MultipleServers_ServeMultipleClientsConcurrently
System.IO.Pipes.Tests.NamedPipeTest_Specific.MaxNumberOfServerInstances_TooManyServers_Throws
System.IO.Pipes.Tests.NamedPipeTest_Specific.Unix_SetReadModeTo__PipeTransmissionModeByte
System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnect_Throws_Timeout_When_Pipe_Not_Found
System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnectAsync_Throws_Timeout_When_Pipe_Not_Found
System.IO.Pipes.Tests.NamedPipeTest_Specific.ConnectToNonExistentServer_Throws_TimeoutException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Write_DataReadFromDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadWrite_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_DisconnectDuringRead_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_ContinuesOnCurrentSynchronizationContextIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.OperationsOnDisconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Windows_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.WaitForConnectionOnAlreadyConnectedServer_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_CancelPendingTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadWriteByte_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.CopyToAsync_AllDataCopied
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Read_Eof_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Read_DataStoredAtDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadWrite_CustomMemoryManager_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Client_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ZeroByteWrite_OtherDataReceivedSuccessfully
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Disposed_ThrowsObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ConnectOnAlreadyConnectedClient_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.DisposedServerPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ZeroByteRead_BlocksUntilDataAvailableOrNops
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ConcurrentBidirectionalReadsWrites_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.CancelTokenOn_ServerWaitForConnectionAsync_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Server_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_CancelPendingValueTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ClonedClient_ActsAsOriginalClient
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ArgumentValidation_ThrowsExpectedException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.OperationsOnUnconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.OperationsOnDisconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Timeout_Roundtrips
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.DisposedClientPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Flush_ValidOnReadableStream_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ClonedServer_ActsAsOriginalServer
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Flush_ValidOnWriteableStreamWithNoData_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadTimeout_Expires_Throws
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.OperationsOnUnconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadWrite_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Read_Eof_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_ContinuesOnCurrentSynchronizationContextIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ZeroByteWrite_OtherDataReceivedSuccessfully
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_CancelPendingTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.CopyToAsync_AllDataCopied
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_DisconnectDuringRead_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.OperationsOnUnconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.OperationsOnDisconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ConnectOnAlreadyConnectedClient_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Server_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.OperationsOnDisconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Windows_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ClonedServer_ActsAsOriginalServer
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ZeroByteRead_BlocksUntilDataAvailableOrNops
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Write_DataReadFromDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Flush_ValidOnReadableStream_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.CancelTokenOn_ServerWaitForConnectionAsync_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.DisposedClientPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadWrite_CustomMemoryManager_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Read_DataStoredAtDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ClonedClient_ActsAsOriginalClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Client_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ConcurrentBidirectionalReadsWrites_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.DisposedServerPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Flush_ValidOnWriteableStreamWithNoData_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadWriteByte_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ArgumentValidation_ThrowsExpectedException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.OperationsOnUnconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.WaitForConnectionOnAlreadyConnectedServer_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_CancelPendingValueTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Timeout_Roundtrips
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadTimeout_Expires_Throws
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Disposed_ThrowsObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadWrite_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadWrite_CustomMemoryManager_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Read_Eof_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ZeroByteWrite_OtherDataReceivedSuccessfully
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_ContinuesOnCurrentSynchronizationContextIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Disposed_ThrowsObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.CopyToAsync_AllDataCopied
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadWriteByte_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ZeroByteRead_BlocksUntilDataAvailableOrNops
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.OperationsOnUnconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Write_DataReadFromDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ConcurrentBidirectionalReadsWrites_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Server_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Flush_ValidOnReadableStream_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.OperationsOnDisconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.DisposedClientPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.DisposedServerPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ClonedServer_ActsAsOriginalServer
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ConnectOnAlreadyConnectedClient_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Flush_ValidOnWriteableStreamWithNoData_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.OperationsOnDisconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.CancelTokenOn_ServerWaitForConnectionAsync_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.OperationsOnUnconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadTimeout_Expires_Throws
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Read_DataStoredAtDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_CancelPendingTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_DisconnectDuringRead_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Client_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_CancelPendingValueTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ArgumentValidation_ThrowsExpectedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.WaitForConnectionOnAlreadyConnectedServer_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ClonedClient_ActsAsOriginalClient
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Windows_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Timeout_Roundtrips

### LINKED ISSUE #51390: System.IO.Tests fails on iOS/tvOS
System.IO.Tests
System.IO.Tests.StreamReaderTests.ReadAsync_Canceled_ThrowsException
System.IO.Tests.StreamReaderWithBufferedStream_Tests.ReadAsync_Canceled_ThrowsException

```
System.IO.Tests.dll   Failed: 8

Test collection for System.IO.Tests.StreamReaderTests
System.IO.Tests.StreamReaderTests.ReadAsync_Canceled_ThrowsException(method: 1, precanceled: True)
    System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_0857a478a821438b8d2d1f65199c308f' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_0857a478a821438b8d2d1f65199c308f.
System.IO.Tests.StreamReaderTests.ReadAsync_Canceled_ThrowsException(method: 0, precanceled: True)
    System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_1ea60ae654374bfc973cea9724a74f64' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_1ea60ae654374bfc973cea9724a74f64.
System.IO.Tests.StreamReaderTests.ReadAsync_Canceled_ThrowsException(method: 0, precanceled: False)
    System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_b830dd9cd9824540b6976a8ac37287e3' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_b830dd9cd9824540b6976a8ac37287e3.
System.IO.Tests.StreamReaderTests.ReadAsync_Canceled_ThrowsException(method: 1, precanceled: False)
    System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_7f620bba041f408e989383f36a4d4e67' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_7f620bba041f408e989383f36a4d4e67.

Test collection for System.IO.Tests.StreamReaderWithBufferedStream_Tests
System.IO.Tests.StreamReaderWithBufferedStream_Tests.ReadAsync_Canceled_ThrowsException(method: 1, precanceled: False)
    System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_2df4f425b46a42aba0a3f295d7eb6e80' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_2df4f425b46a42aba0a3f295d7eb6e80.
System.IO.Tests.StreamReaderWithBufferedStream_Tests.ReadAsync_Canceled_ThrowsException(method: 0, precanceled: True)
    System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_a18efeb986b94c8c89cbf70d5272b251' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_a18efeb986b94c8c89cbf70d5272b251.
System.IO.Tests.StreamReaderWithBufferedStream_Tests.ReadAsync_Canceled_ThrowsException(method: 1, precanceled: True)
    System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_a805933ed0b74041be0dbb806dbb33a6' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_a805933ed0b74041be0dbb806dbb33a6.
System.IO.Tests.StreamReaderWithBufferedStream_Tests.ReadAsync_Canceled_ThrowsException(method: 0, precanceled: False)
    System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_d33cfc57e83741f980731a4defe8a790' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /private/var/root/Library/Developer/CoreSimulator/Devices/11733F4B-056C-439E-AF1B-8D27E9629CA1/data/Containers/Data/Application/62678B72-71A2-4DF8-AB4A-21BF49015C17/tmp/CoreFxPipe_d33cfc57e83741f980731a4defe8a790.

### PR DESCRIPTION
**Pull request by directhex**
Explicitly mark UNIX domain sockets (and named pipes) with PlatformNotSupportedException.

These never worked on device, where the kernel returns EPERM on socket bind. They worked on the simulator when using `/tmp` as the temporary directory instead of the value from `NSTemporaryDirectory()`, but this seems to be an oversight by Apple rather than by design - and /tmp is not writable on device. In cases where device and simulator differ, we need to present the device scenario to our users as the canonically correct one.

See discussion in https://github.com/dotnet/runtime/pull/73258

Closes: #51390
Closes: #51335

### CODE REVIEW

File: src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs [hunk 1]
```diff
@@ -12,7 +13,8 @@ internal static partial class SocketProtocolSupportPal
 
         public static bool OSSupportsIPv6 { get; } = IsSupported(AddressFamily.InterNetworkV6) && !IsIPv6Disabled();
         public static bool OSSupportsIPv4 { get; } = IsSupported(AddressFamily.InterNetwork);
-        public static bool OSSupportsUnixDomainSockets { get; } = IsSupported(AddressFamily.Unix);
+        // iOS/tvOS ostensibly has AF_UNIX, but throws EPERM on iOS/tvOS 10.0+ on bind
+        public static bool OSSupportsUnixDomainSockets { get; } = IsSupported(AddressFamily.Unix) && !RuntimeInformation.IsOSPlatform(OSPlatform.Create("TVOS")) && !RuntimeInformation.IsOSPlatform(OSPlatform.Create("IOS"));
```
Comment (jkotas) [inline src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs:17]:
```suggestion
        public static bool OSSupportsUnixDomainSockets { get; } = IsSupported(AddressFamily.Unix) && !OperatingSystem.IsIOS() && !OperatingSystem.IsTvOS();
```
These are the right API to use to check for OS. `RuntimeInformation.IsOSPlatform` is deprecated.

File: src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs [hunk 2]
```diff
@@ -12,7 +13,10 @@ internal static partial class SocketProtocolSupportPal
 
         public static bool OSSupportsIPv6 { get; } = IsSupported(AddressFamily.InterNetworkV6) && !IsIPv6Disabled();
         public static bool OSSupportsIPv4 { get; } = IsSupported(AddressFamily.InterNetwork);
-        public static bool OSSupportsUnixDomainSockets { get; } = IsSupported(AddressFamily.Unix);
+        // iOS/tvOS ostensibly has AF_UNIX, but throws EPERM on iOS/tvOS 10.0+ on bind
+        // Mac Catalyst returns true on IsIOS, so we need to explicitly check for the case
+        // "is iOS but not Catalyst" as unsupported, but Catalyst itself is supported.
+        public static bool OSSupportsUnixDomainSockets { get; } = IsSupported(AddressFamily.Unix) && !OperatingSystem.IsTvOS() && (!OperatingSystem.IsIOS() || OperatingSystem.IsMacCatalyst());
```
Comment (teo-tsirpanis) [inline src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs:19]:
```suggestion
        public static bool OSSupportsUnixDomainSockets { get; } = !OperatingSystem.IsTvOS() && (!OperatingSystem.IsIOS() || OperatingSystem.IsMacCatalyst()) && IsSupported(AddressFamily.Unix);
```

The operating system checks are essentislly free and we can entirely skip the call to `IsSupported` on unsupported platforms.

**Comment by directhex** [comment]
Half the tests were disabled by https://github.com/dotnet/runtime/issues/51392 so results aren't meaningful. Argh.

Current list of bugs this issue is designed to handle:

#51392
#51390
#67853 
#51335

File: src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs [hunk 3]
```diff
@@ -12,7 +12,7 @@ internal static partial class SocketProtocolSupportPal
 
         public static bool OSSupportsIPv6 { get; } = IsSupported(AddressFamily.InterNetworkV6) && !IsIPv6Disabled();
         public static bool OSSupportsIPv4 { get; } = IsSupported(AddressFamily.InterNetwork);
-        public static bool OSSupportsUnixDomainSockets { get; } = IsSupported(AddressFamily.Unix);
+        public static bool OSSupportsUnixDomainSockets { get; } = IsSupported(AddressFamily.Unix) && !OperatingSystem.IsTvOS() && (!OperatingSystem.IsIOS() || OperatingSystem.IsMacCatalyst());
```
Comment (akoeplinger) [inline src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs:15]: nit: move the OS checks to the IsSupported method in SocketProtocolSupportPal.Unix.cs

File: src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs [hunk 4]
```diff
@@ -1635,8 +1632,8 @@ protected IEnumerable<(Stream writeable, Stream readable)> GetReadWritePairs(Str
             streams.Stream2.CanRead && streams.Stream2.CanWrite;
 
         [Fact]
-        [ActiveIssue("https://github.com/dotnet/runtime/issues/67853", TestPlatforms.tvOS)]
         [SkipOnPlatform(TestPlatforms.LinuxBionic, "SElinux blocks UNIX sockets")]
+        [SkipOnPlatform(TestPlatforms.iOS | TestPlatforms.tvOS, "iOS/tvOS blocks binding to UNIX sockets")]
```
Comment (akoeplinger) [inline src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:1636]: Should we make this a `ConditionalFact(typeof(Socket), nameof(Socket.OSSupportsUnixDomainSockets))` instead?

We probably should also make Linux Bionic return false for that property.

File: src/libraries/System.Net.Sockets/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs [hunk 5]
```diff
@@ -44,6 +44,11 @@ private UnixDomainSocketEndPoint(string path, string? boundFileName)
                 bufferLength++;
             }
 
+            if (!Socket.OSSupportsUnixDomainSockets)
+            {
+                throw new PlatformNotSupportedException();
+            }
```
Comment (akoeplinger) [inline src/libraries/System.Net.Sockets/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs:50]: why did you move this?

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/UnixDomainSocketTest.cs [hunk 6]
```diff
@@ -125,8 +124,8 @@ public async Task Socket_ConnectAsyncUnixDomainSocketEndPoint_NotServer()
         }
 
         [ConditionalFact(nameof(PlatformSupportsUnixDomainSockets))]
```
Comment (akoeplinger) [inline src/libraries/System.Net.Sockets/tests/FunctionalTests/UnixDomainSocketTest.cs:126]: speaking of my earlier comment, we can replace this with Socket.OSSupportsUnixDomainSockets since it is public now and get rid of the custom PlatformSupportsUnixDomainSockets code.

File: src/libraries/System.Net.Sockets/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs (hunk 5 above)
Comment (akoeplinger) [reply src/libraries/System.Net.Sockets/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs:50]: we should also annotate the type itself as UnsupportedOSPlatform(iOS/tvOS) and SupportedOSPlatform(MacCatalyst) in the ref

doesn't need to be done in this PR since it'll likely cause quite a bit of fallout

**Review by akoeplinger — APPROVED** [review]
looks good, just a few comments

File: src/libraries/System.Net.Sockets/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs (hunk 5 above)
Comment (directhex) [reply src/libraries/System.Net.Sockets/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs:50]: I moved it so it would throw PNSE early instead of ArgumentOutOfRangeException on platforms which return a small value for `s_nativePathLength`, like iOSSimulator and tvOSSimulator

File: src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs (hunk 4 above)
Comment (directhex) [reply src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:1636]: Bionic _does_ support UNIX sockets, but it explicitly doesn't permit them in the `/data/local/tmp` directory we use for our test suite (the only folder, more or less, one can use when just using `adb shell` without the apk infrastructure around it)

File: src/libraries/System.Net.Sockets/tests/FunctionalTests/UnixDomainSocketTest.cs (hunk 6 above)
Comment (directhex) [reply src/libraries/System.Net.Sockets/tests/FunctionalTests/UnixDomainSocketTest.cs:128]: I'm not opposed to this at all. I assumed there was some motivation behind the `PlatformSupportsUnixDomainSockets` bool (which helpfully just returns true for non-Windows)

File: src/libraries/System.Net.Sockets/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs (hunk 5 above)
Comment (directhex) [reply src/libraries/System.Net.Sockets/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs]: Never mind, I guess - Windows tests were explicitly looking for the fail-on-path-before-failing-on-PNSE model. I think it's a bad model, but it's the one already in place.

**Review by akoeplinger — APPROVED** [review]
