### PR TITLE
[APX] Make sure KMOV is not encoded in EVEX when JitStressEvexEncoding is set.

### LINKED ISSUE #113814: Test failure: profiler/elt/slowpatheltenter/slowpatheltenter.cmd
**Failed in:** [runtime-coreclr jitstress-isas-avx512 20250322.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=990017&view=ms.vss-test-web.build-test-results-tab&runId=26421268&resultId=117750&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked jitstress_isas_x86_evex @ Windows.10.Amd64.Open
    - profiler/elt/slowpatheltenter/slowpatheltenter.cmd
    - profiler/elt/slowpatheltleave/slowpatheltleave.cmd
    - profiler/unittest/getappdomainstaticaddress/getappdomainstaticaddress.cmd
    - profiler/unittest/inlining/inlining.cmd
```

**Error message:**
```
 Process terminated.
Encountered infinite recursion while looking up resource 'Exception_EndOfInnerExceptionStack' in System.Private.CoreLib. Verify the installation of .NET is complete and does not need repairing, and that the state of the process has not become corrupted.
   at System.Environment.<FailFast>g____PInvoke|11_0(System.Runtime.CompilerServices.StackCrawlMarkHandle, UInt16*, System.Runtime.CompilerServices.ObjectHandleOnStack, UInt16*)
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.Exception.ToString()
   at System.Runtime.ExceptionServices.InternalCalls.<RhpSfiInit>g____PInvoke|0_0(System.Runtime.StackFrameIterator*, Void*, Byte, Boolean*)
   at System.Runtime.ExceptionServices.InternalCalls.<RhpSfiInit>g____PInvoke|0_0(System.Runtime.StackFrameIterator*, Void*, Byte, Boolean*)
   at System.Runtime.ExceptionServices.InternalCalls.RhpSfiInit(System.Runtime.StackFrameIterator ByRef, Void*, Boolean, Boolean*)
   at System.Runtime.EH.DispatchEx(System.Runtime.StackFrameIterator ByRef, ExInfo ByRef)
   at System.Runtime.EH.RhThrowHwEx(UInt32, ExInfo ByRef)
   at System.SpanHelpers.IndexOfNullByte(Byte*)
   at System.RuntimeType+RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.get_ResourceManager()
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.Exception.ToString()
   at System.Runtime.ExceptionServices.InternalCalls.<RhpSfiInit>g____PInvoke|0_0(System.Runtime.StackFrameIterator*, Void*, Byte, Boolean*)
   at System.Runtime.ExceptionServices.InternalCalls.<RhpSfiInit>g____PInvoke|0_0(System.Runtime.StackFrameIterator*, Void*, Byte, Boolean*)
   at System.Runtime.ExceptionServices.InternalCalls.RhpSfiInit(System.Runtime.StackFrameIterator ByRef, Void*, Boolean, Boolean*)
   at System.Runtime.EH.DispatchEx(System.Runtime.StackFrameIterator ByRef, ExInfo ByRef)
   at System.Runtime.EH.RhThrowHwEx(UInt32, ExInfo ByRef)
   at System.SpanHelpers.IndexOfNullCharacter(Char*)
   at System.String.Ctor(Char*)
   at System.AppContext.Setup(Char**, Char**, Int32)
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above. Profilee returned exit code -2146232797.

   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)

   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)

   at SlowPathELTTests.SlowPathELTEnter.Main(String[] args)

Return code:      1
Raw output file:      C:hwA8A1093CwC2C00A07uploadseltslowpatheltenteroutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwA8A1093Cpcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  slowpatheltenter.dll 
Profiler path: C:hwA8A1093CwC2C00A07eprofilereltslowpatheltenterProfiler.dll
Profilee STDOUT: Profiler.dll!DllGetClassObject
Profilee STDOUT: Profiler.dll!Profiler::Initialize
Profilee STDOUT: Testing enter hooks
Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above. Profilee returned exit code -2146232797.
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was cre
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor4|0_5(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by Ruihan-Yin**
Fix #113814

`KMOV` instructions will be able to be encoded in EVEX on APX enabled machine to address EGPRs, but on Avx512 machine, they can only be encoded in VEX.

we should ensure KMOV has the right prefix under different cases, essentially in the bug, we are stressing original EVEX encoding by `JitStressEvexEncoding`. So `KMOV` should not be impacted and stay VEX-encoded.

### CODE REVIEW

**Comment by Ruihan-Yin** [comment]
All failures look related to some timeout issue, I presume this is not related to my changes. PR is ready for review.

File: src/coreclr/jit/emitxarch.cpp [hunk 1]
```diff
@@ -1757,6 +1788,13 @@ bool emitter::TakesEvexPrefix(const instrDesc* id) const
             return false;
         }
 
+        if (IsKMOVInstruction(ins))
+        {
+            // KMOV should not be encoded in EVEX when stressing EVEX, as they are supposed to encded in EVEX only
+            // when APX is available, only stressing EVEX is not enough making the encoding valid.
+            return false;
```
Comment (Ruihan-Yin) [inline src/coreclr/jit/emitxarch.cpp:1795]: Or we can return `UsePromotedEVEXEncoding()` here. Make sure KMOV can be stressed when APX is available.

**Comment by Ruihan-Yin** [comment]
Hi @BruceForstall, please also review this bug fix, thanks!

**Review by BruceForstall — APPROVED** [review]
