### PR TITLE
StringSegment behavior

### LINKED ISSUE #45021: StringSegment doesn't handle null buffers consistently
`Microsoft.Extensions.Primitives.StringSegment` does not handle null backing buffers consistently. One example:

```cs
Console.WriteLine(default(StringSegment).IndexOfAny(new[] { 'x' })); // prints -1
Console.WriteLine(default(StringSegment).IndexOf('x')); // throws ArgumentOutOfRangeException
Console.WriteLine(default(StringSegment).LastIndexOf('x')); // prints -1
```

(Related: https://github.com/dotnet/runtime/issues/39140)

### LINKED ISSUE #53727: StringSegment IndexOf behavior
### Description
Working on reopening PR for #45021 (first one was closed due to inactivity)
Found a few more strange behaviors

**First**:
There is no check for the right bound in `IndexOf` like in the `IndexOfAny`
`IndexOfAny`:
https://github.com/dotnet/runtime/blob/911640b3a891f92ff66e9c82ce65f71d203f11a2/src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs#L519-L529

`IndexOf`:
https://github.com/dotnet/runtime/blob/911640b3a891f92ff66e9c82ce65f71d203f11a2/src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs#L457-L467

Anyway, exception will be thrown in Span\<T\>.Slice method  (exception message will be a little different), but I don't think this is by design 😄

**Second:**
Check for the right bound above (`IndexOfAny`) is quite weird, it allows to get index from original string
Example:
```C# 
public static void Main(string[] args)
        {
            StringSegment segment = new StringSegment("12345", 0, 1);
            var index = segment.IndexOfAny(new[] { '5' }, 2, 3);
            Console.WriteLine(index); // Prints 4 
        }
```
<del>I believe that correct value here should be -1, am I missing something?</del>
UPD: OutOfRangeException should be thrown
So it seems like `Buffer.Length` have to be replaced with `Length` property

### Regression?
Fixes will be breaking changes, but for the original issue (#45021) it was ok https://github.com/dotnet/runtime/pull/46432#issuecomment-803032974

### PR DESCRIPTION
**Pull request by hrrrrustic**
fix #45021
fix #53727

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs [hunk 1]
```diff
@@ -452,22 +452,25 @@ public StringSegment Subsegment(int offset, int length)
...
         {
-            int offset = Offset + start;
+            int index = -1;
 
-            if (!HasValue || start < 0 || (uint)offset > (uint)Buffer.Length)
+            if (HasValue)
             {
-                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
-            }
+                if (start < 0 || start > Length)
```
Comment (gfoidl) [inline src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs:459]:
```suggestion
                if ((uint)start > (uint)Length)
```
to avoid one comparison. If negative the cast to `uint` will put into the range > int.MaxValue, so it's safe.

File: src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs [hunk 2]
```diff
@@ -452,22 +452,25 @@ public StringSegment Subsegment(int offset, int length)
...
+                {
+                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
+                }
 
-            if (count < 0)
-            {
-                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.count);
-            }
+                if (count < 0 || start + count > Length)
```
Comment (gfoidl) [inline src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs:464]: `start + count` could overflow, so become a negative sum. To be on the safe side:
```suggestion
                if (count < 0 || count > Length - start)
```
and to save one comparison:
```suggestion
                if ((uint)count > (uint)(Length - start))
```

Similar below.

File: src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs [hunk 3]
```diff
@@ -516,12 +519,12 @@ public int IndexOfAny(char[] anyOf, int startIndex, int count)
 
             if (HasValue)
             {
-                if (startIndex < 0 || Offset + startIndex > Buffer.Length)
+                if (startIndex < 0 || startIndex > Length)
```
Comment (hrrrrustic) [inline src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs:522]:
```suggestion
                if ((uint)startIndex > (uint)Length)
```

File: src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs [hunk 4]
```diff
@@ -516,12 +519,12 @@ public int IndexOfAny(char[] anyOf, int startIndex, int count)
...
                 {
                     ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
                 }
 
-                if (count < 0 || Offset + startIndex + count > Buffer.Length)
+                if (count < 0 || startIndex + count > Length)
```
Comment (hrrrrustic) [inline src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs:527]:
```suggestion
                if ((uint)count > (uint)(Length - startIndex))
```

**Comment by GrabYourPitchforks** [comment]
@maryamariyan You marked https://github.com/dotnet/runtime/issues/45021 as up-for-grabs but never specified what you believe the correct behavior should be: consistently return -1 or consistently throw an exception.

/cc @halter73

**Comment by hrrrrustic** [comment]
I guess `-1` is the correct way as it described in all of this methods docs 😄 
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs#L447
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs#L504
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Primitives/src/StringSegment.cs#L571

**Review by eerhardt — APPROVED** [review]
I _think_ this looks good. @GrabYourPitchforks - any thoughts/concerns?

**Review by maryamariyan — APPROVED** [review]

**Review by GrabYourPitchforks — APPROVED** [review]

**Comment by eerhardt** [comment]
Linq.Expression failures are #55536. Merging.

**Comment by eerhardt** [comment]
Thanks @hrrrrustic for the contribution here!
