### PR TITLE
[loader] Add append option to loader hook installation functions

### LINKED ISSUE #34273: Fix assembly loading order on mono
## Steps to reproduce
1. Build a mono runtime (`./mono.sh`, `make patch-mono-dotnet`)
2. Clone https://github.com/dotnet/performance
3. Build `src/benchmarks/micro/MicroBenchmarks.csproj` (`./dotnet-mono build -c Release -f netcoreapp5.0 MicroBenchmarks.csproj`)
4. Go to binaries folder in `artifacts/bin/MicroBenchmarks/Release/netcoreapp5.0` and run `MicroBenchmarks.dll`
5. Observer a libgdiplus error which seems to be caused by loading of `System.Drawing.Common.dll` from the current folder, rather than from the `runtimes` folder

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Fixes https://github.com/dotnet/runtime/issues/34273

While this specific issue only affects the preload hook, I've added the append option to all the installation functions since this seems like a generally useful capability, both for internal use and embedders.

@BrzVlad tested locally and confirmed this patch solves the problem.

### CODE REVIEW

File: src/mono/mono/metadata/appdomain.c [hunk 1]
```diff
@@ -314,16 +314,17 @@ mono_runtime_init_checked (MonoDomain *domain, MonoThreadStartCB start_cb, MonoT
 	mono_marshal_init ();
 	mono_gc_init_icalls ();
 
-	mono_install_assembly_preload_hook_v2 (mono_domain_assembly_preload, GUINT_TO_POINTER (FALSE), FALSE);
-	mono_install_assembly_search_hook_v2 (mono_domain_assembly_search, GUINT_TO_POINTER (FALSE), FALSE, FALSE);
-	mono_install_assembly_search_hook_v2 (mono_domain_assembly_postload_search, GUINT_TO_POINTER (FALSE), FALSE, TRUE);
-	mono_install_assembly_load_hook_v2 (mono_domain_fire_assembly_load, NULL);
+	// We have to append here because otherwise this will run before the netcore hook (which is installed first), see https://github.com/dotnet/runtime/issues/34273
+	mono_install_assembly_preload_hook_v2 (mono_domain_assembly_preload, GUINT_TO_POINTER (FALSE), FALSE, TRUE);
```
Comment (vargaz) [inline src/mono/mono/metadata/appdomain.c]: Wouldn't it be possible to merge some of the hooks instead ?

Comment (CoffeeFlux) [reply src/mono/mono/metadata/appdomain.c]: We'd have to split them, not merge them. The problem is that we have two hooks installed but care about the order they're run in. I don't think we have much to gain from refactoring a bunch of this, but if you feel differently I can explore it a bit more.

Comment (CoffeeFlux) [reply src/mono/mono/metadata/appdomain.c]: Keep in mind that even if we change the internal structure of the hooks, we have to keep the v1 embedding APIs still functional (and working alongside them) and port the legacy and netcore loaders to use the new setup. It's not trivial.

Comment (CoffeeFlux) [reply src/mono/mono/metadata/appdomain.c]: Added a comment to the issue to clarify the actual bug, sorry for not doing that earlier.

**Review by lewurm — APPROVED** [review]
