### PR TITLE
P/Invokes should use C types not C++.

### LINKED ISSUE #94931: DisabledRuntimeMarshalling.PInvokeAssemblyMarshallingEnabled.DelegatesFromExternalAssembly.StructWithDefaultNonBlittableFields() failing
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=473177
Build error leg or test failing: Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd
Pull request: https://github.com/dotnet/runtime/pull/94878

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "DisabledRuntimeMarshalling.PInvokeAssemblyMarshallingEnabled.DelegatesFromExternalAssembly.StructWithDefaultNonBlittableFields()",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=473177
**Error message validated:** `DisabledRuntimeMarshalling.PInvokeAssemblyMarshallingEnabled.DelegatesFromExternalAssembly.StructWithDefaultNonBlittableFields()`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/17/2023 6:22:15 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[475116](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475116)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475116&view=ms.vss-test-web.build-test-results-tab&runId=10855880&resultId=117052)||
|[475118](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475118)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475118&view=ms.vss-test-web.build-test-results-tab&runId=10855754&resultId=113386)|dotnet/runtime#93879|
|[475090](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475090)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475090&view=ms.vss-test-web.build-test-results-tab&runId=10854418&resultId=119585)||
|[475098](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475098)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475098&view=ms.vss-test-web.build-test-results-tab&runId=10854388&resultId=110698)|dotnet/runtime#94942|
|[475089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475089)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475089&view=ms.vss-test-web.build-test-results-tab&runId=10854374&resultId=118582)||
|[475070](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475070)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475070&view=ms.vss-test-web.build-test-results-tab&runId=10853572&resultId=113250)|dotnet/runtime#93879|
|[475055](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475055)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475055&view=ms.vss-test-web.build-test-results-tab&runId=10853108&resultId=113249)||
|[475035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475035)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475035&view=ms.vss-test-web.build-test-results-tab&runId=10852844&resultId=113282)|dotnet/runtime#94956|
|[475018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475018)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475018&view=ms.vss-test-web.build-test-results-tab&runId=10852326&resultId=119432)|dotnet/runtime#94978|
|[475013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475013)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475013&view=ms.vss-test-web.build-test-results-tab&runId=10852308&resultId=118599)||
|[475014](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475014)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475014&view=ms.vss-test-web.build-test-results-tab&runId=10852206&resultId=119728)||
|[475015](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475015)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=475015&view=ms.vss-test-web.build-test-results-tab&runId=10852044&resultId=113249)|dotnet/runtime#94978|
|[2319053](https://dev.azure.com/dnceng/internal/_build/results?buildId=2319053)|dotnet-runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng//internal/_build/results?buildId=2319053&view=ms.vss-test-web.build-test-results-tab&runId=52564667&resultId=119431)||
|[474889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474889)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474889&view=ms.vss-test-web.build-test-results-tab&runId=10851092&resultId=126012)||
|[474901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474901)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474901&view=ms.vss-test-web.build-test-results-tab&runId=10850292&resultId=113249)|dotnet/runtime#94647|
|[474841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474841)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474841&view=ms.vss-test-web.build-test-results-tab&runId=10847464&resultId=119432)||
|[474836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474836)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474836&view=ms.vss-test-web.build-test-results-tab&runId=10847068&resultId=117795)||
|[474825](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474825)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474825&view=ms.vss-test-web.build-test-results-tab&runId=10846726&resultId=116926)||
|[474827](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474827)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474827&view=ms.vss-test-web.build-test-results-tab&runId=10846668&resultId=113282)||
|[474808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474808)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474808&view=ms.vss-test-web.build-test-results-tab&runId=10846144&resultId=166584)||
|[474807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474807)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474807&view=ms.vss-test-web.build-test-results-tab&runId=10845810&resultId=113281)||
|[474794](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474794)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474794&view=ms.vss-test-web.build-test-results-tab&runId=10845642&resultId=119575)||
|[474757](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474757)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474757&view=ms.vss-test-web.build-test-results-tab&runId=10844680&resultId=117795)||
|[474758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474758)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474758&view=ms.vss-test-web.build-test-results-tab&runId=10844620&resultId=111698)|dotnet/runtime#93907|
|[474740](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474740)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474740&view=ms.vss-test-web.build-test-results-tab&runId=10843978&resultId=119585)||
|[474739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474739)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474739&view=ms.vss-test-web.build-test-results-tab&runId=10843938&resultId=119585)||
|[474727](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474727)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474727&view=ms.vss-test-web.build-test-results-tab&runId=10843702&resultId=142539)||
|[474720](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474720)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474720&view=ms.vss-test-web.build-test-results-tab&runId=10842994&resultId=113168)||
|[474714](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474714)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474714&view=ms.vss-test-web.build-test-results-tab&runId=10842872&resultId=119728)||
|[474696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474696)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474696&view=ms.vss-test-web.build-test-results-tab&runId=10842664&resultId=115987)||
|[474709](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474709)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474709&view=ms.vss-test-web.build-test-results-tab&runId=10842648&resultId=113250)|dotnet/runtime#94958|
|[474706](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474706)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474706&view=ms.vss-test-web.build-test-results-tab&runId=10842636&resultId=113282)|dotnet/runtime#94956|
|[474698](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474698)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474698&view=ms.vss-test-web.build-test-results-tab&runId=10842572&resultId=113386)|dotnet/runtime#94955|
|[474682](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474682)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474682&view=ms.vss-test-web.build-test-results-tab&runId=10842378&resultId=118142)||
|[474679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474679)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474679&view=ms.vss-test-web.build-test-results-tab&runId=10841636&resultId=119575)||
|[474552](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474552)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474552&view=ms.vss-test-web.build-test-results-tab&runId=10840084&resultId=115446)||
|[474567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474567)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474567&view=ms.vss-test-web.build-test-results-tab&runId=10839216&resultId=113305)|dotnet/runtime#94950|
|[474564](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474564)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474564&view=ms.vss-test-web.build-test-results-tab&runId=10839208&resultId=113250)|dotnet/runtime#94647|
|[474505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474505)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474505&view=ms.vss-test-web.build-test-results-tab&runId=10835984&resultId=119585)||
|[474501](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474501)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474501&view=ms.vss-test-web.build-test-results-tab&runId=10835498&resultId=116616)||
|[474489](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474489)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474489&view=ms.vss-test-web.build-test-results-tab&runId=10835208&resultId=116966)||
|[474490](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474490)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474490&view=ms.vss-test-web.build-test-results-tab&runId=10835128&resultId=113276)||
|[474471](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474471)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474471&view=ms.vss-test-web.build-test-results-tab&runId=10834774&resultId=119800)||
|[474420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474420)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474420&view=ms.vss-test-web.build-test-results-tab&runId=10834688&resultId=117795)|dotnet/runtime#94947|
|[474470](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474470)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474470&view=ms.vss-test-web.build-test-results-tab&runId=10834680&resultId=116462)||
|[474469](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474469)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474469&view=ms.vss-test-web.build-test-results-tab&runId=10834524&resultId=113417)||
|[474468](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474468)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474468&view=ms.vss-test-web.build-test-results-tab&runId=10834482&resultId=113417)||
|[474421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474421)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474421&view=ms.vss-test-web.build-test-results-tab&runId=10834432&resultId=119431)|dotnet/runtime#94947|
|[474463](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474463)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474463&view=ms.vss-test-web.build-test-results-tab&runId=10834408&resultId=113418)|dotnet/runtime#92483|
|[474423](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474423)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474423&view=ms.vss-test-web.build-test-results-tab&runId=10834392&resultId=113418)|dotnet/runtime#94947|
|[474452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474452)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474452&view=ms.vss-test-web.build-test-results-tab&runId=10834314&resultId=119303)||
|[474451](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474451)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474451&view=ms.vss-test-web.build-test-results-tab&runId=10834256&resultId=117795)||
|[474442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474442)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474442&view=ms.vss-test-web.build-test-results-tab&runId=10834016&resultId=119800)||
|[474367](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474367)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474367&view=ms.vss-test-web.build-test-results-tab&runId=10832516&resultId=113403)||
|[474300](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474300)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474300&view=ms.vss-test-web.build-test-results-tab&runId=10831200&resultId=119800)|dotnet/runtime#94239|
|[474315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474315)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474315&view=ms.vss-test-web.build-test-results-tab&runId=10830904&resultId=113418)|dotnet/runtime#94673|
|[474312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474312)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474312&view=ms.vss-test-web.build-test-results-tab&runId=10830898&resultId=113305)|dotnet/runtime#94732|
|[474288](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474288)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474288&view=ms.vss-test-web.build-test-results-tab&runId=10830454&resultId=113418)|dotnet/runtime#94239|
|[474197](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474197)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474197&view=ms.vss-test-web.build-test-results-tab&runId=10829546&resultId=113250)|dotnet/runtime#94938|
|[474252](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474252)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474252&view=ms.vss-test-web.build-test-results-tab&runId=10829534&resultId=113249)|dotnet/runtime#94896|
|[474082](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474082)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474082&view=ms.vss-test-web.build-test-results-tab&runId=10828574&resultId=117795)|dotnet/runtime#94239|
|[474042](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474042)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474042&view=ms.vss-test-web.build-test-results-tab&runId=10828176&resultId=110699)|dotnet/runtime#94239|
|[474142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474142)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474142&view=ms.vss-test-web.build-test-results-tab&runId=10827422&resultId=113417)||
|[474129](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474129)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474129&view=ms.vss-test-web.build-test-results-tab&runId=10826976&resultId=113282)|dotnet/runtime#94935|
|[474112](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474112)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474112&view=ms.vss-test-web.build-test-results-tab&runId=10826632&resultId=113418)|dotnet/runtime#94689|
|[474083](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474083)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474083&view=ms.vss-test-web.build-test-results-tab&runId=10826160&resultId=119432)|dotnet/runtime#94239|
|[474038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474038)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474038&view=ms.vss-test-web.build-test-results-tab&runId=10824842&resultId=118585)||
|[474054](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474054)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474054&view=ms.vss-test-web.build-test-results-tab&runId=10824558&resultId=113418)|dotnet/runtime#94732|
|[474023](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474023)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=474023&view=ms.vss-test-web.build-test-results-tab&runId=10823002&resultId=112807)|dotnet/runtime#94735|
|[473997](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473997)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473997&view=ms.vss-test-web.build-test-results-tab&runId=10822184&resultId=112168)|dotnet/runtime#94764|
|[473177](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473177)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473177&view=ms.vss-test-web.build-test-results-tab&runId=10820552&resultId=113249)|dotnet/runtime#94878|
|[473636](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473636)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473636&view=ms.vss-test-web.build-test-results-tab&runId=10819430&resultId=113305)|dotnet/runtime#94868|
|[473862](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473862)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473862&view=ms.vss-test-web.build-test-results-tab&runId=10818702&resultId=113418)|dotnet/runtime#94292|
|[473831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473831)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473831&view=ms.vss-test-web.build-test-results-tab&runId=10818070&resultId=113282)|dotnet/runtime#94914|
|[473801](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473801)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473801&view=ms.vss-test-web.build-test-results-tab&runId=10817352&resultId=113418)|dotnet/runtime#94647|
|[473753](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473753)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473753&view=ms.vss-test-web.build-test-results-tab&runId=10815384&resultId=113249)|dotnet/runtime#92705|
|[473719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473719)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473719&view=ms.vss-test-web.build-test-results-tab&runId=10814554&resultId=113208)|dotnet/runtime#94764|
|[473698](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473698)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473698&view=ms.vss-test-web.build-test-results-tab&runId=10813386&resultId=113385)|dotnet/runtime#94666|
|[473687](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473687)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473687&view=ms.vss-test-web.build-test-results-tab&runId=10812986&resultId=116069)||
|[473585](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473585)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473585&view=ms.vss-test-web.build-test-results-tab&runId=10810074&resultId=117359)||
|[473529](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473529)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473529&view=ms.vss-test-web.build-test-results-tab&runId=10808230&resultId=119432)||
|[473549](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473549)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473549&view=ms.vss-test-web.build-test-results-tab&runId=10808138&resultId=113417)|dotnet/runtime#94896|
|[473545](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473545)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473545&view=ms.vss-test-web.build-test-results-tab&runId=10808028&resultId=113250)|dotnet/runtime#93493|
|[473408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473408)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473408&view=ms.vss-test-web.build-test-results-tab&runId=10802536&resultId=113250)|dotnet/runtime#94889|
|[473351](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473351)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473351&view=ms.vss-test-web.build-test-results-tab&runId=10802032&resultId=117795)||
|[473380](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473380)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473380&view=ms.vss-test-web.build-test-results-tab&runId=10802252&resultId=113305)|dotnet/runtime#94835|
|[473305](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473305)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473305&view=ms.vss-test-web.build-test-results-tab&runId=10800506&resultId=113169)|dotnet/runtime#94887|
|[473284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473284)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473284&view=ms.vss-test-web.build-test-results-tab&runId=10799746&resultId=113418)|dotnet/runtime#94886|
|[473273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473273)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473273&view=ms.vss-test-web.build-test-results-tab&runId=10798998&resultId=113250)|dotnet/runtime#94825|
|[473249](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473249)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473249&view=ms.vss-test-web.build-test-results-tab&runId=10798730&resultId=113418)|dotnet/runtime#94885|
|[473190](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473190)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473190&view=ms.vss-test-web.build-test-results-tab&runId=10795848&resultId=113418)|dotnet/runtime#93493|
|[473167](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473167)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473167&view=ms.vss-test-web.build-test-results-tab&runId=10795780&resultId=113418)|dotnet/runtime#94732|
|[472428](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472428)|dotnet/runtime|[Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=472428&view=ms.vss-test-web.build-test-results-tab&runId=10784682&resultId=111286)|dotnet/runtime#94630|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|22|93|93|

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
A recent C++ toolchain update uncovered an invalid P/Invoke signature using C++ types as opposed to C types. This caused the test to fail due to invalid assumptions. The test was updated to be valid.

Fixes #94931

### CODE REVIEW

File: src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp [hunk 1]
```diff
@@ -24,24 +19,24 @@ struct StructWithWCharAndShort
     WCHAR c;
 };
 
-extern "C" DLL_EXPORT bool STDMETHODCALLTYPE CheckStructWithShortAndBool(StructWithShortAndBool str, short s, bool b)
+extern "C" DLL_EXPORT BOOL STDMETHODCALLTYPE CheckStructWithShortAndBool(StructWithShortAndBool str, short s, BYTE b)
```
Comment (jkotas) [inline src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp:22]: I would expect the return type to be BYTE here.

Do we have a bug in the JIT implementation of the unmanaged calling conventions for small integer return types?

**Comment by jkotas** [comment]
We do not seem to have the difference between managed and unmanaged x86/x64 calling conventions for small return types noted in https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/clr-abi.md . It would be nice to fix that.

For unmanaged calling conventions, the state of unused bits in the value returned in RAX or XMM0 is undefined. (https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#return-values)

For managed calling conventions, the primitive values smaller than 32-bits must be zero-extended (or sign-extended?) to 32-bits. @dotnet/jit-contrib What is the exact rule that the JIT implements?

**Comment by AndyAyersMS** [comment]
For managed methods, the callee widens small return values. For native methods, the caller widens small return values.

I think we always zero extend.

https://github.com/dotnet/runtime/blob/8a1b985a4f31850ecb5e6537f21666de52e02cee/src/coreclr/jit/importercalls.cpp#L1428-L1445

File: src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp:22]: It seems like the JIT is seeing an `int` return type in the signature when it is compiling `IL_STUB_PInvoke` for the delegate created for `DisabledRuntimeMarshalling.PInvokeAssemblyMarshallingEnabled.DelegatesFromExternalAssembly.StructWithDefaultNonBlittableFields`, so no normalization is done:
```scala
    [ 4]  50 (0x032) calli 11FFFFFF
In Compiler::impImportCall: opcode is calli, kind=0, callRetType is int, structSize is 0

               [000029] DACXG------                         ▌  STORE_LCL_VAR int    V15 tmp3         
               [000027] --CXG------                         └──▌  CALL ind unman int   
               [000022] ----------- arg0                       ├──▌  LCL_VAR   struct<DisabledRuntimeMarshallingNative+StructWithShortAndBool, 12> V13 tmp1         
               [000018] ----------- arg1                       ├──▌  LCL_VAR   int    V07 loc3         
               [000019] ----------- arg2                       ├──▌  LCL_VAR   int    V08 loc4         
               [000026] ----------- calli tgt                  └──▌  LCL_VAR   long   V14 tmp2         
```

Comment (jkotas) [reply src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp:22]: > PInvokeAssemblyMarshallingEnabled

It is expected that the return type will be `int` (matching unmanaged `BOOL`) when the marshalling is enabled.

Maybe the problem is that `CheckStructWithShortAndBool` unmanaged method is used for both the marshaling disabled test (where bool needs to be 1 byte) and marshaling enabled test (where bool needs to be 4 bytes by default)?

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp:22]: > Maybe the problem is that CheckStructWithShortAndBool unmanaged method is used for both the marshaling disabled test (where bool needs to be 1 byte) and marshaling enabled test (where bool needs to be 4 bytes by default)?

Yes, that is the general root of the problem and I can update that as such. I was trying to avoid rewriting these tests. They are written in an odd way and seem to be more complex than needed.

**Comment by AaronRobinsonMSFT** [comment]
@AndyAyersMS Is there a follow up issue to file here?

**Comment by AndyAyersMS** [comment]
You mean for codegen? I don't see one, unless we're not actually doing what is outlined above.

File: src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp (hunk 1 above)
Comment (jkotas) [reply src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp:22]: I think we should fix the tests to avoid mismatched unmanaged/managed signatures. The mismatched unmanaged/managed signatures are always a bug farm.

**Comment by AaronRobinsonMSFT** [comment]
This is step one of the fix. The current update works and passes on macOS. Pushing to CI to make sure Windows and Linux remain in the same state.

File: src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp (hunk 1 above)
Comment (huoyaoyuan) [reply src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp]: Can/should stdint types be used here?

Comment (AaronRobinsonMSFT) [reply src/tests/Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshallingNative.cpp]: `BYTE` is already used in this test and this isn't where I want to start converting these types to stdint.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas Please take another look at this. I'd like to get the CI unblocked. Feel free to merge if you are okay with the changes.

**Review by jkotas — APPROVED** [review]
Thank you
