### PR TITLE
Generate custom attributes from metadata instead of type system

### LINKED ISSUE #100688: Attributes taking object as a parameter have unexpected behavior in AOT
### Description

Given an attribute that take an `object` as a parameter, when using an Enum it gets converted to an `int` before being passed to the constructor during AOT

### Reproduction Steps

```csharp
using System.ComponentModel;
using System.Reflection;

var defaultValue = typeof(MyTeam)
    .GetProperty("Quarterback")!
    .GetCustomAttribute<DefaultValueAttribute>()!.Value!;


var customValue = typeof(MyTeam)
    .GetProperty("Backup")!
    .GetCustomAttribute<MyCustomAttribute>()!.Value!;

Console.WriteLine($"{defaultValue.GetType()} {defaultValue}");
Console.WriteLine($"{customValue.GetType()} {customValue}");

internal enum Quarterbacks { Teddy, Lamar, Malik, Stefan }

internal class MyTeam
{
    [DefaultValue(Quarterbacks.Lamar)]
    public Quarterbacks Quarterback { get; set; }
    
    [MyCustom(Quarterbacks.Teddy)]
    public Quarterbacks Backup { get; set; }
}

internal class MyCustomAttribute(object value) : Attribute
{
    public object Value => value;
}
```

### Expected behavior

```
Quarterbacks Lamar
Quarterbacks Teddy
```

### Actual behavior

```
System.Int32 1
System.Int32 0
```

### Regression?

Not sure

### Known Workarounds

For custom attributes, using a generic attribute will now work. But that doesn't help when wanting to use an existing one like `DefaultAttribute`

### Configuration

* .net 8
* Windows 11
* x64

Not sure

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #100688

Fixes a bit more than just what was reported (see the test). We were losing type information in `attribute.DecodeValue` and could no longer distinguish between `new object[] { SomeEnum.Val }` and `new SomeEnum[] { SomeEnum.Val }`.

The fix required a complete rewrite of attribute emission using the more low level API.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
@dotnet/ilc-contrib could someone have a look? This is switching custom attribute metadata generation from `attribute.DecodeValue` convenience decoder provided by S.R.Metadata to decoding the CA blob manually. The convenience decoder loses fidelity and we're not able to distinguish between `object[] { ... }` and `SomeEnum[] { ... }` being assigned to a location typed as `System.Object`.

The changes to `*Gen.cs` files are autogenerated because I touched `SchemaDef.cs` (the native metadata schema).

**Review by agocke — APPROVED** [review]
LGTM, minor questions

File: src/coreclr/tools/Common/Internal/Metadata/NativeFormat/Generator/SchemaDef.cs [hunk 1]
```diff
@@ -315,6 +315,13 @@ internal sealed class SchemaDef
                     members: new MemberDef[] {
                         new MemberDef(name: "Value", typeName: "string")
                     }
+                ),
+                new RecordDef(
+                    name: "ConstantBoxedEnumValue",
```
Comment (jkotas) [inline src/coreclr/tools/Common/Internal/Metadata/NativeFormat/Generator/SchemaDef.cs:320]:
```suggestion
                    name: "ConstantEnumValue",
```
The value is not stored as boxed object instance in the metadata format. "Boxed" does not make sense to me here.

(I understand that it is a pre-existing problem.)

File: src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs [hunk 2]
```diff
@@ -20,195 +19,245 @@ private List<CustomAttribute> HandleCustomAttributes(Cts.Ecma.EcmaModule module,
...
+                Ecma.SerializationTypeCode.Int16 => new ConstantInt16Value { Value = valueReader.ReadInt16() },
+                Ecma.SerializationTypeCode.UInt16 => new ConstantUInt16Value { Value = valueReader.ReadUInt16() },
+                Ecma.SerializationTypeCode.Int32 => new ConstantInt32Value { Value = valueReader.ReadInt32() },
+                Ecma.SerializationTypeCode.UInt32 => new ConstantUInt32Value { Value = valueReader.ReadUInt32() },
+                Ecma.SerializationTypeCode.Int64 => new ConstantInt64Value { Value = valueReader.ReadInt64() },
+                Ecma.SerializationTypeCode.UInt64 => new ConstantUInt64Value { Value = valueReader.ReadUInt64() },
+                Ecma.SerializationTypeCode.Single => new ConstantSingleValue { Value = valueReader.ReadSingle() },
+                Ecma.SerializationTypeCode.Double => new ConstantDoubleValue { Value = valueReader.ReadDouble() },
+                Ecma.SerializationTypeCode.SZArray => HandleCustomAttributeConstantArray(module, valueReader.ReadSerializationTypeCode(), ref valueReader),
+                _ => throw new System.Exception()
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs:168]: `Cts.ThrowHelper.ThrowBadImageFormatException` or `throw new UnreachableException()` ?

File: src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs [hunk 3]
```diff
@@ -20,195 +19,245 @@ private List<CustomAttribute> HandleCustomAttributes(Cts.Ecma.EcmaModule module,
...
+                Ecma.SerializationTypeCode.UInt16 => new ConstantUInt16Array { Value = GetCustomAttributeConstantArrayElements<ushort>(ref valueReader, count) },
+                Ecma.SerializationTypeCode.Int32 => new ConstantInt32Array { Value = GetCustomAttributeConstantArrayElements<int>(ref valueReader, count) },
+                Ecma.SerializationTypeCode.UInt32 => new ConstantUInt32Array { Value = GetCustomAttributeConstantArrayElements<uint>(ref valueReader, count) },
+                Ecma.SerializationTypeCode.Int64 => new ConstantInt64Array { Value = GetCustomAttributeConstantArrayElements<long>(ref valueReader, count) },
+                Ecma.SerializationTypeCode.UInt64 => new ConstantUInt64Array { Value = GetCustomAttributeConstantArrayElements<ulong>(ref valueReader, count) },
+                Ecma.SerializationTypeCode.Single => new ConstantSingleArray { Value = GetCustomAttributeConstantArrayElements<float>(ref valueReader, count) },
+                Ecma.SerializationTypeCode.Double => new ConstantDoubleArray { Value = GetCustomAttributeConstantArrayElements<double>(ref valueReader, count) },
+                _ => throw new System.Exception()
```
Comment (jkotas) [inline src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs:228]: Dtto

File: src/libraries/System.Runtime/tests/System.Reflection.Tests/CustomAttributeTests.cs [hunk 4]
```diff
@@ -237,5 +237,39 @@ public void CustomAttributeProvider ()
             Assert.Equal(typeof(MyParameterAttribute), customAttributesData[0].AttributeType);
             Assert.Equal(typeof(MyPropertyAttribute), customAttributesData[1].AttributeType);
         }
+
+        internal enum EnumForArrays { One }
```
Comment (jkotas) [inline src/libraries/System.Runtime/tests/System.Reflection.Tests/CustomAttributeTests.cs:241]:
```suggestion
        internal enum EnumForArrays { Zero, One, Two }
```

File: src/libraries/System.Runtime/tests/System.Reflection.Tests/CustomAttributeTests.cs [hunk 5]
```diff
@@ -237,5 +237,39 @@ public void CustomAttributeProvider ()
...
+            public object B3 { get; set; }
+        }
+
+        [Fact]
+        public void BoxedEnumAttributes()
+        {
+            CustomAttributeWithObjectsAttribute att = typeof(ClassWithObjectEnums)
+                .GetCustomAttribute<CustomAttributeWithObjectsAttribute>()!;
+
+            Assert.Equal(typeof(EnumForArrays), att.A1.GetType());
```
Comment (jkotas) [inline src/libraries/System.Runtime/tests/System.Reflection.Tests/CustomAttributeTests.cs:264]: Validate the values as well?

File: src/libraries/System.Runtime/tests/System.Reflection.Tests/CustomAttributeTests.cs [hunk 6]
```diff
@@ -237,5 +237,39 @@ public void CustomAttributeProvider ()
             Assert.Equal(typeof(MyParameterAttribute), customAttributesData[0].AttributeType);
             Assert.Equal(typeof(MyPropertyAttribute), customAttributesData[1].AttributeType);
         }
+
+        internal enum EnumForArrays { One }
+
+        [CustomAttributeWithObjects(EnumForArrays.One, new object[] { EnumForArrays.One }, new EnumForArrays[] { EnumForArrays.One },
+                B1 = EnumForArrays.One, B2 = new object[] { EnumForArrays.One }, B3 = new EnumForArrays[] { EnumForArrays.One })]
```
Comment (jkotas) [inline src/libraries/System.Runtime/tests/System.Reflection.Tests/CustomAttributeTests.cs:244]:
```suggestion
        [CustomAttributeWithObjects(EnumForArrays.One, new object[] { EnumForArrays.One }, new EnumForArrays[] { EnumForArrays.Two },
                B1 = EnumForArrays.One, B2 = new object[] { EnumForArrays.Two }, B3 = new EnumForArrays[] { EnumForArrays.One })]
```

**Review by jkotas — APPROVED** [review]

File: src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs (hunk 2 above)
Comment (MichalStrehovsky) [reply src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs:168]: `Cts.ThrowHelper.ThrowBadImageFormatException` is not a throw for C#, so it won't work.

Any opinion about simply disabling warning CS8509 ILCompiler-project-wide?

We keep having to work around it by adding artificial throws, or worse, by adding `_ =>` for something that could be one concrete value (`SomeFoo =>`), but the right-hand side happens to throw for all the other possibilities, so it's as good as an extra `_ => throw new Blah()` line.

File: src/coreclr/tools/Common/Internal/Metadata/NativeFormat/Generator/SchemaDef.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/Internal/Metadata/NativeFormat/Generator/SchemaDef.cs:320]: We have existing ConstantXXXXValue for the primitives. I'll drop the Boxed part per Jan's comment.

File: src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs (hunk 2 above)
Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs]: > adding _ => for something that could be one concrete value (SomeFoo =>)

The compiler is going to add throw for cases that are not covered by the switch. The difference here is whether the code is explicitly handling it with a throw or whether you let the compiler to generate the throw implicitly. Many of the compiler warnings and our own coding conventions rules force you to write more verbose and explicit code, so I see the CS8509 warning as just another one of those.

I think we should throw BIF for invalid input files when we have a choice. If these default switch cases are reachable for invalid input (it is not obvious to me whether it is the case), we may want to add `Cts.ThrowHelper.CreateBadImageFormatException` and change them to `throw Cts.ThrowHelper.CreateBadImageFormatException()`.

Comment (MichalStrehovsky) [reply src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs]: The thing is that I would be fine with the `SwitchExpressionException` the compiler throws. Anything that kills the compilation is fine by me.

I agree that our coding standards err on the more verbose side, so `throw new UnrechableException` sounds like the best fix.

Throwing a Cts.BadImageException wouldn't make a difference here. This spot is non-recoverable; we're in the middle of generating metadata and can't change our mind about it. We already inspected the attribute for dependencies during dependency analysis so at this point we know it doesn't refer to something that doesn't exist (we'd skip it if it does). If it has some other structural issue we didn't detect during dependency analysis, I'm fine with a compiler crash. We try to be resilient for invalid inputs that could be the result of bad assembly version management, but we don't try to be resilient against source-to-IL compiler bugs. Too much resilience makes it difficult to surface _our own_ bugs because this would also paper over those.

Comment (jkotas) [reply src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs]: > We try to be resilient for invalid inputs that could be the result of bad assembly version management,

Parsing of custom attribute blobs can hit BadImageFormat exception due to user error. If the custom attribute references enum from a different assembly and the enum underlying type changes due to user error, parsing of the custom attribute blob will get lost and it will likely end up hitting one of these unreachable cases.

Comment (MichalStrehovsky) [reply src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.CustomAttribute.cs]: That's a good point but it still needs to go to the other spot that parses it first (at the time we analyze dependencies). #101164 has the fix.
