### PR TITLE
Avoid unnecessary allocations of jump stubs

### LINKED ISSUE #116748: opt/cse/HugeArray1/HugeArray1.cmd Timed Out
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1069577
Build error leg or test failing: JIT/jit64/opt/cse/HugeArray1/HugeArray1.cmd
Pull request: https://github.com/dotnet/runtime/pull/116724

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "opt/cse/HugeArray1/HugeArray1.cmd Timed Out",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

https://github.com/dotnet/runtime/issues/92722 related?

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #116748

### CODE REVIEW

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -11725,16 +11725,24 @@ void CEEJitInfo::recordRelocation(void * location,
...
-                    //
-                    delta = rel32UsingJumpStub(fixupLocation, (PCODE)target, m_pMethodBeingCompiled, NULL, false /* throwOnOutOfMemoryWithinRange */);
-                    if (delta == 0)
+                    if (m_fJumpStubOverflow)
                     {
-                        // This forces the JIT to retry the method, which allows us to reserve more space for jump stubs and have a higher chance that
-                        // we will find space for them.
-                        m_fJumpStubOverflow = TRUE;
+                        // Do not attempt to allocate more jump stubs. We are going to throw away the code and retry anyway.
+                        delta = 0;
```
Comment (jakobbotsch) [inline src/coreclr/vm/jitinterface.cpp:11731]: Is my understanding of what happens in the test correct?

1. We have a first JIT attempt that sets `m_fAllowRel32 = false`
2. The second JIT attempt fails to allocate a jump stub and sets `m_fJumpStubOverflow = false`
3. The third try allocates a new code heap without any address range constraints and puts everything in there

Comment (jakobbotsch) [reply src/coreclr/vm/jitinterface.cpp:11731]: Or is 1 and 2 happening during the same attempt? And the slowness of the compilation was because of needing to find 284k jump stubs, which all go into the `ReserveWithinRange` path that can be quite slow?

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/vm/jitinterface.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/vm/jitinterface.cpp:11731]: It is 3 step process in the worst-case scenario on x64 like what's exercised by this test. It is 2 step process on arm64 (there is no allowRel32 on arm64.)

It may be possible to make it 2 step process in the worst case on x64 as well if the JIT passed more reloc details to the EE. I do not think we care enough about the extremely large methods like this one to make it better. 

> The second JIT attempt fails to allocate a jump stub and sets m_fJumpStubOverflow = false

Right. 

> The third try allocates a new code heap without any address range constraints and puts everything in there

The third allocates a code heap with enough spare space for jump stubs that we may need. Jump stubs are allocated in the same code heap as regular code and we always try to find space for jump stubs in the existing code heaps first.
