### PR TITLE
Ensure side effects are preserved for Arm64

### LINKED ISSUE #105818: JIT: `AdvSimd.BitwiseSelect` discards side effects
```csharp
// Generated by Fuzzlyn v2.2 on 2024-08-01 14:42:46
// Run on Arm64 MacOS
// Seed: 17520120436908093806-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256
// Reduced from 35.4 KiB to 0.6 KiB in 00:00:19
// Debug: Throws 'System.NullReferenceException'
// Release: Runs successfully
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static Vector64<long> s_1;
    public static void Main()
    {
        var vr2 = Vector64.Create<uint>(4294967295U);
        var vr3 = Vector64.Create<uint>(0);
        AdvSimd.BitwiseSelect(vr2, vr3, Vector64.CreateScalar(M2()));
        System.Console.WriteLine(s_1);
    }

    public static uint M2()
    {
        sbyte[] var0 = default(sbyte[]);
        return (uint)var0[0];
    }
}
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #105818

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -31691,6 +31691,7 @@ GenTree* Compiler::gtFoldExprHWIntrinsic(GenTreeHWIntrinsic* tree)
                         // op3 has side effects, this would require us to append a new statement
                         // to ensure that it isn't lost, which isn't safe to do from the general
                         // purpose handler here. We'll recognize this and mark it in VN instead
+                        break;
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:31694]: The `break;` here was apparently lost somewhere and so it was incorrectly folding down to `op2` and losing the side effect

**Review by jakobbotsch — APPROVED** [review]
