### PR TITLE
Fix unnecessary failure when Crossgen'ing dll's without proper Debug Directory data

### LINKED ISSUE #72425: msbuild Publish fails with Error: Invalid directory size.
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/msbuild-Publish-fails-with-Error:-Invali/10090912)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16 to 17]
We are switching from VS 2019/.NET 5 to VS 2022/.NET 6 in our projects. Unfortunately, we now get an exception with the publish target. The build target works fine and the application works normally.
When publishing with the following pubxml

  
    Release
    x64
    ..\bin\Release\publish\
    FileSystem
    net6.0-windows
    win-x64
    true
    False
    True
    False
  

you end up in the exception

...
3>--out:"obj\x64\Release\win-x64\R2R\ActiproSoftware.Shared.Wpf.dll"
3>C:\Program Files (x86)\Actipro Software\WPF-Controls\v14.1.0601\Assemblies\ActiproSoftware.Shared.Wpf.dll
3>
3>Error: Invalid directory size.
3>System.BadImageFormatException: Invalid directory size.
3>   at System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory()
3>   at Internal.TypeSystem.Ecma.PortablePdbSymbolReader.TryOpenEmbedded(PEReader peReader, MetadataStringDecoder stringDecoder)
3>   at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding, ModuleData oldModuleData)
3>   at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding)
3>   at ILCompiler.CompilerTypeSystemContext.GetModuleFromPath(String filePath)
3>   at ILCompiler.Program.Run(String[] args)
3>   at ILCompiler.Program.Main(String[] args)
3>C:\Users\wolfgang\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\6.0.6\tools\crossgen2.exe --targetos:windows
3>--targetarch:x64
3>-O
...

This old third-party DLL from 2014 is included in the project as a reference
    
      C:\Program Files (x86)\Actipro Software\WPF-Controls\v14.1.0601\Assemblies\ActiproSoftware.Shared.Wpf.dll

---
#### Wolfgang Kordts on 7/9/2022, 01:48 AM: 

(private comment, text removed)
#### Feedback Bot on 7/10/2022, 07:20 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/12/2022, 08:48 PM: 

(private comment, text removed)
#### Wolfgang Kordts on 7/14/2022, 00:47 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/12/2022, 08:48 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/14/2022, 07:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by ivdiazsa**
Fixes #72425. When trying to use Crossgen2 with dll's that do not have the proper debug directory data (e.g. obfuscated dll's), a `BadImageException` error is thrown and thus failing the process. In this case, the dll is still usable though debugging tools will probably not work. So, instead of failing, we ought to let the user continue but we shall warn them about this. As a history tidbit, this was the default behavior in .NET 5.

### CODE REVIEW

File: src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs [hunk 1]
```diff
@@ -200,7 +200,26 @@ private EcmaModule AddModule(string filePath, string expectedSimpleName, bool us
...
 
-                    pdbReader = PortablePdbSymbolReader.TryOpenEmbedded(peReader, GetMetadataStringDecoder()) ?? OpenAssociatedSymbolFile(filePath, peReader);
+                    try
+                    {
+                        pdbReader = PortablePdbSymbolReader.TryOpenEmbedded(peReader, GetMetadataStringDecoder())
+                                    ?? OpenAssociatedSymbolFile(filePath, peReader);
+                    }
+                    catch (BadImageFormatException e)
+                    {
+                        if (e.Message.Equals("Invalid directory size."))
```
Comment (mangod9) [inline src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:210]: guess this can be factored out to avoid duplication?

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs [hunk 2]
```diff
@@ -88,8 +89,30 @@ int GetNumDebugDirectoryEntriesInModule()
...
+            catch (BadImageFormatException e)
+            {
+                if (e.Message.Equals("Invalid directory size."))
+                {
+                    int actualDbgDirSize = moduleReader.PEHeaders.PEHeader.DebugTableDirectory.Size;
+
+                    // This comes from the Size property of the DebugDirectoryEntry class.
+                    int expectedDbgDirSizeBase = 28;
+
+                    Console.WriteLine("WARNING: This image's Debug Directory Entry size should be a"
```
Comment (mangod9) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs:108]: these can be created as exception strings instead of string literals?

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs [hunk 3]
```diff
@@ -88,8 +89,30 @@ int GetNumDebugDirectoryEntriesInModule()
...
+            PEReader moduleReader = _module.PEReader;
+            ImmutableArray<DebugDirectoryEntry> entries = ImmutableArray<DebugDirectoryEntry>.Empty;
+
+            try
+            {
+                entries = moduleReader.ReadDebugDirectory();
+            }
+            catch (BadImageFormatException e)
+            {
+                if (e.Message.Equals("Invalid directory size."))
```
Comment (mangod9) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs:101]: not sure if this should be special cased, since on non-english locales this would probably fail anyways

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs (hunk 2 above)
Comment (trylek) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs:108]: I agree we should make this an exception string. I would throw away the "artificial intelligence" analyzing the exception message and just print something generic like "WARNING: %s contains invalid debug information: %s" with the name of the file and the message of the exception caught.

**Review by trylek — COMMENTED** [review]
Mostly looks good, thanks Ivan! I concur with Manish that we should somewhat simplify the warning logic, I have shared my thoughts on that in the PR comments.

**Comment by AntonLapounov** [comment]
Could we create a helper method like below and use it instead of `ReadDebugDirectory` everywhere?
```C#
public static ImmutableArray<DebugDirectoryEntry> ReadDebugDirectoryIgnoringErrors(this PEReader moduleReader)
{
    try
    {
        return moduleReader.ReadDebugDirectory();
    }
    catch (BadImageFormatException e)
    {
        // Report a warning using e.Message
        return ImmutableArray<DebugDirectoryEntry>.Empty;
    }
 }
```

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs (hunk 3 above)
Comment (ivdiazsa) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs:101]: I special cased this as well because it failed otherwise with the same BadImageException.

Comment (AntonLapounov) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs:101]: Since `e.Message` will be localized, this check will not work for any language except English.

**Comment by ivdiazsa** [comment]
Thank you all for the feedback! I have a few questions whatsoever.

First, I'm a big advocate of helper functions as long as it doesn't end up being a big scramble of chained functions (which this is clearly not the case). My question I would like guidance on is where would be the most appropriate place/file to write the helper function, since these two files are in different csproj's. One is in `ILCompiler.Compiler` and the other one is in `ILCompiler.ReadyToRun`.

My other question is regarding the string literal, and it's in a very similar boat. The original throwing function in `System.Reflection.Metadata`, gets the string from a class called `SR`. Here is the original throwing line: 
https://github.com/dotnet/runtime/blob/10438a57b888cbdc6dc15771dc662adde9fd6b14/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs#L541-L544

This `SR` class then called a method named `GetResourceString()` to fetch it from here: 
https://github.com/dotnet/runtime/blob/d34c0ff7c104b3c6e39eb17cc0d21b7ca2dc5c6d/src/libraries/System.Reflection.Metadata/src/Resources/Strings.resx#L270-L272

I might have missed something, but I couldn't get any sort of access to there from our codebase. So, we might just have to create a constant like you mentioned, but my question is where would be most appropriate.

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs (hunk 2 above)
Comment (ivdiazsa) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryNode.cs:108]: I think we can afford to keep the part that says "Debugging tools may not work correctly with this image". I feel our users would like to know what the warning entails for them.

**Comment by AntonLapounov** [comment]
Would it be possible to add both the helper and the resource string to a shared assembly, e.g., `src\coreclr\tools\Common\TypeSystem\Common\Properties\Resources.resx`?

**Comment by trylek** [comment]
@ivdiazsa - what you're looking at is standardized support for localized resources. Crossgen2 uses them too, e.g. here:

https://github.com/dotnet/runtime/blob/48ce77b3de820fa3788938c4abc6e90e0ab39276/src/coreclr/tools/aot/crossgen2/CommandLineOptions.cs#L152

This is coming from the file

https://github.com/dotnet/runtime/blob/48ce77b3de820fa3788938c4abc6e90e0ab39276/src/coreclr/tools/aot/crossgen2/Properties/Resources.resx#L126

that you can edit with VS (or manually). Having said that, proper location depends on the assembly you put the helper in. Are you sure that you see a failure in <code>ILCompiler.Compiler? I was under the impression that is only used by NativeAOT.

**Comment by AntonLapounov** [comment]
> Are you sure that you see a failure in `ILCompiler.Compiler`?

It would be nice to have the same behavior for both.  And there are other places that should be fixed, e.g., https://github.com/dotnet/runtime/blob/ad60e446454c54e25415519bd2570481c8b4973b/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryEntryNode.cs#L253

**Comment by trylek** [comment]
If we want a common fix for Crossgen2 and NativeAOT, it should be probably under <code>src/coreclr/tools/Common</code> that is shared between them. Perhaps this file seems loosely related:

https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/Common/System/FormattingHelpers.cs

File: src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs [hunk 4]
```diff
@@ -200,7 +200,26 @@ private EcmaModule AddModule(string filePath, string expectedSimpleName, bool us
...
+                        {
+                            int actualDbgDirSize = peReader.PEHeaders.PEHeader.DebugTableDirectory.Size;
+
+                            // This comes from the Size property of the DebugDirectoryEntry class.
+                            int expectedDbgDirSizeBase = 28;
+
+                            Console.WriteLine("WARNING: This image's Debug Directory Entry size should be a"
+                                            + $" multiple of {expectedDbgDirSizeBase}, but was {actualDbgDirSize}."
+                                            + " Debugging tools may not work correctly with this image.");
```
Comment (jkotas) [inline src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:219]:
```suggestion
                                            + " Diagnostic tools may not work correctly with this image.");
```
It is also profilers, etc.

File: src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs (hunk 1 above)
Comment (jkotas) [inline src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:210]: There are many other ways that the debug symbols can be corrupted, we just have not seen them. Should we catch all exceptions here and print that the debug symbols are corrupted, and include the error message from the exception?

File: src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs [hunk 5]
```diff
@@ -200,7 +200,26 @@ private EcmaModule AddModule(string filePath, string expectedSimpleName, bool us
                     throw new NotSupportedException($"Error: C++/CLI is not supported: '{filePath}'");
 #endif
 
-                    pdbReader = PortablePdbSymbolReader.TryOpenEmbedded(peReader, GetMetadataStringDecoder()) ?? OpenAssociatedSymbolFile(filePath, peReader);
+                    try
+                    {
+                        pdbReader = PortablePdbSymbolReader.TryOpenEmbedded(peReader, GetMetadataStringDecoder())
+                                    ?? OpenAssociatedSymbolFile(filePath, peReader);
+                    }
+                    catch (BadImageFormatException e)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:208]: This is placed in a very broad spot. A lot of code is going to run and could throw a BadImageFormat (S.R.Metadata will throw it for any sort of corruption).

Can you instead add a e.g. `SafeReadDebugDirectory(this PEReader peReader)` extension method that simply checks the directory size before calling the API and returns `ImmutableArray<DebugDirectoryEntry>.Empty` if it doesn't make sense?

But doing Console.WriteLine in arbitrary spots is not a great practice because we're multithreaded. I would honestly just swallow this.

File: src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs (hunk 1 above)
Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:210]: > There are many other ways that the debug symbols can be corrupted, we just have not seen them. Should we catch all exceptions here and print that the debug symbols are corrupted, and include the error message from the exception?

None of the compiler is hardened for obfuscators. I wouldn't treat debug information very differently.

Comment (MichalStrehovsky) [reply src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:210]: (We might successfully open the debug information but there can be exceptions once we start looking into it.)

**Comment by ivdiazsa** [comment]
> @ivdiazsa - what you're looking at is standardized support for localized resources. Crossgen2 uses them too, e.g. here:
> 
> https://github.com/dotnet/runtime/blob/48ce77b3de820fa3788938c4abc6e90e0ab39276/src/coreclr/tools/aot/crossgen2/CommandLineOptions.cs#L152
> 
> This is coming from the file
> 
> https://github.com/dotnet/runtime/blob/48ce77b3de820fa3788938c4abc6e90e0ab39276/src/coreclr/tools/aot/crossgen2/Properties/Resources.resx#L126
> 
> that you can edit with VS (or manually). Having said that, proper location depends on the assembly you put the helper in. Are you sure that you see a failure in `ILCompiler.Compiler`? I was under the impression that is only used by NativeAOT.

Thanks a lot for the pointers Tomas! Yes, actually the initial failure was under ILCompiler.Compiler. I only found out the ReadyToRun ones when I tried testing the fix and it started failing there then.

File: src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs (hunk 5 above)
Comment (ivdiazsa) [reply src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:208]: I did not consider the fact of multithreading. Thanks for your feedback Michal! I think this is a great suggestion, I'll get to work on it.

**Comment by AntonLapounov** [comment]
Thank you, that is much cleaner.  I think we should also fix one more place I mentioned above: https://github.com/dotnet/runtime/blob/ad60e446454c54e25415519bd2570481c8b4973b/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryEntryNode.cs#L253

There are also two occurrences of `ReadDebugDirectory()` under `src\coreclr\tools\dotnet-pgo`.

File: src/coreclr/tools/Common/TypeSystem/Common/PortableExecutableMethodExtensions.cs [hunk 6]
```diff
@@ -0,0 +1,24 @@
...
+namespace Internal.TypeSystem
+{
+    public static class PortableExecutableMethodExtensions
+    {
+        public static ImmutableArray<DebugDirectoryEntry> SafeReadDebugDirectory(this PEReader peReader)
+        {
+            int actualDbgDirSize = peReader.PEHeaders.PEHeader.DebugTableDirectory.Size;
+
+            // This comes from the Size property of the DebugDirectoryEntry class.
+            int expectedDbgDirSizeBase = 28;
```
Comment (AntonLapounov) [inline src/coreclr/tools/Common/TypeSystem/Common/PortableExecutableMethodExtensions.cs:16]: Nit: Might use `const` here:
```suggestion
            const int ExpectedDbgDirSize = 28;
```

**Comment by ivdiazsa** [comment]
> Thank you, that is much cleaner. I think we should also fix one more place I mentioned above:
> 
> https://github.com/dotnet/runtime/blob/ad60e446454c54e25415519bd2570481c8b4973b/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugDirectoryEntryNode.cs#L253
> 
> There are also two occurrences of `ReadDebugDirectory()` under `src\coreclr\tools\dotnet-pgo`.

Sure thing. I wasn't sure whether I should be meddling with PGO as well, but you're right, it doesn't seem like it would break anything in this case.

**Comment by AntonLapounov** [comment]
It would be nice to have consistent behavior at least within our own AoT toolchain.

**Review by AntonLapounov — APPROVED** [review]
Thank you for fixing this!
