### PR TITLE
Fix lowering usage of an unset LSRA field.

### LINKED ISSUE #54466: `Vector2.One` is not always <1, 1> in some case (silent bad codegen)
Reduced repro - Windows x64, repros at commit 9c0bf218fdeb34e7682bb536f3400fd6910dd386 :

1. Compile with optimizations on:
```csharp
using System;
using System.Numerics;
using System.Runtime.CompilerServices;

t(1, 1, 1, 1, Vector2.One, Vector2.One, Vector2.One, Vector2.One);

[MethodImplAttribute(MethodImplOptions.NoInlining)]
static void t(int a1, int a2, int a3, int a4, Vector2 x1, Vector2 x2, Vector2 x3, Vector2 x4)
{
   if (x1 != Vector2.One) Console.WriteLine("FAIL");
}
```
2. Run (with `COMPlus_TieredCompilation=0`)

Actual result: 
- Checked build: Assertion failed 'isFloatReg(dstReg) && isFloatReg(srcReg)' in '<Program>$:<Main>$(System.String[])' during 'Generate code'
- Release build: FAIL

Expected result: passes without asserts or errors

---
I have some code:
```c#
        public static void DrawSpriteFrame(this CommandBuffer commandBuffer, SpriteFrame spriteFrame, Vector2 position, Color color, float layerDepth = 0f)
        {
            DrawSpriteFrame(commandBuffer, spriteFrame, position, null, color, Vector2.One, 0f, SpriteEffects.None, layerDepth);
        }

        public static void DrawSpriteFrame(this CommandBuffer commandBuffer, SpriteFrame spriteFrame, Vector2 position, Rectangle areaRewrite, Color color, float layerDepth = 0f)
        {
            DrawSpriteFrame(commandBuffer, spriteFrame, position, areaRewrite, color, Vector2.One, 0f, SpriteEffects.None, layerDepth);
        }

        public static void DrawSpriteFrame(this CommandBuffer commandBuffer, SpriteFrame spriteFrame, Vector2 position, Size sizeRewrite, Color color, float layerDepth = 0f)
        {
            var areaRewrite = new Rectangle(0, 0, sizeRewrite.Width, sizeRewrite.Height);
            DrawSpriteFrame(commandBuffer, spriteFrame, position, areaRewrite, color, Vector2.One, 0f, SpriteEffects.None, layerDepth);
        }

        public static void DrawSpriteFrame(this CommandBuffer commandBuffer, SpriteFrame spriteFrame, Vector2 position, Rectangle? areaRewrite, Color color, Vector2 scale, float rotation = 0f, SpriteEffects spriteEffects = SpriteEffects.None, float layerDepth = 0f)
        {
            if (scale != Vector2.One)
            {
                Console.WriteLine("Scale is: {0}", scale);
                return;
            }
            ...
        }
```

The `Vector2.One` passed to method calls is not actually equal to `Vector2.One` in NativeAOT sometimes. It returns `<6.28E-43, 5.27E-43>` instead. But everything is fine is CoreCLR. And I'm sure the value of the `scale` parameter is always <1, 1> in all code logic.

The workaround I found: Change the method call parameter `Vector2.One` to `new Vector2(1, 1)`.

Which looks like:
```c#
        public static void DrawSpriteFrame(this CommandBuffer commandBuffer, SpriteFrame spriteFrame, Vector2 position, Color color, float layerDepth = 0f)
        {
            DrawSpriteFrame(commandBuffer, spriteFrame, position, null, color, new Vector2(1f, 1f), 0f, SpriteEffects.None, layerDepth);
        }
```

### PR DESCRIPTION
**Pull request by sandreenko**
The old code was using `m_lsra->isRegCandidate(varDsc)` that reads `lvIsTracked` field that is not set during lowering and until liveness. So we were reading default `lvIsTracked=false` and always saying that it is not a reg candidate.

The issue started to happen after we added HW support in VN/CSE, it started to produce wrong results, then we added more checks in codegen and it started to fail with assert.

No diffs, the codegen is now clever enough to skip bitcast node when the source is in memory. In theory, we still don't want to create it for TP purposes so we need something like "varIsAlreadyKnownToBeInMemory" but I will try to add it in another change.

Fixes https://github.com/dotnet/runtime/issues/54466

### CODE REVIEW

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -3101,19 +3101,11 @@ void Lowering::LowerStoreLocCommon(GenTreeLclVarCommon* lclStore)
     if ((varTypeUsesFloatReg(lclStore) != varTypeUsesFloatReg(src)) && !lclStore->IsPhiDefn() &&
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:3101]: Do we still need ` !lclStore->IsPhiDefn()` now that `PHI`s are no more in the backend?

Comment (sandreenko) [reply src/coreclr/jit/lower.cpp:3101]: Nop, thanks, will delete.

**Comment by sandreenko** [comment]
PTAL @kunalspathak @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]
Any diffs?

**Comment by sandreenko** [comment]
> Any diffs?

It is good that you asked, I wrote that there is none but now I checked again and saw 1 that I lost in the thousands of SPMI downloading lines.

```
asm.coreclr_tests.pmi.Linux.x64.checked
Top method regressions (bytes):
          10 ( 0.27% of base) : 239371.dasm - BringUpTest:Main():int
1 total methods with Code Size differences (0 improved, 1 regressed), 0 unchanged.
```

added a comment to fix it later.

**Review by kunalspathak — APPROVED** [review]
LGTM...are the CI failures related to your change?

**Comment by sandreenko** [comment]
> LGTM...are the CI failures related to your change?

part of them are, I am working on a fix, looks like the fix will have to be bigger than I thought.

**Comment by sandreenko** [comment]
The failures are unrelated (at least I have not seen any JIT asserts and they failed in the previous run, so looking like infa).
The regressions are small (the worst is coreclr_tests.pmi.Linux.arm.checked.mch Total bytes of delta: 110, 9 total methods with Code Size differences (0 improved, 9 regressed)). I will fix them in a separate PR, this is just correctness.

**Comment by kunalspathak** [comment]
Potential regression: https://github.com/DrewScoggins/performance-2/issues/7131. Needs investigation.

**Comment by kunalspathak** [comment]
Potential improvement: https://github.com/DrewScoggins/performance-2/issues/7138

**Comment by kunalspathak** [comment]
@sandreenko  - do you mind taking a look at the regression?

**Comment by sandreenko** [comment]
> @sandreenko - do you mind taking a look at the regression?

I am planning to fix #54841 this week and it will most likely go away. I can't assign the issue to myself (it is in a fork).

**Comment by kunalspathak** [comment]
> Potential regression: DrewScoggins/performance-2#7131. Needs investigation.

@DrewScoggins - this is the one that needs a transfer.
