### PR TITLE
Fix unboxing handling of Method_Handles

### LINKED ISSUE #52034: crossgen2 produces incorrect [UNBOX] flag for valuetype method fixups
### Description

Crossgen2 produces incorrect fixups for a method which has valuetype instance method fixups. Consider the method `Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer+DefaultDateTimeOffsetValueComparer..ctor(bool)` within `Microsoft.EntityFrameworkCore` crossgen1 produces the following fixups for it:

```
void Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer+DefaultDateTimeOffsetValueComparer..ctor(bool)
Handle: 0x06002D90
Rid: 11664
EntryPointRuntimeFunctionId: 11137
Number of RuntimeFunctions: 1
Number of fixups: 8
    TableIndex 4, Offset 04EB: "v1" (STRING_HANDLE)
    TableIndex 4, Offset 04EC: "v2" (STRING_HANDLE)
    TableIndex 5, Offset 0026: System.DateTimeOffset (TYPE_HANDLE)
    TableIndex 5, Offset 041E: System.RuntimeMethodHandle Flags READYTORUN_LAYOUT_Alignment, READYTORUN_LAYOUT_Alignment_Native, READYTORUN_LAYOUT_GCLayout Size 8 GCLayout 1 (CHECK_TYPE_LAYOUT)
    TableIndex 5, Offset 042D: System.TimeSpan System.DateTimeOffset.get_Offset() (METHOD_HANDLE)
    TableIndex 5, Offset 0DFB: bool System.DateTimeOffset.op_Equality(System.DateTimeOffset, System.DateTimeOffset) (METHOD_HANDLE)
    TableIndex 5, Offset 0DFC: bool System.TimeSpan.op_Equality(System.TimeSpan, System.TimeSpan) (METHOD_HANDLE)
    TableIndex 5, Offset 0DFD: [INST] System.Linq.Expressions.Expression`1<!!0> System.Linq.Expressions.Expression.Lambda<!!0>(System.Linq.Expressions.Expression, System.Linq.Expressions.ParameterExpression[])<System.Func`3<System.DateTimeOffset,System.DateTimeOffset,bool>> (METHOD_DICTIONARY)
```

With crossgen2 these are the fixups:

```
void Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer+DefaultDateTimeOffsetValueComparer..ctor(bool)
Handle: 0x06002D90
Rid: 11664
EntryPointRuntimeFunctionId: 9164
Number of RuntimeFunctions: 1
Number of fixups: 9
    TableIndex 4, Offset 0013: [UNBOX] System.TimeSpan System.DateTimeOffset.get_Offset() (METHOD_HANDLE)
    TableIndex 4, Offset 0017: bool System.DateTimeOffset.op_Equality(System.DateTimeOffset, System.DateTimeOffset) (METHOD_HANDLE)
    TableIndex 4, Offset 0024: bool System.TimeSpan.op_Equality(System.TimeSpan, System.TimeSpan) (METHOD_HANDLE)
    TableIndex 4, Offset 03C8: [INST] System.Linq.Expressions.Expression`1<!!0> System.Linq.Expressions.Expression.Lambda<!!0>(System.Linq.Expressions.Expression, System.Linq.Expressions.ParameterExpression[])<System.Func`3<System.DateTimeOffset,System.DateTimeOffset,bool>> (METHOD_DICTIONARY)
    TableIndex 4, Offset 07DA: System.RuntimeMethodHandle (TYPE_HANDLE)
    TableIndex 4, Offset 07E6: System.DateTimeOffset (TYPE_HANDLE)
    TableIndex 4, Offset 0C7C: System.RuntimeMethodHandle Flags READYTORUN_LAYOUT_Alignment, READYTORUN_LAYOUT_Alignment_Native, READYTORUN_LAYOUT_GCLayout Size 8 GCLayout 1 (CHECK_TYPE_LAYOUT)
    TableIndex 5, Offset 050C: "v1" (STRING_HANDLE)
    TableIndex 5, Offset 050D: "v2" (STRING_HANDLE)
```

Notice the `[UNBOX]` flag for `System.DateTimeOffset.get_Offset()`

### Regression?

Not a regression in crossgen2, but it was discovered because crossgen2 is now being used by default when using `PublishReadyToRun` within the sdk. 

### Other information

This causes the typesystem to assign a separate MethodDesc to the method, which causes equivalence issue within Reflection leading to a failure in EF.

### PR DESCRIPTION
**Pull request by mangod9**
Fixes https://github.com/dotnet/runtime/issues/52034

### CODE REVIEW

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs [hunk 1]
```diff
@@ -2206,11 +2206,7 @@ private void embedGenericHandle(ref CORINFO_RESOLVED_TOKEN pResolvedToken, bool
                             MethodDesc md = HandleToObject(pResolvedToken.hMethod);
                             TypeDesc td = HandleToObject(pResolvedToken.hClass);
 
-                            bool unboxingStub = false;
-                            if ((td.IsValueType) && !md.Signature.IsStatic)
-                            {
-                                unboxingStub = true;
-                            }
+                            bool unboxingStub = md.IsUnboxingThunk();
```
Comment (mangod9) [inline src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:2209]: I have tried to mimic it from cg1: https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/coreclr/vm/zapsig.cpp#L1257. But not sure if `UnboxingThunk` and `UnboxingStub` mean the same thing? 

I have validated the repro test works with this change, but not sure if it breaks other scenarios.

**Review by trylek — APPROVED** [review]
Simon implemented the logic around UnboxingMethodDesc but I believe it was the intent to basically mimic the runtime UnboxingStub; to me your change looks good, thank you for fixing this so quickly!

**Comment by mangod9** [comment]
assume I should also run the `runtime-coreclr crossgen2` pipeline to validate it doesnt break things, or is it the outerloop one?

**Comment by trylek** [comment]
The runtime-coreclr crossgen2 is defintely useful to test that the change doesn't break things in general. Outerloop runs the larger (Pri1) test suite but it takes much longer, runs on fewer platforms and I'm unsure how much value it would have in this particular case considering the Pri1 testing hasn't revealed this issue so far i.o.w. apparently there's not much coverage in this space.

**Comment by mangod9** [comment]
FYI @dotnet/crossgen-contrib . The failures are due to the helix upload issues, rerunning them now

File: src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs (hunk 1 above)
Comment (mangod9) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:2209]: So this test caught a regression: https://github.com/dotnet/runtime/blob/49aec59e52d2f0bc8e2acd297023aa8464aee00c/src/tests/Regressions/coreclr/GitHub_41674/genericldtoken.il#L35

It appears that this flag is not correctly propagated in crossgen2: https://github.com/dotnet/runtime/blob/dec321c12ed283b3c19e829ed7d7a2248ce072b0/src/coreclr/vm/method.hpp#L1837

Needs some better handling here, @davidwrighton in case you have thoughts on this.  

cg1:
```
    TableIndex 2, Offset 0002: [UNBOX] string GenericStruct`1<string>.B() (METHOD_HANDLE)
```
cg2:
```
    TableIndex 4, Offset 0000: [INST] string GenericStruct`1<string>.B() (METHOD_HANDLE)
```

Comment (mangod9) [reply src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs]: Ok a more reasonable fix is to check if the method is `!Static && IsVirtual`. The runtime behavior is here: https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/coreclr/vm/methodtablebuilder.cpp#L6984. For now just added the virtual check but need to determine if the other two checks need to be handled as well.

**Comment by mangod9** [comment]
I have validated the linux builds are now fixed with a manual run: https://dev.azure.com/dnceng/public/_build/results?buildId=1116202&view=results
