### PR TITLE
[loader] Clean up locking around adding assemblies to domain/ALC

### LINKED ISSUE #2305: [mono][loader] CI test failure "appdomain.c:1591, condition !ass->image->references [i]' not met"
Full assertion: 

```* Assertion at /Users/runner/runners/2.164.6/work/1/s/src/mono/mono/metadata/appdomain.c:1591, condition `!ass->image->references [i] not met', function:add_assembly_to_alc, Did not expect reference 0 of /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/System.Net.Http.dll to be resolved```

Happened on an OSX CI lane.  [Failure log here](https://helix.dot.net/api/2019-06-17/jobs/bc78d79b-b720-458d-a443-2463dcd85d2a/workitems/System.Net.Requests.Tests/console)  The full test log https://dev.azure.com/dnceng/public/_build/results?buildId=499602&view=logs&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=22b0078b-0469-5ba6-8725-2121fdbae049&l=50

Stack trace:

```
	0x107901602 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_dump_native_crash_info
	0x1078a3b55 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_handle_native_crash
	0x107900c1b - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : sigabrt_signal_handler
	0x7fff6249ff5a - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x0 - Unknown
	0x7fff6223d1ae - /usr/lib/system/libsystem_c.dylib : abort
	0x107abe1c7 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : monoeg_assert_abort
	0x107a9ed67 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_log_write_logfile
	0x107abe655 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : monoeg_g_logv_nofree
	0x107abe7df - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : monoeg_assertion_message
	0x10795dd07 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_domain_fire_assembly_load
	0x1079679cc - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_assembly_invoke_load_hook_internal
	0x107968d58 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_assembly_request_load_from
	0x1079686c0 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_assembly_request_open
	0x1079021ce - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_core_preload_hook
	0x10796b591 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : invoke_assembly_preload_hook
	0x1079677a8 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_assembly_request_byname
	0x10796721e - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_assembly_load_reference
	0x10796d2eb - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_class_from_typeref_checked
	0x1079acac2 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : method_from_memberref
	0x1079aae00 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_get_method_checked
	0x10783c7e5 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mini_get_method
	0x1078188b5 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_method_to_ir
	0x1077fdae9 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mini_method_compile
	0x1077fffdc - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_jit_compile_method_inner
	0x107803de2 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_jit_compile_method_with_opt
	0x1078a667f - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : common_call_trampoline
	0x1078a7390 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_vcall_trampoline
	0x107c92293 - Unknown
	0x10c9db25a - Unknown
	0x10cb02c53 - Unknown
	0x10c9db25a - Unknown
	0x10cad0ab3 - Unknown
	0x10c9db25a - Unknown
	0x10cae7f53 - Unknown
	0x10780833e - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_jit_runtime_invoke
	0x1079dd888 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_runtime_invoke_checked
	0x1079e5292 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_runtime_try_invoke_array
	0x10798f634 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : ves_icall_InternalInvoke
	0x10799b717 - /private/tmp/helix/working/AF4D0979/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : ves_icall_InternalInvoke_raw
	0x10b642509 - Unknown
	0x10b641689 - Unknown
	0x10c9da28b - Unknown
	0x10c9da163 - Unknown
	0x10c9d9a3b - Unknown
	0x10c9d98bb - Unknown
	0x10c9d9043 - Unknown
	0x10c9d8ed3 - Unknown
	0x10c9d7953 - Unknown
	0x10c9d7823 - Unknown
	0x10c9d1b6b - Unknown
	0x10c9d17e3 - Unknown
	0x10c9ce253 - Unknown
	0x10c9ce08b - Unknown
	0x10c9ca681 - Unknown
	0x10c9c8753 - Unknown
	0x10c9c810b - Unknown
	0x10c9c5b5b - Unknown
	0x10c9c56b3 - Unknown
	0x10c9c281b - Unknown
	0x10c9c2413 - Unknown
	0x10c9bcb6b - Unknown
	0x10c9bc663 - Unknown
	0x10c9bc533 - Unknown
	0x10c9bb84e - Unknown
	0x10c9bafeb - Unknown
	0x10c9baeb3 - Unknown
	0x10c9b9fbb - Unknown
	0x10c9b9e93 - Unknown
	0x10c9b14d3 - Unknown
	0x10c9b07eb - Unknown
	0x10c9b06a3 - Unknown
	0x10c9aca43 - Unknown
	0x10c9ac913 - Unknown
	0x10c9ab938 - Unknown
	0x10c9ab26b - Unknown
	0x10c9ab133 - Unknown
	0x10c985db3 - Unknown
	0x10c985b43 - Unknown
	0x10c984bc8 - Unknown
	0x10bb83313 - Unknown
	0x10c9845c3 - Unknown
	0x10c97d033 - Unknown
	0x10bb83b16 - Unknown
	0x10bb83313 - Unknown
	0x10bb7aeeb - Unknown
```

### PR DESCRIPTION
**Pull request by CoffeeFlux**
This cleans up three components of assembly loading that could potentially cause races/crashes.

First, both `add_assemblies_to_domain` and `add_assembly_to_alc` now ignore resolved references on netcore. We were seeing a crash on CI related to an assertion in here that resulted from two threads using the same MonoImage simultaneously as one is being loaded in with LoadFile, and this should solve that. Fixes #2305 

Second, we take both the domain and ALC loaded assemblies locks simultaneously around the assembly being added to both lists, ensuring they stay in sync.

Finally, MonoImage now takes the image lock when writing to references instead of using the global `assemblies_mutex` in assembly.c for all images. This potentially helps reduce contention. Work here is not complete, but for this PR it's good enough. See #32889

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
This is failing in `add_assemblies_to_domain` with the new assert, but it's failing much more frequently than the ALC one, which is good! Should be easier to track down how that reference is being resolved.

**Review by lambdageek — APPROVED** [review]

File: src/mono/mono/metadata/appdomain.c [hunk 1]
```diff
@@ -128,7 +128,7 @@ static gboolean
 mono_domain_asmctx_from_path (const char *fname, MonoAssembly *requesting_assembly, gpointer user_data, MonoAssemblyContextKind *out_asmctx);
 
 static void
-add_assemblies_to_domain (MonoDomain *domain, MonoAssembly *ass, GHashTable *hash);
+add_assemblies_to_domain (MonoDomain *domain, MonoAssembly *ass, GHashTable *ht);
```
[the remark this answers is not in the document]
Comment (CoffeeFlux) [reply src/mono/mono/metadata/appdomain.c]: Maybe it's not worth the churn; I just noticed they were inconsistent and thought I'd fix it.

File: src/mono/mono/metadata/metadata-internals.h [hunk 2]
```diff
@@ -431,6 +431,7 @@ struct _MonoImage {
 	 */
 	MonoAssembly **references;
 	int nreferences;
+	mono_mutex_t references_lock;
```
Comment (lambdageek) [inline src/mono/mono/metadata/metadata-internals.h]: I wonder what it would take to split up `MonoImage` into a base class (say `MonoEcmaImage`) that only knows about tables and such and make the current `MonoImage` a subclass for the main image of an assembly.  And we could have a separate `MonoPdbImage` or `MonoDeltaImage` that only has a subset of the concrete fields that are relevant for PPDBs or E&C images.

File: src/mono/mono/metadata/assembly.c [hunk 3]
```diff
@@ -1783,15 +1793,15 @@ mono_assembly_load_reference (MonoImage *image, int index)
 	 * image->references is shared between threads, so we need to access
 	 * it inside a critical section.
 	 */
-	mono_assemblies_lock ();
+	mono_image_references_lock (image);
```
Comment (vargaz) [inline src/mono/mono/metadata/assembly.c]: There is already a mono_image_lock () low level lock.

Comment (lambdageek) [reply src/mono/mono/metadata/assembly.c]: @vargaz what are the reasons to prefer using the image lock instead of having a separate lock just for this field?

**Comment by CoffeeFlux** [comment]
Waiting to hear from Zoltan.

File: src/mono/mono/metadata/assembly.c (hunk 3 above)
Comment (CoffeeFlux) [reply src/mono/mono/metadata/assembly.c]: @vargaz ping

**Review by lambdageek — APPROVED** [review]
