### PR TITLE
[HTTP] H/3 fix test closing server connection prematurely

### LINKED ISSUE #117198: `SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException` fails with QUIC protocol error
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082667&view=results
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["Sub-string not found", "SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082667
**Error message validated:** `[Sub-string not found SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/1/2025 2:05:19 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1083776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083776)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest_Http3.SendAsync_ReuseRequestInHandler_ResetsHeadersForEachReuse](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083776&view=ms.vss-test-web.build-test-results-tab&runId=29491730&resultId=157764)||
|[1083778](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083778)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083778&view=ms.vss-test-web.build-test-results-tab&runId=29490784&resultId=228626)||
|[1083739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083739)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083739&view=ms.vss-test-web.build-test-results-tab&runId=29489820&resultId=227451)|dotnet/runtime#117234|
|[1083690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083690)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083690&view=ms.vss-test-web.build-test-results-tab&runId=29485830&resultId=227214)|dotnet/runtime#116901|
|[1082667](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082667)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082667&view=ms.vss-test-web.build-test-results-tab&runId=29453036&resultId=227050)|dotnet/runtime#117051|
|[1081986](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081986)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081986&view=ms.vss-test-web.build-test-results-tab&runId=29435164&resultId=228358)|dotnet/runtime#117154|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|6|6|

### PR DESCRIPTION
**Pull request by ManickaP**
Adds more synchronization into the test so that the server doesn't close before the client can observe the expected exception.

Fixes #117198

### CODE REVIEW

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs [hunk 1]
```diff
@@ -2232,7 +2234,13 @@ await LoopbackServerFactory.CreateClientAndServerAsync(async uri =>
...
                 if (await acceptConnection.Task)
                 {
-                    await IgnoreExceptions(server.AcceptConnectionAsync(c => Task.CompletedTask));
+                    await IgnoreExceptions(async () =>
+                    {
+                        await server.AcceptConnectionAsync(async _ =>
+                        {
+                            await clientFinished.WaitAsync(TestHelper.PassingTestTimeout);
+                        });
+                    });
```
Comment (CarnaViire) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs]: nit
```suggestion
                    await IgnoreExceptions(() =>
                        server.AcceptConnectionAsync(_ =>
                            clientFinished.WaitAsync(TestHelper.PassingTestTimeout)));
```

**Review by CarnaViire — APPROVED** [review]
lgtm
