### PR TITLE
Fix handling of corrupted state exceptions on Windows

### LINKED ISSUE #73794: AccessViolationException should not be catchable
### Description

When an AccessViolationException is thrown, the exception is supposed to be uncatchable. With recent changes in the reflection-invoke machinery, an AccessViolationException that is thrown through reflection-invoke is wrapped in a catchable TargetInvocationException.

This was discovered when updating dotnet/arcade to Preview 7 from Preview 5 (I've validated that the regression started in Preview 6).

### Simplified Repro Steps
(Added by @AntonLapounov.)
```C#
using System;

try
{
    unsafe { *(int*)0x10000 = 0; }
}
catch (AccessViolationException)
{
    Console.WriteLine("Shouldn't be able to catch this exception.");
}
```

### Reproduction Steps

```csharp
using System;
using System.Reflection;
try
{
    typeof(A).GetMethod(nameof(A.AV)).Invoke(null, null);
}
catch (TargetInvocationException ex) when(ex.InnerException is AccessViolationException)
{
      Console.WriteLine("Shouldn't be able to catch this exception.");
}

class A
{
     public unsafe static void AV()
     {
          *(int*)0x10000 = 0;
     }
} 
```

### Expected behavior

The process crashes

### Actual behavior

"Shouldn't be able to catch this exception." is written to the console.

### Regression?

This is a regression from .NET 7 Preview 5 and earlier

### Known Workarounds

Explicitly check for a TargetInvocationException with an inner AV and don't catch it.

### Configuration

Windows 11 x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by AntonLapounov**
The new code for handling hardware exceptions (which was enabled only for Windows x64 with CET before #70428 and became enabled for all Windows targets after #70428) would translate hardware exceptions into managed exception in the `HandleManagedFault` function. That translation broke recognizing corrupted state exceptions in the `ProcessCLRException` function, because the exception would have the generic `EXCEPTION_COMPLUS` exception code instead of the original hardware exception code.

The fix is to re-raise the original exception in `HandleManagedFault`, keeping its `CONTEXT`, and leave handling the exception to `ProcessCLRException`, similar to how it used to work before #70428.

Fixes #73794. @janvorli @jkotas

### CODE REVIEW

File: src/coreclr/vm/excep.cpp [hunk 1]
```diff
@@ -6533,59 +6533,30 @@ AdjustContextForJITHelpers(
...
+           offsetof(EXCEPTION_RECORD, ExceptionInformation)
+          );
 
-    DEBUG_NOINLINE void Enter()
-    {
-        WRAPPER_NO_CONTRACT;
-        ANNOTATION_SPECIAL_HOLDER_CALLER_NEEDS_DYNAMIC_CONTRACT;
-        m_Crst.Enter();
-    }
+    ReplaceExceptionContextRecord(ep->ContextRecord, pParam->pContext);
```
Comment (mangod9) [inline src/coreclr/vm/excep.cpp:6554]: does this handle the special casing of non-catchable exceptions?

Comment (AntonLapounov) [reply src/coreclr/vm/excep.cpp:6554]: We need to restore the original context record for diagnostic purposes.  Moreover, handling of the `STATUS_ACCESS_VIOLATION` code depends on having the correct IP address in the context record.  If the IP address belongs to managed code and the failing address is in the first 64 KiB, we translate that to a harmless `NullReferenceException`.

Comment (AntonLapounov) [reply src/coreclr/vm/excep.cpp:6554]: I restored this snippet from #70428.  We need to restore the original context record for diagnostic purposes.  Moreover, handling of the `STATUS_ACCESS_VIOLATION` code depends on having the correct IP address in the exception record.  If the IP address belongs to managed code and the address we failed to access is in the first 64 KiB, we translate that to a harmless `NullReferenceException`.

**Comment by mangod9** [comment]
Should we add a test for this, so it doesn't regress again?

**Comment by kouvel** [comment]
I see the problem and I see how the solution works, but I'm not familiar enough with the nuances of the area to review this change.

File: src/coreclr/vm/excep.cpp [hunk 2]
```diff
@@ -6533,59 +6533,48 @@ AdjustContextForJITHelpers(
...
-        memcpy(&m_ExceptionRecord, pExceptionRecord, erSize);
-
-    }
+    WRAPPER_NO_CONTRACT;
 
-    void SaveContext(CONTEXT *pContext)
-    {
-        LIMITED_METHOD_CONTRACT;
-#ifdef CONTEXT_EXTENDED_REGISTERS
+    // don't copy param args as have already supplied them on the throw
```
Comment (jkotas) [inline src/coreclr/vm/excep.cpp:6543]: This is copying `NumberParameters` that is not strictly necessary according to this comment.

I think it would look better to just explicitly assign the 4 fields that this needs to copy.

File: src/coreclr/vm/excep.cpp [hunk 3]
```diff
@@ -6533,59 +6533,48 @@ AdjustContextForJITHelpers(
...
+    memcpy((void*) ep->ExceptionRecord,
```
Comment (jkotas) [inline src/coreclr/vm/excep.cpp:6544]: What is `EXCEPTION_RECORD::ExceptionRecord` used for? Is always going to be NULL here or is it actually used for something?

**Review by jkotas — APPROVED** [review]
It looks good to me. 

I suspect that this is not the last fix. We are likely to discover more issues around debugging or diagnosability here. I would recommend to:
- Verify VS debugger handling of the hardware faults with this change - both with interop debugging on and off.
- Verify watson dump triaging of the hardware faults - both fatal hardware faults like AccessViolations and unhandled hardware faults like NullReferenceException

File: src/coreclr/vm/excep.cpp (hunk 3 above)
Comment (jkotas) [reply src/coreclr/vm/excep.cpp:6544]: If it is always null, it may be worth it to add assert.

File: src/coreclr/vm/excep.cpp (hunk 2 above)
Comment (AntonLapounov) [reply src/coreclr/vm/excep.cpp:6543]: Here I just restored the code that was deleted by #70428 and that is known to work.  If we are seeing the exception we just raised, I think we actually need to overwrite just one field, `ExceptionAddress`.  All other fields should have the values we passed to `RaiseException`.

File: src/coreclr/vm/excep.cpp (hunk 3 above)
Comment (AntonLapounov) [reply src/coreclr/vm/excep.cpp:6544]: It seems to be used for [chaining](https://docs.microsoft.com/en-us/cpp/dotnet/differences-in-exception-handling-behavior-under-clr) in case a native exception filter throws another exception:

> When an exception is raised during the processing of an [exception filter](https://docs.microsoft.com/en-us/cpp/cpp/writing-an-exception-filter?view=msvc-170) within managed code, the exception is caught and treated as if the filter returns 0.

> This is in contrast to the behavior in native code where a nested exception is raised, the ExceptionRecord field in the EXCEPTION_RECORD structure (as returned by [GetExceptionInformation](https://docs.microsoft.com/en-us/windows/win32/Debug/getexceptioninformation)) is set, and the ExceptionFlags field sets the 0x10 bit.

Again, I just restored the old code here.  I think it should always be `NULL` unless we have a bug in CLR.

**Comment by AntonLapounov** [comment]
Thank you for the code review.  I am going to merge this as is for today's RC1 snap and follow up on additional testing.
