### PR TITLE
Fix ilasm, ildasm, crossgen and others launch from PATH

### LINKED ISSUE #12690: ildasm has to run by full path
Hi
   I successfully built coreclr and added bin/Product/OSX.x64.Debug to $PATH in mac. But when i execute ildasm, i got segmentation fault. If i execute by full path, it works. Why?

If i get into the powershell in mac by command "pwsh", then execute ildasm, it works again, so wried.

```
/Users/peter/workspace/hostclr>which ildasm
/Users/peter/workspace/coreclr/bin/Product/OSX.x64.Debug/ildasm
/Users/peter/workspace/hostclr>ildasm
Segmentation fault: 11
/Users/peter/workspace/hostclr>/Users/peter/workspace/coreclr/bin/Product/OSX.x64.Debug/ildasm
Usage: ildasm [options] <file_name> [options]

Options for output redirection:
  /OUT=<file name>    Direct output to file rather than to console.
[Undefined resource string ID:0xCC]  /HTML               Output in HTML format (valid with /OUT option only).
  /RTF                Output in rich text format (valid with /OUT option only).
Options for file/console output:
  /BYTES              Show actual bytes (in hex) as instruction comments.
  /RAWEH              Show exception handling clauses in raw form.
  /TOKENS             Show metadata tokens of classes and members.
  /SOURCE             Show original source lines as comments.
  /PRETTY             This option is obsolete and no longer supported.
  /LINENUM            Include references to original source lines.
  /VISIBILITY=<vis>[+<vis>...]    Only disassemble the items with specified
          visibility. (<vis> = PUB | PRI | FAM | ASM | FAA | FOA | PSC)
  /PUBONLY            Only disassemble the public items (same as /VIS=PUB).
  /QUOTEALLNAMES      Include all names into single quotes.
  /NOCA               Suppress output of custom attributes.
  /CAVERBAL           Output CA blobs in verbal form (default - in binary form).
[Undefined resource string ID:0xDC]The following options are valid for file/console output only:
Options for EXE and DLL files:
  /UTF8               Use UTF-8 encoding for output (default - ANSI).
  /UNICODE            Use UNICODE encoding for output.
  /NOIL               Suppress IL assembler code output.
  /FORWARD            Use forward class declaration.
  /TYPELIST           Output full list of types (to preserve type ordering in round-trip).
  /PROJECT            Display .NET projection view if input is a .winmd file.
  /HEADERS            Include file headers information in the output.
  /ITEM=<class>[::<method>[(<sig>)]  Disassemble the specified item only

  /STATS              Include statistics on the image.
  /CLASSLIST          Include list of classes defined in the module.
  /ALL                Combination of /HEADER,/BYTES,/STATS,/CLASSLIST,/TOKENS

  /METADATA[=<specifier>] Show MetaData, where <specifier> is:
          MDHEADER    Show MetaData header information and sizes.
          HEX         Show more things in hex as well as words.
          CSV         Show the record counts and heap sizes.
          UNREX       Show unresolved externals.
          SCHEMA      Show the MetaData header and schema information.
          RAW         Show the raw MetaData tables.
          HEAPS       Show the raw heaps.
          VALIDATE    Validate the consistency of the metadata.

Option key is '-' or '/', options are recognized by first 3 characters

Example:  ildasm /tok /byt myfile.exe /out=myfile.il
```

Thanks

### PR DESCRIPTION
**Pull request by janvorli**
When trying to launch ilasm, ildasm, crossgen or any tool using 
PAL_Initialize that are on the current PATH just by their file names, 
they were crashing with SIGSEGV. 
The problem was that the current exe path was extracted incorrectly 
in that case.

This change fixes the problem using the same methods that corerun
uses to figure out the current exe path.

Close #12690

### CODE REVIEW

File: src/coreclr/src/pal/src/init/pal.cpp [hunk 1]
```diff
@@ -1289,22 +1426,27 @@ static LPWSTR INIT_ConvertEXEPath(LPCSTR exe_path)
     INT return_size;
     struct stat theStats;
 
-    if (!strchr(exe_path, '/'))
+    if (strchr(exe_path, '/'))
```
Comment (jkotas) [inline src/coreclr/src/pal/src/init/pal.cpp:1429]: Why do we even want to look at `exe_path`? Should we rather always use the other method?

Comment (janvorli) [reply src/coreclr/src/pal/src/init/pal.cpp:1429]: I just wanted to preserve the old behavior for the case when an absolute path was specified. But we obviously don't have to do that.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/src/pal/src/init/pal.cpp [hunk 2]
```diff
@@ -1265,6 +1269,139 @@ static LPWSTR INIT_FormatCommandLine (int argc, const char * const *argv)
     return retval;
 }
 
+#if defined(__linux__)
+#define symlinkEntrypointExecutable "/proc/self/exe"
+#elif !defined(__APPLE__)
+#define symlinkEntrypointExecutable "/proc/curproc/exe"
+#endif
+
+bool GetAbsolutePath(const char* path, PathCharString& absolutePath)
```
Comment (am11) [inline src/coreclr/src/pal/src/init/pal.cpp:1278]: We now have this (very similar) logic replicated in three places in the repo. Other two are:

1. https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/coreclr/src/hosts/unixcoreruncommon/coreruncommon.cpp#L53-L67
2. https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/installer/corehost/cli/hostmisc/pal.unix.cpp#L729-L812

it would be nice to de-duplicate some of it. 🙂

Comment (am11) [reply src/coreclr/src/pal/src/init/pal.cpp:1278]: (other two support FreeBSD and SunOS)

Comment (janvorli) [reply src/coreclr/src/pal/src/init/pal.cpp:1278]: @am11 yeah, I am not happy with that. I was trying to figure out a reasonable way to do that, but everything I could come up with was messy. corerun needs this stuff before the coreclr with PAL is loaded, so it cannot call it from the PAL. All the other apps like ildasm, ilasm etc. are built on top of the PAL, so they cannot include platform headers. And I didn't want to modify all these by adding a call to the exe extraction path. I was also thinking that maybe I can relax the coreclr_initialize requirement and not require it to pass in the absolute path to the exe and have it just in the PAL. But then I've realized that corerun needs that path for other purposes.
So I've decided to make it the way I did, since the window for 5.0 changes without having to go through extra process closes this week.
I can see a possible semi-unification in a future though - I'd like to see the corehost native hosts to be built in the coreclr, so at least the corerun and the dotnet host could reasonably share that code.

Comment (jkotas) [reply src/coreclr/src/pal/src/init/pal.cpp:1278]: > unification in a future 

I think we need to adopt mini-pals like what is under https://github.com/dotnet/runtime/tree/master/src/libraries/Native/Unix/Common more broadly.

Comment (am11) [reply src/coreclr/src/pal/src/init/pal.cpp:1278]: Would it make sense (in the future) to extract some functions in a common code file and include in the individual executable projects?

File: src/coreclr/src/pal/src/init/pal.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/src/pal/src/init/pal.cpp:1436]: Less code is always better...

**Review by jkotas — APPROVED** [review]

File: src/coreclr/src/pal/src/init/pal.cpp [hunk 3]
```diff
@@ -1265,45 +1276,161 @@ static LPWSTR INIT_FormatCommandLine (int argc, const char * const *argv)
...
-Notes :
-    this function assumes that "exe_name" is in Unix style (no \)
 --*/
-static LPWSTR INIT_ConvertEXEPath(LPCSTR exe_path)
+static LPWSTR INIT_GetCurrentEXEPath()
 {
     PathCharString real_path;
     LPWSTR return_value;
     INT return_size;
     struct stat theStats;
```
Comment (jkotas) [inline src/coreclr/src/pal/src/init/pal.cpp:1429]:
```suggestion
```

File: src/coreclr/src/pal/src/init/pal.cpp [hunk 4]
```diff
@@ -1265,45 +1276,160 @@ static LPWSTR INIT_FormatCommandLine (int argc, const char * const *argv)
...
+    else if (*path != '/')
+    {
+        char *cwd;
+        if ((cwd = getcwd(NULL, PATH_MAX)) == NULL)
+        {
+            result = false;
+        }
+        else
+        {
+            entrypointExecutable.Set(cwd, strlen(swd));
```
Comment (am11) [inline src/coreclr/src/pal/src/init/pal.cpp:1379]: nit: typo `cwd`
maybe we can use `.assign(cwd)` here:
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/coreclr/src/hosts/unixcoreruncommon/coreruncommon.cpp#L133-L134

Comment (am11) [reply src/coreclr/src/pal/src/init/pal.cpp:1379]: Ah, i see. it is a `PathCharString` not `std::string`.

Comment (janvorli) [reply src/coreclr/src/pal/src/init/pal.cpp:1379]: Oops, thanks for spotting. We cannot use assign here, we are not using a std::string here.

**Comment by AndyAyersMS** [comment]
Do you think this might also fix #38703?

**Comment by janvorli** [comment]
@AndyAyersMS it is theoretically possible. Let me try it.

**Comment by janvorli** [comment]
@AndyAyersMS I've checked and it is a different issue. I'll comment on the issue.

File: src/coreclr/src/pal/src/init/pal.cpp [hunk 5]
```diff
@@ -91,6 +91,17 @@ int CacheLineSize;
...
 
+#if defined(__FreeBSD__)
+#include <sys/types.h>
+#include <sys/param.h>
+#endif
+#if HAVE_GETAUXVAL
+#include <sys/auxv.h>
+#endif
+#if HAVE_SYS_SYSCTL_H || defined(__FreeBSD__)
+#include <sys/sysctl.h>
```
Comment (Gnbrkm41) [inline src/coreclr/src/pal/src/init/pal.cpp:102]: This seems to be causing a warning with Ubuntu 20.04 (on WSL2, not exactly sure if it's related). I noticed this error in https://github.com/dotnet/runtime/issues/40919; not exactly sure if this is the cause for the whole build failing.
```  In file included from /home/gotos/source/repos/runtime/src/coreclr/src/pal/src/init/pal.cpp:102:
  /usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: error: "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror,-W#warnings]
  #warning "The <sys/sysctl.h> header is deprecated and will be removed."
   ^
```

**Comment by Gnbrkm41** [comment]
I noticed I'm hitting a warning / build failure that I hadn't noticed ~3 days ago. (See https://github.com/dotnet/runtime/issues/40919) Could this be related? this PR seems to introduce problematic part (or at least, is involved with it).
