### PR TITLE
Fix AV in host from tracing on exit

### LINKED ISSUE #75760: Win32 Access Violation in EnterCriticalSection when application exits that has multiple mixed mode managed .dlls in .NET runtime inside trace.cpp trace::flush
### Description

The software uses multiple mixed/mode C++ dlls.

The "Access Violation" always happens when the software is shut down i.e. the MainWindow (WPF) is closed.

```
Exception thrown at 0x00007FFC529FD7D1 (ntdll.dll) in XYZ.exe: 0xC0000005: Access violation writing location 0x0000000000000024.
Unhandled exception at 0x00007FFC529FD7D1 (ntdll.dll) in XYZ.exe: 0xC0000005: Access violation writing location 0x0000000000000024.

```

Calls stack:
```

 	ntdll.dll!RtlpWaitOnCriticalSection()	Unknown	Symbols loaded.
 	ntdll.dll!RtlpEnterCriticalSectionContended()	Unknown	Symbols loaded.
 	ntdll.dll!RtlEnterCriticalSection()	Unknown	Symbols loaded.
 	[Inline Frame] XYZ.exe!pal::mutex_t::lock() Line 850	C++	Symbols loaded.
 	[Inline Frame] XYZ.exe!std::lock_guard<pal::mutex_t>::{ctor}(pal::mutex_t &) Line 438	C++	Symbols loaded.
>	[Inline Frame] XYZ.exe!trace::flush() Line 187	C++	Symbols loaded.
 	XYZ.exe!wmain(const int argc, const wchar_t * * argv) Line 304	C++	Symbols loaded.
 	[Inline Frame] XYZ.exe!invoke_main() Line 90	C++	Symbols loaded.
 	XYZ.exe!__scrt_common_main_seh() Line 288	C++	Symbols loaded.
 	kernel32.dll!BaseThreadInitThunk()	Unknown	Symbols loaded.
 	ntdll.dll!RtlUserThreadStart()	Unknown	Symbols loaded.

```
We downloaded and installed the NET runtime source code and debug symbols and the _access violation_ is inside the "runtime\src\native\corehost\hostmisc\trace.cpp" 

this is called from "runtime\src\native\corehost\corehost.cpp" after the call exe_start returns i.e. after the execution of the whole software finished where for whatever reason it calls these two lines:

```
// Flush traces before exit - just to be sure
    trace::flush();
```

And the crash is on the lock_guard here:

```

void trace::flush()
{
    std::lock_guard<pal::mutex_t> lock(g_trace_mutex);

    pal::file_flush(g_trace_file);
    pal::err_flush();
    pal::out_flush();
}
```

Looking at the code, it doesnt make any sense that it is executed anyways on most systems because trace::setup checks the environment variable "COREHOST_TRACE"  and does nothing if it is not set. 

Can somone simply add a early return at the beginning of trace::flush when g_trace_verbosity is 0 anyways i.e. the trace is not even used?

### Reproduction Steps

I cannot provide a sample to reproduce right now (only in our whole software). It only happens in .NET6 with Release, not in Debug. It also does not happen with .NET48 . 

We can see that trace::enable does nothing when g_trace_verbosity == 0 but very strangely trace::flush does something which is probably wrong.

While debugging we noticed that trace::setup() is called for each managed/mixed mode .dll that is loaded on startup, but that might not be related.

But I provided in the Description a fix that should probably avoid this issue without any breaking changes.

### Expected behavior

trace::flush should not do anything if g_trace_verbosity==0

### Actual behavior

trace::flush tries to lock a mutex in shutdown situations where the mutex might positionally have an issue and was even never used before because trace::enabled bailed out early

### Regression?

For us it is a regression from .net48

### Known Workarounds

None. Our software crashes on exit all the time with NET6 Release.

### Configuration

NET6 x64 Release

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elinor-fung**
Fix https://github.com/dotnet/runtime/issues/75760

For tracing, we had a static for the mutex which has a destructor. If a thread calls exit, the static destructor was called on that thread with no synchronization with other threads, resulting in potential issues where they would try to use the destructed object.

This change switches to using a spin lock. In the majority of cases (running an application, tracing not enabled, no errors) we won't use it at all. When we do (tracing explicitly enabled, errors, commands for printing info), we don't expect much contention, since most hosting is on a single thread.

Related:
- https://github.com/dotnet/runtime/issues/36580

### CODE REVIEW

File: src/native/corehost/hostmisc/trace.cpp [hunk 1]
```diff
@@ -13,9 +13,21 @@
...
+static pal::mutex_t* g_trace_mutex;
 thread_local static trace::error_writer_fn g_error_writer = nullptr;
 
+namespace
+{
+    pal::mutex_t& get_mutex()
+    {
+        static pal::mutex_t* mutex = new pal::mutex_t();
+        if (g_trace_mutex == nullptr)
+            g_trace_mutex = mutex;
```
Comment (vitek-karas) [inline src/native/corehost/hostmisc/trace.cpp:25]: For normal hosting operations this is probably OK - the only scenario where this might be problematic is a tool using hosting APIs to probe for things (would never actually start the runtime - basically just using either nethost, or hostfxr which are both cleanly unloadable). If such tool does this repeatedly and it causes errors, each such call would leak a mutex.

Is there really no way to clean up?

One possible idea (but I'm no C++ expert): custom class with a destructor which wraps the mutex. In the destructor it tries to enter the mutex (with a timeout) - if that succeeds, it knows it's the only one there and can delete it and cleanup the wrapper. If it fails - let it leak (should basically never happen). Would probably need some double check when entering the mutex (enter the mutex, check that the wrapper hasn't been destroyed, and only then continue).

I'm just a bit nervous intentionally leaking stuff - especially in the nethost and hostfxr which are meant to be unloadable.

Comment (AaronRobinsonMSFT) [reply src/native/corehost/hostmisc/trace.cpp:25]: Another option would be to use a simple spin-lock and remove the `mutex` logic entirely. Unsure how long these ops are supposed to take, but it might be an okay compromise.

One could also simply create a "private" one and leave the public a pointer as done above. This way cleanup would still happen.

```cpp
static pal::mutex_t g_trace_mutex_private;
static pal::mutex_t* g_trace_mutex;
...
    pal::mutex_t& get_mutex()
    {
        if (g_trace_mutex == nullptr)
            g_trace_mutex = &g_trace_mutex_private;

        return *g_trace_mutex;
    }
```

Comment (AaronRobinsonMSFT) [reply src/native/corehost/hostmisc/trace.cpp:25]: Oops. The second option isn't tenable I see. Avoiding destruction entirely is the point. Hmmm spin-lock seems appropriate to me then.

Comment (elinor-fung) [reply src/native/corehost/hostmisc/trace.cpp:25]: Yeah, I (obviously) had a hard time figuring out how to clean up for the library case. I think any sort of destructor would land us in the same place - the object gets destructed and then some other thread calls into it, resulting in undefined behaviour / badness.

I guess rolling our own spin lock might be it... These are tracing operations, so how long it takes kind of depends on I/O as we write to a file/stdout/stderr.

Comment (AaronRobinsonMSFT) [reply src/native/corehost/hostmisc/trace.cpp:25]: The spin lock is likely something that can be inefficient if this is only for tracing since it is by definition for investigating a bug or issue so speed shouldn't be the priority, I think?

Comment (elinor-fung) [reply src/native/corehost/hostmisc/trace.cpp:25]: Yeah. I don't think speed is the priority. The non-error, non-investigation scenario for tracing would be commands for printing information - for example, `--info`, `--list-runtimes`, `--list-sdks`.

Comment (mgexo) [reply src/native/corehost/hostmisc/trace.cpp]: Here is my new suggestion that does not leak any memory but still does not crash. I am not a dotnet runtime developer, so please adjust the code-style as required:

Keep '''static pal::mutex_t g_trace_mutex;''' as is.

At the top of the original trace.cpp, add this:
```

static bool g_trace_mutex_shutdown = false;


class MutexAccessGuardForCRTShutdownSituations {
public:
    MutexAccessGuardForCRTShutdownSituations() {
        g_trace_mutex_shutdown = false;
    }
    ~MutexAccessGuardForCRTShutdownSituations() {
        g_trace_mutex_shutdown = true;
    }
} g_MutexAccessGuardForCRTShutdownSituations;


```

And then add this check for g_trace_mutex_shutdown before using the mutex i.e. 
```
void trace::flush()
{
    if (g_trace_mutex_shutdown) {
        return;
    }
    
    std::lock_guard<pal::mutex_t> lock(g_trace_mutex);
```

This strange class MutexAccessGuardForCRTShutdownSituations will be destroyed when the CRT shuts down and then it will not access the mutex any more and simply do nothing, as it would be wrong to do anything anyways in that situation

Comment (vitek-karas) [reply src/native/corehost/hostmisc/trace.cpp]: How do you guard against race conditions - what if a thread gets past the boolean check and then another thread initiates the shutdown. By the time the first thread gets to the lock the mutex might be destroyed.

The spin-lock solution is not perfect, but it's highly unlikely to cause problems:
* Tracing is almost always off - so it will never actually run
* Vast majority of the hosting code runs on a single thread, so the contention on the lock should be basically non-existent

**Review by vitek-karas — APPROVED** [review]

File: src/native/corehost/hostmisc/trace.cpp [hunk 2]
```diff
@@ -13,9 +13,34 @@
...
+    class spin_lock
+    {
+    public:
+        spin_lock() = default;
+        spin_lock(const spin_lock&) = delete;
+        spin_lock& operator=(const spin_lock&) = delete;
+
+        void lock()
+        {
+            while (flag.test_and_set(std::memory_order_acquire)) { /*spin*/ }
```
Comment (AaronRobinsonMSFT) [inline src/native/corehost/hostmisc/trace.cpp:29]: You might want to yield at some point. Perhaps spin 1024 times or something and then yield? This is also optional if there is low concern about this code path.

```suggestion
            uint32_t spin = 0;
            while (flag.test_and_set(std::memory_order_acquire))
            { 
                if (spin++ % 1024 == 0)
                    std::this_thread::yield();
            }
```

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/native/corehost/hostmisc/trace.cpp (hunk 1 above)
Comment (elinor-fung) [reply src/native/corehost/hostmisc/trace.cpp]: I'm going to stick with the spin lock. As @vitek-karas said, while it is not ideal, this is a path where we don't expect it to cause issues.

**Comment by mgexo** [comment]
On a side, note, I really do not understand why you didnt check for g_trace_file  != nullptr in trace::flush()  before you even lock. 
Thats what I also wrote in https://github.com/dotnet/runtime/issues/75760 because in most (probably 99% of all environments), the trace feature is not even used and there is simply a useless lock at the end

**Comment by elinor-fung** [comment]
Avoiding the lock at the end when it is not needed is definitely reasonable - and an improvement I will look at. However, the underlying root cause for the issue is the static object with a destructor, so that is what I wish to fix here.
