### PR TITLE
Fix arm64 apple hfa<float>.

### LINKED ISSUE #45780: Support HFA(float) stack passing.
According to C++ tests (build natively on the target machine), HFA(float) requires a 4-byte alignment that contradicts with a standard 8-byte alignment for all structs on arm64. 

So when passing `Vector3 a, Vector3 b` on the stack they take 24 bytes, when on default arm64 it would take 32.
However, for a struct `Vector3int {int x; int y; int z; }` I see normal 8-byte alignment, so 2 of them are taking 32 bytes on the stack.

This behavior is not explicitly described in Apple docs ([Writing ARM64 Code for Apple Platforms](https://developer.apple.com/documentation/xcode/writing_arm64_code_for_apple_platforms)), so it would be nice to get a confirmation that it is expected.

The issue requires 3 things:

- [ ] Distinguish HFA(float) from `struct` when create argInfo and putArgs;

- [ ] Fix code in morph args (`fgInitArgInfo`) and codegen (`genPutArgStk`) that uses the assumption that SIMD12 arguments can be always propagated as SIMD16.

- [x] If we have to support non-rounded putArgs for arm64 apple it could be beneficial for other platforms to use as well, because now we create temporary copies

### PR DESCRIPTION
**Pull request by sandreenko**
Apple Arm64 does not require struct alignment for HFA<float>, instead, it uses 4-byte stack alignment for this type. Add Jit support for this. Closes https://github.com/dotnet/runtime/issues/45780.

The changes:

0296b35c8f5: A small fix in dump printing.

ac6fada9b3c: Keep the aligned size in `fgArgInfo`.

There were no users that required the exact size, but keeping it required roundings all over the place.
So now both `fgArgInfo` and `GenTreePutArg` keep the align size (with padding after the arg value), but the alignment is different on different platforms.

ee4076f1076: Fix float HFA stack passing.

Apple doesn't require struct alignment for it. 
The main change is introducing `eeGetArgAlignment` that returns alignment for an argument type. I am planning to extend this method soon (see https://github.com/dotnet/runtime/issues/46026).
The second change is fix for `LclVarDsc::lvSize()` so it returns `12` for such variables.

Also, I am trying to use less `#if defined(OSX_ARM64_ABI)` to make https://github.com/dotnet/runtime/issues/45501 easier.

2d87c52d2a0: Fix `lvaMapSimd12ToSimd16` for arm64 apple arguments.

Now when `lvSize` returns `12` for `SIMD12` arguments on arm64 apple we need to fix some asserts that do not expect it.

<details>
  <summary>Fixes 46 tests (including pri1 tests):</summary>

```
JIT/Methodical/explicit/rotate/_dbgrotarg_double/_dbgrotarg_double.sh
JIT/Methodical/explicit/rotate/_opt_dbgrotarg_float/_opt_dbgrotarg_float.sh
JIT/Methodical/explicit/rotate/_opt_dbgrotarg_double/_opt_dbgrotarg_double.sh
JIT/Methodical/explicit/rotate/_il_relrotarg_objref/_il_relrotarg_objref.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_r/hfa_nd2G_r.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_d/hfa_sd2G_d.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_r/hfa_sd2G_r.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_d/hfa_nd2G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf2G_d/hfa_nf2G_d.sh
JIT/jit64/hfa/main/testA/hfa_sf1A_d/hfa_sf1A_d.sh
JIT/jit64/hfa/main/testA/hfa_nf1A_r/hfa_nf1A_r.sh
JIT/jit64/hfa/main/testA/hfa_sf0A_d/hfa_sf0A_d.sh
JIT/jit64/hfa/main/testA/hfa_nf0A_r/hfa_nf0A_r.sh
JIT/jit64/hfa/main/testA/hfa_nf2A_d/hfa_nf2A_d.sh
JIT/jit64/hfa/main/testA/hfa_sf2A_r/hfa_sf2A_r.sh
JIT/jit64/hfa/main/testA/hfa_sd2A_r/hfa_sd2A_r.sh
JIT/jit64/hfa/main/testA/hfa_nd2A_d/hfa_nd2A_d.sh
JIT/jit64/hfa/main/testA/hfa_nf1A_d/hfa_nf1A_d.sh
JIT/jit64/hfa/main/testA/hfa_sf1A_r/hfa_sf1A_r.sh
JIT/jit64/hfa/main/testA/hfa_nf0A_d/hfa_nf0A_d.sh
JIT/jit64/hfa/main/testA/hfa_sf0A_r/hfa_sf0A_r.sh
JIT/jit64/hfa/main/testA/hfa_sf2A_d/hfa_sf2A_d.sh
JIT/jit64/hfa/main/testA/hfa_nf2A_r/hfa_nf2A_r.sh
JIT/jit64/hfa/main/testA/hfa_nd2A_r/hfa_nd2A_r.sh
JIT/jit64/hfa/main/testA/hfa_sd2A_d/hfa_sd2A_d.sh
JIT/jit64/hfa/main/testC/hfa_sf1C_r/hfa_sf1C_r.sh
JIT/jit64/hfa/main/testC/hfa_nf1C_d/hfa_nf1C_d.sh
JIT/jit64/hfa/main/testC/hfa_sf0C_r/hfa_sf0C_r.sh
JIT/jit64/hfa/main/testC/hfa_nf0C_d/hfa_nf0C_d.sh
JIT/jit64/hfa/main/testC/hfa_nf1C_r/hfa_nf1C_r.sh
JIT/jit64/hfa/main/testC/hfa_sf1C_d/hfa_sf1C_d.sh
JIT/jit64/hfa/main/testC/hfa_nf0C_r/hfa_nf0C_r.sh
JIT/jit64/hfa/main/testC/hfa_sf0C_d/hfa_sf0C_d.sh
JIT/jit64/hfa/main/testC/hfa_nf2C_d/hfa_nf2C_d.sh
JIT/jit64/hfa/main/testB/hfa_nf2B_d/hfa_nf2B_d.sh
JIT/jit64/hfa/main/testB/hfa_sf2B_r/hfa_sf2B_r.sh
JIT/jit64/hfa/main/testB/hfa_sd2B_r/hfa_sd2B_r.sh
JIT/jit64/hfa/main/testB/hfa_nd2B_d/hfa_nd2B_d.sh
JIT/jit64/hfa/main/testB/hfa_sf0B_d/hfa_sf0B_d.sh
JIT/jit64/hfa/main/testB/hfa_nf0B_r/hfa_nf0B_r.sh
JIT/jit64/hfa/main/testB/hfa_sf2B_d/hfa_sf2B_d.sh
JIT/jit64/hfa/main/testB/hfa_nf2B_r/hfa_nf2B_r.sh
JIT/jit64/hfa/main/testB/hfa_nd2B_r/hfa_nd2B_r.sh
JIT/jit64/hfa/main/testB/hfa_sd2B_d/hfa_sd2B_d.sh
JIT/jit64/hfa/main/testB/hfa_nf0B_d/hfa_nf0B_d.sh
JIT/jit64/hfa/main/testB/hfa_sf0B_r/hfa_sf0B_r.sh

```

</details>

Note: it does not fully fix 
```
JIT/HardwareIntrinsics/General/Vector128/Vector128_r/Vector128_r.sh
JIT/HardwareIntrinsics/General/Vector128/Vector128_ro/Vector128_ro.sh
JIT/HardwareIntrinsics/General/Vector256/Vector256_r/Vector256_r.sh
JIT/HardwareIntrinsics/General/Vector256/Vector256_ro/Vector256_ro.sh
```
because they are using reflection and additional VM fixes are needed.

### CODE REVIEW

**Comment by sandreenko** [comment]
There are several ci failures that repro only on the first run in a clean setup and do not repro on rerun, so I think they are not introduced by my change but I do not see them failing in other runs, so I am investigating them.

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib , cc @sdmaclea @mangod9

**Comment by sandreenko** [comment]
ping @dotnet/jit-contrib

**Review by sdmaclea — APPROVED** [review]
LGTM.  Looked through each commit.  Each looked reasonable and logical.

File: src/coreclr/jit/lclvars.cpp [hunk 1]
```diff
@@ -3656,6 +3651,46 @@ void LclVarDsc::lvaDisqualifyVar()
...
+    // where the struct itself is no longer used because all access is via its member fields.
+    // When that happens, the struct is marked as unused and its type has been changed to
+    // TYP_INT (to keep the GC tracking code from looking at it).
+    // See Compiler::raAssignVars() for details. For example:
+    //      N002 (  4,  3) [00EA067C] -------------               return    struct $346
+    //      N001 (  3,  2) [00EA0628] -------------                  lclVar    struct(U) V03 loc2
+    //                                                                        float  V03.f1 (offs=0x00) -> V12 tmp7
+    //                                                                        f8 (last use) (last use) $345
+    // Here, the "struct(U)" shows that the "V03 loc2" variable is unused. Not shown is that V03
+    // is now TYP_INT in the local variable table. It's not really unused, because it's in the tree.
```
Comment (AndyAyersMS) [inline src/coreclr/jit/lclvars.cpp:3666]: Realize this is a pre-existing comment, but `raAssignVars` is long gone....

**Review by AndyAyersMS — APPROVED** [review]

File: src/coreclr/jit/lclvars.cpp (hunk 1 above)
Comment (sandreenko) [reply src/coreclr/jit/lclvars.cpp:3666]: Thank you, I will fix the comment in the next pr.
