### PR TITLE
Fix stack overflow handling with SuperPMI

### LINKED ISSUE #84911: Test failure baseservices\\exceptions\\stackoverflow\\stackoverflowtester\\stackoverflowtester.cmd
Run: [runtime-coreclr jitstress-isas-x86 20230415.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=240798&view=ms.vss-test-web.build-test-results-tab&runId=4623708&resultId=121656&paneView=debug)

Failed test:
```
coreclr windows x86 Checked jitstress_isas_nohwintrinsic @ Windows.10.Amd64.Open

- baseservices\\exceptions\\stackoverflow\\stackoverflowtester\\stackoverflowtester.cmd
```
**Error message:**
```
cmdLine:C:\h\w\B25509AE\w\A1800911\e\baseservices\exceptions\stackoverflow\stackoverflowtester\stackoverflowtester.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 4/15/2023 9:38:05 PM, end: 4/15/2023 10:08:05 PM)

Return code:      -100
Raw output file:      C:\h\w\B25509AE\w\A1800911\uploads\Reports\baseservices.exceptions\stackoverflow\stackoverflowtester\stackoverflowtester.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B25509AE\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  stackoverflowtester.dll
Running stackoverflow test(smallframe main)
"Stack overflow."
"Repeat 43042 times:"
"--------------------------------"
"   at TestStackOverflow.Program.InfiniteRecursionB()"
"   at TestStackOverflow.Program.InfiniteRecursionA()"
"   at TestStackOverflow.Program.InfiniteRecursionC()"
"--------------------------------"
"   at TestStackOverflow.Program.InfiniteRecursionB()"
"   at TestStackOverflow.Program.InfiniteRecursionA()"
"   at TestStackOverflow.Program.Test(Boolean)"
"   at TestStackOverflow.Program.Main(System.String[])"

cmdLine:C:\h\w\B25509AE\w\A1800911\e\baseservices\exceptions\stackoverflow\stackoverflowtester\stackoverflowtester.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 4/15/2023 9:38:05 PM, end: 4/15/2023 10:08:05 PM)
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\B25509AE\t\tmpofmm5c.tmp" -z "C:\cores\crashdump_3180.dmp"
stdout:
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\cores\crashdump_3180.dmp]
User Mini Dump File with Full Memory: Only application data is available

************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\B25509AE\p\PDB
Symbol search path is: C:\h\w\B25509AE\p\PDB
Executable search path is:
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Sat Apr 15 22:08:05.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:47:51.988
Process Uptime: 0 days 0:29:54.000
ERROR: Reload failure, partially initialized target
WaitForEvent failed, HRESULT 0x8000FFFF
Catastrophic failure
When WaitForEvent fails on dump files the current state is not displayed.
If you are having symbol problems you will need to restart the debugger
after you correct the symbol path.  .restart can also be used.
?:???> cdb: Reading initial command '$<C:\h\w\B25509AE\t\tmpofmm5c.tmp'
?:???> .load C:\Users\runner.dotnet\sos\sos.dll
WARNING: The debugger does not have a current process or thread
WARNING: Many commands will not work
?:???> ~*k
WARNING: The debugger does not have a current process or thread
WARNING: Many commands will not work
^ Illegal thread error in '~*k'
?:???> !clrstack -f -all
WARNING: The debugger does not have a current process or thread
WARNING: Many commands will not work
Extension called without current PC
SOS does not support the current target architecture '' (0x0000). A 32 bit target may require a 32 bit debugger or vice versa. In general, try to use the same bitness for the debugger and target process.
?:???> q
WARNING: The debugger does not have a current process or thread
WARNING: Many commands will not work
quit:
NatVis script unloaded from 'C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\Visualizers\atlmfc.natvis'
NatVis script unloaded from 'C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\Visualizers\concurrency.natvis'
NatVis script unloaded from 'C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\Visualizers\cpp_rest.natvis'
NatVis script unloaded fr


Stack trace
   at baseservices_exceptions._stackoverflow_stackoverflowtester_stackoverflowtester_._stackoverflow_stackoverflowtester_stackoverflowtester_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["stackoverflowtester","Timed Out"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Provided build not found. Provide a valid build in the "**Build:** :mag_right:" line.
**Validation performed at:** 7/28/2024 3:43:37 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[776063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776063)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776063&view=ms.vss-test-web.build-test-results-tab&runId=19863820&resultId=111477)|dotnet/runtime#106413|
|[776041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776041)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776041&view=ms.vss-test-web.build-test-results-tab&runId=19863102&resultId=111477)|dotnet/runtime#106414|
|[775936](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775936)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775936&view=ms.vss-test-web.build-test-results-tab&runId=19859838&resultId=111476)|dotnet/runtime#106139|
|[775734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775734)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775734&view=ms.vss-test-web.build-test-results-tab&runId=19852834&resultId=111474)|dotnet/runtime#100272|
|[775644](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775644)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775644&view=ms.vss-test-web.build-test-results-tab&runId=19847966&resultId=111474)|dotnet/runtime#105288|
|[774985](https://dev.azure.com/dnceng-public/public/_build/results?buildId=774985)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=774985&view=ms.vss-test-web.build-test-results-tab&runId=19824432&resultId=111472)|dotnet/runtime#106164|
|[774360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=774360)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=774360&view=ms.vss-test-web.build-test-results-tab&runId=19808848&resultId=111472)|dotnet/runtime#105030|
|[774234](https://dev.azure.com/dnceng-public/public/_build/results?buildId=774234)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=774234&view=ms.vss-test-web.build-test-results-tab&runId=19804000&resultId=111471)|dotnet/runtime#106328|
|[773688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773688)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773688&view=ms.vss-test-web.build-test-results-tab&runId=19781884&resultId=111471)|dotnet/runtime#106309|
|[773437](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773437)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773437&view=ms.vss-test-web.build-test-results-tab&runId=19776212&resultId=111469)|dotnet/runtime#106000|
|[773189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773189)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773189&view=ms.vss-test-web.build-test-results-tab&runId=19768558&resultId=111468)|dotnet/runtime#106289|
|[773146](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773146)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773146&view=ms.vss-test-web.build-test-results-tab&runId=19767860&resultId=111468)|dotnet/runtime#106287|
|[772522](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772522)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772522&view=ms.vss-test-web.build-test-results-tab&runId=19746400&resultId=111468)|dotnet/runtime#106253|
|[772131](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772131)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772131&view=ms.vss-test-web.build-test-results-tab&runId=19731184&resultId=111468)||
|[771959](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771959)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771959&view=ms.vss-test-web.build-test-results-tab&runId=19724458&resultId=111467)|dotnet/runtime#106224|
|[771572](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771572)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771572&view=ms.vss-test-web.build-test-results-tab&runId=19713578&resultId=111464)|dotnet/runtime#106210|
|[771470](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771470)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771470&view=ms.vss-test-web.build-test-results-tab&runId=19711240&resultId=111464)|dotnet/runtime#106208|
|[771327](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771327)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771327&view=ms.vss-test-web.build-test-results-tab&runId=19706410&resultId=111465)|dotnet/runtime#106130|
|[770591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770591)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770591&view=ms.vss-test-web.build-test-results-tab&runId=19687334&resultId=111463)|dotnet/runtime#105867|
|[770680](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770680)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770680&view=ms.vss-test-web.build-test-results-tab&runId=19686798&resultId=111463)|dotnet/runtime#106179|
|[770472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770472)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770472&view=ms.vss-test-web.build-test-results-tab&runId=19680706&resultId=111463)|dotnet/runtime#106169|
|[769920](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769920)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769920&view=ms.vss-test-web.build-test-results-tab&runId=19664222&resultId=111462)|dotnet/runtime#106146|
|[769596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769596)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769596&view=ms.vss-test-web.build-test-results-tab&runId=19655312&resultId=111460)|dotnet/runtime#106125|
|[769233](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769233)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769233&view=ms.vss-test-web.build-test-results-tab&runId=19636468&resultId=111459)|dotnet/runtime#106103|
|[769148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769148)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769148&view=ms.vss-test-web.build-test-results-tab&runId=19636360&resultId=111459)|dotnet/runtime#106099|
|[767713](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767713)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767713&view=ms.vss-test-web.build-test-results-tab&runId=19582272&resultId=111456)|dotnet/runtime#104503|
|[767505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767505)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767505&view=ms.vss-test-web.build-test-results-tab&runId=19574978&resultId=111453)|dotnet/runtime#106023|
|[766166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766166)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766166&view=ms.vss-test-web.build-test-results-tab&runId=19524140&resultId=111449)|dotnet/runtime#105945|
|[765937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765937)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765937&view=ms.vss-test-web.build-test-results-tab&runId=19521290&resultId=111427)|dotnet/runtime#105866|
|[765436](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765436)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765436&view=ms.vss-test-web.build-test-results-tab&runId=19491434&resultId=111427)|dotnet/runtime#105909|
|[765422](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765422)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765422&view=ms.vss-test-web.build-test-results-tab&runId=19490924&resultId=111427)|dotnet/runtime#105918|
|[764816](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764816)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764816&view=ms.vss-test-web.build-test-results-tab&runId=19457840&resultId=111427)|dotnet/runtime#105877|
|[764679](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764679)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764679&view=ms.vss-test-web.build-test-results-tab&runId=19452126&resultId=111426)|dotnet/runtime#105902|
|[764671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764671)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764671&view=ms.vss-test-web.build-test-results-tab&runId=19451790&resultId=111426)|dotnet/runtime#105901|
|[764565](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764565)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764565&view=ms.vss-test-web.build-test-results-tab&runId=19448072&resultId=111425)|dotnet/runtime#105830|
|[764396](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764396)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764396&view=ms.vss-test-web.build-test-results-tab&runId=19443298&resultId=111425)|dotnet/runtime#104964|
|[764272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764272)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764272&view=ms.vss-test-web.build-test-results-tab&runId=19440896&resultId=111426)|dotnet/runtime#105869|
|[763784](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763784)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763784&view=ms.vss-test-web.build-test-results-tab&runId=19420416&resultId=111424)|dotnet/runtime#105854|
|[763492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763492)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763492&view=ms.vss-test-web.build-test-results-tab&runId=19411760&resultId=111424)|dotnet/runtime#105844|
|[762756](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762756)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762756&view=ms.vss-test-web.build-test-results-tab&runId=19392274&resultId=111421)|dotnet/runtime#105802|
|[760956](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760956)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760956&view=ms.vss-test-web.build-test-results-tab&runId=19326944&resultId=111419)|dotnet/runtime#105353|
|[760835](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760835)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760835&view=ms.vss-test-web.build-test-results-tab&runId=19324602&resultId=111418)||
|[760458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760458)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760458&view=ms.vss-test-web.build-test-results-tab&runId=19311480&resultId=111417)|dotnet/runtime#105703|
|[758039](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758039)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758039&view=ms.vss-test-web.build-test-results-tab&runId=19233094&resultId=111412)|dotnet/runtime#105587|
|[757926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757926)|dotnet/runtime|[baseservices/exceptions/stackoverflow/stackoverflowtester/stackoverflowtester.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757926&view=ms.vss-test-web.build-test-results-tab&runId=19230198&resultId=111412)|dotnet/runtime#104536|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|18|45|

### PR DESCRIPTION
**Pull request by janvorli**
When SuperPMI shared library is loaded last, its SIGSEGV handler is the first one that's executed. But since there is no coreclr runtime handler installed for it, it returns from the SwitchStackAndExecuteHandler in case of SIGSEGV. The remaining code in the SIGSEGV handler was not expecting that and thought that there was no stack overflow and attempted to run the hardware exception handler on the original stack of the thread, which obviously crashed since the original stack overflowed.
The fix is to make sure that we only call the previously registered signal handler in this case.

Close #84911

### CODE REVIEW

File: src/coreclr/pal/src/exception/signal.cpp [hunk 1]
```diff
@@ -649,26 +653,29 @@ static void sigsegv_handler(int code, siginfo_t *siginfo, void *context)
             }
         }
 
-        // Now that we know the SIGSEGV didn't happen due to a stack overflow, execute the common
-        // hardware signal handler on the original stack.
-
-        if (GetCurrentPalThread() && IsRunningOnAlternateStack(context))
+        if (!isStackOverflow)
```
Comment (jkotas) [inline src/coreclr/pal/src/exception/signal.cpp:656]:
```suggestion
        else
```
?

**Review by jkotas — APPROVED** [review]
