### PR TITLE
Fix for m_alignpad == 0 assertion failure

### LINKED ISSUE #70231: Assert failure: m_alignpad == 0 in libraries tests
Hit in https://github.com/dotnet/runtime/pull/70226

Dump and logs: https://dev.azure.com/dnceng/public/_build/results?buildId=1806089&view=ms.vss-test-web.build-test-results-tab&runId=48090090&resultId=197319&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Stacktrace:
```
coreclr!DbgAssertDialog+0x1af [D:\a\_work\1\s\src\coreclr\utilcode\debug.cpp @ 594] 
coreclr!ObjHeader::IllegalAlignPad+0x33 [D:\a\_work\1\s\src\coreclr\vm\syncblk.cpp @ 2952] 
coreclr!ObjHeader::GetBits+0x41 [D:\a\_work\1\s\src\coreclr\vm\syncblk.h @ 1545] 
coreclr!ObjHeader::Validate+0x50 [D:\a\_work\1\s\src\coreclr\vm\syncblk.cpp @ 2042] 
coreclr!Object::ValidateInner+0x493 [D:\a\_work\1\s\src\coreclr\vm\object.cpp @ 581] 
coreclr!Object::Validate+0xa1 [D:\a\_work\1\s\src\coreclr\vm\object.cpp @ 498] 
coreclr!OBJECTREF::operator->+0x21 [D:\a\_work\1\s\src\coreclr\vm\object.cpp @ 1242] 
coreclr!MarshalNative::GCHandleInternalAlloc+0x171 [D:\a\_work\1\s\src\coreclr\vm\marshalnative.cpp @ 492] 
System_Private_CoreLib!System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib]].Pin()+0xffffffff`a4114a41
```

### PR DESCRIPTION
**Pull request by mrsharm**
Fixes https://github.com/dotnet/runtime/issues/70231 by:

1. Removing the demotion check
2. Adding a null check on the GCSafeMethodTable

Also, we are now logging the ``m_alignpad`` value instead of the object address in the ``IllegalAlignPad`` function.

### CODE REVIEW

**Comment by Maoni0** [comment]
does the `LogSpewAlways` actually log something in the stress log the way these tests are run? when I looked at the dumps this message was not there.

File: src/coreclr/vm/syncblk.cpp [hunk 1]
```diff
@@ -2950,8 +2950,8 @@ void ObjHeader::IllegalAlignPad()
     WRAPPER_NO_CONTRACT;
 #ifdef LOGGING
     void** object = ((void**) this) + 1;
-    LogSpewAlways("\n\n******** Illegal ObjHeader m_alignpad not 0, object" FMT_ADDR "\n\n",
-                  DBG_ADDR(object));
+    LogSpewAlways("\n\n******** Illegal ObjHeader m_alignpad not 0, m_alignpad value: %d\n\n",
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/syncblk.cpp:2953]: I'd argue we want both in this case. The object to know which one and the padding to know what is wrong.

Comment (Maoni0) [reply src/coreclr/vm/syncblk.cpp:2953]: the object is easy to get from the dump.

Comment (Maoni0) [reply src/coreclr/vm/syncblk.cpp:2953]: but I'm ok to log both.

Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/syncblk.cpp:2953]: @Maoni0 If this will always assert somewhere else so the object is easy to find, then I'm fine with that. It just wasn't obvious from this change here that that would be the case.

**Review by Maoni0 — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]
