### PR TITLE
Change RSA.LegalKeySizes for Apple platforms to return 8192

### LINKED ISSUE #110588: macOS: RSA.Create and Import fails with > 8192-bit keys
In macOS, this will fail:

```C#
RSA rsa = RSA.Create(16_384);
rsa.ExportParameters(true);
```

Likewise, importing a 16K key does not work.

<details>
<summary>See big test</summary>

```C#
using System.Security.Cryptography;

void Main()
{
 	RSA rsa = RSA.Create();
	rsa.ImportPkcs8PrivateKey(Convert.FromBase64String("""
MIIkQgIBADANBgkqhkiG9w0BAQEFAASCJCwwgiQoAgEAAoIIAQCVjuXvwP6pEIuU
sJFhAQRjDg0m0Kyb/ZcRwxqsWExpdClzzfNHxQNQGe8Ur+MNB9IJKNiYOipxh14G
eo794f64TR0/yEeplViPzo/zngsHPcm/5f/+2FYucRqRcMWwL23pqljge6/0wLs1
jI9fCKQyhI327IMbfWczMPEnEB4LjUnBLBvhY11eWk6CHy1GepIEaUCkvAFRUN4U
BaEa+oFRj438bL/f1NZKcwxqNk6rEsi1aHT1FKEVzpLquk0dsL+NwGR7lIahO09w
L8+7trTAJrNRzgItKceP+JHQrJqfFtwaTTQs9WRuVKbxuek0JSVdNijlGY09tQSV
p2lmTp0BSOSWTve+QLpkTJ9cF3tUQD/x8uDIRBYs6lfaoR3bJidA89U4hDQ1N7ca
v96frypORYE1dnv0WWXWmJrWJ/fAAbf5+cY0nBa7Sk0js0bo9LBvyRClqGn3pKi5
1MfB5rAr8SKnNuxoQz1cMSggpj3O2SeBh5exoUxae7sI91G8IKY1OFJofTlBFvkB
C/973QA4vYfK1gH+XHf8Re8wkq7a/FfJqduWpXn2M6vpjfalNTWU4rnXfel4xtY/
2ppfbtHwMiYmvKVR9pW/Z+MUqZer8TeSrftMZGfpb1f67wHZDZH5GWCI7dzpAgNM
vITGEW8u+nfgJgGyPQPwZU2OqugteNgaTd6TMYUC2mieel6dKFoMIOw6d1Bqsz20
iuBYXLUz2QnXK9ycVH0ZMEFzkpDo5sJdjId2HE5N39QPEBFAT/E+rNXu3BVJfiE9
Er8T1PaSfgzrJpSKvyHuMjctGNHLA4VtRaZeKnkdfDAb98AqddVavLyDP5V6jg8N
eySqh4fm0upMQZRVTDyiWeASLUEWpDpKAL08d2o3duzqZ8S1wbjNlyBliLMIzkqM
ZPbSzOzykdtum+kOXzVzJrSr1cA4Ab9aNr2y2ZrgaHj3//GZvvEBm3IdHy5EHWSv
nKkIXFRs9oPIR7CHy6zZc8YMQ8i+7zbJvsI1ZVFfU67CETz415KGWrpnQajotTeU
WcRn03Ha9aSjzst82p+oK0kge7aHUIGLN5ZLobmJcrqpuA8nGc/5i7W6avic/jAN
zOdABe5RiZxGNHVe0qgGlzV/wmo/gEvqkpdJvMLtiPDlcc1ffQjqTRjOuFuVk/5X
srwF34Rhe7iNv3FO0ic/vlYYbGjuNZEOXh7kRRK0TVjzhUdMNLvNiRNaf04hg5mN
5rR1pXK9nlxkWUMbvUyLe5wQPzl83Pp2Pa/ZAxm6cxYGRV/SOCX9tEFxwchc3smC
1hSksexkzS91hl+3gRoikAuXDas2gHJr/14+j15blNntC7WwsRJG/WSunWXWQELf
LiH2kKVAD2cF+oKSYjmwORhYbQG32YgrGtuVu4n4GgoHsZwY5x4vQjkB21DvbCVJ
mQ1NiY9X9cyVq46wWGNeYwO6q1G8R6OdE0tuOasmGvCo23HaZ+VL5G7q+hGAtbDj
J1F1B7JBztwjOHd/AxT2sISbPe9v+ifDpU81KCiFpeVDGD7TWpBz18JWtxWFFeoA
DXDEsXrCxs3SWQRN4lMEIkCOCCL6Q+Uh4dyKZnH6k8kXYaUlc3G7putoo6o6Xksj
Z8SgLgz0e0JThFKuaSqm/ePTg1TH4h4lNJdhJqQ75N7/soTJv5cTePLuxtGCwZ9H
qFA13YYt7qAdqofuDO2SAxCs0BfaNB8KHtc79hLze/4owUrDSX5ba7Tzv9TrvVh9
PlmAmvvlW54HqRlwUGBotZpQdfdydSTlh0IfUwTVHjEMh05guOfgkJjDr4jTVjlj
n6PlBuNRXPD55IWRDRztn9iFhpQUecThUL6k3ovXlmLbjUUqrBRnVWamFMKkLQTs
AlPrU62Yu/nVWSirPVkxYmagSU+KX8u5akNpy88PZDCxSM1uIFKFURo3pcGXngAB
jpkbgMsZevt/sVsJkh8wub3n9C5qnh/dhkBrPPcDumMp+8eE5BTO2QcIy2XXZ3UX
XgmvHgQtfDgHEb2hSqtV6+OrBc4qlondTb01rykKEQZED4tlYeY1k/CRQY1qne8Z
ARoB9c/hFsx4t/ZzF1IL16u9c9EjPjxMCW47+Q9ma6Wczs5+RRYb+oIr6tcigWCL
G7T/XNyPT4uJ8xtw6NEyiVll4HYd2BQ138ktQE242Jl4reQllPeZJBvFEc8xesOC
jiS2WoUth3EPR72vjqVtY9Ulf7kenyr8ulFOcFNBIWGpoX3omw/Hy3JG1/y8leCq
lh7y3Pi2UZ7VRFHCeawEDE+f5IEUz6bgyffpMWwU0kpyXK4LFi8YM4KVOmBgoDpT
ct+Ezqes21wwnWE7DLT4IaRsRsLqQjnTMFYFfxnRguHln9z966+fLmIezNY6CmsZ
0r7vyQZ0X0T+Ihb74/s+ab5lZhX0T1QSZtBgdKRCi+ZJqVxA6GKsNgOM+wbHF+Q6
nb6gBrJNiCIBO1ao3ipn6AvPLVtQXxx0g+nkoGsW4TUe2dsWXMZ1P2hPR9ulbKx3
xIo6YfRBKw5mVhOjeqTVqx7ga6KPLz4yaUPotQ5p2I1Wo961BclV/58FFGybmzut
7BZ9vA/g0eRiPMTKP2mbfekFlWsGcnMHh1YQhB2DKH7WgshfzqaHXjYLyzcS1uQm
bNUEaHrCHFo67iBMsd7WwMJtfGuKdiiyMadNvIqvAq7uxXw/KtKDJmkfwgbsSFEQ
5Z6q10JN91ddY6YH8oc/iJyopbH6WwIDAQABAoIH/2qO/6vTcAUFXm4sLJwkHWJ2
OhvUK/SSU92HJXoMostMxW9W55kH+VRMWT8w32IC/T0jEGL/dNfVNMKcKavtv/WQ
lazcOWY0NbJAremysVwREHrc/rvINNJ7w6V2TcptmkjiSaQOfIMZm+Lx3M6mJldx
tBsHm/v6KlpO6xzp+H5CkxcPiZqmyxLVRRqkTzeBtu46djrpUtPQZARGZOmgxbYj
xWzhqKEFatxtgtFdeeLQTDD0omBiuMmdmKmlrUxHCQEprNTGl/KvHFDSjMmYlzBR
L3KzVUALt74Pw26EWUAz1jiAyXjYkek9moHTje5mIp96XajeJV3SAj8FCOCovAHH
7eMqYI0tkTnlXgw/e5++9DcI1exA/SVp0shZnOwhdjzRF+cssTk5rG/JEgi0XwnM
FXbO9LWK/J3pts7fRNmJLL9VN30RUyDraT4GfhkWpJ9nb6gx8BtO0Bv95YkO1Hbg
8c/LuKT3Q42feJFkR3JM4D9p9kSZdQCcwXM7kJp52/J1yEF3Xbo11zSBV+1PItlK
l3Xt0eQ2ZHom83h1Cob8d5AEqT0TEDknyu6darhLMRVKDx96lt6qAGN+kOVuECat
Lhs4TcVLhWZ0nooaS5A2tC6a+tg/5PzT8dulPBI3MpcV5Bh4lO1vtOorATu3/Rl7
wlPyWg/Xz8N4ajBvlP2d6SgH7PQmVDiA/tZR834GDu9iH1RVro/xJZ99U45uf3mk
w8SLe9cZ9TswWdhk+6db9lN9zQZaV9a+CfMX5f+GKSmx+4g0eil8gWVowrvFALaS
sqGlqDBmZJNSZzDtsVlawoMYtqP60lCWK0qO1MKfMjF0SA+iCt7gvwwPF6po5muP
22ATWZyf6C1eQkhKwuIruo9l9263QCneK7wLABzmtsVegbai4oaW21OTAq/8Hz2C
SG+52YbKT0rvfDFY55vM1iNw3VHEH8iRDZ+liUs1JujLC7aA50LUFOkKtcs/MOgL
iQzDoQOGgTrUdXquBFoGFpza5x5XeG+mY0PinfUVPOp9U+w+D04lAw5JtA0SmnMB
Xxm91z5RU3AYNAIkIxxGQAaKx75Or3zYqCaq/bp33OnwOr4xeVf7w9reI396U+yR
UscY/7qP9sGILi+l70Do9S4s3Z4SeZ0rKBHsNs44rofbmdFJiZEJepUBkPXRfucp
P4iMEcjj8xMRVxNC94Bbdv7FqnAtLSZ9KOOMeNnTHy9Se0Rl1nhw5PdpAsRpg72W
sQpoKJubEVUdI65vxB+ZUtrsS/fspAHN/eNGvcvXAm3BNBMMZU9f02b+uunQqDcp
+qaOsNdBi117RGBbwzsR40F15ON63IzKTntjdhDU5cp7jUDcfhj2Fq9TyN8Xydf2
7aR6kxQ61mGTKkJGYPOahRKkTnNErthCbnMcSDTS+PJE+/7TCK16bh4JkVJ6ScIq
eknfbuD4wJDJSJeEVtWe3e9feogUIrHm6vHo4CqB29fMvFWuBgsQNQcZE5RvuQgL
pHiyUmfrcjz0XjYFbfM8NXq/skOe+D6lfi9ViOqzS09fVS7yTQQEdjWKMXi9vZ7Z
tsxiud8RqCU1nTtwWr3u+kMwOec91vS4xevWhHjZi2VjfnHpTYsIl8VzurM8ooi5
jcEGIQ42PPMaiy33axPwKsQSz6xtxJZ6SK3efVp6/mIuYulTxinafN7p4h/UIK7B
ha8uPcCgqQ6W6edoXduCx1Slethu7emjQHFXN7oPUtetZE289xnMH19l91H8a/8x
bEZlZH1aozGxE1c9/ZJ899F9Qw5/B6lZAe6/IawlfunofCtlqQlga2580XZVrojT
QF5svtdemFsNr6bFWkCv4LLFstjbxjNuSsbX+rAQHGqZ+gywlPWLB+qVLfv116e8
pj3aK7hJ9XT9ogRHuFPEMC3gNjfEekAj7B5goUgEG30b/3Ywdk+Iyl+kB308Web8
RCssbiWJW0qQPBi69h3cBoMVJghdgDZ70UzWxASeOU2N/uJnida/x4WxLUX/e6md
E5gEjP+Pg//zdDougw1fpUC9XxPbuoCtuLcOKo/oeAefs3CJhIFsl+3GQXrYwhlT
Xr/VHHnDlN1MKrGJPnx6S4GAR7lH1tnEU9EXxNRJMGDe8J0cf+0fG4BY3ZmhsjoP
DIIbYYjwCLfPOzoRilfYO1vjk9CChlw6LFFIhtw3uUo0oKKfDew1h2dZGXeoB9Mo
jBDcN02+G1fdn2E6OgQGLmXO3GUuxmTAkTWItb1i84JzI80Z5+qGY4IwMfw8H/R3
By0fM6IMXMEUX60HIh0EHbEBw7Hm+V4p/oj+wTMAgK+u5SdG1FRXqSe/bPqTMdE4
BNqFdND3Qx8JD79gNdw9AQJfIsCUvHfWIKM3bs5n423u/5CQt1kL2diJkf3dx6G5
lzJ4spz5QAaIWxS5CsR1Z827ztEm793AkpzTVq8rYoAxpWsriNUWDkqonpmctD8f
aTUYrvIJHBsWuw7wwkgjz7F9wUFjtNzSQ0z0P7RKCmEe0HoWhXgu92k79X9e060H
9BC1OM/YJjU40uH0+62VKBYVInNjxs+yG/CBqxmOWSCT2LVS0103rtzpZEeJCznb
5iz3ODo3WVCb33eYTgOEpZnQMcajqT7Z6WdL/Q8xkRDebP0YGFuXjQeDefglL/+B
e8DAoL70V480h6l5d/i2crnjFFvdtH/5szOWzoI5JNIOuyShPzqY4v+Pt0Go6+eV
iF5WiEt6MxhwWgDiCgECggQBAMqqbuCHOkKjWp2xqh2sxAcYfk19uVJuw0z+8X2S
99Qr7zXKIl+gGX5MLNcB7L+V3re0D23TZgN1RLl6Umw+6S0DrXauyho64nB+h5gG
Oael6nETPx7UNbgT2ahGpdEhAMGOL0wDNMKeIZxiO/0V6mPnrHGn+4p5p5fvTpGG
CiRd2HSYPab8coPE6LVd+wroG9ZZy9c51TgJb00AsJeK/EZpct6WgSbwmieSBcZM
DfF4ZLt3/twDwDCb/NAoWsxFh7gPlMWoUip2igY3/CvtZVZF0YcKOJRbbJh6gpuj
h+vRUD/CSwKRlJ/kQbuVbSbkWtJZPRjDibWF1LJ50FTarxkAHmLdVfWhcOc1B76m
PYUyaVy3dM0EkfpU93004rgRIbTr36dn0p7bU0++HGzrgwCDMexXm2j6KnaEbKBK
C1JaI6g1wQbAvnr2W8IM0KGs1cwvoCvSPkvRRwDSaz+vguyPTQWEL3N1k/JVb2f5
FkksonHgEHRi19Gq/wA6AxrG/wxSJVuJRBShLeee8GJQokZrE1A2bJWONXvi4aKU
6FolFkTfLEsHGaTSB652+YjX6j9i6rVMKwN4aRkakhcTgjU3bvW+sKlhpeIwL4YE
TaUsuKBONOocC69jHJxA0887iGhjYH5HDMD7jfX/ORBAJDvG8hEc5J4Q9hPUkqb+
YgEKRcCHO3Xq2kqEoqFoanqKsEWolMG29+Zd3H3TUUu4C9zpmY9Nyl0byRbN97Xr
2H7G9MHMpWuyVt0OI+BD4JJGHjNmhnO8vl9ifYPJH8UOEzDCRk4DvWI/9FupKE3t
cXg/GdWr+8lDFvqMEFEWVKvCg1D90g2LjyLJpcqQaXf3oUB4smTJ+lYSZtREUtLd
/EVeZ8ssqCPDDrsesM8ADC/25zshnnH1bq5miD6HBfC0WCSs3mhW/fKnjoz0lQdp
YRwbLm3zqtuFoWDZJulHR+GORXvlXbZbH6d6VqfCCw6bmo+FCvtq7YNfCog/wwOY
/zWN84jLNnZEMM2ZmkQ3W0yA2Yneed6e5Klw2fkAR0rorH4O6lFePlA6gV4KanK8
vp610MLk/cpxvTFHc1pwK62tM3R0q9AUg6dRoHwR/v5fTVL1+M1kE2/0sYFXdFL6
hEJEYoazmrVa4oTeRxwQ7XsX2Ioai3fZOAByiVIvoKKpKE50KOzUE+bt3oi2YbPe
d22ecb2cPE3ErB2C4QtQP56SDSA773HMLcb9bL0Sw0cLnlsP5ECbm5z/X72nIAoU
wmaqPxRgstCmEmPyB2J8uLJeNXTJUItFfamFF5I0oOEdFMEHBet4DUhzNH2qHlZ5
aUsTI+kmwgjDmHSxQj3qGiXqvxzDqN02e2ljHjEROMDiLmsCggQBALzqnYw0Guyd
5d7YUVdrXxMtmlRpzUnC6EAGKV9cDY58Hb5+yCw2Bp0iqZNUIviOebplXDSUD2Ct
EMQia500k7jMWWFdViXM7tdXHdtASykx+hH8C0X28eLgRxpnnM8gCTyjrvTidkN6
imktpgFar1IY6YG45B4ybKDa9rvjGblFHmGzbFHx087yzuu4Gt2StLTBbjoJjJob
hrR20vq3vQZMQC7wSx4ukrjyPInj4oBEOPp7gaHUJ73GKVYQ1E6Acra5Xw6MfpLI
YLLEtPDzZJKEz/jPwlb/hfikjJgL5GVADwxR6chXGeHwdnvztpdmuJttjr2pQf/O
60el41QfUpN9vWIjCF6DjQNuoU05ev3FEKdc9hB4t5GT2GRRFPicwNK9AhXPQAOW
R3ZS5P4yFzRvTnjWqU5pUovJtHU+IaRaSPjzLp07HzDMAGq2lrUCvInB65RUWnQN
KMxwV2PMrQE8ngxa/i4lDtyfqE5XZ2o0keyEjEUaHZXATG15rDyDNckNVOaWdav6
De+03p7xtAxNozRzCHgVmQpOkgkZkBhwX93LFcIiNh5e8oiM5c6hTnrMS6pgGqyK
q6tolaHLrx4Kt60Nox5X7HZ45VP8ZiVNz8ur3E0LsyzRCYipv0XcxTj4AjuuatZw
Zebwi7vQyMLDuUrobseKqMA/dM8sbWEYp9YI9yU9K6K3KPH2AblAfrv9nBlAK+2B
VonNNP6kSbxL+77rE1kyTrntAEv+RAN6AqV0kIevsKorWoYnpoO3M7MOUreqbZkx
/1i47LQndr6nQ5w/HceuyrsRO83vw+jQNL0mL2PuJaPLE9CPe5G161nboE4CvRxn
urmY4ZL5kco1oM4l657JTp0rba69AzeHsj7MkORbDu8aEat3W/eE6TUcCJODsFr/
Tf2aoPe3fHVSR4rQNvDqmgG9TejKkQ4lMV7Y+CobTMLDAHSRmq36iZmEwd0Lhydd
UMcZ+42LwHjKnCu7ezAYvlDQoLlcGnJZew34vAnTR+L+17altvYbFMqz0aZsdpEw
ScxHFLuQzZImeQLnQVs27ABUn38c1Bnb6qMxoSHFUOOufmaE1AXJOuGhpG0YivEn
vQmt0TTa25xM5I0xHr21exb87v6G8ejmv7BLKlLJPfyG5kVtm1EShOX2zrY/Bg0O
20PWZoyH8v8ObnvYoGuP+zXYl3Ec3P+t3MiA+shu1Huw0+cnYL5w+Ap2/w2BCrxi
vElGbtes3jwS+IZ0S998naVJ4bAC1ZJVviIgNth74FOipxcb1BoaGkcrx887g0ST
+RSangEEkhWqUfqq+hLhEfxRMo3gc939WIAiXX9zzm5oy8fTatUFpJmuuBM01hDe
Rg9WmxLJf9ECggQAXIyIJbCbQmMmtmyzqumCe1sMEocfYi2Csl6aGSZMVm/ZxU6R
c+nAupQ+xdDzNGpUUr+/a//lzh53S9w4V4ZDJXNQe6pGUMQjNAwUD7CIE68I6KpJ
YOK3xWALPXVFs8LGfZ1Yq/Wq2lUsNCYIDwM7DnR1o1F65Tm49wEpd/smFoVkm5oK
TX9rLBF305sfUVO9op1PIPIgFH76fMeb3RhzLBRriIpiYE3vl7JvQKbqlyLLnXCm
ygJMeeZCBSzoifAWkk9LORgsrYeEcGKQnd7DMCqiDHD2dYlqhhcsHbcIEwB7DSLE
7l9c58ds3STXu7L8ZqKp6+0fre13vCk0ogtbeqc7ORqqbolS7cKhzsZLwc/LnbOJ
ezZjE1ZJzruf7T6ljeFJOUGIRVMTMI84m+TQ5iMDYVKAfegADC9dC7XEhc70CZTC
mTrbwXtPW8ZOYAZ1e9Ej698O48CmFBIDOAoGV9D481Px91/yN/Ab9/cf3jqr1CTm
Xr/knrLf0FKtqETHo/C/bpW4qVMRi3xhegQols+++hpga8uNUQ3CzGQD12aoTLs9
luWfKE1hhKKAQaWYK2oYlMI7wlHybKxdmnwmMfcmjMKQGkmlXy1yBllgu9U4Wrxc
HazBCU7ReemA0Fn3aPQ41HHNuTMnGPd8L5ea9FFdqcLwA97rARNKBUiVqLPwNoOK
+8ZL+UuomNz+Awfih2z8wZm0i1bBohQmQ9XAVRm4LmDv0KUnp2pXfJQ/QWXJz9aM
lCnU0Q3sBDX7D9FFaWOgcqn2pchsWQo3n91VliahxG6gxYU/KbyN00hjUO4/9fub
98TTcYcUzHLOJ8GkBhBjJBxfORuswlxATbCfyrlTfgNedn/gxX6N9A27blI2Q+oY
vnwM9haF14HGDwFJhw9LM+9IpAvem+89Hza8KcNnrW5MectapbPren79AcDH6x4j
ICxeDcQcqNsMUEyQHowXx3bFdc3AVMugEQOuCWxQH5As9pkoTiAQBkyP/vzcAdQL
AucRAlLqx8wfvUf6D6OxM6CL+3S1lagy5lpqqwZUquPGwQx2l2NaSRs4UXHl65p2
60QVibN/UgV3bNBzdvLwow07MeVszDvLno4W2ZPKEsFovu+XP+GYFWyhiUGBXNIY
DEl8uABpqL9yM4woLqkAl7JyiIHFg+qMCLwG1Aznw371t7dYsEXZSDKHh1+bwWLf
hwQRNUjXTDtRUjCQHfBA4E7FeOGyDoXK916u6hbPvVFSNtfH+OuhDfl87TVBqSSf
g/jS3SFhjfA2x/2Nm89zIKaTRB6rLPErpqGJILz8TxN7vWIezmQphoPbOZV8CLTS
Vv47WM652VxWpIoWzCPtsVd39CB3YSDkMfEYEQKCBAEAnFB46fCXMp/3+yr8Kxxh
v8mlACHHRjgq2gb/JrNRWEtkhSH8WXCeiliK/afJg+bH3C5QXAUCsFijHdbpOlut
u2QCtOh5BrAKFE42GxuY1U5P/5+QaGTLgpFW5AdFnbCBVBaQBnp3pp/3dM3bpRU3
KfQJClhFEKNidLqZG5/uwfjqCadfgnJZcsw/4JUmTZ49Pa8rmIQcPct2603ChseP
dW2UUgJr9V5N8xAkfWf9G2rXxpJ5EcEs3P7hZyBnu0jXIlBB0hT4ClYYhPL0UMbj
ucSBHPwzbq7hWHo3BvwYEJsvmF8S1L0VYnkIYMmolJ/fMmQ1jsNFI/g/f7pIXmvI
dNe+4zvfiezJukRI3VApb18mx4TI6ZopMiCmFWNtucRiXD0eQ5OIAS/Qk5xFc/tY
bf+Ha78auhG1xoqwca5mQcqexLbbJCguR78UvTe1fbL08/tsBQDDE3FsB7UQ6jgK
EpLop4qG9QGeyXil16TEogE7mPuX4PmZ7zX9Rzw9ApkC4QfR7zYhyZoO+/+pkNSn
yOJYn2ZrZIliZz/Z4AOx0jbxa+DFcSvDod+oSMpkwFOCT2NJXIFGsOvQ3fSckxKp
JG9zyZIWHV5c/y5LevHGRymaPYlHsMx0him0/MqPxKvG2LuFhYJtTmAUQUFaLZ60
70rpv4yRVTRrKx+WdHHrU0MGZLhoXvy9ZVauX37RsEooUz6mcdJCRrQVOdJ8/hJM
HKy2ciOqj8xrjbYH39lUx5emJudLS6pYwIU80vJt+mCVO5wnX2d6Zh8TjIL/AJYC
0AAwllE3P+lmP+EjneO9M59LdBLrdYEwzdWT4KdIdKmVQnXSr5nehmlh/H3+cBFm
y20SUGDaFDm3fZ7Yk5Q73C/AkevMG9cohTkJ09ngU+8608INapm1S6YiDyxp8m51
YdIh9j8QpslHgxbzJyKtYYnuzu8ycAzEuAaIEuwDk99RCaDqlA8c1rqEwynBlj5D
lO74x8rKRGLE3rOxuY33KBTYGBhu5qZWvgFl1fBKclq4Gn0thMoMVVgiSA+snQJU
xpBk4r0cu++22RMsIg5lhbwM6tl+3SWaJ7pTRlqz4NG/kcCg/9Al7yKVbTPQfi51
Nl/9YMJ7EDfg0IWa7yoTckWz6JhZPcTcMF4inOHzeOKc6ncMVYnSZO2dCgWWNsOq
kdaMHpeBLV8mWkiMDoD2b+yZWaI3X68sy+flfkd76jgpVOdfZPoYOwZriynnPzf/
bq+3yfDictp2yrRWNMAznXCq8Su8leXyGOHl5d4V4z8j7S3Rl6xDknPpzl2dTXRN
t/WE/aeJYiOvMRqyfOhylwUwvF0zBel5rquxqfdKV1bi+nKyRtoaIjz4tWpQx/vI
cQKCBAEAwcDwxb3V+WnHj91kAiYYefhycc05uBxKQft1igtdKr7HTiHku/cSME8b
EVdX4FV5NBC8BgqPCvifbXc9BSMKsHtEOt5mpRaktyefuvsOpqHY7IUfBoxHqcDm
tuu77T1IUt762drtm6U2WpvGs9obQ5XGRkZkTei08BkWNPrzEOv0hpDqTxsDVLXw
bOlFi7PRE+rV5523kaU3K+TZzXVEmUM8CInCDRUPOpeCRwLlFdNw4cTvjnjF+gjC
Z4jGVpuhLFP0CzmstLwa4N2ezVl95ath2ek4GCw92ZpksbPDzP6Q+MJYlj1Zhjd8
MicooJKmmn0Ecea5b5qjGgi1cpBwi0y59yRr64Aks0lBw6SSip7fyL+zlxh0GgzF
km8eGyi2Ri2BxDUTJJzZ982fvIuiM7Vj9H3GyKIIVqE7wjfmS/4tvcQgFfXKNVcP
5RZXMXfhxZNqad2SJ1OINF6TuTcpkf9lM9q/CZsZEJ3L3AvtlC8b8V4c3EE32MCf
dYEQOtdZHPPRW3sTv4jlpT1AKM+z0wGALTTc4T9RBEKVrpe//nB8j3HBUJb/0pNv
Wykw9KbpqygCanon70NzcMOqKShtPGtOQkpEgLaTj4KA5/UqCwfPBsZaLU9GU22y
75CEetO74aWDB8aCW0GxsT43BcOuN1A/E/5DtAmSuxIs6aXyF/UyXsW0foVbreOm
lWTTDxCp9ky7IfahcME6n1IRonQAXM1bQwhd0f36kpd7JRJNZGsQ17FOPiLxgpF/
PNzrt/e6BMYxRurmzI7aUReq9ZYdfeebexgdIZA04RInYZfDtlDhp8TSl1a03Zhy
r2iI1Wdt0e2NkFonf/uIVICNZrXqfq6WtYpv2DbJdaJSRNR1fNsCQHBtUoGi9iWf
ORDvpKDMXOvp4X/ULc1KflRjPiR4TBjPU23v9cTBvBg3Hk8/ye/8xVLLTup3YdXd
pz3ZZ8NFJPw4Bnc4hhNeqC/OmnvfVIVbePKmBIVuzh+Add1j7WKKtA8sbrAewxiE
SxsuLF0529htLf3FBIWrt1jaJLVSQF3b0TIIHIgK7fYxqDlBVGcFBfMNPLfLlJ0u
EGpnD8nMhX9sUBXo0PpFbx98UnGOGbjEJ1TCyHrK/cvkxD4jZzkdfUQewzFquUCb
o8eti4tiT7iSZfPdkc/cZfcj5n3340pnAi2UwBA6QfBUNf8Qy+wdu1Nc4Xe71Xie
nhCm16J1vleTRaiW1t9yM9Z02309c45Tqn/O7/h6rfAvdMB0FCkBhyaQZzrWTpHm
KmtdaTZtHoV5cugEfvXAd7VjR8sPcA4wW+gjcOm0PagbvoOEPLjLlQjKFuaubfbh
AZx1cUmna0GUe7XKWWWUlAmUpHayTw==
"""), out _);
}
```

</details>

I don't think it really matters one way or the other if 16K keys work (they are obscenely large) however, the MaxKeySize is `16_384`

https://github.com/dotnet/runtime/blob/f377332dfd3ebe0b36631d37c1e555eece1bc9bb/src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs#L50

Since I don't see a way to get a 16K key to work with Apple platforms, we should probably just lower this to 8192, which does appear to work, as recently as macOS 15.1.1.

We have a test for 16K keys that fails, but it is guarded by "IsStressModeEnabled".

https://github.com/dotnet/runtime/blob/cc66c7769902766ccdf26af708f4484d04e3e604/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/KeyGeneration.cs#L23-L27

It fails when I do `DOTNET_TEST_STRESS=true ./dotnet.sh test src/libraries/System.Security.Cryptography/tests --filter GenerateMaxKey`, so I guess we never run with this enabled on macOS.

### PR DESCRIPTION
**Pull request by vcsjones**
This changes RSA.LegalKeySizes to return a maximum of 8192 on Apple platforms, as opposed to 16384. At least on macOS Sequoia and Sonoma, the limit is 8192-bit.

While we are here, memoize the `KeySizes` instance. They are immutable. The returned array is not - so we only memoize the interior `KeySizes` instance, not the returned array.

Closes #110588.

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
Should we add a test that keys with the max size can be created?

**Comment by vcsjones** [comment]
> Should we add a test that keys with the max size can be created?

We do here

https://github.com/dotnet/runtime/blob/cc66c7769902766ccdf26af708f4484d04e3e604/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/KeyGeneration.cs#L23-L27

But it's (effectively) a manual-only because it takes about ~30 seconds to generate an RSA 8K key. It can take several minutes for platforms that support 16K keys. Even for Outerloop that's too long, in my opinion.

This manual-only test fails without the fix, which is what prompted me to make the change.

**Comment by teo-tsirpanis** [comment]
Makes sense, thanks.

File: src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs [hunk 1]
```diff
@@ -38,19 +44,7 @@ internal RSASecurityTransforms(SafeSecKeyRefHandle publicKey, SafeSecKeyRefHandl
...
-                    return new KeySizes[]
-                    {
-                        // All values are in bits.
-                        // 1024 was achieved via experimentation.
-                        // 1024 and 1024+8 both generated successfully, 1024-8 produced errSecParam.
-                        new KeySizes(minSize: 1024, maxSize: 16384, skipSize: 8),
-                    };
-                }
-            }
+            public override KeySizes[] LegalKeySizes => [s_legalKeySize];
```
Comment (krwq) [inline src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:47]: while this looks correct, we seem to use [CloneKeySizesArray](https://github.com/dotnet/runtime/blob/f6e46ff86b784db1106e2148d84e43432f96116c/src/libraries/Common/src/System/Security/Cryptography/KeySizeHelpers.cs#L12) elsewhere - this will make potential down-porting easier

File: src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs [hunk 2]
```diff
@@ -18,6 +18,12 @@ public sealed partial class RSASecurityTransforms : RSA, IRuntimeAlgorithm
         {
             private SecKeyPair? _keys;
 
+            // All values are in bits.
+            // 1024 was achieved via experimentation.
+            // 1024 and 1024+8 both generated successfully, 1024-8 produced errSecParam.
+            // 8192 generated successfully, 8192+8 produced errSecParam.
+            private static readonly KeySizes s_legalKeySize = new KeySizes(minSize: 1024, maxSize: 8192, skipSize: 8);
```
Comment (krwq) [inline src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:25]: you're changing file under Common, are you sure you're changing just Apple?

Comment (krwq) [inline src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:25]: could this limit be higher in certain configurations like someone installed something and now they can use 16k or i.e. different limit on mobile etc? Just curious if 16k wasn't made because one of those allows it

Comment (filipnavara) [reply src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:25]: Yes, this is Apple specific. It was in Common due to a S.S.C assembly split.

File: src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs (hunk 1 above)
Comment (vcsjones) [reply src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:47]: It doesn't really make sense to use it here for me, and we don't use it in RSABCrypt.

https://github.com/dotnet/runtime/blob/95814d0f99fd876fdc2f6b5b4cf5d5fc94adaea9/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSABCrypt.cs#L355

Using `CloseKeySizesArray` would mean memoizing an array as well, so it would just mean more things unnecessarily held as a static.

It does make sense to use it for EC algorithms since they cannot have their key sizes represented as a single instance of `KeySizes`.

File: src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs (hunk 2 above)
Comment (vcsjones) [reply src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:25]: As far as I can tell there is no way to use a 16K key with SecurityTransforms. If I had to guess, .NET originally supported 16K keys on macOS in .NET Core 1.x days when crypto on macOS was build on OpenSSL and we just kind of assumed that didn't change when we ported to Apple's Security framework.

File: src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs [hunk 3]
```diff
@@ -18,6 +18,12 @@ public sealed partial class RSASecurityTransforms : RSA, IRuntimeAlgorithm
         {
             private SecKeyPair? _keys;
 
+            // All values are in bits.
+            // 1024 was achieved via experimentation.
+            // 1024 and 1024+8 both generated successfully, 1024-8 produced errSecParam.
+            // 8192 generated successfully, 8192+8 produced errSecParam.
```
Comment (bartonjs) [inline src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:24]: Did 8192-8 work?

**Review by bartonjs — APPROVED** [review]

File: src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs (hunk 3 above)
Comment (vcsjones) [reply src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:24]: Yes.

```C#
using System.Security.Cryptography;

RSA rsa = RSA.Create(8192-8);
Console.WriteLine(rsa.ExportParameters(true).Modulus.Length);
```

Prints 1023.
