### PR TITLE
x86 P/Invokes marked with UnmanagedCallersOnly require marshalling

### LINKED ISSUE #38697: Test failure: Interop\\UnmanagedCallersOnly\\UnmanagedCallersOnlyTest\\UnmanagedCallersOnlyTest.cmd
failed in job: [runtime-coreclr outerloop 20200701.4 ](https://dev.azure.com/dnceng/public/_build/results?buildId=713613&view=ms.vss-test-web.build-test-results-tab&runId=22128558&resultId=101117&paneView=debug)

Error message
~~~
Return code: 1
Raw output file: C:\h\w\A6BE0948\w\ACF5090A\e\Interop\UnmanagedCallersOnly\Reports\Interop.UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A6BE0948\p\corerun.exe" UnmanagedCallersOnlyTest.dll 
Running TestUnmanagedCallersOnlyValid...
Running TestUnmanagedCallersOnlyValid_OnNewNativeThread...
Running TestUnmanagedCallersOnlyValid_PrepareMethod...
Running TestUnmanagedCallersOnlyMultipleTimesValid...
Running NegativeTest_NonStaticMethod...
Running NegativeTest_ViaDelegate...
Running NegativeTest_NonBlittable...
Running NegativeTest_NonInstantiatedGenericArguments...
Running NegativeTest_InstantiatedGenericArguments...
Running NegativeTest_FromInstantiatedGenericClass...
Running TestUnmanagedCallersOnlyViaUnmanagedCalli...
Running TestPInvokeMarkedWithUnmanagedCallersOnly...
Test Failure: TestLibrary.AssertTestException: Assert.Fail: Expected 'System.NotSupportedException' to be thrown, however 'System.InvalidProgramException' was thrown. 
 at TestLibrary.Assert.HandleFail(String assertionName, String message) in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/Assertion.cs:line 735
 at TestLibrary.Assert.Fail(String message, Object[] args) in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/Assertion.cs:line 722
 at TestLibrary.Assert.Throws[T](Action action, String message, AssertThrowsOptions options) in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/Assertion.cs:line 191
 at Program.TestPInvokeMarkedWithUnmanagedCallersOnly() in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:line 762
 at Program.Main(String[] args) in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:line 57
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A6BE0948\p
> C:\h\w\A6BE0948\w\ACF5090A\e\Interop\UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.cmd
Expected: True
Actual: False


Stack trace
   at Interop_UnmanagedCallersOnly._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\Interop.UnmanagedCallersOnly\Interop.UnmanagedCallersOnly.XUnitWrapper.cs:line 140
~~~

### LINKED ISSUE #38737: JIT assert under debugger when running TestUnmanagedCallersOnlyNonStatic
Observed on Windows-x86-Debug under a debugger when the dynamic function in [`TestUnmanagedCallersOnlyNonStatic`](https://github.com/dotnet/runtime/blob/9df02475e09859a8d24852011cf3515f7a665670/src/coreclr/tests/src/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs#L349-L387) is being jitted. Test doesn't fail.

https://github.com/dotnet/runtime/blob/9df02475e09859a8d24852011cf3515f7a665670/src/coreclr/src/jit/importer.cpp#L17320-L17327 

Stack
```
 	clrjit.dll!debugError(const char * msg, const char * file, unsigned int line) Line 260	C++
 	clrjit.dll!Compiler::impImportBlock(BasicBlock * block) Line 17322	C++
 	clrjit.dll!Compiler::impImport() Line 18300	C++
 	clrjit.dll!Compiler::fgImport() Line 6994	C++
 	clrjit.dll!CompilerPhaseWithStatus::DoPhase() Line 125	C++
 	clrjit.dll!Phase::Run() Line 62	C++
 	clrjit.dll!DoPhase(Compiler * _compiler, Phases _phase, PhaseStatus(Compiler::*)() _action) Line 138	C++
 	clrjit.dll!Compiler::compCompile(void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags) Line 4261	C++
 	clrjit.dll!Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags) Line 6129	C++
 	clrjit.dll!`Compiler::compCompile'::`61'::__Body::Run(Compiler::compCompile::__l2::__JITParam * __JITpParam) Line 5464	C++
 	clrjit.dll!Compiler::compCompile(CORINFO_MODULE_STRUCT_ * classPtr, void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags) Line 5468	C++
 	clrjit.dll!``jitNativeCode'::`8'::__Body::Run'::`5'::__Body::Run(jitNativeCode::__l8::__Body::Run::__l4::__JITParam * __JITpParam) Line 6768	C++
 	clrjit.dll!`jitNativeCode'::`8'::__Body::Run(jitNativeCode::__l2::__JITParam * __JITpParam) Line 6771	C++
 	clrjit.dll!jitNativeCode(CORINFO_METHOD_STRUCT_ * methodHnd, CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags, void * inlineInfoPtr) Line 6795	C++
 	clrjit.dll!CILJit::compileMethod(ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, unsigned int flags, unsigned char * * entryAddress, unsigned long * nativeSizeOfCode) Line 274	C++
 	coreclr.dll!invokeCompileMethodHelper(EEJitManager * jitMgr, CEEInfo * comp, CORINFO_METHOD_INFO * info, CORJIT_FLAGS jitFlags, unsigned char * * nativeEntry, unsigned long * nativeSizeOfCode) Line 12310	C++
 	coreclr.dll!invokeCompileMethod(EEJitManager * jitMgr, CEEInfo * comp, CORINFO_METHOD_INFO * info, CORJIT_FLAGS jitFlags, unsigned char * * nativeEntry, unsigned long * nativeSizeOfCode) Line 12375	C++
 	coreclr.dll!`CallCompileMethodWithSEHWrapper'::`8'::__Body::Run(CallCompileMethodWithSEHWrapper::__l2::Param * pParam) Line 12429	C++
 	coreclr.dll!CallCompileMethodWithSEHWrapper(EEJitManager * jitMgr, CEEInfo * comp, CORINFO_METHOD_INFO * info, CORJIT_FLAGS flags, unsigned char * * nativeEntry, unsigned long * nativeSizeOfCode, NativeCodeVersion nativeCodeVersion) Line 12436	C++
 	coreclr.dll!UnsafeJitFunction(PrepareCodeConfig * config, COR_ILMETHOD_DECODER * ILHeader, CORJIT_FLAGS flags, unsigned long * pSizeOfCode) Line 12970	C++
 	coreclr.dll!MethodDesc::JitCompileCodeLocked(PrepareCodeConfig * pConfig, ListLockEntryBase<NativeCodeVersion> * pEntry, unsigned long * pSizeOfCode, CORJIT_FLAGS * pFlags) Line 1003	C++
 	coreclr.dll!MethodDesc::JitCompileCodeLockedEventWrapper(PrepareCodeConfig * pConfig, ListLockEntryBase<NativeCodeVersion> * pEntry) Line 876	C++
 	coreclr.dll!MethodDesc::JitCompileCode(PrepareCodeConfig * pConfig) Line 795	C++
 	coreclr.dll!MethodDesc::PrepareILBasedCode(PrepareCodeConfig * pConfig) Line 404	C++
 	coreclr.dll!MethodDesc::PrepareCode(PrepareCodeConfig * pConfig) Line 332	C++
 	coreclr.dll!MethodDesc::PrepareInitialCode(CallerGCMode callerGCMode) Line 322	C++
 	coreclr.dll!MethodDesc::DoPrestub(MethodTable * pDispatchingMT, CallerGCMode callerGCMode) Line 2156	C++
>	coreclr.dll!PreStubWorker(TransitionBlock * pTransitionBlock, MethodDesc * pMD) Line 1942	C++
 	coreclr.dll!_ThePreStub@0() Line 1545	Unknown
 	0a637242()	Unknown
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
On x86 the `InvalidProgramException` is thrown since all P/Invokes marked
  with `UnmanagedCallersOnly` now require marshalling. The test is expecting
  a different exception. For now the test will be updated to accept
  `InvalidProgramException` on x86.
Fix generated IL for test.

Fixes #38697 
Fixes #38737 

/cc @elinor-fung @jkoritzinsky

### CODE REVIEW

File: src/coreclr/tests/src/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs [hunk 1]
```diff
@@ -759,6 +767,15 @@ .locals init (native int V_0)
 
         IntNativeMethodInvoker testNativeMethod = (IntNativeMethodInvoker)testUnmanagedCallersOnly.CreateDelegate(typeof(IntNativeMethodInvoker));
 
-        Assert.Throws<NotSupportedException>(() => testNativeMethod());
+        if (RuntimeInformation.ProcessArchitecture == Architecture.X86)
+        {
+            // This is due to a semantic change in NDirect::MarshalingRequired().
+            // See https://github.com/dotnet/runtime/issues/38697#issuecomment-653310319.
```
Comment (jkotas) [inline src/coreclr/tests/src/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:773]: May we can add `bool bUnmanagedCallersOnly` argument for `NDirect::MarshalingRequired` and alter the exact set of checks it does in that case?

**Review by jkotas — APPROVED** [review]
