### PR TITLE
Don't use the CoercedConstantValue value as the key, when we have a reloc

### LINKED ISSUE #48895: ARM64 -  Assertion failed 'isSharedConst' in 'Test:Main():int' during 'Optimize Valnum CSEs'
Run: [runtime-coreclr r2r-extra 20210227.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1015629&view=ms.vss-test-web.build-test-results-tab&runId=31624618&resultId=100126&paneView=debug)

**Error message:**
```
Assert failure(PID 627 [0x00000273], Thread: 627 [0x0273]): Assertion failed 'isSharedConst' in 'Test:Main():int' during 'Optimize Valnum CSEs' (IL size 1828)

 File: /__w/1/s/src/coreclr/jit/optcse.cpp Line: 2866
 Image: /root/helix/work/correlation/crossgen

/root/helix/work/workitem/Loader/classloader/generics/Instantiation/Positive/NestedStruct01/NestedStruct01.sh: line 188: 627 Aborted (core dumped) __Command=$_DebuggerFullPath "$CORE_ROOT/crossgen" /Platform_Assemblies_Paths $CORE_ROOT:$PWD /in NestedStruct01.org /out NestedStruct01.dll
Managed assembly not found: No such file or directory

Return code: 1
Raw output file: /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/generics/Instantiation/Positive/NestedStruct01/NestedStruct01.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation. All rights reserved.


in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun NestedStruct01.dll ''
in ReleaseLock
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/classloader/generics/Instantiation/Positive/NestedStruct01/NestedStruct01.sh
Expected: True
Actual: False

Stack trace
   at Loader_classloader._generics_Instantiation_Positive_NestedStruct01_NestedStruct01_._generics_Instantiation_Positive_NestedStruct01_NestedStruct01_sh()

```

### PR DESCRIPTION
**Pull request by briansull**
Instead just  use  the vnLibNorm

Fixes #48895

### CODE REVIEW

**Comment by BruceForstall** [comment]
Trigger the "runtime-coreclr r2r-extra" pipeline to verify

**Comment by briansull** [comment]
The failures that occur are due to a different issue, a file not found error when doing a crossgen of CORE_ROOT

**Generate CORE_ROOT**

`Error: Could not load file or assembly 'System.TestStructs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. (0x80070002 (COR_E_FILENOTFOUND))`

**Comment by BruceForstall** [comment]
I kicked off a 'main' branch baseline run so you can see if it also fails in baseline: https://dev.azure.com/dnceng/public/_build/results?buildId=1020021&view=results

**Comment by briansull** [comment]
Thanks Bruce

**Comment by briansull** [comment]
The errors the we get when running crossgen to create CORE_ROOT coudl be caused by:

PR #48858 Build Micrososoft.Extensions.DependencyInjection.Specification.Tests package (checked in 8 hours ago)

**Comment by briansull** [comment]
We are seeing the same regression in the  'main' branch baseline run.
This checkin is blocked until that is fixed

**Comment by briansull** [comment]
I submitted this PR
#49064 - Added System.TestStructs.dll to the list of excluded assemblies in CORE_ROOT

**Comment by briansull** [comment]
@BruceForstall  @AndyAyersMS 

This fixes the issue with the assert failure on arm64 #48895 
We now successfully build the CORE_ROOT folder fin the R2RTest leg now.

I will check this fix in after you approve it.

**Comment by briansull** [comment]
Task failure: **runtime (CoreCLR Pri0 Runtime Tests Run windows arm64 checked)**

```
Discovering: readytorun.multifolder.XUnitWrapper
  Discovered:  readytorun.multifolder.XUnitWrapper
  Starting:    readytorun.multifolder.XUnitWrapper
System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.Collections.Generic.Stack`1.Enumerator.MoveNext()
   at Xunit.Sdk.DisposalTracker.Dispose() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\DisposalTracker.cs:line 26
```

**Comment by BruceForstall** [comment]
r2r-extra was clean. amazing!

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/jit/optcse.cpp [hunk 1]
```diff
@@ -500,6 +500,9 @@ unsigned Compiler::optValnumCSE_Index(GenTree* tree, Statement* stmt)
             // we don't allow/expect it to be set when we need a reloc
             //
             assert((key & TARGET_SIGN_BIT) == 0);
+
+            // Don't use the CoercedConstantValue value as the key
+            key = vnLibNorm;
```
Comment (AndyAyersMS) [inline src/coreclr/jit/optcse.cpp:505]: Seems like this would be less confusing if you didn't set and reset?
```C++
        assert(vnStore->IsVNConstant(vnLibNorm));

        // We don't share small offset constants when we require a reloc
        //
        if (!tree->AsIntConCommon()->ImmedValNeedsReloc(this))
        {
            // Make constants that have the same upper bits use the same key
            key           = vnStore->CoercedConstantValue<size_t>(vnLibNorm);
            key           = Encode_Shared_Const_CSE_Value(key);
            isSharedConst = true;
        }
        else
        {
            key = vnLibNorm;
```

Comment (briansull) [reply src/coreclr/jit/optcse.cpp:505]: Fair enough, I will make this change.

Comment (briansull) [reply src/coreclr/jit/optcse.cpp:506]: @AndyAyersMS

I restructured this slightly and added comments that make it clear that the key encodes a shared constant only when isSharedConst is true.  I also moved this assert and changed it to cover both cases:

`assert(isSharedConst == Is_Shared_Const_CSE(key));`

**Review by AndyAyersMS — APPROVED** [review]
LGTM.
