### PR TITLE
[browser] Calculate hash for runtime assets

### LINKED ISSUE #82888: [browser] don't publish native DLLs
## Problem
System.Diagnostics.Tracing.Tests.csproj has native dependencies such as `vcruntime140.dll`
We should not include them in the `AppBundle` folder and `mono-config.json` because 
- they are not possible to use on wasm anyway
- they create AV problems
- increase download size

The consequences are `Error: MONO_WASM: download 'http://127.0.0.1:40699/managed/vcruntime140_1.dll' for vcruntime140_1.dll failed 0 TypeError: Failed to fetch` see [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-82049-merge-86cfe0b1dd5948ea89/WasmTestOnBrowser-System.Diagnostics.Tracing.Tests/1/console.643bf3f2.log?helixlogtype=result)

image

## Possible solutions
A) `WasmAppBuilder` could skip non IL assemblies
B) `WasmAppBuilder` could fail build when non IL assemblies are added

### PR DESCRIPTION
**Pull request by pavelsavara**
- calculate SHA256 hash and use in to check integrity of the download
- calculate SHA256 of all assets (to be used later for memory snapshot)
- skip non-IL assemblies and issue message for it. Fixes https://github.com/dotnet/runtime/issues/82888

### CODE REVIEW

File: src/tasks/WasmAppBuilder/WasmAppBuilder.cs [hunk 1]
```diff
@@ -37,6 +43,8 @@ public class WasmAppBuilder : WasmAppBuilderBaseTask
     // </summary>
     public ITaskItem[]? ExtraConfig { get; set; }
 
+    private static SHA256 HashAlgorithm = SHA256.Create();
```
Comment (vcsjones) [inline src/tasks/WasmAppBuilder/WasmAppBuilder.cs:46]: Instances of `SHA256` are not thread-safe. If two different instances of `WasmAppBuilder` are sharing this instance and it gets used concurrently, it can lead to incorrect hashes or exceptions.

File: src/tasks/WasmAppBuilder/WasmAppBuilder.cs [hunk 2]
```diff
@@ -199,14 +218,29 @@ protected override bool ExecuteInternal()
...
-            if (DebugLevel != 0) {
-                var pdb = assembly;
-                pdb = Path.ChangeExtension(pdb, ".pdb");
-                if (File.Exists(pdb))
-                    config.Assets.Add(new PdbEntry(Path.GetFileName(pdb)));
+            var bytes = File.ReadAllBytes(assemblyPath);
+            // for the is IL IsAssembly check we need to read the bytes from the original DLL
+            if (!IsAssembly(bytes))
+            {
+                Log.LogWarning("Skipping non-assembly file: " + assemblyPath);
```
Comment (radical) [inline src/tasks/WasmAppBuilder/WasmAppBuilder.cs:225]: Log as a *message* right now, because it is not a test authoring error. It's an issue in our build where we don't correctly handle the publish outputs, and differentiate files. It will be fixed as part of fixing the build to work better for publish.

File: src/tasks/WasmAppBuilder/WasmAppBuilder.cs [hunk 3]
```diff
@@ -408,4 +449,43 @@ private static bool TryConvert(string str, Type type, out object? value)
...
+    {
+        return GetFileHash(File.ReadAllBytes(filePath));
+    }
+
+    public static string GetFileHash(byte[] bytes)
+    {
+        HashAlgorithm.Initialize();
+        var hashBytes = HashAlgorithm.ComputeHash(bytes);
+        return "sha256-" + Convert.ToBase64String(hashBytes);
+    }
```
Comment (radical) [inline src/tasks/WasmAppBuilder/WasmAppBuilder.cs:489]: You can use `Utils.ComputeHash`, and add an overload for `byte[]`

Comment (pavelsavara) [reply src/tasks/WasmAppBuilder/WasmAppBuilder.cs:489]: I need sha-256 not sha-512. I will move it there.

File: src/tasks/WasmAppBuilder/WasmAppBuilder.cs [hunk 4]
```diff
@@ -408,4 +449,43 @@ private static bool TryConvert(string str, Type type, out object? value)
             return false;
         }
     }
+
+    public static bool IsAssembly(byte[] bytes)
```
[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/tasks/WasmAppBuilder/WasmAppBuilder.cs]: moved to utils

**Comment by pavelsavara** [comment]
CI failure is https://github.com/dotnet/runtime/issues/82880

**Review by ilonatommy — APPROVED** [review]

**Review by maraf — APPROVED** [review]
