### PR TITLE
Fix multi-reg temporary copy

### LINKED ISSUE #37830: Assertion failed 'isCandidateLocalRef(tree)'
Failure in libraries System.Linq.Queryable.Tests: release libraries, checked coreclr with:
```
COMPlus_TieredCompilation=0
COMPlus_JitStress=2
COMPlus_JitStressRegs=8
```

Windows arm64

E.g.,
```
build -s libs+libs.tests -runtimeConfiguration checked -c Release -arch arm64 /p:ArchiveTests=true
```

(the `/p:ArchiveTests=true` is required to build the RunTests.cmd wrapper scripts)

```
c:\bugs\System.Linq.Queryable.Tests\net5.0-Release>call .\RunTests.cmd -r C:\bugs\testhost\net5.0-Windows_NT-Release-arm64
```

```
----- start Fri 06/12/2020 15:01:43.35 ===============  To repro directly: =====================================================
pushd c:\bugs\System.Linq.Queryable.Tests\net5.0-Release\
"C:\bugs\testhost\net5.0-Windows_NT-Release-arm64\dotnet.exe" exec --runtimeconfig System.Linq.Queryable.Tests.runtimeconfig.json --depsfile System.Linq.Queryable.Tests.deps.json xunit.console.dll System.Linq.Queryable.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

c:\bugs\System.Linq.Queryable.Tests\net5.0-Release>"C:\bugs\testhost\net5.0-Windows_NT-Release-arm64\dotnet.exe" exec --runtimeconfig System.Linq.Queryable.Tests.runtimeconfig.json --depsfile System.Linq.Queryable.Tests.deps.json xunit.console.dll System.Linq.Queryable.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
  Discovering: System.Linq.Queryable.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Linq.Queryable.Tests (found 720 test cases)
  Starting:    System.Linq.Queryable.Tests (parallel test collections = on, max threads = 8)

Assert failure(PID 11008 [0x00002b00], Thread: 8968 [0x2308]): Assertion failed 'isCandidateLocalRef(tree)' in 'DynamicClass:lambda_method1638(System.Runtime.CompilerServices.Closure):System.Nullable`1[Double]' during 'LSRA allocate' (IL size 19)

    File: C:\gh\runtime2\src\coreclr\src\jit\lsra.cpp Line: 6788
    Image: C:\bugs\testhost\net5.0-Windows_NT-Release-arm64\dotnet.exe

----- end Fri 06/12/2020 15:02:01.37 ----- exit code 255 ----------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by CarolEidt**
If we need to insert a COPY node to signify a temporary copy of field of a multi-reg lclVar, we need to set the appropriate last use bit.

Fix #37830

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

File: src/coreclr/src/jit/gentree.h [hunk 1]
```diff
@@ -7402,6 +7386,86 @@ inline unsigned int GenTree::GetRegSpillFlagByIdx(int regIndex) const
...
+//
+// Arguments:
+//     regIndex - the register index
+//
+// Notes:
+//     This must be a GenTreeLclVar or GenTreeCopyOrReload node.
+//
+inline void GenTree::SetLastUse(int regIndex)
+{
+    unsigned int bitToSet = gtFlags |= GetLastUseBit(regIndex);
```
Comment (BruceForstall) [inline src/coreclr/src/jit/gentree.h:7452]: I realize you just copied this, but the `unsigned int bitToSet =` part is not used.

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/src/jit/gentree.h (hunk 1 above)
Comment (CarolEidt) [reply src/coreclr/src/jit/gentree.h:7452]: Thanks - I'll fix that in a future change, to avoid another CI testing round.
