### PR TITLE
Properly handle byrefs in tailcall helper stubs

### LINKED ISSUE #41555: [GCStress] JIT/Methodical/tailcall/_il_dbgreference_i Assert failure SanityCheck()
```
export COMPlus_TieredCompilation=0
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export COMPlus_GCStress=0xC

    JIT/Methodical/tailcall/_il_dbgreference_i/_il_dbgreference_i.sh [FAIL]
      Unhandled exception. 
      Assert failure(PID 2769 [0x00000ad1], Thread: 2769 [0x0ad1]): SanityCheck()
          File: /__w/1/s/src/coreclr/src/vm/methodtable.cpp Line: 9367
          Image: /root/helix/work/correlation/corerun
      
      /root/helix/work/workitem/JIT/Methodical/tailcall/_il_dbgreference_i/_il_dbgreference_i.sh: line 356:  2769 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/tailcall/_il_dbgreference_i/_il_dbgreference_i.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun _il_dbgreference_i.dll ''
      2 Gathering state for process 2769 corerun
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.2769.dmp
      Written 55345152 bytes (13512 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
```

https://dev.azure.com/dnceng/public/_build/results?buildId=793659&view=results
https://helix.dot.net/api/2019-06-17/jobs/d2e0c1f9-e5dc-4d0c-9252-d4f2d7fe271c/workitems/JIT.Methodical/console

### PR DESCRIPTION
**Pull request by jakobbotsch**
Switch to using ByReference instead of using stind.i/ldind.i and relying
on the JIT to report the locations being moved between.

Fixes #41555

cc @BruceForstall @jkotas

### CODE REVIEW

**Comment by jakobbotsch** [comment]
@BruceForstall assuming tests pass, can you check if this fixes #41555?

File: src/coreclr/src/vm/tailcallhelp.cpp [hunk 1]
```diff
@@ -503,6 +497,11 @@ MethodDesc* TailCallHelp::CreateCallTargetStub(const TailCallInfo& info)
     pCode->EmitLDC(info.ArgBufLayout.HasInstArg ? TAILCALLARGBUFFER_INSTARG_ONLY : TAILCALLARGBUFFER_ABANDONED);
     pCode->EmitSTIND_I();
 
+    // *pTailCallAwareRetAddr = NextCallReturnAddress();
```
Comment (jkotas) [inline src/coreclr/src/vm/tailcallhelp.cpp:500]: Why move it here? Assignments tends to cause stills. It is generally better to make assignments without stuff on the IL stack.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/src/vm/tailcallhelp.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/src/vm/tailcallhelp.cpp:500]: I moved it close to the target call because now there were other calls in the IL stream between the `NextCallReturnAddress` and the actual call to the target. However it was still working properly because `Value` is force expanded, so the move is not strictly necessary. Code quality wise I checked that there is no difference (the JIT is already spilling because of the stind.i right above). However I don't have a strong opinion on where to put it.

Comment (jkotas) [reply src/coreclr/src/vm/tailcallhelp.cpp:500]: ok

Comment (jkotas) [reply src/coreclr/src/vm/tailcallhelp.cpp:500]: Actually, I would expect the original location to generate better code when there is a register pressure (`pTailCallAwareRetAddr` becomes dead earlier).

Comment (jakobbotsch) [reply src/coreclr/src/vm/tailcallhelp.cpp:500]: Good point, I will move it back.

**Review by jkotas — APPROVED** [review]

**Comment by BruceForstall** [comment]
> @BruceForstall assuming tests pass, can you check if this fixes #41555?

I was never able to reliably repro the problem, so I won't be able to "prove" the fix works that way. I looked at the generated code + GC info for the "Call" stub for the 41555 test case on Windows arm32, and it looks good to me: the byrefs I annotated in the bug as needing GC tracking are appropriately tracked.

If you're happy with this change as is, I'm inclined to trigger outerloop + gcstress0x3-gcstress0xc + gcstress-extra legs. That's expensive and time consuming, but it's the best way, IMO, to see that the issue doesn't repro in the CI where it was (somewhat) reliably repro'ing (and check for regressions).

**Review by BruceForstall — APPROVED** [review]
LGTM; thanks for the quick turnaround!

**Comment by jakobbotsch** [comment]
> I was never able to reliably repro the problem, so I won't be able to "prove" the fix works that way. I looked at the generated code + GC info for the "Call" stub for the 41555 test case on Windows arm32, and it looks good to me: the byrefs I annotated in the bug as needing GC tracking are appropriately tracked.
> 
> If you're happy with this change as is, I'm inclined to trigger outerloop + gcstress0x3-gcstress0xc + gcstress-extra legs. That's expensive and time consuming, but it's the best way, IMO, to see that the issue doesn't repro in the CI where it was (somewhat) reliably repro'ing (and check for regressions).

Thanks for checking! Triggering those legs sounds good to me.

**Comment by BruceForstall** [comment]
Triggered:

outerloop: https://dev.azure.com/dnceng/public/_build/results?buildId=800825&view=results
runtime-coreclr gcstress0x3-gcstress0xc: https://dev.azure.com/dnceng/public/_build/results?buildId=800829&view=results
runtime-coreclr gcstress-extra: https://dev.azure.com/dnceng/public/_build/results?buildId=800827&view=results

**Comment by BruceForstall** [comment]
outerloop failures are https://github.com/dotnet/runtime/issues/41853, gcstress failures are a few timeouts (that's unfortunately common). The `_il_dbgreference_i` test did not fail on Linux/arm anywhere, which is good.
