### PR TITLE
Fix copy constructor injection for unsafe value classes

### LINKED ISSUE #100751: Test failure: Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
**Failed in:** [runtime-coreclr jitstress-random 20240407.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634043&view=ms.vss-test-web.build-test-results-tab&runId=15588564&resultId=117792&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress_random_2 @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hwA234091BwAC40094BuploadsIJWCopyConstructorMarshalerCopyConstructorMarshaleroutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwA234091Bpcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  CopyConstructorMarshaler.dll 
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 0
Actual:   2
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at CopyConstructorMarshaler.CopyConstructorMarshaler.CopyConstructorsInArgumentStackSlots()
   at __GeneratedMainWrapper.Main()
Registering 00ABE434
Registering copy of 00ABE434 at 00ABE438
Registering copy of 00ABE438 at 00ABE3F4
Unregistering 00ABE438
Registering copy of 00ABE3F4 at 00ABE390
Unregistering 00ABE3F4
Unmanaged: Using relative at address 00ABE390
Unregistering 00ABE390
Unregistering 00ABE434
Registering 00ABE3F8
Registering copy of 00ABE3F8 at 00ABE3E0
Managed: Using relative at address 00ABE3D0
Error: Relative object 00ABE3D0 not registered
 Error: Relative object 00ABE3D0 has invalid relative pointer 00ABE3DC
Unregistering 00ABE3F8
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 4/7/2024 8:31:14 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwA234091BwAC40094BeInteropInterop../IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor243|25_244(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
For C++/CLI types with C-style array fields (`int x[N];`), the JIT was introducing extra copies without calling the copy constructor.

This was discovered through JitStress, which forcibly set the flag that the C++/CLI compiler sets when it sees a C-style array field.

To avoid adding a new API to the JIT interface just for usage by C++/CLI, I made a targeted fix to disable the GS cookie checking in Reverse P/Invoke stubs as we control the IL and we don't emit IL that would interact with these fields in a dangerous manner. As this fix was in CoreCLR and not propagated to the JIT, I still had to disable the tests that were failing from JitStress as setting the flag for the local in the JIT will still cause the bad behavior.

Alternatively, we could enhance the JIT interface to enable the JIT to discover when a type has a copy constructor and do one of the following:

- Skip GS cookie checks
- Create `GT_CALL` nodes to the copy constructor and destructor instead of generating a `GT_STORE_LCL_VAR` node.

If we were to go the second route, then I'd prefer moving all the "copy construct into the arg's stack slot" logic into the JIT and remove the code we added in the IL marshallers that supports that case.

I think a fix for this bug is worth considering backporting (as it would likely lead to hard-to-diagnose bugs and violates C++/CLI semantics). We may want a more targeted fix like this instead of a more expansive fix for backporting, I'm not sure.

Fixes #100751
Related to #100033

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
cc: @jkotas @AaronRobinsonMSFT for thoughts on the best way to fix this.

**Comment by AaronRobinsonMSFT** [comment]
> Create `GT_CALL` nodes to the copy constructor and destructor instead of generating a `GT_STORE_LCL_VAR` node.

Agree.

Can we do this for .NET 9?

**Comment by jkotas** [comment]
> we could enhance the JIT interface

What would this JIT/EE interface modification look like?

File: src/tests/Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler.cs [hunk 1]
```diff
@@ -62,6 +62,7 @@ public static int TestEntryPoint()
         }
 
         [Fact]
+        [SkipOnCoreClr("JitStress and MinOpts can introduce extra copies that won't happen in production scenarios.", RuntimeTestModes.JitStress | RuntimeTestModes.JitMinOpts)]
```
Comment (jkotas) [inline src/tests/Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler.cs:65]: MinOpts is a production scenario.

File: src/coreclr/vm/jitinterface.cpp [hunk 2]
```diff
@@ -3743,8 +3743,18 @@ uint32_t CEEInfo::getClassAttribsInternal (CORINFO_CLASS_HANDLE clsHnd)
...
-            if (pClass->IsUnsafeValueClass())
+            // In Reverse P/Invoke stubs, we are generating the code
+            // and we are not generating the code patterns that the GS checks
+            // are meant to catch.
+            // As a result, we can skip setting this flag.
+            // We do this as the GS checks (emitted when this flag is set)
+            // can break C++/CLI's copy-constructor semantics by missing copies.
+            if (pClass->IsUnsafeValueClass()
+                && !(m_pMethodBeingCompiled->IsILStub()
+                    && dac_cast<PTR_DynamicMethodDesc>(m_pMethodBeingCompiled)->GetILStubType() == DynamicMethodDesc::StubNativeToCLRInterop))
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:3754]: I think it may be better to introduce a new bit that says "do not create a shadow copies of this argument, this argument must be stored in its natural location". 

Fixing it like this on the VM side looks reasonable to me.

File: src/tests/Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler.cs (hunk 1 above)
Comment (jkoritzinsky) [reply src/tests/Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler.cs:65]: I'll test this again with MinOpts and make sure it works.

**Comment by jkoritzinsky** [comment]
I was thinking of using a bit on `CorInfoTypeWithMod` to represent "must use copy-constructor helper" and populate that depending on the `IsCopyConstructed` modreq. Then use a JIT helper (that either looks up in a hash table or uses an intrinsic implementation like `RuntimeHelpers.IsReferenceOrContainsReferences<T>()`) to do the copy with the copy constructor + destructor semantics instead of `GT_STORE_LCL_VAR`.

I don't like fixing it by dropping the shadow variable because it defeats the GS cookie buffer overflow protections.

**Comment by jkotas** [comment]
> Then use a JIT helper (that either looks up in a hash table or uses an intrinsic implementation like RuntimeHelpers.IsReferenceOrContainsReferences<T>()) to do the copy with the copy constructor + destructor semantics instead of GT_STORE_LCL_VAR.

Does it meant that we would or would not call the user provided constructor/destructor depending on the optimization settings? It does not sound right to me.

**Comment by jkoritzinsky** [comment]
No, we'd always call the copy constructor no matter the optimization level. Because this flag would only be set in the IL stubs (due to when the C++/CLI compiler emits it), we'd only do this particular optimization in places where the JIT emits a copy that the IL stub cannot predict (or predict easily, for the P/Invoke case).

Basically, we'd utilize the flag in at most two places:

- In the GS checks shadow copying
- Into the P/Invoke arg slots

Since the VM will control the IL that the JIT sees with this modreq (as it is only used on P/Invokes and Reverse P/Invokes where the C++/CLI compiler can't emit the copy constructor calls itself) and we won't emit code that would do copies depending on optimization level, the number of times we call the copy constructor or destructor will not differ based on optimization level.

**Comment by jkotas** [comment]
Does it mean that there would be a new call of the copy constructor that is not there today? (ie the change would be user observable)

**Comment by jkoritzinsky** [comment]
Yes, there would be a new call to the copy constructor that isn't there today (as we're currently missing a call). Previously we have not been concerned about introducing additional copies where necessary for validity.

(Additionally, if we were to implement the second of the two items above, we should be able to remove a call from the P/Invoke stubs).

**Comment by jkotas** [comment]
Does it mean that the fix would assume that the user type constructors are correctly implemented according to the C++ rules? I am not sure whether it is safe to assume that and how much real-world code it can break.

**Comment by jkoritzinsky** [comment]
The only assumptions the fix would make would be about the IL we emit (which I think we could guard with `badCode` or asserts in the JIT).

We already don't assume that copy constructors are implemented in any particular way. We just make sure to call them each time we make a copy that could eventually be passed out of the stub.

**Review by jkotas — APPROVED** [review]
LGTM

**Review by AaronRobinsonMSFT — APPROVED** [review]
