### PR TITLE
Fix a couple issues with Vector128.Get/WithElement

### LINKED ISSUE #37260: Assertion failed 'compIsaSupportedDebugOnly(InstructionSet_SSE2)'
Over 52,000 tests in the `runtime-coreclr jitstress-isas-x86` pipeline failed (presumably all) with:
```
      Assert failure(PID 7268 [0x00001c64], Thread: 5492 [0x1574]): Assertion failed 'compIsaSupportedDebugOnly(InstructionSet_SSE2)' in 'VectorRelopTest`1[Single][System.Single]:VectorRelOp(float,float):int' during 'Importation' (IL size 1406)
      
          File: F:\workspace\_work\1\s\src\coreclr\src\jit\simdashwintrinsic.cpp Line: 870
          Image: C:\h\w\9D4B08E8\p\CoreRun.exe
```

Pipeline results:
https://dev.azure.com/dnceng/public/_build/results?buildId=665306&view=ms.vss-test-web.build-test-results-tab

Example:
https://helix.dot.net/api/2019-06-17/jobs/a36943e0-4275-4b16-9f01-6d656c33e5eb/workitems/JIT/console

```
    JIT\SIMD\VectorRelOp_r\VectorRelOp_r.cmd [FAIL]
      
      Assert failure(PID 7268 [0x00001c64], Thread: 5492 [0x1574]): Assertion failed 'compIsaSupportedDebugOnly(InstructionSet_SSE2)' in 'VectorRelopTest`1[Single][System.Single]:VectorRelOp(float,float):int' during 'Importation' (IL size 1406)
      
          File: F:\workspace\_work\1\s\src\coreclr\src\jit\simdashwintrinsic.cpp Line: 870
          Image: C:\h\w\9D4B08E8\p\CoreRun.exe
      
      
      Return code:      1
      Raw output file:      C:\h\w\9D4B08E8\w\A49A0919\e\JIT\SIMD\Reports\JIT.SIMD\VectorRelOp_r\VectorRelOp_r.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\9D4B08E8\p\corerun.exe" VectorRelOp_r.dll 
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\9D4B08E8\p
      > C:\h\w\9D4B08E8\w\A49A0919\e\JIT\SIMD\VectorRelOp_r\VectorRelOp_r.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\JIT.SIMD\JIT.SIMD.XUnitWrapper.cs(9646,0): at JIT_SIMD._VectorRelOp_r_VectorRelOp_r_._VectorRelOp_r_VectorRelOp_r_cmd()
      Output:
```

### LINKED ISSUE #52954: Test failure JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd
Run: [runtime-coreclr outerloop 20210518.6](https://dev.azure.com/dnceng/public/_build/results?buildId=1144608&view=ms.vss-test-web.build-test-results-tab&runId=34673638&resultId=108267&paneView=debug)

Failed test:
```
R2R windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

```
**Error message:**
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
at TestHFAandHVA.TestReturnViaThrowingT in structreturn.dll:token 0x6000077+0x0
at TestHFAandHVA.TestThrowing() in structreturn.dll:token 0x6000078+0x0
at TestHFAandHVA.TestReturnVectorT() in structreturn.dll:token 0x6000079+0x141
at TestHFAandHVA.Test() in structreturn.dll:token 0x600008a+0xa
at TestStructs.Main() in structreturn.dll:token 0x6000095+0xf

Return code:      1
Raw output file:      C:\h\w\B6AA09DE\w\9AC608D1\e\JIT\Directed\Reports\JIT.Directed\StructABI\structreturn\structreturn.output.txt
Raw output:
BEGIN EXECUTION
1 file(s) copied.
" "C:\h\w\B6AA09DE\p\crossgen.exe"  /Platform_Assemblies_Paths C:\h\w\B6AA09DE\p;C:\h\w\B6AA09DE\w\9AC608D1\e\JIT\Directed\StructABI\structreturn /in C:\h\w\B6AA09DE\w\9AC608D1\e\JIT\Directed\StructABI\structreturn\structreturn.org /out C:\h\w\B6AA09DE\w\9AC608D1\e\JIT\Directed\StructABI\structreturn\structreturn.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image C:\h\w\B6AA09DE\w\9AC608D1\e\JIT\Directed\StructABI\structreturn\structreturn.dll generated successfully.
"C:\h\w\B6AA09DE\p\corerun.exe"  structreturn.dll
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B6AA09DE\p
C:\h\w\B6AA09DE\w\9AC608D1\e\JIT\Directed\StructABI\structreturn\structreturn.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._StructABI_structreturn_structreturn_._StructABI_structreturn_structreturn_cmd()
```

caused by #52288

### LINKED ISSUE #52959: Assertion failed '(genTypeSize(node->TypeGet()) == 16) || (genTypeSize(node->TypeGet()) == 32)'
1. Compile:
```csharp
using System;
using System.Numerics;
using System.Reflection;
using System.Runtime.Intrinsics;

var mi = typeof(Vector128).GetMethod("AsVector128", new Type[] { typeof(Vector2) });
mi.Invoke(null, new object[] { new Vector2() });
```

2. Run with VEX instruction encoding disabled: 
```
set COMPlus_EnableAVX=0
set COMPlus_EnableSSE41=0
set COMPlus_ReadyToRun=0
corerun test.exe
```

Result:
```
Assert failure(PID 24192 [0x00005e80], Thread: 12184 [0x2f98]): Assertion failed '(genTypeSize(node->TypeGet()) == 16) || (genTypeSize(node->TypeGet()) == 32)' in 'System.Runtime.Intrinsics.Vector128:AsVector128(System.Numerics.Vector2):System.Runtime.Intrinsics.Vector128`1[Single]' during 'Lowering nodeinfo' (IL size 22)

    File: C:\runtime\src\coreclr\jit\lowerxarch.cpp Line: 5539
    Image: C:\runtime\artifacts\bin\coreclr\windows.x64.Checked\corerun.exe
```

### LINKED ISSUE #53157: Test failure JIT/SIMD/VectorGet_ro/VectorGet_ro.sh
Run: [runtime-coreclr jitstress-isas-x86 20210522.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1151759&view=ms.vss-test-web.build-test-results-tab&runId=34825488&resultId=109378&paneView=debug)

Failed tests:
```
JIT/SIMD/VectorGet_ro/VectorGet_ro.sh
JIT/SIMD/VectorGet_r/VectorGet_r.sh
JIT/SIMD/VectorArray_r/VectorArray_r.sh
```
**Error message:**
```
Return code:      1
Raw output file:      /private/tmp/helix/working/9C4708A3/w/AF38097C/e/JIT/SIMD/Reports/JIT.SIMD/VectorGet_ro/VectorGet_ro.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/9C4708A3/p/corerun VectorGet_ro.dll ''
Method System.Numerics.Vector1[Int32][System.Int32]:get_Item was compiled but should not have been Method System.Numerics.Vector1[Int64][System.Int64]:get_Item was compiled but should not have been
Method System.Numerics.Vector1[Byte][System.Byte]:get_Item was compiled but should not have been Method System.Numerics.Vector1[SByte][System.SByte]:get_Item was compiled but should not have been
Method System.Numerics.Vector1[UInt32][System.UInt32]:get_Item was compiled but should not have been Method System.Numerics.Vector1[UInt64][System.UInt64]:get_Item was compiled but should not have been
Method System.Numerics.Vector1[IntPtr][System.IntPtr]:get_Item was compiled but should not have been Method System.Numerics.Vector1[UIntPtr][System.UIntPtr]:get_Item was compiled but should not have been
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/9C4708A3/p
/private/tmp/helix/working/9C4708A3/w/AF38097C/e/JIT/SIMD/VectorGet_ro/VectorGet_ro.sh
Expected: True
Actual:   False


Stack trace
   at JIT_SIMD._VectorGet_ro_VectorGet_ro_._VectorGet_ro_VectorGet_ro_sh()
```

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/52959 by ensuring that we don't have any unused nodes and that containment checks bail when encountering TYP_SIMD8 or TYP_SIMD12 values where a TYP_SIMD16 or TYP_SIMD32 value is required for containment.
This resolves https://github.com/dotnet/runtime/issues/52954 by ensuring the expected exception is the one thrown by all Vector indexing
This resolves https://github.com/dotnet/runtime/issues/53157
This resolves https://github.com/dotnet/runtime/issues/37260

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @jkotas, @echesakovMSFT

**Comment by jkotas** [comment]
Now failing with:
```
D:\workspace\_work\1\s\src\coreclr\jit\lower.cpp:6025
Assertion failed 'compiler->lvaIsFieldOfDependentlyPromotedStruct(lclVar) || (lclVar->lvSize() == 12)' in 'System.Runtime.Intrinsics.Vector128:AsVector128(System.Numerics.Vector3):System.Runtime.Intrinsics.Vector128`1[System.Single]' during 'Lowering nodeinfo' (IL size 17)
```

**Comment by tannergooding** [comment]
> Now failing with:

This was because we are cloning a TYP_SIMD12 LclVar in lowering. Lowering "widens" (changes the type) of these to TYP_SIMD16 which causes an assert when the types mismatch on clone.
I resolved this by allowing specifically the `TYP_SIMD16` LclVar node over a `TYP_SIMD12` backing `VarDsc`.

There is also a failure in the logic for `WithElement` in the pre-SSE4.1 path which I've fixed.

**Comment by tannergooding** [comment]
> I am still seeing this failure even with the latest commit.

Should be resolved now. Both the LclVar and assignment need to be lowered for ReplaceWithLclVar over TYP_SIMD12 nodes.

**Comment by tannergooding** [comment]
@jkotas, all tests are passing now. This should be good now.

**Comment by jkotas** [comment]
> @jkotas, all tests are passing now. This should be good now.

Thank you. I see all tests passing in runtimelab NativeAOT branch - where I found it initially - as well.

**Comment by tannergooding** [comment]
@echesakovMSFT, @dotnet/jit-contrib can I get a review to unblock the failing jitstress/outerloop tests?

**Comment by tannergooding** [comment]
@echesakovMSFT, @dotnet/jit-contrib can I get a review to unblock the failing jitstress/outerloop tests?

File: src/coreclr/jit/lower.h [hunk 1]
```diff
@@ -217,9 +217,18 @@ class Lowering final : public Phase
...
+            GenTree* assign;
+            use.ReplaceWithLclVar(comp, tempNum, &assign);
+
             GenTree* newUseNode = use.Def();
             ContainCheckRange(oldUseNode->gtNext, newUseNode);
+
+            // We need to lower the LclVar and assignment since there may be certain
+            // types or scenarios, such as TYP_SIMD12, that need special handling
+
+            LowerNode(assign);
```
Comment (sandreenko) [inline src/coreclr/jit/lower.h:229]: I do not think it is a correct approach, this function is used during different phases, for example, during long decomposition, so calling `LowerNode` during it is incorrect. 
`ReplaceWithLclVar` creates such IR:
```
currentNode
storeCurrentNodeToNewNode
NewNodeUse
```
and lowering works node by node, so after we are done with `currentNode` we should go to the next and lower it, why don't we?

See, for example, `LowerSwitch`
https://github.com/dotnet/runtime/blob/b443b8ccce174ef0e87183e21561c4ff13373cfd/src/coreclr/jit/lower.cpp#L504
we call `ReplaceWithLclVar` and it creates these new nodes, but then we return `node->gtNext` that is the created store:
https://github.com/dotnet/runtime/blob/b443b8ccce174ef0e87183e21561c4ff13373cfd/src/coreclr/jit/lower.cpp#L785-L791
and it does their lowering.

**Review by sandreenko — DISMISSED** [review]
I am not against unblocking outerloop I am just worried it could create more issues, I suggest disabling the failing test in separate PR and take time to finish this.

**Review by echesakov — COMMENTED** [review]
I am still reviewing the changes in 1a4e854a3e4b5f171b0c00ebe4eb9eae75a49595
But I want to release some comments to speed up the review process

File: src/coreclr/jit/lower.h (hunk 1 above)
Comment (tannergooding) [reply src/coreclr/jit/lower.h:229]: The one used in long decomposition is the instance method exposed on `LIR::Use` which is distinct from this method that is explicit to lowering and which itself calls into the `LIR::Use` method

Comment (tannergooding) [reply src/coreclr/jit/lower.h:229]: > and lowering works node by node, so after we are done with currentNode we should go to the next and lower it, why don't we?

We should already have lowered all the previous nodes, we aren't removing the "current" node, and we aren't inserting a node after the "current" node, so the "next" node is already correct. We simply need to ensure new nodes created and inserted before this node are also lowered.

This is how the existing HWIntrinsic lowering has been handled and so the same technique is used here as well.

File: src/coreclr/jit/gentree.cpp [hunk 2]
```diff
@@ -6507,9 +6507,16 @@ GenTree* Compiler::gtNewLclvNode(unsigned lnum, var_types type DEBUGARG(IL_OFFSE
         // should be able to remove this exception and handle the assignment mismatch in
         // Lowering.
         LclVarDsc* varDsc = lvaGetDesc(lnum);
+#if FEATURE_SIMD
+        // We can additionally have a SIMD12 that was widened to a SIMD16, generally as part of lowering
+        assert((type == varDsc->lvType) || ((type == TYP_SIMD16) && (varDsc->lvType == TYP_SIMD12)) ||
```
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:6512]: Because we weren't introducing `TYP_SIMD12` nodes in lowering, it was all happening either earlier (in which case the nodes naturally lowered as part of normal traversal) or being handled in codegen (leading to less efficient codegen).

File: src/coreclr/jit/lower.h (hunk 1 above)
Comment (sandreenko) [reply src/coreclr/jit/lower.h:229]: > We should already have lowered all the previous nodes, we aren't removing the "current" node, 

Agree

> and we aren't inserting a node after the "current" node, so the "next" node is already correct.

Don't understand, `ReplaceWithLclVar` creates new nodes and inserts them after the "current" node, what do you mean?

File: src/coreclr/jit/lower.h [hunk 3]
```diff
@@ -217,9 +217,18 @@ class Lowering final : public Phase
...
         {
-            use.ReplaceWithLclVar(comp, tempNum);
+            GenTree* assign;
+            use.ReplaceWithLclVar(comp, tempNum, &assign);
+
             GenTree* newUseNode = use.Def();
             ContainCheckRange(oldUseNode->gtNext, newUseNode);
+
+            // We need to lower the LclVar and assignment since there may be certain
+            // types or scenarios, such as TYP_SIMD12, that need special handling
```
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/lower.h:227]: We have existing handling for those node types which is otherwise missed, this leads to worse codegen or asserts: https://github.com/dotnet/runtime/blob/b443b8ccce174ef0e87183e21561c4ff13373cfd/src/coreclr/jit/lower.cpp#L283-L313

In the case of `GT_STORE_LCL_VAR` its expected that all `TYP_SIMD12` locals are widened to `TYP_SIMD16`, there is then other handling that exists for multiple register and constant handling that otherwise never happens for these introduced locals.

File: src/coreclr/jit/lower.h (hunk 1 above)
Comment (tannergooding) [reply src/coreclr/jit/lower.h:229]: > Don't understand, ReplaceWithLclVar creates new nodes and inserts them after the "current" node, what do you mean?

`ReplaceWithLclVar` creates new nodes and inserts them after the node it replaces. In this case, we are replacing an operand of the "current" node, which means it precedes the current node in the list and will already have been lowered.

File: src/coreclr/jit/simd.cpp [hunk 4]
```diff
@@ -1909,7 +1909,7 @@ GenTree* Compiler::impSIMDIntrinsic(OPCODE                opcode,
 #error Unsupported platform
```
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/simd.cpp]: Fixed.

File: src/coreclr/jit/gentree.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp]: Fixed the assertion to remove duplication.

File: src/coreclr/jit/morph.cpp [hunk 5]
```diff
@@ -12044,7 +12044,7 @@ GenTree* Compiler::fgMorphFieldToSimdGetElement(GenTree* tree)
     unsigned    simdSize        = 0;
     GenTree*    simdStructNode  = getSIMDStructFromField(tree, &simdBaseJitType, &index, &simdSize);
 
-    if (simdStructNode != nullptr)
+    if ((simdStructNode != nullptr) && IsBaselineSimdIsaSupported())
```
Comment (echesakovMSFT) [inline src/coreclr/jit/morph.cpp:12047]: I wonder if should call `fgMorphFieldToSimdGetElement` at all when `!IsBaselineSimdIsaSupported()`

File: src/coreclr/jit/lower.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/lower.h:227]: Will do

File: src/coreclr/jit/lowerxarch.cpp [hunk 6]
```diff
@@ -3093,22 +3093,22 @@ void Lowering::LowerHWIntrinsicWithElement(GenTreeHWIntrinsic* node)
                     {
                         case 1:
                         {
-                            controlBits1 = 0;
-                            controlBits2 = 226;
+                            controlBits1 = 0;   // 00 00 00 00;  op1 = { X = op3,   Y = op3,   Z = op1.X, W = op1.X }
```
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp:3096]: It was tracking the managed API inputs as I found that clearer to see that the right values are being selected over the temporary names

File: src/tests/JIT/SIMD/VectorGet.cs [hunk 7]
```diff
@@ -206,33 +208,35 @@ private static int Main()
...
-        if (!jitLog.Check("get_Count", "UInt32")) returnVal = Fail;
-        if (!jitLog.Check("get_Item", "UInt64")) returnVal = Fail;
-        if (!jitLog.Check("get_Count", "UInt64")) returnVal = Fail;
-        if (!jitLog.Check("get_Item", "IntPtr")) returnVal = Fail;
-        if (!jitLog.Check("get_Count", "IntPtr")) returnVal = Fail;
-        if (!jitLog.Check("get_Item", "UIntPtr")) returnVal = Fail;
-        if (!jitLog.Check("get_Count", "UIntPtr")) returnVal = Fail;
-        jitLog.Dispose();
-
+        if (Sse41.IsSupported || AdvSimd.IsSupported)
```
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/tests/JIT/SIMD/VectorGet.cs:211]: Yes. Before #52288 we would generate code involving shifts for extract/insert. This is fairly inefficient and is only applicable to x86 hardware prior to 2007.
Using the software fallback on the old hardware is reasonable and matches roughly what we do on the managed side when determining if intrinsification is worthwhile.

We could continue emitting the shifting logic on older hardware, but it makes the JIT more complex for little practical use.

File: src/coreclr/jit/morph.cpp (hunk 5 above)
Comment (tannergooding) [reply src/coreclr/jit/morph.cpp:12047]: I can move the check further up.

File: src/coreclr/jit/lowerxarch.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp:3096]: I've added a comment to try and explain things better:
```cpp
                    // The comments beside the control bits below are listed using the managed API operands
                    //
                    // In practice, for the first step the value being inserted (op3) is in tmp1
                    // while the other elements of the result (op1) are in tmp2. The result ends
                    // up containing the value being inserted and its immediate neighbor.
                    //
                    // The second step takes that result (which is in op1) plus the other elements
                    // from op2 (a clone of op1/tmp2 from the previous step) and combines them to
                    // create the final result.
```

File: src/coreclr/jit/lower.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/lower.h:227]: @echesakovMSFT no diffs for the `frameworks`, `benchmarks`, or `tests` pmi diffs from `jit-diff`

The "baseline" for the pre-SSE4.1 codegen fails due to the asserts that this PR fixes, ignoring those asserts the changes for the are just that the immediate and order of the operands on the shuffle are now correct.

File: src/coreclr/jit/morph.cpp (hunk 5 above)
Comment (tannergooding) [reply src/coreclr/jit/morph.cpp]: This was moved out for both `fgMorphFieldToSimdGetElement` and `fgMorphFieldAssignToSimdSetElement` so we only do the transforms when the baseline ISAs are marked supported.

File: src/coreclr/jit/lower.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (echesakovMSFT) [reply src/coreclr/jit/lower.h:227]: Thank you @tannergooding for confirming this.

File: src/coreclr/jit/morph.cpp [hunk 8]
```diff
@@ -12076,7 +12079,7 @@ GenTree* Compiler::fgMorphFieldAssignToSimdSetElement(GenTree* tree)
     unsigned    simdSize        = 0;
     GenTree*    simdStructNode  = getSIMDStructFromField(tree->gtGetOp1(), &simdBaseJitType, &index, &simdSize);
 
-    if (simdStructNode != nullptr)
+    if ((simdStructNode != nullptr) && IsBaselineSimdIsaSupported())
```
Comment (echesakovMSFT) [inline src/coreclr/jit/morph.cpp:12082]: Is this check for `IsBaselineSimdIsaSupported` still needed?

File: src/coreclr/jit/morph.cpp [hunk 9]
```diff
@@ -6006,22 +6006,25 @@ GenTree* Compiler::fgMorphField(GenTree* tree, MorphAddrContext* mac)
...
-    {
-        GenTreeLclVarCommon* lcl = objRef->IsLocalAddrExpr();
-        if (lcl != nullptr)
+        else if ((objRef != nullptr) && (objRef->OperGet() == GT_ADDR) && varTypeIsSIMD(objRef->gtGetOp1()))
         {
-            lvaSetVarDoNotEnregister(lcl->GetLclNum() DEBUGARG(DNER_LocalField));
+            GenTreeLclVarCommon* lcl = objRef->IsLocalAddrExpr();
+            if (lcl != nullptr)
+            {
+                lvaSetVarDoNotEnregister(lcl->GetLclNum() DEBUGARG(DNER_LocalField));
```
Comment (echesakovMSFT) [inline src/coreclr/jit/morph.cpp:6026]: Can you explain why `else if`-case also needs to be conditional on `IsBaselineSimdIsaSupported`?

**Review by echesakov — COMMENTED** [review]
Looks Good but have some additional questions

File: src/coreclr/jit/morph.cpp (hunk 8 above)
Comment (tannergooding) [reply src/coreclr/jit/morph.cpp:12082]: no, I thought I removed it, will fix.

File: src/coreclr/jit/morph.cpp (hunk 9 above)
Comment (tannergooding) [reply src/coreclr/jit/morph.cpp:6026]: It probably doesn't "need" to be. Most of the logic here is around ensuring that the SIMD/HWIntrinsic codegen is correct/optimal and isn't strictly needed when we aren't creating SIMD/HWIntrinsic nodes.

I'll update to only cover `fgMorphFieldToSimdGetElement` for simplicity, however.

File: src/coreclr/jit/morph.cpp (hunk 8 above)
Comment (tannergooding) [reply src/coreclr/jit/morph.cpp]: Removed, I had missed the one from SetElement but gotten the one in GetElement

**Review by echesakov — APPROVED** [review]
