### PR TITLE
Read public GC options if available

### LINKED ISSUE #85961: RuntimeHostConfigurationOption for GC configuration ignored in NativeAOT
### Description

as reported by @wizardars
The hardlimit in AOT doesn't work.

### Reproduction Steps

Add to project file.
```
<PropertyGroup>
    <PublishAot>true</PublishAot>
</PropertyGroup>
<ItemGroup>
	<RuntimeHostConfigurationOption Include="System.GC.HeapHardLimit" Value="100000000" />
</ItemGroup>
```
Put following code 
```
Console.WriteLine($"Total available bytes");
Console.WriteLine($"{GC.GetGCMemoryInfo(GCKind.Any).TotalAvailableMemoryBytes}!"); ; ;

Console.WriteLine($"GC configuration");
var gcConfiguration = GC.GetConfigurationVariables();
foreach (var (key, value) in gcConfiguration)
{
    Console.WriteLine($"{key}: {value}");
}
```

### Expected behavior

```
Total available bytes
4294967296!
GC configuration
ServerGC: False
ConcurrentGC: True
RetainVM: False
NoAffinitize: False
GCCpuGroup: False
GCLargePages: False
HeapCount: 1
GCHeapAffinitizeMask: 0
GCHeapAffinitizeRanges:
GCHighMemPercent: 0
GCHeapHardLimit: 4294967295
GCHeapHardLimitPercent: 0
GCHeapHardLimitSOH: 0
GCHeapHardLimitLOH: 0
GCHeapHardLimitPOH: 0
GCHeapHardLimitSOHPercent: 0
GCHeapHardLimitLOHPercent: 0
GCHeapHardLimitPOHPercent: 0
GCConserveMem: 0
GCName:
```

### Actual behavior

```
Total available bytes
17053245440!
GC configuration
ServerGC: False
ConcurrentGC: True
RetainVM: False
NoAffinitize: False
GCCpuGroup: False
GCLargePages: False
HeapCount: 1
GCHeapAffinitizeMask: 0
GCHeapAffinitizeRanges:
GCHighMemPercent: 0
GCHeapHardLimit: 4294967295
GCHeapHardLimitPercent: 0
GCHeapHardLimitSOH: 0
GCHeapHardLimitLOH: 0
GCHeapHardLimitPOH: 0
GCHeapHardLimitSOHPercent: 0
GCHeapHardLimitLOHPercent: 0
GCHeapHardLimitPOHPercent: 0
GCConserveMem: 0
GCName:
```

### Regression?

No.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by kant2002**
Also pass RuntimeHostConfigurationOption into --runtimeopt ILC parameter Fixes : #85961

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
These configuration names come from different "namespaces". Like I wrote in https://github.com/dotnet/runtime/issues/85961#issuecomment-1541415761 "We need to either add another blob with the new values, or come up with some sort of mangling so that we can store both key/value pairs in the same blob. I don't have an opinion. Whichever looks better."

The approach in this PR will run into issues as soon as there's a conflict between a "Config" name and "Knob" name. Here's how CoreCLR implements this:

https://github.com/dotnet/runtime/blob/0b5f137ab0eea82f59d22da94a0b21f0bc598f16/src/coreclr/vm/gcenv.ee.cpp#L1158-L1176

`CLRConfig::GetConfigValue` is the moral equivalent of RhConfig. It will try reading the value from embedded config or from a `DOTNET_` prefixed environment variable with that name. `Configuration::GetKnobStringValue` reads the value from the JSON on the other hand. We miss the other thing. I don't think making `CLRConfig::GetConfigValue` do the other thing is the right approach.

**Review by MichalStrehovsky — COMMENTED** [review]
Thanks for taking up the challenge!

**Comment by kant2002** [comment]
What about honoring `COMPlus_XXX` environment variables while I'm in this location?

image

**Comment by MichalStrehovsky** [comment]
We should be already honoring the `DOTNET_` prefixed ones. Reading from environment variables is the major difference between "knobs" and "switches".

**Comment by kant2002** [comment]
Yes `DOTNET_` is honored, but in the docs still exists old one `COMPLUS_`, and I thinking about adding that support for `switches` and not knobs. Just I see it is as supported (not sure for how long) and I suspect that after some time would be customer request for that.

**Comment by jkotas** [comment]
`COMPlus_` prefix for env settings is deprecated. We do not need to give it a new life in native AOT. We can add stronger wording in the docs to use `DOTNET_`.

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 1]
```diff
@@ -179,6 +191,103 @@ void RhConfig::ReadEmbeddedSettings()
...
+
+    // Config wasn't read or reading failed
+    if (g_embeddedKnobs == CONFIG_INI_NOT_AVAIL)
+    {
+        return false;
+    }
+
+    const ConfigPair* configPairs = (const ConfigPair*)g_embeddedKnobs;
+
+    // Find the first name which matches (case insensitive to be compat with environment variable counterpart)
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:210]: TODO: compare with coreclr - is this case insensitive?

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 2]
```diff
@@ -179,6 +191,103 @@ void RhConfig::ReadEmbeddedSettings()
...
+    for (int iSettings = 0; iSettings < RCV_Count; iSettings++)
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:211]: `RCV_Count` only make sense if we know the upper bound because this is not something that is user-configurable. RuntimeHostConfigurationOption is unbounded. We need to keep track of the real count. (Same comment applies to other uses of RCV_Count in this file)

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 3]
```diff
@@ -179,6 +191,103 @@ void RhConfig::ReadEmbeddedSettings()
     return;
 }
 
+bool RhConfig::GetEmbeddedKnob(_In_z_ const char* configName, _Out_ const char** configValue)
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:194]: The new methods look very similar to the existing ones. Can we share them?

Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/Runtime/RhConfig.cpp:194]: If we share, we'd delete the concept of `RCV_Count`.

File: src/coreclr/nativeaot/Runtime/gcrhenv.cpp [hunk 4]
```diff
@@ -1367,26 +1367,29 @@ bool GCToEEInterface::GetBooleanConfigValue(const char* privateKey, const char*
...
 
-    *value = uiValue != 0;
-    return true;
+    if (publicKey)
+    {
+        if (g_pRhConfig->ReadKnobValue(publicKey, &uiValue))
+        {
+            *value = uiValue != 0;
+            return true;
+        }
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/gcrhenv.cpp:1382]: This won't work for settings that specify `true`/`false`. Could you mirror how this is handled in CoreCLR?

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp (hunk 1 above)
Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/Runtime/RhConfig.cpp:210]: Whoops, that TODO was for me, but might as well dump it on you :). Can you compare how this is done in CoreCLR?

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp (hunk 3 above)
Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/Runtime/RhConfig.cpp:194]: Note that there's another PR in flight making changes here so we might want to pause for a moment to avoid conflicts. #86656 cc @elinor-fung

Comment (kant2002) [reply src/coreclr/nativeaot/Runtime/RhConfig.cpp]: I do not sure if sharing make things better, but please take a look.

File: src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets [hunk 5]
```diff
@@ -218,6 +218,7 @@ The .NET Foundation licenses this file to you under the MIT license.
       <IlcArg Include="@(DirectPInvoke->'--directpinvoke:%(Identity)')" />
       <IlcArg Include="@(DirectPInvokeList->'--directpinvokelist:%(Identity)')" />
       <IlcArg Include="@(_TrimmerFeatureSettings->'--feature:%(Identity)=%(Value)')" />
+      <IlcArg Include="@(RuntimeHostConfigurationOption->'--runtimeknobs:%(Identity)=%(Value)')" />
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets:221]:
```suggestion
      <IlcArg Include="@(RuntimeHostConfigurationOption->'--runtimeknob:%(Identity)=%(Value)')" />
```

File: src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs [hunk 6]
```diff
@@ -92,6 +92,8 @@ internal sealed class ILCompilerRootCommand : RootCommand
             new(new[] { "--feature" }, Array.Empty<string>, "Feature switches to apply (format: 'Namespace.Name=[true|false]'");
         public Option<string[]> RuntimeOptions { get; } =
             new(new[] { "--runtimeopt" }, Array.Empty<string>, "Runtime options to set");
+        public Option<string[]> RuntimeKnobs { get; } =
+            new(new[] { "--runtimeknobs" }, Array.Empty<string>, "Runtime knobs to set");
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs:96]:
```suggestion
            new(new[] { "--runtimeknob" }, Array.Empty<string>, "Runtime knobs to set");
```

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 7]
```diff
@@ -120,14 +120,23 @@ bool RhConfig::Environment::TryGetStringValue(const char* name, char** value)
...
+
 bool RhConfig::ReadConfigValue(_In_z_ const char *name, uint64_t* pValue, bool decimal)
 {
     if (Environment::TryGetIntegerValue(name, pValue, decimal))
         return true;
 
     // Check the embedded configuration
     const char *embeddedValue = nullptr;
-    if (GetEmbeddedVariable(name, &embeddedValue))
+    if (GetEmbeddedVariable(&g_embeddedSettings, &g_compilerEmbeddedSettingsBlob, name, &embeddedValue))
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:139]:
```suggestion
    if (GetEmbeddedVariable(&g_embeddedSettings, &g_compilerEmbeddedSettingsBlob, name, true, &embeddedValue))
```

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 8]
```diff
@@ -136,26 +145,50 @@ bool RhConfig::ReadConfigValue(_In_z_ const char *name, uint64_t* pValue, bool d
     return false;
 }
 
-bool RhConfig::GetEmbeddedVariable(_In_z_ const char* configName, _Out_ const char** configValue)
+bool RhConfig::ReadKnobUInt64Value(_In_z_ const char *name, uint64_t* pValue)
+{
+    const char *embeddedValue = nullptr;
+    if (GetEmbeddedVariable(&g_embeddedKnobs, &g_compilerEmbeddedKnobsBlob, name, &embeddedValue))
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:151]:
```suggestion
    if (GetEmbeddedVariable(&g_embeddedKnobs, &g_compilerEmbeddedKnobsBlob, name, false, &embeddedValue))
```

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 9]
```diff
@@ -136,26 +145,50 @@ bool RhConfig::ReadConfigValue(_In_z_ const char *name, uint64_t* pValue, bool d
...
+        return true;
+    }
+
+    return false;
+}
+
+bool RhConfig::ReadKnobBooleanValue(_In_z_ const char *name, bool* pValue)
+{
+    const char *embeddedValue = nullptr;
+    if (GetEmbeddedVariable(&g_embeddedKnobs, &g_compilerEmbeddedKnobsBlob, name, &embeddedValue))
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:163]:
```suggestion
    if (GetEmbeddedVariable(&g_embeddedKnobs, &g_compilerEmbeddedKnobsBlob, name, false, &embeddedValue))
```

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 10]
```diff
@@ -136,26 +145,50 @@ bool RhConfig::ReadConfigValue(_In_z_ const char *name, uint64_t* pValue, bool d
...
+    {
+        *pValue = strcmp(embeddedValue, "true") == 0;
+        return true;
+    }
+
+    return false;
+}
+
+bool RhConfig::GetEmbeddedVariable(void *volatile * embeddedSettings, void* compilerEmbeddedSettingsBlob, _In_z_ const char* configName, _Out_ const char** configValue)
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:172]:
```suggestion
bool RhConfig::GetEmbeddedVariable(void *volatile * embeddedSettings, void* compilerEmbeddedSettingsBlob, _In_z_ const char* configName, bool caseSensitive, _Out_ const char** configValue)
```

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 11]
```diff
@@ -136,26 +145,50 @@ bool RhConfig::ReadConfigValue(_In_z_ const char *name, uint64_t* pValue, bool d
...
     {
         return false;
     }
 
-    const ConfigPair* configPairs = (const ConfigPair*)g_embeddedSettings;
+    const ConfigPair* configPairs = (const ConfigPair*)*embeddedSettings;
 
-    // Find the first name which matches (case insensitive to be compat with environment variable counterpart)
-    for (int iSettings = 0; iSettings < RCV_Count; iSettings++)
+    // Find the first name which matches (case sensitive to be compat with CoreCLR)
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:188]:
```suggestion
    // Find the first name which matches
```

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 12]
```diff
@@ -136,26 +145,50 @@ bool RhConfig::ReadConfigValue(_In_z_ const char *name, uint64_t* pValue, bool d
...
+    for (uint32_t iSettings = 0; iSettings < ((CompilerEmbeddedSettingsBlob*)compilerEmbeddedSettingsBlob)->Size; iSettings++)
     {
-        if (_stricmp(configName, configPairs[iSettings].Key) == 0)
+        if (strcmp(configName, configPairs[iSettings].Key) == 0)
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:191]:
```suggestion
        if ((caseSensitive && strcmp(configName, configPairs[iSettings].Key) == 0)
            || (!caseSensitive && _stricmp(configName, configPairs[iSettings].Key) == 0))
```

File: src/coreclr/nativeaot/Runtime/RhConfig.h [hunk 13]
```diff
@@ -101,11 +104,11 @@ class RhConfig
     //NOTE: if the method fails configPair is left in an uninitialized state
     bool ParseConfigLine(_Out_ ConfigPair* configPair, _In_z_ const char * line);
 
-    void ReadEmbeddedSettings();
+    void ReadEmbeddedSettings(void *volatile * embeddedSettings, void* compilerEmbeddedSettingsBlob);
 
     // Gets a pointer to the embedded configuration value. Memory is held by the callee.
     // Returns true if the variable was found, false otherwise
-    bool GetEmbeddedVariable(_In_z_ const char* configName, _Out_ const char** configValue);
+    bool GetEmbeddedVariable(void *volatile * embeddedSettings, void* compilerEmbeddedSettingsBlob, _In_z_ const char* configName, _Out_ const char** configValue);
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.h:111]:
```suggestion
    bool GetEmbeddedVariable(void *volatile * embeddedSettings, void* compilerEmbeddedSettingsBlob, _In_z_ const char* configName, bool caseSensitive, _Out_ const char** configValue);
```

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

**Comment by kant2002** [comment]
Looks like you are tired to babysit me 😄  thank you!

**Comment by MichalStrehovsky** [comment]
> Looks like you are tired to babysit me 😄 thank you!

It was already close enough that we could avoid another round :). Thanks!
