### PR TITLE
Fix JIT using too wide indirections when returning small structs

### LINKED ISSUE #58874: JIT uses too wide reads for small returned structs
For
```csharp
using System.Runtime.CompilerServices;

class Program
{
    static void Main(string[] args)
    {
        Test t = default;
        Foo(ref t);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static Test Foo(ref Test t)
        => t;
}

struct Test
{
    public byte A, B;
}
```
we generate:
```asm
; Assembly listing for method Program:Foo(byref):Test
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; No PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  3,  3   )   byref  ->  rcx         single-def
;# V01 OutArgs      [V01    ] (  1,  1   )  lclBlk ( 0) [rsp+00H]   "OutgoingArgSpace"
;
; Lcl frame size = 0

G_M39029_IG01:              ;; offset=0000H
                                                ;; bbWeight=1    PerfScore 0.00
G_M39029_IG02:              ;; offset=0000H
       8B01                 mov      eax, dword ptr [rcx]
                                                ;; bbWeight=1    PerfScore 2.00
G_M39029_IG03:              ;; offset=0002H
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.00

; Total bytes of code 3, prolog size 0, PerfScore 3.30, instruction count 2, allocated bytes for code 3 (MethodHash=7e33678a) for method Program:Foo(byref):Test
; ============================================================
```

It means for instance that the following program (usually) throws `AccessViolationException`:
```csharp
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

unsafe class Program
{
    static void Main(string[] args)
    {
        IntPtr page = VirtualAlloc(IntPtr.Zero, 0x1000, 0x1000 | 0x2000, 0x04);
        ref Test validRef = ref *(Test*)(page + 0x1000 - sizeof(Test));
        validRef = default;
        Foo(ref validRef);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static Test Foo(ref Test t)
        => t;

    [DllImport("kernel32")]
    public static extern IntPtr VirtualAlloc(IntPtr lpAddress, nuint dwSize, uint flAllocationType, uint flProtect);
}

struct Test
{
    public byte A, B;
}
```

### LINKED ISSUE #64802: Wrong code generation for Unsafe.AsRef<T>, Read<T> when T is a structure
### Description

Looks like JIT doesn't properly evaluate the size of a structure when emitting Unsafe.AsRef<T> for structures less than 4 bytes consisting of a single primitive type field. I have structure, storing ushort in it and sometimes get AccessViolationException when trying to read it from the memory. 

I created a[ gist in sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ZEMfKhKV6mpsayAFtihiAMtmDtufARuo0GDDQA2rIYUBxgGG4AnhAcGAAUMXEYANK8XAAmLPIAjhwwetiSaAwACthgANYMALwM5ACUALqaAMwMuGERGAwAQtEYMKHhkTQA3v5MHcCDMAz40QBqxQW+AL421CHdkcnxSdix8elZOTD5hXzFpRXVdQ0t7Z27vQ7QGCM9E1PEHbj2D4LZarGAbLY7UZRI4pQ7HNIZbJ5ApFErlSo1epNVq0f6vBhGT6vH7UAJ/BgZXqLFaSNY0TZ+bZfPYwg77BFnZFXXg3dH3LFPXEvKEMFwQLgAc2ZGBJZI6knFEuBNLp1AZzzI2gA7AxJtQAJBBABSvAwAHFCjJlAkMNExDAIAAzBKzIaNRqlE3my1Qa22+1OhIDIbS904w1ei1cK1gG12h3OgEfd2e01RmNxgPO95QIlQsM0CNpn1++OBykphiRkux/0JhKE0OCove6O+2tl50KyWV6tt0tZpKKpvhwvk5hIBjcXDYR3zAAqDAtGAAPPOAHwJYgoABUDGwjV1hf1TB1AFUuDO5ywAIK4NgwR1rzcHtQBd8BQvrD/0mhAA=) to illustrate the case.

### Reproduction Steps

```
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct ShortStruct
{
  public short myValue;
}

public class Program {
	public static unsafe T Get<T>(void* a) {
		 return Unsafe.AsRef<T>(a);       
	}

        public unsafe static void Main() {
            int a = 1;
            var x = Get<ShortStruct>(&a);
            Console.WriteLine(x);
        }
}
```

### Expected behavior

I expect 2 bytes will be read and the generated code be equivalent to 
```
Program.Get[[System.Int16, System.Private.CoreLib]](Void*)
    L0000: movsx rax, word ptr [rcx]
    L0004: ret
```

### Actual behavior

It actually tries to read 4 bytes
```
Program.Get[[ShortStruct, _]](Void*)
    L0000: mov eax, [rcx]
    L0002: ret
```

### Regression?

Yes, if I switch the target to .NET Framework (x64) in that sharplab.io gist - everything is generating correctly
```
Program.Get[[System.Int16, mscorlib]](Void*)
    L0000: mov rax, rcx
    L0003: movsx rax, word [rax]
    L0007: ret

Program.Get[[ShortStruct, _]](Void*)
    L0000: mov rax, rcx
    L0003: movsx rax, word [rax]
    L0007: ret
```

### Known Workarounds

_No response_

### Configuration

At least .NET 6.0 (x64) is affected

### Other information

_No response_

### LINKED ISSUE #68157: Dereferencing a pointer to a byte-sized structure reads a DWORD
### Description

We have a structure containing one byte, as follows:

```
struct Byte
{
    private readonly byte Value;
}
```

Both sizeof and Marshal.SizeOf return 1 for this structure, as expected. 

However, dereferencing a pointer (or a ref) to this structure causes JIT to emit a MOV DWORD, rather than MOV BYTE. 

We have a real-world case where the pointer points to a chunk of unmanaged memory, and this results in a read past the boundary of allocated memory. 

Substituting the structure for a byte produces a MOV BYTE.

### Reproduction Steps

Given this:

```
struct Byte
{
    private readonly byte Value;
}

class Test
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static unsafe Byte* GetStructPtr() => null; //Implementation of the method is irrelevant
    public static unsafe Byte GetStructValue() => *GetStructPtr();
}

Test.GetStructValue();

```

The JIT produces this:

```
public static unsafe Byte GetStructValue() => *GetStructPtr();
00007FFA96CF8EC0  push        rbp  
00007FFA96CF8EC1  sub         rsp,20h  
00007FFA96CF8EC5  lea         rbp,[rsp+20h]  
00007FFA96CF8ECA  call        Method stub for: Test.GetStructPtr() (07FFA96CF8390h)  
00007FFA96CF8ECF  mov         eax,dword ptr [rax]  
```

### Expected behavior

The JIT should emit code to read a single byte.

### Actual behavior

The JIT emits code reading a DWORD.

### Regression?

_No response_

### Known Workarounds

Substitute the structure for a byte.

### Configuration

.NET 6
Windows
x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #58874
Fix #64802
Fix #68157

We should backport this given the two customer reports.

### CODE REVIEW

File: src/tests/JIT/Regression/JitBlue/Runtime_58874/Runtime_58874.cs [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+            // Commit first page
+            mem = VirtualAlloc(pages, 0x1000, MEM_COMMIT, PAGE_READWRITE);
+            if (mem != pages)
+            {
+                return 100;
+            }
+        }
+        else
+        {
+            mem = NativeMemory.Alloc(0x1000);
```
Comment (EgorBo) [inline src/tests/JIT/Regression/JitBlue/Runtime_58874/Runtime_58874.cs:33]: just curious - is this enough to reproduce the issue on non-windows platforms?

Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_58874/Runtime_58874.cs:33]: No, this will not guarantee repro for non-Windows. But given the JIT code with the bug is platform agnostic I think it is ok to only have guaranteed coverage on Windows instead of special casing the test for more platforms.

Comment (EgorBo) [reply src/tests/JIT/Regression/JitBlue/Runtime_58874/Runtime_58874.cs:33]: I agree, was just curious if there an easy way to reproduce it on linux, in theory we can use MemoryMappedFile API

**Review by EgorBo — APPROVED** [review]

File: src/tests/JIT/Regression/JitBlue/Runtime_58874/Runtime_58874.cs (hunk 1 above)
Comment (jakobbotsch) [reply src/tests/JIT/Regression/JitBlue/Runtime_58874/Runtime_58874.cs:33]: Hmm, looks like `MemoryMappedFile` commits the entire range immediately, but we could probably increase our changes by using it.
I suppose the "really correct way" would be to pinvoke `mmap` and `mprotect` on Linux platforms.

File: src/coreclr/jit/lower.cpp [hunk 2]
```diff
@@ -3644,15 +3644,15 @@ void Lowering::LowerRetStruct(GenTreeUnOp* ret)
     assert(ret->OperIs(GT_RETURN));
     assert(varTypeIsStruct(ret));
 
-    GenTree* retVal = ret->gtGetOp1();
+    GenTree*  retVal           = ret->gtGetOp1();
+    var_types nativeReturnType = comp->info.compRetNativeType;
     // Note: small types are returned as INT.
```
Comment (Tornhoof) [inline src/coreclr/jit/lower.cpp:3649]: Is that comment still correct with your changes?

Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:3649]: should be still relevant, the following `genActualType` should upscale all small-types to int

Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp:3649]: Right, there are two nodes here, the return and the operand of the return. The return is still wide but the bug was that we were retyping the operand, which is wrong.

**Comment by jakobbotsch** [comment]
Failure is https://github.com/dotnet/arcade/issues/9088
