### PR TITLE
JIT: Set GTF_ORDER_SIDEEFF for some nodes with invisible dependencies

### LINKED ISSUE #78554: Arm64: If Conversion can bypass overflow checks
This issue was spotted as part of PR https://github.com/dotnet/runtime/pull/77728

```
    [MethodImplAttribute(MethodImplOptions.NoInlining)]
    static void lenfail(uint[] a, uint i)
    {
        if (i < a.Length)
	 {
           i = a[i];
	 }
	Consume(i,i+2);
    }

    static void Main(string[] args)
    {
	 var arr = new uint[] { 1, 42, 3000 };
	 lenfail(arr,0xffffffff);
    }
```
With the following set:
```
export DOTNET_TieredCompilation=0
export DOTNET_JitStressModeNames=STRESS_IF_CONVERSION_COST
export DOTNET_JITMinOpts=0
```
Get error:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CSharpTutorials.Program.lenfail(UInt32[], UInt32)
   at CSharpTutorials.Program.Main(System.String[])
[1]    2099041 abort (core dumped)   ./bin/release/net7.0/linux-arm64/conditional.dll
```

Why? The load from `a[i]` should only happen if the `if` condition holds. With If Conversion, the load is effectively hoisted outside `if` and is always executed.

This is the Assignment block the If Conversion sees. There are no flags here to indicate moving the `ASG` before the compare is unsafe. Even more worrying, the `IND` is marked as `GTF_IND_NONFAULTING`.
```
STMT00003 ( 0x008[E-] ... 0x00B )
N012 ( 10, 12) [000018] -A--G---R--                         *  ASG       int    $145
N011 (  1,  1) [000017] D------N---                         +--*  LCL_VAR   int    V01 arg1         d:3 $VN.Void
N010 ( 10, 12) [000031] n---G--N---                         \--*  IND       int    <l:$183, c:$c2>
N009 (  7, 10) [000029] -----------                            \--*  ARR_ADDR  byref int[] $2c0
N008 (  7, 10) [000028] -------N---                               \--*  ADD       byref  $201
N003 (  3,  4) [000027] -----------                                  +--*  ADD       byref  $200
N001 (  1,  1) [000019] -----------                                  |  +--*  LCL_VAR   ref    V00 arg0         u:1 (last use) $80
N002 (  1,  2) [000026] -----------                                  |  \--*  CNS_INT   long   16 $1c0
N007 (  4,  6) [000025] -----------                                  \--*  LSH       long   $241
N005 (  2,  3) [000023] ---------U-                                     +--*  CAST      long <- uint $240
N004 (  1,  1) [000020] -----------                                     |  \--*  LCL_VAR   int    V01 arg1         u:1 (last use) $c0
N006 (  1,  2) [000024] -------N---                                     \--*  CNS_INT   long   2 $1c1
```

Not quite sure yet on what needs to be fixed earlier on

### PR DESCRIPTION
**Pull request by jakobbotsch**
We have a few places where we create the pattern "COMMA(some check, some value)". In some of these cases there may not be any visible dependency (e.g. use of a defined value) which makes the dependency invisible to the JIT.

If the value is safe to compute only because of the check (for example, a bounds check + indexing operation), and if the value otherwise has no side effects, then nothing prevented the backend or optimizations from reordering these nodes.

A particular problem we may have is around array indexing and bounds checks. Creating an arbitrary illegal byref is not allowed, but to the JIT this node is just a normal node that is completely free of any side effects. Before this change nothing was preventing us from reordering the bounds checks with the computation of the array element.

Fix #78554

### CODE REVIEW

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -5190,6 +5194,8 @@ GenTree* Compiler::fgMorphExpandInstanceField(GenTree* tree, MorphAddrContext* m
         GenTree* lclVar  = gtNewLclvNode(lclNum, objRefType);
         GenTree* nullchk = gtNewNullCheck(lclVar, compCurBB);
 
+        nullchk->gtFlags |= GTF_ORDER_SIDEEFF;
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:5197]: This probably makes #71435 possible again.

**Comment by a74nh** [comment]
Is it worth adding the test case from https://github.com/dotnet/runtime/pull/78561 ?

**Comment by jakobbotsch** [comment]
> Is it worth adding the test case from #78561 ?

Yep, will do that

**Comment by jakobbotsch** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90932&view=ms.vss-build-web.run-extensions-tab) were not as bad as I would've feared. The change to check `GTF_ORDER_SIDEEFF` in if-conversion was the most impactful and we can special case it for invariant nodes/locals, which avoids most of those regressions.

Other than that regressions fell into these categories:
* The introduced `GTF_ORDER_SIDEEFF` on indirections sometimes now disallows RBO from duplicating nodes. It is questionable that we are doing this in the first place, I have opened #78713 about it.
* Setting GTF_ORDER_SIDEEFF on an indir that was the source of a block store would block containment of the source address. Submitted #78763 for this, will push other changes to this PR after this is merged.
* Rarely, the new `GTF_ORDER_SIDEEFF` is propagated to some node that ends up pure later (e.g. due to CSE). This may block address mode creation and other containment that was previously allowed.

**Comment by jakobbotsch** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=92166&view=ms.vss-build-web.run-extensions-tab) are pretty minimal now, the larger xarch ones are in some of the massive cse tests.

This should unblock #77728.

cc @dotnet/jit-contrib @a74nh PTAL @EgorBo @SingleAccretion

File: src/tests/JIT/Regression/JitBlue/Runtime_78554/Runtime_78554.cs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Runtime.CompilerServices;
+
+public class Runtime_78554
+{
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    static void Consume(uint op)
+    {
+        return;
```
Comment (jakobbotsch) [inline src/tests/JIT/Regression/JitBlue/Runtime_78554/Runtime_78554.cs:11]:
```suggestion
```

File: src/coreclr/jit/importer.cpp [hunk 3]
```diff
@@ -9696,6 +9696,7 @@ void Compiler::impImportBlockCode(BasicBlock* block)
                     }
                     if (helperNode != nullptr)
                     {
+                        helperNode->gtFlags |= GTF_ORDER_SIDEEFF;
```
Comment (SingleAccretion) [inline src/coreclr/jit/importer.cpp:9699]: Why do we need to set the ordering effect on these?

The calls should not be reorderable with `GTF_GLOB_REF`-tagged field static access by themselves.

File: src/coreclr/jit/importer.cpp [hunk 4]
```diff
@@ -10462,7 +10464,8 @@ void Compiler::impImportBlockCode(BasicBlock* block)
                                 GenTree* boxPayloadAddress =
                                     gtNewOperNode(GT_ADD, TYP_BYREF, cloneOperand, boxPayloadOffset);
                                 GenTree* nullcheck = gtNewNullCheck(op1, block);
-                                GenTree* result    = gtNewOperNode(GT_COMMA, TYP_BYREF, nullcheck, boxPayloadAddress);
+                                nullcheck->gtFlags |= GTF_ORDER_SIDEEFF;
+                                GenTree* result = gtNewOperNode(GT_COMMA, TYP_BYREF, nullcheck, boxPayloadAddress);
```
Comment (SingleAccretion) [inline src/coreclr/jit/importer.cpp:10468]: It is not obvious what the ordering effect here protects against -- what would a theoretical example of bad transformation look like?

Comment (jakobbotsch) [reply src/coreclr/jit/importer.cpp:10468]: I think I can revert this one too given that `boxPayloadAddress` is known to be very small when `cloneOperand` is null.
If it wasn't then early prop would probably be able to do something illegal here if it removed this null check due to an upcoming null check, causing us to form some random byref.

Comment (jakobbotsch) [reply src/coreclr/jit/importer.cpp:10468]: Hmm, I'm not sure after all. Without setting this then if we did the optimization in #71435 we could potentially remove these null checks and turn a NRE into an AV when accessing a field right around the explicit null check threshold. Consider something like:
```scala
ASG
  LCL_VAR byref V00
  COMMA byref           // added here
    NULLCHECK            // node A
      LCL_VAR ref V01
    ADD byref
      LCL_VAR ref V01
      CNS_INT long 8

ASG
  LCL_VAR int V02
  IND int               // node B
    ADD
      LCL_VAR byref V00
      CNS_INT long 0xFFFC

ASG
  LCL_VAR int V03
  IND int             // node C
    LCL_VAR ref V01
```

The optimization would reason as follows: the node A null check is unnecessary because node B only has the same side effects as the null check (throwing NRE), and node C subsumes node A. However, node B will actually AV without node A.

Comment (SingleAccretion) [reply src/coreclr/jit/importer.cpp:10468]: I would classify this as the optimization being wrong, since we can only consider NRE to be "true" NRE and not "NRE but maybe AV" with small offsets (we do the checks against the max null check offset in other places to differentiate these two cases, though not everywhere).

More fundamentally, fixing this with an ordering effect seems... arbitrary? What is the ordering dependency?

Comment (SingleAccretion) [reply src/coreclr/jit/importer.cpp:10468]: We've talked with @jakobbotsch on Discord and concluded the ordering here is needed because "almost null" byrefs must never occur on dynamically reachable paths, so swapping the `ADD` with the null check would effectively introduce UB into the program.

**Comment by jakobbotsch** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=92604&view=ms.vss-build-web.run-extensions-tab) after setting `GTF_ORDER_SIDEEFF` on both operands of the commas are still pretty minimal, with the larger diffs still being test only.

@EgorBo Can you take a look and approve if it looks ok to you?

File: src/coreclr/jit/importer.cpp (hunk 4 above)
Comment (a74nh) [reply src/coreclr/jit/importer.cpp]: > It has also been determined that our handling around `GTF_ORDER_SIDEEFF` is a bit lacking, and it's meaning a bit unclear. We've settled on the "only fully side-effect-less nodes can be reordered with ordered nodes"

It might be useful to add the meaning as a comment. Maybe next to the definition in gentree.h? The current "sub-expression has a re-ordering side effect" is a little lacking.

Comment (jakobbotsch) [reply src/coreclr/jit/importer.cpp]: I agree we should have some more detailed docs on what the effect flags mean and how they are assumed to be set, but I think it would be better to add a section in https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/jit/ryujit-tutorial.md and refer to that. I will aim to do a write-up of that soon.

Comment (a74nh) [reply src/coreclr/jit/importer.cpp]: ok, I'm happy with that.

**Review by EgorBo — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Failures are #78912 #78909
