### PR TITLE
[release/6.0][wasm] Add support for native relinking after Build, and AOT after publish 

### LINKED ISSUE #53612: If you build with trimming enabled, future builds with it disabled will produce incorrect output
### Description

cc @radical 

If I do an incremental build with ```EnableAggressiveTrimming=true```, then do another one later with it ```=false``` after changing some .cs files, not everything is rebuilt so you get outputs that have type load failures and such, like so:

```fail: console.error: Unhandled exception in _finalize_startup Error: System.TypeLoadException: Could not load type of field 'System.Runtime.InteropServices.JavaScript.Runtime:_boundObjects' (0) due to: Could not resolve type with token 01000012 from typeref```

Obliterating my artifacts folder and then doing a full build is usually the fix for this.

Will come back and paste in my exact build command lines later once my rebuild is done.

### Configuration

dotnet/runtime/main current as of today

### Regression?

No

### LINKED ISSUE #58973: [wasm] Avoid unnecessary linking after `Build`, when publishing from VS
VS uses `$(DeployOnBuild)==true` when publishing

### PR DESCRIPTION
**Pull request by radical**
Wasm app build can run in two scenarios:

1. For build, eg. when running the app in VS, or `dotnet build foo.csproj`
2. For Publish, eg, when publishing the app to a folder, or Azure

A dotnet wasm app has some native wasm files (`dotnet.wasm`, and `dotnet.js`). How these files are obtained, or generated:

- Build
    - with no native libraries referenced (AOT setting is ignored here)
        - files from the runtime pack are used as-is
    - with native libraries referenced
        - dotnet.wasm is relinked with the native libraries

- Publish
    - dotnet.wasm is relinked with the native libraries, and updated pinvoke/icalls from the trimmed assemblies
    - if `RunAOTCompilation=true`, then the relinking includes AOT'ed assemblies

## `Build`

Implementation:

- Target `WasmBuildApp`
- runs after `Build` by default
    - which can be disabled by `$(DisableAutoWasmBuildApp)`
    - or the run-after target can be set via `$(WasmBuildAppAfterThisTarget)`

- To run a custom target
    - *before* any of the wasm build targets, use `$(WasmBuildAppDependsOn)`, and prepend your target name to that
    - *after* any of the wasm build targets, use `AfterTargets="WasmBuildApp"` on that target
- Avoid depending on this target, because it is available only when the workload is installed. Use `$(WasmNativeWorkload)` to check if it is installed.

## `Publish`

Implementation:

- This part runs as a nested build using a `MSBuild` task, which means that the project gets reevaluated. So, if there were any changes made to items/properties in targets before this, then they won't be visible in the nested build.
- By default `WasmTriggerPublishApp` runs after the `Publish` target, and that triggers the nested build
    - The nested build runs `WasmNestedPublishApp`, which causes `Build`, and `Publish` targets to be run
    - Because this causes `Build` to be run again, if you have any targets that get triggered by that, then they will be running twice.
        - But the original *build* run, and this *publish* run can be differentiated using `$(WasmBuildingForPublish)`

- `WasmTriggerPublishApp` essentially just invokes the nested publish
    - This runs after `Publish`
        - which can be disabled by `$(DisableAutoWasmPublishApp)`
        - or the run-after target can be set via `$(WasmTriggerPublishAppAfterThisTarget)`

    - To influence the wasm build for publish, use `WasmNestedPublishApp`
        - To run a custom target before it, use `$(WasmNestedPublishAppDependsOn)`
        - to run a custom target *after* it, use `AfterTargets="WasmNestedPublishApp"`

    - If you want to *dependsOn* on this, then use `DependsOnTargets="WasmTriggerPublishApp"`

- Fixes dotnet#56783
- Fixes dotnet#53612
- Fixes dotnet#58973

- Also fixes building for AOT with trimming disabled
Fixes dotnet#53804

### CODE REVIEW

**Comment by radical** [comment]
wasm test failure is https://github.com/dotnet/runtime/issues/58202:

```
[10:07:48] fail: [out of order message from the browser]: http://127.0.0.1:32993/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:32993/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[10:07:48] fail: [out of order message from the browser]: http://127.0.0.1:32993/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:40283/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[10:07:48] info: http://127.0.0.1:32993/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:39461/' failed: WebSocket is closed before the connection is established.
[10:07:48] info: http://127.0.0.1:32993/dotnet.js 0 WebSocket connection to 'ws://24ec1fbf05574cd4b5be6f210fbbe53d/' failed: WebSocket is closed before the connection is established.
[10:07:49] info: http://127.0.0.1:32993/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:32993/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[10:07:49] info: http://127.0.0.1:32993/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:40283/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[10:07:50] info: http://127.0.0.1:32993/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:32993/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[10:07:50] info: http://127.0.0.1:32993/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:40283/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[10:08:37] fail: [FAIL] System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.ReceiveAsync_MultipleOutstandingReceiveOperations_Throws(server: ws://127.0.0.1:32993/WebSocket/EchoWebSocket.ashx)
[10:08:37] info: Closed state when OperationCanceledException
[10:08:37] info: Expected: True
[10:08:37] info: Actual:   False
[10:08:37] info:    at System.Net.WebSockets.Client.Tests.SendReceiveTest.ReceiveAsync_MultipleOutstandingReceiveOperations_Throws(Uri server)
[10:08:37] info: --- End of stack trace from previous location ---
[10:12:05] info: Finished:    System.Net.WebSockets.Client.Tests.dll
```

File: src/tasks/AotCompilerTask/MonoAOTCompiler.cs [hunk 1]
```diff
@@ -280,46 +287,69 @@ public override bool Execute()
...
+            throw new LogAsErrorException($"'{nameof(UseDirectPInvoke)}' can only be used with '{nameof(UseStaticLinking)}=true'.");
         }
 
         if (UseStaticLinking && (parsedOutputType == MonoAotOutputType.Library))
         {
-            throw new ArgumentException($"'{nameof(OutputType)}=Library' can not be used with '{nameof(UseStaticLinking)}=true'.", nameof(OutputType));
+            throw new LogAsErrorException($"'{nameof(OutputType)}=Library' can not be used with '{nameof(UseStaticLinking)}=true'.");
+        }
+
+        return true;
```
Comment (jonathanpeppers) [inline src/tasks/AotCompilerTask/MonoAOTCompiler.cs:328]: You might change this to:
```suggestion
        return !Log.HasLoggedErrors;
```

Just in case something in here logged an error, and it still got here.

**Review by marek-safar — APPROVED** [review]
