### PR TITLE
Fix for x86 stublinker handling of optimized GC descs

### LINKED ISSUE #84694: [Fuzzlyn] x86 assertion in stublinker
# 1 distinct assertion errors seen
## (4 occurrences) cnt < 0
Example occurrence:
```scala
Assert failure(PID 688 [0x000002b0], Thread: 1876 [0x0754]): cnt < 0



CORECLR! GetCLRRuntimeHost + 0x405330 (0x6fabc600)

CORECLR! <no symbol> + 0x0 (0x6f6346f8)

CORECLR! GetCLRRuntimeHost + 0x314250 (0x6f9cb520)

CORECLR! <no symbol> + 0x0 (0x6f635f75)

CORECLR! GetCLRRuntimeHost + 0x107083 (0x6f7be353)

CORECLR! GetCLRRuntimeHost + 0x10E040 (0x6f7c5310)

CORECLR! GetCLRRuntimeHost + 0x461A42 (0x6fb18d12)

<no module>! <no symbol> + 0x0 (0x123885f7)

CORECLR! GetCLRRuntimeHost + 0x461761 (0x6fb18a31)

CORECLR! GetCLRRuntimeHost + 0x18F10C (0x6f8463dc)

    File: D:\a\_work\1\s\src\coreclr\vm\i386\stublinkerx86.cpp Line: 4545

    Image: C:\h\w\A98B09C9\p\CoreRoot\corerun.exe
```
Affected seeds:
* `1040430091043430044`
* `4095131877698125812`
* `10289308730348979979`
* `14657980860939580024`

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #84694

x86 stublinker expected that an array of structs could not have "all pointers" GC desc. 
It is possible now if the element is an "all pointers" struct.

### CODE REVIEW

**Comment by VSadov** [comment]
It is better to look at changes in "ignore whitespace" mode. It is really a very small change, but something makes the diff not able to align.

File: src/tests/Regressions/coreclr/GitHub_84694/test84694.cs [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    public S0(C0 f1) : this()
+    {
+    }
+}
+
+public class Program
+{
+    public static int Main()
+    {
+        var vr4 = new S0[,] { { new S0(new C0()) } };
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_84694/test84694.cs:23]:
```suggestion
        GC.KeepAlive(new S0[,] { { new S0(new C0()) } });
```
to make sure that the JIT won't optimize out the allocation

File: src/tests/Regressions/coreclr/GitHub_84694/test84694.cs [hunk 2]
```diff
@@ -0,0 +1,26 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System;
+
+public class C0
+{
+}
+
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_84694/test84694.cs:9]:
```suggestion
```
This can be just replaced with `object`.

File: src/coreclr/vm/i386/stublinkerx86.cpp [hunk 3]
```diff
@@ -4541,29 +4541,43 @@ VOID StubLinkerCPU::EmitArrayOpStub(const ArrayOpScript* pArrayOpScript)
...
-                        for (SSIZE_T __i = 0; __i > cnt; __i--)
+                        _ASSERTE(cnt < 0 || cnt == 1);
+                        if (cnt == 1)
                         {
-                            HALF_SIZE_T skip =  cur->val_serie[__i].skip;
-                            HALF_SIZE_T nptrs = cur->val_serie[__i].nptrs;
-                            total += nptrs*sizeof (DWORD*);
-                            do
+                            // all pointers
+                            for (size_t i = 0; i < size; i += sizeof(DWORD*))
```
Comment (jkotas) [inline src/coreclr/vm/i386/stublinkerx86.cpp:4549]:
```suggestion
                            for (size_t i = 0; i < size; i += sizeof(Object*))
```
More self-explanatory

Comment (VSadov) [reply src/coreclr/vm/i386/stublinkerx86.cpp:4549]: this file has no consistency on the matter of pointer sizes - some code above uses `sizeof(void*)`, some code closer to here uses `DWORD*`, so I chose that, although `DWORD*` is indeed a bit unusual.

The formatting style ( i.e. `total += nptrs*sizeof (DWORD*);` ) looks like this code might be pretty old code.

File: src/coreclr/vm/i386/stublinkerx86.cpp [hunk 4]
```diff
@@ -4541,29 +4541,43 @@ VOID StubLinkerCPU::EmitArrayOpStub(const ArrayOpScript* pArrayOpScript)
                         total += cur->startoffset - elemOfs;
 
                         SSIZE_T cnt = (SSIZE_T) pArrayOpScript->m_gcDesc->GetNumSeries();
-                        // special array encoding
-                        _ASSERTE(cnt < 0);
 
-                        for (SSIZE_T __i = 0; __i > cnt; __i--)
+                        _ASSERTE(cnt < 0 || cnt == 1);
```
Comment (VSadov) [inline src/coreclr/vm/i386/stublinkerx86.cpp:4545]: also this assert is redundant

**Review by jkotas — APPROVED** [review]
LGTM!

**Comment by VSadov** [comment]
Thanks!!
