### PR TITLE
[browser] fix loading assets

### LINKED ISSUE #89510: [browser] single file JavaScript and custom loader
### Description

I'm attempting to run `browser-wasm` with a minimal custom config under .NET 8:

```js
import { dotnet } from './dotnet.js'

const config = {
    "mainAssemblyName": "Test.dll",
    "assemblyRootFolder": "managed",
    "assets": [
	    {
	      "behavior": "dotnetwasm",
	      "name": "dotnet.native.wasm",
	    },
	    {
	      "behavior": "js-module-native",
	      "name": "dotnet.native.js",
	    },
	    {
	      "behavior": "js-module-dotnet",
	      "name": "dotnet.js",
	    },
	    {
	      "behavior": "js-module-runtime",
	      "name": "dotnet.runtime.js",
	    },
	    {
	      "behavior": "assembly",
	      "name": "System.Console.wasm",
	    },
	    {
	      "behavior": "assembly",
	      "name": "System.Linq.wasm",
	    },
	    {
	      "behavior": "assembly",
	      "name": "System.Private.CoreLib.wasm",
	    },
	    {
	      "behavior": "assembly",
	      "name": "Test.wasm",
	    }
    ]
};
const runtime = await dotnet.withConfig(config).create();
```
But getting nullref here: https://github.com/dotnet/runtime/blob/v8.0.0-preview.6.23329.7/src/mono/wasm/runtime/loader/assets.ts#L145C28

It worked in .NET 7 fine before.

### Reproduction Steps

Publish `browser-wasm` and try running it with a custom config under "AppBundle" dir.

### Expected behavior

No errors.

### Actual behavior

Error in mono_download_assets: TypeError: pendingDownloadInternal is null

### Regression?

Yes, it worked in .NET 7.

### Known Workarounds

None.

### Configuration

.NET v8.0.0-preview.6.23329.7
Windows 10
Local http server under AppBundle dir with `serve` under powershell.

### Other information

_No response_

### LINKED ISSUE #89570: [browser] "Expected asset to have the downloaded buffer" assert fails when specifying "buffer" in MonoConfig
### Description

In an attempt to work around #89510 I've tried loading the assets manually and set them to `buffer` of `MonoConfig`, but it throws on this assert: https://github.com/dotnet/runtime/blob/v8.0.0-preview.6.23329.7/src/mono/wasm/runtime/loader/assets.ts#L159

Sorry if I'm missing something obvious, but is there any way at all to run browser app  in .NET 8? 

### Reproduction Steps

Build and attempt running a minimal `browser-wasm` app as follows:

```js
import { dotnet } from "./dotnet.js";

(async function () {
    const config = {
        mainAssemblyName: "Test.dll",
        assemblyRootFolder: "managed",
        assets: [
            {
                behavior: "dotnetwasm",
                buffer: await fetchBinary("dotnet.native.wasm"),
                name: "dotnet.native.wasm"
            },
            {
                behavior: "js-module-native",
                name: "dotnet.native.js"
            },
            {
                behavior: "js-module-runtime",
                name: "dotnet.runtime.js"
            },
            {
                behavior: "assembly",
                buffer: await fetchBinary("System.Console.wasm"),
                name: "System.Console.wasm"
            },
            {
                behavior: "assembly",
                buffer: await fetchBinary("System.Private.CoreLib.wasm"),
                name: "System.Private.CoreLib.wasm"
            },
            {
                behavior: "assembly",
                buffer: await fetchBinary("Test.wasm"),
                name: "Test.wasm"
            }
        ]
    };
    const runtime = await dotnet.withConfig(config).create();
})();

async function fetchBinary(name) {
    const uri = `./managed/${name}`;
    return new Uint8Array(await (await fetch(uri)).arrayBuffer());
}
```

### Expected behavior

`dotnet.js` initializes with the provided pre-loaded binary assets.

### Actual behavior

`Error in mono_download_assets: Error: Assert failed: Expected asset to have the downloaded buffer` is thrown.

### Regression?

Yes, it worked in .NET 7.

### Known Workarounds

None.

### Configuration

.NET v8.0.0-preview.6.23329.7
Windows 10
Local http server under AppBundle dir with serve under powershell.

### Other information

_No response_

### LINKED ISSUE #89766: Breaking change in WebAssembly loadBootResource
The change in PR #89435 (merged a few days ago) appears not to be back-compatible and is probably causing the SDK ingestion https://github.com/dotnet/aspnetcore/pull/49704 to fail.

Specifically, when calling the application's `loadBootResource` callback, it now passes different values for the `type` parameter, and imposes new rules that are stricter than we had in the past. Existing applications' `loadBootResource` implementations may not support these new types/rules.

As a concrete example, see the Blazor docs at https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0. This page contains the following code sample:

```html
<script src="_framework/blazor.webassembly.js" autostart="false"></script>
<script>
  Blazor.start({
    loadBootResource: function (type, name, defaultUri, integrity) {
      if (type == 'dotnetjs') {
        return null;
      } else {
        return fetch(defaultUri, {
          cache: 'no-cache',
          integrity: integrity,
          headers: { 'Custom-Header': 'Custom Value' }
        });
      }
    }
  });
</script>
```

This works with 7.0, but will break after PR #89435 because the runtime now supplies the new type name `js-module-runtime`, which is not a documented type. The logic above will perform a `fetch` request for the resource, since the only documented type that can't be fetched is `dotnetjs`. Then the runtime will reject the value, giving the exception message *For a js-module-runtime resource, custom loaders must supply a URI string*. This is one of the build failures at https://github.com/dotnet/aspnetcore/runs/15504558324

### Proposed resolution

For any resource type that you don't accept a `Promise<Response>` value, use the type name `dotnetjs` for back-compat. Avoid adding new type names that impose stricter rules than existed before.

cc @pavelsavara @maraf @lewing

### PR DESCRIPTION
**Pull request by pavelsavara**
- make sure that we resolve URLs from `loadBootResource` to absolute URL with `document.baseURI`
   - added `makeURLAbsoluteWithApplicationBase`
   - add new last parameter to `loadBootResource` call with runime behavior type, 
   - removed double call to `loadBootResource`
- add `manifest`, `js-module-dotnet` to `AssetBehaviors`
- add `WebAssemblyBootResourceType` back to `dotnet.d.ts`
- rename `jsSymbols` to `wasmSymbols`, this was a mistake
- added `browser-minimal-config` sample
- fix merging config
- fix loading from legacy `config.assets`

Fixes https://github.com/dotnet/runtime/issues/89510
Fixes https://github.com/dotnet/runtime/issues/89570
Fixes https://github.com/dotnet/runtime/issues/89766

### CODE REVIEW

File: src/mono/sample/wasm/browser-advanced/main.js [hunk 1]
```diff
@@ -52,6 +52,10 @@ try {
             },
             postRun: () => { console.log('user code Module.postRun'); },
         })
+        .withResourceLoader((type, name, defaultUri, integrity, behavior) => {
+            // loadBootResource could return string with unqualified name of resource. It assumes that we resolve it with document.baseURI
+            return `${name}`;
```
Comment (kg) [inline src/mono/sample/wasm/browser-advanced/main.js:57]: Why not `return name`?

File: src/mono/wasm/runtime/loader/assets.ts [hunk 2]
```diff
@@ -78,10 +81,10 @@ function getSingleAssetWithResolvedUrl(resources: ResourceList | undefined, beha
 
     const customSrc = invokeLoadBootResource(asset);
     if (typeof (customSrc) === "string") {
-        asset.resolvedUrl = customSrc;
+        asset.resolvedUrl = makeURLAbsoluteWithApplicationBase(customSrc);
     } else if (customSrc) {
-        // Since we must load this via a import, it's only valid to supply a URI (and not a Request, say)
-        throw new Error(`For a ${behavior} resource, custom loaders must supply a URI string.`);
+        mono_log_warn(`For a ${behavior} resource, custom loaders must supply a URI string.`);
```
Comment (kg) [inline src/mono/wasm/runtime/loader/assets.ts:86]: this warning should specify the asset in question, probably

File: src/mono/wasm/runtime/loader/assets.ts [hunk 3]
```diff
@@ -220,8 +224,25 @@ export async function mono_download_assets(): Promise<void> {
...
 function prepareAssets(containedInSnapshotAssets: AssetEntryInternal[], alwaysLoadedAssets: AssetEntryInternal[]) {
     const config = loaderHelpers.config;
-    const resources = loaderHelpers.config.resources;
-    if (resources) {
+
+    // if assets exits, we will assume Net7 legacy and not process resources object
+    if (config.assets) {
+        for (const a of config.assets) {
+            const asset: AssetEntryInternal = a;
+            mono_assert(typeof asset === "object", "asset must be object");
```
Comment (kg) [inline src/mono/wasm/runtime/loader/assets.ts:232]: it would be good in the future to find a way to call out which specific asset is responsible for errors like this, since the list of assets could be very large

File: src/mono/wasm/runtime/loader/config.ts [hunk 4]
```diff
@@ -83,25 +93,87 @@ function deep_merge_resources(target: ResourceGroups, source: ResourceGroups): R
...
+        jsModuleWorker: {},
         jsModuleRuntime: {},
-        wasmNative: {}
+        wasmNative: {},
+        vfs: {},
+        satelliteResources: {},
     };
+
+    if (config.assets) {
+        mono_log_debug("assets are deprecated, use resources instead");
```
Comment (kg) [inline src/mono/wasm/runtime/loader/config.ts:129]: it would probably be better to phrase this like "config.assets is deprecated, use config.resources instead" but not terribly important

File: src/mono/wasm/runtime/loader/config.ts [hunk 5]
```diff
@@ -83,25 +93,87 @@ function deep_merge_resources(target: ResourceGroups, source: ResourceGroups): R
...
+                    toMerge.satelliteResources[asset.culture!] = resource;
+                    break;
+                case "icu":
+                    toMerge.icu = resource;
+                    break;
+                case "symbols":
+                    toMerge.wasmSymbols = resource;
+                    break;
+                case "vfs":
+                    toMerge.vfs = {};
```
[the remark this answers is not in the document]
Comment (kg) [reply src/mono/wasm/runtime/loader/config.ts:152]: nevermind :)

[the remark this answers is not in the document]
Comment (pavelsavara) [reply src/mono/wasm/runtime/loader/config.ts:152]: it will be deep merged later in the code, into the real config object

**Review by kg — APPROVED** [review]

**Comment by radical** [comment]
Is the sample testing the issue being fixed here? Can we please move to a WBT test? Having it in a sample makes it breakable in future, because we won't really know what it was testing necessarily. And somebody trying to clean up, or improve the code might break remove the things that we wanted to test.

**Comment by pavelsavara** [comment]
> Is the sample testing the issue being fixed here? Can we please move to a WBT test? 

About `browser-minimal-config`: yes I want to do that in the future. 

The `Wasm.Build.Tests.TestAppScenarios.AppTestBase` is currently Blazor based and I want non-blazor template for it. And I want to use the `src\mono\wasm\testassets\` style. We can refactor `AppTestBase` and do that in another PR.
