### PR TITLE
Fix stepping issues with ReadyToRun and TieredCompilation

### LINKED ISSUE #52768: Visual Studio debugger does not work for CoreLib checked builds
- Build this program:
```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

public class MyAttribute
{
}

class Program
{
    static void Main(string[] args)
    {
        var ab = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("MyAssembly"), AssemblyBuilderAccess.Run);
        var mb = ab.DefineDynamicModule("MyModule");
        var tb = mb.DefineType("MyType");
        tb.SetCustomAttribute(typeof(MyAttribute).GetConstructor(new Type[0]), new byte[0]);
        var t = tb.CreateType();
        for (;;) t.GetCustomAttributes();
    }
}
```
- Run the program on checked CoreCLR build, e.g. `corerun test.exe`
- In VS (I have done this on latest 16.10 Preview):
   - Attach to process
   - Break all
   - Switch to main thread
   - Load symbols for CoreLib (the CoreLib will be on the stack, if not step a few times to get into CoreLib)
   - In CoreLib code, try to set break points, step in, step out. For example:
       - Set a breakpoint at first line of `FilterCustomAttributeRecord`
       - F11 - does not work
       - F10 - crashes the process

Expected behavior: Debugging mostly works (checked build is with optimization on, so it is expected that it will step over multiple lines once in a while, etc.)

Actual behavior: Stepping does not work or crashes the process. Lines are often wrong (the debugger tends to stick to the last line in the method)

Crash - the same crash was reported as #12986 that was resolved as no-repro.
```
---------------------------
Microsoft Visual Studio
---------------------------
The debugger's worker process (msvsmon.exe) unexpectedly exited. Debugging will be aborted.
---------------------------
OK   
---------------------------
```
This printed on console:
```
Assert failure(PID 22588 [0x0000583c], Thread: 27592 [0x6bc8]): pOldContext == NULL
    File: D:\runtime\src\coreclr\debug\ee\controller.cpp Line: 4199
    Image: D:\runtime\artifacts\bin\coreclr\windows.x64.Checked\corerun.exe

(repeated many times)

Assert failure(PID 22588 [0x0000583c], Thread: 27592 [0x6bc8]): pOldContext == NULL
    File: D:\runtime\src\coreclr\debug\ee\controller.cpp Line: 4199
    Image: D:\runtime\artifacts\bin\coreclr\windows.x64.Checked\corerun.exe

Stack overflow.

Assert failure(PID 22588 [0x0000583c], Thread: 21836 [0x554c]): Timeout trying to suspend CLR for debugging. Possibly a deadlock.
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #52768 

Fix stepping issues with ReadyToRun assemblies and TieredCompilation in Debug/Checked builds of coreclr.

Narrow the scope of the DebuggerDataLock to only when the JIT info dictionary is being enumerated.

Get the correct PCODE version for ReadyToRun methods when the StubManager is computing the address to step to.

/cc @noahfalk @dotnet/dotnet-diag

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
There is an additional issue, even with this change, that I've been struggling to root out. The problem is that it seems the `DebuggerJitInfo` for some methods isn't being updated. For example, method A is ReadyToRun but then rejit is applied and is now Tier1 - this occurred prior to debugger attach. The debugger is attached and method A has an associated created `DebuggerJitInfo` is for ReadyToRun details but lacks the Tier1 entry. At this point, when stepping out of a method that method A calls, the returning address is in Tier1 code but the associated `DebuggerJitInfo` for method A has entries for ReadyToRun. The result is the debugger assumes the return address is in a thunk/stub.

The failure here is an assert. This means in Release this is likely okay, but in Debug/Checked we assert is chaos ensues. Any suggestions on where method run-down occurs would help me root this out.

/cc @noahfalk @hoyosjs

File: src/coreclr/debug/ee/controller.cpp [hunk 1]
```diff
@@ -6410,7 +6410,8 @@ void DebuggerStepper::TrapStepOut(ControllerStackInfo *info, bool fForceTraditio
                     continue;
 
                 dji = info->m_activeFrame.GetJitInfoFromFrame();
-                _ASSERTE(dji != NULL);
+                if (dji == NULL)
```
Comment (hoyosjs) [inline src/coreclr/debug/ee/controller.cpp:6413]: How do we end up with a null DJI? They should be there on JitComplete

Comment (AaronRobinsonMSFT) [reply src/coreclr/debug/ee/controller.cpp:6413]: That occasionally occurs and is the reason for so many of the asserts. One of the reasons is the issue mentioned above about missing Tier1 data on debug attach. Also, this can return `NULL` if an exception is thrown during the `GetJitInfoFromFrame()` call.

Additionally, handling a `NULL` is done by most callers of this API. The one above and one other are the only ones that prohibit `NULL` but as far as I can see this is possible and at the moment, very common.

Comment (noahfalk) [reply src/coreclr/debug/ee/controller.cpp:6413]: I assume that the other callsites which allow NULL DJIs are doing the lookup on a broader set of inputs. In this case we already confirmed at 6398 and 6406 that the frame we are looking up is a Frameless managed method which (I think) is synonymous with "this method is implemented by R2R or jitted code". If DJI is NULL here it probably means there is a bug in the code that is looking up the DJI. In the case where this assert fires do you know what the code at the IP is? The IP is in info->m_activeFrame->registers.

File: src/coreclr/debug/ee/frameinfo.cpp [hunk 2]
```diff
@@ -606,8 +606,7 @@ DebuggerJitInfo * FrameInfo::GetJitInfoFromFrame() const
     {
         _ASSERTE(this->md != NULL);
         ji = g_pDebugger->GetJitInfo(this->md, (const BYTE*)GetControlPC(&(this->registers)));
-        _ASSERTE(ji != NULL);
-        _ASSERTE(ji->m_nativeCodeVersion.GetMethodDesc() == this->md);
+        _ASSERTE(ji == NULL || ji->m_nativeCodeVersion.GetMethodDesc() == this->md);
```
Comment (noahfalk) [inline src/coreclr/debug/ee/frameinfo.cpp:609]: could you delete that old todo comment at line 604? it is wrong : )

File: src/coreclr/debug/ee/controller.cpp (hunk 1 above)
Comment (noahfalk) [reply src/coreclr/debug/ee/controller.cpp:6413]: by 'bug in lookup' I am including issues where the lookup was expected to populate an entry into the cache just in time. If that IP is pointing to the tier1 code and the lookup doesn't return a DJI for that code I considering that a bug in lookup. Can you find out what the IP represents?

Comment (AaronRobinsonMSFT) [reply src/coreclr/debug/ee/controller.cpp:6413]: Ah. Yes, the IP is in the Tier1 portion. I can see that in the logs and it states the following. I've updates the logs slightly.

The `0x00007FFA3CDAAE30` is an IP in Tier1 and `0x00000195DC6C18D0` is the initial DJI. There is a single one and I've confirmed this is the ReadyToRun entry not the Tier1.

```
TID 1bb2c: DJI:GJIBA finding DJI corresponding to addr 0x00007FFA3CDAAE30, starting with 0x00000195DC6C18D0
TID 1bb2c: CRI::GCRI: simple case: CodeRegionInfo* 0x00000195DC6C1908
TID 1bb2c: DJI:GJIBA: pbAddr 0x00007FFA3CDAAE30 is not in code 0x00007FFA9FE5E570 (size:0x0000000000000269)
TID 1bb2c: DJI:GJIBA couldn't find a DJI corresponding to addr 0x00007FFA3CDAAE30
TID 1bb2c: Couldn't find a DJI by address 0x00007FFA3CDAAE30, so it might be a stub or thunk
TID 1bb2c: StubManager::TraceStub: addr 0x00007FFA3CDAAE30 is managed code
TID 1bb2c: Address not thunked - must be to unJITted method, or normal managed method lacking a DJI!
```

File: src/coreclr/debug/ee/debugger.cpp [hunk 3]
```diff
@@ -2719,58 +2719,58 @@ DebuggerJitInfo *Debugger::GetJitInfoWorker(MethodDesc *fd, const BYTE *pbAddr,
...
+            LOG((LF_CORDB,LL_INFO1000,"Address not thunked - "
+                "must be to unJITted method, or normal managed "
+                "method lacking a DJI!\n"));
         }
-#endif // #ifndef DACCESS_COMPILE
+#endif //LOGGING
     }
+#endif // #ifndef DACCESS_COMPILE
 
     if (pMethInfo)
```
Comment (hoyosjs) [inline src/coreclr/debug/ee/debugger.cpp:2775]: Can you remove the comment on 2780 - the scope is now much narrower.

File: src/coreclr/debug/ee/controller.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/debug/ee/controller.cpp:6413]: I think I found the issue.

[See https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/ee/debugger.cpp#L2700-L2720](https://github.com/dotnet/runtime/blob/f99ba2e2b8fbf03be5058ad23e8cdce9c4a09da6/src/coreclr/debug/ee/debugger.cpp#L2700-L2720)

Comment (AaronRobinsonMSFT) [reply src/coreclr/debug/ee/controller.cpp:6413]: I need to head out now but based on the logs and the comments about not handling code versioning properly I believe this is an issue at the very least. It is likely never hit outside of attach scenarios.

Comment (noahfalk) [reply src/coreclr/debug/ee/controller.cpp:6413]: Yeah, that looks broken. If you wanted to fix that in this PR I think it would be a combo of g_pEEInterface->GetNativeCodeStartAddress(addr) and pDmi->FindOrCreateInitAndAddJitInfo().

Fwiw, a bunch of that stuff in GetJitInfoWorker looks unnecessarily complicated. I think logic like this would work fine:
```
...

PCODE startAddr = g_pEEInterface->GetNativeCodeStartAddress(pbAddr);
if(startAddr == NULL)
{
    // if the address wasn't in jitted code we'll also check to see if it is a stub that leads to jitted code
    TraceDestination trace;
    g_pEEInterface->TraceStub(pbAddr, &trace);
    if(trace.GetTraceType() == TRACE_MANAGED && pbAddr != trace.GetAddress())
    {
        startAddr = trace.GetAddress();
   }
}
if(startAddr != NULL)
{
    dji = dmi->FindOrCreateInitAndAddJitInfo(fd, startAddr);
}
```

**Comment by AaronRobinsonMSFT** [comment]
@noahfalk and @hoyosjs I took a shot at updating `Debugger::GetJitInfoWorker()`. Let me know if I am missing something. With this change the stepping failures during debug/checked build are gone.

**Review by hoyosjs — APPROVED** [review]

**Comment by hoyosjs** [comment]
Thanks Aaron - I went through all the cases I could think of this and this improves more than just the versioning - it even deals with some lock level issues :) So thanks for this one

File: src/coreclr/debug/ee/debugger.cpp [hunk 4]
```diff
@@ -2665,120 +2665,97 @@ DebuggerJitInfo *Debugger::GetJitInfo(MethodDesc *fd, const BYTE *pbAddr, Debugg
...
+        if (startAddr != NULL)
+        {
+            dji = dmi->FindOrCreateInitAndAddJitInfo(fd, startAddr);
+        }
+#endif // !DACCESS_COMPILE
+    }
+
+    if (dji == NULL)
+    {
+        dji = dmi->GetLatestJitInfo(fd);
```
Comment (noahfalk) [inline src/coreclr/debug/ee/debugger.cpp:2751]: I'd suggest we only do this when pbAddr == NULL.

If pbAddr is non-NULL and we didn't find dji above then either the address doesn't correspond to any known implementation of the method or we've got a bug somewhere. Whichever of those it is, I think we'd be better off returning NULL and asserting rather than returning an arbitrarily chosen implementation.

File: src/coreclr/debug/ee/functioninfo.cpp [hunk 5]
```diff
@@ -2326,12 +2333,13 @@ void DebuggerMethodInfoTable::DeleteEntryDMI(DebuggerMethodInfoEntry *entry)
 
 #endif // #ifndef DACCESS_COMPILE
 
-DebuggerJitInfo *DebuggerJitInfo::GetJitInfoByAddress(const BYTE *pbAddr )
+DebuggerJitInfo *DebuggerJitInfo::GetJitInfoByAddress(const BYTE *pbAddr)
```
Comment (noahfalk) [inline src/coreclr/debug/ee/functioninfo.cpp:2336]: I think you deleted the only call to this method in the codebase, you can delete this method now.

File: src/coreclr/debug/ee/controller.cpp (hunk 1 above)
Comment (noahfalk) [reply src/coreclr/debug/ee/controller.cpp:6417]: Now that you fixed the code in GetJitInfoWorker() is there a known case where we expect this callsite to get back a NULL by design? I know it is possible in general for GetJitInfo() to return NULL, but my understanding is that this code path is constrained enough that it doesn't hit those cases.

**Review by noahfalk — COMMENTED** [review]
Looks good, a few potential loose ends commented inline

**Comment by AaronRobinsonMSFT** [comment]
@noahfalk Any other concerns?

**Review by noahfalk — APPROVED** [review]
LGTM!

**Comment by tommcdon** [comment]
Thank you @AaronRobinsonMSFT!
