### PR TITLE
Fix assertions related to combining `cmn (extended-register)` (#113337)

### LINKED ISSUE #113337: JIT: Assertion failed 'isGeneralRegister(reg2)' during 'Generate code'
```csharp
// Generated by Fuzzlyn v2.4 on 2025-03-09 15:13:05
// Run on Arm64 Windows
// Seed: 7075707008869258884-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256,armsve
// Reduced from 47.0 KiB to 0.4 KiB in 00:00:50
// Hits JIT assert in Release:
// Assertion failed 'isGeneralRegister(reg2)' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 38; hash 0xade6b36b; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\emitarm64.cpp Line: 5520
// 
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static sbyte[] s_7;
    public static void Main()
    {
        var vr9 = Vector64.Create<float>(0);
        if ((2147483647 == (-(int)AdvSimd.Extract(vr9, 1))))
        {
            s_7 = s_7;
        }
    }
}
```

Introduced/exposed by #112944. Can you PTAL @snickolls-arm?

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by snickolls-arm**
Fixes issues highlighted by Fuzzlyn, related to erroneously combining cast=>negate=>compare into `cmn (extended-register)` when the second operand is an integral constant.

Fixes: #113337

### CODE REVIEW

File: src/tests/JIT/Regression/JitBlue/Runtime_113337/Runtime_113337.cs [hunk 1]
```diff
@@ -0,0 +1,39 @@
+using System;
+using System.Numerics;
+using System.Runtime.Intrinsics;
+using System.Runtime.Intrinsics.Arm;
+using System.Runtime.CompilerServices;
+using Xunit;
+
+public class Program
```
Comment (jakobbotsch) [inline src/tests/JIT/Regression/JitBlue/Runtime_113337/Runtime_113337.cs:8]:
```suggestion
public class Runtime_113337
```

File: src/tests/JIT/Regression/JitBlue/Runtime_113337/Runtime_113337.cs [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+    }
+
+    [Fact]
+    public static int TestEntryPoint()
+    {
+        // Checking for successful compilation
+        issue1();
+        issue2();
+        return 100;
+    }
```
Comment (jakobbotsch) [inline src/tests/JIT/Regression/JitBlue/Runtime_113337/Runtime_113337.cs:38]:
```suggestion
    public static void TestEntryPoint()
    {
        // Checking for successful compilation
        issue1();
        issue2();
    }
```

File: src/coreclr/jit/lowerarmarch.cpp [hunk 3]
```diff
@@ -404,9 +404,9 @@ bool Lowering::IsContainableUnaryOrBinaryOp(GenTree* parentNode, GenTree* childN
                 return false;
             }
 
-            if (childNode->gtGetOp1()->OperIs(GT_CAST))
+            if (childNode->gtGetOp1()->OperIs(GT_CAST) && !parentNode->gtGetOp2()->IsIntegralConst())
```
Comment (jakobbotsch) [inline src/coreclr/jit/lowerarmarch.cpp:407]:
```suggestion
            if (childNode->gtGetOp1()->OperIs(GT_CAST) && !parentNode->gtGetOp2()->isContained())
```
Should this check rather be like this? Uncontained constant will still be in a register, and that should be fine.

File: src/tests/JIT/Regression/JitBlue/Runtime_113337/Runtime_113337.cs (hunk 1 above)
Comment (EgorBo) [reply src/tests/JIT/Regression/JitBlue/Runtime_113337/Runtime_113337.cs:8]: Also, add the standard header (.NET Foundation)

File: src/coreclr/jit/lowerarmarch.cpp (hunk 3 above)
Comment (snickolls-arm) [reply src/coreclr/jit/lowerarmarch.cpp]: Looking again, I think it was down to the cast node needing more restrictions. I thought the assertion `isGeneralRegister(reg2)` was firing on `REG_NA`, but it was actually firing on a floating point register. The other assertion is down to containing a cast node that already contains a `LCL_VAR`, this shouldn't be allowed.

**Comment by jakobbotsch** [comment]
Are the [Fuzzlyn found](https://dev.azure.com/dnceng-public/public/_build/results?buildId=991397&view=ms.vss-build-web.run-extensions-tab) "unreached" assertion failures a different problem?

**Comment by snickolls-arm** [comment]
> Are the [Fuzzlyn found](https://dev.azure.com/dnceng-public/public/_build/results?buildId=991397&view=ms.vss-build-web.run-extensions-tab) "unreached" assertion failures a different problem?

I haven't seen this assertion fire before, but it looks like it's related to this change in containment patterns. I'll take a look today.

**Comment by snickolls-arm** [comment]
> I haven't seen this assertion fire before, but it looks like it's related to this change in containment patterns. I'll take a look today.

@jakobbotsch 

This new assertion is fired when a `NEG` node contains a `CAST` node. I think this situation is caused by the `CCMP` transform that is running on the code generated by Fuzzlyn. On [this line](https://github.com/dotnet/runtime/blob/32299f4b6aa148fd6ee0da222b01334a88414a25/src/coreclr/jit/lowerarmarch.cpp#L3214) it clears the containment relation between `CMP => NEG` after bashing the `CMP` node to `CCMP`, but it is not clearing the containment relation between `NEG => CAST`.

It's a slightly different problem but still introduced by the same change as before. Would you prefer this fix as a separate pull request, or a continuation here?

**Comment by jakobbotsch** [comment]
I wonder if we should rethink this transformation, to make it more robust. Would it make more sense to introduce a new `GT_CMPNEG` node to represent the "compare negated" version of the instruction? The multiple levels of containments always seem to cause trouble (it's not the first time we see issues like this).

**Comment by jakobbotsch** [comment]
Alternatively I would be ok with skipping the transformation in `TryLowerAndOrToCCMP` when an operand is a contained non-constant. That's an easier fix.

**Comment by snickolls-arm** [comment]
> I wonder if we should rethink this transformation, to make it more robust. Would it make more sense to introduce a new `GT_CMPNEG` node to represent the "compare negated" version of the instruction? The multiple levels of containments always seem to cause trouble (it's not the first time we see issues like this).

This could work. There's potentially some complications around the precedence of this transform over the `CCMP` transform, as the node would need to be split up again when converted into `CCMP` after the fact.

> Alternatively I would be ok with skipping the transformation in TryLowerAndOrToCCMP when an operand is a contained non-constant. That's an easier fix.

OK, I'll try this next.

**Comment by snickolls-arm** [comment]
> Are the [Fuzzlyn found](https://dev.azure.com/dnceng-public/public/_build/results?buildId=991397&view=ms.vss-build-web.run-extensions-tab) "unreached" assertion failures a different problem?
> 
> E.g.
> 
> ```cs
> // Generated by Fuzzlyn v2.5 on 2025-03-24 18:20:14
> // Run on Arm64 Linux
> // Seed: 8261718896722533474-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256,armsve
> // Reduced from 58.9 KiB to 0.5 KiB in 00:00:22
> // Hits JIT assert in Release:
> // Assertion failed 'unreached' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 72; hash 0xade6b36b; FullOpts)
> // 
> //     File: /__w/1/s/src/coreclr/jit/codegenarm64.cpp Line: 3530
> // 
> using System;
> using System.Numerics;
> using System.Runtime.Intrinsics;
> using System.Runtime.Intrinsics.Arm;
> 
> public class Program
> {
>     public static Vector<ulong>[] s_3;
>     public static void Main()
>     {
>         var vr3 = Vector.Create<short>(1);
>         var vr4 = (short)0;
>         var vr5 = Vector128.CreateScalar(vr4).AsVector();
>         if ((Sve.TestFirstTrue(vr3, vr5) | (3268100580U != (-(uint)Sve.SaturatingDecrementBy16BitElementCount(0, 1)))))
>         {
>             s_3[0] = s_3[0];
>         }
>     }
> }
> ```

These latest build failures seem to be network related as far as I understand. I've added this case to the test class and it seems to be compiling now.

**Comment by jakobbotsch** [comment]
Fuzzlyn failures are #113923, #113939, #113940. Linux-x64 failures are azurelinux timeouts.

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
There's a small number of regressions like this one:
image

Can you take a look at why, and potentially submit a follow-up if it's something unexpected?

I'm going to merge this to clean up Fuzzlyn runs.
