### PR TITLE
[mono][amd64] Fix Vector128 relational comparison API's for nuint type

### LINKED ISSUE #96443: Vector128.LessThan broken for some UIntPtr values on mono
Repro:
```C#
        [Theory]
        [InlineData(0ul)]
        [InlineData(1ul)]
        [InlineData(127ul)]
        [InlineData(128ul)]
        [InlineData(129ul)]
        [InlineData((ulong)int.MaxValue)]
        [InlineData(ulong.MaxValue)]
        public void Repro2(ulong ulValue)
        {
            Vector128<UIntPtr> vector = Vector128.Create((UIntPtr)ulValue);
            Assert.True(Vector128.EqualsAll(Vector128.LessThan(vector, Vector128<UIntPtr>.Zero), Vector128<UIntPtr>.Zero));
        }
```

That test passes for all of the supplied values (I haven't tried others) except for ulong.MaxValue, which fails:
```
    System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Repro2(ulValue: 18446744073709551615) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Runtime.Intrinsics/tests/Vectors/Vector128Tests.cs(44,0): at System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Repro2(UInt64 ulValue)
           at System.Object.InvokeStub_Vector128Tests.Repro2(Object , Span`1 )
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(95,0): at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

I haven't tried other values.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=512965&view=ms.vss-test-web.build-test-results-tab&runId=12013976&resultId=129149&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

### PR DESCRIPTION
**Pull request by fanyang-mono**
This PR fixes the following Vector128 API's, when the argument type is `nuint`:
- GreaterThan
- GreaterThanAll
- GreaterThanAny
- GreaterThanOrEqual
- GreaterThanOrEqualAll
- GreaterThanOrEqualAny
- LessThan
- LessThanAll
- LessThanAny
- LessThanOrEqual
- LessThanOrEqualAll
- LessThanOrEqualAny

Fixes #96443

### CODE REVIEW

**Comment by stephentoub** [comment]
What about ulong? Does this also fix that?

And could you add tests?

File: src/mono/mono/mini/mini-amd64.c [hunk 1]
```diff
@@ -3415,9 +3415,9 @@ simd_type_to_shl_op (int t)
 	case MONO_TYPE_I:
 	case MONO_TYPE_U:
 #if TARGET_SIZEOF_VOID_P == 8
-		return OP_PSHLD;
```
Comment (vargaz) [inline src/mono/mono/mini/mini-amd64.c:3418]: Is the #if really needed ?

**Review by vargaz — APPROVED** [review]

File: src/mono/mono/mini/mini-amd64.c (hunk 1 above)
Comment (fanyang-mono) [reply src/mono/mono/mini/mini-amd64.c:3418]: Probably not needed. Since it is amd64, `MONO_TYPE_U` and `MONO_TYPE_I` should be 64 bits integer.

**Comment by fanyang-mono** [comment]
@stephentoub `ulong` has always been working properly. The problematic type is `nuint`, which is the same as `UIntPtr`. Yes, I will add a test for this.

**Comment by stephentoub** [comment]
> The problematic type is nuint, which is the same as UIntPtr

Yes, thanks, that's what I intended to write. The original PR description had `uint` rather than `nuint`.

**Comment by fanyang-mono** [comment]
@stephentoub Yeah, I had a typo before. Sorry about the confusion.

**Review by tannergooding — APPROVED** [review]

**Comment by fanyang-mono** [comment]
CI lane `dotnet-linker-tests (Build osx-x64 release Runtime_Release)` seems to be stuck. It is irrelevant to the changes in this PR. Merging without waiting for it to be done.
