### PR TITLE
Skip flaky FileConfigurationProvider test on .NET Framework

### LINKED ISSUE #126787: ResolveFileProvider_WithMissingParentDirectory_WatchTokenFiresWhenFileCreated test timing out in CI
```
  Starting:    Microsoft.Extensions.Configuration.FileExtensions.Tests (parallel test collections = on [2 threads], stop on fail = off)
   Microsoft.Extensions.Configuration.FileExtensions.Tests: [Long Running Test] 'Microsoft.Extensions.Configuration.FileExtensions.Test.FileConfigurationProviderTest.ResolveFileProvider_WithMissingParentDirectory_WatchTokenFiresWhenFileCreated', Elapsed: 00:02:11
   Microsoft.Extensions.Configuration.FileExtensions.Tests: [Long Running Test] 'Microsoft.Extensions.Configuration.FileExtensions.Test.FileConfigurationProviderTest.ResolveFileProvider_WithMissingParentDirectory_WatchTokenFiresWhenFileCreated', Elapsed: 00:04:11
   Microsoft.Extensions.Configuration.FileExtensions.Tests: [Long Running Test] 'Microsoft.Extensions.Configuration.FileExtensions.Test.FileConfigurationProviderTest.ResolveFileProvider_WithMissingParentDirectory_WatchTokenFiresWhenFileCreated', Elapsed: 00:06:11
   Microsoft.Extensions.Configuration.FileExtensions.Tests: [Long Running Test] 'Microsoft.Extensions.Configuration.FileExtensions.Test.FileConfigurationProviderTest.ResolveFileProvider_WithMissingParentDirectory_WatchTokenFiresWhenFileCreated', Elapsed: 00:08:11
   Microsoft.Extensions.Configuration.FileExtensions.Tests: [Long Running Test] 'Microsoft.Extensions.Configuration.FileExtensions.Test.FileConfigurationProviderTest.ResolveFileProvider_WithMissingParentDirectory_WatchTokenFiresWhenFileCreated', Elapsed: 00:10:11
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1375007
Build error leg or test failing: System.Runtime.InteropServices.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/126699

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[Long Running Test] 'Microsoft.Extensions.Configuration.FileExtensions.Test.FileConfigurationProviderTest.ResolveFileProvider_WithMissingParentDirectory_WatchTokenFiresWhenFileCreated'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375007
**Error message validated:** `[[Long Running Test] 'Microsoft.Extensions.Configuration.FileExtensions.Test.FileConfigurationProviderTest.ResolveFileProvider_WithMissingParentDirectory_WatchTokenFiresWhenFileCreated'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/11/2026 2:01:13 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1379372](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1379372)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1379372&view=ms.vss-test-web.build-test-results-tab&runId=38529772&resultId=138680)|dotnet/runtime#126924|
|[1378710](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378710)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378710&view=ms.vss-test-web.build-test-results-tab&runId=38513446&resultId=138679)|dotnet/runtime#126091|
|[1378540](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378540)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378540&view=ms.vss-test-web.build-test-results-tab&runId=38510750&resultId=138679)|dotnet/runtime#126887|
|[1378257](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378257)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378257&view=ms.vss-test-web.build-test-results-tab&runId=38504336&resultId=138667)|dotnet/runtime#126875|
|[1378133](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378133)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378133&view=ms.vss-test-web.build-test-results-tab&runId=38501622&resultId=138667)|dotnet/runtime#126836|
|[1378001](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378001)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1378001&view=ms.vss-test-web.build-test-results-tab&runId=38498224&resultId=138667)|dotnet/runtime#125607|
|[1377638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1377638)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1377638&view=ms.vss-test-web.build-test-results-tab&runId=38487772&resultId=138681)|dotnet/runtime#126861|
|[1377604](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1377604)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1377604&view=ms.vss-test-web.build-test-results-tab&runId=38485616&resultId=138667)|dotnet/runtime#125596|
|[1377574](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1377574)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1377574&view=ms.vss-test-web.build-test-results-tab&runId=38484614&resultId=138667)|dotnet/runtime#126855|
|[1377204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1377204)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1377204&view=ms.vss-test-web.build-test-results-tab&runId=38473852&resultId=138960)|dotnet/runtime#125439|
|[1376869](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376869)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376869&view=ms.vss-test-web.build-test-results-tab&runId=38464652&resultId=138667)|dotnet/runtime#126807|
|[1376824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376824)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376824&view=ms.vss-test-web.build-test-results-tab&runId=38463036&resultId=138667)|dotnet/runtime#126835|
|[1376721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376721)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376721&view=ms.vss-test-web.build-test-results-tab&runId=38460084&resultId=138667)|dotnet/runtime#125439|
|[1376328](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376328)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376328&view=ms.vss-test-web.build-test-results-tab&runId=38448112&resultId=138667)||
|[1376289](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376289)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1376289&view=ms.vss-test-web.build-test-results-tab&runId=38447382&resultId=138679)|dotnet/runtime#126396|
|[1375908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375908)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375908&view=ms.vss-test-web.build-test-results-tab&runId=38437248&resultId=138667)||
|[1375713](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375713)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375713&view=ms.vss-test-web.build-test-results-tab&runId=38431854&resultId=138667)|dotnet/runtime#126807|
|[1375234](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375234)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375234&view=ms.vss-test-web.build-test-results-tab&runId=38420288&resultId=138667)|dotnet/runtime#126707|
|[1375092](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375092)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375092&view=ms.vss-test-web.build-test-results-tab&runId=38416980&resultId=138667)|dotnet/runtime#126785|
|[1375007](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375007)|dotnet/runtime|[Microsoft.Extensions.Configuration.FileExtensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1375007&view=ms.vss-test-web.build-test-results-tab&runId=38415380&resultId=138667)|dotnet/runtime#126699|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|5|20|20|

### PR DESCRIPTION
**Pull request by svick**
> [!NOTE]
> This PR was AI/Copilot-generated.

Fixes #126787

## Problem

The `ResolveFileProvider_WithMissingParentDirectory_WatchTokenFiresWhenFileCreated` test introduced in #126411 is flaky on the `net481-windows-Release-x86` CI leg, causing it to time out and block CI.

## Root cause

`FileSystemWatcher` on .NET Framework drops directory creation events under I/O contention. The `PendingCreationWatcher` in `PhysicalFilesWatcher` relies on FSW to detect when a missing root directory is created. When the FSW event is lost, the change token never fires and the test hangs.

This was verified by:
1. **Reproducing locally** — running the test in parallel (4-8 concurrent `dotnet test` processes) reproduces the hang on net481 x86 (~3% failure rate).
2. **Isolating to raw FSW** — a minimal test using only `FileSystemWatcher` (no `PendingCreationWatcher`) also fails under the same conditions on .NET Framework.
3. **Confirming .NET is unaffected** — 504 runs on net11.0 x86 with 8 concurrent threads produced 0 failures.

All 7 CI failures in the issue report are on the same `net481-windows-Release-x86-NET481_Release-Windows.10.Amd64.Client.Open` configuration.

## Changes

- **Skip on .NET Framework**: Changed `[Fact]` to `[ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotNetFramework))]` since the test depends on FSW reliability that .NET Framework cannot guarantee under load.
- **Improved timeout**: Replaced `CancellationTokenSource`-based timeout with `Task.WaitAsync(TimeSpan)` (via `TaskTimeoutExtensions` polyfill) and added `TaskCreationOptions.RunContinuationsAsynchronously` — matching the pattern used by all similar tests in `PhysicalFilesWatcherTests`.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs [hunk 1]
```diff
@@ -114,7 +113,8 @@ public void ProviderThrowsDirectoryNotFoundExceptionWhenNotFound(string physical
             Assert.Contains(physicalPath, exception.Message);
         }
 
-        [Fact]
+        // FileSystemWatcher is unreliable under load on .NET Framework, making this test flaky
+        [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotNetFramework))]
```
Comment (tarekgh) [inline src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs:117]: would using `IsNetCore` is better?

**Review by tarekgh — APPROVED** [review]

**Review by rosebyte — APPROVED** [review]
Tarek's comment looks reasonable, please consider it before merging..

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs (hunk 1 above)
Comment (svick) [reply src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs:117]: I think `IsNotNetFramework` expresses the intent better. I want to skip the test on .Net Framework, it's not a test that does something specific to .Net Core.

If there ever was another framework (lowercase f), I would want to run this test on it.

Comment (adamsitnik) [reply src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs:117]: Personally I also prefer `IsNotNetFramework`

**Review by adamsitnik — APPROVED** [review]
LGTM, I am going to allow myself to merge it so the CI is in better shape. Thank you @svick !

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs [hunk 2]
```diff
@@ -150,18 +150,16 @@ public async Task ResolveFileProvider_WithMissingParentDirectory_WatchTokenFires
...
+            using var changeCallbackRegistration = token.RegisterChangeCallback(_ => tcs.TrySetResult(true), null);
 
             Directory.CreateDirectory(missingSubDir);
             await Task.Delay(500);
             Assert.False(tcs.Task.IsCompleted, "Token must not fire when only the directory is created.");
 
             File.WriteAllText(configFilePath, "{}");
 
-            Assert.True(await tcs.Task, "Change token did not fire after the target file was created.");
+            await tcs.Task.WaitAsync(TimeSpan.FromSeconds(30));
```
Comment (jkotas) [inline src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs:162]: Was it intentional to delete ` Assert.True` here that validates the test result?

Comment (svick) [reply src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs:162]: That didn't really validate anything. It's only a `Task<bool>` because the non-generic TCS doesn't exist on .Net Framework. You can see that the test never calls `tcs.TrySetResult(false)`.

File: src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs:117]: Do we have any Mono test run today? if so, `IsNetCore` would be better, I guess.

Comment (svick) [reply src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/FileConfigurationProviderTest.cs:117]: Yes, for example, it runs in the `linux-x64 Debug Mono_MiniJIT_LibrariesTests` leg. But if it's not flaky on Mono (and so far it seems it isn't), then I think it makes sense to run it there.
