### PR TITLE
Fix generic method resolution in composite R2R images

### LINKED ISSUE #64170: Composite CG2 systemically fails to resolve certain generic instantiations
This is a first result of my current Crossgen2 performance investigations motivated by @richlander's container perf experiments from last year. In particular, I adapted the perf harness I had created for the original investigation to let me measure startup performance of the ASP.NET "webapi" sample app on Windows and I managed to reproduce exactly the same perf outlier where the JITted app running against composite framework exhibits significantly worse startup perf in comparison with the default configuration.

In fact, cross-measurements with varying COMPlus_TieredCompilation and COMPlus_ReadyToRun showed that in this case running the JITted app against the composite framework was almost as slow as when disabling R2R altogether. This led me to believe there must be some problem with R2R precompiled method resolution and I instrumented the runtime to help me nail down the problem. It turns out that the existing composite implementation often skips preJITted canonical generic instantiations; while I haven't yet been able to fully fix the problem and measure the perf delta, I highly suspect this deficiency contributes in a non-trivial manner to worse performance of JITted apps running against the composite framework.

Generic instance resolution takes place in ReadyToRunInfo::GetEntryPoint around

https://github.com/dotnet/runtime/blob/1f2116cd60ec0f3e39abbf60d7feedc537e5dfd3/src/coreclr/vm/readytoruninfo.cpp#L907

We iterate over the hashmap and we call SigMatchesMethodDesc to identify a full match. Sadly the way composite signatures work today means that the signature always starts with a module override to the owning type of the generic method. To resolve the owning type, we call ZapSig::DecodeModuleFromIndexIfLoaded; the problem I'm observing is that it may happen that by this time the target module hasn't been loaded yet so that DecodeModuleFromIndexIfLoaded returns null and the signature matcher is unable to recognize the instantiation even though it does match.

The proximate problem is that DecodeModuleFromIndexIfLoaded and related are under very strict VM contracts that don't allow dynamically loading the component assembly at this point. Similarly we presumably cannot preload all component assemblies upon first encountering a composite image as that would be also detrimental to startup perf. I'm exploring various options how to consolidate these, any expert opinion in the field is naturally highly welcome.

Thanks

Tomas

/cc @dotnet/crossgen-contrib

### PR DESCRIPTION
**Pull request by trylek**
According to my recent investigation, worse perf in the presence
of composite R2R images is due to the inability to resolve certain
generic methods in them; as an initial improvement in that direction
I propose changing generic instance signature matching to
always load assemblies referenced in their signatures. I'm locally
seeing this fix cancel the previous composite-specific regression
I originally measured on the webapi project. Please let me know
if you have different suggestions how to tackle this issue.

Thanks

Tomas

/cc: @dotnet/crossgen-contrib 
Fixes: #64170

### CODE REVIEW

File: src/coreclr/vm/zapsig.cpp [hunk 1]
```diff
@@ -343,7 +340,7 @@ BOOL ZapSig::GetSignatureForTypeHandle(TypeHandle      handle,
         {
             DWORD ix = CorSigUncompressData(pSig);
             CONTRACT_VIOLATION(ThrowsViolation|GCViolation);
-            pModule = pZapSigContext->GetZapSigModule()->GetModuleFromIndexIfLoaded(ix);
+            pModule = pZapSigContext->GetZapSigModule()->GetModuleFromIndex(ix);
```
Comment (jkotas) [inline src/coreclr/vm/zapsig.cpp:343]: Can this cause random assemblies to get loaded early?

Comment (trylek) [reply src/coreclr/vm/zapsig.cpp:343]: Well, with a probability corresponding to hash collisions (theoretically 2^-32) it can load more assemblies than required. One possible way to mitigate this would be to add a third method, something like <code>GetModuleFromIndexIfLoadedOrComposite</code>, that would only apply the logic of loading extra assemblies in the presence of a composite image thus removing any impact on non-composite code (even though in practice I doubt this happens very often as single-assembly crossgen files shouldn't precompile generic instantiations involving references to other modules. Without some form of loading the reference assembly I currently don't see how to make the precompiled generic instantiations in composite images useful.

Comment (jkotas) [reply src/coreclr/vm/zapsig.cpp:343]: > Well, with a probability corresponding to hash collisions (theoretically 2^-32)

I believe that the probability can be much higher in aggregate due birthday paradox.

>  Without some form of loading the reference assembly I currently don't see how to make the precompiled generic instantiations in composite images useful.

I think you just need to resolve the reference assembly from the already loaded assemblies to see whether it matches. All constituents of the generic method that we are trying to look up are loaded already. It means that we are not going to miss anything when we do not load any new assemblies.

**Comment by trylek** [comment]
Based on Jan Kotas' PR feedback I drilled deeper into the issue and I believe I have finally nailed down the problem. Turns out the crucial method <code>DecodeModuleFromIndexIfLoaded</code> fails to resolve the offending assembly (System.Linq in my original investigation) due to several interesting reasons:

1) While <code>DecodeModuleFromIndex</code> uses <code>GetNativeMetadataAssemblyRefFromCache</code> / <code>SetNativeMetadataAssemblyRefInCache</code> to cache the assembly resolution, <code>DecodeModuleFromIndexIfLoaded</code> never consulted the same cache. This PR fixes that deficiency.

2) Even though <code>DecodeModuleFromIndex</code> updates the assembly cache, it doesn't kick in when the assembly is loaded directly, not as a referenced entry point. I have fixed <code>NativeImage::Open</code> to register the component assembly.

3) There seems to be an additional assembly cache tied to the assembly binder that should resolve the assembly as a backdrop but it doesn't. I haven't yet investigated this secondary issue and I'm not trying to fix it in this PR.

Thanks

Tomas

**Comment by jkotas** [comment]
Yes, this approach looks better. I see number of test failures in the crossgen2 legs. Are any of them related to this change?

**Comment by trylek** [comment]
I believe not, I see some of them in runs before my change, I'm working on trying to repro them locally and I'll rerun the outerloop after merging in the new addition to issues.targets.

**Comment by trylek** [comment]
So there are basically three categories of the CG2 outerloop failures now: 

1) Crossgen2 compilation-time crashes in tests recently added by @jkoritzinsky under Interop\DisabledRuntimeMarshalling, e.g. here: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64247-head-7288d3d7dce34fca97/Interop/1/console.7e0fc92f.log?sv=2019-07-07&se=2022-02-16T01%3A11%3A42Z&sr=c&sp=rl&sig=YeXcpRNNiiAogWSRaluJ1v6SF9REZeBz5LpiS8uR42I%3D. I'm debugging the problem now.

2) Field offset mismatch on 64-bit platforms in the Runtime_60035 regression test, e.g. here: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64247-head-7288d3d7dce34fca97/JIT.Regression/1/console.70a2b72d.log?sv=2019-07-07&se=2022-02-16T01%3A11%3A42Z&sr=c&sp=rl&sig=YeXcpRNNiiAogWSRaluJ1v6SF9REZeBz5LpiS8uR42I%3D. I'm not yet sure what to do about this one, there's a possibility it's a fallout of Jeremy's type layout refactoring but the CG2 outerloop runs only receive random attention so I'm not 100% sure.

3) A bunch of one-off random crashes, some of them on arm64, mostly in various threading tests. I've ignored them for now.

**Comment by jkoritzinsky** [comment]
The crashes in item 1 should have been fixed by https://github.com/dotnet/runtime/pull/64286

**Comment by trylek** [comment]
Wonderful, thanks Jeremy for the immediate response - I've just unsuccessfully tried to repro it locally so that explains it I guess. In light of this fact I'll take a look at item 2 and then I'll run a new CG2 outerloop run.

**Comment by trylek** [comment]
I believe I have addressed all review feedback so far and the only remaining failures in the runs are the known timeouts in the Vector tests; from my viewpoint the change is ready to be merged in, please let me know if you're aware of any remaining deficiencies that need fixing first.

**Review by mangod9 — APPROVED** [review]

File: src/coreclr/vm/zapsig.cpp (hunk 1 above)
Comment (trylek) [reply src/coreclr/vm/zapsig.cpp]: Fixed in 2nd commit, thanks for pointing that out.
