### PR TITLE
Fix catching of generic exception in crossgened shared generic code 

### LINKED ISSUE #66005: R2R Crossgen2 breaks simple try catch statement with generic type
Sdk 6.0.2

Program.cs
```
try
{
    Test<InvalidOperationException>();
}
catch
{
    System.Diagnostics.Debug.Assert(false); // assertion triggered when running published version
}

static void Test<TException>() where TException : Exception
{
    try
    {
        throw new InvalidOperationException();
    }
    catch (TException)
    {
        return;
    }
}
```
csproj
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>true</ImplicitUsings>
		<PublishDir>published</PublishDir>
		<PublishReadyToRun>True</PublishReadyToRun>
		<RuntimeIdentifier>win8-x64</RuntimeIdentifier>
	</PropertyGroup>
	<Target Name="PublishAfterBuild" AfterTargets="Build">
		<CallTarget Targets="Publish" />
	</Target>
</Project>
```

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #66005

### CODE REVIEW

File: src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs [hunk 1]
```diff
@@ -661,6 +662,24 @@ private bool Get_CORINFO_METHOD_INFO(MethodDesc method, MethodIL methodIL, CORIN
...
 
+#if READYTORUN
+            if ((methodInfo->options & CorInfoOptions.CORINFO_GENERICS_CTXT_MASK) != 0)
+            {
+                foreach (var region in exceptionRegions)
+                {
+                    if (region.Kind == ILExceptionRegionKind.Catch)
+                    {
+                        TypeDesc catchType = (TypeDesc)methodIL.GetObject(region.ClassToken);
+                        if (catchType.IsRuntimeDeterminedSubtype)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:673]: The IL is not RuntimeDetermined (most of the time) in JitInterface because RyuJIT can't handle it. I think this will fix the test failure:

```suggestion
                        if (catchType.IsCanonicalSubtype(CanonicalFormKind.Any))
```

**Review by trylek — APPROVED** [review]
LGTM modulo Michal's suggestion, thank you!

**Comment by jkotas** [comment]
@mangod9 @trylek Are the crossgen2 outerloop failures known issues?

**Comment by mangod9** [comment]
There have been some recent failures with this issue which we need to look into:

```
Could Not Find C:\h\w\B600099D\w\A42B08CC\e\JIT\HardwareIntrinsics\X86\Sse42\Crc32_ro\Crc32_ro.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)
```

**Comment by mangod9** [comment]
also it appears that your run seems to have hit other infra issues too?

**Comment by jkotas** [comment]
> also it appears that your run seems to have hit other infra issues too?

Yes. None of the failures looked related to this fix.
