### PR TITLE
Ensure that we can still inline Math.Max and Math.Min on downlevel hardware

### LINKED ISSUE #88096: Regressions in Math.Min/Max benchmarks
### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 18.04
Queue | TigerUbuntu
Baseline | [4542e09ba0494eb29c86c6255fcba7fd9db897b7](https://github.com/dotnet/runtime/commit/4542e09ba0494eb29c86c6255fcba7fd9db897b7)
Compare | [3a303b8e0a67e3e330c26b4a305caa407f66e443](https://github.com/dotnet/runtime/commit/3a303b8e0a67e3e330c26b4a305caa407f66e443)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4542e09ba0494eb29c86c6255fcba7fd9db897b7...3a303b8e0a67e3e330c26b4a305caa407f66e443)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in BilinearTest

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[Interpol_Scalar - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/BilinearTest.Interpol_Scalar.html>) | 6.97 μs | 11.39 μs | 1.64 | 0.01 | True | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_27_2023/refs/heads/main_x64_ubuntu%2018.04_Regression/BilinearTest.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

### Payloads

[Baseline](<>)
[Compare](<>)

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'BilinearTest*'
```

<details>

### Payloads

[Baseline](<>)
[Compare](<>)
#### BilinearTest.Interpol_Scalar

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 11.392019824289877 > 7.3080500558187635.
IsChangePoint: Marked as a change because one of 6/19/2023 11:51:49 PM, 6/26/2023 6:52:13 PM falls between 6/17/2023 6:37:57 PM and 6/26/2023 6:52:13 PM.
IsRegressionStdDev: Marked as regression because -212.27980464814564 (T) = (0 -11425.0926797762) / Math.Sqrt((3264.2035944192285 / (19)) + (6315.325408949749 / (23))) is less than -2.0210753903043583 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (19) + (23) - 2, .025) and -0.646241001817783 = (6940.1094172485 - 11425.0926797762) / 6940.1094172485 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked as regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 18.04
Queue | TigerUbuntu
Baseline | [4542e09ba0494eb29c86c6255fcba7fd9db897b7](https://github.com/dotnet/runtime/commit/4542e09ba0494eb29c86c6255fcba7fd9db897b7)
Compare | [3a303b8e0a67e3e330c26b4a305caa407f66e443](https://github.com/dotnet/runtime/commit/3a303b8e0a67e3e330c26b4a305caa407f66e443)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4542e09ba0494eb29c86c6255fcba7fd9db897b7...3a303b8e0a67e3e330c26b4a305caa407f66e443)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.MathBenchmarks.Single

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[AcosPi - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.MathBenchmarks.Single.AcosPi.html>) | 33.16 μs | 34.85 μs | 1.05 | 0.05 | False | | |
[AsinPi - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.MathBenchmarks.Single.AsinPi.html>) | 26.10 μs | 27.80 μs | 1.07 | 0.06 | False | | |
[Min - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.MathBenchmarks.Single.Min.html>) | 4.36 μs | 9.79 μs | 2.25 | 0.01 | True | | |
[Max - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.MathBenchmarks.Single.Max.html>) | 4.36 μs | 9.82 μs | 2.25 | 0.05 | True | | |

graph
graph
graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_27_2023/refs/heads/main_x64_ubuntu%2018.04_Regression/System.MathBenchmarks.Single.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

### Payloads

[Baseline](<>)
[Compare](<>)

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.MathBenchmarks.Single*'
```

<details>

### Payloads

[Baseline](<>)
[Compare](<>)
#### System.MathBenchmarks.Single.AcosPi

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 34.85185961395694 > 34.81215898305084.
IsChangePoint: Marked as a change because one of 4/12/2023 9:47:42 AM, 6/19/2023 11:51:49 PM, 6/26/2023 6:52:13 PM falls between 6/17/2023 6:37:57 PM and 6/26/2023 6:52:13 PM.
IsRegressionStdDev: Marked as regression because -275.73947503992264 (T) = (0 -34843.3414755857) / Math.Sqrt((146.78381967633746 / (19)) + (696.340970241494 / (23))) is less than -2.0210753903043583 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (19) + (23) - 2, .025) and -0.051285952678343606 = (33143.543283172294 - 34843.3414755857) / 33143.543283172294 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
#### System.MathBenchmarks.Single.AsinPi

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 27.803446097385716 > 27.411496575261655.
IsChangePoint: Marked as a change because one of 4/12/2023 4:44:56 PM, 6/19/2023 11:51:49 PM, 6/26/2023 6:52:13 PM falls between 6/17/2023 6:37:57 PM and 6/26/2023 6:52:13 PM.
IsRegressionStdDev: Marked as regression because -11.07046276908435 (T) = (0 -28015.593903971618) / Math.Sqrt((2300.110939347 / (19)) + (665512.5293408092 / (23))) is less than -2.0210753903043583 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (19) + (23) - 2, .025) and -0.07222234628146819 = (26128.530151541225 - 28015.593903971618) / 26128.530151541225 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
#### System.MathBenchmarks.Single.Min

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 9.793916284099673 > 4.574769058553263.
IsChangePoint: Marked as a change because one of 6/19/2023 11:51:49 PM, 6/26/2023 6:52:13 PM falls between 6/17/2023 6:37:57 PM and 6/26/2023 6:52:13 PM.
IsRegressionStdDev: Marked as regression because -4077.942787750875 (T) = (0 -9793.360710345663) / Math.Sqrt((8.890539597199659 / (19)) + (30.107403114004754 / (23))) is less than -2.0210753903043583 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (19) + (23) - 2, .025) and -1.247532194273326 = (4357.383949960308 - 9793.360710345663) / 4357.383949960308 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked as regression because Edge Detector said so.

```
#### System.MathBenchmarks.Single.Max

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 9.816313532156284 > 4.575135782515241.
IsChangePoint: Marked as a change because one of 4/25/2023 6:46:56 PM, 5/19/2023 10:30:38 AM, 6/19/2023 11:51:49 PM, 6/26/2023 6:52:13 PM falls between 6/17/2023 6:37:57 PM and 6/26/2023 6:52:13 PM.
IsRegressionStdDev: Marked as regression because -2560.568103936479 (T) = (0 -9796.268681764557) / Math.Sqrt((4.905999652468138 / (19)) + (97.86250809145457 / (23))) is less than -2.0210753903043583 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (19) + (23) - 2, .025) and -1.2486135858622394 = (4356.5816480683325 - 9796.268681764557) / 4356.5816480683325 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked as regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 18.04
Queue | TigerUbuntu
Baseline | [4542e09ba0494eb29c86c6255fcba7fd9db897b7](https://github.com/dotnet/runtime/commit/4542e09ba0494eb29c86c6255fcba7fd9db897b7)
Compare | [3a303b8e0a67e3e330c26b4a305caa407f66e443](https://github.com/dotnet/runtime/commit/3a303b8e0a67e3e330c26b4a305caa407f66e443)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4542e09ba0494eb29c86c6255fcba7fd9db897b7...3a303b8e0a67e3e330c26b4a305caa407f66e443)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.MathBenchmarks.Double

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[Min - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.MathBenchmarks.Double.Min.html>) | 4.36 μs | 9.80 μs | 2.25 | 0.02 | True | | |
[Max - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.MathBenchmarks.Double.Max.html>) | 4.37 μs | 9.80 μs | 2.24 | 0.06 | True | | |

graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_27_2023/refs/heads/main_x64_ubuntu%2018.04_Regression/System.MathBenchmarks.Double.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

### Payloads

[Baseline](<>)
[Compare](<>)

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.MathBenchmarks.Double*'
```

<details>

### Payloads

[Baseline](<>)
[Compare](<>)
#### System.MathBenchmarks.Double.Min

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 9.797353483970342 > 4.580646210246807.
IsChangePoint: Marked as a change because one of 6/19/2023 11:51:49 PM, 6/26/2023 6:52:13 PM falls between 6/17/2023 6:37:57 PM and 6/26/2023 6:52:13 PM.
IsRegressionStdDev: Marked as regression because -4108.113806202843 (T) = (0 -9799.234437855583) / Math.Sqrt((6.967540554707664 / (19)) + (31.835250218845825 / (23))) is less than -2.0210753903043583 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (19) + (23) - 2, .025) and -1.2457873252163145 = (4363.384870787673 - 9799.234437855583) / 4363.384870787673 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked as regression because Edge Detector said so.

```
#### System.MathBenchmarks.Double.Max

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 9.80185848354232 > 4.582261803762309.
IsChangePoint: Marked as a change because one of 4/25/2023 1:57:48 PM, 5/19/2023 10:30:38 AM, 6/19/2023 11:51:49 PM, 6/26/2023 6:52:13 PM falls between 6/17/2023 6:37:57 PM and 6/26/2023 6:52:13 PM.
IsRegressionStdDev: Marked as regression because -2954.2342013487714 (T) = (0 -9798.381123671425) / Math.Sqrt((30.325791946983806 / (18)) + (39.05060689527017 / (23))) is less than -2.0226909200346674 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (18) + (23) - 2, .025) and -1.244769051994068 = (4364.984057031324 - 9798.381123671425) / 4364.984057031324 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked as regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #88096

### CODE REVIEW

File: src/coreclr/jit/importercalls.cpp [hunk 1]
```diff
@@ -8118,18 +8118,18 @@ GenTree* Compiler::impMinMaxIntrinsic(CORINFO_METHOD_HANDLE method,
...
                 if (isNumber)
                 {
-                    needsFixup = cnsNode->IsFloatNegativeZero();
+                    needsFixup = cnsNode->IsFloatPositiveZero();
                 }
                 else
                 {
-                    needsFixup = cnsNode->IsFloatPositiveZero();
+                    needsFixup = cnsNode->IsFloatNegativeZero();
                 }
```
Comment (tannergooding) [inline src/coreclr/jit/importercalls.cpp:8126]: We weren't doing the wrong thing, just not being as efficient as we should've been.

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib, @dotnet/avx512-contrib. Fixes the regression found in #88096 by not importing these as `GT_INTRINSIC` for non-constant inputs on downlevel hardware so inlining can still occur.

We'll likely want to address that problem still, but it will be a separate PR (likely for .NET 9)

**Review by BruceForstall — APPROVED** [review]
