### PR TITLE
Propagate BBF flags during hoisting

### LINKED ISSUE #57774: JIT: Assertion failed 'false'
```
export COMPlus_TieredCompilation=0
export COMPlus_ReadyToRun=0
export COMPlus_ZapDisable=1

 JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh [FAIL]
      
      Assert failure(PID 7987 [0x00001f33], Thread: 7987 [0x1f33]): Assertion failed 'false' in 'System.Collections.Generic.Dictionary`2[Char,__Canon][System.Char,System.__Canon]:TryInsert(ushort,System.__Canon,ubyte):bool:this' during 'Early Value Propagation' (IL size 739)
      
          File: /__w/1/s/src/coreclr/jit/earlyprop.cpp Line: 199
          Image: /datadisks/disk1/work/A11008DE/p/corerun
      
      /datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh: line 351:  7987 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/A11008DE/w/B72709EF/uploads/Reports/JIT.Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.output.txt
      Raw output:
      BEGIN EXECUTION
      /datadisks/disk1/work/A11008DE/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Runtime_56953.dll ''
      BBF_HAS_IDX_LEN is not set on BB15 but is required because of the following tree 
      N002 (  3,  3) [000967] ---X---H----              *  ARR_LENGTH int   
      N001 (  1,  1) [000968] -------H----              \--*  LCL_VAR   ref    V04 loc0         u:1
      Gathering state for process 7987 corerun
      Crashing thread 00001f33 signal 00000006
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7987.dmp
      Written 52674560 bytes (12860 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/A11008DE/p
      > /datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Regression._JitBlue_Runtime_56953_Runtime_56953_Runtime_56953_._JitBlue_Runtime_56953_Runtime_56953_Runtime_56953_sh()
      Output:
        
        Assert failure(PID 7987 [0x00001f33], Thread: 7987 [0x1f33]): Assertion failed 'false' in 'System.Collections.Generic.Dictionary`2[Char,__Canon][System.Char,System.__Canon]:TryInsert(ushort,System.__Canon,ubyte):bool:this' during 'Early Value Propagation' (IL size 739)
        
            File: /__w/1/s/src/coreclr/jit/earlyprop.cpp Line: 199
            Image: /datadisks/disk1/work/A11008DE/p/corerun
        
        /datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh: line 351:  7987 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/A11008DE/w/B72709EF/uploads/Reports/JIT.Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.output.txt
        Raw output:
        BEGIN EXECUTION
        /datadisks/disk1/work/A11008DE/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Runtime_56953.dll ''
        BBF_HAS_IDX_LEN is not set on BB15 but is required because of the following tree 
        N002 (  3,  3) [000967] ---X---H----              *  ARR_LENGTH int   
        N001 (  1,  1) [000968] -------H----              \--*  LCL_VAR   ref    V04 loc0         u:1
        Gathering state for process 7987 corerun
        Crashing thread 00001f33 signal 00000006
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7987.dmp
        Written 52674560 bytes (12860 pages) to core file
        Dump successfully written
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/A11008DE/p
        > /datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/57774 assert

When we hoist expressions we don't update BB flags, e.g. when we move GT_ARR_LEN node we have to set `BBF_HAS_IDX_LEN` flag in the dest block (and, presumably, reset it from source?). Normally we never hoist GT_ARR_LEN nodes because its earlyprop's responsibility but it happens in JitRepeatMode or if we disable EarlyProp phase and suspect it's possible to hit even in normal mode...). 

Perhaps, I should hide my visitor under JitRepeatMode or EarlyPropDisabled flags?

### CODE REVIEW

**Comment by SingleAccretion** [comment]
My opinion on this is that we should not try to maintain these flags because there is very little value in doing so. The sole purpose and use of these flags is making early prop skip "uninteresting" blocks, so it is not a correctness issue if we skip too many (CQ) or too few (TP).

**Comment by EgorBo** [comment]
> My opinion on this is that we should not try to maintain these flags because there is very little value in doing so. The sole purpose and use of these flags is making early prop skip "uninteresting" blocks, so it is not a correctness issue if we skip too many (CQ) or too few (TP).

Ah, you're correct, I didn't realize it's just a minor TP-related checks (both IDX and NULLCHECK)
thanks @SingleAccretion!

**Comment by EgorBo** [comment]
@dotnet/jit-contrib PTAL

**Comment by echesakovMSFT** [comment]
@EgorBo The test in the linked issue was disabled on some platforms in https://github.com/dotnet/runtime/pull/57788. Can you please revert the changes, so the test is enabled after the PR is merged.

File: src/coreclr/jit/optimizer.cpp [hunk 1]
```diff
@@ -5512,6 +5512,14 @@ void Compiler::optPerformHoistExpr(GenTree* origExpr, unsigned lnum)
     compCurBB = preHead;
     hoist     = fgMorphTree(hoist);
 
+#ifdef DEBUG
+    if ((JitConfig.JitDoEarlyProp() == 0) || opts.optRepeat)
+    {
+        // Normally its EarlyProp's responsibility to propagate these trees/flags
+        preHead->bbFlags |= BBF_HAS_NULLCHECK | BBF_HAS_IDX_LEN;
```
Comment (erozenfeld) [inline src/coreclr/jit/optimizer.cpp:5519]: The comment is incorrect. EarlyProp doesn't propagate these flags. It uses them and also asserts if they are not set.

Comment (erozenfeld) [reply src/coreclr/jit/optimizer.cpp:5519]: The condition is also incorrect. If `(JitConfig.JitDoEarlyProp() == 0)` we don't need to maintain these flags since early prop is the only phase that uses them.

I would just maintain these flags properly. Propagate the flags both in debug and release if the the basic block of `origExpr` has them.

Comment (SingleAccretion) [reply src/coreclr/jit/optimizer.cpp:5519]: What is the advantage in maintaining state that will not be used (I realize we could start using them later in the phase order, but then we'd have to write a proper checker anyway)?

FWIW, my take on the fix is to simply reset the flags in `ResetOptAnnotations` (via a visitor).

Comment (AndyAyersMS) [reply src/coreclr/jit/optimizer.cpp:5519]: Right, I would just always propagate these like @erozen says.

It is consistent with what we do elsewhere.

Comment (erozenfeld) [reply src/coreclr/jit/optimizer.cpp:5519]: > What is the advantage in maintaining state that will not be used (I realize we could start using them later in the phase order, but then we'd have to write a proper checker anyway)?

Under optRepeat this state will be used by early prop on the next iteration.

Comment (SingleAccretion) [reply src/coreclr/jit/optimizer.cpp:5519]: Yes, of course, the bug still has to be fixed after all.

To put my question another way: how do we decide what we should maintain for `optRepeat` (as a non-shipping configuration) and what we should just forget/reset/recompute?

Comment (AndyAyersMS) [reply src/coreclr/jit/optimizer.cpp:5519]: If it is cheap and easy to do the least surprising thing, we should do it.

Comment (erozenfeld) [reply src/coreclr/jit/optimizer.cpp:5519]: `optRepeat` is non-shipping but we do experiments with it to assess the usefulness of phases and possible phase reorderings. In this case not maintaining these flags may lead to some missed optimization opportunities and misleading results from optRepeat experiments. And, as @AndyAyersMS said, it's easy to maintain the flags in this case.

**Review by erozenfeld — APPROVED** [review]
LGTM
