### PR TITLE
Outbox AesGcm in to Microsoft.Bcl.Cryptography

### LINKED ISSUE #89718: [API Proposal]: Provide an implementation AesGcm in Microsoft.Bcl.Cryptography
### Background and motivation

The `AesGcm` class was introduced in to .NET in .NET Core 3.1. AES-GCM is an AEAD that is used in many protocols and specifications. Its broad use in in those specs makes it desirable or mandatory to support them.

For .NET Framework, there is no AES-GCM implementation that is readily available. Developers that want AES-GCM either have to p/invoke to Windows or find some other alternative implementation.

This is a proposal to add `AesGcm` to [Microsoft.Bcl.Cryptography][mbc].

1. When the package is build for .NET (Core), it will type-forward in to the shared runtime implementation.
2. When the package is build for .NET Framework, it will carry the required API surface and p/invokes similar to `SP800108HmacCounterKdf`
3. When the package is build for .NET Standard, it will behave similar to .NET Framework, however will perform a runtime check that the platform is Windows.

This means that the package will only provide an implementation on Windows. This is largely okay - developers on non-Windows platforms already have this in .NET itself and will benefit from the type forwards.

[mbc]: https://www.nuget.org/packages/Microsoft.Bcl.Cryptography/

### API Proposal

To provide the best experience, I think the `ref` needs to be split between .NET, .NET Framework, and .NET Standard.

This is because of the constructors that were [replaced in .NET 8](https://github.com/dotnet/runtime/issues/71366). For .NET Framework and .NET Standard, it would be ideal that we provide them with the same improved constructors since the new constructors are meant to mitigate misuse.

### .NET Framework and .NET Standard

```csharp
namespace System.Security.Cryptography;

public sealed partial class AesGcm : System.IDisposable
{
    // NOT included because they are obsolete
    // public AesGcm(byte[] key) { }
    // public AesGcm(System.ReadOnlySpan<byte> key) { }
    public AesGcm(byte[] key, int tagSizeInBytes) { }
    public AesGcm(System.ReadOnlySpan<byte> key, int tagSizeInBytes) { }
    public static bool IsSupported { get { throw null; } }
    public static System.Security.Cryptography.KeySizes NonceByteSizes { get { throw null; } }
    public static System.Security.Cryptography.KeySizes TagByteSizes { get { throw null; } }
    public int? TagSizeInBytes { get { throw null; } }
    public void Decrypt(byte[] nonce, byte[] ciphertext, byte[] tag, byte[] plaintext, byte[]? associatedData = null) { }
    public void Decrypt(System.ReadOnlySpan<byte> nonce, System.ReadOnlySpan<byte> ciphertext, System.ReadOnlySpan<byte> tag, System.Span<byte> plaintext, System.ReadOnlySpan<byte> associatedData = default(System.ReadOnlySpan<byte>)) { }
    public void Dispose() { }
    public void Encrypt(byte[] nonce, byte[] plaintext, byte[] ciphertext, byte[] tag, byte[]? associatedData = null) { }
    public void Encrypt(System.ReadOnlySpan<byte> nonce, System.ReadOnlySpan<byte> plaintext, System.Span<byte> ciphertext, System.Span<byte> tag, System.ReadOnlySpan<byte> associatedData = default(System.ReadOnlySpan<byte>)) { }
}

public sealed partial class AuthenticationTagMismatchException : CryptographicException
{
    public AuthenticationTagMismatchException();
    public AuthenticationTagMismatchException(string message);
    public AuthenticationTagMismatchException(string message, System.Exception inner);
}
```

### .NET 8+ type forward 

```csharp
namespace System.Security.Cryptography;

// Matches ref for .NET 8.
public sealed partial class AesGcm : System.IDisposable
{
    [System.ObsoleteAttribute("AesGcm should indicate the required tag size for encryption and decryption. Use a constructor that accepts the tag size.", DiagnosticId="SYSLIB0053", UrlFormat="https://aka.ms/dotnet-warnings/{0}")]
    public AesGcm(byte[] key) { }
    public AesGcm(byte[] key, int tagSizeInBytes) { }
    [System.ObsoleteAttribute("AesGcm should indicate the required tag size for encryption and decryption. Use a constructor that accepts the tag size.", DiagnosticId="SYSLIB0053", UrlFormat="https://aka.ms/dotnet-warnings/{0}")]
    public AesGcm(System.ReadOnlySpan<byte> key) { }
    public AesGcm(System.ReadOnlySpan<byte> key, int tagSizeInBytes) { }
    public static bool IsSupported { get { throw null; } }
    public static System.Security.Cryptography.KeySizes NonceByteSizes { get { throw null; } }
    public static System.Security.Cryptography.KeySizes TagByteSizes { get { throw null; } }
    public int? TagSizeInBytes { get { throw null; } }
    public void Decrypt(byte[] nonce, byte[] ciphertext, byte[] tag, byte[] plaintext, byte[]? associatedData = null) { }
    public void Decrypt(System.ReadOnlySpan<byte> nonce, System.ReadOnlySpan<byte> ciphertext, System.ReadOnlySpan<byte> tag, System.Span<byte> plaintext, System.ReadOnlySpan<byte> associatedData = default(System.ReadOnlySpan<byte>)) { }
    public void Dispose() { }
    public void Encrypt(byte[] nonce, byte[] plaintext, byte[] ciphertext, byte[] tag, byte[]? associatedData = null) { }
    public void Encrypt(System.ReadOnlySpan<byte> nonce, System.ReadOnlySpan<byte> plaintext, System.Span<byte> ciphertext, System.Span<byte> tag, System.ReadOnlySpan<byte> associatedData = default(System.ReadOnlySpan<byte>)) { }
}

public sealed partial class AuthenticationTagMismatchException : CryptographicException
{
    public AuthenticationTagMismatchException();
    public AuthenticationTagMismatchException(string message);
    public AuthenticationTagMismatchException(string message, System.Exception inner);
}
```

### API Usage

Same as .NET.

### Alternative Designs

This proposal leaves out `AesCcm`. This omission is purely due to no known demand for AES-CCM in downlevel platforms, whereas AES-GCM has demonstrated considerable demand. We can include AesCcm for completeness if desired.

### Risks

This carries the similar risks of providing any API as a package. It carries maintenance burden.

### PR DESCRIPTION
**Pull request by vcsjones**
This provides an implementation of `AesGcm` in Microsoft.Bcl.Cryptography to allow using it in .NET Framework. If the target framework is .NET 8+, then it type-forwards to the built-in version. .NET Standard is not able to include an implementation of `AesGcm` because it was included in .NET Standard 2.1 with an API shape that we do not want to support.

Closes #89718

### CODE REVIEW

File: src/libraries/Common/src/System/Security/Cryptography/AesGcm.cs [hunk 1]
```diff
@@ -0,0 +1,353 @@
...
+using System.Diagnostics;
+using System.Runtime.Versioning;
+using Internal.Cryptography;
+
+namespace System.Security.Cryptography
+{
+    /// <summary>
+    /// Represents an Advanced Encryption Standard (AES) key to be used with the Galois/Counter Mode (GCM) mode of operation.
+    /// </summary>
+    public sealed partial class AesGcm : IDisposable
```
Comment (vcsjones) [inline src/libraries/Common/src/System/Security/Cryptography/AesGcm.cs:13]: One of the things that made outboxing a little tricky is that the public API was split up in to different partials. This is less fun for Microsoft.Bcl.Cryptography, because it is the "source of truth" for its documentation.

The solution I came up with was to shove the public API surface in to a file that is mostly all partials, and document the partial. Different platforms each fill out the partial, but that way each platform correctly sees that it is documented.

Comment (vcsjones) [reply src/libraries/Common/src/System/Security/Cryptography/AesGcm.cs:13]: On that note, the documentation was back-ported from docs repo. So this required going back and filling in all of the public documentation.

File: src/libraries/Common/src/System/Security/Cryptography/AesGcm.Windows.cs [hunk 2]
```diff
@@ -4,43 +4,52 @@
...
     {
         private SafeKeyHandle _keyHandle;
+        private static readonly KeySizes s_tagByteSizes = new KeySizes(12, 16, 1);
 
-        public static bool IsSupported => true;
-        public static KeySizes TagByteSizes { get; } = new KeySizes(12, 16, 1);
+#if NET || NETFRAMEWORK
+        public static partial bool IsSupported => true;
+#elif NETSTANDARD
+        public static partial bool IsSupported => RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
```
Comment (vcsjones) [inline src/libraries/Common/src/System/Security/Cryptography/AesGcm.Windows.cs:19]: In the csproj file, the `AesGcm.Windows.cs` implementation is used for .NET Standard and .NET Framework. AesGcm's constructor checks `IsSupported` and will fail with PNSE if it is false.

File: src/libraries/Common/src/System/Security/Cryptography/AesGcm.cs [hunk 3]
```diff
@@ -0,0 +1,353 @@
...
+        /// </exception>
+        /// <exception cref="PlatformNotSupportedException">
+        ///   The current platform does not support AES-GCM.
+        /// </exception>
+        /// <remarks>
+        ///   The <paramref name="tagSizeInBytes" /> parameter is used to indicate that the tag parameter in <c>Encrypt</c>
+        ///   or <c>Decrypt</c> must be exactly this size. Indicating the required tag size prevents issues where callers
+        ///   of <c>Decrypt</c> may supply a tag as input and that input is truncated to an unexpected size.
+        /// </remarks>
+        public AesGcm(ReadOnlySpan<byte> key, int tagSizeInBytes)
```
Comment (vcsjones) [inline src/libraries/Common/src/System/Security/Cryptography/AesGcm.cs:70]: This is the AesGcm implementation in `Common`, so it lacks the constructors without `tagSizeInBytes`. Those constructors are only in the S.S.Cryptography implementation.

Here is the resulting public API surface for .NET Standard 2.0 and .NET Framework:
 
Screenshot 2025-01-22 at 3 46 13 PM

File: src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets [hunk 4]
```diff
@@ -0,0 +1,8 @@
+<Project InitialTargets="NETStandardCompatError_Microsoft_Bcl_Cryptography">
+    <Target Name="NETStandardCompatError_Microsoft_Bcl_Cryptography">
+        <Error Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1')) AND
+                          !$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0')) AND
+                          !$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net462'))"
+               Text="Microsoft.Bcl.Cryptography doesn't support $(TargetFramework). Use multi-targeting instead of .NET Standard 2.1 for this package, or target .NET Standard 2.0." />
```
Comment (vcsjones) [inline src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: This file is probably the thing that needs the most attention in this pull request. It ends up as a buildTransitive target for .NET Standard 2.1. I did confirm that it does block the package installation in .NET Standard 2.1.

In particular, thoughts on wording for the message and the condition would be appreciated.

Screenshot 2025-01-22 at 3 50 34 PM

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/AesGcm.OpenSsl.cs [hunk 5]
```diff
@@ -10,12 +10,14 @@ namespace System.Security.Cryptography
     public sealed partial class AesGcm
     {
         private SafeEvpCipherCtxHandle _ctxHandle;
+        private static readonly KeySizes s_tagByteSizes = new KeySizes(12, 16, 1);
+        private static readonly bool s_isSupported = Interop.OpenSslNoInit.OpenSslIsAvailable;
 
-        public static bool IsSupported { get; } = Interop.OpenSslNoInit.OpenSslIsAvailable;
-        public static KeySizes TagByteSizes { get; } = new KeySizes(12, 16, 1);
+        public static partial bool IsSupported => s_isSupported;
```
Comment (vcsjones) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/AesGcm.OpenSsl.cs:16]: The downside to the `partial` trick for documentation purposes is that partial properties cannot be auto-properties. This seemed like a worthy tradeoff (and I am not sure how to solve it otherwise).

File: src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets (hunk 4 above)
Comment (teo-tsirpanis) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: How about you move this file to `buildTransitive/netstandard2.1` and remove the conditions? [There are already](https://nuget.info/packages/Microsoft.Bcl.Cryptography/9.0.1) empty folders in `buildTransitive` for the supported frameworks, causing the file to not be imported there.

In a similar vein you can add a `_._` file in `lib/netstandard2.1`, causing no library to be imported in frameworks compatible with .NET Standard 2.1, but earlier than .NET 8. With that, the error can become a warning, which will not break scenarios when `Microsoft.Bcl.Cryptography` is referenced by an NS2.0 library, which is referenced by a NS2.1 library (the end project will still have to target .NET 8+).

File: src/libraries/Common/src/System/Security/Cryptography/AesAEAD.cs [hunk 6]
```diff
@@ -1,15 +1,13 @@
...
 namespace System.Security.Cryptography
 {
-    internal static partial class AesAEAD
+    internal static class AesAEAD
     {
-        public static void CheckKeySize(int keySizeInBytes)
+        internal static void CheckKeySize(int keySizeInBytes)
         {
-            if (keySizeInBytes != (128 / 8) && keySizeInBytes != (192 / 8) && keySizeInBytes != (256 / 8))
+            if (keySizeInBytes is not 128 / 8 and not 192 / 8 and not 256 / 8)
```
Comment (bartonjs) [inline src/libraries/Common/src/System/Security/Cryptography/AesAEAD.cs:10]: Once you're changing the style here, shouldn't it be

```suggestion
            if (keySizeInBytes is not (128 / 8 or 192 / 8 or 256 / 8)
```
?

File: src/libraries/Common/src/System/Security/Cryptography/AesGcm.cs (hunk 1 above)
Comment (bartonjs) [reply src/libraries/Common/src/System/Security/Cryptography/AesGcm.cs:13]: > The solution I came up with was to shove the public API surface in to a file that is mostly all partials, and document the partial. 

Yeah, that's consistent with what I did for the cert loader, and think is our path forward... given our split builds and the docs source-of-truth location being in the code repository.

It'll also help with keeping attributes in sync (like SupportedPlatform)

**Comment by bartonjs** [comment]
The code refactorings LGTM; signoff withheld pending resolution of the "fail the build" target.

File: src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets (hunk 4 above)
Comment (ViktorHofer) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: This infrastructure already exists in all shipping runtime packages. Just as a warning instead of an error for very good reasons. Can you please explain why the existing infrastructure isn't sufficient?

Comment (vcsjones) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: The use case is different here. In API review, it was decided that we cannot outbox `AesGcm` in to M.Bcl.Cryptography for .NET Standard 2.1 because the API shape for it is a pit of failure. The API review folks basically decided "It is an error to use this package on .NET Standard 2.1". @bartonjs correct me if I'm wrong.

Comment (ViktorHofer) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: It's not possible to enforce this via a package target files. Consumers can always set the `ExcludeAssets` metadata to control the assets that are being used from a package (that's a fundamental design of NuGet packages):

`<PackageReference Include="Microsoft.Bcl.Cryptography" Version="..." ExcludeAssets="buildTransitive" />`.

In general, as long as the package supports .NET Standard 2.0 or .NET Standard 2.1, it's consumable on that platform. You would need to make the assembly throw at runtime. Note that we received loud and clear feedback that throwing at runtime is the worst of all options. See https://github.com/open-telemetry/opentelemetry-dotnet/issues/3448#issuecomment-1185459615 and the following comments for more information.

Comment (ViktorHofer) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: @ericstj I would appreciate your opinion on this as well

Comment (teo-tsirpanis) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: Some other options I have thought about, in descending order of preference:

* Hide, obsolete-as-error and change the problematic APIs of `AesGcm` to unconditionally throw when targeting `netstandard2.0`.
* Multi-target to `netstandard2.1` and do not polyfill `AesGcm` there.
* Multi-target to `netcoreapp3.0` and type-forward `AesGcm` there (I can imagine you don't want this).

What do you think about my proposal above? On second thought we could add the empty folder in `lib/netcoreapp3.0` instead of `lib/netstandard2.1`.

Comment (ericstj) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: I agree with not trying to block things via error targets.  We add the targets to try and send a message, but not to block consumption.

If you can avoid exposing any assets on that target framework it's the best - then nuget won't allow install.  Seems that ship has sailed.

In that case, I think I like @teo-tsirpanis's suggestion the best - if we have API that is not appropriate to share in `netstandard` ref - just leave it out.   `netstandard` is lower / smaller than `net` or `netcoreapp` frameworks.

Comment (bartonjs) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: NETStandard 2.1 defines a version of the class with two constructors that we're not exposing from this package (they've since been marked `[Obsolete]` for "no one uses these in a secure enough manner" reasons).  So the problem is that if someone runs on a NS2.1 target that isn't NET8+ they'll get a MissingMethodException, because the underlying runtime won't have exposed the ctors that this library says exist.

The choices are
1) Actively block NS2.1 (what API Review said to do)
2) Deal with NS2.1 MissingMethodException
3) Say that "because NS2.1 exists, we will not support this for .NET Framework", which probably gets someone sent to the principal's office.

Option (4) of "expose the old ctors" has already been rejected on "secure by default" grounds.

Comment (bartonjs) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: Oh, right, not having a NS2.1 asset means they won't unify, so no MissingMethodException.  Instead it's "Ambiguous reference, System.Security.Cryptography.AesGcm [netstandard2.1] vs System.Security.Cryptography.AesGcm [Microsoft.Bcl.Cryptography]"

Comment (teo-tsirpanis) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: Oh [there is `AesGcm` in .NET Standard 2.1](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=net-9.0#applies-to). Then why not multi-target to .NET Standard 2.1 and forward to the inbox `AesGcm`? Sounds like a no-brainer.

Comment (bartonjs) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: > Oh [there is AesGcm in .NET Standard 2.1](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=net-9.0#applies-to). Then why not multi-target to .NET Standard 2.1 and forward to the inbox AesGcm?

Because:

> NETStandard 2.1 defines a version of the class with two constructors that we're not exposing from this package (they've since been marked [Obsolete] for "no one uses these in a secure enough manner" reasons). So the problem is that if someone runs on a NS2.1 target that isn't NET8+ they'll get a MissingMethodException, because the underlying runtime won't have exposed the ctors that this library says exist.

Comment (vcsjones) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: > Oh [there is AesGcm in .NET Standard 2.1](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=net-9.0#applies-to). Then why not multi-target to .NET Standard 2.1 and forward to the inbox AesGcm? Sounds like a no-brainer.

Because the one in .NET Standard 2.1 has constructors that are obsolete, specifically for "people introduce vulnerabilities using them". The only version of `AesGcm` that exists in .NET Standard 2.1 is impossible to use safely, so we don't want to out-box it for .NET Standard 2.1.

Comment (ericstj) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: Can you just leave that type out of the `netstandard` assembly completely?  Why even put it there if you don't have a safe version that can be used everywhere?

Comment (vcsjones) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: Because we want it for netstandard2.0, where `AesGcm` does not exist so we can provide the API we want.

Comment (teo-tsirpanis) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: > The only version of `AesGcm` that exists in .NET Standard 2.1 is impossible to use safely

Ah I see, I now understand the problem.

Comment (ericstj) [reply src/libraries/Microsoft.Bcl.Cryptography/src/buildTransitive/Microsoft.Bcl.Cryptography.targets:6]: I chatted with @bartonjs offline.  I really don't think it's worth exposing this for netsandard with additional API that will have a known unification problem on netstandard2.1 and .NETCore 3.0-7.0 (even though out of support).

IMO you should either a) leave out the constructors from netstandard or b) leave the type out entirely from netstandard.  You can still provide it on netfx, but those places where it already exists -- you really don't want to pretend it works or has more API than it actually does.

**Comment by vcsjones** [comment]
Okay, `AesGcm` is no longer present in .NET Standard builds.

### .NET 10 (type forward):
Screenshot 2025-02-14 at 9 38 17 AM 1

### .NET 9 (type forward):

Screenshot 2025-02-14 at 9 41 19 AM

### .NET 8 (type forward):

Screenshot 2025-02-14 at 9 41 56 AM

### .NET Framework (implementation):

Screenshot 2025-02-14 at 9 40 00 AM

### .NET Standard (no `AesGcm`)

Screenshot 2025-02-14 at 9 42 57 AM

File: src/libraries/Common/tests/System/Security/Cryptography/AesGcmTests.cs [hunk 7]
```diff
@@ -962,6 +972,18 @@ private static IEnumerable<AEADTest> GetNistTests()
                 Tag = "4ce8aff15debc1b23c50665b9c".HexToByteArray(),
             },
         };
+
+        private static void FillRandom(Span<byte> destination)
+        {
+#if NET
+            RandomNumberGenerator.Fill(destination);
+#else
+            RandomNumberGenerator generator = RandomNumberGenerator.Create();
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/AesGcmTests.cs:981]: RNG is IDisposable, so either a manual call to Dispose or a using should be added.

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
Failures are known and unrelated to the changes. Merging.
