### PR TITLE
Fix P/Invoke IL stub race in DoPrestub

### LINKED ISSUE #124530: Race in PInvoke stub generation
### Summary

Multiple threads can race in P/Invoke ILStub creation and produce different `PCODE` values for the same `MethodDesc`, violating the assert in `DoPrestub`.

### Failing Assert

[prestub.cpp#L2340](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/prestub.cpp#L2340):
```cpp
_ASSERTE(pCode == (PCODE)NULL || GetNativeCode() == (PCODE)NULL || pCode == GetNativeCode());
```

Thread A calls `GetStubForInteropMethod` and gets back `pCode` = X, then thread B does the same and gets `pCode` = Y. Thread A's `SetCodeEntryPoint(X)` publishes X as `GetNativeCode()`. Thread B then hits the assert because `Y != X`.

### Why different stubs are produced

The existing comment at [dllimport.cpp#L5689-L5699](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/dllimport.cpp#L5689-L5699) claims this can't happen:

```cpp
// NOTE: there is a race in updating this MethodDesc.  We depend on all
// threads getting back the same DynamicMethodDesc for a particular
// PInvokeMethodDesc, in that case, the locking around the actual JIT
// operation will prevent the code from being jitted more than once.
// By the time we get here, all threads get the same address of code
// back from the JIT operation and they all just fill in the same value
// here.
```

This invariant depends on all threads resolving to the **same** `DynamicMethodDesc` (ILStub) via the `ILStubCache`. However, the cache lookup and insert in `ILStubCache::GetStubMethodDesc` ([ilstubcache.cpp#L514-L586](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/ilstubcache.cpp#L514-L586)) is **guarded by `SF_IsSharedStub`**:

```cpp
if (SF_IsSharedStub(dwStubFlags))
{
    CrstHolder ch(&m_crst);
    const ILStubCacheEntry* phe = m_hashMap.LookupPtr(pHashBlob);
    if (phe)
    {
        pMD = phe->m_pMethodDesc;
    }
}
```

For forward P/Invokes (non-CALLI, non-vararg), `IsSharedStubScenario` returns **`false`** ([dllimport.cpp#L232-L235](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/dllimport.cpp#L232-L235)):

```cpp
if (SF_IsForwardPInvokeStub(dwStubFlags) && !SF_IsCALLIStub(dwStubFlags) && !SF_IsVarArgStub(dwStubFlags))
{
    return false;
}
```

So `SF_IsSharedStub` is never set for ordinary P/Invokes, which means:
1. The hash-based cache lookup is **skipped entirely**
2. `CreateNewMethodDesc` is called unconditionally — each racing thread gets a **distinct** `MethodDesc*`
3. The subsequent `JitILStub` produces different `PCODE` values (same code, different addresses)
4. `SetCodeEntryPoint` in `DoPrestub` sees a mismatch and asserts

### Root Cause

PR [#117901](https://github.com/dotnet/runtime/pull/117901) removed shared IL stubs for P/Invokes by making `IsSharedStubScenario` return `false` for forward P/Invokes. This was previously the mechanism that ensured all threads resolved to the same `DynamicMethodDesc`. With it gone, concurrent threads each create their own stub and JIT it independently, producing distinct `PCODE` values — invalidating the comment at [dllimport.cpp#L5689](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/dllimport.cpp#L5689).

### Relevant Call Path

```
MethodDesc::DoPrestub                                       // prestub.cpp
  → GetStubForInteropMethod(this)                           // prestub.cpp:2283
    → PInvoke::GetStubForILStub(pNMD, &pStubMD, dwStubFlags)  // dllimport.cpp:5779
      → GetILStubMethodDesc(pNMD, &sigInfo, dwStubFlags)      // dllimport.cpp:5653
        → PInvoke::CreateCLRToNativeILStub(...)                // dllimport.cpp:5528
          → CreateInteropILStub(...)                           // dllimport.cpp:4878
            → ILStubCreatorHelper::GetStubMethodDesc()         // dllimport.cpp:4975
              → ILStubCache::GetStubMethodDesc(...)            // ilstubcache.cpp:486
                // SF_IsSharedStub is FALSE → cache lookup skipped
                // → CreateNewMethodDesc (new stub every time)
      → JitILStub(*ppStubMD)                                  // dllimport.cpp:5660 — JITs the new (unique) stub
  // returns distinct PCODE per thread
  → _ASSERTE(... pCode == GetNativeCode())                  // prestub.cpp:2341 — FAILS
```

### Questions

1. Should P/Invoke ILStub creation re-enable cache lookup/insert (i.e., revert the `IsSharedStubScenario` change for the cache path, even if the stubs are no longer "shared" in the old sense)?
2. Or should `DoPrestub` handle `pCode != GetNativeCode()` for P/Invokes by discarding the duplicate and using the already-published value?
3. Or should synchronization be added in `PInvoke::GetStubForILStub` so only one thread creates the stub per `MethodDesc`?

### Repro Notes

- Only reproduces with ReadyToRun enabled (investigating why)
- A `ClrSleepEx(100, FALSE)` after `GetStubForInteropMethod` at [prestub.cpp#L2284](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/prestub.cpp#L2284) widens the window and makes the repro more consisten (still only with readytorun)

Summary generated with AI

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
## Summary

Re-enable ILStubCache lookup/insert for forward P/Invoke stubs to prevent racing threads from independently creating and JIT-ing duplicate IL stubs for the same target method.

## Root Cause

PR #117901 made `IsSharedStubScenario` return `false` for forward P/Invokes, which disabled the `ILStubCache` lookup. Multiple threads could then each create their own `DynamicMethodDesc` and JIT it, producing different `PCODE` values that violated the assert in `DoPrestub`.

## Fix

- Remove the forward P/Invoke exclusion from `IsSharedStubScenario` so these stubs use the `ILStubCache` for de-duplication.
- In `CreateHashBlob`, create a minimal hash blob containing just the target `MethodDesc` pointer for forward P/Invoke stubs, so different P/Invoke methods get distinct cache entries while racing threads for the same method converge on the same `DynamicMethodDesc`.

Fixes #124530

### CODE REVIEW

File: src/coreclr/vm/dllimport.cpp [hunk 1]
```diff
@@ -4081,10 +4081,32 @@ namespace
...
+            && SF_IsForwardPInvokeStub(dwStubFlags)
+            && !SF_IsCALLIStub(dwStubFlags)
+            && !SF_IsVarArgStub(dwStubFlags))
+        {
+            size_t blobSize = sizeof(ILStubHashBlobBase) + sizeof(MethodDesc*);
+            NewArrayHolder<BYTE> pBytes = new BYTE[blobSize];
+            ZeroMemory(pBytes, blobSize);
+            ILStubHashBlob* pBlob = (ILStubHashBlob*)(BYTE*)pBytes;
+            pBlob->m_cbSizeOfBlob = blobSize;
+            memcpy(pBlob->m_rgbBlobData, &pTargetMD, sizeof(pTargetMD));
```
Comment (jtschuster) [inline src/coreclr/vm/dllimport.cpp:4110]: nit: we could be consistent with the `sizeof` arguments
```suggestion
            memcpy(pBlob->m_rgbBlobData, &pTargetMD, sizeof(MethodDesc*));
```

File: src/coreclr/vm/dllimport.cpp [hunk 2]
```diff
@@ -4866,11 +4886,10 @@ namespace
         }
 
     private:
-        MethodDesc*                      m_pTargetMD;
         PInvokeStubParameters*           m_pParams;
-        NewArrayHolder<ILStubHashBlob>   m_pHashParams;
-        AllocMemTracker*                 m_pAmTracker;
```
Comment (jtschuster) [inline src/coreclr/vm/dllimport.cpp:4872]: This was just sitting around unused? Are there no compiler warnings about that in c++?

**Review by jtschuster — APPROVED** [review]
LGTM, thank you!

File: src/coreclr/vm/dllimport.cpp (hunk 1 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp:4110]: I can make them consistent, but it is generally better to use the variable so its type doesn't change but the `sizeof()` computation remains.

File: src/coreclr/vm/dllimport.cpp (hunk 2 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp:4872]: No consistent compiler warnings on this. Also, unused fields in C++ can be a fraught issue. In this case it is probably okay, but generally it become a huge can of worms I'm not opening right now. The gist is about visibility of the type and if it crosses translation units or not.

**Comment by jkoritzinsky** [comment]
Yeah this can wait until we do a greater refactoring of the MethodDesc hierarchy if that's the preference.

File: src/coreclr/vm/dllimport.cpp [hunk 3]
```diff
@@ -4081,10 +4081,32 @@ namespace
...
+        // Forward P/Invoke stubs (non-CALLI, non-vararg) each target a specific method,
+        // so the hash blob is just the target MethodDesc pointer. This ensures racing
+        // threads for the same P/Invoke converge on the same DynamicMethodDesc in the
+        // ILStubCache, while different P/Invoke methods get distinct cache entries.
+        if (pTargetMD != NULL
+            && SF_IsForwardPInvokeStub(dwStubFlags)
+            && !SF_IsCALLIStub(dwStubFlags)
+            && !SF_IsVarArgStub(dwStubFlags))
+        {
+            size_t blobSize = sizeof(ILStubHashBlobBase) + sizeof(pTargetMD);
```
Comment (jkotas) [inline src/coreclr/vm/dllimport.cpp]: We need to guarantee that there is no collision between the blobs created by this path and the PInvokeStubHashBlobs created by the path below.

I think it is guaranteed by this `blobSize` being always smaller than `sizeof(PInvokeStubHashBlob)`. Should we assert it and/or add a comment about it?

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/dllimport.cpp (hunk 3 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/dllimport.cpp]: Done.
