### PR TITLE
fix lower heap hard limit condition for regions

### LINKED ISSUE #76199: .NET 7.0.100-preview.7.22377.5 threw an exception in docker (docker-in-docker with devcontainer - Ubuntu 20.4)
### Description

I used `devcontainer` on `vscode` to create the `Ubuntu 20.4` with `docker in docker` approach. I packaged the .NET 7 Preview 7 application into the docker container. When I run its image inside devcontainer, then it keeps silent. Then I put the variables `COREHOST_TRACE = 1`. Then I see a lot of exceptions there. See below

```bash
Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libcoreclr.so], probe dir [], probe fx level:0, entry fx level:2

    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libcoreclr.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libcoreclr.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libcoreclr.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libcoreclr.so'
Processing native/culture for deps entry [Microsoft.NETCore.App.Runtime.linux-x64, 7.0.0-preview.7.22375.6, libcoreclrtraceptprovider.so]
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libcoreclrtraceptprovider.so], probe dir [], probe fx level:0, entry fx level:2
    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libcoreclrtraceptprovider.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libcoreclrtraceptprovider.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libcoreclrtraceptprovider.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libcoreclrtraceptprovider.so'
Processing native/culture for deps entry [Microsoft.NETCore.App.Runtime.linux-x64, 7.0.0-preview.7.22375.6, libmscordaccore.so]
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libmscordaccore.so], probe dir [], probe fx level:0, entry fx level:2
    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libmscordaccore.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libmscordaccore.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libmscordaccore.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libmscordaccore.so'
Processing native/culture for deps entry [Microsoft.NETCore.App.Runtime.linux-x64, 7.0.0-preview.7.22375.6, libmscordbi.so]
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libmscordbi.so], probe dir [], probe fx level:0, entry fx level:2
    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libmscordbi.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libmscordbi.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libmscordbi.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libmscordbi.so'
Processing native/culture for deps entry [Microsoft.NETCore.App.Runtime.linux-x64, 7.0.0-preview.7.22375.6, libSystem.Globalization.Native.so]
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Globalization.Native.so], probe dir [], probe fx level:0, entry fx level:2
    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Globalization.Native.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Globalization.Native.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.Globalization.Native.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.Globalization.Native.so'
Processing native/culture for deps entry [Microsoft.NETCore.App.Runtime.linux-x64, 7.0.0-preview.7.22375.6, libSystem.IO.Compression.Native.so]
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.IO.Compression.Native.so], probe dir [], probe fx level:0, entry fx level:2
    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.IO.Compression.Native.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.IO.Compression.Native.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.IO.Compression.Native.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.IO.Compression.Native.so'
Processing native/culture for deps entry [Microsoft.NETCore.App.Runtime.linux-x64, 7.0.0-preview.7.22375.6, libSystem.Native.so]
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Native.so], probe dir [], probe fx level:0, entry fx level:2
    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Native.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Native.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.Native.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.Native.so'
Processing native/culture for deps entry [Microsoft.NETCore.App.Runtime.linux-x64, 7.0.0-preview.7.22375.6, libSystem.Net.Security.Native.so]
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Net.Security.Native.so], probe dir [], probe fx level:0, entry fx level:2
    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Net.Security.Native.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Net.Security.Native.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.Net.Security.Native.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.Net.Security.Native.so'
Processing native/culture for deps entry [Microsoft.NETCore.App.Runtime.linux-x64, 7.0.0-preview.7.22375.6, libSystem.Security.Cryptography.Native.OpenSsl.so]
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Security.Cryptography.Native.OpenSsl.so], probe dir [], probe fx level:0, entry fx level:2
    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Security.Cryptography.Native.OpenSsl.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libSystem.Security.Cryptography.Native.OpenSsl.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.Security.Cryptography.Native.OpenSsl.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libSystem.Security.Cryptography.Native.OpenSsl.so'
Processing native/culture for deps entry [Microsoft.NETCore.App.Runtime.linux-x64, 7.0.0-preview.7.22375.6, libhostpolicy.so]
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libhostpolicy.so], probe dir [], probe fx level:0, entry fx level:2
    Skipping... not found in deps dir '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6'
    Skipping... not found in probe dir ''
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libhostpolicy.so], probe dir [/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6], probe fx level:1, entry fx level:2
    Skipping... not found in deps json.
    Skipping... not found in probe dir '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6'
  Considering entry [Microsoft.NETCore.App.Runtime.linux-x64/7.0.0-preview.7.22375.6/libhostpolicy.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6], probe fx level:2, entry fx level:2
    Local path query /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libhostpolicy.so (skipped file existence check)
    Probed deps json and matched '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libhostpolicy.so'
Property System.Reflection.NullabilityInfoContext.IsSupported = true
Property System.Reflection.Metadata.MetadataUpdater.IsSupported = false
Property System.GC.Server = true
Property RUNTIME_IDENTIFIER = debian.11-x64
Property System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization = false
Property FX_DEPS_FILE = /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/Microsoft.NETCore.App.deps.json
Property APP_CONTEXT_DEPS_FILES = /app/ProductService.deps.json;/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.App.deps.json;/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/Microsoft.NETCore.App.deps.json
Property APP_CONTEXT_BASE_DIRECTORY = /app/
Property PLATFORM_RESOURCE_ROOTS = 
Property PROBING_DIRECTORIES = 
Property NATIVE_DLL_SEARCH_DIRECTORIES = /app/runtimes/linux-x64/native/:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/:
Property TRUSTED_PLATFORM_ASSEMBLIES = /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Xml.XPath.XDocument.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.Tasks.Parallel.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.Tasks.Dataflow.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.Channels.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Text.RegularExpressions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Text.Encoding.CodePages.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Principal.Windows.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.AccessControl.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Serialization.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Serialization.Formatters.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Numerics.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.InteropServices.JavaScript.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.InteropServices.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Resources.Writer.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Reflection.DispatchProxy.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Private.Xml.Linq.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Reflection.Metadata.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Private.Xml.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Private.Uri.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Private.DataContractSerialization.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ObjectModel.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.WebSockets.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.WebProxy.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.WebClient.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.Sockets.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.ServicePoint.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.Security.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.Requests.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.NetworkInformation.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.NameResolution.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.HttpListener.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Memory.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Linq.Parallel.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Linq.Expressions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.Pipes.AccessControl.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.MemoryMappedFiles.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.IsolatedStorage.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.FileSystem.Watcher.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.FileSystem.DriveInfo.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.FileSystem.AccessControl.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.Compression.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Formats.Tar.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.TextWriterTraceListener.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Cryptography.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.StackTrace.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.FileVersionInfo.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.DiagnosticSource.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Data.Common.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.Process.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Console.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Collections.Specialized.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Collections.NonGeneric.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Collections.Immutable.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/Microsoft.Win32.Registry.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/WindowsBase.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Xml.XPath.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Xml.XmlSerializer.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Xml.XDocument.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Xml.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Windows.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ValueTuple.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.Timer.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.Tasks.Extensions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.Tasks.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Text.Encoding.Extensions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ServiceProcess.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.SecureString.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Principal.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Cryptography.Encoding.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Cryptography.Csp.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Cryptography.Cng.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Cryptography.Algorithms.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Serialization.Json.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Serialization.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Loader.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.InteropServices.RuntimeInformation.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Handles.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Server.IISIntegration.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ComponentModel.Annotations.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.Xml.dll:/app/ProductService.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Xml.Serialization.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Logging.TraceSource.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Logging.EventSource.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Cors.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.SignalR.Protocols.Json.dll:/app/OpenTelemetry.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Logging.Console.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Http.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Cryptography.X509Certificates.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.FileSystem.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Hosting.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.FileSystemGlobbing.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.FileProviders.Embedded.dll:/app/Serilog.Sinks.File.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ServiceModel.Web.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.DependencyInjection.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Logging.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.WebUtilities.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Core.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.UserSecrets.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.ResponseCaching.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ComponentModel.DataAnnotations.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.CommandLine.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.Binder.dll:/app/Bogus.dll:/app/Confluent.SchemaRegistry.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Localization.Routing.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Authentication.Cookies.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Http.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Linq.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.HttpsPolicy.dll:/app/OpenTelemetry.Exporter.Console.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Server.Kestrel.Core.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.Json.dll:/app/Serilog.Extensions.Logging.dll:/app/CoffeeShop.Contracts.dll:/app/System.Windows.Extensions.dll:/app/System.Security.Permissions.dll:/app/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Text.Encoding.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Html.Abstractions.dll:/app/System.IdentityModel.Tokens.Jwt.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.SignalR.Common.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.Quic.dll:/app/runtimes/unix/lib/netcoreapp3.0/System.Drawing.Common.dll:/app/System.Configuration.ConfigurationManager.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.Compression.ZipFile.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.HttpOverrides.dll:/app/Swashbuckle.AspNetCore.SwaggerUI.dll:/app/Spectre.Console.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Hosting.Server.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Transactions.Local.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Cryptography.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/netstandard.dll:/app/Swashbuckle.AspNetCore.Swagger.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.FileProviders.Composite.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Logging.Configuration.dll:/app/Serilog.Formatting.Compact.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.DependencyInjection.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Http.Abstractions.dll:/app/Serilog.Sinks.Seq.dll:/app/Serilog.Sinks.Elasticsearch.dll:/app/Serilog.Sinks.Console.dll:/app/N8T.Infrastructure.EfCore.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.ThreadPool.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Logging.EventLog.dll:/app/StackExchange.Redis.dll:/app/Microsoft.EntityFrameworkCore.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.Ping.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Buffers.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/System.Security.Cryptography.Xml.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Web.HttpUtility.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Text.Json.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.ObjectPool.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/Microsoft.VisualBasic.Core.dll:/app/MediatR.Contracts.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/Microsoft.CSharp.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Reflection.Emit.Lightweight.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.Debug.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ComponentModel.TypeConverter.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.FileExtensions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Hosting.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.FileProviders.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Localization.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Claims.dll:/app/Microsoft.IdentityModel.JsonWebTokens.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.StaticFiles.dll:/app/N8T.Core.dll:/app/RabbitMQ.Client.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.WebSockets.Client.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Security.Cryptography.OpenSsl.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.WebSockets.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.AppContext.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.Contracts.dll:/app/Microsoft.Extensions.Caching.StackExchangeRedis.dll:/app/Google.Protobuf.dll:/app/Google.Api.CommonProtos.dll:/app/MediatR.Extensions.Microsoft.DependencyInjection.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Antiforgery.dll:/app/Scrutor.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.dll:/app/Serilog.Expressions.dll:/app/Microsoft.Win32.SystemEvents.dll:/app/Pipelines.Sockets.Unofficial.dll:/app/Microsoft.EntityFrameworkCore.Abstractions.dll:/app/RestEase.HttpClientFactory.dll:/app/Serilog.dll:/app/Confluent.Kafka.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Primitives.dll:/app/Microsoft.IdentityModel.Logging.dll:/app/MassTransit.RabbitMqTransport.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Diagnostics.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Intrinsics.dll:/app/Dapr.AspNetCore.dll:/app/Dapr.Client.dll:/app/System.CodeDom.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Rewrite.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.dll:/app/System.Security.Cryptography.ProtectedData.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/System.Diagnostics.EventLog.dll:/app/Npgsql.EntityFrameworkCore.PostgreSQL.dll:/app/Confluent.SchemaRegistry.Serdes.Avro.dll:/app/Newtonsoft.Json.dll:/app/Microsoft.AspNetCore.Authentication.JwtBearer.dll:/app/MediatR.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Server.IIS.dll:/app/MassTransit.dll:/app/Microsoft.Extensions.PlatformAbstractions.dll:/app/EFCore.NamingConventions.dll:/app/Serilog.Sinks.PeriodicBatching.dll:/app/MassTransit.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Options.ConfigurationExtensions.dll:/app/Serilog.Sinks.Debug.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Transactions.dll:/app/Microsoft.EntityFrameworkCore.Relational.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Numerics.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.Pipes.dll:/app/Elasticsearch.Net.dll:/app/OpenTelemetry.Instrumentation.Http.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Authentication.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/Microsoft.VisualBasic.dll:/app/OpenTelemetry.Extensions.Hosting.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.Localization.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ComponentModel.EventBasedAsync.dll:/app/Serilog.Formatting.Elasticsearch.dll:/app/Avro.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Formats.Asn1.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Xml.Linq.dll:/app/OpenTelemetry.Instrumentation.MassTransit.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.HostFiltering.dll:/app/Microsoft.IdentityModel.Protocols.OpenIdConnect.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Extensions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.Cors.dll:/app/OpenTelemetry.Api.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Collections.Concurrent.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Http.Connections.Common.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ComponentModel.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Logging.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.ComponentModel.Primitives.dll:/app/Swashbuckle.AspNetCore.SwaggerGen.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Diagnostics.HealthChecks.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Options.dll:/app/Microsoft.OpenApi.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.FileProviders.Physical.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.ApiExplorer.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Options.DataAnnotations.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Web.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Caching.Abstractions.dll:/app/Npgsql.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Components.Web.dll:/app/OpenTelemetry.Instrumentation.AspNetCore.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.Http.Json.dll:/app/Polly.dll:/app/Grpc.Net.Client.dll:/app/Microsoft.Extensions.DependencyModel.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Xml.ReaderWriter.dll:/app/Serilog.Extensions.Hosting.dll:/app/RestEase.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.EnvironmentVariables.dll:/app/Serilog.AspNetCore.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Authentication.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.Ini.dll:/app/System.Diagnostics.PerformanceCounter.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Globalization.Extensions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Authentication.Core.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Authentication.OAuth.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Authorization.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Collections.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Authorization.Policy.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Drawing.Primitives.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Components.Authorization.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Reflection.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Components.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Components.Forms.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Http.Results.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Connections.Abstractions.dll:/app/Grpc.Core.Api.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.CookiePolicy.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Cryptography.Internal.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.Overlapped.dll:/app/Microsoft.IdentityModel.Protocols.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Cryptography.KeyDerivation.dll:/app/Serilog.Settings.Configuration.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.DataProtection.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Components.Server.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.Formatters.Json.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Diagnostics.Abstractions.dll:/app/N8T.Infrastructure.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Configuration.KeyPerFile.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.Http.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Hosting.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Session.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Hosting.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Reflection.TypeExtensions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Http.Connections.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Http.Extensions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Http.Features.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.HttpLogging.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.CompilerServices.Unsafe.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.DataProtection.Extensions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.DataAnnotations.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Metadata.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Identity.Core.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Logging.Debug.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.Core.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Text.Encodings.Web.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.Formatters.Xml.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.Razor.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Xml.XmlDocument.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.Tools.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.RazorPages.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.TagHelpers.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/System.Security.Cryptography.Pkcs.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.OutputCaching.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.TraceSource.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Razor.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Razor.Runtime.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Features.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.DataProtection.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.RequestDecompression.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.ResponseCaching.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.ResponseCompression.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Routing.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Server.HttpSys.dll:/app/FluentValidation.DependencyInjectionExtensions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Diagnostics.HealthChecks.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Identity.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Server.Kestrel.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Private.CoreLib.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.Compression.Brotli.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.SignalR.Core.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.WebHeaderCollection.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/Microsoft.Win32.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Threading.Thread.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.ViewFeatures.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.SignalR.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Localization.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Identity.Stores.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Localization.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.WebEncoders.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/mscorlib.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.JSInterop.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Configuration.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Data.DataSetExtensions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Data.dll:/app/FluentValidation.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Net.Http.Headers.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Diagnostics.Tracing.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Routing.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Drawing.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.Mail.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Dynamic.Runtime.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.Serialization.Xml.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Globalization.dll:/app/TimeZoneConverter.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.Compression.FileSystem.dll:/app/Microsoft.IdentityModel.Tokens.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.FileSystem.Primitives.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/System.IO.Pipelines.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.IO.UnmanagedMemoryStream.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Numerics.Vectors.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Linq.Queryable.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Reflection.Emit.dll:/app/Grpc.Net.Common.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Reflection.Emit.ILGeneration.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.AspNetCore.Mvc.Abstractions.dll:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.0-preview.7.22376.6/Microsoft.Extensions.Caching.Memory.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Net.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Reflection.Extensions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Runtime.CompilerServices.VisualC.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Globalization.Calendars.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Reflection.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Resources.Reader.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Resources.ResourceManager.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/System.Private.CoreLib.dll
CoreCLR path = '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libcoreclr.so', CoreCLR dir = '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/'
Failed to create CoreCLR, HRESULT: 0x8007000E
```

I expect it can run normally, because when I created the Azure VM (Ubuntu 20.4 distro), no problems with this Docker image. It can run on Azure VM (Ubuntu 20.4) normally.

### Configuration

* Which version of .NET is the code running on?

7.0.100-preview.7.22377.57.0.100-preview.7.22377.5

* What OS and version, and for Linux, what distro?

```bash
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

And just the same distro info on Azure Ubuntu 20.4 box as below

```bash

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* What is the architecture (x64, x86, ARM, ARM64)
My host: Windows 11 x64
devcontainer - Ubuntu 20.4 (docker in docker)

### Other information

When I type `uname -a` on the devcontainer box, I see the information like

```bash
Linux 06f0c99566da 5.15.57.1-microsoft-standard-WSL2 dotnet/core#1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

But when I type the same command on the Azure VM - Ubuntu 20.4 box, I see different:

```bash
Linux nomad-vm 5.15.0-1017-azure dotnet/core#20~20.04.1-Ubuntu SMP Fri Aug 5 12:16:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I just wonder that, is it caused this exception because of the different of OS distro on two boxes? Any one can help me to solve this issue?

The source code can be found at https://github.com/thangchung/coffeeshop-on-nomad
My Dockerfile: https://github.com/thangchung/coffeeshop-on-nomad/blob/main/src/ProductService/Dockerfile

### PR DESCRIPTION
**Pull request by mangod9**
Fixes https://github.com/dotnet/runtime/issues/76199, where containers < 512mb were failing with E_OOM during GC initialization, since the check for `region_size * heaps * 19 (various generations) < reservation size ` was failing.

The logic is to now dynamically adjust region_size for smaller heap sizes. So for very small heap_hard_limits the region_size would be 1mb (instead of the default 4mb currently)

### CODE REVIEW

File: src/coreclr/gc/gc.cpp [hunk 1]
```diff
@@ -44894,10 +44894,13 @@ HRESULT GCHeap::Initialize()
...
         {
-            gc_heap::regions_range = 2 * gc_heap::heap_hard_limit;
+            // Keep the reservation size for regions similar to that for segments. 
+            // We will initially reserve 6x the configured hard limit
+            gc_heap::regions_range = 6 * gc_heap::heap_hard_limit;
         }
         else
         {
+            // If no hard_limit is configured the reservation size is max of 256gb or 2x physical limit
             gc_heap::regions_range = max(((size_t)256 * 1024 * 1024 * 1024), (size_t)(2 * gc_heap::total_physical_mem));
```
Comment (mangod9) [inline src/coreclr/gc/gc.cpp:44904]: guess 2x here is fine?

**Comment by mangod9** [comment]
with the latest change, the lowest hard_limit possible is `0x400000` (4mb)

File: src/coreclr/gc/gc.cpp [hunk 2]
```diff
@@ -44894,10 +44894,21 @@ HRESULT GCHeap::Initialize()
...
         {
-            gc_heap::regions_range = 2 * gc_heap::heap_hard_limit;
+            if (gc_heap::heap_hard_limit_oh[soh])
+            {
+                gc_heap::regions_range = gc_heap::heap_hard_limit;
+            }
+            else
+            {
+                // We will initially reserve 5x the configured hard limit and 2x if
+                // large pages are enabled as this is closer to segments
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:44904]:
```suggestion
                // We will this calculation because it's close to what we used for segments.
```

File: src/coreclr/gc/gc.cpp [hunk 3]
```diff
@@ -44894,10 +44894,21 @@ HRESULT GCHeap::Initialize()
...
+                gc_heap::regions_range = ((gc_heap::use_large_pages_p) ? (2 * gc_heap::heap_hard_limit)  // large pages
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:44905]:
```suggestion
                gc_heap::regions_range = ((gc_heap::use_large_pages_p) ? (2 * gc_heap::heap_hard_limit)
```

no need to say `// large pages` because that's exactly what `use_large_pages_p` says

File: src/coreclr/gc/gc.cpp [hunk 4]
```diff
@@ -45044,7 +45055,28 @@ HRESULT GCHeap::Initialize()
...
+            gc_region_size = 4 * 1024 * 1024;
+        }
+        else if ((gc_heap::regions_range / nhp / min_regions_per_heap) / 2 >= (2 * 1024 * 1024))
+        {
+            gc_region_size = 2 * 1024 * 1024;
+        }
+        else
+        {
+            gc_region_size = 1 * 1024 * 1024;
+        }
```
Comment (Maoni0) [inline src/coreclr/gc/gc.cpp:45076]:
```suggestion
        // We have a minimum amount of basic regions we have to fit per heap, and we'd like to have the initial
        // regions only take up half of the space.
        size_t max_region_size = gc_heap::regions_range / 2 / nhp / min_regions_per_heap;
        if (max_region_size >= (4 * 1024 * 1024))
        {
            gc_region_size = 4 * 1024 * 1024;
        }
        else if (max_region_size >= (2 * 1024 * 1024))
        {
            gc_region_size = 2 * 1024 * 1024;
        }
        else
        {
            gc_region_size = 1 * 1024 * 1024;
        }
```

**Review by Maoni0 — APPROVED** [review]
other than the nit above, it LGTM

**Comment by mangod9** [comment]
The Hardware Instrinsics failure looks related to: https://github.com/dotnet/runtime/issues/76280. Other PRs are failing with that same failure. Need to port to 7 hence merging.
