### PR TITLE
Remove useless assert from assertprop

### LINKED ISSUE #114275: Assertion failed '!stmt->IsPhiDefnStmt()' during 'Assertion prop'
```c#
// Found by Antigen
// Reduced from 52.21 KB to 6.06 KB.


using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;
using System.Numerics;
public class TestClass_Phi
{
    public struct S1
    {
        public int int_0;
    }
    public struct S2
    {
    }
    static long s_long_10 = 0;
    static S1 s_s1_18 = new S1();
    static S2 s_s2_19 = new S2();
    int int_26 = -1;
    ulong ulong_33 = 5;
    private static List<string> toPrint = new List<string>();
    [MethodImpl(MethodImplOptions.NoInlining)]
    public int LeafMethod6()
    {
        unchecked
        {
            return s_s1_18.int_0;
        }
    }
    public ulong Method2(uint p_uint_59, ulong p_ulong_60, ref S2 p_s2_61, out S2 p_s2_62)
    {
        unchecked
        {
            long long_70 = 2;
            S1 s1_78 = new S1();
            try
            {
                switch (LeafMethod6() * int_26)
                {
                    case 83:
                        {
                            break;
                        }
                    case 0:
                        {
                            break;
                        }
                    case -5:
                        {
                            if (15 == 4)
                            {
                            }
                            else
                            {
                                switch (s_long_10)
                                {
                                    case 2:
                                        {
                                            switch (s1_78.int_0 -= 15 - 4 ^ 15 - 4 + LeafMethod6() * int_26)
                                            {
                                                case 0:
                                                    {
                                                        break;
                                                    }
                                                case -1:
                                                    {
                                                        break;
                                                    }
                                                case 83:
                                                    {
                                                        break;
                                                    }
                                                case -2:
                                                    {
                                                        break;
                                                    }
                                                case 2:
                                                    {
                                                        break;
                                                    }
                                                case -5:
                                                    {
                                                        break;
                                                    }
                                                case 1:
                                                    {
                                                        LeafMethod6();
                                                        break;
                                                    }
                                                case 2147483647:
                                                    {
                                                        break;
                                                    }
                                                default:
                                                    {
                                                        break;
                                                    }
                                            }
                                            break;
                                        }
                                    case 83:
                                        {
                                            switch (long_70 *= s_long_10 ^ s_long_10)
                                            {
                                                case 2147483646:
                                                    {
                                                        LeafMethod6();
                                                        break;
                                                    }
                                                case -2:
                                                    {
                                                        break;
                                                    }
                                                case 2:
                                                    {
                                                        break;
                                                    }
                                                case -5:
                                                    {
                                                        break;
                                                    }
                                                case 5:
                                                    {
                                                        break;
                                                    }
                                                case 83:
                                                    {
                                                        break;
                                                    }
                                                default:
                                                    {
                                                        break;
                                                    }
                                            }
                                            break;
                                        }
                                    default:
                                        {
                                            break;
                                        }
                                }
                            }
                            s1_78.int_0 /= int_26 - int_26 | 27;
                            break;
                        }
                    case 1:
                        {
                            break;
                        }
                    default:
                        {
                            break;
                        }
                }
            }
            finally
            {
            }
            return 15 ^ 4;
        }
    }
    public void Method0()
    {
        unchecked
        {
            ulong_33 = Method2(15 | 4, 15 | 4, ref s_s2_19, out s_s2_19);
            return;
        }
    }
    public static int Main(string[] args)
    {
        return Antigen();
    }
    public static int Antigen()
    {
        new TestClass_Phi().Method0();
        return string.Join(Environment.NewLine, toPrint).GetHashCode();
    }
}
/*
Environment:

set DOTNET_TieredCompilation=0

JIT assert failed:
Assertion failed '!stmt->IsPhiDefnStmt()' in 'TestClass:Method2(uint,ulong,byref,byref):ulong:this' during 'Assertion prop' (IL size 298; hash 0x7f2c2e27; FullOpts)

    File: /Users/runner/work/1/s/src/coreclr/jit/assertionprop.cpp Line: 5664


*/
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/114275

It seems like it's totally fine to have PHI in blocks with single predecessor being a single edge to BBJ_SWITCH. Such PHI statements usually appear after RBO phase, in this case it's:
```
------------ BB11 [0023] [104..10B) -> BB12(1) (always), preds={BB07} succs={BB12}

***** BB11 [0023]
STMT00034 ( ??? ... ??? )
N004 (  0,  0) [000166] DA---------                         *  STORE_LCL_VAR int    V16 tmp4         d:4 $VN.Void
N003 (  0,  0) [000165] -----------                         \--*  PHI       int    <l:$107, c:$108>
N001 (  0,  0) [000173] ----------- pred BB10                  +--*  PHI_ARG   int    V16 tmp4         u:2
N002 (  0,  0) [000168] ----------- pred BB07                  \--*  PHI_ARG   int    V16 tmp4         u:3 <l:$107, c:$108>
```
where BB07 is the switch root. BB10 was unlinked by Redundant branch opt phase

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @AndyAyersMS @dotnet/jit-contrib

**Review by AndyAyersMS — COMMENTED** [review]
Instead of doing this, can you just insert the new code after any PHIs?

Existing code does not expect to see non-PHI code above PHIs.

File: src/coreclr/jit/assertionprop.cpp [hunk 1]
```diff
@@ -5722,7 +5722,25 @@ bool Compiler::optCreateJumpTableImpliedAssertions(BasicBlock* switchBb)
...
+            if (curStmt == nullptr)
+            {
+                // The block is either empty or contains only PHI stmt(s).
+                fgInsertStmtAtEnd(target, fgNewStmtFromTree(tree));
+            }
+            else
+            {
+                // Insert the NOP before the first non-PHI stmt.
+                fgInsertStmtBefore(target, curStmt, fgNewStmtFromTree(tree));
+            }
```
Comment (jakobbotsch) [inline src/coreclr/jit/assertionprop.cpp:5742]: `fgInsertStmtAtBeg` already inserts after the first phi node, so this is probably unnecessary.

Comment (EgorBo) [reply src/coreclr/jit/assertionprop.cpp:5742]: I was addressing Andy's feedback, but looks like indeed it was correct as is, thanks!

**Review by jakobbotsch — APPROVED** [review]
