### PR TITLE
Fix ShuffleThunk cache heap

### LINKED ISSUE #55697: Problem with shuffle thunks tracking in collectible AssemblyLoaderAllocator
The unloadability features in runtime don't track the lifetime of the shuffle thunks or the related delegate classes (looks like it happens only for delegates pointing to static methods) and when I have attempted to allocate them from the stub heap of the respective collectible loader allocator, they ended up being used after the loader allocator was destroyed and their underlying memory unmapped. That obviously resulted in crashes.

We should figure out how to track then in a way that would keep the loader allocator alive until all the shuffle thunks belonging to that allocator are destroyed.

### PR DESCRIPTION
**Pull request by janvorli**
There was a problem with using heap from the related LoaderAllocator for shuffle thunk cache heap when I was working on the unloadability stuff a long time ago. I have tested it again now and it seems that the issue is gone.

So I am removing the workaround, making the cache use LoaderAllocator local heap.

Close #55697

### CODE REVIEW

File: src/coreclr/vm/loaderallocator.cpp [hunk 1]
```diff
@@ -1734,11 +1734,7 @@ void AssemblyLoaderAllocator::Init(AppDomain* pAppDomain)
     LoaderAllocator::Init((BaseDomain *)pAppDomain);
     if (IsCollectible())
     {
-        // TODO: the ShuffleThunkCache should really be using the m_pStubHeap, however the unloadability support
-        // doesn't track the stubs or the related delegate classes and so we get crashes when a stub is used after
-        // the AssemblyLoaderAllocator is gone (the stub memory is unmapped).
-        // https://github.com/dotnet/runtime/issues/55697 tracks this issue.
```
Comment (mangod9) [inline src/coreclr/vm/loaderallocator.cpp:1740]: was there any recent change which made tracking of stubs during unload? Just want to check whether it might still cause intermittent issues?

Comment (janvorli) [reply src/coreclr/vm/loaderallocator.cpp:1740]: I am not aware of a specific change in this area, however, it has been a couple of years since I have experienced the problem when developing the unloadability. And even at that time, I was unable to tell how that could happen.

**Review by mangod9 — APPROVED** [review]

File: src/coreclr/vm/loaderallocator.cpp (hunk 1 above)
Comment (janvorli) [reply src/coreclr/vm/loaderallocator.cpp:1740]: It is possible that there is still a problem hidden somewhere and happening rarely. I will try to run some extra gc stress tests when running the tests in an unloadable context.

**Review by jkotas — APPROVED** [review]
