### PR TITLE
[metadata_update] Fix bounds check error

### LINKED ISSUE #49227: [mono] ApplyDelta results in BadImageFormatException
```
Unhandled exception rendering component: Image with invalid assemblyref token 0000000f.
System.BadImageFormatException: Image with invalid assemblyref token 0000000f.
```

@lambdageek was able to reproduce using the `mono/sample/mbr/console` sample with this using these changes in `TestClass.cs`:

```C#
string s = "OLD STRING";
Console.WriteLine ("L = {0}", s.Skip(1).FirstOrDefault());

string s = "NEW STRING";
Console.WriteLine ("W = {0}", s.Skip(2).FirstOrDefault());
```

### PR DESCRIPTION
**Pull request by lambdageek**
The issue is that the STANDALONESIG bounds check was using a 0-based index, and `mono_metadata_bounds_check_slow` was compensating by adding 1.

But that made another call to the bounds check fail: in `mono_class_from_typeref_checked` we passed a 1-based index.  So in the case where a TypeRef was using the last AssemblyRef in a delta, the bound check would fail.

Fixes https://github.com/dotnet/runtime/issues/49227

### CODE REVIEW

File: src/mono/mono/metadata/metadata.c [hunk 1]
```diff
@@ -4779,7 +4783,7 @@ mono_metadata_parse_mh_full (MonoImage *m, MonoGenericContainer *container, cons
 
 	if (local_var_sig_tok) {
 		int idx = mono_metadata_token_index (local_var_sig_tok) - 1;
-		if (mono_metadata_table_bounds_check (m, MONO_TABLE_STANDALONESIG, idx)) {
+		if (mono_metadata_table_bounds_check (m, MONO_TABLE_STANDALONESIG, idx+1)) {
```
Comment (CoffeeFlux) [inline src/mono/mono/metadata/metadata.c:4786]:
```suggestion
		if (mono_metadata_table_bounds_check (m, MONO_TABLE_STANDALONESIG, idx + 1)) {
```

**Review by CoffeeFlux — APPROVED** [review]

**Comment by lambdageek** [comment]
I think the bug in `mono_metadata_parse_mh_full` was introduced 11 years ago https://github.com/dotnet/runtime/commit/f0fb2ab90eab4fe7dbf529e1b2c5adce14b1b982#diff-9bdd29ef9d9416cf265f270850102b27e2d0c580567dc8c5b5f1fc4d3527e1adR3455
