### PR TITLE
[HTTP/3] Release the stream once the response is sent

### LINKED ISSUE #90603: [Test Failure]: System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue
### Error Blob

```json
{
  "ErrorMessage": "Child exception: System.AggregateException: One or more errors occurred. (Assert.True() Failure Expected: True Actual: False) (Connection aborted by peer (256).)",
  "BuildRetry": false,
  "ErrorPattern": "Connection aborted by peer",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

_No response_

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=372621
**Error message validated:** `Connection aborted by peer`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/15/2023 4:49:13 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[387742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387742)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387742&view=ms.vss-test-web.build-test-results-tab&runId=8305302&resultId=102701)||
|[387729](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387729)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387729&view=ms.vss-test-web.build-test-results-tab&runId=8305524&resultId=102102)||
|[387732](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387732)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387732&view=ms.vss-test-web.build-test-results-tab&runId=8304826&resultId=104261)||
|[387731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387731)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387731&view=ms.vss-test-web.build-test-results-tab&runId=8304790&resultId=104261)||
|[387745](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387745)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387745&view=ms.vss-test-web.build-test-results-tab&runId=8305336&resultId=104611)||
|[387728](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387728)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387728&view=ms.vss-test-web.build-test-results-tab&runId=8305502&resultId=102309)||
|[387265](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387265)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387265&view=ms.vss-test-web.build-test-results-tab&runId=8291862&resultId=104261)||
|[387266](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387266)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387266&view=ms.vss-test-web.build-test-results-tab&runId=8291842&resultId=104261)||
|[387273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387273)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387273&view=ms.vss-test-web.build-test-results-tab&runId=8292210&resultId=102819)||
|[387263](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387263)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387263&view=ms.vss-test-web.build-test-results-tab&runId=8292116&resultId=104611)||
|[387271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387271)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387271&view=ms.vss-test-web.build-test-results-tab&runId=8292378&resultId=102082)||
|[387270](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387270)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387270&view=ms.vss-test-web.build-test-results-tab&runId=8292188&resultId=102742)||
|[386871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386871)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386871&view=ms.vss-test-web.build-test-results-tab&runId=8277024&resultId=102699)||
|[386869](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386869)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386869&view=ms.vss-test-web.build-test-results-tab&runId=8276684&resultId=104261)||
|[386856](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386856)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386856&view=ms.vss-test-web.build-test-results-tab&runId=8276642&resultId=104261)||
|[386858](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386858)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386858&view=ms.vss-test-web.build-test-results-tab&runId=8277004&resultId=102755)||
|[386855](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386855)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386855&view=ms.vss-test-web.build-test-results-tab&runId=8276882&resultId=104611)||
|[386870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386870)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386870&view=ms.vss-test-web.build-test-results-tab&runId=8277134&resultId=100722)||
|[386662](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386662)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ReservedFrameType_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=386662&view=ms.vss-test-web.build-test-results-tab&runId=8269452&resultId=204383)||
|[385889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385889)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385889&view=ms.vss-test-web.build-test-results-tab&runId=8247444&resultId=102603)||
|[385887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385887)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385887&view=ms.vss-test-web.build-test-results-tab&runId=8246936&resultId=104261)||
|[385896](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385896)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385896&view=ms.vss-test-web.build-test-results-tab&runId=8246942&resultId=104261)||
|[385897](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385897)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385897&view=ms.vss-test-web.build-test-results-tab&runId=8247428&resultId=104611)||
|[385901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385901)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385901&view=ms.vss-test-web.build-test-results-tab&runId=8247408&resultId=102884)||
|[385886](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385886)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385886&view=ms.vss-test-web.build-test-results-tab&runId=8247638&resultId=103975)||
|[385538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385538)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ReservedFrameType_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385538&view=ms.vss-test-web.build-test-results-tab&runId=8233834&resultId=200010)||
|[385208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385208)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ReservedFrameType_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385208&view=ms.vss-test-web.build-test-results-tab&runId=8228888&resultId=204383)||
|[384638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384638)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384638&view=ms.vss-test-web.build-test-results-tab&runId=8212654&resultId=104611)||
|[384625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384625)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384625&view=ms.vss-test-web.build-test-results-tab&runId=8212594&resultId=104611)||
|[384629](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384629)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384629&view=ms.vss-test-web.build-test-results-tab&runId=8212774&resultId=102821)||
|[384619](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384619)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384619&view=ms.vss-test-web.build-test-results-tab&runId=8212312&resultId=104261)||
|[384637](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384637)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384637&view=ms.vss-test-web.build-test-results-tab&runId=8212998&resultId=100010)||
|[384622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384622)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384622&view=ms.vss-test-web.build-test-results-tab&runId=8212750&resultId=102675)||
|[383382](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383382)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383382&view=ms.vss-test-web.build-test-results-tab&runId=8179720&resultId=102648)||
|[383378](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383378)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383378&view=ms.vss-test-web.build-test-results-tab&runId=8179574&resultId=104611)||
|[383385](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383385)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383385&view=ms.vss-test-web.build-test-results-tab&runId=8179380&resultId=104261)||
|[383379](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383379)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383379&view=ms.vss-test-web.build-test-results-tab&runId=8179338&resultId=104261)||
|[383376](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383376)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383376&view=ms.vss-test-web.build-test-results-tab&runId=8179848&resultId=102219)||
|[383381](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383381)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=383381&view=ms.vss-test-web.build-test-results-tab&runId=8179814&resultId=100086)||
|[382008](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382008)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382008&view=ms.vss-test-web.build-test-results-tab&runId=8149976&resultId=102690)||
|[382021](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382021)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382021&view=ms.vss-test-web.build-test-results-tab&runId=8149448&resultId=104261)||
|[382016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382016)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382016&view=ms.vss-test-web.build-test-results-tab&runId=8149342&resultId=104261)||
|[382012](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382012)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382012&view=ms.vss-test-web.build-test-results-tab&runId=8150060&resultId=102095)||
|[382015](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382015)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382015&view=ms.vss-test-web.build-test-results-tab&runId=8149846&resultId=104611)||
|[382007](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382007)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=382007&view=ms.vss-test-web.build-test-results-tab&runId=8149900&resultId=102633)||
|[380646](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380646)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380646&view=ms.vss-test-web.build-test-results-tab&runId=8113950&resultId=104261)||
|[380640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380640)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380640&view=ms.vss-test-web.build-test-results-tab&runId=8113868&resultId=104261)||
|[380648](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380648)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380648&view=ms.vss-test-web.build-test-results-tab&runId=8114280&resultId=102515)||
|[380634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380634)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380634&view=ms.vss-test-web.build-test-results-tab&runId=8114452&resultId=102244)||
|[380633](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380633)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380633&view=ms.vss-test-web.build-test-results-tab&runId=8114150&resultId=104611)||
|[380632](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380632)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380632&view=ms.vss-test-web.build-test-results-tab&runId=8114430&resultId=100594)||
|[380105](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380105)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380105&view=ms.vss-test-web.build-test-results-tab&runId=8099154&resultId=104261)||
|[380120](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380120)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380120&view=ms.vss-test-web.build-test-results-tab&runId=8099122&resultId=104261)||
|[380117](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380117)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380117&view=ms.vss-test-web.build-test-results-tab&runId=8099622&resultId=102699)||
|[380122](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380122)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380122&view=ms.vss-test-web.build-test-results-tab&runId=8099724&resultId=102141)||
|[380114](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380114)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380114&view=ms.vss-test-web.build-test-results-tab&runId=8099542&resultId=104611)||
|[380107](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380107)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380107&view=ms.vss-test-web.build-test-results-tab&runId=8099702&resultId=100458)||
|[379734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379734)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379734&view=ms.vss-test-web.build-test-results-tab&runId=8088620&resultId=104261)||
|[379731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379731)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379731&view=ms.vss-test-web.build-test-results-tab&runId=8088490&resultId=104261)||
|[379744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379744)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379744&view=ms.vss-test-web.build-test-results-tab&runId=8089052&resultId=102816)||
|[379737](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379737)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379737&view=ms.vss-test-web.build-test-results-tab&runId=8088982&resultId=104611)||
|[379739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379739)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379739&view=ms.vss-test-web.build-test-results-tab&runId=8089012&resultId=102765)||
|[379733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379733)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379733&view=ms.vss-test-web.build-test-results-tab&runId=8089112&resultId=100060)||
|[379328](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379328)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ReservedFrameType_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379328&view=ms.vss-test-web.build-test-results-tab&runId=8077844&resultId=204382)||
|[378480](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378480)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378480&view=ms.vss-test-web.build-test-results-tab&runId=8060376&resultId=104261)||
|[378477](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378477)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378477&view=ms.vss-test-web.build-test-results-tab&runId=8060546&resultId=102683)||
|[378472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378472)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378472&view=ms.vss-test-web.build-test-results-tab&runId=8060242&resultId=104261)||
|[378479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378479)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378479&view=ms.vss-test-web.build-test-results-tab&runId=8060582&resultId=104611)||
|[378475](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378475)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378475&view=ms.vss-test-web.build-test-results-tab&runId=8060708&resultId=100008)||
|[378483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378483)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=378483&view=ms.vss-test-web.build-test-results-tab&runId=8060522&resultId=102439)||
|[377218](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377218)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377218&view=ms.vss-test-web.build-test-results-tab&runId=8027286&resultId=104261)||
|[377219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377219)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377219&view=ms.vss-test-web.build-test-results-tab&runId=8027294&resultId=104261)||
|[377233](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377233)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377233&view=ms.vss-test-web.build-test-results-tab&runId=8027196&resultId=104261)||
|[377224](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377224)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377224&view=ms.vss-test-web.build-test-results-tab&runId=8027964&resultId=103095)||
|[377227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377227)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377227&view=ms.vss-test-web.build-test-results-tab&runId=8027148&resultId=104261)||
|[377221](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377221)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377221&view=ms.vss-test-web.build-test-results-tab&runId=8027686&resultId=104611)||
|[377217](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377217)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377217&view=ms.vss-test-web.build-test-results-tab&runId=8027664&resultId=104611)||
|[377223](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377223)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377223&view=ms.vss-test-web.build-test-results-tab&runId=8028146&resultId=100622)||
|[377228](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377228)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377228&view=ms.vss-test-web.build-test-results-tab&runId=8028136&resultId=102205)||
|[375770](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375770)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375770&view=ms.vss-test-web.build-test-results-tab&runId=7993976&resultId=102678)||
|[375765](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375765)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375765&view=ms.vss-test-web.build-test-results-tab&runId=7993442&resultId=103676)||
|[375762](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375762)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375762&view=ms.vss-test-web.build-test-results-tab&runId=7993920&resultId=104611)||
|[375767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375767)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375767&view=ms.vss-test-web.build-test-results-tab&runId=7993904&resultId=104611)||
|[375752](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375752)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375752&view=ms.vss-test-web.build-test-results-tab&runId=7993782&resultId=104611)||
|[375753](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375753)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375753&view=ms.vss-test-web.build-test-results-tab&runId=7993434&resultId=104261)||
|[375766](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375766)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375766&view=ms.vss-test-web.build-test-results-tab&runId=7993846&resultId=104611)||
|[375756](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375756)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375756&view=ms.vss-test-web.build-test-results-tab&runId=7993458&resultId=104261)||
|[375751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375751)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375751&view=ms.vss-test-web.build-test-results-tab&runId=7993762&resultId=104611)||
|[375771](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375771)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375771&view=ms.vss-test-web.build-test-results-tab&runId=7993800&resultId=104611)||
|[375759](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375759)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375759&view=ms.vss-test-web.build-test-results-tab&runId=7994224&resultId=104454)||
|[375754](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375754)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375754&view=ms.vss-test-web.build-test-results-tab&runId=7993888&resultId=102685)||
|[375360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375360)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ReservedFrameType_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375360&view=ms.vss-test-web.build-test-results-tab&runId=7982724&resultId=200923)||
|[374906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374906)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374906&view=ms.vss-test-web.build-test-results-tab&runId=7970814&resultId=104611)|dotnet/runtime#90631|
|[374235](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374235)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374235&view=ms.vss-test-web.build-test-results-tab&runId=7954428&resultId=102705)||
|[374244](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374244)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374244&view=ms.vss-test-web.build-test-results-tab&runId=7954484&resultId=104611)||
|[374224](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374224)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374224&view=ms.vss-test-web.build-test-results-tab&runId=7954154&resultId=104235)||
|[374230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374230)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374230&view=ms.vss-test-web.build-test-results-tab&runId=7953836&resultId=104261)||
|[374229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374229)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374229&view=ms.vss-test-web.build-test-results-tab&runId=7954710&resultId=102523)||
|[373478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373478)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ReservedFrameType_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373478&view=ms.vss-test-web.build-test-results-tab&runId=7933024&resultId=199916)||
|[372621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372621)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372621&view=ms.vss-test-web.build-test-results-tab&runId=7914374&resultId=104260)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|6|45|100|

### PR DESCRIPTION
**Pull request by ManickaP**
Fixes #90603

### CODE REVIEW

File: src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs [hunk 1]
```diff
@@ -195,6 +190,17 @@ public async Task EstablishControlStreamAsync(SettingsEntry[] settingsEntries)
             await _outboundControlStream.SendSettingsFrameAsync(settingsEntries);
         }
 
+        public async Task DisposeCurrentStream()
+        {
+            Assert.NotNull(_currentStream);
+            Assert.True(_currentStreamId >= 0);
+
+            await _currentStream.DisposeAsync().ConfigureAwait(false);
+            _openStreams.Remove((int)_currentStreamId);
```
Comment (CarnaViire) [inline src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs:199]: This breaks the numeration alignment that seemed to be present before (`_openStreams[requestId - 1]`) -- is that ok? we are not using it anywhere anymore?

**Comment by ManickaP** [comment]
Outerloop failures unrelated, HTTP tests are clear.

File: src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs (hunk 1 above)
Comment (CarnaViire) [reply src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs:199]: Ah, that's a dictionary, not a list 🤦‍♀️ sorry 😄

**Review by CarnaViire — APPROVED** [review]
LGTM
