### PR TITLE
Fix invalid access of Target in SafeCredentialReference 

### LINKED ISSUE #34337: ClientAndServer_OneOrBothUseDefaultOk failing in CI
Only one failure so far but the stack seemed pretty definitive here so filing the issue. 

### Console Log

```
System.Net.Security.Tests.ApmSslStreamSystemDefaultTest.ClientAndServer_OneOrBothUseDefault_Ok(clientProtocols: Default, serverProtocols: Ssl2 | Default | Tls11 | Tls12) [FAIL]
      System.ObjectDisposedException : Safe handle has been closed.
      Object name: 'SafeHandle'.
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs(149,0): at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
        /_/src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs(354,0): at System.Net.Security.SafeCredentialReference..ctor(SafeFreeCredentials target)
        /_/src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs(341,0): at System.Net.Security.SafeCredentialReference.CreateReference(SafeFreeCredentials target)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs(201,0): at System.Net.Security.SslSessionsCache.CacheCredential(SafeFreeCredentials creds, Byte[] thumbPrint, SslProtocols sslProtocols, Boolean isServer, EncryptionPolicy encryptionPolicy)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(830,0): at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(726,0): at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
           at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
        /_/src/libraries/Common/src/System/Threading/Tasks/TaskToApm.cs(42,0): at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs(233,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs(513,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamSystemDefaultsTest.cs(60,0): at System.Net.Security.Tests.SslStreamSystemDefaultTest.ClientAndServer_OneOrBothUseDefault_Ok(Nullable`1 clientProtocols, Nullable`1 serverProtocols)
        --- End of stack trace from previous location ---
```

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#580861](https://dev.azure.com/dnceng/public/_build/results?buildId=580861)|Rolling|1|
### Configurations
- netcoreapp5.0-Windows_NT-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#580861](https://dev.azure.com/dnceng/public/_build/results?buildId=580861)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/ace43b91-c2d5-4eb1-b6a8-2aef17e5fe03/workitems/System.Net.Security.Tests/files/console.00e58fde.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/ace43b91-c2d5-4eb1-b6a8-2aef17e5fe03/workitems/System.Net.Security.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-ace43b91c2d54eb1b6/System.Net.Security.Tests/fdc724e9-46bd-4730-bd3d-21ea28cb988a.log?sv=2019-02-02&se=2020-04-10T04%3A49%3A46Z&sr=c&sp=rl&sig=G%2BS7ewMYttY6QP5LgRgWYL5UjXU7rRbOMai6qQMemnY%3D)|

### PR DESCRIPTION
**Pull request by aik-jahoda**
The SafeCredentialReference derive from CriticalHandleMinusOneIsInvalid however it didn't owerride IsInvalid nor IsClosed and the behaviour of those method are not reflecting the real Target state.

I removed this inheritance so the problemathics methods are no longer valid and it pointed into problematic usage of SafeCredentialReference which is fixed now.

Fixes #34337

### CODE REVIEW

**Comment by wfurt** [comment]
you may need to rebase or merge from upstream @aik-jahoda

**Comment by aik-jahoda** [comment]
@wfurt, thanks for the notice. All tests are passing now.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs [hunk 1]
```diff
@@ -323,45 +324,54 @@ public new IntPtr DangerousGetHandle()
...
+        }
+
+        ~SafeCredentialReference()
+        {
+            Dispose(false);
+
+#if DEBUG
+            Debug.Fail("Finalizer should never be called. The SafeCredentialReference should be always disposed manually.");
+            throw NotImplemented.ByDesign;
+#endif
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs:374]: Why is this valid?  There's no way user code could drop one of these on the floor and result in this being invoked?

Even if the answer is "no", this assert could fire / exception thrown if the SafeFreeCredentials instance passed to the constructor is concurrently closed after target.IsClosed check in CreateReference and before the DangerousAddRef call in the ctor.  If that happens, the DangerousAddRef will throw an exception, but by that point, the SafeCredentialReference instance will have already been allocated and its finalizer will eventually run.

Seems like this whole if DEBUG / endif section should be deleted.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs [hunk 2]
```diff
@@ -323,45 +324,54 @@ public new IntPtr DangerousGetHandle()
...
-            SafeCredentialReference result = new SafeCredentialReference(target);
-            if (result.IsInvalid)
+            if (target.IsInvalid || target.IsClosed)
             {
                 return null;
             }
 
+            SafeCredentialReference result = new SafeCredentialReference(target);
+
             return result;
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs:343]:
```suggestion
            return new SafeCredentialReference(target);
```

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs [hunk 3]
```diff
@@ -323,45 +324,54 @@ public new IntPtr DangerousGetHandle()
...
         }
-        private SafeCredentialReference(SafeFreeCredentials target) : base()
+        private SafeCredentialReference(SafeFreeCredentials target)
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs:345]:
```suggestion

        private SafeCredentialReference(SafeFreeCredentials target)
```

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs [hunk 4]
```diff
@@ -323,45 +324,54 @@ public new IntPtr DangerousGetHandle()
...
         }
 
-        protected override bool ReleaseHandle()
+        public void Dispose()
+        {
+            Dispose(true);
+            GC.SuppressFinalize(this);
+        }
+
+        public void Dispose(bool disposing)
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs:360]:
```suggestion
        private void Dispose(bool disposing)
```

File: src/libraries/Common/src/System/Net/Security/Unix/SafeFreeCredentials.cs [hunk 5]
```diff
@@ -57,19 +51,29 @@ private SafeCredentialReference(SafeFreeCredentials target) : base()
...
+        ~SafeCredentialReference()
+        {
+            Dispose(false);
+
+#if DEBUG
+            Debug.Fail("Finalizer should never be called. The SafeCredentialReference should be always disposed manually.");
+#endif
+        }
+
     }
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Net/Security/Unix/SafeFreeCredentials.cs:78]: Why is this code duplicated in two files?  Are there differences here between the Windows and Unix implementations?  They look the same.

File: src/libraries/Common/src/System/Net/Security/Unix/SafeFreeCredentials.cs [hunk 6]
```diff
@@ -27,27 +27,21 @@ protected SafeFreeCredentials(IntPtr handle, bool ownsHandle) : base(handle, own
...
-    internal sealed class SafeCredentialReference : CriticalHandleMinusOneIsInvalid
+    internal sealed class SafeCredentialReference : CriticalFinalizerObject, IDisposable
     {
-#endif
-
         //
         // Static cache will return the target handle if found the reference in the table.
         //
-        internal SafeFreeCredentials Target;
+        internal SafeFreeCredentials Target { get; private set; }
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Net/Security/Unix/SafeFreeCredentials.cs:35]: Why did you make this a property here but not in the other copy?

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs [hunk 7]
```diff
@@ -125,15 +125,15 @@ public bool Equals(SslCredKey other)
...
-                if (NetEventSource.IsEnabled) NetEventSource.Info(null, $"Not found or invalid, Current Cache Coun = {s_cachedCreds.Count}");
+                if (NetEventSource.IsEnabled) NetEventSource.Info(null, $"Not found or invalid, Current Cache Count = {s_cachedCreds.Count}");
                 return null;
             }
 
-            if (NetEventSource.IsEnabled) NetEventSource.Info(null, $"Found a cached Handle = {cached.Target}");
+            if (NetEventSource.IsEnabled) NetEventSource.Info(null, $"Found a cached Handle = {cached?.Target}");
 
-            return cached.Target;
+            return cached?.Target;
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:136]: How could cached be null here?

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs [hunk 8]
```diff
@@ -213,13 +213,13 @@ internal static void CacheCredential(SafeFreeCredentials creds, byte[]? thumbPri
...
                     {
-                        if (NetEventSource.IsEnabled) NetEventSource.Info(null, $"CacheCredential() (locked retry) Found already cached Handle = {cached.Target}");
+                        if (NetEventSource.IsEnabled) NetEventSource.Info(null, $"CacheCredential() (locked retry) Found already cached Handle = {cached?.Target}");
                     }
                 }
             }
             else if (NetEventSource.IsEnabled)
             {
-                if (NetEventSource.IsEnabled) NetEventSource.Info(null, $"CacheCredential() Ignoring incoming handle = {creds} since found already cached Handle = {cached.Target}");
+                if (NetEventSource.IsEnabled) NetEventSource.Info(null, $"CacheCredential() Ignoring incoming handle = {creds} since found already cached Handle = {cached?.Target}");
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:222]: Same question

File: src/libraries/Common/src/System/Net/Security/Unix/SafeFreeCredentials.cs (hunk 5 above)
Comment (aik-jahoda) [reply src/libraries/Common/src/System/Net/Security/Unix/SafeFreeCredentials.cs:78]: I'll extract this class into one file

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs (hunk 1 above)
Comment (aik-jahoda) [reply src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs]: I have removed ifdefs

File: src/libraries/Common/src/System/Net/Security/Unix/SafeFreeCredentials.cs (hunk 6 above)
Comment (aik-jahoda) [reply src/libraries/Common/src/System/Net/Security/Unix/SafeFreeCredentials.cs]: I merged the SafeFreeCredentials class so it is consistent now

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs (hunk 7 above)
Comment (aik-jahoda) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:136]: you are right

File: src/libraries/Common/src/System/Net/Security/SSPIHandleCache.cs [hunk 9]
```diff
@@ -34,7 +34,7 @@ internal static void CacheCredential(SafeFreeCredentials newHandle)
                     newRef = Interlocked.Exchange<SafeCredentialReference>(ref s_cacheSlots[index], newRef);
                 }
 
-                newRef?.Dispose();
+                newRef.Dispose();
```
[the remark this answers is not in the document]
Comment (stephentoub) [reply src/libraries/Common/src/System/Net/Security/SSPIHandleCache.cs:37]: (The `private static readonly SafeCredentialReference[] s_cacheSlots` up above should instead be `private static readonly SafeCredentialReference?[] s_cacheSlots`; at which point I expect you'll get a warning here.)

File: src/libraries/Common/src/System/Net/Security/SafeCredentialReference.cs [hunk 10]
```diff
@@ -0,0 +1,55 @@
+#nullable enable
+
+using System.Runtime.ConstrainedExecution;
+
+namespace System.Net.Security
+{
+
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Net/Security/SafeCredentialReference.cs:7]:
```suggestion
```

File: src/libraries/Common/src/System/Net/Security/SafeCredentialReference.cs [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+        internal static SafeCredentialReference? CreateReference(SafeFreeCredentials target)
+        {
+            if (target.IsInvalid || target.IsClosed)
+            {
+                return null;
+            }
+
+            return new SafeCredentialReference(target);
+        }
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Net/Security/SafeCredentialReference.cs:26]:
```suggestion
        }

```

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs [hunk 12]
```diff
@@ -125,9 +125,9 @@ public bool Equals(SslCredKey other)
             var key = new SslCredKey(thumbPrint, (int)sslProtocols, isServer, encryptionPolicy);
 
             SafeCredentialReference? cached;
-            if (!s_cachedCreds.TryGetValue(key, out cached) || cached.IsClosed || cached.Target.IsInvalid)
+            if (!s_cachedCreds.TryGetValue(key, out cached) || cached.Target.IsClosed || cached.Target.IsInvalid)
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:128]: When a SafeCredentialReference is disposed, it's null'ing out its target:
https://github.com/dotnet/runtime/pull/36875/files#diff-d9a8c0653d499676a48062a0a80b2018R46
Doesn't that mean this `cached.Target.IsClosed` could null ref?

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs [hunk 13]
```diff
@@ -158,11 +158,11 @@ internal static void CacheCredential(SafeFreeCredentials creds, byte[]? thumbPri
 
             SafeCredentialReference? cached;
 
-            if (!s_cachedCreds.TryGetValue(key, out cached) || cached.IsClosed || cached.Target.IsInvalid)
+            if (!s_cachedCreds.TryGetValue(key, out cached) || cached.Target.IsClosed || cached.Target.IsInvalid)
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:161]: Same question

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs (hunk 12 above)
Comment (aik-jahoda) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:128]: I was about to fix this as part of #2353

Comment (stephentoub) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:128]: But aren't you introducing the problem here?

Comment (aik-jahoda) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs]: I think the issue was there before too as `cached.IsClosed` was always false fo the code reached `cached.Target.IsInvalid` condition check which would fail in the same way.

I added the changes from  #2353 so the null reference issue should be fixed.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs [hunk 14]
```diff
@@ -191,20 +198,13 @@ internal static void CacheCredential(SafeFreeCredentials creds, byte[]? thumbPri
 
                             for (int i = 0; i < toRemoveAttempt.Length; ++i)
                             {
-                                cached = toRemoveAttempt[i].Value;
+                                var freeCreds = toRemoveAttempt[i].Value.Target;
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:201]: var => whatever type this is

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs [hunk 15]
```diff
@@ -156,15 +162,16 @@ internal static void CacheCredential(SafeFreeCredentials creds, byte[]? thumbPri
...
+            if (credentials == null || credentials.IsClosed || credentials.IsInvalid)
             {
                 lock (s_cachedCreds)
                 {
-                    if (!s_cachedCreds.TryGetValue(key, out cached) || cached.IsClosed)
+                    credentials = GetCachedCredential(key);
+                    if (credentials == null || credentials.IsClosed)
                     {
-                        cached = SafeCredentialReference.CreateReference(creds);
+                        var cached = SafeCredentialReference.CreateReference(creds);
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:174]: var => whatever type this is

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs [hunk 16]
```diff
@@ -191,20 +198,13 @@ internal static void CacheCredential(SafeFreeCredentials creds, byte[]? thumbPri
...
                                 {
-                                    creds = cached.Target;
-                                    cached.Dispose();
-
-                                    if (!creds.IsClosed && !creds.IsInvalid && (cached = SafeCredentialReference.CreateReference(creds)) != null)
-                                    {
-                                        s_cachedCreds[toRemoveAttempt[i].Key] = cached;
-                                    }
-                                    else
+                                    if (s_cachedCreds.TryRemove(toRemoveAttempt[i].Key, out var removedCached))
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:205]: var => whatever type this is

File: src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs [hunk 17]
```diff
@@ -191,20 +198,13 @@ internal static void CacheCredential(SafeFreeCredentials creds, byte[]? thumbPri
...
-                                cached = toRemoveAttempt[i].Value;
+                                var freeCreds = toRemoveAttempt[i].Value.Target;
 
-                                if (cached != null)
+                                if (freeCreds == null || freeCreds.IsClosed || freeCreds.IsInvalid)
                                 {
-                                    creds = cached.Target;
-                                    cached.Dispose();
-
-                                    if (!creds.IsClosed && !creds.IsInvalid && (cached = SafeCredentialReference.CreateReference(creds)) != null)
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:201]: Do you know what the purpose of this `cached = SafeCredentialReference.CreateReference(creds)` was?  This is removing it and the adding of it back into the table.

Comment (aik-jahoda) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:201]: The logic was:
1) dispose cahced - cached.Target becomes null, the SafeCredentialReference ref count decrease
2) if creds are still valid, create SafeCredentialReference from it (cached should not be null as CreateReference returns null when creds.IsInvalid )
3) if the SafeCredentialReference is successfully created (the ref count increase), it replace the disposed one in the cache.
- if the creds is valid, the step 1-3 is noop
- if creds is invalid, it is removed from the s_cachedCreds

changed to:
1) if creds are invalid, and are removed from cache, then dispose SafeCredentialReference wrapper which decrease ref count

Comment (stephentoub) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:201]: There is a subtle difference between the old logic and the new logic, and I expect it's why it was written the way it was written.

When you Dispose of a SafeHandle and there's an outstanding ref count on it, the disposal is delayed until that outstanding ref count is released.  So imagine there was a handle in the collection that had Dispose called on it.  That Dispose won't have taken effect yet, because there's an outstanding ref count from this SafeCredentialReference.  The previous logic was disposing of the SafeCredentialReference, which would have allowed an outstanding Dispose to take effect, after which IsClosed might be true.  But in the new logic, the SafeCredentialReference isn't being disposed unless the handle is already disposed, and as such, it's going to miss removing handles that were disposed, because the disposal couldn't have taken effect yet.

This means that the new code is no longer removing disposed handles, because in the common case disposal won't have actually taken effect because of the SafeCredentialReference.  Given that, I expect the new logic is broken.

Comment (aik-jahoda) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslSessionsCache.cs:201]: I reverted the old cleanup logic. Thanks for catching this bug

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
@aik-jahoda, are you still working on this?

**Comment by aik-jahoda** [comment]
@stephentoub not actively now. However this is on our test failure list and I expect it will be prioritised soon.

**Comment by aik-jahoda** [comment]
I continue on this PR to resolve the handles issue.

**Comment by aik-jahoda** [comment]
I run the test in loop for several days with any failure. It is ready to merge and we will observe possible failures in our weekly CI report.

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by ViktorHofer** [comment]
@aik-jahoda is the result.txt file that was checked into this PR necessary?

**Comment by wfurt** [comment]
no, it is not. we miss it in the review IMHO as GitHub would not show binary (utf-16) diff @ViktorHofer

**Comment by ViktorHofer** [comment]
@aik-jahoda can you please send a PR to remove the file from main?
