### PR TITLE
JIT: Handle edge cases around BlendVariableMask rewrite

### LINKED ISSUE #127260: JIT: Invalid codegen for Avx512F.VL.BlendVariable and Avx512BW.VL.BlendVariable for integral types larger than byte
### Description

When using `BlendVariable` with vectors smaller than 512 bit, codegen may incorrectly emit `pblendvb`, causing the mask to be misinterpreted.

### Reproduction Steps

```c#
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

Console.WriteLine(BlendVariable128(Vector128.Create<long>(-1), Vector128<long>.Zero, Vector128.Create(long.MinValue)));
Console.WriteLine(BlendVariable512(Vector512.Create<long>(-1), Vector512<long>.Zero, Vector512.Create(long.MinValue)));

[MethodImpl(MethodImplOptions.NoInlining)]
static Vector128<long> BlendVariable128(Vector128<long> left, Vector128<long> right, Vector128<long> mask)
    => Avx512F.VL.BlendVariable(left, right, mask);

[MethodImpl(MethodImplOptions.NoInlining)]
static Vector512<long> BlendVariable512(Vector512<long> left, Vector512<long> right, Vector512<long> mask)
    => Avx512F.BlendVariable(left, right, mask);
```

### Expected behavior

Both methods should output zero vectors:

```
<0, 0>
<0, 0, 0, 0, 0, 0, 0, 0>
```

### Actual behavior

Actual output:

```
<72057594037927935, 72057594037927935>
<0, 0, 0, 0, 0, 0, 0, 0>
```

### Regression?

No, these were new APIs in net10.0 and have had the same behavior since release.

### Other information

This is due to `RewriteHWIntrinsicBlendv` rewriting `BlendVariableMask` to `BlendVariable`, which emits `pblendvb` rather than the desired `vpblendmq`.

```asm
; Method Program:<<Main>$>g__BlendVariable128|0_0(System.Runtime.Intrinsics.Vector128`1[long],System.Runtime.Intrinsics.Vector128`1[long],System.Runtime.Intrinsics.Vector128`1[long]):System.Runtime.Intrinsics.Vector128`1[long] (FullOpts)
G_M56632_IG01:  ;; offset=0x0000
						;; size=0 bbWeight=1 PerfScore 0.00

G_M56632_IG02:  ;; offset=0x0000
       vmovups  xmm0, xmmword ptr [rdx]
       vmovups  xmm1, xmmword ptr [r9]
       vpblendvb xmm0, xmm0, xmmword ptr [r8], xmm1
       vmovups  xmmword ptr [rcx], xmm0
       mov      rax, rcx
						;; size=22 bbWeight=1 PerfScore 14.25

G_M56632_IG03:  ;; offset=0x0016
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00
; Total bytes of code: 23
```

vs the correct:

```asm
; Method Program:<<Main>$>g__BlendVariable128|0_0(System.Runtime.Intrinsics.Vector128`1[long],System.Runtime.Intrinsics.Vector128`1[long],System.Runtime.Intrinsics.Vector128`1[long]):System.Runtime.Intrinsics.Vector128`1[long] (FullOpts)
G_M56632_IG01:  ;; offset=0x0000
						;; size=0 bbWeight=1 PerfScore 0.00

G_M56632_IG02:  ;; offset=0x0000
       vmovups  xmm0, xmmword ptr [rdx]
       vmovups  xmm1, xmmword ptr [r9]
       vpmovq2m k1, xmm1
       vpblendmq xmm0 {k1}, xmm0, xmmword ptr [r8]
       vmovups  xmmword ptr [rcx], xmm0
       mov      rax, rcx
						;; size=28 bbWeight=1 PerfScore 15.25

G_M56632_IG03:  ;; offset=0x001C
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00
; Total bytes of code: 29
```

### PR DESCRIPTION
**Pull request by saucecontrol**
Fixes #127260

This deals with some edge cases related to `BlendVariable` being 'upgraded' to `BlendVariableMask` on import and then possibly 'downgraded' to its original form in `rationalize`.

First, we were improperly rewriting some blends back to `BlendVariable` when the mask granularity was incompatible with the `pblendvb` instruction.

Second, there is logic in place that checks whether the blend could be used as an EVEX embedded mask and rewrites back to `BlendVariable` if not. However, it misses cases where the mask is created from a vector anyway, and creating the mask just to embed it is a deoptimization.

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
@tannergooding, @kg PTAL.

File: src/coreclr/jit/rationalize.cpp [hunk 1]
```diff
@@ -655,20 +656,25 @@ void Rationalizer::RewriteHWIntrinsicBlendv(GenTree** use, Compiler::GenTreeStac
 
         if (op2->isEmbeddedMaskingCompatible(m_compiler, tgtMaskSize, tgtSimdBaseType))
         {
-            // We are going to utilize the embedded mask, so we don't need to rewrite. However,
-            // we want to fixup the simdBaseType here since it simplifies lowering and allows
-            // both embedded broadcast and the mask to be live simultaneously.
+            // Make sure we had a mask to begin with. We don't want to create a mask
+            // solely for the purpose of embedding it.
```
Comment (tannergooding) [inline src/coreclr/jit/rationalize.cpp:660]: This needs an elaboration covering why as it's operating under the presumption that `vpmov*2m` is more expensive than `vblendvps`, which can depend on the hardware and may change in the future

For example, this is what we have today where it may be slower or may be similar perf (using `XMM/YMM/ZMM` and `vpmov*2m` vs `vblendvps`):
* AMD Zen4: `3/4/5` vs `1`
* AMD Zen5: `3/4/6` vs `2`
* Intel Skylake-X: `3` vs `1-2`
* Intel Emerald Rapids: `3` vs `2-3` 

Then there is also the case where we don't have a `vpblendvw` and `vpblendvb` has slightly different behavior here, so it might not be valid to switch back. Consider that `0x8000` selects a whole word but needs to be `0x8080` if using `vpblendvb`.

Comment (saucecontrol) [reply src/coreclr/jit/rationalize.cpp]: > Then there is also the case where we don't have a `vpblendvw` and `vpblendvb` has slightly different behavior here, so it might not be valid to switch back. Consider that `0x8000` selects a whole word but needs to be `0x8080` if using `vpblendvb`.

This comment led me to realize that the current implementation is incorrect in these cases.  https://github.com/dotnet/runtime/issues/127260

This change only removes the assumption that a mask that is containable is always worth keeping.  The decision whether to actually rewrite it is made below, and that code does not account for element size compatibility.

I'll take a look at rolling that fix together with this.

Comment (tannergooding) [reply src/coreclr/jit/rationalize.cpp]: It should probably be using the existing `IsVectorPerElementMask` to determine compatibility, that way its using the centralized helper

Comment (saucecontrol) [reply src/coreclr/jit/rationalize.cpp]: For `BlendVariable` specifically, that would be too restrictive, because the caller originally specified the granularity of the mask through the overload, regardless of the vector's origin or contents.

We should only have to check that the `simdBaseType` is compatible with the non-mask blend instructions, i.e. it's a floating type (`blendvp[sd]`) or byte-size (`pblendvb`). Anything else must have originated as a call to the `Avx512F.VL` or `Avx512BW.VL` methods and can't be 'downgraded'.

I'll push a fix and some regression tests shortly.

**Comment by saucecontrol** [comment]
Few [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392414&view=ms.vss-build-web.run-extensions-tab) now with the bug fix included.

File: src/coreclr/jit/rationalize.cpp (hunk 1 above)
Comment (tannergooding) [reply src/coreclr/jit/rationalize.cpp]: Yes-ish.

`BlendVariable` is taken from the user and expected to be `MostSignificantBit` set for "select" and anything else otherwise.

The JIT is then expected to emit a correct conversion for the `SimdBaseType` to ensure a correct kmask is created for the underlying `vpblendm` instruction. That is a `vpmov*2m` of the appropriate size

Any IR we produce ourselves then needs to ensure it is correct with that assumption.

File: src/coreclr/jit/rationalize.cpp [hunk 2]
```diff
@@ -648,7 +649,16 @@ void Rationalizer::RewriteHWIntrinsicBlendv(GenTree** use, Compiler::GenTreeStac
...
 
-    if (scratchSideEffects.IsLirInvariantInRange(m_compiler, op2, node))
+    // If the mask was originally a vector, we don't want to create a mask solely for
+    // the purpose of embedding it. vpmov*2m is relatively costly compared to blendvp*.
+    bool isVectorToMask          = op3->OperIsConvertVectorToMask();
+    bool isVectorBlendCompatible = true;
+
+    if (isVectorToMask)
+    {
+        isVectorBlendCompatible = varTypeIsFloating(simdBaseType) || varTypeIsByte(simdBaseType);
```
Comment (tannergooding) [inline src/coreclr/jit/rationalize.cpp]: This is overly restrictive.

We can actually trivially support anything that isn't `varTypeIsShort` here since `varTypeIsLong` can use `double` and `varTypeIsInt` can use `float`.

We can also change the type of the operation to `varTypeIsByte` if the mask is either a per element mask compatible with the original `simdBaseType` or simply even just has the `MostSignificantBit` set for each element of the original `simdBaseType`, which allows us to support `varTypeIsShort` and to keep integer operations as integer operations if that's desired (doesn't matter on most modern hardware, but can for latency and other considerations on some).

Comment (tannergooding) [reply src/coreclr/jit/rationalize.cpp]: As a second nit, we can also just return early here instead of pushing it down to the other return block below.

Comment (saucecontrol) [reply src/coreclr/jit/rationalize.cpp]: > We can actually trivially support anything that isn't varTypeIsShort here since varTypeIsLong can use double and varTypeIsInt can use float.

Done.

> if the mask is either a per element mask compatible with the original simdBaseType or simply even just has the MostSignificantBit set for each element of the original simdBaseType

I'm not sure it's possible for us to end up with something of this shape since `ConvertVectorToMask(CNS_VEC)` gets folded to `CNS_MSK` and since any per-element-mask-vector-producing intrinsic should have also been upgraded to its mask-producing form and would therefore not be wrapped in `ConvertVectorToMask`.  I included the `IsVectorPerElementMask` check just in case, but it didn't show any hits in SPMI.

File: src/tests/JIT/Regression/JitBlue/Runtime_127260/Runtime_127260.cs [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+
+        Assert.Equal(Vector128<int>.Zero,
+            BlendVariableAvx512Int32(Vector128.Create<int>(-1), Vector128<int>.Zero, Vector128.Create(int.MinValue)));
+
+        Assert.Equal(Vector128<long>.Zero,
+            BlendVariableAvx512Int64(Vector128.Create<long>(-1), Vector128<long>.Zero, Vector128.Create(long.MinValue)));
+    }
+
+    [ConditionalFact(typeof(Avx512BW.VL), nameof(Avx512BW.VL.IsSupported))]
+    public static void TestContainableMask()
```
[the remark this answers is not in the document]
Comment (saucecontrol) [reply src/tests/JIT/Regression/JitBlue/Runtime_127260/Runtime_127260.cs:56]: > on machines that support AVX-512F+VL but not AVX-512BW

This is not a supported configuration in .NET, and no hardware actually exists in that configuration.

**Review by tannergooding — APPROVED** [review]

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib, @EgorBo, @kg  this should be ready for secondary review. Fixes an issue with the `BlendVariableMask -> BlendVariable` rewriting and ensures its used in cases where it would be more optimal.

**Review by EgorBo — APPROVED** [review]
