### PR TITLE
Environment variable should override property for gcServer.

### LINKED ISSUE #61674: Garbage collection method is not manageable by environment variables in .net 6
### Describe the bug
[Documentation](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector#workstation-vs-server) mentions that user is able to change the default Server garbage collection to Workstation garbage collection via either `COMPlus_gcServer` (pre .net6) or `DOTNET_gcServer` (in .net6) Environment variable.
It was working (the COMPlus env) in .net5, but after project upgrade to .net6, both methods seems to be doing nothing, gcServer is always set to true.
MSBuild property is still functioning, we can add `/p:ServerGarbageCollection=false` to the build parameters and we will achieve exactly that.
The problem seems to be asp.net related, Console application (with default gc set to Workstation) can be overridden by both of those env variables to Server.

### To Reproduce
* Create webapi template `dotnet new webapi` in .net6
* Run that project with any of given env variables (COMPlus_gcServer=0 or DOTNET_gcServer=0)
* Check used garbage collection method (ie. print `System.Runtime.GCSettings.IsServerGC` on startup)

### Further technical details
- ASP.NET Core version: 6.0
- The IDE: VS Code 1.62.2-1636665017_amd64
- 
<details>
  <summary>dotnet --info Output</summary>

```
NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
```

</details>

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #61674 

Add tests for the scenario.

The added tests can also be used to validate any of the configuration properties and environment variables used for start-up.

/cc @cshung @elinor-fung 

@jkoritzinsky and @trylek Can you please confirm the methodology in this new test works with the system being built?

### CODE REVIEW

**Review by cshung — APPROVED** [review]
LGTM, thanks for adding the test!

**Review by mangod9 — APPROVED** [review]

**Comment by mangod9** [comment]
Thanks @AaronRobinsonMSFT for fixing, this feels like something we should queue up for 6.0.x. Thx!

File: src/tests/baseservices/RuntimeConfiguration/TestConfig.cs [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+    static int Verify_ServerGC_Env_Enable(string[] _)
+    {
+        return GCSettings.IsServerGC
+            ? Success
+            : Fail;
+    }
+
+    [Fact]
+    [ConfigProperty("DOTNET_gcServer", "0")]
+    static int Verify_ServerGC_Env_Disable(string[] _)
```
Comment (am11) [inline src/tests/baseservices/RuntimeConfiguration/TestConfig.cs:30]: @AaronRobinsonMSFT, FYI, this test failed on Windows arm64 checked https://helix.dot.net/api/2019-06-17/jobs/1a1caea9-5980-4759-a7d1-da30e1a225a6/workitems/baseservices.RuntimeConfiguration/console

Comment (AaronRobinsonMSFT) [reply src/tests/baseservices/RuntimeConfiguration/TestConfig.cs:30]: @cshung this seems like something the GC team should investigate. I am unclear why this would be occurring but given the simplicity of the test I'd wager it is unlikely a test issue.

Comment (cshung) [reply src/tests/baseservices/RuntimeConfiguration/TestConfig.cs:30]: @mangod9 It looks like the GCStandAloneServer set `COMPlus_gcServer=1`, so even when the code set `DOTNET_gcServer=0`, we are still unable to disable it.

Comment (mangod9) [reply src/tests/baseservices/RuntimeConfiguration/TestConfig.cs:30]: ok makes sense. @am11 what CI job was failing due to this issue? Is the failure only after this change or unrelated to this?

Comment (am11) [reply src/tests/baseservices/RuntimeConfiguration/TestConfig.cs:30]: @mangod9, it's a new test added by this PR, which started to fail in outerloop test when this PR was merged. Perhaps the root-cause was preexisting and the test has surfaced the problem.

> It looks like the GCStandAloneServer set `COMPlus_gcServer=1`, so even when the code set `DOTNET_gcServer=0`, we are still unable to disable it.

Based on the config parsing implementation:
https://github.com/dotnet/runtime/blob/4da6b9a8d55913c0ea560d63590d35dc942425be/src/coreclr/inc/clrconfignocache.h#L75-L86
first `DOTNET_gcServer` will be checked and if the value is `NULL`, it will fallback to legacy, `COMPlus_gcServer`. It is `LPCSTR`, so `=0` shouldn't be confused by NULL/0, right?
