### PR TITLE
Expose a global switch to disable IPV6

### LINKED ISSUE #47583: Expose a global switch to disable IPV6 to overcome DualMode socket issues in environments that do not support IPV6
BCL as well as [external libraries](https://github.com/dotnet/runtime/pull/45614#issuecomment-739310008) tend to shift towards dual-stack sockets in their networking code. This conforms to best practices defined in [RFC1933](https://tools.ietf.org/html/rfc1933), but can lead to issues when connections are established through VPN tunnels which do not support IPv6 and/or dual-stack properly.

A custom ConnectCallback can help in HttpClient use cases where users have direct control over their HttpClient instances (#47267), but in cases where the Socket connections are carried out by an external component, users may get blocked (#45462).

This cases are rare, but the fix is simple, and easy to communicate (see #45893), therefore we should consider implementing it in .NET 6.

### LINKED ISSUE #52287: HttpClient difference 3.1 vs 5.0. Getting: connection was aborted
Hi there,

I have found strange behavior when moved from 3.1 to 5.0.
The same request in the same environment produces a different result.

Runtime: 3.1 - OK 
Runtime 5.0.4 - Exception:
An error occurred while sending the request. -> Unable to read data from the transport connection -> An established connection was aborted by the software in your host machine.

Code: 
program.cs
``` csharp
namespace WebApplication
{
    public class Program
    {
        public static void Main(string[] args) =>
            Host.CreateDefaultBuilder(args).ConfigureWebHostDefaults(wb => { wb.UseStartup<Startup>(); }).Build().Run();
    }

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services){}

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    try
                    {
                        var client = new HttpClient();
                        var resp = await client.GetAsync("https://demo.identityserver.io/.well-known/openid-configuration");
                        await context.Response.WriteAsync(Environment.Version.ToString() + ": " + resp.StatusCode);
                    }
                    catch (Exception ex)
                    {
                        await context.Response.WriteAsync(Environment.Version.ToString() + ": " + ex.Message);
                    }
                });
            });
        }
    }
}
```

WebApplication.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
	<!--<TargetFramework>netcoreapp3.1</TargetFramework>-->
  </PropertyGroup>
</Project>
```

What could be a reason of this behavior  on the same machine(just flip TargetFramework)? 
Also I have tried on another machine and both runtime works fine and no exception.

OS: Win 10

Thx!

### PR DESCRIPTION
**Pull request by antonfirsov**
Fixes #47583. Resolves #52287, #54807 and similar issues, without changing customer application code.

Introduces an AppContext switch `System.Net.DisableIPv6` and environment variable `DOTNET_SYSTEM_NET_DISABLEIPV6` to emulate the lack of OS-level IPv6 support. This is useful to workaround dual-stack socket issues when the OS reports support of IPv6, but some other underlying infrastructure element (typically VPN) doesn't function well with IPv6 request.

For consistency, this switch also impacts NameResolution and Ping, not only Sockets.

### CODE REVIEW

File: src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+            if (bool.TryParse(envVar, out value))
+            {
+                return value;
+            }
+            else if (uint.TryParse(envVar, out uint intVal))
+            {
+                return intVal != 0;
+            }
+
+            return false;
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs:39]:
```suggestion
            if (envVar is not null)
            {
                return envVar == "1" || envVar.Equals("true", StringComparison.OrdinalIgnoreCase);
            }
            
            return false;
```

File: src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+        private static bool IsIPv6Disabled()
+        {
+            bool value;
+
+            // First check for the AppContext switch, giving it priority over the environment variable.
+            if (AppContext.TryGetSwitch(DisableIPv6AppCtxSwitch, out value))
+            {
+                return value;
+            }
```
Comment (stephentoub) [inline src/libraries/Common/src/System/Net/SocketProtocolSupportPal.cs:25]:
```suggestion
            // First check for the AppContext switch, giving it priority over the environment variable.
            if (AppContext.TryGetSwitch(DisableIPv6AppCtxSwitch, out bool disabled))
            {
                return disabled;
            }
```

**Review by geoffkizer — APPROVED** [review]

**Comment by antonfirsov** [comment]
The IPv6 filtering doesn't work in NameResolutionPal.Unix, converting to draft.

**Review by stephentoub — APPROVED** [review]
