### PR TITLE
Change LoadDomainInfo to honor requested LDAP port

### LINKED ISSUE #65894: Ldap GetMembers working over 389 port
### Description

Hi!

When GroupPrincipal.GetMembers used and 389 port blocked on machine (and 636 specified on connection string)
Method not working

problem is here:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs
protected virtual void LoadDomainInfo()

image

### Reproduction Steps

var  options = Negotiate | SecureSocketLayer;
using var context = new PrincipalContext( ContextType.Domain, "domain:636", "DC=domain", options);
using (var indentity = GroupPrincipal.FindByIdentity(context, "Group"))
{
    var tmp = indentity.GetMembers(true).First(); // we will wall
}

### Expected behavior

When domain specified, used same port (LDAPS) communication

### Actual behavior

Method failed when 389 blocked

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

- Net462, NetCore31, NetCore5 and other
- Windows
- Debug, Release

### Other information

_No response_

### PR DESCRIPTION
**Pull request by JasonDebug**
Fixes https://github.com/dotnet/runtime/issues/65894

LoadDomainInfo builds an LDAP Uri that ignores the requested port.  If LDAPS/636 is requested, traffic still goes to 389 for this request.  For environments where port 389 is blocked, this causes calls such as GroupPrincipal.GetMembers() to fail when the group is Domain Local or Universal.  We do not seem to call LoadDomainInfo for Global groups.

This PR will use the specified port for the call, 389 if no port is specified, or 636 if LDAPS is specified.

### CODE REVIEW

**Review by kumarravik78c — APPROVED** [review]
I have validated this PR on my local set up and made sure this fixes the issue, hence approving.

**Review by steveharter — APPROVED** [review]
Approving based on approval from @kumarravik78c

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs [hunk 1]
```diff
@@ -2417,9 +2417,13 @@ protected virtual void LoadDomainInfo()
             // From that, we can build the DNS Domain Name
             this.dnsHostName = ADUtils.GetServerName(this.ctxBase);
 
+            // Pull the requested port number
+            Uri ldapUri = new Uri(this.ctxBase.Path);
+            int port = ldapUri.Port != -1 ? ldapUri.Port : (ldapUri.Scheme.ToUpperInvariant() == "LDAPS" ? 636 : 389);
```
Comment (rhuijben) [inline src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs:2422]: String.Equals(..., StringComparison.OrdinalIgnoreCase) avoids an unnecessary allocation.
