### PR TITLE
Fix exception handling in the prestub worker

### LINKED ISSUE #112502: Dotnet build hangs at CoreCompile when specific NuGet package referenced
---
**Issue moved from dotnet/sdk#45036**
- Please respond to @fabianoliver.

---

_From @fabianoliver on Friday, November 22, 2024 10:10:28 AM_

### Describe the bug

When using SDK 9.0.100, building any project that references "ReactiveUI.SourceGenerations" version 1.1.31 hangs forever at the "CoreCompile" stage. Building the same project using SDK 8.0.100 works well.

Please feel free to close this issue if you reckon the package itself is at fault of course. I'm raising this here though as I would think that building this with a different SDK version "should" not be able to break the referenced package / source generator in any way?

### To Reproduce

Build an empty project with the following csproj

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ReactiveUI.SourceGenerators" Version="1.1.31" PrivateAssets="all" />
    </ItemGroup>

</Project>

### PR DESCRIPTION
**Pull request by janvorli**
There is a bug in the new exception handling when `ThePreStub` is called
from `CallDescrWorkerInternal` and the exception is propagated through
that. One of such cases is when a managed class is being initialized
during JITting and the constructor is in an assembly that's not found.
The bug results in skipping all the native frames upto a managed frame
that called that native chain that lead to the exception.
The effect is that some lock holders are skipped and the exception is
not converted to `TypeInitializationException`.

The fix is to ensure that when `ThePreStub` is called by
`CallDescrWorkerInternal`, the exception is not caught in the
`PreStubWorker`. It is left flowing into the native calling code instead.

On Windows, we also need to prevent the `ProcessCLRException` invocation
to call into the managed exception handling code for the case when the 
`ProcessCLRException` personality routine was on one of our asm helpers.

Close https://github.com/dotnet/runtime/issues/112502

### CODE REVIEW

File: src/coreclr/vm/prestub.cpp [hunk 1]
```diff
@@ -2556,17 +2566,33 @@ static PCODE PreStubWorker_Preemptive(
     // No GC frame is needed here since there should be no OBJECTREFs involved
     // in this call due to UnmanagedCallersOnlyAttribute semantics.
 
-    INSTALL_MANAGED_EXCEPTION_DISPATCHER;
-    INSTALL_UNWIND_AND_CONTINUE_HANDLER;
+    EX_TRY
+    {
+        bool propagateExceptionToNativeCode = IsCallDescrWorkerInternalReturnAddress(pTransitionBlock->m_ReturnAddress);
```
Comment (jkotas) [inline src/coreclr/vm/prestub.cpp:2571]: `CallDescrWorker` is guaranteed to run in cooperative mode, but `PreStubWorker_Preemptive` is preemptive entrypoint so it should not ever be called by called by CallDescrWorker. Are the changes in `PreStubWorker_Preemptive` reachable?

File: src/coreclr/vm/prestub.cpp [hunk 2]
```diff
@@ -2618,60 +2644,76 @@ extern "C" PCODE STDCALL PreStubWorker(TransitionBlock* pTransitionBlock, Method
 
         pPFrame->Push(CURRENT_THREAD);
 
-        INSTALL_MANAGED_EXCEPTION_DISPATCHER;
-        INSTALL_UNWIND_AND_CONTINUE_HANDLER;
+        EX_TRY
+        {
+            bool propagateExceptionToNativeCode = IsCallDescrWorkerInternalReturnAddress(pTransitionBlock->m_ReturnAddress);
```
Comment (jkotas) [inline src/coreclr/vm/prestub.cpp:2649]: Does this problem exist in other places that use `INSTALL_MANAGED_EXCEPTION_DISPATCHER_EX

For example, can ExternalMethodFixupWorker or VSD_ResolveWorker end up appear to be called from CallDescrWorker?

Comment (janvorli) [reply src/coreclr/vm/prestub.cpp:2649]: That's a good point. I've checked and verified that both of the cases you've mentioned can be called via `CallDescrWorker`, so both suffer from the same issue in case there is an exception stemming from the resolution of the target. I think there are no other cases than the ones you've mentioned.

File: src/tests/Regressions/coreclr/GitHub_76531/test76531.cs [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+            catch (TypeInitializationException)
+            {
+                // This catch fails with issue #76531
+            }
+        }
+
+        [Fact]
+        public static void TestEntryPoint()
+        {
+            File.Delete(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "dependencytodelete.dll"));
```
Comment (jkoritzinsky) [inline src/tests/Regressions/coreclr/GitHub_76531/test76531.cs:39]: Instead of deleting it, could we instead change the csproj to set `Private="false"` on the ProjectReference so it isn't copied to the output in the first place?

Comment (janvorli) [reply src/tests/Regressions/coreclr/GitHub_76531/test76531.cs:39]: Thanks for suggesting it, I'll give it a try.

**Comment by janvorli** [comment]
@jkotas can you please take another look? I believe I have addressed all your feedback.

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/pull/111937#discussion_r1933038306 does not appear addressed.

File: src/tests/Regressions/coreclr/GitHub_76531/tailcallinvoker.il [hunk 4]
```diff
@@ -0,0 +1,17 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+.assembly extern legacy library mscorlib {}
+.assembly extern dependencytodelete {}
+.assembly 'lowlevel' {}
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_76531/tailcallinvoker.il:6]:
```suggestion
.assembly 'tailcallinvoker' {}
```
Should the assembly name match the file name?

File: src/tests/Regressions/coreclr/GitHub_76531/test76531.csproj [hunk 5]
```diff
@@ -0,0 +1,17 @@
+<Project Sdk="Microsoft.NET.Sdk">
+  <PropertyGroup>
+    <!-- Needed for mechanical merging of all remaining tests, this particular project may not actually need process isolation -->
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_76531/test76531.csproj:3]: Does the test need the process isolation? If yes, this comment should be deleted. If no, both this comment and the property should be deleted.

Comment (janvorli) [reply src/tests/Regressions/coreclr/GitHub_76531/test76531.csproj:3]: I need to check that.

File: src/tests/Regressions/coreclr/GitHub_76531/tailcallinvoker.il (hunk 4 above)
Comment (janvorli) [reply src/tests/Regressions/coreclr/GitHub_76531/tailcallinvoker.il]: Thank you for spotting this, I've forgotten to rename it after renaming the file itself locally.

**Review by jkotas — APPROVED** [review]
LGTM!
