### PR TITLE
JIT: handle x86 tail call via helper when control expression is spilled

### LINKED ISSUE #120170: Test failure: JIT/Regression/JitBlue/Runtime_72845/Runtime_72845/Runtime_72845.cmd
**Failed in:** [runtime-coreclr pgostress 20250926.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1159791)

**Failed tests:**
```
coreclr windows x86 Checked instrument_if_optimizing @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/Runtime_72845/Runtime_72845/Runtime_72845.cmd
```

**Error message:**
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'EqualityComparerPER`1' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.FSharp.Core.LanguagePrimitives.HashCompare.isArray(Type ty) in D:_work1ssrcsharpsrcFSharp.Coreprim-types.fs:line 1691
   at Microsoft.FSharp.Core.LanguagePrimitives.HashCompare.checkType@1743(Boolean er, HashSet`1 processed, Int32 index, Type[] types) in D:_work1ssrcsharpsrcFSharp.Coreprim-types.fs:line 1758
   at Microsoft.FSharp.Core.LanguagePrimitives.HashCompare.canUseDefaultEqualityComparer(Boolean er, Type rootType) in D:_work1ssrcsharpsrcFSharp.Coreprim-types.fs:line 1776
   at Microsoft.FSharp.Core.LanguagePrimitives.HashCompare.getEqualityComparer[T](Boolean er) in D:_work1ssrcsharpsrcFSharp.Coreprim-types.fs:line 1828
   at Microsoft.FSharp.Core.LanguagePrimitives.HashCompare.EqualityComparerPER`1..cctor() in D:_work1ssrcsharpsrcFSharp.Coreprim-types.fs:line 1861
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Core.LanguagePrimitives.HashCompare.GenericEqualityWithComparerIntrinsic[T](IEqualityComparer comp, T x, T y) in D:_work1ssrcsharpsrcFSharp.Coreprim-types.fs:line 1886
   at Microsoft.FSharp.Collections.FSharpList`1.Equals(FSharpList`1 obj, IEqualityComparer comp)
   at Runtime_72845.main(String[] _arg1)

Return code:      1
Raw output file:      C:hwAD960928wBB02099EuploadsJitBlueRuntime_72845Runtime_72845output.txt
Raw output:
BEGIN EXECUTION
 "C:hwAD960928pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Runtime_72845.dll 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 9/27/2025 8:04:07 AM
Processing C:corescorerun.exe.3628.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggerscdb.exe -c "$<C:hwAD960928		mpfxeclh.tmp" -z "C:corescorerun.exe.3628.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.3628.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwAD960928pPDB
Symbol search path is: C:hwAD960928pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sat Sep 27 08:04:13.000 2025 (UTC + 0:00)
System Uptime: 0 days 0:23:55.695
Process Uptime: 0 days 0:00:06.000
..........................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(e2c.ee4): CLR exception - code e0434352 (first/second chance not available)
For analysis of this file, run !analyze -v
eax=00000000 ebx=00000000 ecx=00000005 edx=00000000 esi=00000003 edi=00000003
eip=7778f3ec esp=0077a5d8 ebp=0077a768 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000206
ntdll!NtWaitForMultipleObjects+0xc:
7778f3ec c21400          ret     14h
0:000> cdb: Reading initial command '$<C:hwAD960928		mpfxeclh.tmp'
0:000> .cordll -lp "C:hwAD960928p"
The call to LoadLibrary(sos) failed, Win32 error 0n2
    "T
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor648|0_649(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Make sure we order the control expression after the spill.

Also add a range control to selectively enable instrumentation stress.

Fixes #120170.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

Small handful of diffs.

**Comment by AndyAyersMS** [comment]
Remaining failures look like timeouts / stackoverflow tester.

Tier1+instr is likely fairly slow; I wonder if we should invest in making it faster.

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -3504,8 +3504,10 @@ GenTree* Lowering::LowerTailCallViaJitHelper(GenTreeCall* call, GenTree* callTar
     assert(argEntry != nullptr);
     GenTree* arg0 = argEntry->GetEarlyNode()->AsPutArgStk()->gtGetOp1();
 
+    // Temporarily link in the call target range just before the call, since it
+    // may refer to a spilled temp. We will move the putarg after this via MoveCFGCallArgs below.
     ContainCheckRange(callTargetRange);
-    BlockRange().InsertAfter(arg0, std::move(callTargetRange));
+    BlockRange().InsertBefore(call, std::move(callTargetRange));
```
Comment (jakobbotsch) [inline src/coreclr/jit/lower.cpp]: I think this is right since it matches how we normally insert the call target. However, I am unsure what the code above that just removes `gtCallAddr` is doing. That code seems odd. Do you have any insight into it?

From reading the code I am guessing we have two separate cases: one where `callTarget` is `call->gtCallAddr` and thus is already inserted into LIR, and another where `callTarget` was just created and hasn't been inserted yet.

I think for the former case the handling here is wrong -- we should not be moving the call target IR around.

I would suggest inserting `callTargetRange` before the call to `LowerTailCallViaJitHelper` in `LowerCall`, when necessary, and updating `LowerTailCallViaJitHelper` to stop trying to move those nodes around.

File: src/coreclr/jit/lower.cpp [hunk 2]
```diff
@@ -3540,6 +3542,9 @@ GenTree* Lowering::LowerTailCallViaJitHelper(GenTreeCall* call, GenTree* callTar
     assert(arg3->OperIs(GT_CNS_INT));
 #endif // DEBUG
 
+    // Now reorder so all the putargs are just before the call.
+    MoveCFGCallArgs(call);
```
Comment (jakobbotsch) [inline src/coreclr/jit/lower.cpp]: Rename `MoveCFGCallArgs` to something like `MovePutArgNodesUpToCall`?

File: src/coreclr/jit/lower.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lower.cpp]: Reminds me that at some point I'd like to go rework how GT_CALL handles all this and not have two seemingly similar mechanisms for specifying where control should go.

I'll try inserting earlier.

File: src/coreclr/jit/lower.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lower.cpp]: Yes, did that.

File: src/coreclr/jit/lower.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lower.cpp]: Latest commit does the insertion earlier, and no removal/shuffling needed later.

**Review by jakobbotsch — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
pgostress failure is #110173

libraries-pgo is a bit messy, but failures are either timeouts (#120902), ooms (#120918), or one failure that seems timing related and unrelated to this PR:
```
x64 windows

DOTNET_JitDelegateProfiling=1
DOTNET_JitVTableProfiling=1
DOTNET_ReadyToRun=0
DOTNET_TC_QuickJitForLoops=1
DOTNET_TieredCompilation=1
DOTNET_TieredPGO=1

  Starting:    System.Transactions.Local.Tests (parallel test collections = on [4 threads], stop on fail = off
    System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get [FAIL]
      Assert.Equal() Failure: Values differ
      Expected: 00:02:00
      Actual:   00:01:00
```
