### PR TITLE
ILASM - Fixing ILASM roundtrip issue with `vararg` calling convention

### LINKED ISSUE #72759: Test failure JIT\\Regression\\JitBlue\\Runtime_71375\\Runtime_71375\\Runtime_71375.cmd
Run: [runtime-coreclr ilasm 20220723.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1899690&view=ms.vss-test-web.build-test-results-tab&runId=49445382&resultId=105488&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked ilasmroundtrip @ Windows.10.Arm64v8.Open

- JIT\\Regression\\JitBlue\\Runtime_71375\\Runtime_71375\\Runtime_71375.cmd
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

coreclr Linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open

- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

coreclr Linux arm Checked ilasmroundtrip @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/Directed/debugging/poisoning/poison/poison.sh

coreclr Linux arm64 Checked ilasmroundtrip @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/Directed/debugging/poisoning/poison/poison.sh

coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

coreclr OSX x64 Checked ilasmroundtrip @ OSX.1200.Amd64.Open

- JIT/Directed/debugging/poisoning/poison/poison.sh

coreclr OSX arm64 Checked ilasmroundtrip @ OSX.1200.ARM64.Open

- JIT/Directed/debugging/poisoning/poison/poison.sh
```

**Error message:**
```
Unhandled exception. System.BadImageFormatException: Bad binary signature. (0x80131192 (META_E_BAD_SIGNATURE))
at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(RuntimeMethodHandle method, RuntimeTypeHandle[] instantiation)
at Runtime_71375.Main()

Return code:      1
Raw output file:      D:\h\w\A7D8091A\w\B20B0954\uploads\Reports\JIT.Regression\JitBlue\Runtime_71375\Runtime_71375\Runtime_71375.output.txt
Raw output:
BEGIN EXECUTION
D:\h\w\A7D8091A\p\ildasm.exe /raweh /unicode /out=Runtime_71375.dasm.il Runtime_71375.dll
D:\h\w\A7D8091A\p\ilasm.exe /output=Runtime_71375.asm.dll  Runtime_71375.dasm.il

.NET IL Assembler.  Version 7.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'Runtime_71375.dasm.il'  to EXE --> 'Runtime_71375.asm.dll'
Source file is UNICODE

Assembled method Runtime_71375::Main
Assembled method Runtime_71375::VarArgs
Assembled method Runtime_71375::Problem
Assembled method Runtime_71375::.ctor
Creating PE file

Emitting classes:
Class 1:Runtime_71375

Emitting fields and methods:
Global
Class 1Methods: 4;
Resolving local member refs: 1 -> 0 defs, 1 refs, 0 unresolved

Emitting events and properties:
Global
Class 1
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
"D:\h\w\A7D8091A\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Runtime_71375.asm.dll
END EXECUTION OF IL{D}ASM BINARY - FAILED -532462766 vs 100
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\A7D8091A\p
D:\h\w\A7D8091A\w\B20B0954\e\JIT\Regression\JitBlue\Runtime_71375\Runtime_71375\Runtime_71375.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_Runtime_71375_Runtime_71375_Runtime_71375_._JitBlue_Runtime_71375_Runtime_71375_Runtime_71375_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by TIHan**
Should resolve: https://github.com/dotnet/runtime/issues/72759

**Description**

ILASM was failing to emit the correct callsite signature for a method with a `vararg` calling convention if one of the parameters was generic instantiation of a type.

In `ResolveLocalMemberRefs`, it seems we lost some information when getting the fixed signature for `vararg` callconv and it creates a bad signature for the new member reference.

There are two solutions:

1. Remove special handling for `vararg` callconv in `ResolveLocalMemberRefs` as we already have the correct signature from `m_LocalMethodRefDList`.
2. Fix `CountBytesOfOneArg` to handle `ELEMENT_TYPE_GENERICINST` as described by @jakobbotsch 

The PR is now using solution number 2.

I manually tested this and it resolves the issue reported. I also tried this scenario:
ClassLibrary1.dll
```csharp
using System.Runtime.Intrinsics;

namespace ClassLibrary1
{
    public class Class1
    {
        public static int paramLength(Vector128<int> arg, __arglist)
        {
            ArgIterator iterator = new ArgIterator(__arglist);
            return iterator.GetRemainingCount();
        }
    }
}
```
vararg_test.exe
```csharp
using ClassLibrary1;
using System.Runtime.Intrinsics;

Console.WriteLine(Class1.paramLength(Vector128<int>.AllBitsSet, __arglist(1, 2)));
```
This scenario works with the PR changes, so this gives me confidence in the change as this is across assembly boundaries.

**Acceptance Criteria**
- [x] No additional ilasm roundtrip failures in CI

### CODE REVIEW

**Comment by TIHan** [comment]
@dotnet/jit-contrib This is ready, pending CI runs

**Comment by jakobbotsch** [comment]
> it seems we lost some information when getting the fixed signature and it creates a bad signature for the new member reference.

There are other uses of this `_ GetFixedSigOfVarArg` function, does it need to be fixed instead it if is returning a bad signature?

If I understand the fix here right it will cause ilasm to unnecessarily create `TypeRef` tokens to types defined within the same module, which seems a little wasteful (though given that it is only for varargs, probably not a big deal).

**Comment by jakobbotsch** [comment]
> There are other uses of this `_GetFixedSigOfVarArg` function, does it need to be fixed instead it if is returning a bad signature?

It looks suspect to me that `_CountBytesOfOneArg` used by `_GetFixedSigOfVarArg` does not handle `ELEMENT_TYPE_GENERICINST`.

**Comment by TIHan** [comment]
> There are other uses of this _GetFixedSigOfVarArg function, does it need to be fixed instead it if is returning a bad signature?

Possibly, I didn't know exactly what might need to be handled in there and I think the runtime uses this as well. To minimize any risk, I went with just the change only in ILASM.

> If I understand the fix here right it will cause ilasm to unnecessarily create TypeRef

Is this when the `tkMemberDef` is 0? When debugging, it actually does not go down that path.

> It looks suspect to me that _CountBytesOfOneArg used by _GetFixedSigOfVarArg does not handle ELEMENT_TYPE_GENERICINST.

I think this might be it. I just tried to handle this, and when checking it under ILDASM I can see the parameter type starting to form:
```
    IL_000b:  call       vararg int32 Runtime_71375::VarArgs(int32,
                                                             int32,
                                                             int32,
                                                             int32,
                                                             int32,
                                                             int32,
                                                             valuetype [System.Runtime.Intrinsics]System.Runtime.Intrinsics.Vector128`1<void,,int32,,,,,>)
```
I'll see if I can get it working.

**Comment by TIHan** [comment]
Updated the PR to handle `ELEMENT_TYPE_GENERICINST` in `CountBytesOfOneArg` and reverted the other fix in favor of it.

@dotnet/jit-contrib ready for review again pending CI runs.

File: src/coreclr/inc/corhlprpriv.cpp [hunk 1]
```diff
@@ -109,6 +109,23 @@ HRESULT _CountBytesOfOneArg(
     }
     switch (ulElementType)
     {
+        case ELEMENT_TYPE_GENERICINST:
+            CHECK_REMAINDER;
```
Comment (jkotas) [inline src/coreclr/inc/corhlprpriv.cpp:113]: Should `CHECK_REMAINDER` be in front of `CorSigUncompressData` instead?

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/inc/corhlprpriv.cpp (hunk 1 above)
Comment (jkotas) [reply src/coreclr/inc/corhlprpriv.cpp:113]: And there should be `cb = cbTotalMax - cbTotal;` in front of `_CountBytesOfOneArg` calls.

Comment (TIHan) [reply src/coreclr/inc/corhlprpriv.cpp:113]: I see, will fix that.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/inc/corhlprpriv.cpp [hunk 2]
```diff
@@ -109,6 +109,27 @@ HRESULT _CountBytesOfOneArg(
     }
     switch (ulElementType)
     {
+        case ELEMENT_TYPE_GENERICINST:
+            // skip over generic type
+            CHECK_REMAINDER;
```
Comment (jakobbotsch) [inline src/coreclr/inc/corhlprpriv.cpp:114]: I guess this is not strictly necessary in front of the `_CountBytesOfOneArg` calls, since the function ensures this is called before it reads anything from the signature.

Comment (jakobbotsch) [reply src/coreclr/inc/corhlprpriv.cpp:114]: Actually I see the other cases do the same thing, so nevermind this.

Comment (TIHan) [reply src/coreclr/inc/corhlprpriv.cpp:114]: Sure, but looking at places where we call `_CountBytesOfOneArg` in here, it has a `CHECK_REMAINDER` before it.
