### PR TITLE
Ensure kmask registers are marked available 

### LINKED ISSUE #83917: System.Runtime.Intrinsics.Tests crashing on Linux x64
```
/datadisks/disk1/work/B226096B/w/B20309D9/e /datadisks/disk1/work/B226096B/w/B20309D9/e
  Discovering: System.Runtime.Intrinsics.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Intrinsics.Tests (found 1023 test cases)
  Starting:    System.Runtime.Intrinsics.Tests (parallel test collections = on, max threads = 2)
./RunTests.sh: line 168: 15658 Segmentation fault      (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Runtime.Intrinsics.Tests.runtimeconfig.json --depsfile System.Runtime.Intrinsics.Tests.deps.json xunit.console.dll System.Runtime.Intrinsics.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/datadisks/disk1/work/B226096B/w/B20309D9/e
----- end Sat Mar 25 04:26:45 UTC 2023 ----- exit code 139 ----------------------------------------------------------
exit code 139 means SIGSEGV Illegal memory access. Deref invalid pointer, overrunning buffer, stack overflow etc. Core dumped.
```

Full log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-83881-merge-e7a7337a0eee400295/System.Runtime.Intrinsics.Tests/1/console.edf1d97e.log?helixlogtype=result

Failed in #83881 (failing in all PRs that run this leg)

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/83917

This does two parts:
1. Ensures that the kmask registers are actually reset to the available state
2. Updates various places throughout the JIT to account for the existence of a third register type

### CODE REVIEW

File: src/coreclr/jit/lsra.h [hunk 1]
```diff
@@ -46,7 +47,21 @@ typedef var_types RegisterType;
...
+    {
+        return MaskRegisterType;
+    }
+#endif // TARGET_XARCH
+    else
+    {
+        assert(varTypeUsesFloatReg(type));
+        return FloatRegisterType;
+    }
 }
```
Comment (tannergooding) [inline src/coreclr/jit/lsra.h:65]: Checks throughout the JIT have been ordered under the presumption that `varTypeUsesIntReg` is the most likely occurrence. Where mask register handling is needed, `varTypeUsesMaskReg` is the middle case since we only need 1 additional check to cover all 3 cases. This allow the last case to `assert`.

This keeps 1-check for non-xarch, minimizes the total ifdefs when mask handling is needed, and ensures we need no more than 2 checks on xarch with the common case being 1 check. Ideally this helps keep it "pay for play".

Having `varTypeUsesIntReg` allowed a few other checks to become simplified/improved in general.

**Comment by tannergooding** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=217489&view=ms.vss-build-web.run-extensions-tab)

No assembly diffs, but some measurable TP improvements of up to `-0.25%` in MinOpts and up to `-0.21%` in FullOpts.

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib, @dotnet/avx512-contrib

**Review by TIHan — APPROVED** [review]

**Comment by tannergooding** [comment]
PIN for [2da1ee0](https://github.com/dotnet/runtime/pull/83927/commits/2da1ee059350822b7aca6a027dc1f6d1f29d0f8c) (just have EVEX on) vs [8df1b80](https://github.com/dotnet/runtime/pull/83927/commits/8df1b8050fce27884eebbcf197e6fa010778927a) (this PR)

```
Base: 238543002576, Diff: 238444519041, -0.0413%

??$varTypeUsesIntReg@W4var_types@@@@YA_NW4var_types@@@Z                                                : 191369965  : NA       : 19.17% : +0.0802%
?allocateRegisters@LinearScan@@QEAAXXZ                                                                 : 132427491  : +1.15%   : 13.27% : +0.0555%
??$regType@W4var_types@@@@YA?AW4var_types@@W40@@Z                                                      : 95746343   : NA       : 9.59%  : +0.0401%
??$varTypeUsesSameRegType@W4var_types@@PEAUGenTree@@@@YA_NW4var_types@@PEAUGenTree@@@Z                 : 17034759   : NA       : 1.71%  : +0.0071%
??$varTypeUsesIntReg@PEAUGenTreeCall@@@@YA_NPEAUGenTreeCall@@@Z                                        : 7945145    : NA       : 0.80%  : +0.0033%
?processBlockStartLocations@LinearScan@@AEAAXPEAUBasicBlock@@@Z                                        : 1578988    : +0.04%   : 0.16%  : +0.0007%
??$varTypeUsesSameRegType@PEAUGenTreeUnOp@@PEAUGenTree@@@@YA_NPEAUGenTreeUnOp@@PEAUGenTree@@@Z         : 1206506    : NA       : 0.12%  : +0.0005%
?inst_Mov@CodeGen@@QEAAXW4var_types@@W4_regNumber_enum@@1_NW4emitAttr@@W4insFlags@@@Z                  : 1006923    : +9.89%   : 0.10%  : +0.0004%
?LowerRet@Lowering@@AEAAXPEAUGenTreeUnOp@@@Z                                                           : -2294549   : -23.37%  : 0.23%  : -0.0010%
?genCall@CodeGen@@IEAAXPEAUGenTreeCall@@@Z                                                             : -3470872   : -1.78%   : 0.35%  : -0.0015%
?gtNewTempAssign@Compiler@@QEAAPEAUGenTree@@IPEAU2@PEAPEAUStatement@@AEBVDebugInfo@@PEAUBasicBlock@@@Z : -3993960   : -1.62%   : 0.40%  : -0.0017%
?identifyCandidates@LinearScan@@AEAAXXZ                                                                : -4422123   : -1.20%   : 0.44%  : -0.0019%
?allocateReg@LinearScan@@AEAA?AW4_regNumber_enum@@PEAVInterval@@PEAVRefPosition@@@Z                    : -4656710   : -1.52%   : 0.47%  : -0.0020%
??RLclVarDsc_BlendedCode_Less@@QEAA_NII@Z                                                              : -4762712   : -3.38%   : 0.48%  : -0.0020%
?useFloatReg@@YA_NW4var_types@@@Z                                                                      : -8149120   : -100.00% : 0.82%  : -0.0034%
?lvRegMask@LclVarDsc@@QEBA_KXZ                                                                         : -14696972  : -14.29%  : 1.47%  : -0.0062%
?genCodeForTreeNode@CodeGen@@IEAAXPEAUGenTree@@@Z                                                      : -15330459  : -0.94%   : 1.54%  : -0.0064%
?genConsumeReg@CodeGen@@IEAA?AW4_regNumber_enum@@PEAUGenTree@@@Z                                       : -30673675  : -2.89%   : 3.07%  : -0.0129%
?LowerStoreLocCommon@Lowering@@AEAAXPEAUGenTreeLclVarCommon@@@Z                                        : -31562824  : -12.76%  : 3.16%  : -0.0132%
?BuildNode@LinearScan@@AEAAHPEAUGenTree@@@Z                                                            : -42215347  : -2.92%   : 4.23%  : -0.0177%
jitstd::`anonymous namespace'::quick_sort<unsigned int *,LclVarDsc_BlendedCode_Less>                   : -137651696 : -7.73%   : 13.79% : -0.0577%
??$varTypeUsesFloatReg@W4var_types@@@@YA_NW4var_types@@@Z                                              : -242380033 : -100.00% : 24.28% : -0.1016%
```

**Comment by tannergooding** [comment]
Remaining extra-platforms failures are already known and for Mono, not RyuJIT.

File: src/coreclr/jit/compiler.h [hunk 2]
```diff
@@ -994,13 +994,14 @@ class LclVarDsc
...
+            if (varTypeUsesIntReg(this))
             {
-                regMask = genRegMaskFloat(GetRegNum(), TypeGet());
+                regMask = genRegMask(GetRegNum());
             }
             else
             {
-                regMask = genRegMask(GetRegNum());
+                assert(varTypeUsesFloatReg(this));
+                regMask = genRegMaskFloat(GetRegNum(), TypeGet());
```
Comment (kunalspathak) [inline src/coreclr/jit/compiler.h:1004]:
```suggestion
                regMask = genRegMaskFloat(GetRegNum() ARM_ARG(TypeGet()));
```

We should update the definition to:

```c++
 inline regMaskTP genRegMaskFloat(regNumber reg ARM_ARG(var_types type = TYP_DOUBLE));
```

File: src/coreclr/jit/codegencommon.cpp [hunk 3]
```diff
@@ -9335,10 +9346,10 @@ void CodeGen::genPoisonFrame(regMaskTP regLiveIn)
 //
 void CodeGen::genBitCast(var_types targetType, regNumber targetReg, var_types srcType, regNumber srcReg)
 {
-    const bool srcFltReg = varTypeUsesFloatReg(srcType) || varTypeIsSIMD(srcType);
+    const bool srcFltReg = varTypeUsesFloatReg(srcType);
```
Comment (kunalspathak) [inline src/coreclr/jit/codegencommon.cpp:9349]: `varTypeIsSIMD()` does seems redundant when used with `varTypeUsesFloatReg()`, not sure why it was added in first place.

**Comment by kunalspathak** [comment]
> TP improvements of up to `-0.25%` in MinOpts and up to `-0.21%` in FullOpts.

Nice, seems because of `varTypeUsesSameRegType`.

File: src/coreclr/jit/target.h [hunk 4]
```diff
@@ -612,6 +611,7 @@ inline regMaskTP genRegMask(regNumber regNum, var_types type)
     }
     else
     {
+        assert(varTypeUsesIntReg(type));
```
Comment (kunalspathak) [inline src/coreclr/jit/target.h:614]: Should this also be reverseed to have `varTypeUsesIntReg()` check first? Also, shouldn't this include a case for kmask register too?

File: src/coreclr/jit/compiler.h [hunk 5]
```diff
@@ -994,13 +994,14 @@ class LclVarDsc
...
-            if (varTypeUsesFloatReg(TypeGet()))
+            if (varTypeUsesIntReg(this))
             {
-                regMask = genRegMaskFloat(GetRegNum(), TypeGet());
+                regMask = genRegMask(GetRegNum());
             }
             else
             {
-                regMask = genRegMask(GetRegNum());
+                assert(varTypeUsesFloatReg(this));
```
Comment (kunalspathak) [inline src/coreclr/jit/compiler.h:1003]: Is the reason you haven't added a check for kmask register is because we don't have a need currently and a check will be added here in future?

**Review by kunalspathak — CHANGES_REQUESTED** [review]

File: src/coreclr/jit/lsra.cpp [hunk 6]
```diff
@@ -714,6 +714,9 @@ LinearScan::LinearScan(Compiler* theCompiler)
         availableIntRegs &= ~RBM_CALLEE_SAVED | RBM_ENC_CALLEE_SAVED;
         availableFloatRegs &= ~RBM_CALLEE_SAVED;
         availableDoubleRegs &= ~RBM_CALLEE_SAVED;
+#if defined(TARGET_XARCH)
+        availableMaskRegs &= ~RBM_CALLEE_SAVED;
```
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/lsra.cpp:718]: Today, no. But it doesn't hurt anything to have it and likewise aren't filtering other scenarios where we may not have any callee saved for the register type.

If we were to do something here, we should probably change it in a follow up PR to only mask off the relevant registers.

That is, `availableFloatRegs` should use `~RBM_FLT_CALLEE_SAVED` since the `RBM_CALLEE_SAVED` bits set by  `RBM_INT_CALLEE_SAVED` will never be hit.

That in turn would allow the compiler to optimize these away for platforms that have no callee saved registers for a given kind (like unix for float).

File: src/coreclr/jit/lsrabuild.cpp [hunk 7]
```diff
@@ -3841,13 +3851,15 @@ int LinearScan::BuildReturn(GenTree* tree)
...
+
+                            if (varTypeUsesIntReg(dstType))
                             {
-                                buildInternalFloatRegisterDefForNode(tree, dstRegMask);
+                                buildInternalIntRegisterDefForNode(tree, dstRegMask);
                             }
                             else
                             {
-                                buildInternalIntRegisterDefForNode(tree, dstRegMask);
+                                assert(varTypeUsesFloatReg(dstType));
```
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/lsrabuild.cpp:3861]: Not necessarily.

I simply added asserts to the places where `kmask` wasn't being handled. This works today since `kmask` is only introduced in lowering and is restricted to exactly one register and is only used as a return value for an intrinsic.

Once we finish expanding the support to take `kmask` as inputs, to support all 8 registers, and to have them appear from user code in importation, then some of these asserts may trigger and support will need to be added at that time.

File: src/coreclr/jit/target.h (hunk 4 above)
Comment (tannergooding) [reply src/coreclr/jit/target.h:614]: This is for `TARGET_ARM` (note the condition is `#ifndef`). We could inverse it, but since its ARM only I didn't see the need.

File: src/coreclr/jit/compiler.h (hunk 5 above)
Comment (tannergooding) [reply src/coreclr/jit/compiler.h:1003]: Yes. When support for kmask is expanded beyond the 1 special intrinsic that is only introduced in lowering, then we'll want/need to update this and potential downstream handling as well.

File: src/coreclr/jit/compiler.h (hunk 2 above)
Comment (tannergooding) [reply src/coreclr/jit/compiler.h:1004]: Fixed.

File: src/coreclr/jit/target.h (hunk 4 above)
Comment (tannergooding) [reply src/coreclr/jit/target.h:614]: Inverse and made it more obvious that path is for TARGET_ARM

**Review by kunalspathak — APPROVED** [review]
LGTM. Thanks!
