### PR TITLE
Use Knobs to populate AppContext switches

### LINKED ISSUE #77054: NativeAOT: Custom runtime without AppContext class throw
### Description

If you compile application with custom runtime where `System.AppContext` class is not defined, compiler crash

```
 System.AggregateException: One or more errors occurred. (Code generation failed for method '[S.P.CompilerGenerated]Internal.CompilerGenerated.<Module>.SetAppContextSwitches()')
   ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[S.P.CompilerGenerated]Internal.CompilerGenerated.<Module>.SetAppContextSwitches()'
   ---> System.InvalidOperationException: Expected type 'System.AppContext' not found in module 'SeeSharpSnake'
```

Even if I apply suggestion from https://github.com/dotnet/runtime/issues/63862#issuecomment-1014166018 to the csproj file due to this line
https://github.com/dotnet/runtime/blob/e790378284e6a85f5cb4f10cd7c443d5e296f2fb/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L230
workaround no longer working.

### Reproduction Steps

Close code from this PR https://github.com/MichalStrehovsky/seesharpsnake
Apply https://github.com/dotnet/runtime/issues/63862#issuecomment-1014166018

### Expected behavior

Custom runtimes can be built using NativeAOT

### Actual behavior

Currently it is blocked.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Previously AppContext switches were set by injecting a method that calls `AppContext.SetSwitch` at startup. Use the configuration blob added in #86068 instead. This makes startup a tiny bit faster and the outputs a tiny bit smaller.

Fixes #77054.

Cc @dotnet/ilc-contrib

### CODE REVIEW

File: src/coreclr/nativeaot/Runtime/RhConfig.cpp [hunk 1]
```diff
@@ -204,19 +239,19 @@ void RhConfig::ReadEmbeddedSettings(void *volatile * embeddedSettings, void* com
 {
     if (*embeddedSettings == NULL)
     {
-        uint32_t size = ((CompilerEmbeddedSettingsBlob*)compilerEmbeddedSettingsBlob)->Size;
+        uint32_t count = ((CompilerEmbeddedSettingsBlob*)compilerEmbeddedSettingsBlob)->Count;
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/Runtime/RhConfig.cpp:242]: We're treating the size as count incorrectly in rest of the code (missed that in the code review). So this is also a bugfix.

Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/Runtime/RhConfig.cpp]: Ended up deleting all of this.

It ran into an issue that we had a hard limit on how long a key or value can be and instead of writing more C code, I just deleted it and update the compiler to emit it in a format that we don't need to parse at all and just use as-is.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/AppContext.NativeAot.cs [hunk 2]
```diff
@@ -1,13 +1,34 @@
...
 {
     public static partial class AppContext
     {
+        private static unsafe Dictionary<string, object?> InitializeDataStore()
+        {
+            uint count = RuntimeImports.RhGetKnobValues(null, null);
+
+            byte*[] keys = new byte*[count];
+            byte*[] values = new byte*[count];
+            RuntimeImports.RhGetKnobValues(keys, values);
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/AppContext.NativeAot.cs:19]:
```suggestion
            uint count = RuntimeImports.RhGetKnobValues(out byte* keys, out byte* values);
```
Avoid the intermediate array?

Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/AppContext.NativeAot.cs]: Nice simplification!

**Review by jkotas — APPROVED** [review]
Thanks!
