### PR TITLE
Use FLS detach as thread termination notification on windows.

### LINKED ISSUE #110350: Process not responsive dump indicates garbage collection
### Description

After upgrading to .net 9, we have random processes, which just freeze, becoming completely unresponsive
Process are run as windows services on windows VM

I have a dump file, which I could send to you
I would just rather not make that public as it probably has passwords within

Analyzing the dump indicates a possible problem in the garbage collector

0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 1484

    Key  : Analysis.Elapsed.mSec
    Value: 5300

    Key  : Analysis.IO.Other.Mb
    Value: 0

    Key  : Analysis.IO.Read.Mb
    Value: 1

    Key  : Analysis.IO.Write.Mb
    Value: 1

    Key  : Analysis.Init.CPU.mSec
    Value: 781

    Key  : Analysis.Init.Elapsed.mSec
    Value: 120611

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 223

    Key  : Analysis.Version.DbgEng
    Value: 10.0.27725.1000

    Key  : Analysis.Version.Description
    Value: 10.2408.27.01 amd64fre

    Key  : Analysis.Version.Ext
    Value: 1.2408.27.1

    Key  : CLR.Engine
    Value: CORECLR

    Key  : CLR.Version
    Value: 9.0.24.52809

    Key  : Failure.Bucket
    Value: BREAKPOINT_80000003_coreclr.dll!WKS::GCHeap::WaitUntilGCComplete

    Key  : Failure.Hash
    Value: {54e9a6da-d4d0-d004-574b-4219b46bdb8d}

    Key  : Failure.Source.FileLine
    Value: 265

    Key  : Failure.Source.FilePath
    Value: D:\a\_work\1\s\src\coreclr\gc\gcee.cpp

    Key  : Failure.Source.SourceServerCommand
    Value: raw.githubusercontent.com/dotnet/runtime/9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3/src/coreclr/gc/gcee.cpp

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 896327

    Key  : Timeline.Process.Start.DeltaSec
    Value: 17922

    Key  : WER.OS.Branch
    Value: rs5_release

    Key  : WER.OS.Version
    Value: 10.0.17763.1

    Key  : WER.Process.Version
    Value: 1.0.0.0

FILE_IN_CAB:  SmfHaircuts.Service-2024-12-03-YB6213.DMP

NTGLOBALFLAG:  0

APPLICATION_VERIFIER_FLAGS:  0

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 0000000000000000
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 0

FAULTING_THREAD:  00000f6c

PROCESS_NAME:  SmfHaircuts.Service.dll

ERROR_CODE: (NTSTATUS) 0x80000003 - {EXCEPTION}  Breakpoint  A breakpoint has been reached.

EXCEPTION_CODE_STR:  80000003

STACK_TEXT:  
0000008c`61d7e028 00007ffc`bdba0f33     : 00000000`00000000 000002be`90a8dab0 000002be`90a8d9f0 0000008c`61d7e170 : ntdll!NtWaitForSingleObject+0x14
0000008c`61d7e030 00007ffb`364f1c30     : 00000000`00000000 00004612`d1730f35 00000000`00000000 00000000`00000284 : KERNELBASE!WaitForSingleObjectEx+0x93
0000008c`61d7e0d0 00007ffb`36416915     : 00000000`00000000 0000008c`61d7e2d0 00000000`00000804 0000008c`61d7e1b0 : coreclr!WKS::GCHeap::WaitUntilGCComplete+0x30
0000008c`61d7e100 00007ffb`364e8328     : 00007ffa`d68130c0 00000000`00000000 00000000`00000000 0000027d`f97fc570 : coreclr!Thread::RareDisablePreemptiveGC+0x9d
0000008c`61d7e190 00007ffb`3659ea2d     : 00007ffa`d68130c0 00000000`00000000 000002be`906cedf0 00000001`00000000 : coreclr!JIT_ReversePInvokeEnterRare2+0x18
0000008c`61d7e1c0 00007ffa`d7e5b718     : 00000000`00000004 0000008c`61d7e260 00000000`00000000 00007ffc`c166598d : coreclr!JIT_ReversePInvokeEnterTrackTransitions+0x9d13d
0000008c`61d7e1f0 00000000`00000004     : 0000008c`61d7e260 00000000`00000000 00007ffc`c166598d 00000000`00000000 : 0x00007ffa`d7e5b718
0000008c`61d7e1f8 0000008c`61d7e260     : 00000000`00000000 00007ffc`c166598d 00000000`00000000 0000008c`61d7e1f0 : 0x4
0000008c`61d7e200 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x0000008c`61d7e260

STACK_COMMAND:  ~0s; .ecxr ; kb

FAULTING_SOURCE_LINE:  D:\a\_work\1\s\src\coreclr\gc\gcee.cpp

FAULTING_SOURCE_FILE:  D:\a\_work\1\s\src\coreclr\gc\gcee.cpp

FAULTING_SOURCE_LINE_NUMBER:  265

FAULTING_SOURCE_SRV_COMMAND:  https://raw.githubusercontent.com/dotnet/runtime/9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3/src/coreclr/gc/gcee.cpp

FAULTING_SOURCE_CODE:  
No source found for 'D:\a\_work\1\s\src\coreclr\gc\windows\gcenv.windows.cpp'

SYMBOL_NAME:  coreclr!WKS::GCHeap::WaitUntilGCComplete+30

MODULE_NAME: coreclr

IMAGE_NAME:  coreclr.dll

FAILURE_BUCKET_ID:  BREAKPOINT_80000003_coreclr.dll!WKS::GCHeap::WaitUntilGCComplete

OS_VERSION:  10.0.17763.1

BUILDLAB_STR:  rs5_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  9.0.24.52809

FAILURE_ID_HASH:  {54e9a6da-d4d0-d004-574b-4219b46bdb8d}

Followup:     MachineOwner

### Reproduction Steps

Not possilbe. Happens randomly

### Expected behavior

Not freezing

### Actual behavior

Process completely unresponsive

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #110350

Switches the mechanism for OS notification about thread termination to use FLS (Fiber Local Storage) - the same mechanism as used on NativeAOT.

The advantage of FLS notification is that it does not run while holding the Loader Lock, thus it does not require that the termination callback never calls or waits for an OS call that may need to acquire that same Loader Lock. (It is hard for us to guarantee the latter)

### CODE REVIEW

File: src/coreclr/vm/ceemain.cpp [hunk 1]
```diff
@@ -1702,6 +1702,130 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+// Parameters:
+//  thread        - thread to attach
+static void OsAttachThread(void* thread)
+{
+    void* threadFromCurrentFiber = FlsGetValue(g_flsIndex);
+
+    if (threadFromCurrentFiber != NULL)
+    {
+        _ASSERTE(!"Multiple threads encountered from a single fiber");
+        COMPlusThrowWin32();
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:1786]: This should be fail fast or `ASSERTE_ALL_BUILDS`. I do think we want to run any exception handling here.

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:1786]: `ASSERTE_ALL_BUILDS` would be the right choice if it did what the name implies, but is it just a regular assert?

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:1786]: Actually it looks like `ASSERTE_ALL_BUILDS` _is_ a failfast in CoreClr. It is in the NativeAOT where it is just a regular debug-only assert.

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp]: I saw the pattern commonly used in threeads.cpp. So I figured it might be the convention for this kind of code.

https://github.com/dotnet/runtime/blob/ca5cf417e37028812aa40111951b31f8808b3396/src/coreclr/vm/threads.cpp#L1051-L1055

https://github.com/dotnet/runtime/blob/ca5cf417e37028812aa40111951b31f8808b3396/src/coreclr/vm/threads.cpp#L1138-L1139

```
. . . bunch of other cases . . .
```

I do agree that ASSERTE_ALL_BUILDS intuitively seems more appropriate.

Comment (jkotas) [reply src/coreclr/vm/ceemain.cpp]: It is a convention to throw an exception when there is a (transient) error during runtime initialization.

This case is different: It means that something is really wrong, e.g. the process uses fibers that .NET runtime does not support.

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp]: Right. In this case these are situations that we cannot recover from, so should be a failfast or an equivalent.

File: src/coreclr/vm/threads.cpp [hunk 2]
```diff
@@ -1039,6 +1048,13 @@ void InitThreadManager()
     }
     CONTRACTL_END;
 
+#ifdef TARGET_WINDOWS
+    if (!InitFlsSlot())
+    {
+        _ASSERTE_ALL_BUILDS(!"Initialization of a FLS slot failed.");
```
Comment (jkotas) [inline src/coreclr/vm/threads.cpp:1054]: An exception would be more appropriate for this one. It would be even better if InitFlsSlot returns void and throws the exception right away.

**Comment by VSadov** [comment]
I suspect `JSImportGenerator` test failures are not related to this change as the failures happen equally on windows and on linux/osx, while this is a windows-specific change.

File: src/coreclr/vm/ceemain.cpp [hunk 3]
```diff
@@ -1702,6 +1702,127 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+    FlsSetValue(g_flsIndex, thread);
+}
+
+// Detach thread from OS notifications.
+// It fails fast if some other thread value was attached to the current fiber.
+// Parameters:
+//  thread        - thread to detach
+// Return:
+//  true if the thread was detached, false if there was no attached thread
+bool OsDetachThread(void* thread)
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:1799]: We never check the return value. Should it return `void`?

Comment (VSadov) [reply src/coreclr/vm/ceemain.cpp:1799]: This came from NativeAOT. I just mostly wanted to keep code similar. 

In NativeAOT returning false indicates that the thread was initialized (i.e the Thread object that is a C++ TLS object has meaningful data), but not attached (i.e. not inserted in the thread store- basically not a managed thread yest). Returning false here means that the rest of detachment steps like removing from threadstore are unnecessary. 

On CoreCLR the call to `SetThread(NULL)` seems to be more ad-hoc. It is called from 5 different places. It seems more like "just unsubscribe from OS notifications". Noone checks the result. 
`SetThread(NULL)` itself would clear appdomain regardless of whether the thread was attached to the runtime or not. 

Yes, I think we could return `void`. We evidently do not check the result.

File: src/coreclr/vm/ceemain.cpp [hunk 4]
```diff
@@ -1702,6 +1702,126 @@ BOOL STDMETHODCALLTYPE EEDllMain( // TRUE on success, FALSE on error.
...
+}
+
+void InitFlsSlot()
+{
+    // We use fiber detach callbacks to run our thread shutdown code because the fiber detach
+    // callback is made without the OS loader lock
+    g_flsIndex = FlsAlloc(FiberDetachCallback);
+    if (g_flsIndex == FLS_OUT_OF_INDEXES)
+    {
+        _ASSERTE(!"Initialization of an FLS slot failed.");
```
Comment (jkotas) [inline src/coreclr/vm/ceemain.cpp:1769]:
```suggestion
```
We do not assert on OOM

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by jkotas** [comment]
I am sorry - I have to revert this to unblock WinForms codeflow (#110801).
