### PR TITLE
[metadata] make mono_method_get_param_names external only

### LINKED ISSUE #83178: mono_method_get_param_names not wraped with MONO_ENTER_GC_UNSAFE
I found mono_method_get_param_names `MONO_ENTER_GC_UNSAFE` `MONO_EXIT_GC_UNSAFE`.

https://github.com/dotnet/runtime/blob/ae4ba7fb3ec2148e89d58f396b06f4f23c3875a4/src/mono/mono/metadata/loader.c#L1413

Can I add it, but will it break other function calls?

@vargaz @lambdageek  will you take one minute to check this?

this will crash when the class is not inited at below callstack:
```
coreclr.dll!mono_threads_transition_do_blocking(_MonoThreadInfo * info, const char * func) Line 759
	at F:\netease-gitlab\dotnet\runtime\src\mono\mono\utils\mono-threads-state-machine.c(759)
coreclr.dll!mono_threads_enter_gc_safe_region_unbalanced_with_info(_MonoThreadInfo * info, _MonoStackData * stackdata) Line 322
	at F:\netease-gitlab\dotnet\runtime\src\mono\mono\utils\mono-threads-coop.c(322)
coreclr.dll!mono_threads_enter_gc_safe_region_with_info(_MonoThreadInfo * info, _MonoStackData * stackdata) Line 275
	at F:\netease-gitlab\dotnet\runtime\src\mono\mono\utils\mono-threads-coop.c(275)
coreclr.dll!mono_threads_enter_gc_safe_region_internal(_MonoStackData * stackdata) Line 257
	at F:\netease-gitlab\dotnet\runtime\src\mono\mono\utils\mono-threads-coop.c(257)
coreclr.dll!mono_coop_mutex_lock(_MonoCoopMutex * mutex) Line 55
	at F:\netease-gitlab\dotnet\runtime\src\mono\mono\utils\mono-coop-mutex.h(55)
coreclr.dll!mono_loader_lock() Line 136
	at F:\netease-gitlab\dotnet\runtime\src\mono\mono\metadata\loader.c(136)
coreclr.dll!mono_class_setup_supertypes(_MonoClass * klass) Line 4019
	at F:\netease-gitlab\dotnet\runtime\src\mono\mono\metadata\class-init.c(4019)
coreclr.dll!mono_class_init_internal(_MonoClass * klass) Line 2933
	at F:\netease-gitlab\dotnet\runtime\src\mono\mono\metadata\class-init.c(2933)
coreclr.dll!mono_method_get_param_names(_MonoMethod * method, const char * * names) Line 1437
	at F:\netease-gitlab\dotnet\runtime\src\mono\mono\metadata\loader.c(1437)


```

### PR DESCRIPTION
**Pull request by lambdageek**
Add GC Unsafe transitions.

Change the runtime to use mono_method_get_param_names_internal.

Fixes https://github.com/dotnet/runtime/issues/83178

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

File: src/mono/mono/component/debugger-agent.c [hunk 1]
```diff
@@ -8850,7 +8850,7 @@ method_commands_internal (int command, MonoMethod *method, MonoDomain *domain, g
 
 		/* Emit parameter names */
 		names = g_new (char *, sig->param_count);
-		mono_method_get_param_names (method, (const char **) names);
+		mono_method_get_param_names_nternal (method, (const char **) names);
```
Comment (lewing) [inline src/mono/mono/component/debugger-agent.c:8853]:
```suggestion
		mono_method_get_param_names_internal (method, (const char **) names);
```

**Comment by srxqds** [comment]
thank you
