### PR TITLE
Fix null reload token for ConfigurationProvider

### LINKED ISSUE #35996: Exception thrown if IConfigurationProvider.GetReloadToken() returns null
### Description

The summary for `IConfigurationProvider.GetReloadToken()` states:
`Returns a change token if this provider supports change tracking, null otherwise.`
However, if an implementation actually returns 'null', an exception is thrown from `ConfigurationRoot` constructor.

### Steps to reproduce the behavior:
1. Write your own `IConfigurationProvider` implementation
2. Make sure that the `GetReloadToken()` method returns `null`
3. When calling the `IConfigurationBuilder.Build()` method, a `System.NullReferenceException` exception is thrown

### Additional context
Here is the stack trace from my code:
```
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at DeviceServerTransfer.Program.CreateWebHostBuilder(String[] args) in C:\Dev\DotNet\Server\DeviceServerTransfer\DeviceServerTransfer\Program.cs:line 34
   at DeviceServerTransfer.Program.Main(String[] args) in C:\Dev\DotNet\Server\DeviceServerTransfer\DeviceServerTransfer\Program.cs:line 29
```

### LINKED ISSUE #36393: ConfigurationBuilder.Build throws NullReferenceException
I created an implementation of `IConfigurationProvider`, of which `GetReloadToken` method returns null. After adding its corresponding `IConfiguraionSource` into `ConfigurationBuilder` then called `Build` method, a `NullReferenceException` was thrown. Below are the implementation of `IConfigurationProvider` and `IConfigurationSource`:
```csharp
class MyConfigProvider : IConfigurationProvider 
{
   ...
   public void Load() {  ...   } 

   public IChangeToken GetReloadToken() => null;
   ...
}

class MyConfigSource : IConfigurationSource
{
   ...
   public IConfigurationProvider Build(IConfigurationBuilder builder)
      => new MyConfigProvider( ... );
   ...
}
```
To use these implementations: 
```csharp 
var builder = new ConfigurationBuilder();
builder.Add(new MyConfigSource())
var config = builder.Build(); // NullReference thrown here
```
The reason of this bug is that in ConfigurationRoot's constructor, it does not validate the return of `GetReloadToken` before passing it to `ChangeToken.OnChange` method.
```csharp
_providers = providers;
foreach (var p in providers)
{
   p.Load();
   ChangeToken.OnChange(() => p.GetReloadToken(), () => RaiseChanged());
}
```

### PR DESCRIPTION
**Pull request by wzchua**
Fixes #35996 (and fixes #36393)

I'm not sure if this is the best place to do the null check. Or if we want to check earlier.

### CODE REVIEW

File: src/libraries/Microsoft.Extensions.Configuration/tests/ConfigurationTest.cs [hunk 1]
```diff
@@ -889,5 +889,28 @@ public void NullSectionDoesNotExist()
...
+        {
+            // Arrange
+            var builder = new ConfigurationBuilder();
+            builder.Add(new NullReloadTokenConfigSource());
+
+            // Act
+            var config = builder.Build();
+
+            // Assert
+        }
```
Comment (eerhardt) [inline src/libraries/Microsoft.Extensions.Configuration/tests/ConfigurationTest.cs:914]: Can we at least assert that `Assert.IsNotNull(config)`?

**Review by eerhardt — APPROVED** [review]
Looks good to me. Thanks for the contribution.

File: src/libraries/Microsoft.Extensions.Configuration/tests/ConfigurationTest.cs [hunk 2]
```diff
@@ -889,5 +889,28 @@ public void NullSectionDoesNotExist()
             // Assert
             Assert.False(sectionExists);
         }
+
+        internal class NullReloadTokenConfigSource : IConfigurationSource, IConfigurationProvider
+        {
+            public IEnumerable<string> GetChildKeys(IEnumerable<string> earlierKeys, string parentPath) => throw new NotImplementedException();
+            public Primitives.IChangeToken GetReloadToken() => null;
```
Comment (maryamariyan) [inline src/libraries/Microsoft.Extensions.Configuration/tests/ConfigurationTest.cs:896]: Just a note for review, this PR is making sure we don't throw NRE when GetReloadToken is null.

Because otherwise as explained by @davidfowl in https://github.com/dotnet/runtime/issues/36393#issuecomment-531486938, rather than returning null in NullReloadTokenConfigSource in ConfigurationTest

```
public Primitives.IChangeToken GetReloadToken() => null;
```

If NullReloadTokenConfigSource.GetReloadToken() returned [NullChangeToken.Singleton](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.nullchangetoken.singleton?view=aspnetcore-2.2#Microsoft_Extensions_FileProviders_NullChangeToken_Singleton), then there would be no problem to solve.

**Review by maryamariyan — APPROVED** [review]

File: src/libraries/Microsoft.Extensions.Configuration/tests/ConfigurationTest.cs (hunk 2 above)
Comment (wzchua) [reply src/libraries/Microsoft.Extensions.Configuration/tests/ConfigurationTest.cs:896]: Issue #35996 mentioned that the docs suggest returning null. https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationprovider.getreloadtoken?view=dotnet-plat-ext-5.0

File: src/libraries/Microsoft.Extensions.Configuration/tests/ConfigurationTest.cs (hunk 1 above)
Comment (wzchua) [reply src/libraries/Microsoft.Extensions.Configuration/tests/ConfigurationTest.cs:915]: Done
