### PR TITLE
JIT: Fix asserts in fgSplitBlockAfterStatement and fgCheckStmtAfterTailCall (GDV-related)

### LINKED ISSUE #52270: JIT: Assertion failed 'retExpr->gtOper == GT_RETURN' in morph.cpp:19382
Looks similar to https://github.com/dotnet/runtime/issues/50492 (also GDV related), now in `fgCheckStmtAfterTailCall`

Reproduces with `DOTNET_TieredPGO=1` (but not if I also specify `DOTNET_JitEnableGuardedDevirtualization=0`)

Console app: (with `<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.10.0-1.final" />`)
https://gist.github.com/EgorBo/8b2bde996d7093e3b48ae026805eabc7

From a quick glance - same issue with unexpected statements after a tail-call candidate.

/cc @AndyAyersMS

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/52270
There are two issues I found with this repro: https://gist.github.com/EgorBo/8b2bde996d7093e3b48ae026805eabc7

1) Run with:
```
DOTNET_TieredPGO=1
```
It'll hit an assert of an unexpected `NOP` node in `fgCheckStmtAfterTailCall` (my fix is similar to https://github.com/dotnet/runtime/pull/51903)

2) Run with:
```
DOTNET_TieredPGO=1
DOTNET_TC_QuickJitForLoops=1
DOTNET_JitEnableGuardedDevirtualization=1
DOTNET_ReadyToRun=0
DOTNET_ZapDisable=1
```
it will hit an assert in a method with 250 basic-blocks while attempting to split a basic-block with empty preds (it belongs to a `GT_SWITCH`) while `fgComputePredsDone` is `false`.

/cc @dotnet/jit-contrib

### CODE REVIEW

File: src/coreclr/jit/fgflow.cpp [hunk 1]
```diff
@@ -279,8 +279,14 @@ flowList* Compiler::fgRemoveRefPred(BasicBlock* block, BasicBlock* blockPred)
     noway_assert(block != nullptr);
     noway_assert(blockPred != nullptr);
 
-    noway_assert(block->countOfInEdges() > 0);
-    block->bbRefs--;
+    if (block->countOfInEdges() > 0)
```
Comment (AndyAyersMS) [inline src/coreclr/jit/fgflow.cpp:282]: Maybe you should reorder this bit with the stuff that follows, something like
```c++
if (!fgComputePredsDone) return;

assert(block->countOfInEdges()> 0);
block->bbRefs--;
```

Comment (BruceForstall) [inline src/coreclr/jit/fgflow.cpp:282]: I don't understand under what conditions this function will be called and have bbRefs of zero. Maybe the caller in this case should do the check?

You're changing the invariants of this function, so you need to rewrite the header comment to match.

**Review by BruceForstall — CHANGES_REQUESTED** [review]

File: src/coreclr/jit/fgflow.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/fgflow.cpp:282]: Good point.

Likely there is some pred list updating being done in a caller that should be guarded by `fgComputePredsDone`.

**Comment by AndyAyersMS** [comment]
Changes look ok to me now.

Looks like one of the new tests is still missing a using, or the set of assemblies available for us to use in tests is too limited.

File: src/coreclr/jit/fgflow.cpp [hunk 2]
```diff
@@ -291,6 +288,9 @@ flowList* Compiler::fgRemoveRefPred(BasicBlock* block, BasicBlock* blockPred)
         return nullptr;
     }
 
+    assert(block->countOfInEdges() > 0);
```
Comment (BruceForstall) [inline src/coreclr/jit/fgflow.cpp:291]: The header comment specifically states:
```
//    -- block->bbRefs is adjusted even if preds haven't been computed. If preds haven't been computed,
//       the preds themselves aren't touched.
```

This matches the behavior of fgAddRefPreds, but here is no longer true.

Are there any diffs due to this?

If we really shouldn't be updating bbRefs beforehand checking fgComputePredsDone, then it seems like we need to have the same behavior in fgAddRefPred.

But I'd like to understand why that behavior exists in the first place before changing it.

File: src/tests/JIT/opt/Devirtualization/AnalyzeCsFile_Github_52270.cs [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+using Microsoft.CodeAnalysis.CSharp;
+using Microsoft.CodeAnalysis.CSharp.Syntax;
+using Microsoft.CodeAnalysis.Text;
+
+public static class Program
+{
+    public static async Task<int> Main()
+    {
+        // Make sure it doesn't assert, see https://github.com/dotnet/runtime/issues/52270
+        for (int i = 0; i < 100; i++)
```
Comment (BruceForstall) [inline src/tests/JIT/opt/Devirtualization/AnalyzeCsFile_Github_52270.cs:13]: This test looks very expensive. How long does it take to run? How long in minopts on Linux arm32?

**Review by BruceForstall — CHANGES_REQUESTED** [review]

File: src/coreclr/jit/fgflow.cpp (hunk 2 above)
Comment (EgorBo) [reply src/coreclr/jit/fgflow.cpp:291]: I'm trying to investigate it now, but the only method I am able to catch it is quite huge 😢

File: src/tests/JIT/opt/Devirtualization/AnalyzeCsFile_Github_52270.cs (hunk 3 above)
Comment (EgorBo) [reply src/tests/JIT/opt/Devirtualization/AnalyzeCsFile_Github_52270.cs:13]: Pretty long, will remove it

File: src/coreclr/jit/fgflow.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/fgflow.cpp:291]: I believe there are a number of early phases in the jit that don't keep accurate ref counts. And I also don't think there is anything that depends on them being accurate (for correctness, anyways). You may find you can fix the place that's leading to your current assert, but I suspect there will be more.

So I'd suggest looking at the logic for `fgSplitBlockAfterStmt` or what ever is up-stack when the assert fires, and perhaps adding a bypass if pred lists haven't been maintained.

Over time we'll move the building of pred lists earlier and this will all get sorted out.

**Review by BruceForstall — APPROVED** [review]
