### PR TITLE
Ensure that folding of unary mask operations doesn't modify the tracked op2

### LINKED ISSUE #117378: JIT: Assertion failed 'unreached' during 'Morph - Global'
```csharp
// Generated by Fuzzlyn v3.2 on 2025-07-06 14:49:40
// Run on X64 Windows
// Seed: 14677918720271330548-vectort,vector128,vector256,vector512,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86avx512fx64,x86avx512vbmi,x86avx512vbmivl,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86gfni,x86gfniv256,x86gfniv512,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86pclmulqdqv256,x86pclmulqdqv512,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 322.4 KiB to 0.6 KiB in 00:04:45
// Hits JIT assert for Release:
// Assertion failed 'unreached' in 'Program:M0()' during 'Morph - Global' (IL size 43; hash 0xaf50ff37; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\simd.h Line: 1142
// 
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static Vector256<int> s_1;
    public static void Main()
    {
        M0();
    }

    public static void M0()
    {
        var vr2 = Vector256.Create<int>(0);
        var vr3 = Vector256.Create<int>(1);
        var vr1 = Avx512F.VL.CompareNotEqual(vr2, vr3);
        var vr4 = Vector256.Create<int>(0);
        var vr0 = Avx2.AndNot(vr1, vr4);
        s_1 = Avx512CD.VL.LeadingZeroCount(vr0);
    }
}
```

Also hit by Antigen. cc @dotnet/jit-contrib.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #117378

### CODE REVIEW

File: src/coreclr/jit/gentree.cpp [hunk 1]
```diff
@@ -32262,35 +32262,29 @@ GenTree* Compiler::gtFoldExprHWIntrinsic(GenTreeHWIntrinsic* tree)
         // fold the unnecessary back and forth conversions away where possible.
 
         genTreeOps effectiveOper = oper;
-        GenTree*   actualOp2     = op2;
-
-        if (oper == GT_NOT)
-        {
-            assert(op2 == nullptr);
-            op2 = op1;
-        }
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.cpp:32271]: This code used to live in a different location and it doing the tracking like this wasn't problematic there. In the new location, however, we need to ensure op2 isn't modified since code runs after and might use the value if the attempted folding here fails.

The new logic just does the relevant null checks and avoids modifying op2 altogether to fix the issue.

File: src/tests/JIT/Regression/JitBlue/Runtime_117377/Runtime_117377.cs [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+        (new S1()).M4();
+    }
+
+    struct S1
+    {
+        public byte F4;
+
+        public byte M4()
+        {
+            var vr3 = Vector256.CreateScalar(0U);
```
Comment (amanasifkhalid) [inline src/tests/JIT/Regression/JitBlue/Runtime_117377/Runtime_117377.cs]: Do you need an ISA check here?

Comment (tannergooding) [reply src/tests/JIT/Regression/JitBlue/Runtime_117377/Runtime_117377.cs]: Yes indeed. I always seem to forget to add it for the Fuzzlyn regression tests in the first push.

**Review by amanasifkhalid — APPROVED** [review]
LGTM, thanks!
