### PR TITLE
Fix ELT profiler tests

### LINKED ISSUE #44055: Test failure: profiler/elt/slowpatheltenter/slowpatheltenter.sh
failed in job: [runtime-coreclr crossgen2 20201028.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=869845&view=ms.vss-test-web.build-test-results-tab&runId=27834204&resultId=100082&paneView=debug)

R2R-CG2 OSX x64 Checked @ OSX.1013.Amd64.Open

Error message
~~~
/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/slowpatheltenter.sh: line 244: -r:/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/IL/.dll: No such file or directory
rm: /private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/TestLibrary.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/profiler_common.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/slowpathcommon.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/slowpatheltenter.dll.rsp: No such file or directory
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in /__w/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 138
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in /__w/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 92
   at SlowPathELTTests.SlowPathELTEnter.Main(String[] args) in /__w/1/s/src/tests/profiler/elt/slowpatheltenter.cs:line 29
MachO coredumps are not supported. To enable ELF coredumps on MacOS, set the COMPlus_DbgEnableElfDumpOnMacOS environment variable to 1.
/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/slowpatheltenter.sh: line 364: 73918 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/Reports/profiler.elt/slowpatheltenter/slowpatheltenter.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/IL/TestLibrary.dll
Response file: /private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/TestLibrary.dll.rsp
/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/IL/TestLibrary.dll
-o:/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/TestLibrary.dll
-r:/tmp/helix/working/A1660908/p/System..dll
-r:/tmp/helix/working/A1660908/p/Microsoft..dll
-r:/tmp/helix/working/A1660908/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /tmp/helix/working/A1660908/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/TestLibrary.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/TestLibrary.dll
/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/IL/profiler_common.dll
Response file: /private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/profiler_common.dll.rsp
/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/IL/profiler_common.dll
-o:/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/profiler_common.dll
-r:/tmp/helix/working/A1660908/p/System..dll
-r:/tmp/helix/working/A1660908/p/Microsoft.*.dll
-r:/tmp/helix/working/A1660908/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /tmp/helix/working/A1660908/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/profiler_common.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/A1660908/w/A5EF08BD/e/profiler/elt/slowpatheltenter/profiler_common.dll
/private/tmp/helix/work


Stack trace
   at profiler_elt._slowpatheltenter_slowpatheltenter_._slowpatheltenter_slowpatheltenter_sh() in /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/profiler.elt/profiler.elt.XUnitWrapper.cs:line 153
~~~

Runfo Tracking Issue: [Test failure: profiler/elt/slowpatheltenter/slowpatheltenter.sh](https://runfo.azurewebsites.net/tracking/issue/93)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[877759](https://dev.azure.com/dnceng/public/_build/results?buildId=877759)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44322](https://github.com/dotnet/runtime/pull/44322)|CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44322-merge-310d6190067a4c5f84/profiler.elt/console.b8bb895c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T11%2525253A11%2525253A07Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dc4KOkA9uhSKsvlSsSue6joNbqMvccro99ZebzomzeZU%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44322-merge-310d6190067a4c5f84/profiler.elt/core.1001.67?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T11%2525253A11%2525253A07Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dc4KOkA9uhSKsvlSsSue6joNbqMvccro99ZebzomzeZU%2525253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44322-merge-310d6190067a4c5f84/profiler.elt/c7b08173-276d-4a1f-b6f4-732bc4bcbb74.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T11%2525253A11%2525253A07Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dc4KOkA9uhSKsvlSsSue6joNbqMvccro99ZebzomzeZU%2525253D)|
|[877610](https://dev.azure.com/dnceng/public/_build/results?buildId=877610)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|CoreCLR Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-89f3d21b694f4562be/profiler.elt/console.5137d074.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T06%2525253A03%2525253A06Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DsKtTLqZitABhSZZTfFJrgr7h8f7g9e%2525252BkneJ5S94fhJQ%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-89f3d21b694f4562be/profiler.elt/core.1001.149?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T06%2525253A03%2525253A06Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DsKtTLqZitABhSZZTfFJrgr7h8f7g9e%2525252BkneJ5S94fhJQ%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-89f3d21b694f4562be/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T06%2525253A03%2525253A06Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DsKtTLqZitABhSZZTfFJrgr7h8f7g9e%2525252BkneJ5S94fhJQ%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-89f3d21b694f4562be/profiler.elt/9ea96856-c0a5-42ce-9522-c54f39514d05.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T06%2525253A03%2525253A06Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DsKtTLqZitABhSZZTfFJrgr7h8f7g9e%2525252BkneJ5S94fhJQ%2525253D)|
|[877495](https://dev.azure.com/dnceng/public/_build/results?buildId=877495)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 43921](https://github.com/dotnet/runtime/pull/43921)|CoreCLR Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43921-merge-a804d4ecabab46cbba/profiler.elt/console.8fa4638f.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T02%2525253A56%2525253A56Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DzhogHw844uqyjmh%2525252BujVLj5QXcMoeiCM1dh2f6ImyF7U%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43921-merge-a804d4ecabab46cbba/profiler.elt/core.1001.150?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T02%2525253A56%2525253A56Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DzhogHw844uqyjmh%2525252BujVLj5QXcMoeiCM1dh2f6ImyF7U%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43921-merge-a804d4ecabab46cbba/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T02%2525253A56%2525253A56Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DzhogHw844uqyjmh%2525252BujVLj5QXcMoeiCM1dh2f6ImyF7U%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43921-merge-a804d4ecabab46cbba/profiler.elt/d63a4c16-b4c7-464c-b8c8-bc63b3b34008.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-26T02%2525253A56%2525253A56Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DzhogHw844uqyjmh%2525252BujVLj5QXcMoeiCM1dh2f6ImyF7U%2525253D)|
|[877126](https://dev.azure.com/dnceng/public/_build/results?buildId=877126)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44266](https://github.com/dotnet/runtime/pull/44266)|CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44266-merge-2a77237bf37a47a8b1/profiler.elt/console.36f10818.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-25T22%2525253A44%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DresI%2525252BUcuYsk546fw3aZeLC6w2dHE6hfF66S2DitXLMI%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44266-merge-2a77237bf37a47a8b1/profiler.elt/core.1001.44?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-25T22%2525253A44%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DresI%2525252BUcuYsk546fw3aZeLC6w2dHE6hfF66S2DitXLMI%2525253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44266-merge-2a77237bf37a47a8b1/profiler.elt/9db58689-d3f1-40f9-ae1b-6cd686360364.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-25T22%2525253A44%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DresI%2525252BUcuYsk546fw3aZeLC6w2dHE6hfF66S2DitXLMI%2525253D)|
|[875973](https://dev.azure.com/dnceng/public/_build/results?buildId=875973)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44215](https://github.com/dotnet/runtime/pull/44215)|CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44215-merge-549654b19f944b6fa0/profiler.elt/console.c9fccea1.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-25T01%2525253A01%2525253A52Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DWeXmNa9Lahgpax3cgRGEjTUUfcsA1sFnGJWkyY0oiWE%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44215-merge-549654b19f944b6fa0/profiler.elt/core.1001.41?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-25T01%2525253A01%2525253A52Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DWeXmNa9Lahgpax3cgRGEjTUUfcsA1sFnGJWkyY0oiWE%2525253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44215-merge-549654b19f944b6fa0/profiler.elt/c07a5ad8-cf46-4757-b8c8-51dc87df90b5.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-25T01%2525253A01%2525253A52Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DWeXmNa9Lahgpax3cgRGEjTUUfcsA1sFnGJWkyY0oiWE%2525253D)|
|[875800](https://dev.azure.com/dnceng/public/_build/results?buildId=875800)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 43965](https://github.com/dotnet/runtime/pull/43965)|CoreCLR Linux x64 Checked @ Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43965-merge-eb7bd5e3ec91478f8e/profiler.elt/console.6d62a394.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T22%2525253A45%2525253A13Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DS3q15nC5Q8lgHfpcRAStJqId%2525252BR0Bnqk3vksKMyp8tZE%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43965-merge-eb7bd5e3ec91478f8e/profiler.elt/core.1000.17149?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T22%2525253A45%2525253A13Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DS3q15nC5Q8lgHfpcRAStJqId%2525252BR0Bnqk3vksKMyp8tZE%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43965-merge-eb7bd5e3ec91478f8e/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T22%2525253A45%2525253A13Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DS3q15nC5Q8lgHfpcRAStJqId%2525252BR0Bnqk3vksKMyp8tZE%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43965-merge-eb7bd5e3ec91478f8e/profiler.elt/68ea1bcb-5d1b-4d28-b19c-398e5ae9b2cb.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T22%2525253A45%2525253A13Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DS3q15nC5Q8lgHfpcRAStJqId%2525252BR0Bnqk3vksKMyp8tZE%2525253D)|
|[875068](https://dev.azure.com/dnceng/public/_build/results?buildId=875068)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 43735](https://github.com/dotnet/runtime/pull/43735)|CoreCLR Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43735-merge-bd841a83924248cd84/profiler.elt/console.9c51911d.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T03%2525253A34%2525253A07Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D0vsFLLw1EHAoJphLOCkivua3o%2525252BsbrLzI9LIXj24Lg%2525252BA%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43735-merge-bd841a83924248cd84/profiler.elt/core.1001.175?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T03%2525253A34%2525253A07Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D0vsFLLw1EHAoJphLOCkivua3o%2525252BsbrLzI9LIXj24Lg%2525252BA%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43735-merge-bd841a83924248cd84/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T03%2525253A34%2525253A07Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D0vsFLLw1EHAoJphLOCkivua3o%2525252BsbrLzI9LIXj24Lg%2525252BA%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43735-merge-bd841a83924248cd84/profiler.elt/9944452b-0c85-4c4f-aecd-6cda427b89b6.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-24T03%2525253A34%2525253A07Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D0vsFLLw1EHAoJphLOCkivua3o%2525252BsbrLzI9LIXj24Lg%2525252BA%2525253D)|
|[874768](https://dev.azure.com/dnceng/public/_build/results?buildId=874768)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 43811](https://github.com/dotnet/runtime/pull/43811)|CoreCLR OSX x64 Checked @ OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43811-merge-cc8528c001874d8387/profiler.elt/console.edd82071.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T23%2525253A36%2525253A57Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D3DyNg0bKNa72yR6PsX2UCc80f5kj%2525252Bi0TaEnQZ9GMuw4%2525253D)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43811-merge-cc8528c001874d8387/profiler.elt/core.72818?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T23%2525253A36%2525253A57Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D3DyNg0bKNa72yR6PsX2UCc80f5kj%2525252Bi0TaEnQZ9GMuw4%2525253D)|[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43811-merge-cc8528c001874d8387/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T23%2525253A36%2525253A57Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D3DyNg0bKNa72yR6PsX2UCc80f5kj%2525252Bi0TaEnQZ9GMuw4%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43811-merge-cc8528c001874d8387/profiler.elt/7966c7ce-d478-4324-84f6-291bd9cb2646.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T23%2525253A36%2525253A57Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253D3DyNg0bKNa72yR6PsX2UCc80f5kj%2525252Bi0TaEnQZ9GMuw4%2525253D)|
|[874435](https://dev.azure.com/dnceng/public/_build/results?buildId=874435)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44209](https://github.com/dotnet/runtime/pull/44209)|CoreCLR Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44209-merge-4bb1a3eebd4c4cacac/profiler.elt/console.a9e2a3b4.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T19%2525253A56%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVPLUKvyKPyTDYI8EgApYhyvPJ3LzLkruYTk5C1lsqfs%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44209-merge-4bb1a3eebd4c4cacac/profiler.elt/core.1001.149?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T19%2525253A56%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVPLUKvyKPyTDYI8EgApYhyvPJ3LzLkruYTk5C1lsqfs%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44209-merge-4bb1a3eebd4c4cacac/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T19%2525253A56%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVPLUKvyKPyTDYI8EgApYhyvPJ3LzLkruYTk5C1lsqfs%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44209-merge-4bb1a3eebd4c4cacac/profiler.elt/34e98384-3acd-4821-b76b-c228c71ce48f.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T19%2525253A56%2525253A30Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DVPLUKvyKPyTDYI8EgApYhyvPJ3LzLkruYTk5C1lsqfs%2525253D)|
|[874284](https://dev.azure.com/dnceng/public/_build/results?buildId=874284)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|CoreCLR OSX x64 Checked @ OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-5229acb0d971470499/profiler.elt/console.d19533bb.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T17%2525253A06%2525253A16Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DoOHORqlyEBUZggk3XQ4eCB6e9uvYq%2525252BTqEFwu1DRYBtc%2525253D)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-5229acb0d971470499/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T17%2525253A06%2525253A16Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DoOHORqlyEBUZggk3XQ4eCB6e9uvYq%2525252BTqEFwu1DRYBtc%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-5229acb0d971470499/profiler.elt/47c28884-3991-4dee-9917-0b86a9bc2b84.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T17%2525253A06%2525253A16Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DoOHORqlyEBUZggk3XQ4eCB6e9uvYq%2525252BTqEFwu1DRYBtc%2525253D)|
|[874058](https://dev.azure.com/dnceng/public/_build/results?buildId=874058)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 43668](https://github.com/dotnet/runtime/pull/43668)|CoreCLR Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43668-merge-38c598b00ffa4faeac/profiler.elt/console.369c8e9c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T12%2525253A37%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DpcTuftI3cImnpG6VZTDOmpZuQTLI5A2U5zt0eCUvzrA%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43668-merge-38c598b00ffa4faeac/profiler.elt/core.1001.149?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T12%2525253A37%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DpcTuftI3cImnpG6VZTDOmpZuQTLI5A2U5zt0eCUvzrA%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43668-merge-38c598b00ffa4faeac/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T12%2525253A37%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DpcTuftI3cImnpG6VZTDOmpZuQTLI5A2U5zt0eCUvzrA%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43668-merge-38c598b00ffa4faeac/profiler.elt/143bc9d1-f0ba-4b68-a27b-27739019dc35.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T12%2525253A37%2525253A04Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DpcTuftI3cImnpG6VZTDOmpZuQTLI5A2U5zt0eCUvzrA%2525253D)|
|[873788](https://dev.azure.com/dnceng/public/_build/results?buildId=873788)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44172](https://github.com/dotnet/runtime/pull/44172)|CoreCLR OSX x64 Checked @ OSX.1013.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44172-merge-07dec9460d62479f99/profiler.elt/console.4d0afdaa.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T12%2525253A28%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Da4uxEAXQXBdhpLN6p13Izf1E0klLDv5255Deeyt1nmo%2525253D)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44172-merge-07dec9460d62479f99/profiler.elt/core.1857?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T12%2525253A28%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Da4uxEAXQXBdhpLN6p13Izf1E0klLDv5255Deeyt1nmo%2525253D)|[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44172-merge-07dec9460d62479f99/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T12%2525253A28%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Da4uxEAXQXBdhpLN6p13Izf1E0klLDv5255Deeyt1nmo%2525253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44172-merge-07dec9460d62479f99/profiler.elt/a663b7b9-f558-4208-a0cc-6ae34beccaac.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-23T12%2525253A28%2525253A18Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Da4uxEAXQXBdhpLN6p13Izf1E0klLDv5255Deeyt1nmo%2525253D)|
|[873574](https://dev.azure.com/dnceng/public/_build/results?buildId=873574)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44162](https://github.com/dotnet/runtime/pull/44162)|CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44162-merge-6cf35089acb740fc81/profiler.elt/console.b5a4abe1.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T22%2525253A41%2525253A46Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dmu%2525252F0l2tK7aE%2525252FBHd1SXRExSNfxWtLkqlV9Mr2yI31Qxg%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44162-merge-6cf35089acb740fc81/profiler.elt/core.1001.43?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T22%2525253A41%2525253A46Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dmu%2525252F0l2tK7aE%2525252FBHd1SXRExSNfxWtLkqlV9Mr2yI31Qxg%2525253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44162-merge-6cf35089acb740fc81/profiler.elt/c750bf2b-68b1-4161-8380-3d3d28178d72.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T22%2525253A41%2525253A46Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dmu%2525252F0l2tK7aE%2525252FBHd1SXRExSNfxWtLkqlV9Mr2yI31Qxg%2525253D)|
|[873152](https://dev.azure.com/dnceng/public/_build/results?buildId=873152)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|CoreCLR Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-3e40bb39601741258d/profiler.elt/console.c537ecbb.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T16%2525253A21%2525253A19Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DN8T38uByKXsns2Ka%2525252B6Pb%2525252F3egTmQkfE%2525252FnOpxcr4DbWek%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-3e40bb39601741258d/profiler.elt/core.1001.150?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T16%2525253A21%2525253A19Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DN8T38uByKXsns2Ka%2525252B6Pb%2525252F3egTmQkfE%2525252FnOpxcr4DbWek%2525253D)|[test results](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-3e40bb39601741258d/profiler.elt/testResults.xml?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T16%2525253A21%2525253A19Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DN8T38uByKXsns2Ka%2525252B6Pb%2525252F3egTmQkfE%2525252FnOpxcr4DbWek%2525253D)|[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-3e40bb39601741258d/profiler.elt/13a020c3-09fe-4203-8a39-b26ca1a0d347.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T16%2525253A21%2525253A19Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DN8T38uByKXsns2Ka%2525252B6Pb%2525252F3egTmQkfE%2525252FnOpxcr4DbWek%2525253D)|
|[872776](https://dev.azure.com/dnceng/public/_build/results?buildId=872776)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44133](https://github.com/dotnet/runtime/pull/44133)|CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44133-merge-0666f47536394f909f/profiler.elt/console.2e6f1db5.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T03%2525253A49%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DYpcIqgbd5yFeOaVXTVvXSGAG33dHaVrvtdH502Y0c1M%2525253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44133-merge-0666f47536394f909f/profiler.elt/core.1001.70?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T03%2525253A49%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DYpcIqgbd5yFeOaVXTVvXSGAG33dHaVrvtdH502Y0c1M%2525253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44133-merge-0666f47536394f909f/profiler.elt/7a668c31-6a87-4b95-91be-9dfd47d6757c.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-11-22T03%2525253A49%2525253A03Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253DYpcIqgbd5yFeOaVXTVvXSGAG33dHaVrvtdH502Y0c1M%2525253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|4|15|15|

### PR DESCRIPTION
**Pull request by davmason**
Fixes #44055

Recently profiler/elt/slowpatheltenter/slowpatheltenter started failing. On investigation it was because a timer firing was triggering managed code to run as the runtime was shutting down, and we would occasionally try to use pCorProfilerInfo after it was set to NULL.

This PR add some synchronization so we bail on the ELT hooks once Shutdown is called. It also changes the output when a test fails, the previous wording was confusing because it implied PROFILER_TEST_PASSES in the output was the only thing necessary for a test to pass when we check the exit code of the process as well.

### CODE REVIEW

**Comment by stephentoub** [comment]
> Recently profiler/elt/slowpatheltenter/slowpatheltenter started failing

What changed?  You mention a timer firing; it wasn't before?

I'm asking because we saw some other diagnostic failures start frequently around the same time, e.g. https://github.com/dotnet/runtime/issues/44037, and I'm wondering if there might be a link.

File: src/tests/profiler/common/ProfilerTestRunner.cs [hunk 1]
```diff
@@ -83,17 +83,20 @@ public class ProfilerTestRunner
...
                     "text was not found in the output above.");
-                return process.ExitCode == 100 ? process.ExitCode : -1;
             }
+
+            if (process.ExitCode != 100)
+            {
+                LogTestFailure($"Profilee returned exit code {process.ExitCode} instead of expected exit code 100.");
+            }
+
+            return 100;
```
Comment (sdmaclea) [inline src/tests/profiler/common/ProfilerTestRunner.cs:99]: I think you said in an earlier PR that the exit code didn't matter for profiler tests.  It still would be nice to have a comment to that effect.

**Review by sdmaclea — APPROVED** [review]
LGTM

File: src/tests/profiler/common/ProfilerTestRunner.cs (hunk 1 above)
Comment (davmason) [reply src/tests/profiler/common/ProfilerTestRunner.cs:99]: I don't remember exactly what I said, but I think I was trying to say that the exit code doesn't matter for that particular test. We do check the exit code, it's just that a lot of profiler tests don't use it to indicate failure. Some of them do, however, and crashes will return a non 100 exit code.

**Comment by davmason** [comment]
> 
> 
> > Recently profiler/elt/slowpatheltenter/slowpatheltenter started failing
> 
> What changed? You mention a timer firing; it wasn't before?

I shouldn't have worded it so strongly. I was inferring something changed due to it only recently starting to fail, but have no proof. These tests register enter/leave hooks through the profiler APIs, and recently they started failing where after the profiler shut down and cleaned up resources some background thread would still be calling managed code and the test would AV trying to use pCorProfilerInfo, which is now null. 

When I debugged, it consistently hit in a managed timer callback but I never actually verified what code path was hitting it. For the purposes of this test the exact code that causes the failure is irrelevant, it has always been legal and possible for other threads to continue running during shutdown. This is one of those "I'm surprised this worked until now" moments.

I will take a look to see if there is an obvious change causing this, but I would be pretty surprised if this was related to the other failing tests you linked.

**Comment by davmason** [comment]
It fails before it gets to anything that actually tells me what timer is firing:

```
(lldb) clrstack
OS Thread Id: 0x1abfd9 (10)
        Child SP               IP Call Site
00007FFFF40624E0 00007ffff4684bfa [HelperMethodFrame: 00007ffff40624e0]
00007FFFF4062800 00007FFF7DFDD6A9 System.Threading.PortableThreadPool+GateThread.EnsureRunning(System.Threading.PortableThreadPool)
00007FFFF4062830 00007FFF7DFD57D9 System.Threading.PortableThreadPool.RequestWorker()
00007FFFF4062860 00007FFF7DFD121E System.Threading.ThreadPool.RequestWorkerThread()
00007FFFF40628F0 00007FFF7DFD06D6 System.Threading.ThreadPoolWorkQueue.EnqueueTimeSensitiveWorkItem(System.Threading.IThreadPoolWorkItem)
00007FFFF4062920 00007FFF7DFD05F5 System.Threading.ThreadPool.UnsafeQueueTimeSensitiveWorkItemInternal(System.Threading.IThreadPoolWorkItem)
00007FFFF4062950 00007FFF7DFBC850 System.Threading.ThreadPool.UnsafeQueueUnmanagedWorkItem(IntPtr, IntPtr)
```

But, although it mainly fails in the timer path it also randomly fails in other codepaths too. I don't know what changed but it's very unlikely that this is anything but a test bug.

File: src/tests/profiler/common/ProfilerTestRunner.cs (hunk 1 above)
Comment (sdmaclea) [reply src/tests/profiler/common/ProfilerTestRunner.cs:99]: I guess I just wanted to make it clear to someone other than you that `return 100;` can happen even though the test failed.  I just feels confusing to me.  If we hadn't talked about it, I would have asked again.

Comment (davmason) [reply src/tests/profiler/common/ProfilerTestRunner.cs:104]: Sure, I added a comment

Comment (noahfalk) [reply src/tests/profiler/common/ProfilerTestRunner.cs:104]: I agree that logging a failure message and then returning 100 feels counter intuitive. If the exit code matters I was expecting there would be some conditional logic or if it doesn't matter then perhaps we should return 0?

**Comment by davmason** [comment]
It occurs to me that the reason we're seeing managed code executing at times when it wasn't before is the portable thread pool work that @kouvel enabled recently. Earlier I said I didn't know what was causing the timer, but I think the new thread pool implementation itself is causing it.

**Review by noahfalk — COMMENTED** [review]
LGTM

File: src/tests/profiler/common/ProfilerTestRunner.cs (hunk 1 above)
Comment (davmason) [reply src/tests/profiler/common/ProfilerTestRunner.cs:104]: I misunderstood what Steve was saying. As Noah points out in the edit above LogTestFailure intentionally throws an unhandled exception to fail the test. I can see how that is unclear to others though, since it just says log in the name

Comment (sdmaclea) [reply src/tests/profiler/common/ProfilerTestRunner.cs:104]: Precisely **unclear**

Comment (davmason) [reply src/tests/profiler/common/ProfilerTestRunner.cs:104]: I just changed it from LogTestFailure to FailFastWithMessage so hopefully its more clear just from the name

**Comment by kouvel** [comment]
> It occurs to me that the reason we're seeing managed code executing at times when it wasn't before is the portable thread pool work that @kouvel enabled recently. Earlier I said I didn't know what was causing the timer, but I think the new thread pool implementation itself is causing it.

Tiered compilation's background work currently uses the thread pool, a timer is used to get a thread pool thread and some new managed code is triggered.

File: src/tests/profiler/common/ProfilerTestRunner.cs (hunk 1 above)
Comment (sdmaclea) [reply src/tests/profiler/common/ProfilerTestRunner.cs:104]: Thanks
