### PR TITLE
Fix value numbering of HWI loads

### LINKED ISSUE #63499: VN does not number some HWI loads properly
Reproduction:
```cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

unsafe
{
    var dbls = stackalloc double[] { 1, 1 };
    Console.WriteLine(Problem(dbls));
}

[MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
static unsafe bool Problem(double* a)
{
    const double Mask = -0.0;

    var v1 = Avx.MaskLoad(a, Vector128.Create(0, Mask));
    if (v1.GetElement(0) == 0)
    {
        var v2 = Avx.MaskLoad(a, Vector128.Create(Mask, 0));
        if (v2.GetElement(0) == 0)
        {
            return true;
        }
    }

    return false;
}
```
Expected result: `false`.
Actual result: `true`.

Cause: in the below VN code we only encode the value of the address operand:

https://github.com/dotnet/runtime/blob/a71f261010ace01eaceaeef2a70bf2f5807a028b/src/coreclr/jit/valuenum.cpp#L9601-L9622

We need to encode the value of the second parameter (if it is present) as well.

FYI @tannergooding

### PR DESCRIPTION
**Pull request by SingleAccretion**
Take all operands into account and give "new, unique" exception set VNs to intrinsics we do not model properly.

Fixes #63499.

[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1819806&view=ms.vss-build-web.run-extensions-tab) as expected.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib, @tannergooding

File: src/coreclr/jit/valuenum.cpp [hunk 1]
```diff
@@ -9329,143 +9342,169 @@ void Compiler::fgValueNumberSimd(GenTreeSIMD* tree)
...
-    // For safety/correctness we must mutate the global heap valuenumber
-    // for any HW intrinsic that performs a memory store operation
-    if (tree->OperIsMemoryStore())
-    {
-        fgMutateGcHeap(tree DEBUGARG("HWIntrinsic - MemoryStore"));
-    }
+    NamedIntrinsic intrinsicId   = tree->GetHWIntrinsicId();
+    GenTree*       addr          = nullptr;
+    const bool     isMemoryLoad  = tree->OperIsMemoryLoad(&addr);
+    const bool     isMemoryStore = tree->OperIsMemoryStore(&addr);
```
Comment (tannergooding) [inline src/coreclr/jit/valuenum.cpp:9350]: This seems like bad/confusing behavior as its relying on `OperIsMemoryStore` not mutating `addr` on `false`.

Comment (tannergooding) [reply src/coreclr/jit/valuenum.cpp:9350]: I understand that's fine for how it currently is, but it would be good if we made this more explicit and ensure it doesn't look like a potential bug if you're just glancing through the code.

Comment (SingleAccretion) [reply src/coreclr/jit/valuenum.cpp:9350]: Heh, it is actually deliberate. I agree it is not great though, will change it to the original of ``isMemoryStore = !isMemoryLoad && tree->OperIsMemoryStore(&addr);``.

**Review by jakobbotsch — APPROVED** [review]
Looks great to me!
