### PR TITLE
[Crossgen2] Add DelayLoadMethodCallThunks table, fix stack walks containing thunks

### LINKED ISSUE #38482: Test failure: readytorun\crossgen2\crossgen2smoke\crossgen2smoke.cmd
https://dev.azure.com/dnceng/public/_build/results?buildId=705744&view=ms.vss-test-web.build-test-results-tab&runId=21861154&resultId=109360&paneView=debug

The above link is for a failure in a manually scheduled run of gcstress0x3-gcstress0xc pipeline for a PR but I was able to get a local repro on master @ f1bf0defd31da8f60dc33a63071a8e00b036e300

The failure is non-deterministic, it took me 7 tries to get a repro.

Windows x64

```
set COMPlus_TieredCompilation=0
set COMPlus_GCStress=0xC
```

```
readytorun\crossgen2\crossgen2smoke\crossgen2smoke.cmd [FAIL]
      
      Assert failure(PID 656 [0x00000290], Thread: 3904 [0x0f40]): Consistency check failed: AV in clr at this callstack:
      ------
      CORECLR! memcmp + 0x12 (0x00007ffc`56c51532)
      CORECLR! Thread::VirtualUnwindCallFrame + 0x340 (0x00007ffc`56568608)
      CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x1C3 (0x00007ffc`568a8bdb)
      CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x72 (0x00007ffc`5656323e)
      CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x178 (0x00007ffc`565675c8)
      CORECLR! StackFrameIterator::Init + 0x1E5 (0x00007ffc`56565659)
      CORECLR! Thread::StackWalkFramesEx + 0x12E (0x00007ffc`56567fae)
      CORECLR! Thread::HandledJITCase + 0x234 (0x00007ffc`565b6eec)
      CORECLR! ThreadSuspend::SuspendRuntime + 0x421 (0x00007ffc`565bc349)
      CORECLR! ThreadSuspend::SuspendEE + 0x29B (0x00007ffc`565bbc4f)
      CORECLR! GCToEEInterface::SuspendEE + 0x48 (0x00007ffc`56b96a98)
      CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x249 (0x00007ffc`56b13c35)
      CORECLR! WKS::GCHeap::StressHeap + 0x4CA (0x00007ffc`56b16c4a)
      CORECLR! Thread::PerformPreemptiveGC + 0x31F (0x00007ffc`565b8a17)
      CORECLR! Thread::RareEnablePreemptiveGC + 0x11E (0x00007ffc`565b91d6)
      CORECLR! Thread::EnablePreemptiveGC + 0xF7 (0x00007ffc`564b3423)
      CORECLR! GCHolderBase::PopInternal<1> + 0x13F (0x00007ffc`564b02c3)
      CORECLR! GCCoop::~GCCoop + 0x9 (0x00007ffc`564b1159)
      CORECLR! MscorlibBinder::TriggerGCUnderStress + 0x1A3 (0x00007ffc`565eecdb)
      -----
      .AV on tid=0xf40 (3904), cxr=000000FCC1974F40, exr=000000FCC1975430
      FAILED: false
      
      CORECLR! CHECK::Trigger + 0x2C9 (0x00007ffc`56467d65)
      CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2B2 (0x00007ffc`564c0306)
      CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x97 (0x00007ffc`564bfdc7)
      CORECLR! CLRVectoredExceptionHandler + 0x215 (0x00007ffc`564bfd0d)
      CORECLR! CLRVectoredExceptionHandlerShim + 0x1A0 (0x00007ffc`564c0580)
      NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffc`85a45ef0)
      NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffc`85a1fa7b)
      NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffc`85a8964a)
      CORECLR! memcmp + 0x12 (0x00007ffc`56c51532)
      CORECLR! Thread::VirtualUnwindCallFrame + 0x340 (0x00007ffc`56568608)
          File: F:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp Line: 7494
          Image: C:\h\w\B7160A3B\p\CoreRun.exe
      
      
      Return code:      1
```

### PR DESCRIPTION
**Pull request by nattress**
GC stress runs with Crossgen2 binaries frequently see AVs with stack-walk failures. This occurs when a delay load thunk is being executed as a stack-walk is performed. The runtime resolves any thunk address to the code info for the last managed method in the runtime functions table.

Fix the binary search algorithm in `NativeUnwindInfoLookupTable::LookupUnwindInfoForMethod` which doesn't correctly return -1 if the code address being searched for is larger than any present. This old bug was not hit because Crossgen emits stubs earlier in the image than managed code, whereas the two are reversed with Crossgen2.

Fix generation of the RuntimeFunctionsTable so that the terminating sentinel node is not treated as part of the table in the R2R header entry for the table. This was causing the sentinel node to be treated as its own runtime function by the runtime and could lead to reading beyond the table bounds in `NativeUnwindInfoLookupTable::LookupUnwindInfoForMethod`. The bug in the binary search of the table hid this bug until now.

Add the `DelayLoadMethodCallThunks` header entry. `DelayLoadMethodCallThunkNodeRange` is a placeholder node (not an `ObjectNode`) to provide a symbol to relocate against from the header. It represents the range of import thunks. Add support to the object writer for defining a range between two symbols in the same section. The relocation phase can then resolve the difference between the two symbols to determine the range size.

Fixes https://github.com/dotnet/runtime/issues/38482

cc @dotnet/crossgen-contrib

### CODE REVIEW

File: src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs [hunk 1]
```diff
@@ -162,6 +164,16 @@ public void EmitPortableExecutable()
                         nativeDebugDirectoryEntryNode = nddeNode;
                     }
 
+                    if (node is ImportThunk importThunkNode)
+                    {
+                        // All the import thunks are in a single contiguous run
+                        if (firstImportThunk == null)
```
Comment (davidwrighton) [inline src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:170]: Could you add a check to ensure that this is a contiguous run of imports nodes? This is the sort of thing that might break as we adjust sorting for improved memory layout, and I'd like to have the compiler checking for this.

**Review by davidwrighton — COMMENTED** [review]
If you could add the additional check I suggested, I consider this a great change.

File: src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/RuntimeFunctionsTableNode.cs [hunk 2]
```diff
@@ -103,12 +103,17 @@ public override ObjectData GetData(NodeFactory factory, bool relocsOnly = false)
...
+        /// the runtime in NativeUnwindInfoLookupTable::LookupUnwindInfoForMethod) so that it's not treated as
+        /// part of the table itself.
+        /// </summary>
+        public int TableSizeExcludingSentinel
         {
             get
             {
                 Debug.Assert(_tableSize >= 0);
-                return _tableSize;
+                return _tableSize - 4;
```
Comment (trylek) [inline src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/RuntimeFunctionsTableNode.cs:116]: Nit - it's kind of awkward that we need to duplicate this logic between this place and the section table emitter. Perhaps we might be able to shove some virtual method like <code>EndSentinelSize</code> or <code>SizeDelta</code> into HeaderTableNode and use it for these adjustments. Having said that, I know you're running out of time so please feel free to ignore it, it's no big deal and we can clean this up later if we decide it's worth it.

File: src/coreclr/src/vm/codeman.cpp [hunk 3]
```diff
@@ -6175,7 +6175,7 @@ int NativeUnwindInfoLookupTable::LookupUnwindInfoForMethod(DWORD RelativePc,
         if (RelativePc < pNextFunctionEntry->BeginAddress)
         {
             PTR_RUNTIME_FUNCTION pFunctionEntry = pRuntimeFunctionTable + i;
-            if (RelativePc >= pFunctionEntry->BeginAddress)
+            if (RelativePc >= pFunctionEntry->BeginAddress && RelativePc <= pFunctionEntry->EndAddress)
```
Comment (trylek) [inline src/coreclr/src/vm/codeman.cpp:6178]: Is EndAddress actually a valid address? I would expect this to be the RIP after the "ret" instruction i.e. in the non-reachable filler between adjacent functions that's normally getting filled with the "INT 3" instruction (on Intel). Long story short, should this rather be "<code>&lt;</code>" - especially in view of the fact that it _may_ happen in some cases that there's no filler (i.e. the <code>ret</code> instruction has the three lowest-order RIP bits set to 111) in which case the <code>&lt;=</code> sign could cause a spurious match?

**Review by trylek — APPROVED** [review]
Looks great modulo some nits and David's feedback, thanks so much Simon for making these fixes and improvements!

File: src/coreclr/src/vm/codeman.cpp (hunk 3 above)
Comment (nattress) [reply src/coreclr/src/vm/codeman.cpp:6178]: Yes that should be `<` thanks!

File: src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/RuntimeFunctionsTableNode.cs (hunk 2 above)
Comment (nattress) [reply src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/RuntimeFunctionsTableNode.cs:116]: Good idea - I'll add a SentinelSize property so it's more descriptive.

Comment (nattress) [reply src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/RuntimeFunctionsTableNode.cs:116]: Well, actually it's more awkward than I thought. Somewhere along the way, we stopped treating header table component nodes as `HeaderTableNode`s and in fact I further generalized it to `DependencyNodeCode<NodeFactory>` in this commit. For now I'll replace the numbers with a const in `RuntimeFunctionsTableNode`. `HeaderTableNode` currently just provides a base to factor default values for `ObjectNode` required overrides. We might want to just refactor it away altogether and use an interface on the header table component nodes to get the small amount of functionality needed.

Comment (trylek) [reply src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/RuntimeFunctionsTableNode.cs:116]: Sounds good, thank you!

File: src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs (hunk 1 above)
Comment (nattress) [reply src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:173]: Done

**Comment by davidwrighton** [comment]
This needs a fix for Windows X86. I've taken a look and it looks practical to use the GCInfo to provide a function size. Does that sound reasonable to everyone else? As @nattress is currently unavailable, I could put that fix together.

**Comment by mangod9** [comment]
both Simon and @trylek are out this week. If this can wait Tomas might be able make the changes then.

**Comment by davidwrighton** [comment]
We need to get this in for Preview 8, as we might get some usage on that, and the bug is very severe. I'll see if I can swing it tomorrow.

**Review by mangod9 — APPROVED** [review]

**Comment by jkotas** [comment]
Would it be better to handle the thunk problem by excluding the thunk range (`ReadyToRunSectionType::DelayLoadMethodCallThunks`) early?

Cracking the unwind info or gc info feels expensive.

**Comment by davidwrighton** [comment]
I like the @jkotas approach better. That's cheap, and avoids handling things specially for only 1 function. We can put the check in `JitCodeToMethodInfo`.

File: src/coreclr/src/vm/codeman.cpp [hunk 4]
```diff
@@ -6175,11 +6175,12 @@ int NativeUnwindInfoLookupTable::LookupUnwindInfoForMethod(DWORD RelativePc,
         if (RelativePc < pNextFunctionEntry->BeginAddress)
         {
             PTR_RUNTIME_FUNCTION pFunctionEntry = pRuntimeFunctionTable + i;
+            
             if (RelativePc >= pFunctionEntry->BeginAddress)
             {
                 return i;
+                break;
```
Comment (janvorli) [inline src/coreclr/src/vm/codeman.cpp:6182]: It seems the break should stay where it was.

Comment (davidwrighton) [reply src/coreclr/src/vm/codeman.cpp]: Sigh. Yes.

File: src/coreclr/src/debug/daccess/nidump.cpp [hunk 5]
```diff
@@ -3412,7 +3412,7 @@ size_t NativeImageDumper::TranslateSymbol(IXCLRDisassemblySupport *dis,
         {
             if (pNgenLayout->m_CodeSections[iRange].IsInRange((TADDR)addr))
             {
-                int MethodIndex = NativeUnwindInfoLookupTable::LookupUnwindInfoForMethod(rva, pNgenLayout->m_pRuntimeFunctions[iRange], 0, pNgenLayout->m_nRuntimeFunctions[iRange] - 1);
+                int MethodIndex = NativeUnwindInfoLookupTable::LookupUnwindInfoForMethod(PTR_TO_TADDR(m_decoder.GetBase()), rva, pNgenLayout->m_pRuntimeFunctions[iRange], 0, pNgenLayout->m_nRuntimeFunctions[iRange] - 1);
```
Comment (jkotas) [inline src/coreclr/src/debug/daccess/nidump.cpp:3415]: Revert this?

File: src/coreclr/src/vm/codeman.cpp [hunk 6]
```diff
@@ -6778,6 +6778,12 @@ BOOL ReadyToRunJitManager::JitCodeToMethodInfo(RangeSection * pRangeSection,
 
     // READYTORUN: FUTURE: Hot-cold spliting
 
+    // If the address is in a thunk, return NULL.
+    if (GetStubCodeBlockKind(pRangeSection, currentPC) != STUB_CODE_BLOCK_UNKNOWN)
```
Comment (jkotas) [inline src/coreclr/src/vm/codeman.cpp:6782]: It may be a good idea to cache the result of `pReadyToRunInfo->FindSection` in ReadyToRunInfo now that `GetStubCodeBlockKind` will be called much more often.

Comment (davidwrighton) [reply src/coreclr/src/vm/codeman.cpp:6783]: I've done that, and marked the ReadyToRunJitManager as a final class. The end result is that there is a minimal amount of extra code here now.

**Review by jkotas — APPROVED** [review]
