### PR TITLE
Fix compareTypesForEquality

### LINKED ISSUE #96876: CollectionsMarshal.AsSpan assertion failure in System.Text.Json tests
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=524311
Build error leg or test failing: System.Text.Json.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/96870

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Implementation depends on List<T> always using a T[] and not U[] where U : T.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=524311
**Error message validated:** `Implementation depends on List<T> always using a T[] and not U[] where U : T.`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/12/2024 1:31:48 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[524882](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524882)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524882&view=ms.vss-test-web.build-test-results-tab&runId=12431310&resultId=200255)|dotnet/runtime#95583|
|[525560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525560)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525560&view=ms.vss-test-web.build-test-results-tab&runId=12382444&resultId=200263)|dotnet/runtime#96609|
|[526100](https://dev.azure.com/dnceng-public/public/_build/results?buildId=526100)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=526100&view=ms.vss-test-web.build-test-results-tab&runId=12382398&resultId=200263)|dotnet/runtime#96880|
|[525785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525785)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525785&view=ms.vss-test-web.build-test-results-tab&runId=12379924&resultId=200271)|dotnet/runtime#96913|
|[525988](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525988)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525988&view=ms.vss-test-web.build-test-results-tab&runId=12379880&resultId=200357)|dotnet/runtime#96928|
|[525991](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525991)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525991&view=ms.vss-test-web.build-test-results-tab&runId=12379862&resultId=200263)|dotnet/runtime#89472|
|[525957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525957)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525957&view=ms.vss-test-web.build-test-results-tab&runId=12379460&resultId=200357)|dotnet/runtime#96927|
|[525923](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525923)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525923&view=ms.vss-test-web.build-test-results-tab&runId=12379050&resultId=200263)|dotnet/runtime#96926|
|[525892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525892)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525892&view=ms.vss-test-web.build-test-results-tab&runId=12378544&resultId=200263)|dotnet/runtime#96201|
|[525842](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525842)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525842&view=ms.vss-test-web.build-test-results-tab&runId=12377088&resultId=200357)|dotnet/runtime#96924|
|[525765](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525765)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525765&view=ms.vss-test-web.build-test-results-tab&runId=12375278&resultId=200263)|dotnet/runtime#96921|
|[525686](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525686)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525686&view=ms.vss-test-web.build-test-results-tab&runId=12371712&resultId=200357)|dotnet/runtime#96916|
|[525621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525621)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525621&view=ms.vss-test-web.build-test-results-tab&runId=12367392&resultId=200263)||
|[525570](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525570)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525570&view=ms.vss-test-web.build-test-results-tab&runId=12365784&resultId=200263)|dotnet/runtime#96880|
|[525477](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525477)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525477&view=ms.vss-test-web.build-test-results-tab&runId=12362376&resultId=200363)|dotnet/runtime#96805|
|[525444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525444)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525444&view=ms.vss-test-web.build-test-results-tab&runId=12362094&resultId=200258)|dotnet/runtime#96867|
|[525362](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525362)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525362&view=ms.vss-test-web.build-test-results-tab&runId=12359526&resultId=200352)|dotnet/runtime#96880|
|[525344](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525344)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525344&view=ms.vss-test-web.build-test-results-tab&runId=12358858&resultId=200258)|dotnet/runtime#96741|
|[525094](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525094)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525094&view=ms.vss-test-web.build-test-results-tab&runId=12357934&resultId=200255)|dotnet/runtime#96894|
|[525249](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525249)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525249&view=ms.vss-test-web.build-test-results-tab&runId=12357564&resultId=200255)|dotnet/runtime#96896|
|[525236](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525236)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525236&view=ms.vss-test-web.build-test-results-tab&runId=12357546&resultId=200349)|dotnet/runtime#96445|
|[525231](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525231)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525231&view=ms.vss-test-web.build-test-results-tab&runId=12357280&resultId=200255)|dotnet/runtime#96890|
|[525196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525196)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525196&view=ms.vss-test-web.build-test-results-tab&runId=12356392&resultId=200349)|dotnet/runtime#96214|
|[525140](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525140)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525140&view=ms.vss-test-web.build-test-results-tab&runId=12354936&resultId=200349)|dotnet/runtime#96676|
|[525086](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525086)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525086&view=ms.vss-test-web.build-test-results-tab&runId=12353926&resultId=200255)|dotnet/runtime#96893|
|[525001](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525001)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=525001&view=ms.vss-test-web.build-test-results-tab&runId=12352202&resultId=200255)|dotnet/runtime#96741|
|[524968](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524968)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524968&view=ms.vss-test-web.build-test-results-tab&runId=12351974&resultId=200349)|dotnet/runtime#96892|
|[524959](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524959)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524959&view=ms.vss-test-web.build-test-results-tab&runId=12351836&resultId=200255)|dotnet/runtime#96558|
|[524862](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524862)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524862&view=ms.vss-test-web.build-test-results-tab&runId=12349536&resultId=200255)|dotnet/runtime#96889|
|[524798](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524798)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524798&view=ms.vss-test-web.build-test-results-tab&runId=12347658&resultId=200349)||
|[524790](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524790)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524790&view=ms.vss-test-web.build-test-results-tab&runId=12347384&resultId=200349)|dotnet/runtime#95583|
|[524621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524621)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524621&view=ms.vss-test-web.build-test-results-tab&runId=12342992&resultId=200255)|dotnet/runtime#96860|
|[524464](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524464)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524464&view=ms.vss-test-web.build-test-results-tab&runId=12338542&resultId=200266)|dotnet/runtime#96805|
|[524458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524458)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524458&view=ms.vss-test-web.build-test-results-tab&runId=12338530&resultId=200255)|dotnet/runtime#96867|
|[524255](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524255)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524255&view=ms.vss-test-web.build-test-results-tab&runId=12337682&resultId=200247)|dotnet/runtime#96829|
|[524448](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524448)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524448&view=ms.vss-test-web.build-test-results-tab&runId=12337672&resultId=200255)|dotnet/runtime#96858|
|[524210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524210)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524210&view=ms.vss-test-web.build-test-results-tab&runId=12333996&resultId=200247)||
|[524311](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524311)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524311&view=ms.vss-test-web.build-test-results-tab&runId=12332614&resultId=200247)|dotnet/runtime#96870|
|[524291](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524291)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524291&view=ms.vss-test-web.build-test-results-tab&runId=12332148&resultId=200247)|dotnet/runtime#96867|
|[524193](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524193)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524193&view=ms.vss-test-web.build-test-results-tab&runId=12328450&resultId=200247)|dotnet/runtime#96858|
|[524168](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524168)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524168&view=ms.vss-test-web.build-test-results-tab&runId=12328000&resultId=200258)|dotnet/runtime#96805|
|[524110](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524110)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524110&view=ms.vss-test-web.build-test-results-tab&runId=12325752&resultId=200234)|dotnet/runtime#96795|
|[524101](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524101)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=524101&view=ms.vss-test-web.build-test-results-tab&runId=12325584&resultId=200247)|dotnet/runtime#96699|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|43|43|

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #96876

### CODE REVIEW

**Comment by jkotas** [comment]
TODO:
- Add tests
- Fix R2R/NAOT compiler

File: src/coreclr/vm/jitinterface.cpp [hunk 1]
```diff
@@ -4441,6 +4441,59 @@ TypeCompareState CEEInfo::compareTypesForCast(
...
+    {
+        return CorTypeInfo::IsObjRef(et1) != CorTypeInfo::IsObjRef(et2);
+    }
+
+    if (et1 != et2)
+    {
+        return true;
+    }
+
+    switch (et1)
```
Comment (jkotas) [inline src/coreclr/vm/jitinterface.cpp:4463]: This improves the original implementation in addition to make it correct. For example, this can prove that `KeyValuePair<__Canon, int>` and `KeyValuePair<int, __Canon>` are never equal that the original implementation was not able to.

**Comment by EgorBo** [comment]
@MihuBot

**Comment by jkotas** [comment]
@MichalStrehovsky PTLA

**Comment by jkotas** [comment]
This bug is not a recent regression for AOT compilers. The test introduced by this change fails with PublishAot and PublishReadyToRun in .NET 8.

**Comment by EgorBo** [comment]
> This bug is not a recent regression for AOT compilers. The test introduced by this change fails with PublishAot and PublishReadyToRun in .NET 8. Any thoughts about whether the backport meets the bar?

hm.. doesn't repro for me with R2R on net8.0, but does repro with NativeAOT

**Comment by jkotas** [comment]
> hm.. doesn't repro for me with R2R on net8.0, but does repro with NativeAOT

Good catch. The pattern matching of `typeof(X) == t.GetType()` checks seems to be broken in R2R (you can take a look why is that).

The pattern matching of `typeof(X) == typeof(Y)` works well and hits the bug in .NET 8:
```
C:\repro>type Program.cs
using System.Runtime.CompilerServices;

public class Test96876
{
    public static void Main()
    {
        Console.WriteLine(foo<string>());
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static bool foo<T>() => typeof(T[]) == typeof(string[]);
}
C:\repro>dotnet run
True

C:\repro>dotnet publish /p:PublishReadyToRun=true
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  Restored C:\repro\repro.csproj (in 174 ms).
  repro -> C:\repro\bin\Release\net8.0\win-x64\repro.dll
  repro -> C:\repro\bin\Release\net8.0\win-x64\publish\

C:\repro>C:\repro\bin\Release\net8.0\win-x64\publish\repro.exe
False

C:\repro>rmdir /s /q bin obj

C:\repro>dotnet publish /p:PublishAot=true
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  Restored C:\repro\repro.csproj (in 288 ms).
  repro -> C:\repro\bin\Release\net8.0\win-x64\repro.dll
  Generating native code
  repro -> C:\repro\bin\Release\net8.0\win-x64\publish\

C:\repro>C:\repro\bin\Release\net8.0\win-x64\publish\repro.exe
False
```

**Comment by jkotas** [comment]
> The pattern matching of typeof(X) == t.GetType() checks seems to be broken in R2R 

Opened #97134

File: src/coreclr/tools/Common/Compiler/TypeExtensions.cs [hunk 2]
```diff
@@ -182,43 +182,68 @@ public static bool IsArrayTypeWithoutGenericInterfaces(this TypeDesc type)
...
+                        if (((ArrayType)type1).Rank != ((ArrayType)type2).Rank)
+                            return true;
+                        return AreGuaranteedToRepresentDifferentTypes(((ArrayType)type1).ElementType, ((ArrayType)type2).ElementType);
+                    case TypeFlags.SzArray:
+                    case TypeFlags.ByRef:
+                    case TypeFlags.Pointer:
+                        return AreGuaranteedToRepresentDifferentTypes(((ParameterizedType)type1).ParameterType, ((ParameterizedType)type2).ParameterType);
+
+                    default:
+                        if (type1.IsDefType || type2.IsDefType)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/Compiler/TypeExtensions.cs:226]: I think this could get away with the same check as the VM side.

```suggestion
                        if (type1.IsDefType)
```

**Review by MichalStrehovsky — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
> This bug is not a recent regression for AOT compilers. The test introduced by this change fails with PublishAot and PublishReadyToRun in .NET 8. Any thoughts about whether the backport meets the bar?

We also shipped with it in .NET 7. Not a regression from previous release, no customer reports. Doesn't feel like we have a strong case for backport.

File: src/coreclr/tools/Common/Compiler/TypeExtensions.cs (hunk 2 above)
Comment (jkotas) [reply src/coreclr/tools/Common/Compiler/TypeExtensions.cs:226]: The VM side does check of matching CorElementType as early out that guarantees that both or neither types are def types.

I do not think that matching `TypeFlags` gives us the same guarantee here. The managed type system is more flexible, so I think we should check both types.

File: src/tests/Regressions/coreclr/GitHub_96876/test96876.csproj [hunk 3]
```diff
@@ -0,0 +1,12 @@
+<Project Sdk="Microsoft.NET.Sdk">
+  <PropertyGroup>
+    <!-- TODO: Change to 1 -->
+    <CLRTestPriority>0</CLRTestPriority>
```
Comment (jkotas) [inline src/tests/Regressions/coreclr/GitHub_96876/test96876.csproj:4]:
```suggestion
    <CLRTestPriority>1</CLRTestPriority>
```
