### PR TITLE
[mono] Re-enable tests that call MakeGenericType with non-RuntimeType arguments

### LINKED ISSUE #32743: System.RuntimeType.MakeGenericType throws NotImplementedException
```
      System.ComponentModel.Composition.Registration.Tests.RegistrationBuilderTests.GenericBaseClassExportInRegistrationBuilder [FAIL]
        System.NotImplementedException : The method or operation is not implemented.
        Stack Trace:
          /Users/alexander/dev/runtime/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(1256,0): at System.RuntimeType.MakeGenericType(Type[] instantiation)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionServices.cs(92,0): at System.ComponentModel.Composition.Hosting.CompositionServices.AdjustSpecifiedTypeIdentityType(Type specifiedContractType, Type memberType)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionServices.cs(61,0): at System.ComponentModel.Composition.Hosting.CompositionServices.AdjustSpecifiedTypeIdentityType(Type specifiedContractType, MemberInfo member)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionServices.cs(144,0): at System.ComponentModel.Composition.Hosting.CompositionServices.GetTypeIdentityTypeFromExport(MemberInfo member, ExportAttribute export)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionServices.cs(107,0): at System.ComponentModel.Composition.Hosting.CompositionServices.GetContractInfoFromExport(MemberInfo member, ExportAttribute export, Type& typeIdentityType, String& contractName)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(327,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.CreateExportDefinition(MemberInfo member, ExportAttribute exportAttribute)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(277,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetExportDefinitions()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(261,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.DiscoverExportsAndImports()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(67,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetExports()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePartDefinition.cs(67,0): at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.get_ExportDefinitionsInternal()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePartDefinition.cs(84,0): at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.get_ExportDefinitions()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/TypeCatalog.cs(323,0): at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex()
          /Users/alexander/dev/runtime/src/libraries/System.Private.CoreLib/src/System/Lazy.cs(328,0): at System.Lazy`1[[System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.List`1[[System.ComponentModel.Composition.Primitives.ComposablePartDefinition, System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(LazyThreadSafetyMode mode)
          /Users/alexander/dev/runtime/src/libraries/System.Private.CoreLib/src/System/Lazy.cs(346,0): at System.Lazy`1[[System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.List`1[[System.ComponentModel.Composition.Primitives.ComposablePartDefinition, System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
          /Users/alexander/dev/runtime/src/libraries/System.Private.CoreLib/src/System/Lazy.cs(426,0): at System.Lazy`1[[System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.List`1[[System.ComponentModel.Composition.Primitives.ComposablePartDefinition, System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
          /Users/alexander/dev/runtime/src/libraries/System.Private.CoreLib/src/System/Lazy.cs(507,0): at System.Lazy`1[[System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.List`1[[System.ComponentModel.Composition.Primitives.ComposablePartDefinition, System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/TypeCatalog.cs(313,0): at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(String contractName)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/TypeCatalog.cs(300,0): at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(ImportDefinition definition)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Primitives/ComposablePartCatalog.cs(105,0): at System.ComponentModel.Composition.Primitives.ComposablePartCatalog.GetExports(ImportDefinition definition)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CatalogExportProvider.cs(342,0): at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CatalogExportProvider.cs(37,0): at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.cs(213,0): at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.cs(147,0): at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CatalogExportProvider.cs(318,0): at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.cs(213,0): at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.cs(147,0): at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/AggregateExportProvider.cs(180,0): at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.cs(213,0): at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.cs(147,0): at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionContainer.cs(607,0): at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.cs(213,0): at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.cs(101,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(800,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(Type type, Type metadataViewType, String contractName, ImportCardinality cardinality)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(736,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[GenericBaseClass`1](String contractName, ImportCardinality cardinality)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(531,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[GenericBaseClass`1](String contractName)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(480,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[GenericBaseClass`1]()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition.Registration/tests/System/ComponentModel/Composition/Registration/RegistrationBuilderTests.cs(194,0): at System.ComponentModel.Composition.Registration.Tests.RegistrationBuilderTests.GenericBaseClassExportInRegistrationBuilder()

```

### PR DESCRIPTION
**Pull request by lambdageek**
Partially fixes https://github.com/dotnet/runtime/issues/32743

The actual fix was in https://github.com/dotnet/runtime/pull/58014

Some of the re-enabled tests failed on wasm due to https://github.com/dotnet/runtime/issues/52062, so those have been disabled here.

### CODE REVIEW

**Comment by lambdageek** [comment]
Replaces #64195

**Review by radical — APPROVED** [review]

**Review by eerhardt — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Comment by lambdageek** [comment]
Some failures on wasm and tvOS.  In both cases it looks like the tests probably need to be disabled.

Wasm example. Looks like it's trying to find an assembly in the file system, which won't work:
```
[18:08:27] fail: [FAIL] Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.WithNullLevel_GeneratorWontFail(argumentList: "EventId = 0, Level = null, Message = \"This is a m"...)
[18:08:27] info: System.ArgumentException : Empty path name is not legal. (Parameter 'path')
[18:08:27] info:    at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
[18:08:27] info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
[18:08:27] info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[18:08:27] info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
[18:08:27] info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
[18:08:27] info:    at Roslyn.Utilities.StandardFileSystem.OpenFile(String filePath, FileMode mode, FileAccess access, FileShare share)
[18:08:27] info:    at Roslyn.Utilities.CommonCompilerFileSystemExtensions.OpenFileWithNormalizedException(ICommonCompilerFileSystem fileSystem, String filePath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
[18:08:27] info:    at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
[18:08:27] info:    at SourceGenerators.Tests.RoslynTestUtils.CreateTestProject(IEnumerable`1 references, Boolean includeBaseReferences)
[18:08:27] info:    at SourceGenerators.Tests.RoslynTestUtils.RunGenerator(ISourceGenerator generator, IEnumerable`1 references, IEnumerable`1 sources, Boolean includeBaseReferences, CancellationToken cancellationToken)
[18:08:27] info:    at Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.RunGenerator(String code, Boolean wrap, Boolean inNamespace, Boolean includeBaseReferences, Boolean includeLoggingReferences, CancellationToken cancellationToken)
[18:08:27] info:    at Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.WithNullLevel_GeneratorWontFail(String argumentList)
[18:08:27] info: --- End of stack trace from previous location ---
```

tvOS example. `MakeGenericType` with non-`RuntimeType` arguments isn't supported in FullAOT:

```
System.PlatformNotSupportedException : Operation is not supported on this platform.

Stack trace
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at System.ComponentModel.Composition.Hosting.CompositionServices.AdjustSpecifiedTypeIdentityType(Type specifiedContractType, Type memberType)
   at System.ComponentModel.Composition.Hosting.CompositionServices.AdjustSpecifiedTypeIdentityType(Type specifiedContractType, MemberInfo member)
   at System.ComponentModel.Composition.Hosting.CompositionServices.GetTypeIdentityTypeFromExport(MemberInfo member, ExportAttribute export)
   at System.ComponentModel.Composition.Hosting.CompositionServices.GetContractInfoFromExport(MemberInfo member, ExportAttribute export, Type& typeIdentityType, String& contractName)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.CreateExportDefinition(MemberInfo member, ExportAttribute exportAttribute)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetExportDefinitions()
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.DiscoverExportsAndImports()
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetExports()
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.get_ExportDefinitionsInternal()
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.get_ExportDefinitions()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex()
   at System.Lazy`1[[System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.List`1[[System.ComponentModel.Composition.Primitives.ComposablePartDefinition, System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.List`1[[System.ComponentModel.Composition.Primitives.ComposablePartDefinition, System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.List`1[[System.ComponentModel.Composition.Primitives.ComposablePartDefinition, System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.List`1[[System.ComponentModel.Composition.Primitives.ComposablePartDefinition, System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(String contractName)
   at System.ComponentMo
```

**Comment by radical** [comment]
The wasm ones are failing to get the assembly location with `string corelib = Assembly.GetAssembly(typeof(object))!.Location;`.
Issue: https://github.com/dotnet/runtime/issues/52062

File: src/libraries/System.ComponentModel.Composition.Registration/tests/System/ComponentModel/Composition/Registration/RegistrationBuilderTests.cs [hunk 1]
```diff
@@ -45,7 +45,7 @@ public DiscoveredCatalog()
         }
 
         [Fact]
-        [ActiveIssue("https://github.com/dotnet/runtime/issues/32743", TestRuntimes.Mono)]
+        [ActiveIssue("https://github.com/dotnet/runtime/issues/32743", TestPlatforms.tvOS)]
```
Comment (lambdageek) [inline src/libraries/System.ComponentModel.Composition.Registration/tests/System/ComponentModel/Composition/Registration/RegistrationBuilderTests.cs:48]: @radical I don't think this is an ActiveIssue.  (or at least 32743 is misleading).  I don't think we can support MakeGenericType for non-RuntimeType types in FullAOT (without interpreter fallback).

I think this should be `[ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotMonoAot))]`

Comment (marek-safar) [reply src/libraries/System.ComponentModel.Composition.Registration/tests/System/ComponentModel/Composition/Registration/RegistrationBuilderTests.cs:48]: Yep, this is not tvOS specific. Using `RuntimeFeature.IsDynamicCode` or whatever flag NativeAOT uses would be better

/cc @jkotas

Comment (lambdageek) [reply src/libraries/System.ComponentModel.Composition.Registration/tests/System/ComponentModel/Composition/Registration/RegistrationBuilderTests.cs:48]: I guess that's

https://github.com/dotnet/runtime/blob/3e4c4a4c2c3343ac545bf48b9c3189556bfecf73/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L109

```
[ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsReflectionEmitSupported)]
```

Which brings up the question: do we run these tests with NativeAOT? I would expect them to fail there, too

**Comment by lambdageek** [comment]
Failures are https://github.com/dotnet/runtime/issues/64389

**Comment by MaximLipnin** [comment]
The re-enabled `Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests` tests started failing with PNSE on Mono+Windows legs.
