### PR TITLE
Only pass the method context when tracking transitions.

### LINKED ISSUE #47223: UnmanagedCallersOnly performance regression and R2R breaking change in
Introduced by #46238. See https://github.com/dotnet/runtime/pull/46238/files#r560910948 for details.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Create a new helper instead of modifying an existing one. Only track transitions when we absolutely need to.

Fixes #47223

cc: @dotnet/jit-contrib

### CODE REVIEW

File: src/coreclr/inc/corinfo.h [hunk 1]
```diff
@@ -592,6 +592,8 @@ enum CorInfoHelpFunc
     CORINFO_HELP_PATCHPOINT,                // Notify runtime that code has reached a patchpoint
     CORINFO_HELP_CLASSPROFILE,              // Update class profile for a call site
 
+    CORINFO_HELP_JIT_REVERSE_PINVOKE_ENTER_TRACK_TRANSITIONS, // Transition to cooperative mode and track transitions in reverse P/Invoke prolog.
```
Comment (jkotas) [inline src/coreclr/inc/corinfo.h:595]: Nit: This enum does not need to be stable. It is fine to add this where it logically belongs (ie next to existing `CORINFO_HELP_JIT_REVERSE_PINVOKE_ENTER`).

Comment (jkotas) [inline src/coreclr/inc/corinfo.h:595]: We should have `LEAVE` version of this helper too.

File: src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs [hunk 2]
```diff
@@ -881,6 +881,8 @@ public struct InlinedCallFrameInfo
         // Reverse PInvoke offsets
         public uint sizeOfReversePInvokeFrame;
 
+        public byte passMethodContextToReversePInvokeHelper;
```
Comment (jkotas) [inline src/coreclr/tools/Common/JitInterface/CorInfoTypes.cs:884]: I think it would be more appropriate for this to be a `CORJIT_FLAG_`. The flag that controls callbacks for regular profiler enter/exit callouts is also `CORJIT_FLAG_`.

**Comment by jkotas** [comment]
`ReadyToRunInfo::GetEntryPoint` should have something like this:

```
if (CORProfilerTrackTransitions() && pMD->HasUnmanagedCallersOnlyAttribute())
{
   pMD->SetProfilerRejectedPrecompiledCode();
   goto done;
}
```

File: src/coreclr/inc/corjitflags.h [hunk 3]
```diff
@@ -85,7 +85,7 @@ class CORJIT_FLAGS
         CORJIT_FLAG_SAMPLING_JIT_BACKGROUND = 35, // JIT is being invoked as a result of stack sampling for hot methods in the background
         CORJIT_FLAG_USE_PINVOKE_HELPERS     = 36, // The JIT should use the PINVOKE_{BEGIN,END} helpers instead of emitting inline transitions
         CORJIT_FLAG_REVERSE_PINVOKE         = 37, // The JIT should insert REVERSE_PINVOKE_{ENTER,EXIT} helpers into method prolog/epilog
-        CORJIT_FLAG_UNUSED14                = 38,
+        CORJIT_FLAG_TRACK_TRANSITIONS       = 38, // The JIT should insert the helper variants that track transitions.
```
Comment (jkotas) [inline src/coreclr/inc/corjitflags.h:88]:
```suggestion
        CORJIT_FLAG_TRACK_TRANSITIONS       = 38, // The JIT should insert the REVERSE_PINVOKE helper variants that track transitions.
```

File: src/coreclr/vm/jithelpers.cpp [hunk 4]
```diff
@@ -5407,19 +5407,17 @@ NOINLINE static void JIT_ReversePInvokeEnterRare2(ReversePInvokeFrame* frame, vo
 #endif // DEBUGGING_SUPPORTED
 }
 
-// The following two methods are special.
+// The following three methods are special.
```
Comment (jkotas) [inline src/coreclr/vm/jithelpers.cpp:5410]:
```suggestion
// The following JIT_ReversePInvoke helpers are special.
```

**Review by jkotas — APPROVED** [review]
Thank you!

**Review by sandreenko — APPROVED** [review]
Jit changes look fine.

**Comment by jkotas** [comment]
Why is the last commit needed? These callouts should be limited to JIT only. We would have to introduce a whole new separate R2R image flavor to make that work. It is not something we want to do.

**Comment by jkoritzinsky** [comment]
I may have been a little overzealous on adding all the R2R helpers. I’ll go remove the e R2R helpers and just update the JIT helpers on the Crossgen2 side (which is all I really needed to do on that commit)

**Comment by jkoritzinsky** [comment]
Can you take a look at the 2 new commits and let me know what you think?

File: src/coreclr/vm/jithelpers.cpp [hunk 5]
```diff
@@ -5375,7 +5375,7 @@ NOINLINE static void JIT_ReversePInvokeEnterRare(ReversePInvokeFrame* frame, voi
     frame->currentThread = thread;
 
 #ifdef PROFILING_SUPPORTED
-        if (CORProfilerTrackTransitions())
+        if (frame->pMD && CORProfilerTrackTransitions())
```
Comment (jkotas) [inline src/coreclr/vm/jithelpers.cpp:5378]: Do we still need the `frame->pMD` null check here? It is not in other similar places. I am not able to figure what makes this place special.

File: src/coreclr/vm/jithelpers.cpp [hunk 6]
```diff
@@ -5462,7 +5460,41 @@ void F_CALL_CONV HCCALL3(JIT_ReversePInvokeEnter, ReversePInvokeFrame* frame, CO
 #endif
 }
 
-void F_CALL_CONV HCCALL1(JIT_ReversePInvokeExit, ReversePInvokeFrame* frame)
+void F_CALL_CONV HCCALL1(JIT_ReversePInvokeEnter, ReversePInvokeFrame* frame)
+{
+    _ASSERTE(frame != NULL);
+
+    frame->pMD = nullptr;
```
Comment (jkotas) [inline src/coreclr/vm/jithelpers.cpp:5467]: Nit: This should not be needed. You can set it to garbage value in debug-only.

**Comment by jkotas** [comment]
LGTM otherwise.

File: src/coreclr/vm/jithelpers.cpp (hunk 5 above)
Comment (jkoritzinsky) [reply src/coreclr/vm/jithelpers.cpp:5378]: This function is used from both of the Enter helpers. I’m using a null pMD as the semantic for being called from the non-transition-tracking helper.

Comment (jkotas) [reply src/coreclr/vm/jithelpers.cpp:5378]: I think that MetthodDesc is null for the transition tracking helper in the UnmanagedCallersOnly case. It should be sufficient to check `CORProfilerTrackTransitions` here. The value returned by `CORProfilerTrackTransitions` cannot change during the process lifetime.

**Review by jkotas — APPROVED** [review]
