### PR TITLE
Arm64 SVE: Do not remove embedded conditional selects

### LINKED ISSUE #116140: Arm64 SVE: Assert failure when TrueMask used in conditional select
```
    static unsafe void CndSelectEmbeddedOp3LoadTrueMask(int[] array, Vector<int> op1)
    {
        fixed (int* arr_ptr = array)
        {
            var result = Sve.ConditionalSelect(Sve.CreateTrueMaskInt32(), op1, Sve.LoadVectorNonFaulting(arr_ptr));
            Consume(result);
        }
    }
```

```
Assert failure(PID 1322427 [0x00142dbb], Thread: 1322427 [0x142dbb]): Assertion failed '!node->IsEmbMaskOp()' in 'EmbeddedLoads:CndSelectEmbeddedOp3LoadTrueMask(int[],System.Numerics.Vector`1[int])' during 'Generate code' (IL size 51; hash 0xedf2dbdb; FullOpts)

    File: /mnt/sdb/home/alahay01/dotnet/runtime_table/src/coreclr/jit/hwintrinsiccodegenarm64.cpp:1093
    Image: /mnt/sdb/home/alahay01/dotnet/runtime_table/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun
```

This is because LIR  optimises `ConditionalSelect(True, x, EmbeddedConditionalSelect(True, Load(), 0))` to `x`. Later the `EmbeddedConditionalSelect()` is removed as unused. However, the `Load()` is kept because it's a load/store.
The `Load()` fails to codegen becuase it is not inside an `EmbeddedConditionalSelect()`

There are similar tests in HWIntrinsics, but they use `Vector<int>.AllBitsSet` instead of truemask, and so the optimisation in lowering never happens

### PR DESCRIPTION
**Pull request by a74nh**
Fixes #116140

When an embedded SVE instrinsic is created, during lowering a conditional select is created to embed the operation. This required to ensure there is a mask for the embedded intrinsic to use.

Ensure that the embedding conditional select can only be removed if the embedded intrinsic is also removed.

### CODE REVIEW

File: src/coreclr/jit/gentree.h [hunk 1]
```diff
@@ -554,6 +554,7 @@ enum GenTreeFlags : unsigned int
 #ifdef FEATURE_HW_INTRINSICS
     GTF_HW_EM_OP                  = 0x10000000, // GT_HWINTRINSIC -- node is used as an operand to an embedded mask
```
Comment (a74nh) [inline src/coreclr/jit/gentree.h:555]: I don't think we need both `GTF_HW_EM_OP` and `GTF_HW_EMBEDDING_OP`, as `GTF_HW_EM_OP` can be implied when a node is contained and it's parent has `GTF_HW_EMBEDDING_OP`.

Didn't want to do that yet until the rest of the PR is agreed (or maybe push to a future PR)

**Comment by a74nh** [comment]
Was having a further think about this. I've reworked `LowerHWIntrinsicCndSel()` a little so that it takes into account the new flag rather than the more convoluted existing checks.

Checked spmidiff and there are no changes.

I'm happy with this PR now.

File: src/coreclr/jit/lowerarmarch.cpp [hunk 2]
```diff
@@ -1948,9 +1948,6 @@ GenTree* Lowering::LowerHWIntrinsic(GenTreeHWIntrinsic* node)
     if (HWIntrinsicInfo::IsEmbeddedMaskedOperation(intrinsicId))
     {
         LIR::Use use;
-        JITDUMP("lowering EmbeddedMasked HWIntrinisic (before):\n");
```
Comment (kunalspathak) [inline src/coreclr/jit/lowerarmarch.cpp:1951]: This might be still useful to have. #Resolved

File: src/coreclr/jit/gentree.cpp [hunk 3]
```diff
@@ -7226,6 +7226,13 @@ bool GenTree::OperMayThrow(Compiler* comp)
             assert(varTypeIsInt(AsHWIntrinsic()->GetSimdBaseType()));
             return true;
         }
+#elif defined(TARGET_ARM64)
+        // If this node is embedding another node, then check that instead.
+        if (IsEmbeddingMaskOp())
+        {
+            assert(this->AsHWIntrinsic()->GetHWIntrinsicId() == NI_Sve_ConditionalSelect);
+            return this->AsHWIntrinsic()->Op(2)->OperMayThrow(comp);
```
Comment (kunalspathak) [inline src/coreclr/jit/gentree.cpp:7234]: What if this is user written `ConditionalSelect` and contains something that throws in `op1` or `op3`? Should we check for those as well?

File: src/coreclr/jit/lowerarmarch.cpp [hunk 4]
```diff
@@ -4137,65 +4132,59 @@ GenTree* Lowering::LowerHWIntrinsicCndSel(GenTreeHWIntrinsic* cndSelNode)
...
-                DISPTREERANGE(BlockRange(), cndSelNode);
-                JITDUMP("\n");
+                LABELEDDISPTREERANGE("Removed nested conditionalselect (before):", BlockRange(), cndSelNode);
 
                 // Transform:
                 //
-                // CndSel(mask, CndSel(AllTrue, embeddedMask(trueValOp2), trueValOp3), op3) to
-                // CndSel(mask, embedded(trueValOp2), op3)
+                // CndSel1(mask, CndSel2(AllTrue, embedded() trueValOp3), op3) to
+                // CndSel1(mask, embedded() op3)
```
Comment (kunalspathak) [inline src/coreclr/jit/lowerarmarch.cpp]:
```suggestion
                // CndSel1(mask, embedded(), op3)
```

File: src/coreclr/jit/gentree.h [hunk 5]
```diff
@@ -554,6 +554,7 @@ enum GenTreeFlags : unsigned int
...
     GTF_HW_USER_CALL              = 0x20000000, // GT_HWINTRINSIC -- node is implemented via a user call
+    GTF_HW_EMBEDDING_OP           = 0x40000000, // GT_HWINTRINSIC -- node is a node being used to embed a mask and operand
```
Comment (kunalspathak) [inline src/coreclr/jit/gentree.h]:
```suggestion
    GTF_HW_EMBEDDING_OP           = 0x40000000, // GT_HWINTRINSIC -- node is being used to embed a mask and operand
```

**Review by kunalspathak — CHANGES_REQUESTED** [review]
Added a question about `OperMayThrow`

File: src/coreclr/jit/gentree.cpp (hunk 3 above)
Comment (jakobbotsch) [reply src/coreclr/jit/gentree.cpp:7234]: Also `OperMayThrow` should be kept in sync with `OperExceptions`. It does not make sense for the latter to return an empty set of the former returns true.

Comment (jakobbotsch) [reply src/coreclr/jit/gentree.cpp:7234]: > What if this is user written `ConditionalSelect` and contains something that throws in `op1` or `op3`? Should we check for those as well?

These methods like `OperMayThrow`, `OperRequiresCallFlag` etc. do not consider operand nodes. They are meant to recompute the flag for the node itself only.

I would rather see us introducing a new variant of `OperMayThrow` that takes containment into account and which may be used in the rare case that the backend needs it. It should not need hardcoding to a specific oper type like this.

**Comment by a74nh** [comment]
Before I update the PR, and the results are lost, here are the results of the fuzzlyn tests:

Screenshot 2025-06-11 at 11 54 45

File: src/coreclr/jit/gentree.cpp (hunk 3 above)
Comment (a74nh) [reply src/coreclr/jit/gentree.cpp:7234]: > I would rather see us introducing a new variant of `OperMayThrow`

Done. Not keen on the new name (`OperOrEmbeddedChildrenMayThrow()`)

> that takes containment into account and which may be used in the rare case that the backend needs it. It should not need hardcoding to a specific oper type like this.

Specifically, it still checks IsEmbeddingMaskOp() and not containment (as there is a period where the nodes are not yet contained).

> What if this is user written `ConditionalSelect` and contains something that throws in `op1` or `op3`? Should we check for those as well?

Also done.

Comment (jakobbotsch) [reply src/coreclr/jit/gentree.cpp:7234]: > Specifically, it still checks IsEmbeddingMaskOp() and not containment (as there is a period where the nodes are not yet contained).

The liveness that is using this runs after lowering. After lowering, all the containment checks should be done. If we are not properly marking these operands as contained during lowering then that seems like a bug. Have we actually introduced another concept of "containment" called "embedding" here?

Comment (a74nh) [reply src/coreclr/jit/gentree.cpp:7234]: The way I interpreted [this comment](https://github.com/dotnet/runtime/pull/115566#discussion_r2103087325) was that I shouldn't be relying on the changes that happen in lowering. Re-reading now I'm not sure if I still agree.

I'm happy to remove the new `GTF_HW_EMBEDDING_OP` flag and instead `OperOrEmbeddedChildrenMayThrow()` would check nodes based on containing.

??

Comment (a74nh) [reply src/coreclr/jit/gentree.cpp:7234]: > I'm happy to remove the new `GTF_HW_EMBEDDING_OP` flag and instead `OperOrEmbeddedChildrenMayThrow()` would check nodes based on containing.

Fixed it up to work that way

Comment (jakobbotsch) [reply src/coreclr/jit/gentree.cpp:7234]: I upvoted that because changing `OperMayThrow` to check child nodes is outside the contract of what `OperMayThrow` is supposed to do. I think @tannergooding's comment was about the same thing. HIR uses this function to determine if the evaluation of a node itself may throw, and its contract is supposed to exclude child nodes (function header could be clearer on this point). For checking if a subtree rooted at a node may throw we have `GTF_EXCEPT`. So changing `OperMayThrow` could indeed be a pessimization for HIR.

However, in LIR things are different because of containment and because of how evaluation works. The flags no longer make sense there because the operands of the nodes are not actually its children, and are their own thing. The exception of course is containment; evaluation of a node with a contained operand _does_ include the effects of its operand. So we need the spiritual equivalent of `GTF_EXCEPT` for LIR. I think it makes sense to introduce a version of `OperMayThrow` that does that. I would suggest calling it something like `NodeOrContainedOperandsMayThrow()`.

File: src/coreclr/jit/gentree.cpp [hunk 6]
```diff
@@ -7233,6 +7233,70 @@ bool GenTree::OperMayThrow(Compiler* comp)
...
+//    True if the given operator may cause an exception
+//
+bool GenTree::OperOrContainedChildrenMayThrow(Compiler* comp)
+{
+    // Recursively parse all contained children.
+    ContainedChildrenMayThrow ev(comp, this);
+    GenTree *firstNode = this;
+    ev.WalkTree(&firstNode, nullptr);
+    return ev.mayThrow;
+}
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.cpp]: I would suggest modelling this after `gtGetContainedRegMask`. We don't generally use tree walkers in LIR since LIR doesn't have trees.

Comment (a74nh) [reply src/coreclr/jit/gentree.cpp]: > I would suggest modelling this after `gtGetContainedRegMask`. We don't generally use tree walkers in LIR since LIR doesn't have trees.

Much simpler. Done.

**Review by jakobbotsch — APPROVED** [review]
This looks good to me, but need to double check asm/tp diffs

File: src/coreclr/jit/lowerarmarch.cpp [hunk 7]
```diff
@@ -4137,25 +4132,20 @@ GenTree* Lowering::LowerHWIntrinsicCndSel(GenTreeHWIntrinsic* cndSelNode)
...
-                JITDUMP("lowering nested ConditionalSelect HWIntrinisic (before):\n");
-                DISPTREERANGE(BlockRange(), cndSelNode);
-                JITDUMP("\n");
+                LABELEDDISPTREERANGE("Removed nested conditionalselect (before):", BlockRange(), cndSelNode);
 
                 // Transform:
                 //
-                // CndSel(mask, CndSel(AllTrue, embeddedMask(trueValOp2), trueValOp3), op3) to
-                // CndSel(mask, embedded(trueValOp2), op3)
+                // CndSel1(mask, CndSel2(AllTrue, embedded() trueValOp3), op3) to
```
Comment (kunalspathak) [inline src/coreclr/jit/lowerarmarch.cpp]:
```suggestion
                // CndSel1(mask, CndSel2(AllTrue, embedded(), trueValOp3), op3) to
```

File: src/tests/JIT/opt/SVE/EmbeddedLoads.csproj [hunk 8]
```diff
@@ -0,0 +1,19 @@
...
+    <Optimize>True</Optimize>
+    <NoWarn>$(NoWarn),SYSLIB5003</NoWarn>
+  </PropertyGroup>
+  <ItemGroup>
+    <Compile Include="$(MSBuildProjectName).cs">
+      <HasDisasmCheck Condition="'$(DOTNET_EnableHWIntrinsic)' != '0' and '$(DOTNET_EnableArm64Sve)' != '0'">true</HasDisasmCheck>
+    </Compile>
+
+    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="0" />
+    <CLRTestEnvironmentVariable Include="DOTNET_JITMinOpts" Value="0" />
```
Comment (kunalspathak) [inline src/tests/JIT/opt/SVE/EmbeddedLoads.csproj:17]: please add `<CLRTestEnvironmentVariable Include="DOTNET_EnableHWIntrinsic" Value="1" />` as pointed in [https://github.com/dotnet/runtime/pull/116441/](https://github.com/dotnet/runtime/pull/116441/)

Comment (a74nh) [reply src/tests/JIT/opt/SVE/EmbeddedLoads.csproj:17]: > please add `<CLRTestEnvironmentVariable Include="DOTNET_EnableHWIntrinsic" Value="1" />` as pointed in #116441


Done. This line is still correct?
```
      <HasDisasmCheck Condition="'$(DOTNET_EnableHWIntrinsic)' != '0' and '$(DOTNET_EnableArm64Sve)' != '0'">true</HasDisasmCheck>
```

File: src/coreclr/jit/gentree.cpp (hunk 3 above)
Comment (tannergooding) [reply src/coreclr/jit/gentree.cpp:7234]: >  I think @tannergooding's comment was about the same thing

Yep. There's quite a bit of nuance between LIR and HIR in some cases and the guarantees we have in place. We generally don't want to make modifications to general IR for something that is LIR only and instead want to have a `Lowering::*` specific function instead -or- try to work with what LIR may expect, such as by introducing a different LIR specific intrinsic ID (which is what we do for `xarch` in several cases).

File: src/tests/JIT/opt/SVE/EmbeddedLoads.csproj (hunk 8 above)
Comment (kunalspathak) [reply src/tests/JIT/opt/SVE/EmbeddedLoads.csproj:17]: > This line is still correct?

No, because that is taken during build time when those variables might not be set. That was the first thing I tried after which I fallback to `DOTNET_EnableHWIntrinsic=1` alternative.

Comment (a74nh) [reply src/tests/JIT/opt/SVE/EmbeddedLoads.csproj:17]: > No, because that is taken during build time when those variables might not be set. That was the first thing I tried after which I fallback to `DOTNET_EnableHWIntrinsic=1` alternative.

Ok, fixed.

**Review by kunalspathak — APPROVED** [review]
LGTM

File: src/coreclr/jit/gentree.cpp [hunk 9]
```diff
@@ -7233,6 +7233,34 @@ bool GenTree::OperMayThrow(Compiler* comp)
...
+// NodeOrContainedOperandsMayThrow : Check whether the operation or any contained
+//                                   children will throw
+//
+// Arguments:
+//    comp      -  Compiler instance
+//
+// Return Value:
+//    True if the given operator or contained children may cause an exception
+//
+bool GenTree::NodeOrContainedOperandsMayThrow(Compiler* comp)
```
Comment (kunalspathak) [inline src/coreclr/jit/gentree.cpp:7246]: At least in short term, this should only be for arm64. We are seeing diffs on x64 because this is also affecting x64.

**Review by kunalspathak — CHANGES_REQUESTED** [review]
Need to make the `NodeOrContainedOperandsMayThrow` check only for arm64.

**Comment by jakobbotsch** [comment]
> Need to make the `NodeOrContainedOperandsMayThrow` check only for arm64.

I think it's fine to keep this for x64, despite some small regressions. Alternatively we should figure out how x64 deals with the situation for its contained indirections and then do it the same way for arm64.

**Comment by kunalspathak** [comment]
> Alternatively we should figure out how x64 deals with the situation for its contained indirections and then do it the same way for arm64.

Can this be a follow-up work then, or should it be as part of this PR? I prefer the former.

**Comment by jakobbotsch** [comment]
> > Alternatively we should figure out how x64 deals with the situation for its contained indirections and then do it the same way for arm64.
> 
> Can this be a follow-up work then, or should it be as part of this PR? I prefer the former.

I think we should just take this change for all platforms. It's only a handful of regressions on x64, and the logic is equally right everywhere.

**Comment by kunalspathak** [comment]
@jakobbotsch - do you know what these errors are? I will rerun those legs.

> Status: 403 (Key based authentication is not permitted on this storage account.)
ErrorCode: KeyBasedAuthenticationNotPermitted

**Comment by jakobbotsch** [comment]
The superpmi collection after #116484 yesterday failed due to Helix problems, so that's why you're seeing the SPMI failures here. I am rerunning the collection internally.

**Review by kunalspathak — APPROVED** [review]
LGTM
