### PR TITLE
Fix build break on osx/arm64 Debug

### LINKED ISSUE #102618: Debug build errors out
I hit an error when building the CoreCLR in debug mode.

The command that I use to build is

```
./build.sh clr+libs -c debug
```

The error message was

```
  Undefined symbols for architecture arm64:
    "RegSet::rsAllCalleeSavedMask", referenced from:
        RegSet::rsGetModifiedCalleeSavedRegsMask() const in codegencommon.cpp.o
    "RegSet::rsIntCalleeSavedMask", referenced from:
        RegSet::rsGetModifiedOsrIntCalleeSavedRegsMask() const in codegenxarch.cpp.o
        RegSet::rsGetModifiedIntCalleeSavedRegsMask() const in codegenxarch.cpp.o
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This seems to be related to definition of `SWIFT_SUPPORT`

### PR DESCRIPTION
**Pull request by kunalspathak**
Fixes: https://github.com/dotnet/runtime/issues/102618 and the errors reported in 
https://github.com/dotnet/runtime/pull/102297#issuecomment-2127142534

### CODE REVIEW

File: src/coreclr/jit/regset.cpp [hunk 1]
```diff
@@ -44,6 +44,34 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 */
 
+#ifdef SWIFT_SUPPORT
+    regMaskTP rsAllCalleeSavedMask;
+    regMaskTP rsIntCalleeSavedMask;
```
Comment (amanasifkhalid) [inline src/coreclr/jit/regset.cpp:49]: Do you think it would be cleaner to initialize these here instead of in `RegSet`'s constructor below? Also, it might be nice to add a comment explaining these aren't `const` or `constexpr` because `rsClearRegsModified` (and only this method) can modify them in Swift interop scenarios.

**Review by amanasifkhalid — APPROVED** [review]

File: src/coreclr/jit/regset.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/regset.cpp:49]: > Do you think it would be cleaner to initialize these here instead of in RegSet's constructor below?

sure.

> `constexpr`

Was there a specific TP improvement we saw by marking them `constexpr`? I am inclined to just make them and it is just cleaner.

```c++
regMaskTP rsAllCalleeSavedMask = RBM_CALLEE_SAVED;
regMaskTP rsIntCalleeSavedMask = RBM_INT_CALLEE_SAVED;
```

Comment (kunalspathak) [reply src/coreclr/jit/regset.cpp]: Will check if there is any TP impact with this change.

Comment (amanasifkhalid) [reply src/coreclr/jit/regset.cpp]: > Was there a specific TP improvement we saw by marking them constexpr?

This was part of a bigger change, so I'm not sure what the TP impact is of changing this. I'm curious to see as well

File: src/coreclr/jit/regset.h [hunk 2]
```diff
@@ -74,13 +74,8 @@ class RegSet
...
 #endif                                  // DEBUG
 
-#ifdef SWIFT_SUPPORT
-    regMaskTP rsAllCalleeSavedMask;
-    regMaskTP rsIntCalleeSavedMask;
-#else  // !SWIFT_SUPPORT
-    static constexpr regMaskTP rsAllCalleeSavedMask = RBM_CALLEE_SAVED;
-    static constexpr regMaskTP rsIntCalleeSavedMask = RBM_INT_CALLEE_SAVED;
-#endif // !SWIFT_SUPPORT
+    regMaskTP rsAllCalleeSavedMask = RBM_CALLEE_SAVED;
```
Comment (jkotas) [inline src/coreclr/jit/regset.h:77]: Does it mean that we are leaving a bit of perf on the table by turning into into a regular field?

Comment (kunalspathak) [reply src/coreclr/jit/regset.h:77]: We will find out in the tpdiffs. If it does impact TP, I will revert it back.

Comment (kunalspathak) [reply src/coreclr/jit/regset.h:77]: The underlying methods i.e. `rsClearRegsModified` and `rsGetModifiedCalleeSavedRegsMask` is just called once during the compilation, so I am guessing this shouldn't be much of an impact.

Comment (kunalspathak) [reply src/coreclr/jit/regset.h:77]: No TP impact

image

**Comment by am11** [comment]
Thanks @kunalspathak! Build on osx-arm64 is succeeded. 👍
