### PR TITLE
Various fixes for consecutive registers found with jitstressregs

### LINKED ISSUE #84747: Assertion failed 'refPosition->RegOptional()'
arm64 JitStress=2 JitStressRegs=8

https://dev.azure.com/dnceng-public/public/_build/results?buildId=235833&view=ms.vss-test-web.build-test-results-tab&runId=4502376&resultId=116940&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
export DOTNET_TieredCompilation=0
export DOTNET_JitStress=2
export DOTNET_JitStressRegs=8
```

```
08:31:13.646 Running test: _AdvSimd_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Program.VectorLookupExtension_4_Byte()
Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario

Assert failure(PID 23 [0x00000017], Thread: 23 [0x0017]): Assertion failed 'refPosition->RegOptional()' in 'JIT.HardwareIntrinsics.Arm._AdvSimd.VectorLookupExtension_4Test__VectorTableLookupExtensionByte:RunLclVarScenario_UnsafeRead():this' during 'LSRA build intervals' (IL size 183; hash 0xb48fe709; FullOpts)

    File: /__w/1/s/src/coreclr/jit/lsra.cpp Line: 12369
    Image: /root/helix/work/correlation/corerun

[createdump] Gathering state for process 23 corerun
[createdump] Crashing thread 0017 signal 6 (0006)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffeacda45230)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffeacda45230)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffeacda3a414)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.23.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.23.dmp
[createdump] Written 279306240 bytes (68190 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 594ms
[createdump] waitpid() returned successfully (wstatus 00000000)
App Exit Code: 22
Expected: 100
Actual: 22
END EXECUTION - FAILED
```

### PR DESCRIPTION
**Pull request by kunalspathak**
1. The register that was assigned previously to a `copyReg` scenario where not recorded as live at the location because of which we were reassigning it to a different variable, overwriting its value before consuming it for copy. This relates to my findings in https://github.com/dotnet/runtime/issues/84696#issuecomment-1509493749. 
2. When we generate code for upper vector restore, we were generating it at the use where `FIELD_LIST` is populated. But, between that and the intrinsic node, where it is consumed, there can be any number of nodes (like `GT_CALL`) where the restored upper half vectors can be again wiped off. Make sure to insert the restores just before the use of the `FIELD_LIST` node. This relates to my findings in https://github.com/dotnet/runtime/issues/84696#issuecomment-1507926682.
3. There are numerous scenarios in which constraining the number of registers doesn't work with the consecutive registers because consecutive registers, itself constraints the registers that can be assigned. As such, I have added `isLiveAtConsecutiveRegistersLoc` and we will skip constraining the registers for such refpositions. However, to stress test the busy consecutive registers and free/busy code path, I have added a constraint on free registers that the algorithm sees under stress mode.

Fixes: #84747, #84696, #84746

### CODE REVIEW

**Comment by kunalspathak** [comment]
All the CI legs are passing. There is failures on x64 for which I have opened https://github.com/dotnet/runtime/issues/84961. There are failures in `JIT/IL_Conformance/Old/Conformance_Base/` for arm64 which are unlikely to be affected by this change. I have started a run for `jitstress` on main just to confirm it is not related.

**Comment by kunalspathak** [comment]
> I have started a run for `jitstress` on main just to confirm it is not related.

They are on main as well. Opened https://github.com/dotnet/runtime/issues/84966.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @BruceForstall

File: src/coreclr/jit/lsra.h [hunk 1]
```diff
@@ -1416,7 +1416,7 @@ class LinearScan : public LinearScanInterface
         }
         return nextConsecutiveRefPositionMap;
     }
-    FORCEINLINE RefPosition* getNextConsecutiveRefPosition(RefPosition* refPosition);
+    RefPosition* getNextConsecutiveRefPosition(RefPosition* refPosition);
```
Comment (kunalspathak) [inline src/coreclr/jit/lsra.h:1419]: This change should be reverted. I was trying out something for which I had to remove the `FORCEINLINE`, but I didn't made that change and hence no need to change this.

File: src/coreclr/jit/lsraarm64.cpp [hunk 2]
```diff
@@ -1802,6 +1811,45 @@ int LinearScan::BuildConsecutiveRegistersForUse(GenTree* treeNode, GenTree* rmwN
...
+//    of registers will be busy. For RefTypeUse, it will just see if the nodeLocation
+//    matches with the tracking `consecutiveRegistersLocation`. For Def, it will check
+//    the underlying `GenTree*` to see if the tree that produced it had consecutive
+//    registers requirement.
+//
+//
+// Arguments:
+//    consecutiveRegistersLocation - The most recent location where consecutive
+//     registers were needed.
+//
```
Comment (kunalspathak) [inline src/coreclr/jit/lsraarm64.cpp:1829]: Need to add `Return` in summary docs.

**Comment by kunalspathak** [comment]
ping @BruceForstall

**Comment by kunalspathak** [comment]
Adding the links for green runs : 
[jitstress2-jitstressregs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=242167&view=results) , [jitstressregs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=242168&view=results) and [jitstress](https://dev.azure.com/dnceng-public/public/_build/results?buildId=240576&view=results)

File: src/coreclr/jit/lsra.h [hunk 3]
```diff
@@ -1784,6 +1784,12 @@ class LinearScan : public LinearScanInterface
     void clearSpillCost(regNumber reg, var_types regType);
     void updateSpillCost(regNumber reg, Interval* interval);
 
+    FORCEINLINE void updateRegsFreeBusyState(RefPosition& refPosition,
```
Comment (BruceForstall) [inline src/coreclr/jit/lsra.h:1787]: Is it really necessary to use FORCEINLINE?

File: src/coreclr/jit/lsraarm64.cpp [hunk 4]
```diff
@@ -417,6 +417,15 @@ regMaskTP LinearScan::getConsecutiveCandidates(regMaskTP    allCandidates,
     assert(refPosition->isFirstRefPositionOfConsecutiveRegisters());
     regMaskTP freeCandidates = allCandidates & m_AvailableRegs;
 
+#ifdef DEBUG
+    if (getStressLimitRegs() != LSRA_LIMIT_NONE)
+    {
+        // For stress, make only alternate registers available so we can stress the selectoin of free/busy registers.
```
Comment (BruceForstall) [inline src/coreclr/jit/lsraarm64.cpp:423]: nit
```suggestion
        // For stress, make only alternate registers available so we can stress the selection of free/busy registers.
```

File: src/coreclr/jit/lsrabuild.cpp [hunk 5]
```diff
@@ -1864,16 +1871,45 @@ void LinearScan::buildRefPositionsForNode(GenTree* tree, LsraLocation currentLoc
...
+#ifdef TARGET_ARM64
+                    RefPosition* defRefPos = interval->firstRefPosition;
+                    assert(defRefPos->treeNode != nullptr);
+                    if (defRefPos->isLiveAtConsecutiveRegistersLoc(consecutiveRegistersLocation))
+                    {
+                        // If a method has consecutive registers and we are assigning to use refPosition whose
+                        // definition was from a location that has consecutive registers, skip the limit stress for
+                        // them,
+                        // because there are high chances that many registers are busy for consecutive requirements and
+                        // marked as "delayRegFree" state. We do not have enough remaining for other refpositions.
```
Comment (BruceForstall) [inline src/coreclr/jit/lsrabuild.cpp:1902]: nit: some odd formatting, probably because jit-format wrapped the text for you

File: src/coreclr/jit/lsra.cpp [hunk 6]
```diff
@@ -363,6 +363,50 @@ void LinearScan::updateSpillCost(regNumber reg, Interval* interval)
...
+//------------------------------------------------------------------------
+// updateRegsFreeBusyState: Update various register masks and global state to track
+//   registers that are free and busy.
+//
+// Arguments:
+//    refPosition -
+//    assignedRegMask -
+//    copyRegMask -
+//    regsToFree -
+//    delayRegsToFree -
```
Comment (BruceForstall) [inline src/coreclr/jit/lsra.cpp:375]: Would be good to document these

**Review by BruceForstall — APPROVED** [review]

File: src/coreclr/jit/lsra.h (hunk 3 above)
Comment (kunalspathak) [reply src/coreclr/jit/lsra.h:1787]: This is hot functionality used whenever we assign copyRegs with or without consecutive registers. I didn't want to impact the TP for just extracting out this functionality in a method.
