### PR TITLE
[HTTP] Fix new header test

### LINKED ISSUE #117198: `SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException` fails with QUIC protocol error
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082667&view=results
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["Sub-string not found", "SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082667
**Error message validated:** `[Sub-string not found SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/1/2025 2:05:19 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1083776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083776)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest_Http3.SendAsync_ReuseRequestInHandler_ResetsHeadersForEachReuse](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083776&view=ms.vss-test-web.build-test-results-tab&runId=29491730&resultId=157764)||
|[1083778](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083778)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083778&view=ms.vss-test-web.build-test-results-tab&runId=29490784&resultId=228626)||
|[1083739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083739)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083739&view=ms.vss-test-web.build-test-results-tab&runId=29489820&resultId=227451)|dotnet/runtime#117234|
|[1083690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083690)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1083690&view=ms.vss-test-web.build-test-results-tab&runId=29485830&resultId=227214)|dotnet/runtime#116901|
|[1082667](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082667)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082667&view=ms.vss-test-web.build-test-results-tab&runId=29453036&resultId=227050)|dotnet/runtime#117051|
|[1081986](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081986)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081986&view=ms.vss-test-web.build-test-results-tab&runId=29435164&resultId=228358)|dotnet/runtime#117154|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|6|6|

### PR DESCRIPTION
**Pull request by ManickaP**
Use loopback server since some of the validation happens when serializing to the wire which is after establishing the connection.

Fixes #117198

Compare without whitespace.

### CODE REVIEW

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs [hunk 1]
```diff
@@ -2172,56 +2172,68 @@ public async Task SendAsync_InvalidRequestUri_Throws()
...
+                    {
+                        var hrex = Assert.IsType<HttpRequestException>(ex);
+                        var message = UseVersion == HttpVersion30 ? hrex.InnerException.Message : hrex.Message;
+                        Assert.Contains("ASCII", message);
+                    }
                 }
-                else
+            }, async server =>
+            {
+                if (await acceptConnection.Task)
```
Comment (MihaZupan) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:2233]:
```suggestion
                if (await acceptConnection.Task.WaitAsync(TestHelper.PassingTestTimeout))
```
Edit: or maybe it doesn't matter here since the client side would have failed in that case anyway

**Review by MihaZupan — APPROVED** [review]
Thanks

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs (hunk 1 above)
Comment (CarnaViire) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:2233]: LoopbackServerFactory.CreateClientAndServerAsync also have some default timeout I think?

UPD: yes
https://github.com/dotnet/runtime/blob/02a38a68b4aba4b69d6c349b944084b861a560b6/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs#L37
https://github.com/dotnet/runtime/blob/02a38a68b4aba4b69d6c349b944084b861a560b6/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs#L26

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs [hunk 2]
```diff
@@ -2172,56 +2172,68 @@ public async Task SendAsync_InvalidRequestUri_Throws()
...
         public async Task SendAsync_RequestWithDangerousControlHeaderValue_ThrowsHttpRequestException(char dangerousChar, HeaderType headerType)
         {
-            string uri = "https://example.com"; // URI doesn't matter, the request should never leave the client
-            var handler = CreateHttpClientHandler();
+            TaskCompletionSource<bool> acceptConnection = new TaskCompletionSource<bool>();
 
-            var request = new HttpRequestMessage(HttpMethod.Get, uri);
-            request.Version = UseVersion;
-            try
+            await LoopbackServerFactory.CreateClientAndServerAsync(async uri =>
```
Comment (CarnaViire) [inline src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:2177]: Nit you can disregard: this could be

```diff
-       public async Task SendAsync_RequestWithDangerous....
+       public Task SendAsync_RequestWithDangerous....
        {
            ...
-           await LoopbackServerFactory.CreateClientAndServerAsync(...
+           return LoopbackServerFactory.CreateClientAndServerAsync(...
```

**Review by CarnaViire — APPROVED** [review]
LGTM, thanks

File: src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs (hunk 2 above)
Comment (ManickaP) [reply src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:2177]: Almost all occurrences of `LoopbackServerFactory.CreateClientAndServerAsync` are with `await`, even in cases where your suggestion could be also applied. So for this reason I'll keep it as-is.
