### PR TITLE
[Profiler] Avoid Recursive ThreadStoreLock in Profiling Thread Enumerator

### LINKED ISSUE #110062: Deadlock in GC when attached profiler calls ICorProfilerInfo4::EnumThreads using .NET9 runtime
### Description

Background: I am member of team responsible for maintaining a closed source .net profiler

Issue: I am currently working on validating .NET9 with profiler and while running regression tests, I've observed process stall when using .NET9 runtime with the profiler attached.

Root Cause: I've managed to narrow down the cause of the issue to an invocation of  `ICorProfilerInfo4::EnumThreads` within our profiler's overridden  `ICorProfilerCallback::RuntimeSuspendFinished` method, which I'll share in the 'actual behavior' form

### Reproduction Steps

In profiler dll project have class:
`class ProfilerCallback : public ICorProfilerCallback5
{
    public:
    virtual COM_METHOD(HRESULT) Initialize(IUnknown* pICorProfilerInfoUnk)
    {
        return  pICorProfilerInfoUnk->QueryInterface(IID_ICorProfilerInfo8, (void**)&m_pProfilerInfo);
    }

    COM_METHOD(HRESULT) RuntimeSuspendFinished()
    {
        ICorProfilerThreadEnum* threadEnum = nullptr;
        HRESULT enumThreadsHR = m_pProfilerInfo->EnumThreads(&threadEnum);
        threadEnum->Release();
        return enumThreadsHR;
    }
    ICorProfilerInfo8* m_pProfilerInfo = nullptr;
};
`

Attach as profiler this (using [guide](https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/profiling-overview)
Run and observe process stall/deadlock after `RuntimeSuspendFinished` is called

### Expected behavior

Process should not deadlock

### Actual behavior

Process deadlocks

This is the chain of calls that leads to a deadlock:
1. Inside `RuntimeSuspendFinished`, `EnumThreads` is called
2. Via `StateHolder` destructor in `ProfilerThreadEnum::Init`, `ThreadStore::s_pThreadStore->m_HoldingThread` is set to NULL
3. `RuntimeSuspendFinished` returns 
4. `WKS::GCHeap::GarbageCollectGeneration` is called which then calls `Thread::RareDisablePreemptiveGC`
5. Where there is a call made to `ThreadStore::HoldingThreadStore` will return true as `m_HoldingThread` == NULL, which avoids early exit from `Thread::RareDisablePreemptiveGC`
6. Later on a call to `GCHeapUtilities::GetGCHeap()->WaitUntilGCComplete()` is made which will deadlock as `GCHeap::SetWaitForGCEvent()` hasn't been called yet by `ThreadSuspend::RestartEE`

Below are the relevant stack traces:

Resetting holding thread:
`coreclr.dll!ThreadSuspend::UnlockThreadStore(int bThreadDestroyed, ThreadSuspend::SUSPEND_REASON) Line 1934	C++
 	[Inline Frame] coreclr.dll!ThreadStore::UnlockThreadStore() Line 5110	C++
 	[Inline Frame] coreclr.dll!StateHolder<&ThreadStore::LockThreadStore,&ThreadStore::UnlockThreadStore>::Release() Line 359	C++
 	[Inline Frame] coreclr.dll!StateHolder<&ThreadStore::LockThreadStore,&ThreadStore::UnlockThreadStore>::{dtor}() Line 340	C++
 	coreclr.dll!ProfilerThreadEnum::Init() Line 585	C++
 	coreclr.dll!ProfToEEInterfaceImpl::EnumThreads(ICorProfilerThreadEnum * * ppEnum) Line 10366	C++
 	CoreRewriter_x64.dll!ProfilerCallback::RuntimeSuspendFinished() Line 2417	C++
 	coreclr.dll!EEToProfInterfaceImpl::RuntimeSuspendFinished() Line 5056	C++
 	coreclr.dll!ProfControlBlock::DoProfilerCallbackHelper<int (__cdecl*)(ProfilerInfo *),long (__cdecl*)(EEToProfInterfaceImpl *)>(ProfilerInfo * pProfilerInfo, int(*)(ProfilerInfo *) condition, HRESULT(*)(EEToProfInterfaceImpl *) callback, HRESULT * pHR) Line 284	C++
 	coreclr.dll!ThreadSuspend::SuspendEE(ThreadSuspend::SUSPEND_REASON reason) Line 5647	C++
 	coreclr.dll!GCToEEInterface::SuspendEE(SUSPEND_REASON reason) Line 51	C++
 	coreclr.dll!WKS::GCHeap::GarbageCollectGeneration(unsigned int gen, gc_reason reason) Line 51030	C++`

Checking null holding thread:
`coreclr.dll!ThreadStore::HoldingThreadStore(Thread * pThread) Line 7624	C++
 	coreclr.dll!Thread::RareDisablePreemptiveGC() Line 2123	C++
 	[Inline Frame] coreclr.dll!WKS::gc_heap::disable_preemptive(bool) Line 1683	C++
 	coreclr.dll!WKS::GCHeap::GarbageCollectGeneration(unsigned int gen, gc_reason reason) Line 51031	C++`

Deadlock:
` coreclr.dll!WKS::GCHeap::WaitUntilGCComplete(bool bConsiderGCStart) Line 238	C++
 	coreclr.dll!Thread::RareDisablePreemptiveGC() Line 2212	C++
 	[Inline Frame] coreclr.dll!WKS::gc_heap::disable_preemptive(bool) Line 1683	C++
 	coreclr.dll!WKS::GCHeap::GarbageCollectGeneration(unsigned int gen, gc_reason reason) Line 51031	C++`

### Regression?

We have not encountered this GC deadlock in .NET8 and presumably earlier

### Known Workarounds

I haven't tried it yet but there's probably some way to force `ThreadStore::s_pThreadStore->m_HoldingThread` into it's previous correct state after calling `EnumThreads`

### Configuration

.NET: 9.0.100

`
Processor	13th Gen Intel(R) Core(TM) i9-13900H   2.60 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor
`
This has also been replicated on build server. I am not aware of the specs for it.

### Other information

[this](https://github.com/dotnet/runtime/blob/c31bb93ea3ca685b6336cd0cbde4893dff30f80c/src/coreclr/vm/profilingenumerators.cpp#L557) line causes `ThreadStore::s_pThreadStore->m_HoldingThread` to be set to NULL which has knock-on effects later on which lead to a deadlock.

I have minidumps, but they're pretty large to upload, so let me know if there is any way I can send them

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes https://github.com/dotnet/runtime/issues/110062

Profiling Enumerators look to acquire the ThreadStoreLock.
In release config, re-acquiring the ThreadStoreLock and releasing it in ProfilerThreadEnum::Init will cause problems if the callback invoking EnumThread has logic that depends on the ThreadStoreLock being held.
For example, invoking `EnumThread` within `RuntimeSuspendFinished` will violate the [expectation that the ThreadStoreLock is held until RestartEE is called](https://github.com/dotnet/runtime/blob/2d6ea8de12a9f1aad9724a911d201137e5339c4b/src/coreclr/vm/threadsuspend.cpp#L5556-L5559), demonstrated in https://github.com/dotnet/runtime/issues/110062

This PR aims to avoid recursively acquiring the ThreadStoreLock by expanding the known scnearios where the profiling thread enumerator shouldn't acquire the ThreadStoreLock.

### CODE REVIEW

**Comment by jkotas** [comment]
Do we need a test for this?

File: src/coreclr/vm/profilingenumerators.cpp [hunk 1]
```diff
@@ -552,9 +552,11 @@ HRESULT ProfilerThreadEnum::Init()
     }
     CONTRACTL_END;
 
+    // If EnumThreads is called from a profiler callback where the runtime is already suspended,
+    // don't recursively acquire/release the ThreadStore Lock.
     // If a profiler has requested that the runtime suspend to do stack snapshots, it
     // will be holding the ThreadStore lock already
-    ThreadStoreLockHolder tsLock(!g_profControlBlock.fProfilerRequestedRuntimeSuspend);
+    ThreadStoreLockHolder tsLock(!GCHeapUtilities::IsGCInProgress() && !g_profControlBlock.fProfilerRequestedRuntimeSuspend);
```
Comment (VSadov) [inline src/coreclr/vm/profilingenumerators.cpp:559]: If the intent is to not acquire thread store lock second time, then this should check if the current thread is already holding the thread store lock. 

GC could be started by other thread and GC may be changing the thread list (for example starting or background threads). 
If current thread is not holding a thread store lock, it should acquire it before iterating through thread list.

Comment (VSadov) [inline src/coreclr/vm/profilingenumerators.cpp:559]:
```suggestion
    ThreadStoreLockHolder tsLock(!ThreadStore::HoldingThreadStore() && !g_profControlBlock.fProfilerRequestedRuntimeSuspend);
```

Comment (VSadov) [reply src/coreclr/vm/profilingenumerators.cpp:559]: I've also looked at uses of `fProfilerRequestedRuntimeSuspend` and I think there are couple races around setting and clearing this flag.

The flag should be set _after_ the profiler succeeded at suspending the runtime, not before. 
https://github.com/dotnet/runtime/blob/016d356e43659b7789d23defe570628c8864ee73/src/coreclr/vm/proftoeeinterfaceimpl.cpp#L6838-L6839

And the flag should be cleared _before_ resuming the runtime, not after. 
Otherwise if resuming thread is preempted right after it resumes the runtime, the flag could stay set for a very long time, while the threadstore is no longer owned by the profiler.
https://github.com/dotnet/runtime/blob/016d356e43659b7789d23defe570628c8864ee73/src/coreclr/vm/proftoeeinterfaceimpl.cpp#L6877-L6878

Perhaps fix these races in the same change?

Comment (mdh1418) [reply src/coreclr/vm/profilingenumerators.cpp:559]: Thanks for pointing that out! I was mainly looking to not acquire the thread store lock a second time. Will change to `ThreadStore::HoldingThreadStore()`

Comment (mdh1418) [reply src/coreclr/vm/profilingenumerators.cpp:559]: I can swap the order in which `fProfilerRequestedRuntimeSuspend` is set. I don't think we have anything testing its behavior very well. Wouldn't setting the flag after `SuspendEE` returns also mean that any callback during `SuspendEE` wouldn't see that it was a profiler requested suspend? (which would be fine for this scenario as it would see that the ThreadStoreLock was already acquired)

Comment (VSadov) [reply src/coreclr/vm/profilingenumerators.cpp]: > Wouldn't setting the flag after SuspendEE returns also mean that any callback during SuspendEE wouldn't see that it was a profiler requested suspend?

I think until the suspend succeeded, it is not useful for other threads to know that profiler is trying to do it. At least not as a way to tell if it is safe to iterate the thread list. 
For the thread that is performing the suspension checking if it holds the lock is a more direct way to tell when it is ok to iterate. 

Perhaps we have other reasons why the order does not matter, but setting the flag before holding the lock seems at best confusing.

Comment (davmason) [reply src/coreclr/vm/profilingenumerators.cpp]: It shouldn't matter to change the order. The only impact I can think of is that a profiler might get an error for a thread that has just been suspended, but a profiler should be calling SuspendRuntime and only starting sampling once that method has returned.

**Review by davmason — APPROVED** [review]
LGTM

File: src/coreclr/vm/profilingenumerators.cpp (hunk 1 above)
Comment (mdh1418) [reply src/coreclr/vm/profilingenumerators.cpp]: Updated and swapped the order!

**Comment by mdh1418** [comment]
Given that this test should run quickly when it passes, and its expected failure case is when it hangs/deadlocks, is there a straightforward way to set a quick timeout for this test instead of hitting CI's timeouts? And is there a way to hit such a timeout in a local run via corerun? @davmason @jkotas

**Comment by davmason** [comment]
The problem with timeouts is you can't check them in because we run a lot of tests in various modes (GCStress, JITStress, etc) that can make them take 10+ minutes. For this kind of thing what I have done in the past is make the timeout short locally and run it in a loop on your dev machine to build confidence, but leave the timeout unchanged in the tree.
