### PR TITLE
Fix build script on ARM Linux builds

### LINKED ISSUE #44929: Building on Linux ARM using a compiler causes an "unbound variable" shell script error for "arch"
The issue is that arch is not defined for linux builds, only host and build architectures.

### PR DESCRIPTION
**Pull request by SleepyDweams**
On ARM Linux distros that are not Android, the error "unbound variable" occurs as the "arch" variable is not assigned to, even though every other script path assigns a value to arch. For this reason, I changed the script so that arch is assigned on all possible paths, so that building on ARM Linux distros is possible.

Fixes #44929

### CODE REVIEW

File: eng/native/init-os-and-arch.sh [hunk 1]
```diff
@@ -56,9 +56,11 @@ case "$CPUName" in
         if (NAME=""; . /etc/os-release; test "$NAME" = "Tizen"); then
             __BuildArch=armel
             __HostArch=armel
```
Comment (am11) [inline eng/native/init-os-and-arch.sh:58]: nit: `__BuildArch` and `__HostArch` here and below are redundant and can be removed. We are overwriting them unconditionally in `build-commons.sh`.

Comment (PokeCodec) [reply eng/native/init-os-and-arch.sh]: Thank you!

**Review by janvorli — APPROVED** [review]
LGTM, thank you for fixing the problem!

**Comment by PokeCodec** [comment]
@janvorli any updates? Anyone I need to reach out to?

**Comment by janvorli** [comment]
@PokeCodec I was waiting for you completing the changes. I've noticed you've kept force pushing changes, so I have thought you are still working on it.

**Comment by PokeCodec** [comment]
I apologize for that. I needed to ensure no merge conflicts. I am done with this fix.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by janvorli** [comment]
@PokeCodec I can see you keep pushing commits to this change. I guess the reason is to re-trigger the CI tests to get a clean run. Please let me restart the failed legs only for you instead.

**Comment by PokeCodec** [comment]
Alright. Thank you!

**Comment by ViktorHofer** [comment]
@janvorli @am11 do you believe the PR is ready? :)

**Comment by SleepyDweams** [comment]
It certainly is!

**Comment by ViktorHofer** [comment]
Merging, as @janvorli already approved.
