### PR TITLE
Keep blittable layout class In/Out by default

### LINKED ISSUE #50410: [6.0.100-preview.4.21178.2] Package LibGit2Sharp not working with 6.0.100-preview.4.21178.2
**Application Name:** 3 Global tools (git-istage, github-issues-cli, GitVersion.Tool)
**Apps failed by package:** [https://github.com/libgit2/libgit2sharp](https://github.com/libgit2/libgit2sharp)
**OS:** Windows 10 RS5
**CPU:** X64.NET Build Number: main branch - 6.0.100-preview.4.21178.2
**DevDiv bug**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1303009
**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build  6.0.100-preview.4.21178.2: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-preview.2.21158.2: Pass
3). Windows 10 RS5 X64 + .NET Core SDK build 5.0.104 : Pass
4). Windows 10 RS5 X64 + .NET Core SDK build 3.1.300 Pass

**Repro steps to run**
1) Create a .net core console app
2) Add `<PackageReference Include="LibGit2Sharp" Version="0.26.2" />`
3) In Program.cs
```
     var p = Repository.Discover(@"PROJECT PATH WITH GIT FOLDER");
     Console.WriteLine(p);
```

**Expected Result:**
Should return git folder path for the given project

**Actual Result:**
Returns empty string

**Findings**
We think, it doesn't load native git library : git2-106a5f2.dll, it causes this issue.
.NET 6 SDK 6.0.100-preview.4.21178.2 breaks the package LibGit2Sharp and caused 3 global tools failed in AppCompat lab,

@dotnet-actwx-bot @dotnet/compat

### PR DESCRIPTION
**Pull request by elinor-fung**
cc @jkoritzinsky @AaronRobinsonMSFT 

Fixes #50410

### CODE REVIEW

File: src/coreclr/vm/mlinfo.cpp [hunk 1]
```diff
@@ -2372,10 +2372,16 @@ MarshalInfo::MarshalInfo(Module* pModule,
             }
         }
 
-        // If neither IN nor OUT are true, this signals the URT to use the default
-        // rules.
-        if (!m_in && !m_out)
+        if (alwaysInOut)
```
Comment (jkoritzinsky) [inline src/coreclr/vm/mlinfo.cpp:2375]: I think this should only be for non-byref cases.

**Review by jkoritzinsky — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by elinor-fung** [comment]
Bah, it looks like we have a bug and test gap with handling `null`.

Before this and #50137, passing null to this p/invoke worked:
```C#
[StructLayout(LayoutKind.Sequential)]
internal class TestClass
{
    public int i;
}

[DllImport("NativeLib", CallingConvention = CallingConvention.Cdecl)]
public static extern void update_test_class([In][Out] TestClass c);
```
Now, it fails with a null ref exception trying to call `Object.GetType()`. With #50137 but without this change, it would only fail if `[Out]` is specified. With this change, it fails without `[Out]` since this change made that the default.
