### PR TITLE
Do not promote struct locals with holes

### LINKED ISSUE #62597: Explicit struct size is not always taken into account in code emitted at runtime
### Description

After updating from .NET 5 to .NET 6, our code started to fail in a very specific code path. It _looks like_ a case where the `StructLayoutAttribute.Size` field is not taken into account in code emitted at runtime, although I'm not sure if that's the root cause.

The problem only reproduces under Linux with optimizations enabled.

### Reproduction Steps

The following program exhibits the issue:

```C#
using System;
using System.Reflection.Emit;
using System.Runtime.InteropServices;
using System.Text;

namespace ConsoleApp;

[StructLayout(LayoutKind.Explicit, Size = 32)]
public readonly unsafe struct SmallString
{
    [FieldOffset(0)] private readonly byte _length;
    [FieldOffset(1)] private readonly byte _firstByte;

    public SmallString(string value)
    {
        fixed (char* srcPtr = value)
        fixed (byte* destPtr = &_firstByte)
        {
            Encoding.ASCII.GetBytes(srcPtr, value.Length, destPtr, value.Length);
        }

        _length = (byte)value.Length;
    }

    public string Dump()
    {
        fixed (byte* ptr = &_firstByte)
        {
            return $"{BitConverter.ToString(new ReadOnlySpan<byte>(ptr, _length).ToArray())}: {Encoding.ASCII.GetString(ptr, _length)}";
        }
    }
}

public static class Program
{
    public static void Main()
    {
        var value = new SmallString("foobar");
        Execute(value);

        var method = new DynamicMethod("test", typeof(void), new[] { typeof(SmallString) }, typeof(Program), true);
        var il = method.GetILGenerator();
        il.Emit(OpCodes.Ldarg_0);
        il.EmitCall(OpCodes.Call, typeof(Program).GetMethod("Execute")!, null);
        il.Emit(OpCodes.Pop);
        il.Emit(OpCodes.Ret);

        var action = (Action<SmallString>)method.CreateDelegate(typeof(Action<SmallString>));
        action.Invoke(value);
    }

    public static object Execute(SmallString foo)
    {
        Console.WriteLine(foo.Dump());
        return new StringBuilder();
    }
}
```

The project file is fairly standard:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
```

### Expected behavior

The program is supposed to print the following:

```
$ dotnet run -c Release
66-6F-6F-62-61-72: foobar
66-6F-6F-62-61-72: foobar
```

It basically calls `Execute(value)` directly, then through a dynamic method. Both outputs should be the same.

### Actual behavior

When run under **Linux x64** in **Release** mode, the following output is produced:

```
$ dotnet run -c Release
66-6F-6F-62-61-72: foobar
66-00-00-00-00-00: f
```

The program produces the correct output in Debug mode, or under Windows in both Debug and Release.

Note that the part that is zeroed out corresponds to the part of the struct that is not covered by fields. The `f` is not zeroed out since it is stored in the `_firstByte` field.

FYI, I have observed bytes other than `00` following the `f` in our real code. An example output string would be `fÿÚ,\u007f\u0000`, but this repro only seems to output zeros though.

### Regression?

This worked fine under .NET 5. The repro code does not exhibit the issue when recompiled for net5.0.

### Known Workarounds

Adding the following field to `SmallString` fixes the issue:

```C#
[FieldOffset(31)] private readonly byte _lastByte;
```

But then, even other small changes to the repro code make the issue go away...

### Configuration

The issue reproduces on Linux in x64.

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
```

Windows on x64 does not exhibit the behavior. I haven't tested other configurations.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by kunalspathak**
In #43870 , when we added more support for multireg args, we added a check for struct's field count. We didn't check if the total size of struct matched the combined size of both the fields. That led us to generate code that partially copy the struct fields on stack when passing as arguments. Add an explicit check to verify the combined size matches.

Fixes: #62597

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/lclvars.cpp [hunk 1]
```diff
@@ -2045,8 +2045,21 @@ bool Compiler::StructPromotionHelper::ShouldPromoteStructVar(unsigned lclNum)
         // multiple registers?
         if (compiler->lvaIsMultiregStruct(varDsc, compiler->info.compIsVarArgs))
         {
-            if ((structPromotionInfo.fieldCnt != 2) &&
-                !((structPromotionInfo.fieldCnt == 1) && varTypeIsSIMD(structPromotionInfo.fields[0].fldType)))
+            if (structPromotionInfo.fieldCnt == 2)
+            {
+                unsigned structSize = varDsc->GetLayout()->GetSize();
+                if (structPromotionInfo.fields[0].fldSize * 2 != structSize)
```
Comment (BruceForstall) [inline src/coreclr/jit/lclvars.cpp:2051]: Wouldn't this be better and more general?
```suggestion
                if (structPromotionInfo.containsHoles)
```

(e.g., why `*2` instead of `fields[0].fldSize + fields[1].fldSize`?)

Seems like the next condition maybe should also check `containsHoles` in case there's an explicit layout struct of a single SIMD field where the explicit layout is larger than the SIMD field

**Review by BruceForstall — CHANGES_REQUESTED** [review]

File: src/coreclr/jit/lclvars.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/lclvars.cpp:2051]: Ah, I actually had `fields[0].fldSize + fields[1].fldSize` but somehow I didn't push that change. Let me do it.

**Comment by AndyAyersMS** [comment]
Is there some easy way to repro this without generating IL at runtime? 

Dynamic methods bypass tiering (and thus OSR/PGO) and so we won't get as much coverage as we would from a source example.

File: src/coreclr/jit/lclvars.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/lclvars.cpp:2051]: Looking at the code around, `containsHoles` does exactly that, so I should just replace this check with `containHoles`. Perhaps I should also add a check for `customLayout` the way it is done here:

https://github.com/dotnet/runtime/blob/7dcb2892c11d4ab66ba72b767783231e699b28f3/src/coreclr/jit/lclvars.cpp#L2018-L2021

**Comment by kunalspathak** [comment]
> Is there some easy way to repro this without generating IL at runtime?

I will try to find out.

File: src/coreclr/jit/lclvars.cpp (hunk 1 above)
Comment (BruceForstall) [reply src/coreclr/jit/lclvars.cpp:2051]: Yes, probably should add `&& structPromotionInfo.customLayout` as well. I think the logic here is: a default/automatic struct layout might end up with holes due to alignment padding, but users can't depend on values in that padding. However, if the user explicitly set a custom/explicit layout, then we can't depend on the padding/holes being uninteresting.

**Review by BruceForstall — APPROVED** [review]
LGTM

Any asm diffs?

Presumably this is a back-port candidate

**Comment by kunalspathak** [comment]
> Any asm diffs?

I will post the result once the asmdiff pipeline completes.

> Presumably this is a back-port candidate

That's right. I will start the process once I see the asmdiffs.

**Comment by kunalspathak** [comment]
asmdiffs results: https://dev.azure.com/dnceng/public/_build/results?buildId=1507589&view=ms.vss-build-web.run-extensions-tab

The worst difference are around 228 bytes in windows/linux arm64. I also inspected diffs from other platforms, and almost all of them are coming because we stop promoting the `DateTimeOffset` struct. So the code changes are related to `_offsetMinutes` and `_offsetMinutes` as they are passed in memory now.

https://github.com/dotnet/runtime/blob/06bb200673f0a4ac37ea49a4aaf6c16be4441a10/src/libraries/System.Private.CoreLib/src/System/DateTimeOffset.cs#L32-L65

**Comment by ltrzesniewski** [comment]
I took a quick glance at the code to better understand what's going on, and I noticed something: a comment in `ShouldPromoteStructVar` says: We *can* promote; *should* we promote?
Shouldn't that case (`structPromotionInfo.containsHoles && structPromotionInfo.customLayout`) always mean we can't promote? So shouldn't it be checked in `CanPromoteStructVar` or even in `CanPromoteStructType` instead?

**Comment by kunalspathak** [comment]
Failures are related to https://github.com/dotnet/runtime/issues/60648, https://github.com/dotnet/runtime/issues/58704 and https://github.com/dotnet/runtime/issues/52361.

**Comment by kunalspathak** [comment]
> I took a quick glance at the code to better understand what's going on, and I noticed something: a comment in `ShouldPromoteStructVar` says: We _can_ promote; _should_ we promote? Shouldn't that case (`structPromotionInfo.containsHoles && structPromotionInfo.customLayout`) always mean we can't promote? So shouldn't it be checked in `CanPromoteStructVar` or even in `CanPromoteStructType` instead?

Your observations are correct @ltrzesniewski. However, currently, the code that checks for "can" and "should" are intermixed and probably we need to separate out some day. I just wanted to have the fix close to the place where we do similar check for "returned struct":

https://github.com/dotnet/runtime/blob/f18f658fff3d4ee103d1858f5d391ab22c2d5ff9/src/coreclr/jit/lclvars.cpp#L2018-L2021
