### PR TITLE
Fix bug introduced by preventing unwind through stack bottom

### LINKED ISSUE #81869: Test failure baseservices/exceptions/regressions/V1/SEH/COOL/rethrow/rethrow.sh
Run: [runtime-coreclr outerloop 20230208.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=164444&view=ms.vss-test-web.build-test-results-tab&runId=3349608&resultId=122389&paneView=debug)

Failed test:
```
coreclr osx arm64 Checked no_tiered_compilation @ OSX.1200.ARM64.Open

- baseservices/exceptions/regressions/V1/SEH/COOL/rethrow/rethrow.sh
- baseservices/exceptions/regressions/V1/SEH/VJ/HandlerException/HandlerException.sh
- Regressions/coreclr/GitHub_45929/test45929/test45929.sh
- Regressions/coreclr/GitHub_45929/test45929/test45929.sh

coreclr osx arm64 Checked @ OSX.1200.ARM64.Open

- baseservices/exceptions/regressions/V1/SEH/VJ/HandlerException/HandlerException.sh
- baseservices/exceptions/regressions/V1/SEH/COOL/rethrow/rethrow.sh
- Regressions/coreclr/GitHub_45929/test45929/test45929.sh
- Regressions/coreclr/GitHub_12224/Test12224/Test12224.sh
```
**Error message:**
```
Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. UserException1+UserException2: Exception of type 'UserException1+UserException2' was thrown.
at UserException1.UserException2.UserException3.UserException4.RethrowException.runtest()
UserException1+UserException2+UserException3: Exception of type 'UserException1+UserException2+UserException3' was thrown.
at UserException1.UserException2.UserException3.UserException4.RethrowException.runtest()UserException1+UserException2+UserException3+UserException4: Exception of type 'UserException1+UserException2+UserException3+UserException4' was thrown.
at UserException1.UserException2.UserException3.UserException4.RethrowException.runtest()
UserException1+UserException2+UserException3: Exception of type 'UserException1+UserException2+UserException3' was thrown.
at UserException1.UserException2.UserException3.UserException4.RethrowException.runtest()
UserException1+UserException2+UserException3+UserException4: Exception of type 'UserException1+UserException2+UserException3+UserException4' was thrown.
at UserException1.UserException2.UserException3.UserException4.RethrowException.runtest()
UserException1+UserException2: Exception of type 'UserException1+UserException2' was thrown.
at UserException1.UserException2.UserException3.UserException4.RethrowException.runtest()

UserException1+UserException2: Exception of type 'UserException1+UserException2' was thrown.
at UserException1.UserException2.UserException3.UserException4.RethrowException.runtest()
[createdump] Invalid process id: task_for_pid(3441) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
[createdump] waitpid() returned successfully (wstatus 0000ff00)
/private/tmp/helix/working/A70708E1/w/AA6908E3/e/baseservices/exceptions/regressions/V1/SEH/COOL/rethrow/rethrow.sh: line 416:  3441 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/A70708E1/w/AA6908E3/uploads/Reports/baseservices.exceptions/regressions/V1/SEH/COOL/rethrow/rethrow.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A70708E1/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false rethrow.dll ''
Exception3 was caught by Thread 2
Exception4 was caught by Thread 3
Exception1 was caught by Thread 0
Exception1 was caught by Thread 4
Exception2 was caught by Thread 1
Exception3 was caught by Thread 6
Exception4 was caught by Thread 7
Exception1 was caught by Thread 8
Exception2 was caught by Thread 9
Exception2 was caught by Thread 5
[createdump] Target process is alive
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 2/8/2023 12:07:14 PM
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A70708E1/p
/private/tmp/helix/working/A70708E1/w/AA6908E3/e/baseservices/exceptions/regressions/V1/SEH/COOL/rethrow/rethrow.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._regressions_V1_SEH_COOL_rethrow_rethrow_._regressions_V1_SEH_COOL_rethrow_rethrow_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by janvorli**
The recent fix to prevent unwinding through stack bottom was incorrect for secondary threads, as it just compared the SP being above the frame of the hosting API. However, other threads can have their stacks anywhere in the memory, thus this sometimes broke exception handling on secondary threads.

I have also found that there was one more case where the unwind through the hosting API need to be checked - the `Thread::VirtualUnwindToFirstManagedCallFrame`.

I have decided to use the return address of the hosting API for the checks instead of the frame address. That makes the check work properly.

Close #81869

### CODE REVIEW

File: src/coreclr/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -4537,7 +4537,7 @@ VOID UnwindManagedExceptionPass2(PAL_SEHException& ex, CONTEXT* unwindStartConte
     EEPOLICY_HANDLE_FATAL_ERROR(COR_E_EXECUTIONENGINE);
 }
 
-extern void* g_hostingApiFrameAddress;
+extern void* g_hostingApiReturnAddress;
```
Comment (jkotas) [inline src/coreclr/vm/exceptionhandling.cpp:4540]: Is it possible for two different threads to call the hosting API in parallel?

Comment (janvorli) [reply src/coreclr/vm/exceptionhandling.cpp:4540]: I don't think that calling coreclr_initialize / coreclr_execute_assembly in parallel from multiple threads would work. I guess it would likely crash somewhere.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/exceptionhandling.cpp (hunk 1 above)
Comment (janvorli) [reply src/coreclr/vm/exceptionhandling.cpp:4540]: Btw, the original version of my previous change was putting the hosting apis into a separate named section. Then I could use linker generated symbols for the section start / end and compare the PC to that without saving any return address etc. However, the section names format and way to get section range is different for macOS / Linux and I wasn't sure about the other Unixes. That made me move to this solution that should work everywhere.

**Comment by jkoritzinsky** [comment]
Will this work if someone has a .NET plugin to their unmanaged app and calls a function pointer to an UnmanagedCallersOnly function from a thread that has never called the nethost APIs or managed code?

**Comment by janvorli** [comment]
One CI failure is a known issue and the other is unrelated to the change - an assert in JIT under crossgen2.
