### PR TITLE
Skip ENOSYS filter in numa init

### LINKED ISSUE #110074: C++ crashes when calling any function in nativeaot shared library
The system developer said it was caused by selinux permissions. Is there a way to bypass this system call?

https://github.com/dotnet/runtime/blob/35f2b1309a6380f1c8e3edfe1589307fd2a3e1d1/src/coreclr/gc/unix/numasupport.cpp#L57

Image

syscall Disassembly:201
NUMASupportInitialize() 0x0000005c8b963458
GCToOSInterface::Initialize() 0x0000005c8b962480
::PalInit() 0x0000005c8b96072c
::RhInitialize(bool) 0x0000005c8b91b1f0
InitializeRuntime() 0x0000005c8b914ebc
Thread::EnsureRuntimeInitialized() 0x0000005c8b91d0e8
Thread::ReversePInvokeAttachOrTrapThread(ReversePInvokeFrame*) 0x0000005c8b91d094
libavalonia_Entry_napi_init__RegisterEntryModule napi_init.cs:12
::RegisterAvaloniaNativeModule() napi_init.cpp:16

### PR DESCRIPTION
**Pull request by am11**
The usage of `get_mempolicy` is restricted by secomp profile in docker. I couldn't figure out way to repro it with SELinux (class labels are confusing), but docker approach is fine.

It was fixed in libnuma a few days ago https://github.com/numactl/numactl/commit/0efea0eb1980964c3264c901ec4e8934c4c05541 so it's not a huge issue.

Fix https://github.com/dotnet/runtime/issues/110074

### CODE REVIEW

File: src/coreclr/gc/unix/numasupport.cpp [hunk 1]
```diff
@@ -54,7 +54,7 @@ static int GetNodeNum(const char* path, bool firstOnly)
 void NUMASupportInitialize()
 {
 #ifdef TARGET_LINUX
-    if (syscall(__NR_get_mempolicy, NULL, NULL, 0, 0, 0) < 0 && errno == ENOSYS)
+    if (syscall(__NR_get_mempolicy, NULL, NULL, 0, 0, 0) < 0 && (errno == ENOSYS || errno == EPERM))
```
Comment (am11) [inline src/coreclr/gc/unix/numasupport.cpp:57]: @janvorli, an alternative was to drop && errno filter and just return for `< 0`. What do you think?
```suggestion
    if (syscall(__NR_get_mempolicy, NULL, NULL, 0, 0, 0) < 0)
```

Comment (janvorli) [reply src/coreclr/gc/unix/numasupport.cpp:57]: I am fine with both ways, but maybe I'd slightly prefer not checking the errno at all as it would be more future proof.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by janvorli** [comment]
Actually, I am not sure if it is causing the crash in the #110074. The rest of the code in the function should still work and not crash. Since that crash happens on HarmonyOS, I wonder if the crash could occur in the syscall itself due to mishandling of the `mode` argument being NULL.

**Comment by am11** [comment]
I was trying to repro it on Fedora VM with SELinux enabled, that `operation not permitted` is a bit tricky to reproduce since there is no class label for syscall (https://selinuxproject.org/page/ObjectClassesPerms#Kernel_Object_Classes) any my experiments were failing. With seccomp `CAP_SYS_NICE`, it's possible to make `get_mempolicy` syscall fail with `EPERM`. This change itself is aligning with the recent libnuma behavior. Also, from syscall(2) manpage:
> ENOSYS The requested system call number is not implemented. Other errors are specific to the invoked system call.

**Comment by am11** [comment]
I was trying to repro it on Fedora VM with SELinux enabled, that `operation not permitted` is a bit tricky to reproduce since there is no class label for syscall (https://selinuxproject.org/page/ObjectClassesPerms#Kernel_Object_Classes) and my experiments were failing. With seccomp `CAP_SYS_NICE`, it's possible to make `get_mempolicy` syscall fail with `EPERM`. This change itself is aligning with the recent libnuma behavior. Also, from syscall(2) manpage:
> ENOSYS The requested system call number is not implemented. Other errors are specific to the invoked system call.
