### PR TITLE
Fix Globalization Invariant string comparisons with ordinal ignore casing

### LINKED ISSUE #89591: string Equals and IndexOf with OrdinalIgnoreCase don't agree under InvariantGlobalization
### Description

Ran into this one while fuzzing the `SearchValues<string>` implementation (#88394).

### Reproduction Steps

Run with `InvariantGlobalization`:

```c#
string haystack = "\u0261"; // Latin Small Letter Script G
string needle   = "\uA7AC"; // Latin Capital Letter Script G

Console.WriteLine(haystack.Equals(needle, StringComparison.OrdinalIgnoreCase));  // False
Console.WriteLine(haystack.IndexOf(needle, StringComparison.OrdinalIgnoreCase)); // 0
```

### Expected behavior

If two strings are not equal under `OrdinalIgnoreCase`, `IndexOf` shouldn't be 0.
Or if `IndexOf` is 0, `StartsWith` should report `true`.

### Actual behavior

When running under `InvariantGlobalization`, `IndexOf` may find a match when `Equals`/`StartsWith` don't.

### Regression?

I can reproduce this with .NET 6, 7, and 8 with the `InvariantGlobalization` flag.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

When not under `Invariant` mode, the above example evaluates to `True, 0`.

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/89591

### CODE REVIEW

File: src/libraries/System.Globalization/tests/Invariant/InvariantMode.cs [hunk 1]
```diff
@@ -1206,6 +1206,41 @@ public void TestCultureInfo_Ctor_Int32_ReturnsInvariant(int culture)
...
 
+        [Fact]
+        public void TestCasing()
+        {
+            // This test verifies that the casing table in the invariant globalization mode.
+            // The casing table is what we generate from the Unicode data files, and implemented in the CharUnicodeInfo.cs file.
+
+            TextInfo textInfo = CultureInfo.InvariantCulture.TextInfo;
+
+            for (int i = 0; i <= 0xFFFF; i++)
```
Comment (IDisposable) [inline src/libraries/System.Globalization/tests/Invariant/InvariantMode.cs:1217]: As this is UNICODE-16, we should probably should keyhole-out:

- [Unicode BMP Private Use Area](https://en.wikipedia.org/wiki/Private_Use_Areas) U+E000..U+F8FF 
- [Unicode Upper and Lower surrogates ranges](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates) U+D800..U+DFFF

Thus the top of the loop should be
```csharp
for (int i = 0; i <= 0xFFFF; i++)
{
   if (i >= 0xD800 && i <= 0xF8FF)
      continue;
```

The surrogates should always travel in groups, and the PUA is really private use, and thus shouldn't be taunted.

File: src/libraries/System.Globalization/tests/Invariant/InvariantMode.cs [hunk 2]
```diff
@@ -1206,6 +1206,41 @@ public void TestCultureInfo_Ctor_Int32_ReturnsInvariant(int culture)
...
+                char upper = textInfo.ToUpper(ch);
+                char lower = textInfo.ToLower(ch);
+
+                if (ch != upper)
+                {
+                    string upperString = upper.ToString();
+                    string chString = ch.ToString();
+
+                    Assert.True(chString.Equals(upperString, StringComparison.OrdinalIgnoreCase), $"Expected {(int)ch:x4} to be equal to {(int)upper:x4}.");
+                    Assert.True(chString.IndexOf(upperString, StringComparison.OrdinalIgnoreCase) == 0, $"Expected {(int)ch:x4} exist in {(int)upper:x4}.");
```
Comment (IDisposable) [inline src/libraries/System.Globalization/tests/Invariant/InvariantMode.cs:1229]: Since `StartsWith` is also mentioned in the issue #89591, should we `Assert.True(chString.StartsWith(upperString, StringComparison.OrdinalIgnoreCase), $"Expected {(int)ch:x4} start with {(int)upper:x4}.");` them as well?

*note, we probably cannot safely concatenate something to the `chString because there could be some RTL triggering going on... maybe?

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CharUnicodeInfo.cs [hunk 3]
```diff
@@ -273,13 +273,13 @@ internal static uint ToUpper(uint codePoint)
 
             nuint offset = GetCategoryCasingTableOffsetNoBoundsChecks(codePoint);
 
-            // The offset is specified in shorts:
-            // Get the 'ref short' corresponding to where the addend is, read it as a signed 16-bit value, then add
+            // The offset is specified in ushort:
+            // Get the 'ref ushort' corresponding to where the addend is, read it as a unsigned 16-bit value, then add
```
Comment (GrabYourPitchforks) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CharUnicodeInfo.cs:277]: This needs a comment along the lines that we're using 16-bit values because we need to stay within the same Unicode plane. Otherwise it's not obvious as to why the masking step on the final line exists.

**Comment by GrabYourPitchforks** [comment]
The test file https://github.com/dotnet/runtime/blob/main/src/libraries/System.Globalization/tests/System/Globalization/CharUnicodeInfoTests.Generated.cs should also be updated to exercise `ToLower` and `ToUpper` - both for _char_ and for _uint_. That test file exercises _every_ code point to make sure we're following the Standard.

You'll probably need to use `MethodInfo.CreateDelegate` to access them since they're internal. Or somehow figure out how to link a copy of CharUnicodeInfo.cs into the test project. (Though that might be a bit uglier since it'll involve ifdefing production source.)

File: src/libraries/System.Globalization/tests/Invariant/InvariantMode.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/System.Globalization/tests/Invariant/InvariantMode.cs:1217]: Although this doesn't really matter for this test anyway, I'll skip surrogates in the check.

File: src/libraries/System.Globalization/tests/Invariant/InvariantMode.cs [hunk 4]
```diff
@@ -1216,6 +1216,12 @@ public void TestCasing()
 
             for (int i = 0; i <= 0xFFFF; i++)
             {
+                // Surrogates are characters in the Unicode range U+D800—U+DFFF
+                if (i >= 0xD800 && i <= 0xDFFF)
+                {
+                    continue;
```
Comment (GrabYourPitchforks) [inline src/libraries/System.Globalization/tests/Invariant/InvariantMode.cs:1222]: IMO we shouldn't be skipping these tests via a _continue_ statement. It's perfectly legal to call ToUpper / ToLower on an unpaired surrogate char, and the behavior that we want is that we leave the char alone. If we want to skip the surrogate range in this test, then we should have another test specifically for the surrogate range, regression testing that we are in fact reflecting the input chars as-is.

File: src/libraries/System.Globalization/tests/System/Globalization/CharUnicodeInfoTests.Generated.cs [hunk 5]
```diff
@@ -78,6 +79,59 @@ public void GetUnicodeCategory_Int32()
...
+            Func<uint, uint> toLowerUInt = (Func<uint, uint>) typeof(CharUnicodeInfo)
+                                                                .GetMethod("ToLower", BindingFlags.NonPublic | System.Reflection.BindingFlags.Static, new Type[] { typeof(uint) })
+                                                                .CreateDelegate(typeof(Func<uint, uint>));
+            Func<char, char> toLowerChar = (Func<char, char>) typeof(CharUnicodeInfo)
+                                                                .GetMethod("ToLower", BindingFlags.NonPublic | System.Reflection.BindingFlags.Static, new Type[] { typeof(char) })
+                                                                .CreateDelegate(typeof(Func<char, char>));
+
+            for (int i = 0; i <= 0xFFFF; i++)
+            {
+                if ((i >= 0xD800 && i <= 0xDFFF) || // Surrogates are characters in the Unicode range U+D800—U+DFFF
```
Comment (GrabYourPitchforks) [inline src/libraries/System.Globalization/tests/System/Globalization/CharUnicodeInfoTests.Generated.cs:100]: See earlier comment. Instead of calling _continue_ in these cases, we should special-case what the return values actually should be, and test for those return values specifically. Otherwise these chars go untested.

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CharUnicodeInfo.cs [hunk 6]
```diff
@@ -306,12 +308,14 @@ internal static uint ToLower(uint codePoint)
 
             nuint offset = GetCategoryCasingTableOffsetNoBoundsChecks(codePoint);
 
-            // If the offset is specified in ushort:
-            // Get the 'ref ushort' corresponding to where the addend is, read it as a unsigned 16-bit value, then add
+            // The mapped casing for the codePoint is usually existed in the same plane as codePoint.
```
Comment (GrabYourPitchforks) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CharUnicodeInfo.cs:311]: Thanks for updating the comment! 👍

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CharUnicodeInfo.cs [hunk 7]
```diff
@@ -273,12 +273,14 @@ internal static uint ToUpper(uint codePoint)
 
             nuint offset = GetCategoryCasingTableOffsetNoBoundsChecks(codePoint);
 
-            // The offset is specified in ushort:
-            // Get the 'ref ushort' corresponding to where the addend is, read it as a unsigned 16-bit value, then add
+            // The mapped casing for the codePoint is usually existed in the same plane as codePoint.
```
Comment (IDisposable) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CharUnicodeInfo.cs:276]: s/is usually existed/usually exists/

File: src/libraries/System.Private.CoreLib/src/System/Globalization/CharUnicodeInfo.cs (hunk 6 above)
Comment (IDisposable) [inline src/libraries/System.Private.CoreLib/src/System/Globalization/CharUnicodeInfo.cs:311]: [Same](https://github.com/dotnet/runtime/pull/89660/files/f03bff635d6d463642d21f85645174d159359b3a..32c0019d32752927e8d05318adb4ba73900755ba#r1279931181)

**Review by GrabYourPitchforks — APPROVED** [review]
