### PR TITLE
JIT: Allow liveness to remove some nodes with contained side effects

### LINKED ISSUE #116814: JIT: Assertion failed '!node->IsUnusedValue() || !node->OperIs(GT_FIELD_LIST, GT_INIT_VAL)' during 'Global local var liveness'
```csharp
// Generated by Fuzzlyn v3.2 on 2025-06-15 17:16:07
// Run on X86 Windows
// Seed: 11396928574809418613-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86bmi1,x86bmi2,x86fma,x86lzcnt,x86pclmulqdq,x86popcnt,x86sse,x86sse2,x86sse3,x86sse41,x86sse42,x86ssse3,x86x86base
// Reduced from 316.8 KiB to 0.6 KiB in 00:08:07
// Hits JIT assert for Release:
// Assertion failed '!node->IsUnusedValue() || !node->OperIs(GT_FIELD_LIST, GT_INIT_VAL)' in 'C1:M1(byref):byte:this' during 'Global local var liveness' (IL size 51; hash 0x17217cb6; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\lir.cpp Line: 1636
// 
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class C0
{
    public short F3;
    public long F4;
}

public class C1
{
    public byte F0;
    public C0 F3;
    public byte M1(ref byte arg0)
    {
        sbyte var0 = (sbyte)((this.F3.F4 * Program.s_3.F3) << -1);
        System.Console.WriteLine(var0);
        return this.F0;
    }
}

public class Program
{
    public static C0 s_3;
    public static byte s_11;
    public static void Main()
    {
        (new C1()).M1(ref s_11);
    }
}
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
Contained operands with side effects can usually be handled by clearing their containment status. This is what we did before #116144 which changed the DCE to skip nodes with contained side effects. However, the only case that does not support its own standalone codegen is currently embedded mask ops, so switch to check more specifically for this case.

This fixes a case where after removing a call node we could end up with a unused `FIELD_LIST` with a contained IND node, and also fixes the regressions seen because of #116144.

Also switches `GenTree::VisitOperands` to return the visit result, and switches `NodeOrContainedOperandsMayThrow()` to use it (it is slightly more efficient than the iterator version).

Most ideally we would just allow these embedded mask ops to work as top-level nodes, like all other containment candidates.

Fix #116814

### CODE REVIEW

File: src/coreclr/jit/liveness.cpp [hunk 1]
```diff
@@ -1683,6 +1683,38 @@ bool Compiler::fgTryRemoveDeadStoreLIR(GenTree* store, GenTreeLclVarCommon* lclN
...
+//   node - The node whose operands are to be checked
+//
+// Return Value:
+//   Whether the operands can be uncontained or removed.
+//
+// Remarks:
+//   Only embedded mask ops do not support standalone codegen. All other
+//   nodes can be uncontained.
+//
+bool Compiler::fgCanUncontainOrRemoveOperands(GenTree* node)
```
Comment (a74nh) [inline src/coreclr/jit/liveness.cpp:1700]: I'm happy that this won't break anything I was fixing.

**Comment by jakobbotsch** [comment]
PTAL @dotnet/jit-contrib

[Minor diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1072693&view=ms.vss-build-web.run-extensions-tab). Essentially just undoing the regressions from #116144

**Review by amanasifkhalid — APPROVED** [review]
