### PR TITLE
Fix arm64 scalar intrinsic use with small arguments

### LINKED ISSUE #73804: [arm64] JIT assertion failures for valid C# code
In https://github.com/dotnet/runtime/pull/73768 I've wrote quite complex, but valid (it defnitely works fine on x64) C# code that produces JIT assertion failures on arm64:

Sample run: https://github.com/dotnet/runtime/pull/73768/checks?check_run_id=7793120898

Sample log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73768-merge-b3d703c3580445e6b2/JIT.1.Attempt.3/1/console.32c25b20.log?helixlogtype=result

```log
    JIT\Performance\CodeQuality\BenchmarksGame\regex-redux\regex-redux-5\regex-redux-5.cmd [FAIL]
      
      Assert failure(PID 2736 [0x00000ab0], Thread: 11800 [0x2e18]): Assertion failed 'ins != INS_invalid' in 'System.SpanHelpers:LastIndexOfValueType(byref,short,int):int' during 'Generate code' (IL size 335; hash 0xbe43e860; FullOpts)
      
          File: D:\a\_work\1\s\src\coreclr\jit\hwintrinsiccodegenarm64.cpp Line: 282
          Image: D:\h\w\A7BB0946\p\corerun.exe
      
      
      Return code:      1
      Raw output file:      D:\h\w\A7BB0946\w\A93E0970\uploads\Reports\JIT.Performance\CodeQuality\BenchmarksGame\regex-redux\regex-redux-5\regex-redux-5.output.txt
      Raw output:
```

It would be great if someone from the @dotnet/jit-contrib Team could take a look and let me know whether I've hit a bug in JIT or my code is invalid. Thanks!

### PR DESCRIPTION
**Pull request by BruceForstall**
The code already uses `emitActualTypeSize` in the scalar case;
this also uses `genActualType` to get the "actual" type of small
types when deciding the intrinsic base type, used in codegen.

Fixes #73804

### CODE REVIEW

**Comment by BruceForstall** [comment]
[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1941050&view=ms.vss-build-web.run-extensions-tab)

**Comment by BruceForstall** [comment]
@tannergooding @dotnet/jit-contrib PTAL

File: src/coreclr/jit/hwintrinsic.h [hunk 1]
```diff
@@ -866,6 +866,11 @@ struct HWIntrinsic final
             {
                 baseType = node->TypeGet();
             }
+
+            if (category == HW_Category_Scalar)
```
Comment (jakobbotsch) [inline src/coreclr/jit/hwintrinsic.h:870]: What about the `HW_Category_Special` category? Likely the above three cases that get a type via `GenTree::TypeGet` should be changed to use `genActualType(tree)` instead.

Comment (BruceForstall) [reply src/coreclr/jit/hwintrinsic.h:870]: I was trying to make a targeted change, and hadn't fully investigated all the processing that "Special" nodes have. It turns out that this class is only used on arm64, and the only "special" instruction is "Yield", which has no arguments, and for which the "baseType" is ignored. So I could just make the `genActualType` unconditional as you suggest.

**Review by jakobbotsch — APPROVED** [review]

**Comment by adamsitnik** [comment]
@BruceForstall @jakobbotsch can this PR be merged now?

**Comment by jakobbotsch** [comment]
> @BruceForstall @jakobbotsch can this PR be merged now?

I am ok with merging this as is if you are blocked on this.

**Comment by adamsitnik** [comment]
@BruceForstall  @jakobbotsch thank you both!
