### PR TITLE
Fix struct ReturnKind on SysV AMD64.

### LINKED ISSUE #115815: Reproducible segfaults during GC on .NET 8/9 Linux x64
### Description

I've observed a number of segfaults in the runtime with the common theme of what appears to be a garbage collection encountering an `Object` with a null method table ptr. The original applications and cores are not shareable, but the included example is a much more consistent and minimal reproduction with similar backtraces. The reproduction reliably segfaults within seconds of running across a suite of Linux x64 machines running .NET 8 and 9.

I can no longer reproduce the issue on the .NET 10 preview using this provided example, so it does look like the issue was fixed or avoided in main at some point between .NET 9 and 10. A backport to the older supported .NET versions would be much appreciated if possible.

### Reproduction Steps

The following program consistently segfaults on a number of Linux x64 hosts I've tested with .NET 8/9:

```C#
using System.Threading;
using System.Collections.Generic;

internal sealed class Program
{
    private struct Container
    {
        public string Name;
        public Container(string name) { this.Name = name; }
    }

    public static void Main(string[] args)
    {
        var structChurnThread = new Thread(ChurnThread) { Name="StructChurn", IsBackground=true };
        structChurnThread.Start();

        while (true)
        {
            var allocation = new byte[100_000];
            Thread.Sleep(2);
        }
    }

    private static void ChurnThread()
    {
        var source = new KeyValuePair<Container, double>[1_000_000];
        for (var i = 0; i < source.Length; i++)
        {
            source[i] = new KeyValuePair<Container, double>(new Container(i.ToString()), i);
        }

        var destination = new KeyValuePair<Container, double>[source.Length];
        while (true)
        {
            var i = 0;
            foreach (var kvp in (IReadOnlyList<KeyValuePair<Container, double>>) source)
            {
                destination[i++] = kvp;
            }

            Thread.Sleep(1);
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
</Project>
```

### Expected behavior

The example is not expected to cause the GC to segfault.

### Actual behavior

Shortly after startup, the program will segfault during a GC with a backtrace along the lines of:

```
(lldb) bt
* thread #9, name = '.NET BGC', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x0)
  * frame #0: 0x00007ffff747ae39 libcoreclr.so`WKS::gc_heap::background_promote(Object**, ScanContext*, unsigned int) [inlined] MethodTable::GetFlag(this=0x0000000000000000, flag=enum_flag_HasComponentSize) const at methodtable.h:3511:16
    frame #1: 0x00007ffff747ae39 libcoreclr.so`WKS::gc_heap::background_promote(Object**, ScanContext*, unsigned int) [inlined] MethodTable::HasComponentSize(this=0x0000000000000000) const at methodtable.h:1532:16
    frame #2: 0x00007ffff747ae39 libcoreclr.so`WKS::gc_heap::background_promote(Object**, ScanContext*, unsigned int) [inlined] WKS::my_get_size(ob=0x00007fbf66d8b380) at gc.cpp:11581:18
    frame #3: 0x00007ffff747ae32 libcoreclr.so`WKS::gc_heap::background_promote(Object**, ScanContext*, unsigned int) [inlined] WKS::gc_heap::background_mark_simple(o="") at gc.cpp:27817:24
    frame #4: 0x00007ffff747ae0b libcoreclr.so`WKS::gc_heap::background_promote(ppObject=0x00007fbecaccc980, sc=<unavailable>, flags=<unavailable>) at gc.cpp:27904:5
    frame #5: 0x00007ffff7215514 libcoreclr.so`HijackFrame::GcScanRoots(this=0x00007fbecaccc8f0, fn=(libcoreclr.so`WKS::gc_heap::background_promote(Object**, ScanContext*, unsigned int) at gc.cpp:27847), sc=0x00007fbeca4cbc28) at frames.cpp:1173:13
    frame #6: 0x00007ffff731a5bf libcoreclr.so`GcStackCrawlCallBack(pCF=0x00007fbeca4c9060, pData=0x00007fbeca4cbaf8) at gcenv.ee.common.cpp:297:21
    frame #7: 0x00007ffff7293e22 libcoreclr.so`Thread::MakeStackwalkerCallback(this=0x000055555561fb40, pCF=0x00007fbeca4c9060, pCallback=(libcoreclr.so`GcStackCrawlCallBack(CrawlFrame*, void*) at gcenv.ee.common.cpp:200), pData=0x00007fbeca4cbaf8) at stackwalk.cpp:846:27
    frame #8: 0x00007ffff72940ad libcoreclr.so`Thread::StackWalkFramesEx(this=0x000055555561fb40, pRD=0x00007fbeca4c9400, pCallback=(libcoreclr.so`GcStackCrawlCallBack(CrawlFrame*, void*) at gcenv.ee.common.cpp:200), pData=0x00007fbeca4cbaf8, flags=34048, pStartFrame=0x0000000000000000) at stackwalk.cpp:926:26
    frame #9: 0x00007ffff72943ff libcoreclr.so`Thread::StackWalkFrames(this=0x000055555561fb40, pCallback=(libcoreclr.so`GcStackCrawlCallBack(CrawlFrame*, void*) at gcenv.ee.common.cpp:200), pData=0x00007fbeca4cbaf8, flags=34048, pStartFrame=0x0000000000000000) at stackwalk.cpp:1009:12
    frame #10: 0x00007ffff7316fea libcoreclr.so`ScanStackRoots(pThread=0x000055555561fb40, fn=(libcoreclr.so`WKS::gc_heap::background_promote(Object**, ScanContext*, unsigned int) at gc.cpp:27847), sc=0x00007fbeca4cbc28) at gcenv.ee.cpp:182:18
    frame #11: 0x00007ffff7316dd6 libcoreclr.so`GCToEEInterface::GcScanRoots(fn=(libcoreclr.so`WKS::gc_heap::background_promote(Object**, ScanContext*, unsigned int) at gc.cpp:27847), condemned=2, max_gen=2, sc=0x00007fbeca4cbc28) at gcenv.ee.cpp:281:13
    frame #12: 0x00007ffff746adea libcoreclr.so`WKS::gc_heap::background_mark_phase() at gc.cpp:38204:5
    frame #13: 0x00007ffff74695f2 libcoreclr.so`WKS::gc_heap::gc1() at gc.cpp:22320:13
    frame #14: 0x00007ffff748eb5c libcoreclr.so`WKS::gc_heap::bgc_thread_function() at gc.cpp:39246:9
    frame #15: 0x00007ffff748ea71 libcoreclr.so`WKS::gc_heap::bgc_thread_stub(arg=<unavailable>) at gc.cpp:37174:5 [artificial]
    frame #16: 0x00007ffff731a0b4 libcoreclr.so`(anonymous namespace)::CreateSuspendableThread(void (*)(void*), void*, char16_t const*)::$_0::__invoke(void*) [inlined] (anonymous namespace)::CreateSuspendableThread(void (*)(void*), void*, char16_t const*)::$_0::operator()(this=<unavailable>, argument=<unavailable>) const at gcenv.ee.cpp:1440:17
    frame #17: 0x00007ffff731a051 libcoreclr.so`(anonymous namespace)::CreateSuspendableThread(void (*)(void*), void*, char16_t const*)::$_0::__invoke(argument=<unavailable>) at gcenv.ee.cpp:1420:27
    frame #18: 0x00007ffff76171ae libcoreclr.so`CorUnix::CPalThread::ThreadEntry(pvParam=0x000055555558e2b0) at thread.cpp:1760:16
    frame #19: 0x00007ffff788a0ea libc.so.6`start_thread + 794
    frame #20: 0x00007ffff790f150 libc.so.6`__clone3 + 48
```
Or,
```
(lldb) bt
* thread #9, name = '.NET BGC', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x0)
  * frame #0: 0x00007ffff748ede6 libcoreclr.so`WKS::gc_heap::background_drain_mark_list(int) [inlined] MethodTable::GetFlag(this=0x0000000000000000, flag=enum_flag_HasComponentSize) const at methodtable.h:3511:16
    frame #1: 0x00007ffff748ede6 libcoreclr.so`WKS::gc_heap::background_drain_mark_list(int) [inlined] MethodTable::HasComponentSize(this=0x0000000000000000) const at methodtable.h:1532:16
    frame #2: 0x00007ffff748ede6 libcoreclr.so`WKS::gc_heap::background_drain_mark_list(int) [inlined] WKS::my_get_size(ob=0x00007fbf66d9e582) at gc.cpp:11581:18
    frame #3: 0x00007ffff748eddf libcoreclr.so`WKS::gc_heap::background_drain_mark_list(int) [inlined] WKS::gc_heap::background_mark_simple(o="") at gc.cpp:27817:24
    frame #4: 0x00007ffff748edb5 libcoreclr.so`WKS::gc_heap::background_drain_mark_list(int) [inlined] WKS::gc_heap::background_mark_object(o="") at gc.cpp:27834:9
    frame #5: 0x00007ffff748eda3 libcoreclr.so`WKS::gc_heap::background_drain_mark_list(thread=<unavailable>) at gc.cpp:37196:9
    frame #6: 0x00007ffff746ab79 libcoreclr.so`WKS::gc_heap::background_mark_phase() at gc.cpp:38031:5
    frame #7: 0x00007ffff74695f2 libcoreclr.so`WKS::gc_heap::gc1() at gc.cpp:22320:13
    frame #8: 0x00007ffff748eb5c libcoreclr.so`WKS::gc_heap::bgc_thread_function() at gc.cpp:39246:9
    frame #9: 0x00007ffff748ea71 libcoreclr.so`WKS::gc_heap::bgc_thread_stub(arg=<unavailable>) at gc.cpp:37174:5 [artificial]
    frame #10: 0x00007ffff731a0b4 libcoreclr.so`(anonymous namespace)::CreateSuspendableThread(void (*)(void*), void*, char16_t const*)::$_0::__invoke(void*) [inlined] (anonymous namespace)::CreateSuspendableThread(void (*)(void*), void*, char16_t const*)::$_0::operator()(this=<unavailable>, argument=<unavailable>) const at gcenv.ee.cpp:1440:17
    frame #11: 0x00007ffff731a051 libcoreclr.so`(anonymous namespace)::CreateSuspendableThread(void (*)(void*), void*, char16_t const*)::$_0::__invoke(argument=<unavailable>) at gcenv.ee.cpp:1420:27
    frame #12: 0x00007ffff76171ae libcoreclr.so`CorUnix::CPalThread::ThreadEntry(pvParam=0x000055555558e2b0) at thread.cpp:1760:16
    frame #13: 0x00007ffff788a0ea libc.so.6`start_thread + 794
    frame #14: 0x00007ffff790f150 libc.so.6`__clone3 + 48
```

### Regression?

The included example reliably crashes on Linux x64 .NET 8 and 9 (as well as .NET 6 and 7, for completeness)

Windows x64 builds for the same .NET versions do not appear to be impacted.

### Known Workarounds

_No response_

### Configuration

```
.NET SDKs: 6.0.428, 7.0.410, 8.0.409, 9.0.300
.NET Runtimes: 6.0.36, 7.0.20, 8.0.16, 9.0.5

Runtime Environment:
 OS Name:     almalinux
 OS Version:  9.6
 OS Platform: Linux
 RID:         linux-x64
```

Other linux configurations (e.g., ARM) haven't been tested. The issue does not appear to be present on Windows.

### Other information

Originally it looked like this _could_ be related to MUTLIREG_RETURN on Linux x64 but this hasn't been fully confirmed.

### PR DESCRIPTION
**Pull request by zengandrew**
On SysV AMD64, structs returned in a float and int reg pair were being classified as RT_Scalar_XX. This causes downstream consumers (e.g., HijackFrame::GcScanRoots) to look for obj/byref's in the second int reg. Per the ABI, however, the first float is passed through a float reg and the obj/byref is passed through the _first_ int reg. We now detect and fix this case by skipping the first float type in the ReturnKind encoding and moving the second type into the first.

Fix #115815

### CODE REVIEW

**Comment by zengandrew** [comment]
@dotnet-policy-service agree

File: src/coreclr/jit/gcencode.cpp [hunk 1]
```diff
@@ -50,8 +50,21 @@ ReturnKind GCInfo::getReturnKind()
         case 1:
             return VarTypeToReturnKind(retTypeDesc.GetReturnRegType(0));
         case 2:
-            return GetStructReturnKind(VarTypeToReturnKind(retTypeDesc.GetReturnRegType(0)),
-                                       VarTypeToReturnKind(retTypeDesc.GetReturnRegType(1)));
+        {
+            var_types first = retTypeDesc.GetReturnRegType(0);
```
Comment (jkotas) [inline src/coreclr/jit/gcencode.cpp]: This is the right fix for backport. In main, this path is unreachable in main - the whole method can be under `TARGET_X86` ifdef and simplified to only handle a single register.

@jakobbotsch How would you like to handle this?

Comment (jakobbotsch) [reply src/coreclr/jit/gcencode.cpp]: @zengandrew Thanks so much for filing the fix here. I have cherry-picked the commit from this PR directly into the two backports (#116206, #116208).

Given the testing it appears to be unnecessary for the 9.0 backport. However 9.0 still has the code around return kinds enabled for x64. That code was removed in #110799 which is not part of 9.0. The actual PRs that made it unnecessary are #95565 and #104336 that are part of 9.0. But, just to be safe, since the code is actually running during hijack, I think we should include it as well.

For main I think we should skip the change (mainly to avoid the misleading commit history, since this code is unused). And indeed we should clean this up (cc @VSadov if you want to do it).

Comment (jkotas) [reply src/coreclr/jit/gcencode.cpp]: I have pushed a commit with the cleanup

File: src/coreclr/jit/gcencode.cpp [hunk 2]
```diff
@@ -29,40 +31,38 @@ ReturnKind VarTypeToReturnKind(var_types type)
...
-#endif // TARGET_X86
         default:
             return RT_Scalar;
     }
 }
 
 ReturnKind GCInfo::getReturnKind()
 {
-    // Note the GCInfo representation only supports structs with up to 2 GC pointers.
+    // Note the JIT32 GCInfo representation only supports structs with 1 pointer.
```
Comment (jkotas) [inline src/coreclr/jit/gcencode.cpp]:
```suggestion
    // Note the JIT32 GCInfo representation only supports structs with 1 GC pointer.
```

File: src/coreclr/vm/method.cpp [hunk 3]
```diff
@@ -1299,6 +1299,15 @@ ReturnKind MethodDesc::ParseReturnKindFromSig(INDEBUG(bool supportStringConstruc
...
                                 }
                             }
+
+                            if (eeClass->GetEightByteClassification(0) == SystemVClassificationTypeSSE)
+                            {
+                                // Skip over SSE types since they do not consume integer registers.
+                                // An obj/byref in the 2nd eight bytes will be in the first integer register.
+                                regKinds[0] = regKinds[1];
+                                regKinds[1] = RT_Scalar;
+                            }
```
Comment (jakobbotsch) [inline src/coreclr/vm/method.cpp]: Can `ParseReturnKindFromSig` be simplified too? It is only used by `MethodDesc::GetReturnKind` and that one has only uses from GCStress (which is under `TARGET_X86`) and `CLRToCOMMethodFrame::GcScanRoots_Impl` (which does not try to handle the multireg cases, but with a NYI assert.).

The `ReturnKind` enum could probably be cleaned up too after that.

Comment (jkotas) [reply src/coreclr/vm/method.cpp]: > The ReturnKind enum could probably be cleaned up too after that.

 GCInfo decoder source is shared with diagnostic repo. It needs to support older versions of the format. The no longer used ReturnKind values need to stay for that.

> Can ParseReturnKindFromSig be simplified too?

Done

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/vm/method.cpp [hunk 4]
```diff
@@ -1275,34 +1294,6 @@ ReturnKind MethodDesc::ParseReturnKindFromSig(INDEBUG(bool supportStringConstruc
                     if (!thValueType.IsTypeDesc())
                     {
                         MethodTable * pReturnTypeMT = thValueType.AsMethodTable();
-#ifdef UNIX_AMD64_ABI
```
Comment (janvorli) [inline src/coreclr/vm/method.cpp:1278]: I am not sure I understand how we can get rid of this. What if the returned struct contains two references?

File: src/coreclr/vm/method.hpp [hunk 5]
```diff
@@ -1688,18 +1688,15 @@ class MethodDesc
...
-
+#if defined(TARGET_X86) || defined(FEATURE_COMINTEROP)
 public:
-    // This method is used to restore ReturnKind using the class handle, it is fully supported only on x64 Ubuntu,
-    // other platforms do not support multi-reg return case with pointers.
-    // Use this method only when you can't hit this case
-    // (like CLRToCOMMethodFrame::GcScanRoots) or when you can tolerate RT_Illegal return.
-    // Also, on the other platforms for a single field struct return case
-    // the function can't distinguish RT_Object and RT_ByRef.
+    // This method is used to restore ReturnKind using the class handle,e
```
Comment (jkotas) [inline src/coreclr/vm/method.hpp]:
```suggestion
    // This method is used to restore ReturnKind using the class handle.
```

File: src/coreclr/vm/method.hpp [hunk 6]
```diff
@@ -1688,18 +1688,15 @@ class MethodDesc
...
 public:
-    // This method is used to restore ReturnKind using the class handle, it is fully supported only on x64 Ubuntu,
-    // other platforms do not support multi-reg return case with pointers.
-    // Use this method only when you can't hit this case
-    // (like CLRToCOMMethodFrame::GcScanRoots) or when you can tolerate RT_Illegal return.
-    // Also, on the other platforms for a single field struct return case
-    // the function can't distinguish RT_Object and RT_ByRef.
+    // This method is used to restore ReturnKind using the class handle.
+    // It does not support multi-reg return case with pointers. Use this
+    // method only when you can't hit
```
Comment (jkotas) [inline src/coreclr/vm/method.hpp]:
```suggestion
    // It does not support multi-reg return case with pointers. Use this method only when you can't hit
```

File: src/coreclr/vm/method.cpp (hunk 4 above)
Comment (jkotas) [reply src/coreclr/vm/method.cpp:1278]: This method is only used on x86 and Windows now, so the code under this ifdef is unreachable.

Also, the existing method contract for non-x86 Windows is to return `RT_Illegal` for non-implemented cases. See existing comment at https://github.com/dotnet/runtime/pull/116194/files#diff-6e60a6042a58e12c329936a1edd7daeec7c184ba089e2cc9f2570c07320f6ffaR1693-R1696 . I am bothering with fixing that since the imprecise contract works fine for the two cases where this is called.

File: src/coreclr/vm/method.cpp [hunk 7]
```diff
@@ -1275,43 +1294,6 @@ ReturnKind MethodDesc::ParseReturnKindFromSig(INDEBUG(bool supportStringConstruc
...
-                                regKinds[0] = regKinds[1];
-                                regKinds[1] = RT_Scalar;
-                            }
-
-                            ReturnKind structReturnKind = GetStructReturnKind(regKinds[0], regKinds[1]);
-                            return structReturnKind;
-                        }
-#endif // UNIX_AMD64_ABI
 
                         if (pReturnTypeMT->ContainsGCPointers() || pReturnTypeMT->IsByRefLike())
```
Comment (VSadov) [inline src/coreclr/vm/method.cpp]: If we have `pReturnTypeMT->IsByRefLike()`, should we return `RT_ByRef` ?
Or, if we cannot distinguish `RT_Object` from `RT_ByRef`, would `RT_ByRef` be safer to return?

Comment (VSadov) [reply src/coreclr/vm/method.cpp]: Does `pReturnTypeMT->IsByRefLike()` actually imply that there must be a GC ref? 

I think at C# level you can make any struct to be stack-only, it does not need to contain pointers or refs. If `IsByRefLike()` is true for all ref structs, there may not be a pointer. 

Perhaps 
`pReturnTypeMT->ContainsGCPointers()` should return `RT_Object` and 
`pReturnTypeMT->ContainsGCPointers() && pReturnTypeMT->IsByRefLike()` should return `RT_ByRef`

Or maybe for simplicity just return `RT_ByRef` for `pReturnTypeMT->ContainsGCPointers()`?

Comment (VSadov) [reply src/coreclr/vm/method.cpp]: It is not the part that is being fixed, but since we are touching this, and it looks a bit suspicious,...

Comment (jkotas) [reply src/coreclr/vm/method.cpp]: Ok, I have done more cleanup. This method is only used for GC stress on x86 now. GC stress can tolerate `RT_Illegal` return (it did that before this change as well, so it is not a coverage regression).
