### PR TITLE
use new API on new windows to get TLS13

### LINKED ISSUE #1720: TLS1.3 does not work on Windows
While TLS1.3 is not fully supported in releases Windows version It is available for opt-in in some recent one. I used internal preview and I verified that schannel can handle connect to TLS13 Azure endpoint as well as it can connect to my local Linux server running OpenSSL 1.1.1.

However when IO try to connect using .NET I get:
```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

```

further more, When TLS1.3 was originally added to .NET OpenSSL was only one working implementation.  Currently  TLS1.3 tests will not run on TLS1.3 capable Windows server as well as other test break when  1.3 is enabled.

### PR DESCRIPTION
**Pull request by wfurt**
Update SslStream to use SCH_CREDENTIALS on new Windows builds. It does not allow to enforce EncryptionPolicy.NoEncryption so when requested, we will fall-back to legacy API and protocols. 

It will negotiate TLS 1.3 on Windows insider build and it will pass all tests (but the one bellow)

fixes #1720

SslStream_StreamToStream_ClientInitiatedCloseNotify_Ok test was failing. After some experiments, it can pass if server passes some data before shutdown. This is probably OS bug and ticket was opened to track it. Completion of TLS 1.3 piggy backs on application frames but this should work IMHO. I updated the test to run with and without extra data to make it more visible. We can decided what to do when we get new windows build to CI.

### CODE REVIEW

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs [hunk 1]
```diff
@@ -318,6 +317,59 @@ public new IntPtr DangerousGetHandle()
...
+                                null,
+                                ref outCredential._handle,
+                                out timeStamp);
+            }
+            finally
+            {
+                authdata->paCred = copiedPtr;
+            }
+
+#if TRACE_VERBOSE
```
Comment (davidsh) [inline src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs:361]: I thought we got rid of 'TRACE_VERBOSE'.  It's an ancient relic from .NET Framework and the 'TRAVE' environment variable ("TRAce + VErbose").

We should stop using it. Most developers don't build with that env variable set. Eventually we should transition all of the TRACE_VERBOSE stuff.

Instead, if we need more "chatty" diagnostic tracing, we should add a `NetEventSource.Verbose` method and map that to EventSource `verbose` level events.  The current `NetEventSource.Info` method maps to EventSource `info` level events.

Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs:361]: This is clone of the other overloads. Perhaps TRACE_VERBOSE should be removed completely in separate PR.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs [hunk 2]
```diff
@@ -318,6 +317,59 @@ public new IntPtr DangerousGetHandle()
...
+            // If there is a certificate, wrap it into an array.
+            // Not threadsafe.
+            IntPtr copiedPtr = authdata->paCred;
+            try
+            {
+                IntPtr certArrayPtr = new IntPtr(&copiedPtr);
+                if (copiedPtr != IntPtr.Zero)
+                {
+                    authdata->paCred = certArrayPtr;
+                }
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs:341]: I don't understand why we're doing this dance with authdata->paCred to replace it with an address that contains the desired value.  Why not just create the authdata correctly in the first place?

File: src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs [hunk 3]
```diff
@@ -215,6 +215,97 @@ public enum Flags
...
+            public int cCreds;
+
+            // ptr to an array of pointers
+            // There is a hack done with this field.  AcquireCredentialsHandle requires an array of
+            // certificate handles; we only ever use one.  In order to avoid pinning a one element array,
+            // we copy this value onto the stack, create a pointer on the stack to the copied value,
+            // and replace this field with the pointer, during the call to AcquireCredentialsHandle.
+            // Then we fix it up afterwards.  Fine as long as all the SSPI credentials are not
+            // supposed to be threadsafe.
+            public IntPtr paCred;
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs:234]: Why are some things declared as actual strongly-typed pointers and others like this declared just as IntPtr?

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs [hunk 4]
```diff
@@ -16,6 +16,15 @@ namespace System.Net.Security
 {
     internal static class SslStreamPal
     {
+        private static bool UseNewCryptoApi = CheckWindowsVersion();
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:19]: readonly

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs [hunk 5]
```diff
@@ -16,6 +16,15 @@ namespace System.Net.Security
...
+        private static bool CheckWindowsVersion()
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:20]: Nit: the name here seems like it should instead be specific to what it's checking, e.g. Is1809OrNewer, or something like that.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs [hunk 6]
```diff
@@ -145,6 +162,69 @@ public static SafeFreeCredentials AcquireCredentialsHandle(X509Certificate? cert
             return AcquireCredentialsHandle(direction, secureCredential);
         }
 
+        public static unsafe SafeFreeCredentials AcquireCredentialsHandleNew(X509Certificate? certificate, SslProtocols protocols, EncryptionPolicy policy, bool isServer)
+        {
+            int protocolFlags = GetProtocolFlagsFromSslProtocols(protocols, isServer);
+            Interop.SspiCli.SCH_CREDENTIALS.Flags flags;
+            Interop.SspiCli.CredentialUse direction;
+
+            if (!isServer)
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:171]: Nit: why not flip the polarity to avoid the negative, e.g.
```C#
if (isServer)
{
   ...
}
else
{
    ...
}
```

File: src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs [hunk 7]
```diff
@@ -215,6 +215,97 @@ public enum Flags
...
+            public int dwCredformat;
+            public int cCreds;
+
+            // ptr to an array of pointers
+            // There is a hack done with this field.  AcquireCredentialsHandle requires an array of
+            // certificate handles; we only ever use one.  In order to avoid pinning a one element array,
+            // we copy this value onto the stack, create a pointer on the stack to the copied value,
+            // and replace this field with the pointer, during the call to AcquireCredentialsHandle.
+            // Then we fix it up afterwards.  Fine as long as all the SSPI credentials are not
+            // supposed to be threadsafe.
```
[the remark this answers is not in the document]
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs:233]: I copy the body of the function from existing code. With exception of places I know changed, I assumed same behavior and I left types and comments ASIS. 

https://github.com/dotnet/runtime/blob/f05ebc894ba8d09a21a638cf928742d9fae3a56e/src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs#L176-L190

I can take the feedback and go and fix both places. For now, I tried to minimize changes to legacy code to make back port easier.

[the remark this answers is not in the document]
Comment (stephentoub) [reply src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs:233]: We definitely shouldn't propagate the badness to here, so let's at least fix it here.  We can fix the other one separately.  This case should be trivial to configure correctly at the site where the struct is initialized.

File: src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs (hunk 3 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs:234]: I left same as existing SCHANNEL_CRED in most cases. 
The notable difference is SCH_CREDENTIALS* and that was done to pass reference via RunImpersonated() lambda.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs (hunk 2 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs:341]: That part I don't know. I will investigate. Possibly fixing only on new code path to limit risk for now.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs (hunk 1 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs]: fixed.

File: src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs]: fixed.

File: src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs (hunk 3 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs]: In that case we get opaque pointer and we are it in safe handle. I updated the structure to use native pointer in places where caller (WindowesPAL) is responsible for pinning the data. 
In this particular case I also made update to construct expected layout so there is no trickery in SecuritySafeHandle. I think this will be handy soon to pass entire certificate chain. I'll do more testing with chains and I'll fix the leafy code when that gets ready.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs (hunk 5 above)
Comment (wfurt) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs]: updated.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs (hunk 6 above)
Comment (wfurt) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs]: updated.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs (hunk 2 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs]: removed, see the other comment.

**Comment by wfurt** [comment]
this is ready for another review round.

File: src/libraries/Common/src/Interop/Windows/SspiCli/ISSPIInterface.cs [hunk 8]
```diff
@@ -15,6 +15,7 @@ internal interface ISSPIInterface
         int EnumerateSecurityPackages(out int pkgnum, out SafeFreeContextBuffer pkgArray);
         int AcquireCredentialsHandle(string moduleName, Interop.SspiCli.CredentialUse usage, ref SafeSspiAuthDataHandle authdata, out SafeFreeCredentials outCredential);
         int AcquireCredentialsHandle(string moduleName, Interop.SspiCli.CredentialUse usage, ref Interop.SspiCli.SCHANNEL_CRED authdata, out SafeFreeCredentials outCredential);
+        unsafe int AcquireCredentialsHandle(string moduleName, Interop.SspiCli.CredentialUse usage, Interop.SspiCli.SCH_CREDENTIALS* authdata, out SafeFreeCredentials outCredential);
```
Comment (bartonjs) [inline src/libraries/Common/src/Interop/Windows/SspiCli/ISSPIInterface.cs:18]: Why use a pointer instead of a ref (what the rest of the methods do)?

Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/ISSPIInterface.cs:18]: I could net get ref through lambda used to inpersonificate.

File: src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs [hunk 9]
```diff
@@ -215,6 +215,92 @@ public enum Flags
...
+        internal unsafe struct SCH_CREDENTIALS
+        {
+            public const int CurrentVersion = 0x5;
+
+            public int dwVersion;
+            public int dwCredformat;
+            public int cCreds;
+
+            // This is pointer to arry of CERT_CONTEXT*
+            // We do not use it directly in .NET. Instead, we wrap returned OS pointer in safe handle.
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs:228]: Is this comment needed?  I'm not even sure what it means; we do use it.

Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs:228]: the meaning was that we do not dereference or use CERT_CONTEXT in .NET. So it is pointer to a structure but that is hidden to PAL.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs [hunk 10]
```diff
@@ -141,6 +141,31 @@ public static SafeFreeCredentials AcquireCredentialsHandle(ISSPIInterface secMod
             return outCredential;
         }
 
+        public static unsafe SafeFreeCredentials AcquireCredentialsHandle(ISSPIInterface secModule, string package, Interop.SspiCli.CredentialUse intent, Interop.SspiCli.SCH_CREDENTIALS* scc)
+        {
+            if (NetEventSource.IsEnabled)
+            {
+                NetEventSource.Enter(null, package);
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs:148]: Have you found such Enter/Exit tracing to be valuable?  I'm hoping we might actually rip them all out.  I realize you're just following the same pattern that's used elsewhere, so it's fine, but... yeah.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs [hunk 11]
```diff
@@ -141,6 +141,31 @@ public static SafeFreeCredentials AcquireCredentialsHandle(ISSPIInterface secMod
...
+                NetEventSource.Log.AcquireCredentialsHandle(package, intent, (IntPtr)scc);
+            }
+
+            SafeFreeCredentials? outCredential = null;
```
Comment (stephentoub) [inline src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs:152]: Is the `= null` needed?

File: src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs (hunk 9 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs:228]: I added that comment after your questions about IntPtr vs something strongly typed.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs [hunk 12]
```diff
@@ -16,6 +16,15 @@ namespace System.Net.Security
 {
     internal static class SslStreamPal
     {
+        private static readonly bool UseNewCryptoApi = Is1809OrNewer();
+        private static bool Is1809OrNewer()
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:20]: Is the separate function needed anymore?
```C#
private static readonly bool UseNewCryptoApi = 
    // On newer Windows version we use new API to get TLS1.3.
    // API is supported since Windows 10 1809 (17763)but there is no reason to use at the moment.
    Interop.NtDll.RtlGetVersionEx(out Interop.NtDll.RTL_OSVERSIONINFOEX osvi) == 0 &&
    osvi.dwMajorVersion >= 10 && osvi.dwBuildNumber >= 18836;
```

File: src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs (hunk 10 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs:148]: I did no not - so far. But I'm not the PerfView master. I added them for consistency. 
BTW you can filter them out easily with pipeline keywords. As far as I know, with the right filter, the entry/exit would not be edited - but it would still stay in source code and we would need to maintain it.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs [hunk 13]
```diff
@@ -107,6 +116,14 @@ public static SecurityStatusPal InitializeSecurityContext(ref SafeFreeCredential
         }
 
         public static SafeFreeCredentials AcquireCredentialsHandle(X509Certificate? certificate, SslProtocols protocols, EncryptionPolicy policy, bool isServer)
+        {
+            // New crypto API does not allow to force NULL encryption.
+            return !UseNewCryptoApi || policy == EncryptionPolicy.NoEncryption ?
+                        AcquireCredentialsHandleLegcy(certificate, protocols, policy, isServer) :
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:122]: AcquireCredentialsHandleLegcy => AcquireCredentialsHandleLegacy

Also, could we use a different term than Legacy?  Is it PreWindows101809 vs PostWindows101809?

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs [hunk 14]
```diff
@@ -145,6 +162,74 @@ public static SafeFreeCredentials AcquireCredentialsHandle(X509Certificate? cert
...
+            if (certificate != null)
+            {
+                credential.cCreds = 1;
+                Span<IntPtr> certificates = stackalloc IntPtr[1];
+                certificates[0] = certificate.Handle;
+                fixed (void* ptr = &certificates[0])
+                {
+                    credential.paCred = ptr;
+                }
+            }
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:216]:
```suggestion
            IntPtr certificateHandle = IntPtr.Zero;
            if (certificate != null)
            {
                credential.cCreds = 1;
                certificateHandle = certificate.Handle;
                credential.paCred = &certificateHandle;
            }
```
?

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs [hunk 15]
```diff
@@ -145,6 +162,74 @@ public static SafeFreeCredentials AcquireCredentialsHandle(X509Certificate? cert
...
+            {
+                // If we were asked to do specific protocol we need to fill TLS_PARAMETERS.
+                Interop.SspiCli.TLS_PARAMETERS tlsParameters = default;
+                tlsParameters.grbitDisabledProtocols = (uint)protocolFlags ^ uint.MaxValue;
+
+                credential.cTlsParameters = 1;
+                credential.pTlsParameters = &tlsParameters;
+            }
+
+            return AcquireCredentialsHandle(direction, &credential);
```
Comment (stephentoub) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:230]: This `credential` is storing a pointer to something on the stack.  I assume that whatever AcquireCredentialsHandle returns doesn't expect that to still be alive?

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs (hunk 13 above)
Comment (wfurt) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:122]: Would it make sense to name them by the structure they use? The name is similar so even with that I found it confusing but that is really the main difference. The structures them selves have version field and it is v4 for "legacy" and v5 for the "new" one.

Comment (stephentoub) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:122]: > Would it make sense to name them by the structure they use? 

Sounds good.

File: src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs (hunk 9 above)
Comment (stephentoub) [reply src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs:228]: So the "it" in we dot not use it" is referring to CERT_CONTEXT rather than to paCred?  That was my confusion.

But, even so, we are kind of using it, aren't we?  X509Certificate.Handle must be a CERT_CONTEXT*; we're storing that into paCred, effectively storing a pointer to an array of one CERT_CONTEXT.  So while we're not naming it as such, we are using it.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs (hunk 15 above)
Comment (wfurt) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:230]: not as far as I know. I can verify that as well. I expect tile time to be same as the structure.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs (hunk 10 above)
Comment (stephentoub) [reply src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs:148]: > but it would still stay in source code and we would need to maintain it.

Yes.  It's extra maintenance (and we're already wildly inconsistent on it) and extra overhead.

File: src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs (hunk 9 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/Interop.SSPI.cs:228]: yes. I assumed the "directly" would be a hint but obviously it is not clear.  I was also thinking about also adding CERT_CONTEXT so we can see details in debugger but that is somewhat complicated with more pointers inside.
Maybe Windbg could do cast to native but I failed so far with VS.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs (hunk 10 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs]: since the wrapper really does not do anything I took it out and did the same to legacy function.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs (hunk 12 above)
Comment (wfurt) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs]: updated.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs (hunk 13 above)
Comment (wfurt) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs]: I made the change and added comment to each.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs (hunk 14 above)
Comment (wfurt) [reply src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs]: time will come when we need more than just one certificate to pass down custom chain. But since that is not needed for TLS13 I moved forward with proposed change. That should also make back-porting easier.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs (hunk 11 above)
Comment (wfurt) [reply src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs]: no. I also updated legacy function I used as baseline.

File: src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs [hunk 16]
```diff
@@ -15,6 +15,12 @@ namespace System.Net.Security
 {
     internal static class SslStreamPal
     {
+        private static readonly bool UseNewCryptoApi =
+            // On newer Windows version we use new API to get TLS1.3.
+            // API is supported since Windows 10 1809 (17763)but there is no reason to use at the moment.
+            Interop.NtDll.RtlGetVersionEx(out Interop.NtDll.RTL_OSVERSIONINFOEX osvi) == 0 &&
+            osvi.dwMajorVersion >= 10 && osvi.dwBuildNumber >= 18836;
```
Comment (scalablecory) [inline src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:22]: We fixed `Environment.OSVersion` in https://github.com/dotnet/runtime/pull/33651, so no need to call this directly now.

File: src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs [hunk 17]
```diff
@@ -301,6 +301,39 @@ public new IntPtr DangerousGetHandle()
...
+            errorCode = Interop.SspiCli.AcquireCredentialsHandleW(
+                                null,
+                                package,
+                                (int)intent,
+                                null,
+                                authdata,
+                                null,
+                                null,
+                                ref outCredential._handle,
+                                out timeStamp);
```
Comment (scalablecory) [inline src/libraries/Common/src/Interop/Windows/SspiCli/SecuritySafeHandles.cs:325]:
```suggestion
            outCredential = new SafeFreeCredential_SECURITY();

            int errorCode = Interop.SspiCli.AcquireCredentialsHandleW(
                                null,
                                package,
                                (int)intent,
                                null,
                                authdata,
                                null,
                                null,
                                ref outCredential._handle,
                                out long timeStamp);
```

**Review by scalablecory — APPROVED** [review]
looks good, thanks.

**Comment by safern** [comment]
@wfurt I know CI is acting weird. However this was merged without CI run. There was only the cla that was triggered.

**Comment by wfurt** [comment]
oops. I let it sit and did something else and then I saw it green.
