### PR TITLE
Fixing tests on android that uses Icu Shim Globalization

### LINKED ISSUE #36685: Android tests are broken - attempt to load libmono-sgen-2.0.so
Broken in https://github.com/dotnet/runtime/pull/35790

Follow [these](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing-android.md) steps to install prerequisites for Android.
Then, optionally, enable logging for Mono [here](https://github.com/dotnet/runtime/blob/49f59a3cb935523c07187ce26bb03c7fa7fd66bd/tools-local/tasks/mobile.tasks/AndroidAppBuilder/Templates/runtime-android.c#L142-L143) (replace `TRUE` with `true`)
```bash
# build repo
./build.sh Mono+Libs -os Android -arch arm64

# run tests on device
./dotnet.sh build src/libraries/System.Text.Encoding.Extensions/tests \
/p:TargetOS=Android /p:TargetArchitecture=arm64 /t:Test
```
Open adb log and observe something like this:
```
05-19 12:30:33.500 13187 13227 D DOTNET  : (Mono debug) DllImport attempting to load: '__Internal'.
05-19 12:30:33.500 13187 13227 D DOTNET  : (Mono debug) DllImport searching in: '__Internal' ('(null)').
05-19 12:30:33.500 13187 13227 D DOTNET  : (Mono debug) Searching for 'GlobalizationNative_GetDefaultLocaleName'.
05-19 12:30:33.500 13187 13227 D DOTNET  : (Mono debug) DllImport attempting to load: 'libmonosgen-2.0.so'.
05-19 12:30:33.501 13187 13227 D DOTNET  : (Mono debug) DllImport error loading library 'libmonosgen-2.0.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
05-19 12:30:33.502 13187 13227 I chatty  : uid=10392(u0_a392) identical 1 line
05-19 12:30:33.503 13187 13227 D DOTNET  : (Mono debug) DllImport error loading library 'libmonosgen-2.0.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
05-19 12:30:33.503 13187 13227 D DOTNET  : (Mono warning) DllImport unable to load library 'libmonosgen-2.0.so'.
05-19 12:30:33.504 13187 13227 D DOTNET  : (Mono debug) DllImport attempting to load: '__Internal'.
05-19 12:30:33.504 13187 13227 D DOTNET  : (Mono debug) DllImport searching in: '__Internal' ('(null)').
05-19 12:30:33.504 13187 13227 D DOTNET  : (Mono debug) Searching for 'GlobalizationNative_GetDefaultLocaleName'.
05-19 12:30:33.504 13187 13227 D DOTNET  : (Mono debug) DllImport attempting to load: 'libmonosgen-2.0.so'.
05-19 12:30:33.505 13187 13227 D DOTNET  : (Mono debug) DllImport error loading library 'libmonosgen-2.0.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
05-19 12:30:33.506 13187 13227 I chatty  : uid=10392(u0_a392) identical 1 line
05-19 12:30:33.506 13187 13227 D DOTNET  : (Mono debug) DllImport error loading library 'libmonosgen-2.0.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
05-19 12:30:33.507 13187 13227 D DOTNET  : (Mono warning) DllImport unable to load library 'libmonosgen-2.0.so'.
05-19 12:30:33.536 13187 13227 D DOTNET  : ((null) warning) CLR: Managed code called FailFast, saying "Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_DllNotFoundException"
--------- beginning of crash
05-19 12:30:33.537 13187 13227 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 13227 (.dot.MonoRunner)
```

### PR DESCRIPTION
**Pull request by thaystg**
The linker was removing the icu shim functions even exporting them. The unique solution that we found until now is to force the linking using the -u flag.
This is a temporary fix until we mplement QCalls.
Fixes https://github.com/dotnet/runtime/issues/36685

### CODE REVIEW

File: src/mono/mono/metadata/native-library.c [hunk 1]
```diff
@@ -1272,7 +1272,7 @@ lookup_pinvoke_call_impl (MonoMethod *method, MonoLookupPInvokeStatus *status_ou
 			new_scope = g_strdup ("libcoreclr.dylib");
 #else			
 #if defined(TARGET_ANDROID)
-			new_scope = g_strdup ("libmonosgen-2.0.so");
+			new_scope = g_strdup ("libruntime-android.so");
```
Comment (EgorBo) [inline src/mono/mono/metadata/native-library.c:1275]: NOTE: I'll rename it later to the one XA uses (and I'll rename our runtime for tests) - `libmonodroid.so` as far as I remember

File: tools-local/tasks/mobile.tasks/AndroidAppBuilder/Templates/CMakeLists-android.txt [hunk 2]
```diff
@@ -13,4 +13,14 @@ target_link_libraries(
...
+    "-u GlobalizationNative_LoadICU"
+    "-u GlobalizationNative_GetLatestJapaneseEra"
+    "-u GlobalizationNative_ChangeCase"
+    "-u GlobalizationNative_CloseSortHandle"
+    "-u GlobalizationNative_GetLocales"
+    "-u GlobalizationNative_GetLocaleInfoInt"
+    "-u GlobalizationNative_GetLocaleTimeFormat"
+    "-u GlobalizationNative_ToUnicode"
+    "-u GlobalizationNative_NormalizeString"
+    "-u GlobalizationNative_GetTimeZoneDisplayName")
```
Comment (EgorBo) [inline tools-local/tasks/mobile.tasks/AndroidAppBuilder/Templates/CMakeLists-android.txt:26]: Not sure the list is complete, I'll check locally

**Review by EgorBo — APPROVED** [review]

**Comment by EgorBo** [comment]
LGTM

I am merging this in order to unblock Android Tests

**Comment by lambdageek** [comment]
The issue is that we put the ICU shims in `libmonosgen-2.0.a`, they are linked into `libruntime-android.so` - but the android runtime does not use any symbols from any of the constituent `.o` files in the archive.  Therefore the linker strips those files out.  We also tried `-Wl,-force_load,libmonosgen-2.0.a` and `-Wl,-all_load` which did not work.

The long term fix is #36449 - the ICU shims should be QCalls - the QCall table in the runtime will reference the symbols and they won't be stripped out.  This is a short-term fix.
