### PR TITLE
Don't suspend for debugger while holding the slot backpatching lock

### LINKED ISSUE #37278: Func eval unreliable in .NET 5 due to Tiered JIT
### Description

Debugger func eval tests are flaky on .NET 5. After much investigation, the problem is [this call to MethodDescBackpatchInfoTracker::IsLockOwnedByAnyThread](https://github.com/dotnet/runtime/blob/581dc193406082f76ae3c58511f724ab5d5c0d6d/src/coreclr/src/debug/ee/debugger.cpp#L15246).

That lock is owned by this thread:
```
Call stack for thread 0x21158:
Index  Function
--------------------------------------------------------------------------------
1      ntdll.dll!_ZwWaitForSingleObject@12()
2      KERNELBASE.dll!WaitForSingleObjectEx(void * hHandle, unsigned long dwMilliseconds, int bAlertable)
3      [Inline Frame] coreclr.dll!CLREventWaitHelper2(void *)
4      coreclr.dll!CLREventWaitHelper(void * handle, unsigned long dwMilliseconds, int alertable)
5      coreclr.dll!CLREventBase::WaitEx(unsigned long dwMilliseconds, WaitMode mode, PendingSync * syncState)
6      coreclr.dll!CLREventBase::Wait(unsigned long dwMilliseconds, int alertable, PendingSync * syncState)
7      coreclr.dll!Thread::WaitSuspendEventsHelper()
8      coreclr.dll!Thread::RareEnablePreemptiveGC()
---> 9      coreclr.dll!TieredCompilationManager::DeactivateTieringDelay()
10     coreclr.dll!TieredCompilationManager::TieringDelayTimerCallback(void * parameter, unsigned char timerFired)
11     coreclr.dll!ThreadpoolMgr::AsyncTimerCallbackCompletion(void * pArgs)
12     coreclr.dll!UnManagedPerAppDomainTPCount::DispatchWorkItem(bool * foundWork, bool * wasNotRecalled)
13     [Inline Frame] coreclr.dll!ThreadpoolMgr::ExecuteWorkRequest(bool *)
14     coreclr.dll!ThreadpoolMgr::WorkerThreadStart(void * lpArgs)
15     kernel32.dll!BaseThreadInitThunk(unsigned long RunProcessInit, long(__stdcall*)(void *) StartAddress, void * Argument)
16     ntdll.dll!__RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument)
17     ntdll.dll!_RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument)
```

Where I think the lock is acquired here: https://github.com/dotnet/runtime/blob/09602102dc1926dbf0ef8c53ccb9a9313abc3a83/src/coreclr/src/vm/tieredcompilation.cpp#L453

### Regression?

Seems to be a new problem in .NET 5

### PR DESCRIPTION
**Pull request by kouvel**
- Mostly reverted the previous workaround for the issue (commit fc06054a774e28a5a47bbe862adcf03251abb43c)
- Added a forbid-suspend-for-debugger region in preemptive GC mode
- Added a crst holder type that acquires a lock and enters the forbid region
- Where the slot backpatching lock would be taken where cooperative GC mode may be entered inside that lock, the new crst holder is used
- When a suspend for debugger is requested, a thread in preemptive GC mode that is in the forbid region is considered not yet suspended and is synched later similarly to threads in cooperative GC mode

Fixes https://github.com/dotnet/runtime/issues/37278

### CODE REVIEW

**Comment by kouvel** [comment]
CC @janvorli @mangod9 @noahfalk

**Comment by mangod9** [comment]
Was the previous fix incomplete which led to the issue re-occurring due to timing?

File: src/coreclr/src/vm/tieredcompilation.cpp [hunk 1]
```diff
@@ -448,8 +448,7 @@ void TieredCompilationManager::DeactivateTieringDelay()
         COUNT_T methodCount = methodsPendingCounting->GetCount();
         CodeVersionManager *codeVersionManager = GetAppDomain()->GetCodeVersionManager();
 
-        MethodDescBackpatchInfoTracker::PollForDebuggerSuspension();
-        MethodDescBackpatchInfoTracker::ConditionalLockHolder slotBackpatchLockHolder;
+        MethodDescBackpatchInfoTracker::ConditionalLockHolderForGCCoop slotBackpatchLockHolder;
```
Comment (mangod9) [inline src/coreclr/src/vm/tieredcompilation.cpp:451]: why is tiering enabled while under the debugger? Wouldnt the debugger enforce non-optimized code anyways?

**Comment by kouvel** [comment]
> Was the previous fix incomplete which led to the issue re-occurring due to timing?

The underlying issue was introduced when we started using cooperative GC mode for the slot backpatching info data structure. It was not obvious that such an issue would arise. The workaround used in the previous fix was a partial fix to the most problematic occurrences of the issue, we did not come up with a complete fix at the time after a fair bit of discussion, and the workaround was never intended to be a complete fix for the issue. The issue appears to be more problematic in 5.0 due to differences in the ways in which the lock is used. This change should be a complete fix for the issue.

File: src/coreclr/src/vm/tieredcompilation.cpp (hunk 1 above)
Comment (kouvel) [reply src/coreclr/src/vm/tieredcompilation.cpp:451]: I'm not sure what the relevance is to the code pointed out, can you clarify? Aside from that when tiering is enabled under the debugee (typical case), then the debugger needs to be able to handle that. Methods jitted while the debugger is attached may be generated with unoptimized code, but methods that are already jitted with optimizations when a debugger is attached are still optimized.

Comment (mangod9) [reply src/coreclr/src/vm/tieredcompilation.cpp:451]: Not relevant to the specific change, just commented since it was in tieredcompilation.cpp. Was just wondering why not just disable tiering when under the debugger.. is there a use case where Tiering is helpful while debugging?

Comment (kouvel) [reply src/coreclr/src/vm/tieredcompilation.cpp:451]: When a debugger attaches to an already-running process, it is typically attaching to a process that has tiering enabled, at an arbitrary point in time. The debugger needs to be able to handle the effects of tiering in the debugee despite any desire to disable or defer tiering activities while a debugger is attached. As for that desire, whether it is necessary or useful is probably a separate question.

**Review by mangod9 — APPROVED** [review]

**Comment by hoyosjs** [comment]
cc: @gregg-miskelly

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by noahfalk — APPROVED** [review]
Thanks Kount! This looks good to me. Given the subtleties in the area I don't have high confidence that I would spot an issue if there was one, but I am OK accepting that risk.

Long term this still feels a bit "princess and the pea" to me. The pea is that we designed a low-level data structure that requires co-op mode to access it, and then we've layered on a bunch of complex locking/suspend logic to resolve the undesirable effects (the mattresses in the analogy). As I recall the original purpose of the co-op mode datastructure was to simplify some lifetime management for state attached to collectible assemblies. My suspicion is that the amount of complexity and performance overhead we have added working around co-op mode outweighs the value we are getting from it. Of course I make no claim that I have carefully evaluated the alternatives, so it is only my hunch at this point.

**Comment by kouvel** [comment]
Thanks @noahfalk! Longer-term, avoiding coop mode would avoid some complication, though there are other complications it may not avoid. I haven't seen a startup perf hit from using the coop mode data structure initially or from this change, so there may not be any improvement from using a preemptive mode data structure. The alternative data structure may have to be a separate data structure and along with other changes that would go along with using it, it would be a bit too large/risky for .NET 5 at the moment. In the interest of simplifying some things it would be good longer-term to see if we can switch to a mostly preemptive mode solution.
