### PR TITLE
[wasm][debugger] Fix DebuggerTypeProxy for structs and for classes with multiple constructors

### LINKED ISSUE #68390: [wasm][debugger] Add support for ValueTypes in DebuggerProxyAttribute
Runtime does not support invoking .ctor on ValueType. 

Reproduction: remove `return null` from `GetValuesFromDebuggerProxyAttribute` and uncomment //FIXME: Issue #68390
https://github.com/dotnet/runtime/blob/87645922fe4b493213c6d4d9dfc936ad9c9b47b5/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L2273
Run test: `DebuggerTests.EvaluateOnCallFrameTests.EvaluateBrowsableRootHidden` with Theory data: "EvaluateBrowsableStruct" to evaluate `testPropertiesNone.list`.

Behavior:
for properties Invoke of .ctor fails in the runtime. In this case we are sending a buffer with 7 fields: 
```
240 0 0 0 0 0 0 0 0 1 17 0 0 0 0 0 9 0 0 0 7 18 0 0 0 21 29 0 0 0 22 14 0 0 0 8 240 29 2 0 0 0 1 0 0 0 2 17 1 0 0 0 0 3 0 0 0 1 8 0 0 0 0 17 0 0 0 0 0 4 0 0 0 2 8 0 0 0 100 2 0 0 0 1 18 0 0 0 23
```
First error is caused by runtime not supporting type == MONO_TYPE_SZARRAY inside of valueTypes. Adding this option to default case in `decode_value_internal` helps to get to the remaining errors.

For fields we are sending a buffer with 2 fields:
```
240 0 0 0 0 0 0 0 0 1 17 0 0 0 0 0 3 0 0 0 2 8 0 0 0 100 2 0 0 0 1
```
Invoke .ctor in fields returns an object of a collection type. While getting its members in `GetTypeMemberValues` we are calling InvokeMethod again, in `GetNonAutomaticPropertyValues` which results in another runtime exception.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/68390.
As a result of the discussion here: https://github.com/dotnet/runtime/pull/75958#discussion_r995534127I I separated the test fix into this PR. `EvaluateBrowsableRootHidden` when run on main is failing, so the quoted PR changes are not connected with the problem.
The problem: `DebuggerProxy` was working only in a specific case - when the proxy class had only one constructor with 1 argument or the constructor we intended to use was declared as the first one. 
Fix:
- we are able to serve multiple constructors and recognise the proper one by number of arguments and their type.
- we support `DebuggerProxy` for value types (not only classes).

Connected issues:
https://github.com/dotnet/runtime/issues/77315
https://github.com/dotnet/runtime/issues/77768

### CODE REVIEW

**Comment by radical** [comment]
What's the failure with the test? Is this related to https://github.com/dotnet/runtime/issues/76876 ?

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs [hunk 1]
```diff
@@ -150,8 +152,9 @@ private static string GetNamePrefixForValues(string memberName, string typeName,
                 {
                     // a collection - expose elements to be of array scheme
                     var memberNamedItems = members
-                        .Where(m => m["name"]?.Value<string>() == "Items" || m["name"]?.Value<string>() == "_items")
-                        .FirstOrDefault();
+                        .FirstOrDefault(m => m["name"]?.Value<string>() == "Items" || m["name"]?.Value<string>() == "_items");
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:155]: background:
- `List<T>` allocates a private array (`_items`) of `Capacity` size. The size for that can be obtained from `Capacity`, or `_items.Length`.
- It also has a private `int _size`, which has the number of *actual* elements in the list (`== list.Count`). And this changes when you add/remove elements to the list.
- At some threshold, `_items` array is reallocated to have a bigger size, and the elements are copied over.

https://github.com/dotnet/runtime/blob/51e3afb2ba42609c3711cb50fb5eaa6800bc1fde/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L25-L26

Based on that:
- `maxSize` is really the size of the internal array
- `_items` here makes sense, since that is a fixed private field in `List<T>` (specifically in `List<T>` though)
- Also, the type has `[DebuggerTypeProxy(typeof(ICollectionDebugView<>))]` which has:

https://github.com/dotnet/runtime/blob/51e3afb2ba42609c3711cb50fb5eaa6800bc1fde/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/ICollectionDebugView.cs#L19-L28

.. which returns an array of size == list.Count .

- So, is this using the type proxy, or are we reading from the actual object? If it's from the former then `Items`, and for the latter `_items` would be relevant. Feel free to correct me, I might be missing something.

**Comment by radical** [comment]
Oh, found the comment - https://github.com/dotnet/runtime/pull/75958#discussion_r995534127 .

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs (hunk 1 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:155]: I don't see any errors in the above. I only cannot understand what mechanism makes the decision if to use `Items` or `_items`. I don't think that it's too important but if we knew the rule it would help in simplifying the code. I think I will add some comments to the current code

**Comment by ilonatommy** [comment]
Actually it's strange. I reverted the changes on https://github.com/dotnet/runtime/pull/75958 that were fixing this failure and it's passing the CI. It might be something system-related then

**Comment by radical** [comment]
I tried to look at this, and found:

1. `GetValuesFromDebuggerProxyAttribute` is used only for *object* types, but it uses `ValueCreator.TryGetValueTypeById`:
https://github.com/dotnet/runtime/blob/10d342cecc5cbfc57419f8a92af4787f29d76c08/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L2121-L2128

- Even though the `objectId` is not for valuetypes, it can still find a value type with the same int id, and then end up incorrectly returning `null`. Instead, the value type part should be removed from this method completely. And maybe change the name to `GetValuesFromDebuggerProxyAttributeForObject`.
- This is the reason why sometimes the `DebuggerProxyType` for `List<T>` would get ignored, and you would get `_items` instead.

2. The way we are checking the values for `List<>` type is incorrect:
https://github.com/dotnet/runtime/blob/10d342cecc5cbfc57419f8a92af4787f29d76c08/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs#L1181-L1184

- `refListProp` should have the root-hidden contents of the list, IIUC based on https://github.com/dotnet/runtime/issues/76876 .
- So, it should not be using line 1183, and line 1184

- This reveals that RootHidden is not working for properties in types that are used as DebuggerProxyType (`ICollectionDebugView<>` used here on `List<>`).

- In `FindDebuggerProxyConstructorIdFor`, it doesn't find the correct set of `.ctor` methods because it is missing `BindingFlags.DeclaredOnly`, so it returns the `object..ctor` also

- Hopefully, we should be able to get rid of hardcoded `_items`, and `Items` check with these changes.

About the the corresponding test:
1. it is hacking around the returned result to pick out the values, and check them
2. it is checking the properties of the container object with the properties from the individual members, but this is self-referential. The test should instead check the returned results, with the *expected* output hardcoded in the tests. For example:

```csharp

                JObject[] expectedArrayElements = new[]
                {
                    TNumber(11),
                    TNumber(22)
                };
                JObject[] expectedListRootHiddenElements = new[]
                {
                    TNumber(1),
                    TNumber(2)
                };

                //in Console App names are in []
                //adding variable name to make elements unique
                for (int i = 0; i < expectedArrayElements.Length; i ++)
                {
                    var actualValObj = GetAndAssertObjectWithName(testRootHiddenProps, $"arrayRootHidden[{i}]");
                    await CheckValue(actualValObj["value"], expectedArrayElements[i], "x");
                }
                await CheckProps(refArrayProp, expectedArrayElements, "arrayRootHidden");

                for (int i = 0; i < expectedListRootHiddenElements.Length; i ++)
                {
                    var actualValObj = GetAndAssertObjectWithName(testRootHiddenProps, $"listRootHidden[{i}]");
                    await CheckValue(actualValObj["value"], expectedListRootHiddenElements[i], "listRootHidden");
                }
                await CheckProps(refListProp, expectedListRootHiddenElements, "listRootHidden");
```

This is the [incomplete patch](https://gist.github.com/radical/8f5c5cef970f650d41305aae3142dd84) that I was able to come up with.

File: src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs [hunk 2]
```diff
@@ -150,10 +150,10 @@ private static string GetNamePrefixForValues(string memberName, string typeName,
                 {
                     // a collection - expose elements to be of array scheme
                     var memberNamedItems = members
-                        .Where(m => m["name"]?.Value<string>() == "Items" || m["name"]?.Value<string>() == "_items")
+                        .Where(m => m["name"]?.Value<string>() == "Items")
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:153]: All cases in  DebuggerTests.EvaluateOnCallFrameTests.EvaluateBrowsableRootHidden because
```
Error Message:
   [] Could not find variable 'listRootHidden[0]'
```
This PR fixes only the problem with `Items` vs `_items` (now it's always `Items`). But it does not fix the fact that they need to get expanded manually - rootHidden info does not exist on them and cannot be easily extracted. The issue where we address it is this one: https://github.com/dotnet/runtime/issues/76876.

[the remark this answers is not in the document]
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:153]: Is my understanding here correct?:

1. `List<T>` has `[DebuggerTypeProxy(typeof(ICollectionDebugView<>))]`, so we look at the proxy
2. the proxy has `Items` property
3. `Items` has `[DebuggerBrowsable(DebuggerBrowsableState.RootHidden)]`, which isn't working yet (https://github.com/dotnet/runtime/issues/76876)
4. So, we are expanding `Items` here to work specifically for `List<T>`?

If so, then is this only to get `EvaluateBrowsableRootHidden` passing?
Also, does https://github.com/dotnet/runtime/issues/76876 still happen after the DebuggerTypeProxy fix here?

[the remark this answers is not in the document]
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:153]: I looked at it, and (4) is true. The test for `listRootHidden` should be disabled for now, and a comment mentioning the issue. And we can remove this incorrect hack.
And in a follow up PR, the root hidden issue can be fixed.

[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:153]: I would say it's a misunderstanding caused by me not deleting the dependency on non-fixed values in the tests properly. Manual expansion was not done on an object decorated with `RootHidden` but on `testPropertiesNone`. The `else` block is not to make the tests pass, it is necessary till `RootHidden` on `Items` will be received correctly by Proxy. It was the test that was not 100% logical.
I think now it will make more sense after the last commit.

Yes, the issue is still here. Proxy is not receiving any DebuggerAttributes assigned to `Items`, so it does not know it's of rootHidden type.

[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:153]: > I looked at it, and (4) is true. The test for `listRootHidden` should be disabled for now, and a comment mentioning the issue. And we can remove this incorrect hack. And in a follow up PR, the root hidden issue can be fixed.

Sorry, this comment did not display for me when I was investigating. I don't agree. This will break mechanism for all Collections that are in rootHidden objects. The `else` block can be removed when we have the fix already, so that we won't be changing the behavior from working to not working.

[the remark this answers is not in the document]
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs:153]: https://github.com/dotnet/runtime/blob/8064bfe0c2b1b90f9922767a4475685722eaeb78/src/mono/wasm/debugger/BrowserDebugProxy/MemberObjectsExplorer.cs#L149-L161

This code is *very explicitly* looking for a `Items` member which is an `array`. So, the `else` arm is affecting only the very specific types that have such a member, which is the case for `List<T>`. The proxy, or the debugger agent aren't populating it as an extra thing.

I agree that we shouldn't break the behavior in this PR. But it *is* incorrect. We want to avoid depending on magic like that, especially when proper mechanisms are available to get the information - `DebuggerTypeProxy` in this case.

The rootHidden issue is in addition to this, and that's fine to fix separately.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 3]
```diff
@@ -1178,47 +1178,67 @@ async Task EvaluateOnCallFrameFail(string call_frame_id, params (string expressi
...
+                    expectedListRootHiddenElements[0],
+                    expectedListRootHiddenElements[1],
+                    expectedClassRootHiddenElements[0],
+                    expectedClassRootHiddenElements[1],
+                    expectedStructRootHiddenElements[0],
+                    expectedStructRootHiddenElements[1]
+                };
+                // CheckProps for JArrays care about the order and here the order differs between InlineData
+                var testRootHiddenPropsSorted = new JArray(testRootHiddenProps.OrderBy(v => (string)v["name"]));
+                await CheckProps(testRootHiddenPropsSorted, expectedTestRootHiddenProps, "listRootHidden");
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1241]: If we are checking all the members here, then why are the earlier loops needed?

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 4]
```diff
@@ -1178,47 +1178,67 @@ async Task EvaluateOnCallFrameFail(string call_frame_id, params (string expressi
...
+                    expectedArrayElements[1],
+                    expectedListRootHiddenElements[0],
+                    expectedListRootHiddenElements[1],
+                    expectedClassRootHiddenElements[0],
+                    expectedClassRootHiddenElements[1],
+                    expectedStructRootHiddenElements[0],
+                    expectedStructRootHiddenElements[1]
+                };
+                // CheckProps for JArrays care about the order and here the order differs between InlineData
+                var testRootHiddenPropsSorted = new JArray(testRootHiddenProps.OrderBy(v => (string)v["name"]));
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1240]: The order matters, so we shouldn't adjust the results to match the test. The test types seem to have slightly different ordering of the fields/properties, which is causing the difference that you see. Making that consistent would allow not having to sort here.

I made these changes to the tests https://gist.github.com/radical/208598ae72b6310224dc531e3b66eff8 . Removing the sorting actually reveals that in case of root hidden, the members don't get added in the correct order. For example, you get `arrayRootHidden[0]` as the first member, but `arrayRootHidden[1]` is not the next one (it was the last in my run).

In general, we want to test the result as-is, as much as possible. And want to avoid adjusting the tests to match incorrect behavior. In case of incorrect behavior, we can have correct tests, but disabled with a corresponding issue.

But since we already have overlapping issues, you can either disable some tests, or patch them up as needed, to merge this PR. And in follow ups fix things to do it correctly.. thank you for being patient with it ;) Make sure to have some issue(s) tracking the TODOs.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs [hunk 5]
```diff
@@ -1178,47 +1178,67 @@ async Task EvaluateOnCallFrameFail(string call_frame_id, params (string expressi
...
+                {
+                    JObject.FromObject(new { value = TNumber(200), name = "sampleClassRootHidden.ClassId"}),
+                    JObject.FromObject(new { value = TObject("System.Collections.Generic.List<string>", description: "Count = 1"), name = "sampleClassRootHidden.Items"})
+                };
 
-                //in Console App names are in []
-                //adding variable name to make elements unique
-                foreach (var item in refListElementsProp)
+                // in Console App names are in []
+                // adding variable name to make elements unique
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1203]: Correct me if I'm wrong, but we are doing this only because the existing code in the proxy, and tests kinda assumes that the names will be unique in the get-properties results. Is there an open issue about that?

Comment (ilonatommy) [reply src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1203]: It's true, sending two elements with the same name resulted in an error. There was no issue about it, I made this one - https://github.com/dotnet/runtime/issues/77965.

File: src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs (hunk 3 above)
Comment (ilonatommy) [reply src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:1241]: Not needed, `CheckValue` calls `CheckProps`, so we can shorten this way by leaving only the quoted lines.

**Review by thaystg — APPROVED** [review]
LGTM.
