### PR TITLE
Prevent build scripts from letting random values through

### LINKED ISSUE #35222: Runtime build.cmd lets random values through
Follow up to #34782 

`Build.cmd` in the root of the `runtime` repo lets random values on several parameters pass and actually start the building process, only to fail much later with unrelated, and therefore misguiding errors. It is worth highlighting this happens both, on Windows and Linux. Running various cases, the flags that allow these "garbage" parameters are:
- Configuration
- OS
- Architecture

I've started working on this, but there are other things that remain unclear, which are preventing me of making further progress.

- Does `build.cmd` support any platform other than Windows? The `-help` says the possible options are `Windows_NT` and `Unix`, but the latter fails. This help documentation might need to be updated.
- On the other hand, `build.sh` lists a whole different (and bigger) list of supported platforms: Windows, Linux, FreeBSD, OSX, tvOS, iOS, Android, WebAssembly. Can I assume Windows is wrong here as `build.cmd` does that?

A funny story that added to my motivation on working on this fix, is that I spent so much time one day trying to build `runtime` only to fail over and over again. It turns out I had a typo in one of those flags.

### PR DESCRIPTION
**Pull request by ivdiazsa**
Fixes #35222 and a few more things.

The runtime repo's build scripts, `build.cmd` and `build.sh`, were allowing random values through certain flags, such as `--os`, `--arch`, and `--configuration`. This caused certain tasks prior to building like restoring projects to trigger, giving the user a false sense of security that it would work. However, later on, the build would obviously fail. The error messages shown would be entirely unrelated and therefore the user couldn't know what went wrong. This was a common scenario due to typos.

With this PR, invalid values to these flags are immediately called out to the user, alongside a suggestion on which arguments are valid for the given flag. This in turn prevents loss of time waiting for the eventual build failure.

As a follow up to improve the experience with these scripts, the letter casing restrictions in the Linux script (`build.sh`) have been removed. Users can now type `--os LINUX` or `--os linux` for example, and it will work. The casing stuff is now managed internally. Also, `--runtimeConfiguration` and `--librariesConfiguration` were fixed as well.

### CODE REVIEW

File: eng/build.sh [hunk 1]
```diff
@@ -116,23 +117,46 @@ while [[ $# > 0 ]]; do
...
-     if [ -z ${2+x} ]; then 
+      if [ -z ${2+x} ]; then 
         echo "No configuration supplied. See help (--help) for supported configurations." 1>&2
         exit 1
       fi
-      val="$(tr '[:lower:]' '[:upper:]' <<< ${2:0:1})${2:1}"
+      passedConfig="$(echo "$2" | awk '{print tolower($0)}')"
+      case "$passedConfig" in
+        debug|release|checked)
+          val="$(tr '[:lower:]' '[:upper:]' <<< ${passedConfig:0:1})${passedConfig:1}"
```
Comment (janvorli) [inline eng/build.sh:148]: A nit - you can avoid this double transformation (once using awk and then using tr) by just keeping the original command and then passing the `val` to case and checking for `Debug`, `Release` and `Checked`.

File: eng/build.sh [hunk 2]
```diff
@@ -116,23 +117,46 @@ while [[ $# > 0 ]]; do
...
+
      -arch)
       if [ -z ${2+x} ]; then 
         echo "No architecture supplied. See help (--help) for supported architectures." 1>&2
         exit 1
       fi
-      arch=$2
+      passedArch="$(echo "$2" | awk '{print tolower($0)}')"
+      case "$passedArch" in
+        x64|x86|arm|armel|arm64|wasm)
```
Comment (trylek) [inline eng/build.sh:128]: Is it intentional that <code>armel</code> is missing in <code>build.ps1</code> above?

**Review by trylek — APPROVED** [review]
LGTM, thank you for making our scripts more robust!

File: eng/build.sh (hunk 2 above)
Comment (janvorli) [reply eng/build.sh:128]: I think it is, as there is no armel flavor of Windows.

Comment (ivdiazsa) [reply eng/build.sh:128]: Yes, I followed the `help` command when adding these validations. Thanks for the clarification Jan!

File: eng/build.sh (hunk 1 above)
Comment (ivdiazsa) [reply eng/build.sh:148]: Do you mean by converting all to lowercase and then the first one to uppercase in the same command? I ask this because the `tr` command in `val` changes the first letter to uppercase, but leaves the rest untouched. That's why I'm using `awk` beforehand to convert everything to lowercase beforehand, in order to allow input like "RELEASE" to be valid. I'm removing the casing restrictions on the Linux scripts, aside from fixing the problems.

Comment (janvorli) [reply eng/build.sh:148]: I am sorry, I've misread the `tr` command.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!
