### PR TITLE
Fixup some Vector<T> function lookups to use the right name/type

### LINKED ISSUE #118848: Vector<T>.SquareRoot no longer vectorizing in .NET 10.0
### Description

The codegen for `Vector<T>.SquareRoot` in .NET 10.0 is no longer producing vectorized code like it did in .NET 9.0. This can be reproduced with [this microbenchmark](https://github.com/dotnet/performance/blob/05d29ee3ea9dd6aa124143a12c420a28d4c8e241/src/benchmarks/micro/libraries/System.Numerics.Vectors/Perf_VectorOfT.cs#L165).

### Regression?

Yes, this is a regression going from .NET 9.0 to .NET 10.0.

### Data

.NET 9.0
```
BenchmarkDotNet v0.14.1-nightly.20250107.205, Windows 11 (10.0.26100.4946)
.NET SDK 10.0.100-preview.7.25380.108
  [Host]     : .NET 9.0.8 (9.0.825.36511), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  Job-DCSEPH : .NET 9.0.8 (9.0.825.36511), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

PowerPlanMode=00000000-0000-0000-0000-000000000000  IterationTime=250ms  MaxIterationCount=20
MinIterationCount=15  WarmupCount=1

| Type                  | Method              | Mean      | Error     | StdDev    | Median    | Min       | Max       | Allocated |
|---------------------- |-------------------- |----------:|----------:|----------:|----------:|----------:|----------:|----------:|
| Perf_VectorOf<Double> | SquareRootBenchmark | 0.6996 ns | 0.0113 ns | 0.0106 ns | 0.6984 ns | 0.6827 ns | 0.7205 ns |         - |
| Perf_VectorOf<Single> | SquareRootBenchmark | 0.0445 ns | 0.0119 ns | 0.0111 ns | 0.0449 ns | 0.0257 ns | 0.0605 ns |         - |
```

.NET 10.0
```
BenchmarkDotNet v0.14.1-nightly.20250107.205, Windows 11 (10.0.26100.4946)
.NET SDK 10.0.100-preview.7.25380.108
  [Host]     : .NET 10.0.0 (10.0.25.38108), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  Job-CCVXYZ : .NET 10.0.0 (10.0.25.38108), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

PowerPlanMode=00000000-0000-0000-0000-000000000000  IterationTime=250ms  MaxIterationCount=20
MinIterationCount=15  WarmupCount=1

| Type                  | Method              | Mean     | Error     | StdDev    | Median   | Min      | Max      | Allocated |
|---------------------- |-------------------- |---------:|----------:|----------:|---------:|---------:|---------:|----------:|
| Perf_VectorOf<Double> | SquareRootBenchmark | 5.737 ns | 0.0415 ns | 0.0389 ns | 5.735 ns | 5.678 ns | 5.798 ns |         - |
| Perf_VectorOf<Single> | SquareRootBenchmark | 6.508 ns | 0.0496 ns | 0.0440 ns | 6.502 ns | 6.448 ns | 6.586 ns |         - |
```

### Analysis

The issue is related to codegen. 

.NET 9.0 is able to produce vectorized codegen for `Vector<T>.SquareRoot`, but .NET 10.0 does not vectorize the same code. 

Here is the codegen for `Vector<Single>.SquareRoot` as an example:

.NET 9.0
```
       vsqrtps   ymm0,[7FF816FAB740]
       vmovups   [rdx],ymm0
       mov       rax,rdx
       vzeroupper
       ret
```

.NET 10.0
```
       sub       rsp,58
       vbroadcastss ymm0,dword ptr [7FF7D9EDB4A8]
       vmovups   [rsp],ymm0
       vsqrtss   xmm0,xmm0,dword ptr [rsp]
       vmovss    dword ptr [rsp+20],xmm0
       vsqrtss   xmm0,xmm0,dword ptr [rsp+4]
       vmovss    dword ptr [rsp+24],xmm0
       vsqrtss   xmm0,xmm0,dword ptr [rsp+8]
       vmovss    dword ptr [rsp+28],xmm0
       vsqrtss   xmm0,xmm0,dword ptr [rsp+0C]
       vmovss    dword ptr [rsp+2C],xmm0
       vsqrtss   xmm0,xmm0,dword ptr [rsp+10]
       vmovss    dword ptr [rsp+30],xmm0
       vsqrtss   xmm0,xmm0,dword ptr [rsp+14]
       vmovss    dword ptr [rsp+34],xmm0
       vsqrtss   xmm0,xmm0,dword ptr [rsp+18]
       vmovss    dword ptr [rsp+38],xmm0
       vsqrtss   xmm0,xmm0,dword ptr [rsp+1C]
       vmovss    dword ptr [rsp+3C],xmm0
       vmovups   ymm0,[rsp+20]
       vmovups   [rdx],ymm0
       mov       rax,rdx
       vzeroupper
       add       rsp,58
       ret
```

I think this can be resolved by checking the method name during import [similar to these intrinsics](https://github.com/dotnet/runtime/blob/39aec194cbdf72f51feb93fdcecac86a337f69d7/src/coreclr/jit/importercalls.cpp#L10703) to make sure that `Vector<T>.SquareRoot` gets generated as the appropriate `NI_Vector128_Sqrt/NI_Vector256_Sqrt/NI_Vector512_Sqrt` intrinsic.

### LINKED ISSUE #119066: Vector.LessThan fails for negative floating point numbers (NET10 Preview 7)
### Description

We encountered an issue with Vector.LessThan because our UnitTests failed.
It seems that only negative floating numbers pairs (left,right) are affected. We have tried it width float and double where it fails. If one of left or right is negativem it works as expected.

We have also tried integer numbers (int, long). There it seems to work as normal.

### Reproduction Steps

```cs
Vector<float> left = new (-65f);
Vector<float> right = new(-1264f);

Assert.That(Vector.LessThan(left, right)[0] == 0);
Assert.That(Vector.LessThan(right, left)[0] == -1);
```

### Expected behavior

LessThan should return correct results when both values (left/right) are negative.

### Actual behavior

LessThan returns wrong values if left and right argument is negative.

### Regression?

It worked with .NET9, no with 10.0.100-preview.7.25380.108 it doesn't work anymore.

### Known Workarounds

Revert vectorized code back to linear.

### Configuration

.NET Version: 10.0.100-preview.7.25380.108
OS: Win11 23H2 (Build 22631.5768)
Architecture: x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #119066 and resolves #118848

This will need backport to .NET 10

### CODE REVIEW

File: src/tests/JIT/Regression/JitBlue/Runtime_119008/Runtime_119008.cs [hunk 1]
```diff
@@ -0,0 +1,19 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System;
+using System.Numerics;
+using Xunit;
+
+public class Runtime_118377
```
Comment (EgorBo) [inline src/tests/JIT/Regression/JitBlue/Runtime_119008/Runtime_119008.cs]: Mismatched class name

**Review by EgorBo — APPROVED** [review]

File: src/tests/JIT/Regression/JitBlue/Runtime_119008/Runtime_119008.cs (hunk 1 above)
Comment (tannergooding) [reply src/tests/JIT/Regression/JitBlue/Runtime_119008/Runtime_119008.cs]:
```suggestion
public class Runtime_119008
```
