### PR TITLE
Sve2 Scatters need a temp register for indices

### LINKED ISSUE #124750: JIT: non-temporal scatter store tests are failing
Example pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1305236&view=results
Example console log: https://helixr18s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4424d7e9872d488fa0/HardwareIntrinsics_Arm_ro/1/console.2d74b0ab.log

```
11:04:47.043 Running test: _Sve2_ro::JIT.HardwareIntrinsics.Arm._Sve2._Sve.Program.Sve2_Scatter16BitNarrowingNonTemporal_Indices_long_long()
Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunBasicScenario_Load
Beginning scenario: RunBasicScenario_FalseMask
Beginning scenario: RunBasicScenario_NonFaulting
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Sve2.Scatter16BitNarrowingNonTemporal(Int64, Int16*, Int64, Int64): RunStructLclFldScenario failed:
   mask: (1, 0)
  input: (598790890201539011, 197271212887199194)
indices: (1074, 1108)
 result: (0, 0)
```

These tests seem to have been added last week by #123892. cc @dotnet/arm64-contrib @ylpoonlg, can you please take a look with high priority?

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Failed test: _Sve2_ro::JIT.HardwareIntrinsics.Arm._Sve2._Sve.Program.Sve2_Scatter16BitNarrowingNonTemporal_Indices_long_long",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1305236
**Error message validated:** `[Failed test: _Sve2_ro::JIT.HardwareIntrinsics.Arm._Sve2._Sve.Program.Sve2_Scatter16BitNarrowingNonTemporal_Indices_long_long`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/23/2026 12:07:31 PM UTC

### PR DESCRIPTION
**Pull request by a74nh**
Fixes #124750

There are three forms of scatter instructions supported by CoreCLR
* Vector of addresses
* A single address plus a vector of indices (vector length offsets)
* A single address plus a vector of byte offsets

There are encodings for all of these in SVE1.

SVE2 duplicates all the scatter instructions, providing non temporal versions of them. The encodings all match SVE1, except for the indices version, which is missing. This can be replicated by simply shifting the offsets before calling the instruction (and is exactly what happens in the equivalent C++ instrinsics).

Therefore, ensure there is a temp register to hold the shifted value.

### CODE REVIEW

File: src/coreclr/jit/lsraarm64.cpp [hunk 1]
```diff
@@ -1386,6 +1365,19 @@ int LinearScan::BuildHWIntrinsic(GenTreeHWIntrinsic* intrinsicTree, int* pDstCou
     // Build any immediates
     BuildHWIntrinsicImmediate(intrinsicTree, intrin);
 
+    // Build any additional special cases
```
Comment (a74nh) [inline src/coreclr/jit/lsraarm64.cpp:1368]: I really don't like special casing here (there are no other special cases in the function). Ideally I'd add a hwintrinsic flag, but we're running out of space for them.

File: src/coreclr/jit/hwintrinsiccodegenarm64.cpp [hunk 2]
```diff
@@ -2471,6 +2468,18 @@ void CodeGen::genHWIntrinsic(GenTreeHWIntrinsic* node)
                 break;
             }
 
+            case NI_Sve2_Scatter16BitWithByteOffsetsNarrowingNonTemporal:
```
Comment (a74nh) [inline src/coreclr/jit/hwintrinsiccodegenarm64.cpp:2488]: Split these out to make the code easier to read

File: src/coreclr/jit/lsraarm64.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lsraarm64.cpp:1368]: xarch has similar special casing in its `BuildHWIntrinsic`, so at least it seems consistent across targets.

**Review by jakobbotsch — APPROVED** [review]
Thanks!
