### PR TITLE
Retry installer Process.Start if ETXTBSY

### LINKED ISSUE #53587: Host tests often fail on text file busy issues
<!-- runfo report start -->
Runfo Tracking Issue: [Host tests often fail on text file busy issues](https://runfo.azurewebsites.net/tracking/issue/133)
|Build|Definition|Kind|Run Name|
|---|---|---|---|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|0|0|

<!-- runfo report end -->

### PR DESCRIPTION
**Pull request by agocke**
Caused by https://github.com/dotnet/runtime/issues/58964

Fixes #53587

### CODE REVIEW

File: src/installer/tests/TestUtils/Command.cs [hunk 1]
```diff
@@ -196,7 +197,22 @@ public Command Start()
...
+                try
+                {
+                    Process.Start();
+                    break;
+                }
+                catch (Win32Exception e) when (e.Message.Contains("Text file busy"))
+                {
+                    // 10 ms is short, but the race we're trying to avoid is in-between
+                    // "fork" and "exec", so it should be fast
+                    Thread.Sleep(10);
```
Comment (vitek-karas) [inline src/installer/tests/TestUtils/Command.cs:213]: Ideally this should print out some diagnostics - so that we know it happened. Not sure if Console.WriteLine is the correct solution here - but it might be.

**Review by vitek-karas — APPROVED** [review]

File: src/installer/tests/TestUtils/Command.cs (hunk 1 above)
Comment (vitek-karas) [reply src/installer/tests/TestUtils/Command.cs:213]: Since this has been giving us trouble, having enough info to diagnose potential issues sounds like a good idea.
I know that we don't have existing diagnostics, but ideally that should not block us from adding them :wink:.

That said - I don't know how the diagnostics should look. Is there some existing mechanism for tests to output additional info to be used in case of failure (but honestly it would be great to get this even on passes if it's not too verbose).

File: src/installer/tests/TestUtils/Command.cs [hunk 2]
```diff
@@ -196,7 +197,22 @@ public Command Start()
...
+            // Retry if we hit ETXTBSY due to Linux race
+            // https://github.com/dotnet/runtime/issues/58964
+            for (int i = 0; i < 3; i++)
+            {
+                try
+                {
+                    Process.Start();
+                    break;
+                }
+                catch (Win32Exception e) when (e.Message.Contains("Text file busy"))
```
Comment (VSadov) [inline src/installer/tests/TestUtils/Command.cs:209]: catch should consider `i` - there should be an iteration that lets the exception propagate out.

File: src/installer/tests/TestUtils/Command.cs [hunk 3]
```diff
@@ -196,7 +197,22 @@ public Command Start()
 
             ReportExecBegin();
 
-            Process.Start();
+            // Retry if we hit ETXTBSY due to Linux race
+            // https://github.com/dotnet/runtime/issues/58964
+            for (int i = 0; i < 3; i++)
```
Comment (VSadov) [inline src/installer/tests/TestUtils/Command.cs:202]: just make this without `i < 3` and move the exit condition to the filter. - The exit should be either success or a crash.

File: src/installer/tests/TestUtils/Command.cs [hunk 4]
```diff
@@ -196,7 +197,22 @@ public Command Start()
...
+            {
+                try
+                {
+                    Process.Start();
+                    break;
+                }
+                catch (Win32Exception e) when (e.Message.Contains("Text file busy"))
+                {
+                    // 10 ms is short, but the race we're trying to avoid is in-between
+                    // "fork" and "exec", so it should be fast
```
Comment (VSadov) [inline src/installer/tests/TestUtils/Command.cs:212]: to balance latency and likelihood of waiting long enough, perhaps we should scale the backoff a little, like this could be `Sleep(i * 10)` ?

Comment (agocke) [reply src/installer/tests/TestUtils/Command.cs:212]: It's probably worth seeing if this solves the issue, but there's no reason we can't come back to it later.

File: src/installer/tests/TestUtils/Command.cs (hunk 1 above)
Comment (agocke) [reply src/installer/tests/TestUtils/Command.cs:213]: Unfortunately I don't know of a good logging mechanism at the moment. This code could be executed across many threads, so there would likely need to be some coordination for anything useful to come out.
