### PR TITLE
Fix the namespace of IServiceCollection.AddMetrics

### LINKED ISSUE #86885: Fix AddMetrics extension method namespace
**edited by @tarekgh adding the proposal section**
### Description

MetricsServiceExtensions has the namespace `Microsoft.Extensions.Diagnostics.Metrics`.That isn't the standard namespace for extensions methods on `IServiceCollection`. The standard namespace is `Microsoft.Extensions.DependencyInjection`.

https://github.com/dotnet/runtime/blob/8154757175ead0854b9cf914bff87e03d352a4ce/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/MetricsServiceExtensions.cs

For example, `Microsoft.Extensions.Http` correctly has `Microsoft.Extensions.DependencyInjection`: https://github.com/dotnet/runtime/blob/8154757175ead0854b9cf914bff87e03d352a4ce/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs

## Proposal
```diff

- namespace Microsoft.Extensions.Diagnostics.Metrics
+ namespace Microsoft.Extensions.DependencyInjection
{
    public static class MetricsServiceExtensions
    {
        public static IServiceCollection AddMetrics(this IServiceCollection services)
    }
}
```

### Reproduction Steps

In an ASP.NET Core app, try to configure metrics with `AddMetrics(config)` extension method.

### Expected behavior

`AddMetrics` automatically shows up in intellisense like other `AddXXX` methods that are in the `Microsoft.Extensions.DependencyInjection` namespace. That namespace is automatically added in ASP.NET Core apps.

### Actual behavior

Not automatically visible with intellisense and `Microsoft.Extensions.Diagnostics.Metrics` needs to be added.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/86885

### CODE REVIEW

**Comment by tarekgh** [comment]
@noahfalk @JamesNK could you please have a look? Thanks!

File: src/libraries/Microsoft.Extensions.Diagnostics/ref/Microsoft.Extensions.Diagnostics.cs [hunk 1]
```diff
@@ -1,7 +1,7 @@
 // Licensed to the .NET Foundation under one or more agreements.
 // The .NET Foundation licenses this file to you under the MIT license.
 
-namespace Microsoft.Extensions.Diagnostics.Metrics
+namespace Microsoft.Extensions.DependencyInjection
```
Comment (stephentoub) [inline src/libraries/Microsoft.Extensions.Diagnostics/ref/Microsoft.Extensions.Diagnostics.cs:4]: While you're here, the return null below should be throw null

**Review by stephentoub — APPROVED** [review]

**Review by noahfalk — APPROVED** [review]

**Review by JamesNK — APPROVED** [review]
