### PR TITLE
[mono][interp] Properly handle exceptions thrown by mono_marshal_get_native_wrapper

### LINKED ISSUE #101370: [mono][interpreter] Mono interpreter is crashing during System.Data.Odbc.Tests (linux-x64 Release Mono_Interpreter_LibrariesTests)
`linux-x64 Release Mono_Interpreter_LibrariesTests` job is crashing during execution of `System.Data.Odbc.Tests`

Build ID: https://dev.azure.com/dnceng-public/public/_build/results?buildId=651287
Helix log: https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-292fc48e84df4bd683/System.Data.Odbc.Tests/1/console.b19c4e76.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-292fc48e84df4bd683/System.Data.Odbc.Tests/1/console.b19c4e76.log?helixlogtype=result)

Stack trace:

```
=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fc46cdf8e86):0x7fc46cdf8e76  85 d2 0f 84 b2 2e 00 00 0f b7 73 04 48 8b 34 30  ..........s.H.40
0x7fc46cdf8e86  48 89 32 48 83 c3 06 0f b7 13 48 8d 35 d9 30 1d  H.2H......H.5.0.
0x7fc46cdf8e96  00 4d 89 e2 49 89 db 4d 89 fc 49 89 c7 ff 24 d6  .M..I..M..I...$.
0x7fc46cdf8ea6  66 2e 0f 1f 84 00 00 00 00 00 4c 89 f8 4d 89 e7  f.........L..M..

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeConstructorInfo:InternalInvoke <0x0008a>
	  at System.Reflection.MethodBaseInvoker:InterpretedInvoke_Constructor <0x0003c>
	  at System.Reflection.MethodBaseInvoker:InvokeWithNoArgs <0x0008e>
	  at System.RuntimeType:CreateInstanceMono <0x001e8>
	  at System.RuntimeType:CreateInstanceDefaultCtor <0x00066>
	  at System.Activator:CreateInstance <0x00094>
	  at System.RuntimeType:CreateInstanceImpl <0x00488>
	  at System.Activator:CreateInstance <0x00140>
	  at System.Activator:CreateInstance <0x00028>
	  at <>c__DisplayClass0_0:<CreateTestClass>b__0 <0x00032>
	  at Xunit.Sdk.ExecutionTimer:Aggregate <0x0002c>
	  at ReflectionAbstractionExtensions:CreateTestClass <0x000e8>
	  at Xunit.Sdk.TestInvoker`1:CreateTestClass <0x000c8>
	  at <<RunAsync>b__47_0>d:MoveNext <0x000c4>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.TestInvoker`1:<RunAsync>b__47_0 <0x00062>
	  at <RunAsync>d__10`1:MoveNext <0x00060>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x00076>
	  at Xunit.Sdk.TestInvoker`1:RunAsync <0x0003a>
	  at Xunit.Sdk.XunitTestRunner:InvokeTestMethodAsync <0x000a8>
	  at <InvokeTestAsync>d__4:MoveNext <0x00178>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.XunitTestRunner:InvokeTestAsync <0x00076>
	  at <>c__DisplayClass43_0:<RunAsync>b__0 <0x0002c>
	  at <RunAsync>d__10`1:MoveNext <0x00060>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x00076>
	  at <RunAsync>d__43:MoveNext <0x002aa>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.TestRunner`1:RunAsync <0x00062>
	  at Xunit.Sdk.XunitTestCaseRunner:RunTestAsync <0x00104>
	  at <RunAsync>d__19:MoveNext <0x001f0>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.TestCaseRunner`1:RunAsync <0x00062>
	  at Xunit.Sdk.XunitTestCase:RunAsync <0x0006a>
	  at Microsoft.DotNet.XUnitExtensions.SkippedFactTestCase:<>n__0 <0x0002c>
	  at <RunAsync>d__2:MoveNext <0x000bc>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Microsoft.DotNet.XUnitExtensions.SkippedFactTestCase:RunAsync <0x000c6>
	  at Xunit.Sdk.XunitTestMethodRunner:RunTestCaseAsync <0x00076>
	  at <RunTestCasesAsync>d__32:MoveNext <0x000fe>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.TestMethodRunner`1:RunTestCasesAsync <0x00062>
	  at <RunAsync>d__31:MoveNext <0x00114>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.TestMethodRunner`1:RunAsync <0x00062>
	  at Xunit.Sdk.XunitTestClassRunner:RunTestMethodAsync <0x000a2>
	  at <RunTestMethodsAsync>d__38:MoveNext <0x00382>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.TestClassRunner`1:RunTestMethodsAsync <0x00062>
	  at <RunAsync>d__37:MoveNext <0x0020e>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.TestClassRunner`1:RunAsync <0x00062>
	  at Xunit.Sdk.XunitTestCollectionRunner:RunTestClassAsync <0x000aa>
	  at <RunTestClassesAsync>d__28:MoveNext <0x001a4>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.TestCollectionRunner`1:RunTestClassesAsync <0x00062>
	  at <RunAsync>d__27:MoveNext <0x0020e>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0007a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0000e>
	  at Xunit.Sdk.TestCollectionRunner`1:RunAsync <0x00062>
	  at Xunit.Sdk.XunitTestAssemblyRunner:RunTestCollectionAsync <0x00076>
	  at <>c__DisplayClass14_2:<RunTestCollectionsAsync>b__2 <0x00092>
	  at System.Threading.Tasks.Task`1:InnerInvoke <0x00054>
	  at <>c:<.cctor>b__289_0 <0x0001c>
	  at System.Threading.ExecutionContext:RunInternal <0x000f2>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x001f2>
	  at System.Threading.Tasks.Task:ExecuteEntry <0x000b6>
	  at <>c:<.cctor>b__8_0 <0x0001c>
	  at Xunit.Sdk.MaxConcurrencySyncContext:RunOnSyncContext <0x00044>
	  at <>c__DisplayClass11_0:<WorkerThreadProc>b__0 <0x00056>
	  at System.Action`1:invoke_void_T <0x0007a>
	  at System.Threading.ExecutionContext:RunInternal <0x000f2>
	  at System.Object:lambda_method2 <0x0003a>
	  at Xunit.Sdk.ExecutionContextHelper:Run <0x00036>
	  at Xunit.Sdk.MaxConcurrencySyncContext:WorkerThreadProc <0x0016e>
	  at <>c:<QueueUserWorkItem>b__5_0 <0x0003a>
	  at System.Threading.Tasks.Task:InnerInvoke <0x00096>
	  at <>c:<.cctor>b__289_0 <0x0001c>
	  at System.Threading.ExecutionContext:RunInternal <0x000f2>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x001f2>
	  at System.Threading.Tasks.Task:ExecuteEntryUnsafe <0x00086>
	  at <>c:<.cctor>b__10_0 <0x00020>
	  at System.Object:runtime_invoke_direct_void__this__ <0x0024c>
	  at <unknown> <0x00000>
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "(core dumped) \"$RUNTIME_PATH/dotnet\" exec --runtimeconfig System.Data.Odbc.Tests.runtimeconfig.json",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=651287
**Error message validated:** `[(core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Data.Odbc.Tests.runtimeconfig.json`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/22/2024 8:41:27 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[881973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881973)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881973&view=ms.vss-test-web.build-test-results-tab&runId=23055858&resultId=216805)||
|[881617](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881617)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881617&view=ms.vss-test-web.build-test-results-tab&runId=23042768&resultId=216805)||
|[881547](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881547)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881547&view=ms.vss-test-web.build-test-results-tab&runId=23040422&resultId=216458)||
|[881304](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881304)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881304&view=ms.vss-test-web.build-test-results-tab&runId=23033810&resultId=216654)||
|[880658](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880658)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880658&view=ms.vss-test-web.build-test-results-tab&runId=23008702&resultId=216458)||
|[880651](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880651)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880651&view=ms.vss-test-web.build-test-results-tab&runId=23007460&resultId=216772)||
|[880527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880527)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880527&view=ms.vss-test-web.build-test-results-tab&runId=23002102&resultId=216457)||
|[880271](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880271)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880271&view=ms.vss-test-web.build-test-results-tab&runId=22994268&resultId=216474)||
|[880215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880215)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880215&view=ms.vss-test-web.build-test-results-tab&runId=22992932&resultId=216457)||
|[880112](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880112)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880112&view=ms.vss-test-web.build-test-results-tab&runId=22989738&resultId=216772)||
|[879417](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879417)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879417&view=ms.vss-test-web.build-test-results-tab&runId=22969764&resultId=216457)||
|[879353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879353)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879353&view=ms.vss-test-web.build-test-results-tab&runId=22966986&resultId=216771)||
|[879338](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879338)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879338&view=ms.vss-test-web.build-test-results-tab&runId=22966474&resultId=216457)||
|[879235](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879235)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879235&view=ms.vss-test-web.build-test-results-tab&runId=22962844&resultId=216455)||
|[879123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879123)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879123&view=ms.vss-test-web.build-test-results-tab&runId=22958954&resultId=216455)||
|[878914](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878914)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878914&view=ms.vss-test-web.build-test-results-tab&runId=22950414&resultId=216455)||
|[878908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878908)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878908&view=ms.vss-test-web.build-test-results-tab&runId=22950206&resultId=216767)||
|[878758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878758)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878758&view=ms.vss-test-web.build-test-results-tab&runId=22945818&resultId=216453)||
|[878139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878139)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878139&view=ms.vss-test-web.build-test-results-tab&runId=22925276&resultId=216767)||
|[877992](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877992)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877992&view=ms.vss-test-web.build-test-results-tab&runId=22918734&resultId=216767)||
|[877772](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877772)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877772&view=ms.vss-test-web.build-test-results-tab&runId=22910890&resultId=216767)||
|[877691](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877691)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877691&view=ms.vss-test-web.build-test-results-tab&runId=22906660&resultId=216767)||
|[877432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877432)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877432&view=ms.vss-test-web.build-test-results-tab&runId=22895294&resultId=216767)||
|[877066](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877066)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877066&view=ms.vss-test-web.build-test-results-tab&runId=22888820&resultId=216767)||
|[876414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=876414)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=876414&view=ms.vss-test-web.build-test-results-tab&runId=22868656&resultId=216767)||
|[875999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875999)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875999&view=ms.vss-test-web.build-test-results-tab&runId=22858826&resultId=216767)||
|[875455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875455)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875455&view=ms.vss-test-web.build-test-results-tab&runId=22843340&resultId=216768)||
|[874957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874957)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874957&view=ms.vss-test-web.build-test-results-tab&runId=22826652&resultId=216768)||
|[874394](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874394)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874394&view=ms.vss-test-web.build-test-results-tab&runId=22809708&resultId=216759)||
|[873781](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873781)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873781&view=ms.vss-test-web.build-test-results-tab&runId=22794420&resultId=216759)||
|[873030](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873030)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873030&view=ms.vss-test-web.build-test-results-tab&runId=22769002&resultId=216736)||
|[872567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=872567)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=872567&view=ms.vss-test-web.build-test-results-tab&runId=22755466&resultId=216736)||
|[871891](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871891)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871891&view=ms.vss-test-web.build-test-results-tab&runId=22732356&resultId=216736)||
|[871770](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871770)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871770&view=ms.vss-test-web.build-test-results-tab&runId=22727448&resultId=216736)||
|[871623](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871623)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871623&view=ms.vss-test-web.build-test-results-tab&runId=22722102&resultId=216736)||
|[871544](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871544)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871544&view=ms.vss-test-web.build-test-results-tab&runId=22718402&resultId=216736)||
|[871401](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871401)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871401&view=ms.vss-test-web.build-test-results-tab&runId=22712162&resultId=216736)||
|[871150](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871150)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871150&view=ms.vss-test-web.build-test-results-tab&runId=22705276&resultId=216736)||
|[871026](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871026)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871026&view=ms.vss-test-web.build-test-results-tab&runId=22701320&resultId=216444)||
|[870664](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870664)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870664&view=ms.vss-test-web.build-test-results-tab&runId=22687722&resultId=216736)||
|[870329](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870329)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870329&view=ms.vss-test-web.build-test-results-tab&runId=22674280&resultId=216444)||
|[870278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870278)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870278&view=ms.vss-test-web.build-test-results-tab&runId=22672640&resultId=216736)||
|[870074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870074)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=870074&view=ms.vss-test-web.build-test-results-tab&runId=22666914&resultId=216444)||
|[869615](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869615)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869615&view=ms.vss-test-web.build-test-results-tab&runId=22654262&resultId=216727)||
|[869114](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869114)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=869114&view=ms.vss-test-web.build-test-results-tab&runId=22641276&resultId=216727)||
|[868986](https://dev.azure.com/dnceng-public/public/_build/results?buildId=868986)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=868986&view=ms.vss-test-web.build-test-results-tab&runId=22638396&resultId=216444)||
|[868591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=868591)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=868591&view=ms.vss-test-web.build-test-results-tab&runId=22623522&resultId=216726)||
|[867963](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867963)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867963&view=ms.vss-test-web.build-test-results-tab&runId=22605934&resultId=216726)||
|[867425](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867425)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867425&view=ms.vss-test-web.build-test-results-tab&runId=22586450&resultId=216701)||
|[866931](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866931)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866931&view=ms.vss-test-web.build-test-results-tab&runId=22565568&resultId=216701)||
|[866682](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866682)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866682&view=ms.vss-test-web.build-test-results-tab&runId=22558326&resultId=216444)||
|[866215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866215)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866215&view=ms.vss-test-web.build-test-results-tab&runId=22541566&resultId=216702)||
|[866081](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866081)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=866081&view=ms.vss-test-web.build-test-results-tab&runId=22537162&resultId=216702)||
|[865898](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865898)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865898&view=ms.vss-test-web.build-test-results-tab&runId=22531036&resultId=216700)||
|[865724](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865724)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865724&view=ms.vss-test-web.build-test-results-tab&runId=22526836&resultId=216700)||
|[865503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865503)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865503&view=ms.vss-test-web.build-test-results-tab&runId=22520058&resultId=216700)||
|[865123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865123)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865123&view=ms.vss-test-web.build-test-results-tab&runId=22511762&resultId=216700)||
|[864427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864427)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864427&view=ms.vss-test-web.build-test-results-tab&runId=22494754&resultId=216699)||
|[864134](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864134)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=864134&view=ms.vss-test-web.build-test-results-tab&runId=22486078&resultId=216444)||
|[863922](https://dev.azure.com/dnceng-public/public/_build/results?buildId=863922)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=863922&view=ms.vss-test-web.build-test-results-tab&runId=22477790&resultId=216684)||
|[863308](https://dev.azure.com/dnceng-public/public/_build/results?buildId=863308)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=863308&view=ms.vss-test-web.build-test-results-tab&runId=22462406&resultId=216677)||
|[863052](https://dev.azure.com/dnceng-public/public/_build/results?buildId=863052)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=863052&view=ms.vss-test-web.build-test-results-tab&runId=22453936&resultId=216444)||
|[862974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=862974)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=862974&view=ms.vss-test-web.build-test-results-tab&runId=22451902&resultId=216669)||
|[862338](https://dev.azure.com/dnceng-public/public/_build/results?buildId=862338)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=862338&view=ms.vss-test-web.build-test-results-tab&runId=22436724&resultId=216669)||
|[861628](https://dev.azure.com/dnceng-public/public/_build/results?buildId=861628)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=861628&view=ms.vss-test-web.build-test-results-tab&runId=22415928&resultId=216669)||
|[860872](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860872)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860872&view=ms.vss-test-web.build-test-results-tab&runId=22392446&resultId=216585)||
|[860529](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860529)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860529&view=ms.vss-test-web.build-test-results-tab&runId=22382604&resultId=216444)||
|[860443](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860443)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860443&view=ms.vss-test-web.build-test-results-tab&runId=22380196&resultId=216585)||
|[860205](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860205)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860205&view=ms.vss-test-web.build-test-results-tab&runId=22376458&resultId=100539)|dotnet/runtime#105099|
|[859673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859673)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859673&view=ms.vss-test-web.build-test-results-tab&runId=22359390&resultId=216585)||
|[859580](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859580)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859580&view=ms.vss-test-web.build-test-results-tab&runId=22355820&resultId=216585)||
|[859395](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859395)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859395&view=ms.vss-test-web.build-test-results-tab&runId=22351872&resultId=216585)||
|[859273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859273)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859273&view=ms.vss-test-web.build-test-results-tab&runId=22348230&resultId=216585)||
|[859030](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859030)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859030&view=ms.vss-test-web.build-test-results-tab&runId=22340798&resultId=216585)||
|[858785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=858785)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=858785&view=ms.vss-test-web.build-test-results-tab&runId=22333898&resultId=216585)||
|[858306](https://dev.azure.com/dnceng-public/public/_build/results?buildId=858306)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=858306&view=ms.vss-test-web.build-test-results-tab&runId=22319636&resultId=216563)||
|[857959](https://dev.azure.com/dnceng-public/public/_build/results?buildId=857959)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=857959&view=ms.vss-test-web.build-test-results-tab&runId=22307970&resultId=216560)||
|[857281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=857281)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=857281&view=ms.vss-test-web.build-test-results-tab&runId=22287760&resultId=216560)||
|[857137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=857137)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=857137&view=ms.vss-test-web.build-test-results-tab&runId=22282436&resultId=100080)|dotnet/runtime#109135|
|[856935](https://dev.azure.com/dnceng-public/public/_build/results?buildId=856935)|dotnet/runtime|[System.Data.Odbc.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=856935&view=ms.vss-test-web.build-test-results-tab&runId=22271260&resultId=216560)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|24|80|

### PR DESCRIPTION
**Pull request by BrzVlad**
`mono_marshal_get_native_wrapper` can run some managed callbacks that can end up throwing an exception. This means both that if an exception is thrown we could leak compilation data and we weren't checking for the resume state, leading to executing bogus code when returning. This PR follows the approach JIT from https://github.com/mono/mono/pull/20177 to defer the throwing of exception when the method is actually called and not during compilation and we add the necessary resume state checks.

Should fix https://github.com/dotnet/runtime/issues/101370

### CODE REVIEW

File: src/mono/mono/mini/interp/transform.c [hunk 1]
```diff
@@ -2692,8 +2692,6 @@ static MonoMethod*
 interp_transform_internal_calls (MonoMethod *method, MonoMethod *target_method, MonoMethodSignature *csignature, gboolean is_virtual)
 {
 	if (((method->wrapper_type == MONO_WRAPPER_NONE) || (method->wrapper_type == MONO_WRAPPER_DYNAMIC_METHOD)) && target_method != NULL) {
-		if (target_method->flags & METHOD_ATTRIBUTE_PINVOKE_IMPL)
-			target_method = mono_marshal_get_native_wrapper (target_method, FALSE, FALSE);
 		if (!is_virtual && target_method->iflags & METHOD_IMPL_ATTRIBUTE_SYNCHRONIZED)
 			target_method = mono_marshal_get_synchronized_wrapper (target_method);
```
Comment (kotlarmilos) [inline src/mono/mono/mini/interp/transform.c:2696]: Can `mono_marshal_get_synchronized_wrapper` run managed callbacks that can end up throwing an exception as well?

**Review by kotlarmilos — APPROVED** [review]
