### PR TITLE
[Mono] added simple reverse pinvoke support to interpreter

### LINKED ISSUE #100010: [mono] Implement UnmanagedCallersOnly support for Swift calling convention
# Description

This issue tracks implementation progress of UnmanagedCallersOnly for the Swift calling convention. When a Swift function calls into .NET, it utilizes the `swiftself` and `swifterror` registers to pass context pointers according to the [calling convention](https://github.com/dotnet/designs/blob/main/proposed/swift-interop.md). In methods annotated with the `UnmanagedCallersOnly` attribute, users can add `SwiftSelf` argument to load `swiftself` register value. Additionally, users can add `SwiftError` argument to store an exception pointer into `swifterror` register.
 
The existing [runtime tests](https://github.com/dotnet/runtime/tree/main/src/tests/Interop/Swift/SwiftCallbackAbiStress) should be used for verification.

## Tasks
 - [x] https://github.com/dotnet/runtime/pull/101122
 - [ ] https://github.com/dotnet/runtime/pull/102185

**Note:** The default configuration on Apple and Apple mobile platforms uses the LLVM backend, but native wrappers are compiled with the mini backend. Efforts to enable LLVM compilation of native wrappers has been done in https://github.com/dotnet/runtime/pull/96910.

### PR DESCRIPTION
**Pull request by jkurdek**
Adds simple (no structs) Swift reverse pinvoke support to mono interpreter.

### CODE REVIEW

File: src/mono/mono/mini/interp/transform.c [hunk 1]
```diff
@@ -4417,6 +4417,43 @@ interp_method_compute_offsets (TransformData *td, InterpMethod *imethod, MonoMet
...
+		MonoClass *swift_error_ptr = mono_class_create_ptr (m_class_get_this_arg (swift_error));
+
+		int swift_error_index = -1;
+		for (int i = 0; i < sig->param_count; i++) {
+			MonoClass *klass = mono_class_from_mono_type_internal (sig->params [i]);
+			if (klass == swift_error_ptr) {
+				swift_error_index = i;
+				break;
+			}
+		}
```
Comment (jkurdek) [inline src/mono/mono/mini/interp/transform.c:4435]: We could probably hardcode type and allocate this variable without checking whether SwiftError* exists on signature

File: src/mono/mono/mini/mini-arm64.c [hunk 2]
```diff
@@ -2081,10 +2081,24 @@ mono_arch_set_native_call_context_ret (CallContext *ccontext, gpointer frame, Mo
...
 			storage = arg_get_storage (ccontext, ainfo);
+
+#ifdef MONO_ARCH_HAVE_SWIFTCALL
+		int swift_error_preserved_val = 0;
+		if (ccontext->gregs [PARAM_REGS + 2]) {
+			swift_error_preserved_val = ccontext->gregs [PARAM_REGS + 2];
+		}
+#endif
+
 		memset (ccontext, 0, sizeof (CallContext)); // FIXME
```
Comment (jkurdek) [inline src/mono/mono/mini/mini-arm64.c:2092]: The whole `swift_error_preserved` thing is to circumvent this memset. Do you have any better ideas how to go about it?

File: src/mono/mono/mini/interp/interp.c [hunk 3]
```diff
@@ -3195,6 +3209,11 @@ interp_entry_from_trampoline (gpointer ccontext_untyped, gpointer rmethod_untype
 		} else {
 			size = MINT_STACK_SLOT_SIZE;
 		}
+#ifdef MONO_ARCH_HAVE_SWIFTCALL
+		if (swift_error_arg_index >= 0 && swift_error_arg_index == i) {
+			newsp->data.p = swift_error_pointer;
```
Comment (BrzVlad) [inline src/mono/mono/mini/interp/interp.c:3214]: Shouldn't we also initialize `*swift_error_pointer` with `swift_error_data` before the call ?

File: src/mono/mono/mini/interp/transform.c [hunk 4]
```diff
@@ -4417,6 +4417,43 @@ interp_method_compute_offsets (TransformData *td, InterpMethod *imethod, MonoMet
...
+			td->vars [index].type = type;
+			td->vars [index].global = TRUE;
+			td->vars [index].offset = offset;
+			size = mono_interp_type_size (type, mt, &align);
+			td->vars [index].size = size;
+			interp_mark_ref_slots_for_var (td, index);
+
+			offset += size;
+			offset = ALIGN_TO (offset, MINT_STACK_ALIGNMENT);
+			imethod->swift_error_offset = td->vars [index].offset;
```
Comment (BrzVlad) [inline src/mono/mono/mini/interp/transform.c:4452]: I would rather have this with something like:
```
int var = interp_create_var_explicit (td, ..);
td->vars [var].global = TRUE;
interp_alloc_global_var_offset (td, var);
imethod->swift_error_offset = td->vars [var].offset;
```

File: src/mono/mono/mini/interp/transform.c [hunk 5]
```diff
@@ -4417,6 +4417,43 @@ interp_method_compute_offsets (TransformData *td, InterpMethod *imethod, MonoMet
...
+#ifdef MONO_ARCH_HAVE_SWIFTCALL
+	// Allocate SwiftError
+	if (mono_method_signature_has_ext_callconv (sig, MONO_EXT_CALLCONV_SWIFTCALL)) {
+		imethod->swift_error_offset = -1;
+
+		MonoClass *swift_error = mono_class_try_get_swift_error_class ();
+		MonoClass *swift_error_ptr = mono_class_create_ptr (m_class_get_this_arg (swift_error));
+
+		int swift_error_index = -1;
+		for (int i = 0; i < sig->param_count; i++) {
```
Comment (kotlarmilos) [inline src/mono/mono/mini/interp/transform.c:4429]: Is it possible to avoid another loop over params and do this in the loop before?

File: src/mono/mono/mini/mini-arm64.c (hunk 2 above)
Comment (BrzVlad) [reply src/mono/mono/mini/mini-arm64.c:2092]: Unfortunately I don't remember what is the point of this memset. I would get rid of it instead.

Comment (kotlarmilos) [reply src/mono/mono/mini/mini-arm64.c:2092]: Perhaps update the memset num to be `sizeof (CallContext) - CTX_REGS` when `MONO_ARCH_HAVE_SWIFTCALL`?

File: src/mono/mono/mini/interp/transform.c (hunk 1 above)
Comment (kotlarmilos) [reply src/mono/mono/mini/interp/transform.c:4435]: Sounds good. It can allocate a variable for `SwiftError*` if a signature is `SwiftCallConv`.

Comment (jkurdek) [reply src/mono/mono/mini/interp/transform.c]: I got rid of the loop as you suggested. I don't think there is a significant benefit of hardcoding it now. What you think?

**Comment by jkurdek** [comment]
Verified that using `SwiftSelf` in reverse pinvokes works with this changes.

**Review by kotlarmilos — APPROVED** [review]
LGTM!

File: src/mono/mono/mini/interp/interp.c [hunk 6]
```diff
@@ -3467,9 +3493,19 @@ interp_create_method_pointer (MonoMethod *method, gboolean compile, MonoError *e
...
-	entry_wrapper = mono_jit_compile_method_jit_only (wrapper, error);
+	bool skipWrapper = false;
+#ifdef MONO_ARCH_HAVE_SWIFTCALL
+	if (mono_method_signature_has_ext_callconv (sig, MONO_EXT_CALLCONV_SWIFTCALL))
+		/* Methods with Swift cconv should go to trampoline */
+		skipWrapper = true;
+#endif
+
+	MonoMethod *wrapper = NULL;
+	if (!skipWrapper) {
```
[the remark this answers is not in the document]
Comment (jkurdek) [reply src/mono/mono/mini/interp/interp.c:3505]: I think that we want to have both calls conditionally executed, not only the first one. Or am I missing something?

[the remark this answers is not in the document]
Comment (kotlarmilos) [reply src/mono/mono/mini/interp/interp.c]: Yes, that would require brackets as well.

File: src/mono/mono/mini/interp/transform.c [hunk 7]
```diff
@@ -4384,6 +4391,16 @@ interp_method_compute_offsets (TransformData *td, InterpMethod *imethod, MonoMet
 		td->vars [i].offset = offset;
 		interp_mark_ref_slots_for_var (td, i);
 		offset += size;
+
+#ifdef MONO_ARCH_HAVE_SWIFTCALL
+	if (swift_error_index < 0 && mono_method_signature_has_ext_callconv (sig, MONO_EXT_CALLCONV_SWIFTCALL)) {
+		MonoClass *klass = mono_class_from_mono_type_internal (type);
+		if (klass == swift_error_ptr) {
```
Comment (BrzVlad) [inline src/mono/mono/mini/interp/transform.c:4398]: We don't use brackets for single line blocks

**Review by BrzVlad — APPROVED** [review]

File: src/mono/mono/mini/interp/interp.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (jkurdek) [reply src/mono/mono/mini/interp/interp.c]: Well, but then we would have something like this, right? If you feel this is clearer, we can go with this

```c
#ifdef MONO_ARCH_HAVE_SWIFTCALL
	if (!mono_method_signature_has_ext_callconv (sig, MONO_EXT_CALLCONV_SWIFTCALL)) {
#endif
            wrapper = mini_get_interp_in_wrapper (sig);
	    entry_wrapper = mono_jit_compile_method_jit_only (wrapper, error);
#ifdef MONO_ARCH_HAVE_SWIFTCALL
}
#endif
```

[the remark this answers is not in the document]
Comment (BrzVlad) [reply src/mono/mono/mini/interp/interp.c]: In various places in the runtime we do stuff like:
```
#ifdef MONO_ARCH_HAVE_SWIFTCALL
	if (!mono_method_signature_has_ext_callconv (sig, MONO_EXT_CALLCONV_SWIFTCALL))
#endif
        {
            wrapper = mini_get_interp_in_wrapper (sig);
	    entry_wrapper = mono_jit_compile_method_jit_only (wrapper, error);
        }
```
