### PR TITLE
JIT: run local struct to field update in morph both pre and post order for returns

### LINKED ISSUE #74900: Test failure JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
Run: [runtime-coreclr jitstress 20220830.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1978087&view=ms.vss-test-web.build-test-results-tab&runId=50605536&resultId=104755&paneView=debug)

Failed test:
```
coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd

coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd

coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
- readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd
- readytorun\\determinism\\crossgen2determinism\\crossgen2determinism.cmd
- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd

coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- managed\\Compilation\\Compilation\\Compilation.cmd
```
**Error message:**
```
Assert failure(PID 3644 [0x00000e3c], Thread: 824 [0x0338]): Assertion failed 'ssaNum != SsaConfig::RESERVED_SSA_NUM' in 'Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol:Microsoft.Cci.ISignature.GetParameters(Microsoft.CodeAnalysis.Emit.EmitContext):System.Collections.Immutable.ImmutableArray`1[[Microsoft.Cci.IParameterTypeInformation, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]:this' during 'VN based copy prop' (IL size 64; hash 0x7a737bc2; FullOpts)

File: D:\a\_work\1\s\src\coreclr\jit\compiler.h Line: 358
Image: C:\h\w\992E0841\p\corerun.exe
Return code:      1
Raw output file:      C:\h\w\992E0841\w\9EF70957\uploads\Reports\JIT.Performance\CodeQuality\Roslyn\CscBench\CscBench.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\992E0841\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  CscBench.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\992E0841\p
C:\h\w\992E0841\w\9EF70957\e\JIT\Performance\CodeQuality\Roslyn\CscBench\CscBench.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Performance._CodeQuality_Roslyn_CscBench_CscBench_._CodeQuality_Roslyn_CscBench_CscBench_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
In some rare cases (currently only jitstress) morph may miss out in updating a return of a "struct that can be replaced by its field" with the field. But because we run local assertion prop after we check for this update, assertion prop it may change the local from one that could not be updated into one that could be, and if this happens, we miss out on a (required) update.

So, retry the update in post order, after the return operand has been morphed.

Fixes #74900.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

Not the most elegant solution, but pre-order morph and assertion prop are not playing together nicely.

Some minor diffs, eg

```diff
 G_M56927_IG01:        ; gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref, nogc <-- Prolog IG
                                                ;; size=0 bbWeight=1    PerfScore 0.00
 G_M56927_IG02:        ; gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref
        movsx    eax, cx
        dec      eax
        cwde
-       cwde
-                                               ;; size=6 bbWeight=1    PerfScore 1.00
+                                               ;; size=5 bbWeight=1    PerfScore 0.75
 G_M56927_IG03:        ; , epilog, nogc, extend
        ret
                                                ;; size=1 bbWeight=1    PerfScore 1.00
```

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -10243,6 +10243,18 @@ GenTree* Compiler::fgMorphSmpOp(GenTree* tree, MorphAddrContext* mac, bool* optA
...
                 }
+                // Local assertions may enable zero or copy prop.
+                //
+                if (fgGlobalMorph && optLocalAssertionProp && (optAssertionCount > 0) && op1->OperIs(GT_LCL_VAR))
+                {
+                    GenTree* newOp1 = op1;
+                    while (newOp1 != nullptr)
+                    {
+                        op1    = newOp1;
+                        newOp1 = optAssertionProp(apFull, newOp1, nullptr, nullptr);
```
Comment (SingleAccretion) [inline src/coreclr/jit/morph.cpp:10254]: It would feel like a lesser evil to "retry" replacing the local with its promoted field in post-order to me. It would be more in line with how the other decomposition transforms work.

Comment (AndyAyersMS) [reply src/coreclr/jit/morph.cpp:10254]: I agree it seems like a more natural fit. 

I had a version that did that, but it caused LSRA churn (though not too much).

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:10254]: > I had a version that did that, but it caused LSRA churn (though not too much).

It seems a bit surprising it did -- wouldn't the lack of this replacement cause the failure (assert) being fixed?

To be clear, I meant trying the replacement on both pre- and post- order.

**Comment by AndyAyersMS** [comment]
Native AOT tests timed out, seems like this is #75005 with a fix forthcoming.

File: src/coreclr/jit/morph.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/morph.cpp:10254]: Yes, I was trying it both places. I'll revive that version....

Comment (AndyAyersMS) [reply src/coreclr/jit/morph.cpp]: Looks like my earlier assessment was wrong; doing the update both pre and post order works nicely and has no diffs on win x64 or x86. 

Updated.

**Review by SingleAccretion — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
@jakobbotsch ping

**Review by jakobbotsch — APPROVED** [review]
