### PR TITLE
JIT: Determine which ARM64 HWIntrinsics will throw ArgumentOufOfRangeExceptions

### LINKED ISSUE #105479: JIT: Missing argument validation for `ExtractVector64` when optimizing
```csharp
// Generated by Fuzzlyn v2.0 on 2024-07-25 14:01:07
// Run on Arm64 Windows
// Seed: 15104036987171876681-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armsha1,armsha256,armsve
// Reduced from 16.0 KiB to 0.4 KiB in 00:00:39
// Debug: Throws 'System.ArgumentOutOfRangeException'
// Release: Runs successfully
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static void Main()
    {
        var vr5 = Vector64.Create(0, 0);
        var vr6 = Vector64.CreateScalar(1);
        var vr7 = (byte)Sve.Count16BitElements();
        AdvSimd.ExtractVector64(vr5, vr6, vr7);
    }
}
```

cc @dotnet/jit-contrib @dotnet/arm64-contrib

### PR DESCRIPTION
**Pull request by TIHan**
Resolves https://github.com/dotnet/runtime/issues/105479

### CODE REVIEW

File: src/tests/JIT/Regression/JitBlue/Runtime_105474/Runtime_105474.cs [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+#nullable disable
+
+public class Runtime_105474_A
+{
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    private void Method1()
+    {
+        Vector128<ulong> vr0 = Vector128.CreateScalar(1698800584428641629UL);
+        AdvSimd.ShiftLeftLogicalSaturate(vr0, 229);
```
Comment (kunalspathak) [inline src/tests/JIT/Regression/JitBlue/Runtime_105474/Runtime_105474.cs:18]: I thought we have coverage in unit test for invalid immediate too. can you double check why this problem didn't appear in those tests?

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @dotnet/arm64-contrib

File: src/coreclr/jit/hwintrinsic.h [hunk 2]
```diff
@@ -895,6 +895,14 @@ struct HWIntrinsicInfo
     }
 
 #ifdef TARGET_ARM64
+    static bool HasImmediateOperandRange(NamedIntrinsic id)
```
Comment (kunalspathak) [inline src/coreclr/jit/hwintrinsic.h:898]: `DuplicateSelectedScalarToVector128` has `HW_Flag_HasImmediateOperand` and not any of the `HW_Category_` flag in this method, but still it should check for the range.

```c#
/// <summary>
        /// uint8x16_t vdupq_lane_u8 (uint8x8_t vec, const int lane)
        ///   A32: VDUP.8 Qd, Dm[index]
        ///   A64: DUP Vd.16B, Vn.B[index]
        /// </summary>
        public static [Vector128](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Vector128_1.cs.html#a7d647b6968ad0f9)<byte> [DuplicateSelectedScalarToVector128](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Arm/AdvSimd.PlatformNotSupported.cs,c98f4003aa811a2f)([Vector64](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Vector64_1.cs.html#576983e071d8f012)<byte> value, [[ConstantExpected](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/ConstantExpectedAttribute.cs.html#12103fea5f68fa88)([Max](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/ConstantExpectedAttribute.cs.html#bcd0dee62624224e) = (byte)(7))] byte index) { throw new [PlatformNotSupportedException](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/PlatformNotSupportedException.cs.html#ad07c3864de72561)(); }
```

File: src/coreclr/jit/liveness.cpp [hunk 3]
```diff
@@ -1475,6 +1475,13 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
                     // or have a behavioral semantic that is undesirable to remove
                     break;
                 }
+#if defined(TARGET_ARM64)
```
Comment (kunalspathak) [inline src/coreclr/jit/liveness.cpp:1478]: can you elaborate on why we are doing this? Why was the repro working in Debug and not in Release?

File: src/coreclr/jit/gentree.h [hunk 4]
```diff
@@ -118,16 +118,23 @@ enum gtCallTypes : BYTE
...
-    StackOverflowException   = 0x20,
+    None                        = 0x0,
+    OverflowException           = 0x1,
+    DivideByZeroException       = 0x2,
+    ArithmeticException         = 0x4,
+    NullReferenceException      = 0x8,
+    IndexOutOfRangeException    = 0x10,
+    StackOverflowException      = 0x20,
+#ifdef TARGET_ARM64
+    ArgumentOutOfRangeException = 0x40,
```
Comment (tannergooding) [inline src/coreclr/jit/gentree.h:129]: Notably was talking about this with @jakobbotsch on Discord earlier and mentioned that we can't model `ArgumentOutOfRangeException` with `OperExceptions` because we can't reorder two such exceptions due to containing parameters.

I don't have the context as to why that is, but my guess is there's some other usage/handling of these that makes it problematic

File: src/tests/JIT/Regression/JitBlue/Runtime_105474/Runtime_105474.cs [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+            }
+            catch (Exception)
+            {
+                throw new Exception("Expected an ArgumentOutOfRangeException.");
+            }
+        }
+    }
+
+    [Fact]
+    public static void TestEntryPoint() => new Runtime_105474_A().Method0();
```
Comment (tannergooding) [inline src/tests/JIT/Regression/JitBlue/Runtime_105474/Runtime_105474.cs:42]: You probably want this to be:
```
if (AdvSimd.IsSupported)
{
    Assert.Throws<ArgumentOutOfRangeException>(() => new Runtime_105474_A().Method1());`
}
```

That way it uses the existing xunit functionality for validating something throws an expected exception

File: src/coreclr/jit/liveness.cpp [hunk 6]
```diff
@@ -1475,6 +1475,13 @@ void Compiler::fgComputeLifeLIR(VARSET_TP& life, BasicBlock* block, VARSET_VALAR
...
+                else if (HWIntrinsicInfo::HasImmediateOperandRange(intrinsicId))
```
Comment (tannergooding) [inline src/coreclr/jit/liveness.cpp:1479]: I think this bit is overly conservative. We don't need to preserve any intrinsic with an immediate range, rather only ones that have something we can't determine is in bounds.

Consider for example if it was `ShiftLeftLogicalSaturate(vr0, 1)`.

File: src/tests/JIT/Regression/JitBlue/Runtime_105474/Runtime_105474.cs (hunk 1 above)
Comment (tannergooding) [reply src/tests/JIT/Regression/JitBlue/Runtime_105474/Runtime_105474.cs:18]: We should validate that the `GT_HWINTRINSIC` node is marked `GTF_SIDE_EFFECT` when we insert the `GT_BOUNDS_CHK` node over `op2` here (this should be happening already as part of `GenTreeMultiOp::InitializeOperands` which runs in the constructor).

Beyond that, we likely need to also ensure that hwintrinsic nodes marked as `GTF_HW_USER_CALL` are also marked as `GTF_EXCEPT` when the allowed input range is a partial range and for that to be stripped in rationalization (where we already strip `GTF_HW_USER_CALL`) if it is determined to be "in range".

File: src/coreclr/jit/hwintrinsic.h (hunk 2 above)
Comment (TIHan) [reply src/coreclr/jit/hwintrinsic.h:898]: It should, though I'm not sure the best way to cover all the intrinsics that have a possible ArgumentOutOfRangeException without going through them one by one (which would take some time). At least this gets most of it blocked and we can fix the others as they come in through Fuzzlyn.

File: src/coreclr/jit/gentree.h (hunk 4 above)
Comment (TIHan) [reply src/coreclr/jit/gentree.h:129]: What should we do instead?

File: src/coreclr/jit/liveness.cpp (hunk 6 above)
Comment (TIHan) [reply src/coreclr/jit/liveness.cpp:1479]: It is conservative, but I think that's ok for now. Given this fixes a correctness issue now, we can figure out how to optimize it later.

Comment (tannergooding) [reply src/coreclr/jit/liveness.cpp:1479]: Normally I'd agree, but this is going to mark a very large number of core APIs as side effecting even when they aren't and will likely have impact to important workloads.

Today, the general logic of "do I need a bounds check" goes through `lookupImmBounds` followed by `addRangeCheckIfNeeded`, so I'd expect us to be able to use this to mark the `GT_HWINTRINSIC` as side effecting and then key this liveness check based on that.

I'd expect if we do that, it also solves the issue of ensuring all nodes which insert bounds checks are marked that way, without needing to use this separate `HasImmediateOperandRange` check

Comment (tannergooding) [reply src/coreclr/jit/liveness.cpp:1479]: For reference, here's where we check in rationalization for which operands are immediate and whether they are in range or not: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/rationalize.cpp#L457-L499

That then helps us decide whether or not we need to convert it back to a user call or if we can handle it "as is".

We have similar overall logic in the importer (https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsic.cpp and https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsicarm64.cpp, look for `addRangeCheckIfNeeded`), and I think we can mostly hook into the importation handling here to ensure this all works nicely and tracks the side effect.

File: src/coreclr/jit/hwintrinsic.h (hunk 2 above)
Comment (kunalspathak) [reply src/coreclr/jit/hwintrinsic.h:898]: can you open an issue for this?

**Comment by TIHan** [comment]
@dotnet/jit-contrib @tannergooding this is ready

**Review by tannergooding — APPROVED** [review]
LGTM, thanks for cleaning this up and simplifying the fix!

File: src/coreclr/jit/gentree.cpp [hunk 7]
```diff
@@ -7239,6 +7239,15 @@ bool GenTree::OperMayThrow(Compiler* comp)
         helper = comp->eeGetHelperNum(this->AsCall()->gtCallMethHnd);
         return ((helper == CORINFO_HELP_UNDEF) || !comp->s_helperCallProperties.NoThrow(helper));
     }
+#ifdef FEATURE_HW_INTRINSICS
+    else if (OperIsHWIntrinsic())
+    {
+        if ((gtFlags & (GTF_HW_USER_CALL | GTF_EXCEPT)) == (GTF_HW_USER_CALL | GTF_EXCEPT))
```
Comment (jakobbotsch) [inline src/coreclr/jit/gentree.cpp:7245]: `OperMayThrow` is expected to recompute whether we need to set `GTF_EXCEPT` on a node, without taking into account its operand nodes. This does take into account the operands nodes; I think instead the check should be:
```suggestion
        if ((gtFlags & GTF_HW_USER_CALL) != 0)
```

**Comment by jakobbotsch** [comment]
I think there is one more thing we need to do here. Right now `OperExceptions` is invalid to call on these hw intrinsics; it will return an incorrect result, and some functions (like forward sub and call args morphing) can end up reordering these intrinsics illegally.
Can you add an assert in `OperExceptions` for the `GT_HWINTRINSIC` case that `GTF_HW_USER_CALL` is not set? Then, to make sure that callers do not try to reorder these intrinsics you will have to also set `GTF_CALL` on the node where we are now setting `GTF_HW_USER_CALL | GTF_EXCEPT`.

I notice that `GenTreeHWIntrinsic::OperRequiresCallFlag` is already correct (ends up checking `GTF_HW_USER_CALL`), so that one doesn't look like it will need to change.

**Comment by TIHan** [comment]
@jakobbotsch this is ready, made the changes you suggested

**Review by jakobbotsch — APPROVED** [review]
