### PR TITLE
IANA To/From Windows Ids Conversion APIs

### LINKED ISSUE #49407: Time Zone IANA Ids to/From Windows Ids conversion APIs
## Background and Motivation

It is planned in 6.0 release to start supporting the IANA time zone Ids on Windows and support Windows Ids on non-Windows platforms (e.g. Linux). That will allow users to use any time zone Id across all platforms without worrying what Id work on what platform. 
In addition to that, users need to be able to convert any Windows Id to IANA Id and vice versa. The proposal here is to provide the needed APIs to do that. 

As we are using ICU library for supporting IANA Ids and the conversion, we'll be limited to provide this functionality only when running with ICU. i.e. this functionality is not going to be supported in the Globalization Invariant mode nor when enabling NLS mode on Windows. Because of this limitation, the proposed APIs is using `TryConvert` pattern to allow users check for the conversion failures without throwing any exception.

## Proposed API

```C#

namespace System
{
    public sealed partial class TimeZoneInfo : IEquatable<TimeZoneInfo?>, ISerializable, IDeserializationCallback
    {
        // Tells if the current TimeZoneInfo Id is Iana Id or not.
        public readonly bool HasIanaId { get; }

        // Try to convert from Iana Id to Windows Id.
        public static bool TryConvertIanaIdToWindowsId(string ianaId, out string windowsId);

        // Try to convert from Windows Id to Iana Id.
        public static bool TryConvertWindowsIdToIanaId(string windowsId, out string ianaId);
        public static bool TryConvertWindowsIdToIanaId(string windowsId, string region, out string ianaId);
    }
}

```

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/49407

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @mattjohnsonpint @safern @eerhardt

**Comment by tarekgh** [comment]
@marek-safar @eerhardt @lewing could you please advise what is wrong here? 
https://dev.azure.com/dnceng/public/_build/results?buildId=1082685&view=logs&jobId=f217f715-90ad-5404-53bd-b93e3b80f465&j=f217f715-90ad-5404-53bd-b93e3b80f465&t=d9b45970-da80-576b-c4ba-5d7bc638e9e8

This is browser/AOT/Mono error. do we need to add something to Mono's runtime or should I exclude it?

**Comment by filipnavara** [comment]
Browser configurations do not contain the time zone data and hence the Interop file is also excluded:

https://github.com/dotnet/runtime/blob/486757d783a9769a44080e11f83c290efa401716/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems#L1106-L1108

This was already mentioned in one of the issues related to time zone names.

File: src/libraries/Common/src/Interop/Interop.TimeZoneInfo.cs [hunk 1]
```diff
@@ -16,9 +16,9 @@ internal static partial class Globalization
             int resultLength);
 
         [DllImport(Libraries.GlobalizationNative, CharSet = CharSet.Unicode, EntryPoint = "GlobalizationNative_WindowsIdToIanaId")]
-        internal static extern unsafe int WindowsIdToIanaId(string windowsId, char* ianaId, int ianaIdLength);
+        internal static extern unsafe int WindowsIdToIanaId(string windowsId, string? region, ref char ianaId, int ianaIdLength);
 
         [DllImport(Libraries.GlobalizationNative, CharSet = CharSet.Unicode, EntryPoint = "GlobalizationNative_IanaIdToWindowsId")]
-        internal static extern unsafe int IanaIdToWindowsId(string ianaId, char* windowsId, int windowsIdLength);
+        internal static extern unsafe int IanaIdToWindowsId(string ianaId, ref char windowsId, int windowsIdLength);
```
Comment (eerhardt) [inline src/libraries/Common/src/Interop/Interop.TimeZoneInfo.cs:22]: I didn't think we were supposed to use `ref char` in P/Invoke signatures because it isn't just a single char being referenced, but a whole sequence of chars.

**Comment by eerhardt** [comment]
> @marek-safar @eerhardt @lewing could you please advise what is wrong here?
https://dev.azure.com/dnceng/public/_build/results?buildId=1082685&view=logs&jobId=f217f715-90ad-5404-53bd-b93e3b80f465&j=f217f715-90ad-5404-53bd-b93e3b80f465&t=d9b45970-da80-576b-c4ba-5d7bc638e9e8

> This is browser/AOT/Mono error. do we need to add something to Mono's runtime or should I exclude it?

See 

https://github.com/dotnet/runtime/blob/87798e77ba3bf84bc16645305ca268d20cb81dc6/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems#L1106-L1108

This falls into the same category as https://github.com/dotnet/runtime/issues/50210. We need to make sure we aren't regressing size on Blazor WASM when we are making new calls to ICU.

File: src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs [hunk 2]
```diff
@@ -2638,6 +2638,63 @@ public static void UsingAlternativeTimeZoneIdsTest(string windowsId, string iana
...
+            {
+                Assert.True((expected || tzi.Id.Equals("Utc", StringComparison.OrdinalIgnoreCase)) == tzi.HasIanaId, $"`{tzi.Id}` has wrong IANA Id indicator");
+            }
+
+            Assert.False(TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time").HasIanaId, $"`Pacific Standard Time` should not be IANA Id.");
+            Assert.True(TimeZoneInfo.FindSystemTimeZoneById("America/Los_Angeles").HasIanaId, $"'America/Los_Angeles' should be IANA Id");
+        }
+
+        [ConditionalTheory(nameof(SupportIanaNamesConversion))]
+        [InlineData("Pacific Standard Time", "America/Los_Angeles")]
```
Comment (eerhardt) [inline src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:2658]: Is this the same data that is used in `UsingAlternativeTimeZoneIdsTest` above? Can we refactor it and combine it so it is only defined once?

File: src/libraries/Common/src/Interop/Interop.TimeZoneInfo.cs (hunk 1 above)
Comment (tarekgh) [reply src/libraries/Common/src/Interop/Interop.TimeZoneInfo.cs:22]: The address of the first character is the same as the address of the whole string. I can change this to char* but that will make the calling site unsafe which I am not seeing a reason we need to do so. 

@jkotas may advise about that.

File: src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs (hunk 2 above)
Comment (tarekgh) [reply src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:2658]: It has some difference. this one I need it to round trip while the other doesn't have to round trip. I am expecting in the future we may need to add more and both data will diverge. So, I prefer to keep it liek that.

**Comment by tarekgh** [comment]
@lewing @eerhardt 

> This falls into the same category as #50210. We need to make sure we aren't regressing size on Blazor WASM when we are making new calls to ICU.

Thanks for the reply. I want to confirm, are we ok excluding this new functionality for browser? these new APIs wouldn't work at all.

File: src/libraries/Common/src/Interop/Interop.TimeZoneInfo.cs (hunk 1 above)
Comment (jkotas) [reply src/libraries/Common/src/Interop/Interop.TimeZoneInfo.cs:22]: Using `ref char windowsId` to represent address of a string is even more unsafe pattern than `char*`. I have a strong preference for using `char*` in cases like this one.

> make the calling site unsafe 

You are using `MemoryMarshal.GetReference` at the callsite that is pretty unsafe even though the C# does not require unsafe C# for it.

Comment (tarekgh) [reply src/libraries/Common/src/Interop/Interop.TimeZoneInfo.cs:22]: Yes, I meant not intentionally marking the code `unsafe`. The question now, do you have any concern using `ref char` for a stack buffer?

Comment (tarekgh) [reply src/libraries/Common/src/Interop/Interop.TimeZoneInfo.cs:22]: I'll change back to `char*` anyway. Thanks all.

**Comment by lewing** [comment]
> @lewing @eerhardt
> 
> > This falls into the same category as #50210. We need to make sure we aren't regressing size on Blazor WASM when we are making new calls to ICU.
> 
> Thanks for the reply. I want to confirm, are we ok excluding this new functionality for browser? these new APIs wouldn't work at all.

We'd be happy to support this optionally but the size impact is large enough that it we probably can't do it by default.  Just referencing the symbols pulled in 40k of compressed runtime size in #50210 and @tqiu8 can weigh in with the actual zone data sizes but if memory serves even just "en" was huge.

**Comment by tarekgh** [comment]
@eerhardt I have addressed the feedback. do you have any more comments or we are good to go?

**Comment by mattjohnsonpint** [comment]
@lewing - not sure exactly what changes would be required for packaging, but this feature would only need the [`windowsZones`](https://github.com/dotnet/icu/blob/maint/maint-67/icu/icu4c/source/data/misc/windowsZones.txt) file.

**Comment by mattjohnsonpint** [comment]
Oh wait - it would also need to be able to resolve aliases.  In CLDR, that's done in [`timezone.xml`](https://github.com/unicode-org/cldr/blob/master/common/bcp47/timezone.xml).  I think that might be part of the [`zoneinfo64`](https://github.com/dotnet/icu/blob/maint/maint-67/icu/icu4c/source/data/misc/zoneinfo64.txt) data file in ICU.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs [hunk 3]
```diff
@@ -950,14 +962,111 @@ public bool HasSameRules(TimeZoneInfo other)
...
+            return false;
+        }
+
+        /// <summary>
+        /// Tries to convert Windows time zone Id to IANA Id.
+        /// </summary>
+        /// <param name="windowsId">The Windows time zone Id.</param>
+        /// <param name="ianaId">String object hold the IANA Id which resulted from the Windows Id conversion.</param>
+        /// <returns>True if the Id conversion succeed, false otherwise .</returns>
+        public static bool TryConvertWindowsIdToIanaId(string windowsId, out string? ianaId) => TryConvertWindowsIdToIanaId(windowsId, null, out ianaId);
```
Comment (iSazonov) [inline src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:1023]: The same about NotNullWhen

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs [hunk 4]
```diff
@@ -950,14 +962,111 @@ public bool HasSameRules(TimeZoneInfo other)
...
+
+        /// <summary>
+        /// Tries to convert Windows time zone Id to IANA Id.
+        /// </summary>
+        /// <param name="windowsId">The Windows time zone Id.</param>
+        /// <param name="region">The ISO 3166 for the country/region.</param>
+        /// <param name="ianaId">String object hold the IANA Id which resulted from the Windows Id conversion.</param>
+        /// <returns>True if the Id conversion succeed, false otherwise .</returns>
+        public static unsafe bool TryConvertWindowsIdToIanaId(string windowsId, string? region, out string? ianaId)
```
Comment (iSazonov) [inline src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:1032]: The same about NotNullWhen

File: src/libraries/System.Runtime/ref/System.Runtime.cs [hunk 5]
```diff
@@ -3890,6 +3891,9 @@ public sealed partial class TimeZoneInfo : System.IEquatable<System.TimeZoneInfo
         void System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
         public string ToSerializedString() { throw null; }
         public override string ToString() { throw null; }
+        public static bool TryConvertIanaIdToWindowsId(string ianaId, out string windowsId) { throw null; }
```
Comment (eerhardt) [inline src/libraries/System.Runtime/ref/System.Runtime.cs:3894]: Why isn't `out string windowsId` nullable?

Should it be `out string? windowsId` to match `TryConvertWindowsIdToIanaId`? It also looks like this doesn't match the src file.

File: src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c [hunk 6]
```diff
@@ -21,13 +21,36 @@ static const UChar EXEMPLAR_CITY_PATTERN_UCHAR[] = {'V', 'V', 'V', '\0'};
...
-int32_t GlobalizationNative_WindowsIdToIanaId(const UChar* windowsId, UChar* ianaId, int32_t ianaIdLength)
+int32_t GlobalizationNative_WindowsIdToIanaId(const UChar* windowsId, const UChar* region, UChar* ianaId, int32_t ianaIdLength)
 {
     UErrorCode status = U_ZERO_ERROR;
 
     if (ucal_getTimeZoneIDForWindowsID_ptr != NULL)
     {
-        int32_t ianaIdFilledLength = ucal_getTimeZoneIDForWindowsID(windowsId, -1, NULL, ianaId, ianaIdLength, &status);
+        #define BUFFER_LENGTH 41 // enough length for the region code including the null termination
+        char buffer[BUFFER_LENGTH];
```
Comment (eerhardt) [inline src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: Why copy `region` into a buffer? Can't we just pass it through? It is a managed string, so it should always be NULL terminated.

File: src/libraries/System.Runtime/ref/System.Runtime.cs (hunk 5 above)
Comment (tarekgh) [reply src/libraries/System.Runtime/ref/System.Runtime.cs:3894]: Yes, I just missed it. thanks.

File: src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c (hunk 6 above)
Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: I have to convert it from UChar to char.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs [hunk 7]
```diff
@@ -950,14 +962,111 @@ public bool HasSameRules(TimeZoneInfo other)
...
+        /// </summary>
+        /// <param name="ianaId">The IANA time zone Id.</param>
+        /// <param name="windowsId">String object hold the Windows Id which resulted from the IANA Id conversion.</param>
+        /// <returns>True if the Id conversion succeed, false otherwise .</returns>
+        public static unsafe bool TryConvertIanaIdToWindowsId(string ianaId, out string? windowsId)
+        {
+            windowsId = null;
+
+            // This functionality is not enabled in the browser for the sake of size reduction.
+#if !TARGET_BROWSER
```
Comment (eerhardt) [inline src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:989]: Can we refactor these `#if`s out into separate partial files? We've been trying hard not to use `#if` in these files.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs [hunk 8]
```diff
@@ -950,14 +962,111 @@ public bool HasSameRules(TimeZoneInfo other)
...
+        /// <param name="windowsId">The Windows time zone Id.</param>
+        /// <param name="region">The ISO 3166 for the country/region.</param>
+        /// <param name="ianaId">String object hold the IANA Id which resulted from the Windows Id conversion.</param>
+        /// <returns>True if the Id conversion succeed, false otherwise .</returns>
+        public static unsafe bool TryConvertWindowsIdToIanaId(string windowsId, string? region, out string? ianaId)
+        {
+            ianaId = null;
+
+            // This functionality is not enabled in the browser for the sake of size reduction.
+#if !TARGET_BROWSER
```
Comment (eerhardt) [inline src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:1037]: Can we refactor these `#if`s out into separate partial files? We've been trying hard not to use `#if` in these files.

Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:1037]: That will introduce a new file for just this small case. currently we have many TimeZoneInfo.?????.cs files which became very confusing. let me know if you still think it is worth splitting that to a new file.

File: src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c (hunk 6 above)
Comment (eerhardt) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: Can we just use the Marshaling to do this for us? Make the method signature be:

```C
int32_t GlobalizationNative_WindowsIdToIanaId(const UChar* windowsId, const char* region, UChar* ianaId, int32_t ianaIdLength)
```

And then on the managed side:

```C#
        [DllImport(Libraries.GlobalizationNative, CharSet = CharSet.Unicode, EntryPoint = "GlobalizationNative_WindowsIdToIanaId")]
        internal static extern unsafe int WindowsIdToIanaId(string windowsId, [MarshalAs(UnmanagedType.LPStr)] string? region, char* ianaId, int ianaIdLength);

Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: I can try that if you are sure this is safe.

Comment (eerhardt) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: I'm not 100% sure how CharSet and `MarshalAs` work together. My assumption is that `MarshalAs` overrides the CharSet on the DllImport.

Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: I'll follow up with the Interop guys on that. Thanks for the idea.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs (hunk 8 above)
Comment (eerhardt) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:1037]: See https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/project-guidelines.md#conventions-for-forked-code.

> In general we prefer different code files over #ifdef's because it forces us to better factor the code which leads to easier maintenance over time.

Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:1037]: Yes, I know that. we already using `#if TARGET_BROWSER` in other places too for the case we think it is not worth splitting to a file. anyway, I'll move it to its own file. do you have suggestion for the file name? `TimeZoneInfo.NonBrowser.cs`?

Comment (eerhardt) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:1037]: I think we could reuse the `FullGlobalizationData` and `MinimalGlobalizationData` files. The `FullGlobalizationData` may need to get split into `Unix` and `Windows` though....

Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:1037]: > The FullGlobalizationData may need to get split into Unix and Windows though....

That will require me duplicating the code in both files if we do that. We have to have a file that compile for Linux and Windows and not for the browser.

Comment (eerhardt) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs:1037]: I meant:

* FullGlobalizationData.cs
* FullGlobalizationData.Windows.cs
* FullGlobalizationData.Unix.cs

Note this is just an idea.... You can employ whatever naming you think fits the situation best.

File: src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c (hunk 6 above)
Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: talked offline with @jkoritzinsky and he said the following:
```
    If the parameter is a string, you can add [MarshalAs(MarshalType.LPUTF8Str)] on the parameter to marshal it as a UTF-8 string, which a char* can represent
```

Comment (jkoritzinsky) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: To answer the other question in this thread, MarshalAs takes precedence over DllImport.

Comment (eerhardt) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: > LPUTF8Str

Reading the ICU docs, I _think_ `region` is an ANSI string.

Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: All region names have characters in ANSI. if the caller pass non-ANSI that will make it as if passing wrong region name anyway. The API will just return the default name at that time. The behavior should still be correct.

Comment (eerhardt) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: That reminds me.... maybe we need some validation for the `region` parameter?

Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: The ICU API does that for us. why we need manually doing it?

Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: @jkoritzinsky I assume you meant `UnmanagedType` instead of `MarshalType` when you replied me.

Comment (jkoritzinsky) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: Yes that is correct.

Comment (eerhardt) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c:31]: > I can add negative test too there.

Sounds good. The concern is that we are taking any UTF-16 string and converting it ourselves (either our code as you currently have, or making the Marshaller do it for us). We need to ensure our API acts appropriately when someone passes in invalid region codes here.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs (hunk 8 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs]: I have moved the code to its own file. 

TimeZoneInfo.FullGlobalizationData.cs is compiled for all platforms but the browser.
TimeZoneInfo.FullGlobalizationData.Unix.cs is compiled for Unix platforms but the browser.
TimeZoneInfo.MinimalGlobalizationData.cs is compiled for all the browser only.

When code reviewing this, `git` of course get confused. basically, I renamed the original TimeZoneInfo.FullGlobalizationData.cs to TimeZoneInfo.FullGlobalizationData.Unix.cs without any change. And now TimeZoneInfo.FullGlobalizationData.cs just have only the new code I added.

Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs]: @eerhardt thanks for all the feedback. it is helpful. Please let me know if you have any more comments.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs [hunk 9]
```diff
@@ -950,14 +962,111 @@ public bool HasSameRules(TimeZoneInfo other)
                 adjustmentRules = (AdjustmentRule[])adjustmentRules.Clone();
             }
 
+            bool hasIanaId = TimeZoneInfo.TryConvertIanaIdToWindowsId(id, out string _);
```
[the remark this answers is not in the document]
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs]: That is a good idea. I have done that.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs [hunk 10]
```diff
@@ -950,14 +962,111 @@ public bool HasSameRules(TimeZoneInfo other)
...
+                hasIanaId);
+        }
+
+        /// <summary>
+        /// Tries to convert IANA time zone Id to Windows Id.
+        /// </summary>
+        /// <param name="ianaId">The IANA time zone Id.</param>
+        /// <param name="windowsId">String object hold the Windows Id which resulted from the IANA Id conversion.</param>
+        /// <returns>True if the Id conversion succeed, false otherwise .</returns>
+        public static unsafe bool TryConvertIanaIdToWindowsId(string ianaId, out string? windowsId)
```
[the remark this answers is not in the document]
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs]: done that.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs (hunk 3 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs]: done that.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs (hunk 4 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs]: done that.

File: src/libraries/System.Runtime/ref/System.Runtime.cs (hunk 5 above)
Comment (tarekgh) [reply src/libraries/System.Runtime/ref/System.Runtime.cs]: I have fixed that.

File: src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c (hunk 6 above)
Comment (tarekgh) [reply src/libraries/Native/Unix/System.Globalization.Native/pal_timeZoneInfo.c]: I have done that. We have used LPStr instead of UTF8 anyway. The other reason is code gen couldn't accept UTF8.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs (hunk 7 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs]: This is done

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs (hunk 8 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.cs]: This is done now.

File: src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs [hunk 11]
```diff
@@ -2638,6 +2638,65 @@ public static void UsingAlternativeTimeZoneIdsTest(string windowsId, string iana
...
+        [InlineData("Central Europe Standard Time", "Europe/Budapest", "\uFFFFNotValidRegion")]
+        [InlineData("Central Europe Standard Time", "Europe/Prague", "CZ")]
+        [InlineData("Central Europe Standard Time", "Europe/Ljubljana", "SI")]
+        [InlineData("Central Europe Standard Time", "Europe/Bratislava", "SK")]
+        [InlineData("Central Europe Standard Time", "Europe/Tirane", "AL")]
+        [InlineData("Central Europe Standard Time", "Europe/Podgorica", "ME")]
+        [InlineData("Central Europe Standard Time", "Europe/Belgrade", "RS")]
+        public static void IdsConversionsWithRegionTest(string windowsId, string ianaId, string region)
+        {
+            Assert.True(TimeZoneInfo.TryConvertWindowsIdToIanaId(windowsId, region, out string ianaConvertedId));
```
Comment (eerhardt) [inline src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:2696]: Were you going to add some "invalid" region tests? Just to make sure the API behaves correctly when unicode characters are passed into this string.

**Review by eerhardt — APPROVED** [review]
:shipit:

File: src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs (hunk 11 above)
Comment (tarekgh) [reply src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:2696]: Yes, I already did.

```
[InlineData("Pacific Standard Time", "America/Los_Angeles", "\u0600NotValidRegion")]
[InlineData("Central Europe Standard Time", "Europe/Budapest", "\uFFFFNotValidRegion")]
```

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs [hunk 12]
```diff
@@ -7,260 +7,75 @@ namespace System
...
-
-        // Helper function to get the full display name for the UTC static time zone instance
-        private static string GetUtcFullDisplayName(string timeZoneId, string standardDisplayName)
-        {
-            return $"(UTC) {standardDisplayName}";
-        }
-
-        // Helper function that retrieves various forms of time zone display names from ICU
-        private static unsafe void GetDisplayName(string timeZoneId, Interop.Globalization.TimeZoneDisplayNameType nameType, string uiCulture, ref string? displayName)
+        private static unsafe bool TryConvertIanaIdToWindowsId(string ianaId, bool allocate, out string? windowsId)
```
Comment (safern) [inline src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs:10]: Doesn't matter much because it is private but it helps with data flow analysis for nullability in code that calls this, you could use NotNullWhen(true).

**Review by safern — APPROVED** [review]
LGTM

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs [hunk 13]
```diff
@@ -7,260 +7,75 @@ namespace System
...
-            }
-
-            // Prefer location names in some special cases.
-            if (StringArrayContains(timeZoneId, s_ZonesThatUseLocationName, StringComparison.OrdinalIgnoreCase))
-            {
-                displayName = $"{baseOffsetText} {genericLocationName}";
-                return;
+                // ICU uses some characters as a separator and trim the id at that character.
+                // while we should fail if the Id contained one of these characters.
+                if (c == '\\' || c == '\n' || c == '\r')
```
Comment (safern) [inline src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs:61]: I see this for validation of the chars duplicated can we make it a helper Private method with aggressive inlining or would that cause extra allocations?

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs (hunk 12 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs:10]: It can be null even when we return true here. Therefore I annotated the public API and not this one.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs (hunk 13 above)
Comment (tarekgh) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs:61]: it is not worth it. we can factor that if we need to add more.

File: src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs (hunk 12 above)
Comment (safern) [reply src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs:10]: A, ok I missed that.

**Comment by iSazonov** [comment]
Oops! ^-) Already merged.
