### PR TITLE
Fixing COM Aggregation and XAML reference tracking on .NET AOT

### LINKED ISSUE #85137: NativeAOT ComWrappers: support IReferenceTrackerHost
Currently NativeAOT's ComWrapper managed object wrapper supports being created with the [`CreateComInterfaceFlags.TrackerSupport`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.createcominterfaceflags) flag. This causes the wrapper to implement [`IReferenceTrackerTarget`](https://learn.microsoft.com/windows/win32/api/windows.ui.xaml.hosting.referencetracker/nn-windows-ui-xaml-hosting-referencetracker-ireferencetrackertarget).

What is missing is an implementation of [`IReferenceTrackerHost`](https://learn.microsoft.com/windows/win32/api/windows.ui.xaml.hosting.referencetracker/nn-windows-ui-xaml-hosting-referencetracker-ireferencetrackerhost). Supporting `IReferenceTrackerHost` would enable tighter integreation between the .NET garbage collector and the unmanaged runtime. When implementing this, inspiration can be taken from [CoreCLR's implementation](https://github.com/dotnet/runtime/blob/main/src/coreclr/interop/trackerobjectmanager.cpp).

This tracking issue captures some of the conversation from #85087

### LINKED ISSUE #89713: System.NotImplementedException in ComWrappers.TryGetOrCreateObjectForComInstanceInternal on NativeAOT
### Description

I get `System.NotImplementedException` in `ComWrappers.TryGetOrCreateObjectForComInstanceInternal` when [COM Aggregation](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.createobjectflags) is used when using [ComWrappers.GetOrRegisterObjectForComInstance](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comwrappers.GetOrRegisterObjectForComInstance) like in case of WinRT class inheriting. 

### Reproduction Steps

1. Clone https://github.com/ahmed605/NativeAOTComWrappersAggregationRepro
2. Open a VS Developer Command Prompt
3. `cd` to `NativeAOTComWrappersAggregationRepro`
4. Publish with NativeAOT:
```bash
msbuild NativeAOTComWrappersAggregationRepro.csproj -t:restore,publish /p:Configuration=Release /p:Platform=x64 /p:RuntimeIdentifier=win-x64 /p:TargetFramework=net8.0-windows10.0.22000.0
```
5. Run the published .exe
6. Attach a debugger
7. Press any key to continue execution

### Expected behavior

The app prints "Hello!" to the console.

### Actual behavior

Crash with `System.NotImplementedException` in `ComWrappers.TryGetOrCreateObjectForComInstanceInternal`

image

And this is printed into the console:
```
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal(IntPtr, IntPtr, CreateObjectFlags, Object, Object&) + 0x554
   at System.Runtime.InteropServices.ComWrappers.GetOrRegisterObjectForComInstance(IntPtr, CreateObjectFlags, Object, IntPtr) + 0x30
   at WinRT.ComWrappersHelper.Init(Boolean, Object, IntPtr, IntPtr, IObjectReference&) + 0x151
   at TestComponent.Class..ctor() + 0x72
   at NativeAOTComWrappersAggregationRepro.Program.Main(String[] args) + 0x29
   at NativeAOTComWrappersAggregationRepro!<BaseAddress>+0x2735c4
```

Stacktrace:
```
NativeAOTComWrappersAggregationRepro.exe!S_P_CoreLib_System_Runtime_InteropServices_ComWrappers__TryGetOrCreateObjectForComInstanceInternal() Line 726
NativeAOTComWrappersAggregationRepro.exe!S_P_CoreLib_System_Runtime_InteropServices_ComWrappers__GetOrRegisterObjectForComInstance_0() Line 648
NativeAOTComWrappersAggregationRepro.exe!WinRT_Runtime_WinRT_ComWrappersHelper__Init()
NativeAOTComWrappersAggregationRepro.exe!TestComponent_Projection_TestComponent_Class___ctor() Line 108
NativeAOTComWrappersAggregationRepro.exe!NativeAOTComWrappersAggregationRepro_NativeAOTComWrappersAggregationRepro_Program__Main() Line 15
NativeAOTComWrappersAggregationRepro.exe!NativeAOTComWrappersAggregationRepro__Module___StartupCodeMain()
NativeAOTComWrappersAggregationRepro.exe!wmain(int argc, wchar_t * * argv) Line 218
[Inline Frame] NativeAOTComWrappersAggregationRepro.exe!invoke_main() Line 90
NativeAOTComWrappersAggregationRepro.exe!__scrt_common_main_seh() Line 288
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

.NET 8.0.100 Preview 6 SDK

### Other information

_No response_

### PR DESCRIPTION
**Pull request by manodasanW**
There were blocks put in place in AOT for COM aggregation and XAML reference tracking wasn't implemented.  This PR adds support for both of them by porting the CoreCLR native code that existed to C# for AOT support.  With these changes, the ComWrappers API tests and weak reference tests all pass.

Fixes #89713
Fixes #85137

### CODE REVIEW

File: src/libraries/Common/src/Interop/Windows/Ole32/Interop.CoGetContextToken.cs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+        internal static unsafe int CoGetContextToken(out IntPtr token)
+        {
+            fixed (IntPtr* pToken = &token)
+            {
+                return CoGetContextToken(pToken);
+            }
+        }
+
+        [LibraryImport(Libraries.Ole32)]
+        internal static unsafe partial int CoGetContextToken(IntPtr* pToken);
```
Comment (jkoritzinsky) [inline src/libraries/Common/src/Interop/Windows/Ole32/Interop.CoGetContextToken.cs:20]: This is the same as having manually written the wrapper, so just use LibraryImport directly.

```suggestion
        [LibraryImport(Libraries.Ole32)]
        internal static unsafe partial int CoGetContextToken(out IntPtr pToken);
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 2]
```diff
@@ -471,15 +480,76 @@ public ManagedObjectWrapperReleaser(ManagedObjectWrapper* wrapper)
...
+            private IntPtr _trackerObject;
+            private readonly bool _releaseTrackerObject;
+            private int _trackerObjectDisconnected;
+
+            internal readonly IntPtr _contextToken;
 
-            public NativeObjectWrapper(IntPtr externalComObject, ComWrappers comWrappers, object comProxy)
+            public IntPtr TrackerObject => (_trackerObject == IntPtr.Zero || _trackerObjectDisconnected == 1) ? IntPtr.Zero : _trackerObject;
+
+            public NativeObjectWrapper(IntPtr externalComObject, IntPtr inner, ComWrappers comWrappers, object comProxy, CreateObjectFlags flags)
```
Comment (jkoritzinsky) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:499]: Would it be interesting to split the aggregation and tracker runtime support into separate subclasses of `NativeObjectWrapper` or introduce a base class/interface?

It might help make the code cleaner/easier to understand, especially since we have the `CreateObjectFlags` data present at the time we create this wrapper.

This work can also wait until after merging.

**Review by jkoritzinsky — COMMENTED** [review]
LGTM, but I'll defer to @AaronRobinsonMSFT for final sign-off.

File: src/libraries/Common/src/Interop/Windows/Ole32/Interop.CoGetContextToken.cs (hunk 1 above)
Comment (jkotas) [inline src/libraries/Common/src/Interop/Windows/Ole32/Interop.CoGetContextToken.cs:20]:
```suggestion
        [LibraryImport(Libraries.Ole32)]
        internal static unsafe partial int CoGetContextToken(out IntPtr pToken);
```
Why not leave it to the source generator to generate the marshalling code for you?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 3]
```diff
@@ -471,15 +480,76 @@ public ManagedObjectWrapperReleaser(ManagedObjectWrapper* wrapper)
...
             private ComWrappers _comWrappers;
             internal GCHandle _proxyHandle;
+            internal GCHandle _proxyHandleTrackingResurrection;
+            internal GCHandle _nativeObjectWrapperWeakHandle;
+
+            private readonly bool _aggregatedManagedObjectWrapper;
+            internal readonly bool _fromTrackerRuntime;
+            private IntPtr _trackerObject;
+            private readonly bool _releaseTrackerObject;
+            private int _trackerObjectDisconnected;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:493]:
```suggestion
            private int _trackerObjectDisconnected; // Atomic boolean, so using int.
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 4]
```diff
@@ -471,15 +480,76 @@ public ManagedObjectWrapperReleaser(ManagedObjectWrapper* wrapper)
...
                 _externalComObject = externalComObject;
+                _inner = inner;
                 _comWrappers = comWrappers;
-                Marshal.AddRef(externalComObject);
                 _proxyHandle = GCHandle.Alloc(comProxy, GCHandleType.Weak);
+
+                // We have a separate handle tracking resurrection as we want to make sure
+                // we clean up the NativeObjectWrapper only after the RCW has been finalized
+                // due to it can access the native object in the finalizer. At the same time,
+                // we want other callers which are using _proxyHandle such as the rcw cache to
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:509]:
```suggestion
                // we want other callers which are using _proxyHandle such as the RCW cache to
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 5]
```diff
@@ -471,15 +480,76 @@ public ManagedObjectWrapperReleaser(ManagedObjectWrapper* wrapper)
...
+                // see the object as not alive once it is eligible for finalization.
+                _proxyHandleTrackingResurrection = GCHandle.Alloc(comProxy, GCHandleType.WeakTrackResurrection);
+
+                _nativeObjectWrapperWeakHandle = GCHandle.Alloc(this, GCHandleType.Weak);
+
+                if (flags.HasFlag(CreateObjectFlags.TrackerObject))
+                {
+                    if (Marshal.QueryInterface(externalComObject, in IID_IReferenceTracker, out IntPtr trackerObject) == 0 &&
+                        trackerObject != IntPtr.Zero)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:518]:
```suggestion
                        trackerObject != IntPtr.Zero)
```

I would remove this. If the QI returns `S_OK` and `null`, I want this to fail hard.

Comment (AaronRobinsonMSFT) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:518]: Feel free to assert, but this is breaking a well established contract and is simply unnecessary overhead.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 6]
```diff
@@ -952,7 +1125,89 @@ internal static object ComObjectForInterface(IntPtr externalComObject)
...
+                    if (nativeObjectWrapper != null &&
+                        nativeObjectWrapper.TrackerObject != IntPtr.Zero)
+                    {
+                        FindReferenceTargetsCallback.s_currentRootObjectHandle = nativeObjectWrapper._proxyHandle;
+                        IReferenceTracker.FindTrackerTargets(nativeObjectWrapper.TrackerObject, TrackerObjectManager.s_findReferencesTargetCallback);
+                        FindReferenceTargetsCallback.s_currentRootObjectHandle = default;
+                    }
+                }
+            }
+            catch (Exception)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:1187]:
```suggestion
            catch
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 7]
```diff
@@ -0,0 +1,543 @@
...
+            vftbl[2] = (IntPtr)(delegate* unmanaged<IntPtr, uint>)&ComWrappers.Untracked_Release;
+            vftbl[3] = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, int>)&IFindReferenceTargetsCallback_FoundTrackerTarget;
+            return (IntPtr)vftbl;
+        }
+
+        internal static unsafe IntPtr CreateFindReferenceTargetsCallback()
+        {
+            IntPtr wrapperMem = (IntPtr)NativeMemory.Alloc(2 * (nuint)sizeof(IntPtr));
+            *(IntPtr*)(wrapperMem) = CreateDefaultIFindReferenceTargetsCallbackVftbl();
+            *(IntPtr*)(wrapperMem + sizeof(IntPtr)) = wrapperMem;
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:394]:
```suggestion
```
This looks unused. Is it actually needed for anything?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 8]
```diff
@@ -0,0 +1,543 @@
...
+        internal static GCHandle s_currentRootObjectHandle;
+
+        [UnmanagedCallersOnly]
+        private static unsafe int IFindReferenceTargetsCallback_QueryInterface(IntPtr pThis, Guid* guid, IntPtr* ppObject)
+        {
+            if (pThis == IntPtr.Zero)
+            {
+                return HResults.E_POINTER;
+            }
+
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:351]:
```suggestion
```
this pointer is assumed to be non-null in COM calls. These null checks for this pointer are superfluous.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 9]
```diff
@@ -0,0 +1,543 @@
...
+        }
+
+    }
+
+    // Wrapper for IReferenceTrackerManager
+    internal static unsafe class IReferenceTrackerManager
+    {
+        public static void ReferenceTrackingStarted(IntPtr pThis)
+        {
+            Marshal.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, int>**)pThis)[3](pThis));
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:280]: `StdCall` is in some places, but not in others. Delete it from everywhere since it is the default?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 10]
```diff
@@ -0,0 +1,543 @@
...
+
+    internal static class TrackerObjectManager
+    {
+        internal static readonly IntPtr s_findReferencesTargetCallback = FindReferenceTargetsCallback.CreateFindReferenceTargetsCallback();
+
+        internal static volatile IntPtr s_TrackerManager;
+        internal static volatile bool s_HasTrackingStarted;
+        internal static volatile bool s_IsGlobalPeggingOn = true;
+
+        internal static DependentHandleList s_ReferenceCache;
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:116]:
```suggestion
        internal static volatile IntPtr s_trackerManager;
        internal static volatile bool s_hasTrackingStarted;
        internal static volatile bool s_isGlobalPeggingOn = true;

        internal static DependentHandleList s_referenceCache;
```
Nit: Repo coding conventions

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 11]
```diff
@@ -0,0 +1,543 @@
...
+
+        // Begin the reference tracking process for external objects.
+        public static void BeginReferenceTracking()
+        {
+            if (!ShouldWalkExternalObjects())
+            {
+                return;
+            }
+
+            Debug.Assert(s_HasTrackingStarted == false);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:188]:
```suggestion
            Debug.Assert(!s_HasTrackingStarted);
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 12]
```diff
@@ -0,0 +1,543 @@
...
+                EndReferenceTracking();
+            }
+        }
+
+        [UnmanagedCallersOnly]
+        private static void GCAfterMarkPhase(int condemnedGeneration)
+        {
+            DetachNonPromotedObjects();
+        }
+
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:272]:
```suggestion
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 13]
```diff
@@ -0,0 +1,543 @@
...
+        {
+            if (pThis == IntPtr.Zero)
+            {
+                return HResults.E_POINTER;
+            }
+
+            if (*guid == IID_IFindReferenceTargetsCallback || *guid == IID_IUnknown)
+            {
+                *ppObject = pThis;
+                return 0;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:355]:
```suggestion
                return HResults.S_OK;
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 14]
```diff
@@ -0,0 +1,543 @@
...
+            return true;
+        }
+
+        public bool Reset()
+        {
+            // Allocation for the first time
+            if (_pHandles == null)
+            {
+                _capacity = DefaultCapacity;
+                _pHandles = (IntPtr*)Interop.Ucrtbase.calloc((nuint)_capacity, (nuint)sizeof(IntPtr));
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:461]: `calloc` sets the memory to zero. Do you really need the memory zero-initialized here?

Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:461]: Yes we do, the logic as ported checks if there was a previously allocated dependency handle at the slot by checking if it is not default / zero and if so overrides the target and dependent for it rather than allocating a new one.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 15]
```diff
@@ -0,0 +1,543 @@
...
+            vftbl[3] = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, int>)&IFindReferenceTargetsCallback_FoundTrackerTarget;
+            return (IntPtr)vftbl;
+        }
+
+        internal static unsafe IntPtr CreateFindReferenceTargetsCallback()
+        {
+            IntPtr wrapperMem = (IntPtr)NativeMemory.Alloc(2 * (nuint)sizeof(IntPtr));
+            *(IntPtr*)(wrapperMem) = CreateDefaultIFindReferenceTargetsCallbackVftbl();
+            *(IntPtr*)(wrapperMem + sizeof(IntPtr)) = wrapperMem;
+            return wrapperMem;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:395]:
```suggestion
            IntPtr* wrapperMem = (IntPtr*)NativeMemory.Alloc(2 * (nuint)sizeof(IntPtr));
            wrapperMem[0] = CreateDefaultIFindReferenceTargetsCallbackVftbl();
            wrapperMem[1] = (IntPtr)wrapperMem;
            return (IntPtr)wrapperMem;
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 16]
```diff
@@ -0,0 +1,543 @@
...
+            *(IntPtr*)(wrapperMem) = DefaultIReferenceTrackerHostVftblPtr;
+            *(IntPtr*)(wrapperMem + sizeof(IntPtr)) = wrapperMem;
+            return wrapperMem;
+        }
+
+        public static void DisconnectUnusedReferenceSources(uint flags)
+        {
+            if ((((XAML_REFERENCETRACKER_DISCONNECT)flags) & XAML_REFERENCETRACKER_DISCONNECT.XAML_REFERENCETRACKER_DISCONNECT_SUSPEND) != 0)
+            {
+                // In CoreCLR, low_memory_p is also set to true which it isn't here in AOT currently via this code path.
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:35]: It would be fine to add a new argument to the existing RhCollect export so that the flag can be passed in.

**Comment by AaronRobinsonMSFT** [comment]
Thanks @manodasanW. So far so good. 

/cc @AustinWise

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 17]
```diff
@@ -0,0 +1,543 @@
...
+
+            IntPtr handle = _pHandles[_freeIndex];
+            if (handle != default)
+            {
+                RuntimeImports.RhHandleSet(handle, target);
+                RuntimeImports.RhHandleSetDependentSecondary(handle, dependent);
+            }
+            else
+            {
+                _pHandles[_freeIndex] = RuntimeImports.RhHandleAllocDependent(target, dependent);
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:448]: Do we need to check that this succeded?

Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:442]: It looks like it will throw if it fails.  I think for an out of memory allocating a handle that might be fine to leave as is and break there instead of catching or adding another import that doesn't throw.  Let me know if there are other concerns here where we should indeed catch the exception.

Comment (jkotas) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:442]: > It looks like it will throw if it fails

It is not going to run that far. This code runs during GC where allocations are disallowed. It will lead to some very bad crash.

This should call the lower-level non-throwing method.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs (hunk 5 above)
Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs]: Removed check.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs (hunk 17 above)
Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs]: Addressed this and a couple other exceptions on other call paths from GC callbacks.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 18]
```diff
@@ -471,15 +480,72 @@ public ManagedObjectWrapperReleaser(ManagedObjectWrapper* wrapper)
...
+                // due to it can access the native object in the finalizer. At the same time,
+                // we want other callers which are using _proxyHandle such as the RCW cache to
+                // see the object as not alive once it is eligible for finalization.
+                _proxyHandleTrackingResurrection = GCHandle.Alloc(comProxy, GCHandleType.WeakTrackResurrection);
+
+                _nativeObjectWrapperWeakHandle = GCHandle.Alloc(this, GCHandleType.Weak);
+
+                if (flags.HasFlag(CreateObjectFlags.TrackerObject))
+                {
+                    if (Marshal.QueryInterface(externalComObject, in IID_IReferenceTracker, out IntPtr trackerObject) == 0)
```
Comment (Sergio0694) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:517]: Should these `0`-s for QI calls use `HResults.S_OK` for readability?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 19]
```diff
@@ -952,7 +1121,91 @@ internal static object ComObjectForInterface(IntPtr externalComObject)
...
-            return s_globalInstanceForMarshalling.GetOrCreateObjectForComInstance(externalComObject, CreateObjectFlags.Unwrap);
+            // TrackerObject support and unwrapping matches the built-in semantics that the global marshalling scenario mimics.
+            return s_globalInstanceForMarshalling.GetOrCreateObjectForComInstance(externalComObject, CreateObjectFlags.TrackerObject | CreateObjectFlags.Unwrap);
+        }
+
+        internal static IntPtr GetOrCreateTrackerTarget(IntPtr externalComObject)
+        {
+            if (s_globalInstanceForTrackerSupport == null)
+            {
+                throw new NotSupportedException(SR.InvalidOperation_ComInteropRequireComWrapperInstance);
```
Comment (Sergio0694) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:1132]: Should all these be `ThrowHelper.ThrowNotSupportedException`? There's already an overload taking a resource.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 20]
```diff
@@ -952,7 +1121,91 @@ internal static object ComObjectForInterface(IntPtr externalComObject)
...
+            if (walkFailed)
+            {
+                TrackerObjectManager.s_isGlobalPeggingOn = true;
+            }
+            IReferenceTrackerManager.FindTrackerTargetsCompleted(TrackerObjectManager.s_trackerManager, walkFailed);
+        }
+
+        internal static void DetachNonPromotedObjects()
+        {
+            for (int idx = 0; idx < s_nativeObjectWrapperCache.Count; idx++)
```
Comment (Sergio0694) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:1198]: How come this isn't also just using a `foreach` loop like in `WalkExternalTrackerObjects`? Just trying to understand this better — does this method expect that the wrapper cache list will be mutated across iterations?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 21]
```diff
@@ -0,0 +1,549 @@
...
+    // Defined in windows.ui.xaml.hosting.referencetracker.h.
+    internal enum XAML_REFERENCETRACKER_DISCONNECT
+    {
+        // Indicates the disconnect is during a suspend and a GC can be trigger.
+        XAML_REFERENCETRACKER_DISCONNECT_SUSPEND = 0x00000001
+    };
+
+    internal struct HostServices
+    {
+        internal static IntPtr s_globalHostServices = CreateHostServices();
```
Comment (Sergio0694) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:21]: Just double checking: is this intentionally not readonly? Not seeing it being reassigned anywhere 🤔

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 22]
```diff
@@ -0,0 +1,549 @@
...
+
+        // Creates a proxy object (managed object wrapper) that points to the given IUnknown.
+        // The proxy represents the following:
+        //   1. Has a managed reference pointing to the external object
+        //      and therefore forms a cycle that can be resolved by GC.
+        //   2. Forwards data binding requests.
+        //
+        // For example:
+        //
+        // Grid <---- NoCW             Grid <-------- NoCW
```
Comment (Sergio0694) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:60]: What's "NoCW" in this context? Not sure I've seen this acronym before 😅
Maybe clarify what that means in the comment to make this easier to understand?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 23]
```diff
@@ -0,0 +1,549 @@
...
+        //                    1. We can either create a new NoCW or get back an old one from the cache.
+        //                    2. This obj could be a regular tracker runtime object for data binding.
+        //  ppNewReference  - The IReferenceTrackerTarget* for the proxy created
+        //                    The tracker runtime will call IReferenceTrackerTarget to establish a reference.
+        //
+        public static void GetTrackerTarget(IntPtr punk, out IntPtr ppNewReference)
+        {
+            if (punk == IntPtr.Zero)
+            {
+                throw new ArgumentException();
```
Comment (Sergio0694) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:78]: Is it not worth it to use `ThrowHelper`-s in this method rather than having all these inline exceptions?

**Review by Sergio0694 — COMMENTED** [review]
Just leaving a few thoughts here. This is all looking amazing!! 🎉

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs (hunk 2 above)
Comment (Sergio0694) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:499]: Just curious, would this also lead to some memory usage improvements for the non-aggregation/tracker scenario? Since it seems there's quite a few additional fields being needed for those, which also seem to be per-object? 🤔

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs (hunk 23 above)
Comment (jkotas) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:78]: Complicating the code with hand-rolled throw helpers makes sense only for small hot methods where it makes a perf difference. This does not look like one of those.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs (hunk 22 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:60]: "Native Object Com Wrapper", Basically a RCW in the parlance of the legacy system.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs (hunk 2 above)
Comment (jkotas) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:499]: I agree. If this is kept as-is, we should understand whether the perf regression for plain vanilla COM interop is acceptable before merging.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs (hunk 21 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:21]: This is for the lifetime of the process. I could be marked `readonly`.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 24]
```diff
@@ -0,0 +1,549 @@
...
+namespace System.Runtime.InteropServices
+{
+    // Defined in windows.ui.xaml.hosting.referencetracker.h.
+    internal enum XAML_REFERENCETRACKER_DISCONNECT
+    {
+        // Indicates the disconnect is during a suspend and a GC can be trigger.
+        XAML_REFERENCETRACKER_DISCONNECT_SUSPEND = 0x00000001
+    };
+
+    internal struct HostServices
```
Comment (AustinWise) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:19]:
```suggestion
    internal static class HostServices
```

I don't see this struct instantiated anywhere.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs (hunk 2 above)
Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:532]: Addressed by creating a new subclass for the tracker scenarios.  Left the aggregation scenario as there is only one bool it uses.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs (hunk 18 above)
Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs]: Addressed.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs (hunk 19 above)
Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs]: It looks like it needs an ExceptionResource rather than a string and from looking at the ones there it seems to be a limited set.  So leaving this alone for now based on the feedback in the other comment about it being meant for methods which are small hot methods.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs (hunk 20 above)
Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs]: I was using a different collection before and that was doing an allocation when using the enumerator which causes issues for GC callbacks such as this.  So I had addressed it by doing that, but it seems to no longer be the issue with the current collection I am using.  Updated to use foreach again.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs [hunk 25]
```diff
@@ -2,32 +2,94 @@
...
+            // new RCW for it.
+            if (IWeakReference.Resolve(pComWeakRef, IID_IInspectable, out IntPtr targetPtr) == HResults.S_OK &&
+                targetPtr != IntPtr.Zero)
+            {
+                using ComHolder target = new ComHolder(targetPtr);
+                if (Marshal.QueryInterface(target.Ptr, in ComWrappers.IID_IUnknown, out IntPtr targetIdentityPtr) == HResults.S_OK)
+                {
+                    using ComHolder targetIdentity = new ComHolder(targetIdentityPtr);
+                    return ComWrappers.GetOrCreateObjectFromWrapper(wrapperId, targetIdentity.Ptr);
+                }
```
[the remark this answers is not in the document]
Comment (Sergio0694) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs:40]: Yup absolutely, just figured I'd mention this while I was at it 😄

**Comment by manodasanW** [comment]
@jkotas it looks like the build is failing on osx-x64 Release NativeAOT due to the binary size increased.  What options do we have here?

      ****************************************************
      * Size test                                        *
      * Size of the executable is   1,780 kB             *
      ****************************************************
      BUG: File size is not in the expected range (1331200 to 1792000 bytes). Did a libraries change regress size of Hello World?

**Comment by jkotas** [comment]
It means that a lot of the ComWrappers code ends up in the final binary even when none of it is actually used.

The problem is most likely caused by the calls from WeakReference/ComAwareWeakReference. We either need to make all these calls from WeakReference to go through indirections that are initialized only after the Com wrappers tracking is initialized (ie replace the `bool` that you have added with a bunch of delegates or function pointers, and make sure to do all calls from WeakReference/ComAwareWeakReference via these).

If that does not work for some reason, we may need end up introducing a feature switch to enable this feature in WinUI apps only. https://learn.microsoft.com/en-us/dotnet/core/runtime-config/threading#autoreleasepool-for-managed-threads is a good example of prior art.

**Comment by Sergio0694** [comment]
> "If that does not work for some reason, we may need end up introducing a feature switch to enable this feature in WinUI apps only"

Pretty sure that's what you meant, but just to double check: did you just use WinUI as a reference here but the feature switch would just be a general-purpose feature switch like others in .NET, that anyone could use? Because WinUI 3 apps are not the only applications that would use the new stuff added in this PR. For instance, COM aggregation can be needed by any WASDK app (without WinUI 3) that also happens to have some types deriving from WinRT projection types.

**Comment by jkotas** [comment]
> the feature switch would just be a general-purpose feature switch like others in .NET, that anyone could use?

Correct.

We should investigate whether this feature switch is actually needed.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs [hunk 26]
```diff
@@ -2,32 +2,55 @@
...
+
+        internal static unsafe object? ComWeakRefToObject(IntPtr pComWeakRef, long wrapperId)
         {
-            // NativeAOT support for COM WeakReference is NYI
-            throw new NotImplementedException();
+            return ComWeakRefToObjectCallback != null ? ComWeakRefToObjectCallback(pComWeakRef, wrapperId) : null;
         }
 
-        internal static bool PossiblyComObject(object target)
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
```
Comment (Sergio0694) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs:38]: Nit: is this still needed and/or doing anything now that the method is only ever called via fnptr?

Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs:38]: Well this is the one calling the function pointer, so it can still be useful I think.  Let me know if otherwise.  But it probably isn't useful in the actual function in the other file.

Comment (Sergio0694) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs:38]: Oops sorry, added a comment on the wrong line, I meant to add this one to this method:

https://github.com/dotnet/runtime/blob/032b7d35e3a6221b7fc9cc9d1f5cfba2baad0d55/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs#L1566-L1570

**Comment by manodasanW** [comment]
> It means that a lot of the ComWrappers code ends up in the final binary even when none of it is actually used.
> 
> The problem is most likely caused by the calls from WeakReference/ComAwareWeakReference. We either need to make all these calls from WeakReference to go through indirections that are initialized only after the Com wrappers tracking is initialized (ie replace the `bool` that you have added with a bunch of delegates or function pointers, and make sure to do all calls from WeakReference/ComAwareWeakReference via these).
> 
> If that does not work for some reason, we may need end up introducing a feature switch to enable this feature in WinUI apps only. https://learn.microsoft.com/en-us/dotnet/core/runtime-config/threading#autoreleasepool-for-managed-threads is a good example of prior art.

Looks like all the tests passed after the callback change.  Thanks.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs (hunk 26 above)
Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs:38]: Addressed.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs [hunk 27]
```diff
@@ -2,32 +2,55 @@
...
+        private static unsafe delegate*<object, bool> PossiblyComObjectCallback;
+        private static unsafe delegate*<object, long*, IntPtr> ObjectToComWeakRefCallback;
+
+        internal static unsafe void InitializeCallbacks(
+            delegate*<IntPtr, long, object?> comWeakRefToObject,
+            delegate*<object, bool> possiblyComObject,
+            delegate*<object, long*, IntPtr> objectToComWeakRef)
+        {
+            // PossiblyComObjectCallback is initialized last to avoid any potential races
+            // where functions are being called while initialization is happening.
```
[the remark this answers is not in the document]
Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs]: Thanks for calling this out, made them volatile.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs [hunk 28]
```diff
@@ -2,32 +2,49 @@
...
+        private static unsafe volatile delegate*<object, bool> s_possiblyComObjectCallback;
+        private static unsafe volatile delegate*<object, out long, IntPtr> s_objectToComWeakRefCallback;
+
+        internal static unsafe void InitializeCallbacks(
+            delegate*<IntPtr, long, object?> comWeakRefToObject,
+            delegate*<object, bool> possiblyComObject,
+            delegate*<object, out long, IntPtr> objectToComWeakRef)
+        {
+            // PossiblyComObjectCallback is initialized last to avoid any potential race
+            // conditions where functions are being called while initialization is happening.
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs:27]: I am looking at this again - what is the exact race condition that you are worried about? I do not see it. Could you please elaborate?

Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/ComAwareWeakReference.NativeAot.cs:27]: The race condition I was concerned about is the callbacks being initialized while a weak reference was being allocated and _PossiblyComObjectCallback_ returning true when the other callbacks hadn't been set yet.  But thinking about it again, it shouldn't return true because due to where I initialize it, there won't be any RCWs yet.  So I will undo the volatile change and remove the comment.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 29]
```diff
@@ -0,0 +1,550 @@
...
+
+        internal readonly IntPtr Ptr => _ptr;
+
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        public ComHolder(IntPtr ptr)
+        {
+            _ptr = ptr;
+        }
+
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:402]:
```suggestion
        public ComHolder(IntPtr ptr)
        {
            _ptr = ptr;
        }

```
Unnecessary. The JIT is going inline these trivial methods without any help.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 30]
```diff
@@ -8,6 +8,7 @@
 using System.Runtime.CompilerServices;
 using System.Runtime.Versioning;
 using System.Threading;
+using static System.Runtime.InteropServices.ComWrappers;
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:11]:
```suggestion
```
Unnecessary

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 31]
```diff
@@ -0,0 +1,550 @@
...
+        private static unsafe IntPtr CreateHostServices()
+        {
+            IntPtr* wrapperMem = (IntPtr*)NativeMemory.Alloc((nuint)sizeof(IntPtr));
+            wrapperMem[0] = DefaultIReferenceTrackerHostVftblPtr;
+            return (IntPtr)wrapperMem;
+        }
+
+        public static void DisconnectUnusedReferenceSources(uint flags)
+        {
+            if ((((XAML_REFERENCETRACKER_DISCONNECT)flags) & XAML_REFERENCETRACKER_DISCONNECT.XAML_REFERENCETRACKER_DISCONNECT_SUSPEND) != 0)
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:32]:
```suggestion
            // Defined in windows.ui.xaml.hosting.referencetracker.h.
            const uint XAML_REFERENCETRACKER_DISCONNECT_SUSPEND = 0x00000001;

            if ((flags & XAML_REFERENCETRACKER_DISCONNECT_SUSPEND) != 0)
```
Less ceremony

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 32]
```diff
@@ -0,0 +1,550 @@
...
+
+namespace System.Runtime.InteropServices
+{
+    // Defined in windows.ui.xaml.hosting.referencetracker.h.
+    internal enum XAML_REFERENCETRACKER_DISCONNECT
+    {
+        // Indicates the disconnect is during a suspend and a GC can be trigger.
+        XAML_REFERENCETRACKER_DISCONNECT_SUSPEND = 0x00000001
+    };
+
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:18]:
```suggestion
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 33]
```diff
@@ -26,17 +27,43 @@ public abstract partial class ComWrappers
         internal static IntPtr DefaultIUnknownVftblPtr { get; } = CreateDefaultIUnknownVftbl();
         internal static IntPtr TaggedImplVftblPtr { get; } = CreateTaggedImplVftbl();
         internal static IntPtr DefaultIReferenceTrackerTargetVftblPtr { get; } = CreateDefaultIReferenceTrackerTargetVftbl();
+        internal static IntPtr DefaultIReferenceTrackerHostVftblPtr { get; } = CreateDefaultIReferenceTrackerHostVftbl();
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:30]:
```suggestion
```
This vtable is used to create singleton. It does not need to be cached.

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 34]
```diff
@@ -0,0 +1,550 @@
...
+    internal static class HostServices
+    {
+        internal static readonly IntPtr s_globalHostServices = CreateHostServices();
+
+        private static unsafe IntPtr CreateHostServices()
+        {
+            IntPtr* wrapperMem = (IntPtr*)NativeMemory.Alloc((nuint)sizeof(IntPtr));
+            wrapperMem[0] = DefaultIReferenceTrackerHostVftblPtr;
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:26]:
```suggestion
            wrapperMem[0] = CreateDefaultIReferenceTrackerHostVftbl();
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 35]
```diff
@@ -0,0 +1,550 @@
...
+namespace System.Runtime.InteropServices
+{
+    // Defined in windows.ui.xaml.hosting.referencetracker.h.
+    internal enum XAML_REFERENCETRACKER_DISCONNECT
+    {
+        // Indicates the disconnect is during a suspend and a GC can be trigger.
+        XAML_REFERENCETRACKER_DISCONNECT_SUSPEND = 0x00000001
+    };
+
+    internal static class HostServices
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:19]: `System.Runtime.InteropServices.HostServices` sounds like a very generic name - one cannot guess what it does from its name. Do we need this type? Would it make sense to just inline it into where it is used and TrackerObjectManager?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs [hunk 36]
```diff
@@ -1049,5 +1380,214 @@ private static unsafe IntPtr CreateDefaultIReferenceTrackerTargetVftbl()
...
+                return Marshal.GetHRForException(e);
+            }
+        }
+
+        [UnmanagedCallersOnly]
+        internal static unsafe int IReferenceTrackerHost_AddMemoryPressure(IntPtr pThis, long bytesAllocated)
+        {
+            try
+            {
+                HostServices.AddMemoryPressure(bytesAllocated);
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs:1447]: E.g. we can call `GC.AddMemoryPressure(bytesAllocated);` directly here. No need to go through "HostServices".

**Review by jkotas — COMMENTED** [review]
Some remaining nits

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs [hunk 37]
```diff
@@ -0,0 +1,550 @@
...
+        }
+
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        public readonly void Dispose()
+        {
+            Marshal.Release(_ptr);
+        }
+    }
+
+    // This is used during a GC callback so it needs to be free of any managed allocations.
```
Comment (jkotas) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs:409]: It would be useful to add "// Used during GC callback" or similar comment on all methods that can be called during GC callback so that it easier to tell which methods are under this restriction.

File: src/libraries/System.Private.CoreLib/src/Resources/Strings.resx [hunk 38]
```diff
@@ -4181,6 +4181,9 @@
   <data name="InvalidOperation_ComInteropRequireComWrapperInstance" xml:space="preserve">
     <value>COM Interop requires ComWrapper instance registered for marshalling.</value>
   </data>
+  <data name="InvalidOperation_ComInteropRequireComWrapperTrackerInstance" xml:space="preserve">
+    <value>COM Interop requires ComWrapper instance registered for reference tracker support.</value>
```
Comment (jkotas) [inline src/libraries/System.Private.CoreLib/src/Resources/Strings.resx:4185]: I do not see this message in CoreCLR anywhere. Is the CoreCLR error handling different? Do we want to make it the same?

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs (hunk 35 above)
Comment (manodasanW) [reply src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs]: Removed and inlined the various functions.

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/libraries/System.Private.CoreLib/src/Resources/Strings.resx (hunk 38 above)
Comment (manodasanW) [reply src/libraries/System.Private.CoreLib/src/Resources/Strings.resx:4185]: CoreCLR doesn't have a message, but following the code path, it does throw an ArgumentException in one case and in the other it seems it would hit a NullPointerException from a null access.  Given in CoreCLR they are mixing between C# and the C++ layer for where this logic is and the error happens in a more generic function like CallReleaseObjects, I guess they didn't have a specific error message there.  But here we are able to.

Comment (jkotas) [reply src/libraries/System.Private.CoreLib/src/Resources/Strings.resx:4185]: @AaronRobinsonMSFT Should we have a test for these paths?

Comment (AaronRobinsonMSFT) [reply src/libraries/System.Private.CoreLib/src/Resources/Strings.resx:4185]: Sure. This code path in CoreCLR is a bit more contrived given the set up, but we can construct a test. Due to how the system is built up it is going to be some effort though.
