### PR TITLE
Differentiate between IMPL_LIMITATION and NO_WAY

### LINKED ISSUE #43067: NO_WAY macro in JIT
The NO_WAY macro is used in the JIT primarily to represent issues in the JIT where either the JIT has failed due to invalid IL code provided to it, or when the JIT has some bug that places the JIT into an invalid state. Currently, the crossgen2 compiler is configured to fail to build if a NO_WAY is encountered unless the --resilient switch is passed to it. (The --resilient switch is passed to the compiler by default by the SDK for customer scenarios.)

However, there is at least one location where the JIT uses a NO_WAY to protect against code while valid, overflows some limit in the jit. See (https://github.com/dotnet/runtime/blob/6b84a7490365cc6918ac7f0f93fe71b3f2fe451c/src/coreclr/src/jit/lclvars.cpp#L404)

I'd like to add a new macro, ... call it NO_WAY_VALIDCODE which would cause the JIT to return an error code which is different from a normal NO_WAY so that crossgen2 can ignore that method and instead allow any failure to occur at runtime instead of at compile time.

I'm looking for some buyoff from the jit team before I do this.

### PR DESCRIPTION
**Pull request by davidwrighton**
Differentiate between `IMPL_LIMITATION` and `NO_WAY` in the JIT by making `IMPL_LIMITATION` return `CORJIT_IMPLLIMITATION` and handle that value such that crossgen2 behavior behaves better in the presence of an `IMPL_LIMITATION`.

Also, change a `NO_WAY` in the X86 JIT to `IMPL_LIMITATION` to better reflect the issue in code.

The effect of these changes is that a test which encounters an `IMPL_LIMITATION` while running crossgen2 in our test suite will not cause the test to fail, but instead will only cause it to fail if the limitation is also present at runtime. This addresses the last issue known to cause the Pri0 X86 Crossgen2 tests to fail.

Fixes issues #43067

### CODE REVIEW

**Comment by davidwrighton** [comment]
I'd like to get signoff from a crossgen engineer
@dotnet/crossgen-contrib 
And a jit engineer.
@dotnet/jit-contrib

File: src/coreclr/src/tools/Common/JitInterface/CorInfoImpl.cs [hunk 1]
```diff
@@ -198,6 +198,10 @@ private void CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, Method
             {
                 ThrowHelper.ThrowInvalidProgramException();
             }
+            if (result == CorJitResult.CORJIT_IMPLLIMITATION)
+            {
+                throw new RequiresRuntimeJitException("JIT implementation limitation");
```
Comment (MichalStrehovsky) [inline src/coreclr/src/tools/Common/JitInterface/CorInfoImpl.cs:203]: To avoid build break in runtimelab:

```suggestion
#if READYTORUN
                throw new RequiresRuntimeJitException("JIT implementation limitation");
#else
                ThrowHelper.ThrowInvalidProgramException();
#endif
```

**Review by BruceForstall — CHANGES_REQUESTED** [review]
Generally looks good.

However, I'm worried about this line:

https://github.com/dotnet/runtime/blob/1be890714a7dc5fb2de5da4ab72475e0f2d6a0e5/src/coreclr/src/jit/compiler.cpp#L6811

Since NO_WAY used to generate `CORJIT_INTERNALERROR`, I think now that you've split off `CORJIT_IMPLLIMITATION` you should add `CORJIT_IMPLLIMITATION` to this case. As you've pointed out, some of these are recoverable and some are not, and we don't distinguish them; we try again in all cases. We should keep doing so in the absence of deeper analysis of each one.

File: src/coreclr/src/jit/error.cpp [hunk 2]
```diff
@@ -65,6 +65,16 @@ void DECLSPEC_NORETURN noWay()
     fatal(CORJIT_INTERNALERROR);
 }
 
+/*****************************************************************************/
+void DECLSPEC_NORETURN implLimitation()
+{
+#if MEASURE_FATAL
+    fatal_noWay += 1;
```
Comment (BruceForstall) [inline src/coreclr/src/jit/error.cpp:72]: You should add a new `fatal_implLimitation` variable

File: src/coreclr/src/inc/corjit.h [hunk 3]
```diff
@@ -45,6 +45,7 @@ enum CorJitResult
     CORJIT_INTERNALERROR =     MAKE_HRESULT(SEVERITY_ERROR,FACILITY_NULL, 3),
     CORJIT_SKIPPED       =     MAKE_HRESULT(SEVERITY_ERROR,FACILITY_NULL, 4),
     CORJIT_RECOVERABLEERROR =  MAKE_HRESULT(SEVERITY_ERROR,FACILITY_NULL, 5),
+    CORJIT_IMPLLIMITATION=     MAKE_HRESULT(SEVERITY_ERROR,FACILITY_NULL, 6),
```
[the remark this answers is not in the document]
Comment (davidwrighton) [reply src/coreclr/src/inc/corjit.h:48]: Done. There is no real cost to updates, so I've done it.

File: src/coreclr/src/jit/error.cpp (hunk 2 above)
Comment (davidwrighton) [reply src/coreclr/src/jit/error.cpp]: done.

**Review by BruceForstall — APPROVED** [review]

**Review by trylek — APPROVED** [review]
Looks great to me, thanks David!
