### PR TITLE
JIT: Avoid incorrect TYP_UINT retyping for ToScalar

### LINKED ISSUE #71360: Test failure JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_r\\Vector128_r.cmd
Run: [runtime-coreclr outerloop 20220627.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1847764&view=ms.vss-test-web.build-test-results-tab&runId=48713400&paneView=debug&resultId=100173)

Failed test:
```

R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_r\\Vector128_r.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_ro\\Vector128_ro.cmd

R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_r\\Vector128_r.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_ro\\Vector128_ro.cmd

```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\ACDB0955\w\AB310971\uploads\Reports\JIT.HardwareIntrinsics\General\Vector128\Vector128_r\Vector128_r.output.txt
Raw output:
BEGIN EXECUTION
TestLibrary.dll
Vector128_r.dll
2 file(s) copied.
21:12:16.38
Response file: C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\TestLibrary.dll.rsp
C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\IL-CG2\TestLibrary.dll
-o:C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\TestLibrary.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\ACDB0955\p\System..dll
-r:C:\h\w\ACDB0955\p\Microsoft..dll
-r:C:\h\w\ACDB0955\p\mscorlib.dll
-r:C:\h\w\ACDB0955\p\netstandard.dll
-O
" "dotnet" "C:\h\w\ACDB0955\p\crossgen2\crossgen2.dll" @"C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\TestLibrary.dll.rsp"   -r:C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\TestLibrary.dll
21:12:18.76
21:12:18.76
Response file: C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\Vector128_r.dll.rsp
C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\IL-CG2\Vector128_r.dll
-o:C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\Vector128_r.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\ACDB0955\p\System..dll
-r:C:\h\w\ACDB0955\p\Microsoft..dll
-r:C:\h\w\ACDB0955\p\mscorlib.dll
-r:C:\h\w\ACDB0955\p\netstandard.dll
-O
" "dotnet" "C:\h\w\ACDB0955\p\crossgen2\crossgen2.dll" @"C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\Vector128_r.dll.rsp"   -r:C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\IL-CG2*.dll"
D:\a_work\1\s\src\coreclr\jit\lower.cpp:1198
Assertion failed 'genActualType(arg->TypeGet()) == type' in 'JIT.HardwareIntrinsics.General.VectorBinaryOpTest__DotUInt32:RunBasicScenario_UnsafeRead():this' during 'Lowering nodeinfo' (IL size 86; hash 0xf29d8d42; FullOpts)

21:12:39.98
Crossgen2 failed with exitcode - 1073741855
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\ACDB0955\p
C:\h\w\ACDB0955\w\AB310971\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\Vector128_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._General_Vector128_Vector128_r_Vector128_r_._General_Vector128_Vector128_r_Vector128_r_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
TYP_UINT is only meaningful for certain operations in the JIT and nodes
can/should never produce values of this type.

Fix #71360

### CODE REVIEW

**Comment by jakobbotsch** [comment]
The logic in `LowerArg` that normalized small-typed nodes in an ad-hoc manner also seems strange to me. I've changed that to just use `genActualType` which would have avoided the assert on its own as well.

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -1261,13 +1261,7 @@ void Lowering::LowerArg(GenTreeCall* call, CallArg* callArg, bool late)
     DISPNODE(arg);
     assert(arg->IsValue());
 
-    var_types type = arg->TypeGet();
-
-    if (varTypeIsSmall(type))
-    {
-        // Normalize 'type', it represents the item that we will be storing in the Outgoing Args
-        type = TYP_INT;
```
Comment (kunalspathak) [inline src/coreclr/jit/lower.cpp:1269]: Just that I understand, was there an inconsistency in the way we set type here to `TYP_INT` but not doing the same in `ToScalar()`?

Comment (kunalspathak) [reply src/coreclr/jit/lower.cpp:1269]: Got it. So is the assert reported in https://github.com/dotnet/runtime/issues/71360 is the only one that checks for this or do we have other places we make sure that type is never one of `TYP_UINT` or `TYP_ULONG`?

Comment (kunalspathak) [reply src/coreclr/jit/lower.cpp:1269]: Sounds good to me.

**Review by kunalspathak — APPROVED** [review]
LGTM

File: src/coreclr/jit/lower.cpp (hunk 1 above)
Comment (tannergooding) [reply src/coreclr/jit/lower.cpp:1269]: > and maybe some SIMD base types

Its most SIMD base types in practice. The SIMD base type should always be the exact type required for the underlying instruction. That includes correctly tracking the sign and size. This is important because there are many SIMD instructions that differ based on size/type and will do the wrong thing otherwise.

It was definitely a bug that the `gtType` wasn't the right thing, however.
