### PR TITLE
[wasm][debugger] Support NO_PROXY": "localhost" in launchSettings.json

### LINKED ISSUE #88051: Blazor Wasm debugging with a proxy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not sure where/how to get an answer from this.  WASM Hosted debugs successfully on my personal computer.  However working in an enterprise environment that uses a proxy there is a problem.  I created a vanilla Blazor WASM Hosted project using the VS template.  
launchSettings.json has the
"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
lines

When I F5 for debug I get (I have used square brackets to replace sensitive values):

 Content root path: [MY PATH]\repos\BlazorWasmVanilla\BlazorWasmVanilla\Server\
got exception System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://[ENTERPRISE_PROXY].com/' failed with status code '403'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   
The only thing (and I don't know that it is a thing) is that the proxy in my machine's Environment Variable has port 80 specified (the :80 suffix) which I don't see in the error message.

What can resolve this debugging issue?

### Expected Behavior

Create Blazor WASM hosted project using standard template.
Press F5, run in debug mode

### Steps To Reproduce

Within an enterprise using a proxy
Create Blazor WASM hosted project using standard template.
Press F5, run in debug mode

### Exceptions (if any)

info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7086
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5007
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\...\repos\BlazorWasmVanilla\BlazorWasmVanilla\Server\
got exception System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://[...].com/' failed with status code '403'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
   at Microsoft.WebAssembly.Diagnostics.DebugExtensions.<>c__DisplayClass2_0.<<UseDebugProxy>g__ConnectProxy|5>d.MoveNext()

C:\Users\[...]\repos\BlazorWasmVanilla\BlazorWasmVanilla\Server\bin\Debug\net6.0\BlazorWasmVanilla.Server.exe (process 35192) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

### .NET Version

Tried with .Net 6 and .Net 7

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thaystg**
Fixes https://github.com/dotnet/runtime/issues/88051
Depends on https://github.com/dotnet/aspnetcore/pull/49395

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/DevToolsProxy.cs [hunk 1]
```diff
@@ -235,6 +238,9 @@ public async Task RunForDevTools(Uri browserUri, WebSocket ideSocket, Cancellati
 
                 ClientWebSocket browserSocket = new();
                 browserSocket.Options.KeepAliveInterval = Timeout.InfiniteTimeSpan;
+                var proxy = WebRequest.DefaultWebProxy;
+                if (_options is not null && _options.IgnoreProxyForLocalAddress && proxy is not null && !proxy.IsBypassed(browserUri))
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DevToolsProxy.cs:242]: I'm not sure I understand. How is `IgnoreProxyForLocalAddress` being honored here, when we are not checking if the `browserUri` is a local address or not?

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/DevToolsProxy.cs:242]: Looking at https://github.com/dotnet/aspnetcore/pull/49395/files

`var ignoreProxyForLocalAddress = (noProxyEnvVar is not null && (noProxyEnvVar.Equals("localhost") || noProxyEnvVar.Equals("127.0.0.1"))) ? "--IgnoreProxyForLocalAddress True" : "";`

.. it is passing `true` as the argument if the url is local. So, the check is on blazor side and not the proxy here. Would it make more sense to name this `IgnoreProxy` then?

Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/DevToolsProxy.cs:242]: I think browserUri is always a local address right?

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/DevToolsProxy.cs:242]: The app/browser could be running on a remote machine, IIUC. For example, in case of running the proxy on codespaces but the browser/app on a local machine.

**Review by radical — APPROVED** [review]

**Comment by MattDowningShell** [comment]
This is great, will this be in .Net 8 Preview 7?
