### PR TITLE
Loop cloning for Span

### LINKED ISSUE #82946: Loops aren't cloned for Spans
```csharp
void Test(Span<byte> source)
{
    for (int i = 0; i < 100; i++)
        source[i] = 0;
}
```
Codegen:
```asm
; Method Progr:Test(System.Span`1[ubyte]):this
G_M11420_IG01:              
       4883EC28             sub      rsp, 40
G_M11420_IG02:              
       33C0                 xor      eax, eax
                            align    [0 bytes for IG03]
G_M11420_IG03:              
       3B4208               cmp      eax, dword ptr [rdx+08H]
       7317                 jae      SHORT G_M11420_IG05
       488B0A               mov      rcx, bword ptr [rdx]
       448BC0               mov      r8d, eax
       42C6040100           mov      byte  ptr [rcx+r8], 0
       FFC0                 inc      eax
       83F864               cmp      eax, 100
       7CE9                 jl       SHORT G_M11420_IG03
G_M11420_IG04:              
       4883C428             add      rsp, 40
       C3                   ret      
G_M11420_IG05:              
       E829C64C5F           call     CORINFO_HELP_RNGCHKFAIL
       CC                   int3     
; Total bytes of code: 40
```
```
*************** Starting PHASE Clone loops

*************** In optCloneLoops()
Considering loop L00 to clone for optimizations.
Not checking loop L00 -- no array bounds or type tests in this method
------------------------------------------------------------

  No clonable loops

*************** Finishing PHASE Clone loops
```
Here it is expected to have two loops and one of them without bound checks.

cc @BruceForstall @dotnet/jit-contrib 

category:cq
theme:loop-opt
skill-level:expert
cost:medium
impact:large

### LINKED ISSUE #110986: JIT doesn't elide bounds checking when iterating over a span and an array of known length
### Description

If you ensure that the length of an array and a span are the same, the JIT will still emit bounds checking on only the span when indexing.
This does not occur when iterating over a span and a span, or an array and an array.

```csharp
public static int SumSpanArray(int[] arr, Span<int> span)
{
    int counter = 0;
    
    if(arr.Length != span.Length)
        return 0;
    
    //bounds check here
    for(int i = 0; i < arr.Length; i++)
        counter += arr[i] + span[i];
    
    return counter;
}
```

Sharplab example [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBoEsA7DGKB7AGwAIzvyB2GgG8anUdwDMvJJ0YZOAZQCu+ACoB3CAEEoUbAE9cAClkBtALqdsO8mhlNzlnaQCUIscOpivduZEVMWTgBeTgAGAG43b04o7zoAM0MrKHIAOgAZGAYAcwwAC04AQhDk0gys3LzXT2jvYj4wyJro2K8AejbgCH8AE1xOMDyYMABrThh2Oh6YHtaxeOhjJhlgxpWAHkcU8pz88JkAagPq2u8/AKhOA5LrEzoLA63SO7Mm07nReoHui7exAF9YrFiJJiORpLIFMp5AAHbAMbS6PRLDAOZK2WHw9ayAB8nFwcIYJ3cHx8338zEuIQipNJCSSOh2lSKIQJ8KZ+WJp0+DRpzW8pI6XV6/UGwzGQ1gpIWUBRK2p+zonE2yQ5eUVRy53POlKuNygLyu+MJLz+LX5Xi+OpYZs4gP5wNB4LJSnwmIROn0pBRaJ0GMJ2KYeLZRNiHlOkOtVMatItYnpqsyuwKxWN7KTlS1py+fPecdEHTAiigdG6uHYels+To/R6EBguAYAHI5LBcIp2HJGJZOMKGH0BkNRtLFpClQqNmmGGqNcdSV4o3qtobHiHTbHsw0o7b7f8gA)

### Regression?

I have only used Sharplab to test this, but it doesn't seem likely to be a regression.

### Analysis

I don't know why, but curiously enough when checking the span length when iterating over a span + array, there is no bound check

```csharp
public static int SumSpanArray2(int[] arr, Span<int> span)
{
    int counter = 0;
    
    if(arr.Length != span.Length)
        return 0;
    
    //no bound check
    for(int i = 0; i < span.Length; i++)
        counter += arr[i] + span[i];
    
    return counter;
}
```

### LINKED ISSUE #112019: JIT: Bounds check not elided for inlined function with safe arguments on Windows
JIT currently elides bounds check for `for (int i = 0; i < arr.Length; i++)` loops.
When `ClearBase` is inlined with the given function arguments it is equivalent to exactly that, however the bounds check is not removed when targeting windows. See: https://godbolt.org/z/PMx8oPrM9. With `int[]` the redundant check is gone.
```cs
static void Clear(Span<int> arr)
{
    ClearBase(arr, arr.Length);
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
static void ClearBase(Span<int> arr, int len)
{
    for (int i = 0; i < len; i++)
    {
        arr[i] = 0;
    }
}
```
```assembly
Program:Clear(System.Span`1[int]) (FullOpts):
       sub      rsp, 40
       mov      rax, bword ptr [rcx]
       mov      ecx, dword ptr [rcx+0x08]
       mov      edx, ecx
       xor      r8d, r8d
       test     ecx, ecx
       jle      SHORT G_M46351_IG04
       align    [13 bytes for IG03]
G_M46351_IG03:  ;; offset=0x0020
       cmp      r8d, edx
       jae      SHORT G_M46351_IG05
       xor      r10d, r10d
       mov      dword ptr [rax+4*r8], r10d
       inc      r8d
       cmp      r8d, ecx
       jl       SHORT G_M46351_IG03
G_M46351_IG04:  ;; offset=0x0034
       add      rsp, 40
       ret      
G_M46351_IG05:  ;; offset=0x0039
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
```

### PR DESCRIPTION
**Pull request by EgorBo**
This PR enables loop cloning for Spans
Closes https://github.com/dotnet/runtime/issues/82946
Closes https://github.com/dotnet/runtime/issues/110986
Closes https://github.com/dotnet/runtime/issues/112019

Example:
```cs
static void Test(Span<int> span, int len)
{
    for (int i = 0; i < len; i++)
        span[i] = 0;
}
```
Current codegen:
```asm
; Assembly listing for method Test(System.Span`1[int],int) (FullOpts)
       sub      rsp, 40
       xor      eax, eax
       test     edx, edx
       jle      SHORT G_M2065_IG04
       align    [0 bytes for IG03]
G_M2065_IG03:
       cmp      eax, dword ptr [rcx+0x08]    ;; <-- bounds check each iteration
       jae      SHORT G_M2065_IG05
       mov      r8, bword ptr [rcx]
       xor      r10d, r10d
       mov      dword ptr [r8+4*rax], r10d
       inc      eax
       cmp      eax, edx
       jl       SHORT G_M2065_IG03
G_M2065_IG04:
       add      rsp, 40
       ret    
  
G_M2065_IG05:
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
; Total bytes of code 42, prolog size 4, PerfScore 38.00
```
New codegen:
```asm
; Assembly listing for method Test(System.Span`1[int],int) (FullOpts)
       sub      rsp, 40
       xor      eax, eax
       test     edx, edx
       jle      SHORT G_M2065_IG05
       cmp      edx, dword ptr [rcx+0x08]
       jg       SHORT G_M2065_IG06
       xor      eax, eax
       align    [15 bytes for IG04]
G_M2065_IG04:
       mov      r8, bword ptr [rcx]     ;; <-- no bounds checks (fast loop)
       xor      r10d, r10d
       mov      dword ptr [r8+rax], r10d
       add      rax, 4
       dec      edx
       jne      SHORT G_M2065_IG04
G_M2065_IG05:
       add      rsp, 40
       ret      

G_M2065_IG06:
       cmp      eax, dword ptr [rcx+0x08]  ;; slow loop (cloned)
       jae      SHORT G_M2065_IG07
       mov      r8, bword ptr [rcx]
       mov      r10d, eax
       xor      r9d, r9d
       mov      dword ptr [r8+4*r10], r9d
       inc      eax
       cmp      eax, edx
       jl       SHORT G_M2065_IG06
       jmp      SHORT G_M2065_IG05
G_M2065_IG07:
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
; Total bytes of code 87, prolog size 4, PerfScore 23.38
```
Another example where this helps:
```cs
    void Test(Span<int> a, Span<int> b)
    {
        if (a.Length == b.Length)
        {
            for (int i = 0; i < a.Length; i++)
                a[i] = b[i];
        }
    }
```
previously, we couldn't optimize range check for ^

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=983876&view=ms.vss-build-web.run-extensions-tab)

### CODE REVIEW

**Comment by EgorBo** [comment]
@EgorBot -arm -amd -windows_intel
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Benchmark
{
    static int[] _array = new int[5000];

    [Benchmark]
    [Arguments(4000)]
    public int Sum(int len)
    {
        Span<int> span = _array;

        int sum = 0;
        for (int i = 0; i < len; i++)
            sum += span[i];
        return sum;
    }
}
```

**Comment by EgorBo** [comment]
@MihuBot

**Comment by bencyoung-Fignum** [comment]
Out of interest, for loop cloning, if (len > span.Length) would it more less code/more efficient to run the cloned loop up to span.Length and only then switch to the un-optimized version? Or because that path is likely to throw anyway, it's better to just do the simplest thing?

**Comment by EgorBo** [comment]
> Out of interest, for loop cloning, if (len > span.Length) would it more less code/more efficient to run the cloned loop up to span.Length and only then switch to the un-optimized version? Or because that path is likely to throw anyway, it's better to just do the simplest thing?

Yep, the current impl is easier to implement and is more generic - we also need to check array instance for being null (for arrays) and there are other kinds of cloning conditions, e.g. if we have a virtual call inside the loop, we can add an additional cloning condition for the most popular type under that virtual call (PGO).

**Comment by bencyoung-Fignum** [comment]
Thanks for the info. So would all "likely" optimization go in the optimized verison of the loop, and none of them in the fallback or could you have some combinations? E.g. potentially multiple clone loops with different assumptions? I guess you can assume the fallback is always the fully-unoptimized version as you assume there will be a failure at some point

**Comment by EgorBo** [comment]
> Thanks for the info. So would all "likely" optimization go in the optimized verison of the loop, and none of them in the fallback or could you have some combinations? E.g. potentially multiple clone loops with different assumptions? I guess you can assume the fallback is always the fully-unoptimized version as you assume there will be a failure at some point

It depends. Normally, yes, fallback is not expected to be hit in normal circumstances unless code is relying on OOB exception, but it is not the case for virtual calls, we clone loops with them but the fallback still may be invoked (when some other type arrives), we discussed this recently in https://github.com/dotnet/runtime/pull/113579#issuecomment-2727685204

**Comment by EgorBo** [comment]
@MihuBot

**Comment by EgorBo** [comment]
@AndyAyersMS @BruceForstall @dotnet/jit-contrib PTAL

Surprisingly, it was not difficult, my changes are mostly cosmetic (with asserts). Basically, if we have a LCL_VAR length, we don't need to deref the array object (it was either already dereferenced when this local was created, or it's a local span that doesn't need any dereference).

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=983876&view=ms.vss-build-web.run-extensions-tab) look sane to me, the TP impact is ~0.2% on average with a huge outlier in `libraries_tests.run.`, however, same happens today for existing array cloning (for reference, here are the diffs for Main where loop cloning is disabled: [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=982200&view=ms.vss-build-web.run-extensions-tab)). The diffs are PerfScore improvements, they're better if we mark the cloned loop (slow one) as cold (today, we mark it as 0.01 weight).

Outerloop failures are not related.

**Review by BruceForstall — COMMENTED** [review]
You've overloaded the existing "jagged" array implementation with a case to support Span. Is this the cleanest way to express this? Would it be better to introduce a new `LC_OPT(LcSpan)` "type" of optimization (and maybe a `LC_Span` type that parallels `LC_Array`, etc.)?

Can Span participate in "jagged" arrays? E.g., for `a[x][y][z]`, can `a` be a `Span`, `a[x]` be a span, `a[x][y]` be an array?

File: src/coreclr/jit/loopcloning.cpp [hunk 1]
```diff
@@ -1161,13 +1185,19 @@ bool Compiler::optDeriveLoopCloningConditions(FlowGraphNaturalLoop* loop, LoopCl
     // is beyond the limit.
     int stride = abs(iterInfo->IterConst());
 
-    if (stride >= 58)
+    static_assert_no_msg(INT32_MAX >= CORINFO_Array_MaxLength);
+    if (stride >= (INT32_MAX - CORINFO_Array_MaxLength))
```
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/coreclr/jit/loopcloning.cpp]: Restored. although, I keep the named constants as nothing stops GC from lifting this limitation in future (ideally, it should be a JIT-EE API)

**Comment by EgorBo** [comment]
> You've overloaded the existing "jagged" array implementation with a case to support Span. Is this the cleanest way to express this? Would it be better to introduce a new `LC_OPT(LcSpan)` "type" of optimization (and maybe a `LC_Span` type that parallels `LC_Array`, etc.)?

@BruceForstall The basic idea that we just don't know what we work with - it could be just same array with GT_BOUND_CHECK.op2 being LCL_VAR instead of GT_ARR_LENGTH, there is nothing Span specific. It allows us to only skip the object dereference part. I can try to build LcSpan (although it could still be an array) abstraction, but I presume it will be copy-paste.

> Can Span participate in "jagged" arrays? E.g., for `a[x][y][z]`, can `a` be a `Span`, `a[x]` be a span, `a[x][y]` be an array?

The PR gives up on such combinations, not sure people mix them this way. Span might have their own jagged Span in future `Span<ReadOnlySpan<T>>`, but it's not supported today by C# compiler (JaredP said it might be doable).

**Comment by EgorBo** [comment]
@BruceForstall I've addressed your feedback. The impl is 2x bigger now, but I agree that it looks better

File: src/coreclr/jit/loopcloning.cpp [hunk 2]
```diff
@@ -1154,23 +1195,37 @@ bool Compiler::optDeriveLoopCloningConditions(FlowGraphNaturalLoop* loop, LoopCl
     }
 
     const bool isIncreasingLoop = iterInfo->IsIncreasingLoop();
-    assert(isIncreasingLoop || iterInfo->IsDecreasingLoop());
+    if (!isIncreasingLoop && !iterInfo->IsDecreasingLoop())
+    {
+        // Normally, we reject weird-looking loops in optIsLoopClonable, but it's not the case
```
Comment (EgorBo) [inline src/coreclr/jit/loopcloning.cpp:1200]: A small pre-existing issue, can be reproduced in Main via this snippet 

```
<details>
  <summary>Click me</summary>
  
```cs
using System;
using System.Runtime.CompilerServices;

class Program : IDisposable
{
    public static void Main()
    {
        for (int i = 0; i < 1200; i++)
        {
            try
            {
                Test(new int[100000000], 44, new Program());
                Thread.Sleep(16);
            }
            catch
            {
            }
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Test(int[] arr, int x, IDisposable d)
    {
        for (int i = 0; i < x; i--)
        {
            d.Dispose();
            Console.WriteLine(arr[i]);
        }
    }

    public void Dispose()
    {
    }
}
```

</details>
```

**Comment by EgorBo** [comment]
@EgorBot -amd -arm -profiler
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    byte[] _arr1 = new byte[2000];
    byte[] _arr2 = new byte[2000];

    [Benchmark]
    [Arguments(1000)]
    public void CopyN(int elems)
    {
        Span<byte> span1 = _arr1;
        Span<byte> span2 = _arr2;

        for (int i = 0; i < elems; i++)
            span1[i] = span2[i];
    }


    [Benchmark]
    [Arguments(1000)]
    public void ReversedIter(int elems)
    {
        Span<byte> span = _arr1;

        // Reversed iteration
        for (int i = span.Length - 1; i >= 0; i--)
            span[i] = 42;
    }
}
```

File: src/coreclr/jit/loopcloning.cpp [hunk 3]
```diff
@@ -45,6 +45,22 @@ void ArrIndex::PrintBoundsCheckNodes(unsigned dim /* = -1 */)
     }
 }
 
+//--------------------------------------------------------------------------------------------------
+// Print: debug print an SpanIndex struct in form: `V01[V02]`.
+//
+void SpanIndex::Print()
+{
+    printf("V%02d[V%02d]", lenLcl, indLcl);
```
Comment (BruceForstall) [inline src/coreclr/jit/loopcloning.cpp:53]: This seems a bit odd, as it indicates that `lenLcl` is an "array", but it's actually just the length of the array (in the span). Maybe use something like `Span<V%02d>[V%02d]` instead? Basically, something to make it obvious that `lenLcl` is not an array.

**Review by BruceForstall — APPROVED** [review]
LGTM. One nit/question to consider.

File: src/coreclr/jit/loopcloning.cpp (hunk 3 above)
Comment (EgorBo) [reply src/coreclr/jit/loopcloning.cpp:53]: yep, copy-paste from ArrIndex 🙂 I'll fix the comment in a follow up (I think I found a few missing opportunities for LC)

**Comment by EgorBo** [comment]
/ba-g "wasm build failure is already fixed - https://github.com/dotnet/runtime/issues/113685"

**Comment by omariom** [comment]
@EgorBo  Does it have to deference Span's `_reference` on each iteration? 
```ASM
mov      r8, bword ptr [rcx]     ;; <-- no bounds checks (fast loop)
```

it doesn't [for arrays](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGPKQAIyGBhBgbxoe4a57sbEUDACoxcGABQBLAHYYA2gF0G2KFGwBPNAzkYGAGxiyAlH26dqPawwBm0BjPm6GAXgYAGANwuAPIeMfaQBqYLMrG0i1DU0FaRV3b3MGAF8aFKA)
```ASM
    L0020: xor eax, eax
    L0022: mov [rcx], eax
    L0024: add rcx, 4
    L0028: dec edx
    L002a: jne short L0020
```

**Comment by EgorBo** [comment]
> @EgorBo Does it have to deference Span's _reference on each iteration?

@omariom it's an unfortunate unrelated issue, in this example, JIT doesn't promote the Span arg (which is an implicit byref) into variables and loads it each iteration from the arg (stack). It rarely happens on practice as the code usually more complex and convince the JIT's struct promoter that it is profitable to promote it. I observe this issue only on Windows for these examples, e.g. same example on Linux has no issues.

We'll eventually fix it once @jakobbotsch makes the new (aka physical) promotion default
