### PR TITLE
NativeAOT: Skip TypeSpec for well-known custom attributes lookup

### LINKED ISSUE #111578: AOT enums with generic attributes don't support any reflection at all;  System.Enum Get...() methods all throw exceptions.
### Description

Eric Erhardt makes the claim in https://devblogs.microsoft.com/dotnet/creating-aot-compatible-libraries/ that if you don't get warnings, there shouldn't be different behavior in AOT...  However, I have found that there is no support for doing anything with enums on linux except assigning and comparing.  For example, I get a warning that "Using member 'System.Enum.GetValues(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. It might not be possible to create an array of the enum type at runtime. Use the GetValues<TEnum> overload or the GetValuesAsUnderlyingType method instead."   But using either of the suggestions (which gets rid of the warnings) still results in an UnsupportedException at runtime.  In fact, everything I tried with enums results in an unsupported exception. 

I found that for non-enum objects, I can slap a [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] attribute which allows reflection to work great.  But enums do not support this attribute, I couldn't find any other kind of attribute to give a hint that I want to keep the values in the assembly.

This seems like such a basic/core piece of functionality...  It would be nice if a solution could be found for this.

### Reproduction Steps

Create a console dotnet application.

csproj needs these added:

```
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishTrimmed>true</PublishTrimmed>
```
 to PropertyGroup

In the .cs file, simply

Define
  `enum Color { R, Y, G, B, C, N }`
and have a statement that does
 `Enum.GetValues<Color>();`

### Expected behavior

no crashes

### Actual behavior

Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at System.Reflection.Runtime.General.NativeFormatMetadataReaderExtensions.IsCustomAttributeOfType(CustomAttributeHandle, MetadataReader, ReadOnlySpan`1, String) + 0x466

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

(linux dotnet 8/9)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by hez2010**
Skip checking TypeSpec for well-known custom attributes.
Fixes #111578

/cc: @MichalStrehovsky

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
I think the size test is failing because the `typeHandle.Resolve` brings in the entire reflection stack.

Do we actually _need_ this to support generic attributes? Could this just skip over them as "not what we're looking for"?

**Comment by hez2010** [comment]
> Do we actually _need_ this to support generic attributes? Could this just skip over them as "not what we're looking for"?

I was originally thinking it's fine to just return a `false` if it's only for internal use, but I'm seeing this helper is `public` so that it may be called from external code?

**Comment by hez2010** [comment]
I instead go with another approach that unwraps the generic type from typespec if we see a type instantiation. This can make sure we can check for generic attributes correctly without introducing the full reflection stack.

**Comment by hez2010** [comment]
> > Could this just skip over them as "not what we're looking for"?
> 
> +1

Done.

File: src/tests/nativeaot/SmokeTests/Reflection/Reflection.cs [hunk 1]
```diff
@@ -2700,6 +2701,31 @@ public static void Run()
...
+            Assert.Equal(MyEnum.B, values[1]);
+            Assert.Equal(MyEnum.C, values[2]);
+            Assert.Equal(MyEnum.D, values[3]);
+        }
+
+        public static void Run()
+        {
+            GetEnumValues();
+        }
+    }
```
Comment (MichalStrehovsky) [inline src/tests/nativeaot/SmokeTests/Reflection/Reflection.cs:2727]: The bug was in reading FlagsAttribute, it's a bit better to have a test that directly exercises something that needs it. GetValues doesn't need it, it just happens to run the codepath that reads it anyway.

```suggestion
    class TestGenericAttributesOnEnum
    {
        class MyAttribute<T> : Attribute { }

        [My<int>]
        enum MyEnum { A = 1, B = 2 }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static object GetVal() => MyEnum.A | MyEnum.B;

        public static void Run()
        {
            if (GetVal().ToString() != "3")
                throw new Exception();
        }
    }
```

File: src/coreclr/nativeaot/System.Private.CoreLib/src/System/Reflection/Runtime/General/MetadataReaderExtensions.NativeFormat.cs [hunk 2]
```diff
@@ -482,6 +482,7 @@ public static bool IsCustomAttributeOfType(this CustomAttributeHandle customAttr
         {
             Handle typeHandle = customAttributeHandle.GetCustomAttribute(reader).GetAttributeTypeHandle(reader);
             HandleType handleType = typeHandle.HandleType;
+
```
Comment (MichalStrehovsky) [inline src/coreclr/nativeaot/System.Private.CoreLib/src/System/Reflection/Runtime/General/MetadataReaderExtensions.NativeFormat.cs:485]:
```suggestion
```

**Review by MichalStrehovsky — APPROVED** [review]
Thank you for the quick fix!
