### PR TITLE
JIT: Use small register types for some enregisterable locals

### LINKED ISSUE #67152: OSR failure in System.Text.Json.Tests
x64 Ubuntu
```
export COMPlus_TieredCompilation=1
export COMPlus_TC_OnStackReplacement=1
export COMPlus_TC_QuickJitForLoops=1

  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 2)
    System.Text.Json.Tests.Utf8JsonReaderTests.ReadJsonStringsWithCommentsAndTrailingCommas(jsonString: "{\"Property1\": {\"Property1.1\": 42} // comment\n"...) [FAIL]
```
Via `COMPlus_JitEnablePatchpointRange` I have isolated this down to
```
System.Text.Json.Tests.Utf8JsonReaderTests::ReadJsonStringsWithCommentsAndTrailingCommas, IL size = 399, hash=0xc1a3563b 
Tier1-OSR @0x159
```

### LINKED ISSUE #67188: Spilling can overwrite adjacent stack parameters on ARM64 macOS ABI
Reproduction:
```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static int Problem(int x0, int x1, int x2, int x3, int x4, int x5, int x6, int x7, short stk0, short stk1)
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static int Call(int k) => 0;

    stk1 = (short)(stk0 + stk1 + stk0);

    Call(stk1);

    return stk0 + stk1;
}
```
Compile with CG2: `--targetarch:arm64 --targetos:OSX --codegenopt NgenDump=Problem --codegenopt JitNoCSE=1 --codegenopt JitStressRegs=2`.

Expected result: spilling of the small stack parameters cannot overwrite anything.

Actual result: it can, due to using `TYP_INT`-wide stores:
```asm
IN0014: 000008  B94013A1          ldr     w1, [fp,#16]  // [V08 arg8]
IN0015: 00000C  B84123A2          ldr     w2, [fp,#18]  // [V09 arg9]

...

IN0008: 00002C  B90013A1          str     w1, [fp,#16]
```

Essentially this is the same issue as in #67152.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Fix two cases where small enregisterable locals can't be saved to the stack
using actual (widened) types:
* small memory args for OSX ARM64
* promoted fields of OSR locals

Closes #67152.
Closes #67188.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@egorbo PTAL
cc @dotnet/jit-contrib 

I don't have a simple repro as the failures above are only seen in spilling.

**Comment by AndyAyersMS** [comment]
CI hit two test failures

Ubuntu amd64
```
  Starting:    System.Text.Json.SourceGeneration.Roslyn3.11.Tests (parallel test collections = on, max threads = 2)
Process terminated. Assertion failed.
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropCache() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.Cache.cs:line 613
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonMetadataServicesConverter.cs:line 60
```
Alpine arm64
```
  Starting:    System.Collections.Concurrent.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 23 [0x00000017], Thread: 116 [0x0074]): m_alignpad == 0
    File: /__w/1/s/src/coreclr/vm/syncblk.cpp Line: 2952
    Image: /root/helix/work/correlation/dotnet
```
Neither repros locally (I don't have alpine arm64 hw, so ran on OSX).

Will retry these.

**Review by kunalspathak — APPROVED** [review]
LGTM

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/lclvars.cpp [hunk 1]
```diff
@@ -3825,8 +3825,28 @@ var_types LclVarDsc::GetRegisterType() const
...
+// Notes:
+//    Special cases are small OSX ARM64 memory params (where args are not widened)
+//    and small local promoted fields (which use Tier0 frame space as stack homes)
+//
 var_types LclVarDsc::GetActualRegisterType() const
 {
+    if (varTypeIsSmall(TypeGet()))
+    {
+
+#ifdef OSX_ARM64_ABI
```
Comment (SingleAccretion) [inline src/coreclr/jit/lclvars.cpp:3837]: Does this define exist?

I would have expected a `compMacOsArm64Abi()` check.

**Comment by jakobbotsch** [comment]
We really should run Antigen and Fuzzlyn on macOS. I would expect this to be the kind of bug that they could find quickly.

**Comment by EgorBo** [comment]
> We really should run Antigen and Fuzzlyn on macOS. I would expect this to be the kind of bug that they could find quickly.

is that something difficult to setup?

**Comment by jakobbotsch** [comment]
> > We really should run Antigen and Fuzzlyn on macOS. I would expect this to be the kind of bug that they could find quickly.
> 
> is that something difficult to setup?

Probably not, I am making a PR right now :-)

File: src/coreclr/jit/lclvars.cpp [hunk 2]
```diff
@@ -3825,8 +3825,28 @@ var_types LclVarDsc::GetRegisterType() const
...
+        if (lvIsParam && !lvIsRegArg)
+        {
+            return GetRegisterType();
+        }
+#endif
+
+        if (lvIsOSRLocal && lvIsStructField)
+        {
+            return GetRegisterType();
+        }
```
Comment (SingleAccretion) [inline src/coreclr/jit/lclvars.cpp:3847]: Worth adding a comment and/or assert about how this will not work on x86 due to the byteability requirement?

(I realize OSR isn't supported on x86 right now)

File: src/coreclr/jit/lclvars.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lclvars.cpp:3837]: Right, thanks.

File: src/coreclr/jit/lclvars.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/lclvars.cpp:3847]: Sure.

**Comment by AndyAyersMS** [comment]
On the repro from #67188 
```asm

;; before

        910003FD          mov     fp, sp
        B94013A2          ldr     w2, [fp,#16]	// [V08 arg8]
        B84123A1          ldr     w1, [fp,#18]	// [V09 arg9]
						;; bbWeight=1    PerfScore 5.50
G_M37948_IG02:              ;; offset=0010H
        13003C40          sxth    w0, w2
        13003C21          sxth    w1, w1
        0B010000          add     w0, w0, w1
        B90013A2          str     w2, [fp,#16]
        13003C4B          sxth    w11, w2
        0B0B0000          add     w0, w0, w11
        13003C01          sxth    w1, w0
        B80123A1          str     w1, [fp,#18]

;; after 

        79C023A2          ldrsh   w2, [fp,#16]	// [V08 arg8]
        79C027A1          ldrsh   w1, [fp,#18]	// [V09 arg9]
						;; bbWeight=1    PerfScore 5.50
G_M37948_IG02:              ;; offset=0010H
        13003C40          sxth    w0, w2
        13003C21          sxth    w1, w1
        0B010000          add     w0, w0, w1
        790023A2          strh    w2, [fp,#16]
        13003C4B          sxth    w11, w2
        0B0B0000          add     w0, w0, w11
        13003C01          sxth    w1, w0
        790027A1          strh    w1, [fp,#18]
```
