### PR TITLE
[browser] Add `OutputType=Library` tests

### LINKED ISSUE #110620: [browser] Add test for OutputType=Library
`OutputType=Library` has same publish/deployment story as `OutputType=Exe`. 
It will create `AppBundle` with all necessary JS files.
User has to call `dotnet.create()` from `dotnet.js` before `getAssemblyExports()` is available. 
The only difference is that this mode doesn't require `Main()` method and `runMain` should fail.

We should cover scenarios from https://github.com/dotnet/runtime/pull/102806 with automated tests
Also discussed in https://github.com/dotnet/runtime/pull/109866#discussion_r1845416384
Check if wasi has enough test coverage

Possible use-cases with browser build (described in https://github.com/dotnet/runtime/pull/102806 for WASI)
### 1. "I want to create a plain old .NET library"
  - Nothing WASM specific needed
  - Output is managed dll
  - Can be distributed as nuget package)

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
</Project>
 ```

### 2. "I want to create a .NET library with access to browser specific APIs"
  - Use standard .NET SDK
  - Set `RuntimeIdentifier` to `browser-wasm`
  - Output is managed dll
  - Can be distributed as nuget package)

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
  </PropertyGroup>
</Project>
 ```

### 3. "I want to create a .NET application running in browser and have a meaningful main method" (like Blazor does)
  - Use `Microsoft.NET.Sdk.WebAssembly` (or `Microsoft.NET.Sdk.BlazorWebAssembly`) SDK
  - `RuntimeIdentifier` implicitly set to `browser-wasm`
  - Output is `app bundle` (dotnet.js, .NET runtime, managed dlls)
  - Can be deployed to server

```
<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
</Project>
 ```

### 4. "I want to create a .NET application running in browser, but my use-case doesn't have a meaningful main method" (I don't have a single entrypoint into my .NET code, but rather want to call JSExports from JavaScript)
  - Use `Microsoft.NET.Sdk.WebAssembly` SDK
  - `RuntimeIdentifier` implicitly set to `browser-wasm`
  - Output is `app bundle` (dotnet.js, .NET runtime, managed dlls)
  - Can be deployed to server, can be wrapped as NPM package

```
<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
</Project>
 ```

### 5. In use-case 4. a situation can occur when two such applications should be hosted on a single page
- a) Each app is built separately and loaded separately (loading 2 .NET runtimes, 2 set of framework dlls trimmed to each needs)
- b) Unifying project is created, the two app projects are referenced and a single app bundle is created and deployed

A.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
  </PropertyGroup>
</Project>
 ```

B.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
  </PropertyGroup>
</Project>
 ```

App.csproj
```
<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="A.csproj" />
    <ProjectReference Include="B.csproj" />
  </ItemGroup>
</Project>
 ```

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/110620.

### CODE REVIEW

File: src/mono/wasi/testassets/LibraryMode.cs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+using System;
+using System.Runtime.InteropServices;
+public unsafe class Test
+{
+    [UnmanagedCallersOnly(EntryPoint = "MyCallback")]
```
Comment (ilonatommy) [inline src/mono/wasi/testassets/LibraryMode.cs:5]: It's same as browser's `LibraryMode.cs` but I can't see a good place for common test assets location. Each: wasi and browser has their own `BuildEnvironment.TestAssetsPath`. Maybe after refactoring wasi WBT we could solve such duplicates?

**Review by javiercn — APPROVED** [review]

**Comment by pavelsavara** [comment]
please let's discuss the goals of this before we proceed further

**Comment by maraf** [comment]
> please let's discuss the goals of this before we proceed further

The use-case on browser is something like this demo https://github.com/maraf/dotnet-wasm-react. It doesn't need `main`, because there is no single entrypoint from .NET point of view. The application is driven by JavaScript

**Comment by pavelsavara** [comment]
> > please let's discuss the goals of this before we proceed further
> 
> The use-case on browser is something like this demo https://github.com/maraf/dotnet-wasm-react. It doesn't need `main`, because there is no single entrypoint from .NET point of view. The application is driven by JavaScript

But something still needs to call JS API `dotnet.create()`. There needs to be the emscripten, `AppBundle` and `dotnet.js` as build/publish output of such "library". If this is what we want, we should also define how it behaves when people add such "library" into Blazor WASM app or add two such "libraries" as dependencies to another project. Should it create one AppBundle ? Should it be same dotnet runtime ? Should it be trimmed together ?

**Comment by pavelsavara** [comment]
There are updated requirements in https://github.com/dotnet/runtime/issues/110620 description

File: src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs [hunk 2]
```diff
@@ -281,5 +281,24 @@ void AssertFile(string suffix)
                 Assert.True(copyOutputSymbolsToPublishDirectory == (fileName != null && File.Exists(fileName)), $"The {fileName} file {(copyOutputSymbolsToPublishDirectory ? "should" : "shouldn't")} exist in publish folder");
             }
         }
+
+        [Theory]
+        [InlineData("Microsoft.NET.Sdk", false, "<TargetIdentifier>browser-wasm</TargetIdentifier>")]
```
Comment (maraf) [inline src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs:286]:
```suggestion
        [InlineData("Microsoft.NET.Sdk", false, "< RuntimeIdentifier >browser-wasm</RuntimeIdentifier >")]
```

Comment (ilonatommy) [reply src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs:286]: this made it, we have an error:
`Program does not contain a static 'Main' method suitable for an entry point`
Thanks!

Comment (ilonatommy) [reply src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs:286]: btw: why do we support both: `RuntimeIdentifier` and `TargetIdentifier` and why using one has different effects than using the other?

**Review by maraf — COMMENTED** [review]
Please, add also an index.html and main.js to the library mode testasset. The main.js will start the runtime and instead of calling main, it will call just the JSExport. Ideally, also run the app in the browser

File: src/mono/wasm/testassets/LibraryMode/wwwroot/index.html [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+
+<body>
+  <h1>Stopwatch</h1>
+  <p>
+    Time elapsed in .NET is <span id="time"><i>loading...</i></span>
+  </p>
+  <p>
+    <button id="pause">Pause</button>
+    <button id="reset">Reset</button>
+  </p>
```
Comment (maraf) [inline src/mono/wasm/testassets/LibraryMode/wwwroot/index.html:21]:
```suggestion
```

File: src/mono/wasm/testassets/LibraryMode/wwwroot/main.js [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+const { setModuleImports, getAssemblyExports, getConfig } = await dotnet
+    .withApplicationArguments("start")
+    .create();
+
+setModuleImports('main.js', {
+    dom: {
+        setInnerText: (selector, time) => document.querySelector(selector).innerText = time
+    }
+});
+
```
Comment (maraf) [inline src/mono/wasm/testassets/LibraryMode/wwwroot/main.js:15]:
```suggestion
```

File: src/mono/wasm/testassets/LibraryMode/wwwroot/main.js [hunk 5]
```diff
@@ -0,0 +1,19 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+import { dotnet } from './_framework/dotnet.js'
+
+const { setModuleImports, getAssemblyExports, getConfig } = await dotnet
+    .withApplicationArguments("start")
```
Comment (maraf) [inline src/mono/wasm/testassets/LibraryMode/wwwroot/main.js:7]:
```suggestion
```

**Review by maraf — APPROVED** [review]
