### PR TITLE
Fix incorrect definition of LSA_FOREST_TRUST_RECORD in System.DirectoryServices

### LINKED ISSUE #68240: Assembly.GetTypes fails on System.DirectoryServices assembly
### Description

When calling `Assembly.GetTypes` on the assembly `System.DirectoryServices` a `ReflectionTypeLoadException` is thrown.

```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'System.DirectoryServices.ActiveDirectory.LSA_FOREST_TRUST_RECORD' from assembly 'System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it contains an object field at offset 16 that is incorrectly aligned or overlapped by a non-object field.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at DirectoryServicesIssue.Program.Main(String[] args) in C:\Development\test\carebear\DirectoryServicesIssue\Program.cs:line 13
System.TypeLoadException: Could not load type 'System.DirectoryServices.ActiveDirectory.LSA_FOREST_TRUST_RECORD' from assembly 'System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it contains an object field at offset 16 that is incorrectly aligned or overlapped by a non-object field.
```

### Reproduction Steps

1. Create new console app using .NET 7.0.0 Preview 3
2. Add System.DirectoryServices package `<PackageReference Include="System.DirectoryServices" Version="7.0.0-preview.3.22175.4" />`
3. Add the code below to Program.cs
4. Run

```csharp
//Use System.DirectoryServices
var _ = new DirectorySearcher("testing");
//GetTypes
var assembly = AppDomain.CurrentDomain.GetAssemblies().Single(x => x.GetName().Name == "System.DirectoryServices");
assembly.GetTypes();
```

### Expected behavior

ReflectionTypeLoadException should not be thrown

### Actual behavior

ReflectionTypeLoadException is thrown

### Regression?

Yes, works as expected when using the 6.0.0 version of the System.DirectoryServices nuget package

### Known Workarounds

Don't call GetTypes on the System.DirectoryServices assembly

### Configuration

.NET 7.0.0 Preview 3
Windows 10 21H2
x64

### Other information

I think it is due to this change here https://github.com/dotnet/runtime/commit/a61c1a3cf5a3391c8df61d5db739ba7d1674bba5#diff-bb93fc33786f17ce709a25bd79b94cf4e6c5e2ba8ac5b4b0f728dcb35d2ac77dL415

`LSA_UNICODE_STRING` (class) was replaced with `global::Interop.UNICODE_STRING` (struct) causing a mismatch since `LSA_FOREST_TRUST_BINARY_DATA` and `LSA_FOREST_TRUST_DOMAIN_INFO` are both classes and use the same FieldOffset

### PR DESCRIPTION
**Pull request by elinor-fung**
Fixes #68240

Switch `LSA_FOREST_TRUST_DOMAIN_INFO` and  `LSA_FOREST_TRUST_BINARY_DATA` to be structs as well.

Added a test that just loads all types in `System.DirectoryServices`.

Manually ran:
```csharp
Forest forest = Forest.GetCurrentForest();
foreach (var t in forest.GetAllTrustRelationships())
{
    if (t is ForestTrustRelationshipInformation f)
    {
        Console.WriteLine("TopLevelNames");
        foreach (var name in f.TopLevelNames)
        {
            Console.WriteLine($"  {((TopLevelName)name).Name}");
        }
        Console.WriteLine("ExcludedTopLevelNames");
        foreach (string name in f.ExcludedTopLevelNames)
        {
            Console.WriteLine($"  {name}");
        }
        Console.WriteLine("TrustedDomainInformation");
        foreach (var info in f.TrustedDomainInformation)
        {
            Console.WriteLine($"  {((ForestTrustDomainInformation)info).DnsName}");
        }
    }
}
```

cc @AaronRobinsonMSFT @jkoritzinsky I broke this back in December when we were switching things to the p/invoke source generator

### CODE REVIEW

File: src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/UnsafeNativeMethods.cs [hunk 1]
```diff
@@ -445,7 +445,7 @@ internal sealed class LSA_FOREST_TRUST_DOMAIN_INFO
     }
 
     [StructLayout(LayoutKind.Sequential)]
```
Comment (AaronRobinsonMSFT) [inline src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/UnsafeNativeMethods.cs:447]: Nit: Now that all these types are `struct`s we can remove `[StructLayout(LayoutKind.Sequential)]`.

File: src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ForestTrustRelationshipInformation.cs [hunk 2]
```diff
@@ -381,30 +379,30 @@ private void GetForestTrustInfoHelper()
                                 if (record.ForestTrustType == LSA_FOREST_TRUST_RECORD_TYPE.ForestTrustTopLevelName)
                                 {
                                     IntPtr myPtr = IntPtr.Add(addr, 16);
-                                    Marshal.PtrToStructure(myPtr, record.TopLevelName);
+                                    record.TopLevelName = (global::Interop.UNICODE_STRING)Marshal.PtrToStructure(myPtr, typeof(global::Interop.UNICODE_STRING))!;
```
Comment (AaronRobinsonMSFT) [inline src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ForestTrustRelationshipInformation.cs:382]: If this is unsafe already, I would instead go for the easier dereference.

```csharp
record.TopLevelName = *(global::Interop.UNICODE_STRING*)myPtr;
```

Comment (AaronRobinsonMSFT) [reply src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/ForestTrustRelationshipInformation.cs:382]: All can now be converted to that pattern.

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectoryServicesTests.cs [hunk 3]
```diff
@@ -14,6 +15,13 @@ public partial class DirectoryServicesTests
         internal static bool IsLdapConfigurationExist => LdapConfiguration.Configuration != null;
         internal static bool IsActiveDirectoryServer => IsLdapConfigurationExist && LdapConfiguration.Configuration.IsActiveDirectoryServer;
 
+        [Fact]
+        public void TestGetAllTypes()
+        {
+            Type[] allTypes = typeof(DirectoryEntry).Assembly.GetTypes();
```
Comment (danmoseley) [inline src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectoryServicesTests.cs:21]: I wonder whether it would be possible (later) to write a test that did this for each of our implementation assemblies, without actually pasting in the test into every one.

Something like - a common file that was included in all test assemblies, with a test that enumerated all loaded assemblies and did GetTypes on them.

**Review by jkoritzinsky — APPROVED** [review]

File: src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectoryServicesTests.cs (hunk 3 above)
Comment (elinor-fung) [reply src/libraries/System.DirectoryServices/tests/System/DirectoryServices/DirectoryServicesTests.cs:21]: I opened https://github.com/dotnet/runtime/issues/68341 to track trying to do something like this.
