### PR TITLE
JIT: fix gc hole in peephole optimizations

### LINKED ISSUE #77661: Test failure JIT/Directed/nullabletypes/Desktop/boxunboxvaluetype_ro/boxunboxvaluetype_ro.sh
Run: [runtime-coreclr gcstress-extra 20221029.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67178&view=ms.vss-test-web.build-test-results-tab&runId=1368242&resultId=110288&paneView=debug)

Failed test:
```
coreclr OSX arm64 Checked gcstress0xc_jitstress2 @ OSX.1200.ARM64.Open

- JIT/Directed/nullabletypes/Desktop/boxunboxvaluetype_ro/boxunboxvaluetype_ro.sh

coreclr windows arm64 Checked gcstress0xc_jitstress2 @ Windows.10.Arm64v8.Open

- JIT\\Directed\\nullabletypes\\Desktop\\boxunboxvaluetype_ro\\boxunboxvaluetype_ro.cmd
- JIT\\Directed\\nullabletypes\\Desktop\\boxunboxvaluetype_do\\boxunboxvaluetype_do.cmd

coreclr windows arm64 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Arm64v8.Open

- JIT\\Directed\\nullabletypes\\Desktop\\boxunboxvaluetype_ro\\boxunboxvaluetype_ro.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      /tmp/helix/working/A66408B2/w/B88D09D2/uploads/Reports/JIT.Directed/nullabletypes/Desktop/boxunboxvaluetype_ro/boxunboxvaluetype_ro.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A66408B2/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false boxunboxvaluetype_ro.dll ''
--- char? s = Helper.Create(default(char)) ---
--- char? s = null ---
--- char u = Helper.Create(default(char)) ---
--- bool? s = Helper.Create(default(bool)) ---
--- bool? s = null ---
--- bool u = Helper.Create(default(bool)) ---
--- byte? s = Helper.Create(default(byte)) ---
--- byte? s = null ---
--- byte u = Helper.Create(default(byte)) ---
--- sbyte? s = Helper.Create(default(sbyte)) ---
--- sbyte? s = null ---
--- sbyte u = Helper.Create(default(sbyte)) ---
--- short? s = Helper.Create(default(short)) ---
--- short? s = null ---
--- short u = Helper.Create(default(short)) ---
--- ushort? s = Helper.Create(default(ushort)) ---
--- ushort? s = null ---
--- ushort u = Helper.Create(default(ushort)) ---
--- int? s = Helper.Create(default(int)) ---
--- int? s = null ---
--- int u = Helper.Create(default(int)) ---
--- uint? s = Helper.Create(default(uint)) ---
--- uint? s = null ---
--- uint u = Helper.Create(default(uint)) ---
--- long? s = Helper.Create(default(long)) ---
--- long? s = null ---
--- long u = Helper.Create(default(long)) ---
--- ulong? s = Helper.Create(default(ulong)) ---
--- ulong? s = null ---
--- ulong u = Helper.Create(default(ulong)) ---
--- float? s = Helper.Create(default(float)) ---
--- float? s = null ---
--- float u = Helper.Create(default(float)) ---
--- double? s = Helper.Create(default(double)) ---
--- double? s = null ---
--- double u = Helper.Create(default(double)) ---
--- decimal? s = Helper.Create(default(decimal)) ---
--- decimal? s = null ---
--- decimal u = Helper.Create(default(decimal)) ---
--- IntPtr? s = Helper.Create(default(IntPtr)) ---
--- IntPtr? s = null ---
--- IntPtr u = Helper.Create(default(IntPtr)) ---
--- UIntPtr? s = Helper.Create(default(UIntPtr)) ---
--- UIntPtr? s = null ---
--- UIntPtr u = Helper.Create(default(UIntPtr)) ---
--- Guid? s = Helper.Create(default(Guid)) ---
--- Guid? s = null ---
--- Guid u = Helper.Create(default(Guid)) ---
--- GCHandle? s = Helper.Create(default(GCHandle)) ---
--- GCHandle? s = null ---
--- GCHandle u = Helper.Create(default(GCHandle)) ---
--- ByteE? s = Helper.Create(default(ByteE)) ---
--- ByteE? s = null ---
--- ByteE u = Helper.Create(default(ByteE)) ---
--- IntE? s = Helper.Create(default(IntE)) ---
--- IntE? s = null ---
--- IntE u = Helper.Create(default(IntE)) ---
--- LongE? s = Helper.Create(default(LongE)) ---
--- LongE? s = null ---
--- LongE u = Helper.Create(default(LongE)) ---
--- EmptyStruct? s = Helper.Create(default(EmptyStruct)) ---
--- EmptyStruct? s = null ---
--- EmptyStruct u = Helper.Create(default(EmptyStruct)) ---
--- NotEmptyStruct? s = Helper.Create(default(NotEmptyStruct)) ---
--- NotEmptyStruct? s = null ---
--- NotEmptyStruct u = Helper.Create(default(NotEmptyStruct)) ---
--- NotEmptyStructQ? s = Helper.Create(default(NotEmptyStructQ)) ---
--- NotEmptyStructQ? s = null ---
--- NotEmptyStructQ u = Helper.Create(default(NotEmptyStructQ)) ---
--- NotEmptyStructA? s = Helper.Create(default(NotEmptyStructA)) ---
--- NotEmptyStructA? s = null ---
--- NotEmptyStructA u = Helper.Create(default(NotEmptyStructA)) ---
--- NotEmptyStructQA? s = Helper.Create(default(NotEmptyStructQA)) ---
--- NotEmptyStructQA? s = null ---
--- NotEmptyStructQA u = Helper.Create(default(NotEmptyStructQA)) ---
--- EmptyStructGen<int>? s = Helper.Create(default(EmptyStructGen<int>)) ---
--- EmptyStructGen<int>? s = null ---
--- EmptyStructGen<int> u = Helper.Create(default(EmptyStructGen<int>)) ---
--- NotEmptyStructGen<int>? s = Helper.Create(default(NotEmptyStructGen<int>)) ---
--- NotEmptyStructGen<int>? s = null ---
--- NotEmptyStructGen<int> u = Helper.Create(default(NotEmptyStructGen<int>)) ---


Stack trace
   at JIT_Directed._nullabletypes_Desktop_boxunboxvaluetype_ro_boxunboxvaluetype_ro_._nullabletypes_Desktop_boxunboxvaluetype_ro_boxunboxvaluetype_ro_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-10-31T00:09:11.85Z | osx.1200.arm64.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=67446&view=ms.vss-test-web.build-test-results-tab&runId=1373766&resultId=110918&paneView=debug)
2022-10-30T00:34:12.895Z | osx.1200.arm64.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=67178&view=ms.vss-test-web.build-test-results-tab&runId=1368242&resultId=110288&paneView=debug)
2022-09-27T21:28:00.087Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=32186&view=ms.vss-test-web.build-test-results-tab&runId=650398&resultId=100366&paneView=debug)
2022-09-23T06:53:56.591Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545628&resultId=104801&paneView=debug)
2022-09-21T21:30:34.502Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=25335&view=ms.vss-test-web.build-test-results-tab&runId=513594&resultId=100350&paneView=debug)
2022-09-21T06:09:57.685Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493404&resultId=105110&paneView=debug)
2022-09-05T10:07:05.729Z | ubuntu.1804.armarch.open | arm64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=4698&view=ms.vss-test-web.build-test-results-tab&runId=81638&resultId=100872&paneView=debug)

### PR DESCRIPTION
**Pull request by AndyAyersMS**
We cannot safely peephole instructions that straddle a gc enable boundary. Detecting when this might happen is a bit subtle; currently we rely on `emitForceNewIG` to be set.

Add a new utility `emitCannotPeepholeLastIns` to centralize the logic that decides whether basing a peephole opt on `emitLastIns` is safe.

Closes #77661.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib 

One diff on arm64, still running x64 locally but don't expect much there.

File: src/coreclr/jit/emit.h [hunk 1]
```diff
@@ -2180,6 +2180,13 @@ class emitter
 
     instrDesc* emitLastIns;
 
+    // Check if a peephole opt involving emitLastIns is unsafe
+    // emitForceNewIG here prevents peepholes from crossing nogc boundaries.
+    bool emitCannotPeepholeLastIns()
+    {
+        return emitForceNewIG || ((emitCurIGinsCnt == 0) && ((emitCurIG->igFlags & IGF_EXTEND) == 0));
+    }
```
Comment (BruceForstall) [inline src/coreclr/jit/emit.h:2188]: I'm not fond of functions with "Not" in the name, especially when they are later used with `!`. How about `emitPeepholeLastInsIsSafe`? How about also checking `emitLastIns != nullptr` since that is also checked at most of the call sites.

```suggestion
    bool emitPeepholeLastInsIsSafe()
    {
        return (emitLastIns != nullptr) && !emitForceNewIG && ((emitCurIGinsCnt != 0) || ((emitCurIG->igFlags & IGF_EXTEND) != 0));
    }
```

**Review by kunalspathak — APPROVED** [review]
LGTM

File: src/coreclr/jit/emitarm64.cpp [hunk 2]
```diff
@@ -16065,9 +16065,7 @@ bool emitter::IsRedundantMov(instruction ins, emitAttr size, regNumber dst, regN
 bool emitter::IsRedundantLdStr(
     instruction ins, regNumber reg1, regNumber reg2, ssize_t imm, emitAttr size, insFormat fmt)
 {
-    bool isFirstInstrInBlock = (emitCurIGinsCnt == 0) && ((emitCurIG->igFlags & IGF_EXTEND) == 0);
-
-    if (((ins != INS_ldr) && (ins != INS_str)) || (isFirstInstrInBlock) || (emitLastIns == nullptr))
```
Comment (BruceForstall) [inline src/coreclr/jit/emitarm64.cpp:16070]: Why remove `emitLastIns == nullptr`?

**Review by BruceForstall — CHANGES_REQUESTED** [review]
One suggestion, one question. Let me know if you want to leave it as-is.

File: src/coreclr/jit/emitarm64.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/emitarm64.cpp:16070]: Hmm, looks like it was inadvertent. At any rate I will follow your suggestion to check this in the helper; I almost did that initially but was tempted to keep things a bit more minimal in case we wanted to port it back.

File: src/coreclr/jit/emit.h (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/emit.h]: Done.

**Review by BruceForstall — APPROVED** [review]
Looks great.

I do think we should back-port.

**Comment by AndyAyersMS** [comment]
One other thought -- if we had emitted the GC liveness update even though we didn't emit the instruction then the peephole in #77661 would have been ok.

Kind of makes me think that instead of not emitting instructions we should just shrink them to zero size or something similar, But that would have some annoying aspects too (perhaps we could discard them after the gc updates are done).

**Comment by AndyAyersMS** [comment]
Per SPMI, just one arm64 method with [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=77325&view=ms.vss-build-web.run-extensions-tab) -- see https://github.com/dotnet/runtime/issues/77661#issuecomment-1307878094.

**Comment by AndyAyersMS** [comment]
> > One other thought -- if we had emitted the GC liveness update even though we didn't emit the instruction then the peephole in #77661 would have been ok.
> 
> Are you suggesting that an instruction that gets removed by a peephole optimization would still have its GC effect applied? That seems dangerous. It seems like the peephole optimization needs to always do the right thing w.r.t. GC no matter what that might be.

The net effect on GC needs to be the same whether we do the peephole or not. Maybe we can at least sanity check this is true somehow? Say save gc state before, then compare after states with/without peephole, they should match. Probably tricky to pull off.

**Comment by AndyAyersMS** [comment]
FYI I think #77153 is the same bug -- so this may be more widespread than I first thought.

I tracked this down by doing an SPMI collect of the (intermittently failing) libraries run and then running SPMI diffs with and without the fix here.
