### PR TITLE
Arm64: Make unroll code for cpblk non-interruptible

### LINKED ISSUE #68530: Test failure JIT/Directed/VectorABI/VectorMgdMgdStatic_r/VectorMgdMgdStatic_r.sh
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20220423.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1734438&view=ms.vss-test-web.build-test-results-tab&runId=46962418&paneView=debug&resultId=110667)

Failed test:
```
coreclr Linux arm64 Checked gcstress0xc @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/Directed/VectorABI/VectorMgdMgdStatic_r/VectorMgdMgdStatic_r.sh
- JIT/Directed/VectorABI/VectorMgdMgdArray_ro/VectorMgdMgdArray_ro.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.Directed/VectorABI/VectorMgdMgdStatic_r/VectorMgdMgdStatic_r.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false VectorMgdMgdStatic_r.dll ''
testReflectionReturn_HVA64_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v4): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
Test FAILED
Expected: 100
Actual: 0
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/Directed/VectorABI/VectorMgdMgdStatic_r/VectorMgdMgdStatic_r.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._VectorABI_VectorMgdMgdStatic_r_VectorMgdMgdStatic_r_._VectorABI_VectorMgdMgdStatic_r_VectorMgdMgdStatic_r_sh()
```

### PR DESCRIPTION
**Pull request by kunalspathak**
In https://github.com/dotnet/runtime/pull/68085, I relaxed the heuristics under which we would use SIMD registers for copy block unroll code. The code generated uses temporary registers to addresses to copy (could be GC references) and they are not reported. As such, we should mark the unroll code region as GC non-interruptible to make sure GC doesn't kick in and collect the wrong objects.

Note: We were marking `gtBlkOpGcUnsafe` only for situation where destination address was local, but never checked about the source address. This PR expands it to situation when either src/dst addresses are non-local (on heap).

Fixes: https://github.com/dotnet/runtime/issues/68530

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @BruceForstall

**Comment by BruceForstall** [comment]
Related, but not necessary for fixing the bug: genCodeForCpObj() handles unrolling for structs with pointers where the dst address is on the stack. In that case, no write barrier helper is called and we only use ldp/stp, ldr/str sequence. However, we still mark the dst register as a byref for GC, which seems unnecessary.

**Comment by BruceForstall** [comment]
We only unroll for 64 or 128 bytes.

**Comment by BruceForstall** [comment]
> How hard is it to properly report the GC references?

The problem is the unrolling code wants to create a "byref" like pointer that is based on an actual object/byref pointer, but doesn't actually point to or within the object. So we can't report it to the GC because it wouldn't get updated properly.

File: src/coreclr/jit/lowerarmarch.cpp [hunk 1]
```diff
@@ -440,18 +440,10 @@ void Lowering::LowerBlockStore(GenTreeBlk* blkNode)
 
         if (blkNode->OperIs(GT_STORE_OBJ))
         {
-            if (!blkNode->AsObj()->GetLayout()->HasGCPtr())
+            if (!blkNode->AsObj()->GetLayout()->HasGCPtr() || (isDstAddrLocal && (size <= copyBlockUnrollLimit)))
```
Comment (BruceForstall) [inline src/coreclr/jit/lowerarmarch.cpp:443]: This looks like a bug: before, if `(isDstAddrLocal && (size <= copyBlockUnrollLimit))`, we would set gtBlkOpGcUnsafe=true. Now, we won't unless `!isSrcAddrLocal`.

So, if both isSrcAddrLocal and isDstAddrLocal are true, we won't disable GC. However, the thing we are copying contains GC pointers in this case, and the GC pointers loaded into temporary registers aren't reported, so we have a GC hole.

File: src/coreclr/jit/lowerarmarch.cpp [hunk 2]
```diff
@@ -440,18 +440,10 @@ void Lowering::LowerBlockStore(GenTreeBlk* blkNode)
...
             {
                 blkNode->SetOper(GT_STORE_BLK);
             }
-            else if (isDstAddrLocal && (size <= copyBlockUnrollLimit))
```
Comment (BruceForstall) [inline src/coreclr/jit/lowerarmarch.cpp:447]: It seems like we don't need the `isDstAddrLocal` check: why can't we use this code path even if copying with src=heap, dst=heap, or src=stack, dst=heap?

File: src/coreclr/jit/lowerarmarch.cpp [hunk 3]
```diff
@@ -464,6 +456,17 @@ void Lowering::LowerBlockStore(GenTreeBlk* blkNode)
...
             blkNode->gtBlkOpKind = GenTreeBlk::BlkOpKindUnroll;
 
+            if (!isSrcAddrLocal || !isDstAddrLocal)
+            {
+                // If the size is small enough to unroll then we need to mark the block as non-interruptible
+                // to actually allow unrolling. The generated code does not report GC references loaded in the
+                // temporary register(s) used for copying.
+                // Although marking it here would sometime make blkop gcUnsafe for more scenarios than needed,
+                // it will be less complex if marked in genCodeForCpBlkUnroll() for scenarios that generate
+                // code of GC references.
```
Comment (BruceForstall) [inline src/coreclr/jit/lowerarmarch.cpp:466]:
```suggestion
                // If the size is small enough to unroll then we need to mark the block as non-interruptible
                // to actually allow unrolling. The generated code does not report GC references loaded in the
                // temporary register(s) used for copying.
                // Also, under certain conditions when using SIMD registers for copying, arm64 genCodeForCpBlkUnroll()
                // creates pointers into the blocks that should (for non-stack blocks) that can't be reported as BYREFs.
                // Although marking gtBlkOpGcUnsafe here can sometimes make blkop gcUnsafe for more scenarios than needed,
                // it is much less complex than if it was marked in genCodeForCpBlkUnroll().
```

File: src/coreclr/jit/lowerarmarch.cpp [hunk 4]
```diff
@@ -464,6 +456,17 @@ void Lowering::LowerBlockStore(GenTreeBlk* blkNode)
         {
             blkNode->gtBlkOpKind = GenTreeBlk::BlkOpKindUnroll;
 
+            if (!isSrcAddrLocal || !isDstAddrLocal)
```
Comment (BruceForstall) [inline src/coreclr/jit/lowerarmarch.cpp:459]: All these changes are specific to arm64. Shouldn't it be ifdef'ed so it doesn't affect arm32?

**Review by BruceForstall — DISMISSED** [review]

File: src/coreclr/jit/lowerarmarch.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/lowerarmarch.cpp:443]: That's true. I missed that case.

File: src/coreclr/jit/lowerarmarch.cpp (hunk 2 above)
Comment (kunalspathak) [reply src/coreclr/jit/lowerarmarch.cpp:447]: I was trying to consolidate the `blkNode->SetOper(GT_STORE_BLK)` case, but in general, we need to disable GC for following `unroll` cases:
- isDstAddrLocal = true (as of today)
- isDstAddrLocal = false (if dst is on heap)
- isSrcAddrLocal = false (if src is on heap)
- isSrcAddrLocal = true (since we want to disable GC regardless if dst is on stack/heap, src state won't matter).

So basically, if we are doing `GT_STORE_BLK` and unrolling, we need to disable GC. With that said, I think we should disable the GC inside `genCodeForCpBlkUnroll()` only for cases where we will be doing the adjustments i.e. `srcOffsetAdjustment != 0 || dstOffsetAdjustment != 0` to limit it to scenarios that are really affected.

File: src/coreclr/jit/lowerarmarch.cpp (hunk 4 above)
Comment (kunalspathak) [reply src/coreclr/jit/lowerarmarch.cpp:459]: hhm, today `blkNode->gtBlkOpGcUnsafe = true` is marked for both arm/arm64. This PR just extends it to more scenarios?

File: src/coreclr/jit/codegenarmarch.cpp [hunk 5]
```diff
@@ -2948,6 +2959,17 @@ void CodeGen::genCodeForCpBlkUnroll(GenTreeBlk* node)
...
 #endif
 
+#ifndef JIT32_GCENCODER
+    if (!node->gtBlkOpGcUnsafe && ((srcOffsetAdjustment != 0) || (dstOffsetAdjustment != 0)))
+    {
+        // If node is not already marked as non-interruptible, and if are about to generate code
+        // that produce GC references in temporary registers not reported, then mark the block
+        // as non-interruptible.
+        node->gtBlkOpGcUnsafe = true;
+        GetEmitter()->emitDisableGC();
```
Comment (AndyAyersMS) [inline src/coreclr/jit/codegenarmarch.cpp:2969]: Add a note that the corresponding `emitEnableGC()` call will happen in the caller?

**Review by AndyAyersMS — APPROVED** [review]

**Comment by kunalspathak** [comment]
Failure is https://github.com/dotnet/runtime/issues/69136

File: src/coreclr/jit/lowerarmarch.cpp (hunk 2 above)
Comment (kunalspathak) [reply src/coreclr/jit/lowerarmarch.cpp:447]: With that being the case, I missed a case for objects that has GC pointers. Fixed in https://github.com/dotnet/runtime/pull/70053
