### PR TITLE
Fix issue 98506 - Excessive exceptions generated in StackTraceSymbols

### LINKED ISSUE #98506: Excessive exceptions generated in StackTraceSymbols when using Portable PDB
I have discovered a situation when attempting to build and use a portable PDB file which is causing a performance degredation in my application by emitting unneccessary exceptions when collecting stack traces (for exceptions).

https://github.com/dotnet/runtime/blob/bd5f6eb73f6dffe91386f75d3ed5531ddcb2aeb6/src/libraries/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.cs#L66

There is at least one situation where this code can be entered into with a handle of value 0x06000000. That is, technically, a nil token, but with an invalid row ID. In the case I have observed it is because a dynamic method is on the stack and that dynamic method is attached to an existing type from an assembly with an associated portable PDB.

Thus the check in StackTraceSymbols which checks if it's Kind == MethodDef succeeds. The code continues, converts it to a MethodDebugInformation token, and then attempts to look it up from the MetadataReader, which then calls Throw.OutOfBounds. Which causes another exception.

The problem seems to appear all the way back to .NET 6.

### PR DESCRIPTION
**Pull request by mikem8361**
Fixes https://github.com/dotnet/runtime/issues/98506 by checking the token for nil.

### CODE REVIEW

File: src/libraries/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.cs [hunk 1]
```diff
@@ -63,7 +63,7 @@ void IDisposable.Dispose()
             {
                 Handle handle = MetadataTokens.Handle(methodToken);
 
-                if (handle.Kind == HandleKind.MethodDefinition)
+                if (!handle.IsNil && handle.Kind == HandleKind.MethodDefinition)
```
Comment (jkotas) [inline src/libraries/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.cs:66]: We can do this check even before `TryGetReader`. No point in getting the reader if we are not going to use it anyway.

**Review by jkotas — APPROVED** [review]
