### PR TITLE
Arm64: Fix for 96441

### LINKED ISSUE #96441: [ARM64] CINC or CSINC is not emitted for conditional increment
### Description

Creating a separate issue from https://github.com/dotnet/runtime/issues/96380 to track `CINC`/`CSINC` not kicking in place of `CSEL`.

### Analysis

Given method
```cs
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static int RuneLength(in byte value)
{
    var lzcnt = (uint)BitOperations.LeadingZeroCount(~((uint)value << 24));
    if (lzcnt is 0) lzcnt++;

    return (int)lzcnt;
}
```

Currently the following codegen is produced:
```asm
G_M000_IG01:                ;; offset=0x0000
            stp     fp, lr, [sp, #-0x10]!
            mov     fp, sp
 
G_M000_IG02:                ;; offset=0x0008
            ldrb    w0, [x0]
            lsl     w0, w0, #24
            mvn     w0, w0
            clz     w0, w0
            mov     w1, #1
            cmp     w0, #0
            csel    w0, w0, w1, ne ;; <-- Could have been just cinc with mov 1 elided - we're incrementing zero
 
G_M000_IG03:                ;; offset=0x0024
            ldp     fp, lr, [sp], #0x10
            ret     lr
 
; Total bytes of code 44
```

The `mov, cmp, csel` sequence can be produced in a more optimal way - `cmp, cinc`.

### Configuration
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100/
 ```

### Regression?

No

### PR DESCRIPTION
**Pull request by dhartglassMSFT**
The increment of `lzcnt`  (`*`) wasn't getting transformed to a conditional increment, because an earlier phase folds the "add local, 1" into a constant based on assertion information.

```
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static int RuneLength(in byte value)
{
    var lzcnt = (uint)BitOperations.LeadingZeroCount(~((uint)value << 24));
    if (lzcnt is 0) lzcnt++; //*

    return (int)lzcnt;
}
```

Fix to allow `TryLowerCnsIntCselToCinc` to look cases similar to `if (myvar==0)myvar=1;`

fixes #96441

### CODE REVIEW

File: src/coreclr/jit/lowerarmarch.cpp [hunk 1]
```diff
@@ -3466,56 +3467,128 @@ void Lowering::TryLowerCnsIntCselToCinc(GenTreeOp* select, GenTree* cond)
...
+            return;
+        }
+        if ((!cond->gtGetOp1()->IsIntegralConst() && !cond->gtGetOp2()->IsIntegralConst()) ||
+            (!cond->gtGetOp1()->OperIs(GT_LCL_VAR) && !cond->gtGetOp2()->OperIs(GT_LCL_VAR)))
+        {
+            return;
+        }
+
+        // One of the CMP operands is a constant int
+        auto     code     = select->AsOpCC()->gtCondition.GetCode();
```
Comment (jakobbotsch) [inline src/coreclr/jit/lowerarmarch.cpp]: We generally don't use `auto` except for unspeakable types (like lambdas)

**Review by jakobbotsch — APPROVED** [review]
LGTM! I will kick off Fuzzlyn which is good at testing stuff like this (it may have failures in it unrelated to this PR)
