### PR TITLE
Fix XUnit Log Fixer Irregularities

### LINKED ISSUE #84940: XUnit log fixer creates invalid XML when fixing the xml after a timed out test
Platform: **Windows arm checked**
Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=241282&view=ms.vss-test-web.build-test-results-tab&runId=4637564&resultId=122180&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
Failing test: **Directed_1**

Diagnostics:

<pre>
...
END EXECUTION - PASSED
PASSED
Test Harness Exitcode is : 0
To run the test:
Set up CORE_ROOT and run.
> C:\h\w\A9F7091C\w\9FAC08C6\e\JIT\Directed\Directed_1\../callconv/ThisCall/EmptyThisCallTest/EmptyThisCallTest.cmd
10:48:09.033 Passed test: JIT/Directed/callconv/ThisCall/EmptyThisCallTest/EmptyThisCallTest.cmd
10:48:09.036 Running test: JIT/Directed/debugging/debuginfo/tester/tester.cmd

cmdLine:C:\h\w\A9F7091C\w\9FAC08C6\e\JIT\Directed\Directed_1\../debugging/debuginfo/tester/tester.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 4/17/2023 10:48:09 AM, end: 4/17/2023 11:18:09 AM)

Return code:      -100
Raw output file:      C:\h\w\A9F7091C\w\9FAC08C6\uploads\debugging\debuginfo\tester\output.txt
Raw output:

cmdLine:C:\h\w\A9F7091C\w\9FAC08C6\e\JIT\Directed\Directed_1\../debugging/debuginfo/tester/tester.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 4/17/2023 10:48:09 AM, end: 4/17/2023 11:18:09 AM)
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.
> C:\h\w\A9F7091C\w\9FAC08C6\e\JIT\Directed\Directed_1\../debugging/debuginfo/tester/tester.cmd
11:18:09.123 Failed test: JIT/Directed/debugging/debuginfo/tester/tester.cmd
11:18:09.123 Running test: JIT/Directed/forceinlining/AttributeConflict/AttributeConflict.cmd
11:18:09.207 Failed test: JIT/Directed/forceinlining/AttributeConflict/AttributeConflict.cmd
11:18:09.208 Running test: JIT/Directed/forceinlining/PositiveCases/PositiveCases.cmd
11:18:09.274 Failed test: JIT/Directed/forceinlining/PositiveCases/PositiveCases.cmd
11:18:09.275 Running test: JIT/Directed/IL/PInvokeTail/PInvokeTail/PInvokeTail.cmd
Unhandled exception. 
   Cannot print exception string because Exception.ToString() failed.
App Exit Code: -1073741819
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
[XUnitLogChecker]: Item 'Directed_1' did not finish running. Checking and fixing the log...
[XUnitLogChecker]: XUnit log file has been fixed!

106/128 tests run.
* 93 tests passed.
* 4 tests failed.
* 9 tests skipped.

[XUnitLogChecker]: Checking for dumps...
Unhandled exception. System.Xml.XmlException: The 'assembly' start tag on line 1 position 2 does not match the end tag of 'stack'. Line 267, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at XUnitLogChecker.PrintStackTracesFromDumps(String dumpsPath, String tempLogPath) in D:\a\_work\1\s\src\tests\Common\XUnitLogChecker\XUnitLogChecker.cs:line 396
   at XUnitLogChecker.Main(String[] args) in D:\a\_work\1\s\src\tests\Common\XUnitLogChecker\XUnitLogChecker.cs:line 153
ERROR: The process "corerun.exe" not found.
2023-04-17T11:18:40.639Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2023-04-17T11:18:40.639Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\A9F7091C\w\9FAC08C6\e' for test results files
2023-04-17T11:18:40.670Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\A9F7091C\w\9FAC08C6\uploads' for test results files
2023-04-17T11:18:40.670Z	WARNING	run.py	__init__(55)	read_results	No results file found in any of the following formats: xunit, junit, trx
2023-04-17T11:18:40.670Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 0 test reports to 'C:\h\w\A9F7091C\w\9FAC08C6\e\__test_report.json'
2023-04-17T11:18:40.670Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 1539 bytes
['Directed_1' END OF WORK ITEM LOG: Command exited with -532462766]
</pre>

/cc @ivdiazsa @jkoritzinsky @dotnet/runtime-infrastructure

### LINKED ISSUE #85056: Test failures not reported in test run
I found a case where a test failure is not reported in the CoreCLR test run.

See the log file here:

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-abd91328c2f94763aa/HardwareIntrinsics_General_ro/1/console.b75ffbb8.log?helixlogtype=result

This is the console log for the HardwareIntrinsics_General_ro test run for win-x64 pri-1 outerloop run

https://dev.azure.com/dnceng-public/public/_build/results?buildId=243871&view=logs&j=bc936583-455b-59a6-ba6a-b6595d929238&t=deb3df3a-0bd3-5b15-90c9-d170d4bd5993

specifically, for `DOTNET_TieredCompilation=0`

Note the bottom of the log file:
```
11:03:55.549 Running test: _Vector512_1_ro::JIT.HardwareIntrinsics.General._Vector512_1.Program.GetAndWithLowerAndUpperByte()
Beginning scenario: RunBasicScenario
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at JIT.HardwareIntrinsics.General._Vector512_1.VectorGetAndWithLowerAndUpper__GetAndWithLowerAndUpperByte.RunBasicScenario()
   at JIT.HardwareIntrinsics.General._Vector512_1.Program.GetAndWithLowerAndUpperByte()
   at Program.<<Main>$>g__TestExecutor26|0_25(System.IO.StreamWriter, System.IO.StreamWriter, <>c__DisplayClass0_0 ByRef)
   at Program.<Main>$(System.String[])
App Exit Code: -1073741795
Expected: 100
Actual: -1073741795
END EXECUTION - FAILED
FAILED
[XUnitLogChecker]: Item 'HardwareIntrinsics_General_ro' did not finish running. Checking and fixing the log...
[XUnitLogChecker]: XUnit log file has been fixed!

1259/2363 tests run.
* 1259 tests passed.
* 0 tests failed.
* 0 tests skipped.

[XUnitLogChecker]: Checking for dumps...
[XUnitLogChecker]: No crash dumps found. Continuing...
[XUnitLogChecker]: Finished!
ERROR: The process "corerun.exe" not found.
2023-04-19T11:03:58.485Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2023-04-19T11:03:58.485Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\B51E0A11\w\AD88096E\e' for test results files
2023-04-19T11:03:58.485Z	INFO   	run.py	__init__(48)	read_results	Found results file C:\h\w\B51E0A11\w\AD88096E\e\JIT\HardwareIntrinsics\HardwareIntrinsics_General_ro\HardwareIntrinsics_General_ro.testResults.xml with format xunit
2023-04-19T11:03:58.501Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\B51E0A11\w\AD88096E\uploads' for test results files
2023-04-19T11:03:58.501Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 1259 test reports to 'C:\h\w\B51E0A11\w\AD88096E\e\__test_report.json'
2023-04-19T11:03:58.501Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 281920 bytes
['HardwareIntrinsics_General_ro' END OF WORK ITEM LOG: Command exited with 0]
```

The test crashed, the exit code was non-100, and the wrapper script reported FAILED.

Then, XUnitLogChecker comes along, fixes the log, prints out that only a subset of the expected tests were run, and returns success. Thus, the work item is marked as succeeding, and AzDO UI does not show it as a failure.

Found when investigating https://github.com/dotnet/runtime/issues/84967

@ivdiazsa @trylek 
cc @hoyosjs

### PR DESCRIPTION
**Pull request by ivdiazsa**
Fixes #84940 and #85056. This PR addresses some irregularities with the XUnit Log Fixer that were causing some CI runs to not give the appropriate result.

- _84940_: The log fixer was creating invalid XML's because of a problem with the `<stack-trace>` tag. It did not know tags could also have hyphens as part of their label. The regex in charge of this was adjusted accordingly, and now it recognizes all of them seamlessly.
- _85056_: Some CI failures were being reported as passed because of how app exit return codes are handled in Helix. The last run command is the one that determines that specific test's status. Since now the final command is the log fixer, then this overshadowed the exit status of the test. In other words, if the test failed but the log fixer ran well, then it was treated as passed. The log fixer was adjusted to return the test's exit code, rather than one of its own, in order to preserve the status of that specific CI test.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by trylek — APPROVED** [review]
LGTM, thanks Ivan for fixing this! I'm not sure about the HW intrinsics failures on arm, they don't seem related to your change but they might be worth retrying or checking other recent PR runs to see whether they're ambient or somehow indirectly caused by the slightly changed test execution logic.

File: src/tests/Common/XUnitLogChecker/XUnitLogChecker.cs [hunk 1]
```diff
@@ -97,7 +104,7 @@ static int Main(string[] args)
         {
             Console.WriteLine("[XUnitLogChecker]: An error occurred. No stats csv"
                             + $" was found. The expected name would be '{statsCsvPath}'.");
-            return FAILURE;
+            return TestExitCode;
```
Comment (BruceForstall) [inline src/tests/Common/XUnitLogChecker/XUnitLogChecker.cs:107]: Is it possible for the test to return success, but the XUnitLogChecker to fail (i.e., places where it previously returned `FAILURE` before this PR)? In that case, should the CI consider that a failure? Or do you want various XUnitLogChecker failures to be ignored by the CI? If you want XUnitLogChecker failures to be shown as a CI failure, then the `return FAILURE` cases here should be preserved.

**Review by BruceForstall — APPROVED** [review]
One comment/question

File: src/tests/Common/XUnitLogChecker/XUnitLogChecker.cs (hunk 1 above)
Comment (trylek) [reply src/tests/Common/XUnitLogChecker/XUnitLogChecker.cs:107]: Thanks Bruce, that's a reasonable suggestion; in practice I think most of these special cases only occur when the test crashes halfway through and then it also returns an error exit code but I believe your suggestion is a general goodness for robustness of the infra.

File: src/tests/Common/helixpublishwitharcade.proj [hunk 2]
```diff
@@ -405,8 +405,8 @@
       <XUnitLogCheckerHelixPath>$(XUnitLogCheckerHelixPath)XUnitLogChecker/</XUnitLogCheckerHelixPath>
 
       <XUnitLogCheckerArgs>$(_MergedWrapperRunScriptDirectoryRelative) $(_MergedWrapperName)</XUnitLogCheckerArgs>
-      <XUnitLogCheckerArgs Condition="'$(TestWrapperTargetsWindows)' != 'true'">$(XUnitLogCheckerArgs) %24HELIX_DUMP_FOLDER</XUnitLogCheckerArgs>
-      <XUnitLogCheckerArgs Condition="'$(TestWrapperTargetsWindows)' == 'true'">$(XUnitLogCheckerArgs) %25HELIX_DUMP_FOLDER%25</XUnitLogCheckerArgs>
+      <XUnitLogCheckerArgs Condition="'$(TestWrapperTargetsWindows)' != 'true'">$(XUnitLogCheckerArgs) %24%3F %24HELIX_DUMP_FOLDER</XUnitLogCheckerArgs>
```
Comment (hoyosjs) [inline src/tests/Common/helixpublishwitharcade.proj:408]: Would this better be in the helix command? As in save the result, not pass it in, and then exit with that if non-zero or with the fixer's exit otherwise?

**Review by hoyosjs — COMMENTED** [review]
Suggestion that may decouple the fixer.

File: src/tests/Common/helixpublishwitharcade.proj (hunk 2 above)
Comment (BruceForstall) [reply src/tests/Common/helixpublishwitharcade.proj:408]: I agree with this. Something like:
```
// run test
set _saved_errorlevel=%errorlevel%
// run XunitLogChecker
if %errorlevel% NEQ 0 exit 1
if %_saved_errorlevel% NEQ 0 exit 1
exit 0
```
?

It's unfortunate that building a script in this helixpublishwitharcade.proj is comically complex.

File: src/tests/Common/XUnitLogChecker/XUnitLogChecker.cs (hunk 1 above)
Comment (ivdiazsa) [reply src/tests/Common/XUnitLogChecker/XUnitLogChecker.cs:107]: This sounds like a reasonable suggestion to me, combined with Juan's in the next comment. I'll implement it.

File: src/tests/Common/helixpublishwitharcade.proj (hunk 2 above)
Comment (BruceForstall) [reply src/tests/Common/helixpublishwitharcade.proj:408]: Makes sense to me.

Another question is whether we should preferentially return the test failing code, which would require saving the XUnitLogChecker code:
```
# Run test
test_exit_code=$?
# Run XUnitLogChecker
xunitlogchecker_exit_code=$?
# If the test failed, return that exit code
if [ $test_exit_code -ne 0 ]; then exit $test_exit_code; fi
if [ $xunitlogchecker_exit_code -ne 0 ]; then exit $xunitlogchecker_exit_code; fi
exit 0
```

Comment (ivdiazsa) [reply src/tests/Common/helixpublishwitharcade.proj:408]: I think this is the best way to proceed. Thanks for your observations Bruce.

**Comment by tannergooding** [comment]
There's some failures due to missing logs from test assemblies that are skipped for a given platform.

There's also some x86/x64 hwintrinsic failures that should all be resolved in https://github.com/dotnet/runtime/pull/85281.

**Review by BruceForstall — APPROVED** [review]
I like how it looks now.

One more question:

In https://github.com/dotnet/runtime/issues/85056, I see:
```
1259/2363 tests run.
* 1259 tests passed.
* 0 tests failed.
* 0 tests skipped.
```

If I see those numbers, passed + failed + skipped doesn't add up to tests run. Should that be considered a failure, and if so, should the XUnitLogChecker return an error code in that case? (Perhaps the test already did or should have returned an error code in that case?)

**Comment by ivdiazsa** [comment]
> I like how it looks now.
> 
> One more question:
> 
> In #85056, I see:
> 
> ```
> 1259/2363 tests run.
> * 1259 tests passed.
> * 0 tests failed.
> * 0 tests skipped.
> ```
> 
> If I see those numbers, passed + failed + skipped doesn't add up to tests run. Should that be considered a failure, and if so, should the XUnitLogChecker return an error code in that case? (Perhaps the test already did or should have returned an error code in that case?)

Oh this might need some addressing, considering you're bringing up the question. The log checker here is just reporting the status until the crash. When the test process was terminated, 1259 tests had passed, and no others had been skipped or failed gracefully. Maybe we could add in a subsequent PR a fourth field called "tests missing"? We could have the log checker subtract passed+failed+skipped from the total expected for a more complete report.

**Comment by tannergooding** [comment]
If you pull in latest main, then the x64 hwIntrinsic tests should now pass.

You may still have to handle the other case I called out above of. That is, the `HardwareIntrinsics_Arm_r` tests are skipped on x64 and inversely the `HardwareIntrinsics_X86_r` tests are skipped on Arm64. CI was failing saying logs are missing, when they are intentionally "missing" due to the project being skipped.

**Comment by da748** [comment]
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ivdiazsa** [comment]
> If you pull in latest main, then the x64 hwIntrinsic tests should now pass.
> 
> You may still have to handle the other case I called out above of. That is, the `HardwareIntrinsics_Arm_r` tests are skipped on x64 and inversely the `HardwareIntrinsics_X86_r` tests are skipped on Arm64. CI was failing saying logs are missing, when they are intentionally "missing" due to the project being skipped.

Thanks Tanner. I will pull the latest main changes and be on the lookout for the other potential issue.

**Comment by BruceForstall** [comment]
@tannergooding The logs are now seeing, e.g.:

```
C:\h\w\9C720908\w\B4460A48\e>call JIT\HardwareIntrinsics\HardwareIntrinsics_Arm_r\HardwareIntrinsics_Arm_r.cmd -usewatcher 
'JIT\HardwareIntrinsics\HardwareIntrinsics_Arm_r\HardwareIntrinsics_Arm_r.cmd' is not recognized as an internal or external command,
operable program or batch file.

C:\h\w\9C720908\w\B4460A48\e>set test_exit_code=1 

C:\h\w\9C720908\w\B4460A48\e>dotnet C:\h\w\9C720908\p/XUnitLogChecker/XUnitLogChecker.dll JIT\HardwareIntrinsics\HardwareIntrinsics_Arm_r HardwareIntrinsics_Arm_r C:\cores 
[XUnitLogChecker]: No logs were found. This work item was skipped.
[XUnitLogChecker]: If this is a mistake, then something went very wrong. The expected temp log name would be: 'HardwareIntrinsics_Arm_r.tempLog.xml'

C:\h\w\9C720908\w\B4460A48\e>set xunitlogchecker_exit_code=0 
```

So the XunitLogFixer changes in this PR appear to be working correctly. However, presumably these failures were masked/hidden before, and now they are exposed. It doesn't appear to be the job of the XUnitLogFixer to fix this problem.

How should this get fixed? Someone is trying to execute a .cmd file that doesn't exist, and is actually *expected* to not exist (in this case).

**Comment by BruceForstall** [comment]
@trylek @markples In the example above, why do we create a Helix job for a merged test .cmd file that doesn't exist?

**Comment by trylek** [comment]
This might be due to a corner case where we don't know in advance that all tests in a particular merged wrapped will end up getting skipped e.g. due to their incompatiblity with GC stress or a given targeting architecture. Overall I would expect these cases to be rare and not particularly sensitive w.r.t. Helix performance. At the very least we should fix them so that they don't cause such spurious errors, ideally we should avoid sending them to Helix altogether (albeit I doubt it's generally doable in the presence of tests requiring process isolation as the merged wrapper logic simply has no way to know what the execution script contains).

**Comment by trylek** [comment]
On second thought, the corner case I described shouldn't manifest as a missing merged test execution script (cmd / sh) so I guess there must be something else at work here.

**Comment by markples** [comment]
Conjecture - we produce the marker files (.MergedTestAssembly / .MergedTestAsembly.x.y.MergedTestAssemblyForStress) because the build is AnyCPU/etc, but then we produce the .cmd files in a build on the actual test target, and since _Arm is architecture-specific (we have conditional GCStressIncompatible and CLRTestTargetUnsupported on the merged group itself) it does not generate a .cmd but at this point we're already in the helix job that will have nothing more to do.

**Comment by trylek** [comment]
Thanks Mark, that sounds very reasonable. If that's indeed the case, we should be able to easily filter these out somewhere around

https://github.com/dotnet/runtime/blob/2802c972f7352c1bad068d5c247a675e8618c230/src/tests/Common/helixpublishwitharcade.proj#L360

by detecting that we don't have the equivalent execution scripts.

**Comment by ivdiazsa** [comment]
> Thanks Mark, that sounds very reasonable. If that's indeed the case, we should be able to easily filter these out somewhere around
> 
> https://github.com/dotnet/runtime/blob/2802c972f7352c1bad068d5c247a675e8618c230/src/tests/Common/helixpublishwitharcade.proj#L360
> 
> by detecting that we don't have the equivalent execution scripts.

Am I right in assuming this gets executed at some point after the _sh/cmd_ scripts have been generated? If yes, then it might not be too difficult to address in a follow-up PR.

**Comment by BruceForstall** [comment]
I think the failure of missing .cmd files needs to be fixed before this PR can merge, or else there will be lots of Pri-0/outerloop test failures.

**Comment by ivdiazsa** [comment]
On second thought, it might not be that good if merging this would break all those legs while we fix that other problem. What are your thoughts everyone?

**Comment by ivdiazsa** [comment]
> I think the failure of missing .cmd files needs to be fixed before this PR can merge, or else there will be lots of Pri-0/outerloop test failures.

Sounds reasonable to me. Let me know if you or someone in your team will do that Bruce. If not, then I can take on that work item.

**Comment by trylek** [comment]
My initial impression is that this should be a one-line change in the script <code>helixpublishwitharcade.proj</code>, basically going over the <code>_MergedWrapperMarker</code> item group and removing those items that don't have the matching <code>cmd / sh</code> in the same folder. It's getting late around here but I think I should be able to put up the PR for the fix tomorrow.

**Comment by markples** [comment]
I wrote "but then we produce all .cmd files in separate builds on the actual test targets", but I can't find when this actually happens.  In run-test-job, there are 3 `script:` sections before sending to helix.  "Generate test wrappers" is the obvious one, but I only see evidence of the old (not merged group) wrappers.  I don't see (for example) the .cmd for JIT\Regression_1 in any of those logs or in the helix log.  I also don't see the .cmd in the managed build (AnyCPU/AnyOS), as expected.

(Please don't let me distract you from an actual fix here, which I think you'll be able to do much faster than me, as I'm not completely following this part of the discussion.  Thanks for your help!)

**Comment by trylek** [comment]
I believe that from the Helix viewpoint the merged test wrappers are just ordinary runtime tests so that the logic for generating their own cmd / sh execution scripts should mostly follow the normal logic around <code>CLRTest.Execute.Bash/Batch.targets</code>. In general we're indeed producing all test execution scripts in the test run job (IIRC it happens as part of copying the native test components to the test output tree) but that doesn't automatically mean that the merged test wrapper script is aware of all the details in the component scripts for out-of-process tests.

**Comment by ivdiazsa** [comment]
> My initial impression is that this should be a one-line change in the script `helixpublishwitharcade.proj`, basically going over the `_MergedWrapperMarker` item group and removing those items that don't have the matching `cmd / sh` in the same folder. It's getting late around here but I think I should be able to put up the PR for the fix tomorrow.

Thanks a lot for your help Tomas! Let me know if there's anything you need my help with.

**Comment by BruceForstall** [comment]
@ivdiazsa Can you merge in https://github.com/dotnet/runtime/pull/85476 and re-test this?

**Comment by BruceForstall** [comment]
Test run looks (basically) clean
