### PR TITLE
ML-KEM: Fix-up ASN.1 reading and writing logic

### LINKED ISSUE #115063: Wrong exception thrown by MLKem.ImportPkcs8PrivateKey for a too-small buffer
`CryptographicException` should be thrown when `MLKem.ImportPkcs8PrivateKey` is called with an input buffer that is shorter than expected, but `AsnContentException` is thrown instead.

```csharp
[Fact]
public static void ArgumentValidation_MalformedAsnEncoding()
{
    // Generate a valid ASN.1 encoding
    AsnWriter writer = new AsnWriter(AsnEncodingRules.BER);
    writer.WriteOctetString("some data"u8);
    byte[] encodedBytes = writer.Encode();
    int encodedLength = encodedBytes.Length;

    // Add a trailing byte
    Array.Resize(ref encodedBytes, encodedLength + 1);
    Assert.Throws<CryptographicException>(() => MLKem.ImportPkcs8PrivateKey(encodedBytes));

    // Remove the last byte so the length indicated in the encoding will be larger than the actual data.
    Array.Resize(ref encodedBytes, encodedLength - 1);
    Assert.Throws<CryptographicException>(() => MLKem.ImportPkcs8PrivateKey(encodedBytes)); // <-- FAILS
}
```

Error is thrown from: https://github.com/dotnet/runtime/blob/32463ba7daff98330c8bc550280c6dc26538de08/src/libraries/Common/src/System/Security/Cryptography/MLKem.cs#L1746

Test Failure:
```
      System.Security.Cryptography.Tests.MLKemTests.ArgumentValidation_MalformedAsnEncoding [FAIL]
        Assert.Throws() Failure: Exception type was not an exact match
        Expected: typeof(System.Security.Cryptography.CryptographicException)
        Actual:   typeof(System.Formats.Asn1.AsnContentException)
        ---- System.Formats.Asn1.AsnContentException : The encoded length exceeds the number of bytes remaining in the input buffer.
        Stack Trace:
          /mnt/d/git/runtime-base2/src/libraries/Common/tests/System/Security/Cryptography/MLKemTests.cs(824,0): at System.Security.Cryptography.Tests.MLKemTests.ArgumentValidation_MalformedAsnEncoding()
             at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
             at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
          /mnt/d/git/runtime-base2/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs(1159,0): at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
          /mnt/d/git/runtime-base2/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs(36,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
          /mnt/d/git/runtime-base2/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
          ----- Inner Stack Trace -----
          /mnt/d/git/runtime-base2/src/libraries/System.Formats.Asn1/src/System/Formats/Asn1/AsnDecoder.cs(172,0): at System.Formats.Asn1.AsnDecoder.ReadEncodedValue(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& contentOffset, Int32& contentLength, Int32& bytesConsumed)
          /mnt/d/git/runtime-base2/src/libraries/Common/src/System/Security/Cryptography/MLKem.cs(1746,0): at System.Security.Cryptography.MLKem.ThrowIfTrailingData(ReadOnlySpan`1 data)
          /mnt/d/git/runtime-base2/src/libraries/Common/src/System/Security/Cryptography/MLKem.cs(1239,0): at System.Security.Cryptography.MLKem.ImportPkcs8PrivateKey(ReadOnlySpan`1 source)
          /mnt/d/git/runtime-base2/src/libraries/Common/src/System/Security/Cryptography/MLKem.cs(1254,0): at System.Security.Cryptography.MLKem.ImportPkcs8PrivateKey(Byte[] source)
          /mnt/d/git/runtime-base2/src/libraries/Common/tests/System/Security/Cryptography/MLKemTests.cs(824,0): at System.Security.Cryptography.Tests.MLKemTests.<>c__DisplayClass62_0.<ArgumentValidation_MalformedAsnEncoding>b__1()
```

### PR DESCRIPTION
**Pull request by vcsjones**
This has a couple of improvements to how MLKem interacts with SubjectPublicKeyInfo and PrivateKeyInfo.

* Thrown exceptions are improved, either by throwing the right exception or not including irrelevant inner exceptions.
* The trailing data check will now account for improperly encoded ASN.1
* Improved handling when derived types have an incorrectly implemented `TryExportPkcs8PrivateKeyCore`

Fixes #115063

### CODE REVIEW

File: src/libraries/Common/src/System/Security/Cryptography/MLKem.cs [hunk 1]
```diff
@@ -1801,32 +1815,26 @@ private TResult ExportPkcs8PrivateKeyCallback<TResult>(ExportPkcs8PrivateKeyFunc
...
 
-            if (written > buffer.Length)
+            if (written < 0 || written > buffer.Length)
             {
                 // We got a nonsense value written back. Clear the buffer, but don't put it back in the pool.
                 CryptographicOperations.ZeroMemory(buffer);
                 throw new CryptographicException();
             }
 
             TResult result = func(buffer.AsSpan(0, written));
```
Comment (PranavSenthilnathan) [inline src/libraries/Common/src/System/Security/Cryptography/MLKem.cs:1835]: Should this invocation be guarded by a `try..catch`?

File: src/libraries/Common/src/System/Security/Cryptography/MLKem.cs [hunk 2]
```diff
@@ -1801,32 +1815,26 @@ private TResult ExportPkcs8PrivateKeyCallback<TResult>(ExportPkcs8PrivateKeyFunc
...
             while (!TryExportPkcs8PrivateKeyCore(buffer, out written))
             {
-                ClearAndReturnToPool(buffer, written);
+                CryptoPool.Return(buffer);
                 size = checked(size * 2);
                 buffer = ArrayPool<byte>.Shared.Rent(size);
             }
 
-            if (written > buffer.Length)
+            if (written < 0 || written > buffer.Length)
```
Comment (PranavSenthilnathan) [inline src/libraries/Common/src/System/Security/Cryptography/MLKem.cs:1828]: Is `if ((uint)written > buffer.Length)` avoided here for readability?

Comment (vcsjones) [reply src/libraries/Common/src/System/Security/Cryptography/MLKem.cs:1828]: Yeah, I don't really care for things like that until we are on some kind of hot path, and importing PKCS#8 is not a hot path. Idiomatic code seems better here, to me at least.

File: src/libraries/Common/src/System/Security/Cryptography/MLKem.cs (hunk 1 above)
Comment (vcsjones) [reply src/libraries/Common/src/System/Security/Cryptography/MLKem.cs:1835]: `func` is going to either be

1. `static pkcs8 => PemEncoding.WriteString(PemLabels.Pkcs8PrivateKey, pkcs8)`
2. `static pkcs8 => pkcs8.ToArray()`

I don't really expect writing a PEM or `ToArray` to ever throw.

File: src/libraries/Common/tests/System/Security/Cryptography/MLKemTests.cs [hunk 3]
```diff
@@ -453,7 +469,14 @@ public static void ImportPkcs8PrivateKey_Both_TrailingData()
             }
         }
 
-       [Fact]
+        [Fact]
+        public static void ImportPkcs8PrivateKey_NotAsn()
+        {
+            Assert.Throws<CryptographicException>(() => MLKem.ImportPkcs8PrivateKey("potatoes"u8));
+            Assert.Throws<CryptographicException>(() => MLKem.ImportPkcs8PrivateKey("potatoes"u8.ToArray()));
```
Comment (bartonjs) [inline src/libraries/Common/tests/System/Security/Cryptography/MLKemTests.cs:476]: I don't see a test of "trim off the last byte, might require 768 or 512 because of preconditions", but I guess it's "make ReadEncodedValue throw", which this does.

Do these actually trigger that?  Or do they hit a minimum size precondition?

Comment (vcsjones) [reply src/libraries/Common/tests/System/Security/Cryptography/MLKemTests.cs:476]: There is no minimum size pre-condition for PKCS#8 imports on ML-KEM, only on export destination buffers. We can add one, but it seemed a bit unnecessary, and we don't do it on existing algorithms.

**Comment by bartonjs** [comment]
ICYMI:

```
  Discovering: Microsoft.Bcl.Cryptography.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Bcl.Cryptography.Tests (found 360 of 481 test cases)
  Starting:    Microsoft.Bcl.Cryptography.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.Security.Cryptography.Tests.MLKemNotSupportedTests.ImportSubjectPublicKeyInfo_NotSupported [FAIL]
      Assert.Throws() Failure: Exception type was not an exact match
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   typeof(System.Security.Cryptography.CryptographicException)
      ---- System.Security.Cryptography.CryptographicException : ASN1 corrupted data.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Security/Cryptography/MLKemNotSupportedTests.cs(35,0): at System.Security.Cryptography.Tests.MLKemNotSupportedTests.ImportSubjectPublicKeyInfo_NotSupported()
           at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
           at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
        /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs(1159,0): at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs(36,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/src/System/Security/Cryptography/MLKem.cs(1764,0): at System.Security.Cryptography.MLKem.ThrowIfTrailingData(ReadOnlySpan`1 data)
        /_/src/libraries/Common/src/System/Security/Cryptography/MLKem.cs(1173,0): at System.Security.Cryptography.MLKem.ImportSubjectPublicKeyInfo(ReadOnlySpan`1 source)
        /_/src/libraries/Common/src/System/Security/Cryptography/MLKem.cs(1205,0): at System.Security.Cryptography.MLKem.ImportSubjectPublicKeyInfo(Byte[] source)
        /_/src/libraries/Common/tests/System/Security/Cryptography/MLKemNotSupportedTests.cs(36,0): at System.Security.Cryptography.Tests.MLKemNotSupportedTests.<>c.<ImportSubjectPublicKeyInfo_NotSupported>b__4_0()
    System.Security.Cryptography.Tests.AesGcmIsSupportedTests.CtorThrowsPNSEIfNotSupported [SKIP]
      Condition(s) not met: "RuntimeSaysIsNotSupported"
  Finished:    Microsoft.Bcl.Cryptography.Tests
```

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
runtime-ci run is here: https://github.com/vcsjones/runtime-ci/actions/runs/14720877862/job/41314348123

Only commit since that green run was a merge commit.
