### PR TITLE
Move type check to after the null ref branch in out marshalling of blittable classes.

### LINKED ISSUE #50841: [6.0.100-preview.4.21206.10][main branch] LibGit2Sharp System.NullReferenceException at git_diff_find_similar native method
**Application Name:**  LibGit2Sharp (https://github.com/libgit2/libgit2sharp)
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-preview.4.21206.10
**Affected Application:** git-istage global tool app (GlobalToolsNETCore21Part01)
https://github.com/terrajobst/git-istage

**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build  6.0.100-preview.4.21206.1 - **main branch: Fail**
2). Windows 10 RS5 X64 + .NET Core SDK build  6.0.100-preview.3.21202.5 - **Preview 3 branch: Pass**
3). Windows 10 RS5 X64 + .NET Core SDK build 5.0.104 : Pass

**DevDiv bug:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1307298

**Repro steps to run**
1) Create a .net core console app
2) Add `<PackageReference Include="LibGit2Sharp" Version="0.26.2" />`
3) In Program.cs
```
var _repository = new Repository(@".git folder path in the project");
var tipTree = _repository.Head.Tip?.Tree;
var comp = _repository.Diff.Compare<TreeChanges>(tipTree, DiffTargets.Index);  //exception here
Console.WriteLine(comp.Count); //changes count
```
 
**Expected Result:**
Should return the number of staged changes

**Actual Result:**
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at LibGit2Sharp.Core.NativeMethods.git_diff_find_similar(git_diff* diff, GitDiffFindOptions options)
   at LibGit2Sharp.Core.Proxy.git_diff_find_similar(DiffHandle diff, GitDiffFindOptions options)
   at LibGit2Sharp.Diff.DetectRenames(DiffHandle diffList, CompareOptions compareOptions)
   at LibGit2Sharp.Diff.BuildDiffList(ObjectId oldTreeId, ObjectId newTreeId, TreeComparisonHandleRetriever comparisonHandleRetriever, DiffModifiers diffOptions, IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOptions, CompareOptions compareOptions)
   at LibGit2Sharp.Diff.Compare[T](Tree oldTree, DiffTargets diffTargets, IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOptions, CompareOptions compareOptions)
   at LibGit2Sharp.Diff.Compare[T](Tree oldTree, DiffTargets diffTargets)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\v-altunc\source\repos\ConsoleApp12\ConsoleApp1\Program.cs:line 14
```

@dotnet-actwx-bot  @dotnet/compat

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes the case of marshalling a `null` blittable class instance from native to managed.

Fixes https://github.com/dotnet/runtime/issues/50841

### CODE REVIEW

File: src/coreclr/vm/ilmarshalers.cpp [hunk 1]
```diff
@@ -2466,12 +2466,12 @@ void ILBlittablePtrMarshaler::EmitConvertContentsNativeToCLR(ILCodeStream* pslIL
...
     int fieldDef = pslILEmit->GetToken(CoreLibBinder::GetField(FIELD__RAW_DATA__DATA));
 
-    ILCodeLabel* isNotMatchingTypeLabel = pslILEmit->NewCodeLabel();
-    bool emittedTypeCheck = EmitExactTypeCheck(pslILEmit, isNotMatchingTypeLabel);
-
     EmitLoadManagedValue(pslILEmit);
     pslILEmit->EmitBRFALSE(pNullRefLabel);
 
+    ILCodeLabel* isNotMatchingTypeLabel = pslILEmit->NewCodeLabel();
+    bool emittedTypeCheck = EmitExactTypeCheck(pslILEmit, isNotMatchingTypeLabel);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/ilmarshalers.cpp:2473]: I think there were other locations for the original change. Why is this one the only one that is impacted?

Comment (jkoritzinsky) [reply src/coreclr/vm/ilmarshalers.cpp:2473]: This is the only one I forgot to put after the null check instead of before.

File: src/tests/Interop/LayoutClass/LayoutClassTest.cs [hunk 2]
```diff
@@ -134,6 +134,9 @@ class StructureTests
         [DllImport("LayoutClassNative")]
         private static extern bool SimpleExpLayoutClassByRef(ExpClass p);
 
+        [DllImport("LayoutClassNative")]
+        private static extern bool SimpleBlittableSeqLayoutClass_Null(Blittable p);
```
Comment (elinor-fung) [inline src/tests/Interop/LayoutClass/LayoutClassTest.cs:138]: Should we add one for the non-blittable case too?

Comment (jkoritzinsky) [reply src/tests/Interop/LayoutClass/LayoutClassTest.cs:138]: I'll add one for completeness and regression testing.

File: src/tests/Interop/LayoutClass/LayoutClassTest.cs [hunk 3]
```diff
@@ -128,12 +128,18 @@ class StructureTests
         [DllImport("LayoutClassNative")]
         private static extern bool SimpleSeqLayoutClassByRef(SeqClass p);
 
+        [DllImport("LayoutClassNative")]
+        private static extern bool SimpleSeqLayoutClassByRefNull([In, Out] Blittable p);
```
Comment (elinor-fung) [inline src/tests/Interop/LayoutClass/LayoutClassTest.cs:132]: `SeqClass` instead of `Blittable`?

Comment (jkoritzinsky) [reply src/tests/Interop/LayoutClass/LayoutClassTest.cs:132]:
```suggestion
        private static extern bool SimpleSeqLayoutClassByRefNull([In, Out] SeqClass p);
```

**Review by elinor-fung — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
The build legs that are stuck in pending are due to an infrastructure issue. Merging this in.
