### PR TITLE
Consolidate System.Private.Xml test projects

### LINKED ISSUE #75456: Consolidate System.Private.Xml tests into a single csproj
System.Private.Xml currently has 27 different test projects!  It makes it near impossible to determine whether some change has appropriate test coverage.  With the exception of the trimming tests, we should consolidate them all into a single test project.

### PR DESCRIPTION
**Pull request by stephentoub**
We currently have almost 30 test projects underneath System.Private.Xml\tests in various levels of nested directories.  This makes it challenging to appropriately run all of the System.Private.Xml tests when making any changes to anything in S.P.Xml, and it makes it all but impossible to get meaningful code coverage information, which in turns significantly lowers our confidence about any changes being made to the library.

This PR consolidates almost all of them into a single System.Private.Xml.Tests projects.  It is a mostly mechanical change, adding all of the relevant files to the single .csproj and deleting the individual csproj files.  In some cases I added more specific namespaces to deal with conflicts.  In others multiple projects were including the same files containing [Facts] and parameterizing them via statics that were supplied by individual files built only into the relevant projects; I fixed those by making the [Fact]s into [Theory]s and passing in all the relevant state.  I also had to fix up some cases where tests were mutating global state that then conflicted with other tests.

```
    Discovering: System.Private.Xml.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Private.Xml.Tests (found 4734 of 4785 test cases)
    Starting:    System.Private.Xml.Tests (parallel test collections = on, max threads = 12)
    Finished:    System.Private.Xml.Tests
  === TEST EXECUTION SUMMARY ===
     System.Private.Xml.Tests  Total: 23714, Errors: 0, Failed: 0, Skipped: 0, Time: 64.213s
```

This explicitly does not:
- Clean up any test code beyond the minimal necessary to get this to compile.  Many of these tests are old and crusty and worthy of a complete rewrite, but I restrained myself.
- Move or rename any files around.
- Try to enable parallelization of the tests.  That’d be good to do at some point to help with test execution time, but I didn’t want to change any tests beyond what was necessary.

I did run the fixer to remove unnecessary usings, as I’d added some usings as part of mechanically fixing this without paying attention to whether they were necessary or not.

There are just two test projects that remain separate: one for trimming, and one for serialization that runs some of the same tests but with a different compilation constant set for its build.

Fixes https://github.com/dotnet/runtime/issues/75456

Resulting code coverage is now measurable but not great:

```
+--------------------+--------+--------+--------+
| Module             | Line   | Branch | Method |
+--------------------+--------+--------+--------+
| System.Private.Xml | 52.68% | 43.27% | 60.92% |
+--------------------+--------+--------+--------+
```

### CODE REVIEW

**Comment by danmoseley** [comment]
> Try to enable parallelization of the tests. 

Is the default xunit parallelization disabled?

**Comment by stephentoub** [comment]
> Is the default xunit parallelization disabled?

Yes

**Comment by danmoseley** [comment]
Is this going to increase end to end test time then, as previously each library would potentially run concurrently with the others?

**Comment by stephentoub** [comment]
> Is this going to increase end to end test time then, as previously each library would potentially run concurrently with the others?

Considering the significant overhead associated with running a test suite in CI, I highly doubt it.

File: src/libraries/Common/tests/System/Xml/XPath/Common/Utils.cs [hunk 1]
```diff
@@ -1,32 +1,50 @@
...
 using System.Xml.XPath;
+using Xunit;
 
 namespace XPathTests.Common
 {
     public static partial class Utils
     {
-        public static XPathNavigator CreateNavigatorFromFile(string fileName)
+        private static readonly ICreateNavigator s_xmlDocumentNavigatorCreator = new CreateNavigatorFromXmlDocument();
+        private static readonly ICreateNavigator s_xmlReaderNavigatorCreator = new CreateNavigatorFromXmlReader();
```
Comment (krwq) [inline src/libraries/Common/tests/System/Xml/XPath/Common/Utils.cs:15]: I can't remember exactly this code anymore but I think there were 3 XPath implementations being tested here:
- XPathDocument
- XmlDocument.CreateNavigator() (aka XmlDocumentXPathNavigator)
- XPathNavigator created from XmlReader

but I'm seeing only 2 being tested here

File: src/libraries/System.Private.Xml/tests/XPath/XPathDocument/System.Xml.XPath.Tests.csproj [hunk 2]
```diff
@@ -1,196 +0,0 @@
-<Project Sdk="Microsoft.NET.Sdk">
```
Comment (krwq) [inline src/libraries/System.Private.Xml/tests/XPath/XPathDocument/System.Xml.XPath.Tests.csproj:1]: note there were previously 3 csproj files testing different implementations of XPath with some subtle differences, now we only have two kinds. I cannot remember exactly what the differences were but I do remember those tests actually found a bunch of different issues and removing one kind might reduce coverage significantly (I might remember incorrectly, it's been couple of years since I touched this)

**Review by krwq — APPROVED** [review]
Please verify that there are actually 2 kinds of XPath implementation and not 3. Other than that looks good to me.

Thanks a lot for this cleanup - this has been a giant pain point.

File: src/libraries/System.Private.Xml/tests/XPath/XPathDocument/System.Xml.XPath.Tests.csproj (hunk 2 above)
Comment (stephentoub) [reply src/libraries/System.Private.Xml/tests/XPath/XPathDocument/System.Xml.XPath.Tests.csproj:1]: what 3 csproj says you referring to?

**Comment by eiriktsarpalis** [comment]
> > Is the default xunit parallelization disabled?
> 
> Yes. A bunch of the tests change process-wide state, e.g. setting various AppContext switches.

How many tests do this? Would it be feasible to use RemoteExecutor for those in a later change?

**Comment by stephentoub** [comment]
> Would it be feasible to use RemoteExecutor for those in a later change?

Yup.

**Review by krwq — APPROVED** [review]
I just double checked the old code - seems I misremembered and it looks good as is. Thanks again!

File: src/libraries/System.Private.Xml/tests/XPath/XPathDocument/System.Xml.XPath.Tests.csproj (hunk 2 above)
Comment (krwq) [reply src/libraries/System.Private.Xml/tests/XPath/XPathDocument/System.Xml.XPath.Tests.csproj:1]: Bad memory I guess, just validated and there are in fact 2
