### PR TITLE
JIT: Fix case where we illegally optimize away a memory barrier on ARM32

### LINKED ISSUE #91732: Test failure: System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking "Inconsistent LargeStruct: 1 1 1 1 1 1 0 0"
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=398160
Build error leg or test failing: System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1)
Pull request: https://github.com/dotnet/runtime/pull/91663

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Exception : Inconsistent LargeStruct: ",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```scala
+ grep DOTNET
DOTNET_EnableCrashReport=1
DOTNET_TieredCompilation=1
DOTNET_JitStress=1
DOTNET_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
DOTNET_DbgEnableMiniDump=1
+ ./RunTests.sh --runtime-path /root/helix/work/correlation
----- start Thu Sep 7 11:03:23 UTC 2023 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Collections.Concurrent.Tests.runtimeconfig.json --depsfile System.Collections.Concurrent.Tests.deps.json xunit.console.dll System.Collections.Concurrent.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Collections.Concurrent.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Concurrent.Tests (found 897 of 905 test cases)
  Starting:    System.Collections.Concurrent.Tests (parallel test collections = on, max threads = 2)
    System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1) [FAIL]
      System.Exception : Inconsistent LargeStruct: 1 1 1 1 1 1 0 0
      Stack Trace:
        /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs(1030,0): at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.LargeStruct.get_Value()
        /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs(871,0): at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.<>c__DisplayClass52_0.<ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking>b__1()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2399,0): at System.Threading.Tasks.Task.InnerInvoke()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(179,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(203,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2345,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs(1013,0): at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.WaitAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs(876,0): at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(Double seconds)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(155,0): at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
  Finished:    System.Collections.Concurrent.Tests
=== TEST EXECUTION SUMMARY ===
   System.Collections.Concurrent.Tests  Total: 2406, Errors: 0, Failed: 1, Skipped: 0, Time: 35.091s
/root/helix/work/workitem/e
----- end Thu Sep 7 11:04:03 UTC 2023 ----- exit code 1 ----------------------------------------------------------
```

I can take an initial look, this could be physical promotion related.

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=398160
**Error message validated:** `System.Exception : Inconsistent LargeStruct: `
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/7/2023 2:12:29 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[401000](https://dev.azure.com/dnceng-public/public/_build/results?buildId=401000)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=401000&view=ms.vss-test-web.build-test-results-tab&runId=8663440&resultId=151314)||
|[399429](https://dev.azure.com/dnceng-public/public/_build/results?buildId=399429)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=399429&view=ms.vss-test-web.build-test-results-tab&runId=8623226&resultId=143378)||
|[398160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=398160)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=398160&view=ms.vss-test-web.build-test-results-tab&runId=8596634&resultId=141139)|dotnet/runtime#91663|
|[398021](https://dev.azure.com/dnceng-public/public/_build/results?buildId=398021)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=398021&view=ms.vss-test-web.build-test-results-tab&runId=8590130&resultId=139822)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|4|4|

### PR DESCRIPTION
**Pull request by jakobbotsch**
The ARM32/ARM64 backends have an optimization where they optimize out the latter of two subsequent memory barriers if no memory store/load has been seen between them. This optimization did not take calls into account, allowing the removal of a memory barrier even if a call (with potential memory operations) had happened since the last one.

Fix #91732

The problem happened in `ConcurrentQueueSegment<LargeStruct>.TryEnqueue` in this code:

https://github.com/dotnet/runtime/blob/e0a81708fd4f7f57ad85c3d4cffcc3752e5d4046/src/libraries/System.Private.CoreLib/src/System/Collections/Concurrent/ConcurrentQueueSegment.cs#L293-L300

The block copy was turned into a helper call to `CORINFO_HELP_MEMCPY`. Then the JIT effectively turned the `Volatile.Write` into a plain write without any memory barrier. The diff with this PR is:

```diff
@@ -1,42 +1,42 @@
 G_M50486_IG05:  ;; offset=0x0042
 ldr     r6, [r4+0x94]
 dmb     15
 ldr     r0, [r4+0x0C]
 and     r7, r0, r6
 ldr     r0, [r5+0x04]
 cmp     r7, r0
 bhs     SHORT G_M50486_IG07
 movs    r0, 72
 mul     r0, r7, r0
 adds    r0, 8
 ldr     r0, [r5+r0]
 dmb     15
 sub     r8, r0, r6
 cmp     r8, 0
 bne     SHORT G_M50486_IG06
 add     r0, r4, 148
 adds    r1, r6, 1
 mov     r2, r6
 movw    r3, 0x221
 movt    r3, 0xf732
 blx     r3		// System.Threading.Interlocked:CompareExchange(byref,int,int):int
 cmp     r0, r6
 bne     SHORT G_M50486_IG05
 movs    r2, 72
 mul     r2, r7, r2
 adds    r2, 8
 adds    r2, r5, r2
 add     r0, r2, 8
 add     r1, sp, 40
 movs    r2, 64
 movw    r12, 0x565f
 movt    r12, 0xf749
 blx     r12		// CORINFO_HELP_MEMCPY
 movs    r0, 72
 mul     r0, r7, r0
 adds    r0, 8
 adds    r3, r6, 1
+dmb     15
 str     r3, [r5+r0]
 movs    r0, 1
 b       SHORT G_M50486_IG03
```

### CODE REVIEW

File: src/coreclr/jit/emitarm64.cpp [hunk 1]
```diff
@@ -8908,6 +8908,7 @@ void emitter::emitIns_Call(EmitCallType          callType,
 
     dispIns(id);
     appendToCurIG(id);
+    emitLastMemBarrier = nullptr; // Cannot optimize away future memory barriers
```
Comment (jakobbotsch) [inline src/coreclr/jit/emitarm64.cpp:8911]: I think this entire peephole should be switched to use the new backwards traversal peephole mechanism, which I expect would have quite significant TP improvements as we currently have code in very hot `appendToCurIG` to handle this peephole. I've opened #91825 for that. However, given that this PR should be backported I've kept the fix here surgical.

**Review by EgorBo — APPROVED** [review]

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

Significant number of [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=400408&view=ms.vss-build-web.run-extensions-tab) on ARM32. No diffs on ARM64, presumably (as @EgorBo told me) because we use combined memory barrier and memory operations there now.

**Comment by jakobbotsch** [comment]
Failure is #91838
