### PR TITLE
Fix tailcall regression with compiled F#

### LINKED ISSUE #40864: tailcall regression with compiled F#
Machine:
Latest Windows 10 x64

Pre-verification:

1. On a clean machine install latest VS with the following workloads:
   - **.NET desktop development**
      - Add optional component **F# desktop language support**
   - **.NET Core cross-platform development**
2. Clone `https://github.com/dotnet/fsharp` and reset to commit 1c1b5ac7eacbbfd79e7277982e15178cecee20b4
3. Build with `.\Build.cmd -c Release`
4. Run test with `dotnet test tests\fsharp\FSharpSuite.Tests.fsproj --no-restore --no-build --filter LargeRecordDoesNotStackOverflow -f netcoreapp3.1 -c Release -v n`

At this point the test should pass.

Bug repro:

5. Install latest .NET 5 SDK from [here](https://dotnet.microsoft.com/download/visual-studio-sdks).
6. Invalidate the .NET 3 SDK and runtime by doing the following:
   - Rename/delete `C:\Program Files\dotnet\sdk\3.1.401`
   - Rename/delete `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7`
   - Ensure they're not listed via `dotnet --list-sdks` and `dotnet --list-runtimes`
7. Re-run the test from step (4) exactly as above.
   N.b., you may need to alter `global.json` with the following:
   ``` diff
    {
   +  "sdk": {
   +    "version": "5.0.100-preview.7.20366.6"
   +   },
      "tools": {
   -    "dotnet": "3.1.302",
   +    "dotnet": "5.0.100-preview.7.20366.6",
    ...
   ```

Result:
Stack overflow

Possibly related to #40581

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #40864

### CODE REVIEW

File: src/coreclr/src/vm/jitinterface.cpp [hunk 1]
```diff
@@ -13952,7 +13952,7 @@ bool CEEInfo::getTailCallHelpersInternal(CORINFO_RESOLVED_TOKEN* callToken,
 
     TailCallHelp::CreateTailCallHelperStubs(
         m_pMethodBeingCompiled, pTargetMD,
-        msig, isCallvirt, isThisArgByRef,
+        msig, isCallvirt, isThisArgByRef, sig->hasTypeArg(),
```
[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/src/vm/jitinterface.cpp:13955]: I have seen cases where `pTargetMD->RequiresInstArg()` did not match `sig->hasTypeArg()`. For example, `pTargetMD` is transformed above, but there are other places where it can get out of sync.

`sig->hasTypeArg()` is guaranteed to match what the JIT is going to do.

File: src/coreclr/src/vm/tailcallhelp.cpp [hunk 2]
```diff
@@ -194,6 +188,12 @@ void TailCallHelp::LayOutArgBuffer(
         addValue(thisHnd);
     }
 
+    if (hasInstArg)
+    {
+        layout->HasInstArg = true;
+        addValue(TypeHandle(CoreLibBinder::GetElementType(ELEMENT_TYPE_I)));
+    }
```
[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/src/vm/tailcallhelp.cpp:197]: Fixed

File: src/coreclr/src/vm/tailcallhelp.cpp [hunk 3]
```diff
@@ -163,9 +157,9 @@ void TailCallHelp::CreateTailCallHelperStubs(
 
 void TailCallHelp::LayOutArgBuffer(
     MetaSig& callSiteSig, MethodDesc* calleeMD,
-    bool storeTarget, bool thisArgByRef, ArgBufferLayout* layout)
+    bool storeTarget, bool thisArgByRef, bool hasInstArg, ArgBufferLayout* layout)
 {
-    unsigned int offs = 0;
+    unsigned int offs = offsetof(TailCallArgBuffer, Args);
```
Comment (jakobbotsch) [inline src/coreclr/src/vm/tailcallhelp.cpp:162]: The size is assigned from this offset (at the end of the function), so the size is a bit overapproximated now.

Comment (jkotas) [reply src/coreclr/src/vm/tailcallhelp.cpp:162]: Good catch. Fixed.

**Comment by jkotas** [comment]
@dotnet/jit-contrib This is blocked on #41059. Ready for review otherwise.

**Review by jakobbotsch — APPROVED** [review]
LGTM. Nice to see the optimizations also, that should remove a function call from the hot path.

**Comment by erozenfeld** [comment]
@jkotas #41059 has been merged.

**Review by AndyAyersMS — APPROVED** [review]
Changes LGTM.

Should we also make updates to the [design doc](https://github.com/dotnet/runtime/blob/master/docs/design/features/tailcalls-with-helpers.md)?

**Comment by jkotas** [comment]
> design doc

I have read the design doc and I believe everything in the doc is still accurate. I like that the design doc is focused on the concept and it does not go into explaining every detail.

Let me know if there is a specific fact that you would like to see captured.

File: src/coreclr/src/vm/tailcallhelp.cpp [hunk 4]
```diff
@@ -447,42 +476,31 @@ MethodDesc* TailCallHelp::CreateCallTargetStub(const TailCallInfo& info)
...
 
-    // RuntimeHelpers.FreeTailCallArgBuffer();
-    pCode->EmitCALL(METHOD__RUNTIME_HELPERS__FREE_TAILCALL_ARG_BUFFER, 0, 0);
-
-    // *pTailCallAwareRetAddr = NextCallReturnAddress();
-    pCode->EmitLDARG(ARG_PTR_TAILCALL_AWARE_RET_ADDR);
-    pCode->EmitCALL(METHOD__STUBHELPERS__NEXT_CALL_RETURN_ADDRESS, 0, 1);
+    // All arguments are loaded on the stack, it is safe to disable the GC reporting of ArgBuffer now.
+    // This is optimization to avoid extending argument lifetime unnecessarily.
+    // We still need to report the inst argument of shared generic code to prevent it from being unloaded. The inst
```
Comment (jkotas) [inline src/coreclr/src/vm/tailcallhelp.cpp:499]: FYI: In theory, I have noticed that nothing guarantees that the tailcall target function pointer is kept alive and maybe unloaded. It would be a very corner-case situation that is unlikely to be ever hit in a real-world. I have opened #41314 on it.

**Comment by erozenfeld** [comment]
@jkotas I recommend also running **runtime-coreclr libraries-jitstress**.
