### PR TITLE
[mono][wasm] Force interpreter to initialize the pointers

### LINKED ISSUE #95087: [mono][wasm] Add interpreter support for calls to UnmanagedCallersOnly EntryPoint without managed delegate reference
https://github.com/dotnet/runtime/pull/94615#issuecomment-1813789511

#94615 added EntryPoint support to UCO on wasm (it was missing before)
```csharp
 
        [UnmanagedCallersOnly(EntryPoint = "display_meaning")]
        public static void DisplayMeaningExport(int meaning)
        {
            Console.WriteLine($"The meaning of life is {meaning}");
        }
```
but there is currently an issue with when invoking the export from unmanaged when there is no managed delegate pointing to it and something akin to the following workaround is required:

```csharp
   Intptr workaround = (IntPtr)(delegate* unmanaged<int,void>)&display_meaning;  // needs to be in method loaded by interp prior to unmanaged call 
```

This is because `get_native_to_interp` must be called before attempting to invoke the unmanaged entry point or the call will fail.  Without the call `wasm_native_to_interp_ftndescs` is never initialized.  For the workaround to work the delegate * does not need to be reached/reachable, the interpreter simply needs to resolve the method prior to calling it from unmanaged.

### PR DESCRIPTION
**Pull request by mkhamoyan**
Fixes https://github.com/dotnet/runtime/issues/95087

### CODE REVIEW

File: src/mono/browser/runtime/runtime.c [hunk 1]
```diff
@@ -356,3 +357,25 @@ mono_wasm_assembly_find_method (MonoClass *klass, const char *name, int argument
...
+ * Creates a wrapper for a function pointer to a method marked with
+ * UnamangedCallersOnlyAttribute.
+ * This wrapper ensures that the interpreter initializes the pointers.
+ */
+void
+mono_wasm_marshal_get_managed_wrapper (const char* assemblyName, const char* nspace, const char* typeName, const char* methodName, int num_params)
+{
+	MonoError error;
+	mono_error_init (&error);
+    MonoAssembly* assembly = mono_wasm_assembly_load (assemblyName);
```
Comment (pavelsavara) [inline src/mono/browser/runtime/runtime.c:372]: This would force loading all assemblies with any [UCO], which means we also need to make them loaded before runtime start in https://github.com/dotnet/runtime/pull/100141, right ? 

Or could we have this UCO initialization postponed until user code executes ?

cc @maraf

Comment (lewing) [reply src/mono/browser/runtime/runtime.c]: This will only be called when the uco method is called and the wrapper func has not been initialized

File: src/mono/browser/runtime/runtime.c [hunk 2]
```diff
@@ -356,3 +357,25 @@ mono_wasm_assembly_find_method (MonoClass *klass, const char *name, int argument
...
+ * This wrapper ensures that the interpreter initializes the pointers.
+ */
+void
+mono_wasm_marshal_get_managed_wrapper (const char* assemblyName, const char* nspace, const char* typeName, const char* methodName, int num_params)
+{
+	MonoError error;
+	mono_error_init (&error);
+	MonoAssembly* assembly = mono_wasm_assembly_load (assemblyName);
+	assert (assembly);
+	MonoClass* class = mono_wasm_assembly_find_class (assembly, nspace, typeName);
```
Comment (pavelsavara) [inline src/mono/browser/runtime/runtime.c:374]: Is the reflection here in conflict with our (Native)AOT goals ?

**Review by lewing — COMMENTED** [review]
It would probably a good idea to remove the workaround from the native sample and add add a proper test for this.

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs [hunk 3]
```diff
@@ -323,6 +323,13 @@ private void EmitNativeToInterp(StreamWriter w, List<PInvokeCallback> callbacks)
         // Only blittable parameter/return types are supposed.
         int cb_index = 0;
 
+        w.WriteLine("#include <mono/utils/details/mono-error-types.h>\n" +
+                    "#include <mono/metadata/assembly.h>\n" +
+                    "#include <mono/utils/mono-error.h>\n" +
+                    "#include <mono/metadata/object.h>\n" +
+                    "#include <mono/utils/details/mono-logger-types.h>\n" +
+                    "#include \"runtime.h\"\n");
```
Comment (lewing) [inline src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:331]:
```suggestion
        w.Write("""#include <mono/utils/details/mono-error-types.h>
                   #include <mono/metadata/assembly.h>
                   #include <mono/utils/mono-error.h>
                   #include <mono/metadata/object.h>
                    #include <mono/utils/details/mono-logger-types.h>
                    #include "runtime.h"
                    """
```

File: src/mono/browser/runtime/runtime.c (hunk 2 above)
Comment (lewing) [reply src/mono/browser/runtime/runtime.c:374]: > Is the reflection here in conflict with our (Native)AOT goals ?

This is an interpreter issue, the code in question already works in NativeAOT

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs (hunk 3 above)
Comment (mkhamoyan) [reply src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs]: thanks,updated.

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs [hunk 4]
```diff
@@ -371,7 +379,16 @@ private void EmitNativeToInterp(StreamWriter w, List<PInvokeCallback> callbacks)
...
 
-            //sb.Append($"  printf(\"{entry_name} called\\n\");\n");
+            // In case when null force interpreter to initialize the pointers
+            sb.Append($"  if (!(WasmInterpEntrySig_{cb_index})wasm_native_to_interp_ftndescs [{cb_index}].func) {{\n");
+            var assemblyFullName = cb.Method.DeclaringType == null ? "" : cb.Method.DeclaringType.Assembly.FullName;
+            var assemblyName = assemblyFullName != null && assemblyFullName.Split(',').Length > 0 ? assemblyFullName.Split(',')[0].Trim() : "";
+            var typeName = cb.Method.DeclaringType == null  || cb.Method.DeclaringType.FullName == null ? "" : cb.Method.DeclaringType.FullName;
+            var methodName = cb.Method.Name;
+            int numParams = method.GetParameters().Length;
+            sb.Append($"   mono_wasm_marshal_get_managed_wrapper (\"{assemblyName}\", \"{string.Empty}\", \"{typeName}\", \"{methodName}\", {numParams});\n");
```
Comment (lewing) [inline src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:389]: Since we own both sides here is there any reason we need to pass the namespace as separate item given we're passing the fullname?

**Comment by lewing** [comment]
This passes locally so let's get it asap once we have a test.

**Review by lewing — APPROVED** [review]

File: src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs (hunk 4 above)
Comment (mkhamoyan) [reply src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs]: No there is no need, removed it.

File: src/mono/wasi/Wasi.Build.Tests/PInvokeTableGeneratorTests.cs [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+        buildArgs = ExpandBuildArgs(buildArgs);
+        AddItemsPropertiesToProject("<NativeFileReference Include=\"local.c\" />");
+        AddItemsPropertiesToProject(projectFile, "<WasmSingleFileBundle>true</WasmSingleFileBundle>");
+
+        BuildProject(buildArgs,
+                    id: id,
+                    new BuildProjectOptions(
+                        InitProject: () =>
+                        {
+                            File.WriteAllText(Path.Combine(_projectDir!, "Program.cs"), code);
```
Comment (mkhamoyan) [inline src/mono/wasi/Wasi.Build.Tests/PInvokeTableGeneratorTests.cs:64]: Not sure why, but this line doesn't overwrite Program.cs.

Comment (maraf) [reply src/mono/wasi/Wasi.Build.Tests/PInvokeTableGeneratorTests.cs:64]: It's execution is guarded by `options.CreateProject` https://github.com/dotnet/runtime/blob/71e989d1b5641024655800cbae43f62895544692/src/mono/wasi/Wasi.Build.Tests/BuildTestBase.cs#L208

It's value should be true by default, so it should be executed. Anyway I think we don't want `CreateProject=true`, because the project is already created by `CreateWasmTemplateProject`. So I would just override `Program.cs` before running `BuildProject`

**Review by maraf — APPROVED** [review]
Looks good to me 👍
