### PR TITLE
Fixing compressed singlefile scenario on osx-arm64

### LINKED ISSUE #79470: Host tests fail to restore on osx-arm64
I am trying to build host tests, after successfully building clr, libs, host(with no tests), packs, ...,   building the tests part fails.

Is there something that needs to be done to make it work, or host tests are essentially broken on on a contributor's machine for osx-arm64 ?   

How does the lab build/run the tests?

```
./build.sh clr+libs -rc Checked -lc Release <=== OK
./build.sh host.native+host.tools+host.pkg -rc Checked -lc Release <=== OK
./build.sh packs -rc Checked -lc Release  <== OK
./build.sh host.tests -rc Checked -lc Release -test  <=== FAIL
```

```
Build FAILED.

/usr/local/share/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(135,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'osx-arm64'. [/Users/vs/Hosting01/runtime/src/installer/tests/Assets/TestProjects/StandaloneApp3x/StandaloneApp3x.csproj::TargetFramework=netcoreapp3.0]
/usr/local/share/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(135,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'osx-arm64'. [/Users/vs/Hosting01/runtime/src/installer/tests/Assets/TestProjects/StandaloneApp3x/StandaloneApp3x.csproj::TargetFramework=netcoreapp3.0]
/usr/local/share/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(135,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'osx-arm64'. [/Users/vs/Hosting01/runtime/src/installer/tests/Assets/TestProjects/StandaloneApp3x/StandaloneApp3x.csproj::TargetFramework=netcoreapp3.0]
/usr/local/share/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(135,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'osx-arm64'. [/Users/vs/Hosting01/runtime/src/installer/tests/Assets/TestProjects/StandaloneApp3x/StandaloneApp3x.csproj::TargetFramework=netcoreapp3.0]
/Users/vs/Hosting01/runtime/src/installer/tests/PrepareTestAssets/PrepareTestAssets.proj(123,5): error MSB4181: The "MSBuild" task returned false but did not log an error.
    0 Warning(s)
    5 Error(s)
```

### PR DESCRIPTION
**Pull request by VSadov**
Re: https://github.com/dotnet/runtime/issues/79267

Also fixes host tests so they can restore/run on osx-arm64
Fixes: #79470

### CODE REVIEW

File: src/coreclr/vm/peimagelayout.cpp [hunk 1]
```diff
@@ -775,10 +775,15 @@ void* FlatImageLayout::LoadImageByCopyingParts(SIZE_T* m_imageParts) const
     }
 #endif // FEATURE_ENABLE_NO_ADDRESS_SPACE_RANDOMIZATION
 
+    DWORD allocationType = MEM_RESERVE | MEM_COMMIT;
+#if defined(__APPLE__) && defined(HOST_ARM64)
+    allocationType |= MEM_RESERVE_EXECUTABLE;
```
Comment (janvorli) [inline src/coreclr/vm/peimagelayout.cpp:780]: I would do this for `HOST_UNIX` in general like we do in the `ExecutableAllocator::Reserve`.

Comment (janvorli) [reply src/coreclr/vm/peimagelayout.cpp:780]: That would cause that memory to be taken from the pre-reserved block in PAL that is close to the libcoreclr.so.

Comment (VSadov) [reply src/coreclr/vm/peimagelayout.cpp:780]: Will it help R2R code in the same way as JITed code (making it closer to coreclr and avoiding stubs) ?

Comment (VSadov) [reply src/coreclr/vm/peimagelayout.cpp:783]: Did not see you've answered this already.

**Comment by VSadov** [comment]
I do not think by default CI will run host tests with `osx-arm64`. 
I am not sure if/how it can be forced.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by am11** [comment]
> I do not think by default CI will run installer test leg with `osx-arm64`.

I think currently we don't run installer tests on any arm64, which we can (should?) change by adding arm64 here: https://github.com/dotnet/runtime/blob/cd599ec05c24630043196a646418244850edbbc4/eng/pipelines/installer/jobs/build-job.yml#L91

**Comment by VSadov** [comment]
Thanks!!

**Comment by elinor-fung** [comment]
> should we just remove this archType condition instead?

We probably could, but unfortunately, I don't think that would actually let the CI run installer tests on arm64. The installer tests currently run directly on the build machine, so they are disabled when cross-building. I think we'd need to get them running with Helix (and also wouldn't be surprised if they have issues on win-arm64 right now) - related: https://github.com/dotnet/runtime/issues/77800.

**Comment by lewing** [comment]
is this a candidate for servicing?

**Comment by VSadov** [comment]
@lewing - yes, but I think we also need to fix tests.

**Comment by VSadov** [comment]
@elinor-fung - I actually tried to enable installer tests on osx-arm64 tests in https://github.com/dotnet/runtime/pull/80198 

The tests did run, but there are failures. More failures that I would expect. 
I think we should look into failures and enable the tests.

**Comment by elinor-fung** [comment]
I think that is because the tests are running directly on the build machine. I believe the build machine is x64, so trying to run the arm64 host fails. Looking at some of the failures, they fail trying to start the process with `Bad CPU type in executable`.

**Comment by VSadov** [comment]
Oh, that would explain the issues. I did not realize we build on x64.

We really need to fix the test issue, but it looks harder than I thought.

**Comment by am11** [comment]
With today's daily build, the uncompressed single-file is also failing to load embedded libSystem.Native.dylib and trying to locate the library on disk with single-file app on M1. (which was working with December 2022 build https://github.com/dotnet/runtime/discussions/79229#discussioncomment-4319611)

```sh
$ uname -m
arm64

$ dotnet8 --version
8.0.100-alpha.1.23055.16

$ dotnet8 publish -o publish -p:PublishSingleFile=true -c Release
MSBuild version 17.5.0-preview-23054-02+762ae6c6b for .NET
  Determining projects to restore...
  Restored /Users/am11/projects/helloworldapp/helloworldapp.csproj (in 51 ms).
/Users/am11/.dotnet8/sdk/8.0.100-alpha.1.23055.16/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/am11/projects/helloworldapp/helloworldapp.csproj]
  helloworldapp -> /Users/am11/projects/helloworldapp/bin/Release/net8.0/osx-arm64/helloworldapp.dll
  helloworldapp -> /Users/am11/projects/helloworldapp/publish/

$ strings publish/helloworldapp | grep '@(#)'
@(#)Version 8.0.23.5418 @Commit: a2243718922e85370f137bdfa3e30a8eedebe954

$ publish/helloworldapp 
Error message: Unable to load shared library 'libSystem.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Users/am11/projects/helloworldapp/publish/libSystem.Native.dylib, 0x0001): tried: '/Users/am11/projects/helloworldapp/publish/libSystem.Native.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/am11/projects/helloworldapp/publish/libSystem.Native.dylib' (no such file), '/Users/am11/projects/helloworldapp/publish/libSystem.Native.dylib' (no such file)
dlopen(libSystem.Native.dylib, 0x0001): tried: 'libSystem.Native.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibSystem.Native.dylib' (no such file), '/usr/lib/libSystem.Native.dylib' (no such file, not in dyld cache), 'libSystem.Native.dylib' (no such file), '/usr/local/lib/libSystem.Native.dylib' (no such file), '/usr/lib/libSystem.Native.dylib' (no such file, not in dyld cache)
dlopen(/Users/am11/projects/helloworldapp
Failed to create CoreCLR, HRESULT: 0x80131524
```

```sh
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001001e2ef4 p`(anonymous namespace)::LoadLibErrorTracker::Throw(SString&)
    frame #1: 0x00000001001e315c p`NativeLibrary::LoadLibraryByName(char16_t const*, Assembly*, int, unsigned int, int) + 288
    frame #2: 0x000000010008b5b0 p`CorHost2::CreateAppDomainWithManager(char16_t const*, unsigned int, char16_t const*, char16_t const*, int, char16_t const**, char16_t const**, unsigned int*) + 1344
    frame #3: 0x000000010056d3f8 p`coreclr_initialize + 872
    frame #4: 0x0000000100021528 p`coreclr_t::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, char const*, coreclr_property_bag_t const&, std::__1::unique_ptr<coreclr_t, std::__1::default_delete<coreclr_t> >&) + 420
    frame #5: 0x0000000100038210 p`(anonymous namespace)::create_coreclr() + 432
```

**Comment by janvorli** [comment]
@am11 this sounds like a problem with my coreclr initialization failure logging additions. The change added attempt to load libSystem.Native during coreclr initialization to make sure it is present and valid. It is compiled in only for the case when CORECLR_EMBEDDED is not defined. So it seems that either the symbol is not defined when it should be.

Thank you for reporting this issue just in time, I was just about to backport it to .NET 7 as there were no errors reported by any of our tests during the last month.

@elinor-fung it seems we are missing host tests for this kind of scenario.

**Comment by am11** [comment]
> it seems we are missing host tests for this kind of scenario.

Yup. Single-file tests were added and then removed for cost saving: https://github.com/dotnet/runtime/issues/67062#issuecomment-1110940869. We should revert that change as at least a few "basic" single-file tests should be available in this repro. The end-to-end test in installer repo does not catch anything related to single-file and we have always found breakages with manual testing or consumer reports.

**Comment by janvorli** [comment]
@am11 even enabling the test didn't repro the issue. The problem is that the test build still copies the `libSystem.Native.so` into the test binary directory. 
Anyways, I've found the problem and I am going to create a PR with a fix in a minute.

**Comment by am11** [comment]
> test build still copies the libSystem.Native.so into the test binary directory

@janvorli, this defeats the purpose of PublishSingleFile sandbox test. We should fix it by passing `-p:PublishDir=<always a new path>` to avoid mixing things.

BTW, this is exactly what I am currently working on in https://github.com/dotnet/runtime/pull/80154. crossgen2.exe is currently the only thing in runtime repo which is published as SingleFile or AOT (depending on the platform) and we are not using the "published" binary (which we ship in publicly available nuget package), but instead invoking its assembly with `<dotnet.exe or corerun.exe> crossgen2.dll`.
