### PR TITLE
[wasm][coreclr] Implement RhpNewArrayFastAlign8

### LINKED ISSUE #120659: [wasm][coreclr] implement RhpNewArrayFastAlign8
With https://github.com/dotnet/runtime/issues/120318 fixed, we are now hitting
```
TestArray
ASSERT FAILED
	Expression: false && "RhpNewArrayFastAlign8 is not yet implemented"
	Location:   line 79 in /Users/rodo/git/runtime-main/src/coreclr/runtime/portable/AllocFast.cpp
	Function:   RhpNewArrayFastAlign8
	Process:    42
Frame (InterpreterFrame): 0x4fecac
   0) InterpreterTest::ArrayInt64, IR_0007
   1) InterpreterTest::TestArray, IR_0449
   2) InterpreterTest::RunInterpreterTests, IR_0602
   3) InterpreterTest::Main, IR_0029
```

### PR DESCRIPTION
**Pull request by radekdoulik**
Resolves https://github.com/dotnet/runtime/issues/120659

### CODE REVIEW

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 1]
```diff
@@ -3,13 +3,15 @@
...
 
 #include <fcall.h>
+#include <gcinterface.h>
+#include "../gc/env/gcenv.ee.h"
 
 extern void RhExceptionHandling_FailedAllocation(MethodTable *pMT, bool isOverflow);
 EXTERN_C Object* RhpGcAlloc(MethodTable* pMT, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame);
 
-EXTERN_C FCDECL2(Object*, RhpNewVariableSizeObject, MethodTable* pMT, INT_PTR numElements)
+static Object* _AllocateObject(MethodTable* pMT, uint32_t uFlags, INT_PTR numElements)
```
Comment (jkotas) [inline src/coreclr/runtime/portable/AllocFast.cpp]: Do we need `_` prefix in the name? This is local function, so it should not conflict with anything.

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 2]
```diff
@@ -3,13 +3,15 @@
 //
 
 #include <fcall.h>
+#include <gcinterface.h>
+#include "../gc/env/gcenv.ee.h"
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/runtime/portable/AllocFast.cpp]: Why is this header needed?

File: src/coreclr/runtime/portable/AllocFast.cpp (hunk 1 above)
Comment (radekdoulik) [reply src/coreclr/runtime/portable/AllocFast.cpp]: It is not needed. I have updated the other names too and also removed _Rhp prefix from the core functions, so that it is easier to distinguish the local functions here.

File: src/coreclr/runtime/portable/AllocFast.cpp (hunk 2 above)
Comment (radekdoulik) [reply src/coreclr/runtime/portable/AllocFast.cpp]: For `GCToEEInterface::GetFreeObjectMethodTable()`

Comment (AaronRobinsonMSFT) [reply src/coreclr/runtime/portable/AllocFast.cpp]: The `GCToEEInterface` is for the GC to communicate with the VM. In this case, I believe we want to use `g_pFreeObjectMethodTable` instead. This is defined in `vars.hpp`.

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 3]
```diff
@@ -3,13 +3,15 @@
...
 
 extern void RhExceptionHandling_FailedAllocation(MethodTable *pMT, bool isOverflow);
 EXTERN_C Object* RhpGcAlloc(MethodTable* pMT, uint32_t uFlags, uintptr_t numElements, void * pTransitionFrame);
 
-EXTERN_C FCDECL2(Object*, RhpNewVariableSizeObject, MethodTable* pMT, INT_PTR numElements)
+static Object* AllocateObject(MethodTable* pMT, uint32_t uFlags, INT_PTR numElements)
 {
-    Object* obj = RhpGcAlloc(pMT, 0, numElements, nullptr);
+    Object* obj = RhpGcAlloc(pMT, uFlags, numElements, nullptr);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/runtime/portable/AllocFast.cpp:15]:
```suggestion
    FCALL_CONTRACT;
    Object* obj = RhpGcAlloc(pMT, uFlags, numElements, nullptr);
```

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 4]
```diff
@@ -18,7 +20,12 @@ EXTERN_C FCDECL2(Object*, RhpNewVariableSizeObject, MethodTable* pMT, INT_PTR nu
     return obj;
 }
 
-static Object* _RhpNewArrayFastCore(MethodTable* pMT, INT_PTR size)
+EXTERN_C FCDECL2(Object*, RhpNewVariableSizeObject, MethodTable* pMT, INT_PTR numElements)
+{
+    return AllocateObject(pMT, 0, numElements);
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/runtime/portable/AllocFast.cpp:27]:
```suggestion
    WRAPPER_NO_CONTRACT;
    return AllocateObject(pMT, 0, numElements);
```

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 5]
```diff
@@ -41,7 +50,64 @@ static Object* _RhpNewArrayFastCore(MethodTable* pMT, INT_PTR size)
...
+    _ASSERTE(size < INT32_MAX);
+
+    Thread* thread = GetThread();
+    ee_alloc_context* cxt = thread->GetEEAllocContext();
+
+    size_t sizeInBytes = (size_t)pMT->GetBaseSize() + ((size_t)size * (size_t)pMT->RawGetComponentSize());
+    sizeInBytes = ALIGN_UP(sizeInBytes, sizeof(void*));
+
+    uint8_t* alloc_ptr = cxt->getAllocPtr();
+    int requiresAlignObject = ((uint32_t)alloc_ptr) & 7;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/runtime/portable/AllocFast.cpp]: I _think_ we have a macro for this sort of operation. @jkotas ?

**Review by AaronRobinsonMSFT — COMMENTED** [review]
Overall, LGTM. I'm like to try and remove some of the "magic" numbers in `NewArrayFastAlign8Core`. There must be some simple macros or computation to get them.

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 6]
```diff
@@ -41,7 +50,64 @@ static Object* _RhpNewArrayFastCore(MethodTable* pMT, INT_PTR size)
         return pObject;
     }
 
-    return RhpNewVariableSizeObject(pMT, size);
+    return AllocateObject(pMT, 0, size);
+}
+
+static Object* NewArrayFastAlign8Core(MethodTable* pMT, INT_PTR size)
```
Comment (jkotas) [inline src/coreclr/runtime/portable/AllocFast.cpp:61]:
```suggestion
#if defined(FEATURE_64BIT_ALIGNMENT)
static Object* NewArrayFastAlign8Core(MethodTable* pMT, INT_PTR size)
```

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 7]
```diff
@@ -41,7 +50,64 @@ static Object* _RhpNewArrayFastCore(MethodTable* pMT, INT_PTR size)
...
+    // <= 0xffff, and thus the product is <= 0xffff0000, and the base size is only ~12 bytes
+    if (size > 0x10000)
+    {
+        // Overflow here should result in an OOM. Let the slow path take care of it.
+        return AllocateObject(pMT, GC_ALLOC_ALIGN8, size);
+    }
+#endif // !HOST_64BIT
+
+    return NewArrayFastAlign8Core(pMT, size);
 }
```
Comment (jkotas) [inline src/coreclr/runtime/portable/AllocFast.cpp:120]:
```suggestion
}
#endif // FEATURE_64BIT_ALIGNMENT
```

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 8]
```diff
@@ -41,7 +50,64 @@ static Object* _RhpNewArrayFastCore(MethodTable* pMT, INT_PTR size)
...
+
+    return AllocateObject(pMT, GC_ALLOC_ALIGN8, size);
+}
+
+EXTERN_C FCDECL2(Object*, RhpNewArrayFastAlign8, MethodTable* pMT, INT_PTR size)
+{
+    FCALL_CONTRACT;
+    _ASSERTE(pMT != NULL);
+
+#ifndef HOST_64BIT
```
Comment (jkotas) [inline src/coreclr/runtime/portable/AllocFast.cpp]:
```suggestion
```

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 9]
```diff
@@ -41,7 +50,64 @@ static Object* _RhpNewArrayFastCore(MethodTable* pMT, INT_PTR size)
...
+    // if the element count is <= 0x10000, no overflow is possible because the component size is
+    // <= 0xffff, and thus the product is <= 0xffff0000, and the base size is only ~12 bytes
+    if (size > 0x10000)
+    {
+        // Overflow here should result in an OOM. Let the slow path take care of it.
+        return AllocateObject(pMT, GC_ALLOC_ALIGN8, size);
+    }
+#endif // !HOST_64BIT
```
Comment (jkotas) [inline src/coreclr/runtime/portable/AllocFast.cpp]:
```suggestion
```

File: src/coreclr/runtime/portable/AllocFast.cpp (hunk 5 above)
Comment (jkotas) [reply src/coreclr/runtime/portable/AllocFast.cpp]: There is e.g. IS_ALIGNED macro for this (sibling of `ALIGN_UP` used above).

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 10]
```diff
@@ -41,7 +50,64 @@ static Object* _RhpNewArrayFastCore(MethodTable* pMT, INT_PTR size)
...
+
+    _ASSERTE(alloc_ptr <= cxt->getAllocLimit());
+    if ((size_t)(cxt->getAllocLimit() - alloc_ptr) >= paddedSize)
+    {
+        cxt->setAllocPtr(alloc_ptr + paddedSize);
+        if (requiresAlignObject)
+        {
+            Object* dummy = (Object*)alloc_ptr;
+            dummy->SetMethodTable(g_pFreeObjectMethodTable);
+            alloc_ptr += 12;
```
Comment (jkotas) [inline src/coreclr/runtime/portable/AllocFast.cpp]: You can replace 12 with `MIN_OBJECT_SIZE` if you would like to avoid the magic constant.

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 11]
```diff
@@ -41,7 +50,64 @@ static Object* _RhpNewArrayFastCore(MethodTable* pMT, INT_PTR size)
...
+
+    size_t sizeInBytes = (size_t)pMT->GetBaseSize() + ((size_t)size * (size_t)pMT->RawGetComponentSize());
+    sizeInBytes = ALIGN_UP(sizeInBytes, sizeof(void*));
+
+    uint8_t* alloc_ptr = cxt->getAllocPtr();
+    int requiresAlignObject = ((uint32_t)alloc_ptr) & 7;
+    size_t paddedSize = sizeInBytes;
+    if (requiresAlignObject)
+    {
+        paddedSize += 12;
```
Comment (jkotas) [inline src/coreclr/runtime/portable/AllocFast.cpp]:
```suggestion
        // We are assuming that allocation of minimal object flips the alignment
        paddedSize += MIN_OBJECT_SIZE;
```

File: src/coreclr/runtime/portable/AllocFast.cpp (hunk 5 above)
Comment (radekdoulik) [reply src/coreclr/runtime/portable/AllocFast.cpp]: I can use `IS_ALIGNED` macro and `sizeof(int64_t)`

**Review by jkotas — APPROVED** [review]

File: src/coreclr/runtime/portable/AllocFast.cpp (hunk 5 above)
Comment (radekdoulik) [reply src/coreclr/runtime/portable/AllocFast.cpp]: Done

File: src/coreclr/runtime/portable/AllocFast.cpp [hunk 12]
```diff
@@ -41,9 +50,67 @@ static Object* _RhpNewArrayFastCore(MethodTable* pMT, INT_PTR size)
...
-    return RhpNewVariableSizeObject(pMT, size);
+    return AllocateObject(pMT, 0, size);
+}
+
+#if defined(FEATURE_64BIT_ALIGNMENT)
+static Object* NewArrayFastAlign8Core(MethodTable* pMT, INT_PTR size)
+{
+    FCALL_CONTRACT;
+    _ASSERTE(pMT != NULL);
+    _ASSERTE(size < INT32_MAX);
```
Comment (jkotas) [inline src/coreclr/runtime/portable/AllocFast.cpp]: I do not see what guarantees that size < INT32_MAX. Can the size be negative?

Comment (AaronRobinsonMSFT) [reply src/coreclr/runtime/portable/AllocFast.cpp]: In native AOT - see `src\coreclr\nativeaot\Runtime\portable.cpp`, there is a check for negative.

```cpp
    if (numElements < 0)
    {
        ASSERT_UNCONDITIONALLY("NYI");  // TODO: Throw overflow
    }
```

The argument is also `int` so naturally limited to `INT32_MAX`. Unsure why this is `INT_PTR` in CoreCLR. Is it intentional?

Comment (radekdoulik) [reply src/coreclr/runtime/portable/AllocFast.cpp]: Possibly because the size comes from `newarr` IL? I found this comment
https://github.com/dotnet/runtime/blob/bb1e80a56d97ffc5e513981d4c9ea205bede5aab/src/coreclr/vm/gchelpers.cpp#L93-L99

So I think we should check for negative too.

Comment (radekdoulik) [reply src/coreclr/runtime/portable/AllocFast.cpp]: Interestingly `RhpGcAlloc` has `uintptr_t numElements` and then checks for negative, which doesn't make sense?

@jkotas  I see you replaced `uintptr_t` with `intptr_t`in other places recently, should we change it here  too? https://github.com/dotnet/runtime/blob/bb1e80a56d97ffc5e513981d4c9ea205bede5aab/src/coreclr/vm/gchelpers.cpp#L58

Comment (jkotas) [reply src/coreclr/runtime/portable/AllocFast.cpp]: > Possibly because the size comes from newarr IL? I found this comment

Right, it is whatever you pass in to `new X[...]` in C#.

> I see you replaced uintptr_t with intptr_tin other places recently, should we change it here too?

I think so - looks like that I have missed this one.

Comment (radekdoulik) [reply src/coreclr/runtime/portable/AllocFast.cpp]: I didn't put `#ifdef HOST_64BIT` around the `INT32_MAX` check, I guess compiler will throw it away for 32bit platforms. Or should I add it for consistency?

**Review by jkotas — APPROVED** [review]
