### PR TITLE
Disable W^X in Rosetta emulated x64 containers on macOS

### LINKED ISSUE #102226: Crash on Rosetta for double mapping jitted code
### Description

Roblox reported that their app crashes when run in Rosetta unless they set DOTNET_EnableWriteXorExecute=0

### Reproduction Steps

docker run --platform linux/amd64 -it docker.artifactory.rbx.com/dotnet/sdk:8.0 /bin/bash 

root@361134e3e399:/# dotnet new tool-manifest

### Expected behavior

No crash

### Actual behavior

Segmentation fault

### Regression?

Unknown

### Known Workarounds

set DOTNET_EnableWriteXorExecute=0

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by janvorli**
The docker on macOS Arm64 uses Rosetta to run x64 containers. That has an effect on the double mapping. The Rosetta is unable to detect when an already executed code page is modified. So we cannot use double mapping on those containers. To detect that case, this change adds check that verifies that the double mapping works even when the code is modified.

Close #102226

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @noahfalk, @mangod9

File: src/coreclr/minipal/Unix/doublemapping.cpp [hunk 1]
```diff
@@ -47,6 +47,90 @@ static const off_t MaxDoubleMappedSize = UINT_MAX;
 
 #endif // TARGET_OSX
 
+#if defined(TARGET_AMD64) && !defined(TARGET_OSX)
```
Comment (am11) [inline src/coreclr/minipal/Unix/doublemapping.cpp:50]: Is there any technical issue that require us to restrict this run-time introspection? If we don't restrict it, then it will cover qemu cases for other archs as well (e.g. https://github.com/dotnet/runtime/issues/97729#issuecomment-2050507728), and prevent user from manually setting `DOTNET_EnableWriteXorExecute=1` to run .NET applications.

Comment (am11) [reply src/coreclr/minipal/Unix/doublemapping.cpp:50]: I remember once @jkotas mentioned that we wanted to support rosetta2 on macOS as a first-class platform, and therefore we are handling it explicitly with `sysctl.proc_translated` in a few places (coreclr, nativelibs and shell scripts and even in official build infra for downloading x64 on arm64 in translated process). I think it might be better to bring this to `IsProcessTranslated` plan as well without the run-time detection? https://github.com/dotnet/runtime/blob/362a95d53d7266ee9b7452e351d07845dcc1edd2/src/coreclr/minipal/Unix/doublemapping.cpp#L28

Comment (jkotas) [reply src/coreclr/minipal/Unix/doublemapping.cpp:50]: `sysctl.proc_translated` is not going to help. This is about running Linux docker containers. We do not know about `sysctl.proc_translated` equivalent for Linux docker containers running under Rosetta.

File: src/coreclr/minipal/Unix/doublemapping.cpp [hunk 2]
```diff
@@ -47,6 +47,90 @@ static const off_t MaxDoubleMappedSize = UINT_MAX;
...
+    {
+        goto Cleanup;
+    }
+
+    // Now overwrite the first function by a second one that returns 2 using the writeable mapping
+    memcpy(pWriteablePage, (void*)VerifyDoubleMapping2, (char*)VerifyDoubleMapping2_End - (char*)VerifyDoubleMapping2);
+    pVerificationFunction = (VerificationFunctionPtr)pExecutablePage;
+    testCallResult = pVerificationFunction();
+    // Invoke the function via the executable mapping again. It should return 2 now.
+    // This doesn't work when running x64 code in docker on macOS Arm64 where the code is not re-translated by Rosetta
```
Comment (jkotas) [inline src/coreclr/minipal/Unix/doublemapping.cpp:113]: I am wondering whether it is possible to make it work by issuing flush instruction cache syscall. Is there a syscall like on Linux x64?

Similar to what we do for Windows: https://github.com/dotnet/runtime/blob/362a95d53d7266ee9b7452e351d07845dcc1edd2/src/coreclr/vm/amd64/cgencpu.h#L588-L605

Comment (janvorli) [reply src/coreclr/minipal/Unix/doublemapping.cpp:113]: Apple folks told me in the past that Rosetta doesn't support this scenario, but I can add the cache flushing. In fact, it should be in this testing method anyways.

File: src/coreclr/minipal/Unix/doublemapping.cpp (hunk 1 above)
Comment (am11) [reply src/coreclr/minipal/Unix/doublemapping.cpp:50]: Ah, I see, it makes sense. Could we enable this feature detection for other platforms as well (which will cover qemu scenarios)? (assuming the overhead due to this one-time check is negligible)

File: src/coreclr/minipal/Unix/doublemapping.cpp (hunk 2 above)
Comment (janvorli) [reply src/coreclr/minipal/Unix/doublemapping.cpp:113]: To be specific, the problem is that Rosetta JITs the x64 code into arm64 on first execution and uses the result ever after. Since it doesn't get any notification on the executable code modification via a secondary mapping, it doesn't re-JIT it and keeps using the old code.

Comment (janvorli) [reply src/coreclr/minipal/Unix/doublemapping.cpp:113]: As for the cache flushing, there is the `__builtin___clear_cache`, but it doesn't generate any code on x64. And there is no syscall to do that on Linux.

File: src/coreclr/minipal/Unix/doublemapping.cpp [hunk 3]
```diff
@@ -74,6 +158,14 @@ bool VMToOSInterface::CreateDoubleMemoryMapper(void** pHandle, size_t *pMaxExecu
         return false;
     }
 
+#if defined(TARGET_AMD64) && !defined(TARGET_OSX)
+    if (!VerifyDoubleMapping(fd))
+    {
+        close(fd);
+        return false;
```
Comment (jkotas) [inline src/coreclr/minipal/Unix/doublemapping.cpp:165]: Is this going to result in W^X being disable?

If I am reading the code correctly, it is going to result into startup failure.

Comment (janvorli) [reply src/coreclr/minipal/Unix/doublemapping.cpp:165]: No, it is going to result in W^X being disabled - I've tested it in a x64 docker container on my M1. See the caller of the `VMToOSInterface::CreateDoubleMemoryMapper`:
https://github.com/dotnet/runtime/blob/745230568e52639e229dcc24c98fe0dbb4c1641d/src/coreclr/utilcode/executableallocator.cpp#L282-L298

**Review by jkotas — APPROVED** [review]

File: src/coreclr/minipal/Unix/doublemapping.cpp (hunk 1 above)
Comment (janvorli) [reply src/coreclr/minipal/Unix/doublemapping.cpp:50]: @am11 I've tried to look at the discussion you have linked, but I have not seen any evidence of the culprit being inability to double map. But I might have missed that. Can you please point me to such information? The point is, if it is not a problem of double mapping, this check may not be able to check the other issue. 
When I started to investigate this issue, I actually still had a docker desktop that used QEMU for x64 emulation on arm64 and even with W^X disabled, attempt to build .NET runtime was failing at some point due to SIGSEGV. Only after that I've realized I need to upgrade docker to get the version that used Rosetta to be able to make it work even with W^X disabled.

**Comment by mrpippy** [comment]
If you just want to detect Rosetta when running on Linux, the best way I know of is to get the "processor brand string" [through CPUID](https://en.wikipedia.org/wiki/CPUID#EAX=80000002h,80000003h,80000004h:_Processor_Brand_String), and check for `VirtualApple`.

**Comment by jkotas** [comment]
@mrpippy Thank you for the tip! @janvorli Checking CPUID sounds better to me than what's in the PR. What do you think?

**Comment by am11** [comment]
With qemu based linux/amd64 container running on osx-arm64: `CPU Vendor: AuthenticAMD`
With roestta based linux/amd64 container running on osx-arm64: `CPU Vendor: GenuineIntel`

test:
```sh
# on osx-arm64
# docker run --rm --platform linux/amd64 ubuntu
# apt update && apt install -y gcc

$ cc -xc - <<EOF
#include <stdio.h>
#include <string.h>
#include <cpuid.h>

int main()
{
    unsigned int regs[4];
    char vendor[13];
    char brand[49];

    // Get the vendor string
    __cpuid(0, regs[0], regs[1], regs[2], regs[3]);
    memcpy(vendor, &regs[1], 4);
    memcpy(vendor + 4, &regs[3], 4);
    memcpy(vendor + 8, &regs[2], 4);
    vendor[12] = '\0';

    printf("CPU Vendor: %s\n", vendor);

    // Get the brand string if available
    if (regs[0] >= 0x80000004) {
        __cpuid(0x80000002, regs[0], regs[1], regs[2], regs[3]);
        memcpy(brand, regs, 16);
        __cpuid(0x80000003, regs[0], regs[1], regs[2], regs[3]);
        memcpy(brand + 16, regs, 16);
        __cpuid(0x80000004, regs[0], regs[1], regs[2], regs[3]);
        memcpy(brand + 32, regs, 16);
        brand[48] = '\0';

        printf("CPU Brand: %s\n", brand);
    } else {
        printf("CPU Brand: Not available\n");
    }

    return 0;
}
EOF


$ ./a.out
CPU Vendor: GenuineIntel
CPU Brand: Not available
```

**Comment by am11** [comment]
A less-appealing ways to detect is:

```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>

int main() {
    // Get the process name of PID 1
    pid_t pid = 1;
    char proc_path[256];
    char proc_name[256];
    snprintf(proc_path, sizeof(proc_path), "/proc/%d/cmdline", pid);

    FILE *file = fopen(proc_path, "r");
    if (file == NULL) {
        fprintf(stderr, "Error opening file: %s\n", strerror(errno));
        exit(EXIT_FAILURE);
    }

    if (fgets(proc_name, sizeof(proc_name), file) != NULL) {
        printf("Process name of PID %d: %s\n", pid, proc_name);
    } else {
        fprintf(stderr, "Error reading process name\n");
        exit(EXIT_FAILURE);
    }

    fclose(file);
    return 0;
}
```

> Process name of PID 1: /run/rosetta/rosetta

(we try to sparingly use procfs, but in this case, maybe not bad after all 😅)

File: src/coreclr/minipal/Unix/doublemapping.cpp (hunk 1 above)
Comment (am11) [reply src/coreclr/minipal/Unix/doublemapping.cpp:50]: @janvorli, I was running into `qemu: uncaught target signal 11 (Segmentation fault)` which was fixed with `DOTNET_EnableWriteXorExecute=0`. Later dotnet publish  was failing a runtime assertion on qemu arm target. But to get to that late assertion `DOTNET_EnableWriteXorExecute=0` solution to sigsegv was the roadblock. In the context of this PR, I thought it might be useful to keep the condition a bit relaxed.

Comment (am11) [reply src/coreclr/minipal/Unix/doublemapping.cpp:50]: @janvorli, I was running into `qemu: uncaught target signal 11 (Segmentation fault)` which was fixed with `DOTNET_EnableWriteXorExecute=0`. Later dotnet publish  was failing a runtime assertion on qemu arm target. But to get to that late assertion sigsegv was the roadblock that `DOTNET_EnableWriteXorExecute=0` fixed. In the context of this PR, I thought it might be useful to keep the condition a bit relaxed.

**Comment by mrpippy** [comment]
> With qemu based linux/amd64 container running on osx-arm64: `CPU Vendor: AuthenticAMD` With roestta based linux/amd64 container running on osx-arm64: `CPU Vendor: GenuineIntel`
> 
> test:
> 
> ```shell
> $ ./a.out
> CPU Vendor: GenuineIntel
> CPU Brand: Not available
> ```

That's not correct: `regs[0]` there is the maximum value for basic CPUID information, even on a real Intel system it only returns 0x20. You have to additionally call `__cpuid(0x80000000, regs[0], regs[1], regs[2], regs[3]);` to get the maximum value for "extended function" CPUID info. I'm testing on macOS, but with that line added I get:
```
$ ./a.out
CPU Vendor: GenuineIntel
CPU Brand: VirtualApple @ 2.50GHz
```

Maybe a function to get the CPU brand can go into `minipal/cpufeatures.c`?

(BTW, I stumbled across this issue because I work on Wine, and found that .NET 7/8 apps were hanging when run on Wine, on Rosetta/macOS. They work again when `DOTNET_EnableWriteXorExecute=0` is used. It's an odd request, but I'd like to add a CPUID check like this to the Windows `doublemapping.cpp` also, and having the function in `minipal` would be nice.)

**Comment by am11** [comment]
Ah, thanks for the pointer! Yes having this detection in minipal is a nice idea (assuming we may end up using it in multiple places). e.g.

```c
bool minipal_is_rosetta_based_container(void)
{
    unsigned int regs[4];
    char brand[49];

    // Get the maximum value for extended function CPUID info
    __cpuid(0x80000000, regs[0], regs[1], regs[2], regs[3]);
    if (regs[0] < 0x80000004) {
        return false; // Extended CPUID not supported
    }

    // Retrieve the CPU brand string
    for (unsigned int i = 0x80000002; i <= 0x80000004; ++i) {
        __cpuid(i, regs[0], regs[1], regs[2], regs[3]);
        memcpy(brand + (i - 0x80000002) * sizeof(regs), regs, sizeof(regs));
    }
    brand[sizeof(brand) - 1] = '\0';

    // Check if CPU brand indicates Rosetta emulation
    return (strstr(brand, "VirtualApple") != NULL) ? true : false;
}
```

**Comment by janvorli** [comment]
> Checking CPUID sounds better to me than what's in the PR. What do you think?

I agree, I also prefer that. Let me rework the change that way.

**Comment by janvorli** [comment]
> perhaps a more general approach to cover QEMU as well:

@am11 thank you for the suggestion, makes sense to include that as well.

**Comment by am11** [comment]
A bit more broader approach could be this:

```c
#include <stdbool.h>
#include <string.h>
#include <unistd.h>

#ifdef TARGET_X64
#include <cpuid.h>
#endif

bool minipal_detect_emulation(void)
{
#ifdef TARGET_X64
    // Check for CPU brand indicating emulation
    unsigned int regs[4];
    char brand[49];

    // Get the maximum value for extended function CPUID info
    __cpuid(0x80000000, regs[0], regs[1], regs[2], regs[3]);
    if (regs[0] < 0x80000004)
    {
        return false; // Extended CPUID not supported
    }

    // Retrieve the CPU brand string
    for (unsigned int i = 0x80000002; i <= 0x80000004; ++i)
    {
        __cpuid(i, regs[0], regs[1], regs[2], regs[3]);
        memcpy(brand + (i - 0x80000002) * sizeof(regs), regs, sizeof(regs));
    }
    brand[sizeof(brand) - 1] = '\0'; // Null-terminate the string

    // Check if CPU brand indicates emulation
    if (strstr(brand, "VirtualApple") != NULL || strstr(brand, "QEMU") != NULL)
    {
        return true;
    }
#endif

    // Check for process name of PID 1 indicating emulation
    char cmdline[256];
    FILE *cmdline_file = fopen("/proc/1/cmdline", "r");
    if (cmdline_file != NULL)
    {
        fgets(cmdline, sizeof(cmdline), cmdline_file);
        fclose(cmdline_file);

        if (strstr(cmdline, "qemu") != NULL)
        {
            return true;
        }
    }

    return false;
}
```

**Comment by mangod9** [comment]
assume we are certain that `strstr(brand, "VirtualApple") != NULL` would work on localized environments as well right?

**Comment by am11** [comment]
It is conceivable that the name could be localized, but given that it's a brand name it may not be the case. In the last comment, I added a fallback for all platforms to proc/1/cmdline checking for qemu or rosetta, which should cover some corner cases of CPUID. 🤞

**Comment by jkotas** [comment]
> assume we are certain that strstr(brand, "VirtualApple") != NULL would work on localized environments as well right?

The CPU IDs are never localized. We check for CPU IDs in other places.

> strstr(cmdline, "qemu")

We know that the runtime is broken on qemu in number of different ways, this won't make it work reliably. If we want to check for qemu, I would rather fail with error that says qemu is not supported so that people stop filling issues about crashes caused by running on qemu.

File: src/native/minipal/cpufeatures.c [hunk 4]
```diff
@@ -473,3 +475,49 @@ int minipal_getcpufeatures(void)
...
+    brand[sizeof(brand) - 1] = '\0';
+
+    // Check if CPU brand indicates emulation
+    if (strstr(brand, "VirtualApple") != NULL || strstr(brand, "QEMU") != NULL)
+    {
+        return true;
+    }
+#endif
+
+    // Check for process name of PID 1 indicating emulation
```
Comment (jkotas) [inline src/native/minipal/cpufeatures.c:508]: Unless we know about cases where this is actually necessary, I do not think we should be doing this check.

File: src/coreclr/vm/amd64/asmhelpers.S [hunk 5]
```diff
@@ -311,3 +311,14 @@ LEAF_ENTRY GetTlsIndexObjectDescOffset, _TEXT
         int 3
 LEAF_END GetTlsIndexObjectDescOffset, _TEXT
 #endif
+
+# These functions are used to verify that double mapping used to implement W^X works.
```
Comment (jkotas) [inline src/coreclr/vm/amd64/asmhelpers.S:315]: No longer needed.

File: src/native/minipal/cpufeatures.c (hunk 4 above)
Comment (janvorli) [reply src/native/minipal/cpufeatures.c:508]: It seems it is also incorrect when running an app in docker say on x64 linux and the app has qemu or rosetta in its name or path. Then it would turn the W^X off even though there was no emulation. 
I guess you are right and we should remove all checks for qemu from this PR. We can add a qemu check in a separate PR to some different place in the runtime startup if we want to prevent the execution there.

Comment (am11) [reply src/native/minipal/cpufeatures.c:508]: @janvorli, PID 1 is reserved for init process.

Comment (am11) [reply src/native/minipal/cpufeatures.c:508]: > I guess you are right and we should remove all checks for qemu from this PR. 

AOT apps have no problem running on qemu. There are few things in VM which break and can be fixed given time. I don't think abandoning qemu straight up is the right thing. New architectures development (RV64, LA64) heavily rely on qemu.

Comment (janvorli) [reply src/native/minipal/cpufeatures.c:508]: > @janvorli, PID 1 is reserved for init process.

That is not the case under Docker without emulation. The PID 1 is used by the first process you run in the container. 

Example:
```
docker run -it ubuntu:22.04 /bin/bash
ps
```
shows
```
  PID TTY          TIME CMD
    1 pts/0    00:00:00 bash
    9 pts/0    00:00:00 ps
```

Comment (am11) [reply src/native/minipal/cpufeatures.c:508]: @janvorli, that is a good point. Thank you. To further disambiguate it, we can check the file actually exists and is a  Phantom or Virtual file (which init process are, e.g. will report it doesn't exists but proc/1/cmdline will return its path just like ps(1)).

```c
        if (strstr(cmdline, "qemu") != NULL || strstr(cmdline, "rosetta") != NULL)
        {
            // Verify if the file corresponding to the process name actually exists in the filesystem
            // If the file does not exist, it likely indicates a phantom path, suggesting a virtual or emulated environment
            if (!file_exists(cmdline))
            {
                return true;
            }
        }
```


```sh
root@00212246f8f2:/# ps uax
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0 149312 13644 pts/0    Ssl  04:20   0:00 /usr/bin/qemu-x86_64 /bin/bash /bin/bash
root      3130  0.0  0.0 152188 10388 ?        Rl+  09:02   0:00 ps uax
root@00212246f8f2:/# ls /usr/bin/qemu-x86_64
ls: cannot access '/usr/bin/qemu-x86_64': No such file or directory

# same with rosetta emulation
```

Comment (jkotas) [reply src/native/minipal/cpufeatures.c:508]: > AOT apps have no problem running on qemu. 

This function is not used or needed for AOT.

Comment (am11) [reply src/native/minipal/cpufeatures.c:508]: True, at the moment it has only one usage, but its name is general enough to be used in other places. If QEMU is broken in other cases which come after manually disabling W^X via environment variable, it will continue to be in that state (use at your own risk) until someone investigate/fix it upstream or add a few workaround in the coreclr VM where it usually give up.

Comment (am11) [reply src/native/minipal/cpufeatures.c:508]: True, at the moment it has only one usage, but its name is general enough to be used in other places. If QEMU is broken in other cases which come after manually disabling W^X via environment variable, it will continue to be in that state (use at your own risk) until someone investigate/fix it upstream or add a few workarounds in the coreclr VM where it usually give up.

Comment (janvorli) [reply src/native/minipal/cpufeatures.c:508]: I was thinking about this for a bit and I tend to agree with @am11 to not to block running on QEMU completely. While I can see quite a number of issues reported related to QEMU, the fact that Docker uses QEMU when running containers for non-native architectures makes me think that it would be worth keeping that in the enabled state and give QEMU a chance to fix the problems. For developers that want to test their code on multiple targets, it is a great mean for testing apps on target architectures that they don't have physical devices for.
As for disabling W^X for QEMU, I'd leave it out of the checks until the W^X is the only thing that doesn't work. The problem with W^X kicks in very quickly, so I think that it makes people find out quite soon the culprit if they search our issues. Random crashes sound much worse from the perspective of us investigating the problems.

Comment (jkotas) [reply src/native/minipal/cpufeatures.c:508]: > it would be worth keeping that in the enabled state and give QEMU a chance to fix the problems.

We have been in this state for last 10 years. I have not seen any of these reliability problems being fixed in QEMU during that time.

> For developers that want to test their code on multiple targets, it is a great mean for testing apps on target architectures that they don't have physical devices for.

I would be fine with having `DOTNET_UNRELIABLE_ENABLE_QEMU=1` settings that can be used by folks who want to give it a try.

Comment (janvorli) [reply src/native/minipal/cpufeatures.c:508]: Actually, having it disabled by default and enabling it using an env var like this sounds like a great idea. When looking though the QEMU related issues, I can see that in many cases people were not even aware that they were running under QEMU. So this way they would know right away and those that did that intentionally would be able to enable it.

Comment (janvorli) [reply src/native/minipal/cpufeatures.c:508]: Let's do that in a separate PR though.

**Review by jkotas — APPROVED** [review]
LGTM. Thanks!

File: src/coreclr/minipal/Windows/doublemapping.cpp [hunk 6]
```diff
@@ -60,6 +61,12 @@ inline void *GetBotMemoryAddress(void)
 
 bool VMToOSInterface::CreateDoubleMemoryMapper(void **pHandle, size_t *pMaxExecutableCodeSize)
 {
+    if (minipal_detect_emulation())
+    {
```
Comment (mrpippy) [inline src/coreclr/minipal/Windows/doublemapping.cpp:65]: Maybe a comment here to explain that Rosetta on Windows would be on Wine/macOS?

**Review by mrpippy — COMMENTED** [review]
Thanks for adding the Windows part! A few requests:

File: src/native/minipal/cpufeatures.c [hunk 7]
```diff
@@ -473,3 +475,49 @@ int minipal_getcpufeatures(void)
 
     return result;
 }
+
+bool minipal_detect_emulation(void)
+{
+#ifdef HOST_AMD64
```
[the remark this answers is not in the document]
Comment (janvorli) [reply src/native/minipal/cpufeatures.c]: Of course! I've added a new commit with that.

File: src/coreclr/minipal/Windows/doublemapping.cpp (hunk 6 above)
Comment (janvorli) [reply src/coreclr/minipal/Windows/doublemapping.cpp:65]: Added the comment

**Comment by janvorli** [comment]
@mrpippy many thanks for suggesting the CPUID way of checking for Rosetta!
