### PR TITLE
Value num refine phis

### LINKED ISSUE #95645: [Perf] Regressions from cross-block local assertion prop
### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Text.Perf_Ascii

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[EqualsIgnoreCase_ExactlyTheSame_Bytes_Chars - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Text.Perf_Ascii.EqualsIgnoreCase_ExactlyTheSame_Bytes_Chars(Size%3a%206).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.Encoding/Perf.Ascii.cs#L58-#L59>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXY/SQBR9N/E/zFtbZaF8qiQ1AqKiYhD6ZgwZ2gsdMx/dO9PddmP87c4UggubmL40ndNzzj1zc2+XQHWBIEAa/ew3uc8AgUwLxtM15IpEEfFSZSSYDhbSMAHeJWuKVCZZzUPY604GNNUdQZm8Ik4wyZiBxNhqhEnie+Vo4LWIR1HYl+DMjkGbb1SA83znbSptQLRjKE17BbjfTnTCWHt+W1CuFwepEGZUw3Ze0sTwKs5gY7XbaWVAb2cZRe1v2AOMySj4F2hdyJmSe3YokBqmpP7hzZTIGa9PS5WC95NEf4hnmKWn3vP/KS30hcn0pBAsQfVIwDSI3FT+E+FEmaABbaH0V34n6hY24X/Wc3lgEppwnXET3lJJ1TCuoy6kAcwR7LOJZHVQcZU3CrzKKs0SyleohHJIU+Gnaocs/cjVjnL2UGNNZOveummFeZkD2vWQ9exeTvNM2dUBjFV+ervcjNjKNoaKnLwlKTXgtszvhb3+TfjmJhzG4etxOBx3++1Xg9Gg2x2+DMNxGLoSuhCCoh1vQvGwFbT0a0OXoEVeBGRXXVVonber5Ub5ewEFWJ8c1S+7mU/Ia9AFNxHa1Kn/6CZHfHIHSA/WqR+0SG3ljKMPyECmvDojrln1wUVG+w2QuDsmdjsNuWcmI762zQMdnTUtUiaKF0JG15mqI66jYwhLNMxwiLz3tnX2f1Kdjk5CfKkDh+mcMxPREnTwFwYtngrxBAAA>)</li></ul> | 4.08 ns | 5.11 ns | 1.25 | 0.04 | False | | |
|<ul><li>[ToUpper_Chars - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Text.Perf_Ascii.ToUpper_Chars(Size%3a%20128).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.Encoding/Perf.Ascii.cs#L82-#L83>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U0W7TQBB8R+If7s02pImb0LSJZEQaWigQFBLzhFB0sTfxIt+dtXdu7Qrx7dw5UWhSCfnF8o1nZudWu54B1yWBAGn0i9/sIQMCdl1ini6gUCyKmJcqI8H0qJQGBXjHrGviMskaHsFG9zLgqe4JjvKEOKEkQwOJsdUYSuZ71fCN12EeJ2FfggM7Bm2+cgHO8523rLUB0Y2hMt050GY10QliN1bfiwJoNc04aX+JjzBm5/2r4F/RRSmnSm5wWxI3qKT+4U2VKDBvTjOVgveTRX+YZ9DSU+/l/5QW+owy3SsEJqSeCFCDKEztPxNOlAla0O6U/pLfi6ZNbfif9I3cooQ2XGfchjdTUrWM66h30gAVBPbZRjLfqrguWgWeZ7XGhOdzUkI5pK3wY70mTD/kas1zfGywNrJFf9G2wk1lR86ugGzm83hip8quB1Csiv3b8fTHVrY0XBTsLUu5AbdJfj/sD87C0Vl4EYdX4/BifD7oji4vR8P+8HUYjsPQldClEJzsgDNO25Xgld8YugQd9ipg6/qkQuewQR03yt9KKMH6FKR+2e17Rl6ALnMTkU2d+k9ussMn90B8a50GQYc1Vs44uiUEmeb1AXHNag4uMtlvQMzdMbH7adgDmoz52jYPdHTQdFiVqLwUMjrNVO9wHe1CWKJBk0Pkvbets/+Men90EuZLHThMFzmaiFegg78uv0Ij1QQAAA==>)</li></ul> | 17.57 ns | 23.73 ns | 1.35 | 0.15 | False | | |
|<ul><li>[ToLower_Chars - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Text.Perf_Ascii.ToLower_Chars(Size%3a%20128).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.Encoding/Perf.Ascii.cs#L73-#L74>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBM3H9BGMiINBQoNConfEIou9iZe5Luz9s5NXCF+O3dOFJpUQn6xfOOZ2bnVrqfAdUUgQBr94jfb5kDAbiossjmUisUx8zJlJJguVdKgAO+UdUNcpnnDI1jrbg48013BUZ4Rx5TmaCA1thpDyXxv92bghczjJOxLcGQnoM03LsB5vvcWtTYgOgnsTGcGtF6OdYrYSdS92gItJzkn7S/wEUbssncV/Cs6r+REyTVuKuIGldQ/vIkSJRbNaaoy8H6y+A/zDFp65r38n9JCX1FmB4XAlNQTAWoQpan9Z8KxMkEL2p3S98WDaNrUhv9F38oNSmjDdcZteFMlVcu4jnonDVBJYJ9tJLONSuqyVeBZXmtMeTEjJZRD2go/1yvC7FOhVrzAxwZrI5v35m0r3O5KILsCspnP04mdKLseQIkqD2+n059Y2cJwUbJ3LOMG3Cb5vajXv4iuL6JhEl2NouHoctC5vI6G/cHb11E0iiJXQldCcLIDzjhtloLv/MbQJQjZq4Ct6rMK4XGDQjfK3yuowPqUpH7Z7XtGnoOuChOTTZ35T26yx8cPQHxjnfpByBorZxx/JASZFfURcc1qDi4y2W9AzN0xtftp2BZNznxtmwc6PmpCtktVUQkZn2eq97iO9yEs0aApIPY+2NbZf0Z9ODoJ86UOHKbLAk3Md6CDv++sgaTVBAAA>)</li></ul> | 17.53 ns | 24.33 ns | 1.39 | 0.19 | True | | |
|<ul><li>[EqualsIgnoreCase_DifferentCase_Bytes_Chars - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Text.Perf_Ascii.EqualsIgnoreCase_DifferentCase_Bytes_Chars(Size%3a%20128).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.Encoding/Perf.Ascii.cs#L67-#L68>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXY/SQBR9N/E/zFtb7UKB3Q2S1AgsKioGoW/GkKG9tGPmo96Z7tKN8bc7UwgubGL60sycnHPvmZt7ugCqKwQB0ugXv8lDAQhkUjGeraBUJI6JlykjwXSxkoYJ8M5ZE6QyLRoewk53C6CZ7grK5AVxjGnBDKTGdiNMEt/b3157IfEoCnsITuwEtPlKBbia77x1rQ2ITgJ701kC7jZjnTLWmf2qKNfzXCqEKdWwuWO7nVVL09wmtQG9mRYUtb9mjzAivf4w+OdoVcmpkjuWV0gNU1J/96ZKlIw3t4XKwPtB4j/EM8zSM+/l/5QW+sxkdlQIlqJ6ImAaRGlq/5lwrEzQgjZX+gu/F80M2/A/6ZnMmYQ2XFe4DW+hpGpp11Hn0gCWCPbbRrLMVVKXrQwvi1qzlPIlKqEc0lb4sd4iyz5wtaWcPTZYG9mqv2rbYbYvAW0+ZLO85+s8VTY7gIkqj6fzaCRWtjZUlOQtyagBFzO/H/UHV9Gbq+gmiYaj6GbUu+4Mhr3+YHD7OopGUeRa6EoIinbBCcV8I+jebwo6ByF5FZBtfdEhPMUrdKv8rYIKbJ0S1U8bzWfkFeiKmxit68x/8pIDPr4HpLmtNAhC0pRyheP3yEBmvD4hbljNxVm2Gc0AiXtjavNpyAMzBfG1HR7o+KQJyT5VvBIyvvRUH3AdH0xYomGGQ+zd2dHZH0p9vDoJ8aUOHKZLzkxM96CDv2QeEovyBAAA>)</li></ul> | 22.04 ns | 23.75 ns | 1.08 | 0.10 | False | | |

graph
graph
graph
graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Text.Perf_Ascii.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Text.Perf_Ascii*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.TryGetValueTrue&lt;Int32, Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[ConcurrentDictionary - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.TryGetValueTrue(Int32%2c%20Int32).ConcurrentDictionary(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/TryGetValue/TryGetValueTrue.cs#L97-#L106>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBPHIYhEuCJNSykQFBKLF4TQxd7Gh+7D2rtr4wrx27lzotCkEvKLfbuamZ1b73oOVFsEAdLoZ7/JfQUI5MIyXi6hViTLSFAqI8H00UrDBATHqAuksqhaHMKt7ldAS90XlMkT4BSLihkojKtGmCRhsH39KohJQFG4Q3RA56DNFyrAa74LVo02IHozxbnjMiV1L8fmGsw3yi3kaOHtjTTDNCbt69whZWER3X0uWUug2IQr9gATMhqk0T9XSysd9pZtLNJW+HswU6JmvI3mqoTgB8n+kMAwBy+D5/9jutQnJss9Q7AC1SMC0yBq04RPiFNlog6wG6U/8zvR9rEL/qO+khsmoQvWC3fBzZVUHe16qPsagDWCe3ahLDYqb+pOhhdVo1lB+QKVUD7TlfihWSMrr7laU84e2lwX2jJddq1wta0B3Y7IdoCPR3qm3P4A5qren47XI3e0laGiJuekpAb8qoVpkg7PkvFZMsqTN5NkNEmT3nA8HqaDwcskmSSJL6GtEBTdgBOKm5+CbsNW0DuIyYuIrJuTCvFhxWI/yl8tWHA6NapfbsWegJegLTcZOtdl+Ogmu/z0DpBunNIwikkr5YWz98hAlrw5ZHyz2sBbdttZAhJ/x6KiaMg9MxUJtWse6OzAicm2UNwKmZ16anZ5ne1MOKBhhkMWXLrWuZ9Ksw89hYRSRz6na85MRrego7+vfd8F9gQAAA==>)</li></ul> | 1.04 μs | 1.91 μs | 1.83 | 0.06 | True | | |
|<ul><li>[IDictionary - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.TryGetValueTrue(Int32%2c%20Int32).IDictionary(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/TryGetValue/TryGetValueTrue.cs#L61-#L63>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TMBR9R+I/+C0JZG2WrtNWkYmt+6BAUWkjXhBCbnLXGPkjura3ZkL8duy0Kmsnobwk9s055x7f3OspUG0RBEijX/0mjxUgkCvLeDmHWpEsI0GpjATTRysNExDso66QyqJqcQj3ul8BLXVfUCYPgJdYVMxAYVw2wiQJg/XpSRCTgKJwi2iHzkGbL1SA13wfLBptQPTGinPHZUrqXo7NHZhvlFvI0cK7iTSDNCbt66I3uWYtjmITLtgTjMjwOI3+mZlbOVbynq0s0lbvezBWoma83U1VCcEPkv0hgWEOXgav/8d0oU9MlluGYAWqZwSmQdSmCV8QL5WJOsAmSn/mD6ItXxf8R30jV0xCF6wX7oKbKqk62vVQ9xMAawT37EKZrVTe1J0Mz6pGs4LyGSqhfKQr8UOzRFbecbWknD21sS60eTrvmuFmXQO60ZBt3+538li5sQHMVb1d7U9F7mgLQ0VNLkhJDfgJC9MkHRwl50fJME/ORslwlCa90+Hxydn54G2SjJLEp9BWCIquwQnF1U9B12Er6B3E5E1Els1Bhng3WbFv5a8WLDidGtUvN1kvwHPQlpsMnesyfHaSTfzyAZCunNIgikkr5YWzW2QgS97sIr5Y7cZbRvcNkPgzFhVFQx6ZqUioXfFAZztOTNaF4lbI7NBTs4nrbGPCAQ0zHLLg2pXO3SXNduspJJQ68jFdc2YyugYd/QUywba97QQAAA==>)</li></ul> | 2.24 μs | 3.52 μs | 1.57 | 0.30 | False | | |
|<ul><li>[SortedDictionary - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.TryGetValueTrue(Int32%2c%20Int32).SortedDictionary(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/TryGetValue/TryGetValueTrue.cs#L86-#L95>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TMBR9R+I/+C0JZG2armityMTWjTGgqLQRLwghN7lrjPwRXdtbMyF+O3ZalbWTUF4S++acc49v7vUMqLYIAqTRL36ThwoQyKVlvFxArUiWkaBURoLpo5WGCQgOUZdIZVG1OIQ73a+AlrovKJNHwAssKmagMC4bYZKEwebNaRCTgKJwi2iPzkGbL1SA13wXLBttQPSminPHZUrqXo7NDZhvlFvI0cLbW2mGaUza13lvqdBAecVaMMUmXLJHmJDRII3+OVpYOVXyjq0t0lb0ezBVoma83c1UCcEPkv0hgWEOXgYv/8d0oU9MljuGYAWqJwSmQdSmCZ8RL5SJOsBulf7M70Vbwy74j/parpmELlgv3AU3U1J1tOuh7k8A1gju2YUyX6u8qTsZnleNZgXlc1RC+UhX4odmhay84WpFOXtsY11oi3TRNcP1pgZ08yHb5j1s56lyswOYq3q3OhyN3NGWhoqanJOSGvBjFqZJOjxJxifJKE/OJslokia9s/FgPBicvk6SSZL4FNoKQdE1OKG4/inoJmwFvYOYvIrIqjnKEO/HK/at/NWCBadTo/rlxusZeAHacpOhc12GT06yjV/cA9K1UxpGMWmlvHD2HhnIkjf7iC9Wu/GW0X0DJP6MRUXRkAdmKhJqVzzQ2Z4Tk02huBUyO/bUbOM625pwQMMMhyy4cqVzF0qz23oKCaWOfEzXnJmMbkBHfwGGlmHb8gQAAA==>)</li></ul> | 21.25 μs | 22.79 μs | 1.07 | 0.04 | False | | |

graph
graph
graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.TryGetValueTrue%28Int32%2C%20Int32%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.TryGetValueTrue&lt;Int32, Int32&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Text.Json.Tests.Perf_Reader

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[ReadMultiSpanSequenceEmptyLoop - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Text.Json.Tests.Perf_Reader.ReadMultiSpanSequenceEmptyLoop(IsDataCompact%3a%20True%2c%20TestCase%3a%20Json40KB).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.Json/Utf8JsonReader/Perf.Reader.cs#L88-#L93>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U0W7TMBR9R+If/JYEuja0G3SVgmjLgG4rKmneEJrc5LYxiu1wfbM1E+LbsdOqrJ2E8pLY1+ece2z5eA7cVAgSFJkXv9lDDghsUokii6HULIqYl2lSQD2sFAkJ3jFqglyleYNDWJteDjwzPcmFOgGOMc0FQUq2GxOK+d727bnXYR5HaQfBAZ2Aoa9cgtP84C1rQyC7CWype220siNDprsAXN/Fthdg1/3mVUFiWXK1hF8VqBSuZEn1rdalPzMfOfGpliVPacQSrKDTNJlyAyPmRM/Dm0nwz29cqalWa7GpkJPQynz3HF0UzWyuM/B+sOgP80hYeOa9/B/Tlm6EyvYMKVLUTwjCgDPqPyOONQUtYDNtbot72ZxwG/y1uVIboaAN1gm3wc210i3tOuhMEWCJYL9tKIuNTuqyleFFXhuR8mKBWmpXaUv8Uq9QZJ8LveKFeGxqbWhxP27b4WpbAtr0qOZqH1/2qbbJAkx0uR8dByextCVxWbL3LOMELoR+P+wPzsLLs/AiCYej8GLUH3QHw/DN8PLd6zAchaFrYSopOYpHYBw3d5Jv/UbQOeiwVwFb1ScddrnYrdstfKugAqtTov5pg/sMHIOxsYvQus78JzvZ1cf3gHxjlQZBhzVSTjj6hAJUVtSHijusZuIso10DZG6Pac6R2IOgnPnGHh6Y6MDpsG2qi0qq6NRTvaubaGfCAklQAZFnHwGwz029nzoK85UJXM2UhaCIb8EEfwGI0pB1EAUAAA==>)</li></ul> | 32.63 μs | 34.33 μs | 1.05 | 0.07 | False | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Text.Json.Tests.Perf_Reader.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Text.Json.Tests.Perf_Reader*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Text.RegularExpressions.Tests.Perf_Regex_Common

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Uri_IsMatch - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Text.RegularExpressions.Tests.Perf_Regex_Common.Uri_IsMatch(Options%3a%20IgnoreCase%2c%20Compiled).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.RegularExpressions/Perf.Regex.Common.cs#L51-#L51>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UUW/TMBB+R+I/+C0JZG1o6bRVCqIrYxQolK48IVS5yTUxiu3oztmSCfHbsdOqrJ2E8hLZn7/v7vPlznPgVCFIUIae/Wb3OSCwq0oU6RJKzeKYeak2CkwfK2WEBO+YdYVcJXnLQ9hSPweeUl9yoU6IE0xyYSAxNhsTivleff7aC5nHUdpFcGCvgMwXLsHFfOvdNmRA9lZQm94SsqrgeF2XCERCK7I4GeotALdrewr1eqql1Kr3HcV6RnNuktz/WhrHHbNZpjTClBOEzPJKUUAa/LO5rNRUq63IKuSt4oe3Y7W7uU7B+8niP8wzwtJT7/n/lBb6JFS6V0iRoH4kEASyNI3/RDjRJuhAm2n6XNzJtrBd+B/pWmVCQReuC9yFN9dKd7TrqDNlAO2Ps98ukkWmV03ZyfAib0gkvFigltohXYUfmg2K9KbQG16IhxbrIlsOll0z2FYFtEOj2o4+7vGptgMFuNLlfnU8LysruzVcluwNS7kBN3v+IBoMz6LLs2i0ii7G0Wg8jHqjy1eD8+HFyygaR5FLQZWUHMUDMI7ZWvLabwM6ByF7EbBNc5IhPMxc6Fr5WwUV2Dgl6l92Xp+Ql0BVYWK0rlP/0U12+OQOkGc20jAIWRvKBY7fowCVFs0BccVqN84y2jNA5u6Y5BwNuxcmZz7Z4gHFB03I6kQXlVTxqadmh1O8M2GJRpgCYu+dLZ19ZZr91kmYryhwGJWFMDGvgYK//qI81wcFAAA=>)</li></ul> | 65.16 ns | 70.03 ns | 1.07 | 0.02 | False | | |
|<ul><li>[Uri_IsNotMatch - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Text.RegularExpressions.Tests.Perf_Regex_Common.Uri_IsNotMatch(Options%3a%20IgnoreCase%2c%20Compiled).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.RegularExpressions/Perf.Regex.Common.cs#L52-#L52>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U72/TMBD9jsT/4G9JIOuidkNbpSC2MliBjtKVTwhVXnJLjGI7urtsyYT427HTqeyHhPIlsp/fu3u+3HkBkhoEDYbpxW9xWwKCOG1Ula+gtiJNRZBbNsD72BhWGoLHrFOUJit7HsI17Zcgc9rXUpknxBPMSsWQscsmlBFh0L45CGIRSNRuEe3YayC+kBp8zHfBZUcMerSGlkcrKJpK4llbIxApa8jhxDRaAl5v3Cm0m5nV2prRd1SbOV1YXkjOyvBrzZ4+FfPCWISZJIiFo9aqgjz653TVmJk116poUPaKH8GW1e8WNofgp0j/iICVo+fBy/8pHfRZmfxeoVWG9oFAEeiau/CZ8MRyNIA2t/SlutF9bYfwP9GZKZSBIVwfeAhvYY0daNdT54YB3b9z3yGSZWHXXT3I8LLsSGWyWqLV1iNDhefdFar8Y2WvZKXuemyIbDVeDc3guhXQzY3pm/pxm8+smynAta3vV49HZu1klyx1Ld6KXDL48QvHyXiylxzvJYfr5GiaHE4nyehocnCcHI1fJ8k0SXwKarSWqO5ASCw2WrZhH9A7iMWrSFx1TzLEu7GLfSt/a6ABF6dG+8uN7DPyCqipOEXnOg8f3GSLn9wAysJFmkSx6EP5wOkHVGDyqtshvlj9xltGdwYo/B2zUiKLW8WlCMkVDyjdaWLRZrZqtEmfeuq2OKVbE47IiitIg/eudO6h6e63XiJCQ5HHqK4Up7IFiv4C+7NRgwoFAAA=>)</li></ul> | 68.94 ns | 76.96 ns | 1.12 | 0.03 | False | | |
|<ul><li>[MatchesWord - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Text.RegularExpressions.Tests.Perf_Regex_Common.MatchesWord(Options%3a%20None).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.RegularExpressions/Perf.Regex.Common.cs#L56-#L56>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TMBR9R+I/+C0JZG3WUkQrBdGVMQZ0lCwSDwhVbnKbGPkjuna2ZEL8duy0KmsnobxE9vE59x7f3OslUF0jCJBGP/tN7ktAIBc143kClSJxTLxcGQlmiLU0TIB3zLpAKrOy4yFs9bAEmuuhoEyeEOeYlcxAZmw2wiTxveb1Ky8kHkVhF8GBnYI2N1SAi/nOu221ATFIoTGDBIqaU7xsKgStmZLa4trowQpwu7an0KwXSgglB0tqshL0d4W5/7UyjjsjN0pC8M9WUsuFkltW1Eg7xg/PqivGu91S5eD9JPEf4hlm6bn3/H9KC31mMt8rBMtQPRIwDaIyrf9EOFcm6EG7VvoLvxNdIfvwP+lLWTB72x5cF7gPb6mk6mnXUa+lAbQ/yn77SFaFStuql+FV2WqWUb5CJZRD+go/thtk+RVXG8rZQ4f1kSWjpG8G25qAdkhk18HHPb1QdoAAU1XtV8fzkVrZraGiIm9JTg24WfNH0Wh8Fk3PokkavZlFk9n4fBCNzyeT6fRlFM2iyKXQtRAU2QMQisVa0MbvAjoHIXkRkE17kiE8zFjoWvlbDTXYOBWqX3Y+n5AT0DU3MVrXuf/oJjt8fgdICxtpHISkC+UCxx+Qgcx5e0BcsbqNs4z2DJC4O2YlRUPumSmJr23xQMcHTUiaTPFayPjUU7vDdbwzYYmGGQ6x996Wzr4q7X7rJMSXOnCYrjgzMW1AB38BTXTSZfcEAAA=>)</li></ul> | 1.01 μs | 1.08 μs | 1.08 | 0.08 | False | | |
|<ul><li>[Uri_IsNotMatch - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Text.RegularExpressions.Tests.Perf_Regex_Common.Uri_IsNotMatch(Options%3a%20Compiled).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.RegularExpressions/Perf.Regex.Common.cs#L52-#L52>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UUW/TMBB+R+I/+C0JZG1oVwaVgujKgAIdpQtPCFVucm2MYjs6X7ZkQvx27LQqayehvET25++7+3y58xy4qRAkKDJPfrO7HBDYZSWKbAmlZnHMvEyTAupjpUhI8I5Zl8hVmrc8hI3p58Az05dcqBPiBNNcEKRkszGhmO/VL8+9kHkcpV0EB3YChq65BBfzrXfTGALZS6Cm3hK2VcHxqi4RjBFaGYsbMr0F4GZlT6FeTbWUWvW+o1jNzLWmOac097+W5OhjZo9LUUAW/HO3rNRUq43YVshb1g9vx2p3c52B95PFf5hHwtIz7+n/lBb6LFS2V0iRon4gEAZkSY3/SDjRFHSgzbT5UtzKtp5d+J/MldoKBV24LnAX3lwr3dGuo84UAdr/Zb9dJIutTpqyk+FF3hiR8mKBWmqHdBV+bNYosg+FXvNC3LdYF9lysOyawXYooJ0V1TbycWtPtZ0jwESX+9XxmCRWdkNcluwNyziBGzl/EA2GZ9Hrs2iURK/G0Wg8fNEbDAcXo4vz51E0jiKXwlRSchT3wDhuV5LXfhvQOQjZs4Ctm5MM4WHUQtfK3yqowMYpUf+yY/qIvARTFRSjdZ35D26ywye3gHxrIw2DkLWhXOD4PQpQWdEcEFesduMsoz0DZO6Oac6R2J2gnPnGFg9MfNCErE51UUkVn3pqdriJdyYskQQVEHvvbOns49Lst07CfGUCh5myEBTzGkzwF/2Ylbf+BAAA>)</li></ul> | 69.53 ns | 76.92 ns | 1.11 | 0.06 | False | | |

graph
graph
graph
graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Text.RegularExpressions.Tests.Perf_Regex_Common.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Text.RegularExpressions.Tests.Perf_Regex_Common*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.CreateAddAndClear&lt;String&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Span - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.CreateAddAndClear(String).Span(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/CreateAddAndClear.cs#L41-#L52>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBOTJiGNcEVqChQICkneEEIX39Y+dB/W3rmNK8Rv586JQpNKyC+WbzwzO7fa9RyoqREkKGue/Sb3JSCQq5oLtoRKkzQlAdNWge1jrSyXEByzrpCqvGx5CLemXwJlpi8pVyfEGeYlt5BbV41wRcJgOx4GMQkoSvcSHdhrMPYrleA93warxliQvUwL4bRcK9PLEKiFGWMzxTIBFN+sLHJVXPZWFVXhij/AlIxeDaJ/CZa1yrS65UWNtDX5HmRaVly0p7lmEPwg6R8SWO7oLHj+P6WDPnPF9grJc9SPBNyArGwTPhHOtI060G60+SLuZNuzLvxP5loVXEEXrjfuwptrpTvG9dQbZQErBPfsIlkUet1UnQIvysbwnIoFaqk90lX4sdkgZx+E3lDBH1qsi2w5WHatcL2tAN0+qHZYj8c3025XANe62r8dr8LayVaWyopcEuZG2a9VOEgG52fJxVkyWieTaTKaDie94Xgynry+eJkk0yTxJUwtJUU34IRi8VPSbdga+gQxeRGRTXNSIT6sU+xH+VsNNTifCvUvt05PyEswtbAputQsfHSTHT67A6SFczqPYtJaeeP0PXJQTDQHxDerPfjI6L4BEn/HvKRoyT23JQmNax6Y9KCJyTbXopYqPc3U7HCT7kI4ouVWQBq8c61zP5Bmf/QSEioTecxUgtuUbsFEfwFNLhMZ4gQAAA==>)</li></ul> | 1.20 μs | 1.51 μs | 1.25 | 0.38 | False | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.CreateAddAndClear%28String%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.CreateAddAndClear&lt;String&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.IndexerSetReverse&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Span - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.IndexerSetReverse(Int32).Span(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Indexer/IndexerSetReverse.cs#L36-#L45>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBOTj1IiXJGGFgIEBSdvCKGLvY0P3Zf2zq1dIX47d04UmlRCfrF845nZudWuF0BNhSBAWvPsN7kvAYFcVYwXGWhF0pQEhbISbB8raZmA4Jh1hVTmZctDuDX9Emhh+oIyeUKcYl4yC7l11QiTJAzq81EQk4CicC/Rgb0GY79SAd7zXbBqjAXRmynOnZYpaXpzWUANuAKbwR2ggbdzaYeDy95KUxmu2ANMyPjVIPoXIKvkTMlbtq2Qth7fg5kSmvH2tFAFBD9I+ocEljl6ETz/n9JBn5ks9grBclSPBMyA0LYJnwinykYdaHNlvvA70basC/+TuZZbJqEL1xt34S2UVB3jeqrrPqBGcM8ukuVWrRvdKfCybAzLKV+iEsojXYUfmw2y4gNXG8rZQ4t1kWWDrGuF61oDunWQ7aweT+9MuVUBXCu9fzvehLWTrSwVmlySglrwWxUOksHwLHlzlozXycUkOZ8k49749Wg4uhi+TJJJkvgSphKCohtwQnH7U9A6bA19gpi8iMimOakQH7Yp9qP8rYIKnI9G9ctt0xNyBqbiNkWXuggf3WSHT92y0a1zGkYxaa28cXqDDGTBmwPim9UefGR03wCJv2NeUrTkntmShMY1D0x60MSkzhWvhExPMzU73KS7EI5omeWQBu9d69z/o9kfvYSE0kQeM5ozm9IaTPQXDssOKOEEAAA=>)</li></ul> | 173.16 ns | 228.86 ns | 1.32 | 0.00 | True | | |
|<ul><li>[Array - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.IndexerSetReverse(Int32).Array(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Indexer/IndexerSetReverse.cs#L27-#L34>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBPjNFWIcEUaCgQICk7eEEJX3zY+dB/W3rm1K8Rv586JQpNKyC+WbzwzO7fa9RKoqREkKGue/Sb3JSCQq5oLlkOlSZaRgGmrwA6xVpZLCI5ZV0hVUXY8hFszLIEyM5SUqxPiDIuSWyisq0a4ImHQXJwHMQkoSvcSHdgbMPYrleA93wbr1liQg7kWwmm5VmawUAwawDXYHO4ADbxZKDtKLwczRNqGa/4AUzJ+lUb/EuS1mmt1y7c10s7kezDXsuKiOy01g+AHyf6QwHJHZ8Hz/ykd9JkrtldIXqB+JOAGZGXb8Ilwpm3Ug7bQ5ou4k13P+vA/mWu15Qr6cL1xH95SK90zrqe69gNWCO7ZR7La6k1b9Qq8KlvDCypWqKX2SF/hx/YGOfsg9A0V/KHD+sjyNO9b4bqpAN0+qG5Yj8d3rt2uAG50tX87XoWNk60tlRW5JIxa8GsVpkk6OktenyXjTTKZJhfTZDyYJOlkcp6+TJJpkvgSppaSohtwQnH7U9Im7Ax9gpi8iMhNe1IhPqxT7Ef5Ww01OJ8K9S+3Tk/IOZha2AxdahY+uskOn7lto1vnNIpi0ll54+w9clBMtAfEN6s7+MjovgESf8eipGjJPbclCY1rHpjsoIlJU2hRS5WdZmp3uMl2IRzRcisgC9651rkfSLs/egkJlYk8ZirBbUYbMNFfXlZ9EeIEAAA=>)</li></ul> | 173.37 ns | 229.20 ns | 1.32 | 0.00 | True | | |
|<ul><li>[IList - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.IndexerSetReverse(Int32).IList(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Indexer/IndexerSetReverse.cs#L59-#L61>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBPHaSOIcEUaWgg0KDh+Qwhd7G186D6svXNrV4jfzp0ThSaVkCXLul3PzM6tdr0EqmsEAdLoF7/JQwkI5KpmvEihUiRJiFcoI8EMsZaGCfCOUVdIZV52OIQ7PSyBFnooKJMnwBnmJTOQG1uNMEl8r5mceyHxKAp7CA7oDLT5SgU4zffeutUGxGCuOLdcpqQeLGQBDeAaTAr3gBreLaQZx5eDxS3Txl+zR5iSi1Ec/HOQ1nKu5B3b1kg7ke/eXImK8S5aqgK8HyT5QzzDLLzwXv6PaVNfmCz2DMFyVE8ITIOoTOs/I86UCXrAFkrf8nvR9awP/rO+llsmoQ/WCffBLZVUPe06qG0/YIVg330oq63K2qqX4VXZapZTvkIllMv0JX5qN8iKj1xtKGePXa4PLY3TvhWumwrQ7oPshvV4fOfK7gpgpqr96XgVMktbGyoqckkKasCtlR9H8fgsensWXWTRm2k0sc8gGo3O48nkdRRNo8iV0LUQFO2AE4rbn4I2fifoHITkVUA27UmF8LBOoRvlbzXUYHUqVL/sOj0Dp6BrbhK0rgv/yU12+ZndNrq1SuMgJJ2UE05ukIEseHvIuGZ1gbOM9hsgcXfMS4qGPDBTEl/b5oFODpyQNLnitZDJqad2l9fJzoQFGmY4JN4H2zr7A2n3oaMQX+rA5XTFmUloAzr4C6oq8HniBAAA>)</li></ul> | 507.30 ns | 566.83 ns | 1.12 | 0.13 | False | | |

graph
graph
graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.IndexerSetReverse%28Int32%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.IndexerSetReverse&lt;Int32&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.Perf_Frozen&lt;NotKnownComparable&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Contains_True - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Perf_Frozen(NotKnownComparable).Contains_True(Count%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Frozen/Perf_Frozen.cs#L96-#L105>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/aQBB8r9T/cG+2WwccE1CL6qiEJm2SElHit6pCh73gq+7D2jsHjKr89t4ZRAORKr9YvvHM7Nxq1xOgukIQII1+84esC0AgVxXj+QxKRZKEeLkyEkwXK2mYAO+YdYVUZkXDQ1jqbgE0111BmTwhjjArmIHM2GqESeJ7m8GFFxKPorAvwYGdgjYPVIDz/Ow91tqA6IwV51bLlNSdKeByfoNqC/LTgzL3Uq3lWImSIl1wuLRcaWx9PU+xAn+sbO4h6Z/Hwb9Es8oq5JKtKqSN6U/POTDenCYqB+8XSZ6JZ5il597b/yktdM9kvlcIlqF6IWAaRGlq/5VwpEzQgnar9Hf+JJoetuHf6Wu5YhLacJ1xG95ESdUyrqPeSgNYIthnG8l0pdK6bBV4WtSaZZRPUQnlkLbCb/UCWf6VqwXlbNtgbWSzeNa2wvWmBLT7IZvhPR7nZgYBU1Xu345XI7WyR0NFSS5JTg24NfPjKO6dRR/Pon4afRhGg+F53OkP4os46r2PomEUuRK6EoIi2wKhuJoLuvEbQ5cgJO8CsqhPKoSH9QrdKP+ooALrU6L6bdfrFXkGuuImQZs691/cZIePngDpyjr1gpA0Vs44uUEGMuf1AXHNag4uMtpvgMTdMSsoGrJmpiC+ts0DnRw0IdlkildCJqeZ6h2uk10ISzTMcEi8L7Z19odS749OQnypA4fpkjOT0A3o4C+x/vPa8gQAAA==>)</li></ul> | 1.45 μs | 1.95 μs | 1.35 | 0.07 | False | | |
|<ul><li>[Contains_True - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Perf_Frozen(NotKnownComparable).Contains_True(Count%3a%2064).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Frozen/Perf_Frozen.cs#L96-#L105>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBNjl6iNcEUaWiglVUj9hlB0sTfxofuw9s5NHCF+O3dOFJpUQn6xfOOZ2bnVridAdY0gQBr96jdZl4BArmvGixlUiqQp8QplJJg+1tIwAd4x6xqpzMuWh7DU/RJoofuCMnlCHGFeMgO5sdUIk8T3NoNzLyQeRWFfggM7A20eqADn+dF7bLQB0Rsrzq2WKal7U8Dl/BbVFuSHB2XupVrLsRIVRbrgcGW50tj6ep5hDf5Y2dxDMjgP/gWa1VYgl2xVI209f3jOgPH2NFEFeD9J+od4hll64b3+n9JC90wWe4VgOapnAqZBVKbxXwhHygQdaHdKf+NPom1hF/5XfSNXTEIXrjPuwpsoqTrGddQ7aQArBPvsIpmuVNZUnQJPy0aznPIpKqEc0lX4pVkgKz5ztaCcbVusi2wWz7pWuNlUgHY9ZDu7x9PcjiBgpqr92/FmZFb2aKioyBUpqAG3ZX4cxclZdHkWvc+ii2E0GL6LexdJklzG8dsoGkaRK6FrISiyLRCKq7mgG781dAlC8iYgi+akQnjYrtCN8vcaarA+FapfdrtekGega25StKkL/9lNdvjoCZCurFMShKS1csbpLTKQBW8OiGtWe3CR0X4DJO6OeUnRkDUzJfG1bR7o9KAJySZXvBYyPc3U7HCd7kJYomGGQ+p9sq2z/5Nmf3QS4ksdOExXnJmUbkAHfwF9fFHX8QQAAA==>)</li></ul> | 210.64 ns | 243.33 ns | 1.16 | 0.12 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.Perf_Frozen%28NotKnownComparable%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.Perf_Frozen&lt;NotKnownComparable&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.Sort&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[LinqOrderByExtension - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Sort(Int32).LinqOrderByExtension(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Sort.cs#L72-#L80>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBOTkLSJcEUSAhQaCInfEEIXexsfug9379zaFeK3c+dEoUkl5Bfrdj0zO7fe9QKoLhEESKOf/Sb3OSCQacl4toJCkTgmXqaMBNPFUhomwDtGTZHKNG9wCDe6mwPNdFdQJk+AE0xzZiA1thphkvheNXzthcSjKOwhOKAT0OYLFeA033rrWhsQnZni3HKZkrqzVmjeXEnT7112rpm8/YoZ4LSeVwaktgh/zR5gTAavesE/D6tSzpS8YdsSaSPz3ZspUTDeRAuVgfeDxH+IZ5iFZ97z/zFt6jOT2Z4hWIrqEYFpEIWp/SfEiTJBC9iV0tf8TjRda4P/pOdyyyS0wTrhNriFkqqlXQe1XwOwQLDPNpTlViV10crwMq81SylfohLKZdoSP9YbZNkHrjaUs4cm14a26q3aVphXBaDdCNmM6/EAz5TdFsBEFfvT8TIklrY2VBTkkmTUgFssvxf1+mfR6CwaJNHFOBqO+1FndHE+GpwPX0bROIpcCV0KQdEOOKG4/Slo5TeCzkFIXgRkU59UCA8LFbpR/lZCCVanQPXLLtQT8Ap0yU2M1nXmP7rJLj+5A6Rbq9QPQtJIOeH4PTKQGa8PGdesJnCW0b4DJO6OaU7RkHtmcuJr2zzQ8YETkipVvBQyPvVU7/I63pmwQMMMh9h7Z1tnfyH1PnQU4ksduJwuODMxrUAHfwH6mhkY5AQAAA==>)</li></ul> | 16.49 μs | 20.15 μs | 1.22 | 0.13 | False | | |
|<ul><li>[LinqQuery - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.Sort(Int32).LinqQuery(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Sort.cs#L62-#L70>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3NvZ1E1cm1ZNhCvSUKClQSHJG0LoYm/jQ/fh7p3buEL8du6cKDSphPxi3a5nZufWu54AMzWCBGXNq9/ksQQEcllzUcyg0iTLCC20VWD7WCvLJdB91CUylZctDuHO9EtghelLxtUBcIR5yS3k1lUjXJGArs/e0ohQhtIdwh16AcZ+ZRK85ns6b4wF2RtrIRyXa2V6c4323bWyaXLRu+Xq/lsN2ARz/gRDcnqShP8Kz2o11uqOr2pkLfc7HWtZcdFGE10A/UGyP4Ra7uAFff0/pkt94arYMiTPUT8jcAOysk3wgjjSNuwAu9bmVjzItlVd8DfmSq24gi5YL9wFN9FKd7Troe4TAFYI7tmFMl3pRVN1MjwtG8NzJqaopfaZrsTPzRJ58UnoJRP8qc11oc2SWdcKV+sK0K2Bamd0f2rH2q0I4EJX29P+BiwcbW6ZrMgFKZgFv01BEifpcTw4jk8X8fkwPhumJ70kTgfn6eAojodx7EuYWkqGbsAJw9VPydZBK+gdRORNSJbNQYVot0WRH2W3ITU4nQr1L7dFL8AzMLWwGTrXRfDsJpv86AGQrZxSGkaklfLC2UfkoArR7DK+WW3gLaN7B0j8HfOSoSWP3JYkMK55YLIdJyLrXItaquzQU7PJm2xjwgEttwIy+sG1zv03mm3oKSRQJvQ5UwluM7YGE/4FDKW6mdkEAAA=>)</li></ul> | 16.43 μs | 20.21 μs | 1.23 | 0.11 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.Sort%28Int32%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.Sort&lt;Int32&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Buffers.Tests.ReadOnlySequenceTests&lt;Char&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[IterateForEachArray - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Buffers.Tests.ReadOnlySequenceTests(Char).IterateForEachArray.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Buffers/ReadOnlySequenceTests.cs#L46-#L47>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TMBR9R+I/+C0JZG3UtWNUZKItGxQolLRvCCE3uW2M/JFd21szIX47dlqVtZNQXiL7+Jx7j698MgOqLYIAafSz3+S+BAQytowXGVSKpCkJCmUkmC5aaZiA4Jg1RirzsuEhrHW3BFrorqBMnhBHmJfMQG5cN8IkCYPtRT+ISUBRuEV0YC9Bmy9UgK/5NljU2oDojO16Dag7/lB3Mtfkq+T1Am4tyBwa9M2kpHjVmRpAauBG4TXNyxEirf85yaycKLlmG+s4TEn9PZgoUTHe7GaqgOAHSf+QwDBHL4Ln/1M66BOTxV4hWI7qkYBpEJWpwyfCkTJRC9pU6c/8TjSza8P/qK/lhklow/WF2/BmSqqWdj11Kt3sKwT3bSOZb9SyrloZnpe1Zjnlc1RCeaSt8EO9Qla852pFOXtosDayrJe17XC9rQBdLmTzaI+f8US5zAAuVbVfHUdi6WQLQ0VFrkjh3qyPV9hLeudnyeuzZLBMLofJxbA/6PReDfqXveRlkgyTxLfQVgiK7AEIxc1PQbdhU9A7iMmLiKzqkw7xIVaxf8rfLFhwdSpUv1wkn5Az0JabFJ3rInx0kx0+unMR27hK51FMmlK+cHqDDGTB6wPih9VsvGV0Z4DE3zF3QTXknpmShNoND3R60MRkmytuhUxPPdU7XKc7E45omOGQBu/c6NyPpN5vvYSEUkce0xVnJqVb0NFf9kIy4OoEAAA=>)</li></ul> | 4.48 ns | 5.76 ns | 1.28 | 0.47 | False | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Buffers.Tests.ReadOnlySequenceTests%28Char%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Buffers.Tests.ReadOnlySequenceTests&lt;Char&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.IndexerSetReverse&lt;String&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Array - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.IndexerSetReverse(String).Array(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Indexer/IndexerSetReverse.cs#L27-#L34>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBOTtAmNcEUaCgQICnbeEEIXe2sfug9r79zaFeK3c+dEoUkl5BfLN56ZnVvtegVU1wgCpNHPfpP7EhDIdc14nkClSBwTL1dGghliLQ0T4B2zrpHKrOx4CLd6WALN9VBQJk+Ic8xKZiAzthphkvheMzn3QuJRFPYlOLA3oM1XKsB5vvXSVhsQg4Xi3GqZknqwlDk0gCmYBO4ANbxJDTJZXA3miLT1U/YAM3LxahT8i5DUcqHkLStqpJ3Ld2+hRMV4d1qpHLwfJP5DPMMsPfee/09poc9M5nuFYBmqRwKmQVSm9Z8I58oEPWhLpb/wO9E1rQ//k76RBZPQh+uM+/BWSqqecR11KQ1ghWCffSTrQm3aqlfgddlqllG+RiWUQ/oKP7ZbZPkHrraUs4cO6yNLRknfCjdNBWgXQnbTejy/C2WXBXCjqv3b8S5srCw1VFTkiuTUgNsrfxSNxmfR5Vl0sYlez6LJ7Hw6mF5G48l09DKKZlHkSuhaCIp2wAnF4qegjd8ZugQheRGQbXtSITzsU+hG+VsNNVifCtUvu09PyAnompsYbercf3STHT6360YL6zQOQtJZOeP4PTKQOW8PiGtWd3CR0X4DJO6OWUnRkHtmSuJr2zzQ8UETkiZTvBYyPs3U7nAd70JYomGGQ+y9s62zf5B2f3QS4ksdOExXnJmYNqCDv934rl/jBAAA>)</li></ul> | 173.61 ns | 228.81 ns | 1.32 | 0.00 | True | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.IndexerSetReverse%28String%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.IndexerSetReverse&lt;String&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7](https://github.com/dotnet/runtime/commit/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7)
Compare | [18c746aa09c5f50f615636500809fc32c1216efd](https://github.com/dotnet/runtime/commit/18c746aa09c5f50f615636500809fc32c1216efd)
Diff | [Diff](https://github.com/dotnet/runtime/compare/52e65a5fab8fc2a60a5eb4d23e00a4a4544232f7...18c746aa09c5f50f615636500809fc32c1216efd)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.IterateForEach&lt;String&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[ImmutableArray - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Collections.IterateForEach(String).ImmutableArray(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Iterate/IterateForEach.cs#L273-#L281>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBOTNAEiXJGGtAQICkneEEIXexsfug9r79zGFeK3s+dEoWkl5Bfrdj0zO7fe9Ry4rRAUaGef/WZ3BSCwy0rIfAmlYWnKgtw4Da6LlXZCQXCKukSus6LBIdzYbgE8t13FhX4EHGNWCAeZo2pMaBYGu+F5ELOAo6JDdESvwbqvXIHXfB+sautAdSZGSuIKo21n5gC5gyuDU54V71YOhd5edGZKVY5vJIwReR2uxD2M2OBVL/pnZFnpidE3YluRgNf6HkyMKoVsornJIfjB0j8scILgefD8f0xKfRY6PzCUyNA8IAgLqnR1+IQ4Ni5qAZsZ+0XeqqZ1bfCf7FRvhYY2WC/cBjc32rS066EzTR+mRKBnG8pia9Z12crwoqityLhcoFHGZ9oSP9YbFPm1NBsuxX2Ta0Nb9pZtK0x3JSCthW5m9nSKJ4ZWBnBtysPpdCPWRFs5rkp2wXIaaL9dYS/p9c+St2fJYJ28GSXD0SDp9F+fD3rD4cskGSWJL2ErpTjSgDOO25+K78JG0DuI2YuIbepHFeLjVsV+lL9VUAHplGh+0VY9AS/BVtKlSK7z8MFN9vnxLe3flpT6UcwaKS+cXqEAncv6mPHNagJvGekdIPN3zAqOjt0JV7DQUvPApkdOzHaZkZXS6WNP9T5v070JAjrhJKTBB2od/UfqQ+gpLNQ28jlbSuFSvgMb/QU9DEIb6QQAAA==>)</li></ul> | 147.73 ns | 192.26 ns | 1.30 | 0.00 | True | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/12_05_2023/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Collections.IterateForEach%28String%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.IterateForEach&lt;String&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-2d3ac721-eafe-4eaf-bb29-a532b30140a5d25a1705ac048b99e/dbaad52a-d29c-4c88-9799-616287e90dae.zip?sv=2021-08-06&se=2023-12-28T15%3A54%3A18Z&sr=c&sp=rl&sig=1oX%2FBAy7uFr4LkjGUVdzwRyVHwD1tTWnGD9Xn1EBl%2B4%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-195fded8-7622-4a64-b0ba-07e6ccfb2daa03f1b90dcfa4af596/2a1a474f-3fc6-443c-9bae-de12e8c375f0.zip?sv=2021-08-06&se=2023-12-29T09%3A27%3A17Z&sr=c&sp=rl&sig=n0%2FH4Ri9ghAMlYA%2BD7im%2Bt%2B4Pyw8CY75Tuu1k4Xu880%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Alternative take on #104458. 

VN doesn't always give PHI defs the best possible values (in particular if there are backedge PHI args). Revise VN to run intg a "loop-respecting" RPO where we don't visit any loop successors until all loop blocks have been visited. Once the loop is done, update the header PHI VNs since all PHI arg VNs are now known.

Then look for equivalent PHI defs in copy prop and enable copy prop when two locals have the same values at the head of a loop.

Addresses the regression case noted in #95645 (comment) where cross-block morph's copy prop plus loop bottom testing has created some unnecessary loop-carried values.

Closes #95645.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch FYI

File: src/coreclr/jit/valuenum.cpp [hunk 1]
```diff
@@ -6770,6 +6770,138 @@ const char* ValueNumStore::VNRelationString(VN_RELATION_KIND vrk)
...
+//    Normally if vn1 != vn2 then we cannot say if the two values
+//    are equivalent or different. PhiDef VNs don't represent the
+//    phi def values in this way, and can be proven equivalent even
+//    for different value numbers.
+//
+bool ValueNumStore::AreVNsEquivalent(ValueNum vn1, ValueNum vn2)
+{
+    if (vn1 == vn2)
+    {
+        return true;
```
Comment (EgorBo) [inline src/coreclr/jit/valuenum.cpp:6800]: is it fine if boths are NoVN ? I mean can the caller assume it can apply some opts

Comment (AndyAyersMS) [reply src/coreclr/jit/valuenum.cpp:6800]: I expect callers to screen these out. I guess I should add asserts here.

**Comment by AndyAyersMS** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=738217&view=ms.vss-build-web.run-extensions-tab). TP is indeed down a bit from the other PR.

Looks like there's a set of novel test failures on arm/arm64.

**Comment by AndyAyersMS** [comment]
The NAOT failure is looking suspiciously like another case of #88091. In `System.Uri:CheckAuthorityHelper` phi refinement allows RBO to jump thread both sides of a block that has a memory phi (w/o this change it just does one side); this converts a CSE def into a use. We set BBF_NO_CSE_IN on the block, but it has no effect as that block is now unreachable. I suspect this new CSE use is not valid but haven't gotten that far.

Need to try and extract this pattern as a repro case. Not sure why it is seemingly arm/naot only yet, maybe the CSE only happens there.

**Comment by AndyAyersMS** [comment]
Repro case is something like the following
```C#
using System.Runtime.CompilerServices;

unsafe
{
    string example = "./";
    fixed (char* p = example)
    {
        int result = Problem(p, 0, example.Length);
        Console.WriteLine($"result={result}");
    }
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void Expose(ref int x)
{ }

static unsafe int Problem(char* pString, int idx, int length)
{
    bool dotFound = false;
    int end = 0;
    Expose(ref end);
    for (end = idx; end < length; ++end)
    {
        if (dotFound && (pString[end] == '/' || pString[end] == '?' || pString[end] == '#'))
            break;
        else if (end < (idx + 2) && pString[end] == '.')
        {
            // allow one or two dots
            dotFound = true;
        }
        else
        {
            //failure
            return -1;
        }
    }

    return 0;
}
```
(if `end` is not exposed, other things block jump threading).

Here RBO can see `dotFound` is false if we've just entered the loop and also can now see it is true if we've come around the backedge. So the flow is now more like
```C#
    while (true)
    {
        if (end < (idx + 2) && pString[end] == '.')
        {
            //
        }
        else
        {
            return -1;
        }

        end++;

        if (end < length) break;

        if (pString[end] == '/' || pString[end] == '?' || pString[end] == '#')
        {
            break;
        }
    }
```
and CSE commons up all the `pString[end]` occurrences despite the increment of the index in between, since they all have the same VNs (in the initial loop order they indeed all have the same value, but we don't CSE there because the first reads are conditional).

One possible fix is to rework the `BBF_NO_CSE_IN` mechanism to be a flow edge annotation instead of a block annotation. When we jump thread past a memory PHI we could mark all the new pred edges this way and block CSE dataflow. But we currently don't have any flow edge annotations. And this may not be sufficiently durable, say if we can subsequently re-thread one of those new edges.

Another though is to try and somehow capture the dependence of the memory load VNs on the VN for end, but I'm not sure how to approach that.

**Comment by AndyAyersMS** [comment]
Though not particularly elegant, [ccdca2a](https://github.com/dotnet/runtime/pull/104752/commits/ccdca2a74c065f2ae0f86fecdfc783cac788af5c) has fairly minimal diffs on its own. Hopefully this forestalls the need to do something more elaborate to avoid RBO tripping up CSE.

**Comment by AndyAyersMS** [comment]
[Latest diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741693&view=ms.vss-build-web.run-extensions-tab)

**Comment by AndyAyersMS** [comment]
Libraries stress failures look like https://github.com/dotnet/runtime/issues/104153, https://github.com/dotnet/runtime/issues/103459, and https://github.com/dotnet/runtime/issues/102706.

runtime jitstress failure (nativeruntimeeventsource) not clear

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
TP cost is all in copyprop, I think we can get some/most of this back by reducing the number of candidates it considers.

File: src/coreclr/jit/valuenum.cpp [hunk 2]
```diff
@@ -6770,6 +6770,138 @@ const char* ValueNumStore::VNRelationString(VN_RELATION_KIND vrk)
 }
 #endif
 
+bool ValueNumStore::IsVNPhiDef(ValueNum vn)
```
Comment (jakobbotsch) [inline src/coreclr/jit/valuenum.cpp:6773]: This looks unused

**Review by jakobbotsch — APPROVED** [review]
LGTM

File: src/coreclr/jit/valuenum.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/valuenum.cpp:6773]: Yeah, I'll remove it soon, if I don't find some other use for it.
