### PR TITLE
JIT: fix liveness in throw helper blocks

### LINKED ISSUE #123929: Assert failure: !CREATE_CHECK_STRING(pMT && pMT->Validate())
**Failed in:** [runtime-coreclr r2r-extra 20260201.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1275701)

**Failed tests:**
```
R2R-CG2 windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open
- baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd
R2R-CG2 windows x64 Checked gcstress0xc @ Windows.10.Amd64.Open
- baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd
R2R-CG2 windows arm64 Checked gcstress0xc @ Windows.11.Arm64.Open
- baseservices/exceptions/regressions/V1/SEH/VJ/UserExceptionThread/UserExceptionThread.cmd
- baseservices/exceptions/unittests/InnerFinally/InnerFinally.cmd
- baseservices/exceptions/unittests/InnerFinallyAndCatch/InnerFinallyAndCatch.cmd
- baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd

```

**Error message:**
```

Assert failure(PID 696 [0x000002b8], Thread: 5448 [0x1548]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

CORECLR! Object::Validate + 0xA9 (0x73930889)
CORECLR! WKS::GCHeap::Relocate + 0x51 (0x73d9f4f1)
CORECLR! GcEnumObject + 0x161 (0x73ac1641)
CORECLR! EnumGcRefsX86 + 0xEBE (0x737fa6de)
CORECLR! EECodeManager::EnumGcRefs + 0x1D2 (0x737f97d2)
CORECLR! GcStackCrawlCallBack + 0x2DB (0x73ac1b0b)
CORECLR! Thread::StackWalkFramesEx + 0x223 (0x7398c553)
CORECLR! Thread::StackWalkFrames + 0x13B (0x7398c29b)
CORECLR! ScanStackRoots + 0x31D (0x73abeb2d)
CORECLR! GCToEEInterface::GcScanRoots + 0x16E (0x73abc07e)
    File: D:_work1ssrccoreclrmobject.cpp:548
    Image: C:hwAF0B094Bpcorerun.exe


Return code:      1
Raw output file:      C:hwAF0B094BwA5800946uploadsunittestsStrSwitchFinallyoutput.txt
Raw output:
BEGIN EXECUTION
StrSwitchFinally.dll
        1 file(s) copied.
 3:47:44.45
Response file: C:hwAF0B094BwA5800946easeservicesexceptionsunittestsStrSwitchFinallyStrSwitchFinally.dll.rsp
C:hwAF0B094BwA5800946easeservicesexceptionsunittestsStrSwitchFinallyIL-CG2StrSwitchFinally.dll
-O
-o:C:hwAF0B094BwA5800946easeservicesexceptionsunittestsStrSwitchFinallyStrSwitchFinally.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwAF0B094BpSystem.*.dll
-r:C:hwAF0B094BpMicrosoft.*.dll
-r:C:hwAF0B094Bp\xunit.*.dll
-r:C:hwAF0B094Bpmscorlib.dll
-r:C:hwAF0B094Bp
etstandard.dll
"Running CrossGen2:  "C:hwAF0B094Bpcrossgen2crossgen2.exe" @"C:hwAF0B094BwA5800946easeservicesexceptionsunittestsStrSwitchFinallyStrSwitchFinally.dll.rsp"   -r:C:hwAF0B094BwA5800946easeservicesexceptionsaseservices-exceptionsIL-CG2*.dll  -r:C:hwAF0B094BwA5800946easeservicesexceptionsunittestsStrSwitchFinallyIL-CG2*.dll"
Emitting R2R PE file: C:hwAF0B094BwA5800946easeservicesexceptionsunittestsStrSwitchFinallyStrSwitchFinally.dll
"Running R2RDump:  "dotnet" "C:hwAF0B094Bp
2rdump
2rdump.dll" --header --sc --in C:hwAF0B094BwA5800946easeservicesexceptionsunittestsStrSwitchFinallyStrSwitchFinally.dll --out C:hwAF0B094BwA5800946easeservicesexceptionsunittestsStrSwitchFinallyStrSwitchFinally.dll.r2rdump --val"
 3:47:44.99
 "C:hwAF0B094Bpcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  StrSwitchFinally.dll 
-----------------------------
StrSwitchFinalTest
-----------------------------
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwAF0B094BwA5800946easeservicesexceptionsaseservices-exceptions../unittests/StrSwitchFinally/StrSwitchFinally.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/arcade/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/arcade/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor166|0_167(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/v-bibu/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/v-bibu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2/2/2026, 7:27:05.614 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_jitminopts_heapverify1 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","System.StageName":"Build","System.StageAttempt":"1","BuildId":"1275869","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"35615398","configuration":"Checked-gcstress0xc_jitminopts_heapverify1","System.JobName":"__default","System.JobAttempt":"1","BuildNumber":"20260201.1","operatingSystem":"OSX.26.Arm64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"arm64","Project":"public","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","Reason":"Schedule","DefinitionId":"141"} | Schedule
2/2/2026, 7:27:05.38 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","BuildId":"1275869","operatingSystem":"OSX.26.Arm64.Open","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","architecture":"arm64","System.StageName":"Build","BuildNumber":"20260201.1","System.JobAttempt":"1","configuration":"Checked-gcstress0xc_disabler2r","System.PhaseAttempt":"1","System.StageAttempt":"1","Project":"public","Reason":"Schedule","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","AzurePipelinesTestRunId":"35615390","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","System.JobName":"__default","DefinitionId":"141"} | Schedule
2/2/2026, 7:27:05.177 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_tailcallstress | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"BuildNumber":"20260201.1","System.JobAttempt":"1","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","AzurePipelinesTestRunId":"35615396","operatingSystem":"OSX.26.Arm64.Open","configuration":"Checked-gcstress0xc_tailcallstress","Reason":"Schedule","DefinitionId":"141","System.StageAttempt":"1","System.StageName":"Build","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","architecture":"arm64","Project":"public","BuildId":"1275869","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","System.PhaseAttempt":"1","System.JobName":"__default"} | Schedule
2/2/2026, 7:27:04.924 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_jitstress2 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"Reason":"Schedule","Project":"public","DefinitionId":"141","System.StageName":"Build","BuildNumber":"20260201.1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","configuration":"Checked-gcstress0xc_jitstress2","BuildId":"1275869","architecture":"arm64","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","System.StageAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","operatingSystem":"OSX.26.Arm64.Open","System.JobAttempt":"1","AzurePipelinesTestRunId":"35615400","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","System.JobName":"__default"} | Schedule
2/2/2026, 7:27:04.799 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_jitstress1 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"BuildNumber":"20260201.1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"141","operatingSystem":"OSX.26.Arm64.Open","architecture":"arm64","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","AzurePipelinesTestRunId":"35615402","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","Reason":"Schedule","Project":"public","System.PhaseAttempt":"1","BuildId":"1275869","DefinitionName":"runtime-coreclr   crossgen2-composite gcstress","System.JobName":"__default","System.StageName":"Build","configuration":"Checked-gcstress0xc_jitstress1","System.StageAttempt":"1"} | Schedule
2/2/2026, 7:27:04.38 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r_heapverify1 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"configuration":"Checked-gcstress0xc_disabler2r_heapverify1","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","System.JobName":"__default","DefinitionId":"141","System.StageAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","architecture":"arm64","System.StageName":"Build","Project":"public","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","AzurePipelinesTestRunId":"35615394","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","System.PhaseAttempt":"1","operatingSystem":"OSX.26.Arm64.Open","BuildId":"1275869","BuildNumber":"20260201.1"} | Schedule
2/2/2026, 3:39:11.288 AM | runtime-coreclr r2r-extra | Checked-gcstress0xc | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"AzurePipelinesTestRunId":"35610496","System.PhaseName":"run_test_p1_R2R_osx_arm64_checked","configuration":"Checked-gcstress0xc","System.PhaseAttempt":"1","DefinitionId":"114","architecture":"arm64","System.StageAttempt":"1","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr   r2r-extra","operatingSystem":"OSX.26.Arm64.Open","BuildId":"1275701","BuildNumber":"20260201.1","System.JobName":"__default","System.JobAttempt":"1","System.StageName":"Build","System.JobId":"99f15f99-448d-5593-a271-dbdf553789a6","Reason":"Schedule"} | Schedule
2/1/2026, 10:17:43.072 PM | runtime-coreclr gcstress-extra | Checked-gcstress0xc_disabler2r_heapverify1 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"Reason":"Schedule","System.PhaseAttempt":"1","DefinitionId":"113","operatingSystem":"OSX.26.Arm64.Open","AzurePipelinesTestRunId":"35602926","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_arm64_checked","System.StageName":"Build","BuildNumber":"20260201.1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.StageAttempt":"1","BuildId":"1275580","DefinitionName":"runtime-coreclr   gcstress-extra","System.JobAttempt":"1","configuration":"Checked-gcstress0xc_disabler2r_heapverify1","architecture":"arm64","Project":"public"} | Schedule
2/1/2026, 10:17:42.838 PM | runtime-coreclr gcstress-extra | Checked-gcstress0xc_disabler2r | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"DefinitionName":"runtime-coreclr   gcstress-extra","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","BuildNumber":"20260201.1","DefinitionId":"113","System.JobName":"__default","System.StageName":"Build","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Project":"public","configuration":"Checked-gcstress0xc_disabler2r","System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobAttempt":"1","architecture":"arm64","BuildId":"1275580","AzurePipelinesTestRunId":"35602934","operatingSystem":"OSX.26.Arm64.Open","System.PhaseAttempt":"1","System.StageAttempt":"1"} | Schedule
2/1/2026, 10:17:42.706 PM | runtime-coreclr gcstress-extra | Checked-gcstress0xc_jitstress1 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","DefinitionId":"113","System.StageName":"Build","BuildNumber":"20260201.1","Reason":"Schedule","AzurePipelinesTestRunId":"35602922","BuildId":"1275580","DefinitionName":"runtime-coreclr   gcstress-extra","configuration":"Checked-gcstress0xc_jitstress1","architecture":"arm64","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","Project":"public","operatingSystem":"OSX.26.Arm64.Open","System.PhaseAttempt":"1","System.StageAttempt":"1"} | Schedule
2/1/2026, 10:17:42.348 PM | runtime-coreclr gcstress-extra | Checked-gcstress0xc_jitstress2 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageAttempt":"1","BuildNumber":"20260201.1","Project":"public","AzurePipelinesTestRunId":"35602928","System.StageName":"Build","DefinitionName":"runtime-coreclr   gcstress-extra","System.PhaseName":"run_test_p1__osx_arm64_checked","DefinitionId":"113","Reason":"Schedule","configuration":"Checked-gcstress0xc_jitstress2","System.JobName":"__default","architecture":"arm64","System.JobAttempt":"1","operatingSystem":"OSX.26.Arm64.Open","BuildId":"1275580","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e"} | Schedule
2/1/2026, 10:17:42.118 PM | runtime-coreclr gcstress-extra | Checked-gcstress0xc_tailcallstress | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"operatingSystem":"OSX.26.Arm64.Open","System.JobName":"__default","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildId":"1275580","System.StageAttempt":"1","configuration":"Checked-gcstress0xc_tailcallstress","architecture":"arm64","System.StageName":"Build","DefinitionId":"113","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","BuildNumber":"20260201.1","Reason":"Schedule","Project":"public","DefinitionName":"runtime-coreclr   gcstress-extra","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"35602932","System.PhaseName":"run_test_p1__osx_arm64_checked"} | Schedule
2/1/2026, 2:12:38.298 PM | runtime-coreclr gcstress0x3-gcstress0xc | Checked-gcstress0xc | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageName":"Build","DefinitionName":"runtime-coreclr   gcstress0x3-gcstress0xc","configuration":"Checked-gcstress0xc","Reason":"Schedule","DefinitionId":"112","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_arm64_checked","architecture":"arm64","System.PhaseAttempt":"1","BuildId":"1275418","System.StageAttempt":"1","BuildNumber":"20260201.1","System.JobName":"__default","operatingSystem":"OSX.26.Arm64.Open","AzurePipelinesTestRunId":"35596368","Project":"public","System.JobAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e"} | Schedule
2/1/2026, 2:12:38.126 PM | runtime-coreclr gcstress0x3-gcstress0xc | Checked-gcstress0x3 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.PhaseName":"run_test_p1__osx_arm64_checked","System.StageName":"Build","System.StageAttempt":"1","AzurePipelinesTestRunId":"35596366","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20260201.1","Reason":"Schedule","System.JobName":"__default","Project":"public","System.JobAttempt":"1","BuildId":"1275418","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","DefinitionName":"runtime-coreclr   gcstress0x3-gcstress0xc","System.PhaseAttempt":"1","configuration":"Checked-gcstress0x3","architecture":"arm64","operatingSystem":"OSX.26.Arm64.Open","DefinitionId":"112"} | Schedule
2/1/2026, 7:34:42.672 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_jitminopts_heapverify1 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.JobName":"__default","configuration":"Checked-gcstress0xc_jitminopts_heapverify1","System.StageName":"Build","BuildId":"1275291","Reason":"Schedule","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"35592642","System.JobAttempt":"1","Project":"public","operatingSystem":"OSX.26.Arm64.Open","System.StageAttempt":"1","DefinitionId":"141","BuildNumber":"20260131.1","System.PhaseAttempt":"1","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5"} | Schedule
2/1/2026, 7:34:42.563 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_jitstress1 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.JobName":"__default","DefinitionId":"141","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","DefinitionName":"runtime-coreclr   crossgen2-composite gcstress","Reason":"Schedule","Project":"public","BuildNumber":"20260131.1","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","BuildId":"1275291","configuration":"Checked-gcstress0xc_jitstress1","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"35592636","operatingSystem":"OSX.26.Arm64.Open","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","System.StageName":"Build","architecture":"arm64"} | Schedule
2/1/2026, 7:34:42.122 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_jitstress2 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","architecture":"arm64","BuildNumber":"20260131.1","configuration":"Checked-gcstress0xc_jitstress2","System.JobName":"__default","DefinitionId":"141","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","System.JobAttempt":"1","System.PhaseAttempt":"1","BuildId":"1275291","Reason":"Schedule","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","Project":"public","AzurePipelinesTestRunId":"35592640","operatingSystem":"OSX.26.Arm64.Open","System.StageAttempt":"1"} | Schedule
2/1/2026, 7:34:42 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"architecture":"arm64","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","DefinitionId":"141","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","Project":"public","System.JobName":"__default","Reason":"Schedule","System.StageAttempt":"1","System.JobAttempt":"1","BuildNumber":"20260131.1","configuration":"Checked-gcstress0xc_disabler2r","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","BuildId":"1275291","operatingSystem":"OSX.26.Arm64.Open","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","AzurePipelinesTestRunId":"35592644"} | Schedule
2/1/2026, 7:34:41.843 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r_heapverify1 | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"architecture":"arm64","System.JobAttempt":"1","BuildId":"1275291","System.JobName":"__default","DefinitionName":"runtime-coreclr   crossgen2-composite gcstress","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"141","System.StageName":"Build","configuration":"Checked-gcstress0xc_disabler2r_heapverify1","Project":"public","Reason":"Schedule","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","System.PhaseAttempt":"1","System.StageAttempt":"1","BuildNumber":"20260131.1","operatingSystem":"OSX.26.Arm64.Open","AzurePipelinesTestRunId":"35592646"} | Schedule
2/1/2026, 7:34:41.383 AM | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_tailcallstress | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"Project":"public","Reason":"Schedule","DefinitionId":"141","BuildId":"1275291","System.StageAttempt":"1","System.JobName":"__default","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20260131.1","System.StageName":"Build","configuration":"Checked-gcstress0xc_tailcallstress","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","operatingSystem":"OSX.26.Arm64.Open","System.JobAttempt":"1","AzurePipelinesTestRunId":"35592634","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","System.PhaseAttempt":"1"} | Schedule
2/1/2026, 3:29:03.112 AM | runtime-coreclr r2r-extra | Checked-gcstress0xc | osx.26.arm64.open | arm64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"BuildId":"1275170","System.JobId":"99f15f99-448d-5593-a271-dbdf553789a6","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","System.StageAttempt":"1","System.PhaseName":"run_test_p1_R2R_osx_arm64_checked","DefinitionId":"114","Project":"public","System.StageName":"Build","DefinitionName":"runtime-coreclr   r2r-extra","architecture":"arm64","operatingSystem":"OSX.26.Arm64.Open","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"35587966","configuration":"Checked-gcstress0xc","System.JobAttempt":"1","BuildNumber":"20260131.1","System.JobName":"__default"} | Schedule
11/24/2025, 4:48:35.327 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageName":"Build","operatingSystem":"AzureLinux.3.Amd64.Open","System.StageAttempt":"1","architecture":"x64","System.JobAttempt":"1","AzurePipelinesTestRunId":"33530638","DefinitionId":"316","BuildId":"1211193","System.JobName":"__default","DefinitionName":"runtime-interpreter","BuildNumber":"20251124.1","Project":"public","configuration":"Checked-interpmode1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__linux_x64_checked","Reason":"Schedule","System.PhaseAttempt":"1","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5"} | Schedule
11/24/2025, 4:48:30.935 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageName":"Build","operatingSystem":"AzureLinux.3.Amd64.Open","System.StageAttempt":"1","architecture":"x64","System.JobAttempt":"1","AzurePipelinesTestRunId":"33530636","DefinitionId":"316","BuildId":"1211193","System.JobName":"__default","DefinitionName":"runtime-interpreter","BuildNumber":"20251124.1","Project":"public","configuration":"Checked-interpmode1_no_tiered_compilation","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__linux_x64_checked","Reason":"Schedule","System.PhaseAttempt":"1","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5"} | Schedule
11/21/2025, 4:46:09.753 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"operatingSystem":"AzureLinux.3.Amd64.Open","System.JobName":"__default","AzurePipelinesTestRunId":"33482320","System.JobAttempt":"1","System.PhaseName":"run_test_p1__linux_x64_checked","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","DefinitionName":"runtime-interpreter","BuildId":"1209667","Reason":"Schedule","configuration":"Checked-interpmode1","System.PhaseAttempt":"1","architecture":"x64","System.StageAttempt":"1","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","DefinitionId":"316","BuildNumber":"20251121.1"} | Schedule
11/21/2025, 4:44:10.064 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageAttempt":"1","System.StageName":"Build","Reason":"Schedule","System.JobName":"__default","DefinitionName":"runtime-interpreter","DefinitionId":"316","System.PhaseName":"run_test_p1__linux_x64_checked","architecture":"x64","Project":"public","BuildNumber":"20251121.1","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"33482308","configuration":"Checked-interpmode1_no_tiered_compilation","BuildId":"1209667","operatingSystem":"AzureLinux.3.Amd64.Open","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5"} | Schedule
11/19/2025, 4:47:05.658 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"BuildId":"1207530","Project":"public","System.StageName":"Build","operatingSystem":"AzureLinux.3.Amd64.Open","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","Reason":"Schedule","System.JobName":"__default","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"33424960","BuildNumber":"20251119.1","System.PhaseName":"run_test_p1__linux_x64_checked","configuration":"Checked-interpmode1","DefinitionId":"316","System.StageAttempt":"1","System.JobAttempt":"1","DefinitionName":"runtime-interpreter","System.PhaseAttempt":"1"} | Schedule
11/19/2025, 4:46:57.922 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageAttempt":"1","System.JobAttempt":"1","Project":"public","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"33424954","architecture":"x64","BuildId":"1207530","System.JobName":"__default","operatingSystem":"AzureLinux.3.Amd64.Open","DefinitionName":"runtime-interpreter","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"316","BuildNumber":"20251119.1","System.PhaseName":"run_test_p1__linux_x64_checked","configuration":"Checked-interpmode1_no_tiered_compilation","Reason":"Schedule"} | Schedule
11/19/2025, 3:16:46.683 PM | runtime-interpreter | Checked-interpmode1 | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"BuildId":"1207530","System.PhaseAttempt":"1","System.StageName":"Build","DefinitionName":"runtime-interpreter","configuration":"Checked-interpmode1","System.JobAttempt":"1","Project":"public","System.StageAttempt":"1","architecture":"x64","BuildNumber":"20251119.1","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","operatingSystem":"OSX.13.Amd64.Open","AzurePipelinesTestRunId":"33423504","DefinitionId":"316","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked"} | Schedule
11/19/2025, 3:12:27.354 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.PhaseName":"run_test_p1__osx_x64_checked","System.PhaseAttempt":"1","operatingSystem":"OSX.13.Amd64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildId":"1207530","System.StageAttempt":"1","AzurePipelinesTestRunId":"33423494","System.StageName":"Build","Reason":"Schedule","DefinitionName":"runtime-interpreter","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobAttempt":"1","BuildNumber":"20251119.1","architecture":"x64","Project":"public","configuration":"Checked-interpmode1_no_tiered_compilation","System.JobName":"__default","DefinitionId":"316"} | Schedule
11/17/2025, 5:16:18.402 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"Reason":"Schedule","BuildId":"1205459","System.JobName":"__default","operatingSystem":"AzureLinux.3.Amd64.Open","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","configuration":"Checked-interpmode1","BuildNumber":"20251117.1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__linux_x64_checked","DefinitionId":"316","architecture":"x64","AzurePipelinesTestRunId":"33367336","System.StageName":"Build","Project":"public","System.PhaseAttempt":"1","System.StageAttempt":"1","System.JobAttempt":"1","DefinitionName":"runtime-interpreter"} | Schedule
11/17/2025, 4:59:25.142 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"BuildId":"1205459","BuildNumber":"20251117.1","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-interpmode1_no_tiered_compilation","System.PhaseName":"run_test_p1__linux_x64_checked","System.StageName":"Build","System.StageAttempt":"1","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","operatingSystem":"AzureLinux.3.Amd64.Open","Reason":"Schedule","DefinitionId":"316","System.JobAttempt":"1","DefinitionName":"runtime-interpreter","AzurePipelinesTestRunId":"33367086"} | Schedule
11/17/2025, 3:05:24.325 PM | runtime-interpreter | Checked-interpmode1 | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"configuration":"Checked-interpmode1","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","architecture":"x64","Project":"public","BuildNumber":"20251117.1","BuildId":"1205459","System.JobAttempt":"1","DefinitionId":"316","System.PhaseName":"run_test_p1__osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.StageAttempt":"1","System.StageName":"Build","Reason":"Schedule","System.PhaseAttempt":"1","operatingSystem":"OSX.13.Amd64.Open","AzurePipelinesTestRunId":"33365674","DefinitionName":"runtime-interpreter"} | Schedule
11/17/2025, 2:57:41.775 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.JobAttempt":"1","operatingSystem":"OSX.13.Amd64.Open","BuildNumber":"20251117.1","System.StageName":"Build","architecture":"x64","DefinitionId":"316","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.StageAttempt":"1","System.PhaseName":"run_test_p1__osx_x64_checked","configuration":"Checked-interpmode1_no_tiered_compilation","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","DefinitionName":"runtime-interpreter","Project":"public","Reason":"Schedule","BuildId":"1205459","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"33365538"} | Schedule
11/14/2025, 4:44:57.764 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.PhaseAttempt":"1","BuildId":"1203312","System.PhaseName":"run_test_p1__linux_x64_checked","operatingSystem":"AzureLinux.3.Amd64.Open","architecture":"x64","BuildNumber":"20251114.1","Project":"public","configuration":"Checked-interpmode1","DefinitionName":"runtime-interpreter","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageAttempt":"1","System.JobName":"__default","DefinitionId":"316","System.StageName":"Build","Reason":"Schedule","AzurePipelinesTestRunId":"33311540","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","System.JobAttempt":"1"} | Schedule
11/14/2025, 4:42:22.49 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","System.PhaseName":"run_test_p1__linux_x64_checked","DefinitionName":"runtime-interpreter","BuildNumber":"20251114.1","Project":"public","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","DefinitionId":"316","AzurePipelinesTestRunId":"33311486","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"AzureLinux.3.Amd64.Open","System.StageAttempt":"1","System.JobName":"__default","configuration":"Checked-interpmode1_no_tiered_compilation","BuildId":"1203312","System.PhaseAttempt":"1","System.StageName":"Build"} | Schedule
11/12/2025, 4:54:28.983 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","architecture":"x64","System.PhaseName":"run_test_p1__linux_x64_checked","Project":"public","System.StageAttempt":"1","System.PhaseAttempt":"1","operatingSystem":"AzureLinux.3.Amd64.Open","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","AzurePipelinesTestRunId":"33237596","Reason":"Schedule","DefinitionId":"316","configuration":"Checked-interpmode1","BuildId":"1200882","System.JobName":"__default","DefinitionName":"runtime-interpreter","BuildNumber":"20251112.1"} | Schedule
11/12/2025, 4:52:02.682 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.JobName":"__default","DefinitionName":"runtime-interpreter","configuration":"Checked-interpmode1_no_tiered_compilation","System.PhaseAttempt":"1","System.StageName":"Build","BuildId":"1200882","AzurePipelinesTestRunId":"33237564","Project":"public","BuildNumber":"20251112.1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"316","System.PhaseName":"run_test_p1__linux_x64_checked","Reason":"Schedule","architecture":"x64","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","operatingSystem":"AzureLinux.3.Amd64.Open","System.StageAttempt":"1"} | Schedule
11/12/2025, 2:57:12.319 PM | runtime-interpreter | Checked-interpmode1 | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"AzurePipelinesTestRunId":"33235224","System.PhaseName":"run_test_p1__osx_x64_checked","architecture":"x64","DefinitionName":"runtime-interpreter","System.PhaseAttempt":"1","System.StageAttempt":"1","DefinitionId":"316","BuildNumber":"20251112.1","Project":"public","System.JobName":"__default","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Reason":"Schedule","BuildId":"1200882","operatingSystem":"OSX.13.Amd64.Open","configuration":"Checked-interpmode1"} | Schedule
11/12/2025, 2:53:31.637 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageName":"Build","System.StageAttempt":"1","DefinitionName":"runtime-interpreter","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","System.JobName":"__default","operatingSystem":"OSX.13.Amd64.Open","System.JobAttempt":"1","AzurePipelinesTestRunId":"33235200","System.PhaseAttempt":"1","BuildNumber":"20251112.1","configuration":"Checked-interpmode1_no_tiered_compilation","BuildId":"1200882","architecture":"x64","DefinitionId":"316","Reason":"Schedule","System.PhaseName":"run_test_p1__osx_x64_checked","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823"} | Schedule
11/10/2025, 4:44:48.529 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageName":"Build","System.PhaseName":"run_test_p1__linux_x64_checked","System.StageAttempt":"1","System.JobAttempt":"1","architecture":"x64","configuration":"Checked-interpmode1","System.JobName":"__default","Project":"public","System.PhaseAttempt":"1","BuildId":"1198715","BuildNumber":"20251110.1","AzurePipelinesTestRunId":"33177324","DefinitionId":"316","operatingSystem":"AzureLinux.3.Amd64.Open","DefinitionName":"runtime-interpreter","Reason":"Schedule","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
11/10/2025, 4:42:20.83 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"architecture":"x64","Project":"public","operatingSystem":"AzureLinux.3.Amd64.Open","System.StageName":"Build","BuildNumber":"20251110.1","BuildId":"1198715","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__linux_x64_checked","System.JobName":"__default","AzurePipelinesTestRunId":"33177276","System.StageAttempt":"1","DefinitionId":"316","configuration":"Checked-interpmode1_no_tiered_compilation","System.JobAttempt":"1","System.PhaseAttempt":"1","Reason":"Schedule","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","DefinitionName":"runtime-interpreter"} | Schedule
11/5/2025, 4:49:28.024 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"BuildId":"1194570","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageAttempt":"1","AzurePipelinesTestRunId":"33064472","DefinitionId":"316","Project":"public","operatingSystem":"AzureLinux.3.Amd64.Open","Reason":"Schedule","System.StageName":"Build","System.JobName":"__default","System.PhaseName":"run_test_p1__linux_x64_checked","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","architecture":"x64","System.JobAttempt":"1","DefinitionName":"runtime-interpreter","configuration":"Checked-interpmode1","BuildNumber":"20251105.1"} | Schedule
11/5/2025, 4:48:56.818 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageAttempt":"1","System.PhaseAttempt":"1","BuildId":"1194570","DefinitionName":"runtime-interpreter","BuildNumber":"20251105.1","AzurePipelinesTestRunId":"33064468","configuration":"Checked-interpmode1_no_tiered_compilation","System.JobAttempt":"1","System.PhaseName":"run_test_p1__linux_x64_checked","System.JobName":"__default","architecture":"x64","operatingSystem":"AzureLinux.3.Amd64.Open","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"316","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","Reason":"Schedule","Project":"public"} | Schedule
11/3/2025, 4:48:05.651 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.PhaseAttempt":"1","DefinitionName":"runtime-interpreter","DefinitionId":"316","System.PhaseName":"run_test_p1__linux_x64_checked","System.JobAttempt":"1","System.JobName":"__default","Reason":"Schedule","configuration":"Checked-interpmode1","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","BuildNumber":"20251103.1","AzurePipelinesTestRunId":"32980058","operatingSystem":"AzureLinux.3.Amd64.Open","System.StageName":"Build","System.StageAttempt":"1","BuildId":"1191892","architecture":"x64","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
11/3/2025, 4:47:21.384 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"operatingSystem":"AzureLinux.3.Amd64.Open","Reason":"Schedule","System.PhaseName":"run_test_p1__linux_x64_checked","DefinitionId":"316","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-interpreter","Project":"public","architecture":"x64","AzurePipelinesTestRunId":"32980050","configuration":"Checked-interpmode1_no_tiered_compilation","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","System.StageName":"Build","System.JobAttempt":"1","System.StageAttempt":"1","BuildNumber":"20251103.1","System.JobName":"__default","BuildId":"1191892"} | Schedule
11/3/2025, 2:50:48.297 PM | runtime-interpreter | Checked-interpmode1 | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"AzurePipelinesTestRunId":"32978008","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageAttempt":"1","operatingSystem":"OSX.13.Amd64.Open","Reason":"Schedule","Project":"public","DefinitionName":"runtime-interpreter","DefinitionId":"316","architecture":"x64","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_x64_checked","BuildId":"1191892","System.JobName":"__default","BuildNumber":"20251103.1","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.StageName":"Build","System.PhaseAttempt":"1","configuration":"Checked-interpmode1"} | Schedule
11/3/2025, 2:47:28.896 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageAttempt":"1","architecture":"x64","AzurePipelinesTestRunId":"32977952","System.PhaseName":"run_test_p1__osx_x64_checked","operatingSystem":"OSX.13.Amd64.Open","BuildId":"1191892","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","System.JobName":"__default","Project":"public","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","DefinitionName":"runtime-interpreter","DefinitionId":"316","configuration":"Checked-interpmode1_no_tiered_compilation","System.StageName":"Build","System.PhaseAttempt":"1","BuildNumber":"20251103.1"} | Schedule
10/31/2025, 4:45:40.837 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"AzurePipelinesTestRunId":"32928758","operatingSystem":"AzureLinux.3.Amd64.Open","System.StageName":"Build","BuildId":"1190256","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","System.PhaseName":"run_test_p1__linux_x64_checked","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","Reason":"Schedule","configuration":"Checked-interpmode1","Project":"public","BuildNumber":"20251031.1","DefinitionId":"316","System.PhaseAttempt":"1","System.JobAttempt":"1","System.JobName":"__default","DefinitionName":"runtime-interpreter"} | Schedule
10/31/2025, 4:42:12.854 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageName":"Build","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","System.PhaseName":"run_test_p1__linux_x64_checked","Project":"public","architecture":"x64","System.StageAttempt":"1","BuildNumber":"20251031.1","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","BuildId":"1190256","System.JobAttempt":"1","DefinitionName":"runtime-interpreter","AzurePipelinesTestRunId":"32928738","operatingSystem":"AzureLinux.3.Amd64.Open","System.PhaseAttempt":"1","configuration":"Checked-interpmode1_no_tiered_compilation","System.JobName":"__default","DefinitionId":"316"} | Schedule
10/31/2025, 2:49:57.78 PM | runtime-interpreter | Checked-interpmode1 | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"OSX.13.Amd64.Open","BuildNumber":"20251031.1","System.StageAttempt":"1","System.JobAttempt":"1","Project":"public","DefinitionName":"runtime-interpreter","AzurePipelinesTestRunId":"32925370","System.StageName":"Build","DefinitionId":"316","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Checked-interpmode1","BuildId":"1190256","architecture":"x64","System.PhaseName":"run_test_p1__osx_x64_checked"} | Schedule
10/31/2025, 2:45:52.227 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"DefinitionName":"runtime-interpreter","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20251031.1","System.JobName":"__default","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"32925320","DefinitionId":"316","architecture":"x64","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_x64_checked","System.StageAttempt":"1","operatingSystem":"OSX.13.Amd64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","System.PhaseAttempt":"1","BuildId":"1190256","configuration":"Checked-interpmode1_no_tiered_compilation"} | Schedule
10/29/2025, 3:24:03.244 PM | runtime-interpreter | Checked-interpmode1 | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageAttempt":"1","architecture":"x64","Project":"public","BuildId":"1188401","Reason":"Schedule","AzurePipelinesTestRunId":"32874552","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","operatingSystem":"OSX.13.Amd64.Open","System.PhaseAttempt":"1","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-interpmode1","DefinitionName":"runtime-interpreter","System.StageName":"Build","DefinitionId":"316","BuildNumber":"20251029.1","System.JobAttempt":"1"} | Schedule
10/29/2025, 3:21:22.638 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.StageName":"Build","BuildNumber":"20251029.1","architecture":"x64","operatingSystem":"OSX.13.Amd64.Open","System.PhaseName":"run_test_p1__osx_x64_checked","configuration":"Checked-interpmode1_no_tiered_compilation","System.JobAttempt":"1","Reason":"Schedule","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildId":"1188401","System.PhaseAttempt":"1","System.StageAttempt":"1","Project":"public","DefinitionName":"runtime-interpreter","DefinitionId":"316","AzurePipelinesTestRunId":"32874498"} | Schedule
10/27/2025, 4:36:50.568 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"BuildNumber":"20251027.1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","DefinitionName":"runtime-interpreter","operatingSystem":"AzureLinux.3.Amd64.Open","Project":"public","AzurePipelinesTestRunId":"32821914","System.PhaseAttempt":"1","BuildId":"1186541","System.PhaseName":"run_test_p1__linux_x64_checked","System.StageAttempt":"1","System.StageName":"Build","configuration":"Checked-interpmode1","System.JobName":"__default","architecture":"x64","Reason":"Schedule","DefinitionId":"316"} | Schedule
10/27/2025, 4:33:07.215 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"operatingSystem":"AzureLinux.3.Amd64.Open","Reason":"Schedule","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","configuration":"Checked-interpmode1_no_tiered_compilation","System.JobAttempt":"1","AzurePipelinesTestRunId":"32821850","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"1186541","Project":"public","System.PhaseAttempt":"1","System.StageAttempt":"1","System.JobName":"__default","System.StageName":"Build","BuildNumber":"20251027.1","DefinitionId":"316","DefinitionName":"runtime-interpreter","System.PhaseName":"run_test_p1__linux_x64_checked"} | Schedule
10/27/2025, 2:59:26.313 PM | runtime-interpreter | Checked-interpmode1 | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"DefinitionName":"runtime-interpreter","architecture":"x64","Reason":"Schedule","System.JobName":"__default","System.JobAttempt":"1","operatingSystem":"OSX.13.Amd64.Open","System.PhaseName":"run_test_p1__osx_x64_checked","configuration":"Checked-interpmode1","Project":"public","System.PhaseAttempt":"1","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","AzurePipelinesTestRunId":"32820594","DefinitionId":"316","BuildId":"1186541","System.StageAttempt":"1","BuildNumber":"20251027.1","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
10/27/2025, 2:54:21.77 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"DefinitionName":"runtime-interpreter","architecture":"x64","DefinitionId":"316","Reason":"Schedule","System.PhaseName":"run_test_p1__osx_x64_checked","BuildNumber":"20251027.1","configuration":"Checked-interpmode1_no_tiered_compilation","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"OSX.13.Amd64.Open","AzurePipelinesTestRunId":"32820536","System.JobAttempt":"1","BuildId":"1186541","System.PhaseAttempt":"1","System.StageName":"Build","Project":"public","System.JobName":"__default"} | Schedule
10/24/2025, 4:50:10.82 PM | runtime-interpreter | Checked-interpmode1 | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"DefinitionName":"runtime-interpreter","architecture":"x64","operatingSystem":"AzureLinux.3.Amd64.Open","System.PhaseName":"run_test_p1__linux_x64_checked","DefinitionId":"316","Reason":"Schedule","configuration":"Checked-interpmode1","System.StageName":"Build","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","BuildNumber":"20251024.1","BuildId":"1184428","System.PhaseAttempt":"1","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","System.StageAttempt":"1","Project":"public","AzurePipelinesTestRunId":"32772822"} | Schedule
10/24/2025, 4:46:43.261 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | azurelinux.3.amd64.open.rt | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"BuildId":"1184428","architecture":"x64","Reason":"Schedule","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","configuration":"Checked-interpmode1_no_tiered_compilation","AzurePipelinesTestRunId":"32772756","DefinitionId":"316","DefinitionName":"runtime-interpreter","System.StageName":"Build","operatingSystem":"AzureLinux.3.Amd64.Open","BuildNumber":"20251024.1","System.JobAttempt":"1","System.PhaseAttempt":"1","System.JobName":"__default","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","System.PhaseName":"run_test_p1__linux_x64_checked"} | Schedule
10/24/2025, 2:55:36.451 PM | runtime-interpreter | Checked-interpmode1 | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","operatingSystem":"OSX.13.Amd64.Open","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"32770678","System.StageAttempt":"1","System.StageName":"Build","BuildNumber":"20251024.1","System.JobAttempt":"1","configuration":"Checked-interpmode1","DefinitionName":"runtime-interpreter","Project":"public","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Reason":"Schedule","architecture":"x64","System.PhaseName":"run_test_p1__osx_x64_checked","BuildId":"1184428","DefinitionId":"316"} | Schedule
10/24/2025, 2:50:54.737 PM | runtime-interpreter | Checked-interpmode1_no_tiered_compilation | osx.13.amd64.open | x64 | baseservices/exceptions/unittests/StrSwitchFinally/StrSwitchFinally.cmd | Failed | {"System.JobAttempt":"1","System.StageName":"Build","DefinitionId":"316","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"32770540","operatingSystem":"OSX.13.Amd64.Open","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","configuration":"Checked-interpmode1_no_tiered_compilation","BuildId":"1184428","DefinitionName":"runtime-interpreter","BuildNumber":"20251024.1","System.StageAttempt":"1","Reason":"Schedule","architecture":"x64","System.JobName":"__default","Project":"public"} | Schedule

</body>

</html>

### PR DESCRIPTION
**Pull request by AndyAyersMS**
PR #123781 changed things so that throw helper blocks are now created just after lower. Because of this they no longer get the special liveness update for unreachable blocks.

Add this update in explicitly when the blocks are created.

Fixes #123929

### CODE REVIEW

**Review by kg — APPROVED** [review]

File: src/coreclr/jit/liveness.cpp [hunk 1]
```diff
@@ -1472,22 +1472,7 @@ void Liveness<TLiveness>::DoLiveVarAnalysis()
...
-            if (block->HasPotentialEHSuccs(m_compiler))
-            {
-                block->VisitEHSuccs(m_compiler, [=](BasicBlock* succ) {
-                    VarSetOps::UnionD(m_compiler, block->bbLiveOut, succ->bbLiveIn);
-                    return BasicBlockVisit::Continue;
-                });
-            }
-
-            VarSetOps::Assign(m_compiler, block->bbLiveIn, block->bbLiveOut);
+            m_compiler->fgSetThrowHelpBlockLiveness(block);
```
Comment (jakobbotsch) [inline src/coreclr/jit/liveness.cpp:1475]: Are some of the throw helpers created before this point still? If not I think you can delete this code from liveness.

**Review by jakobbotsch — APPROVED** [review]
LGTM.

I assume codegen is still implicitly referencing the throw helper blocks and that we thus cannot just run the liveness after they are created (i.e. it would require some special casing regardless of when we run it).

File: src/coreclr/jit/liveness.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/liveness.cpp:1475]: This is more or less what I plan to do in a follow-up -- run this only for BBF_THROW_HELPER blocks. Or, I could just remove it all together and assert no unreachable block is a throw helper.
