### PR TITLE
Align up structs to IntPtr.Size if they have gc pointers

### LINKED ISSUE #100220: Non-blittable struct with explicit layout has wrong managed size
Context https://github.com/dotnet/runtime/pull/100206#issuecomment-2016856746

## Repro

```csharp
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

Console.WriteLine(Unsafe.SizeOf<MyStruct>());

[StructLayout(LayoutKind.Explicit, Size = 9)]
struct MyStruct
{
    [FieldOffset(0)]
    public byte[] a;
    [FieldOffset(8)]
    public byte b;
}
```

## Expected result (on x64)

16

## Actual result

9

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/100220

I am not an expert in R2R/NAOT type system, but looks like it fixes the issue

### CODE REVIEW

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 1]
```diff
@@ -993,6 +993,11 @@ private static SizeAndAlignment ComputeInstanceSize(MetadataType type, LayoutInt
                 }
             }
 
+            if (type.ContainsGCPointers)
+            {
+                instanceSize = LayoutInt.AlignUp(instanceSize, new LayoutInt(target.PointerSize), target);
```
Comment (tannergooding) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:998]: Does the general code here also need factor in other higher packing like for `Vector64/128/256/512`, `Int128/UInt128`, or `long/ulong/double`?

It seems odd in general how setting `Size` works (below is for `Sequential`, but `Explicit` is generally the same).

Setting `Size = 0` is ignored:
```csharp
[StructLayout(LayoutKind.Sequential, Size = 0)]
struct MyStruct      // Size 16
{
    public double a; // offset: 0
    public int b;    // offset: 8
    public byte c;   // offset: 12
}
```

Setting `Size < NaturalSize` trims any packing, but doesn't actually change the layout/packing, but trims the size:
```csharp
[StructLayout(LayoutKind.Sequential, Size = 1)]
struct MyStruct      // Size 13
{
    public double a; // offset: 0
    public int b;    // offset: 8
    public byte c;   // offset: 12
}
```

Setting `Size >= NaturalSize` just adds more bytes, but similarly doesn't make things line up for packing.

Comment (EgorBo) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:998]: @tannergooding I presume you tested on CoreCLR, right? I guess for those case we need to file a separate issue - this PR fixes an obvious bug that is only NAOT/R2R specific

Comment (tannergooding) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:998]: > I presume you tested on CoreCLR, right

Yes

> his PR fixes an obvious bug that is only NAOT/R2R specific

I don't think it's NAOT/R2R specific. A new console app containing the repro from #100220 prints the same thing for RyuJIT (`9`, when it should be `16`).

File: src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.StructLayoutAttribute.cs [hunk 2]
```diff
@@ -193,6 +194,22 @@ public static void Test_Interface()
             Assert.Null(s);
         }
 
+        [Fact]
+        [ActiveIssue("https://github.com/dotnet/runtime/issues/100220", typeof(PlatformDetection), nameof(PlatformDetection.IsMonoRuntime))]
+        public static void StructWithGCAndExplicitSizeIsAlignedByPtr()
```
Comment (jkotas) [inline src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.StructLayoutAttribute.cs:199]: This test does not belong into this file. These are System.Reflection.MetadataLoadContext tests. They are meant to test MetadataLoadContext projections of the types, not the behavior of the runtime type system.

Comment (EgorBo) [reply src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.StructLayoutAttribute.cs:199]: @jkotas any idea what is a more appropriate place? I had a hard time finding the right spot

Comment (jkotas) [reply src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.StructLayoutAttribute.cs:199]: Somewhere under src\tests\Loader\classloader\explicitlayout

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 3]
```diff
@@ -993,6 +993,11 @@ private static SizeAndAlignment ComputeInstanceSize(MetadataType type, LayoutInt
                 }
             }
 
+            if (type.ContainsGCPointers)
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:996]: For reference, here is the matching logic in the runtime type loader:

https://github.com/dotnet/runtime/blob/8c68710084b861c44b6868c0bd972ce24aed55dd/src/coreclr/vm/methodtablebuilder.cpp#L8868-L8872

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 4]
```diff
@@ -993,6 +993,11 @@ private static SizeAndAlignment ComputeInstanceSize(MetadataType type, LayoutInt
                 }
```
Comment (jkotas) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:993]: The `classLayoutSize` is only respected for value types by the runtime type loader: https://github.com/dotnet/runtime/blob/8c68710084b861c44b6868c0bd972ce24aed55dd/src/coreclr/vm/methodtablebuilder.cpp#L8832-L8835

```
if (type.IsValueType)
{
    if (classLayoutSize != 0)
    {
       instanceSize = LayoutInt.Max(instanceSize, new LayoutInt(classLayoutSize));
    }
    else
    {
        instanceSize = LayoutInt.AlignUp(instanceSize, alignment, target);
    }
}
```

Repro:

```
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

for (;;)
{
    var start = GC.GetAllocatedBytesForCurrentThread();
    GC.KeepAlive(new MyClass());
    Console.WriteLine(GC.GetAllocatedBytesForCurrentThread() - start);
}

[StructLayout(LayoutKind.Explicit, Size = 1000)]
class MyClass
{
    [FieldOffset(0)]
    public byte[] a;
    [FieldOffset(8)]
    public byte b;
}
```

Prints 32 with regular CoreCLR and 1016 with native AOT.

Comment (MichalPetryka) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:993]: I feel like this should print `1000` on both runtimes instead? I don't think anything documents that oversizing is not supported for classes.

Comment (jkotas) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:993]: The StructLayout and FieldOffset attributes were designed to control the marshalled unmanaged layout. `LayoutKind.Explicit` is fully respected for the marshalled layout. `Console.WriteLine(Marshal.SizeOf<MyClass>())` prints `1000` for my example as expected.

Later ExplicitLayout got overloaded to control overlapping of fields in the managed layout. This overloading introduced many non-sensical behaviors. User code should not depend on managed layout (except blittable structs) in the first place.

**Comment by EgorBo** [comment]
Probably needs https://github.com/dotnet/runtime/pull/100618 since the GC.* trick is not reliable to get object size in tests.

Otherwise should be ready. The rules turn out to be a bit complex, e.g.
```cs
[StructLayout(LayoutKind.Sequential, Size = 1000)]
class ClassA
{
    long A;
}

[StructLayout(LayoutKind.Explicit, Size = 1000)]
class ClassB
{
    [FieldOffset(0)]
    long A;
}
```

Here, CoreCLR allocates 1016 bytes for an instance of `ClassA` and 24 bytes for `ClassB` - I am not sure whether it should be "fixed" in CoreCLR, but I aligned NAOT/R2R, so the rules are:

- Classes:
  - Layout has gc pointers - we ignore explicit Size
  - Layout has ExplicitLayout - we ignore explicit Size (bug-to-bug compat?)
- Structs:
  - Layout has gc pointers - we align up size to target pointer

**Comment by jkotas** [comment]
> Probably needs https://github.com/dotnet/runtime/pull/100618 since the GC.* trick is not reliable to get object size in tests.

I do not think it would help you. This API gives you the exact same result as `sizeof`.

File: src/tests/Loader/classloader/explicitlayout/Regressions/100220/Runtime_100220.cs [hunk 5]
```diff
@@ -0,0 +1,189 @@
...
+    }
+
+    public class SubclassSubclassSeq : SubclassSeq
+    {
+        public byte E;
+        public nint F;
+    }
+
+    [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
+    private static int GetManagedSize(Func<object> allocator)
```
Comment (jkotas) [inline src/tests/Loader/classloader/explicitlayout/Regressions/100220/Runtime_100220.cs:106]: This is not reliable as you have pointed out. 

I think a reliable version of this check would be to inherit from the type you want to check, add a byte field, and verify offset of the byte field.

Comment (MichalPetryka) [reply src/tests/Loader/classloader/explicitlayout/Regressions/100220/Runtime_100220.cs:106]: Would an `UnsafeAccessor` to `RuntimeHelpers.GetRawObjectDataSize` work better here instead maybe?

File: src/tests/Loader/classloader/explicitlayout/Regressions/100220/Runtime_100220.cs [hunk 6]
```diff
@@ -0,0 +1,190 @@
...
+using Xunit;
+
+public static class Runtime_100220
+{
+    [Fact]
+    [ActiveIssue("https://github.com/dotnet/runtime/issues/100220", TestRuntimes.Mono)]
+    // Also, Mono needs RuntimeHelpers.GetRawObjectDataSize or equivalent to get an object size
+    public static int TestEntryPoint()
+    {
+        if (IntPtr.Size == 8)
```
[the remark this answers is not in the document]
Comment (EgorBo) [reply src/tests/Loader/classloader/explicitlayout/Regressions/100220/Runtime_100220.cs:17]: I prefer expected value to be a constant rather then computed expressions for Asserts

**Comment by EgorBo** [comment]
@jkotas anything else here? looks like R2R and NAOT outerloops passed

**Comment by lewing** [comment]
The maui team is waiting for a resolution on this

**Comment by MichalStrehovsky** [comment]
> I assume Jan is OOF, so maybe @MichalStrehovsky can review this?

There is a reason I moved this to crossgen2 team (https://github.com/dotnet/runtime/issues/100220#issuecomment-2017353546). Type layout needs to exactly match CoreCLR type layout for ReadyToRun to work. It has been a bug farm in the past. I don't see anything obviously _wrong_ in this PR but that's not a high quality bar. I know we have modes of operation of crossgen2 where it serializes type layout into the image and validates it at runtime, but I don't know what CI legs that runs in and if this would cover it too. Can you get @davidwrighton to have a look? I really only have surface-level knowledge of R2R testing and very much hope I'm not the biggest expert.

**Review by jkotas — APPROVED** [review]
LGTM. Thank you for adding a lot of tests!

**Comment by EgorBo** [comment]
> The maui team is waiting for a resolution on this

@lewing do we need to backport the fix to a specific release preview branch? if so, which?
