### PR TITLE
[Merge-on-Red] - Implement Test Process Watcher

### LINKED ISSUE #77735: [Merge-on-Red] - Accurately log catastrophic test failures and freezes in source-gened test infrastructure
# Merge-on-Red Subproject

Tests should have failures logged in a format that Build Analysis can easily reasoned about and surfaced to the check tab.

## Goals

* Be able to identify and record catastrophic failures to Build Analysis:
  * Native Crashes
  * Hangs and Timeouts

## Work Items

* [x] Look into the other format (other than _trx_) used by `dotnet test` and understand how it works.
* [x] ~~A Yaml version was decided, so it has to be implemented in the test source generators.~~ Helix compatibility with older OS's would be broken by adding new stuff, so this work item was changed to a XML log fixer.
* [ ] Implement accordingly so the _Helix script_ can easily understand and surface it.
* [ ] Implement a _watchdog_ to be able to easily identify when a test has taken too long and/or frozen. Suggested ideas:
  ~~* [ ] Add it as a new feature in _corerun_: Create a new flag like `--timeout`. Have _corerun_ exit and report the failure if this value is exceeded.~~
  * [ ] Add it as a new mini-app: This mini-app will receive the test's corerun command, and the timeout value as parameters. It will spawn a separate process to run the test in, and monitor it itself. If it exceeds the time limit, then i
t will kill the process and report the failure accordingly.

### PR DESCRIPTION
**Pull request by ivdiazsa**
This PR adds a new harness to run tests by means of _corerun_. This is the watchdog work item defined in issue #77735.

The main purpose of adding it, is to be able to have a way to monitor potential freezes and hangs when running tests. If a specified time frame lapses, and the test hasn't finished, then the watcher will automatically kill the process and report accordingly.

With this mechanism in place, we will no longer have incomplete test runs that froze somewhere, without any further information, making test failures of this kind much easier to begin investigating, and consequently fix them.

Remaining Tasks Until Completion:

- [x] Refactor accordingly to give it a more solid multi-platform shape.
- [x] Modify the test script generators to use the watcher, instead of directly calling corerun.
- [x] Add the watcher to the repo's build scripts, so it's addition is transparent.

### CODE REVIEW

**Comment by ivdiazsa** [comment]
Hi @jkoritzinsky! Here's the initial draft of the test watcher. It works on Linux and Windows, and it's ready for sharing, so you can take a look and we can adjust/refactor/edit/etc as necessary.

**Comment by ivdiazsa** [comment]
FYI. This is the draft PR of the watcher @agocke @tommcdon

**Comment by jkoritzinsky** [comment]
I think we can just include the watchdog CMakeLists.txt from the CoreCLR and Mono CMake builds. I don’t think we need to introduce a separate subset and native project build for it.

File: src/native/watchdog/watchdog.cpp [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+    GetExitCodeProcess(proc_info.hProcess, &exit_code);
+
+    CloseHandle(proc_info.hProcess);
+    CloseHandle(proc_info.hThread);
+    return exit_code;
+
+#else
+    const int check_interval = 1000;
+    int check_count = 0;
+    char **args = new char *[exe_argc];
```
Comment (agocke) [inline src/native/watchdog/watchdog.cpp:69]: Consider a vector<string> here. You forgot to delete

**Comment by agocke** [comment]
fwiw I'm not completely sold on C++ if we have to parse and fixup the XML file. I'd rather use... anything else tbh.

File: src/native/watchdog/watchdog.cpp (hunk 1 above)
Comment (ivdiazsa) [reply src/native/watchdog/watchdog.cpp:69]: I forgot the deletion, thanks for pointing it out Andy. The reason we're using a `char*[]` is because that's the type that `execv()` requires.

Comment (agocke) [reply src/native/watchdog/watchdog.cpp:69]: `unique_ptr<char*[]>` then?

Comment (ivdiazsa) [reply src/native/watchdog/watchdog.cpp:69]: That might work as well. I'll try it.

**Comment by agocke** [comment]
Yeah, I don't think we need to block this PR -- gathering crash dumps is the purpose here and we should move forward with that.

However, the problem with XML will be that the watcher will need to pick up a broken YAML file and translate it into XML. This can't be done in the runner, because by definition the runner has crashed at that point. So we would have to start up a new process to do the translation.

**Comment by ivdiazsa** [comment]
> Yeah, I don't think we need to block this PR -- gathering crash dumps is the purpose here and we should move forward with that.
> 
> However, the problem with XML will be that the watcher will need to pick up a broken YAML file and translate it into XML. This can't be done in the runner, because by definition the runner has crashed at that point. So we would have to start up a new process to do the translation, or translate from YAML to XML in C++.

I'm confused. The watcher only runs the test. Why does it need to read an XML or YAML?

**Comment by agocke** [comment]
The latest update is that Helix can't parse YAML. So we need a watcher (of some sort) to rewrite the YAML to XML.

**Comment by ivdiazsa** [comment]
There was a possibility of excluding the affected platforms to not use YAML. If that ends up not being the case anymore, we will work some magic over at the logger writers, as shown here: https://github.com/ivdiazsa/runtime/blob/2f66c46c1948af53c447e1efe0d1cc32867244f3/src/tests/Common/XUnitWrapperLibrary/TestSummary.cs#L95

Either translating the YAML to XML, or verifying the XML, or another way we might think of. And that's is done in C#. There's no reason to have a test runner also read logs.

**Comment by agocke** [comment]
How would you avoid having the test runner do the translation?

By definition, we only need to fix up the logs if the test execution has aborted in a non-recoverable way. The watcher is the only thing alive. It will at minimum need to kickstart the process to recover a log.

**Comment by ivdiazsa** [comment]
But the code I linked is in charge of writing down the XML logs, and it dumps everything at the end, not as it's happening. Considering we're dealing with incomplete XML logs, then it means that process did write something. If it was completely aborted, then in theory, we would end up with nothing, rather than incomplete logs.

**Comment by agocke** [comment]
> Considering we're dealing with incomplete XML logs, then it means that process did write something. If it was completely aborted, then in theory, we would end up with nothing, rather than incomplete logs.

That's just as bad. We need valid log files at the end that described what passed and what failed.

**Comment by ivdiazsa** [comment]
> > Considering we're dealing with incomplete XML logs, then it means that process did write something. If it was completely aborted, then in theory, we would end up with nothing, rather than incomplete logs.
> 
> That's just as bad. We need valid log files at the end that described what passed and what failed.

In that case, we might need to rewrite the generated test runners to dump the test logs as they are happening, not all at the end. Thoughts @jkoritzinsky?

**Comment by jkoritzinsky** [comment]
Yes, I think updating the runner to write and flush the logs as the tests execute is a good idea. I forgot that I had designed it to avoid the IO until the end of the test.

File: src/native/watchdog/watchdog.cpp [hunk 2]
```diff
@@ -0,0 +1,134 @@
+#include <cstdio>
```
Comment (jkotas) [inline src/native/watchdog/watchdog.cpp:1]: Nit: Add license header

File: src/tests/Common/helixpublishwitharcade.proj [hunk 3]
```diff
@@ -722,7 +722,10 @@
   </PropertyGroup>
 
   <PropertyGroup>
-    <TestWatcherPath>$(ArtifactsDir)obj/coreclr/$(OSPlatformConfig)/test-watchdog/watchdog</TestWatcherPath>
+    <TestWatcherExe Condition="'$(TestWrapperTargetsWindows)' != 'true'">watchdog</TestWatcherExe>
+    <TestWatcherExe Condition="'$(TestWrapperTargetsWindows)' == 'true'">watchdog.exe</TestWatcherExe>
```
Comment (jkoritzinsky) [inline src/tests/Common/helixpublishwitharcade.proj:726]:
```suggestion
    <TestWatcherExe>watchdog$(ExeSuffix)</TestWatcherExe>
```

File: src/native/watchdog/watchdog.cpp [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+    WaitForSingleObject(proc_info.hProcess, timeout_ms);
+    GetExitCodeProcess(proc_info.hProcess, &exit_code);
+
+    CloseHandle(proc_info.hProcess);
+    CloseHandle(proc_info.hThread);
+    return exit_code;
+
+#else // !TARGET_WINDOWS
+
+    // TODO: Describe what the 'ms_factor' is, and why it's being used here.
```
Comment (jkoritzinsky) [inline src/native/watchdog/watchdog.cpp:81]: Address this TODO?

File: src/tests/Common/helixpublishwitharcade.proj [hunk 5]
```diff
@@ -720,7 +720,9 @@
 
   <ItemGroup Condition=" '$(UsesHelixSdk)' == 'true' ">
     <HelixCorrelationPayload Include="$(CoreRootDirectory)" />
-    <HelixCorrelationPayload Include="$(XUnitLogCheckerDirectory)" />
+
+    <!-- Browser-Wasm follows a very different workflow, which is currently out of scope of the Log Checker and Test Watcher. -->
+    <HelixCorrelationPayload Include="$(XUnitLogCheckerDirectory)" Condition="'$(TargetsBrowser)' != 'true'" />
```
Comment (jkoritzinsky) [inline src/tests/Common/helixpublishwitharcade.proj:725]: We're not going to use the watcher on any platforms that use XHarness, so don't include it there either.

```suggestion
    <!-- Browser-Wasm follows a very different workflow, which is currently out of scope of the Log Checker and Test Watcher. -->
    <HelixCorrelationPayload Include="$(XUnitLogCheckerDirectory)" Condition="'$(TargetsBrowser)' != 'true' and '$(TargetHasHelixXHarnessSdkSupport)' != 'true'" />
```

**Review by jkoritzinsky — APPROVED** [review]
Two small comments, but other than that, LGTM!

File: src/native/watchdog/watchdog.cpp (hunk 4 above)
Comment (ivdiazsa) [reply src/native/watchdog/watchdog.cpp:81]: Oops forgot that. Thanks for the catch.

File: src/tests/Common/helixpublishwitharcade.proj (hunk 5 above)
Comment (ivdiazsa) [reply src/tests/Common/helixpublishwitharcade.proj:725]: I think this would be better suited for the log checker PR. Since we are passing the watcher to Helix through the Core_Root, then this is no longer related here. I'll update the comment, removing the mention to the Test Watcher.

File: src/native/watchdog/watchdog.cpp (hunk 4 above)
Comment (ivdiazsa) [reply src/native/watchdog/watchdog.cpp:81]: I actually removed it altogether. I needed it because originally, I was dealing with some C stuff that combined microseconds and milliseconds. After switching to C++'s `std::chrono::milliseconds`, testing with and without it yielded virtually the same wait time, so it ended up being redundant.

**Review by jkoritzinsky — APPROVED** [review]

File: src/tests/Common/helixpublishwitharcade.proj [hunk 6]
```diff
@@ -720,7 +720,9 @@
 
   <ItemGroup Condition=" '$(UsesHelixSdk)' == 'true' ">
     <HelixCorrelationPayload Include="$(CoreRootDirectory)" />
-    <HelixCorrelationPayload Include="$(XUnitLogCheckerDirectory)" />
+
+    <!-- Browser-Wasm follows a very different workflow, which is currently out of scope of the Log Checker. -->
+    <HelixCorrelationPayload Include="$(XUnitLogCheckerDirectory)" Condition="'$(TargetsBrowser)' != 'true'" />
```
Comment (lewing) [inline src/tests/Common/helixpublishwitharcade.proj:725]: Does this change the current behavior for wasm logs then?

Comment (ivdiazsa) [reply src/tests/Common/helixpublishwitharcade.proj:725]: Not at all. Wasm is out of scope of this project for the time being, so wasm tests will remain unaffected.

**Comment by BruceForstall** [comment]
It seems undesirable to hard-code yet another timeout value (300 seconds?) into a new location (and there isn't a big, obvious comment noting that's what the number is). Especially since the YAML files (?) already specify per-test timeouts. E.g., it wouldn't surprise me if some merged test cases (e.g., Hardware Intrinsics) run under GCStress=3 on Linux/arm could be very slow.
