### PR TITLE
Fix for stress failure when adjusting effective IP while stackwalking may put it on a wrong instruction.

### LINKED ISSUE #86273: Assertion failed: (GetComponentSize() <= 2) || IsArray()
net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

System.Memory.Tests Work Item

https://dev.azure.com/dnceng-public/public/_build/results?buildId=272702&view=ms.vss-test-web.build-test-results-tab&runId=5384424&paneView=debug&resultId=195466

```
export DOTNET_TieredCompilation=0
export DOTNET_DbgEnableMiniDump=1
export DOTNET_EnableCrashReport=1
export DOTNET_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export DOTNET_JitStress=2
export DOTNET_JitStressRegs=1
```

```
+ ./RunTests.sh --runtime-path /root/helix/work/correlation
----- start Sat May 13 09:40:19 UTC 2023 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Memory.Tests.runtimeconfig.json --depsfile System.Memory.Tests.deps.json xunit.console.dll System.Memory.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Memory.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Memory.Tests (found 2682 of 2709 test cases)
  Starting:    System.Memory.Tests (parallel test collections = on, max threads = 2)

Assert failure(PID 28 [0x0000001c], Thread: 42 [0x002a]): (GetComponentSize() <= 2) || IsArray()
    File: /__w/1/s/src/coreclr/vm/methodtable.cpp Line: 7265
    Image: /root/helix/work/correlation/dotnet

[createdump] Gathering state for process 28 dotnet
[createdump] Crashing thread 002a signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.28.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.28.dmp
[createdump] Written 201752576 bytes (49256 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 389ms
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
./RunTests.sh: line 168:    28 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Memory.Tests.runtimeconfig.json --depsfile System.Memory.Tests.deps.json xunit.console.dll System.Memory.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/root/helix/work/workitem/e
----- end Sat May 13 09:40:40 UTC 2023 ----- exit code 134 ----------------------------------------------------------
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "CancelItselfOutsideOfTryCatchFinally",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 3/22/2024 4:10:23 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[660346](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660346)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660346&view=ms.vss-test-web.build-test-results-tab&runId=16363210&resultId=177506)|dotnet/runtime#101162|
|[659851](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659851)|dotnet/runtime|[WasmTestOnChrome-MT-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659851&view=ms.vss-test-web.build-test-results-tab&runId=16348920&resultId=177506)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|2|2|

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: https://github.com/dotnet/runtime/issues/86273

The change makes sure that an instruction after a throwing call cannot be branched to (and have different GC liveness.
In many cases that was already guaranteed, just picking up remaining cases.

This allows not to do `-1` adjustment of the effective IP when stackwalking through exceptional/aborting frames. The root cause of https://github.com/dotnet/runtime/issues/86273 was that this adjustment is not safe under some conditions. 

One solution would be to:
1. detect those conditions (which appear to be nontrivial, and we may not know all the cases), or 
2. make the adjustment unnecessary regardless of the context.

This change does the `#2`

### CODE REVIEW

**Comment by VSadov** [comment]
The few failures that were observed in the stress runs are not new, so I consider this a pass.

**Comment by VSadov** [comment]
CC. @jkotas @jakobbotsch

**Comment by VSadov** [comment]
I think this is ready for a review.

**Comment by VSadov** [comment]
I've just realized that we can now stop doing this adjustment on x86 and on NativeAOT as well. 
And then can get rid of `ICodeManagerFlags::AbortingCall` entirely.

So, there is another commit. It is not strictly necessary for the fix, just some cleanup that we can do.

File: src/coreclr/jit/codegenlinear.cpp [hunk 1]
```diff
@@ -756,6 +758,20 @@ void CodeGen::genCodeForBBlist()
...
             case BBJ_ALWAYS:
             {
+                GenTree* call = block->lastNode();
+                if ((call != nullptr) && (call->gtOper == GT_CALL))
+                {
+                    if ((call->AsCall()->gtCallMoreFlags & GTF_CALL_M_DOES_NOT_RETURN) != 0 ||
+                        ((call->AsCall()->gtCallType == CT_HELPER) &&
+                         Compiler::s_helperCallProperties.AlwaysThrow(call->AsCall()->GetHelperNum())))
+                    {
+                        // NOTE: We should probably never see a BBJ_ALWAYS block ending with a throw in a first place.
```
Comment (AndyAyersMS) [inline src/coreclr/jit/codegenlinear.cpp:768]: I take it you did see such cases? Can you open an issues for us to follow-up and switch them over to BBJ_THROWs?

File: src/coreclr/jit/codegenlinear.cpp [hunk 2]
```diff
@@ -712,7 +712,9 @@ void CodeGen::genCodeForBBlist()
 
                     if ((call != nullptr) && (call->gtOper == GT_CALL))
                     {
-                        if ((call->AsCall()->gtCallMoreFlags & GTF_CALL_M_DOES_NOT_RETURN) != 0)
+                        if ((call->AsCall()->gtCallMoreFlags & GTF_CALL_M_DOES_NOT_RETURN) != 0 ||
```
Comment (AndyAyersMS) [inline src/coreclr/jit/codegenlinear.cpp:715]: Can we extend `GenTreeCall::IsNoReturn()` to cover the helper case too? Either by setting the  no return flag when the helper is set, or by putting this check there?

File: src/coreclr/jit/codegenlinear.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/codegenlinear.cpp:768]: Note this might largely clean itself up by adding the logic to `IsNoReturn`, though there is one place in morph where we still check the flag rather than the property.

Comment (VSadov) [reply src/coreclr/jit/codegenlinear.cpp:768]: > I take it you did see such cases? 

Yes, I wanted this to be an assert, so it would not happen by accident in the future. To my surprise, the assert was hit with existing code.

File: src/coreclr/jit/codegenlinear.cpp (hunk 2 above)
Comment (VSadov) [reply src/coreclr/jit/codegenlinear.cpp:715]: I have tried, naively, to put 

```c
    if (s_helperCallProperties.AlwaysThrow((CorInfoHelpFunc)helper))
    {
        result->gtCallMoreFlags |= GTF_CALL_M_DOES_NOT_RETURN;
    }
```

in gtNewHelperCallNode

, but that resulted in 

```
  Assertion failed 'call->gtCallType == CT_USER_FUNC' in 'System.ModuleHandle:ResolveFieldHandle(int,System.RuntimeTypeHandle[],System.Run
  timeTypeHandle[]):System.RuntimeFieldHandle:this' during 'Merge throw blocks' (IL size 283; hash 0x040825d3; FullOpts)
```

```c
        if (!call->IsNoReturn())
        {
            continue;
        }

        // Sanity check -- only user funcs should be marked do not return
        assert(call->gtCallType == CT_USER_FUNC);
```

I could not easily tell if the assert is just an observation/sanity, that could be relaxed or indeed guarding some assumptions made in the code, so I did not continue on that path.

Comment (VSadov) [reply src/coreclr/jit/codegenlinear.cpp:715]: Commenting out that assert leads to others:

```
  Assert failure(PID 35472 [0x00008a90], Thread: 41468 [0xa1fc]): Assertion failed 'updateCount < optNoReturnCallCount' in 'System.Tests.S
  tringComparerTests:Create_CreatesValidComparer():this' during 'Merge throw blocks' (IL size 543; hash 0xc45bc068; FullOpts)
```

Comment (VSadov) [reply src/coreclr/jit/codegenlinear.cpp:715]: I think I'd prefer entering an issue on this.

Comment (AndyAyersMS) [reply src/coreclr/jit/codegenlinear.cpp:715]: Makes sense, looks like there are some assumptions in the throw helper merging to sort out.

**Review by AndyAyersMS — APPROVED** [review]
JIT changes LGTM.

File: src/coreclr/inc/gcinfodecoder.h [hunk 3]
```diff
@@ -179,7 +179,7 @@ enum ICodeManagerFlags
     ExecutionAborted  =  0x0002, // execution of this function has been aborted
                                  // (i.e. it will not continue execution at the
                                  // current location)
-    AbortingCall      =  0x0004, // The current call will never return
+    // unused         =  0x0004, // was AbortingCall
```
Comment (jkotas) [inline src/coreclr/inc/gcinfodecoder.h:182]:
```suggestion
```
This information is not important going forward.

File: src/coreclr/inc/eetwain.h [hunk 4]
```diff
@@ -89,7 +89,7 @@ enum ICodeManagerFlags
     ExecutionAborted =  0x0002, // execution of this function has been aborted
                                     // (i.e. it will not continue execution at the
                                     // current location)
-    AbortingCall    =   0x0004, // The current call will never return
+    // unused       =   0x0004, // was AbortingCall
```
Comment (jkotas) [inline src/coreclr/inc/eetwain.h:92]:
```suggestion
```

File: src/coreclr/inc/gcinfodecoder.h (hunk 3 above)
Comment (jkotas) [reply src/coreclr/inc/gcinfodecoder.h:182]: (You can shrink these bits to be consecutive if you would like - there are multiple unused holes.)

**Comment by jkotas** [comment]
Do you plan to get rid of the adjustment in a follow up PR?

**Review by jkotas — APPROVED** [review]

File: src/coreclr/inc/gcinfodecoder.h (hunk 3 above)
Comment (VSadov) [reply src/coreclr/inc/gcinfodecoder.h:182]: I just saw the same pattern decorating gaps in an enum later in the file.

Comment (jkotas) [reply src/coreclr/inc/gcinfodecoder.h:182]: The place later in this file where this pattern is used has to do with the GCInfo format. Eliminating those gaps would be GCInfo format breaking change and it is useful to know what that gap was used for in the past versions of the format.

ICodeManagerFlags are not coupled with the file format, so these reasons do not apply here.

**Comment by VSadov** [comment]
> Do you plan to get rid of the adjustment in a follow up PR?

In this PR we can only avoid adjustment in a throwing case. 

That is possible because on this path we will care only about faults in fully-interruptible methods or methods that throw (most commonly it is `IL_Throw`). We do not need to adjust in these cases because: 
* we only care about fully interruptible methods as only those may have EH, and otherwise all locals are dead anyways.
* in a leaf that faulted we never wanted to adjust during stackwalk.
* and in nonleaf that called a throwing helper the `<brk>` after the call makes it irrelevant if the IP is on the instruction following the throwing call or at `-1` relative to that.

We stopped adjusting in this case in this PR - including x86 and AOT cases.

To get rid of the adjustment in all cases is a bigger change because:
* we'd need to solve the issues uncovered in #95565 
I am getting warmer towards "just add a NOP" solution, just want to see if I can scope it a bit. 
Adding `<brk>` after throwing calls is one thing, since those are rare and generally a slow path, adding NOP in a more general case where call is at the end of a BB still kind of bothers me. 
This will need to have a solution first. There are many benefits, not just that it leads to complete removal of `-1` (although not sure if that can be done for x86 as well, maybe...) 
* another issue is that partially interruptible case includes `-1` skew in the GCInfo for safepoints, so we'd need to change the format, which we can do in this release.

**Comment by VSadov** [comment]
Thanks!!!
