### PR TITLE
[EventPipe] Block eventpipe delete provider for pending callbacks

### LINKED ISSUE #106113: Test failure: tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd
**Failed in:** [runtime-coreclr outerloop 20240807.6](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769251&view=ms.vss-test-web.build-test-results-tab&runId=19637068&resultId=113708&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx x64 Checked no_tiered_compilation @ OSX.1200.Amd64.Open
    - tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd
```

**Error message:**
```
 /private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/tracing/../eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.sh: line 341: -r:/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/*.dll: No such file or directory
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/tracing/../eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.sh: line 467: 26828 Segmentation fault: 11  (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/A8C2096C/w/ABD00996/uploads/eventpipe/eventsourceerror/eventsourceerror/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
22:28:17
Response file: /private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/Microsoft.Diagnostics.NETCore.Client.dll.rsp
/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
-o:/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/Microsoft.Diagnostics.NETCore.Client.dll
-r:/tmp/helix/working/A8C2096C/p/System.*.dll
-r:/tmp/helix/working/A8C2096C/p/Microsoft.*.dll
-r:/tmp/helix/working/A8C2096C/p/xunit.*.dll
-r:/tmp/helix/working/A8C2096C/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:x64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/A8C2096C/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/Microsoft.Diagnostics.NETCore.Client.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/Microsoft.Diagnostics.NETCore.Client.dll
Running R2RDump:  dotnet /tmp/helix/working/A8C2096C/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/Microsoft.Diagnostics.NETCore.Client.dll --out /private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/Microsoft.Diagnostics.NETCore.Client.dll.r2rdump --val
22:28:20
/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/TestLibrary.dll
22:28:20
Response file: /private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/TestLibrary.dll.rsp
/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/TestLibrary.dll
-o:/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/TestLibrary.dll
-r:/tmp/helix/working/A8C2096C/p/System.*.dll
-r:/tmp/helix/working/A8C2096C/p/Microsoft.*.dll
-r:/tmp/helix/working/A8C2096C/p/xunit.*.dll
-r:/tmp/helix/working/A8C2096C/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:x64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/A8C2096C/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/TestLibrary.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/TestLibrary.dll
Running R2RDump:  dotnet /tmp/helix/working/A8C2096C/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/TestLibrary.dll --out /private/tmp/helix/working/A8C2096C/w/ABD00996/e/tracing/eventpipe/eventsourceerror/eventsourceerror/TestLibrary.dll.r2rdump --val
22:28:22
/private/tmp/helix/working/A8C2096C/w/AB
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor19|0_20(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-08-08T02:24:00.815Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.StageAttempt":"1","System.PhaseAttempt":"1","DefinitionName":"runtime-coreclr   outerloop","AzurePipelinesTestRunId":"19637068","architecture":"x64","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked","System.JobName":"__default","Project":"public","System.StageName":"Build","System.JobAttempt":"1","BuildId":"769251","Reason":"Schedule","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","operatingSystem":"OSX.1200.Amd64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"108","BuildNumber":"20240807.6"} | Schedule
2024-07-23T07:08:50.086Z | runtime-coreclr crossgen2 | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"operatingSystem":"OSX.1200.Amd64.Open","System.JobName":"__default","System.PhaseAttempt":"1","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2","Project":"public","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","AzurePipelinesTestRunId":"19031306","BuildNumber":"20240722.1","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","System.StageAttempt":"1","DefinitionId":"124","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","BuildId":"751456","Reason":"Schedule"} | Schedule
2024-07-23T06:29:22.826Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"AzurePipelinesTestRunId":"19030210","System.JobName":"__default","architecture":"x64","System.PhaseAttempt":"1","System.JobAttempt":"1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_osx_x64_checked","BuildNumber":"20240722.1","DefinitionName":"runtime-coreclr   crossgen2   outerloop","DefinitionId":"134","Project":"public","System.JobId":"94bcf053-7b40-5111-f380-056c9b4b6421","System.StageName":"Build","operatingSystem":"OSX.1200.Amd64.Open","Reason":"Schedule","BuildId":"751418"} | Schedule
2024-07-23T06:20:33.352Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.arm64.open | arm64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.StageName":"Build","DefinitionId":"134","System.JobName":"__default","BuildId":"751418","architecture":"arm64","Project":"public","System.PhaseAttempt":"1","System.JobId":"b98d1326-0c22-5cb0-0518-a01616fe181e","configuration":"Checked-no_tiered_compilation","BuildNumber":"20240722.1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","System.PhaseName":"run_test_p1_R2R_Composite_osx_arm64_checked","Reason":"Schedule","AzurePipelinesTestRunId":"19029810","operatingSystem":"OSX.1200.ARM64.Open","DefinitionName":"runtime-coreclr   crossgen2 outerloop"} | Schedule
2024-07-22T09:07:58.708Z | runtime | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"architecture":"x64","System.JobId":"e3709b8d-3156-5bab-add0-5fb59fdfbeb2","DefinitionId":"129","BuildNumber":"20240722.6","System.StageName":"Build","System.JobName":"__default","DefinitionName":"runtime","System.PhaseName":"run_test_p0_coreclr__osx_x64_checked","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"18972706","System.StageAttempt":"1","configuration":"Checked-no_tiered_compilation","Project":"public","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildId":"749625"} | Schedule
2024-07-22T07:23:30.459Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.PhaseAttempt":"1","DefinitionId":"135","BuildId":"749570","AzurePipelinesTestRunId":"18969620","System.StageAttempt":"1","DefinitionName":"coreclr-release-outerloop-nightly","System.StageName":"Build","System.PhaseName":"run_test_p1_R2R_osx_x64_release","operatingSystem":"OSX.1200.Amd64.Open","System.JobName":"__default","BuildNumber":"20240721.1","System.JobAttempt":"1","architecture":"x64","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","Reason":"Schedule","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Release-no_tiered_compilation"} | Schedule

<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-07-22T07:21:49.153Z | runtime-coreclr crossgen2-composite gcstress | Checked-heapverify1 | osx.1200.arm64.open | arm64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-heapverify1","BuildId":"749571","operatingSystem":"OSX.1200.ARM64.Open","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","System.JobName":"__default","architecture":"arm64","Reason":"Schedule","AzurePipelinesTestRunId":"18969638","Project":"public","System.StageAttempt":"1","System.StageName":"Build","BuildNumber":"20240721.1","System.PhaseAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","DefinitionId":"141","System.JobAttempt":"1"} | Schedule
2024-07-22T06:25:17.554Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.StageName":"Build","Project":"public","BuildId":"749562","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","DefinitionId":"134","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20240721.1","AzurePipelinesTestRunId":"18968848","DefinitionName":"runtime-coreclr   crossgen2   outerloop","System.JobId":"30d857d6-2812-5c31-5c67-e52c43389e0f","architecture":"x64","System.StageAttempt":"1","System.PhaseName":"run_test_p1_R2R_Composite_osx_x64_checked","configuration":"Checked-no_tiered_compilation","System.JobName":"__default","Reason":"Schedule","System.PhaseAttempt":"1"} | Schedule
2024-07-22T06:22:18.344Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"configuration":"Checked-no_tiered_compilation","DefinitionId":"134","BuildId":"749562","System.StageAttempt":"1","Reason":"Schedule","BuildNumber":"20240721.1","AzurePipelinesTestRunId":"18968836","operatingSystem":"OSX.1200.Amd64.Open","Project":"public","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"94bcf053-7b40-5111-f380-056c9b4b6421","System.PhaseName":"run_test_p1_R2R_osx_x64_checked","DefinitionName":"runtime-coreclr   crossgen2 outerloop","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobAttempt":"1","architecture":"x64"} | Schedule
2024-07-22T06:21:29.617Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.arm64.open | arm64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"AzurePipelinesTestRunId":"18968832","BuildNumber":"20240721.1","System.JobName":"__default","configuration":"Checked-no_tiered_compilation","DefinitionName":"runtime-coreclr   crossgen2   outerloop","System.JobAttempt":"1","System.JobId":"b98d1326-0c22-5cb0-0518-a01616fe181e","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"134","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1_R2R_Composite_osx_arm64_checked","System.PhaseAttempt":"1","System.StageAttempt":"1","architecture":"arm64","BuildId":"749562","Reason":"Schedule","Project":"public","System.StageName":"Build"} | Schedule
2024-07-22T02:19:49.496Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"configuration":"Checked-no_tiered_compilation","BuildId":"749526","System.JobAttempt":"1","DefinitionName":"runtime-coreclr   outerloop","Reason":"Schedule","System.JobName":"__default","AzurePipelinesTestRunId":"18967148","System.StageAttempt":"1","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked","Project":"public","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"108","architecture":"x64","BuildNumber":"20240721.3","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","System.StageName":"Build","operatingSystem":"OSX.1200.Amd64.Open"} | Schedule
2024-07-22T02:18:08.057Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1__osx_x64_checked","DefinitionName":"runtime-coreclr   outerloop","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","AzurePipelinesTestRunId":"18967128","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"108","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","System.JobAttempt":"1","BuildNumber":"20240721.3","System.StageAttempt":"1","BuildId":"749526","Project":"public","System.JobName":"__default"} | Schedule
2024-07-21T10:18:54.968Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"BuildNumber":"20240721.1","System.JobName":"__default","BuildId":"749181","System.JobAttempt":"1","Reason":"Schedule","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked","AzurePipelinesTestRunId":"18953760","configuration":"Checked-no_tiered_compilation","System.StageAttempt":"1","Project":"public","System.PhaseAttempt":"1","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","architecture":"x64","DefinitionId":"108","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr   outerloop"} | Schedule
2024-07-21T07:26:21.238Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"135","System.JobAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","Reason":"Schedule","System.JobName":"__default","System.PhaseAttempt":"1","Project":"public","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","BuildNumber":"20240720.1","DefinitionName":"coreclr-release-outerloop-nightly","System.StageAttempt":"1","System.StageName":"Build","architecture":"x64","AzurePipelinesTestRunId":"18952430","BuildId":"749114","System.PhaseName":"run_test_p1_R2R_osx_x64_release","configuration":"Release-no_tiered_compilation"} | Schedule
2024-07-21T07:17:28.489Z | runtime-coreclr crossgen2-composite gcstress | Checked-heapverify1 | osx.1200.arm64.open | arm64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.StageAttempt":"1","System.JobName":"__default","AzurePipelinesTestRunId":"18952284","DefinitionId":"141","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked","BuildId":"749113","Reason":"Schedule","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","configuration":"Checked-heapverify1","System.StageName":"Build","architecture":"arm64","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","BuildNumber":"20240720.1","System.PhaseAttempt":"1","System.JobAttempt":"1"} | Schedule
2024-07-21T06:18:18.543Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.arm64.open | arm64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"Reason":"Schedule","DefinitionId":"134","configuration":"Checked-no_tiered_compilation","System.StageName":"Build","DefinitionName":"runtime-coreclr   crossgen2   outerloop","System.JobAttempt":"1","System.JobId":"b98d1326-0c22-5cb0-0518-a01616fe181e","Project":"public","System.JobName":"__default","System.StageAttempt":"1","AzurePipelinesTestRunId":"18951998","BuildId":"749107","BuildNumber":"20240720.1","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.ARM64.Open","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1_R2R_Composite_osx_arm64_checked"} | Schedule
2024-07-21T06:17:36.66Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"DefinitionName":"runtime-coreclr crossgen2   outerloop","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","System.PhaseAttempt":"1","configuration":"Checked-no_tiered_compilation","System.StageName":"Build","AzurePipelinesTestRunId":"18951994","BuildId":"749107","DefinitionId":"134","System.JobName":"__default","System.JobId":"30d857d6-2812-5c31-5c67-e52c43389e0f","System.PhaseName":"run_test_p1_R2R_Composite_osx_x64_checked","BuildNumber":"20240720.1","operatingSystem":"OSX.1200.Amd64.Open","System.StageAttempt":"1","Reason":"Schedule","architecture":"x64","System.JobAttempt":"1"} | Schedule
2024-07-20T19:22:45.652Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"BuildNumber":"20240720.2","System.StageAttempt":"1","Project":"public","Reason":"Schedule","System.JobName":"__default","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","architecture":"x64","configuration":"Checked-no_tiered_compilation","AzurePipelinesTestRunId":"18946692","System.PhaseAttempt":"1","System.JobAttempt":"1","DefinitionName":"runtime-coreclr   outerloop","BuildId":"748944","System.PhaseName":"run_test_p1__osx_x64_checked","operatingSystem":"OSX.1200.Amd64.Open","System.StageName":"Build","DefinitionId":"108","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2024-07-20T07:27:15.343Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"Project":"public","AzurePipelinesTestRunId":"18933762","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","System.JobAttempt":"1","Reason":"Schedule","BuildId":"748560","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","System.StageAttempt":"1","DefinitionName":"coreclr-release-outerloop-nightly","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"135","System.JobName":"__default","BuildNumber":"20240719.1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","System.StageName":"Build","System.PhaseName":"run_test_p1_R2R_osx_x64_release"} | Schedule
2024-07-20T07:00:46.822Z | runtime-coreclr crossgen2 | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.JobName":"__default","operatingSystem":"OSX.1200.Amd64.Open","Reason":"Schedule","System.JobAttempt":"1","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","DefinitionId":"124","AzurePipelinesTestRunId":"18933468","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-no_tiered_compilation","BuildNumber":"20240719.1","System.PhaseAttempt":"1","architecture":"x64","BuildId":"748563","DefinitionName":"runtime-coreclr   crossgen2","Project":"public"} | Schedule
2024-07-20T06:24:55.525Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.JobName":"__default","System.JobAttempt":"1","configuration":"Checked-no_tiered_compilation","DefinitionName":"runtime-coreclr   crossgen2 outerloop","Reason":"Schedule","System.StageAttempt":"1","System.JobId":"30d857d6-2812-5c31-5c67-e52c43389e0f","System.PhaseName":"run_test_p1_R2R_Composite_osx_x64_checked","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","AzurePipelinesTestRunId":"18932828","Project":"public","architecture":"x64","BuildNumber":"20240719.1","DefinitionId":"134","System.StageName":"Build","BuildId":"748543","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2024-07-20T02:31:34.366Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"architecture":"x64","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked","Project":"public","System.PhaseAttempt":"1","DefinitionId":"108","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","System.StageAttempt":"1","configuration":"Checked-no_tiered_compilation","System.JobName":"__default","System.StageName":"Build","AzurePipelinesTestRunId":"18931014","BuildId":"748490","DefinitionName":"runtime-coreclr   outerloop","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20240719.3"} | Schedule
2024-07-19T07:26:42.813Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"Project":"public","DefinitionId":"135","System.StageAttempt":"1","configuration":"Release-no_tiered_compilation","architecture":"x64","System.JobAttempt":"1","AzurePipelinesTestRunId":"18892276","BuildId":"747260","Reason":"Schedule","System.JobName":"__default","BuildNumber":"20240718.1","System.PhaseName":"run_test_p1_R2R_osx_x64_release","System.PhaseAttempt":"1","System.JobId":"ed94b4c4-ff55-5657-ff29-58e87100eb6d","DefinitionName":"coreclr-release-outerloop-nightly","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","operatingSystem":"OSX.1200.Amd64.Open"} | Schedule
2024-07-19T07:08:24.08Z | runtime-coreclr crossgen2 | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","System.PhaseAttempt":"1","System.StageName":"Build","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked-no_tiered_compilation","BuildId":"747262","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","System.JobName":"__default","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2","Reason":"Schedule","AzurePipelinesTestRunId":"18891800","architecture":"x64","Project":"public","BuildNumber":"20240718.1"} | Schedule
2024-07-19T06:25:10.367Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.StageAttempt":"1","System.JobId":"30d857d6-2812-5c31-5c67-e52c43389e0f","architecture":"x64","BuildId":"747218","System.StageName":"Build","Project":"public","DefinitionName":"runtime-coreclr   crossgen2   outerloop","BuildNumber":"20240718.1","configuration":"Checked-no_tiered_compilation","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"134","System.PhaseAttempt":"1","System.JobName":"__default","AzurePipelinesTestRunId":"18890578","System.PhaseName":"run_test_p1_R2R_Composite_osx_x64_checked","Reason":"Schedule","System.JobAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open"} | Schedule
2024-07-19T06:22:53.83Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.arm64.open | arm64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"134","System.PhaseName":"run_test_p1_R2R_Composite_osx_arm64_checked","configuration":"Checked-no_tiered_compilation","System.JobId":"b98d1326-0c22-5cb0-0518-a01616fe181e","architecture":"arm64","System.StageName":"Build","System.PhaseAttempt":"1","BuildNumber":"20240718.1","System.JobAttempt":"1","operatingSystem":"OSX.1200.ARM64.Open","System.StageAttempt":"1","Reason":"Schedule","DefinitionName":"runtime-coreclr   crossgen2   outerloop","AzurePipelinesTestRunId":"18890536","Project":"public","BuildId":"747218"} | Schedule
2024-06-28T02:45:21.083Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd | Failed | {"System.JobName":"__default","architecture":"x64","System.JobId":"2bb87d59-31ba-55f9-0713-03158c3fd52f","configuration":"Checked-no_tiered_compilation","System.JobAttempt":"1","DefinitionId":"108","AzurePipelinesTestRunId":"18157254","BuildId":"723534","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","DefinitionName":"runtime-coreclr   outerloop","Reason":"Schedule","Project":"public","System.PhaseName":"run_test_p1_R2R_CG2_osx_x64_checked","System.StageAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20240627.5"} | Schedule

</details>

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=769733
Build error leg or test failing: tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd
Pull request: https://github.com/dotnet/runtime/pull/106132

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "eventsourceerror.*Segmentation fault",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=769251
**Error message validated:** `[eventsourceerror.*Segmentation fault`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/8/2024 6:56:11 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[772519](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772519)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772519&view=ms.vss-test-web.build-test-results-tab&runId=19746196&resultId=111458)|dotnet/runtime#106252|
|[772531](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772531)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772531&view=ms.vss-test-web.build-test-results-tab&runId=19746234&resultId=106068)|dotnet/runtime#106254|
|[772444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772444)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772444&view=ms.vss-test-web.build-test-results-tab&runId=19741816&resultId=111458)|dotnet/runtime#105545|
|[772292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772292)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772292&view=ms.vss-test-web.build-test-results-tab&runId=19736684&resultId=111458)|dotnet/runtime#106238|
|[771517](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771517)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771517&view=ms.vss-test-web.build-test-results-tab&runId=19712652&resultId=111454)|dotnet/runtime#106185|
|[771458](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771458)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771458&view=ms.vss-test-web.build-test-results-tab&runId=19709406&resultId=106097)||
|[771303](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771303)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771303&view=ms.vss-test-web.build-test-results-tab&runId=19705478&resultId=106064)|dotnet/runtime#106072|
|[770472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770472)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770472&view=ms.vss-test-web.build-test-results-tab&runId=19703972&resultId=111443)|dotnet/runtime#106169|
|[770955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770955)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770955&view=ms.vss-test-web.build-test-results-tab&runId=19696860&resultId=111443)|dotnet/runtime#100294|
|[770038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770038)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770038&view=ms.vss-test-web.build-test-results-tab&runId=19668422&resultId=111452)|dotnet/runtime#106153|
|[770027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770027)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770027&view=ms.vss-test-web.build-test-results-tab&runId=19667890&resultId=108891)|dotnet/runtime#106152|
|[769887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769887)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769887&view=ms.vss-test-web.build-test-results-tab&runId=19662664&resultId=106161)|dotnet/runtime#106090|
|[769733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769733)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769733&view=ms.vss-test-web.build-test-results-tab&runId=19657518&resultId=106060)|dotnet/runtime#106132|
|[769251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769251)|dotnet/runtime|[tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769251&view=ms.vss-test-web.build-test-results-tab&runId=19637068&resultId=113708)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|14|14|

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes https://github.com/dotnet/runtime/issues/106113

https://github.com/dotnet/runtime/pull/106040 previously only blocked EventPipeEventProvider's Dispose for the EventPipe Provider's deferred deletion scenarios. This PR extends the blocking behavior for non deferred deletion scenarios as well, so EventPipeEventProvider.Dispose/Unregister will *always* be blocked by in flight callbacks.

### CODE REVIEW

**Comment by mdh1418** [comment]
No eventsourceerror in first coreclr outerloop run

File: src/native/eventpipe/ep.c [hunk 1]
```diff
@@ -1319,22 +1319,15 @@ ep_delete_provider (EventPipeProvider *provider)
...
-			// as deleting the provider with an active tracing session will block
-			// until all of the provider's callbacks are completed.
-			if (provider->callbacks_pending > 0)
-				wait_for_provider_callbacks_completion = true;
-		} else {
-			config_delete_provider (ep_config_get (), provider);
-		}
+		// The callback func must be set to null,
+		// otherwise callbacks might never stop coming.
+		provider->callback_func = NULL;
```
Comment (noahfalk) [inline src/native/eventpipe/ep.c:1324]: Any reason not to call `ep_provider_set_delete_deferred(provider,true)` here? Down below would then be:
```
if(!enabled()) {
    config_delete_provider (ep_config_get (), provider);
}
```

File: src/native/eventpipe/ep.c [hunk 2]
```diff
@@ -1344,6 +1337,15 @@ ep_delete_provider (EventPipeProvider *provider)
 	if (wait_for_provider_callbacks_completion)
 		ep_rt_wait_event_wait (&provider->callbacks_complete_event, EP_INFINITE_WAIT, false);
 
+	EP_LOCK_ENTER (section2)
+		if (enabled ()) {
+			// Save the provider until the end of the tracing session.
+			ep_provider_set_delete_deferred (provider, true);
```
Comment (noahfalk) [inline src/native/eventpipe/ep.c:1343]: Looking around while reviewing this I think I spotted a pre-existing bug. Its fine if you want to make it a separate PR but I think it would be pretty easy to include a mitigation in this one. 

https://github.com/dotnet/runtime/blob/0f2ce100fb386fec5eb784cf501ee95881a14e47/src/native/eventpipe/ep.c#L647 is deleting deferred providers at the end of a session, but I see nothing that prevents a 2nd session that is still in progress from having a reference to the same provider. If that 2nd session dereferenced the deleted provider I'd expect an AV or other undefined behavior. To safely delete a provider we need to ensure that no session is using it. I think we'd be better off letting undeleted deferred providers accumulate vs potentially deleting them while they are still in use by a 2nd session. You could just comment out the line of code that deletes deferred providers and add a comment saying we are mitigating the potential use-after-free by allowing them to accumulate. Its possible to delete them more aggressively with session reference counting but I'd question if its worth spending the extra dev-time on given the very atypical scenario it would take to use a lot of memory that way.

File: src/native/eventpipe/ep.c (hunk 1 above)
Comment (mdh1418) [reply src/native/eventpipe/ep.c:1324]: Ah good point since `config_delete_provider` will unregister + free the provider, then unconditionally calling `ep_provider_set_delete_deferred` works.

File: src/native/eventpipe/ep.c (hunk 2 above)
Comment (mdh1418) [reply src/native/eventpipe/ep.c]: Commented out the line that deletes deferred providers at the end of `disable_holding_lock`.

**Review by noahfalk — APPROVED** [review]
👍
