### PR TITLE
Fix Diagnostic port suspension message doesn't report expected port name

### LINKED ISSUE #75581: Diagnostic port suspension message doesn't report expected port name
### Description

If the diagnostic port suspension message is written to the console output in .NET 7, the diagnostic port name is missing.

### Reproduction Steps

1. dotnet new console -f net7.0 -o test
2. cd .\test\
3. dotnet build
4. cd .\bin\Debug\net7.0\
5. $env:DOTNET_DiagnosticPorts="nonexistantport"
6. .\test.exe

### Expected behavior

Output should show:

```
The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a Diagnostic Port.
DOTNET_DiagnosticPorts="nonexistantport"
DOTNET_DefaultDiagnosticPortSuspend=0
```

### Actual behavior

Actual output:

```
The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a Diagnostic Port.
DOTNET_DiagnosticPorts=""
DOTNET_DefaultDiagnosticPortSuspend=0
```

### Regression?

Yes, works on .NET 6 and lower.

### Known Workarounds

None

### Configuration

Windows x64 .NET SDK version 7.0.100-preview.7.22377.5

### Other information

_No response_

### PR DESCRIPTION
**Pull request by nickyMcDonald**
Fixes #75581

I repo’d #75581 on Windows and verified this works. Apparently, the static member function CLRConfigNoCache::Get from the header ‘src/coreclr/inc/clrconfignocache.h’ first copies the prefix “DOTNET_” to a char array and then appends “DOTNET_ DiagnosticPorts” resulting in “DOTNET_DOTNET_ DiagnosticPorts” which when passed to getenv() returns null because it doesn’t exist in the environment table. This works by instead appending “DiagnosticPorts” resulting in “DOTNET_ DiagnosticPorts” which does exist in the environment table.

### CODE REVIEW

File: src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h [hunk 1]
```diff
@@ -302,7 +302,7 @@ ds_rt_server_log_pause_message (void)
 {
 	STATIC_CONTRACT_NOTHROW;
 
-	const char diagPortsName[] = "DOTNET_DiagnosticPorts";
+	const char diagPortsName[] = "DiagnosticPorts";
```
Comment (hoyosjs) [inline src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h:305]: Thanks! However, now the print that happens below will fail to show the right name. Can you please add the `DOTNET_` prefix to the config on line 316?

**Review by hoyosjs — APPROVED** [review]
Minor comment, looks good otherwise.

File: src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h (hunk 1 above)
Comment (davmason) [reply src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h:305]: Is there a reason we can't use the standard `CLRConfig::EXTERNAL_DOTNET_DiagnosticPorts` instead of having an explicit string?

Comment (n77y) [reply src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h:305]: > Is there a reason we can't use the standard `CLRConfig::EXTERNAL_DOTNET_DiagnosticPorts` instead of having an explicit string?

`CLRConfigNoCache::Get` seems like it only accepts ANSI but `CLRConfig::EXTERNAL_DOTNET_DiagnosticPorts` is Unicode.
This change was introduced on https://github.com/dotnet/runtime/commit/c3e0c8a3dcaa9be860953931fd1bf8cd579e8758

Comment (hoyosjs) [reply src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h:305]: I'd gotten to the same uft8 -> utf16 conclusion. Do you see a better way @davmason? Perhaps we could do something like `MAKE_UTF8PTR_FROMWIDE_NOTHROW` on the `ConfigStringInfo.name`? Don't know if it matters, but also doing that brings in all of utilcode. This is in the runtime specific part, so maybe that's not as bad.
