### PR TITLE
Use ConcurrentDictionary to avoid threading issues

### LINKED ISSUE #102136: PropertyDescriptor.AddValueChanged is not thread-safe
### Description

In the System.ComponentModel.PropertyDescriptor class, the AddValueChanged and RemoveValueChanged methods mutate `private Dictionary<object, EventHandler?>? _valueChangedHandlers` without locking.  This causes errors if multiple threads add or remove value-changed event handlers for different components in parallel.  Because TypeDescriptor caches the PropertyDescriptor instances, it is normal that multiple threads use the same PropertyDescriptor instance.

### Reproduction Steps

This demo program attempts to trigger the bug in one of three ways, depending on the command line:

- [PropertyDescriptor](https://learn.microsoft.com/dotnet/api/system.componentmodel.propertydescriptor?view=netstandard-2.0): Hits the bug, but might not be a realistic scenario.
- [BindingSource](https://learn.microsoft.com/dotnet/api/system.windows.forms.bindingsource?view=windowsdesktop-8.0): Hits the bug, but BindingSource is defined in Windows Forms and would typically be used from a UI thread only.  In the Debug configuration, the dictionary corruption causes an assertion failure before the InvalidOperationException.
- [BindingList\<T\>](https://learn.microsoft.com/dotnet/api/system.componentmodel.bindinglist-1?view=netstandard-2.0): Doesn't hit the bug because it checks for INotifyPropertyChange, rather than adding event handlers via PropertyDescriptor.

#### ConsoleApp1.csproj

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net8.0-windows;net9.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>

    <DefineConstants Condition="$(UseWindowsForms) == 'true'">$(DefineConstants);UseWindowsForms</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework) == 'net48'">
    <Reference Include="System.Windows.Forms" Condition="$(UseWindowsForms) == 'true'" />
  </ItemGroup>

</Project>
```

#### Program.cs

```csharp
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;

#if UseWindowsForms
using System.Windows.Forms;
#endif

namespace ConsoleApp1
{
    internal static class Program
    {
        private static int Main(string[] args)
        {
            if (args.Length != 2
                || !long.TryParse(args[1], out long count))
            {
                ShowUsage(Console.Error);
                return 1;
            }

            Console.WriteLine("Initial check.");
            PropertyDescriptor property = TypeDescriptor.GetDefaultProperty(componentType: typeof(Notifier));
            Debug.Assert(property.SupportsChangeEvents, "Must support change events.");

            switch (args[0])
            {
                case "BindingList":
                    // No problem.
                    Console.WriteLine("Parallel looping with BindingList...");
                    Parallel.For(0, count, _ => PokeViaBindingList());
                    Console.WriteLine("Finished.");
                    break;

                case "BindingSource":
#if UseWindowsForms
                    Console.WriteLine("Parallel looping with BindingSource...");
                    Parallel.For(0, count, _ => PokeViaBindingSource());
                    Console.WriteLine("Finished.");
                    break;
#else
                    Console.Error.WriteLine("BindingSource requires Windows Forms.");
                    return 1;
#endif

                case "PropertyDescriptor":
                    // Not thread-safe.
                    Console.WriteLine("Parallel looping with PropertyDescriptor...");
                    Parallel.For(0, count, _ => PokeViaPropertyDescriptor());
                    Console.WriteLine("Finished.");
                    break;

                default:
                    ShowUsage(Console.Error);
                    return 1;
            }

            return 0;
        }

        private static void ShowUsage(TextWriter textWriter)
        {
            string appName = System.Reflection.Assembly.GetEntryAssembly().GetName().Name;
            textWriter.WriteLine($"Usage: {appName} (BindingList | BindingSource | PropertyDescriptor) count");
        }

        // No problems here.
        private static void PokeViaBindingList()
        {
            BindingList<Notifier> bindingList = new BindingList<Notifier>();
            Debug.Assert(((IRaiseItemChangedEvents)bindingList).RaisesItemChangedEvents, "Must raise ItemChanged events.");

            int itemChangeCount = 0;
            ListChangedEventHandler listChangedHandler = (sender, e) =>
            {
                if (e.ListChangedType == ListChangedType.ItemChanged)
                {
                    itemChangeCount++;
                }
            };
            bindingList.ListChanged += listChangedHandler;

            Notifier notifier = new Notifier();
            bindingList.Add(notifier);
            Debug.Assert(itemChangeCount == 0, "Expected itemChangeCount == 0");
            notifier.Number = 42;
            Debug.Assert(itemChangeCount == 1, "Expected itemChangeCount == 1");

            bindingList.ListChanged -= listChangedHandler;
            bindingList.Clear();
        }

#if UseWindowsForms
        private static void PokeViaBindingSource()
        {
            using (BindingSource bindingSource = new BindingSource())
            {
                // Because List<T> implements neither IRaiseItemChangedEvents nor IBindingList,
                // BindingSource will hook the property-change events of the current item only.
                bindingSource.DataSource = new List<Notifier>();

                bindingSource.CurrencyManager.PositionChanged += (sender, e) => { };

                int itemChangeCount = 0;
                ListChangedEventHandler listChangedHandler = (sender, e) =>
                {
                    if (e.ListChangedType == ListChangedType.ItemChanged)
                    {
                        itemChangeCount++;
                    }
                };
                bindingSource.ListChanged += listChangedHandler;

                Notifier notifier = new Notifier();
                bindingSource.Add(notifier);

                Debug.Assert(bindingSource.Current == notifier, "The item should have become current");
                Debug.Assert(itemChangeCount == 0, "Expected itemChangeCount == 0", $"Is actually {itemChangeCount}");
                notifier.Number = 42;
                Debug.Assert(itemChangeCount == 1, "Expected itemChangeCount == 1", $"Is actually {itemChangeCount}");

                bindingSource.ListChanged -= listChangedHandler;
            }
        }
#endif // UseWindowsForms

        private static void PokeViaPropertyDescriptor()
        {
            Notifier component = new Notifier();
            PropertyDescriptor property = TypeDescriptor.GetDefaultProperty(component: component);
            Debug.Assert(property.SupportsChangeEvents, "Must support change events.");

            EventHandler valueChangedHandler = (sender, e) => { };
            property.AddValueChanged(component, valueChangedHandler);
            property.RemoveValueChanged(component, valueChangedHandler);
        }
    }

    [DefaultProperty(nameof(Number))]
    internal sealed class Notifier : INotifyPropertyChanged
    {
        private int number;

        public int Number
        {
            get => this.number;

            set
            {
                this.number = value;
                this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(this.Number)));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
```

#### Run

dotnet run --configuration=Release --framework=net9.0-windows -- PropertyDescriptor 1000000

### Expected behavior

Should not throw any exceptions.  Indeed it doesn't throw, if the parallel loop count is only 1.

```
Initial check.
Parallel looping with PropertyDescriptor...
Finished.
```

### Actual behavior

Throws InvalidOperationException because invalid parallel access corrupts the dictionary.

```
Initial check.
Parallel looping with PropertyDescriptor...
Unhandled exception. System.AggregateException: One or more errors occurred. (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.) (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.)
 ---> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Collections.Generic.CollectionExtensions.GetValueOrDefault[TKey,TValue](IReadOnlyDictionary`2 dictionary, TKey key, TValue defaultValue)
   at System.ComponentModel.ReflectPropertyDescriptor.AddValueChanged(Object component, EventHandler handler)
   at ConsoleApp1.Program.PokeViaPropertyDescriptor() in [REDACTED]\ConsoleApp1\Program.cs:line 136
   at ConsoleApp1.Program.<>c.<Main>b__0_2(Int64 _) in [REDACTED]\ConsoleApp1\Program.cs:line 53
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int64 fromInclusive, Int64 toExclusive, Action`1 body)
   at ConsoleApp1.Program.Main(String[] args) in [REDACTED]\ConsoleApp1\Program.cs:line 53
 ---> (Inner Exception #1) System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Collections.Generic.CollectionExtensions.GetValueOrDefault[TKey,TValue](IReadOnlyDictionary`2 dictionary, TKey key, TValue defaultValue)
   at System.ComponentModel.ReflectPropertyDescriptor.AddValueChanged(Object component, EventHandler handler)
   at ConsoleApp1.Program.PokeViaPropertyDescriptor() in [REDACTED]\ConsoleApp1\Program.cs:line 136
   at ConsoleApp1.Program.<>c.<Main>b__0_2(Int64 _) in [REDACTED]\ConsoleApp1\Program.cs:line 53
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

### Regression?

No, it doesn't work in .NET Framework either.

### Known Workarounds

_No response_

### Configuration

.NET 9.0.0-preview.3.24172.9 on Windows 10.

The thread-unsafety of PropertyDescriptor.AddValueChange is not specific to Windows.  In the .NET Runtime however, only WPF and Windows Forms seem to call this method; that may make the bug less likely to affect applications on other operating systems.

### Other information

Related to <https://github.com/dotnet/runtime/issues/30024> and <https://github.com/dotnet/runtime/issues/92394>.  The bug corrupts this dictionary:

<https://github.com/dotnet/runtime/blob/9e6ba1f68c6a9c7206dacdf1e4cac67ea19931eb/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs#L19>

### LINKED ISSUE #103823: NuGet restore failing with NullReferenceException
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=715438
Build error leg or test failing: Build / windows-x64 release CrossDac / Build product
Pull request: https://github.com/dotnet/runtime/pull/103806

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "NuGet.RestoreEx.targets.*: error : Object reference not set to an instance of an object.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=715438
**Error message validated:** `[NuGet.RestoreEx.targets.*: error : Object reference not set to an instance of an object.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/21/2024 3:51:17 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[2529303](https://dev.azure.com/dnceng/internal/_build/results?buildId=2529303)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2529303/logs/471)||
|[775106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775106)|dotnet/runtime|Build native test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/775106/logs/441)|dotnet/runtime#106218|
|[771952](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771952)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/771952/logs/795)|dotnet/runtime#106037|
|[771634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771634)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/771634/logs/768)|dotnet/runtime#105771|
|[771585](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771585)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/771585/logs/248)|dotnet/runtime#100294|
|[770038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770038)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/770038/logs/893)|dotnet/runtime#106153|
|[769492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769492)|dotnet/runtime|Copy native test components to test output folder|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/769492/logs/664)|dotnet/runtime#106118|
|[769435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769435)|dotnet/runtime|Generate test wrappers|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/769435/logs/2106)||
|[767757](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767757)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/767757/logs/312)|dotnet/runtime#105783|
|[767236](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767236)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/767236/logs/1296)|dotnet/runtime#99596|
|[767175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767175)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/767175/logs/719)|dotnet/runtime#106013|
|[767109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767109)|dotnet/runtime|Generate test wrappers|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/767109/logs/822)|dotnet/runtime#106010|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|12|

### LINKED ISSUE #104221: Assertion failed under System.ComponentModel.TypeDescriptor.CheckDefaultProvider
From https://dev.azure.com/dnceng-public/public/_build/results?buildId=725665&view=ms.vss-test-web.build-test-results-tab&runId=18226406&resultId=209449&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

```
  Starting:    System.Data.Common.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.Data.Tests.DataSetTypedDataSetTest.TypedDataSet [SKIP]
      Condition(s) not met: "IsBinaryFormatterSupported"
    System.Data.Tests.DataSetTest2.Bug537229_BinFormatSerializer_Test [SKIP]
      Condition(s) not met: "IsBinaryFormatterSupported"
    System.Data.Tests.DataTableReadXmlSchemaTest.XsdSchemaSerializationIgnoresLocale [SKIP]
      Condition(s) not met: "IsBinaryFormatterSupported"
    System.Data.Tests.DataTableReadXmlSchemaTest.XsdSchemaDeserializationIgnoresLocale [SKIP]
      Condition(s) not met: "IsBinaryFormatterSupported"
    System.Data.Tests.DataSetTest.SerializationFormat_Binary_works_with_appconfig_switch [SKIP]
      Condition(s) not met: "RemoteExecutorBinaryFormatter"
Process terminated. Assertion failed.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:line 446
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:line 1394
   at System.ComponentModel.TypeDescriptor.CheckDefaultProvider(Type type) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 336
   at System.ComponentModel.TypeDescriptor.NodeFor(Type type, Boolean createDelegator) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 1649
   at System.ComponentModel.TypeDescriptor.NodeFor(Type type) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 1629
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 1773
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 1711
   at System.ComponentModel.TypeDescriptor.GetCache(Object instance) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 786
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 1493
   at System.ComponentModel.TypeDescriptor.GetProperties(Object component, Boolean noCustomTypeDesc) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 1403
   at System.ComponentModel.TypeDescriptor.GetProperties(Object component) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 1385
   at System.Data.XmlTreeGen.AddXdoProperties(Object instance, XmlElement root) in /_/src/libraries/System.Data.Common/src/System/Data/xmlsaver.cs:line 117
   at System.Data.XmlTreeGen.SchemaTree(XmlDocument xd, XmlWriter xmlWriter, DataSet ds, DataTable dt, Boolean writeHierarchy) in /_/src/libraries/System.Data.Common/src/System/Data/xmlsaver.cs:line 690
   at System.Data.XmlTreeGen.Save(DataSet ds, DataTable dt, XmlWriter xw, Boolean writeHierarchy, Converter`2 multipleTargetConverter) in /_/src/libraries/System.Data.Common/src/System/Data/xmlsaver.cs:line 1144
   at System.Data.XmlTreeGen.Save(DataSet ds, DataTable dt, XmlWriter xw, Boolean writeHierarchy) in /_/src/libraries/System.Data.Common/src/System/Data/xmlsaver.cs:line 1127
   at System.Data.XmlDataTreeWriter.Save(XmlWriter xw, Boolean writeSchema) in /_/src/libraries/System.Data.Common/src/System/Data/xmlsaver.cs:line 2878
   at System.Data.DataTable.WriteXml(XmlWriter writer, XmlWriteMode mode, Boolean writeHierarchy) in /_/src/libraries/System.Data.Common/src/System/Data/DataTable.cs:line 5418
   at System.Data.DataTable.WriteXml(Stream stream, XmlWriteMode mode, Boolean writeHierarchy) in /_/src/libraries/System.Data.Common/src/System/Data/DataTable.cs:line 5344
   at System.Data.Tests.DataTableTest4.XmlTest7() in /_/src/libraries/System.Data.Common/tests/System/Data/DataTableTest4.cs:line 760
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=725665
Build error leg or test failing: System.Data.Common.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/104219

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at System.ComponentModel.TypeDescriptor.CheckDefaultProvider(Type type)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=725665
**Error message validated:** `[at System.ComponentModel.TypeDescriptor.CheckDefaultProvider(Type type)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/1/2024 6:48:36 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[2487307](https://dev.azure.com/dnceng/internal/_build/results?buildId=2487307)|dotnet-runtime|[Microsoft.Extensions.Options.Tests.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2487307&view=ms.vss-test-web.build-test-results-tab&runId=53822583&resultId=214549)||
|[725665](https://dev.azure.com/dnceng-public/public/_build/results?buildId=725665)|dotnet/runtime|[System.Data.Common.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=725665&view=ms.vss-test-web.build-test-results-tab&runId=18226406&resultId=209449)|dotnet/runtime#104219|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|2|

### PR DESCRIPTION
**Pull request by steveharter**
Address various threading issues including:
Fixes https://github.com/dotnet/runtime/issues/104221
Fixes https://github.com/dotnet/runtime/issues/103823
Fixes https://github.com/dotnet/runtime/issues/102136

Local testing included running all tests in a loop 300x in both Release and Debug builds.

Linking here other threading issues fixed in this area fixed during 9.0:
https://github.com/dotnet/runtime/issues/30024
https://github.com/dotnet/runtime/issues/92394
https://github.com/dotnet/runtime/issues/97179
https://github.com/dotnet/runtime/issues/103265

### CODE REVIEW

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs [hunk 1]
```diff
@@ -165,10 +167,11 @@ public virtual void AddValueChanged(object component, EventHandler handler)
             ArgumentNullException.ThrowIfNull(component);
             ArgumentNullException.ThrowIfNull(handler);
 
-            _valueChangedHandlers ??= new Dictionary<object, EventHandler?>();
-
-            EventHandler? h = _valueChangedHandlers.GetValueOrDefault(component, defaultValue: null);
-            _valueChangedHandlers[component] = (EventHandler?)Delegate.Combine(h, handler);
+            lock (s_internalSyncObject)
```
Comment (lilinus) [inline src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs:170]: Perhaps we can use `LazyInitializer. EnsureInitialized` here? Then the sync lock doesn't have to be allocated until needed.

Comment (steveharter) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs]: Sure. Thanks

**Review by AustinWise — COMMENTED** [review]
You could potentially use features of the ConcurrentDictionary to avoid the need for a lock. See this gist: https://gist.github.com/AustinWise/92f293463124cdbf95e702946502b636

**Review by buyaa-n — APPROVED** [review]
LGTM

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs [hunk 2]
```diff
@@ -165,10 +170,11 @@ public virtual void AddValueChanged(object component, EventHandler handler)
...
 
-            _valueChangedHandlers ??= new Dictionary<object, EventHandler?>();
-
-            EventHandler? h = _valueChangedHandlers.GetValueOrDefault(component, defaultValue: null);
-            _valueChangedHandlers[component] = (EventHandler?)Delegate.Combine(h, handler);
+            lock (SyncObject)
+            {
+                _valueChangedHandlers ??= new ConcurrentDictionary<object, EventHandler?>();
+                _valueChangedHandlers.AddOrUpdate(component, handler, (k, v) => (EventHandler?)Delegate.Combine(v));
+            }
```
[the remark this answers is not in the document]
Comment (steveharter) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs]: Yes thanks - also added a test to differentiate between delegate update vs. add.

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs [hunk 3]
```diff
@@ -433,15 +439,18 @@ public virtual void RemoveValueChanged(object component, EventHandler handler)
...
             if (_valueChangedHandlers != null)
             {
-                EventHandler? h = _valueChangedHandlers.GetValueOrDefault(component, defaultValue: null);
-                h = (EventHandler?)Delegate.Remove(h, handler);
-                if (h != null)
-                {
-                    _valueChangedHandlers[component] = h;
-                }
-                else
+                lock (SyncObject)
```
[the remark this answers is not in the document]
Comment (steveharter) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs:443]: I think using the lock as-is is more straightforward. Also, the Remove is not likely to be used as often.

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs [hunk 4]
```diff
@@ -165,10 +170,12 @@ public virtual void AddValueChanged(object component, EventHandler handler)
...
 
-            _valueChangedHandlers ??= new Dictionary<object, EventHandler?>();
+            if (_valueChangedHandlers is null)
+            {
+                Interlocked.CompareExchange(ref _valueChangedHandlers, new ConcurrentDictionary<object, EventHandler?>(), null);
+            }
 
-            EventHandler? h = _valueChangedHandlers.GetValueOrDefault(component, defaultValue: null);
-            _valueChangedHandlers[component] = (EventHandler?)Delegate.Combine(h, handler);
+            _valueChangedHandlers.AddOrUpdate(component, handler, (k, v) => (EventHandler?)Delegate.Combine(v, handler));
```
Comment (jkotas) [inline src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs:178]: Can this lock-free AddOrUpdate have bad race conditions with Remove?

Comment (jkotas) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs:178]: I think either both Add and Remove need be lock-free as proposed in the other comment, or both need to take the lock.

Comment (steveharter) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs:178]: I was just thinking about this as well; I'll revert this since it will collide with the lock in Remove.

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs [hunk 5]
```diff
@@ -165,10 +170,11 @@ public virtual void AddValueChanged(object component, EventHandler handler)
             ArgumentNullException.ThrowIfNull(component);
             ArgumentNullException.ThrowIfNull(handler);
 
-            _valueChangedHandlers ??= new Dictionary<object, EventHandler?>();
-
-            EventHandler? h = _valueChangedHandlers.GetValueOrDefault(component, defaultValue: null);
-            _valueChangedHandlers[component] = (EventHandler?)Delegate.Combine(h, handler);
+            lock (SyncObject)
+            {
+                _valueChangedHandlers ??= new ConcurrentDictionary<object, EventHandler?>();
```
Comment (stephentoub) [inline src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs:175]: Am I reading this correctly that there's one of these dictionaries possible per property? Are many writes expected? The default concurrency level for ConcurrentDictionary is Environment.ProcessorCount, meaning each of these CDs is going to have that many locks created for it under the covers at a minimum. If the thread-safety here is just precautionary and a lot of concurrency isn't expected, consider using the constructor that allows you to specify a concurrency level and set it to 1.

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs [hunk 6]
```diff
@@ -864,15 +864,11 @@ internal Type[] GetPopulatedTypes(Module module)
 
             lock (TypeDescriptor.s_commonSyncObject)
```
Comment (stephentoub) [inline src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs:865]: Is this lock still needed?

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs (hunk 5 above)
Comment (steveharter) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs]: Thanks. Changing to 1

File: src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs (hunk 6 above)
Comment (steveharter) [reply src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs]: It doesn't appear to be necessary anymore since the ConcurrentDictionary enumerator is thread-safe. Thanks
