### PR TITLE
[wasm][debugger] Fixing async locals in nested ContinueWith blocks

### LINKED ISSUE #41984: [wasm][debugger] Async locals in a `ContinueWith` block
wip

### PR DESCRIPTION
**Pull request by thaystg**
- Adding test to close https://github.com/dotnet/runtime/issues/41984
- Adding a lot of old tests written by @radical 
- Fixing the behavior of getting async locals in nested ContinueWith blocks.

### CODE REVIEW

**Review by lewing — APPROVED** [review]

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 1]
```diff
@@ -1710,6 +1710,48 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+            {
+                if (asyncLocal["name"].Value<string>().EndsWith("__this"))
+                {
+                    asyncLocal["name"] = "this";
+                    asyncLocalsFull.Add(asyncLocal);
+                }
+                else if (asyncLocal["name"].Value<string>().StartsWith("<>8__") ||
+                        asyncLocal["name"].Value<string>().StartsWith("<>f__ref") ||
+                        asyncLocal["name"].Value<string>().StartsWith("$locvar") ||
+                        asyncLocal["name"].Value<string>().StartsWith("CS$<>")) //same code that has on debugger-libs
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1726]: Where is the similar code in debugger-libs?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 2]
```diff
@@ -1710,6 +1710,48 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                {
+                    DotnetObjectId.TryParse(asyncLocal?["value"]?["objectId"]?.Value<string>(), out DotnetObjectId dotnetObjectId);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1728]: `dotnetObjectId` could be null

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 3]
```diff
@@ -1710,6 +1710,48 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                    int objectIdToGetInfo = int.Parse(dotnetObjectId.Value);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1729]: maybe TryParse?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 4]
```diff
@@ -1710,6 +1710,48 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                        asyncLocalsFull = new JArray(asyncLocalsFull.Union(hoistedLocalVariable));
+                    }
+                }
+                else if (asyncLocal["name"].Value<string>().Contains("<>"))
+                {
+                    continue;
+                }
+                else if (asyncLocal["name"].Value<string>().Contains('<'))
+                {
+                    asyncLocal["name"] = Regex.Match(asyncLocal["name"].Value<string>(), @"\<([^)]*)\>").Groups[1].Value;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1744]: Couldn't the regex fail to match? Maybe with some newer roslyn, which breaks the pattern in some way?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 5]
```diff
@@ -1710,6 +1710,48 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                        var asyncLocalsFromObject = await GetObjectValues(sessionId, objectIdToGetInfo, true, false, false, false, token);
+                        var hoistedLocalVariable = await GetHoistedLocalVariables(sessionId, objectAlreadyRead, asyncLocalsFromObject, token);
+                        asyncLocalsFull = new JArray(asyncLocalsFull.Union(hoistedLocalVariable));
+                    }
+                }
+                else if (asyncLocal["name"].Value<string>().Contains("<>"))
+                {
+                    continue;
+                }
+                else if (asyncLocal["name"].Value<string>().Contains('<'))
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1742]: nit: add a comment example of the pattern that we are looking for

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 6]
```diff
@@ -1710,6 +1710,48 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                    int objectIdToGetInfo = int.Parse(dotnetObjectId.Value);
+                    if (!objectAlreadyRead.Contains(objectIdToGetInfo))
+                    {
+                        objectAlreadyRead.Add(objectIdToGetInfo);
+                        var asyncLocalsFromObject = await GetObjectValues(sessionId, objectIdToGetInfo, true, false, false, false, token);
+                        var hoistedLocalVariable = await GetHoistedLocalVariables(sessionId, objectAlreadyRead, asyncLocalsFromObject, token);
+                        asyncLocalsFull = new JArray(asyncLocalsFull.Union(hoistedLocalVariable));
+                    }
+                }
+                else if (asyncLocal["name"].Value<string>().Contains("<>"))
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1738]: Is the `<>` is a specific part of the string, or anywhere?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 7]
```diff
@@ -1725,18 +1767,13 @@ public async Task<JArray> StackFrameGetValues(SessionId sessionId, MethodInfo me
 
             if (await IsAsyncMethod(sessionId, method.DebuggerId, token))
             {
+                List<int> objectAlreadyRead = new List<int>();
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1770]:
```suggestion
                List<int> objectAlreadyRead = new();
```

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 8]
```diff
@@ -1710,6 +1710,48 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
             return retDebuggerCmdReader.ReadByte() == 1 ; //token
         }
 
+        public async Task<JArray> GetHoistedLocalVariables(SessionId sessionId, List<int> objectAlreadyRead, JArray asyncLocals, CancellationToken token)
+        {
+            JArray asyncLocalsFull = new JArray();
+            foreach (var asyncLocal in asyncLocals)
+            {
+                if (asyncLocal["name"].Value<string>().EndsWith("__this"))
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1718]: Maybe extract `(asyncLocal["name"].Value<string>()` into a local

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 7 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1770]: nit: pass the objectId to the new method, and the list can be created, and used in that method.
nit: rename to plural - `objectsAlreadyRead`

File: src/mono/wasm/debugger/DebuggerTestSuite/AsyncTests.cs [hunk 9]
```diff
@@ -0,0 +1,104 @@
...
+    {
+
+        // FIXME: method with multiple async blocks - so that we have two separate classes for that method!
+        // FIXME: nested blocks
+        // FIXME: Confirm the actual bp location
+        // FIXME: check object properties..
+
+        //FIXME: function name
+        [Fact] // Same as Instance case
+        public async Task AsyncLocalsInContinueWithStaticBlock() => await CheckInspectLocalsAtBreakpointSite(
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/AsyncTests.cs:23]: This can be combined with `AsyncLocalsInContinueWithInstanceBlock`. They are identical, except for the method name in two places.

File: src/mono/wasm/debugger/DebuggerTestSuite/AsyncTests.cs [hunk 10]
```diff
@@ -0,0 +1,104 @@
...
+             "DebuggerTests.AsyncTests.ContinueWithTests", "ContinueWithStaticAsync", 5, "<ContinueWithStaticAsync>b__3_0",
+             "window.setTimeout(function() { invoke_static_method('[debugger-test] DebuggerTests.AsyncTests.ContinueWithTests:RunAsync'); })",
+             wait_for_event_fn: async (pause_location) =>
+             {
+                var frame_locals = await GetProperties(pause_location["callFrames"][0]["callFrameId"].Value<string>());
+                Console.WriteLine (frame_locals);
```
Comment (radical) [inline src/mono/wasm/debugger/DebuggerTestSuite/AsyncTests.cs:29]: nit: this, and other CWLs can be dropped, unless you need them for debugging, in which case they are fine!

File: src/mono/wasm/debugger/tests/debugger-test/debugger-async-test.cs [hunk 11]
```diff
@@ -0,0 +1,97 @@
...
+                    dt0 = new DateTime(3415, 4, 6, 8, 0, 2);
+                }
+                Console.WriteLine ($"First continueWith: {code}, {dt0}, {Date}");//this, t, code, str, dt0
+                await Task.Delay(300).ContinueWith(t2 =>
+                {
+                    var dt1 = new DateTime(4513, 4, 5, 6, 7, 8);
+                    Console.WriteLine ($"t2: {t2.Status}, str: {str}, {dt1}, {dt0}");//this, t2, dt1, str, dt0
+                });
+            });
+            Console.WriteLine ($"done with this metho d");
```
Comment (radical) [inline src/mono/wasm/debugger/tests/debugger-test/debugger-async-test.cs:92]:
```suggestion
            Console.WriteLine ($"done with this method");
```

**Review by radical — CHANGES_REQUESTED** [review]
Looking good! Just some feedback

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 1 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1726]: https://github.com/mono/debugger-libs/blob/08268b730a73cca0e3b3ac9c703f0b773a3be25b/Mono.Debugging.Soft/SoftDebuggerAdaptor.cs#L865

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 4 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1744]: I really don't know. But I don't think so. It would also break debugger-libs.

File: src/mono/wasm/debugger/DebuggerTestSuite/AsyncTests.cs (hunk 10 above)
Comment (thaystg) [reply src/mono/wasm/debugger/DebuggerTestSuite/AsyncTests.cs]: done.

File: src/mono/wasm/debugger/DebuggerTestSuite/AsyncTests.cs (hunk 9 above)
Comment (thaystg) [reply src/mono/wasm/debugger/DebuggerTestSuite/AsyncTests.cs]: done.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 8 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: done.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 7 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: done.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 6 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: changed to startswith.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 5 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: done.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 3 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: done.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 2 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: fixed.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 1 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: thanks! That code has nice method names for the conditions too. *nit*: maybe move the conditions into similarly named methods, so it's kinda documented what they are for?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 12]
```diff
@@ -1710,6 +1710,55 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                else if (fieldName.StartsWith("<>8__") ||
+                        fieldName.StartsWith("<>f__ref") ||
+                        fieldName.StartsWith("$locvar") ||
+                        fieldName.StartsWith("CS$<>")) //same code that has on debugger-libs
+                {
+                    if (DotnetObjectId.TryParse(asyncLocal?["value"]?["objectId"]?.Value<string>(), out DotnetObjectId dotnetObjectId))
+                    {
+                        if (int.TryParse(dotnetObjectId.Value, out int objectIdToGetInfo))
+                        {
+                            if (!objectsAlreadyRead.Contains(objectIdToGetInfo))
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1736]: nit: combine into the same condition?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 1 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: > thanks! That code has nice method names for the conditions too. _nit_: maybe move the conditions into similarly named methods, so it's kinda documented what they are for?

Adding to comments would be fine too.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 13]
```diff
@@ -1710,6 +1710,55 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                        }
+                    }
+                }
+                else if (fieldName.StartsWith("<>")) //examples: <>t__builder, <>1__state
+                {
+                    continue;
+                }
+                else if (fieldName.StartsWith('<')) //examples: <code>5__2
+                {
+                    asyncLocal["name"] = Regex.Match(fieldName, @"\<([^)]*)\>").Groups[1].Value;
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1751]: It might make sense to cache the compiled regex

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 4 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: True, but we don't have to fail the whole operation when it does. If it doesn't match, then we can skip this particular local, and still be able to return others.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 1 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: Done.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 4 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: Changed.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 12 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: Done.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 13 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs]: Done.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 14]
```diff
@@ -1710,6 +1710,63 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                else if (fieldName.StartsWith("<>")) //examples: <>t__builder, <>1__state
+                {
+                    continue;
+                }
+                else if (fieldName.StartsWith('<')) //examples: <code>5__2
+                {
+                    var match = regex.Match(fieldName);
+                    if (match.Success)
+                        asyncLocal["name"] = match.Groups[1].Value;
+                    asyncLocalsFull.Add(asyncLocal);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1760]: Would this still be valid without a name? If not, then we shouldn't add it to `asyncLocalsFull`, and just skip it.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 15]
```diff
@@ -1729,14 +1786,7 @@ public async Task<JArray> StackFrameGetValues(SessionId sessionId, MethodInfo me
                 retDebuggerCmdReader.ReadByte(); //ignore type
                 var objectId = retDebuggerCmdReader.ReadInt32();
                 var asyncLocals = await GetObjectValues(sessionId, objectId, true, false, false, false, token);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1788]: Just curious, what does this return? reference to the generated class?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 16]
```diff
@@ -1710,6 +1710,63 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                        fieldName.StartsWith ("<>f__ref", StringComparison.Ordinal) ||
+                        fieldName.StartsWith ("$locvar", StringComparison.Ordinal) ||
+                        fieldName.StartsWith ("<>8__", StringComparison.Ordinal);
+        }
+
+        public async Task<JArray> GetHoistedLocalVariables(SessionId sessionId, int objectId, JArray asyncLocals, CancellationToken token)
+        {
+            JArray asyncLocalsFull = new JArray();
+            List<int> objectsAlreadyRead = new();
+            Regex regex = new Regex(@"\<([^)]*)\>", RegexOptions.Singleline);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1729]: Maybe a field? IIUC, a single `MonoSDBHelper` instance is used for the full lifetime of `MonoProxy`.

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1729]: And name it to reflect what it is for.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 17]
```diff
@@ -1710,6 +1710,63 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                    {
+                        if (int.TryParse(dotnetObjectId.Value, out int objectIdToGetInfo) && !objectsAlreadyRead.Contains(objectIdToGetInfo))
+                        {
+                            var asyncLocalsFromObject = await GetObjectValues(sessionId, objectIdToGetInfo, true, false, false, false, token);
+                            var hoistedLocalVariable = await GetHoistedLocalVariables(sessionId, objectIdToGetInfo, asyncLocalsFromObject, token);
+                            asyncLocalsFull = new JArray(asyncLocalsFull.Union(hoistedLocalVariable));
+                        }
+                    }
+                }
+                else if (fieldName.StartsWith("<>")) //examples: <>t__builder, <>1__state
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1751]: StringComparison.Ordinal

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 18]
```diff
@@ -1710,6 +1710,63 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+                {
+                    continue;
+                }
+                else if (fieldName.StartsWith('<')) //examples: <code>5__2
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1755]: StringComparison.Ordinal

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs [hunk 19]
```diff
@@ -1710,6 +1710,63 @@ public async Task<bool> IsAsyncMethod(SessionId sessionId, int methodId, Cancell
...
+        public async Task<JArray> GetHoistedLocalVariables(SessionId sessionId, int objectId, JArray asyncLocals, CancellationToken token)
+        {
+            JArray asyncLocalsFull = new JArray();
+            List<int> objectsAlreadyRead = new();
+            Regex regex = new Regex(@"\<([^)]*)\>", RegexOptions.Singleline);
+            objectsAlreadyRead.Add(objectId);
+            foreach (var asyncLocal in asyncLocals)
+            {
+                var fieldName = asyncLocal["name"].Value<string>();
+                if (fieldName.EndsWith("__this"))
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1734]: StringComparison.Ordinal

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 18 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1755]: as I understood I cannot use StringComparison.Ordinal passing a char as parameter.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 19 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1734]: done

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 17 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1751]: done

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 16 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1729]: done

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs (hunk 18 above)
Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:1755]: oh, that makes sense.. I think!

**Review by radical — APPROVED** [review]
Looks good, thank you! 👍

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
The changes did not impact the lanes that had failed.
