### PR TITLE
JIT: fix jump threading to keep track of preds instead of reanalyzing

### LINKED ISSUE #58368: JIT [QualityWeek]: Random edge count assert in System.Text.Json.Tests
Random edge counts triggered an assert running one of the libraries tests on x64 Linux and arm Linux.

https://dev.azure.com/dnceng/public/_build/results?buildId=1325466&view=ms.vss-test-web.build-test-results-tab
```
COMPlus_ReadyToRun=0
COMPlus_TC_QuickJitForLoops=1
COMPlus_TieredCompilation=1
COMPlus_JitRandomEdgeCounts=1
COMPlus_TieredPGO=1

/root/helix/work/correlation/dotnet exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=faili

Assert failure(PID 61 [0x0000003d], Thread: 67 [0x0043]): Assertion failed 'predBlock == fallThroughPred' in 'System.Text.Json.Serialization.JsonConverter`1[Person_Struct][System.Text.Json.Serialization.Tests.Person_Struct]:ReadCore(byref,System.Text.Json.JsonSerializerOptions,byref):System.Text.Json.Serialization.Tests.Person_Struct:this' during 'Redundant branch opts' (IL size 503)

    File: /__w/1/s/src/coreclr/jit/redundantbranchopts.cpp Line: 566
    Image: /root/helix/work/correlation/dotnet
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
In #58368 we see an issue where a previously ambiguous pred becomes a true pred
once other pred flow is redirected. While this may be a missed opportunity, we
are better off just keeping with our initial assessment for now.

So during the initial pred walk, track which preds are ambiguous and true (and
by implication, false) and then use that classification during the second walk.

Fixes #58368.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

No SPMI diffs. No simple repro, unfortunately.

File: src/coreclr/jit/redundantbranchopts.cpp [hunk 1]
```diff
@@ -534,30 +517,14 @@ bool Compiler::optJumpThread(BasicBlock* const block, BasicBlock* const domBlock
...
-        {
-            // Skip over switch preds, they will continue to flow to block.
-            //
-            continue;
-        }
-
-        const bool isTruePred =
-            ((predBlock == domBlock) && (trueSuccessor == block)) || optReachable(trueSuccessor, predBlock, domBlock);
-        const bool isFalsePred =
-            ((predBlock == domBlock) && (falseSuccessor == block)) || optReachable(falseSuccessor, predBlock, domBlock);
```
Comment (jakobbotsch) [inline src/coreclr/jit/redundantbranchopts.cpp:547]: Is `optReachable` still used anywhere after this change?

Comment (AndyAyersMS) [reply src/coreclr/jit/redundantbranchopts.cpp:547]: The initial classification loop still calls it.

Comment (jakobbotsch) [reply src/coreclr/jit/redundantbranchopts.cpp:547]: Just to check, is that needed over `fgReachable` to be able to check for reachability that does not pass through `domBlock`? The other reason was that the flow graph was being modified in the second loop, but I guess that reason is gone now.

Comment (AndyAyersMS) [reply src/coreclr/jit/redundantbranchopts.cpp:547]: I think it still offers benefit because prior RBO's and jump threads may impact reachability. But not 100% sure.

Comment (jakobbotsch) [reply src/coreclr/jit/redundantbranchopts.cpp:547]: Ah, the classification is still running multiple times, I see.

**Review by jakobbotsch — APPROVED** [review]
