### PR TITLE
vtable setup fix for generic default interface methods in mono runtime

### LINKED ISSUE #61244: [mono] class-setup-vtable.c:1747, condition `is_ok (error)' not met, function:mono_class_setup_vtable_general, VAR 1 (T) cannot be expanded in this context with 1 instantiations
### Description

Using Blazor WebAssembly project.  I have a class hierarchy that seems to cause an assertion failure in the mono runtime.  I've created a solution and reduced the code as much as I can and attached it to this issue.  The project works fine in a Blazor Server (non-WebAssembly) project.

The projects were created with Visual Studio 2022 using the 6.0.100-rc.2.21505.57 SDK.

[ComfileTech.Framework.zip](https://github.com/dotnet/runtime/files/7481347/ComfileTech.Framework.zip)

### Reproduction Steps

Open the attached solution and run the project ending in ".Server" (ASP.Net hosted Blazor Web Assembly project).  View the result in a web browser.

### Expected behavior

No assertion failure.

### Actual behavior

Assertion failure.  See image below:

image

### Regression?

I have not tested this code in a prior version of the .Net Framework.

### Known Workarounds

No known workarounds.

### Configuration

6.0.100-rc.2.21505.57
Tested on Windows 10 64bit
Tested using the Brave web browser.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by bholmes**
When processing the overrides from interface default methods we should
check if the interface class is a generic type definition first and
inflate with the interface class context.

Test case included.

Fixes #61244

### CODE REVIEW

File: src/mono/mono/metadata/class-setup-vtable.c [hunk 1]
```diff
@@ -1742,11 +1742,11 @@ mono_class_setup_vtable_general (MonoClass *klass, MonoMethod **overrides, int o
...
 			MonoMethod *override = iface_overrides [i*2 + 1];
-			if (decl->is_inflated) {
+			if (mono_class_is_gtd (override->klass)) {
+				override = mono_class_inflate_generic_method_full_checked (override, ic, mono_class_get_context (ic), error);
+			} else if (decl->is_inflated) {
 				override = mono_class_inflate_generic_method_checked (override, mono_method_get_context (decl), error);
 				mono_error_assert_ok (error);
-			} else if (mono_class_is_gtd (override->klass)) {
-				override = mono_class_inflate_generic_method_full_checked (override, ic, mono_class_get_context (ic), error);
 			}
```
Comment (bholmes) [inline src/mono/mono/metadata/class-setup-vtable.c:1750]: I am not certain that we need the `decl->is_inflated` case at all. I can not think of a scenario where this is needed. If we can find the testcase I would like to add that to the tests in this PR as well.

Comment (bholmes) [reply src/mono/mono/metadata/class-setup-vtable.c:1750]: I did change the code locally to assert if we hit the `decl->is_inflated` case and `override` changed. I then ran all the tests and I do think this this assert was hit and I got the same results. Depending on how well dims are covered with our test code, this code block may really be unnecessary.  

```
} else if (decl->is_inflated) {
	MonoMethod *toverride = mono_class_inflate_generic_method_checked (override, mono_method_get_context (decl), error);
	g_assert(toverride == override);
	override = toverride;
	mono_error_assert_ok (error);
}
```

**Review by lambdageek — APPROVED** [review]

File: src/mono/mono/metadata/class-setup-vtable.c (hunk 1 above)
Comment (lambdageek) [reply src/mono/mono/metadata/class-setup-vtable.c:1750]: We'll do a separate PR for net7 
```c
} else if (decl->is_inflated) {
	g_assert_not_reached ();
}
```

we'll backport the current version to mono/mono and net6

File: src/tests/Loader/classloader/DefaultInterfaceMethods/regressions/github61244.cs [hunk 2]
```diff
@@ -0,0 +1,25 @@
+// Licensed to the .NET Foundation under one or more agreements.
```
Comment (MichalStrehovsky) [inline src/tests/Loader/classloader/DefaultInterfaceMethods/regressions/github61244.cs:1]: Before adding new tests, it might be worth checking whether this is already covered by the any of the existing default interface methods tests that are disabled on Mono. There's a ton of them and don't have an issue number:

https://github.com/dotnet/runtime/blob/6527b7fe83b95a195615c1081f345b6d34d716e7/src/tests/issues.targets#L1848-L1850

https://github.com/dotnet/runtime/blob/6527b7fe83b95a195615c1081f345b6d34d716e7/src/tests/issues.targets#L1913-L1918

https://github.com/dotnet/runtime/blob/6527b7fe83b95a195615c1081f345b6d34d716e7/src/tests/issues.targets#L1928-L1930

https://github.com/dotnet/runtime/blob/6527b7fe83b95a195615c1081f345b6d34d716e7/src/tests/issues.targets#L1934-L1939

https://github.com/dotnet/runtime/blob/6527b7fe83b95a195615c1081f345b6d34d716e7/src/tests/issues.targets#L1943-L1945

Comment (MichalStrehovsky) [reply src/tests/Loader/classloader/DefaultInterfaceMethods/regressions/github61244.cs:1]: (This test look pretty low value because it doesn't try to do a dispatch or check whether we have a good generic context.)

Comment (bholmes) [reply src/tests/Loader/classloader/DefaultInterfaceMethods/regressions/github61244.cs:1]: I did check and none of the existing tests you list cover this case. If you want a more interesting case I can push this following...  

```
// The .NET Foundation licenses this file to you under the MIT license.

using System;

class Program
{
    static int Main(string[] args)
    {
        return new TestClass().DoTest();
    }
}

public interface OneArgBaseInterface<T1>
{
    int SomeFunc1(T1 someParam1, Type someParam1Type);
}

public interface TwoArgBaseInterface<T1, T2>
{
    int SomeFunc1(T1 someParam1, T2 someParam2, Type someParam1Type, Type someParam2Type);
}

public interface SecondInterface<TParam2Type, TParam1Type> :  OneArgBaseInterface<TParam1Type>, TwoArgBaseInterface<TParam1Type, TParam2Type>
{
    int OneArgBaseInterface<TParam1Type>.SomeFunc1(TParam1Type someParam1, Type someParam1Type)
    {
        if (typeof(TParam1Type) != someParam1Type)
        {
            Console.WriteLine("Failed => 101");
            return 101;
        }

        return 100;
    }

    int TwoArgBaseInterface<TParam1Type, TParam2Type>.SomeFunc1(TParam1Type someParam1, TParam2Type someParam2, Type someParam1Type, Type someParam2Type)
    {
        if (typeof(TParam1Type) != someParam1Type)
        {
            Console.WriteLine("Failed => 102");
            return 102;
        }

        if (typeof(TParam2Type) != someParam2Type)
        {
            Console.WriteLine("Failed => 103");
            return 103;
        }

        return 100;
    }
}

public class TestClass : SecondInterface<int, string>
{
    public int DoTest ()
    {
        int ret = (this as OneArgBaseInterface<string>).SomeFunc1("test string", typeof(string));
        if (ret != 100)
            return ret;

        ret = (this as TwoArgBaseInterface<string, int>).SomeFunc1("test string", 0, typeof(string), typeof(int));
        if (ret != 100)
            return ret;

        Console.WriteLine("Passed => 100");
        return 100;
    }
}
```

Comment (MichalStrehovsky) [reply src/tests/Loader/classloader/DefaultInterfaceMethods/regressions/github61244.cs:1]: 👍 this test looks much more thorough! Thanks!

**Comment by bholmes** [comment]
@lambdageek pushed a test update.  Will need to wait for all the tests to run again.

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@bholmes Could you merge dotnet/runtime `main` into this branch.  There are some CI infrastructure changes that are preventing the minijit and monointerpreter lanes from running.

**Comment by lambdageek** [comment]
Thanks @bholmes !
