### PR TITLE
SPMI: Read csv files output by superpmi as UTF8

### LINKED ISSUE #98759: win-x64 SPMI asmdiffs failing
Fails after my PR with this message:
```scala

Traceback (most recent call last):

  File "C:\h\w\AAFC096C\p\superpmi.py", line 5227, in <module>

    sys.exit(main(args))

  File "C:\h\w\AAFC096C\p\superpmi.py", line 5118, in main

    success = asm_diffs.replay_with_asm_diffs()

  File "C:\h\w\AAFC096C\p\superpmi.py", line 2155, in replay_with_asm_diffs

    details = read_csv(detailed_info_file)

  File "C:\h\w\AAFC096C\p\superpmi.py", line 511, in read_csv

    return list(reader)

  File "C:\python3\lib\csv.py", line 111, in __next__

    row = next(self.reader)

  File "C:\python3\lib\encodings\cp1252.py", line 23, in decode

    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5250: character maps to <undefined>


Failed during asmdiffs. Log file: C:\h\w\AAFC096C\w\A1AB090D\uploads\superpmi_asmdiffs_windows_x64.log
```

I'm investigating...

### PR DESCRIPTION
**Pull request by jakobbotsch**
Hopefully fixes #98759

### CODE REVIEW

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -116,8 +116,8 @@ void Compiler::impResolveToken(const BYTE* addr, CORINFO_RESOLVED_TOKEN* pResolv
 {
     pResolvedToken->tokenContext = impTokenLookupContextHandle;
     pResolvedToken->tokenScope   = info.compScopeHnd;
-    pResolvedToken->token        = getU4LittleEndian(addr);
     pResolvedToken->tokenType    = kind;
+    pResolvedToken->token        = getU4LittleEndian(addr);
```
Comment (BruceForstall) [inline src/coreclr/jit/importer.cpp:120]: unrelated change?

**Review by BruceForstall — APPROVED** [review]

**Review by EgorBo — APPROVED** [review]
Looks like it has fixed the CI issue?

File: src/coreclr/jit/importer.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/importer.cpp:120]: Yeah, it was just to trigger SPMI pipelines.
