### PR TITLE
Fix missing analyzer warning for generics in containing type

### LINKED ISSUE #109270: Several IL20XX trim warnings missed by analyzers, only show up with ILC
### Description

I've noticed several IL20XX trim warnings when publishing the Microsoft Store with NAOT, that only show up via ILC:

Image

### Reproduction Steps

Can't share repro steps here (since the code is not open source).
I can however share:
- binlog (MSFT only): [link](https://microsoft-my.sharepoint-df.com/:u:/p/sergiopedri/ESW_tpVfTPVEtkIJdBVS1AQBQ9ztXn2vzjpIlzbD65wZPw?e=pt20Y0)
- repo link and instructions to build locally (ping me on Teams)

### Expected behavior

Ideally, all those warnings should also show up in the IDE.

### Actual behavior

Several warnings only show up via ILC at publish time.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sbomer**
Fixes the IL2091 warnings missed by the analyzer in https://github.com/dotnet/runtime/issues/109270.

Fixes https://github.com/dotnet/runtime/issues/109270

### CODE REVIEW

File: src/tools/illink/src/ILLink.RoslynAnalyzer/TrimAnalysis/GenericArgumentDataFlow.cs [hunk 1]
```diff
@@ -21,12 +21,20 @@ public static void ProcessGenericArgumentDataFlow (Location location, IMethodSym
 		{
 			ProcessGenericArgumentDataFlow (location, method.TypeArguments, method.TypeParameters, reportDiagnostic);
 
-			ProcessGenericArgumentDataFlow (location, method.ContainingType, reportDiagnostic);
+			var type = method.ContainingType;
+			while (type is { IsGenericType: true }) {
```
Comment (jtschuster) [inline src/tools/illink/src/ILLink.RoslynAnalyzer/TrimAnalysis/GenericArgumentDataFlow.cs:25]: Same as below
```suggestion
			while (type.IsGenericType) {
```

Comment (jtschuster) [reply src/tools/illink/src/ILLink.RoslynAnalyzer/TrimAnalysis/GenericArgumentDataFlow.cs:25]: Also, would it make sense to recurse up the `ContainingType`s in the `INamedTypeSymbol` overload of `ProcessGenericArgumentDataflow` rather than in both the `IMethodSymbol` and `IFieldSymbol` overloads, or does doing that cause issues elsewhere?

File: src/tools/illink/test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs [hunk 2]
```diff
@@ -849,6 +850,31 @@ static void TestNoWarningsInRUCType<T, U> ()
...
+				}
+			}
+
+			public static void Test ()
+			{
+				new Generic<int> ().CallNestedMethod ();
+				new Generic<string> ().AccessNestedField ();
+			}
+		}
+
```
Comment (jtschuster) [inline src/tools/illink/test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs:877]: Are properties and events relevant here?

**Review by jtschuster — APPROVED** [review]
Thank you!
