### PR TITLE
[browser][ws] fix ConnectAsync_CancellationRequestedInflightConnect_ThrowsOperationCanceledException

### LINKED ISSUE #97092: [browser][MT] System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedInflightConnect_ThrowsOperationCanceledException
### Error Blob

```json
{
  "ErrorMessage": "[FAIL] System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedInflightConnect_ThrowsOperationCanceledException",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

_No response_

### PR DESCRIPTION
**Pull request by pavelsavara**
Fixes https://github.com/dotnet/runtime/issues/97092

### CODE REVIEW

File: src/mono/browser/runtime/web-socket.ts [hunk 1]
```diff
@@ -105,9 +105,11 @@ export function ws_wasm_create(uri: string, sub_protocols: string[] | null, rece
         if (ws[wasm_ws_is_aborted]) return;
         if (!loaderHelpers.is_runtime_running()) return;
         ws.removeEventListener("message", local_on_message);
-        const error = new Error(ev.message || "WebSocket error");
-        mono_log_warn("WebSocket error", error);
-        reject_promises(ws, error);
+        const message = ev.message
+            ? "WebSocket error :" + ev.message
```
Comment (campersau) [inline src/mono/browser/runtime/web-socket.ts:109]: Nit
```suggestion
            ? "WebSocket error: " + ev.message
```

**Comment by pavelsavara** [comment]
I'm really confused how this could happen.

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97868-merge-1bb1532610b0496285/WasmTestOnBrowser-System.Net.WebSockets.Client.Tests/1/console.00fec533.log?helixlogtype=result)
```
[15:05:50] info: [STRT] System.Net.WebSockets.Client.Tests.HttpClientConnectTest.ConnectAsync_CancellationRequestedBeforeConnect_ThrowsOperationCanceledException
[15:05:50] fail: [out of order message from the browser]: http://127.0.0.1:42619/_framework/dotnet.runtime.js 2 WebSocket connection to 'ws://38c12b6832644ebbbcc2f28974617f84/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
[15:05:50] warn: [0x000dc23c 15:05:50.656] MONO_WASM: WebSocket error
[15:05:50] info: [STRT] System.Net.WebSockets.Client.Tests.HttpClientConnectTest.ConnectAsync_PassNoSubProtocol_ServerRequires_ThrowsWebSocketException(server: ws://127.0.0.1:42619/WebSocket/EchoWebSocket.ashx)
[15:05:50] warn: [0x000dc23c 15:05:50.667] MONO_WASM: WebSocket error
[15:05:50] fail: [0x000dc23c 15:05:50.668] MONO_WASM: Unhandled error: {}
[15:05:50] fail: [0x000dc23c 15:05:50.669] MONO_WASM: {"status":1,"silent":true}
[15:05:50] fail: [out of order message from the browser]: http://127.0.0.1:42619/_framework/dotnet.runtime.js 2 WebSocket connection to 'ws://127.0.0.1:42619/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[15:05:50] info: WASM EXIT 1
```

**Review by ilonatommy — APPROVED** [review]
