### PR TITLE
Fix for field layout verification across version bubble boundary

### LINKED ISSUE #49982: Many tests failed with Verify_FieldOffset 'ExtendedSocketException._endPoint' Field offset 128!=136(actual) || baseOffset 128!=136(actual)
Run: [runtime-coreclr crossgen2 20210320.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1049652&view=ms.vss-test-web.build-test-results-tab&runId=32441742&resultId=101999&paneView=debug)

**One of error message:**
```
/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/processinfo.sh: line 280: -r:/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/IL-CG2/.dll: No such file or directory
rm: /private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/common.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/processinfo.dll.rsp: No such file or directory

Assert failure(PID 1344 [0x00000540], Thread: 1065195 [0x1040eb]): Verify_FieldOffset 'ExtendedSocketException._endPoint' Field offset 128!=136(actual) || baseOffset 128!=136(actual)
 File: /Users/runner/work/1/s/src/coreclr/vm/jitinterface.cpp Line: 14129
 Image: /private/tmp/helix/working/AD85094A/p/corerun

MachO coredumps are not supported. To enable ELF coredumps on MacOS, set the COMPlus_DbgEnableElfDumpOnMacOS environment variable to 1.
/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/processinfo.sh: line 401: 1344 Abort trap: 6 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/Reports/tracing.eventpipe/processinfo/processinfo/processinfo.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/IL-CG2/common.dll
Response file: /private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/common.dll.rsp
/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/IL-CG2/common.dll
-o:/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/common.dll
-r:/tmp/helix/working/AD85094A/p/System..dll
-r:/tmp/helix/working/AD85094A/p/Microsoft..dll
-r:/tmp/helix/working/AD85094A/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2: dotnet /tmp/helix/working/AD85094A/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/common.dll.rsp 
Emitting R2R PE file: /private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/common.dll
/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/IL-CG2/processinfo.dll
Response file: /private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/processinfo.dll.rsp
/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/IL-CG2/processinfo.dll
-o:/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/processinfo.dll
-r:/tmp/helix/working/AD85094A/p/System..dll
-r:/tmp/helix/working/AD85094A/p/Microsoft.*.dll
-r:/tmp/helix/working/AD85094A/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2: dotnet /tmp/helix/working/AD85094A/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/processinfo.dll.rsp 
Emitting R2R PE file: /private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/processinfo.dll
in ReleaseLock
/tmp/helix/working/AD85094A/p/corerun processinfo.dll ''
 0.0s: Test PID: 1344
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/AD85094A/p
> /private/tmp/helix/working/AD85094A/w/B37709B8/e/tracing/eventpipe/processinfo/processinfo/processinfo.sh
Expected: True
Actual: False

Stack trace
   at tracing_eventpipe._processinfo_processinfo_processinfo_._processinfo_processinfo_processinfo_sh()

```

### PR DESCRIPTION
**Pull request by trylek**
When verifying field offset consistency, we shouldn't be checking
base class size when the base class doesn't belong to the current
version bubble. I have fixed this by adding a special case for
the existing fixup encoding indicated by base class size being
zero; please let me know if you find it preferable to create
a new fixup type for this purpose instead. I have also created
a simple regression test that was previously failing when run
against the framework compiled with CG2 assembly by assembly.

Thanks

Tomas

Fixes: https://github.com/dotnet/runtime/issues/49982

/cc @dotnet/crossgen-contrib

### CODE REVIEW

**Review by davidwrighton — APPROVED** [review]
I like it. We don't need a new encoding as we've never shipped anything that should depend on this.

**Comment by trylek** [comment]
@davidwrighton - CI testing uncovered a pre-existing deficiency of CG2 field layout, we weren't properly aligning base class sizes on ARM32. Could you please take another look when you have a chance?

**Comment by trylek** [comment]
OK, I found out there were actually three different places in Crossgen2 - auto field layout calculation, sequential field layout calculation and the field offset verification fixup - that were using three different methods to calculate the field base offset. I have unified all of them to use the same method <code>CalculateFieldBaseOffset</code>.

**Comment by davidwrighton** [comment]
Every time anyone looks at this stuff we find more cases to consolidate. Hopefully this is it. I like the current state of the change, but of course, we need to look at the results of the outerloop testing that you are doing now.

File: src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs [hunk 1]
```diff
@@ -775,13 +762,14 @@ private static bool IsByValueClass(TypeDesc type)
             return type.IsValueType && !type.IsPrimitive && !type.IsEnum;
         }
 
-        private static LayoutInt ComputeBytesUsedInParentType(DefType type)
+        public LayoutInt CalculateFieldBaseOffset(TypeDesc type)
```
Comment (MichalStrehovsky) [inline src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:765]: This API will crash with an InvalidCast if e.g. an array is passed. It would be better to ensure valid inputs at compile time.

```suggestion
        public LayoutInt CalculateFieldBaseOffset(MetdataType type)
```

Comment (trylek) [reply src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs]: Good point, thanks, fixed in 8th commit.

**Comment by trylek** [comment]
I have rebased the change, I reverted a failed attempt at ARM offset bias refactoring; for the sake of expediency I have also included my two other pending fixes, 

https://github.com/dotnet/runtime/pull/50474

and

https://github.com/dotnet/runtime/pull/50562

For now I assume that we'll first merge in the two fixes and I'll then rebase this change against them and rerun the testing but I'm open to merging in this combination of the three fixes for the sake of expediency.

**Comment by mangod9** [comment]
merging together should be fine, assuming tests are passing with all of them together.

**Comment by trylek** [comment]
Down to three remaining test failures (ExplicitClass in crossgen2smoke on ARM, LayoutClassTest, PlatformDefaultMemberFunctionTest); some unrelated failures in composite CG2 builds that should be fixed or at least change their behavior after the fix for MVID checks (https://github.com/dotnet/runtime/pull/50474) is merged in; I'm looking at them now but the crossgen2smoke failure on arm[32] is interesting and I would love to hear @davidwrighton's opinion:

<pre>
Verify_FieldOffset 'ExplicitlySizedClass.A' Field offset 0!=-4(actual) || baseOffset 0!=0(actual)
</pre>

I think this raises two interesting questions:

1) The shortcut I used to encode extra-bubble base class sizes as zero probably incorrectly conflates this case with types without a base class. For now I think I should probably introduce a new fixup for this case after all, I don't see any non-hacky way to encode this extra bit of information in the existing fixup format.

2) I sincerely doubt that the "actual" information is correct, I think it rather means that in this particular case the field offset check in jitinterface.cpp calculates the base size incorrectly; I guess that the base class - object - is assumed to have size 8 and the offset of the first field in ExplicitlySizedClass is 4 and that gets recalculated to the relative offset notation, otherwise it doesn't make sense to me.

Thanks

Tomas

**Comment by jkotas** [comment]
Is the base validation actually useful?
- If there is no version bubble boundary crossing, the base does not matter. All fields are accessed by absolute offset.
- If there is version bubble boundary, the base cannot be validated.

**Comment by trylek** [comment]
I believe it's extremely useful. Please remember that these checks are not supposed to improve our code in any manner, they are just sanity checks helping us chase down subtle differences in the two type systems and class loaders that have been plaguing us throughout the entire CG2 development - each longer-term member of the CG2 v-team has their stories to tell; I side with David on this one, I believe the validation has been an awesome boost in nailing down hard issues, I recall times before that change and having to do everything manually. And this logic already bears unexpected fruits - discoveries of tiny misalignments between CG2 and the runtime regarding field layout, not only on ARM (even within a version bubble i.e. with fixed offsets). While this PR is difficult, I would be very sad to have to trim this down by reducing the quality of the checks.

**Comment by trylek** [comment]
Hmm, I guess the expression I used is somewhat ambiguous, sorry about that, I think I meant to say something like "the checks are not supposed to improve the runtime native code in any manner, ...", the way I phrased that it sounds like a contradiction in terms to some extent. Thanks for your patience :-).

**Comment by jkotas** [comment]
I understand that the field offset check is useful. I am questioning the usefulness of the base check.

**Comment by davidwrighton** [comment]
The particular value of the runtime base check isn't to validate them in cases where there is a cross-module boundary. Its to validate the data that *would be* used in a cross module boundary to ensure that the general type layout processing is correct. It turns out that while not exactly matching up to a useful value, it has been quite valuable at finding all kinds of edge cases that do affect the within version bubble cases. In particular, it is good at finding cases where the alignment calculations were subtly wrong in a way that didn't cause a field offset to be wrong in that particular test case, but could have caused a problem for other fields on the type.

Now, if it turns out the only incorrectness is caused by this incorrect conflation of cross boundary and non-deriving, we could use a different sentinel value like 0xFFFFFFFF or something or simply not allow a sentinel value for types that derive directly from object. @trylek I assume that you have an arm32 test environment where you can test this locally? Relying on the CI for this sort of testing is a giant time waster.

Also, what I've found in the past is that when a layout issue is particularly nasty is that I need to build a standalone repro of the bug, and debug in parallel through the native CLR type layout logic and the managed type layout logic and find where they differ. I worry that when you consolidated the 3 different ways in which we calculated base offset that you actually removed a way in which they are required to be very subtly different.

**Comment by trylek** [comment]
Hmm, I guess you're probably right that in the local case (within version bubble) the verification of absolute field offset is sufficient. On the other hand, the base class - derived class boundary turns out to be a super productive bug farm, I have been poring over the code for more than a week by now and I still cannot claim I exactly know what's happening in each situation, especially as there are multiple code paths involved for explicit / sequential / auto layouts for reference types vs. value types with side fun regarding the ARM32 offset bias. As I believe that "usefulness" of this fixup is basically preventively diagnostic (we detect upfront that we got it wrong), I tend to believe that the base field offset calculation does constitute a value worth validating (in the intra-bubble scenario) as getting that wrong indicates a potentially critical bug in our implementation.

**Comment by trylek** [comment]
In fact, this is exactly what crashes the LayoutClassTest - in the test, there's a class named <code>SeqDerivedClass</code> that derives from an empty class named <code>EmptyBase</code>, please cf.

https://github.com/dotnet/runtime/blob/c24bf80fae47a27a5efd2c3382e53fa28bf4e4af/src/tests/Interop/LayoutClass/LayoutClassTest.cs#L16

The proximate problem is that, on x64, we don't properly replicate runtime behavior w.r.t. the base class <code>EmptyBase</code> that adds 1 byte to its 8-byte <code>object</code> base (on x64) - I haven't yet found the place in the CoreCLR runtime method table builder where the empty class gets added an extra byte, probably akin to C++ being unable to properly deal with zero-sized classes. Long story short, my current belief is that this is what causes the remaining discrepancy until proven otherwise.

**Comment by trylek** [comment]
Merging in as the PR is green and the remaining CG2 failures are known.
