### PR TITLE
Do not count page cache towards cgroup’s memory load

### LINKED ISSUE #49058: Memory load includes the file cache on Docker Linux
### Description

We have a complex C# application that makes heavy use of memory mapped files.

In Docker it spends most its time hitting the container memory limit, but this is only due to page cache so shouldn’t be a problem. Our app isn’t failing due to lack of memory. However it’s running at half the speed on Linux compared to Windows. G2 garbage collections are also way more frequent on Linux.

We suspected this was due to the process garbage collecting too aggressively, as it wrongly thought it was about to run out of memory (although it’s harmlessly hitting the limit due to page cache). We conducted an experiment to test this theory.
We tried allocating/writing to a large chunk of memory outside the container (swap is off so this stays in RAM). This stops the C# app from hitting the container memory limit because page cache size is now constrained by physical RAM on the machine, not by the cgroup limit. Allocating the large chunk of memory outside the container doubles the speed of our C# app, and reduces G2 collections by 8x!

This looks similar to https://github.com/dotnet/runtime/issues/13371 but for the cgroup code path.

I tried working round the issue by setting System.GC.HighMemoryPercent to 100 – this makes no difference, probably because HighMemoryPercent is capped at 99 in the code (search for `min (99, highmem_th_from_config)` in https://raw.githubusercontent.com/dotnet/runtime/main/src/coreclr/gc/gc.cpp)

### Configuration

This effect has been observed using both the .NET Core 3.1.3 and 5.0.0 runtimes.

~~~~~
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
~~~~~

~~~~~
$ uname -a
Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
~~~~~

~~~~~
$ docker -v
Docker version 18.06.1-ce, build e68fc7a
~~~~~

### Regression?
This has always been the case AFAIK

### Data
Typical example:
~700GiB Memory free at start: 10421 seconds, GC counts: G0=111932, G1=29224, G2=812
27GiB Memory free at start: 5592 seconds, GC Counts: G0=110433, G1=29013, G2=98

(Container memory limit is 36GiB, machine has 768GiB in total)

### Analysis

Possibly issue in https://github.com/dotnet/runtime/blob/main/src/coreclr/gc/unix/cgroup.cpp ?

### PR DESCRIPTION
**Pull request by marcin-krystianc**
As reported in the https://github.com/dotnet/runtime/issues/49058 there are scenarios in which GC is too aggressive when the app runs inside a Linux container (cgroups v1 & cgroups v2).
One of the factors considered for deciding whether it is necessary to run GC is a [memory load](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/coreclr/vm/gcenv.os.cpp#L915-L989).
A memory load value is supposed to mean the approximate percentage of physical memory that is in use. 
Unlike on Windows, memory load on Linux containers also includes a page cache which makes the memory load value larger than it ought to be.
This PR changes how the memory load is calculated on Linux containers to match Windows.

Fixes : https://github.com/dotnet/runtime/issues/49058

### CODE REVIEW

File: src/coreclr/pal/src/misc/cgroup.cpp [hunk 1]
```diff
@@ -401,22 +416,84 @@ class CGroup
...
+        size_t readValues = 0;
+        size_t active_file = 0;
+        size_t inactive_file = 0;
+        size_t dirty_file = 0;
+        char* endptr;
+
+        while (getline(&line, &lineLen, stat_file) != -1)
         {
-            if (temp > std::numeric_limits<size_t>::max())
+            if (strncmp(line, s_active_file_key_name, s_active_file_key_length) == 0)
```
Comment (omajid) [inline src/coreclr/pal/src/misc/cgroup.cpp:445]: A tiny nit: this string comparison will incorrectly evaluate to true if `line` begins with contents of `s_active_file_key_name` but contains additional characters. [More here](http://www.cpp.re/forum/beginner/109868/3/).

**Comment by janvorli** [comment]
@marcin-krystianc thank you! I assume you have tested your scenario with this fix and the problems you were seeing are gone, right?

File: src/coreclr/pal/src/misc/cgroup.cpp (hunk 1 above)
Comment (marcin-krystianc) [reply src/coreclr/pal/src/misc/cgroup.cpp:445]: @omajid It is actually my intention to use `strncmp`  as a prefix match. Lines in the `memory.stat` file are in a form of:
`<key_name><space><value>`. In my code I'm treating the space character as integral part of the name of a key. This is to avoid any mistakes in case when a `key_name` is a prefix of another `key_name` .

**Comment by marcin-krystianc** [comment]
Yes, absolutely! 
Also, I've found an easier way to detect the problem. Instead of looking at the number of GCs before and after my change (which is a correct way but it is not very straightforward), it is better to just look at the value of `GCMemoryInfo.MemoryLoadBytes`. Before my change, that value was equal to the value reported in the cgroup's `usage_in_bytes` which we know that it does also include the page cache. After my change,  the value of `GCMemoryInfo.MemoryLoadBytes` doesn't include page cache anymore.

**Comment by tmds** [comment]
@janvorli @marcin-krystianc I asked a cgroup expert input on how we could improve this. He suggested that as usage we sum up fields that count memory used by the managed heap.

It would mean we no longer need to read the usage file and can sum up one or two fields from the `memory.stat` file. For cgroupv1, it would be `total_rss` with `total_swap`. For cgroupv2, it would be `anon`. I'm not sure if something needs to be added to that for swap. We should be able to figure that out by seeing what increments when we the grow the GC larger than RAM.

I think this can work and addresses the referenced issue. It would simpler to calculate than what the PR is currently doing.

What do you think?

**Comment by marcin-krystianc** [comment]
I would really like to implement the exact memory load calculation by reading `memory.stat` file only, but I don't believe it is actually possible.

For cgroups v1 I've run following experiment (using the app mentioned in https://github.com/dotnet/runtime/issues/49058#issuecomment-808191298) :
- start the container with 1 GB memory limit and 1GB of swap memory available
```docker.exe run -t -i --rm --name=gctesting --memory=1gb --entrypoint /bin/bash gctesting```
- run the `watch` command to monitor memory load 
```docker.exe exec -it gctesting watch -n 1 -d cat /sys/fs/cgroup/memory/memory.stat /sys/fs/cgroup/memory/memory.usage_in_bytes```
- run 3 instances of the `gctesting` app with 500mb memory usage to force the container to use swap:
```docker.exe exec -it gctesting ./GcTesting --memorypressuretask=true --memorypressurerate=1mb --allocationunitsize=80Kb --minimummemoryusage=500mb```
```docker.exe exec -it gctesting ./GcTesting --memorypressuretask=true --memorypressurerate=1mb --allocationunitsize=80Kb --minimummemoryusage=500mb```
```docker.exe exec -it gctesting ./GcTesting --memorypressuretask=true --memorypressurerate=1mb --allocationunitsize=80Kb --minimummemoryusage=500mb```

The output from the watch command is:
```
cache 0
rss 920088576
rss_huge 0
shmem 0
mapped_file 0
dirty 0
writeback 0
swap 617717760
pgpgin 422598
pgpgout 161992
pgfault 436689
pgmajfault 1419
inactive_anon 1047400448
active_anon 20140032
inactive_file 0
active_file 0
unevictable 0
hierarchical_memory_limit 1073741824
hierarchical_memsw_limit 2147483648
total_cache 0
total_rss 920088576
total_rss_huge 0
total_shmem 0
total_mapped_file 0
total_dirty 0
total_writeback 0
total_swap 617717760
total_pgpgin 422598
total_pgpgout 161992
total_pgfault 436689
total_pgmajfault 1419
total_inactive_anon 1047400448
total_active_anon 20140032
total_inactive_file 0
total_active_file 0
total_unevictable 0
1073610752
```

- `usage_in_bytes` = 1073610752 = 0.999 GB
- `total_rss`  + `total_swap` = 920088576 + 617717760 = 1537806336 = 1.432 GB
- `total_inactive_anon` + `total_active_anon` = 1047400448 + 20140032 = 1067540480 = 0.994 GB

Note that in this experiment we don't need to look at the page cache as it is not used at all (`total_cache` is 0).
From this single experiment we can see that the best approximation of memory load (`usage_in_bytes` - `page_cache`) is to use `total_inactive_anon` + `total_active_anon`, but even that it is missing few megabytes. I believe that the missing megabytes are used by kernel itself and they are not reported in the `memory.stat` file (but they are included in the `usage_in_bytes`).

If we are willing to accept the fact that our calculation slightly underestimate the actual memory usage then we could implement it without reading the `usage_in_bytes` file. I believe that the formula for that would be:
`memory_load` = `total_inactive_anon` + `total_active_anon` + `total_dirty` + `total_unevictable`

**Comment by tmds** [comment]
> If we are willing to accept the fact that our calculation slightly underestimate the actual memory usage then we could implement it without reading the usage_in_bytes file.

I think we should do that. From kernel side there is some lazy counting. And from .NET side, GC starts already at a certain percentage of the limit.

I had not thought about how swap is considered by the GC. From your measurements, it's clear the GC doesn't want to use swap space and compares usage_in_bytes vs limit_in_bytes which both reflect RAM usage.

So when we're calculating usage from the `memory.stat` file we shouldn't count swap either.

`memory_load = total_inactive_anon + total_active_anon + total_dirty + total_unevictable`.

This looks good to me. `total_inactive_anon + total_active_anon` are accounting for a bit more than `total_rss`. This is the main thing we care about because that's counting the managed heap. Adding `total_dirty + total_unevictable` is also fine.

I'll look at running similar commands with cgroupv2 and share the `memory.stat` file.

File: src/coreclr/pal/src/misc/cgroup.cpp [hunk 2]
```diff
@@ -52,25 +50,42 @@ class CGroup
...
-        s_inactive_file_key_name = s_cgroup_version == 1 ? "total_inactive_file " : "inactive_file ";
-        s_dirty_file_key_name = s_cgroup_version == 1 ? "total_dirty " : "file_dirty ";
-        s_active_file_key_length = strlen(s_active_file_key_name);
-        s_inactive_file_key_length = strlen(s_inactive_file_key_name);
-        s_dirty_file_key_length = strlen(s_dirty_file_key_name);
+        
+        if (s_cgroup_version == 1)
+        {
+            s_mem_stat_n_keys = 4;
+            s_mem_stat_key_names = new const char*[s_mem_stat_n_keys];
```
Comment (janvorli) [inline src/coreclr/pal/src/misc/cgroup.cpp:66]: Can you please make the s_mem_stat_key_names an array instead of allocating it via new? And the same for s_mem_stat_key_lengths.

Comment (marcin-krystianc) [reply src/coreclr/pal/src/misc/cgroup.cpp]: done

**Review by janvorli — APPROVED** [review]
LGTM, thank you for your contribution!

**Comment by tmds** [comment]
@marcin-krystianc if you want to optimize it a little more, you can get rid of the `s_mem_stat_key_names`, `s_mem_stat_n_keys`, and `s_mem_stat_key_lengths` fields.

```c
#define CGROUP1_MEMSTAT_FIELDS_LENGTH 1
const_string CGROUP1_MEMSTAT_FIELDS[CGROUP1_MEMSTAT_FIELDS_LENGTH] =
{ "total_inactive_anon %uld\n", ... };
```
You can pass these as arguments to `GetCGroupMemoryUsage` based on `s_cgroup_version`.

Then:
```c
// GetCGroupMemoryUsage args: int fieldsLength, const_string* fields;

    int fieldsFound = 0;
    while (getline(&line, &lineLen, file) != -1 && fieldsFound < fieldsLength)
    {
        for (int i = 0; i < fieldsLength; i++)
        {
            unsigned long value;
            if (sscanf(line, fields[i], &value))
            {
                fieldsFound++;
                // ...
            }
        }
    }
```

Note the `fieldsFound < fieldsLength` which stop reading lines as soon when all were found.

For cgroupv2 I'd read `anon` instead of summing up `inactive_anon` and `active_anon` because it requires less parsing/checking.

**Comment by marcin-krystianc** [comment]
@tmds Thanks for your suggestion it looks really elegant! 

I was worried a little bit though about its performance. It is not obvious what is the complexity characteristic of `sscanf`. Some sources suggest that it runs `strlen` on the input. Also the `sscanf` needs to parse the format string which has negative impact. 
To clear my doubts I've run performance benchmark of `sscanf` based `GetCGroupMemoryUsage` method and the same method based on `strtoll`. The `strtoll` is a clearly a winner as it is roughly twice as fast. I'm not sure how often is the `GetCGroupMemoryUsage` method being called by the GC, so I'm not sure whether it actually matters if it is little bit slower or not. I'm leaving this decision to @janvorli - what do you think about it ? 
 
> Note the fieldsFound < fieldsLength which stop reading lines as soon when all were found.
For cgroupv2 I'd read anon instead of summing up inactive_anon and active_anon because it requires less parsing/checking.
 
Done 👍

**Comment by janvorli** [comment]
@marcin-krystianc let's keep the strtoll. This function is called quite often, I had to modify the cgroups implementation in the past to fix a performance regression (https://github.com/dotnet/coreclr/pull/21229)

**Comment by tmds** [comment]
@marcin-krystianc thank you for improving this!

**Comment by marcin-krystianc** [comment]
@janvorli 
I would like to request a backport of this change to `release/5.0` and `release/3.1` branches.
From what I can see, the backport to `release/3.1` needs to be done manually by raising a PR in the `coreclr` repository and waiting for a review by the servicing team.
But as far as I understand, a backport to `release/5.0` can be triggered by a special comment made on this PR by a repo maintainer. Is there any official way to request it?

**Comment by tmds** [comment]
@marcin-krystianc for a backport you need to assess Customer Impact and Risk. Performance improvements are rarely considered, and even less if there is a chance of regressions.

Maybe you can start using .NET 6 preview releases? .NET 6 will be released in half a year.
