### PR TITLE
Fix IJW OverflowException with 17+ by-ref parameters

### LINKED ISSUE #127166: [C++/CLI] [IJW] HRException crash when calling a managed function with 17+ parameters from native code (regression from .NET 8)
### Description

Calling a managed C++/CLI function with 17 or more parameters from a native C++ executable via IJW (It Just Works) interop throws an unhandled HRException at runtime. The same code works correctly on .NET 8 and works correctly on .NET 10 if the function has 16 or fewer parameters.

### Reproduction Steps

1. C++/CLI managed project (CppCliProject.dll) — Functions.hpp:
```
#pragma once
#include <cstdint>

struct IntWrapper
{
    int Value;
};

class __declspec(dllexport) Functions
{
public:

    int64_t static Sum17(const int& a0,
        const IntWrapper& a1,
        const IntWrapper& a2,
        const IntWrapper& a3,
        const IntWrapper& a4,
        const IntWrapper& a5,
        const IntWrapper& a6,
        const IntWrapper& a7,
        const IntWrapper& a8,
        const IntWrapper& a9,
        const IntWrapper& a10,
        const IntWrapper& a11,
        const IntWrapper& a12,
        const IntWrapper& a13,
        const IntWrapper& a14,
        const IntWrapper& a15,
        const IntWrapper& a16,
        const int& a17);
};
```
function.cpp

```
#include "Functions.hpp"

int64_t Functions::Sum17(const int& a0,
	const IntWrapper& a1,
	const IntWrapper& a2,
	const IntWrapper& a3,
	const IntWrapper& a4,
	const IntWrapper& a5,
	const IntWrapper& a6,
	const IntWrapper& a7,
	const IntWrapper& a8,
	const IntWrapper& a9,
	const IntWrapper& a10,
	const IntWrapper& a11,
	const IntWrapper& a12,
	const IntWrapper& a13,
	const IntWrapper& a14,
	const IntWrapper& a15,
	const IntWrapper& a16,
	const int& a17)
{
	System::Console::WriteLine(System::Runtime::InteropServices::RuntimeInformation::FrameworkDescription);
	System::Console::WriteLine(a1.Value);
	System::Console::WriteLine(a2.Value);
	return a1.Value + a2.Value + a3.Value + a4.Value + a5.Value + a6.Value + a7.Value + a8.Value + a9.Value + a10.Value
		+ a11.Value + a12.Value + a13.Value + a14.Value + a15.Value + a16.Value + a17;
}
```
2. Native C++ executable (ParametersCrashCppCli.exe) — main.cpp:

```
#include <iostream>
#include "../CppCliProject/Functions.hpp"


int main()
{
	auto value = Functions::Sum17(0, { 1 }, { 2 }, { 3 }, { 4 }, { 5 }, { 6 }, { 7 }, { 8 }, { 9 }, { 10 }, { 11 }, { 12 }, { 13 }, { 14 }, { 15 }, { 16 }, 17);
    std::cout << value << std::endl;
}
```

[ParametersCrashCppCli.zip](https://github.com/user-attachments/files/26902824/ParametersCrashCppCli.zip)

### Expected behavior

The function executes normally and returns the sum of all 18 arguments (153).

### Actual behavior

An unhandled HRException (Microsoft C++ exception) is thrown during the IJW native-to-managed thunk dispatch:

```
Exception thrown at 0x00007FFE757773FA in ParametersCrashCppCli.exe:
Microsoft C++ exception: HRException at memory location 0x0000008702CFEC38.
```
Callstack:

```
KernelBase.dll!00007ffe757773fa
ParametersCrashCppCli.exe!main  [ParametersCrashCppCli.cpp @ line with Sum17 call]
ParametersCrashCppCli.exe!invoke_main
ParametersCrashCppCli.exe!__scrt_common_main_seh
```

### Regression?

yes, works in .NET8

### Known Workarounds

reduce number of parameters

## Environment

| Component       | Version                                                                 |
|-----------------|-------------------------------------------------------------------------|
| .NET Runtime    | 10.0.5                                                                  |
| `coreclr.dll`   | 10.0.5 (`C:\...\dotnet-sdk\shared\Microsoft.NETCore.App\10.0.5\`)      |
| `clrjit.dll`    | 10.0.5 (`C:\...\dotnet-sdk\shared\Microsoft.NETCore.App\10.0.5\`)      |
| `Ijwhost.dll`   | loaded from `x64\Debug\Ijwhost.dll`                                     |
| MSVC toolset    | 14.50.35717                                                             |
| Visual Studio   | 18 Professional                                                         |
| OS              | Windows (x64)                                                           |
| Architecture    | x64                                                                     |
| Configuration   | Debug                                                                   |

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkoritzinsky**
> [!NOTE]
> This PR was authored with the assistance of GitHub Copilot.

## Summary

Fixes #127166 — IJW (C++/CLI) reverse P/Invoke throws `OverflowException` when calling a managed function with 17+ by-ref parameters from native code.

## Root Cause

`StubSigBuilder::EnsureEnoughQuickBytes` only doubled the buffer size once. When `FunctionSigBuilder::SetSig` needed to store a 524-byte parameter signature (18 by-ref params with custom modifiers), the buffer grew from 256 → 512 bytes — still in the `CQuickBytes` inline buffer. Writing 524 bytes overflowed the 512-byte inline buffer by 12 bytes into the adjacent `m_nItems` field, corrupting the arg count from 18 to garbage (~0x2800220F). This caused `GetSigSize()` to compute an overflowed `S_UINT32` and throw `COR_E_OVERFLOW`.

## Why This Regressed

PR #106000 changed `ConvertToInternalSignature` to preserve custom modifiers (`bSkipCustomModifier=FALSE`). Each preserved modifier adds 10 bytes (`ELEMENT_TYPE_CMOD_INTERNAL` + required byte + 8-byte TypeHandle pointer). For 18+ parameters with `NeedsCopyConstructorModifier`, the signature exceeded 512 bytes for the first time, triggering the latent buffer overflow in `EnsureEnoughQuickBytes`.

## Fix

Loop the doubling in `EnsureEnoughQuickBytes` until the buffer is large enough to hold the requested data.

## Regression Test

Added an IJW test with a managed function that has 18 by-ref parameters (`const int&` and `const IntWrapper&`), called from native `#pragma unmanaged` code. The test verifies the correct sum (153) is returned.

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/vm/stubgen.cpp [hunk 1]
```diff
@@ -2005,7 +2005,14 @@ void StubSigBuilder::EnsureEnoughQuickBytes(size_t cbToAppend)
     SIZE_T cbBuffer = m_qbSigBuffer.Size();
     if ((m_cbSig + cbToAppend) >= cbBuffer)
```
Comment (jkotas) [inline src/coreclr/vm/stubgen.cpp]:
```suggestion
    if ((cbBuffer - m_cbSig) < cbToAppend)
```
`m_cbSig + cbToAppend` can overflow in theory. Comparing against available space is more robust pattern.

File: src/coreclr/vm/stubgen.cpp [hunk 2]
```diff
@@ -2005,7 +2005,14 @@ void StubSigBuilder::EnsureEnoughQuickBytes(size_t cbToAppend)
...
     {
-        m_qbSigBuffer.ReSizeThrows(2 * cbBuffer);
+        S_SIZE_T cbNew = S_SIZE_T(cbBuffer) * S_SIZE_T(2);
+        while (!cbNew.IsOverflow() && (m_cbSig + cbToAppend) >= cbNew.Value())
+        {
+            cbNew *= S_SIZE_T(2);
+        }
+        if (cbNew.IsOverflow())
+            COMPlusThrowHR(COR_E_OVERFLOW);
```
Comment (jkotas) [inline src/coreclr/vm/stubgen.cpp]:
```suggestion
        SIZE_T cbNew = max(m_cbSig + cbToAppend, 2 * cbBuffer);
        // Detect integer overflow
        if ((cbNew - m_cbSig) < cbToAppend)
            COMPlusThrowHR(COR_E_OVERFLOW);
```
This is simpler (and fixes the potential integer overflow)

File: src/coreclr/vm/stubgen.cpp [hunk 3]
```diff
@@ -2003,9 +2003,13 @@ void StubSigBuilder::EnsureEnoughQuickBytes(size_t cbToAppend)
...
     SIZE_T cbBuffer = m_qbSigBuffer.Size();
-    if ((m_cbSig + cbToAppend) >= cbBuffer)
+    if ((cbBuffer - m_cbSig) < cbToAppend)
     {
-        m_qbSigBuffer.ReSizeThrows(2 * cbBuffer);
+        SIZE_T cbNew = max(m_cbSig + cbToAppend, 2 * cbBuffer);
+        // Detect integer overflow
+        if ((cbNew - m_cbSig) < cbToAppend)
+            COMPlusThrowHR(COR_E_OVERFLOW);
+        m_qbSigBuffer.ReSizeThrows(cbNew.Value());
```
Comment (jkotas) [inline src/coreclr/vm/stubgen.cpp]:
```suggestion
        m_qbSigBuffer.ReSizeThrows(cbNew);
```

**Review by AaronRobinsonMSFT — APPROVED** [review]

File: src/coreclr/vm/stubgen.cpp [hunk 4]
```diff
@@ -2041,9 +2041,13 @@ void StubSigBuilder::EnsureEnoughQuickBytes(size_t cbToAppend)
     STANDARD_VM_CONTRACT;
 
     SIZE_T cbBuffer = m_qbSigBuffer.Size();
-    if ((m_cbSig + cbToAppend) >= cbBuffer)
+    if ((cbBuffer - m_cbSig) < cbToAppend)
     {
-        m_qbSigBuffer.ReSizeThrows(2 * cbBuffer);
+        SIZE_T cbNew = max(m_cbSig + cbToAppend, 2 * cbBuffer);
```
Comment (jkoritzinsky) [inline src/coreclr/vm/stubgen.cpp]:
```suggestion
        SIZE_T cbNew = max((SIZE_T)(m_cbSig + cbToAppend), 2 * cbBuffer);
```
