### PR TITLE
JIT: Improve block IL offset range selection when splitting

### LINKED ISSUE #119616: [RuntimeAsync] Assertion failed 'lastBlockILEndOffset < beginOffs'
Observed while enabling rt async in Libraires partition - https://github.com/dotnet/runtime/pull/119432

There is code in `CreateCheckAndSuspendAfterCall` that splits the basic block that contains await. Somehow when the splitting operation infers the IL range for the shortened block, it may end up with longer IL range than before shortening, thus overlapping with the IL range of the splitted-off remainder block. 

This can trigger asserts later on when introducing scopes for untracked locals.

There is a hack/workaround in https://github.com/dotnet/runtime/pull/119432/commits/6a2972197f88eac6dc376fe956ce236b64ebc4b5

that illustrates/suppresses the issue, but that is not a fix.

### PR DESCRIPTION
**Pull request by jakobbotsch**
In debug codegen we expect basic blocks to have valid start IL offsets, potentially to an invalid IL end offset.

When we split a block at a node, we find the end offset by looking backwards from that node for an `IL_OFFSET` node. If we find such a node, we use it as the split point IL offset. Otherwise we use `BAD_IL_OFFSET` and start the next block at the end offset (making it have a 0 byte range).

This latter behavior is problematic if the bottom portion of the split has its own `IL_OFFSET` nodes. In that case we can end up with `IL_OFFSET` nodes pointing outside the region of the basic block. If we later split again, then we can end up creating illegal IL offset ranges for unoptimized code. In an example case we first ended up with the bottom block having an IL offset range of `[0aa..0aa)` but still containing an `IL_OFFSET` with an offset of `092`. When we later split the bottom block again we ended up with `[0aa..0aa), [092..0aa)` and hit an assert.

To address the problem change the behavior in the following way:
* If we find no `IL_OFFSET` node in the upper block, then look for one in the lower block, and use its value as the split point
* If we find no `IL_OFFSET` in both blocks then consider the lower block empty and the upper block to have everything (same behavior as before).
* One exception to above: if the end was already `BAD_IL_OFFSET` then we have to consider the upper block to be empty as we cannot represent the other case

This fixes #119616. However for that specific case, which is inside async code, we will have the exact IL offset of the async call we are splitting at after #120303, so we will be able to do better. I'll make that change as part of that PR.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
PTAL @dotnet/jit-contrib. Failures are Android timeouts and known issues.

**Comment by VSadov** [comment]
After the #120303 merged I see a different assert:
```
  Assert failure(PID 45844 [0x0000b314], Thread: 43504 [0xa9f0]): Assertion failed 'Valid()' in 'System.IO.Compression.CompressionStreamUnitTestBase:Read(System.String):this' during 'Emit code' (IL size 211; hash 0x11c1e97a; Tier1-OSR)
  
      File: E:\dotnet004\runtime\src\coreclr\jit\emit.cpp:60
      Image: E:\dotnet004\runtime\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe

  Assert failure(PID 37232 [0x00009170], Thread: 14144 [0x3740]): Assertion failed 'Valid()' in 'System.IO.Compression.CompressionStreamUnitTestBase:RoundTripWithZLibCompressionOptions(System.String,System.IO.Compression.ZLibCompressionOptions):this' during 'Emit code' (IL size 176; hash 0x03f009b8; Tier1-OSR)
  
      File: E:\dotnet004\runtime\src\coreclr\jit\emit.cpp:60
      Image: E:\dotnet004\runtime\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe
  
  Assert failure(PID 49552 [0x0000c190], Thread: 31992 [0x7cf8]): Assertion failed 'Valid()' in 'System.Linq.AsyncEnumerable:<ToLookupAsync>g__Impl|190_0[System.__Canon,int](System.Collections.Generic.IAsyncEnumerable`1[System.__Canon],System.Func`3[System.__Canon,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask`1[int]],System.Collections.Generic.IEqualityComparer`1[int],System.Threading.CancellationToken):System.Linq.ILookup`2[int,System.__Canon]' during 'Emit code' (IL size 151; hash 0x35af0c6f; Tier1-OSR)
  
        Condition(s) not met: "NotSourceGenMode"
      File: E:\dotnet004\runtime\src\coreclr\jit\emit.cpp:60
      Image: E:\dotnet004\runtime\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe
```


It is just 3 failures, vs 16, so it is an improvement. 

Not sure if the assert is expected without the fix in this PR, - just FYI in case it is not.

It seems the new assert does not require `-lc Debug`

**Comment by jakobbotsch** [comment]
> After the #120303 merged I see a different assert:
> 
> ```
>   Assert failure(PID 45844 [0x0000b314], Thread: 43504 [0xa9f0]): Assertion failed 'Valid()' in 'System.IO.Compression.CompressionStreamUnitTestBase:Read(System.String):this' during 'Emit code' (IL size 211; hash 0x11c1e97a; Tier1-OSR)
>   
>       File: E:\dotnet004\runtime\src\coreclr\jit\emit.cpp:60
>       Image: E:\dotnet004\runtime\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe
> 
>   Assert failure(PID 37232 [0x00009170], Thread: 14144 [0x3740]): Assertion failed 'Valid()' in 'System.IO.Compression.CompressionStreamUnitTestBase:RoundTripWithZLibCompressionOptions(System.String,System.IO.Compression.ZLibCompressionOptions):this' during 'Emit code' (IL size 176; hash 0x03f009b8; Tier1-OSR)
>   
>       File: E:\dotnet004\runtime\src\coreclr\jit\emit.cpp:60
>       Image: E:\dotnet004\runtime\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe
>   
>   Assert failure(PID 49552 [0x0000c190], Thread: 31992 [0x7cf8]): Assertion failed 'Valid()' in 'System.Linq.AsyncEnumerable:<ToLookupAsync>g__Impl|190_0[System.__Canon,int](System.Collections.Generic.IAsyncEnumerable`1[System.__Canon],System.Func`3[System.__Canon,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask`1[int]],System.Collections.Generic.IEqualityComparer`1[int],System.Threading.CancellationToken):System.Linq.ILookup`2[int,System.__Canon]' during 'Emit code' (IL size 151; hash 0x35af0c6f; Tier1-OSR)
>   
>         Condition(s) not met: "NotSourceGenMode"
>       File: E:\dotnet004\runtime\src\coreclr\jit\emit.cpp:60
>       Image: E:\dotnet004\runtime\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe
> ```
> 
> It is just 3 failures, vs 16, so it is an improvement.
> 
> Not sure if the assert is expected without the fix in this PR, - just FYI in case it is not.
> 
> It seems the new assert does not require `-lc Debug`

Not expected, I'll take a look at that.

**Comment by jakobbotsch** [comment]
PTAL @EgorBo

File: src/coreclr/jit/fgbasic.cpp [hunk 1]
```diff
@@ -4840,11 +4840,34 @@ BasicBlock* Compiler::fgSplitBlockAfterNode(BasicBlock* curr, GenTree* node)
             }
         }
 
-        curr->bbCodeOffsEnd = max(curr->bbCodeOffs, splitPointILOffset);
+        if (splitPointILOffset == BAD_IL_OFFSET)
+        {
+            // Try to look forwards in the next block
+            for (GenTree* node : LIR::AsRange(newBlock))
```
Comment (EgorBo) [inline src/coreclr/jit/fgbasic.cpp:4846]: Does LIR::AsRange always guarantee in HIR that it will walk trees in the execution order?

**Review by EgorBo — APPROVED** [review]
Makes sense to me

File: src/coreclr/jit/fgbasic.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/fgbasic.cpp:4846]: This function is only used for LIR (there is an assert at the top)

**Comment by jakobbotsch** [comment]
> After the #120303 merged I see a different assert:
> 
> ```
>   Assert failure(PID 45844 [0x0000b314], Thread: 43504 [0xa9f0]): Assertion failed 'Valid()' in 'System.IO.Compression.CompressionStreamUnitTestBase:Read(System.String):this' during 'Emit code' (IL size 211; hash 0x11c1e97a; Tier1-OSR)
>   
>       File: E:\dotnet004\runtime\src\coreclr\jit\emit.cpp:60
>       Image: E:\dotnet004\runtime\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe
> 
>   Assert failure(PID 37232 [0x00009170], Thread: 14144 [0x3740]): Assertion failed 'Valid()' in 'System.IO.Compression.CompressionStreamUnitTestBase:RoundTripWithZLibCompressionOptions(System.String,System.IO.Compression.ZLibCompressionOptions):this' during 'Emit code' (IL size 176; hash 0x03f009b8; Tier1-OSR)
>   
>       File: E:\dotnet004\runtime\src\coreclr\jit\emit.cpp:60
>       Image: E:\dotnet004\runtime\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe
>   
>   Assert failure(PID 49552 [0x0000c190], Thread: 31992 [0x7cf8]): Assertion failed 'Valid()' in 'System.Linq.AsyncEnumerable:<ToLookupAsync>g__Impl|190_0[System.__Canon,int](System.Collections.Generic.IAsyncEnumerable`1[System.__Canon],System.Func`3[System.__Canon,System.Threading.CancellationToken,System.Threading.Tasks.ValueTask`1[int]],System.Collections.Generic.IEqualityComparer`1[int],System.Threading.CancellationToken):System.Linq.ILookup`2[int,System.__Canon]' during 'Emit code' (IL size 151; hash 0x35af0c6f; Tier1-OSR)
>   
>         Condition(s) not met: "NotSourceGenMode"
>       File: E:\dotnet004\runtime\src\coreclr\jit\emit.cpp:60
>       Image: E:\dotnet004\runtime\artifacts\bin\testhost\net10.0-windows-Release-x64\dotnet.exe
> ```
> 
> It is just 3 failures, vs 16, so it is an improvement.
> 
> Not sure if the assert is expected without the fix in this PR, - just FYI in case it is not.
> 
> It seems the new assert does not require `-lc Debug`

@VSadov This should be fixed by #121502
