### PR TITLE
[mono][interp] Optimize ves_pinvoke_method () on wasm.

### LINKED ISSUE #25113: [Perf] Linux/x64: 12 Regressions on 11/20/2023 6:28:42 AM
### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [83f116627e2548c7a55b3701bd5448570b84a784](https://github.com/dotnet/runtime/commit/83f116627e2548c7a55b3701bd5448570b84a784)
Compare | [5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb](https://github.com/dotnet/runtime/commit/5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Diff | [Diff](https://github.com/dotnet/runtime/compare/83f116627e2548c7a55b3701bd5448570b84a784...5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Configs | CompilationMode:wasm, RunKind:micro

### Regressions in System.Collections.CtorFromCollectionNonGeneric&lt;String&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Queue - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Collections.CtorFromCollectionNonGeneric(String).Queue(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Create/CtorFromCollectionNonGeneric.cs#L34-#L35>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TMBR9R+I/+M0JZG1IR9VVZGIr2xjQqbR9Qwi5yV1i5I/o2lmbCfHbsdOqWzsJ5SWyT84599i5N1NgpkaQoKx59YesS0AglzUX+RwqTdKU0FxbBbaPtbJcAj1kXSJTWdnyEO5NvwSWm75kXB0RLzAruYXMumqEKxLQzfCURoQylG4R7tlLMPaOSfCeH+miMRZkb6KFcFqulelNrMZr1PIJu9PqBhQgzz4sLHJVnPe+11BDsOCPMCbv3yXhU5p5rSZa3fOiRtYa/qATLSsu2t1U50B/kvQvoWtmJH39P52DvnKV7/iSZ6ifCbgBWdkmeCG80DbsQLvV5pt4kO3tdeF/MVeq4Aq6cL1xF95UK90xrqfeKgtYIbhnF8ms0Mum6hR4VjaGZ0zM3IfXHukq/NyskOc3Qq+Y4I8t1kU2T+ZdK1xtKtd6foJ82x428kS7qQFc6mq3OhyKpZMtLJMVOSc5s+AHLEjiZHASj06S0TIejZN4PBj2BvHg7Ox0+DaOx3HsS5haSoauvQnD4pdkm6A19Aki8iYkq+aoQrQfrMi3cjsfzqdC/dsN0QvyHEwtbIoudR48O8kWv3gAZIVzGoQRaa28cXqNHFQumj3iL6vd+Mjo3gESf8asZGjJmtuSBMZdHph0r4nIJtOilio9ztRscZNuQzii5VZASj+5q3O/kma39RISKBN6zFSC25RtwIT/AJQky13sBAAA>)</li></ul> | 339.88 μs | 370.31 μs | 1.09 | 0.14 | False | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_28_2023/refs/heads/main_x64_ubuntu%2022.04_CompilationMode%3Dwasm_RunKind%3Dmicro_Regression/System.Collections.CtorFromCollectionNonGeneric%28String%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.CtorFromCollectionNonGeneric&lt;String&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-01c4a606-e56e-4f80-8132-e5301652663235fd9152dce4de19a/14da6fd9-324e-40fa-85f5-4c4401fcd9e2.zip?sv=2021-08-06&se=2023-12-20T00%3A39%3A18Z&sr=c&sp=rl&sig=e1VS67n%2FJyUqEZzPM1Ty14urz0MFmmVDrH1sdG8Vh5I%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-3de10032-20fb-4059-b9ce-bae299fbc721d3184b1387044cd97/eb84a456-01cc-4482-af4e-dfb8f5a9a711.zip?sv=2021-08-06&se=2023-12-20T14%3A25%3A20Z&sr=c&sp=rl&sig=MgZn2XSLNomLyrB2sdf609PhCiqrhleyJNJ433r1ZNI%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [83f116627e2548c7a55b3701bd5448570b84a784](https://github.com/dotnet/runtime/commit/83f116627e2548c7a55b3701bd5448570b84a784)
Compare | [5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb](https://github.com/dotnet/runtime/commit/5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Diff | [Diff](https://github.com/dotnet/runtime/compare/83f116627e2548c7a55b3701bd5448570b84a784...5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Configs | CompilationMode:wasm, RunKind:micro

### Regressions in System.Reflection.Attributes

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[IsDefinedMethodOverrideHitInherit - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Reflection.Attributes.IsDefinedMethodOverrideHitInherit.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/runtime/System.Reflection/Attributes.cs#L89-#L90>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JsdcBPXqaookhHpBzSFQHDzhhC62Jv40H1Ye+smrhC/nTsnCk0qIb9YvvHM7Nxq1zPgtkZQoMm++s02JSCwq1rIIoPKsDRlQWFIAw2w1iQUBMesK+Q6L1sewsoOSuCFHSgu9AlxgnkpCHJy1ZjQLAy2lxdBxAKOyr30DuwFWPrCFXjP98FDYwlUP4OVdFphdH9ChGJZE9j+1N7ASmgoZkClKb4+AqIo4E7QVDsvQf8yZLW+Nnol1jVyb2O/B9dGVUK2p5kpIPjB0j8s2HCrgtf/0znok9DFnq9EjuaZQFhQFTXhC+HEUK8DbWrsZ/mo2p514d/bW712PejC9cZdeDOjTce4njrVBFghuGcXyXxtFk3VKfC8bKzIuZyjUcYjXYV3zdJNwkdpllyKpxbrIsuSrGuF223lJszvjR/W4/G9Nm5XABem2r8dr8LCyR6Iq4q9YwUn8GsVJnEyPItHZ8loEY/Gyfn4POlfXiTDJBm+jeNxHPsStlaKo3gCxnH9U/Ft2Br6BBF702PL5qRCdFinyI/ytxpqcD4Vml9unV6QM7C1pBRd6iJ8dpMdPnH7xdfOadiLWGvljdMPKEAXsjkgvlntwUdG9w2Q+TvmJUdiG0ElC61rHtj0oInYNjeyVjo9zdTscJvuQjgiCZKQBjeude4H0uyPXsJCbXses5UUlPIt2N5fkEI+WOIEAAA=>)</li></ul> | 1.46 μs | 1.58 μs | 1.08 | 0.16 | False | | |
|<ul><li>[IsDefinedMethodOverrideMiss - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Reflection.Attributes.IsDefinedMethodOverrideMiss.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/runtime/System.Reflection/Attributes.cs#L96-#L97>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U0W7TQBB8R+If7s02uIlroyqKZESaFkghENy8IYQu9iY+5Luzds9NXCG+nTsnCk0qIb9YvvHM7Nxq13Pg1CBIUIZe/GbbEhDYdSOqIoNaszRlXqGNAjPERhkhwTtlXSNXednxENY0LIEXNJRcqDPiBPNSGMiNrcaEYr63u3rjhczjKO1LcGQvgcwXLsF5vvPuWzIgBxmsK6sVWg0mxqBYNQZoMKMbWAsFxRxMqYuvD4AoCpgLon/Vs0ZNtVqLTYPcGdB3b6plLaruNNcFeD9Y+od5W07Se/k/nYU+CVUc+FLkqJ8IBIGsTes/E060CXrQZpo+Vw+y61Yf/h3dqo29fR+uM+7Dm2ule8Z11JkygDWCffaRLDZ62da9Ai/KlkTOqwVqqR3SV/ixXdkZ+FDpFa/EY4f1kWVx1rfC7a4GtJugujE9HdyptlsCuNT14e10CZZWdm+4rNlbVnADbqH8OIqTi2h0EY+W0WgcX44v48EouUqS5PJ1FI2jyJWgRkqO4hEYx81PyXd+Z+gShOxVwFbtWYXwuEihG+VvDTRgfWrUv+wiPSNnQE1lUrSpC//JTfb4xG4W31inJAhZZ+WM0/coQBVVe0Rcs7qDi4z2GyBzd8xLjoZthSmZT7Z5QOlRE7JdrqtGqvQ8U7vHKd2HsEQjTAWpd2NbZ38d7eHoJMxXFDiM6kqYlO+Agr9qLZx73AQAAA==>)</li></ul> | 1.47 μs | 1.59 μs | 1.08 | 0.14 | False | | |
|<ul><li>[IsDefinedClassHit - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Reflection.Attributes.IsDefinedClassHit.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/runtime/System.Reflection/Attributes.cs#L84-#L85>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcFM3qSBEMiJNSxsgKLh5Qwhd7E186D6s3XMTV4jfzp0ThSaVkF8s33hmdm616xlwqhEUaEsvfrNNCQjsqhayyKAyLE1ZUBirwZ5jra1QEByzrpDrvGx5CCs6L4EXdK640CfEMealsJBbV40JzcJg++YyiFnAUbmX6MBeANmvXIH3/BDcN2RB9TJYSacVRvfG1qJY1haoN6VrWAkNxURyojth/9XMaj0xeiXWNXIvo+/BxKhKyPY0MwUEP1j6hwUbTip4+T+dgz4LXez5SuRonggEgapsEz4Tjo2NOtCmhr7IB9X2qAv/E93otbtzF6437sKbGW06xvXUqbaAFYJ7dpHM12bRVJ0Cz8uGRM7lHI0yHukqvGuWKIpbaZZciscW6yLL+lnXCjfbCtDNv26H83hcJ8btBuDCVPu349FfONm95api71nBLfg1CvtJf3CWDM/6w0UyHPUvRheDXtJ/O3w3uHydJKMk8SWoVoqjeATGcf1T8W3YGvoEMXsVsWVzUiE+rE/sR/lbDTU4nwrNL7c+z8gZUC1tii51ET65yQ4fPwDytXMaRDFrrbxx+hEF6EI2B8Q3qz34yOi+ATJ/x7zkaNlG2JKF5JoHlB40MdvmRtZKp6eZmh1O6S6EI1phJaTBtWud+2E0+6OXsFBT5DGqpLAp3wJFfwGGEZzg0gQAAA==>)</li></ul> | 950.22 ns | 1.03 μs | 1.08 | 0.15 | False | | |
|<ul><li>[IsDefinedMethodOverrideMissInherit - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Reflection.Attributes.IsDefinedMethodOverrideMissInherit.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/runtime/System.Reflection/Attributes.cs#L91-#L92>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBPHQRBVMiJNCw0QCGneEEIXexMfug/rdt3EFeK3c+dEoUkl5BfLN56ZnVvtegYcawsKNOGz32xbggV2VQtZLKAyLMtYUBjSQH1baxIKglPWleU6L1uehTX2S+AF9hUX+ow4tnkpCHJy1ZjQLAx2r18FMQu4Ve4lOrKXgPSFK/Ce74K7BglUbwFr6bTC6N6YyIpVTYC9KV7DWmgoZkClKb7eg7WigJlAnGpnJuhfiEWtJ0avxaa23Pvg92BiVCVke5qZAoIfLPvDgi1HFTz/n85Bn4QuDnwlcmseCQSCqqgJnwjHhqIOtKnBz/JetU3rwv+IN3rjmtCF64278GZGm45xPXWqCWxlwT27SOYbs2yqToHnZYMi53JujTIe6Sq8bVZuFD5Is+JSPLRYF9kiXXStcLOr3IT5xfHTejq/E+OWBezSVIe3011YOtkdcVWxt6zgBH6vwjRJhxfJ6CIdLZPRZTq4HAx76WD4ZjhIXybJZZL4Elgrxa14AMbt5qfiu7A19Ali9iJiq+asQnzcp9iP8rcaanA+lTW/3D49IS8Aa0mZdamL8NFN9vjYLRjfOKdhFLPWyhtn760AXcjmiPhmtQcf2bpvYJm/Y15yS2wrqGQhuuYBZkdNzHa5kbXS2XmmZo9jtg/hiCRIQhZcu9a5P0hzOHoJCzVGHsNKCsr4DjD6C2QJ0zXjBAAA>)</li></ul> | 1.50 μs | 1.59 μs | 1.06 | 0.10 | False | | |

graph
graph
graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_28_2023/refs/heads/main_x64_ubuntu%2022.04_CompilationMode%3Dwasm_RunKind%3Dmicro_Regression/System.Reflection.Attributes.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Reflection.Attributes*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-01c4a606-e56e-4f80-8132-e5301652663235fd9152dce4de19a/14da6fd9-324e-40fa-85f5-4c4401fcd9e2.zip?sv=2021-08-06&se=2023-12-20T00%3A39%3A18Z&sr=c&sp=rl&sig=e1VS67n%2FJyUqEZzPM1Ty14urz0MFmmVDrH1sdG8Vh5I%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-3de10032-20fb-4059-b9ce-bae299fbc721d3184b1387044cd97/eb84a456-01cc-4482-af4e-dfb8f5a9a711.zip?sv=2021-08-06&se=2023-12-20T14%3A25%3A20Z&sr=c&sp=rl&sig=MgZn2XSLNomLyrB2sdf609PhCiqrhleyJNJ433r1ZNI%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [83f116627e2548c7a55b3701bd5448570b84a784](https://github.com/dotnet/runtime/commit/83f116627e2548c7a55b3701bd5448570b84a784)
Compare | [5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb](https://github.com/dotnet/runtime/commit/5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Diff | [Diff](https://github.com/dotnet/runtime/compare/83f116627e2548c7a55b3701bd5448570b84a784...5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Configs | CompilationMode:wasm, RunKind:micro

### Regressions in System.Tests.Perf_Enum

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[ToString_NonFlags_Large - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Tests.Perf_Enum.ToString_NonFlags_Large(value%3a%20Format).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime/Perf.Enum.cs#L47-#L53>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U74/SQBD9buL/sN/aKge1pychqZFD0NPjgsA3Y8jSDu2a/dHM7gK9GP92dwvBg0tMvzQ7b9+beTuZ6RSotggCpNEvfpNdCQjk1jKez6FSJE1JkCsjwfTQSsMEBOesW6QyKxsewkb3SqC57gnK5AVxiFnJDGTGVSNMkjDY37wNOiSgKNwhOrGXoM0DFeBzfgwWtTYguh7U3RngZjWW1sVqYZDJYvWg5ITTQq/uKRYQbim3MCAThYKa6J+FuZUjJTessEgNU1L/CEZKVIw30VTlEPwk6R8S7KgWwcv/6Rz0jcn8yBcsQ/VEwDSIytThM+FQmagF7U7pe74VTcva8L/qsSyYhDZcn7gNb6qkamnXU++kAawQ3LeNZFaoZV21Mjwra80yymeohPJIW+GXeo0s/8zVmnL22GBtZPNk3rbCeF8BunWQzayeT+9IuVUBXKrqeDrfhKWTLQwVFflAcmrAb1WYxMn1Vdy/SvrLuD9I3gySpPsuid8nyc3rOB7EsS+hrRAU2SMQN+wrQfdhk9A76JBXEVnXFxU6p23q+FH+bsGCy1Oh+uU28Rl5Dtpyk6JznYdPXnLAh1tAWrhM11GHNKl84nSCDGTO6xPim9UE3jK6O0Di35iVFA3ZMVOSULvmgU5Pmg7ZZ4pbIdNLT/UB1+nBhCMaZjikwSfXOvf/qI+hl5BQ6shjuuLMpHQPOvoLSgmjQOEEAAA=>)</li></ul> | 338.80 ns | 387.60 ns | 1.14 | 0.17 | False | | |
|<ul><li>[ToString_Format_NonFlags - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Tests.Perf_Enum.ToString_Format_NonFlags(value%3a%20Monday%2c%20format%3a%20%22g%22).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime/Perf.Enum.cs#L55-#L65>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXY/aMBB8r9T/YN1LkjYHuVyFAClVOcq115YTBd6qCplkSVz5I1o7QE5Vf3vtgOjBSVVeIu94Zne82s0UqK4QBEijX/0muwIQyF3FeDaHUpEkIV6mjATTxUoaJsA7Z90hlWnR8BA2ulsAzXRXUCYviCNMC2YgNbYaYZL43r73zguJR1HYQ3BiL0GbRyrA5fzgLWptQHQcqDszwM1qIisbq4VBJvPVvUJBzepRyXtOc+1vKa9gSKZKZrQOyaa5HpKr/Cr4Z2heybGSG5ZXSA1TUv/wxkqUjDfRVGXg/STJH+LtqBbe6//pLPSVyezIFyxF9UzANIjS1P4L4UiZoAXtQelvfCuaBrbhf9ETmTMJbbgucRuebaVqaddRH6QBLBHst41klqtlXbYyPCtqzVLKZ6iEckhb4ed6jSz7xNWacvbUYG1k83jetsJkXwLa5ZDN5J7P8ljZxQFcqvJ4Ot+LpZUtDBUleU8yasDtmB9H8e111L+O+8uoP4xvhnHc6Q3iweCm9zaKhlHkSuhKCIrsCQjFfCXo3m8SOgcheROQdX1RITztVuhG+XsFFdg8Japfdi9fkOegK24StK4z/9lLDvhoC0hzm+k2CEmTyiVO7pGBzHh9QlyzmsBZRnsHSNwb04KiITtmCuJr2zzQyUkTkn2qeCVkcumpPuA6OZiwRMMMh8T7aFtn/yb1MXQS4ksdOEyXnJmE7kEHfwFmK0xL7wQAAA==>)</li></ul> | 335.01 ns | 385.13 ns | 1.15 | 0.19 | False | | |
|<ul><li>[ToString_Format_NonFlags - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Tests.Perf_Enum.ToString_Format_NonFlags(value%3a%20Thursday%2c%20format%3a%20%22f%22).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime/Perf.Enum.cs#L55-#L65>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/nPpiG9zUdRGESEa0IS0FUoUkbwhFF3tjH7oPa+8uiSvEb+fOiUKTSsgvlnc8Mzu3uvUYqLYIAqTRL36TTQUI5MYyXkyhViTLSFAoI8FcoJWGCQiOWTdIZV61PISVvqiAFvpCUCZPiNeYV8xAblw3wiQJg+3bN0FMAorCvUQH9hy0eaACvOfHYNZoA6LnQd2bAK4WI2ldrWYGmSwXtwoFNYsHJW85LXW4ptzCgMwri7qgTUxWLWFAzlZn0b9IUyuHSq5YaZEapqT+EQyVqBlvq7EqIPhJsj8k2FAtgpf/0znoK5PFni9YjuqJgGkQtWnCZ8JrZaIOtHulv/G1aEfYhf9Fj2TJJHTheuMuvLGSqmNcT72XBrBGcM8ukkmp5k3dKfCkajTLKZ+gEsojXYWfmyWy4o6rJeXsscW6yKbptGuH0bYGdOsh27t7fJuHyq0O4FzV+7fjzZg72cxQUZMPpKAG/JaFaZJenSf987Q/T/qD9HKQpr33yWXaf3f1OkkGSeJbaCsERfYIhGK5EHQbtoY+QUxeRWTZnHSID9sV+6v83YIF51Oj+uU28xl5Ctpyk6FLXYRPTrLDr9eAtHROV1FMWitvnN0iA1nw5oD4YbWFj4zuGyDxZ8wrioZsmKlIqN3wQGcHTUy2ueJWyOw0U7PDdbYL4YiGGQ5Z8MmNzv1Pmn3pJSSUOvKYrjkzGd2Cjv4C+PcMZPEEAAA=>)</li></ul> | 374.90 ns | 428.70 ns | 1.14 | 0.23 | False | | |
|<ul><li>[ToString_Format_NonFlags - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Tests.Perf_Enum.ToString_Format_NonFlags(value%3a%20Tuesday%2c%20format%3a%20%22d%22).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime/Perf.Enum.cs#L55-#L65>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U72vbMBD9Ptj/IPrF9uYmrlO2EvBYmqVdt7VkSb6NERT7YmvohzlJSVzG/vZJTsiaFoa/GN3Te3dPx53vgWqLIEAa/eo32VaAQK4t48UMakWyjASFMhJMH600TEBwyrpGKvOq5SGsdb8CWui+oEw+I44wr5iB3LhqhEkSBrt3l0FMAorCHaIjewHaPFABPufHYN5oA6LnQd2bAq6XE2ldrOYGmSyXNwoFNcsHJW84LXW4odzCkCws6II2MVm390NyVpxF/xzNrBwruWalRWqYkvpHMFaiZryN7lUBwU+S/SHBlmoRvP6fzkFfmSwOfMFyVE8ETIOoTRO+EI6UiTrQ7pT+xjei7WAX/hc9kSWT0IXrE3fh3SupOtr11DtpAGsE9+0imZZq0dSdDE+rRrOc8ikqoTzSVfi5WSErbrlaUc4eW6yLbJbOulaY7GpAtx2yHd3TYR4rtzmAC1UfTqeLsXCyuaGiJh9IQQ34JQvTJB2cJ1fn6dUiuRqmF8N00Lu4TNPB5fu3STJMEl9CWyEoskcgFMuloLuwTegdxORNRFbNswrxcbliP8rfLVhweWpUv9xiviDPQFtuMnSui/DJS/b4aANIS5dpEMWkTeUTZzfIQBa8OSK+WW3gLaO7AyT+jXlF0ZAtMxUJtWse6OyoickuV9wKmT331Oxxne1NOKJhhkMWfHKtc7+T5hB6CQmljjyma85MRnego7+uRFlE8AQAAA==>)</li></ul> | 300.02 ns | 346.42 ns | 1.15 | 0.19 | False | | |
|<ul><li>[ToString_Format_NonFlags - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/System.Tests.Perf_Enum.ToString_Format_NonFlags(value%3a%20Friday%2c%20format%3a%20%22X%22).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Runtime/Perf.Enum.cs#L55-#L65>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1U74/SQBD9buL/sLkvbbUHtajHkdTInaCnckHgg4kxZGmHds3+aGa3QC/Gv93dQvDgEtMvzc7b92beTmY6AaorBAHS6Ge/ybYABHJTMZ7NoFQkSYiXKSPBdLGShgnwTlk3SGVaNDyEte4WQDPdFZTJM+IQ04IZSI2tRpgkvrd7+9oLiUdR2ENwZC9Am3sqwOV8781rbUB0HKg7U8D1ciQrG6u5QSbz5VihoGZ5r+SY01z7G8orGJAxsozWIVk31wNy8f0i+GdoVslbJdcsr5AapqT+4d0qUTLeRBOVgfeTJH+It6VaeM//p7PQFyazA1+wFNUjAdMgSlP7T4RDZYIWtDulv/KNaBrYhv9Zj2TOJLThusRteBMlVUu7jnonDWCJYL9tJNNcLeqyleFpUWuWUj5FJZRD2go/1Ss7Dh+5WlHOHhqsjWwWz9pWGO1KQLscspnc01m+VXZxABeqPJxO92JhZXNDRUnekYwacDvmx1Hcu4z6l3F/EfUH8atB3Ov0oqs311fXL6NoEEWuhK6EoMgegFDMl4Lu/CahcxCSFwFZ1WcVwuNuhW6Uv1VQgc1Tovpl9/IJeQa64iZB6zrzH71kjw83gDS3mXpBSJpULnFiFw9kxusj4prVBM4y2jtA4t6YFhQN2TJTEF/b5oFOjpqQ7FLFKyGTc0/1HtfJ3oQlGmY4JN4H2zr7N6kPoZMQX+rAYbrkzCR0Bzr4Cz75/dLvBAAA>)</li></ul> | 428.16 ns | 476.26 ns | 1.11 | 0.15 | False | | |

graph
graph
graph
graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_28_2023/refs/heads/main_x64_ubuntu%2022.04_CompilationMode%3Dwasm_RunKind%3Dmicro_Regression/System.Tests.Perf_Enum.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Tests.Perf_Enum*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-01c4a606-e56e-4f80-8132-e5301652663235fd9152dce4de19a/14da6fd9-324e-40fa-85f5-4c4401fcd9e2.zip?sv=2021-08-06&se=2023-12-20T00%3A39%3A18Z&sr=c&sp=rl&sig=e1VS67n%2FJyUqEZzPM1Ty14urz0MFmmVDrH1sdG8Vh5I%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-3de10032-20fb-4059-b9ce-bae299fbc721d3184b1387044cd97/eb84a456-01cc-4482-af4e-dfb8f5a9a711.zip?sv=2021-08-06&se=2023-12-20T14%3A25%3A20Z&sr=c&sp=rl&sig=MgZn2XSLNomLyrB2sdf609PhCiqrhleyJNJ433r1ZNI%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [83f116627e2548c7a55b3701bd5448570b84a784](https://github.com/dotnet/runtime/commit/83f116627e2548c7a55b3701bd5448570b84a784)
Compare | [5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb](https://github.com/dotnet/runtime/commit/5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Diff | [Diff](https://github.com/dotnet/runtime/compare/83f116627e2548c7a55b3701bd5448570b84a784...5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Configs | CompilationMode:wasm, RunKind:micro

### Regressions in PerfLabTests.CastingPerf

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[CheckArrayIsVariantGenericInterfaceReflection - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/PerfLabTests.CastingPerf.CheckArrayIsVariantGenericInterfaceReflection.html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/runtime/perflab/CastingPerf.cs#L426-#L430>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXY/TMBB8R+I/+C0J5NqQ41BUKYheOe4KV1RCxQtCyE22icEf0dq5JifEb8dOq6rtSSgvkXc8szte7WYBVDcIAqTRz/6QbQUI5LphvMigViRNiVcoI8GMsZGGCfBOWddIZV71PISNHldACz0WlMkz4hTzihnIja1GmCS+17557YXEoyjsITiwV6DNZyrA5XznLQE393TtQD2aUW2YLB02mlWQ/54i0m6uv1FkVJpbkIAsn0tjCTSHDDbcFmTqyEvWyJmSG1Y2SN2N/u7NlKgZ76OFKsD7QdK/xNtSLbzn/9NZ6BOTxZ4vWI7qSMA0iNp0/hPhVJlgAG2u9D1/EH3vhvA/6htZMglDuC7xEN5CSTXQrqP2ja8R7HeIZFmqVVcPMrysOs1yypeohHLIUOFdt0ZW3HK1ppw99tgQWRZnQyvctLUdOrc/bmhPx3im7M4ArlS9P52uxMrKvhoqavKWFNSAWy8/juLLiyi5iJNVlEziV5P4apTEURJfJS+jaBJFroRuhLAz/wiEYvlT0NbvEzoHIXkRkHV3ViE8rFXoRvlLAw3YPDWqX3ZDnpAz0A03KVrXhX/0kh0+fQCkpc10GYSkT+USpx+QgSx4d0Bcs/rAWUZ7B0jcG/OKoiFbZiria9s80OlBE5I2V7wRMj331O1wne5MWKJhhkPqvbetsz+Sbh86CfGlDhyma85MSlvQwT8j1BQg6gQAAA==>)</li></ul> | 570.48 ns | 670.21 ns | 1.17 | 0.11 | False | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_28_2023/refs/heads/main_x64_ubuntu%2022.04_CompilationMode%3Dwasm_RunKind%3Dmicro_Regression/PerfLabTests.CastingPerf.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'PerfLabTests.CastingPerf*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-01c4a606-e56e-4f80-8132-e5301652663235fd9152dce4de19a/14da6fd9-324e-40fa-85f5-4c4401fcd9e2.zip?sv=2021-08-06&se=2023-12-20T00%3A39%3A18Z&sr=c&sp=rl&sig=e1VS67n%2FJyUqEZzPM1Ty14urz0MFmmVDrH1sdG8Vh5I%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-3de10032-20fb-4059-b9ce-bae299fbc721d3184b1387044cd97/eb84a456-01cc-4482-af4e-dfb8f5a9a711.zip?sv=2021-08-06&se=2023-12-20T14%3A25%3A20Z&sr=c&sp=rl&sig=MgZn2XSLNomLyrB2sdf609PhCiqrhleyJNJ433r1ZNI%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [83f116627e2548c7a55b3701bd5448570b84a784](https://github.com/dotnet/runtime/commit/83f116627e2548c7a55b3701bd5448570b84a784)
Compare | [5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb](https://github.com/dotnet/runtime/commit/5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Diff | [Diff](https://github.com/dotnet/runtime/compare/83f116627e2548c7a55b3701bd5448570b84a784...5fa2080e2fff7bb31a4235250ce2f7a4bb1b64cb)
Configs | CompilationMode:wasm, RunKind:micro

### Regressions in PerfLabTests.EnumPerf

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[EnumCompareTo - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04_CompilationMode=wasm_RunKind=micro/PerfLabTests.EnumPerf.EnumCompareTo(color%3a%20Red).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/runtime/perflab/EnumPerf.cs#L26-#L28>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TQBB8R+I/3JttcBs3iaIQyYg0BFpoqmD8hhC62Jv40H1Ye3dNXCF+O3dOlDaphPxi3Y1nZserXS+AaosgQBr96g/ZVoBAri3jZQa1ImlKglIZCaaHVhomIDhlXSOVRdXyENa6VwEtdU9QJs+IUywqZqAwrhphkoTBbjQMYhJQFO4QHdk5aHNPBXjPD8EScH1HVx7Ul3NphQfaw0yJmiLkKiwUVzghGZTRU9HMypmSa7axSA1TUv8IvILx9rZQJQQ/SfqXBFuqRfD6fzoHfWWyPPAFK1A9EzANojZN+EI4VSbqQLtV+o4/iLZJXfhf9FxumIQuXG/chbdQUnWM66m30gDWCO7ZRbLcqLypOwVeVo1mBeVLVEJ5pKvwplkhKz9ztaKcPbZYF1nWz7pWmO9qQLcAsp3O03mdKbccgLmqD6fT2c+d7LuhoibvSUkN+D0K+0l/cJGML/rjPBlP+leTwdVlMhoO343Gb5NkkiS+hLZCUGSPQChufgm6C1tDnyAmbyKyas4qxMf9if0of7NgwfnUqH673XtBzkBbblJ0qcvw2Zfs8ekDIN04p0EUk9bKG6efkIEseXNEfLPai4+M7h0g8d9YVBQN2TJTkVC75oFOj5qY7NzeWiHT80zNHtfpPoQjGmY4pMFH1zr3x2gOVy8hodSRx3TNmUnpDnT0D7/qtS/TBAAA>)</li></ul> | 315.78 ns | 352.38 ns | 1.12 | 0.13 | False | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_28_2023/refs/heads/main_x64_ubuntu%2022.04_CompilationMode%3Dwasm_RunKind%3Dmicro_Regression/PerfLabTests.EnumPerf.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'PerfLabTests.EnumPerf*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-01c4a606-e56e-4f80-8132-e5301652663235fd9152dce4de19a/14da6fd9-324e-40fa-85f5-4c4401fcd9e2.zip?sv=2021-08-06&se=2023-12-20T00%3A39%3A18Z&sr=c&sp=rl&sig=e1VS67n%2FJyUqEZzPM1Ty14urz0MFmmVDrH1sdG8Vh5I%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-3de10032-20fb-4059-b9ce-bae299fbc721d3184b1387044cd97/eb84a456-01cc-4482-af4e-dfb8f5a9a711.zip?sv=2021-08-06&se=2023-12-20T14%3A25%3A20Z&sr=c&sp=rl&sig=MgZn2XSLNomLyrB2sdf609PhCiqrhleyJNJ433r1ZNI%3D>)
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by vargaz**
* Precompute the data used by build_args_from_sig ().
* Avoid allocations.

Fixes https://github.com/dotnet/perf-autofiling-issues/issues/25113.

### CODE REVIEW

File: src/mono/mono/mini/interp/interp.c [hunk 1]
```diff
@@ -1442,115 +1464,136 @@ build_args_from_sig (MonoMethodSignature *sig, InterpFrame *frame)
...
+			g_error ("build_args_from_sig: ret type not implemented yet: 0x%x\n", sig->ret->type);
+	}
+
+	return info;
+}
+
+static void
+build_args_from_sig (InterpMethodArguments *margs, MonoMethodSignature *sig, BuildArgsFromSigInfo *info, InterpFrame *frame)
+{
+#ifdef TARGET_ARM
```
Comment (BrzVlad) [inline src/mono/mono/mini/interp/interp.c:1490]: Not sure how this is the first time I'm noticing arm handling here. The `build_args_from_sig` path is wasm only. All other platforms have pinvoke tramp. Some of the code from this PR could be removed/simplified.

File: src/mono/mono/mini/interp/interp.c [hunk 2]
```diff
@@ -1692,8 +1731,23 @@ ves_pinvoke_method (
 	mono_arch_set_native_call_context_args (&ccontext, &frame, sig, call_info);
 	args = &ccontext;
 #else
-	InterpMethodArguments *margs = build_args_from_sig (sig, &frame);
-	args = margs;
+
+#ifdef HOST_WASM
+	BuildArgsFromSigInfo *call_info = cache_data->call_info;
+#else
```
Comment (BrzVlad) [inline src/mono/mono/mini/interp/interp.c:1737]: Isn't this path dead ? Is it supposed to run on WASI ? Shouldn't wasi always be wasm ?

Comment (vargaz) [reply src/mono/mono/mini/interp/interp.c:1737]: Its initialized here:
```
		cache_data->entry_func = (MonoPIFunc)mono_wasm_get_interp_to_native_trampoline (sig);
		cache_data->call_info = get_build_args_from_sig_info (get_default_mem_manager (), sig);
```

On wasm, we need to cache both the entry_func and the call_info, this is why its using a different code path.

Comment (BrzVlad) [reply src/mono/mono/mini/interp/interp.c:1737]: My point is that this code is in the `!MONO_ARCH_HAVE_INTERP_PINVOKE_TRAMP` path.  This path is wasm only. So my question is why do we guard for `HOST_WASM` again and we also have an else path for it. If anything, I would expect the else path to be a pragma error or something like that.

Comment (BrzVlad) [reply src/mono/mono/mini/interp/interp.c:1737]: So then the code in the `!HOST_WASM` path here is dead.

**Review by BrzVlad — APPROVED** [review]

**Comment by kg** [comment]
Thanks for doing this, it was on my mental todo list

File: src/mono/mono/mini/interp/interp.c [hunk 3]
```diff
@@ -1535,22 +1463,122 @@ build_args_from_sig (MonoMethodSignature *sig, InterpFrame *frame)
...
+#ifdef TARGET_WASM
+	margs->sig = sig;
+#endif
+
+	margs->ilen = info->ilen;
+	margs->flen = info->flen;
+
+	if (margs->ilen > 0) {
+		if (margs->ilen <= 8)
+			margs->iargs = margs->iargs_buf;
```
Comment (kg) [inline src/mono/mono/mini/interp/interp.c:1494]: Is this thread safe? It doesn't look like it

Comment (kg) [reply src/mono/mono/mini/interp/interp.c:1494]: nvm, read that as info->iargs_buf

**Review by kg — APPROVED** [review]
