### PR TITLE
JIT: Ensure EH clauses with same try region are reported contiguously to the VM

### LINKED ISSUE #101772: Change in exception handling in 9.0
### Description

If you have a try-catch-catch, I don't believe C# allows the second catch to handle exceptions thrown by the first catch.  At least, that's the behavior I'm seeing in 8.0.  In 9.0, there seem to be cases where the second catch _can_ handle them.

### Reproduction Steps

```csharp
try
{
    Console.WriteLine("Try");
    throw new NotSupportedException();
}
catch (NotSupportedException)
{
    Console.WriteLine("NotSupportedException");
    throw new Exception("Repro failed");
}
catch (InvalidOperationException)
{
    Console.WriteLine("InvalidOperationException");
    try
    {
        System.Diagnostics.Debug.Fail("How did we get here?");
    }
    finally // Required for repro
    {
        System.Diagnostics.Debug.Fail("How did we get here?");
    }
}
catch (Exception)
{
    Console.WriteLine("Exception");
    Console.WriteLine("Repro succeeded");
}
finally
{
    Console.WriteLine("Finally");
}
```

### Expected behavior

8.0 printed
```
Try
NotSupportedException
Unhandled exception. System.Exception: Repro failed [SNIP]
Finally
```

### Actual behavior

9.0.100-preview.5.24229.2 prints
```
Try
NotSupportedException
Exception
Repro succeeded
Finally
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

9.0.100-preview.5.24229.2 (in aspnetcore repo)
Win11 22631.3447 on x64 (haven't tried others)

### Other information

The nested try finally in the unreachable catch block seems essential to the repro.

### PR DESCRIPTION
**Pull request by amanasifkhalid**
The `CORINFO_EH_CLAUSE_SAMETRY` flag indicates to the VM that a given EH clause maps to the same try region as the previous EH clause. However, the JIT's internal invariants may result in an EH table ordering such that clauses mapped to the same try region aren't contiguous, thus breaking the functionality of this flag. To address this without changing the JIT's EH invariants, ensure the JIT reports clauses with the same try region contiguously to the VM, and sets `CORINFO_EH_CLAUSE_SAMETRY` accordingly.

Fixes #101772.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
cc @janvorli @jkotas for visibility, @AndyAyersMS PTAL. Thanks!

This change has a bunch of zero-size [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732498&view=ms.vss-build-web.run-extensions-tab) from changes in EH clause ordering -- looks like the JIT's internal ordering was breaking up clauses with the same try region with some frequency. TP cost is pretty minimal.

Are there any outerloop pipelines worth running? From my block layout work, I don't recall `JitStress` being all that useful for stressing EH semantics...

File: src/coreclr/jit/codegencommon.cpp [hunk 1]
```diff
@@ -2404,8 +2406,16 @@ void CodeGen::genReportEH()
...
     compiler->eeSetEHcount(EHCount);
 
-    XTnum = 0; // This is the index we pass to the VM
+    struct EHClauseInfo
+    {
+        CORINFO_EH_CLAUSE clause;
+        EHblkDsc*         HBtab;
+    };
+
+    EHClauseInfo* clauses = new EHClauseInfo[compiler->compHndBBtabCount];
```
Comment (jakobbotsch) [inline src/coreclr/jit/codegencommon.cpp:2415]: This is allocating memory on the global heap

```suggestion
    EHClauseInfo* clauses = new (compiler, CMK_Codegen) EHClauseInfo[compiler->compHndBBtabCount];
```

**Comment by amanasifkhalid** [comment]
The only failing outerloop test ([report](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732594&view=results)) is `JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests`, which isn't a new failure: https://github.com/dotnet/runtime/issues/104337.

File: src/coreclr/jit/codegencommon.cpp [hunk 2]
```diff
@@ -2427,7 +2437,43 @@ void CodeGen::genReportEH()
...
+        {
+            // We have two clauses mapped to the same try region.
+            // Make sure we report the clause with the smaller index first.
+            const auto leftIndex  = left.HBtab - this->compiler->compHndBBtab;
+            const auto rightIndex = right.HBtab - this->compiler->compHndBBtab;
+            return leftIndex < rightIndex;
+        }
+
+        return leftTryIndex < rightTryIndex;
+    });
```
Comment (AndyAyersMS) [inline src/coreclr/jit/codegencommon.cpp:2470]: We don't use any of the `CORINFO_EH_CLAUSE` data when sorting, so seems like it would be more efficient to just sort a table of `EHblkDsc*` and then report each clause like we did before?

File: src/coreclr/jit/codegencommon.cpp [hunk 3]
```diff
@@ -2427,7 +2437,43 @@ void CodeGen::genReportEH()
...
+                 [this](const EHClauseInfo& left, const EHClauseInfo& right) {
+        const unsigned short leftTryIndex  = left.HBtab->ebdTryBeg->bbTryIndex;
+        const unsigned short rightTryIndex = right.HBtab->ebdTryBeg->bbTryIndex;
+
+        if (leftTryIndex == rightTryIndex)
+        {
+            // We have two clauses mapped to the same try region.
+            // Make sure we report the clause with the smaller index first.
+            const auto leftIndex  = left.HBtab - this->compiler->compHndBBtab;
+            const auto rightIndex = right.HBtab - this->compiler->compHndBBtab;
```
Comment (AndyAyersMS) [inline src/coreclr/jit/codegencommon.cpp:2465]: I don't think we have used `auto` for anything but function types. Use `ptrdiff_t`?

File: src/coreclr/jit/codegencommon.cpp (hunk 2 above)
Comment (amanasifkhalid) [reply src/coreclr/jit/codegencommon.cpp:2470]: I initially tried doing this, and then iterating over the sorted table to build the clauses in the above table, but changing the order in which we call `Compiler::ehCodeOffset` hit JIT asserts -- I think `emitter::emitCodeOffset` has some hard dependency on us calling `ehCodeOffset` in the order of the JIT's EH table. I can look into cleaning this up in a follow-up if you'd like, though the TP cost of the current approach doesn't seem too bad.

Comment (AndyAyersMS) [reply src/coreclr/jit/codegencommon.cpp:2470]: Thats fine. EH is relatively rare and lots of EH clauses even more so.

I don't see why there'd be such an order dependence in the emitter, so it is worth digging into more deeply.

**Review by AndyAyersMS — APPROVED** [review]

**Comment by amanasifkhalid** [comment]
SPMI replay failure is #104570.
