### PR TITLE
Fix OperIsSimple assert in lower

### LINKED ISSUE #96612: Assertion failed 'OperIsSimple()' in pgo pipelines
### Error Blob

```json
{
  "ErrorMessage": "Assertion failed 'OperIsSimple()'",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

_No response_

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 1/8/2024 9:26:36 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/96612

@dotnet/jit-contrib It seems that in lower we have a worrisome pattern to handle nodes like this:

```c
// Returns:
//     A pointer to the next node to evaluate. On no operation, returns nullptr.
//
GenTree* LowerFoo(GenTree* tree)
{
    if (!someValidation)
        return nullptr;

    return newNode->gtNext;
}
```

and then caller assumes that `nullptr` means nothing was handled. Which is not true - it could be handled and it's just that `gtNext` is nullptr.

This is exactly what happens with https://github.com/dotnet/runtime/issues/96612
`TryLowerAndOrToCCMP` converts a binary op to `GT_SECC` and returns nullptr and then `ContainBinaryNode` fails because node is no longer a simple op.

The correct pattern should be
```c
bool TryLowerFoo(GenTree* node, GenTree** next)
{
    if (!someValidation)
        return false;

    *next = newNode->gtNext;
    return true;
}
```

I'll inspect more functions for this pattern separately.

### CODE REVIEW

File: src/coreclr/jit/lowerarmarch.cpp [hunk 1]
```diff
@@ -2433,11 +2444,12 @@ GenTree* Lowering::TryLowerAndOrToCCMP(GenTreeOp* tree)
     tree->SetOper(GT_SETCC);
     tree->AsCC()->gtCondition = cond2;
 
-    JITDUMP("Conversion was legal. Result:\n");
-    DISPTREERANGE(BlockRange(), tree);
-    JITDUMP("\n");
+    JITDUMP("Conversion was legal. Result:\n")
+    DISPTREERANGE(BlockRange(), tree)
+    JITDUMP("\n")
```
Comment (jakobbotsch) [inline src/coreclr/jit/lowerarmarch.cpp:2449]: Why remove the semicolons? It looks odd to have statements without semicolons, even if the macro expansion allows it.

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/lowerarmarch.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/lowerarmarch.cpp:2449]: ok will return it back, it's just that my Resharper++ highlights them as redundant which is annoying (will change its settings 🙂)

image
