### PR TITLE
JIT: Remove `GT_CAST` handling in `Lowering::IsValidConstForMovImm`

### LINKED ISSUE #106020: JIT: Assertion failed '(imm < maxVal) || ((imm & signBitsMask) == signBitsMask)' during 'Generate code'
```csharp
// Generated by Fuzzlyn v2.2 on 2024-08-05 19:14:52
// Run on Arm64 MacOS
// Seed: 16897731911671998240-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256
// Reduced from 67.3 KiB to 0.3 KiB in 00:00:23
// Hits JIT assert in Debug:
// Assertion failed '(imm < maxVal) || ((imm & signBitsMask) == signBitsMask)' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 16; hash 0xade6b36b; MinOpts)
// 
//     File: /Users/runner/work/1/s/src/coreclr/jit/emitarm64.cpp Line: 2676
// 
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static void Main()
    {
        int vr2 = 0;
        Vector128.Create<short>((short)((0 * vr2) + 2147483647));
    }
}
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #106020 ([comment](https://github.com/dotnet/runtime/issues/106020#issuecomment-2274006891)).

### CODE REVIEW

File: src/coreclr/jit/lowerarmarch.cpp [hunk 1]
```diff
@@ -1931,17 +1931,21 @@ bool Lowering::IsValidConstForMovImm(GenTreeHWIntrinsic* node)
     GenTree* op1    = node->Op(1);
     GenTree* castOp = nullptr;
 
-    // TODO-Casts: why don't we fold the casts? MinOpts?
+    // In MinOpts, casts won't be folded during importation
     if (varTypeIsIntegral(node->GetSimdBaseType()) && op1->OperIs(GT_CAST))
```
Comment (jakobbotsch) [inline src/coreclr/jit/lowerarmarch.cpp:1935]: Does removing this handling entirely have any significant diffs outside MinOpts?

Comment (amanasifkhalid) [reply src/coreclr/jit/lowerarmarch.cpp:1935]: I tried removing this, and (surprisingly?) I didn't get any diffs, so this code pattern doesn't seem common enough to even help MinOpts all that much. Maybe we should get rid of it altogether.

**Review by jakobbotsch — APPROVED** [review]

**Comment by amanasifkhalid** [comment]
[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769315&view=ms.vss-build-web.run-extensions-tab) in CI, either.
