### PR TITLE
[mono] Reenable C4244 MSVC warning and fix occurrences

### LINKED ISSUE #91249: Mono build disables required warning C4244 under MSVC
In cmakelists.txt, we have:

https://github.com/dotnet/runtime/blob/41878765a826b5bbf54c00fd9b934bae337de650/src/mono/CMakeLists.txt#L500-L511

And in zlib.cmake, we have:

https://github.com/dotnet/runtime/blob/41878765a826b5bbf54c00fd9b934bae337de650/src/native/external/zlib.cmake#L1-L5

The end result is that _all_ of the mono native libs - not just the zlib components - are being built with C4244 disabled, which is causing binskim violations in the official build.

The mono sources should re-enable C4244 _as error_ per SDL and binskim requirements.

See also https://github.com/dotnet/runtime/pull/91245.

### PR DESCRIPTION
**Pull request by akoeplinger**
Fixes https://github.com/dotnet/runtime/issues/91249

We originally fixed the warnings with https://github.com/dotnet/runtime/pull/69236 but due to `add_compile_options()` calls in zlib.cmake _all_ of the mono native libs - not just the zlib components - were being built with C4244 disabled and a few couple more leaked in.

This fixes the occurrences and reworks the .cmake files a bit to hopefully prevent this in the future.

### CODE REVIEW

File: src/mono/mono/mini/aot-runtime.c [hunk 1]
```diff
@@ -2275,7 +2275,7 @@ load_aot_module (MonoAssemblyLoadContext *alc, MonoAssembly *assembly, gpointer
 
 		addr = amodule->mem_begin;
 		g_assert (addr);
-		len = amodule->mem_end - amodule->mem_begin;
+		len = (int)(amodule->mem_end - amodule->mem_begin);
```
Comment (akoeplinger) [inline src/mono/mono/mini/aot-runtime.c:2278]: this one is a bit weird to me in general, I'm not sure why we need `addr` and `len` since for calculating `page_end` we're adding them back together so couldn't we just use `amodule->mem_end` instead?

Comment (akoeplinger) [reply src/mono/mono/mini/aot-runtime.c]: removed the intermediate variables

File: src/mono/mono/mini/graph.c [hunk 2]
```diff
@@ -228,6 +227,7 @@ mono_draw_graph (MonoCompile *cfg, MonoGraphOptions draw_options)
 #ifdef HAVE_SYSTEM
 	//com = g_strdup_printf ("dot %s -Tpng -o %s.png; eog %s.png", fn, fn, fn);
 	com = g_strdup_printf ("dot %s -Tps -o %s.ps;gv %s.ps", fn, fn, fn);
+	int _i G_GNUC_UNUSED;
```
Comment (fanyang-mono) [inline src/mono/mono/mini/graph.c:230]: Do you still need `G_GNUC_UNUSED` here?

File: src/mono/mono/mini/helpers.c [hunk 3]
```diff
@@ -255,6 +254,7 @@ MONO_RESTORE_WARNING
 #endif
 
 #ifdef HAVE_SYSTEM
+	int unused G_GNUC_UNUSED;
```
Comment (fanyang-mono) [inline src/mono/mono/mini/helpers.c:257]: Same question here.

File: src/mono/mono/mini/mini-llvm-cpp.cpp [hunk 4]
```diff
@@ -779,7 +779,7 @@ mono_llvm_register_overloaded_intrinsic (LLVMModuleRef module, IntrinsicId id, L
 unsigned int
 mono_llvm_get_prim_size_bits (LLVMTypeRef type)
 {
-	return unwrap (type)->getPrimitiveSizeInBits ();
+	return (unsigned int)(unwrap (type)->getPrimitiveSizeInBits ());
```
Comment (fanyang-mono) [inline src/mono/mono/mini/mini-llvm-cpp.cpp:782]: Why not using the macros here?

**Review by fanyang-mono — APPROVED** [review]
Overall, the change looks good to me.

File: src/mono/mono/mini/graph.c (hunk 2 above)
Comment (akoeplinger) [reply src/mono/mono/mini/graph.c:230]: Yes because otherwise we'd get a warning about the variable being assigned but never used.

File: src/mono/mono/mini/mini-llvm-cpp.cpp (hunk 4 above)
Comment (akoeplinger) [reply src/mono/mono/mini/mini-llvm-cpp.cpp:782]: Not intentional, will change, thanks!

File: src/mono/mono/mini/mini-llvm.c [hunk 5]
```diff
@@ -14387,7 +14387,7 @@ emit_dbg_loc (EmitContext *ctx, LLVMBuilderRef builder, const unsigned char *cil
 		MonoDebugSourceLocation *loc;
 		LLVMValueRef loc_md;
 
-		loc = mono_debug_method_lookup_location (ctx->minfo, cil_code - cfg->header->code);
+		loc = mono_debug_method_lookup_location (ctx->minfo, GINT64_TO_INT (cil_code - cfg->header->code));
```
Comment (lateralusX) [inline src/mono/mono/mini/mini-llvm.c:14390]: GPTRDIFF_TO_INT

File: src/mono/mono/mini/mini-x86.c [hunk 6]
```diff
@@ -3388,7 +3388,7 @@ mono_arch_output_basic_block (MonoCompile *cfg, MonoBasicBlock *bb)
 			break;
 
 		case OP_LABEL:
-			ins->inst_c0 = code - cfg->native_code;
+			ins->inst_c0 = GINT64_TO_TMREG (code - cfg->native_code);
```
Comment (lateralusX) [inline src/mono/mono/mini/mini-x86.c:3391]: GPTRDIFF_TO_TMREG

File: src/mono/mono/sgen/sgen-scan-object.h [hunk 7]
```diff
@@ -14,7 +14,7 @@
  * "start" will point to the start of the next object, if the scanned
  * object contained references.  If not, the value of "start" should
  * be considered undefined after executing this code.  The object's
- * GC descriptor must be in the variable "mword desc".
+ * GC descriptor must be in the variable "SgenDescriptor desc".
```
Comment (lateralusX) [inline src/mono/mono/sgen/sgen-scan-object.h:17]: These are different type depending on host/target, mword is host machine word while SgenDescriptor is target machine word, have you validated that calls only uses SgenDescriptor and we don't end up casting mword to SgenDescriptor or SgenDescriptor to mword since that can lead to data loss depending on host/target combinations.

File: src/mono/mono/metadata/sgen-mono.c [hunk 8]
```diff
@@ -1297,7 +1297,7 @@ two_args_report_root (void *address, MonoObject *obj, void *gc_data)
 }
 
 static void
-precisely_report_roots_from (GCRootReport *report, void** start_root, void** end_root, mword desc)
+precisely_report_roots_from (GCRootReport *report, void** start_root, void** end_root, SgenDescriptor desc)
```
Comment (lateralusX) [inline src/mono/mono/metadata/sgen-mono.c:1300]: Same comment as above, only called with SgenDescriptor, no casting happening on callsite?

**Review by lateralusX — COMMENTED** [review]
Overall looks good, great work. Mainly a couple of additional places to use different conversion macros or opportunity to add a new more precise conversion macro.

The only thing to look out for is the mword SGenDescriptor related changes, mword is based on host size while SGenDescriptor is based on target size, so changing the type we will need to make sure that it doesn't introduce changed behavior or potentially loss of precision in case you have different host/target pointer sizes.

File: src/mono/mono/metadata/sgen-mono.c [hunk 9]
```diff
@@ -98,7 +98,7 @@ ptr_on_stack (void *ptr)
 	} while (0)
 
 static void
-scan_object_for_binary_protocol_copy_wbarrier (gpointer dest, char *start, mword desc)
+scan_object_for_binary_protocol_copy_wbarrier (gpointer dest, char *start, SgenDescriptor desc)
```
[the remark this answers is not in the document]
Comment (akoeplinger) [reply src/mono/mono/metadata/sgen-mono.c:101]: Yes.

File: src/mono/mono/metadata/sgen-client-mono.h [hunk 10]
```diff
@@ -90,7 +90,7 @@ enum {
 };
 
 static inline mword
-sgen_mono_array_size (GCVTable vtable, MonoArray *array, mword *bounds_size, mword descr)
+sgen_mono_array_size (GCVTable vtable, MonoArray *array, mword *bounds_size, SgenDescriptor descr)
```
[the remark this answers is not in the document]
Comment (akoeplinger) [reply src/mono/mono/metadata/sgen-client-mono.h:93]: It is only called with SgenDescriptor.

File: src/mono/mono/sgen/sgen-scan-object.h (hunk 7 above)
Comment (akoeplinger) [reply src/mono/mono/sgen/sgen-scan-object.h:17]: Yep I checked all the callsites and they are all called with SgenDescriptor type without casting.

**Review by lateralusX — APPROVED** [review]
