### PR TITLE
JIT: Handle `GT_JTRUE` nodes during post-layout condition reversal

### LINKED ISSUE #103252: JIT: Assertion failed 'cond == test' during 'Optimize post-layout'
```csharp
// Generated by Fuzzlyn v1.6 on 2024-06-09 16:24:09
// Run on X86 Windows
// Seed: 1355796564435856377
// Reduced from 42.7 KiB to 1.5 KiB in 00:01:57
// Hits JIT assert in Release:
// Assertion failed 'cond == test' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Optimize post-layout' (IL size 219; hash 0xade6b36b; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\optimizer.cpp Line: 2483
// 
using System.Runtime.CompilerServices;

public struct S0
{
    public int F0;
}

public class C0
{
    public long F0;
    public S0 F3;
    public uint F4;
    public short F7;
    public sbyte F9;
}

public struct S1
{
    public ulong F0;
    public short F3;
}

public struct S2
{
    public S1 F0;
}

public struct S3
{
    public S2 F2;
    public byte F4;
}

public class C1
{
    public int F1;
    public uint F3;
    public C1(int f1, uint f3)
    {
        F1 = f1;
        F3 = f3;
    }
}

public struct S4
{
    public C0 F1;
}

public struct S5
{
    public S1 F1;
    public C0 F2;
    public S4 F3;
}

public class Program
{
    public static IRuntime s_rt;
    public static void Main()
    {
        S5 vr9 = default(S5);
        S3 vr10 = default(S3);
        if ((vr9.F2.F0 >= (vr9.F3.F1.F3.F0 / vr9.F2.F0)) == !(vr9.F3.F1.F4 >= 0))
        {
            if (vr9.F2.F9 >= vr9.F3.F1.F9)
            {
                vr9.F2.F7 = vr9.F1.F3;
            }
            else
            {
                s_rt.WriteLine(vr10.F2.F0.F0);
                s_rt.WriteLine(vr10.F4);
                var vr11 = new C1(0, 0);
                var vr12 = new C1(0, 0);
                var vr13 = new C1(0, 0);
            }
        }
    }
}

public interface IRuntime
{
    void WriteLine<T>(T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(T value) => System.Console.WriteLine(value);
}
```

cc @amanasifkhalid

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #103252. In the (rare?) case where a `BBJ_COND` block still ends with a `GT_JTRUE` node post-layout and lowering, and reversing the block's condition would eliminate a jump, find the conditional IR preceding the `GT_JTRUE` node, and reverse its condition instead of trying to wrap the `GT_JTRUE` node in a `GT_NOT`, and triggering asserts.

### CODE REVIEW

File: src/coreclr/jit/optimizer.cpp [hunk 1]
```diff
@@ -2477,8 +2477,20 @@ PhaseStatus Compiler::optOptimizePostLayout()
...
+                // search for the correct node to flip the condition on
+                do
+                {
+                    test = test->gtPrev;
+                    assert(test != nullptr);
+                } while (!test->OperIsCompare() && !test->OperIs(GT_SETCC));
+            }
+
             GenTree* const cond = gtReverseCond(test);
             assert(cond == test); // Ensure `gtReverseCond` did not create a new node
```
Comment (jakobbotsch) [inline src/coreclr/jit/optimizer.cpp:2495]: I don't think this is quite right. There is no invariant on the JTRUE node operand after lowering, so we do need to handle the `GT_NOT` inserted case (or just skip this optimization for these rare cases).

I think the code should rather be something like:
```csharp
if (test->OperIs(GT_JTRUE))
{
  GenTree* const cond = gtReverseCond(test->gtGetOp1());
  if (cond != test->gtGetOp1())
  {
    LIR::AsRange(block).InsertAfter(test->gtGetOp1(), cond);
    test->AsUnOp()->gtOp1 = cond;
  }
}
else
{
  GenTree* const cond = gtReverseCond(test);
  assert(cond == test);
}
```

Skipping the transformation when the terminator node is not JCC, JCMP or JTEST would be fine to me as well.

It might be nice to add a stress mode that `LowerJTrue` uses to leave more JTRUEs in place (`TryLowerConditionToFlagsNode` is almost able to convert all `JTRUE`s today, as you pointed out).

Comment (amanasifkhalid) [reply src/coreclr/jit/optimizer.cpp]: I see, thank you for the suggestion! Fixed.

> It might be nice to add a stress mode that LowerJTrue uses to leave more JTRUEs in place (TryLowerConditionToFlagsNode is almost able to convert all JTRUEs today, as you pointed out).

I'll add a stress mode in a follow-up PR. The [lack of diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=704441&view=ms.vss-build-web.run-extensions-tab) seems to further justify exercising these cases.

**Review by jakobbotsch — APPROVED** [review]

**Comment by amanasifkhalid** [comment]
Failure is unrelated timeout. [No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=704659&view=ms.vss-build-web.run-extensions-tab)
