### PR TITLE
Make sure to remove operand of TernaryLogic node

### LINKED ISSUE #116568: JIT: Assertion failed 'false && "found use of a node that is not in the LIR sequence"
Found by llm-fuzz based on JIT\Regression\JitBlue\Runtime_114572
```
Assert failure(PID 7200 [0x00001c20], Thread: 19780 [0x4d44]): Assertion failed 'false && "found use of a node that is not in the LIR sequence"' in 'Runtime_114572:Main()' during 'Lowering nodeinfo' (IL size 138; hash 0x86f53552; FullOpts)

    File: C:\repos\runtime1\src\coreclr\jit\lir.cpp:1687
    Image: c:\repos\runtime1\artifacts\tests\coreclr\windows.x64.Checked\tests\core_root\corerun.exe
```
Compile and run with TieredCompilation=0 on a box with AVX-512 support.
```csharp

using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Runtime_114572
{
    public static Vector256<ushort> s_2;
    public static ushort s_4;
    public static byte s_ub = 1;
    public static ushort s_us = 1;
    private struct LocalStruct
    {
        public int Value;
    }

    private static void CalculateChecksum(int initialChecksum)
    {
        // Simple checksum calculation
        int checksum = initialChecksum;
        for (int i = 0; i < 5; i++)
        {
            checksum += i * (i + 1);
            Console.WriteLine($"Checksum: {checksum}");
        }
        Console.WriteLine($"Final Checksum: {checksum}");
    }

    public static void Main()
    {
        CalculateChecksum(0);

        if (Avx512F.VL.IsSupported)
        {
            var vr11 = Vector256.Create<ushort>(0);
            var vr12 = Vector256.Create<ushort>(1);
            var vr13 = (ushort)0;
            var vr14 = Vector256.CreateScalar(vr13);
            var vr15 = (ushort)1;
            var vr16 = Vector256.CreateScalar(vr15);
            var vr17 = Vector256.Create<ushort>(s_4);
            var vr18 = Avx2.Max(vr16, vr17);

            for (int i = 0; i < 3; i++)
            {
                s_2 = Avx512F.VL.TernaryLogic(vr11, vr12, Avx512BW.VL.CompareGreaterThanOrEqual(vr14, vr18), 216);
                Console.WriteLine(s_2);

                if (i == 1)
                {
                    Console.WriteLine("Redundant branch: i == 1");
                }

                CalculateChecksum(123);
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by kunalspathak**
Fixes: https://github.com/dotnet/runtime/issues/116568

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

File: src/coreclr/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -3646,7 +3648,18 @@ GenTree* Lowering::LowerHWIntrinsicTernaryLogic(GenTreeHWIntrinsic* node)
...
+
+                    LIR::Use use;
+                    if (BlockRange().TryGetUse(condition, &use))
+                    {
+                        use.ReplaceWith(tmp);
+                        BlockRange().Remove(condition);
+                    }
+                    else
+                    {
+                        tmp->SetUnusedValue();
```
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp]: It's being set as unused and persisted in case of side effects. This isn't intended to remove it.

**Review by tannergooding — APPROVED** [review]

File: src/coreclr/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -3646,7 +3648,18 @@ GenTree* Lowering::LowerHWIntrinsicTernaryLogic(GenTreeHWIntrinsic* node)
                 if (condition->OperIsConvertMaskToVector())
                 {
                     GenTree* tmp = condition->AsHWIntrinsic()->Op(1);
-                    BlockRange().Remove(condition);
+
+                    LIR::Use use;
+                    if (BlockRange().TryGetUse(condition, &use))
+                    {
+                        use.ReplaceWith(tmp);
+                        BlockRange().Remove(condition);
```
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp:3651]: We're not removing `condition` in both paths because it should already be marked as "unused" and that should handle things, correct?

File: src/coreclr/jit/lowerxarch.cpp (hunk 1 above)
Comment (tannergooding) [inline src/coreclr/jit/lowerxarch.cpp]: Is this going to conflict with the `node->ResetHWIntrinsicId` below?

Should it rather be conditioned on the `if (!condition->OperIsHWIntrinsic())` which causes it to break?

Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp]: I think it is actually. I'm pretty sure the issue here is we want this instead...
```csharp
if (tmp->OperIsHWIntrinsic())
{
    BlockRange().Remove(condition);
    condition = tmp;
}
```

We should always find a user for `condition`, because it's always going to be `op1`, `op2`, or `op3` of `node`.

So by replacing the `use` in the case `tmp` isn't a HWIntrinsic, we're going to end up with `TernaryLogic(mask)` which will result in bad codegen.

We instead only want to remove `condition` in the scenario we know that `tmp` will be used in the `ResetHWIntrinsic` call, so it needs to be conditioned as per the above.

-------------------

This all stems from us needing to know how many bits are in the mask so that the `BlendVariable` is configured with the right type so the behavior stays the same.

**Review by tannergooding — CHANGES_REQUESTED** [review]
Believe a tweak is required after thinking it through some more.

File: src/coreclr/jit/lowerxarch.cpp (hunk 1 above)
Comment (kunalspathak) [reply src/coreclr/jit/lowerxarch.cpp]: We are operating on `t92` and the `condition` node is `t85`. In `main` today, we remove it, but then leave the `t235` node untouched leading to the failure.

```
LowerHWIntrinsicTernaryLogic: (before)
N001 (  3,  2) [000083] -----------                   t83 =    LCL_VAR   simd32<System.Runtime.Intrinsics.Vector256`1> V02 loc2         u:2 $100
N002 (  3,  2) [000084] -----------                   t84 =    LCL_VAR   simd32<System.Runtime.Intrinsics.Vector256`1> V01 loc1         u:2 $101
N003 (  3,  2) [000087] -----------                   t87 =    LCL_VAR   simd32<System.Runtime.Intrinsics.Vector256`1> V00 loc0         u:2 $100
N004 (  3,  2) [000088] -----------                   t88 =    LCL_VAR   simd32<System.Runtime.Intrinsics.Vector256`1> V04 loc4         u:2 <l:$340, c:$341>
                                                            ┌──▌  t87    simd32 
                                                            ├──▌  t88    simd32 
N005 (  7,  5) [000086] -----------                   t86 = ▌  HWINTRINSIC mask   32 ushort CompareGreaterThanOrEqualMask <l:$380, c:$381>
                                                            ┌──▌  t86    mask   
N006 ( 11,  8) [000234] DA---------                         ▌  STORE_LCL_VAR mask   V11 cse4         d:1 $VN.Void
N007 (  3,  2) [000235] -----------                  t235 =    LCL_VAR   mask   V11 cse4         u:1 <l:$380, c:$381>
                                                            ┌──▌  t235   mask   
N009 ( 15, 11) [000085] -A---------                   t85 = ▌  HWINTRINSIC simd32 32 ushort ConvertMaskToVector $84
N010 (  1,  4) [000089] -------N---                   t89 =    CNS_INT   int    216 $47
                                                            ┌──▌  t83    simd32 
                                                            ├──▌  t84    simd32 
                                                            ├──▌  t85    simd32 
                                                            ├──▌  t89    int    
N011 ( 23, 20) [000082] -A---------                   t82 = ▌  HWINTRINSIC simd32 32 uint TernaryLogic $85
```

With my change, here is what we do after updating. Is that not accurate? 

````
LowerHWIntrinsicTernaryLogic: (after)
N001 (  3,  2) [000083] -----------                   t83 =    LCL_VAR   simd32<System.Runtime.Intrinsics.Vector256`1> V02 loc2         u:2 $100
N002 (  3,  2) [000084] -----------                   t84 =    LCL_VAR   simd32<System.Runtime.Intrinsics.Vector256`1> V01 loc1         u:2 $101
N003 (  3,  2) [000087] -----------                   t87 =    LCL_VAR   simd32<System.Runtime.Intrinsics.Vector256`1> V00 loc0         u:2 $100
N004 (  3,  2) [000088] -----------                   t88 =    LCL_VAR   simd32<System.Runtime.Intrinsics.Vector256`1> V04 loc4         u:2 <l:$340, c:$341>
                                                            ┌──▌  t87    simd32 
                                                            ├──▌  t88    simd32 
N005 (  7,  5) [000086] -----------                   t86 = ▌  HWINTRINSIC mask   32 ushort CompareGreaterThanOrEqualMask <l:$380, c:$381>
                                                            ┌──▌  t86    mask   
N006 ( 11,  8) [000234] DA---------                         ▌  STORE_LCL_VAR mask   V11 cse4         d:1 $VN.Void
N007 (  3,  2) [000235] -----------                  t235 =    LCL_VAR   mask   V11 cse4         u:1 <l:$380, c:$381>
N010 (  1,  4) [000089] -------N---                   t89 =    CNS_INT   int    216 $47
                                                            ┌──▌  t83    simd32 
                                                            ├──▌  t84    simd32 
                                                            ├──▌  t235   mask   
                                                            ├──▌  t89    int    
N011 ( 23, 20) [000082] -A---------                   t82 = ▌  HWINTRINSIC simd32 32 uint TernaryLogic $85
```

If we add the condition of `tmp->OperIsHWIntrinsic()`, `condition` stays `ConvertMaskToVector()` and we hit assert `                assert(varTypeIsMask(condition));` few lines below.

Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp]: > With my change, here is what we do after updating. Is that not accurate?

No, because you can see that `TernaryLogic` is taking `t235` directly. This will lead to incorrect codegen because `TernaryLogic` expects a `simd32` here:
```
                                                            ┌──▌  t83    simd32 
                                                            ├──▌  t84    simd32 
                                                            ├──▌  t235   mask   
                                                            ├──▌  t89    int    
N011 ( 23, 20) [000082] -A---------                   t82 = ▌  HWINTRINSIC simd32 32 uint TernaryLogic $85
```

We rather shouldn't be removing `condition` (`t85`) at all, because `t235` is a `LCL_VAR` rather than a `HWINTRINSIC` node, and we don't currently have a way of knowing how many mask bits are in that `LCL_VAR` node.

Comment (tannergooding) [reply src/coreclr/jit/lowerxarch.cpp]: So, by instead changing it to the following we keep things correct and avoid the issue altogether:
```csharp
if (tmp->OperIsHWIntrinsic())
{
    BlockRange().Remove(condition);
    condition = tmp;
}
else
{
    // We can't change to a BlendVariable intrinsic, so bail out
    break;
}
```

**Review by tannergooding — APPROVED** [review]
