### PR TITLE
Fix trim analyzer warning for inferred type arguments

### LINKED ISSUE #86032: Trim Analyzer doesn't handle annotations on inferred generic arguments
```C#
public class TestType
{
    [RequiresUnreferencedCode("Dangerous")]
    public void Dangerous() {}
}

public static void InvokeDangerous<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods)] T>(T instance)
{
    typeof(T).GetMethod("Dangerous").Invoke(instance, Array.Empty<object>());
}

// IL2026 - Dangerous
InvokeDangerous<TestType>(new TestType());

// No warning
InvokeDangerous(new TestType());
```

When the generic argument is inferred, the analyzer doesn't react to it in any way and doesn't produce any diagnostics. See the above sample, calling a generic method with the argument explicitly specified produces diagnostics, but when it's inferred no diagnostics are produced.

### PR DESCRIPTION
**Pull request by sbomer**
Fixes https://github.com/dotnet/runtime/issues/86032.

This replaces the syntax-based logic with:
- ISymbol-based logic that looks at generic instantiations in parameter types, return types, and base/interface types
- IOperation-based logic that looks at invocations

The syntax-based logic used to also warn for the types of local variables, but `SymbolKind.Local` isn't supported for `RegisterSymbolAction`. Since this falls into the category of warnings that isn't strictly necessary (based on nativeaot logic which only warns on generic instantiations that can actually lead to code execution), I just left out local variables.

I'm slightly concerned that this could be missing some cases, but at least it works on our existing testcases.

There are two slight differences in warning locations, which I don't expect to cause issues for warning suppressions:
- For invocations, the warning location used to be the generic method name, without the argument list. Using the IOperation-based approach, we use the invocation's location that includes the argument list.
- For properties that use arrow syntax (`RequireMethods<TFields> Property => null`), the ISymbol-based approach warns on the underlying getter method, whose location seems to be the body of the accessor. We used to warn on the return type specifically, but I couldn't find a better way to get the location.

### CODE REVIEW

File: src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs [hunk 1]
```diff
@@ -76,17 +77,79 @@ public override void Initialize (AnalysisContext context)
...
 							context.ReportDiagnostic (diagnostic);
 					}
 				});
-				context.RegisterSyntaxNodeAction (context => {
-					ProcessGenericParameters (context);
-				}, SyntaxKind.GenericName);
+				// Examine generic instantiations in base types and interface list
+				context.RegisterSymbolAction (context => {
+					var type = (INamedTypeSymbol) context.Symbol;
+					if (type.BaseType is INamedTypeSymbol baseType) {
```
Comment (vitek-karas) [inline src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs:90]: What if I put RUC on the type - I don't remember if we decided to still warn on base/interface violation or not.

File: src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs [hunk 2]
```diff
@@ -76,17 +77,79 @@ public override void Initialize (AnalysisContext context)
...
+				// Examine generic instantiations in invocations, of generically instantiated methods,
+				// or methods on generically instantiated types.
+				context.RegisterOperationAction (context => {
+					if (context.ContainingSymbol.IsInRequiresUnreferencedCodeAttributeScope (out _))
+						return;
+
+					var invocation = (IInvocationOperation) context.Operation;
+					var methodSymbol = invocation.TargetMethod;
+					foreach (var diagnostic in ProcessGenericParameters (methodSymbol, invocation.Syntax.GetLocation()))
+						context.ReportDiagnostic (diagnostic);
```
Comment (vitek-karas) [inline src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs:134]: Just curious - is there a reason to use this pattern of returning a list of diagnostics and iterating over it just to call report. Why not call report inside the method? It seems there's lot of unnecessary code duplication this way.

File: src/tools/illink/test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs [hunk 3]
```diff
@@ -432,7 +434,7 @@ public void PublicFieldsMethodLocalVariable ()
 				TypeRequiresPublicFields<TOuter> t = null;
 			}
 
-			[ExpectedWarning ("IL2091", nameof (TypeRequiresPublicMethods<TOuter>), ProducedBy = Tool.Trimmer | Tool.Analyzer)] // NativeAOT_StorageSpaceType
+			[ExpectedWarning ("IL2091", nameof (TypeRequiresPublicMethods<TOuter>), ProducedBy = Tool.Trimmer)]
```
Comment (vitek-karas) [inline src/tools/illink/test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs:437]: Could you please add a comment?
Keep the `NativeAOT_StorageSpaceType` and add something about the analyzer (that it doesn't handle local variables or something).

File: src/tools/illink/test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresAccessedThrough.cs [hunk 4]
```diff
@@ -74,6 +74,57 @@ public static void Test ()
 			}
 		}
 
+		class AccessedThroughGenericParameterAnnotation
```
Comment (vitek-karas) [inline src/tools/illink/test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresAccessedThrough.cs:77]: Is there a reason you duplicated the test from `RequiresViaDataFlow`?

**Review by vitek-karas — APPROVED** [review]
In general looks good.

File: src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs (hunk 2 above)
Comment (vitek-karas) [reply src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs]: Now I remember hitting this myself - it's a shame the context doesn't implement an interface with the parts which are common across all contexts (like `ReportDiagnostics`).

**Review by vitek-karas — APPROVED** [review]

File: src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs (hunk 1 above)
Comment (vitek-karas) [reply src/tools/illink/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs]: Thanks.
