### PR TITLE
Lower GT_RETURN_SUSPEND blocks to BBJ_RETURN

### LINKED ISSUE #124162: Test failure: async/valuetask-source/valuetask-source/valuetask-source.cmd
**Failed in:** [runtime-coreclr jitstress-random 20260208.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1284762)

**Failed tests:**
```
coreclr osx x64 Checked jitstress_random_1 @ OSX.15.Amd64.Open
- async/valuetask-source/valuetask-source/valuetask-source.cmd

```

**Error message:**
```

Return code:      1
Raw output file:      /tmp/helix/working/BB2009EB/w/B51B09D9/uploads/valuetask-source/valuetask-source/output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/BB2009EB/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true valuetask-source.dll ''
Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Async2ValueTaskSource.AwaitValueTaskDefaultContext()
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/BB2009EB/w/B51B09D9/e/async/async/../valuetask-source/valuetask-source/valuetask-source.sh
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor70|0_71(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
When the AsyncSuspend intrinsic is used we can end up with GT_RETURN_SUSPEND present in a block that is not `BBJ_RETURN`. That would happen for instance because of return merging due to ELT profiler hooks.

Expand the lowering for this node to convert the block containing `GT_RETURN_SUSPEND` into a `BBJ_RETURN` block.

Fix #124162

### CODE REVIEW

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -6050,6 +6050,33 @@ void Lowering::LowerReturnSuspend(GenTree* node)
...
+        }
+
+        if (profileInconsistent)
+        {
+            JITDUMP("Flow removal of " FMT_BB " needs to be propagated. Data %s inconsistent.\n", block->bbNum,
+                    m_compiler->fgPgoConsistent ? "is now" : "was already");
+            m_compiler->fgPgoConsistent = false;
+        }
+
+        block->SetKindAndTargetEdge(BBJ_RETURN);
```
Comment (SingleAccretion) [inline src/coreclr/jit/lower.cpp:6075]: Can this run into the epilog count limit on x86?

Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp:6075]: With our very limited use of this intrinsic, no, I do not think so.
When the async transformation introduces these nodes it does return merging for x86 to account for the epilog limit.

**Review by AndyAyersMS — APPROVED** [review]
