### PR TITLE
JIT: have jit tail call stress avoid creating loops in some cases

### LINKED ISSUE #73090: Assertion failed 'compCanHavePatchpoints()' during 'Importation'
Lots of jitstress/libraries-jitstress tests are failing with this assert.
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1911013&view=results

cc @dotnet/jit-contrib @AndyAyersMS

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Don't create a loop via tail call stress if the method didn't already have a loop and could have patchpoints.

Fixes #73090.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Bug was different than I thought -- jit stress was creating modifiable `this`, but we didn't disqualify the method from OSR initially because the method didn't have a loop. But later tail call stress created a loop and subsequent importer calls asserted that the method could not have patchpoints.

Fix is to disallow tail call stress from creating the loop.

File: src/coreclr/jit/importer.cpp [hunk 1]
```diff
@@ -15665,7 +15665,13 @@ void Compiler::impImportBlockCode(BasicBlock* block)
...
                                                            returnFalseIfInvalid);
 
-                            if (passedConstraintCheck)
+                            // Avoid setting compHasBackwardsJump = true via tail call stress if the method cannot have
+                            // patchpoints.
+                            //
+                            const bool mayHavePatchpoints = opts.jitFlags->IsSet(JitFlags::JIT_FLAG_TIER0) &&
+                                                            (JitConfig.TC_OnStackReplacement() > 0) &&
+                                                            compCanHavePatchpoints();
+                            if (passedConstraintCheck && (mayHavePatchpoints || compHasBackwardJump))
```
Comment (jakobbotsch) [inline src/coreclr/jit/importer.cpp:15674]: The fix looks fine to me but I am a bit confused we are marking a backward jump in the first place. We should not do the loop optimization in tier-0 (and, since #41059, never under tailcall stress).

I can clean this up in the future if you don't want to do this as part of this PR.

**Review by jakobbotsch — APPROVED** [review]

File: src/coreclr/jit/importer.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/importer.cpp:15674]: But clearly you had to add special support for OSR due to the tailcall-to-loop optimization, so maybe I am missing something?

Comment (AndyAyersMS) [reply src/coreclr/jit/importer.cpp:15674]: No, you're on to something.

We are probably too aggressive in marking explicit tail calls as backwards branches in Tier0&mdash;and more importantly in this case, changing the value of `compHasBackwardJump`. We do this regardless of optimization flags. If we are never going to do the optimization, then we don't need to change `compHasBackwardJump` either.

Another possible fix would be that when tail call stress changes an implicit tail call to an explicit one, it should also set `compTailPrefixSeen`. But it's not as clean of a fix; we might already have added some patchpoints.

**Comment by AndyAyersMS** [comment]
I'll merge this to fix jitstress. Not sure if I'll have time today to do anything more.
