### PR TITLE
JIT: tolerate malformed IL when counting block successors

### LINKED ISSUE #83674: runtime-coreclr pgostress: failures with synthetic PGO
https://dev.azure.com/dnceng-public/public/_build/results?buildId=209551&view=ms.vss-test-web.build-test-results-tab&runId=3874694&resultId=120799&paneView=debug

Looks like some invalid IL is tripping up synthesis -- hits on many isa/os combos.

```
set DOTNET_TieredCompilation=1
set DOTNET_ReadyToRun=0
set DOTNET_TC_QuickJitForLoops=1
set DOTNET_JitSynthesizeCounts=1

    JIT\Directed\coverage\importer\Desktop\badendfinally_il_d\badendfinally_il_d.cmd [FAIL]
      
      Assert failure(PID 2032 [0x000007f0], Thread: 6640 [0x19f0]): Assertion failed 'block->hasHndIndex()' in '<Module>:f():int' during 'Profile incorporation' (IL size 4; hash 0x02ca6609; MinOpts)
      
          File: D:\a\_work\1\s\src\coreclr\jit\fgbasic.cpp Line: 647
          Image: C:\h\w\BB710A13\p\corerun.exe
      
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
If we run synthesis, we may now invoke `BasicBlock::NumSucc` before we've detected some cases of invalid IL, In particular an endfinally that is not within a finally (this gets detected during importation).

Tolerate this by reporting that an endfinally with no handler index has no successors.

Fixes #83674.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib (feel free to poach the review, it is a simple change)

File: src/coreclr/jit/block.cpp [hunk 1]
```diff
@@ -1151,6 +1151,13 @@ unsigned BasicBlock::NumSucc(Compiler* comp)
 
         case BBJ_EHFINALLYRET:
         {
+            // We may call this method before we realize we have invalid IL. Tolerate.
+            //
+            if (!hasHndIndex())
+            {
+                return 0;
+            }
+
```
Comment (jakobbotsch) [inline src/coreclr/jit/block.cpp:1160]: Would it be feasible to badcode on something like this earlier so we could have a nicer invariant on the data structures, making it simpler to work with this?

What about the other NumSucc variant?

Comment (AndyAyersMS) [reply src/coreclr/jit/block.cpp:1160]: > Would it be feasible to badcode on something like this earlier

I think in this case we can probably detect it earlier, when we're building the flow graph. I can look into this.

> What about the other NumSucc variant?

`BBJ_EHFINALLYRET` is handled differently in the "simple" variant, since it takes some work to figure out where control goes when it leaves a finally; we don't represent this flow via graph edges.

It turns out that synthesis runs so early that the algorithm the complex variant uses won't work anyways (the relevant blocks are created by our friend `impImportLeave` which as the name implies happens in the importer), but synthesis wants the complex variant's behavior for other BBJ kinds.

Comment (AndyAyersMS) [reply src/coreclr/jit/block.cpp:1160]: > > Would it be feasible to badcode on something like this earlier
> 
> I think in this case we can probably detect it earlier, when we're building the flow graph. I can look into this.

In the failing test case we have an `endfinally` in an inlinee. We could catch this earlier by calling `fgCheckBasicBlockControlFlow` before returning from `fgMakeBasicBlocks` for inlinees and for methods with no EH clauses. 

But that seems like overkill for this case; we know immediately when we see the IL opcode that things are bad, since the method has no EH clauses. But thanks to the issue I was trying to resolve in #83622 we pollute the inlinee with the root method's EH table, so the check for "has no EH clauses" is not quite as simple as checking `info.compXcptnsCount == 0`.

So (assuming I don't merge #83622 because of the TP impact) the check has to be a bit more nuanced: BADCODE if we see an `endfinally` (or `endfilter`) and we're the root method and `info.compXcptnsCount` is zero, or always, if we're an inlinee (thus further deepening the assumption that we won't inline methods with EH).

There is also the possibility that the block with the wayward `endfinally` is unreachable in which case we might be able to jit the method and just ignore the problematic IL.

So I'm tempted to go with this fix.

Comment (jakobbotsch) [reply src/coreclr/jit/block.cpp:1160]: Ok, sounds good. Thanks for looking.

**Review by jakobbotsch — APPROVED** [review]
