### PR TITLE
[wasm][coreclr] Fix reflection with large valuetypes

### LINKED ISSUE #122922: [wasm][coreclr] Failing VectorMgdMgdArray_r tests
Failures
```
14:51:51.828 Running test: JIT/Directed/VectorABI/VectorMgdMgdArray_r/VectorMgdMgdArray_r.dll
testReflectionReturn_HVA64_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v4): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_01(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
testReflectionReturn_HVA128_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) 
testReflectionReturn_HVA128_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_02(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
Test FAILED
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   0
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
   at Xunit.Assert.Equal[T](T expected, T actual)
   at Program.<>c__DisplayClass0_0.<<Main>$>g__TestExecutor64|65(TestFilter filter, StreamWriter tempLogSw, StreamWriter statsCsvSw)
14:51:52.200 Failed test: JIT/Directed/VectorABI/VectorMgdMgdArray_r/VectorMgdMgdArray_r.dll
14:51:52.233 Running test: JIT/Directed/VectorABI/VectorMgdMgdArray_ro/VectorMgdMgdArray_ro.dll
testReflectionReturn_HVA64_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v4): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_01(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
testReflectionReturn_HVA128_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) 
testReflectionReturn_HVA128_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_02(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
Test FAILED
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   0
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
   at Xunit.Assert.Equal[T](T expected, T actual)
   at Program.<>c__DisplayClass0_0.<<Main>$>g__TestExecutor65|66(TestFilter filter, StreamWriter tempLogSw, StreamWriter statsCsvSw)
14:51:52.575 Failed test: JIT/Directed/VectorABI/VectorMgdMgdArray_ro/VectorMgdMgdArray_ro.dll
14:51:52.610 Running test: JIT/Directed/VectorABI/VectorMgdMgdStatic_r/VectorMgdMgdStatic_r.dll
testReflectionReturn_HVA64_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v4): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_01(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
testReflectionReturn_HVA128_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) 
testReflectionReturn_HVA128_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_02(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
Test FAILED
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   0
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
   at Xunit.Assert.Equal[T](T expected, T actual)
   at Program.<>c__DisplayClass0_0.<<Main>$>g__TestExecutor66|67(TestFilter filter, StreamWriter tempLogSw, StreamWriter statsCsvSw)
14:51:52.959 Failed test: JIT/Directed/VectorABI/VectorMgdMgdStatic_r/VectorMgdMgdStatic_r.dll
14:51:52.993 Running test: JIT/Directed/VectorABI/VectorMgdMgdStatic_ro/VectorMgdMgdStatic_ro.dll
testReflectionReturn_HVA64_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v4): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_01(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
testReflectionReturn_HVA128_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) 
testReflectionReturn_HVA128_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_02(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
Test FAILED
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   0
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
   at Xunit.Assert.Equal[T](T expected, T actual)
   at Program.<>c__DisplayClass0_0.<<Main>$>g__TestExecutor67|68(TestFilter filter, StreamWriter tempLogSw, StreamWriter statsCsvSw)
14:51:53.333 Failed test: JIT/Directed/VectorABI/VectorMgdMgdStatic_ro/VectorMgdMgdStatic_ro.dll
14:51:53.367 Running test: JIT/Directed/VectorABI/VectorMgdMgd_r/VectorMgdMgd_r.dll
testReflectionReturn_HVA64_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_02(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_03(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_04(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v1): FAILED - Vector64<T> checkValues(index = 8, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v2): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v3): FAILED - Vector64<T> checkValues(index = 24, i = 0) (via reflection)
testReflectionReturn_HVA64_05(result.v4): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_01(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_02(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_03(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_04(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
test1Argument_HVA128_05(arg1.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
testReflectionReturn_HVA128_01(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) 
testReflectionReturn_HVA128_02(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_02(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_03(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_04(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v0): FAILED - Vector64<T> checkValues(index = 0, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v1): FAILED - Vector64<T> checkValues(index = 16, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v2): FAILED - Vector64<T> checkValues(index = 32, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v3): FAILED - Vector64<T> checkValues(index = 48, i = 0) (via reflection)
testReflectionReturn_HVA128_05(result.v4): FAILED - Vector64<T> checkValues(index = 64, i = 0) (via reflection)
Test FAILED
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   0
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
   at Xunit.Assert.Equal[T](T expected, T actual)
   at Program.<>c__DisplayClass0_0.<<Main>$>g__TestExecutor68|69(TestFilter filter, StreamWriter tempLogSw, StreamWriter statsCsvSw)
14:51:53.707 Failed test: JIT/Directed/VectorABI/VectorMgdMgd_r/VectorMgdMgd_r.dll
14:51:53.742 Running test: JIT/Directed/array-il/_Arrayscomplex3/_Arrayscomplex3.dll
Starting...
Rank is :7

Try to get count!
128Count is:128
Everything Worked!
14:51:53.753 Passed test: JIT/Directed/array-il/_Arrayscomplex3/_Arrayscomplex3.dll
14:51:53.760 Running test: JIT/Directed/aliasing_retbuf/aliasing_retbuf/aliasing_retbuf.cmd
14:51:53.766 Passed test: JIT/Directed/aliasing_retbuf/aliasing_retbuf/aliasing_retbuf.cmd
14:51:53.772 Running test: JIT/Directed/callconv/CdeclMemberFunction/CdeclMemberFunctionTest/CdeclMemberFunctionTest.cmd
14:51:53.778 Passed test: JIT/Directed/callconv/CdeclMemberFunction/CdeclMemberFunctionTest/CdeclMemberFunctionTest.cmd
14:51:53.786 Running test: JIT/Directed/callconv/PlatformDefaultMemberFunction/PlatformDefaultMemberFunctionTest/PlatformDefaultMemberFunctionTest.cmd
14:51:53.793 Passed test: JIT/Directed/callconv/PlatformDefaultMemberFunction/PlatformDefaultMemberFunctionTest/PlatformDefaultMemberFunctionTest.cmd
14:51:53.802 Running test: JIT/Directed/callconv/StdCallMemberFunction/StdCallMemberFunctionTest/StdCallMemberFunctionTest.cmd
14:51:53.808 Passed test: JIT/Directed/callconv/StdCallMemberFunction/StdCallMemberFunctionTest/StdCallMemberFunctionTest.cmd
14:51:53.816 Running test: JIT/Directed/callconv/ThisCall/EmptyThisCallTest/EmptyThisCallTest.cmd
14:51:53.821 Passed test: JIT/Directed/callconv/ThisCall/EmptyThisCallTest/EmptyThisCallTest.cmd
14:51:53.827 Running test: JIT/Directed/callconv/ThisCall/ThisCallTest/ThisCallTest.cmd
14:51:53.832 Passed test: JIT/Directed/callconv/ThisCall/ThisCallTest/ThisCallTest.cmd
14:51:53.838 Running test: JIT/Directed/Convert/out_of_range_fp_to_int_conversions/out_of_range_fp_to_int_conversions.cmd
14:51:53.844 Passed test: JIT/Directed/Convert/out_of_range_fp_to_int_conversions/out_of_range_fp_to_int_conversions.cmd
14:51:53.851 Running test: JIT/Directed/debugging/debuginfo/tester/tester.cmd
14:51:53.855 Passed test: JIT/Directed/debugging/debuginfo/tester/tester.cmd
14:51:53.861 Running test: JIT/Directed/debugging/poisoning/poison/poison.cmd
14:51:53.865 Passed test: JIT/Directed/debugging/poisoning/poison/poison.cmd
14:51:53.870 Running test: JIT/Directed/IL/Tailcall/ExplicitTailCallNoSO/ExplicitTailCallNoSO.cmd
14:51:53.875 Passed test: JIT/Directed/IL/Tailcall/ExplicitTailCallNoSO/ExplicitTailCallNoSO.cmd
14:51:53.882 Running test: JIT/Directed/IL/Tailcall/JitTailcall2/JitTailcall2.cmd
14:51:53.886 Passed test: JIT/Directed/IL/Tailcall/JitTailcall2/JitTailcall2.cmd
14:51:53.892 Running test: JIT/Directed/pinvoke/tail_pinvoke/tail_pinvoke.cmd
14:51:53.896 Passed test: JIT/Directed/pinvoke/tail_pinvoke/tail_pinvoke.cmd
14:51:53.901 Running test: JIT/Directed/PrimitiveABI/PrimitiveABI/PrimitiveABI.cmd
14:51:53.905 Passed test: JIT/Directed/PrimitiveABI/PrimitiveABI/PrimitiveABI.cmd
14:51:53.911 Running test: JIT/Directed/StructABI/EmptyStructs/EmptyStructs.cmd
14:51:53.915 Passed test: JIT/Directed/StructABI/EmptyStructs/EmptyStructs.cmd
14:51:53.921 Running test: JIT/Directed/StructABI/StructABI/StructABI.cmd
14:51:53.925 Passed test: JIT/Directed/StructABI/StructABI/StructABI.cmd
14:51:53.930 Running test: JIT/Directed/tailcall/more_tailcalls/more_tailcalls.cmd
14:51:53.934 Passed test: JIT/Directed/tailcall/more_tailcalls/more_tailcalls.cmd
14:51:53.940 Running test: JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
14:51:53.944 Passed test: JIT/Directed/tailcall/mutual_recursion/mutual_recursion.cmd
14:51:53.950 Running test: JIT/Directed/tailcall/tailcall/tailcall.cmd
14:51:53.954 Passed test: JIT/Directed/tailcall/tailcall/tailcall.cmd
14:51:53.959 Running test: JIT/Directed/tls/TestTLSWithLoadedDlls/TestTLSWithLoadedDlls.cmd
14:51:53.964 Passed test: JIT/Directed/tls/TestTLSWithLoadedDlls/TestTLSWithLoadedDlls.cmd
14:51:53.970 Running test: JIT/Directed/VectorABI/VectorMgdMgd_ro/VectorMgdMgd_ro.cmd
14:51:53.975 Passed test: JIT/Directed/VectorABI/VectorMgdMgd_ro/VectorMgdMgd_ro.cmd
...
=== TEST EXECUTION SUMMARY ===
Tests run: 89 Passed: 82 Inconclusive: 0 Failed: 7 Ignored: 0 Skipped: 0
```

### PR DESCRIPTION
**Pull request by radekdoulik**
Implement return of large valuetypes from reflection calls and also large valuetypes arguments.

Change the order of `this` and `retbuf` arguments. This goes toward the https://github.com/dotnet/runtime/issues/120791 and the new calling convention. It also helps to keep the interpreter calls use simple memory copy.

JIT/Directed/Directed_3 runtime tests were used as repro.

It fixes 6 tests in Pri0 and ~2000 tests in Pri1

Fixes https://github.com/dotnet/runtime/issues/122922

### CODE REVIEW

File: src/coreclr/vm/wasm/calldescrworkerwasm.cpp [hunk 1]
```diff
@@ -26,5 +28,10 @@ extern "C" void STDCALL CallDescrWorkerInternal(CallDescrData* pCallDescrData)
         targetIp = pMethod->GetInterpreterCode();
     }
 
-    ExecuteInterpretedMethodWithArgs((TADDR)targetIp, (int8_t*)pCallDescrData->pSrc, pCallDescrData->nArgsSize, (int8_t*)pCallDescrData->returnValue, (PCODE)&CallDescrWorkerInternal);
+    size_t argsSize = pCallDescrData->nArgsSize;
+    if (pCallDescrData->hasRetBuff) {
+        argsSize -= INTERP_STACK_SLOT_SIZE;
+    }
```
[the remark this answers is not in the document]
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/wasm/calldescrworkerwasm.cpp]: Or feel free to remove the braces entirely if the branch case is a single statement.

File: src/coreclr/vm/callingconvention.h [hunk 2]
```diff
@@ -1072,7 +1073,10 @@ int ArgIteratorTemplate<ARGITERATOR_BASE>::GetThisOffset()
 #ifdef TARGET_X86
     // x86 is special as always
     ret += offsetof(ArgumentRegisters, ECX);
-#endif
+#elif defined(TARGET_WASM)
+    if (this->HasRetBuffArg() && IsRetBuffPassedAsFirstArg())
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/callingconvention.h]: There is a member IsRetBuffPassedAsFirstArg() and a stand alone IsRetBuffPassedAsFirstArg(). It isn't obvious to me which one we should be relying on. It looks like there are multiple architectural designs here and it would be great if we could clean them up. For WASM specifically, its as through the RetBuff is always passed as the first arg, is that true?

File: src/coreclr/vm/callingconvention.h [hunk 3]
```diff
@@ -1902,6 +1906,22 @@ int ArgIteratorTemplate<ARGITERATOR_BASE>::GetNextOffset()
...
+
+    size_t align;
+    if (argType == ELEMENT_TYPE_VALUETYPE && argSize > INTERP_STACK_SLOT_SIZE)
+    {
+        align = CEEInfo::getClassAlignmentRequirementStatic(thValueType.GetMethodTable());
+        if (align < INTERP_STACK_SLOT_SIZE)
+            align = INTERP_STACK_SLOT_SIZE;
+
+        if (align > INTERP_STACK_ALIGNMENT)
+            align = INTERP_STACK_ALIGNMENT;
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/callingconvention.h]: I would like to see comments on this logic. It looks as if the SLOT_SIZE and STACK_ALIGNMENT are both constants, can't we simplify this? In the sense of `std::min(align, INTERP_STACK_ALIGNMENT)`?

File: src/coreclr/vm/frames.cpp [hunk 4]
```diff
@@ -734,7 +734,10 @@ PTR_VOID TransitionFrame::GetParamTypeArg()
 TADDR TransitionFrame::GetAddrOfThis()
 {
     WRAPPER_NO_CONTRACT;
-    return GetTransitionBlock() + ArgIterator::GetThisOffset();
```
Comment (jkotas) [inline src/coreclr/vm/frames.cpp:737]: This makes wasm more different from all other architectures. `this` is in a fixed location on all other architectures. In the past, we had some cases where it was not the case and we got rid of them since keep `this` in a fixed location everywhere makes things simpler overall.

Can we keep it like that for wasm too (ie revert this change)?

Instead, move the return bufffer pointer to either dedicated location/register (like it is on arm64) or to be after the this pointer (like it is on x64).

File: src/coreclr/vm/frames.cpp [hunk 5]
```diff
@@ -734,7 +734,10 @@ PTR_VOID TransitionFrame::GetParamTypeArg()
...
+    MethodDesc *pFunction = GetFunction();
+    MetaSig msig(pFunction);
+    ArgIterator argit (&msig);
+    return GetTransitionBlock() + argit.GetThisOffset();
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/vm/frames.cpp]: The `GetAddrOfThis()` API can be called from various locations. It might be worth caching this value somewhere. The previous implementation had far less state than what is being done here.

File: src/coreclr/vm/callingconvention.h (hunk 3 above)
Comment (radekdoulik) [reply src/coreclr/vm/callingconvention.h]: We need to get the alignment into the range `<SLOT_SIZE, STACK_ALIGNMENT>` here. So we would need to use `std::clamp` instead. We use C++ 17 AFAIK, so I can use it. There are few more places with that logic, I will update them all.

File: src/coreclr/vm/frames.cpp (hunk 4 above)
Comment (radekdoulik) [reply src/coreclr/vm/frames.cpp:737]: I wanted to get closer to the calling convention, OTOH it doesn't matter much here. I can offset the change to `CallDescrWorkerInternal`.

Comment (jkotas) [reply src/coreclr/vm/frames.cpp:737]: https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/clr-abi.md#the-this-pointer covers of `this` pointer in the managed ABIs. It should be always passed first.

@AndyAyersMS Can you confirm that it is going to be the case on wasm too?

Comment (AndyAyersMS) [reply src/coreclr/vm/frames.cpp:737]: Currently for Wasm the SP is always the first argument, but it would be easy enough to change that and have SP be first after `this`.

Comment (SingleAccretion) [reply src/coreclr/vm/frames.cpp:737]: For the fixed position of `this`, it is presumably not going to matter whether it is after SP or not, since all methods that have `this` will also have the SP.

Comment (jkotas) [reply src/coreclr/vm/frames.cpp:737]: > > For the fixed position of this, it is presumably not going to matter whether it is after SP or not, since all methods that have this will also have the SP.

yep

File: src/coreclr/vm/callingconvention.h (hunk 3 above)
Comment (radekdoulik) [reply src/coreclr/vm/callingconvention.h]: Updated

File: src/coreclr/vm/frames.cpp (hunk 4 above)
Comment (radekdoulik) [reply src/coreclr/vm/frames.cpp:737]: I reverted the change and updated the calling convention design.

File: src/coreclr/vm/frames.cpp (hunk 5 above)
Comment (radekdoulik) [reply src/coreclr/vm/frames.cpp]: This part is now reverted

File: src/coreclr/vm/callingconvention.h (hunk 2 above)
Comment (radekdoulik) [reply src/coreclr/vm/callingconvention.h]: This part is now reverted

File: docs/design/coreclr/botr/clr-abi.md [hunk 6]
```diff
@@ -709,7 +709,7 @@ Managed code uses the same linear stack as C code. The stack grows down.
 
 ## Incoming argument ABI
 
-The linear stack pointer `$sp` is the first argument to all methods. At a native->managed transition it is the value of the `$__stack_pointer` global. This global may be updated to the current `$sp` within managed code, and must be up to date with the current `$sp` at managed->native boundaries. Within the method the stack pointer always points at the bottom (lowest address) of the stack; generally this is a fixed offset from the value the stack pointer held on entry, except in methods that can do dynamic allocation.
+The linear stack pointer `$sp` is the first argument after the managed `this` argument or the first argument for static methods. At a native->managed transition it is the value of the `$__stack_pointer` global. This global may be updated to the current `$sp` within managed code, and must be up to date with the current `$sp` at managed->native boundaries. Within the method the stack pointer always points at the bottom (lowest address) of the stack; generally this is a fixed offset from the value the stack pointer held on entry, except in methods that can do dynamic allocation.
```
Comment (jkotas) [inline docs/design/coreclr/botr/clr-abi.md]: I think it would be better for stack pointer to be argument 0 so that it is always in a fixed position, and for `this` to be to after that (if it is present) so that it is in fixed position too.

Comment (radekdoulik) [reply docs/design/coreclr/botr/clr-abi.md]: I have reverted the previous change and updated the part with the return buffer for structs.

File: src/coreclr/vm/callingconvention.h [hunk 7]
```diff
@@ -1902,6 +1905,22 @@ int ArgIteratorTemplate<ARGITERATOR_BASE>::GetNextOffset()
 
     return argOfs;
 #elif defined(TARGET_WASM)
+
+    unsigned align;
+    if (argType == ELEMENT_TYPE_VALUETYPE)
+    {
+        align = std::clamp(CEEInfo::getClassAlignmentRequirementStatic(thValueType.GetMethodTable()), INTERP_STACK_SLOT_SIZE, INTERP_STACK_ALIGNMENT);
+    } else {
```
Comment (jkotas) [inline src/coreclr/vm/callingconvention.h]:
```suggestion
    }
    else
    {
```
Style nit

File: src/coreclr/vm/callingconvention.h [hunk 8]
```diff
@@ -1902,6 +1905,22 @@ int ArgIteratorTemplate<ARGITERATOR_BASE>::GetNextOffset()
...
+        align = INTERP_STACK_SLOT_SIZE;
+    }
+
+    if (HasRetBuffArg()) {
+        // the slot for retbuf arg will be removed before the actual call
+        m_ofsStack = ALIGN_UP(m_ofsStack - INTERP_STACK_SLOT_SIZE, align) + INTERP_STACK_SLOT_SIZE;
+    } else {
```
Comment (jkotas) [inline src/coreclr/vm/callingconvention.h]:
```suggestion
    if (HasRetBuffArg())
    {
        // the slot for retbuf arg will be removed before the actual call
        m_ofsStack = ALIGN_UP(m_ofsStack - INTERP_STACK_SLOT_SIZE, align) + INTERP_STACK_SLOT_SIZE;
    }
    else
    {
```

File: src/coreclr/vm/reflectioninvocation.cpp [hunk 9]
```diff
@@ -406,7 +406,7 @@ extern "C" void QCALLTYPE RuntimeMethodHandle_InvokeMethod(
 
     callDescrData.pSrc = pTransitionBlock + sizeof(TransitionBlock);
     _ASSERTE((nStackBytes % TARGET_POINTER_SIZE) == 0);
```
Comment (jkotas) [inline src/coreclr/vm/reflectioninvocation.cpp]:
```suggestion
```
This assert does not make sense now that we are aligning the size up

File: src/coreclr/vm/wasm/calldescrworkerwasm.cpp [hunk 10]
```diff
@@ -26,5 +28,24 @@ extern "C" void STDCALL CallDescrWorkerInternal(CallDescrData* pCallDescrData)
...
+        argsSize -= INTERP_STACK_SLOT_SIZE;
+        if (pCallDescrData->hasThis)
+        {
+            retBuff = *SPECIAL_ARG_ADDR(1);
+            *SPECIAL_ARG_ADDR(1) = *SPECIAL_ARG_ADDR(0);
+        } else {
+            retBuff = *SPECIAL_ARG_ADDR(0);
+        }
+        args = (int8_t*)SPECIAL_ARG_ADDR(1);
+    } else {
```
Comment (jkotas) [inline src/coreclr/vm/wasm/calldescrworkerwasm.cpp]:
```suggestion
        }
        else
        {
            retBuff = *SPECIAL_ARG_ADDR(0);
        }
        args = (int8_t*)SPECIAL_ARG_ADDR(1);
    }
    else
    {
```

File: src/coreclr/vm/wasm/calldescrworkerwasm.cpp [hunk 11]
```diff
@@ -26,5 +28,24 @@ extern "C" void STDCALL CallDescrWorkerInternal(CallDescrData* pCallDescrData)
         targetIp = pMethod->GetInterpreterCode();
```
Comment (jkotas) [inline src/coreclr/vm/wasm/calldescrworkerwasm.cpp:28]: (unrelated to this PR) Just a reminted that WASM-TODO a few lines above is a farm for intermittent crashes. Ideally, it would be fixed by us getting rid of CallDescrWorker completely. If we are not able to do that soon enough, we may need to figure an alternative solution. cc @AaronRobinsonMSFT

**Review by jkotas — APPROVED** [review]

File: src/coreclr/vm/wasm/calldescrworkerwasm.cpp (hunk 11 above)
Comment (AaronRobinsonMSFT) [reply src/coreclr/vm/wasm/calldescrworkerwasm.cpp:28]: Copilot and I are working on it :)

Comment (radekdoulik) [reply src/coreclr/vm/wasm/calldescrworkerwasm.cpp:28]: @AaronRobinsonMSFT how do you plan to solve it?
