### PR TITLE
Fixes 55107

### LINKED ISSUE #55107: Assertion failed '!"unknown type in Global_RelOp"' during 'Assertion prop'
The following program

```c#
using System;
using System.Runtime.CompilerServices;

namespace Runtime_55107
{
    class Program
    {
        class G
        {
        }

        static int Main(string[] args)
        {
            G g = new G();

            ref G iprnull = ref Unsafe.NullRef<G>();
            ref G ipr1 = ref g;

            if(Unsafe.AreSame(ref ipr1, ref iprnull)) { return 7; }
            // Note that using
            // else if(Unsafe.IsNullRef(ref ipr1)) { ... }
            // would not work here.
            else if(Unsafe.AreSame(ref ipr1, ref Unsafe.NullRef<G>())) { return 8; }

            return 100;
        }
    }
}
```

when run with the following environment
```
COMPlus_JitDoRedundantBranchOpts=0
COMPlus_TieredCompilation=0
```

will assert
```
D:\echesako\GitHub\Runtime_55107>D:\echesako\src\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\CoreRun.exe bin\Release\net6.0\Runtime_55107.dll

Assert failure(PID 28844 [0x000070ac], Thread: 33980 [0x84bc]): Assertion failed '!"unknown type in Global_RelOp"' in 'Runtime_55107.Program:Main(System.String[]):int' during 'Assertion prop' (IL size 44)

    File: D:\echesako\src\runtime\src\coreclr\jit\assertionprop.cpp Line: 3397
    Image: D:\echesako\src\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe
```
while propagating assertion `(576, 0) ($240,$0) V03.02 != 0 index=#01, mask=0000000000000001` for the tree
```
N003 (  5,  4) [000054] J------N----              \--*  NE        int    $280
N001 (  3,  2) [000026] ------------                 +--*  LCL_VAR   byref  V03 loc2         u:2 (last use) $240
N002 (  1,  1) [000053] ------------                 \--*  CNS_INT   byref  0 $VN.Null
```

This is a long standing issue - I could reproduce the same bug with 3.1 (not with `Unsafe.*` helpers but in pure IL), so setting milestone to Future.

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by briansull**
Add support for the very rare case of a constant byref to Compiler::optAssertionPropGlobal_RelOp

### CODE REVIEW

**Comment by briansull** [comment]
Fixes #55107

**Comment by echesakovMSFT** [comment]
@briansull Can you please add the test case from #55107 to this PR? Note that you would need to set `COMPlus_JitDoRedundantBranchOpts=0` in the test project to make it always repro.

**Comment by briansull** [comment]
@echesakov Yes, I will turn that repro into a test and add it to the PR

**Comment by briansull** [comment]
I verified that the regress test fails with the old baseline and passes with my fix

File: src/coreclr/jit/assertionprop.cpp [hunk 1]
```diff
@@ -3394,6 +3394,10 @@ GenTree* Compiler::optAssertionPropGlobal_RelOp(ASSERT_VALARG_TP assertions, Gen
                 assert(vnStore->ConstantValue<size_t>(vnCns) == 0);
                 printf("null\n");
             }
+            else if (op1->TypeGet() == TYP_BYREF)
+            {
+                printf("%d (byref)\n", vnStore->ConstantValue<size_t>(vnCns));
```
Comment (echesakovMSFT) [inline src/coreclr/jit/assertionprop.cpp:3399]: Shouldn't we use `target_size_t` here?

**Comment by briansull** [comment]
@echesakovMSFT Please take another look

File: src/coreclr/jit/assertionprop.cpp [hunk 2]
```diff
@@ -3449,6 +3453,11 @@ GenTree* Compiler::optAssertionPropGlobal_RelOp(ASSERT_VALARG_TP assertions, Gen
             noway_assert(vnStore->ConstantValue<size_t>(vnCns) == 0);
             op1->AsIntCon()->gtIconVal = 0;
         }
+        else if (op1->TypeGet() == TYP_BYREF)
+        {
+            op1->ChangeOperConst(GT_CNS_INT);
+            op1->AsIntCon()->gtIconVal = vnStore->ConstantValue<target_size_t>(vnCns);
```
Comment (SingleAccretion) [inline src/coreclr/jit/assertionprop.cpp:3459]: I believe this should be using `target_ssize_t`. Our contract for `gtIconVal` for `TYP_INT` (which `TYP_BYREF` size-wise is when cross compiling to 32 bit on 64 bit) is that the value must be sign-extended. Assigning from an unsigned type will zero-extend it, which is incorrect.

Comment (briansull) [reply src/coreclr/jit/assertionprop.cpp:3459]: Fine I will chnage it to target_ssize_t.  It shouldn't really matter, since the only byref constant that I think we will see is 0.

Comment (echesakovMSFT) [reply src/coreclr/jit/assertionprop.cpp:3459]: If you are saying it's only 0 should we add an assert here? Or noway_assert?

Comment (SingleAccretion) [reply src/coreclr/jit/assertionprop.cpp:3459]: I think we can also see byref consts with RVA statics these days, for example the following code:
```cs
public static ReadOnlySpan<byte> RVAStatic => new byte[] { 1, 2, 3 };
private static ref readonly byte ReturnByrefConst() => ref MemoryMarshal.GetReference(RVAStatic);
```
Gets us the following tree (among many copies...):
```scala
N003 (  6, 13) [000039] -A------R---              *  ASG       byref  $100
N002 (  3,  2) [000038] D------N----              +--*  LCL_VAR   byref  V09 tmp9         d:1 $100
N001 (  2, 10) [000058] H-----------              \--*  CNS_INT(h) byref  0xd1ffab1e static Fseq[039058C6F2C0CB492C533B0A4D14EF77CC0F78ABCCCED5287D84A1A2011CFB81] $100
```
Actually we propagate this constant in assertion prop as `long` (64 bit) for reasons I do not quite understand:
```scala
After constant propagation on [000080]:
STMT00001 (IL   ???...  ???)
N005 (  5,  4) [000085] -A----------              *  COMMA     void   $c2
N003 (  5,  4) [000081] -A------R---              +--*  ASG       byref  $100
N002 (  3,  2) [000079] D------N----              |  +--*  LCL_VAR   byref  V05 tmp5         d:1 $100
               [000093] H-----------              |  \--*  CNS_INT(h) long   0xd1ffab1e static $100
N004 (  0,  0) [000084] ------------              \--*  NOP       void   $c2
```
But we can end up with constant byrefs.

Comment (briansull) [reply src/coreclr/jit/assertionprop.cpp:3459]: I wouldn't add an assert that it must be zero.  
Perhaps we can see this with a RVA static as well as @SingleAccretion pointed out.

Comment (briansull) [reply src/coreclr/jit/assertionprop.cpp:3459]: Using a target_ssize_t causes an assert to be hit in valuenum.h, line 764.



`assert(&typeid(T) == &typeid(size_t)); // We represent ref/byref constants as size_t's.`

Comment (SingleAccretion) [reply src/coreclr/jit/assertionprop.cpp:3459]: Ehh, looks like it will need to use a `static_cast<target_ssize_t>` then :(.

**Comment by briansull** [comment]
@dotnet/jit-contrib This is ready for checkin

File: src/coreclr/jit/assertionprop.cpp (hunk 2 above)
Comment (briansull) [reply src/coreclr/jit/assertionprop.cpp:3459]: We are currently using size_t to store both refs and byrefs constants values in VN.
I don't believe that cross compiling is impacted here either.

Comment (SingleAccretion) [reply src/coreclr/jit/assertionprop.cpp:3459]: > We are currently using size_t to store both refs and byrefs constants values in VN.

Yes, I understand. But here we are converting between the way VN stores them and the IR does, and the IR always stores them as signed.

My concern comes from the following scenario: say the original IR had a byref constant in it, and we have a 64 bit host and a 32 bit target, which means that we sign-extended this constant (say the upper bits are all ones). Now VN saves this constant in the map (doesn't actually matter how it does it, what matter is how we retrieve it) and then the code rehydrates it into an IR constant again, but now zero-extending - we end up with a different value, i. e. the result of `IconValue() < 0` will be different. And this all of course only matter for the cross-compilation scenario because for native compilation there are no extensions, values are stored according to their `TYP` widths.

**Comment by briansull** [comment]
OK, I added the extra casts that @SingleAccretion requested.

File: src/coreclr/jit/assertionprop.cpp (hunk 2 above)
Comment (briansull) [reply src/coreclr/jit/assertionprop.cpp]: I don't think that code can rely upon the order of  constant byref pointers, only equality and inequality should be used when comparing byref pointers.  But I have added the extra compares in order to get this checked in.

I note that there seems to some other nonsense going on when we are cross targeting from 64-bit to 32-bit.
I don't know if it impacts anything or if it is just some dead code.

Take a look at the method  `TruncateOrSignExtend32()` in gentree.h line 3173
It is checking a GT_CNS_INT node for the presence of the flag GTF_UNSIGNED
This flag is not permitted on a GT_CNS_INT node and will always return false.

Comment (SingleAccretion) [reply src/coreclr/jit/assertionprop.cpp]: > I don't think that code can rely upon the order of constant byref pointers, only equality and inequality should be used when comparing byref pointers. But I have added the extra compares in order to get this checked in.

Yes I agree that we ought not to be checking byrefs for their sign, but note that in my example equality is also impacted, i. e. `originalNode->IconValue() == rehydratedNode->IconValue()` will return `false`.

> I note that there seems to some other nonsense going on when we are cross targeting from 64-bit to 32-bit.
I don't know if it impacts anything or if it is just some dead code.

> Take a look at the method TruncateOrSignExtend32() in gentree.h line 3173
It is checking a GT_CNS_INT node for the presence of the flag GTF_UNSIGNED
This flag is not permitted on a GT_CNS_INT node and will always return false.

I've been meaning to delete that method for a little while now :). My understanding of it aligns with yours in that the `GTF_UNSIGNED` check is dead. The only way, in theory (modulo overlapping flags), to hit is if something bashes an oper to a const without resetting the flags, which in itself is incorrect.

**Comment by briansull** [comment]
@dotnet/jit-contrib - 1 approving Review is still required...

File: src/coreclr/jit/assertionprop.cpp [hunk 3]
```diff
@@ -3449,6 +3453,11 @@ GenTree* Compiler::optAssertionPropGlobal_RelOp(ASSERT_VALARG_TP assertions, Gen
             noway_assert(vnStore->ConstantValue<size_t>(vnCns) == 0);
             op1->AsIntCon()->gtIconVal = 0;
         }
+        else if (op1->TypeGet() == TYP_BYREF)
+        {
+            op1->ChangeOperConst(GT_CNS_INT);
+            op1->AsIntCon()->gtIconVal = static_cast<target_ssize_t>(vnStore->ConstantValue<target_size_t>(vnCns));
```
Comment (jakobbotsch) [inline src/coreclr/jit/assertionprop.cpp:3459]: Doesn't this need to be `static_cast<target_ssize_t>(vnStore->ConstantValue<size_t>(vnCns))` due to the assertion you showed in the other discussion thread? Otherwise that assert will fire when the host is 64-bit and the target is 32-bit.

**Comment by briansull** [comment]
@jakobbotsch Made the changes that you wanted

**Review by jakobbotsch — APPROVED** [review]
