### PR TITLE
Fix for Issue 44895

### LINKED ISSUE #44895: Incorrect codegen with multiple returns of a field of a Nullable or struct type
---
**Issue moved from dotnet/sdk#14535**
- Please respond to @dale-personal.

---

_From @dale-personal on Friday, November 13, 2020 2:54:27 PM_

Here is a repo which reproduces the issue:

https://github.com/dale-personal/net5-issue

The code in question functions as expected for a number of iterations, then starts producing unexpected results.

### PR DESCRIPTION
**Pull request by briansull**
Don't allow an unwrapped promoted field to be returned when we are expecting a TYP_STRUCT
(Expanded to include any mismatched type)

### CODE REVIEW

**Comment by briansull** [comment]
@dotnet/jit-contrib PTAL

There are no Asm diffs in System.Private.Corelib 
and for the full frameworks the Arm64 had two methods that had small diffs when we have a multi-reg return struct. and we return one of the two values.

File: src/coreclr/src/jit/gentree.cpp [hunk 1]
```diff
@@ -17583,8 +17583,10 @@ CORINFO_CLASS_HANDLE Compiler::gtGetStructHandleIfPresent(GenTree* tree)
                 break;
             }
             case GT_RETURN:
-                structHnd = gtGetStructHandleIfPresent(tree->AsOp()->gtOp1);
+                // We can grab the return type from the 'args' signature in compMethodInfo
+                structHnd = info.compMethodInfo->args.retTypeClass;
```
Comment (briansull) [inline src/coreclr/src/jit/gentree.cpp:17587]: I could back this change out as it is not necessary for this fix

Comment (sandreenko) [reply src/coreclr/src/jit/gentree.cpp:17587]: Does this change cause the diffs that you see with arm64 multi-reg?

**Comment by sandreenko** [comment]
Nice catch!

Does the test take a long time to run, should it be Pri1 or longRunningGC test?

I have tried to run it locally and it failed with a Jit assert:
```
 "runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe" Runtime_44895.dll
               [000118] -----+------              *  LCL_VAR   ref    V15 tmp11

Assert failure(PID 51232 [0x0000c820], Thread: 4292 [0x10c4]): Assertion failed '!"Incompatible types for gtNewTempAssign"' in 'Property`1[Text][Text]:GetValue(System.Nullable`1[Text]):Text:this' during 'Morph - Global' (IL size 150)

    File: runtime\src\coreclr\src\jit\gentree.cpp Line: 15492
```
for this tree:
```
fgMorphTree BB06, STMT00027 (before)
               [000089] --C---------              *  RETURN    struct
               [000118] ------------              \--*  LCL_VAR   ref    V15 tmp11
```

looks like we catch this problem with our asserts but it makes it hard to understand what exactly goes wrong in release and why it leads to bad execution.


I think your test uncovers a bigger issue with `FIELD struct (1 field with the same size)`  transformation like this:
```
LocalAddressVisitor visiting statement:
STMT00017 (IL   ???...  ???)
               [000059] --C---------              *  RETURN    struct
               [000149] ----G-------              \--*  FIELD     struct value
               [000147] ------------                 \--*  ADDR      byref 
               [000148] -------N----                    \--*  LCL_VAR   struct<System.Nullable`1[Text], 16>(P) V01 arg1         
                                                        \--*    bool   V01.hasValue (offs=0x00) -> V12 tmp8         
                                                        \--*    ref    V01.value (offs=0x08) -> V13 tmp9         
Replacing the field in promoted struct with local var V13
LocalAddressVisitor incrementing ref count from 2 to 3 for implict by-ref V01
LocalAddressVisitor modified statement:
STMT00017 (IL   ???...  ???)
               [000059] --C---------              *  RETURN    struct
               [000149] ------------              \--*  LCL_VAR   ref    V13 tmp9 
```
that can be hit not only for `ref` and not only for trees under return.

I have added another condition to your test so now it fails with the same assert but for `TYP_LONG` so your new condition does not guard against that, but maybe it can't lead to bad execution in release.

[Runtime_44895.modified.txt](https://github.com/dotnet/runtime/files/5651339/Runtime_44895.modified.txt)

I think there are 2 main questions:
1. Is it correct to have `GT_OP struct -> LCL_VAR ref` for GC tracking? We are lucky here because there is a limited number of trees which can have struct type and can use `FIELD` as a child (I can think of `RETURN`, `ASG`, `STORE_*`), so we can check all.
2. Should we allow such cases in `gtNewTempAssign`?
3. How big are the diffs if we forbid the optimization in `fgMorphStructField` for 5.0? As I said we don't many `GT_OP struct -> FIELD` cases, so maybe we won't see many regressions?

File: src/coreclr/src/jit/gentree.cpp (hunk 1 above)
Comment (briansull) [reply src/coreclr/src/jit/gentree.cpp:17587]: No it doesn't cause those diffs.  Occasionally it can give a more specific return type when dealing with generics types.

**Comment by briansull** [comment]
The test fails with an assert using Checked,  With a retail build I think that there is a GC hole.  I will try running it with GCSTRESS.
I modified the original test that the user submitted slightly.

**Comment by briansull** [comment]
We will want a conservative fix for 5.0, so that is what I will pursue as the initial fix in master as well.
As that allows the /backport command.

We wouldn't want to allow gtNewTemp assign to accept a mismatched TYP_REF type assignment.

File: src/coreclr/src/jit/gentree.cpp (hunk 1 above)
Comment (briansull) [reply src/coreclr/src/jit/gentree.cpp:17587]: Updated comment:
Yes, it does cause the diffs that I saw. I am backing it out as it is unnecessary

**Comment by briansull** [comment]
Joy, Joy:

This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
**src/coreclr/src/jit/morph.cpp**

**Comment by JulieLeeMSFT** [comment]
PR #44973 removed the second src folder.

**Comment by briansull** [comment]
@JulieLeeMSFT PR #44973 removed the second src folder.

Yes, I know and caused all existing PR to have a merge conflict that has to be resolved by hand.
I'm sure that this also breaks the /backport command as well.

:-(

**Comment by briansull** [comment]
@sandreenko Please take a look
@dotnet/jit-contrib

**Comment by sandreenko** [comment]
@briansull do you know on which tree we had a GC hole, was it `ASG(struct, ref)`? 
Could we have a GC hole without a merge return block (just `Return struct(LCL_VAR ref)`)?

I was surprised to see that in `Return struct(LCL_VAR ref)`  case we did not hit any asserts, probably if we understand where the hole was happening we could add additional checks there.

I agree with your latest change that the type doesn't matter but I am not sure that `parent->OperGet()`, could it be reproduced when `parent` is not a return instruction?

**Comment by briansull** [comment]
@sandreenko 
I didn't see a GC hole when I ran the test case with a release build under GCSTRESS.
So, I am not sure that there is a GC hole here, but there is bad codegen with release that is for sure.

**Comment by BruceForstall** [comment]
#44895

**Comment by briansull** [comment]
@AndyAyersMS @sandreenko 
Ping -I would like to check this fix in.

**Comment by AndyAyersMS** [comment]
I still don't know what the bug is, so it's hard to be confident this is a complete fix.

Also I wonder if there's some overlap here with #45557?

**Comment by sandreenko** [comment]
@briansull are you confident that the issue can't be repro when the parent is not a struct?

**Comment by BruceForstall** [comment]
> @briansull are you confident that the issue can't be repro when the parent is not a struct?

Do you mean "when the parent is not a GT_RETURN"?

**Comment by sandreenko** [comment]
> Do you mean "when the parent is not a GT_RETURN"?

Yes, thanks, edited.

**Comment by BruceForstall** [comment]
@briansull what does the bad IL (and codegen) look like in the test case, and what does it look like with your change?

**Comment by briansull** [comment]
I am continuing to investigate.  This is not an area in which I know a lot about. @sandreenko may know more about the invariants in this area than I know.

If I disallow **all** other parents there is a huge regression, but it looks like most of that is where the parent is a GT_ADDR node which should always be a safe parent node.

**Comment by briansull** [comment]
The IL isn't bad, instead we hit a whole pile of asserts with a checked build that don't exist in a retail build, so it generates what I assume is bade code because the asserts are there for a good reason.

**Comment by briansull** [comment]
Only five methods have diffs when I use:

```
if (parent->OperGet() != GT_ADDR)
{
    return;
}
```

**Comment by briansull** [comment]
Here is an example of what this transformation does:

```
LocalAddressVisitor visiting statement:
STMT00005 (IL   ???...  ???)
               [000032] -AC---------              *  ASG       struct (copy)
               [000030] D------N----              +--*  LCL_VAR   struct<System.Index, 4>(P) V03 loc1         
                                                  +--*    int    V03._value (offs=0x00) -> V11 tmp7         
               [000074] ------------              \--*  FIELD     struct <Start>k__BackingField
               [000072] ------------                 \--*  ADDR      byref 
               [000073] -------N----                    \--*  LCL_VAR   struct<System.Range, 8>(P) V02 loc0         
                                                        \--*    int    V02.<Start>k__BackingField (offs=0x00) -> V09 tmp5         
                                                        \--*    int    V02.<End>k__BackingField (offs=0x04) -> V10 tmp6         
Replacing the field in promoted struct with local var V09
LocalAddressVisitor modified statement:
STMT00005 (IL   ???...  ???)
               [000032] -AC---------              *  ASG       struct (copy)
               [000030] D------N----              +--*  LCL_VAR   struct<System.Index, 4>(P) V03 loc1         
                                                  +--*    int    V03._value (offs=0x00) -> V11 tmp7         
               [000074] -------N----              \--*  LCL_VAR   int    V09 tmp5         

```
the tree is the GT_FIELD node, which refers to a field of a promoted struct.   As you can see the type of the GT_FIELD node is a TYP_STRUCT, while the promoted local is an int:
`  int    V02.<Start>k__BackingField (offs=0x00) -> V09 tmp5  `       

For this case the parent node is a GT_ASG, and this sequence is the current regression that I got from System.Private.Corelib method `Range:Equals(Object):bool:this`

**Comment by briansull** [comment]
Here is an example of what the transformation does:

```
LocalAddressVisitor visiting statement:
STMT00011 (IL   ???...  ???)
               [000056] -AC---------              *  ASG       struct (copy)
               [000054] D------N----              +--*  LCL_VAR   struct<System.Index, 4>(P) V03 loc1         
                                                  +--*    int    V03._value (offs=0x00) -> V11 tmp7         
               [000091] ------------              \--*  FIELD     struct <End>k__BackingField
               [000089] ------------                 \--*  ADDR      byref 
               [000090] -------N----                    \--*  LCL_VAR   struct<System.Range, 8>(P) V02 loc0         
                                                        \--*    int    V02.<Start>k__BackingField (offs=0x00) -> V09 tmp5         
                                                        \--*    int    V02.<End>k__BackingField (offs=0x04) -> V10 tmp6         
Replacing the field in promoted struct with local var V10
LocalAddressVisitor modified statement:
STMT00011 (IL   ???...  ???)
               [000056] -AC---------              *  ASG       struct (copy)
               [000054] D------N----              +--*  LCL_VAR   struct<System.Index, 4>(P) V03 loc1         
                                                  +--*    int    V03._value (offs=0x00) -> V11 tmp7         
               [000091] -------N----              \--*  LCL_VAR   int    V10 tmp6         

```

**Comment by sandreenko** [comment]
> Only five methods have diffs in System.Private.Corelib.dll when I use:
> 
> if (parent->OperGet() != GT_ADDR)
> {
>     return;
> }

it could be a safe solution, but this method looks important:
```
16 (16.67% of base) : System.Private.CoreLib.dasm - Range:Equals(Object):bool:this
```
what happens there?

**Comment by AndyAyersMS** [comment]
3.1 codegen (no asserts)
```
; Assembly listing for method UnitTest1:testStructReturn(int):struct
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T01] (  6,  4.50)     int  ->  rcx        
;* V01 loc0         [V01    ] (  0,  0   )  struct ( 8) zero-ref    ld-addr-op
;# V02 OutArgs      [V02    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]   "OutgoingArgSpace"
;  V03 tmp1         [V03,T00] (  6,  7   )     ref  ->  rax         "Single return block return value"
;  V04 tmp2         [V04,T02] (  6,  3.50)     ref  ->  rax         V01.innerStruct(offs=0x00) P-INDEP "field V01.innerStruct (fldOffset=0x0)"
;
; Lcl frame size = 0

G_M64641_IG01:
       0F1F440000           nop      

G_M64641_IG02:
       48B8A03100908B020000 mov      rax, 0x28B900031A0
       488B00               mov      rax, gword ptr [rax]
       83F901               cmp      ecx, 1
       7502                 jne      SHORT G_M64641_IG03
       EB15                 jmp      SHORT G_M64641_IG06

G_M64641_IG03:
       83F902               cmp      ecx, 2
       7502                 jne      SHORT G_M64641_IG04
       EB0E                 jmp      SHORT G_M64641_IG06

G_M64641_IG04:
       83F903               cmp      ecx, 3
       7502                 jne      SHORT G_M64641_IG05
       EB07                 jmp      SHORT G_M64641_IG06

G_M64641_IG05:
       83F904               cmp      ecx, 4
       7502                 jne      SHORT G_M64641_IG06
       EB00                 jmp      SHORT G_M64641_IG06

G_M64641_IG06:
       C3                   ret  
```
Jitdump: 
[3.1.dump.txt](https://github.com/dotnet/runtime/files/5664858/3.1.dump.txt)

**Comment by briansull** [comment]
`16 (16.67% of base) : System.Private.CoreLib.dasm - Range:Equals(Object):bool:this`

The Span struct get stack allocated  instead of being enregistered, 

The parent node for the five diff cases are a GT_ASG which is "fixed up" later in this method:

See https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/morph.cpp#L17639

**Comment by briansull** [comment]
I will generated diffs for a change that allows both GT_ADDR and GT_ASG:

```
if (!parent->OperIs(GT_ADDR, GT_ASG))
{
    return;
}

```

**Comment by briansull** [comment]
With the above change there are no difsf in System.Private.Corelib and thereare only two arm64 diffs in the full framework libraries:

```
Top method regressions (percentages):

          32 ( 8.16% of base) : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap:SubstituteCustomModifiers(Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol,System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.CustomModifier, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]):System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.CustomModifier, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]:this (2 methods)

          20 ( 1.37% of base) : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.OverloadResolution:InferMethodTypeArguments(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol,System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol, Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Microsoft.CodeAnalysis.CSharp.AnalyzedArguments,EffectiveParameters,byref,byref):System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]:this (2 methods)


2 total methods with Code Size differences (0 improved, 2 regressed), 209215 unchanged.

Found 2 files with textual diffs.
```
I will take a look at the JIT dump for the two diffs

**Comment by briansull** [comment]
These two have a parent node that is a GT_RETURN, but the method doesn't use the force single return block.

```
LocalAddressVisitor visiting statement:
STMT00030 (IL 0x074...0x07A)
               [000145] ------------              *  RETURN    struct
               [000144] ------------              \--*  FIELD     struct InferredTypeArguments
               [000143] ------------                 \--*  ADDR      byref 
               [000142] -------N----                    \--*  LCL_VAR   struct<Microsoft.CodeAnalysis.CSharp.MethodTypeInferenceResult, 16>(P) V09 loc2         
                                                        \--*    bool   V09.Success (offs=0x00) -> V26 tmp13        
                                                        \--*    ref    V09.InferredTypeArguments (offs=0x08) -> V27 tmp14        

Replacing the field in promoted struct with local var V27
LocalAddressVisitor modified statement:
STMT00030 (IL 0x074...0x07A)
               [000145] ------------              *  RETURN    struct
               [000144] ------------              \--*  LCL_VAR   ref    V27 tmp14        
Local V26 should not be enregistered because: it is address exposed

Local V27 should not be enregistered because: it is address exposed

Local V09 should not be enregistered because: it is address exposed
```

**Comment by briansull** [comment]
@AndyAyersMS @sandreenko 
The current fix has only two small regressions in the framework libraries on Arm64 where we actually have a GT_RETURN parent node, just not one that also has the JIT forcing a single return block.   The dumps on X64 are similar but the codegen ends up being the same because the struct field ends up not getting enregistered on x64.

**Comment by AndyAyersMS** [comment]
So the bad codegen is in ```Property`1[Text][Text]:GetValue(System.Nullable`1[Text]):Text:this```? 

And the issue is that we mistakenly think a var def is a CSE candidate in release because of the rewrite we do during local morph? 

And so we generate bad code when optimizing?

And the explanation for the "fails eventually" note in the original repro is that it takes about this many iterations until Tier1 code for the method above finally gets invoked?

> /// Running 'dotnet test -c release' fails eventually at around 300k iterations.

Note if I run the original repro with tiering disabled it fails quite a bit sooner....
```
C:\bugs\r44895>dotnet test -c Release - -v q --nologo
Test run for C:\bugs\r44895\bin\Release\net5.0\r44895.dll (.NETCoreApp,Version=v5.0)
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 214 ms - r44895.dll (net5.0)

C:\bugs\r44895>set complus_tieredcompilation=0

C:\bugs\r44895>dotnet test -c Release - -v q --nologo
Test run for C:\bugs\r44895\bin\Release\net5.0\r44895.dll (.NETCoreApp,Version=v5.0)
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 28 ms - r44895.dll (net5.0)
```

**Comment by sandreenko** [comment]
> And the issue is that we mistakenly think a var def is a CSE candidate in release because of the rewrite we do during local morph?

The issue is a wrong assignment that we generate with the replaced field type, and the assignment creation asserts about it. If we ignore this assert then we have different types of bad codegen, in the original example it was wrong gc information, that is why many iterations were required in my simplified version it was wrong CSE optimization.

File: src/tests/JIT/Regression/JitBlue/Runtime_44895/Runtime_44895.cs [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+/// Running 'dotnet test -c release' fails eventually at around 300k iterations.
+/// </summary>
+public class UnitTest1
+{
+    public static int Main(string[] args)
+    {
+        var test = "test";
+        var list = new System.Collections.Generic.List<TextProperty>();
+
+        for (int i = 0; i < 10000000; i++)
```
Comment (BruceForstall) [inline src/tests/JIT/Regression/JitBlue/Runtime_44895/Runtime_44895.cs:96]: How long does this run on a checked build? With GCStress? It seems worrying to add a single test with this many iterations.

**Comment by AndyAyersMS** [comment]
> In the original example it was wrong gc information

Are you sure? It looks like with TC disabled the original test will fail consistently after the first call to `GetValue`.  I would not expect a GC info failure to be quite this deterministic.

```
;; default

  Failed TestMethod1 [212 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<test>. Actual:<>. interation: 310148
  Stack Trace:
     at UnitTest1.TestMethod1() in C:\bugs\r44895\Class1.cs:line 97

;; with TC=0

  Failed TestMethod1 [28 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<test>. Actual:<>. interation: 0
  Stack Trace:
     at UnitTest1.TestMethod1() in C:\bugs\r44895\Class1.cs:line 97
```

**Comment by briansull** [comment]
I wasn't able to debug this test using a release build.
I ran it using GCSTRESS=4 and it didn't fail so I probably isn't failing due to a GC hole.

I know that it generates bad code.
I know why it generates bad code.
and I know that my fix corrects the test.

**Comment by briansull** [comment]
I can "fix" the test case so that it doesn't have any iterations
as  it looks like all that is required for it to fail is that we optimize.

**Comment by AndyAyersMS** [comment]
Right. Here's the disasm from the original case...

```asm
; Assembly listing for method Property`1[Text][Text]:GetValue(System.Nullable`1[Text]):Text:this
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 this         [V00,T01] (  5,  4   )     ref  ->  rcx         this class-hnd
;  V01 arg1         [V01,T00] (  4,  8   )   byref  ->  rdx         ld-addr-op
;* V02 loc0         [V02    ] (  0,  0   )  struct (16) zero-ref    ld-addr-op
;* V03 loc1         [V03    ] (  0,  0   )  struct ( 8) zero-ref    ld-addr-op
;  V04 OutArgs      [V04    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;  V05 tmp1         [V05,T09] (  2,  2   )     ref  ->   r9         class-hnd "Inlining Arg"
;* V06 tmp2         [V06,T27] (  0,  0   )     ref  ->  zero-ref    class-hnd "Inlining Arg"
;  V07 tmp3         [V07,T10] (  2,  2   )   byref  ->  r10         "Inlining Arg"
;  V08 tmp4         [V08,T11] (  2,  2   )   byref  ->   r9         "Inlining Arg"
;  V09 tmp5         [V09,T12] (  2,  2   )     ref  ->  rdx         class-hnd "Inlining Arg"
;* V10 tmp6         [V10,T28] (  0,  0   )     ref  ->  zero-ref    class-hnd "Inlining Arg"
;* V11 tmp7         [V11    ] (  0,  0   )  struct ( 8) zero-ref    "Single return block return value"
;  V12 tmp8         [V12,T24] (  2,  1.50)    bool  ->   r8         V18.hasValue(offs=0x00) P-INDEP "field V01.hasValue (fldOffset=0x0)"
;  V13 tmp9         [V13,T23] (  2,  1.50)     ref  ->  rdx         V18.value(offs=0x08) P-INDEP "field V01.value (fldOffset=0x8)"
;  V14 tmp10        [V14,T02] (  4,  2   )    bool  ->  r10         V02.hasValue(offs=0x00) P-INDEP "field V02.hasValue (fldOffset=0x0)"
;* V15 tmp11        [V15,T07] (  0,  0   )     ref  ->  zero-ref    V02.value(offs=0x08) P-INDEP "field V02.value (fldOffset=0x8)"
;  V16 tmp12        [V16,T25] (  2,  1   )     ref  ->  rax         V03._value(offs=0x00) P-INDEP "field V03._value (fldOffset=0x0)"
;  V17 tmp13        [V17,T06] (  4,  2.50)     ref  ->  rax         must-init V11._value(offs=0x00) P-INDEP "field V11._value (fldOffset=0x0)"
;* V18 tmp14        [V18    ] (  0,  0   )  struct (16) zero-ref    "Promoted implicit byref"
;  V19 tmp15        [V19,T04] (  3,  3   )   byref  ->   r9         "BlockOp address local"
;* V20 tmp16        [V20,T29] (  0,  0   )   byref  ->  zero-ref    "BlockOp address local"
;  V21 tmp17        [V21,T05] (  3,  3   )   byref  ->  rdx         "BlockOp address local"
;* V22 tmp18        [V22,T30] (  0,  0   )   byref  ->  zero-ref    "BlockOp address local"
;  V23 cse0         [V23,T18] (  3,  1.50)     int  ->  r10         "CSE - moderate"
;  V24 cse1         [V24,T13] (  2,  1   )   byref  ->   r9         "CSE - moderate"
;  V25 cse2         [V25,T14] (  2,  1   )   byref  ->  rdx         "CSE - moderate"
;* V26 cse3         [V26,T15] (  0,  0   )     ref  ->  zero-ref    "CSE - moderate"
;  V27 cse4         [V27,T08] (  3,  1.50)     ref  ->  rdx         "CSE - moderate"
;* V28 cse5         [V28,T16] (  0,  0   )     ref  ->  zero-ref    "CSE - moderate"
;  V29 cse6         [V29,T03] (  3,  2.50)     ref  ->   r9         "CSE - aggressive"
;  V30 cse7         [V30,T19] (  2,  1   )     int  ->  r10         "CSE - moderate"
;  V31 cse8         [V31,T26] (  2,  1   )     int  ->   r8         "CSE - moderate"
;  V32 cse9         [V32,T20] (  2,  1   )     int  ->  r10         "CSE - moderate"
;  V33 cse10        [V33,T21] (  3,  1.50)     int  ->  r10         "CSE - moderate"
;  V34 cse11        [V34,T17] (  3,  1.50)   byref  ->   r9         "CSE - moderate"
;  V35 cse12        [V35,T22] (  3,  1.50)     int  ->  rdx         "CSE - moderate"
;
; Lcl frame size = 40

G_M34657_IG01:              ;; offset=0000H
       4883EC28             sub      rsp, 40
       33C0                 xor      rax, rax
                                                ;; bbWeight=1    PerfScore 0.50
G_M34657_IG02:              ;; offset=0006H
       440FB602             movzx    r8, byte  ptr [rdx]
       488B5208             mov      rdx, gword ptr [rdx+8]
                                                ;; bbWeight=1    PerfScore 4.00
G_M34657_IG03:              ;; offset=000EH
       4C8B4908             mov      r9, gword ptr [rcx+8]
       4D85C9               test     r9, r9
       741C                 je       SHORT G_M34657_IG06
                                                ;; bbWeight=1    PerfScore 3.25
G_M34657_IG04:              ;; offset=0017H
       4983C108             add      r9, 8
       450FB611             movzx    r10, byte  ptr [r9]
       4D8B4908             mov      r9, gword ptr [r9+8]
       450FB6D2             movzx    r10, r10b
       4585D2               test     r10d, r10d
       7407                 je       SHORT G_M34657_IG06
       4585D2               test     r10d, r10d
       7456                 je       SHORT G_M34657_IG13
                                                ;; bbWeight=0.50 PerfScore 3.50
G_M34657_IG05:              ;; offset=0031H
       EB4F                 jmp      SHORT G_M34657_IG12
                                                ;; bbWeight=0.50 PerfScore 1.00
G_M34657_IG06:              ;; offset=0033H
       4C8D4918             lea      r9, bword ptr [rcx+24]
       4D8BD1               mov      r10, r9
       450FB612             movzx    r10, byte  ptr [r10]
       4585D2               test     r10d, r10d
       740B                 je       SHORT G_M34657_IG08
       4585D2               test     r10d, r10d
       743F                 je       SHORT G_M34657_IG13
                                                ;; bbWeight=0.50 PerfScore 2.63
G_M34657_IG07:              ;; offset=0048H
       498B4108             mov      rax, gword ptr [r9+8]
       EB34                 jmp      SHORT G_M34657_IG12
                                                ;; bbWeight=0.50 PerfScore 2.00
G_M34657_IG08:              ;; offset=004EH
       450FB6C0             movzx    r8, r8b
       4585C0               test     r8d, r8d
       7406                 je       SHORT G_M34657_IG09
       48891424             mov      gword ptr [rsp], rdx                 /// bad code, should set RAX
       EB25                 jmp      SHORT G_M34657_IG12
                                                ;; bbWeight=0.50 PerfScore 2.25
G_M34657_IG09:              ;; offset=005DH
       488B5110             mov      rdx, gword ptr [rcx+16]
       4885D2               test     rdx, rdx
       741A                 je       SHORT G_M34657_IG11
       4883C208             add      rdx, 8
       440FB612             movzx    r10, byte  ptr [rdx]
       488B5208             mov      rdx, gword ptr [rdx+8]
       410FB6D2             movzx    rdx, r10b
       85D2                 test     edx, edx
       7406                 je       SHORT G_M34657_IG11
       85D2                 test     edx, edx
       7409                 je       SHORT G_M34657_IG13
                                                ;; bbWeight=0.50 PerfScore 5.13
G_M34657_IG10:              ;; offset=007EH
       EB02                 jmp      SHORT G_M34657_IG12
                                                ;; bbWeight=0.50 PerfScore 1.00
G_M34657_IG11:              ;; offset=0080H
       33C0                 xor      rax, rax
                                                ;; bbWeight=0.50 PerfScore 0.13
G_M34657_IG12:              ;; offset=0082H
       4883C428             add      rsp, 40
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.25
G_M34657_IG13:              ;; offset=0087H
       E82CFCFFFF           call     System.ThrowHelper:ThrowInvalidOperationException_InvalidOperation_NoValue()
       CC                   int3
``` 
the bug is we return a value improperly in the `_default` case (and also the `_required` case). So it looks like bad code.

You just need to change the last class in the original repro to something like this (and run with TC disabled). No iteration required.
```c#
public class X
{
    public static int Main()
    {
        var test = "test";
        var l = new System.Collections.Generic.List<TextProperty>();
        var t = new TextProperty();
        l.Add(t);
        t.SetDefault(test);
        var gv = t.GetValue();
        bool result = test.Equals(gv.Value);
        Console.WriteLine(result ? "Pass" : "Fail");
        if (!result) Console.WriteLine($"got '{gv.Value}', expected '{test}'");
        return result ? 100 : -1;
    }
}
```

This gives me a bit more confidence in the fix, and I would hazard a guess that the precipitating problem is that we fail to set DONT_CSE on the LHS and so lose track of the fact that this LHS is a local def instead of a local use.

It would be nice to connect the dots a bit further -- are there other cases where we might fail to set the DONT_CSE property and end up with a similar problem? When exactly did this regress?

(as an aside this implicit notion of which lcl var appearances are defs is a major weakness in our IR. It should just be obvious and not require analysis. I know we looked at fixing GT_ASG so the destination was more clearly specified, and perhaps we need to look at it again).

**Comment by AndyAyersMS** [comment]
> How do we "turn off TC" for test in the .csproj file?

`COMPlus_TieredCompilation=0` works on product builds.

**Comment by briansull** [comment]
I noted above and again in the comments for the current fix we have code in this method that checks for a GT_ASG parent node and fixes up the flags by hand.  This doesn't happen when we have a GT_RETURN node that can be turned into GT_ASG when we have a single return block.

See https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/morph.cpp#L17929

**Comment by AndyAyersMS** [comment]
`<Optimize>true</Optimize>` impacts CSC. It does not directly affect the runtime ( its effect is seen indirectly by the absence of a debuggable attribute on the assembly). But as you know with tiering most jitted methods are initially not optimized even if they are optimizable.

> I noted above and again in the comments for the current fix 

Wasn't trying to imply that you weren't clear on what the fix was -- just that we hadn't yet shown specifically on this test case how it lead to bad code.

Did you look into fixing this by adding the missing flag?

**Comment by AndyAyersMS** [comment]
Here's a simpler repro...

```C#
using System;

public struct Text
{
    private readonly string _value;
    public Text(string value) => _value = value;
    public string Value => _value ?? string.Empty; 
}

public class TextProperty 
{
    public Text GetValue(Text? a = null, Text? b = null, Text? c = null, Text? d = null)
    {
        if (a.HasValue) return a.Value;
        if (b.HasValue) return b.Value;
        if (c.HasValue) return c.Value;
        if (d.HasValue) return d.Value;
        return default;
    }
}

public class X
{
    public static int Main()
    {
        string test = "test";
        TextProperty t = new TextProperty();
        Text gv = t.GetValue(new Text(test));
        bool result = test.Equals(gv.Value);
        Console.WriteLine(result ? "Pass" : "Fail");
        if (!result) Console.WriteLine($"got '{gv.Value}', expected '{test}'");
        return result ? 100 : -1;
    }
}
```

**Comment by briansull** [comment]
>Did you look into fixing this by adding the missing flag?

Not sure what you mean by this,  add it when we have a GT_RETURN?

I think the best fix is what I currently have and I don't  think we should optimize the GT_RETURN case at all.

I will take a look at the new repro case

**Comment by briansull** [comment]
I could also tighten up the badcode case by changing one of the asserts that we hit in Checked to be a noway_assert()

**Comment by AndyAyersMS** [comment]
Have been thinking about this some more. I hate to add more checks to workaround limitations elsewhere. Seems like an alternative approach would be to adjust the type of the temp return local if it turns out it's a struct-wrapped field.

Currently we do:
```
lvaGrabTemp returning 7 (V07 tmp1) called for Single return block return value.

mergeReturns statement tree [000115] added to genReturnBB BB34 [0029]
               [000115] ------------              *  RETURN    struct
               [000114] -------N----              \--*  LCL_VAR   struct<Text, 8> V07 tmp1         
```
and then for the individual returns we transform
```
STMT00017 (IL   ???...  ???)
               [000053] --C---------              *  RETURN    struct
               [000066] ----G-------              \--*  FIELD     struct value
               [000064] ------------                 \--*  ADDR      byref 
               [000065] -------N----                  \--*  LCL_VAR struct<System.Nullable`1[Text], 16> V01 arg1       
```
into this after promotion & updates:
```
fgMorphTree BB05, STMT00017 (before)
               [000053] --C---------              *  RETURN    struct
               [000066] ------------              \--*  LCL_VAR   ref    V09 tmp3         
```
and then into this after fixing the individual returns to refer to the temp:
```
STMT00017 (IL   ???...  ???)
               [000185] -A----------              *  ASG       ref   
               [000184] ------------              +--*  IND       ref   
               [000183] ------------              |  \--*  ADDR      byref 
               [000182] D------N----              |     \--*  LCL_VAR   struct<Text, 8>(P) V07 tmp1         
                                                  |     \--*    ref    V07._value (offs=0x00) -> V17 tmp11        
               [000066] -----+-N----              \--*  LCL_VAR   ref    V09 tmp3         
```
and that last `IND` is the troublemaker.

Clearly we already know how to handle the case where we return a non-struct but expect a struct. If you modify my simple repro to have one less return statement we won't merge the returns and we'll end up post-morph with IR like:
```
STMT00009 (IL   ???...  ???)
               [000031] -----+------              *  RETURN    struct
               [000084] -----+------              \--*  LCL_VAR   ref    V12 tmp6         
```
and everything works out as expected.

So that would suggest that if we changed `MergedReturns::CreateReturnBB` to always follow the "old struct retyping" behavior we could avoid this bug. But maybe it would cause other problems.

@sandreenko I presume you might have looked at something like this...?

**Comment by sandreenko** [comment]
> Clearly we already know how to handle the case where we return a non-struct but expect a struct.

You are right, it is supported in `Lowering::LowerRet(GenTreeUnOp* ret)` that calls `LowerRetStruct`, here the code that does the check:
https://github.com/dotnet/runtime/blob/df6ff0fbfa2c107ed710db12fcbf434fc933ea2c/src/coreclr/jit/lower.cpp#L3042-L3046

this case passes as `actualTypesMatch ` because `comp->info.compRetNativeType` is `TYP_REF`.


> So that would suggest that if we changed MergedReturns::CreateReturnBB to always follow the "old struct retyping" behavior we could avoid this bug. But maybe it would cause other problems.
> @sandreenko I presume you might have looked at something like this...?

I think going back to the old struct retyping behavior will create more issues than fixes. 
I would rather prefer the current fix + noway_assert for 5.0 and master and open another 6.0 issue to handle it better later.

**Comment by AndyAyersMS** [comment]
> But maybe it would cause other problems.

Seems to be the case; `fgMorphBlockCopy` would also need to recognize a struct assign where source and dest are the underlying non-struct fields.

Let's go with the current fix.

I think we should also add a merged return stress mode so we exercise this part of the jit's logic more frequently (creating a merged return block even if we don't absolutely have to do so). Seems like it would be a simple thing to add.

**Comment by AndyAyersMS** [comment]
> > But maybe it would cause other problems.
> 
> Seems to be the case

Actually it's not all that bad, the issue is that in `fgMorphSmpOp` we currrently only transform returns for un-merged return cases and the merged return temp; instead we should process all returns.

See https://github.com/dotnet/runtime/compare/master...AndyAyersMS:AlternateReturnWrappedStructFix.

**Comment by briansull** [comment]
I investigated why the left side of this GT_ASG tree didn't have it flags set correctly:
```
STMT00017 (IL   ???...  ???)
               [000185] -A----------              *  ASG       ref   
               [000184] ------------              +--*  IND       ref   
               [000183] ------------              |  \--*  ADDR      byref 
               [000182] D------N----              |     \--*  LCL_VAR   struct<Text, 8>(P) V07 tmp1         
                                                  |     \--*    ref    V07._value (offs=0x00) -> V17 tmp11        
               [000066] -----+-N----              \--*  LCL_VAR   ref    V09 tmp3    
```
Since it is on the left side of the assignment it should have  GTF_VAR_DEF and GTF_DONT_CSE flags set, but it doesn't

This tree node gets created in impAssignStructPtr here:

See https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/importer.cpp#L1591

**Comment by sandreenko** [comment]
@briansull it is cleared here:
https://github.com/dotnet/runtime/blob/a03ab4393908c7cc910a7b68f44fdbfca48f8a68/src/coreclr/jit/importer.cpp#L1621-L1623

**Comment by briansull** [comment]
Yes, the gtNewAssignNode properly sets the GTF_DONT_CSE on the 'dest' two lines above,
Then for some unknown reason this code decides to clear it.

**Comment by sandreenko** [comment]
@AndyAyersMS try the test where not all structs are optimized as `native types`, like
[Runtime_44895.Andy.edited.txt](https://github.com/dotnet/runtime/files/5675590/Runtime_44895.Andy.edited.txt)

so one `FIELD` is not transformed as a primitive and you will get such return:
```
fgMorphTree BB20, STMT00012 (before)
               [000046] ------------              *  RETURN    struct
               [000045] ------------              \--*  FIELD     struct _value
               [000044] ------------                 \--*  ADDR      byref 
               [000043] -------N----                    \--*  LCL_VAR   struct<Text2, 16> V05 loc0  

fgMorphTree BB20, STMT00012 (after)
               [000046] -----+------              *  RETURN    struct
               [000043] -----+------              \--*  LCL_FLD   struct V05 loc0         [+0]
```

and with your changes when we merge return blocks we will get a primitive `mergeTemp` and a struct source, it will just reverse the issue.

**Comment by AndyAyersMS** [comment]
@sandreenko thanks, figured there might be more complications.

**Comment by AndyAyersMS** [comment]
@sandreenko if you are ok with this fix let's go ahead and approve and see if we can get this in for 5.0.2. 

I would like to see the simpler test case added.

**Comment by sandreenko** [comment]
@briansull could you please update the test with a simpler repo or just delete the loop and confirm that it fails without the fix with `complus_TieredCompilation=0`?

File: src/coreclr/jit/importer.cpp [hunk 3]
```diff
@@ -1616,12 +1616,6 @@ GenTree* Compiler::impAssignStructPtr(GenTree*             destAddr,
     GenTree* asgNode = gtNewAssignNode(dest, src);
     gtBlockOpInit(asgNode, dest, src, false);
 
-    // TODO-1stClassStructs: Clean up the settings of GTF_DONT_CSE on the lhs
```
Comment (sandreenko) [inline src/coreclr/jit/importer.cpp:1619]: have you tested this change?

Comment (briansull) [reply src/coreclr/jit/importer.cpp:1619]: I am testing it currently.
I haven't seen any issues with it so far
I an willing to remove it from this fix.

**Comment by briansull** [comment]
@sandreenko I tried running jitstress, copied from you email:

File: src/coreclr/jit/gentree.cpp [hunk 4]
```diff
@@ -15489,7 +15489,7 @@ GenTree* Compiler::gtNewTempAssign(
         if (!ok)
         {
             gtDispTree(val);
-            assert(!"Incompatible types for gtNewTempAssign");
+            noway_assert(!"Incompatible types for gtNewTempAssign");
```
Comment (AndyAyersMS) [inline src/coreclr/jit/gentree.cpp:15492]: Since this is under `#ifdef DEBUG` it's not going to do anything useful.

File: src/coreclr/jit/importer.cpp (hunk 3 above)
Comment (AndyAyersMS) [reply src/coreclr/jit/importer.cpp:1619]: I think for backport sake we should leave it out.

**Comment by briansull** [comment]
>@briansull could you please update the test with a simpler repo or just delete the loop and confirm that it fails without the fix with complus_TieredCompilation=0?

@sandreenko Both tests fail when run with complus_TieredCompilation=0
@AndyAyersMS  When I prepare the final PR with the minimal fix woudl you like one or two test cases?

**Comment by AndyAyersMS** [comment]
> When I prepare the final PR with the minimal fix would you like one or two test cases?

They're more or less equivalent so I would just keep the simpler one.

File: src/coreclr/jit/gentree.cpp (hunk 4 above)
Comment (briansull) [reply src/coreclr/jit/gentree.cpp:15492]: I see, well I will remove it then.

**Comment by briansull** [comment]
@AndyAyersMS @sandreenko 
I posted what I hope can be the final version of this fix
Please review and approve

**Review by sandreenko — APPROVED** [review]
LGTM

**Review by AndyAyersMS — APPROVED** [review]

**Comment by briansull** [comment]
**runtime (Libraries Test Run release coreclr windows x64 Debug) Failing after 42m**
  Starting:    System.Security.Cryptography.Csp.Tests (parallel test collections = on, max threads = 2)
    System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.EmptyHashAlgorithm [FAIL]
      System.TypeInitializationException : The type initializer for 'System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests' threw an exception.
      ---- Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal error occurred.

**Comment by AndyAyersMS** [comment]
I think this is a known issue that pops up from time to time: #29683.

**Comment by briansull** [comment]
@AndyAyersMS - ThanksI guess I will go ahead and merge and I'm sure it isn't caused by my changes.

**Comment by briansull** [comment]
Fixes #44895
