### PR TITLE
Release `CordbUnmanagedThread` instance from `CordbProcess` member

### LINKED ISSUE #65357: corerun debugger fails on exit with "debugger type: mixed (.net core)"
image

Repro: run an app that uses both managed and unmanaged code, for example, C# application or crossgen2, set breakpoints in both managed and unmanaged parts, set debugging mode to "mixed .net core". finish the app and see this error with a high probability. I saw this on VS 2019 and it is still happening with VS 2022.

I guess this scenario is used mostly by runtime developers but would be nice to have it fixed because usually after such errors VS code closes all windows and loses project settings if they were not saved.

In this case, I was running crossgen2 on a test that I and @trylek are working on, so I guess Tomas can repro it as well.

PTAL @mangod9

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #65357

The `m_lastDispatchedIBEvent` was not being cleared during shutdown, which was causing a memory leak assert to fire.

See https://github.com/dotnet/runtime/blob/c3fa7655ea3006f010780d325addcd04aaffa76b/src/coreclr/debug/di/process.cpp#L8130-L8148

I added the clearing in the `NeuterChildren()` method because it seemed like the best place. Suggestions on more appropriate places is welcome.

/cc @dotnet/dotnet-diag

### CODE REVIEW

File: src/coreclr/debug/di/process.cpp [hunk 1]
```diff
@@ -1312,6 +1312,12 @@ void CordbProcess::NeuterChildren()
     m_steppers.NeuterAndClear(GetProcessLock());
 
 #ifdef FEATURE_INTEROP_DEBUGGING
+    if(m_lastDispatchedIBEvent != NULL)
```
Comment (am11) [inline src/coreclr/debug/di/process.cpp:1315]: nit:
```suggestion
    if (m_lastDispatchedIBEvent != NULL)
```

**Review by hoyosjs — APPROVED** [review]
Feels pretty safe - this is a flush, shutdown, or detach path. Might not mimic the best lifetime for the event being held but can't think of a better place to have it - you need it for other continue events and native event convoys. I couldn't find a case that wouldn't fall in this scenario as long as the debugger impl is checking the shutdown/detach path for interop.
