### PR TITLE
Dispose LdapConnections used by PrincipalContext.ValidateCredentials

### LINKED ISSUE #62035: PrincipalContext.Dispose() does not dispose LdapConnection(s) used by PrincipalContext.ValidateCredentials()
### Description

Assume we have an instance `pc` of `System.DirectoryServices.AccountManagement.PrincipalContext` initialised with `ContextType.Domain`. The first time `ValidateCredentials(string userName, string password)` or `ValidateCredentials(string userName, string password, ContextOptions options)` is called on `pc`, a new `LdapConnection` is created and [cached](https://github.com/dotnet/runtime/blob/7414af2a5f6d8d99efc27d3f5ef7a394e0b23c42/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs#L196). Depending on the actual value of the parameter `options` of further invocations of `ValidateCredentials()`, additional instances of `LdapConnection` may be added to the cache. The cache is implemented as a [hashtable `_connCache`](https://github.com/dotnet/runtime/blob/7414af2a5f6d8d99efc27d3f5ef7a394e0b23c42/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs#L57) inside of the internal class [`CredentialValidator`](https://github.com/dotnet/runtime/blob/7414af2a5f6d8d99efc27d3f5ef7a394e0b23c42/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs#L47).

All LDAP connections added to this cache are private to the respective instance of `PrincipalContext` and not shared among different instances of `PrincipalContext` or `CredentialValidator`. Moreover, it is impossible to obtain a reference to a cached LDAP connection using public APIs (without reflection).

When an instance of `PrincipalContext` is disposed, its cached `LdapConnection`s are not used anymore. Consequently, they should be disposed in order to free resources and close the underlying LDAP connections. Unfortunately, the current implementation of `PrincipalContext.Dispose()` does not dispose them, so the `LdapConnection`s remain open until their finalizers run. This may lead to resource exhaustion in scenarios where an LDAP server has a maximum number of simultaneous LDAP connections.

### Reproduction Steps

1. Set up an Active Directory Domain Controller in the local network. In the following, we assume that the DC is available under `dc01.corp`.
2. Create a new C# Console Application with the following code:
```csharp
PrincipalContext principalContext = new PrincipalContext(ContextType.Domain, "dc01.corp");
bool result = principalContext.ValidateCredentials("test", "test");
Console.WriteLine(result);
principalContext.Dispose();
Console.WriteLine("Finished.");
```
3. Add a breakpoint to the call of `principalContext.Dispose()`.
4. Build and debug the application. Step over the call of `Dispose()`.
5. Verify that the cached `LdapConnection`s are not disposed: In the debugger, open Locals > `principalContext` > Non-Public members > `_credValidate` > Non-Public members > `_connCache` > Raw View > Values > Results View >`[0]`. This instance is of type `LdapConnection`. In the debugger, you can see that its member `_disposed` is set to false, i.e. it has not been disposed.

### Expected behavior

The implementation of `PrincipalContext.Dispose()` should call the `Dispose()` method on all of the `LdapConnection`s it caches.

### Actual behavior

`PrincipalContext.Dispose()` does not dispose the `LdapConnection`s the `CredentialValidator` caches.

### Regression?

This does not appear to be a regression, because the same behaviour can be observed in all public versions of `PrincipalContext` in .NET/.NET Core. See for example [this version from 2016](https://github.com/dotnet/corefx/blob/a28b8493c18d745045bb5b3fe3ca58f5c2a758ac/src/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs). Unfortunately, I wasn't able to find `PrincipalContext` in the reference source of .NET Framework, so I don't know whether the .NET Framework implementation is affected.

### Known Workarounds

It is possible to use reflection to close the `LdapConnection`s manually:
```csharp
// The following code is added immediately before or after the call to principalContext.Dispose(),
// e.g. at the end of the using block of a PrincipalContext instance.
if (Environment.Version >= new Version(3, 0) && Environment.Version <= new Version(6, 0))
{
    FieldInfo? fieldCredValidate = typeof(PrincipalContext).GetField("_credValidate", BindingFlags.NonPublic | BindingFlags.Instance);
    object? credValidate = fieldCredValidate?.GetValue(principalContext);
    FieldInfo? fieldConnCache = credValidate?.GetType().GetField("_connCache", BindingFlags.NonPublic | BindingFlags.Instance);
    Hashtable? connCache = fieldConnCache?.GetValue(credValidate) as Hashtable;
    if (connCache is not null)
    {
        foreach (LdapConnection connection in connCache.Values)
        {
            connection.Dispose();
        }
    }
}
```

While this works, this workaround should be used with caution and only temporarily because it accesses implementation details of the framework that are not intended to be accessed outside of the implementation of `PrincipalContext`.

### Configuration

- Versions: I reproduced this issue on .NET 6.0 and nightly builds of .NET 7.0. However, I assume that all versions of .NET Core are affected. 
- OS: Windows 11 Pro Insider Preview Version 10.0.22504.1010
- Architecture: x64
- This issue is not specific to this configuration.

### Other information

I wrote a fix for this and will send a PR in the next few minutes.

### PR DESCRIPTION
**Pull request by juliushardt**
Currently, instances of `LdapConnection` created by `PrincipalContext.ValidateCredentials` are not disposed when the corresponding instance of `PrincipalContext` is disposed (for more information, see #62035). This PR fixes this by adding the required calls to `LdapConnection.Dispose()`.

--

Ensure that cached LdapConnection instances created by
PrincipalContext.ValidateCredentials are disposed when
the corresponding PrincipalContext is disposed.

Fix #62035

### CODE REVIEW

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs [hunk 1]
```diff
@@ -1014,6 +1022,8 @@ public void Dispose()
                 if (_queryCtx != null)
                     _queryCtx.Dispose();
 
+                _credValidate.Dispose();
```
Comment (juliushardt) [inline src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs:1025]: We do not need a null check here because the constructor of `PrincipalContext` always assigns an instance of `CredentialValidator` to `_credValidate` and this is the only place where `_credValidate` is modified.

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs [hunk 2]
```diff
@@ -341,6 +341,14 @@ public bool Validate(string userName, string password, ContextOptions connection
...
             }
         }
+
+        public void Dispose()
+        {
+            foreach (LdapConnection connection in _connCache.Values)
+            {
+                connection.Dispose();
+            }
+        }
```
Comment (juliushardt) [inline src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs:351]: In the other methods of `CredentialValidator`, access to `_connCache` is guarded by locks. However, I'm not sure what the guidelines with respect to multithreading in `IDisposable.Dispose()` methods are. I assumed that `Dispose()` is only supposed to be called when the object is definitely not used anymore (by any thread), so adding a lock may not be necessary. If this is not in line with the guildelines, feel free to tell me and I will update the PR.

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs [hunk 3]
```diff
@@ -44,7 +44,7 @@ internal static class CapabilityMap
         public const string LDAP_CAP_ACTIVE_DIRECTORY_V61_OID = "1.2.840.113556.1.4.1935";
     }
 
-    internal sealed class CredentialValidator
+    internal sealed class CredentialValidator : IDisposable
```
Comment (joperezr) [inline src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs:47]: Even though you are making the class disposable here, you arent' actually using it on the places where it gets instantiated (In PrincipalContext constructor). In order for this to actually get disposed you need to add a `_credValidate.Dispose()` call on PrincipalContext.Dispose()

**Comment by joperezr** [comment]
BTW, sorry for taking a long time for reviewing this, for some reason this PR feel through my radar.

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs (hunk 3 above)
Comment (juliushardt) [reply src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs:47]: Thanks for reviewing my PR! I did add a [`_credValidate.Dispose()` call](https://github.com/dotnet/runtime/blob/810ac4b8275b2da32a084c770474263df3697f49/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs#L1025) on PrincipalContext.Dispose() in this PR (line 1025 in Context.cs). Since the only place where `CredentialValidator` is instantiated is in the constructor of PrincipalContext, this should ensure that it gets properly disposed. Or am I missing something here?

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs (hunk 1 above)
Comment (Alexx999) [reply src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs:1025]: The funny bit to remember about readonly fields is that they might be null if the class has a finalizer. Namely, if the constructor throws before initializing such a field you will get a finalizer call where the field will be null.
In this case, no finalizer so it should be OK to omit a null check.

File: src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs (hunk 3 above)
Comment (joperezr) [reply src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Context.cs:47]: You are totally right, the one that missed it was me, sorry 😄. I was thrown off by the fact that for these types we don't have separate files.

**Review by joperezr — APPROVED** [review]
This is ready to go, I'll just ammend the last commit in order to re-trigger CI since it has been a while since it ran so just to ensure everything is still green.
