### PR TITLE
[wasm][debugger] Breakpoint set in a invalid line, set it to the next available line

### LINKED ISSUE #42704: [wasm][debugger] BP on hidden line; debugger should stop at the next available line
This fails with master:

```csharp
        [Fact]
        public async Task BreakpointOnHiddenLineShouldStopAtEarliestNextAvailableLine()
        {
            var insp = new Inspector();

            //Collect events
            var scripts = SubscribeToScripts(insp);

            await Ready();
            await insp.Ready(async (cli, token) =>
            {
                ctx = new DebugTestContext(cli, insp, token, scripts);

                await SetBreakpoint("dotnet://debugger-test.dll/debugger-test.cs", 539, 8);
                await EvaluateAndCheck(
                    "window.setTimeout(function() { invoke_static_method ('[debugger-test] HiddenSequencePointTest:StepOverHiddenSP'); }, 1);",
                    "dotnet://debugger-test.dll/debugger-test.cs", 546, 4,
                    "StepOverHiddenSP2");
            });
        }
```

Issue: debugger never stops

What is the intended behavior with breakpoint on a hidden line? I tried VS/.net, and that automatically moves the the bp to the next "available" line.

Related code: https://gist.github.com/radical/69a593b9fac153937d60b2053559d596

### PR DESCRIPTION
**Pull request by thaystg**
Fixes [#42704](https://github.com/dotnet/runtime/issues/42704)

### CODE REVIEW

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 1]
```diff
@@ -1619,6 +1619,30 @@ public IEnumerable<SourceLocation> FindBreakpointLocations(BreakpointRequest req
...
+        {
+            AssemblyInfo asm = assemblies.FirstOrDefault(a => a.Name.Equals(request.Assembly, StringComparison.OrdinalIgnoreCase));
+            SourceFile sourceFile = asm?.Sources?.SingleOrDefault(s => s.DebuggerFileName.Equals(request.File, StringComparison.OrdinalIgnoreCase));
+
+            if (sourceFile == null)
+                return null;
+
+            foreach (MethodInfo method in sourceFile.Methods)
+            {
+                if (!method.DebugInformation.SequencePointsBlob.IsNil)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:1632]: nit: Invert the condition, to avoid an extra level of nesting.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 2]
```diff
@@ -1565,6 +1565,16 @@ protected async Task<DebugStore> RuntimeReady(SessionId sessionId, CancellationT
...
             return locations;
         }
+
+        private static IEnumerable<IGrouping<SourceId, SourceLocation>> GetBPReqNextLocation(DebugStore store, BreakpointRequest req)
+        {
+            var nextLocation = store.FindBreakpointNextLocation(req);
+            var nextLocationList = new List<SourceLocation>();
+            if (nextLocation != null)
+                nextLocationList.Add(nextLocation);
+            return nextLocationList.GroupBy(l => l.Id);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1575]: Doesn't `nextLocationList` have one or zero elements only?

Comment (radical) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1575]: oh, but they are needed in the grouped format by the caller.

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 3]
```diff
@@ -1565,6 +1565,16 @@ protected async Task<DebugStore> RuntimeReady(SessionId sessionId, CancellationT
                 .GroupBy(l => l.Id);
             return locations;
         }
+
+        private static IEnumerable<IGrouping<SourceId, SourceLocation>> GetBPReqNextLocation(DebugStore store, BreakpointRequest req)
+        {
+            var nextLocation = store.FindBreakpointNextLocation(req);
+            var nextLocationList = new List<SourceLocation>();
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1572]: can we use a `stackalloc SourceLocation[1]` here?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs [hunk 4]
```diff
@@ -1565,6 +1565,16 @@ protected async Task<DebugStore> RuntimeReady(SessionId sessionId, CancellationT
                 .GroupBy(l => l.Id);
             return locations;
         }
+
+        private static IEnumerable<IGrouping<SourceId, SourceLocation>> GetBPReqNextLocation(DebugStore store, BreakpointRequest req)
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1569]: Maybe this should be done in `GetBPReqLocations` itself? Maybe with a `bool ifNoneFoundThenFindNext` param?

File: src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs (hunk 3 above)
Comment (thaystg) [reply src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:1572]: It looks like we cannot do it for managed types:
error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('SourceLocation')

I changed to:
var nextLocationList = new SourceLocation[1];

**Review by lewing — COMMENTED** [review]
I don't have a strong objection here but it does seem like this is working around a different issue in VS or vscode-js-debug which is allowing breakpoints on lines that aren't returned from getpossiblebreakpoints?

File: src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs [hunk 5]
```diff
@@ -1608,15 +1610,29 @@ public IEnumerable<SourceLocation> FindBreakpointLocations(BreakpointRequest req
...
-                    {
-                        if (!sequencePoint.IsHidden && Match(sequencePoint, request.Line, request.Column))
-                            yield return new SourceLocation(method, sequencePoint);
-                    }
+                    if (sequencePoint.IsHidden)
+                        continue;
+                    if (Match(sequencePoint, request.Line, request.Column))
+                        locations.Add(new SourceLocation(method, sequencePoint));
+                    else if (ifNoneFoundThenFindNext && nextSeqPoint == null && sequencePoint.StartLine > request.Line)
+                        nextSeqPoint = new SourceLocation(method, sequencePoint);
```
Comment (radical) [inline src/mono/wasm/debugger/BrowserDebugProxy/DebugStore.cs:1624]: If either of these is true, then we can break out of the outer loop (for methods).

**Comment by thaystg** [comment]
Debugger.getPossibleBreakpoints is not called by vs or vscode.

**Comment by thaystg** [comment]
If it's called from chrome, when we are using chrome as IDE, we answer 0 availables breakpoints at this line correctly, but chrome tries to set it anyway, it looks like it's ignore this answer.

**Comment by thaystg** [comment]
One important information is that Blazor doesn't support #line hidden #line default, if we add this to a .razor file, the generated file is wrong and we cannot set breakpoint on it at all, because the sequence points are set to the wrong line.

**Comment by radical** [comment]
I added a couple of cases, but they aren't working yet. For the case with "hidden line containing start of an async block", that seemed to work unexpectedly in VS.

**Review by radical — APPROVED** [review]
