### PR TITLE
[JIT] - Fixed sub-optimal optimization for `a % 1` to Zero

### LINKED ISSUE #10956: Sub-optimal code when the operation "% 1" on integers is met
Currently, the CLR gives result "0" (which seems correct) for "remainder of 1" operation on integers.

> The formula `a % b` will always return a value on the range `(-b, b)`, exclusive (it can never return `b` or `-b`), keeping the sign of the dividend. For integer division, the remainder operator satisfies the rule `a % b = a - (a / b) * b`. This is not to be confused with canonical modulus, which satisfies a similar rule but with floored division and returns values on the range `[0, b)`. C# does not have an operator for canonical modulus. However, the behavior is the same for positive dividends.

For `b = 1` the resulting range is obviously `(-1; 1)` ==> just plain `0`.

However, it looks like there is some space for improvements in JIT codegen, since JIT does not seem to fold the result of evaluation to zero constant, which prohibits further optimizations - see the repro code below.

To my understanding, **ALL** `% 1` operations can be folded to just use constant values, with maybe notable exception when the memory read and/or write is required to observe some side effects (eg. volatile variables). For signed integers obtained directly or indirectly (thru implicit type convertion to `Int32`) the code looks quite verbose, given that the result is known ahead. It's better for `UInt32` and `UInt64` where `AND r/m, 0` is issued, but of these `AND [m], 0` only makes sense when again side effects are to be observed. I don't see any reason for `AND r, 0` - this loads CPU scheduler much more than `XOR r, r`.

Understanding that `% 1` does not often occur in the code, here's real case when it may appear (happened to me). Say there is ring buffer with `N` items, and that `N` is provided externally - either thru `static readonly` field (resolve during runtime), or thru `const` definition (resolve during compile time). To calculate the slot index for current or next item, the `% N` opration is used. Since in degenerate case that `N` can be set to `1`, there is desire to reduce all related calculations when there's just one slot for everything. At the moment additional checks placed manually are required and that provides more IL, which reduces inlineability for methods.

------------------------------

The repro code:
```
static sbyte i8 = sbyte.MinValue;
static byte u8 = byte.MaxValue;
static short i16 = short.MinValue;
static ushort u16 = ushort.MaxValue;
static int i32 = int.MinValue;
static uint u32 = uint.MaxValue;
static long i64 = long.MinValue;
static ulong u64 = ulong.MaxValue;

static void Main(string[] args)
{
    // Test with m.loc.
    i8 %= (sbyte)1;
    i16 %= (short)1;
    i32 %= (int)1;
    i64 %= (long)1;

    // Test with r.loc.
    Console.WriteLine((sbyte)(i8 + i8) % (sbyte)1);
    Console.WriteLine((short)(i16 + i16) % (short)1);
    Console.WriteLine((int)(i32 + i32) % (int)1);
    Console.WriteLine((long)(i64 + i64) % (long)1);

    // Test with m.loc.
    u8 %= (byte)1;
    u16 %= (ushort)1;
    u32 %= (uint)1;
    u64 %= (ulong)1;

    // Test with r.loc.
    Console.WriteLine((byte)(u8 + u8) % (byte)1);
    Console.WriteLine((ushort)(u16 + u16) % (ushort)1);
    Console.WriteLine((uint)(u32 + u32) % (uint)1);
    Console.WriteLine((ulong)(u64 + u64) % (ulong)1);
}
```
-----------------
The disasm:
```
--- ...\Program2.cs ---
    i8 %= (sbyte)1;
000007FE749F1450  sub         rsp,28h  
000007FE749F1454  mov         rcx,7FE748D4B30h  
000007FE749F145E  mov         edx,1  
000007FE749F1463  call        000007FED44D04F0  

    // Test with m.loc.
    i8 %= (sbyte)1;
000007FE749F1468  movsx       rcx,byte ptr [7FE748D4B84h]  
000007FE749F1470  mov         eax,ecx  
000007FE749F1472  sar         eax,1Fh  
000007FE749F1475  and         eax,0  
000007FE749F1478  add         eax,ecx  
000007FE749F147A  and         eax,0FFFFFFFFh  
000007FE749F147D  sub         ecx,eax  
000007FE749F147F  movsx       rcx,cl  
000007FE749F1483  mov         byte ptr [7FE748D4B84h],cl  

    i16 %= (short)1;
000007FE749F1489  movsx       rcx,word ptr [7FE748D4B80h]  
000007FE749F1491  mov         eax,ecx  
000007FE749F1493  sar         eax,1Fh  
000007FE749F1496  and         eax,0  
000007FE749F1499  add         eax,ecx  
000007FE749F149B  and         eax,0FFFFFFFFh  
000007FE749F149E  sub         ecx,eax  
000007FE749F14A0  movsx       rcx,cx  
000007FE749F14A4  mov         word ptr [7FE748D4B80h],cx  

    i32 %= (int)1;
000007FE749F14AB  mov         ecx,dword ptr [7FE748D4B78h]  
000007FE749F14B1  mov         eax,ecx  
000007FE749F14B3  sar         eax,1Fh  
000007FE749F14B6  and         eax,0  
000007FE749F14B9  add         eax,ecx  
000007FE749F14BB  and         eax,0FFFFFFFFh  
000007FE749F14BE  sub         ecx,eax  
000007FE749F14C0  mov         dword ptr [7FE748D4B78h],ecx  

    i64 %= (long)1;
000007FE749F14C6  mov         rcx,qword ptr [7FE748D4B68h]  
000007FE749F14CD  mov         rax,rcx  
000007FE749F14D0  sar         rax,3Fh  
000007FE749F14D4  and         rax,0  
000007FE749F14D8  add         rax,rcx  
000007FE749F14DB  and         rax,0FFFFFFFFFFFFFFFFh  
000007FE749F14DF  sub         rcx,rax  
000007FE749F14E2  mov         qword ptr [7FE748D4B68h],rcx  

    // Test with r.loc.
    Console.WriteLine((sbyte)(i8 + i8) % (sbyte)1);
000007FE749F14E9  movsx       rcx,byte ptr [7FE748D4B84h]  
000007FE749F14F1  add         ecx,ecx  
000007FE749F14F3  movsx       rcx,cl  
000007FE749F14F7  mov         eax,ecx  
000007FE749F14F9  sar         eax,1Fh  
000007FE749F14FC  and         eax,0  
000007FE749F14FF  add         eax,ecx  
000007FE749F1501  and         eax,0FFFFFFFFh  
000007FE749F1504  sub         ecx,eax  
000007FE749F1506  call        000007FE749F12D0  

    Console.WriteLine((short)(i16 + i16) % (short)1);
000007FE749F150B  movsx       rcx,word ptr [7FE748D4B80h]  
000007FE749F1513  add         ecx,ecx  
000007FE749F1515  movsx       rcx,cx  
000007FE749F1519  mov         eax,ecx  
000007FE749F151B  sar         eax,1Fh  
000007FE749F151E  and         eax,0  
000007FE749F1521  add         eax,ecx  
000007FE749F1523  and         eax,0FFFFFFFFh  
000007FE749F1526  sub         ecx,eax  
000007FE749F1528  call        000007FE749F12D0  

    Console.WriteLine((int)(i32 + i32) % (int)1);
000007FE749F152D  mov         ecx,dword ptr [7FE748D4B78h]  
000007FE749F1533  add         ecx,ecx  
000007FE749F1535  mov         eax,ecx  
000007FE749F1537  sar         eax,1Fh  
000007FE749F153A  and         eax,0  
000007FE749F153D  add         eax,ecx  
000007FE749F153F  and         eax,0FFFFFFFFh  
000007FE749F1542  sub         ecx,eax  
000007FE749F1544  call        000007FE749F12D0  

    Console.WriteLine((long)(i64 + i64) % (long)1);
000007FE749F1549  mov         rcx,qword ptr [7FE748D4B68h]  
000007FE749F1550  add         rcx,rcx  
000007FE749F1553  mov         rax,rcx  
000007FE749F1556  sar         rax,3Fh  
000007FE749F155A  and         rax,0  
000007FE749F155E  add         rax,rcx  
000007FE749F1561  and         rax,0FFFFFFFFFFFFFFFFh  
000007FE749F1565  sub         rcx,rax  
000007FE749F1568  call        000007FE749F12E0  

    // Test with m.loc.
    u8 %= (byte)1;
000007FE749F156D  movzx       ecx,byte ptr [7FE748D4B85h]  
000007FE749F1574  mov         eax,ecx  
000007FE749F1576  sar         eax,1Fh  
000007FE749F1579  and         eax,0  
000007FE749F157C  add         eax,ecx  
000007FE749F157E  and         eax,0FFFFFFFFh  
000007FE749F1581  sub         ecx,eax  
000007FE749F1583  movzx       ecx,cl  
000007FE749F1586  mov         byte ptr [7FE748D4B85h],cl  

    u16 %= (ushort)1;
000007FE749F158C  movzx       ecx,word ptr [7FE748D4B82h]  
000007FE749F1593  mov         eax,ecx  
000007FE749F1595  sar         eax,1Fh  
000007FE749F1598  and         eax,0  
000007FE749F159B  add         eax,ecx  
000007FE749F159D  and         eax,0FFFFFFFFh  
000007FE749F15A0  sub         ecx,eax  
000007FE749F15A2  movzx       ecx,cx  
000007FE749F15A5  mov         word ptr [7FE748D4B82h],cx  

    u32 %= (uint)1;
000007FE749F15AC  and         dword ptr [7FE748D4B7Ch],0  

    u64 %= (ulong)1;
000007FE749F15B3  and         qword ptr [7FE748D4B70h],0  

    // Test with r.loc.
    Console.WriteLine((byte)(u8 + u8) % (byte)1);
000007FE749F15BB  movzx       ecx,byte ptr [7FE748D4B85h]  
000007FE749F15C2  add         ecx,ecx  
000007FE749F15C4  movzx       ecx,cl  
000007FE749F15C7  mov         eax,ecx  
000007FE749F15C9  sar         eax,1Fh  
000007FE749F15CC  and         eax,0  
000007FE749F15CF  add         eax,ecx  
000007FE749F15D1  and         eax,0FFFFFFFFh  
000007FE749F15D4  sub         ecx,eax  
000007FE749F15D6  call        000007FE749F12D0  

    Console.WriteLine((ushort)(u16 + u16) % (ushort)1);
000007FE749F15DB  movzx       ecx,word ptr [7FE748D4B82h]  
000007FE749F15E2  add         ecx,ecx  
000007FE749F15E4  movzx       ecx,cx  
000007FE749F15E7  mov         eax,ecx  
000007FE749F15E9  sar         eax,1Fh  
000007FE749F15EC  and         eax,0  
000007FE749F15EF  add         eax,ecx  
000007FE749F15F1  and         eax,0FFFFFFFFh  
000007FE749F15F4  sub         ecx,eax  
000007FE749F15F6  call        000007FE749F12D0  

    Console.WriteLine((uint)(u32 + u32) % (uint)1);
000007FE749F15FB  mov         ecx,dword ptr [7FE748D4B7Ch]  
000007FE749F1601  add         ecx,ecx  
000007FE749F1603  and         ecx,0  
000007FE749F1606  call        000007FE749F12D8  

    Console.WriteLine((ulong)(u64 + u64) % (ulong)1);
000007FE749F160B  mov         rcx,qword ptr [7FE748D4B70h]  
000007FE749F1612  add         rcx,rcx  
000007FE749F1615  and         rcx,0  
000007FE749F1619  call        000007FE749F12E8  

000007FE749F161E  nop  
000007FE749F161F  add         rsp,28h  
000007FE749F1623  ret  
--- No source file -------------------------------------------------------------
```

category:cq
theme:expression-opts
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by TIHan**
**Description**

Should resolve: https://github.com/dotnet/runtime/issues/10956

We already did the transformation of `a % 1`, but we ignored it if `op1` had any side effects. This PR should fix that.

X64 Diff:
image

**Acceptance Criteria**
- [x] Disasm tests

### CODE REVIEW

File: src/coreclr/jit/morph.cpp [hunk 1]
```diff
@@ -13160,6 +13177,50 @@ GenTree* Compiler::fgMorphMultiOp(GenTreeMultiOp* multiOp)
...
+        INDEBUG(zero->gtDebugFlags |= GTF_DEBUG_NODE_MORPHED);
+
+        DEBUG_DESTROY_NODE(tree->gtOp2);
+        DEBUG_DESTROY_NODE(tree->gtOp1);
+        DEBUG_DESTROY_NODE(tree);
+
+        return zero;
+    }
+
+    GenTree* comma = gtNewOperNode(GT_COMMA, tree->gtType, op1, zero);
```
Comment (TIHan) [inline src/coreclr/jit/morph.cpp:13214]: Does `op1` have to be `TYP_VOID` for this to be valid?

**Comment by SingleAccretion** [comment]
Note there is already an optimization that does this: https://github.com/dotnet/runtime/blob/bdd67af67dbf43c0f5e9151b98dc100b9555898a/src/coreclr/jit/morph.cpp#L9872-L9887.

**Comment by TIHan** [comment]
Good catch. Will probably remove it in favor of this since it expands it.

File: src/coreclr/jit/morph.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp]: I think you should use `gtExtractSideEffList` instead, that will give you a better tree to put as the LHS here (or null if there are no side effects). There are some existing examples in morph you can look at.

Comment (TIHan) [reply src/coreclr/jit/morph.cpp]: Yes, this will be better since my approach was more conservative.

**Comment by TIHan** [comment]
@dotnet/jit-contrib This is ready.

**Comment by jakobbotsch** [comment]
The failures look related

**Comment by TIHan** [comment]
@dotnet/jit-contrib @jakobbotsch This is ready again.

File: src/coreclr/jit/morph.cpp [hunk 2]
```diff
@@ -9869,20 +9869,13 @@ GenTree* Compiler::fgMorphSmpOp(GenTree* tree, MorphAddrContext* mac, bool* optA
...
 
-            // For "val % 1", return 0 if op1 doesn't have any side effects
-            // and we are not in the CSE phase, we cannot discard 'tree'
-            // because it may contain CSE expressions that we haven't yet examined.
-            //
-            if (((op1->gtFlags & GTF_SIDE_EFFECT) == 0) && !optValnumCSE_phase)
+            if (!optValnumCSE_phase)
             {
-                if (op2->IsIntegralConst(1))
+                if (tree->OperIs(GT_MOD, GT_UMOD) && (op2->IsIntegralConst(1) || op2->IsIntegralConst(-1)))
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:9874]: Note that `a % -1` throws an exception for `a == int.MinValue`, so I'm not sure the transformation is valid for that case.

Comment (BruceForstall) [reply src/coreclr/jit/morph.cpp:9874]: > Note that `a % -1` throws an exception for `a == int.MinValue`, so I'm not sure the transformation is valid for that case.

Hopefully we have a test for that case somewhere?

File: src/coreclr/jit/morph.cpp [hunk 3]
```diff
@@ -13160,6 +13148,57 @@ GenTree* Compiler::fgMorphMultiOp(GenTreeMultiOp* multiOp)
...
+
+    GenTree* op1SideEffects = nullptr;
+    gtExtractSideEffList(op1, &op1SideEffects, GTF_ALL_EFFECT);
+    if (op1SideEffects != nullptr)
+    {
+        GenTree* comma = gtNewOperNode(GT_COMMA, type, op1SideEffects, zero);
+
+#ifdef DEBUG
+        // op1 may already have been morphed, so unset this bit.
+        op1SideEffects->gtDebugFlags &= ~GTF_DEBUG_NODE_MORPHED;
```
Comment (jakobbotsch) [inline src/coreclr/jit/morph.cpp:13182]: It would be better if we can factor the code so that we don't morph the same trees multiple times (I'm not sure it is in general ok to morph the same node twice). In what cases have we already morphed `op1SideEffects`? Seems odd since this runs in pre-order.

File: src/coreclr/jit/morph.cpp [hunk 4]
```diff
@@ -13160,6 +13148,57 @@ GenTree* Compiler::fgMorphMultiOp(GenTreeMultiOp* multiOp)
...
+
+    assert(tree->OperIs(GT_MOD, GT_UMOD));
+    assert(tree->gtOp2->IsIntegralConst(1) || tree->gtOp2->IsIntegralConst(-1));
+
+    GenTree* op1 = tree->gtGetOp1();
+    GenTree* op2 = tree->gtGetOp2();
+
+    const var_types type = tree->TypeGet();
+
+    GenTree* zero = gtNewZeroConNode(type);
```
Comment (SingleAccretion) [inline src/coreclr/jit/morph.cpp:13172]: TP nit: it would be better to reuse an existing constant node (`op2`) instead of creating a new one.

File: src/coreclr/jit/morph.cpp (hunk 2 above)
Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp]: Ah, here it is:
https://github.com/dotnet/runtime/blob/c6549d9ef9f37539f8ea4c14073e75c7b69fbd23/src/tests/JIT/CodeGenBringUpTests/ModConst.cs#L216

File: src/coreclr/jit/morph.cpp (hunk 3 above)
Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp:13181]: Well, that's unfortunate. I wonder if we could chnage `gtBuildCommaList` to only set the flag if the expression being added has already been morphed.

File: src/coreclr/jit/morph.cpp (hunk 2 above)
Comment (TIHan) [reply src/coreclr/jit/morph.cpp]: Yea I removed the -1 optimization. We probably could optimize it for small types since they don't throw, let's do that in a separate PR.

File: src/coreclr/jit/morph.cpp (hunk 3 above)
Comment (TIHan) [reply src/coreclr/jit/morph.cpp:13181]: Yea there seems to be a case where op1 is a GT_COMMA that is already marked as morphed. I'm not familiar with how that happens, so this is acting like a bandaid.

File: src/coreclr/jit/morph.cpp (hunk 4 above)
Comment (TIHan) [reply src/coreclr/jit/morph.cpp:13171]: We shouldn't need to update for VN should we?

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:13171]: Why not?

(Of at least two trees - the comma and the zero)

Comment (TIHan) [reply src/coreclr/jit/morph.cpp]: Updated the VN and re-using `op2`. Not sure how to update the comma for VN.

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp]: > Not sure how to update the comma for VN.

It's a bit non-trivial. The comma needs to have the normal VN of zero and `op1SideEffects`'s exception set.

We usually shy away from complex VN updates like this in morph and guard the transform on `fgGlobalMorph` instead.

Comment (TIHan) [reply src/coreclr/jit/morph.cpp]: Do you suggest we not do the transformation if `op1` has side effects and it's not `fgGlobalMorph`? I guess I'm a little confused because there are cases where we create GT_COMMAs without updating VNs.

Comment (TIHan) [reply src/coreclr/jit/morph.cpp]: It's not updating the VN, but maybe `gtUpdateNodeSideEffects` is sufficient enough?

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp]: > Do you suggest we not do the transformation if op1 has side effects and it's not `fgGlobalMorph`

There are multiple ways to solve this problem.

1) The simplest (but most pessimistic) is to only do the optimization under `fgGlobalMorph` and not worry about VN updates.

2) A less pessimistic one would be to do the part of the transformation that doesn't require VN complex updates always, and one that does - under `fgGlobalMorph`. This would be differentiated by `op1->gtFlags & GTF_SIDE_EFFECT`.

3) Finally, you could introduce a method, call it `fgUpdateCommaValueNumber` that will do the appropriate thing and call it here.

So far we've been doing `1` in morph, but if the diffs for this change mean it's not useful if not done with `2` or `3`, I guess we can do those.

> there are cases where we create GT_COMMAs without updating VNs 

In general, any code that creates / changes nodes without paying attention to VNs after VNs have been established and before they are invalidated (~rationalization) is bugged.

Comment (TIHan) [reply src/coreclr/jit/morph.cpp]: If you look at `fgMorphModToSubMulDiv`, we create new `GT_COMMA`s there but it's not guarded by `fgGlobalMorph` - does that mean it's bugged as well?

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp]: Yes in theory, no in practice, because we nothing introduces new `MOD/UMOD` nodes after global morph, and the ones that were there would all be transformed. There are a few other "fixed point" transformations like that (e. g. block morphing).

Comment (TIHan) [reply src/coreclr/jit/morph.cpp]: Majority of the optimization still works if we only do it in global morph when there are side effects, so it's sufficient.

**Comment by TIHan** [comment]
@dotnet/jit-contrib @EgorBo  This is ready for review again. We update the value number for the zero node, and we disable the optimization if we are not in global morph when there are side effects.

File: src/coreclr/jit/morph.cpp [hunk 5]
```diff
@@ -12789,6 +12794,11 @@ GenTree* Compiler::fgMorphModToZero(GenTreeOp* tree)
     gtExtractSideEffList(op1, &op1SideEffects, GTF_ALL_EFFECT);
     if (op1SideEffects != nullptr)
     {
+        // Do not transform this if there are side effects and we are not in global morph.
+        // If we want to allow this, we need to update value numbers for the GT_COMMA.
```
Comment (SingleAccretion) [inline src/coreclr/jit/morph.cpp:12798]: `gtExtractSideEffList` alters the state of IR, so this check has to be done before using it.

Comment (TIHan) [reply src/coreclr/jit/morph.cpp:12798]: That's unfortunate. I'll add the check before then.

Comment (TIHan) [reply src/coreclr/jit/morph.cpp:12798]: If I add the check before, then the optimization when there are no side effects will not happen when not in global morph. So this makes this a little more complicated.

Comment (TIHan) [reply src/coreclr/jit/morph.cpp:12798]: Why is `gtExtractSideEffList` actually causing a side effect itself? This should just be a function to get information, not modify it.

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:12798]: (I would expect you could check it like this: `if ((gtFlags & GTF_SIDE_EFFECT) == 0) { /* no side effects */ } else if (fgGlobalMorph) { /* side effects and in global morph */ }`.)

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:12798]: > Why is `gtExtractSideEffList` actually causing a side effect itself? This should just be a function to get information, not modify it.

Just a consequence of the how it is currently used. It is unusual to have the situation we have here, plus, the side effects flags can always be checked instead to get approximately the same answer.

Comment (TIHan) [reply src/coreclr/jit/morph.cpp:12798]: I'm going to have to think on this. The code gets messy when I want to use `gtExtractSideEffList`. Might be better off just checking the flag and wrapping `op1` with a new tmp and comma.

Comment (SingleAccretion) [reply src/coreclr/jit/morph.cpp:12798]: I am not sure what the point of temporaries would be. In my mind the code could look like this:
```scala
if (((op1->gtFlags & GTF_SIDE_EFFECT) != 0) && !fgGlobalMorph)
{
    // Comment about VNs.
    retrun nullptr;
}

op2->AsIntConCommon()->SetIconValue(0);
fgUpdateConstTreeValueNumber(op2);

GenTree* op1SideEffects = nullptr;
gtExtractSideEffList(op1, &op1SideEffects, GTF_ALL_EFFECT);
if (op1SideEffects != nullptr) // Same code as we already have below
```

Comment (TIHan) [reply src/coreclr/jit/morph.cpp:12798]: I see, that looks fine since we will assume extracting side effects will always be null if that flag is not flag. I was overthinking it.

**Comment by TIHan** [comment]
@dotnet/jit-contrib ready again

**Comment by TIHan** [comment]
@dotnet/jit-contrib @jakobbotsch @EgorBo This is ready again too. Fixed a minor issue when setting the integral value for `GT_CNS_LNG` on x86/arm.

File: src/tests/JIT/opt/Remainder/Regressions/Regression1/Regression1.csproj [hunk 6]
```diff
@@ -0,0 +1,13 @@
+<Project Sdk="Microsoft.NET.Sdk">
+  <PropertyGroup>
+    <OutputType>Exe</OutputType>
+    <DisableProjectBuild Condition="'$(RuntimeFlavor)' == 'Mono'">true</DisableProjectBuild>
```
Comment (markples) [inline src/tests/JIT/opt/Remainder/Regressions/Regression1/Regression1.csproj:4]: Why is this disabled on mono?  And if so, why DisableProjectBuild rather than using issues.targets?  (I'm not sure why one would be used over the other except I guess DisableProjectBuild could be used for code that doesn't even build for a platform?)

(And if left this way, is it `Mono` or `mono`?)

Comment (TIHan) [reply src/tests/JIT/opt/Remainder/Regressions/Regression1/Regression1.csproj:4]: Disabled this for mono because it was failing the AllSubsets_Mono_LLVMFullAot runs. 

I used disable project build because it was more convenient.

Comment (TIHan) [reply src/tests/JIT/opt/Remainder/Regressions/Regression1/Regression1.csproj:4]: As far as using `Mono` or `mono`, I was just following precedent on how it was used. You can see uses from `git grep "DisableProjectBuild Condition="`

Comment (markples) [reply src/tests/JIT/opt/Remainder/Regressions/Regression1/Regression1.csproj:4]: Did you file a mono issue?  Using issues.targets is the common place to then store the issue number so that the test can later be reenabled.

Grepping for it shows both Mono and mono.

Comment (TIHan) [reply src/tests/JIT/opt/Remainder/Regressions/Regression1/Regression1.csproj:4]: We should file the mono issue once the test is checked in.

Comment (markples) [reply src/tests/JIT/opt/Remainder/Regressions/Regression1/Regression1.csproj:4]: I'd recommend filing it first and then you just include the work item # in a comment (presumably in issues.targets) like other issues are tracked.  Otherwise you'll have a two-step checkin.

Comment (TIHan) [reply src/tests/JIT/opt/Remainder/Regressions/Regression1/Regression1.csproj]: done

**Comment by TIHan** [comment]
@dotnet/jit-contrib This is ready for another round of review, based on our internal discussion yesterday.

**Review by BruceForstall — APPROVED** [review]

File: src/tests/JIT/opt/Remainder/IntRemainder.csproj [hunk 7]
```diff
@@ -0,0 +1,17 @@
...
+    <DebugType>None</DebugType>
+    <Optimize>True</Optimize>
+  </PropertyGroup>
+  <ItemGroup>
+    <Compile Include="$(MSBuildProjectName).cs">
+      <HasDisasmCheck>true</HasDisasmCheck>
+    </Compile>
+
+    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="0" />
+    <CLRTestEnvironmentVariable Include="DOTNET_JITMinOpts" Value="0" />
```
[the remark this answers is not in the document]
Comment (TIHan) [reply src/tests/JIT/opt/Remainder/IntRemainder.csproj:15]: `<HasDisasmCheck>true<...>` does not force any environment variables - so it is up to the test itself to decide them.

File: src/coreclr/jit/morph.cpp (hunk 3 above)
Comment (jakobbotsch) [reply src/coreclr/jit/morph.cpp:12827]: > But what if there are more than two side effects?

Was this addressed @TIHan? I'm seeing failures in Fuzzlyn on main that look related to this change, e.g.
```csharp
// Generated by Fuzzlyn v1.5 on 2022-12-10 12:51:10
// Run on Arm64 MacOS
// Seed: 5902439178145702891
// Reduced from 176.0 KiB to 0.3 KiB in 00:01:07
// Hits JIT assert in Release:
// Assertion failed '((tree->gtDebugFlags & GTF_DEBUG_NODE_MORPHED) == 0) && "ERROR: Already morphed this node!"' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Morph - Global' (IL size 34; hash 0xade6b36b; FullOpts)
// 
//     File: /Users/runner/work/1/s/src/coreclr/jit/morph.cpp Line: 12916
// 
public class Program
{
    public static int[][][] s_10;
    public static ulong[][] s_14;
    public static byte[] s_26;
    public static void Main()
    {
        ulong vr6 = s_14[0][0];
        var vr5 = ((short)vr6 * (s_10[0][0][0] | s_26[0])) % 1;
    }
}
```

Maybe try the fix I suggested above?
