### PR TITLE
[NativeAOT/Apple] Map the thunks using vm_allocate/vm_remap

### LINKED ISSUE #94655: [NativeAOT] App Store Connect warning ITMS-90999: Invalid executable
_From @tipa on Thu, 02 Nov 2023 18:59:22 GMT_

I read about the NativeAOT experimental feature [here](https://devblogs.microsoft.com/dotnet/dotnet-8-performance-improvements-in-dotnet-maui/#nativeaot-on-ios) and wanted to give it a try right away.
The app can be downloaded via TestFlight and is significantly smaller than before (with the Mono AOT) - **awesome**! I also don't see any functional issues

### Steps to Reproduce

1. Add `<PublishAot>true</PublishAot>` to .csproj
2. `dotnet publish`
3. Upload resulting .ipa to App Store Connect

### Expected Behavior
No warning/error

### Actual Behavior
Email from Apple:
```
We identified one or more issues with a recent delivery for your app, "MyApp" 1.0.0 (1.0.0). Your delivery was successful, but you may wish to correct the following issues in your next delivery: 
ITMS-90999: Invalid executable - The executable in “MyApp.iOS.app” contains multiple segments with the executable permission bit set when it should only contain one. 
After you’ve corrected the issues, you can upload a new binary to App Store Connect. 
```
### Environment

.NET8 RC2.1

_Copied from original issue xamarin/xamarin-macios#19387_

### PR DESCRIPTION
**Pull request by filipnavara**
Map the thunks using vm_allocate/vm_remap to avoid need for specific executable segment layout.

Fixes #94655

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thank you!

File: src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp [hunk 1]
```diff
@@ -516,59 +515,61 @@ extern "C" bool PalDetachThread(void* thread)
...
     }
 
-    // NOTE: We ignore templateRva since we would need to convert it to file offset
-    // and templateSize is useless too. Instead we read the sections from the
-    // executable and determine the size from them.
-    if (thunks_section == NULL)
+    do
+    {
+        ret = vm_remap(
+            mach_task_self(), &addr, templateSize, 0, VM_FLAGS_FIXED | VM_FLAGS_OVERWRITE,
```
Comment (ivanpovazan) [inline src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:540]: Just trying to understand the difference here, Mono seems to pass only `FALSE` in place of flags when calling `vm_remap`, why are we passing `VM_FLAGS_FIXED | VM_FLAGS_OVERWRITE` instead (or vice versa should we use the same on Mono side as well)?

**Review by ivanpovazan — APPROVED** [review]
LGTM, thank you!

I just left a minor question/comment above.

@filipnavara would it make sense to add some kind of unit test verifying that the app has only a single executable segment?

File: src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp (hunk 1 above)
Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:540]: We should use this on Mono side as well. Mono uses a loop with vm_allocate(2*size)+vm_deallocate(1*size)+vm_remap. There's a race condition between the vm_deallocate+vm_remap not ending up at the same address. If the race condition is hit then it starts again from the beginning. `VM_FLAGS_OVERWRITE` gets rid of this race condition by skipping the intermediate reallocation.

**Comment by filipnavara** [comment]
> would it make sense to add some kind of unit test verifying that the app has only a single executable segment?

I don't think it's necessary. You have to go out of your way to create a second executable segment, it doesn't happen without an explicit effort to do so.

File: src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp (hunk 1 above)
Comment (ivanpovazan) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:540]: /cc: @lambdageek ^

**Comment by filipnavara** [comment]
Thanks for review and backport.

File: src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp (hunk 1 above)
Comment (lambdageek) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:540]: Yea seems like a good idea (I'm not intimately familiar with our infinite trampolines code, but it seems workable).

So the new loop would be:
- `vm_allocate(size)` returning `addr`
- set `tpage = addr+size`
- `vm_remap(&tpage, VM_FLAGS_FIXED | VM_FLAGS_OVERWRITE)`
- if success, we're done; if failure, `vm_deallocate(addr)` and repeat

?

Comment (filipnavara) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:540]: Yep
