### PR TITLE
JIT: Check for potential store-to-load forwarding before reordering ldr -> ldp

### LINKED ISSUE #93401: [Perf] Linux/arm64: 8 Regressions on 10/7/2023 2:03:18 PM
### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 20.04
Queue | AmpereUbuntu
Baseline | [f55549222e4dc1469190caa56e03361ee46208ca](https://github.com/dotnet/runtime/commit/f55549222e4dc1469190caa56e03361ee46208ca)
Compare | [551a4db7917df8c321867d47ce028c726106a3c2](https://github.com/dotnet/runtime/commit/551a4db7917df8c321867d47ce028c726106a3c2)
Diff | [Diff](https://github.com/dotnet/runtime/compare/f55549222e4dc1469190caa56e03361ee46208ca...551a4db7917df8c321867d47ce028c726106a3c2)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.IterateFor&lt;String&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[ReadOnlySpan - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 20.04/System.Collections.IterateFor(String).ReadOnlySpan(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Iterate/IterateFor.cs#L59-#L68>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UXW/TMBR9r8R/8FsSSLMk7da1kEldERpCY9AU8TBNyE3uGg9/RLZDW4T47dykpW06ivISX59zfM/JjTlYkhZK249UgCEJyanFZ87BnVbycwUVjIzVTC580qxq3LbikfuO85XJXC1NEIXBWOQX/SAOb+LgbsmDT6AfHZ84Sya7q4t+l4rc8f9BiIY3UTBjC9DPKExa4DXpy7yStkLtsB+MtUDWXyhHKK0rqF+ChkN0XKObM9ry/IR8dHmaEF22KYc2dg0FabU3sOnKYIVmcEhJQf9A8baP5bGPzsPrzi1Q5IMAaU3nF1kWuEGuK8bzKZSKJAlxcmUl2DONBphAVgt1ranMigan4dGcFUBzcyYok0fAsc4KZiGzeFoDR68OUfrEbtPoXmIGppmfZi9dGwsimCjOkcGUNMF7C5paeKf0m7SZnKtgip3cSb5OSyrdlP2EETmPYm+vidM3UfKRLSqk1ir3zkSJkvFmdatycB5I8ps4liE8d178j4mlDxj+liFYplW7+4nC/EDPVLl9a8czw2hTix+GXNU/CNRRu3EY97rhoBvFs3Aw6g9HODz93nB4Pui/CsNRGHooYiohqEZ/hOrFN0FXbiNYp+WTlx6Zr49O8Hdp+rWT5p9DnVKrJ4zzGXgKpuI20dh17h442dTHOGd0gUo9r6X2pJgk3zGRhEkJ+vAGUPIQqEHmuF/7zQqqLVkyWxDXgGZgkt2F4JNVpnglZHLc33pTN8mmIQRaZjkkzluMEed+vV3WFOJK49U1U3JmE7oC4/0BB0O61KAEAAA=>)</li></ul> | 205.40 ns | 222.33 ns | 1.08 | 0.03 | False | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/10_12_2023/refs/heads/main_arm64_ubuntu%2020.04_Regression/System.Collections.IterateFor%28String%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.IterateFor&lt;String&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-40e5850e-9a75-418a-b15b-3da8dbda15558c1e588bad54811a1/b719c70b-e555-4a44-b1e6-f23ed32e466e.zip?sv=2021-08-06&se=2023-11-04T23%3A13%3A21Z&sr=c&sp=rl&sig=eU0LMAKyhygG7GcyHqvQqBnHIyhnMnmvsKUx3bTsYbM%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c97c2395-2db0-4754-8471-8a4f125317e3dd2c5426ba444bfb5/8ac716ed-45f7-4745-810c-a61589d4fccf.zip?sv=2021-08-06&se=2023-11-07T04%3A07%3A00Z&sr=c&sp=rl&sig=fDFjpNtQpLtJvryDIHxoiW5ZRo77BKUmDcXRRv6k4II%3D>)
#### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 222.32651915631124 > 215.6400041349606.
IsChangePoint: Marked as a change because one of 5/19/2023 4:22:12 AM, 9/23/2023 7:05:34 AM, 10/6/2023 9:14:38 AM, 10/11/2023 11:44:03 AM falls between 10/2/2023 7:07:56 PM and 10/11/2023 11:44:03 AM.
IsRegressionStdDev: Marked as regression because -372.39294984996354 (T) = (0 -222.2885707448892) / Math.Sqrt((0.004433913439093746 / (12)) + (0.010203089316673741 / (6))) is less than -2.1199052992212764 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (12) + (6) - 2, .025) and -0.08250910009314494 = (205.3456832148222 - 222.2885707448892) / 205.3456832148222 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 20.04
Queue | AmpereUbuntu
Baseline | [f55549222e4dc1469190caa56e03361ee46208ca](https://github.com/dotnet/runtime/commit/f55549222e4dc1469190caa56e03361ee46208ca)
Compare | [551a4db7917df8c321867d47ce028c726106a3c2](https://github.com/dotnet/runtime/commit/551a4db7917df8c321867d47ce028c726106a3c2)
Diff | [Diff](https://github.com/dotnet/runtime/compare/f55549222e4dc1469190caa56e03361ee46208ca...551a4db7917df8c321867d47ce028c726106a3c2)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Text.Perf_Ascii

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[ToUpper_Bytes_Chars - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 20.04/System.Text.Perf_Ascii.ToUpper_Bytes_Chars(Size%3a%20128).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.Encoding/Perf.Ascii.cs#L85-#L86>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UXY+aQBR9N+l/mDegRQS06trQxLUPmzTbD2XTh83GjHCV2TIzZGao2jT97b2gVXBrwwtz7zln7jnMkIMhi0wq84ly0CQiKTX4rHKw56X4WkIJE20UExuX1KsKd6w45LFjfWMilVvtBb435elw4IX+Xeh93ubeF1BryyXWlonubjjoUp5a7j8Iwc1d4MVsA+oFhQkDeUV6WJXClKjtD7yp4sj6C80RSqsK6hegoIkOK3S9R1s+vyIfjK8TgnGb0rRxGshblGcDh6k0VmgCTcoC1A8Ub/vYXvroPL3r3ANFPnAQRnd+kW2GDXJbsjydQyFJFBErlUaA6Sk0wDiyWqhbRUWS1TgFa93LgKa6xykTF8CpSjJmIDG4Ww1HrxaR6kq3HvQsEYOuz0/dW+y1Ae7FsDO1ueVUJ4x5sXwo0Nfydm9AL2cZVdpesJ8wIUE4ds5aeOpmUqzZplTUMCn0ozWTvGB5vbqXKVhPJPpNLMMQnlqv/sfE0kcM/cjgLFGyPfVMYm6gYlkc39qxxBjpwuAHIe+riwFVxHboh/2uP+oGYeyPJoObSRB6/bfD/qjvv/H9ie87KKJLzqlCf4SqzZLTnV0LVim55LVDVvuLHdxTim7lpL5rqFMo+YzBvwDPQZe5iRROndoNJ4f6FM8X3aBS32mpPUsmyHdMJGJCgGrefCmaQAUixX7lN8FPZciWmYzYGhQDHZ1+BC7ZJTIvuYgu59sf6jo6DIRAw0wOkfUBY8Tzvj8uKwqxhXaqmi5yZiK6A+38AR25aheYBAAA>)</li></ul> | 23.88 ns | 28.56 ns | 1.20 | 0.14 | False | | |
|<ul><li>[ToLower_Bytes_Chars - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 20.04/System.Text.Perf_Ascii.ToLower_Bytes_Chars(Size%3a%20128).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Text.Encoding/Perf.Ascii.cs#L76-#L77>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UXW+bMBR9j7T/4DdgIwRo2qaZmJRmD5W67iMw7aGqIgdugjtsR7YZyTTtt+9CsgTSZeIF33vO8T0HmwIMiXOpzEfKQZOIZNTgsyjAnpXiSwkljLVRTKxc0qxq3L7ikMee9Y2JTFbaC3xvwrOroRf6d6H3qSq8z6CWlkusion+5mrYpzyz3H8Qgpu7wEvYCtQLChMGipr0dVEKU6K2P/QmiiPrL7RAKK0rqL8GBW10WKObPbryxRn5YHSeEIy6lLaNw0BeXB4N7KbSWKEptCkxqB8o3vVRnfroPb3tPQBFPnAQRvd+kSrHBrktWZHNYC1JFBErk0aAGSg0wDiyOqhbRUWaNzgFSz3IgWZ6wCkTJ8CJSnNmIDW4WwNHrxaR6ky3GfQokYBuzk/Ti7faAPcS2JjG3HyiU8a8RH6QFaj57daAnk9zqrQds58wJkE4co5aeOqmUizZqlTUMCn0ozWVfM2KZvUgM7CeSPSbWIYhPLNe/Y+JpXsMfc/gLFWyO/VUYm6gErnev3VjSTDS2OAHIe/qiwF1xHbohxd9/7ofhIl/PR7ejIPQu7wcDUN/9Mb3x77voIguOacK/RGqVnNON3YjWKfkktcOWWxPdnAPKbq1k+auoc5ayWcM/gV4BrosTKRw6sxuOdnVJ3i+6AqVLpyO2rNkgnzHRCImBKj2zZeiDVQgMuzXflP8VIZUzOTE1qAY6OjwI3DJJpVFyUV0Ot92V9fRbiAEGmYKiKz3GCOe9+1+WVOILbRT1/S6YCaiG9DOH7BkJWaYBAAA>)</li></ul> | 23.94 ns | 28.02 ns | 1.17 | 0.15 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/10_12_2023/refs/heads/main_arm64_ubuntu%2020.04_Regression/System.Text.Perf_Ascii.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Text.Perf_Ascii*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-40e5850e-9a75-418a-b15b-3da8dbda15558c1e588bad54811a1/b719c70b-e555-4a44-b1e6-f23ed32e466e.zip?sv=2021-08-06&se=2023-11-04T23%3A13%3A21Z&sr=c&sp=rl&sig=eU0LMAKyhygG7GcyHqvQqBnHIyhnMnmvsKUx3bTsYbM%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c97c2395-2db0-4754-8471-8a4f125317e3dd2c5426ba444bfb5/8ac716ed-45f7-4745-810c-a61589d4fccf.zip?sv=2021-08-06&se=2023-11-07T04%3A07%3A00Z&sr=c&sp=rl&sig=fDFjpNtQpLtJvryDIHxoiW5ZRo77BKUmDcXRRv6k4II%3D>)
#### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 28.559514717492952 > 24.79856478599641.
IsChangePoint: Marked as a change because one of 5/19/2023 4:22:12 AM, 8/22/2023 6:29:15 PM, 10/6/2023 9:14:38 AM, 10/11/2023 11:44:03 AM falls between 10/2/2023 7:07:56 PM and 10/11/2023 11:44:03 AM.
IsRegressionStdDev: Marked as regression because -20.76254857027171 (T) = (0 -28.104504760503044) / Math.Sqrt((0.3645918407156724 / (12)) + (0.05786128073273915 / (6))) is less than -2.1199052992212764 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (12) + (6) - 2, .025) and -0.1734346247423125 = (23.95063531270421 - 28.104504760503044) / 23.95063531270421 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
#### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 28.019010068564185 > 24.869754563726246.
IsChangePoint: Marked as a change because one of 5/19/2023 4:22:12 AM, 8/22/2023 6:29:15 PM, 10/6/2023 9:14:38 AM, 10/11/2023 11:44:03 AM falls between 10/2/2023 7:07:56 PM and 10/11/2023 11:44:03 AM.
IsRegressionStdDev: Marked as regression because -20.25521761383546 (T) = (0 -28.24787440830941) / Math.Sqrt((0.2906103764827192 / (12)) + (0.13260424713375574 / (6))) is less than -2.1199052992212764 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (12) + (6) - 2, .025) and -0.18248282820609205 = (23.88861278532339 - 28.24787440830941) / 23.88861278532339 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 20.04
Queue | AmpereUbuntu
Baseline | [f55549222e4dc1469190caa56e03361ee46208ca](https://github.com/dotnet/runtime/commit/f55549222e4dc1469190caa56e03361ee46208ca)
Compare | [551a4db7917df8c321867d47ce028c726106a3c2](https://github.com/dotnet/runtime/commit/551a4db7917df8c321867d47ce028c726106a3c2)
Diff | [Diff](https://github.com/dotnet/runtime/compare/f55549222e4dc1469190caa56e03361ee46208ca...551a4db7917df8c321867d47ce028c726106a3c2)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Buffers.Text.Tests.Base64Tests

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[ConvertToBase64CharArray - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 20.04/System.Buffers.Text.Tests.Base64Tests.ConvertToBase64CharArray(NumberOfBytes%3a%201000).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Buffers/Base64Tests.cs#L49-#L50>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1U0W7aMBR9R9o/+C1hC6lDWWmZMgnYQ6Wp7VYy7aGqJpNciLvYRtf2gGnat+8msJbQdUJC8fU5x/ecG6cCx2alQXctFFiWskI4+s0rCG+9/uzBw8g6lHoZsWZV4/aVLrvrBF+lLszaxgmPx6o4G8R9ftmPb9ZV/AlwEUQsWEvd25wNekIVQfQPQnJxmcSZXAI+o0jtoKpJX+ZeO0/afBCPURHrL7QiqKgrpL8ChEN0v0Y3Z7Tlqxfkk/OXCcl5m3Jo47GheOafDOy6slQRORxSZoA/SLztY33so3P/rnMFgvigQDvb+cXWJW2wiZdVcQsrw9KUBYVxGtwJkgGpiNVCTVDovGxwCAt7UoIo7IkSUh8Bx5iX0kHu6LQGTl4DZvCF3abRJ4kMbPP+NHuzrXWg4olfLABtnMHG0Z91Np4IC2eD3fPUaMrAZWZXnJYCx4hiG157NQe8WUy2DuyIJZzz7tNJ9E4ScyGXHoWTRtu7YGrUSlbN6soUENyz9DcLnCR4Ebz6H5NKH2kke4aSOZq2p6mhVAEzs9o/tUPLKPCZo3Gx9/W1gXoAYZ/3T3t82Ev6GR+OBhej5G3Mh4OL8yF/w/mI3JCI9UoJlD+BCVx+U2ITNoJ1hhF73WXz7dEJ0WPGUe2kuYmks0LzQGN5Br4F6yuXInVdhAdOdvUxJS+WpHTabak9GKnZd0oklVoDHn4XjD4EIuiC9mu/OQ3OsbV0JQstoASbPn4mIrbJTeWVTo/72+7qNt01REAnXQVp8IFipNuw3S9rCgu17dY1u6qkS8UGbPcPzO25jLYEAAA=>)</li></ul> | 427.30 ns | 530.37 ns | 1.24 | 0.08 | False | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/10_12_2023/refs/heads/main_arm64_ubuntu%2020.04_Regression/System.Buffers.Text.Tests.Base64Tests.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Buffers.Text.Tests.Base64Tests*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-40e5850e-9a75-418a-b15b-3da8dbda15558c1e588bad54811a1/b719c70b-e555-4a44-b1e6-f23ed32e466e.zip?sv=2021-08-06&se=2023-11-04T23%3A13%3A21Z&sr=c&sp=rl&sig=eU0LMAKyhygG7GcyHqvQqBnHIyhnMnmvsKUx3bTsYbM%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c97c2395-2db0-4754-8471-8a4f125317e3dd2c5426ba444bfb5/8ac716ed-45f7-4745-810c-a61589d4fccf.zip?sv=2021-08-06&se=2023-11-07T04%3A07%3A00Z&sr=c&sp=rl&sig=fDFjpNtQpLtJvryDIHxoiW5ZRo77BKUmDcXRRv6k4II%3D>)
#### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 530.3676104438226 > 447.5848694018119.
IsChangePoint: Marked as a change because one of 4/12/2023 8:39:35 PM, 4/28/2023 1:33:49 PM, 5/3/2023 7:05:50 AM, 7/1/2023 8:07:46 AM, 7/17/2023 4:07:27 PM, 8/4/2023 10:42:53 AM, 8/22/2023 6:29:15 PM, 10/6/2023 9:14:38 AM, 10/11/2023 11:44:03 AM falls between 10/2/2023 7:07:56 PM and 10/11/2023 11:44:03 AM.
IsRegressionStdDev: Marked as regression because -51.53911793942635 (T) = (0 -525.548318232403) / Math.Sqrt((21.142287272695157 / (12)) + (13.333299949151087 / (6))) is less than -2.1199052992212764 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (12) + (6) - 2, .025) and -0.24338488874057676 = (422.6754909050972 - 525.548318232403) / 422.6754909050972 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 20.04
Queue | AmpereUbuntu
Baseline | [f55549222e4dc1469190caa56e03361ee46208ca](https://github.com/dotnet/runtime/commit/f55549222e4dc1469190caa56e03361ee46208ca)
Compare | [551a4db7917df8c321867d47ce028c726106a3c2](https://github.com/dotnet/runtime/commit/551a4db7917df8c321867d47ce028c726106a3c2)
Diff | [Diff](https://github.com/dotnet/runtime/compare/f55549222e4dc1469190caa56e03361ee46208ca...551a4db7917df8c321867d47ce028c726106a3c2)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.CreateAddAndClear&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[List - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 20.04/System.Collections.CreateAddAndClear(Int32).List(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/CreateAddAndClear.cs#L54-#L64>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UXW/aMBR9R9p/8FuSLaRJYFDYUomyh05b9wFMe6iqycS3xJ0/kO0MmKb99t0EBoSOKS/xvecc33NiR4Aj00Ib94FKsCQjjDp85gL8Sak+l1DC0DrD1SIk9arC7SoBuWt5X7liemWjJI5GkvW6URrfpNHHlYg+gXnwQuKtuGqve902lcwL/0FIBjdJNOMLME8oXDkQFenLvFSuRO24G42MRNZfqEAorSqovwQDx+i0Qtd7NOXFGfnk8jwhuWxSjm3sB4qm5cHAdiqLFZrDMWUK5geKN32sTn207l+1boEiHyQoZ1u/yKrABrkuuWATWGqSZcRj2ilwFwYNcImsBuraUJUXNc7Ag70ogDJ7ISlXJ8CRyQvuIHe4Ww1Hrx7R5ky3HvQgMQNbn5+6N91YBzIaayGQwbWy0dgAdTBibKTYWAA1r98q10mvovfcOn/Kf8KQvEzS4KCIZ2+s1QNflIbWGnfeWMslF/XqVjPw7kn2m3iOI5x5z/7HxNI7jH7HkDw3ujn7WGN6YGZ6uXtrhjPDYKcOPwu5qq4HVEH7aZx22nG/naSzuD/sDoZJP+r1O2k/HbyI42EcByhiSympQX+EmsU3Sdd+LVhlFZLnAZlvTnYI91mGlZP6xqHO0uhHDPMJeAK2FC4zODXzj5xs6yM8ZXSBSp2gofaouSLfMZGMKwXm+P5rdQw0oBj2K795QY0jK+4K4lswHGy2/x2EZJ1rUUqVnc632dZtth0IgY47AZn3BmPEU7/ZLSsK8ZUNqppdCu4yugYb/AH8AfDFngQAAA==>)</li></ul> | 1.50 μs | 1.80 μs | 1.20 | 0.24 | False | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/10_12_2023/refs/heads/main_arm64_ubuntu%2020.04_Regression/System.Collections.CreateAddAndClear%28Int32%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.CreateAddAndClear&lt;Int32&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-40e5850e-9a75-418a-b15b-3da8dbda15558c1e588bad54811a1/b719c70b-e555-4a44-b1e6-f23ed32e466e.zip?sv=2021-08-06&se=2023-11-04T23%3A13%3A21Z&sr=c&sp=rl&sig=eU0LMAKyhygG7GcyHqvQqBnHIyhnMnmvsKUx3bTsYbM%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c97c2395-2db0-4754-8471-8a4f125317e3dd2c5426ba444bfb5/8ac716ed-45f7-4745-810c-a61589d4fccf.zip?sv=2021-08-06&se=2023-11-07T04%3A07%3A00Z&sr=c&sp=rl&sig=fDFjpNtQpLtJvryDIHxoiW5ZRo77BKUmDcXRRv6k4II%3D>)
#### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 1.7977876246594005 > 1.5936733124485132.
IsChangePoint: Marked as a change because one of 5/19/2023 4:22:12 AM, 10/6/2023 9:14:38 AM, 10/11/2023 11:44:03 AM falls between 10/2/2023 7:07:56 PM and 10/11/2023 11:44:03 AM.
IsRegressionStdDev: Marked as regression because -10.988586748442112 (T) = (0 -1838.0158013387618) / Math.Sqrt((3446.231724137695 / (12)) + (2498.4499069713015 / (6))) is less than -2.1199052992212764 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (12) + (6) - 2, .025) and -0.1884698700010806 = (1546.5396706582815 - 1838.0158013387618) / 1546.5396706582815 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 20.04
Queue | AmpereUbuntu
Baseline | [f55549222e4dc1469190caa56e03361ee46208ca](https://github.com/dotnet/runtime/commit/f55549222e4dc1469190caa56e03361ee46208ca)
Compare | [551a4db7917df8c321867d47ce028c726106a3c2](https://github.com/dotnet/runtime/commit/551a4db7917df8c321867d47ce028c726106a3c2)
Diff | [Diff](https://github.com/dotnet/runtime/compare/f55549222e4dc1469190caa56e03361ee46208ca...551a4db7917df8c321867d47ce028c726106a3c2)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.Perf_Frozen&lt;NotKnownComparable&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[Contains_True - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 20.04/System.Collections.Perf_Frozen(NotKnownComparable).Contains_True(Count%3a%204).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Frozen/Perf_Frozen.cs#L96-#L105>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UXW/TMBR9r8R/8FsSSLMkrfZRyKRuCE2aNqAt4mGaJi+5azz8UdkOaSfEb+faLWvTMZSX+Pqcc++5vjYHS6a10vaaCjCkIBW1+N1zCCeN/NpAAyNjNZPzmPiVw20iEbnpBd+ZrFRrkixNxqI6HCZ5epEnn1uefAH9EMQkaJnsLw+HfSqqIP4HITu5yJIZm4N+QWHSAnekb/eNtA1qp8NkrAWy/kI5QqmLoP4CNOyic4f2Obry/BX57Ph1QnbcpezaeC4omTZbA+uqDEZoCbuUKeifKN710e776N2+710BRT4IkNb0fpG2xg1y1jBeTWChSFGQoFJWgj3QaIAJZHVQZ5rKsvY4DQ/moAZamQNBmdwDjnVZMwulxWwejl4DovQru77QrcQMjJ8fvzddGQsiOVecI4MpabzHu09aPYH8cK3spVStPFdiQbUbtFPESos1mbuZbiA8V+hlRIbRNgGOImIe2LzR1EveBI7PuF9dqQqCW1L8JoFlCK+CN/9jYugST2LDEKzUqmvFFwB6phabv26vZtjnqcVTIqfutoDre5in+aCfHvWzfJYejYYnozzF0RjkR9nwXZqO0jRCEdMIQTV7AkL1/E7QZegFXeti8jYi96u9DPFza2PnxF9A1Flo9Yi9fQGegGm4LTRWXYU7TtbxMQ4dnaPSIOqoPSomyQ/sSMGkBL37HCi5C9QgK9x3fsuaaktaZmsSGtAMTPH8OsRkWSreCFns17dax02xLgiBllkORfAR24iXYLVZOgoJpYlczCw4swVdgon+ABC9SOatBAAA>)</li></ul> | 13.49 ns | 15.78 ns | 1.17 | 0.02 | True | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/10_12_2023/refs/heads/main_arm64_ubuntu%2020.04_Regression/System.Collections.Perf_Frozen%28NotKnownComparable%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.Perf_Frozen&lt;NotKnownComparable&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-40e5850e-9a75-418a-b15b-3da8dbda15558c1e588bad54811a1/b719c70b-e555-4a44-b1e6-f23ed32e466e.zip?sv=2021-08-06&se=2023-11-04T23%3A13%3A21Z&sr=c&sp=rl&sig=eU0LMAKyhygG7GcyHqvQqBnHIyhnMnmvsKUx3bTsYbM%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c97c2395-2db0-4754-8471-8a4f125317e3dd2c5426ba444bfb5/8ac716ed-45f7-4745-810c-a61589d4fccf.zip?sv=2021-08-06&se=2023-11-07T04%3A07%3A00Z&sr=c&sp=rl&sig=fDFjpNtQpLtJvryDIHxoiW5ZRo77BKUmDcXRRv6k4II%3D>)
#### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 15.776818896170987 > 14.160815293970957.
IsChangePoint: Marked as a change because one of 10/6/2023 9:14:38 AM, 10/11/2023 11:44:03 AM falls between 10/2/2023 7:07:56 PM and 10/11/2023 11:44:03 AM.
IsRegressionStdDev: Marked as regression because -59.943852744772315 (T) = (0 -15.728146954519806) / Math.Sqrt((0.002666869030084915 / (12)) + (0.00715756535636858 / (6))) is less than -2.1199052992212764 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (12) + (6) - 2, .025) and -0.1673708091342549 = (13.473137097015565 - 15.728146954519806) / 13.473137097015565 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked as regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 20.04
Queue | AmpereUbuntu
Baseline | [f55549222e4dc1469190caa56e03361ee46208ca](https://github.com/dotnet/runtime/commit/f55549222e4dc1469190caa56e03361ee46208ca)
Compare | [551a4db7917df8c321867d47ce028c726106a3c2](https://github.com/dotnet/runtime/commit/551a4db7917df8c321867d47ce028c726106a3c2)
Diff | [Diff](https://github.com/dotnet/runtime/compare/f55549222e4dc1469190caa56e03361ee46208ca...551a4db7917df8c321867d47ce028c726106a3c2)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Memory.Span&lt;Char&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[IndexOfAnyThreeValues - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 20.04/System.Memory.Span(Char).IndexOfAnyThreeValues(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Memory/Span.cs#L84-#L85>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UXW/TMBR9r8R/8FsSSLMk6z5ayKSuPAyhMWgKPEwT8pLbxiO2o2uHtgjx27lJS9d0DPWlvj7n+J7j65RgWVpotB+4BMMSlnNLv/sS3GmtPtVQw8hYFGrhs3bV4LYVj932nK9C5XppgigMxjI/HQRxeBUHN8sy+Ag4d3zmLIXqr04HfS5zx/8HIRpeRcFMLACfUISyUDakz/e1sjVph4NgjJJYf6ElQXlTIf0KEPbRcYNuz+jKl8/IR+fPE6LzLmXfxq6hIK0fDWy6MlThGexTUsAfJN71sTz00bt73bsGTnyQoKzp/WLLgjbYZS3KfAqVZknCnFxbBfYIyYCQxOqgLpGrrGhxCHNzVADPzZHkQh0Ax5gVwkJm6bQWTl4dpvGZ3bbRR4kZmHZ+2r10bSzI4BqkxnWQVly9mRQcL4J3KofVzXys1rMCAb7wsgbjpuInjNhJFHuPejR5E63mYlEjt0Irc+tMtKxE2a6udQ7OHUt+M8cKgufOi/8xqfSegt8ypMhQdzufaMoOcKar7b9uNDOKNbV0KeyieRzQxOzGYXzcD8/6UTwLz0aD4Sg+Cc6Gg8H58ORVGI7C0CMRU0vJkfwxjotvkq/cVrBJymcvPXa/PjjB3yXpN07a90Y6FeoHCv8JeAqmLm2C1HXu7jnZ1Mc0Y3xBSsdeR+1BC8W+UyKJUApw//VrtQ9EoAtD1vjN6AItWwpbMNcACjDJ7mPgs1Wmy1qq5LC/9aZukk1DBLTClpA4bylGmvn1dtlQmKuM19RMVQqb8BUY7w84jaYgnAQAAA==>)</li></ul> | 44.00 ns | 49.23 ns | 1.12 | 0.10 | False | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/10_12_2023/refs/heads/main_arm64_ubuntu%2020.04_Regression/System.Memory.Span%28Char%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Memory.Span&lt;Char&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-40e5850e-9a75-418a-b15b-3da8dbda15558c1e588bad54811a1/b719c70b-e555-4a44-b1e6-f23ed32e466e.zip?sv=2021-08-06&se=2023-11-04T23%3A13%3A21Z&sr=c&sp=rl&sig=eU0LMAKyhygG7GcyHqvQqBnHIyhnMnmvsKUx3bTsYbM%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c97c2395-2db0-4754-8471-8a4f125317e3dd2c5426ba444bfb5/8ac716ed-45f7-4745-810c-a61589d4fccf.zip?sv=2021-08-06&se=2023-11-07T04%3A07%3A00Z&sr=c&sp=rl&sig=fDFjpNtQpLtJvryDIHxoiW5ZRo77BKUmDcXRRv6k4II%3D>)
#### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 49.22978510694759 > 46.15877453468914.
IsChangePoint: Marked as a change because one of 4/28/2023 1:33:49 PM, 5/3/2023 7:05:50 AM, 7/1/2023 8:07:46 AM, 7/17/2023 4:07:27 PM, 8/5/2023 6:15:42 AM, 8/22/2023 6:29:15 PM, 10/6/2023 9:14:38 AM, 10/11/2023 11:44:03 AM falls between 10/2/2023 7:07:56 PM and 10/11/2023 11:44:03 AM.
IsRegressionStdDev: Marked as regression because -14.473174356749167 (T) = (0 -49.362602321879855) / Math.Sqrt((0.10814897384925021 / (12)) + (0.7497474708297018 / (6))) is less than -2.1199052992212764 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (12) + (6) - 2, .025) and -0.12021896215335026 = (44.06513725405271 - 49.362602321879855) / 44.06513725405271 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 20.04
Queue | AmpereUbuntu
Baseline | [f55549222e4dc1469190caa56e03361ee46208ca](https://github.com/dotnet/runtime/commit/f55549222e4dc1469190caa56e03361ee46208ca)
Compare | [551a4db7917df8c321867d47ce028c726106a3c2](https://github.com/dotnet/runtime/commit/551a4db7917df8c321867d47ce028c726106a3c2)
Diff | [Diff](https://github.com/dotnet/runtime/compare/f55549222e4dc1469190caa56e03361ee46208ca...551a4db7917df8c321867d47ce028c726106a3c2)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Collections.AddGivenSize&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[List - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 20.04/System.Collections.AddGivenSize(Int32).List(Size%3a%20512).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Add/AddGivenSize.cs#L28-#L36>)</li><li>[📈 - ADX Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACn1UXW/TMBR9r8R/8FsSSNMkDe1WyKSuSAzB+FiLeJgm5MW3jYc/KttZW4T47dykpWs6hvIS33vO8T0ndgQ4Mi21cR+pBEtywqjD51aAf1WpLxVUMLLOcLUISbOqcbtKQK473jeumF7ZKImjsWSDLErjizT6tBLRZzBzLyTeiqvuepB1qWRe+A9CcnqRRDO+APOIwpUDUZO+3lbKVagdZ9HYSGT9hQqE0rqC+kswcIhOa3SzR1tePCGfnDxNSE7alEMb+4GiafVgYDuVxQot4JAyBXOP4m0fq2MfnZtXnUugyAcJytnOL7IqsUHOKy7YFSw1yXPiMe0UuJ5BA1wiq4U6N1QVZYMzMLe9EiizPUm5OgKOTVFyB4XD3Ro4evWINk90m0EfJGZgm/PT9KYb60BGEy0EMrhWNhoz9pbfg5ryn/D6nXL99Cz6wK3z68KIvEzS4EEMj91EqzlfVIY29GtvouWSi2Z1qRl4NyT/TTzHEc68Z/9jYuk9pr5jSF4Y3R57ojE4MDO93L21c5lhplOHX4Sc1TcD6oz9NE773XjYTdJZPBxlp6P0JEr7w2yQZS/ieBTHAYrYSkpq0B+hZvFd0rXfCNYxheR5QG43RzuE+xjD2klz2VBnafQd5vgIfAW2Ei43ODXzD5xs62M8YHSBSv2gpXanuSI/MJGcKwXm8OprdQg0oBj2a79FSY0jK+5K4lswHGy+/xOEZF1oUUmVH8+32dZtvh0IgY47Abn3BmPEA7/ZLWsK8ZUN6ppdCu5yugYb/AGOZvTJmQQAAA==>)</li></ul> | 1.44 μs | 1.66 μs | 1.15 | 0.35 | False | | |

graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/10_12_2023/refs/heads/main_arm64_ubuntu%2020.04_Regression/System.Collections.AddGivenSize%28Int32%29.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Collections.AddGivenSize&lt;Int32&gt;*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-40e5850e-9a75-418a-b15b-3da8dbda15558c1e588bad54811a1/b719c70b-e555-4a44-b1e6-f23ed32e466e.zip?sv=2021-08-06&se=2023-11-04T23%3A13%3A21Z&sr=c&sp=rl&sig=eU0LMAKyhygG7GcyHqvQqBnHIyhnMnmvsKUx3bTsYbM%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c97c2395-2db0-4754-8471-8a4f125317e3dd2c5426ba444bfb5/8ac716ed-45f7-4745-810c-a61589d4fccf.zip?sv=2021-08-06&se=2023-11-07T04%3A07%3A00Z&sr=c&sp=rl&sig=fDFjpNtQpLtJvryDIHxoiW5ZRo77BKUmDcXRRv6k4II%3D>)
#### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 1.66042285032892 > 1.4533978942651908.
IsChangePoint: Marked as a change because one of 7/18/2023 9:59:03 AM, 10/6/2023 9:14:38 AM, 10/11/2023 11:44:03 AM falls between 10/2/2023 7:07:56 PM and 10/11/2023 11:44:03 AM.
IsRegressionStdDev: Marked as regression because -15.426483125143072 (T) = (0 -1658.5832139364875) / Math.Sqrt((4077.5324724249035 / (12)) + (116.7192038612997 / (6))) is less than -2.1199052992212764 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (12) + (6) - 2, .025) and -0.21401884300283375 = (1366.192315297215 - 1658.5832139364875) / 1366.192315297215 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### LINKED ISSUE #101437: List Add is way slower (almost 3 times) in `net9.0 preview 3` than with `net8.0`
With the latest preview 3 (net9) there seems to be a major performance regression on MacOS 14.4 (M2 Pro) with lists. Given that they are one of the most used types, it should receive special treatment.

## Benchmark

```csharp
[Benchmark]
public List<int> ListAdd10000()
{
    var list = new List<int>();
    for (var i = 0; i < 10_000; i++)
    {
        list.Add(i);
    }

    return list;
}

[Benchmark]
public List<int> ListAdd10000PreAlloc()
{
    var list = new List<int>(10_000);
    for (var i = 0; i < 10_000; i++)
    {
        list.Add(i);
    }

    return list;
}
```

Results:
```no-class
BenchmarkDotNet v0.13.12, macOS Sonoma 14.4.1 (23E224) [Darwin 23.4.0]
Apple M2 Pro, 1 CPU, 12 logical and 12 physical cores
.NET SDK 9.0.100-preview.3.24204.13
  [Host]   : .NET 9.0.0 (9.0.24.17209), Arm64 RyuJIT AdvSIMD
  .NET 8.0 : .NET 8.0.2 (8.0.224.6711), Arm64 RyuJIT AdvSIMD
  .NET 9.0 : .NET 9.0.0 (9.0.24.17209), Arm64 RyuJIT AdvSIMD


| Method               | Runtime  | Mean      | Error     | StdDev    | Ratio | 
|--------------------- |--------- |----------:|----------:|----------:|------:|-
| ListAdd10000         | .NET 8.0 |  9.739 us | 0.0236 us | 0.0209 us |  1.00 | 
| ListAdd10000         | .NET 9.0 | 25.646 us | 0.1531 us | 0.1432 us |  2.63 | 
|                      |          |           |           |           |       | 
| ListAdd10000PreAlloc | .NET 8.0 |  6.701 us | 0.0175 us | 0.0146 us |  1.00 | 
| ListAdd10000PreAlloc | .NET 9.0 | 22.562 us | 0.1429 us | 0.1336 us |  3.37 |
```

Interestingly even the pre-allocated list is comparably slow.

## `dotnet --info` 
<details>
<summary>Output</summary>
dotnet --info
.NET SDK:
 Version:           9.0.100-preview.3.24204.13
 Commit:            81f61d8290
 Workload version:  9.0.100-manifests.77bb7ba9
 MSBuild version:   17.11.0-preview-24178-16+7ca3c98fa

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/9.0.100-preview.3.24204.13/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.3.24172.9
  Architecture: arm64
  Commit:       9e6ba1f68c

.NET SDKs installed:
  6.0.417 [/usr/local/share/dotnet/sdk]
  7.0.306 [/usr/local/share/dotnet/sdk]
  7.0.404 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]
  8.0.101 [/usr/local/share/dotnet/sdk]
  8.0.200 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.2.24121.2 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.2.24157.14 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.3.24204.13 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.2.24120.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.2.24128.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.3.24172.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.2.24120.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.2.24128.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24172.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</code>
</details>

### PR DESCRIPTION
**Pull request by jakobbotsch**
Very targeted fix for #93401 and #101437: before reordering two indirections, check if there is a potential store in the same loop that looks like it could end up being a candidate for store-to-load forwarding into one of those indirections. Some hardware does not handle store-to-load forwarding with the same fidelity when `stp`/`ldp` is involved compared to multiple `str`/`ldr`.

The detection is done by a graph walk that starts at the indirection and then walks backwards until it finds a store that would reach the indirection. The walk is limited to stay within the same loop as the indirections, and also limited by a budget of 100 nodes visited (for a large loop we expect this to not be as important).

If we detect the situation then avoid doing the reordering.

Not so happy with the complexity. I would probably rather disable this transformation entirely, but this is much more surgical.

Fix #93401 
Fix #101437

### CODE REVIEW

**Comment by jakobbotsch** [comment]
@EgorBot -arm64 --disasm --envvars "DOTNET_JitDisasm:List" 

```csharp
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using BenchmarkDotNet.Attributes;

namespace System.Collections
{
    public class AddGivenSize
    {
        private int[] _uniqueValues;

        public int Size = 512;

        [GlobalSetup]
        public void Setup() => _uniqueValues = Enumerable.Range(0, Size).ToArray();

        [Benchmark]
        public List<int> List()
        {
            var collection = new List<int>(Size);
            var uniqueValues = _uniqueValues;
            for (int i = 0; i < uniqueValues.Length; i++)
                collection.Add(uniqueValues[i]);
            return collection;
        }
    }
}
```

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @EgorBo @AndyAyersMS 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=760928&view=ms.vss-build-web.run-extensions-tab). Regressions as one would expect. I had feared TP regressions would be bad, but apparently not so.

File: src/coreclr/jit/lower.cpp [hunk 1]
```diff
@@ -9565,6 +9586,183 @@ bool Lowering::TryMakeIndirsAdjacent(GenTreeIndir* prevIndir, GenTreeIndir* indi
...
+        for (BasicBlock* pred : block->PredBlocks())
+        {
+            if (loop->ContainsBlock(pred) && BitVecOps::TryAddElemD(&traits, visited, pred->bbPostorderNum))
+            {
+                stack.Push(pred);
+            }
+        }
+    };
+
+    pushPreds(m_block);
```
Comment (AndyAyersMS) [inline src/coreclr/jit/lower.cpp:9732]: Lower runs in linear block order, is there any concern that we might not have yet lowered some of thedr preds?

**Review by AndyAyersMS — APPROVED** [review]
I suspect this only really matters for small loops where the loads are on the critical path, so a very small budget might suffice.

File: src/coreclr/jit/lower.cpp (hunk 1 above)
Comment (EgorBo) [reply src/coreclr/jit/lower.cpp:9732]: I presume it's not important since it's just a heuritics and STORIND for primitives look generally the same before & after lower (except the addressing modes)

**Review by EgorBo — APPROVED** [review]

File: src/coreclr/jit/lower.cpp (hunk 1 above)
Comment (jakobbotsch) [reply src/coreclr/jit/lower.cpp:9732]: Yeah, I don't think there is a concern there. `gtPeelOffsets` that this is using works both on pre and post lowered forms of address modes.
